### ISSUE TITLE
windows: No panic for cgo crashes 

### ISSUE THREAD

**Issue by sparkkoori** [golang/go#30737]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> windows/amd64</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\sparkkoori\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\sparkkoori\code
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\sparkkoori\AppData\Local\Temp\go-build334970126=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
Run:
```
package main

/*
void crash(){ int* p = 0; *p=1; }
*/
import "C"

func main() {
	C.crash()
	println("Oh! No crash!")
}

```

### What did you expect to see?
Panic. 

### What did you see instead?
Nothing.

**Comment by Allenyn** [comment]
cgo too hard to use.
Can we improve it. Enhance the ability of interaction for go with c .

**Comment by julieqiu** [comment]
cc: @alexbrainman @bradfitz

**Comment by polarina** [comment]
There is a hard assumption that C code is well-behaved.

Writing through a null pointer in C is undefined behaviour. The Go runtime makes no attempts to map undefined behaviour in C to Go panics, it'd be a futile attempt.

**Comment by ianlancetaylor** [comment]
What does a C program with the same code do?  Does it crash?

**Comment by sparkkoori** [comment]
@ianlancetaylor 
Yes, it does crash,  and nothing prints.

@polarina 
Thanks for your explaining.

But raising a SIGSEGV also doesn't make the Go runtime panic.
```
package main

/*
#include <signal.h>
void crash(){ raise(SIGSEGV); }
*/
import "C"

func main() {
	C.crash()
	println("Oh! No crash!")
}
```

From document of package os/signal:

> …… In general, except as discussed below, Go programs will convert a synchronous signal into a run-time panic.

> If the non-Go code installs a signal handler for any of the synchronous signals (SIGBUS, SIGFPE, SIGSEGV), then it should record the existing Go signal handler. If those signals occur while executing Go code, it should invoke the Go signal handler (whether the signal occurs while executing Go code can be determined by looking at the PC passed to the signal handler). Otherwise some Go run-time panics will not occur as expected.

If SIGSEGV can't trigger a panic, what can be?

**Comment by ianlancetaylor** [comment]
I really don't know what `raise(SIGSEGV)` does on Windows.

The os/signal package doc start by saying that they are mostly for Unix.  You are quoting from the Unix docs for os/signal, not the (very short) Windows docs.

**Comment by sparkkoori** [comment]
As the C standard library contains <signal.h> and Mingw-w64 also supports it, should the panic logic on Windows behaves the same as on Unix?

**Comment by alexbrainman** [comment]
> As the C standard library contains <signal.h> and Mingw-w64 also supports it, should the panic logic on Windows behaves the same as on Unix?

What does Mingw-w64 do with `raise(SIGSEGV)` on Windows?

Alex

**Comment by sparkkoori** [comment]
> What does Mingw-w64 do with raise(SIGSEGV) on Windows?
> 
> Alex

It is implemented in msvcrt.dll, I guess.
See [signal | Windows Docs](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/signal?view=vs-2019)

**Comment by ianlancetaylor** [comment]
If you can change the runtime package to make signals on Windows work as they do on Unix, that would be fine with me.

**Comment by sparkkoori** [comment]
I'm not really sure if it's necessary or just fine.
If it's not necessary, I think this issue should be closed.
