### ISSUE TITLE
Why go get path@version is not working

### ISSUE THREAD

**Issue by akhilravuri1** [golang/go#30734]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

I Don't know

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\rakhil\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\rakhil\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\rakhil\AppData\Local\Temp\go-build895664346=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I was trying to install the branch or version of a package in GitHub.

go get github.com/ibmdb/go_ibm_db@GoPointerFix

### What did you expect to see?

Download and the install the GoPointerFix version of go_ibm_db package from GitHub.

### What did you see instead?

go: cannot use path@version syntax in GOPATH mode

**Comment by bcmills** [comment]
See the paragraph on `GO111MODULE` in https://golang.org/cmd/go/#hdr-Preliminary_module_support.
