### ISSUE TITLE
x/sys/cpu: tests fail on nacl

### ISSUE THREAD

**Issue by tklauser** [golang/go#30733]
The `x/sys/cpu` tests fail on the nacl-386 and nacl-amd64p32 builders:

https://build.golang.org/log/cc4f59f7b4f276707e7bcdde980e0329520f99e7
https://build.golang.org/log/a0e3434d13a77b080e3f6d2d176d96bd368dc1ef

```
exit status 1
FAIL	golang.org/x/sys/cpu	0.079s
?   	golang.org/x/sys/unix	[no test files]
?   	golang.org/x/sys/windows	[no test files]
?   	golang.org/x/sys/windows/registry	[no test files]

tests failed: exit status 1
```

when executing via gomote I get

```
/usr/bin/go_nacl_amd64p32_exec: line 3: go: command not found
sed: -e expression #1, char 0: no previous regular expression
FAIL	golang.org/x/sys/cpu	0.026s
Error running run: exit status 1
```

/cc @bradfitz @ianlancetaylor

**Comment by bradfitz** [comment]
This builder config might be new. I forget whether we ever tested nacl against subrepos before. Maybe we shouldn't? Especially if we plan to delete nacl anyway (#30439).

As for gomote, perhaps its environment is slightly wrong in its config. Can you test other subrepo nacl stuff via gomote successfully?

**Comment by tklauser** [comment]
> This builder config might be new. I forget whether we ever tested nacl against subrepos before. Maybe  
we shouldn't? Especially if we plan to delete nacl anyway (#30439).

I assume it got activated by https://golang.org/cl/166218? In any case it's then probably not worth bothering about `x/sys/cpu` failing on `nacl` if it's going to be deleted.

> As for gomote, perhaps its environment is slightly wrong in its config. Can you test other subrepo nacl stuff via gomote successfully?

I didn't try any other subrepos as I just wanted to quickly see whether I can get some additional info on the failing test.
