### ISSUE TITLE
x/mobile: [doc] Go 1.10 or newer is required

### ISSUE THREAD

**Issue by bronze1man** [golang/go#30731]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.9.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
No. I do not test the latest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/a/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m9/qtbxkp6s3p96fk54rln7qhj80000gp/T/go-build131413475=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

</pre></details>

### What did you do?
./bin/gomobile build -target=android golang.org/x/mobile/example/basic

### What did you expect to see?
ask me to run gomobile init

### What did you see instead?
./bin/gomobile: Go 1.10 or newer is required

### Ps
https://github.com/golang/mobile/blob/master/README.md says it need `This is early work and installing the build system requires Go 1.5.`

https://github.com/golang/go/wiki/Mobile says `Note: You need to have Go 1.5 or above to install mobile tools. (Or at least Go 1.7.4 if using macOS Sierra)`

From the document I think go1.9 can use the lasted version of gomobile.

**Comment by karalabe** [comment]
Any particular reason for not using Go 1.12? The 1.9.x family is not supported any more by the Go team per Go's release policy, so it might make more sense to upgrade?

**Comment by bronze1man** [comment]
> Any particular reason for not using Go 1.12? The 1.9.x family is not supported any more by the Go team per Go's release policy, so it might make more sense to upgrade?

This is a document problem.I will not stay at go1.9.7 forever.
I may try to upgrade to go1.12 once I solve all the problem when I upgrade:

* go1.12 have compatibility with my code, As I use syscall.Setrlimit on darwin, go1.9.7 works, go 1.12 not. https://github.com/golang/go/issues/30401
* go 1.11 compile slow with cgo/android then go1.9 when I only change one line of one my cgo package.(1min vs 10s) (I have reported this issue, but I can not find it any more) I do not verify this again on go1.12 .

**Comment by mvdan** [comment]
This indeed sounds like a doc issue; in general, the x repos only support the latest two major Go versions. That would be 1.11 or later as of today's master branch.

**Comment by changkun** [comment]
The wiki page of Gomobile have documented that [Go 1.16 is required](https://github.com/golang/go/wiki/Mobile), the gomobile command also documented this information in [CL [346150](https://go-review.googlesource.com/c/mobile/+/346150)](https://go.dev/cl/[346150](https://go-review.googlesource.com/c/mobile/+/346150)), I would consider this issue is fixed.
