### ISSUE TITLE
x/build/cmd/coordinator: trybots on release branches sometimes didn't show Go version

### ISSUE THREAD

**Issue by dmitshur** [golang/go#30747]
There are three entries for "linux-amd64" on the trybot status page. One of them is for tip, the other for Go 1.12 release branch, and the last for Go 1.11 release branch. They used to have this information displayed in parenthesis, but not now:

<img width="412px" src="https://user-images.githubusercontent.com/1924134/54150531-150ecb00-440f-11e9-9ab3-5b401711a00a.png">

This may be related to the recent refactor. /cc @bradfitz

**Comment by bradfitz** [comment]
Weird. I don't see how I might've broken that, but I agree it's probably related to the massive https://go-review.googlesource.com/c/build/+/166218

**Comment by bradfitz** [comment]
The CL in question (type from the screenshot) was https://go-review.googlesource.com/c/tools/+/166877

**Comment by bradfitz** [comment]
I can't reproduce.

I removed the TryBot-Result vote from that CL and watched maintq:

```
$ maintq try-work
waiting:<project:"tools" branch:"master" change_id:"Idaa0bb72bf896bb8addc0004f17c3e97f8cc8b7a" commit:"8ec0247ba501b9479de91b14734dddae63441274" go_commit:"486ca37b14f56b2e125fc3afbd900a5369532043" go_commit:"4dd46a678fec26ff05b0ef1cf43aa4531dfa192a" go_commit:"8390781ca35ac5874eb5b136cfc29bb47adee94b" go_branch:"master" go_branch:"release-branch.go1.12" go_branch:"release-branch.go1.11" go_version:<major:1 minor:12 > go_version:<major:1 minor:12 > go_version:<major:1 minor:11 > > 
```

And then watched its trybots re-run, and here's what I see:

<img width="543" alt="Screen Shot 2019-03-11 at 12 39 23 PM" src="https://user-images.githubusercontent.com/2621/54152603-d66f1580-43fa-11e9-99ac-8ac894a27326.png">

So, uh, works for me?

**Comment by dmitshur** [comment]
I can't reproduce it now either:

<img width="405px" src="https://user-images.githubusercontent.com/1924134/54153762-c1a07b00-4416-11e9-9125-bb408d249d84.png">

(From https://farmer.golang.org/try?commit=8ec0247b.)

It happened only on the first run of trybots in [CL 166877](https://golang.org/cl/166877), but not 2nd or 3rd.

I'll try running trybots for the first time on a fresh CL to see if that produces different results.

**Comment by af-engineering** [comment]
Looks like the same issue as #30690

**Comment by dmitshur** [comment]
I haven't seen this since that one time, even for new CLs. I'll close this and re-open if I see it happen again.
