### ISSUE TITLE
cmd/gofmt: inconsistent blank line after package statement

### ISSUE THREAD

**Issue by dsnet** [golang/go#30741]
Using Go1.12

Consider the following two snippets:
```go
package main
import "archive/tar"
```
and
```go
package main // github.com/example/main
import "archive/tar"
```

The former formats as:
```go
package main

import "archive/tar"
```
while the latter formats as:
```go
package main // github.com/example/main
import "archive/tar"
```

The latter does not have a blank line injected when a trailing comment on the package statement exists.

This seems to be the root problem of #26290, which was not addressed in the right place, in my opinion.

**Comment by dmitshur** [comment]
This looks like a clear bug in `cmd/gofmt`. It's worth finding out whether it's a recent regression, or if it has been there for a while.

**Comment by dmitshur** [comment]
Maybe not so clear. This affects other statements too. E.g.:

```Go
package main         // comment
import "archive/tar" // comment
var _ = tar.TypeReg  // comment
func main()          {} //comment
```

**Comment by griesemer** [comment]
Yes, I'd consider this a bug. There should be a blank line between the package clause and declarations, and between different kinds of declarations.  There shouldn't be a difference just because there's a comment.

**Comment by jamdagni86** [comment]
this looks like a duplicate of #22631

**Comment by dmitshur** [comment]
It is, thanks for pointing that out @jamdagni86. Closing this as duplicate of #22631.
