### ISSUE TITLE
cmd/go: inaccurate go mod download errors

### ISSUE THREAD

**Issue by marwan-at-work** [golang/go#30743]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes 

### What did you do?

1. `go mod download -json bad/path@latest` 
2. `go mod download -json bad/path@v0.9.0`
3. `go mod download -json github.com/gomods/moduledoesnotexist@latest`
4. `go mod download -json github.com/gomods/moduledoesnotexist@v0.9.0`

### What did you expect to see?

1. Reliable code or message to say it's a bad module path
2. Reliable code or message to say it's a bad module path. 
3. Reliable code or message to say that the module does not exist.
4. Reliable code or message to say that the module does not exist.

### What did you see instead?

1. Incorrect error message: it should prioritize saying that the module path is incorrect rather than that the version invalid. In fact, `latest` is not invalid. 

```json
{
	"Path": "github.com/gomods/moduledoesnotexist",
	"Version": "latest",
	"Error": "invalid version \"latest\""
}
```

2. Correct error message, comparing against no.1 above, but it might be helpful to lock the message or introduce an error code. 

```json
{
	"Path": "bad/path",
	"Version": "v0.9.0",
	"Error": "unrecognized import path \"bad/path\" (import path does not begin with hostname)"
}
```

3. Incorrect error message same as no.1 

```json
{
	"Path": "github.com/gomods/moduledoesnotexist",
	"Version": "latest",
	"Error": "invalid version \"latest\""
}
```

4. Inaccurate error message: it should tell us that the Repository is not found, instead of "invalid revision" 

```json
{
	"Path": "github.com/gomods/moduledoesnotexist",
	"Version": "v0.9.0",
	"Error": "unknown revision v0.9.0"
}
```

cc: @jayconrod

**Comment by jayconrod** [comment]
Related #30134
