### ISSUE TITLE
Deprecate the GO111MODULE environment variable.

### ISSUE THREAD

**Issue by tariq1890** [golang/go#30750]
### What version of Go are you using (`go version`)?

1.12

What is the deprecation plan for this env var? I think it's pretty awkward that we still use GO111MODULE now that we are in Go 1.12.

**Comment by julieqiu** [comment]
For questions about Go, see https://golang.org/wiki/Questions

**Comment by tariq1890** [comment]
Sorry, this doesn't answer my question. The issue I raised is about GO111MODULE still being used in Go 1.12.

**Comment by agnivade** [comment]
The default value will be `on` in 1.13. So module mode will be enabled by default.
