### ISSUE TITLE
spec: apparent contradiction for passing of slice argument to variadic parameter

### ISSUE THREAD

**Issue by myitcv** [golang/go#30769]
```
Version of November 16, 2018
```

Section ["Passing arguments to ... parameters"](https://golang.org/ref/spec#Passing_arguments_to_..._parameters) says:

> If the final argument is assignable to a slice type []T, it may be passed unchanged as the value for a ...T parameter if the argument is followed by .... In this case no new slice is created.

Notice the use of the word "may". This appears to contradict what I understand to be the case in practice (i.e. that it _will_ be passed unchanged, for reasons of efficiency) but also the example that follows:

> ... who will have the same value as s with the same underlying array.

Notice the use of the word "will".

cc @griesemer 

FYI @mvdan @rogpeppe

**Comment by ianlancetaylor** [comment]
In this case "may" refers to the programmer, and "will" refers to the implementation.  So I think it is correct.

But I'll let @griesemer decide whether to change the wording to avoid confusion.

**Comment by mvdan** [comment]
If it serves as a data point, all three of us (Roger, Paul, and myself) found the wording a bit confusing :)

**Comment by myitcv** [comment]
Thanks @ianlancetaylor. So the key part of that first paragraph is actually the final sentence:

> In this case no new slice is created.

**Comment by griesemer** [comment]
I suggest s/may be/is/ in that sentence. That is, it would say:

 > If the final argument is assignable to a slice type []T, it is passed unchanged as the value for a ...T parameter if the argument is followed by .... In this case no new slice is created.

Does that seem clearer?

**Comment by myitcv** [comment]
@griesemer yes that seems much clearer (to us three at least!). Thank you
