### ISSUE TITLE
When HTTP response XML body contains the unicode, Decoder.Decode() occur errors

### ISSUE THREAD

**Issue by toranger** [golang/go#30765]
### What did you expect to see?
![image](https://user-images.githubusercontent.com/23206440/54187794-4a87e700-44e9-11e9-94ba-415e009abd37.png)
`err = xml.NewDecoder(resp.Body).Decode(result)`
When decode this resp it occurs  "XML syntax error on line 9: illegal character code U+0005".
How can I avoid this?

### What did you see instead?
normal analysis。

**Comment by mvdan** [comment]
You showed a piece of JSON, yet you're talking about the XML decoder, so this makes little sense.

If you still think there's a bug to be fixed, open a new issue with a full program to reproduce the problem.

**Comment by ianlancetaylor** [comment]
Let me add: please post text, not screenshots.  Thanks.
