### ISSUE TITLE
cmd/go: go version shows command not found, when I install go by go1.12.darwin-amd64.pkg or go1.11.5.darwin-amd64.pkg

### ISSUE THREAD

**Issue by AZmake** [golang/go#30762]
go version: 
go1.11.5.darwin-amd64.pkg  or go1.12.darwin-amd64.pkg

OS: 
macOS Mojave 10.14.3

I install go by go1.12.darwin-amd64.pkg or go1.11.5.darwin-amd64.pkg.

1、 I type `go version` in mac terminal, it shows `-bash: go: command not found`.

2、I type `echo $PATH`, there isn't  go path like `/usr/local/go/bin`, but the `/etc/paths.d/go` is found.

3、 I type `cd /usr/local/go/bin and ./go version`, this shows go version.

4、I set the go path `export PATH=$PATH:/usr/local/go/bin`  in `.bash_profile` and `source .bash_profile`, and then I exec steps ，shows `-bash: go: command not found` .

So, what's wrong whit me?

**Comment by agnivade** [comment]
Did you follow the steps here (https://golang.org/doc/install#macos) exactly ? 

> The package should put the /usr/local/go/bin directory in your PATH environment variable. You may need to restart any open Terminal sessions for the change to take effect.

including this one ?

**Comment by AZmake** [comment]
In fact, I don't need to add the go path to my PATH environment variable，because the pkg package had auto add it in `/etc/paths.d`, and OS will load it when I restart OS. But it takes something wrong here.

Steps 4, I had add it and restart terminal.

**Comment by AZmake** [comment]
It's a new os, I just formatted hard disk and install it. 

My another computer is update os from 10.14 to 10.14.3,  `go version` shows version info, It looks good

**Comment by AZmake** [comment]
Sorry, I don't know what's wrong, when I takes `export PATH=$PATH:/usr/local/go/bin`  to the end of the `.bash_profile` and kill the terminal , `go version` shows version info, It looks good.
