### ISSUE TITLE
testing: run subtest with its name without knowing how many parents it has

### ISSUE THREAD

**Issue by santhosh-tekuri** [golang/go#30766]
This is feature request.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.3 windows/amd64
</pre>

Usecase:

I have lots of subtests with deep hierarchy. I changed some code and would like to test my changes.
I know the test name, but does not know how nested the test is.

I would like to do: `go test -run .../mytest`

currently I try: `go test -run /mytest`
if it says no tests run, i try `go test -run //mytest`
and so on (adding one slash until it matches)

**Comment by julieqiu** [comment]
@santhosh-tekuri - are you looking for commands to run all tests, such as:

`go test ./...` 
`go test -run ''` 
 
See additional info: https://golang.org/pkg/testing/#hdr-Subtests_and_Sub_benchmarks

If not, would you be able to provide more information about this issue, including a code sample?
