### ISSUE TITLE
cmd/go: directory named go.mod defines new module but is otherwise ignored

### ISSUE THREAD

**Issue by heschik** [golang/go#30788]
### What version of Go are you using (`go version`)?

<pre>
go version devel +ee6bec958d Fri Mar 1 18:35:31 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

I have no idea how I ended up with a go.mod directory, but I did. I discovered this in `x/tools` so that's where the repro is.

```
tools/imports (master)$ git reset --hard
HEAD is now at e65039ee internal/lsp: make sure completion items are never null
tools/imports (master)$ GO111MODULE=on go list .  
golang.org/x/tools/imports
tools/imports (master)$ mkdir go.mod
tools/imports (master)$ GO111MODULE=on go list .
go: finding golang.org/x/tools/imports latest
can't load package: package golang.org/x/tools/imports: unknown import path "golang.org/x/tools/imports": cannot find module providing package golang.org/x/tools/imports
tools/imports (master)$ GO111MODULE=on go mod tidy
go: finding golang.org/x/tools/imports latest
tools/imports (master)$ echo $?
0
tools/imports (master)$ echo 'module golang.org/x/tools' > ../go.mod
tools/imports (master*)$ GO111MODULE=on go mod tidy
tools/imports (master*)$ GO111MODULE=on go mod tidy                  
[snip]
tools/imports (master*)$ cat ../go.mod
module golang.org/x/tools

go 1.12

require golang.org/x/net v0.0.0-20190311183353-d8887717615a
```

The way it's ignored by tidy is strange; I imagine there are two code paths for finding go.mod and only one of them checks whether the file is a regular file. This is particularly confusing since Git won't show you an empty directory in `git status`.

**Comment by bcmills** [comment]
> I imagine there are two code paths for finding go.mod and only one of them checks whether the file is a regular file.

Three, actually. And you're right that only one of them checks for a file vs. a directory:
https://github.com/golang/go/blob/f54b8909ac93637159e2661f25aef5e61e8cd8fc/src/cmd/go/internal/modload/init.go#L487
https://github.com/golang/go/blob/5f40351708cabe28f90500be87dbe316a2280f4a/src/cmd/go/internal/modload/search.go#L79
https://github.com/golang/go/blob/f54b8909ac93637159e2661f25aef5e61e8cd8fc/src/cmd/go/internal/modload/import.go#L236

**Comment by bcmills** [comment]
Make that four. And two of them check.
https://github.com/golang/go/blob/5f40351708cabe28f90500be87dbe316a2280f4a/src/go/build/build.go#L1042-L1043

**Comment by bcmills** [comment]
Five.
https://github.com/golang/go/blob/5f40351708cabe28f90500be87dbe316a2280f4a/src/cmd/go/internal/search/search.go#L193
