### ISSUE TITLE
x/tools/internal/lsp: build errors linger after they are saved

### ISSUE THREAD

**Issue by marwan-at-work** [golang/go#30786]
As you type around with gopls turned on, errors happen because you're in the middle of typing but once the code is correct the error should disappear. This usually works well, but once you start "going to def" and go back to the original file, the behavior is no longer true. Basically, the error keeps lingering around even though the code looks ok. 

I have a video to show the issue but not sure where to upload it yet since github doesn't let me. Might just put it on YouTube unless someone suggests an easier option.

**Comment by stamblerre** [comment]
I'd recommend trying out these settings in your VSCode config. It's likely that you are getting duplicate diagnostics from gopls and the Go compiler, and I wonder if they are interacting strangely.

```json
{
    "go.buildOnSave": "off",
    "go.vetOnSave": "off"
}
````

/cc @ramya-rao-a

**Comment by marwan-at-work** [comment]
@stamblerre this happens before I save a file. Basically the last error just lingers around before I save the file and after as well.

**Comment by stamblerre** [comment]
2 more instances of this error were reported [here](https://github.com/Microsoft/vscode-go/pull/2383#issuecomment-475284476). I have also seen it myself when using gopls with VSCode-Go, but I haven't had this issue when I use an extension that only uses gopls. This will be challenging to debug, but I guess we can start by looking at the gopls logs. gopls can be started with a `-logfile` flag (which can be configured in VSCode setting `go.languageServerFlags`), so if anyone is able to reproduce this error and has a corresponding log file, that would be very helpful.

**Comment by mafredri** [comment]
If it's any help, here's a log from VSCode / gopls getting stuck on `tmp not declared by package js`. Can't say I did anything special. I recall typing `js.` and browsing the auto-complete menu on a line below where `tmp` was declared after that I noticed the persistent error.

[gopls-stuck-tmp-not-declared.log](https://github.com/golang/go/files/2993757/gopls-stuck-tmp-not-declared.log)

**Comment by ianthehat** [comment]
I see it when only using the test extension. I seems like when there are no more errors we fail to tell the client that there are no errors, so it keeps remembering whatever the last error it saw was.

**Comment by ianthehat** [comment]
Except that log clearly shows us sending the empty list back for that file.
Do we have to do something special to clear out reports from previous runs?

**Comment by stamblerre** [comment]
I'm hoping that [golang.org/cl/167737](https://golang.org/cl/167737) may have fixed this issue, but I'm not certain. If anyone sees this error come up again, it'd be really helpful if you could comment here (and add a log, if you have it).

**Comment by primalmotion** [comment]
To try that with vscode I can pull latest master of gopls and disable vetOnSave, buildOnSave and reenable diagnostics?

**Comment by stamblerre** [comment]
yep, that should be all you need to do.

**Comment by stamblerre** [comment]
I may have spoken too soon - it should actually work correctly now.

**Comment by primalmotion** [comment]
from my early testing it seems to work fine now :) thanks!

**Comment by primalmotion** [comment]
Actually I still have issues. It's less frequent, but the error that sticks forever until I reload vscode is still happening.

**Comment by marwan-at-work** [comment]
Same here 😅

**Comment by ianthehat** [comment]
Could you add

```
    "go.languageServerFlags": [
        "-logfile=/tmp/golsp.log"
        "-rpc.trace"
    ],
```

to your settings and then send us the trace file after it happens?
It will contain the entire content of any files you have open, along with all edits you have made, but we don't really need that, feel free to sanitize it if there is anything proprietary in there, and feel free to send it directly to Rebecca and/or Me rather than attaching it to this issue.

**Comment by muirrn** [comment]
I am having this issue in emacs (running gopls from 8a44e74612bcf51f0d4407df3d3a8377cb99c2d8). Here are the relevant entries from my rpc log (I wasn't able to reproduce it on a simple test case, so I had to redact details from the log). The first `textDocument/didChange` is me adding the syntax error (a single errant quote), and the second `textDocument/didChange` is me correcting the error:

```
[Trace - 12:37:24 PM] Sending notification 'textDocument/didChange'.
Params: {"textDocument":{"uri":"file:///some/path/foo.go","version":25},"contentChanges":[{"text":"<source code>"}]}

[Trace - 12:37:24 PM] Sending request 'textDocument/hover - (97)'.
Params: {"textDocument":{"uri":"file:///some/path/foo.go"},"position":{"line":339,"character":1}}


[Trace - 12:37:24 PM] Sending request 'textDocument/signatureHelp - (98)'.
Params: {"textDocument":{"uri":"file:///some/path/foo.go"},"position":{"line":339,"character":1}}


[Trace - 12:37:24 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///some/path/cli.go","diagnostics":[]}


[Trace - 12:37:24 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///some/path/foo.go","diagnostics":[]}


[Trace - 12:37:24 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///some/path/cli.go","diagnostics":[]}


[Error - 12:37:24 PM] send textDocument/hover#97 no identifier found


[Trace - 12:37:24 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///some/path/foo.go","diagnostics":[{"range":{"start":{"line":339,"character":0},"end":{"line":339,"character":0}},"severity":1,"source":"LSP","message":"rune literal not terminated"}]}


[Trace - 12:37:24 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///some/path/foo_test.go","diagnostics":[]}


[Error - 12:37:24 PM] send textDocument/signatureHelp#98 cannot find an enclosing function


[Trace - 12:37:29 PM] Sending notification 'textDocument/didChange'.
Params: {"textDocument":{"uri":"file:///some/path/foo.go","version":26},"contentChanges":[{"text":"<source code>"}]}


[Trace - 12:37:30 PM] Sending request 'textDocument/hover - (99)'.
Params: {"textDocument":{"uri":"file:///some/path/foo.go"},"position":{"line":338,"character":0}}


[Error - 12:37:30 PM] send textDocument/hover#99 no identifier found


[Trace - 12:37:30 PM] Sending request 'textDocument/signatureHelp - (100)'.
Params: {"textDocument":{"uri":"file:///some/path/foo.go"},"position":{"line":338,"character":0}}


[Error - 12:37:30 PM] send textDocument/signatureHelp#100 cannot find an enclosing function


As expected, there is no message to clear out the diagnostics. Let me know what other info would be useful.
```

**Comment by muirrn** [comment]
I spent a bit more time investigating this. Based on my extra logging, it seemed like the problem, at least in some cases, was `runAnalyses` never returning, causing `cacheAndDiagnose` to block in its goroutine and never send back the diagnostics. I stopped reproducing for me at that point, so I didn't continue digging.

**Comment by stamblerre** [comment]
Thank you for the information! This is one of those bugs that happens ~1 time per day for me, so it's been difficult to track down. There seem to be multiple issues at play too - in certain cases, we don't generate diagnostics after a file change, and in other cases, VSCode seems to stop receiving diagnostics that we do send. I'll look into `runAnalyses` more.

**Comment by ianthehat** [comment]
If `runAnalyses` is blocking forever, we need to make sure that we are always using context with a deadline and also that the analysis framework is obeying a cancelled context everywhere. At least that way we might get some useful signal about what is going wrong.

**Comment by muirrn** [comment]
I was able to track this down. The problem is that the pkg.analyses cache in GetActionGraph doesn't get cleared on errors. Here is a rough timeline of what happens:

- goroutine a is in GetActionGraph, inserts entry into pkg.analyses, recurses into another GetActionGraph call
- goroutine b cancels context via SetContent
- goroutine a errors out of recursive call w/ context.Canceled error. it doesn't clear out the pkg.analyses entry. at this point, this pkg/analyzer combination will never complete again.
- goroutine b (or another) enters GetActionGraph and blocks on <-e.ready
 
In my case, the stuck package was a std lib dependency of the package I was currently editing. Nothing normally will cause a std lib package to reparse, so the stuck cache entry persists forever.

I patched with a [quick fix](https://github.com/muirrn/tools/commit/8ef4a2b6379564748930a516bcf3587450b7640e) and confirmed the problem didn't happen again.

**Comment by stamblerre** [comment]
Thank you so much for investigating this, @muirrn! Do you want to send your fix out as a CL or is it easier for you if I make the CL?

**Comment by muirrn** [comment]
I wasn't sure if you wanted my exact approach or not. I'll open a PR if you think the change looks okay, otherwise feel free to fix it how you want.

**Comment by primalmotion** [comment]
I'm running this patch locally and it works great. thanks!

**Comment by molind** [comment]
I have a similar issue on gopls 0.3.2 and vscode 1.42.1. Syntax errors don't appear in VSCode Problems tab, no matter I just saved the file or build the project.
