### ISSUE TITLE
build failing on go1.11 because package golang.org/x/sys requires go1.12

### ISSUE THREAD

**Issue by fernandezpablo85** [golang/go#30792]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.11 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/despegar/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/despegar/go"
GOPROXY=""
GORACE=""
GOROOT="/opt/go1.11/go"
GOTMPDIR=""
GOTOOLDIR="/opt/go1.11/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build587233094=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

run `go build`

### What did you expect to see?

build succeeded

### What did you see instead?

`go build golang.org/x/sys/unix: module requires Go 1.12`

### Additional comments

This build used to work a few days ago but now it fails with the previous message. Perhaps it has something to do with [this change](https://github.com/golang/sys/commit/b294cbcfc56d2a65a30c02c78722b5df061e99b8)?

### go.mod
<details><pre>
module github.com/despegar/dym

require (
	cloud.google.com/go v0.37.0 // indirect
	dmitri.shuralyov.com/app/changes v0.0.0-20181114035150-5af16e21babb // indirect
	dmitri.shuralyov.com/service/change v0.0.0-20190301072032-c25fb47d71b3 // indirect
	github.com/GoogleCloudPlatform/cloudsql-proxy v0.0.0-20190312192040-a2a65ffce834 // indirect
	github.com/Shopify/sarama v1.21.0 // indirect
	github.com/aclements/go-gg v0.0.0-20170323211221-abd1f791f5ee // indirect
	github.com/aclements/go-moremath v0.0.0-20180329182055-b1aff36309c7 // indirect
	github.com/coreos/etcd v3.3.12+incompatible // indirect
	github.com/coreos/go-systemd v0.0.0-20190212144455-93d5ec2c7f76 // indirect
	github.com/gliderlabs/ssh v0.1.3 // indirect
	github.com/go-logfmt/logfmt v0.4.0 // indirect
	github.com/go-sql-driver/mysql v1.4.1
	github.com/gobuffalo/buffalo-plugins v1.13.1 // indirect
	github.com/gobuffalo/envy v1.6.15
	github.com/gobuffalo/genny v0.0.0-20190228211236-f262bb0c783b // indirect
	github.com/gobuffalo/packd v0.0.0-20190224160250-d04dd98aca5b
	github.com/gobuffalo/packr v1.22.0
	github.com/gobuffalo/release v1.2.5 // indirect
	github.com/gobuffalo/syncx v0.0.0-20190224160051-33c29581e754
	github.com/gogo/protobuf v1.2.1 // indirect
	github.com/golang/lint v0.0.0-20190301231843-5614ed5bae6f // indirect
	github.com/golang/protobuf v1.3.0 // indirect
	github.com/golang/snappy v0.0.1 // indirect
	github.com/google/pprof v0.0.0-20190309163659-77426154d546 // indirect
	github.com/googleapis/gax-go v2.0.2+incompatible // indirect
	github.com/gopherjs/gopherjs v0.0.0-20190309154008-847fc94819f9 // indirect
	github.com/gorilla/mux v1.7.0 // indirect
	github.com/gregjones/httpcache v0.0.0-20190212212710-3befbb6ad0cc // indirect
	github.com/grpc-ecosystem/grpc-gateway v1.8.3 // indirect
	github.com/hashicorp/golang-lru v0.5.1 // indirect
	github.com/joho/godotenv v1.3.0
	github.com/kisielk/errcheck v1.2.0 // indirect
	github.com/konsorten/go-windows-terminal-sequences v1.0.2
	github.com/mailru/easyjson v0.0.0-20180823135443-60711f1a8329
	github.com/mattn/go-sqlite3 v1.10.0 // indirect
	github.com/newrelic/go-agent v2.4.0+incompatible
	github.com/onsi/ginkgo v1.8.0 // indirect
	github.com/onsi/gomega v1.5.0 // indirect
	github.com/openzipkin/zipkin-go v0.1.5 // indirect
	github.com/pkg/errors v0.8.1
	github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90 // indirect
	github.com/prometheus/procfs v0.0.0-20190306233201-d0f344d83b0c // indirect
	github.com/rogpeppe/fastuuid v1.0.0 // indirect
	github.com/rogpeppe/go-internal v1.2.2
	github.com/russross/blackfriday v2.0.0+incompatible // indirect
	github.com/shurcooL/go v0.0.0-20190121191506-3fef8c783dec // indirect
	github.com/shurcooL/gofontwoff v0.0.0-20181114050219-180f79e6909d // indirect
	github.com/shurcooL/highlight_diff v0.0.0-20181222201841-111da2e7d480 // indirect
	github.com/shurcooL/highlight_go v0.0.0-20181215221002-9d8641ddf2e1 // indirect
	github.com/shurcooL/home v0.0.0-20190204141146-5c8ae21d4240 // indirect
	github.com/shurcooL/htmlg v0.0.0-20190120222857-1e8a37b806f3 // indirect
	github.com/shurcooL/httpfs v0.0.0-20181222201310-74dc9339e414 // indirect
	github.com/shurcooL/issues v0.0.0-20190120000219-08d8dadf8acb // indirect
	github.com/shurcooL/issuesapp v0.0.0-20181229001453-b8198a402c58 // indirect
	github.com/shurcooL/notifications v0.0.0-20181111060504-bcc2b3082a7a // indirect
	github.com/shurcooL/octicon v0.0.0-20181222203144-9ff1a4cf27f4 // indirect
	github.com/shurcooL/reactions v0.0.0-20181222204718-145cd5e7f3d1 // indirect
	github.com/shurcooL/sanitized_anchor_name v1.0.0 // indirect
	github.com/shurcooL/webdavfs v0.0.0-20181215192745-5988b2d638f6 // indirect
	github.com/sirupsen/logrus v1.4.0
	github.com/spf13/afero v1.2.1 // indirect
	github.com/spf13/jwalterweatherman v1.1.0 // indirect
	github.com/ugorji/go/codec v0.0.0-20190309163734-c4a1c341dc93 // indirect
	github.com/urfave/cli v1.20.0
	go.opencensus.io v0.19.1 // indirect
	go4.org v0.0.0-20190218023631-ce4c26f7be8e // indirect
	golang.org/x/build v0.0.0-20190312210729-f0bdfa832ffe // indirect
	golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
	golang.org/x/exp v0.0.0-20190312203227-4b39c73a6495 // indirect
	golang.org/x/lint v0.0.0-20190301231843-5614ed5bae6f // indirect
	golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421 // indirect
	golang.org/x/perf v0.0.0-20190312170614-0655857e383f // indirect
	golang.org/x/sys v0.0.0-20190312061237-fead79001313
	golang.org/x/time v0.0.0-20190308202827-9d24e82272b4 // indirect
	golang.org/x/tools v0.0.0-20190312170243-e65039ee4138 // indirect
	google.golang.org/appengine v1.4.0
	google.golang.org/genproto v0.0.0-20190307195333-5fe7a883aa19 // indirect
	gopkg.in/olivere/elastic.v5 v5.0.79
	honnef.co/go/tools v0.0.0-20190215041234-466a0476246c // indirect
	sourcegraph.com/sqs/pbtypes v1.0.0 // indirect
)
</pre></details>

**Comment by bradfitz** [comment]
Dup of #30446, documented by https://github.com/golang/go/commit/e32203f647370897c6a28018c16cfd9584849569

You need to update to a newer Go 1.11.x version.

**Comment by alexcpn** [comment]
after uninstall https://golang.org/doc/install#uninstall (delete /usr/local/go) and installing the 1.12 version it worked. Maybe in the installation page it should be written to uninstall the old go version in system
