### ISSUE TITLE
x/tools/internal/lsp: completion works only when typing first character 

### ISSUE THREAD

**Issue by anjmao** [golang/go#30796]
### What version of Go are you using (`go version`)?

Hi, just tried newest gopls version.

<pre>
go version go1.12 darwin/amd64
</pre>

###

Typing `s` shows completion items and string is suggested
```go
func fn() {
	var a <>
}
```

Typing `st` shows no completion suggestions but should suggest string
```go
func fn() {
	var a s<>
}
```

### My findings

I'm using vscode with gopls. What I noticed is that Completion handler is called only once and until completion popup is visible no more calls are made for completion, this is why completion is not updated. DidChange handler is working fine and called on every character input. 

By following vscode language client-server tutorial https://code.visualstudio.com/api/language-extensions/language-server-extension-guide I can see that completion is triggered only once (while completion menu with suggested items is shown) for performance reasons and client does filtering, but for some reasons this doesn't work for gopls and vscode-go. Do you have any ideas that is the problem here?

/cc @stamblerre

**Comment by ALTree** [comment]
(OT)

@stamblerre can you confirm that the new lsp issue label is spelled correctly? It's `gopls` but it seems it should be `golsp` (or even `lsp`). The tool is at `internal/lsp` and I can't find instances of it being spelled `pls` on the internet.

**Comment by anjmao** [comment]
@ALTree it should be `gopls` meaning Go Please do x task for me.

**Comment by ALTree** [comment]
Ah, my bad. You're right. I also just noticed the wiki page is at https://github.com/golang/go/wiki/gopls too. 

Sorry for the noise.

**Comment by anjmao** [comment]
After debugging a bit I found that this issue is due to TextEdit https://github.com/golang/tools/blob/master/internal/lsp/completion.go#L40

If I remove TextEdit from completion item then it works.

**Comment by stamblerre** [comment]
@anjmao: thanks for investigating - it's really interesting that TextEdit is the problem, since as far as I know, InsertText is deprecated in favor of TextEdit (https://microsoft.github.io/language-server-protocol/specification#textDocument_completion). I'll look into this further.
