### ISSUE TITLE
How to uninstall go on MacOS

### ISSUE THREAD

**Issue by NiNJAD3vel0per** [golang/go#30793]
I've just upgraded for Go 1.12; this version has lots of bugs and incompatibility, especially for WASM and syscall/js .
So, I wanted to downgrade ; but I realized that Go has no document to properly uninstall/downgrade version on Mac!!! 
This page doesn't help at all! 
[`https://golang.org/doc/install#uninstall`](https://golang.org/doc/install#uninstall) 

**First of all, When installed Go through pkg on Mac, Go's default real location is "/usr/local/Cellar/go/1.12(or other version name) not /usr/local/go** No one mentioned about this.  
So, if I just do **rm -rf /usr/local/Cellar/go** folder, everything is ready to reinstall go?? there is no other side effect or something to do more??  Why no document mention about this?? 
How to do clean uninstall? completely?

Python has very good version manage tools; Go has not; Yes, there is "gvm". but it has lots of bugs either.

**Comment by randall77** [comment]
`Cellar` is the install directory for homebrew. So presumably you installed Go with homebrew, not directly with the Go installer (it installs at `/usr/local/go`). You should then use homebrew to uninstall it. The instructions at the page you linked are not intended to help you with that - you should consult the homebrew documentation.
Having said that, it's probably just `brew uninstall go` or `brew uninstall go1.12`.

**Comment by NiNJAD3vel0per** [comment]
> `Cellar` is the install directory for homebrew. So presumably you installed Go with homebrew, not directly with the Go installer (it installs at `/usr/local/go`). You should then use homebrew to uninstall it. The instructions at the page you linked are not intended to help you with that - you should consult the homebrew documentation.
> Having said that, it's probably just `brew uninstall go` or `brew uninstall go1.12`.

Yes, You're right. I've installed via homebrew; Now, I noticed that; Never install Go sdk via Homebrew; 
I manually delete the Cellar folder and then manually downloaded and extracted go version in /usr/local/go Now.

**Comment by agnivade** [comment]
Sounds like this is resolved. In future, please reach out to the forums at the [Questions] (https://github.com/golang/go/wiki/Questions) wiki page for general questions like these.
