### ISSUE TITLE
variables modified by later parameters are unreliably updated

### ISSUE THREAD

**Issue by arnottcr** [golang/go#30801]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build021705053=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```go
var a []int
var b bool
var c complex64
var f float32
var i int
var m map[int]int
var r rune
var s string
var t struct{ i int }
var u uint

fmt.Println(a, b, c, f, i, m, r, s, t, u, func() string {
	fmt.Println(a, b, c, f, i, m, r, s, t, u, "first")
	a = []int{1}
	b = true
	c = complex(1, 1)
	f = 1
	i = 1
	m = map[int]int{1: 1}
	r = '1'
	s = "1"
	t = struct{ i int }{1}
	u = 1
	fmt.Println(a, b, c, f, i, m, r, s, t, u, "second")
	return "third"
}())
```
[play](https://play.golang.org/p/YjQtsW50pJ8)

### What did you expect to see?
either:
```go
[] false (0+0i) 0 0 map[] 0  {0} 0 first
[1] true (1+1i) 1 1 map[1:1] 49 1 {1} 1 second
[] false (0+0i) 0 0 map[] 0  {0} 0 third
```
or
```go
[] false (0+0i) 0 0 map[] 0  {0} 0 first
[1] true (1+1i) 1 1 map[1:1] 49 1 {1} 1 second
[1] true (1+1i) 1 1 map[1:1] 49 1 {1} 1 third
```

### What did you see instead?
```go
[] false (0+0i) 0 0 map[] 0  {0} 0 first
[1] true (1+1i) 1 1 map[1:1] 49 1 {1} 1 second
[1] false (0+0i) 1 1 map[] 49 1 {1} 1 third
```

**Comment by winjeg** [comment]
The result for me on `go 1.11.5`  ran on my PC is as follows
```
[] false (0+0i) 0 0 map[] 0  {0} 0 first
[1] true (1+1i) 1 1 map[1:1] 49 1 {1} 1 second
[] false (0+0i) 0 0 map[] 0  {0} 0 third
```
It seems like a bug on go playground.

**Comment by arnottcr** [comment]
I can reproduce this on my local system too, the play link is for ease of access.

**Comment by go101** [comment]
The evaluation order of non-function expressions and function expressions is not specified in a statement. See
* https://github.com/golang/go/issues/27804
* https://github.com/go101/go101/wiki/Some-evaluation-orders-in-multi-value-assignments-are-unspecified

**Comment by arnottcr** [comment]
unfortunate that behaviour changed between releases, but this seems like a pretty clear cut duplicate, thanks @go101
