### ISSUE TITLE
Benchmark with time.Sleep show confusing results.

### ISSUE THREAD

**Issue by winjeg** [golang/go#30802]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
It's not the latest release. I don't have the latest release installed.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\wenwen\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\wenwen\go
set GOPROXY=
set GORACE=
set GOROOT=D:\apps\goinst
set GOTMPDIR=
set GOTOOLDIR=D:\apps\goinst\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\projects\go\github.com\winjeg\demo\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\wenwen\AppData\Local\Temp\go-build481306094=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
```go
package main

import (
	"testing"
	"time"
)

func SleepTest(milliseconds time.Duration) {
	time.Sleep(time.Millisecond * milliseconds)
}

func BenchmarkTestSleep500(b *testing.B) {
	SleepTest(500)
	b.ReportAllocs()
}

func BenchmarkTestSleep1000(b *testing.B) {
	SleepTest(1000)
	b.ReportAllocs()
}
```

### What did you expect to see?
I'm not so sure about this.

### What did you see instead?
```
D:\projects\go\github.com\winjeg\demo>go test -test.bench=".*"
goos: windows
goarch: amd64
pkg: github.com/winjeg/demo
BenchmarkTestSleep500-8         2000000000               0.25 ns/op            0 B/op          0 allocs/op
BenchmarkTestSleep1000-8               1        1000487600 ns/op              64 B/op          1 allocs/op
PASS
ok      github.com/winjeg/demo  11.401s

```

I don't understand why the result has  so huge difference.
Two test cases has different sleep time.

**Comment by mvdan** [comment]
This is not how benchmarks are written; you're forgetting about `b.N`. See https://golang.org/pkg/testing/#hdr-Benchmarks.

**Comment by winjeg** [comment]
> This is not how benchmarks are written; you're forgetting about `b.N`. See https://golang.org/pkg/testing/#hdr-Benchmarks.

After setting the `b.N`
```
goos: windows
goarch: amd64
pkg: github.com/winjeg/demo
BenchmarkTestSleep500-8                2         250189400 ns/op               0 B/op          0 allocs/op
BenchmarkTestSleep1000-8               2         500092600 ns/op              32 B/op          0 allocs/op
PASS
ok      github.com/winjeg/demo  19.403s
```

after setting the same `b.N` why there is a difference on `32 B/op` 

```
goos: windows
goarch: amd64
pkg: github.com/winjeg/demo
BenchmarkTestSleep500-8                2         250363100 ns/op               0 B/op          0 allocs/op
BenchmarkTestSleep1000-8               1        1000750300 ns/op              64 B/op          1 allocs/op
PASS
ok      github.com/winjeg/demo  19.396s
```

I've actually read this document before opening this issue, but still I can't understand why the sleep function doesn't actually do the sleep work when `b.N` is not set.

**Comment by go101** [comment]
> but still I can't understand why the sleep function doesn't actually do the sleep work when b.N is not set.

because the error is too larger.

The allocation results are really some weird. Looks they depend on the benchmark order.

**Comment by winjeg** [comment]
> > but still I can't understand why the sleep function doesn't actually do the sleep work when b.N is not set.
> 
> because the error is too large.
> 
> The allocation results are really some weird. Looks they depend on the benchmark order.

when `b.N` is not set why the 500ms case choose `2000000000`  and the 1000ms  case choose `1` as the value for `b.N`

And what do you mean by the error is too large? how to view the error?

thanks for your reply.

**Comment by go101** [comment]
Sorry, the explanation "the error is too large" may be not correct.

> ... and the 1000ms case choose 1 as the value for b.N

No, it also chooses a `2000000000` or `1000000000`. That is just the reason for your question.

**Comment by mvdan** [comment]
I think you should move this discussion to one of the forums: https://github.com/golang/go/wiki/Questions

Feel free to come back to the issue tracker if you think the documentation isn't clear, or if you think there's a bug in the testing package.
