### ISSUE TITLE
Clarify 32-bit x86 target

### ISSUE THREAD

**Issue by mcandre** [golang/go#30804]
Technically, Go binaries for the 32-bit x86 architecture depend on 686 (like Rust). Could the “386” architecture known to GOARCH and `go build` be renamed to reflect this dependence?

To be sure, some other tech stacks, including Debian, label their 686 ports as “386”. However, this is misleading, and in fact most modern 686 software will fail to run on pre-Pentium hardware.

**Comment by ALTree** [comment]
This is documented here: https://golang.org/doc/install/source#environment

At the `$GO386` item:

> $GO386 (for 386 only, default is auto-detected if built on either 386 or amd64, 387 otherwise)
>
> This controls the code generated by gc to use either the 387 floating-point unit (set to 387) or SSE2 instructions (set to sse2) for floating point computations.
>
> - GO386=387: use x87 for floating point operations; should support all x86 chips (Pentium MMX or later).
> - GO386=sse2: use SSE2 for floating point operations; has better performance than 387, but only available on Pentium 4/Opteron/Athlon 64 or later.

**Comment by ALTree** [comment]
In general, I think that renaming the ARCH is probably not worth it at this point. The documentation is clear enough and changing the GOARCH name wouldn't add much.

**Comment by randall77** [comment]
I agree with @ALTree.  Renaming the architecture at this point would cause a lot more pain than benefit. And we can't encode the exact set of compatible processors in 5 characters anyway. For instance, Go does run on some 586 chips.
