### ISSUE TITLE
net/http: TimeoutHandler doesn't log superfluous WriteHeader calls

### ISSUE THREAD

**Issue by LarsFox** [golang/go#30803]
#### What version of Go are you using (`go version`)?
```bash
$ go version
go version go1.12 darwin/amd64
```

#### What did you do?
Here is the program that listens and serves 2 ports with a buggy handler that calls `WriteHeader` twice. The second port, however, is also wrapped in a `http.TimeoutHandler`.

```go
package main

import (
	"log"
	"net/http"
	"reflect"
	"time"
)

func h404() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		log.Println(reflect.TypeOf(w))
		w.WriteHeader(404)
		w.WriteHeader(404)
	})
}

func main() {
	go func() {
		http.ListenAndServe(":8500", h404())
	}()
	http.ListenAndServe(":8501", http.TimeoutHandler(h404(), time.Second*10, "no logs here"))
}
```

Then I test the handlers with `curl localhost:8500 && curl localhost:8501`.

#### What did you expect to see?
Two warnings.

#### What did you see instead?
A single warning.

```
$ go run main.go
2019/03/13 14:41:02 *http.response
2019/03/13 14:41:02 http: superfluous response.WriteHeader call from main.h404.func1 (main.go:15)
2019/03/13 14:41:02 *http.timeoutWriter
```

Am I doing something terribly wrong?

#### System details

```
go version go1.12 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/leo/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/leo/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version go1.12 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.12
uname -v: Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
lldb --version: lldb-1000.0.38.2
  Swift-4.2
```

**Comment by odeke-em** [comment]
Thank you for reporting this issue @LarsFox and welcome to the Go project!

I am don't think that we have a guarantee that every handler provided by the
net/http package should log "superfluous WriteHeader call". However, this does seem inconsistent.

Here is a standalone repro that can be run on the Go playground https://play.golang.org/p/B-LBC3SyB47
or inlined below
```go
package main

import (
	"log"
	"net/http"
	"net/http/httptest"
	"net/http/httputil"
	"reflect"
	"time"
)

func h404() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		log.Println(reflect.TypeOf(w))
		w.WriteHeader(404)
		w.WriteHeader(404)
	})
}

func main() {
	cst := httptest.NewServer(http.TimeoutHandler(h404(), time.Second*10, "no logs here"))
	defer cst.Close()

	for i := 0; i < 100; i++ {
		res, err := cst.Client().Get(cst.URL)
		if err != nil {
			log.Printf("%d: error: %v", i, err)
			continue
		}

		blob, _ := httputil.DumpResponse(res, true)
		res.Body.Close()
		log.Printf("#%d:\n%s\n\n", i, blob)
	}
}
```
which produces
```shell
009/11/10 23:00:00 *http.timeoutWriter
2009/11/10 23:00:00 #0:
HTTP/1.1 404 Not Found
Date: Tue, 10 Nov 2009 23:00:00 GMT
Content-Length: 0



2009/11/10 23:00:00 *http.timeoutWriter
2009/11/10 23:00:00 #1:
HTTP/1.1 404 Not Found
Date: Tue, 10 Nov 2009 23:00:00 GMT
Content-Length: 0



2009/11/10 23:00:00 *http.timeoutWriter
2009/11/10 23:00:00 #2:
HTTP/1.1 404 Not Found
Date: Tue, 10 Nov 2009 23:00:00 GMT
Content-Length: 0
```

but no log to superfluous WriteHeader.

Kindly paging @bradfitz @tombergan

**Comment by Gnouc** [comment]
@LarsFox `timeoutWriter.WriteHeader(code)` just set the response code to `code` and `wroteHeader` to `true`, that's why no warnings is necessary.

**Comment by LarsFox** [comment]
@Gnouc, didn’t quite get the difference.
```go
func (w *response) WriteHeader(code int) {
	if w.conn.hijacked() {
		caller := relevantCaller()
		w.conn.server.logf("http: response.WriteHeader on hijacked connection from %s (%s:%d)", caller.Function, path.Base(caller.File), caller.Line)
		return
	}
	if w.wroteHeader {
		caller := relevantCaller()
		w.conn.server.logf("http: superfluous response.WriteHeader call from %s (%s:%d)", caller.Function, path.Base(caller.File), caller.Line)
		return
	}
	checkWriteHeaderCode(code)
	w.wroteHeader = true
	w.status = code

	// more stuff goes on with the Content-Length header
```

```go
func (tw *timeoutWriter) WriteHeader(code int) {
	checkWriteHeaderCode(code)
	tw.mu.Lock()
	defer tw.mu.Unlock()
	if tw.timedOut || tw.wroteHeader {
		return
	}
	tw.writeHeader(code)
}

func (tw *timeoutWriter) writeHeader(code int) {
	tw.wroteHeader = true
	tw.code = code
}
```

Also, I don’t know, but by looking through the source code I found out that if I try sending codes of 404 and then 1000 (which is very naughty), only `timeoutWriter` panics with `invalid WriteHeader code 1000` as `checkWriteHeaderCode` is called before `.wroteHeader` check. Should I make another issue or is it fine to develop the idea of _inconsistency_ here?

**Comment by Gnouc** [comment]
@LarsFox normal writer also modify the content length header in WriteHeader, timeoutWriter doesn't.

> Also, I don’t know, but by looking through the source code I found out that if I try sending codes of 404 and then 1000 (which is very naughty), only timeoutWriter panics with invalid WriteHeader code 1000 as checkWriteHeaderCode is called before .wroteHeader check. Should I make another issue or is it fine to develop the idea of inconsistency here?

cc @bradfitz @odeke-em

**Comment by odeke-em** [comment]
@cuonglm @LarsFox thanks for the comment in https://github.com/golang/go/issues/30803#issuecomment-472741330, would you mind filing an issue highlighting that other inconsistency, if an issue doesn't exist already?
