### ISSUE TITLE
x/build: warn in TryBot CL comment if the parent commit is old

### ISSUE THREAD

**Issue by bcmills** [golang/go#30807]
On #30785, @bradfitz helpfully noticed that the baseline I was testing against was quite old.

It would have been even more helpful if the bot would have told me that instead of requiring human intervention. 🙂

The TryBot result for my test said:

```
2 of 2 TryBots failed:
Failed on linux-amd64-androidemu: https://storage.googleapis.com/go-build-log/a0836481/linux-amd64-androidemu_3d8ec5df.log
Failed on android-amd64-emu: https://storage.googleapis.com/go-build-log/a0836481/android-amd64-emu_5da43c59.log

Consult https://build.golang.org/ to see whether they are new failures.
```

Perhaps it also could have said something like:

```
WARNING: Base commit xxxxxx (merged Feb. 22, 2019) is older than 7 days.
Results might not reflect current master.
```

(CC @dmitshur)

**Comment by ALTree** [comment]
Also see: #19664 (x/build: make trybots refuse to test a commit that's too old), only difference is that you're asking for a warning and not an hard refusal. May be worth to just move the discussion there and decide if a warning of a refusal is better.

**Comment by mvdan** [comment]
It looks like the original commit stalled because they couldn't reach a consensus on what the right limit should be. A number of days, a number of commits, some combination of both?

Perhaps we can start with a warning and see if it's too agressive or conservative. And if we're happy with it, consider replacing the warning with an error.

**Comment by bradfitz** [comment]
It stalled on time to implement it more than deciding anything.

**Comment by bcmills** [comment]
Duplicate of #19664
