### ISSUE TITLE
x/tools/cmd/gopls: crashes in $GOROOT

### ISSUE THREAD

**Issue by stamblerre** [golang/go#30812]
Need to handle opening of files in `$GOROOT`.

**Comment by stamblerre** [comment]
This seems to work now. @jayconrod can you confirm, since I believe you initially reported this bug to me?

**Comment by jayconrod** [comment]
Seems to be working now, both at tip and 1.12.1.

**Comment by stamblerre** [comment]
Awesome, thanks for confirming!
