### ISSUE TITLE
x/tools/cmd/gopls: logger logs wrong direction

### ISSUE THREAD

**Issue by zmb3** [golang/go#30813]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zbergquist/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/zbergquist/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bv/kylltzdj3fq_9_rgjngc45cc0000gn/T/go-build589970541=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you expect to see?

I just fired up `gopls` with the log file flag set and expected to see it log the initialize response that it sent.

### What did you see instead?

`gopls` is indicating that it _received_ a response that it actually _sent_.

```
[Trace - 2:30:55 PM] Received response 'initialize - (0)' in 1ms.
Params: {"capabilities":{"textDocumentSync":{"openClose":true,"change":1,"save":{}},"hoverProvider":true,"completionProvider":{"triggerCharacters":["."]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"codeActionProvider":true,"codeLensProvider":{},"documentFormattingProvider":true,"documentRangeFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":""},"documentLinkProvider":{},"workspace":{"workspaceFolders":{}}}}
```

This seems to be an error in the following code: https://github.com/golang/tools/blob/dbb4d4be5353aa01a3652094d511f7fe53952a7f/internal/lsp/cmd/serve.go#L84-L88

Am I interpreting this incorrectly or is this indeed a bug?  Happy to submit a CL if so.

**Comment by ianthehat** [comment]
I am not sure, but I think it is correct as it is. There is some weirdness about the logging where it is written by the server but interpreted by the tools as if it were written by the client.
I remember playing with it until https://microsoft.github.io/language-server-protocol/inspector/ gave the right results and then backing slowly away. If you could confirm whether the current log works with that tool, and then whether the change either makes the log start working or breaks it, that would be great.

**Comment by zmb3** [comment]
Thanks Ian.  Looks like the inspector is happy with it as is.  Weirdness indeed 🤷‍♂️
