### ISSUE TITLE
x/tools/cmd/godoc: add 'expand all' link to expand all examples

### ISSUE THREAD

**Issue by vdobler** [golang/go#3081]
<pre>The code examples are initially closed in the html output of
godoc.  While this is perfectly fine for online browsing it
is unsuitable for a printout:  During printing the examples
should be open/folded out.</pre>

**Comment by agnivade** [comment]
@andybons / @bradfitz for decision.

**Comment by rsc** [comment]
Per @andybons and @bradfitz, a trivial CL doing this is OK.

**Comment by agnivade** [comment]
Perfect, thanks !

**Comment by agnivade** [comment]
@bradfitz / @andybons - I have been thinking about where to put this button on the page. I have decided to place it beside the "Example" header under which all examples are listed. It has one click access from the top level ToC and is in a position from where all examples are accessible.

![expand1](https://user-images.githubusercontent.com/1774000/41362760-d01cc6a8-6f4f-11e8-9b7d-86d7161da5e5.png)


It looks a bit clumsy to me. But I am not able to find a better place. Let me know if you think of a more suitable place.

/cc @ysmolsky , @jimmyfrasche for more inputs.

**Comment by jimmyfrasche** [comment]
If this is for printing, and I'm not sure where else it would be
useful, I'd go with
https://github.com/golang/go/issues/3081#issuecomment-66063442

Just works is a better UI than more UI

**Comment by agnivade** [comment]
True. Maybe I misunderstood; the title does say to add an 'expand all' link. But I don't think we should expand all examples _by default_ during printing, which the comment is doing. The user should be able to control this with a toggle.

**Comment by jimmyfrasche** [comment]
The initial request does state that this is specifically for printing.

When would this be useful, other than printing?

When would you want to exclude some examples when printing?

**Comment by agnivade** [comment]
Yea, the title and the description are not in sync. ping @vdobler for clarification.

> When would you want to exclude some examples when printing?

I might not want to print all examples always. For eg- I might want only 1 or 2 examples. So I can expand them specifically and then print the document. I think that's a fair thing to ask.

**Comment by andybons** [comment]
@agnivade I think your position in https://github.com/golang/go/issues/3081#issuecomment-396990983 is fine. Let's move forward with that.

**Comment by vdobler** [comment]
@agnivade 
My original intention was to have all examples printed by default or by clicking once
to open them all. I find it very annoying if I print out documentation just to find out
during reading that half of it is missing because it was an "interactive" document.
Like I do not order individual chapters from a book I like to have the whole together.
Skimming over an uninteresting example is not a big deal for me in a printout.

**Comment by agnivade** [comment]
Thanks for clarifying.

> or by clicking once to open them all. 

Cool, we are going with that.
