### ISSUE TITLE
go/packages: returned packages are in incorrect order

### ISSUE THREAD

**Issue by josharian** [golang/go#30826]
Using Go 1.12.

```go
package main

import (
	"fmt"

	"golang.org/x/tools/go/packages"
)

func main() {
	cfg := &packages.Config{
		Mode: packages.LoadImports,
	}

	initial, err := packages.Load(cfg, "golang.org/x/tools/cmd/compilebench", "fmt")
	if err != nil {
		panic(err)
	}
	for _, x := range initial {
		fmt.Println(x.PkgPath)
	}
}
```

When I run this, I get:

```
$ go run bug.go 
fmt
golang.org/x/tools/cmd/compilebench
```

I expected:

```
$ go run bug.go 
golang.org/x/tools/cmd/compilebench
fmt
```

`Load` is documented to return the packages in the order they were passed to `Load`. (And this is important; if given relative package names, I have no other way of correlating them to the packages I receive back from `Load`.)

This does not reproduce if `Mode` is `LoadFiles`; it reproduces with all other modes.

cc @matloob

**Comment by ianthehat** [comment]
The input to Load is "patterns", and the documentation says "in general it is not possible to determine which packages correspond to which patterns"
I don't believe there is even an implied promise about the order matching, so I am surprised the documentation made you think that, we should probably fix the documentation.
I think if you need to do this, I think you need to make multiple independent calls to load instead.

**Comment by josharian** [comment]
> I think if you need to do this, I think you need to make multiple independent calls to load instead.

That's unfortunate. I guess I understand. It's a cumbersome and expensive way to resolve a relative path. I might be remembering the order-preservation promise from go/loader.
