### ISSUE TITLE
go/packages: returned packages are deduplicated

### ISSUE THREAD

**Issue by josharian** [golang/go#30828]
Using Go 1.12.

```go
// +build ignore

package main

import (
	"fmt"

	"golang.org/x/tools/go/packages"
)

func main() {
	cfg := &packages.Config{
		Mode: packages.LoadImports,
	}

	initial, err := packages.Load(cfg, "fmt", "fmt")
	if err != nil {
		panic(err)
	}
	for _, x := range initial {
		fmt.Println(x.PkgPath)
	}
}
```

Got:

```
$ go run bug.go
fmt
```

Want:

```
$ go run bug.go
fmt
fmt
```

Related: https://github.com/golang/go/issues/30826. This is important to me for the same reasons.

(For the record, neither of these bugs is theoretical. I hit both of them working on go-fuzz; this one I hit while trying to work around #30826.)

cc @matloob

**Comment by josharian** [comment]
@ianthehat's comments on #30826 are apropos here as well.

**Comment by matloob** [comment]
Hi -- just want to make sure that you intended to close this bug.

**Comment by matloob** [comment]
Oh, just read #30826... Yeah, you'd have to make two separate calls to Load for this usecase. Once we get the changes to LoadMode in, that should be relatively cheap to do.
