### ISSUE TITLE
 x/tools/packages how to disable specific cgo package?

### ISSUE THREAD

**Issue by shuxiao9058** [golang/go#30836]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jiya/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/usr/local/gopath"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zz/kq305wt53jx650qz4dmn7r8h0000gn/T/go-build945039651=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you expect to see?

x/tools/packages painc with cgo package(linux build version .a)

### What did you see instead?
How to disable specific cgo package?

**Comment by shuxiao9058** [comment]
refer to：https://github.com/saibing/bingo/issues/126#issuecomment-472723509

**Comment by katiehockman** [comment]
This seems like a general question, not a bug with steps to reproduce. For questions about Go, see https://golang.org/wiki/Questions.
