### ISSUE TITLE
goimports will not automatically delete duplicate imports at certain case

### ISSUE THREAD

**Issue by andyafter** [golang/go#30832]
Hey there I am working on go language version 1.12 darwin/amd64. I have saved my go import as the following:
```
import (
    "context"
    
    "some/package/aaa"

    "another/package"
    "some/package/aaa"
)
```

And in this case, only in this case, goimports will not be deleting duplicate imports automatically. I tried with terminal command, emacs and vscode.

**Comment by agnivade** [comment]
Please see @rsc's comment here https://github.com/golang/go/issues/26846#issuecomment-412629549.

> We intentionally leave this to local custom - gofmt and goimports will never move imports across blank lines in the import block. So if I want path with the others, I can do that, and gofmt/goimports respect that. And if you want all your renamed imports together, you can do that, and gofmt/goimports respect that too.

i.e. imports separated by blank lines are considered separate and that is intentional. Hence gofmt/goimports will not dedup entries beyond a single import group.

**Comment by andyafter** [comment]
Damn it I thought I finally got something
