### ISSUE TITLE
net: why not check valid when parse CIDR

### ISSUE THREAD

**Issue by daixiang0** [golang/go#30834]
### What version of Go are you using (`go version`)?

```
$ go version
go version go1.10.3 linux/amd64
```

### Does this issue reproduce with the latest release?
yes

### What did you do?

I setup an invalid CIDR address  by mistake in k8s CNI then all pods in different nodes can not communicate each other, then i find code never check a CIDR address is valid or not.

Based on example in https://golang.org/pkg/net/#ParseCIDR, test some invalid CIDR address like `10.97.0.0/12`, `192.167.0.0/12`, all can work. They are invalid based on my knowledge, aren't they? 

### What did you expect to see?

Check validation when parse.

**Comment by daixiang0** [comment]
#30825

**Comment by mikioh** [comment]
> They are invalid based on my knowledge, aren't they?

Please make sure what's valid and what's invalid from what point of view.

**Comment by daixiang0** [comment]
take `10.97.0.0/12` as example:
CIDR bases on dotted decimal, `12` mean it uses 12 bits, the first num uses whole 8 bits and the second num should use first 4 bit of whole 8 bits, `97` is invalid since it is `01100001` while `96` is valid since it is `01100000`.

there is a check way by bash: https://stackoverflow.com/questions/50084229/bash-check-if-cidr-address-is-valid

**Comment by mikioh** [comment]
> CIDR bases on dotted decimal

Oh, please don't forget Pv6 addresses.

> 12 mean it uses 12 bits

It's the length of the address prefix, no more no less.

> 10.97.0.0/12

We usually think that "okay, the attached address is 10.97.0.0/32, the address prefix is 10.96.0.0/12; presumably, the subnet address is 10.96.0.0 and the directed broadcast address is 10.111.255.255; what a big subnet! which RIR allocates this for which organization?"

**Comment by daixiang0** [comment]
take k8s network as example:
kubeadm and CNI like calico use CIDR to setup cluster network, specify 10.96.0.0/12 as pod ip range is common.  If specify 10.97.0.0/12, network not works as expected.

**Comment by daixiang0** [comment]
CIDR format as ip/mask, now ParseCIDR() only check the validation of ip part not mask, so if use invalid CIDR,  in this range, must have many subnets can not communicate.

**Comment by mikioh** [comment]
> kubeadm and and CNI like ... network not works as expected.

Sounds like that is not an issue of ParseCIDR. If your issue is that ParseCIDR accepts a valid CIDR notation and the behavior is not what you want, changing the behavior of ParseCIDR for your application is not an ideal solution (moreover the change will break Kubernetes and Docker).

Instead, you may use ParseCIDR more appropriately like https://play.golang.org/p/z3cYDbR21ws Closing.
