### ISSUE TITLE
cmd/go: avoid term "notary" to avoid confusion with CNCF Notary

### ISSUE THREAD

**Issue by rsc** [golang/go#30835]
#25530 proposes securing releases with a transparent log served by a service called a _notary_.
I adopted both the term and the behavior (publish observations of the internet) from the [CMU Perspectives system](https://www.cs.cmu.edu/~dga/papers/perspectives-usenix2008/).

It's been pointed out to me that CNCF has a [project called Notary](https://github.com/theupdateframework/notary), which turns out to be written Go, but of course is different from our notary.

This issue is to rename the Go notary service to avoid confusion with the CNCF Notary system. Because the notary is basically a giant `go.sum` database server, I am currently inclined toward “summary.” We would s/notary/summary service/ when talking about a server and s/notary/summary/ or s/notary/sum/ elsewhere (something like $GOROOT/lib/sum/sum.cfg, GET /sum/supported; https://summary.golang.org/; and so on).

This probably won't happen for a few weeks at least. Happy bikeshedding!

**Comment by bcmills** [comment]
> Because the notary is basically a giant go.sum database server, I am currently inclined toward “summary.”

“module summary” carries connotations of documentation for me. Perhaps “summator”, as in “one who summates”?

**Comment by ericlagergren** [comment]
Summary—and derivatives—do not have the same connotations as notary.

At the very least it could be changed to a synonym of notary:

- registrar
- witness
- recorder

Or services that are similar to notaries:

- signatory
- medallion

etc.

**Comment by FiloSottile** [comment]
I am still fond of "clerk", as it keeps the receipts.

(I think it came from @bcmills originally? I did not come up with it.)

**Comment by agnivade** [comment]
Late to the party, but here goes -
- ledger
- auditor

**Comment by bcmills** [comment]
Ooh, “ledger” is nice. It even carries that nice “repository of sums” connotation!

**Comment by FiloSottile** [comment]
Please not "ledger". It will lead to endless confusion as to whether we are using a blockchain or even issued a token (which should sound ludicrous, but look up how Namecoin works), and we don't have two columns and a balance anyway.

Auditors are third-party entities in a transparency log ecosystem, they are the ones that follow the log and make sure it's operated honestly.

**Comment by mvdan** [comment]
I agree with "clerk", if anything because it seems to mean "they who keep records/notes/history".

We also have other words in that vicinity, like "scribe", "bookkeeper", "registrar", or "notetaker". Or perhaps even "historian", since it keeps a history of published modules.

**Comment by jimmyfrasche** [comment]
Grandmaster Hash

**Comment by komuw** [comment]
- notaio

**Comment by kybin** [comment]
* summer
* grandsum

**Comment by AlexRouSg** [comment]
Kinda surprised no one said `NoteyMcNoterface` yet

**Comment by opennota** [comment]
herodotus

**Comment by oiooj** [comment]
`sum.golang.org`? Since we have a `go.sum`.

**Comment by rsc** [comment]
This service is an implementation detail - an important one - but not something anyone should be focusing on. The cute name gives it more focus than it arguably should have. We don't have a cute name for, say, the go command build cache. 

The hostname will be sum.golang.org instead of notary.golang.org, as @oiooj suggested, but beyond that, I think we'll try just not using any other name at all. If you need to refer to the service-without-a-short-name, call it the "Go module checksum service" (or just sum.golang.org).

**Comment by rsc** [comment]
Reopening because we need to excise the term "notary" from various docs and code. Then this can be closed.

**Comment by rsc** [comment]
This is done. (The new term is Go checksum database, or sumdb for short.)
