### ISSUE TITLE
plugin: types on different scopes when using vendor

### ISSUE THREAD

**Issue by jschintag** [golang/go#30838]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 linux/s390x
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="s390x"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="s390x"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_s390x"
GCCGO="gccgo"
CC="s390x-linux-gnu-gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -march=z196 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build249750574=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I have the following structure:
<pre>
/root/go/src/
|-- foo
    |-- main.go
    |-- types/
        |-- types.go
|-- foo-plugin
    |-- plugin.go
</pre>

I have an interface in types.go

types/types.go
<pre>
package types

type Custom interface {
        Test() string
}
</pre>

I use this in the Plugin

plugin.go
<pre>
package main

import (
        "foo/types"
)

type CustomStruct struct {
}

var CustomVar types.Custom = &CustomStruct{}

func (c *CustomStruct) Test() string {
        return "success"
}
</pre>

And i load and use the Plugin in main.go

main.go
<pre>
package main

import (
        "fmt"
        "plugin"

        "foo/types"
)

func main() {
        p, err := plugin.Open("/root/go/src/foo-plugin/foo-plugin.so")
        if err != nil {
                fmt.Println(err)
        }
        symbol, err := p.Lookup("CustomVar")
        customVar := symbol.(*types.Custom)
        custom := *customVar
        result := custom.Test()
        fmt.Println(result)
}
</pre>

When i build the Plugin and then run `go run main.go` it works.
However, when i copy `foo` into `foo-plugin/vendor/foo` i get an error.

### What did you expect to see?

<pre>
$ go run main.go
success
</pre>

### What did you see instead?

<pre>
$ go run main.go
panic: interface conversion: plugin.Symbol is *types.Custom, not *types.Custom (types from different scopes)

goroutine 1 [running]:
main.main()
        /root/go/src/foo/main.go:16 +0x27e
exit status 2
</pre>

**Comment by bcmills** [comment]
In GOPATH mode, each `vendor` copy of a package is its own distinct package. That behavior will not be changing.

The solution is not to use `vendor`, or to use module mode with only a top-level `vendor` directory.

**Comment by jschintag** [comment]
Ok, thank you for your answer.
