### ISSUE TITLE
'go get' fails when '?' in file path inside of module

### ISSUE THREAD

**Issue by clarsen** [golang/go#30854]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes, in 1.12

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/Users/clarsen/lsrc/go/bin"
GOCACHE="/Users/clarsen/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/clarsen/lsrc/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/clarsen/lsrc/go/src/github.com/clarsen/go-trello-workflow/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mx/gr33pns500xgxj5cyvfnx6tw0000gn/T/go-build927821387=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
<pre>
export GO111module=on
go get github.com/dougEfresh/gtoggl-api
</pre>

I believe issue is that file in https://github.com/dougEfresh/gtoggl-api/tree/master/gttimentry/mock/GET/api/v8 has a '?' in the filename.

### What did you expect to see?
successful import

### What did you see instead?
<pre>
go: finding github.com/dougEfresh/gtoggl-api latest
go: extracting github.com/dougEfresh/gtoggl-api v0.0.0-20181029170833-3dde07b8438e
-> unzip /Users/clarsen/lsrc/go/pkg/mod/cache/download/github.com/doug!efresh/gtoggl-api/@v/v0.0.0-20181029170833-3dde07b8438e.zip: malformed file path "gttimentry/mock/GET/api/v8/time_entries?end_date=2013-03-12T15%3A42%3A46%2B02%3A00&start_date=2013-03-10T15%3A42%3A46%2B02%3A00.json": invalid char '?'
package github.com/dougEfresh/gtoggl-api: unknown import path "github.com/dougEfresh/gtoggl-api": unzip /Users/clarsen/lsrc/go/pkg/mod/cache/download/github.com/doug!efresh/gtoggl-api/@v/v0.0.0-20181029170833-3dde07b8438e.zip: malformed file path "gttimentry/mock/GET/api/v8/time_entries?end_date=2013-03-12T15%3A42%3A46%2B02%3A00&start_date=2013-03-10T15%3A42%3A46%2B02%3A00.json": invalid char '?'
</pre>

**Comment by bcmills** [comment]
The error message here is clear and intentional: the character `?` is not allowed in files within a module. That character is one of many disallowed on Windows filesystems, and we require that module contents be portable across platforms.
