### ISSUE TITLE
cmd/compile: give better error for composite literal parsing ambiguity

### ISSUE THREAD

**Issue by empijei** [golang/go#30867]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
```go
type foo struct{}

func main() {
	bar := foo{}
	if bar == foo{} {
		fmt.Println("true")
		return
	}
	fmt.Println("false")
}
```
[Play link](https://play.golang.org/p/TteIWNEER1t)

### What did you expect to see?
```
true
```

### What did you see instead?
```
prog.go:11:18: syntax error: unexpected { at end of statement
prog.go:15:2: syntax error: non-declaration statement outside function body
```

Please note that [adding parentheses works](https://play.golang.org/p/vkXqH18UoNf)
```go
	if bar == (foo{}) {
```
Is this intended? If so, shouldn't the compiler give better errors?

**Comment by ianlancetaylor** [comment]
Search for "parsing ambiguity" in https://golang.org/ref/spec#Composite_literals .

I don't know whether the compiler could give a better error message.  I'll retitle the issue for that.

**Comment by arashbina** [comment]
Do you still need someone to investigate this?

**Comment by ianlancetaylor** [comment]
The thing to investigate would be whether it is straightforward for the compiler to give a better error message for this case.  If you want to look into it, go ahead, but please be aware that this is a subtle issue that will need to consider several different kinds of incorrect code to make sure that the error message does not become more misleading.  Thanks.

**Comment by arashbina** [comment]
Ok thanks. I'll take a look and update here.

**Comment by quasilyte** [comment]
I think the main complexity here is that the error message probably originates from the parser, and we don't know about types at that point, so I think it's impossible for a parser in the current state to tell whether `foo` is a type or not. I think it's relevant not only to the Go internal parser but also to `go/parser`.

**Comment by empijei** [comment]
I think this is rather complicated and would probably come up to be a hack. I looked into it and IMO it would add too much complexity to address it. I don't want that and since this is already documented I guess it can stay as it is.

Closing as won't fix. Feel free to re-open if you can come up with a good and simple solution.
