### ISSUE TITLE
cmd/cover: failing TestFuncWithDuplicateLines

### ISSUE THREAD

**Issue by sudeeshjohn** [golang/go#30861]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.1 linux/amd64

built version:

root@ubuntu18:/go/src/golang/go# ./bin/go version
go version devel +cb8054a6b6 Fri Mar 15 04:15:59 2019 +0000 linux/amd64
root@ubuntu18:/go/src/golang/go#
</pre>

### Does this issue reproduce with the latest release?

No. The issue is there with the upstream master.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build733849470=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

git clone https://github.com/golang/go.git && cd go/src && ./all.bash

### What did you expect to see?

all the tests should have passed

### What did you see instead?
```
ok  	cmd/compile/internal/test	0.023s [no tests to run]
ok  	cmd/compile/internal/types	0.035s
--- FAIL: TestFuncWithDuplicateLines (3.26s)
    cover_test.go:553: running [/go/src/golang/go/bin/go test -toolexec=/tmp/gotestcover178375904/toolexec.exe /tmp/gotestcover178375904/cover.exe -cover -covermode count -coverprofile /tmp/gotestcover178375904/linedup/linedup.out]
    cover_test.go:553: go: cannot find main module; see 'go help modules'
    cover_test.go:553: exit status 1
FAIL
FAIL	cmd/cover	6.872s
ok  	cmd/doc	0.047s
ok  	cmd/fix	13.342s

```

**Comment by bcmills** [comment]
Fixed by https://golang.org/cl/167740.
