### ISSUE TITLE
image/gif: bounds offset reversed when encoding

### ISSUE THREAD

**Issue by splace** [golang/go#30887]
go 1.12.1 linux/amd64

## What did you expect to see?

image shift not depending on saved format.

### What did you see instead?

gif image shifted in the opposite direction to all other formats.

(several other image format generating libs tried and gif the only one in disagreement.)

### demo example:

````
package main
import "image"
import "image/png"
import "image/jpeg"
import "image/gif"
import "os"

type offsetImage struct{
	image.Image
	Rect image.Rectangle	
}

func (i offsetImage) Bounds() image.Rectangle{
	return i.Rect
}

func main() {
	img:=offsetImage{image.Rect(0,0,50,50),image.Rect(0,0,50,50) }
	w,_:= os.Create("1.png")
	png.Encode(w,img)
	w,_= os.Create("1.jpg")
	jpeg.Encode(w,img,nil)
	w,_= os.Create("1.gif")
	gif.Encode(w,img,nil)
	
	img.Rect=image.Rect(30,30,80,80)  // same size just offset

	w,_= os.Create("2.png")
	png.Encode(w,img)
	w,_= os.Create("2.jpg")
	jpeg.Encode(w,img,nil)
	w,_= os.Create("2.gif")
	gif.Encode(w,img,nil)
	
}

````

### output

without shift:all white, all the same as expected

* ![1](https://user-images.githubusercontent.com/1234848/54484070-907cdc00-4856-11e9-80c6-340d92af1684.png)
* ![1](https://user-images.githubusercontent.com/1234848/54484071-907cdc00-4856-11e9-8b03-b066ce74e4c9.jpg)
* ![1](https://user-images.githubusercontent.com/1234848/54484072-907cdc00-4856-11e9-8141-709153b0a365.gif)

with shift: 

* ![2](https://user-images.githubusercontent.com/1234848/54484067-8fe44580-4856-11e9-8e03-78704e73f9eb.png)
* ![2](https://user-images.githubusercontent.com/1234848/54484068-8fe44580-4856-11e9-84fc-f4d0601ca629.jpg)
* ![2](https://user-images.githubusercontent.com/1234848/54484069-8fe44580-4856-11e9-95a0-812b10ff7a23.gif)

(png image above not showing in github md?)

**Comment by katiehockman** [comment]
I was able to reproduce this, does seem that gif changes after the offset in a way that's different from the other image formats.

/cc @nigeltao for image/gif package

**Comment by splace** [comment]
confirmed fixed. (with patch) demo now results in matching images and original code now works as expected. nice.
