### ISSUE TITLE
cmd/go: avoid invoking git for standard library queries

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#30885]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +14c3692502 Sat Mar 16 14:16:39 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What did you do?
Removed git, then
<pre>
$ cd $HOME/go/golang.org/x/tools # previously checked out x/tools
$ go clean -modcache
$ go list -- unsafe
go: golang.org/x/net@v0.0.0-20190311183353-d8887717615a: git init --bare in /home/elias/go/pkg/mod/cache/vcs/4a22365141bc4eea5d5ac4a1395e653f2669485db75ef119e7bbec8e19b12a21: exec: "git": executable file not found in $PATH
</pre>
### What did you expect to see?
No error

### What did you see instead?
An error about missing git.

Queries such as the above are issued by go/packages in module mode, which is breaking many tests on GOOS=android where git is not installed. See x/tools: https://build.golang.org/log/763e5ef04fc3679a903b8cd85a7e0ececcdd15b69.

It seems to me it should be possible to avoid downloading dependencies and invoking git when querying the standard library.

**Comment by eliasnaur** [comment]
CC @bcmills @jayconrod

**Comment by eliasnaur** [comment]
Another bunch of errors from x/exp:

https://build.golang.org/log/546c34306ce262ec806cd8ccda7462f0ce503ad6

(Look for "could not determine GOARCH and Go compiler")

**Comment by ericlagergren** [comment]
Related to https://github.com/golang/go/issues/29452

**Comment by jayconrod** [comment]
This is happening when we load the build list. The first thing the Go command does in module mode (whether running `go build`, `go test`, `go list`, ...) is load the `go.mod` of the main module and any other modules that are transitively required. If `go.mod` files are not present in the module cache, they are fetched via `GOPROXY` or VCS tools. 

It might be possible for us to limit this behavior, based on the command line arguments, but it would add a lot of complexity, and I think it would only be feasible for the main module and the standard library. It doesn't seem worth it.

`GOPROXY` should probably be the long-term solution. Can that be used here? Setting `GOPROXY` to a `file://` URL pointing to a tree prepared ahead of time seems like a good setup for tests.

**Comment by eliasnaur** [comment]
GOPROXY is a good idea. The builders already have GOPROXY setup for them; CL 168118 passes that to the device environment. Thank you, I believe that solves the issue with running go list on android.

I still believe go list queries for std and the main module are common enough to do something here, but I'll leave that discussion for #29452.
