### ISSUE TITLE
go/src/plugin: proposed generate wrap code when build plugin

### ISSUE THREAD

**Issue by rocket049** [golang/go#30882]
If we have follow plugin code:

```
//plugin.go
package main

import (
	"fmt"
)

type ObjType struct {
	name string
}

func (p *ObjType) Say(s string) int {
	fmt.Printf("%s say: %s\n", p.name, s)
	return len(s)
}

func NewObjType(name string) *ObjType {
	return &ObjType{name}
}
```

When we build it like this:
`go build -buildmode=plugin plugin.go`

It is better to generate wrap code like follow:

```
//pluginloader.go
package main

import (
	"plugin"
	"reflect"
)

type ObjTypeInterface interface {
	Say(string) int
}

type PluginLoader struct {
	p *plugin.Plugin
}

func (p *PluginLoader) NewObjType(s string) ObjTypeInterface {
	f0, err := p.p.Lookup("NewObjType")
	if err != nil {
		panic(err)
	}
	f1 := reflect.ValueOf(f0)
	p1 := reflect.ValueOf(s)
	res := f1.Call([]reflect.Value{p1})
	if res == nil {
		return nil
	}
	return res[0].Interface().(ObjTypeInterface)
}

func PluginLoad(name string) (p *PluginLoader) {
	plug, err := plugin.Open(name)
	if err != nil {
		panic(err)
	}
	return &PluginLoader{p: plug}
}
```

**Comment by rocket049** [comment]
I do something for it.

code:

https://github.com/rocket049/pluginloader

**Comment by katiehockman** [comment]
@rocket049 Can you please clarify what the actual output of `go build -buildmode=plugin plugin.go` is, versus what you are proposing? It's unclear from the issue description what problem that the proposed solution would be trying to solve. Is there a bug that you feel your solution is fixing?

**Comment by rocket049** [comment]
The problem is too complex to use plugin.
I want to use plugin simple,
call function and use object from a plugin natural.
Just like gomobile does!

**Comment by rocket049** [comment]
Let go generate wrap code for user,  when build a plugin.

**Comment by helperShang** [comment]
@rocket049 No sense to do this , i can reflect by myself.

**Comment by rocket049** [comment]
Vitality lies in progress！

**Comment by rocket049** [comment]
I write a wrap tool: `github.com/rocket049/pluginloader/cmd/pluginwrap`
It works well with `github.com/rocket049/pluginloader/`
I really don't like reflect ,it is slow.
But it seems no way to convert a function by type assert when it returns an object (struct with methods).

**Comment by rocket049** [comment]
pluginwrap is almost perfect now!

**Comment by agnivade** [comment]
@rocket049 - You seem to have a tool which works for you. Is there anything else you want to be done in this issue ? What you seem to ask is likely a proposal anyways.

**Comment by rocket049** [comment]
> @rocket049 - You seem to have a tool which works for you. Is there anything else you want to be done in this issue ? What you seem to ask is likely a proposal anyways.

I have no proposal now. Because I have resolve it myself. Should I close this issue?

**Comment by agnivade** [comment]
If there is nothing to do from our side, then yes. I will go ahead and close it.
