### ISSUE TITLE
cmd/go: add sort for go.mod after 'go mod tidy'

### ISSUE THREAD

**Issue by guhan121** [golang/go#30897]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.1 darwin/amd64

$go env
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
</pre>

### What did you do?

after run `go mod tidy`
the go.mod file is modified!
But if you diff it with last version by git tools,you can't see the change clearly。

i hope add a rule for sort lines in go.mod !

**Comment by bcmills** [comment]
`go` commands that edit the `go.mod` file do preserve sort order within each block. Could you give a concrete example for which the result ends up unsorted?

https://github.com/golang/go/blob/93af67783796a48b3f59bd969dc0c528c37571ec/src/cmd/go/internal/modfile/rule.go#L669-L678

**Comment by guhan121** [comment]
oh! sorry, because the `go.mod` in our project edit by developers not use `go mod tidy`,so it not sort.
i check the `go.mod` file. it is sorted!
As shown in the figure below：
On the left is developer submissions！
On the right is `go mod tidy`！

![image](https://user-images.githubusercontent.com/5517369/55324337-4f223880-54b4-11e9-8c86-d33d60ac8922.png)
