### ISSUE TITLE
x/tools/internal/lsp: add support for document symbols

### ISSUE THREAD

**Issue by zmb3** [golang/go#30915]
Tracking issue to add support for the [document symbols request](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol)

**Comment by zmb3** [comment]
I'm looking into this and figured I'd log an issue for visibility.

**Comment by stamblerre** [comment]
Remaining tasks:

- Add struct fields as children of the struct document symbol.
- Associate struct methods with the struct document symbol.
- List methods as children of an interface symbol (maybe?)

**Comment by stamblerre** [comment]
I think at this point we can count this issue as fixed. We can file issues for further improvements separately. Thanks for contributing, @zmb3!
