### ISSUE TITLE
cmd/compile: internal/ssa TestNexting failing

### ISSUE THREAD

**Issue by katiehockman** [golang/go#30912]
Change d949d0b (cmd/compile: reorganize init functions) seems to have failed the TestNexting test in the `cmd/compile/internal/ssa` package for linux-amd64-longtest builds

```
--- FAIL: TestNexting (10.74s)
    --- FAIL: TestNexting/gdb-dbg-i22558 (0.48s)
        debug_test.go:241: step/next histories differ, diff=
            --- testdata/i22558.gdb-dbg.nexts	2019-03-18 21:16:19.000000000 +0000
            +++ /workdir/tmp/debug_test137844848/test-i22558.gdb-dbg.nexts	2019-03-18 21:42:04.493540912 +0000
            @@ -2,3 +2,10 @@
             19:	func test(t *thing, u *thing) {
             20:		if t.next != nil {
             23:		fmt.Fprintf(os.Stderr, "%s\n", t.name)
            +24:		u.self = u
            +25:		t.self = t
            +26:		t.next = u
            +27:		for _, p := range t.stuff {
            +28:			if isFoo(t, p) {
            +29:				return
            +44:	}
FAIL
FAIL	cmd/compile/internal/ssa	85.797s
```
 
https://build.golang.org/log/cb49293c3202a9d78ae2324b5a8217e99dc82e8a

cc @randall77

**Comment by randall77** [comment]
@dr2chase

**Comment by katiehockman** [comment]
This seems to be failing x/tools builds as well:
https://build.golang.org/log/f1e3906e966da6b4c3a47af7cf1b005e95f2c906

**Comment by dr2chase** [comment]
I'll give it a look tomorrow, but superficially it looks like the behavior got better.

**Comment by katiehockman** [comment]
@dr2chase will you also be making the fix to the test that failed [[ExampleRead](https://github.com/golang/tools/blob/83362c3779f5f48611068d488a03ea7bbaddc81e/go/gcexportdata/example_test.go#L25)] in x/tools as well, or would you like help with that? The fix seems straightforward enough that I can likely do it if needed.

**Comment by katiehockman** [comment]
Re-opening this just to track the other related x/tools bug. Can keep track in a separate issue if that's easier.
