### ISSUE TITLE
cmd/go: test failing to initialize build cache

### ISSUE THREAD

**Issue by katiehockman** [golang/go#30914]
`cmd/go` tests are failing for darwin-arm64-mn4m2zdaios and darwin-arm-mg912baios builds

```
lldb: running program
2019/03/18 20:16:58 failed to initialize build cache at /private/var/folders/qq/qxn86k813bn9fjxydm095rxw0000gp/T/workdir-host-darwin-amd64-zenly-ios/go/pkg/obj/go-build: mkdir /private/var/folders/qq: operation not permitted
FAIL	cmd/go	117.729s

```
Seems somewhat related to #29523

https://build.golang.org/log/e556301592beb290f2a21aafacf76f4176552ab1
https://build.golang.org/log/2bb2f1740aec8d028fa98073bc4c0d3810842d33

Though I'm not convinced that it's related, the failures started after 47e42cd was merged

/cc @bcmills @ianlancetaylor

**Comment by ianlancetaylor** [comment]
CC @bradfitz @dmitshur

**Comment by dmitshur** [comment]
Another possible cause is [CL 167087](https://golang.org/cl/167087), the CL that changed the default value of GO111MODULE to 'on'. It was 3 commits earlier, and there are no test results for it for those 2 builders.

It could be related to symlinks and the temporary directory on Darwin. I.e., `os.TempDir()` is usually something like `/var/folders/b8/66r1c5856mqds1mrf2tjtq8w0000gn/T/` but `/var` is a symlink to `/private/var`.

**Comment by bradfitz** [comment]
@eliasnaur has been working on these.
