### ISSUE TITLE
Import Cycle Not Allowed error need help - GOLANG beginer ! 

### ISSUE THREAD

**Issue by andresitompul** [golang/go#30919]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
I want to compile a usual hello world program,

but it showing me an error like this

Import Cycle not allowed
package hello 
               Imports fmt
               Imports errors
               Imports runtime
               Imports internal/cpu
               Imports runtime

If possible, provide a recipe for reproducing the error.

I want to build the .exe by using go build command in the right path.
where the .go file is already on the right path

A complete runnable program is good.

this is the script

package main

import "fmt"

func main() {
	fmt.Printf("hello, world\n")
}
A link on play.golang.org is best.

#### What did you expect to see?

I want to see this program is succeeding compiled 

#### What did you see instead?

error already given

#### Does this issue reproduce with the latest release (go1.12.1)?

no I use the 1.8.3 for windows

#### System details

```
go version go1.8.3 windows/386
GOARCH="386"
GOBIN=""
GOEXE=".exe"
GOHOSTARCH="386"
GOHOSTOS="windows"
GOOS="windows"
GOPATH="C:\Users\Andre Sitompul\go"
GORACE=""
GOROOT="C:\Go"
GOTOOLDIR="C:\Go\pkg\tool\windows_386"
GCCGO="gccgo"
GO386=""
CC="gcc"
GOGCCFLAGS="-m32 -mthreads -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
GOROOT/bin/go version: go version go1.8.3 windows/386
GOROOT/bin/go tool compile -V: compile version go1.8.3 X:framepointer
```

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
