### ISSUE TITLE
undefined: registry.OpenKey when cross compiling on Windows for Linux

### ISSUE THREAD

**Issue by TKSS3** [golang/go#30927]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.5 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH=amd64
GOHOSTARCH=amd64
GOHOSTOS=windows
GOOS=linux

</pre></details>

### What did you do?
https://gist.github.com/TKSS3/dde5491ba0d96ae8bff0b816dd4d9fbc

### What did you expect to see?
<pre>
Since the windows registry part is not being used if GOOS=Linux, I expected to see no errors and succesfull build
</pre>

### What did you see instead?
<pre>
.\test.go:24:17: undefined: registry.OpenKey
.\test.go:24:34: undefined: registry.CURRENT_USER
.\test.go:24:82: undefined: registry.QUERY_VALUE
</pre>

**Comment by kardianos** [comment]
You need to lookup build tags. https://golang.org/pkg/go/build/

Name one file `task.go`, then put linux specific calls into `task_linux.go` and `task_windows.go` and it will choose the correct files to compile be convention, even without build tags.

**Comment by bradfitz** [comment]
Yeah, what @kardianos said.

**Comment by TKSS3** [comment]
Thank you for your help! I will look into it.
