### ISSUE TITLE
Issue with 7-Zip

### ISSUE THREAD

**Issue by Souldrake** [golang/go#30923]
Hello, I am having an issue with the current build 2.4.0.0 and 7-zip.

I am running Win10 64 bit

In the past, I have been able to right click on 7-zip, run in Japanese and use it to open Japanese files in zip archives and extract them without getting garbled characters.

Due to some unfortunate instances with a virus and such, I have had to reinstall Win 10 multiple times and, upon doing so and downloading the latest version of Locale Emulator, for some reason this no longer shows up as an option when trying to run 7-zip and I can no longer extract Japanese file names from zip files as a result. =/ It works with other programs, but not for 7 zip for whatever reason T_T;

I have been trying desperately to fix this issue as it's rather important to me for work in some of the projects I freelance for. I have tried to fix this multiple times through win 10, but so far the only solution I have found is through this program and now it's not working either T_T;

Any advice or help with this issue would be appreciated. I'm not sure if it's some weird thing on my end or a problem with the program or what. ><;

**Comment by ianlancetaylor** [comment]
I'm sorry, I don't understand why you are reporting this problem on this issue tracker.  This issue tracker is for problems with the Go tools and standard library.  We have no version 2.4.0.0.  I don't know what 7-zip is.

**Comment by AlexRouSg** [comment]
@ianlancetaylor 

https://www.7-zip.org

But the 2.4.0.0 is referring to https://github.com/xupefei/Locale-Emulator/releases

I'm very confused too, neither of those even uses Go.

**Comment by Souldrake** [comment]
Sorry if this is not the proper spot, I was looking for a place to report issues with Locale Emulator and I was lead to this place >.<;

**Comment by AlexRouSg** [comment]
What lead you here?

**Comment by Souldrake** [comment]
A google search =/

**Comment by agnivade** [comment]
This is not the right place. Closing.
