### ISSUE TITLE
cmd/go: 'looping trying to add package' is not a helpful error message

### ISSUE THREAD

**Issue by integrii** [golang/go#30936]
### What version of Go are you using (`go version`)?

<pre>
go version go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

Use a program that references a package that no longer exists at that location.  I was importing a package that imports `github.com/docker/docker/container`, which imports `github.com/opencontainers/runc/libcontainer/label`, which does not exist [here](https://github.com/opencontainers/runc/tree/master/libcontainer) anymore.

### What did you expect to see?

A helpful error telling me that the package specified by a dependency does not exist.

### What did you see instead?

A confusing error from [here](https://github.com/golang/go/blob/master/src/cmd/go/internal/modload/load.go#L551) that simply says `looping trying to add package`.  

This is confusing for the user.  We should indicate better that the package does not exist or was not found at the specified location.  People are hitting this, getting confused, and wasting time, which makes them dislike go modules (and go itself by relationship).

Related issue: #30394

**Comment by jayconrod** [comment]
Yep, not a helpful error message.

The fix for #30394 will be to improve the error message though, so I'll close this one as a dup.
