### ISSUE TITLE
cmd/go: duplicate symbols when including two main packages in -coverpkg in module mode [1.12 backport]

### ISSUE THREAD

**Issue by jayconrod** [golang/go#30937]
I'd like [CL 168200](https://golang.org/cl/168200) to be cherry-picked for 1.12.2.

This was the second fix for #30374 (its first backport issue was #30684). The first fix, [CL 164877](https://go-review.googlesource.com/c/go/+/164877), was backported and released in 1.12.1, but it missed an important case that was discovered later.

#30374 (aka #30684) was a regression from GOPATH mode, and the fix is again straightforward.

(I know gopherbot usually opens these issues; I asked politely, but it didn't do it).

**Comment by dmitshur** [comment]
> (I know gopherbot usually opens these issues; I asked politely, but it didn't do it).

For reference, this is tracked in issue #25574. Until that is resolved, gopherbot listens for backport requests at most one time per issue.

**Comment by dmitshur** [comment]
Cherry pick approved because this is a followup to a fix for a significant regression from GOPATH mode.
