### ISSUE TITLE
text/template:  illegal number syntax: "-"

### ISSUE THREAD

**Issue by bep** [golang/go#30948]
```go
package main

import (
	"log"
	"text/template"
)

func main() {
	_, err := template.New("").Parse(`{{- .Foo  -}}`)
	if err != nil {
		log.Fatal(err)
	}
}
```

Fails with:

```bash
template: :1: illegal number syntax: "-"
```

https://play.golang.org/p/VC7LYAI34HU

There is an extra space after `.Foo`, which is an easy "mistake" to make (I just did), and not always obvious to spot, esp. since there is only a line number in the error message.

**Comment by mvdan** [comment]
Thanks for the report! I think this is just a bug in the lexer. I think it should be a valid template to parse. After all, `{{    .Foo     }}` is a valid template, and the mention of `- ` and ` -` never specifies that exactly one space is required.
