### ISSUE TITLE
Possible error in url.go

### ISSUE THREAD

**Issue by delbertaud** [golang/go#30958]
go version go1.12 windows/amd64

set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\delbe\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\delbe\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\delbe\AppData\Local\Temp\go-build263610566=/tmp/go-build -gno-record-gcc-switches

### What did you do?
Testing Lorca for Desktop App Development

### What did you expect to see?
Web page to be displayed

### What did you see instead?
Received an error reported by net\url\url.go 
because the url had a space at the end of the string. I feel this is an invalid error as it does not effect the referencing of the end-point.

My fix was to simply trim the url in the function of url.go

func stringContainsCTLByte(s string) bool {
	s = strings.TrimSpace(s)
	for i := 0; i < len(s); i++ {

**Comment by ianlancetaylor** [comment]
This is an intentional change mentioned in the 1.12 release notes at https://golang.org/doc/go1.12#net/url .
