### ISSUE TITLE
blog: bugs in "Using Go Modules"

### ISSUE THREAD

**Issue by skybrian** [golang/go#30954]
https://blog.golang.org/using-go-modules

- There's a duplicate section starting with: "Note that our module now depends on both rsc.io/quote and rsc.io/quote/v3:"

- In the example of upgrading a major version, Hello was renamed to HelloV3, but the name in the calling code isn't fixed. It should be "quoteV3.HelloV3", not "quoteV3.Hello".

**Comment by andybons** [comment]
@skybrian Thanks, Brian!
