### ISSUE TITLE
cmd/asm: inconsistent handling of explicit zero offset for TEXT pseudo

### ISSUE THREAD

**Issue by benjaminp** [golang/go#30968]
`cmd/asm` in Go 1.12.1 and before willingly assembles
```
TEXT ·MyFunc+0(SB), $0
```
However, `cmd/asm` in `-gensymabis` mode doesn't recognize this line as a definition. That leads to esoteric symbol ABI errors during linking on Go 1.12.

Either offset for the `TEXT` pseudo should be fully banned or `-gensymabis` should handle explicit zero offsets.

**Comment by josharian** [comment]
cc @aclements @robpike

**Comment by cherrymui** [comment]
I would guess that accepting +0 offset was not intentional. Maybe we should just reject it.

**Comment by robpike** [comment]
It was certainly intentional. The first example in the assembly document has that form, and that output came from a compiler. I don't think it should be rejected and there's nothing wrong with it.
