### ISSUE TITLE
x/net/html: Parse handles custom self-closing tags differently to all major browsers

### ISSUE THREAD

**Issue by TomAnthony** [golang/go#30961]
### What version of Go are you using (`go version`)?

<pre>
> go version
go version go1.12.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
> go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tom/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tom/projects/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hm/n8fgn9bx61z5129js8wft_1c0000gn/T/go-build225010318=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I ran this program:

https://play.golang.org/p/JfyssBdfzFH

Which parses this snippet of html then re-stringifies it:

```html
<!doctype html>
<html>
	<head></head>
	<body>
		<tag1>
			<tag2 />
			<p>one</p>
		</tag1>
		<div>two</div>
	</body>
</html>
```

### What did you expect to see?

I'd expect the custom `tag2` tag to wrap the `p` tag (as a custom tag cannot be self-closing according to the [spec](https://www.w3.org/TR/html5/single-page.html#self-closing-start-tag-state) - this is discussed in issue https://github.com/golang/go/issues/26566), but everything at a higher level in the tree (including `tag1`) to remain in their respective locations:

```html
<!doctype html>
<html>
	<head></head>
	<body>
		<tag1>
			<tag2>
				<p>one</p>
			</tag2>
		</tag1>
		<div>two</div>
	</body>
</html>
```

### What did you see instead?

The `p` tag is wrapped as we would expect, but the `div` tag that was a sibling of `tag1` is now a child of `tag1`:

```html
<!DOCTYPE html>
<html>
	<head></head>
	<body>
		<tag1>
			<tag2>
				<p>one</p>
			</tag2>
			<div>two</div>
		</tag1>
	</body>
</html>
```

This doesn't make sense to me - the self-closing `tag2` is in violation of the spec, but has been turned into a properly closed tag following sensible assumptions about what should become children of it (all its siblings). It makes no sense that after being closed there are further alterations to subsequent parts of the tree.

The Go output is also in disagreement to how all the major browsers handle the same HTML code:

Chrome:

![chrome](https://user-images.githubusercontent.com/966003/54713609-eb5c4f00-4b46-11e9-8df7-e24430e518c2.png)

Firefox:

![firefox](https://user-images.githubusercontent.com/966003/54713622-f2835d00-4b46-11e9-8f34-aaf56ecbb5cb.png)

Safari:

![safari](https://user-images.githubusercontent.com/966003/54713633-f911d480-4b46-11e9-9948-1fd2a1a6c228.png)

Go [script](https://play.golang.org/p/JfyssBdfzFH) output:

![golang](https://user-images.githubusercontent.com/966003/54713705-23639200-4b47-11e9-9556-b78f306c033e.png)

**Comment by TomAnthony** [comment]
An additional observation.

If you swap the illegal `tag2` for an illegal self closing `div` instead:

```html
<!doctype html>
<html>
	<head></head>
	<body>
		<tag1>
			<div />
			<p>one</p>
		</tag1>
		<div>two</div>
	</body>
</html>
```

Then Chrome/Safari/Firefox all exhibit a similar behaviour to Go, in that they move the `<div>two</div>` inside the `tag1` (which Go does also with the `<div />` example):

![chrome-div](https://user-images.githubusercontent.com/966003/54760776-aa1c7b80-4be8-11e9-965e-41cd7e74cdcd.png)

I don't know the spec well enough to understand why that would be the case and why all the browsers agree with one another on these two use cases, but Go disagrees on one.

**Comment by TomAnthony** [comment]
One final example, with the original example but now with the illegal `tag1` swapped for a legal `div`, wrapping the illegal self-closing `tag2`:

```html
<!doctype html>
<html>
	<head></head>
	<body>
		<div>
			<tag2 />
			<p>one</p>
		</div>
		<div>two</div>
	</body>
</html>
```

In this instance Go parses it correctly:

```html
<!doctype html>
<html>
	<head></head>
	<body>
		<div>
			<tag2>
				<p>one</p>
			</tag2>
		</div>
		<div>two</div>
	</body>
</html>
```

So the erroneous handling seems to come about only when there is an non-standard tag wrapping a non-standard self-closing tag.

**Comment by TomAnthony** [comment]
I've submitted a PR which fixes this issue whilst passing all the existing go and webkit unit tests. From my examples above it seems the `popUntil` function, when run on unknown tags, should treat other unknown tags as a stop tags.

However, I don't have a detailed understanding of the spec, so this likely needs some tweaks / overhauling.

I'll keep reading the spec and update this if I get a clearer understanding.

**Comment by TomAnthony** [comment]
After some more reading, I believe I have pinpointed this better.

I believe the issue is the `inBodyEndTagOther` where it checks if the atom types match. For unknown elements this will be 0, meaning nested unknown elements will falsely match against each other (which aligns with the manifestations we see above):

```go
func (p *parser) inBodyEndTagOther(tagAtom a.Atom) {
	for i := len(p.oe) - 1; i >= 0; i-- {
		if p.oe[i].DataAtom == tagAtom {
			p.oe = p.oe[:i]
			break
		}
		if isSpecialElement(p.oe[i]) {
			break
		}
	}
}
```

I need to have a think about how best to update my PR.

**Comment by nigeltao** [comment]
I dropped some comments on https://go-review.googlesource.com/c/net/+/168638/5#message-4ac4bc26800e097755388cd7530f897286537176

**Comment by TomAnthony** [comment]
I've [responded in Gerrit](https://go-review.googlesource.com/c/net/+/168638/5#message-cad749ea40552ac42d6f7726159532933170a5d9) and updated the PR. Thanks! :)
