### ISSUE TITLE
x/tools/go/loader: should respect PKG_CONFIG environmental variable

### ISSUE THREAD

**Issue by benjaminp** [golang/go#30964]
When loading cgo, the `go` tool allows the path to the `pkg-config` tool to be overridden with the `PKG_CONFIG` environmental variable. The `x/tools` loader, however, hardcodes the name `pkg-config` for a `$PATH` search. It should instead only fallback to such a search after looking at the `PKG_CONFIG` environmental variable.

**Comment by josharian** [comment]
go/loader is deprecated in favor of go/packages. Please give it a try. (The same bug may well exist there. If so, please let us know.)

cc @matloob

**Comment by benjaminp** [comment]
The `go/packages` < 1.12 fallback code uses the same cgo code as `go/loader`. But it looks like that's all slated to be deleted imminently?

**Comment by matloob** [comment]
The go/packages fallback code was just deleted as of golang.org/cl/166537. 

As @josharian noted above, go/loader is deprecated. We don't plan on making changes to go/loader except to fix serious bugs.

**Comment by andybons** [comment]
Closing as the package is deprecated.
