### ISSUE TITLE
errors: As crashes if nil error is passed

### ISSUE THREAD

**Issue by agnivade** [golang/go#30970]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +e96c4ace9c Mon Mar 18 10:50:57 2019 +0530 linux/amd64
</pre>

### What did you do?

```go
package main

import (
	"errors"
)

type ErrNoUser struct {
	err error
}

func (e ErrNoUser) Error() string {
	return e.err.Error()
}

func (e ErrNoUser) Unwrap() error {
	return e.err
}

func main() {
	err := doSth()
	ce := ErrNoUser{}
	errors.As(err, &ce)
}

func doSth() error {
	return nil
}
```

### What did you expect to see?
No output or an intentional error

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x45487d]

goroutine 1 [running]:
errors.As(0x0, 0x0, 0x465440, 0xc000010020, 0xc00001e118)
	/home/agniva/play/gosource/go/src/errors/wrap.go:93 +0x23d
main.main()
	/home/agniva/play/go/src/osexpand.go:22 +0x50
exit status 2
```

Note that this does not happen with `errors.Is`. Something like this works fine:

```
ce := ErrNoUser{}
errors.Is(err, ce)
```

Possibly due to this https://github.com/golang/go/blob/master/src/errors/wrap.go#L55

/cc @mpvl @jba

**Comment by jba** [comment]
@neild 

Should `errors.As(nil, ...)` panic or return false?  Returning false seems reasonable to me.

Either way, we should state the behavior in the docstring.

**Comment by jimmyfrasche** [comment]
Logically, if there is no error, then it cannot be a particular error, so false makes sense.

Practically, I might want to write something like
```
err := f()
if errors.As(err, &something) {
  // handle special case of a something error
}
// otherwise return err whether or not it is nil
return err
```
so false is useful.

**Comment by neild** [comment]
Returning false for a nil error seems reasonable to me.
