### ISSUE TITLE
Tar files cannot store file names larger than 100 characters

### ISSUE THREAD

**Issue by barcelona-messi** [golang/go#30976]
File names larger than 100 characters will be truncated when i use archive/tar , how can I save a file name larger than 100 characters in the tar?

**Comment by agnivade** [comment]
You are probably using USTAR format. Please use PAX. https://golang.org/pkg/archive/tar/#Format.

If you still face the same issue with PAX. Please show us a complete code sample that we can run at our end to reproduce the issue, along with other details in the issue template with go version and go env, which you have skipped.

Thanks.
