### ISSUE TITLE
cmd/vet/all: build failures affecting misc-vet-vetall

### ISSUE THREAD

**Issue by erifan** [golang/go#30971]
### What version of Go are you using (`go version`)?

go version devel +0fe1986a72 Thu Mar 21 01:35:21 2019 +0000 linux/arm64

### Does this issue reproduce with the latest release?

no

### What operating system and processor architecture are you using (`go env`)?
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/*/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/*/go"
GOPROXY=""
GORACE=""
GOROOT="/home//go-master"
GOTMPDIR=""
GOTOOLDIR="/home//go-master/pkg/tool/linux_arm64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home//go-master/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build580593418=/tmp/go-build -gno-record-gcc-switches"

The problem also occurs on amd64.

### What did you do?

GO_BUILDER_NAME=*-vetall ../bin/go tool dist test -run arm64$

##### Testing packages.

ok      cmd/internal/obj/arm64  0.056s

ALL TESTS PASSED (some were excluded)

##### cmd/vet/all
go run main.go -p darwin/arm64
encoding/xml/marshal.go:104: method MarshalXML(e *xml.Encoder, start xml.StartElement) error should have signature MarshalXML(*xml.Encoder, xml.StartElement) error
encoding/xml/read.go:175: method UnmarshalXML(d *xml.Decoder, start xml.StartElement) error should have signature UnmarshalXML(*xml.Decoder, xml.StartElement) error
encoding/xml/marshal_test.go:317: method MarshalXML(e *xml.Encoder, start xml.StartElement) error should have signature MarshalXML(*xml.Encoder, xml.StartElement) error
encoding/xml/read_test.go:630: method UnmarshalXML(d *xml.Decoder, start xml.StartElement) error should have signature UnmarshalXML(*xml.Decoder, xml.StartElement) error
encoding/xml/xml_test.go:887: method UnmarshalXML(*xml.Decoder, xml.StartElement) error should have signature UnmarshalXML(*xml.Decoder, xml.StartElement) error
exit status 1
2019/03/21 06:14:58 Failed: exit status 1
go run main.go -p android/arm64
encoding/xml/marshal.go:104: method MarshalXML(e *xml.Encoder, start xml.StartElement) error should have signature MarshalXML(*xml.Encoder, xml.StartElement) error
encoding/xml/read.go:175: method UnmarshalXML(d *xml.Decoder, start xml.StartElement) error should have signature UnmarshalXML(*xml.Decoder, xml.StartElement) error
encoding/xml/marshal_test.go:317: method MarshalXML(e *xml.Encoder, start xml.StartElement) error should have signature MarshalXML(*xml.Encoder, xml.StartElement) error
encoding/xml/read_test.go:630: method UnmarshalXML(d *xml.Decoder, start xml.StartElement) error should have signature UnmarshalXML(*xml.Decoder, xml.StartElement) error
encoding/xml/xml_test.go:887: method UnmarshalXML(*xml.Decoder, xml.StartElement) error should have signature UnmarshalXML(*xml.Decoder, xml.StartElement) error
exit status 1
2019/03/21 06:14:59 Failed: exit status 1
go run main.go -p linux/arm64
encoding/xml/marshal.go:104: method MarshalXML(e *xml.Encoder, start xml.StartElement) error should have signature MarshalXML(*xml.Encoder, xml.StartElement) error
encoding/xml/read.go:175: method UnmarshalXML(d *xml.Decoder, start xml.StartElement) error should have signature UnmarshalXML(*xml.Decoder, xml.StartElement) error
encoding/xml/marshal_test.go:317: method MarshalXML(e *xml.Encoder, start xml.StartElement) error should have signature MarshalXML(*xml.Encoder, xml.StartElement) error
encoding/xml/read_test.go:630: method UnmarshalXML(d *xml.Decoder, start xml.StartElement) error should have signature UnmarshalXML(*xml.Decoder, xml.StartElement) error
encoding/xml/xml_test.go:887: method UnmarshalXML(*xml.Decoder, xml.StartElement) error should have signature UnmarshalXML(*xml.Decoder, xml.StartElement) error
exit status 1
2019/03/21 06:14:59 Failed: exit status 1
2019/03/21 06:15:00 FAILED

**Comment by erifan** [comment]
The problem seems to be related with https://go-review.googlesource.com/c/go/+/168458

**Comment by agnivade** [comment]
@mvdan

**Comment by mvdan** [comment]
Sorry, I cannot reproduce this issue. On a newly built `go version devel +277609f844 Thu Mar 21 08:41:51 2019 +0000 linux/amd64`:

```
$ cd src/cmd/vet/all/
$ go run main.go -p linux/arm64
[no error]
```

Are you positive you're on a clean clone? Also, `main.go` now *downloads* the latest version from `x/tools` via Go modules, so perhaps your module cache is somehow broken or out of date. Try `go clean -modcache` before trying again.

**Comment by erifan** [comment]
Sorry for late reply. After running `go clean -modcache`, I can still reproduce this error.

go version devel +4906a00cdd Fri Mar 22 09:07:09 2019 +0000 linux/arm64
`$ GO_BUILDER_NAME=*-vetall ~/go-master/bin/go tool dist test -run linux/arm64`

##### cmd/vet/all
go run main.go -p linux/arm64
encoding/xml/marshal.go:104: method MarshalXML(e *xml.Encoder, start xml.StartElement) error should have signature MarshalXML(*xml.Encoder, xml.StartElement) error
encoding/xml/read.go:175: method UnmarshalXML(d *xml.Decoder, start xml.StartElement) error should have signature UnmarshalXML(*xml.Decoder, xml.StartElement) error
encoding/xml/marshal_test.go:317: method MarshalXML(e *xml.Encoder, start xml.StartElement) error should have signature MarshalXML(*xml.Encoder, xml.StartElement) error
encoding/xml/read_test.go:630: method UnmarshalXML(d *xml.Decoder, start xml.StartElement) error should have signature UnmarshalXML(*xml.Decoder, xml.StartElement) error
encoding/xml/xml_test.go:887: method UnmarshalXML(*xml.Decoder, xml.StartElement) error should have signature UnmarshalXML(*xml.Decoder, xml.StartElement) error
exit status 1
2019/03/22 10:50:27 Failed: exit status 1
2019/03/22 10:50:28 FAILED

go version devel +4906a00cdd Fri Mar 22 09:07:09 2019 +0000 linux/amd64
`$ GO_BUILDER_NAME=*-vetall ~/go-master/bin/go tool dist test -run linux/amd64`

##### cmd/vet/all
go: finding golang.org/x/tools/go/analysis/cmd/vet latest
go: finding golang.org/x/tools/go/analysis/cmd latest
go: finding golang.org/x/tools/go/analysis latest
go: finding golang.org/x/tools/go latest
go: finding golang.org/x/tools latest
go: downloading golang.org/x/tools v0.0.0-20190321232350-e250d351ecad
go: extracting golang.org/x/tools v0.0.0-20190321232350-e250d351ecad
go: finding golang.org/x/net v0.0.0-20190311183353-d8887717615a
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding golang.org/x/text v0.3.0
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go run main.go -p linux/amd64
compress/gzip/example_test.go:58: ExampleReader_Multistream refers to unknown field or method: Reader.Multistream
net/http/example_test.go:116: ExampleServer_Shutdown refers to unknown field or method: Server.Shutdown
exit status 1
2019/03/22 10:51:47 Failed: exit status 1
2019/03/22 10:51:47 FAILED

Do you export GO_BUILDER_NAME=*-vetall ?

**Comment by mvdan** [comment]
`GO_BUILDER_NAME=*-vetall go run main.go -p linux/arm64` succeeds just as fine.

Can you try that exact command? `go tool dist test` does way more work, so I don't want to run that every time I want to try to reproduce.

Also /cc @bcmills, since he rewrote `cmd/vet/all/main.go` to be module-aware. Though I believe he's on holiday at the moment.

**Comment by erifan** [comment]
Yeah, @bcmills 

```
$ ~/go-master/bin/go clean -modcache
$ GO_BUILDER_NAME=*-vetall ~/go-master/bin/go run main.go -p 
```
linux/arm64
go: finding golang.org/x/tools/go/analysis/cmd/vet latest
go: finding golang.org/x/tools/go/analysis/cmd latest
go: finding golang.org/x/tools/go/analysis latest
go: finding golang.org/x/tools/go latest
go: finding golang.org/x/tools latest
go: downloading golang.org/x/tools v0.0.0-20190321232350-e250d351ecad
go: extracting golang.org/x/tools v0.0.0-20190321232350-e250d351ecad
go: finding golang.org/x/net v0.0.0-20190311183353-d8887717615a
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding golang.org/x/text v0.3.0
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go run main.go -p linux/arm64
compress/gzip/example_test.go:58: ExampleReader_Multistream refers to unknown field or method: Reader.Multistream
net/http/example_test.go:116: ExampleServer_Shutdown refers to unknown field or method: Server.Shutdown
exit status 1

**Comment by mvdan** [comment]
Hmm, this trybot run ran into the same `ExampleReader_Multistream` failure: https://storage.googleapis.com/go-build-log/f424e025/misc-vet-vetall_a955c34e.log

**Comment by mvdan** [comment]
This is worse than I thought; the misc-vet-vetall builder has been red for a few hours:

![2019-03-22-12:33:00](https://user-images.githubusercontent.com/3576549/54823114-c0850e80-4c9e-11e9-906b-3cd6de7f3c48.png)

/cc @matloob @dmitshur

**Comment by mvdan** [comment]
All trybot runs are failing now because of this, so I'm pinning the issue to ensure others find it.

**Comment by mvdan** [comment]
The error itself doesn't make much sense to me; these methods have existed for many Go releases.

```
api/go1.4.txt:11:pkg compress/gzip, method (*Reader) Multistream(bool)
api/go1.8.txt:196:pkg net/http, method (*Server) Shutdown(context.Context) error
```

Even if the build was somehow happening with the Go 1.4 bootstrap version, we wouldn't be seeing the gzip error.

**Comment by ianlancetaylor** [comment]
The cause is a bug in https://golang.org/cl/168404.  I added a comment to the CL.  CC @matloob

**Comment by mvdan** [comment]
Nice find! Seeing as the fix is trivial, we should probably push it to master as soon as possible, to get the trybots green again. We can always add a test later.

**Comment by ianlancetaylor** [comment]
I'm going to give myself 10 minutes to write a test.

**Comment by jayconrod** [comment]
I'm still seeing this failure on [CL 168404](https://go-review.googlesource.com/c/tools/+/168404/), which I rebased a few minutes ago. The log is [here](https://storage.googleapis.com/go-build-log/ccb3ba6a/misc-vet-vetall_14f34952.log).

```
encoding/xml/marshal.go:104: method MarshalXML(e *xml.Encoder, start xml.StartElement) error should have signature MarshalXML(*xml.Encoder, xml.StartElement) error
encoding/xml/read.go:175: method UnmarshalXML(d *xml.Decoder, start xml.StartElement) error should have signature UnmarshalXML(*xml.Decoder, xml.StartElement) error
encoding/xml/marshal_test.go:317: method MarshalXML(e *xml.Encoder, start xml.StartElement) error should have signature MarshalXML(*xml.Encoder, xml.StartElement) error
encoding/xml/read_test.go:630: method UnmarshalXML(d *xml.Decoder, start xml.StartElement) error should have signature UnmarshalXML(*xml.Decoder, xml.StartElement) error
encoding/xml/xml_test.go:887: method UnmarshalXML(*xml.Decoder, xml.StartElement) error should have signature UnmarshalXML(*xml.Decoder, xml.StartElement) error
```

**Comment by dmitshur** [comment]
I'm seeing this failure, or a failure similar to this one, on latest tip commit on https://build.golang.org/ from [CL 168697](https://golang.org/cl/168697) that was submitted 15 minutes ago:

https://build.golang.org/log/62231cd4bf3fcb3d2c5a2e425240a31ad258b79c

Also in a CL to release-branch.go1.12 that I rebased today ([CL 168958](https://golang.org/cl/168958)).

It looks identical to what @jayconrod posted above in https://github.com/golang/go/issues/30971#issuecomment-475719840.

**Comment by dmitshur** [comment]
I can't reproduce this locally so far; `GO_BUILDER_NAME=*-vetall ../bin/go tool dist test -run arm64` and `GO_BUILDER_NAME=*-vetall ../bin/go tool dist test -run js/wasm` succeed locally for me both at CL 168697 and its parent commit.

**Comment by bradfitz** [comment]
Plan:

* temporarily disable the vetall builders & trybots
* remove the vetall special cases in x/build/cmd/coordinator
* rewrite src/cmd/vet/all to use modules and not $GOPATH. (I suspect our bug is somewhere in this step, or a bad interaction with the $GOPATH the coordinator lays down)
* re-enable the vetall builders.

/cc @josharian

**Comment by mvdan** [comment]
Note that I think part of the problem is that `cmd/vet/all/main.go` currently pulls the latest version from `x/tools` via module mode, instead of using the pinned version from `cmd/go.mod`. It's hard to reason about which exact version of `go/analysis` the test is running with.
