### ISSUE TITLE
legalize circular imports

### ISSUE THREAD

**Issue by Vany** [golang/go#30974]
We know that circular dependencies a banned just because of linking process. Compiler must be fast as possible.  But if we can show our agreement to be slightly slow here, like 

```
import (
    ...
    name "path/to/our/circular/importer" `compile:"together"`
)
```

this tag forces compiler always to compile this two packages together in to single .o

Yes, compilation process now will be slowed down, but another side of this coin is dedicated package with interfaces and indirect calling in runtime.

Another look at this is copackages, in fact it is a single package, but have different namespaces.

also we can do a lot more stuff with this import tags.

**Comment by ALTree** [comment]
Thanks for the report.

This was asked several times in the past, including the recent #30247 (for Go2). It has always been rejected. In particular, see: https://github.com/golang/go/issues/30247#issuecomment-463940936 and https://github.com/golang/go/issues/30247#issuecomment-464251208.

The consensus in the Go team about allowed circular imports *not* happening, ever, even in Go2, seems to be quite strong, so I'm closing this issue as a dup of #30247.

**Comment by yanlee26** [comment]
OK
Thanks!
