### ISSUE TITLE
encoding/xml: decoding XML with entities not supported

### ISSUE THREAD

**Issue by kunalgrover05** [golang/go#30983]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.9
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Linux AMD64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

XML entity support 

```
	s := "<?xml version='1.0' encoding='ISO-8859-1'?><!DOCTYPE foo [ <!ENTITY test 'hello' > ]><Users><User><Name>&test;</Name></User></Users>"

	reader := strings.NewReader(s)
	decoder := xml.NewDecoder(reader)
	decoder.CharsetReader = charset.NewReaderLabel

	for {
		token, err := decoder.Token()
		if err != nil && err != io.EOF {
			fmt.Printf("Error! Decoding XML failed: %v\n", err)
			break
		}
		if token == nil {
			break
		}
		switch element := token.(type) {
		case xml.CharData:
			fmt.Printf("%s\n", element)
		}
	}

```

Exception
```
Error! Decoding XML failed: XML syntax error on line 1: invalid character entity &test;
```

Parsed data with `decoder.Strict = false`
```
&pwnd;
```

### What did you expect to see?
Entities and External entities to be processed as per https://www.w3.org/TR/xml/#sec-entity-decl

**Comment by mvdan** [comment]
I'm not experienced with XML, but have you had a look at https://github.com/golang/go/issues/4196? And possibly https://github.com/golang/go/issues/20614 too, since I see some extra whitespace in there.
