### ISSUE TITLE
strconv: document ParseFloat's special cases (nan, inf)

### ISSUE THREAD

**Issue by johnbalvin** [golang/go#30990]
### What version of Go are you using (`go version`)?

<pre>
go version go1.12 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\TATA\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\TATA\Documents\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\TATA\AppData\Local\Temp\go-build125692270=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
Convert some string values to float

package main
```go
package main

import (
	"fmt"
	"strconv"
	"log"
)

func main() {
	s, err := strconv.ParseFloat("nan", 32)
	if err != nil {
		log.Printf(" err: %s: ",err)
	}
	fmt.Printf("%T, %v\n", s, s)

}

```

### What did you expect to see?
Error showing in the console because NaN is not a number

### What did you see instead?
NaN

**Comment by randall77** [comment]
This is intentional behavior.  I think we just need to mention it in the docs.

**Comment by msoedov** [comment]
> Change has been successfully cherry-picked as 203b80ab8639ff9dc0710e22c2b33f2df861363b by
