### ISSUE TITLE
database/sql: Provide format string for SQL dates, times, and datetimes

### ISSUE THREAD

**Issue by mcandre** [golang/go#30991]
Go helpfully declares a predefined format string for parsing and formatting RFC3339 timestamps. Unfortunately, SQL uses a slightly different format, essentially replacing the `T` separator with a space. So, it would be helpful for the database/sql` package to provide format strings for reliably parsing and formatting SQL dates/times/datetimes. For example:

```go
var SQLTimestampFormat = "2006-01-02 15:04:05"
```

Higher level API's supposedly offer automatic marshaling between SQL literals and Go objects, such as ORM's and special SQL driver options. However, sometimes lower level access is needed. In these cases, it is helpful to be able to use a predefined, tested format string rather than having to write our own.

**Comment by kardianos** [comment]
Which SQL databases use this format? Can you confirm it is widely supported?

**Comment by mcandre** [comment]
The ANSI SQL specification, PostgreSQL, MySQL/MariaDB, MSSQL, Oracle, BigQuery, Spanner, SQLite, MonetDB, Virtuoso, and Firebird support the aforementioned `tr/$RFC3339/T/ /` syntax as a common datetime format.

So we should probably name this format string `AnsiSqlTimestampFormat`.

Some implementations support an ISO 8601 variant with the conventional T separator, most expect a space. Some reject subsecond precision. Most reject a timezone.

DB2 appears to expects a dash, deviating from not only RFC3339 but also ANSI SQL. It's beyond me why RDBMS's have not adopted RFC3339 as the preferred timestamp format, but such is life.

**Comment by kardianos** [comment]
@mcandre Thanks for the info. (small nit it would be a const if added).

Some databases also support timezones such as timestampz or datetimeoffset. I have two additional question:
 1. What about date only, time of day, or timestampz (datetimeoffset)? Do you think those have the same utility? Are these also uniform across implementations? I think SQL Server supports offset only, but postgresql supports timezone names.
 2. These consts certainly do have value. Can you explain why you think they should be in the standard library rather then in a public package? Would this be useful for better conversion in database/sql?

Thanks.
