### ISSUE TITLE
cmd/go: import cycle error message lacks position information

### ISSUE THREAD

**Issue by josharian** [golang/go#31011]
```
$ go test
can't load package: import cycle not allowed
package math/big
	imports math/big
```

This error message would be much more helpful if it told me where the offending root import is.

cc @bcmills @jayconrod

**Comment by bcmills** [comment]
@josharian, do you have an input that reproduces this issue?

**Comment by josharian** [comment]
I don't, I'm afraid. I'll just close this and re-open if I see something like it again.
