### ISSUE TITLE
cmd/cgo: unexpected semicolon, expecting expression error (part III)

### ISSUE THREAD

**Issue by gooid** [golang/go#31017]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 windows/amd64
</pre>

main.go
```
package main

import (
	"unsafe"
)

/*
void cgofoo(void* a, int b) {}
*/
import "C"

func foo() {
	var p unsafe.Pointer

	C.cgofoo(nil, (C.int)(
		0))

	C.cgofoo(p, (C.int)(0))

	// syntax error: unexpected semicolon, expecting expression
	C.cgofoo(p, (C.int)(
		0))
}

func main() {}
```

### What did you expect to see?
build success,
but go 1.11.4 is ok.

### What did you see instead?
main.go:21:27: syntax error: unexpected semicolon, expecting expression

**Comment by ALTree** [comment]
Thanks for reporting this.

This is related to #29748 and #29781. I've verified that tip still fails, so it's probably another variation the previous fixed don't cover.

cc @ianlancetaylor
