### ISSUE TITLE
How to convert [] byte into JSON

### ISSUE THREAD

**Issue by soamyak** [golang/go#31026]
### What version of Go are you using (`go version`)?

<pre>
$ go1.12 windows/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

package main
import (
	"WIP_SINGLE/controllers"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"github.com/gorilla/mux"
)

func main() {
	router := mux.NewRouter()
	router.HandleFunc("/v1.0/singles/{id}", GetSingleInfo).Methods("GET")
	log.Println("Server Started...")
	log.Fatal(http.ListenAndServe(":8000", router))
}

//GetSingleInfo function
func GetSingleInfo(w http.ResponseWriter, r *http.Request) {

	vars := mux.Vars(r)
       //var pdata models.JSON
	pdata, err := json.Marshal(vars)
	controller := controllers.Controller{}
	pdatar, err := controller.GetSingleUnitInfo(pdata)

	fmt.Println(pdatar["errorCode"])
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	
json.NewEncoder(w).Encode(pdatar)
}

### What did you expect to see?
GET /singles/{id}
 Want to create an API which take id from here and return a json. 

### What did you see instead?
pdatar, err := controller.GetSingleUnitInfo(pdata) --> Parameter is not getting accepted by the controller function as it expects a Json type but pdata here is [] byte type, not sure how to convert it in json.

**Comment by OneOfOne** [comment]
This belongs on a forum or stackoverflow.
