### ISSUE TITLE
cookie value can't contains "=" character.

### ISSUE THREAD

**Issue by butnet** [golang/go#31029]
https://github.com/golang/go/blob/68a98d52794fc324841f62732411f6bba23fc62c/src/net/http/cookie.go#L359

I change to
`	if strings.IndexByte(v, ' ') >= 0 || strings.IndexByte(v, ',') >= 0 || strings.IndexByte(v, '=') >= 0 {`

**Comment by agnivade** [comment]
Please fill the complete issue template, mentioning what you did, what you say and what you expected. A self-contained code sample which shows the issue is preferred.

**Comment by vdobler** [comment]
According to https://tools.ietf.org/html/rfc6265#section-4.1.1 the cookie-value consists of cookie-octets which **do** allow 0x3d '=' (covered by the range %x3C-5B). Also all browsers accept = signs in cookie values. Quoting a cookie-value containing a '=' is not necessary.

What is this issue addressing?
