### ISSUE TITLE
proposal: please try to make your promised Google-run module proxy not blocked in China

### ISSUE THREAD

**Issue by aofei** [golang/go#31020]
Of course, I know this is our own problem. However, in order for Go to be better spread around the world, China is an indispensable part, isn't it?

According to @rsc mentioned in [Go Modules in 2019](https://blog.golang.org/modules2019), Go will serve a Google-run module proxy for the `go` command by default in Go 1.13. That would be great, at least I think so.

> ...
> We are planning to launch a mirror service for publicly-available modules in 2019.
> ...
> We are aiming to have the Google-run module mirror ready to be used by default in the go command starting in Go 1.13. Using an alternate mirror, or no mirror at all, will be trivial to configure.
> ...

I really like the concept of Go modules, and I believe that the Go community will build the first deptopia in the programming language world. Language without std libraries? Amazing! However, it's difficult to enjoy all of this in my home country. Not because of the Go itself, but because of some problems between our country's government and Google, since Google has full control over Go, so...

For example, https://golang.org has been completely blocked in our country. The well-known Go's official website is not accessible to any corner of China's mainland unless you use some workaround like a VPN. Guess what, [Rust's official website](https://www.rust-lang.org), [Java's official website](https://www.oracle.com/java), [Python's official website](https://www.python.org), [Ruby's official website](https://www.ruby-lang.org), they can all be normally accessed in China without any special treatment. Why can't Go? My best guess is that Go's official website runs on Google's server cluster, and Google's server cluster has been completely blocked by our country. I'm curious, is it really difficult to move the Go's official website out of the Google's server cluster? Even moved to [Google Cloud Platform](https://cloud.google.com)? Maybe it is. I'm not going to struggle with it, after all, you also run a [proxy website](https://golang.google.cn) for us (even almost no one knows it).

I also noticed the #28652, I was surprised, the best solution you can give is to use `go mod edit -replace` to replace `golang.org/x` with something else... well, anyway, I believe that problems like #28652 may be alleviated in Go 1.13. So let's talk about the module proxy that Go 1.13 is about to introduce.

Although I'm currently discussing with China's well-trusted cloud service provider [Qiniu Cloud](https://qiniu.com)'s CEO to build a trusted Go module proxy in China (called [Goproxy China](https://github.com/aofei/goproxy.cn), not officially released yet), I still hope that the Go's default proxy can also be accessed in China. I know that you have the ability to do it, or you can ask the Google Analytics team for some advice. FYI, Google Analytics works like a charm in China.

So, please, please try your best to make your promised Google-run module proxy not blocked in China! 🙏

**Comment by agnivade** [comment]
@aofei - Welcome to the Go project. This sounds more like a request than a concrete proposal.

This has been discussed here https://github.com/golang/go/issues/25530#issuecomment-469583362. If you want to add your suggestions, I would request you to please feel free to comment there. Or on this golang-dev thread here - https://groups.google.com/forum/#!topic/golang-dev/DD88cds-LuI%5B1-25%5D.

This is a sub-issue of the main parent issue #25530 and should be part of that. I will close this now. And please do post your thoughts on any of the channels mentioned above. Thanks.
