### ISSUE TITLE
access: Trybot Access ("may-start-trybots") and approver access ("approvers")

### ISSUE THREAD

**Issue by bsiegert** [golang/go#31037]
https://go-review.googlesource.com/#/admin/groups/1030,members
https://go-review.googlesource.com/#/admin/groups/1005,members

See https://golang.org/wiki/GerritAccess

I would like to have access to start trybots and to +2 CLs.

I have been active in the Go project since 2010 or so. Among other things, I maintain the netbsd builders. As a Googler, I am an active Go user and mentor internally.

Recently, I have begun sending CLs more regularly. At least one of them was stuck waiting for +2 for a while.

@mvdan suggested that I file for access.

**Comment by dmitshur** [comment]
Hi @bsiegert,

Thank you for contributing to the Go project and helping maintain some of the builders! I've discussed this request with the team (/cc @golang/osp-team), and we agreed to grant you access (some people thought you already had +2 rights and were surprised to learn you didn't; that's a good sign that you should have it). I've added you to the `may-start-trybots` and `approvers ` groups now.

As you've probably seen at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a trybot run.

Similarly, please be aware of the rules for submitting and voting on CLs described at https://golang.org/wiki/GerritAccess#approver-access-approvers. If you're unsure or have any questions, please don't hesitate to ask us.

Thank you again, your help is greatly appreciated!
