### ISSUE TITLE
cmd/go: error message refers to "." instead of the path provided on the command line

### ISSUE THREAD

**Issue by pjweinb** [golang/go#31031]
### What version of Go are you using (`go version`)?
go version go1.12 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
linux

### What did you do?
go build cmd/gopls

and it says
can't load package: package cmd/gopls: cannot find package "." in:
	/usr/lib/google-golang/src/cmd/gopls

Note that . is not mentioned anywhere in the command, nor is there an "import ." anywhere either.

Of course,
go build ./cmd/gopls works,
but the other error message is not helpful.

**Comment by bcmills** [comment]
Please complete the issue template.

In particular, we need the `go env` output to determine whether you are running in module mode or `GOPATH` mode, since the package-resolution logic differs between the two modes.

**Comment by bcmills** [comment]
CC @jayconrod

**Comment by jayconrod** [comment]
Reproduced in both modes in Go 1.12.4.

However, the error message is different at tip.

```
$ GO111MODULE=on go build cmd/gopls
can't load package: package cmd/gopls: unknown import path "cmd/gopls": cannot find module providing package cmd/gopls
```

```
$ GO111MODULE=off go build cmd/gopls
can't load package: package cmd/gopls: cannot find package "cmd/gopls" in any of:
	/Users/jayconrod/Code/go/src/cmd/gopls (from $GOROOT)
	/Users/jayconrod/go/src/cmd/gopls (from $GOPATH)
```

I think the GOPATH message is fine, but the module error message could be improved.

**Comment by bcmills** [comment]
It's actually even worse now. 😞

```
example.com$ gotip version
go version devel +2165452a Fri May 31 11:26:23 2019 +0000 linux/amd64

example.com$ gotip mod init example.com
go: creating new go.mod: module example.com

example.com$ gotip build cmd/gopls
can't load package: package cmd/gopls: unknown import path "cmd/gopls": explicit requirement on standard-library module cmd not allowed

example.com$
```
