### ISSUE TITLE
bytes: TrimSpace returns non-nil byte slice when given all-space input

### ISSUE THREAD

**Issue by andybons** [golang/go#31038]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +501632339f Mon Mar 25 18:16:51 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
No. This is a regression from go1.12.1 and earlier.

```
package main

import (
	"bytes"
	"fmt"
)

func main() {
	fmt.Println(bytes.TrimSpace([]byte("   ")) == nil)
}
```

On tip (1.13) it outputs `false` while on previous versions it prints `true`. This was caused by  https://golang.org/cl/152917 because it no longer uses `bytes.TrimFunc(s, unicode.IsSpace)` which calls `bytes.TrimLeftFunc` on an empty string, causing it to return nil due to `indexFunc` returning -1:

```
// TrimFunc returns a subslice of s by slicing off all leading and trailing
// UTF-8-encoded code points c that satisfy f(c).
func TrimFunc(s []byte, f func(r rune) bool) []byte {
	return TrimRightFunc(TrimLeftFunc(s, f), f)
}

// TrimLeftFunc treats s as UTF-8-encoded bytes and returns a subslice of s by slicing off
// all leading UTF-8-encoded code points c that satisfy f(c).
func TrimLeftFunc(s []byte, f func(r rune) bool) []byte {
	i := indexFunc(s, f, false)
	if i == -1 {
		return nil
	}
	return s[i:]
}

// TrimRightFunc returns a subslice of s by slicing off all trailing
// UTF-8-encoded code points c that satisfy f(c).
func TrimRightFunc(s []byte, f func(r rune) bool) []byte {
	i := lastIndexFunc(s, f, false)
	if i >= 0 && s[i] >= utf8.RuneSelf {
		_, wid := utf8.DecodeRune(s[i:])
		i += wid
	} else {
		i++
	}
	return s[0:i]
}

```

It seems weird that `TrimRightFunc` returns a non-nil slice every time, while `TrimLeftFunc` returns a nil slice if it can't find a rune that satisfies `f(c)`, but I imagine changing that behavior would cause more breakage in weird places.

@benhoyt @josharian

**Comment by FiloSottile** [comment]
This is unfortunate, because "returns a subslice of s" to me suggests it returns an empty slice, not nil, on an all-space input. (Might not be worth breaking, though.)

**Comment by josharian** [comment]
This is unfortunate, indeed, but we should try to preserve the existing behavior. From a glance, looks like we just need to replace `return s[start:stop]` with `r := s[start:stop]; if len(r) == 0 { r = nil }; return r`. @benhoyt are you interested in following up on this? I.e. investigate more deeply, write some tests, and send a CL?

**Comment by benhoyt** [comment]
@josharian Yes, I'm interested in following up. What timeline are we looking at? I can probably do this in the next 7-10 days.

Are we definitely sure we want to preserve backwards compatibility here, and the weirdness? Or move to always returning a non-nil slice?

**Comment by josharian** [comment]
Sooner is better of course, but we have at least a month worst case. If it is remotely reasonable, let’s remain perfectly backwards compatible, weird or no.

**Comment by andybons** [comment]
Spoke with @ianlancetaylor about this and while it is odd behavior and people shouldn't be relying on these functions returning a nil slice in practice, it's not worth the breakage of code that does.

**Comment by benhoyt** [comment]
Submitted. While I was in there, I noticed there were no tests for `TrimLeftFunc` or `TrimRightFunc` (though there are a couple of examples for each). It seems like there should be tests for these, including the nil-returning case, so if you folks agree I can submit another CL for that (should I open a new issue as well?).

**Comment by ianlancetaylor** [comment]
Some tests would be nice, yes, in a separate CL.  No need to open an issue.  Thanks.
