### ISSUE TITLE
cmd/vet/all: get golang.org/x/tools/go/analysis/cmd/vet via a go.mod file, not via coordinator

### ISSUE THREAD

**Issue by bradfitz** [golang/go#31040]
The cmd/vet/all program right now builds golang.org/x/tools/go/analysis/cmd/vet using the x/tools repo head tree places there by the x/build/cmd/coordinator.

Several problems with that, including:

* it doesn't work on release branches
* it's extra complication in the coordinator

It'd be nicer if cmd/vet/all just use modules mechanism & its versioning to get at x/tools/go/analysis/cmd/vet instead.

And then the coordinator could be simplified (https://golang.org/cl/169198).

/cc @dmitshur @bcmills @josharian

**Comment by dmitshur** [comment]
`cmd/vet/all` is inside the `cmd` module, and its go.mod file specifies a version of the golang.org/x/tools module. Is it not being used?

https://github.com/golang/go/blob/e6df1799791fac7262effe4464bd5c82bbb275cb/src/cmd/go.mod#L11

**Comment by bradfitz** [comment]
Maybe! We could remove all the code in the coordinator for it and disable it on Go 1.12 and earlier release branches and see what happens.

**Comment by dmitshur** [comment]
> and see what happens

FWIW, the x/tools version currently specified in the `cmd` module go.mod file predates both CL 168404 (which caused #30971) and CL 168803 (which fixed it), so it should pass. When updating to a newer version, we should use golang/tools@6aabc1ca790df3e0b556593b27bc25d26b151751 or newer.

**Comment by bradfitz** [comment]
All submitted for master.

Over to @dmitshur if he wants to backport the cmd/vet/all changes to Go 1.11 and Go 1.12. (They're builder-only things and don't affect end users, where the tests are disabled by default anyway)

**Comment by bcmills** [comment]
> Over to @dmitshur if he wants to backport the cmd/vet/all changes to Go 1.11 and Go 1.12.

The `cmd/vet/all` changes seem to require the presence of `cmd/go.mod`, which may be difficult to backport.

(We can always just try it and see, but many tests in `cmd` had to be updated for #30228: search for `cmd/` in the gopherbot mention-links.)

**Comment by bradfitz** [comment]
> On the other hand, it might be straightforward to add a cmd/vet/all/go.mod in those releases.

That was my thought. It should be a very basic go.mod file with a single line.

**Comment by laboger** [comment]
I'm not sure if this is the right place to report this, but I'm seeing trybot failures from cmd/vet/all in my CL https://go-review.googlesource.com/c/go/+/168478. At first I thought it was unrelated to my change (which is only for crypto/elliptic asm on ppc64le so I don't understand how that could affect vet running other platforms) but after I rebased and reran, it gave me some errors in my asm which I fixed. After fixing those errors, I uploaded the fix, reran the trybots, and I am seeing some other odd errors in vet/freebsd/arm.

How can a run the equivalent of misc-vet-all for testing before I submit a change? I don't see it run from ./all.bash.

**Comment by bcmills** [comment]
> How can a run the equivalent of misc-vet-all for testing before I submit a change?

`cd $(go env GOROOT)/src/cmd/vet/all && go run main.go -p linux/ppc64`

**Comment by ianlancetaylor** [comment]
I think you just need to rebase forward.  I hope.

**Comment by bradfitz** [comment]
Looks like it. The latest patchset git parent is old.

**Comment by laboger** [comment]
OK, thanks. I thought I had rebased once yesterday but looks like I just uploaded a new patch.

**Comment by bradfitz** [comment]
This happened in the CLs above and is working well.
