### ISSUE TITLE
cmd/compile: possible oversight with internal/gc.disableExport

### ISSUE THREAD

**Issue by odeke-em** [golang/go#31049]
I was just studying closure.go and noticed that we invoke disableExport(sym) for closures created.
The signature for disableExport says
https://github.com/golang/go/blob/0ec302c49ee3dd1a7f290db9a326bbfb734e8c35/src/cmd/compile/internal/gc/dcl.go#L1005-L1006

However, in the body of disableExport we see that we invoke `sym.SetOnExportList(true)`
which toggles the symbol to be exported as per https://github.com/golang/go/blob/0ec302c49ee3dd1a7f290db9a326bbfb734e8c35/src/cmd/compile/internal/types/sym.go#L55

This change is from [CL 108216](https://go-review.googlesource.com/108216)

I believe it should be `sym.SetOnExportList(false)`
The bug only doesn't show because when creating object files we explicitly check that names are exported as per https://github.com/golang/go/blob/0ec302c49ee3dd1a7f290db9a326bbfb734e8c35/src/cmd/compile/internal/gc/export.go#L56-L58
otherwise if you add debugs you'll see that we encounter closure symbols such as `"".bar.func1` 

Kindly paging @mdempsky @griesemer

**Comment by mdempsky** [comment]
Thanks @odeke-em , but I believe it's correct as-is. The OnExportList flag is used by [exportsym](https://github.com/golang/go/blob/0ec302c49ee3dd1a7f290db9a326bbfb734e8c35/src/cmd/compile/internal/gc/export.go#L28) to avoid adding a symbol to exportlist if it's already been added. The way disableExport works is that it sets OnExportList before exportsym is called, so that exportsym thinks the symbol has already been added to exportlist and avoids adding it again.

**Comment by odeke-em** [comment]
Thanks for the reply @mdempsky!
Yes, I saw that before but I now understand the purpose of it and context of usage after your reply, thanks!

Perhaps let's rename that helper function to `hideFromExportSym` instead of `disableExporting`? `disableExporting` to me seems like we are requesting that regardless of its case, prevent it from being exported.

Perhaps let's think of a different marking naming, because `(*types.Sym).OnExportList` for closures within functions (especially those that have names such as `"".bar.func1`) is a little confusing, just from reading through the source code.

**Comment by josharian** [comment]
@odeke-em feel free to leave renaming suggestions over at https://github.com/golang/go/issues/27167

**Comment by odeke-em** [comment]
Cool, thanks @josharian I've made the suggestion at https://github.com/golang/go/issues/27167#issuecomment-476968159

and with that I'll close this issue. Thank you @mdempsky for the response too.
