### ISSUE TITLE
net: DialTimeout w/ "udp4" or "udp6" failing

### ISSUE THREAD

**Issue by baloo32** [golang/go#31058]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, however, it is not present in v1.11.5 (this is last known good version).

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=D:\Development\Go\bin
set GOCACHE=C:\Users\XXXX\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Development\work\go
set GOPROXY=
set GORACE=
set GOROOT=D:\Development\Go
set GOTMPDIR=
set GOTOOLDIR=D:\Development\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\XXXX\AppData\Local\Temp\go-build594754674=/tmp/go-build -gno-record-gcc-switches
</pre></details>

Windows 10 Professional Version 1809 (OS Build 17763.379) x64
MongoDB version 3.6.11
Golang version 1.12.1

### What did you do?

Using the MGO driver (github.com/globalsign/mgo) to connect to a MongoDB instance using the driver's Dial function.

Sample code:

<pre>
package db

import (
	"errors"
	"fmt"
	"log"
	"sync"
	"time"

	mgo "github.com/globalsign/mgo"
)

// MongoDB is a shortcut structure to a MongoDB Database
type MongoDB struct {
	*mgo.Database
}

// MDB is main DB
var MDB *MongoDB
var mainDBOnce sync.Once

// DialMainDB creates new Mongo session with main DB. Always once.
func DialMainDB(dbHost, dbName string) (err error) {
	if dbName == "" {
		return errors.New("dbHost is not defined")
	}
	if dbName == "" {
		return errors.New("dbName is empty")
	}
	var mgoSession *mgo.Session
	mainDBOnce.Do(func() {
		// Dial Mongo - get session
		mgoSession, err = mgo.Dial(dbHost)
		if err != nil {
			return
		}
		// Check session is alive
		err = mgoSession.Ping()
		if err != nil {
			return
		}

		MDB = &MongoDB{mgoSession.DB(dbName)}
	})
	return err
}
</pre>

### What did you expect to see?
On versions prior to 1.12.1 the connection to local Mongo is established in less than a second and a correct session and no error is returned from the function. Code is then able to connect and execute against MongoDB.

### What did you see instead?
Attempts to connect run for ~10 seconds before timing out. No connection is established, no connection request is seen in the Mongo logs and the session creation fails - program terminates.

The issue has been raised on the driver's Git pages (see https://github.com/globalsign/mgo/issues/338#issuecomment-475520400) however, initial debugging points to change in Go `net` package issue instead of mgo driver.

**Comment by mikioh** [comment]
Sounds like the DNS stub resolver is broken in Go 1.12. Can you please confirm that the issue still happens when GODEBUG=netdns=go on non-Windows platforms. If not, the root cause is probably #30521.

**Comment by baloo32** [comment]
I don't have access to non-Windows platform - sorry. Will cross post to other repo to see if anyone there can try.

**Comment by baloo32** [comment]
User on Mac replied with:

when using the `GODEBUG=netdns=go` on Mac OS X 10.14.18A391 with go1.12.1 darwin/amd64 the issue is resolved.

https://github.com/globalsign/mgo/issues/338#issuecomment-477119294

**Comment by mikioh** [comment]
Thanks for the confirmation. Will merge this issue into #30521 and #31062 is just for tracking the backport to Go 1.12.
