### ISSUE TITLE
cmd/go: binaries built with `test -c` do not support `-json` option

### ISSUE THREAD

**Issue by ijc** [golang/go#31051]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

I believe 1.12.1 is latest, so yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
/go # go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build705366494=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I am building a test binary using `go test -c` (with the intention of running the actual test on another host, which has no Go toolchain installed) and I would like to use it with [`gotestsum`](https://github.com/gotestyourself/gotestsum) (primarily for the `--junitfile` support to integrate with Jenkins).

However the binaries built this way do not support the `-json` option required by `gotestsum` (nor does it support `-test.json`).

`go test --json ./` produces `json` output while:
```
$ go test -o foo -c ./
$ ./foo -json
flag provided but not defined: -json
$ ./foo -test.json
flag provided but not defined: -test.json
```

I'm aware that I can pipe the output of my test binary to `go tool test2json` but this is inconvenient since the target host lacks Go. I'm going to experiment with working around this by using `TestMain` to inject something like the code which backs the `-json` option on `go test` (https://github.com/golang/go/blob/master/src/cmd/go/internal/test/test.go#L1045...L1049), but it would be great if this just worked.

### What did you expect to see?

Support for the `-json` option in my test binary built with `go test -s`

### What did you see instead?

No support for `-json` in that binary.

**Comment by ijc** [comment]
> I'm going to experiment with working around this by ...

I fell at the first hurdle, because `test2json` is in an internal package...

**Comment by agnivade** [comment]
`test2json` is just another binary which lives in `$GOROOT/pkg/tool/linux_amd64`. So you can just copy foo and test2json in the target host.

**Comment by ijc** [comment]
Thanks, but the other host is actually (sometimes) running a different OS (i.e. the build is sometimes a cross-build, sorry, I should have mentioned that!) so it's sadly not as simple as just a copy for me.

**Comment by agnivade** [comment]
@bcmills @rsc

**Comment by ianlancetaylor** [comment]
I believe this is in effect a dup of #22996.

**Comment by agnivade** [comment]
Agree. @ijc - please have a look at @rsc's comment on the issue. The solution is to do a cross-platform build of test2json. I will close this as it was rejected before. Please feel free to reopen if you think otherwise.

**Comment by ijc** [comment]
Thanks and sorry for not finding the previous issue (I did search, I promise).

I understand the issues from #22996, it's not ideal but I think I can lash something together, thanks!

**Comment by tiny-dancer** [comment]
For future diggers: https://github.com/gotestyourself/gotestsum/issues/77
