### ISSUE TITLE
cmd/compile: bitwise OR of fp constants triggers an internal compiler error

### ISSUE THREAD

**Issue by nsajko** [golang/go#31060]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/tmp/freedesktopCache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/nsajko"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build891538814=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/__u_Ihvs3Vg

### What did you expect to see?

No "internal compiler error". Probably a message like "operator | not defined on floating point constants" would be nice.

### What did you see instead?
<pre>internal compiler error: binaryOp: bad operation: 3.5 | 2.8</pre>

**Comment by josharian** [comment]
cc @mdempsky

**Comment by mark-rushakoff** [comment]
Looks like was not an ICE in 1.11.

```
$ go version; go build x.go
go version go1.11.4 darwin/amd64
# command-line-arguments
./x.go:8:18: illegal constant expression: untyped number | untyped number
```

**Comment by mdempsky** [comment]
Technically, an "illegal constant expression" was still an ICE. ;)

But yes, hmm, this is definitely related to my const.go refactoring. I'll take a look.

**Comment by mdempsky** [comment]
This might be worth backporting to Go 1.12. It's only affects invalid Go code (i.e., failing with ICE instead of emitting a proper compiler error), but it's still technically a regression in Go 1.12 from Go 1.11.

**Comment by ianlancetaylor** [comment]
The guideline on backports isn't to fix all regressions, it's to only backport patches that fix serious bugs with no workaround.  There is always a workaround for invalid code, so I don't think we need to backport this.

**Comment by mdempsky** [comment]
@ianlancetaylor Okay, SGTM.
