### ISSUE TITLE
x/tools/packages: nil file set

### ISSUE THREAD

**Issue by BlakeMScurr** [golang/go#31066]
### What version of Go are you using?

<pre>
go version go1.12.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

It reproduces with the current tip of master [3ad05305](https://github.com/golang/tools/commit/3ad05305c9b0e30fce8bcbef2a43203fc3beb792), but I was not able to identify the version of tools that was released in go `1.12.1` or `1.12`. The [1.12 release notes](https://golang.org/doc/go1.12#tools) don't specify versions for subrepos, and the [tools github mirror](https://github.com/golang/tools) has no releases. What, if anything, am I missing?

### What operating system and processor architecture are you using?

<details><summary><code>go env</code></summary>

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/matt/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/matt/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build257393927=/tmp/go-build -gno-record-gcc-switches"
<br><pre>
$ go env

</pre></details>

### What did you do?

Ran a program that tests every package loading mode to see if the Fset is ever set:

```go
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"

	"golang.org/x/tools/go/packages"
)

func main() {
	if err := testPackageLoader(); err != nil {
		fmt.Fprintf(os.Stderr, err.Error())
		os.Exit(1)
	}
}

func testPackageLoader() error {
	modes := []packages.LoadMode{
		packages.LoadFiles,
		packages.LoadImports,
		packages.LoadTypes,
		packages.LoadSyntax,
		packages.LoadAllSyntax,
	}

	for i, mode := range modes {
		fmt.Println("testing mode", i)
		// Load packages

		conf := &packages.Config{
			Mode: mode,
		}

		packagePkgs, err := packages.Load(conf, "path/to/anaylsed/package")
		if err != nil {
			return err
		}

		errs := []error{}
		packages.Visit(packagePkgs, nil, func(pkg *packages.Package) {
			for _, err := range pkg.Errors {
				errs = append(errs, err)
			}
		})
		if len(errs) != 0 {
			return errs[0]
		}

		fmt.Println(conf.Fset)
	}
	return nil
}
```

where `"path/to/anaylsed/package"` has a single go file:

```
package main

func main() {
	f()
}

func f() {}
```

### What did you expect to see?

Non-nil fsets for the more complete modes. Something like:
```
testing mode 0
<nil>
testing mode 1
<nil>
testing mode 2
<nil>
testing mode 3
&{{{0 0} 0 0 0 0} 50 [0xc000141260] 0xc000141260}
testing mode 4
&{{{0 0} 0 0 0 0} 50 [0xc000160ae0] 0xc000160ae0}
```

### What did you see instead?

```
testing mode 0
<nil>
testing mode 1
<nil>
testing mode 2
<nil>
testing mode 3
<nil>
testing mode 4
<nil>
```

### Workaround

I was able to populate the config's Fset by setting its `ParseFile` function like so:

```Go
parseFile := func(fset *token.FileSet, filename string, src []byte) (*ast.File, error) {
	var isrc interface{}
	if src != nil {
		isrc = src
	}

	conf.Fset = fset

	const mode = parser.AllErrors | parser.ParseComments
	return parser.ParseFile(fset, filename, isrc, mode)
}

conf.ParseFile = parseFile
```

but this seems like a hacky and fragile workaround. Can I do this better? This can be fixed in `tools` by updating `cfg.fset` to `l.fset` after calling `refine` [here](https://github.com/golang/tools/blob/master/go/packages/packages.go#L178). Does that make sense?

Thanks,
Blake

**Comment by agnivade** [comment]
@ianthehat @matloob

**Comment by ianthehat** [comment]
The config is meant to be an input, not an output.
Rather than try to extract the fileset from the Load call, instead you build a new fileset and set it on the config before the call.
I will close this bug for now, but feel free to re-open it if my answer is not working for you.
