### ISSUE TITLE
Go should include an official module version parser function

### ISSUE THREAD

**Issue by nim-nim** [golang/go#31077]
Go modules defined their own version syntax and ordering rules.  Because this syntax is Go-specific, it needs translation in generic non-Go-specific software management tools. Those tools have their own syntax rules, and raw Go version syntax will either be incompatible with the other software management syntax, or will produce different version ordering than the one expected by Go people.

Since Go version syntax is constructed around semver, and semver.org tried to sum up industry best practices, translating mostly involves parsing the individual components of a Go version, and reformatting them in the format the other tool expect (with possibly slightly different separators).

Practically, reliable translation requires:
* a clear Go spec, that documents the module version formats go will output, and their expected ordering
* a reference Go version parser function, that transforms a raw Go module version string in the elements used by this spec

My understanding of the `go help module` text is that the expected range of Go versions and pseudo-versions, and their ordering, is:

```
vX.0.0-yyyymmddhhmmss-abcdefabcdef
vX.0.0-pre
vX.0.0-pre.0.yyyymmddhhmmss-abcdefabcdef
vX.0.0
vX.Y.Z-0.yyyymmddhhmmss-abcdefabcdef
vX.Y.Z-pre
vX.Y.Z-pre.0.yyyymmddhhmmss-abcdefabcdef
vX.Y.Z
vX.Y.(Z+1)-0.yyyymmddhhmmss-abcdefabcdef
vX.Y.(Z+1)-pre 
```

It would be nice to have it confirmed (or corrected) and traced somewhere official.

My understanding of those version templates, is that they are composed of

```
type ModVersion struct {
  Version   string
  Time      time.Time
  Pre       string
  ShortHash string
  Build     string  // Just to get it parsed, even though it will be ignored in version comparisons
}
```

And anything else is not significant, and can be deduced from the other fields.

It would be nice to have it confirmed (or corrected) and traced somewhere official.

My understanding is that one can parse those fields with something like

```go
  versionGr   := `(?P<version>\d+\.\d+\.\d+)`
  timeGr      := `(?P<time>\d{4}[0-1]\d[0-3]\d[0-2]\d[0-5]\d[0-5]\d)` // yyyymmddhhmmss
  preGr       := `(?P<pre>[[:alnum:]]([[:alnum:]-.]*[[:alnum:]])?)`
  shortHashGr := `(?P<shorthash>[0-9a-fA-F]{12})`
  buildGr     := `\+(?P<build>[[:alnum:]-.]+)`
  re := regexp.MustCompile(`^v` + versionGr + `((-((` + preGr + `\.)?0\.)?` + timeGr + `-` +  shortHashGr + `)|(-` + preGr + `)?)(` + buildGr + `)?$`)
```

It would be nice to have it confirmed (or corrected), and better have an official parsing function, so there's no ambiguity on what the Go module version spec actually intends.

**Comment by josharian** [comment]
IIRC the original module proposal indicated that there would be a public package available for parsing and printing go.mod. Perhaps the work simply has not been done yet?

cc @bcmills @jayconrod

**Comment by jayconrod** [comment]
[cmd/go/internal/semver](https://godoc.org/cmd/go/internal/semver) is the package that parses and compares semver within the Go command. There's an unofficial copy at [github.com/rogpeppe/go-internal/semver](https://godoc.org/github.com/rogpeppe/go-internal/semver).

We'll eventually need to move this package and others out of `cmd/go/internal` so that tools can use them. #28101 is the tracking issue for that. I'll close this as a duplicate.

**Comment by nim-nim** [comment]
@jayconrod 

[cmd/go/internal/semver](https://godoc.org/cmd/go/internal/semver) is pretty useless because it only deals with full semvers not the 4? pseudoversions Go modules grew up since, it does not return the components used to construct those pseudoversions, and it does not document clearly the intended ordering of the various pseudoversions Go modules use.

**Comment by nim-nim** [comment]
And pseudoversions are the only non-standard Go-specific part of Go module versionning, so they're the most difficult element to translate.

**Comment by jayconrod** [comment]
[cmd/go/internal/modfetch](https://godoc.org/cmd/go/internal/modfetch) is probably what you're looking for then.

**Comment by nim-nim** [comment]
@jayconrod Thanks, that looks like the actual pseudoversion parsing code. So that will answer the official parsing function part whenever it's moved from internal to something else.

That still does not answer if my pseudoversion list and its ordering are correct or not, or if I misunderstood `go help module` (which is not too clear on the subject).

**Comment by bcmills** [comment]
@nim-nim, pseudo-versions follow the same ordering as any other semantic version. (See [semver.org](https://semver.org) for details.)

**Comment by nim-nim** [comment]
@bcmills not really, because `vx.y.z.-0.2` is a valid semver pre-version and go help modules sort of implies that `vx.y.z.-0.yyyymmddhhmmss-abcdefabcdef` should be ordered before it, and `vx.y.z.-0.2.0.yyyymmddhhmmss-abcdefabcdef` after it (and I'm still trying to figure why the go code finds it necessary to inject a '.0.' after the pre-version.

**Comment by nim-nim** [comment]
But anyway, I'm not here to tell the Go project how to generate its module versions, that's its module versions go does as it wants to, I just want to have a clear spec on all the versions and pseudo-versions it generates, and how each version string should be ordered WRT other version strings
