### ISSUE TITLE
x/build/cmd/gopherbot: add command to rebase CLs

### ISSUE THREAD

**Issue by matloob** [golang/go#31085]
Hi,

I often want to make sure that a change will pass trybots once it's applied to head. It seems like the only way to do that is to rebase the change, and then run trybots. So it would be nice if we could easily rebase CLs on gerrit (we currently need the "Forge Author" permission).

**Comment by dmitshur** [comment]
> I often want to make sure that a change will pass trybots once it's applied to head.

We can achieve this either by allowing rebasing, or by making trybots able to do this as part of testing. /cc @bradfitz

**Comment by agnivade** [comment]
> We can achieve this either by allowing rebasing, or by making trybots able to do this as part of testing

That's https://github.com/golang/go/issues/9858
