### ISSUE TITLE
misc/cgo/test: make sure we run TestCrossPackageTests with appropriate options

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#31083]
In https://golang.org/cl/163418 we started running several of the tests in misc/cgo/test via a separate invocation of `go test`.  In cmd/dist we run the tests in misc/cgo/test with several different `-linkmode` options; see `(*tester).cgoTest` in cmd/dist/test.go.  But as far as I can see those different options are not being carried through the separate invocation of `go test` in `TestCrossPackageTests`, so we are no longer testing all the cases we did before.

This issue is to make sure that we run those tests with the appropriate options.

CC @bcmills

**Comment by bcmills** [comment]
`TestCrossPackageTests` explicitly propagates `os.Environ()`, so it would probably suffice to set whatever options are needed in the `GOFLAGS` variable before running the test.
