### ISSUE TITLE
x/tools/internal/lsp/protocol: vet failures for json tags

### ISSUE THREAD

**Issue by myitcv** [golang/go#31090]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +478f3a5384 Wed Mar 27 16:21:00 2019 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20190325223049-1d95b17f1b04
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPROXY=""
GORACE=""
GOROOT="/home/myitcv/gos"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build072271407=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version devel +478f3a5384 Wed Mar 27 16:21:00 2019 +0000 linux/amd64
GOROOT/bin/go tool compile -V: compile version devel +478f3a5384 Wed Mar 27 16:21:00 2019 +0000
uname -sr: Linux 4.15.0-46-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.27-3ubuntu1) stable release version 2.27.
</pre></details>

### What did you do?

```
$ go vet golang.org/x/tools/internal/lsp/protocol
# golang.org/x/tools/internal/lsp/protocol
../../../../pkg/mod/golang.org/x/tools@v0.0.0-20190325223049-1d95b17f1b04/internal/lsp/protocol/tsprotocol.go:1023:2: struct field TextDocument repeats json tag "textDocument" also at tsprotocol.go:1012
../../../../pkg/mod/golang.org/x/tools@v0.0.0-20190325223049-1d95b17f1b04/internal/lsp/protocol/tsprotocol.go:1024:2: struct field TextDocument repeats json tag "textDocument" also at tsprotocol.go:1012
../../../../pkg/mod/golang.org/x/tools@v0.0.0-20190325223049-1d95b17f1b04/internal/lsp/protocol/tsprotocol.go:1025:2: struct field Workspace repeats json tag "workspace" also at tsprotocol.go:1007
../../../../pkg/mod/golang.org/x/tools@v0.0.0-20190325223049-1d95b17f1b04/internal/lsp/protocol/tsprotocol.go:1026:2: struct field Workspace repeats json tag "workspace" also at tsprotocol.go:1007
../../../../pkg/mod/golang.org/x/tools@v0.0.0-20190325223049-1d95b17f1b04/internal/lsp/protocol/tsprotocol.go:1027:2: struct field TextDocument repeats json tag "textDocument" also at tsprotocol.go:1012
../../../../pkg/mod/golang.org/x/tools@v0.0.0-20190325223049-1d95b17f1b04/internal/lsp/protocol/tsprotocol.go:1028:2: struct field TextDocument repeats json tag "textDocument" also at tsprotocol.go:1012
../../../../pkg/mod/golang.org/x/tools@v0.0.0-20190325223049-1d95b17f1b04/internal/lsp/protocol/tsprotocol.go:1029:2: struct field TextDocument repeats json tag "textDocument" also at tsprotocol.go:1012
../../../../pkg/mod/golang.org/x/tools@v0.0.0-20190325223049-1d95b17f1b04/internal/lsp/protocol/tsprotocol.go:1030:2: struct field TextDocument repeats json tag "textDocument" also at tsprotocol.go:1012
../../../../pkg/mod/golang.org/x/tools@v0.0.0-20190325223049-1d95b17f1b04/internal/lsp/protocol/tsprotocol.go:2321:2: struct field Kind repeats json tag "kind" also at tsprotocol.go:2291
../../../../pkg/mod/golang.org/x/tools@v0.0.0-20190325223049-1d95b17f1b04/internal/lsp/protocol/tsprotocol.go:2361:2: struct field Kind repeats json tag "kind" also at tsprotocol.go:2291
../../../../pkg/mod/golang.org/x/tools@v0.0.0-20190325223049-1d95b17f1b04/internal/lsp/protocol/tsprotocol.go:2406:2: struct field Kind repeats json tag "kind" also at tsprotocol.go:2291
```

### What did you expect to see?

A clean vet run

### What did you see instead?

The above failures

cc @stamblerre

**Comment by stamblerre** [comment]
cc @pjweinb

**Comment by stamblerre** [comment]
This was fixed by https://golang.org/cl/171026.
