### ISSUE TITLE
cmd/cgo: uint64_t used to permit C.ulong, but no longer does

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#31093]
This program works fine with Go 1.12.

```Go
package main

// #include <stdint.h>
// static uint64_t foo(uint64_t v) { return v; }
import "C"

import "fmt"

func main() {
	i := 0
	j := C.foo(C.ulong(i))
	fmt.Printf("%T %d\n", j, j)
}
```

With current tip, it fails to build with

```
# command-line-arguments
foo.go:11:20: cannot use _Ctype_ulong(i) (type _Ctype_ulong) as type uint64 in argument to _Cfunc_foo
```

This is a consequence of the change for #29878.  We need to address it one way or another.

CC @phst

**Comment by rsc** [comment]
I am having a similar problem in a cgo program of mine that built in Go 1.12.
The C code contains 

	typedef uint8_t other_t;

and I used to be able to pass a Go `*C.uchar` to a C function expecting `other_t*`.
Now that code does not compile.

The good news is that if I fix the code to use `*C.other_t` then it compiles
both with current master and Go 1.12. 

I guess the first question is whether we think cgo _should_ be this picky.
Maybe if we were starting from scratch.
Ten years in, I am reluctant to break old code.

Should we tell cgo the go version from the go.mod file
and only do this for explicit go1.13 or later?

Or should we roll back #29878? 
I mean, there are zero systems where
char, short, int, and long long are not 8, 16, 32, and 64 bits.

**Comment by ianlancetaylor** [comment]
I agree that cgo should not be this picky.  I haven't thought about whether there is a way to fix this, or whether we need to roll back.  If rolling back is the only way to let existing code continue to build, then I think we should roll back.
