### ISSUE TITLE
cmd/compile: assignment pluralization grammatical error

### ISSUE THREAD

**Issue by nobozo** [golang/go#31099]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jonf/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jonf/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build622067500=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

https://play.golang.org/p/7R1_1wboUZ5

### What did you expect to see?
/a.go:16:12: assignment mismatch: 2 variables but 1 value

### What did you see instead?
./a.go:16:12: assignment mismatch: 2 variable but 1 values

**Comment by agnivade** [comment]
Yes, we do not check the no. of variables/values and update the message accordingly. The fix is pretty simple. @griesemer any objections ?

**Comment by griesemer** [comment]
Let's leave this alone for now. It's probably not the only place, and in the past we have avoided any extra code just to fix the grammar. Maybe at some point we will, but for that I'd rather have a general solution that works everywhere.

**Comment by beoran** [comment]
May I reccomend https://github.com/jinzhu/inflection
JinZhu wrote a nice inflection library which is MIT licensed and at the cost of less than 300 lines of code, you can have plurals for English. With this permission, you could add this to the Ho standard library, and then the compiler can be made to emit grammatically correct English plurals easily.

**Comment by mdempsky** [comment]
@beoran Thanks for the tip. It looks like "variables" and "values" are the only words that potentially need inflection within any Go error messages though, so I think an entire inflection library is probably unnecessary.

**Comment by beoran** [comment]
Fair enough, if there's only that few words. You could always import that library later if more plurals become necessary.

**Comment by mdempsky** [comment]
This is fixed by 396b6c2e7c5c368c67e71824471d4f2d48f5c128 on dev.regabi.
