### ISSUE TITLE
blue-jay.github.io， blueprint "Quickstart" failed. clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by xuzhe0205** [golang/go#31098]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.12.1 darwin/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/Oliver/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/Oliver/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="x86_64-apple-darwin13.4.0-clang"
CXX="x86_64-apple-darwin13.4.0-clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sl/pty4cch922gbrxstwp_ym3_m0000gn/T/go-build011233491=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I simply follow the instruction on blue-jay.io

################################################################################
# Install Go using Homebrew
################################################################################

# Install Go (use any of the latest versions)
brew install go

# Create a workspace folder
mkdir -p ~/godev/workspace
cd ~/godev/workspace

# Set PATH and GOPATH
# You should also add these to ~/.bash_profile
export GOPATH=$HOME/godev/workspace
export PATH=$PATH:$GOPATH/bin

################################################################################
# Install Jay
################################################################################

# Download and build Jay
go get github.com/blue-jay/jay

################################################################################
# Download Blueprint
################################################################################

# Download and build Blueprint
go get github.com/blue-jay/blueprint
cd $GOPATH/src/github.com/blue-jay/blueprint

################################################################################
# Set Up MySQL Database
################################################################################

# Create a new env.json configuration file
jay env make

# Export environment variable
export JAYCONFIG=$GOPATH/src/github.com/blue-jay/blueprint/env.json

# Start an instance of MySQL using Docker
docker run --name=mysql57 -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -d mysql:5.7

# Open env.json in an editor and change the MySQL.Hostname to your
# docker container IP (for example: 192.168.99.100)

# You may also want to change the Server.HTTPPort in env.json from 80 to 8080
# if you don't want to execute the run command below with sudo

# Apply the initial migration to the database
jay migrate:mysql all

### What did you expect to see?

Honestly, I don't know what I expect to see, I am totally new to all this. But I believe it should have been "success" or "clean".

### What did you see instead?

# runtime/cgo
ld: warning: ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libpthread.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libpthread.tbd
Undefined symbols for architecture x86_64:
  "___stack_chk_fail", referenced from:
      _x_cgo_init in _x004.o
      __cgo_sys_thread_start in _x004.o
  "___stack_chk_guard", referenced from:
      _x_cgo_init in _x004.o
      __cgo_sys_thread_start in _x004.o
  "___stderrp", referenced from:
      __cgo_sys_thread_start in _x004.o
      _x_cgo_sys_thread_create in _x005.o
      _x_cgo_thread_start in _x008.o
  "_abort", referenced from:
      __cgo_sys_thread_start in _x004.o
      _x_cgo_sys_thread_create in _x005.o
      _x_cgo_thread_start in _x008.o
  "_fprintf", referenced from:
      __cgo_sys_thread_start in _x004.o
      _x_cgo_sys_thread_create in _x005.o
  "_free", referenced from:
      _threadentry in _x004.o
  "_fwrite", referenced from:
      _x_cgo_thread_start in _x008.o
  "_malloc", referenced from:
      _x_cgo_thread_start in _x008.o
  "_nanosleep", referenced from:
      _x_cgo_sys_thread_create in _x005.o
      __cgo_try_pthread_create in _x005.o
  "_pthread_attr_destroy", referenced from:
      _x_cgo_init in _x004.o
  "_pthread_attr_getstacksize", referenced from:
      _x_cgo_init in _x004.o
      __cgo_sys_thread_start in _x004.o
  "_pthread_attr_init", referenced from:
      _x_cgo_init in _x004.o
      __cgo_sys_thread_start in _x004.o
  "_pthread_cond_broadcast", referenced from:
      _x_cgo_notify_runtime_init_done in _x005.o
  "_pthread_cond_wait", referenced from:
      __cgo_wait_runtime_init_done in _x005.o
  "_pthread_create", referenced from:
      _x_cgo_sys_thread_create in _x005.o
      __cgo_try_pthread_create in _x005.o
     (maybe you meant: __cgo_try_pthread_create)
  "_pthread_detach", referenced from:
      _x_cgo_sys_thread_create in _x005.o
      __cgo_try_pthread_create in _x005.o
  "_pthread_mutex_lock", referenced from:
      __cgo_wait_runtime_init_done in _x005.o
      _x_cgo_notify_runtime_init_done in _x005.o
      _x_cgo_set_context_function in _x005.o
      __cgo_get_context_function in _x005.o
  "_pthread_mutex_unlock", referenced from:
      __cgo_wait_runtime_init_done in _x005.o
      _x_cgo_notify_runtime_init_done in _x005.o
      _x_cgo_set_context_function in _x005.o
      __cgo_get_context_function in _x005.o
  "_pthread_sigmask", referenced from:
      __cgo_sys_thread_start in _x004.o
  "_setenv", referenced from:
      _x_cgo_setenv in _x006.o
     (maybe you meant: _x_cgo_setenv)
  "_strerror", referenced from:
      __cgo_sys_thread_start in _x004.o
      _x_cgo_sys_thread_create in _x005.o
  "_unsetenv", referenced from:
      _x_cgo_unsetenv in _x006.o
     (maybe you meant: _x_cgo_unsetenv)
ld: symbol(s) not found for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ianlancetaylor** [comment]
You have the wrong version of the C libraries installed.  It looks like you have the 32-bit versions but you need the 64-bit versions.

**Comment by xuzhe0205** [comment]
> You have the wrong version of the C libraries installed. It looks like you have the 32-bit versions but you need the 64-bit versions.

So should I go ahead and update/install 64-bit version?

**Comment by ianlancetaylor** [comment]
I suppose so.  I don't know anything about blue-jay.io or homebrew.  I'm just explaining what the error message means.

**Comment by xuzhe0205** [comment]
> I suppose so. I don't know anything about blue-jay.io or homebrew. I'm just explaining what the error message means.

Ok, I will go head and try that!, thx
