### ISSUE TITLE
cmd/go: builds fail when GOPATH=/dev/null

### ISSUE THREAD

**Issue by josharian** [golang/go#31100]
When run with `GOPATH=/dev/null`, `go build` fails:

```
$ GOPATH=/dev/null go test -run=TestLldbPython -v -count=1 runtime
=== RUN   TestLldbPython
--- FAIL: TestLldbPython (0.21s)
    runtime-lldb_test.go:169: building source exit status 1
        go: failed to create cache directory /dev/null/pkg/mod/cache: mkdir /dev/null: not a directory
FAIL
FAIL	runtime	0.220s
```

That seems fine. Who would run with `GOPATH=/dev/null`‽ It's not even a directory.

But it's not fine, because run.bash sets `GOPATH=/dev/null`. Why? The comment says: `The $GOPATH value doesn't need to point to an actual directory, it just needs to pass the semantic checks performed by Go.`

I don't know who is wrong here, but I do want all.bash to pass. I have a workaround I can mail just for TestLldbPython (set `GOPATH=`). Or we can fix this mess...somewhere else.

Opinions?

@bcmills @jayconrod @bradfitz

**Comment by Gnouc** [comment]
@josharian IMHO, set `GOPATH=/dev/null` in `run.bash` prevent it from conflict with `GOROOT`. If the test required a valid `GOPATH`, it should set explicitly.

**Comment by bcmills** [comment]
`GOPATH/pkg/mod` contains the module cache, which includes a lockfile that guards edits to the user's `go.mod` and `go.sum` files (see `cmd/go/internal/modfetch.SideLock`).

If those files do not need to be updated and no modules need to be downloaded, then the lock does not need to be acquired, and `GOPATH` does not need to be set. I'm guessing that the failure you're observing is an interaction with #30790, which perhaps introduces more edits to the `go.mod` file than strictly necessary.

Regardless of the cause, we could proceed without locking if `GOPATH` does not exist and cannot be created, but I think an explicit failure in that case is preferable to an undetected race.

**Comment by josharian** [comment]
Thanks. I went ahead and mailed my simple workaround for you to take a look at.
