### ISSUE TITLE
sync.Once: Why don't use uint8 instead of uint32 to avoid using atomic

### ISSUE THREAD

**Issue by anjiawei1991** [golang/go#31101]
```
func (o *Once) Do(f func()) {
	if atomic.LoadUint32(&o.done) == 0 {
		// Outlined slow-path to allow inlining of the fast-path.
		o.doSlow(f)
	}
}

func (o *Once) doSlow(f func()) {
	o.m.Lock()
	defer o.m.Unlock()
	if o.done == 0 {
		defer atomic.StoreUint32(&o.done, 1)
		f()
	}
}
```

I guess the atomic here is for the data integrety (won't read half-writed `done`) , especially on lower than 32-bits machines.

but why don't use uint8 to avoid using atomic, and that can improve performance.

like:
```
type Once struct {
	done uint8
	m    Mutex
}

func (o *Once) Do(f func()) {
	if o.done == 0 {
		// Outlined slow-path to allow inlining of the fast-path.
		o.doSlow(f)
	}
}

func (o *Once) doSlow(f func()) {
	o.m.Lock()
	defer o.m.Unlock()
	if o.done == 0 {
		defer func(){o.done=1}
		f()
	}
}
```

**Comment by anjiawei1991** [comment]
@dvyukov

**Comment by dvyukov** [comment]
Besides atomicity we also need need ordering and visibility:
http://www.1024cores.net/home/lock-free-algorithms/so-what-is-a-memory-model-and-how-to-cook-it
Plain memory accesses won't provide these properties, besides races being formally undefined behavior.

**Comment by martisch** [comment]
As was answered atomic functions provide additional needed properties beyond data integrity.

For asking questions please see https://golang.org/wiki/Questions.
