### ISSUE TITLE
Is there a method for  Go to  compile []byte regex like python ?

### ISSUE THREAD

**Issue by leaixian** [golang/go#31108]
## Python can compile a string bytes like this,
```
import re
re.compile(b"\x80\x80")
```
This can do match for string which is not utf-8 encoding ,can go do this ? Anyone knows a method for it ,Thank you

**Comment by agnivade** [comment]
https://golang.org/pkg/regexp/#pkg-overview says 

> All characters are UTF-8-encoded code points.

So, I don't think there is a way to match non UTF-8 values. If you want this, you are welcome to file a proposal citing the reasons this is beneficial to be included in the standard library.

For further questions, please see https://github.com/golang/go/wiki/Questions.
