### ISSUE TITLE
net/rpc: DialHttp cannot set the client port.

### ISSUE THREAD

**Issue by yjxxtd** [golang/go#31106]
### What version of Go are you using (`go version`)?

<pre>
1.11.1

</pre>

I cannot set the client port when using rpc.DialHTTP.  Does rpc.DialHTTP support that？
DialHttp choose the random port which maybe has conflict with other port. For example, DialHttp choose the port 40010,  if I start server which also bind 40010, the  server will fail.
Though I can set the client port of Dial by the following code, which is tcp connection. But there are some old clients using DialHttp. If the server does not add a port for tcp connetcion, it cannot process both tcp and http connection by one port.  So I wish I can Set the client port for DialHTTP.
<pre><code>
			addr := &net.TCPAddr{IP: net.ParseIP("127.0.0.1"), Port:port}
			d := net.Dialer{LocalAddr: addr}
			conn, err := d.Dial("tcp", rpcaddr)
			if err != nil || conn == nil {
				return
			}
			client = rpc.NewClient(conn)
</pre></code>

**Comment by AlexRouSg** [comment]
`rpc.DialHTTP` just calls `net.Dial` which uses `198.51.100.1:80` syntax

There's even an example on https://golang.org/pkg/net/rpc
`client, err := rpc.DialHTTP("tcp", serverAddress + ":1234")`

**Comment by yjxxtd** [comment]
Sorry, I didn't explain it clearly. I want to set the local port when call rpc.DialHttp, the port 80 of 198.51.100.1:80 is the remote port.

**Comment by bradfitz** [comment]
You can just take the code from `net/rpc.DialHTTPPath` and tweak it slightly to do your own net.DialTCP with a local addr.

**Comment by tv42** [comment]
> For example, DialHttp choose the port 40010, if I start server which also bind 40010, the server will fail.

The convention is to run servers on ports that aren't used for outgoing connections.

The usual default is ports 32k- are for clients:

```
$ cat /proc/sys/net/ipv4/ip_local_port_range 
32768	60999
```

**Comment by yjxxtd** [comment]
@tv42 But there are servers which use port between 32768	and 60999, such as HDFS. If I change the port of these servers, it will be  complicated, because there are a lot of servers. So I want to pick source port for client connections by myself.
![image](https://user-images.githubusercontent.com/7078626/55199928-d3479800-51f6-11e9-94a3-59ffdf8ad70e.png)

**Comment by bradfitz** [comment]
We're not going to add API for this case, but the workaround from my comment above should work fine.

**Comment by yjxxtd** [comment]
@bradfitz Thank you very much.

**Comment by tv42** [comment]
@yjxxtd You can tell Linux not to use the ports you want as listening ports for clients. That'll solve the problem for all (well-behaving) clients, not just the one Go thing you've noticed so far.

https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt

```
ip_local_port_range - 2 INTEGERS
	Defines the local port range that is used by TCP and UDP to
	choose the local port. The first number is the first, the
	second the last local port number.
	If possible, it is better these numbers have different parity.
	(one even and one odd values)
	The default values are 32768 and 60999 respectively.

ip_local_reserved_ports - list of comma separated ranges
	Specify the ports which are reserved for known third-party
	applications. These ports will not be used by automatic port
	assignments (e.g. when calling connect() or bind() with port
	number 0). Explicit port allocation behavior is unchanged.

	The format used for both input and output is a comma separated
	list of ranges (e.g. "1,2-4,10-10" for ports 1, 2, 3, 4 and
	10). Writing to the file will clear all previously reserved
	ports and update the current list with the one given in the
	input.

	Note that ip_local_port_range and ip_local_reserved_ports
	settings are independent and both are considered by the kernel
	when determining which ports are available for automatic port
	assignments.

	You can reserve ports which are not in the current
	ip_local_port_range, e.g.:

	$ cat /proc/sys/net/ipv4/ip_local_port_range
	32000	60999
	$ cat /proc/sys/net/ipv4/ip_local_reserved_ports
	8080,9148

	although this is redundant. However such a setting is useful
	if later the port range is changed to a value that will
	include the reserved ports.

	Default: Empty
```

**Comment by yjxxtd** [comment]
@tv42   Yes, it's great.  Tank you very much.
