### ISSUE TITLE
wasm: support new WASI interface

### ISSUE THREAD

**Issue by johanbrandhorst** [golang/go#31105]
Mozilla, Fastly and others have started work on a new standard interface for WASM to interact with system calls, they're calling it _WASI_, the _WebAssembly System Interface_.

https://hacks.mozilla.org/2019/03/standardizing-wasi-a-webassembly-system-interface/

I think we should consider supporting this in the Go WASM architecture, possibly under a new OS (GOOS=WASI).

This issue should track the development of such an effort.

Mozilla have invited interested parties to join the #wasi channel on the Mozilla IRC server (https://wiki.mozilla.org/IRC).

**Comment by johanbrandhorst** [comment]
@neelance @agnivade

**Comment by neelance** [comment]
I'm already looking into this. Yes, this is likely to become the GOOS/GOARCH `wasi/wasm`. My current long term plan is to also make `js/wasm` partially use WASI as soon as a feature can be expressed with WASI without losing any functionality.

**Comment by johanbrandhorst** [comment]
https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-api.md this looks like a good list to reference.

**Comment by neelance** [comment]
My WIP for WASI can be found here: https://github.com/neelance/go/tree/wasi

There is no `GOOS=wasi` yet, use `GOARCH=wasm` + `GOOS=js` to target WASI. The fork is thus not compatible with wasm_exec.

**Comment by gedw99** [comment]
This is a very important thing.
Wasi can be a new containerisation approach but running on mobiles, desktops, IOT and servers. It solves is able to solve a fundamental problem of trusting code from someone else with the host deciding what file / network IO the third party code has access to.
Sort of like how android will prompt you when an app wants to access your contacts or file system.

Wasmer git repo has it working for golang, python using a rust wasm / wasi engine currently btw. It's fast too.

It seems that there is not IDL / RPC standard yet for WASI though. I looked but could not find. If anyone knows would be great.

**Comment by tiborvass** [comment]
@gedw99 you should probably ask on the [WASI repo](https://github.com/WebAssembly/WASI) instead. Not sure if https://github.com/WebAssembly/WASI/issues/49 is what you're looking for. Either way WASI is still in active development so it is normal that certain things are lacking.

**Comment by philippgille** [comment]
It's great to see there's some interest here! How is the progress? I see a recent commit from Dec 26, 2019 and one before that on Mar 29, 2019 in the fork of @neelance.

I recently stumbled on https://webassembly.sh, which drops you into a shell where you can execute WebAssembly binaries that were packaged with the *WebAssembly Package Manager* (`wapm`, by the [Wasmer](https://wasmer.io) guys) and target WASI: https://wapm.io/interface/wasi

There are small command line programs like `cowsay` and `lolcat`, but some people seem to try to experiment with bigger things as well (TiDB, but didn't try it out).

So naturally, I'd like to experiment with this new tech and create a WASI-targeting WASM file with Go, upload it to wapm and try it out on webassembly.sh :)

**Comment by neelance** [comment]
@philippgille I've updated my fork and just successfully ran a Go program on webassembly.sh. Try `hello-go`.

**Comment by superloach** [comment]
@neelance can we get a status update on WASI support? What's still missing? Do you need help with anything?

Very excited to get this working - combining the portability of WASI with the strength of Go will open up lots of opportunities. :smiley:

**Comment by carlskii** [comment]
Any update on this?

**Comment by mvdan** [comment]
A reminder that this is open source and there are no ETAs, especially when it comes to external contributions such as Richard's. He hasn't posted any update in this thread since March, so that's the latest update. If you want to be notified of updates, subscribe to the thread. Aside from that, the best way to speed up progress is to check out his work, figure out how it works, and try to improve it.

**Comment by inliquid** [comment]
Open source doesn't mean there is no ETA.

**Comment by ianlancetaylor** [comment]
@inliquid That is true but I hope that the meaning is reasonably clear.  Please be charitable in your understanding of what other people write.  Thanks.

**Comment by neelance** [comment]
See https://github.com/golang/go/issues/38248 for what I was working on. No ETA though. Depends on how much time I get to spend on contributing to the Go project.

**Comment by inliquid** [comment]
>That is true but I hope that the meaning is reasonably clear. Please be charitable in your understanding of what other people write. Thanks.

Meaning is clear and it's not correct. At least in a form when someone replies to very reasonable question "this is open source". Open source doesn't mean work is not paid or not compensated in other ways. In most cases it's just one of the business models. So no one should feel like asking for ETA or just a progress is something wrong.

**Comment by mvdan** [comment]
Let's please remain on topic. Yes, we all wish Go had more features and less bugs. There are literally thousands of issues open, and priorities are different depending on who is asked.

I'll hide the last comment and any future ones that just continue on the topic of ETAs, so the thread can just go back to development.

**Comment by nu8** [comment]
https://github.com/wasm3/wasm3/issues/170

**Comment by timcash** [comment]
Is it possible to run wasm code inside of golang? Is this the other side of the same coin with WASI?

**Comment by vshymanskyy** [comment]
@timcash this ticket is about compiling Go apps into WASI-compatible wasm binaries.

But it's also possible to run WASM inside of your Go app, for example you can use **Wasmer** or our **Wasm3** engine (via https://github.com/matiasinsaurralde/go-wasm3 bindings).

**Comment by jedisct1** [comment]
There's also a [WAVM fork](https://github.com/xuperchain/wavm) with Go bindings (that work just fine with recent versions of WAVM).

**Comment by beriberikix** [comment]
There's also [Wasmtime](https://github.com/bytecodealliance/wasmtime-go) bindings via CGO.

**Comment by torch2424** [comment]
Hello! 

So I noticed that in Go 1.16, [Go for OpenBSD is using libc syscalls](https://utcc.utoronto.ca/~cks/space/blog/programming/Go116OpenBSDUsesLibc). 

I was curious after https://github.com/golang/go/issues/38248 is merged, if [WASI libc](https://github.com/WebAssembly/wasi-libc) could be used as an easy(-er) way to bring Go to WASI? 

If not, what's missing from wasi-libc that could make this happen? :thinking:

**Comment by ZhouBox** [comment]
I use wasmtime-go running wasm in golang,but I only use rust developing wasm. So when golang support wasi?

**Comment by Hywan** [comment]
[`wasmer-go`](https://github.com/wasmerio/wasmer-go/) is embedding [Wasmer](https://github.com/wasmerio/wasmer) inside Go. It supports WASI. When using TinyGo to produce Wasm modules, there is no problem. When using Go, you need an adapter to support the Go JS ABI. So far, there are 2 libraries to support it, https://github.com/mattn/gowasmer/ and https://github.com/go-wasm-adapter/go-wasm/, both are assuming the runtime if `wasmer-go`.

It would be easier if Go could add support for WASI. We have many users reporting they try to run Go inside Go via WebAssembly, or even running Go in other environments (like [Python](https://github.com/wasmerio/wasmer-python), [PHP](https://github.com/wasmerio/wasmer-php/), [C](https://github.com/wasmerio/wasmer/tree/master/lib/c-api), [Rust](https://github.com/wasmerio/wasmer/) and so on) via WebAssembly. Obviously we may be able to implement the Go JS ABI for all those hosts, but (i) there is no garantee that the JS ABI is stable and won't break, (ii) it's time consuming, (iii) it's a JS ABI, so it won't fit in all the other hosts, some stuff are deeply tied to the Web.

Thank you for your efforts :-).

**Comment by dosgo** [comment]
Some TinyGo standard libraries do not support it, so there is still no way to compile golang to WASI at present.

**Comment by dankegel** [comment]
More of go's standard libraries compile and pass tests with each release of tinygo.
If you need wasi, do try tinygo now and then to see how close it is to meeting your needs.

**Comment by superloach** [comment]
Perhaps a golang.org/x/wasi package would work for now, until the WASI spec
is stable? I feel like relying on outside tooling like witx doesn't fit
with Go's goals here.

**Comment by gcsfred2** [comment]
My project is waiting for Go + wasm + WASI.

**Comment by hunjixin** [comment]
any plan support  wasi?

**Comment by malisetti** [comment]
Is it possible to use go stdlib which is compiled for wasi from other languages?

**Comment by inkeliz** [comment]
I think, instead of supporting WASI, could Golang suport `GOOS=none GOARCH=wasm` or `GOOS=freestanding GOARCH=wasm`? 

I think that would be the first step to support `GOOS=WASI`. The difference between `GOOS=none` and `GOOS=js` is that would no long require the js glue, which is used on the `runtime` too (far I remember). It would make possible to implement WASI on top of that, even by third-party packages at first.

However, I think https://github.com/golang/go/issues/42372 should be solved first, because exporting function is almost mandatory for WASM.

**Comment by gcsfred2** [comment]
What about upper-case versus lower-case names of functions? Could that
native mechanism be used to map to exported and non-exported functions?

**Comment by KiYugadgeter** [comment]
Now is time to send feedback If you hopes WASI support on Go!!
https://go.dev/blog/survey2023-q1

**Comment by johanbrandhorst** [comment]
Closing this in favor of #58141, where we will track the effort to implement the accepted proposal 🎉.

**Comment by hurae** [comment]
For who concerns and clicked into this, golang is supporting wasi preview 1 in version 1.21.

refer to this: https://tip.golang.org/doc/go1.21
