### ISSUE TITLE
what's the correct syntax of go.mod file?

### ISSUE THREAD

**Issue by shaocongliang** [golang/go#31102]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
not sure

### What operating system and processor architecture are you using (`go env`)?
````
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/shaocong/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/shaocong/go:/Users/shaocong/Documents/ifly/iot/repo"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/shaocong/Documents/langver/vgo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/w8/mjfggzds2rd2989748t70zyr0000gq/T/go-build273839415=/tmp/go-build -gno-record-gcc-switches -fno-common"
````

### What did you do?
I am trying to create a demo for go modules. First I create two modules named a,b in bitbucket. Below is the repo addresss
[moduleA](https://bitbucket.org/lshaocong/a/src/master/)
[moduleB](https://bitbucket.org/lshaocong/b/src/master/)

then create a directory "vgo(outside GOPATH)" in my local computer and a go file in this dir. Here is the code
````golang
package main

import "bitbucket.org/lshaocong/a"
import "bitbucket.org/lshaocong/b"

func main() {
	a.Greet("shaocong")
	b.CallMeByYourName("100")
}
````
#### go.mod
````
module hello
````
#### build output
````
go: finding bitbucket.org/lshaocong/a latest
go: finding bitbucket.org/lshaocong/b latest
go: bitbucket.org/lshaocong/b@v0.0.0-20190328034506-a26657131143: parsing go.mod: go.mod:4: usage: require module/path v1.2.3
go: error loading module requirements
````
### What did you expect to see?
all is passed 

### What did you see instead?
why give me a usage error and what's the meaning of v1.2.3? The vxxx is necessary for a a require package?
I try to find the go.mod syntax document in module wiki but can't find it.

**Comment by agnivade** [comment]
Yes, the module version is required in the `require` stanza. It is documented here https://golang.org/cmd/go/#hdr-The_go_mod_file. The wiki is not an exhaustive source of information, just a quickstart and some FAQ.

Bottom line is do not write a go.mod by hand. Use the go toolchain and let it do its job. See the quickstart in the modules wiki.
