### ISSUE TITLE
x/build/env/linux-arm64-packet: builder is down

### ISSUE THREAD

**Issue by bradfitz** [golang/go#31112]
Our linux/arm64 builder on packet is missing. Seems to be powered off or something?

```
bradfitz@go:~/src/golang.org/x/build/env/linux-arm64/packet$ ssh -v -i ~/keys/id_ed25519_golang1 root@147.75.74.194
OpenSSH_7.4p1 Debian-10+deb9u4, OpenSSL 1.0.2q  20 Nov 2018
debug1: Reading configuration data /home/bradfitz/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to 147.75.74.194 [147.75.74.194] port 22

(hangs)
```

@dmitshur, could you take a look? There's a README in that directory with go links to auth info.

/cc @eliasnaur @griesemer

**Comment by bradfitz** [comment]
According to the packet.net admin UI, the machine is up. But it doesn't ping. I tried its serial console (via Packet's ssh gateway to serial) but can't get a login.

I guess it's hung & will reboot it.

**Comment by dmitshur** [comment]
> I guess it's hung & will reboot it.

Have you done that? https://farmer.golang.org shows "host-linux-arm64-packet: 17/20", i.e., none are missing.

**Comment by bradfitz** [comment]
Yeah, I did from the web UI. We have existing bugs open for monitoring so I'll close this.
