### ISSUE TITLE
wiki: document gomote for first time users

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#31118]
Thanks for this. If there's one thing that could make the wiki significantly clearer it would be a paragraph about directory structure and the "gomote machine model". It took me a bunch of try-and-error runs to find out. Much of it may be "obvious" in retrospect, but it helps spelling it out right away, especially for first-time gomote users. This would provide newcomers a clearer model of how the gomote looks like from a client's perspective.

Some of the things that would be nice if they were spelled out:

- each instance of a gomote has its own working directory, accessible via `$WORKDIR`
- gomote push does essentially an `rsync` of the `$GOROOT` directory into the remote `$WORKDIR`; i.e., after a `gomote push`, the local `$GOROOT` appears as `go` directory on the gomote (I had to find this out by doing repeated `gomote ls` commands)
- when issuing `gomote run` commands, one needs to specify the full path for commands and files, e.g. `go/bin/go tool compile go/src/mypkg/x.go` - there appears no notion of a `cwd`, or perhaps I missed it
- to change individual uploaded files, make the changes locally and use `gomote push $MOTE` and it will only upload the changes (this was not obvious to me at first, especially because there's also a `gomote put` command to push single files. I thought I was supposed to use that one for smaller changes)
- I didn't figure out to how to use `gomote put` to get a file into a specific directory on the gomote instance (I still don't know how to do it, but I resorted to just using `gomote push` all the time.)
- explain that the gomote self-destructs after 30min of non-use
- I'm unclear on the `-system` flag

_Originally posted by @griesemer in https://github.com/golang/go/issues/31091#issuecomment-477718369_

**Comment by mknyszek** [comment]
I updated the wiki and I think I hit your main points: https://github.com/golang/go/wiki/Gomote.

Closing for now. Feel free to reopen.
