### ISSUE TITLE
strings: broken backward compatibility in 1.12

### ISSUE THREAD

**Issue by kirillDanshin** [golang/go#31121]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12
</pre>

### Does this issue reproduce with the latest release?

yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/apple/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cs/0p7xq1h91795xymyb6h7pbhh0000gn/T/go-build419608424=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Example 1.
```
go get -v github.com/fasthttp/router
cd $GOPATH/src/github.com/fasthttp/router
go test -v -run TestTreeFindCaseInsensitivePath # fails using go1.12

# switch back to 1.11.x

go test -v -run TestTreeFindCaseInsensitivePath # works

# switch back to 1.12, vendor strings.ToLower and strings.Map from 1.11.x, replace all strings.ToLower with vendored e.g. toLower()

go test -v # works
```

Example 2: the exactly same steps, but with github.com/gramework/gramework before [hotfix](https://github.com/gramework/gramework/commit/0cf42e494b2509859fcdc1c758bdaad75b40877f)
Example 3: or https://github.com/julienschmidt/httprouter
Example 4: or https://github.com/buaazp/fasthttprouter
Example ∞: or any program that relies on lowering UTF-8 characters.

### What did you expect to see?

Tests pass on 1.12 without copying two functions from the standard strings package. 

### What did you see instead?

Broken tests and projects that can be fixed only by [vendoring stdlib functions](https://github.com/gramework/gramework/commit/0cf42e494b2509859fcdc1c758bdaad75b40877f), which is at least strange keeping in mind the backward compatibility promise.

**Comment by kirillDanshin** [comment]
Update: the bug seems to be introduced by https://go-review.googlesource.com/c/go/+/131495

**Comment by ALTree** [comment]
Thanks for the report. I'm tentatively putting this into the 1.13 milestone, pending investigation. 

It would be nice to have a self-contained example that shows how the new behaviour is different from the old, and why this is causing tests breakage.

cc @martisch, author of that CL, in the meantime.

**Comment by kirillDanshin** [comment]
@ALTree I still trying to figure out what exactly triggers that bug, but no luck for now. anyway, for now only solution for me is to swap toLower implementation with vendored one in the router core using build constraints.

**Comment by martisch** [comment]
The difference is how invalid UTF8 characters are treated and this is WAI and wont change back. They now will always be converted to rune errors. Before they were only converted to RuneError runes when there was no e.g. upper case character converted to lower case. Which was inconsistent and a bug. The new behaviour is consistent.

For the noted examples such as https://github.com/julienschmidt/httprouter a bug was filed before go1.12 release that the tests will fail as they assume the old behaviour. https://github.com/julienschmidt/httprouter/issues/263

**Comment by martisch** [comment]
Of course there can still be a bug in ToLower that converts a string incorecctly. For that it would be good to have an example string that can be passes to ToLower as a minimal reproducer to investigate.
