### ISSUE TITLE
net/http/httputil: ReverseProxy FlushInterval no longer flushes headers in go1.12

### ISSUE THREAD

**Issue by liggitt** [golang/go#31125]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/liggitt/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/liggitt/go"
GOPROXY=""
GORACE=""
GOROOT="/Users/liggitt/.gvm/gos/go1.12.1"
GOTMPDIR=""
GOTOOLDIR="/Users/liggitt/.gvm/gos/go1.12.1/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/h8/3dzrjpfj76d93vbhc5f2r8tw00kjgb/T/go-build963504992=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

1. Set up a reverse proxy with a flush interval.
2. Proxied to a backend that writes and flushes headers, then streams response chunks (which can be arbitrarily delayed from the original header write/flush).

### What did you expect to see?
Clients making requests to the proxy should see the headers from the backend no later than the FlushInterval

### What did you see instead?
Clients making requests to the proxy receive no data until the first body chunk is written.

https://play.golang.org/p/Y8KQO8-57MR
* go1.11 works properly
* go1.12 hangs

The change in https://github.com/golang/go/commit/5440bfc2ea8c0a4c78d5161605659c07ea10e37a#diff-d863507a61be206d112f6e00e6d812a2L343 removed the goroutine that ensured the FlushInterval was honored while blocking in copyResponse, even prior to the first Write() call being encountered. The time.After() ticker it sets up doesn't get set up until the first Write() call is made.

**Comment by thaJeztah** [comment]
Could this be tracked for Go 1.12.2 ? (is a separate tracking issue needed for that?)

**Comment by ALTree** [comment]
cc @bradfitz for investigation and decision regarding a possible backport

> is a separate tracking issue needed for that?

In general, after the issue has been investigated, a team member will decide if it qualifies for a backport. Then a backport issue will be opened.

**Comment by PaulSD** [comment]
Work-around for Go 1.12:
```
type flushResponseWriter struct {
  http.ResponseWriter
  http.Flusher
  http.Hijacker
  http.CloseNotifier
}
func NewFlushResponseWriter(wrap http.ResponseWriter) (http.ResponseWriter) {
  f, _ := wrap.(http.Flusher)
  h, _ := wrap.(http.Hijacker)
  cn, _ := wrap.(http.CloseNotifier)
  if f == nil || h == nil || cn == nil {
    log.Printf("WARNING: http.ResponseWriter doesn't implement all flushResponseWriter interfaces, >
    return wrap
  }
  return flushResponseWriter{wrap, f, h, cn}
}
func (self flushResponseWriter) WriteHeader(statusCode int) {
  self.ResponseWriter.WriteHeader(statusCode)
  self.Flusher.Flush()
}

func HttpHandler(w http.ResponseWriter, req *http.Request) {
  ...
  proxy.ServeHTTP(NewFlushResponseWriter(w), req)
}
```

**Comment by bradfitz** [comment]
@gopherbot, please backport to Go 1.12.
