### ISSUE TITLE
go 1.12.1 mod checksum errors

### ISSUE THREAD

**Issue by djgilcrease** [golang/go#31124]
<details><summary><code></code> In Docker Container</summary><br><pre>
$ docker run --rm -it --entrypoint "/bin/bash" -v $(pwd):/build golang:1
root@4999befd6af9:/build# go mod verify
verifying github.com/docker/distribution@v2.7.1+incompatible/go.mod: checksum mismatch
	downloaded: h1:J2gT2udsDAN96Uj4KfcMRqY0/ypR+oyYUYmja8H+y+w=
	go.sum:     h1:OQAyNXQeyeeMzTCM3VqsPD8NiZw1G4K4ScrGHwJ1iX0=
root@4999befd6af9:/build# go version
go version go1.12.1 linux/amd64
root@4999befd6af9:/build# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/build/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build039885288=/tmp/go-build -gno-record-gcc-switches"
root@4999befd6af9:/build# exit
exit
</pre></details>

<details><summary><code></code> On Host OS</summary><br><pre>
$ go mod verify
all modules verified
$ go version
go version go1.12.1 linux/amd64
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/digitalxero/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/opt/projects/f5/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/opt/projects/go/kog/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build434655851=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you expect to see?
checksums to be the same

### What did you see instead?
checksums appear to not calculate properly even within the same version of go.

This seems to always happen with the following in my deps
* github.com/docker/distribution
* github.com/stretchr/testify
* github.com/coreos/etcd

**Comment by agnivade** [comment]
What's in your $PWD ? Can you give us the steps to reproduce this ?

**Comment by bcmills** [comment]
Please provide concrete steps to reproduce the problem, starting with an empty `GOPATH`.

It is possible that you have copies of some modules in your module cache from before Go 1.11.4 (see #29278). If so, we do not expect this sort of problem to recur, provided that all subsequent module fetches are done using Go 1.11.4 or newer (https://github.com/golang/go/issues/29278#issuecomment-454906519).

**Comment by djgilcrease** [comment]
After running `go clean -modcache` on the host things cleaned up. and did not keep switching every time I ran in a container
