### ISSUE TITLE
x/blog: survey2018 fig25 incorrect title

### ISSUE THREAD

**Issue by carnott-snap** [golang/go#31122]
In the [2018 survey results](https://blog.golang.org/survey2018-results#TOC_8), [fig25](https://blog.golang.org/survey2018/fig25.svg) has an erroneously copied title:
- act: `Please rank the top 5 resources you use to get answers to your Go related questions:`
- exp: `Please rank the top 5 resources you use to get your Go related news:`
- note: This is embedded within an SVG.

**Comment by agnivade** [comment]
@spf13

**Comment by fflewddur** [comment]
Thanks for the report! This was resolved as part of 169977 on Mar 29.
