### ISSUE TITLE
Strange behaviour with multi-module repository

### ISSUE THREAD

**Issue by an2deg** [golang/go#31129]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes. The issue reproduces also on go1.11.x

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
08:47 $ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ad/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ad/Library/Go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/ad/Projects/go-middleware/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6t/7s8tk6ld2vd49f2b5yw4_xnrv8z53_/T/go-build786902005=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I have a Go mod compatible service which export his Thrift contracts (Go code) as sub-package `contracts`. Let's call it `service-a`.

From the other side I have a consumer of the `service-a` contracts with name `go-middleware`. For some reasons `go-middleware` has all dependencies of the `service-a` despite the fact that only `contracts` sub-package is using.

I tried to solve it by converting `service-a` into a multi-module repository. Now sub-package `contracts` is a Go module and it has only single dependency - git.apache.org/thrift.git@0.10.0

<pre>
$ cat go.mod
module service-a/contracts

require git.apache.org/thrift.git v0.0.0-20161221203622-b2a4d4ae21c7

go 1.12

$ cat go.sum
git.apache.org/thrift.git v0.0.0-20161221203622-b2a4d4ae21c7/go.mod h1:fPE2ZNJGynbRyZ4dJvy6G277gSllfV2HJqblrnkyeyg=
</pre>

But `go-middleware` still has dependency from `service-a`. 

`go list -m all` is looking like the following:

<pre>
service-a v1.4.1-0.20190313111141-dd3b952f494f
service-a/contracts v0.0.0-20190328141637-ad4e80cb4d4c
</pre>

### What did you expect to see?

I expected to see dependency only from `service-a/contracts`.

### What did you see instead?

`go list -m all` and go.sum contain dependencies from both `service-a/contracts` and it parent module `service-a`

**Comment by agnivade** [comment]
Can you give us the exact steps to reproduce this ?

/cc @bcmills

**Comment by an2deg** [comment]
@agnivade when I tried to prepare test project I figured out that the problem was on my side. Sorry for confusion.
