### ISSUE TITLE
net/http/httputil: ReverseProxy does not flush header writes

### ISSUE THREAD

**Issue by PaulSD** [golang/go#31126]
### What version of Go are you using (`go version`)?
go version go1.12.1 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dev/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/dev/docker-auth-proxy/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build232253968=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I have a server with a long-poll endpoint which returns response headers immediately, then delays writing anything in the response body until an event occurs.  Events typically occur after a long delay.
The client waits for the response headers with a very short timeout (and throws an error if the headers aren't received), then waits for a response body with a very long timeout.
I'm trying to use httputil.ReverseProxy to write a proxy that sits between this client and server.  However, the client almost always errors out because it didn't receive response headers within its timeout.
The problem is that httputil.ReverseProxy only flushes response body writes to the client.  It does not flush header writes, regardless of the FlushInterval.

More specifically, ReverseProxy calls `rw.WriteHeader(res.StatusCode)` then waits for a read on the response body.  Neither WriteHeader() nor ReverseProxy flushes `rw` before ReverseProxy begins waiting for a body read.

Example code: https://play.golang.org/p/SRbVbyZYsnp

### What did you expect to see?
2009/11/10 23:00:00 Server wrote status
2009/11/10 23:00:00 Client got status
2009/11/10 23:00:05 Server wrote body
2009/11/10 23:00:10 Server done writing

### What did you see instead?
2009/11/10 23:00:00 Server wrote status
2009/11/10 23:00:05 Server wrote body
2009/11/10 23:00:05 Client got status
2009/11/10 23:00:10 Server done writing

**Comment by liggitt** [comment]
just opened https://github.com/golang/go/issues/31125 for the same issue :)

**Comment by PaulSD** [comment]
Seriously? 22 minutes apart? What are the odds?
LOL

**Comment by ALTree** [comment]
Closing here as a dup of #31125 then. Feel free to post your analysis on that issue, if you believe it could be helpful.
