### ISSUE TITLE
Go2 Improve the way of package import

### ISSUE THREAD

**Issue by Allenyn** [golang/go#31128]
### The go package desgin
The package is important.  Go use file path and package name (more like a namespace) to define a unique package. It is a great design that easy to use and understand.

### What is the problem ?
Also go package is easy to use, but when we import the package and use the element of the package. we have to write the package name first. I think it is boring and some kind of unnecessary. After we import the package usually think current go file have all element of the package.   

### Proposal
No need to clarify the package name. Only if there is a naming conflicts with other package or local package, then we need to write the package. 
Such as C# namespace using. 

### Some tips
* I know some one will point out that go can import package with a point in front of package name. Like blow.
```
import (  
    . "math"    
)

```

But there will report an error when the name of the element such as function, struct and var conflicts with the one in the package "math". And write a "." in front of the every imported package name is boring too. So just don't mention it ,Thinks.   

* Most of the time there is no naming conflicts. Right ?
* Some times the package name is not as same as the last directory' name that maybe a little confusing. Most of time we don't need and care about the package name.
* This does not break existing code.

### Go package cycle import
* Now go has module. So just forbid modules circular dependency and open package cycle import. 
* Many people  merge the all files in one package just to avoid the error of the package cycle import. It is quite annoying. It didn't have a positive impact. 
* I know the chances of changing this are low. But I just want to say it !!!

**Comment by bronze1man** [comment]
`Go package cycle import` will cause single package can not be reused in another projects, because it has relative to everything in current project.
