### ISSUE TITLE
cmd/go: document use of nested `go.mod` files to prune out irrelevant directories

### ISSUE THREAD

**Issue by slimjim777** [golang/go#31137]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jjesudason/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jjesudason/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/by/70vkys8x6z7134zfbms06wdc0000gn/T/go-build053664553=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
1. Create an application that uses `github.com/snapcore/snapd` as an import
2. Run: `go mod tidy`

<pre>
go mod tidy
go: finding github.com/snapcore/snapd/asserts latest
go: finding github.com/snapcore/snapd latest
go: extracting github.com/snapcore/snapd v0.0.0-20190329093636-71bdfa33d159
-> unzip /Users/jjesudason/go/pkg/mod/cache/download/github.com/snapcore/snapd/@v/v0.0.0-20190329093636-71bdfa33d159.zip: malformed file path "cmd/snap-confine/spread-tests/distros/debian.": trailing dot in path element
</pre>

### What did you expect to see?
Expected to see the package fetched successfully

### What did you see instead?
go modules choke on some filenames that it does not like, even though they are no Go files and have no relevance to the app/package compilation

**Comment by slimjim777** [comment]
This is another example of a filename that fails:

<pre>
go: finding github.com/slimjim777/snapd/asserts latest
go: finding github.com/slimjim777/snapd latest
go: extracting github.com/slimjim777/snapd v0.0.0-20190329103353-c1ea86c7084a
-> unzip /Users/jjesudason/go/pkg/mod/cache/download/github.com/slimjim777/snapd/@v/v0.0.0-20190329103353-c1ea86c7084a.zip: malformed file path "tests/completion/data/twisted/this isn't.innit": invalid char '\''
</pre>

**Comment by agnivade** [comment]
@bcmills this is coming up pretty frequently now.

https://github.com/golang/go/issues/28001#issuecomment-432796527

Shall we do something about it ?

**Comment by bcmills** [comment]
@agnivade We can look at specific characters, but in general we cannot allow non-portable filenames within modules.

If there are parts of the repository that should not be included in the module at all, you can always cut them off by adding another `go.mod` file in the directory tree.

**Comment by slimjim777** [comment]
> If there are parts of the repository that should not be included in the module at all, you can always cut them off by adding another `go.mod` file in the directory tree.

@bcmills that's interesting - could clarify how to do that? The `exclude` directive seems to be aimed at excluding sub-dependencies rather than a specific directory. Also, the files that are causing `go mod` to fail are not actually Go files, so potentially they could be excluded by default.

**Comment by bcmills** [comment]
@thepudds, @myitcv: Are you aware of any documentation on using `go.mod` files to prune a repository?

I'm not having any luck finding it, so I'm going to retitle the issue to focus on that part (since there's not much we can plausibly do about the rest).

**Comment by bcmills** [comment]
@slimjim777, you should be able to just drop in an empty `go.mod` file at the topmost directory whose contents are irrelevant to the Go packages. So perhaps:

```
$ touch cmd/snap-confine/go.mod
```

**Comment by myitcv** [comment]
> Are you aware of any documentation on using go.mod files to prune a repository?

@bcmills - I am not, no. But to be honest I would have deferred to @thepudds in any case 😄

**Comment by slimjim777** [comment]
> @slimjim777, you should be able to just drop in an empty `go.mod` file at the topmost directory whose contents are irrelevant to the Go packages. So perhaps:
> 
> ```
> $ touch cmd/snap-confine/go.mod
> ```

Thanks - I'll create a PR for that project.

Then docs that I've found are: [https://github.com/golang/go/wiki/Modules](https://github.com/golang/go/wiki/Modules)
