### ISSUE TITLE
cmd/compile: preempt repeated checks for zero constant in prove

### ISSUE THREAD

**Issue by zdjones** [golang/go#31141]
In several heavily-used paths, prove is checking for the existence of a zero-valued constant, and creating it if not found:

- After initialisation, prove ranges through all blocks and values, checking for the zero constant  at every Value until it finds one. A similar check is also done here for every string len, slice len, and slice cap op.
- factTable.isNonNegative contains a similar check needed to take advantage of the poset.

I’d like to clean this up in two ways:
1. Preempt all these checks by finding or creating the zero constant Value when the factsTable is initialised on entry to prove().
2. Use a method from func.go, func.ConstInt64(), that takes care of locating an extant value or creating one if necessary. 

(On mobile, will fix formatting and add details/links when back to keyboard)

cc/ @rasky @josharian @mvdan

**Comment by josharian** [comment]
Yes please. No need to add more detail here, just do it. This was also discussed in passing at https://github.com/golang/go/issues/25086

**Comment by zdjones** [comment]
Will do. Thanks @josharian for pointing out that constInt method.
