### ISSUE TITLE
godoc: Minor typo in documentation for Queue#Get method

### ISSUE THREAD

**Issue by garukun** [golang/go#31156]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
The [Queue#Get method in godoc](https://godoc.org/github.com/golang-collections/go-datastructures/queue#Queue.Get) states the following:

> Get will _**add**_ an item to the queue. If there are some items in the queue, get will ...

#### What did you expect to see?
I believe the comment for `Get` method should read:

> Get will retrieve an item from the queue. If there are some items in the queue, get will ...

or something similar.

#### What did you see instead?

> Get will _**add**_ an item to the queue. If there are some items in the queue, get will ...

#### System details

```
go version go1.12.1 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/stevejiang/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/stevejiang/developments/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version go1.12.1 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.12.1
uname -v: Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226
lldb --version: lldb-1001.0.12.1
  Swift-5.0
```

**Comment by garukun** [comment]
I'm happy to take this on an fix it for my first contribution to Go repo if this is worth fixing. :)

**Comment by agnivade** [comment]
Thanks for the initiative. Unfortunately, this is not in the Go repo. Feel free to file an issue in github.com/golang-collections/go-datastructures/queue instead.

You are most welcome to contribute any other fixes which are in the Go repo.
