### ISSUE TITLE
Please add "Abandon 996" badge and License in this project to support us. 

### ISSUE THREAD

**Issue by firedom** [golang/go#31161]
---------------------------
- Add this [badge](https://github.com/996icu/996.ICU/blob/master/externals/instruction.md) - to your project to support 996.ICU.  
- 把这个[徽章](https://github.com/996icu/996.ICU/blob/master/externals/instruction.md)加入你的项目来支持996.ICU
![https://996.icu](https://img.shields.io/badge/link-996.icu-red.svg)
--------------------------------------------
Chinese software engineers are protesting against the country ’ s 996 work schedule.
An unleagal work schedule (9a.m. ~ 9p.m., 6 days a week) .
Search 996.icu to support us !!

中国的程序员正在网上发起反抗 996 工作制的运动
“ 996 ”工作制，即每天早 9 点到岗，一直工作到晚上 9 点，每周工作 6 天。
请搜索 996.icu 支持我们 ！
---------------------------
# License
<p align="center">The 996ICU License (996ICU)</p>
<p align="center">Version 0.1, March 2019</p>

PACKAGE is distributed under LICENSE with the following restriction:

The above license is only granted to entities that act in concordance with local labor laws. In addition, the following requirements must be observed:

* The licensee must not, explicitly or implicitly, request or schedule their employees to work more than 45 hours in any single week.
* The licensee must not, explicitly or implicitly, request or schedule their employees to be at work consecutively for 10 hours.

# <p align="center">Developers of All Countries, Unite!</p>

**Comment by chfanghr** [comment]
Why this repository???This is not and never will be a issue,THIS IS JUST A LANGUAGE.

**Comment by AlseinX** [comment]
Why not this repository???This is certain and ever could be a issue, HUMAN RIGHTS ARE PRIOR TO EVERYTHING.

**Comment by bradfitz** [comment]
Sorry, but this is not compatible with the Open Source Definition. (https://opensource.org/osd)

We agree that it's wrong that anybody would be forced to work so long, but we won't be changing our license.
