### ISSUE TITLE
cmd/compile: double assignment not optimized

### ISSUE THREAD

**Issue by marigonzes** [golang/go#31172]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version devel +576442b Fri Mar 29 23:05:45 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
I compiled the following code (simplified from a more complex program):
```go
package test

var sink int

func aux() int {
    return 0
}

func test1() {
    sink = aux()
    sink = aux()
}
```

### What did you expect to see?
I expected the double assignment to be compiled away, as in the code presented below:
```go
package test

var sink int

func test1() {
    sink = 0
    sink = 0
}
```

### What did you see instead?
Instead, the following code was generated:
```asm
        movq    $0, "".sink(SB)
        nop
        movq    $0, "".sink(SB)
        ret
```

Note: Before commit 69c2c56, the code snippets shown above behaved similarly.

**Comment by randall77** [comment]
Yes, the inline marks prevent this optimization.
Removing unused inline marks would help.
