### ISSUE TITLE
x/tools/go/packages: struct field tag `json "command"` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair

### ISSUE THREAD

**Issue by mbana** [golang/go#31181]
https://github.com/golang/tools/blob/master/go/packages/external.go#L21

Linter complains:

```
struct field tag `json "command"` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair
```

Code:

```go
// Driver
type driverRequest struct {
	Command    string            `json "command"`
	Mode       LoadMode          `json:"mode"`
	Env        []string          `json:"env"`
	BuildFlags []string          `json:"build_flags"`
	Tests      bool              `json:"tests"`
	Overlay    map[string][]byte `json:"overlay"`
}
````

Feel free to close, if this is false positive.

**Comment by josharian** [comment]
Looks real. Thanks for reporting.

cc @matloob 

I'm surprised the builders aren't failing. I thought vet checked this too(?).

**Comment by ahsun-ahmed** [comment]
according to the code, **space** is not allowed between **key** and **value**, only **colon** is allowed. i think the error is legit @josharian @mbana

**Comment by PrasadKasar** [comment]
copy and paste this in your code it should work fine: 


// Driver
type driverRequest struct {
	Command    string            `json:"command"`
	Mode       LoadMode          `json:"mode"`
	Env        []string          `json:"env"`
	BuildFlags []string          `json:"build_flags"`
	Tests      bool              `json:"tests"`
	Overlay    map[string][]byte `json:"overlay"`
}
