### ISSUE TITLE
About the use of time.NewTicker()

### ISSUE THREAD

**Issue by xssed** [golang/go#31182]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
unknown

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\gopath
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build064470026=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

<pre>
package main

import (
	"fmt"
	"os"
	"time"
)

func main() {

	task_serverlistbackup, err := time.ParseDuration("1" + "m")
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(0)
	}

	ticker := time.NewTicker(time.Minute * task_serverlistbackup)
	go func() {
		for _ = range ticker.C {
			fmt.Printf("ticked at %v", time.Now())
		}
	}()

	time.Sleep(time.Minute * 10)
}

</pre>

### What did you expect to see?

Output every minute.

### What did you see instead?
The program did not report any errors.However, the program did not execute the result.
Why can I only use this?  
<pre>
time.NewTicker(time.Minute * 1) 
</pre>
I noticed that:
<pre>
time.Minute== Duration == int64

func NewTicker(d Duration) *Ticker {
	if d <= 0 {
		panic(errors.New("non-positive interval for NewTicker"))
	}
	// Give the channel a 1-element time buffer.
	// If the client falls behind while reading, we drop ticks
	// on the floor until the client catches up.
	c := make(chan Time, 1)
	t := &Ticker{
		C: c,
		r: runtimeTimer{
			when:   when(d),
			period: int64(d),
			f:      sendTime,
			arg:    c,
		},
	}
	startTimer(&t.r)
	return t
}

time.Duration*time.Duration   is  wrong

Can you throw an exception?

</pre>

**Comment by DisposaBoy** [comment]
`task_serverlistbackup` is already in `minutes` so `time.Minute * task_serverlistbackup` = `60000000000 * 60000000000`  = `801362h40m26.63743488s`.

**Comment by xssed** [comment]
> 
> 
> `task_serverlistbackup` is already in `minutes` so `time.Minute * task_serverlistbackup` = `60000000000 * 60000000000` = `801362h40m26.63743488s`.

time.Second * time.Duration(task_serverlistbackup)

**Comment by agnivade** [comment]
Also feel free to check out https://github.com/charithe/durationcheck
