### ISSUE TITLE
x/sys/unix: SYS_CLOCK_GETTIME undefined on darwin/amd64 with Go 1.11

### ISSUE THREAD

**Issue by gleichda** [golang/go#31203]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes its new in the latest release of golang.org/x/sys

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/gleichd/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/gleichd/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go@1.11/1.11.6/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go@1.11/1.11.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bs/n6sgl2cs1nn4wn__fcy9t4q80000gn/T/go-build282528659=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Trying to run a programm including https://github.com/sirupsen/logrus

### What did you expect to see?
The program works

### What did you see instead?
With the latest release of golang.org/x/sys/unix I'm getting an error:
`$ go run src/main/main.go
# golang.org/x/sys/unix
../../../golang.org/x/sys/unix/zsyscall_darwin_amd64.1_11.go:687:22: undefined: SYS_CLOCK_GETTIME`

Checking out the previous commit (9eb1bfa1ce65ae8a6ff3114b0aaf9a41a6cf3560) of golang.org/x/sys/ makes it work again

**Comment by AlexRouSg** [comment]
It was intentionally removed as it's not defined for darwin. See https://go-review.googlesource.com/c/sys/+/170299

**Comment by ikhsanfaruqi** [comment]
get same err

**Comment by kashifmin** [comment]
Getting the same error here. Waiting for the fix to be merged. 🤘🏻
