### ISSUE TITLE
x/tools/internal/lsp: Wrong symbol kind for the `textDocument/symbol`.

### ISSUE THREAD

**Issue by movie-travel-code** [golang/go#31202]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/henrywong/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/henrywong/workspace/gopath"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fm/bk0wqlkj523gdp9pbtnyvxmm0000gn/T/go-build954865857=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Get the `textDocument/symbol` for the go source file.

```go
// The symbol kind for `int_basic_alias` should be `NumberSymbol`, not `StructSymbol`.
type int_basic_alias = int
```

### What did you expect to see?
For the type alias, lsp should strip off the type alias to get the essential type. And compute the correct symbol based on the essential type.
```go
// The symbol kind for `int_basic_alias` should be `NumberSymbol`
type int_basic_alias = int
```
### What did you see instead?
```go
// The symbol kind for `int_basic_alias` is `StructSymbol`
type int_basic_alias = int
```

**Comment by stamblerre** [comment]
cc @zmb3

**Comment by movie-travel-code** [comment]
Hi @zmb3 btw, I have sent a PR for this issue. Please review it and help me decide if it can solve the this issue.
