### ISSUE TITLE
misc-vet-vetall build failure

### ISSUE THREAD

**Issue by aarzilli** [golang/go#31210]
Just got a weird build failure from misc-vet-vetall builder:

```
##### cmd/vet/all
can't load package: package golang.org/x/tools/go/analysis/cmd/vet: cannot find package "golang.org/x/tools/go/analysis/cmd/vet" in any of:
	/workdir/go/src/golang.org/x/tools/go/analysis/cmd/vet (from $GOROOT)
	/workdir/gopath/src/golang.org/x/tools/go/analysis/cmd/vet (from $GOPATH)
vet/all: exit status 1
exit status 1
2019/04/02 16:37:12 Failed: exit status 1
2019/04/02 16:37:12 FAILED
```

Full log: https://storage.googleapis.com/go-build-log/c98fc4a0/misc-vet-vetall_7099ef79.log

**Comment by dmitshur** [comment]
The log is from [CL 163677](https://golang.org/cl/163677).

/cc @bradfitz Have we done anything recently (today-ish) that would affect the misc-vet-vetall builder?

**Comment by bradfitz** [comment]
Nope.

And my earlier test CL https://go-review.googlesource.com/c/go/+/170399 passed on the misc-vet-vetall builder.

The coordinator's been up 17 hours and 43 minutes (https://farmer.golang.org/), and that test CL is more recent than that.

**Comment by aarzilli** [comment]
Maybe it's because the parent commit was old? Do they build the exact commit or do they cherry pick?

**Comment by dmitshur** [comment]
They build the exact commit. However, your CL's parent commit is not very old at all.

This builder is passing for the latest master commit at https://build.golang.org/.

**Comment by dmitshur** [comment]
Looks like it was some sort of flakiness. Retrying the trybots at https://go-review.googlesource.com/c/go/+/163677 made the failing builder pass.

**Comment by bradfitz** [comment]
No, the git parent was old.

Look at the diff from patchset 2 (which failed) to 3 (which passed) and its git parent change: https://go-review.googlesource.com/c/go/+/163677/2..3//COMMIT_MSG#b1

That's nearly 600 commits behind:

```
$ git log --format=oneline 73b803ee..4ebc6514 | wc -l
599
```

Dup of  golang/go#19664, golang/go#9858, golang/go#30807

**Comment by dmitshur** [comment]
> No, the git parent was old.

Ah, indeed. I made a mistake and looked at the wrong patch set. I'm glad it's a simple explanation.
