### ISSUE TITLE
cmd/internal/obj/x86, cmd/compile/internal/ssa: Possible lack of handling for panicIndex

### ISSUE THREAD

**Issue by nsajko** [golang/go#31219]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +56517216c0 Tue Apr 2 05:45:33 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Not applicable, I think.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/tmp/freedesktopCache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/nsajko"
GOPROXY=""
GORACE=""
GOROOT="/home/nsajko/goNew"
GOTMPDIR=""
GOTOOLDIR="/home/nsajko/goNew/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/nsajko/goNew/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build609693791=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Notice that panicindex was renamed to panicIndex since the release. Then I found that references to the old panicindex still exist in the tip.

### What did you expect to see?

I am guessing either panicIndex should be handled together with panicindex in the below files, or instead of panicindex. Sorry if this is not a bug, I am just guessing.

### What did you see instead?

src/cmd/internal/obj/x86/obj6.go:       case "runtime.panicindex", "runtime.panicslice", "runtime.panicdivide", "runtime.panicwrap", "runtime.panicshift":
src/cmd/compile/internal/ssa/rewrite.go:                                case "runtime.racefuncenter", "runtime.racefuncexit", "runtime.panicindex",
src/cmd/compile/internal/ssa/rewrite.go:                                        "runtime.panicslice", "runtime.panicdivide", "runtime.panicwrap",

**Comment by nsajko** [comment]
I think panicSlice is in the same situation as panicIndex.

**Comment by randall77** [comment]
Thanks. I will fix these. Both are optimizations that may not trigger because of the mismatch.

**Comment by odeke-em** [comment]
Thank you for this report @nsajko!

@randall77 thanks for taking this on! I've crafted for you a suggestion of a unit test that we use to ensure
we never regress after this is corrected. Please perhaps consider adding this to `cmd/compile/internal/ssa/rewrite_test.go`
```go
type stringerPlaceHolder string

func (sph stringerPlaceHolder) String() string {
        return string(sph)
}

func TestNeedRaceCleanup_OpStaticCall(t *testing.T) {
        mustTrigger := []string{
                "runtime.racefuncenter", "runtime.racefuncexit",
                "runtime.panicIndex", "runtime.panicslice", "runtime.panicdivide",
                "runtime.panicwrap", "runtime.panicshift",
        }
        t.Run("OpStaticCall", func(tt *testing.T) {
                testNeedRaceCleanup(tt, OpStaticCall, mustTrigger, true)
        })
        t.Run("OpClosureCall", func(tt *testing.T) {
                testNeedRaceCleanup(tt, OpClosureCall, mustTrigger, false)
        })
        t.Run("OpInterCall", func(tt *testing.T) {
                testNeedRaceCleanup(tt, OpInterCall, mustTrigger, false)
        })
}

func testNeedRaceCleanup(t *testing.T, op Op, names []string, want bool) {
        for _, symName := range names {
                v := &Value{
                        Block: &Block{
                                Func: &Func{
                                        Config: &Config{Race: true},
                                        Blocks: []*Block{
                                                {
                                                        Values: []*Value{
                                                                {
                                                                        Aux: stringerPlaceHolder(symName),
                                                                        Op:  op,
                                                                },
                                                        },
                                                },
                                        },
                                },
                        },
                }
                sym := stringerPlaceHolder("runtime.racefuncexit")
                got := needRaceCleanup(sym, v)
                if got != want {
                        t.Errorf("needRaceCleanup(%q)=%t want %t", symName, got, want)
                }
        }
}
```

**Comment by randall77** [comment]
@odeke-em Thanks for the test, but I think I found a better way to test using our codegen framework.

**Comment by odeke-em** [comment]
@randall77 cool, thanks for showing me that! I might be using the codegen framework in the near future and also writing such tests.
