### ISSUE TITLE
syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by mec07** [golang/go#31225]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/marc/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/marc"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/marc/src/github.com/shellagilehub/coc-activity-api/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p_/1pp4gq996nd4v1b7tpp4746h0000gn/T/go-build815798108=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Set the package name to something other than `main` then built it, e.g. (https://play.golang.org/p/wBbzloBXKH0)
```
package app

import (
	"fmt"
)

func main() {
	fmt.Println("Hello, playground")
}
```

it seems to have built fine and didn't give any errors:
```
$ go build -v -o ./bin/app ./cmd/app
```

The binary produced isn't executable, so make it executable and run it and it errors:
```
$ chmod +x ./bin/app
$ ./bin/app
./bin/app: line 1: syntax error near unexpected token `newline'
./bin/app: line 1: `!<arch>'
```
The error is pretty confusing.

### What did you expect to see?
I would have expected to have seen a compiler error.

### What did you see instead?
No compiler error, only an error when trying to run the binary.

**Comment by ianlancetaylor** [comment]
There is no compiler error because what you are doing is permitted and documented.  You are building an ordinary Go package.  This would normally produce a file like `app.a`, but you are using the `-o` option to store it in a file named `app`.  Then you are explicitly making it executable, and trying to run it.  There is no step here where the Go tools could emit an error.
