### ISSUE TITLE
x/crypto/sha3: When compiling for all platforms `undefined: cpu.S390X`

### ISSUE THREAD

**Issue by mjarkk** [golang/go#31227]
### What version of Go are you using (`go version`)?

<pre>
My laptop:
$ go version
go version go1.10.4 linux/amd64

In docker container:
$ go version:
go version go1.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
Laptop:
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mark/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mark/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build171862865=/tmp/go-build -gno-record-gcc-switches"

In container:
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build425469403=/tmp/go-build -gno-record-gcc-switches"
/go/src/github.com/mjarkk/test # go version
go version go1.12 linux/amd64

</pre></details>

### What did you do?

Code on play.golang.org: https://play.golang.org/p/oUY0D25kCzz  
Code:
```go
package main

import (
	"fmt"

	"golang.org/x/crypto/sha3"
)

func main() {
	fmt.Println(sha3.New256().Sum(nil))
}
```
How i compiled the code:  
```
$ GOARCH=s390x GOOS=linux go get
# golang.org/x/crypto/sha3
../../../golang.org/x/crypto/sha3/sha3_s390x.go:235:5: undefined: cpu.S390X
../../../golang.org/x/crypto/sha3/sha3_s390x.go:244:5: undefined: cpu.S390X
../../../golang.org/x/crypto/sha3/sha3_s390x.go:253:5: undefined: cpu.S390X
../../../golang.org/x/crypto/sha3/sha3_s390x.go:262:5: undefined: cpu.S390X
../../../golang.org/x/crypto/sha3/sha3_s390x.go:271:5: undefined: cpu.S390X
../../../golang.org/x/crypto/sha3/sha3_s390x.go:280:5: undefined: cpu.S390X
$ GOARCH=s390x GOOS=linux go build
# golang.org/x/crypto/sha3
../../../golang.org/x/crypto/sha3/sha3_s390x.go:235:5: undefined: cpu.S390X
../../../golang.org/x/crypto/sha3/sha3_s390x.go:244:5: undefined: cpu.S390X
../../../golang.org/x/crypto/sha3/sha3_s390x.go:253:5: undefined: cpu.S390X
../../../golang.org/x/crypto/sha3/sha3_s390x.go:262:5: undefined: cpu.S390X
../../../golang.org/x/crypto/sha3/sha3_s390x.go:271:5: undefined: cpu.S390X
../../../golang.org/x/crypto/sha3/sha3_s390x.go:280:5: undefined: cpu.S390X
```

### What did you expect to see?

```
$ GOARCH=s390x GOOS=linux go get
$ GOARCH=s390x GOOS=linux go build
```

### What did you see instead?

For some reason while trying to compile a docker container after a while it did just compile but i'm not sure why it did that. After i removed the compiled binary it showed the same error again.

**Comment by mundaym** [comment]
Hmmm, not sure what is happening here. I just tried that command sequence on my laptop and it worked fine.

One thing you could try is adding '-u' to your go get command line options. That will download dependencies automatically:

```bash
GOARCH=s390x GOOS=linux go get -u
```

**Comment by mjarkk** [comment]
That didn't work.  
But i think that I've found it,  
What i did:
- removed `~/go/src/golang.org/`
- ran `go get`
- ran `GOARCH=s390x GOOS=linux go build`
- no errors

This doesn't explain why docker also didn't compile but it works.  
I'm going to close this issue.
