### ISSUE TITLE
cmd/go: go mod change vendor content

### ISSUE THREAD

**Issue by daixiang0** [golang/go#31223]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/deploy/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build492195104=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```
git clone https://github.com/cortexproject/cortex.git
go mod init
go mod vendor
go mod tidy
```

### What did you expect to see?

Do not change vendor.

### What did you see instead?

Vendor changed.

**Comment by FiloSottile** [comment]
Can you elaborate on what change happened, after what command, and why it's unexpected?

**Comment by daixiang0** [comment]
After `go mod vendor`, there are lots of changes in`Vendor`.
Since i only want move from `dep` to `module`, all things about `dep` like `Vendor` should stay as they were.

**Comment by FiloSottile** [comment]
`go mod vendor` is more effective than dep at removing unneded files from the vendor folder. However, if the `go mod init` step went well, there should be no other meaningful change to the vendor folder.

If there is and you believe it is a bug, we will need instructions to reproduce the issues, and details on what changes.

**Comment by daixiang0** [comment]
I reproduce it:
```
$ git clone https://github.com/cortexproject/cortex.git
$ cd corex
$ GO111MODULE=on go mod init
go: creating new go.mod: module github.com/cortexproject/cortex
go: copying requirements from Gopkg.lock
$ git status
# On branch master
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	go.mod
$ GO111MODULE=on go mod vendor
$ git status
# On branch master
# Changes not staged for commit:
#   (use "git add/rm <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   vendor/cloud.google.com/go/bigtable/admin.go
#	modified:   vendor/cloud.google.com/go/bigtable/bigtable.go
#	modified:   vendor/cloud.google.com/go/bigtable/bttest/inmem.go
#	modified:   vendor/cloud.google.com/go/bigtable/filter.go
......
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	go.mod
#	go.sum
#	vendor/cloud.google.com/go/bigtable/go18.go
```

There is two question:
1. `go mod init` do not generate `go.sum`
2. `go mod vendor` change lots of things in `Vendor`

**Comment by daixiang0** [comment]
@FiloSottile hi, any input?

**Comment by bcmills** [comment]
`go mod init` does not promise to exactly reproduce the configuration of `dep`. It roughs in a starting point, from which the result is computed using minimal version selection and the transitive `go.mod` files of your dependencies.

To my knowledge, `dep` makes no effort to ingest or interpret the dependencies declared in `go.mod` files, so if any dependency has such a file, module mode can produce a substantially different result from `dep`. So merely being different from `dep` is not an error.

If you believe that the module-mode result is erroneous, please provide specific detail for which module's (or modules') requirements are not being followed. (#29773 is the only such issue that I know of at the moment.)

**Comment by daixiang0** [comment]
@bcmills hi, my key issue is that why `go mod` modify things under `vendor`, `go mod` do not need them any more, right?

**Comment by daixiang0** [comment]
Hi, i do below test in clean env:
```
$ docker run golang:1.12.1 /bin/bash
# go get github.com/cortexproject/cortex
# export GO111MODULE=on
# go mod init
# go mod vendor
# go mod tidy
```
Then i can see lots of changes in `vendor`.
@bcmills i test 3 times, reproduce every time.

**Comment by daixiang0** [comment]
@bcmills hi, any update?

**Comment by bcmills** [comment]
Your steps to reproduce explicitly invoke `go mod vendor`. The whole point of `go mod vendor` is to update the `vendor` directory.

As noted in https://github.com/golang/go/issues/31223#issuecomment-480818671: if you believe that the module-mode result is erroneous, please provide specific detail for which module's (or modules') requirements are not being followed.

**Comment by daixiang0** [comment]
Get it, `go mod vendor` not only get things from vendor and also update it.
But it may be confused for users who want to move `dep` to `go mod` since after move the `vendor` would be useless for them, so update `vendor` could be meaningless for them.
Add an option to avoid changes in `vendor` could be better i think.

**Comment by bcmills** [comment]
`go mod vendor` does not “get things from vendor” at all: its _only_ purpose is to update the `vendor` directory, and it currently begins that process by deleting it entirely (without reading from it) before repopulating it.

If you want to avoid changes in `vendor`, then simply don't run `go mod vendor`. (But see also #30240.)
