### ISSUE TITLE
net: document where service names come from?

### ISSUE THREAD

**Issue by TomitaSilvestruSC** [golang/go#31249]
Found in `net/http/server.go`:
 
```
type Server struct {
	Addr    string  // TCP address to listen on, ":http" if empty
```

What is this ":http" exactly? Presumably an alias, but I can't find any concrete documentation to know what it resolves to.

https://github.com/golang/go/blob/964fe4b80ff7a9e5490f11de0e216ae34a019ebc/src/net/http/server.go#L2477

**Comment by bradfitz** [comment]
https://golang.org/pkg/net/#Listen references
https://golang.org/pkg/net/#Dial which says "The port must be a literal port number or a service name."

Perhaps we should mention that comes from /etc/services (or equivalent, depending on OS).

**Comment by cuonglm** [comment]
@bradfitz How about mention that service name is defined in [RFC 6335](https://tools.ietf.org/html/rfc6335), and [assigned by IANA](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml)

**Comment by luka-zitnik** [comment]
Is there missing a description of the address format in general? -- Empty host or port, port "0", square brackets for ipv6 addresses, ... As a reader of the comment I would also be interested in what does using the service name effectively means -- will it be port 80 or a dynamically assigned port from the 80** range?

Can we do something like this?
```
type Server struct {

	// TCP address to listen on, ":http" (all IP addresses,
	// default http port) if empty
	// See package net for description of the address format
	Addr string
```

**Comment by AndersonQ** [comment]
As this issue has been inactive for a while, I'll submit a PR following @luka-zitnik suggestion.
