### ISSUE TITLE
quotedprintable decoding issue for = followed by digits

### ISSUE THREAD

**Issue by Vikrammel** [golang/go#31246]
### What version of Go are you using (`go version`)?
1.12

### Does this issue reproduce with the latest release?
yes.

### What operating system and processor architecture are you using (`go env`)?
linux, amd64 (but reproducible in go playground as well)

### What did you do?
https://play.golang.org/p/vPDX_UQCcTL
tried decoding a few URLs which use query params whose values are hashes. First 2 (digit) chars of hashes are mistaken for hex chars since they are preceded by an '=' and decoded.

### What did you expect to see?
don't decode =<first 2 digits of larger sequence>

### What did you see instead?
=<first 2 chars of hash> gets replaced by chars represented by that combination. This should probably only happen if 2 digits following '=' are not part of a larger sequence of chars like a hash.

**Comment by bradfitz** [comment]
It doesn't look like you're using the right package. Your input doesn't look like quoted-printable to me. Your input looks HTML escaped instead.

I don't see a bug here.  You can't have substrings like `tab=notifications` in a quoted-printable encoding, so you can't decode it with `quotedprintable.NewReader`.

**Comment by Vikrammel** [comment]
@bradfitz Sorry, I suppose you're right. I cannot reproduce the message here as it is from a private mailbox but we were trying to decode email message bodies which had the 'quoted-printable' value for the 'Content-Transfer-Encoding' header. But if they wanted to put links with '=' in their quoted-printable encoded message, it should be =3D so seems like an encoding issue on the other end. Thanks for looking into it.

**Comment by bradfitz** [comment]
Okay, closing.
