### ISSUE TITLE
cmd/go: get some.domain.net/... no longer works with custom domains

### ISSUE THREAD

**Issue by alandonovan** [golang/go#31241]
% ~/go1.10/bin/go version
go version go1.10.3 linux/amd64
% ~/go1.10/bin/go get -v -u  go.starlark.net/...
Fetching https://go.starlark.net/cmd/starlark?go-get=1
Parsing meta tags from https://go.starlark.net/cmd/starlark?go-get=1 (status code 200)
get "go.starlark.net/cmd/starlark": found meta tag get.metaImport{Prefix:"go.starlark.net", VCS:"git", RepoRoot:"https://github.com/google/starlark-go"} at https://go.starlark.net/cmd/starlark?go-get=1
get "go.starlark.net/cmd/starlark": verifying non-authoritative meta tag
Fetching https://go.starlark.net?go-get=1
Parsing meta tags from https://go.starlark.net?go-get=1 (status code 200)
go.starlark.net (download)
...
etc, success

% ~/goroot/bin/go version
go version devel +e9d1273997 Wed Apr 3 20:39:58 2019 +0000 linux/amd64
% ~/goroot/bin/go get -v -u  go.starlark.net/...
Fetching https://go.starlark.net/...?go-get=1
Parsing meta tags from https://go.starlark.net/...?go-get=1 (status code 404)
Fetching https://go.starlark.net?go-get=1
Parsing meta tags from https://go.starlark.net?go-get=1 (status code 200)
get "go.starlark.net": found meta tag get.metaImport{Prefix:"go.starlark.net", VCS:"git", RepoRoot:"https://github.com/google/starlark-go"} at https://go.starlark.net?go-get=1
go: finding go.starlark.net latest
go get go.starlark.net/...: unrecognized import path "go.starlark.net/..." (parse https://go.starlark.net/...?go-get=1: no go-import meta tags ())

Observe that the first command does one Fetch per package in the expansion of go.starlark.net/... whereas the second fetches https://go.starlark.net/...?go-get=1, which doesn't exist.

This breaks the google3 update.go script for custom domains.

**Comment by myitcv** [comment]
Is this a dup of https://github.com/golang/go/issues/29363?

**Comment by jayconrod** [comment]
Yes, I'll close this in favor of #29363. Looks like my CL will need to be updated to handle wildcards inside a module, too.
