### ISSUE TITLE
cmd/compile/internal/ssa: TestNexting broken on longtest builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#31263]
https://build.golang.org/log/accd72f95cd2dcfb4da4bee9029543f35d626fd1:

```
--- FAIL: TestNexting (14.26s)
    --- FAIL: TestNexting/gdb-dbg-i22558 (0.97s)
        debug_test.go:242: step/next histories differ, diff=
            --- testdata/i22558.gdb-dbg.nexts	2019-04-03 21:27:05.000000000 +0000
            +++ /workdir/tmp/debug_test870531445/test-i22558.gdb-dbg.nexts	2019-04-03 21:53:20.820874734 +0000
            @@ -2,10 +2,3 @@
             19:	func test(t *thing, u *thing) {
             20:		if t.next != nil {
             23:		fmt.Fprintf(os.Stderr, "%s\n", t.name)
            -24:		u.self = u
            -25:		t.self = t
            -26:		t.next = u
            -27:		for _, p := range t.stuff {
            -28:			if isFoo(t, p) {
            -29:				return
            -44:	}
```

The first failure is at https://golang.org/cl/168479, but https://golang.org/cl/170639 seems like a more likely culprit. (CC @randall77 for both.)

**Comment by randall77** [comment]
@dr2chase 
I don't see how either of those changelists would affect this test.

**Comment by bcmills** [comment]
Neither do I, but there's a clear inflection point in the dashboard, and the other CLs around that point seem even less likely.

**Comment by bcmills** [comment]
The fact that the `longtest` builder is so flaky from this regression is masking other failures in the `longtest` builder (#31421). This needs to be fixed soon.

**Comment by bcmills** [comment]
This test is now skipped in the builders. It should still be fixed, but is no longer quite as urgent.

**Comment by bradfitz** [comment]
It's back, but with a different subtest:

```
--- FAIL: TestNexting (13.64s)
    --- FAIL: TestNexting/gdb-opt-hist (3.06s)
        debug_test.go:245: step/next histories differ, diff=
```

Are these important or should we skip this too?

**Comment by dr2chase** [comment]
We skip it for now, sort it out during the freeze.
I might want to change the test to use Delve instead of gdb; it's generally less flaky and a lot easier to figure out what the debugger is doing.

**Comment by dr2chase** [comment]
This is probably fixed, because TestNexting now tests Delve instead of Gdb
