### ISSUE TITLE
cmd/go: go test reports module missing when no test files in the cwd

### ISSUE THREAD

**Issue by davecheney** [golang/go#31270]
### What version of Go are you using (`go version`)?

<pre>
$go version
go version devel +964fe4b80f Thu Apr 4 00:26:24 2019 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
% mkdir ~/devel/mod.a && cd ~/devel/mod.a
% go mod init github.com/davecheney/mod.a
% go test
```

### What did you expect to see?

```
can't load package: package github.com/davecheney/mod.a: no Go files in /Users/dfc/devel/mod.a
```

### What did you see instead?

```
can't load package: package github.com/davecheney/mod.a: unknown import path "github.com/davecheney/mod.a": cannot find module providing package github.com/davecheney/mod.a
```

**Comment by bcmills** [comment]
I feel like this is a duplicate but I can't find it right now.

CC @jayconrod

**Comment by bcmills** [comment]
Duplicate of #27122
