### ISSUE TITLE
x/arch/arm64/arm64asm: TestObjdumpARM64TestDecode{GNU,Go}Syntaxdata failing at Go 1.12.3

### ISSUE THREAD

**Issue by ohir** [golang/go#31305]
Relevant to #21506 and #23237.

Looks like a regression.
I can't recall this fail going from 1.10 to 1.11 on this staging env,
though its binutils certainly are newer than were at 1.10->1.11 testing.

I know that it is relevant to the `binutils` changing its output, but either tests should
account for changes in `objdump` or should fail with suitable message if `objdump` version
is not known to the tests.

<pre>
$  objdump --version
GNU objdump (GNU Binutils) 2.31.1.20180828-19

$ go version
go version go1.11.1 linux/amd64
#... other releases tested
go version go1.12.2 linux/amd64

<details><summary><code>go env</code> Output</summary><br>
$ go env
GOARCH="amd64"
GOBIN="/testbed/staging/bin"
GOCACHE="/testbed/staging/gocache"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/testbed/staging/user/go"
GOPROXY=""
GORACE=""
GOROOT="/testbed/staging/go"
GOTMPDIR="/testbed/staging/gotmp/"
GOTOOLDIR="/testbed/staging/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/testbed/staging/gotmp/go-build503835491=/tmp/go-build -gno-record-gcc-switches"</details>
$ git checkout go1.12.2
$ cd src && ./all.bash

<details><summary>all.bash Output: <br>(with 1.12.2 as bootstrap)</summary>
--- FAIL: TestObjdumpARM64TestDecodeGNUSyntaxdata (0.18s)
    ext_test.go:197: decode(9f3003d5) = "dsb #0x00", 4, want "ssbb", 4

    ext_test.go:197: decode(9f3403d5) = "dsb #0x04", 4, want "pssbb", 4

    ext_test.go:203: 4651 test cases, 933 expected mismatches, 2 failures; 56747 cases/second
    ext_test.go:204: decoder coverage: 96.4%;
    ext_test.go:203: 4651 test cases, 0 expected mismatches, 0 failures; 54157 cases/second
    ext_test.go:204: decoder coverage: 96.4%;
--- FAIL: TestObjdumpARM64TestDecodeGoSyntaxdata (0.12s)
    ext_test.go:197: decode(9f3003d5) = "dsb #0x00", 4, want "ssbb", 4

    ext_test.go:197: decode(9f3403d5) = "dsb #0x04", 4, want "pssbb", 4

    ext_test.go:203: 4564 test cases, 964 expected mismatches, 2 failures; 62673 cases/second
    ext_test.go:204: decoder coverage: 96.4%;
    ext_test.go:203: 4564 test cases, 0 expected mismatches, 0 failures; 62482 cases/second
    ext_test.go:204: decoder coverage: 96.4%;
FAIL
FAIL    cmd/vendor/golang.org/x/arch/arm64/arm64asm 2.087s
</pre></details>
**FAIL: cmd/vendor/golang.org/x/arch/arm64/arm64asm**

**Comment by ohir** [comment]
Tested on 1.12.3 built with 1.12.2 bootstrap.
```
go version go1.12.3 linux/amd64
git checkout go1.12.3
go test cmd/vendor/golang.org/x/arch/arm64/arm64asm

--- FAIL: TestObjdumpARM64TestDecodeGNUSyntaxdata
--- FAIL: TestObjdumpARM64TestDecodeGoSyntaxdata
both pieces fail at:
    ext_test.go:197: decode(9f3003d5) = "dsb #0x00", 4, want "ssbb", 4
    ext_test.go:197: decode(9f3403d5) = "dsb #0x04", 4, want "pssbb", 4
```

**Comment by bcmills** [comment]
CC @zhangfannie @cherrymui @mwhudson via `git blame`.

**Comment by bcmills** [comment]
Any idea why this isn't showing up as a failure on the build dashboard?

(https://build.golang.org/?branch=release-branch.go1.12)

**Comment by mwhudson** [comment]
I fixed this in x/arch (https://go.googlesource.com/arch/+/b19384d3c130858bb31a343ea8fce26be71b5998) but it doesn't look to me as if that fix is in release-branch.go1.12.

**Comment by cherrymui** [comment]
> Any idea why this isn't showing up as a failure on the build dashboard?

This test is very sensitive to the GNU objdump installed on the machine. It may pass if the builder has a different version.

**Comment by cherrymui** [comment]
Thanks @mwhudson. The vendored copy of x/arch/arm64 in the standard library is older. We just need to revendor it.
