### ISSUE TITLE
cmd/compile: internal compiler error: 'main': not lowered

### ISSUE THREAD

**Issue by ericlagergren** [golang/go#31315]
### What version of Go are you using (`go version`)?

1.12.2 (occurs with 1.12 and 1.12.1).

### What operating system and processor architecture are you using (`go env`)?

darwin/amd64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/Users/ericlagergren/gopath/bin"
GOCACHE="/Users/ericlagergren/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ericlagergren/gopath"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vp/6n5tkzt93_7cb22vrc0qd08r0000gn/T/go-build366116268=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
$ cat x.go
package main

import (
	"fmt"
	"math/bits"
)

func main() {
	fmt.Println(bits.Sub(4, 100, 0))
}
```

The bug is a bit different on the playground:

https://play.golang.org/p/UmLdx0JeZHN

### What did you expect to see?

```
18446744073709551520 1
```

### What did you see instead?

```
# command-line-arguments
<unknown line number>: internal compiler error: 'main': not lowered: v19, Store SSA PTR UINT64 SSA

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
```

**Comment by ericlagergren** [comment]
This does *not* reproduce the error:

```
package main

import (
	"fmt"
	"math/bits"
)

func main() {
	x, c := bits.Sub(4, 100, 0)
	fmt.Println(x, c)
}
```

**Comment by agnivade** [comment]
Seems to be fixed at tip. Can you confirm ?

**Comment by ericlagergren** [comment]
Yup. Sorry, I thought it sounded like another issue (dupe) I'd read before, but couldn't find one that was similar enough.
