### ISSUE TITLE
does net/rpc have packet sticky?

### ISSUE THREAD

**Issue by wenweihu86** [golang/go#31314]
### What version of Go are you using (`go version`)?
go version go1.10.3 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?
send many packets to server parallelly, so that server may receive incomplete packet.

### What did you expect to see?
server can solve packet sticky, that is if the received packet is incomplete, it can store the packet, and it can concat the two packets when receive the next packet.

### What did you see instead?
not test yet

**Comment by bcmills** [comment]
The `rpc` package is frozen and essentially unowned at this point, so you might have better luck asking in a different forum. (See https://golang.org/wiki/Questions.)
