### ISSUE TITLE
cmd/go: [modules + integration] go mod test, execute all the unit tests of a module

### ISSUE THREAD

**Issue by nim-nim** [golang/go#31324]
This report is part of a series, filled at the request of @mdempsky, focused at making Go modules integrator-friendly.

**Please do not close or mark it as duplicate before making sure you’ve read and understood the [general context](https://gist.github.com/nim-nim/9f72827d7cba9637dfe1492364ad9adf)**. A lot of work went into identifying problems points precisely.

### Needed feature

Go needs an official `go mod test` command that executes all the unit tests of a particular Go module, to make sure it is healthy.

### Constrains

* the input should be:
  * a `module path`,  or
  * a `module path` + `module version`, or
  * the `filesystem path` of a specific `mod` module descriptor
      * either the `go.mod` file at the root of an unpacked module tree, or
      * a `mod` file inside a  [goproxy](https://tip.golang.org/cmd/go/#hdr-Module_proxy_protocol) hierarchy
* all the usual `go test` flags  should apply
* the command should allow selecting (or not) the following test sets:
  * unit tests. Tests, that only require the compiler
  * integration tests. Tests, that have more needs than just the compiler, and that will fail in a generic CI/CD environment:
    * internet access,
    * root access
    * some specific software instance
    * some credentials
    * etc
* the command should work in secure no-internet-download mode. In that mode it should fail if one of the modules it needs for building is not available in the cache or configured goproxy  (#31304) sources
  * it should not get stuck forever waiting on the CI/CD firewall to let `go get` download from the internet

### Motivation

Go modules are wonderful and exciting, until you realise they only deal with the code download part. One stills need to dissect individual Go packages in the next stages of a CI/CD Go-related job.

The Go module concept should be extended to the rest of Go code processing phases.

**Comment by seankhliao** [comment]
this is just `go test ./...`
