### ISSUE TITLE
net/rpc: How to judge whether the client is shutdown？

### ISSUE THREAD

**Issue by humyPro** [golang/go#31337]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\admin\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\code\gopath
set GOPROXY=direct
set GORACE=
set GOROOT=C:\app\Go
set GOTMPDIR=
set GOTOOLDIR=C:\app\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\code\gopath\local\rawrpcdemo\rawrpc-webService\go.mod
set CGO_CFLAGS=-g -O2

</pre></details>

### What did you do?

Create an RPC client and server, start the server first, then start the client, and then restart the server, the client's RPC client will appear "connection is shut down" error, just a string. I need to determine if the connection is disconnected, but I can't get the'shutdown'field in Client.

**Comment by bcmills** [comment]
Note that, per https://tip.golang.org/pkg/net/rpc/, “The net/rpc package is frozen and is not accepting new features.”

Probably you will need to call a method and check for a return value of `rpc.ErrShutdown`, but it's not obvious to me whether you can do so without additional side-effects.
