### ISSUE TITLE
x/tools/cmd/gopls: no reply to shutdown request

### ISSUE THREAD

**Issue by hbar-x-2pi** [golang/go#31333]
### What version of Go are you using (`go version`)?

<pre>
go version go1.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOOS="linux"
</pre></details>

### What did you do?

Emacs (`lsp-mode`) hangs when closing a `go` file. The problem seems to be caused by the fact that in the current implementation:
https://github.com/golang/tools/blob/0fdf0c73855bae8482c5d3907a9e06f33ff70a10/internal/lsp/protocol/server.go#L79-L86

`gopls` does not reply to the `shutdown` request.

### What did you expect to see?

According to [the specification](https://microsoft.github.io/language-server-protocol/specification#shutdown) `gopls` should reply to the `shutdown` request.

Adding the following to the code fragment linked above solved this problem. 
```go
 else {
	conn.Reply(ctx, r, nil, nil)
}
```
This is just a quick workaround. The error should also be sent to the client and more importantly the server should reject other requests in between `shutdown` and `exit` with an `InvalidRequest`.

**Comment by ianthehat** [comment]
This is clearly something we need to fix, but I am also interested to know why/when emacs shuts down the language server. 
Restarting a language server is a very heavy weight operation, as it has to re-populate all it's caches, I want to make sure that emacs is not doing this in a way that is going to cause significant performance problems.

**Comment by hbar-x-2pi** [comment]
This happens when Emacs exits normally. I noticed that it got stuck for 20s (approx) after  `C-x C-c`.

There are more problems with the `lsp-mode` `emacs` interaction but I need more time to investigate. `gopls` dies from time to time and haven't yet figured out what is causing it.

**Comment by pekim** [comment]
I think that this fix has been lost, probably in https://github.com/golang/tools/commit/08ecc9ed.
