### ISSUE TITLE
cmd/link: support buildmode=pie with internal linking (on Android)

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#31343]
With [Termux](https://termux.com/) it's now within reach to run all.bash directly an Android device  without a host. Termux is an Android app that includes a complete Linux environment, including the NDK C toolchain.

However, I'm stopped by an unfortunate chain of constraints:

1. Android only run PIE binaries, so buildmode=pie must be set in cmd/dist (https://go-review.googlesource.com/c/go/+/170943).
2. Buildmode=pie forces external linking (#18968)
3. External linking requires that the g register is allocated to TLS storage.
4. Android doesn't support native ELF TLS storage (yet), so runtime/cgo is needed for setting up the g register storage at initialization using the pthread API.
5. cmd/dist doesn't know how to build runtime/cgo.

Of the above conditions, 1, 3 and 4 are outside our control and I don't think we want to fix 5.

This issue is about relaxing 2, so buildmode=pie no longer requires external linking.

**Comment by cherrymui** [comment]
I'm not sure about Android, but on Linux, on AMD64 internal linking PIE should work. It is not the default, but `-buildmode=pie -ldflags=-linkmode=internal` would do. On ARM64, it is ongoing work on https://golang.org/cl/163579.
