### ISSUE TITLE
use FreeOSMemory ,fd is free.

### ISSUE THREAD

**Issue by zhaoya881010** [golang/go#31357]
i found /proc/pid/fd change.
test code:
![image](https://user-images.githubusercontent.com/4704280/55771694-a2e7df80-5abb-11e9-998e-1a2fa2a4edcf.png)

build and run:
![image](https://user-images.githubusercontent.com/4704280/55771740-ddea1300-5abb-11e9-8d13-0d77471f8dd3.png)

ll /proc/pid/fd
![image](https://user-images.githubusercontent.com/4704280/55771763-f6f2c400-5abb-11e9-8445-fcd28408b2b1.png)

if used flock ，it may have question.

version go 1.12 linux/amd64

**Comment by randall77** [comment]
I'm not really sure what you are reporting.  In particular, we would need to see the "What did you expect to see" vs. "What did you see instead" sections.
I'm going to close this issue. Please feel free to open another and take care to complete all the sections of the template.

**Comment by agnivade** [comment]
And for code samples and logs, writing the actual text is always preferred than sending a screenshot.
