### ISSUE TITLE
regexp: get rid of the internal/testenv dependency

### ISSUE THREAD

**Issue by sylvinus** [golang/go#31350]
`regexp/exec_test.go` depends on `internal/testenv` for the sole purpose of doing this in 2 tests: `isRaceBuilder := strings.HasSuffix(testenv.Builder(), "-race")`

Would it be possible to refactor both tests, possibly moving some of their testcases to the `exec2_test.go` file which has `// +build !race`? I'm not sure if they are strictly equivalent.

This would make testing patches on the `regexp` module easier.

thanks!

**Comment by ianlancetaylor** [comment]
Why does it matter?  I run tests via `go test regexp`.  What are you doing?

**Comment by sylvinus** [comment]
Sorry I might not be doing the right thing.

I'm in my working copy of `src/regexp/` with failing tests. I would like to use my unpatched system go binary to run the tests. when I do that I get this:
```
➜  regexp git:(master) ✗ go test -run=TestRE2Search
# std/regexp
exec_test.go:11:2: use of internal package internal/testenv not allowed
FAIL	std/regexp [setup failed]
```

I have to do `../../bin/go test -run=TestRE2Search` for them to run. Is there another way?

thanks!

**Comment by ianlancetaylor** [comment]
I just change the regexp package in GOROOT without running `go install cmd/go`.  So I'm using the unpatched go binary as you suggest.  But it's true that it's a little more fragile.

But in general I don't think we should start removing `internal/testenv` from standard library tests.  The argument you are using here would apply to any standard library package, so the end result is that internal/testenv can never be used.  That doesn't seem ideal.

**Comment by sylvinus** [comment]
Yes I see your point and unfortunately I don't know enough about the whole context to suggest a proper fix. I just wanted to report this is making life a little harder for novice stdlib contributors :)

**Comment by rsc** [comment]
> I'm in my working copy of src/regexp/ with failing tests. I would like to use my unpatched system go binary to run the tests. 

If you set GOROOT explicitly to your working copy root, then that should work, provided your system go binary is a close enough version to your working copy. The best answer is to use the cmd/go binary from the working copy, of course. The main Go repo is a whole that moves forward together, not an a la carte menu. There are plenty of other cross-dependencies besides internal/testenv, and that's OK.

**Comment by sylvinus** [comment]
OK thanks that makes sense, thanks.
