### ISSUE TITLE
Build Issue on Windows

### ISSUE THREAD

**Issue by RajeshSeervi** [golang/go#31367]
**What version of Go are you using (`go version`)?**
go version go1.12 windows/amd64

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`go env`)?**
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\rajesh1.choudhary\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Rajesh_SW\GoLang
set GOPROXY=
set GORACE=
set GOROOT=C:\Rajesh_SW\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Rajesh_SW\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\rajesh1.choudhary\AppData\Local\Temp\go-build308731990=/tmp/go-build -gno-record-gcc-switches

**What did you do?**
Building HelloWorld program :-
> go build HelloWorld.go

**What did you expect to see?**
Binary should be generated.

**What did you see instead?**
Error :- 
C:\Rajesh_SW\Go\pkg\tool\windows_amd64\link.exe: cannot create $WORK\b001\exe\a.out.exe: open $WORK\b001\exe\a.out.exe: Access is denied.

**Comment by agnivade** [comment]
Hi @RajeshSeervi - this seems to be some permission related issue on your machine, and not a bug in the Go language. I would request you to reach out to the various forums at the [Questions](https://github.com/golang/go/wiki/Questions) wiki page. Folks will be glad to help you out there.

This issue tracker is only meant for tracking bugs and proposals specific to Go. In case you find this to be an issue with Go, please feel free to report back with concrete repro steps for us to debug. Thanks.

**Comment by RajeshSeervi** [comment]
Hi @agnivade, initially I thought same, but when I run command with "-work" option  (go build -work HelloWorld.go), I got the temporary work directory which was used while building, it is crated successfully. Issue is with a.out.exe, it is not generated.

You are right that it might be permission issue. 

**Can you guide how can I change temporary WORK folder path for building go files ?**

**Comment by agnivade** [comment]
I am not well-versed in Windows. I would request you to ask in any of the forums mentioned above. You will get better help there.

**Comment by RajeshSeervi** [comment]
Got it and issue resolved.
In windows Go "WORK" path is taken from windows "TMP" environment variable.
It worked by creating new folder and changing "TMP" path in windows.
TMP is changed only before running build command for that shell, so that it doesn't impact other processes running on windows.

Thanks.

**Comment by xmapst** [comment]
@RajeshSeervi 
Can you show the detailed configuration

**Comment by mhussein79** [comment]
maybe late a bit :) 
I go the same error. Error :-
C:\Rajesh_SW\Go\pkg\tool\windows_amd64\link.exe: cannot create $WORK\b001\exe\a.out.exe: open $WORK\b001\exe\a.out.exe: Access is denied

so I clicked the right click on the cmd prompt and selected run as administrator. then it works fine and built the exe.

*make sure the environment variables modified as mentioned in the setup notes.

**Comment by EugenSorin** [comment]
I see the issue is closed.
There is not an building issue. I just got the same problem and I found the cause: the antivirus who suspect the result of the build and blocked it. And the same compilation works a day before ;-)
Well, can also be an acces problem (from recent changes of the rights policy), but is little likely.

**Comment by G-kpoor** [comment]
Use Windows Powershell instead command prompt and make sure you accessing in Administrator mode
