### ISSUE TITLE
x/mobile/bind: Reflection to get ApplicationContext is disallowed on Android P (API Level 28) and causes a crash on Android Q

### ISSUE THREAD

**Issue by timcooijmans** [golang/go#31364]
### Problem
For loading gobind-libraries on Android, currently the non-SDK method `android.app.AppGlobals.getInitialApplication` is used via reflection in [LoadJNI.java](https://github.com/golang/mobile/blob/master/bind/java/LoadJNI.java#L28) to provide the `ApplicationContext` to the native-library.
```java
Application appl = (Application)Class.forName("android.app.AppGlobals").getMethod("getInitialApplication").invoke(null);
androidCtx = appl.getApplicationContext();
```

Usage of non-SDK methods is not allowed in Android P and up (API level 28 and higher), for more information see: [developer.android.com: Restrictions on non-SDK interfaces](https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces)
From Android Q on this prevents an gobind-library from loading and causes an exception:
```
 D/StrictMode: StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/app/AppGlobals;->getInitialApplication()Landroid/app/Application;
        at android.os.StrictMode.lambda$static$1(StrictMode.java:406)
        at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
        at java.lang.Class.getDeclaredMethodInternal(Native Method)
        at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
        at java.lang.Class.getMethod(Class.java:2066)
        at java.lang.Class.getMethod(Class.java:1693)
        at go.LoadJNI.<clinit>(LoadJNI.java:28)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at go.Seq.<clinit>(Seq.java:38)
        at go.Seq.touch(Seq.java:55)
```

### Solution
I think we should consider asking the `ApplicationContext` to be provided by the application when loading the gobind-library instead of acquiring it via reflection.  

An proposal to defer context-binding was discussed in #12725. Another option would be to defer loading of the library itself.

**Comment by timcooijmans** [comment]
I introduced a fix: https://github.com/golang/mobile/pull/30

**Comment by timcooijmans** [comment]
With the Play Store now giving warnings, can we look at this or another solution getting merged?

**Comment by dmitshur** [comment]
This was resolved via [CL 175103](https://golang.org/cl/175103), closing.

(The reason it wasn't closed automatically is because the "Fixes #31364" line in the commit message was missing the "golang/go" prefix required on subrepos. See details [here](https://golang.org/wiki/CommitMessage#other-repos)).

**Comment by hajimehoshi** [comment]
It looks like the fix makes `app.RunOnVM` unavailable for gomobile-bind. I realized that originally `RunOnVM` should not be used for gomobile-bind, so that's fine, I was surprised though.

**Comment by timcooijmans** [comment]
`app.RunOnVm` should still work, but you have to call the (new) static method `Seq.init(Context context)` to pass the required `Context` to Go before using `app.RunOnVm`

**Comment by hajimehoshi** [comment]
I think you meant `Seq.setContext`? Yes, that fixed the issue. I missed that in the CL. Thank you!

BTW, I started to wonder if reverse binding would be better than `RunOnJVM`. `RunOnJVM` cannot be called in `init` functions while the reverse binding should be available anywhere. I'll check this later.

**Comment by timcooijmans** [comment]
Yes, sorry quick reply from my phone. I edited my original post.
