### ISSUE TITLE
x/*: introduce semantically versioned tags

### ISSUE THREAD

**Issue by jsha** [golang/go#31371]
According to https://github.com/golang/go/wiki/Modules#semantic-import-versioning:

> As a result of Semantic Import Versioning, code opting in to Go modules must comply with these rules:
> Follow semver (with tags such as v1.2.3).

Right now, the x/* repositories, e.g. https://github.com/golang/crypto, https://github.com/golang/net, and https://github.com/golang/sys, don't appear to have version tags, but they are opted into Go modules (they have go.mod files). Could you start tagging releases for these repositories?

This would make managing go.mod files that depend on them much easier, since those files would contain a semver tag rather than an opaque commit hash. The opaque commit hash makes it hard to figure out whether a given go.mod file requires a higher version of a dependency than is currently in use.

**Comment by ALTree** [comment]
Thanks for the request.

This is a dup of #21324 (x/all: start tagging versions); note that it's on hold:

> On hold until Go 1.11 and/or Go 1.12. At least until we have tooling ready and some experience with said tooling.

I'm closing this thread in favour of the older one.
