### ISSUE TITLE
x/tools/internal/lsp: generated files not marked with "// Code generated" comments

### ISSUE THREAD

**Issue by wxio** [golang/go#31375]
Much of the code in protocol is unidiomatic. Starts making more sense in the context of generated code. 

Please decorate generated code with the standard comment.

**Comment by wxio** [comment]
eg
``` 
// Code generated by go.ts DO NOT EDIT.
// source:   /vscode-languageserver-node/protocol/src/protocol.ts, /vscode-languageserver-node/types/src/main.ts
// commit: 54f6caacea8aa0cf9f45527153d993010c1cc793
// tag: n/a
```

**Comment by pjweinb** [comment]
Yup. Now there are 3 generated files, and they all need DO NOT EDIT.

Coming within a week.
