### ISSUE TITLE
x/tools/gopls: use xerrors package

### ISSUE THREAD

**Issue by bstaletic** [golang/go#31374]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/bstaletic/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/bstaletic/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build434682588=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

This is basically a continuation of https://github.com/golang/go/issues/31194. This time I'm having troubles getting to gopls' log.

Steps to reproduce:

- Follow all but the final two steps in https://github.com/golang/go/issues/31194 (basically, setup ycmd and open a go file).
- Currently, the gopls command line is `gopls -logfile /tmp/gopls_$PID_$RANDOM.log`
  - The file and its name is generated by ycmd.
- If the log path is hardcoded (to somthing like `/home/bstaletic/go.log`), the empty log file gets created but nothing is written to the file.

### What did you expect to see?

Some content in the log, to help me debug things.

### What did you see instead?

Empty log whose size was 0bytes.

**Comment by ianthehat** [comment]
try adding -rpc.trace and it will log all the rpc messages

**Comment by bstaletic** [comment]
Thanks. That did work. Is there also a way to log tracebacks when an error is returned?

**Comment by stamblerre** [comment]
Not right now, but we should switch to using the https://golang.org/x/xerrors package so that we can do that.

**Comment by bstaletic** [comment]
Thanks for the response. For what it's worth, I did make a PR for our project to use `gopls` instead of `gocode` and `godef`.

https://github.com/Valloric/ycmd/pull/1243

**Comment by jan-xyz** [comment]
I would like to take on this issue, what's the best way to start?

**Comment by stamblerre** [comment]
Thanks for contributing this, @jan-xyz! Closing this issue since https://golang.org/cl/179880 has been submitted.
