### ISSUE TITLE
How to mount file in linux 

### ISSUE THREAD

**Issue by wNee** [golang/go#31381]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.3 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wnie/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/wnie/go/src/git.dev.fwmrm.net/core/common/src/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tx/kyk53m810j321smxnpxn47r9bpbt8m/T/go-build800267695=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
Use syscall.Mount

### What did you expect to see?
I want to know is there any update to use linux mount? Please show me an example.

### What did you see instead?
This syscall.Mount() func is not exist. Conflict with the doc https://golang.org/pkg/syscall/#Mount

**Comment by tklauser** [comment]
The output above indicates you're running Go on `darwin`. Is this what you want? `syscall.Mount` currently only exists on `linux`. The `syscall` package is frozen as per https://github.com/golang/go/blob/62ec3dd260324d243491b271d53ccdfd4a1f14e3/src/syscall/syscall.go#L21-L25, but we might add `Mount` for `darwin` tot eh  `golang.org/x/sys/unix` package.
