### ISSUE TITLE
runtime: bad use of bucket.mp crash

### ISSUE THREAD

**Issue by rename2** [golang/go#31380]
### What version of Go are you using (`go version`)?
<pre>
go1.11.5 linux/amd64
(compile to linux/386)
</pre>

### Does this issue reproduce with the latest release?
Don't know. Have not upgrade to latest release.

### What operating system and processor architecture are you using (`go env`)?
<pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build342362144=/tmp/go-build -gno-record-gcc-switches"
</pre>

### What did you do?
Developing a program that periodically executing scripts to monitor system status.

### What did you expect to see?
No crashes.

### What did you see instead?
Random crashes.
<pre>
fatal error: bad use of bucket.mp

goroutine 83 [running]:
runtime.throw(0x866a21b, 0x14)
	/usr/local/go/src/runtime/panic.go:608 +0x6a fp=0xab0fda4 sp=0xab0fd90 pc=0x806fc4a
runtime.(*bucket).mp(0xe6fa16c8, 0xe74d8fd8)
	/usr/local/go/src/runtime/mprof.go:189 +0x46 fp=0xab0fdb0 sp=0xab0fda4 pc=0x80699e6
runtime.mProf_FlushLocked()
	/usr/local/go/src/runtime/mprof.go:308 +0x37 fp=0xab0fdc4 sp=0xab0fdb0 pc=0x8069e67
runtime.mProf_Flush()
	/usr/local/go/src/runtime/mprof.go:299 +0x45 fp=0xab0fdcc sp=0xab0fdc4 pc=0x8069e15
runtime.gcMarkTermination(0xe06b6471, 0x3fe7e074)
	/usr/local/go/src/runtime/mgc.go:1649 +0x6e8 fp=0xab0ff7c sp=0xab0fdcc pc=0x805eea8
runtime.gcMarkDone()
	/usr/local/go/src/runtime/mgc.go:1510 +0x213 fp=0xab0ff9c sp=0xab0ff7c pc=0x805e773
runtime.gcBgMarkWorker(0xa836c00)
	/usr/local/go/src/runtime/mgc.go:1909 +0x2a1 fp=0xab0ffe8 sp=0xab0ff9c pc=0x805f981
runtime.goexit()
	/usr/local/go/src/runtime/asm_386.s:1324 +0x1 fp=0xab0ffec sp=0xab0ffe8 pc=0x809a201
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1720 +0x61
</pre>

**Comment by ALTree** [comment]
Thanks for the report.

This will be hard to debug unless you provide a reproducer. 

Usual questions:
- Does your program use cgo?
- Does the race detector barks if you run your program with the `-race` flag (i.e. `go run -flag main.go`)?

**Comment by ALTree** [comment]
Closing here, see my comment at https://github.com/golang/go/issues/31379#issuecomment-484048020 (OP's code contains data races).
