### ISSUE TITLE
Compiling on different OS

### ISSUE THREAD

**Issue by lwlwilliam** [golang/go#31385]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOOS=windows
</pre></details>

### What did you do?

I want to implement a http server with tcp socket.

https://play.golang.org/p/lx-AJvpdkdH

### What did you expect to see?

Visit "http://localhost:10000" with browser and receive the correct response.

### What did you see instead?

When I build the program on Windows, the browser shows "This site can’t be reached. The connection was reset."

When I build the same program on Linux, the browser can show me the correct response "Hello world!".

**Comment by bcmills** [comment]
Some versions of Windows have a built-in firewall. You may need to configure the firewall to allow `localhost` connections on port 10000.

(That's more of a Windows issue than a Go one.)

**Comment by lwlwilliam** [comment]
> Some versions of Windows have a built-in firewall. You may need to configure the firewall to allow `localhost` connections on port 10000.
> 
> (That's more of a Windows issue than a Go one.)

Maybe it is irrelevant with the configuration of firewall. if I use the io package and insert the code before line 17 as follows:

```
var buf = make([]byte, 1024)
_, err := conn.Read(buf)
checkErr(err)
```

https://play.golang.org/p/6XioZaILQ_A

The program works well. It seems that I must read all the bytes from the socket on Windows.
