### ISSUE TITLE
error from Packge csv

### ISSUE THREAD

**Issue by hyangfji** [golang/go#31395]
### What version of Go are you using (`go version`)?

<pre>
go version go1.12.2 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/hoyang/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/proj/cmcad_develop8/hoyang/tmp/go"
GOPROXY=""
GORACE=""
GOROOT="/home/hoyang/go"
GOTMPDIR=""
GOTOOLDIR="/home/hoyang/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build748992403=/tmp/go-build"
</pre></details>

### What did you do?

I tried to use Package csv to parse a CSV file and got an error due to unusual patterns in the CSV file.

### What did you expect to see?

For this line:
"2019-01-16 11:45:54",,-1,,script,,dain0070,/proj/dk/technology/production-projrev,"\\"/ \\. [^/]+ \\.swp $\\",",Create,,/tmp/tmperC1xd/reportDeviceTotalWidth_work/gen_pininfo
I expect to get "\\"/ \\. [^/]+ \\.swp $\\"," as a field.

### What did you see instead?

2019/04/10 18:16:20 parse error on line 864, column XXX: extraneous or missing " in quoted-field

**Comment by agnivade** [comment]
Please see - https://golang.org/pkg/encoding/csv/#pkg-overview

> Within a quoted-field a quote character followed by a second quote character is considered a single quote.

Add another double-quote inside your field - `"\""/ \. [^/]+ \.swp $\""`
