### ISSUE TITLE
Some responses using net/http client don't have content-length in header.

### ISSUE THREAD

**Issue by odg0318** [golang/go#31394]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
I didn't try it with latest version.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> GOARCH="amd64"
GOBIN=""
GOCACHE="***/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="***/golang"
GOPROXY=""
GORACE=""
GOROOT="***/.gobrew/versions/1.11"
GOTMPDIR=""
GOTOOLDIR="***/.gobrew/versions/1.11/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9m/67253zn170n5wy5npvpn1d980000gp/T/go-build568756787=/tmp/go-build -gno-record-gcc-switches -fno-common"</summary><br><pre>
$ go env

</pre></details>

#### My code
https://play.golang.org/p/iXIURvuXKdh
```golang
package main

import (
	"log"
	"net/http"
)

func main() {
	res, _ := http.Get("http://ipinfo.io")
	log.Printf("%v %v", res.ContentLength, res.Header)
}
```
#### Output
```
2019/04/11 08:02:18 -1 map[Date:[Wed, 10 Apr 2019 23:02:18 GMT] Content-Type:[application/json; charset=utf-8] Vary:[Accept-Encoding] X-Powered-By:[Express] Access-Control-Allow-Origin:[*] X-Frame-Options:[DENY] X-Content-Type-Options:[nosniff] Via:[1.1 google]]
```

### What did you expect to see?
`res.ContentLength` or `res.Header['Content-Length']` is set.

### What did you see instead?
`res.ContentLength` is `-1` and `Content-Length` is missing in `res.Header`.

I will show other results.
#### NodeJS
```node
var http = require('http')
http.request('http://ipinfo.io', (res) => { console.log(res.headers) }).end()
> { date: 'Wed, 10 Apr 2019 22:42:28 GMT',
  'content-type': 'application/json; charset=utf-8',
  'content-length': '167',
  vary: 'Accept-Encoding',
  'x-powered-by': 'Express',
  'access-control-allow-origin': '*',
  'x-frame-options': 'DENY',
  'x-content-type-options': 'nosniff',
  via: '1.1 google',
  connection: 'close' }
```

#### Python 2.7
```bash
>>> import urllib2
>>> dict(urllib2.urlopen('http://ipinfo.io').info())
{'content-length': '167', 'via': '1.1 google', 'x-content-type-options': 'nosniff', 'x-powered-by': 'Express', 'vary': 'Accept-Encoding', 'connection': 'close', 'date': 'Wed, 10 Apr 2019 23:00:13 GMT', 'access-control-allow-origin': '*', 'content-type': 'application/json; charset=utf-8', 'x-frame-options': 'DENY'}
```

#### curl
```base
$ curl -i http://ipinfo.io
HTTP/1.1 200 OK
Date: Wed, 10 Apr 2019 23:38:31 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 167
Vary: Accept-Encoding
X-Powered-By: Express
Access-Control-Allow-Origin: *
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Via: 1.1 google
```

**Comment by agnivade** [comment]
See - https://golang.org/pkg/net/http/#Response  `Uncompressed bool` 

Set `DisableCompression: true` in http.Transport to get the content-length.
