### ISSUE TITLE
syscall: TestDirentRepeat broken on FreeBSD 11.2

### ISSUE THREAD

**Issue by bradfitz** [golang/go#31403]
https://go-review.googlesource.com/c/go/+/171477 broke:

https://build.golang.org/log/659cce8aef83ace25901509984f0d41e0bf1833b
```
--- FAIL: TestDirentRepeat (0.00s)
    dirent_bsd_test.go:131: bad file list: want
        ["file0" "file1" "file10" "file11" "file12" "file13" "file14" "file15" "file16" "file17" "file18" "file19" "file2" "file20" "file21" "file22" "file23" "file24" "file25" "file26" "file27" "file28" "file29" "file3" "file30" "file31" "file32" "file33" "file34" "file35" "file36" "file37" "file38" "file39" "file4" "file40" "file41" "file42" "file43" "file44" "file45" "file46" "file47" "file48" "file49" "file5" "file50" "file51" "file52" "file53" "file54" "file55" "file56" "file57" "file58" "file59" "file6" "file60" "file61" "file62" "file63" "file64" "file65" "file66" "file67" "file68" "file69" "file7" "file70" "file71" "file72" "file73" "file74" "file75" "file76" "file77" "file78" "file79" "file8" "file80" "file81" "file82" "file83" "file84" "file85" "file86" "file87" "file88" "file89" "file9" "file90" "file91" "file92" "file93" "file94" "file95" "file96" "file97" "file98" "file99"]
        got
        ["file0" "file1" "file10" "file11" "file12" "file13" "file14" "file15" "file2" "file3" "file4" "file5" "file6" "file62" "file63" "file64" "file65" "file66" "file67" "file68" "file69" "file7" "file70" "file71" "file72" "file73" "file74" "file75" "file76" "file77" "file78" "file79" "file8" "file9"]
FAIL
FAIL	syscall	0.058s
```

**Comment by eliasnaur** [comment]
I believe both netbsd also broke by the same change, in a different way:

https://build.golang.org/log/08ee3b794c5871f4778b426526f5072f3083bed7

**Comment by paulzhol** [comment]
https://github.com/golang/go/blob/a6af1041f6889fddd71c2a08308f52637b3f345d/src/syscall/dirent_bsd_test.go#L109-L112

On FreeBSD 11.x `syscall.Dirent` is not the type stored/read. It is converted from `syscall.dirent_freebsd11 `, also the minimum buffer size to read dirents into is 1024 bytes (DIRBLKSIZ).

https://github.com/golang/go/blob/3cb92fcba71f9c0d64b3b714fc92870065848345/src/syscall/ztypes_freebsd_amd64.go#L185-L202

The convertion is done in `Getdirentries`:
https://github.com/golang/go/blob/3cb92fcba71f9c0d64b3b714fc92870065848345/src/syscall/syscall_freebsd.go#L268-L282
