### ISSUE TITLE
cmd/cgo: ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by nitishsaboo** [golang/go#31408]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by agnivade** [comment]
Incomplete.

**Comment by Arshiamidos** [comment]
https://github.com/golang/go/issues/31409#issuecomment-482641900
