### ISSUE TITLE
`slc = append(slc, )`  pass compile

### ISSUE THREAD

**Issue by northfun** [golang/go#31400]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.12
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
code as this:
```
tars = append(tars, ) 
```

### What did you expect to see?

compile err.
I wonder why it is designed to pass well,it does nothing but mostly would be a typo,shouldn't it be found early?

### What did you see instead?

go-fmt pass, compile pass

**Comment by cuonglm** [comment]
I think it works as expected, a variadic arguments can be zero or more.

**Comment by northfun** [comment]
Sorry, I find `go-fmt` removes the last comma.
