### ISSUE TITLE
expvar: overhead cost of Map.Add when the number of entries grows

### ISSUE THREAD

**Issue by ShiKaiWi** [golang/go#31414]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xkwei/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xkwei/Code/GO"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s2/s4mtcvn50z798btptmrvvg3h0000gp/T/go-build853285173=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I tried to use `Map` in package the `expvar` to collect some metrics but I found it would be very slow to call `Add` method of it when the number of entries in the map grew. As for the concurrent case most of goroutines calling the `Add` of the same `Map` instance would be blocked.

And the source code of the `Add` method tells that in the `Add` method a sorting for all the keys will be executed holding the lock:
```
// addKey updates the sorted list of keys in v.keys.
func (v *Map) addKey(key string) {
	v.keysMu.Lock()
	defer v.keysMu.Unlock()
	v.keys = append(v.keys, key)
	sort.Strings(v.keys)
}

....

// Add adds delta to the *Int value stored under the given map key.
func (v *Map) Add(key string, delta int64) {
	i, ok := v.m.Load(key)
	if !ok {
		var dup bool
		i, dup = v.m.LoadOrStore(key, new(Int))
		if !dup {
			v.addKey(key)
		}
	}

	// Add to Int; ignore otherwise.
	if iv, ok := i.(*Int); ok {
		iv.Add(delta)
	}
}
```

### What did you expect to see?
1. It should be low-cost to add a key in the `Map` even if the number of the keys is large.
2. I think it is a waste to do sorting every time a new key is added. (Actually I guess it can be sorted only when output if the sorted outputs is necessary)
3. I think it is not smart to do a high cost operation(sorting) holding a lock. (Actually it is better to search and insert in this case).

### What did you see instead?
Holding the lock do a sort for all the entries.

**Comment by bcmills** [comment]
If you were to resolve the bottleneck in `(*expvar.Map).Add`, you would find that there is one lurking below it in `sync.Map` (#21032). Reducing contention for newly-added keys will require a lot of work.

**Comment by ShiKaiWi** [comment]
> If you were to resolve the bottleneck in `(*expvar.Map).addKey`, you would find that there is one lurking below it in `sync.Map` (#21032). Reducing contention for newly-added keys will require a lot of work.

@bcmills  thanks for your quick reponse.

Actually I only want to avoid `sort.Strings(v.keys)` in the `(*expvar.Map).addKey` which is high cost when holding too many keys and more serious the lock won't be released until sort is finished. 

The code and benchmark of #31418 may help explain what I say.
