### ISSUE TITLE
go modules can`t download dependicies with first attempt

### ISSUE THREAD

**Issue by mr-tron** [golang/go#31415]
<pre>
$ go version
go version go1.12.1 linux/amd64
</pre>

<pre>
$ go env
 go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/tmp/gopath"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go12"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go12/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/vault-pki-backend-venafi/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build415455380=/tmp/go-build -gno-record-gcc-switches"

</pre>

### What did you do?
```
mkdir /tmp/gopath
cd /tmp
export GOPATH=/tmp/gopath
git clone 
git clone https://github.com/Venafi/vault-pki-backend-venafi
git fetch
git checkout 7f1e61d8e437c53ca6f09dd17200d9c51cc890d9
env CGO_ENABLED=0 GOOS=linux   GOARCH=amd64 go build -ldflags '-s -w -extldflags "-static"' -a -o /tmp/plugin 

```

### What did you expect to see?

success build

### What did you see instead?

```
go: finding github.com/hashicorp/vault-plugin-secrets-gcp v0.0.0-20190409204055-960ba981b05e
go: finding github.com/araddon/gou v0.0.0-20190110011759-c797efecbb61
....
blah-blah-blah
....
go: finding golang.org/x/oauth2 v0.0.0-20181017192945-9dcd33a902f4
go: google.golang.org/api@v0.0.0-20181220000619-583d854617af: git -c protocol.version=0 fetch --unshallow -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /tmp/gopath/pkg/mod/cache/vcs/9e62a95b0409d58bc0130bae299bdffbc7b7e74f3abe1ecf897474cc474b8bc0: exit status 1:
	fatal: bad object c7964aab01c00a07d0cc6216a78a5570459cebfd
	error: https://code.googlesource.com/google-api-go-client did not send all necessary objects
go: error loading module requirements
```

if I repeat command `go build`,  it downloads dependecies and finish succesfull. but after clening cache i see problem again.

**Comment by mr-tron** [comment]
https://github.com/golang/go/issues/31399 - looks like same problem

**Comment by jayconrod** [comment]
Yep, looks to be a dup of #31399.
