### ISSUE TITLE
os: TestRemoveAllDotDot broken at head

### ISSUE THREAD

**Issue by bcmills** [golang/go#31421]
Observed in https://build.golang.org/log/79c45622d3e12177863a8eafbb8772e26af1a30c.

Broken in https://golang.org/cl/171099 (#29921), and the breakage in the longtest builder was masked by #31263.

**Comment by bcmills** [comment]
And some others too:

```
~/go/src/os$ go test .
--- FAIL: TestRemoveAllDotDot (0.00s)
    removeall_test.go:252: unlinkat /tmp/TestRemoveAllDotDot-695588954/x/y: error from RemoveAllTestHook
--- FAIL: TestRemoveUnreadableDir (0.00s)
    removeall_test.go:406: openfdat /tmp/TestRemoveAllButReadOnly-192841201/d0/d1/d2: permission denied
--- FAIL: TestRemoveAllButReadOnlyAndPathError (0.00s)
    removeall_test.go:360: got "/tmp/TestRemoveAllButReadOnly-172665500/a/x/1", expected pathErr.path "/tmp/TestRemoveAllButReadOnly-172665500/b/y"
FAIL
FAIL    os      18.322s
```

**Comment by cuonglm** [comment]
@bcmills Thanks for the fix :+1: 

Can you tell my why trybot result and local test passed in my original CL?

**Comment by ianlancetaylor** [comment]
Because the tests are run in short mode by default, and your test wasn't run in short mode.

**Comment by cuonglm** [comment]
> Because the tests are run in short mode by default, and your test wasn't run in short mode.

Ah right, but how can it test in my local run? I just did `go-tip test -v -count=1`.

Is there a way I can make sure that my test will run all tests or mimic the builder so we won't get in this trouble next time?

**Comment by bcmills** [comment]
The `os` package resolves to whatever `os` package is present in the `GOROOT` of the `go` command (`go-tip` in your example), so if you built `go-tip` in a different `GOROOT` from the one in which you drafted the CL, then `go-tip test os` might have actually tested a copy of the `os` package without your changes.
