### ISSUE TITLE
cmd/go: require and replace doesn't seem to like uppercase

### ISSUE THREAD

**Issue by ryandawsonuk** [golang/go#31437]
I was trying to use a submodule under a relative path and set up the go.mod to do a replace like in https://stackoverflow.com/questions/52079662/go-get-cannot-find-local-packages-when-using-modules

In my case the github organisation name has an uppercase in it. So think `github.com/Org/repo/proj/submod` But the error when I did a `go build` from the top-level came out with:

`build github.com/org/repo/proj: cannot load github.com/org/repo/proj/submod: cannot find module providing package github.com/org/repo/proj/submod`

I then changed the require and replace statements in the top-level go.mod to refer to the submodule with the all-lowercase and then it worked.
 
go version go1.12.1 linux/amd64

Issue similar to https://github.com/golang/go/issues/26208 and https://github.com/golang/go/issues/27157

**Comment by rsc** [comment]
> build github.com/org/repo/proj: cannot load github.com/org/repo/proj/submod: cannot find module providing package github.com/org/repo/proj/submod

This message is saying "build <PACKAGE>: cannot load <IMPORTED PACKAGE>: reason". It sounds like (1) your go.mod in github.com/org/repo says 'module github.com/org/repo' with lowercase org, and (2) github.com/org/repo/proj contains a Go import of "github.com/org/repo/proj/submod", again with lowercase org.

What matters is what's in the go.mod file and what is in the import statements. It sounds like they are both lowercase.

Without details it's hard to say more.

**Comment by bcmills** [comment]
If the case in the `module` directive doesn't match the case in the `import` statement, part of the `stderr` output should at least clearly diagnose that condition. @ryandawsonuk, what was the complete output of `go build`?

(This situation should already be improved at head by @jayconrod's diagnostic changes for #28489.)

**Comment by ryandawsonuk** [comment]
Sorry you are right. It does work for me now - I must have had some mismatch.
