### ISSUE TITLE
syscall: undefined symbols _readdir_r$INODE64, _fdopendir$INODE64 on iOS simulators

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#31447]
## What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +08e1823a63 Tue Apr 9 05:45:34 2019 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/elias/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/elias/go"
GOPROXY=""
GORACE=""
GOROOT="/Users/elias/go-tip"
GOTMPDIR=""
GOTOOLDIR="/Users/elias/go-tip/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/elias/go/src/golang.org/x/mobile/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_7/lnt35k555hl2bs7fjygkhgx00000gp/T/go-build472586928=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

go test -short golang.org/x/mobile/bind/objc

### What did you expect to see?
no errors

### What did you see instead?
```
...
        	Undefined symbol: _readdir_r$INODE64
        	Undefined symbol: _fdopendir$INODE64
...
```

This is caused by the fix for https://github.com/golang/go/issues/30933, where getdirentries is replaced by calls to readdir_r and fdopendir. Unfortunately, the 64-bit inode versions of those syscalls are suffixed with $INODE64 on macOS but not on iOS. Since Go does not use a separate GOOS for iOS, the error above appear when running on a simulator (amd64).

CC @randall77.

**Comment by donnie-jp** [comment]
I experienced this issue while trying to follow https://github.com/golang/go/wiki/Mobile#building-and-deploying-to-ios-1

`go version devel +97dfbc54e6 Wed Apr 24 01:10:42 2019 +0000 darwin/amd64`
and
`Xcode 10.2`
