### ISSUE TITLE
x/build/cmd/gomote: retrieve buildlet from $MOTE if present

### ISSUE THREAD

**Issue by josharian** [golang/go#31445]
I usually set a $MOTE envvar when using gomote, to minimize typing:

```
export MOTE=some-buildlet
gomote push $MOTE
gomote run $MOTE go/src/make.bash
```

I propose we hard-code this convention. All gomote commands that take a buildlet argument will check whether $MOTE is set. If so, it pretends $MOTE was provided in that argument slot. So all existing commands work unchanged as long as $MOTE is not set. If it is set, the commands above become:

```
export MOTE=some-buildlet
gomote push $MOTE
gomote run $MOTE go/src/make.bash
```

Opinions? @bradfitz @dmitshur

**Comment by bradfitz** [comment]
Dup of #29037 it seems. Re-open if you disagree.
