### ISSUE TITLE
x/tools/cmd/gopls: GoToDef does not work with embedded pointer structs

### ISSUE THREAD

**Issue by marwan-at-work** [golang/go#31451]
Say you have a struct that looks like this: 

```golang
type A struct {}

type B struct {
    *A
}
```

If you tried to GoToDef on the embedded struct `*A` inside `B`, then the GoToDef does not work. But if you remove the `*`, then GoToDef works properly by moving the cursor to the A declaration

cc: @ianthehat

**Comment by muirrn** [comment]
I'll work on this one if it is still available.

**Comment by stamblerre** [comment]
It is available. Thanks!

**Comment by ianthehat** [comment]
Although Marwan did mention he might decide to look at himself, not sure if he still means to or not?
I believe this is probably related to the special handling for embedded fields [here](https://github.com/golang/tools/blob/master/internal/lsp/source/definition.go#L95)

**Comment by marwan-at-work** [comment]
@muirrn you beat me to it so it's all yours :)

**Comment by muirrn** [comment]
Oops, didn't mean to step on anyone's toes.
