### ISSUE TITLE
runtime/chan.go: Why atomic.Load in chanrecv but directly read in chansend

### ISSUE THREAD

**Issue by anjiawei1991** [golang/go#31455]
in chan.go, I noticed that atomic.Load  is called while checking whether there's some data ready for read in function **chanrecv**.  but directly read while checking whether there's some space for write or some waiting receivers in **chansend**.

So, I want to know why.  Thank you!

**Comment by ianlancetaylor** [comment]
A better place to ask this kind of question is golang-nuts.  See https://golang.org/wiki/Questions.

Also, it helps to directly quote the lines you are asking about.  In this case I guess you are asking about

```Go
	if !block && (c.dataqsiz == 0 && c.sendq.first == nil ||
		c.dataqsiz > 0 && atomic.Loaduint(&c.qcount) == 0) &&
		atomic.Load(&c.closed) == 0 {
		return
	}
```

in `chanrecv` and

```Go
	if !block && c.closed == 0 && ((c.dataqsiz == 0 && c.recvq.first == nil) ||
		(c.dataqsiz > 0 && c.qcount == c.dataqsiz)) {
		return false
	}
```

in `chansend`.

If that is your question, see the discussion in https://codereview.appspot.com/110580043 .  The race between reading from a channel and closing a channel discussed there only happens on read, not send.
