### ISSUE TITLE
crypto, x/crypto: use math.bits rotate functions instead of ad-hoc implementations

### ISSUE THREAD

**Issue by vitaminniy** [golang/go#31456]

**Comment by andybons** [comment]
@FiloSottile

**Comment by dgryski** [comment]
The following query finds a number of additional cases in /x/crypto when run with `GOARCH=arm64` to scan the non-amd64-assembly versions.

```
gogrep -x       '$a >> $k | $a << (64 - $k)' ./...
gogrep -x       '($a >> $k) | ($a << (64 - $k))' ./...
gogrep -x       '$a << $k | $a >> (64 - $k)' ./...
gogrep -x       '($a << $k) | ($a >> (64 - $k))' ./...
gogrep -x       '$a >> (64 - $k) | $a << $k' ./...
gogrep -x       '($a >> (64 - $k)) | ($a<< $k)' ./...
gogrep -x       '$a << (64 - $k) | $a >> $k' ./...
gogrep -x       '($a << (64 - $k)) | ($a >> $k)' ./...
gogrep -x       '$a >> $k | $a << (32 - $k)' ./...
gogrep -x       '($a >> $k) | ($a << (32 - $k))' ./...
gogrep -x       '$a << $k | $a >> (32 - $k)' ./...
gogrep -x       '($a << $k) | ($a >> (32 - $k))' ./...
gogrep -x       '$a >> (32 - $k) | $a << $k' ./...
gogrep -x       '($a >> (32 - $k)) | ($a<< $k)' ./...
gogrep -x       '$a << (32 - $k) | $a >> $k' ./...
gogrep -x       '($a << (32 - $k)) | ($a >> $k)' ./...
```

**Comment by vitaminniy** [comment]
Probably we can close this one as soon as the [#171731](https://go-review.googlesource.com/c/go/+/171731/) would be merged.

```bash
➜  src git:(master) find crypto -type f -name "*.go" -exec egrep ".+>>(\d)+ \| .+<<\((\d)+-(\d)+\)" {} \+
crypto/sha256/sha256block.go: t1 := (v1>>17 | v1<<(32-17)) ^ (v1>>19 | v1<<(32-19)) ^ (v1 >> 10)
crypto/sha256/sha256block.go: t2 := (v2>>7 | v2<<(32-7)) ^ (v2>>18 | v2<<(32-18)) ^ (v2 >> 3)
crypto/sha256/sha256block.go: t1 := h + ((e>>6 | e<<(32-6)) ^ (e>>11 | e<<(32-11)) ^ (e>>25 | e<<(32-25))) + ((e & f) ^ (^e & g)) + _K[i] + w[i]
crypto/sha256/sha256block.go: t2 := ((a>>2 | a<<(32-2)) ^ (a>>13 | a<<(32-13)) ^ (a>>22 | a<<(32-22))) + ((a & b) ^ (a & c) ^ (b & c))
```

@FiloSottile

**Comment by vitaminniy** [comment]
> Probably we can close this one as soon as the [#171731](https://go-review.googlesource.com/c/go/+/171731/) would be merged.
> 
> ```shell
> ➜  src git:(master) find crypto -type f -name "*.go" -exec egrep ".+>>(\d)+ \| .+<<\((\d)+-(\d)+\)" {} \+
> crypto/sha256/sha256block.go: t1 := (v1>>17 | v1<<(32-17)) ^ (v1>>19 | v1<<(32-19)) ^ (v1 >> 10)
> crypto/sha256/sha256block.go: t2 := (v2>>7 | v2<<(32-7)) ^ (v2>>18 | v2<<(32-18)) ^ (v2 >> 3)
> crypto/sha256/sha256block.go: t1 := h + ((e>>6 | e<<(32-6)) ^ (e>>11 | e<<(32-11)) ^ (e>>25 | e<<(32-25))) + ((e & f) ^ (^e & g)) + _K[i] + w[i]
> crypto/sha256/sha256block.go: t2 := ((a>>2 | a<<(32-2)) ^ (a>>13 | a<<(32-13)) ^ (a>>22 | a<<(32-22))) + ((a & b) ^ (a & c) ^ (b & c))
> ```
> 
> @FiloSottile

There is code in x/crypto that contains bit rotation operations. Should it be changed in case of this particular issue?

**Comment by FiloSottile** [comment]
I would be happy to take two global CLs, one for `crypto/...` and one for `x/crypto/...`, fixing all cases identified by gogrep according to https://github.com/golang/go/issues/31456#issuecomment-483104913.

**Comment by AlexanderYastrebov** [comment]
@FiloSottile Is there any chance to land changes mentioned in https://github.com/golang/go/issues/31456#issuecomment-946300450?

**Comment by seankhliao** [comment]
what's left here?

**Comment by dgryski** [comment]
My semgrep rule (above) doesn't have any hits in `crypto/...` or `x/crypto/...`.  Seems like we're probably good to close this.
