### ISSUE TITLE
golang.org/x/tools: fatal failed to traverse parents of commit

### ISSUE THREAD

**Issue by HazCod** [golang/go#31460]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xxx/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xxx/Source/go/"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/go-build718381006=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

<pre>
go mod init testrepo
go mod vendor
</pre>

### What did you expect to see?
All modules installed to vendor/

### What did you see instead?
<pre>
$ go mod vendor
go: finding github.com/oblq/i18n latest
go: finding golang.org/x/text/language latest
go: finding google.golang.org/appengine/log latest
go: finding cloud.google.com/go/profiler latest
go: finding golang.org/x/tools v0.0.0-20190114222345-bf090417da8b
go: golang.org/x/tools@v0.0.0-20190114222345-bf090417da8b: git -c protocol.version=0 fetch --unshallow -f https://go.googlesource.com/tools refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/niels/Source/go/pkg/mod/cache/vcs/b44680b3c3708a854d4c89f55aedda0b223beb8d9e30fba969cefb5bd9c1e843: exit status 128:
	error: Could not read a8576e2603b2bc62c97e830174b002dba60d6a0c
	fatal: Failed to traverse parents of commit 44bcb96178d39510d2bb8a61ef1c08b85bb24a45
	error: remote did not send all necessary objects
go: error loading module requirements
</pre>

**Comment by agnivade** [comment]
Likely a duplicate of https://github.com/golang/go/issues/31399.

@jayconrod @draftcode

**Comment by agnivade** [comment]
@HazCod - is this still happening for you ?

**Comment by HazCod** [comment]
Seems to be fixed now, thanks for the followup!
