### ISSUE TITLE
x/tools/go/packages: cgo error in one package causes entire Load to fail

### ISSUE THREAD

**Issue by dominikh** [golang/go#31462]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.3 linux/amd64
go version devel +a01d108e30 Sun Apr 14 16:19:31 2019 +0000 linux/amd64
</pre>

Trying to load multiple packages with packages.Load fails if any of the packages have cgo errors:

```
desktop 1? ~ $ cat $GOPATH/src/sandbox/foo/*.go
package main

import (
	"fmt"
)

func main() {
	x := 42
	fmt.Printf("%w\n", x)
}
desktop ~ $ cat $GOPATH/src/sandbox/bar/*.go
package bar

import "C"

func fn() {
	C.doesnotexist()
}
desktop ~ $ cat /tmp/foo.go 
package main

import (
	"log"

	"golang.org/x/tools/go/packages"
)

func main() {
	cfg := &packages.Config{
		Mode: packages.LoadAllSyntax,
	}
	_, err := packages.Load(cfg, "sandbox/foo", "sandbox/bar")
	if err != nil {
		log.Fatal(err)
	}
}
desktop ~ $ go run /tmp/foo.go 
2019/04/15 01:13:57 go [list -e -json -compiled=true -test=false -export=false -deps=true -find=false -- sandbox/foo sandbox/bar]: exit status 2: # sandbox/bar
prj/src/sandbox/bar/bar.go:6:2: could not determine kind of name for C.doesnotexist
exit status 1
desktop 1? ~ $ 
```

I expected packages.Load to return no error, to get two packages for sandbox/foo and sandbox/bar, and sandbox/bar to have a non-empty Errors.

/cc @ianthehat @matloob

**Comment by sauyon** [comment]
After discussion with @dominikh on IRC, we've worked out the source of the bug:

cgo preprocessing always happens, and the tool doesn't expect there to be build output/failures unless the function `usesExportData(cfg)` evaluates to true. This causes `Load` function to think the `driver` has failed, and therefore error out before doing any analysis. Interestingly, the error code seems to only get set if `-compiled=true` is passed.

This bug will therefore only trigger if `packages.NeedExportsFile` is not set and either `packages.NeedTypes` is not set or `packages.NeedTypesInfo` is set.

Relevant code:
`usesExportData`: https://github.com/golang/tools/blob/212fb13d595e5faf79425c78ae101012873a81a1/go/packages/packages.go#L1073
Relevant exception: https://github.com/golang/tools/blob/212fb13d595e5faf79425c78ae101012873a81a1/go/packages/golist.go#L818

**Comment by matloob** [comment]
This is fixed by [golang.org/cl/192330](golang.org/cl/192330).

**Comment by matloob** [comment]
This is fixed by [golang.org/cl/192330](https://golang.org/cl/192330)
