### ISSUE TITLE
os: RemoveAll failing silently in go 1.12.2 when removing non-empty directories at /

### ISSUE THREAD

**Issue by BooleanCat** [golang/go#31468]
### What version of Go are you using (`go version`)?

1.12.{2|3|4}

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
docker run \
                --rm \
                -v /Users/pivotal/workspace/deletepls:/deletepls \
                -w /deletepls \
                -it golang:1.12.4-alpine3.9 \
                go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build8
97413456=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I work on the garden project, we help orchestrate container lifecycle operations. I bumped the version of go 1.12.4 we build with and saw a consistent failure in our CI for a test related to removing a file.

I see the same failure on go 1.12.2 and go 1.12.3, but not on go 1.12.1.

I have reproduced the issue with a small go binary here (I'm going to continue to tease out the issue here, for now it's doing roughly what my code in the garden project is doing):

```
package main

import (
	"os"
	"path/filepath"
)

func main() {
	hello := filepath.Join("/", "hello")

	if err := os.MkdirAll(filepath.Join(hello, "there"), 0700); err != nil {
		panic(err)
	}

	if err := os.RemoveAll(hello); err != nil {
		panic(err)
	}

	if _, err := os.Stat(hello); err == nil {
		panic("what?")
	}
}
```

**Edited with simpler solution: the problem seems to occur when I try to RemoveAll a directory positioned at `/` after having ChDir'd to `/`.**

**Edited again: Chdir is not needed to repro**

I run `make` with this makefile

```
.PHONY = run

tag ?= 1.12.4-alpine3.9

run:
	docker run \
		--rm \
		-v /Users/pivotal/workspace/deletepls:/deletepls \
		-w /deletepls \
		-it golang:$(tag) \
		go run main.go
```

... and observe a panic on `"what?"` (indicating that I was able to stat a file I just deleted).

When I run `make tag=1.12.1-alpine3.9` I observe no panic.

### What did you expect to see?

I expect this snippet to not panic.

### What did you see instead?

The snippet panics on go 1.12.2+ but not on 1.12.1.

**Comment by BooleanCat** [comment]
Interestingly, I can delete `/hello` with `RemoveAll` if I `RemoveAll("hello")` rather than `RemoveAll("/hello")` (i.e. use a relative path).

**Comment by BooleanCat** [comment]
This might be the culprit - if I revert this line it works as I expect: https://github.com/golang/go/commit/d039e12b54a73796caa913994597a9f3a73e8e87#diff-55fac2af5cab3979fb5c47e41d21e0e4L54

**Comment by BooleanCat** [comment]
Resolved in PR - will sign CLA and other admin tomorrow.

**Comment by ianlancetaylor** [comment]
Thanks--I have a slightly different patch with a test.

**Comment by ianlancetaylor** [comment]
@gopherbot please open backport to 1.12

**Comment by BooleanCat** [comment]
@ianlancetaylor I was thinking about how I'd write a test for this given I'd need to write at / to reproduce with RemoveAll, but saw the export test file - neat trick!
