### ISSUE TITLE
x/mobile: gomobile doesn't find Android NDK installed from typical dist pkgs

### ISSUE THREAD

**Issue by quite** [golang/go#31461]
On Ubuntu, the google-android-ndk-installer leaves the NDK in /usr/lib/android-ndk, and it seems to be up to the user to set ANDROID_NDK_HOME.

On Arch Linux, the android-ndk package installs the NDK into /opt/android-ndk and sets ANDROID_NDK_HOME to there using an /etc/profile.d/file

There are also other variables, such as ANDROID_NDK, but they seem deprecated. This was somewhat informative: https://github.com/openssl/openssl/pull/8103

**Comment by eliasnaur** [comment]
One complication is that `gomobile build` uses tools from the Android SDK. What to do when only ANDROID_NDK_HOME is set?

**Comment by quite** [comment]
It looks like all code that references ANDROID_HOME returns error if if can't be find.

And the code that I touch for this issue is only in the `ndkRoot()` function, so just doing our best there to find the NDK should be enough.
