### ISSUE TITLE
x/tools/cmd/gopls: "Request textDocument/definition failed" when working on a module whose upper directory contains no Go code

### ISSUE THREAD

**Issue by kidlj** [golang/go#31492]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> 

</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mellon/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mellon/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/01/v02g0nk97_98qt_4_dsq07hw0000gn/T/go-build847911855=/tmp/go-build -gno-record-gcc-switches -fno-common

</pre></details>

### What did you do?

Open demo code: https://github.com/kidlj/pki-example in vscode with the latest 0.9.3-beta.7 vscode-go extension and gopls language server on.

There's is a module inside the repository, which is `github.com/kidlj/pki-example/demo`.

When open the module directory with vscode, which is `demo`, it works fine.

```
$ code ~/Code/pki-example/demo
```

Instead if I open the upper directory, which is `pki-example`, gopls fails everything.

```
$ code ~/Code/pki-example
```

In the second case, gopls logs:

```
[Error - 2:08:41 AM] Request textDocument/codeAction failed.
  Message: no file information for file:///Users/mellon/Code/pki-example/demo/main.go
  Code: 0 
```

<img width="1680" alt="WX20190417-014312@2x" src="https://user-images.githubusercontent.com/300616/56233943-d081e980-60b6-11e9-89d5-f2c0f3196378.png">

### What did you expect to see?

gopls works with vscode.

### What did you see instead?

vscode 'Go To Definition' fails.

**Comment by ianthehat** [comment]
This is working as intended, you need to add any module directories you are using by hand as workspace directories in your vscode project. Until you do, the module is not visible to gopls, even if the files are, and thus it cannot analyze any of the code.
This is not something that gopls can fix, but it is possible in the future that the vscode go extension could either add the directories for you.

**Comment by divmgl** [comment]
@ianthehat do you mean adding directories using Go modules under the `"folders"` property in the JSON? Because I did this and it's still not working for me.

```
[Error - 3:16:57 PM] Request textDocument/hover failed.
  Message: no file information for file:///Users/dextermiguel/Documents/dev/ss/k2/cmd/lambda/survey-ingest-legacy/survey-ingest-legacy.go
  Code: 0 
```

```
{
  "folders": [
    {
      "path": "."
    },
    {
      "path": "/Users/dextermiguel/Documents/dev/ss/k2/cmd/lambda/survey-ingest-legacy"
    }
  ],
```

**Comment by ianthehat** [comment]
yes, but note that once you add them you currently need to reload the window as we do not track the update messages
