### ISSUE TITLE
cmd/compile: segfaults in `s390x` port after CL 170448

### ISSUE THREAD

**Issue by bcmills** [golang/go#31496]
The `linux-s390x-ibm` builder is throwing `SIGSEGV` all over the place as of https://golang.org/cl/170448.

I'm not sure whether that's a bug in the escape analysis change, or if it just tickled existing bugs in the `s390x` compiler or runtime, but it seems alarmingly consistent.

https://build.golang.org/log/17d8a268ff942ee3fa4fa27ea8685aaa4347b689
https://build.golang.org/log/0e2023e3028d604edf2875a48664849fd1b0b53d
https://build.golang.org/log/c6708844df8c89743f2db3e2bf35b3dfd630a5f9

CC @mdempsky @cherrymui @dr2chase @aclements

**Comment by mdempsky** [comment]
Dup of #31495.
