### ISSUE TITLE
encoding/gob: test frequently failing with "signal: killed" in longtest builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#31517]
The `encoding/gob` test is frequently failing in the `longtest` builder with output like:

```
signal: killed
FAIL	encoding/gob	13.202s
```

(That's the entire output.)

First example I saw was in https://build.golang.org/log/608043bae4b6ccc72e79f266fd92fa51410517b1, but the failure mode doesn't obviously relate to the associated CL (https://golang.org/cl/172418).

I haven't been able to replicate the failure locally so far. I don't know whether the failure is due to recent changes in the compiler (@mdempsky, @cuonglm) or in `cmd/go` (myself and @jayconrod).

The transition from passing to failure was partially masked by #31263.

**Comment by bcmills** [comment]
There are enough `uintptr` shenanigans in `encoding/gob` that I'm inclined to suspect that the escape-analysis change uncovered another bug.

I'm still unable to reproduce the failure locally, though, so can't confirm.

**Comment by bcmills** [comment]
The only tests in `encoding/gob` that call `testing.Short()` are `TestFuzzOneByte`, `TestCountEncodeMallocs`, and `TestCountDecodeMallocs`, so it must be one of those.

**Comment by cuonglm** [comment]
@bcmills the builder just run `go tool dist test` or something else?

**Comment by bcmills** [comment]
@cuonglm, yes, it's running `go tool dist test`.

**Comment by bcmills** [comment]
Some searching suggests that the `signal: killed` failure message may indicate that the test ran out of memory.

(`ulimit -m` is apparently completely nonfunctional on Linux, so that explains why the failure is hard to replicate...)

**Comment by ALTree** [comment]
This happened in the past for gob: #28321

**Comment by bcmills** [comment]
For folks debugging along: `go test -c encoding/gob && /usr/bin/time -v ./gob.test` seems to successfully report max RSS.

**Comment by bcmills** [comment]
I'm observing a bimodal distribution of RSS for `gob.test`: it seems to consume either ~470500 KiB (~4.5 GiB) or ~8750000 KiB (~8.4 GiB).

Samples at both of those sizes occur at all CLs in recent history, but there is an inflection point in the distribution at [CL 170448](https://golang.org/cl/170448), wherein the larger RSS goes from about 1 in 16 runs (on my machine) to about 1 in 2.

The 1⁄2 rate roughly corresponds to the observed failure rate of the `longtest` builder. However, I can't explain why haven't observed `longtest` builder failures at the 1⁄16 rate before now.

**Comment by bcmills** [comment]
I think @robpike and @mdempsky will need to decide whether the fix belongs in the `encoding/gob` tests, in the new escape-analysis code, or perhaps elsewhere in the runtime.

**Comment by bcmills** [comment]
(CC @aclements for the interaction with GC pacing.)

**Comment by mdempsky** [comment]
Looking at -m output, the make(map) at encoding/gob/decode.go:1121 is now stack allocated:

    op := dec.decIgnoreOpFor(wireField.Id, make(map[typeId]*decOp))

That looks correct to me (decIgnoreOpFor's inProgress parameter doesn't leak). I wonder if it happens to affect GC pacing somehow?

**Comment by mdempsky** [comment]
Removing @robpike for now. encoding/gob doesn't use package unsafe, so I don't think it should be to blame for any escape analysis changes.

**Comment by mdempsky** [comment]
FYI, RSS seems very sensitive to GOMAXPROCS. E.g., if I set GOMAXPROCS=1, then -newescape=true does a lot better; if I set GOMAXPROCS=4, then -newescape=false does a lot better.

**Comment by mdempsky** [comment]
I can't spot anything wrong with escape analysis here. I'm inclined to say encoding/gob's tests straddle some cliff in the GC sensitive to a few things, and the new escape analysis just tweaked the conditions that it falls over.

@aclements Can I pass this to you to look into for GC?

**Comment by bcmills** [comment]
> I'm inclined to say encoding/gob's tests straddle some cliff in the GC sensitive to a few things, and the new escape analysis just tweaked the conditions that it falls over.

That agrees with my measurements from earlier (going from 1⁄16 to 1⁄2, with the 1⁄16 possibly masked by some detail of the builder — such as its default GOMAXPROCS setting or per-core throughput).

**Comment by mdempsky** [comment]
> Do we know which specific test is causing this now that we understand the nature of the failure better?

Looks like TestFuzzOneByte. I can reproduce the bimodal distribution change with -test.run=FuzzOneByte.

**Comment by mdempsky** [comment]
I've tried poking at this a bit with `go tool trace` and `go tool pprof`, but performance stuff isn't really my strong point. As best I can tell, `gob.test -test.run=FuzzOneByte` allocates less memory now when built with `-gcflags=all=-newescape=true` than `-gcflags=all=-newescape=false`, so I'm unsure why it's leading to a higher RSS more often.

**Comment by robpike** [comment]
The test is pretty aggressively expensive and could dial back the default cost. It isn't necessary to run it to its full run on every test of the package.
