### ISSUE TITLE
cmd/go: go get mod/... fails to resolve version

### ISSUE THREAD

**Issue by rsc** [golang/go#31518]
This used to work but now fails:

	$ go get -d rsc.io/quote/...
	go: finding rsc.io/quote/... latest
	go get rsc.io/quote/...: no matching versions for query "latest"
	$

**Comment by jayconrod** [comment]
I changed this yesterday in [CL 171138](https://go-review.googlesource.com/c/go/+/171138), so I might have broken something. `go get -d rsc.io/quote/...` is actually one of the test cases though, so I'm surprised it doesn't work.

How can I reproduce this? The commands below succeeded for me at tip:

```
export GOPATH=$(mktemp -d)
cd $(mktemp -d)
go mod init m
go get rsc.io/quote/...
```

```
go: finding rsc.io/quote v1.5.2
go: downloading rsc.io/quote v1.5.2
go: extracting rsc.io/quote v1.5.2
go: finding rsc.io/sampler v1.3.0
go: finding golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c
go: downloading rsc.io/sampler v1.3.0
go: extracting rsc.io/sampler v1.3.0
go: downloading golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c
go: extracting golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c
```

**Comment by bcmills** [comment]
I just checked again and my result matches Jay's: this seems to be working. Perhaps it was broken at some intermediate point during the development cycle?

Please reopen if you have concrete steps that reproduce the failure.

```
$ gotip version
go version devel +62fb079e Thu Sep 19 04:46:17 2019 +0000 linux/amd64

example.com$ gotip mod init example.com
go: creating new go.mod: module example.com

example.com$ gotip get -d rsc.io/quote/...
go: finding rsc.io/quote v1.5.2
go: downloading rsc.io/quote v1.5.2
go: extracting rsc.io/quote v1.5.2
go: downloading rsc.io/sampler v1.3.0
go: extracting rsc.io/sampler v1.3.0
go: downloading golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c
go: extracting golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c

example.com$
```
