### ISSUE TITLE
runtime/map Non-atomic hashWriting flag may cause data corruption

### ISSUE THREAD

**Issue by samaingw** [golang/go#31516]
### What version of Go are you using (`go version`)?

`master`

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

Any.

### What did you do?
Inspect [runtime map](https://github.com/golang/go/blob/master/src/runtime/map.go) for concurrent access checks. I am not talking about `sync.map`.

### What did you expect to see?
`hashWriting` flag (un)set with atomic operations.

### What did you see instead?
Non atomic operations like in those lines:
[mapaccess flag set](https://github.com/golang/go/blob/master/src/runtime/map.go#L595),
[mapaccess flag reset](https://github.com/golang/go/blob/master/src/runtime/map.go#L682).

These instructions compile to the following assembly instructions, without any prior lock:
1. `mov` from memory into register;
2. `<binary_operation>` (e.g. `xor`, `and`, ...);
3. `mov` from register back into memory.

These instructions, as well as the checks above them, are not guaranteed to be atomic.
As a consequence, we *may* have (rare but some) cases were a concurrent access is not detected.

**Comment by randall77** [comment]
This is ok as is, I think. The checks that this flag enables are best effort. They are intended to help catch races in user programs, but there are no guarantees.

Accesses which would cause problems, like simultaneous writes to a map, are already forbidden by the language spec.
