### ISSUE TITLE
net: use the same default TCPKeepAlive interval in net.Listen and net.Dial

### ISSUE THREAD

**Issue by CAFxX** [golang/go#31510]
In https://github.com/golang/go/issues/23378#issuecomment-483984051 we noted that there is a mismatch between the default TCP keepalive used by `net.Listen` (3m, previously in `http.ListenAndServe(TLS)`) and the one used by `net.Dial` (15s).

For uniformity, it would be advisable to ensure these two defaults match.

If there are no counter-proposals, my suggestion would be to use 15s as the interval (see #23459 for prior discussion).

An explicit non-goal of this issue is that of making the default value part of the API. For the reasons discussed in https://go-review.googlesource.com/c/go/+/107196 this should remain undefined, and users that have specific requirements in terms of exact keepalive durations should specify a custom configuration.

**Comment by FiloSottile** [comment]
Does `http.ListenAndServe` still actually set a TCP Keep-Alive? When I looked yesterday, I couldn't find it anymore, and assumed it was now relying on the new `net.Listen` default.

**Comment by FiloSottile** [comment]
Yeah, this is not in net/http as of 1abf3aa55bb8b346bb1575ac8db5022f215df65a.

The `Accept()` default is 3 minutes though, not 15s.

**Comment by CAFxX** [comment]
Yeah, but the net.Listen default is 3m *because* 1abf3aa lifted the default out of ListenAndServe and into net.Listen. This is orthogonal though to the point that these two defaults (in net.Listen and net.Dial) should be the same for consistency.

**Comment by FiloSottile** [comment]
Changed the title accordingly. release-blocker because the net.Listen keep-alive is new, so we should decide if we are changing it before shipping it, ideally.

**Comment by CAFxX** [comment]
Are there specific concerns against the approach outline above?

> If there are no counter-proposals, my suggestion would be to use 15s as the interval (see #23459 for prior discussion).

If there are none, I'll go ahead and send a CL.

**Comment by rsc** [comment]
I can't see why these should be different. Go ahead and send a CL.
