### ISSUE TITLE
cmd/go: go mod vendor looking for AUTHORS in root

### ISSUE THREAD

**Issue by masterada** [golang/go#31524]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\adam.kiss\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\go\workspace
set GOPROXY=
set GORACE=
set GOROOT=C:\go
set GOTMPDIR=
set GOTOOLDIR=C:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\dev\dliver-webrtc-server\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADAM~1.KIS\AppData\Local\Temp\go-build216719358=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

<pre>
$ go mod vendor
</pre>

### What did you expect to see?

successfully creating vendor directory with dependencies

### What did you see instead?

<pre>
go mod vendor: open C:\AUTHORS: Access is denied.
</pre>

**Comment by thepudds** [comment]
@masterada A quick test just now did not reproduce this using go1.12.4.

Do you happen to have a public repository where this is reproducible?

Alternatively, would you be able to supply a more complete set of steps to reproduce from scratch?  For example, if you start with `go mod init testmod` and then create a simple `main.go` with some statements like ` import _ "github.com/some/repo"` or similar, are you able to reproduce this problem?

**Comment by masterada** [comment]
Seems like the issue only appeary if GOPATH is a direct child of GOROOT, eg:
```
GOROOT="C:\go"
GOPATH="C:\go\workspace"
```

Any other setup (`GOPATH="C:\workspace"`, `GOPATH="C:\go\test\workspace"`) did not reproduce the bug. Here is a project for reproducing it: https://github.com/masterada/go-mod-vendor-test

Not sure if it's reproducible on other OS.

I can live with moving my GOPATH, altough it's a bit painful.

**Comment by alexbrainman** [comment]
> Seems like the issue only appeary if GOPATH is a direct child of GOROOT

I am pretty sure that is not supported.

Mind you, the error message of

> go mod vendor: open C:\AUTHORS: Access is denied.

is not very helpful.

Alex

**Comment by agnivade** [comment]
@masterada - Putting GOPATH under GOROOT is definitely something not recommended as is evident from here - https://golang.org/doc/code.html#GOPATH.

I would request you to move GOPATH to somewhere else.

Is there anything else you want to be done in this issue ?

**Comment by masterada** [comment]
I have long moved GOPATH since then, and it works fine. A better error message would be helpful, but otherwise it's working as expected.

**Comment by agnivade** [comment]
Thanks. Please feel free to open a separate issue for the error message. I will close this.
