### ISSUE TITLE
x/tools/go/packages: support packages entirely defined in overlays

### ISSUE THREAD

**Issue by stamblerre** [golang/go#31522]
From comments on https://golang.org/cl/172409:

"I think in the long run we are either going to have to have some complicated logic to associate go files with packages the same way go list would, or we are going to have to write all the overlays to a temporary directory and actually run go list on them."

**Comment by myitcv** [comment]
@stamblerre aren't we done here now?

**Comment by stamblerre** [comment]
With @matloob's changes, I believe so. Thanks for noticing this - closing now.

**Comment by matloob** [comment]
wooooooh!~
