### ISSUE TITLE
x/sys/unix: missing Linux system call name_to_handle_at

### ISSUE THREAD

**Issue by bradfitz** [golang/go#31521]
I needed to call the Linux `name_to_handle_at` (SYS_NAME_TO_HANDLE_AT = 303) system call for a test but it's not in x/sys/unix.

Likewise, looks like we need a type for `struct file_handle *`.

@tklauser, interested in adding? :)

**Comment by bradfitz** [comment]
Actually, the C struct isn't very mappable to Go types:

```c
           struct file_handle {      
               unsigned int  handle_bytes;   /* Size of f_handle [in, out] */ 
               int           handle_type;    /* Handle type [out] */
               unsigned char f_handle[0];    /* File identifier (sized by    
                                                caller) [out] */
           };
```

So we'd likely need some higher-level Go wrapper around the system calls that dealt with the unsafety of making such a struct for the kernel.

**Comment by cuonglm** [comment]
@bradfitz duplicate of https://github.com/golang/go/issues/30537

**Comment by bradfitz** [comment]
@cuonglm, whoops, thanks.
