### ISSUE TITLE
runtime: support 2^31+ goroutines?

### ISSUE THREAD

**Issue by xiazemin** [golang/go#31531]
we'd need to have 2^31+ goroutines, but ,if goroutines are generated and exited frequently. The ticket maybe not enough. and the variable 'wait' and 'notify' maybe negitive, is that right?

https://github.com/golang/go/blob/cbaa8e5f93a9571c30271c0f6d7c874793ec49ce/src/runtime/sema.go#L457

**Comment by ianlancetaylor** [comment]
Are you reporting a bug?  If you just want to discuss the code, golang-nuts is a better place.  See https://golang.org/wiki/Questions .

**Comment by crvv** [comment]
I think the question is clearly answered by the comment in the posted link.
