### ISSUE TITLE
cmd/go: spurious error message when external linking a pure Go program

### ISSUE THREAD

**Issue by cherrymui** [golang/go#31544]
### What version of Go are you using (`go version`)?

tip (3235f7c0720338a160debe6e9c632b8af968b4dd)

### Does this issue reproduce with the latest release?

Yes, happens with Go 1.11, 1.12, and tip, but not with Go 1.10.

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

### What did you do?

```
$ mkdir -p /tmp/src/hello
$ cat >hello.go
package main
func main() { println("hello") }
$ GO111MODULE=off GOPATH=/tmp go build -ldflags=-linkmode=external
# hello
loadinternal: cannot find runtime/cgo
$ echo $?
0
$ ./hello
hello
```

When using external linking for a pure Go program, the linker prints `loadinternal: cannot find runtime/cgo` message. The linking actually succeeded, and the generated binary works fine.

### What did you expect to see?
No error message, like with Go 1.10.
```
$ GOPATH=/tmp go1.10 build -ldflags=-linkmode=external 
$ ./hello 
hello
```

### What did you see instead?
Spurious `loadinternal: cannot find runtime/cgo` error message.

**Comment by cherrymui** [comment]
This also happens in module mode:
```
$ go mod init hello
go: creating new go.mod: module hello
$ GO111MODULE=on go build -ldflags=-linkmode=external 
# hello
loadinternal: cannot find runtime/cgo
```

But it does not happen if the file name (hello.go) is given explicitly.
```
$ go build -ldflags=-linkmode=external hello.go 
$
```

**Comment by bcmills** [comment]
I can reproduce the failure. I'm bisecting it now to try to get some idea of how it broke.

**Comment by bcmills** [comment]
`git bisect` points to [CL 129059](https://golang.org/cl/129059).

**Comment by bcmills** [comment]
This is a result of the `-ldflags=-linkmode=external` flag now (correctly) being passed when compiling the `hello` package, which reveals a typestate bug in `load.PackagesAndErrors`.

The decision in the `LinkerDeps` function about whether to add the `runtime/cgo` dependency is based on whether the `CmdlinePkg` flag is set:
https://github.com/golang/go/blob/19966e9b533a85039458eabf08228e0b85f3bf4e/src/cmd/go/internal/load/flag.go#L43

That field is set *after* the call to `loadImport`:
https://github.com/golang/go/blob/19966e9b533a85039458eabf08228e0b85f3bf4e/src/cmd/go/internal/load/pkg.go#L1962-L1964

However, by that point `loadImport` has already called `load` on the package:
https://github.com/golang/go/blob/19966e9b533a85039458eabf08228e0b85f3bf4e/src/cmd/go/internal/load/pkg.go#L511

...and `load` is what's supposed to figure out the implicit linker dependencies:
https://github.com/golang/go/blob/19966e9b533a85039458eabf08228e0b85f3bf4e/src/cmd/go/internal/load/pkg.go#L1534

**Comment by rsc** [comment]
@cherrymui, unless this is important for you for some reason, we'd like to postpone the fix to Go 1.14. It's subtle code.

/cc @bcmills

**Comment by cherrymui** [comment]
> @cherrymui, unless this is important for you for some reason, we'd like to postpone the fix to Go 1.14. It's subtle code.

Sure, it is fine to postpone.

**Comment by michael-obermueller** [comment]
We would like to propose to reconsider the priority fixing this issue. The implication of it is, that such Go binaries have no `runtime/cgo` dependency which means they do not create threads using `pthread_create` but instead the `clone` system call.

Preloaded (LD_PRELOAD) shared objects may rely on the fact that Go creates POSIX threads.

**Comment by ianlancetaylor** [comment]
I certainly think this should be fixed, but I'm not following the concern with LD_PRELOAD shared objects.  I don't see how it would be possible to use an LD_PRELOAD with a pure Go program.

**Comment by Hollerberg** [comment]
@ianlancetaylor: The scenario is very specific, but has a serious impact on existing applications.

A shared object of our (application performance monitoring) product is pre-loaded into Go processes to hook certain Go functions. Customers use `-ldflags=-linkmode=external` in some cases to enforce dynamically built applications. 

As the issue causes `iscgo` set to `false`, Go runtime will create threads with `clone` and not with `pthread_create`. Thus, pre-loaded C code executed in Go runtime thread context (invoked from hooked Go functions) will crash the application accessing e.g. TLS.

**Comment by ianlancetaylor** [comment]
OK, that seems not only specific but completely unsupported.

Again, I think this bug should be fixed, but the Go team can't take any responsibility for keeping that kind of pre-loaded library working.
