### ISSUE TITLE
cmd/compile: allows assigning to blank identifier in struct

### ISSUE THREAD

**Issue by bradfitz** [golang/go#31546]
https://play.golang.org/p/WMC4t5oiRR-
```go
package main

import (
	"fmt"
	"reflect"
)

var x = struct{ a, _, c int }{1, 2, 3}

func main() {
	var y = struct{ a, _, c int }{1, 2, 3}
	fmt.Println(x)
	fmt.Println(y)
	fmt.Println(reflect.ValueOf(x).Field(1).Int())
	fmt.Println(reflect.ValueOf(y).Field(1).Int())
	fmt.Println(x == y)
}
```

Currently (Go 1.12, master) says:

```
{1 2 3}
{1 0 3}
2
0
true
```

The `x == y` part returning `true` is defined by the spec, but `x` and `y` getting a different value for the blank identifier is... weird. I see nothing in the spec that addresses this directly but if squint I might be able to connect some different parts and make guesses as to intent.

But Go 1.4 - Go 1.8 fail to compile with:

```
./x.go:11: cannot refer to blank field or method
```

Go 1.9 is the first version where the program above compiles and returns that result.

/cc @ianlancetaylor @griesemer @josharian @cherrymui @randall77 @davecheney

**Comment by cuonglm** [comment]
it seems to be a regression of https://go-review.googlesource.com/c/go/+/38006/

**Comment by josharian** [comment]
@cuonglm the discussion in https://github.com/golang/go/issues/19482 (which that CL fixes) indicates that the previous behavior is wrong. But maybe I'm misinterpreting what the "it" is that was the regression.

There are some possibly related cases in https://github.com/golang/go/issues/15481.

> x and y getting a different value for the blank identifier is... weird.

This seems to be the crux of the issue. I think we need to start with some clarity about the correct behavior is here. (Or whether it is ok for the value of the blank field to be implementation dependent.)

**Comment by jimmyfrasche** [comment]
If you told me one was legal and asked me what I expect to happen without looking at the spec or testing it in the playground, I would say `y` by analogy with
```
var a, _, c int = 1, 2, 3
```
which is effectively equivalent to
```
var a, c = 1, 3
```

But I also think that https://play.golang.org/p/Qzcyybi8ZUV should print 0 by the same logic, so maybe I'm not the best person to ask :smile:

**Comment by rsc** [comment]
The reason there's any assignment allowed at all is for:

   type T struct {x, _, z int} 
   var t1, t2 T
   t1 = t2

where the _ is padding.

The literal assignment fell out from changing the rules to allow the whole-struct assignment but was probably a mistake. If we had it to do over again, we could probably disallow:

    var x = struct{ a, _, c int }{1, 2, 3}

But we don't have it to do over again, and it is silly to insist on writing the _ field, so it seems like we must insist on not writing it during the literal. So the global is the wrong behavior that needs fixing.

**Comment by josharian** [comment]
Working on a fix.
