### ISSUE TITLE
runtime: dynamically adjust initial stack size according to workload

### ISSUE THREAD

**Issue by valyala** [golang/go#31558]
### The issue

Typical server written in go has the following loop ([net/http.Server has similar loop](https://github.com/golang/go/blob/master/src/net/http/server.go#L2911)):
```go
for {
    conn := listener.Accept()
    go serveConn(conn)
}
```

or

```go
for {
    req := getRequest()
    go serveRequest(req)
}
```

This code starts new goroutine for serving each incoming connection or request. Go runtime starts new goroutines with small initial stack sizes (2KB). This stack may grow if `serveConn` or `serveRequest` calls many nested functions. This results in unnecessary CPU time spent in `newStack` calls for each incoming connection or request. See [this article from Uber engineers](https://eng.uber.com/optimizing-m3/) for details.

### The solution

Create new goroutines with dynamic initial stack sizes according to stack size stats from recently exited goroutines. This will eliminate `newStack` calls in typical server code, including `net/http.Server`.

### The workaround I don't like

To serve connections / requests via goroutine pool. See [this article](https://eng.uber.com/optimizing-m3/) for details.

cc'ing @josharian and @aclements

**Comment by randall77** [comment]
Dup of #18138
