### ISSUE TITLE
runtime/trace: running out of memory on plan9/amd64 builder

### ISSUE THREAD

**Issue by 0intro** [golang/go#31554]
Since 2019-03-06 approximately, the runtime/trace test is running out of memory on the plan9/amd64 builder.

**Comment by bradfitz** [comment]
Why's it use so much memory?

How much memory does the machine have?

**Comment by 0intro** [comment]
The machine has 2048 MB memory. 1822 MB are available from user space. The TestTraceStress and TestTraceStressStartStop tests are using all available memory.
