### ISSUE TITLE
x/tools/internal/lsp: don't complete in unterminated string literals

### ISSUE THREAD

**Issue by muirrn** [golang/go#31557]
Similar to comments, I don't think it is useful to complete within string literals:

```
var fooBarBaz int
fmt.Println("foo<>
```
I'm not certain it is easy to detect this case, though, since it is a syntax error.

Alternatively, we could try to complete based on words in other nearby string literals, but I don't imagine that would end up being too useful, and might be outside the purview of a Go language server.

**Comment by muirrn** [comment]
I now see this is only an issue for unterminated string literals. Updated title.

**Comment by stamblerre** [comment]
It's not possible to add a test for this in the context of the packagestest framework (can't put a marker after an unterminated string literal), but I believe this issue was fixed by https://golang.org/cl/173518. Please reopen if I am mistaken.
