### ISSUE TITLE
cmd/go/internal/modfetch: document known bug in `isVendoredPackage`

### ISSUE THREAD

**Issue by haamed** [golang/go#31562]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.12.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/home/gheibi/.go/bin/"
GOCACHE="/home/gheibi/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/gheibi/.go/"
GOPROXY=""
GORACE=""
GOROOT="/local/go1.12.1.linux_amd64/go"
GOTMPDIR=""
GOTOOLDIR="/local/go1.12.1.linux_amd64/go                                                                                     /pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build865790926=/tmp/go-build"

</pre></details>

### What did you do?

```
$grep -A12 "func isVendoredPackage" $GOROOT/src/cmd/go/internal/modfetch/coderepo.go
```
https://github.com/golang/go/blob/c8aaec2f70c5ccbca1ec2152c57d19981ac09133/src/cmd/go/internal/modfetch/coderepo.go#L632-L642

### What did you expect to see?
```
func isVendoredPackage(name string) bool {
	var i int
	if strings.HasPrefix(name, "vendor/") {
		i += len("vendor/")
	} else if j := strings.Index(name, "/vendor/"); j >= 0 {
		i += j + len("/vendor/")
	} else {
		return false
	}
	return strings.Contains(name[i:], "/")
}
```
### What did you see instead?
The function is not documented, but it is obvious that it is not doing what the intention is.
It seems that the intention is to match against this regex: `(^vendor/|/vendor/).*/`
But in fact it does random match by skipping first 8 bytes in case the input contains `/vendor/`.
The fix is to add the j to the i as states above.

It is quite important to fix it early on, because it may cause go-modules with different hashes and a late fix can cause more hash mismatch of the same content (defy the immutability logic).

**Comment by agnivade** [comment]
@bcmills @jayconrod

**Comment by bcmills** [comment]
That sure looks like a bug — it should probably be `i = j + len("/vendor/")`.

Unfortunately, at this point we can't safely make _any_ changes to the extracted contents of modules; see #30369 and #29278.

**Comment by bcmills** [comment]
At least the failure mode here is fairly benign: we know that `len(name)` is at least `len("/vendor/")`, so we might not chop off enough of the path, but we won't panic, and it won't cause a spurious `true` return for packages that aren't actually vendored.

So the net effect is that we'll include some packages that aren't strictly necessary, but fail to prune some contents that really aren't needed.

**Comment by bcmills** [comment]
As @rsc put it in https://github.com/golang/go/issues/30369#issuecomment-467457743:
“Now the algorithm is the algorithm. Let's leave it there. Any bugs that remain are now features.”

Since this error won't break builds (it includes packages that should be excluded, but does not exclude packages that should be included), it doesn't seem worth the churn of fixing at this time. We can revisit if we discover more severe bugs that are worth breaking the hash function over; for now, we should just document the known issue in the code.

**Comment by matloob** [comment]
@samthanawalla I think post-1.21 we can now fix this, but only on modules declaring a new enough version of go.

**Comment by dmitshur** [comment]
This issue from 2019 was resolved and frozen due to age. For new work, maybe it'd be better to file a new issue and refer to this one.

**Comment by matloob** [comment]
Oops! Closing
