### ISSUE TITLE
cmd/compile: cut dependency on go/build

### ISSUE THREAD

**Issue by josharian** [golang/go#31563]
```go
// cmd/compile/internal/gc/main.go
func currentLang() string {
	tags := build.Default.ReleaseTags
	return tags[len(tags)-1]
}
```

This function causes cmd/compile to depend on go/build, which accounts for 1.6mb (6.5%) of the cmd/compile binary.

It'd be nice to cut this dependency. Perhaps an internal package containing the release tags? Or duplicating the release tag info in two places?

Easy to fix once we decide what path to take forward.

cc @ianlancetaylor @bradfitz

**Comment by bradfitz** [comment]
Seems good to me. I sent CL 172997 if others don't object.
