### ISSUE TITLE
cmd/go: go install documentation is lacking; effect of $GOBIN underdocumented

### ISSUE THREAD

**Issue by griesemer** [golang/go#31576]
It's been a while since I had to fiddle with my dev setup but I recently created a new separate go repo in my home directory and it took me a while to untangle where which binaries got installed. Specifically when it comes to uses of `$GOBIN` for which the [documentation](https://golang.org/doc/install/source#environment) is a bit vague. It says that if `$GOBIN` is set, the `go` command installs **all** commands there. Well, that's not what I am observing.

I have no Go specific environment variables set but for `GOPATH` which is set to `$HOME`. So no `GOBIN`, or `GOROOT` per the usual recommendation.

In a brand-new local repo of the Go distribution, after running `make.bash`, the two tools `go` and `gofmt` are built and installed in `$GOROOT/bin` where `$GOROOT` is the repo directory (per documentation). It doesn't matter if `$GOBIN` is set or not.

`go install` of a new "command", that is a main package under `$GOROOT/src/cmd`, appears to be installed in `$GOTOOLDIR` no matter if `$GOBIN` is set or not. `$GOTOOLDIR` is `$GOROOT/pkg/tool/GOOS_$GOARCH`.

Only for binaries (main packages) outside `$GOROOTsrc/cmd` does `$GOBIN` apply: Those end up in `$GOBIN` if it set, or in `GOROOT/bin` if `$GOBIN` is not set.

(This is all based in empirical evidence, I haven't studied the code. Happy to be corrected if I got this wrong.)

The documentation should be more clear. Right now we have lists of environment variables and respective documentation which is referred to from various places but it's not consistent.

More generally, it would be useful to document the recommended basic dev setup for people who want to work on the std lib. Specifically, where what is installed. Note that `go help install` doesn't say anything about what "install" actually means or where things go. It refers to `go help build` and `go help packages` which only makes things complicated.

cc: @bcmills

**Comment by gertcuykens** [comment]
Hmm is it possible to do it the other way around. So let's try to keep the consistency and do what the documentation suggest instead of modifying the doc. So $GOBIN is always king: go modules or go path or goroot stuff doesn't matter, always put it in $GOBIN. I understand it will break a lot of things but nothing I think where make files and build scripts can adapt to by modifying $GOBIN on the fly?

**Comment by griesemer** [comment]
@gertcuykens I doubt that we can change the existing behavior w/o breaking a large number of people's setups. Updating the documentation is probably the way to go. But leaving this to the people responsible for the current behavior.

cc: @rsc
