### ISSUE TITLE
cmd/go: go run . uses wrong executable name

### ISSUE THREAD

**Issue by rsc** [golang/go#31571]
If I am in a directory x/y/z (in module mode, but maybe in GOPATH too)
such that the import path of that directory is m/x/y/z, and there is
a single file foo.go in the directory, and I run `go run .`, the name of
the binary that is built and run should be `z`. Right now it is `foo`.
This matters because it shows up in `ps`, etc.

**Comment by Liberatys** [comment]
Is someone handling this issue ? I think I found the code that is setting the "wrong" name for the temporary executable and would like to tackle it ?
