### ISSUE TITLE
x/tools/gopls: share cache between views

### ISSUE THREAD

**Issue by stamblerre** [golang/go#31589]
Context: https://github.com/Microsoft/vscode-go/issues/2450

**Comment by ianthehat** [comment]
I was looking at this the other day, in the context of wanting to improve the client server support, mostly for command line usage.
The trouble is that you end up needing some very complicated garbage collection like logic to evict things that are not needed from the cache, and you also want it to be lazy not precise, as closing a view and then immediately making a new view that wants the same information becomes a common pattern.
This means it is going to take a well thought out design.

**Comment by stamblerre** [comment]
I think this can be closed as of CL 198317.
