### ISSUE TITLE
cmd/compile: prevent interface conversion panic at compile time

### ISSUE THREAD

**Issue by gertcuykens** [golang/go#31585]
I think the compiler at compile time should stop building to prevent this panic at runtime ?

https://play.golang.org/p/ffP9vSHdHof

```
package main

import (
	"fmt"
)

type Test4 interface {
	test(string) string
}

type Test2 interface {
	test(string) string
}

type Test1 func(string) string

func (t Test1) test(str string) string {
	return t(str)
}

type Test3 func(string) string

func (t Test3) test(str string) string {
	return t(str)
}

func main() {
	test1 := Test1(func(str string) string {
		return str + " world"
	})
	fmt.Println(test1.test("hello"))

	test2 := Test2(test1)
	fmt.Println(test2.test("hello"))

	test3 := test2.(Test2)
	fmt.Println(test3.test("hello"))

	test4 := test3.(Test4)
	fmt.Println(test4.test("hello"))

	test5 := test4.(Test4)
	fmt.Println(test5.test("hello"))

	test6 := test4.(Test2)
	fmt.Println(test6.test("hello"))

	test7 := test4.(Test1)
	fmt.Println(test7.test("hello"))

	test8 := test4.(Test3)
	fmt.Println(test8.test("hello"))
}
```
panic: interface conversion: main.Test4 is main.Test1, not main.Test3

**Comment by go101** [comment]
It is a panic at run time, not compile time. The output clearly states the reason: the dynamic type of `test4` in `main.Test1`, not `main.Test3`. 

A failed type assertion without the second optional result will panic. You can write the last assertion as the following to avoid panic.
```golang
	test8, _ := test4.(Test3) // present the second optional result
	if test8 != nil {
		fmt.Println(test8.test("hello"))
	}
```

**Comment by gertcuykens** [comment]
Thanks, but what I ment was that I think the compiler should pic it up and prevent it from running / building in the first place. So what I mean is, it should be a compile error instead of a runtime error

**Comment by randall77** [comment]
The spec requires that this code compile successfully. We'd have to adjust the spec in order to do what you suggest, which is a very high bar.
We could possibly add a check to vet, but generally we don't do so when the runtime error is obvious. It's more commonly used to detect at compile time something that would be hard to debug at runtime.

If you want to move forward with a vet strategy, we'd need to know what such a detector would look like. How would the analysis happen? What would be the error rate (both positive and negative)? Are there actual instances of this bug in the wild?

**Comment by gertcuykens** [comment]
`go vet` is also fine for this. I think it's in the same category as the  `a = append(b, 2, 3, 4)` gotcha bug but arguably less common. Maybe this is not so important. As for analysing interfaces I think first step would be listing all interfaces of a program by line snipit. It would be a nice overview of your go program I think. `go vet interfaces` which can then also be used to highlight interfaces in ide's like https://github.com/Microsoft/vscode-go/issues/486 Second step would be to figure out if the a cast make sense.

**Comment by beoran** [comment]
I think the gopls tool which is currently being developed here will do what you want.

**Comment by gertcuykens** [comment]
As far as I can tell `gopls` doesn't do that by design https://microsoft.github.io/language-server-protocol/specification you going to need `go vet` always for detecting stuff like shadow variables and specific golang things like interfaces. LSP only fits generic program language things like defenition look up etc.

**Comment by stamblerre** [comment]
`gopls` includes `go vet` checks as part of [textDocument/publishDiagnostics](https://microsoft.github.io/language-server-protocol/specification#textDocument_publishDiagnostics) (see https://github.com/golang/tools/blob/master/internal/lsp/source/diagnostics.go).

**Comment by gertcuykens** [comment]
ok so the best place to implement a list of all interfaces to begin with is still go vet right? Maybe step two to compare it with other types to see if a cast makes sense could be implemented in gopls directly then. But step one is still a grouped by interface list of all interfaces variables (`go vet interfaces`) and it associated code line so you can follow the life of each interface in your progamer like for this example something like 

```
line:xx type Test4 interface{}
line: xx test4 := test3.(Test4)
line: xx test5 := test4.(Test4)
line: xx test6 := test4.(Test2)

line:xx type Test2 interface{}
...
```

**Comment by odeke-em** [comment]
Thank you @gertcuykens for filing this issue and everyone for chiming in. As @go101 and @randall77 have mentioned, this in deed is a runtime error and we can't change this, but as @beoran and @stamblerre have noted, you can add vet rules for such.

I shall also kindly cc @johanbrandhorst @dominikh who might be interested in these vet rules, but for now I shall close this issue. Please feel free to reopen if I've missed something.
