### ISSUE TITLE
unicode/utf8: document specification

### ISSUE THREAD

**Issue by dsnet** [golang/go#31590]
The `utf8` package merely documents that it "supports text encoded in UTF-8", but doesn't point to any external sources for what "UTF-8" exactly is. I'm not an expert in this area, but my understanding is that UTF-8 is formally defined in [RFC 3629](https://tools.ietf.org/html/rfc3629). Is that true?

Furthermore, does the `Valid` function implement validation for merely the syntax of UTF-8 encoding ([section 4](https://tools.ietf.org/html/rfc3629#section-4)) or a validation of the "definition" of UTF-8 ([section 3](https://tools.ietf.org/html/rfc3629#section-3))? The code seems to suggest that it is the later. The godoc does not make this clear to me and probably should  be documented.

**Comment by rsc** [comment]
I'm sure we can find the right chapter of the Unicode spec and link to that (unicode.org).
https://www.unicode.org/versions/Unicode12.0.0/UnicodeStandard-12.0.pdf#page=65
