### ISSUE TITLE
cmd/cgo: program got a SIGBUS signal

### ISSUE THREAD

**Issue by duanbing** [golang/go#31593]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes, go version go1.12.4 darwin/amd64 is the latest version I can download.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/duanbing/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/duanbing/Project/Go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/xxxxx/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/35/1f0_9bnn0dvc0mdr0kv8dy08cm5r19/T/go-build681850907=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I write a cgo program, and use go test to run the unit test.
but if I set GOGC=off,  go test run as I expect.

### What did you expect to see?

tests finished without crash when GOGC=on.

### What did you see instead?

I got SIGBUS signal if I just run ```go test```.

**Comment by ALTree** [comment]
Thanks for the report.

It's possible that this is caused by issues with the cgo part of your program. It's possible that the bug is in the C code of your program, and not in the Go runtime.

Can you provide a (possibly small) reproducer? Otherwise it won't be possible to investigate this.

**Comment by 40345839668** [comment]
You can find all the information in the link below.
https://gist.github.com/40345839668/31e75de1a47233faa00d7dc33aaac0fd

**Comment by duanbing** [comment]
Thanks, @ALTree .  the codes are too large, so I didn't post it here.  I will mimic a simple one to reproduce it. BTW, can you give me some tips about what kinda scenario  I will get this error?

**Comment by duanbing** [comment]
this is the associated issue, https://github.com/WAVM/WAVM/issues/151 , its maybe helpful.

**Comment by duanbing** [comment]
@ALTree  https://github.com/WAVM/WAVM/blob/master/Lib/Platform/POSIX/Thread.cpp#L148 is the source of SIGBUS.

**Comment by ALTree** [comment]
@duanbing Thanks for the investigation. 

Unfortunately, as I wrote above, this kind of crashes are often caused by issues in the C code, so I'm afraid this issue won't be actionable from the Go project's side unless you're able to to reduce your large code into a smaller reproducer.

I'll leave this open with a `WaitingForInfo` label, so feel free to post updates here.

**Comment by duanbing** [comment]
I fixed it by allocating the memory in mmapped seactions, not in current stack. 

Thanks all!
