### ISSUE TITLE
net/http: behavior error when request doesn't have HOST header

### ISSUE THREAD

**Issue by Zheaoli** [golang/go#31598]
Host header may not exist when some of the HTTP library make a request.

https://github.com/golang/go/blob/master/src/net/http/server.go#L982

In net/http, the default code forbade this request.

I think maybe raise warning info is a better idea than this.

**Comment by davecheney** [comment]
HTTP/1.1 mandates the Host header MUST (RFC2119) be present.

Which HTTP libraries are sending malformed requests?
