### ISSUE TITLE
gomod can't debug on VS code

### ISSUE THREAD

**Issue by YuanDdQiao** [golang/go#31607]
i'm git clone  https://github.com/pingcap/dm 
 and  run "start debugging" on vs code IDE ,
it's does't work and raised "undefined: unix.Statfs_t"
but i'm checked "F:\source-tree\pkg\mod\golang.org/x/sys/unix"  ,it's exists .

what can i do for debugging on module

F:\gomodworkspace\dm>go env
set GOARCH=amd64
set GOBIN=F:\source-tree\bin
set GOCACHE=C:\Users\admin pc\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=F:\source-tree
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=F:\gomodworkspace\dm\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINP~1\AppData\Local\Temp\go-build820054998=/tmp/go-build -gno-record-gcc-switches

F:\gomodworkspace\dm>

**Comment by agnivade** [comment]
Statfs_t is a linux type. You are in windows. I guess you are not setting the appropriate GOOS/GOARCH variables.

If you are indeed setting those, please report back with the exact set of steps for us to reproduce this issue which does not require to run VS code as we would want the issue to be with the Go language and not VS Code. Thanks

**Comment by YuanDdQiao** [comment]
thinks ,i got it.
