### ISSUE TITLE
unable to use my gcc 8.1 with go1.12? linux armhf

### ISSUE THREAD

**Issue by Askmewho** [golang/go#31606]
Hi, ive tried compiling go 1.12.4 and downloading precompiled binaries from debian of the same version. the problem its than i get a lot of "cannot use _cgo0" when on "go env"

pi@pi:~/Desktop/Ikemen_GO $ go version
go version go1.12.4 linux/arm

pi@pi:~/Desktop/Ikemen_GO $ go env
GOARCH="arm"
GOBIN=""
GOCACHE="/home/pi/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pi/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.12"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.12/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build574726848=/tmp/go-build -gno-record-gcc-switches"

pi@pi:~/Desktop/Ikemen_GO $ gcc --version
gcc (GCC) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
Esto es software libre; vea el código para las condiciones de copia.  NO hay
garantía; ni siquiera para MERCANTIBILIDAD o IDONEIDAD PARA UN PROPÓSITO EN
PARTICULAR

pi@pi:~/Desktop/Ikemen_GO $ g++ --version
g++ (GCC) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
Esto es software libre; vea el código para las condiciones de copia.  NO hay
garantía; ni siquiera para MERCANTIBILIDAD o IDONEIDAD PARA UN PROPÓSITO EN
PARTICULAR
}

maybe i should add something more on /home/pi/.bashrc?
I add the following to execute go because the deb package (not from the raspbian repo) didn't do that.
export PATH=/usr/lib/go-1.12/bin:$PATH

**Comment by ianlancetaylor** [comment]
What exactly did you do?  What exactly happened?

If you are explicitly setting `GOARCH` or `GOOS` in the environment, and you have an appropriate cross-compiler in `CC`, then the problem may be that you need to set `CGO_ENABLED=1`.

**Comment by Askmewho** [comment]
this its the build script. 
`#!/bin/sh
export GOPATH=$PWD/go
export CGO_ENABLED=1
if [ -n "$OS" ];    then 
    case "$OS" in
    "windows")
        export GOOS=windows
        export CC=x86_64-w64-mingw32-gcc
        export CXX=x86_64-w64-mingw32-g++
        BINARY_NAME="Ikemen_GO.exe"; 

        ;;
    "mac") 
        export GOOS=darwin
        export CC=o64-clang 
        export CXX=o64-clang++
        BINARY_NAME="Ikemen_GO_mac"; 

        ;;
    "linux") 
        BINARY_NAME="Ikemen_GO_linux"; 
        ;;
    esac 
else 
    BINARY_NAME="Ikemen_GO";  
fi;

go get -u github.com/yuin/gopher-lua
go get -u github.com/go-gl/glfw/v3.2/glfw
go get -u github.com/go-gl/gl/v2.1/gl
go get -u github.com/timshannon/go-openal/openal
go get -u github.com/K4thos/glfont
go get -u github.com/flopp/go-findfont
go get -u github.com/faiface/beep
go get -u github.com/hajimehoshi/oto
go get -u github.com/hajimehoshi/go-mp3
go get -u github.com/pkg/errors
go get -u github.com/jfreymuth/oggvorbis
go get -u github.com/mewkiz/flac
`
for some reason, on the repo version 1.7 it runs ok and on my new version dont.
you see than CGO its enabled.

crash log 
`pi@pi:~/Desktop/Ikemen_GO $ ./get.sh
# github.com/timshannon/go-openal/openal
go/src/github.com/timshannon/go-openal/openal/alcCore.go:86:144: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcGetError
go/src/github.com/timshannon/go-openal/openal/alcCore.go:125:95: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCloseDevice
go/src/github.com/timshannon/go-openal/openal/alcCore.go:131:102: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCreateContext
go/src/github.com/timshannon/go-openal/openal/alcCore.go:137:110: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_walcGetIntegerv
go/src/github.com/timshannon/go-openal/openal/alcCore.go:142:151: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_walcGetInteger
go/src/github.com/timshannon/go-openal/openal/alcCore.go:163:109: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureCloseDevice
go/src/github.com/timshannon/go-openal/openal/alcCore.go:171:83: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureStart
go/src/github.com/timshannon/go-openal/openal/alcCore.go:175:81: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureStop
go/src/github.com/timshannon/go-openal/openal/alcCore.go:179:179: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureSamples
go/src/github.com/timshannon/go-openal/openal/alcCore.go:183:179: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureSamples
go/src/github.com/timshannon/go-openal/openal/alcCore.go:183:179: too many errors
`

**Comment by Askmewho** [comment]
Now, with my compiled golang go (and purged any other golang go version) and with these adjustments on .bashrc
´´´
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin
´´´

but..

´´´
pi@pi:~/Desktop/Ikemen_GO $ go env
GOARCH="arm"
GOBIN=""
GOCACHE="/home/pi/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pi/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="7"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build429821255=/tmp/go-build -gno-record-gcc-switches"
pi@pi:~/Desktop/Ikemen_GO $ ./get.sh 
package bufio: unrecognized import path "bufio" (import path does not begin with hostname)
package context: unrecognized import path "context" (import path does not begin with hostname)
package errors: unrecognized import path "errors" (import path does not begin with hostname)
package fmt: unrecognized import path "fmt" (import path does not begin with hostname)
package bytes: unrecognized import path "bytes" (import path does not begin with hostname)
package io: unrecognized import path "io" (import path does not begin with hostname)
package reflect: unrecognized import path "reflect" (import path does not begin with hostname)
package strconv: unrecognized import path "strconv" (import path does not begin with hostname)
package strings: unrecognized import path "strings" (import path does not begin with hostname)
package io/ioutil: unrecognized import path "io/ioutil" (import path does not begin with hostname)
package math: unrecognized import path "math" (import path does not begin with hostname)
package math/rand: unrecognized import path "math/rand" (import path does not begin with hostname)
package os: unrecognized import path "os" (import path does not begin with hostname)
package os/exec: unrecognized import path "os/exec" (import path does not begin with hostname)
package path/filepath: unrecognized import path "path/filepath" (import path does not begin with hostname)
package runtime: unrecognized import path "runtime" (import path does not begin with hostname)
package sort: unrecognized import path "sort" (import path does not begin with hostname)
package sync/atomic: unrecognized import path "sync/atomic" (import path does not begin with hostname)
package syscall: unrecognized import path "syscall" (import path does not begin with hostname)
package time: unrecognized import path "time" (import path does not begin with hostname)
package unsafe: unrecognized import path "unsafe" (import path does not begin with hostname)
package fmt: unrecognized import path "fmt" (import path does not begin with hostname)
package image: unrecognized import path "image" (import path does not begin with hostname)
package image/draw: unrecognized import path "image/draw" (import path does not begin with hostname)
package log: unrecognized import path "log" (import path does not begin with hostname)
package reflect: unrecognized import path "reflect" (import path does not begin with hostname)
package sync: unrecognized import path "sync" (import path does not begin with hostname)
package unsafe: unrecognized import path "unsafe" (import path does not begin with hostname)
package errors: unrecognized import path "errors" (import path does not begin with hostname)
package fmt: unrecognized import path "fmt" (import path does not begin with hostname)
package reflect: unrecognized import path "reflect" (import path does not begin with hostname)
package strings: unrecognized import path "strings" (import path does not begin with hostname)
package unsafe: unrecognized import path "unsafe" (import path does not begin with hostname)
package errors: unrecognized import path "errors" (import path does not begin with hostname)
package fmt: unrecognized import path "fmt" (import path does not begin with hostname)
package strings: unrecognized import path "strings" (import path does not begin with hostname)
package unsafe: unrecognized import path "unsafe" (import path does not begin with hostname)
package fmt: unrecognized import path "fmt" (import path does not begin with hostname)
package errors: unrecognized import path "errors" (import path does not begin with hostname)
package reflect: unrecognized import path "reflect" (import path does not begin with hostname)
package strings: unrecognized import path "strings" (import path does not begin with hostname)
package unsafe: unrecognized import path "unsafe" (import path does not begin with hostname)
package image: unrecognized import path "image" (import path does not begin with hostname)
package image/color: unrecognized import path "image/color" (import path does not begin with hostname)
package image/draw: unrecognized import path "image/draw" (import path does not begin with hostname)
package math: unrecognized import path "math" (import path does not begin with hostname)
package strconv: unrecognized import path "strconv" (import path does not begin with hostname)
package io: unrecognized import path "io" (import path does not begin with hostname)
package unicode/utf8: unrecognized import path "unicode/utf8" (import path does not begin with hostname)
package io/ioutil: unrecognized import path "io/ioutil" (import path does not begin with hostname)
package os: unrecognized import path "os" (import path does not begin with hostname)
package fmt: unrecognized import path "fmt" (import path does not begin with hostname)
package os: unrecognized import path "os" (import path does not begin with hostname)
package os/user: unrecognized import path "os/user" (import path does not begin with hostname)
package path/filepath: unrecognized import path "path/filepath" (import path does not begin with hostname)
package strings: unrecognized import path "strings" (import path does not begin with hostname)
package fmt: unrecognized import path "fmt" (import path does not begin with hostname)
package math: unrecognized import path "math" (import path does not begin with hostname)
package time: unrecognized import path "time" (import path does not begin with hostname)
package errors: unrecognized import path "errors" (import path does not begin with hostname)
package fmt: unrecognized import path "fmt" (import path does not begin with hostname)
package bufio: unrecognized import path "bufio" (import path does not begin with hostname)
package io: unrecognized import path "io" (import path does not begin with hostname)
package runtime: unrecognized import path "runtime" (import path does not begin with hostname)
package sync: unrecognized import path "sync" (import path does not begin with hostname)
package time: unrecognized import path "time" (import path does not begin with hostname)
package unsafe: unrecognized import path "unsafe" (import path does not begin with hostname)
package fmt: unrecognized import path "fmt" (import path does not begin with hostname)
package io: unrecognized import path "io" (import path does not begin with hostname)
package math: unrecognized import path "math" (import path does not begin with hostname)
package fmt: unrecognized import path "fmt" (import path does not begin with hostname)
package io: unrecognized import path "io" (import path does not begin with hostname)
package path: unrecognized import path "path" (import path does not begin with hostname)
package runtime: unrecognized import path "runtime" (import path does not begin with hostname)
package strconv: unrecognized import path "strconv" (import path does not begin with hostname)
package strings: unrecognized import path "strings" (import path does not begin with hostname)
package bytes: unrecognized import path "bytes" (import path does not begin with hostname)
package encoding/binary: unrecognized import path "encoding/binary" (import path does not begin with hostname)
package errors: unrecognized import path "errors" (import path does not begin with hostname)
package math: unrecognized import path "math" (import path does not begin with hostname)
package sort: unrecognized import path "sort" (import path does not begin with hostname)
package io: unrecognized import path "io" (import path does not begin with hostname)
package bufio: unrecognized import path "bufio" (import path does not begin with hostname)
package bytes: unrecognized import path "bytes" (import path does not begin with hostname)
package crypto/md5: unrecognized import path "crypto/md5" (import path does not begin with hostname)
package encoding/binary: unrecognized import path "encoding/binary" (import path does not begin with hostname)
package fmt: unrecognized import path "fmt" (import path does not begin with hostname)
package io: unrecognized import path "io" (import path does not begin with hostname)
package errors: unrecognized import path "errors" (import path does not begin with hostname)
package hash: unrecognized import path "hash" (import path does not begin with hostname)
package runtime: unrecognized import path "runtime" (import path does not begin with hostname)
package strings: unrecognized import path "strings" (import path does not begin with hostname)
package syscall: unrecognized import path "syscall" (import path does not begin with hostname)
package unsafe: unrecognized import path "unsafe" (import path does not begin with hostname)
package path: unrecognized import path "path" (import path does not begin with hostname)
package log: unrecognized import path "log" (import path does not begin with hostname)
package io/ioutil: unrecognized import path "io/ioutil" (import path does not begin with hostname)
package os: unrecognized import path "os" (import path does not begin with hostname)
´´´

**Comment by pokeshark** [comment]
How did you solve this issue?
