### ISSUE TITLE
cmd/cgo: some type checks tightened since Go 1.12

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#31601]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +dc193dee15 Fri Apr 19 19:47:53 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Only with tip.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/elias/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/elias/go"
GOPROXY=""
GORACE=""
GOROOT="/home/elias/dev/go-tip"
GOTMPDIR=""
GOTOOLDIR="/home/elias/dev/go-tip/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build014756832=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
```
$ git clone https://git.sr.ht/~sircmpwn/go-libvterm
...
$ cd go-libvterm
$ git checkout 75984434 
...
$ go1.12.2 build
$ go build
# git.sr.ht/~sircmpwn/go-libvterm
./vterm.go:215:8: cannot use _Ctype_uchar(r) (type _Ctype_uchar) as type uint8 in assignment
./vterm.go:216:10: cannot use _Ctype_uchar(g) (type _Ctype_uchar) as type uint8 in assignment
./vterm.go:217:9: cannot use _Ctype_uchar(b) (type _Ctype_uchar) as type uint8 in assignment
```

### What did you expect to see?
No errors from the go tip build.

### What did you see instead?
An error caused by stricter C type checks.

Note that the cgo error is technically correct: the correct type of the [VTermColor fields](https://github.com/neovim/libvterm/blob/89675ffdda615ffc3f29d1c47a933f4f44183364/include/vterm.h#L151) is indeed uint8_t, not uchar. I'm filing this to make sure the tighter checks are deliberate.

**Comment by ianlancetaylor** [comment]
Same as #31093?

**Comment by eliasnaur** [comment]
Seems so.
