### ISSUE TITLE
cmd/compile: suspicious symbol generation for args_stackmap

### ISSUE THREAD

**Issue by mdempsky** [golang/go#31615]
In CL 171464, @randall77 fixed a `lookup(fmt.Sprintf(...))` call in pgen.go, but we noticed another similarly suspicious line of code for generating args_stackmap symbols. However, Keith reports that applying the same fix didn't work: https://go-review.googlesource.com/c/go/+/171464/1/src/cmd/compile/internal/gc/pgen.go#39

Seems worth looking into and understanding whether the existing code is safe.

**Comment by cuonglm** [comment]
@randall77 Can you elaborate what is exactly the `same fix`?

Does it mean:

```
lsym := Ctxt.Lookup(fn.Func.lsym.Name + ".args_stackmap")
```

or:

```
lsym := Ctxt.Lookup(fn.funcname()+ ".args_stackmap")
```

**Comment by cuonglm** [comment]
> Seems worth looking into and understanding whether the existing code is safe.

@mdempsky it seems to be safe.

Method without body can only occur via `//go:linkname` (method via assembly won't happen in Go 1 https://github.com/golang/go/issues/4978) and `//go:linkname` already has full path. So something like this:

```
package d

import _ "unsafe"

//go:linkname a a.IndexController.M
func a() {}

//go:linkname b b.IndexController.M
func b() {}
```

will work.
