### ISSUE TITLE
cmd/go: "go mod vendor" should not modify my go.mod file.

### ISSUE THREAD

**Issue by andyliuliming** [golang/go#31612]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/andy/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/andy/workspace/gopath"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/andy/workspace/gopath/src/goms.io/acsrp/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cg/3770ch_93sj65nvnr6t4rbtm0000gn/T/go-build638280199=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by jayconrod** [comment]
@andyliuliming What modifications are you seeing?

Most commands will modify the `go.mod` file if the module graph is not fully specified. These modifications are important for ensuring a reproducible build (and in this case, a reproducible vendor directory).

Did you run `go mod tidy` before `go mod vendor`? If there was an unexpected modification, please provide enough information for us to reproduce the issue.
