### ISSUE TITLE
Go' bootstrap: Will the performance increase if C or assembly language is involved?

### ISSUE THREAD

**Issue by beef9999** [golang/go#31613]
Please beat up C++ on performance so I can switch to Go as soon as possible.

**Comment by agnivade** [comment]
Hi @beef9999 - We use the issue tracker only for specific bugs or proposals related to the Go programming language. Suggestions like these are best discussed in https://github.com/golang/go/wiki/Questions.

However, if you have some specific suggestions to improve, please do file specific issues on those. Thanks.

**Comment by beoran** [comment]
@beef9999 Go is already getting close to being as performant as C(++) for several types of program. 
See, e.g. https://benchmarksgame-team.pages.debian.net/benchmarksgame/faster/go-gpp.html. And you can use the [Go Assembler](https://golang.org/doc/asm) if you ever need a speed up for critical code.
