### ISSUE TITLE
cmd/go: go mod edit -json panics on empty go.mod file

### ISSUE THREAD

**Issue by fhs** [golang/go#31623]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +f0e9754696 Tue Apr 23 00:58:08 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/fhs/.cache/go-build"
GOENV="/home/fhs/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/fhs/go"
GOPROXY=""
GOROOT="/home/big/go"
GOTMPDIR=""
GOTOOLDIR="/home/big/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build834544503=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
mkdir /tmp/test
cd /tmp/test
touch go.mod
go mod edit -json
```

### What did you expect to see?

Not panic

### What did you see instead?
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8c6c82]

goroutine 1 [running]:
cmd/go/internal/modcmd.editPrintJSON(0xc000070360)
	/home/big/go/src/cmd/go/internal/modcmd/edit.go:388 +0x52
cmd/go/internal/modcmd.runEdit(0xe5c960, 0xc0000200f0, 0x0, 0x0)
	/home/big/go/src/cmd/go/internal/modcmd/edit.go:204 +0x530
main.main()
	/home/big/go/src/cmd/go/main.go:188 +0x580
```

**Comment by agnivade** [comment]
Happens with 1.12 also. 

@bcmills @jayconrod
