### ISSUE TITLE
golang driver for oracle timesten

### ISSUE THREAD

**Issue by chuongnx** [golang/go#31625]
https://github.com/golang/go/wiki/SQLDrivers
please help me, i want golang driver for oracle timesten,

**Comment by mdlayher** [comment]
Please see https://github.com/golang/go/wiki/Questions. Closing, not a Go project issue.

**Comment by sinylei** [comment]
@chuongnx , Hi, have you found such driver? I found goracle that support OCI/ODPI-C, It is ok to connect to traditional oracle database using goracle, but I failed to connect to TimesTen though timesten support OCI/ODPI-C.
If you find some method or lib, can you share me ?

**Comment by chuongnx** [comment]
Hi sinylei, I have not yet find it
