### ISSUE TITLE
"cannot define new methods on non-local type ___" is not always an error

### ISSUE THREAD

**Issue by StephanVerbeeck** [golang/go#31631]
about the compile time error "cannot define new methods on non-local type ___"

Related to closed issue #28066

	func (a int) Sum(b int) (total int) {
		total = a + b
		return
	}

	func (a int) sum(b int) (total int) {
		total = a + b
		return
	}

This feature request was already made and rejected based on **flawed** reasoning.
This is **very crucial missing functionality**.  The reasoning that changing the behavior of other packages (and exporting these changes introducing compiler complications and inconsistency) is only CORRECT for public functions, but there is no valid argument why this should not be allowed for package local functions.  So in the 2 examples provided the first should indeed generate a compiler error (or at least warning) but the second one should be allowed and should work without any arguable difficulties or compile problems.

Given that GOlang does not (correctly so) do stuff like templates and macros, this last resort should not be taken away from programmers.

That every package needs to copy its own set of extensions this way is also not a problem as any of such extensions is local to the extender and a local issue of each distinct package.

**Comment by beoran** [comment]
You can already extend existing types simply by defining a type based on them. 

Either
```
type extended Existing
```
or
```
type extended struct { 
Existing // inherit the methods
}
```
And you can then define any methods you like on extended. So I see no reason to change the language just to  save a single type statement.

**Comment by ianlancetaylor** [comment]
@StephanVerbeeck I agree that permitting unexported methods to be defined on externally defined types is less problematic.  But that is an odd and subtle change to make to the language.  And as @beoran notes, there are other ways to do this.  So we aren't going to make this change.  Sorry.
