### ISSUE TITLE
misc/wasm: wrong string length in strPtr function in wasm_exec.js

### ISSUE THREAD

**Issue by wcchoi** [golang/go#31645]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes, the source code for the function `strPtr` in `misc/wasm/wasm_exec.js` in the latest commit is same as that of the file in my local Go installation 

https://github.com/golang/go/blob/7e08c7f43da876bc451b774808e323215a193abd/misc/wasm/wasm_exec.js#L417-L422

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/gopath"
GOPROXY=""
GORACE=""
GOROOT="/home/user/go"
GOTMPDIR=""
GOTOOLDIR="/home/user/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build119002230=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```
$ cat main.go
package main

import "os"
import "fmt"

func main() {
    fmt.Println(os.Args)
}

$ GOOS=js GOARCH=wasm go build -o main.wasm
$ node wasm_exec.js main.wasm hello 世界

```

### What did you expect to see?
```
[main.wasm hello 世界]
```

### What did you see instead?
```
(node:1475) UnhandledPromiseRejectionWarning: RangeError: Source is too large
    at Uint8Array.set (<anonymous>)
    at strPtr (/home/user/gopath/go_wasm_bug/wasm_exec.js:389:56)
    at /home/user/gopath/go_wasm_bug/wasm_exec.js:398:19
    at Array.forEach (<anonymous>)
    at global.Go.run (/home/user/gopath/go_wasm_bug/wasm_exec.js:397:14)
    at /home/user/gopath/go_wasm_bug/wasm_exec.js:460:14
(node:1475) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1475) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
wasm-009bfb96:167


RuntimeError: memory access out of bounds
    at runtime.handleEvent (wasm-function[166]:87)
    at wasm_pc_f_loop (wasm-function[851]:5)
    at wasm_export_resume (wasm-function[850]:16)
    at global.Go._resume (/home/user/gopath/go_wasm_bug/wasm_exec.js:433:23)
    at process.<anonymous> (/home/user/gopath/go_wasm_bug/wasm_exec.js:465:9)
    at process.emit (events.js:196:13)

```
### Discussion, suggestion
This would only happen if multi-byte character (like Chinese character) are passed to the `strPtr` function.

FYI in Node.js (I used v12.0.0)
```
Welcome to Node.js v12.0.0.
Type ".help" for more information.
> let s = "世界"
undefined
> s.length
2
> let encoder = new TextEncoder("utf-8")
undefined
> let es = encoder.encode(s)
undefined
> es.length
6
> es
Uint8Array [ 228, 184, 150, 231, 149, 140 ]
> 
```

I believe this could be fixed by the following change:
```
const strPtr = (str) => {
    let ptr = offset;
    let encodedStr = encoder.encode(str + "\0");
    new Uint8Array(mem.buffer, offset, encodedStr.length).set(encodedStr);
    let encodedStrLength = encodedStr.length - 1; // exclude the null byte
    offset += encodedStrLength + (8 - (encodedStrLength % 8));
    return ptr;
};
```

**Comment by odeke-em** [comment]
Thank you for reporting this issue @wcchoi and welcome to the Go project!

Please feel free to send a CL or a Github Pull request.

Kindly paging @neelance

**Comment by neelance** [comment]
Yes, this seems correct. Sorry for not considering multi-byte characters.

I would write it like this:
```
const strPtr = (str) => {
	let ptr = offset;
	const bytes = encoder.encode(str + "\0");
	new Uint8Array(mem.buffer, offset, bytes.length).set(bytes);
	offset += bytes.length;
	if (offset % 8 !== 0) {
		offset += 8 - (offset % 8);
	}
	return ptr;
};
```

Do you want to open a pull request / CL or shall I?

**Comment by wcchoi** [comment]
Thanks, I think your code is better because there is no extra 8 bytes padding in some case as in the original code.

You can submit the PR for this issue.
