### ISSUE TITLE
a scile bug?

### ISSUE THREAD

**Issue by L-jasmine** [golang/go#31649]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I run a code like this

```
package main
import "fmt"

func main(){
	b:=[10]byte{0,1,2,3,4,5,6,7,8,9}
	b1:=b[1:2]
	b2:=b1[3:5]
	fmt.Println(b1,b2)
}
```

### What did you expect to see?
panic: runtime error: index out of range

### What did you see instead?
it output is
`[1] [4 5]`

**Comment by cuonglm** [comment]
You don't limit the cap, so `b1` has cap = 9.

**Comment by mvdan** [comment]
Closing. In the future, when you have questions, see https://golang.org/wiki/Questions.
