### ISSUE TITLE
Unexpected output

### ISSUE THREAD

**Issue by shameertt** [golang/go#31650]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>
play.golang.org
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

play not showing current time

https://play.golang.org/p/Z8j-Ca32HDO

### What did you expect to see?
time.Now()

### What did you see instead?
but golang play shows 2009-11-10_23:00:00

**Comment by ALTree** [comment]
Thanks for reporting this.

On the playground, time is frozen. If you click on the "About" button, you can read this:

> In the playground the time begins at 2009-11-10 23:00:00 UTC (determining the significance of this date is an exercise for the reader). This makes it easier to cache programs by giving them deterministic output.

So this is working as expected. Closing here.
