### ISSUE TITLE
x/mobile/bind: after binding ios framework for go-ipfs it has nothing in it

### ISSUE THREAD

**Issue by mNizhurin** [golang/go#31655]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.12.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/max/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/max/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kh/8ts9nvy534b3b0n8fwzpqrwm0000gn/T/go-build592238090=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
go get github.com/ipfs/go-ipfs/cmd/ipfs
go get -d github.com/ipfs/go-ipfs/cmd/ipfs/...
gomobile bind -target=ios github.com/ipfs/go-ipfs

### What did you expect to see?
Framework with .h file containing interface for classes, constructors and methods to work with ipfs.

### What did you see instead?

As you can see, only IpfsVersion is available:

Ipfs.h: 

```
// Objective-C API for talking to the following Go packages
//
//	github.com/ipfs/go-ipfs
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Ipfs_FRAMEWORK_H__
#define __Ipfs_FRAMEWORK_H__

#include "Ipfs.objc.h"
#include "Universe.objc.h"

#endif
```

Ipfs.objc.h

```
// Objective-C API for talking to github.com/ipfs/go-ipfs Go package.
//   gobind -lang=objc github.com/ipfs/go-ipfs
//
// File is generated by gobind. Do not edit.

#ifndef __Ipfs_H__
#define __Ipfs_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull const IpfsApiVersion;
/**
 * CurrentVersionNumber is the current application's version literal
 */
FOUNDATION_EXPORT NSString* _Nonnull const IpfsCurrentVersionNumber;

@interface Ipfs : NSObject
/**
 * CurrentCommit is the current git commit, this is set as a ldflag in the Makefile
 */
+ (NSString* _Nonnull) currentCommit;
+ (void) setCurrentCommit:(NSString* _Nonnull)v;

@end

#endif
```

**Comment by eliasnaur** [comment]
That's all the github.com/ipfs/go-ipfs package contains (according to https://godoc.org/github.com/ipfs/go-ipfs). You have to list all Go packages you want to bind on the gomobile command line.
