### ISSUE TITLE
x/gddo: trybots do not work

### ISSUE THREAD

**Issue by bsiegert** [golang/go#31660]
There are a number of pending CLs for godoc.org, aka golang.org/x/gddo.

Unfortunately, trybot runs do not work in this subrepository. For example, https://go-review.googlesource.com/c/gddo/+/173218 shows all trybots failed, with an [error message like](https://storage.googleapis.com/go-build-log/13d0af4e/openbsd-amd64-64_1c5802ca.log)

```
go: warning: "golang.org/x/gddo/..." matched no packages
no packages to test
```

**Comment by bradfitz** [comment]
Dup of #21071 wherein it was decided that TryBots weren't desired there.
