### ISSUE TITLE
cmd/go: Improve module tag discovery

### ISSUE THREAD

**Issue by saschagrunert** [golang/go#31673]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 linux/amd6
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/home/sascha/go/bin"
GOCACHE="/home/sascha/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/sascha/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib64/go/1.12"
GOTMPDIR=""
GOTOOLDIR="/usr/lib64/go/1.12/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build085180678=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

- create a new go package with a single `main.go`:
```go
package main

import (
	"fmt"

	specs "github.com/opencontainers/runtime-spec/specs-go"
)

func main() {
	spec := specs.Spec{Version: "1.0.0"}
	fmt.Printf("spec version: %v\n", spec.Version)
}
```
- create a `go.mod` file which points to `master`:
```
module vendor

go 1.12

require github.com/opencontainers/runtime-spec master
```
- let go discover the latest tag:
```
> export GO111MODULE=on
> go mod download
go: finding github.com/opencontainers/runtime-spec master
```
- verify the version string:
```
> cat go.mod
module vendor

go 1.12

require github.com/opencontainers/runtime-spec v0.1.2-0.20190408193819-a1b50f621a48
```

### What did you expect to see?

A correct version string like this, [since v1.0.1 is the latest release](https://github.com/opencontainers/runtime-spec/releases).
```
require github.com/opencontainers/runtime-spec v1.0.2-0.20190408193819-a1b50f621a48
```

### What did you see instead?

A wrong latest version like this:
```
require github.com/opencontainers/runtime-spec v0.1.2-0.20190408193819-a1b50f621a48
```

The main issue here is the discovery of the git tag, which uses the `--first-parent` which follows only the first parent on merges.
https://github.com/golang/go/blob/44343c777ca8c02262d1d381a2cc24866b3c5414/src/cmd/go/internal/modfetch/codehost/git.go#L651-L656

I would propose to remove this flag and allow tags from branches. WDYT?

**Comment by thepudds** [comment]
Hi @saschagrunert, FYI there is some potentially related discussion in #27171, including https://github.com/golang/go/issues/27171#issuecomment-486328242.

`--first-parent` might have been first introduced in 9430c1a669b6d4a832f740ba0c9f67c4267d9170

Could you say a bit more about what specific piece of the git history for `github.com/opencontainers/runtime-spec ` might be throwing things off in your example under the current implementation?

CC @leitzler

**Comment by thepudds** [comment]
#31287 also potentially related, including https://github.com/golang/go/issues/31287#issuecomment-483833985

**Comment by saschagrunert** [comment]
> #31287 also potentially related, including [#31287 (comment)](https://github.com/golang/go/issues/31287#issuecomment-483833985)
> 
> CC @paulbdavis

Yes, this is the issue. The other linked issues might are (partly) related to caching but do not state the issue mentioned here.

A main workflow for release engineering would be:
- Create a release branch
- Work on it, tag the version
- Merge the release branch back

These tags are currently not caught because of the `--first-parent` flag. :) In runtime-spec it looks like this, where tag `<v1.0.1>` is not matched:

```
2017-11-07 20:06 -0800 Tianon Gravi      ●─│─╮ Merge pull request #919 from vbatts/release-1.0.1
2017-09-08 11:35 -0400 Vincent Batts     │ │ ∙ version: put master back to -dev
2017-09-08 11:29 -0400 Vincent Batts     │ │ ∙ <v1.0.1> version: release 1.0.1
2017-09-06 14:34 -0700 W. Trevor King    │ │ ∙ ChangeLog: Document changes since v1.0.0
2017-10-23 09:42 -0700 Tianon Gravi      ●─┼─╯ Merge pull request #929 from giuseppe/add-more-implementations
```

**Comment by leitzler** [comment]
I don’t think that will solve the entire issue.
Git describe doesn’t seem to actually see all tags, and should probably be replaced with something like `git for-each-ref --sort=-creatordate --format '%(refname:lstrip=2)' --merged master refs/tags` (If the desired branch is master), then filtered (and sorted) based on semver.
