### ISSUE TITLE
misc/cgo/fortran: segmentation fault on fortran test

### ISSUE THREAD

**Issue by rnunziata** [golang/go#31680]
##### ../misc/cgo/fortran
signal: segmentation fault (core dumped)
FAIL	_/home/rjn/go/misc/cgo/fortran	0.115s
FAIL: go test
2019/04/25 12:40:12 Failed: exit status 1

##### ../misc/swig/stdio
PASS
ok  	_/home/rjn/go/misc/swig/stdio	0.004s

##### ../misc/swig/callback
PASS
ok  	_/home/rjn/go/misc/swig/callback	0.002s

##### ../misc/cgo/test
PASS
ok  	_/home/rjn/go/misc/cgo/test	2.424s
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error

##### ../misc/cgo/testgodefs
skipped due to earlier error
2019/04/25 12:40:25 FAILED

>>>>env | grep FC
FC=/home/rjn/anaconda3/bin/x86_64-conda_cos6-linux-gnu-gfortran

**Comment by ianlancetaylor** [comment]
Thanks for the report.  What version of `gfortran` are you using?

Please try changing to the misc/cgo/fortran directory and running `base -xv test.bash /home/rjn/anaconda3/bin/x86_64-conda_cos6-linux-gnu-gfortran`, and append the result here.  Thanks.

**Comment by rnunziata** [comment]
```
gfortran --version
GNU Fortran (Homebrew gcc 5.5.0_4) 5.5.0
Copyright (C) 2015 Free Software Foundation, Inc.
```

not sure what you mean by changing the misc/cgo/fortran directory.

If I go to fortran directory and run test.bash I get the following.
```

bash -xv test.bash /home/rjn/anaconda3/bin/x86_64-conda_cos6-linux-gnu-gfortran
#!/usr/bin/env bash
# Copyright 2016 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This directory is intended to test the use of Fortran with cgo.

set -e
+ set -e

FC=$1
+ FC=/home/rjn/anaconda3/bin/x86_64-conda_cos6-linux-gnu-gfortran

goos=$(go env GOOS)
go env GOOS
++ go env GOOS
+ goos=linux

libext="so"
+ libext=so
if [ "$goos" = "darwin" ]; then
	libext="dylib"
fi
+ '[' linux = darwin ']'

case "$FC" in
*gfortran*)
  libpath=$(dirname $($FC -print-file-name=libgfortran.$libext))
  export CGO_LDFLAGS="$CGO_LDFLAGS -Wl,-rpath,$libpath -L $libpath"
  ;;
esac
+ case "$FC" in
dirname $($FC -print-file-name=libgfortran.$libext)
$FC -print-file-name=libgfortran.$libext
+++ /home/rjn/anaconda3/bin/x86_64-conda_cos6-linux-gnu-gfortran -print-file-name=libgfortran.so
++ dirname /home/rjn/anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/lib/../lib/libgfortran.so
+ libpath=/home/rjn/anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/lib/../lib
+ export 'CGO_LDFLAGS= -Wl,-rpath,/home/rjn/anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/lib/../lib -L /home/rjn/anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/lib/../lib'
+ CGO_LDFLAGS=' -Wl,-rpath,/home/rjn/anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/lib/../lib -L /home/rjn/anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/lib/../lib'

if ! $FC helloworld/helloworld.f90 -o main.exe >& /dev/null; then
  echo "skipping Fortran test: could not build helloworld.f90 with $FC"
  exit 0
fi
+ /home/rjn/anaconda3/bin/x86_64-conda_cos6-linux-gnu-gfortran helloworld/helloworld.f90 -o main.exe
rm -f main.exe
+ rm -f main.exe

status=0
+ status=0

if ! go test; then
  echo "FAIL: go test"
  status=1
fi
+ go test
# _/home/rjn/go/misc/cgo/fortran
/tmp/go-build822519950/_/home/rjn/go/misc/cgo/fortran/_test/_obj_test/fortran.cgo2.o: In function `_cgo_52c0002bf9f5_Cfunc_the_answer':
./fortran.go:42: undefined reference to `the_answer'
collect2: error: ld returned 1 exit status
FAIL	_/home/rjn/go/misc/cgo/fortran [build failed]
+ echo 'FAIL: go test'
FAIL: go test
+ status=1

exit $status
+ exit 1

```

**Comment by ianlancetaylor** [comment]
Thanks.  That is not the same problem as in your original report.  Any idea why?  Is the original problem repeatable?

Now could you please try, in that directory,

    FC=/home/rjn/anaconda3/bin/x86_64-conda_cos6-linux-gnu-gfortran go test -x

Thanks.

**Comment by rnunziata** [comment]
Here is the results:

```
~/go/misc/cgo/fortran$ FC=/home/rjn/anaconda3/bin/x86_64-conda_cos6-linux-gnu-gfortran go test -x


WORK=/tmp/go-build831298017
mkdir -p $WORK/_/home/rjn/go/misc/cgo/fortran/_test/_/home/rjn/go/misc/cgo/
mkdir -p $WORK/_/home/rjn/go/misc/cgo/fortran/_test/_obj_test/
cd /home/rjn/go/misc/cgo/fortran
CGO_LDFLAGS="-g" "-O2" /usr/lib/go-1.6/pkg/tool/linux_amd64/cgo -objdir $WORK/_/home/rjn/go/misc/cgo/fortran/_test/_obj_test/ -importpath _/home/rjn/go/misc/cgo/fortran -- -I $WORK/_/home/rjn/go/misc/cgo/fortran/_test/_obj_test/ fortran.go
/home/rjn/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/_/home/rjn/go/misc/cgo/fortran/_test/_obj_test/ -g -O2 -o $WORK/_/home/rjn/go/misc/cgo/fortran/_test/_obj_test/_cgo_main.o -c $WORK/_/home/rjn/go/misc/cgo/fortran/_test/_obj_test/_cgo_main.c
/home/rjn/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/_/home/rjn/go/misc/cgo/fortran/_test/_obj_test/ -g -O2 -o $WORK/_/home/rjn/go/misc/cgo/fortran/_test/_obj_test/_cgo_export.o -c $WORK/_/home/rjn/go/misc/cgo/fortran/_test/_obj_test/_cgo_export.c
/home/rjn/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/_/home/rjn/go/misc/cgo/fortran/_test/_obj_test/ -g -O2 -o $WORK/_/home/rjn/go/misc/cgo/fortran/_test/_obj_test/fortran.cgo2.o -c $WORK/_/home/rjn/go/misc/cgo/fortran/_test/_obj_test/fortran.cgo2.c
/home/rjn/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -I . -fPIC -m64 -pthread -fmessage-length=0 -o $WORK/_/home/rjn/go/misc/cgo/fortran/_test/_obj_test/_cgo_.o $WORK/_/home/rjn/go/misc/cgo/fortran/_test/_obj_test/_cgo_main.o $WORK/_/home/rjn/go/misc/cgo/fortran/_test/_obj_test/_cgo_export.o $WORK/_/home/rjn/go/misc/cgo/fortran/_test/_obj_test/fortran.cgo2.o -g -O2
# _/home/rjn/go/misc/cgo/fortran
/home/rjn/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: $WORK/_/home/rjn/go/misc/cgo/fortran/_test/_obj_test/fortran.cgo2.o: in function `_cgo_52c0002bf9f5_Cfunc_the_answer':
./fortran.go:42: undefined reference to `the_answer'
collect2: error: ld returned 1 exit status
$WORK/_/home/rjn/go/misc/cgo/fortran/_test/fortran.test
FAIL	_/home/rjn/go/misc/cgo/fortran [build failed]

```

**Comment by ianlancetaylor** [comment]
The test is running with Go 1.6.  That doesn't support Fortran.  This test assumes that the version of `go` on `PATH` is the one that you are building.  I'm guessing that that is not the case for you.

**Comment by ianlancetaylor** [comment]
Although while that explains why running the test yourself doesn't work, it doesn't explain why the test fails when running via `all.bash`.  Try adjusting your `PATH` so that the newly built `go` tool is first, and then run `test.bash` again.  Thanks.

**Comment by rnunziata** [comment]
I get same error after:

export PATH=/usr/lib/go-1.6/pkg/tool/linux_amd64:$PATH

also some additional info:



```
>>> go env


GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="/home/rjn/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="/home/rjn/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++"
CGO_ENABLED="1"

```

and note if I try to run test directly it fails without error..

```
>>> ./test.bash
skipping Fortran test: could not build helloworld.f90 with 
```

**Comment by ianlancetaylor** [comment]
I would not expect this test to work when using Go 1.6.  I'm assuming that you are not building Go 1.6, as misc/cgo/fortran does not exist in Go 1.6; it was added in Go 1.7.  I'm suggesting that you modify `PATH` to point to the `bin` directory of whatever release you are actually building.

**Comment by rnunziata** [comment]
If I set PATH to : 

`export PATH=/home/rjn/go/bin:$PATH`

which is the go directory I am currently installing then 

`go test -x`

works but

`./all.bash`

still fails as before 

===================================

if I set PATH to:

export PATH=/usr/lib/go-1.6/bin:$PATH

which is installed in usr dir. then 

`go test -x '

fails`

====================

So what you are saying is true but for some reason all.bash still fails....I can not seem to set GOROOT or GOROOT_BOOTSTRAP to its liking.  No mater what I do I get the same error as follows:
note: I had to rename my dir to go1.4 to make it install happy now it fails as below.
```

Building Go cmd/dist using /home/rjn/go1.4.
ERROR: $GOROOT_BOOTSTRAP must not be set to $GOROOT
Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4
```
Can I just upgrade to Go 1.7? How can I do this?

**Comment by ianlancetaylor** [comment]
I'm not sure why `all.bash` fails if you set `PATH` to include the path to the newly built Go binary.

Note that you can in practice ignore this test failure.  Your Go tools will be installed and working.

**Comment by rnunziata** [comment]
ok...I guess we can close this.
