### ISSUE TITLE
x/tools/cmd/gopls: doesn't support Go 1.10; ti.EmbeddedType undefined

### ISSUE THREAD

**Issue by chew351** [golang/go#31693]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.4 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
yes， it can always reproduce

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
 go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build779563939=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
I just git clone https://github.com/golang/tools.git, and want to build gopls, but failed,
my OS is ubuntu 18

**Comment by stamblerre** [comment]
We typically only support the current and previous Go versions (1.12 and 1.11) in the x/tools repository. However, maybe I can investigate adding Go 1.10 support in this case. Is there a reason you are still using Go 1.10?

**Comment by dlech** [comment]
> Is there a reason you are still using Go 1.10?

It is the version that is packaged with Ubuntu 18.04.

**Comment by chew351** [comment]
Hi Rebecca,

Thanks for your reply immediately, I just use apt-get install golang and the version 1.10 was installed. I’ll try update go to 1.12

Regards
Chew

发自我的 iPad

**Comment by chew351** [comment]
Hi David,
Thanks for your reply!
Yes, I just use apt-get install golang on Ubuntu18, and version1.10 was installed, I will try to update go to version 1.12.

Thanks
Chew

发自我的 iPad

**Comment by stamblerre** [comment]
I apologize, but we've decided that we will not be supporting Go versions <= 1.10 in `gopls`. `gopls` is built on top of [`go/packages`](https://godoc.org/golang.org/x/tools/go/packages), which does not support Go 1.10, so we won't be able to fully support it. I recommend upgrading to the latest Go version.
