### ISSUE TITLE
x/tools/go/packages: permit separate LoadMode for deps

### ISSUE THREAD

**Issue by zombiezen** [golang/go#31699]
I really like the new `packages.LoadMode` bits that were introduced to fix #29429, thanks! I'm using go/packages for a [utility to gather example functions](https://github.com/google/go-cloud/blob/master/internal/website/gatherexamples/gatherexamples.go) in the Go CDK. Part of what this tool does is to determine which imports an example uses, which I'm doing by [walking the AST](https://github.com/google/go-cloud/blob/0ad59855e88eb6683fc5e018f2d4329bbe3bff5f/internal/website/gatherexamples/gatherexamples.go#L148-L168) of the example function body and using type information to see whether an identifier is a package name. I've been [using a `LoadMode`](https://github.com/google/go-cloud/blob/0ad59855e88eb6683fc5e018f2d4329bbe3bff5f/internal/website/gatherexamples/gatherexamples.go#L104-L108) of `NeedName | NeedFiles | NeedTypes | NeedSyntax | NeedTypesInfo`.

However, I discovered this check doesn't work if the package is not in the stdlib or in the set of directly matched packages. In an upcoming change, I will add `NeedImports | NeedDeps`, but this results in a 10x slowdown. I assume this is because it is syntax + type-checking the dependencies, which is not what I need. I really only need `NeedName` for dependencies, but I can't see a way of specifying that. Similar to #28740, I would like to specify different behavior for dependencies versus directly referenced packages.

/cc @matloob @ianthehat

**Comment by matloob** [comment]
We're considering an option for this (below) let us know if it would work for you.

We want to make it possible to supply ids to Load to specify packages. Then you can gather the ids for all dependency packages and query their names in a second query.

**Comment by zombiezen** [comment]
I don't think it would work: the `TypesInfo` for the package I'm walking does not have any information for any not-loaded package names in the AST. IIUC doing a second `Load` wouldn't help in this case, since I wouldn't have a way to associate a particular symbol with the package it represents.
