### ISSUE TITLE
go.mod should list dependencies of indirect package dependency without a go.mod file, not the indirect dependency module itself though

### ISSUE THREAD

**Issue by didrocks** [golang/go#31691]
#### What did you do?
Here is a small reproducer.

1. Create a project with one file to depend on spf13/cobra:
```main.go
package main

import (
        "github.com/spf13/cobra"
)

func main() {
        _ = &cobra.Command{}
}
```
With a simple `go mod init moduletest` to craft `go.mod`:
```
module moduletest

go 1.12
```
2. Now run `go mod tidy`, you would end up with the following `go.mod` file:
```
module moduletest

go 1.12

require (
        github.com/inconshreveable/mousetrap v1.0.0 // indirect
        github.com/spf13/cobra v0.0.3
        github.com/spf13/pflag v1.0.3 // indirect
)
```

#### What did you expect to see?
I was expecting to not have any indirect dependencies. Indeed, `github.com/spf13/cobra v0.0.3` has a [go.mod](https://github.com/spf13/cobra/blob/master/go.mod) file listing both `github.com/inconshreveable/mousetrap v1.0.0` and `github.com/spf13/pflag v1.0.3`.

I thus would have expect our moduletest to only list cobra:
```
module moduletest

go 1.12

require (
        github.com/spf13/cobra v0.0.3
)
```

My understanding is that both `mousetrap` and `pflag` are listed here because they don't have a `go.mod` file themselves. However, I would have expected to only have the dependencies of `mousetrap `and `pflag` to be in the moduletest `go.mod` (marked as `// indirect`), but not `mousetrap` or `pflag` themselves, as there is no additional dependency constraints on them (no `go get -u`, no other module requiring a different version).
In that particular situation, `mousetrap` and `pflag` have no out of the stdlib dependencies themselves, so no additional indirect dependencies should be listed in moduletest `go.mod`.

Basically, I don't see the immediate reason why those dependencies constraints listed via other `go.mod` files are listed here, even if those don't have any `go.mod` files. I'm happy if this reasoning makes sense to have a look to exclude them (but keeping their dependencies listed in `go.mod` if they have any as this is needed due to their lack of `go.mod` file).

I expect that a lot of leaf modules, which don't have dependencies outside of stdlib, won't use a go.mod file (even if they should, at least, for sane versioning when having a v2), so those kind of indirect listing can spread out quite quickly. (the popular pflag used by cobra is one common example by itself).

#### What did you see instead?

As stated previously, both modules are listed.

#### Does this issue reproduce with the latest release (go1.12.4)?
I reproduced it on go1.12.3, but I didn't see any relevant fixed in go 1.12.4.

#### System details

```
go version go1.12 linux/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/didrocks/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/didrocks/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version go1.12 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.12
uname -sr: Linux 5.0.0-13-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.29-0ubuntu2) stable release version 2.29.
gdb --version: GNU gdb (Ubuntu 8.2.91.20190405-0ubuntu3) 8.2.91.20190405-git
```

**Comment by thepudds** [comment]
Your example seems to depend on v0.0.3 of cobra. 

 There seems to be  a go.mod file on master of cobra, but not at that v0.0.3 version you are using: 

https://github.com/spf13/cobra/tree/v0.0.3

**Comment by leitzler** [comment]
As @thepudds say, v0.0.3 of cobra doesn’t have a go.mod. The reason you get `v0.0.3` instead of the current master version is because your newly added dependency defaults to “latest” version, that resolves to the latest release (see https://github.com/golang/go/wiki/Modules#version-selection).

If you specify master, the other dependencies won’t be listed in your `go.mod`:
```
$ cd $(mktemp -d) && go mod init foo
go: creating new go.mod: module foo
$ go get github.com/spf13/cobra@master
go: finding github.com/spf13/cobra master
$ cat go.mod
module foo

go 1.12

require github.com/spf13/cobra v0.0.4-0.20190321000552-67fc4837d267 // indirect
$ cat > main.go
package main

import _ "github.com/spf13/cobra"
$ go mod tidy
$ cat go.mod
module foo

go 1.12

require github.com/spf13/cobra v0.0.4-0.20190321000552-67fc4837d267
```

**Comment by didrocks** [comment]
Oh sorry, I mislooked and got the impression that cobra had a `go.mod` file. I should have checked v0.0.3 indeed!

Ok, so that explains why the 2 dependencies were thus listed, and confirmed that with latest master, those are not. Thanks @leitzler & @thepudds. Closing thus.
