### ISSUE TITLE
wasm: cmd/asm test has been flaky on wasm builder

### ISSUE THREAD

**Issue by cherrymui** [golang/go#31702]
cmd/asm test has been flaky on wasm builder for a while. For example,
https://build.golang.org/log/e9777631c449354459ab95a76f8c6e3e0110c468
https://build.golang.org/log/35784fb64c82e732ef2c02b4596679f8eea429d3

It's mostly assembling for ARM or ARM64. Sometimes it just failed to assemble, and sometimes  it got a lot of wrong output or even junk data.

It doesn't look like a problem of cmd/asm, as it works fine on all the other platforms.

It seems like memory corruption that is Wasm specific, but it looks weird to me that it always happens on cmd/asm, which is by no means special, and is not a very intensive stress test. (For example, it never fails at cmd/compile, which shares a lot of code with cmd/asm.) Maybe something related to the file system, or reading output from child process?

I have not looked into it.

**Comment by odeke-em** [comment]
Thank you for this report @cherrymui! Kindly paging @neelance
