### ISSUE TITLE
x/tools/cmd/gopls: allow user fine-grained control over which vet checks to run

### ISSUE THREAD

**Issue by inliquid** [golang/go#31717]
For example, I need to pass `-composites=false` flag to avoid these meaningless messages:
![изображение](https://user-images.githubusercontent.com/6797881/56853958-ad1d3100-6937-11e9-9747-73c96f4ee266.png)

**Comment by KatamariJr** [comment]
Any update on this? I would also like this feature for the exact same reason.

**Comment by stamblerre** [comment]
This hasn't been a high priority issue for us yet, but if someone wants to take a look at adding it before I have a chance to, we'd be happy to take contributions.

**Comment by guiguan** [comment]
I think this is pretty critical to the developer experience of `gopls`. I wish I had time to make a contribution

**Comment by guiguan** [comment]
A simple workaround to config `vet`. For example, disable the `composite` analyzer for `github.com/mongodb/mongo-go-driver`: https://github.com/guiguan/tools/commit/a9ca269c6eb67aed4c0ed4c9f870c091d729ea56

**Comment by mvdan** [comment]
For those of you disabling the entire composites check, would https://github.com/golang/go/issues/43864 seem like a good compromise to not disable the check entirely? Please upvote that proposal or comment on it, depending on your thoughts.
