### ISSUE TITLE
can't run go run projectname.go

### ISSUE THREAD

**Issue by eugenepranoto** [golang/go#31715]
### **this is my env**
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go-project"
GOPROXY=""
GORACE=""
GOROOT="/root/go"
GOTMPDIR=""
GOTOOLDIR="/root/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"

**IM GETTING THIS ERROR**
runtime: epollwait on fd 4 failed with 38
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0x9e9a22, 0x17)
        /usr/local/go/src/runtime/panic.go:617 +0x72
runtime.netpoll(0x554fc67700, 0x0)
        /usr/local/go/src/runtime/netpoll_epoll.go:75 +0x209
runtime.sysmon()
        /usr/local/go/src/runtime/proc.go:4326 +0x374
runtime.mstart1()
        /usr/local/go/src/runtime/proc.go:1206 +0xc4
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1172 +0x6f

goroutine 1 [runnable]:
syscall.Syscall6(0x106, 0xffffffffffffff9c, 0xc000250000, 0xc00024e038, 0x100, 0x0, 0x0, 0x0, 0xc00024e038, 0x0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.fstatat(0xffffffffffffff9c, 0xc00024c000, 0x20, 0xc00024e038, 0x100, 0xc00024c000, 0xc00024c011)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:1520 +0xcb
syscall.Lstat(...)
        /usr/local/go/src/syscall/syscall_linux_amd64.go:72
os.lstatNolog(0xc00024c000, 0x20, 0x3, 0x3, 0xc00024c000, 0x20)
        /usr/local/go/src/os/stat_unix.go:42 +0x6f
os.Lstat(0xc00024c000, 0x20, 0x10, 0x9de2a6, 0x1, 0xc0000e8050)
        /usr/local/go/src/os/stat.go:22 +0x4d
os.(*File).readdir(0xc0000e05e8, 0xffffffffffffffff, 0x0, 0xc000000000, 0xc0000e05e8, 0x0, 0x0)
        /usr/local/go/src/os/file_unix.go:384 +0x1ba
os.(*File).Readdir(...)
        /usr/local/go/src/os/dir.go:26
io/ioutil.ReadDir(0xc0001f1a80, 0x10, 0xc0001cf400, 0x2, 0x2, 0xc000211060, 0x1e)
        /usr/local/go/src/io/ioutil/ioutil.go:101 +0x1ee
go/build.(*Context).readDir(0xe4e340, 0xc0001f1a80, 0x10, 0x0, 0xc000211060, 0x1e, 0x4, 0xc0001d89e0)
        /usr/local/go/src/go/build/build.go:181 +0xa1
go/build.(*Context).Import(0xe4e340, 0xc0001f19d7, 0x3, 0xc000210c80, 0x19, 0x4, 0x1, 0x2, 0x1)
        /usr/local/go/src/go/build/build.go:742 +0x707
cmd/go/internal/load.LoadImport(0xc0001f19d7, 0x3, 0xc000210c80, 0x19, 0xc000140900, 0xc000103ac0, 0xc00022cbd0, 0x1, 0x1, 0x1, ...)
        /usr/local/go/src/cmd/go/internal/load/pkg.go:548 +0x10d4
cmd/go/internal/load.(*Package).load(0xc000140900, 0xc000103ac0, 0xc000237500, 0x0, 0x0)
        /usr/local/go/src/cmd/go/internal/load/pkg.go:1416 +0x21af
cmd/go/internal/load.GoFilesPackage(0xc0000201a0, 0x1, 0x1, 0x0)
        /usr/local/go/src/cmd/go/internal/load/pkg.go:2010 +0x543
cmd/go/internal/run.runRun(0xe43dc0, 0xc0000201a0, 0x1, 0x1)
        /usr/local/go/src/cmd/go/internal/run/run.go:78 +0x186
main.main()
        /usr/local/go/src/cmd/go/main.go:219 +0x7a4

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41
![Capture](https://user-images.githubusercontent.com/35261929/56851801-6cc0b180-693d-11e9-981c-d27b45718e0f.PNG)

**Comment by ALTree** [comment]
Thanks for the report. 

Your screenshot shows the linux-am64 archive, but the explorer looks like the one on windows. Are you trying to run go for Linux on the Windows Subsystem for Linux (WSL)?

**Comment by JAicewizard** [comment]
GOHOSTOS is Linux, so I would assume that he is running the command from Linux subsystem for windows?
The .* files also seem to indicate a Linux environment and the lxss folder also indicate WSL.

**Comment by eugenepranoto** [comment]
> Thanks for the report.
> 
> Your screenshot shows the linux-amd64 archive, but the explorer looks like the one on windows. Are you trying to run go for Linux on the Windows Subsystem for Linux (WSL)? If yes, this may be a dup of #25384.

yes Im.  Im trying to run go on WSL. i already extract the linux-amd64, the result is go folder. But im a little bit confuse with root directory and rootfs directory. Which is both contain in lxss directory. Can u explain me about that 2 directory? Am I wrong during setting my go env?

**Comment by eugenepranoto** [comment]
> GOHOSTOS is Linux, so I would assume that he is running the command from Linux subsystem for windows?
> The .* files also seem to indicate a Linux environment and the lxss folder also indicate WSL.

yes im running on WSL.. any suggestion sir?

**Comment by JAicewizard** [comment]
no, but (as far as I remember) ALTree didn't notice it, so I though I might be of use to him.

**Comment by ALTree** [comment]
Thanks for checking. Then this is indeed a dup of #25384. As it was said there:

> historically we've just waited for Microsoft to fix kernel compatibility issues in WSL.

So I'm closing this issue.
