### ISSUE TITLE
Simplified execution of shell commands.

### ISSUE THREAD

**Issue by XenonLab-Studio** [golang/go#31714]
I have been using golang for 1 month, and I really like it. The programming language is very beautiful and very easy. But I was wondering if it was possible to implement in the next releases the possibility of importing a package to manage the execution of shell commands (unix, linux, mac os, windows).

Currently the only solution to manage a clear screen under linux seems to be this:

```go
package main

import (
	"os"
	"os/exec"
	"runtime"
)

var clear map[string]func() //create a map for storing clear funcs

func init() {
	clear = make(map[string]func()) //Initialize it
	clear["linux"] = func() {
		cmd := exec.Command("clear") //Linux example, its tested
		cmd.Stdout = os.Stdout
		cmd.Run()
	}
	clear["windows"] = func() {
		cmd := exec.Command("cmd", "/c", "cls") //Windows example, its tested
		cmd.Stdout = os.Stdout
		cmd.Run()
	}
}

func CallClear() {
	value, ok := clear[runtime.GOOS] //runtime.GOOS -> linux, windows, darwin etc.
	if ok {                          //if we defined a clear func for that platform:
		value() //we execute it
	} else { //unsupported platform
		panic("Your platform is unsupported! I can't clear terminal screen :(")
	}
}
```

In C++ it is sufficient to do this:

```cpp
#include <iostream>
#include <stdlib.h>

int main()
{
    std::system("clear");
}
```

I think it's a very useful thing, I did a lot of research and I assume that a library that easily handles the execution of shell commands is not yet available.

Thanks to all, golang is really cool.

**Comment by crvv** [comment]
This is documented in `os/exec`.
https://golang.org/pkg/os/exec/

> Unlike the "system" library call from C and other languages, the os/exec package intentionally does not invoke the system shell and does not expand any glob patterns or handle other expansions, pipelines, or redirections typically done by shells. The package behaves more like C's "exec" family of functions. To expand glob patterns, either call the shell directly, taking care to escape any dangerous input, or use the path/filepath package's Glob function. To expand environment variables, use package os's ExpandEnv.

**Comment by beoran** [comment]
Also, if toy want to clear the screen,  there are many terminal libraries available for Go language, such as:
https://github.com/gdamore/tcell
https://github.com/avelino/awesome-go#advanced-console-uis

**Comment by agnivade** [comment]
@XenonLab-Studio - Please clarify why you want such a feature to be in the standard library and not as a third party package as mentioned earlier. Also see https://golang.org/doc/faq#x_in_std

**Comment by XenonLab-Studio** [comment]
@agnivade The solution I found is good, but it would be nice to be able to call specific functions that simplify the execution of shell commands.

Something like:

```go
package main

import (
        "fmt"
	"os"
	"os/exec"
)

func main() {
        exec.Shell("echo Hello, World")
	fmt.Println("Hello, world")
}
```
Reason for my request:

Go is a very easy language, it really simplifies many complex aspects in all the other languages. I wonder if it is possible to make it even easier, especially for beginners, without removing or modifying anything. Creating simplified functions to execute shell commands shouldn't be a problem (I assume). Experienced programmers can use more complex procedures for their projects, without changing what already exists in the standard library.

I hope I was clear. I use Golang for teaching (middle school children), I try to evaluate what can be made easy and what is not. For all the rest I will wait for Go 2 with the new features.

**Comment by bradfitz** [comment]
Sorry, but we're not going to do this for the various reasons listed above.

**Comment by JAicewizard** [comment]
you can create your own library that abstracts this.
