### ISSUE TITLE
x/tools/present: add timer and current time to notes/speaker window

### ISSUE THREAD

**Issue by leighmcculloch** [golang/go#31718]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/home/leighmcculloch/local/bin"
GOCACHE="/home/leighmcculloch/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/leighmcculloch/go"
GOPROXY=""
GORACE=""
GOROOT="/home/leighmcculloch/local/bin/go"
GOTMPDIR=""
GOTOOLDIR="/home/leighmcculloch/local/bin/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build861470077=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Press `N` while viewing my go present talk slides, to open the notes window.

### What did you expect to see?

The current time and a timer clearly showing how long I've been talking for (since the notes window is opened).

### What did you see instead?

Not that.

### Why would this be helpful?

The current time and how long we've been speaking for is something that almost all speakers need to be aware of. In some very well setup situations that information might be provided on stage, but in a lot of situations we're opening our phones and turning on stop watches and this never works well because our phone displays will sleep and it means looking at another display.

Other presentation tools, e.g. [gitpitch](https://github.com/gitpitch/in-60-seconds), provide this, and it is extraordinarily helpful.

**Comment by darkLord19** [comment]
I would like to work on this. Any pointers on how to start?

**Comment by Liberatys** [comment]
I would like to work on this if that is wanted. I think I found an efficient way to do it without much change.

**Comment by bcmills** [comment]
@ianthehat, does `present` have an owner?

**Comment by asahasrabuddhe** [comment]
Any update? I am looking for the same feature
