### ISSUE TITLE
x/build: add macOS 10.14 386 builder

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#31719]
While working on https://go-review.googlesource.com/c/go/+/174199, I noticed that GOARCH=386 ./all.bash had been broken for a while. This issue is about adding a 10.14 386 builder to avoid that problem in the future.

**Comment by bradfitz** [comment]
We have limited Macs so we're not going to run every macOS version on amd64 and 386. Mac 32-bit is already a weird case, as its days are probably numbered from Apple and nobody has 32-bit Mac hardware or OSes anyway. The only reason we have darwin/386 at all is to enable hacking on the 386 backend on a Mac.

Are you saying that we broke darwin/386 on macOS 10.14 but not on macOS 10.11 where we do run a 386 builder already?

**Comment by randall77** [comment]
Indeed, 1.11 and 1.12 work, but 1.14 doesn't.

If we have limited resources, it probably makes sense to make our darwin/386 builder match what our developers use.  That's probably the latest supported OS (I'm still on 1.12, but I've got weird hardware reasons to stay.)

**Comment by bradfitz** [comment]
SGTM. I'll update it.
