### ISSUE TITLE
doc/spec#Package_initializationthe: initialized order d b c a, real result is d c b a

### ISSUE THREAD

**Issue by terryding77** [golang/go#31724]
https://github.com/golang/go/blob/049c8dbfdbdd414359699c215f15764a7aa733b5/doc/go_spec.html#L6452

the code as [spec#Package_initializationthe](https://golang.org/ref/spec#Package_initialization)
```
package main

import "fmt"

var (
    a = c + b
    b = f()
    c = f()
    d = 3
)

func f() int {
    d++
    return d
}

func main() {
    fmt.Println("a", a)
    fmt.Println("b", b)
    fmt.Println("c", c)
    fmt.Println("d", d)
}
```
got  
```
result:
a 9
b 5
c 4
d 5
```
but with the order in spec **d-> b -> c -> a**, I think the expect result shoud be 
```
a 9
b 4
c 5
d 5
```
if I change `a = c + b` to `a = b + c` the order is same as spec `init order d b c a`
so is there something wrong?

my go version is `go version go1.12.4 linux/amd64`

**Comment by randall77** [comment]
I agree.
It seems very odd that this bug is here. This exact example is *in* the spec. There should be a test!

The gc toolchain has had this bug since at least 1.2.
The gccgo toolchain (7.3.0, at least) gets it right!

**Comment by dmitshur** [comment]
I think this is the same as issue #22326.

**Comment by dmitshur** [comment]
@terryding77 Thanks for reporting. I'll close this as duplicate.

@randall77 Feel free to apply release-blocker label to the other issue too, if you think it still applies.
