### ISSUE TITLE
cmd/api: what is contexts supposed to contain?

### ISSUE THREAD

**Issue by 4a6f656c** [golang/go#31725]
The contexts list in `src/cmd/api/goapi.go` contains an selection of GOOS/GOARCH values, however there appears to be no consistency. There are only a subset of GOOS values and an even smaller subset of GOARCHs.

Should this be synced with `cgoEnabled` supported list from `src/cmd/dist/build.go` (which is the "single point of truth for supported platforms") or should it be pruned to remove recent additions (e.g. the incomplete netbsd/arm64 port).

**Comment by katiehockman** [comment]
Are you suggesting a documentation change to clarify this?
For questions, see https://golang.org/wiki/Questions.

**Comment by andybons** [comment]
@bradfitz

**Comment by bradfitz** [comment]
Ideally it would test all supported platforms (`go tool dist list`) but that's slow, so we have a representative sample that should catch most accidental mistakes.

It's true that if some files in std are tagged such that they're only for `netbsd/arm64` then it's possible for API to change between releases and not be caught. But that's pretty rare that code outside runtime or syscall would be so specific to a certain port so in practice a small representative sample of ports is enough to catch mistakes.
