### ISSUE TITLE
x/tools/cmd/guru: definition doesn't look up the function references in the same package if modules are enabled

### ISSUE THREAD

**Issue by jdevelop** [golang/go#31720]
### What version of Go are you using (`go version`)?

<pre>
go version go1.12.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
**Yes**

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build666000922=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Given the files `a.go` and `b.go` defined in the same package, `guru definition` isn't able to find the method that is defined in the same package but in different file if **go.mod** is present and the project is outside of **GOPATH**.

##### a.go
```golang
package a

func TestA() {
	// do nothing
}
```

##### b.go
```golang
package a

func TestAA() {
	TestA()
}
```

Then with if the files are in the `$GOPATH/src/test/guru_mod_files/a/` the command 
```
guru definition /home/user/go/src/test/guru_mod_files/a/b.go:#30
```
returns
```
/home/user/go/src/test/guru_mod_files/a/a.go:3:6: defined here as func TestA()
```

however if the package is moved out of $GOPATH, then it doesn't work as expected:
```
guru definition /home/user/tmp/guru_mod_files/a/b.go:#30
guru: no object for identifier
```

### What did you expect to see?

Proper function definition from the other file in the same package.

### What did you see instead?

`guru: no object for identifier`

**Comment by jdevelop** [comment]
Some quick fix to consider, at the first glance it works ( tested on several modules I tried so far ). And looks pretty logical, given that `CreateFromFilenames` is meant to take several files.

```
diff --git a/cmd/guru/guru.go b/cmd/guru/guru.go
index 8dea3b53..f4c2fb26 100644
--- a/cmd/guru/guru.go
+++ b/cmd/guru/guru.go
@@ -20,6 +20,8 @@ import (
 	"go/types"
 	"io"
 	"log"
+	"os"
+	"path"
 	"path/filepath"
 	"strings"
 
@@ -164,7 +166,24 @@ func importQueryPackage(pos string, conf *loader.Config) (string, error) {
 		// Can't find GOPATH dir.
 		// Treat the query file as its own package.
 		importPath = "command-line-arguments"
-		conf.CreateFromFilenames(importPath, filename)
+		dirPath := path.Dir(filename)
+		dir, err := os.Open(dirPath)
+		if err != nil {
+			return "", err
+		}
+		defer dir.Close()
+		fis, err := dir.Readdir(-1)
+		if err != nil {
+			return "", err
+		}
+		files := make([]string, 0, 1)
+		for _, fileinfo := range fis {
+			if fileinfo.IsDir() {
+				continue
+			}
+			files = append(files, path.Join(dirPath, fileinfo.Name()))
+		}
+		conf.CreateFromFilenames(importPath, files...)
 	} else {
 		// Check that it's possible to load the queried package.
 		// (e.g. guru tests contain different 'package' decls in same dir.)
```

**Comment by bcmills** [comment]
CC @ianthehat

**Comment by ianthehat** [comment]
As mentioned on the linked cl, we have chosen not to convert guru to work with modules because we feel the effort required is too large and are focusing on gopls as a better solution instead.
If anyone wants to contribute a true port of guru to modules please to re-open this bug and send us the changes.

**Comment by bogdando** [comment]
You can simlink things around, based on that ``go mod tidy`` or ``go get`` produces. To w/a this issue I created a bash snippet https://gist.github.com/bogdando/d15cf014f3171a9ae06b83cd9c9b1c26 and it seems working for me, more or less...

**Comment by bogdando** [comment]
> not to convert guru to work with modules
https://github.com/bogdando/gogetguru a script that workarounds that issue. This time it works much better, I hope.
