### ISSUE TITLE
cgo linking issue with C++ dynamic libraries

### ISSUE THREAD

**Issue by DineshReddyK** [golang/go#31723]
### What version of Go are you using (`go version`)?

<pre>
go version go1.10.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
cp:~/containerfolder/API_Gateway_5G_cOAM_Productized$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build634932465=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I have a C++ shared library in /opt/xx/lib64. Headers are in C. In my go code, I am including proper header and linker options using CPPFLAGS/CFLAGS and LDFLAGS. Still while building go I am getting 'undefined reference` error.

```
import (
    //#cgo LDFLAGS: -L/opt/xxx/lib64/ -lsessionmgmt
    //#cgo CPPFLAGS: -I/opt/xxx/include/
    //#include <stdlib.h>
    //#include <sessionMgmt/sessionMgmt.h>
    "C"
    "unsafe"
)
```

### What did you expect to see?
successful build

### What did you see instead?

I am getting this linking errors:

```
/tmp/go-build609413262/b163/_x002.o: In function `_cgo_e38947506e9d_Cfunc_um_get_lastlogin_info':
/tmp/go-build/cgo-gcc-prolog:52: undefined reference to `um_get_lastlogin_info'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:48: vet] Error 2
```

Library is exist in the right path and do contain the required method. Not sure why this error.

```$ grep um_get_lastlogin_info /opt/xxx/lib64/libsessionmgmt.so
Binary file /opt/xxx/lib64/libsessionmgmt.so matches
```
Also tried using the pkg-config with cgo. Still the same linking error appears.

**Comment by beoran** [comment]
Is the function  `um_get_lastlogin_info` compiled as extern "C"  in the  C++ library ? Otherwise this might be due to the name mangling C++ applies.

**Comment by DineshReddyK** [comment]
Thanks a lot :). Yes, extern "C" was missing. After generating the .so with the changes, linking worked fine. 

But from the cgo documentation, I see that there is already support for c++ right. Any reason, why is it mandatory to keep extern "C".

**Comment by AlexRouSg** [comment]
cgo is integrating C and Go, not C++ and Go. You can compile and use C++ sources/libs but to use those inside Go sources you need to make it into something you can call from C.

**Comment by DineshReddyK** [comment]
Thanks for the info. I will close this.
