### ISSUE TITLE
Can't set go environment properly

### ISSUE THREAD

**Issue by AvetisSargsian** [golang/go#31733]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 windows/amd64
</pre>
### Does this issue reproduce with the latest release?
yes
### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=F:\GoWorckspace\bin
set GOCACHE=C:\Users\Avetis\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=F:\GoWorckspace
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Avetis\AppData\Local\Temp\go-build710083038=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
Hello, I am trying to launch my first hello.go example in worckspace directory
here is its structure
 F:\GoWorckspace
--bin
-- pkg
-- src
   --hello
         hello.go

My actions are:
F:\GoWorckspace\src\hello> go install hello.go
or
F:\GoWorckspace\src\hello> go build hello.go
or
F:\GoWorckspace\src\hello> go run hello.go

### What did you expect to see?
I expect to see hello.exe in bin folder of worckspace

### What did you see instead?

PS F:\GoWorckspace\src\hello> go install hello.go
open C:\Users\Avetis\AppData\Local\Temp\go-build945139258\b001\exe\a.out.exe: The system cannot find the file specified.
PS F:\GoWorckspace\src\hello> go build hello.go
open C:\Users\Avetis\AppData\Local\Temp\go-build409713554\b001\exe\a.out.exe: The system cannot find the file specified.
PS F:\GoWorckspace\src\hello> go run hello.go
open C:\Users\Avetis\AppData\Local\Temp\go-build476595234\b001\exe\hello.exe: The system cannot find the file specified.

**Comment by agnivade** [comment]
I think you will get better help on the [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions.

**Comment by odeke-em** [comment]
Thank you for the question @AvetisSargsian and welcome to the Go project!

As @agnivade pointed out, please ask questions using those resources as the Go issue tracker is for bugs with the Go programming language and tools. I'll close this issue but I hope that you can ask the question on those mediums.
