### ISSUE TITLE
s390x broken by https://go-review.googlesource.com/c/go/+/173437

### ISSUE THREAD

**Issue by billotosyr** [golang/go#31734]
### What version of Go are you using (`go version`)?

<pre>
$ go version
master tip
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?
Linux
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?

successful build

### What did you see instead?
It seems all tests in ../misc/cgo/testshared are failing

**Comment by bradfitz** [comment]
Fixed by https://go-review.googlesource.com/c/go/+/174278 I hope.

**Comment by billotosyr** [comment]
Yes -- looks like it's fixed -- thanks!
