### ISSUE TITLE
question: gccgo: bootstrapping go with gccgo

### ISSUE THREAD

**Issue by williamh** [golang/go#31732]
What version of Go are you using (`go version`)?

go version go1.12.4 linux/amd64

Hello, I'm not sure whether this is the correct forum for this, but right now it is the only one I know about and have access to, so I hope you will bear with me. :-)

I am the go package maintainer on Gentoo, and I would like to know if bootstrapping go via gccgo is supported, and what the official way of doing this is.

- How should I set GOROOT_BOOTSTRAP?

- What about the go binary that should be used to build? Is there a variable that can be set to define it?

Thanks much,

William

**Comment by ALTree** [comment]
AFAIK the process is just something like "use the binary at `$GOROOT_BOOTSTRAP/bin/go`". 

So I would just set up a folder structure like `gccgo-bootstrapping/bin/go` and make `go` point to the gccgo binary. And then try to bootstrap. Does this work?
