### ISSUE TITLE
x/crypto/ssh: Support sha-2 family hash algorithms for key exchange (RFC 8268)

### ISSUE THREAD

**Issue by breml** [golang/go#31731]
### Feature Request: Add support for sha-2 family hash algorithms for key exchange (RFC 8268)

Due to concerns with SHA-1 and with MODP groups with less than 2048 bits, [RFC 8268](https://tools.ietf.org/html/rfc8268) suggests to add 5 new key exchange algorithms:

* `diffie-hellman-group14-sha256`
* `diffie-hellman-group15-sha512`
* `diffie-hellman-group16-sha512`
* `diffie-hellman-group17-sha512`
* `diffie-hellman-group18-sha512`

Currently, non of these new key exchange algorithms is present in x/crypto/ssh. For `diffie-hellman-group14-sha256` the RFC states it SHOULD be supported to smooth the transition to newer group sizes.

**Comment by hanwen** [comment]
But why? There are a number of more modern kexes based on elliptic curves, which are faster to process and (AFAIK) as secure.

**Comment by bcmills** [comment]
CC @hanwen @FiloSottile
