### ISSUE TITLE
cmd/compile: Go 1.13 language changes not rejected in go1.12 mode

### ISSUE THREAD

**Issue by rsc** [golang/go#31747]
`go tool compile -lang=go1.12` should probably be diagnosing (rejecting) use of the new Go 1.13 language features like signed shifts and the new number literals. That way people who have `go 1.12` in their go.mod files can be more confident that the code does build with Go 1.12.

/cc @ianlancetaylor @griesemer

**Comment by dmitshur** [comment]
Would that apply in all .go files, even ones with `// +build go1.13` build constraints?

An implication of doing this would be that, for example the [`go-cmp`](https://github.com/google/go-cmp) module that currently has a `go 1.8` directive in its [go.mod file](https://github.com/google/go-cmp/blob/6f77996f0c42f7b84e5a2b252227263f93432e9b/go.mod#L3), would not be able to use new Go 1.13 language features, even in .go files with a `// +build go1.13` build constraint. /cc @dsnet

Is that an intended consequence? Is it unavoidable for modules that want to support more than 1 version of Go, or is `go-cmp` using a suboptimal value for the `go` directive (i.e., perhaps it should start using 1.12 or 1.13 once that's out).

**Comment by rsc** [comment]
This is independent of build tags. It's a little confusing but build tags are really about the specific release you are _actually_ compiling with (usually for things like library features), while the go line is about what version of Go-the-language your source code intends to use. (It would be nice to do more for the library but that's future work at best.)

Discussed with @griesemer and @ianlancetaylor; Robert will check on it. Accepted.
