### ISSUE TITLE
How to get *interface{} of field in struct.

### ISSUE THREAD

**Issue by shihaonan369** [golang/go#31756]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.11.4

</pre>

### Does this issue reproduce with the latest release?

Not an issue, just a question.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/shihaonan/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/shihaonan/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5y/tg5wtlx9255g3mfhp8g0fzn80000gn/T/go-build386392868=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

[https://play.golang.org/p/3GtnyYYrjlM](https://play.golang.org/p/3GtnyYYrjlM)
Run code will Throw a panic:
"panic: reflect: reflect.Value.Set using unaddressable value"
I know change the type of i from interface{} to *interface{} could be right, but how to get *interface{} of field in struct?

**Comment by bcmills** [comment]
You can't get a `*interface{}`, but you can get a pointer as the `interface{}` by invoking the `Addr` method:
https://play.golang.org/p/MfUr0Bb4-sY
