### ISSUE TITLE
cmd/go: go get -x prints to stdout

### ISSUE THREAD

**Issue by heschik** [golang/go#31768]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +08318f5942 Tue Apr 30 20:30:30 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What did you do?
`go list -x -v -m -e -json --versions android.googlesource.com/platform/tools/gpu.git@latest 2> /dev/null`

### What did you expect to see?
Just JSON, i.e. 
```
{
	"Path": "android.googlesource.com/platform/tools/gpu.git",
	"Version": "v0.0.0-20150804144629-269101c4a73c",
	"Time": "2015-08-04T14:46:29Z"
}
```

### What did you see instead?
Some stray -x output on stdout, which breaks JSON parsing:
```
cd .
git ls-remote https://android.googlesource.com/platform/tools/gpu
{
	"Path": "android.googlesource.com/platform/tools/gpu.git",
	"Version": "v0.0.0-20150804144629-269101c4a73c",
	"Time": "2015-08-04T14:46:29Z"
}
```

**Comment by hyangah** [comment]
@gopherbot please consider this for backport to 1.12. This prevents parsing of go command output
