### ISSUE TITLE
cmd/go/internal/lockedfile: use F_OFD_SETLK on Illumos

### ISSUE THREAD

**Issue by bcmills** [golang/go#31765]
See the TODO here:
https://github.com/golang/go/blob/f686a2890b34996455c7d7aba9a0efba74b613f5/src/cmd/go/internal/lockedfile/internal/filelock/filelock_fcntl.go#L16-L19

The `illumos` tag was added in https://golang.org/cl/174457 (for #20603), so the TODO can now be done. It should be pretty straightforward.

CC @jclulow @jayconrod @bradfitz

**Comment by jclulow** [comment]
Can we add an `OS-illumos` label for issues like this one?

**Comment by bradfitz** [comment]
@jclulow, done.

**Comment by bcmills** [comment]
Fixed in [CL 255258](https://golang.org/cl/255258).
