### ISSUE TITLE
cmd/go: misleading error message

### ISSUE THREAD

**Issue by go101** [golang/go#31775]
### What version of Go are you using (`go version`)?

```
go version devel +ba978f5fff Tue Apr 30 23:31:26 2019 +0000 linux/amd64
```

### What did you do?

```
module example.com/myapp v2.0.0
```

```
go build
```

### What did you expect to see?

```
go: errors parsing go.mod:
/tmp/foo/go.mod:1: usage: module module/path
```

### What did you see instead?

```
go: errors parsing go.mod:
/tmp/foo/go.mod:1: usage: module module/path [version]
```

**Comment by katiehockman** [comment]
Hi @go101, could you please provide more context here? It would be helpful if you could run `go env` and give the output, as well as give more context about what exactly you think is misleading/missing about the current error message.

**Comment by go101** [comment]
`go env` doesn't help for this issue.

What I mean is the error message indicates that a version is allowed to be specified in the `module` directive, but in fact, it is not allowed.
