### ISSUE TITLE
x/tools/cmd/callgraph: pta algorithm fails with internal error

### ISSUE THREAD

**Issue by rootAvish** [golang/go#31787]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12.1
</pre>

### What operating system and processor architecture are you using (`go env`)?
MacOS Mojave, amd64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/avgupta/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/avgupta/golang"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9k/_rqr9c3564vfgzh1x2d8ndzh0000gn/T/go-build929933793=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

- Clone the kubernetes/kubernetes repo as with `go get -d k8s.io/kubernetes`, mine was at revision 8f5a62af48d707eab9acd557a4b7366acb42dcf4

- Build, with `make`

- Try to build the callgraph with pta algorithm, as with:
```
$ callgraph -algo=pta ./cmd/hyperkube
```

### What did you expect to see?

A callgraph, also the output said I should report this bug.

### What did you see instead?

<details>Error output<pre>
^Internal panic in pointer analysis:
goroutine 1 [running]:
runtime/debug.Stack(0x24, 0x0, 0x0)
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/debug/stack.go:16 +0x22
golang.org/x/tools/go/pointer.Analyze.func1(0xc1dff3dc90)
	/Users/avgupta/golang/src/golang.org/x/tools/go/pointer/analysis.go:227 +0x10b
panic(0x12e7ec0, 0xc0e9e1e2a0)
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9
golang.org/x/tools/go/pointer.(*analysis).taggedValue(0xc0807e88c0, 0xc0000e3e2f, 0x2, 0x64, 0xc046d1c000)
	/Users/avgupta/golang/src/golang.org/x/tools/go/pointer/gen.go:272 +0x12a
golang.org/x/tools/go/pointer.(*invokeConstraint).solve(0xc075471420, 0xc0807e88c0, 0xc1ee6d08c0)
	/Users/avgupta/golang/src/golang.org/x/tools/go/pointer/solve.go:317 +0x239
golang.org/x/tools/go/pointer.(*analysis).solveConstraints(0xc0807e88c0, 0xc11a676870, 0xc1ee6d08c0)
	/Users/avgupta/golang/src/golang.org/x/tools/go/pointer/solve.go:165 +0x170
golang.org/x/tools/go/pointer.(*analysis).solve(0xc0807e88c0)
	/Users/avgupta/golang/src/golang.org/x/tools/go/pointer/solve.go:59 +0x2e0
golang.org/x/tools/go/pointer.Analyze(0xc0a2b0b9a0, 0x0, 0x13badc0, 0xc0e9e1e2c0)
	/Users/avgupta/golang/src/golang.org/x/tools/go/pointer/analysis.go:331 +0x4ce
main.doCallgraph(0x0, 0x0, 0x0, 0x0, 0x7ffeefbff690, 0x3, 0x136ef07, 0x3f, 0xc000072000, 0xc0000761a0, ...)
	/Users/avgupta/golang/src/golang.org/x/tools/cmd/callgraph/main.go:233 +0x32d
main.main()
	/Users/avgupta/golang/src/golang.org/x/tools/cmd/callgraph/main.go:159 +0xa5
callgraph: internal error in pointer analysis: not a tagged object: n933423 (please report this bug)
</details></pre>

**Comment by bcmills** [comment]
CC @ianthehat

**Comment by adonovan** [comment]
x/tools/go/pointer was deleted; see #59676.
