### ISSUE TITLE
x/tools/cmd/gopls: add implementation for textDocument/didSave

### ISSUE THREAD

**Issue by myitcv** [golang/go#31796]
<pre>
$ go version
go version go1.12.4 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20190429181656-7af746645d51
</pre>

Per discussions with @ianthehat, if we add an implementation for `textDocument/didSave` we can implement logic within that method to invalidate the `gopls` cache when new imports are added to a package. i.e. we can check whether the imports in the file that was just saved are a subset of the current package cache and invalidate if not.

This will remove a category of "failures" with respect to completions returning no results.

**Comment by stamblerre** [comment]
Closing this, as the above CL added an implementation of didSave, and the memoization related changes (upcoming) will handle invalidating the `gopls` cache using a different mechanism.
