### ISSUE TITLE
regexp/syntax: [\s\S] -> string is unparsable

### ISSUE THREAD

**Issue by hanwen** [golang/go#31807]
### What version of Go are you using (`go version`)?

go 1.12
 
### Does this issue reproduce with the latest release?

yes.

### What operating system and processor architecture are you using (`go env`)?

playground

### What did you do?

See https://play.golang.org/p/ss5UUhg98GU

### What did you expect to see?

I expect regexp to be able to parse back what syntax.Regexp.String() output.

### What did you see instead?

"[^]a": error parsing regexp: missing closing ]: `[^]a`

**Comment by hanwen** [comment]
this is causing https://github.com/google/zoekt/issues/82

**Comment by mvdan** [comment]
Slightly simpler reproducer: https://play.golang.org/p/6prqe3xt2lT

**Comment by junyer** [comment]
https://github.com/golang/go/blob/3813edf26edb78620632dc9c7d66096e5b2b5019/src/regexp/syntax/regexp.go#L142-L154

RE2 had a similar problem, but I fixed it just now in https://github.com/google/re2/commit/cd23be77c716bf75ebb3ddc07fa3ef0c943da6d2. ;)
