### ISSUE TITLE
x/tools/cmd/gopls: add support for handling deltas in DidChange

### ISSUE THREAD

**Issue by myitcv** [golang/go#31800]
This is a tracking issue for adding support for handling deltas in `textDocument/didChange`.

https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#didchangetextdocument-notification-arrow_right

Currently clients are required to send the entire file contents for each change. This starts to get noticeable for large-ish files.

cc @stamblerre @ianthehat

**Comment by ianthehat** [comment]
If you set `incrementalSync=true' in the [initialize](https://microsoft.github.io/language-server-protocol/specification#initialize) params it will be enabled. We will enable it by default when we have reasonable confidence that it works properly (I have had it enabled for a while now and it seems to be okay)

**Comment by myitcv** [comment]
Thanks - I'm still waiting on a change on the Vim side to be able to do this (without workarounds) https://github.com/vim/vim/issues/4191
