### ISSUE TITLE
x/build/cmd/gopherbot: who is suppose to be congratulated?

### ISSUE THREAD

**Issue by tomocy** [golang/go#31805]
Does this code means as commented or not to congratulate before 2017/06/17 in UTC??
https://go.googlesource.com/build/+/refs/heads/master/cmd/gopherbot/gopherbot.go#1051

**Comment by bradfitz** [comment]
The purpose was to not spam people with "Congrats!" retroactively on things that happened in the past. This was important when we first rolled out this feature of the bot.

See how that variable is used in the code below.
