### ISSUE TITLE
x/tools/imports: don't prepend std/ to packages from GOROOT

### ISSUE THREAD

**Issue by bradfitz** [golang/go#31814]
In #31769 goimports added `"std/go/token"` for me. (Because I used a new API only in master and not yet recognized by the goimports fast path)

And in https://go-review.googlesource.com/c/go/+/175099/ I got a failure:

https://storage.googleapis.com/go-build-log/0c3a1672/freebsd-amd64-12_0_de6f6ad5.log
```
ok  	context	1.249s
ok  	crypto	0.006s
ok  	crypto/aes	0.020s
# crypto/cipher
package crypto/cipher_test
	imports std/internal/testenv: unknown import path "std/internal/testenv": cannot find module providing package std/internal/testenv
FAIL	crypto/cipher [setup failed]
ok  	crypto/des	0.007s
ok  	crypto/dsa	0.004s
2019/05/02 22:10:18 Failed: exit status 1
```

because goimports added `"std/internal/testenv"`.

We need to remove the `std/` prefixes.

**Comment by mvdan** [comment]
I had the same happen to me while I was working on the `go/token` CL itself, but I figured I was using goimports wrong :)
