### ISSUE TITLE
runtime: linux/arm64 sigtramp seems wrong

### ISSUE THREAD

**Issue by coypoop** [golang/go#31827]
As I understand it:
- Go doesn't have callee-saved registers
- Even if the normal C ABI does.
- This is true on arm64 as well.
- A Go signal handler may be called when running C code

darwin/arm64 runtime.sigtramp  saves callee-saved registers (r19-r27, g aka r28, r29) for this scenario
https://github.com/golang/go/blob/59ea685ce96a696281e56badd80d2e5dd618b0b0/src/runtime/sys_darwin_arm64.s#L152-L163

linux/arm64 sigtramp does not do this. 
https://github.com/golang/go/blob/59ea685ce96a696281e56badd80d2e5dd618b0b0/src/runtime/sys_linux_arm64.s#L319-L337

I don't have a reproducer for this bug (or a setup for it), but it seems wrong.
Tell me your thoughts.

**Comment by ianlancetaylor** [comment]
Yes, clearly `sigtramp` in runtime/sys_linux_arm64.s must save all callee-saved registers.

Same for sys_openbsd_arm64.s and sys_netbsd_arm64.s.

Thanks for pointing this out.

CC @4a6f656c

**Comment by Zheng-Xu** [comment]
I doubt there is really need to save/restore the registers in `sigtramp`. We shouldn't allow the C code to call Go functions directly without going through CGO. It is true that `A Go signal handler may be called when running C code`. But it is not called from C code directly. It is actually called from kernel. Kernel will preserve the context anyway.

I think the question should be: Why we save/restore those registers on darwin system? Is it necessary?

**Comment by 4a6f656c** [comment]
@ianlancetaylor - I don't see why this would be necessary. When a signal is delivered the kernel preserves all of the register state in the trap frame, restoring all of the (possibly modified) register state on return from the signal handler. In the case of OpenBSD/arm64, see `sendsig()` and `sys_sigreturn()` in:

http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/sys/arch/arm64/arm64/sig_machdep.c?rev=1.6

This is fairly standard behaviour - NetBSD is effectively the same via `cpu_getmcontext()` and the setcontext system call:

http://cvsweb.netbsd.org/bsdweb.cgi/src/sys/arch/aarch64/aarch64/sig_machdep.c?rev=1.1.28.2

I would expect Linux to do the same.

**Comment by ianlancetaylor** [comment]
@4a6f656c This is not a theoretical problem.  Signal handlers are used in many different ways by different programs.  See #18328.

**Comment by 4a6f656c** [comment]
@ianlancetaylor - fair enough, one could argue that the signal forwarding code should be preserving and restoring context (as the kernel would). I guess saving/restoring is the safe solution, although at a cost for the normal/non-forwarding case.
