### ISSUE TITLE
x/build/gerrit: quota issues accessing golang.org/x/sys

### ISSUE THREAD

**Issue by myitcv** [golang/go#31826]
Raising as a result of https://groups.google.com/d/msg/golang-dev/LggZwiBTIvc/7kN0w_krAQAJ

I'm seeing the following in my Travis logs; not running a large number of builds here, at most 4 in parallel:

```
go: golang.org/x/sys@v0.0.0-20190429190828-d89cdac9e872: git fetch -f
origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in
/home/travis/gopath/pkg/mod/cache/vcs/76a8992ccba6d77c6bcf031ff2b6d821cf232e4ad8d1f2362404fbd0a798d846:
exit status 128:
remote: RESOURCE_EXHAUSTED Resource has been exhausted (e.g. check quota).
[type.googleapis.com/google.rpc.QuotaFailure]
violations {
 subject: "IP 104.154.113.151"
 description: "Short term bandwidth rate limit exceeded"
}
fatal: protocol error: bad pack header
```

cc @dborowitz @hanwen @tparker (per @bradfitz)

**Comment by myitcv** [comment]
Started seeing it ~1 hour ago. I'm attempting ~4 parallel builds every ~10 mins trying to fix a build failure. I've seen the failure ~5 times in total. 

If it's relevant, there also appear to be some connectivity issues from Travis to GitHub; I'm seeing timeouts accessing https://raw.githubusercontent.com/ URLs (suspect however this is very much unrelated, but I report it here for completeness)

**Comment by tparker** [comment]
This was a quota denial. It looks like you generated some bursty activity. Quota buckets refill every 5 seconds, so an exponential backoff retry strategy should keep builds making steady progress.

This looks like unauthenticated access, which has a smaller quota than authenticated access. Can you say more about the environment in which these builds are running?

**Comment by bradfitz** [comment]
> Can you say more about the environment in which these builds are running?

At the top he mentioned Travis. Travis is https://travis-ci.org/. It's a popular TAP/Sponge-ish thing for non-Googlers.

**Comment by tparker** [comment]
We had special configuration for Travis IP addresses to give more quota, but our list was out-of-date. We just updated it so your Travis machines should have more quota going forward.

**Comment by jrn** [comment]
https://docs.travis-ci.com/user/encrypting-files/ allows passing in a credential without exposing it to the public. But then your build has access to that credential, which likely defeats the purpose.

Sorry for the trouble. The quota increase @tparker mentioned grants each Travis instance the same quota as ordinary authenticated users get; if that's not sufficient, we can increase it more.

**Comment by dmitshur** [comment]
Based on https://github.com/golang/go/issues/31826#issuecomment-489270494, this should be resolved now. I'll close this, but if the issue persists, please feel free to re-open and provide more information so we can investigate further.

Thank you @myitcv for reporting this and @tparker and others for resolving this.

**Comment by myitcv** [comment]
Thanks all.
