### ISSUE TITLE
x/crypto/ssh/terminal: MakeRaw returns the <nil> oldstate  on windows , and pop "The handle is invalid"

### ISSUE THREAD

**Issue by kenzhaoyihui** [golang/go#31831]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
Not Sure

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
C:\Users\zz>go env
set GOARCH=amd64
set GOHOSTARCH=amd64
...

### What did you do?

</pre>
use the ssh/terminal to do the  interacting ssh command

### What did you expect to see?

</pre>
successfully

**Comment by odeke-em** [comment]
Thank you for reporting this issue @kenzhaoyihui and welcome to the Go project!

It would be great @kenzhaoyihui if you could paste in here a minimal reproducer which
can make it easy to debug and diagnose the issue. Also the template requests this. Please
provide this.

In the meantime, I shall kindly page @hanwen

**Comment by hanwen** [comment]
I am not responsible for the terminal package.
