### ISSUE TITLE
cmd/trace: debugging support like PySnooper?

### ISSUE THREAD

**Issue by guanw** [golang/go#31847]
This isn't an issue regarding golang itself but would be a nice addition to have.

I notice in Python now there's a really nice debugging library [PySnooper](https://github.com/cool-RR/PySnooper). It uses notion of trace from `sys.settrace` to fire up callback when codes are running so you could monitor/log everything ongoing. 

Golang already has a notion of trace but the meaning is bit different from what python had here. I think a tool similar to PySnooper would be particularly helpful for new developers who's learning Golang. Since you are much more experienced with Golang than I am, I'm wondering if you guys think it's a good idea to make a similar module and if so what are some of the existing modules that could help achieve the goal here?(e.g something similar to `sys.settrace` that provides a nice callback) Thanks in advance for any ideas and recommendations here!

**Comment by bcmills** [comment]
Probably the closest equivalent in the Go standard library is the [`runtime/trace`](https://tip.golang.org/pkg/runtime/trace/) package.

Please have a look at that package and let us know which (if any) of your use-cases it doesn't address well.

**Comment by guanw** [comment]
@bcmills Thanks for the reply. Yeah I did check out `runtime/trace` package. I think the idea here is to log variable changes in pretty format without any outside interruption for developers.(You'd still have to manually call `trace.Log` in this case which is not ideal). So I'm not sure this is enough.

**Comment by bcmills** [comment]
Since Go is a compiled language, something like that would presumably require deep compiler support.

A project that large probably ought to go through the [proposal process](https://golang.org/s/proposal-process), in which case it would need a lot more detail: what should the API look like, how would we implement it, and how important is the underlying use-case in relation to the other large projects in the issue backlog?

(Or, if you don't want to work it out in that much detail, a description of the general use-case would probably be more helpful as an [experience report](https://github.com/golang/go/wiki/ExperienceReports#diagnostics-and-debugging) instead.)

**Comment by guanw** [comment]
Cool. I will write something when I have time. Thanks for the info here.

**Comment by bcmills** [comment]
I'll close this issue for now, but do feel free to file a proposal if/when you're ready. 🙂

**Comment by guanw** [comment]
@bcmills I made a draft here: https://github.com/guanw/go-proposal/blob/master/proposal.md. Could you let me know if it's unclear/incomplete and maybe link it to golang's experience report? Thanks.

**Comment by bcmills** [comment]
@guanw thanks, but more detail would still be helpful. Per http://golang.org/wiki/ExperienceReports:

> **The best experience reports tell: (1) what you wanted to do, (2) what you actually did, and (3) why that wasn’t great, illustrating those by real concrete examples, ideally from production use.**

**Comment by guanw** [comment]
> @guanw thanks, but more detail would still be helpful. Per http://golang.org/wiki/ExperienceReports:
> 
> > **The best experience reports tell: (1) what you wanted to do, (2) what you actually did, and (3) why that wasn’t great, illustrating those by real concrete examples, ideally from production use.**

Updated. Please check again. Thanks.

**Comment by bcmills** [comment]
Added to the wiki. Thanks!
