### ISSUE TITLE
Rename GO111MODULE

### ISSUE THREAD

**Issue by webern** [golang/go#31844]
This is a bad name for an environment variable. I have to do a web search every time to remember exactly what it is. It should be renamed to GOMOD or GOMODULE.

**Comment by bradfitz** [comment]
Sorry, but it's a temporary name, so any problem will fix itself soon enough once the default change. Changing it would cause more problems by breaking people. And recognizing more than 1 would cause undue complexity, and break people using the new alias with older versions. Not worth it. Anybody bewildered with the name can choose to not live in experimental land.
