### ISSUE TITLE
cmd/vet: initialize an external context is regarded as context leak?

### ISSUE THREAD

**Issue by SilverRainZ** [golang/go#31856]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/la/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/la/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/la/git/tools/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build166721615=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Variables context, cancel are declared at toplevel,  function `Foo` is used to to initialize them,
Indeed this code is quite poor, but is it really fine to be regard as an error?

https://play.golang.org/p/fHQ_fEu0GLW

### What did you expect to see?

`go vet` reports nothing.

### What did you see instead?

`go vet` reports lostcancel error:

```
/home/la/git/tools/main.go:11:2: the cancel function is not used on all paths (possible context leak)
/home/la/git/tools/main.go:12:1: this return statement may be reached without using the cancel var defined on line 11
```

**Comment by josharian** [comment]
cc @alandonovan @mvdan

**Comment by alandonovan** [comment]
Seems like a bug in the analyzer. If the cancel variable has package scope (x.Parent() == x.Pkg().Scope()) it should suppress the finding.

**Comment by SilverRainZ** [comment]
@alandonovan `(x.Parent() == x.Pkg().Scope())` is just a special case for the aboved case. In my opinion,  the fundamental reason is that lostcancel should skip the analysis for cancel which defined outside current function because the analysis is limited to function scope, what do you think?

This case also complained by go vet, but looks more reasonable:

```go
// Test for Go issue 31856.
func _() {
	var cancel func()

	func() {
		_, cancel = context.WithCancel(bg)
	}()

	cancel()
}
```
I have filed a PR, should fix this issue.

**Comment by SilverRainZ** [comment]
@andybons The related PR is merged, this issue shouldn't be labled as `NeedsInvestigation` and may can be closed.

**Comment by agnivade** [comment]
In future, you can write "Fixes golang/go#xxxx" if you want CLs to automatically close issues when they are merged.
