### ISSUE TITLE
cmd/dist: delete GOROOT/pkg/obj after bootstrap

### ISSUE THREAD

**Issue by josharian** [golang/go#31851]
Quoting src/cmd/dist/build.go:

```go
	// Use a build cache separate from the default user one.
	// Also one that will be wiped out during startup, so that
	// make.bash really does start from a clean slate.
	os.Setenv("GOCACHE", pathf("%s/pkg/obj/go-build", goroot))
```

We should delete this build cache once bootstrapping is complete; it serves no further purpose that I can see. At tip, it is 189mb, which accounts for 28% of the size of a built GOROOT.

This adds up for folks like me who use tools (compilecmp, toolstash-check) that generate new GOROOTs like candy.

cc @bradfitz @bcmills to correct me if I am wrong about wanting to delete this

**Comment by mvdan** [comment]
I assume this is already being deleted from binary releases?

**Comment by josharian** [comment]
Also pkg/bootstrap, for another 86mb.
