### ISSUE TITLE
x/exp/sumdb: package rename causes go get to fail

### ISSUE THREAD

**Issue by shakeel** [golang/go#31865]
### What version of Go are you using (`go version`)?

<pre>
go version go1.12.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
I have not tried to reproduce it with 1.12.4 or ToT of the master branch.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/shakeel/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/shakeel/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build134252151=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Sometime ago, I had done a go get on exp packages
go get -u golang.org/x/exp/...

I did a go get -u after the the following CL https://go.googlesource.com/exp/+/7da06db65df0ed3340347289c3f44e04ca68231f mov notary to sumdb

### What did you expect to see?
go get -u reports no failures

### What did you see instead?
<pre>
package golang.org/x/exp/notary/internal/note: cannot find package "golang.org/x/exp/notary/internal/note" in any of:
	/usr/local/go/src/golang.org/x/exp/notary/internal/note (from $GOROOT)
	/home/shakeel/go/src/golang.org/x/exp/notary/internal/note (from $GOPATH)
package golang.org/x/exp/notary/internal/notecheck: cannot find package "golang.org/x/exp/notary/internal/notecheck" in any of:
	/usr/local/go/src/golang.org/x/exp/notary/internal/notecheck (from $GOROOT)
	/home/shakeel/go/src/golang.org/x/exp/notary/internal/notecheck (from $GOPATH)
package golang.org/x/exp/notary/internal/tlog: cannot find package "golang.org/x/exp/notary/internal/tlog" in any of:
	/usr/local/go/src/golang.org/x/exp/notary/internal/tlog (from $GOROOT)
	/home/shakeel/go/src/golang.org/x/exp/notary/internal/tlog (from $GOPATH)
</pre>

However a second go get -u works as expected and reports no failures.

This could be due to work in progress or it might be an edge case of failure when packages are moved.

**Comment by dmitshur** [comment]
`go get -u` failing in GOPATH mode on first time, but succeeding on second time has come up before (e.g., issue #9224) and was resolved.

> Sometime ago, I had done a go get on exp packages [...]

If you can provide a way to reproduce this failure, then this issue can be more actionable. That'll help us know if this is a rare edge case that few people will run into, or something more widespread.

**Comment by shakeel** [comment]
This CL documents the changes made to rename notary to sumdb. https://go.googlesource.com/exp/+/7da06db65df0ed3340347289c3f44e04ca68231f%5E%21/ 

Here are the steps to reproduce
Setup go package with this tree https://go.googlesource.com/exp/+/2cc83dd57ac10eaf754bf2f90254364862360727
Then do go get -u on it
Update the package with this tree
https://go.googlesource.com/exp/+/7da06db65df0ed3340347289c3f44e04ca68231f/
Then do go get -u on it.
You should be able to see the error.

**Comment by shakeel** [comment]
CL #173737 https://go-review.googlesource.com/c/exp/+/173737/4

**Comment by seankhliao** [comment]
I don't think there's anything to do here (GOPATH get was removed).
