### ISSUE TITLE
unable to distribute binary-only package

### ISSUE THREAD

**Issue by srimanster** [golang/go#31877]
### What version of Go are you using (`go version`)?
go version go1.11.5 windows/amd64
### Does this issue reproduce with the latest release?
Yes
### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=C:\Users\vemsr03\go\bin
set GOCACHE=C:\Users\vemsr03\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\vemsr03\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\vemsr03\AppData\Local\Temp\go-build867270282=/tmp/go-build -gno-record-gcc-switches
### What did you do?
I have to built a binary-only package and want to distribute the package to customers. I have done all the required changes to build a binary-only package and tested locally , everything works fine. I have also added cross compilation support for the package(linux and windows) and bundled  the required ".a" and also ".go" and make it useful.

### What did you expect to see?
I expected that the bundle can be used everywhere and we can access the exposed functions of the package.

### What did you see instead?
I am seeing the below error when i tried to access the package in a different machine where my Go version is (go1.10.8 linux/amd64). 
./cmd.go:15:2: import /root/go/pkg/linux_amd64/github.com/ESD/goprobe.a: object is [linux amd64 go1.11.5 X:framepointer] expected [linux amd64 go1.10.8 X:framepointer]

Can you help in resolving this?

**Comment by mvdan** [comment]
When you use binary-only packages, the Go versions must match exactly. I believe Go plugins have a similar limitation. I don't think this has any possible fix, and binary-only packages are being dropped in 1.13 anyway.

**Comment by srimanster** [comment]
@mvdan  Thank You...!!!
