### ISSUE TITLE
cmd/go: go.mod and go.sum are written with mode 0600

### ISSUE THREAD

**Issue by adg** [golang/go#31871]
I noticed that the `go.mod` and `go.sum` files in my projects written with 0600 permissions (readable and writable only by the owner).

```
-rw-------    1 adg  eng   2487 May  6 17:02 go.mod
-rw-------    1 adg  eng  29364 May  6 17:02 go.sum
```

This is a bit unusual; I would have expected them to be written with `0644` (also readable to group and others), like all the other regular files in my Git repo.

I tracked this down to being a side-effect of the `cmd/go/internal/renameio` package, which first creates the files with `ioutil.TempFile`, which calls `OpenFile` with mode `0600` (a perfectly reasonable thing to do when creating a file in a system temporary directory).

If this behavior is deemed undesirable (and that's my opinion) then I think the fix is to have `renameio` call `Chmod` on the file after moving it out of the temporary directory.

cc @bcmills

**Comment by bradfitz** [comment]
I likewise suspect this wasn't intentional.

**Comment by bcmills** [comment]
It was not intentional. I used `ioutil.TempFile` assuming that an explicit `dir` argument would create the file using the default umask for that `dir`, but it doesn't: for some reason it masks the permission to `0600`.

Probably the fix is to just stop using `ioutil.TempFile`.
