### ISSUE TITLE
+build tags not honored

### ISSUE THREAD

**Issue by jinfengnarvar** [golang/go#31878]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/Users/jinfeng/dev/narvar/go/bin"
GOCACHE="/Users/jinfeng/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jinfeng/dev/narvar/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jinfeng/dev/narvar/NarvarGolangApps/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x2/6yhw9qq129gffvpx90dv5gyw0000gp/T/go-build705269767=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Here is the package structure and file content:

<pre>
$ tree
.
├── n1.go
└── n2.go

0 directories, 2 files
$ cat n1.go 
package ntest

func DoSomething() error {
    return nil
}
$ cat n2.go 
// +build ignore

package ntest

func DoSomething() error {
    return nil
}
$ go build *.go
# command-line-arguments
./n2.go:5:6: DoSomething redeclared in this block
	previous declaration at ./n1.go:3:20
$
</pre>

### What did you expect to see?
`go build *.go` succeeds

### What did you see instead?
`go build *.go` failed

**Comment by mvdan** [comment]
See `go help packages`. I'm pretty sure this has been raised multiple times before.

```
As a special case, if the package list is a list of .go files from a
single directory, the command is applied to a single synthesized
package made up of exactly those files, ignoring any build constraints
in those files and ignoring any other files in the directory.
```
