### ISSUE TITLE
cmd/compile: possible issue in optimization of -(c+-x)

### ISSUE THREAD

**Issue by josharian** [golang/go#31888]
amd64.rules contains this rule:

```
(NEGQ (ADDQconst [c] (NEGQ x))) && c != -(1<<31) -> (ADDQconst [-c] x)
```

It was added in https://go-review.googlesource.com/c/go/+/38311/.

I don't understand the constraint `c != -(1<<31)`: Why it is necessary at all, and if it is necessary, why it isn't say `-(1<<63)`. If it does need to be `-(1<<63)`, then we may be generating bad code. As such, tentatively marking Go 1.13.

cc @randall77

**Comment by randall77** [comment]
`ADDQconst` on x86 requires that `c` be an `int32`.

That's why the restriction is there, so that we don't generate an `ADDQconst` of `1<<31` (which is invalid) from an `ADDQconst` of `-1<<31` (which is valid).

**Comment by josharian** [comment]
Ah! Thanks.
