### ISSUE TITLE
x/tools/go/analysis/cmd/vet: delete this program

### ISSUE THREAD

**Issue by rsc** [golang/go#31886]
`go tool vet` and `golang.org/x/tools/go/analysis/cmd/vet` should have the same set of checks but today do not. It looks like the x/tools version adds atomicalign, errorsas, and nilness. 

If any of these are not ready to go into std (and nilness seems to be called out explicitly as not for std), they should not be in the x/tools vet either. (If the x/tools vet is going to intentionally diverge from cmd/vet, we should avoid confusion by naming it something different from `vet`.)

```
$ go tool vet help >vet.help 2>&1
$ /tmp/xvet help >xvet.help 2>&1
$ diff vet.help xvet.help
1c1
< vet is a tool for static analysis of Go programs.
---
> xvet is a tool for static analysis of Go programs.
3c3
< vet examines Go source code and reports suspicious constructs,
---
> xvet examines Go source code and reports suspicious constructs,
12a13
>     atomicalign  check for non-64-bits-aligned arguments to sync/atomic functions
17a19
>     errorsas     report passing non-pointer or non-error values to errors.As
21a24
>     nilness      check for redundant or impossible nil comparisons
46a50,51
>   -atomicalign
>     	enable atomicalign analysis
64a70,75
>   -cpuprofile string
>     	write CPU profile to this file
>   -debug string
>     	debug flags, any subset of "fpstv"
>   -errorsas
>     	enable errorsas analysis
74a86,87
>   -memprofile string
>     	write memory profile to this file
78a92,93
>   -nilness
>     	enable nilness analysis
96a112,113
>   -trace string
>     	write trace log to this file
111c128
< To see details and flags of a specific analyzer, run 'vet help name'.
---
> To see details and flags of a specific analyzer, run 'xvet help name'.
$ 
```

/cc @matloob @ianthehat

**Comment by letientai299** [comment]
@andybons I would like to help unblock this release-blocker. Right now, compare between master of go and tools report, `go vet` don't have `atomicalign` and `errorsas`. Does the decision is to add the 2 checks to `go vet`?

**Comment by ianthehat** [comment]
I believe the decision was to just delete `golang.org/x/tools/go/analysis/cmd/vet`.

Adding new checks to `go vet` at this point in the release process is not something we should do without a very compelling reason, especially as we have not done any analysis to see if they are reliable enough.

**Comment by letientai299** [comment]
> I believe the decision was to just delete golang.org/x/tools/go/analysis/cmd/vet.

I don't think so. This [CL 181717](https://go-review.googlesource.com/c/go/+/181717) is merged today, for adding `errorsas` to `vet`.

**Comment by matloob** [comment]
I agree with the hat.

We've planned to add errorsas a while ago. I think it's better to proceed with caution than to add a new analyzer.

We should delete the vet tool in tools: it's a safer thing to do, especially in the freeze.

**Comment by qbradq** [comment]
@gopherbot please add label NeedsDecision

**Comment by ianlancetaylor** [comment]
@ianthehat @matloob It sounds like you feel that someone should delete this program.  Could one of you do that soon, so that it can be in the 1.13 release?  Thanks.

**Comment by ianthehat** [comment]
x/tools is not actually part of the release, and no changes are needed in the vet that is part of the release, so this is not really a release blocker given the decision to just delete the one in x/tools. I agree we should just get it done anyway though.
Assigning to @matloob
