### ISSUE TITLE
cmd/cgo: C Structs with the same field definitions are used interchangeably in generated prototypes

### ISSUE THREAD

**Issue by kesmit13** [golang/go#31891]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nd/fslycqgs2m54077zvlwx158h000464/T/go-build014851518=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

If I use the following struct definitions in functions exported by cgo, the 
struct names get mixed up in the generated h file.

#### Input h File
<pre>
typedef struct {
    char *objtype;
    unsigned long long obj;
} Connection;

typedef struct {
    char *objtype;
    unsigned long long obj;
} Error;

typedef struct {
    char *objtype;
    unsigned long long obj;
} CASValueList;
</pre>

#### Exported Function Definitions
<pre>
func casConnectionDestroy(c *C.CASConnection) { ... }
func casErrorDestroy(e *C.CASError) { ... }
</pre>

### What did you expect to see?

I expected the generated prototypes to look like the following.

<pre>
extern void casConnectionDestroy(CASConnection* p0);
extern void casErrorDestroy(CASError* p0);
</pre>

### What did you see instead?

There are the prototypes that were generated instead.

<pre>
extern void casConnectionDestroy(CASValueList* p0);
extern void casErrorDestroy(CASValueList* p0);
</pre>

### Observation

I suspected that some sort of hashing was being used to alias structs that
had the same fields, so I added a unique field to each of the structs in the 
input header file and that did solve the problem.

**Comment by odeke-em** [comment]
Thank you for filing this change @kesmit13 and welcome to the Go project!

Since Ian on CL https://golang.org/cl/181857 added this to wait-release, I shall accordingly move the milestone to Go1.14 so perhaps please except a fix to land after August 2019.
