### ISSUE TITLE
x/mobile: Getting undefined reference while generating binding using gomobile

### ISSUE THREAD

**Issue by jay11ca39** [golang/go#31905]
### What version of Go are you using (`go version`)?

<pre>
$ go version: go1.12.4 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
GOBIN="/usr/local/go"
GOCACHE="/home/--/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="My Go path"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build242944229=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
1. I have go package, I am trying to generate go binding for that using gomobile tool.
    (a)  **gomobile bind -o my.aar -target=android  mygopackage**

2. Details about my go package [**mygopackage**]:
    (a) $ tree
          ├── file.go
          └── res.c

    (b) Details about **file.go**:   
         (i) I am including my **res.c**  
         (ii) I am just redirecting my function call to c file.

    (c) Details about my **res.c** file: 
         (i)  I am including one header for getting interfaces: **#include <ifaddrs.h>** : 
              **http://man7.org/linux/man-pages/man3/getifaddrs.3.html**
               and I am calling one API: getifaddrs()
   
**Issue:** 
While generating the go mobile binding it is giving **undefined reference** : 
$ gomobile bind -o my.aar -target=android mygopackage

> gomobile: go build -buildmode=c-shared -o=/tmp/gomobile-work-063445150/android/src/main/jniLibs/armeabi-v7a/libgojni.so gobind failed: exit status 2
> '#mygopackage'
> src/mygopackage/res.c:15: **error: undefined reference** to 'getifaddrs'
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have browsed all issues but no issue is related to this.

**Comment by jay11ca39** [comment]
Hello eliasnaur 
Can you please help me out in this

**Comment by jay11ca39** [comment]
As per my analysis this symbol is present in **"libc"** library. But I am not sure how gomobile internally links "libc" while we run gomobile tool to generate .aar file.

**Comment by eliasnaur** [comment]
According to a quick Google search, getifaddrs is not available before Android API level 24. Gomobile builds with a lower API level (21 if I remember correctly). You should be able to work around the issue while maintaining Android compatibility by using dlopen and dlsym to access getifaddrs.

**Comment by AlexRouSg** [comment]
@eliasnaur is there anything preventing android from having a command line arg to set the API level? I saw IOS has one and find it weird android doesn't.

**Comment by jay11ca39** [comment]
@AlexRouSg ,
I was not aware of that. I thought those are exposed to application.
Then, may be the issue is API level while using gomobile bind. 

@eliasnaur and @AlexRouSg 
As currently we can not give the API level on command line while using gomobile bind command, Is there is any way to manually change the API level in code and rebuild and test?

**Comment by jay11ca39** [comment]
@AlexRouSg ,
I thought, those will be available to application.

@eliasnaur  and @AlexRouSg 
As currently, there is no way to pass the API level from the command line in gomobile bind. 
Can API level be set manually in the gomobile code ?

**Comment by jay11ca39** [comment]
@AlexRouSg ,
I thought those will be available to apps. I did not find any doc saying that it is introduced in API 8.

@eliasnaur ,
As currently, gomobile bind command is not taking command line argument for API-Level. 
Is there is any way to set manually in gomobile code to set API level and build it..

**Comment by AlexRouSg** [comment]
@jay11ca39 

https://github.com/golang/go/issues/31905#issuecomment-490454156

> if you want to implement it, look at https://github.com/golang/mobile/blob/master/cmd/gomobile/env.go#L311 and https://github.com/golang/mobile/blob/master/cmd/gomobile/build.go#L220

"it" referring to the api version command line arg.

**Comment by jay11ca39** [comment]
https://github.com/golang/go/issues/31905#issuecomment-490545005

**Comment by AlexRouSg** [comment]
@jay11ca39 what is that last comment suppose to mean? You asked how to get gomobile to use a different API level and I told you where to start looking.

**Comment by jay11ca39** [comment]
Hello @eliasnaur
I have one **basic** query regarding build gomobile source code: 

1. go get golang.org/x/mobile/cmd/gomobile

2. Then, i have taken the changes from https://golang.org/cl/176077

3. Now, **I want to rebuild the gomobile.** 

I did not find steps to build gomobile code from source code. 

Can you, let me know how to to build from source ?

**Comment by jay11ca39** [comment]
https://github.com/golang/go/issues/31905#issuecomment-490931657
@eliasnaur @AlexRouSg  @andybons 
Can anybody please provide views on how to build from source? so that I can verify whether given patch solved this issue or not.

**Comment by AlexRouSg** [comment]
Anything you can obtain with `go get` is just a normal Go program/package, so you just build it the same way you build any normal Go program/package. 

Please see https://golang.org/doc/code.html#remote

But the changes have been merged, this means you can `go get -u golang.org/x/mobile/cmd/gomobile` to update.

**Comment by eliasnaur** [comment]
You should be able to just run go install `golang.org/x/mobile/cmd/...` after applying the change.

**Comment by jay11ca39** [comment]
Thanks @eliasnaur , @AlexRouSg  for all your help and suggestions.

I am able to build my code using **-androidapi** command line flag introduced in: https://go-review.googlesource.com/c/mobile/+/176077
