### ISSUE TITLE
cmd/go: GOPROXY list should not terminate on non 404/410 errors

### ISSUE THREAD

**Issue by amnonbc** [golang/go#31913]
The new GOPROXY list feature allows the specification of a series of proxies. If the first one returns a 404/410 status, we will try to fetch from the next one.

But if any other error is returned, e.g. a 500, then the search will terminate and the download will fail.
This limits our ability to use multiple proxies to improve make importing more robust and allow downloads to succeed even if a subset of the proxies are down or misbehaving.

We also can not rely on proxies to be well behaved in the errors they return. The athens proxy returns a 500 status if it can not authenticate against the upstream repository. This should of course be fixed in athens. But it would be useful if this feature allows us to work around such problems.

**Comment by bcmills** [comment]
A 500 error indicates that the server for some reason didn't know how to handle the request. We have no way to determine whether it would have rejected the module or simply didn't know about it. In that case, there is a conservative (privacy-preserving) option, which is to assume that it would have rejected it, and an aggressive (error-tolerant) option, which is to assume that the proxy simply didn't know about it.

For a comma-separated list of proxies in `GOPROXY`, we have chosen the option that biases toward preserving the privacy of paths. That was discussed and decided on #26334, and absent new information (such as empirical observations of the reliability of generally-available proxy implementations), I don't think we should revisit that decision.

If you want to compose multiple proxies using some other policy, it should be fairly trivial to write a local `GOPROXY` server that implements whatever error behavior you like.

**Comment by bcmills** [comment]
See [related discussion](https://go-review.googlesource.com/c/go/+/173441/4#message-5eb2aa3e9f0d98b60705706b169b943cbc531d93) on CL 173441 (#26334).

**Comment by beoran** [comment]
In our proxy I made it so that it returns 404 if the upstream repo couldn't be checked out, exactly because of this way go works. So the current behavior of go helps proxy developers to do the Right Thing (tm). I think  Athens should make the same fix, it's really normally just small a 15 minutes fix.
