### ISSUE TITLE
all: run 'go vet std' during run.bash, disable vetall builder

### ISSUE THREAD

**Issue by rsc** [golang/go#31916]
What the vetall builder does - run go vet on std and tell us about problems - is valuable, but hiding that in a builder makes it too easy to be surprised when it breaks. It would be better if we ran 'go vet' during run.bash (maybe during 'go test', maybe separately), so that the problems are surfaced before you get all the way to sending CLs out. Doing this would require first cleaning up std to be vet-safe.

I intend to chip away at this.

**Update**: Based on discussion below, my concrete suggestion is:
 - [x] Fix all the vet issues in GOROOT so there are no whitelists left.
 - [ ] Make 'go test' on packages in GOROOT run all vet checks, not just the usual subset.
   This will help people catch problems on their native GOOS/GOARCH during regular development.
 - [ ] Make sure misc-compile\* trybots have complete GOOS/GOARCH coverage.
 - [ ] Make those trybots also run vet for their GOOS/GOARCH.
   This will help keep detecting build breakages, which is a side effect of the current vetall builder.
 - [ ] Retire the vetall builder.

**Comment by ianlancetaylor** [comment]
For what it's worth, where the vetall builder always catches me is other `GOARCH` `GOOS` values.

**Comment by bradfitz** [comment]
What Ian said. I think that's why Josh added it, too.

Don't we already run `go vet std` effectively via in run.bash by running the tests? The only ones where we don't might be the packages that lack tests.

/cc @josharian

**Comment by josharian** [comment]
In addition to what Ian said, 'go vet' doesn't run all the vet checks; the vetall builder does. That's why there is still a set of whitelists, despite 'go vet' running on all packages in std as part of 'go test'.

To be clear, I'm definitely in favor of fixing things so that the whitelists eventually disappear, moving vet checks to places that they always get run (https://github.com/golang/go/issues/17544), etc.

These comments about why we have a vetall builder are to help clarify scope.

**Comment by rsc** [comment]
> Don't we already run go vet std effectively via in run.bash by running the tests? 

> 'go vet' doesn't run all the vet checks; the vetall builder does. That's why there is still a set of whitelists, despite 'go vet' running on all packages in std as part of 'go test'.

'go vet' _does_ run all the vet checks, exactly the same ones that the misc-vet-vetall builder does.
But 'go test' does not. Quoting `go help test`:

```
As part of building a test binary, go test runs go vet on the package
and its test source files to identify significant problems. If go vet
finds any problems, go test reports those and does not run the test
binary. Only a high-confidence subset of the default go vet checks are
used. That subset is: 'atomic', 'bool', 'buildtags', 'nilfunc', and
'printf'. You can see the documentation for these and other vet tests
via "go doc cmd/vet". To disable the running of go vet, use the
-vet=off flag.
```

I am thinking that either we make `go test` in std run all the vet checks instead of the subset, or we make all.bash run a separate `go vet std cmd` (the latter takes 37 seconds on my laptop right now, which suggests to me there is a bug somewhere; it should be essentially free).

> For what it's worth, where the vetall builder always catches me is other GOARCH GOOS values.

Sure, but that's true of all the builders. If the vet checks are running as part of all.bash, then the builder responsible for the GOOS/GOARCH you broke will report it, like any other system-specific breakage.

**Comment by rsc** [comment]
To understand the value that the vetall builder is providing, I searched in groups/golang-codereviews for trybot failures where misc-vet-vetall failed by itself or with only one other builder and looked at all the ones I found back to April 1.

There were 4 real vet reports that affected what I judged to be the native GOOS/GOARCH the CL sender would have been using for all.bash or go test; obviously these would be better to surface on the local machine.

There were 2 real vet reports that affected a non-native GOOS/GOARCH. Assuming the CL sender built the code, we could think about surfacing those in go build, or else a misc-compile builder.

There were 2 broken builds of a non-native GOOS/GOARCH. Those reports have an incredibly low SNR (because they report the build problem, the build stops early, and then they list all the expected-but-not-found vet errors) and would be better coming from a misc-compile builder.

There were 16 failures that were the builder being misconfigured or otherwise mysteriously broken. Much of that was due to the module default change, but that is still an example of how the current integration is too awkward.

Real vet report for native GOOS/GOARCH
 - https://storage.googleapis.com/go-build-log/e8224a4c/misc-vet-vetall_277b691d.log (unkeyed fields)
 - https://storage.googleapis.com/go-build-log/f7cd8091/misc-vet-vetall_4f23ac21.log (func+0(SB) bug)
 - https://storage.googleapis.com/go-build-log/9ee73d27/misc-vet-vetall_110a072b.log (solaris asm)
 - https://groups.google.com/forum/#!searchin/golang-codereviews/misc-vet-vetall|sort:date/golang-codereviews/QZk9bHph9A4/wzuo2ittCQAJ (openbsd asm)

Real vet report for non-native GOOS/GOARCH
 - https://storage.googleapis.com/go-build-log/60fb6d81/misc-vet-vetall_7780b921.log (s390x asm)
 - https://storage.googleapis.com/go-build-log/1701a31e/misc-vet-vetall_f67ad242.log (arm asm)

Broken build of non-native GOOS/GOARCH
 - https://storage.googleapis.com/go-build-log/9842c437/misc-vet-vetall_0349a43c.log (dragonfly/amd64)
 - https://storage.googleapis.com/go-build-log/ee4d3a33/misc-vet-vetall_17fa6275.log (plan9/arm)

Broken/flaky builder:
 - https://storage.googleapis.com/go-build-log/f59c7124/misc-vet-vetall_22a45053.log
 - https://storage.googleapis.com/go-build-log/d004be1a/misc-vet-vetall_96722d15.log
 - https://storage.googleapis.com/go-build-log/8fdf4208/misc-vet-vetall_f0e06a99.log
 - https://storage.googleapis.com/go-build-log/e95fd27b/misc-vet-vetall_d0892f32.log
 - https://storage.googleapis.com/go-build-log/83680dcf/misc-vet-vetall_5b1c9f96.log
 - https://storage.googleapis.com/go-build-log/8ae62732/misc-vet-vetall_ccd96fe2.log
 - https://storage.googleapis.com/go-build-log/e8aefd0a/misc-vet-vetall_8b917fa1.log
 - https://storage.googleapis.com/go-build-log/7122b50a/misc-vet-vetall_1c54b37e.log
 - https://storage.googleapis.com/go-build-log/c98fc4a0/misc-vet-vetall_7099ef79.log
 - https://storage.googleapis.com/go-build-log/d325a7a6/misc-vet-vetall_be1b1252.log
 - https://storage.googleapis.com/go-build-log/dc2e7bac/misc-vet-vetall_961d63f0.log
 - https://storage.googleapis.com/go-build-log/7e35e585/misc-vet-vetall_62a2e315.log
 - https://storage.googleapis.com/go-build-log/3c521277/misc-vet-vetall_c4c555f5.log
 - https://storage.googleapis.com/go-build-log/0109e66a/misc-vet-vetall_df40efce.log
 - https://storage.googleapis.com/go-build-log/cb001a47/misc-vet-vetall_4860f931.log
 - https://storage.googleapis.com/go-build-log/427c525d/misc-vet-vetall_2eddc49b.log

**Comment by rsc** [comment]
Added note in top comment about concrete plan based on discussion.

**Comment by bradfitz** [comment]
@rsc, updated plan LGTM. I assume the misc-compile-*'s added vet checks would also vet the tests for those ports? If so, that would address #20119 at the same time.

**Comment by rsc** [comment]
Why do we run vet in cmd/compile/internal/gc/testdata? That seems like it would be a place full of things vet would not like (and it is, of course). What are we trying to catch by running vet?

**Comment by josharian** [comment]
> Why do we run vet in cmd/compile/internal/gc/testdata?

Historical accident, I believe.

When I wrote `cmd/vet/all`, `go tool vet` was dramatically faster than `go vet`, but it required directories. I don't know why I didn't ignore all directories containing `testdata`...but instead I wrote:

```
// ignorePathPrefixes are file path prefixes that should be ignored wholesale.
var ignorePathPrefixes = [...]string{
	// These testdata dirs have lots of intentionally broken/bad code for tests.
	"cmd/go/testdata/",
	"cmd/vet/testdata/",
	"go/printer/testdata/",
}
```

I believe that `cmd/compile/internal/gc/testdata` was added later, and whitelist entries added for it.

We should probably now do I what I should have done ages ago and systematically ignore `testdata`.

**Comment by rsc** [comment]
OK, thanks. When the check moves to 'go test' (or 'go vet std cmd' in buildall.bash for misc-compile) we'll ignore that directory at no extra charge. As of right now it's the only thing left in the whitelist directory.
