### ISSUE TITLE
cmd/go: timing out on plan9/amd64 builder

### ISSUE THREAD

**Issue by 0intro** [golang/go#31910]
The cmd/go tests are timing out on the plan9/amd64 builder.

```
ok  	cmd/fix	49.968s

communication error to buildlet (promoted to terminal error): network error promoted to terminal error: runTests: dist test failed: all buildlets had network errors or timeouts, yet tests remain
```

or

```
ok  	cmd/fix	51.528s

##### 
Test "go_test:cmd/go" ran over 20m0s limit (20m0.12161669s)
```

See https://build.golang.org/log/0f96baaa7cfaa1c3546adceb7e49553d88a99ac7 or https://build.golang.org/log/520cd0eb6a7941d1591537b1604a06e6ebabfdc5

This is related to issue #29822 (plan9/386 builder).

**Comment by bcmills** [comment]
This issue is many years old. Is it still relevant?
