### ISSUE TITLE
x/build: GitHub rate limit exceeded for various tools

### ISSUE THREAD

**Issue by andybons** [golang/go#31919]
gopherbot can't make any calls to GitHub and gerritbot logs are showing that our quota is getting drained very quickly.

@bradfitz @dmitshur

**Comment by andybons** [comment]
I've disabled gopherbot, gitmirror, and gerritbot for now. There is a repeated error from gopherbot I'm looking into.

**Comment by dmitshur** [comment]
> repeated error from gopherbot

That might be related to issue #28320.

**Comment by andybons** [comment]
maintnerd looks to be the reason why our quota keeps getting exhausted, as it got stuck in a loop. We're out of quota again so it's another hour or so at least before that and any other dependent services are available.

**Comment by dmitshur** [comment]
We've identified this is connected to the incorrect timing information recorded on some GitHub comments posted a few hours ago. GitHub has said the issue has been fixed, and they're in process of correcting inaccurate timestamps:

https://twitter.com/githubstatus/status/1126171459255185414

The current inaccurate timestamps are causing maintnerd to take incorrect actions and use up its rate limit quota. After another hour passes (unless GitHub corrects the incorrect timestamps even sooner), those comments will no longer be in the future and maintnerd should be able to run okay. So we're currently waiting a bit more.

**Comment by bradfitz** [comment]
@dmitshur, did you figure out what the problem in maintnerd was?

I saw this log line a bunch:

```go
func (p *githubRepoPoller) syncComments(ctx context.Context) error {
        for {
                nums := p.issueNumbersWithStaleCommentSync()
                if len(nums) == 0 {
                        return nil
                }
                remain := len(nums)
                for _, num := range nums {
                        p.logf("comment sync: %d issues remaining; syncing issue %v", remain, num)
```

But I never saw the log from the code that immediately follows:

```go
                        if err := p.syncCommentsOnIssue(ctx, num); err != nil {
                                p.logf("comment sync on issue %d: %v", num, err)
                                return err
                        }
                        remain--
                }
        }
}
```

So `issueNumbersWithStaleCommentSync` kept returning the same number, but then it ran without returning an error, over and over. It is just:

```go
        for n, gi := range p.gr.issues {
                if !gi.commentsSynced() {
                        issueNums = append(issueNums, n)
                }
        }
```

And `commentsSynced` is just:

```go
func (gi *GitHubIssue) commentsSynced() bool {
        if gi.NotExist {
                // Issue doesn't exist, so can't sync its non-issues, 
                // so consider it done.
                return true
        }
        return gi.commentsSyncedAsOf.After(gi.Updated)
}
```

That `commentsSyncedAsOf` field of `GithubIssue` is:

```go
        commentsSyncedAsOf time.Time                   // as of server's Date header
```

That's written to from:

```go
func (c *Corpus) processGithubIssueMutation(m *maintpb.GithubIssueMutation) {
....
        if m.CommentStatus != nil && m.CommentStatus.ServerDate != nil {
                if serverDate, err := ptypes.Timestamp(m.CommentStatus.ServerDate); err == nil {
                        gi.commentsSyncedAsOf = serverDate.UTC()
                }
```

But why didn't make progress before in ...

```go
func (p *githubRepoPoller) syncCommentsOnIssue(ctx context.Context, issueNum int32) error {
```

Because of this GitHubIssue field?

```go
    commentsUpdatedTil time.Time       // max comment modtime seen
```

And syncCommentsOnIssue does:

```go
        since := issue.commentsUpdatedTil
        p.c.mu.RUnlock()

        owner, repo := p.gr.id.Owner, p.gr.id.Repo
        morePages := true // at least try the first. might be empty.                                                                                                                                                    
        for morePages {
                ics, res, err := p.githubDirect.Issues.ListComments(ctx, owner, repo, int(issueNum), &github.IssueListCommentsOptions{
                        Since:       since,
                        Direction:   "asc",
                        Sort:        "updated",
                        ListOptions: github.ListOptions{PerPage: 100},
                })
```

.... but, uh, where is `commentsUpdatedTil` ever updated?

```
bradfitz@go:~/src/golang.org/x/build$ git grep commentsUpdatedTil
maintner/github.go:     commentsUpdatedTil time.Time                   // max comment modtime seen
maintner/github.go:     if gi.commentsUpdatedTil.After(ret) {
maintner/github.go:             ret = gi.commentsUpdatedTil
maintner/github.go:     since := issue.commentsUpdatedTil
```

Never?

Um.

**Comment by dmitshur** [comment]
I misread one of the lines as `gi.commentsUpdatedTil = ret`, so I thought it was possible for it to get updated. You're right, it always has the zero value and never gets set to anything else. That was the case since the CL that added it ([CL 38137](https://golang.org/cl/38137)). This issue must've been elsewhere.

**Comment by dmitshur** [comment]
We're in the process of turning on `maintnerd` and other related services now.

**Comment by dmitshur** [comment]
We've recovered all services from this outage by now.

**Comment by dmitshur** [comment]
This specific outage has been resolved, and this issue isn't actionable, so I'll close it. We can open new issues if there is specific work that needs to be done.
