### ISSUE TITLE
misc/cgo/test: internal linking now fails on openbsd/arm64

### ISSUE THREAD

**Issue by 4a6f656c** [golang/go#31940]
openbsd/arm64 passes all tests successfully prior to d2765de, however with that commit the misc/cgo/test now fails with:

```shell
##### ../misc/cgo/test                                                                                           
PASS               
ok      misc/cgo/test   184.359s
# misc/cgo/test.test                                                                                             
/tmp/go-build512157972/b053/_pkg_.a(_x002.o): unknown relocation type 299; compiled without -fpic?
FAIL    misc/cgo/test [build failed]                                                                             
2019/05/08 12:23:39 Failed: exit status 2
```

This occurs on the `-linkmode=internal` run of this test and is reproducible via:

```shell
$ cd src/misc/cgo/test
$ GOFLAGS=-ldflags=-linkmode=internal go test -c
```

I haven't yet tracked down the failure/fix, however it is worth noting that openbsd/arm64 uses clang and hence this may also result on other platforms when clang is in use.

**Comment by ianlancetaylor** [comment]
Relocation 299 is `R_AARCH64_LDST128_ABS_LO12_NC`.  That may need to be added to the switch in `relSize` in cmd/link/internal/loadelf/ldelf.go.  Likely we'll also need some code for the reloc in cmd/link/internal/arm64/asm.go.

**Comment by erifan** [comment]
@4a6f656c Do you want me to add this relocation ? It's easy to do, but I don't have a Openbsd test environment.

**Comment by 4a6f656c** [comment]
@ianlancetaylor - thanks for the pointers.

@erifan - I've just mailed https://go-review.googlesource.com/c/go/+/176697 which allows openbsd/arm64 to pass all tests again.
