### ISSUE TITLE
cmd/compile/internal/ssa: build/test failures on openbsd/arm (limited memory)

### ISSUE THREAD

**Issue by 4a6f656c** [golang/go#31941]
The openbsd/arm builder has limited memory and the platform has a limited data size - builds are now frequently failing either during the build of `cmd/compile/internal/ssa` or during the build of the tests for the same package:

```
Building Go toolchain1 using /home/gopher/src/go-bootstrap.                                                                                                                                                                      
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.                                                                                                                                                                     
# cmd/compile/internal/ssa
fatal error: runtime: out of memory
```

See also builder logs:

https://build.golang.org/log/62e7db1dc3e13bbbf7aa0f0efa0e42c3021c6229

https://build.golang.org/log/f3a479db1e71e96d1921f97fcb2cf2eb7e13bb01

**Comment by josharian** [comment]
Possible dup of https://github.com/golang/go/issues/27739

**Comment by 4a6f656c** [comment]
It is likely a dup, however worth noting that Go built fine on the same builder around Go 1.12 and the issue has gradually gotten worse (first the odd test time build failure, now regular build time failures) - in other words it has regressed between Go 1.12 and current.

**Comment by josharian** [comment]
I'm going to transfer that observation into #27739, where there is active work ongoing, and close this one as a dup.
