### ISSUE TITLE
Operator =+ compiles correctly and performs an assignment

### ISSUE THREAD

**Issue by skrynauw** [golang/go#31956]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build933389805=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/UgB5VmyvwEl

### What did you expect to see?
Expected to get a compilation error on the line:
equalsPlus =+ value

### What did you see instead?
The operator =+ assigns the value

**Comment by skrynauw** [comment]
I understand that =+ is parsed as a unary + operator and thus just shows the value to be positive, but it might be valuable to throw a compilation error if possible.

A mistyped += as =+ has big consequences in this case

**Comment by ALTree** [comment]
Thanks for the report.

`x=+3` is perfectly valid syntax, so we definitely cannot make it compilation error. That would break the Go 1 compatibility promise.

Closing this issue as I don't think it's possible (and useful) to do this.

**Comment by dominikh** [comment]
gofmt formats it as `equalPlus = +value` making this much less of an issue.

**Comment by skrynauw** [comment]
Thanks for the replies, agreed that with gofmt it is a lot more obvious
