### ISSUE TITLE
io.Copy will lost some data

### ISSUE THREAD

**Issue by suliang** [golang/go#31957]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\suliang\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Go\;E:\gostudy\;E:\gostudy\bin;
set GOPROXY=
set GORACE=
set GOROOT=D:\Go
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\suliang\AppData\Local\Temp\go-build657753758=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
I copy a file by io.Copy

code:
`
	

	oldfile := "E:/aa.txt"		// size: 6K
	newfile := "E:/bb.txt"		// When program done,  this file size: 4K
    FileOld,_ := os.Open(oldfile)
	reader := bufio.NewReader(FileOld)

	FileNew,_ := os.OpenFile(newfile, os.O_WRONLY | os.O_CREATE | os.O_TRUNC, 0666)
	writer := bufio.NewWriter(FileNew)

	io.Copy(writer, reader) 
    /// When the program has been executed, new file size is 4K , but old file size is 6K

`

### What did you expect to see?
I expect , newfile(bb.txt) size is 6K, 
Because oldfile size is 6K

### What did you see instead?
But newfile size is 4K

**Wen I use io.Copy to copy a file, I find, new file's size less than old file's size
I uesd many files to tried many times, find a rule :**

if old file size % 4K == 0
No problem
if old file size % 4K > 0
new file can be lost some data

The lost data is old file's end data
The lost data's size is old file's size % 4K

So I tracking code, I find
in bufio.go, some codes write counter

**bufio.io: line 739**

When if b.Available() == 0
Because file's size % 4k == 0
So not use Flush

When if b.Available() > 0
Because file's size % 4k > 0
So must to be Flush

I have submitted a pull request to fix this bug:
[https://github.com/golang/go/pull/31953](https://github.com/golang/go/pull/31953)

**Comment by AlexRouSg** [comment]
https://golang.org/pkg/bufio/#Writer

> the client should call the Flush method to guarantee all data has been forwarded to the underlying io.Writer.

You didn't call `writer.Flush() `

**Comment by suliang** [comment]
I think I don't need call write.Flush() by myself
Because  io.Copy is a packaged function
Tracking source code, you will find:
The Flush method is encapsulated inside
and look bufio.io: line 739
and please Read carefully my issue

**Comment by ianlancetaylor** [comment]
You do need to call `Flush`, as documented.  This is true whether you are use `io.Copy` or not.  `io.Copy` will copy all data from the reader to the writer, but it does not promise to flush the writer.  The fact that it does flush the writer in some cases does not mean that you do not have to call `Flush` yourself.

The documentation says

> After all data has been written, the client should call the Flush method to guarantee all data has been forwarded to the underlying io.Writer.

which seems clear and does not have any exception like "unless you used `io.Copy`".

**Comment by AlexRouSg** [comment]
Would making a one word change, `should call` to `must call`, maybe help when taking into consideration translators and/or non native speakers?

**Comment by suliang** [comment]
@ianlancetaylor 
if eyery time , I mush call Flush after io.Copy
Please look
bufio.io: line 738~743
What these code mean? 
is it mean : At the end of the file, the program can call Flush,to write the last data to the file ?

**Comment by openset** [comment]
@suliang `b.Available() == 0` mean  the buffer filled exactly. If more than one file need to read or some string need to write too, the writer.buffer can also use,  because it not filled.this just i understand.

**Comment by suliang** [comment]
@openset Are you Chinese? Can I talk about you by Chinese?  What's your Email

**Comment by openset** [comment]
@suliang 可以使用 GitHub 邮箱

**Comment by ianlancetaylor** [comment]
The point of these lines in bufio.go:

```Go
	if err == io.EOF {
		// If we filled the buffer exactly, flush preemptively.
		if b.Available() == 0 {
			err = b.Flush()
		} else {
			err = nil
		}
	}
```

is that we don't want to return `io.EOF` to the caller.  So we have to change `io.EOF` to `nil`.  While we're doing that, there is a small optimization: if the buffer is full, we flush it immediately, so that the next `Write`, if there is one, will be faster.

**Comment by networkimprov** [comment]
@suliang you can also write:
```
_, err = io.Copy(FileNew, FileOld)
```

**Comment by andybons** [comment]
Closing as this is clearly documented and no behavior is broken.
