### ISSUE TITLE
net/http: allow concurrent requests with different Transport proxy

### ISSUE THREAD

**Issue by windzhu0514** [golang/go#31952]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOOS=windows
</pre></details>

### What did you do?

there is one transport in my program 
several goroutine send get request with same url 
when one request return 403 , i change the proxy 

### What did you expect to see?
every goroutine can use it own proxy
it seems transport.Proxy is not safe for concurrent

### What did you see instead?

the proxy in other goroutine  request is also change 

example code 
```go
package main

import (
	"io/ioutil"
	"log"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/signal"
	"syscall"
	"time"
)

func main() {
	log.SetFlags(log.Lshortfile | log.Ldate | log.Ltime)
	client := &http.Client{
		Transport: &http.Transport{
			//Proxy: http.ProxyFromEnvironment,
			DialContext: (&net.Dialer{
				Timeout:   5 * time.Second,
				KeepAlive: 30 * time.Second,
			}).DialContext,
			MaxIdleConns:          100,
			IdleConnTimeout:       90 * time.Second,
			TLSHandshakeTimeout:   10 * time.Second,
			ExpectContinueTimeout: 1 * time.Second,
		},
	}

	go func() {
		req, _ := http.NewRequest(http.MethodGet, "https://www.google.com", nil)
		client.Transport.(*http.Transport).Proxy = func(request *http.Request) (url *url.URL, e error) {
			return url.Parse("http://10.101.32.12")
		}
		response, err := client.Do(req)
		if err != nil {
			log.Println(err)
			return
		}

		defer response.Body.Close()
		data, _ := ioutil.ReadAll(response.Body)
		log.Println(string(data))
	}()

	go func() {
		req, _ := http.NewRequest(http.MethodGet, "https://www.google.com", nil)
		client.Transport.(*http.Transport).Proxy = func(request *http.Request) (url *url.URL, e error) {
			return url.Parse("http://10.101.32.13")
		}
		response, err := client.Do(req)
		if err != nil {
			log.Println(err)
			return
		}

		defer response.Body.Close()
		data, _ := ioutil.ReadAll(response.Body)
		log.Println(string(data))

	}()

	chOver := make(chan os.Signal, 1)
	signal.Notify(chOver, syscall.SIGINT, syscall.SIGTERM)
	<-chOver
}
```

i want each request use it's own proxy

**Comment by andybons** [comment]
Can you show example code?

@bradfitz

**Comment by windzhu0514** [comment]
i have add some example code @bradfitz

**Comment by bradfitz** [comment]
Correct; you cannot set Transport.Proxy from two concurrent goroutines, just like how you can't set anything else concurrently from two concurrent goroutines.

Your Transport.Proxy function should be set before any concurrent use and then it should consult its `request *http.Request` input to make its routing decision.

**Comment by sinylei** [comment]
@windzhu0514 , Hi, buddy, I met exactly the same issue, I have a proxy pool, for each http request I will choose one proxy from the pool. With only one HttpClient, proxy is not concurrent safe.
Have you found any solution? Use different HttpClient for each Proxy?

**Comment by windzhu0514** [comment]
@sinylei the solution i found is writing youself Proxy select func and set transport.Proxy before before any concurrent use.
 erery new request will call the proxy select func
