### ISSUE TITLE
cmd/doc: go doc os.ModTime does not print enough

### ISSUE THREAD

**Issue by rsc** [golang/go#31961]
$ go doc os.ModTime
func ModTime() time.Time  // modification time
$

I am fairly sure there is no top-level ModTime function in os.

**Comment by ianlancetaylor** [comment]
`go doc` has acted like this since 1.8.  This is clearly a bug but I'm not sure it's a release blocker.

**Comment by palmamartin** [comment]
It seems `go doc` shows methods defined on an interface as top-level function if in the package no top-level function with the same name, as the method defined on the interface, exists. 

The os packages does not have a top-level function `ModTime` but it has an interface `os.FileInfo`  in `src/go/types.go` which defines a method `ModTime() time.Time // modification time` which `go doc` shows here.

**Comment by agnivade** [comment]
I think some clarification is needed here

The comment for `symbolDoc` says  

```
// symbolDoc prints the docs for symbol. There may be multiple matches.
// If symbol matches a type, output includes its methods factories and associated constants.
// If there is no top-level symbol, symbolDoc looks for methods that match.
```
And then `printMethodDoc` first searches for a struct type's methods, and then goes to an interface type's methods. Which is what we see here.

So just to clarify-   `go doc os.Sync` gives

```
func (f *File) Sync() error
    Sync commits the current contents of the file to stable storage. Typically,
    this means flushing the file system's in-memory copy of recently written
    data to disk.
 ```

which is correct, but `go doc os.ModTime` is not ?

Should the correct behavior be only to check struct's methods if there is no top-level symbol, or to not check any method at all (in which case, it is even a bigger behavior change) ?

cc @robpike

**Comment by ianlancetaylor** [comment]
`go doc os.ModTime` prints

```
func ModTime() time.Time  // modification time
```

That is clearly wrong, as there is no such function in the os package.

The output of `go doc os.Sync` correctly reports that `Sync` is a method of `File`.
