### ISSUE TITLE
cmd/go: go version stopped getting added to go.mod

### ISSUE THREAD

**Issue by rsc** [golang/go#31960]
I ran some go build commands just now in a new module and there is not a go version in my go.mod. There should be.

/cc @bcmills @jayconrod

**Comment by bcmills** [comment]
That was an intentional change in behavior for #30790.

We now add the `go` directive only in `go mod init` and `go mod tidy`

**Comment by bcmills** [comment]
Per discussion with Russ, we should go with the alternative described in https://github.com/golang/go/issues/30790#issuecomment-472433192: we should always write the `go` version if it isn't present.
