### ISSUE TITLE
x/tools/internal/lsp: ignore builtin.go

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#31962]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +7feb31384a 2019-05-07 13:30:32 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yep

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/home/oneofone/code/go/bin"
GOCACHE="/tmp/.gocache"
GOENV="/home/oneofone/.config/go/env"
GOEXE=""
GOFLAGS="-gcflags=-c=16"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/oneofone/code/go"
GOPROXY="direct"
GOROOT="/usr/src/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/src/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118855782=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Working on a project in vscode.

### What did you expect to see?

no errors in `$GOROOT/src/builtin/builtin.go`

### What did you see instead?

![Screenshot_20190510_104356](https://user-images.githubusercontent.com/1080443/57539653-8d5f1300-7310-11e9-9e90-6a8b51dcde77.png)

**Comment by andybons** [comment]
@stamblerre
