### ISSUE TITLE
cmd/go/internal/modfetch: TestCodeRepo/parallel/gopkg.in_natefinch_lumberjack.v2/v2.1 failing at head

### ISSUE THREAD

**Issue by bcmills** [golang/go#31965]
<strike>Likely another case of #28856, masked by #31263.</strike>

```
[…]
--- FAIL: TestCodeRepo (18.60s)
    --- FAIL: TestCodeRepo/parallel (0.00s)
        --- FAIL: TestCodeRepo/parallel/gopkg.in_natefinch_lumberjack.v2/v2.1 (3.35s)
            coderepo_test.go:386: info.Version = "v2.1.1-0.20170531160350-a96e63847dc3", want "v2.0.0-20170531160350-a96e63847dc3"
[…]
FAIL
FAIL    cmd/go/internal/modfetch        19.588s
```

CC @jayconrod

**Comment by bcmills** [comment]
I don't actually see any tagging changes that explain the failure. Will need to bisect.

**Comment by thepudds** [comment]
> coderepo_test.go:386: info.Version = "v2.1.1-0.20170531160350-a96e63847dc3", want "v2.0.0-20170531160350-a96e63847dc3"

Drive by comment: https://golang.org/cl/174061 or #30634 spring to mind.

But is this an internal test that was passing previously with those changes already in place? (If so, then perhaps not them ;-)

That looks like a "want" non-pseudoversion is now a pseudoversion?

**Comment by bcmills** [comment]
The base for the `want` pseudo-version went from `v2.0.0` to `v2.1.1`.

I'm pretty sure I saw a couple pseudo-version changes go by while I was out, but I'm pretty sure `git bisect` will find it either way. 🙂

**Comment by thepudds** [comment]
That commit seems to have an "almost semver" tag of `v2.1`:

https://github.com/natefinch/lumberjack/tree/v2.1

**Comment by thepudds** [comment]
https://github.com/golang/go/blob/3b8c804164e26bdec6ca94a5ab1b5c35fa119e5e/src/cmd/go/internal/modfetch/codehost/git.go#L681

I think semver.IsValid might accept something like `v2.1` as valid?

Maybe that needs to be `semtag == semver.Canonical(semtag)`, or something like that?

**Comment by bcmills** [comment]
Ooh, that's a good find. Thank you!

**Comment by bcmills** [comment]
`git bisect` points to [CL 174061](https://golang.org/cl/174061), which (as it turns out) is where that call to `semver.IsValid` was added.
