### ISSUE TITLE
cmd/compile: non-100%-reproducible object files

### ISSUE THREAD

**Issue by josharian** [golang/go#31975]
Observed by @dr2chase in [CL 176577](https://golang.org/cl/176577). I have reproduced locally using `for f in `seq 1000`; do go build -o oserr -a internal/oserror; md5 oserr; done` and noting occasional deviations.

I am bisecting now.

**Comment by josharian** [comment]
Drat. Bisected to https://go-review.googlesource.com/c/go/+/170037, which was just when non-trivial code was added to `internal/oserror`. Will bisect again tomorrow.

**Comment by cuonglm** [comment]
@josharian Because https://go-review.googlesource.com/c/go/+/170037 added duplicated anonymous interface, causing build not 100% reproducible.

CL https://go-review.googlesource.com/c/go/+/162240/ tries to fix that problem, +2 but not merge yet.

**Comment by josharian** [comment]
Looks like this is indeed a duplicate of #30202.
