### ISSUE TITLE
x/tools/gopls: completion fails on broken code

### ISSUE THREAD

**Issue by stamblerre** [golang/go#31973]
Context: https://github.com/microsoft/vscode-go/issues/2506

Repro case:

```
var x = []string{fmt.<>}
```

**Comment by muirrn** [comment]
This seems to work fine. I think the linked report didn't work because of the incomplete selector in the previous line:

```go
fmt.
var x = []string{fmt.<>}
```

In this case, the second line is completely missing from the AST, so it is trickier to fix.

**Comment by freeformz** [comment]
Is there a reasonable expectation that completion work if the code above the point at which completion is expected isn't correct (as is the case in the linked vscode-go issue).

**Comment by stagedataloss1** [comment]
test123

**Comment by stamblerre** [comment]
Yes, I think we want to do the most we can to get completion to work, even on broken code. I've added a `gopls-parse` label that we can use to mark such issues.
