### ISSUE TITLE
type switch on error type always selects first custom type

### ISSUE THREAD

**Issue by kstenerud** [golang/go#31985]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes. It also reproduces on play.golang.org

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/karl/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/karl/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/virtual/mounts/tp-dev/Projects/go-cbe/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build623156020=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/V7gUTJqEiwt

### What did you expect to see?

    TEST1 is something else
    TEST2 is a myError

### What did you see instead?

    TEST1 is a myError2
    TEST2 is a myError2

The ordering of the type statements at the top determines which type is selected in the switch statement:

```golang
    type myError2 error
    type myError error
```
Reversing these lines will cause it to identify both errors as type `myError` instead of `myError2`

**Comment by artyom** [comment]
To my understanding this is working as intended: the spec says on [type switches](https://golang.org/ref/spec#TypeSwitchStmt) that they follow tha same logic as [type assertions](https://golang.org/ref/spec#Type_assertions), and for the case of type being interface (as in your case, as error is an interface), type assertions documented to behave like this:

> If T is an interface type, x.(T) asserts that the dynamic type of x implements the interface T.

As your type myError2 is an interface implementing `Error() string` method, first clause of type switch is triggered, as value inspected satisfies this interface.

You may want to reimplement your idea with concrete types for them to work the way you want, or look at the new [errors](https://tip.golang.org/pkg/errors/) package (coming in Go 1.13) or its standalone version at <https://golang.org/x/xerrors>.

Notice that somewhat similar example is given in [Effective Go article](https://golang.org/doc/effective_go.html#interface_conversions), which shows how both concrete type value and interface work in a single type switch.

**Comment by dominikh** [comment]
This is indeed working as intended. See also http://staticcheck.io/docs/checks#SA4020 for a description of the mistake.
