### ISSUE TITLE
cmd/compile: sparse slices with struct items are not initialized

### ISSUE THREAD

**Issue by kdarkhan** [golang/go#31987]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/opt/go-src/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build290432406=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Sparse slices with struct items are not initialized properly.
This test fails on 1.12 but passes on 1.11
```
type container struct {
	Value string
}

func TestSparseSlice(t *testing.T) {
	s := []container {
		7: {Value: "string value"},
	}
	if len(s) != 8 || s[7].Value != "string value" {
		t.Errorf("wanted string=\"string value\", got %s", s[7].Value)
	}
}
```

### What did you expect to see?
7th entry in the slice containing `{Value: "some string"}` and test passing.

### What did you see instead?
All elements in the slice are zero-valued. Reverting the change introduced here https://go-review.googlesource.com/c/go/+/151319/ fixes the issue.

**Comment by ALTree** [comment]
Thanks for the report.

cc @randall77

**Comment by randall77** [comment]
@gopherbot Please open a backport to 1.12.
