### ISSUE TITLE
os: Readlink should return destination even if link is broken

### ISSUE THREAD

**Issue by mfojtik** [golang/go#31996]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPROXY=""
GORACE=""
GOTMPDIR=""
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you do?

When reading a symlink with non-existing target the `os.Readlink` will return empty string and error. That makes reading the path of the target impossible.

For example, if you are in container and use shared PID namespace (which means you share the `/proc`) and you want to get a PID, one way to do so is to follow the `/proc/PID/exe` link.
In case of shared PID namespace, if you don't use the same image for containers sharing the `/proc`, it will return broken link (which is OK). Unfortunately, `os.Readlink` can't be used to get the destination string.

### What did you expect to see?

I want to see the destination of a symlink, even when `os.Readlink` is not able to follow the link. It is fine to return the error, but the destination can be returned as well.
The caller can decide to ignore (or not to ignore) the returned destination.
There should be no breakage to existing code.

### What did you see instead?

The `os.Readlink` return "", error on broken link.

**Comment by andybons** [comment]
@ianlancetaylor @bradfitz

**Comment by ianlancetaylor** [comment]
I'm sorry, I don't understand what you mean.  This program shows an example of reading a symlink whose destination does not exist, and it works without error.

```Go
package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
)

func main() {
	tmpdir, err := ioutil.TempDir("", "readlink")
	if err != nil {
		panic(err)
	}
	defer os.RemoveAll(tmpdir)
	from := filepath.Join(tmpdir, "from")
	to := filepath.Join(tmpdir, "to")
	if err := os.Symlink(to, from); err != nil {
		panic(err)
	}
	fmt.Println(os.Readlink(from))
}
```

**Comment by networkimprov** [comment]
/proc/PID/exe is not a normal symlink; it's a resource of procfs.

This might reproduce it:
```
$ ln /usr/bin/cat ./mycat
$ ./mycat &
$ mypid=$!
$ rm ./mycat
$ ls -l /proc/$mypid/exe // try Go app with os.Readlink() here
$ kill %1
```

**Comment by ianlancetaylor** [comment]
Thanks for the example.  But when I try that on my system, `os.Readlink("/proc/3540/exe")` returns without error.

**Comment by bradfitz** [comment]
@mfojtik, you say you're using `go version go1.12.5 darwin/amd64` but there's no `/proc` on macOS.

What is your environment?
