### ISSUE TITLE
proxy.golang.org: 410 Gone for simple get request

### ISSUE THREAD

**Issue by myitcv** [golang/go#31995]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/home/myitcv/gostuff/src/github.com/myitcv/govim/cmd/govim/.bin"
GOCACHE="/home/myitcv/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPROXY="https://proxy.golang.org/"
GORACE=""
GOROOT="/home/myitcv/gos"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build077283485=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
$ go get github.com/gohugioio/hugo
```

### What did you expect to see?

No error; the latest version of `hugo` to have been "got".

### What did you see instead?

```
go get github.com/gohugioio/hugo: unexpected status (https://proxy.golang.org/github.com/gohugioio/hugo/@v/list): 410 Gone
```

cc @katiehockman

FYI @rogpeppe

**Comment by myitcv** [comment]
🤦‍♂ user error here; there's a typo in `github.com/gohugioio/hugo`; should be `github.com/gohugoio/hugo`

That said, @katiehockman - should this instead be a 404?

If this is working as intended, please close... and accept my apologies for the noise!

**Comment by heschik** [comment]
This is an implementation detail of our HTTP caching. It can cache 410s, but not 404s, and the go command doesn't care which we give, so we we give 410s.

In the next few days you should be able to go to the URL (https://proxy.golang.org/github.com/gohugioio/hugo/@v/list) and see the same error as you'd see without a proxy:
```
not found: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/2e23c98e9a4d18876e6a489dc5e73c9145655dd9761b24724a763f697c1604f2: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
```

but that won't do users a ton of good until something happens with #30748.

Closing as WAI, no worries about the "noise".
