### ISSUE TITLE
cmd/go: dependency only used in test code can not be found

### ISSUE THREAD

**Issue by cloudfstrife** [golang/go#31992]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
I use the latest version 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Cloud.F.Strife\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\go\env
set GOPROXY=
set GORACE=
set GOROOT=D:\go
set GOTMPDIR=
set GOTOOLDIR=D:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\space\testing\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\CLOUDF~1.STR\AppData\Local\Temp\go-build307206806=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
testing code is this 
```
.
|-- fibonacci
|   |-- fibonacci.go
|   `-- fibonacci_test.go
|-- go.mod
`-- go.sum
```
go.mod file

```
module app/testing

go 1.12

require github.com/google/go-cmp v0.3.0 // indirect
```

`fibonacci.go` do not import any module 

`fibonacci/fibonacci_test.go`  import `github.com/google/go-cmp`

```
package fibonacci

import (
        "fmt"
        "testing"

        "github.com/google/go-cmp"
)
```

when i run  `go test -v app/testing/fibonacci` , i got an error:

```
$ go test -v app/testing/fibonacci
# app/testing/fibonacci
fibonacci\fibonacci_test.go:7:2: unknown import path "github.com/google/go-cmp": cannot find module providing package github.com/google/go-cmp
FAIL    app/testing/fibonacci [setup failed]
```

when i run `go mod tidy` , the go-cmp dependency in go.mod disappeared

### What did you expect to see?

did i use go module in wrong way ? what can i do to  resolve this problem?

**Comment by andybons** [comment]
@jayconrod @bcmills

**Comment by jayconrod** [comment]
I think you meant to import `github.com/google/go-cmp/cmp`? There is no package with the path `github.com/google/go-cmp`, though that is the correct module path.

The error message could be a bit clearer. #30723 is the main issue for that.

**Comment by cloudfstrife** [comment]
thanks  a lot
