### ISSUE TITLE
x/tools/gopls: support go.mod files

### ISSUE THREAD

**Issue by stamblerre** [golang/go#31999]
Context: Beginning of https://github.com/golang/go/issues/31712.

Some other features that fall under the umbrella of this issue:
- Detection of the local module (https://github.com/golang/go/issues/32049)
- `textDocument/documentLink` taking the user to the exact version of their dependency (https://github.com/golang/go/issues/35563).

**Comment by myitcv** [comment]
Noting a specific comment that in https://github.com/golang/go/issues/35820 we report that changes to `go.mod` files do not trigger recalculation of diagnostics.

**Comment by stamblerre** [comment]
@ridersofrohan: Do you think we can close this issue?

**Comment by ridersofrohan** [comment]
I think we can 😃

**Comment by stamblerre** [comment]
I'll let you do the honors 🎉

**Comment by segevfiner** [comment]
@stamblerre Was automatic detection of the local module ever implemented, both this and the referenced issue are closed.

P.S. That's kind of a missing thing in the stock goimports, most editors just run it without flags and you have to specifically customize the editor configuration to pass the flag which is obviously different for different projects, it doesn't have a config file or detection logic for it, which is annoying.

**Comment by stamblerre** [comment]
@segevfiner: This issue refers to adding support for various features for `go.mod` in `gopls`. The automatic detection of the module is partially implemented, but not yet complete - https://github.com/golang/go/issues/32394 tracks that work.

As for `goimports`, neither you nor your editor need to run `goimports` directly if you are using `gopls`. All import organization should go through `gopls`. I'm not sure what flag you are referring to specifically - the only one I know that changes per-project is `-local` -- is that what you're referring to? In any case, please open a new issue to continue this discussion.

**Comment by segevfiner** [comment]
I was specifically complaining about standalone goimports not supporting automatic detection of the local import prefix, requiring to supply `-local` to it. I know gopls calls it internally, but I'm not sure if it implemented any such automatic detection either, which is what I'm asking about.

I think the issue you linked is about figuring out module roots independent of editor workspace folder roots?

**Comment by stamblerre** [comment]
Ah I see, thanks for the clarification. This was an umbrella issue so I wasn't sure what feature you were referring to. It seems https://github.com/golang/go/issues/32049 did not cover automatic detection of the local module. I opened https://github.com/golang/go/issues/40660 to restart that discussion - thanks!
