### ISSUE TITLE
x/tools/cmd/godoc: reduce scope to display documentation only, remove the rest of golang.org website

### ISSUE THREAD

**Issue by dmitshur** [golang/go#32011]
The 4th milestone described in https://github.com/golang/go/issues/29206#issuecomment-449134264 was:

> Reduce x/tools/cmd/godoc to be the minimal version (since the website can now be run out of x/website).

Now that the golang.org website is served by the x/website subrepo, progress can be made on this.

This is the issue tracking that task.

**Comment by dmitshur** [comment]
This is the current godoc web server tree:

	http://localhost:6060/		main landing page
	http://localhost:6060/doc/	serve from $GOROOT/doc - spec, mem, etc.
	http://localhost:6060/src/	serve files from $GOROOT/src; .go gets pretty-printed
	http://localhost:6060/cmd/	serve documentation about commands
	http://localhost:6060/pkg/	serve documentation about packages
				(idea is if you say import "compress/zlib", you go to
				http://localhost:6060/pkg/compress/zlib)

I am considering resolving this issue by implementing the following new tree:

	http://localhost:6060/		redirect to /pkg/
	http://localhost:6060/doc/	display a page moved notice
	    (the rest is unchanged)

The http://localhost:6060/doc/ notice would say something like:

> Please find documentation for the Go programming language at https://golang.org/doc/, or use the [`golangorg`](https://golang.org/x/website/cmd/golangorg) command to serve the golang.org website locally.
>
> The golang.org website has moved into the [golang.org/x/website](https://golang.org/x/website) repository. The scope of the `godoc` command is being narrowed to just serving Go package documentation.

/cc @andybons Do you think it's worth also including a link to https://golang.google.cn/doc/ in the "page moved notice" for people who cannot access the golang.org website?

**Comment by dmitshur** [comment]
As I was prototyping a fix for this, it became more clear it should be viable to move more quickly and simply remove the /doc/ tree altogether, without any kind of intermediate message. The reason this should be viable is because we can remove all links to /doc/ from the navigation bar:

![image](https://user-images.githubusercontent.com/1924134/69089874-a874b300-0a16-11ea-878d-527d9a1af178.png)

Since there won't be any links to /doc/, people can't get there. I don't think many people make bookmarks for things at http://localhost:6060.

The new web server tree plan is:

```
http://localhost:6060/		redirect to /pkg/
http://localhost:6060/src/	serve files from $GOROOT/src; .go gets pretty-printed
http://localhost:6060/cmd/	serve documentation about commands
http://localhost:6060/pkg/	serve documentation about packages
			(idea is if you say import "compress/zlib", you go to
			http://localhost:6060/pkg/compress/zlib)
```

**Comment by Li-ReDBox** [comment]
Hi @dmitshur current godoc has lost navigation bar which has caused inconveniences. For example, after viewing the document of one package, I have to change the url to http://localhost:6060/pkg/ in the address bar to go back to the index.

Also, even help, project and etc are reachable, they are not visible.

Are these in transition into x/website?

**Comment by dmitshur** [comment]
@Li-ReDBox Thanks for reporting.

You should still have the option of going to the index by clicking the "Go Documentation Server" text in the top left corner, as before. Additionally, navigating to just http://localhost:6060/ is fine and will redirect you to http://localhost:6060/pkg/ automatically.

> Also, even help, project and etc are reachable, they are not visible.

I don't completely understand, maybe you can elaborate and show a screenshot? This is what you should see:

![image](https://user-images.githubusercontent.com/1924134/76421476-194f2a80-637a-11ea-8115-aea8551e4d5c.png)

If that's not what you're seeing, maybe your `godoc` binary is out of date and needs to be rebuilt?

**Comment by Li-ReDBox** [comment]
Thanks @dmitshur for taking time to reply to me.

Thanks for the tip for going back to package index page. Should have guessed.

I was expecting to see a navigation bar saw in previous versions
![image](https://user-images.githubusercontent.com/3203171/76472225-cdb58300-6444-11ea-965c-0b41aa582da0.png) to give me a convenient way to go to doc page at least. As for doc page, it still exists but if someone runs godoc first time, it is not clear there are lots of useful information accessible locally:
![image](https://user-images.githubusercontent.com/3203171/76472680-34876c00-6446-11ea-9a98-91c072a3c6c8.png)

I am very glad to know godoc will not be removed. It is a very useful tool. Thanks.
