### ISSUE TITLE
cmd/internal/obj/x86: TestOclass/386 broken on solaris-amd64-smartosbuildlet

### ISSUE THREAD

**Issue by bcmills** [golang/go#32028]
The test fails consistently. An example run (https://build.golang.org/log/5a4d651e6c0f6c765aadbfaed8ea393096f71e63):

```
--- FAIL: TestOclass (0.00s)
    --- FAIL: TestOclass/386 (0.00s)
        asm_test.go:205: oclass("$(SB)"):
            have: 11
            want: 9
FAIL
FAIL	cmd/internal/obj/x86	2.286s
```

This test was added in [CL 175357](https://golang.org/cl/175357) and has been failing ever since (CC @quasilyte @cherrymui @TocarIP).

**Comment by quasilyte** [comment]
I'll fix it in a few mins.
