### ISSUE TITLE
net/http: the comment of Server.IdleTimeout doesn't describe its behavior correctly 

### ISSUE THREAD

**Issue by spacewander** [golang/go#32053]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lzx/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lzx/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="/usr/bin/gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build730423934=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you see instead?

The comment of `IdleTimeout` says:
> If IdleTimeout is zero, the value of ReadTimeout is used. If both are zero, ReadHeaderTimeout is used.

https://github.com/golang/go/blob/master/src/net/http/server.go#L2524

However, after reading:
https://github.com/golang/go/blob/master/src/net/http/server.go#L3008
https://github.com/golang/go/blob/master/src/net/http/server.go#L1913

It seems that `IdleTimeout` doesn't take account of `ReadHeaderTimeout`. Maybe I have missed something?

**Comment by bradfitz** [comment]
Thanks. That does look like a mistake.

**Comment by jamdagni86** [comment]
@bradfitz can I send a CL for this?

**Comment by bradfitz** [comment]
@jamdagni86, sure? But I haven't looked at it yet. It might be a code change or a doc fix. I don't know. So you should investigate and your commit message should explain.

**Comment by jamdagni86** [comment]
@bradfitz the current documentation is slightly incorrect. The earlier comment was

> IdleTimeout is the maximum amount of time to wait for the
> next request when keep-alives are enabled. If IdleTimeout
> is zero, the value of ReadTimeout is used. If both are
> zero, there is no timeout.

This got changed to the current version in [this](https://go-review.googlesource.com/46434) CL as a fix for [this](https://github.com/golang/go/issues/20383).

The correct sequence is this. At the end of the current request, it waits for IdleTimeout or ReadTimeout, whichever is non zero. At the beginning of the next request, it waits for ReadHeaderTimeout or ReadTimeout, whichever is non zero. The missing piece in the documentation is the last part where ReadTimeout is considered yet again.

In case IdleTimeout and ReadHeaderTimeout are both zeros and ReadTimeout is non zero, it would wait twice the duration of ReadTimeout and if none of the former two are zeros, it would wait end up waiting for a duration of IdleTimeout+ReadHeaderTimeout.

I'm not sure if this was the intended behaviour. And assuming that the code is working as intended, I guess it is enough if we revert the IdleTimeout documentation to the previous version and add a line in the ReadHeaderTimeout to mention that it falls back to ReadTimeout in case the former is zero.

Please let me know if this sounds good; I will send a CL.

**Comment by spacewander** [comment]
Maybe we could simply merge the patch and close the issue?

**Comment by odeke-em** [comment]
Thank you for filing this issue @spacewander and for working on the CL @jamdagni86, plus thanks for the tag @agnivade!

So from my reading of the current situation, I agree with @spacewander's comments:

1. s.idleTimeout() firstly checks if s.IdleTimeout is set, lest uses s.ReadTimeout  as per
https://github.com/golang/go/blob/06e34e58150a5cb77afdd3807a93f270a3068456/src/net/http/server.go#L3008-L3013

and if s.idleTimeout()'s result (either s.IdleTimeout or s.ReadTimeout) is non-zero, we'll set the ReadDeadline on the underlying s.c.rwc and then peek(4), thus wait a max deadline as per
https://github.com/golang/go/blob/06e34e58150a5cb77afdd3807a93f270a3068456/src/net/http/server.go#L1913-L1919

and at the end remove that deadline. If either of s.IdleTimeout and s.ReadTimeout are not set, there won't be a deadline as we see on line 1919
https://github.com/golang/go/blob/06e34e58150a5cb77afdd3807a93f270a3068456/src/net/http/server.go#L1919

2. ReadHeaderTimeout+ReadTimeout in s.readRequest are disjoint from s.idleTimeout() as per point 1
https://github.com/golang/go/blob/06e34e58150a5cb77afdd3807a93f270a3068456/src/net/http/server.go#L1817
https://github.com/golang/go/blob/06e34e58150a5cb77afdd3807a93f270a3068456/src/net/http/server.go#L936-L952

Thus this warrants just a documentation change the doc for Server.IdleTimeout from
https://github.com/golang/go/blob/06e34e58150a5cb77afdd3807a93f270a3068456/src/net/http/server.go#L2525-L2527

to

```go
 // next request when keep-alives are enabled. If IdleTimeout 
 // is zero, the value of ReadTimeout is used. If both are 
 // zero, there is no timeout.
```

as well as update the doc for ReadHeaderTimeout to include falling back to ReadTimeout as @jamdagni86 has presented in their CL.
