### ISSUE TITLE
feature request: call darwin system libraries from go

### ISSUE THREAD

**Issue by pjebs** [golang/go#32072]
I'm trying to call darwin libraries directly without using cgo.

The `https://godoc.org/golang.org/x/sys` package seems to support windows but not mac.

Will mac be supported in the future?

**Comment by ianlancetaylor** [comment]
You can find macOS support in golang.org/x/sys/unix.

If that isn't what you are looking for, what is missing?

**Comment by pjebs** [comment]
forgot that darwin was based on unix
