### ISSUE TITLE
x/tools/cmd/gopls: completions don't expand correctly in Emacs

### ISSUE THREAD

**Issue by muirrn** [golang/go#32078]
In Emacs when accepting a completion candidate, the already typed prefix is not replaced properly:

![EmacsComplete](https://user-images.githubusercontent.com/11356572/57828939-230bff80-7762-11e9-8e36-b8ad23d4a612.gif)

When we set the newText's range we properly move the range's start back to the start of the prefix, but we also move the range's end to the start of the prefix, so we end up just inserting the completion without overwriting anything. I think we need to leave the range's end at the cursor position so the prefix is overwritten. I'm not sure why VSCode doesn't show the same problem.

/cc @stamblerre

**Comment by senghoo** [comment]
same here.

**Comment by stamblerre** [comment]
My guess is VSCode only ever cares about the start. Thanks for catching this. The earlier change actually broke vim-go because it wasn't using the positions coming from the completion items, so it also might be worth checking if Emacs does that.

I'm just wary of adding an end position at the original start because its technically not the end of the completion item. But then, to get the real end we would have to get the length of the insertText, which will include special characters that shouldn't be counted...

**Comment by muirrn** [comment]
> I'm just wary of adding an end position at the original start because its technically not the end of the completion item

The end of the range needs to to be the end of the text you are overwriting, not the end of the text you are inserting. Setting the end to the cursor position is correct except for the postfix completion case. To handle postfix, you need to basically set the start to the start of the *ast.Ident, and the end to the end of the *ast.Ident.

**Comment by muirrn** [comment]
> it wasn't using the positions coming from the completion items, so it also might be worth checking if Emacs does that.

Emacs definitely uses the positions properly (and so does VSCode). I've been running with a patch that does what I describe above for a while since it is required for fuzzy matching (the typed prefix is not actually a prefix of the insertion text so you have to overwrite it).

The TextEdit range is the area of text you want to replace with the insertText. That's why you set start==end to insert text without replacing anything. As for why VSCode works, I would guess it sees start==end and the text after the cursor is a prefix of the completion item, so it automatically overwrites it.
```
interface TextEdit {
	/**
	 * The range of the text document to be manipulated. To insert
	 * text into a document create a range where start === end.
	 */
	range: Range;
```

**Comment by Stumble** [comment]
Tested with newest company-lsp + this version of gopls, spaces after the completion point and some symbol is eaten.

Before completion:
![Selection_077](https://user-images.githubusercontent.com/3461891/57896022-839f4900-7803-11e9-9bf6-3e6f4543a81b.png)

After:
![Selection_078](https://user-images.githubusercontent.com/3461891/57896032-9023a180-7803-11e9-8b2d-fd5fc3973e83.png)

**Comment by shackra** [comment]
I installed recently gopls I'm experiencing this bug for some reason

**Comment by stamblerre** [comment]
Which version of `gopls` are you using (`gopls version`)?

**Comment by shackra** [comment]
@stamblerre `version v0.1.1, built in $GOPATH mode`

**Comment by muirrn** [comment]
@shackra can you open a separate issue with details about what you are seeing including reproduction steps and gopls debug log if possible?

**Comment by shackra** [comment]
@muirrn yes I can, will do that during the week
