### ISSUE TITLE
runtime plugin.Open always crashed with unexpected signal SIGSEGV

### ISSUE THREAD

**Issue by cs-wang** [golang/go#32080]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.1 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="off"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/opt/gopath"
GOPROXY=""
GORACE=""
GOROOT="/opt/go"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build126490423=/tmp/go-build -gno-record-gcc-switches"
$ uname -a
Linux 039813279e8e 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
</pre></details>

### What did you do?

I start a golang binary program in a docker container in the environment above, when it step into plugin.Open, the program always crashed:

	p, err := plugin.Open(path)
	if err != nil {
		return err
	} 

### What did you expect to see?
the plugin.Open work normally
No failure

### What did you see instead?
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0xbb7b5d, 0x2a)
        /opt/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
        /opt/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 1 [syscall]:
runtime.cgocall(0x960650, 0xc000063ac0, 0xc00000e068)
        /opt/go/src/runtime/cgocall.go:128 +0x5e fp=0xc000063a90 sp=0xc000063a58 pc=0x4039de
plugin._Cfunc_pluginOpen(0xc00015a000, 0xc00000e068, 0x0)
        _cgo_gotypes.go:77 +0x4e fp=0xc000063ac0 sp=0xc000063a90 pc=0x73550e
plugin.open.func1(0xc00015a000, 0xc00000e068, 0xc000036240)
        /opt/go/src/plugin/plugin_dlopen.go:74 +0xa7 fp=0xc000063af8 sp=0xc000063ac0 pc=0x736727
plugin.open(0xba2efe, 0xb, 0x50, 0x0, 0x0)
        /opt/go/src/plugin/plugin_dlopen.go:74 +0x32a fp=0xc000063db0 sp=0xc000063af8 pc=0x73594a
plugin.Open(0xba2efe, 0xb, 0xc000063e78, 0x1, 0x1)
        /opt/go/src/plugin/plugin.go:32 +0x35 fp=0xc000063de8 sp=0xc000063db0 pc=0x7351e5

**Comment by f1qwase** [comment]
Hi @cs-wang !
I have exactly the same problem. Did you solve it?
