### ISSUE TITLE
Regexp issue

### ISSUE THREAD

**Issue by SLusenti** [golang/go#32086]
### What version of Go are you using (`go version`)? 

<pre>
$ go version
go version go1.11.7 
</pre>

### Does this issue reproduce with the latest release?
this is the last version on fedora 29

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/slusenti/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/slusenti/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build237052522=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

just look at this code
<pre>
reDash, _ := regexp.Compile("^:[ ]+[-]?(.*)[-]?$")
s := ": 7 this;is a test -"
s = reDash.ReplaceAllString(s, "$1")
print(s)
</pre>
<pre>
this;is a test -
</pre>

### What did you expect to see?
<pre>
7 this;is a test -
</pre>
it seems that it has no clue of the difference between numbers and spaces

### What did you see instead?
<pre>
this;is a test -
</pre>

**Comment by ianlancetaylor** [comment]
Please show us a complete example, ideally on https://play.golang.org.  As far as I can tell your program works as expected.

**Comment by SLusenti** [comment]
yeah , I've tested on the playground and it works well.
but if I run the same code on my fedora desktop I get **"this;is a test -"** instead of###  **"7 this;is a test -"**

**Comment by agnivade** [comment]
@SLusenti - I tried this on Ubuntu and it works fine. Would it be possible for you to show this using a docker image of Fedora 29 ?

**Comment by ianlancetaylor** [comment]
You need to show us exactly what you are running.

**Comment by SLusenti** [comment]
yeah,
now I've textsted on fedora30 with golang 1.12 and work fine thanks.
