### ISSUE TITLE
gccgo: very long gcbits symbol names

### ISSUE THREAD

**Issue by Helflym** [golang/go#32083]
gccgo is generated gcbits symbols with their full name, instead of hidding them under gcbits..* like Go toolchain is doing (cf https://go-review.googlesource.com/c/go/+/12531/). 
Corresponding Go issue #11583

```
$ nm index0-out.o | grep gcbits  
...
gcbits..bazaaaaaaaamaaa... (average 100 000 a... )
...
```

On AIX, symbol names are limited to 65535 characters. 
Therefore, test "./index0-out.go compilation" is failing: 
```
ld: 0711-950 ERROR: A name is too long.
        Names longer than 65535 characters are truncated.
        The name begins: gcbits..bazaaaaaaaamaaaaaaaaaaaaaaaaaaaaaaaaa
ld: 0711-950 ERROR: A name is too long.
        Names longer than 65535 characters are truncated.
        The name begins: gcbits..bazaaaaaaaamaaaaaaaaaaaaaaaaaaaaaaaaa
collect2: error: ld returned 8 exit status
compiler exited with status 1
```

Is there any way to reduce/hide these symbol names as it's done under Go toolchain ? 
I don't think such thing can actually occur in a "real" Go code, but that might be worth fixing it once for all. 

/cc @ianlancetaylor  @thanm

**Comment by thanm** [comment]
Could you please post the code in question, or some sort of source reproducer? Thanks.

**Comment by Helflym** [comment]
[index0-out.zip](https://github.com/golang/go/files/3187246/index0-out.zip)

This index0-out.go is generated inside gccgo testsuite (under gcc/testsuite/go.test/test) by index0.go and index.go.
