### ISSUE TITLE
import "path/filepath" is a program, not an importable package

### ISSUE THREAD

**Issue by FlorianVAG** [golang/go#32103]
### What version of Go are you using (`go1.12.4 darwin/amd64`)?

<pre>
$ go version
go version go1.12.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
idk
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/fuchsi/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/fuchsi/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sh/wpxrvpmn427fpml2z2z3m41h0000gn/T/go-build767506079=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I made a hello.go test go file where I imported the path/filepath package. I tried to compile the hello.go file with $go build hello.go and got this error message:

Error: import "path/filepath" is a program, not an importable package

I also tried to reinstall go but this still nothing change
### What did you see instead?

**Comment by ianlancetaylor** [comment]
Sounds like something is wrong with your Go installation.  Look at `go env GOROOT`/src/path/filepath and make sure there are no extra files dropped into that directory.  If that doesn't help, show us the exact program you tried to build, the exact command that you ran, and the complete and exact output.

**Comment by wsyingang** [comment]
I am solving this probelms too

**Comment by ianlancetaylor** [comment]
@wsyingang Please see the comment above https://github.com/golang/go/issues/32103#issuecomment-493466628
