### ISSUE TITLE
Tips for a first time github user

### ISSUE THREAD

**Issue by devjames25** [golang/go#32122]
The layout for this project is great and very detailed. It's very helpful for a first time github user, but problems could arise especially if one wants to contribute by fixing bugs. I suggest adding a small section on the contributing page dedicated for first time users.

**Comment by ALTree** [comment]
The contribution page at https://golang.org/doc/contribute.html is very detailed. Have you seen that, and you think it's not enough, or you didn't see that?

**Comment by devjames25** [comment]
Ok, I haven't seen it when doing my evaluation but I do now. Thank you
