### ISSUE TITLE
debug/pe: fails to parse variable length optional header

### ISSUE THREAD

**Issue by prash2611** [golang/go#32126]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes it does! The issue is present is current master.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/prashant/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/prashant/go2"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build980405246=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I was trying to parse a PE file (linux Kernel to be specific) using debug/pe package.
A toy program for the same would look like:

```
package main

import (
    "debug/pe"
    "fmt"
)

func main() {
    file, err := pe.Open("/boot/vmlinuz-4.15.0-48-generic")
    if err != nil {
        file.Close()
        return
    }
    defer file.Close()

    fmt.Println(file.OptionalHeader)
}
```

### What did you expect to see?

I would like to see parsed optional header.

### What did you see instead?

Optional header turned out to be nil.

### What is actual bug?

The debug/pe package assumes there are always 16 entries in [16]DataDirectory in OptionalHeader32/64 (ref pe.go)
NumberOfRvaAndSizes uint32
DataDirectory [16]DataDirectory
}

But that is not always the case, there could be less no of entries (PE signed linux kernel for example):
prashant@Pra-Work:~$ sudo pev /boot/vmlinuz-4.15.0-47-generic
....
Data-dictionary entries:	6
....

In such case, the parsing gives incorrect results.

**Comment by alexbrainman** [comment]
@prash2611 thank you for reporting the problem. I will review your change when I have time.

Alex

**Comment by prash2611** [comment]
Thanks @alexbrainman, looking forward to your review comments.

**Comment by nokute78** [comment]
Hi. 
I have an similar issue and this patch helps me.
https://go-review.googlesource.com/c/go/+/177959

I tested this code.
https://gist.github.com/nokute78/46c1eb6a2f6050db4c5a87845dbdf87c

I tested using Ubuntu 18.04 kernel (vmlinuz-4.18.0-25-generic)
```sh
taka@ubuntu:~/tmp$ sudo cp /boot/vmlinuz-4.18.0-25-generic .
taka@ubuntu:~/tmp$ sudo chmod +r vmlinuz-4.18.0-25-generic
taka@ubuntu:~/tmp$ go version
go version go1.12.7 linux/amd64
taka@ubuntu:~/tmp$ go run pe.go vmlinuz-4.18.0-25-generic 
invalid format
exit status 1
```

With the patch, my program worked correctly.
```sh
taka@ubuntu:~/tmp$ ~/git/go/bin/go version
go version devel +0cb90728c9 Mon Jun 17 11:31:57 2019 -0700 linux/amd64
taka@ubuntu:~/tmp$ ~/git/go/bin/go run pe.go vmlinuz-4.18.0-25-generic 
Header64
dataDir:[{0 0} {0 0} {0 0} {0 0} {8550272 1912} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0}]
```

**Comment by prash2611** [comment]
Thanks @nokute78, glad to know that the patch solves your issue!

I will let @alexbrainman comment on when it will be merged in master and GA.

**Comment by alexbrainman** [comment]
> I have an similar issue and this patch helps me.
> https://go-review.googlesource.com/c/go/+/177959

I am glad to know. Thank you for confirming.

We cannot merge this change onto master branch until after go1.13 is released. Everyone is waiting for that.

Alex

**Comment by nokute78** [comment]
@prash2611 @alexbrainman 
Thanks.

I’m also looking forward to Go 1.13.
So, I will wait the patch patiently.
