### ISSUE TITLE
x/exp/shiny/driver/gldriver: add missing modifier key codes

### ISSUE THREAD

**Issue by smasher164** [golang/go#32131]
Currently the right control key and right command keys are not (accurately) represented in the mods struct. After testing for key events, I've determined that
- **key.ControlRight** should be represented by the flags `33<<13 | 0x100`, the code `C.kVK_RightControl`, and modifier `key.ModControl`.
- **kVK_RightCommand** should be represented by the flags `1<<20 | 0x110`, the code `0x36` (does not appear in *Events.h*), and modifier `key.ModMeta`.

**Comment by smasher164** [comment]
Is there something in particular that needs investigating? The items I mentioned are currently TODOs in [shiny/driver/gldriver/cocoa.go](https://github.com/golang/exp/blob/efd6b22b2522a48712e1fd0b3c1ab34d243f5245/shiny/driver/gldriver/cocoa.go#L224). I understand if there is a bandwidth issue with having to review shiny code. I can submit a CL that makes the above changes if desired.

**Comment by dmitshur** [comment]
> Is there something in particular that needs investigating?

It's just the very first triage state an issue goes through. See https://golang.org/wiki/HandlingIssues#issue-states for more information.

Thanks for reporting and fixing this!
