### ISSUE TITLE
Can go tool compile run in module-aware mode?

### ISSUE THREAD

**Issue by xujintao** [golang/go#32139]
go version: 1.12

### What did you do?
go.mod
```
module github.com/user/foo
```
main.go
```
package main

import "github.com/user/foo/bar"
func main() {
	bar.Hello()
}
```
bar/bar.go
```
package bar

func Hello() {
	println(1)
}
```
```sh
# go tool compile -S -l main.go &> main.s
```
### What did you expect to see?
The golang assembly of main.go

### What did you see instead?
main.go:3:8: can't find import: "github.com/user/foo/bar"

**Comment by ALTree** [comment]
The answer is no.

The `compile` tool is a rather low-level command. From its doc:

> Compile, typically invoked as “go tool compile,” compiles a single Go
package comprising the files named on the command line. It then writes a
single object file named for the basename of the first source file with a .o
suffix. 

It doesn't know how to find and link multiple packages. `build` does.

Closing here.

**Comment by ALTree** [comment]
As a side note, you can use the `-S` flag with `go build`, like this:

```
$ go build -gcflags=-S main.go
```

**Comment by xujintao** [comment]
Thanks, go build works.
