### ISSUE TITLE
errors: documentation for errors.Unwrap mentions non existing interface Wrapper

### ISSUE THREAD

**Issue by johan-bolmsjo** [golang/go#32130]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +1ab063ce53 Fri May 17 22:32:30 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/johan/.cache/go-build"
GOENV="/home/johan/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/johan/go"
GOPROXY="direct"
GOROOT="/home/johan/go/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/home/johan/go/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/johan/go/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build709384782=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Check documentation for errors package in standard library.

### What did you expect to see?

Correct documentation for errors.Unwrap, similar to the Is and As functions.

### What did you see instead?

The documentation for the Unwrap function mentions a non existing interface called Wrapper. This interface has was removed by revert in commit 3e2c522d5c712fa2b1d18a101272abefc7dcb074

Also it's rather unclear how one would go about actually wrap an error. There is the Unwrap function with a short comment (that mentions the non existing Wrapper interface), but nothing much else that provide more context. How are errors chained? Up to 3pp library support?

**Comment by ALTree** [comment]
Thanks for reporting this.

This issue has already been noticed, and it'll be fixed by [CL 177617](https://go-review.googlesource.com/c/go/+/177618/).

**Comment by neild** [comment]
https://golang.org/cl/177618
