### ISSUE TITLE
http client memory leak

### ISSUE THREAD

**Issue by Highter87** [golang/go#32143]
This code has a memory leak. Memory grows with every request.

```
package main

import (
	"fmt"
	"net/http"
	"io"
	"io/ioutil"
	"time"
)
func main() {
	httpClient := &http.Client{}

	for {
		res, err := httpClient.Get("https://google.com/")
		if err != nil {
			return
		}

		io.Copy(ioutil.Discard, res.Body)

		fmt.Println(res.StatusCode)

		time.Sleep( time.Second * 1 )
		res.Body.Close()
	}
}
```

**Comment by ALTree** [comment]
> Memory grows with every request.

How are you measuring this?

**Comment by AlexRouSg** [comment]
@ALTree he has a closed issue on the same topic with a little more detail.
#32110

> go version go1.12.5 windows/amd64

**Comment by Highter87** [comment]
go version go1.12.5 windows/amd64

After each request, the memory is increased, but not cleared. After 8 hours - 8 gigabytes ends and the program ends. What else to write here, the example code is given, it remains only to run and see. Yes, the application is opened a second time, because the first one was closed, without even understanding it.

**Comment by agnivade** [comment]
Your first issue was closed because your code was erroneous. With the correct code, I am unable to reproduce the issue (I am on linux though).

You still haven't mentioned how are you measuring the memory increase. Can you mention that ?
