### ISSUE TITLE
context: CancelFunc isn't documented to be safe for simultaneous use by multiple goroutines

### ISSUE THREAD

**Issue by dmitshur** [golang/go#32145]
There are two types defined in the `context` package. The documentation makes it very clear that the `context.Context` type and its methods are safe for simultaneous use by multiple goroutines:

- In the [package comment](https://godoc.org/context):

    > The same Context may be passed to functions running in different goroutines; Contexts are safe for simultaneous use by multiple goroutines.

- In the [`context.Context`](https://godoc.org/context#Context) type documentation:

  > Context's methods may be called by multiple goroutines simultaneously.

There is another type in the context package, the [`context.CancelFunc`](https://godoc.org/context#CancelFunc) type. It is currently documented as:

> A CancelFunc tells an operation to abandon its work. A CancelFunc does not wait for the work to stop. After the first call, subsequent calls to a CancelFunc do nothing.

It states that after the first call, subsequent calls to a CancelFunc do nothing. The three `With*` methods that return a Context and CancelFunc say:

> Canceling this context releases resources associated with it, so code should call cancel as soon as the operations running in this Context complete.

As I understand it, the documentation does not state that ContextFunc is safe for simultaneous use by multiple goroutines. Is that a documentation bug?

/cc @Sajmani, @bradfitz as [owners](https://dev.golang.org/owners); also /cc @mvdan

**Comment by neild** [comment]
A `CancelFunc` is intended to be safe for concurrent use, so that's a documentation bug if "subsequent calls do nothing" isn't clear enough.
