### ISSUE TITLE
syscall: int 0x80 is still used by syscalls in Linux

### ISSUE THREAD

**Issue by faissaloo** [golang/go#32140]
`int 0x80` is deprecated and extremely slow, new x86 software should be using `sysenter`, you can find the calling convention [on this SO answer](https://stackoverflow.com/questions/29482174/delete-a-file-in-linux-assembly-x86/41282643#41282643)

**Comment by ianlancetaylor** [comment]
Which platform are you talking about?  As far as I know on amd64 we always use the `SYSCALL` instruction.

**Comment by faissaloo** [comment]
386 (aka x86) https://github.com/golang/go/blob/master/src/syscall/asm_linux_386.s

**Comment by martisch** [comment]
Current Minimum Go CPU requirement for 386 is Pentium MMX which does not support sysenter.
Therefore changing this for all supported Go archs would need a test for the specific CPUID bit and a bump in minimum CPU requirements. https://golang.org/doc/install/source#environment

See https://github.com/golang/go/blob/c6f9321b5a46e4af3233417d068c0efb4113d8e7/src/runtime/sys_linux_386.s#L13 for why int 0x80 is used:

```
// Most linux systems use glibc's dynamic linker, which puts the
// __kernel_vsyscall vdso helper at 0x10(GS) for easy access from position
// independent code and setldt in runtime does the same in the statically
// linked case. However, systems that use alternative libc such as Android's
// bionic and musl, do not save the helper anywhere, and so the only way to
// invoke a syscall from position independent code is boring old int $0x80
// (which is also what syscall wrappers in bionic/musl use).
//
// The benchmarks also showed that using int $0x80 is as fast as calling
// *%gs:0x10 except on AMD Opteron. See https://golang.org/cl/19833
// for the benchmark program and raw data.
```

Are there new benchmarks showing Go to better off not using int 0x80 with an alternative supported with bionic, musl and position independent code? This would be interesting especially on CPUs that dont support amd64 as the newer ones are likely better of to use amd64 target at any rate.
