### ISSUE TITLE
runtime: getting failed MSpanList_Insert while doing mongorestore

### ISSUE THREAD

**Issue by AnilDarji** [golang/go#32159]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
I am trying to run a command mongoexport but getting the error  ./mongorestore -d storefront /Users/temp/storefront/
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

#### What did you expect to see?
Dump of mongodb should be restored

#### What did you see instead?
failed MSpanList_Insert 0xb58000 0x382f48ff9d6d 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0xabaecb)
	/usr/local/go/src/runtime/panic.go:491 +0xad fp=0x7ffeefbff660 sp=0x7ffeefbff630
runtime.MSpanList_Insert(0xadcb88, 0xb58000)
	/usr/local/go/src/runtime/mheap.c:692 +0x8f fp=0x7ffeefbff688 sp=0x7ffeefbff660
MHeap_FreeSpanLocked(0xad9780, 0xb58000, 0x100)
	/usr/local/go/src/runtime/mheap.c:583 +0x163 fp=0x7ffeefbff6c8 sp=0x7ffeefbff688
MHeap_Grow(0xad9780, 0x8, 0x0)
	/usr/local/go/src/runtime/mheap.c:420 +0x1a8 fp=0x7ffeefbff708 sp=0x7ffeefbff6c8
MHeap_AllocSpanLocked(0xad9780, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.c:298 +0x365 fp=0x7ffeefbff748 sp=0x7ffeefbff708
mheap_alloc(0xad9780, 0x1, 0x12, 0x0)
	/usr/local/go/src/runtime/mheap.c:190 +0x121 fp=0x7ffeefbff770 sp=0x7ffeefbff748
runtime.MHeap_Alloc(0xad9780, 0x1, 0x10000000012, 0xdea9)
	/usr/local/go/src/runtime/mheap.c:240 +0x66 fp=0x7ffeefbff7a8 sp=0x7ffeefbff770
MCentral_Grow(0xae14f8, 0x0)
	/usr/local/go/src/runtime/mcentral.c:197 +0x8b fp=0x7ffeefbff810 sp=0x7ffeefbff7a8
runtime.MCentral_CacheSpan(0xae14f8, 0x0)
	/usr/local/go/src/runtime/mcentral.c:85 +0x167 fp=0x7ffeefbff848 sp=0x7ffeefbff810
runtime.MCache_Refill(0xb54000, 0x12, 0x0)
	/usr/local/go/src/runtime/mcache.c:90 +0xa0 fp=0x7ffeefbff870 sp=0x7ffeefbff848
runtime.mcacheRefill_m()
	/usr/local/go/src/runtime/malloc.c:368 +0x57 fp=0x7ffeefbff890 sp=0x7ffeefbff870
runtime.onM(0x9d5490)
	/usr/local/go/src/runtime/asm_amd64.s:273 +0x9a fp=0x7ffeefbff898 sp=0x7ffeefbff890
runtime.mallocgc(0x120, 0x3273c0, 0x0, 0x0)
	/usr/local/go/src/runtime/malloc.go:178 +0x849 fp=0x7ffeefbff948 sp=0x7ffeefbff898
runtime.newobject(0x3273c0, 0xb54000)
	/usr/local/go/src/runtime/malloc.go:353 +0x49 fp=0x7ffeefbff970 sp=0x7ffeefbff948
runtime.newG(0x29e6a)
	/usr/local/go/src/runtime/proc.go:233 +0x2a fp=0x7ffeefbff988 sp=0x7ffeefbff970
allocg(0xacaf40)
	/usr/local/go/src/runtime/proc.c:925 +0x1f fp=0x7ffeefbff998 sp=0x7ffeefbff988
runtime.malg(0x8000, 0xacafe0)
	/usr/local/go/src/runtime/proc.c:2106 +0x1f fp=0x7ffeefbff9c8 sp=0x7ffeefbff998
runtime.mpreinit(0xacb5c0)
	/usr/local/go/src/runtime/os_darwin.c:137 +0x27 fp=0x7ffeefbff9e0 sp=0x7ffeefbff9c8
mcommoninit(0xacb5c0)
	/usr/local/go/src/runtime/proc.c:201 +0xc9 fp=0x7ffeefbffa08 sp=0x7ffeefbff9e0
runtime.schedinit()
	/usr/local/go/src/runtime/proc.c:138 +0x55 fp=0x7ffeefbffa30 sp=0x7ffeefbffa08
runtime.rt0_go(0x7ffeefbffa60, 0x4, 0x7ffeefbffa60, 0x0, 0x4, 0x7ffeefbffba0, 0x7ffeefbffbaf, 0x7ffeefbffbb2, 0x7ffeefbffbbd, 0x0, ...)
	/usr/local/go/src/runtime/asm_amd64.s:95 +0x116 fp=0x7ffeefbffa38 sp=0x7ffeefbffa30

#### System details

```
go version go1.12.5 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/temp/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/temp/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version go1.12.5 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.12.5
uname -v: Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54
lldb --version: lldb-1000.11.38.2
  Swift-4.2
```

**Comment by agnivade** [comment]
Hello @AnilDarji, we would need the complete steps to reproduce this issue.

Could you confirm that this is an issue with the Go runtime and not with mongorestore code ?

Will it be possible for you to create a minimalistic repro (by pulling out the necessary code from mongorestore) that creates the same crash ?
