### ISSUE TITLE
x/website: tip serving 404s for lib/godoc/go-logo-blue.svg

### ISSUE THREAD

**Issue by bcmills** [golang/go#32151]
This [logo image](https://tip.golang.org/lib/godoc/go-logo-blue.svg) appears in godoc pages on `tip` (such as https://tip.golang.org/cmd/go/), but the server is currently producing 404s for it.

[CL 178137](https://golang.org/cl/178137) (#9936) seems to be closely related (CC @katiehockman).

**Comment by andybons** [comment]
Not fixed yet. Need to update go.mod in x/website to pull in https://go.googlesource.com/tools/+/d1a3278ee74994e9aa609e9e711c616bba677d5d

**Comment by andybons** [comment]
Fixed by https://go-review.googlesource.com/c/website/+/178237
