### ISSUE TITLE
x/tools/go/analysis: accomodate multiple output formats in Diagnostic

### ISSUE THREAD

**Issue by dominikh** [golang/go#32156]
Right now, analyses report diagnostics, where a diagnostic consists of a position, category and message. This makes it difficult to accommodate multiple output formats. For editor integration, we want short, concise messages. These messages are usually restricted to one line, but may be occasionally multi-line. For interactive use in a terminal, we may want to offer a more verbose format that includes instructions on how to address the finding, or provide more information about the context of the finding. For interactive use in a browser, we would like to include hyperlinks, or possibly other markup. It is not feasible to address all these different media with a single message.

I am not proposing a concrete solution to the problem. Instead, I'd like to encourage discussion on how we can improve the situation.

/cc @matloob @ianthehat @mvdan @fatih

**Comment by matloob** [comment]
I agree that this is a bit of a problem. I think the solution might be to have conventions on how the messages are displayed. Maybe we only show the first sentence/line in some cases?

One thing I'd worry about if we added multiple message fields is that we might add too many output formats so that we don't make writing the docs too burdensome on tool writers...

**Comment by ianthehat** [comment]
I think we might be better off indicating to the analysis the type of output we want and then sticking to a single string.

**Comment by dominikh** [comment]
Diagnostics now have suggested fixes and related information, which covers most needs expressed in this issue. The only issue that remains is differently formatted messages for different frontends. Personally I think this can be worked around with what we have. 

Tools that want to display a short message can display the first paragraph, tools that want to display more detailed messages can display the whole message. This would work similar to `git log` and `git log --oneline`.

Hyperlinks don't need explicit markup, they can be automatically extracted from text if written out as URLs. And nobody has asked for more complex formatting.

I am going to close this issue, but feel free to reopen if you disagree with my conclusion.

**Comment by matloob** [comment]
Sounds good
