### ISSUE TITLE
cmd/go: go mod init does not correctly resolve pseudo-versions

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#32161]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +ab724d43ef Mon May 20 20:58:14 2019 +0000 linux/amd64
</pre>

### What did you do?

Extract the following files:
```
-- glide.lock --
imports:
- name: github.com/Shopify/sarama
  version: 4602b5a8c6e826f9e0737865818dd43b2339a092
  subpackages:
  - mocks
- name: github.com/eapache/queue
  version: 093482f3f8ce946c05bcba64badd2c82369e084d
-- glide.yaml --
package: example

-- main.go --
package main

import (
	_ "github.com/Shopify/sarama"
	_ "github.com/eapache/queue"
)

func main() {}
```

Run `go mod init example`.

### What did you expect to see?

I would expect to see the `go.mod` file reflect the requirements listed in the `glide.lock` file. Specifically, I'd expect to see this `go.mod` file:

```
module example

require (
	github.com/Shopify/sarama v1.21.0
	github.com/eapache/queue v1.1.1-0.20180227141424-093482f3f8ce
)

go 1.13
```

which is what you get if you start with this `go.mod` file, which exactly reflects the `glide.lock` file:

```
module example

go 1.12

require (
	github.com/eapache/queue 093482f3f8ce946c05bcba64badd2c82369e084d
	github.com/Shopify/sarama 4602b5a8c6e826f9e0737865818dd43b2339a092
)
```

### What did you see instead?

I see this `go.mod` file:

```
module example

go 1.13

require (
	github.com/Shopify/sarama v1.21.0
	github.com/eapache/queue v0.0.0-20180227141424-093482f3f8ce
)
```

The `github.com/eapache/queue` dependency has the wrong pseudo-version, which means that when dependencies are later resolved, the dependency in sarama (which depends on epache/queue v1.1.0) supercedes the dependency in the `go.mod` file, which leads to a version regression.

**Comment by myitcv** [comment]
cc @bcmills @jayconrod

**Comment by cuonglm** [comment]
Seems duplicated of https://github.com/golang/go/issues/29262

**Comment by rogpeppe** [comment]
@cuonglm I don't *think* it's a duplicate of that bug. With that bug, I can do `go get rsc.io/quote@5d9f230bcfba` and version stays at `v0.0.0-20180710144737-5d9f230bcfba`, whereas with this bug, if I do `go get github.com/eapache/queue@093482f3f8ce`, the version changes to the correct `v1.1.1-0.20180227141424-093482f3f8ce`.

**Comment by bcmills** [comment]
Neat example. I can confirm the observed behavior: `go mod init` produces the wrong pseudo-version, but `go get` finds the correct one.

**Comment by thepudds** [comment]
https://golang.org/cl/178497 I think is trying to get `go mod init` to create the proper pseudoversion.

If that turns out to be tricky to get right or a bigger change than would work for 1.13, I wonder if an alternative approach might be to simplify what `go mod init` tries to do in this case. 

Instead of `go mod init` creating the proper pseudoversion, perhaps instead `go mod init` could just leave the commit hash in the resulting `go.mod` file?

That should then be automatically converted to the right pseudoversion by the first `go list -m all`, `go build` or similar because the commit hash would be treated as a ["module query"](https://golang.org/cmd/go/#hdr-Module_queries).

However, perhaps that is no simpler than the current https://golang.org/cl/178497 approach.

**Comment by cuonglm** [comment]
@thepudds I don't know why that change is not sure or hard to understand. When the `convert` try to make pseudoversion, it does use `statVers` to query the most recent tag:

```
                        // Otherwise make a pseudo-version.                                                                                                                                                                                   
                        if info2.Version == "" {                                                                                                                                                                                              
                                tag, _ := r.code.RecentTag(statVers, p)                                                                                                                                                                       
                                v = tagToVersion(tag)                                                                                                                                                                                         
                                // TODO: Check that v is OK for r.pseudoMajor or else is OK for incompatible.                                                                                                                                 
                                info2.Version = PseudoVersion(r.pseudoMajor, v, info.Time, info.Short)                                                                                                                                        
                        }
```

we passed `statVers` as empty string, so most recent tag from HEAD was returned instead of most recent tag from commit.

**Comment by bcmills** [comment]
It is not correct for `convert` to use `statVers` in the `RecentTag` lookup, but passing in the correct `rev` moves things in the right direction regardless.
