### ISSUE TITLE
cmd/go: accept -Wl,-R,path

### ISSUE THREAD

**Issue by ng-0** [golang/go#32167]
### What version of Go are you using (`go version`)?

<pre>
$ go112 version
go version go1.12.4 netbsd/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go112 env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ng0/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="netbsd"
GOOS="netbsd"
GOPATH="/home/ng0/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/pkg/go112"
GOTMPDIR=""
GOTOOLDIR="/usr/pkg/go112/pkg/tool/netbsd_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build011870882=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Given any code which involves:

`#cgo LDFLAGS: -Wl,-R/usr/pkg/lib`

or similar,

```
go build command-line-arguments: invalid flag in #cgo LDFLAGS: -Wl,-R/usr/pkg/lib
```

is returned.

### What did you expect to see?

A successful treatment of the LDFLAGS.

I don't know if this is a feature limitation or a bug, but given that I need to invoke
LDFLAGS this way for out-of-pkgsrc builds usually, I consider this a bug.

### What did you see instead?

See above.

**Comment by AlexRouSg** [comment]
cgo flags are white listed, see https://golang.org/cmd/cgo/

> For security reasons, only a limited set of flags are allowed, notably -D, -I, and -l. To allow additional flags, set CGO_CFLAGS_ALLOW to a regular expression matching the new flags. To disallow flags that would otherwise be allowed, set CGO_CFLAGS_DISALLOW to a regular expression matching arguments that must be disallowed. In both cases the regular expression must match a full argument: to allow -mfoo=bar, use CGO_CFLAGS_ALLOW='-mfoo.*', not just CGO_CFLAGS_ALLOW='-mfoo'. Similarly named variables control the allowed CPPFLAGS, CXXFLAGS, FFLAGS, and LDFLAGS.

cc @ianlancetaylor incase the flag could be added to the list

**Comment by ng-0** [comment]
I see. Okay, let me expand my argument for the specific LDFLAGS, this is I believe
the official statement/explanation for this in NetBSD: http://www.netbsd.org/docs/elf.html

Reference code, if relevant (debug quality, and I've just picked up go):
https://c.n0.is/go-hello-c/file/tip/v2/main.go

**Comment by ianlancetaylor** [comment]
Yes, we should accept that.  We currently accept -Wl,-rpath but not -Wl,-R.

If anybody wants to send a patch, the place is cmd/go/internal/work/security.go.

@gopherbot Please open backport to 1.12.

**Comment by ng-0** [comment]
Thanks for looking into this.

**Comment by AlexRouSg** [comment]
@ng-0 you want to do the change?

**Comment by ng-0** [comment]
Yes (in fact I've looked into this already). There could be some delay for other tasks take priority.
