### ISSUE TITLE
Go mod:Can't find the code which isn't on the master branch

### ISSUE THREAD

**Issue by Smityz** [golang/go#32160]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/data/home/***/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/data/home/***/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/data/home/***/***/***/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build015182643=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
I want to use go mod to find the code which isn't on the master branch.But I failed.

<pre>
go: finding git.code.oa.com/*** latest
go: finding git.code.oa.com/***i latest
go: finding git.code.oa.com/*** latest
Fetching https://git.code.oa.com/***?go-get=1
Parsing meta tags from https://git.code.oa.com/***?go-get=1 (status code 404)
Fetching https://git.code.oa.com?go-get=1
Parsing meta tags from https://***?go-get=1 (status code 404)

</pre>

### What did you expect to see?
How can I  use go module to find the code which isn't on the master branch?

### What did you see instead?
It can't find

**Comment by agnivade** [comment]
See https://golang.org/cmd/go/#hdr-Module_queries. Use a branch identifier in the version suffix.

**Comment by Smityz** [comment]
> See https://golang.org/cmd/go/#hdr-Module_queries. Use a branch identifier in the version suffix.

So,can module support to fetch a un-master branch?

**Comment by agnivade** [comment]
Yes.

**Comment by Smityz** [comment]
> Yes.

I don't understand it.Should I use replace url and@branch name

**Comment by agnivade** [comment]
Please feel free to ask in any of the forums in [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions. We mainly use the issue tracker for bugs and proposals.
