### ISSUE TITLE
cmd/go: -trimpath build flag has no effect in gccgo

### ISSUE THREAD

**Issue by cespare** [golang/go#32162]
Go 1.13 is adding a new `-trimpath` flag (see 74695644e0c38586a85b9b483830c546efbb6642).

The documentation says

```
        -trimpath
                remove all file system paths from the resulting executable.
                Instead of absolute file system paths, the recorded file names
                will begin with either "go" (for the standard library),
                or a module path@version (when using modules),
                or a plain import path (when using GOPATH).
```

This works with gc, but the flag has no effect in gccgo. Demo:

```
$ mkdir /tmp/xyz123
$ cd /tmp/xyz123/
$ cat > hello.go
package main
func main() { println("hello") }
$ out=gc.out && gotip clean -cache && gotip build -o $out hello.go && strings $out | grep xyz123 | head -3
/tmp/xyz123/hello.go
$ out=gc.trimpath.out && gotip clean -cache && gotip build -trimpath -o $out hello.go && strings $out | grep xyz123 | head -3
$ out=gccgo.out && gotip clean -cache && gotip build -compiler gccgo -o $out hello.go && strings $out | grep xyz123 | head -3
/tmp/xyz123
/tmp/xyz123/hello.go
GNU Go 8.3.0 -m64 -mtune=generic -march=x86-64 -g -fgo-relative-import-path=_/tmp/xyz123
$ out=gccgo.trimpath.out && gotip clean -cache && gotip build -trimpath -compiler gccgo -o $out hello.go && strings $out | grep xyz123 | head -3
/tmp/xyz123
/tmp/xyz123/hello.go
GNU Go 8.3.0 -m64 -mtune=generic -march=x86-64 -g -fgo-relative-import-path=_/tmp/xyz123
$ diff gccgo.out gccgo.trimpath.out
```

(This came up in [CL 176112](https://golang.org/cl/176112).)

Here are some things we could do to improve the situation:

* Hook up `-trimpath` to the appropriate gcc flags so that the option works as advertised (if that's possible).
* Reject `-trimpath` if it's being used with a compiler where that isn't implemented.
* Document that `-trimpath` only works with gc.

Marking for 1.13 since this is a new feature and we should at least document the interaction.

**Comment by rsc** [comment]
The GCC/LLVM option to use to implement -trimpath is -ffile-prefix-map, which implies -fdebug-prefix-map and -fmacro-prefix-map. See https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html. This was added to LLVM in mid-2018 (https://reviews.llvm.org/D49466).

**Comment by cespare** [comment]
@bcmills should we document that `-trimpath` only works with gc for 1.13?

**Comment by ianlancetaylor** [comment]
https://golang.org/cl/187824, which is out for review for 1.13, will affect this.
