### ISSUE TITLE
cmd/go: unknown revision despite it being a released revision

### ISSUE THREAD

**Issue by aesherman** [golang/go#32170]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.12.5 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/andrewsherman/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/andrewsherman/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/andrewsherman/Desktop/modules/device-logs-service/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/j3/wf6zjt5x0fx6l2nr0h1x8yv80000gn/T/go-build910017862=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

go build

### What did you expect to see?

I expected it to build

### What did you see instead?

```go: finding github.com/getwagz/go-sdk v1.38.1
go: github.com/getwagz/go-sdk@v1.38.1: unknown revision v1.38.1
go: error loading module requirements
```

This is the latest release of the `github.com/getwagz/go-sdk` and in my go.mod file, it is req

**Comment by thepudds** [comment]
@aesherman is `github.com/getwagz/go-sdk` a public repository?

Can you try with the tip version of Go? It might work better, or give a better error message.

An easy way to get tip is `go get golang.org/dl/gotip && gotip download`, and then you can do `gotip github.com/getwagz/go-sdk`.

If that does not help, can you try `gotip get -x -v github.com/getwagz/go-sdk`?

**Comment by aesherman** [comment]
To answer a question I saw... `github.com/getwagz/go-sdk` _is_ a private repo that I have access to.  Does something different need to be configured for modules in order to get it to work with private repos?

**Comment by aesherman** [comment]
I fixed the issue by changing https to ssh in my gitconfig. I also discovered that the case must match in the paths from github, go.mod, & the import in the actual source. Thanks
