### ISSUE TITLE
undefined: syscall.SIGTSTP on windows

### ISSUE THREAD

**Issue by timestee** [golang/go#32181]
go version:
```shell
go version go1.12 darwin/amd64
```
go ver:
```shell
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
```

when cross-compilation for windows on mac osx under  go1.12
```shell
GOOS=windows GOARCH=amd64 go build -ldflags="-s -w"
```

Failed with "undefined: syscall.SIGTSTP",

**Comment by ianlancetaylor** [comment]
The syscall package is intentionally system dependent.  There is nothing like the `SIGTSTP` signal on Windows, so the syscall package does not define it.  Closing because this is working as expected.
