### ISSUE TITLE
package declaration without quotes while import package use quotes

### ISSUE THREAD

**Issue by icyhat** [golang/go#32185]
### What did you do?

1. searched 5+ answers
2. compare about 3+ other languages

the reason may be for white space in path
1. as the language forbid space in `package hello world` already
2. why not forbid space in  `import hello world `?
3. so we won't stroke 4 keys(Shift + ')  per name

Saving time, saving life, let's go!
### What did you expect to see?
```
package main
import os
```

### What did you see instead?
```
package main
import "os"
```
### Go 2.0 
Or, may make it simplest, use keyword `in` and `out`
```
out main

in
    fmt
    str  strings

fn main()
    fmt.Println(str.Title("let's go!"))

```

**Comment by ianlancetaylor** [comment]
The package declaration is an identifier, that importing packages will then use to refer to names defined in the package.

The import statement uses a file path.  It's perfectly reasonable to put the package `frobber` into the directory `My Packages`, in which case we have

    package frobber

and

    import "My Packages/frobber"

So this is working as designed.

**Comment by icyhat** [comment]
> The package declaration is an identifier, that importing packages will then use to refer to names defined in the package.
> 
> The import statement uses a file path. It's perfectly reasonable to put the package `frobber` into the directory `My Packages`, in which case we have
> 
> ```
> package frobber
> ```
> 
> and
> 
> ```
> import "My Packages/frobber"
> ```
> 
> So this is working as designed.

Thanks for clear demo.

I downloaded go src code, open vim
1. `:r! find go-master -type f -name "*.go" | xargs pcre2grep -M 'import[\s\S]*?(?=\n\n)'`
2. 41004 lines that contains `import xxx`
3. then searched `/\s".* .*"`
4. only about 2 lines in a test file that did use blank in `import`
`
39482 import "a b"      // ERROR "import path"                                        
39483 import `a b`      // ERROR "import path"                                        
`
The question is why Go forcing us to stroke 4 keys per line in 40000+ lines only because about 10 lines test which may contain blank in directory and nobody use that style to import?

It cost so much, and gave us nothing. And should we continue wasting more time?

**Comment by icyhat** [comment]
Also, I do think we should Close Issues by 
1. the one who opened Issue
2. the one who handled Issue and made most of us in a common view.
3. auto closed if no one talk about the Issue in 24 hours

Will it be better for go's growing?

**Comment by ianlancetaylor** [comment]
Thanks for the comments.  For a case like this it's simpler to have only one way to do something.  The cost of two double quote characters is low.  I closed the issue because we aren't going to change anything in this area.  There is no reason to leave it open.

**Comment by icyhat** [comment]
I understood that there are more important things worth spending time on go...

Thanks your reply.

1. `import "My Packages/frobber"` vs `import My Packages/frobber`, I don't know why second way isn't a simpler and consistent way if someone do insist to make a blank in directory
2. may it's a different syntax while we can use auto import utility offered by IDE.
## as for other questions
### variable shadow
why not auto check the variable name when we `var fmt = 123` since explicitly imported "fmt" package?

leave this job to IDE or spend programmer's brains?

I just wanna make go better, more friendly and simpler if something isn't necessary, no offence.

Since your concise reply, i'll follow you~

**Comment by ianlancetaylor** [comment]
We don't  use the issue tracker for general discussion.  Please see https://golang.org/wiki/Questions.  Thanks.
