### ISSUE TITLE
x/website: provide portrait screen mode friendly style for mobile devices

### ISSUE THREAD

**Issue by hyangah** [golang/go#32183]
Browse https://tip.golang.org/cmd/go
from mobile devices, on portrait mode

Particularly the two column TOC is not ideal.

### Does this issue reproduce with the latest release?
 Yes.

### What operating system and processor architecture are you using (`go env`)?
Chrome on android

**Comment by agnivade** [comment]
I had done some work ([CL 129135](https://go-review.googlesource.com/c/tools/+/129135)) to generate the TOC at server side for the /search page. For the rest of the pages, AFAIR, the TOC is hard-coded to be 2 columns. Is this issue just about adjusting the no. of columns in TOC for mobile devices or are there other aspects to be tacked ?

@andybons @dmitshur - Is the TOC rendering logic going to be looked at in the new website revamp ?

**Comment by andybons** [comment]
@agnivade yes it’s likely we’ll look at it at some point.

**Comment by hyangah** [comment]
@agnivade I think switching to the single column mode when the width is not sufficient is sufficient for this bug.

I wished we could do something about the pre-formatted text width too but I guess I can live with it.

**Comment by seankhliao** [comment]
Seems no longer relevant now that it uses pkg.go.dev
