### ISSUE TITLE
cmd/go: allow omitting http scheme from GOPROXY

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#32191]
Currently, `GOPROXY` has to be specified as a full URL (`https://proxy.golang.org`) whereas `GOSUMDB` does not (`sum.golang.org`). Without knowing the details of the underlying protocol, this seems like an unnecessary inconsistency that will be easy for people to get wrong.

How about allowing `GOPROXY` to be specified without the URL scheme? So:

    GOPROXY=proxy.golang.org

would be treated the same as:

    GOPROXY=https://proxy.golang.org

Then in the common case, both `GOPROXY` and `GOSUMDB` can be specified in a similar way. The go command would continue to accept a full URL for `GOPROXY` so all the original flexibility is still available.

**Comment by rsc** [comment]
I agree this inconsistency is annoying and hard to explain. Let's say that a GOPROXY entry (something in the comma-separated list) without :// gets https:// inserted at the front, and let's also say that a leading https:// in GOSUMDB is dropped before the rest of the processing happens.
.

**Comment by bcmills** [comment]
One minor wrinkle: we should probably reserve dotless words for special tokens. (Today we have `off` and `direct`, and we may want to add others.)

Those will be fine with an explicit `https://` prefix.

**Comment by bcmills** [comment]
One more wrinkle: [RFC 8089](https://tools.ietf.org/html/rfc8089) allows file URIs of the form `file:/path/to/file` or `file:c:/path/to/file`. I suggest that we check for the `:/` token rather than `://`.
