### ISSUE TITLE
Need help to run mkall.sh (delve\vendor\golang.org\x\sys\unix\mkall.sh)

### ISSUE THREAD

**Issue by floodcaptain** [golang/go#32194]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.12.4 linux/arm64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>

$ go env

GOARCH="arm64"
GOBIN="/home/bin"
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build141065257=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Hi, i am interested in regenerating files for my native environment (arm64 with linux), located at :
> src/vendor/golang.org/x/sys/unix/

I looked at the file mkall.sh that generates files for Architecture/OS combination .
> src/vendor/golang.org/x/sys/unix/mkall.sh

line 51 in file mkall.sh, requires a dockerfile present at ${GOOS}/Dockerfile but i can't locate it anywhere in the source .

`line 51:  $cmd docker build --tag generate:$GOOS $GOOS`

please suggest how can i get this dockerfile .

error in running the script is as follows:
`unable to prepare context: path "linux" not found`
`Unable to find image 'generate:linux' locally`

### What did you expect to see?
I expected to find a dockerfile present in   $GOOS or atleast anywhere in the repository .

### What did you see instead?
`unable to prepare context: path "linux" not found`
`Unable to find image 'generate:linux' locally`

**Comment by bradfitz** [comment]
See the big README at https://github.com/golang/sys/tree/master/unix#building-sysunix

It's likely it won't work in some project's vendor directory.

The Dockerfile is in https://github.com/golang/sys/tree/master/unix/linux but that's an implementation detail if you follow the instructions above and run it from the upstream location.

But we already regenerate files for arm64 regularly, so you should back up and describe your actual problem (http://xyproblem.info/).

/cc @tklauser
