### ISSUE TITLE
go get (with `GO111MODULE=on`) is not grabbing the newest version of my software

### ISSUE THREAD

**Issue by gilgameshskytrooper** [golang/go#32208]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/Users/andrew/go/bin"
GOCACHE="/Users/andrew/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/andrew/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="/usr/local/bin/gcc-8"
CXX="/usr/local/bin/g++-8"
CGO_ENABLED="0"
GOMOD="/Users/andrew/Desktop/testvigo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/var/folders/2c/dff53p2915j5qx4w2vh4y47c0000gn/T/go-build068661935=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
```
mkdir testvoiceitmod && cd testvoiceitmod
go mod init testvoiceitmod
go get -u github.com/voiceittech/VoiceIt2-Go
cat go.mod
```

### What did you expect to see?
```
module testvoiceitmod

go 1.12

require (
	github.com/stretchr/objx v0.2.0 // indirect
	github.com/voiceittech/VoiceIt2-Go v2.2.0 // indirect
)
```

because the latest release on Github is v2.2.0
![releases](https://66.media.tumblr.com/f1dd101c8d253b872584106d296c8f35/tumblr_pryrbwwktD1xbkxdso1_1280.png)

### What did you see instead?

```
module testvoiceitmod

go 1.12

require (
	github.com/stretchr/objx v0.2.0 // indirect
	github.com/voiceittech/VoiceIt2-Go v1.2.1 // indirect
)
```

I guess this is pretty weird to me because the go module system worked fine until v1.2.1 (released Mar 19). Furthermore, we have minimal dependencies (the main library itself only uses the standard library, tests use testify).

**Comment by gilgameshskytrooper** [comment]
Also, `go get github.com/voiceittech/VoiceIt2-Go@latest` is also grabbing v1.2.1

**Comment by neild** [comment]
Each different major version of a module has a different module path (see the section "adding a dependency on a new major version" in https://blog.golang.org/using-go-modules), so the command to add the latest v2 version of the module would be:

```
go get -u github.com/voiceittech/VoiceIt2-Go/v2
```

**Comment by gilgameshskytrooper** [comment]
I see. thanks. I didn't know

**Comment by thepudds** [comment]
@gilgameshskytrooper It looks like you might have just updated your `go.mod` file to include a /v2 at the end of the module path on the first line?

If so, note that the /v2 version of `VoiceIt2-Go` seems depending on the v1 version of itself:

https://github.com/voiceittech/VoiceIt2-Go/commit/11950397167ab9561f273afd673a1fafeefeed45
```
module github.com/voiceittech/VoiceIt2-Go/v2

require (
	github.com/stretchr/testify v1.2.2
	github.com/voiceittech/VoiceIt2-Go v1.2.1
)
```
You might want to try https://github.com/marwan-at-work/mod to make the needed changes automatically.

**Comment by gilgameshskytrooper** [comment]
@thepudds Huh. You are right. Thanks for the tip
