### ISSUE TITLE
golang.org\x\tools\go\ssa\interp\testdata\src\strings\strings.go:3:6: missing function body

### ISSUE THREAD

**Issue by speedyhoon** [golang/go#32207]
<pre>
$ go version go1.12.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GOARCH=amd64
set GOBIN=
set GOCACHE=%userprofile%\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=%userprofile%\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=%TMP%\go-build305408746=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
cd %gopath%\src\golang.org\
git pull
go install

### What did you expect to see?
No errors

### What did you see instead?
<pre>
golang.org\x\tools\go\ssa\interp\testdata\src\strings\strings.go:3:6: missing function body
golang.org\x\tools\go\ssa\interp\testdata\src\strings\strings.go:5:6: missing function body
</pre>
https://github.com/golang/tools/blob/master/go/ssa/interp/testdata/src/strings/strings.go

**Comment by bradfitz** [comment]
You can't run "git pull" in %gopath%\src\golang.org ... that's not a git repo.

What did you actually do?

**Comment by speedyhoon** [comment]
Accidently imported "golang.org/x/tools/go/ssa/interp/testdata/src/strings" with the Alt Enter shortcut in Goland instead of "strings". 2am facepalm.

**Comment by TerraSkye** [comment]
i had the same issue, it imported `golang.org/x/tools/go/ssa/interp/testdata/src/strings`

**Comment by DCjanus** [comment]
Same issue with me, would you mind reopen this issue?

**Comment by zhangguanzhang** [comment]
at the part of the import
`golang.org/x/tools/go/ssa/interp/testdata/src/strings` change to `strings`

**Comment by ORESoftware** [comment]
I accidentally imported:

```golang
	"golang.org/x/tools/go/ssa/interp/testdata/src/fmt"
```

instead of 

```
"fmt"
```

fml

**Comment by davecheney** [comment]
This looks like a tooling bug, packages inside a folder named testdata are not source code.

**Comment by bynil** [comment]
If you are using GoLand, you can exclude these misleading packages:

![image](https://user-images.githubusercontent.com/3390634/103620492-89184c80-4f6e-11eb-8468-35941cc6acf9.png)

Ref: https://youtrack.jetbrains.com/issue/GO-8106
