### ISSUE TITLE
cmd/cover: missing whole switch body in coverage

### ISSUE THREAD

**Issue by rsc** [golang/go#32200]
cd go/src/regexp
go test -run=TestMatch -coverprofile=x.prof
go tool cover -coverhtml=x.prof

Navigate to backtrack.go and scroll down.
In the tryBacktrack function, the switch inst.Op line is itself green but the entire switch body is gray, meaning untracked. It seems as if the coverage tool did not find and instrument the body at all. This may be a systemic problem so we should try to understand it for Go 1.13, and fix it if the fix is straightforward and low risk.

/cc @robpike in case you are interested

<img width="716" alt="Screen Shot 2019-05-23 at 7 25 20 AM" src="https://user-images.githubusercontent.com/104030/58249247-5505fe80-7d2c-11e9-80e0-0140565e8602.png">

**Comment by robpike** [comment]
@rsc It doesn't do this in go1.4's version, which manipulated the AST. I suspect the bug was added during the conversion to source code manipulation.

**Comment by adg** [comment]
As a diversion, I took a quick look at this, and [managed to reproduce this](https://go-review.googlesource.com/c/go/+/179581/1/src/cmd/cover/testdata/test.go) in cmd/cover's tests.

```
func testSwitch() {
        for i := 0; i < 5; func() { i++; check(LINE, 5) }() {
                goto label2
        label1:
                if false {
                        goto label1
                }
        label2:
                switch i {
                case 0:
                        check(LINE, 1)
                case 1:
                        check(LINE, 1)
                case 2:
                        check(LINE, 1)
                default:
                        check(LINE, 2)
                }
        }
}
```

Adding this peculiar set of lines before the switch—a goto, a label, an if block with a goto, and another label—apparently causes `ast.Walk` to not even visit the switch's block. Will investigate further.
