### ISSUE TITLE
proposal: Set up a security policy into the github repo ^^^

### ISSUE THREAD

**Issue by sviechnikov** [golang/go#32201]

**Comment by ianlancetaylor** [comment]
I apologize if I'm missing the obvious, but what is the proposal here?  What do you mean by "set up a security policy"?

**Comment by agnivade** [comment]
I guess OP is talking about https://github.com/golang/go/security/policy

**Comment by sviechnikov** [comment]
@ianlancetaylor yeah, this one ^^

**Comment by ALTree** [comment]
In our case it would just be a link to https://golang.org/security, I guess?

**Comment by sviechnikov** [comment]
I think yes) That's will be better to have it here
