### ISSUE TITLE
x/tools/cmd/splitdwarf: build failure on Windows due to unskipped files

### ISSUE THREAD

**Issue by nilajawill** [golang/go#32212]
### What version of Go are you using (`go version`)?

<pre>
$ go version 
go1.12.5 windows/am64
</pre>

### Does this issue reproduce with the latest release?

Yes, I have the latest Go on my system.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=~\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=~\Desktop\Development\gocode
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=~\AppData\Local\Temp\go-build501080342=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

While attempting to retrieve tools (mainly godoc) by using `go get golang.org/x/tools/cmd/...` in my shell via Emacs, an error seems to be thrown by `golang.org/x/tools/cmd/splitdwarf`.

### What did you expect to see?

Nothing, as an indication that all went well.

### What did you see instead?

This is what I get in my shell:

    # golang.org/x/tools/cmd/splitdwarf
    runtime.main_mainÂ·f: function main is undeclared in the main package

However, if I try to retrieve godoc directly via `go get golang.org/x/tools/cmd/godoc`, I do not receive this message.

#### Sidenote

This doesn't affect me as I am not using splitdwarf (at least to my knowledge). I don't know how to solve this nor what caused this error, as I am pretty new to Go. Therefore, I wanted to bring it to the attention of highly capable individuals : ). Maybe it will benefit someone out there.

Thank you very much for your time and attention, 
Nilaja D Williams

**Comment by josharian** [comment]
cc @dr2chase
