### ISSUE TITLE
x/tools/cover: ParseProfiles is very slow on large coverage files

### ISSUE THREAD

**Issue by Katharine** [golang/go#32211]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/local/google/home/ktbry/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/google/home/ktbry/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/google-golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/google-golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build691661056=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I'm using a tool that uses `golang.org/x/tools/cover` to parse the coverage files output by `bazel coverage` on [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes). The resulting (perhaps somewhat pathological) output has 3 GB of output across 827 files, totalling about 36 million blocks.

### What did you expect to see?

Reasonably fast parsing of the coverage files.

### What did you see instead?

The tool spends 72 seconds inside `cover.ParseProfile`, and 61 of those seconds are spent in `ParseProfile`'s calls to `regexp.FindStringSubmatch`.

Going down the rabbit hole while I was waiting, a relatively simple (but less readable) regexp-less implementation instead spent 11 seconds in `cover.ParseProfile`, of which 2 seconds were spent in the replacement for the regexp.

**Comment by josharian** [comment]
Want to contribute your change?
