### ISSUE TITLE
wire.NewSet does not generate any code in the wire_gen.go file.

### ISSUE THREAD

**Issue by GarimaBathla** [golang/go#32217]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
I am trying to use wire. 

wire command generates some code but not complete code. 
all providers with wire.build get generated correctly in generated code. 
but function that provides are wire.NewSet (provider set) is not getting generated code. 

#### What did you expect to see?
I expect to see that either wire will give an exception on why wire.NewSet is not getting resolved.

#### What did you see instead?
No exception. just generated code has 2 sections.. 
// Injectors
And
// file.go
with function with wire.NewSet

func ProvideClients(configFilePath string) (error, *dsc.Client, *dsc.NCFile) {
	initLogger()
	wire.NewSet(provideConfig, provideSSHClient, provideCMDExecutorInstance, provideDSCClient, provideNCFileClient)
	return nil, nil, nil
}

1) Am I missing something here, not much info on provider sets code generation online
2) And also running go generate doesn't really generate any wire code? is it suppose to?
#### Does this issue reproduce with the latest release (go1.12.5)?
Haven't tried.

#### System details

```
go version go1.12.4 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/gb186037/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/gb186037/Projects/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version go1.12.4 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.12.4
uname -v: Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
lldb --version: lldb-900.0.45
  Swift-4.0
```

**Comment by odeke-em** [comment]
Welcome to the Go project @GarimaBathla and thanks for opening this!

I don't think this is the correct repository, perhaps you are looking for  https://github.com/google/go-cloud? Kindly paging @zombiezen

**Comment by zombiezen** [comment]
https://github.com/google/wire is the correct repo. Routed to google/wire#182.
