### ISSUE TITLE
dangling instance still alive although nothing pointing at it (not bug, maybe proposal)

### ISSUE THREAD

**Issue by ljubomirb** [golang/go#32226]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 windows/amd64
</pre>

### What did you do?

```
package main

import (
	"fmt"
	"time"
)

type someStruct struct {
}

func (s *someStruct) f1(ID string) {
	for {
		select {
		case <-time.After(time.Millisecond * 500):
			fmt.Print(ID)
		}
	}
}

func main() {
		
	m := someStruct{}
	go m.f1("X")
	
	m = someStruct{}
	go m.f1("O")
	
	time.Sleep(time.Second * 5)
}
```

> result: XOXOXOXOXOXOXOXOXO

### What did you expect to see?
When `m` is an instance of `someStruct`, but a new instance is created and assigned to the **same** `m`, I was hoping the first one might get GC-ed.

### What did you see instead?
Although nothing was pointing to the first instance, it remained alive and working.

--
I am very aware this is an issue of a bad coding, nothing to say about it, but this things happen and are of type of hard to find bugs.
While I understand it would be impossible for compiler to know when something is safe to assign, I was just curious - is there a way for garbage collector to notice these cases, and simply kill, no questions asked?

**Comment by randall77** [comment]
I think you may be confusing objects and goroutines. Even if the first `someStruct` you allocated is garbage collected, the first goroutine you created will keep running. There's no fixed association between the two.

The garbage collector will not stop running goroutines, ever.
