### ISSUE TITLE
cgo fatal error

### ISSUE THREAD

**Issue by litao09h** [golang/go#32228]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.3 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build471889977=/tmp/go-build -gno-record-gcc-switches"
</pre></details>
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xffffffffffffffe4 pc=0x7f2cc6e3b5c6]
runtime stack:
.throw(0xf2701c, 0x2a)
/usr/local/go/src/runtime/panic.go:616 +0x81
runtime.sigpanic()
/usr/local/go/src/runtime/signal_unix.go:372 +0x28e
goroutine 18337733 [syscall]:
runtime.cgocall(0xcb9d50, 0xc421bb9c90, 0x7f2c80812320)
/usr/local/go/src/runtime/cgocall.go:128 +0x64 fp=0xc421bb9c50 sp=0xc421bb9c18 pc=0x403374
/path/to/myfunc._Cfunc_start(0x7f2c80813a30, 0x0)
_cgo_gotypes.go:181 +0x4d fp=0xc421bb9c90 sp=0xc421bb9c50 pc=0xa3d0bd
/path/to/xx.Init(0xc42e98acb0, 0x71c0, 0xc42b4ff330, 0xc, 0xc42b4ff320, 0xb, 0xc42b4ff319, 0x1, 0xc428d29700, 0x32, ...)
/path/to/xg.go:90 +0x637 fp=0xc421bb9dd8 sp=0xc421bb9c90 pc=0xa3d997

### What did you do?

Estimated to be related to memory gc

### What did you expect to see?

The cause of the problem, how to avoid it

**Comment by bradfitz** [comment]
Sorry, there's not enough information here to help you. (There's actually no information)

See the cgo rules at https://golang.org/cmd/cgo/, try Go 1.12, run with GODEBUG=cgocheck=2 (per that earlier URL), and try the golang-nuts mailing list if you have further question.
