### ISSUE TITLE
x/mobile  does anyone still supported x/mobile label?

### ISSUE THREAD

**Issue by orange-jacky** [golang/go#32220]
i find that issue of golang  can be fixed still, meanwhile,  the issue of x/mobile barely be fixed.
does anyone of golang official still supported x/mobile issue?

hope the reply

**Comment by bcmills** [comment]
The issue tracker is probably not the right venue for this. You might try a thread on the `golang-nuts` or `golang-dev` list.

Do note, per https://go.googlesource.com/mobile#go-support-for-mobile-devices:
> The Go Mobile project is experimental. Use this at your own risk. While we are working hard to improve it, neither Google nor the Go team can provide end-user support.

(@hyangah does triage issues, but for the most part `x/mobile` is maintained by volunteers.)
