### ISSUE TITLE
x/playground: error output inserts "# play" line with multi-file programs

### ISSUE THREAD

**Issue by ldb** [golang/go#32237]
### What version of Go are you using (`go version`)?
go1.12.5

### Does this issue reproduce with the latest release?
Did not test yet.

### What operating system and processor architecture are you using (`go env`)?
play.golang.org

### What did you do?

While working on a fix for #32064 I noticed that compile errors are prepended with `# play`.
![Bildschirmfoto 2019-05-24 um 23 23 54](https://user-images.githubusercontent.com/10501668/58357651-f0f25000-7e7b-11e9-88fd-1f9f8a704e45.png)

[Example](https://play.golang.org/p/NWzBoeaOM-T)

### What did you expect to see?
There should be no `# play` before the error output.

### What did you see instead?
`# play` before the first line of error output.

**Comment by cosmonawt** [comment]
This seems to be another instance of what is already happening and being treated in [sandbox.go:388](https://github.com/golang/playground/blob/master/sandbox.go#L388) to me.

**Comment by bradfitz** [comment]
@julieqiu, do you feel strongly that this is Go 1.13 thing? We can update the playground whenever and it's not tied to the Go release process or repo, which is why gopherbot added the Unreleased milestone.

**Comment by julieqiu** [comment]
I do not - I added the milestone because I assumed this is something that we would resolve by Go 1.13. Changed it back to Unreleased.
