### ISSUE TITLE
x/build/env/linux-ppc64/osuosl: upgrade ppc64 machines from Debian jessie to stretch

### ISSUE THREAD

**Issue by bradfitz** [golang/go#32234]
Our big endian ppc64 machines run Debian jessie, which is no longer really supported by Debian, and apt-get update doesn't work (without changing to the archives.debian.org URL).

We should just upgrade them to stretch.

/cc @dmitshur

**Comment by bcmills** [comment]
Stretch reached EOL on June 30, 2022.
