### ISSUE TITLE
sync.WaitGroup support timeout

### ISSUE THREAD

**Issue by huangxuwen** [golang/go#32230]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by polarina** [comment]
You can use [`golang.org/x/sync/errgroup`](https://godoc.org/golang.org/x/sync/errgroup) to achieve this. Call `WithContext` and pass in a context that gets cancelled after a timeout.

**Comment by mvdan** [comment]
What @polarina said. I also don't see how we could add support for this without breaking existing users or without adding extra overhead. You could also just use channels and a combination of `select` with a timer.
