### ISSUE TITLE
cmd/link: combining dwarf failed: Unknown load command 0x80000018 (2147483672)

### ISSUE THREAD

**Issue by triztian** [golang/go#32233]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.12.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
λ dwarfunk ~> go env
GOARCH="amd64"
GOBIN="/Users/Tristian/go/bin"
GOCACHE="/Users/Tristian/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/Tristian/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/Tristian/Repositories/github.com/triztian/dwarfunk/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7s/cnfg6ksj44gb3br_lc4v3gn40000gp/T/go-build997778752=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Tried to install the `main` package

### What did you expect to see?

A successful linking and executable for the macOS platform.

### What did you see instead?

The following error:

<details><summary><code>go install</code> Output</summary><br><pre>
# github.com/triztian/dwarfunk
/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64/link: /usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x80000018 (2147483672)
</pre></details>

### Notes 

I've created the following repo to reproduce the issue:

 * https://github.com/triztian/dwarfunk

The subpackage `github.com/triztian/dwarfunk/lib` contains an objective-c file and successfully builds using the `go build` command:

```
go build ./lib
```
I've noticed that if I edit the `objc.m` file and [remove the following line](https://github.com/triztian/dwarfunk/blob/master/lib/ObjC.m#L6), then the `go install` command works.

Looking at the following CL, it _seems_ like the command is not part of the list:

 * https://go-review.googlesource.com/c/go/+/119115/5/src/cmd/link/internal/ld/macho.go#147

Could it be that the the command has to be added and `OR` ed as depicted in the `ruby-macho` library?

 * https://github.com/Homebrew/ruby-macho/blob/master/lib/macho/load_commands.rb#L37

**Comment by thanm** [comment]
Problem appears to be [here](https://github.com/golang/go/blob/496b8dbbfcd39cc51e1dfc1e9be90b7e61179009/src/cmd/link/internal/ld/macho.go#L144) I think. Looks like the constant defined for LC_LOAD_WEAK_DYLIB is incorrect. I will send a patch.

**Comment by triztian** [comment]
Awesome, thank you for the quick response,  it probably has to be more like `0x80000018`

**Comment by thanm** [comment]
Hi @triztian 

I've made an attempt to adapt your reproducer as a testcase -- see https://golang.org/cl/178726. My first attempt is problematic in that I it contains code that doesn't work with older versions of MacOS, e.g. 10.11, since it refers to the UserNotifications framework.

I can add guards via #ifdef to insure that those constructs are conditionally compiled based on the OS version, e.g. 

```
#import <Foundation/Foundation.h>
#if (__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__>101300)
#import <UserNotifications/UserNotifications.h>
#endif
```

however I can't use the same trick with the cgo directives. Something like

```
#if (__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__>101300)
#cgo darwin LDFLAGS: -framework Foundation -framework UserNotifications
#endif
```

doesn't have the desired effect, since cgo doesn't run the C preprocessor.

A question for you: is it possible to reproduce the same DWARF issue without using the newer framework (e.g. just using something from the Foundation framework)?

Thanks, Than

**Comment by thanm** [comment]
OK, I think I have a revised testcase that works.

**Comment by triztian** [comment]
@thanm I stumbled into the issue randomly because I was trying to use the `UserNotifications` framework from Go.

I don't have an alternative way to reproduce that issue. I could look into how we can get the compiler to produce a binary that specifically uses that MACH-O command.

Ah, from looking at the revised test case, did you try different frameworks randomly?

Thank you for looking into this issue!
