### ISSUE TITLE
Question: how to get smaller code size for "Hello world" example?

### ISSUE THREAD

**Issue by TerryGuo** [golang/go#32250]
Hi there,
According to the section [Reducing the size of Wasm files](https://github.com/golang/go/wiki/WebAssembly#reducing-the-size-of-wasm-files) from Wiki, we can get 575 bytes for the "Hello world" example with Tinygo, however the code size I got with Tinygo is 64KB. Could someone please give me some help? 
Below is my "Hello world" example:
```
package main

import (
        "fmt"
)

func main() {
        fmt.Println("Hello world!")
}
```

And command use to build it:
`~/tinygo/tinygo/bin/tinygo build  -target wasm -o wasm.wasm main/main.go`

And the size is:
`64K May 25 23:19 wasm.wasm`

The Tinygo version is:
`tinygo version 0.5.0 linux/amd64`

**Comment by martisch** [comment]
Hello TerryGuo. This is the bug tracker of the Go project and not used for Questions.
The Tinygo compiler is a different project. Please see https://github.com/tinygo-org/tinygo#getting-help for Getting help with Tinygo.
