### ISSUE TITLE
x/tools/gopls: implement didChangeConfiguration

### ISSUE THREAD

**Issue by zchee** [golang/go#32258]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +385b2e0cac Fri May 24 21:34:53 2019 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Might be Yes. It's related LSP protocol spec.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zchee/.cache/go-build"
GOENV="/Users/zchee/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zchee/go"
GOPROXY="https://proxy.golang.org"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"
CXX="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++"
CGO_ENABLED="1"
GOMOD="/Users/zchee/go/src/github.com/zchee/nvim-lsp/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6_/10hjzx0d027_8rfblcw1lbm40000gp/T/go-build972805647=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

`gopls` send `protocol.RegistrationParams` when `initialized`, the ref is here:

https://github.com/golang/tools/blob/7be61e1b0e514e106d83fc439d56a79143738603/internal/lsp/general.go#L117-L125

But AFAIK, the `vscode-languageserver-node/client` just ignore if `[]Registration. RegisterOptions` is empty.

- `vscode-languageserver-node/client.register`
    - https://github.com/microsoft/vscode-languageserver-node/blob/625fbdbe492f7b4b95e6d29e0adf36c01b88d056/client/src/client.ts#L790-L792
- `internal/lsp/protocol/Registration.RegisterOptions`
   - https://github.com/golang/tools/blob/7be61e1b0e514e106d83fc439d56a79143738603/internal/lsp/protocol/tsprotocol.go#L177

I also now develop Language Server Protocol `client` side for IDE written in Go, but I can't handle that `gopls` send `RegisterCapability` call.

### What did you expect to see?

empty `Registration.RegisterOptions` fields `RegisterCapability` call.

### What did you see instead?

non-nil `Registration.RegisterOptions`.

**Comment by stamblerre** [comment]
Thanks for catching this! This means that the `RegistrationOptions` field of the `Registration` struct should be an `*interface{}`, not an `interface{}`. @pjweinb, can you make this change in the TypeScript generator?

**Comment by zchee** [comment]
@stamblerre
Also, the `Registration.ID` will use to `client/unregisterCapability` call.
It would be better to use unique ID such as UUID like LSP spec.

```json
{
	"method": "client/registerCapability",
	"params": {
		"registrations": [
			{
				"id": "79eee87c-c409-4664-8102-e03263673f6f",
				"method": "textDocument/willSaveWaitUntil",
				"registerOptions": {
					"documentSelector": [
						{ "language": "javascript" }
					]
				}
			}
		]
	}
}
```

- https://github.com/golang/tools/blob/7be61e1b0e514e106d83fc439d56a79143738603/internal/lsp/general.go#L119
- https://microsoft.github.io/language-server-protocol/specification#client_registerCapability

**Comment by ianthehat** [comment]
The id only has to be unique within the server (not the client) and is only used if you make an unregister call.
Given that we only register in this function, which only happens once, and we never unregister, the current values meet the requirements for uniqueness.

**Comment by pjweinb** [comment]
I think I do not understand.
1. In the LSP Typescript specification, RegisterOptions is an optional
field with type any. The Go code (tsprotocol.go:177) has interface{} for
the corresponding type, and "omitempty" for json. What should be a pointer?
2. Gopls is using the name of the method as the id in registering a
capability. That seems like a good thing to use if it wants to unregister
the capability later. (Using the method name means that it doesn't need to
remember a separate ID.)

**Comment by zchee** [comment]
@stamblerre @ianthehat @pjweinb 
I'll details reply later, but I understand and totally agreed @ianthehat @pjweinb said.

Anyway, I posted issue first means not "should be a pointer", "misuse `RegisterCapability` call". I think no needs to change to pointer too. Because that's specificication like RFC.

**Comment by stamblerre** [comment]
I'm sorry, I misunderstood - I now see that we don't correctly implement didChangeConfiguration.

**Comment by zchee** [comment]
@stamblerre

> I'll details reply later

At first, Sorry for not reply to details comment.

But yeah, `RegistrationOptions` is optional field on LSP spec, but actually it required param for handle `RegisterCapability` on client side.
So, we should adding any `interface{}` value to `RegistrationOptions` instead of change to pointer.

Thanks for reading my comment!
