### ISSUE TITLE
Add issue number in branch name

### ISSUE THREAD

**Issue by Windsooon** [golang/go#32263]
The [golang docs make_branch](https://golang.org/doc/contribute.html#make_branch) didn't mention what branch name we should use when we create a new branch for an issue. (I know we added the issue number to the commit messages). Learned from the Python and Django communities, I suggest we use `bog-XXXX` as the branch name (short for "bug of golang") for the issue already created. IMO, that will make maintainers easier to review the PR.

**Comment by martisch** [comment]
The local branch name is not shown in the Go gerrit instance: https://go-review.googlesource.com/  as normal contributions are always made on the master branch into which they are later cherry picked. It does not seem to make it easier for maintainers and constrains the freedom of contributors to have their own system to organizer their CLs. Not every commit has a bug associated with the effort either.

Could you elaborate how this will help maintainers?

**Comment by ianlancetaylor** [comment]
I don't think there is anything to do here.  You can choose any branch name you like.  It won't make any difference to the code review process or to the master repository.  Closing the issue, but please comment if you disagree.
