### ISSUE TITLE
what mean supported os

### ISSUE THREAD

**Issue by rekby** [golang/go#32268]
For example:
https://golang.org/doc/go1.12

>  Go 1.12 is the last release that will run on macOS 10.10 Yosemite. Go 1.13 will require macOS 10.11 El Capitan or later. 

Mean go compiler run on macOS 10.10 and later or compiled binary will run on maxOS 10.10 and later?

**Comment by martisch** [comment]
Things may still work but both go compiler and the binaries the go compiler produces are only supported meaning its considered a bug if they dont work on the platforms supported.
