### ISSUE TITLE
sync: TestPoolChain occasionally fails on linux-arm64

### ISSUE THREAD

**Issue by erifan** [golang/go#32265]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +d97bd5d07a Sat May 25 22:38:01 2019 +0000 linux/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/hostname/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/hostname/gopath"
GOPROXY=""
GORACE=""
GOROOT="/home/hostname/go1.12"
GOTMPDIR=""
GOTOOLDIR="/home/hostname/go1.12/pkg/tool/linux_arm64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/hostname/go-master/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build909981503=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Run all.bash

### What did you expect to see?

ALL TESTS PASSED

### What did you see instead?
--- FAIL: TestPoolChain (0.00s)
    pool_test.go:242: popHead never succeeded
FAIL
FAIL	sync	1.312s

The test was first added in https://go-review.googlesource.com/c/go/+/166957, and a comment said that "In theory it's possible in a valid schedule for popHead to never succeed, but in practice it almost always succeeds, so this is unlikely to flake". But this test occasionally fails on two of our machines. On one of these two machines, the frequency of this error is not small, it occurred six times in our last 11 runs.
\cc @aclements

**Comment by erifan** [comment]
This error can also be seen in the Go Dashboard:
https://build.golang.org/log/fb59b25c744918866a47130551b6c7cf09bf384e

**Comment by bradfitz** [comment]
Dup of #31422
