### ISSUE TITLE
json.Unmarshal should empty other field.

### ISSUE THREAD

**Issue by orestonce** [golang/go#32262]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build501657845=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
1.  Set the json tag <code>omitempty</code>
2. Marshal "{ Tom, 15 } {Jerry, 0}" to 2 binary
3. Use only one temp object unmarshal from 2 binary above
4. I got a nil error but the Jerry object not equal last binary expected.
https://play.golang.org/p/b0SSaOM0fis

### What did you expect to see?
{Tom, 15}
{Jerry, 0}

### What did you see instead?
{Tom, 15}
{Jerry, 15}

**Comment by orestonce** [comment]
It will also happen when get a reused object from sync.Pool. So I suggestion the json.Unmarshal should empty other fields that not include by the binary.
https://play.golang.org/p/0YAc5hytSed

**Comment by opennota** [comment]
https://play.golang.org/p/tKhpbhPG206

**Comment by agnivade** [comment]
Can you elaborate why you think it should empty an existing field ? You are unmarshalling to an already populated struct. So it will only populate fields which are present in the input text. That is what is documented - 

> To unmarshal JSON into a struct, Unmarshal matches incoming object keys to the keys used by Marshal (either the struct field name or its tag), preferring an exact match but also accepting a case-insensitive match.

Either you need to use a new struct every time or remove the omitempty tag.

I don't see any bug here. On the contrary, consider you have a struct with other metadata fields already populated. And you just want to unmarshal some fields from a json text. But if what you say happens, then it should wipe off all other fields not in the json text. I don't think that is right behavior.
