### ISSUE TITLE
io: CopyBuffer should document when buf is not used

### ISSUE THREAD

**Issue by sandyskies** [golang/go#32276]
The follow is the comment for io.CopyBuffer,
// CopyBuffer is identical to Copy except that it stages through the
// provided buffer (if one is required) rather than allocating a
// temporary one. If buf is nil, one is allocated; otherwise if it has
// zero length, CopyBuffer panics.
func CopyBuffer(dst Writer, src Reader, buf []byte) (written int64, err error) 

 which is not precise enough, in the case of src implements the WriterTo interface or the case of if dst implements the ReaderFrom interface , buf will be ignore ,which is not mentioned at all. Which is very easy to lead people to wrong way.

**Comment by bcmills** [comment]
This closely relates to #16474.

**Comment by sandyskies** [comment]
@bcmills  Before the API is changed, we should add more comment to explain the behavior. This PR
is for adding the comment. https://github.com/golang/go/pull/32279
