### ISSUE TITLE
panic: overlapping edits

### ISSUE THREAD

**Issue by aykevl** [golang/go#32271]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes, with Go compiled from 45d74aad539c645d4e50a405f55ca46811dd70d6.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ayke/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ayke"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build818149774=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### Reproducing

I'm not exactly sure how to reproduce this yet, but this is the error I'm getting:

```
panic: overlapping edits: [52942,53034)->"func() { _cgo0 := /*line :1305:33*/b.C; _cgo1 := _Ctype_uint(line); _cgoCheckPointer(_cgo0); _cgoCheckPointer(_cgo1); _Cfunc_LLVMSetCurrentDebugLocation2(_cgo0, _cgo1); }()", [52996,53006)->" /*line :1305:56*/_Ctype_uint /*line :1305:66*/"
```

It is clearly related to CGo _somehow_ and I think it may be caused by a signature mismatch. There are two symbols with the same name and a different signature. One lives in the Go package as a .cpp file, the other is declared in a header file (included by CGo) and lives in an archive file. My theory is that CGo picks the one at one time and a different one some other time which leads to a conflict.
That's a lot of guessing and little reproducing. But this is a large and complicated system and I'm not sure how to make it smaller, but perhaps you can see something that is wrong so I can look into it further?

Tested with two different system linkers: `ld.bfd` and `ld.lld-8`.

Sort-of related:
https://reviews.llvm.org/D60484
https://reviews.llvm.org/rL358086

Also: this is with Go modules disabled, if that is relevant.

**Comment by ianlancetaylor** [comment]
Tell us exactly what you did and exactly what happened.  Not just a single snippet from the output.  Thanks.

Also, if you are using the original Go 1.12 release as suggested above, try the Go 1.12.5 release.  There have been some bug fixes that may be relevant.
