### ISSUE TITLE
x/tools/cmd/godoc: unicode/utf8 package docs are not renderable

### ISSUE THREAD

**Issue by kevinburke** [golang/go#32275]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +a326bc6df2 Wed May 22 17:22:46 2019 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kevin/Library/Caches/go-build"
GOENV="/Users/kevin/Library/Preferences/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/kevin"
GOPROXY="direct"
GOROOT="/Users/kevin/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/Users/kevin/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sf/fsn3_vgd0n98r0jb86bgp83r0000gn/T/go-build304907158=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version devel +a326bc6df2 Wed May 22 17:22:46 2019 +0000 darwin/amd64
GOROOT/bin/go tool compile -V: compile version devel +a326bc6df2 Wed May 22 17:22:46 2019 +0000
uname -v: Darwin Kernel Version 17.7.0: Wed Feb 27 00:43:23 PST 2019; root:xnu-4570.71.35~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G6030
lldb --version: lldb-1000.11.38.2
  Swift-4.2
</pre></details>

### What did you do?

- Compile Go tip
- Use tip to compile x/tools/cmd/godoc
- Start godoc
- Load http://localhost:6060/pkg/unicode/utf8 in any browser

### What did you expect to see?

Package text for utf8

### What did you see instead?

```
/src/unicode/utf8/utf8.go:28:8: expected ';', found b00000000 (and 10 more errors)
```

I cannot reproduce this on tip.golang.org/pkg/unicode/utf8 (maybe it is Darwin specific, or are we supposed to be using that now, or??)

**Comment by agnivade** [comment]
Works here on linux/amd64. Possibly darwin specific.

**Comment by josharian** [comment]
The unicode/utf8 package uses binary literals, which were introduced in 1.13. I suspect that somehow or other you are using a 1.12 toolchain or a 1.12 go/types.

**Comment by bradfitz** [comment]
I also can't reproduce.

I see you're not using modules. (`GO111MODULE="off"` in your `go env` output, and May 22 build predates flipping it on by default right?). It's possible that your build of "tip" x/tools/cmd/godoc is picking up a not-tip dependency from $GOPATH.

**Comment by kevinburke** [comment]
I'm on Darwin. I just pulled down Go tip (0f897f916aa6734bb8d089400ea996ee461ae41f), as of ten minutes ago, compiled it using Go 1.12 as a bootstrap, used that to recompile x/tools and I can still reproduce the error.

x/tools only depends on the standard library, x/net and x/sync, and all of those are pointing to their most current versions. I'm not sure  go/types can be out of date, it is provided by the Go googlesource.com repository and I just downloaded/recompiled that.

I cannot reproduce the error with the x/website/cmd/golangorg binary.

**Comment by bradfitz** [comment]
Just tried tip on my Mac and still can't reproduce.

**Comment by kevinburke** [comment]
Ugh, apologies... the Go tool was up to date, and godoc was being recompiled, but somehow an old `godoc` binary snuck into `/usr/local/bin` ahead of `$GOPATH/bin` and I was running that, instead. If you are hitting this error double check your godoc binary was not compiled using 1.11.
