### ISSUE TITLE
x/playground: document all its tricks

### ISSUE THREAD

**Issue by bradfitz** [golang/go#32294]
The playground is underdocumented: 

* test mode
* multiples files, mod files
* images
* sleeps
* clearing screen

Document & link from play.golang.org.

**Comment by ysmolsky** [comment]
Thanks, I agree, especially after the addition of modules. I saw couple of times in tickets people raising eyebrows when they hear about playground having testing. How do we proceed on this beyond extending the about page? It seems to be that nobody reads the about page. Maybe writing a post for Go blog?

Also should we document and expose the way multifiles supported via txtar or wait until we have some kinda non-text interface for it?

_I admit, I was distracted heavily from playground by my job, and I have lot's of unclosed playground tickets here :-)_

**Comment by bradfitz** [comment]
I think to the right of the Share button we should have:

    Examples: [  fun trick 1             \/ ]
              [  fun trick 2                ]
              [  fun trick 3                ]
              [  fun trick 4                ]
              [  fun trick 5                ]
              [  fun trick 6                ]

And have those pre-load some representative features (multi-files, tests, images, sleep animations w/ clearing the screen, etc).

That would make it more prominent.

The golang.org homepage has something similar:

<img width="483" alt="Screen Shot 2019-05-29 at 7 58 35 AM" src="https://user-images.githubusercontent.com/2621/58567675-9a707300-81e7-11e9-88e7-80f0c3f28a7e.png">
