### ISSUE TITLE
issue on go append function

### ISSUE THREAD

**Issue by RoynKo** [golang/go#32296]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/royn/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/.../go"
GOPROXY=""
GORACE=""
GOROOT="/.../go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/.../go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1w/b85zrz3s2jbg6vh10_xzf0500000gn/T/go-build187517297=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</pre></details>

### What did you do?
Just tried to run the following code
```go
package main

import (
	"fmt"
)

func main() {
	arr := make([]int, 0)
	for i := 0; i < 6; i++ {
		arr0 := append(arr, 0)
		arr1 := append(arr, 1)
		fmt.Printf("%v %v\n", arr0, arr1)
		arr = arr0
	}
}
```

link to go playground, which returns a different wrong output:
https://play.golang.org/p/pzvyzNWjUbU

### What did you expect to see?
expected output:
```
[0] [1]
[0 0] [0 1]
[0 0 0] [0 0 1]
[0 0 0 0] [0 0 0 1]
[0 0 0 0 0] [0 0 0 0 1]
[0 0 0 0 0 0] [0 0 0 0 0 1]
```

### What did you see instead?
actual output:
```
[0] [1]
[0 0] [0 1]
[0 0 0] [0 0 1]
[0 0 0 1] [0 0 0 1]
[0 0 0 1 0] [0 0 0 1 1]
[0 0 0 1 0 1] [0 0 0 1 0 1]
```

**Comment by robpike** [comment]
It's working as intended, or at least as defined. The underlying array is shared until it can't be. You might find https://blog.golang.org/slices instructive.
