### ISSUE TITLE
gccgo: libgo runtime/pprof regression introduced by r271172 on ppc64le

### ISSUE THREAD

**Issue by laboger** [golang/go#32290]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.2 gccgo (GCC) 10.0.0 20190528 (experimental) linux/ppc64le
</pre>

### Does this issue reproduce with the latest release?
Latest gccgo from trunk.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
ppc64le/linux
gccgo trunk

</pre></details>

### What did you do?
Test failure occurs in the libgo testsuite in runtime/pprof test. The failures started before r271193 and after 271168, so I'm suspecting r271172.

--- FAIL: TestMutexProfile (0.11s)
    --- FAIL: TestMutexProfile/debug=1 (0.10s)
        pprof_test.go:788: received profile: --- mutex:
            cycles/second=1000000859
            sampling period=1
            1 1 @ 0x1000d258
            #	0x1000d257	pprof.blockMutex..func1+0x47	/home/boger/gccgo.work/trunk/bld/powerpc64le-linux/libgo/gotest108541/test/pprof_test.go:750
            
        pprof_test.go:796: expected 6 lines, got 5 "--- mutex:\ncycles/second=1000000859\nsampling period=1\n1 1 @ 0x1000d258\n#\t0x1000d257\tpprof.blockMutex..func1+0x47\t/home/boger/gccgo.work/trunk/bld/powerpc64le-linux/libgo/gotest108541/test/pprof_test.go:750"
            --- mutex:
            cycles/second=1000000859
            sampling period=1
            1 1 @ 0x1000d258
            #	0x1000d257	pprof.blockMutex..func1+0x47	/home/boger/gccgo.work/trunk/bld/powerpc64le-linux/libgo/gotest108541/test/pprof_test.go:750
    --- FAIL: TestMutexProfile/proto (0.00s)
        pprof_test.go:823: parsed proto: PeriodType: contentions count
            Period: 1
            Time: 2019-05-28 12:38:39.044234671 -0500 CDT
            Samples:
            contentions/count delay/nanoseconds
                      1          0: 1 
            Locations
                 1: 0x1000d257 M=1 pprof.blockMutex..func1 /home/boger/gccgo.work/trunk/bld/powerpc64le-linux/libgo/gotest108541/test/pprof_test.go:750 s=0
            Mappings
            1: 0x10000000/0x10450000/0x0 /home/boger/gccgo.work/trunk/bld/powerpc64le-linux/libgo/gotest108541/test/a.out  [FN]
            2: 0x7bbe618a0000/0x7bbe61ab0000/0x0 /lib/powerpc64le-linux-gnu/libc-2.27.so 0c8d19aea66e0184dbaac8bdd92ab60bea75e7b7 
            3: 0x7bbe61ad0000/0x7bbe61af0000/0x0 /home/boger/gccgo.work/trunk/bld/gcc/libgcc_s.so.1  
            4: 0x7bbe61b10000/0x7bbe61c40000/0x0 /lib/powerpc64le-linux-gnu/libm-2.27.so 5968523ac787ff1e8378356a275096a591455905 
            5: 0x7bbe61c60000/0x7bbe61c90000/0x0 /lib/powerpc64le-linux-gnu/libpthread-2.27.so 38a19c9d996f258d2cd3ba239570e6d6a9ebca1b 
            6: 0x7bbe61cd0000/0x7bbe61cf0000/0x0 [vdso]  
            7: 0x7bbe61cf0000/0x7bbe61d30000/0x0 /lib/powerpc64le-linux-gnu/ld-2.27.so 5a8b9f2892435fbbf994603c9a1b4345cc4a3e6e 
        pprof_test.go:834: No matching stack entry for [sync.Mutex.Unlock pprof.blockMutex..func1]
FAIL
Keeping gotest108541
FAIL: runtime/pprof
We see it on power8 and power9.

I ran it by doing 'make check-go' from the build directory.

**Comment by bcmills** [comment]
That revision is [CL 171497](https://golang.org/cl/171497), for those following along.

CC @ianlancetaylor @thanm @cherrymui

**Comment by thanm** [comment]
This is almost certainly due to my CL, 171497.  Not clear why this would be machine/arch dependent, though.

**Comment by thanm** [comment]
Pre-fixup stack on x86_64:

```
 0x10151c98 runtime.saveblockevent
 0x10153194 sync.event
 0x101533bc runtime.semrelease1
 0x10157ae8 sync.runtime_Semrelease
 0x1019386c sync.Mutex.Unlock
 0x1000c1d4 runtime..z2fpprof.blockMutex..func1
 0x1001fd6c runtime..z2fpprof.runtime..z2fpprof..thunk1
 0x10149fa4 runtime.kickoff
```

Same stack on powerpc:

```
 0x005dad4c __morestack
 0x005227bb runtime.saveblockevent
 0x0052383f sync.event
 0x005239b0 runtime.semrelease1
 0x00527314 sync.runtime_Semrelease
 0x0055c13b sync.Mutex.Unlock
 0x0040ca02 runtime..z2fpprof.blockMutex..func1
 0x0041f2fe runtime..z2fpprof.runtime..z2fpprof..thunk1
 0x0051c211 runtime.kickoff
```

A call to __morestack just happened to trigger between runtime.saveblockevent and runtime.CallersRaw , and this wound up screwing up the skip count.

I think what I will need to do is rework the patch to do the skipping as part of fixup as opposed to before.
