### ISSUE TITLE
go/src/debug/dwarf: more DWARF tag and attribute constants

### ISSUE THREAD

**Issue by justinclift** [golang/go#32304]
Would an update to the DWARF attribute and tag constants be useful (eg via PR)?

* https://github.com/golang/go/blob/60cf9ec677cb87cce1480b2d442c64f051b7c007/src/debug/dwarf/const.go#L15-L86
* https://github.com/golang/go/blob/60cf9ec677cb87cce1480b2d442c64f051b7c007/src/debug/dwarf/const.go#L139-L201

Although a few DWARF4 ones are currently defined, there are still several missing.

It's nothing critical, just a bit annoying when stepping through LLVM compiled Go code which uses these newer constants.

If this would be a useful addition, I'll create a suitable PR.  Can also include the DWARF5 constants if that'd be useful.

**Comment by ianlancetaylor** [comment]
I think I got them all in https://golang.org/cl/175137, which was too late for 1.13 but is expected to be in 1.14.

**Comment by justinclift** [comment]
Thanks @ianlancetaylor, scanning through that quickly now, it looks fine.  Good stuff. :smile:

**Comment by justinclift** [comment]
Looks like more complete DWARF5 support is being added?

**Comment by ianlancetaylor** [comment]
Yes, also for 1.14.
