### ISSUE TITLE
x/tools/cmd/goimports: strict ordering of local packages

### ISSUE THREAD

**Issue by romikser** [golang/go#32301]
Support for multiple packages was added [here](https://github.com/golang/go/issues/19188).
It would be good to be able to specify strict order of local packages. 
For example if I specify local packages as `mycompany.com/foo,mycompany.com/bar` `mycompany.com/foo` imports will always be placed above `mycompany.com/bar` packages.

**Comment by josharian** [comment]
I dunno; I'd rather not. The less configuration, the better. As it stands, you won't get code churn if two people set up their flags differently.

**Comment by heschik** [comment]
We don't want to add more configuration to `goimports`, and this hasn't attracted much attention, so closing. Please comment if you disagree.
