### ISSUE TITLE
os: let FileInfo type also contain the full path, not just basename

### ISSUE THREAD

**Issue by rogierlommers** [golang/go#32300]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?
I often use the [FileInfo type](https://golang.org/src/os/types.go?s=369:411#L20) to work with files. The file struct now contains the following:

```
type FileInfo interface {
	Name() string       // base name of the file
	Size() int64        // length in bytes for regular files; system-dependent for others
	Mode() FileMode     // file mode bits
	ModTime() time.Time // modification time
	IsDir() bool        // abbreviation for Mode().IsDir()
	Sys() interface{}   // underlying data source (can return nil)
}
```

Now I was wondering: why doesn't it contain the full path to the file? I often pass around a File to functions, but I see myself always reconstruct the full path, which -in my opinion- could also be part of the File itself.

#just wondering

**Comment by mvdan** [comment]
You showed the FileInfo interface, though. File does contain the original path that was opened:

```
// Name returns the name of the file as presented to Open.
func (f *File) Name() string
```

**Comment by rogierlommers** [comment]
Sorry, my bad. To give you an example of what I usually do:

```
files, _ := ioutil.ReadDir(splittedLocation)
for _, file := range files {
  if err := processFile(file); err != nil {
    // handle err
  }
}

```

In then in the `processFile` function, I need the full file path to read the file. But then it's not available in the `fileInfo` struct.

**Comment by mvdan** [comment]
Right; then the issue should be about FileInfo to be clear.

In that case I'd simply pass the directory path along with each file. Then you can join the path with the basename easily. I'm not sure that this is a big issue.

**Comment by rogierlommers** [comment]
> Right; then the issue should be about FileInfo to be clear.
> 
> In that case I'd simply pass the directory path along with each file. Then you can join the path with the basename easily. I'm not sure that this is a big issue.

This indeed can be a workaround, but I don't see why the full filepath couldn't be part of the fileInfo struct.

**Comment by bradfitz** [comment]
a) for go1compat reasons, we can't extend the FileInfo interface, even if we wanted to.

b) a full path name isn't always available/known/unique. There could be multiple paths to a file, and only some paths that are accessible to the current user. From the point of view of Readdir, it only gets the base names from the operating systems, so that's all it can return anyway. The `*os.File` only returns the "full" name if you opened it with a full name, and it just returns the exact string you opened with, which might be relative.

Closing, because there's nothing we can do here.
