### ISSUE TITLE
sync/atomic: can Value still not be copied after the first use?

### ISSUE THREAD

**Issue by hyper0x** [golang/go#32318]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/Users/haolin/Gobin"
GOCACHE="/Users/haolin/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/haolin/Golib:/Users/haolin/Golib2:/Users/haolin/Projects/golang:/Users/haolin/Projects/gopcp/gopcp/example.v2:/Users/haolin/GeekTime/Golang_Puzzlers_FULL"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ts/7lg_tl_x2gd_k1lm5g_48c7w0000gn/T/go-build623934671=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

According to the document of type sync/atomic.Value,  `A Value must not be copied after first use`. But I see in the source code of this type that it is no longer contains the `noCopy` type and `go vet` also no longer checks for copy operations of such values.

So, is the values of sync/atomic.Value still not allowed to be copied after the first use??

By the way, I've already looked at this issue: https://github.com/golang/go/issues/21504 .

### What did you expect to see?

I want consistency about how to type sync/atomic.Value is used.

### What did you see instead?

The documentation and source code should be consistent, but they are not.

**Comment by mdempsky** [comment]
Looking at the code, I don't see any reason why Value can't be copied, as long as there aren't any [concurrent](https://golang.org/ref/mem#tmp_2) calls `Store`. It seems to me like the comment could be toned down to just warn that copying a Value isn't atomic.

It looks like the warning was added in c81a3532fea42df33dea54497dfaa96873c2d976.

/cc @valyala @ianlancetaylor

**Comment by ianlancetaylor** [comment]
The whole point of a `Value` is to be atomic.  I think I would rather keep the comment.  It's true that `go vet` no longer warns about copying, but that's OK.  I don't see anything to do here.

**Comment by hyper0x** [comment]
I still reserve my opinion. Since the statement in the documentation is useful, a detection (like the previous `go vet`) or error reporting mechanism (like `sync.Cond`) should be provided.

**Comment by ianlancetaylor** [comment]
I'm fine with a vet check if someone can figure out how to write one without breaking #21504.
