### ISSUE TITLE
failed to create new OS thread (have 916 already; errno=11)

### ISSUE THREAD

**Issue by linqh1** [golang/go#32323]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 windows/amd64

go version go1.12.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\linqh1\AppData\Local\go-build
set GOEXE=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=linux
set GOPATH=C:\Users\linqh1\go;D:\workspace\go\qtl-scada
set GOPROXY=
set GORACE=
set GOROOT=C:\Program Files\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\linqh1\AppData\Local\Temp\go-build973867170=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

I am building a SYN scanner.

And when I do stress test, I send SYN packet to same ip:port in a loop. 

And I limit the number of goroutine concurrence. Something like:

	pool := make(chan struct{},maxGoroutines)
	for {
		pool <- struct{}{}
		go func() {
			defer func() {
				<- pool
			}()
			doHalfOpenScan()
		}()
	}

After running for a period of time(about 20minutes), I found it create many threads (localhost:9999/debug/pprof/), and it crash. This log like:

    runtime: failed to create new OS thread (have 916 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc

    runtime stack:
    runtime.throw(0x907378, 0x9)
            C:/Program Files/Go/src/runtime/panic.go:608 +0x72
    runtime.newosproc(0xc0027ffc00)
            C:/Program Files/Go/src/runtime/os_linux.go:166 +0x1c0

### What did you expect to see?

It shouldn't create so many thread because the number of goroutine is fixed.

### What did you see instead?

Process crashed.

Code could be found at https://play.golang.org/p/U8Bcd0xIuX1, build and run as root

`./fast-syn-scanner -c 2000 -ip xxx.xxx.xxx.xx -port 80 -listen 9999`

**Comment by bcmills** [comment]
> Here is my code

Please provide a link on play.golang.org if possible. (Barring that, paste the code directly within a `<details>` tag and ` ```go ` Markdown block.)

It seems likely that `doHalfOpenScan` is doing something that ends up spawning a goroutine (and thread) as a side effect, and is leaking that thread instead of cancelling the operation before `doHalfOpenScan` returns. Can you confirm or eliminate that hypothesis?

The crash should be accompanied by a goroutine dump, which can help you track down the leak. (You may need to set `GOTRACEBACK=all` or `GOTRACEBACK=system` to get enough stacks to figure it out.)

**Comment by linqh1** [comment]
Code now could be found at : https://play.golang.org/p/U8Bcd0xIuX1

@bcmills I set GOTRACEBACK=all and run again. The crash log is filled with the following 2 trace:
```
goroutine 551605 [semacquire]:
sync.runtime_SemacquireMutex(0xc00000e0a4, 0xc000e7ad00)
        C:/Program Files/Go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc00000e0a0)
        C:/Program Files/Go/src/sync/mutex.go:134 +0xff
log.(*Logger).Output(0xc00000e0a0, 0x2, 0xc000436540, 0x55, 0x0, 0x0)
        C:/Program Files/Go/src/log/log.go:153 +0x72
log.Printf(0x7d6052, 0x45, 0xc000e7af40, 0x6, 0x6)
        C:/Program Files/Go/src/log/log.go:295 +0x80
main.doHalfOpenScan(0x0, 0x0)
        C:/Users/linqh1/go/src/qtl-scada/cmd/fast-syn-scannner.go:147 +0x63b
main.main.func2(0xc000120000)
        C:/Users/linqh1/go/src/qtl-scada/cmd/fast-syn-scannner.go:71 +0x48
created by main.main
        C:/Users/linqh1/go/src/qtl-scada/cmd/fast-syn-scannner.go:67 +0xf9


goroutine 547729 [syscall]:
syscall.Syscall(0x3, 0x10cc, 0x0, 0x0, 0xc001490d30, 0x4b89ed, 0x7fdd0e2984d0)
        C:/Program Files/Go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Close(0x10cc, 0x7fdd0e2984d8, 0x77)
        C:/Program Files/Go/src/syscall/zsyscall_linux_amd64.go:310 +0x40
internal/poll.(*FD).destroy(0xc0043cdc80, 0x4b8a01, 0x7fdd0e2984d0)
        C:/Program Files/Go/src/internal/poll/fd_unix.go:78 +0x4e
internal/poll.(*FD).decref(0xc0043cdc80, 0x44a101, 0xa92fa0)
        C:/Program Files/Go/src/internal/poll/fd_mutex.go:213 +0x45
internal/poll.(*FD).Close(0xc0043cdc80, 0xc0043cdc80, 0x0)
        C:/Program Files/Go/src/internal/poll/fd_unix.go:100 +0x9b
net.(*netFD).Close(0xc0043cdc80, 0xc00012c300, 0x826938)
        C:/Program Files/Go/src/net/fd_unix.go:184 +0x4f
net.(*conn).Close(0xc0008df2f8, 0x0, 0x0)
        C:/Program Files/Go/src/net/net.go:201 +0x4a
main.doHalfOpenScan(0x0, 0x0)
        C:/Users/linqh1/go/src/qtl-scada/cmd/fast-syn-scannner.go:157 +0x6da
main.main.func2(0xc000120000)
        C:/Users/linqh1/go/src/qtl-scada/cmd/fast-syn-scannner.go:71 +0x48
created by main.main
        C:/Users/linqh1/go/src/qtl-scada/cmd/fast-syn-scannner.go:67 +0xf9
```

And I found that when the number of created thread raise up to hundreds in a short time. Like:

time: 1min threadcreate:15
time: 2min threadcreate:15
...

**Comment by ianlancetaylor** [comment]
Are you saying that there are a lot of goroutines hanging in `syscall.Close`?

Are you using a FUSE file system?

**Comment by bcmills** [comment]
> It shouldn't create so many thread because the number of goroutine is fixed.

You appear to have 5000 tokens in the semaphore guarding the number of goroutines in flight. If each of those goroutines ends up stuck on a blocking system call, that can easily result in a large number of threads.

The combination of file paths starting with `C:/Program Files/` and syscalls in `asm_linux_amd64.s` suggests that you're running this under Microsoft's Windows Subsystem for Linux. Is that correct?

If so, due to the relative newness of that subsystem I'd be inclined to suspect a bug in their implementation of the `close` syscall.

**Comment by linqh1** [comment]
> Are you saying that there are a lot of goroutines hanging in `syscall.Close`?
> 
> Are you using a FUSE file system?

According to the crash log, yes. 

FUSE file system? I don't konw, what can I do to check if I am using FUSE file system?

**Comment by ianlancetaylor** [comment]
If you don't know whether you are using a FUSE file system, then you probably aren't.

You didn't answer @bcmills 's question about Windows.

**Comment by linqh1** [comment]
> > It shouldn't create so many thread because the number of goroutine is fixed.
> 
> You appear to have 5000 tokens in the semaphore guarding the number of goroutines in flight. If each of those goroutines ends up stuck on a blocking system call, that can easily result in a large number of threads.
> 
> The combination of file paths starting with `C:/Program Files/` and syscalls in `asm_linux_amd64.s` suggests that you're running this under Microsoft's Windows Subsystem for Linux. Is that correct?
> 
> If so, due to the relative newness of that subsystem I'd be inclined to suspect a bug in their implementation of the `close` syscall.

Sorry for the late replay. It take me some time to do some company work.

I write and build the code under Windows 10 (`set GOOS=linux`), and run it under Linux. 

Linux version: `cat /proc/version:`

`Linux version 4.13.10-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)) #1 SMP Fri Oct 27 09:07:34 EDT 2017`

According the test in these days, I found a interesting fact that when the tokens number is limited to 2000, the the code can work fine at host S(short for success. running for 2 day+, 47 thread created), while it crash at host F(short for fail) in 20 minutes. 

And when the tokens number is limited to 500, the code can work fine at both host, although the thread number at host F still reached 500+ finally(running for 2 days+). It seems that there are some different between host S and host F.

Maybe lowering goroutine number is a solution? I'd love to provide any information if it's helpful for solving the problem.

**Comment by linqh1** [comment]
There are some data colleced by the pprof visualization tool from the crash host.

It seems that many time is cost at closing ip connection(created by `net.Dial("ip4:tcp", ipstr)`), I'm not sure if it make goroutine stuck.

![image](https://user-images.githubusercontent.com/42435177/58792091-14f52480-8626-11e9-8aa3-1942e4b9c5fc.png)

Does it have some side effect if I do not close the connection since it's not TCP connection?

[pprof.fast-syn-scannner.samples.cpu.002.pb.gz](https://github.com/golang/go/files/3246876/pprof.fast-syn-scannner.samples.cpu.002.pb.gz)

**Comment by agnivade** [comment]
From what I can understand from the code, you are concurrently creating upto 5000 tcp connections to the same host. And since you say there are differences between two hosts where you are running the tests, is it possible that you are hitting the underlying kernel maxconn limits ? Please check your syslog and see if there are lines like `ip_conntrack: table full, dropping packet.` or similar to this.

Also, please check the values of these parameters, and set them to the following and see if it gives you any benefit -

```
net.ipv4.tcp_fin_timeout = 25
net.ipv4.ip_local_port_range = 32768    61000
net.ipv4.tcp_tw_reuse=1 
```

A word of caution: do not just cargo-cult kernel tcp settings. Please read and understand before applying in production :)

**Comment by linqh1** [comment]
> maxconn

There are not any abnormal message in syslog (`dmesg` and `/var/log/messages`).

And these parameters are all same at both hosts.

`net.ipv4.ip_local_port_range = 32768	60999`
`net.ipv4.tcp_fin_timeout = 60`
`net.ipv4.tcp_tw_reuse = 0`

![image](https://user-images.githubusercontent.com/42435177/58859017-7b884a00-86db-11e9-9c23-be0065aa52a9.png)

**Comment by linqh1** [comment]
> > It shouldn't create so many thread because the number of goroutine is fixed.
> 
> You appear to have 5000 tokens in the semaphore guarding the number of goroutines in flight. If each of those goroutines ends up stuck on a blocking system call, that can easily result in a large number of threads.
> 
> The combination of file paths starting with `C:/Program Files/` and syscalls in `asm_linux_amd64.s` suggests that you're running this under Microsoft's Windows Subsystem for Linux. Is that correct?
> 
> If so, due to the relative newness of that subsystem I'd be inclined to suspect a bug in their implementation of the `close` syscall.

As @bcmills  said, so many goroutines stuck on a blocking system call result in a large number of threads. The code work fine when I lower the max number of goroutines, although I still not find the reason why the  same code result in different behavior at different host. Thank you anyway!
