### ISSUE TITLE
proxy.golang.org: clarify privacy policy for proxy.golang.org

### ISSUE THREAD

**Issue by owais** [golang/go#32343]
The beta announcement links to https://proxy.golang.org/privacy as the privacy policy which redirects to https://policies.google.com/privacy. Is this the intentional long term privacy policy or a temporary one until Go proxy gets it's own specific version?

Thanks

**Comment by heschik** [comment]
See [Russ's reply to the alpha announcement](https://groups.google.com/d/msg/golang-dev/go6_lZqew6g/KiNlh7xFDQAJ): 

> That's right - the privacy policy for the servers is currently Google's standard privacy policy, so that URL is a simple redirect. We very much want to provide more specific information in the future. When that happens, proxy.golang.org/privacy will be updated to either redirect to the more specific policy or serve it directly. That's all I can say right now.

I'll leave this open to track the eventual result of that work.

**Comment by katiehockman** [comment]
https://proxy.golang.org/privacy should have updated privacy documentation soon, rather than the redirect (it may take a couple more hours to go live at all of our servers). Hopefully this provides more clarity.
