### ISSUE TITLE
math.Float32frombits don't support interface{}

### ISSUE THREAD

**Issue by henghuang** [golang/go#32346]
Hi, in the following codes, i expect to get 8, but i got 1.1e-44 instead.   I think the problem is caused by the unsafe pointer inside math.Float32frombits function.  I don't know if it's a feature or bug. I really hope we at least can get some warning information when compile following codes.  
```
package main
import (
	"fmt"
	"math"
)

func main() {
	var x interface{}
	x = uint32(8)
	
	fmt.Println(math.Float32frombits(x.(uint32)))
}
```

**Comment by henghuang** [comment]
I just figure it out, the number 8 need to be convert to hexadecimal 0x41000000. kind of weird. Issue closed.

**Comment by ALTree** [comment]
0x41000000 is how 8 is written in IEE754 float32, so that's not that surprising. Float32frombits is a rather low-level function that works directly on the value's bit representation in memory.
