### ISSUE TITLE
proposal: [Go2] Error default handler for tests.

### ISSUE THREAD

**Issue by krhubert** [golang/go#32361]
Hi,

Error handling in tests could be done with `handle err` as shown in [this example](https://github.com/golang/proposal/blob/master/design/go2draft-error-handling.md#stack-frame-preservation). 

But maybe go can use [implicit default handler](https://github.com/golang/proposal/blob/master/design/go2draft-error-handling.md#default-handler) for a test so that every test function will have implicit error handler:

```go
func TestFoo(t *testing.T) {
	handle err { t.Fatal(err) } // implicit handler.
}
```

Motivation is to remove repetition of the same pattern the same as with implicit default handler for functions and methods.

**Comment by ianlancetaylor** [comment]
Thanks for the suggestion.  I added this to the wiki at https://github.com/golang/go/wiki/Go2ErrorHandlingFeedback.
