### ISSUE TITLE
x/tools/go/packages: leading newline in error message

### ISSUE THREAD

**Issue by dominikh** [golang/go#32363]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 linux/amd64
go version devel +2165452a37 Fri May 31 11:26:23 2019 +0000 linux/amd64
</pre>

### What did you do?
https://play.golang.org/p/Ze4miT_P7Dn

### What did you expect to see?
No leading newline in packages.Error.Msg

/cc @matloob

**Comment by dominikh** [comment]
Output of `go list`:

```
$ go list -json sandbox/foo
can't load package: package sandbox/foo: 
../foo/foo.go:1:1: expected 'package', found pckage
```

**Comment by matloob** [comment]
Is this what you're seeing? I don't see a leading newline in the message. I wonder if the issue has been fixed in a different cl?

```$ GO111MODULE=off go run f.go
<nil>
packages.Error{Pos:"", Msg:"cannot find package \"sandbox/foo\" in any of:\n\t/usr/local/go/src/sandbox/foo (from $GOROOT)\n\t/Users/matloob/go/src/sandbox/foo (from $GOPATH)", Kind:0}
```

**Comment by dominikh** [comment]
I am seeing 

```
<nil>
packages.Error{Pos:"", Msg:"\n/home/dominikh/prj/src/sandbox/foo/foo.go:1:1: expected 'package', found pckage", Kind:0}
```

You didn't create the appropriate `sandbox/foo` package and are getting a different error. Not all errors suffer from the leading newline problem.

I should've been clearer in my original report.

**Comment by matloob** [comment]
Oh sorry about that, thanks for pointing that out. I can reproduce. I'll try to get a fix out very soon

**Comment by matloob** [comment]
So this is a problem that originates in go list: 

```
matloob$ GO111MODULE=off go list -e -json -compiled sandbox/foo
{
	"Dir": "/Users/matloob/go/src/sandbox/foo",
	"ImportPath": "sandbox/foo",
	"Root": "/Users/matloob/go",
	"Match": [
		"sandbox/foo"
	],
	"Incomplete": true,
	"Error": {
		"ImportStack": [
			"sandbox/foo"
		],
		"Pos": "",
		"Err": "\n../go/src/sandbox/foo/g.go:1:1: expected 'package', found pckage"
	}
}
```
Now I'm wondering if we should trim all the errors returned by go list...
