### ISSUE TITLE
x/tools/go/packages: provide alternative to deprecated LoadAllSyntax

### ISSUE THREAD

**Issue by dominikh** [golang/go#32365]
A fair number of tools will need the equivalent of the now deprecated LoadAllSyntax constant. Instead of forcing everyone to write their own bitwise OR of 9 constants, it would be nice if we could provide a constant for this. Unfortunately we can't call it `NeedEverything`, as LoadAllSyntax doesn't include NeedExportsFile, and including it unnecessarily probably causes unnecessary work by the compiler.

/cc @matloob

**Comment by matloob** [comment]
I'm actually a bit surprised by this. There are that many tools that need to be able to see (almost) all the fields on the package struct? My instinct is to avoid adding a NeedX field that has more than one bit set if we can avoid doing so

**Comment by dominikh** [comment]
It's possible that the tools I looked at used LoadAllSyntax out of convenience, not necessity. 

However, intuitively, it seems to me that all tools that do full-fledged source based analysis will need the majority of fields in Package. They will need ASTs, they will need to resolve imports, and they will need type information. This amounts to LoadAllSyntax. Tools that need this amount of information include go/analysis runners, pre-go/analysis linters (golint, errcheck, ...) and, to a degree, code manipulation tools like goreturns, though these may not need NeedDeps, but then I'd argue that `LoadAllSyntax ^ NeedDeps` is easier than ORing 8 constants.

Am I missing something? Do most tools actually need much less information than I am thinking?

**Comment by dominikh** [comment]
I don't personally need this anymore, and I haven't seen anyone else ask for it. @matloob should we close this?

**Comment by matloob** [comment]
Yeah closing sounds good.
