### ISSUE TITLE
cmd/link/internal/ld: TestMachoIssue32233 broken on darwin-amd64 builders

### ISSUE THREAD

**Issue by bcmills** [golang/go#32373]
https://build.golang.org/log/b7e0356fc8f515a200229d94f29a72bf9970ce96

<details>

```
--- FAIL: TestMachoIssue32233 (0.65s)
    dwarf_test.go:126: build: # cmd/link/internal/ld/testdata/issue32233/lib
        warning: unknown warning option '-Wunguarded-availability-new'; did you mean '-Wpartial-availability'? [-Wunknown-warning-option]
        go build cmd/link/internal/ld/testdata/issue32233/lib: C compiler warning promoted to error on Go builders
        
    dwarf_test.go:127: build error: exit status 1
FAIL
FAIL	cmd/link/internal/ld	3.216s
```

</details><br>

The test was introduced in [CL 178726](https://golang.org/cl/178726) and has been broken on those builders since.

**Comment by thanm** [comment]
Should be fixed with https://go-review.googlesource.com/c/go/+/179837

**Comment by thanm** [comment]
From the dashboard it looks like there are a couple of other builders that are consistently failing with timeouts  (nocgo, 386). Do we have issues for these?

**Comment by bcmills** [comment]
I believe that the two broken `darwin` builders are #31705.
