### ISSUE TITLE
x/tools/gopls: strange autocompletion behaviour for function arguments

### ISSUE THREAD

**Issue by stamblerre** [golang/go#32375]
Forked from https://github.com/microsoft/vscode-go/issues/2549.

**Comment by muirrn** [comment]
I can't reproduce this. Could you reproduce it @stamblerre?

**Comment by muirrn** [comment]
@fotonmoton can you try upgrading gopls and see if you can still reproduce this? I wasn't able to reproduce.

**Comment by fotonmoton** [comment]
@muirrn yeah, no problem, how can i do it? Just `go get -u golang.org/x/tools/cmd/gopls` will be sufficient? I`m a bit new to go :)

**Comment by fotonmoton** [comment]
@muirrn get the same results. How can I supply a bit more info? and what information is needed? When I was installing vscode-go I install all go dependencies, maybe some packages in conflict with each other?

**Comment by stamblerre** [comment]
To update, run `go get -u golang.org/x/tools/gopls@master`.

@muirrn: I am actually able to reproduce this. Maybe this is something VSCode-specific, but quite clearly in the `TextEdit` there are no parentheses.

**Comment by stamblerre** [comment]
I'm no longer able to reproduce this issue with the more recent improvements to `gopls`. Thanks @muirrn!

Closing this issue now. @fotonmoton: Please open a new issue if something else comes up.
