### ISSUE TITLE
gollvm: cmake step failing with "go-typedesc-equal.c missing" error

### ISSUE THREAD

**Issue by ALTree** [golang/go#32381]
I'm trying to build gollvm, following the instructions here: https://go.googlesource.com/gollvm/#building

The `cmake` step is failing with:

```
CMake Error at tools/gollvm/libgo/CMakeLists.txt:479 (add_library):
  Cannot find source file:

    /home/alberto/workarea/llvm/tools/gollvm/gofrontend/libgo/runtime/go-typedesc-equal.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at tools/gollvm/libgo/CMakeLists.txt:470 (add_library):
  No SOURCES given to target: libgo_c_piclib


CMake Error at tools/gollvm/libgo/CMakeLists.txt:479 (add_library):
  No SOURCES given to target: libgo_c_nonpiclib
```

cc @cherrymui

**Comment by ALTree** [comment]
It appears the file was deleted yesterday from the `gofrontend` repository in [CL 179858](https://go-review.googlesource.com/c/gofrontend/+/179858).

**Comment by cherrymui** [comment]
Thanks. Yes, the file was deleted yesterday and I haven't got a chance to keep gollvm in sync. But here we go: https://go-review.googlesource.com/c/gollvm/+/180017
