### ISSUE TITLE
proxy.golang.org: no matching versions on initial go get

### ISSUE THREAD

**Issue by fhs** [golang/go#32391]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +fa02af4238 Tue May 28 19:23:53 2019 +0000 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/fhs/.cache/go-build"
GOENV="/home/fhs/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/fhs/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/big/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/big/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build354443293=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
go get augie.upspin.io/cmd/upspin-ui
```
### What did you expect to see?

Successful install

### What did you see instead?
Installation fails the first time and then succeeds afterwards:
```
$ go get augie.upspin.io/cmd/upspin-ui
go: finding augie.upspin.io latest
go get augie.upspin.io/cmd/upspin-ui: no matching versions for query "latest"
$ go get augie.upspin.io/cmd/upspin-ui
go: finding augie.upspin.io latest
go: downloading augie.upspin.io v0.0.0-20180817000714-2bfce48dc2ca
go: extracting augie.upspin.io v0.0.0-20180817000714-2bfce48dc2ca
go: finding upspin.io latest
go: finding google.golang.org/api v0.5.0
go: finding golang.org/x/oauth2 latest
go: downloading google.golang.org/api v0.5.0
go: downloading golang.org/x/oauth2 v0.0.0-20190523182746-aaccbc9213b0
go: extracting golang.org/x/oauth2 v0.0.0-20190523182746-aaccbc9213b0
go: extracting google.golang.org/api v0.5.0
go: finding golang.org/x/net latest
go: finding go.opencensus.io v0.21.0
go: finding golang.org/x/tools v0.0.0-20190312170243-e65039ee4138
go: finding golang.org/x/sync v0.0.0-20190227155943-e225da77a7e6
go: finding honnef.co/go/tools v0.0.0-20190102054323-c2f93a96b099
go: finding google.golang.org/genproto v0.0.0-20190307195333-5fe7a883aa19
go: finding golang.org/x/lint v0.0.0-20190301231843-5614ed5bae6f
go: finding golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
go: finding google.golang.org/grpc v1.19.0
go: finding github.com/hashicorp/golang-lru v0.5.0
go: finding golang.org/x/tools v0.0.0-20190226205152-f727befe758c
go: finding golang.org/x/lint v0.0.0-20190227174305-5b3e6a55c961
go: finding golang.org/x/net v0.0.0-20190213061140-3a22650c66bd
go: finding golang.org/x/exp v0.0.0-20190121172915-509febef88a4
go: finding golang.org/x/tools v0.0.0-20190114222345-bf090417da8b
go: finding golang.org/x/lint v0.0.0-20181026193005-c67002cb31c3
go: downloading golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: downloading google.golang.org/grpc v1.19.0
go: downloading cloud.google.com/go v0.34.0
go: downloading go.opencensus.io v0.21.0
go: finding gopkg.in/yaml.v2 v2.2.2
go: downloading gopkg.in/yaml.v2 v2.2.2
go: extracting google.golang.org/grpc v1.19.0
go: extracting gopkg.in/yaml.v2 v2.2.2
go: downloading google.golang.org/genproto v0.0.0-20190307195333-5fe7a883aa19
go: downloading golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: extracting cloud.google.com/go v0.34.0
go: extracting golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: extracting golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: extracting google.golang.org/genproto v0.0.0-20190307195333-5fe7a883aa19
go: extracting go.opencensus.io v0.21.0
go: downloading github.com/hashicorp/golang-lru v0.5.0
go: extracting github.com/hashicorp/golang-lru v0.5.0
$ go get augie.upspin.io/cmd/upspin-ui
go: finding augie.upspin.io latest
go: finding upspin.io latest
go: finding golang.org/x/oauth2 latest
go: finding golang.org/x/net latest
$
```

**Comment by heschik** [comment]
Both `proxy.golang.org` and `upspin.googlesource.com` (the Upspin git repository) are hosted by Google, which is currently having a [large-scale outage](https://www.google.com/appsstatus#hl=en&v=status). I'm not sure whether this particular problem is the mirror or the repo, but it's almost certainly related. Sorry for the trouble; hopefully things will be stabilized soon.

**Comment by hyangah** [comment]
The google service dashboard is green. I verified the above command is working (as of 06/02/2019 7:50pm EDT)

**Comment by fhs** [comment]
Yes, it's working fine. The `go` command should probably give better error than "no matching versions" if something happened while talking to the proxy?
