### ISSUE TITLE
gerrit: status 502 when trying to access go.googlesource.com repos

### ISSUE THREAD

**Issue by creachadair** [golang/go#32395]
<pre>
$ go version

go version go1.12.5 darwin/amd64
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="REDACTED"
GOCACHE="REDACTED"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="REDACTED"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="REDACTED"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m8/8x5f9_qn2gs1zxr6c86jw1940000gn/T/go-build600864526=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
$ go get -u ; go mod tidy ; git diff
```

### What did you expect to see?

Updates of x/sys, x/tools, etc.

### What did you see instead?

```
go get: upgrading golang.org/x/xerrors@v0.0.0-20190513163551-3ee3066db522: git ls-remote -q https://go.googlesource.com/xerrors in REDACTED/pkg/mod/cache/vcs/3dae2e2383f75162530e523fa60c46a0150bec632a2a57ec3fee7fac3fc3648c: exit status 128:
        fatal: unable to access 'https://go.googlesource.com/xerrors/': The requested URL returned error: 502
go get: upgrading golang.org/x/crypto@v0.0.0-20190308221718-c2843e01d9a2: git ls-remote -q https://go.googlesource.com/crypto in REDACTED/pkg/mod/cache/vcs/de5fd3af413a4f3f969455ae522b4002fcb7bb4c158f339396dfc77710c9007d: exit status 128:
        fatal: unable to access 'https://go.googlesource.com/crypto/': The requested URL returned error: 502
go get: upgrading golang.org/x/crypto@v0.0.0-20190513172903-22d7a77e9e5f: git ls-remote -q https://go.googlesource.com/crypto in REDACTED/pkg/mod/cache/vcs/de5fd3af413a4f3f969455ae522b4002fcb7bb4c158f339396dfc77710c9007d: exit status 128:
        fatal: unable to access 'https://go.googlesource.com/crypto/': The requested URL returned error: 502
go get: upgrading golang.org/x/sys@v0.0.0-20190412213103-97732733099d: git ls-remote -q https://go.googlesource.com/sys in REDACTED/pkg/mod/cache/vcs/76a8992ccba6d77c6bcf031ff2b6d821cf232e4ad8d1f2362404fbd0a798d846: exit status 128:
        fatal: unable to access 'https://go.googlesource.com/sys/': The requested URL returned error: 502
go get: upgrading golang.org/x/sys@v0.0.0-20190215142949-d0b11bdaac8a: git ls-remote -q https://go.googlesource.com/sys in REDACTED/pkg/mod/cache/vcs/76a8992ccba6d77c6bcf031ff2b6d821cf232e4ad8d1f2362404fbd0a798d846: exit status 128:
        fatal: unable to access 'https://go.googlesource.com/sys/': The requested URL returned error: 502
go get: upgrading golang.org/x/text@v0.3.0: git ls-remote -q https://go.googlesource.com/text in REDACTED/pkg/mod/cache/vcs/5b03666c2d7b526129bad48c5cea095aad8b83badc1daa202e7b0279e3a5d861: exit status 128:
        fatal: unable to access 'https://go.googlesource.com/text/': The requested URL returned error: 502
go get: upgrading golang.org/x/net@v0.0.0-20190404232315-eb5bcb51f2a3: git ls-remote -q https://go.googlesource.com/net in REDACTED/pkg/mod/cache/vcs/4a22365141bc4eea5d5ac4a1395e653f2669485db75ef119e7bbec8e19b12a21: exit status 128:
        fatal: unable to access 'https://go.googlesource.com/net/': The requested URL returned error: 502
```

This seems to affect all the x/ repositories. I am able to `go get` modules from other repositories normally. This problem also occurs in other modules, so it is not limited to the one I happen to be working on right now.

**Comment by heschik** [comment]
`go.googlesource.com` is hosted by Google, which is having a [large-scale outage](https://www.google.com/appsstatus#hl=en&v=status) right now. Since you're using modules, you might try setting `GOPROXY=https://proxy.golang.org`. `proxy.golang.org` is also hosted by Google, but seems to be tolerating the outage better.

**Comment by heschik** [comment]
FYI for @tparker @draftcode, who have helped us with Gerrit in the past, but I doubt they can do much in this case.

**Comment by creachadair** [comment]
> GOPROXY=https://proxy.golang.org

Confirmed that setting this makes the symptoms go away for me, thanks for the workaround. (And yes, I realize the proxy will eventually _not_ be a workaround 🙂).

**Comment by heschik** [comment]
Outage is over.

**Comment by abhishek246** [comment]
Still facing the same issue 
`Fetching https://golang.org/x/sys/unix?go-get=1`
`Parsing meta tags from https://golang.org/x/sys/unix?go-get=1 (status code 200)`
`get "golang.org/x/sys/unix": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at https://golang.org/x/sys/unix?go-get=1`
`get "golang.org/x/sys/unix": verifying non-authoritative meta tag`
`Fetching https://golang.org/x/sys?go-get=1`
`Parsing meta tags from https://golang.org/x/sys?go-get=1 (status code 200)`
`golang.org/x/sys (download)`
`# cd .; git clone https://go.googlesource.com/sys /go/src/golang.org/x/sys`
`Cloning into '/go/src/golang.org/x/sys'...`
`fatal: unable to access 'https://go.googlesource.com/sys/': The requested URL returned error: 502`
`package golang.org/x/sys/unix: exit status 128`


`https://go.googlesource.com/sys/` is returning 502. 
I have already added `GOPROXY=https://proxy.golang.org` to my env variables still same issue

**Comment by agnivade** [comment]
Duplicate of https://github.com/golang/go/issues/36048. Seems to be a temporary blip.

**Comment by heschik** [comment]
I don't think you would have gotten that error if `GOPROXY` were set correctly. Either way, a months-old bug isn't the place to discuss it; please file a new one if you're having trouble.
