### ISSUE TITLE
encoding/json: SyntaxError's Offset is wrong after decoding some valid json

### ISSUE THREAD

**Issue by itchyny** [golang/go#32399]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/itchyny/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/itchyny/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mg/nqgjy_l53n15b3_dfrjw9_600000gn/T/go-build713456458=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Run the following code (https://play.golang.org/p/gBI1qRBJvPa).
```go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
)

func main() {
	in := strings.NewReader(`false true [ "foo" : "bar" ]`)
	dec := json.NewDecoder(in)
	var vs []interface{}
	for {
		var v interface{}
		if err := dec.Decode(&v); err != nil {
			if err != io.EOF {
				fmt.Printf("%#v\n", err)
				os.Exit(1)
			}
			break
		}
		vs = append(vs, v)
	}
	fmt.Println(vs)
}
```

### What did you expect to see?
Outputs `&json.SyntaxError{msg:"invalid character ':' after array element", Offset:20}`.

### What did you see instead?
Outputs `&json.SyntaxError{msg:"invalid character ':' after array element", Offset:22}`

**Comment by agnivade** [comment]
@mvdan @dsnet

**Comment by mvdan** [comment]
Could you please clarify why you expected the offset to be 20?

**Comment by itchyny** [comment]
I expect because the 20th character of the source string `false true [ "foo" : "bar" ]` is `:`. In addition, I expect the Offset does not exceed the source length (see https://play.golang.org/p/W73hGXHZIxq).
