### ISSUE TITLE
CGOmixed compilation

### ISSUE THREAD

**Issue by hoster110** [golang/go#32396]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.11

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
CGO， When mixed compilation, hundreds of dynamic library dependencies are solved, and one connection at a time is too tedious.

### What did you expect to see?
I'd like to get a simple method or technique for linking dynamic libraries，thank you

**Comment by mdlayher** [comment]
Please see https://github.com/golang/go/wiki/Questions. Closing.
