### ISSUE TITLE
net/http missing server address

### ISSUE THREAD

**Issue by tenox7** [golang/go#32400]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

any

### What did you do?

I need to be able to `http.Redirect()` or otherwise output absolute URL to `net/http` server.

`request.Host` doesn't really do the job and it's often empty.

### What did you expect to see?

I would like to have `request.LocalAddr` similar to `request.RemoteAddr`. This should be per request as each request can come on different address in case of multihomed servers.

### What did you see instead?

 On Apache/CGI this is usually achieved by using `SERVER_ADDR` + `SERVER_PORT` variables.

**Comment by bradfitz** [comment]
You're looking for https://golang.org/pkg/net/http/#LocalAddrContextKey

**Comment by tenox7** [comment]
It worked, thank you!!!
