### ISSUE TITLE
x/tools/gopls: move function signature into detail for completion

### ISSUE THREAD

**Issue by stamblerre** [golang/go#32414]
Forked from VSCode-Go: https://github.com/microsoft/vscode-go/issues/2523.
Please comment if you have any opinions on this.

**Comment by edganiukov** [comment]
I think `label` should contain only method/function/etc name and not full signature. 
Here is feedback from vim-lsp developer - https://github.com/prabirshrestha/vim-lsp/issues/328#issuecomment-492646814

Also, this:
<img width="758" alt="Screenshot 2019-06-03 at 22 24 45" src="https://user-images.githubusercontent.com/1741939/58832142-d8352780-863d-11e9-96ca-3a379fb92dba.png">

**Comment by stamblerre** [comment]
The above image looks like a mistake on the vim-lsp side of things - the text that should get inserted is the `InsertText` field, not the `Label`.

**Comment by edganiukov** [comment]
When I select a completion item, it inserts a correct value (with https://github.com/prabirshrestha/vim-lsp/blob/master/doc/vim-lsp.txt#L163 `g:lsp_text_edit_enabled` enabled). The picture in my previous comment shows situation when I am switching between completion items.

**Comment by edganiukov** [comment]
I've checked cquery, rls and go-langserver - all of these return only a name in `label` and a full signature in `detail`.

**Comment by muirrn** [comment]
FYI emacs also shows the detail next to the label by default, so this change would not be very disruptive.

![Screen Shot 2019-06-05 at 10 33 56 AM](https://user-images.githubusercontent.com/11356572/58976969-8d222e00-877d-11e9-8daa-5cf5c774a6ff.png)

**Comment by danishprakash** [comment]
I'd like to work on this one.

cc @stamblerre
