### ISSUE TITLE
x/tools/cmd/gopls: builtin errors in Problems view in VSCode

### ISSUE THREAD

**Issue by nezorflame** [golang/go#32410]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes (`tools` commit: `2de7f9bf822ce37065c31659ae7187ea9e416dde`)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
...
GOARCH="amd64"
GOOS="darwin"
</pre></details>

### Editor and extension versions

`VSCode`: `1.34.0`
`vscode-go`: `0.10.3-beta.4`

### VSCode settings for `vscode-go` and `gopls`

<details><summary><code>settings.json</code></summary><br><pre>
    ...
    "go.autocompleteUnimportedPackages": true,
    "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
    "go.docsTool": "godoc",
    "go.formatTool": "goimports",
    "go.lintTool": "golangci-lint",
    "go.lintFlags": [
        "--config=/my/config/folder/.golangci.yml"
    ],
    "go.buildOnSave": "off",
    "go.vetOnSave": "off",
    "go.lintOnSave": "package",
    "go.coverageDecorator": {
        "type": "gutter"
    },
    "go.coverageOptions": "showUncoveredCodeOnly",
    "go.coverOnTestPackage": true,
    "go.coverOnSingleTest": false,
    "go.testFlags": [
        "-v",
        "-cover"
    ],
    "go.addTags": {
        "tags": "json",
        "promptForTags": false,
        "transform": "snakecase"
    },
    "go.enableCodeLens": {
        "references": false,
        "runtest": true
    },
    "go.useLanguageServer": true,
    "go.languageServerExperimentalFeatures": {
        "diagnostics": true,
        "documentLink": false,
    },
    "gopls": {
        "usePlaceholders": true,
    },
    "[go]": {
        "editor.defaultFormatter": "ms-vscode.Go",
        "editor.snippetSuggestions": "top",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        },
    },
    "files.eol": "\n",
    ...
</pre></details>

### What did you do?

Just working in any project for some time (usually 5+ minutes is enough).

### What did you expect to see?

Only my project's issues.

### What did you see instead?

After some time I start to get builtin issues in **Problems** view:

<img width="424" alt="image" src="https://user-images.githubusercontent.com/3906766/58813441-79b37d80-862c-11e9-805b-8794af484144.png">

**Comment by stamblerre** [comment]
This should be fixed with https://golang.org/cl/179921.

**Comment by nezorflame** [comment]
Seems to be fixed. Thanks!
