### ISSUE TITLE
doc: Contributing Guidelines site does not have anchor links on some headers

### ISSUE THREAD

**Issue by phamt2** [golang/go#32415]
In the contributing guidelines there is an inconsistency in which a paragraph symbol appears on certain titles while on others it does not. I think it would be better to not have the unnecessary paragraph symbol appear as a clickable as it does nothing that the links at the top already does.

**Comment by cespare** [comment]
It does have a purpose: if you're reading the document and you want to link to the section you're reading, the paragraph symbol makes it clear that you can copy the link from the section header directly rather than scrolling to the top of the document to get the section link.

**Comment by phamt2** [comment]
Oh okay that makes sense. With that being said then there is a inconsistency issue with the paragraph symbols. There are a few titles that are missing paragraph symbols while most of the others do contain the paragraph symbols. I initially thought it was because of how it was spread out but even the smallest sections had paragraph symbols so I am thinking it could be a mistake?

**Comment by agnivade** [comment]
You are right. Some `<h3>` headers are missing `id`s, due to which the anchor links don't appear. Will send a CL.
