### ISSUE TITLE
go/build: Recognize `.sx` as equivalent to `.S`

### ISSUE THREAD

**Issue by bdarnell** [golang/go#32434]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/bdarnell/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/bdarnell/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qx/.../tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I tried to rename [an assembly file](https://github.com/cockroachdb/cockroach/blob/9521979debfb805cc1f22b3277711b4bec4262d4/pkg/storage/engine/slice.s#L36) from lowercase `.s` to capital `.S` ([PR](https://github.com/cockroachdb/cockroach/pull/38021)) in order to use preprocessor directives in it. 

### What did you expect to see?

Renaming the file from lowercase `.s` to capital `.S` should cause the preprocessor directives to work.

### What did you see instead?

Some combination of git and the macos filesystem (case-insensitive but case preserving) made the rename difficult. I had to change the base name of the file to make sure the rename "stuck". 

This worked, but it would have been simpler if go recognized the suffix `.sx` for assembly files that use the preprocessor. This suffix is [supported by gcc](http://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html).

**Comment by ianlancetaylor** [comment]
Seems reasonable to me.

**Comment by darkLord19** [comment]
Hi, I am working with Go from past few months and I was thinking about contributing to Go. So if no one is working then I would like to work on this.

**Comment by darkLord19** [comment]
After some code reading, I figured that I will need to update src/cmd/go/internal/work/exec.go and src/cmd/go/internal/work/gc.go mainly and some other places in internal/load accordingly. Can anyone explain how the go build works in an abstract way so that I can understand the working of current build toolchains and then add changes necessary for the issues? Thanks.
@ianlancetaylor

**Comment by agnivade** [comment]
For general questions like these please reach out to the forums here on the [Questions](https://github.com/golang/go/wiki/Questions) wiki page.

**Comment by ianlancetaylor** [comment]
I understand that you are asking an abstract question, but it's a bit too abstract for me to know what the answer is.  `go build` works by finding all the files in a package and building them.

My first guess, without looking at the code, would be that this could be done entirely in the go/build package by handling ".sx" files like ".S" files.
