### ISSUE TITLE
Casting of interface obtained through the reflection does not work for values, but works for references

### ISSUE THREAD

**Issue by dealancer** [golang/go#32432]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/vadymmyrgorod/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/vadymmyrgorod/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/vadymmyrgorod/Projects/validate/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4m/9gjlbd2j5l1915n953t6bq440000gn/T/go-build641966181=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I am trying to cast an interface obtained through the reflection, but it does not work for values. Though it works for pointers. Am I doing something wrong?

```go
package main

import (
	"fmt"
	"reflect"
)

type Printer interface {
	Increment()
	Print()
}

type I int

func (i *I) Increment() {
	*i++
}
func (i I) Print() {
	fmt.Println(i)
}

func IncrementPrint(i interface{}) {
	value := reflect.ValueOf(i)

	if value.CanInterface() {
		// Next line does not work when i is a value, but works when i is a reference
		if printer, ok := value.Interface().(Printer); ok {
			printer.Increment()
			printer.Print()
		} else {
			fmt.Println("Could not convert!")
		}
	} else {
		fmt.Println("Could not interface!")
	}
}

func main() {
	var i I

	i.Print()          // Prints "0"
	i.Increment()      // Increments
	i.Print()          // Prints "1"
	(&i).Increment()   // Increments
	(&i).Print()       // Prints "2"
	IncrementPrint(i)  // Prints "Could not convert!"
	IncrementPrint(&i) // Prints "3"

}
```

### What did you expect to see?

I expect `value.Interface().(Printer)` to work and `IncrementPrint(i)` to print "3".

### What did you see instead?

`value.Interface().(Printer)` is not working and "Could not convert!" is printed.

**Comment by randall77** [comment]
This is intended.
```
IncrementPrint(i)
```
`i` is passed by value here. There is no way that the implementation of IncrementPrint could modify the variable `i` declared in `main`.

In the other calls you listed, there's an explicit `&` or an implicit one (the `i.Increment()` call).

**Comment by dealancer** [comment]
@randall77, thank you for the help! You are right,

Here is the error that is being generated, when I remove `ok` check.

```
panic: interface conversion: main.I is not main.Printer: missing method Increment
```

I think this is quite confusing feature of language. Because interface implementation influences the behavior. Interface definition should influence the behavior, but not implementation. Unfortunately there is no way to describe receiver type (value, or reference) in the interface itself!

**Comment by randall77** [comment]
> Unfortunately there is no way to describe receiver type (value, or reference) in the interface itself!

True.
I'm not really sure why you want that.
You declared one interface, `Printer`. You essentially declared 2 types, `I` and `*I`. The former only has one method, `Print`. The latter has 2 methods, `Print` and `Increment` (`Print` is there because pointer types acquire the methods on the corresponding value).
Anything that implements `Printer` can be assigned to one. So you can do:
```
var p Printer = new(I)
```
but you can't do
```
var p Printer = I(0)
```
because `I` does not implement `Incrementer`, only `*I` does.

So you don't need to declare whether an interface requires a pointer receiver.  The type system will only allow types that implement `Increment` to be assigned to `Printer`. And it's on your clients to understand that this doesn't work:
```
func (i I) Increment() {
	i++
}
```
But this would be ok to assign to `Printer`, despite not using a pointer receiver:
```
type J struct {
    p *int
}
func (j J) Increment() {
    *j.p++
}
func (j J) Print() {
    fmt.Println(*j.p)
}
```

I admit it's a bit more opaque when going through `reflect`, but in regular code this all falls out naturally.

**Comment by dealancer** [comment]
@randall77, is there a correct way to covert an interface to a specific interface?

Following does not work:

```
	var j interface{} = i
	j.(Printer).Increment()      // Panic
	j.(Printer).Print()          // Panic
```

Following does not work as well:

```
	var j interface{} = i
	Printer(j).Increment()      // Build error
	Printer(j).Print()          // Build error
```

**Comment by randall77** [comment]
I think you should probably move this question to a different forum. See https://github.com/golang/go/wiki/Questions

**Comment by dealancer** [comment]
@randall77, ok thank you, leaving a new thread link just for the reference: https://forum.golangbridge.org/t/how-to-cast-interface-to-a-given-interface/13997.
