### ISSUE TITLE
cmd/compile: bce: if slice[n] is in bounds, then slice[:n+1] should have bounds check eliminated

### ISSUE THREAD

**Issue by ugorji** [golang/go#32431]
I expect that if we can access the nth element of a slice, then we can slice up to n+1.

See below.
```go
		var blen int
		var b []byte
		// ... do some computation
		b[blen-1] = '"' // bounds check: Found IsInBounds (expected)
		use(b[:blen]) // bounds check: Found IsSliceInBounds (unexpected as above is sufficient)
```

Consequently, I do not expect a bounds check for b[:blen]. 

However, I get a bounds check for both b[blen-1] and b[:blen].

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +1531192272 Mon May 27 17:58:39 2019 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bt/526m392x16x8y149jwx28mkm0000gp/T/go-build760118559=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by randall77** [comment]
Sure.
@zdjones @rasky @brtzsnr

**Comment by randall77** [comment]
Need to watch out for blen==MinInt. Then the index succeeds but the slice fails.

**Comment by dpinela** [comment]
@randall77 While not immediately useful, I think it's worth noting that this would no longer be a concern if we adopted #19623 or #31500.

**Comment by martisch** [comment]
I think the titles suggestion is not save for when n==MaxInt as n+1 would overflow.

**Comment by go101** [comment]
It looks Go 1.12 does BCE for this case.

Some finding:
```golang
package main

type T = uint64

func f(s []int, n T) {
	_ = s[n]
	_ = s[:n+1] // BCEed when T is int/uint/int64/uint64 for Go SDK 1.12, but not for tip.
	// I think T=unsignedIntergerType should be ok here.
}

func g(s []int, n T) {
	_ = s[n-1]
	_ = s[:n] // BCEed when T is int/uint/int64/uint64 for Go SDK 1.12, but not for tip.
	// I think T=unsignedIntergerType should be ok here.
}

func main() {
```

**Comment by zdjones** [comment]
@ugorji It seems the bounds check in your example is removed, at least as of 1.12.6. Do you have an example where the bounds check is not removed?

Otherwise this can be closed, fixed somewhere <= 1.12.6

**Comment by rasky** [comment]
@zdjones did you check the behaviour is correct when n==MaxIntT?

**Comment by go101** [comment]
It is impossible for a program to successfully allocate a slice with lengh n == MaxIntT for T is int/uint/int64/uint64, even if the element type is byte. For other signed interger types, if n==MaxIntT, then n+1 is negative, so the bound check can't be removed for sure. For unsigned integer types, n+1 is zero, so the bound check can be removed for sure.

In short, bound check can be removed for int, int64 and any unsigned integer types.

**Comment by zdjones** [comment]
This still needs more thought, don't close it yet. 

I've started checking the current behaviour near MaxInt and ended up down quite the rabbit-hole (exploring how big of a slice the compiler and runtime will allow, compared with what the spec allows for)

**Comment by randall77** [comment]
Note that you can make slices of 0-sized items. That will let you test near maxint without using huge amounts of memory.
```
package main

type T struct{}

func main() {
	s := make([]T, 1<<63-1)
	println(len(s))
}

```

**Comment by go101** [comment]
With @randall77's comment, the conclusion in my last comment is wrong (for int and int64).

**Comment by go101** [comment]
It looks the slice expression in the following code has already BCEed at least since Go 1.12.
```Go
		_ = b[blen-1] // bounds check: Found IsInBounds (expected)
		use(b[:blen]) // BCEed
```

So maybe it also should for OP's code:
```Go
		b[blen-1] = '"' // bounds check: Found IsInBounds (expected)
		use(b[:blen]) // bounds check: Found IsSliceInBounds (unexpected as above is sufficient)
```

Rethought it for a while, even if `blen` is MinInt, the bound check for the slice expression could be also eliminated, for `blen-1` is MaxInt, so the expression `b[blen-1]` will always cause a panic. If it doesn't panic, then the slice expression is absolutely safe.

**Comment by go101** [comment]
And it looks this problem only happens for package-level slices:
```Go
package main

var blen int = 1
var b []byte = make([]byte, 1)
var b2 []byte

func fff(b []byte, blen int) {
	type _ int
	b[blen-1] = '"' //  Found IsInBounds
	b2 = b[:blen]
}

func ggg() {
	type _ int
	b[blen-1] = '"' // Found IsInBounds
	b2 = b[:blen] //  Found IsSliceInBounds
}

func main() {
	b[blen-1] = '"' // Found IsInBounds
	b2 = b[:blen] // Found IsSliceInBounds
	
	ggg()
	
	fff(b, blen)
}
```

**Comment by randall77** [comment]
@go101, the compiler assumes global variables can be reassigned at any time. The two reads of `b` might be completely different slices.

**Comment by go101** [comment]
@randall77, then it looks this issue could be closed now, as this problem doesn't happen to local slices.

BTW, more evidences to prove global variables are not BCE friendly.
```Go
package main

var blen int = 1
var b []byte = make([]byte, 1)
var b2 []byte
var x byte

func ggg1() {
	_ = b[blen-1] // Found IsInBounds
	b2 = b[:blen]
}

func ggg2() {
	_ = b[blen-1] // Found IsInBounds
	b2 = b[:blen]
	b[blen-1] = '"' // Found IsInBounds
}

func ggg3() {
	_ = b[blen-1] // Found IsInBounds
	b[blen-1] = '"'
	b2 = b[:blen] //  Found IsSliceInBounds
}

func ggg1b() {
	x = b[blen-1] // Found IsInBounds
	b2 = b[:blen] // Found IsSliceInBounds
}

func ggg2b() {
	x = b[blen-1]   // Found IsInBounds
	b2 = b[:blen]   // Found IsSliceInBounds
	b[blen-1] = '"' // Found IsInBounds
}

func ggg3b() {
	x = b[blen-1]   // Found IsInBounds
	b[blen-1] = '"' // Found IsInBounds
	b2 = b[:blen]   //  Found IsSliceInBounds
}

func main() {
	ggg1()
	ggg2()
	ggg3()
}
```

**Comment by go101** [comment]
It looks there is still a little unreasonable in BCE decision making:
```Go
package main

var s = make([]int, 100)

func f() (r int) {
	for i := range s {
		r += s[i] // bound check eliminated
	}
	return r
}

func g() {
	for i := range s {
		s[i] = i // need bound check
	}
}

func main() {
}
```

I filed another issue: https://github.com/golang/go/issues/47736
