### ISSUE TITLE
go build Success but go vet direct assignment to atomic value

### ISSUE THREAD

**Issue by Liberxue** [golang/go#32445]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.12 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/Users/liberxue/golang/bin"
GOCACHE="/Users/liberxue/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/liberxue/golang"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1f/1b5_xh8x2sq5q_lfs0p86x640000gn/T/go-build329714378=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

<pre>
~/golang/src/demo013 » go run main.go                                                                                                liberxue@liberxue
&{{0 0} {1559727225781453000 0}}
------------------------------------------------------------
~/golang/src/demo013 » go vet -composites=false main.go                                                                              liberxue@liberxue
# command-line-arguments
./main.go:23:2: direct assignment to atomic value
------------------------------------------------------------
~/golang/src/demo013 »                                                                                                               liberxue@liberxue
</pre>

### What did you expect to see?

<pre>

package main

import (
	"fmt"
	"sync/atomic"
	"time"
)
type UMQVersion struct {
	Timestamp int64 `json:"timestamp"`
	Counter   int64 `json:"counter"`
}
type GetAllSubscriptionGroupResponse struct {
	SubscriptionGroupTable interface{} `json:"subscriptionGroupTable"`
	DataVersion            UMQVersion `json:"dataVersion"`
}
func NewUMQVersion(timestamp ...int64) *UMQVersion {
	dataVersion := new(UMQVersion)
	dataVersion.Timestamp = time.Now().UnixNano()
	if timestamp != nil && len(timestamp) > 0 {
		dataVersion.Timestamp = timestamp[0]
	}
	dataVersion.Counter = atomic.AddInt64(&dataVersion.Counter, 0)
	return dataVersion
}
func main() {
	wrapper := new(GetAllSubscriptionGroupResponse)
	wrapper.SubscriptionGroupTable = wrapper.DataVersion
	wrapper.DataVersion = *NewUMQVersion()
	fmt.Println(wrapper)
}
</pre>

**Comment by ALTree** [comment]
The vet tool is (correctly) giving you a warning. What you want is this:

```
atomic.AddInt64(&dataVersion.Counter, 1)
```

which will already update the dataVersion.Counter as needed (that's why it's passed by pointer). You don't have to assign the return value back to `dataVersion.Counter`. 

Closing here, since this is not a Go bug.

**Comment by Liberxue** [comment]
why build  or run Not error

**Comment by ianlancetaylor** [comment]
Because `go vet` looks for different kinds of errors in your program than `go build` does.

https://golang.org/cmd/go/#hdr-Report_likely_mistakes_in_packages
