### ISSUE TITLE
x/tools/cmd/gopls: import organization fails in test package

### ISSUE THREAD

**Issue by stamblerre** [golang/go#32440]
Forked from VSCode-Go and Slack discussions: https://github.com/microsoft/vscode-go/issues/2521.

**Comment by ramya-rao-a** [comment]
@stamblerre, @Steelphase can either of you add a summary of the slack discussion here?

**Comment by heschik** [comment]
Looks like a bug in golang.org/cl/170238: it checks only the directories in play, ignoring the package names. That won't work in the case of an external test that wants to import the package under test. It also won't work in Bazel, where multiple unrelated packages can be in the same directory.

Possible fix would be to check the candidate's import path vs. the file's import path around [hereish](https://github.com/golang/tools/blob/8aaa1484dc108aa23dcf2d4a09371c0c9e280f6b/internal/imports/fix.go#L204) but I need to think about it more.
