### ISSUE TITLE
x/tools/gopls: cache diagnostics, don't re-send if unchanged

### ISSUE THREAD

**Issue by myitcv** [golang/go#32443]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +ef84fa082c Mon Jun 10 23:23:39 2019 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20190611222205-d73e1c7e250b
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/myitcv/gostuff/src/github.com/myitcv/govim/cmd/govim/.bin"
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPROXY="https://proxy.golang.org/"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build939912546=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://github.com/myitcv/govim/blob/multiple_gopls_diagnostics/cmd/govim/testdata/diagnostics.txt defines a test that looks to assert the number of diagnostic callbacks for various files.

The setup is very simple (see the txtar at the end of the script)

The sequence is then:

* Open `main1.go`
* Add blank line above line 1
* Set line 1 to be the comment `// Hello`
* Save file

### What did you expect to see?

As the last two lines of the testscript assert, this should result in:

* 3 x diagnostics for `main1.go`: initial load + first change + second change
* 1 x diagnostic for `main2.go`: initial load (after which no changes are made to `main2.go` or any related file that cause the diagnostics for `main2.go` to change)

### What did you see instead?

* 3 x diagnostics for `main1.go`: initial load + first change + second change
* 3 x diagnostics for `main2.go`: initial load + first change to `main1.go` + second change to `main1.go`

Therefore, two superfluous diagnostic notifications for `main2.go` (because the diagnostics for `main2.go`  have not changed, i.e. they remain zero.

Arguably, there should be no notifications for `main1.go` either because the diagnostics for that file have not changed either, but there may be some requirement on diagnostics being sent for files that have been changed?

---

cc @stamblerre @ianthehat

---

_Edit: update to reflect the fact this problem persists with `golang.org/x/tools v0.0.0-20190611222205-d73e1c7e250b`_

**Comment by myitcv** [comment]
There is actually a more serious bug here beyond the superfluous diagnostics; we aren't actually receiving diagnostics for files where it matters, at least not reliably. 

In the scenario described in https://github.com/myitcv/govim/issues/280, we are only getting diagnostic updates for a subset of the 100 files. For example, for a given edit to `foo1.go`, I only received 38 `PublishDiagnostics` notifications.

Critically, we sometimes fail to get diagnostic updates for the one file we are editing. 

This gives the impression that, from the user's perspective, things have stalled. i.e. Vim's quickfix window shows an error from a number of edits ago (the intervening published diagnostics have not been received by `govim`).

**Comment by myitcv** [comment]
Just noting a Slack conversation here, where there was some suggestion that this issue might be related to the "no room in queue" errors that others have been seeing. FWIW, `govim` uses [internal JSON RPC and LSP client implementations](https://github.com/golang/tools/tree/eacb66d2a7c3d6b93b39f7224e6bef6a44cbe70e/internal).

**Comment by myitcv** [comment]
Updated my two previous comments to reflect the fact that diagnostic results from `gopls` were being dropped because, per https://github.com/golang/go/issues/32467#issuecomment-499607554, the default for the JSON RPC client is to do just that:

> This seems to happen because the defaultMessageBufferSize is set to 20 and RejectIfOverloaded is set to true for both client and server conns in jsonrpc2.
> 
> https://github.com/golang/tools/blob/master/internal/lsp/protocol/protocol.go#L14
> https://github.com/golang/tools/blob/master/internal/jsonrpc2/jsonrpc2.go#L28
> 
> I think increasing the default to a more-reasonable 128, or just disabling RejectIfOverloaded should fix this issue.

Hence https://github.com/myitcv/govim/pull/295/commits/e9bdd971737bf61f304992c04e92703c92a0997e fixed this for `govim`.

So this issue is now just about the superfluous diagnostics being sent from `gopls` to the client, per the original description.

**Comment by icexin** [comment]
There is a similar problem in emacs. If there are too many files in a package, when editing one of the files, each time you add a character, you will get the diagnostics of all the files under the package, causing the emacs to be very stuck and almost impossible to edit.

**Comment by stamblerre** [comment]
This is likely one of the causes of https://github.com/golang/go/issues/33531.
