### ISSUE TITLE
cmd/go: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by minaevmike** [golang/go#32451]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

Compilation fails with `invalid memory address or nil pointer dereference`

https://play.golang.org/p/h0KwbQYlCKk

**Comment by mark-rushakoff** [comment]
Looks fixed on tip.

```
$ gotip version
go version devel +5f509148b1 Wed Jun 5 00:53:25 2019 +0000 darwin/amd64

$ gotip build ./x.go
# command-line-arguments
./x.go:9:7: invalid recursive type [10]elem
```

**Comment by minaevmike** [comment]
Ok, so i'll close it
