### ISSUE TITLE
proxy.golang.org: unexpected status 410 Gone

### ISSUE THREAD

**Issue by kindermoumoute** [golang/go#32461]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Use go index:

```
export GOPROXY=https://proxy.golang.org
go mod download
```

### What did you expect to see?

Should download modules.

### What did you see instead?

```
go: github.com/tsenart/vegeta@v12.1.1-0.20190104112155-65db074680f5+incompatible: unexpected status (https://proxy.golang.org/github.com/tsenart/vegeta/@v/v12.1.1-0.20190104112155-65db074680f5+incompatible.info): 410 Gone
```

**Comment by heschik** [comment]
Where did that pseudoversion come from? 65db074680f5 in that repository is tagged as v12.2.0, so it's questionable to use a pseudoversion to refer to it. I'm not sure offhand why the mirror is rejecting the request though.

**Comment by kindermoumoute** [comment]
In case this can help:
```bash
$ cat go.mod | grep vegeta
	github.com/tsenart/vegeta v12.1.1-0.20190104112155-65db074680f5+incompatible
$ cat go.sum | grep vegeta
github.com/tsenart/vegeta v12.1.1-0.20190104112155-65db074680f5+incompatible h1:BOkXQRcpd/1H9QU5eLMWY6Swb+2oA6KldbQWdKT9zHY=
github.com/tsenart/vegeta v12.1.1-0.20190104112155-65db074680f5+incompatible/go.mod h1:Smz/ZWfhKRcyDDChZkG3CyTHdj87lHzio/HOCkbndXM=
```

**Comment by bcmills** [comment]
> Where did that pseudoversion come from? 65db074680f5 in that repository is tagged as v12.2.0

That pseudo-version would be an appropriate name for the commit if the tag was not added until some later point. (This is one of the cases described in https://github.com/golang/go/issues/27173#issuecomment-494954298, in which we need to accept a pseudo-version below what is implied by the current tags.)

**Comment by dmitshur** [comment]
For (my) reference, a good thing to try in the future for issues similar to this one is to run the same command with `export GOPROXY=direct` and see if the error happens as well. In that case, the problem is in `cmd/go` rather than the mirror.

In this case, it seems the problem only happens with GOPROXY set to mirror and not direct:

```
$ export GOPATH=$(mktemp -d)
$ export GOPROXY=https://proxy.golang.org
$ go mod download -json github.com/tsenart/vegeta@v12.1.1-0.20190104112155-65db074680f5+incompatible
go: finding github.com/tsenart/vegeta v12.1.1-0.20190104112155-65db074680f5+incompatible
{
	"Path": "github.com/tsenart/vegeta",
	"Version": "v12.1.1-0.20190104112155-65db074680f5+incompatible",
	"Error": "unexpected status (https://proxy.golang.org/github.com/tsenart/vegeta/@v/v12.1.1-0.20190104112155-65db074680f5+incompatible.info): 410 Gone"
}
$ echo $?
1

$ export GOPROXY=direct
$ go mod download -json github.com/tsenart/vegeta@v12.1.1-0.20190104112155-65db074680f5+incompatible
go: finding github.com/tsenart/vegeta v12.1.1-0.20190104112155-65db074680f5+incompatible
{
	"Path": "github.com/tsenart/vegeta",
	"Version": "v12.1.1-0.20190104112155-65db074680f5+incompatible",
	"Info": "/var/folders/3m/rg2zm24d1jg40wb48wr0hdjw00jwcj/T/tmp.xbI3lVwp/pkg/mod/cache/download/github.com/tsenart/vegeta/@v/v12.1.1-0.20190104112155-65db074680f5+incompatible.info",
	"GoMod": "/var/folders/3m/rg2zm24d1jg40wb48wr0hdjw00jwcj/T/tmp.xbI3lVwp/pkg/mod/cache/download/github.com/tsenart/vegeta/@v/v12.1.1-0.20190104112155-65db074680f5+incompatible.mod",
	"Zip": "/var/folders/3m/rg2zm24d1jg40wb48wr0hdjw00jwcj/T/tmp.xbI3lVwp/pkg/mod/cache/download/github.com/tsenart/vegeta/@v/v12.1.1-0.20190104112155-65db074680f5+incompatible.zip",
	"Dir": "/var/folders/3m/rg2zm24d1jg40wb48wr0hdjw00jwcj/T/tmp.xbI3lVwp/pkg/mod/github.com/tsenart/vegeta@v12.1.1-0.20190104112155-65db074680f5+incompatible",
	"Sum": "h1:BOkXQRcpd/1H9QU5eLMWY6Swb+2oA6KldbQWdKT9zHY=",
	"GoModSum": "h1:Smz/ZWfhKRcyDDChZkG3CyTHdj87lHzio/HOCkbndXM="
}
$ echo $?
0
```

**Comment by heschik** [comment]
We've released a change that improves this behavior; the query that previously returned an error will now return `v12.2.0+incompatible`, since that's the more canonical way to reference that commit. If that causes you any trouble please let us know.
