### ISSUE TITLE
website: please remove google analytics from golang.org

### ISSUE THREAD

**Issue by catastrop** [golang/go#32469]

**Comment by ALTree** [comment]
Why?

**Comment by catastrop** [comment]
This is a free and open source  software. And Don't  want to be tracked by Google, even though Go is developed at Google

**Comment by ianlancetaylor** [comment]
Personally I think it would be very misleading to suggest that if we stopped using Google Analytics we would be unable to track people using the website.  I don't see any particular problem in being upfront about it.  Anybody can run their own copy of golang.org, there is no special need to contact the official version.

**Comment by singhpradeep** [comment]
Looking issues created by OP, I think he is trolling.

I apologize to be that guy but you have created many frivolous issues like 

"release Windows 10 under free license"
"Why no mention of GNU"
"Why google analytics"
"Why in C and not in go/rust".

I think this ticket can be closed. There are more important things to do than responding to troll tickets.

Like Ian mentioned, you are free to create your own copy of golang.org and ask people to use it.
