### ISSUE TITLE
go assembly file call c library func ,how build?

### ISSUE THREAD

**Issue by awzhgw** [golang/go#32460]
### What version of Go are you using (`go version`)?
go version go1.12.5 linux/amd64
### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build448552426=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Since cgo is particularly slow, I plan to use go's assembly language, first convert the .c file to a C language assembly, then use c2goasm to convert to the go language assembly language, because my .c file calls other libraries. The library is the standard library for the system. So how do I compile at this time? Go build support link other dynamic libraries instead of cgo?

**Comment by beoran** [comment]
I would probably use //go:generate instructions to automate this without the need for external tools: 
 https://blog.golang.org/generate Otherwise, many people also use a makefile.

**Comment by ianlancetaylor** [comment]
Your plan is not safe.  There is a reason that cgo does the things that it does; it's not actively trying to be slow.

I'm going to close this issue because there is nothing to fix.  I'm not really sure what you are asking.  I recommend that you discuss this on a forum; see https://golang.org/wiki/Questions.
