### ISSUE TITLE
float64 numbers don't add up appropriately

### ISSUE THREAD

**Issue by PraGitHub** [golang/go#32472]
### What version of Go are you using (`go version go1.11.1 windows/amd64`)?

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?

I don't know.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\prashanh\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\MyLearnings\Prapository\GoLang\Web\mail;E:\MyLearnings\Prapository\GoLang\Web\articles-site;E:\RouterJobStatus\RouterJobStatus;E:\MyLearnings\Prapository\GoLang\Sorting;E:\MyLearnings\Prapository\GoLang\DynamicProgramming\FibSeries;E:\MyLearnings\Prapository\GoLang\ComplexNumbers;E:\MyLearnings\Prapository\GoLang\FindTheFaulty;E:\MyLearnings\Go\Wrappers\CTrial;
set GOPROXY=
set GORACE=
set GOROOT=E:\Go
set GOTMPDIR=
set GOTOOLDIR=E:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\prashanh\AppData\Local\Temp\go-build261146570=/tmp/go-build -gno-record-gcc-switches</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I am trying to add up all the probabilities and checking if sum of probabilities is 1.
While I am adding, i encountered a problem, which is this => adding 0.05 to 0.65 resulting in   0.7000000000000001. Check the sample output below,

2019/06/07 07:59:04 R Rumrah  :: value =  0.2  sum =  0.2
2019/06/07 07:59:04 R Rumrah  :: value =  0.3  sum =  0.5
2019/06/07 07:59:04 R Rumrah  :: value =  0.15  sum =  0.65
2019/06/07 07:59:04 R Rumrah  :: value =  0.05  sum =  0.7000000000000001
2019/06/07 07:59:04 R Rumrah  :: value =  0.05  sum =  0.7500000000000001
2019/06/07 07:59:04 R Rumrah  :: value =  0.01  sum =  0.7600000000000001
2019/06/07 07:59:04 R Rumrah  :: value =  0.04  sum =  0.8000000000000002
2019/06/07 07:59:04 R Rumrah  :: value =  0.2  sum =  1.0000000000000002

playground link - https://play.golang.org/p/dlo8xrHD8Fh

source code link - https://github.com/PraGitHub/Prapository/blob/master/Misc/GeekTrust/Problem4/main.go

### What did you expect to see?

Explained above.

### What did you see instead?

Explained above.

**Comment by PraGitHub** [comment]
Playground link - https://play.golang.org/p/dlo8xrHD8Fh
Complete source code link - https://github.com/PraGitHub/Prapository/blob/master/Misc/GeekTrust/Problem4/main.go

**Comment by martisch** [comment]
float64 and float32 only have finite precision. Not every number can be represented exactly. This is the same for other programming languages.

See https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html for more info.
