### ISSUE TITLE
x/playground compile error outputs #play 

### ISSUE THREAD

**Issue by Xavierh93** [golang/go#32489]
### What version of Go are you using (`go version`)?

go1.12.5

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

go playground on macOS

### What did you do?

I ran a program with a few files I noticed that compile errors are prepended with # play

### What did you expect to see?

I just expected to see a compile error without the # play before the output.

### What did you see instead?

# play before the first line of error output

**Comment by agnivade** [comment]
Duplicate of https://github.com/golang/go/issues/32237. Please comment if it's not.
