### ISSUE TITLE
x/tools/cmd/gopls: no packages found

### ISSUE THREAD

**Issue by raxod502** [golang/go#32487]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

I'm using 1.12.5 which is the latest release according to [this page](https://golang.org/doc/devel/release.html#go1.12.minor). I just ran `go get -u golang.org/x/tools/cmd/gopls` so presumably `gopls` is up to date.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/raxod502/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/raxod502/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/raxod502/code/goval/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f6/sdzsx0rn71g8_5xxqg3bm9fw0000gn/T/go-build670253121=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Put in file `main.go` in an otherwise empty directory:

```go
package main

import "fmt"

func main() {
	fmt.Println("Hello World")
}
```

Then run:

```
% gopls check main.go
```

### What did you expect to see?

Some diagnostics, maybe. Not an error. (I don't actually use this command specifically; I narrowed down the error from an LSP failure in Emacs.)

### What did you see instead?

```
2019/06/07 14:24:10 Error:unable to check package for file:///Users/raxod502/temp/go-test/main.go: no packages found for /Users/raxod502/temp/go-test/main.go
2019/06/07 14:24:10 Error:unable to check package for file:///Users/raxod502/temp/go-test/main.go: no packages found for /Users/raxod502/temp/go-test/main.go
2019/06/07 14:24:10 Error:failed to deliver diagnostic for file:///Users/raxod502/temp/go-test/no%20packages%20found%20for%20/Users/raxod502/temp/go-test/main.go: stat /Users/raxod502/temp/go-test/no packages found for /Users/raxod502/temp/go-test/main.go: no such file or directory
```

**Comment by muirrn** [comment]
In module mode you need a go.mod file for gopls to load the package properly. I think there are plans to improve the messaging to make this more clear.

**Comment by wubo0067** [comment]
I had the same problem.

**Comment by stamblerre** [comment]
This issue is now fixed on master, as of https://github.com/golang/tools/commit/1d40570c5c726e05e8ab95c7fb86a26cd5fa0f8b.
