### ISSUE TITLE
x/playground: inconsistent GOOS when go-vet-ing and executing

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#32481]
### What version of Go are you using (`go version`)?

n/a

### Does this issue reproduce with the latest release?

n/a

### What operating system and processor architecture are you using (`go env`)?

n/a

### What did you do?

Run
https://play.golang.org/p/kk3GHSV1tqM

### What did you expect to see?

```
./foo_nacl.go:5:2: unreachable code
Go vet exited.

GOOS: nacl
```

or

```
./foo_linux.go:5:2: unreachable code
Go vet exited.

GOOS: linux
```

### What did you see instead?

```
./foo_linux.go:5:2: unreachable code
Go vet exited.

GOOS: nacl
```

That's odd that GOOS-es are different when go-vet-ing and executing the snippet.

**Comment by agnivade** [comment]
Just a hunch, but maybe build tags are set to linux/amd64 when playground runs vet. That's why it always goes to foo_linux.go first and exits. And while running, it always gives GOOS as nacl.

@ysmolsky @andybons @dmitshur

**Comment by hajimehoshi** [comment]
This is no longer an issue.
