### ISSUE TITLE
strconv: Doubt about atof 

### ISSUE THREAD

**Issue by achun** [golang/go#32494]
https://github.com/golang/go/blob/13f179b9c8c3b9d9066e71d0a69cff8c0876098b/src/strconv/atof_test.go#L50

The code

```
{"0x1ep-1", "15", nil}
```

Should be

```
{"0x1ep-1", "0.9375", nil}
```

**Comment by robpike** [comment]
No, in hexadecimal constants the exponent is still in decimal. Thus this example is 30/2 not 30/16. (Anyway 0.9375 is 15/16; not sure how you got that.)

Thus the example is correct.

**Comment by robpike** [comment]
From the spec:
A hexadecimal floating-point literal consists of a 0x or 0X prefix, an integer part (hexadecimal digits), a radix point, a fractional part (hexadecimal digits), and an exponent part (p or P followed by an optional sign and decimal digits). One of the integer part or the fractional part may be elided; the radix point may be elided as well, but the exponent part is required. (This syntax matches the one given in IEEE 754-2008 §5.12.3.) An exponent value exp scales the mantissa (integer and fractional part) by 2exp.

**Comment by achun** [comment]
Thank you robpike
