### ISSUE TITLE
net/textproto: unclear statement about ReadContinuedLine

### ISSUE THREAD

**Issue by pam4** [golang/go#32493]
From the [documentation](https://golang.org/pkg/net/textproto/#Reader.ReadContinuedLine):

> A line consisting of only white space is never continued.

I can't make sense of the above statement.
```go
var txt string
txt += "A \n" // line 1
txt += "  \n" // line 2
txt += " B\n" // line 3
tp := textproto.NewReader(bufio.NewReader(strings.NewReader(txt)))
s, err := tp.ReadContinuedLine()
fmt.Printf("%q %v\n", s, err)
```
Prints `"A  B" <nil>` (https://play.golang.org/p/Bsrs8-5bAft).

Line 2 consists of only white space but it *is* "continued" (as it should be, I think).
I propose to clarify ~or remove~ the statement in question.

**EDIT**: It should probably read: "An empty line is never continued".

**Comment by pam4** [comment]
Is this lost in bureaucracy?
The CL is 6 words of documentation and has been sitting for a year with no feedback. I'm not familiar enough with the process here, but it seems far from satisfactory.

**Comment by ianlancetaylor** [comment]
Sorry about that.  I'm not sure why that change got lost.
