### ISSUE TITLE
go.mod shows changed in Git on Windows

### ISSUE THREAD

**Issue by josephzidell** [golang/go#32491]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xyz\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\xyz\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=c:\code\arms\api\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\xyz\AppData\Local\Temp\go-build896467466=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
Switched git branches, then ran `git status`

### What did you expect to see?
```nothing to commit, working tree clean```

### What did you see instead?
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   go.mod
```

**Comment by alexbrainman** [comment]
> Switched git branches, then ran `git status`

These instructions are not enough to demonstrate your problem.

I tried this:

```
c:\Users\Alex\dev\src\b>git status
On branch a1
nothing to commit, working tree clean

c:\Users\Alex\dev\src\b>git checkout a2
Switched to branch 'a2'

c:\Users\Alex\dev\src\b>git status
On branch a2
nothing to commit, working tree clean

c:\Users\Alex\dev\src\b>
```

I don't see what you see.

Alex

**Comment by josephzidell** [comment]
@alexbrainman After the weekend, this issue is not reproducing. Closing now until I can reproduce definitively.
