### ISSUE TITLE
cmd/go: TestScript/env_write failed

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#32503]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +13f179b9c8 Fri Jun 7 23:25:54 2019 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yoshiki/Library/Caches/go-build"
GOENV="/Users/yoshiki/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/yoshiki/gocode:/Users/yoshiki/exercises/gpl:/Users/yoshiki/oak"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/yoshiki/tools/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/yoshiki/tools/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/yoshiki/tools/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r3/f30_9n8958j4ndrjyl1k7mp40000gn/T/go-build081806595=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version devel +13f179b9c8 Fri Jun 7 23:25:54 2019 +0000 darwin/amd64
GOROOT/bin/go tool compile -V: compile version devel +13f179b9c8 Fri Jun 7 23:25:54 2019 +0000
uname -v: Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
lldb --version: lldb-1001.0.13.3
  Swift-5.0
</pre></details>

### What did you expect to see?

I tried to rebuild the latest tip with all.bash. I expected the all.bash didn't fail.

### What did you see instead?

```
ok  	cmd/fix	0.032s
go test proxy running at GOPROXY=http://127.0.0.1:57012/mod
--- FAIL: TestScript (0.00s)
    --- FAIL: TestScript/env_write (0.04s)
        script_test.go:192: 
            # go env should default to the right places (0.034s)
            > env AppData=$HOME/windowsappdata
            > env home=$HOME/plan9home
            > go env GOENV
            [stdout]
            /no-home/Library/Application Support/go/env
            > [aix] stdout $HOME/.config/go/env
            > [darwin] stdout '$HOME/Library/Application Support/go/env'
            FAIL: testdata/script/env_write.txt:8: no match for `(?m)$HOME/Library/Application Support/go/env` found in stdout
            
FAIL
FAIL	cmd/go	131.354s
```

**Comment by agnivade** [comment]
@mvdan

**Comment by av86743** [comment]
Issue #32475
CL https://golang.org/cl/181177 
Change was not validated on target platform.

**Comment by mvdan** [comment]
You can see similar failures on https://build.golang.org/. This is my bad; I didn't know that there were no mac machines in the trybot list.

Initially it was a syntax error, fixed in https://go-review.googlesource.com/c/go/+/181278. But that wasn't the end of the story.

I don't have a Mac to test this with unfortunately, and I've already made two mistakes when guessing :)

**Comment by mvdan** [comment]
FYI @andybons @dmitshur for the first beta (and because I think either/both of you run on macs)

**Comment by av86743** [comment]
@mvdan

> I don't have a Mac to test this with...

You are joking, right?

**Comment by mvdan** [comment]
Why would I be joking?
