### ISSUE TITLE
gollvm: update functions getContents and setRemarkStreamer

### ISSUE THREAD

**Issue by erifan** [golang/go#32517]
This llvm CL https://reviews.llvm.org/rG6ada11f13466a758597f912156be47ffca2e1408 changed the API RemarkStreamer::RemarkStreamer, and this llvm CL https://reviews.llvm.org/rG98090824a617c7e1719a296e57859a45775a8e57#change-xtjxSKpXMYzJ changed function getContents. Gollvm used these two functions and needs to sync these changes, or the building will fail.

**Comment by cherrymui** [comment]
Thanks for reporting. Will look into it.

(In the meantime, you can check out an older LLVM commit for building gollvm.)
