### ISSUE TITLE
x/mobile: gomobile init failed

### ISSUE THREAD

**Issue by guotie** [golang/go#32514]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.11.5
</pre>

### Does this issue reproduce with the latest release?

yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\gopath\
set GOPROXY=
set GORACE=
set GOROOT=E:\bin\Go
set GOTMPDIR=
set GOTOOLDIR=E:\bin\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build144258234=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

Use gomobile init -ndk `my-ndk-path`, it failed:
```
# gomobile init -ndk=C:\Users\Administrator\AppData\Local\Android\Sdk\ndk-bundle
gomobile: C:\Users\Administrator\AppData\Local\Android\Sdk\ndk-bundle\prebuilt\windows-x86_64\bin\python2.7 build/tools/make_standalone_toolchain.py --arch=arm --api=15 --install-dir=E:\gopath\pkg\gomobile\ndk-toolchains\arm failed: exit status 1
WARNING:__main__:make_standalone_toolchain.py is no longer necessary. The
%NDK%\toolchains\llvm\prebuilt\windows-x86_64\bin directory contains target-specific scripts that perform
the same task. For example, instead of:

    C:\>python %NDK%\build\tools\make_standalone_toolchain.py \
        --arch arm --api 15 --install-dir toolchain
    C:\>toolchain\bin\clang++ src.cpp

Instead use:

    C:\>%NDK%\toolchains\llvm\prebuilt\windows-x86_64\bin\armv7a-linux-androideabi15-clang++ src.cpp

15 is less than minimum platform for arm (16)


```

**Comment by odeke-em** [comment]
Thank you for reporting this issue @guotie!

Unfortunately I still don't get what the issue is. Is it that  your version of the Android API (of 15) isn't supported yet we claim to support at least 15?

Kindly paging @eliasnaur @hyangah

**Comment by eliasnaur** [comment]
Please update your gomobile tools:

go get -u golang.org/x/mobile/cmd/...

Gomobile init hasn't been necessary for a while now.

**Comment by guotie** [comment]
yes, gomobile init does not ecessary.
