### ISSUE TITLE
runtime: fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by Swhite215** [golang/go#32524]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/fcprxbci/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/fcprxbci/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ws/xmcjpcrd0n9cx4vm8zq5vplnl7pjk6/T/go-build383146832=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I am working on a project using Hyperledger Fabric. I am attempting to install chaincode on one of my peer nodes using this command:
`docker exec $env_vars $peer peer chaincode install -n loan-chain -l node -p /opt/gopath/src/github.com/hyperledger/fabric/peer/loan-chain-node -v v1 --tls --cafile /etc/hyperledger/msp/orderer0.example.com/msp/tlscacerts/tlsca.example.com-cert.pem 
`
The error sometimes randomly goes away with repeated attempts.

### What did you expect to see?
Expected chaincode to be successfully installed: `Installed remotely response:<status:200 payload:"OK"`

### What did you see instead?
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7fd384254638]

runtime stack:
runtime.throw(0x1272c18, 0x2a)
        /opt/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
        /opt/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 1 [syscall]:
runtime.cgocall(0xe45f30, 0xc0003e2c70, 0x29)
        /opt/go/src/runtime/cgocall.go:128 +0x5e fp=0xc0003e2c38 sp=0xc0003e2c00 pc=0x4039ee
os/user._Cfunc_mygetgrgid_r(0x3b81b428, 0xc00022c000, 0x7fd36c0008c0, 0x400, 0xc00014a0d8, 0xc000000000)
        _cgo_gotypes.go:106 +0x4d fp=0xc0003e2c70 sp=0xc0003e2c38 pc=0x79d33d
os/user.lookupUnixGid.func1.1(0x3b81b428, 0xc00022c000, 0x7fd36c0008c0, 0x400, 0xc00014a0d8, 0xc0003e2d08)
        /opt/go/src/os/user/cgo_lookup_unix.go:181 +0x135 fp=0xc0003e2cb0 sp=0xc0003e2c70 pc=0x79f2a5
os/user.lookupUnixGid.func1(0x110e8c0)
        /opt/go/src/os/user/cgo_lookup_unix.go:181 +0x50 fp=0xc0003e2cf0 sp=0xc0003e2cb0 pc=0x79f340
os/user.retryWithBuffer(0xc000412000, 0xc0003e2dd8, 0xc000412000, 0x48)
        /opt/go/src/os/user/cgo_lookup_unix.go:253 +0x3e fp=0xc0003e2d48 sp=0xc0003e2cf0 pc=0x79e59e
os/user.lookupUnixGid(0x3b81b428, 0x0, 0x0, 0x0)
        /opt/go/src/os/user/cgo_lookup_unix.go:177 +0x130 fp=0xc0003e2e10 sp=0xc0003e2d48 pc=0x79e0a0
os/user.lookupGroupId(0xc00035c020, 0x9, 0xa, 0xc00035c020, 0x9)
        /opt/go/src/os/user/cgo_lookup_unix.go:167 +0x73 fp=0xc0003e2e48 sp=0xc0003e2e10 pc=0x79df33
os/user.LookupGroupId(0xc00035c020, 0x9, 0x9, 0x0, 0x0)
        /opt/go/src/os/user/lookup.go:53 +0x35 fp=0xc0003e2e80 sp=0xc0003e2e48 pc=0x79d015
archive/tar.statUnix(0x13bc060, 0xc00015bba0, 0xc00003afc0, 0x1fa1740, 0x492a36)
        /opt/go/src/archive/tar/stat_unix.go:45 +0x379 fp=0xc0003e2ef0 sp=0xc0003e2e80 pc=0x7a8a39
archive/tar.FileInfoHeader(0x13bc060, 0xc00015bba0, 0xc000385b00, 0x54, 0x0, 0x0, 0x1)
        /opt/go/src/archive/tar/common.go:702 +0x454 fp=0xc0003e3070 sp=0xc0003e2ef0 pc=0x7a2074
github.com/hyperledger/fabric/core/container/util.WriteStreamToPackage(0x139bb00, 0xc000229080, 0xc000385b00, 0x54, 0xc00040e6e0, 0x15, 0xc000092e00, 0x38, 0xc0003e32c8)
        /opt/gopath/src/github.com/hyperledger/fabric/core/container/util/writer.go:185 +0x18b fp=0xc0003e3228 sp=0xc0003e3070 pc=0x8dfabb
github.com/hyperledger/fabric/core/container/util.WriteFileToPackage(0xc000385b00, 0x54, 0xc00040e6e0, 0x15, 0xc000092e00, 0x0, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/core/container/util/writer.go:175 +0x395 fp=0xc0003e3358 sp=0xc0003e3228 pc=0x8df8a5
github.com/hyperledger/fabric/core/container/util.WriteFolderToTarPackage.func1(0xc000385b00, 0x54, 0x13bc060, 0xc00015bad0, 0x0, 0x0, 0xd, 0xc0003e3510)
        /opt/gopath/src/github.com/hyperledger/fabric/core/container/util/writer.go:127 +0x377 fp=0xc0003e3488 sp=0xc0003e3358 pc=0x8e0577
path/filepath.walk(0xc000385b00, 0x54, 0x13bc060, 0xc00015bad0, 0xc000228cc0, 0x0, 0x0)
        /opt/go/src/path/filepath/path.go:358 +0x41c fp=0xc0003e3560 sp=0xc0003e3488 pc=0x512a0c
path/filepath.walk(0xc0004106e0, 0x46, 0x13bc060, 0xc00015b860, 0xc000228cc0, 0x0, 0x0)
        /opt/go/src/path/filepath/path.go:382 +0x2fe fp=0xc0003e3638 sp=0xc0003e3560 pc=0x5128ee
path/filepath.walk(0x7ffc1d99398b, 0x42, 0x13bc060, 0xc00015b450, 0xc000228cc0, 0x0, 0x60)
        /opt/go/src/path/filepath/path.go:382 +0x2fe fp=0xc0003e3710 sp=0xc0003e3638 pc=0x5128ee
path/filepath.Walk(0x7ffc1d99398b, 0x42, 0xc000228cc0, 0x0, 0x1)
        /opt/go/src/path/filepath/path.go:404 +0x105 fp=0xc0003e3770 sp=0xc0003e3710 pc=0x512b45
github.com/hyperledger/fabric/core/container/util.WriteFolderToTarPackage(0xc000092e00, 0x7ffc1d99398b, 0x42, 0xc000379920, 0x1, 0x1, 0x0, 0x0, 0x13bc060, 0xc00015b380)
        /opt/gopath/src/github.com/hyperledger/fabric/core/container/util/writer.go:136 +0x24a fp=0xc0003e3868 sp=0xc0003e3770 pc=0x8deeba
github.com/hyperledger/fabric/core/chaincode/platforms/node.(*Platform).GetDeploymentPayload(0x1fc5e60, 0x7ffc1d99398b, 0x42, 0x4, 0xc00016f198, 0x123d701, 0x4, 0xc0003799c0)
        /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/platforms/node/platform.go:160 +0x235 fp=0xc0003e3960 sp=0xc0003e3868 pc=0xa29c45
github.com/hyperledger/fabric/core/chaincode/platforms.(*Registry).GetDeploymentPayload(0xc0002b29a0, 0x123d77a, 0x4, 0x7ffc1d99398b, 0x42, 0x4, 0x7ffc1d99398b, 0x42, 0x0, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/platforms/platforms.go:103 +0x8f fp=0xc0003e39d0 sp=0xc0003e3960 pc=0x8e12cf
github.com/hyperledger/fabric/core/container.GetChaincodePackageBytes(0xc0002b29a0, 0xc000151c40, 0x0, 0x1197340, 0xc0003c8730, 0xc00035d614, 0x4)
        /opt/gopath/src/github.com/hyperledger/fabric/core/container/controller.go:217 +0xc7 fp=0xc0003e3a30 sp=0xc0003e39d0 pc=0xd35f47
github.com/hyperledger/fabric/peer/chaincode.getChaincodeDeploymentSpec(0xc000151c40, 0xc000151c01, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/common.go:58 +0x11c fp=0xc0003e3aa0 sp=0xc0003e3a30 pc=0xd4f9ec
github.com/hyperledger/fabric/peer/chaincode.genChaincodeDeploymentSpec(0xc0001e4780, 0x7ffc1d993975, 0xa, 0x7ffc1d9939d1, 0x2, 0x0, 0x6020100, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/install.go:109 +0xac fp=0xc0003e3b68 sp=0xc0003e3aa0 pc=0xd56aec
github.com/hyperledger/fabric/peer/chaincode.chaincodeInstall(0xc0001e4780, 0x0, 0x0, 0xc00010cdc0, 0x0, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/install.go:177 +0x156 fp=0xc0003e3c58 sp=0xc0003e3b68 pc=0xd57276
github.com/hyperledger/fabric/peer/chaincode.installCmd.func1(0xc0001e4780, 0xc0001e7970, 0x0, 0xb, 0x0, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/install.go:44 +0x54 fp=0xc0003e3c98 sp=0xc0003e3c58 pc=0xd5c5e4
github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).execute(0xc0001e4780, 0xc0001e78c0, 0xb, 0xb, 0xc0001e4780, 0xc0001e78c0)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:762 +0x473 fp=0xc0003e3d88 sp=0xc0003e3c98 pc=0xd21183
github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1eb4220, 0x8, 0x0, 0x1eb33e0)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:852 +0x2fd fp=0xc0003e3ec8 sp=0xc0003e3d88 pc=0xd21b7d
github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).Execute(0x1eb4220, 0xc00029ff40, 0x1)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:800 +0x2b fp=0xc0003e3ef8 sp=0xc0003e3ec8 pc=0xd2185b
main.main()
        /opt/gopath/src/github.com/hyperledger/fabric/peer/main.go:53 +0x2f7 fp=0xc0003e3f98 sp=0xc0003e3ef8 pc=0xe45427
runtime.main()
        /opt/go/src/runtime/proc.go:201 +0x207 fp=0xc0003e3fe0 sp=0xc0003e3f98 pc=0x42f7b7
runtime.goexit()
        /opt/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0003e3fe8 sp=0xc0003e3fe0 pc=0x45de51

goroutine 8 [syscall]:
os/signal.signal_recv(0x0)
        /opt/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /opt/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /opt/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 36 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc000150540, 0x1, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:317 +0x103
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc0003fa3c0, 0x0, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:435 +0x1ac
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client.func3(0xc0000c8680)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport/http2_client.go:301 +0x7b
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport/http2_client.go:299 +0xc53

goroutine 23 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*ccResolverWrapper).watcher(0xc000393380)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:109 +0x142
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*ccResolverWrapper).start
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:95 +0x3f

goroutine 24 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000085000)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:122 +0x10f
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc.newCCBalancerWrapper
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:113 +0x13d

goroutine 25 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc00016c280)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:1070 +0x1c1
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc00016c280)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:622 +0x1b2
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*addrConn).connect
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:613 +0xe1

goroutine 34 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport.(*http2Client).keepalive(0xc0000c8680)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport/http2_client.go:1229 +0x113
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport/http2_client.go:256 +0x1281

goroutine 35 [IO wait]:
internal/poll.runtime_pollWait(0x7fd384661f00, 0x72, 0xc00006f988)
        /opt/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000154218, 0x72, 0xffffffffffffff00, 0x13a05a0, 0x1ed6df0)
        /opt/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000154218, 0xc0000ec000, 0x400, 0x400)
        /opt/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000154200, 0xc0000ec000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /opt/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000154200, 0xc0000ec000, 0x400, 0x400, 0x40983b, 0xc000030000, 0x10b2ec0)
        /opt/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000c0028, 0xc0000ec000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /opt/go/src/net/net.go:177 +0x68
crypto/tls.(*block).readFromUntil(0xc0002ee060, 0x139e660, 0xc0000c0028, 0x5, 0xc0000c0028, 0x0)
        /opt/go/src/crypto/tls/conn.go:492 +0x89
crypto/tls.(*Conn).readRecord(0xc000214700, 0x12a4b17, 0xc000214820, 0x0)
        /opt/go/src/crypto/tls/conn.go:593 +0xdd
crypto/tls.(*Conn).Read(0xc000214700, 0xc0001c4000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /opt/go/src/crypto/tls/conn.go:1145 +0xf1
bufio.(*Reader).Read(0xc0003fa300, 0xc00003a2d8, 0x9, 0x9, 0x30, 0x28, 0x1164560)
        /opt/go/src/bufio/bufio.go:216 +0x22f
io.ReadAtLeast(0x139bb00, 0xc0003fa300, 0xc00003a2d8, 0x9, 0x9, 0x9, 0xc0003ca1e0, 0x4024ee, 0xc00006fe9b)
        /opt/go/src/io/io.go:310 +0x88
io.ReadFull(0x139bb00, 0xc0003fa300, 0xc00003a2d8, 0x9, 0x9, 0x99048a, 0xc0003ca210, 0xc0003c0004)
        /opt/go/src/io/io.go:329 +0x58
github.com/hyperledger/fabric/vendor/golang.org/x/net/http2.readFrameHeader(0xc00003a2d8, 0x9, 0x9, 0x139bb00, 0xc0003fa300, 0x0, 0x0, 0xc0003ca210, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/hyperledger/fabric/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc00003a2a0, 0xc0003ca210, 0xc0003ca200, 0x0, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/golang.org/x/net/http2/frame.go:492 +0xa3
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc0000c8680)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport/http2_client.go:1178 +0x12e
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport/http2_client.go:261 +0xaf8

goroutine 38 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*ccResolverWrapper).watcher(0xc0002ef590)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:109 +0x142
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*ccResolverWrapper).start
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:95 +0x3f

goroutine 39 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000150980)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:122 +0x10f
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc.newCCBalancerWrapper
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:113 +0x13d

goroutine 40 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc00034e780)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:1070 +0x1c1
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc00034e780)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:622 +0x1b2
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*addrConn).connect
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:613 +0xe1

goroutine 46 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport.(*http2Client).keepalive(0xc0000c8820)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport/http2_client.go:1229 +0x113
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport/http2_client.go:256 +0x1281

goroutine 47 [IO wait]:
internal/poll.runtime_pollWait(0x7fd384661e30, 0x72, 0xc00006d988)
        /opt/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000386698, 0x72, 0xffffffffffffff00, 0x13a05a0, 0x1ed6df0)
        /opt/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000386698, 0xc0000ecc00, 0x400, 0x400)
        /opt/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000386680, 0xc0000ecc00, 0x400, 0x400, 0x0, 0x0, 0x0)
        /opt/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000386680, 0xc0000ecc00, 0x400, 0x400, 0x40983b, 0xc000030000, 0x10b2ec0)
        /opt/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00014a648, 0xc0000ecc00, 0x400, 0x400, 0x0, 0x0, 0x0)
        /opt/go/src/net/net.go:177 +0x68
crypto/tls.(*block).readFromUntil(0xc0002ef920, 0x139e660, 0xc00014a648, 0x5, 0xc00014a648, 0x0)
        /opt/go/src/crypto/tls/conn.go:492 +0x89
crypto/tls.(*Conn).readRecord(0xc000092700, 0x12a4b17, 0xc000092820, 0x0)
        /opt/go/src/crypto/tls/conn.go:593 +0xdd
crypto/tls.(*Conn).Read(0xc000092700, 0xc000220000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /opt/go/src/crypto/tls/conn.go:1145 +0xf1
bufio.(*Reader).Read(0xc0002a0c60, 0xc00003a8f8, 0x9, 0x9, 0x30, 0x28, 0x1164560)
        /opt/go/src/bufio/bufio.go:216 +0x22f
io.ReadAtLeast(0x139bb00, 0xc0002a0c60, 0xc00003a8f8, 0x9, 0x9, 0x9, 0xc0003939b0, 0x4024ee, 0xc00006de9b)
        /opt/go/src/io/io.go:310 +0x88
io.ReadFull(0x139bb00, 0xc0002a0c60, 0xc00003a8f8, 0x9, 0x9, 0x99048a, 0xc0003c4000, 0xc0003c0004)
        /opt/go/src/io/io.go:329 +0x58
github.com/hyperledger/fabric/vendor/golang.org/x/net/http2.readFrameHeader(0xc00003a8f8, 0x9, 0x9, 0x139bb00, 0xc0002a0c60, 0x0, 0x0, 0xc0003c4000, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/hyperledger/fabric/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc00003a8c0, 0xc0003c4000, 0xc0003c4000, 0x0, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/golang.org/x/net/http2/frame.go:492 +0xa3
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc0000c8820)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport/http2_client.go:1178 +0x12e
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport/http2_client.go:261 +0xaf8

goroutine 48 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc000151840, 0x1, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:317 +0x103
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc0002f61e0, 0x0, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:435 +0x1ac
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client.func3(0xc0000c8820)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport/http2_client.go:301 +0x7b
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/internal/transport/http2_client.go:299 +0xc53

**Comment by AlexRouSg** [comment]
How have you determined that this is a issue with Go and not chaincode?

**Comment by agnivade** [comment]
Please ensure that there is no race in your code by building with the `-race` flag.

And if you believe this is a bug in Go and not chaincode, please give us a sample code along with instructions on how to reproduce this error.

**Comment by Swhite215** [comment]
The exact same chaincode is used in multiple other projects successfully. To be honest I am not familiar with go and don't know what else would be producing this error. I can't provide code to reproduce the error. Could either of you point me in the direction as to where I might solve this problem or what is causing it?

**Comment by AlexRouSg** [comment]
I would start with reporting the issue to hyperledger and and go through their process.
https://hyperledger-fabric.readthedocs.io/en/release-1.4/questions.html

**Comment by agnivade** [comment]
> The exact same chaincode is used in multiple other projects successfully. 

Race conditions manifest in strange ways. It just might be that this project triggers it.

I would recommend to first build with the `-race` flag to ensure there are no races. Then, ask hyperledger forums for help. If they say it's an issue with Go, then file an issue with the _exact_ steps for us to reproduce the issue. Not just a single docker command. We would need the entire list of steps to prepare the environment and reproduce the issue.

I am going to close this as there isn't enough evidence that this is an issue with Go. However, if you have indeed found that it is an issue with Go, please feel free to open a separate issue. Thanks.
