### ISSUE TITLE
Shouldn't "encoding/xml" handling of []byte mirror that of "encoding/json"?

### ISSUE THREAD

**Issue by jvsteiner** [golang/go#32525]
### What version of Go are you using (`go version`)?

v.1.12.5

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/Users/jamie/Code/go/bin"
GOCACHE="/Users/jamie/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jamie/Code/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-I/usr/local/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/y9/_gm0t1010sx43s27vxrcrmh40000gq/T/go-build272664046=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://play.golang.org/p/oZCebOm521l

Marshaled a `[]byte` using "encoding/xml"

### What did you expect to see?

base64 encoded handling, like with json

### What did you see instead?

a raw binary interpretation

**Comment by ianlancetaylor** [comment]
XML and JSON are not the same.  The code is working as intended.
