### ISSUE TITLE
runtime: non-blocking read on an empty closed channel takes the slow path

### ISSUE THREAD

**Issue by bemasc** [golang/go#32529]
On my workstation, nonblocking receive on an empty open channel is about 700 times faster than nonblocking receive on an empty closed channel.  This is because `chanrecv()` in `runtime/chan.go` has a special-case optimization that takes a lock-free path in this case.  A similar lock-free path can be implemented for closed channels, and should result in similar performance.

**Comment by randall77** [comment]
Reopened because fixing CL has been reverted.
