### ISSUE TITLE
Can't compile aar under windows

### ISSUE THREAD

**Issue by marinat** [golang/go#32521]
### What version of Go are you using (`go version`)?
go1.12.5 windows/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

windows 10/amd64

### What did you do?

Hello world like project:
`package goTest

import "fmt"
func Main() {
	fmt.Println("hello world")
}`

gomobile init
gomobile bind -o pult.aar -target=android

### What did you expect to see?
generated .aar file

### What did you see instead?
gomobile: go build -buildmode=c-shared -o=C:\Users\1\AppData\Local\Temp\gomobile-work-762096787\android\src\main\jniLibs\armeabi-v7a\libgojni.so gobind failed: exit status 1
C:\Users\1\AppData\Local\Temp\gomobile-work-762096787\src\gobind\go_goTestmain.go:17:2: local import "." in non-local package

**Comment by AlexRouSg** [comment]
Your go source files needs to be in `%GOPATH%/src/importpath` on windows `GOPATH` by default is at `%USERPROFILE%/go`

related: #27234

**Comment by marinat** [comment]
Thanks! Thats right!
