### ISSUE TITLE
net: TestDialerControl flake on darwin-amd64-race

### ISSUE THREAD

**Issue by bcmills** [golang/go#32534]
https://build.golang.org/log/03a8960a27ab5e837fa3d57ae7b08f6ece4a4285:

```
--- FAIL: TestDialerControl (75.50s)
    --- FAIL: TestDialerControl/StreamDial (75.50s)
        dial_test.go:944: dial tcp6 [::1]:49570: connect: operation timed out
FAIL
FAIL	net	86.859s
```

Looks like the test was added about a year ago (in [CL 72810](https://golang.org/cl/72810)). It's not obvious to me whether this is a recent regression or just a low-frequency flake.

CC @ianlancetaylor @mikioh

**Comment by networkimprov** [comment]
cc @bradfitz

**Comment by bcmills** [comment]
No more failures in about a year. Possibly fixed (in the sense of no longer affected by a probable macOS kernel bug?) by #34920.

[2019-08-30T17:07:53-9d480ed/darwin-amd64-race](https://build.golang.org/log/8a75e974b5a6dbc9e5afb1a6049581aa33b4cada)
[2019-06-10T13:43:51-ec3ebf7/darwin-amd64-race](https://build.golang.org/log/03a8960a27ab5e837fa3d57ae7b08f6ece4a4285)
