### ISSUE TITLE
Getting undefined error for SameSiteNoneMode 

### ISSUE THREAD

**Issue by vsubramoney** [golang/go#32546]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12.5 
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?
windows/amd64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
I am adding a new cookie as follows
newCookie := &http.Cookie{
                Name:     MatchCookieName,
                Domain:   GetRootDomain(r),
                MaxAge:   CookieMaxAge,
                Expires:  time.Now().Add(CookieMaxAge),
                Value:    matchCookieAfter.EncodeToBase64(),
                SameSite: http.SameSiteNoneMode,
                Path:     "/",
            }

### What did you expect to see?

It should not give any error, I do not get any errors for
SameSiteLaxMode anf SameSiteNoneMode

### What did you see instead?

Getting an undefined error for SameSiteNoneMode

**Comment by agnivade** [comment]
Because there is no `SameSiteNoneMode`. https://golang.org/pkg/net/http/#SameSite

For further questions, please reach out to the forums in the [Questions](https://github.com/golang/go/wiki/Questions) wiki page.

**Comment by vsubramoney** [comment]
i see the changes getting added in 
https://github.com/golang/go/blob/master/src/net/http/cookie.go

type SameSite int

const (
	SameSiteDefaultMode SameSite = iota + 1
	SameSiteLaxMode
	SameSiteStrictMode
	SameSiteNoneMode
)
when would this be updated.

**Comment by agnivade** [comment]
When 1.13 is released.
