### ISSUE TITLE
encoding/asn1: Marshal fails with ECDSA public keys

### ISSUE THREAD

**Issue by andrewmbenton** [golang/go#32541]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
The latest stable release, yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
</pre></details>

### What did you do?
I attempted to use the `asn1` package to encode the public portion of an ECDSA key.

Here's a link to the playground: https://play.golang.org/p/Kwfs67b4KaI

### What did you expect to see?
Encoded bytes.

### What did you see instead?
An error.

**Comment by FiloSottile** [comment]
`ecdsa.PublicKey` is a complex type that includes values that can't be serialized, and `encoding/asn1` does not have special cases for known types, so it tries to serialize everything.

Use `crypto/x509.MarshalPKIXPublicKey` or create your own struct to pass to `Marshal` if you need a specific encoding.

**Comment by andrewmbenton** [comment]
Yeah in retrospect this makes sense. `crypto/x509.MarshalPKIXPublicKey` adds PKIX format overhead though, which you have to then unpack if you just want the public key bytes.

Ideally the x509 package would export its `marshalPublicKey` func name. Any reason not to do that?

For now I have to essentially replicate the internals of that func and use `crypto/elliptic.Marshal` directly.

**Comment by FiloSottile** [comment]
Feel free to open a proposal issue for it. The two main reasons I can think of that might not get it accepted are if there is no reference for its format, or if it's not invertible without knowing the type in advance (that is, we can't write a corresponding Parse function). If you to address those, it will help getting it approved.

**Comment by mathieudevos** [comment]
I'm entirely opposed to opening marshalPublicKey, instead I suggested we split its functionality in 2 to increase type-safety in the program.

Proposal: https://github.com/golang/go/issues/32657
