### ISSUE TITLE
"build constraints exclude all Go files in" when trying to import golang.org/x/sys/unix

### ISSUE THREAD

**Issue by aadarshpratik1** [golang/go#32548]
What exactly did you do? Did you specify `GOOS=js` and `GOARCH=wasm`?

_Originally posted by @neelance in https://github.com/golang/go/issues/26598#issuecomment-407818226_

I saw this answer in an old issue but did not understand why this needs to be done

**Comment by AlexRouSg** [comment]
Please fill in the entire issue template you see when creating a new issue. What exactly are you trying to do? And what exactly is your build environment? (Output from the command `go env`)

Setting `GOOS` and/or `GOARCH` means you are cross compiling. `golang.org/x/sys/unix` as the name suggest, is a unix package and thus is only for Linux/OSX and other unix based operating systems. Your issue title suggest you are on windows, in which case you cannot use this package.

**Comment by agnivade** [comment]
If you do not specify GOOS and GOARCH, the build constraints won't pick up the right files for that target. Please see https://golang.org/pkg/go/build/#hdr-Build_Constraints.

For further questions, please feel free to take a look at the [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions.
