### ISSUE TITLE
Bug in using slice : index can be exceeded

### ISSUE THREAD

**Issue by promptsrw** [golang/go#32549]
I use go version go1.12.5 windows/amd64. 
I can use exceeding slice index and got successful code compilation. My problem is in the code below

```
package main
import (
	"fmt"
)
func main() 
{
        j := []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

	j = j[:4]
	fmt.Println(j)

	j = j[1:]
	fmt.Println(j)

	j = j[:8] // <<<<<<<<<<<<<<< I should get error by this line but dont
	fmt.Println(len(j), j)
}

```

Should I get an error because I used exceeding slice index? Yes , I should, but I got complete result instead.  The result I got is
```
[1 2 3 4]
[2 3 4]
8 [2 3 4 5 6 7 8 9]
```

You can try in this link.
https://play.golang.org/p/M4VLmRdunRr

**Comment by mvdan** [comment]
You can index all the way to a slice's capacity, not just its length. Please see https://golang.org/ref/spec#Slice_expressions:

> For slices, the upper index bound is the slice capacity cap(a) rather than the length.

**Comment by promptsrw** [comment]
Thanks I miss it.
