### ISSUE TITLE
cmd/go: GO111MODULE=on  go get -v -insecure gitlab.com/xxx/xxx failed

### ISSUE THREAD

**Issue by KielChan** [golang/go#32569]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
I am not sure.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build123327735=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I have a package in gitlab repo, but path in the package shows like "github.com/xxx/xxx"

so, I replace it like this in go.mod:
```
module gitlab.com/grp/proj

go 1.12

require (

	github.com/xxx/xxx v1.0.0


replace github.com/xxx/xxx v1.0.0 => gitlab.com/xxx/xxx v0.0.0-xxxxxx-xxxxx

```
on my macOS, I can exec cmd `GO111MODULE=on go get -v -insecure gitlab.com/xxx/xxx` to pre-install it and then, when I exec cmd `GOOS=linux GOARCH=amd64 CGO_ENABLED=1 GO111MODULE=on GOPROXY=https://athens.azurefd.net go build`, it exit 0.

But when the cmd `GO111MODULE=on go get -v -insecure gitlab.com/xxx/xxx` executed in golang:v1.12.1 container, it may try to pull module in `go.mod` and without `GOPROXY` it failed in the end.

The go env and go version executed in `golang:1.12.1`

I want to know why.

### What did you expect to see?

I can pre-install go module solely, not all of them in go.mod

**Comment by FiloSottile** [comment]
/cc @bcmills @jayconrod 

By the way, why are you using `-insecure`?

**Comment by bcmills** [comment]
> without `GOPROXY` it failed in the end.

* What was the failure message?
* The current `go` release is 1.12.6. Can you still reproduce the problem using that release instead of 1.12.1?
* Is the GitLab repo private? (Is this an instance of #29888 or #29094?)
