### ISSUE TITLE
cmd/go: go mod tidy gitlab.com error: RPC failed; result=22, HTTP code = 404

### ISSUE THREAD

**Issue by liuliqiang** [golang/go#32566]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, it does.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/liuliqiang/soft/installed/dev/go/gopath"
GOPROXY=""
GORACE=""
GOROOT="/home/liuliqiang/soft/installed/dev/go/go"
GOTMPDIR=""
GOTOOLDIR="/home/liuliqiang/soft/installed/dev/go/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build306223789=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

i just input `go mod tidy` in the project root directory and get the following error:

<details><summary><code>go mod tidy</code> Output</summary><br><pre>
$ go mod tidy
go: finding k8s.io/apiserver/pkg/features latest
go: finding k8s.io/apiserver/pkg/authentication/user latest
go: finding k8s.io/apiserver/pkg/util/feature latest
go: finding k8s.io/apiserver/pkg/authentication/authenticator latest
go: finding k8s.io/apiserver/pkg/authentication/serviceaccount latest
go: finding k8s.io/apiserver/pkg/registry/generic latest
go: finding k8s.io/apiserver/pkg/authentication latest
go: finding k8s.io/apiextensions-apiserver/pkg/features latest
go: finding k8s.io/apiserver/pkg latest
go: finding k8s.io/apiserver/pkg/util latest
go: finding k8s.io/apiserver/pkg/registry latest
go: finding k8s.io/apiextensions-apiserver/pkg latest
go: finding k8s.io/cloud-provider/features latest
go: finding k8s.io/apiserver latest
go: finding k8s.io/apiextensions-apiserver latest
go: finding k8s.io/cloud-provider latest
go: finding k8s.io/apiserver/pkg/registry/rest latest
go: finding k8s.io/apiserver/pkg/util/feature/testing latest
go: finding k8s.io/apiserver/pkg/storage latest
go: finding k8s.io/apiserver/pkg/endpoints/request latest
go: finding k8s.io/apiserver/pkg/storage/names latest
go: finding k8s.io/apiserver/pkg/endpoints latest
go: finding github.com/prometheus/client_golang/prometheus latest
go: finding github.com/docker/distribution/reference latest
go: finding github.com/globalsign/mgo v0.0.0-20180905125535-1ca0a4f7cbcb
go: finding github.com/globalsign/mgo v0.0.0-20181015135952-eeefdecb41b8
go: finding modernc.org/mathutil v1.0.0
go: finding modernc.org/cc v1.0.0
go: finding modernc.org/golex v1.0.0
go: finding modernc.org/xc v1.0.0
go: finding modernc.org/strutil v1.0.0
go: modernc.org/golex@v1.0.0: git fetch -f https://gitlab.com/cznic/golex refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/liuliqiang/soft/installed/dev/go/gopath/pkg/mod/cache/vcs/9aae2d4c6ee72eb1c6b65f7a51a0482327c927783dea53d4058803094c9d8039: exit status 128:
        error: RPC failed; result=22, HTTP code = 404
        fatal: The remote end hung up unexpectedly
go: modernc.org/cc@v1.0.0: git fetch -f https://gitlab.com/cznic/cc refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/liuliqiang/soft/installed/dev/go/gopath/pkg/mod/cache/vcs/3dac616a9d80602010c4792ef9c0e9d9812a1be8e70453e437e9792978075db6: exit status 128:
        fatal: unable to access 'https://gitlab.com/cznic/cc/': TCP connection reset by peer
go: modernc.org/mathutil@v1.0.0: git fetch -f https://gitlab.com/cznic/mathutil refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/liuliqiang/soft/installed/dev/go/gopath/pkg/mod/cache/vcs/fb72eb2422fda47ac75ca695d44b06b82f3df3c5308e271486fca5e320879130: exit status 128:
        error: RPC failed; result=22, HTTP code = 404
        fatal: The remote end hung up unexpectedly
go: modernc.org/xc@v1.0.0: git fetch -f https://gitlab.com/cznic/xc refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/liuliqiang/soft/installed/dev/go/gopath/pkg/mod/cache/vcs/29fc2f846f24ce3630fdd4abfc664927c4ad22f98a3589050facafa0991faada: exit status 128:
        error: RPC failed; result=22, HTTP code = 404
        fatal: The remote end hung up unexpectedly
go: modernc.org/strutil@v1.0.0: git fetch -f https://gitlab.com/cznic/strutil refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/liuliqiang/soft/installed/dev/go/gopath/pkg/mod/cache/vcs/f48599000415ab70c2f95dc7528c585820ed37ee15d27040a550487e83a41748: exit status 128:
        error: RPC failed; result=22, HTTP code = 404
        fatal: The remote end hung up unexpectedly
</pre></details>

and i go to directory: `/home/liuliqiang/soft/installed/dev/go/gopath/pkg/mod/cache/vcs/f48599000415ab70c2f95dc7528c585820ed37ee15d27040a550487e83a41748` and watch the repo address, it show as following:

```
$ git remote -v
origin  https://gitlab.com/cznic/strutil (fetch)
origin  https://gitlab.com/cznic/strutil (push)
```
does it should be `https://gitlab.com/cznic/strutil.git` ？

### What did you expect to see?

`go mod tidy` run success.

### What did you see instead?

I get some error in the detail show upper.

**Comment by bcmills** [comment]
This looks like a connectivity issue between you and `gitlab.com`, or perhaps a transient server error on the GitLab side.

Are you still able to reproduce this issue?

Here's what I got (using `go build` rather than `go mod tidy`, but with the same dependencies):
```
example.com$ go1.12.6 mod init example.com
go: creating new go.mod: module example.com

example.com$ go1.12.6 get modernc.org/golex@v1.0.0
go: finding modernc.org/golex v1.0.0
go: downloading modernc.org/golex v1.0.0
go: extracting modernc.org/golex v1.0.0
go: finding modernc.org/lex v1.0.0
go: finding modernc.org/lexer v1.0.0
go: downloading modernc.org/lex v1.0.0
go: extracting modernc.org/lex v1.0.0
go: downloading modernc.org/lexer v1.0.0
go: extracting modernc.org/lexer v1.0.0
go: finding modernc.org/fileutil v1.0.0
go: finding golang.org/x/exp/ebnf latest
go: downloading modernc.org/fileutil v1.0.0
go: extracting modernc.org/fileutil v1.0.0
go: finding golang.org/x/exp latest
go: downloading golang.org/x/exp v0.0.0-20190510132918-efd6b22b2522
go: extracting golang.org/x/exp v0.0.0-20190510132918-efd6b22b2522
go: finding github.com/BurntSushi/xgb v0.0.0-20160522181843-27f122750802
go: finding golang.org/x/mobile v0.0.0-20190312151609-d3739f865fa6
go: finding golang.org/x/tools v0.0.0-20190312151545-0bb0c0a6e846
go: finding golang.org/x/sys v0.0.0-20190312061237-fead79001313
go: finding golang.org/x/image v0.0.0-20190227222117-0694c2d4d067
go: finding golang.org/x/text v0.3.0
go: finding golang.org/x/net v0.0.0-20190311183353-d8887717615a
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a

example.com$ go1.12.6 build modernc.org/golex/...

example.com$
```

**Comment by liuliqiang** [comment]
Thanks @bcmills ，After try at different times, i found maybe it's because there are some network issue in my machine.

Because when i get this error, i try command `nslookup gitlab.com` and i can't get the information for that.

I close this issue now.
