### ISSUE TITLE
panic: JSON decoder out of sync - data changing underfoot?

### ISSUE THREAD

**Issue by goith** [golang/go#32563]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/odin/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/search/odin/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-std=gnu99 -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build032790095=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
json.Unmarshal

### What did you see instead?

```
panic: JSON decoder out of sync - data changing underfoot?

goroutine 3385386 [running]:
encoding/json.(*decodeState).object(0xc005e00640, 0x78df00, 0xc00dc5b2a0, 0x196, 0xc005e00668, 0xc00674537b)
        /usr/local/go/src/encoding/json/decode.go:681 +0x2485
encoding/json.(*decodeState).value(0xc005e00640, 0x78df00, 0xc00dc5b2a0, 0x196, 0x78df00, 0xc00dc5b2a0)
        /usr/local/go/src/encoding/json/decode.go:381 +0x6e
encoding/json.(*decodeState).array(0xc005e00640, 0x7912a0, 0xc000d23b10, 0x197, 0xc005e00668, 0x5b)
        /usr/local/go/src/encoding/json/decode.go:560 +0x1a9
encoding/json.(*decodeState).value(0xc005e00640, 0x7912a0, 0xc000d23b10, 0x197, 0x7912a0, 0xc000d23b10)
        /usr/local/go/src/encoding/json/decode.go:371 +0xff
encoding/json.(*decodeState).object(0xc005e00640, 0x78dd80, 0xc00d111028, 0x196, 0xc005e00668, 0x7b)
        /usr/local/go/src/encoding/json/decode.go:763 +0x18bc
encoding/json.(*decodeState).value(0xc005e00640, 0x78dd80, 0xc00d111028, 0x196, 0x78dd80, 0xc00d111028)
        /usr/local/go/src/encoding/json/decode.go:381 +0x6e
encoding/json.(*decodeState).object(0xc005e00640, 0x78de40, 0xc00d111020, 0x16, 0xc005e00668, 0x7b)
        /usr/local/go/src/encoding/json/decode.go:763 +0x18bc
encoding/json.(*decodeState).value(0xc005e00640, 0x78de40, 0xc00d111020, 0x16, 0xc006745ba0, 0x6a5ee9)
        /usr/local/go/src/encoding/json/decode.go:381 +0x6e
encoding/json.(*decodeState).unmarshal(0xc005e00640, 0x78de40, 0xc00d111020, 0xc005e00668, 0x0)
        /usr/local/go/src/encoding/json/decode.go:179 +0x209
encoding/json.Unmarshal(0xc008a82000, 0xb9d, 0x1000, 0x78de40, 0xc00d111020, 0x1000, 0x0)
        /usr/local/go/src/encoding/json/decode.go:106 +0x123
```

**Comment by agnivade** [comment]
Please fill the entire issue template, mentioning the exact steps needed to reproduce the problem. Ensure that you are not changing the data while the unmarshaling is happening.

**Comment by dsnet** [comment]
Have you tried build the binary with the race detector enabled? See https://golang.org/doc/articles/race_detector.html

**Comment by goith** [comment]
ok， thanks.  i will check it.
