### ISSUE TITLE
x/tools/gopls: references does not guarantee ordered result

### ISSUE THREAD

**Issue by myitcv** [golang/go#32572]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +ef84fa082c Mon Jun 10 23:23:39 2019 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20190611222205-d73e1c7e250b
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/myitcv/gostuff/src/github.com/myitcv/govim/cmd/govim/.bin"
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build727910193=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

The new [references implementation](https://go-review.googlesource.com/c/tools/+/181122) is great; thanks @suzmue!

However I'm seeing that list of locations returned is not guaranteed to be ordered. Given that multiple URIs could possibly be returned, I think the most sensible default is to order by URI then start offset.

If the client then wants to apply some other initial ordering (i.e. they take the filename and map it to some state in their editor) then fine, we at least have a stable result.

I don't see this 100% of the time, hence I suspect this is the result of a map to slice conversion, where the resulting slice is then not sorted?

### What did you expect to see?

Guaranteed order of results from a call to the `references` method.

### What did you see instead?

Random ordered results.

---

cc @stamblerre @ianthehat

**Comment by stamblerre** [comment]
The LSP spec does not state anywhere that the result has to be ordered - therefore, I'd say that clients should not rely on this behavior (https://microsoft.github.io/language-server-protocol/specification#textDocument_references).

Is there a reason that the client cannot apply this ordering? VSCode definitely orders results, so it seems redundant to me for us to guarantee ordering, when more likely than not, the client will redo the sort.

**Comment by myitcv** [comment]
> Is there a reason that the client cannot apply this ordering?

No reason, other than perhaps there being a sensible default that the server might want to offer to clients so that they don't have to do the work themselves.

But just to note: the current state means that the results sent from server to client will not be stable, which is a problem if you're looking to assert in tests against the behaviour of `gopls` at a high-level input/output.

**Comment by suzmue** [comment]
Thanks for bringing this to our attention! We do not want to commit to sorting the returned results at this time since it is not in the spec.

**Comment by myitcv** [comment]
Thanks @suzmue @stamblerre. 

Quite agree that this isn't specified in the LSP spec, which I think means that one can in fact argue that returning sorted results is just as correct/valid as returning them in a random order. 

In addition to the points about it being a sensible default from the client's perspective and making testing easier, I think it's also more intuitive that for a list response type the order is defined, whether in the spec or the implementation. 

All that said, very happy to defer 😄 

Use of the references method has just landed in `govim` (https://github.com/myitcv/govim/pull/291) so thanks again for the work to get this into `gopls`!

**Comment by myitcv** [comment]
Re-opening this issue to continue discussion on the following specific point.

The `textDocument/references` method parameter is defined as follows:

```
interface ReferenceParams extends TextDocumentPositionParams {
	context: ReferenceContext
}

interface ReferenceContext {
	/**
	 * Include the declaration of the current symbol.
	 */
	includeDeclaration: boolean;
}
```

From `govim`, we set `includeDeclaration: true`. This means we're expecting the declaration to be one of the locations returned.

To my mind I think it's most intuitive to have the declaration as the first location, hence we should define that this is what `gopls` will do, regardless of whether it then sorts the remaining results or not.

What do you think?

**Comment by suzmue** [comment]
Yes, that makes sense.  Thanks for pointing that out. 

Until find references is supported at a project level (#32869), this would mean that find references would return all of the references in the current package + the declaration from the other package (if includeDeclaration=true).

**Comment by stamblerre** [comment]
Looks like the CL above fixed the problem. Please re-open if there's anything else we should do here.
