### ISSUE TITLE
x/tools/go/packages: support ad-hoc packages

### ISSUE THREAD

**Issue by stamblerre** [golang/go#32587]
`gopls` users have been reporting a common issue - `gopls` fails outside of `$GOPATH` without a `go.mod` file. This is to be expected, because `go/packages` does not support the `file=` query on ad-hoc packages. Ideally, `go list` would support the `file=` query, eliminating the need for `go/packages` to implement this support. In the meantime, `go/packages` should add support for ad-hoc packages.

/cc @matloob

**Comment by FiloSottile** [comment]
@stamblerre Please apply NeedsInvestigation/NeedsFix and a milestone when opening issues. You are in a better position than the OSP team to triage :)

**Comment by stamblerre** [comment]
Sorry, thank you for doing it. I usually try to, but forgot because, for once, it was not my issue to solve :smile:
