### ISSUE TITLE
x/tools/gopls: jsonrpc worker goroutine can get stuck

### ISSUE THREAD

**Issue by muirrn** [golang/go#32589]
My gopls got stuck with "no room in queue" errors because the "workspace/configuration" call gopls made to Emacs never got a response. Emacs didn't respond because I had an error in my config, but it seems like we either need a timeout or more goroutines to avoid getting stuck in the case the server doesn't respond properly.

/cc @ianthehat

**Comment by myitcv** [comment]
I'm not sure I'm a huge fan of timeouts.... they tend to mask underlying, bigger problems.

The "no room in queue" errors are a derivative error of the underlying in this case, correct?

**Comment by muirrn** [comment]
Yes, I got "no room in queue" because the worker goroutine was not reading off queue, so the queue filled up.
