### ISSUE TITLE
x/tools/cmd/godoc: ?m=all not showing t and T

### ISSUE THREAD

**Issue by gertcuykens** [golang/go#32588]
andrey mirtchovski https://groups.google.com/d/msg/golang-nuts/yurCBIjtVq8/ULFl7jwIBgAJ

collection is not an exported type: 
https://github.com/couchbase/moss/blob/master/collection.go#L24 

the ?m=all parameter should enable you to see those, but it's not 
working for me https://godoc.org/github.com/couchbase/moss?m=all. Perhaps because "collection" and  "Collection" are not considered by godoc to be two different things?

**Comment by mirtchovski** [comment]
i created the simplest package possible and am not seeing the problem locally with go 1.12.5:

```
package t

type T struct {
}

func (t *T) Do() {
}

type t struct {
}

func (t *t) Do() {
}
```

attached is a screencap from local godoc:

<img width="246" alt="Screen Shot 2019-06-12 at 4 22 13 PM" src="https://user-images.githubusercontent.com/2047078/59390389-57a5b380-8d2e-11e9-93c7-1190ad1f8e9b.png">

**Comment by agnivade** [comment]
It indeed shows up `collection`, but after all the exported types are shown. So you have to scroll down a bit.  I think this is by design as people might not want to mix exported and unexported types. If you think this should be changed, please feel free to open a separate proposal. But there is no bug here.

**Comment by mirtchovski** [comment]
Can you please post a screenshot, preferably capturing the URL at the top?

I'm failing to see `ResetStackDirtyTop` which is a method on (*collection) but not on (*Collection)

**Comment by agnivade** [comment]
![godoc-collection](https://user-images.githubusercontent.com/1774000/59403061-c3cff800-8dbe-11e9-92f0-12966c0c7431.png)

**Comment by agnivade** [comment]
URL is http://localhost:6060/pkg/github.com/couchbase/moss/?m=all

**Comment by dmitshur** [comment]
The `?m=all` parameter is only supported by `x/tools/cmd/godoc` right now. The original issue linked to godoc.org, which is another website that does not support the `?m=all` query parameter.

**Comment by mirtchovski** [comment]
thank you. this clears up my confusion.
