### ISSUE TITLE
cmd/doc: add option to suppress showing package docs

### ISSUE THREAD

**Issue by gertcuykens** [golang/go#32597]
A `go doc -tree` output please would be awesome.

Currently there is no way for go doc to output a clean single line separated definitions of types, functions, vars and consts.

For example `go doc | fzf` the intro of a package is scrambled between the output for a fuzzy finder 
![image](https://user-images.githubusercontent.com/863731/59416311-6e4b1980-8dc5-11e9-8364-a63b9264fadd.png)

**Comment by gertcuykens** [comment]
Yep this is the output of go doc
```
package moss // import "."

Package moss stands for "memory-oriented sorted segments", and provides a
data structure that manages an ordered Collection of key-val entries, with
optional persistence.

The design is similar to a simplified LSM tree (log structured merge tree),
but is more like a "LSM array", in that a stack of immutable, sorted key-val
....

var StorePageSize = 4096
var StorePrefix = "data-"
var StoreSuffix = ".moss"
var StoreVersion = uint32(4)
func ByteSliceToUint64Slice(in []byte) ([]uint64, error)
func FormatFName(seq int64) string
func HeaderLength() uint64
func OpenStoreCollection(dir string, options StoreOptions, persistOptions StorePersistOptions) (*Store, Collection, error)
func ParseFNameSeq(fname string) (int64, error)
func ToOsFile(f File) *os.File
func Uint64SliceToByteSlice(in []uint64) ([]byte, error)
type Batch interface{ ... }
type BatchOptions struct{ ... }
type Collection interface{ ... }
    func NewCollection(options CollectionOptions) (Collection, error)
type CollectionOptions struct{ ... }
type CollectionStats struct{ ... }
type CompactionConcern int
    const CompactionDisable CompactionConcern = iota ...
type EntryEx struct{ ... }
type Event struct{ ... }
type EventKind int
    const EventKindCloseStart EventKind = 1 + iota ...
type File interface{ ... }
type FileRef struct{ ... }
type Footer struct{ ... }
    func ReadFooter(options *StoreOptions, file File) (*Footer, error)
    func ScanFooter(options *StoreOptions, fref *FileRef, fileName string, pos int64) (*Footer, error)
type Header struct{ ... }
...
```
If go doc -tree would only ouput this then a fuzzy finder will not scramble intro lines in the result 
```
var StorePageSize = 4096
var StorePrefix = "data-"
var StoreSuffix = ".moss"
var StoreVersion = uint32(4)
func ByteSliceToUint64Slice(in []byte) ([]uint64, error)
func FormatFName(seq int64) string
func HeaderLength() uint64
func OpenStoreCollection(dir string, options StoreOptions, persistOptions StorePersistOptions) (*Store, Collection, error)
func ParseFNameSeq(fname string) (int64, error)
func ToOsFile(f File) *os.File
func Uint64SliceToByteSlice(in []uint64) ([]byte, error)
type Batch interface{ ... }
type BatchOptions struct{ ... }
type Collection interface{ ... }
    func NewCollection(options CollectionOptions) (Collection, error)
type CollectionOptions struct{ ... }
type CollectionStats struct{ ... }
type CompactionConcern int
    const CompactionDisable CompactionConcern = iota ...
type EntryEx struct{ ... }
type Event struct{ ... }
type EventKind int
    const EventKindCloseStart EventKind = 1 + iota ...
type File interface{ ... }
type FileRef struct{ ... }
type Footer struct{ ... }
    func ReadFooter(options *StoreOptions, file File) (*Footer, error)
    func ScanFooter(options *StoreOptions, fref *FileRef, fileName string, pos int64) (*Footer, error)
type Header struct{ ... }
...
```
For me this is much fuzzy finder friendly because no scrambled intro text is ever in the search result
```
gert@gert ~/Desktop/moss:master> go doc > index.txt
gert@gert ~/Desktop/moss:master> remove intro from index.txt manually then do
gert@gert ~/Desktop/moss:master> cat index.txt | fzf
```
![image](https://user-images.githubusercontent.com/863731/59434725-69e62700-8dec-11e9-8775-1a080e18747f.png)

Notice the difference between the first screenshot and this one for the same search

**Comment by agnivade** [comment]
I see. I thought -tree meant a tree like structure. So IIUC, you just do not want the package doc(or rather any sort of docs) to appear for fuzzy finder to work properly. I will update the title appropriately and leave it to @robpike to make a call.

**Comment by robpike** [comment]
I have no problem with the idea, but the flag name chosen in the CL (go doc -sym) is both misleading (all go doc does is show symbols) and poorly explained. Hoping a better suggestion will come.

Once that's sorted, the CL will need to update the go command as well.

**Comment by robpike** [comment]
The idea you're looking for is "short" or "compact" or "simple", not "symbol".

**Comment by gertcuykens** [comment]
I agree :) , what about ```flagSet.BoolVar(&short, "short", false, "short summary of symbols without package docs")```

**Comment by robpike** [comment]
It's not just package docs, though, is it? Other things are suppressed too, are they not? Or at least the intent should be. I think what you're trying to get (we could be on different paths here) is a way to get just a list of the symbols with a concise summary of their types, free of documentation.

**Comment by gertcuykens** [comment]
Correct, a one line representation for each symbol

**Comment by robpike** [comment]
This is looking good.
