### ISSUE TITLE
Fetch info of multiple struct dynamically in loop

### ISSUE THREAD

**Issue by amitu101** [golang/go#32616]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12
</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 18 MVC architecture 

### What did you do?
I need to fetch collection list and each collection's keys from mongodb and compare those key in loop with struct which has same name as collection name

Fetched collection list from mongodb
<code>names, err := db.CollectionNames()</code>

Loop over collection list and fetched each collection's key list
Example collection chats has key Id and Value
Now in the same loop I tried to fetch fields of struct (collection name is similar to struct name)
Here I am getting error 

```
/****struct in model****/
type chats struct {
	Id  string
	Value string
}
/****struct in model****/
/****Handler****/
names, err := db.CollectionNames()
for _, name := range names {  // name is similar to struct name
		a := &models.name{}  //here getting error as name is dynamic
		fmt.Println(name)
}
```

**Comment by FiloSottile** [comment]
In Go, struct fields are not meant to be dynamic. You might be able to solve this with reflection, but there is probably a simpler and more idiomatic solution in changing the approach you are taking.

The golang/go issue tracker is used to develop the Go project, so you'll get more help with questions about using the Go language through the resources listed at https://golang.org/wiki/Questions.
