### ISSUE TITLE
ugly potato image

### ISSUE THREAD

**Issue by pjebs** [golang/go#32615]
I downloaded Go 1.12 macos installer from official site.

To my surprise (I almost vomited), I saw an ugly potato.

![Screen Shot 2019-06-14 at 1 50 36 pm](https://user-images.githubusercontent.com/5377970/59482283-97de7080-8eab-11e9-88da-bc8a948df0c9.png)

Maybe this should be fixed before the next release.

**Comment by edwardhutchison** [comment]
It appears to have it's arms raised like a 1980's zombie, this could truly be the end of the world where the potatoes break forth from their subterranean prison to wreak havoc upon the unsuspecting denizens of mid-west USA.

**Comment by ericlagergren** [comment]
If you don’t take that back the ~~ugly~~ cute toothed potato is gonna haunt you in your sleep.
