### ISSUE TITLE
go1.1rc2 does not fix internal linking issue 

### ISSUE THREAD

**Issue by BhuvanRK** [golang/go#32622]
https://github.com/golang/go/issues/27200

### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by ALTree** [comment]
I've edited back the new-issue template in your post. Please fill the requested informations.

**Comment by BhuvanRK** [comment]
What version of Go are you using (go version)?
go 1.11rc1

Does this issue reproduce with the latest release?
Yes

What operating system and processor architecture are you using (go env)?
go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/bramkumar/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/bramkumar/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vt/6qhm_2156k10_l3g8g_nzxcm0000gp/T/go-build940353526=/tmp/go-build -gno-record-gcc-switches -fno-common"

What did you do?

$ pwd
/Users/bramkumar/go/src/github.com/WeConnect/identity-subjects

$ cat cmd/subjects/subjects.go
package main

import (
"database/sql"
"io"
"net"
"net/http"
"strings"
"github.com/golang/protobuf/ptypes/empty"
server "github.com/weconnect/identity-subjects/internal"
log "github.com/sirupsen/logrus"
)

$ pwd
/Users/bramkumar/go/src/github.com/WeConnect/identity-subjects/internal

$ cat server.go
package internal

import (
"context"
)

What did you expect to see?
Compilation success

What did you see instead?

$go build cmd/subjects/subjects.go
cmd/subjects/subjects.go:10:2: use of internal package github.com/weconnect/identity-subjects/internal not allowed

Its the same for me with go1.11rc2

$ go1.11rc2 build cmd/subjects/subjects.go
cmd/subjects/subjects.go:10:2: use of internal package github.com/weconnect/identity-subjects/internal not allowed

**Comment by tmthrgd** [comment]
The internal package is imported as `github.com/weconnect/identity-subjects/internal` (note lower case), but it’s imported by the main package which is located in `$GOPATH/src/github.com/WeConnect/identity-subjects` (note that WeConnect is capitalised). I think that’s your problem here.

**Comment by agnivade** [comment]
What @tmthrgd said. package paths are case sensitive.
