### ISSUE TITLE
cmd/compile: multiple ineffective assignments

### ISSUE THREAD

**Issue by marigonzes** [golang/go#32624]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version devel +73abea3 Thu Jun 13 02:49:03 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What did you do?
I compiled the following function and inspected the assembly code generated (https://godbolt.org/z/-7YwuJ):
```go
func f() (ret int) {
    return func() int {
        ret = -1
        return 1
    }()
}
```

### What did you expect to see?
I expected function `f` to be compiled to a simple move+return.

### What did you see instead?
Instead, I see 3 moves before the return.

**Comment by randall77** [comment]
Yep.
Might be related to #14762.

See cmd/compile/internal/gc/ssa.go:exit, the TODO about PPARAMOUTs.
Also cmd/compile/internal/gc/ssa.go:addNamedValue

**Comment by marigonzes** [comment]
Something else I found while playing with this function is that if I assign to `ret` before the return, these assignments are not optimized away, as you can see in https://godbolt.org/z/wuO5-j.
This doesn't happen without the anonymous function call.

**Comment by marigonzes** [comment]
These issues seem to be a regression caused by 0029cd4.

**Comment by marigonzes** [comment]
No longer reproduces
