### ISSUE TITLE
cmd/go: can't load package when GOPATH is under GOROOT

### ISSUE THREAD

**Issue by Helflym** [golang/go#32621]
The go command seems to have trouble parsing the package name when it's under $GOROOT/src. 
The error is obvious with gccgo (so also with version 1.12). However, I'm not sure if the error from TIP is related or not. 

```
$ go env
GOPATH="/opt/freeware/src/packages/BUILD/go-path"
GOROOT="/opt/freeware"
$ cd $GOPATH/src/golang.org/x/sys/unix/

WITH GCCGO
$ go.gcc version  
go version go1.12.2 gccgo (GCC) 9.1.0 aix/ppc64
$ go.gcc build 
can't load package: package packages/BUILD/go-path/src/golang.org/x/sys/unix: cannot find package "packages/BUILD/go-path/src/golang.org/x/sys/unix" in any of:
        /opt/freeware/src/packages/BUILD/go-path/src/golang.org/x/sys/unix (from $GOROOT)
        /opt/freeware/src/packages/BUILD/go-path/src/packages/BUILD/go-path/src/golang.org/x/sys/unix (from $GOPATH)

WITH GO 1.12 
$ go version
go version go1.12.5 aix/ppc64
$ go.golang build
can't load package: package packages/BUILD/go-path/src/golang.org/x/sys/unix: code in directory /opt/freeware/src/packages/BUILD/go-path/src/golang.org/x/sys/unix expects import "golang.org/x/sys/unix"

WITH TIP
$ go version
go version devel +d2f0628430 Thu Jun 13 09:51:55 2019 -0500 aix/ppc64
$ go build
go: inconsistent vendoring in /opt/freeware/src/packages/BUILD/go-path/src/golang.org/x/sys:
        go.mod requires golang.org/x/sys  but vendor/modules.txt does not include it.
        run 'go mod tidy; go mod vendor' to sync
```

This alos happen on Fedora 30 (at least with gccgo). 
I do agree that having GOPATH under GOROOT isn't the best idea ever. But this is sometime the case on AIX (and maybe Fedora), because default GOROOT is "/opt/freeware" and the RPM are built under "/opt/freeware/src/packages/BUILD". 

Therefore, is it a true bug in go command or a problem related to how Go RPMs are delivered ?

**Comment by FiloSottile** [comment]
Setting GOPATH within GOROOT is definitely not a supported configuration, but maybe we should generate a better error for it.

/cc @jayconrod

**Comment by bcmills** [comment]
A GOROOT of `/opt/freeware` seems like a problem in general. GOROOT has a lot of really generic directories such as `src`, `test`, and `misc` that are likely to conflict with other programs.

In particular, if we were to add a `packages` package to the standard library, then a GOROOT of `/opt/freeware` would place that package's source at `/opt/freeware/src/packages`.

**Comment by bcmills** [comment]
At any rate, we do have a similar existing diagnostic, if someone wants to expand it:
https://github.com/golang/go/blob/82cf8bca9cf20297bc0edf481cc530c9b3f4bf1e/src/cmd/go/main.go#L106-L111

**Comment by Helflym** [comment]
GOROOT is set to /opt/freeware only with gccgo. And I think this is because we are using `--prefix="/opt/freeware"` when building gcc in general. 
Maybe @ianlancetaylor, you're aware of such problems in a different OS ?

**Comment by Helflym** [comment]
GOROOT is set to `/opt/freeware` only with gccgo. When building the gcc toolchain, we're specifying `--prefix=/opt/freeware` therefore according to https://github.com/golang/gofrontend/blob/master/libgo/Makefile.am#L55, the defaultGoroot will be `/opt/freeware`. @ianlancetaylor, is there any reason behind this choice or can it be moved freely ? 
Note that with the Golang toolchain, the default GOROOT is set to `/opt/freeware/lib/golang` so there is no problem expect if a user manually change GOROOT and OGPATH.

**Comment by ianlancetaylor** [comment]
The gccgo default for `GOROOT` is definitely problematic.  See https://gcc.gnu.org/PR89171.  I've been intending to take a look at it before the next GCC release.

**Comment by qbradq** [comment]
I am unable to reproduce the issue. The only way I can convince go to not find something under GOPATH is to reference it incorrectly. Even when GOPATH is a sub-directory of GOROOT. Can you post the code or at least the `import` block @Helflym ?

**Comment by Helflym** [comment]
You're right, my error occurs only because `GOPATH` is a sub-directory of `$GOROOT/src` (and not simply `$GOROOT`). It's very unlikely that it'll ever occur with Golang as `GOROOT` as a true meaning. However, with the current gccgo, `GOROOT` is more a placeholder AFAIK.   
```
$ go env 
GOROOT="/tmp/go-root"
GOPATH="/tmp/go-root/src/go-path"
$ cd /tmp/go-root/src/go-path/src/golang.org/x/sys/unix 
$ GO111MODULE=off go build
can't load package: package go-path/src/golang.org/x/sys/unix: code in directory /tmp/go-root/src/go-path/src/golang.org/x/sys/unix expects import "golang.org/x/sys/unix"
```
GO111MODULE=off is just to make a more explicit error.

**Comment by qbradq** [comment]
@Helflym I still have not be able to reproduce this. Can you at least post the `import` block of your main go file? I have tried all the combinations I can think of as far as file and import structure to cause this, but I get no errors.

```
qbradq@qbradq-AB350-Gaming:~/golang/src/go-path/src/golang.org/x/sys/unix$ set | grep GO
GOPATH=/home/qbradq/golang/src/go-path
GOROOT=/home/qbradq/golang
qbradq@qbradq-AB350-Gaming:~/golang/src/go-path/src/golang.org/x/sys/unix$ cat main.go
package main

import "golang.org/x/sys/unix/sub"

func main() {
	sub.SayHello()
}
qbradq@qbradq-AB350-Gaming:~/golang/src/go-path/src/golang.org/x/sys/unix$ cat sub/lib.go
package sub

import "fmt"

// SayHello says hello
func SayHello() {
	fmt.Println("Hello, #32621!")
}
qbradq@qbradq-AB350-Gaming:~/golang/src/go-path/src/golang.org/x/sys/unix$ GO111MODULE=off $GOROOT/bin/go build
qbradq@qbradq-AB350-Gaming:~/golang/src/go-path/src/golang.org/x/sys/unix$ ./unix
Hello, #32621!

```

**Comment by Helflym** [comment]
I was using the whole `x/sys/unix` package (https://github.com/golang/sys) not a simple `main.go` and its sub package. 
But indeed, it does work with your simple example. It could be interesting to know why it does with this simple package but it doesn't with a complex package like `x/sys/unix`. 
Anyway, here is the imports of `x/sys/unix`, 
```
$ go list -f '{{ .Imports }}'
[bytes encoding/binary net runtime sort strings sync syscall time unsafe]
```

**Comment by qbradq** [comment]
@Helflym Thank you the patience :) I understand now that you are trying to build the golang.org/x/sys/unix package. I was able to reproduce the issue when building this package. I am continuing analysis now.

**Comment by FiloSottile** [comment]
Let's just detect it early, print a helpful error, and exit.

**Comment by qbradq** [comment]
@FiloSottile We can't exit. The go build process and as well as some internal test cases change GOPATH to be a subdirectory of GOROOT and expects it to work. So should it just print a helpful warning?

**Comment by FiloSottile** [comment]
Which part of the build process, and what tests? It seems weird to rely on an unsupported and apparently broken configuration.

**Comment by qbradq** [comment]
```
qbradq@qbradq-AB350-Gaming:~/godev/goroot/src$ ./all.bash
Building Go cmd/dist using /usr/lib/go-1.10.
Building Go toolchain1 using /usr/lib/go-1.10.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
go: GOPATH (/home/qbradq/godev/goroot/pkg/obj/gopath) under GOROOT (/home/qbradq/godev/goroot) is not supported
go tool dist: FAILED: /home/qbradq/godev/goroot/pkg/tool/linux_amd64/go_bootstrap install -gcflags=all= -ldflags=all= -i cmd/asm cmd/cgo cmd/compile cmd/link: exit status 2

```
Building toolchain2 apparently uses this configuration. And I am not sure how we can cleanly avoid it in the tests that rely on files found in the GOPATH.

For an example of a test that uses this, see https://github.com/golang/go/blob/a6a7b148f874b32a34e833893971b471cd9cdeb7/src/cmd/go/go_test.go#L2464

**Comment by bcmills** [comment]
@qbradq, can you get things to work by narrowing the check to `GOROOT/src` rather than all of `GOROOT`?

**Comment by qbradq** [comment]
This was going to be my next try :) Unfortunately I broke my hand. That slowed me down. The Go build and test cases are all going to be under `$GOROOT/src` though, so it doesn't help.

**Comment by Pranavvks** [comment]
Greetings.I am running Linux I am facing a similar issue wherein i get a error message that cannot load package and cannot find package. I have tried to use an external package main package works fine. I am a newbie to Linux and Programming in general any help would be highly appreciated. 
Thanks in advance.

**Comment by ianlancetaylor** [comment]
@Pranavvks Please don't ask use an existing issue to ask questions about a new problem using Go.  Please instead use a forum.  See https://golang.org/wiki/Questions.  Thanks.

**Comment by sarinkejohn** [comment]
golang_org/x/net/route: package golang_org/x/net/route is not in GOROOT (/usr/local/bin/go/src/golang_org/x/net/route)

**Comment by davecheney** [comment]
Times out
