### ISSUE TITLE
Unable to reconnect a bluetooth

### ISSUE THREAD

**Issue by weixingsun** [golang/go#32633]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12.5
</pre>

### Does this issue reproduce with the latest release?
no testing on latest 1.12.6, but done on both 1.7.4 & 1.12.5

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="arm"
GOBIN=""
GOCACHE="/home/pi/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pi/go"
GOPROXY=""
GORACE=""
GOROOT="/home/pi/go"
GOTMPDIR=""
GOTOOLDIR="/home/pi/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build293999460=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Implemented a Bluetooth server side, codes pasted as below

### What did you expect to see?
Connection resumed  after retrying, 
without restarting the whole program

### What did you see instead?
The existing connection keep seeing bad FD error, until I restart the whole process:
Waiting... fd=-1  sa=<nil>2019/06/15 18:05:57 file descriptor in bad state
Waiting... fd=-1  sa=<nil>2019/06/15 18:06:02 file descriptor in bad state
....

Code: ----------------------------------------------------------------------------------

package main

import (
	"fmt"
	"log"
	"bytes"
	"strings"
	"syscall"
	"time"
	"golang.org/x/sys/unix"
)

func init_socket() int {
    fd, _ := unix.Socket(syscall.AF_BLUETOOTH, syscall.SOCK_STREAM, unix.BTPROTO_RFCOMM)
    addr := &unix.SockaddrRFCOMM{
        Channel: 1,
        Addr:    [6]uint8{0,0,0,0,0,0},
    }
    _ = unix.Bind(fd, addr)
    _ = unix.Listen(fd,1)
    nfd, sa, err := unix.Accept(fd)
    if err != nil {
        fmt.Printf("Waiting... fd=%v  sa=%v", nfd, sa)
        log.Println(err)
        time.Sleep(5*time.Second)
        return 0
    }else{
        //print client mac addr
        //fmt.Printf("Conn addr=%v fd=%d\n", sa.(*unix.SockaddrRFCOMM).Addr, nfd)
        return nfd
    }
}
func main() {
    buf := make([]byte, 30)
bt_init:
    nfd := init_socket()
    if nfd == 0 {
        goto bt_init
    }
    for {
        _, err:= unix.Read(nfd, buf)
        if err != nil {
            //log.Println(err)
            fmt.Println("error when reading bt, this error occurred when connection lost")
            time.Sleep(2*time.Second)
            goto bt_init
        }
        fmt.Println("Connected")
        n := bytes.Index(buf, []byte{0})
        s0 := string(buf[:n])
        fmt.Printf("Received: %v chars: %s\n", len(s), s )
    }
}

**Comment by beoran** [comment]
The fd is -1 due to some error. Please change the unix.Socket call and also get the error and check that. It should become more clear then what is going on. It's better to avoid  ignoring errors with _, check them in stead.

**Comment by mdlayher** [comment]
This doesn't appear to be a Go issue, so closing. Please reach out for help at one of the links listed here: https://github.com/golang/go/wiki/Questions.

**Comment by weixingsun** [comment]
@beoran 
Thanks for taking time to look at my code, the err is nil from unix.Socket statement, 
I changed the code section, 

error when reading bt
Init BT socket sucessfully
Bind BT socket sucessfully
Listen BT socket sucessfully
Waiting... fd=-1  sa=<nil>2019/06/15 22:51:37 file descriptor in bad state

**Comment by weixingsun** [comment]
Well, if you think this is not a Go issue, that's fine
Thanks for closing
