### ISSUE TITLE
x/tools/gopls: type checking deadlock

### ISSUE THREAD

**Issue by muirrn** [golang/go#32638]
I managed to hit a type checking deadlock. All goroutines involved were waiting on `<-e.ready` in `getPkg` in lsp/cache/check.go, which suggests some sort of impossible circular dependency. In the debugger I found the below getPkg call chains from each goroutine:

```
go/build <- golang.org/x/tools/go/analysis/passes/asmdecl
go/doc <- go/build <- golang.org/x/tools/imports
encoding/json <- golang.org/x/tools/go/packages
net/url <- crypto/x509 <- crypto/tls <- net/http/httptrace <- net/http <- encoding/json <- golang.org/x/tools/internal/span
encoding/json <- net/url <- text/template <- go/doc
```

It is a deadlock, but the `encoding/json <- net/url` edge jumped out as not quite right until I noticed that "net/url" imports "encoding/json" in its test. So, due to the package variant issue, we are hitting circular dependencies. In particular, in this case when "text/template" imports "net/url", we ended up importing the test variant of "net/url" that also has an import for "encoding/json".

Once the variant issue is resolved so that importer.Import only ever imports the non-test variant, this issue should be resolved as well.

/cc @stamblerre @ianthehat

**Comment by stamblerre** [comment]
This should be resolved as of https://golang.org/cl/183628. Closing.
