### ISSUE TITLE
net/http: DefaultTransport documentation should describe HTTPS_PROXY

### ISSUE THREAD

**Issue by HouzuoGuo** [golang/go#32649]
### What version of Go are you using (`go version`)?

<pre>
go version go1.12.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Affirmative.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/howard/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/howard/gopath"
GOPROXY=""
GORACE=""
GOROOT="/home/howard/go"
GOTMPDIR=""
GOTOOLDIR="/home/howard/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build043222332=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

In https://golang.org/pkg/net/http/#RoundTripper, the online manual explains the following for RoundTripper:

> DefaultTransport is the default implementation of Transport and is used by DefaultClient. It establishes network connections as needed and caches them for reuse by subsequent calls. It uses HTTP proxies as directed by the $HTTP_PROXY and $NO_PROXY (or $http_proxy and $no_proxy) environment variables.

Although DefaultTransport uses proxy settings from system environment via [ProxyFromEnvironment](https://golang.org/pkg/net/http/#ProxyFromEnvironment), which not even recognises HTTP proxy, but HTTPS proxy also:

> ProxyFromEnvironment returns the URL of the proxy to use for a given request, as indicated by the environment variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY (or the lowercase versions thereof). HTTPS_PROXY takes precedence over HTTP_PROXY for https requests.

`DefaultTransport` indeed behaves correctly and recognises both HTTPS and HTTP proxy settings from system environment. Therefore, please elaborate about the support of HTTPS proxy in the documentation for `DefaultTransport`.

Thanks!

**Comment by katiehockman** [comment]
Please let me know if I am understanding this issue. To summarize:
The documentation for `DefaultTransport` says that it supports HTTP_PROXY and NO_PROXY, but does not mention that it supports HTTPS_PROXY, and your suggestion is that it should describe this additional environment variable. Correct?

**Comment by HouzuoGuo** [comment]
Thanks @katiehockman and yes indeed.

**Comment by narqo** [comment]
@HouzuoGuo with the changes from https://go.dev/cl/430135 is there anything to improve for the issue?

See the tip's documentation for the reference https://pkg.go.dev/net/http@master#DefaultTransport

**Comment by HouzuoGuo** [comment]
That's amazing - thank you!
