### ISSUE TITLE
Switch bug

### ISSUE THREAD

**Issue by luthfikw** [golang/go#32647]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

In reflect.Kind case switch not working properly
i write example code switch statement [code](https://play.golang.org/p/kOplHDBk8Df)
there program exited without print something

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/gearintellix/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/gearintellix/Sites/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fw/zkl81fnd2d966l2_jvddn0gw0000gn/T/go-build252307363=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you expect to see?

that must be

```bash
OK 50
```

### What did you see instead?

nothing

**Comment by ALTree** [comment]
In Go, the switch statement doesn't have automatic fallthrough like in C. See: https://tour.golang.org/flowcontrol/9

In your example, `v` is an `Int` but your `Int` case in the switch is empty, so nothing is printed. Do this:

```
switch val.Kind() {
	case reflect.Int:
		fmt.Println("OK", v)
```

and you'll see "OK" printed.

Closing here, since this is not  Go bug.
