### ISSUE TITLE
cmd/go: go mod init . creates a module called .

### ISSUE THREAD

**Issue by davecheney** [golang/go#32644]
### What version of Go are you using (`go version`)?

<pre>
% go version
go version devel +b388d6868f Thu Jun 13 03:58:18 2019 +0000 darwin/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```
(~/src/d) % go mod init .
go: creating new go.mod: module .
(~/src/d) % ls
go.mod  main.go
(~/src/d) % cat go.mod 
module .

go 1.13
```

### What did you expect to see?

My gopath is set to `~/src`, tf. the modules name should be `d`.

### What did you see instead?

The module is called `.` which is not valid
```
(~/src/d) % go test
build _/Users/dfc/src/d: cannot find module for path _/Users/dfc/src/d
(~/src/d) % 
```

**Comment by cuonglm** [comment]
@davecheney I think expected should be an error, `.` is not a valid module path (emphasis by me):

```
$ go help mod init
usage: go mod init [module]
```

> Init initializes and writes a new go.mod to the current directory,
in effect creating a new module rooted at the current directory.
The file go.mod must not already exist.
If possible, init will guess the module path from import comments
(see 'go help importpath') or from version control configuration.
To override this guess, supply the **module path** as an argument.
