### ISSUE TITLE
Pure function returns different values for the same input under different conditions.

### ISSUE THREAD

**Issue by SMemsky** [golang/go#32642]
#### What did you do?
Found a bug in a huge private codebase and ended up reducing it to just two functions.

Here is a case where calling function produces conflicted results based on how it is called (see line 25 where it is called with the same arguments but returns a different result)
https://pastebin.com/XGEZG2TZ
Here is output of `go tool compile -S` for this file:
https://pastebin.com/XeFtTSyK

Here is a slightly different. I moved `x < 0` comparison which in theory should not change anything, but now code works as it is supposed to. (i.e. not outputting anything)
https://pastebin.com/BCJKDkfX
Here is output of `go tool compile -S` for this working file:
https://pastebin.com/Vnq5bDLK

And here is the last version that removes check for `y >= 1` (which in that case should be always false anyways) and it generates a different output, also unexpected.
https://pastebin.com/FukvAcQ5
And its asm code:
https://pastebin.com/hKmXzdhp

#### What did you expect to see?
Same output (i.e. no output at all) for all three versions.

#### What did you see instead?
Different output of a pure function with the same values as arguments

#### Does this issue reproduce with the latest release (go1.12.6)?
No. And since it might have been fixed.

#### System details
Note: go was installed a while ago with `go1.11.windows-amd64.msi` from https://golang.org/dl/
At the time it was the latest release.
```
go version go1.11 windows/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="C:\Users\User\AppData\Local\go-build"
GOEXE=".exe"
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="windows"
GOOS="windows"
GOPATH="C:\Users\User\go"
GOPROXY=""
GORACE=""
GOROOT="C:\Go"
GOTMPDIR=""
GOTOOLDIR="C:\Go\pkg\tool\windows_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version go1.11 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.11
gdb --version: GNU gdb (GDB) 8.1
```

As I can't reproduce this issue on a latest Go version, I think that this issue is probably already fixed and I'm just wasting your precious time, but I thought it is still worth sharing what I got. I hope for your understanding :)

**Comment by mvdan** [comment]
I think it's not worth keeping this issue open, unless the latest 1.11.x version also has this bug. Have you tested that?

**Comment by SMemsky** [comment]
Tested latest 1.11.11 and it does not seem to be affected. I'm closing this issue then 😅
