### ISSUE TITLE
runtime/race: external_cgo_thread passed unexpectedly in TestOutput 

### ISSUE THREAD

**Issue by cuonglm** [golang/go#32653]
https://storage.googleapis.com/go-build-log/63849344/linux-amd64-race_657c252c.log

Output extracted from test log:

```
--- FAIL: TestOutput (9.68s)
    output_test.go:76: failed test case external_cgo_thread, expect:
        ==================
        WARNING: DATA RACE
        Read at 0x[0-9,a-f]+ by main goroutine:
          main\.main\(\)
              .*/main\.go:34 \+0x[0-9,a-f]+
        
        Previous write at 0x[0-9,a-f]+ by goroutine [0-9]:
          main\.goCallback\(\)
              .*/main\.go:27 \+0x[0-9,a-f]+
          main._cgoexpwrap_[0-9a-z]+_goCallback\(\)
              .*_cgo_gotypes\.go:[0-9]+ \+0x[0-9,a-f]+
        
        Goroutine [0-9] \(running\) created at:
          runtime\.newextram\(\)
              .*/runtime/proc.go:[0-9]+ \+0x[0-9,a-f]+
        ==================
        got:
```

**Comment by katiehockman** [comment]
Can you please provide more information on what action we should be taking with this issue report? It looks like this is just from a trybots run in https://go-review.googlesource.com/c/go/+/182561, and that the builders are passing for linux-amd64-race right now.

**Comment by cuonglm** [comment]
@katiehockman it's a data race, so it can happen this time but not that time.

**Comment by bcmills** [comment]
I think #43008 is a duplicate of this issue, but I've added a bit more information there already so I'm going to dup this one to that instead.

**Comment by bcmills** [comment]
Duplicate of #43008
