### ISSUE TITLE
time.Parse: why not literals?

### ISSUE THREAD

**Issue by boumboum** [golang/go#32651]
This is rather a feature request.
New to GO I'm just wondering why go is using this crazy time literal "2006-01-02 15:04:05" instead of "yyyy-mm-dd HH:MM:SS" for parsing time objects? Nobody can remember this date string bu everybody understands immediately the character based pattern.

Also it would be nice to implement to the encoding/json and encoding xml for the  `xml:"mytimestamp,attr"` for DecodeElement like this: `xml:"mytimestamp,attr,format:yyyy-mm-dd HH:MM:SS"`

**Comment by katiehockman** [comment]
For questions about Go, see https://golang.org/wiki/Questions

For a proposal to change encoding/json and encoding/xml, please file a separate issue to describe this proposal.

**Comment by shane-howearth** [comment]
I've just been bitten by the date format, it really does need revisiting.

The bug I had was "2006-1-2" means yyyy-dd-mm but I wanted "2006-2-1" (yyyy-mm-dd)
The fact that I need to represent the desired date in the yyyy mm dd format to clarify to readers should be a big hint as to why I had a bug.

I honestly cannot believe magic numbers is the right way to go. 

Given that Go is 10+ years old, is there a possibility of having a sister representation, so developers can choose whichever they prefer.

**Comment by ianlancetaylor** [comment]
@shane-howearth This issue has been closed for a while.  Commenting here has no effect.

You may be interested in packages like https://pkg.go.dev/github.com/jehiah/go-strftime?tab=doc (I don't know anything about that package other than the docs).

Providing a separate representation in the standard library would require going through the proposal process: https://golang.org/s/proposal.
