### ISSUE TITLE
x/tools/gopls: current directory shouldn't matter

### ISSUE THREAD

**Issue by pierrre** [golang/go#32663]
### What version of Go are you using (`go version`)?
go1.12.6 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pierre/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pierre/go"
GOPROXY=""
GORACE=""
GOROOT="/home/pierre/.gimme/versions/go1.12.6.src"
GOTMPDIR=""
GOTOOLDIR="/home/pierre/.gimme/versions/go1.12.6.src/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build146965632=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I've opened an issue here https://github.com/microsoft/vscode-go/issues/2579
It seems that the current directory while running gopls is very important.
If the current directory is not inside my project, gopls doesn't work.
I guess it's used in order to find the `go.mod` file.

### What did you expect to see?

gopls should run even if the current directory is not inside my project.

### What did you see instead?

See the other Github issue.

**Comment by mattn** [comment]
Do you set `$GO111MODULE` ?

**Comment by pierrre** [comment]
@mattn no, I don't set `$GO111MODULE`.
I'm just using vscode-go.

**Comment by stamblerre** [comment]
@pierrre: In your linked issue, you mentioned working in a directory outside your `$GOPATH`, which leads me to believe that you are using modules. In this case, you will need to open each module root as a separate workspace root. VSCode-Go sends a "rootURI" to `gopls` on initialization, which `gopls` treats as the module root. We hope to improve the user experience for editing multiple modules simultaneously in the future (see #32394).

**Comment by pierrre** [comment]
OK, thank you.
I'm closing this issue, because it's a duplicate of https://github.com/golang/go/issues/32394
