### ISSUE TITLE
x/playground: TryBot fails for playground

### ISSUE THREAD

**Issue by toothrot** [golang/go#32669]
### What version of Go are you using (`go version`)?

<pre>
 linux-amd64 (Go 1.12.x)
 linux-amd64 (Go 1.11.x)
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

(trybot  linux-amd64 (Go 1.12.x) and linux-amd64 (Go 1.11.x))

### What did you do?

Ran TryBot for a x/playground CR for #32606 : https://go-review.googlesource.com/c/playground/+/182180

### What did you expect to see?

```
ok  	golang.org/x/playground	0.070s
```

### What did you see instead?

```
linux-amd64 at 4ce6a8e89668b87dce67e2f55802903d6eb9110a building playground at 798aa1a16276f8ea745637da7b9fd4a8a3e06fec

:: Running /workdir/go/bin/go with args ["/workdir/go/bin/go" "test" "-short" "golang.org/x/playground/..."] and env ["PATH=/workdir/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" "HOSTNAME=buildlet-linux-stretch-rn65a9b55" "DEBIAN_FRONTEND=noninteractive" "HOME=/root" "USER=root" "GO_STAGE0_NET_DELAY=9.1s" "GO_STAGE0_DL_DELAY=200ms" "WORKDIR=/workdir" "GOROOT_BOOTSTRAP=/workdir/go1.4" "GO_BUILDER_NAME=linux-amd64" "GOROOT_BOOTSTRAP=/go1.4" "GO_DISABLE_OUTBOUND_NETWORK=1" "GOROOT=/workdir/go" "GOPATH=/workdir/gopath" "GOPROXY=http://10.240.0.150:30157" "TMPDIR=/workdir/tmp" "GOCACHE=/workdir/gocache"] in dir /workdir/gopath/src/golang.org/x/playground

main.go:13:2: cannot find package "cloud.google.com/go/compute/metadata" in any of:
	/workdir/go/src/cloud.google.com/go/compute/metadata (from $GOROOT)
	/workdir/gopath/src/cloud.google.com/go/compute/metadata (from $GOPATH)
edit.go:14:2: cannot find package "cloud.google.com/go/datastore" in any of:
	/workdir/go/src/cloud.google.com/go/datastore (from $GOROOT)
	/workdir/gopath/src/cloud.google.com/go/datastore (from $GOPATH)
cache.go:11:2: cannot find package "github.com/bradfitz/gomemcache/memcache" in any of:
	/workdir/go/src/github.com/bradfitz/gomemcache/memcache (from $GOROOT)
	/workdir/gopath/src/github.com/bradfitz/gomemcache/memcache (from $GOPATH)
fmt.go:14:2: cannot find package "github.com/rogpeppe/go-internal/modfile" in any of:
	/workdir/go/src/github.com/rogpeppe/go-internal/modfile (from $GOROOT)
	/workdir/gopath/src/github.com/rogpeppe/go-internal/modfile (from $GOPATH)
txtar.go:14:2: cannot find package "github.com/rogpeppe/go-internal/txtar" in any of:
	/workdir/go/src/github.com/rogpeppe/go-internal/txtar (from $GOROOT)
	/workdir/gopath/src/github.com/rogpeppe/go-internal/txtar (from $GOPATH)


Error: tests failed: exit status 1
```

According to the helpful feedback from @dmitshur and @bradfitz, we should be able to force GO111MODULE=yes for x/playground, which should allow this build to succeed. 

Related issues: https://github.com/golang/go/issues/17312, https://github.com/golang/go/issues/30233

**Comment by toothrot** [comment]
Duplicate of #24823

**Comment by dmitshur** [comment]
I'm not sure that it's a duplicate. As I understand, that issue is more about adding playground post-submit builders (i.e., on https://build.golang.org) and testing building the playground image is successful.

Perhaps we can use this issue for the smaller task of just fixing existing trybots so they don't fail.

**Comment by toothrot** [comment]
It would be nice if trybot worked at all, but part of the reason why I feel like it is a duplicate is that many of the important playground tests run as part of the Docker build. I am not sure if there is enough utility of just making the trybot pass without actually fully considering the Docker build case, as it would be a potential false-positive. The trybot could pass with the docker based integration tests failing.
