### ISSUE TITLE
report warning while build with sqlite3 lib.(contains C code using ld tool)

### ISSUE THREAD

**Issue by violin0622** [golang/go#32677]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes,still apears in `go version go1.12.6 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/violin/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/violin/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/violin/Projects/go/src/violin/sq/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9k/g9fr68yx00dfx_9790kccrb80000gn/T/go-build560338982=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

details described in [issue](https://github.com/mattn/go-sqlite3/issues/721)

### What did you expect to see?
no warnings 

### What did you see instead?
```sh
# violin/sq
ld: warning: building for macOS, but linking in object file (/var/folders/9k/g9fr68yx00dfx_9790kccrb80000gn/T/go-link-904695182/go.o) built for
```

**Comment by katiehockman** [comment]
Please let me know if I'm misunderstanding the issue filed, but it looks like this is more of a question than it is a bug that needs to be fixed. For questions about Go, see https://golang.org/wiki/Questions.

**Comment by obynio** [comment]
I had the same problem and found a fix. You need to update the Mojave's Command Line Tools manually using the installer available here https://developer.apple.com/download/more/

Take the most recent corresponding to your macOS version. That was Command Line Tools (macOS 10.14) for Xcode 10.2.1.dmg for me. Tell me if it solved your issue.

**Comment by obynio** [comment]
I had the same problem and found a fix. You need to update the Mojave's Command Line Tools manually using the installer available here https://developer.apple.com/download/more/

Take the most recent corresponding to your macOS version. That was `Command Line Tools (macOS 10.14) for Xcode 10.2.1.dmg` for me. Tell me if it solved your issue.

**Comment by darron** [comment]
Worked for me on Mojave as well.
