### ISSUE TITLE
wiki: CodeReviewComments #NakedReturns

### ISSUE THREAD

**Issue by jkopczyn** [golang/go#32672]
The wiki page states that naked returns are bad but does not give any reasons _why_ they are bad.

In general, I think naked returns are a good idea in almost all cases. Using naked returns consistently enforces a discipline that the variables to be returned will always be correct if the function returns right then. This makes it easier to follow the flow of a function, since Ctrl+F (or equivalent in your text editor) for the return param names will find all the critical pieces.

This may not be correct, but it's enough to warrant a better explanation of why naked returns are bad.

**Comment by andybons** [comment]
The doc never states naked returns are “bad.” It states that explicit return values are preferred for functions longer than a few lines (and that naming return values isn’t always the best for clarity of docs).

@dmitshur’s [comment on the proposal for removing naked returns](https://github.com/golang/go/issues/21291#issuecomment-328731498) sums up one of the reasons why they can be problematic.

How would you like us to improve the wording?

**Comment by jkopczyn** [comment]
>It states that explicit return values are preferred

This is the same thing as saying bare returns are bad. And it gives no
justification for it.

**Comment by jkopczyn** [comment]
The linked comment is a good argument against supporting variables scoped
to sub-functional blocks, but not an argument against bare returns. As he
says himself, he rarely uses them, so he forgot they existed and couldn't
parse a function using them.
Personally, I'd prefer they were mandatory, which would solve his problem
and have the discipline and readability benefits I mentioned in the
top-level issue.

**Comment by andybons** [comment]
Sorry, but we aren't going to make naked returns mandatory. In practice, use of them in large functions causes legitimate readability issues. Our advice is that you can avoid shadowing surprises by being explicit with your return values.

**Comment by jkopczyn** [comment]
If that's true, you could provide examples. I am skeptical you can.
