### ISSUE TITLE
could not launch process: could not find .debug_line section in binary

### ISSUE THREAD

**Issue by a2210** [golang/go#32679]
### What version of Go are you using (`go version`)?
<pre>
$ go 1.12.6

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/careersocially/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/careersocially/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build032173936=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I'm using JetBrains goland ide version 2018.1.6.
when i debug program they got error could not launch process: could not find .debug_line section in binary

**Comment by agnivade** [comment]
Hello @a2210 - we would need more information than this to investigate this. Perhaps this is an issue with JetBrains and not Go ?

Please give us the _exact_ steps from the command line to reproduce this.

**Comment by a2210** [comment]
when i debug program in JetBrains goland ide version 2018.1.6 with go version 1.10.2  is work successfully
but when i change my go version 1.12.6 they got error like   could not launch process: could not find .debug_line section in binary

**Comment by agnivade** [comment]
Please give us the exact steps that is required to reproduce this _without_ JetBrains. i.e. - give us the _exact_ steps that JetBrains is doing, and list it out step by step.

You say "debug program". Which program ? What Go command is JetBrains invoking which is causing this failure ? Please note that this issue tracker is about Go, not JetBrains. So any issue has to be specific to the Go command and toolchain. You need to find out what JetBrains is doing and tell us that.
