### ISSUE TITLE
cmd/go: unable to `go get` @master on linux

### ISSUE THREAD

**Issue by liu-xuewen** [golang/go#32683]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"

</pre></details>

### What did you do?

go get myproject@master 

### What did you expect to see?

myproject's version should be master branch in go.mod

### What did you see instead?
myproject's version is latest tag  in go.mod

**Comment by mvdan** [comment]
Please try with the latest Go 1.12.x version, which is 1.12.6 at the moment. Also, you should provide a way to reproduce the issue with clear steps.
