### ISSUE TITLE
x/crypto: The new crypto package conditional tag for go 1.13 is not supported by glide install

### ISSUE THREAD

**Issue by martinkunc** [golang/go#32687]
### What version of Go are you using (`go version`)?

go version go1.12.4 darwin/amd64

### Does this issue reproduce with the latest release?

I think so

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

<details><summary><code>go env</code> Output</summary><br></details>

glide install

my code is using import like:
"golang.org/x/crypto/ed25519"

If glide is unconstrained, it will fail on installing the version, because it seems it doesnt support `+build go1.13`

### What did you expect to see?
glide passes installation

### What did you see instead?
```
[INFO]	--> Fetching golang.org/x/text
[INFO]	--> Fetching crypto/ed25519
[WARN]	Unable to checkout crypto/ed25519
[ERROR]	Error looking for crypto/ed25519: Cannot detect VCS
[ERROR]	Failed to retrieve a list of dependencies: Error resolving imports
[ERROR]  Glide failed
```
when glide --debug install started it constains:
```
[DEBUG]	Package golang.org/x/crypto/ed25519 imports crypto/ed25519
[DEBUG]	Missing crypto/ed25519. Trying to resolve.
[0;32m[INFO]	[m--> Fetching crypto/ed25519
[0;33m[WARN]	[mUnable to checkout crypto/ed25519
[0;31m[ERROR]	[mError looking for crypto/ed25519: Cannot detect VCS
[DEBUG]	Package golang.org/x/crypto/ed25519 imports golang.org/x/crypto/ed25519/internal/edwards25519
```

It seems that for glide the package broke backward compatibility.

Workaround was to fix package version in glide.yaml to the commit before the change. I used this:
```
- package: golang.org/x/crypto/ed25519
  version: 57b3e21c3d5606066a87e63cfe07ec6b9f0db000
```

**Comment by agnivade** [comment]
Can you clarify what is to be done here from our side on this ? It is perfectly normal for a code to have "// +build go1.13" tag.

**Comment by martinkunc** [comment]
Hi Agnivade, this is primarily glide issue, maybe I should not report this here, but I was thinking maybe it should be backward compatible. Now i checked glide repo and it seems its not supporting these valid tags, so probably we can close. 
Thanks,
The issue I opened for glide: https://github.com/Masterminds/glide/issues/1055

**Comment by ALTree** [comment]
> so probably we can close.

Doing that.
