### ISSUE TITLE
Can't compress the whole string using compress/lzw

### ISSUE THREAD

**Issue by proishan11** [golang/go#32688]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.12.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/proishan11/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/proishan11/go"
GOPROXY=""
GORACE=""
GOROOT="/snap/go/3947"
GOTMPDIR=""
GOTOOLDIR="/snap/go/3947/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build987887418=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
I am trying to compress a HTML string. When I decompress it the output is not
the complete string I am compressing. It is a part of it (prefix precisely).

Here is the code
<code>
<pre>
htmlBytes := []byte(res) 
var buf bytes.Buffer
w := lzw.NewWriter(&buf, lzw.LSB, 8)
_, _ = w.Write(htmlBytes)
w.Close()

r1 := lzw.NewReader(&buf, lzw.LSB, 8)
output := make([]byte, len(htmlBytes))
_, _ = r1.Read(output)

if bytes.Equal(htmlBytes, output) {
	fmt.Println("Compression successful")
}
</pre>
</code>

### What did you expect to see?
After decompressing I should get the same string I am compressing 

### What did you see instead?
A prefix of the input string

**Comment by martisch** [comment]
Can you check for the error returns of Write and Read methods and provide a minimal self contained program (e.g. on https://play.golang.org/) that shows the problem (e.g. what is res in the program above?).

Also try ```output, err := ioutil.ReadAll(r1)``` instead of ```r1.Read(output)```.

**Comment by proishan11** [comment]
Thanks for the help. I used `output, err := ioutil.ReadAll(r1)` and it worked. Do you know the reason why `r1.Read(output)` can't read the complete data?

**Comment by DisposaBoy** [comment]
@proishan11 I learnt this a long time ago so I don't know of a good source of docs to point you to... but the TL;DR is: that's how network/file/io works.

There are no guarantees that a read will return all data, so you should keep calling `.Read()` until it returns an `eof` when you need to read all data. For that [io.Copy](https://golang.org/pkg/io/#Copy) and (to a less extent) [ioutil.ReadAll](https://golang.org/pkg/io/ioutil/#ReadAll) are your friends.

See also [io.ReadFull](https://golang.org/pkg/io/#ReadFull), [io.ReadAtLeast](https://golang.org/pkg/io/#ReadAtLeast), [ioutil.ReadFile](https://golang.org/pkg/io/ioutil/#ReadFile) and the rest of the [io](https://golang.org/pkg/io/) and [ioutil](https://golang.org/pkg/io/ioutil/) packages.

Likewise, there are no guarantees that writing to a file will result in data being written to disk, so you must call `.Flush`, `.Sync` or `.Close` where appropriate (and don't ignore the error return).

**Comment by martisch** [comment]
Some more links to documentation:
https://tour.golang.org/methods/21
https://golang.org/pkg/io/#Reader
