### ISSUE TITLE
malformed mach-o image

### ISSUE THREAD

**Issue by leaxoy** [golang/go#32684]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12.6 & devel version +bc27b64dba

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/lixiaohui/Library/Caches/go-build"
GOENV="/Users/lixiaohui/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/lixiaohui/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/Users/lixiaohui/goroot"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/lixiaohui/goroot/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/lixiaohui/work/v/apiserver/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f3/bpz3qb6s4pd25h95wxtz8xh40000gn/T/go-build829840761=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

go build cmd/server/main.go -o apiserver_server
./apiserver

### What did you expect to see?
Server start correctly

### What did you see instead?
dyld: malformed mach-o image: segment __DWARF has vmsize < filesize
fish: './apiserver_server' terminated by signal SIGABRT (Abort)

**Comment by leaxoy** [comment]
OS version is MacOS 10.15 catalina beta2

**Comment by agnivade** [comment]
Can you provide us with the code ?

Does the error go away with `-ldflags "-w"` ?

**Comment by ALTree** [comment]
This appears to be a dup of #32673. Closing here.

**Comment by leaxoy** [comment]
It looks like.

**Comment by bong0** [comment]
> Can you provide us with the code ?
> 
> Does the error go away with `-ldflags "-w"` ?

for me, the '-w' had to stand **frontmost** in the argument list of '-ldflags'
