### ISSUE TITLE
x/tools/gopls: formatting code with a missing } rewrites function declaration

### ISSUE THREAD

**Issue by dgryski** [golang/go#32698]
Every so often when I'm moving code around, I'll hit save (which formats) but the code I'm working on is incomplete: there's a missing `}`.  Because of this, the function declaration following the one I'm currently working in changes from `func (f *foo) Bar(a,b int,c string) error {` to `(func(f *foo)Bar(a,b,c))()`.  It looks like because gopls thinks it's still in a function and so tries to make that valid code?.

(I'm running VSCode 1.35.1 with 0.11.0 of the Go plugin.  My gopls is from April 2nd, which I'm realizing is a bit out-of-date.  I'll update my gopls and close this if I don't see it still happening..)

**Comment by stamblerre** [comment]
Thanks for reporting! I filed https://github.com/golang/go/issues/33479, which should hopefully lead to the resolution of this problem. 

However, I'm not able to reproduce this in the Go playground: https://play.golang.org/p/_k32CGihMsA. Were you seeing this issue specifically on format or on import organization?

**Comment by dgryski** [comment]
I haven't encountered this error again.  Will reopen if I see it.
