### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by chaitanyav** [golang/go#32694]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12.5
</pre>

### Does this issue reproduce with the latest release?
I have not tried my program with 1.12.6. 

### What operating system and processor architecture are you using (`go env`)?
This is CentOS release 6.8 (Final). 
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pnagato/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pnagato/projects"
GOPROXY=""
GORACE=""
GOROOT="/home/utils/go-1.12.5"
GOTMPDIR=""
GOTOOLDIR="/home/utils/go-1.12.5/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/home/pnagato/projects/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build943411570=/tmp/go-build"
</pre></details>

### What did you see instead?

<pre>
fatal error: unexpected signal during runtime execution
[signal SIGBUS: bus error code=0x2 addr=0xca4b6c pc=0x44be99]

runtime stack:
runtime.throw(0xa27187, 0x2a)
        /home/utils/go-1.12.5/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
        /home/utils/go-1.12.5/src/runtime/signal_unix.go:374 +0x4a9
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc01560c900, 0x0, 0x0, 0x7fffffff, 0xa31308, 0xc0000d1af8, 0x0, ...)
        /home/utils/go-1.12.5/src/runtime/traceback.go:191 +0x359
runtime.copystack(0xc01560c900, 0x4000, 0xf16d00)
        /home/utils/go-1.12.5/src/runtime/stack.go:881 +0x25b
runtime.shrinkstack(0xc01560c900)
        /home/utils/go-1.12.5/src/runtime/stack.go:1137 +0x107
runtime.scanstack(0xc01560c900, 0xc00004a170)
        /home/utils/go-1.12.5/src/runtime/mgcmark.go:690 +0x90
runtime.newstack()

fatal error: unexpected signal during runtime execution
panic during panic
[signal SIGBUS: bus error code=0x2 addr=0xca49fc pc=0x44be99]

runtime stack:
runtime.throw(0xa2717e, 0x2a)
        /home/utils/go-1.12.5/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
        /home/utils/go-1.12.5/src/runtime/signal_unix.go:374 +0x4a9
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc0266f0480, 0x0, 0x0, 0x64, 0x0, 0x0, 0x0, ...)
        /home/utils/go-1.12.5/src/runtime/traceback.go:191 +0x359
runtime.traceback1(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc0266f0480, 0x0)
        /home/utils/go-1.12.5/src/runtime/traceback.go:746 +0xf1
runtime.traceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc0266f0480)
        /home/utils/go-1.12.5/src/runtime/traceback.go:700 +0x52
runtime.tracebackothers(0xc0194de180)
        /home/utils/go-1.12.5/src/runtime/traceback.go:935 +0x28d
runtime.dopanic_m(0xc0194de180, 0x42bd72, 0xc034605738, 0x1)
        /home/utils/go-1.12.5/src/runtime/panic.go:817 +0x2a0
runtime.fatalthrow.func1()
        /home/utils/go-1.12.5/src/runtime/panic.go:672 +0x5f
runtime.fatalthrow()
        /home/utils/go-1.12.5/src/runtime/panic.go:669 +0x57
runtime.throw(0xa2717e, 0x2a)
        /home/utils/go-1.12.5/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
        /home/utils/go-1.12.5/src/runtime/signal_unix.go:374 +0x4a9
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc0266f0480, 0x0, 0x0, 0x7fffffff, 0xa31330, 0xc034605af8, 0x0, ...)
        /home/utils/go-1.12.5/src/runtime/traceback.go:191 +0x359
runtime.copystack(0xc0266f0480, 0x4000, 0xf16d00)
        /home/utils/go-1.12.5/src/runtime/stack.go:881 +0x25b
runtime.shrinkstack(0xc0266f0480)
        /home/utils/go-1.12.5/src/runtime/stack.go:1137 +0x107
runtime.scanstack(0xc0266f0480, 0xc00005f270)
        /home/utils/go-1.12.5/src/runtime/mgcmark.go:690 +0x90
runtime.newstack()
        /home/utils/go-1.12.5/src/runtime/stack.go:1019 +0x367
runtime.morestack()
        /home/utils/go-1.12.5/src/runtime/asm_amd64.s:429 +0x8f
</pre>

**Comment by martisch** [comment]
Please provide a way to reproduce the panic by posting or linking to the code and how it was started.

**Comment by randall77** [comment]
This looks kinda like there's a non-Go function on the Go stack. Are you using assembly?

**Comment by chaitanyav** [comment]
@randall77 I don't have any assembly, only go code.

**Comment by agnivade** [comment]
Hello @chaitanyav - We would need some way to reproduce this error to investigate further. As mentioned above, please provide us with the code that is triggering this if possible.

Otherwise, we need more information on what triggers the crash. Can you pinpoint to a part of the code, which, if removed prevents the crash ? Is the crash deterministic ?

**Comment by chaitanyav** [comment]
This happened only once, on a perpetually running process which spawns goroutines (number of CPU cores on the system) every few minutes. This program has no race conditions.

**Comment by agnivade** [comment]
Thanks. If this has happened only once, and if we don't have any code to reproduce, it will be very hard to investigate this.

If at all you cannot provide us with code, I would request you to run your application with `GOTRACEBACK=system` and report back with the complete trace once you get a crash again.

**Comment by chaitanyav** [comment]
@agnivade Sure will update the issue when I encounter it again.

**Comment by chaitanyav** [comment]
Closing this issue, might be a regression in the code. Have not seen it happen again.
