### ISSUE TITLE
x/mod: semver.Max does more than compute the max

### ISSUE THREAD

**Issue by bcmills** [golang/go#32700]
Currently, [`semver.Max`](https://godoc.org/golang.org/x/mod/semver#Max) canonicalizes its arguments according to `semver.Canonical`:
https://play.golang.org/p/04IP9gNhFWH

To me, the name `Max` does not evoke “canonicalize”, and the action of canonicalizing is potentially fairly destructive: for example, if I have a version with a `+incompatible` build suffix, that version is canonical according to [`module.CanonicalVersion`](https://godoc.org/golang.org/x/mod/module#CanonicalVersion), but will not be preserved by a call to `semver.Max`.

@rsc points out that the canonicalization avoids ambiguity: `v0.1.0+a` and `v0.1.0+b` have the same precedence, so if we call `semver.Max("v0.1.0+a", "v0.1.0+b")` we would otherwise have to pick one arbitrarily, and [semver.org](https://semver.org/#spec-item-10) says “Build metadata SHOULD be ignored when determining version precedence.”

Instead, I propose that `Max` should always return one of its arguments. Build metadata must comprise only the usual dot-separated ASCII identifiers, so if we have two versions with equal precedence it seems to me that we could break the tie using the usual rule for comparing pre-release suffixes.

CC @jayconrod @hyangah

**Comment by dsymonds** [comment]
Alternatively, replace Max with Less, which just returns a bool. It is trivial to wrap to get the existing Max semantics in existing code, and avoids the issue by not even trying to return one arg or the other.

**Comment by bcmills** [comment]
@dsymonds, we already have `Compare`, which is even more ergonomic than `Less` in general. But it's true that we could just remove `Max` instead of providing a version of it with dubious semantics.

**Comment by dsymonds** [comment]
Oh, I overlooked Compare. Yeah, Max seems extra pointless; callers who care can use Compare, then if they actually care about canonicalisation they can use Canonical explicitly.

**Comment by bcmills** [comment]
`Max` was deprecated in [CL 269357](https://golang.org/cl/269357). At this point I don't see a pressing need to delete it, so I don't think there is anything left to do for this issue.
