### ISSUE TITLE
internal/lsp: prepareSupport must be set for RenameOptions to be valid

### ISSUE THREAD

**Issue by ianthehat** [golang/go#32703]
Kevin Smith reported on slack
vim-lsp is having trouble parsing the renameProvider capability because it isn't a boolean. The lsp spec seems to indicate renameProvider should be a boolean unless prepareSupport is true. Right now, gopls always returns RenameOptions (instead of a boolean) with prepareSupport: false

Our generated struct does not support renameProvider not being RenameOptions, but it should be safe to set prepareSupport to true

**Comment by kevinms** [comment]
> Our generated struct does not support renameProvider not being RenameOptions, but it should be safe to set prepareSupport to true

I think "prepareSupport" is something the client sends to the server. So the server would need to respond with a boolean if the client says prepareSupport is false.

Excerpt from LSP spec:
```
	/**
	 * The server provides rename support. RenameOptions may only be
	 * specified if the client states that it supports
	 * `prepareSupport` in its initial `initialize` request.
	 */
	renameProvider?: boolean | RenameOptions;
```

Disclaimer: I barely know anything about LSP or vim-lsp's client implementation, so sorry if I'm way off base. I just happen to use vim-lsp and Go and would love the rename capability to work :-)

Let me know if there is some test I can run to help clarify how vim-lsp is failing.

**Comment by suzmue** [comment]
Yeah @kevinms is right.  It looks like the server is only allowed to respond with RenameOptions if the client first sends prepareSupport=true (it seems like it is always ok to send a boolean though).

Will fix the generated struct to support renameProvider being a boolean or RenameOptions.

**Comment by kevinms** [comment]
Just tried out the fix and renaming does work with the vim-lsp client now!

**Comment by jbizzle** [comment]
Hi -- Did this break with [207598](https://go-review.googlesource.com/c/tools/+/207598)? IIUC, that [changed](https://go-review.googlesource.com/c/tools/+/207598/3/internal/lsp/protocol/tsprotocol.go#1885) `RenameProvider`'s type to `RenameOptions` from `interface{}`, and [the code which previously set the `true` value](https://go-review.googlesource.com/c/tools/+/207598/3/internal/lsp/general.go#b74) was removed. It again breaks `vim-lsp` for me in a way that is consistent with the original report here, so wonder if this was a regression.

(Tagging @pjweinb and @ianthehat from that revision).

**Comment by stamblerre** [comment]
Thanks for pointing this out. I mailed the above CL to fix it, and if it gets changed the next time the protocol is generated, we will be able to pick up the breakage in the new test.
