### ISSUE TITLE
Plugins are strongly related to versions and have poor practicability.

### ISSUE THREAD

**Issue by rocket049** [golang/go#32708]
### What version of Go are you using (`go version`)?

go version go1.12.5 linux/amd64

### What did you expect to see?

It is hoped that the plugin call interface can be decoupled from the version.

### What did you see instead?

Plugins are strongly related to versions and have poor practicability.

**Comment by ianlancetaylor** [comment]
Yes, that would be nice.  But this isn't really an actionable issue, so I'm going to close it.  Sorry.

Fixing this will require a complete rethink of how plugins work.  I don't see any way the current approach for plugins, which simply relies on the system dynamic linker, could safely permit mixing multiple Go versions.

**Comment by rocket049** [comment]
It's worth it.
Hope it will come true in the future

**Comment by rocket049** [comment]
@ianlancetaylor i thought the problem is a plugin include a real runtime. if give it a virtual runtime, let it pointer to current runtime when the plugin is loaded ,the issue maybe can be fixed.

**Comment by ianlancetaylor** [comment]
I would be happy to look at a detailed design.
