### ISSUE TITLE
Why design that goroutine will not exit instead park resume when we set chan = nil 

### ISSUE THREAD

**Issue by Anteoy** [golang/go#32702]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/home/zhoudazhuang/gobin/"
GOCACHE="/home/zhoudazhuang/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/zhoudazhuang/db11/jm/pro"
GOPROXY=""
GORACE=""
GOROOT="/home/zhoudazhuang/usr/local/go1.12.1/go"
GOTMPDIR=""
GOTOOLDIR="/home/zhoudazhuang/usr/local/go1.12.1/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build631445118=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
```
package main

import (
	"fmt"
	"net/http"
	_ "net/http/pprof"
	"sync"
	"time"
)

func main() {
	buf := make(chan int, 10)
	wg := sync.WaitGroup{}
	wg.Add(1)
	go func() {
		defer func() {
			wg.Add(-1)
			fmt.Println("协程退出...")
		}()
		for {
			message, ok := <-buf
			if !ok {
				fmt.Println("is not ok")
				return
			}
			fmt.Printf("%d\n", message)
		}
	}()
	buf <- 1
	time.Sleep(time.Second * 10)
	buf = nil
	fmt.Printf("开始 wait\n")
	go http.ListenAndServe(":9191", nil)
	time.Sleep(time.Minute * 10)
	wg.Wait()
}
```
my goroutine which receive with the channel will not exit or panic. I just see :
```
runtime.chanrecv
if c == nil {
		if !block {
			return
		}
		gopark(nil, nil, waitReasonChanReceiveNilChan, traceEvGoStop, 2)
		throw("unreachable")
}
```
then it call the gopark. It cause that my server got lots of goroutine which is not exit. I got the goroutine leak.

### What did you expect to see?
the goroutine will panic and exit.

### What did you see instead?
goroutine leak

**Comment by MaruHyl** [comment]
Agree.
`nil chan` should be equal to `closed chan`.

**Comment by nussjustin** [comment]
The issue tracker is not for questions. In the future please try to ask your question on the [golang-nuts mailing list](https://groups.google.com/forum/#!forum/golang-nuts) or [one of the other places listed in the wiki](https://github.com/golang/go/wiki/Questions).

---

To answer your question:

This works as specified.

The current behaviour where receiving from a `nil` channel blocks is a design decision and can be useful in some cases. See [this blogspot](https://www.godesignpatterns.com/2014/05/nil-channels-always-block.html) for an example use case.

From the [spec](https://golang.org/ref/spec#Receive_operator)

> For an operand ch of channel type, the value of the receive operation <-ch is the value received from the channel ch. The channel direction must permit receive operations, and the type of the receive operation is the element type of the channel. The expression blocks until a value is available. **Receiving from a nil channel blocks forever.** A receive operation on a closed channel can always proceed immediately, yielding the element type's zero value after any previously sent values have been received.

I you want to signal your goroutines that no more values will be received on a channel just close it and check for the `ok` value in the receiving goroutines.

This will also help prevent data races, like the one in your example: You are concurrently reading and writing `buf` without synchronization, which can lead to unexpected behavior. Running your example with the [race detector](https://golang.org/doc/articles/race_detector.html) enabled (`-race` flag to `go run/build/install`) will cause a data race warning to be printed after a few seconds.

**Comment by Anteoy** [comment]
thx

**Comment by ianlancetaylor** [comment]
See also #21069.
