### ISSUE TITLE
Installer: allow different installation directories

### ISSUE THREAD

**Issue by catastrop** [golang/go#32706]
can i use `/usr/local/bin` instead of `/usr/local/go/bin`?

**Comment by ALTree** [comment]
Which OS? Are you talking about the MacOS installer?

**Comment by catastrop** [comment]
I have moved go, gofmt, godoc to `usr/local/bin` and everything is working fine.

Why the installation guide tell us to use `usr/local/go/bin`.

**Comment by agnivade** [comment]
I am guessing you are not able to use the Go binaries from the command line. This is because you haven't added /usr/local/go/bin to your $PATH. The installer does mention that.

You are not forced to install the binaries to /usr/local/go/bin. That is just a convention followed in UNIX.

**Comment by agnivade** [comment]
A minor correction - There is a relation between where the go binary is placed and the GOROOT resolution. If you place the Go distribution in /usr/local/go, then you may place the go binary anywhere. BUT, if you choose to place it elsewhere, then you must place the go binary in the bin/ directory under that path. Hence, the binaries are placed under /usr/local/go/bin.
