### ISSUE TITLE
x/tools/gopls: ServerCapabilities.RenameProvider should be interface

### ISSUE THREAD

**Issue by suzmue** [golang/go#32710]
ServerCapabilities.RenameProvider needs to be interface in the generated struct.

The server may need to return either a boolean or RenameOptions to the client, since it may only send RenameOptions if the client specifies prepareSupport.

Re: Issue #32703

**Comment by suzmue** [comment]
@pjweinb : Could we make this change in the protocol generator?

**Comment by pjweinb** [comment]
i'll try to look at it over the weekend.

**Comment by stamblerre** [comment]
This is done as of [CL 194177](https://go-review.googlesource.com/c/tools/+/194177).
