### ISSUE TITLE
Value returned by reflect.Value.Index() can be Set when indexing into slice but not when indexing into array

### ISSUE THREAD

**Issue by marcel** [golang/go#32714]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes. As of right now the latest release is `1.12.6`.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/marmolina/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/marmolina/local/lib/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.6/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/42/ls02b11d6rn2k4v2mw981t80h_g409/T/go-build026078408=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

https://play.golang.org/p/turNRNTJNKi

### What did you expect to see?

<pre>
slice correct: true
array correct: true
</pre>

### What did you see instead?

<pre>
slice correct: true
panic: reflect: reflect.Value.Set using unaddressable value

goroutine 1 [running]:
reflect.flag.mustBeAssignable(0x16, 0x4c85)
	/usr/local/go/src/reflect/value.go:234 +0x180
reflect.Value.Set(0xe84c0, 0x0, 0x16, 0xe84c0, 0x1acfe0, 0x16)
	/usr/local/go/src/reflect/value.go:1467 +0x40
main.SetValue(0xe84c0, 0x0, 0x16, 0x0)
	/tmp/sandbox414651569/prog.go:40 +0xc0
main.PopulateList(0xf1ca0, 0x0, 0x11, 0x2)
	/tmp/sandbox414651569/prog.go:35 +0x60
main.main()
	/tmp/sandbox414651569/prog.go:26 +0x2c0
</pre>

### Commentary

The flag set on the `reflect.Value` returned by the `Index` method for slice elements versus array elements is different which is why `Set` is not possible on the array elements' `Value`, but the question is whether that's an unintended consequence or deliberate. From the outside it seems incorrect and inconsistent that you would not be able to mutate a pointer to a struct stored in an array via reflection because you are able to do so directly without reflection. Presumably functionally equivalent behavior performed with reflection versus without would have the same outcome.

**Comment by ianlancetaylor** [comment]
The reflect package works this way because arrays are values whereas slices include a reference to an array.  Calling `reflect.ValueOf` on a value of array type gives you an array value, not a reference to an array value.  You can't change an element of that array value any more than you can change the result of calling `reflect.ValueOf` on a number.  Calling `reflect.ValueOf` on a value of slice type gives you a slice value, which includes a reference to an array.  Changing an element of the slice means changing an element of the referenced array.

Compare to https://play.golang.org/p/rdoVOVFbN4u which uses an addressable array rather than an array value.
