### ISSUE TITLE
net: cannot bind network card to send data on macos

### ISSUE THREAD

**Issue by weiyixuan** [golang/go#32722]
go1.11.0   
macOS Mojave

I added two default routes that direct all traffic to a single virtual network card. Then I want to send the test program data directly from the physical network card. I first used bind()，but an error occured while establishing the connection: [connect: no route to host]

On Windows and Linux, I can use the bind() function to bind network cards to send data. Is there any way to do it on a MAC?

```
var netAddr net.Addr

netAddr = &net.TCPAddr{}
netAddr.(*net.TCPAddr).IP = net.ParseIP("xxx.xxx.xxx.xxx")
dialer := net.Dialer{LocalAddr:netAddr}
conn, err := dialer.Dial("tcp", "yyy.yyy.yyy.yyy:mm")
if err != nil {
	log.Println(err)
	return
}
defer conn.Close()
log.Println("conn successful")
```

**Comment by ianlancetaylor** [comment]
CC @mikioh

**Comment by weiyixuan** [comment]
Is there a temporary solution?
