### ISSUE TITLE
gollvm:  CMake Error can't find source file ../gofrontend/libgo/urntime/go-strslice.c

### ISSUE THREAD

**Issue by dereklstinson** [golang/go#32727]
I'm trying to build gollvm. I am using the steps given at https://go.googlesource.com/gollvm/. Ran into this error.  

> 
> CMake Error at tools/gollvm/libgo/CMakeLists.txt:469 (add_library):
>   Cannot find source file:
> 
>    home/derek/workspace/llvm/tools/gollvm/gofrontend/libgo/runtime/go-strslice.c
> 
>   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
>   .hxx .in .txx
> 
> 
> CMake Error: CMake can not determine linker language for target: libgo_c_piclib
> CMake Error: CMake can not determine linker language for target: libgo_c_nonpiclib
>

**Comment by thanm** [comment]
Thanks for the report. There was a recent commit (this morning in fact) that removed that file in gofrontend -- gollvm hasn't caught up.  I will send a CL, stay tuned.
