### ISSUE TITLE
cmd/compile: internal error on complex comparison

### ISSUE THREAD

**Issue by gazerro** [golang/go#32723]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +44c9354c5a Fri Jun 21 05:21:30 2019 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What did you do?

`_ = 1i < 2i`

https://play.golang.org/p/syOtlxxmrya

### What did you expect to see?

invalid operation: 1i < 2i (operator < not defined on complex128)

### What did you see instead?

internal compiler error: compareOp: bad comparison: 1i < 2i

**Comment by agnivade** [comment]
Not a regression from 1.12. So adding to 1.14.

And seems to happen only while directly comparing literals. If I compare complex variables, I get the correct error.

**Comment by danicat** [comment]
I'm interested in working on this issue if nobody is working on it yet. Seems like a good opportunity to start digging into the compiler code.

**Comment by fgm** [comment]
A very similar error happens on exponentiation, as shown on https://play.golang.org/p/hYUAK-ex6tQ  (#33458 closed as dup), except it is not an internal error on comparison but on operation.
