### ISSUE TITLE
GONOPROXY doesn't whitelist my private modules

### ISSUE THREAD

**Issue by owlwalks** [golang/go#32736]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/khoa/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/khoa/go"
GOPROXY="https://proxy.golang.org"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/khoa/src/public-api/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build385300656=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```
export GOPROXY=https://proxy.golang.org
export GONOPROXY=gitlab.com/localmeasure
export GONOSUMDB=$GONOPROXY
```
```
git config --global url.ssh://git@gitlab.com/localmeasure.insteadOf https://gitlab.com/localmeasure
```
then
```
go get ./...
```

### What did you expect to see?
My whitelisted private modules should not be queried to proxy.golang.org

### What did you see instead?
```
go: finding gitlab.com/localmeasure/std v0.0.0-20190618060853-6f2e594241de
go: gitlab.com/localmeasure/std@v0.0.0-20190618060853-6f2e594241de: unexpected status (https://proxy.golang.org/gitlab.com/localmeasure/std/@v/v0.0.0-20190618060853-6f2e594241de.info): 410 Gone
go: error loading module requirements
```

**Comment by mvdan** [comment]
Seems to me like you're misusing the pattern. You likely want `gitlab.com/localmeasure/*`.

Also, see the new `GOPRIVATE` var being added in 1.13, which is more appropriate for these purposes. It uses the same syntax.

**Comment by owlwalks** [comment]
thanks @mvdan, still no luck with `gitlab.com/localmeasure/*` though
```
export GOPROXY=https://proxy.golang.org
export GONOPROXY=gitlab.com/localmeasure/*
export GONOSUMDB=$GONOPROXY
...
source ~/.profile
go clean -modcache
...
go get -d ./...
go: finding gitlab.com/localmeasure/std v0.0.0-20190618060853-6f2e594241de
go: gitlab.com/localmeasure/std@v0.0.0-20190618060853-6f2e594241de: unexpected status (https://proxy.golang.org/gitlab.com/localmeasure/std/@v/v0.0.0-20190618060853-6f2e594241de.info): 410 Gone
go: error loading module requirements
```

**Comment by mvdan** [comment]
Be careful with characters like `*` in the shell; they might be getting expanded. You might want to verify that it's being set properly via `go env | grep gitlab` or something similar.

**Comment by owlwalks** [comment]
that could be the problem then, my `go env` doesn't have `GONOPROXY` nor `GONOSUMDB`, it only picks up `GOPROXY`

```
export GOPROXY="https://proxy.golang.org"
export GONOPROXY="gitlab.com/localmeasure/*"
export GONOSUMDB="gitlab.com/localmeasure/*"
```

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/khoa/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/khoa/go"
GOPROXY="https://proxy.golang.org"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build090552563=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by mvdan** [comment]
Right. These were added in master as part of the 1.13 cycle, so you can't use them in 1.12.x

**Comment by owlwalks** [comment]
Thought it [was ready](https://go.googlesource.com/proposal/+/master/design/25530-sumdb.md) :) , appreciate your help.
