### ISSUE TITLE
cmd/vet reports unreachable code - for/switch

### ISSUE THREAD

**Issue by qiangli** [golang/go#32730]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/qiang.li/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/qiang.li/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2r/7l5dccss0y74mcl41nqbpyfm6h04p2/T/go-build866904691=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

run  go vet ./... for the below code

<pre>
package main

import (
	"fmt"
	"os"
	"strconv"
)

const max = 1

func main() {
	for i := 0; ; i++ {
		_, err := strconv.Atoi(os.Args[1])

		switch {
		case err == nil:
			break
		case i < max:
			continue
		default:
			os.Exit(1)
		}
	}

	fmt.Println("unreachable code?")
}
</pre>

### What did you expect to see?

no warning

### What did you see instead?
<pre>
# _/Users/qiang.li/saas/play/bug
./main.go:25:2: unreachable code
</pre>

**Comment by mvdan** [comment]
The code is unreachable. I assume your confusion comes from the `break`, which is working with the `switch`, not the `for`.
