### ISSUE TITLE
question: Full meaning of `rune`

### ISSUE THREAD

**Issue by catastrop** [golang/go#32737]
What does `rune` represent?
Why is it called `rune`?

**Comment by mvdan** [comment]
Have you read the documentation, or researched this first?

https://golang.org/pkg/builtin/#rune

https://stackoverflow.com/questions/19310700/what-is-a-rune

**Comment by catastrop** [comment]
@mvdan,
I have read them. My question was what does `rune` stand for ?

Like `int` stands for integer.

**Comment by mvdan** [comment]
It's an English noun. You can find many definitions online, like:

> A letter of an ancient Germanic alphabet, related to the Roman alphabet.

It really just means "character" in this context, as documented in the builtin package. I assume they didn't choose `character` as it's long, and they didn't choose `char` because of the confusion with the C family of languages.

**Comment by dominikh** [comment]
Note that `rune` in this context predates Go. You can find runes in Plan 9's code base.

**Comment by dominikh** [comment]
https://twitter.com/rob_pike/status/732353233474064384 for the relatively simple history of it.
