### ISSUE TITLE
path/filepath: considering supporting  Match capture brackets?

### ISSUE THREAD

**Issue by BlackHole1** [golang/go#32745]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/black-hole/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/black-hole/Code/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/82/jkr30dwj24ncf6ng3tdv9kd40000gn/T/go-build995054786=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://play.golang.org/p/5z50Mg2C_ol

### What did you expect to see?

```
/etc/group
/etc/hosts
```

### What did you see instead?

`nothing`

### Other

I looked at the code and found that match does not support bracket matching. Is there any reason?

**Comment by av86743** [comment]
>     matches, err := filepath.Glob("/etc/(group|hosts)")
It's not a shell glob?

**Comment by ianlancetaylor** [comment]
To expand on what @av86743 said, `filepath.Match` implements the file path matching done by the Unix shell.  I'm not aware of any Unix shell that implements the kind of match you describe.

**Comment by BlackHole1** [comment]
@ianlancetaylor Match is not implemented. Only support `[-]*`

**Comment by BlackHole1** [comment]
The support of glob is to guarantee the same behavior as the linux shell. Is this the case?

**Comment by ianlancetaylor** [comment]
Yes.  As documented.

**Comment by BlackHole1** [comment]
I don't understand why it must be the same as the original Glob? What are the benefits of doing this?

**Comment by ianlancetaylor** [comment]
It's easy to understand by analogy, and it corresponds to the C language `glob` function (http://man7.org/linux/man-pages/man7/glob.7.html).

What are the benefits of being different?

**Comment by BlackHole1** [comment]
Ok, really shouldn’t be different, thank you for your answer.
