### ISSUE TITLE
x/playground: support custom GOPROXY

### ISSUE THREAD

**Issue by cep21** [golang/go#32740]
### What version of Go are you using (`go version`)?
Playground depends upon `docker build`.  I'm using the default build args.
<pre>
$ github.com/golang/playground@master

</pre>

### What did you do?

Install the go playground inside my company VPN.  I wrote a playground program that used internal only libraries.

### What did you expect to see?

I expected my program to run.

### What did you see instead?

The playground was unable to run my code.

The playground code hardcodes https://github.com/golang/playground/blob/a7b4d4c4bb72efd2ec20c9f30d5c1e6f09cee3d2/sandbox.go#L373 GOPROXY=https://proxy.golang.org.

I forked the playground code and replace `GOPROXY=https://proxy.golang.org.` with our company's internal athen's proxy `GOPROXY=https://proxy.mycompany.intranet.` . I was then able to use my company's internal software.

I would propose that the playground's Dockerfile https://github.com/golang/playground/blob/master/Dockerfile accept GOPROXY as an environment variable that configures where the playground uses the proxy

**Comment by andybons** [comment]
Seems fine with me. Mind submitting a patch that accepts an env var and defaults to https://proxy.golang.org if it’s not set?

**Comment by cep21** [comment]
Sure thing!
