### ISSUE TITLE
How to extract the IV of AES-GCM in "crypto/cipher"

### ISSUE THREAD

**Issue by jyxjjj** [golang/go#32742]
### What version of Go are you using (`go version`)?
<pre>
go version go1.12.6 linux/amd64
</pre>
### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/data/Projects/Go/gopath"
GOPROXY=""
GORACE=""
GOROOT="/data/go"
GOTMPDIR=""
GOTOOLDIR="/data/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build319981367=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Developing an "AES-256-GCM" Client Interacting with PHP-openssl-ext
### What did you expect to see?
Like this (It's Pseudo-code and only my target):
<pre>
It's Pseudo-code and only my target:

func encrypt("123"(data),"123"(key))
return encryptedData(hex)+"|"+iv(hex)+"|"+nonce(hex)

then:

encryptedData = split(return)[0]
iv = split(return)[1]
nonce = split(return)[2]
decrypt(encryptedData , iv , nonce)
return decryptedData
</pre>
### What did you see instead?
1.Golang has no iv, only nonce.(I found Python maybe hasn't too. But C and PHP has. And the RFC doc said it should have.)
2.Golang doesn't support un-fixed very short length password.(like "123" will cause error because of its short.)(It doesn't mean i can't do any padding for the password(key), If I do, it can't crypt as well as php.)

**Comment by jyxjjj** [comment]
Sorry, due to some personal blogs, maybe i confused the iv/nonce/aad/tag.
But it truely only one 32 length HEX string data.
In php it is tag. I think it is nonce.
Another 24 length HEX string data lost. In php it's IV.

**Comment by jyxjjj** [comment]
Searched on Wikipedia.
I think i need tag instead of iv.
The iv in GoLang is nonce.

**Comment by FiloSottile** [comment]
IV and nonce are mostly synonyms. AES-GCM is an AEAD and it takes (key, nonce, plaintext[, aad]) and generates a ciphertext, which includes the authentication tag.

Note that the key for AES-256 must be 32 uniform (random-looking) bytes, you don't want to use a password like "123", or even "12345678901234567890123456789012". Use scrypt to derive the key first.

The golang/go issue tracker is used to develop the Go project, so you'll get more help with questions about using the Go language through the resources listed at https://golang.org/wiki/Questions.

**Comment by FiloSottile** [comment]
If you are trying to separate ciphertext and tag, the tag is at the end of the ciphertext in Go. There is some discussion about a split API at #24990.
