### ISSUE TITLE
runtime: callee saved r4 is destroyed unexpectedly in sigtramp@sys_darwin_arm.s

### ISSUE THREAD

**Issue by beenshi** [golang/go#32744]
TEXT runtime·sigtramp(SB),NOSPLIT,$0
		// Reserve space for callee-save registers and arguments.
		SUB	$36, R13
	
		MOVW	R4, 12(R13)
		MOVW	R5, 16(R13)
		MOVW	R6, 20(R13)
		MOVW	R7, 24(R13)
		MOVW	R8, 28(R13)
		MOVW	R11, 32(R13)	
	
		// Save arguments.
		MOVW	R0, 4(R13)	// sig
		MOVW	R1, 8(R13)	// info
		MOVW	R2, 12(R13)	// ctx
	
The R4 is first stored to 12(R13), then R2 is also stored to 12(R13), so the original value in R4 is destroyed.

**Comment by odeke-em** [comment]
Thank you for reporting this bug @beenshi!

@ianlancetaylor I see you've reviewed Ben's CL, shall we triage this for Go1.13 or Go1.14?

**Comment by ianlancetaylor** [comment]
It's fine for 1.13.  Thanks.
