### ISSUE TITLE
x/sys: howto set a autorun registry  in windows

### ISSUE THREAD

**Issue by zsdevX** [golang/go#32748]
I write the code, but does not work. it cannot create xxx and no error found.
```
func SetAutoRun(run bool) error {
	k, err := registry.OpenKey(registry.CURRENT_USER,
		`HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`,
		registry.QUERY_VALUE|registry.SET_VALUE)
	if err != nil {
		return err
	}
	defer k.Close()
	if run {
		if err := k.SetStringValue("xxx", SysExecPath("xxx.exe")); err != nil {
			return err
		}
	} else {
		k.DeleteValue("xxx")
	}
	return nil
}
```

another code:
```
	key, _, err := registry.CreateKey(registry.CURRENT_USER, "HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run", registry.ALL_ACCESS)
	if err != nil {
		return err
	}
	defer key.Close()

	if run {
		nkey, _, err := registry.CreateKey(key, "xxx", registry.ALL_ACCESS)
		if err != nil {
			return err
		}
		defer nkey.Close()
		err = nkey.SetStringValue("String", SysExecPath("xxx.exe"))
		if err != nil {
			return err
		}
	} else {
		key.DeleteValue("xxx")
	}
```

**Comment by bontibon** [comment]
I didn't try running the code, but since you already are opening `registry.CURRENT_USER`, you can drop `HKEY_CURRENT_USER` from the path:
```go
registry.OpenKey(registry.CURRENT_USER, `SOFTWARE\Microsoft\Windows\CurrentVersion\Run`, ...)
```

**Comment by solderjs** [comment]
Just posting for the sake of posterity:

The reason I came across this was that I was trying to create a user-mode service that would run on user login every time.

Here's how I did it, which is working for me presently:
https://git.rootprojects.org/root/serviceman/src/commit/f95897cf308c3e19d6fe4b088547d8290907e384/manager/install_windows.go#L60-L109

I also needed to do similar for Mac and Linux, and that project is the cross-platform service manager I came up with, suited to my needs - which are more focused on user-mode services than system-level services.
