### ISSUE TITLE
cmd/go: panic when attempting to load a plugin on 1.11.4

### ISSUE THREAD

**Issue by wangzz719** [golang/go#32752]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
go1.12.4 works correctly

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/wangzhizhao/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/wangzhizhao/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/wangzhizhao/go/src/code.byted.org/ies/sensitive_marker/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build679397982=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

With go1.11.4, I use go module with vendor mode, and then I load a so build whith go1.11.4, then I got a panic: plugin was built with a different version of package net

### What did you expect to see?

plugin .so could be correctly loaded.

### What did you see instead?
panic plugin was built with a different version of package net

**Comment by AlexRouSg** [comment]
Have you tried `1.11.11`?

**Comment by wangzz719** [comment]
> Have you tried `1.11.11`?

go1.11.11 got the same error.

**Comment by andybons** [comment]
@wangzz719 is there a reason you’re stuck on 1.11 and have not upgraded to 1.12? It’s unlikely this will be fixed by the time 1.11 becomes unsupported a couple months from now.

**Comment by wangzz719** [comment]
> @wangzz719 is there a reason you’re stuck on 1.11 and have not upgraded to 1.12? It’s unlikely this will be fixed by the time 1.11 becomes unsupported a couple months from now.

In our workplace, a lot of projects still using 1.11 and try using the go module to manage dependency. I can have a try to persuade other workmates using go module with 1.12.

**Comment by andybons** [comment]
Closing for now since modules support is improving with each release and 1.11 will be unsupported soon anyway.
