### ISSUE TITLE
l-0po0o[p=-09oi8y67gtfb vcijuhm nboiuytg xcfytdvc

### ISSUE THREAD

**Issue by AndreySerebrovC2M** [golang/go#32753]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by martisch** [comment]
Not filled out bug report. Nothing actionable. Therefore closing.
