### ISSUE TITLE
You guys should look into this to find out what things are needed to improve go: https://github.com/ksimka/go-is-not-good

### ISSUE THREAD

**Issue by cyantarek** [golang/go#32759]
https://github.com/ksimka/go-is-not-good

**Comment by networkimprov** [comment]
The Go team is all too aware of the criticism that is constantly leveled at their work, poor devils.

If you think Go needs fixing, you might want to try a different language, e.g. [Zig](https://ziglang.org) or [Rust](https://rust-lang.org).

**Comment by agnivade** [comment]
Thanks. If you have any specific issue that needs to be worked on, please let us know. Otherwise feel free to discuss this in the forums at the [Questions](https://github.com/golang/go/wiki/Questions) wiki page. The issue tracker is only meant to track bugs and proposals.
