### ISSUE TITLE
runtime: request softfloat for all platform (not only mips)

### ISSUE THREAD

**Issue by mohanson** [golang/go#32760]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 linux/amd64
</pre>

I can use `GOMIPS=softfloat` to use softfloat on MIPS since go1.10 or go1.11, do you guys intend to bring it to other platforms? like x86 or arm.

**Comment by martisch** [comment]
Could you give some details why soft float on x86 would be useful?

The minimum requirement due to 64bit atomics for Go is Pentium MMX on x86 and thereby all supported chips should have floating point support in hardware.

I think arm has softfloat support. See https://github.com/golang/go/wiki/GoArm

**Comment by mohanson** [comment]
I'm interested on riscv, as we known, floating point on rsicv chip is optional, So I think If there is a **general** softfloat implementation(not limited on MIPs), it would be fine.

**Comment by martisch** [comment]
Go gc does not support RISC V yet. Once it does soft float for RISC V if not yet implemented can be considered. Which leaves the question why soft float for platforms that always support hardware float operations needs to be supported?

I can see not much demands/use for this yet and its something that needs to be kept maintained and tested. 

Once RISC V is supported I think it would be fine to open an issue about soft float support if not present. But likely that will trigger an implementation with compiler intrinsics and asm code to have better performance.

**Comment by mohanson** [comment]
For some cross-architecture solutions, the most hacked solution is to translate the source architecture machine language to the target architecture machine language, and if the source machine language uses floating point instructions, it will cause a lot of trouble for the translation. It's my personal interst. 

I understand that this is not your current focus,  and most people doesn't need it. Thank you for your reply!  :)

**Comment by martisch** [comment]
Thanks for the explanation. I can see how it makes this very special use case a bit easier but I do not think there is sufficient demand to out way the complexity and maintenance burden that would be added.

GCC supports [-msoft-float](http://gcc.gnu.org/onlinedocs/gcc-4.6.1/gcc/i386-and-x86_002d64-Options.html#i386-and-x86_002d64-Options) but I do not know if https://golang.org/doc/install/gccgo does.

**Comment by elvin-du** [comment]
In the area of blockchain, smart contracts run floating-point computing. If golang can support soft floating-point computing on all platforms, it will be very useful.
