### ISSUE TITLE
proxy.golang.org: 400 Bad Request

### ISSUE THREAD

**Issue by gobins** [golang/go#32765]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Have not checked.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env
</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gsougrak/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/gsougrak/go"
GOPROXY="https://proxy.golang.org"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/gsougrak/git/capacitor/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build359367473=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
go clean --modcache
go build

### What did you expect to see?
Clean build with no errors

### What did you see instead?
```cannot load golang.org/x/sys/unix: unexpected status (https://proxy.golang.org/golang.org/x/sys/@v/v0.0.0-20190624145334-c5567b49c5d0.zip): 400 Bad Request```

The build works if I unset the GOPROXY.

**Comment by heschik** [comment]
Where did that pseudoversion come from? The correct pseudoversion for that commit seems to be `v0.0.0-20190624142023-c5567b49c5d0`, with a slightly different timestamp. https://github.com/golang/go/issues/32662#issuecomment-502863470 is the reason it's failing.

**Comment by gobins** [comment]
The issue got fixed after I updated the package. I don't touch the mod file directly, must be one the steps in the build that updated the version.

**Comment by heschik** [comment]
I'm glad it's working for you, but I'd really like to know where the bad version came from, especially since it'll break in 1.13. Can you tell me anything about what might have caused it?

**Comment by gobins** [comment]
I spent some time trying to reproduce the issue but have not been successful. 
The go version I started out was 1.12.

**Comment by heschik** [comment]
Very strange. Well, thanks for trying.
