### ISSUE TITLE
syscall/js: "goroutines are asleep" error only in Node.js

### ISSUE THREAD

**Issue by agnivade** [golang/go#32764]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
```go
package main

import (
	"fmt"
	"syscall/js"
)

func main() {
	var cb js.Func
	cb = js.FuncOf(func(this js.Value, args []js.Value) interface{} {
		fmt.Println("cb called")
		return nil
	})
	js.Global().Set("callme", cb)
	done := make(chan struct{})
	fmt.Println("waiting for callback")
	<-done
}
```

I ran this in both browser and Node.js.

### What did you expect to see?
I expect in both cases, for the program to wait indefinitely.

### What did you see instead?
In works fine in browser:
```
$#go_js_wasm_exec is set to wasmbrowsertest
$GOOS=js GOARCH=wasm go run foo.go 
waiting for callback
^Csignal: interrupt
```

But fails in Node.js

```
$PATH=/usr/local/go/misc/wasm:$PATH GOOS=js GOARCH=wasm go run foo.go 
waiting for callback
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
main.main()
	/home/agniva/play/go/src/foo.go:24 +0xb
exit status 2
```
Is this expected ?

My node version is 10.2.1

/cc @neelance

I haven't tried with 1.11 because the function semantics have changed since.

**Comment by johanbrandhorst** [comment]
Thinking out loud, but presumably this incompatibility is lurking somewhere in `wasm_exec.js`? If it's working in the browser, I assume that means the generated WASM is fine, and that it's the translation layer that's doing something wrong.

**Comment by neelance** [comment]
This is expected. The following code is only used by Node.js:
https://github.com/golang/go/blob/5f4aa5d79fba270d6a14f2a55999b5b6ccec2326/misc/wasm/wasm_exec.js#L525-L531

The reasoning is that if all goroutines are asleep AND there is no Node.js event handler pending, then the program can never continue, which is a "deadlock" situation. In fact, the default behavior of Node.js is to just quit with exit code 0, because there is no code to run any more 😒. I opted for throwing the error instead.

**Comment by agnivade** [comment]
I see. Then does this mean in Node.js, we can never attach a global callback without hooking into the event loop somehow ?

**Comment by neelance** [comment]
The issue is not the callback, but that there is no code at all running any more, thus the application would hang forever. Explicitly saying "this is a deadlock" is a feature, not a bug.

 What are you trying to do?

**Comment by agnivade** [comment]
I was trying to debug this - https://github.com/golang/go/issues/26277. Then realized that the code gives this deadlock error, which obviously did not give at that time. Reduced it to this test case.

Hence, I was trying to get to the root of it.

Full code here

<details>
package main

import (
	"fmt"
	"syscall/js"
)

var headers js.Value

func init() {
	headers := js.Global().Get("Object").New()
	headers.Set("Content-Type", "text/plain")
}

func main() {
	require := js.Global().Get("require")
	http := require.Invoke("http")
	app := http.Get("Server").New()
	app.Call("on", "request", js.FuncOf(request))
	app.Call("listen", 3000, js.FuncOf(listen))
	wait()
}

func request(this js.Value, args []js.Value) interface{} {
	res := args[1]
	res.Call("writeHead", 200, headers)
	res.Call("write", "Hello World")
	res.Call("end", "\n")
	return nil
}

func listen(this js.Value, args []js.Value) interface{} {
	fmt.Println("listening on port 3000")
	return nil
}

func wait() {
	done := make(chan bool)
	js.Global().Get("process").Call("on", "SIGTERM", js.FuncOf(func(this js.Value, args []js.Value) interface{} {
		done <- true
		return nil
	}))
	<-done
}

</details>

**Comment by neelance** [comment]
The problem with this code is that you are doing a blocking operation (`fmt.Println`) in a callback (`listen`). This causes `listen` to never return, thus the HTTP server never starts. This means that there is no event that can ever cause the program to continue, which is a deadlock.

If you replace `fmt.Println` with `go fmt.Println` or `println`, then it works as expected.

However, the stack of the hanging `listen` function does not show up when printing the deadlock. This is bad, I'll look into it.

**Comment by agnivade** [comment]
Aha ! Missed that one. Sorry I went down a different rabbit hole. Thanks for looking into it.

**Comment by agnivade** [comment]
This is resolved. Closing.
