### ISSUE TITLE
`` Function special symbols in text are not supported

### ISSUE THREAD

**Issue by xhochipe** [golang/go#32767]
<pre>
$ go version
  go version 1.11
</pre>

![image](https://user-images.githubusercontent.com/9391575/60084726-a3af1a00-976a-11e9-8b6f-076f2940e44a.png)

`` Function special symbols in text are not supported

**Comment by agnivade** [comment]
Hello @xhochipe - It is not exactly clear what you are reporting. Did you mean to put a ` inside a raw string literal ? That is not supported.

Please show us a complete sample of code that is not a screenshot which clearly explains what you did, what happened and what you expected to happen. Thanks.

**Comment by xhochipe** [comment]
@agnivade  https://github.com/golang/go/issues/24475#event-1556138522  i`m  close issue
