### ISSUE TITLE
wasm: no standard output on Windows

### ISSUE THREAD

**Issue by jb2martel** [golang/go#32774]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
NA

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\jdemartel\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\jdemartel\go
set GOPROXY=
set GORACE=
set GOROOT=c:\go
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\JDEMAR~1\AppData\Local\Temp\go-build750286854=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

- Write a hello world go program
<details><summary> Source code </summary><br />

```go
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Println("standard output")
	os.Exit(0)
}
```
</details>

- Compile to webassembly using` GOOS=js GOARCH=wasm go build -o main.wasm main.go`
- Run the compiled code using node and the supplied wasm_exec.js:
`node wasm_exec.js main.wasm`
  - On linux, this works fine
  - On windows, no output appears in terminal, whether it's git bash, command prompt or powershell

### What did you expect to see?
As the node versions (v12.4.0) and input files (wasm_exec.js and main.wasm) are identical, I would expect it to work on windows.

### What did you see instead?
No terminal output on windows. The command completes with no output in terminal, whether it's command prompt, git bash or powershell.

This is probably a mistake on my part rather than a bug - I guess I'm missing something but can't seem to find any related information. 

Thank you for your help !

EDIT:  added go source code

**Comment by jb2martel** [comment]
Note: C++ code compiled to wasm using emscripten works fine in the windows environnement, so it's probably not just my windows / node setup.

**Comment by andybons** [comment]
@neelance @dmitshur

**Comment by jb2martel** [comment]
Is there anything I can do to help investigate and/or advance the issue ?
I really don't know where to start and would appreciate any tips. 
Thanks!

**Comment by benshi001** [comment]
Please try go1.13, I can see "hello" printed with

go-1.13 for windows/amd64
node 10.16
windows server 2008 R2
	
	package main
	import "fmt"
	func main() {
		fmt.Println("hello")
	}

**Comment by andybons** [comment]
@jb2martel is this still an issue for you?

**Comment by benshi001** [comment]
Closed. Since,

1. it is not reproducible
2. it should not be a go issue (go wasm use console.log for fmt.Println)
