### ISSUE TITLE
flag: index out of range when argc is 0

### ISSUE THREAD

**Issue by kneht** [golang/go#32775]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.12"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.12/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you do?
When golang compiled binary invoked by execve with 0 arguments like this:
<details><summary><code>test.cpp</code> code</summary><br><pre>
#include <unistd.h>

int main() {
    execve("test.go.out", NULL, NULL);
}
</pre></details>

https://play.golang.org/p/zo3YJZTkBu_A

### What did you expect to see?
nothing

### What did you see instead?

panic: runtime error: index out of range

goroutine 1 [running]:
flag.init.ializers()
	/usr/lib/go-1.12/src/flag/flag.go:1009 +0x172

As for documentation, it's sort of guaranteed that os.Args[0] is a program name:
https://golang.org/pkg/os/#pkg-variables

When argc is 0, at least for Linux platform program name can be fetched from procfs(/proc/self/comm), probably here:
https://github.com/golang/go/blob/0a7bc8f430e3e4017910780a898a5f20d337895b/src/runtime/runtime1.go#L70-L73

**Comment by robpike** [comment]
Not sure there's anything to fix. That binary compiles and runs fine; it's the caller that's making a mistake: argv should never be empty.

**Comment by gregory-m** [comment]
From execve(2) man page:

On Linux, argv can be specified as NULL, which has the same effect as 
specifying this argument as a pointer to a list containing a single NULL pointer. 
**Do not take advantage of this misfeature!**
It is nonstandard and nonportable: on most other UNIX systems doing this 
will result in an error (EFAULT).

So, I'am also not sure if we need to fix something.

**Comment by kneht** [comment]
I've spotted this issue when my binary was ran by rsyslog.
Documentation looks inconsistent, as argv[0] doesn't have a program name, but whatever is provided to argv[0].
Module flag apparently is not only in charge of parsing args, but also flags when there is no argv[0] by throwing runtime error.
I'm new to golang and don't really have horse in this race, but from what I see at least len(argv) in flag module needs to be checked.

**Comment by gregory-m** [comment]
What config was used for `rsyslog`?

Something like this:

```
module(load="omprog")
action(type="omprog"
       binary="/pathto/omprog.py --parm1=\"value 1\" --parm2=\"value2\""
       template="RSYSLOG_TraditionalFileFormat")
```

**Comment by kneht** [comment]
yep, binary was invoked by `omprog` with no parameters.

**Comment by kneht** [comment]
It was fixed in latest versions of rsyslog apparently:
https://github.com/rsyslog/rsyslog/commit/8d807e35f08237438d5c4315ec0af74c43e69517
```
mmexternal bugfix: potentially missing argv[0]
This is incorrect and can cause problems with some language, namely go.
```

**Comment by gregory-m** [comment]
I searched Github and found another examples of `execve("cmd", NULL, NULL);` usage. It defentely  not best practice but maybe it good idea to not panic in such case? @ianlancetaylor @robpike

**Comment by ianlancetaylor** [comment]
It seems to me that the C `getopt` function will also crash in this case.  It really doesn't seem worth worrying about.

But I guess if someone sends a patch for 1.14 we can take a look.

**Comment by kneht** [comment]
`getopt(0,NULL,NULL)` will work as argc is 0 obviously,
I can try to work on patch, but I would need some guidance on where this issue needs to be fixed.

**Comment by ianlancetaylor** [comment]
In the initialization of `CommandLine` in the flag package.

**Comment by odeke-em** [comment]
Thank you for filing this issue @kneht and for the patience and everyone for chiming in. Welcome to the Go project!

I agree with what @robpike and @ianlancetaylor say: I don't think we should do anything here.

You are incorrectly using `execve` and yet `execve` asks that you pass at least one argument to `char *const argv[]` with the various standards and OSes stating in e.g.

### Posix
The all encompassing standard says
https://pubs.opengroup.org/onlinepubs/9699919799/functions/exec.html
<img width="1248" alt="Screen Shot 2019-11-07 at 10 06 16 PM" src="https://user-images.githubusercontent.com/4898263/68453588-d6523000-01aa-11ea-8660-c226e631b770.png">

### Linux
http://man7.org/linux/man-pages/man2/execve.2.html
<img width="766" alt="Screen Shot 2019-11-07 at 10 02 36 PM" src="https://user-images.githubusercontent.com/4898263/68453418-5330da00-01aa-11ea-8ebc-800a79476ef6.png">

### Windows
https://docs.microsoft.com/en-us/cpp/c-runtime-library/exec-wexec-functions?view=vs-2019
<img width="1239" alt="Screen Shot 2019-11-07 at 10 05 48 PM" src="https://user-images.githubusercontent.com/4898263/68453575-c76b7d80-01aa-11ea-8d6f-c5006ceb8ef2.png">

### Darwin
https://man.openbsd.org/execve.2
<img width="1067" alt="Screen Shot 2019-11-07 at 10 13 08 PM" src="https://user-images.githubusercontent.com/4898263/68453924-cdae2980-01ab-11ea-90b5-a0e2b4abd8bb.png">


### FreeBSD
https://www.freebsd.org/cgi/man.cgi?query=execve&sektion=2
<img width="746" alt="Screen Shot 2019-11-07 at 10 12 16 PM" src="https://user-images.githubusercontent.com/4898263/68453887-b53e0f00-01ab-11ea-9870-608d813da32f.png">


and running a C variant on my MacbookPro computer
```C
#include <unistd.h>

int main(int argc, char **argv) {
    getopt(0, NULL, NULL);
}
```
produces a SEGMENTATION FAULT as per
```shell
$ gcc call.c -o call && ./call
Segmentation fault: 11
```

Thus I shall close this issue, but nonetheless thank you for filing it, for the discourse, patience and for the CL. Looking forward to continuing to interact more with you on Go.

**Comment by kneht** [comment]
Hi @odeke-em, thank you for complete reply.

Based on links you've posted, standard and Linux documentation says that argv[0] **should** contain the filename, which sounds like recommendation to me.

Obviously you can check in **evecve** documentation for every OS and run any tests on personal computer  of your choice, but it doesn't matter much as more then 50% of golang users are on Linux, at least based on [survey 2018](https://blog.golang.org/survey2018-results).

Given that fix has been implemented by Max and pre approved by Ian I guess it's up to them if this change needs to be merged.

Thanks for your contributions @odeke-em .
