### ISSUE TITLE
misc/cgo: Test32579 breaks builds on aix/ppc64 and linux/s390x

### ISSUE THREAD

**Issue by Helflym** [golang/go#32770]
Test32579, introduce by [CL 183458](https://go-review.googlesource.com/c/go/+/183458),  doesn't work on aix/ppc64 and linux/s390x:
https://build.golang.org/log/7390cf1f99fa31505bc0f13e1834c2e7a20cc62f
https://build.golang.org/log/7df224f96eeb375bacff23d3656b111b3ee38a98

As these are big-endian, memset(..., 1, 1) won't set the value to 1(=0x00000001) but to 16777216 (=0x01000000). This can be reproduced with a C program. 

On aix/pc64 (big-endian):
```
$ cat memset.c 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct S32579 { int data[1]; } S32579;

void main(){
        S32579 s[1];
        s[0].data[0] = 0; //clear
        memset(&s[0].data[0], 1, 1);
        printf("0x%08x\n", s[0].data[0]);
}
$ gcc -maix64 memset.c && a.out 
0x01000000
```
On linux/ppc64le (little-endian)
```
$ gcc -m64 memset.c && ./a.out
0x00000001
```

How should this test be fixed ? Should memset be changed in order to still have `s[0].data[0] == 1` or can we simply check that for big-endian `s[0].data[0] == 16777216` ? 

/cc @ianlancetaylor @kawakami-o3

**Comment by kawakami-o3** [comment]
I recommend to use `unsigned char data[1]`, instead of `int data[1]`.
