### ISSUE TITLE
go/types: add a race test

### ISSUE THREAD

**Issue by griesemer** [golang/go#32783]
Reminder issue: go/types can be invoked concurrently and while the design is such that this should be ok (we know it's working), it would be good to have a test for it.

See also #32154 for a most recent failure due to a race condition.

(A test can be added to `(*tester).raceTest` in `cmd/dist/test.go`.)

**Comment by dmitshur** [comment]
https://github.com/golang/go/issues/36605#issuecomment-576924501 is relevant. /cc @matloob

**Comment by bcmills** [comment]
This may be relevant to #37602 and #37690.

**Comment by findleyr** [comment]
This was done in #47729
