### ISSUE TITLE
go/build: doesn't implement new GO111MODULE=auto logic for 1.13

### ISSUE THREAD

**Issue by dmitshur** [golang/go#32799]
There was limited module support added to `go/build` in #26504.

There is logic to determine whether it's appropriate to look at modules in `Context.importGo` method:

```Go
// If modules are not enabled, then the in-process code works fine and we should keep using it.
// TODO(bcmills): This assumes that the default is "auto" instead of "on".
switch os.Getenv("GO111MODULE") {
case "off":
	return errNoModules
case "on":
	// ok
default: // "", "auto", anything else
	// Automatic mode: no module use in $GOPATH/src.
	for _, root := range gopath {
		sub, ok := ctxt.hasSubdir(root, srcDir)
		if ok && strings.HasPrefix(sub, "src/") {
			return errNoModules
		}
	}
}
```

_(Source: [src/go/build/build.go#L1004-L1019](https://github.com/golang/go/blob/f938b9b33bc51eec6a16cfb13b5c3ef5e266db17/src/go/build/build.go#L1004-L1019))_

This logic is out of date for 1.13 given the change to `GO111MODULE=auto` in #31857.

Further [below](https://github.com/golang/go/blob/f938b9b33bc51eec6a16cfb13b5c3ef5e266db17/src/go/build/build.go#L1036-L1051), it looks to see if there is a go.mod file in the source directory or any of its parent directories. That needs to be checked before `return errNoModules` can be done when `srcDir` is inside GOPATH/src.

I know the support for modules in `go/build` is limited, so we need to decide if we should fix this or not. Given that having the wrong logic here can produce incorrect/inconsistent results and the fix should be small, I think it makes sense to do it. Added NeedsDecision label.

/cc @bcmills @jayconrod @rsc @matloob

**Comment by jayconrod** [comment]
I think we should fix this. We don't need to add any new support for modules, just new interpretation of `GO111MODULE`. Shouldn't be too complicated.
