### ISSUE TITLE
x/tools/gopls: cmd definition tests are flaky

### ISSUE THREAD

**Issue by stamblerre** [golang/go#32794]
The `gopls` cmd defintion tests tend to be flaky/inconsistent in some way.
To reproduce, run `go test ./internal/lsp/cmd -run=TestDefinitionHelpExample -v -count=2`. There should be unexpected errors in the logs.
They have been temporarily disabled by https://golang.org/cl/183628, but they should be fixed and re-enabled.

**Comment by heschik** [comment]
TestDefinitionHelpExample in cmd_test.go references this bug, and fixing it wasn't totally trivial. Reopening for a decision.

**Comment by stamblerre** [comment]
I think these tests have been skipped for so long that the code has really diverged. I think it's probably simplest to delete the test.
