### ISSUE TITLE
1.13beta1: can't load package: package -trimpath:

### ISSUE THREAD

**Issue by msAlcantara** [golang/go#32800]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go1.13beta1 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Latest beta version

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE="auto"
GOARCH="amd64"
GOBIN="/home/matheus/go/bin"
GOCACHE="/home/matheus/.cache/go-build"
GOENV="/home/matheus/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/matheus/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/matheus/sdk/go1.13beta1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/matheus/sdk/go1.13beta1/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/matheus/dev/go/test-go1.13beta1/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build630365835=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Simple hello world

```go
package main

import "fmt"

func main() {
	fmt.Println("Hello go 1.13 :D")	
}

```

### What did you expect to see?

Build program

### What did you see instead?

error:
`can't load package: package -trimpath: unknown import path "-trimpath": malformed module path "-trimpath": leading dash`

**Comment by dmitshur** [comment]
Thanks for the report.

Your `go env` output mentions:

```
GOMOD="/home/matheus/dev/go/test-go1.13beta1/go.mod"
```

Can you please include the contents of that `go.mod` file?

I can't reproduce the issue with just the `main.go` file you provided but without a `go.mod`, and I suspect it's very relevant.

**Comment by ianlancetaylor** [comment]
I think there is some confusion in your GOROOT.  Did you unpack 1.13beta1 into a clean, empty, directory?

**Comment by msalcantara** [comment]
My go.mod file
```
module github.com/msalcantara/test-go1.13beta1

go 1.13
```

**Comment by msalcantara** [comment]
I'm follow the next steps to install go1.13beta1

- ` $ go get golang.org/dl/go1.13beta1`

- `$ go1.13beta1 download`

**Comment by dmitshur** [comment]
@msAlcantara That should be successful. Can you try again with a newer version (e.g., `go1.13`) and let us know if it works?

**Comment by msAlcantara** [comment]
All works good now with new go1.13 :D
