### ISSUE TITLE
cmd/go: document that module names without dots are reserved

### ISSUE THREAD

**Issue by mvdan** [golang/go#32819]
Intuitively, most Go developers publish Go code under import paths like `foo.com/bar`, not `foo/bar`. Often, this is just to make them reachable on the internet.

However, some have avoided the `.tld` entirely when working with local-only GOPATHS and modules. And this mostly works, as long as you're careful to not clash with an existing standard library package.

For example, I recall a recent issue in this tracker (which I can't find now!) where their GOPATH build broke when upgrading the Go version, as the root path element was `plugin`, which had been added to the standard library since.

An instance of this discussion happened [last September](https://github.com/golang/go/issues/27503#issuecomment-437052752), as pointed out by @bcmills. Quoting @rsc:

> We want to allow experimentation, so we're not categorically cutting off all module statements in all contexts without dots, but anything that has to get resolved through downloading needs a dot and more generally should have a fully qualified domain name. That's how we've carved the name space between standard library and external things. I understand that pedantically the RFCs don't require dots but that's the separation we've used from very very early on with goinstall and later go get.

However, this separation isn't well documented anywhere. Even if we consider it as a warning or recommendation more than a strict rule, I think we should still mention it somewhere.

I also think we should encourage the use of `.tld` even if the module is for local use only, because of potential breakages with future Go builds. Perhaps a suggestion can be made, like `.local`.

Another advantage of strongly encouraging the use of `.tld` is that it's much easier to tell if a package is from the standard library or not. Without the separation, one would have to keep a list of all standard library package paths, which easily gets out of date. Or run `go list std`, which adds work.

Note that this doesn't need to change how `cmd/go` behaves; it's fine if a module name without a dot happens to build today.

**Comment by mvdan** [comment]
The title contains "modules", but I assume this would apply to the `GOPATH` mode too. That is, `$GOPATH/src/foo/bar` would be discouraged just like `module foo/bar`.

**Comment by andybons** [comment]
@bcmills @jayconrod

**Comment by mvdan** [comment]
Small detail I forgot - it's a dot in the first path element. `foo.com/bar` is fine as a non-reserved path, but `foo/bar.baz` technically isn't.

**Comment by mvdan** [comment]
Another small detail. It's not correct to say "all import paths without dots are reserved by the standard library", because there are a few counter-examples. Use `go list foo.go`, and you'll see `command-line-arguments`. Or do `go build -x foo.go`, and you'll see `[...]/compile -p main [...]`.

Both `main` and `command-line-arguments` are reserved, but they don't belong to the standard library. Perhaps it's correct to say that they belong to ad-hoc packages, those constructed via lists of Go files alone.

I'm also a bit surprised that the two commands above give different package paths. I think that's counter-intuitive, but maybe there's a good reason for it.

**Comment by bcmills** [comment]
Import paths without dots are reserved for the standard library _and toolchain_.

`command-line-arguments` and `main` are both synthesized by the toolchain: if you try to `import` them from some other package you're gonna have a bad time.

**Comment by mvdan** [comment]
Thanks, I like that wording. It's clear in my mind now. I'll have a look at sending a CL before the freeze is over :)

**Comment by mvdan** [comment]
I'd like to work on this this cycle. Any thoughts on where such a piece of documentation could go? I'm thinking either `go help modules` or https://golang.org/ref/mod. I imagine the latter might be best, because we don't want `go help modules` to become too long for terminals.

**Comment by jayconrod** [comment]
https://golang.org/ref/mod would be best. Ideally `go help modules` will be significantly shortened in 1.16, and it refer to that, plus some introductory docs.

**Comment by mvdan** [comment]
A separate but still related issue: tinygo is a different implementation of Go, and it adds its own standard library packages, much like `syscall/js` exists for gc's port to `js/wasm`. For example, they add packages like `machine` and `device/arm`, which I think is entirely reasonable. When one builds with tinygo, tinygo is what owns the standard library and toolchain, so it's within its right to include these extra packages.

However, `go mod tidy` gets upset, as it's not aware of those packages:

```
github.com/tinygo-org/tinygo/src/device/arm imports
  runtime/volatile: package runtime/volatile is not in GOROOT (/home/mvdan/tip/src/runtime/volatile)
github.com/tinygo-org/tinygo/src/device/nxp imports
  device/arm: package device/arm is not in GOROOT (/home/mvdan/tip/src/device/arm)
github.com/tinygo-org/tinygo/src/examples/adc imports
  machine: package machine is not in GOROOT (/home/mvdan/tip/src/machine)
```

I think, to allow modules to play nicer with alternative Go implementations, we should allow it to ignore reserved package paths that it doesn't know about.

**Comment by bcmills** [comment]
@mvdan, `machine` and `device` are _not_ reserved. TinyGo should arguably be using paths like `tinygo.org/machine` and `tinygo.org/device/arm` rather than `machine` and `device/arm`, and at that point they _could_ provide dummy or polyfill packages that could be fetched by `go mod tidy` when using the regular `go` tool.

**Comment by mvdan** [comment]
> `machine` and `device` are _not_ reserved

Hm, doesn't that contradict what we said earlier in the thread?

> Import paths without dots are reserved for the standard library and toolchain.

**Comment by bcmills** [comment]
Ah, yeah. I see what you mean. They _are_ reserved for the Go toolchain — not for non-Go toolchains.

**Comment by aykevl** [comment]
Hi all! Author of TinyGo here. You might want to read my previous comment on the issue: https://github.com/golang/go/issues/43079#issuecomment-749044855

I am well aware of this issue and I like to change it, but it will be a major breaking change so I'd like to provide a soft transition path. The proposal in https://github.com/golang/go/issues/34055 would be a big help to allow that to happen, and luckily it appears to lean towards being accepted. These reserved paths made sense when I started the project but especially now with Go modules it's becoming a compatibility issue (something which I've wanted to avoid).

**Comment by mvdan** [comment]
An upcoming change in `go mod tidy` also seems to align with this documentation change: https://go-review.googlesource.com/c/go/+/298749/

**Comment by bcmills** [comment]
I don't think we should bother setting `Standard` for packages that don't exist. Despite the names being reserved, some user code does use dotless package paths, and I would rather not explicitly set a field we're not sure about for about a package we don't know anything about.

**Comment by mvdan** [comment]
Yeah, that's fair. I was a bit on the fence about that, and I guess I can implement the "reserved" logic myself if I want to.
