### ISSUE TITLE
doc: update release notes for library support for new literals

### ISSUE THREAD

**Issue by rsc** [golang/go#32815]
The release notes don't mention all the library changes related to the new number literals.
In particular there is new printing in fmt, new parsing in strconv, math/big, and text/scanner.

I started to update the notes but there's a lot to add. Filing so I don't forget.

**Comment by odeke-em** [comment]
For the checklist, as we update release notes for this issue we can update accordingly here

- [X] textscanner -- completed by CL [183357](https://go-review.googlesource.com/c/go/+/183357)
- [ ] strconv
- [ ] math/big

**Comment by odeke-em** [comment]
Alright, all the packages on our checklist have been completed. With that I shall close this issue.

**Comment by odeke-em** [comment]
I'll reopen this until we have fully verified that fmt's release notes also document the updates; perhaps tonight when I get time.

**Comment by odeke-em** [comment]
And can now confirm that this issue is completely done.

**Comment by odeke-em** [comment]
@andybons could you please help me cherry pick https://go-review.googlesource.com/c/go/+/191578 as my two emails aren't associated to my +2's hence I can't do it. Thank you.
