### ISSUE TITLE
x/tools/gopls: optimize strategy for sending overlays to go/packages

### ISSUE THREAD

**Issue by muirdm** [golang/go#32810]
When opening files gopls still hits the expensive go/packages "overlay" case. gopls has logic to know a file is not a pure overlay after a `DidSave` event, but when starting up, Emacs only sends a bunch of `DidOpen` events. Perhaps we should track "onDisk" from the "os.Stat" we do in (*view).findFile instead of in `DidSave`?

/cc @stamblerre

**Comment by stamblerre** [comment]
I probably should have used a more descriptive name than `onDisk` - I had intended it to mean that the overlay file contents are equivalent to those on disk. I think we still need to send all of the overlays even if we know the file is on disk, in case the user has edited it without saving.

**Comment by muirrn** [comment]
Ah, ok. I misunderstood what `onDisk` meant.

Maybe we can read the files contents in `DidOpen` and set `onDisk` if they match?

It is also weird that having _any_ unsaved file causes us to hit the go/packages overlay code when opening _any_ new file. Most of the time we already know a file's package path, so it seems like go/packages could avoid doing the overlay "go list" calls if the package being loaded doesn't depend on the package with an overlay file?

**Comment by stamblerre** [comment]
I suppose we could add that check to solve the `didOpen` problem. 

The issue with the overlays is that go/packages needs to match them to their packages to figure that part out. The way we use go/packages now, we basically ask it for all of the packages under a certain directory (that's the way `file=` works under the hood), so I think it still needs to do that. I wonder if go/packages could add logic not to look at overlays if it figured out the package that file belongs to and if that package doesn't have any `go list` errors - what do you think @matloob?

**Comment by muirrn** [comment]
I tested and the above change avoids the extra "go list" calls. Thanks!

Currently gopls only passes along the overlay file names to go/packages, and it seems like the implicit assumption in go/packages is we have no idea what package those files belong to. But most of the time gopls has already loaded the package and knows what package they belong to. For example for common case:
1. User is editing `company/foo/foo.go` with unsaved changes (gopls already has already loaded package `foo` and knows path is `company/foo`)
1. User opens `company/bar/bar.go`. If `bar` doesn't transitively depend on `company/foo`, it doesn't seem like go/packages needs to do any extra overlay work involving `foo.go`.

**Comment by stamblerre** [comment]
I don't think there are any further optimizations we can make here. It would be too much complexity to strategically not send overlays to go/packages.
