### ISSUE TITLE
A shortcut for error annotation in errors package

### ISSUE THREAD

**Issue by sirkon** [golang/go#32827]
I noticed I am keep writing something like 

```go
return fmt.Errorf("create cache item: %s", err)
```

I guess a special tagged error type like [this](https://github.com/sirkon/errors/blob/master/tagged.go) would be handy in these circumstances:

```go
return errors.Tag("create-cache-item", err)
```

PS `errors.Wrap` may play this role as well, but it is a bit on heavy side, hard to log and `<file>:<line>` information may become obsolete. Tags are naturally more resistant to code changes as they are rather business-logic related entities.

**Comment by posener** [comment]
Check out [`errors.WithMessage`](https://godoc.org/github.com/pkg/errors#WithMessage).

**Comment by sirkon** [comment]
@posener indeed, thank you!
