### ISSUE TITLE
Compiler doesn't catch builtin overwrite

### ISSUE THREAD

**Issue by Happy-Ferret** [golang/go#32829]
### What version of Go are you using (`go version`)?

1.12.5

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

windows_amd64

### What did you do?

https://play.golang.org/p/q64y6jcU9n4

I added a function called `delete`, replicating the signature of the builtin of the same name.

### What did you expect to see?

The compiler should throw an error akin to `delete is a builtin`.

### What did you see instead?

The code compiles cleanly, leading to unexpected behavior during run-time.

**Comment by mvdan** [comment]
This is how pre-declared identifiers work; they can be replaced in a package or function block by another declaration. See https://golang.org/ref/spec#Predeclared_identifiers.

**Comment by Happy-Ferret** [comment]
Thanks for the spec link!

Interesting. One would assume this is considered an anti-pattern, a source of otherwise easily avoidable software faults.

**Comment by ianlancetaylor** [comment]
This approach permits us to add new built-in functions without breaking existing code.
