### ISSUE TITLE
x/tools/gopls: frequent "expected full AST […], returned trimmed" failures in builders

### ISSUE THREAD

**Issue by bcmills** [golang/go#32832]
I've been looking through flakes on the [build dashboard](https://build.golang.org), and noticed a pattern in the `x/tools/internal/lsp` tests. They seem to fail frequently with error messages of the form `expected full AST for file:///tmp/workdir/tmp/[…].go, returned trimmed`.

Examples:
https://build.golang.org/log/035d6f57a677b538aa7bcbab8e4d959d225896b3
https://build.golang.org/log/bd47b4f273b8fba6536cbb47257a2340c0575bad
https://build.golang.org/log/035d6f57a677b538aa7bcbab8e4d959d225896b3
https://build.golang.org/log/2d45e4b10c7e990d922b9606b99db59c4d10635c
https://build.golang.org/log/008b9f9c6839ab16253155c23b5f22f5df9a2222

CC @stamblerre @ianthehat

**Comment by bcmills** [comment]
It's not clear to me whether this one is related or not: a `no AST for` rather than `expected full AST`.
https://build.golang.org/log/13d5da81654a025a3bf86d38b616d7936a0788f2

**Comment by stamblerre** [comment]
There are some race conditions in `gopls` but we are working on a significant rewrite, so hopefully those flakes will go away once those are in.

**Comment by stamblerre** [comment]
This issue is fairly old and we have resolved the races between full/trimmed ASTs, so I think this can be closed now.
