### ISSUE TITLE
x/review/git-codereview: tests fail with "Permission denied" on certain builders

### ISSUE THREAD

**Issue by bcmills** [golang/go#32836]
It's not obvious to me whether this one is a builder misconfiguration or a missing check and `Skip` in the tests, but the `golang.org/x/review/git-codereview` tests consistently fail on the `illumos-amd64-joyent` builder.

https://build.golang.org/log/8e941dad2bba091bf6494b1702b1865b8723fbba:

```
--- FAIL: TestLoadAuth (0.35s)
    util_test.go:242: in git-client/, ran [git commit -m msg
        
        Change-Id: I123456789
        ] with git version 2.2.1
        :
        exit status 1
        fatal: cannot exec '.git/hooks/pre-commit': Permission denied
```

and many similar failures.

**Comment by bcmills** [comment]
Same failure mode on `dragonfly-amd64`.
https://build.golang.org/log/9a3d9b0108508ecf8d760fb3ff008cdbea2be4e6

**Comment by bcmills** [comment]
CC @tdfbsd

**Comment by tdfbsd** [comment]
How do I force this particular test to run?

**Comment by bcmills** [comment]
@tdfbsd, if you just run `go test golang.org/x/review/git-codereview/...` that should do the trick.

**Comment by tdfbsd** [comment]
The builder is running as root and for some reason that's the problem. When I run it as a normal user, it works.

**Comment by tdfbsd** [comment]
I can't think of why running as root would cause this problem, but it's 100% reproducible.

**Comment by bcmills** [comment]
Aha, I think it's a bug in the test here:
https://github.com/golang/review/blob/5934012ba8014dec70c822aae374611bca0d7107/git-codereview/util_test.go#L162-L173

Probably when running as root those hooks aren't created by any other means, so the test creates its own hooks — but the `write` helper-function sets permission `0666` instead of something more reasonable for an executable hook (say, `0755`).
