### ISSUE TITLE
flag package misleading msg on parsing issue

### ISSUE THREAD

**Issue by wa2nfn** [golang/go#32830]
go version go1.12 windows/amd64

ISSUE 1
var minWordLen = flag.Int("min", 5, "Minimum word length.\n")
var maxWordLen = flag.Int("max", 5, "Maxmum word length, >= min.\n")
var filePtr = flag.String("file", "afile.txt", "input data file\n")

executing in bash: ./program.exe -min 1 -max 4 -file book.txt
Above works fine.
Fat finger and forget the "-" for the max option, and get a misleading error about: -file book.txt not found. Of course the file is present since reedit of command line works.

Was expecting some better message about garbage option data, of even that the int for min was invalid - that would have pointed the the error area better.

ISSUE 2 (maybe a bash issue and not Go?)
Run the command  and get output to stdout, then try to redirect like:

 ./program.exe -min 1 -max 4 -file book.txt -suffix 2
Above works fine.

./program.exe -min 1 -max 4 -file book.txt -suffix 2>OUT.file
No space before redirect, display help (option data), unexpected 

Edit and add the space works fine.

**Comment by ianlancetaylor** [comment]
Your ISSUE 2 is just how the Unix shell works.  `2>OUT.file` redirects file descriptor 2 to `OUT.file`, and the `2` is not passed to the program.  There is no Go problem there.  (In general, please file unrelated problems as separate issues on the issue tracker.  Thanks.)

For ISSUE 1, the error you mention is presumably coming from your program.  I don't see why it would be coming from the flag package.  Flag parsing stops before the first non-flag argument, which in this case would be `max`.  The remaining arguments `4 -file book.txt` will all be passed to your program as normal non-flag arguments accessible via `os.Args`.  Can you suggest what the flag package could do differently here?

**Comment by wa2nfn** [comment]
Issue 1: I agree ;-) this is what retirement does to you, I forgot cmdline
order of evaluation

2 Bugs in one report - forgive me, 35 years at Bell Labs we DID put
multiple issues in a report IF they were tightly related  to the same
code.I'll play by your rules.

Issue 2: Hummm.  I expected the cmdline to be parsed with some regex
findall/split based on something like -[A-Za-z](\s+|=) thus allowing for
all proper options to be evaluated and the left over "max 4" being passed
to the program which would be easy to decipher and err on.
But I'll cope.

Lastly a request? Why not allow an "or" in the option name like "n|number"
as we often did in shell case statements to accommodate power users as well
as novices?

Nice pkg by all means, especially the help text in the declaration and the
free formatting of help output. I've filed 100's of bugs in my career in
those area alone which would be much less likely,and certainly easier ti fix
this way.

Please close the report, blame my older gray matter.

**Comment by ianlancetaylor** [comment]
You can define multiple flags with the same name using `flag.StringVar` and the like.  I can't recall ever seeing the idea of `n|number` before.  I'm not sure we could make such a change today.
