### ISSUE TITLE
x/net/proxy: TestDial persistently failing on js-wasm builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#32842]
The test for `golang.org/x/net/proxy` is persistently failing on the `js-wasm` builder.

If it is not expected to pass, it should be skipped to avoid masking more serious bugs.

https://build.golang.org/log/c1cfc25dcb267d98777f1b08f6f3842f329d4fa1:
```
--- FAIL: TestDial (0.02s)
    --- FAIL: TestDial/DirectWithCancel (0.00s)
        dial_test.go:35: dial tcp :1: Connection refused
    --- FAIL: TestDial/DirectWithTimeout (0.00s)
        dial_test.go:54: dial tcp :3: Connection refused
FAIL
FAIL	golang.org/x/net/proxy	4.817s
```

**Comment by bcmills** [comment]
CC @dweomer @bradfitz @neelance

**Comment by agnivade** [comment]
I think they should be skipped. Dial tests are not supported in js. As is evident from `net/dial_test.go`

**Comment by dweomer** [comment]
@agnivade wrote:

> I think they should be skipped. Dial tests are not supported in js. As is evident from the build tag in `net/dial_test.go`

thanks for this pointer, i will submit a fix

**Comment by dweomer** [comment]
So I found https://github.com/golang/go/blob/ef9217e7bd9c854e4f8d2d79ff8aec550130cbc4/src/net/dial_test.go#L5 which added the skip when wasm/js support was added last year-ish. Looking over x/net it seems there should be more failures. What is interesting is that `TestDial()` is only failing with `Direct*` passes that actually attempt a connection to localhost via IP. The `internal/socks` stuff should fail as well but it is using `internal/nettest#NewLocalListener`.

**Comment by agnivade** [comment]
My guess is that is because `sockstest.Server.TargetAddr` returns a fake address.

```go
// TargetAddr returns a fake final destination address.
//
// The returned address is only valid for testing with Server.
func (s *Server) TargetAddr() net.Addr {
	a := s.ln.Addr()
	switch a := a.(type) {
	case *net.TCPAddr:
		if a.IP.To4() != nil {
			return &net.TCPAddr{IP: net.IPv4(127, 0, 0, 1), Port: 5963}
		}
		if a.IP.To16() != nil && a.IP.To4() == nil {
			return &net.TCPAddr{IP: net.IPv6loopback, Port: 5963}
		}
	}
	return nil
}
```

You will see in the tests that the port returned is always `5963`.

In general, `net.Listen` at a kernel assigned port does not work in wasm

```go
func main() {
	l, err := net.Listen("tcp4", "127.0.0.1:0")
	if err != nil {
		panic(err)
	}
	defer l.Close()
	fmt.Println(l.Addr().String())
}
```

gives - `127.0.0.1:1`

So anything that dials at a listener listening at `127.0.0.1:0` will fail.

**Comment by dweomer** [comment]
Turns out that not fully honoring the listener address, aka knowing it is a "local" address and so providing an empty string for the host portion of the address was the cause of this problem. I will submit my fix as it is more explicitly correct but this seems like a gap in the wasm/js networking code?

**Comment by dweomer** [comment]
```
$ GOOS=js GOARCH=wasm go test -v ./proxy/...
=== RUN   TestDial
=== RUN   TestDial/DirectWithCancel
=== RUN   TestDial/DirectWithTimeout
=== RUN   TestDial/DirectWithTimeoutExceeded
=== RUN   TestDial/SOCKS5
=== RUN   TestDial/SOCKS5WithTimeout
=== RUN   TestDial/SOCKS5WithTimeoutExceeded
--- PASS: TestDial (0.01s)
    --- PASS: TestDial/DirectWithCancel (0.00s)
    --- PASS: TestDial/DirectWithTimeout (0.00s)
    --- PASS: TestDial/DirectWithTimeoutExceeded (0.00s)
    --- PASS: TestDial/SOCKS5 (0.00s)
    --- PASS: TestDial/SOCKS5WithTimeout (0.00s)
    --- PASS: TestDial/SOCKS5WithTimeoutExceeded (0.00s)
=== RUN   TestPerHost
=== RUN   TestPerHost/Dial
=== RUN   TestPerHost/DialContext
--- PASS: TestPerHost (0.00s)
    --- PASS: TestPerHost/Dial (0.00s)
    --- PASS: TestPerHost/DialContext (0.00s)
=== RUN   TestFromEnvironment
--- PASS: TestFromEnvironment (0.00s)
=== RUN   TestFromURL
--- PASS: TestFromURL (0.00s)
=== RUN   TestSOCKS5
--- PASS: TestSOCKS5 (0.00s)
=== RUN   TestFromEnvironmentUsing
--- PASS: TestFromEnvironmentUsing (0.00s)
PASS
ok      golang.org/x/net/proxy  1.099s
```
