### ISSUE TITLE
x/tools/gopls: language server stops working at valid file with "has errors, skipping type-checking"

### ISSUE THREAD

**Issue by inliquid** [golang/go#32855]
VS Code, see screenshot:
![изображение](https://user-images.githubusercontent.com/6797881/60387250-e180ab00-9aa8-11e9-84bc-6d3854a96d77.png)
These messages appear infinitely with `gopls` simply not working. File is valid, btw (but even if it was not, how am I supposed to work? non-sense if it can only work with files with no errors).

Tried both `@latest` and `@master`.

**Comment by stamblerre** [comment]
We should probably improve that error message, but that means that there were errors determining the files and dependencies for the package. Are you opening VSCode from the root of your module?

**Comment by inliquid** [comment]
Yes, VS Code workspace is at the root of module.

**Comment by stamblerre** [comment]
I know you updated to master, as per our discussion on your other issue. Do you still see these errors on master? If so, what is the output of `go list -e -json -compiled -test /absolute/path/to/your/package`?

**Comment by inliquid** [comment]
I'll test and report.

**Comment by zouyee** [comment]
```
for GOROOT=/usr/local/go GOPATH=/Users/xxx/Code/golang GO111MODULE=on PWD=/Users/xxx/Code/golang/src/k8s.io/kubernetes go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "/Users/xxx/Code/golang/src/k8s.io/kubernetes/pkg/kubelet/lifecycle", stderr: <<>>

[Error - 3:12:38 PM] Request textDocument/codeAction failed.
  Message: GetAST: unable to check package for file:///Users/xxx/Code/golang/src/k8s.io/kubernetes/pkg/kubelet/lifecycle/predicate.go: package k8s.io/kubernetes/pkg/kubelet/lifecycle has errors, skipping type-checking
```
same issue

**Comment by stamblerre** [comment]
@zouyee: Please open a new issue, along with the information described [here](https://github.com/golang/go/wiki/gopls#troubleshooting). In your case, please also add the output of `go list -e -json -compiled -test /absolute/path/to/your/package`. Thanks!

**Comment by stamblerre** [comment]
@inliquid: Is this still an issue for you?

**Comment by inliquid** [comment]
@stamblerre it is.

**Comment by stamblerre** [comment]
@inliquid: What is the output of `gopls -rpc.trace -v check /path/to/file.go`?

**Comment by inliquid** [comment]
I will check when I have time to.

**Comment by cardonator** [comment]
I'm having a similar problem to the above in gopls with a module package.

If I run `gopls -rpc.trace -v check /home/bcardon/dev/app/package/base.go` the output I get is:
```2019/08/24 12:07:45 Info:Build info
----------
version v0.1.0, built in $GOPATH mode

Go info
-------
go version go1.12.9 linux/amd64

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/bcardon/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/bcardon/go"
GOPROXY=""
GORACE=""
GOROOT="/snap/go/4301"
GOTMPDIR=""
GOTOOLDIR="/snap/go/4301/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build355155299=/tmp/go-build -gno-record-gcc-switches"
2019/08/24 12:07:45 Error:unable to check package for file:///home/bcardon/dev/app/package/base.go: no packages found for /home/bcardon/dev/app/package/base.go
2019/08/24 12:07:46 Error:unable to check package for file:///home/bcardon/dev/app/package/base.go: no packages found for /home/bcardon/dev/app/package/base.go
2019/08/24 12:07:46 Error:failed to deliver diagnostic for file:///home/bcardon/no%20packages%20found%20for%20/home/bcardon/dev/app/package/base.go: stat /home/bcardon/no packages found for /home/bcardon/dev/app/package/base.go: no such file or directory
check: timed out waiting for results from file:///home/bcardon/dev/app/package/base.go```

**Comment by stamblerre** [comment]
@cardonator: it looks like you are also using an old version of gopls. You can upgrade by running “GO111MODULE=on go get golang.org/x/tools/gopls@latest”.

**Comment by cardonator** [comment]
Ah, thanks for the command. I could tell I was on an old version but not why it wasn't updating. :+1:

**Comment by stamblerre** [comment]
This issue seems to be fairly old and a lot has changed in `gopls` since it was filed. I'm going to close it, but please open a new issue if you encounter problems with `gopls`.
