### ISSUE TITLE
x/sys: Please add release or tags

### ISSUE THREAD

**Issue by FSjursaether** [golang/go#32868]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.10.3 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
S C:\git\go\src\faservices\tools\cleanup-ptk-jobs> go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xxx\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\git\go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\zzz\AppData\Local\Temp\go-build025826170=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
N/A
We use scanning tools for the code development that requires a base version of the code to be defined. Please consider adding a tag or release version to GitHub for the golang repositories (x/sys, x/tools, x/crypto, x/net, x/oauth2).

### What did you expect to see?
Tag or release version in GitHub.

### What did you see instead?
No tags or release version.

**Comment by ALTree** [comment]
Thanks for the request.

This is a dup of #21324 (x/all: start tagging versions); note that it's on hold:

> On hold until Go 1.11 and/or Go 1.12. At least until we have tooling ready and some experience with said tooling.

I'm closing this thread in favour of the older one.
