### ISSUE TITLE
cannot use txBldr (type "github.com/x/auth/client/txbuilder".TxBuilder) as type "github.com/cosmos/cosmos-sdk/x/auth/client/txbuilder".TxBuilder

### ISSUE THREAD

**Issue by ying2025** [golang/go#32865]
two different project quote same file, but the file is in different package, so project1 cannot use package1/x as package2/x
how to solve it

**Comment by mvdan** [comment]
Please read https://golang.org/ref/spec#Type_identity, or one of the many answered questions online like https://stackoverflow.com/questions/52174644/golang-cannot-use-type-as-type-in-argument.

Long story short, named types from different packages are different. If the types are identical, you can convert from one to another.
