### ISSUE TITLE
x/tools/gopls: support all features on the command line

### ISSUE THREAD

**Issue by stamblerre** [golang/go#32875]
`gopls` features like find references, rename, etc. should work on the command line. Support for them should be added to `internal/lsp/cmd`. Right now, only definition and format are supported.

**Comment by hartzell** [comment]
If no one's working on it, I'll take a swing at adding rename.  Looks like it's a matter of adding an `internal/lsp/cmd/rename.go` that defines a `type rename struct {...}` and fleshing out a `Run` method for it.  Looks like the rename machinery wants to work from a position, seems like I can mimic/steal what the `query definition` subcommand uses.  Anything I'm missing?

**Comment by hartzell** [comment]
> I'll take a swing at adding rename

This has been merged, see https://github.com/golang/tools/pull/157.  Great support for a first time contributor.

**Comment by stamblerre** [comment]
@rentziass: Absolutely, please do! Feel free to reach out with any questions here or on the Gophers Slack (https://invite.slack.golangbridge.org/).

**Comment by kalmanb** [comment]
@stamblerre any others need implementation?

**Comment by stamblerre** [comment]
Anything that doesn't have a test in this file is available: https://github.com/golang/tools/blob/e4d7c6f25b8e08c4784d6585835a053ae0ad53bb/internal/lsp/cmd/test/cmdtest.go#L41. I would suggest Import or SuggestedFix as a useful next feature.

**Comment by kalmanb** [comment]
I'll also take a look at `Import` and `Link`

**Comment by rentziass** [comment]
I'll keep going with `SignatureHelp` and `Symbol` then :)

**Comment by rentziass** [comment]
Continuing with `FoldingRange` and `Highlight` if no one's on them!

**Comment by rhnvrm** [comment]
Taking up prepare_rename

**Comment by rentziass** [comment]
Moving on to `Completion`

**Comment by jbszczepaniak** [comment]
I will jump into `Highlight`

**Comment by jbszczepaniak** [comment]
I will jump into `Highlight`

**Comment by stamblerre** [comment]
@jbszczepaniak: I believe that Highlight has already been handled by https://go-review.googlesource.com/c/tools/+/207291. I just haven't had a chance to review it yet.

**Comment by jbszczepaniak** [comment]
O, I see, right. It seems that these are yet to be done.

- Completion
- CompletionSnippet
- UnimportedCompletion
- DeepCompletion
- FuzzyCompletion
- CaseSensitiveCompletion
- RankCompletion

I will take from the list - `Completion`

**Comment by rentziass** [comment]
@jbszczepaniak I'm currently working on `Completion`, see a couple of comments above :)

**Comment by jbszczepaniak** [comment]
🤦‍♂ ok. I believe this is a list (right?):

-    CompletionSnippet
-    UnimportedCompletion
-    DeepCompletion
-    FuzzyCompletion
-    CaseSensitiveCompletion
-    RankCompletion

Thus I will take `CompletionSnippet`

**Comment by stamblerre** [comment]
@rentziass: Do you intend to add all of the completion related test code in your CL? In that case, I believe that this issue could be considered done.

**Comment by rentziass** [comment]
I'd surely like to try :)

**Comment by jbszczepaniak** [comment]
O, In that case I will move to something else.

**Comment by daisuzu** [comment]
I'll do workspace/symbol.

**Comment by msAlcantara** [comment]
Anyone is working on `Completion`? If not I can try to implement.

**Comment by stamblerre** [comment]
No, I don't believe anyone has worked on completion, so please feel free to work on it.

**Comment by findleyr** [comment]
Circling back, I don't think we should do this.

Supporting features on the command line has a real cost:
 - we need to implement and maintain versions of our test runner for each feature
 - we increase our API surface area
 
But on the other hand, I never see requests for additional command-line features. So absent specific requests, I think we should not change the CLI.

Tentatively closing this issue as it doesn't seem actionable. If you are reading this and wish that gopls had a specific command-line feature, please file a separate issue.
