### ISSUE TITLE
Regex: Underscore (_) makes replace group not found

### ISSUE THREAD

**Issue by mikhailkolesnik** [golang/go#32885]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Assuming playground uses it - yes: https://play.golang.org/p/THIwTK5zXpW

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/...Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/.../.../gocode"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/th/6k5d1zsx18z5dnzlrsrskxgc0000gp/T/go-build913576916=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

https://play.golang.org/p/THIwTK5zXpW
```
package main

import (
	"fmt"
	"regexp"
)

func main() {
	r := regexp.MustCompile(`(\w+)`)
	fmt.Println(r)

	orig := "somerandomtext"
	fmt.Println(r.MatchString(orig))

	fmt.Println(r.ReplaceAllString(orig, "$1"))
	fmt.Println(r.ReplaceAllString(orig, "$1_"))
	fmt.Println(r.ReplaceAllString(orig, "$1 _"))
}
```

### What did you expect to see?

second output should produce `somerandomtext_` but produces nothing

```
(\w+)
true
somerandomtext
somerandomtext_
somerandomtext _
```

### What did you see instead?

```
(\w+)
true
somerandomtext

somerandomtext _
```

RE2 issue: https://github.com/google/re2/issues/209

**Comment by ianlancetaylor** [comment]
The docs for `regexp.ReplaceAllString` say that it interprets `$` as in `Expand`.  The docs for `Expand` say "a variable is denoted by a substring of the form $name or ${name}, where name is a non-empty sequence of letters, digits, and underscores."   The names are for use with the `(?P<name>re)` syntax.  So when you write `$1_`, `ReplaceAllString` is substituting the value of the variable `1_`, which is empty.  You need to write `${1}_`.
