### ISSUE TITLE
regexp: Named captures should appear in a hashmap

### ISSUE THREAD

**Issue by mcandre** [golang/go#32881]
The regexp API expects users to perform dangerous index arithmetic between two different arrays, defeating the purpose of naming capture groups. Let's provide a standard method for retrieving capture groups from regexp results in the form of hashmaps, using the names specified in the regular expression.

**Comment by cespare** [comment]
See #32420.

**Comment by bcmills** [comment]
If you want to propose a specific API, please propose a specific API (with details and examples and so on).

In the meantime, #32420 is a concrete proposal that aims to address what I believe is the same underlying problem.

**Comment by bcmills** [comment]
Duplicate of #32420
