### ISSUE TITLE
cmd/go: go version is added even when there are no other changes

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#32889]
Under Go 1.12.6, compiling [this program](https://play.golang.org/p/TQdGP4ZSD1f) will leave the `go.mod` file untouched. Under Go tip (go version devel +d410642f49 Mon Jul 1 21:30:23 2019 +0000 linux/amd64), a `go 1.13` line is added to the end of the `go.mod` file.

This is annoying when compiling older Go programs, as it always leaves the repository dirty, so doing:

     git checkout oldversion
     go build

will require a `git reset --hard`, even though the `go.mod` file was fully resolved.

I'd like to suggest that if the versions remain unchanged (as they should with MVS), the `go.mod` file should remain unchanged too.

**Comment by bcmills** [comment]
That's what we did for #30790, but not how the `go` directive was intended to work. See #31960.
