### ISSUE TITLE
nil type assertion passed

### ISSUE THREAD

**Issue by yonghenghuanmie** [golang/go#32888]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

no

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Administrator\go;E:\gocode;
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build640794018=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

player := scene.GetPlayerByPos(data.GetPos()).(*WinthreePlayer)
GetPlayerByPos() return interface Player,and actually is *WinthreePlayer.
When GetPlayerByPos() return nil,I looked up some unofficial document(not seen any of this in official document),type assertion should be failed.But actually it's passed!

### What did you expect to see?

panic

**Comment by mvdan** [comment]
Please provide a full program to reproduce the bug.

Also, have you asked other Go developers in forums first? Oftentimes, these end up being mistakes in the user's code and not the compiler or runtime.

**Comment by yonghenghuanmie** [comment]
> 
> 
> Please provide a full program to reproduce the bug.
> 
> Also, have you asked other Go developers in forums first? Oftentimes, these end up being mistakes in the user's code and not the compiler or runtime.

                                player := scene.GetPlayerByPos(data.GetPos()).(*WinthreePlayer)
				logger.Logger.Errorf("??????????????????%v????????????????", player)
				if player != WinthreeNilPlayer {
					player.Coin = data.Coin
					//结算了以后 要初始化当前机器人的暗牌值和勇气值
					if player.IsRobot() {
						player.InitAICharacter(true)
					}
				}
				logger.Logger.Errorf("??????????????????%v????????????????", player)
				//结算了以后 要初始化当前机器人的暗牌值和勇气值
				if player.IsRobot() {
					player.InitAICharacter(true)
				}
No,but when second player.IsRobot() crashed,I add two logger that shows player is nil.
The entire project is multi-process,and this situation only reappear in given way by chance.So what should I provide?all program files && describe how to reproduce?

**Comment by mvdan** [comment]
Then you likely have a data race. There's not much that we can do here without being able to reproduce a bug. We can take guesses, but we can't debug your code.

**Comment by yonghenghuanmie** [comment]
I write a demo and do reproduce this issue.
package main

type base interface {
	do()
}

type deriver struct{}

func (this *deriver) do() {

}

func getBase() base {
	//return nil
	var temp *deriver = nil
	return temp
}

func main() {
	t := getBase().(*deriver)
	t.do()
}
So nil type assertion should failed no matter what kind of type or interface,right?

**Comment by agnivade** [comment]
Please see - https://golang.org/doc/faq#nil_error

**Comment by yonghenghuanmie** [comment]
> 
> 
> Then you likely have a data race. There's not much that we can do here without being able to reproduce a bug. We can take guesses, but we can't debug your code.

thank you

**Comment by yonghenghuanmie** [comment]
> 
> 
> Please see - https://golang.org/doc/faq#nil_error

thank you
