### ISSUE TITLE
encoding/json: addrMarshalerEncoder does not respect SetEscapeHTML

### ISSUE THREAD

**Issue by nkovacs** [golang/go#32896]
### What version of Go are you using (`go version`)?

1.12.5 (playground)

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

play.golang.org

### What did you do?

https://play.golang.org/p/lt-Mky4vAtq

```go
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
)

type T1 int
type T2 int

func (t T1) MarshalJSON() ([]byte, error) {
	return []byte(`"<script>T1</script>"`), nil
}

func (t *T2) MarshalJSON() ([]byte, error) {
	return []byte(`"<script>T2</script>"`), nil
}

func main() {
	var t struct {
		T1 T1
		T2 T2
	}

	var out bytes.Buffer
	encoder := json.NewEncoder(&out)
	encoder.SetEscapeHTML(false)

	err := encoder.Encode(&t)
	if err != nil {
		panic(err)
	}

	fmt.Println(out.String())
}
```

### What did you expect to see?

```
{"T1":"<script>T1</script>","T2":"<script>T2</script>"}
```

### What did you see instead?

```
{"T1":"<script>T1</script>","T2":"\u003cscript\u003eT2\u003c/script\u003e"}
```

I noticed this inconsistency while studying the code of encoding/json, and I believe this is an edge case that was missed in https://github.com/golang/go/issues/14749.

**Comment by bcmills** [comment]
CC @cespare @dsnet @mvdan

**Comment by mvdan** [comment]
Thanks - this seems like a simple fix, so I've sent a CL with a test.
