### ISSUE TITLE
import "github.com/chaosblade-io/chaosblade/exec/os/bin" is a program, not an importable package

### ISSUE THREAD

**Issue by jievince** [golang/go#32893]
$ go version
1.12.6

I have a common.go file in the exec/os/bin/ directory, and its package name is bin. Then I imported the package bin in exec/os/bin/burncpu/burncpu.go, and I reported this error.

**Comment by AlexRouSg** [comment]
`exec/os/bin/` is `package main`. You cannot import `package main` as the message says.

**Comment by mvdan** [comment]
What @AlexRouSg said.

**Comment by jievince** [comment]
@AlexRouSg @mvdan  Hi, thanks for your reply.  I am still confused.
(1). The package name I defined for the common.go file located in the exec/os/bin directory is bin (that is, its direct directory name). Why do you say its package name main?
(2). Is this because the golang syntax specifies that the package name of the file in the bin directory must be main?
(3). Then, if I want to refer to the function in exec/os/bin/.common in exec/os/bin/burncpu/burncpu.go, how do I import the package?

**Comment by mvdan** [comment]
From files like `burnio.go`, you can clearly see `package main`.

If you have questions, look up tutorials and documentation online. And if you have questions, see https://github.com/golang/go/wiki/Questions.

**Comment by jievince** [comment]
Not understand.

**Comment by AlexRouSg** [comment]
See: https://github.com/jievince/chaosblade/blob/master/exec/os/bin/common.go#L1

Package name is not determined by the path, that is the import path. Package names are determined by the line `package main`

**Comment by jievince** [comment]
Hi @AlexRouSg ,the previous common.go file is like this:
`package bin

import (
	"os"
	"fmt"
)

const ErrPrefix = "Error:"

func printAndExitWithErrPrefix(message string) {
	fmt.Fprint(os.Stderr, fmt.Sprintf("%s %s", ErrPrefix, message))
	os.Exit(1)
}

func printErrAndExit(message string) {
	fmt.Fprint(os.Stderr, message)
	os.Exit(1)
}

func printOutputAndExit(message string) {
	fmt.Fprintf(os.Stdout, message)
	os.Exit(0)
}`

**Comment by AlexRouSg** [comment]
Then you are still using the original package and not the edited one.
