### ISSUE TITLE
x/tools/gopls: not understanding package_test

### ISSUE THREAD

**Issue by jadekler** [golang/go#32906]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/usr/local/google/home/deklerk/dev/go1.12.5.linux-amd64/go/bin"
GOCACHE="/usr/local/google/home/deklerk/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/google/home/deklerk/workspace/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/google/home/deklerk/dev/go1.12.5.linux-amd64/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/google/home/deklerk/dev/go1.12.5.linux-amd64/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/usr/local/google/home/deklerk/workspace/google-cloud-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build430311602=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Using vscode with Go@0.11.0 plugin. Have package `bigtable`, create a new file `conformance_test.go` with `package bigtable_test` declaration.

### What did you expect to see?

No problems in editor.

### What did you see instead?

Red squiggly under `package` with text:

```
package bigtable_test; expected bigtable LSP
```

**Comment by jadekler** [comment]
FYI, this is doubly annoying because it prevents any other interpretation of the file. So, unless I rename this `package bigtable`, there is no LSP on the entire file, rendering my editor mostly-useless.

**Comment by stamblerre** [comment]
What version of `gopls` are you using (`gopls version`)? What happens when you save the file - does the error ever go away?

**Comment by jadekler** [comment]
Not sure:

```
$ gopls version
no module information, gopls not built in module mode
```

So, I blew that binary away, reset everything I could in vscode, and performed:

```
go get golang.org/x/tools/gopls@latest
```

Now it seems to accept `bigtable_test`. Huzzah!

**Comment by jadekler** [comment]
Whoops, spoke too soon. Now I get an error at the first character of the file with the following:

```
file:///usr/local/google/home/deklerk/workspace/google-cloud-go/bigtable/conformance_test.go is not part of a package LSP
```

**Comment by ogimenezb** [comment]
Same problem here with VSCode

```
$ gopls version
golang.org/x/tools/gopls v0.1.0
    golang.org/x/tools/gopls@v0.1.1 h1:mU/O8r53RjzdZfkqmFOX4iEt8PJxTPXyLdiuQNa27OE=
```

**Comment by stamblerre** [comment]
Can you try reproducing this on master (`go get -u golang.org/x/tools/gopls@master`)? We will likely be tagging a new version of `gopls` soon, but for now, the fix may already be on master.

**Comment by ogimenezb** [comment]
Hi,

Still the same problem.

`/const.go is not part of a package LSP`

```
$ gopls version
golang.org/x/tools/gopls v0.1.1
    golang.org/x/tools/gopls@v0.1.2-0.20190708203411-c8855242db9c h1:qFHl9H1pFOvam5c7rRNiSVPuASu5sS/VNZUj7KNAyGI=
```

**Comment by ogimenezb** [comment]
I have been doing some more testing.

If I have a package and have, for example
```
argon.go -> package passwords
argon_test.go -> package passwords_test
```
Work well, but If I have the same and is using cgo, Then I have the problem
As an example I add:
```
package passwords

/*

#cgo CFLAGS: -std=gnu99
*/
import "C"
```
argon.go is not part of a package LSP

**Comment by jadekler** [comment]
Seems to work on master for me.

**Comment by stamblerre** [comment]
@ogimenezb: Your issue sounds more like https://github.com/golang/go/issues/31561.
I will close this issue in favor of that one.
