### ISSUE TITLE
lsp: LSP should still suggest results even if import not present

### ISSUE THREAD

**Issue by jadekler** [golang/go#32908]
If I start typing `json.`, I expect to get results from all `json` packages (probably ranked/ordered somehow, with any imports being at the top). Pressing enter on a result from an unimported package should import that package.

However, LSP does not suggest results from anything you have yet to import. This greatly inhibits the code-complete functionality:

- First I have to go find the exact package of the thing I'm looking for (already the major purpose of code completion for me is lost)
- I have to manually add it
- _I have to be careful not to save file in vscode, which will run goimports, which will remove my import because nothing uses it_
- Perform auto-complete
- Save

This is not an ideal situation. It would be greatly alleviated if I could have just use autocomplete to search for the method I'm looking for across all packages.

I realize this is probably hard in a GOPATH-less world, FWIW.

**Comment by stamblerre** [comment]
We are working on this. See https://github.com/golang/go/issues/31906.
Closing as a duplicate.
