### ISSUE TITLE
net: TestTCPServer flaky on macOS 10.12 builders

### ISSUE THREAD

**Issue by bcmills** [golang/go#32919]
From https://build.golang.org/log/19f0ac1d66a927076b256862638641e261489304 on the `darwin-amd64-race` builder:

```
--- FAIL: TestTCPServer (10.01s)
    server_test.go:60: skipping tcp :0<-127.0.0.1 test
    server_test.go:60: skipping tcp 0.0.0.0:0<-127.0.0.1 test
    server_test.go:60: skipping tcp [::ffff:0.0.0.0]:0<-127.0.0.1 test
    server_test.go:60: skipping tcp [::]:0<-::1 test
    server_test.go:60: skipping tcp :0<-::1 test
    server_test.go:60: skipping tcp 0.0.0.0:0<-::1 test
    server_test.go:60: skipping tcp [::ffff:0.0.0.0]:0<-::1 test
    server_test.go:60: skipping tcp [::]:0<-127.0.0.1 test
    server_test.go:60: skipping tcp :0<-127.0.0.1 test
    server_test.go:60: skipping tcp 0.0.0.0:0<-127.0.0.1 test
    server_test.go:60: skipping tcp [::ffff:0.0.0.0]:0<-127.0.0.1 test
    server_test.go:60: skipping tcp [::]:0<-::1 test
    server_test.go:60: skipping tcp :0<-::1 test
    server_test.go:60: skipping tcp 0.0.0.0:0<-::1 test
    server_test.go:60: skipping tcp [::ffff:0.0.0.0]:0<-::1 test
    server_test.go:60: skipping tcp [::]:0<-127.0.0.1 test
    server_test.go:107: dial tcp [::1]:49737: i/o timeout
FAIL
FAIL	net	23.757s
```

CC @mikioh @ianlancetaylor

**Comment by bcmills** [comment]
Compare #32534.

**Comment by bcmills** [comment]
Another `darwin-amd64-race`: https://build.golang.org/log/9b0ba4fa74c5011965aebec20f6794e1186837ce

**Comment by bcmills** [comment]
`darwin-amd64-race`: https://build.golang.org/log/87a6a195e770baea9298ed4f3b87e640700a1477

**Comment by bcmills** [comment]
Seems like we have enough of these to form a pattern.

CC @mikioh @bradfitz @ianlancetaylor

**Comment by bcmills** [comment]
`darwin-amd64-10_12`: https://build.golang.org/log/d33cf20b1cc2056d235cb49e5b504e1217eb8971

**Comment by bcmills** [comment]
https://build.golang.org/log/b1b0acc773357589c52b772d1f5064b12e1f711a

**Comment by networkimprov** [comment]
I'm shipping a Mac app with HTTP server and TLS/TCP client, both of which are always on. Should I be concerned?

**Comment by bcmills** [comment]
`darwin-amd64-race`: https://build.golang.org/log/17f5dc994f9cdbda9c3f6baf87e15a2c7c599e0d

**Comment by ianlancetaylor** [comment]
It would be interesting to know whether this ever occurs on a version of Darwin later than 10.12.

**Comment by bcmills** [comment]
Looks like it hasn't so far: `darwin-amd64-race` is [still 10.12](https://github.com/golang/build/blob/a07c53d8a3ae8fb7322b956a26b5fb6071637b46/dashboard/builders.go#L1921-L1922).

**Comment by bcmills** [comment]
That suggests that this may be the same underlying issue as #22019.
