### ISSUE TITLE
io/ioutil: WriteFile example returns "No such file or directory" because testdata does not exist

### ISSUE THREAD

**Issue by KolesnikDmitriy** [golang/go#32916]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.12.6
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
https://play.golang.org/
</pre></details>

### What did you do?

Run example in https://golang.org/pkg/io/ioutil/#WriteFile

### What did you expect to see?

Expected file created

### What did you see instead?

2009/11/10 23:00:00 open testdata/hello: No such file or directory

Program exited.

**Comment by AlexRouSg** [comment]
Does the folder exist?

**Comment by av86743** [comment]
Indeed, that link https://golang.org/pkg/io/ioutil/#WriteFile above, which offers much better `func `**`TempFile`** choice, also with examples, deserves an issue on its own.

**Comment by agnivade** [comment]
Thanks. The code in the example assumes a `testdata` directory. Since it cannot find it, it throws an error. It worked so far because the source tree always had a `testdata` directory.

You are welcome to send a patch.

**Comment by darkLord19** [comment]
https://github.com/golang/go/tree/master/src/io/ioutil/testdata Isn't it still present?

**Comment by cuonglm** [comment]
@darkLord19 Examples are run in separate environment, without the directory structure as in source code. `ReadFile` has the same problem as it read `testdata/hello` file.

**Comment by av86743** [comment]
Regarding https://golang.org/cl/185037 :

```
$ find go/src/github.com/av86743/go/src -type f -name 'example_test.go' -exec grep -e '"testdata' {} ';' -print 
	r, err := zip.OpenReader("testdata/readme.zip")
go/src/github.com/av86743/go/src/archive/zip/example_test.go
	cert, err := tls.LoadX509KeyPair("testdata/example-cert.pem", "testdata/example-key.pem")
go/src/github.com/av86743/go/src/crypto/tls/example_test.go
	content, err := ioutil.ReadFile("testdata/hello")
	err := ioutil.WriteFile("testdata/hello", message, 0644)
go/src/github.com/av86743/go/src/io/ioutil/example_test.go
$
```

**Comment by bcmills** [comment]
I believe this is a specific case of the broader issue #19825.

**Comment by fgm** [comment]
Does the fix need to bring the testdata file, or could it just read one of the few files actually available, readable and non-empty test files on the playground, currently just `/etc/group` and `/etc/hosts` ? The latter would actually be demonstrating the purpose of `ioutil.ReadFile`, without implying other changes.
