### ISSUE TITLE
wiki: PerfDashboard links broken

### ISSUE THREAD

**Issue by cep21** [golang/go#32911]
### Wiki link

https://github.com/golang/go/wiki/PerfDashboard

### Which broken links

* [in detail](https://build.golang.org/perfdetail?commit=fb3d6c1631c3f3141f33a01afb4c0a23ef0ea2cf&commit0=82f48826c6c79a3d5697d5e06cac8451f3dc3c7f&kind=builder&builder=linux-amd64-perf&benchmark=http)
* [perf detail](https://build.golang.org/perfdetail?commit=fb3d6c1631c3f3141f33a01afb4c0a23ef0ea2cf&commit0=82f48826c6c79a3d5697d5e06cac8451f3dc3c7f&kind=builder&builder=linux-amd64-perf&benchmark=http)

### Using the perf dashboard

When I click to the perf dashboard on https://build.golang.org/perf?page=6, I see many empty HTML rows and links that go to the code review.  I am unable to find performance differences.  It appears the perf dashboard may not be working as intended.

**Comment by ALTree** [comment]
The perf dashboard is unmaintained and currently not active, and it has been for a long time (a few years). We should probably note that in the wiki page.

**Comment by shivi28** [comment]
Hello @cep21, Can I pick up this task?
If yes then please guide

**Comment by ALTree** [comment]
@shivi28 If you mean editing the wiki, it was already done; the page now says:

> The perf dashboard is unmaintained and currently not active

If you mean fixing the dashboard, I'm afraid that's something that only googlers on the Go team can work on, since it runs on services they control.

**Comment by ALTree** [comment]
Since this issue is about the wiki and the page is now fixed, I would close here.

**Comment by cep21** [comment]
Hold on a minute :)

> The perf dashboard is unmaintained and currently not active

Shouldn't we just delete the page rather than leave a comment saying "Everything on this page isn't worth reading" :)

**Comment by shivi28** [comment]
yes @cep21 I think we should delete it, because its was showing that page was updated by someone 18 days ago, so it might create confusions

**Comment by ALTree** [comment]
We generally don't delete wiki pages, to avoid breaking links. 

Also the dashboard is still up (even if it's not currently working), and that wiki page does a good job at describing how it works and what it does. If at some point in the future someone fixes the dashboard, we won't have to write the wiki page from scratch. 

The description of the dashboard the wiki page has could also help restoring the dashboard in its original state in the future.

IMO a note at the top is enough to avoid any confusion.
