### ISSUE TITLE
blog: errors are values.article

### ISSUE THREAD

**Issue by isomorphisms** [golang/go#32920]
https://github.com/golang/blog/blob/master/content/errors-are-values.article#L205

> Although `bufio.Writer.Write` returns an error, that is mostly about honoring the [[https://golang.org/pkg/io/#Writer][`io.Writer`]] interface.
> The `Write` method of `bufio.Writer` behaves just like our `errWriter.write`method above, with `Flush` reporting the error

`flush` no longer appears in `io`, and `Writer`’s signature must have changed.

https://golang.org/src/io/io.go?s=3794:3855#L80

```
type Writer interface {
	Write(p []byte) (n int, err error)
}
```

**Comment by ALTree** [comment]
That part is about `bufio`, not `io`. And [`bufio.Writer`](https://golang.org/pkg/bufio/#Writer) has a Flush method.

Closing here, since the text is correct.
