### ISSUE TITLE
encoding/binary: Read fails to detect a non-pointer 'data' argument

### ISSUE THREAD

**Issue by martin-juhlin** [golang/go#32927]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
It does on play.golang.org

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/martin/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/martin/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r2/nz7__kld2qq9w4dhg19fmx5h0000gn/T/go-build214042936=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I was trying to read a value with binary.Read. That function need a pointer for the Data parameter. I was using that function faulty by passing a non pointer value to it.

```
var value int32
err := binary.Read(input, binary.LittleEndian, value)
```

https://play.golang.org/p/ZFNQ4PjM9H-

### What did you expect to see?
An error message saying that Data need to be a pointer

### What did you see instead?
No error and and my value was zero. The method doesn't do anything at all.

**Comment by bcmills** [comment]
CC @griesemer for `encoding/binary`

**Comment by vitaminniy** [comment]
Looks like `binary.Read` should return an error when passed data interface is not a pointer or slice.

`intDataSize` handles the case when dst arg is a simple/primitive value but `binary.Read` not.

**Comment by griesemer** [comment]
It is not clear to me that the CL chose the right approach. Given that the Read function panics when other conditions that _must_ be satisfied are not satisfied, it seems ok to panic in this case as well.

Marked as NeedsDecision.

**Comment by vitaminniy** [comment]
My point is that in the case when a pointer to a struct is passed and struct itself is incorrect then the reflect-related code may (or may not) panic.
It seems to me that documentation on `Read` is a little bit unclear.

**Comment by ianlancetaylor** [comment]
I think we should do the same thing we do in the fallback case, which is

```Go
	if size < 0 {
		return errors.New("binary.Read: invalid type " + reflect.TypeOf(data).String())
	}
```

**Comment by martin-juhlin** [comment]
Shouldn't the behaviour be equal to other packages? Both encoding/json and encoding/xml is returning error.
https://play.golang.org/p/o9hl4rmIUDA

**Comment by martin-juhlin** [comment]
encoding/json and encoding/xml with int32 instead of struct{} : https://play.golang.org/p/KKE6ssLsBmy

**Comment by odeke-em** [comment]
Hello @griesemer, I am just prodding you about this issue. From the precedent, it seems to be that returning an error is alright. This issue is marked for Go1.14 and there is already a CL that's just waiting for your blessing https://go-review.googlesource.com/c/go/+/184957/, please take a look and thank you.

**Comment by griesemer** [comment]
@odeke-em Thanks. On it.
