### ISSUE TITLE
path: Match support for `**`

### ISSUE THREAD

**Issue by alessandrozucca** [golang/go#32938]
Currently `path.Match` only supports `*` would be nice if it supported `**` as well.

This is similar to https://github.com/golang/go/issues/11862 but this is only about only the `path` package

**Comment by ianlancetaylor** [comment]
I think that if we change either `path.Math` or `filepath.Match`, we should change both.  For them to be different would just be unnecessarily confusing.  So closing this as a dup of #11862.

**Comment by alessandrozucca** [comment]
Yes, that's true but at the same time, they are two different packages - should it not be possible to update them separately?

**Comment by ianlancetaylor** [comment]
We can update them separately in the sense of doing it as two different patches.  But the decision as to whether to update them or not should be made for both packages.  And if we do decide to update them then both packages should be updated in the same release.
