### ISSUE TITLE
x/net/icmp: ListenPacket shouldn't panic  for invalid network

### ISSUE THREAD

**Issue by songjiayang** [golang/go#32933]
I write some test for `x/net/icmp`,  there is my code:
```
package main

import (
	"log"

	"golang.org/x/net/icmp"
)

func main() {
	conn, err := icmp.ListenPacket("ip4", "0.0.0.0")
	if err != nil {
		log.Panic(err)
	}
}
```

When I run the code, get error message like:

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
golang.org/x/net/icmp.ListenPacket(0x113c872, 0x3, 0x113cd87, 0x7, 0x0, 0xc0000ae381, 0x123aa60)
	/Users/songjiayang/go/pkg/mod/golang.org/x/net@v0.0.0-20190628185345-da137c7871d7/icmp/listen_posix.go:53 +0x872
```
I known the reason is because I use an invalid network, it should be `ip4:1`  rather than `ip4`. But I think it should raise a specific error rather than a panic runtime error.

**Comment by bcmills** [comment]
The bug is a missing range check here:
https://github.com/golang/net/blob/da137c7871d730100384dbcf36e6f8fa493aef5b/icmp/listen_posix.go#L52-L53

```go
		i := last(network, ':')
		switch network[:i] {
```

**Comment by songjiayang** [comment]
> The bug is a missing range check here:
> https://github.com/golang/net/blob/da137c7871d730100384dbcf36e6f8fa493aef5b/icmp/listen_posix.go#L52-L53
> 
> ```go
> 		i := last(network, ':')
> 		switch network[:i] {
> ```

yes, I try to fix the `last` help function, just make it return the length if no found target char.

**Comment by ivenk** [comment]
Since it has been a couple of days, i took a swing at it. 
So far i did the following : 
- changed the helper function last() to return -1 when no match is found. Similar to what strings.Index does. 
- Later i check for -1 and return a new error i created in message.go

Now instead of a panic an error is returned.
Let me know if i should change anything.

**Comment by songjiayang** [comment]
HI @ivenk, thanks for your PR.

 I have make a same PR for this bug,  but it blocked at code review, you can check it with link https://golang.org/cl/185317

**Comment by ivenk** [comment]
Oh okay i didn't know about that. Will get fixed eventually then.
