### ISSUE TITLE
why does `go test` check depencies which already are in `./vendor`

### ISSUE THREAD

**Issue by jney** [golang/go#32943]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I ran `GO111MODULE=on go test ./...` outside of the `$GOPATH`

### What did you expect to see?

I expected to check dependencies in `./vendor` folder and just run the test

### What did you see instead?

It fetch dependencies fiest

**Comment by AlexRouSg** [comment]
You need to use the `-mod=vendor` arg to use the vendor folder.

**Comment by jney** [comment]
thank you @AlexRouSg 
I tried to find some informations using `go help test`, but nothing there
