### ISSUE TITLE
Clarify thread safety status of JSON, YAML encoders and decoders

### ISSUE THREAD

**Issue by mcandre** [golang/go#32957]
I would like to reuse a single encoding/json encoder object across multiple JSON serializations if possible, but I am concerned about thread safety. For example, would it be a good idea to create just one JSON encoder for responding to HTTP client requests in a typical Go microservice?

The same question applies to JSON decoders, and to YAML encoders and decoders: Are these thread-safe or not?

If they are, could we indicate this more directly in the API documentation? If not, what does the Go community think about making these thread-safe by default?

**Comment by freeformz** [comment]
Encoders / Decoders are each created with a single [io.Writer](https://golang.org/pkg/encoding/json/#NewEncoder) or [io.Reader](https://golang.org/pkg/encoding/json/#NewDecoder).

The documentation does not state that they (json.Encoder and json.Decoder) are safe for concurrent use. Generally speaking you can only assume values of a type are safe for concurrent use when the documentation says they are.

PS: Why do you want to re-use a single encoder ?

**Comment by agnivade** [comment]
As mentioned above, unless the documentation explicitly mentions it, things are not safe for concurrent use by default. https://github.com/golang/go/issues/30632 tracks documenting this and other assumptions more prominently.

Regarding your first question, I think the [forums](https://github.com/golang/go/wiki/Questions) are a better place to discuss that.

**Comment by ALTree** [comment]
What @freeformz and @agnivade said. I'm closing this issues as a dup of #30632.
