### ISSUE TITLE
remote debugging requires depricated configuration

### ISSUE THREAD

**Issue by robinbryce** [golang/go#32962]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.11.6 darwin/amd64

$ dlv version
Delve Debugger
Version: 1.2.0
</pre>

### Does this issue reproduce with the latest release?

Yes (Go extention 0.11.2)

### What operating system and processor architecture are you using (`go env`)?
macOs Mojave 10.14.3 (18D109)
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/robin/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/robin/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/robin/jitsuin/avid/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS="-I/usr/local/opt/openssl/include"
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/usr/local/opt/openssl/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vw/hk51qnpj08n5xw6h1_2brwj40000gn/T/go-build121478435=/tmp/go-build -gno-record-gcc-switches -fno-common" 
</pre></details>

### What did you do?

Started a debug session with delv running headless in a docker container with the following launch config

<pre>
        {
            "name": "Debug - echo",
            "type": "go",
            "request": "attach",
            "mode": "remote",
            "remotePath": "/service/cmd/echo/main.go",
            "port": 2345,
            "host": "127.0.0.1",
        },
</pre> 

### What did you expect to see?

Program execution stops on break points

### What did you see instead?

Program ran to completion

The following "depricated" configuration does what I expect

<pre>
        {
            "name": "Debug - echo",
            "type": "go",
            "request": "launch",
            "mode": "remote",
            "program": "${workspaceRoot}/src/cmd/echo/main.go",
            "remotePath": "/service/cmd/echo/main.go",
            "port": 2345,
            "host": "127.0.0.1",
        },
</pre> 

This configuration warns that "Request type of 'launch' with mode 'remote' is depricated, please use request type 'attach' with mode 'remote' instead

How is remote / local source mapping going to work with the new 'attach' mode ?

**Comment by AlexRouSg** [comment]
I think you have the wrong github project. 
https://github.com/microsoft/vscode-go/issues

**Comment by mvdan** [comment]
What @alexrousg said. I guess Delve's issue tracker is the other option.

If you're positive that this is a bug in Go and not the debugger or another program you're using, please clarify that in the issue with some evidence.

**Comment by robinbryce** [comment]
Ah, nuts. To many tabs open. Sorry guys
