### ISSUE TITLE
after marshal and unmarshal ,  type change

### ISSUE THREAD

**Issue by chowyu08** [golang/go#32972]
### What version of Go are you using (`go version`)?
1.12.6

### What did you do?
`    

       data := map[string]interface{}{
		"Qos": 1,
	}

	for _, v := range data {
		fmt.Println("type:", reflect.TypeOf(v).String())
	}

	fmt.Println("after do marshal and unmarshal...........")

	byts, _ := json.Marshal(data)

	marshalData := make(map[string]interface{})

	json.Unmarshal(byts, &marshalData)

	for _, v := range marshalData {
		fmt.Println("type:", reflect.TypeOf(v).String())
	}`

### output
![image](https://user-images.githubusercontent.com/16483518/60803279-6a849a00-a1ad-11e9-8e70-699cfb7e28a8.png)

**Comment by agnivade** [comment]
See - https://golang.org/pkg/encoding/json/#Unmarshal

> To unmarshal JSON into an interface value, Unmarshal stores one of these in the interface value:

> bool, for JSON booleans
float64, for JSON numbers
string, for JSON strings
[]interface{}, for JSON arrays
map[string]interface{}, for JSON objects
nil for JSON null

**Comment by mvdan** [comment]
What @agnivade said. Please check the documentation and search a bit online before opening bug reports.
