### ISSUE TITLE
-H windowsgui has no effect

### ISSUE THREAD

**Issue by jooadam** [golang/go#32975]
### What version of Go are you using (`go version`)?

1.12

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

### What did you do?

```
GOARCH=amd64 GOOS=windows go build -ldflags '-H windowsgui' -a -o application.exe application.go
```

### What did you expect to see?

No console window on Windows.

### What did you see instead?

Console window appears along with GUI.

**Comment by AlexRouSg** [comment]
You need to do `-ldflags=all='-H windowsgui'`

**Comment by jooadam** [comment]
@AlexRouSg Actually it did work without the `all` pattern. The application starts another process, and I didn’t notice that the command the console window belongs to changed when I applied the flag.
