### ISSUE TITLE
runtime: TestDebugCall* flaky on android-amd64-emu

### ISSUE THREAD

**Issue by bcmills** [golang/go#32985]
From the `android-amd64-emu` builder (https://build.golang.org/log/9cf7d64a00c151574d96c45a0b6e50358b527085):

```
##### GOMAXPROCS=2 runtime -cpu=1,2,4 -quick
--- FAIL: TestDebugCallPanic (0.01s)
    debug_test.go:244: executing on Go runtime stack
FAIL
exitcode=1FAIL	runtime	31.768s
```

CC @aclements @mknyszek

**Comment by bcmills** [comment]
A very similar failure on `android-amd64-emu` in `TestDebugCallGrowStack` (https://build.golang.org/log/ee79c59d8a212e1461c433e52ff9427e44c2fad5):
```
##### GOMAXPROCS=2 runtime -cpu=1,2,4 -quick
--- FAIL: TestDebugCallGrowStack (0.00s)
    debug_test.go:183: executing on Go runtime stack
FAIL
exitcode=1FAIL	runtime	26.259s
```

**Comment by bcmills** [comment]
CC @aclements

**Comment by mvdan** [comment]
Perhaps related? https://github.com/golang/go/issues/33944

**Comment by bcmills** [comment]
`android-amd64-emu` again: https://build.golang.org/log/96ce0d1b4decbb7edcdb2fc9e25da255d50638bb

**Comment by bcmills** [comment]
`android-amd64-emu` again:
https://storage.googleapis.com/go-build-log/a75e00b3/android-amd64-emu_b51c7469.log

CC @aclements @cherrymui @danscales @mknyszek

**Comment by bcmills** [comment]
`android-amd64-emu` again: https://storage.googleapis.com/go-build-log/af0f6d56/android-amd64-emu_efb37c55.log

**Comment by bcmills** [comment]
Still flaky:

**Comment by ianlancetaylor** [comment]
That's a different, albeit related, problem.  Will send a CL.
