### ISSUE TITLE
x/tools/gopls: prefer registering formatting provider dynamically

### ISSUE THREAD

**Issue by stamblerre** [golang/go#32989]
Forked from https://github.com/microsoft/vscode-go/issues/2446.

**Comment by vincepri** [comment]
Thanks for filing this @stamblerre, happy to contribute a patch if I can get more information on where this change should live

**Comment by stamblerre** [comment]
Absolutely - that would be great! It would have to be in https://github.com/golang/tools/blob/master/internal/lsp/general.go - in the initialize and initialized functions, which correspond to the https://microsoft.github.io/language-server-protocol/specification#initialize and https://microsoft.github.io/language-server-protocol/specification#initialized requests. Basically, you'd have to check if the client supports dynamic configuration in initialize, and if so, do the dynamic configuration in initialized. Feel free to ask follow up questions if you need more clarification here.

**Comment by vincepri** [comment]
It seems there is already a check in `initialized` that registers some capabilities dynamically https://github.com/golang/tools/blob/master/internal/lsp/general.go#L130. With regards to the formatter, how would I go about registering it dynamically?

**Comment by stamblerre** [comment]
Yes, that's exactly the place to do it. It would look the same way, only you would be registering the `textDocument/formatting` capability.

**Comment by stamblerre** [comment]
Closing as discussed on the above CL.
