### ISSUE TITLE
runtime: memclrNoHeapPointers: unexpected fault address

### ISSUE THREAD

**Issue by masiulaniec** [golang/go#32999]
Just encountered this crash using `go version go1.12.1 openbsd/amd64` on a pure-Go program:

<pre>
unexpected fault address 0xc02e6ba528
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0xc02e6ba528 pc=0x45a07c]

goroutine 65350 [running]:
runtime.throw(0xccb747, 0x5)
  /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc01afe1860 sp=0xc01afe1830 pc=0x42d7b2
runtime.sigpanic()
  /usr/local/go/src/runtime/signal_unix.go:397 +0x401 fp=0xc01afe1890 sp=0xc01afe1860 pc=0x441ff1
runtime.memclrNoHeapPointers(0xc02e6ba528, 0x18)
  /usr/local/go/src/runtime/memclr_amd64.s:142 +0x1dc fp=0xc01afe1898 sp=0xc01afe1890 pc=0x45a07c
runtime.growslice(0xb9fc80, 0x0, 0x0, 0x0, 0x1a8, 0x0, 0x0, 0x3e5398e)
  /usr/local/go/src/runtime/slice.go:178 +0x17b fp=0xc01afe1900 sp=0xc01afe1898 pc=0x44311b
upspin.io/upspin.(*DirEntry).Unmarshal(0xc01afe1ca0, 0xc013798623, 0x267, 0xffd, 0x2, 0x1000, 0x0, 0x0, 0xc01afe1ba0)
  /home/x/src/upspin.io/upspin/code.go:371 +0x706 fp=0xc01afe1a20 sp=0xc01afe1900 pc=0x70b4a6
upspin.io/dir/server/serverlog.(*Entry).unmarshal(0xc01afe1c98, 0xe5c840, 0xc0172620d8, 0xc013798620, 0x1000, 0x1000, 0x3e5398e, 0xc01
  /home/x/src/upspin.io/dir/server/serverlog/log.go:1271 +0x4c6 fp=0xc01afe1c00 sp=0xc01afe1a20 pc=0xaacbb6
upspin.io/dir/server/serverlog.(*Reader).ReadAt(0xc013798600, 0x1ce54185, 0x0, 0xc037579380, 0x2d, 0x0, 0x0, 0x1400, 0x5d23977e, 0xc02
  /home/x/src/upspin.io/dir/server/serverlog/log.go:812 +0x2f4 fp=0xc01afe1c88 sp=0xc01afe1c00 pc=0xaa93a4
upspin.io/dir/server/tree.(*watcher).sendEventFromLog(0xc0038d0a40, 0xe6d320, 0xc01abbd920, 0x1ce2b4e3, 0x527f2b, 0xc00ac3eb01, 0xc000
  /home/x/src/upspin.io/dir/server/tree/watch.go:333 +0x195 fp=0xc01afe1ec8 sp=0xc01afe1c88 pc=0xab86b5
upspin.io/dir/server/tree.(*watcher).watch(0xc0038d0a40, 0xe6d320, 0xc01abbd920, 0x1ce2b4e3, 0x0, 0x0)
  /home/x/src/upspin.io/dir/server/tree/watch.go:371 +0xaf fp=0xc01afe1fb0 sp=0xc01afe1ec8 pc=0xab8baf
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc01afe1fb8 sp=0xc01afe1fb0 pc=0x459051
created by upspin.io/dir/server/tree.(*Tree).Watch
  /home/x/src/upspin.io/dir/server/tree/watch.go:171 +0x42b
</pre>

OpenBSD version is 6.5.  I will try to repro using the latest version of the compiler.

**Comment by dmitshur** [comment]
Thanks for the report.

Does it happen reproducibly, or is it hard to reproduce?

Please let us know if it happens with Go 1.12.7 and/or 1.13 beta 1.
