### ISSUE TITLE
channel with net.http, no deadlock, why

### ISSUE THREAD

**Issue by georgehao** [golang/go#33004]
### What version of Go are you using (`go version`)?

go version go1.12.2 darwin/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/haohongfan/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xx/go"
GOPROXY="https://goproxy.io"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/haohongfan/goproject/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9q/mcmf4t9x6qgf9bc4x83nvl5m0000gn/T/go-build979680138=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

if a `channel` without buffer, send data to channel but not receive, it must be `deadlock`, eg
```go
func main() {
	waitQueue := make(chan int)
	for {
		waitQueue <- 1
	}
}
```
> output: fatal error: all goroutines are asleep - deadlock!

**But when this build with `net/http`, the deadlock is missing, only block the program, WHY** 

eg
```go
func main() {
        fmt.Println("xxx")
	waitQueue := make(chan int)
	waitQueue <- 1
	return

	server, err := net.Listen("tcp", "127.0.0.1:9001")
	if err != nil {
		fmt.Println(err)
	}

	for {
		connection, err := server.Accept()
		if err != nil {
			panic("server")
		}
		fmt.Printf("Received connection from %s.\n", connection.RemoteAddr())
		//go func(c net.Conn) {
		//connection.Close()
		//}(connection)
	}
}
```
output:
```
xxx
```
### What did you expect to see?

As I see the official document, This `must` get deadlock, but result not.

### What did you see instead?

deadlock

**Comment by bcmills** [comment]
The built-in deadlock detector only flags states in which the program is _guaranteed_ not to make further progress — it does not flag conditions in which _some_ goroutine is guaranteed not to make progress (which we call “goroutine leaks”).

**Comment by bcmills** [comment]
That said, the built-in deadlock detector *does* trigger for the code you've pasted above: https://play.golang.org/p/UvS4MkDtXhx

**Comment by georgehao** [comment]
at playground, it deadlock. but on my mac, it's not, see the picture below

![image](https://user-images.githubusercontent.com/6947653/60895332-08a05f00-a297-11e9-9e84-123b745f1b2c.png)

**Comment by bcmills** [comment]
@georgehao, the deadlock detector is disabled when the C linker is used (see #29322), and as of Go 1.12, Go on macOS uses the C `libSystem` for system calls (#17490).

**Comment by georgehao** [comment]
@bcmills I see the golang version of playgroud is 1.12.5, it's deadlock. but on my macOS is not. why ?

**Comment by bcmills** [comment]
The Playground does not use macOS.

**Comment by georgehao** [comment]
I see, when run the code in linux os, the deadlock appeared. That is, golang invokes system calls  don't use C lib on linux OS, it invoke direct ?

**Comment by bcmills** [comment]
Correct.

**Comment by georgehao** [comment]
@bcmills oh, my mistake. I just found that I commented the wrong code. When I run the right code on linux, it also don't has the deadlock.  see the below 

![image](https://user-images.githubusercontent.com/6947653/60901448-90d73200-a2a0-11e9-9876-7e591a57a452.png)

**Comment by bcmills** [comment]
That's expected. See https://github.com/golang/go/issues/33004#issuecomment-509654759.

**Comment by georgehao** [comment]
@bcmills I test on centos, ubuntu with version 1.10, 1.12.5, 1.12.6, 1.12.7 of the code, all don't have the deadlock.  but go playground does, it's interesting

**Comment by bcmills** [comment]
Whether the deadlock detector triggers may depend on goroutine scheduling and system call implementation details.

Fundamentally, your programs — and tests of those programs — should not rely on the behavior of the deadlock detector. It's a useful tool when it triggers, but it's not an adequate substitute for profiling, integration-testing, and load-testing.

**Comment by georgehao** [comment]
I know, thx @bcmills
