### ISSUE TITLE
net: host lookup on Linux non-GNU-libc systems

### ISSUE THREAD

**Issue by tomkcook** [golang/go#33019]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 linux/arm
</pre>

### Does this issue reproduce with the latest release?
Not tested on 1.12.7 but I don't believe any of the tickets included between 1.12.6 and 1.12.7 affect this issue.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="arm"
GOBIN=""
GOCACHE="/home/vsys/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/vsys/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build834352528=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```
package main

import (
	"net"
	"fmt"
	"os"
)

func main() {
	ips, err := net.LookupIP("localhost")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Could not get IPs: %v\n", err)
		os.Exit(1)
	}
	for _, ip := range ips {
		fmt.Printf("localhost. IN A %s\n", ip.String())
	}
}
```

The above program gives the wrong address for `localhost` if:
* The system does not use GNU libc AND
* The combination of the DNS server configured on the system and the system's default domain do not produce a correct result for `localhost`.

The system where this was observed is running Alpine Linux 3.9.  This uses the musl libc.  This libc does not support `/etc/nsswitch.conf` and so that file is usually missing.

On this type of system, it seems that golang's name resolution code looks for `/etc/nsswitch.conf`, doesn't find it, and then defaults to DNS only, skipping any lookup in `/etc/hosts`.  The DNS query that is sent is not for `localhost` but for `localhost.x.y.z` where `x.y.z` is the `domain` setting from `resolv.conf`.

If the configured DNS server produces a correct response for `localhost.x.y.z` then all is still well, but if it doesn't then lookup fails (or even worse, as below, returns an address for another host).

My suggestion is that golang on musl libc systems should follow the musl libc convention, which is to check /etc/hosts first and then DNS.

A workaround is to add a file `/etc/nsswitch.conf` that specifies `hosts: files dns`.

### What did you expect to see?
On a system with IPv6 enabled:
```
localhost. IN A ::1
localhost. IN A 127.0.0.1
```

### What did you see instead?
The exact output varies with the environment where it is run, but eg:
```
localhost. IN A 192.64.119.254
```

**Comment by ianlancetaylor** [comment]
When using glibc the default when there is no /etc/nsswitch.conf is `dns [!UNAVAIL=return] files`, according to https://www.gnu.org/software/libc/manual/html_node/Notes-on-NSS-Configuration-File.html.  It sounds like you are saying that musl behaves differently.  That seems unfortunate.

You can force the use of the C resolver by setting `GODEBUG=netdns=cgo`.  I guess we could consider adding a `GODEBUG` setting that looks at /etc/hosts first and then falls back to the Go resolver.

I'm not excited about doing a run-time test for whether we are using musl.

**Comment by mhaley-tignis** [comment]
I am hitting an issue on MacOS and am unsure if it is related to this or not. If it is not, please let me know and I will open another issue.

I have a very similar program to the original posted above. If I provide a domain that does not resolve and build and run it using `go build` I see the following:

```
Could not get IPs: lookup does-not-exist: no such host
```

If I build the same program with `CGO_ENABLED=0 go build` I see the below:

```
Could not get IPs: lookup does-not-exist on 192.168.0.1:53: no such host
```

It seems like the resolver is only using DNS and not looking at any of the configs in `/etc/resolver`.

I ask, because a tool I want to use (kafkactl) builds with `CGO_ENABLED=0` which is interfering with the applications ability to resolve a name that can be found in the `/etc/resolver` directory. If I build that same app without setting the `CGO_ENABLED` flag, the hostname is resolved as expected and the app works.

**Comment by mhaley-tignis** [comment]
@ianlancetaylor Thank you for replying. I created a new issue then to track the behaviour https://github.com/golang/go/issues/51753. We can continue the conversation there.

**Comment by mateusz834** [comment]
It seems like this issue was fixed in the meantime.
```
root@db2:~# cat /etc/resolv.conf
nameserver 127.0.0.53
search .
root@db2:~# cat /etc/nsswitch.conf
cat: /etc/nsswitch.conf: No such file or directory
root@db2:~# GODEBUG=netdns=2 ./main
go package net: confVal.netCgo = false  netGo = false
go package net: dynamic selection of DNS resolver
go package net: hostLookupOrder(localhost) = files,dns
localhost. IN A ::1
localhost. IN A 127.0.0.2
```

**Comment by ianlancetaylor** [comment]
@mateusz834 Where did you find that quote?  Thanks.

**Comment by mateusz834** [comment]
@ianlancetaylor On the link you posted here: https://github.com/golang/go/issues/33019#issuecomment-510076310

**Comment by ianlancetaylor** [comment]
@mateusz834 Ah, thanks.  Looks like this was changed in December, 2021 for https://sourceware.org/bugzilla/show_bug.cgi?id=28700.

And it does seem that Go does the expected thing, so closing.  Please comment if you disagree.

**Comment by tomkcook** [comment]
@ianlancetaylor I'm unclear, sorry - I can see that glibc default behaviour has changed to match the muslc behaviour but has the golang net package also changed to match this behaviour?  I can't see a reference to a PR above but it might just be whoever did the PR wasn't aware of this ticket.

**Comment by mateusz834** [comment]
@tomkcook There was a proposal somewhere to change that. #35305

**Comment by tomkcook** [comment]
Gotcha.  Looks like [this](https://go-review.googlesource.com/c/go/+/238629) was merged, which implements the change.

**Comment by kgersen** [comment]
Don't know if this is the same issue but on some of my systems, (mostly Arch Linux), net.LookupIP("localhost") don't give the IPv6 value (::1) only IPv4 (127.0.0.1).
but all other commands like dig, host and resolvctf do.

```
resolvectl query localhost
localhost: 127.0.0.1                           -- link: lo
           ::1                                 -- link: lo
```
but on the same machine, this Go code: https://go.dev/play/p/gHlxWsre2Cp
gives:
```
go run main.go 
localhost: 127.0.0.1

```
