### ISSUE TITLE
x/website: Remove the Google logo

### ISSUE THREAD

**Issue by noxer** [golang/go#33021]
Go is perceived by some as a pure Google project without community involvement (see https://utcc.utoronto.ca/~cks/space/blog/programming/GoIsGooglesLanguage). Adding a Google logo does not help in this discussion.

I propose removing the Google logo from the website.

### What version of Go are you using (`go version`)?
The current Go website (https://golang.org)

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
All of them

### What did you do?
Open the website and scroll to the bottom.

### What did you expect to see?
No Google logo

### What did you see instead?
A Google logo

**Comment by andybons** [comment]
Thanks for the issue. We spent a long time talking about it and are sensitive to this concern. It's equally important to make it clear that Google supports Go, which was missing before (Much like http://typescriptlang.org). Google pays for and hosts the infrastructure that golang.org runs on and we hope the current very small logo is a decent compromise.

**Comment by noxer** [comment]
I get that you've discussed this internally. This is a great opportunity to discuss it with the community.
I'm thankful to Google for financing the initial and ongoing development of Go but Google is not the only company investing Go. I would like to move the Google logo into an separate section, together will the major stakeholders of the project.

**Comment by RandomGuyDTB** [comment]
Maybe to the left of the Google logo you could write "Supported by", to clarify the meaning behind the logo?

**Comment by painhardcore** [comment]
Maybe we even can have the "Supported by" section on the index page with a list of company logos?
Of course, the Google logo should be the biggest one but other companies make their contribution to language too.

**Comment by CShepartd** [comment]
If Go is Google's language stay with Google logo. If Go is community language (what i personally don't believe) remove Google logo. Simple? Yes.

**Comment by abourget** [comment]
If the argument is, according to the linked post, that "the Go team at Google won't add the generics I asked for", therefore we should remove their logo, I think it is a very poor argument.

I personally value tremendously the diligent work made by the Go team to _always_ strive to keep things simple. Resistance is part of this process, yet they have proven that with some patience, we can obtain spectacular results, without sacrificing simplicity (I'm thinking of "go mod" here).

Therefore, I suggest we keep the logo, and keep the trust in the diligent evolution it conveys.

**Comment by dataf3l** [comment]
Regardless of "whose language it is", (which is a byzantine discussion), I think if Google supported go, they should be able to put their logo on the site, they clearly spent money on it, and then gave it away for free for devs to use, as for "it belong to the community vs it belongs to the corporation", unfortunately, if Google where to drop the language, which I doubt, then it would probably fade away, but I think we are far away from that, I think they will continue to invest in it for many years to come.

**Comment by Jacalz** [comment]
Yeah I think that the Google logo should remain but I’m in favor of add a text saying supported by just over the Google logo. I would argue that it’s the best way forward.

**Comment by timkofu** [comment]
Unless there's something I don't know, Google invested senior developer time(hence money) into bringing the language into being, maintaining it and enhancing it into what it is today. They then gave it away for free. 

Now the rest of us can write fast efficient programs simply, in a language specially designed for Software Engineering. Personally I'm grateful.

**Comment by noxer** [comment]
> If the argument is, according to the linked post, that "the Go team at Google won't add the generics I asked for", therefore we should remove their logo, I think it is a very poor argument.

That is not the argument, where did you get this from?

There seems to be a misconception about what this issue is about. I value Google's participation in Go and I'm not arguing to change that. Having the Google logo in the corner of each golang.org page suggests that this is a pure Google project when it is not (this is why I linked the article, not to make some weird argument about generics).

> Google pays for and hosts the infrastructure that golang.org runs on and we hope the current very small logo is a decent compromise.

>  I think if Google supported go, they should be able to put their logo on the site

> Unless there's something I don't know, Google invested senior developer time(hence money) into bringing the language into being, maintaining it and enhancing it into what it is today. They then gave it away for free.

AFAIK Google hosts and supports Android (https://www.android.com/) and Dart (https://dart.dev/) without putting their logo on every page. Compare the commercial products of Google (https://www.google.com/) and Google Docs (https://docs.google.com, in the hamburger menu) which feature the logo fairly prominently.

Why is Go special with regard to the omnipresence of the Google logo?

**Comment by ALTree** [comment]
Just a reminder that this issue is closed, and closed issues are not monitored, and certainly are not a good place to keep a discussion going.

I believe the answer that @andybons gave in https://github.com/golang/go/issues/33021#issuecomment-510107266 is, like it or not, the "official" one; so the logo will probably stay.

I encourage anyone that wants to keep discussing this to move the discussion on the [golang-nuts mailing list](https://groups.google.com/forum/#!forum/golang-nuts), or some other Go forum. Thanks!
