### ISSUE TITLE
Why fmt.Scan don't accept empty input?

### ISSUE THREAD

**Issue by AhmedMKamal** [golang/go#33027]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
I didn't use any of the previews releases.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=E:\WorkSpace\Projects\MyProject\bin
set GOCACHE=C:\Users\enahm\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\WorkSpace\Projects\MyProject\src\github.com\MyProject\CLI
set GOPROXY=
set GORACE=
set GOROOT=c:\go
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\enahm\AppData\Local\Temp\go-build254941182=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
```
package main

import (
	"fmt"
	"log"
)

func main() {
	// ...
	var str string
	fmt.Println("prompt message")
	_, err := fmt.Scan(&str)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(str)
	// ...
}
```

### What did you expect to see?
Expected `str` to be `""` when the user press enter without typing any value

### What did you see instead?
Nothing at all, `fmt.Scan` keep waiting until the user types some value

**Comment by av86743** [comment]
https://golang.org/pkg/fmt/#Scanln

**Comment by AhmedMKamal** [comment]
@av86743 Getting error `unexpected newline`, so should I use it like that?
```
if _, err := fmt.Scanln(&str);
	err != nil && !strings.Contains(err.Error(), "unexpected newline") {
	log.Fatal(err)
}
```

**Comment by ianlancetaylor** [comment]
As far as I can see `fmt.Scan` is behaving as documented.  The docs say:

> Scan, Fscan, Sscan treat newlines in the input as spaces.

> Input processed by verbs is implicitly space-delimited: the implementation of every verb except %c starts by discarding leading spaces from the remaining input,

Questions about how to use these functions are best directed to a forum.  See https://golang.org/wiki/Questions.

If you just want to read a line ending in a newline, I recommend the `ReadString` method of `bufio.Reader`.  That is simpler than `fmt.Scan`.

**Comment by av86743** [comment]
https://golang.org/pkg/bufio/#Reader.ReadString

Interestingly, ReadString in turn redirects to Scanner "for simple uses":

_ReadString reads until the first occurrence of delim in the input, returning a string containing the data up to and including the delimiter. If ReadString encounters an error before finding a delimiter, it returns the data read before the error and the error itself (often io.EOF). ReadString returns err != nil if and only if the returned data does not end in delim._ **_For simple uses, a Scanner may be more convenient._**

https://golang.org/pkg/bufio/#example_Scanner_lines

**Comment by ianlancetaylor** [comment]
The reference to a `Scanner` in the docs for `ReadString` are not to `fmt.Scan`, but to `bufio.Scanner` (https://golang.org/pkg/bufio/#Scanner).

**Comment by av86743** [comment]
Not a circular reference, no.
