### ISSUE TITLE
go run main.go failed because of .babelrc ?

### ISSUE THREAD

**Issue by dfang** [golang/go#33022]
### What version of Go are you using (`go version`)?

<pre>
λ  go version
go version go1.12.6 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
λ  go env
GOARCH="amd64"
GOBIN="/Users/mj/go/bin"
GOCACHE="/Users/mj/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mj/go"
GOPROXY="https://goproxy.io"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.6/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/mj/src/qor-demo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xb/dsd0_2b92x7bsl92xlzj6fbm0000gn/T/go-build403472382=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```
go run main.go
go: downloading gitlab.com/qor2/admin v0.0.0-20190710123852-4131afc59aee
build command-line-arguments: cannot load github.com/qor/admin: zip for gitlab.com/qor2/admin@v0.0.0-20190710123852-4131afc59aee has unexpected file gitlab.com/qor2/admin@v0.0.0-20190710125636-4131afc59aee/.babelrc
```

### What did you expect to see?
`go run main.go` works as usual

btw, last commit of gitlab.com/qor2/admin works, after go get gitlab.com/qor2/admin, update the replacement hash, then go run main.go failed

### What did you see instead?
exits

**Comment by heschik** [comment]
`GOPROXY="https://goproxy.io"`

This is a goproxy.io bug; you'll need to talk to them. Though I can't reproduce it, so maybe they've fixed it already.

**Comment by dfang** [comment]
how do you confirm that as s goproxy.io bug ?

**Comment by heschik** [comment]
Module zips are either created by the `go` command with `GOPROXY=direct` or downloaded directly from a proxy. Since I've never seen a report of the `go` command creating an invalid zip, and you're using a relatively unusual proxy, it seems like a safe bet that it's the proxy's bug. If you can reproduce the problem after a `go clean -modcache` without using goproxy.io, by all means reopen the bug. But I'm pretty confident it's not a bug in Go.

**Comment by dfang** [comment]
yes, just unset GOPROXY env, it works

i was confusing the process how you confirm the bug.

thanks !

**Comment by agnivade** [comment]
It's in the output of your `go env` which you posted in the issue template. :slightly_smiling_face:  It's one of the reasons why following the issue template is so important.

**Comment by oiooj** [comment]
This not a goproxy.io bug, I checked cached data on goproxy server.

```
[ @v]# cat list
v0.0.0-20190603120644-fda02ae33deb
v0.0.0-20190604051254-beade7c800d1
v0.0.0-20190606145212-fb76afa05f9f
v0.0.0-20190710123852-8018a1abc078
v0.0.0-20190710125636-4131afc59aee
```

All data on the server are correct. 

But from your log, you got a `gitlab.com/qor2/admin@v0.0.0-20190710123852-4131afc59aee` zip,  goproxy.io does not have this zip file. And this commit is not correct on you gitlab repo, see https://gitlab.com/qor2/admin/commits/develop

I can't reproduce this issue, as I know, download zip have some bugs before, but already fixed. Maybe you cached the bad zip file, please clean you mod cache data and try it again,  or update you go version to the latest version.

**Comment by dfang** [comment]
hi oiooj, 

```
 λ  env | grep GOPROXY
GOPROXY=https://goproxy.io
 λ  j go/pkg/mod
 λ  sudo rm -rf gitlab.com/qor2/admin*
Password:
 λ  j qor-demo
 λ  go run main.go
```

It works now with or without GOPROXY env, clean or not clean go mod cache.

But i clearly remember the build keeps failing on coderefresh.io pipeline.

only after i removed this line, build pass ....

<img width="1093" alt="Screen Shot 2019-07-12 at 11 06 45 AM" src="https://user-images.githubusercontent.com/1277047/61099534-48349a00-a495-11e9-8d40-df3a5784c459.png">

**Comment by dfang** [comment]
@oiooj 

what do you mean by 'this commit is not correct on you gitlab repo', i got this pkg on my local after  remove all go/pkg/mod directory and `go mod tidy`.

```
 λ  ls ~/go/pkg/mod/gitlab.com/qor2 | grep admin@v0.0.0-20190710123852-4131afc59aee
admin@v0.0.0-20190710123852-4131afc59aee
```

**Comment by oiooj** [comment]
@dfang The time `20190710123852`'s commit hash should be `8018a1abc078`, not `4131afc59aee`, and I checked data on the server, not found `admin@v0.0.0-20190710123852-4131afc59aee`.

![image](https://user-images.githubusercontent.com/2253095/61101868-1b38b500-a49e-11e9-941d-adc2e7fb33f8.png)
