### ISSUE TITLE
x/website: suggestion: animate the gophers eyes on the website

### ISSUE THREAD

**Issue by Skarlso** [golang/go#33024]
Using this technique (animating the Go Gopher's Eyes: https://buipalsulich.com/post/gopher-eyes/) it would be fairly easy and would add a nice touch to a simple website like golang.org.

Note, I know that the goal is to keep the website simple, like the language is. And I think that it would retain that, but would also add a kind of flair that the Go language has. It's simple in nature, but has powerful foundations which should not be dismissed lightly.

**Comment by andybons** [comment]
Thanks, but we're not going to do this. We've discussed it before and it would be way too distracting.

**Comment by Skarlso** [comment]
Fair enough. :) I had to try. :)

**Comment by Bored0ne** [comment]
*Gopher's eyes roll*
