### ISSUE TITLE
cmd/go: 'go get' failed in go1.13beta1 if proxy serves non-404/410 response code

### ISSUE THREAD

**Issue by oiooj** [golang/go#33032]
### context

`https://goproxy.io/github.com/@latest` returns code 500, not 404, but this design found a bug in go1.13beta1.

### description

if we run `go get -v golang.org/x/tools/cmd/gopls`

use go1.12:

```
Sosara@MBA:/tmp$ go get -v golang.org/x/tools/cmd/gopls
go: finding golang.org/x/tools/cmd/gopls latest
go: finding golang.org/x latest
go: finding golang.org latest
go: finding golang.org/x/tools/cmd latest
go: finding golang.org/x/tools latest
go: downloading golang.org/x/tools v0.0.0-20190606050223-4d9ae51c2468
go: extracting golang.org/x/tools v0.0.0-20190606050223-4d9ae51c2468
go: downloading golang.org/x/sync v0.0.0-20190423024810-112230192c58
go: extracting golang.org/x/sync v0.0.0-20190423024810-112230192c58
go: finding golang.org/x/sync v0.0.0-20190423024810-112230192c58
```

but use go1.13beta1

```
# go version
go version go1.13beta1 linux/amd64

# go get -v golang.org/x/tools/cmd/gopls
go: finding golang.org/x/text/language latest
go: finding golang.org latest
go: finding golang.org/x/text v0.3.2
go: finding golang.org/x latest
go: downloading golang.org/x/text v0.3.2
go: extracting golang.org/x/text v0.3.2
go get golang.org/x/text/language: module golang.org: reading https://goproxy.io/golang.org/@latest: 500 Internal Server Error
```

We already found the prefix, but the error also returned.
Introduced by https://go-review.googlesource.com/c/go/+/177958

**Comment by bcmills** [comment]
Why is the proxy returning status 500 for this path? That seems like the bug to fix.

(See previously #31913.)

**Comment by oiooj** [comment]
> Why is the proxy returning status 500 for this path? That seems like the bug to fix.

@bcmills Thanks, The `goproxy.io` built before [CL173441](https://go-review.googlesource.com/c/go/+/173441), and it breaks user's `go get` in go1.13beata1, I will fixed the proxy server.
