### ISSUE TITLE
x/tools/gopls: releases

### ISSUE THREAD

**Issue by stamblerre** [golang/go#33030]
This issue will include announcements about new tagged versions of `gopls`.

**Comment by stamblerre** [comment]
### v0.1.3

Fixes some deadlocking issues. Adds experimental support for documentation in completion items.

**Comment by stamblerre** [comment]
### v0.1.4

- Speed improvements for import organization (@suzmue)
- Autocompletion for unimported packages (@suzmue)
- Experimental support for deep completion and fuzzy matching (@muirrn)
- Fix for https://github.com/golang/go/issues/29313 (@muirrn)
- Many bug fixes in caching
- Documentation for completion items

**Comment by stamblerre** [comment]
### v0.1.5

- Config settings were not being respected in v0.1.4, so released a fix for that specific issue

**Comment by stamblerre** [comment]
### v0.1.6
* Fix an issue with URI escaping on Windows

**Comment by stamblerre** [comment]
### v0.1.6
* Fix issue with configurations not being respected
* Fix issue with test variants and go/packages (caused import organization to not cause a cache invalidation)

**Comment by stamblerre** [comment]
### v0.2.0-pre2
* Pre-release for the next version of `gopls`. Please test and report bugs if you can!

**Comment by stamblerre** [comment]
### v0.2.1

* Fix for parse errors showing up as errors on the whole package ([CL 206597](https://go-review.googlesource.com/c/tools/+/206597)).

**Comment by stamblerre** [comment]
### v0.2.2

* Fix concurrent map read and write when a file is created ([CL 210199](https://go-review.googlesource.com/c/tools/+/210199)).
* Fix issue that caused errors to show up when a new file was created ([CL 209978](https://go-review.googlesource.com/c/tools/+/209978)).

**Comment by stamblerre** [comment]
### v0.3.0

#### Note: `gopls` now loads your entire workspace, where “workspace” is directory you opened in your editor.

#### In module mode, you must open your module root (directory containing the `go.mod` file) or a subdirectory.

#### In `GOPATH` mode, you must open your `GOPATH/src` or a directory within it. If you have a large `GOPATH` and you open your `GOPATH` as your workspace root, `gopls` may be very slow to load. Please see https://github.com/golang/go/issues/36899 for further information.

* Autocompletion from unimported packages is on by default. You will get completions for something like `fmt.Printf` even if `“fmt”` isn’t imported yet. (@heschik)
* Workspace-scoped references, rename, and go to implementation. These features use your workspace root as the search scope, so behavior will vary based on the directory you open in your editor. This may result in unexpected behavior. (@muirdm, @matloob)
* Workspace-wide diagnostics. You will now see errors in your entire workspace, rather than just in your currently open files. Analysis errors will only be shown for packages with currently open files.
* Watch file changes on disk. This allows users to switch branches without reloading their editors. Also, changing configurations no longer requires an editor reload.
* New autocompletion suggestions for type conversions. Improved completions for literal candidates and variadic functions. Better rankings, including rankings for builtin functions and keywords. (@muirdm)
* Highlighting improvements: Highlighting now applies not only to variables, but also to fields, methods, types, and imports. Additional highlighting helps visualize control flow in loops and functions. Highlighting of single character variables has better support. (@ridersofrohan)
* Documentation on hover includes links to [pkg.go.dev](https://pkg.go.dev) for exported symbols. (@Southclaws)
* Improved support for cgo dependencies. All features now work for packages that have cgo dependencies. Authoring cgo packages is still not supported, but improvements are scheduled for Go 1.15 (see https://golang.org/issue/35721). (@heschik)
* Deep completions are now on by default. This feature of completion will search the fields and methods of all available candidates to see if there are any more candidates with the expected type. As an example, say you have imported the `context` package and are calling a function that takes a `context.Context` as a parameter. In the case that you don’t have a variable of that type in scope, deep completions will suggest `context.Background()` and `context.TODO()`. (@muirdm)

Opt-in:
* staticcheck analyses remain opt-in and can be enabled by setting `“staticcheck”: true` in your `gopls` settings.
* Go 1.14 will support running the go command without modifying the user’s go.mod file. This new feature is used in gopls to show diagnostics and suggest edits in a user’s go.mod file rather than change the file without the user noticing. Currently, gopls will suggest removing unused dependencies and warn the user if there is a parse error in the go.mod file. Enable this behavior by using the go1.14 beta and setting `”tempModfile”: true` in your `gopls` settings. (@ridersofrohan)

**Comment by stamblerre** [comment]
### v0.3.1
* https://github.com/golang/go/issues/36975: Handle nil pointer in builtin packages if workspace load fails.
* https://github.com/golang/go/issues/36999: Fix panic on files that contain `%` in them.
* Fix memory leak caused by autocompletion ([CL 217677](https://go-review.googlesource.com/c/tools/+/217677)). Users were seeing huge memory usage over long sessions. Please comment on https://github.com/golang/go/issues/36943 if you're still seeing this issue with `gopls/v0.3.1`.

**Comment by heschik** [comment]
### v0.3.1
* https://github.com/golang/go/issues/36975: Handle nil pointer in builtin packages if workspace load fails.
* https://github.com/golang/go/issues/36999: Fix panic on files that contain `%` in them.
* Fix memory leak caused by autocompletion ([CL 217677](https://go-review.googlesource.com/c/tools/+/217677)). Users were seeing huge memory usage over long sessions. Please comment on https://github.com/golang/go/issues/36943 if you're still seeing this issue with `gopls/v0.3.1`.

**Comment by stamblerre** [comment]
### v0.3.2
* https://github.com/fatih/vim-go/issues/2701: Fix a crash in references on builtin symbols.
* golang/go#37104: Fix crash in completion of recursive pointer types (for example, `type foo *foo`).
* golang/go#37108: Fix handling of build flags in imports code.
* golang/go#34955: Import organization was corrupting file contents for untracked files. This is now fixed.
* [CL 219203](https://go-review.googlesource.com/c/tools/+/219203): Disable nilness analyzer. This is the only analyzer that requires `go/ssa`, which is expensive to compute. If you are still seeing excessive memory usage with `gopls/v0.3.2`, please read https://github.com/golang/go/issues/36943 and open a new issue.

**Comment by stamblerre** [comment]
### v0.3.3

- Support for workspace symbols. (@daisuzu)
- Various completion improvements, including fixes for completion in code that doesn't parse. (@muirdm)
- Limit diagnostic concurrency, preventing huge spikes in memory usage that some users encountered. (@heschik)
- Improved handling for URIs containing escaped characters. (@heschik)
- Module versions from "go list" in pkg.go.dev links. (@ridersofrohan)
- Upgrade module dependencies via a code lens on `go.mod` files. (@ridersofrohan)
- Opt-in:
- Support for multiple concurrent clients. See golang/go#34111 for more details. (@findleyr) 
- tempModFile: Additional diagnostics and quick fixes for missing dependencies. (@ridersofrohan)

**Comment by stamblerre** [comment]
### v0.3.4

* [golang.org/cl/222979](https://golang.org/cl/222979): fix for a nil pointer exception in completion (@muirdm)
* [golang.org/cl/222980](https://golang.org/cl/222980): fix a concurrent map write and iteration (@ridersofrohan)

**Comment by stamblerre** [comment]
### v0.4.0
- Improved support for working with modules (@ridersofrohan). A detailed walk-through of the new features can be found [here](https://www.ardanlabs.com/blog/2020/04/modules-05-gopls-improvements.html). A quick summary:
  -  Use the `-modfile` flag to suggest which modules should be added/removed from the `go.mod` file, rather than editing it automatically. 
  - Suggest dependency upgrades in-editor and provide additional language features, such as formatting, for the `go.mod` file.
-  Inverse implementations (@muirdm). "Go to implementations" on a concrete type will show the interfaces it implements.
- Completion improvements (@muirdm). Specifically, improved completion for keywords. Also, offer `if err != nil { return err }` as a completion item.
- Jumping to definition on an import statement returns all files as definition locations (@danishprakash).
- Support for running `go generate` through the editor, via a code lens (@marwan-at-work).
- Command-line support for workspace symbols (@daisuzu).

#### Opt-in:
 - Code actions suggesting `gofmt -s`-style simplifications (@ridersofrohan). To get these on-save, add the following setting:

```json5
"[go]": {
	"editor.codeActionsOnSave": {
		"source.fixAll": true,
	}
}
```
 - Code actions suggesting fixes for type errors, such as missing return values ([goreturns](https://github.com/sqs/goreturns)-style), undeclared names, unused parameters, and assignment statements that should be converted from `:=` to `=` (@ridersofrohan). Add the following to your gopls settings to opt-in to these analyzers. In the future, they will be on by default and high-confidence suggested fixes may be applied on save.

```json5
"gopls": {
	"analyses": {
		"fillreturns": true,
                "undeclarename": true,
                "unusedparams": true,
                "nonewvars": true,
	}
}
```

 - Further improvements in the support for multiple concurrent clients (@findleyr). See #34111 for all details. 

For a complete list of the issues resolved, see the [gopls/v0.4.0 milestone](https://github.com/golang/go/milestone/133?closed=1).

**Comment by stamblerre** [comment]
### v0.4.1

This release contains mostly stability improvements and smaller bug fixes. A list of all of the issues fixed in this release can be found in the [gopls/v0.4.1 milestone](https://github.com/golang/go/milestone/146?closed=1). A notable change is that type error analyzers (fillreturns, undeclaredname, unusedparams, nonewvars) are now on by default.

**Comment by stamblerre** [comment]
### v0.4.2

Release notes: https://github.com/golang/tools/releases/tag/gopls%2Fv0.4.2.

We are migrating away from using this issue. New releases will be announced via a [GitHub Release](https://github.com/golang/tools/releases).

**Comment by stamblerre** [comment]
Closing this issue, as we are now using GitHub Releases. Please see https://github.com/golang/tools/releases for future updates.

**Comment by mvdan** [comment]
For those wondering "how should I be notified of releases now?", you can watch the tools repository just for new releases instead of all activity:
![2020-07-01-17:29:43](https://user-images.githubusercontent.com/3576549/86268769-93711c80-bbc0-11ea-9202-3cc6ec88c624.png)

I think that feature is fairly recent - I don't think it existed a couple of years ago when we first suggested using an issue to announce releases.

**Comment by hyangah** [comment]
Uh, we need to update the release note link hardcoded in vscode-go. :-)
