### ISSUE TITLE
cmd/go: -failfast flag does not apply across packages

### ISSUE THREAD

**Issue by dsnet** [golang/go#33038]
Using `go1.12`

The documentation for `failfast` says "Do not start new tests after the first test failure."

When running `go test ./... -failfast` and one of the packages has a failure, it continues to run the tests for other packages. My interpretation of the documentation above is that `go test` would stop after any failure, even if in a different package.

**Comment by zenovich** [comment]
For now, this command helps a lot: ```for s in $(go list ./...); do if ! go test -failfast -v -p 1 $s; then break; fi; done```

**Comment by lookfirst** [comment]
Bump?

**Comment by docmerlin** [comment]
Bump!

**Comment by mvdan** [comment]
Please refrain from "bumping" github threads; see https://github.com/golang/go/wiki/NoPlusOne. If you would like to speed up the resolution of this issue, you can either react with a :+1: on the original post, or look into sending a CL with a test. See https://go.dev/doc/contribute :)

**Comment by AlexanderYastrebov** [comment]
Bump :)

**Comment by AlexanderYastrebov** [comment]
> Please refrain from "bumping" github threads

@mvdan @bcmills @dsnet How do I bring attention back? PR is ready since October 2023
