### ISSUE TITLE
x/website: remove G+ Community links

### ISSUE THREAD

**Issue by Prithvipal** [golang/go#33049]
Google plus is no longer available so G+ Community link: https://golang.org/help/#pluscom should be removed from the Help page. Clicking on this link shows below message:

**Google+ is no longer available for consumer (personal) and brand accounts**

**Comment by dgryski** [comment]
https://github.com/golang/go/commit/bc27b64dba0ac74cd084d5331862d8fbf587c262 didn't get ported to /x/website.  Not sure if there are any other fixes that need to be migrated.

**Comment by agnivade** [comment]
Thanks @dgryski. The commit was made 23 days ago. x/website does not directly hold templates which are in the main repo. They are loaded dynamically. golang.org will show it when it gets redeployed. You can see that tip.golang.org shows it correctly.

I am closing the issue as the code fix has already been made. And it will appear in golang.org when it gets redeployed.

**Comment by andybons** [comment]
It will get deployed once 1.13 is released (unless someone cherry-picks the fix to the 1.12 branch). We’re still working to move all our docs into x/website so that we don’t have to do this much for such a small change.
