### ISSUE TITLE
x/website: inconsistent headers

### ISSUE THREAD

**Issue by jadekler** [golang/go#33043]
At https://golang.org the headers are:

<img width="1061" alt="Screen Shot 2019-07-10 at 3 51 24 PM" src="https://user-images.githubusercontent.com/3584893/61007661-98431d80-a32a-11e9-9a65-1a7115067f86.png">

At https://golang.org/dl/ the headers are:

<img width="1043" alt="Screen Shot 2019-07-10 at 3 51 42 PM" src="https://user-images.githubusercontent.com/3584893/61007668-a5600c80-a32a-11e9-8278-ed94ba17c1ed.png">

Note that Play is in the latter but not the former.

**Comment by AndrusGerman** [comment]
Golang.org congratulations for the new design. I have my question where is the code of the page? AND Thank you for the report, you are looking if someone had uploaded it

**Comment by ALTree** [comment]
@AndrusGerman The code is at https://github.com/golang/website. 

If you have other questions, the [golang-nuts mailing list](https://groups.google.com/forum/#!forum/golang-nuts) is a better place to ask them.

**Comment by av86743** [comment]
@jadekler 

On the home page https://golang.org there is an `Open in playground` link, which makes menu item `Play` kind of redundant.  It would be of course nicer if that link would open in a separate tab/window for larger screens, but that's a different point.

PS WOW. Now https://golang.org/dl has also missing `Blog` from the menu.

**Comment by andybons** [comment]
Previously, the "Play" link showed a popup of the playground much like what is on the golang.org landing page, which is why (I'm guessing) it was hidden on the homepage. This should be fixed to show the Play link on all pages since it now links to play.golang.org.

**Comment by ivenk** [comment]
@andybons From what i can tell this seems to be fixed already.

**Comment by andybons** [comment]
@ivenk “Play” is not present in the navigation header on https://golang.org/, so this is not yet fixed.

**Comment by ivenk** [comment]
@andybons oh ... yeah you are correct. My bad.
