### ISSUE TITLE
go test about mkdir 

### ISSUE THREAD

**Issue by kadisi** [golang/go#33053]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.10.2 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go version go1.10.2 linux/amd64
[root@container common]# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build335872179=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

i create a function:
```
func GetCurrentDirectory() string {
	dir, err := filepath.Abs(filepath.Dir(os.Args[0]))
	if err != nil {
		fmt.Printf("error when reading currentDirectory:%v\n", err)
	}
	return strings.Replace(dir, "\\", "/", -1)
}

```

and it`s test function:

```
func TestGetCurrentDirectory(t *testing.T) {
	t.Run("first", func(t *testing.T) {
		configDir := GetCurrentDirectory()
		t.Logf("dir: %v", configDir)
		_, err := os.Stat(configDir)
		if !os.IsExist(err) {
			err := os.MkdirAll(configDir, os.ModePerm)
			if err != nil {
				t.Errorf("mkdir %v error %v\n", configDir, err)
			} else {
				t.Logf("mkdir %v successful", configDir)
			}
		}
		//time.Sleep(time.Second * 10)
	})
}
``` 
### What did you expect to see?

when i exec `go test -v` , it output 
```
=== RUN   TestGetCurrentDirectory
=== RUN   TestGetCurrentDirectory/first
--- PASS: TestGetCurrentDirectory (0.00s)
    --- PASS: TestGetCurrentDirectory/first (0.00s)
    	com_test.go:11: dir: /tmp/go-build194121955/b001
    	com_test.go:18: mkdir /tmp/go-build194121955/b001 successful
PASS

```

but i can not find `/tmp/go-build194121955/b001` dir.

when i uncomment `time.Sleep(time.Second * 10)` line, and then exec `go test -v &`

i will see `/tmp/go-build**/b001` dir for a while. when `go test ` is done,  `/tmp/go-build**/b001` not exist.

### What did you see instead?

is it the original design or a bug ?

**Comment by ianlancetaylor** [comment]
This is by design.  Note that your `GetCurrentDirectory` function, despite its name, does not return the current directory.  It returns the directory where the test executable exists.  When you run `go test` the test executable is created in a temporary directory.  The executable is run in the directory being tested, as you can see by calling `os.Getwd`.  After the test is completed, `go test` removes the temporary directory containing the test executable, as it is no longer needed.

**Comment by kadisi** [comment]
@ianlancetaylor  thank you
