### ISSUE TITLE
x/sys: go build fail on powerPC64 using gccgo

### ISSUE THREAD

**Issue by wj36604** [golang/go#33057]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.2 gccgo (GCC) 9.1.0 linux/ppc64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="ppc64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="ppc64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/opt/golang"
GOPROXY=""
GORACE=""
GOROOT="/opt/gcc-9.1.0"
GOTMPDIR=""
GOTOOLDIR="/opt/gcc-9.1.0/libexec/gcc/powerpc64-unknown-linux-gnu/9.1.0"
GCCGO="/opt/gcc-9.1.0/bin/gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build451740613=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
</pre></details>

### What did you do?
 cat /proc/version 
Linux version 4.1.35-g2019-05-20-637432e (houzp@dev) (gcc version 4.9.2 (GCC) ) #118 SMP Mon May 20 12:59:31 CST 2019

go build

### What did you expect to see?
compile success

### What did you see instead?
# usb_client
/root/.cache/go-build/09/09c966f52bbded84a8ec71e8ff39f8486d6c851665f52cc7420a13ecb26bdaf5-d(_go_.o): In function `unix.realSyscallNoError':
/opt/golang/src/usb_client/vendor/golang.org/x/sys/unix/gccgo.go:22: undefined reference to `gccgoRealSyscall'
/root/.cache/go-build/09/09c966f52bbded84a8ec71e8ff39f8486d6c851665f52cc7420a13ecb26bdaf5-d(_go_.o): In function `usb_client..z2fvendor..z2fgolang.org..z2fx..z2fsys..z2funix.RawSyscallNoError':
affinity_linux.go:(.text+0x6168): undefined reference to `gccgoRealSyscall'
/root/.cache/go-build/09/09c966f52bbded84a8ec71e8ff39f8486d6c851665f52cc7420a13ecb26bdaf5-d(_go_.o): In function `usb_client..z2fvendor..z2fgolang.org..z2fx..z2fsys..z2funix.Syscall':
affinity_linux.go:(.text+0x6498): undefined reference to `gccgoRealSyscall'
/root/.cache/go-build/09/09c966f52bbded84a8ec71e8ff39f8486d6c851665f52cc7420a13ecb26bdaf5-d(_go_.o): In function `usb_client..z2fvendor..z2fgolang.org..z2fx..z2fsys..z2funix.Syscall6':
affinity_linux.go:(.text+0x6704): undefined reference to `gccgoRealSyscall'
/root/.cache/go-build/09/09c966f52bbded84a8ec71e8ff39f8486d6c851665f52cc7420a13ecb26bdaf5-d(_go_.o): In function `usb_client..z2fvendor..z2fgolang.org..z2fx..z2fsys..z2funix.Syscall9':
affinity_linux.go:(.text+0x68c8): undefined reference to `gccgoRealSyscall'
/root/.cache/go-build/09/09c966f52bbded84a8ec71e8ff39f8486d6c851665f52cc7420a13ecb26bdaf5-d(_go_.o):affinity_linux.go:(.text+0x6958): more undefined references to `gccgoRealSyscall' follow
collect2: error: ld returned 1 exit status

**Comment by ianlancetaylor** [comment]
This looks like a problem with usb_client, not with x/sys.  You are building a vendored version of golang.org/x/sys/unix.  You didn't say which version is vendored.   The first thing to try is updating to the current version of golang.org/x/sys/unix.

**Comment by wj36604** [comment]
I'm sorry for the late reply firstly. If go build on powerPC64 will use gccgo?
When the a package is not used in the program，go build success and the program is running normally.

**Comment by ianlancetaylor** [comment]
If you use the go tool that is distributed with gccgo, then running `go build` will use gccgo.

If you use the go tool that is distributed with the gc toolchain, which is the version that you can fetch from https://golang.org, then running `go build` will not use gccgo.

In the comment above you are using the go tool that is distributed with gccgo.  I can tell because the output of `go version` says "gccgo".

**Comment by wj36604** [comment]
Thanks for your  reply.There is a problem with the "gccgo" compilation environment.
Compiling on another host is fine, will reinstall the build tool。

**Comment by ianlancetaylor** [comment]
Thanks for following up.
