### ISSUE TITLE
x/tools/cmd/godoc: sort package list into stdlib and GOPATH

### ISSUE THREAD

**Issue by adg** [golang/go#3305]
<pre>Brad: &quot;I'd really like to see the standard library by itself, or at least broken up
by itself at the top of the page, with third-party GOPATH stuff at the bottom.&quot;

Russ: &quot;If you really wanted to, you could do something like
<a href="http://golang.org/cl/5797067">http://golang.org/cl/5797067</a> But I am not sure it's such a good idea&quot;

Brad: &quot;Sounds like a great idea. Much prettier. What's the downside?&quot;

Russ: &quot;I have used systems with 'mostly sorted' lists before, and the convenience
always seems to give way to confusion, because people think they _are_ sorted and then
can't find things.&quot;

Robert: &quot;Can we have different modes for looking at it?&quot;

Brad: &quot;The default is all that matters. There's already a flat mode (which I
prefer), but I can never remember how to get to it without looking up the source, which
I'm always too lazy to do. You could argue for mode-switching links, but therein lies
craziness.&quot;</pre>

**Comment by paulswanson** [comment]
I'd like to add a practical observation. I find the headings misleading.

Currently, (go1.4.2),  $GOPATH imports are alphabetically intermingled with packages from the standard library under a heading "Standard library". Further down the page there is a heading "Other packages" where I'd naturally expect my imports to be listed. It's not a clear structure.

I feel that separating Standard Library documentation from GOPATH would make more sense, but even if it deemed not, the headings need to reflect the structure more accurately.

**Comment by adg** [comment]
@paulswanson I agree that the gopath packages should be in a separate list to the standard library.

**Comment by paulswanson** [comment]
@adg, the more I use godoc the more it's ticking me off. What's required to move this forward? Is this one a question of consensus and / or implementation? Cheers.

**Comment by adg** [comment]
It's an implementation thing.

**Comment by andradei** [comment]
It would be nice to have this worked on. A separation of Standard Library and GOPATH libraries would improve the `godoc` experience immensely.

Also, Merry Christmas and thank you for working on Go.

**Comment by agnivade** [comment]
I will take a stab at it. I also like @pebbe's suggestion about collapsing/expanding items beyond a certain depth. Makes for a much cleaner UI.

**Comment by agnivade** [comment]
I have brought it to a presentable state now. I have grouped them under 2 headers - Standard Library and Third Party, which are collapsible and expandable like in a package directory. This would make for a much more cleaner experience. 

**In collapsed form -**
![screenshot-2018-2-2 - the go programming language 1](https://user-images.githubusercontent.com/1774000/35715856-0a04c8c8-07fb-11e8-9cc1-457399556ec7.png)

**Expanding the third part section -**
![screenshot-2018-2-2 - the go programming language 2](https://user-images.githubusercontent.com/1774000/35715863-15f7ff88-07fb-11e8-87f7-7529387620e5.png)

I will send a CL once the 1.11 tree opens.

**Comment by pebbe** [comment]
When GOPATH has multiple parts, I would like to see each part have its own section

**Comment by agnivade** [comment]
Hmm .. that is a bit non-trivial as it would involve more changes to the `PageInfo` struct to avoid looping multiple times through the `DirList` in the html template. 

I think the current CL is a good start, and since the original issue was just about grouping it into GOROOT and GOPATH, its good to keep this to just that to avoid further complexity in the review. Maybe it's best to tackle this in a separate issue.
