### ISSUE TITLE
proposal: generics

### ISSUE THREAD

**Issue by NivenT** [golang/go#33063]
It would be nice if Go had more support for generic programming, something simple like C++ templates or more involved like Rust's traits (or somewhere inbetween). Basically, it would be nice to write code like
```Go
package linalg

typevar T, S

type Mather interface {
 Add(T, T) T
 Broadcast(T, S) S
}

func BroadcastDouble(m Mather, t T, s S) S {
 return m.Broadcast(m.Add(t, t), s)
}
```

**Comment by ianlancetaylor** [comment]
Dup of #15292.

See also https://go.googlesource.com/proposal/+/master/design/go2draft.md .
