### ISSUE TITLE
io/ioutil: don't check for short write in WriteFile

### ISSUE THREAD

**Issue by jsign** [golang/go#33064]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ignacio/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ignacio/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build249863972=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### Issue description
The function [WriteFile()](https://github.com/golang/go/blob/master/src/io/ioutil/ioutil.go) checks if the returned bytes are different from the expected bytes if `err=nil`. This case will never happen since the `Write()` function already satisfies that case.
I think this may be related to another [previous](https://github.com/golang/go/issues/20386) fix regarding this case.

### Propose solution
Delete this `if` case, since `err` should be already correctly returned in the previous line.

If this seems correct, I'd like to propose the PR.

**Comment by ianlancetaylor** [comment]
I think that's fine for the 1.14 release.  Thanks.

The check dates back to ff9e657fb33bb7fe6f8b5e8922925d2ac5026372, before the open source release.  I think that back then we were less clear on exactly how `Write` should behave.
