### ISSUE TITLE
cmd/cgo: panic: overlapping edits

### ISSUE THREAD

**Issue by zeldovich** [golang/go#33061]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +80cca23b59 Wed Jul 10 21:26:21 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/nickolai/.cache/go-build"
GOENV="/home/nickolai/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/nickolai/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/nickolai/tmp/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/nickolai/tmp/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build157323227=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
% cat cgo-panic.go
package p

// #include <stdlib.h>
import "C"

func f() {
	C.free(0, C.size_t(0))
}
% go build cgo-panic.go
# command-line-arguments
panic: overlapping edits: [58,80)->"func() { _cgo0 := /*line :7:9*/0; _cgoCheckPointer(_cgo0); _Cfunc_free(_cgo0); }()", [68,76)->" /*line :7:12*/_Ctype_size_t /*line :7:20*/"

goroutine 1 [running]:
cmd/internal/edit.(*Buffer).Bytes(0xc000086960, 0xc00000e148, 0x602de7, 0xe)
	/home/nickolai/tmp/go/src/cmd/internal/edit/edit.go:79 +0x598
main.(*Package).writeOutput(0xc0000c8000, 0xc0000ba140, 0x7fff391c7ff5, 0x11)
	/home/nickolai/tmp/go/src/cmd/cgo/out.go:597 +0x38d
main.main()
	/home/nickolai/tmp/go/src/cmd/cgo/main.go:356 +0xce3
% 
</pre>

### What did you expect to see?

No panic messages.

### What did you see instead?

A panic message.

**Comment by zeldovich** [comment]
It looks like I failed to properly quote certain characters in my initial bug report, so here it is formatted with Markdown, which should do the right thing with `<` and `>` symbols:

    % cat cgo-panic.go
    package p

    // #include <stdlib.h>
    import "C"

    func f() {
        C.free(0, C.size_t(0))
    }
    % go build cgo-panic.go
    # command-line-arguments
    panic: overlapping edits: [58,80)->"func() { _cgo0 := /*line :7:9*/0; _cgoCheckPointer(_cgo0); _Cfunc_free(_cgo0); }()", [68,76)->" /*line :7:12*/_Ctype_size_t /*line :7:20*/"

    goroutine 1 [running]:
    cmd/internal/edit.(*Buffer).Bytes(0xc000086960, 0xc00000e148, 0x602de7, 0xe)
        /home/nickolai/tmp/go/src/cmd/internal/edit/edit.go:79 +0x598
    main.(*Package).writeOutput(0xc0000c8000, 0xc0000ba140, 0x7fff391c7ff5, 0x11)
        /home/nickolai/tmp/go/src/cmd/cgo/out.go:597 +0x38d
    main.main()
        /home/nickolai/tmp/go/src/cmd/cgo/main.go:356 +0xce3
    %

**Comment by ianlancetaylor** [comment]
It's kind of a terrible error message, but note that your program is invalid.  `C.free` takes only a single argument.

**Comment by zeldovich** [comment]
Indeed, I just minimized this to a simple reproducing case.  The original program was much larger, and the bad error message made it difficult to track down what was wrong (it was also some C function being called with the wrong number of arguments).

**Comment by ianlancetaylor** [comment]
@gopherbot Please open a backport issue for 1.12.
