### ISSUE TITLE
syscall/js: add "delete" operator

### ISSUE THREAD

**Issue by electricface** [golang/go#33079]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13beta1
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by electricface** [comment]
set undefined？

**Comment by dpinela** [comment]
There's no way to do delete properties through syscall/js right now - perhaps we should add one? (Setting a property to undefined isn't quite the same thing as deleting it.)

cc @neelance

**Comment by agnivade** [comment]
There is no direct way as of now. You have to resort to using `eval`.

**Comment by neelance** [comment]
I think we should add this to js.Value, since this is one of JavaScript's basic operations. Setting to `undefined` is not the same. I'm waiting for the next development phase. Reopening.

**Comment by andybons** [comment]
@neelance can you retitle and label the issue to more accurately describe what changes you'll be making/investigating?

**Comment by neelance** [comment]
Sure. Changed the title.
