### ISSUE TITLE
crypto/x509/pkix: clarify docs for ExtraNames field in pkix.Name

### ISSUE THREAD

**Issue by rittneje** [golang/go#33094]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jrittner/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jrittner/go-workspace"
GOPROXY=""
GORACE=""
GOROOT="/home/jrittner/go"
GOTMPDIR=""
GOTOOLDIR="/home/jrittner/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build691331496=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I unmarshaled a pkix.Name containing a custom ExtraName, and printed it out.

https://play.golang.org/p/BUS-NDgjPLI

### What did you expect to see?

1.2.3.4=#130673616d706c65,CN=foobar

### What did you see instead?

CN=foobar

**Comment by katiehockman** [comment]
I don't think this is a bug that requires a code fix. I do agree that the behavior could be clearer though, so changed this issue to a documentation improvement (which I'll send a PR for shortly).

This behaves very similarly to `x509.Certificate.ExtraExtensions` and I think those docs explain this behavior a bit better: 

```
// Extensions contains raw X.509 extensions. When parsing certificates,
// this can be used to extract non-critical extensions that are not
// parsed by this package. When marshaling certificates, the Extensions
// field is ignored, see ExtraExtensions.
Extensions []pkix.Extension

// ExtraExtensions contains extensions to be copied, raw, into any
// marshaled certificates. Values override any extensions that would
// otherwise be produced based on the other fields. The ExtraExtensions
// field is not populated when parsing certificates, see Extensions.
ExtraExtensions []pkix.Extension

```

This is the important part of the pkix.Name docs that could be expanded:

> When parsing, all elements are stored in Names and non-standard elements can be extracted from there. When marshaling, elements in ExtraNames are appended and override other values with the same OID.

So what's happening here is that `ExtraNames` will override any standard elements (like `Locality` or `Country`) with the same OID. But for OIDs which aren't standard (like the one in your example {1, 2, 3, 4}, the attribute is simply put into name.Names.
If you inspect `pkix.Name.Names` you'll see that data is still there, it's just that `pkix.Name.String()` doesn't print these non-standard fields.
