### ISSUE TITLE
x/crypto: NaCl compatibility not clear

### ISSUE THREAD

**Issue by flyn-org** [golang/go#33109]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mike/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mike/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build347076838=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I spent some time investigating the compatibility of golang.org/x/crypto/nacl/box/ with DJB's NaCL and libsodium.

### What did you expect to see?

The documentation at  https://godoc.org/golang.org/x/crypto/nacl/box states "This package is interoperable with NaCl: https://nacl.cr.yp.to/box.html," so I expected the package's Seal function would produce ciphertext that NaCl's crypto_box_open function could decrypt.

### What did you see instead?

After some experimentation, I found that the Go package instead seem to be compatible with libsodium's "easy" API. That is, Seal produces ciphertext that crypto_box_open_easy will decrypt, and crypto_box_easy produces ciphertext that Open will decrypt.

I recommend amending the documentation at https://godoc.org/golang.org/x/crypto/nacl/box to provide more clarity about this. I wrote some sample programs in Go and C which might help illustrate this.

**Comment by flyn-org** [comment]
[box.c.txt](https://github.com/golang/go/files/3390487/box.c.txt)
[unbox.c.txt](https://github.com/golang/go/files/3390488/unbox.c.txt)
[box.go.txt](https://github.com/golang/go/files/3390489/box.go.txt)
[unbox.go.txt](https://github.com/golang/go/files/3390490/unbox.go.txt)

**Comment by flyn-org** [comment]
@FiloSottile

**Comment by slrz** [comment]
Why do you think the x/crypto implementations don't interoperate with NaCl's crypto_box? Did you test it? If so, please provide the code for your tests.

Isn't libsodium's crypto_box_easy supposed to be the same as NaCl's crypto_box? Libsodium just offers an additional detached mode (called crypto_box_detached) that allows you to write the tag somewhere else instead of prepending it to the ciphertext.

**Comment by ohir** [comment]
@flyn-org 
Where is the sample code using DJB's [reference NaCl](https://hyperelliptic.org/nacl/nacl-20110221.tar.bz2) that fails to interoperate with your sample .go?

Have you tested either with [tweetNaCl](https://tweetnacl.cr.yp.to)/20140427/tweetnacl.{h,c} ?

**Comment by dmitshur** [comment]
Also relevant here is that NaCl is close to being removed (1.13 will be the last release to support it), see #30439 and https://tip.golang.org/doc/go1.13#ports.

**Comment by FiloSottile** [comment]
@dmitshur This is not the same NaCl. :)

#30439 is about Native Client, while this is about x/crypto/nacl, which is not being removed.

**Comment by FiloSottile** [comment]
The original NaCl API is [bizarre to the point of being perplexing and unsafe](https://libsodium.gitbook.io/doc/public-key_cryptography/authenticated_encryption#notes), so while x/crypto/nacl is interoperable with it, it doesn't match its idiosyncrasies, so doesn't require the same padding.

If you use the more reasonable "easy" libsodium API, or if you properly apply padding as required by the original NaCl API, you should find it to interoperate correctly with x/crypto/nacl. (If not, please open a new issue!)
