### ISSUE TITLE
Go module: cannot find module providing package 

### ISSUE THREAD

**Issue by Alireza-Ta** [golang/go#33106]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.12.4 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
package main

import (
	"fmt"
	"golang.org/x/net/html"
	"net/http"
)

func main() {
	res, err := http.Get("example.com/something.html)

	fmt.Println("http error : ", err)

	h, err := html.Parse(res.Body)
	fmt.Println(h)
}
```

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/admin/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/admin/Desktop/GoProjects"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/admin/Desktop/GoProjects/src/voice/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cg/27tz050s4xzggym0mdhw3kd00000gn/T/go-build234647493=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I'm just trying to use `net/html` package but when hitting `go run main.go` just giving me the following error:
`build command-line-arguments: cannot load golang.org/x/net/html: cannot find module providing package golang.org/x/net/html`

### What did you expect to see?
Working as expected!

### What did you see instead?
`build command-line-arguments: cannot load golang.org/x/net/html: cannot find module providing package golang.org/x/net/html`

**Comment by hyangah** [comment]
I couldn't reproduce the issue with the included program. (after fixing the missing ")
Can you try to see what version of golang.org/x/net module you have in your cache? From the main module (in your case, it seems like `/Users/admin/Desktop/GoProjects/src/voice`)
<pre>
$ go list -m -json golang.org/x/net
</pre>

Or, what happens if you clean up the module cache and build?
<pre>
$ go clean -modcache
$ go build
</pre>

**Comment by Alireza-Ta** [comment]
@hyangah Sorry for late reply!
I did all what you said but no luck. Also it does not about missing double quote!
I just removed all directory and start a fresh module and it works!
Thanks anyway.
