### ISSUE TITLE
gccgo: go/internal/work forces -fsplit-stack into cgoCFLAGS

### ISSUE THREAD

**Issue by DHowett** [golang/go#33108]
### What version of Go are you using (`go version`)?

<pre>
1.10.8
1.11
1.12.7
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"                                                                                                                             GOBIN=""                                                                                                                                   GOCACHE="/home/dhowett/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GORACE=""
GOROOT="/opt/go1.10.8"
GOTMPDIR=""
GOTOOLDIR="/opt/go1.10.8/pkg/tool/linux_amd64"
GCCGO="x86_64-openwrt-linux-gnu-gccgo"
CC="x86_64-openwrt-linux-gnu-gcc"
CXX="x86_64-openwrt-linux-gnu-g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build157113365=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Attempted to compile mixed code (Go and C) with golang-go as the driver for gccgo.

_This is necessary because gcc will occasionally decide not to install `<triple>-go` if it believes the compilation to be a cross-compilation._

Here's what's happening:

On these lines, we're unequivocally adding `-fsplit-stack` to the `cgoCFLAGS` on i386 and amd64.

https://github.com/golang/go/blob/21f548400650e4e7047202ee1894ee6ddd44de82/src/cmd/go/internal/work/exec.go#L2543-L2547
https://github.com/golang/go/blob/21f548400650e4e7047202ee1894ee6ddd44de82/src/cmd/go/internal/work/gccgo.go#L531-L534

The equivalent lines in [golang/gofrontend](https://github.com/golang/gofrontend), which I believe (?) are used in gcc's `<triple>-go`, do a [feature check](https://github.com/golang/gofrontend/blob/70ceba5e95716653b9f829a457a44a829175d4da/libgo/go/cmd/go/internal/work/exec.go#L2498-L2500) before adding it.

### What did you expect to see?

`go build` succeed with a mixed cgo and go project.

### What did you see instead?

```
cc1: error: '-fsplit-stack' currently only supported on GNU/Linux
cc1: error: '-fsplit-stack' is not supported by this compiler configuration
```

There is no way to suppress the addition of `-fsplit-stack`.

Incidentally, it was a toolchain issue that broke `-fsplit-stack`, but there's a real desync between the code in gofrontend and go proper. Is that intended, and should that be resolved?

**Comment by ianlancetaylor** [comment]
The code differences between the gofrontend and the gc implementations should be resolved.
