### ISSUE TITLE
cmd/gofmt: rewrite 'a->a' breaks declaration inside function literal

### ISSUE THREAD

**Issue by rillig** [golang/go#33105]
### What version of Go are you using (`go version`)?

go version go1.13beta1 windows/amd64

### Does this issue reproduce with the latest release?

yes

### What did you do?

```go
package main

func main() {
	_ = func() { var ptr *string; println(ptr) }
}
```

```shell
gofmt -r 'a->a' -d rewrite.go
```

### What did you expect to see?

No change.

### What did you see instead?

```diff
-       _ = func() { var ptr *string; println(ptr) }
+       _ = func() { var ptr *string = ; println(ptr) }
```

**Comment by dmitshur** [comment]
Thanks for reporting this as well.
