### ISSUE TITLE
cmd/gofmt: rewrite 'a->a' adds parentheses around function return type

### ISSUE THREAD

**Issue by rillig** [golang/go#33104]
### What version of Go are you using?

go version go1.13beta1 windows/amd64

### Does this issue reproduce with the latest release?

yes

### What did you do?

```go
package main

func main() {
	_ = func() string {}
}
```

```shell
gofmt -r 'a->a' -d funcreturn.go
```

### What did you expect to see?

The return type of the function literal is still `string`, without parentheses.

### What did you see instead?

The return type is enclosed in parentheses.

```diff
-       _ = func() string {}
+       _ = func() (string) {}
```

**Comment by dmitshur** [comment]
Thanks for reporting this.
