### ISSUE TITLE
x/website: footer text is cut off on smaller viewports

### ISSUE THREAD

**Issue by komuw** [golang/go#33100]
### What did you do?
- go to https://golang.org/ on mobile

### What did you expect to see?
- everything well laid out

### What did you see instead?
- the letter 'R' in 'Report a website issue' is missing
- there's no space before the google logo

![IMG-0304](https://user-images.githubusercontent.com/5163857/61176112-cf802b80-a5c3-11e9-807b-95f97d55cbf6.png)

- my phone is iphone SE
- browser; chrome

**Comment by andybons** [comment]
Added `NeedsFix` but it's unclear what fixed means (perhaps changing the text to be "Report issue" is enough).
