### ISSUE TITLE
Test Package Error: cmd/vet or the next package.

### ISSUE THREAD

**Issue by changrui** [golang/go#33119]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.12.4
</pre>

### Does this issue reproduce with the latest release?
When I compile golang v1.13 beta from source code, the error occurs.

### What operating system and processor architecture are you using (`go env`)?
Windows 10, amd64.
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

get source golang code from github.com/golang/go, and I compile it with go v1.12.4. 

### What did you expect to see?

test package OK.

**Comment by agnivade** [comment]
Hi @changrui - please tell us exactly what you did (for eg. what commands you ran), and show us the entire output.

**Comment by changrui** [comment]
hi, today, I do `git clone` & `./all.bash` under Ubuntu 19.04 again, it says `ALL TESTS PASS`, THANKS.
