### ISSUE TITLE
the tool to prioritization the test cases order by coverage rate

### ISSUE THREAD

**Issue by gxs929** [golang/go#33110]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?
i want to find a tool to prioritization the test cases order by coverage rate.

**Comment by dmitshur** [comment]
Hi @gxs929.

This seem to be a question rather than an issue. I suggest posting it another medium that is better suited for questions, see https://golang.org/wiki/Questions. Compare to the issue tracker, it's more likely someone will see your question there and be able to reply to it.

Thanks.

**Comment by gxs929** [comment]
> Hi @gxs929.
> This seem to be a question rather than an issue. I suggest posting it another medium that is better suited for questions, see https://golang.org/wiki/Questions. Compared to the issue tracker, it's more likely someone will see your question there and be able to answer it.
> Thanks.
Aha，thanks for your suggest,cause i am a freshman to Github,there are lots of rules i dont know.
