### ISSUE TITLE
time.Date return wrong when get Weekday for 12 December 2019

### ISSUE THREAD

**Issue by miun173** [golang/go#33120]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/miun/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/miun/golang"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.7/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/miun/learn/bootcamp-kumparan-academy/mini-project-backend-2/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7b/0b4h2f9n03772j3zmby5xhth0000gn/T/go-build393908295=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I want to get first day of 12 December 2019

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	loc, _ := time.LoadLocation("Asia/Jakarta")

	currDay := int(time.Date(2019, 11, 1, 0, 0, 0, 0, loc).Weekday())
	// expected 5 (Friday) correct
	fmt.Println("first day of 1 November 2019", currDay)
	
	currDay = int(time.Date(2019, 12, 1, 0, 0, 0, 0, loc).Weekday())
	// expected 7 (Sunday)
	fmt.Println("first day of 1 December 2019", currDay)	
}

```
check https://play.golang.org/p/zbEokKYouc8

### What did you expect to see?
I expect to get 7 (sunday)

### What did you see instead?
but got 0

**Comment by bserdar** [comment]
Sunday is 0. See the docs: 

https://golang.org/pkg/time/#Weekday

**Comment by miun173** [comment]
Oh, i see thanks
