### ISSUE TITLE
Disable chunked encoding for HTTP server responses

### ISSUE THREAD

**Issue by watermelo** [golang/go#33127]
### What version of Go are you using (`go version`)?
go version go1.12.6 darwin/amd64

### What did you do?
Because of AWS lambda does not support stream response, so I want to disable chunked encoding. how should I disable it?

**Comment by FiloSottile** [comment]
Chunked encoding is required when the server doesn't know in advance the length of your response. You can just set the Content-Length response header, and chunked encoding will be automatically disabled.

The golang/go issue tracker is used to develop the Go project, so you'll get more help with questions about using the Go language through the resources listed at https://golang.org/wiki/Questions.

**Comment by tandr** [comment]
That information might a good candidate for a paragraph in the godoc for http module or one of the calls there
