### ISSUE TITLE
x/xerrors: update with new %w semantics

### ISSUE THREAD

**Issue by zombiezen** [golang/go#33143]
The [launch decision on #29934](https://github.com/golang/go/issues/29934#issuecomment-489682919) mentions changing `fmt.Errorf` to permit `%w` anywhere in the format string. [golang.org/cl/176998](https://golang.org/cl/176998) updated `fmt` at tip to support this, but `xerrors.Errorf` has not been given the new semantics yet. Since xerrors will presumably be used as a transition package for folks writing libraries that need to support older versions of Go, I think it's still worth updating xerrors to include this behavior.

@jba @neild

### What did you do?

https://play.golang.org/p/rL3z0G4cmnR

### What did you expect to see?

```
err2: foo bar
err3: bar: foo
```

### What did you see instead?

```
err2: %!w(*xerrors.errorString) bar
err3: bar: foo
```

**Comment by carlmjohnson** [comment]
I ran into this myself. I tried to wrap with `xerrors.Errorf("%w", err)` and I was surprised when it didn't work. I debugged the wrong thing before changing it to `": %w"`.

**Comment by jba** [comment]
I have a (clumsy, incomplete) fix for this at https://go-review.googlesource.com/c/xerrors/+/186957.

**Comment by sidh** [comment]
Would really like to see a fix for this too.

**Comment by sidh** [comment]
Any news on this issue?

**Comment by jba** [comment]
I updated my CL to fix the problem @sidh pointed out. I'm waiting for a review.

**Comment by sidh** [comment]
Another issue which actually has a TODO in the code - https://play.golang.org/p/KJZ0Uirj48r

**Comment by jba** [comment]
(First, that CL was submitted, but for some reason this bug wasn't closed. I guess that's a blessing in disguise :)

@sidh, there are several such problems that would require better parsing of the format string. However, since Go 1.14 is coming out shortly and it will make xerrors obsolete, I don't think it's worth fixing them.

**Comment by jba** [comment]
To clarify: once 1.14 is out, the only two officially supported versions of Go are 1.13 and 1.14, both of which have the new errors support. So if you follow the official policy, you can remove xerrors from your code.

**Comment by sidh** [comment]
Yeah, I've updated our version already.

Problem with switching to stdlib version of errors is you will miss out on stack frames and neat formatting. May be there is another package out there, all compatible with 1.13 errors? I'd prefer not to write it myself if there is one.

**Comment by ALTree** [comment]
Fixed in [CL 186957](https://go-review.googlesource.com/c/xerrors/+/186957).
