### ISSUE TITLE
net/http: Header.Clone behavior

### ISSUE THREAD

**Issue by dsnet** [golang/go#33141]
The [`Header.Clone` method is being added in Go1.13](https://tip.golang.org/pkg/net/http/#Header.Clone). It's current behavior is to always allocate a map and return it even if the receiver is nil.

Thus:
```go
h1 := http.Header(nil)
h2 := h1.Clone()
fmt.Println(h1 == nil) // true
fmt.Println(h2 == nil) // false
```

Is this behavior we want to go with? It seems more consistent for `Clone` to return nil if the receiver is also nil.

**Comment by andybons** [comment]
Agree. Will send a change.

@bsiegert

**Comment by odeke-em** [comment]
Good catch @dsnet! I agree that passing a nil header to Clone should also return a nil header and I'll review @andybons' CL
