### ISSUE TITLE
x/tools/go/packages: 'go list -e -json /absolute/path' doesn't show correct import path

### ISSUE THREAD

**Issue by jayconrod** [golang/go#33157]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +6bf2767cc87 Tue Jul 16 15:37:25 2019 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

no, only on tip

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jayconrod/Library/Caches/go-build"
GOENV="/Users/jayconrod/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/var/folders/rq/x0692kqj6ml8cvrhcqh5bswc008xj1/T/tmp.6IPWXRqB"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org"
GOROOT="/Users/jayconrod/Code/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/jayconrod/Code/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jayconrod/Code/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rq/x0692kqj6ml8cvrhcqh5bswc008xj1/T/go-build053820400=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
$ go mod init m
$ go list -e -json $(pwd)
```

### What did you expect to see?

The `ImportPath` field should be set to the expected import path of the directory.

```
{
	"ImportPath": "m",
	"Match": [
		"/Users/jayconrod/Code/test"
	],
	"Incomplete": true,
	"Error": {
		"ImportStack": [
			"m"
		],
		"Pos": "",
		"Err": "unknown import path \"m\": package m is not in the main module (m)"
	}
}
```

### What did you see instead?

`ImportPath` is set to the absolute path of the directory instead.

```
{
	"ImportPath": "/Users/jayconrod/Code/test",
	"Match": [
		"/Users/jayconrod/Code/test"
	],
	"Incomplete": true,
	"Error": {
		"ImportStack": [
			"/Users/jayconrod/Code/test"
		],
		"Pos": "",
		"Err": "unknown import path \"/Users/jayconrod/Code/test\": cannot find package"
	}
}
```

### Other notes

`golang.org/x/tools/go/packages` relies on the old behavior for packages with new files that are edited but not saved yet.

New behavior was likely introduced in [CL 185417](https://go-review.googlesource.com/c/go/+/185417).

**Comment by jayconrod** [comment]
cc @stamblerre @bcmills

**Comment by bcmills** [comment]
`go/packages` should not be relying on this behavior: it's extremely fragile.

What happens if the main module is `example.com/m` and has a requirement on module `example.com` which _actually_ contains the package `example.com/m`?

**Comment by jayconrod** [comment]
I'll work with @stamblerre more to figure out exactly why it's doing this and what should happen instead. In general, I think they mainly need a way to map a directory to an import path.

**Comment by stamblerre** [comment]
Yes, exactly. Editors like Vim might not write anything to disk for a while, but the user will still be editing their file. We need some way to guess an import path given a directory. The code in go/packages that does this is [here](https://github.com/golang/tools/blob/128ec6dfca091cc7d4fe6d18d97911f37c95a590/go/packages/golist_overlay.go#L49), and it only works because, previously, `go list` returned the "guess" of what that directory's import path was.

**Comment by andybons** [comment]
Moving to 1.14 as this isn't a release-blocker. Feel free to bump it back if it becomes one.

**Comment by stamblerre** [comment]
I think that this will actually have to be a release blocker for 1.13, because it will completely break the `gopls` overlay behavior. We need some kind of resolution here - was our conclusion that `go/packages` should do the work of resolving the import path?

**Comment by jayconrod** [comment]
I think this should be fixed in `go/packages`. It should be done before 1.13 ships though.

In general, overlays can't be processed by underlying build systems. If a package only exists in the overlay (not on disk) the driver needs to be smart enough to create new packages for it. The driver will also need to suppress errors for packages that are empty or incomplete because the overlay wasn't present.

**Comment by stamblerre** [comment]
Makes sense. We will move the logic into `go/packages`.

/cc @matloob
