### ISSUE TITLE
cmd/go: go help mod prints unclear error message on bad mod subcommand

### ISSUE THREAD

**Issue by ALTree** [golang/go#33153]
```
$ go version
go version devel +0cadf40f4c Tue Jul 16 22:31:35 2019 +0000 windows/amd64
```

`go help mod` prints:

```
Go mod provides access to operations on modules.

[...]

Use "go help mod <command>" for more information about a command.
```

`go help mod <command>` works as advertised, except when `<command>` is not a valid mod command; in that case this bizarre error message is printed:

> $ go help mod bad
>  go help mod bad: unknown help topic. Run ' mod'.

It's not clear what it means by `Run ' mod'`, but it doesn't look right.

**Comment by jmartin82** [comment]
Hi, 

This issue is not only affecting mod subcommands, but it's also affecting all of them.

For example:

` go help vet a`

`go help vet a: unknown help topic. Run ' vet'.`

I've added a CL with the fix.
