### ISSUE TITLE
wiki: CodeTools links broken

### ISSUE THREAD

**Issue by tommy-sho** [golang/go#33165]
## Wiki Links
https://github.com/golang/go/wiki/CodeTools

## Which broken links
[gonerics.io](http://bouk.co/blog/idiomatic-generics-in-go/)

## Detail
When I click to the gonerics, website return 404 code
![image](https://user-images.githubusercontent.com/37259600/61431038-0e690500-a967-11e9-8ac2-7ee94d8c9794.png)
The perf gonerics.io is not active today, and it has been for a long time (a few years). We should probably note that in the wiki page or remove links from CodeTools wiki page.

**Comment by agnivade** [comment]
Thank you. I have removed it.
