### ISSUE TITLE
Strange behaviour for call by value functions with self referenced structs as params

### ISSUE THREAD

**Issue by spacanowski** [golang/go#33168]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>
<pre>
$ go version
go version go1.11.6 linux/amd64
</pre>
<pre>
$ go version
go version go1.12.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/szymonpacanowski/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/szymonpacanowski/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.7/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3_/zxvdktsx4bq7gqnhj_0nl__c0000gn/T/go-build833847980=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

[test code](https://gist.github.com/spacanowski/8dba4f260c5c03ad78cd1e09e35d9105)
[go play](https://play.golang.org/p/jnEndS_ot7P)

### What did you expect to see?

When calling function with call by value param with self referenced struct and changing value of nested struct on deeper level that value change won't be seen outside function. What's stranger if all nested structs are changed or value on first level inside function those changes aren't seen outside given function.

### What did you see instead?

Changes made in call by value function are seen outside this function.

e.g.
Given struct
```golang
type node struct {
	val  int
	next *node
}
```
and call by value function 
```golang
func passByValueChangeDeeperLevel(n node) {
	n.val = 5
	n.next.next = &node{val: 13}
}
```
called by
```golang
list := node{val: 0, next: &node{val: 1, next: &node{val: 2}}}
passByValueChangeDeeperLevel(list)
```
those changes are seen outside of this function and changes made by functions below aren't
```golang
func passByValueChangeDeeperAllLevels(n node) {
	n.val = 5
	n.next = &node{val: 11}
	n.next.next = &node{val: 13}
}

func passByValueChangeSingleLevel(n node) {
	n.val = 3
	n.next = &node{val: 9}
}
```

**Comment by av86743** [comment]
```
func passByValueChangeDeeperLevel(n node) {
	n.val = 5
	n.next.next = &node{val: 13}
}
```
In this case, you are using unmodified `n.next` == `ll.next`.  Which makes update of `n.next.next` visible to `ll` as `ll.next.next`, and test fails.  

In all other cases, you are working with copy of `ll` in `n` and whatever is contained in this copy.  So `ll` is not affected, and tests pass.

**Comment by spacanowski** [comment]
I've checked how it works in [this go play](https://play.golang.org/p/k6uRVsMcH0R). I was expecting that if call by value makes a copy then pointer from struct is also copied to other memory address. Just like `val` from struct is in copied, but pointer is the same and is just brought back after function call if it was changed and not copied.

**Comment by av86743** [comment]
> I was expecting that if call by value makes a copy then pointer from struct is also copied to other memory address.

Pointer `n.next` is copied like you expect.  With that, `ll.next` and `n.next` point to the same struct originally pointed by `ll.next` - struct pointed to is not copied.  Not a deep copy, naturally.

> Just like `val` from struct is in copied, but pointer is the same and is just brought back after function call if it was changed and not copied.

Pointer is the same because it is copied.  Not sure about "is just brought back ..." - `.next`-s are the same [address] and are not changed in the test that fails.

> It's like two different structs (one outside and second one in function) are pointing to same address of `next`.

Yes they are. `ll` and `n`.

**Comment by ianlancetaylor** [comment]
Closing because the code is working as expected.

For help using Go you may get better answers on a forum.  See https://golang.org/wiki/Questions.
