### ISSUE TITLE
cmd/go: can't compile files with relative imports under testdata directory using modules

### ISSUE THREAD

**Issue by natefinch** [golang/go#33163]
#### What did you do?
OK so here's an edge case for you...

I have ~/test/testdata/foo/bar

in `bar` I have

```go
package bar

var Bar string
```

in foo I have

```go
package main

import "./bar"

func main() {
    _ = bar.Bar
}
```

This code will compile if I run it with GO111MODULE=off, but will fail if I compile with GO111MODULE=on with this error message:

```
$ go build
build foo: cannot find module for path _/Users/finchnat/test/testdata/foo/bar
```

#### Does this issue reproduce with the latest release (go1.12.7)?

Yes (note the below says 1.12.4 but I verified with .7 as well).

#### System details

```
go version go1.12.4 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/finchnat/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/finchnat"
GOPROXY=""
GORACE=""
GOROOT="/Users/finchnat/sdk/go1.12.4"
GOTMPDIR=""
GOTOOLDIR="/Users/finchnat/sdk/go1.12.4/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/finchnat/test/go.mod"
GOROOT/bin/go version: go version go1.12.4 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.12.4
uname -v: Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
lldb --version: lldb-1001.0.13.3
  Swift-5.0
```

**Comment by natefinch** [comment]
I just re-tested this with full import paths and it appears to behave the same (works with modules turned off, fails with that same error for the import path with modules turned on).

**Comment by natefinch** [comment]
BTW, the reason for compiling code under testdata is to have that code avoid `go test ./...` etc when working with the "real" code, but to have it available for my tests to compile.  These are tests of `github.com/magefile/mage` which calls `go build` and so I have a lot of actual go files that I use for tests.

**Comment by FiloSottile** [comment]
I think relative imports just don't work with modules, regardless of testdata.

https://github.com/golang/go/issues/26645#issuecomment-408572701

To make your use case work in modules, it sounds like you can just put a go.mod in the testdata folder?

**Comment by natefinch** [comment]
I think you're right that it's just that relative import paths don't work with modules. I swear I'd tested it outside testdata and it worked fine, but I can't reproduce that now.  I'm fine with relative paths going the way of the dodo, mostly just didn't realize this was a backwards incompatibility that was deemed ok.
