### ISSUE TITLE
syscall: missing syscall.Winsize for both linux and darwin

### ISSUE THREAD

**Issue by nsf** [golang/go#3316]
<pre>Just a simple complaint. Since linux's syscall package has Termios struct, is there a
reason why it doesn't exist on darwin as well (or other OSes with similar terminal
mechanics)?

Another issue is ioctl's TIOCGWINSZ which uses 'struct winsize', I was thinking if
Termios struct is defined, why can't we define Winsize as well?</pre>

**Comment by tklauser** [comment]
The syscall package is locked down, but the `Winsize` type and the `Ioctl{Get,Set}Winsize` functions have been added to the x/sys/unix package, thus closing.
