### ISSUE TITLE
GoStore: Teal is listed as both Original and Special

### ISSUE THREAD

**Issue by bradfitz** [golang/go#33173]
Some issues with this page in the store...

https://go-store.io/collections/items/products/test-1?variant=5210865631264

* its URL contains "test-1". Is the test over? Are gophers for sale now?

* the page is full of "Golang" instead of "Go".  (https://golang.org/doc/faq#go_or_golang)

* Teal is listed as both an original and a special color:

<img width="920" alt="Screen Shot 2019-07-18 at 10 39 34 AM" src="https://user-images.githubusercontent.com/2621/61479401-9b509600-a948-11e9-8a07-0f32f9c6273a.png">

/cc @cassandraoid @andybons

**Comment by cassandraoid** [comment]
fixed plushie descrips, waiting on URL fix

**Comment by cassandraoid** [comment]
everything should be fixed @bradfitz

**Comment by cassandraoid** [comment]
cc @andybons ^^
