### ISSUE TITLE
json.Unmarshal to map[string]interface{} missing field 

### ISSUE THREAD

**Issue by manlinl** [golang/go#33179]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, also on 12.x

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
</pre></details>
Ubuntu 18.04 x64

### What did you do?

Repro code below. The json file pass in via flag is downloadable here
https://d1ane3fvebulky.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json

<pre>
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io/ioutil"
)

var input = flag.String("input", "", "input file path.")

func main() {
	flag.Parse()
	rawData, _ := ioutil.ReadFile(*input)
	var spec = make(map[string]interface{})
	json.Unmarshal(rawData, &spec)
	propertyTypes := spec["PropertyTypes"].(map[string]interface{})
	// Works fine
	fmt.Println(propertyTypes["AWS::WAFRegional::ByteMatchSet.ByteMatchTuple"])

	// For unknown reason, AWS::AutoScaling::LaunchConfiguration isn't found in the result
	fmt.Println(propertyTypes["AWS::AutoScaling::LaunchConfiguration"])
}

</pre>
### What did you expect to see?
For some reason, json object keyed by "AWS::AutoScaling::LaunchConfiguration" is missing.

**Comment by av86743** [comment]
Content of `.../latest/...` link will likely change.

**Comment by agnivade** [comment]
From what I see, `AWS::AutoScaling::LaunchConfiguration` is under ResourceTypes, not PropertyTypes. I believe you are looking under the wrong key. Could you double-check ?

**Comment by manlinl** [comment]
My bad, overlooked ‘ResourceType’
