### ISSUE TITLE
go get is look into my computer and not the web

### ISSUE THREAD

**Issue by zfc9d3f** [golang/go#33176]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.12.7 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 18.04

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
go get github.com/foo/bar produces an error
`can't load package: package github.com/dnote/dnote: no Go files in /home/f/go/src/github.com/foo/bar`

**Comment by ianlancetaylor** [comment]
Please add the actual `go env` output.  Thanks.
