### ISSUE TITLE
x/build/cloudfns/wikiwebhook: wiki updates reporter does not report deleted pages

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#33187]
gopherbot reports changes to the wiki in e-mail to golang-wikichanges, which is very helpful.  However, it does not report when pages are deleted.  This means that when someone carelessly or maliciously deletes a page, we don't notice.  This recently happened with the page Mobile.md, in revision 0615f77906f56357715932cf43f79ef2b1823c80, and then again in revision 04aa758f8beac3ab957e3e48537d263b710c1f54, of the wiki repo, but no e-mail was sent either time.

CC @andybons

**Comment by andybons** [comment]
Currently the [only events we get from GitHub are `created` and `edited`](https://developer.github.com/v3/activity/events/types/#gollumevent) so we'd have to write our own loop to check this.

**Comment by ianlancetaylor** [comment]
Well that is just absurd.

**Comment by dmitshur** [comment]
Fortunately Gerrit supports setting up [notifications](https://go-review.googlesource.com/settings/#Notifications) for the wiki repo for all changes, including those that involve deleting pages:

![image](https://github.com/user-attachments/assets/a486d9c3-ce27-479c-8fad-60465a95f4fe)
