### ISSUE TITLE
Warn when v2 or other directory appears in source dir

### ISSUE THREAD

**Issue by vyskocilm** [golang/go#33186]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes!

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mvyskocil/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mvyskocil/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/mvyskocil/projects/cnc/behav/playground/BEH-432-rpc-mod/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build697224910=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Author of github.com/gorilla/rpc placed v2 of it's library to `v2` directory. As he was apparently not using go modules, this was perfectly valid move. Which unfortunately ends in a situation gorilla/rpc/v2 is illegal for use with go modules. And fixing the problem breaks backward compatibility for non module users.

### What did you expect to see?

go build or go vet should issue a warning in this case. Especially if such directory contains go source files. That way the well known compatibility problem will be reported for developers unaware about Go modules.

Reference: https://github.com/gorilla/rpc/issues/65

**Comment by bcmills** [comment]
A `v2` directory is not a problem in general: it should work fine, and we should not warn about it.

I do see a bug in relation to `github.com/gorilla/rpc/v2`, but it's golang/go#33099, and that's fixed at head. (I added more detail on gorilla/rpc#65.)
