### ISSUE TITLE
translate C to GO fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by blacktear** [golang/go#33180]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/data/go"
GOTMPDIR=""
GOTOOLDIR="/data/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build976429460=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
translate C  to GO ; fatal error ; Help!!!
```
[root@e5a86baa4b98 test]# go run main.go
leave msg: index = 0 ,len = 4198
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x106602119cd0 pc=0x7fbc16187098]

runtime stack:
runtime.throw(0x477edf, 0x2a)
        /data/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
        /data/go/src/runtime/signal_unix.go:374 +0x4a9

goroutine 1 [syscall]:
runtime.cgocall(0x452c80, 0xc000032708, 0xc000080000)
        /data/go/src/runtime/cgocall.go:128 +0x5b fp=0xc0000326d8 sp=0xc0000326a0 pc=0x40407b
main._Cfunc_GetImageStreamFunc(0xc00007c000, 0x5c0041a00000, 0xc000003300, 0xc00007c004, 0xc000080000, 0x0)
        _cgo_gotypes.go:85 +0x4e fp=0xc000032708 sp=0xc0000326d8 pc=0x4525de
main.main.func1(0xc00007c000, 0xc00007c004, 0xc000080000, 0x0)
        /data/src/test/main.go:32 +0xd2 fp=0xc000032748 sp=0xc000032708 pc=0x452af2
main.main()
        /data/src/test/main.go:32 +0x102 fp=0xc000032798 sp=0xc000032748 pc=0x452952
runtime.main()
        /data/go/src/runtime/proc.go:200 +0x20c fp=0xc0000327e0 sp=0xc000032798 pc=0x42697c
runtime.goexit()
        /data/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000327e8 sp=0xc0000327e0 pc=0x44b4e1
exit status 2
```

go file
```
package main

/*
#cgo CFLAGS: -I /data/src/imageparser/libs
#cgo LDFLAGS: -L /data/src/imageparser/libs -lImageOperationLib
typedef struct IMAGE_INFO_STRUCT
{
    int DataFilePTR;
}ImageInfoStruct;
typedef void  *LPVOID;

int InitImageFileFunc( ImageInfoStruct* sImageInfo, const char* Path );
int UnInitImageFileFunc( ImageInfoStruct* sImageInfo );
char * GetImageStreamFunc( ImageInfoStruct* sImageInfo, float fScale, int nImagePosX, int nImagePosY, int* nDataLength,  char** ImageStream );
int DeleteImageDataFunc( LPVOID pImageData );
*/
import "C"

func main() {
	var h C.ImageInfoStruct

	r := C.InitImageFileFunc(&h, C.CString("/data/src/imageparser/data/somefile.kfb"))
	if int(r) != 1 {
		panic("open file failed!")
	}
	defer C.UnInitImageFileFunc(&h)

	var dataLength C.int
	var imageStream *C.char

	for i := 0; i < 10; i++ {
		C.GetImageStreamFunc(&h, 20, 92*256, 51*256, &dataLength, &imageStream)
		C.DeleteImageDataFunc(C.LPVOID(imageStream))
		println("leave msg: index =", i, ",len =", dataLength)
	}
}
```
C file can do
```
#include "stdio.h"
#include "imageparser/libs/jfsdk.h"

//gcc test.c -L./imageparser/libs -lImageOperationLib && ./a.out

int main() {
	ImageInfoStruct h;
	int r;

	r = InitImageFileFunc(&h, "/data/src/imageparser/data/somefile.kfb");
	if (r != 1) {
		printf("open file failed!\n");
		return 0;
	}

	int len;
	char* imageStream;

	int i;
	for (i = 0; i < 10; i++) {
		GetImageStreamFunc(&h, 20, 92*256, 51*256, &len, &imageStream);
		DeleteImageDataFunc((LPVOID)imageStream);
		printf("leave msg: index = %d len = %d\n", i, len);
	}

	UnInitImageFileFunc(&h);
}
```

### What did you expect to see?

can run

### What did you see instead?

fatal error

**Comment by ianlancetaylor** [comment]
This is a segmentation violation in your C code.  I don't see anything wrong with your Go code.  I don't know why it behaves differently than your C code.

Is there a way that we can recreate the problem ourselves?  If not, I'm not sure that we can help.

**Comment by blacktear** [comment]
I will make some code to give yours to recreate the problem!I wish golang better!!!Just a moment!!!

**Comment by blacktear** [comment]
I wrote some pseudo code, but there is no way to reproduce the problem. This file is a company file, I can't upload it directly. I contacted a third-party sdk development engineer on Monday to see if I can provide some clues.

**Comment by blacktear** [comment]
var h C.ImageInfoStruct
log.Println(" ") //but I put here(fmt or log).Println(" ")  The problem is solved, I don't know why.

**Comment by ianlancetaylor** [comment]
I suggest that you run the failing case under a debugger to see exactly where the segmentation violation occurs.

**Comment by blacktear** [comment]
I put all the demo files to the address [https://github.com/blacktear/issue33180](https://github.com/blacktear/issue33180) shoud recreate the problem ,you can debug!

**Comment by ianlancetaylor** [comment]
I don't know how you wrote your code, but you seem to be calling a C++ function by calling a C function that just jumps to the C++ code.  Don't do that.  Write an extern "C" function that uses the C ABI rather than the C++ ABI.

If you want a better answer, show us the source code for libImageOperationLib.so rather than sending us a binary.

**Comment by blacktear** [comment]
I don't have the source code of the so file. It seems that I have to find someone to write this SDK. I will try to see if I can.
