### ISSUE TITLE
GoStore: Stock is sold out on most items.

### ISSUE THREAD

**Issue by codyolsen** [golang/go#33197]
### What version of Go are you using (`go version`)?

<pre>
https://go-store.io/
</pre>

### What did you do?

Tried to buy go merch.

### What did you expect to see?

A full shopping cart and an empty wallet.

### What did you see instead?

`SOLD OUT`

---

### Joking Aside:

Is there a timeline for restocking?

**Comment by mvdan** [comment]
Is the GitHub issue tracker the recommended place to ask questions about the store? I'm not being sarcastic; I can't see anything on the site. /cc @cassandraoid @ardan-bkennedy

**Comment by codyolsen** [comment]
https://blog.golang.org/store

>If you find any issues, please submit an issue prefixed with “GoStore” and we will aim to remedy it as soon as we can.

**Comment by mvdan** [comment]
Ah, my bad, missed that :)

**Comment by ALTree** [comment]
I'm pretty sure it means "technical issues", I would be surprised if opening a issue in the toolchain repository on github was the right way of reporting Out-of-stock merchandize... but Cassandra probably can answer this.

**Comment by codyolsen** [comment]
@ALTree If I'm out of line I can remove for sure. But to be fair, the described spec was `ANY` issues...  😉

**Comment by ardan-bkennedy** [comment]
For the time being, people can send an email to GoBridge at support@gobridge.org.  I will talk to the team about setting up a more official email specifically for the store.

**Comment by julieqiu** [comment]
We are working on getting restocked. New items will be added over the next two weeks.

/cc @cassandraoid
