### ISSUE TITLE
x/tools/gopls: debug output is showing on wrong line

### ISSUE THREAD

**Issue by jadekler** [golang/go#33199]
Debug output is showing on the line of the problem, and the line above the problem.

```
$ gopls version
golang.org/x/tools/gopls v0.1.2
    golang.org/x/tools/gopls@v0.1.3 h1:CB5ECiPysqZrwxcyRjN+exyZpY0gODTZvNiqQi3lpeo=
```

<img width="707" alt="Screen Shot 2019-07-19 at 5 20 18 PM" src="https://user-images.githubusercontent.com/3584893/61570409-8d366e80-aa49-11e9-9133-53feab857144.png">

**Comment by stamblerre** [comment]
It doesn't look like the error message matches either of those lines. Was `gopls` lagging / hanging when you encountered this?

**Comment by stamblerre** [comment]
Going to close this issue since it's been a while since the last discussion. Please open a new issue if this problem persists.
