### ISSUE TITLE
GoStore: mention contact info on the site too

### ISSUE THREAD

**Issue by mvdan** [golang/go#33204]
https://blog.golang.org/store contains:

> If you find any issues, please submit an issue prefixed with “GoStore” and we will aim to remedy it as soon as we can. 

This should also be on the store page itself, perhaps as part of the footer.

**Comment by bcmills** [comment]
CC @spf13 @cassandraoid

**Comment by spf13** [comment]
Great idea!

**Comment by cassandraoid** [comment]
Sent this to vendor.

**Comment by wowa1234567** [comment]
Go store habe ich nicht what is this 🙃

**Comment by wowa1234567** [comment]
Sohl ich den Code to mean ausführen?

**Comment by wowa1234567** [comment]
?

**Comment by wowa1234567** [comment]
Hallo

**Comment by wowa1234567** [comment]
Ich habe keine PayPal und ich weiß nicht wie man N26 app benutzt

Cassandra Salisbury <notifications@github.com> schrieb am Mo., 22. Juli
2019, 23:04:

**Comment by andybons** [comment]
The Go Store is [currently offline](https://golang.org/issue/34665). Closing out.
