### ISSUE TITLE
question: I have updated go but still it's showing me the old version

### ISSUE THREAD

**Issue by realuser07** [golang/go#33208]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.2 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?
Debian 64 google instance
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/work"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build089779667=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### I was trying to install Amass via go get.
first of all when I started installing i faced some issue because I was using 1.10.2 version of go.
so I updated manually as described on official website and rebooted my system.

but when I checked the version it was still old.
so I ran these commands to remove go completely on my system to remove go completely:

`sudo apt-get remove golang-go`
`sudo apt-get remove --auto-remove golang-go`
`sudo apt-get purge --auto-remove golang-go`
 
I was trying to install github.com/owasp/amass and this was the error while installing:
root@machine:~# go get -u github.com/OWASP/Amass/...
github.com/OWASP/Amass/services/sources
work/src/github.com/OWASP/Amass/services/sources/radb.go:352:12: undefined: strings.ReplaceAll

I searched on google and it was due to old version of golang but I have already uninstalled the old one and updated latest version 1.12.6

but still after updating when i check i am still running old version of go
and remove commands did not work any more because it is not installed by apt pkg manager any more.
and I am stuck at that I ran some more commands like:
`go get golang.org/dl/go1.12.7`
and nothing happened 

my current go version is after every thing i have done:
` go version`
`go version go1.10.2 linux/amd64`
Same
I am out of options so I created that issue, please help me to solve this issue

please help me to upgrade to new version of go thanks

**Comment by ALTree** [comment]
- Completely nuke every possible version of Go you installed from the OS package manager using the package manager itself
- if `go version` still works, it means Go is still installed. Run `which go`, take note of the path, delete the whole parent folder. For example if `which go` says:

> /usr/local/go/bin/go

delete the whole /usr/local/go folder using

```
sudo rm -rf /usr/local/go 
```

Make sure that now `go version` doesn't work (it should say "go: command not found" or something like that). Then try again to install the latest following the instructions here: https://golang.org/doc/install#install

**Comment by realuser07** [comment]
it worked thanks
