### ISSUE TITLE
Source paths in a binary file

### ISSUE THREAD

**Issue by afonichev** [golang/go#33207]
Why does the compiler write the paths to directories in a binary file and how to remove them?

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
I do not know / no

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=G:\Go\workspace
set GOPROXY=
set GORACE=
set GOROOT=G:\Go
set GOTMPDIR=
set GOTOOLDIR=G:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build692188682=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
`go build -ldflags="-s -w" -o demo-win32-ia32.exe main.go`

### What did you see instead?
![screenshot](https://i.imgur.com/jxGd3Ga.png)

**Comment by ALTree** [comment]
Thanks for the report.

This should be fixed on tip (soon to be published go1.13) by the `-trimpath` flag.

You can (and should) try the new flag in the 1.13 beta (see [here](https://groups.google.com/d/msg/golang-dev/Qn7Gc9-y-nw/JSSCuLYCAwAJ) for installation instructions). Then you can do

```
$ go build -trimpath -ldflags="-s -w" main.go
```

Closing here, since I believe this is already fixed.

**Comment by afonichev** [comment]
Thanks for the quick response.
