### ISSUE TITLE
x/website: Go latest release version info oh home page

### ISSUE THREAD

**Issue by nurali-techie** [golang/go#33212]
### What version of Go are you using (`go version`)?
NA

### Does this issue reproduce with the latest release?
NA

### What operating system and processor architecture are you using (`go env`)?
NA

### What did you do?
Visit home page https://golang.org/

### What did you expect to see?
This is new feature.  As user of Go language, it would be great if I can see latest release version of Go on home page.

The Usecase is, as Go lang user, I visit home page to see latest updates like new blog, new go release etc.  If I can see latest release version of Go then I can instantly download and start using it.

I just expect Go release number somewhere on home page.

### What did you see instead?
Currently, I need to first visit Home page https://golang.org/ and then click "Download Go" which takes me to https://golang.org/dl/ where I can see latest release as well as download link.

**Comment by ALTree** [comment]
Thanks for the request.

This is essentially a dup of #33083 (show current Go version next to download button on homepage). Andybons is working on this, so I think we can close this issue in favour of the older one. Feel free to subscribe to that thread for updated.

**Comment by agnivade** [comment]
Sorry for the confusion here. OP had opened #33145 which I closed citing the same reason. And I asked him to open a new issue for this.

As far as I understand, #33083 is just about showing the existing string which was shown at the footer to be shown next to the download page. But that string just shows the version with which x/website is being built.

OP wants the latest released Go version to be displayed on the home page. I understand both are eventually equivalent, but not exactly same. If that is what @andybons meant in #33083, then we can close this.

So just to be clear, I will reopen this and leave it to Andy for a final call.

Apologies for the to-and-fro.

**Comment by ALTree** [comment]
Wait, I don't get it. If we end up showing something on the DOWNLOAD button, it'll be the latest released version, right? Which is what the OP is asking here. So #33083 will solve the issues this OP has.

I don't think the version near the download button will show the version the website was built with (it wouldn't make much sense for that information to be on the download button).

Also the OP in that old issues wrote:

> I used to check the website to see if a new version was released

it seems he's talking about the latest *released* version, I don't think he cares about the version the website was build for. So my understanding is that 1) OP here and OP in #33083 are asking exactly for the same thing 2) andybons work will fix #33083 (and this one) and satisfy both OPs

**Comment by nurali-techie** [comment]
@ALTree yes, I don't care about the version the website was build for.  I am requesting to show Go latest release version on home page. (anywhere on homepage).

**Comment by agnivade** [comment]
@ALTree  Yeah, I guess you are right. I just wanted to clarify that the initial assumption of OP in #33083 was wrong. It's not just a matter of showing the exact same string in a different location now. We will be showing something completely different.

I guess we can close this since the end result of #33083 is the right one in any case.

@nurali-techie - My apologies for asking you to open a new issue. It seems #33083 is what you should be tracking.
