### ISSUE TITLE
GoStore: Gopher20 discount not applied to my order.

### ISSUE THREAD

**Issue by AndrewSnyder-Legrand** [golang/go#33231]
### What version of Go are you using (`go version`)?

<pre>
$ go version
**go version go1.12.7 windows/amd64**
</pre>

### Does this issue reproduce with the latest release?
I made a purchase on the Go Store on Friday, July 19th that came to $47.03. I entered the Coupon Code **Gopher20** which should have given me a 20% discount of approximately $9.40, but this apparently was not applied. Since I placed my order while this coupon code was still valid ("through Sunday, July 21st at 11:59 PM PST."), could you please either refund that amount of $9.40 to my VISA account on record, or if that isn't possible, please issue me a credit on your lovely Go Store for my future purchases? Thank you very much in advance!

Andrew.Snyder.WT14@Wharton.UPenn.edu
908-256-4907

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?

My order totaling $37.63 ($47.03 - 20%)

### What did you see instead?

My order totaling $47.03 (no discount applied).

![image](https://user-images.githubusercontent.com/52720189/61663986-d7b12880-ac9f-11e9-9d6b-9ff19422bde0.png)

**Comment by ALTree** [comment]
cc @cassandraoid @ardan-bkennedy

**Comment by andybons** [comment]
The Go Store is [currently offline](https://golang.org/issue/34665). Closing out.
