### ISSUE TITLE
gccgo: single-clause select improperly lowered (missing interface conversion?)

### ISSUE THREAD

**Issue by thanm** [golang/go#33235]
### What version of Go are you using (`go version`)?

tip gccgo

<pre>
$ go version
go version go1.12.2 gccgo (GCC) 10.0.0 20190719 (experimental) linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

### What did you do?

Run this program:

https://play.golang.org/p/URnDqSGuHmp

Code:
<pre>
package main

import "fmt"

type SC interface {
	C()
}

type testSC struct {
	id string
}

func (tsc *testSC) C() {
}

func (tsc *testSC) String() string {
	return tsc.id
}

func main() {
	ch := make(chan SC, 10)
	tsc := testSC{id: "blah"}
	select {
	case ch <- &tsc:
	default:
	}
	sc := <-ch
	fmt.Printf("%p %v\n", sc, sc)
}
</pre>

### What did you expect to see?

Successful run with output

  `pointer-value` "blah"

### What did you see instead?

Crash at runtime with:

<pre>
unexpected fault address 0
fatal error: fault
[signal SIGSEGV: segmentation violation code=128 addr=0 pc=140149375235632]

goroutine 1 [running]:
runtime.dopanic_m
	../../../gcc-trunk/libgo/go/runtime/panic.go:1037
runtime.fatalthrow
	../../../gcc-trunk/libgo/go/runtime/panic.go:906
runtime.throw
	../../../gcc-trunk/libgo/go/runtime/panic.go:877
runtime.sigpanic
	../../../gcc-trunk/libgo/go/runtime/signal_unix.go:357
runtime.sighandler
	../../../gcc-trunk/libgo/go/runtime/signal_sighandler.go:100
runtime.sigtrampgo
	../../../gcc-trunk/libgo/go/runtime/signal_unix.go:314

	/build/glibc-XAwaOT/glibc-2.28/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
reflect.rtype.String
	../../../gcc-trunk/libgo/go/reflect/type.go:515
fmt.pp.badVerb
	../../../gcc-trunk/libgo/go/fmt/print.go:338
fmt.pp.fmtPointer
	../../../gcc-trunk/libgo/go/fmt/print.go:509
fmt.pp.printArg
	../../../gcc-trunk/libgo/go/fmt/print.go:645
fmt.pp.doPrintf
	../../../gcc-trunk/libgo/go/fmt/print.go:1016
fmt.Fprintf
	../../../gcc-trunk/libgo/go/fmt/print.go:199
fmt.Printf
	../../../gcc-trunk/libgo/go/fmt/print.go:208
main.main
	/ssd2/go1/src/b/bug.go:28
</pre>

I am pretty sure that this is due to [CL 184998](https://go-review.googlesource.com/c/gofrontend/+/184998), which deals with 0,1,2 select lowering.

From what I can tell in the debugger, the value 'tsc' on line 18 is being passed directly to the channel send as a struct, as opposed to being converted to an interface value.

Also of interest is that if you change line 13 to rename the testSC "C" method to something like "D", the compile continues to go through, as opposed to what we want which is a compiler error. This seems likely to be related.

**Comment by ianlancetaylor** [comment]
CC @cherrymui

**Comment by thanm** [comment]
I poked around a little on this.  Looking at how things worked prior to CL 184998, in clauses::Select_clause::lower_send there is this code:

  // Note that copying the value to a temporary here means that we
  // evaluate the send values in the required order.
  Temporary_statement* val = Statement::make_temporary(valtype, this->val_,
						       loc);

which introduces a type conversion from the RHS type (testSC) to the channel element type (a.SC). This conversion isn't getting created after 184998.   I'll see if I can figure out the right place to restore the type conversion.

**Comment by cherrymui** [comment]
Thanks for looking into this. You're right about the temporary statement. In `Select_statement::lower_two_case` we didn't use the right type to create the temporary.
