### ISSUE TITLE
plugin: changing the plugin code and re-compiling it, the new changes do not add up

### ISSUE THREAD

**Issue by Shivam010** [golang/go#33230]
On changing the plugin code and re-compiling it, the new changes do not add up on opening the newly generated `.so file`, using `plugin.Open`

Follow the code in [main.go](https://github.com/Shivam010/golang-plugin-error/blob/master/main.go) or run the docker [image](https://github.com/Shivam010/golang-plugin-error/blob/master/Dockerfile)

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build277122299=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Follow the code and process in the [repository](https://github.com/Shivam010/golang-plugin-error)

### What did you expect to see?
[Link](https://github.com/Shivam010/golang-plugin-error#golang-plugin-error)

### What did you see instead?
[Link](https://github.com/Shivam010/golang-plugin-error#golang-plugin-error)

### Hot Fix 
Build the plugins with a unique name for `.so` files, i.e. explicitly generate a new so File instead of overwriting the file for the same name

**Comment by ianlancetaylor** [comment]
What do you mean by "do not add up"?

**Comment by AlexRouSg** [comment]
@ianlancetaylor from looking at his `main.go` and expected output. It looks like he expects to be able to hot reload plugins.

@Shivam010 Plugins cannot be unloaded so there is no way to do what you want except to open a new plugin with a different name every time.

**Comment by Shivam010** [comment]
Thank you @AlexRouSg
It means that the only way to do what I am doing is to use different names for the plugin.

**Comment by julieqiu** [comment]
@Shivam010 - does @AlexRouSg's suggestion answer the question?

**Comment by Shivam010** [comment]
The suggestion turns out to be the same as what I had in my mind. So yes, it solves the problem, for now. I have gone through issue #20461 but am open for a more concrete solution for hot code reload on runtime. 
Thanks again !!

**Comment by AlexRouSg** [comment]
For better help finding a solution, please see https://github.com/golang/go/wiki/Questions

**Comment by agnivade** [comment]
Thanks for confirming @Shivam010. I will go ahead and close the issue as there is no bug to fix here. For solutions on how to approach your issue, please reach out to the various forums in the link above. We primarily use the issue tracker for bug fixes and feature proposals. Thank you.
