### ISSUE TITLE
cmd/go: install package for all users

### ISSUE THREAD

**Issue by iptaylortechnical** [golang/go#33234]
# Global `go get`

As it is, `go get` installs to `$GOPATH/src`, traditionally `/home/$USER/go/src`. Unfortunately, this means that modules cannot be installed for all users, unless everyone shares a `$GOPATH` (and all have access to that directory). This would be very unconventional for Linux.

Since there is already a global `$GOROOT/src`, there should be an option to `go get` packages to that location, making them available for all users. 

Use cases:
* sysadmins who want to add a tool to the environment available for everyone
* machines with multiple users for multiple functions can share packages

Solution:
Add a global flag to go get (e.g. `go get -g`) that installs to `$GOROOT` instead of `$GOPATH`.

**Comment by AlexRouSg** [comment]
Do you only care about the executable or do you want the sources to be global too?

There is a `GOBIN` variable that lets you set where to put the executables.
https://golang.org/cmd/go/#hdr-Environment_variables

If you want the sources to be global, you can have multiple `GOPATH` directories e.g. `GOPATH=/some/global/path:/home/$USER/go` and `go get` should download to the first path, but build should search all paths. I'm not sure if this works in module mode tho.

**Comment by agnivade** [comment]
In module mode, if you are running a `go get` outside a module, then the binary will be installed in `GOBIN`. So then, your binary becomes available for all users. But if you are talking about running a global install inside a module then https://github.com/golang/go/issues/30515 is for that.

Regarding sharing packages, I believe it will take us back to GOPATH mode from module mode. Each module will always have it's own go.mod which will pin down it's version. Having a global package will break this as the version of the global package and in go.mod can go out of sync.

**Comment by bcmills** [comment]
The functionality you propose seems like it would overlap significantly with `GOPROXY`. In particular, a `GOPROXY` setting using a `file://` URL can easily point to a shared read-only directory tree, from which individual users can `go get` files into their local `GOPATH` cache.

Do you have any particular use-cases in mind that cannot be satisfied using a combination of `GOPROXY` (to retrieve modules from the shared cache) and `GOPATH` + `go mod download` (to populate modules into the shared cache)?
