### ISSUE TITLE
Want to add Mirror method to string package

### ISSUE THREAD

**Issue by ssenthil416** [golang/go#33243]
### What version of Go are you using (`go version`)? 

1.11.1

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
This is not a issue, its request to add a method called Mirror to string package

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Need to a new method to string package call Mirror. Like the same suggest want to convert all bytes in a string to its mirror byte
for example

Given String : "{(){}[]}"
Excepted output string : "})(}{][{"

### What did you expect to see?
Given String : "{(){}[]}"
Excepted output string : "})(}{][{"

### What did you see instead?
N/A

**Comment by ALTree** [comment]
Hi,

this doesn't seem something that is used often enough to justify it being in the standard library. See https://golang.org/doc/faq#x_in_std:

> The standard library's purpose is to support the runtime, connect to the operating system, and provide key functionality that many Go programs require, such as formatted I/O and networking. It also contains elements important for web programming, including cryptography and support for standards like HTTP, JSON, and XML. 

And more importantly:

> **New additions to the standard library are rare and the bar for inclusion is high.**

If you find this useful (or think it may be useful to many other people), I suggest implementing it as an external library.

Closing here.

**Comment by ssenthil416** [comment]
Thanks. That make sense....
