### ISSUE TITLE
Question: how to import my local package use go mod

### ISSUE THREAD

**Issue by dingrui37** [golang/go#33252]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
no

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dingrui/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dingrui/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/dingrui/projects/heterogeneous/server_go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build379134339=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I want to try Modules outside of the GOPATH, but I don't know how to import my package, 
can someone give me a help? My workspace tree is as below:
![image](https://user-images.githubusercontent.com/22718365/61758840-ee1ec780-adf8-11e9-85c0-dcff28a08c04.png)
This dir is outside of the GOPATH, I want to use proto/calculate.go, how to import it?

**Comment by yoloyi** [comment]
You should import your pkg in the GOPATH or GOROOT
