### ISSUE TITLE
gollvm: incorrect LD_LIBRARY_PATH setting in libgo/buildpackage.sh

### ISSUE THREAD

**Issue by shawn-xdji** [golang/go#33255]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.2 gollvm LLVM 10.0.0svn linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xiaji01/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/xiaji01/.go"
GOPROXY=""
GORACE=""
GOROOT="/home/xiaji01/build/gl.0723.gcc9"
GOTMPDIR=""
GOTOOLDIR="/home/xiaji01/build/gl.0723.gcc9/tools"
GCCGO="/home/xiaji01/build/gl.0723.gcc9/bin/llvm-goc"
CC="/home/xiaji01/util/bin/gcc"
CXX="/home/xiaji01/util/bin/g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build975824184=/tmp/go-build -gno-record-gcc-switches -funwind-tables"

</pre></details>

### What did you do?

I built gollvm on x86-64 using gcc-9, gollvm building and installing worked fine, but 'ninja check-gollvm' failed due to a GLIBCXX issue, it turns out LD_LIBRARY_PATH in ./tools/gollvm/libgo/checkpackage.sh is misspelled 

export LD_LIBRARY_PATH="${BINDIR}:${LD_LIBARY_PATH}"
${LD_LIBARY_PATH} should be ${LD_LIBRARY_PATH}

I'll check with stakeholders if using a personal github account to fix the issue is compliant with my corporate's policy.  

### What did you expect to see?
'ninja check-gollvm' running without issues

### What did you see instead?
link error messages

version `GLIBCXX_3.4.26' not found (required by /home/xiaji01/build/gl.0723.gcc9/./bin/llvm-goc)
ninja: build stopped: subcommand failed.

**Comment by thanm** [comment]
Thanks for the report. I'll send a patch later this morning.
