### ISSUE TITLE
sync/atomic  block

### ISSUE THREAD

**Issue by lqu3j** [golang/go#33258]
### What version of Go are you using (`go version`)?

<pre>
go version go1.12.5 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Maybe not, i don't know!

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/woocat/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/woocat/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/home/woocat/workspace/temps/ip2location/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build745597643=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
I write flollow demo, build it, and run.
```go
package main

import (
	"fmt"
	"sync/atomic"
)

func main() {
	i := 0
	cnt := int32(0)
	for {
		for atomic.LoadInt32(&cnt) >= 10 {
		}
		i++
		atomic.AddInt32(&cnt, 1)
		go func() {
			// do something
			fmt.Println(i)
			atomic.AddInt32(&cnt, -1)
		}()
	}
}

```

### What did you expect to see?

Run up to 10 threads to do someting

### What did you see instead?

The initial program runs normally, gorouoting print ```i``` normally, after running for a while,  the program blocked, and doesn't print anything. Like all goroutings exited, but cnt is greater than or equal to ```10```.

**Comment by bamarni** [comment]
Hey @lqu3j,

There is something to be careful about when running a goroutine in a loop, see https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables

Also here is it not clear when your program will exit, as it's in an infinite loop. There should be simpler ways to achieve what you're doing, maybe using this https://gobyexample.com/worker-pools.

**Comment by lqu3j** [comment]
@bamarni Have you run this code? My question is not whether the value of i is correct. My problem is that this code will block in for atomic.LoadInt32(&cnt) >= 10 {}

**Comment by bamarni** [comment]
Here it seems possible that the goroutines which are decrementing cnt are not running as the program is busy looping. Usually one should use select statements with channels, or eg. waitgroups  for these scenarios.

**Comment by lqu3j** [comment]
@bamarni  I know what you said, and I usually do that.  In theory, the above code will not be blocked, the program will run normally, goroutines will print ```i```, may not be efficient, but will always run and print ```i```. But in reality, when the program runs for a while,  the program blocks and doesn't print anything. Like all goroutings exited, but ```cnt``` is greater than or equal to 10

**Comment by asv1** [comment]
> @bamarni Have you run this code? My question is not whether the value of `i` is correct. My problem is that this code will block in `for atomic.LoadInt32(&cnt) >= 10 {}`, I feel this is a bug in golang.

Your program will be blocked when cnt >= 10. And no new goroutines will be created and **i** will not printing. Its not a bug.

**Comment by lqu3j** [comment]
@asv1  After gorouting quit, execute  ```atomic.AddInt32(&cnt, -1)```.

**Comment by lqu3j** [comment]
> > @bamarni Have you run this code? My question is not whether the value of `i` is correct. My problem is that this code will block in `for atomic.LoadInt32(&cnt) >= 10 {}`, I feel this is a bug in golang.
> 
> Your program will be blocked when cnt >= 10. And no new goroutines will be created and **i** will not printing. Its not a bug.

After gorouting quit, execute atomic.AddInt32(&cnt, -1). The above code is a bit like sync.WaitGroup .

**Comment by bamarni** [comment]
@lqu3j : I think this relates to https://github.com/golang/go/issues/10958, if you try to put some dummy statements in your loop it shouldn't hang at some point anymore.

**Comment by randall77** [comment]
This is expected. Go has a cooperative scheduler, and your main goroutine is not cooperating. It will tend to work until the runtime needs to stop all the goroutines for something (garbage collection, typically).  If it stops enough of your decrementer goroutines before it tries to stop the main goroutine, then the main loop will be unstoppable.

To fix your program, you could put a call to `runtime.Gosched()` into your loop.
