### ISSUE TITLE
wiki: Copying paragraph in CodeReviewComments contains outdated information

### ISSUE THREAD

**Issue by acln0** [golang/go#33257]
https://github.com/golang/go/wiki/CodeReviewComments#copying

> For example, the bytes.Buffer type contains a `[]byte` slice and, as an optimization for small strings, a small byte array to which the slice may refer.

As of 9c2be4c22d78cebc52458ba7298a470a3be0cdce, this is no longer the case.

**Comment by ianlancetaylor** [comment]
Thanks, fixed.
