### ISSUE TITLE
github: add label 'error handling' on the issue tracker

### ISSUE THREAD

**Issue by Freeaqingme** [golang/go#33267]
Currently there are 444 proposals in the issue tracker, many of which appear to revolve around the issue of error handling. Can we maybe add a separate label 'error handling' (or something similar), so one can easily exclude them (or specifically show them instead).

**Comment by av86743** [comment]
Also add a bot rule to close those issues with `Proposal-Rejected` after, say, 6 months.

**Comment by Freeaqingme** [comment]
@av86743 I fail to see how your suggestion relates to this issue. Can you perhaps elaborate on how your suggestion is related to this issue, or - alternatively - open a new issue instead?

**Comment by av86743** [comment]
@Freeaqingme Unrelated suggestion removed.

**Comment by ALTree** [comment]
I'm not sure the proposal mechanism is the correct way to ask for this. From https://github.com/golang/proposal:

> Significant changes to the language, libraries, or tools must be first discussed, and sometimes formally documented, before they can be implemented.

This doesn't really qualify as a "Significant change to the language, libraries, or tools", you're just asking for a new label on the github issue tracker. 

I'm changing this to be not a proposal.

**Comment by Freeaqingme** [comment]
@ALTree Thanks! I wasn't sure about that aspect either, this clears it up :)

**Comment by bradfitz** [comment]
I actually just labeled about 25 issues with a new `error-handling` label and in the process of searching for more found this bug.

So, uh, consider this approved & done.
