### ISSUE TITLE
net/http: optimize http2 in readPreface phase

### ISSUE THREAD

**Issue by detailyang** [golang/go#33268]

**Comment by av86743** [comment]
That's some negation:

```
		} else if string(buf[0:8]) != "PRI * HT" &&
			string(buf[8:16]) != "TP/2.0\r\n" &&
			string(buf[16:24]) != "\r\nSM\r\n\r\n" {
```

**Comment by FiloSottile** [comment]
@av86743 Please use Gerrit for code review, so authors and future reviewers can track comments associated with revisions.

**Comment by av86743** [comment]
> @av86743 Please use Gerrit for code review, so authors and future reviewers can track comments associated with revisions.

Why would I?

**Comment by bradfitz** [comment]
On https://go-review.googlesource.com/c/net/+/187457 I said:

> Sorry, this isn't something that happens enough to be worth optimizing, especially not at this readability/complexity cost.
