### ISSUE TITLE
x/net/http2: Strict handling of http.Transport.DisableKeepAlives in http2

### ISSUE THREAD

**Issue by maurice2k** [golang/go#33260]
### What version of Go are you using (`go version`)?

<pre>
go version go1.12.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?

Using a `http.Transport` with `http.Client` and multiple concurrent outgoing http(s) connections. Basically load testing an http(s) endpoint.

Set `http.Transport.DisableKeepAlives` to `true` to enforce a single connection for each request.

### What did you expect to see?

I was expecting to see _n_ connections for _n_ requests. This is true for http(s)/1.1 but http2 is re-using connections even though `http.Transport.DisableKeepAlives` is `true`.

I understand that this is not strictly a http2 feature but gets translated to http2 in `func (t *http2Transport) disableKeepAlives() bool` and thus should have the same meaning.

### What did you see instead?

Works for http(s)/1.1 but http2 connections get re-used. In a test with `n` requests and a concurrency of `c` only ~`c` connections where used (instead of expected `n` connections).

### How to fix?

See here: https://github.com/golang/net/pull/48

### Related issues
* x/net/http2: connection reused with DisableKeepAlives #22441
* x/net/http2: Transport ignores net/http.Transport.Proxy once connected #25793
* net/http: http2 transport doesn't respect all http1 Transport fields #14008

**Comment by FiloSottile** [comment]
I remember @rsc looked into something similar.

**Comment by maurice2k** [comment]
Can I help with something?
