### ISSUE TITLE
x/tools/godoc,gddo: do not swallow code after output comments if it is not in concluding lines

### ISSUE THREAD

**Issue by ysmood** [golang/go#33276]
### What did you do?

Pushed example code to github: 

```go
func ExampleScanner() {
	frame := byframe.Encode([]byte("test"))
	s := byframe.NewScanner(bytes.NewReader(frame))

	for s.Scan() {
		fmt.Println(string(s.Frame()))
		// Output: test
	}
}
```

Here's the link for the project: https://github.com/ysmood/byframe/blob/7f2ce7731dfc716eb39bb99f4a93e2f43ce11fac/byframe_test.go#L32

### What did you expect to see?

On the godoc website we should see

```go
frame := byframe.Encode([]byte("test"))
s := byframe.NewScanner(bytes.NewReader(frame))

for s.Scan() {
    fmt.Println(string(s.Frame()))
}
```

### What did you see instead?

The last `}` was missing:

```go
frame := byframe.Encode([]byte("test"))
s := byframe.NewScanner(bytes.NewReader(frame))

for s.Scan() {
    fmt.Println(string(s.Frame()))
```

Here's the link for the godoc: https://godoc.org/github.com/ysmood/byframe#example-Scanner

**Comment by agnivade** [comment]
I believe this is because your `Output:` comments are before the closing brace. As you can see here - https://golang.org/pkg/testing/#hdr-Examples, output comments are always concluding line comments.

Can you move the output comment below the closing brace and check ?

**Comment by ysmood** [comment]
Thank you for your quick response, If I move it out, it will work properly.

But I still think this is a bug or something need to be optimized. If my code format is wrong the `go test` should fail or the godoc website should report the misuse, not silently swallow the close-brace.

**Comment by agnivade** [comment]
Should be doable with a little bit of work. The offending code is here -
https://github.com/golang/tools/blob/2e34cfcb95cb3d24b197d58fe6d25046b8f25c86/godoc/godoc.go#L588-L591

Instead of just blindly wiping anything after the index, we need to start from bottom and stop after the first non-comment line.

Note that this is affects both godoc and godoc.org. The two have different codebases.

**Comment by seankhliao** [comment]
this works on pkg.go.dev.
