### ISSUE TITLE
runtime.go: unexpected compiler optimization within goroutine

### ISSUE THREAD

**Issue by blatter2016** [golang/go#33288]
### What version of Go are you using (`go version`)?
1.9.7

### Does this issue reproduce with the latest release?
Yes

### What did you do?
Run the following snippet:
```
package main

import (
	"fmt"
	"time"
)

func main() {
	counter := 0
	
	go func() {
		for {
			counter = counter + 1
			//fmt.Printf("")
		}
	}()

	time.Sleep(1 * time.Second)
	fmt.Println("counter: %d\n", counter)
}

```

### What did you expect to see?
counter should have incremented whether or not the `fmt.Printf` is commented.

### What did you see instead?
Counter is 0 when the `fmt.Printf` is commented out, but increments as expected when uncommented.

The generated assembly shows that the `for` within the goroutine is omitted, so it looks like a compiler optimization but not exactly sure which one it is.

It would be great if someone can help with this.
Thanks!!

**Comment by ianlancetaylor** [comment]
There is no happens-before relationship between the goroutine and the print outside of the goroutine, and there are no atomic operations, so the language doesn't really specify what this program means.  Also, this is likely affected by issue #10958.  Basically, with no atomic of synchronization primitives, the language doesn't promise that the main function will ever see the changes to counter.  Go is not assembly language.

Closing this issue as I don't think there is anything to do.  If you want to discuss this, you are likely to get better answers on a forum.  See https://golang.org/wiki/Questions.
