### ISSUE TITLE
x/tools/gopls: returns incorrect text edits

### ISSUE THREAD

**Issue by autozimu** [golang/go#33289]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/lijunfen/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/lijunfen/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.7/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sz/4srfsz3151xfrxz4t03y23hx7wl71v/T/go-build501432677=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
1. Setup https://github.com/autozimu/LanguageClient-neovim
2. Open a hello world go file.
3. Set `set nofixeol` in vim/neovim.
4. Call `:call LanguageClient#textDocument_formatting_sync()`

Note: this is not specific to this vim/neovim LSP client. It would affects many other LSP clients as the response is violating the protocol.

### What did you expect to see?
gopls sends properly text edits.

### What did you see instead?
gopls sends incorrect text edits that violate the protocol, in that no two text edits shall overlap.

This is originally reported as https://github.com/autozimu/LanguageClient-neovim/issues/844 Please let me know if there is anything needed from me.

**Comment by ianthehat** [comment]
The response looks correct to me? Also I think it works in VSCode (the bug did not have the original source file to repro with so I was guessing from the returned edits)
Why do you think there is an overlap? It has two insertions at the end, but they are not overlapping, they are just insertions that should happen one after the other at the same location.
The spec is very explicit that this is allowed

> All text edits ranges refer to positions in the original document. Text edits ranges must never overlap, that means no part of the original document must be manipulated by more than one edit. However, it is possible that multiple edits have the same start position: multiple inserts, or any number of inserts followed by a single remove or replace edit. If multiple inserts have the same position, the order in the array defines the order in which the inserted strings appear in the resulting text

Also note that a file without a \n a the end is not correctly formatted according to gofmt, so the formatting call will attempt to fix it for you.
cc @stamblerre

**Comment by autozimu** [comment]
I was believing there are overlaps because of the two edits targeting the same range. But that might fall into the `However` clause you pointed out.

Slightly off topic, VSCode itself works usually doesn't justify there isn't any issue. There are far too many implementations that are using VSCode as standard rather than the protocol itself, which makes plugins authors life harder.

Thanks for looking into this!

**Comment by ianthehat** [comment]
Ok. Glad I could help. 
I was not trying to imply that VSCode is always correct, just letting you know that I had attempted to reproduce it on the editor I normally use and was not just replying without checking, because it frustrates me when people do that to me.

**Comment by autozimu** [comment]
I see.👍
