### ISSUE TITLE
cmd/compile: constant arithmetic with typed complex numbers is too precise

### ISSUE THREAD

**Issue by mdempsky** [golang/go#33285]
When computing constant arithmetic of typed floating-point numbers, we truncate the results based on the floating-point type. That is, if `x` and `y` are float32 constants, then `x + y` will be truncated to fit into a float32 too, even if we could compute it more precisely:

This is currently handled in const.go:setconst:

https://github.com/golang/go/blob/919594830f17f25c9e971934d825615463ad8a10/src/cmd/compile/internal/gc/const.go#L1043-L1046

However, there's no corresponding logic for truncating typed *complex* constants. E.g., see this sample program that demonstrates "catastrophic cancellation" for arithmetic on const floats, non-const floats, and non-const complexes, but (non-spec-compliantly) computes the precise result for the const complex arithmetic: https://play.golang.org/p/UpXhGv8pLjQ

gccgo correctly computes 0 for all results. go/types looks like it probably handles this correctly too, but cmd/gotype doesn't easily expose constant values, and I haven't tried writing a test case.

Tagging "help wanted" since this is probably an easy CL if someone wants to grab it. There's already trunccmplxlit, just need to call it.

**Comment by bkpathak** [comment]
@mdempsky Hi Matthew, I can work on this.

**Comment by mdempsky** [comment]
@bkpathak Thanks for the offer! However, @choleraehyq has already started work on this. See CL 187697 linked above.
