### ISSUE TITLE
gccgo: git-lfs doesn't build with due to unsupported _C_int

### ISSUE THREAD

**Issue by glaubitz** [golang/go#33299]
Another Go package which doesn't build with ```gccgo``` is ```git-lfs```:

```
golang.org/x/net/context
github.com/davecgh/go-spew/spew
github.com/spf13/pflag
golang.org/x/sys/unix
# github.com/kr/pty
src/github.com/kr/pty/pty_linux.go:39:8: error: use of undefined type ‘_C_uint’
  var n _C_uint
        ^
src/github.com/kr/pty/pty_linux.go:48:8: error: use of undefined type ‘_C_int’
  var u _C_int
        ^
github.com/git-lfs/git-lfs/t/cmd
github.com/git-lfs/gitobj/pack
github.com/git-lfs/gitobj/storage
golang.org/x/sync/semaphore
github.com/ThomsonReutersEikon/go-ntlm/ntlm
github.com/git-lfs/git-lfs/errors
github.com/git-lfs/git-lfs/filepathfilter
github.com/git-lfs/gitobj
github.com/stretchr/testify/assert
```

Full log at: https://buildd.debian.org/status/fetch.php?pkg=git-lfs&arch=sparc64&ver=2.8.0-1&stamp=1564065645&raw=0

CC @ianlancetaylor

**Comment by ianlancetaylor** [comment]
That's a bug in the github.com/kr/pty package.  Writing `_C_int` used to work with cgo, but that was a mistake.  The documented and only supported approach is to write `C.int`.

**Comment by glaubitz** [comment]
Does it mean it will also fail with a current version of Google's Go compiler?

**Comment by ianlancetaylor** [comment]
Yes, I believe it will.

**Comment by glaubitz** [comment]
Okay, good. This means that the ```git-lfs``` maintainers will notice this bug at some point ;).

Thanks for the quick feedback!

**Comment by AlexRouSg** [comment]
I don't see the relevant file in `github.com/kr/pty` so I'm assuming it's redirecting to `github.com/creack/pty` where it's not a cgo type. It's defined in files like https://github.com/creack/pty/blob/master/ztypes_amd64.go
```go
package pty

type (
	_C_int  int32
	_C_uint uint32
)
```
