### ISSUE TITLE
golang 建议

### ISSUE THREAD

**Issue by JeffreyBool** [golang/go#33290]
能否解决中国地区 依赖需要翻墙下载的问题。
能否解决文档支持中文。现在中国用户 go 除了美国生态是最好的

**Comment by ianlancetaylor** [comment]
Unfortunately, this issue tracker works in English.  Google Translate says:

> Can you solve the problem of relying on the wall to download in China?
> Can I resolve the document to support Chinese? Now Chinese users go apart from the American ecology is the best

I'm sorry, I don't really know what this means.  I suspect that this is a dup of #8870 or #31755, so closing.  Please comment if you disagree.

**Comment by JeffreyBool** [comment]
Want to support Chinese documents

**Comment by JeffreyBool** [comment]
Hope to support Chinese documents. Users who use golang now; China's ecology is the best except for the United States.

**Comment by aofei** [comment]
For the Go module proxy ([proxy.golang.org](https://proxy.golang.org)), please consider using the [goproxy.cn](https://goproxy.cn) as an alternative, which is supported by the [Qiniu Cloud](https://www.qiniu.com) and super fast (CDNed).

![CBDE8D75-17EC-494C-83EA-469325885364](https://user-images.githubusercontent.com/5037285/61952884-a01be680-afe7-11e9-8264-3ab83c29abfc.jpeg)

For the chinese version docs, I suggest that we should shelve this idea for now because its costs too much, IMO.

还有，哥们儿，在这里讨论的话确实应该以英文为主，因为世界各地的人都有，不统一出一门公用的语言的话交流起来会很吃力，而且容易让人产生误解。

**Comment by ianlancetaylor** [comment]
What does "support Chinese documents" mean?  Can you give an example?

**Comment by beoran** [comment]
Now, the documentation of Go is written in English only. There is no tooling yet to do easily do translations of the go documentation to Chinese, or to some even more "obscure" native languages, like, say, mine. The issue that tracks the technical problem is #32743, which should be given more attention. As it is now, one must first learn English before one can learn to use Go well, which is not ideal, to say the least.

**Comment by tianywan** [comment]
The author hope you can offer another version of document and library written in Chinese. @ianlancetaylor  Besides, people live in China cannot access to GitHub freely as most of us were being blocked by the government's Great FireWall for many years until we found something like vpn...

**Comment by ianlancetaylor** [comment]
Go is an open source project, and many aspects of it come from contributions.  We encourage translations of the documentation, and many translations are listed at https://golang.org/wiki/NonEnglish, including Chinese translations.  There is nothing that we can do about the Great Firewall.

**Comment by beoran** [comment]
Most of these translations are in that page are outdated, or even just in planning. It's not easy to translate Go's documentation now. There are technical issues with godoc that prevent easy use of it for translations. Furthermore translated docs should be distributed alongside with Go, not as separate products that will invariably go out of sync.

**Comment by tianywan** [comment]
It's not easy to maintain the documentations in multilingual versions, and more to the point, "Who can do this?"

**Comment by Lizhooh** [comment]
> Go is an open source project, and many aspects of it come from contributions. We encourage translations of the documentation, and many translations are listed at https://golang.org/wiki/NonEnglish, including Chinese translations. There is nothing that we can do about the Great Firewall.

Network connection error！

**Comment by ianlancetaylor** [comment]
Again, Go is an open source project.

If there are technical issues with godoc that make translations harder, please report them and they can be fixed.

Distributing translations alongside Go is fine in principle, but who is going to write the translations?  And promise to keep them up to date with each new release?  Unless we can find those people, distributing translations is a promise we can't keep.

**Comment by aofei** [comment]
Sorry guys, please note that this issue has been closed, and both requests from the author of this issue can be found in earlier existing issues:

1. For the Chinese version of the Go's official module proxy, I've already made a proposal at https://github.com/golang/go/issues/31755#issuecomment-516110168.

2. For the Chinese version docs, as @beoran said, we should discuss it at #32743.

So I think we should move to that two issues to add new ideas. 😊

It seems that this issue should be locked. Thanks. @ianlancetaylor
