### ISSUE TITLE
after executing http shutdown, the client still accesses the server.

### ISSUE THREAD

**Issue by monkey92t** [golang/go#33296]
### What version of Go are you using (`go version`)?

<pre>
go version go1.12.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/Users/ax/language/go/gobin"
GOCACHE="/Users/ax/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ax/language/go/gopath"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/ax/Desktop/ArcTestHttpServer/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mp/7ggd7yxj3vx1x3wcx_wvsb9r0000gn/T/go-build089757980=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
simple test code: 

https://github.com/monkey92t/monkey_code/blob/master/shutdown.go

not 100% panic: Invalid request, please execute it many times.

### What did you expect to see?

after shutdown, http server no longer accepts http client requests.

### What did you see instead?
panic: Invalid request
.....

**Comment by medusar** [comment]
mark
