### ISSUE TITLE
wasm: emit producer custom section

### ISSUE THREAD

**Issue by xtuc** [golang/go#33295]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +1c45dca365 Mon Mar 4 14:21:23 2019 -0800 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="linux"

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Build with `GOOS=js GOARCH=wasm`.

### What did you expect to see?

A wasm producers custom section: https://github.com/WebAssembly/tool-conventions/blob/master/ProducersSection.md with Golang's compiler and its version (or the git hash).

### What did you see instead?

Not present.

**Comment by agnivade** [comment]
@neelance - thoughts ?

We already use the custom section for recording the buildid.

**Comment by neelance** [comment]
Sure, we can add this. Sounds useful. Maybe `language` set to `Go` and `processed-by` set to `gc`?

**Comment by agnivade** [comment]
SGTM.

**Comment by cherrymui** [comment]
> processed-by set to gc?

For DWARF, we set DW_AT_producer to "Go cmd/compile <version>". Maybe we can consider doing the same.

**Comment by neelance** [comment]
@xtuc Is there already some tool that prints the contents of the producer section (and checks its format while doing so)?

**Comment by xtuc** [comment]
I use to print it out https://github.com/xtuc/webassemblyjs/blob/master/packages/cli/src/get-producer-section.js, it will fail to parse if the format is invalid.
