### ISSUE TITLE
wiki: CodeReviewComments change: defer placement

### ISSUE THREAD

**Issue by pselle** [golang/go#33305]
I was looking for a code review comment about `defer` about how it's clearer when the defer is closer to the impacted resources/actions than when put at the end of the function. The relevant part of Effective Go is here: 

>  Second, it means that the close sits near the open, which is much clearer than placing it at the end of the function.

This is of course, in Effective Go, but is less link-able than the CodeReviewComments.

**Comment by agnivade** [comment]
Hi @pselle - The wiki page clearly says 

> You can view this as a supplement to Effective Go.

I don't think it is good to duplicate information in two places.

**Comment by pselle** [comment]
However, it is referenceable:

> This page collects common comments made during reviews of Go code, so that a single detailed explanation can be referred to by shorthands. 

Unlike Effective Go, and that's why I said "less link-able than the CodeReviewComments." It can be useful to have information in two place in different forms.

**Comment by agnivade** [comment]
@andybons @dmitshur

**Comment by andybons** [comment]
How is https://golang.org/doc/effective_go.html#defer less “linkable” than CodeReviewComments?

**Comment by pselle** [comment]
@andybons That's a link to "defer and what it does" versus "where is the best place to put defer when writing Go code". If you all disagree, it's fine to close, but I leaned towards saying something versus saying nothing.

**Comment by andybons** [comment]
@pselle is the proposal to add a "Defer" section that has this information?

**Comment by pselle** [comment]
@andybons It could be that ... reading the style of the page, it seems like there _are_ some general links like that, like this one for comments: https://github.com/golang/go/wiki/CodeReviewComments#doc-comments

I was thinking something more like a maxim, like:

## Defer near the open

When using `defer`, such as closing a file you've opened, locate the `defer` call close to the open, because it makes it less likely you'll leave something un-tidied-up. See https://golang.org/doc/effective_go.html#defer for more information on defer.

But that heading could say "Defer" as well, sure.

I didn't lead with wording because I feel like the "open" part doesn't encompass the generalized use cases for defer, although thinking of close/open is helpful for memory in my opinion.

**Comment by andybons** [comment]
It's not clear to me that this is a "common" code review comment. Does this happen often in reviews?

**Comment by pselle** [comment]
What qualifies something as common? I'm not sure how to answer the question. I ran into a scenario where it would have been useful, and so I proposed.

**Comment by agnivade** [comment]
What Andy is trying to get at is, how often have you seen this happen in reviews. If it is once or twice, it is probably a one-off case. If you have seen it more than three times, then probably it happens more often. This is a common practice where we try to get additional data points from real world usage and base our decisions on it.

**Comment by andybons** [comment]
At the top of the wiki page it says “This page collects common comments made during reviews of Go code”

So I’m trying to ascertain whether this is a common comment. Do people have issues with this often?

@bcmills as one data point, is this a common mistake you see when doing reviews at Google?

**Comment by bcmills** [comment]
> as one data point, is this a common mistake you see when doing reviews at Google?

In reviews I've done, `defer` placement of this sort has come up only very rarely — only in the context of panic-safe code, but most code isn't (and doesn't need to be) panic-safe to begin with.

Most of the issues I've seen with 'defer' are due to incorrect sequencing of operations rather than placement style: for example, writing a `defer` statement in a `for` loop body that should only be scoped to the body (rather than the containing function, as it is _actually_ scoped), or eagerly evaluating arguments that ought to be evaluated lazily (by wrapping the call in a `func() { […] }()`).

**Comment by andybons** [comment]
@pselle we appreciate the suggestion but it’s likely that we won’t add this as there doesn’t seem to be compelling evidence that this is common enough to live in CodeReviewComments. I’ll leave open for another week as a last call for objections/new data.

Thanks

**Comment by pselle** [comment]
Thanks for considering! I understand the decision.
