### ISSUE TITLE
cmd/go: Go modules reads go.mod file from parent directory

### ISSUE THREAD

**Issue by CCXD** [golang/go#33300]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.12.4
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/CC/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/CC/go/"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/CC/go/src/project/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build911813928=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Given the following situation:
```
project
├── lib1
│   └── lib1.go
├── app1
│   └── main.go
└── go.mod

```

- project is in the gopath under /home/CC/go/src/project/
- _app1_ imports _lib1_ with "project/lib1"
- **Only the project root has a go.mod file**, which contains 3rd party imports

When _go build_ is executed in _app1_, _lib1_ is fetched locally, while 3rd party imports such as _"github.com/BurntSushi/toml"_ are fetched remotely with the latest revision. If a _"github.com/BurntSushi/toml"_ version is specified in the _go.mod_ file in the project root, _go build_ in _app1_ will fetch that specific version.

### What did you expect to see?
_go build_ in _app1_ builds without go modules, or always fetches latest revision of all dependencies. I expected the go.mod file in the project root to be ignored.

**Is it intended that go module works if there is only a go mod file in the parent project directory?**

**Comment by AlexRouSg** [comment]
> Is it intended that go module works if there is only a go mod file in the parent project directory?

Yes. 

> A module is defined by a tree of Go source files with a go.mod file in the tree's root directory.


https://tip.golang.org/cmd/go/#hdr-Defining_a_module

**Comment by ALTree** [comment]
What @AlexRouSg said. Closing here.
