### ISSUE TITLE
Help Required for Intellij -  Go plugin

### ISSUE THREAD

**Issue by surapuramakhil** [golang/go#33319]
Hey! I am who liked to use Intellij IDE- Community Versions. for new projects, I wished to switch to go lang instead of Java / Python and Start building/Using it.

initially go plugin was helpful for community versions but eventually and
Unfortunately, Intellij GO plugin support is turned to be a commercial one. they are suggesting to go for their paid version i.e Intellij Ultimate or go lang.

Fortunately, Intellij Go plugin an open-source one. contributing and make that plugin works will help more developers to use GO lang.

[Repo](https://github.com/surapuramakhil/go-lang-idea-plugin)  

Thanks in advance

### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by agnivade** [comment]
Hi @surapuramakhil - I would request you to reach out to various forums listed in the [Questions](https://github.com/golang/go/wiki/Questions) wiki page for help. Also the golang [subreddit](https://reddit.com/r/golang/) is also there for things like this.

We use the issue tracker only to track bugs and feature proposals.

I will close this issue as there is nothing to be done on this from our side. Thanks.
