### ISSUE TITLE
I'm so sorry,the go module is so hard to use ,fuck it!

### ISSUE THREAD

**Issue by ThunderLT** [golang/go#33316]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by agnivade** [comment]
I am sorry that you feel that way about using modules. But please be mindful of our https://golang.org/conduct. You might want to take a look at the [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions.
