### ISSUE TITLE
sync: map crash at Store

### ISSUE THREAD

**Issue by hemaolong** [golang/go#33338]
Hi, it seems sync.Map crash randomly.
I can not reproduce this bug, it occurs about three times during last two months.

> panic: assignment to entry in nil map
> 
> goroutine 213908 [running]:
> sync.(*Map).Store(0xc0000d1818, 0x787340, 0xc01a6415e0, 0x786980, 0xc00026a548)
> 	**/usr/local/go/src/sync/map.go:160 +0x3c4**
> hive.(*SessionPipelineImpl).SetTag(0xc0000d17b8, 0x813957, 0x4, 0x786980, 0xc00026a548)
> 	/data1/heml/hrg_deploy/src/hive/session.go:246 +0x9a
> common.(*Room).Join(0xb2f2e0, 0x4e33a801b439e03, 0x884560, 0xc0000d17a0, 0x0)
> 	/data1/heml/hrg_deploy/src/common/room.go:65 +0x196
> main.(*preParser).OnSessionRead(0xc00000c5e0, 0x884560, 0xc0000d17a0, 0x7e4620, 0xc01af64fc0)
> 	/data1/heml/hrg_deploy/src/mail/main.go:64 +0x1a4
> hive.(*sessionImpl).runLogic(0xc0000d17a0)
> 	/data1/heml/hrg_deploy/src/hive/session.go:205 +0x279
> created by hive.(*sessionImpl).Start
> 	/data1/heml/hrg_deploy/src/hive/session.go:86 +0xb1

go version:  go version go1.10.4 linux/amd64
go env
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/root/.cache/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOOS="linux"
> GOPATH="/root/mario/gopkg:/data1/heml/hrg_deploy"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/local/go"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
> GCCGO="gccgo"
> CC="gcc"
> CXX="g++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build743823671=/tmp/go-build -gno-record-gcc-switches"

Thanks!

**Comment by hemaolong** [comment]
BTW, this is the code snippet

`/////////////////////////////////////////////////////////////
type SessionPipelineImpl struct {
	decoder CodecDecoder
	encoder CodecEncoder

	decoderPostHandlers []CodecDecoderPost
	encoderPreHandlers  []CodecEncoderPre

	eventHandler SessionEventHandler

	tags sync.Map
}

////////////////////////////////////////
func (self *SessionPipelineImpl) SetTag(k string, v interface{}) {
	if v != nil {
		**_self.tags.Store(k, v) // Line 246_**
	} else {
		self.tags.Delete(k)
	}
}`

**Comment by agnivade** [comment]
Hi @hemaolong - It would be great if you could provide us with a self-contained code sample that shows the issue.

Have you tried running the code under the race detector to confirm there are no races ?

Are you copying the map anywhere in your code ?

**Comment by hemaolong** [comment]
Hi @agnivade 
Sorry, I can not reproduce it with self-contained code until now.

There is no map-copying in my codes(I think).

I will try the 1.12.7 and run under the race detector latter.

Thanks.

**Comment by hemaolong** [comment]
I wonder if the code snippet cause the map-copying(fmt.Sprintf("%v", self.tags))?
```
func (self *sessionImpl) String() string {
	if self.conn == nil {
		return fmt.Sprintf("{addr:nil}")
	} else {
		return fmt.Sprintf("{addr:%v tag:%v}",
			self.conn.RemoteAddr(), 
			self.tags)
	}
}

/// 
type SessionPipelineImpl struct {
	decoder CodecDecoder
	encoder CodecEncoder

	decoderPostHandlers []CodecDecoderPost
	encoderPreHandlers  []CodecEncoderPre

	eventHandler SessionEventHandler

	tags sync.Map
}
```

**Comment by hemaolong** [comment]
Hi @agnivade 
It is my mistake. There are several data race in my codes.No new crash until now after fix the race codes.
It seems that the "**ClearTag**"(used to clear the sync.Map) crash the program, which cause the map-copying.

Thanks for your help!


```
==================
==================
WARNING: DATA RACE
func (self *sessionImpl) String() string {
	if self.conn == nil {
		return fmt.Sprintf("{addr:nil}")
	} else {
		return fmt.Sprintf("{addr:%v tag:%v}",
			self.conn.RemoteAddr(), self.tags)
	}
}
```

```
==================
==================
WARNING: DATA RACE
func (self *SessionPipelineImpl) ClearTag() {
	self.tags = sync.Map{}
}
```

**Comment by ALTree** [comment]
Nice. Closing here, then.
