### ISSUE TITLE
chtimes The parameter is incorrect.

### ISSUE THREAD

**Issue by gj52** [golang/go#33334]
I use Hugo (gohugo.io) in the latest version.
I should report the error here.

```
E:\hugo>hugo
INFO 2019/07/28 17:55:17 Using config file:
Building sites … INFO 2019/07/28 17:55:17 removing all files from destination that don't exist in static dirs
INFO 2019/07/28 17:55:17 syncing static files to E:\hugo\public
Total in 2 ms
Error: Error copying static files: chtimes E:\hugo\public: The parameter is incorrect.
```
I'm wondering why there is an  invalid colon / double dot  E:\hugo\public:

**Comment by dominikh** [comment]
`<syscall> <path>: <error message>`.

Also, this is the Go issue tracker, and you seem to be having a problem with Hugo, not Go.
