### ISSUE TITLE
runtime: slice allocation with 1<<33 cap not showing up in profile

### ISSUE THREAD

**Issue by zeast** [golang/go#33342]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
</pre></details>

### What did you do?

```
func main() {
	go func() {
		l, _ := net.Listen("tcp", "0.0.0.0:8989")
		http.Serve(l, http.DefaultServeMux)
	}()

	bigMem := make([]byte, 0, 1<<33)

	time.Sleep(time.Hour)

	_ = bigMem
}
```

runnable program: https://play.golang.org/p/RPebfcdzpvI

### What did you expect to see?
In normal, I think `bigMem` will be shown when I use `go tool pprof xxx/heap`
The program has been simplified, In my case bigMem in other package, and I want to find who use the memory from a lot of heap recordes.

### What did you see instead?
I did't see information about `bigMem`

### What I found
I think the reason in malloc.go +1014
```
	if rate := MemProfileRate; rate > 0 {
		if rate != 1 && int32(size) < c.next_sample {
			c.next_sample -= int32(size)
		} else {
			mp := acquirem()
			profilealloc(mp, x, size)
			releasem(mp)
		}
	}
```
In fact size bigger than maxint32, so int32(size) maybe negative or zero, and never be recorded, perhaps definition c.next_sample uint64 is better ?  or  always record when size bigger than a threshold.

**Comment by randall77** [comment]
I think changing the type to `uintptr` is the right fix.
Testing is a bit challenging - we'd need a multi-gig machine, which isn't always available.
