### ISSUE TITLE
strconv: fmt.Sscanf "0x" "%v" regression in 1.13beta1/tip

### ISSUE THREAD

**Issue by speter** [golang/go#33356]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +01d137262a Mon Jul 29 21:07:49 2019 +0000 linux/amd64
go version go1.13beta1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Not with stable releases, yes with latest beta.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/peter/.cache/go-build"
GOENV="/home/peter/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/peter/tmp"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/peter/tmp/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/peter/tmp/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/peter/tmp/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build986871235=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
https://play.golang.org/p/rQsfk3s-_ai

### What did you expect to see?
<nil> as with stable releases

### What did you see instead?
strconv.ParseInt: parsing "0x": invalid syntax

go-gcfg/gcfg#17

**Comment by robpike** [comment]
It's not clear to me that it's a regression so much as catching a previously missed error. "0x" is indeed invalid syntax.

**Comment by andybons** [comment]
Thanks for the issue.

`0x` is in fact invalid syntax. 1.13 has just made it more strict. I’m going to close this issue. If you feel this is in error then please comment.
