### ISSUE TITLE
cmd/link: ELF linker generates incorrect local dynamic symbol count

### ISSUE THREAD

**Issue by shachaf** [golang/go#33358]
When generating a dynamically-linked ELF file, the ".dynsym" section's info field specifies the number of local symbols. It currently seems to generate 0, but symbol 0 is reserved and always local, so the value should be at least 1. `readelf` (from GNU binutils 2.30) reports this warning.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

It is present in master at the time of writing.

See https://github.com/golang/go/blob/master/src/cmd/link/internal/ld/elf.go#L1934

### What operating system and processor architecture are you using (`go env`)?

linux_amd64

### What did you do?

Build a program that uses dynamic linking. E.g.

```go
package main

import "net"

func main() {
	net.Dial("", "")
}
```

And look at the .dynsym info field.

### What did you expect to see?

.dynsym info field >= 1.

### What did you see instead?

.dynsym info field 0, and no warnings from `readelf`.

```
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [11] .dynsym           DYNSYM           000000000052c1e0  0012c1e0
       0000000000000390  0000000000000018   A      10     0     8
readelf: Warning: local symbol 0 found at index >= .dynsym's sh_info value of 0
```

**Comment by agnivade** [comment]
@ianlancetaylor

**Comment by ianlancetaylor** [comment]
Thanks.  I agree that this should be fixed.

**Comment by shachaf** [comment]
I suspect this won't happen if there's a .dynsym section, but I should mention that if there are no global symbols, this code won't set `sh.info` (it should be set to the local symbol count regardless).

**Comment by cuonglm** [comment]
@shachaf good catch, fixed in https://go-review.googlesource.com/c/go/+/192600
