### ISSUE TITLE
x/mobile: handle assets on iOS

### ISSUE THREAD

**Issue by CanRui-Wu** [golang/go#33350]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.12.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wucanrui/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/wucanrui/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.7/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0_/j6m36l9s0psg9xm5ggt2_b680000gp/T/go-build792194215=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I am new to IOS.

I build an IOS framework file by using gomobile.

I run gomobile bind -target=ios xxx (xxx is a package with a subdirectory "assets", and there are a file 'config.json' in assets). 

In xxx package, I use asset.Open() to get the asset but it failed with log (no such file or directory). And then when I check the 'bind_iosapp.go' in gomobile, I find that it does not handle the "assets" directory at all.

### What did you expect to see?
I can use my asset file in xxx.framework by using golang.

### What did you see instead?
I see this tip on godoc of gomobile.(On iOS an asset is a resource stored in the application bundle. Resources can be loaded using the same relative paths). How can I get the asset file? Should I use the asset.Open API? What the path I should put the asset file into IOS is?

**Comment by julieqiu** [comment]
For asking questions about learning the language, see one of our forums: https://golang.org/wiki/Questions We only use this issue tracker for tracking bugs. People in the forums can explain what is happening here.
