### ISSUE TITLE
gollvm: potential redundant CABIOracle::analyze over the same set of parameter/result types

### ISSUE THREAD

**Issue by shawn-xdji** [golang/go#33367]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.2 gollvm LLVM 9.0.0svn linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xiaji01/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/xiaji01/.go"
GOPROXY=""
GORACE=""
GOROOT="/home/xiaji01/build/gl.0723.share.gcc9"
GOTMPDIR=""
GOTOOLDIR="/home/xiaji01/build/gl.0723.share.gcc9/tools"
GCCGO="/home/xiaji01/build/gl.0723.share.gcc9/bin/llvm-goc"
CC="/home/xiaji01/util/bin/gcc"
CXX="/home/xiaji01/util/bin/g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build100884527=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
</pre></details>

### What did you do?

Found a potential redundancy of CABIOracle::analysis, it has no side effect to IR creation as we cache llvm and backend objects, wondering if a fix could be made to avoid confusion. 

Initial analysis:

A. line 6231 calls TypeManager::makeLLVMFunctionType and TypeManager::functionType, a llvm::FunctionType and a BFunctionType are created (assume no cached type is available).

B. line 6233 instantiates a new CABIOracle object in constructing Bfunction, it extracts the same parameter types and result type from 'functype' to run its analysis.

Could 'functype->type_' be passed to CABIOracle's ctor in Bfunction::Bfunction to prevent the analysis being conducted once again? 

//gogo.cc
6230	
6231	      Btype* functype = this->type_->get_backend_fntype(gogo);
6232	      this->fndecl_ =
6233	          gogo->backend()->function(functype, no->get_id(gogo), asm_name,
6234					    flags, this->location());

**Comment by ALTree** [comment]
cc @thanm

**Comment by shawn-xdji** [comment]
Perhaps trying to keep and reuse the first CABIOracle object in constructing Bfunction is also an option.

**Comment by thanm** [comment]
[ apologies for the late response, I was OOO for a while ]

You're right that there is some redundant analysis going on, but I guess the question in my mind is whether this matters? Seems as though CABIOracle::analyze is doing a relatively modest amount of work, not clear to me why we'd want to restructure the code to avoid multiple calls to it.  Is there any additional context I'm missing?

**Comment by shawn-xdji** [comment]
Thanks for replying.
There is no other context, the two passes do exactly the same thing, I think it's fine to leave it as is, closing the issue.
