### ISSUE TITLE
doc: describe/summarize error value features in the Go 1.13 release notes

### ISSUE THREAD

**Issue by cespare** [golang/go#33365]
The error value changes landing in Go 1.13 are one piece of the headline Go 2 "better error handling" improvements. However, [the only mention in the Go 1.13 release notes](https://tip.golang.org/doc/go1.13#errors) right now is a short list of the new functions in the "Minor changes to the library" section.

I think these changes are important enough to warrant a description/summary at the top level of the release notes. Perhaps we should link to the design or mention the expected upcoming changes that will also tie in. Additionally, if we expect people to be adopting these features widely, perhaps we should include some prescriptive language to that end. (Or will there be a blog post?)

This is related to #33364, where the new features are also inadequately described in the package documentation.

/cc @jba @neild

**Comment by ianlancetaylor** [comment]
@jba Want to work on this issue along with your revamp of the errors package doc?

**Comment by jba** [comment]
Sure.
