### ISSUE TITLE
Unexpected assignment to global variable

### ISSUE THREAD

**Issue by romanzac** [golang/go#33377]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/roman/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/roman/sources/gospace"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build333493096=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

1) nextUIDNumber defined at package level outside function AddUserLDAP
2) function body is
func AddUserLDAP(user *User) (err error) {
.
.
.

nextUIDNumber = 0

	for _, entry := range sr.Entries {
		for _, attr := range entry.Attributes {

			if attr.Name == "uidNumber" {

				log.Output(1, "LDAPadd: Attr Name: "+attr.Name+" Value: "+attr.Values[0])

				i, _ := strconv.Atoi(attr.Values[0])
				if i > nextUIDNumber {
					str := strconv.Itoa(i)
					log.Output(1, "LDAPadd: Condition passed: value of i. "+str)
					nextUIDNumber = i + 1

					log.Output(1, "LDAPadd: nextUIDNumber: "+strconv.Itoa(nextUIDNumber))
				}
			}
			if attr.Name == "gidNumber" {
				if i, _ := strconv.Atoi(attr.Values[0]); i > nextGIDNumber {
					nextUIDNumber = i + 1
				}
			}
		}
	}

	log.Output(1, "LDAPadd: Before no Users check: nextUIDNumber: "+strconv.Itoa(nextUIDNumber))
	// Check for cases with no users in LDAP
	if nextUIDNumber == 0 {
		nextUIDNumber = 1000
	}

	if nextGIDNumber == 0 {
		nextGIDNumber = 100
	}

	log.Output(1, "LDAPadd: After no Users check: nextUIDNumber: "+strconv.Itoa(nextUIDNumber))

.
.
.
}

### What did you expect to see?
nextUIDNumber == 1051

### What did you see instead?
nextUIDNumber == 101

2019/07/31 11:33:11 Adding username: test010
2019/07/31 11:33:11 LDAPadd: Attr Name: uidNumber Value: 1050
2019/07/31 11:33:11 LDAPadd: Condition passed: value of i. 1050
2019/07/31 11:33:11 LDAPadd: nextUIDNumber: 1051
2019/07/31 11:33:11 LDAPadd: Attr Name: uidNumber Value: 101
2019/07/31 11:33:11 LDAPadd: Attr Name: uidNumber Value: 101
2019/07/31 11:33:11 LDAPadd: Attr Name: uidNumber Value: 101
2019/07/31 11:33:11 LDAPadd: Attr Name: uidNumber Value: 101
2019/07/31 11:33:11 LDAPadd: Attr Name: uidNumber Value: 101
2019/07/31 11:33:11 LDAPadd: Attr Name: uidNumber Value: 101
2019/07/31 11:33:11 LDAPadd: Attr Name: uidNumber Value: 101
2019/07/31 11:33:11 LDAPadd: Attr Name: uidNumber Value: 101
2019/07/31 11:33:11 LDAPadd: Attr Name: uidNumber Value: 101
2019/07/31 11:33:11 LDAPadd: Attr Name: uidNumber Value: 101
2019/07/31 11:33:11 LDAPadd: Before no Users check: nextUIDNumber: 101
2019/07/31 11:33:11 LDAPadd: After no Users check: nextUIDNumber: 101

**Comment by ianlancetaylor** [comment]
Show us a complete program that we can use to recreate the problem.  It's impossible to diagnose from a partial program.  Thanks.

**Comment by AlexRouSg** [comment]
This is just a hunch but ...
```go
if attr.Name == "gidNumber" {
	if i, _ := strconv.Atoi(attr.Values[0]); i > nextGIDNumber {
		nextUIDNumber = i + 1
	}
}
```
It feels like you meant to have `nextGIDNumber = i + 1`?

**Comment by romanzac** [comment]
Yes，exactly I hope nextUIDNumber is the highest found in ldap search result plus 1.

**Comment by romanzac** [comment]
Complete code:

// AddUserLDAP adds user to ldap 
func AddUserLDAP(user *User) (err error) {

	// Search for all uid and gid numbers to determine the next one to be added
	searchRequest := ldap.NewSearchRequest(
		LDAPbaseDN,
		ldap.ScopeWholeSubtree, ldap.NeverDerefAliases, 0, 0, false,
		"(&(objectClass=*)(uid=*))",
		[]string{"uidNumber", "gidNumber"},
		nil,
	)

	LDAPconn, err := ldap.Dial("tcp", LDAPurl)
	if err != nil {
		log.Println(err)
	}
	defer LDAPconn.Close()

	err = LDAPconn.Bind(LDAPbindDN, LDAPpwd)
	if err != nil {
		// error in ldap bind
		log.Println(err)
	}

	// Get all entries' uidNumber and gidNumber to know the highest one
	sr, err := LDAPconn.Search(searchRequest)
	if err != nil {
		log.Output(1, "LDAPsearch failed: "+err.Error())
		return err
	}

	nextUIDNumber = 0

	for _, entry := range sr.Entries {
		for _, attr := range entry.Attributes {

			if attr.Name == "uidNumber" {

				log.Output(1, "LDAPadd: Attr Name: "+attr.Name+" Value: "+attr.Values[0])

				i, _ := strconv.Atoi(attr.Values[0])
				if i > nextUIDNumber {
					str := strconv.Itoa(i)
					log.Output(1, "LDAPadd: Condition passed: value of i. "+str)
					nextUIDNumber = i + 1

					log.Output(1, "LDAPadd: nextUIDNumber: "+strconv.Itoa(nextUIDNumber))
				}
			}
			if attr.Name == "gidNumber" {
				if i, _ := strconv.Atoi(attr.Values[0]); i > nextGIDNumber {
					nextUIDNumber = i + 1
				}
			}
		}
	}

	log.Output(1, "LDAPadd: Before no Users check: nextUIDNumber: "+strconv.Itoa(nextUIDNumber))
	// Check for cases with no users in LDAP
	if nextUIDNumber == 0 {
		nextUIDNumber = 1000
	}

	if nextGIDNumber == 0 {
		nextGIDNumber = 100
	}

	log.Output(1, "LDAPadd: After no Users check: nextUIDNumber: "+strconv.Itoa(nextUIDNumber))

	addRequest := ldap.NewAddRequest("uid="+user.UserName+","+LDAPuserBaseDN, nil)

	addRequest.Attribute("objectClass", []string{"top", "account", "posixAccount", "shadowAccount"})
	addRequest.Attribute("cn", []string{user.UserName})
	addRequest.Attribute("uid", []string{user.UserName})
	addRequest.Attribute("uidNumber", []string{strconv.Itoa(nextUIDNumber)})
	addRequest.Attribute("gidNumber", []string{strconv.Itoa(nextGIDNumber)})
	addRequest.Attribute("homeDirectory", []string{"/home/" + user.UserName})
	addRequest.Attribute("loginShell", []string{"/bin/bash"})
	addRequest.Attribute("gecos", []string{user.UserName})
	addRequest.Attribute("userPassword", []string{"{crypt}" + user.Pwd})

	err = LDAPconn.Add(addRequest)
	if err != nil {
		log.Output(1, "LDAPadd failed: "+err.Error())
		return err
	}

	return nil
}

**Comment by romanzac** [comment]
I tried couple of things:
1) Have local declaration  nextUIDNumber := 0 or var nextUIDNumber int just before two for loops. Behavior was the same with global declaration.
2) When local declaration was used, I had nextUIDNumber = i  assigment which resulted into even worse behavior:
2019/07/31 11:06:37 Adding username: test006
2019/07/31 11:06:37 Authenticator: User does not exist or too many entries returned
2019/07/31 11:06:37 LDAPadd: Attr Name: uidNumber Value: 1050
2019/07/31 11:06:37 LDAPadd: Condition passed: value of i. 1050
2019/07/31 11:06:37 LDAPadd: nextUIDNumber: 1050
2019/07/31 11:06:37 LDAPadd: Attr Name: uidNumber Value: 101
2019/07/31 11:06:37 LDAPadd: Condition passed: value of i. 101
2019/07/31 11:06:37 LDAPadd: nextUIDNumber: 101
2019/07/31 11:06:37 LDAPadd: Attr Name: uidNumber Value: 101
2019/07/31 11:06:37 LDAPadd: Condition passed: value of i. 101
2019/07/31 11:06:37 LDAPadd: nextUIDNumber: 101
2019/07/31 11:06:37 LDAPadd: Attr Name: uidNumber Value: 101
2019/07/31 11:06:37 LDAPadd: Condition passed: value of i. 101
2019/07/31 11:06:37 LDAPadd: nextUIDNumber: 101
2019/07/31 11:06:37 LDAPadd: Attr Name: uidNumber Value: 101
2019/07/31 11:06:37 LDAPadd: Condition passed: value of i. 101
2019/07/31 11:06:37 LDAPadd: nextUIDNumber: 101
2019/07/31 11:06:37 LDAPadd: Attr Name: uidNumber Value: 101
2019/07/31 11:06:37 LDAPadd: Condition passed: value of i. 101
2019/07/31 11:06:37 LDAPadd: nextUIDNumber: 101
2019/07/31 11:06:37 LDAPadd: Attr Name: uidNumber Value: 101
2019/07/31 11:06:37 LDAPadd: Condition passed: value of i. 101
2019/07/31 11:06:37 LDAPadd: nextUIDNumber: 101
2019/07/31 11:06:37 LDAPadd: Before no Users check: nextUIDNumber: 100
2019/07/31 11:06:37 LDAPadd: After no Users check: nextUIDNumber: 101

**Comment by AlexRouSg** [comment]
Look at the code I pasted earlier carefully.

You are checking for `i > nextGIDNumber` but assigning `nextUIDNumber = i + 1`

**Comment by romanzac** [comment]
I am very sorry. Problem solved. Thank you.
