### ISSUE TITLE
x/mobile: android bind failing

### ISSUE THREAD

**Issue by davidsteed** [golang/go#33382]
### What version of Go are you using (`go version`)?1.12.5

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?darwin

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you see instead? gomobile: /Users/davidsteed/go/bin/gobind -lang=go,java -outdir=/var/folders/v9/_mzflmvx1t5d5tmv6b4211tc0000gn/T/gomobile-work-641481098 scp/ped failed: exit status 1
failed to open Java support file: open /Users/davidsteed/src/golang.org/x/mobile/bind/java/LoadJNI.java: no such file or directory
failed to copy Java support file: invalid argument

**Comment by AlexRouSg** [comment]
Your gomobile binary and sources do not match. How did you install gomobile?

**Comment by davidsteed** [comment]
go get golang.org/x/mobile/cmd/gomobile

**Comment by AlexRouSg** [comment]
Try `go get -u golang.org/x/mobile/cmd/gomobile`

**Comment by davidsteed** [comment]
Davids-MacBook-Pro:ped davidsteed$ go get -u
golang.org/x/mobile/cmd/gomobile
Davids-MacBook-Pro:ped davidsteed$ gomobile bind -target android .
gomobile: /Users/davidsteed/go/bin/gobind -lang=go,java
-outdir=/var/folders/v9/_mzflmvx1t5d5tmv6b4211tc0000gn/T/gomob
ile-work-598779738 scp/ped failed: exit status 1
failed to open Java support file: open /Users/davidsteed/src/
golang.org/x/mobile/bind/java/LoadJNI.java: no such file
or directory
failed to copy Java support file: invalid argument

**Comment by davidsteed** [comment]
I had GOMODULES turned off.  When I put it back to automatic this went away
and I got this error

go: writing go.sum: open /Users/davidsteed/go/pkg/mod/
github.com/go-openapi/runtime@v0.19.0/go.sum637570821.tmp: permission denied

**Comment by AlexRouSg** [comment]
Try deleting the gomobile binary and sources manually and run `gomobile -h` to make sure it's not found. If it doesn't error then you have another gomobile binary somewhere. Then `go get ...` again.

I'm sure your binary is outdated because `LoadJNI.java` was removed from the sources a while ago.

> I had GOMODULES turned off.  When I put it back to automatic this went away
> and I got this error

gomobile does not work with modules, so you need to do everything the gopath way.

**Comment by davidsteed** [comment]
Deleted all references to it reinstalled from scratch and still get the
same error

**Comment by AlexRouSg** [comment]
Can you do the same for the `gobind` command?

**Comment by davidsteed** [comment]
That has fixed it.  Thank you very much for your help

**Comment by AlexRouSg** [comment]
Can you please close this issue then?
