### ISSUE TITLE
x/sys/unix: missing SIGSTKFLT for mips64le

### ISSUE THREAD

**Issue by Ydcool** [golang/go#33381]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 linux/mips64le
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="mips64le"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="mips64le"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/opt/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-go1.12.5"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-go1.12.5/pkg/tool/linux_mips64le"
GCCGO="gccgo"
GOMIPS64="hardfloat"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -mabi=64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build457678816=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```shell
git clone -b v18.09.8-ce https://github.com/docker/docker-ce "$GOPATH/src/github.com/docker/"
cd $GOPATH/src/github.com/docker
ln -s $GOPATH/src/github.com/docker/docker-ce/components/engine docker
cd $GOPATH/src/github.com/docker/docker
sh -x ./hack/make.sh dynbinary
```

### What did you expect to see?

build docker without error related to golang.org/x/sys

### What did you see instead?

\# github.com/docker/docker/pkg/signal
pkg/signal/signal_linux.go:35:14: undefined: unix.SIGSTKFLT

**Comment by Ydcool** [comment]
I wonder if I  could submit a PR for  [golang.org/x/sys/unix/zerros_linux_mips64le.go](https://github.com/golang/sys/blob/master/unix/zerrors_linux_mips64le.go), just adding the code like this: 

at line 2013:
```go
SIGSTKFLT = syscall.Signal(0x16)
```

And this works for me.

**Comment by ianlancetaylor** [comment]
As far as I can tell, the x/sys/unix package is correct.  MIPS64le GNU/Linux does not have a `SIGSTKFLT` signal.  Signal number 0x16 is `SIGIO` aka `SIGPOLL`.  You would see the same error compiling an equivalent C program on MIPS64le GNU/Linux.  Note that in the x86 header file `SIGSTKFLT` is marked as obsolete.

This needs to be fixed in Docker itself.
