### ISSUE TITLE
benchmark pending by unknown reason

### ISSUE THREAD

**Issue by FelixSeptem** [golang/go#33383]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes,I use go1.12 already

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/XXX/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/XXX/.gvm/pkgsets/go1.12/global"
GOPROXY=""
GORACE=""
GOROOT="/Users/XXX/.gvm/gos/go1.12"
GOTMPDIR=""
GOTOOLDIR="/Users/XXX/.gvm/gos/go1.12/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/90/hr1_x8993q9fyw7gf7g_85v80000gp/T/go-build592076382=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

runnining benchmark like https://github.com/FelixSeptem/sizepool/blob/master/sizepool_test.go#L111-L119 but pending forever ,running result like https://www.travis-ci.org/FelixSeptem/sizepool

### What did you expect to see?

running benchmark like usual

### What did you see instead?

the benchmark pending forever

**Comment by AlexRouSg** [comment]
There are 2 main things wrong with your code.

```
func (p *sizePoolChan) BGet(timeout time.Duration) (interface{}, error) {
	ticker := time.NewTicker(timeout)
        ...
}
```

You need to add a `defer ticker.Stop()`, also a `time.Timer` is better for one time events.


```
func BenchmarkSizePoolChan_BGet(b *testing.B) {
	p := NewChanPool(65535, newConn, resetConn)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		if _, err := p.BGet(time.Millisecond); err != nil {
			_ = err
		}
	}
}
```

`b.N` is a very large number, e.g. 1000000. worst case it will take ~1000000 ms = 16.67 minutes

If you must use `time.Millisecond` then you need to tell test to run it less times. e.g. `go test -benchtime=100x` 100x = run 100 times.

**Comment by FelixSeptem** [comment]
> There are 2 main things wrong with your code.
> 
> ```
> func (p *sizePoolChan) BGet(timeout time.Duration) (interface{}, error) {
> 	ticker := time.NewTicker(timeout)
>         ...
> }
> ```
> 
> You need to add a `defer ticker.Stop()`, also a `time.Timer` is better for one time events.
> 
> ```
> func BenchmarkSizePoolChan_BGet(b *testing.B) {
> 	p := NewChanPool(65535, newConn, resetConn)
> 	b.ResetTimer()
> 	for i := 0; i < b.N; i++ {
> 		if _, err := p.BGet(time.Millisecond); err != nil {
> 			_ = err
> 		}
> 	}
> }
> ```
> 
> `b.N` is a very large number, e.g. 1000000. worst case it will take ~1000000 ms = 16.67 minutes
> 
> If you must use `time.Millisecond` then you need to tell test to run it less times. e.g. `go test -benchtime=100x` 100x = run 100 times.

I don't specify execute time but I give a running time here by 
`go test -run none -bench . -benchtime 1s -benchmem`, but it still pending more than 10minutes

**Comment by FelixSeptem** [comment]
also, I see the sample code snippet as below:
```
`
func BenchmarkBigLen(b *testing.B) {
   big := NewBig()
   b.ResetTimer()
   for i := 0; i < b.N; i++ {
       big.Len()
   }
}
```

**Comment by AlexRouSg** [comment]
The thing with using `1s` over `100x` is that `1s` means if this `b.N` took over 1s then stop.It runs the benchmark multiple times with increasing `b.N`. So at the start `b.N` will be small and it thinks it's a good idea to do a large maybe 1000000 run and then it doesn't stop until it finishes.

So `100x` means literally run 100 times and don't try to be smart about it.

**Comment by FelixSeptem** [comment]
I can tell the difference between `100x` and `1s`.But I can't understand why it will pending a lot of time by `1s`

**Comment by AlexRouSg** [comment]
Because `1s` does not mean stop running immediately after `1s`. The check for `1s` is after the function returns. So if it takes a very long time it will not stop.

**Comment by FelixSeptem** [comment]
I try to fix it, the pending version code:
```go
func BenchmarkSizePoolChan_BGet(b *testing.B) {
	p := NewChanPool(65535, newConn, resetConn)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		if _, err := p.BGet(time.Millisecond); err != nil {
			_ = err
		}
	}
}
```
and the new pass version:
```go
func BenchmarkSizePoolChan_BGet(b *testing.B) {
	p := NewChanPool(65535, newConn, resetConn)
	fc := new(fakeConn)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		p.Put(fc)
		if _, err := p.BGet(time.Nanosecond); err != nil {
			_ = err
		}
	}
}
```
the difference is the previous one will trigger a lot of times of `Ticker.C`,and the latter one won't.I suspect that a big amount of `Ticker.C` may cause some problem in benchmark situation.

**Comment by FelixSeptem** [comment]
I reproduce it with https://play.golang.org/p/gAXjYIdJb2K  no clear reason to pending with benchmark

**Comment by AlexRouSg** [comment]
As I've already said in my very first reply, you need to have a `defer ticker.Stop()`

tickers keep running even after the function returns, forever. That is why you need to tell it to stop or use `time.Timer` which only trigger once.

**Comment by FelixSeptem** [comment]
> As I've already said in my very first reply, you need to have a `defer ticker.Stop()`
> 
> tickers keep running even after the function returns, forever. That is why you need to tell it to stop or use `time.Timer` which only trigger once.

I have tried to manually call `defer ticker.Stop`,no help for the pending problem

**Comment by AlexRouSg** [comment]
> I have tried to manually call defer ticker.Stop,no help for the pending problem

With which code? With `BenchmarkSizePoolChan_BGet` you need to do that and your code gets very slow with big `b.N` so you need to figure out why it gets slow or as I've already said, tell test to don't use a big `b.N` by using `-benchtime=1000x` or some other number. 

There is no bug here, just the code you have run slow when calling in a long loop. You will find better help asking in the places listed in https://github.com/golang/go/wiki/Questions

**Comment by FelixSeptem** [comment]
> > I have tried to manually call defer ticker.Stop,no help for the pending problem
> 
> With which code? With `BenchmarkSizePoolChan_BGet` you need to do that and your code gets very slow with big `b.N` so you need to figure out why it gets slow or as I've already said, tell test to don't use a big `b.N` by using `-benchtime=1000x` or some other number.
> 
> There is no bug here, just the code you have run slow when calling in a long loop. You will find better help asking in the places listed in https://github.com/golang/go/wiki/Questions

I can't agree your explanation. As I post in https://github.com/golang/go/issues/33383#issuecomment-517089766  I do more operation in the second code snippet,and it doesn't pending. Obvious, it's not due the long loop for the first code to pending.

**Comment by AlexRouSg** [comment]
```
ticker := time.NewTicker(timeout)
	select {
	case i := <-p.pool:
		return i, nil
	case <-ticker.C:
		return nil, ErrNoEnoughItem
	}
```

`case i := <-p.pool:` You drain from the pool, after 65535 times the pool is empty, so this statement blocks forever. 65535 because `p := NewChanPool(65535, newConn, resetConn)`

`case <-ticker.C:` this statement fires after 1ms. 

So now every single iteration of the loop after 65535 times will be 1ms long. If `b.N` is 1000000, that is a very very long time.
 
`p.Put(fc)` works because you are adding to the pool so the pool is never empty, so `case <-ticker.C:` will not fire.

**Comment by FelixSeptem** [comment]
> ```
> ticker := time.NewTicker(timeout)
> 	select {
> 	case i := <-p.pool:
> 		return i, nil
> 	case <-ticker.C:
> 		return nil, ErrNoEnoughItem
> 	}
> ```
> 
> `case i := <-p.pool:` You drain from the pool, after 65535 times the pool is empty, so this statement blocks forever. 65535 because `p := NewChanPool(65535, newConn, resetConn)`
> 
> `case <-ticker.C:` this statement fires after 1ms.
> 
> So now every single iteration of the loop after 65535 times will be 1ms long. If `b.N` is 1000000, that is a very very long time.
> 
> `p.Put(fc)` works because you are adding to the pool so the pool is never empty, so `case <-ticker.C:` will not fire.

I got it.Thanks for your reply.The benchmark function must run the target code b.N times. During benchmark execution, b.N is adjusted until the benchmark function lasts long enough to be timed reliably. when I give the params with `65535`, the function run time will not be stable for a long range of time,I shall give it `0` or `1000000`(or other number big enough) to let it run stable. Thanks for your help.I will close this issue.
