### ISSUE TITLE
x/tools/gopls: data race accessing flags

### ISSUE THREAD

**Issue by jayconrod** [golang/go#33392]
Log 1: https://storage.googleapis.com/go-build-log/fe8a8664/linux-amd64-race_e77173df.log

<details><pre>
==================
WARNING: DATA RACE
Read at 0x00c0001055e0 by goroutine 111:
  golang.org/x/tools/internal/lsp/cmd.(*cmdClient).LogMessage()
      /workdir/gopath/src/golang.org/x/tools/internal/lsp/cmd/cmd.go:252 +0x373
  golang.org/x/tools/internal/lsp/protocol.clientHandler.Deliver()
      /workdir/gopath/src/golang.org/x/tools/internal/lsp/protocol/tsclient.go:55 +0xab9
  golang.org/x/tools/internal/lsp/protocol.(*clientHandler).Deliver()
      <autogenerated>:1 +0x94
  golang.org/x/tools/internal/jsonrpc2.(*Conn).Run.func1()
      /workdir/gopath/src/golang.org/x/tools/internal/jsonrpc2/jsonrpc2.go:370 +0x1c5

Previous write at 0x00c0001055e0 by goroutine 39:
  golang.org/x/tools/internal/tool.addFlags()
      /workdir/go/src/flag/flag.go:112 +0x8ca
  golang.org/x/tools/internal/tool.addFlags()
      /workdir/gopath/src/golang.org/x/tools/internal/tool/tool.go:167 +0xb14
  golang.org/x/tools/internal/tool.Main()
      /workdir/gopath/src/golang.org/x/tools/internal/tool/tool.go:89 +0x204
  golang.org/x/tools/internal/lsp/cmd_test.(*runner).Diagnostics.func1()
      /workdir/gopath/src/golang.org/x/tools/internal/lsp/cmd/check_test.go:25 +0xc6
  golang.org/x/tools/internal/lsp/cmd_test.captureStdOut()
      /workdir/gopath/src/golang.org/x/tools/internal/lsp/cmd/cmd_test.go:92 +0x1b6
  golang.org/x/tools/internal/lsp/cmd_test.(*runner).Diagnostics()
      /workdir/gopath/src/golang.org/x/tools/internal/lsp/cmd/check_test.go:24 +0x28e
  golang.org/x/tools/internal/lsp/tests.Run.func2()
      /workdir/gopath/src/golang.org/x/tools/internal/lsp/tests/tests.go:276 +0x19e
  testing.tRunner()
      /workdir/go/src/testing/testing.go:909 +0x199

Goroutine 111 (running) created at:
  golang.org/x/tools/internal/jsonrpc2.(*Conn).Run()
      /workdir/gopath/src/golang.org/x/tools/internal/jsonrpc2/jsonrpc2.go:354 +0x7f3

Goroutine 39 (running) created at:
  testing.(*T).Run()
      /workdir/go/src/testing/testing.go:960 +0x651
  golang.org/x/tools/internal/lsp/tests.Run()
      /workdir/gopath/src/golang.org/x/tools/internal/lsp/tests/tests.go:267 +0x1fb
  golang.org/x/tools/internal/lsp/cmd_test.testCommandLine()
      /workdir/gopath/src/golang.org/x/tools/internal/lsp/cmd/cmd_test.go:45 +0x319
  golang.org/x/tools/go/packages/packagestest.TestAll.func1()
      /workdir/gopath/src/golang.org/x/tools/go/packages/packagestest/export.go:101 +0x91
  testing.tRunner()
      /workdir/go/src/testing/testing.go:909 +0x199
==================
</pre></details>

Log 2: https://build.golang.org/log/fc6af8558a1f11307b1dd3113a1a7c5e744e451a

<details><pre>
==================
WARNING: DATA RACE
Read at 0x00c000119ae0 by goroutine 241:
  golang.org/x/tools/internal/lsp/cmd.(*cmdClient).LogMessage()
      /workdir/gopath/src/golang.org/x/tools/internal/lsp/cmd/cmd.go:252 +0x373
  golang.org/x/tools/internal/lsp/protocol.clientHandler.Deliver()
      /workdir/gopath/src/golang.org/x/tools/internal/lsp/protocol/tsclient.go:55 +0xaba
  golang.org/x/tools/internal/lsp/protocol.(*clientHandler).Deliver()
      <autogenerated>:1 +0x94
  golang.org/x/tools/internal/jsonrpc2.(*Conn).Run.func1()
      /workdir/gopath/src/golang.org/x/tools/internal/jsonrpc2/jsonrpc2.go:370 +0x18b

Previous write at 0x00c000119ae0 by goroutine 35:
  golang.org/x/tools/internal/tool.addFlags()
      /workdir/go/src/flag/flag.go:112 +0x8dc
  golang.org/x/tools/internal/tool.addFlags()
      /workdir/gopath/src/golang.org/x/tools/internal/tool/tool.go:167 +0xb28
  golang.org/x/tools/internal/tool.Main()
      /workdir/gopath/src/golang.org/x/tools/internal/tool/tool.go:89 +0x205
  golang.org/x/tools/internal/lsp/cmd_test.(*runner).Diagnostics.func1()
      /workdir/gopath/src/golang.org/x/tools/internal/lsp/cmd/check_test.go:25 +0xc6
  golang.org/x/tools/internal/lsp/cmd_test.captureStdOut()
      /workdir/gopath/src/golang.org/x/tools/internal/lsp/cmd/cmd_test.go:92 +0x194
  golang.org/x/tools/internal/lsp/cmd_test.(*runner).Diagnostics()
      /workdir/gopath/src/golang.org/x/tools/internal/lsp/cmd/check_test.go:24 +0x28f
  golang.org/x/tools/internal/lsp/tests.Run.func2()
      /workdir/gopath/src/golang.org/x/tools/internal/lsp/tests/tests.go:276 +0x19e
  testing.tRunner()
      /workdir/go/src/testing/testing.go:865 +0x163

Goroutine 241 (running) created at:
  golang.org/x/tools/internal/jsonrpc2.(*Conn).Run()
      /workdir/gopath/src/golang.org/x/tools/internal/jsonrpc2/jsonrpc2.go:354 +0x876

Goroutine 35 (running) created at:
  testing.(*T).Run()
      /workdir/go/src/testing/testing.go:916 +0x65a
  golang.org/x/tools/internal/lsp/tests.Run()
      /workdir/gopath/src/golang.org/x/tools/internal/lsp/tests/tests.go:267 +0x1fb
  golang.org/x/tools/internal/lsp/cmd_test.testCommandLine()
      /workdir/gopath/src/golang.org/x/tools/internal/lsp/cmd/cmd_test.go:45 +0x2d4
  golang.org/x/tools/go/packages/packagestest.TestAll.func1()
      /workdir/gopath/src/golang.org/x/tools/go/packages/packagestest/export.go:101 +0x91
  testing.tRunner()
      /workdir/go/src/testing/testing.go:865 +0x163
==================
</details></pre>

cc @stamblerre

**Comment by stamblerre** [comment]
I think that this is related to @ianthehat's changes to the `internal/jsonrpc2` package, so he will likely have more insight when he's back in the office.
