### ISSUE TITLE
Forwarded declared C struct shared the same memory address in cgo

### ISSUE THREAD

**Issue by sammyne** [golang/go#33398]
Workaround wanted, any sugguestion?

source code repository: https://github.com/sammyne/playground-go/tree/master/forwarded-declared-c-struct

### Environment
- OS: ubuntu: 18.04
- CMake: >=3.10
- Compiler: g++-7.4
- Go: 1.12.7

> This environment can be reproduced by the [docker/Dockerfile](docker/Dockerfile)

### Reproduction

```bash
mkdir cpp/build && cd cpp/build
cmake ..
make 

cd - 
go run world.go
```

### Expect 

- Different address for `x` and `y`
- Different address for `a` and `b`

Something likes

```bash
x: 0x777280
y: 0x777284

a: 0xc00001a080
b: 0xc00001a084
```

### Got

- Same address for `x` and `y`
- Different address for `a` and `b`

```bash
x: 0x777280
y: 0x777280

a: 0xc00001a080
b: 0xc00001a084
```

`unsafe.Sizeof(x) == 0`，I think this is the root cause, so any workaround?

**Comment by ianlancetaylor** [comment]
The language spec says that two distinct zero-size variables may have the same address in memory (https://golang.org/ref/spec#Size_and_alignment_guarantees).

The only workaround is to not use zero-size variables.
