### ISSUE TITLE
strings.Split - remove empty elements

### ISSUE THREAD

**Issue by kotyara85** [golang/go#33393]
Would it make sense to add an option to remove empty elements during split?

Something like this would work
```
str := []string{"test1","","test3"}

RemoveEmpty(&str)

func RemoveEmpty(slice *[]string) {
	i := 0
	p := *slice
	for _, entry := range p {
		if entry != "" {
			p[i] = entry
			i++
		}
	}
	*slice = p[0:i]
}
```

**Comment by ianlancetaylor** [comment]
`strings.Split` works on a single string, not a slice of string.  More generally, `strings.Split` does what it does, and we aren't going to change it now.

If you are suggesting adding a new function to the standard library, see https://golang.org/doc/faq#x_in_std .

**Comment by kotyara85** [comment]
Yes, I know.
The idea is to either add a new func or extend Split to allow drop empty values after the string is split into splice.

**Comment by ianlancetaylor** [comment]
I see.  Still, we can't change `strings.Split` now.  That would break existing working programs.

**Comment by ianlancetaylor** [comment]
And as far as a new function goes, https://golang.org/doc/faq#x_in_std .  I don't see why the proposed function meets the bar.
