### ISSUE TITLE
cmd/go: conversion from legacy dependency managers puts replacement module path in require section

### ISSUE THREAD

**Issue by liuchang0812** [golang/go#33406]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/liuchang/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/liuchang/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build510154135=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

run `go mod init` with a dep project that contains source config.

### What did you expect to see?

go.mod should put module's old path in require section.

### What did you see instead?

go.mod put module's new path in require section.

**Comment by bcmills** [comment]
@liuchang0812, is this still an issue?

**Comment by bcmills** [comment]
Never mind, spotted an issue in `src/cmd/go/testdata/script/mod_init_dep.txt` that reproduces it.

**Comment by bcmills** [comment]
CC @jayconrod @oiooj

**Comment by liuchang0812** [comment]
@bcmills I added a test case in `src/cmd/go/internal/modconv/convert_test.go`, see https://github.com/golang/go/pull/33343

**Comment by bcmills** [comment]
@liuchang0812, I don't think we even need a new test case. We need to fix the existing `mod_init_dep` test case as described [in CL 126915](https://go-review.googlesource.com/c/go/+/126915/11#message-f8669d13a8c97659de52b4320d92448647693716).

**Comment by bcmills** [comment]
This is no longer needed due to #53327.
