### ISSUE TITLE
cmd/go: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"

### ISSUE THREAD

**Issue by dingrui37** [golang/go#33401]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
dingrui@ubuntu:~/projects/heterogeneous/client$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dingrui/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dingrui/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/dingrui/projects/heterogeneous/client/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build123236790=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I want to use docker SDK, I find the same issue, but I don't know what they talking about.

  ```
    "github.com/moby/moby/client"
    "github.com/moby/moby/api/types"
    "github.com/moby/moby/api/types/container"
    "github.com/moby/moby/pkg/stdcopy"
```
go.mod
```
module heterogeneous

go 1.12

require (
	github.com/acroca/go-symbols v0.1.1 // indirect
	github.com/docker/distribution v2.7.1+incompatible // indirect
	github.com/docker/docker v1.13.1 // indirect
	github.com/docker/go-connections v0.4.0 // indirect
	github.com/docker/go-units v0.4.0 // indirect
	github.com/golang/protobuf v1.3.2
	github.com/keegancsmith/rpc v1.1.0 // indirect
	github.com/mdempsky/gocode v0.0.0-20190203001940-7fb65232883f // indirect
	github.com/moby/moby v0.7.3-0.20190731150326-928381b2215c
	github.com/opencontainers/go-digest v1.0.0-rc1 // indirect
	github.com/pkg/errors v0.8.1 // indirect
	github.com/ramya-rao-a/go-outline v0.0.0-20181122025142-7182a932836a // indirect
	github.com/sirupsen/logrus v1.4.2 // indirect
	github.com/stamblerre/gocode v0.0.0-20190327203809-810592086997 // indirect
	golang.org/x/crypto v0.0.0-20190701094942-4def268fd1a4 // indirect
	golang.org/x/lint v0.0.0-20190409202823-959b441ac422 // indirect
	golang.org/x/net v0.0.0-20190724013045-ca1201d0de80 // indirect
	golang.org/x/sys v0.0.0-20190712062909-fae7ac547cb7 // indirect
	golang.org/x/text v0.3.2 // indirect
	golang.org/x/tools v0.0.0-20190723021737-8bb11ff117ca // indirect
	google.golang.org/grpc v1.22.0
)
```

### What did you expect to see?
How to solve this problem

**Comment by agnivade** [comment]
See https://github.com/golang/go/issues/28489. This is because Sirupsen and sirupsen are different. If you try with [tip](https://godoc.org/golang.org/dl/gotip), then you should get a better error message.

**Comment by katiehockman** [comment]
@agnivade is there any other action you think should be taken on this bug? Otherwise we can close this.

**Comment by agnivade** [comment]
I agree. I was just waiting to let OP have a chance to respond. Thanks for following up.
