### ISSUE TITLE
x/playground: use same new visual design as golang.org

### ISSUE THREAD

**Issue by lucacasonato** [golang/go#33414]
https://play.golang.org does not currently use the same updated visual design as https://golang.org.

I have a PR that updates the ui to match: https://go-review.googlesource.com/c/playground/+/188557

**Comment by agnivade** [comment]
@andybons

**Comment by andybons** [comment]
@lucacasonato Thanks for the PR. We have mocks from our designers that I’m happy to share with you if you’d like to take it on.

**Comment by lucacasonato** [comment]
That would be perfect. I would love to take this on.

**Comment by slrz** [comment]
Abandoning the playground's soothing yellow background is not really an option, right?

**Comment by lucacasonato** [comment]
Well... Times change 😋

**Comment by andybons** [comment]
@lucacasonato I will follow up with you Monday. I assume the email on your profile is the best one?

**Comment by lucacasonato** [comment]
Sounds good. Just send it to luca.casonato@antipy.com

**Comment by seankhliao** [comment]
I believe https://go.dev/play/ is now consistent with https://go.dev/
