### ISSUE TITLE
Enhancement: math.RoundOut

### ISSUE THREAD

**Issue by mcandre** [golang/go#33417]
Ceil and Floor don't quite do what most people expect them to, for negative numbers for example. It would be helpful to provide a convenience method `RoundOut`, which rounds all positive numbers up, and all negative numbers down.

This can be implemented in JavaScript as `math.Sign(x) * math.Ceil(math.Abs(x))`, but Go doesn't quite have the same Sign() behavior.

**Comment by AlexRouSg** [comment]
https://golang.org/pkg/math/#Round

**Comment by agnivade** [comment]
There are [Round](https://golang.org/pkg/math/#Round) and [RoundToEven](https://golang.org/pkg/math/#RoundToEven) which do exactly what you say unless I am missing something.

Please update your proposal clarifying what is missing in those functions that you require otherwise. Thanks.

**Comment by smasher164** [comment]
Would the following exhibit the behavior you want?
```Go
func RoundOut(x float64) float64 {
	return math.Copysign(math.Ceil(math.Abs(x)), x)
}
```
Note that your proposed behavior is "round away from zero", which is non-standard. I'm not exactly sure why one would want to round -1.3 down to -2.0. Can you please explain your use case?

**Comment by mpx** [comment]
Go implements the IEEE rounding modes (API: Ceil, Floor, Trunc, Round, RoundToEven - #21748). Other discussions in #20100, #4594.

I'm not sure there would be much demand for esoteric non-IEEE modes in the standard library.

**Comment by agnivade** [comment]
Sorry I missed that this is about rounding also 1.3 to 2 apart from 1.7 to 2. In any case, the question still stands to explain the use case for this and why does this [need](https://golang.org/doc/faq#x_in_std) to be in the standard library.
