### ISSUE TITLE
iOS: the Readdirnames(-1) func can only return 100 files at most

### ISSUE THREAD

**Issue by sunqiming** [golang/go#33426]
I compiled a iOS sdk with gomobile, but the Readdirnames(-1) func can only return 100 files at most.
It works for Windows and Mac OS.

**Comment by fyy000** [comment]
I have the same problem.I see dir_ios.go.
`
    30  func (f *File) readdirnames(n int) (names []string, err error) {
    31  	if f.dirinfo == nil {
    32  		dir, call, errno := f.pfd.OpenDir()
    33  		if errno != nil {
    34  			return nil, wrapSyscallError(call, errno)
    35  		}
    36  		f.dirinfo = &dirInfo{
    37  			dir: dir,
    38  		}
    39  	}
    40  	d := f.dirinfo
    41  
    42  	size := n
    43  	if size <= 0 {
    44  		size = 100
    45  		n = -1
    46  	}
`

but why?

**Comment by AlexRouSg** [comment]
Can you please try `1.13beta1`, the function was changed in https://github.com/golang/go/commit/9da6530faab0a58c4c4e02b2f3f4a5c754dcbd4e

**Comment by ianlancetaylor** [comment]
Please use the issue template so we can see what version you are using.  Thanks.

As far as I can see this has been fixed.
