### ISSUE TITLE
crypto: implement Hash.String

### ISSUE THREAD

**Issue by Ma124** [golang/go#33430]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ma_124/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ma_124/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build821474858=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I wanted to iterate all builtin hash functions by doing something like the following:

```go
var algs map[string]crypto.Hash

var h crypto.Hash
for ; h < crypto.maxHash; h++ {
    if h.Available() {
        algs[h.String()] = h
    }
}
```

### What did you expect to see?

An exported [`crypto.maxHash`](https://golang.org/src/crypto/crypto.go?s=1664:1671#L43) and [`crypto.Hash`](https://golang.org/src/crypto/crypto.go?s=364:378#L6) implementing the `fmt.Stringer` interface.

**Comment by andybons** [comment]
@FiloSottile

**Comment by andybons** [comment]
@Ma124 you mention what you _want_ to do, but don’t explain _why_ you or others would need this functionality. Could you elaborate a bit more on that in your proposal?

**Comment by Ma124** [comment]
The Stringer would be useful for all kinds of logging purposes and I personally see no drawback.

The maxHash would be useful every time you need to show something non-go the options there are for hashing. So for example every time a user can choose a hashing algorithm in a CLI or GUI or maybe you list available hashing options to a program written in another language. And your duplicating code every time when you use the alternative: importing the package and putting it into a map. So if for example one of the choices becomes insecure you need to remove the import and the map entry and if you forget one of them you've got either an unused import which cannot be detected by the compiler or you've got a panic.

So I think there are no reasons against Stringer and very few drawbacks of a renamed maxHash.

**Comment by FiloSottile** [comment]
I'm not against implementing crypto.Hash.String for logging and the like.

Since hash functions need to be imported anyway to be available, I don't see the advantage of maxHash, and it's leaking an internal detail. Also, I don't want to encourage "pick your own hash" designs. The set of available hashes in a design should be ideally of size 1, and anyway clearly specified, not "whatever Go supports".

**Comment by rsc** [comment]
Added to proposal minutes, seems headed for likely accept.

**Comment by rsc** [comment]
Based on the discussion above, this seems like a **likely accept**.

**Comment by rsc** [comment]
No change in consensus, so accepted.

**Comment by toothrot** [comment]
@katiehockman Hello! It looks like the documentation is missing for this new API: https://tip.golang.org/pkg/crypto/#Hash.String

**Comment by FiloSottile** [comment]
@toothrot Is it common to document trivial `String() string` methods?
