### ISSUE TITLE
doc: Effective Go typos

### ISSUE THREAD

**Issue by lesomnus** [golang/go#33432]
at https://golang.org/doc/effective_go.html#generality, the `Block` interface  described as:
```go
type Block interface {
    BlockSize() int
    Encrypt(src, dst []byte)
    Decrypt(src, dst []byte)
}
```
the types are correct, but the name of argument `src` and `dst` seems to be vice versa.
the [doc](https://golang.org/pkg/crypto/cipher/#Block) describes it as:

```go
type Block interface {
        // BlockSize returns the cipher's block size.
        BlockSize() int

        // Encrypt encrypts the first block in src into dst.
        // Dst and src must overlap entirely or not at all.
        Encrypt(dst, src []byte)

        // Decrypt decrypts the first block in src into dst.
        // Dst and src must overlap entirely or not at all.
        Decrypt(dst, src []byte)
}
```

**Comment by ALTree** [comment]
There's a proposal of freezing that document (#28782) but it seems to be stalled and anyway I think it would be fine to fix small errors like this one.
