### ISSUE TITLE
os, syscall: changes to os.Err* and syscall.Errno not mentioned in release notes and syscall package docs

### ISSUE THREAD

**Issue by bcmills** [golang/go#33436]
The changes made to the `os` and `syscall` package for #30322 are not mentioned in the Go 1.13 release notes, nor in the documentation for `syscall.Errno` or the `syscall` package.

Because users in general cannot redefine the error behavior of the errors defined by their dependencies, as a user I would not expect `syscall.Errno` errors to be defined as equivalent to errors defined in the higher-level `os` package. As noted in #32463 and #33411, the fact that they are has significant, non-trivial implications.

If `errors.Is` is now recommended and supported for checking the properties of `syscall.Errno` errors, the `syscall.Errno` documentation and the Go 1.13 release notes should be updated to mention that.

CC @neild @jba @mpvl @rsc @andybons @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Ping @jba Want to write something about this as you've written other error-related docs?
