### ISSUE TITLE
net/url: URL User field is not JSON marshaled

### ISSUE THREAD

**Issue by doppioandante** [golang/go#33431]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Didn't test

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lavoro/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lavoro/apps/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.12"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.12/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build187346097=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

Playground: https://play.golang.org/p/8u1idvEZNKp
```
package main

import (
	"encoding/json"
	"fmt"
	"net/url"
)

func main() {
	urlStr := "ssh://git:pw@gitlab.test:test/test.git"
	ur, _ := url.Parse(urlStr)
	s, _ := json.Marshal(ur)
	var ur2 *url.URL
	json.Unmarshal(s, &ur2)
	fmt.Println(ur)
	fmt.Println(ur2)

}
```

**Comment by agnivade** [comment]
It _is_ being encoded correctly. Just that User does not have its fields exported. So you are getting a "{}". You need to define your own marshal method, or just pass the string representation of the url directly. This is WAI.

**Comment by doppioandante** [comment]
I think I will go with the "use the whole URL" approach in my use case. What are the disadvantages of putting a default marshal method for the User field in the standard library?

**Comment by agnivade** [comment]
>  What are the disadvantages of putting a default marshal method for the User field in the standard library?

Any new API needs to have sufficient justification to be added. As of now, there seems to be a easy enough workaround to the issue. However, if you think such a method should be added, please feel free to file a [proposal](https://golang.org/s/proposal), and we can let the discussion happen over there. I will close this one since this issue is WAI.
