### ISSUE TITLE
testing: API should be general purpose

### ISSUE THREAD

**Issue by gopherbot** [golang/go#3343]
by **nickdsnyder**:

<pre>The testing package currently provides an API that is only useful to gotest, but it
would be nice if the API were made more general so that tests could be easily run from
any Go code.

Specifically, the test runners (RunTests, RunExamples, RunBenchmarks) just write output
to os.Stderr.

An easy improvement would be to add a io.Writer parameter to write output to.

Even better would be to define a test result structure and return a slice of test
results (one per test run).</pre>

**Comment by ysmolsky** [comment]
Those functions are still exported because of cross-package usage, but they are part of "go test" implementation. I do not think that we ever will add this functionality.
