### ISSUE TITLE
Remove from Hacking.md the minikube section and make platform-container

### ISSUE THREAD

**Issue by loukkl** [golang/go#33434]
minikube section  (?) no longer applies nor is ``make platform-container`` supported, remove them from Hacking.md

minor edit: removed an "is"

**Comment by ianlancetaylor** [comment]
What file are you talking about?  I don't see any file Hacking.md in the Go distribution.  Do you have a URL?

**Comment by loukkl** [comment]
> What file are you talking about? I don't see any file Hacking.md in the Go distribution. Do you have a URL?

this file : https://github.com/airmap/platform/blob/master/HACKING.md
