### ISSUE TITLE
pprof: How to profile goroutines?

### ISSUE THREAD

**Issue by You-NeverKnow** [golang/go#33444]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12.5
</pre>

### What operating system and processor architecture are you using (`go env`)?
<pre>linux/amd64</pre>

I have a Go program in which several goroutines are calling a database querying function concurrently. I want to log the memory and cpu usage every time that function is called. Currently `pprof` package only consists of `StartCPUProfile()` and `WriteHeapProfile()` functions, but I can't use them because they return per-process statistics. 

Is there a way to get the same functionality per-goroutine?

**Comment by ianlancetaylor** [comment]
One approach is to use the `WithLabels` (https://golang.org/pkg/runtime/pprof/#WithLabels) function to pass an appropriate label to each goroutine you want to profile.  Then look for the labels in the resulting profile.

In general you are likely to get better answers for this kind of question in a forum.  See https://golang.org/wiki/Questions.
