### ISSUE TITLE
Internal compiler error with complex operations

### ISSUE THREAD

**Issue by fgm** [golang/go#33458]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 nacl/amd64p3
</pre>

### Does this issue reproduce with the latest release?
This is the latest non-dev release

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
(none)
</pre></details>

### What did you do?

https://play.golang.org/p/hYUAK-ex6tQ

### What did you expect to see?

The compiler warning that these comparisons and that operation are forbidden for complex types instead of reporting an internal error.

### What did you see instead?

./prog.go:19:16: internal compiler error: compareOp: bad comparison: 1i < 1i

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new

And similar errors for the other cases in the example.

**Comment by ALTree** [comment]
Thanks for the report. This is a dup of #32723, which already has a patch, so I'm closing this thread in favour of the older one.

**Comment by fgm** [comment]
@ALTree Actually, there is one more error kind in this report, which is not mentioned in https://github.com/golang/go/issues/32723 : #32723 only mentions comparisons, but here we also have an error on an operation.

**Comment by ALTree** [comment]
@fgm the error on the bit operator is #31060 and it's already fixed on tip. 

P.S. In Go, `^` is not exponentiation, it's a bitwise XOR.
