### ISSUE TITLE
net/http: another typo in Response.Body field docs

### ISSUE THREAD

**Issue by sanjib** [golang/go#33453]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.12.7 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH=amd64
GOOS=windows
</pre></details>

### What did you do?

Read the documentation in file: ~/src/net/http/response.go
Found grammatical issue in field Body of struct Response, around line 68

### What did you expect to see?

// As of Go 1.12, the Body will also implement io.Writer

### What did you see instead?

// As of Go 1.12, the Body will be also implement io.Writer

**Comment by smasher164** [comment]
Good catch! Would you like to submit a change for this (https://golang.org/doc/contribute.html)? Also (let's see if this works), @gopherbot, add NeedsFix, help-wanted.

**Comment by sanjib** [comment]
Sure, would love to! Thanks.

**Comment by shivi28** [comment]
Hello @agnivade @sanjib I tried to solve this issue.

**Comment by odeke-em** [comment]
Thank you for filing this issue @sanjib and welcome to the Go project! Thank you for the triage @smasher164 too and for chiming in @shivi28!

 >Hello @agnivade @sanjib I tried to solve this issue.

I had just posted feedback on your CL @shivi28 and on coming here noticed that @sanjib had already committed to it. @sanjib sorry about that, but could you please perhaps let @shivi28 take this one as they already have the CL out, and in the future @shivi28 please take a look at who has responded in case they are already working on the fix :)

**Comment by sanjib** [comment]
@odeke-em hey no problem, thanks! :-)

**Comment by shivi28** [comment]
Sure @odeke-em I will keep this in mind and I am extremely apologized for this  @sanjib

**Comment by sanjib** [comment]
@shivi28  don't worry, this was a classic go race condition :-)
It was going to be my first contribution but I took too much time on the "contribute" document (basically trying to decide if I should use my @gmail or Google Suite account to sign the CLA and setting up gcc on Windows for the all.bat test to pass, though strictly wasn't necessary for a simple comment change) that I realized you beat me to it. 
After n-number of languages I am having a lot of fun with Go, so let's keep having fun!

**Comment by agnivade** [comment]
@sanjib - Don't worry, you are now done with your setup, and this issue tracker will keep having new issues. And I'm pretty sure if you go through old issues searching for "Documentation"/ "help wanted"/ "suggested" labels, you can find something that you feel comfortable contributing to. See [this](https://golang.org/doc/contribute.html#tmp_8) for more info.
