### ISSUE TITLE
go/packages: ignore cgo errors

### ISSUE THREAD

**Issue by bwmarrin** [golang/go#33462]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/bwmarrin/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/bwmarrin/.go"
GOPROXY=""
GORACE=""
GOROOT="/home/bwmarrin/.go/root"
GOTMPDIR=""
GOTOOLDIR="/home/bwmarrin/.go/root/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build824270571=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Opened a new temp package in my GOPATH src folder.  Tested auto completion and it worked fine.  Then I added an import for the http package.  Then I tested and auto completion no longer worked for items within my temp package.

After hunting down some other issues, I found the below command.
```
go list -e -json -compiled
```

Running that without the http package returned details without an error.  Running it with the http package returned an error, along with the details I expected.

```
exec: "gcc": executable file not found in $PATH
```

Which, I assume is to say gcc is required for this to work right. So I installed gcc, and now everything works as expected.

I'm not sure if this is a bug, or working as intended.  It took me several hours to figure out why my auto completion wasn't working and thought I'd share it here in case it wasn't intended behaviour and so maybe others might be helped, possibly. 

### What did you expect to see?
I expected go auto completion to "just work" even after adding the http package without needing to install a compiler I didn't think I needed.

### What did you see instead?
Auto completion failed to work for things within the test package after adding http import.

**Comment by stamblerre** [comment]
To confirm, this was when you were importing the `net/http` package in the standard library?

**Comment by bwmarrin** [comment]
Correct.

**Comment by stamblerre** [comment]
/cc @jayconrod for more clarity on why `go list` would behave this way. This sound similar to a few other issues users have encountered with `gopls`, specifically https://github.com/golang/go/issues/33107#issuecomment-514054656 and https://github.com/golang/go/issues/33018#issuecomment-518069495.

@bwmarrin: And this code compiles without any problems?

**Comment by jayconrod** [comment]
`net/http` depends on packages that have cgo code. It looks like these are `runtime/cgo`, `net`, and `crypto/x509`.

If the `-compiled` flag is passed to `go list`, listed packages and their dependencies are compiled, and the paths to the compiled .a files are included in the output. If cgo is enabled, a C compiler is required to build those packages. I'm guessing `gopls` uses the compiled .a files for type information, but even if it didn't, cgo may be required for type checking.

@bwmarrin Have you tried disabling cgo by setting `CGO_ENABLED=0` in your environment? I don't believe cgo is disabled automatically depending on whether there is a C compiler in `PATH`.

**Comment by bwmarrin** [comment]
@stamblerre - yes, the test code compiled fine.  I could create a repo with an example, if that helped.

@jayconrod - No, I didn't try disabling cgo.  Once I found the error I just went ahead and installed gcc.  I just hadn't needed it on this dev machine yet so never installed it but it wasn't a big deal to add it if that's what it took to get things working so I could get back to work ;)

**Comment by stamblerre** [comment]
> I don't believe cgo is disabled automatically depending on whether there is a C compiler in `PATH`.

@jayconrod: Is this something we could possibly do in the `go` command, or would go/packages have to handle this error?

**Comment by stamblerre** [comment]
I think this is fairly fixable in go/packages. Sent @matloob a test case so that this issue can be resolved there.

**Comment by hyangah** [comment]
golang.org/x/mobile/cmd/gobind experienced the same issue and works around by disabling cgo explicitly with CGO_ENABLED=0. 

https://go-review.googlesource.com/c/mobile/+/189597/2/cmd/gobind/main.go#62
cc @hajimehoshi 

I am curious what's the consequence of disabling cgo - will it exclude the files that have 'import "C"' or 'cgo' build constraints in the code analysis completely?

**Comment by jayconrod** [comment]
> will it exclude the files that have 'import "C"' or 'cgo' build constraints in the code analysis completely?

Yes, exactly. Packages that only have cgo sources may not build at all.

**Comment by bwmarrin** [comment]
Thanks for all the work, everyone :)
