### ISSUE TITLE
goproxy: The private repository failed to fetch using the go proxy

### ISSUE THREAD

**Issue by wzshiming** [golang/go#33469]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Fetch private repositories in the presence of a $GOPROXY

### What did you expect to see?

Private repository does not use $GOPROXY

### What did you see instead?

Because goproxy does not have private warehouse permissions, it cannot fetch

**Comment by bcmills** [comment]
Please read https://tip.golang.org/cmd/go/#hdr-Module_downloading_and_verification, then fill out the complete issue template. (You can go to https://golang.org/issue/new to get a fresh copy of the complete template, but please copy it into this issue instead of creating a new one.)

**Comment by bcmills** [comment]
The `GOPRIVATE`, `GONOPROXY`, and `GONOSUMDB` variables are being added in Go 1.13. If they are not working for you with `go1.13beta1`, please provide more detailed steps to reproduce the problem.

Specifically:
* Fill out the `go env` Output section.
* In the “What did you do?” section, copy and paste the actual `go` commands that you ran and their output. (Redact or rewrite any parts that you don't want to publicize, but bear in mind that we can't in general fix a problem that we can't reproduce.)

**Comment by wzshiming** [comment]
i see. thank you.
