### ISSUE TITLE
x/tools/gopls: can't install @latest

### ISSUE THREAD

**Issue by ilovelili** [golang/go#33464]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.12.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/min/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/min/Projects/dongfeng"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/min/Projects/dongfeng/src/github.com/ilovelili/dongfeng-core/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build261873378=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```bash
go get golang.org/x/tools/gopls@latest
```

### What did you expect to see?

Get gopls installed

### What did you see instead?

<pre>
golang.org/x/tools/gopls
../../../../pkg/mod/golang.org/x/tools/gopls@v0.1.3/main.go:20:41: not enough arguments in call to cmd.New
	have (string, nil)
	want (string, string, []string)
</pre>

**Comment by stamblerre** [comment]
Sounds like you have a more recent version of x/tools installed than `@latest` expects. Can you try deleting the old dependencies by running `go mod tidy` and then try running `go get golang.org/x/tools/gopls@latest` again?

**Comment by 0ostreamo0** [comment]
> Sounds like you have a more recent version of x/tools installed than `@latest` expects. Can you try deleting the old dependencies by running `go mod tidy` and then try running `go get golang.org/x/tools/gopls@latest` again?

have the same question, and run go mod tidy not working
![image](https://user-images.githubusercontent.com/7197034/62510190-ad836d00-b840-11e9-96e8-1da69176ea08.png)

**Comment by stamblerre** [comment]
@0ostreamo0: `-u` updates all of your dependencies to master, so it would not work with `@latest`. It would update the `x/tools` dependency to a version that is past the version expected by `gopls@latest`. `go get golang.org/x/tools/gopls@latest` is the correct way to run the command, as specified on the wiki page: https://github.com/golang/go/wiki/gopls.

**Comment by ilovelili** [comment]
@stamblerre Thanks Rebecca that worked for me. I will close the issue.
