### ISSUE TITLE
x/tools/gopls: spurious "is not an identifier" error

### ISSUE THREAD

**Issue by ainar-g** [golang/go#33467]
* `gopls` built from `1d1727260058c6d58ebfdeb982c4657342282355`
* `go` version `go1.11.12`
* `vim` version `8.0` from the Ubuntu 18.04 repo
* [`vim-lsc`](https://github.com/natebosch/vim-lsc) version `ad9d2bd0582419e902bc402545da397634202ed0`

When browsing through code, I constantly get:

```
[lsc:Error] no highlight: /home/me/go/src/example.com/foo.go:254:2 is not an identifier
Span = /home/me/go/src/example.com/foo.go:254:2
```

I get this whenever the cursor is not on an identifier. This error also makes the cursor invisible, which is annoying.

I am still not sure, if it's a problem with `vim-lsc` or `gopls`. I am ready to provide more information to help diagnose the issue.

**Comment by stamblerre** [comment]
These error messages are removed in `gopls` at master, if you would like to update. However, master will likely not be as stable as the latest tagged version.

This error is a result of your editor showing the errors from the hover request to the user, so it might be worth filing that issue. Some editors, like VSCode, choose not show the errors from every request to the user.

**Comment by ainar-g** [comment]
@stamblerre I've included the commit hash in my original post. I _am_ on master. I've just updated to `2756c524cc1ca1284d912b9c5ee3b0092ff4459b`, which was committed recently, and the problem is still there.

Not sure “just ignore it” is a good strategy, but I will open an issue, if it wasn't already.

**Comment by ainar-g** [comment]
@stamblerre FWIW, I've replaced

```
return nil, fmt.Errorf("%s is not an identifier", fset.Position(pos))
```

with

```
return nil, nil
```

in `internal/lsp/source/highlight.go`, and it started working again.

**Comment by stamblerre** [comment]
Oh I'm sorry, I misunderstood - I had assumed that the error was with hover, not with document highlight.

In that case, this is definitely an error on the client side. We never return errors from document highlight (see [here](https://github.com/golang/tools/blob/2756c524cc1ca1284d912b9c5ee3b0092ff4459b/internal/lsp/highlight.go#L34)), they are only ever logged. The client should not show the user logged errors--the LSP specification has a specific [`window/showMessage`](https://microsoft.github.io/language-server-protocol/specification#window_showMessage) request that is distinct from [`window/logMessage`](https://microsoft.github.io/language-server-protocol/specification#window_logMessage). I would suggest filing this issue on the `vim-lsc` repo.

**Comment by ainar-g** [comment]
You are very correct! Disabling logging with

```vim
let g:lsc_server_commands = {"go": {"command": "gopls serve", "log_level": -1}}
```

fixes the issue! Should I add info about this vim LSC implementation to the Wiki to prevent duplicates?

**Comment by stamblerre** [comment]
I think it might be best to file an issue with `vim-lsc` so that they can correct the problem, but as a temporary fix, adding a suggestion to the Wiki would also be helpful. Thanks!

**Comment by ainar-g** [comment]
Done. Thank you thrice: for helping me today, for your GopherCon Russia talk, and for `gopls` in general!

**Comment by stamblerre** [comment]
:smile: And thank you for reporting this issue!
