### ISSUE TITLE
cmd/compile: internal compiler error on complex modulo instead of compilation failure

### ISSUE THREAD

**Issue by jadr2ddude** [golang/go#33461]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes I think.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jadenw/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jadenw/GOPATH"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build531868898=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I forgot whether the spec allows modulo on complex numbers (and I now know it does not), so I tried it on the playground.

https://play.golang.org/p/erbCFy39DAy

### What did you expect to see?
The correct behavior would be to spit out an error something like `% operator not defined for complex numbers`.

### What did you see instead?
```
./prog.go:8:16: internal compiler error: binaryOp: bad operation: 1i % 1

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new

Go build failed.
```

### Notes
This only appears to happen for inline constant expressions. When [breaking it up with variables](https://play.golang.org/p/inpWzGNYDAT), it spits out a proper error.

**Comment by odeke-em** [comment]
Thank you for this report @jadr2ddude!

We shall get this fixed for Go1.14.

**Comment by cuonglm** [comment]
This is duplicated of https://github.com/golang/go/issues/32723, and should be fixed in https://go-review.googlesource.com/c/go/+/183459

**Comment by jadr2ddude** [comment]
Oops! I looked around for a previous report, but nothing had showed up when I originally looked. Thanks, closing as a duplicate.
