### ISSUE TITLE
go.mod replace statements within dependancies are ignored.

### ISSUE THREAD

**Issue by kellengreen** [golang/go#33478]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kgreen/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/kgreen/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.7/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/kgreen/src/dunkirk/cmd/a/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s6/yd4cf7p559v66xs941ncw55c0000gn/T/go-build426619971=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
<pre>
cd a/
go run main.go
</pre>

### What did you expect to see?
<pre>
A
B
C
</pre>

### What did you see instead?
<pre>
go: finding github.com/kellengreen/test/c v0.0.0
go: github.com/kellengreen/test/c@v0.0.0: unknown revision c/v0.0.0
go: error loading module requirements
</pre>

### Steps to reproduce

This could very well be as designed. However I couldn't find specifics within the [modules](https://github.com/golang/go/wiki/Modules) page. To summarize it seems that `replace` statements within `go.mod` files of dependancies are ignored during the build process. Say we have a project like below: where `a` depends on `b` which depends on `c`. Without a specific replace statement for `c` in `a/go.mod`, the build will fail.

`/a/go.mod`
```go.mod
module github.com/kellengreen/test/a

go 1.12

replace github.com/kellengreen/test/b v0.0.0 => ../b

// UNCOMMENTING THE LINE BELOW RESOLVES THE ISSUE
// replace github.com/kellengreen/test/c v0.0.0 => ../c

require github.com/kellengreen/test/b v0.0.0
```
`/a/main.go`
```go
package main

import (
	"fmt"

	"github.com/kellengreen/test/b"
)

var Name = "A"

func main() {
	fmt.Println(Name)
	fmt.Println(b.Name)
	fmt.Println(b.Friend)
}
```
`/b/go.mod`
```go.mod
module github.com/kellengreen/test/b

go 1.12

// SHOULD THIS LINE BE IGNORED WHEN BUILDING A?
replace github.com/kellengreen/test/c v0.0.0 => ../c

require github.com/kellengreen/test/c v0.0.0
```
`/b/b.go`
```go
package b

import (
	"github.com/kellengreen/test/c"
)

var Name = "B"
var Friend = c.Name
```
`/c/go.mod`
```go.mod
module github.com/kellengreen/test/c

go 1.12
```
`/c/c.go`
```go
package c

var Name = "C"
```

**Comment by ianlancetaylor** [comment]
This is documented at https://tip.golang.org/cmd/go/#hdr-Defining_a_module.

**Comment by kellengreen** [comment]
Thank you, here is the quote in question should anyone else come across this:

> The go.mod file can also specify replacements and excluded versions that only apply when building the module directly; they are ignored when the module is incorporated into a larger build.

**Comment by alltom** [comment]
The full quote is:

> The go.mod file can also specify replacements and excluded versions that only apply when building the module directly; they are ignored when the module is incorporated into a larger build. For more about the go.mod file, see 'go help go.mod'.

Running `go help go.mod` returns a bit that says:

> Exclude and replace apply only in the main module's go.mod and are ignored
in dependencies.  See https://research.swtch.com/vgo-mvs for details.

And I think that the relevant bit from that page is:

> Minimum requirements combine without conflict, so it is feasible (even easy) to gather them from all dependencies. But exclusions and replacements can and do conflict, so we allow them to be specified only by the top-level module.
