### ISSUE TITLE
blog: home page should only show previews instead of full posts

### ISSUE THREAD

**Issue by khalidfad** [golang/go#33476]
The read more on the homepage of the goLang website leads to a tunnel which has bad User Experience
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by smasher164** [comment]
Can you be a bit more specific about exactly is the bad user experience you are having?

**Comment by khalidfad** [comment]
WaitingForInfo check out this url https://blog.golang.org/

**Comment by mattn** [comment]
Do you mean that the list page of each entry on Go Blog should omitted the content, and add a "read more" link to go to the permalink?

**Comment by ALTree** [comment]
The fact that the https://blog.golang.org homepage is a huge page where the latest n blog entries are included in full without being clear where one ends and the following one begins is also something that has always bugged me. I'm guessing this is what the OP is reporting.

**Comment by ALTree** [comment]
Two different suggestions for a possible solution:

- List the first few paragraphs of the latest 5 entries, after each one a "read more" button with links to the full entry. Change the spacing/style of the page to clearly demarcate the starting of a new homepage item
- List on the homepage the latest blog entry in full, leave the read-more link at the bottom for the index with all the entries

**Comment by khalidfad** [comment]
Another possible solution:

There should be pagination and sidebar with categories

**Comment by khalidfad** [comment]
> Do you mean that the list page of each entry on Go Blog should omit the content, and add a "read more" link to go to the permalink?

The  https://blog.golang.org/ is unnecessarily long and can bore the users.

Pagination can be applied

**Comment by agnivade** [comment]
@andybons

**Comment by andybons** [comment]
Let’s start with only showing previews (with a “read more”) instead of full posts.

**Comment by khalidfad** [comment]
help wanted  I am a UI/UX Developer i can help revamping the blog page #helpwanted  #NeedsFix #NeedsDecision @agnivade

**Comment by agnivade** [comment]
Feel free to go ahead. And just a small note that mentioning hashtags does not have any effect here.

**Comment by apparluk** [comment]
my preference is to leave it alone

but can't certain gophers use a feed reader

_e.g_., [Atom](https://blog.golang.org/feed.atom) | Copyright | Terms of Service | Privacy Policy | Report issue

appearing in the blog footer

categories complicate feeds

**Comment by seankhliao** [comment]
it only shows a title and subtitle now.
