### ISSUE TITLE
cmd/go: go build in modules module does not build dependencies

### ISSUE THREAD

**Issue by MartinKosicky** [golang/go#33496]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.12.7 windows/amd6

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\martin\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Development\Go\Test123\vendor
set GOPROXY=
set GORACE=
set GOROOT=D:\Golang
set GOTMPDIR=
set GOTOOLDIR=D:\Golang\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Development\Go\Test123\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\martin\AppData\Local\Temp\go-build709166158=/tmp/go-build -gno-record-gcc-switches

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Well this is not really a bug. I am using go modules.  I think it would be very helpful if go build (when running in go modules mode) does also build the dependencies. For instance I want to use a protoc-gen-go library which is tightly coupled with the current protobuf library. I have a go.mod that specified "github.com/golang/protobuf v1.3.2" but that only downloads the runtime libraries. The compiler is stripped from the download as (I guess it's not referenced anywhere). I don't really need this kind of tidying. I know I can make a custom script that does 
 go get -u github.com/golang/protobuf/protoc-gen-go@v1.xxx

but that is redundant since I already specified version in go.mod.
Are there any plans for this thing???

**Comment by bcmills** [comment]
`go build` _does_ build dependencies.

Since you mention `protoc-gen-go`, see https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module. Does that address your use-case here?

**Comment by bcmills** [comment]
See also #27653.

**Comment by MartinKosicky** [comment]
Well I looked at the docs. It's still annoying that I have to actually write 
`go install github.com/golang/protobuf/protoc-gen-go`
however now the version can be omited so I don't have to track the versioning at 2 different places (go.mod and some build script). However I think this will suffice

**Comment by MartinKosicky** [comment]
Ur right this totally fixes my issues. Thank you!

**Comment by agnivade** [comment]
Thanks @MartinKosicky, I will close this then.
