### ISSUE TITLE
x/tools/gopls: log error frames when logging an error

### ISSUE THREAD

**Issue by stamblerre** [golang/go#33499]
Now that we are using x/errors in `gopls`, we can also log error frames when logging errors.
@jan-xyz is interested in adding this behavior.

**Comment by jan-xyz** [comment]
According to the blog post https://blog.golang.org/experiment the design draft for printing frames is abandoned and they are on a look out for a better solution. I am not sure if the current implementation will stay. Do you have any more insights on this @stamblerre ?

**Comment by stamblerre** [comment]
Ah, I missed Russ's talk at GopherCon. I think I'm fine with using the features supported by `x/errors` as long as they are around, just to try them out.

I think we could make these changes quite simple and easy to revert because @ianthehat's telemetry work introduced a new way of logging errors. Supporting this behavior might be as simple as adding the `%+v` in a single place. Take a look at https://godoc.org/golang.org/x/tools/internal/lsp/telemetry/log and let me know what you think.

**Comment by jan-xyz** [comment]
Just printing errors as `%+v` probably doesn't hurt in general. I suppose it's enough to change the format here:
https://github.com/golang/tools/blob/128824a23e7c038a341252700f1001ad29ef1988/internal/lsp/telemetry/log/entry.go#L46

**Comment by stamblerre** [comment]
Something like messing with the name of the package, adding an import that doesn't exist, completing something that's not declared - these would all likely cause errors to be logged.
