### ISSUE TITLE
access: Trybot Access

### ISSUE THREAD

**Issue by sylvinus** [golang/go#33493]
Hello!

Some of you know me as the organizer of dotGo :) 

I've had a [couple CLs](https://go-review.googlesource.com/q/owner:sylvinus%2540gmail.com) merged in the `regexp` package and plan to be increasingly active there, hopefully. Daniel Marti recommended I ask for Trybot Access. I understand the semi-hardened nature of it and will skim for malicious code (though I'll probably stick to the `regexp` package for now).

My Gerrit email is "sylvinus@gmail.com"

Thanks!

**Comment by ianlancetaylor** [comment]
Done.  Enjoy.

**Comment by sylvinus** [comment]
Thanks!
