### ISSUE TITLE
cmd/gofmt: align function parameter types on subsequent lines

### ISSUE THREAD

**Issue by D1CED** [golang/go#33507]
Signatures of functions taking a lot of parameters are quickly exceeding a readable line length (80-120 characters).

    func httpHandlerFunc(logger *log.Logger, db *sql.DB, imgCache map[string]io.Reader, w http.ResponseWriter, r *http.Request)

To make this more readable one can put each parameter on an individual line like so:

    func httpHandlerFunc(
    	logger *log.Logger,
    	db *sql.DB,
    	imgCache map[string]io.Reader,
    	w http.ResponseWriter,
    	r *http.Request,
    )

In contrast to most other forms e.g. imports, structs, variable and constant declarations gofmt does not align this form. I propose that this form should be recognised by gofmt and parameter names and parameter types be appropriately aligned.

    func httpHandlerFunc(
    	logger   *log.Logger,
    	db       *sql.DB,
    	imgCache map[string]io.Reader,
    	w        http.ResponseWriter,
    	r        *http.Request,
    )

The objective of this proposal is to increase readability and make formatting rules more consistent.

**Comment by jgoc** [comment]
Also for type parameters and multiple returns
```go
func httpHandlerFunc(
	T constraints.Comparable,
	U constraints.Ordered,
) (
	logger   *log.Logger,
	db       *sql.DB,
	imgCache map[string]io.Reader,
	w        http.ResponseWriter,
	r        *http.Request,
) (
	f   func(w http.ResponseWriter, r *http.Request) (error),
	err error,
)
```

**Comment by andybons** [comment]
Sorry, but gofmt is pretty much frozen at this point. Thanks for the issue.
