### ISSUE TITLE
Golang generates go.mod file automatically

### ISSUE THREAD

**Issue by mrdulin** [golang/go#33509]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ldu020/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ldu020/workspace/go:/Users/ldu020/workspace/github.com/mrdulin/golang"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/ldu020/workspace/github.com/mrdulin/golang/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/38/s8g_rsm13yxd26nwyqzdp2shd351xb/T/go-build159636335=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I am using vscode and go extension. Recently, I found each project of my workspace has a `go.mod` file in the project root path.

### What did you expect to see?

DON'T generate `go.mod` file in my project of the workspace even it's not related to Golang.

### What did you see instead?

```bash
├── dl-toolkits
│   ├── LICENSE
│   ├── README.md
│   ├── dist
│   ├── go.mod
│   ├── jest.config.js
│   ├── node_modules
│   ├── package-lock.json
│   ├── package.json
│   ├── src
│   ├── tsconfig.json
│   └── tslint.json
├── docker-research
│   ├── LICENSE
│   ├── README.md
│   ├── examples
│   ├── go.mod
│   ├── node_modules
│   ├── package-lock.json
│   ├── package.json
│   └── test.txt.gz
├── dotfiles
│   ├── LICENSE
│   ├── README.md
│   ├── go.mod
│   ├── iTerm2
│   ├── vim
│   └── zsh
```

As you can see, there is `go.mod` file in each project of my workspace, even these projects are not related to Golang

**Comment by AlexRouSg** [comment]
Please report this to the vscode extension project. https://github.com/microsoft/vscode-go/issues

**Comment by mrdulin** [comment]
@AlexRouSg Thanks. Because I am not sure golang or vscode-go cause this issue. So I report this issue here. 

Are you sure this is a vscode-go issue? If so, can you help move this issue to vscode extension project?

**Comment by AlexRouSg** [comment]
> Are you sure this is a vscode-go issue?
Unless you can reproduce this without vscode-go, yes. In the future if you observe bugs or weird behaviours, report it to the software you are directly using first if you are not sure.

> If so, can you help move this issue to vscode extension project?
You have to manually do it sorry

**Comment by agnivade** [comment]
Please let us know if you are able to reproduce this issue just by manually using the Go toolchain. And if so, outline the exact steps that show the problem. Thanks.

**Comment by liudonghua123** [comment]
I have this problem too.

**Comment by liudonghua123** [comment]
https://github.com/microsoft/vscode-go/issues/2692 is also closed 😢

**Comment by stamblerre** [comment]
@liudonghua123: Which version of VS Code Go are you using? Please make sure you are using the latest version. If you are seeing this issue with 0.14.1, please report it to the microsoft/vscode-go repository.
