### ISSUE TITLE
misc/cgo: testcarchive, testcshared are skipped on ppc64, ppc64le with no obvious way to run them

### ISSUE THREAD

**Issue by laboger** [golang/go#33501]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +0ed86cda67 Tue Aug 6 19:12:41 2019 +0000 linux/ppc64le
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
ppc64le
</pre></details>

### What did you do?

Just trying to run all the tests with all.bash

### What did you expect to see?
testcarchive, testcshared run normally

### What did you see instead?
go tool dist test testcarchive

##### ../misc/cgo/testcarchive
SKIP - short mode and $GO_BUILDER_NAME not set

ALL TESTS PASSED (some were excluded)
go tool dist test testcshared

##### ../misc/cgo/testcshared
SKIP - short mode and $GO_BUILDER_NAME not set

ALL TESTS PASSED (some were excluded)

I'm not sure what this means and couldn't find it documented. This doesn't happen in go 1.12.
I'm assuming a recent change was made to skip some tests based on whether GO_BUILDER_NAME was set or not, but I don't see any CLs that mention skipping them on ppc64?

If the goal is to reduce test time when doing all.bash, that is fine but there should be some way to run these tests to ensure they don't break.

**Comment by ianlancetaylor** [comment]
The testcarchive and testcshared tests are now skipped by default on all.bash on all platforms.  https://golang.org/cl/177417.

The tests are still run on the builders, which set `GO_BUILDER_NAME`.

You can run the tests yourself by changing to the directory and running `go test`.  Or by setting `GO_BUILDER_NAME` in the environment when you run all.bash.
