### ISSUE TITLE
x/tools/gopls: improve textDocument/documentLink

### ISSUE THREAD

**Issue by stamblerre** [golang/go#33505]
Some additional features we should add support for in `textDocument/documentLink`:

- ~~Links missing `http://` or `https://` should be treated as links. For example, `golang.org/issue/12345`.~~ (Completed via [golang.org/cl/194661](https://go-review.googlesource.com/c/tools/+/194661)).
- ~~Links to the Go issue tracker should be treated as links. For example, `golang/go#12345`~~.

Please add any others as ideas come up.

**Comment by vacheli** [comment]
Also, there is no code completion, hint, or suggestion.

**Comment by eduvim** [comment]
I'm working on it

**Comment by stamblerre** [comment]
Re-opening because not all of these features have been implemented.

**Comment by eduvim** [comment]
what we can do is to check at links file if the link is http | https or nothing followed by golang/go#number . I can help with it. I just need to understand it in order to don't make a lot of pr's xD

**Comment by stamblerre** [comment]
@eduvim: If you'd like to continue work on this, I think we could add a second regex to match on `golang/go#1234`. Please feel free to add any other ideas as they come up.

**Comment by zikaeroh** [comment]
Is there any chance that the hueristic can be disabled without also disabling import links? I'm finding the current changes pretty distracting when it thinks things are links which actually aren't, e.g.:

![image](https://user-images.githubusercontent.com/48577114/70182650-1832a100-1699-11ea-93a7-82c019aa02e0.png)

I'd personally prefer this feature to not just accept anything that's `foo.bar` and start treating it as links in strings/comments.

And, if you hadn't seen it, there's already some great work in this area by @mvdan I use in another project: https://github.com/mvdan/xurls

**Comment by stamblerre** [comment]
Thank you for the suggestion @zikaeroh! I would be in favor of us using this library to do a better job of detecting links. What do you think, @ianthehat?

**Comment by eduvim** [comment]
Would you need any help ?

**Comment by stamblerre** [comment]
Thank you @eduvim -- I'm sorry I didn't reply earlier, but I actually did a small refactoring of the code for `textDocument/documentLink` which resolved this issue. I think I will close this, but if you are still interested in contributing, please check out the available issues [here](https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Agopls+label%3A%22help+wanted%22+).
