### ISSUE TITLE
cmd/cgo: env CGO_LDFLAGS not working but config #cgo LDFLAGS works

### ISSUE THREAD

**Issue by apptut** [golang/go#33520]
Hi, When build go code with some c .so file code in go 1.11+ modules, I config the directives in cgo file like this:
```go
// #cgo LDFLAGS: -L/abc/dir -lfoo
```
That's build successfull, but when I remove this line and then config env var `CGO_LDFLAGS` when build, it not working:
```sh
CGO_LDFLAGS="-L/abd/dir -lfoo" go build main.go
# or
export CGO_LDFLAGS="-L/abd/dir -lfoo" go build main.go
go build main.go
```
both above are failed find the c so inner func method, why. Anybody can help me?

**Comment by ianlancetaylor** [comment]
Please show us your Go environment as requested by the issue template.

Please show us exactly what happens in the case that fails.

Are you running `go build main.go` in both cases?
