### ISSUE TITLE
CGO_LDFLAGS_ALLOW as go cmd build flag

### ISSUE THREAD

**Issue by suizman** [golang/go#33521]
It's really painful to use environment variable to pass allowed **CGO** flags. 
It would be great to be able to pass this stuff as an build flag.

Eg:
go build -cgo-ldflags-allow '.*'

**Comment by ianlancetaylor** [comment]
Use a shell script or use `go env -w`.  I don't think we need two ways to do this.

**Comment by suizman** [comment]
OK @ianlancetaylor, i'll give it a try, but it seams that **go env -w** is on 0.13.0 beta.

**Comment by andybons** [comment]
@suizman thanks for the issue. Yes you're correct about `go env -w` being introduced in 1.13. Sorry for the inconvenience.

**Comment by suizman** [comment]
Thanks @andybons
