### ISSUE TITLE
encoding/gob: handle errors

### ISSUE THREAD

**Issue by alberts** [golang/go#3353]
<pre>What steps will reproduce the problem?

gob.Register(errors.New(&quot;&quot;)) returns gob: type errors.errorString has no
exported fields

Please provide any additional information below.

<a href="https://groups.google.com/forum/?fromgroups#">https://groups.google.com/forum/?fromgroups#</a>!topic/golang-dev/Cua1Av1J8Nc</pre>

**Comment by agnivade** [comment]
Duplicate of https://github.com/golang/go/issues/23340.
