### ISSUE TITLE
x/tools/gopls: autogenerate documentation for supported configurations

### ISSUE THREAD

**Issue by stamblerre** [golang/go#33544]
`gopls` has a number of configurations, some of which are meant for users to set manually. The rest are used primarily to "hide" experimental features and are only meant for use by `gopls` developers and testers.

We should formalize the set of `gopls` configurations that we want to make public for users, and we should consolidate these configurations with the settings of `gopls`'s clients, such as VSCode-Go, vim-go, govim, etc.

Current settings include:

```json5
"gopls": {
    // user-facing
    "env": {}, // the environment to use when loading packages
    "buildFlags": [], // the build flags to use when loading packages
    "usePlaceholders": true, // if the user wants placeholders when they complete an item
    "hoverKind": "FullDocumentation", // the amount of documentation to show on hover, one of NoDocumentation, Synopsis, SingleLine, FullDocumentation
    
    // experimental configurations
    "wantCompletionDocumentation": true, // if the user wants to see documentation in completion items
    "wantSuggestedFixes": true, // offer fixes to apply along with diagnostics
    "experimentalDisabledAnalyses": [], // list of analyses to disable in diagnostics
    "useDeepCompletions": true, // show completions for symbols in imported packages
}
```

We should add the settings used by clients to this issue to get a better understanding of how we can provide a more unified experience.

We should autogenerate this documentation from the comments in the internal/lsp/source/options.go.

**Comment by ermik** [comment]
Just checking if any of these can help with choosing the inferred package root as that would be a workaround for a subset of #32394 where project directory is a step above package root folder (one that has `go.mod` in it).

**Comment by stamblerre** [comment]
@ermik: That is something that will have to be implemented through VS Code Go, so I would recommend filing that issue in that repository.

**Comment by stamblerre** [comment]
We should also auto-generate documentation for the commands and code lenses available in `gopls`.
This command documentation could also be used to generate package.json contents for commands, making it possible to easily expose commands from `gopls` in VS Code without a code lens.

**Comment by heschik** [comment]
I guess this is not actually fixed given the above.

**Comment by heschik** [comment]
I'm still unclear on what extra documentation we want. I believe the result of discussion was that we don't want to automatically connect commands to the extension. @stamblerre, you said that we should document code lenses, but I don't understand where or why. Just so that users can disable them in the `codelens` setting?

**Comment by heschik** [comment]
Also, should we enable documentation of the debugging options?

**Comment by stamblerre** [comment]
> I'm still unclear on what extra documentation we want. I believe the result of discussion was that we don't want to automatically connect commands to the extension. @stamblerre, you said that we should document code lenses, but I don't understand where or why. Just so that users can disable them in the `codelens` setting?

I had thought that https://github.com/golang/tools/blob/master/internal/lsp/source/command.go was structured in such a way that we could easily generate documentation from it. I think it would be nice to have a page describing our code lenses to make them more discoverable and so that users can understand how to enable/disable them.

Since we've agreed not to expose commands through the VS Code Go command palette, I think this issue is resolved in that there are no more blockers for VS Code Go. I will mention the above in a general issue about documentation.

> Also, should we enable documentation of the debugging options?

Yeah, that sounds good.

**Comment by heschik** [comment]
command.go would indeed be easy to generate documentation from. I think you're saying you want it? So I'll add them to the json and write a documentation page, separate from the settings page since there are no settings that refer to commands.

**Comment by stamblerre** [comment]
That would be awesome--thanks! I mentioned it on https://github.com/golang/go/issues/41591 in case you wanted to close this issue.
