### ISSUE TITLE
x/tools/gopls: no packages found for file

### ISSUE THREAD

**Issue by vacheli** [golang/go#33549]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?

![image](https://user-images.githubusercontent.com/5040231/62725558-f5c0ac00-ba47-11e9-8d71-4c8b1a274b10.png)

![image](https://user-images.githubusercontent.com/5040231/62725603-0bce6c80-ba48-11e9-8396-67d2f96f5ec3.png)

**Comment by vacheli** [comment]
Also, there is no code completion, hint, or suggestion.

**Comment by stamblerre** [comment]
What is the output of `gopls -rpc.trace -v check path/to/file.go`?

**Comment by vacheli** [comment]
> What is the output of `gopls -rpc.trace -v check path/to/file.go`?

![image](https://user-images.githubusercontent.com/5040231/62817675-25b59f80-bb6d-11e9-8e14-aaa43b34d2a0.png)

**Comment by vacheli** [comment]
Also,No autocomplete suggestion
![image](https://user-images.githubusercontent.com/5040231/62817699-9ceb3380-bb6d-11e9-91ef-87dd9b1277d6.png)

**Comment by stamblerre** [comment]
@vacheli: Can you please share the full output of the `gopls -rpc.trace -v check /path/to/file.go` command? It's missing the top portion with the `go env`, which I need to see to investigate this. Are you using modules?

Also, autocompletion for unimported packages is not yet supported in `gopls` generally (https://github.com/golang/go/issues/31906), but you will not see any language features because it seems `gopls` cannot type-check your package.

**Comment by vacheli** [comment]
> @vacheli: Can you please share the full output of the `gopls -rpc.trace -v check /path/to/file.go` command? It's missing the top portion with the `go env`, which I need to see to investigate this. Are you using modules?
> 
> Also, autocompletion for unimported packages is not yet supported in `gopls` generally (#31906), but you will not see any language features because it seems `gopls` cannot type-check your package.

[gopls.log](https://github.com/golang/go/files/3497012/gopls.log)

**Comment by vacheli** [comment]
@stamblerre I use go module, but no set GO111MODULE environment variable.

**Comment by stamblerre** [comment]
Does the output of the `gopls -rpc.trace -v check path/to/file.go` change if you run `export GO111MODULE=on`?

Also can you `cd` into `/Users/vachel/work/code/gitlab.cowelltech.com/cloud-pos-ssl` and run `go list -e -json -compiled -test /Users/vachel/work/code/gitlab.cowelltech.com/cloud-pos-ssl`?

**Comment by vacheli** [comment]
Sorry, It's no problem, I didn't use it properly.
