### ISSUE TITLE
net/http: Client panics if RoundTripper returns neither response nor error

### ISSUE THREAD

**Issue by Teelevision** [golang/go#33563]
### What did you do?

Use a http.RoundTripper that returns neither response nor error.

https://play.golang.org/p/EGEjS2P2xQI

### What did you expect to see?

Documentation that the RoundTripper MUST return either response or error.

### What did you see instead?

https://github.com/golang/go/blob/1dc0110bf725640a9b912e3d31e6654ed1c4da9d/src/net/http/client.go#L119-L125

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0xffffffff addr=0x0 pc=0x24bc42]

goroutine 1 [running]:
net/http.redirectBehavior(0x311a6b, 0x3, 0x0, 0x84c510, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:422 +0x22
net/http.(*Client).do(0x840940, 0x84c510, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:655 +0x3a0
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:509
net/http.(*Client).Get(0x840940, 0x3122b2, 0x7, 0x5503, 0x0, 0x0, 0x0, 0x5503)
	/usr/local/go/src/net/http/client.go:398 +0xa0
main.main()
	/tmp/sandbox656600978/prog.go:15 +0xc0

Program exited: status 2.
```

**Comment by odeke-em** [comment]
Hello @Teelevision, thank you for filing this issue and welcome to the Go project!

So my apologies if am preaching to the choir; in Go, the idiomatic way of communicating
between functions is by returning values as well as error as per `(values..., error)`. You'll commonly see in Go code handling for which:
1. A non-nil error signals a non-normal flow/state of the program and requires a form of handling
2. If no error was encountered, the value is then assumed to be okay and can be dereferenced/used

if we have the case of `(*http.Response)(nil), (error)(nil)` both being `nil`, we are in an invalid state where the expectation of a valid *http.Response is no longer fulfilled. It would break from the norm to expect that every function handle both `error == nil` and `values == nil`

Right above the lines that you quoted, we've got
https://github.com/golang/go/blob/9c1f14f3763dbbc0d8105fa88c0b7bdad5674ee7/src/net/http/client.go#L115-L117

which says that RoundTrip returns a Response.

Also I believe this doc already says what you'd like it to report
https://github.com/golang/go/blob/9c1f14f3763dbbc0d8105fa88c0b7bdad5674ee7/src/net/http/client.go#L120-L123

<img width="675" alt="Screen Shot 2019-08-09 at 11 08 33 PM" src="https://user-images.githubusercontent.com/4898263/62818304-a4252980-bafa-11e9-9e7c-e2326495abe9.png">
and implicitly a nil Response can't have a status code.

What do you think?

**Comment by Teelevision** [comment]
Ok, thank you, this clarifies it for me.
