### ISSUE TITLE
cmd/go: 'go mod vendor' replacement fails if indirect

### ISSUE THREAD

**Issue by Teelevision** [golang/go#33566]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Untested.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/marius/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/marius/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.7/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/marius/PACE/bricks/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bn/qgsj5pj57hz95p6bknh10hw40000gn/T/go-build673679875=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I replaced a dependency with a modified version in a module A: https://github.com/pace/bricks/commit/be638357ffd20c43011a0ad51078cd90b4b513d9

When I do `go mod vendor` the modified version correctly appears in the vendor directory. If I however, in another module B, depend on that module A, `go mod vendor` places the original and not the modified version of the dependency in the vendor directory.

So it seems that replacements only work on the module that introduces them, not on other modules.

### What did you expect to see?

Module A and module B should have the same version of the dependency in the vendor directory.

### What did you see instead?

Module A has the modified dependency, module B the original.

**Comment by bcmills** [comment]
This is working as designed. Per https://tip.golang.org/cmd/go/#hdr-The_go_mod_file:

> Exclude and replace apply only in the main module's go.mod and are ignored in dependencies. See https://research.swtch.com/vgo-mvs for details.
