### ISSUE TITLE
const declaration comparison between complex numbers

### ISSUE THREAD

**Issue by golark** [golang/go#33579]
### What version of Go are you using (`go version`)?
go version go1.12.7 linux/amd64
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
linux, amd64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Comparison between two complex numbers in a constant declaration:
const unTypedConst = 0.2i > 0.3i
https://play.golang.org/p/ADx6O3eV1AU

### What did you expect to see?
Perhaps one could anticipate a default boolean type with value false generated

### What did you see instead?
internal compiler error: compareOp: bad comparison

**Comment by ALTree** [comment]
Thanks for reporting this. This is a dup of #32723, which already have a patch waiting to be merged.

I'm closing this issue as a dup of that one.
