### ISSUE TITLE
os.Stdin.stat doesn't work on Windows with WSL when STDIN is redirected

### ISSUE THREAD

**Issue by zachmu** [golang/go#33570]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 windows/amd64  
</pre>

### Does this issue reproduce with the latest release?
1.12.7 is the latest stable release. Haven't tried with 1.13.x

### What operating system and processor architecture are you using (`go env`)?

I'm running Ubuntu on Windows using WSL (see below).

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Zach Musgrave\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\Users\zachmu\liquidata\go-workspace
set GOPROXY=
set GORACE=
set GOROOT=c:\go
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ZACHMU~1\AppData\Local\Temp\go-build071076366=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I have a go program that attempts to call os.Stdin.Stat(). Complete program:

<pre>
package main

import (
	"fmt"
	"os"
)

func main() {
	fi, err := os.Stdin.Stat()
	if err != nil {
		panic(err)
	}

	if (fi.Mode() & os.ModeCharDevice) == 0 {
		fmt.Println("STDIN is piped")
	} else {
		fmt.Println("STDIN is a character device")
	}
}
</pre>

I'm invoking this program using WSL (window subsystem for linux), Ubuntu image. No redirection and piped redirection of STDIN both work, but a file redirection fails.

<pre>
% ./windowstest.exe
STDIN is a character device
% echo "hello" | ./windowstest.exe
STDIN is piped                       
%./windowstest.exe < hello.txt
panic: GetFileInformationByHandle /dev/stdin: Incorrect function.
</pre>

### What did you expect to see?
I expect os.Stdin.Stat() to return a result equivalent to the piped ("|") version. This is the behavior on Mac and (real) Linux with go 1.12.7.

### What did you see instead?
os.Stdin.Stat() returns an error.

**Comment by ianlancetaylor** [comment]
At first glance this appears to be a problem with WSL, not with Go.

**Comment by zachmu** [comment]
You appear to be correct -- this works with cmd.exe but not wsl.exe.

**Comment by zachmu** [comment]
Closing this. I'll go bother microsoft about it if WSL 2 doesn't fix it.
