### ISSUE TITLE
How to auto generate function code hidden .go files for static library built by -buildmode=archive?

### ISSUE THREAD

**Issue by smcduck** [golang/go#33576]
### What version of Go are you using (`go version`)?

<pre>
 go version go1.12.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN="/Users/***/git/bin"
GOCACHE="/Users/***/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/***/git/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/97/*****************/T/go-build********=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

`go build -buildmode=archive -o ***.a`

### What did you expect to see?

.a static library and .go header files generated.

This project has many public functions, structs and constants, it's too hard to write function code hidden .go files (close to c language .H header files) by hand. I hope to use some command or tool to generate .go "header" files for static library users.

### What did you see instead?

.a only

**Comment by ianlancetaylor** [comment]
That's not how Go works.  Go doesn't use header files at all.  You don't have to write them by hand.

Also, `-buildmode=archive` is the default for a non-main package.

For questions like this you may get better and faster answers if you use a forum.  See https://golang.org/wiki/Questions.
