### ISSUE TITLE
os: some functions fail if full paths are long (more than about 250 chars) on windows

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#3358]
<pre>This program creates directory, but fails to create file inside (CAREFUL IF CHANGING
THIS PROGRAM - YOU MIGHT END UP WITH FILES/DIRECTORIES YOU WILL NOT BE ABLE TO DELETE
WITH STANDARD SHELL TOOLS):

package main

import (
    &quot;fmt&quot;
    &quot;log&quot;
    &quot;os&quot;
    &quot;strings&quot;
)

func main() {
//  root := `\\?\c:\`
    root := `c:\`
    dir := root + strings.Repeat(&quot;d&quot;, 200)
    file := dir + `\` + strings.Repeat(&quot;f&quot;, 200)
    err := os.Mkdir(dir, 0777)
    if err != nil {
        log.Fatalf(&quot;Mkdir(%s): %v&quot;, dir, err)
    }
    f, err := os.Create(file)
    if err != nil {
        log.Fatalf(&quot;Create(%s): %v&quot;, file, err)
    }
    _, err = fmt.Fprintf(f, &quot;Hello world&quot;)
    if err != nil {
        log.Fatalf(&quot;Fprintf(%s): %v&quot;, file, err)
    }
    err = f.Close()
    if err != nil {
        log.Fatalf(&quot;Close(%s): %v&quot;, file, err)
    }
    err = os.Remove(file)
    if err != nil {
        log.Fatalf(&quot;Remove(%s): %v&quot;, file, err)
    }
    err = os.Remove(dir)
    if err != nil {
        log.Fatalf(&quot;Remove(%s): %v&quot;, dir, err)
    }
}

This can be handled properly if we use \\?\ path prefix (uncomment line in the code).
But \\?\ prefixed paths needs to be &quot;normalized&quot;: they have to be absolute, no
. or .. allowed, / is not allowed, UNC paths needs to be handled properly. See
<a href="http://goo.gl/th2fJ">http://goo.gl/th2fJ</a> for details, especially &quot;Maximum Path Length Limitation&quot;
section.

This issue has come up on our own builder: <a href="http://goo.gl/FbblU">http://goo.gl/FbblU</a>. Perhaps our own paths do
not need to be that long. I did not look into that yet.

Alex</pre>

**Comment by xStrom** [comment]
Is anyone currently working on a solution for this? I am willing to supply a fix myself, but I was asked to consolidate planning in this thread.

As evidenced by the slew of issues referencing this one, this bug is affecting people all the time. With the explosive growth of node's popularity, we can only expect the frequency of people running into this bug to grow similarly. Indeed I ran into this while using the govendor tool on a rather simple project that contains gulp: `C:\Gopath\src\bitbucket.org\xStrom\lopya\node_modules\gulp\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\normalize-package-data\node_modules\validate-npm-package-license\node_modules\spdx-correct\node_modules\spdx-license-ids\LICENSE`.

As mentioned in this thread, it is currently possible to supply "\\\\?\\" prepended paths to some of the `os` package functions to solve the issue. This however goes directly against the claim made in the `os` package documentation: ["a platform-independent interface to operating system functionality"](https://golang.org/pkg/os/). There's nothing platform-independent about an if-windows-then-prepend block before every function call.

Then there's also the problem that Windows API does some magic handling of paths shorter than MAX_PATH. Replacing "/" with "\\" etc. So if we just start prepending "\\\\?\\" then people's existing code will start breaking, if they're using *C:/foo/bar.txt* or something similar as input.

I think a reasonable solution would be to do a length check on the path name before syscalling. If the name fits MAX_PATH, then use it as is, and enjoy the extra magic. If the name exceeds MAX_PATH and doesn't already start with "\\\\?\\", then we can only benefit from prepending "\\\\?\\". This solution is backwards compatible with magic-needing paths (e.g. *C:/foo/bar.txt*) that are already being used in the wild, and is also backwards compatible with code that already has their own if-windows-then-prepend block. Yes no magic would be applied to long paths, but those magic-needing long paths don't work currently either.

**Comment by bradfitz** [comment]
@xStrom, sounds like a plan. Feel free to send a change for review.

I also think it's simple enough for us to replace `/` with `\` when prepending `\\?\` for long paths.

**Comment by alexbrainman** [comment]
@xStrom are you aware that not all Windows APIs work with long path? For example, see https://github.com/golang/go/issues/10577#issuecomment-96925558 What is your plan to deal with those situations?

Alex

**Comment by minux** [comment]
Keep in mind that we also need to handle relative paths, . and .. ourselves
if we use \\?\ paths. There might be other complications.

**Comment by xStrom** [comment]
@alexbrainman I'll look into it, thanks for the link. My plan in general is best effort with limited scope. I think even partial improvement with backwards compatibility is a success.

@minux that's exactly the *magic* that I was talking about in my previous post. I agree that it would be nice to support relative paths etc, but that's not something I'm too excited about solving right now. Paths longer than MAX_PATH don't work right now at all. Adding support for long full paths seems easy and I don't think support for them should be held back by the lack of support for long relative paths. Again, I don't plan on changing behavior of paths shorter than MAX_PATH, so relative paths there will continue to work just fine.

I haven't written the changes yet, they're only theoretical based on brief reviews of the Go source & my knowledge of the Windows API. I hope to get some practical testing done soon.

**Comment by alexbrainman** [comment]
> ... My plan in general is best effort with limited scope. I think even partial improvement with backwards compatibility is a success.

I am skeptical about "best effort" approach. This sometimes gets interpreted as "it works". And later as "it is expected to work". If things are broken, I don't want to give false impression.

If any of your changes solve a particular problem we have, then I am OK with them. Otherwise I am not.

Alex

**Comment by iafan** [comment]
Hi there. Just ran across the same issue in #15615 (thanks to @bradfitz for pointing me to this thread). 

I don't think it makes sense to "magically" fix the file paths on every syscall, tbh. My concern is, obviously, the speed. I traverse a huge directory tree, and I don't want Go internals to be analyzing and fixing the path deep in the loop, when the proper solution in my case would be to provide a `\\?\`-prefixed canonical path just once in the call to `filepath.Walk()`.

What makes sense to me is to have some helper function, e.g. `filepath.Canonicalize()` that, under Windows, would replace all `/` with `\` and prepend `\\?\` (or return an error if the provided path is not absolute). This way everyone can use such a function as early as possible (when processing user input or external data), and forget about _"if windows then ... else ..."_ kind of code. The very existence of such a function, along with its documentation, will make other developers aware of OS-specific caveats. Other corresponding FS-related functions might then link to that function.

Internal functions that return the file path, like `os.Getwd()`, `os.TempDir()` or `filepath.Abs()` could also benefit from returning a canonicalized path that other functions can safely consume.

**Comment by bradfitz** [comment]
@iafan, what matter is being correct and consistent, and providing a simple interface. The speed is a detail which can be fixed. We shouldn't make an ugly API just for speed reasons.

**Comment by minux** [comment]
A compromise solution:

We make all the std library function (exclude syscall) that manipulate
paths always generate and use Cleaned paths so that when necessary, the
user can pass a \\?\ style path and all the functions still work as
expected.

We can even document this.

**Comment by wpostma** [comment]
Further activity by Microsoft on Windows 10 updates has rendered some of the underlying MAX_PATH/250-char limit stuff less troublesome.

For your GO app to take advantage of the "I am large path aware" feature in Windows, a manifest file must be attached to your app. It would be nice if Go made adding that manifest easy on Windows.

Manifests are also useful for other purposes like specifying that you require a particular version of some system library, and may be useful to some very small amount of users to have a custom manifest, but a default manifest that is at least marking the app as "large path aware" might be a useful thing to think of doing.

**Comment by harshavardhana** [comment]
We have been successfully using a nice wrapper on windows for Minio, same code path works transparently for both Unixes and Windows. 

```
// UNCPath converts a absolute windows path to a UNC long path.
func UNCPath(path string) string {
        // Clean the path for any trailing "/".
        path = filepath.Clean(path)

        // UNC can NOT use "/", so convert all to "\".
        path = filepath.FromSlash(path)

        // If prefix is "\\", we already have a UNC path or server.
        if strings.HasPrefix(path, `\\`) {

                // If already long path, just keep it
                if strings.HasPrefix(path, `\\?\`) {
                        return path
                }

                // Trim "\\" from path and add UNC prefix.
                return `\\?\UNC\` + strings.TrimPrefix(path, `\\`)
        }
        path = `\\?\` + path
        return path
}
```

**Comment by alexbrainman** [comment]
> It would be nice if Go made adding that manifest easy on Windows.

This https://github.com/lxn/walk/blob/master/README.mdown#create-manifest-testmanifest is one one way to do it.

Alex

**Comment by rsc** [comment]
Even though Windows 10 will "fix" this, not everyone has it, and not everyone will have it for quite a while.

It seems like we should probably fix it too, by transparently flipping to the \\?\ syntax for _absolute_ paths passed to the os calls. This is worth prototyping at least.

**Comment by harshavardhana** [comment]
> Even though Windows 10 will "fix" this, not everyone has it, and not everyone will have it for quite a while.
> 
> It seems like we should probably fix it too, by transparently flipping to the \?\ syntax for absolute paths passed to the os calls. This is worth prototyping at least

All operations work transparently other than helpers like MkdirAll and RemoveAll which needs a custom wrapper. But it is neatly doable 

Should i make a PR?

**Comment by cretz** [comment]
I have tested this on 1.8 beta 2 and still have issues with large go build calls:

    go build github.com/cretz/myproj: C:\dls\go1.8\go\pkg\tool\windows_amd64\compile.exe: fork/exec C:\dls\go1.8\go\pkg\tool\windows_amd64\compile.exe: The filename or extension is too long.

I can open this as a separate bug if that works better.

**Comment by bradfitz** [comment]
@cretz, please file a separate bug. My guess is that problem is separate, since the magic we added here to the `os` package doesn't help the `syscall` package, since `syscall` (where the exec happens) doesn't use `os`.
