### ISSUE TITLE
time: time.Unix(0, 0).IsZero() == false

### ISSUE THREAD

**Issue by h4xnoodle** [golang/go#33597]
I'm aware that IsZero is implemented with year 1, Jan 1 being 'zero'. (https://golang.org/pkg/time/#Time.IsZero) However, it causes confusion when most developers use epoch time at 0, and the IsZero function is then false for `time.Unix(0,0)`. 

**Why is zero time considered year 1, Jan 1 instead of epoch 0?**

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/Users/bex/workspace/bin"
GOCACHE="/Users/bex/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/bex/workspace/bosh-cli-workspace"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.7/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z7/dyfnyjn14rngs_4g0bfwc5440000gp/T/go-build443496455=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
https://play.golang.org/p/NtsWcGMJMaU

### What did you expect to see?
IsZero evaluates to `true` for the beginning of epoch time. I'm unsure what the compelling reason for deviating from typical standards is.

### What did you see instead?
Using epoch time within my applications and golang requires special consideration and it does not work as expected. I feel the deviation is unnecessarily complicated, though now would be a breaking change so we cannot just change it now.

**Comment by bradfitz** [comment]
This is working as intended and documented:

https://golang.org/pkg/time/#Time
https://golang.org/pkg/time/#Time.IsZero

Even if we wanted to change it, we couldn't at this point for go1compat reasons.

Go's time.Time zero value is not the Unix epoch zero value. The `Unix` func converts from Unix to Go.

**Comment by runner-mei** [comment]
@bradfitz  Can fix it on go2

**Comment by ianlancetaylor** [comment]
@runner-mei We could change it in a v2 of the time package, but we aren't going to do that.  See the discussion at https://golang.org/src/time/time.go?#L346.

**Comment by Dongss** [comment]
```
var TimeFromUnixZero = time.Unix(0, 0)
t := time.Now()
isZero := t.Equal(TimeFromUnixZero)
```

I use this instead

**Comment by runner-mei** [comment]
add IsUnixZero()？

**Comment by ianlancetaylor** [comment]
I don't think this comes up often enough to need a special function or method.
