### ISSUE TITLE
runtime: why a variable in closure can not be read in time? 

### ISSUE THREAD

**Issue by chenqinghe** [golang/go#33591]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.11 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\username\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\libs;E:\projects
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\username\AppData\Local\Temp\go-build715944026=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
here is the code:

```go
package main

import (
	"fmt"
	"sync"
)

func main() {
	var (
		i int
		wg sync.WaitGroup
	)

	wg.Add(2)

	go func() {
		for {
			i++
		}
	}()

	go func() {
		for {
			fmt.Println(i)
		}
	}()

	wg.Wait()
}


```
my  computer has 4 logic cpu, so these two goroutines may both have opportunity to run, but unfortunately, what was printed is always 0.
### What did you expect to see?
print different value of `i`

### What did you see instead?

always print  0

**Comment by bserdar** [comment]
The two goroutines do not communicate, so there is no guarantee that something happens in one is visible to the other.

https://golang.org/ref/mem

**Comment by Yanwenjiepy** [comment]
Both goroutines are running, but i in main is always 0, and the gorout that executes i++ does not copy an i to perform the add operation.
Is i++ been executed by cpu, but the result is not updated to i in main?

**Comment by Yanwenjiepy** [comment]
> The two goroutines do not communicate, so there is no guarantee that something happens in one is visible to the other.
> 
> https://golang.org/ref/mem

3Q

**Comment by av86743** [comment]
Dup of https://github.com/golang/go/issues/10958.
