### ISSUE TITLE
expvar: Map: excessive sorting in Add

### ISSUE THREAD

**Issue by bemehow** [golang/go#33607]
It looks like `Map` is re-sorting the `keys` slice on every `Add` even though sorting is really needed for `Do` and introduces overhead for simple set operations.

This overhead is showing up in when profiling via `pprof`

![image](https://user-images.githubusercontent.com/2608098/62896443-ecfcfe00-bd05-11e9-8c55-af71d169537d.png)

I'm using `go version go1.12.5 darwin/amd64`

**Comment by jsign** [comment]
The required change to address this was merged [here](https://github.com/golang/go/commit/518ee55d7814a1de66ec9e2fb4829711cc63d0aa#diff-e4fb3a2d42311171535831443fb1fca2). Planned for `1.13`.

**Comment by bcmills** [comment]
@bemehow, is the problem you encountered resolved when using `go1.13rc2`?
