### ISSUE TITLE
the package "net/rpc" has no timeout mecchanism????

### ISSUE THREAD

**Issue by 756445638** [golang/go#33615]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\yuyang\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\golib;D:\backstage\newest\hmi-server\code\gopath;D:\BATCH_backstage\code\newest\batchServer;
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\yuyang\AppData\Local\Temp\go-build927238374=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you expect to see?
nothing,just send a rpc package to another server.

### What did you see instead?
looks like the function will block forever!!!

goroutine 67 [chan receive, 15 minutes]:
net/rpc.(*Client).Call(...)
	C:/Go/src/net/rpc/client.go:322
hmi-server/common/rpc/client.(*SingleConnRpcClient).Send(0xc0001f6d80, 0xc0024c3c30, 0x4, 0xc002ae2a01)
	D:/backstage/newest/hmi-server/code/gopath/src/hmi-server/common/rpc/client/single.go:32 +0x24a
hmi-server/agent/g.SendToVarcompute(0xae789e, 0xc, 0x9e85a0, 0xc00016a260, 0xb14cb0, 0xfc63b0)
	D:/backstage/newest/hmi-server/code/gopath/src/hmi-server/agent/g/varcompute.go:29 +0x156
hmi-server/agent/cron.(*DeviceOpc).reportData.func1(0xbf4cad82ee7bb62c, 0x3a043ac3231, 0xfa95c0, 0xc002ae2a01, 0x2)
	D:/backstage/newest/hmi-server/code/gopath/src/hmi-server/agent/cron/variable.go:644 +0xe1
hmi-server/agent/cron.(*DeviceOpc).reportData(0xc0000d0160)
	D:/backstage/newest/hmi-server/code/gopath/src/hmi-server/agent/cron/variable.go:654 +0x2e0
created by hmi-server/agent/cron.(*DeviceOpc).start
	D:/backstage/newest/hmi-server/code/gopath/src/hmi-server/agent/cron/variable.go:300 +0x9c7

goroutine 69 [chan receive, 15 minutes]:
net/rpc.(*Client).Call(...)
	C:/Go/src/net/rpc/client.go:322
hmi-server/common/rpc/client.(*SingleConnRpcClient).Send(0xc0001f6d80, 0xc0010b7ab0, 0x4, 0xc000c54101)
	D:/backstage/newest/hmi-server/code/gopath/src/hmi-server/common/rpc/client/single.go:32 +0x24a
hmi-server/agent/g.SendToVarcompute(0xae789e, 0xc, 0x9e85a0, 0xc0002ca9e0, 0x40a9b2, 0x10)
	D:/backstage/newest/hmi-server/code/gopath/src/hmi-server/agent/g/varcompute.go:29 +0x156
hmi-server/agent/cron.(*DeviceOpc).setNetMetric(0xc0000d0420, 0xc00061b430)
	D:/backstage/newest/hmi-server/code/gopath/src/hmi-server/agent/cron/variable.go:623 +0x136
hmi-server/agent/cron.(*DeviceOpc).collect(0xc0000d0420, 0xc000444000, 0x1b7b, 0x1f9c, 0xc0005e7840, 0x18, 0xc00061b430)
	D:/backstage/newest/hmi-server/code/gopath/src/hmi-server/agent/cron/variable.go:596 +0x5bb
created by hmi-server/agent/cron.(*DeviceOpc).start
	D:/backstage/newest/hmi-server/code/gopath/src/hmi-server/agent/cron/variable.go:295 +0x6c0

**Comment by checkmatesolo** [comment]
checkmatesolo

**Comment by agnivade** [comment]
Yes, the net/rpc package is frozen and not accepting new features. See the last line in https://golang.org/pkg/net/rpc/#pkg-overview.

See https://github.com/golang/go/issues/15236, https://github.com/golang/go/issues/16844. Please use grpc or other mature rpc frameworks.
