### ISSUE TITLE
Cover all the sub-packages when running coveage test

### ISSUE THREAD

**Issue by AnikHasibul** [golang/go#33618]
If I have a test file in `./pkg/tests/all_test.go`. And I run `go test  go test -coverprofile cover.out` form `./pkg` directory. I would like to see the coverage for all my sub-packages inside `./pkg` to be tested and covered as well instead of just `./pkg/tests/all.go`

**Comment by andybons** [comment]
You can achieve this with `go test -coverprofile cover.out ./...`
