### ISSUE TITLE
net/http: transport.go: strange assignment func(pc *persistConn) cancelRequest(error) to func(error)

### ISSUE THREAD

**Issue by gdi63** [golang/go#33634]
Does it really work? Does func(error) type match to method of persistConn 

type Transport struct {
	reqCanceler map[*Request]func(error)

func (t *Transport) replaceReqCanceler(r *Request, fn func(error)) bool {
		t.reqCanceler[r] = fn

func (pc *persistConn) cancelRequest(err error) {

func (pc *persistConn) roundTrip(req *transportRequest) (resp *Response, err error) {
	if !pc.t.replaceReqCanceler(req.Request, pc.cancelRequest) {

**Comment by smasher164** [comment]
Yes, it matches. See https://golang.org/ref/spec#Method_values.
Here is a playground example to demonstrate this behavior: https://play.golang.org/p/yHJtcrG4H0d.
For questions about Go, see https://golang.org/wiki/Questions.
