### ISSUE TITLE
Undeclared name when there is a declaration

### ISSUE THREAD

**Issue by stoicAlchemist** [golang/go#33636]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 darwin/amd64

$gopls version
version v0.1.3, built in $GOPATH mode
</pre>

### Does this issue reproduce with the latest release?
Yes, it is currently happening with the latest release

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
GOBIN=""
GOCACHE="~/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="~/.gopath"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.7/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
G

</pre></details>

### What did you do?
I'm following a course on Go splitting functionality between files and the files (that are in the same package as the main function). I'm using NeoVim as my IDE/Text editor with the COC.nvim plugin that calls for `gopls` as LSP server. Following the issue #33608 I was requested to execute the following command with the following output:

<pre>
$ gopls -rpc.trace -v check path/to/file.go

.
.
.
2019/08/13 11:20:26 Info:Build info
----------
version v0.1.3, built in $GOPATH mode

Go info
-------
go version go1.12.7 darwin/amd64

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.7/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ds/9zp1b1q9013098gtpld3zv0m0000gn/T/go-build071080114=/tmp/go-build -gno-record-gcc-switches -fno-common"
2019/08/13 11:20:26 Info:22.728451ms for GOROOT= GO111MODULE=  go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" , stderr: <<>>
2019/08/13 11:20:27 Info:936.646818ms for GOROOT=  go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--", stderr: <<>>
2019/08/13 11:20:27 Info:go/packages.Load
        packages = 1
2019/08/13 11:20:27 Info:go/packages.Load
        package = command-line-arguments
        files = [~/main.go]
~/main.go:4:12-19: undeclared name: newDeck
~/main.go:6:26-30: undeclared name: deal
</pre>

As you can see, there is a main.go file that is calling for the newDeck function, which is in the deal.go file (in the same main package)

### What did you expect to see?

A clean error/warning free output

### What did you see instead?

Errors marking `undeclared name: newDeck`. The error shows here: https://imgur.com/gallery/6rjR54D

**Comment by stamblerre** [comment]
What directory are you running the command from? What does your directory structure look like? Are you using Go modules?

**Comment by stoicAlchemist** [comment]
the same directory where the files are

**Comment by stamblerre** [comment]
Have you configured your `GOPATH` environment variable? It looks like it's not set in your `go env` that gets printed by `gopls`.

If you are not using modules (which it appears you are not), then you will need to have configured your `GOPATH` and your code needs to be in a subdirectory of `$GOPATH/src`. Based on your logs, it seems you are running both outside of `GOPATH` and outside of a module, so `gopls` is only recognizing your code as a single file package.

**Comment by stoicAlchemist** [comment]
I guess I must have deleted that by mistake, yes I have `GOPATH` set to `~/.gopath`. The project has those two files and are in the same directory, if I re-run the command with al the files involved, I get the same:

```
cards >>> gopls -rpc.trace -v check *.go                                                                                                                                                                               (0) [1] 16:56:01
2019/08/13 16:56:05 Info:1.006437735s for GOROOT= GOPATH=~/.gopath GO111MODULE= PWD=~/Tutorials/Go/cards go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "builtin", stderr: <<>>
2019/08/13 16:56:05 Info:Build info
----------
version v0.1.3, built in $GOPATH mode

Go info
-------
go version go1.12.7 darwin/amd64

GOARCH="amd64"
GOBIN=""
GOCACHE="~/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="~/.gopath"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.7/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ds/9zp1b1q9013098gtpld3zv0m0000gn/T/go-build401088351=/tmp/go-build -gno-record-gcc-switches -fno-common"
2019/08/13 16:56:05 Info:21.759202ms for GOROOT= GOPATH=~/.gopath GO111MODULE= PWD=~/Tutorials/Go/cards go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "~/Tutorials/Go/cards", stderr: <<>>
2019/08/13 16:56:06 Info:126.645027ms for GOROOT= GOPATH=~/.gopath GO111MODULE= PWD=~/Tutorials/Go/cards go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "~/Tutorials/Go/cards/deck.go", stderr: <<>>
2019/08/13 16:56:06 Info:go/packages.Load
        packages = 1
2019/08/13 16:56:06 Info:go/packages.Load
        package = command-line-arguments
        files = [~/Tutorials/Go/cards/deck.go]
2019/08/13 16:56:06 Info:22.478147ms for GOROOT= GOPATH=~/.gopath GO111MODULE= PWD=~/Tutorials/Go/cards go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "~/Tutorials/Go/cards", stderr: <<>>
2019/08/13 16:56:06 Info:139.931334ms for GOROOT= GOPATH=~/.gopath GO111MODULE= PWD=~/Tutorials/Go/cards go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "~/Tutorials/Go/cards/deck_test.go", stderr: <<>>
2019/08/13 16:56:06 Info:go/packages.Load
        package = command-line-arguments
        files = [~/Tutorials/Go/cards/deck_test.go]
2019/08/13 16:56:06 Info:go/packages.Load
        packages = 1
~/Tutorials/Go/cards/deck_test.go:27:11-18: undeclared name: newDeck
~/Tutorials/Go/cards/deck_test.go:30:17-32: undeclared name: newDeckFromFile
~/Tutorials/Go/cards/deck_test.go:9:8-15: undeclared name: newDeck
2019/08/13 16:56:06 Info:22.286626ms for GOROOT= GOPATH=~/.gopath GO111MODULE= PWD=~/Tutorials/Go/cards go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "~/Tutorials/Go/cards", stderr: <<>>
2019/08/13 16:56:06 Info:84.098107ms for GOROOT= GOPATH=~/.gopath GO111MODULE= PWD=~/Tutorials/Go/cards go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "~/Tutorials/Go/cards/main.go", stderr: <<>>
2019/08/13 16:56:06 Info:go/packages.Load
        package = command-line-arguments
        files = [~/Tutorials/Go/cards/main.go]
2019/08/13 16:56:06 Info:go/packages.Load
        packages = 1
~/Tutorials/Go/cards/main.go:4:12-19: undeclared name: newDeck
```

**Comment by stamblerre** [comment]
Ah, so it looks like your code is not inside of your `$GOPATH/src` directory. Here's some more information on how to configure your `GOPATH` correctly: https://golang.org/cmd/go/#hdr-GOPATH_environment_variable. You will probably find better resources for asking questions on this wiki page: https://github.com/golang/go/wiki/Questions.

Closing this issue since this doesn't appear to be a `gopls` bug. Feel free to reopen if I'm mistaken.

**Comment by stoicAlchemist** [comment]
Go is correctly running the code and building, I don't think this is a GO issue, I'll finish my course and check get a better understanding of the GOPATH variable, maybe I'm missing something, thanks anyway.
