### ISSUE TITLE
x/tools/cmd/gopls: error returned by client Configuration simply logged

### ISSUE THREAD

**Issue by myitcv** [golang/go#33645]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +61bb56ad63 Mon Aug 12 23:12:29 2019 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20190809145639-6d4652c779c4
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.1.4-0.20190809145639-6d4652c779c4
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build024756293=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

One of the issues I encountered whilst debugging https://github.com/golang/go/issues/33347 is that an error return from a server call to the client's `Configuration` method ends up simply being logged.

```
[Trace - 12:09:37 PM] Sending response 'workspace/configuration - (2)' in 0ms.
Params: {}


[Error - 12:09:37 PM] send workspace/configuration oh dear


[Trace - 12:09:37 PM] Sending notification 'initialized' in 1ms.
Params: {}


[Trace - 12:09:37 PM] Received notification 'window/logMessage' in 0ms.
Params: {"type":1,"message":": oh dear"}
```

This feels like a serious enough error for us to want to surface it to the user?

Is the right way to do this for the server to call `ShowMessage` instead of `LogMessage`?

---

cc @stamblerre @ianthehat

**Comment by stamblerre** [comment]
I think that we have started to report errors a bit better since this was filed (see https://github.com/golang/tools/blob/b1451cf3445bfc43d9982a3e85bec2dacced42ce/internal/lsp/general.go#L187). Is this still an issue for you, @myitcv?

**Comment by myitcv** [comment]
Yes, it is better handled now, thanks. Errors get reported back via `ShowMessage` which is exactly what I would hope/expect as the user.
