### ISSUE TITLE
feedback: Go2 generics proposal

### ISSUE THREAD

**Issue by snakeru** [golang/go#33659]
I have some feedback about "Why Generics?" blog entry (Ian Lance Taylor, 31 July 2019). I hope you find it useful.

As a long-time Go user, but a person who never heard (until today) about any in-progress generics effort in Go I find the following three aspects confusing:

1. (least confusing) The fact that a well-known keyword `type` appears in a function declaration
2. The fact that using a generic type and defining a contract for it use different keywords that are seemingly independent (`type` vs `contract`)
3. (most confusing) The fact that the word order in defining and using a generic type is different:
`type Graph (type Node, Edge G)`  vs `contract G(Node, Edge)` (note G taking the last and not-so-last position).

--

Personal opinion: all three issues could be solved by using the keyword `contract` in all places and changing the syntax:
`contract Node, Edge G {...}`
`type Graph (contract Node, Edge G) struct { ... }`
`func New (contract Node, Edge G) (nodes []Node) *Graph(Node, Edge) { ... }`

**Comment by agnivade** [comment]
Hello @snakeru - Thank you for the feedback. If you haven't seen, we are collecting generics related feedback [here](https://github.com/golang/go/wiki/Go2GenericsFeedback). May I request you to kindly add a section in that page with your feedback ?
