### ISSUE TITLE
mime/multipart: unable to process bigger parts

### ISSUE THREAD

**Issue by danielkucera** [golang/go#33666]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/u/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/yw674/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build154661289=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
func readStream(){
        resp, err := http.Get(device.Url)
        if err != nil {
                // handle error
        }
        defer resp.Body.Close()
        log.Printf("%v+", resp.Header)

        contentType := resp.Header.Get("Content-Type");
        if len(contentType) < 1 {
                return
        }

        mediaType, mediaTypeParams, err := mime.ParseMediaType(contentType)
        fmt.Println("parseMessageWithHeader", mediaType)
        if err != nil {
                return
        }
        
        boundary := mediaTypeParams["boundary"]
        log.Printf("boundary %s", boundary)

        mr := multipart.NewReader(resp.Body, boundary)
        for {
                p, err := mr.NextPart()
                if err == io.EOF {
                        return
                }
                if err != nil {
                        log.Fatal("np: ", err)
                }
                slurp, err := ioutil.ReadAll(p)
                if err != nil {
                        log.Fatal("io: ", err)
                }
                fmt.Printf("Part %q: %q\n", p.Header.Get("Foo"), slurp)
        }
}
</pre>

### What did you expect to see?

MJPEG chunks to be read to slurp.

### What did you see instead?
```
2019/08/15 13:30:16 map[Content-Type:[multipart/x-mixed-replace; boundary=--myboundary] Date:[Thu, 15 Aug 2019 11:30:16 GMT]]+
parseMessageWithHeader multipart/x-mixed-replace
2019/08/15 13:30:16 boundary --myboundary
2019/08/15 13:30:16 np: multipart: NextPart: bufio: buffer full
```

I suspect this is due to peekBufferSize is only 4096 bytes:
https://github.com/golang/go/blob/9b2bd2f7151381cc54638726808f55c6088fa30a/src/mime/multipart/multipart.go#L32
And the single parts of multipart are much longer (few hundreds of kBs)
Would it be possible to make this value configurable for example by adding NewReader method with configurable buffer size?
https://github.com/golang/go/blob/9b2bd2f7151381cc54638726808f55c6088fa30a/src/mime/multipart/multipart.go#L100
Shall I create a PR?

**Comment by danielkucera** [comment]
something like this: 
https://github.com/golang/go/commit/69cb30b432c62464c945cc8ba8a97d06006929ca

**Comment by andybons** [comment]
@bradfitz @minux

**Comment by danielkucera** [comment]
My bad, the boundary returned from `mime.ParseMediaType`
```
boundary := mediaTypeParams["boundary"]
```
contains leading dashes:
```
2019/08/15 13:30:16 boundary --myboundary
```
After striping them out, everything works ok.

**Comment by andybons** [comment]
@danielkucera glad you found the issue. Thanks for following up.
