### ISSUE TITLE
cmd/compile: new escape analysis implementation doesn't heap-allocate pointer

### ISSUE THREAD

**Issue by dsnet** [golang/go#33662]
[Apache Beam has a function as follows](https://github.com/apache/beam/blob/b7bca84e8250bb7fc7d3245af55c8b671fab4736/sdks/go/pkg/beam/core/util/reflectx/functions.go#L41-L45):
```go
func LoadFunction(ptr uintptr, t reflect.Type) interface{} {
	v := reflect.New(t).Elem()
	*(*uintptr)(unsafe.Pointer(v.Addr().Pointer())) = (uintptr)(unsafe.Pointer(&ptr))
	return v.Interface()
}
```

When compiled on Go1.12 with `-gcflags=-m`, we see:
```go
functions.go:43: &ptr escapes to heap
```
When compiled on Go1.13 with `-gcflags=-m`, the fact that `&ptr` escapes is no longer true. The effect of this change is a subtle memory corruption where since `&ptr` now points to the heap, rather than a copy of the value on the stack.

Git bisect reports that the issue is due to [CL/170448](https://go-review.googlesource.com/c/go/+/170448), which seems to suggest that this breakage is intentional. The fix the Beam code is relatively straight forward by manually allocating `ptr` on the heap.

I'm filing an issue to confirm that this is an expected regression.

\cc @mdempsky @dr2chase

**Comment by cherrymui** [comment]
I think this was intentional. The assignment is done as integer assignment, not pointer assignment, so it does not form an escape edge. The old escape analysis was a bit conservative on this.

**Comment by mdempsky** [comment]
Yeah, the change was intentional. That LoadFunction code is not using unsafe.Pointer safely according to https://golang.org/pkg/unsafe/#Pointer

Easiest fix would be:

	*(**uintptr)(unsafe.Pointer(v.Addr().Pointer())) = &ptr

**Comment by andybons** [comment]
Closing as this is confirmed intentional behavior. Thanks, @mdempsky and @cherrymui!
