### ISSUE TITLE
cmd/go: "go_asm.h:585:39: 'p' exponent requires hexadecimal mantissa" when building go1.12.9 with go1.13beta1

### ISSUE THREAD

**Issue by choleraehyq** [golang/go#33679]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13beta1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Use go1.13beta1 to compile go1.12.9

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/cholerae/Library/Caches/go-build"
GOENV="/Users/cholerae/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/cholerae/Documents/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/cholerae/Documents/gopath/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/cholerae/Documents/gopath/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lg/ld5t5rss459241qtzmqfp0h80000gn/T/go-build175651752=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

GOROOT_BOOTSTRAP=~/Documents/gopath/go1.13beta1 ./make.bash

### What did you expect to see?

Build successfully without extra logs.

### What did you see instead?

```
Building Go cmd/dist using /Users/cholerae/Documents/gopath/go1.13beta1.
Building Go toolchain1 using /Users/cholerae/Documents/gopath/go1.13beta1.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
go_asm.h:584:33: 'p' exponent requires hexadecimal mantissa
go_asm.h:585:39: 'p' exponent requires hexadecimal mantissa
go_asm.h:584:33: 'p' exponent requires hexadecimal mantissa
go_asm.h:585:39: 'p' exponent requires hexadecimal mantissa
go_asm.h:584:33: 'p' exponent requires hexadecimal mantissa
go_asm.h:585:39: 'p' exponent requires hexadecimal mantissa
go_asm.h:584:33: 'p' exponent requires hexadecimal mantissa
go_asm.h:585:39: 'p' exponent requires hexadecimal mantissa
Building Go toolchain2 using go_bootstrap and Go toolchain1.
# runtime
go_asm.h:584:33: 'p' exponent requires hexadecimal mantissa
go_asm.h:585:39: 'p' exponent requires hexadecimal mantissa
# runtime
go_asm.h:584:33: 'p' exponent requires hexadecimal mantissa
go_asm.h:585:39: 'p' exponent requires hexadecimal mantissa
# runtime
go_asm.h:584:33: 'p' exponent requires hexadecimal mantissa
go_asm.h:585:39: 'p' exponent requires hexadecimal mantissa
# runtime
go_asm.h:584:33: 'p' exponent requires hexadecimal mantissa
go_asm.h:585:39: 'p' exponent requires hexadecimal mantissa
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for darwin/amd64.
---
Installed Go for darwin/amd64 in /Users/cholerae/Documents/gopath/go1.12.9
```

**Comment by ALTree** [comment]
This is #33625. Closing here as a dup.
