### ISSUE TITLE
time: Time.Sub regression

### ISSUE THREAD

**Issue by dsnet** [golang/go#33677]
Consider the following:
```go
func main() {
	t := time.Date(2311, 11, 26, 02, 16, 47, 63535996, time.UTC)
	u := time.Date(2019, 8, 16, 02, 29, 30, 268436582, time.UTC)

	fmt.Println(int(time.Second) + t.Nanosecond() - u.Nanosecond())
	fmt.Println(t.Sub(u))
}
```

On `go1.12`, this prints:
```
795099414
2562047h47m16.795099414s
```

On `go1.13beta1`, this prints:
```
795099414
2562047h47m16.854775807s
```

Notice how the nanoseconds are off? On 1.12, it is correctly `.795099414`, while on 1.13, it is incorrectly `.854775807`. This regression causes the calculation of timeouts for network connections to go wonky in RPC implementations.

The culprit for this regression is https://golang.org/cl/131196

\cc @pongad @ianlancetaylor @cybrcodr @paranoiacblack

**Comment by pongad** [comment]
Wanted to give a little update on this. (Apologies if this should be written elsewhere.)

There is a fix for this that passes all tests by checking `t.Before(u)` against the sign of the computed duration. At least on my laptop, the performance benefit of this is rather small at ~20% in an already-fast function. I'm not sure if this is actually worth doing. Unless someone can think of a better algorithm for this?
