### ISSUE TITLE
image/draw: subimage rectangle's MIN point is not (0,0)

### ISSUE THREAD

**Issue by leexingliang** [golang/go#33681]
### What version of Go are you using (`go version`)?

 go version go1.12.1 linux/amd64

### Does this issue reproduce with the latest release?

Not

### What operating system and processor architecture are you using (`go env`)?

<pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/work/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/work/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/work/fencoder/huifang-fencoder/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build595600236=/tmp/go-build -gno-record-gcc-switches"

</pre>

### What did you do?
I want to capture part of the RGBA image with rectangle by using image.RGBA.SubImage funcation.

```go
func subimage(src *image.RGBA, rect image.Rectangle) *image.RGBA {
	// src.Rect = image.Rectangle{
	// 	Min: image.Point{0, 0},
	// 	Max: image.Point{1000, 1000},
	// }

	dstrect := image.Rect(100, 100, 200, 200)
	dstimage := src.SubImage(dstrect)

        fmt.Println("dstimage rectangle: ", dstimage.Bounds())
        return dstimage.(*image.RGBA)
}
```

### What did you expect to see?
for above code 
```
dstimage rectangle: (100,100)-(200,200)
```

### What did you see instead?

```
dstimage rectangle: (0,0)-(100,100)
```
that equal image.Rect(0, 0, rect.Dx(), rect.Dy())

**Comment by nigeltao** [comment]
This is intentional. See https://blog.golang.org/go-image-package, which says that "A common mistake is assuming that an Image's bounds start at (0, 0)".

**Comment by nigeltao** [comment]
Judging from the issue title, "subimage rectangle's MIN point is not (0,0)", I assume that you are expecting that dstimage's rectangle starts at (0, 0).

In other words, the "What did you expect to see?" and "What did you see instead?" sections' contents should be swapped around.

**Comment by leexingliang** [comment]
> Judging from the issue title, "subimage rectangle's MIN point is not (0,0)", I assume that you are expecting that dstimage's rectangle starts at (0, 0).
> 
> In other words, the "What did you expect to see?" and "What did you see instead?" sections' contents should be swapped around.

yeah,  i will mod it
