### ISSUE TITLE
x/dl: UTF-8 source file names differ after unpacking go1.12.9.src.tar.gz

### ISSUE THREAD

**Issue by Sevolin** [golang/go#33709]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.12.9 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/home/u1/go/pkg/tool/linux_amd64/"
GOCACHE="/home/u1/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/u1/go/projects"
GOPROXY=""
GORACE=""
GOROOT="/home/u1/go"
GOTMPDIR="/home/u1/go/tmpdir"
GOTOOLDIR="/home/u1/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/home/u1/go/tmpdir/go-build983033821=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

In git "https://github.com/golang/go"  in dir "test/fixedbugs/issue27836.dir"
the files are called "Äfoo.go" and "Ämain.go".

In website "https://golang.org/dl/" in go1.12.9.src.tar.gz and for previous
versions of GO these files are called "foo.go" and "main.go"

This difference has existed for so long that you can't remember when it started.
And if you unarchieve go1.12.9.src.tar.gz and compile, then an error is generated:

##### API check
Go version is "go1.12.9", ignoring -next /home/u1/go/api/next.txt

ALL TESTS PASSED
---
Installed Go for linux/amd64 in /home/u1/go
Installed commands in /home/u1/go/bin
*** You need to add /home/u1/go/bin to your PATH.

##### ../test
# go run run.go -- fixedbugs/issue27836.go
exit status 1
/home/u1/go/test/fixedbugs/issue27836.dir/main.go:6:2: can't find import: "Äfoo"

FAIL	fixedbugs/issue27836.go	0.061s
2019/08/18 22:13:33 Failed: exit status 1

##### API check
Go version is "go1.12.9", ignoring -next /home/u1/go/api/next.txt
2019/08/18 22:13:34 FAILED

**Comment by bcmills** [comment]
The tarball itself appears to contain the correct names for these files:

```
~/tmp$ curl -O https://dl.google.com/go/go1.12.9.src.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20.9M  100 20.9M    0     0  36.2M      0 --:--:-- --:--:-- --:--:-- 36.2M

~/tmp$ LC_ALL=en_US.UTF-8 tar --list -zf ./go1.12.9.src.tar.gz | grep issue27836
go/test/fixedbugs/issue27836.dir/
go/test/fixedbugs/issue27836.dir/Äfoo.go
go/test/fixedbugs/issue27836.dir/Ämain.go
go/test/fixedbugs/issue27836.go
```

What exact commands did you run to unpack the tarball, into what kind of filesystem and with what [locale environment variables](http://pubs.opengroup.org/onlinepubs/7908799/xbd/envvar.html#tag_002_002)?

**Comment by bcmills** [comment]
Note that the [Installing Go from source](https://golang.org/doc/install/source#fetch) page recommends fetching the repository using `git clone` rather than downloading the source tarball.
