### ISSUE TITLE
x/website: documents link is not aligned on tip.golang.org/doc/go1.6+

### ISSUE THREAD

**Issue by JAicewizard** [golang/go#33718]
### What did you do?
visit one of:
https://tip.golang.org/doc/go1.6
...
https://tip.golang.org/doc/go1.13

### What did you expect to see?
see behavior on everything pre go1.6 docs

### What did you see instead?
![documents_not_aligned](https://user-images.githubusercontent.com/19241481/63279822-fc51ed80-c2a9-11e9-8daa-00033fc2e2f5.png)

**Comment by ALTree** [comment]
Ah, that's funny. In the Go1.5 and before they're aligned. The issue is caused by an embedded style 

```
<style>
ul li { margin: 0.5em 0; }
</style>
```

in the .html page, that is present since the Go1.6 release notes (but not before).

**Comment by tomocy** [comment]
Can I tackle on this?

**Comment by ALTree** [comment]
@tomocy Sure. If you do, please double-check that my analysis above is correct. I just skimmed the pages sources quickly.

**Comment by JAicewizard** [comment]
@ALTree FYI that rule is overwritten by line 429 of style.css, so that is not the issue.
If I disable both of the morgin-top rules it works on all pages, but more testing is requred to make sure that its more then just a "works for me" kinda fix.

And in general its weird that ALL other pages work as expected.

**Comment by tomocy** [comment]
@ALTree I want to modify `/lib/godoc/style.css`,  but I cannot find it. Where is it located??

**Comment by agnivade** [comment]
https://github.com/golang/website/blob/master/content/static/style.css

**Comment by tomocy** [comment]
@agnivade Thank you!! (I did not know website repo)

**Comment by andybons** [comment]
Duplicate of #33738
