### ISSUE TITLE
x/mobile: The sdk generated by gomobile cause crash in Android Q (API 29)

### ISSUE THREAD

**Issue by AlisaLLL** [golang/go#33715]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.12.7
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wucanrui/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="linux"
GOPATH="/Users/wucanrui/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.7/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD="/Users/wucanrui/Desktop/develop/SAG/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0_/j6m36l9s0psg9xm5ggt2_b680000gp/T/go-build077800331=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

When I call the function in sdk generated by gomobile in andorid api 29, the application crashed and I get the log as below. While it runs well in andorid api 28 and lower.

<pre>
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 15296 (e.myapplication), pid 15272 (e.myapplication)
A/go/Seq: failed to initialize jnienvs thread local storage
Application terminated.
</pre>

**Comment by bcmills** [comment]
CC @hyangah @steeve

**Comment by hyangah** [comment]
See #29674 

Please try the go1.13 release candidate or beta version. The fix is non-trivial so it's not backported to go1.12.
