### ISSUE TITLE
encoding/json: slice out of bounds decoder crash found via fuzzing

### ISSUE THREAD

**Issue by mvdan** [golang/go#33728]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=16500

Filing this issue to track it. I'll update the thread once I have a reproducer.

This is a bug introduced in 1.13, but given how late the release already is, I don't want to mark this as a release blocker. We can easily backport a fix for 1.13.1 if necessary.

**Comment by mvdan** [comment]
Manually minified repro case, which errors on 1.12.8, but panics on master (1.13): https://play.golang.org/p/MRohOdk3uIt

**Comment by cuonglm** [comment]
@mvdan it panics for me both with go1.12.8 and master, but with different reason. go1.12.8 gives 

```
`panic: json: invalid use of ,string struct tag, trying to unmarshal "\"" into int
```

**Comment by mvdan** [comment]
That's just an error; see my `panic(err)` line. An error here is correct, because the nested string is missing the closing quote.

**Comment by dmitshur** [comment]
I'll copy @FiloSottile's comment from https://go-review.googlesource.com/c/go/+/190909/1#message-40010dc222e17a86edce656aa3c589f8c5adb95a here:

> I don't have a strong opinion on whether to rollback or fix forward. Rolling back feels like the safer option, if Daniel agrees the revert is clean.
>
> This is here so it's easy to choose one or the other. Up to the rest of the OSP team to decide. We should not ship the RC without either though.

All that's left is to select which CL to go with, but we need to do that for 1.13 to avoid shipping a regression in behavior. This is a release blocker, but it shouldn't cause any extra delay because the fixes are ready.

**Comment by mvdan** [comment]
Up to you :) I just really, really hope that the release goes out soon.

**Comment by geraldstanje** [comment]
when is soon? :)

**Comment by andybons** [comment]
Revert was landed. Closing.
