### ISSUE TITLE
net/http/httputil: make it easier for ReverseProxy.ErrorHandler to preserve the request body

### ISSUE THREAD

**Issue by fovecifer** [golang/go#33726]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 darwin/amd64
</pre>

We could use `ErrorHandler func(http.ResponseWriter, *http.Request, error)` to handle errors when backend timeout, but one important fact is the `Body io.ReadCloser`
in http.Request of ErrorHandler func is no "readable", because the interface io.ReadClose
just like a stream, you could not read twice from it. 
So when I add some "retry function" in the ErrorHandler, the Body always empty, we could 
not retry this request to another health backend, to let my project work I do something like
this in `func (p *ReverseProxy) ServeHTTP(rw http.ResponseWriter, req *http.Request):`

```var buf bytes.Buffer
	if outreq.Body != nil && outreq.ContentLength != 0 {
		tee := io.TeeReader(outreq.Body, &buf)
		outreq.Body = ioutil.NopCloser(tee)
	}
	res, err := transport.RoundTrip(outreq)
	if err != nil {
		if outreq.Body != nil && outreq.ContentLength != 0 {
			outreq.Body = ioutil.NopCloser(&buf)
		}
		p.getErrorHandler()(rw, outreq, err)
		return
	}
```

Maybe we have 2 options:

1. Add Comments to ErrorHandler like this:
```
        // ErrorHandler is an optional function that handles errors
	// reaching the backend or errors from ModifyResponse.
        // *the Body of http.Request in this function maybe unreadable*
        // *because it readed by RoundTrip function*
	//
	// If nil, the default is to log the provided error and return
	// a 502 Status Bad Gateway response.
	ErrorHandler func(http.ResponseWriter, *http.Request, error)
```

2. Add a option to ReverseProxy, let the call to choose storing the body into buffer or not

**Comment by bcmills** [comment]
> Add a option to ReverseProxy, let the call to choose storing the body into buffer or not

As far as I can tell, you can already use the `Director` field to inject the `io.TeeReader`. The difficult part is how to pass the resulting buffer to the `ErrorHandler` function.

On the other hand, if you're assigning to `outreq.Body` anyway, then you could provide your own implementation than injects your own custom struct type, and use a type-switch to unpack that type within the `ErrorHandler` function. So it's not obvious to me that anything is needed here beyond the existing `Director` function.

**Comment by bcmills** [comment]
CC @bradfitz (on leave) for `httputil`.

**Comment by fovecifer** [comment]
> > Add a option to ReverseProxy, let the call to choose storing the body into buffer or not
> 
> As far as I can tell, you can already use the `Director` field to inject the `io.TeeReader`. The difficult part is how to pass the resulting buffer to the `ErrorHandler` function.
> 
Thank you!

Your way is much better, I should create a new "init" function like this:
```
func NewSingleHostBodyBufReverseProxy(target *url.URL, key string) *httputil.ReverseProxy {
	director := func(req *http.Request) {
		httputil.NewSingleHostReverseProxy(target).Director(req)
		if req.Body != nil && req.ContentLength != 0 {
			var buf bytes.Buffer
			tee := io.TeeReader(req.Body, &buf)
			req.Body = ioutil.NopCloser(tee)
			ctx := context.WithValue(req.Context(), key, &buf)
			r2 := req.WithContext(ctx)
			*req = *r2
		}
	}
	return &httputil.ReverseProxy{Director: director}
}
```
I inject the "buf" into context of request with the "key", so in my ErrorHandler, it could be 
```
if buf, ok := r.Context().Value("bodybuf").(*bytes.Buffer); ok {
	r.Body = ioutil.NopCloser(buf)
}
```

the existing `Director` and `ReverseProxy` are good enough
