### ISSUE TITLE
cmd/go: this version is not compatible with the version of Windows you're running error when building

### ISSUE THREAD

**Issue by mrjesen** [golang/go#33736]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Golang\gopath
set GOPROXY=https://mirrors.aliyun.com/goproxy/
set GORACE=
set GOROOT=D:\Golang\Go
set GOTMPDIR=
set GOTOOLDIR=D:\Golang\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build513384590=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
sometimes I run the "go build" command,and then failed to run the new program. .

### What did you expect to see?
new program created!

### What did you see instead?
it is created but when i run it ,the command line gives me a tip: The program is not a 64bit program.
[test.zip](https://github.com/golang/go/files/3520803/test.zip)

**Comment by ianlancetaylor** [comment]
Please tell us exactly what you did and show us exactly what happened.  Cut and paste from the terminal window.  Thanks.

**Comment by mrjesen** [comment]
2019-8-22 16:20:33 Build success! And it runs success.
2019-8-22 16:30:43 Build failed  return : C:\Users\ADMINI~1\AppData\Local\Temp\go-build805579086\b001\exe\main.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.


2019-8-22 16:37:46 I have found that : When i restart my pc ,the problem will be  solved. and after some time,the problem start again.

**Comment by mrjesen** [comment]
@ianlancetaylor

**Comment by ianlancetaylor** [comment]
You didn't tell us exactly what you did.  What exact command are you running that produces the output

```
2019-8-22 16:30:43 Build failed return : C:\Users\ADMINI~1\AppData\Local\Temp\go-build805579086\b001\exe\main.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.
```

That said, see https://golang.org/doc/faq#virus .

**Comment by ianlancetaylor** [comment]
It's also quite likely that you will get a better and faster answer in a forum.  See https://golang.org/wiki/Questions .
