### ISSUE TITLE
added otp package to generate otp 

### ISSUE THREAD

**Issue by shrikar007** [golang/go#33734]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.12.6

</pre>

### Does this issue reproduce with the latest release?
yes it resolves the problem with OTP generation

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/shrikar/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/shrikar/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build612801997=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
created a package that uses to generate OTP 
simply call a function and  specify the length of the OTP that returns generated OTP

### What did you expect to see?
this OTP package may be included inside go packages inbuilt

### What did you see instead?
getting All checks have failed
PR closed

**Comment by ianlancetaylor** [comment]
I'm not sure but it sounds like you are asking for a new function to be added to the Go standard library.,  See https://golang.org/doc/faq#x_in_std.  An OTP package can be a third party package; it doesn't have to be in the standard library.

I'm going to close this issue.  Please add a comment if I have misunderstood.
