### ISSUE TITLE
x/tools/gopls: Code navigation and lsp doesn't work when using go.mod replace

### ISSUE THREAD

**Issue by krasi-georgiev** [golang/go#33731]
<pre>
go version go1.12.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release? Yes
```
 gopls version
golang.org/x/tools/gopls v0.1.3
    golang.org/x/tools/gopls@v0.1.4-0.20190820033707-85edb9ef3283 h1:4RzCZ4grbWxufc4sDtqmkQ6criGdzTK41oyDOb7JnYQ=
```

As soon as you put something in the go.mod replace as
```
replace github.com/calvernaz/rak811 => ../local/rak811
```
The code navigation(clicking on the function name) still takes you to 
`github.com/calvernaz/rak811`

If I change some code in `../local/rak811` LSB complains about errors as it uses the `github.com/calvernaz/rak811` and ignores the replace directive.

**Comment by stamblerre** [comment]
Thanks for moving this issue! Just to confirm, are you opening VSCode at the module root (the directory that contains the `go.mod` file)?

**Comment by krasi-georgiev** [comment]
yes

**Comment by stamblerre** [comment]
Can you run the command `gopls -rpc.trace -v check path/to/file.go` when your code is in the state you described above (doesn't have errors, but `gopls` shows errors)?

**Comment by krasi-georgiev** [comment]
Thanks for this command, after running it I realized that I had a duplicate do.mod file in the subdir.
