### ISSUE TITLE
x/tools/cmd/gomvpkg: support Go modules

### ISSUE THREAD

**Issue by ainar-g** [golang/go#33754]
It seems like `gomvpkg` can't operate outside of `GOPATH`:

```
gomvpkg: src dir not found for package example.com/my/mod
```

It is a useful tool, and I would like to be able to use it with Go modules.

**Comment by agnivade** [comment]
Thanks for filing this. I have added it to the list in https://github.com/golang/go/issues/24661. We are tracking module support of all tools there. There are some exceptions like godoc/gddo which have their own issue. But I don't think this needs to be tracked separately.

Please correct me if you think this is a mistake.

**Comment by Halimao** [comment]
> Thanks for filing this. I have added it to the list in #24661. We are tracking module support of all tools there. There are some exceptions like godoc/gddo which have their own issue. But I don't think this needs to be tracked separately.
> 
> Please correct me if you think this is a mistake.

hello, is go modules supported now?
