### ISSUE TITLE
x/build, runtime: linux-s390x-ibm regression in TestGdbPython on release-branch.go1.12

### ISSUE THREAD

**Issue by bcmills** [golang/go#33757]
`TestGdbPython` (in the `runtime` package) has been failing on the `linux-s390x-ibm` builder on `release-branch.go1.12` starting at [CL 181658](https://golang.org/cl/181658) (https://build.golang.org/log/c9c6830fd79bda38aa4a7c5f1594aafccda247cb).

The failure mode appears to be unrelated to that change, so I'm guessing that something about the builder configuration may have changed..?

CC @mundaym @aclements

**Comment by mundaym** [comment]
I suspect that the build started failing when I installed GDB on the builder following the merge of https://golang.org/cl/169857 into master. We could cherry-pick that fix I guess. Or disable the test somehow.

**Comment by bcmills** [comment]
> We could cherry-pick that fix I guess. Or disable the test somehow.

Either of those options seems reasonable to me, assuming the merge is clean.

CC @cherrymui

**Comment by katiehockman** [comment]
This is a fix that addresses an external change that would otherwise make the release unstable with failing tests, so approved the cherry pick. I'll make the CL now.
