### ISSUE TITLE
access: deklerk@ approvers + may-start-trybots

### ISSUE THREAD

**Issue by jadekler** [golang/go#33763]
See https://golang.org/wiki/GerritAccess

(for things like x/tools/digraph, x/exp/cmd/modgraphviz, blog/ etc)

(per @dmitshur suggestion)

**Comment by dmitshur** [comment]
Hi Jean,

Thank you for contributing to the Go project and helping out so much in the world of modules! I've discussed this request with the team (/cc @golang/osp-team), and we agreed to grant you access. I've added you to the `may-start-trybots` and `approvers` groups now.

Please be familiar with the rules for voting and submitting changes as described at https://golang.org/wiki/GerritAccess#approver-access-approvers. If you're unsure or have any questions, please don't hesitate to ask us.

Additionally, as described at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a trybot run.

Thank you again for contributing, your help is greatly appreciated!

**Comment by jadekler** [comment]
Woohoo, thanks!
