### ISSUE TITLE
go1.13rc1: all.bash skips testcarchive and testcshared

### ISSUE THREAD

**Issue by ulikunitz** [golang/go#33766]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13rc1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

No. The issue is related to the build of go1.13rc1.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kunitz/.cache/go-build"
GOENV="/home/kunitz/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/kunitz/work"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/kunitz/go1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/kunitz/go1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build036334565=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
$ cd ~/go1.13/src
$ git checkout go1.13rc1
$ ./clean.bash
$ ./all.bash
</pre>

### What did you expect to see?

<pre>
##### ../misc/cgo/testcarchive
PASS

##### ../misc/cgo/testcshared
PASS
</pre>

I get this output building go1.12.

### What did you see instead?

<pre>
##### ../misc/cgo/testcarchive
SKIP - short mode and $GO_BUILDER_NAME not set

##### ../misc/cgo/testcshared
SKIP - short mode and $GO_BUILDER_NAME not set
</pre>

**Comment by ianlancetaylor** [comment]
This is expected.  See https://golang.org/cl/177417, for #26473.  You can still run `go test` yourself in those directories to run the tests.

**Comment by ulikunitz** [comment]
Thank you for the explanation. Why are the tests not completely removed from all.bash?

**Comment by ianlancetaylor** [comment]
Because they are run on the Go builders used to produce https://build.golang.org/.  That helps ensure that they continue to pass--even if people don't notice when running all.bash themselves, the builders will report a problem and someone will notice.
