### ISSUE TITLE
x/tools/cmd/guru: not working on files outside gopath

### ISSUE THREAD

**Issue by fastfading** [golang/go#33773]
### What version of Go are you using (`go version`)?
go version go1.12.7 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xxxx/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xxxx/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.7/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g4/b17y14y9753bsx3_f_03ggh80000gn/T/go-build017275408=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?
use go tool guru , this tool only work in gopath. 
but for many case the go project is not under gopath
~/go/bin/guru referrers <go project outside gopath>/file.go:#1234

### What did you expect to see?
guru show all the reference 

### What did you see instead?
if file.go:#1234   is  a reference place
guru: no object for identifier: *ast.CallExpr
else if is  a definition place
guru only show this definition

**Comment by bcmills** [comment]
Modules are the general solution for developing outside of GOPATH, and there is no current plan to convert `guru` to work with modules.

(See https://github.com/golang/go/issues/31720#issuecomment-495722369.)

**Comment by fastfading** [comment]
pls give us a workaround ,
I try to ln -s  mypackage  gopath/src/mypackage
it did not work.
pls add least let guru support this softlink

Bryan C. Mills <notifications@github.com> 于2019年8月22日周四 上午11:47写道：

**Comment by fastfading** [comment]
pls give us a workaround ,
I try to ln -s  mypackage  gopath/src/mypackage 
it did not work. 
pls add least let guru support this softlink

**Comment by bogdando** [comment]
I created a script that attempts symlinking https://gist.github.com/bogdando/d15cf014f3171a9ae06b83cd9c9b1c26

works for me, more or less...

**Comment by bogdando** [comment]
reworked the workaround (symlinking script)

https://github.com/bogdando/gogetguru a script that workarounds that issue. This time it works much better, I hope.
