### ISSUE TITLE
godoc: remove comments from index associated with anonymous function parameter

### ISSUE THREAD

**Issue by gertcuykens** [golang/go#33777]
Example:
```
func Reporter(r interface {
	// PushStep is called when a tree-traversal operation is performed.
	// The PathStep itself is only valid until the step is popped.
	// The PathStep.Values are valid for the duration of the entire traversal
	// and must not be mutated.
	//
	// Equal always calls PushStep at the start to provide an operation-less
	// PathStep used to report the root values.
        ....
```

https://godoc.org/github.com/google/go-cmp/cmp

![image](https://user-images.githubusercontent.com/863731/63477642-5b6c5980-c486-11e9-8b60-5bf1c191d1ed.png)

Remove comments from the index view (see screenshot)

**Comment by agnivade** [comment]
This is a gddo issue. Unless you see this in godoc also, please file the issue in the [gddo](https://github.com/golang/gddo) repo.

**Comment by gertcuykens** [comment]
Ok thx found duplicated https://github.com/golang/gddo/issues/633 closing this one
