### ISSUE TITLE
gollvm: build failures with 'llvm::make_unique' and SectionRef::getName

### ISSUE THREAD

**Issue by shawn-xdji** [golang/go#33782]
### What version of Go are you using (`go version`)?

<pre>
$ go version
Latest gollvm on arm/x86
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Sync llvm, gollvm and gofrontend to latest version and build.

### What did you expect to see?
Build pass.

### What did you see instead?
A few build errors like the following one.

/home/xiaji01/src/gollvm/tools/gollvm/driver/GollvmOptions.cpp:43:23: error: ‘make_unique’ is not a member of ‘llvm’; did you mean ‘std::make_unique’?
   43 |   auto Result = llvm::make_unique<DriverOptTable>();

They are caused by the recent llvm changes:

commit 114087caa6f95b526861c3af94b3093d9444c57b
[llvm] Migrate llvm::make_unique to std::make_unique

commit 1bfa43df5886a8c51442dd457b3a89c59ce02b46
Recommit r368812 "[llvm/Object] - Convert SectionRef::getName() to return Expected<>"

commit 0d8949846a525ca1920771aeea88d1dcaa1779f7
[llvm/Object] - Convert SectionRef::getName() to return Expected<>

**Comment by shawn-xdji** [comment]
Yes, it would be good if we pin to stable version of llvm, turns out there are too many small changes in llvm every day.

**Comment by thanm** [comment]
I created a CL yesterday for this -- I'll go ahead and submit it.
