### ISSUE TITLE
math/big: Rat.Denom has side effects

### ISSUE THREAD

**Issue by ericlagergren** [golang/go#33792]
From here: https://github.com/ericlagergren/decimal/issues/138

My package divides `(*Rat).Num` by `(*Rat).Denom` to produce a decimal number. It turns out that `(*Rat).Denom` lazily sets its denominator, meaning it cannot be used concurrently.

Since the receiver is `x` not `z`, I assumed that the method simply read the denominator.

The receiver name should be updated to indicate side effects and/or the documentation for `big.Rat` should mention this side effect. I assume that the 7 years this has spent in the tree is too long to be reverted 😄. And, at any rate, not materializing the denominator can save allocations for whole numbers, which is a good thing.

I can send a CL if you want.

**Comment by bcmills** [comment]
CC @griesemer

**Comment by griesemer** [comment]
Reopening due to #34919 
Should Denom() be allowed to have side-effects in the first place?
If we change this, we may break existing programs. See also #3521 and the respective test cases.
