### ISSUE TITLE
cmd/link: external linking on darwin strips symbols starting with "l"

### ISSUE THREAD

**Issue by jeremyfaller** [golang/go#33808]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13 locally built
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/jfaller/go/bin"
GOCACHE="/Users/jfaller/Library/Caches/go-build"
GOENV="/Users/jfaller/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jfaller/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/jfaller/src/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/jfaller/src/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kt/9h7gfgy955lgbm_cys108l2c002pwh/T/go-build423342355=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

<pre>
[16:12]~/go/src/hello $ cat hello.go
package main

import "log"

func main() {
	log.Fatalf("See we called a function that started with l")
}
[16:12]~/go/src/hello $ go build .
[16:12]~/go/src/hello $ nm hello | grep Fatal
000000000109c170 t log.Fatalf
[16:12]~/go/src/hello $ go build -ldflags="-linkmode external"
[16:12]~/go/src/hello $ nm hello | grep Fatal
[16:13]~/go/src/hello $ 
</pre>

### What did you expect to see?

I expected that log.Fatal would still be in my executable.

### What did you see instead?

Symbols starting with an l have been stripped.

Oringally reported [HERE](https://github.com/go-delve/delve/issues/1635)

**Comment by jeremyfaller** [comment]
CC @cherrymui @aarzilli @diffmike

**Comment by cherrymui** [comment]
I think we already add leading _ to symbol names for plugins, for exactly the reason mentioned in https://github.com/go-delve/delve/issues/1635#issuecomment-524443933 : dlsym needs it. We may want to do this for other build modes as well.

**Comment by aarzilli** [comment]
Given that the change was reverted this issue should be reopened, I think.

**Comment by jeremyfaller** [comment]
Totally right. I'm on vacation till Monday, but will fix whatever caused the trybots unhappiness first thing.

**Comment by jeremyfaller** [comment]
Apparently external linking hasn't ever worked on darwin_386. I'll exclude that in the test, and resubmit.
