### ISSUE TITLE
x/net/http2: window updates on randomWriteScheduler after stream closed cause memory leaks

### ISSUE THREAD

**Issue by jared2501** [golang/go#33812]
### What version of Go are you using (`go version`)?

<pre>
go version go1.12.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do? What did you expect to see? What did you see instead?

I've been tracing down some issues in a creeping response times in a gRPC server that uses HTTP/2.

![image](https://user-images.githubusercontent.com/2866738/63632251-9043f200-c5e7-11e9-9d9e-7f166b97b61b.png)

The big jump downwards is when I restart the server (purple=median, blue=p95, yellow=max response times).

After much poking and logging, I've traced it down to the entries in the `randomWriteScheduler.sq` growing, and not being garbage collected. What I believe is happening is that RST_STREAM frames are being sent on closed streams, which causes the `randomWriteScheduler` to allocate new entries in the `randomWriteScheduler.sq` map (see code [here](https://github.com/golang/net/blob/master/http2/writesched_random.go#L53)). The RST_STREAM frames will get queued and emitted by `WriteScheduler.Pop()` eventually, however since the stream has already been closed, they will never get deleted from the `randomWriteScheduler.sq` map since `randomWriteScheduler.CloseStream` will never be called, which causes this map to grow unbounded.

The `priorityWriteScheduler` handles this case by not allocating new nodes, but instead attaching RST_STREAM frames for closed streams to it's root node (in fact, it has a nice comment explaining this logic [here](https://github.com/golang/net/blob/master/http2/writesched_priority.go#L391)).

I can look at providing a minimum repro of the issue if required, but it's a bit tricky to isolate since it requires delay in the stream to reproduce. Hopefully, the difference in behaviour between the `randomWriteScheduler` and the `priorityWriteScheduler`, and reading the code, is enough to identify & fix the issue here.

**Comment by jared2501** [comment]
I've been running gRPC server through a full traffic cycle with the `priorityWriteScheduler` enabled and it seems to have fixed the issue!

![image](https://user-images.githubusercontent.com/2866738/63657885-0b79e500-c75b-11e9-99ce-e463449cb97e.png)

Here's a suggested fix to the leak:

```
diff --git a/http2/writesched_random.go b/http2/writesched_random.go
index 36d7919..4c34683 100644
--- a/http2/writesched_random.go
+++ b/http2/writesched_random.go
@@ -51,8 +51,14 @@ func (ws *randomWriteScheduler) Push(wr FrameWriteRequest) {
        }
        q, ok := ws.sq[id]
        if !ok {
-               q = ws.queuePool.get()
-               ws.sq[id] = q
+               // id is an idle or closed stream. wr should not be a HEADERS or
+               // DATA frame. However, wr can be a RST_STREAM. In this case, we
+               // push wr onto the zero write queue, rather than creating a new
+               // write queue, since RST_STREAM is tiny.
+               if wr.DataSize() > 0 {
+                       panic("add DATA on non-open stream")
+               }
+               q = &ws.zero
        }
        q.push(wr)
 }
```

**Comment by jared2501** [comment]
Quick ping @bradfitz  - any chance of landing this in 1.14?

**Comment by jared2501** [comment]
Sorry to harp on this issue, but quick ping on this @bradfitz (now that you're back from leave - congrats btw!)

**Comment by bradfitz** [comment]
@jared2501, thanks for the great bug report & diagnosis! 

@gopherbot, please backport to Go 1.13.

/cc @tombergan

**Comment by bradfitz** [comment]
@jared2501, can you try out https://golang.org/cl/198462 and report back about whether it helps or not? And any performance numbers if that's easy?

Also, code reviews welcome from anybody.

**Comment by jared2501** [comment]
@bradfitz change looks like a reasonable fix to me. Thanks! Will try and find a chance to run it some time next week. 

I'll see what I can do re perf numbers, but I suspect we don't have good enough instrumentation to capture any difference here. Will include them if there is :)
