### ISSUE TITLE
net/mail: ReadMessage fails on header-only messages

### ISSUE THREAD

**Issue by pam4** [golang/go#33823]
Sorry to open this again (see #15632, #24256).
Postfix just landed one such message on my Maildir mailbox, and my Go tools choked on it.
(I receive messages one per file, in raw format, with LF line endings from Postfix.)

The message has no body and only one LF at the end. The `X-Mailer` header field says `MIME-tools 5.503 (Entity 5.501)`. It was sent by a person.

You can see it [here](https://play.golang.org/p/loX0CGRLHU3) (slightly altered).
Isn't it standard compliant?
According to [RFC 5322](https://tools.ietf.org/html/rfc5322#section-3.5) it seems that the body is optional and the empty line is required only if the body is present:
```
message = (fields / obs-fields)
          [CRLF body]
```
And such `message` is what `mail.ReadMessage` should be able to parse.

Postfix *can* send header-only messages, and it preserves the absence of the empty line.
To reproduce it, setup Postfix to deliver to a [Maildir](https://en.wikipedia.org/wiki/Maildir) mailbox, then send yourself a header-only message using the `sendmail` command.
(If you use an [mbox](https://en.wikipedia.org/wiki/Mbox) mailbox you get multiple messages per file, and an empty line is added as a separator, in addition to the "From_ line", but an mbox is *not* a message.)

I agree that header-only messages are rare and not very useful and this is a minor issue, but not completely worthless.

The simplest solution would be to filter out `EOF` in `mail.ReadMessage` [here](https://github.com/golang/go/blob/c4ca60313ef7fd0b9d2c223889caeb20147309ac/src/net/mail/message.go#L57). But that would make it succeed even in case of incomplete last line (possibly truncated message).

**Comment by bcmills** [comment]
CC @bradfitz (on leave)

**Comment by emersion** [comment]
Can confirm header-only messages are valid messages. (For reference, here's a similar patch for go-message: https://lists.sr.ht/~emersion/public-inbox/patches/9396)

**Comment by pam4** [comment]
Fixing `textproto` seems a little more complex than just turning `io.EOF` into `nil` [here](https://github.com/golang/go/blob/33e98326a25d54cef19e94ca73c45eaed8847f56/src/net/textproto/reader.go#L508).
That would make it succeed even if the last line doesn't end in newline (which is not standard compliant).

(Unfortunately `readContinuedLineSlice` behaves exactly the same for either `"x"EOF` or `"x\n"EOF`.)

Anyway, `io.EOF` doesn't make much sense for `mail.ReadMessage`; it should be turned into `io.ErrUnexpectedEOF` (or `nil` if the last line is complete).

**Comment by kayrus** [comment]
I also experience this issue. See also some related issue in https://github.com/golang/go/issues/53858
