### ISSUE TITLE
cmd/compile: prefer AND instead of SHR+SHL

### ISSUE THREAD

**Issue by martisch** [golang/go#33826]
In [cl/19485](https://golang.org/cl/19485/) we added a generic SSA rule to replace an AND with specific constants by two SHIFT instructions. 

While this optimization does avoid a load of the constant to be ANDed into an extra register and has a shorter encoding on amd64 it does use two data dependent instructions. There was already some discussion on the CL after accidental early submission that micro benchmarks do not show using two shifts to be faster. Some seem to show it can be slower e.g. `x &= 1 << 63`. I benchmarked math.Copysign and it showed the same throughput using either variant. LLVM and GCC do not seem to replace AND with SHIFTs on amd64 either and some platforms like arm64 in the go gc compiler even reverse this rewrite.

https://go.googlesource.com/go/+/06f709a04acc6d5ba0ba181129e9ee93ed20f311/src/cmd/compile/internal/ssa/gen/ARM64.rules#1866

There has also been some unwanted interaction with other optimizations rules e.g. #32781.

The initial added rules from [cl/19485](https://golang.org/cl/19485/) operated on And64 and And32. The And32 case was already removed in [cl/20410 ](https://golang.org/cl/20410). 

Removing the And64 case too can make binaries slightly larger but in common cases where there is no register pressure should be as fast or faster as two SHIFTs on modern amd64 CPUs and should create less interference with other SSA rules that need not consider the additional case of a mask using AND having been rewritten to SHIFTs.

I intend to send CLs for evaluation and submission to remove the generic rule to rewrite AND into a pair of SHIFTs for go1.14 and follow up with some CLs that avoid regressing on interaction with other rules that are based on optimizing SHIFTs instead of ANDs. For example the AND instruction in `(u64>>32)&0xFFFFFFFF` should still be optimized away by SSA.

This issue is to document the related CLs and discuss this (de)optimization and whether any go gc supported 64bit platforms should keep rewriting some ANDs to two SHIFTs.

/cc @klauspost @cherrymui @khr @dr2chase @laboger @mundaym

**Comment by klauspost** [comment]
Looking at instruction timing it should be pretty much the same. 

I am not saying that this is a bad change, just that I don't think this benchmark is accurate if it is emitting what you write.

```
func BenchmarkAndHighBits(b *testing.B) {
	x := uint(0)
	for i := 0; i < b.N; i++ {
		x &= 1 << 63
	}
	GlobalU = x
}
```
Is  `MOVQ $0x8000000000000000, RAX` actually inside the loop? And wouldn't it emit `ANDQ  $0x8000000000000000, REG`?

On Ivy Bridge (your CPU) and pretty much all other CPUs, the instructions involved are all with a 1 cycle latency. Since your benchmark is serial, it should pretty much be the same assuming it is emitting MOVQ+ANDQ. If it is only ANDQ, it should be 2x faster (excluding the loop overhead).

It could also be that Ive Bridge is able to do some magic and can ignore the MOVQ.

Either way; with the `AND`, the compiler will be able to do some optimizations. A clever compiler could even move the constant loading outside the loop, as mentioned above.

**Comment by martisch** [comment]
> Looking at instruction timing it should be pretty much the same.

I would agree if viewed standalone. If there is surrounding code like in the benchmark loop I would expect the MOV being able to be issued in parallel ahead with some earlier instruction (unless the CPU is saturated with 4 retires per cycle already). The two shifts together always need at least 2 cycles after their input is ready from a previous loop iteration.

> Is `MOVQ $0x8000000000000000, RAX` actually inside the loop?
I have not rechecked but I think that is what I saw. That a MOV is needed should only be clear very late - in the arch specific SSA (see why below). I do not think there is loop hoisting pass run after that stage.

> And wouldn't it emit `ANDQ $0x8000000000000000, REG`?
AND does not support 64bit immediates https://www.felixcloutier.com/x86/and .

**Comment by klauspost** [comment]
Yeah, the CPU is doing magic.

A simple test, pure assembler:

```
TEXT ·testAnd(SB), NOSPLIT, $0
	MOVQ $65535, CX
	XORQ AX, AX

loop_and:
	MOVQ $0x8000000000000000, BX
	ANDQ BX, AX
	DECQ CX
	JNZ  loop_and
	RET

TEXT ·testShift(SB), NOSPLIT, $0
	MOVQ $65535, CX
	XORQ AX, AX

loop_shift:
	SHRQ $63, AX
	SHLQ $63, AX
	DECQ CX
	JNZ  loop_shift
	RET
```

Using `AND` is ~2x as fast on my Ryzen 3600. Moving the MOVQ outside the loop makes absolutely no difference, which indicates the magic :)

**Comment by martisch** [comment]
The first attempt broke codegen tests in arm64 (bfxil) and s390x (abs and copysign).
https://build.golang.org/log/a47a1c98bac2aa509d570d6bf583609857b1be5a
https://build.golang.org/log/6456da8a84cc82e7407981287f211caaab41c7eb

Will make sure to run codegen tests for all platforms for the new version of the CL.

For a new version of the CL I added abs and copysign rules that need detect the new AND variant, still working on the arm64 bitfield adjustment.

**Comment by randall77** [comment]
Anything else need to be done here?

**Comment by martisch** [comment]
The feature is in at the 3rd try and AFAIK did not cause any new breakages since then.

There is some cleanups that can be done. e.g. adding codegen tests that the old shift based rules are exercised and tested or just remove the old rules. However I wont likely get to that and test them across the different architectures due to other feature CLs before go1.14. Therefore closing this issue as the desired generate of code itself is in for go1.14.
