### ISSUE TITLE
cmd/go: 'go build' error from 'git ls-remote' when downloading from private repo

### ISSUE THREAD

**Issue by lihaic** [golang/go#33836]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13rc1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lhc/.cache/go-build"
GOENV="/home/lhc/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY="*.bmi"
GONOSUMDB="*.bmi"
GOOS="linux"
GOPATH="/home/lhc/go"
GOPRIVATE="*.bmi"
GOPROXY="https://goproxy.io,direct"
GOROOT="/home/lhc/sdk/go1.13rc1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/lhc/sdk/go1.13rc1/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/lhc/gitlab.bmi/tss/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build750408901=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I set two enviroment variable first.
$ go1.13rc1 env -w GOPROXY=https://goproxy.io,direct
$ go1.13rc1 env -w GOPRIVATE=*gitlab.bmi
Then i tried to build my project.
$ go1.13rc1 build -v
And then it failed, because some packages my project rely on is in a private repo.
The error message is:
<pre>
# cd .; git ls-remote -- https://gitlab.bmi/aaa/logv
usage: git ls-remote [--heads] [--tags]  [--upload-pack=<exec>]
                     [-q | --quiet] [--exit-code] [--get-url] [<repository> [<refs>...]]
# cd .; git ls-remote -- git+ssh://gitlab.bmi/aaa/logv
usage: git ls-remote [--heads] [--tags]  [--upload-pack=<exec>]
                     [-q | --quiet] [--exit-code] [--get-url] [<repository> [<refs>...]]
# cd .; git ls-remote -- ssh://gitlab.bmi/aaa/logv
usage: git ls-remote [--heads] [--tags]  [--upload-pack=<exec>]
                     [-q | --quiet] [--exit-code] [--get-url] [<repository> [<refs>...]]
go: gitlab.bmi/aaa/logv.git@v1.2.2: reading gitlab.bmi/aaa/logv.git/go.mod at revision v1.2.2: unknown revision v1.2.2
</pre>
I thought this git ls-remote is trying to get tag info, is this supposed to be git ls-remote --tags <repository> or git ls remote <repository>

Then i modified the source code /home/lhc/sdk/go1.13rc1/src/cmd/go/internal/get/vcs.go line186
pingCmd:    "ls-remote -- {scheme}://{repo}", ---> to pingCmd:    "ls-remote {scheme}://{repo}",

And then i tried to run go1.13rc1 build -v, and it succeed.

### What did you expect to see?

I hope after i set GOPROXY and GOPRIVATE, i could download package from both public repo  and  private repo.

### What did you see instead?
But i can't run go build correctly.

Question is that is that line wrong? 

Thank you for your help.

**Comment by aofei** [comment]
This seems to work as designed. What you need to know is that `go` isn't smart enough to handle VCS authentications on its own.

See: [Why does "go get" use HTTPS when cloning a repository?](https://golang.org/doc/faq#git_https)

**Comment by lihaic** [comment]
<pre>
$git version
git version 2.7.4
</pre>

Try running those git ls-remote command in an empty directory.
<pre>
$mkdir emptydir; cd emptydir
$git ls-remote -- https://gitlab.bmi/aaa/logv
usage: git ls-remote [--heads] [--tags]  [--upload-pack=]
                     [-q | --quiet] [--exit-code] [--get-url] [ [...]]
$git ls-remote -- git+ssh://gitlab.bmi/aaa/logv
usage: git ls-remote [--heads] [--tags]  [--upload-pack=]
                     [-q | --quiet] [--exit-code] [--get-url] [ [...]]
#git ls-remote -- ssh://gitlab.bmi/aaa/logv
usage: git ls-remote [--heads] [--tags]  [--upload-pack=]
                     [-q | --quiet] [--exit-code] [--get-url] [ [...]]
</pre>
Running git ls-remote in an empty directory produces the same result.
<pre>
$git ls-remote https://gitlab.bmi/aaa/logv
46c721ee6bab43c94dd8b3f3dc8a357cb4884627	HEAD
46c721ee6bab43c94dd8b3f3dc8a357cb4884627	refs/heads/master
1dccbdb4d84588a52a147e9f0e98ce222ba7027a	refs/heads/v1
2741972f4356fd428439411eba51e19639fc4df1	refs/tags/v1.0.0
46c721ee6bab43c94dd8b3f3dc8a357cb4884627	refs/tags/v1.1.0
2c05092bd904db3c5d0f3dfa81059bb0808c317e   refs/tags/v1.2.0
1aeae1413f640f643de9d864f09b36c85d5409ca	refs/tags/v1.2.1
1dccbdb4d84588a52a147e9f0e98ce222ba7027a	refs/tags/v1.2.2
$git ls-remote --tags https://gitlab.bmi/aaa/logv
2741972f4356fd428439411eba51e19639fc4df1	refs/tags/v1.0.0
46c721ee6bab43c94dd8b3f3dc8a357cb4884627	refs/tags/v1.1.0
2c05092bd904db3c5d0f3dfa81059bb0808c317e   refs/tags/v1.2.0
1aeae1413f640f643de9d864f09b36c85d5409ca	refs/tags/v1.2.1
1dccbdb4d84588a52a147e9f0e98ce222ba7027a	refs/tags/v1.2.2
</pre>
But running git ls-remote without the -- or with --tags get all tag info.

By the way, i order to use private repo, i added ssh git config like below.
<pre>
$ cat ~/.gitconfig
[user]
	name = lhc
	email = lhcgotobed@163.com
[url "ssh://git@gitlab.bmi/"]
	insteadOf = https://gitlab.bmi/
</pre>
I think this sholud only avoid go tools using https since my private repo don't have https.
@bcmills Appreciate all you help, thanks.

**Comment by lihaic** [comment]
I am currently using ubuntu 16.04, default git version is 2.7.4.
<pre>
$sudo add-apt-repository -y ppa:git-core/ppa
$sudo apt-get update
$sudo apt-get install git -y
$git version
git version 2.23.0
</pre>
I did this to upgrade git to v2.23.0, and then git ls-remote -- worked! And with the origin go1.13rc1 binary, go build works fine with my private repo.
So seems like this problem related to git version.
