### ISSUE TITLE
x/website: Documents misaligned in menu for release notes

### ISSUE THREAD

**Issue by peterhellberg** [golang/go#33834]
The **Documents** menu option is misaligned in the Go release notes.

<img width="699" alt="Go 1.12 Release Notes" src="https://user-images.githubusercontent.com/565124/63676000-5989f980-c7ea-11e9-9b04-aec798cc9386.png">

The alignment is correct on other documentation pages.

<img width="711" alt="Go Documentation" src="https://user-images.githubusercontent.com/565124/63676213-bab1cd00-c7ea-11e9-9d3a-0badfc0b9699.png">

### What did you do?

Go to the release notes for Go, for example [go1.11](https://golang.org/doc/go1.11), [go1.12](https://golang.org/doc/go1.12) or [go1.13 (tip)](https://tip.golang.org/doc/go1.13)

### What did you expect to see?

**Documents** aligned with the other menu options.

### What did you see instead?

**Documents** being positioned higher up than the rest of the menu options.

### Browsers tested

The following browsers were tested under macOS High Sierra.

 - Firefox Developer Edition
 - Safari
 - Google Chrome

**Comment by ALTree** [comment]
Thanks for the report. This is #33718. Closing here as a dup.
