### ISSUE TITLE
ticker timer issue.

### ISSUE THREAD

**Issue by kakatkar** [golang/go#33831]
### What version of Go are you using (`go version`)?

<pre>
go version go1.12.9 windows/amd64
</pre>

### Does this issue reproduce with the latest release? 
Yes

### What operating system and processor architecture are you using (`go env`)?
linux and windows
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

package main
import "time"
import "fmt"
func main() {
    ticker := time.NewTicker(500 * time.Millisecond)
    go func() {
        for t := range ticker.C {
            fmt.Println("Tick at", t)
        }
        fmt.Println("Ticker done")
    }()
    time.Sleep(1600 * time.Millisecond)
    ticker.Stop()
    fmt.Println("Ticker stopped")
    time.Sleep(1600 * time.Millisecond)
}

### What did you expect to see?

since stop will complete timer and for loop ends, 
Expected "Ticker done" printed after  "Ticker stopped"

### What did you see instead?
After "Ticker stopped",   nothing gets printed.

**Comment by ianlancetaylor** [comment]
The `time.Ticker.Stop` method does not close the channel, so the range loop does not stop.  This is working as documented and intended (https://golang.org/pkg/time/#Ticker.Stop).
