### ISSUE TITLE
I have bad opinion about GO (especially coz GUI... QT, GTK, OPENGL .etc)

### ISSUE THREAD

**Issue by ManPython** [golang/go#33845]
I wait long time with decision to interes myself with Go Lang as new tech.
When I want start do something more than simple examples I still meet difrent problems.
I was in idea to replace python, c++, c# by GO ..it's really hard. After 3years with observation this all I don't see any progress here.

First.. GUI.. if no support for GUI then 70% of usage of GO as future lang is out.
Here is how this looks..
**QT**
https://stackoverflow.com/questions/57659704/running-simple-qt-gui-application-in-go
https://github.com/therecipe/qt/issues/931
https://github.com/therecipe/qt/issues/940
https://github.com/kitech/qt.go/issues/43 

**QT QML** - ok, but it's speciall dedication to huge work with own GUI

**GTK**
..there is more problems than case of QT

**CommonControls** - tihs lib have to big limitations to

**OPENGL**
..working but hard in advanced usage
https://github.com/go-gl-legacy/glu/issues/30
https://github.com/go-gl/example/issues/67

Soo.. whatever touches GO have problems.. 
I understand that is opensource, but GO team must decide that GO is "toy" or "tool".. really..
https://www.youtube.com/watch?v=yL704C1PI4o Top 15 Programming Languages by Popularity (2004-2019)

Nobody should work with this if simple examples not working and have problmes that can be easy solved. Programer should not be like a devops (specialist from wide range of tools, laguages, etc.).. in other way is bether to back to ASM.. 

Please start to cordinate this in some rational direction or close this (seriously). The server side solutions by GO as worker or for some network computations, concurency, etc. is not enough to learn GO and join to this community. Opinion that GO is for something like this show that GO is some of model realted to https://en.wikipedia.org/wiki/Bait-and-switch  ..devils job
Must be some miles steps of support, ussage, practical area where this tool is helpful or can be. 
If I watching this.. it's looks like "huge interface for everything" for closed group as observed. Near like s# as fast env. Dont'w want discuss here with all of this.. just comment for decission ppls and maybe other users to orientate about facts. We can't fight with "machines" as compilators, etc.. it's idle work and occupation (it's bether to do nothing than waste time).

@google-admin @golang

**Comment by ALTree** [comment]
Hi,

the github issue tracker is only used for concrete, actionable bugs. This looks more like a rant (written in a rather inflammatory language), so I think it would be better as a medium blog post.

Closing here.
