### ISSUE TITLE
x/tools/gopls: support workspace/Symbol request

### ISSUE THREAD

**Issue by stamblerre** [golang/go#33844]
Forked from https://github.com/microsoft/vscode-go/issues/954.

**Comment by moonnoon** [comment]
[helm-lsp](https://github.com/emacs-lsp/helm-lsp) needs it.

**Comment by myitcv** [comment]
Just to confirm, `workspace/Symbol` would effectively allow us to show exported package symbols, correct? Or is the plan to have `textDocument/documentSymbol` satisfy that question?

**Comment by stamblerre** [comment]
`workspace/Symbol` is used to do a search of the workspace on a particular symbol, whereas `textDocument/documentSymbol` shows the list of symbols in the a given file.

**Comment by myitcv** [comment]
So is there nothing that corresponds to the package level?

**Comment by stamblerre** [comment]
Not that I am aware of - how would that be displayed by the editor?

**Comment by stamblerre** [comment]
That does sound like a good feature. I encourage you to open up an issue with [LSP](https://github.com/microsoft/vscode-languageserver-node) :)

**Comment by daisuzu** [comment]
I sent a change because I'd like to use `workspace/symbol` with Vim.
This can be used as an alternative to ctags.

**Comment by daisuzu** [comment]
@stamblerre 
Basic workspace/symbol feature is working now.
However, the following is not implemented, is there anything required for this issue?

- [deprecated](https://github.com/golang/tools/blob/5916a50871fbb77650a14d484c89ca39f9487118/internal/lsp/protocol/tsprotocol.go#L2924-L2927) field of SymbolInformation
- [containerName](https://github.com/golang/tools/blob/5916a50871fbb77650a14d484c89ca39f9487118/internal/lsp/protocol/tsprotocol.go#L2940-L2946) field of SymbolInformation
- [WorkspaceSymbolClientCapabilities](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#workspace_symbol)
    - But, I am not sure how this is used.
- [Work Done Progress](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#workDoneProgress)
- [Partial Result Progress](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#partialResults)

If not required, I'd like to implement CLI support for workspace/symbol as the last CL in this issue.

**Comment by stamblerre** [comment]
Thanks for your work on this, @daisuzu! The features you mentioned above don't need to be added.

> If not required, I'd like to implement CLI support for workspace/symbol as the last CL in this issue.

That would be great - thanks!

**Comment by stamblerre** [comment]
Closing this issue as this work is complete. The workspace symbols CLI feature can be associated with https://github.com/golang/go/issues/32875. Thanks for working on this, @daisuzu!

**Comment by daisuzu** [comment]
Sure! Thank you for reviewing CLs.
