### ISSUE TITLE
x/mobile: Cannot get objective api(function type) on ios

### ISSUE THREAD

**Issue by CanRui-Wu** [golang/go#33858]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> </summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wucanrui/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/wucanrui/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/wucanrui/Desktop/develop/SAG/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0_/j6m36l9s0psg9xm5ggt2_b680000gp/T/go-build184268174=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I first import "ObjC/Foundation".
It is easy to get class in "Foundation" like "NSDate". 
However, I cannot find the function "NSHomeDirectory"  in "Foundation".

### What did you expect to see?
Successfully use objective api(function type). 

### What did you see instead?
 "NSHomeDirectory" cannot find in "Foundation".

**Comment by julieqiu** [comment]
@CanRui-Wu Could you provide an example of the code that produced the error, preferably as a Go playground link (https://play.golang.org/)? Additionally, could you provide what version of go you are using?
