### ISSUE TITLE
x/tools/cmd/godoc: directory listings aren't updated

### ISSUE THREAD

**Issue by gopherbot** [golang/go#3386]
by **trolleriprofessorn**:

<pre>The current godoc server (baeb068aac25+ tip) generates directory listings on startup and
don't update them on reload. This is inconvenient when you use the server to browse the
documentation of your project during development.

If it's not possible to address this before the Go 1 release, I suggest making the
-timestamps flag true by default. This will help new users discover the behavior and
experienced users can easily turn timestamps off.</pre>

**Comment by agnivade** [comment]
This was decided in #7524 that it is enough to be able to tune the index interval to have enough control to change the update frequency. Mentioning here for reference - 

> @andybons-  Another alternative--though I'm not saying it's a good one--is to allow a flag to specify how often to index or to disable reindexing entirely. It's unclear what's better here. Whether to add yet another flag or increase the complexity of the code by adding inotify watches.

> @agnivade- It is already behind a flag called "index", which is false by default. And the index_interval is also behind a flag (default of 5 mins).

> @andybons- Then let’s close this. If it comes up again we can revisit.

Hence, closing this.
