### ISSUE TITLE
cmd/go: require directive fails verifying local modules

### ISSUE THREAD

**Issue by agalal** [golang/go#33873]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13rc1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/abdullah/.cache/go-build"
GOENV="/home/abdullah/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/abdullah/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/abdullah/goroots/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/abdullah/goroots/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/abdullah/project/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build901671745=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
I run `go mod tidy` with the following `go.mod` file:
```
module bar

go 1.13

require (
	local.git.company.intranet/foo v0.0.0-20190827165402-2d7dc3de0e5e
)
```

### What did you expect to see?
I expected `go mod tidy` to succeed or exit with `0` !

### What did you see instead?
It fails with the following output:
```
verifying local.git.company.intranet/foo@v0.0.0-20190827165402-2d7dc3de0e5e/go.mod: local.git.company.intranet/foo@v0.0.0-20190827165402-2d7dc3de0e5e/go.mod: reading https://sum.golang.org/lookup/local.git.company.intranet/foo@v0.0.0-20190827165402-2d7dc3de0e5e: 410 Gone
```
```
$ echo $?
1
```

This doesn't happen with `go1.12`. Seems to be related to the `go1.13rc1` update adding a check against some sum database.

**Comment by tmthrgd** [comment]
You’ll need to set the `GOPRIVATE` environment variable: https://tip.golang.org/cmd/go/#hdr-Module_configuration_for_non_public_modules.

**Comment by agalal** [comment]
> You’ll need to set the `GOPRIVATE` environment variable: https://tip.golang.org/cmd/go/#hdr-Module_configuration_for_non_public_modules.

Thanks a lot! This is exactly what I was missing!
