### ISSUE TITLE
cmd/go: test prompts to authenticate vcs-test.golang.org

### ISSUE THREAD

**Issue by bcmills** [golang/go#33883]
When running `go test cmd/go/...` for the first time on a new machine, I saw an `ssh` prompt on the terminal:

```
The authenticity of host 'vcs-test.golang.org (35.184.38.56)' can't be established.
ECDSA key fingerprint is SHA256:[…].
Are you sure you want to continue connecting (yes/no)? yes
```

Perhaps we can add a `known_hosts` file somewhere in `cmd/go/testdata` and set some environment variable to suppress the prompt?

(See also #27494.)

CC @hanwen @FiloSottile @jayconrod

**Comment by hanwen** [comment]
prompt looks as if it comes from openssh and not Go SSH, so unsubscribing.

**Comment by mvdan** [comment]
I encountered the same, and it was pretty annoying as it stopped a long-running `go test std cmd` check until I went to appease openssh :)

**Comment by mvdan** [comment]
This is annoying me again, enough to investigate a bit. I narrowed it down to `TestScript/mod_get_svn`.

There is a way to give ssh a flag to skip this verification, but unfortunately that knob can't be turned via an environment variable.

Worse even, ssh doesn't obey `$HOME`, so I can't use that to point it at a different config or known_hosts file.

**Comment by mvdan** [comment]
I found a workaround hack for it. It isn't great, but it's better than not having a workaround.
