### ISSUE TITLE
cmd/go: go run cannot build a command in a module directory

### ISSUE THREAD

**Issue by robpike** [golang/go#33890]
### What version of Go are you using (`go version`)?

Recent, pretty much 1.13.
<pre>
$ go version
go version devel +5498fa90e9 Fri Aug 23 00:46:55 2019 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/r/Library/Caches/go-build"
GOENV="/Users/r/Library/Application Support/go/env"
GOEXE=""
GOFLAGS="-ldflags=-w -mod=readonly"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/r"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/Users/r/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/Users/r/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/r/src/sos/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bf/qmf6xmzn7vs1gzv6g7mq_wfr0004fc/T/go-build281039180=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I cannot do `go run file.go` in a module directory, but I can in a  non-module directory:

<pre>
% go run v.go
v.go:14:2: found packages foo (foo_test.go) and main (v.go) in /Users/r/src/foo
% grep ignore v.go
v.go:3: // +build ignore
%
</pre>

### What did you expect to see?

It should run the program.

### What did you see instead?

An error about conflicting packages.

**Comment by robpike** [comment]
Also, why is it complaining about a test file? It shouldn't even be looking at that.

**Comment by mvdan** [comment]
`go run` was recently taught to build entire packages with their dependencies, so perhaps that's when this regression was introduced. CC @bcmills @jayconrod

**Comment by robpike** [comment]
This was my mistake involving misuse of build tags.
