### ISSUE TITLE
cmd/compile: SIGSEGV on NaCl when accessing implicit-zero elements in a large slice

### ISSUE THREAD

**Issue by johnrichardrinehart** [golang/go#33893]
The playground seems to trigger SIGSEGV runtime exceptions when accessing undefined elements in a large slice. I could not reproduce this locally (I get compile-time too-much-required-memory errors for large slices and normal runtime behavior for smaller slices).

### What version of Go are you using (`go version`)?
`Go 1.12.9`

### Does this issue reproduce with the latest release?
Not on a local machine, only on the playground.

### What operating system and processor architecture are you using (`go env`)?

Native Client, NaCl.

### What did you do?
I ran the following 3 programs.
1. https://goplay.space/#Rbv05s_S5ax
1. https://goplay.space/#Maqi_gYFakb
1. https://goplay.space/#NIfrZa_IIxb

### What did you expect to see?
1. Not a SIGSEGV
1. I got what I expected.
1. I got what I expected.

### What did you see instead?
1. A SIGSEGV runtime exception.
1. What I expected.
1. What I expected.

**Comment by agnivade** [comment]
I do get a seg fault when running locally, although not with the full stack trace.

```
GOOS=nacl GOARCH=amd64p32 go run foo.go 
signal: segmentation fault
```

**Comment by cuonglm** [comment]
> I do get a seg fault when running locally, although not with the full stack trace.
> 
> ```
> GOOS=nacl GOARCH=amd64p32 go run foo.go 
> signal: segmentation fault
> ```

You have to setup this https://github.com/golang/go/tree/master/misc/nacl for running nacl

**Comment by agnivade** [comment]
Woops, thanks @cuonglm. I never ran a basic program to check whether it works or not.

**Comment by johnrichardrinehart** [comment]
Oh, these are old issues. Sorry, @bcmills: I didn't do my due diligence. I'll go ahead and close this. No point in issuing a fix.
