### ISSUE TITLE
golang.org/x/tools/go/ssa/interp/testdata/src/fmt/fmt.go:3:6: missing function body

### ISSUE THREAD

**Issue by SanfordLuo** [golang/go#33909]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
go get golang.org/x/tools/cmd/goimports
TF_ACC=1 go test ./alicloud -v run=TestAccAlicloudSagInstancesDataSource_basic-timeout=300m

### What did you expect to see?
I expect this is pass

### What did you see instead?
golang.org/x/tools/go/ssa/interp/testdata/src/fmt/fmt.go:3:6: missing function body

**Comment by mvdan** [comment]
Please fill the issue template.
