### ISSUE TITLE
cmd/compile: js-wasm builder broke on "isfat" optimization

### ISSUE THREAD

**Issue by mdempsky** [golang/go#33916]
https://go-review.googlesource.com/c/go/+/179578 changed plive.go's "isfat" function to treat single element arrays and single field structs as single-value objects rather than multi-value objects. The notable thing about this change is it means for things like:

    var x struct { m *blah }
    x.m = foo()

the `x.m = foo()` assignment is considered as clobbering `x`, whereas before it was treated as just updating a single field, so the variable was considered live.

The CL updated test expectations accordingly, but the js-wasm builder seemed to fail on these, as it still considered the struct live in some cases.

The CL has been [reverted](https://go-review.googlesource.com/c/go/+/192157), but I think it would be good to understand why only js-wasm failed and land the change again.

/cc @cuonglm

**Comment by mdempsky** [comment]
I think the problem is that ssa/gen/WasmOps.go doesn't annotate instructions with symEffect.

I'm kind of surprised there aren't more liveness issues on GOARCH=wasm.

**Comment by mdempsky** [comment]
I see. So in live2.go's bad40, immediately before SSA lowering, we have (v25 is the return value from makemap, and v23 is the mem object returned by it):

```
v2 = SP
v26 = LocalAddr <*T40> {ret} v2 v23
v27 = OffPtr <*map[int]int> [0] v26
v28 = Store <mem>{map[int]int} v27 v25 v23
```

On most architectures (I tested amd64 and arm64), this gets lowered to something like:

```
v2 = SP
v8 = MOVQstore <mem> {ret} v2 v25 v23
```

Critically, plive.go is able to recognize than this MOVQ clobbers `ret` because MOVQstore is annotated with `symEffect: "write"` in gen/AMD64Ops.go.

However, on wasm, this gets lowered to:

```
v2 = SP
v26 = LoweredAddr <*T40> {ret} v2
v28 = I64Store <mem> [0] v26 v25 v23
```

which I think is roughly comparable to something like:

```
v2 = SP
v26 = LEAQ <*T40> {ret} v2
v28 = MOVQstore <mem> [0] v26 v25 v23
```

That is, the address computation is split out separately, and plive.go can't figure out the store is clobbering anything.

I think wasm should switch to support SymOffset for its load and store operations like other GOARCHes.

/cc @randall77 @cherrymui @neelance

**Comment by mdempsky** [comment]
> I think wasm should switch to support SymOffset for its load and store operations like other GOARCHes.

It seems like the reason this isn't a bigger issue for wasm is that gc/ssa.go inserts OpVarDef instructions around assignments where possible. This issue came up because it introduced new cases where plive.go was able to detect a variable was dead where gc/ssa.go didn't notice.

So an alternative fix here would be to extend gc/ssa.go to incorporate the "isfat" logic for figuring out when it can insert `OpVarDef`.

**Comment by cuonglm** [comment]
@mdempsky IIRC, buildssa emits OpVarDef regardless of variable is fat or not.

**Comment by mdempsky** [comment]
> IIRC, buildssa emits OpVarDef regardless of variable is fat or not.

For assignments like `x = ...` it does, but I don't believe that's the case for subvariable assignments like `x.m = ...`.

**Comment by cherrymui** [comment]
> I think wasm should switch to support SymOffset for its load and store operations like other GOARCHes.

I think this makes sense, at least for local variables.

**Comment by cuonglm** [comment]
>So an alternative fix here would be to extend gc/ssa.go to incorporate the "isfat" logic for figuring out when it can insert OpVarDef.

@mdempsky can you describe it more details?

Looking at SSA output, I see `OpVarDef` was inserted when `ret` declared. Also where must we incorporate the "isfat" logic?

**Comment by mdempsky** [comment]
> @mdempsky can you describe it more details?

gc/ssa.go emits OpVarDef when an assignments overwrites the entire variable. Currently it does this when an object is declared, and also immediately before assignments that overwrite the entire object (eg, `x = ...`). Note: OpVarDef can be emitted multiple times for a single variable.

The alternative suggestion I was making was that gc/ssa.go should also recognize `x.m = ...` assignments where x's type is not "fat".

> Also where must we incorporate the "isfat" logic?

I would expect it would just be a tweak to the existing OpVarDef logic in builder.assign.

**Comment by cuonglm** [comment]
> > @mdempsky can you describe it more details?
> 
> gc/ssa.go emits OpVarDef when an assignments overwrites the entire variable. Currently it does this when an object is declared, and also immediately before assignments that overwrite the entire object (eg, `x = ...`). Note: OpVarDef can be emitted multiple times for a single variable.
> 
> The alternative suggestion I was making was that gc/ssa.go should also recognize `x.m = ...` assignments where x's type is not "fat".
> 
> > Also where must we incorporate the "isfat" logic?
> 
> I would expect it would just be a tweak to the existing OpVarDef logic in builder.assign.

Hmm, the same as I did, but still no luck, maybe I check the wrong place, let me re-check.
