### ISSUE TITLE
test/codegen: wrong test cases can not be detected effectively

### ISSUE THREAD

**Issue by benshi001** [golang/go#33924]
The test/codegen test can not detect wrong cases for arm/wasm effectively.

For arm,  both

	GOOS=android GOARCH=arm CC_FOR_TARGET=$NDK ./all.bash

and

	GOOS=linux GOARCH=amd64 ./all.bash

passed on my ubnutu/amd64 host, without any error rised for an obvious wrong arm assembly.

For wasm,  both

	GOOS=js GOARCH=wasm ./all.bash

and

	GOOS=linux GOARCH=amd64 ./all.bash

passed on my ubnutu/amd64 host, without any error rised for an obvious incorrect wasm assembly.

What's more, the wrong cases even passed TryBot, until caught by daily build machines.

**Comment by agnivade** [comment]
Possibly, the issue maybe that `run.go` is run without the `all_codegen` flag.

**Comment by benshi001** [comment]
make `all_codegen` default to `true`?

And another issue is the TryBot did not catch some errors.

**Comment by ALTree** [comment]
The `all_codegen` flag was introduced to make all.bash faster by skipping the slow cross-arch compilations, it would make no sense to default it to true. The trybots also need to be fast.

To be honest, if someone is touching code generation in the compiler, I think it's their responsibility to run the codegen tests manually and with all_codegen enabled. No, `all.bash` is not enough. The name is misleading, it doesn't test *everything*.

For example, there are many standard library test that are slow to run, so they are skipped in all.bash. But if you working on the, say, `math/big` library, after you're done **first you manually run all the math/big tests using `go test`**, *then*, as a final check before mailing the patch, you run all.bash. But the first step is very important. When you are working on code generation, running the codegen test is a must, and especially when you are working on an arch different from the one your machine has, you must enable cross-testing with all_codegen.

One thing I note is that  the `all_codegen` flag is not documented in the codegen test harness README (go/test/codegen/README). We should definitely document it, and recommend that everyone that changes code generation in the compiler manually run the codegen test with the all_codegen enabled.

I'll send a README patch later.

**Comment by benshi001** [comment]
Thank you. Please close close this issue in your patch's commit message.
