### ISSUE TITLE
no call stack print when c dll setUnhandleExceptionFilter

### ISSUE THREAD

**Issue by zhaoya881010** [golang/go#33925]
i add setUnhandleExceptionFilter in c dll，dmp file is generated  when dll crash .but i found go program no print call stack. i  try cancel setUnhandleExceptionFilter dll,print call stack is normal.

### What did you expect to see?
dll generated  dmp file and go program print call stack.

### What did you see instead?
generated  dmp file,no print call stack.

**Comment by zhaoya881010** [comment]
maybe golang‘s osinit initExceptionHandler before setUnhandleExceptionFilter in dll.

**Comment by julieqiu** [comment]
Could you provide an example of the code that produced the error, preferably as a Go [Go playground](https://play.golang.org/) link?
