### ISSUE TITLE
x/website: tests failing on Android builders

### ISSUE THREAD

**Issue by bcmills** [golang/go#33935]
Two tests seem to be consistently failing on the `android-*-emu` builders (https://build.golang.org/log/2b88b2f804799f9e5780270b06f07542b8c400ab):

```
-- FAIL: TestWeb (2.41s)
    godoc_test.go:48: Building godoc: exit status 1
FAIL
exitcode=1FAIL	golang.org/x/website/cmd/golangorg	68.529s
?   	golang.org/x/website/cmd/googlegolangorg	[no test files]
--- FAIL: TestStaticIsUpToDate (0.01s)
    gen_test.go:23: error while generating static.go: open analysis/call3.png: no such file or directory
    gen_test.go:27: static.go is stale.  Run:
          $ go generate golang.org/x/website/content/static
          $ git diff
        to see the differences.
FAIL
exitcode=1FAIL	golang.org/x/website/content/static	66.472s
```

We should either fix those tests, or (given that we're unlikely to be hosting `golang.org` on a mobile device any time soon) skip the `x/mobile` tests on those builders.

CC @toothrot @dmitshur @andybons

**Comment by dmitshur** [comment]
`TestStaticIsUpToDate` is failing on that builder likely because it doesn't have local filesystem access. The test is passing on linux/amd64.

`TestWeb` is also failing on aix and illumos because it's unable to build or is missing the compiler.

I think it's reasonable to skip all these architectures for x/website tests.

**Comment by dmitshur** [comment]
> `TestWeb` is also failing on aix and illumos because it's unable to build or is missing the compiler.

If we disable the tests, these failures will become invisible. These seem fixable, so I'll leave them alone for now.

**Comment by dmitshur** [comment]
Something that's odd is that [`buildGodoc`](https://github.com/golang/tools/blob/42f498d34c4d67145e3950193a8f23db9328e7f3/cmd/godoc/godoc_test.go#L35-L37) is supposed to skip `TestWeb` when `runtime.GOOS == "android"`. Is GOOS not "android" on `android-*-emu` builders?
