### ISSUE TITLE
x/website: better HTML printing, don't page break inside code blocks

### ISSUE THREAD

**Issue by greywolve** [golang/go#33933]
I was trying to print out Effective Go and I noticed code blocks get split across pages.

This is easily fixed by amending the CSS a bit:

```
@media print {
  pre {
    background: #fff;
    border: 0.0625rem solid #bbb;
    white-space: pre-wrap;
    page-break-inside: avoid; // added this
  }
}
```

Before:
![Screenshot from 2019-08-29 14-03-33](https://user-images.githubusercontent.com/1939511/63938793-f1dfe280-ca65-11e9-9033-8a38739ea918.png)

After:
![Screenshot from 2019-08-29 14-05-26](https://user-images.githubusercontent.com/1939511/63938850-1a67dc80-ca66-11e9-8f63-1b066df71031.png)

**Comment by andybons** [comment]
@greywolve feel free to send a change.

**Comment by Freeaqingme** [comment]
Why is breaking a page across a code block not desirable? For one thing, it's more environmentally to fill every page. Also, I remember back in the day that it wasn't unheard of of copying multiple pages of books filled with qbasic code. A page break never bothered me really.

Maybe we can only do this for small code blocks?

**Comment by greywolve** [comment]
It's not desirable (to me) because it makes reading large blocks of code more difficult. Perhaps I'm just not used to reading printed out code split across pages. :) It's annoying to have to shuffle back and forth to try read a block of code, especially if you have the pages bound and can't see the other page.

Doing this for small blocks of code seems much more difficult, and perhaps not worth the effort then. You'd have to tag each small block of code throughout the entire website with a different class that you can target. 

Personally this change is much more about large blocks of code than smaller blocks anyway. For me, that's the 80/20.

Would you be happy buying a technical book with code split across pages? I suspect most people wouldn't be.

**Comment by Freeaqingme** [comment]
> Would you be happy buying a technical book with code split across pages? I suspect most people wouldn't be.

For larger blocks? Sure.

Anyways, feel free to fly with it. Just wanted to bring up some points that possibly hadn't been considered yet. I'm not that strongly opinionated on it.
