### ISSUE TITLE
strings: replace strings.Index with strings.IndexByte

### ISSUE THREAD

**Issue by akaNightmare** [golang/go#33931]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ivan.zubok/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ivan.zubok/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.7/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zw/x6_dxqvs0v15850v4qsj6gch0000gn/T/go-build301222442=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

Replace all `strings.Index("some string", "ONE_CHARACTER_HERE")` with `strings.IndexByte("some string", 'ONE_CHARACTER_HERE')` where it's possible (same situations for `strings.LastIndex`)

**Comment by mvdan** [comment]
You don't need to file an issue for a small refactor like this, unless there's a performance bug that you've spotted.

**Comment by akaNightmare** [comment]
@mvdan got it

**Comment by mvdan** [comment]
The patch was rejected, and this issue doesn't seem to have anything else to act on.
