### ISSUE TITLE
go get  -  parsing go.mod: missing module line

### ISSUE THREAD

**Issue by monsterzzz** [golang/go#33948]
C:\Users\monster\Desktop\ginProject>go get gopkg.in/jcmturner/rpc.v2
go: gopkg.in/jcmturner/rpc.v2@v2.0.0: parsing go.mod: missing module line
go: error loading module requirements

what should I do？

**Comment by julieqiu** [comment]
A better place to ask this kind of question is golang-nuts. See https://golang.org/wiki/Questions.
