### ISSUE TITLE
reflect: get name of variables for consts

### ISSUE THREAD

**Issue by esvm** [golang/go#33941]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.12.4 windows/amd64
</pre>

Is there an wasy way to get the name of variables on consts? To to that I add `go generate` to my files where exists consts to have an easy way to get the consts names. (https://jbu.io/2017/05/02/simple-enumeration-in-golang-using-stringer/)

I think that we can have this option in reflect package with something like reflect.GetName(myVar). I did a search about this and didn't find anything. If already exists a maner to do this, please tell me. If not, I can try to implement and create a PR with this feature.

**Comment by esvm** [comment]
Any news about this?

**Comment by ianlancetaylor** [comment]
It's only been a day.  In general, we don't use the issue tracker for questions.  You will get better and faster answers on a forum.  See https://golang.org/wiki/Questions.

I'm not sure precisely what you are asking, but Go is a compiled language and variable and const names are not recorded in the binary.  So there is no way to implement that in the reflect package.

**Comment by esvm** [comment]
Okay, thanks!!
