### ISSUE TITLE
x/blog: support Markdown

### ISSUE THREAD

**Issue by andybons** [golang/go#33955]
If an article has an `.md` extension, it should render using a Markdown parser. We don’t have to go through the trouble of converting all articles over, but new ones should be in a more broadly supported format.

Perhaps using https://github.com/russross/blackfriday along with https://github.com/microcosm-cc/bluemonday to sanitize content.

@julieqiu with thoughts on Markdown libraries and sanitation 🚮

**Comment by ThePartyOfGUN** [comment]
I think it is a very good idea!

**Comment by smasher164** [comment]
Would articles written in the Markdown format still support runnable code snippets? If so, one option is to implement a custom rendering engine for blackfriday that interprets snippets like the following as runnable.
````
```play
```
````
/cc @dmitshur since he's written a renderer for blackfriday before.

**Comment by ruzaikr** [comment]
I'd love to try this issue :) Pls assign it to me

**Comment by rsc** [comment]
I have a draft of this working, although the extension is unchanged. CLs to follow shortly.

**Comment by dmitshur** [comment]
This has been implemented via the aforementioned CLs. Closing.

Please re-open or file a new issue if there's something more to do here.
