### ISSUE TITLE
cmd/go: gofmt should ignore vendor

### ISSUE THREAD

**Issue by abhigenie92** [golang/go#33962]
When you run `go fmt $$(go list ./...)` it ignores vendor by default but `gofmt .` doesn't do that.
The use case is if you run fmt without the code modification in-place and ignore the vendor.

One way is `gofmt -l (find . -type f -name '*.go'| grep -v "/vendor/")`, is there an easier way?

**Comment by bcmills** [comment]
@abhigenie92, please fill out the full template — specifically, it would be helpful to know the exact commands you ran that led to confusion.

Specifically:
* What concrete problem were you trying to solve that led you to run `gofmt .`?
* Did you actively `cd` into the `vendor` directory before running the command?
* Are you talking about the behavior of `go fmt .`, or `gofmt .`? (That is, is this the problem found in `cmd/go`, `cmd/gofmt`, or both?) How did you choose between them?

**Comment by bcmills** [comment]
See also #29751.
