### ISSUE TITLE
cmd/link: ErrorUnresolved provides misleading information

### ISSUE THREAD

**Issue by 4a6f656c** [golang/go#33979]
Under OpenBSD -current with clang, `cgo_test` currently fails to build with: 

```shell
# misc/cgo/test.test
misc/cgo/test(.text): relocation target __mulsc3 not defined for ABI0 (but is defined for ABI0)
misc/cgo/test(.text): relocation target __muldc3 not defined for ABI0 (but is defined for ABI0)
misc/cgo/test(.text): relocation target __absvsi2 not defined for ABI0 (but is defined for ABI0)
FAIL    misc/cgo/test [build failed]
```

The underlying cause is an unrelated issue that is resulting in `libcompiler_rt.a` not being found. However, ErrorUnresolved should not be reporting `relocation target X not defined for ABI0 (but is defined for ABI0)` - this is caused by the code searching the same ABI and finding a matching `SXREF` symbol, which is the same symbol that it is trying to resolve in the first place.

This appears to be a variant of issue #29852.

**Comment by aclements** [comment]
Re-opened by revert CL 213417

**Comment by aclements** [comment]
See #36389 for some discussion of the issue that resulted in a revert. The fix itself is almost certainly fine; it's just a problem with the test that was added.
