### ISSUE TITLE
cmd/doc: show Bugs section

### ISSUE THREAD

**Issue by pascaldekloe** [golang/go#33970]
The new `go doc` does not show documented bugs conform the [convention](https://blog.golang.org/godoc-documenting-go-code).

For example, `go doc -all godoc.org/pascaldekloe/jwt | grep -i bug` has no results. The HTML representation catches the comments correctly at <https://godoc.org/github.com/pascaldekloe/jwt#pkg-note-bug> .

Bugs are an essential part of the documentation.
* `go doc -all` should have a bugs section (like godoc(8) does)
* `go doc <selection>` should include the relevant bugs for the respective selection

**Comment by agnivade** [comment]
Sounds reasonable to me.

@robpike @mvdan

**Comment by pascaldekloe** [comment]
Technically this is not a feature. The old godoc had bug listing on the command line.

**Comment by agnivade** [comment]
Right. But `cmd/doc` didn't. So it is a feature request for `cmd/doc`. But I get what you mean :).

**Comment by mvdan** [comment]
I assume that @ianthehat or @dmitshur have some ideas here, since I undesrtand they plan on sharing more code between similar tools like `go doc` and `gddo`.

**Comment by pascaldekloe** [comment]
The old go doc als listed bugs correctly @agnivade. I see now how my description is a bit misleading. This is a bug, or maybe an undocumented feature los. 😏

**Comment by mvdan** [comment]
Are you positive? If so, can you reproduce that with a specific old version of Go? For example, see https://godoc.org/golang.org/dl, or the Docker images.

**Comment by pascaldekloe** [comment]
Yes, version 1.11 of `go doc` (without any flags) reports the bugs section nicely.

**Comment by robpike** [comment]
It already does this. Try 'go doc strings`, or `go doc -all strings`, which is equivalent functionality to what the the `godoc` server shows for the package, and you will see:

```
BUG: The rule Title uses for word boundaries does not handle Unicode punctuation properly.
```

If you are asking that the bug information be shown always, I disagree, as `go doc TrimFunc` should not display the output for a bug about `Title`.

**Comment by agnivade** [comment]
Aha ! It shows it as part of the function itself. I was searching for a separate section like `godoc` shows. My bad, I should have grepped for "BUG".

@robpike - Do you think it makes sense to move all `BUG`s and show them as a separate section at the bottom like godoc does ? Apart from also showing them when someone explicitly asks for that function/method.

**Comment by pascaldekloe** [comment]
The strings package example has a BUG comment embedded into the function comment block. In that case `go doc` prints the bugs section indeed. However, the detection fails with the `-all` flag, and prints the comment block as is, including `(rsc)` marker.

```
% go doc strings | tail -n 5
type Replacer struct{ ... }
    func NewReplacer(oldnew ...string) *Replacer

BUG: The rule Title uses for word boundaries does not handle Unicode punctuation properly.

% go doc -all strings | grep -i bug -B 2 -A 3
    words mapped to their Unicode title case.

    BUG(rsc): The rule Title uses for word boundaries does not handle Unicode
    punctuation properly.

func ToLower(s string) string
% go doc github.com/pascaldekloe/jwt | grep -i bug
% ~/sdk/go1.11.6/bin/go !*
~/sdk/go1.11.6/bin/go doc github.com/pascaldekloe/jwt | grep -i bug
BUG: Some broken implementations fail to parse tokens
% 
```

So it turns out there are 3 issues.
1. The `-all` flag disables bug comment detection
2. Go version 1.13 no longer detects bug comments in blocks
3. Go should include bug notes with a selection where applicable [new feature]

How to proceed? Shall I split this issue up into separate reports?

**Comment by pascaldekloe** [comment]
> include bug notes with a selection where applicable

Bit of a rabbit hole. Do we include a function body and all of its functions invoked? 😅 Also, doc.reader clears the Body of each ast.FuncDecl now to save some memory, so the location information is lost.
