### ISSUE TITLE
x/tools/gopls: Context cancelled errors after some editing

### ISSUE THREAD

**Issue by inliquid** [golang/go#33989]
VS Code.
go version go1.12.9 windows/amd64
`gopls`: latest from master (but these annoying errors have been seen for a while with older versions)

I'm regularly seeing these `Context cancelled` errors, this one is simple example but there are much more in bigger projects. They usually appear after some editing. As a result it requires LSP restart.

![изображение](https://user-images.githubusercontent.com/6797881/64049837-d4526c00-cb7e-11e9-867d-fdb3c20baa32.png)

**Comment by stamblerre** [comment]
Are you still noticing these issues with the current master of `gopls`? https://go-review.googlesource.com/c/tools/+/192719 should have fixed most of them, I believe.

**Comment by inliquid** [comment]
Not sure, I'll watch a little.

**Comment by inliquid** [comment]
Haven't seen these messages with latest builds, so I'm closing issue for now.
