### ISSUE TITLE
The community needs a stronger WARNING about the change in private modules - proxy.golang.org

### ISSUE THREAD

**Issue by hammerandtongs** [golang/go#33980]
https://tip.golang.org/cmd/go/#hdr-Module_configuration_for_non_public_modules

This was featured nowhere in the announcement -  

https://blog.golang.org/module-mirror-launch

It would seem to impact a large number of people using golang.

**Comment by donatj** [comment]
I would request you to be able to mark a module as private in the go.mod rather than depending on each machine setting it's environmental variables.

**Comment by katiehockman** [comment]
This was addressed in #33796. It's in the [first paragraph of the release notes](https://tip.golang.org/doc/go1.13#introduction) and the first paragraph of the [blog post](https://blog.golang.org/module-mirror-launch)
