### ISSUE TITLE
x/sys/unix: TestPassFD consistently failing in aix-ppc64 builder on release-branch.go1.12

### ISSUE THREAD

**Issue by bcmills** [golang/go#33982]
`golang.org/x/sys/unix` is failing in `aix-ppc64` on `release-branch.go1.12` (https://build.golang.org/log/2ceea003d216da8b55d107004541d477ada9c89f):

```
--- FAIL: TestPassFD (0.75s)
    syscall_unix_test.go:224: child process: "WriteMsgUnix: write unix : sendmsg: bad file number", <nil>
FAIL
FAIL	golang.org/x/sys/unix	1.041s
```

The same failure does not occur on `release-branch.go1.13`. Is there a fix we should backport, or should we skip the test on AIX on 1.12?

CC @Helflym @trex58 @laboger

**Comment by Helflym** [comment]
https://golang.org/cl/170537 should fix it.

**Comment by bcmills** [comment]
@Helflym, as far as I can tell that CL is on the `master` branch (that is, Go 1.14), but the test failure was only observed on `release-branch.go1.12`. Is there something that can/should be backported to fix the builder?

**Comment by Helflym** [comment]
Why 1.14 ? Yes, it has been merged in `master` branch but before 1.13 freeze. That's why `golang.org/x/sys/unix` is green for `release-branch.go1.13` but fails for `release-branch.go1.12`. Or I'm missing something... 
To explain a bit further, the test is failing because in 1.12, we are using `recvmsg` and `sendmsg` which aren't compatible with `Control` and `Controllen` structures.

**Comment by bcmills** [comment]
Sorry, my mistake — for some reason I thought that CL hadn't been merged yet.

If it is expected that the `golang.org/x/sys/unix` test fails on AIX before 1.13, then the test should call `t.Skip` if `runtime.GOOS == "aix"` on builds that lack the `go1.13` build tag.

**Comment by Helflym** [comment]
Is it possible to check the `go1.13` build tag inside an `if` or the whole file must be disabled for 1.12 ?

**Comment by bcmills** [comment]
I'm not sure, but you can always add a separate file that sets a variable:

```
// […]

// +build aix,!go1.13

package unix

func init() {
	aixHasSendmsgBug = true
}
```

**Comment by tklauser** [comment]
Couldn't we just backport https://golang.org/cl/170537 (maybe sans the `SockaddrDatalink` addition) to `release-branch.go1.12` to fix the issue instead of just skipping the test? Or is that not worth the effort?

**Comment by Helflym** [comment]
I think it's also better to backport it. Syscall package is also using Control and Controllen structures, so `nrecvmsg` and `nsendmsg` should be used.

**Comment by ianlancetaylor** [comment]
Sure, let's backport it.
