### ISSUE TITLE
bytes/hash: TestSmhasherSeed flaky on 32-bit builders

### ISSUE THREAD

**Issue by bcmills** [golang/go#33988]
Seen on the `windows-386-2008` builder, likely as a result of CL 186877 (#28322):

https://build.golang.org/log/2be333e9f2c0cdac67f47107a5a7a8411982f8fd
```
--- FAIL: TestSmhasherSeed (0.09s)
    smhasher_test.go:94: unexpected number of collisions: got=11 mean=0.000000 stddev=0.000033
FAIL
FAIL	bytes/hash	0.254s
```

**Comment by bcmills** [comment]
`linux-386-387`: https://build.golang.org/log/f371d2f41f07168250f1a4f6da413a722a2bbe5f

**Comment by ALTree** [comment]
`darwin-386-10_14`:  https://build.golang.org/log/c3df795bd63e01fb9e9f9b804e80edcced255004

**Comment by bcmills** [comment]
`freebsd-386-12_0`:
* https://build.golang.org/log/417d3a90ceb96105a38f8281b70c1ad1ae3d6f6d
* https://build.golang.org/log/b5cd25b43213b69c186c6a01fc3b8cd2d4ad9851

@randall77, if there isn't an easy fix please add a `Skip` for the test on 32-bit targets in the meantime.
