### ISSUE TITLE
error interface, is nil or not?

### ISSUE THREAD

**Issue by yixinin** [golang/go#33994]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.9 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/yixin/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/yixin/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build424146697=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

``` go
func main() {
	var err = errors.New("errors msg")
	name, err := GetName()
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(name)
	}
}

type Error struct {
	Message string
}

func (e *Error) Error() string {
	if e == nil {
		return "Error is nil"
	}
	return e.Message
}

func GetName() (string, *Error) {
	var err = &Error{
		Message: "error msg",
	}
	err = nil
	return "yixinin", err
}

```
### What did you expect to see?

"Error is nil"

### What did you see instead?

"yixinin"
or
"error msg"

if err ==nil, it should print "yixinin", or err !=nil, it should print error msg.

**Comment by davecheney** [comment]
https://golang.org/doc/faq#nil_error

**Comment by av86743** [comment]
Dup of [#33965](https://github.com/golang/go/issues/33965)?

**Comment by yixinin** [comment]
sorry, I will close it. thanks all
