### ISSUE TITLE
cmd/go: confusing error message when downloading modules with no internet connection

### ISSUE THREAD

**Issue by Russiancold** [golang/go#33995]
### What version of Go are you using (`go version`)?
<pre>
$ go version
1.12.9
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> GOOS=linux GOARCH=amd64</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I've tried to build my go app with modules in docker.
```
FROM golang:1.12.9 as builder

ENV GO111MODULE=on
WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o encashment


FROM scratch
COPY --from=builder /app/encashment /encashment/
EXPOSE 8080
ENTRYPOINT ["/app/encashment"]
```
The problem was that my docker had no internet connection and `go mod download` couldn't load packages. I was very confused with an error message it returns. Suddenly, I don't know exactly what was wrong and how to reproduce this properly. But I did:
```
pkill docker
iptables -t nat -F
ifconfig docker0 down
brctl delbr docker0
docker -d
```
And this worked for me.
### What did you expect to see?

Error message informing that something is wrong with internet connection.

### What did you see instead?
```
go: finding github.com/gorilla/mux v1.7.3
go: github.com/gorilla/mux@v1.7.3: unknown revision v1.7.3
go: error loading module requirements
```

**Comment by seankhliao** [comment]
Current error message seems reasonable.

> $ go mod download
> go: github.com/gorilla/mux@v1.8.0: Get "https://proxy.golang.org/github.com/gorilla/mux/@v/v1.8.0.mod": dial tcp: lookup proxy.golang.org: i/o timeout
