### ISSUE TITLE
encoding/json: unexpected behavior when unmarshalling to "boxed" struct

### ISSUE THREAD

**Issue by brenol** [golang/go#33993]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.9 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/goworkspace"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build909978713=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

https://play.golang.org/p/IOwj_PHRGXK

### What did you expect to see?

I did not expect `v` to be of type map[string]interface{}, as its underlying type is clearly Y.

### What did you see instead?
`v`is of type map[string]interface{}, failing the type assertion.

Note that if it's a pointer to Y, it works correctly.
Also, this came from a bigger project where Sprintf was reporting both `v`and `Y{}` with the same underlying type, however, I was unable to reproduce that here.

Also, removing json.Unmarshal  fixes the issue, as the boxed Y is cast correctly to Y when there is no unmarshal.

**Comment by OneOfOne** [comment]
You need to use a pointer to `Y`:

https://play.golang.org/p/wYxDOs4QdUn

**Comment by katiehockman** [comment]
@brenol can you confirm that this suggestion resolves your issue? If so, this issue can be closed.

You can also check out https://github.com/golang/go/wiki/Questions for more resources.

**Comment by brenol** [comment]
Yes, the suggestion fixes the issue.

However, is this the expected behavior? I mean, as I mentioned, removing json.Unmarshal altogether *does* work and it does not panic.

My main issue here is: should json.Unmarshal change the underlying type of a by value struct to map[string]interface{}? I tried looking up for some reason this happens but it didn't make sense to me, as the docs don't make it clear why it works with pointers and not with values.

**Comment by seankhliao** [comment]
Plain structs in interfaces aren't addressable, so they can't be set.
encoding/json makes no provision for setting the value of non pointer structs (since it can't), so it follows the other documented rules, allocating a map.
