### ISSUE TITLE
Unexpected behavior of built-in `append` function

### ISSUE THREAD

**Issue by zzy96** [golang/go#34001]
### Does this issue reproduce with the latest release?

Yes

### What did you do?

Run
```
a := []int{}
a = append(a, 1)
fmt.Println(len(a))
fmt.Println(cap(a))
```

### What did you expect to see?
Both len and cap should be 1

### What did you see instead?
len(a) is 1, cap(a) is 2

**Comment by mvdan** [comment]
This is expected. Please read https://blog.golang.org/slices.
