### ISSUE TITLE
encoding/json: backport CL 188717 for 1.13

### ISSUE THREAD

**Issue by mvdan** [golang/go#34006]
https://golang.org/cl/188717 removes a piece of godoc added in 1.13, since it was incorrect and misleading.

We should backport this for either the final 1.13 release, or 1.13.1.

Not a release blocker, as this is only a minor doc change.

/cc @andybons @dmitshur

**Comment by dmitshur** [comment]
Approving because it's a documentation fix.

I've looked at the history of relevant issues/CLs and the fix looks valid to me. Compact does not escape `<`, `>`, `&` characters the way Marshal does. E.g., see [here](https://play.golang.org/p/o0XfQWmILlx).
