### ISSUE TITLE
proxy.golang.org: github.com/go-redis/redis 6.15.4

### ISSUE THREAD

**Issue by pierrre** [golang/go#34005]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.13rc2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, I'm using the latest RC

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pierre/.cache/go-build"
GOENV="/home/pierre/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pierre/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/pierre/.gimme/versions/go1.13rc2.src"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/pierre/.gimme/versions/go1.13rc2.src/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build984822954=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I've noticed that it is impossible for me to get github.com/go-redis/redis 6.15.4.
It prints the error message:
```
verifying github.com/go-redis/redis@v6.15.4+incompatible/go.mod: github.com/go-redis/redis@v6.15.4+incompatible/go.mod: reading https://sum.golang.org/lookup/github.com/go-redis/redis@v6.15.4+incompatible: 410 Gone
```

I don't have any issue with version 6.15.3

https://sum.golang.org/lookup/github.com/go-redis/redis@v6.15.3+incompatible is working fine
https://sum.golang.org/lookup/github.com/go-redis/redis@v6.15.4+incompatible is returning an error

Of course, I know that this package is "incompatible" (it seems to be fixed in v7, but it's still in beta).

Do you have any idea why this version is not working ?

I don't see a lot of difference between these versions.
https://github.com/go-redis/redis/compare/v6.15.3...v6.15.4
Could it be caused by the change in `go.mod` ? (they added `go 1.13`)

Thank you.

**Comment by heschik** [comment]
There's a couple things going on here, I think. First is the new validation added in 1.13, described in the "version validation" section of https://tip.golang.org/doc/go1.13. That would normally reject both v6.15.3+incompatible and .4+incompatible. However, you probably upgraded from 1.12 and already had both versions in your module cache. That bypasses the validation, which only takes place on fetch.

Second is that sum.golang.org was running 1.12 for quite a while, which allowed these bad versions to be recorded permanently in the log. They were purged from proxy.golang.org, so you'll see that both https://proxy.golang.org/github.com/go-redis/redis/@v/v6.15.3+incompatible.info and https://proxy.golang.org/github.com/go-redis/redis/@v/v6.15.4+incompatible.info return the same error as the failing sum.golang.org URL. However, it was not feasible to purge them from sum.golang.org, so the (invalid) cached version will live forever there.

Long and short of it is, these go-redis versions are not usable in module mode in 1.13 without some replace hackery, and you'll get much clearer error messages if you clear your module cache. Hope that clears things up, and sorry for the trouble.

**Comment by pierrre** [comment]
And 6.15.2 is working, because it doesn't have a `go.mod` file !
I understand now. Thank you for your explanation. :+1: 

I will open an issue to `go-redis`, and mention this current issue.
(Originally, I thought it was an issue with the proxy)
