### ISSUE TITLE
fmt: spaces instead of zeroes in padding when precision is 0

### ISSUE THREAD

**Issue by inliquid** [golang/go#34003]
I read fmt docs several times, but didn't find any reasoning why the following would ever happen.

So here is normal working behavior:
```go
func main() {
	i := 1
	fmt.Printf("%03d", i)
}
```
Output (ok):
```
001
```

Now, we add one additional dot `.` making precision equal to zero, and we'll see spaces instead of zeroes as it  should be with `0` flag:
```go
func main() {
	i := 1
	fmt.Printf("%03.d", i)
}
```
Output (wrong):
```
  1
```

#### System details

```
go version go1.12.9 windows/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="C:\Users\***\AppData\Local\go-build"
GOEXE=".exe"
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="windows"
GOOS="windows"
GOPATH="C:\Users\***\go"
GOPROXY=""
GORACE=""
GOROOT="C:\Go"
GOTMPDIR=""
GOTOOLDIR="C:\Go\pkg\tool\windows_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="NUL"
GOROOT/bin/go version: go version go1.12.9 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.12.9
```

**Comment by KarthikNayak** [comment]
Did a little deep diving and found this in the source code.
```
// Two ways to ask for extra leading zero digits: %.3d or %03d.
// If both are specified the f.zero flag is ignored and
// padding with spaces is used instead.
```

This seems a little obsolete since the code below is modified, but the gist from the code is that when you use a precision value, only space padding is done. Happy to submit a patch if this isn't intended behavior

**Comment by robpike** [comment]
It's working as intended and as explained in this comment. It is intentional, but a historical artifact: C's printf works the same way.

**Comment by inliquid** [comment]
I see, thank you for clarifying.
