### ISSUE TITLE
go run -race test.go, print WARNING: DATA RACE

### ISSUE THREAD

**Issue by zz2** [golang/go#34018]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/export/gopath"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build051426756=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
go run -race test.go

```
package main

//import "fmt"
import "time"

type test struct {
	a int
	c chan int
}

func (t *test) f() {
	for {
		t.a++    // (1)
		t.c <- 0 // (2)

		time.Sleep(10 * time.Microsecond)
	}
}

func (t *test) f2() {
	for {
		<-t.c         // (3)
		if t.a == 3 { // (4)
			//fmt.Println("##\n")
		}

		time.Sleep(10 * time.Microsecond)
	}
}

func doTest() {
	t := new(test)
	t.a = 2
	t.c = make(chan int, 10)
	go t.f()
	go t.f2()
}

func main() {
	for i := 0; i < 100; i++ {
		doTest()
	}

	time.Sleep(time.Second * 10)
}
```

### What did you expect to see?

no WARNING: DATA RACE.

I refer to the example program in the link (https://golang.org/ref/mem) and write test.go.
In example program, is guaranteed to print "hello, world".
But in my test.go，it report DATA RACE. 

the example program is:
```
var c = make(chan int, 10)
var a string

func f() {
    a = "hello, world"
    c <- 0
}

func main() {
    go f()
    <-c
    print(a)
}
```

### What did you see instead?
```
==================
WARNING: DATA RACE
Write at 0x00c000010080 by goroutine 5:
  main.(*test).f()
      /root/test.go:13 +0x54

Previous read at 0x00c000010080 by goroutine 6:
  main.(*test).f2()
      /root/test.go:23 +0x67

Goroutine 5 (running) created at:
  main.doTest()
      /root/test.go:35 +0xcb
  main.main()
      /root/test.go:41 +0x38

Goroutine 6 (running) created at:
  main.doTest()
      /root/test.go:36 +0xed
  main.main()
      /root/test.go:41 +0x38
==================
```

**Comment by egonelbre** [comment]
The code you provided does have a data race. It becomes more obvious when you remove `time.Sleep`.

```
func (t *test) f() {
	for {
		t.a++    // (1)
		t.c <- 0 // (2)
	}
}

func (t *test) f2() {
	for {
		<-t.c         // (3)
		if t.a == 3 { // (4)
		}
	}
}
```

In the first loop, everything is correct. However, after step `(3)`, lines `(4)` and `(1)` may happen concurrently, which is a data race.

**Comment by av86743** [comment]
If your example, you serialize read of `t.a` in `f2()` with read/write of `t.a` in `f()` like in documentation example.  However, next read/write of `t.a` in `f()` is not serialized with first read of `t.a` in `f2()` (or at least I do not see how.)

**Comment by zz2** [comment]
thanks for your help @egonelbre @av86743
