### ISSUE TITLE
GOPROXY is not used in go 1.13 GO111MODULE auto mode

### ISSUE THREAD

**Issue by mschneider82** [golang/go#34019]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13rc2 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/matthiass/.cache/go-build"
GOENV="/home/matthiass/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/matthiass/go"
GOPRIVATE=""
GOPROXY="https://goproxy.internal"
GOROOT="/home/matthiass/.go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/matthiass/.go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-I/opt/ibm/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/opt/ibm/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build205597140=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```
$ go get -v -u github.com/mschneider82/problem
github.com/mschneider82/problem (download)

```

### What did you expect to see?

In the athens proxy (goproxy.internal) log the get, but there is no proxy used!

### What did you see instead?

It doesn't use the `$GOPROXY` when i am not in a module directory (e.g. cd $HOME ), its only used if I set `GO111MODULE=on`

**Comment by mvdan** [comment]
GOPROXY is for Go module proxies, so it can't be used if you're in GOPATH mode. Is that what you're asking?

**Comment by mschneider82** [comment]
Yes, i would expect that the GOPROXY is always used to get modules or repositories

**Comment by mschneider82** [comment]
I am closing this issue, it seems to works as designed.
