### ISSUE TITLE
syscall: TestAmbientCapsUserns test failing with operation not permitted

### ISSUE THREAD

**Issue by LocutusOfBorg** [golang/go#34015]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13-rc2
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

Ubuntu devel, 19.10

</pre></details>

### What did you do?

trying to build the source code, I get

```
ok  	sync/atomic	0.047s
--- FAIL: TestAmbientCapsUserns (0.00s)
    exec_linux_test.go:667: fork/exec /tmp/gotest465803457: operation not permitted
FAIL
FAIL	syscall	0.033s
```

I suspect Ubuntu builders should ignore that test?

**Comment by ALTree** [comment]
Thanks for reporting this.

I doubt this is related to #12815. This look yet another variant of #30698. We already try to detect Kernel configurations that would make the test fail ([CL 166460](https://go-review.googlesource.com/c/go/+/166460/), [CL 180877](https://go-review.googlesource.com/c/go/+/180877/))  but the current checks are possibly not exhaustive.

**Comment by ALTree** [comment]
Also, please not that this is not a build failure (i.e.: the code does not compile). The package compiles just fine, this is just a test failing. You can run `make.bash` instead of `all.bash` and the toolchain should be built without errors.

**Comment by LocutusOfBorg** [comment]
this is what we run...
```
        set -ex; \
                cd src; \
                export PATH="$(GOROOT)/bin:$$PATH"; \
                eval "$$(go tool dist env)"; \
                bash run.bash -k -no-rebuild;
```

**Comment by LocutusOfBorg** [comment]
interesting this fails also in pbuilder chroot configuration...

**Comment by LocutusOfBorg** [comment]
I can provide information if needed! Such as kernel configuration (Ubuntu 18.04 amd64 default one),
and steps to reproduce on a clean debian/ubuntu environment

**Comment by ALTree** [comment]
I can provide information if needed! Such as kernel configuration (Ubuntu 18.04 amd64 default one),
and steps to reproduce on a clean debian/ubuntu environment

@LocutusOfBorg Yes please. I'll help the investigation. Thanks.

**Comment by LocutusOfBorg** [comment]
on a Debian/Ubuntu system (I'm using ubuntu 18.04 LTS amd64)
```
pbuilder-dist sid create
pbuilder-dist sid login (remember the directory where the chroot is extracted)
pull-debian-source golang-1.13

copy the downloaded files into the chroot

go inside the chroot (the login command above does it)
cd golang-*
apt build-dep ../golang*dsc
dpkg-buildpackage

enjoy your failure!
```

Of course, inside the chroot you can install/play with whatever you want, install git, download stuff and so on...

**Comment by LocutusOfBorg** [comment]
inside an Ubuntu/Debian machine you probably just need to install "ubuntu-dev-tools" and "pbuilder-dist"

**Comment by LocutusOfBorg** [comment]
This is my default kernel configuration

[config-5.0.0-25-generic.txt](https://github.com/golang/go/files/3568562/config-5.0.0-25-generic.txt)

**Comment by longsleep** [comment]
This also fails on launchpad (see https://launchpadlibrarian.net/440240117/buildlog_ubuntu-xenial-amd64.golang-1.13_1.13-1longsleep1+xenial_BUILDING.txt.gz for example)

**Comment by tklauser** [comment]
@LocutusOfBorg @longsleep Could you please check whether https://golang.org/cl/195738 fixes the test failure for you?

**Comment by LocutusOfBorg** [comment]
Hello, looks like still failing...
```
 ok strings 0.272s
ok sync 0.513s
ok sync/atomic 0.077s
--- FAIL: TestAmbientCapsUserns (0.02s)
    exec_linux_test.go:672: fork/exec /tmp/gotest797948891: operation not permitted
FAIL
FAIL syscall 0.142s
ok testing 0.098s
```

**Comment by LocutusOfBorg** [comment]
In my case, the kernel is 5.3, so the patch is not skipping the test...

FWIW we have new systemd 241, so maybe /tmp is not able anymore to fork processes?

**Comment by tklauser** [comment]
Thanks for the feedback @LocutusOfBorg. Reopening the issue for further investigation.

**Comment by tklauser** [comment]
Trying the instructions in https://github.com/golang/go/issues/34015#issuecomment-527325055 I was able to reproduce this in a chroot. I think we need to check in `TestAmbientCapsUserns` whether we're chrooted like it is already done for all other tests involving user namespaces, see the comment here: https://github.com/golang/go/blob/62fb079e2b374d0e64f5432191f53cecd5282f6b/src/syscall/exec_linux_test.go#L80-L85

@LocutusOfBorg do you only see the issue inside a chroot or also outside?

**Comment by LocutusOfBorg** [comment]
@tklauser only inside chroots, Ubuntu builders can't build outside.

In my machine, and local builds are good

**Comment by tklauser** [comment]
@LocutusOfBorg thanks for confirming. Thus considering this fixed by https://golang.org/cl/196500 which skips `TestAmbientCapsUserns` in case of the test running in a chroot.

**Comment by LocutusOfBorg** [comment]
thanks!
I'll happily drop my patch on the next upstream release...
unfortunately that commit doesn't apply on top of the official 1.13 version, so I'll wait for the next tarball :)

**Comment by LocutusOfBorg** [comment]
Hello, we had a few golang 1.13 releases since 20 September, but none including this patch...

**Comment by ALTree** [comment]
@LocutusOfBorg we don't backport fixes to tests to minor releases. 

See: https://github.com/golang/go/wiki/MinorReleases
