### ISSUE TITLE
x/tools/gopls: autocomplete in comments

### ISSUE THREAD

**Issue by stamblerre** [golang/go#34010]
Suggest the name of the symbol when writing the beginning of a comment for an exported symbol. For example:

```go
// <>
var Foo int 
```

The above should offer a completion for `Foo`.

**Comment by KarthikNayak** [comment]
I want to pick this up, but I'm not familiar with the `gopls` codebase, so might take some time.

**Comment by stamblerre** [comment]
@KarthikNayak: The first place to look would be in https://github.com/golang/tools/blob/be0da057c5e3c2df569a2c25cd280149b7d7e7d0/internal/lsp/source/completion.go#L441. I would suggest making a separate function for autocompletion in comments and going from there. Feel free to reach out to me here or on the Gophers Slack if you have any questions on how to move forward with this.

**Comment by KarthikNayak** [comment]
@stamblerre Thanks for the heads up. I'll contact you if I need any clarifications!

**Comment by KarthikNayak** [comment]
@stamblerre I see that @clintjedwards has raised a PR for this, I'm glad he got to it before me!

**Comment by stamblerre** [comment]
@clintjedwards' PR added this for exported variables, but this still needs to be added for exported functions, constants, and types.

**Comment by danishprakash** [comment]
@stamblerre working on this

**Comment by clintjedwards** [comment]
Shouldn't be too bad, the code just checks for VAR type and then throws out the rest. Should be a few lines change at most, not counting tests ;)

Let me know if you have questions @danishprakash

**Comment by stamblerre** [comment]
@clintjedwards implemented the remaining changes for this in https://golang.org/cl/230215/. Closing this as a result. Thanks!
