### ISSUE TITLE
<a id="c5"></a>Comment 5:

### ISSUE THREAD

**Issue by els2520** [golang/go#34028]
<a id="c5"></a>Comment 5:

<pre>This facility is unix specific. Does not exists on Windows.
The client portion of this package could be useful, if someone on Windows wants to
report to syslog on another unix computer.
Alternatively, this could be a start for a general log package, that reports to "system"
log. But, I am not sure, it is a good time to start such development now.
Alex</pre>

_Originally posted by @alexbrainman in https://github.com/golang/go/issues/1108#issuecomment-66052624_

**Comment by ianlancetaylor** [comment]
This seems to be a repost of a seven year old comment on issue #1108.  I don't see a need for this to be a separate issue.  As #1108 says, we probably should not have put log/syslog in the standard library in the first place.
