### ISSUE TITLE
proxy.golang.org: Where is the source?

### ISSUE THREAD

**Issue by kaihendry** [golang/go#34029]
I noticed https://validator.nu/?doc=https%3A%2F%2Fproxy.golang.org%2F misses the DOCTYPE, but I'm unable to locate the source of https://proxy.golang.org/ to propose a trivial PR.

I'm genuinely interested in how it's run, e.g. k8s config et al. So could the source please be linked from https://{index,sum,proxy}.golang.org/

**Comment by aofei** [comment]
What I can tell you is that they are all closed source. So, I think you can only wait for the Go team to fix it. @andybons

**Comment by agnivade** [comment]
Russ' [response](https://groups.google.com/d/msg/golang-dev/go6_lZqew6g/bhKMbhlFDQAJ) to 
> When will proxy.golang.org be opened sourced (if at all)?

That server is not likely to be open-sourced directly. As you know from your work on Athens, of course, a basic module proxy is not a fundamentally complicated program. The vast majority of our code is dealing with various Google-internal serving infrastructure, not proxy details. It shells out to "go mod download" to get modules, same as Athens.

As part of working on proxy.golang.org, we've also been working on a more detailed description of expected proxy behavior (beyond 'go help goproxy'), and I expect we will release that document along with a very basic proxy of a couple hundred lines that others can adapt or use as a reference.

Best,
Russ
