### ISSUE TITLE
x/build: add builder for netbsd/arm64

### ISSUE THREAD

**Issue by bcmills** [golang/go#34036]
The [Go 1.13 release notes](https://github.com/golang/go/blob/b36a7a502a590bd9fbf7f73b9678ba58028acfde/doc/go1.13.html#L154-L158) currently claim that “Go now supports NetBSD on arm64.”

We have a [`host-netbsd-arm-bsiegert` builder](https://github.com/golang/build/blob/e21f1db94c01dcb5319146b4872dd11f0ce04a1a/dashboard/builders.go#L253-L258), but it isn't clear to me whether that is regular ARM or ARM64.

By last report (https://github.com/golang/go/issues/30824#issuecomment-502479334), the `netbsd/arm64` build may be broken.

We should either get a `netbsd/arm64` builder up and running and verify that it is passing, or remove the claim of support from the release notes.

CC @bsiegert @bradfitz @ianlancetaylor @andybons @toothrot @dmitshur

**Comment by bsiegert** [comment]
Sorry that this was not clearer. We do not, as a matter of fact, have a netbsd/arm64 builder. The netbsd-arm-bsiegert is arm, as the name says. Right now, binaries compiled on netbsd/arm64 die when they receive a signal, so we cannot sensibly run the go tool on it. Rest assured that I'll take care of a builder when we are at that point.

For now, removing arm64 from the release notes SGTM.

**Comment by bcmills** [comment]
Thanks for the confirmation!

**Comment by dmitshur** [comment]
@bsiegert I saw your [recent message](https://groups.google.com/d/msg/golang-dev/qtxOW0x4Rrw/Z_fH-Tn2AQAJ) on golang-dev. Let's use this as the tracking issue for the next steps. I can send you a builder key soon (on Monday).

/cc @cagedmantis Issue #36841 may be relevant here. Please let us know if you think it would be viable to have a non-reverse builder for NetBSD ARM64. I think we can proceed with a reverse builder for now, but if a non-reserve builder becomes possible/easy in the future, let's evaluate that option too.

**Comment by dmitshur** [comment]
I've provided a builder key to @bsiegert. Benny, please update this issue and/or ping me when you're ready to take the next steps here.

**Comment by cagedmantis** [comment]
@bsiegert @dmitshur a non-reverse builder for NetBSD ARM64 is on the roadmap for the near future (next few weeks). There is no need to delay this any further by waiting for that builder to go online.

**Comment by bsiegert** [comment]
@cagedmantis I am excited to hear about the non-reverse arm64 builder! There does not need to be any waiting involved; we can have both builders for the time being, and I'll happily decommission the reverse builder.

@dmitshur provided a key, and I have the builder running right now. I will send a CL to add it to the coordinator.

**Comment by bsiegert** [comment]
@cagedmantis How is the non-reverse builder coming along? Anything I can do to help?

**Comment by dmitshur** [comment]
I don't believe there are active plans to pursue a non-reverse netbsd/arm64 builder now, and a newer reverse builder for LUCI was added: https://ci.chromium.org/ui/p/golang/builders/luci.golang.ci/gotip-netbsd-arm64. Closing this in favor of the newer issue #63614.
