### ISSUE TITLE
proxy.golang.org: @v/list includes versions with no corresponding .info file

### ISSUE THREAD

**Issue by aofei** [golang/go#34033]
The https://proxy.golang.org/gopkg.in/jcmturner/rpc.v1/@v/list is now printing:

```
v1.0.0
v1.1.0
v1.1.1
```

But in fact this module doesn't contain the `v1.1.1` revision (see [this](https://gopkg.in/jcmturner/rpc.v1) and [this](https://github.com/jcmturner/rpc/releases)). Or maybe it existed before but was deleted by the author after being cached by the [proxy.golang.org](https://proxy.golang.org).

This caused a problem: I can't pass the following command:

```bash
$ GOPROXY=https://proxy.golang.org go get -u github.com/jinzhu/gorm
...
go get: upgrading gopkg.in/jcmturner/rpc.v1@v1.1.0: unexpected status (https://proxy.golang.org/gopkg.in/jcmturner/rpc.v1/@v/v1.1.1.info): 410 Gone
...
```

Therefore, I recommend that the [proxy.golang.org](https://proxy.golang.org) should only cache the results of the `/<module>/@v/<version>.info`, `/<module>/@v/<version>.mod`, and `/<module>/@v/<version>.zip` into the storage. Both of the `/<module>/@latest` and `/<module>/@v/list` should only be cached by the CDN and the backend should refresh the results (regenerate from the module's source) every time the CDN back-to-source.

cc @andybons

**Comment by bcmills** [comment]
CC @katiehockman @hyangah @heschik

**Comment by katiehockman** [comment]
Thanks for reporting the issue. I think you're right in your assumptions. It looks like gopkg.in/jcmturner/rpc.v1 had a version 1.1.1 tag, proxy.golang.org picked it up, then the tag was removed and proxy.golang.org is continuing to serve that version from list.

What we'll probably end up doing is serving a combination of cached module versions (ie. versions with zips that are currently being served through proxy.golang.org) and new list results, which would prevent /list from including versions like this one.

**Comment by heschik** [comment]
This should now be fixed. Please let us know if you see any further problems.
