### ISSUE TITLE
x/tools/gopls: make sure gopherbot doesn't add comment to issues filed with `gopls bug`

### ISSUE THREAD

**Issue by stamblerre** [golang/go#34042]
Forked from https://github.com/golang/go/issues/34011.

**Comment by zikaeroh** [comment]
I'm not sure if this is entirely related, but `gopls bug` prefills the title with `gopls:`, but all of the current issues seem to use `x/tools/gopls:` as the prefix.

**Comment by stamblerre** [comment]
We've stopped adding the automatic comment, so this is no longer relevant.
