### ISSUE TITLE
cmd/go: replace directive for "latest" is replaced with latest version

### ISSUE THREAD

**Issue by fastest963** [golang/go#34044]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.13
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

1. Added:
```replace gerrit.levenlabs.com/ctxtime => gerrit.levenlabs.com/ctxtime latest```
to my `go.mod` file.
2. Run `go get`

### What did you expect to see?
I expected it to leave `latest` in replace line so that the latest version is always fetched when `go get` is run. Ideally we can commit `latest` and when CI runs and calls `go get` it'll always get the latest version of this particular module (which is an internal/private module). Additionally, when developers run `go get` they also get the latest version of that module and when they run `go get -u` the `go.mod` file won't be changed to remove the `latest` directive.

### What did you see instead?
When `go mod tidy` or `go get` is run, the `latest` is replaced with the latest version at that time.

**Comment by katiehockman** [comment]
This is intentional behavior as described in https://golang.org/cmd/go/#hdr-The_go_mod_file. It's important that go.mod files only have versions in semver form to have reproducible builds for other modules that may depend on it.

**Comment by katiehockman** [comment]
I also recommend checking out https://github.com/golang/go/wiki/Questions (and specifically the #modules slack).
