### ISSUE TITLE
cmd/go: Module mode doesn't turn on automatically while build upon relative path

### ISSUE THREAD

**Issue by JBrVJxsc** [golang/go#34043]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/FOOBAR/Library/Caches/go-build"
GOENV="/Users/FOOBAR/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/FOOBAR/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gs/5npvnn7x1s75tnbcx020t_yr000r7f/T/go-build967562719=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
`go mod init` // convert the project to the module-based
`go build ./src/cli/project/"` // from a relative directory. `./src/cli/project` isn't in `GOPATH` (that's why I'm using module).

### What did you expect to see?
It should build successfully via module mode.
(If `go build` directly in the project folder it will detect the `go.mod` file and use module mode to build successfully)
### What did you see instead?
src/cli/project/main.go:4:2: cannot find package "project/cmd" in any of:
        /usr/local/go/src/project/cmd (from $GOROOT)
        /Users/FOOBAR/go/src/project/cmd (from $GOPATH)

**Comment by bcmills** [comment]
Please provide concrete steps to reproduce the problem. Specifically, please provide the _exact_ commands run, including any `cd` commands, and a minimal set of source files.

Note that the `go` command locates the `go.mod` file based on its current working directory, _not_ on the directory containing the requested packages — if the `go.mod` file is in a subdirectory of the current working directory, then the `go` command will not be able to locate it.

**Comment by MHBauer** [comment]
> Note that the `go` command locates the `go.mod` file based on its current working directory, _not_ on the directory containing the requested packages — if the `go.mod` file is in a subdirectory of the current working directory, then the `go` command will not be able to locate it.

My understanding reading this is: I must call `go build` in the directory containing the `go.mod` file. Is this in the documentation somewhere? 

This is surprising to me. Is there a flag to give to `go build` so it does a `cd` into the directory before running?

**Comment by bcmills** [comment]
> I must call `go build` in the directory containing the `go.mod` file. Is this in the documentation somewhere?

https://golang.org/cmd/go/#hdr-The_main_module_and_the_build_list

> Is there a flag to give to `go build` so it does a `cd` into the directory before running?

No. (The argument to `go build` is, strictly speaking, a package path, not a directory.)
