### ISSUE TITLE
spec: minor bug relating to changes made for shifts

### ISSUE THREAD

**Issue by GaneshRapolu** [golang/go#34056]
### Does this issue reproduce with the latest release?
Yes (Go 1.13).

### What did you do?

Read the latest go language specification at https://golang.org/ref/spec#Arithmetic_operators

### What did you expect to see?

The shift operators shift the left operand by the shift count specified by the right operand, which must be **non-negative**.

### What did you see instead?

The shift operators shift the left operand by the shift count specified by the right operand, which must be **positive**.

This language was added as part of a10b4cff91cb5d26e2049f6efc20349aa4d50d20, which modified the spec to reflect the shift changes made in go 1.13. It is trivially wrong: it disallows shifts by zero.

**Comment by griesemer** [comment]
Fair enough. It appears that whether zero is considered positive depends on where you're coming from...

"non-negative" avoids the ambiguity. Will fix.
