### ISSUE TITLE
doc: errors: wrong unwrap example

### ISSUE THREAD

**Issue by minaevmike** [golang/go#34061]
### What version of Go are you using (`go version`)?

<pre>
go 1.13

</pre>

Documentation provides this example of `Unwrap` call https://github.com/golang/go/blob/master/src/errors/errors.go#L19. But this example wont work because `fmt.Errorf` returned `error` interface https://play.golang.org/p/KaQv-yJl6yy

**Comment by hartzell** [comment]
Perhaps the example should be 

```go
errors.Unwrap(fmt.Errorf("... %w ...", ..., err, ...))
```

**Comment by jba** [comment]
Yes, it was me, and the given fix is correct. I'll make a CL.

**Comment by jba** [comment]
@gopherbot please backport 1.13
