### ISSUE TITLE
ARM 1.13: readunalign redeclared, duplicate symbols

### ISSUE THREAD

**Issue by wti** [golang/go#34064]
Two glitches installing 1.13/arm on Raspbian/arm7 (PI-4):

1. `unaligned2.go:12:6: readUnaligned32 redeclared`: "solved" by commenting out duplicate

2. Duplicate symbol (`Acos`): unable to debug/solve.  (As a workaround, Is it possible (or safe) to set the loader flag (`StrictDupsWarnFlag`) to warn instead of die?)

Details below.  Apologies if this is misconfiguration.  I wonder if the '+build' flags are working right, if the build/source assembly steps are broken, or if there were commits merged over.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/arm
</pre>

### Does this issue reproduce with the latest release?
Yes, using `go1.13.linux-armv6l.tar.gz`.

Rough install steps before getting to the duplicate symbols (in case they are in error):

1. tar xf to `/usr/local` as usual
2. Define temp dir: `go env -w GOTMPDIR=$HOME/tempgo`
3. `go build` reported buildutil missing, so `go get golang.org/x/tools/go/buildutil`, got readUnaligned error (see below)
4. Comment out redeclared readUnaligned[32|64], so go-get and go build produces the duplicate-symbol error.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm"
GOBIN=""
GOCACHE="${HOME}/.cache/go-build"
GOENV="${HOME}/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="${HOME}/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR="${HOME}/tempgo"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6" # also tried 7
AR="ar"
CC="gcc"
CXX="c++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=${HOME}/tempgo/go-build270506164=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.13 linux/arm
GOROOT/bin/go tool compile -V: compile version go1.13
uname -v: #1245 SMP Fri Jul 12 17:31:45 BST 2019
uname -a: Linux [machine] 4.19.58-v7l+ #1245 SMP Fri Jul 12 17:31:45 BST 2019 armv7l GNU/Linux
</pre></details>

### What did you do?
Same result compiling my code or yours, or this program:

```go
package main

import ( "math")

func main() {
    if 0 < math.Acos(.5) {
        panic("correct!")
    }
}
```

### What did you expect to see?
`panic: correct!`

### What did you see instead?

```
2019/09/03 23:51:15 duplicate symbol math.Acos (types 1 and 1) in math and ${HOME}/.cache/go-build/12/12922fad69ac95432e97258bda1b1585274fb2aa40b439b006399ab19f1a293b-d(stubs_arm.o)
```

Note: same result after removing `${HOME}/.cache/go-build/` and `${HOME}/tempgo/*` to force rebuild.

Message `duplicate symbol... (types ...)` is from objfile.go:
```
$ cd /usr/local/go/src
$ grep 'duplicate symbol' $(find . -type f -name \*.go) | sed -n /types/p
./cmd/link/internal/objfile/objfile.go:         log.Fatalf("duplicate symbol %s (types %d and %d) in %s and %s", s.Name, s.Type, t, s.File, r.pn)
```
Using `go build -x -v hello.go`, it appears this happens after building math, when loading another package.  
```
## create b015/ space (line:87), build math there (line:105)
  87 mkdir -p $WORK/b015/

  94 cat >$WORK/b015/go_asm.h << 'EOF' # internal
  95 EOF
  96 cd /usr/local/go/src/math
  97 /usr/local/go/pkg/tool/linux_arm/asm -trimpath "$WORK/b015=>" -I $WORK/b015/ -I /usr/local/go/pkg/include -D GOOS_linux -D GOARCH_arm -gensymabis -o $WORK/b015/symabis ./asinh_stub.s ./cbrt_stub.s ./erf_stub.s ./pow_stub.s ./sinh_stub.s ./sqrt_arm.s ./stubs_arm.s ./tan_arm.s

 100 cat >$WORK/b015/importcfg << 'EOF' # internal
 101 # import config
 102 packagefile math/bits=$WORK/b016/_pkg_.a
 103 EOF
 104 cd /usr/local/go/src/math
 105 /usr/local/go/pkg/tool/linux_arm/compile -o $WORK/b015/_pkg_.a -trimpath "$WORK/b015=>" -p math -std -buildid wu3qd3hKoUFoFoXYmAc5/wu3qd3hKoUFoFoXYmAc5 -goversion go1.13 -symabis $WORK/b015/symabis -D "" -importcfg $WORK/b015/importcfg -pack -asmhdr $WORK/b015/go_asm.h -c=4 ./abs.go ./acosh.go ./asin.go ./asinh.go ./atan.go ./atan2.go ./atanh.go ./bits.go ./cbrt.go ./const.go ./copysign.go ./dim.go ./erf.go ./erfinv.go ./exp.go ./expm1.go ./floor.go ./frexp.go ./gamma.go ./hypot.go ./j0.go ./j1.go ./jn.go ./ldexp.go ./lgamma.go ./log.go ./log10.go ./log1p.go ./logb.go ./mod.go ./modf.go ./nextafter.go ./pow.go ./pow10.go ./remainder.go ./signbit.go ./sin.go ./sincos.go ./sinh.go ./sqrt.go ./tan.go ./tanh.go ./trig_reduce.go ./unsafe.go

## + stubs
 241 cd /usr/local/go/src/math
 248 /usr/local/go/pkg/tool/linux_arm/asm -trimpath "$WORK/b015=>" -I $WORK/b015/ -I /usr/local/go/pkg/include -D GOOS_linux -D GOARCH_arm -o $WORK/b015/stubs_arm.o ./stubs_arm.s
  
 252 /usr/local/go/pkg/tool/linux_arm/pack r $WORK/b015/_pkg_.a $WORK/b015/asinh_stub.o $WORK/b015/cbrt_stub.o $WORK/b015/erf_stub.o $WORK/b015/pow_stub.o $WORK/b015/sinh_stub.o $WORK/b015/sqrt_arm.o $WORK/b0
 253 /usr/local/go/pkg/tool/linux_arm/buildid -w $WORK/b015/_pkg_.a # internal

## detect duplicates
 978 cd /usr/local/go/src/go/scanner 
 979 /usr/local/go/pkg/tool/linux_arm/compile -o $WORK/b061/_pkg_.a -trimpath "$WORK/b061=>" -p go/scanner -std -complete -buildid cJNf_nnBE7XiKYX5kpa2/cJNf_nnBE7XiKYX5kpa2 -goversion go1.13 -D "" -importcfg
 980 /usr/local/go/pkg/tool/linux_arm/buildid -w $WORK/b048/_pkg_.a # internal

 982 2019/09/04 01:27:49 duplicate symbol math.Acosh (types 1 and 1) in math and $WORK/b015/_pkg_.a(stubs_arm.o)
```

## Possible cause: files not removed after consolidating stubs?
- [commit to remove dups](https://go.googlesource.com/go/+/f0fdbb1e8ba44da536050329050424b7b555aecb)
- [Apr 23 math stubs consolidated](https://go-review.googlesource.com/c/go/+/173398/)

These commits appear to remove the .s files (including the asin_arm.s with the Acos symbol), but they still exist in the arm distribution.  However, this may be a red herring since removing them does not solve the problem.

## Initial issue `go get` for `buildutil` reporting readUnaligned[32|64] redeclared

```
tools $ go get golang.org/x/tools/go/buildutil
# runtime
/usr/local/go/src/runtime/unaligned2.go:12:6: readUnaligned32 redeclared in this block
    previous declaration at /usr/local/go/src/runtime/alg.go:321:40
/usr/local/go/src/runtime/unaligned2.go:17:6: readUnaligned64 redeclared in this block
    previous declaration at /usr/local/go/src/runtime/alg.go:329:40
```

Solution: commented out declaration in `alg.go` in favor of arm-specific code in `unaligned2.go`.

## Variants tried for duplicate symbols issue; OS detail
- With and without GO111MODULE
- Using 6 or 7 as GOARM value (go distribution indicates 6, but `uname` reports `arm7l`).  
- fyi, although Raspberry PI-4 is a 64-bit processor (BCM2711 is an Arm A72), Raspbian is a 32-bit OS.
- I have tried wiping $GOROOT and re-installing - same result.

**Comment by ALTree** [comment]
> These commits appear to remove the .s files (including the asin_arm.s with the Acos symbol), but **they still exist in the arm distribution.**

Where are they? I unpacked go1.13.linux-armv6l.tar.gz from https://golang.org/dl/ on my pc, there is not `asin_arm.s` file in the archive. If you see a `asin_arm.s` in your /url/local/go/src/math/ dir, you borked the installation in some way and you now have a weird hybrid of 1.12 and 1.13.

**Comment by wti** [comment]
Sorry, not a bug - confirmed pilot error.
