### ISSUE TITLE
cmd/go: go mod import package can't find out the package which include capital letter

### ISSUE THREAD

**Issue by sunvim** [golang/go#34074]
like title, now returned 1.12.9 version, and it's not a problem any more
### What version of Go are you using (`go version`)?
<pre>
$ go version

</pre>
go 1.13
### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?
linux  amd64  ubuntu 18.04
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

action:   go mod tidy -v
output:
github.com/Microsoft/go-winio: cannot find module providing package github.com/Microsoft/go-winio

### What did you expect to see?

Fetching https://goproxy.io/github.com/%21microsoft/go-winio/@v/list
Fetching https://goproxy.io/github.com/%21microsoft/@v/list

**Comment by bcmills** [comment]
Please fill out the complete issue template. What command did you run, with what source files? What did you expect to see, and what did you actually see?

**Comment by sunvim** [comment]
> Please fill out the complete issue template. What command did you run, with what source files? What did you expect to see, and what did you actually see?

update

**Comment by bcmills** [comment]
The module appears to be missing from `goproxy.io` for some reason. You'll need to take that up with them.

Note that Go 1.13 supports fallback to direct origins for modules that are not provided by the selected proxy. If you are currently setting

```
GOPROXY=https://goproxy.io
```

then with Go 1.13 you could try setting

```
GOPROXY=https://goproxy.io,direct
```

instead.

----

With Go 1.12, you may need to temporarily set `GOPROXY=direct` long enough to populate your local cache:
```
GOPROXY=direct go mod tidy
```

**Comment by bcmills** [comment]
Closing, since the issue does not appear to be within the `go` toolchain.

**Comment by oiooj** [comment]
@sunvim Fixed, Thanks for your report.
