### ISSUE TITLE
cmd/go: 'go test' adds test.timeout flag after positional arguments

### ISSUE THREAD

**Issue by juliusmh** [golang/go#34072]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/juliusmh/.cache/go-build"
GOENV="/home/juliusmh/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/juliusmh/go/"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build898241332=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
In a module test we have named flags as well as positional arguments. When we run the tests using `go test ... -flag 1 positional` the `-test.timeout` is appended resulting in `go test ... -flag 1 positional -test.timeout=10m`. Flags after positional arguments are not parsed anymore which makes `-test.timeout=10m` a positional argument as well.

### What did you expect to see?
The tests should run as in 1.12, no timeout flag specified.

### What did you see instead?
The timeout flag `-test.timeout=10m` was not parsed correctly but ends up as a positional argument.

### Possible fix?
Add the `-test.timeout=10m` flag at the very beginning, making it immune to breaking positional arguments. Updated docs mentioning that behavior would be highly appreciated too. The line causing that behavior is [/src/cmd/go/internal/test/test.go](https://github.com/golang/go/blob/release-branch.go1.13/src/cmd/go/internal/test/test.go#L576).

**Comment by bcmills** [comment]
@gopherbot, please backport to Go 1.13: this is a regression and the fix is trivial.

**Comment by mjl-** [comment]
To run tests with go1.13 add "-timeout 0" to prevent the -test.timeout flag from being appended:

> go1.13 test -timeout 0 -args ...
