### ISSUE TITLE
x/build/app/appengine: automatically hide and stop testing old versions

### ISSUE THREAD

**Issue by dmitshur** [golang/go#34097]
We make a change like [CL 193477](https://golang.org/cl/193477) every 6 months. It's usually a one line diff, but it still needs to be remembered, made, reviewed, and deployed each time.

Maybe it's time we automate it to reduce the amount of manual work to be done for each release.

By now, we have an endpoint [`MaintnerServiceClient.ListGoReleases`](https://godoc.org/golang.org/x/build/maintner/maintnerd/apipb#MaintnerServiceClient) that we can use to do this more easily. E.g.:

```
$ go run golang.org/x/build/maintner/maintq list-releases
major:1 minor:13 [...]
major:1 minor:12 [...]
```

/cc @golang/osp-team

**Comment by bradfitz** [comment]
We don't really even need to make an RPC.

It already reads from the datastore first and then uses that map to filter. We could just encode the policy into the dashboard instead (last two releases) and not list out what the last two releases are. We have the various branch/version parsing code now too, which makes it easier.
