### ISSUE TITLE
proxy is failing for newly-created modules

### ISSUE THREAD

**Issue by jadekler** [golang/go#34090]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13beta1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

I assume so.

### What did you do?

```
deklerk at deklerk-macbookpro2 in ~/workspace/google-cloud-go/firestore on firestore_carveout*
$ go mod tidy
go: finding cloud.google.com/go v0.45.1
everifying cloud.google.com/go@v0.45.1/go.mod: cloud.google.com/go@v0.45.1/go.mod: reading https://sum.golang.org/lookup/cloud.google.com/go@v0.45.1: 410 Gone
deklerk at deklerk-macbookpro2 in ~/workspace/google-cloud-go/firestore on firestore_carveout*
$ echo $?
1
```

### What did you expect to see?

Proxy fails to fetch a recently-released version of our module.

### What did you see instead?

Proxy should go fetch it if it doesn't know about it. It certainly does exist: https://github.com/googleapis/google-cloud-go/releases/tag/v0.45.1

**Comment by hyangah** [comment]
I am not sure if that's the upstream issue (Go module mirror shells out 'go mod download' and it doesn't provide any more details). The module mirror indicated it tried to fetch the version multiple times but couldn't for a while. Finally it managed to access the origin at 14:25:59 and it's available.

https://proxy.golang.org/cloud.google.com/go/@v/v0.45.1.info
https://sum.golang.org/lookup/cloud.google.com/go@v0.45.1
