### ISSUE TITLE
os/user: Lookup() function doesn't work in 32 bit executables

### ISSUE THREAD

**Issue by thebatvic** [golang/go#34099]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.13
</pre>

### Does this issue reproduce with the latest release?
Yes, this issue reproduce with the latest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/local/ZOHOCORP/vignesh-pt3070/.cache/go-build"
GOENV="/home/local/ZOHOCORP/vignesh-pt3070/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/vignesh-pt3070/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build184156317=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I have used user.Lookup(<username>) function in my code to find a user in a machine, when i run the program as a 64 bit executable, it could find users from both the machine and the active directory but when i run it as a 32 bit executable, it couldn't find users in active directory.

You can see my code here...
https://play.golang.org/p/U94tx8ZY1lp

### What did you expect to see?
In both compilation, i want to see users from both machine and active directory

### What did you see instead?
Only on 64 bit compilation, i could see users in both machine and active directory. On 32 bit compilation i could see users only in the machine.

I have attached output for the code, 

64 Bit compilation
![64bitcompilation](https://user-images.githubusercontent.com/31430905/64314748-b4cba100-cfcd-11e9-884d-d7ece143ef6e.png)

32 Bit compilation
![32bitcompilation](https://user-images.githubusercontent.com/31430905/64314769-c745da80-cfcd-11e9-9873-f15a77a1c2dd.png)

**Comment by bradfitz** [comment]
Cgo is disabled by default when cross compiling. Set CGO_ENABLED=1 explicitly when cross compiling. You'll likely need some extra C packages installed on your machine.

**Comment by thebatvic** [comment]
> Cgo is disabled by default when cross compiling. Set CGO_ENABLED=1 explicitly when cross compiling. You'll likely need some extra C packages installed on your machine.

I tried as per you said, Thanks for the info.
Also sorry for not analyzing the issue deeply and creating a issue.
