### ISSUE TITLE
crypto/elliptic: handle compressed formats in new MarshalCompressed, UnmarshalCompressed

### ISSUE THREAD

**Issue by roman-khimov** [golang/go#34105]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.9 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
I think so.

### What operating system and processor architecture are you using (`go env`)?
play.golang.org

### What did you do?
https://play.golang.org/p/ugkQeobnYRP

### What did you expect to see?
Successful unmarshaling.

### What did you see instead?
Failed unmarshaling.

### The real problem
`elliptic.Unmarshal()` only supports uncompressed format (prefix `0x04`) at the moment, as can be seen [in the source code](https://golang.org/src/crypto/elliptic/elliptic.go?s=8747:8803#L312), which probably is fine given that it's supposed to be a companion for `elliptic.Marshal()` that only uses that format to serialize the point. But at the same time it would be very nice to have support for compressed (prefixes `0x02` and `0x03`) format that is being used in the wild, it doesn't cost much in terms of code (there is a [nice snippet on SO](https://stackoverflow.com/questions/46283760)) and this proposed change is certainly backwards-compatible. At the moment I see this (or similar) code being duplicated by several projects that use compressed format, thus this issue.

Of course it would be very nice if `elliptic` could also serialize into this format, but that's a bit more complicated, because you can't change `Marshal()` without breaking backwards compatibility (the only option I see at the moment is introducing another function like `MarshalCompressed()`).

**Comment by im-kulikov** [comment]
```
func Unmarshal(curve elliptic.Curve, data []byte) (x, y *big.Int) {
	byteLen := (curve.Params().BitSize + 7) >> 3
	if len(data) != 1+2*byteLen {
		return
	}

	switch prefix := data[0]; prefix {
	case 0x2, 0x3:
		x = new(big.Int).SetBytes(data[1 : 1+byteLen])

		// y² = x³ - 3x + b
		x3 := new(big.Int).Mul(x, x)
		x3.Mul(x3, x)

		threeX := new(big.Int).Lsh(x, 1)
		threeX.Add(threeX, x)

		x3.Sub(x3, threeX)
		x3.Add(x3, curve.Params().B)
		x3.Mod(x3, curve.Params().P)

		// y = √(x³ - 3x + b) mod p
		y = new(big.Int).ModSqrt(x3, curve.Params().P)

		// big.Int.Jacobi(a, b) can return nil
		if y == nil {
			return nil, nil
		} else if y.Bit(0) == uint(prefix & 0x1) {
			y.Neg(y)
			y.Mod(y, curve.Params().P)
		}
	case 0x4:
		p := curve.Params().P
		x = new(big.Int).SetBytes(data[1 : 1+byteLen])
		y = new(big.Int).SetBytes(data[1+byteLen:])
		if x.Cmp(p) >= 0 || y.Cmp(p) >= 0 {
			return nil, nil
		}
		if !curve.IsOnCurve(x, y) {
			return nil, nil
		}

	default:
		return nil, nil
	}

	return
}
```

**Comment by im-kulikov** [comment]
and marshal compressed, can be implemented very simple:

```go
func MarshalCompressed(curve elliptic.Curve, x, y *big.Int) []byte {
	byteLen := (curve.Params().BitSize + 7) >> 3

	ret := make([]byte, 1+byteLen)

	// compressed point:
	ret[0] = 3
	if y.Bit(0) == 0 {
		ret[0] = 2
	}
	
	copy(ret[1:], x.Bytes())
	
	return ret
}
```

**Comment by FiloSottile** [comment]
Can you provide some examples of projects that had to implement this? If it's indeed common, I'd support implementing it.

**Comment by im-kulikov** [comment]
> Can you provide some examples of projects that had to implement this? If it's indeed common, I'd support implementing it.

- https://github.com/nspcc-dev/neo-go
- https://github.com/nspcc-dev/neofs-crypto
- https://github.com/btcsuite/btcd
- etc

**Comment by katiehockman** [comment]
Supporting compressed formats in `elliptic.Unmarshal()` would break the backwards compatibility rule, since the [docs](https://pkg.go.dev/crypto/elliptic?tab=doc#Marshal) say
> It is an error if the point is not in uncompressed form or is not on the curve.

In order to support this, we could add two new functions to the `elliptic` package:

```
func MarshalCompressed(curve Curve, x, y *big.Int) []byte
func UnmarshalCompressed(curve Curve, data []byte) (x, y *big.Int)
```

**Comment by rsc** [comment]
Adding to proposal minutes, seems headed for likely accept.

**Comment by im-kulikov** [comment]
updated PR

MarshalCompressed implemented as specified in section 4.3.6 (2. compressed form) of ANSI X9.62

**Comment by rsc** [comment]
Based on the discussion above and the specific retitling of adding new functions instead of overloading the existing ones, this seems like a **likely accept**.

**Comment by rsc** [comment]
No change in consensus, so accepted.
