### ISSUE TITLE
x/tools/cmd/goimports: doesn't traverse hidden files (dotfiles)

### ISSUE THREAD

**Issue by preslavmihaylov** [golang/go#34100]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.9 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/pmihaylov/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/pmihaylov/programming/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.9/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.9/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9v/vvj1r6_54pb855bvmtqv3wn80000gn/T/go-build618023056=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

In a go project: 
 1. Create the file `.gen/foo/foo.go` with contents:
```go
package foo

import "fmt"

func Foo() {
	fmt.Println("Foo")
}
```

2. Create the file `bar/bar.go` with contents:
```go
package bar

import "fmt"

func Bar() {
	fmt.Println("Bar")
}
```

3. Create the file `main.go` with contents:
```go
package main

func main() {
	foo.Foo()
	bar.Bar()
}
```

4. Run `goimports main.go`.

### What did you expect to see?
Both `foo` and `bar` packages included

### What did you see instead?
Only `bar` package was included

It would be great if goimports traverses hidden directories as we use a `.gen` folder for storing auto-generated code (e.g. protobuf). Or at least to export a flag that enables this feature.

From a little tweaking, it seems that Intellij and GoLand already support this feature and that doesn't come from the integrated `goimports`.

NOTE: If I add the import manually, the program compiles.

**Comment by heschik** [comment]
Clearly `goimports` shouldn't enter VCS directories like `.git`, `.hg`, etc. So allowing all hidden directories isn't viable. That means having a list of directories to avoid or enter, and that means configuration, which I don't think is justified for a use case this niche.

Is it so annoying to rename the directory to `gen` instead of `.gen` and have it appear in directory listings?

**Comment by preslavmihaylov** [comment]
Well, it’s hard to change company-wide standards (Uber).

**Comment by bradfitz** [comment]
Sorry, this is not a configuration knob I want to add.

Corporations with their own opinions can have their own internal goimports binary available to their employes. (Google does, for instance, for misc reasons)

**Comment by preslavmihaylov** [comment]
Alright, fair enough.

In case anyone else has this or a similar issue, here is what I did to create a custom binary that works for me:
 1. Open `$GOPATH/src/golang.org/x/tools/internal/gopathwalk/walk.go`. Download the sources first if you don't have them (`go get ...`)
 2. Change this line https://github.com/golang/tools/blob/5b82db07426dbac2c94df2e3a85e83f3026c088c/internal/gopathwalk/walk.go#L198 the way you prefer.
 3. Recompile `goimports` with `go build goimports.go goimports_not_gc.go` in `$GOPATH/src/golang.org/x/tools/cmd/goimports`

**Comment by agnivade** [comment]
Sounds like this is resolved. Is there anything else you wanted to be done on this issue ?

**Comment by preslavmihaylov** [comment]
Nope, that’s all folks.
