### ISSUE TITLE
proxy.golang.org: what about download stats?

### ISSUE THREAD

**Issue by antonmedv** [golang/go#34106]
What about download stats? Before it was able to use GitHub Insight to see clone stats.

**Comment by aofei** [comment]
See this: https://twitter.com/belbaoverhill/status/1169251559085092864

**Comment by mvdan** [comment]
What @aofei said. GitHub download stats were equally skewed, because most users would be either caching or vendoring.

Maybe @katiehockman wants to disagree here, but I'm going to assume she won't :)

**Comment by katiehockman** [comment]
Agree with @mvdan and @aofei.
It is something that we're considering though, and something that we'd like to provide publicly should we have good statistics to share in the future. The module discovery site (led by @julieqiu) will be providing popularity data which you may find insightful, too. https://github.com/golang/go/issues/33654 is the tracking issue for that project.
