### ISSUE TITLE
[bug?] Strange error with cgo and cc1 on raspberry pi

### ISSUE THREAD

**Issue by TheButlah** [golang/go#34109]
This bug prevents me from compiling my code as it depends on several libraries that exhibit this bug (they never exhibited the behavior before, I recently reinstalled go).

Sorry in advance if its not a bug - I suppose its possible that its because I'm using armv6l on an armv7l OS on an armv8l CPU, but my understanding was that that would be perfectly fine. Maybe I'm wrong?

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/arm
</pre>

### Does this issue reproduce with the latest release?
Yes, reproduces with `go1.13.linux-armv6l.tar.gz` and `go1.12.9.linux-armv6l.tar.gz`

### What operating system and processor architecture are you using (`go env`)?
Running Raspberry pi 4, armv7l (32bit os on 64 bit armv8l CPU)
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm"
GOBIN=""
GOCACHE="/home/ryan/.cache/go-build"
GOENV="/home/ryan/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ryan/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/opt/huggable.us/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build988274220=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
`go get -u -v github.com/urfave/cli...` or `go get -u -v golang.org/x/text/internal...` or `go get -u -v golang.org/x/crypto...`

### What did you expect to see?
Successfully `go get` the package

### What did you see instead?
In the case of `go get -u -v github.com/urfave/cli...` I saw:
```
github.com/urfave/cli (download)
github.com/cpuguy83/go-md2man (download)
github.com/BurntSushi/toml (download)
get "gopkg.in/yaml.v2": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at //gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)
runtime/cgo
# runtime/cgo
gcc: error trying to exec 'cc1': execvp: No such file or directory
```
Last three lines define the error in question, occur in all cases.

**Comment by agnivade** [comment]
Looks like you don't have the build toolchain installed. The top google hit gives https://stackoverflow.com/questions/11912878/gcc-error-gcc-error-trying-to-exec-cc1-execvp-no-such-file-or-directory. 

Please try that and let us know.

**Comment by TheButlah** [comment]
I already looked at that. I've tried all manner of updating build-essentials and manually installing gcc and g++. Beyond that I'm not knowledgeable enough to diagnose the issue further.

**Comment by ianlancetaylor** [comment]
As @agnivade said it looks like there is something wrong with your GCC installation.  What happens if you compile a simple C file?

**Comment by TheButlah** [comment]
Yep I'm dumb, compiling a basic hello world c file fails with the same execve error. Not sure whats wrong with my setup. Will update if it ends up being something relevant to go in particular.
