### ISSUE TITLE
[mod]Go get private repository

### ISSUE THREAD

**Issue by PxyUp** [golang/go#34112]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Create a private git package, and try to go get "package-url"

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/Users/pyxru/go/bin"
GOCACHE="/Users/pyxru/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/pyxru/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n2/cn3vkdtd1slbxs9mpcdnnvfw0000gn/T/go-build863878618=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you expect to see?

I expect download mod via git protocol

### What did you see instead?

The error message, because it is used https

**Comment by aofei** [comment]
Have you tried this: https://golang.org/doc/faq#git_https?

BTW, your `go env` output doesn't look like it was printed by Go 1.13.

**Comment by bcmills** [comment]
Please fill out the complete issue template. What did you actually do?

* Where/how is the private git repo hosted? (In particular, what [`<meta>` tags](https://tip.golang.org/cmd/go/#hdr-Remote_import_paths) does it serve for your import path, and do the URLs in those tags indicate the appropriate protocol?)
* How do you authenticate to that host? (Do you expect to authenticate using SSH, or using HTTPS? Do you store your credentials in a Git credential store, a `.netrc` file, or both?)

**Comment by PxyUp** [comment]
`go env -w GOPRIVATE=` that command was help
