### ISSUE TITLE
x/tools/gopls: pre-warm the cache for imports

### ISSUE THREAD

**Issue by stamblerre** [golang/go#34115]
Original conversation in https://github.com/golang/go/issues/32750#issuecomment-523141204.

**Comment by myitcv** [comment]
@heschik I haven't been following all the recent conversations about `goimports` closely, but is this in effect already done?

**Comment by heschik** [comment]
Not really, but it's probably moot now. Closing in favor of all the stuff I did for https://golang.org/issue/36222.
