### ISSUE TITLE
cmd/go: "unrecognized import path" for local packages after updating to go1.13

### ISSUE THREAD

**Issue by nichoriverae** [golang/go#34117]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
$ go env

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nrivera/Library/Caches/go-build"
GOENV="/Users/nrivera/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/nrivera/go"
GOPRIVATE=""
GOPROXY="off"
GOROOT="/usr/local/Cellar/go/1.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sf/74kcmjp94lzc1567ysxwb0z15rwk9k/T/go-build433853316=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I attempted to go run an application as before, but ran into an unrecognized import path error. Previously with 1.12 I did not have an issue. These are imports from sub packages within a main package.

running
`go get -u ./...`
returns:
`package _/*/src: unrecognized import path "_/*/src" (import path does not begin with hostname) `

### What did you expect to see?

That local packages don't need a hostname, and they don't fail to "get".

### What did you see instead?

`"import path does not begin with hostname"`

**Comment by bcmills** [comment]
That error message comes from here:
https://github.com/golang/go/blob/aae0b5b0b26bf4fd26cad0111535d703691a9083/src/cmd/go/internal/get/vcs.go#L774

**Comment by bcmills** [comment]
Can you provide a concrete source file that reproduces the issue? There were certainly changes around that code path in 1.13 that may be related, but my understanding (from https://github.com/golang/go/issues/26645#issuecomment-408572701 and other previous discussions) is that relative imports have never worked with `go get`.

This may also be related to #12385.

**Comment by thepudds** [comment]
@nichoriverae just to confirm, is it correct that are you _not_ using modules?

One change in Go 1.13 is `GO111MODULE=auto` (which is the default value if not explicitly set) now turns on module mode whenever you are running the `go` command inside of a directory tree with a go.mod file — even if the current directory is within GOPATH/src. This means module mode happens in more cases than in Go 1.12. (See the [Go 1.13 release notes](https://golang.org/doc/go1.13#modules) for more details).

**Comment by nichoriverae** [comment]
@thepudds the project is using modules

@bcmills I'm attempting to recreate the error using a fresh directory now, I'll post a gist when I get it to the same state. Just to reaffirm, there are no relative imports and the failure point is on submodules within the main package.

**Comment by nichoriverae** [comment]
go vet seems to be looking in GOPATH and GOROOT:
```<package>/src/*/<file>:14:2: cannot find package "github.com/golang-migrate/migrate/v4/database/mysql" in any of:
        /usr/*/github.com/golang-migrate/migrate/v4/database/mysql (from $GOROOT)
        /Users/*/github.com/golang-migrate/migrate/v4/database/mysql (from $GOPATH)```

**Comment by nichoriverae** [comment]
$ and a simple `go get ./...`
```
package <package>/src/config: unrecognized import path "<package>/src/config" (import path does not begin with hostname)
```

**Comment by nichoriverae** [comment]
@bcmills this repo repoduces the error. Granted, it's not using the import that is failing, but the `go get` command gives me the same error.
https://github.com/nichoriverae/Go-Issue-34117

**Comment by thepudds** [comment]
@nichoriverae Thank you for putting that repo together.

For that repo, what is the exact command sequence that fails, and what is the error you currently get?

`go get github.com/nichoriverae/Go-Issue-34117` fails complaining about a mismatch with `parsing go.mod: module declares its path as: main`, but that's expected, and I think not the error in question here.  

Doing `git clone https://github.com/nichoriverae/Go-Issue-34117`, cd'ing to the resulting directory, and doing `go get ./...` and `go get -u ./...` do not seem to complain, so I am probably doing something wrong.

**Comment by nichoriverae** [comment]
I'm under the impression these issues are happening because of GOPROXY and my corporate network settings. I changed the environment variable to "direct" and that solved most of my issues. 

@thepudds I tried the repo on another machine that had a fresh go1.13 install and it didn't give me any problems either, which makes me assume that it is indeed the corporate settings.

**Comment by bubuzzz** [comment]
> Can you provide a concrete source file that reproduces the issue? There were certainly changes around that code path in 1.13 that may be related, but my understanding (from [#26645 (comment)](https://github.com/golang/go/issues/26645#issuecomment-408572701) and other previous discussions) is that relative imports have never worked with `go get`.
> 
> This may also be related to #12385.

I am testing the `qor` package and just created the `main.go` file exactly like the link here https://doc.getqor.com/get_started.html. After that, running `go get -u ./...` will give the same issue

**Comment by bcmills** [comment]
@bubuzzz, that issue seems unrelated. If you're still seeing a problem, please open a new issue.

**Comment by bcmills** [comment]
@nichoriverae, I'm having a bit of trouble following the discussion here, but please let us know if there is anything we still need to resolve.

**Comment by hitzhangjie** [comment]
Hi, my project is organized in GOPATH. I upgrade go from go1.12 to go1.14.

```
conf
src
  |-- source files
```

when I run `GO111MODULE=off go get -v ./...`, it reports `unrecognized import path ....  import path does not begin with hostname`.

It looks like the same problem. Does the behavior change from Go1.13 when GO111MODULE=off?

**Comment by jayconrod** [comment]
@hitzhangjie Make sure there aren't source files directly in a `$GOPATH/src` directory. They should be in subdirectories not in `$GOPATH/src` itself.

Also, make sure any imports outside the standard library start with a hostname, for example, `github.com/go-sql-driver/mysql`. The import posted above was `main/salut`. That won't work because `go get` can't resolve it to a repository.
