### ISSUE TITLE
cmd/go: unable to get x/crypto with go get

### ISSUE THREAD

**Issue by osok** [golang/go#34120]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

$ go get -u golang.org/x/crypto/

### What did you expect to see?
nothing

### What did you see instead?

package golang.org/x/crypto: unrecognized import path "golang.org/x/crypto" (https fetch: Get https://golang.org/x/crypto?go-get=1: EOF)

**Comment by heschik** [comment]
What happens if you visit that URL in a browser or using curl?

**Comment by osok** [comment]
It forwards me to the docs page.  My assumption is that this was the correct place to put an issue that I was not able to get the crypto library, given it was from golang.org.

**Comment by heschik** [comment]
Yes, this is a reasonable place to file an issue, but I don't know how to help you. Perhaps there's something extra in your browser's configuration that allows it to contact golang.org, or something in your Go environment that breaks it.

**Comment by ianlancetaylor** [comment]
I have no idea why you are seeing that particular error.

But `go get golang.org/x/crypto` is not expected to work as that package does not exist.  There are a number of packages under x/crypto, as can be seen at https://godoc.org/golang.org/x/crypto.  But x/crypto is not itself a package.  What happens if you try, say, `go get golang.org/x/crypto/blowfish`?

**Comment by jayconrod** [comment]
Closing, since some time has passed without update. Please comment if you're still seeing this.
