### ISSUE TITLE
x/tools/cmd/gopls: no CheckPackageHandles error when calling Definition

### ISSUE THREAD

**Issue by myitcv** [golang/go#34131]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +9da7abd2eb Tue Sep 3 18:35:32 2019 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20190905221716-4f238b926e10
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.1.4-0.20190905221716-4f238b926e10
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build208684794=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

This is a follow up to https://github.com/golang/go/issues/34103#issuecomment-528570093

We have started to see functional failures as a result of 'no CheckPackageHandles' errors. In this case we were running a test that verifies the behaviour of `Definition`.

The test in question has not changed for some time:

https://github.com/myitcv/govim/blob/46ffc9c315ce59fa13e7df943065e4ee6d2eb199/cmd/govim/testdata/go_to_def_useopen.txt

### What did you expect to see?

No error.

### What did you see instead?

```
failed to call gopls.Definition: no CheckPackageHandles for file://$WORK/q/q.go
```

At this stage I don't have a reproducer for this, and I haven't yet managed to reproduce it locally. When I can reproduce it locally, I will have a `govim`/`gopls` log

---

cc @stamblerre @ianthehat @muirrn

**Comment by myitcv** [comment]
FYI - we've now moved to a version of `gopls` and `x/tools` that includes https://go-review.googlesource.com/c/tools/+/193601, so will monitor whether we see any recurrences of the above issue.

**Comment by myitcv** [comment]
I suspect we can close this now following https://go-review.googlesource.com/c/tools/+/198317

**Comment by kevinburkemeter** [comment]
I can still reproduce this error by calling `:GoDef` with github.com/jmhodges/justrun, when I have either `GO111MODULE=off` or `GOFLAGS='-mod=vendor'` set.

**Comment by stamblerre** [comment]
@kevinburkemeter: What version of `gopls` are you using (`gopls version`)?

**Comment by kevinburkemeter** [comment]
version v0.1.6-cmd.gopls, built in $GOPATH mode

I download/recompile /x/tools and Go tip more or less every day

**Comment by stamblerre** [comment]
We recommend building `gopls` in module mode regardless of whether you are using modules, as module mode has additional features and improvements that we can't offer in GOPATH mode.

I am not able to reproduce your error with GO111MODULE=off--would you mind filing a new issue with a specific repro case? This original issue was more related to flaky errors with caching, whereas it sounds like you're encountering a genuine breakage.

**Comment by kevinburkemeter** [comment]
opened #35081.
