### ISSUE TITLE
plugin: builder failing in freebsd-arm-paulzhol

### ISSUE THREAD

**Issue by katiehockman** [golang/go#34146]
https://build.golang.org/log/0c11bd8b1fd96f011fbf6242bdeeff1403bffcea

```
# plugin.test
/tmp/workdir-host-freebsd-arm-paulzhol/go/pkg/tool/freebsd_arm/link: running clang failed: exit status 1
clang: error: invalid linker name in argument '-fuse-ld=gold'

FAIL	plugin [build failed]
```

Seems related to https://github.com/golang/go/issues/25327
Started appearing after https://go-review.googlesource.com/c/go/+/191617

**Comment by ianlancetaylor** [comment]
Should be fixed by https://golang.org/cl/193537, just submitted.
