### ISSUE TITLE
proxy.golang.org: weird 410 response body

### ISSUE THREAD

**Issue by aofei** [golang/go#34141]
```bash

$ curl -i https://proxy.golang.org/github.com/gohugoio/hugo\!test\!modules1_darwin/modh2/@v/v1.4.0.info
HTTP/2 410 
content-type: text/plain; charset=UTF-8
date: Fri, 06 Sep 2019 11:03:59 GMT
expires: Fri, 06 Sep 2019 11:33:59 GMT
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 0
content-length: 11
cache-control: public, max-age=1800
age: 945
alt-svc: quic=":443"; ma=2592000; v="46,43,39"

not found: %
```

The response body above has only one `not found: ` prefix. It seems that the [proxy.golang.org](https://proxy.golang.org) missed the specific error message.

@katiehockman @mvdan

**Comment by katiehockman** [comment]
Interesting, when I run 
```
curl -i https://proxy.golang.org/github.com/gohugoio/hugo\!test\!modules1_darwin/modh2/@v/v1.4.0.info
``` 

I get the following: 

```
HTTP/2 410
content-type: text/plain; charset=UTF-8
date: Fri, 06 Sep 2019 14:42:46 GMT
expires: Fri, 06 Sep 2019 15:12:46 GMT
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 0
content-length: 61
cache-control: public, max-age=1800
age: 93
alt-svc: quic=":443"; ma=2592000; v="46,43,39"

not found: unknown revision Test/Modules1_darwin/modh2/v1.4.0%
````

I'm not sure why you are missing the error message when you run the command. Can you confirm that you see the same thing when you navigate to https://proxy.golang.org/github.com/gohugoio/hugo\!test\!modules1_darwin/modh2/@v/v1.4.0.info in the browser?

**Comment by aofei** [comment]
Alright, I'll use screenshots to make you believe me. 😂

Terminal:

<img width="892" alt="terminal" src="https://user-images.githubusercontent.com/5037285/64438692-21908980-d0fb-11e9-9196-a51741b072f7.png">

Safari:

<img width="396" alt="safari" src="https://user-images.githubusercontent.com/5037285/64438705-26edd400-d0fb-11e9-8868-bc09c931247d.png">

**Comment by aofei** [comment]
And since it's normal on your side, I think this may be a problem with CDN nodes. I don't know, just a guess.

**Comment by katiehockman** [comment]
Sorry that was my bad. I needed to remove the "\!" when I put it in the browser :)

Will look into this.

**Comment by katiehockman** [comment]
It looks like the mirror had a cached copy of this particular module version which has since been removed from upstream. I can see that sum.golang.org has seen it in the past: https://sum.golang.org/lookup/github.com/gohugoio/hugo!test!modules1_darwin/modh2@v1.4.0

I added a FAQ entry on the https://proxy.golang.org docs to explain this case a little better, and I can look into improving the error message later on.

/cc @hyangah @heschik
(I'll be taking the next 2 weeks as vacation)

**Comment by aofei** [comment]
Closing this issue because it hasn't been reproduced since the last time.
