### ISSUE TITLE
cmd/link: -pluginpath seems to no longer work with go1.13

### ISSUE THREAD

**Issue by e-nikolov** [golang/go#34143]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/enikolov/.cache/go-build"
GOENV="/home/enikolov/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY="bitbucket.org/unchain/*"
GONOSUMDB="bitbucket.org/unchain/*"
GOOS="linux"
GOPATH="/home/enikolov/go"
GOPRIVATE="bitbucket.org/unchain/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/enikolov/.gvm/gos/go1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/enikolov/.gvm/gos/go1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build411225951=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

`go build -ldflags "-pluginpath=custom/path" -buildmode=plugin ./path/to/plugin`

With go1.13 this seems to no longer map the packages to the custom path.

### What did you expect to see?
I have the variable Version in my main package

With go 1.12 after running the strings utility on the produced binary, I would see this somewhere in the output:

custom/path.Version

### What did you see instead?

With go1.13 I now see this instead:

path/to/plugin.Version

Could this be related to go modules?

**Comment by RaynorGu** [comment]
Has this problem be solved? It is inconvenient if we want to reload a plugin.

**Comment by saintdianabless** [comment]
Am I using it the wrong way or is it still buggy? 
![WindowsTerminal_LOu7norgKK](https://user-images.githubusercontent.com/93075932/151197243-17bf8ba9-0e9f-4490-b99f-992aed07c7c9.png)
![image](https://user-images.githubusercontent.com/93075932/151199005-a30fbc20-bf15-4148-8d19-f96cb85c272d.png)

**Comment by cherrymui** [comment]
What is the use case of -pluginpath? Does it affect the semantics of the program, besides changing some symbol names that can be inspected by tools (nm, objdump, strings)? @crawshaw what use cases did you have in mind? Thanks.
