### ISSUE TITLE
cmd/go: Unable to update dependency using insteadOf

### ISSUE THREAD

**Issue by avorima** [golang/go#34148]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Only with the latest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mv/.cache/go-build"
GOENV="/home/mv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mv/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/mv/.local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/mv/.local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/testmodule/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build026595744=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
$ cat ~/.gitconfig
[url "git@private.gitlab.com:"]
    insteadOf = "https://private.gitlab.com/"

$ go get private.gitlab.com/project/repo@vX.Y.Z
```

### What did you expect to see?

That the dependency got added to the `go.mod`.

### What did you see instead?

```
go: finding private.gitlab.com v0.1.0
go: finding private.gitlab.com/project v0.1.0
verifying private.gitlab.com/project/repo@vX.Y.Z: private.gitlab.com/project/repo@v0.1.0: reading https://sum.golang.org/lookup/private.gitlab.com/project/repo@v0.1.0: 410 Gone
```

After exporting `GONOSUMDB=private.gitlab.com/project` the dependency was added successfully. This is an unexpected behaviour, which is why we're currently still waiting with upgrading the go version in our environment.

**Comment by hyangah** [comment]
Sorry for the inconvenience. I think this is working as intended.
The go1.13 release note mentions this in its very first section.

> If you depend on non-public modules, see the documentation for configuring your environment.

GOPRIVATE (or GONOPROXY, GONOSUMDB) are offered to work with private repos.

**Comment by avorima** [comment]
We've further analyzed this issue and found out that most of our repos are working just fine without `GOPRIVATE` or `GONOSUMDB`. We could reproduce the issue by creating a module with a hyphen in the name, e.g. `gitlab.com/project/test-repo`, then creating a go file in the project root with a snake case version of the name, e.g. `package test_repo`. The error was a 410 response from `https://sum.golang.org/lookup/...` (the same as mentioned in [this issue](https://github.com/golang/go/issues/34141)).

**Comment by avorima** [comment]
It seems this really only affects private repos, as I couldn't reproduce this issue [here](https://github.com/avorima/test-repo)

**Comment by dolmen** [comment]
Fix: `export GOPRIVATE=private.gitlab.com`

**Comment by avorima** [comment]
Yes, we know how to fix it. It's just that it doesn't work OOTB anymore. The `GOPROXY` env var has a `direct` fallback. We also tried `GOSUMDB=sum.google.org,off` and it worked. I don't understand why one has a fallback, while the other doesn't

**Comment by hyangah** [comment]
@avorima It's intentional that GOSUMDB doesn't accept fallback. Otherwise, it's possible that MITM attacker blocks your communication temporarily, lets you download different version without getting noticed. By triggering failure, at least, the `go` command draws your attention and you can check what's going on.

**Comment by avorima** [comment]
Ok, I read the [sumdb proposal](https://go.googlesource.com/proposal/+/master/design/25530-sumdb.md) and I understand the security implications of disabled GOSUMDB as fallback. It also answered a few other questions I had about this whole infrastructure.
Thanks for your patience.
