### ISSUE TITLE
reflect:documentation for IsValid and IsZero is confusing

### ISSUE THREAD

**Issue by mohit10verma** [golang/go#34152]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/administrator/.cache/go-build"
GOENV="/home/administrator/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/administrator/Work/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/administrator/Work/go/src/go-latest"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/administrator/Work/go/src/go-latest/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build484657166=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/GYF3SFr7z77

### What did you expect to see?
For a zero value, 
value.IsZero() = true , and 
value.IsValid() = false
according to the documentation here: https://golang.org/pkg/reflect/#Value.IsValid

### What did you see instead?
value.IsZero() = true 
value.IsValid() = true

**Comment by dsnet** [comment]
This is working as intended, but slightly confusing in the documentation.

The documentation for `reflect.Value.IsValid` says "It returns false if v is the zero Value". Note the uppercase `Value`, it's referring to the `reflect.Value`, an abstract representation of any Go value.

The documentation for `reflect.Value.IsZero` says "IsZero reports whether v is the zero value for its type". Note the lowercase `value`, it's referring the underlying Go value that the `reflect.Value` is representing.
