### ISSUE TITLE
proxy.golang.org: Add FAQ item on https://proxy.golang.org/ about use of private modules

### ISSUE THREAD

**Issue by bvwells** [golang/go#34153]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code>
$ go env
</summary><br><pre>
set GOARCH=amd64
set GOOS=windows
</pre></details>

### What did you do?

I had some concerns about the use of https://proxy.golang.org/ in Go 1.13 as to whether private go modules appear in the index database https://index.golang.org if the GOPRIVATE environment variable is not set.

I read through the documentation and couldn't really find the documented behaviour for this. Apologies if I missed it. After a discussion on the modules slack channel it was suggested to post an issue to suggest the addition of an item in the FAQ section of https://proxy.golang.org/ or https://index.golang.org to describe the behaviour of the index database with private modules.

### What did you expect to see?

I expected to see some documentation on the https://proxy.golang.org/ or https://index.golang.org about the behaviour of the proxy and index database for private modules. Perhaps in the FAQ section.

### What did you see instead?

It was good to see that the privacy information for the new proxy was at top of the documentation. However, I couldn't find any information on the behaviour of the index database with private modules.

**Comment by heschik** [comment]
cc @katiehockman, @hyangah

**Comment by heschik** [comment]
The new FAQ question is now published, subject to a brief HTTP cache delay. We also updated the wording in a few places to mention GOPRIVATE. If you have any significant issues with the wording, let us know.
