### ISSUE TITLE
x/tools/gopls: format godoc comments as markdown correctly

### ISSUE THREAD

**Issue by stamblerre** [golang/go#34161]
Forked from https://github.com/golang/go/issues/29151:
> As I'm sure you are aware, note that Go doc strings are not Markdown but rather have their own minimalistic formatting. For them to display with formatting correctly they will need to be converted to Markdown before returning them if we want them to show up formatted in the editor correctly. See [microsoft/vscode-go#2245](https://github.com/microsoft/vscode-go/pull/2245) where I implemented this transformation albeit in JS and here it is needed in Go.

**Comment by JAicewizard** [comment]
do you still need a port of [the ts version markdown escape](https://github.com/microsoft/vscode-go/blob/e3c70486365680580cf57260b4d8905c1dc93527/src/godocToMarkdown.ts)?

**Comment by stamblerre** [comment]
@JAicewizard: Yes, we do. We haven't done any of the work to resolve this issue yet.

**Comment by JAicewizard** [comment]
I would like to finish this issue, I have [a branch](https://github.com/JAicewizard/tools/tree/addBetterComments) with a comment.go and comment_test.go. I wanted to add the tests to tests/ but it tested some private functions as well that shouldn't really be exported.
I think it would be better to merge it with go/doc/comment.go but that would take another release cycle.

**Comment by stamblerre** [comment]
If you'd like to contribute your change to `gopls`, please send us a CL so we can review it. We can discuss on the CL if it's something that should be merged into `go/doc`. In either case, the x/tools repo has to be compatible with older Go versions, so even if it makes it into 1.14, we would probably have to use a copy in x/tools for a few more cycles.

**Comment by stamblerre** [comment]
For some reason [CL 197760](https://go-review.googlesource.com/c/tools/+/197760) wasn't associated with this issue. Closing as it has been merged now.
