### ISSUE TITLE
Leaking goroutines in transport.go

### ISSUE THREAD

**Issue by r0liang** [golang/go#34162]
### What version of Go are you using (`go version`)?

<pre>
go version go1.12.9 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>
$ go env
</code></summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY="https://mirrors.aliyun.com/goproxy/"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/dailing/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build007805367=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I am developing a small network processing, but I noticed that the goroutine in pprof will gradually accumulate and increase, as in the lower part. When the goroutine accumulates to a certain amount, such as 1K, 2K, the process will be blocked and then cannot Handle any transaction. Then I checked the 1800 lines and 1978 lines of transport.go. The reason for the problem seems to be that the release was not completely released, resulting in the same amount of readLoop and writeLoop.

### What did you expect to see?
Will not block

### What did you see instead?
<code>
81 @ 0x430f3f 0x440a18 0x73b8fa 0x45e481
0x73b8f9	net/http.(*persistConn).readLoop+0x959	/usr/local/go/src/net/http/transport.go:1800

81 @ 0x430f3f 0x440a18 0x73cc03 0x45e481
0x73cc02	net/http.(*persistConn).writeLoop+0x112	/usr/local/go/src/net/http/transport.go:1978
</code>

**Comment by antong** [comment]
Can you post code that reproduces the issue? Are you sure you are always closing the response body?

**Comment by r0liang** [comment]
Maybe my version is not updated to the latest, I tried to update to the latest version of golang later, but the response body in the program code I only called once, and used <code>defer response.Body.Close()</code >
