### ISSUE TITLE
Template.Execute doesn't return the original error from methods and functions

### ISSUE THREAD

**Issue by snowcall** [golang/go#34179]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\User\AppData\Local\go-build
set GOENV=C:\Users\User\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\Go
set GOPRIVATE=
set GOPROXY=direct
set GOROOT=C:\Go\go1.13
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\go1.13\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\Projects\test\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\User\AppData\Local\Temp\go-build112356450=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

```go
package main

import (
	"html/template"
	"log"
	"os"
)

type etype struct { str string }

func (e *etype) Error() string { return e.str }

type Rec struct { Some int }

func (r *Rec) Hello() (string, error) { return "", &etype{str: "Message"} }

func main() {
	t := template.Must(template.New("test").Parse("{{ .Rec.Hello }}"))

	err := t.Execute(os.Stdout, struct{
		Rec *Rec
	}{
		Rec: &Rec{10},
	})
	
	log.Printf("%#v\n", err)
}
```

### What did you expect to see?
```
&main.etype{str:"Message"}
```

### What did you see instead?
```
template.ExecError{Name:"test", Err:(*errors.errorString)(0xc00004c3f0)}
```

The same applies to errors returned by functions passed with `template.FuncMap` but docs clearly states:
> if the second (error) return value evaluates to non-nil during execution, execution terminates and Execute returns **that error**

(emphasis mine)

Printing `err.(template.ExecError).Err` returns `&errors.errorString{...}`

**Comment by robpike** [comment]
You're printing with %#v, which unpacks the contents. Use %v instead and it works fine:

```
2009/11/10 23:00:00 template: test:1:7: executing "test" at <.Rec.Hello>: error calling Hello: Message
```

**Comment by snowcall** [comment]
I'm talking here about types, not messages. 

Execute returns opaque template.ExecError and there is no way to get original error.

**Comment by snowcall** [comment]
Let's take another example:

```go
package main

import (
	"errors"
	"fmt"
	"os"
	"text/template"
)

type MyError struct {
	Value int
}

func (e *MyError) Error() string { return "some message" }

func test(some int) (string, error) {
	return "", &MyError{
		Value: some,
	}
}

func main() {
	t := template.Must(template.New("test").Funcs(template.FuncMap{
		"test": test,
	}).Parse("{{ test 10 }}"))

	err := t.Execute(os.Stdout, nil)

	if err != nil {
		var e *MyError
		fmt.Println(errors.As(err, &e)) // false
	}
}
```
`template.ExecError` does support `Unwrap()` but returns `*errors.ErrorString`, not a `*MyError`

As I pointed in the first post, documentation states that Execute should return the error returned by template function, but actually it returns opaque error that cannot be unwrapped.

**Comment by snowcall** [comment]
@robpike why did you close this? Your message is not related to the issue. How can I reopen it?

**Comment by networkimprov** [comment]
@snowcall you might want to revise the issue text with your clarification above...

cc @neild @jba

**Comment by robpike** [comment]
I closed this because I believed it was not a correct report. I am not sure now.

I suggest rather than reopening this one, which is a little confusing, you use your second example to create a new, clearer issue.

**Comment by jba** [comment]
For that new issue: I can confirm that at least since 1.5, the `Funcs` doc comment says "Execute returns _that_ error " (emphasis mine), and also that it does not in fact do so.
