### ISSUE TITLE
fmt: Scanning '%%' is a verb

### ISSUE THREAD

**Issue by pavel** [golang/go#34180]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
https://play.golang.org/p/PNBiGNussAs
```
package main

import (
	"fmt"
	"log"
)

func readVersion(f, s string) {
	var major, minor uint8

	_, err := fmt.Sscanf(s, f, &major, &minor)
	if err != nil {
		log.Println("Failed to parse", s, ". Reason:", err)
		return
	}

	log.Println("Parsed", s, "into", major, minor)
}

func main() {
	readVersion("%%VER-%d.%d", "%VER-1.4")
	readVersion("%%VER-%d.%d", "%ER-1.4") // fails: "bad verb '%%' for integer"
	readVersion("VER-%d.%d", "VER-1.4")
	readVersion("VER-%d.%d", "ER-1.4") // fails: "input does not match format"
}
```

### What did you expect to see?
Second run should return `input does not match format`, just like the call number 4.

### What did you see instead?
`bad verb '%%' for integer` error.

**Comment by rusq** [comment]
Observing the same behaviour for Go 1.8, Go 1.9.5 and Go 1.10.5, not something introduced in 1.13.

`34180.go` contains the code from the playground mentioned above. https://play.golang.org/p/PNBiGNussAs
```
$ go1.8 run 34180.go
2019/09/10 22:10:03 Parsed %VER-1.4 into 1 4
2019/09/10 22:10:03 Failed to parse %ER-1.4 . Reason: bad verb '%%' for integer
2019/09/10 22:10:03 Parsed VER-1.4 into 1 4
2019/09/10 22:10:03 Failed to parse ER-1.4 . Reason: input does not match format
```
