### ISSUE TITLE
x/debug/cmd/viewcore install error: use of internal package not allowed

### ISSUE THREAD

**Issue by yyb196** [golang/go#34187]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.9 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
centos-7

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/yyb/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/yyb/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build820861264=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

$go get -u github.com/golang/debug/cmd/viewcore
go/src/github.com/golang/debug/cmd/viewcore/html.go:17:2: use of internal package golang.org/x/debug/internal/core not allowed
go/src/github.com/golang/debug/cmd/viewcore/html.go:18:2: use of internal package golang.org/x/debug/internal/gocore not allowed

### What did you expect to see?
install viewcore binary to $GOPATH/bin

### What did you see instead?
use of internal package ... not allowed

**Comment by antong** [comment]
The path is golang.org/x/debug/cmd/viewcore, not github.com/golang/debug/cmd/viewcore .

**Comment by hyangah** [comment]
Thanks @antong

Yes, this is working as intended. The official path of the viewcore tool is  `golang.org/x/debug/cmd/viewcore`

<p>
$ go get golang.org/x/debug/cmd/viewcore
</p>
