### ISSUE TITLE
x/tools/go/packages: race in TestConfigDefaultEnv/GOPATH

### ISSUE THREAD

**Issue by stamblerre** [golang/go#34196]
Noticed this on builders. 
Logs: https://storage.googleapis.com/go-build-log/51c8d969/linux-amd64-race_830cf157.log.

<details>
==================
WARNING: DATA RACE
Read at 0x00c00039bc50 by goroutine 57:
  runtime.slicecopy()
      /workdir/go/src/runtime/slice.go:197 +0x0
  golang.org/x/tools/go/packages.invokeGo()
      /workdir/gopath/src/golang.org/x/tools/go/packages/golist.go:857 +0x1e0
  golang.org/x/tools/go/packages.determineRootDirsGOPATH()
      /workdir/gopath/src/golang.org/x/tools/go/packages/golist_overlay.go:224 +0xc8
  golang.org/x/tools/go/packages.determineRootDirs()
      /workdir/gopath/src/golang.org/x/tools/go/packages/golist_overlay.go:205 +0x36e
  golang.org/x/tools/go/packages.goListDriver.func2()
      /workdir/gopath/src/golang.org/x/tools/go/packages/golist.go:116 +0x3c

Previous write at 0x00c00039bc50 by goroutine 58:
  golang.org/x/tools/go/packages_test.testConfigDefaultEnv.func1()
      /workdir/gopath/src/golang.org/x/tools/go/packages/packages_test.go:1891 +0x287
  testing.tRunner()
      /workdir/go/src/testing/testing.go:909 +0x199

Goroutine 57 (running) created at:
  golang.org/x/tools/go/packages.goListDriver()
      /workdir/gopath/src/golang.org/x/tools/go/packages/golist.go:115 +0x22b
  golang.org/x/tools/go/packages.defaultDriver()
      /workdir/gopath/src/golang.org/x/tools/go/packages/packages.go:226 +0x79
  golang.org/x/tools/go/packages.Load()
      /workdir/gopath/src/golang.org/x/tools/go/packages/packages.go:211 +0x93
  golang.org/x/tools/go/packages_test.testConfigDefaultEnv.func1()
      /workdir/gopath/src/golang.org/x/tools/go/packages/packages_test.go:1892 +0x3e4
  testing.tRunner()
      /workdir/go/src/testing/testing.go:909 +0x199

Goroutine 58 (running) created at:
  testing.(*T).Run()
      /workdir/go/src/testing/testing.go:960 +0x651
  golang.org/x/tools/go/packages_test.testConfigDefaultEnv()
      /workdir/gopath/src/golang.org/x/tools/go/packages/packages_test.go:1887 +0x7ed
  golang.org/x/tools/go/packages/packagestest.TestAll.func1()
      /workdir/gopath/src/golang.org/x/tools/go/packages/packagestest/export.go:102 +0x91
  testing.tRunner()
      /workdir/go/src/testing/testing.go:909 +0x199
==================
--- FAIL: TestConfigDefaultEnv (0.06s)
    --- FAIL: TestConfigDefaultEnv/GOPATH (0.02s)
        --- FAIL: TestConfigDefaultEnv/GOPATH/driver_set (0.01s)
            testing.go:853: race detected during execution of test
        testing.go:853: race detected during execution of test
    testing.go:853: race detected during execution of test
FAIL
FAIL	golang.org/x/tools/go/packages	54.823s
</details>

/cc @matloob

**Comment by matloob** [comment]
I believe this was fixed by https://go-review.googlesource.com/c/tools/+/203897.
