### ISSUE TITLE
x/tools/imports: doesn't add import for ast.Expr

### ISSUE THREAD

**Issue by muirrn** [golang/go#34199]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/muir/Library/Caches/go-build"
GOENV="/Users/muir/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/muir/projects/<project>/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/muir/projects/tools/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/96/wknz1jg92yl623qgplk6qw2h0000gn/T/go-build439747941=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I ran organize imports on below file:

```go
package main
var _ ast.Expr
```

### What did you expect to see?

I expected it to add an import for "go/ast".

### What did you see instead?

No import added. goimports works, and mysteriously organize imports works if you change it to ast.Node.

**Comment by heschik** [comment]
Not (just) a gopls bug, renamed.

**Comment by heschik** [comment]
Huh.
```
$ grep 'bytes, type Buffer' go/api/go1.txt
pkg bytes, type Buffer struct
$ grep 'go/ast, type Expr' go/api/go1.txt
pkg go/ast, type Expr interface, End() token.Pos
pkg go/ast, type Expr interface, Pos() token.Pos
pkg go/ast, type Expr interface, unexported methods
...
```

We take the API files and turn them into `zstdlib.go`, and use that for the stdlib. So, two bugs: the built in exports list for `go/ast` is missing Expr, and `goimports` doesn't look at `GOROOT` for some reason.

**Comment by dmitshur** [comment]
> the built in exports list for `go/ast` is missing Expr

We've determined it's not missing, it just looks different. This line is the entry for the `ast.Expr` interface:

```
pkg go/ast, type Expr interface, unexported methods
```

The line looks a little unusual because of the ", unexported methods" suffix.
