### ISSUE TITLE
fallthrough, Is this correct?

### ISSUE THREAD

**Issue by gclove** [golang/go#34206]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.13 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

https://play.golang.org/p/lOGAE6qg9WM

```go
package main

import "fmt"

func main() {
	var a int64 = 20

	switch {
	case 5 == a:
		fmt.Println(a)
		fallthrough
	case 20 == a:
		fmt.Println(1, a)
		fallthrough
	case 322332 == a:
		fmt.Println(2, a)
		fallthrough
	case 3223 == a:
		fmt.Println(3, a)
		fallthrough
	default:
		fmt.Println("default", a)
	}

}
```

### What did you see instead?

```txt
1 20
2 20
3 20
default 20
```

**Comment by gclove** [comment]
Maybe I understand it wrong, it is my problem.

**Comment by DisposaBoy** [comment]
For anyone else that's confused about why the playground is outputting `default 20` after reading the code here, it's because the code is different.
