### ISSUE TITLE
text/template: wrap errors returned by custom template functions

### ISSUE THREAD

**Issue by snowcall** [golang/go#34201]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\User\AppData\Local\go-build
set GOENV=C:\Users\User\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\Go
set GOPRIVATE=
set GOPROXY=direct
set GOROOT=C:\Go\go1.13
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\go1.13\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\Projects\test\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\User\AppData\Local\Temp\go-build112356450=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I'm trying to get the error returned by my custom template function. The error is a struct implementing the `error` interface. 

`Execute` returns `template.ExecError` and despite the fact that it implements `Unwrap() error`, calling `Unwrap` returns `*errors.errorsString`, not my error implementation.

Thus, there is no way to get the original error.

Code:
```go
package main

import (
	"errors"
	"fmt"
	"os"
	"text/template"
)

type MyError struct {
	Value int
}

func (e *MyError) Error() string { return "error message" }

func test(val int) (string, error) {
	return "", &MyError{
		Value: val,
	}
}

func main() {
	t := template.Must(template.New("test").Funcs(template.FuncMap{
		"test": test,
	}).Parse("{{ test 10 }}"))

	err := t.Execute(os.Stdout, nil)

	if err != nil {
		var e *MyError
		fmt.Println(errors.As(err, &e)) // <-- false
	}
}
```

### What did you expect to see?
`true`

### What did you see instead?
`false`

### Additional notes
1. Documentation for `template.FuncMap` states that:
> if the second (error) return value evaluates to non-nil during execution, execution terminates and Execute returns **that error**

2. The same applies for method calls like `{{ .Object.Method }}`.

3. Both `text/template` and `html/template` are affected.

**Comment by snowcall** [comment]
_Originally posted by @jba in https://github.com/golang/go/issues/34179#issuecomment-529700943_
> For that new issue: I can confirm that at least since 1.5, the `Funcs` doc comment says "Execute returns _that_ error " (emphasis mine), and also that it does not in fact do so.

**Comment by tmthrgd** [comment]
I believe this is caused by this line using `%v` not `%w`:

https://github.com/golang/go/blob/b963149d4eddaf92d9e2a9d3bf5474c2d0a3b55d/src/text/template/exec.go#L715

**Comment by toothrot** [comment]
Thanks for filing the updated issue, @snowcall.

The "errors" package (and corresponding `%w` wrap) is new in the standard library, and has only been used selectively so far in the standard library. I believe that documentation copy (`execution terminates and Execute returns that error`) predates error wrapping.

I'm cc'ing the owners of text/template who can provide some more context.

/cc @mvdan @robpike

**Comment by mvdan** [comment]
I think this should be a proper proposal to change text/template to use error wrapping. The proposal should explain what scenarios would start wrapping errors and why.

**Comment by tj** [comment]
I ran into this as well, I need to get my error back from a template but you can't unwrap this `&errors.errorString{s:"template: :4:6:...` it's returning. IMO it should be all or nothing in the stdlib, it was really jarring to see that it only works with _some_ errors

**Comment by mvdan** [comment]
@tj sorry, do you mean that error wrapping is inconsistent within `text/template` itself? If so, we should definitely fix that sooner than later. I'd be happy to review a patch.

If you mean with other packages in the standard library, I think it's expected that it will take a few releases for each one of them to be adapted to error wrapping.

**Comment by tj** [comment]
@mvdan I'm not sure if text/template wraps in other scenarios, but in this case the `{{compile .Query}}` is returning a `errors.errorString`, so I can't get access to the underlying parser/compiler error, which is more human-friendly for customers than:

```
template: :4:6: executing \"\" at <compile .Query>: error calling compile: parsing query: Parse error near \"\\\"ping and host = \\\"\""
```

**Comment by mvdan** [comment]
Yeah, I think the package just hasn't been adapted for error wrapping at all. It's certainly something we can look at for 1.15, but as you can imagine, that's eight months away from being generally available. Changing the types of errors is just far too risky to do during code freeze.

If anyone wants to take a stab at this work, feel free. Otherwise I might get started once the tree reopens for 1.15. I think the biggest part of the work will be figuring out what APIs should start using error wrapping, and making sure that no tests are broken.

**Comment by tj** [comment]
Fair enough! I didn't realize they weren't mostly converted when the wrapping was introduced

**Comment by mholt** [comment]
Will this bugfix make it into Go 1.16?

**Comment by mvdan** [comment]
The CL got some questions in November which weren't answered, and we're very late in the freeze, so I think it's a safe "no" at this point. It's more of an API consistency improvement rather than a bugfix.

I think it can definitely make 1.17 if @azr responds there, or if someone else takes over the change.

**Comment by mholt** [comment]
Ok, thanks.

>  It's more of an API consistency improvement rather than a bugfix.

Well, it's in violation of the documentation, which says it returns "that error".

>  I think the package just hasn't been adapted for error wrapping at all.

Yet, the `templates.ExecError` type does have an Unwrap method, introduced in Go 1.13: https://golang.org/pkg/text/template/#ExecError.Unwrap

It's pretty clear this is a bug, even if it is just an oversight.

In any case, let me know how I can help make progress getting this fixed.

**Comment by mvdan** [comment]
Maybe you're right, I'm not sure. My instinct is that this kind of internal change, even if it's definitely correct, could very easily change the behavior of existing programs. So my default response is that three weeks before the final release, given that there's nearly no time to get it tested.

Then again, rc1 is late so that could still work as a way to get it tested. Normally it would already be out by now.

> In any case, let me know how I can help make progress getting this fixed.

Sending a new CL to advance the change sounds like the right way. At minimum, the original change needs a test, like Ian said.

**Comment by mholt** [comment]
Gotcha. If 1.17 is the earliest it can make it at this point I'll spare my energy and see if the existing CL makes it in over the next few months. Thanks! :crossed_fingers:

**Comment by azr** [comment]
I'll add some tests right away so that it's ready for 1.7
