### ISSUE TITLE
x/text/unicode/norm: TestLinking consistently failing on multiple builders

### ISSUE THREAD

**Issue by bcmills** [golang/go#34209]
See previously #32843.

`TestLinking` appears to be failing consistently on the following builders:
* `linux-arm` (https://build.golang.org/log/367d5667c1ab0411c469fb3ff70496dec84e41e0)
   ```
   normalize_test.go:937: tables appear not to be dropped: 1945437 - 1941429 = 4008
   ```
* `linux-arm64-packet` (https://build.golang.org/log/a52ea14003e838e42ca1cd2b4082435838e79631)
   ```
   normalize_test.go:937: tables appear not to be dropped: 2095708 - 2091220 = 4488
   ```
* `linux-ppc64le-buildlet` (https://build.golang.org/log/6c896381e8a1c82f113eb45978ff309dd893513e)
   ```
   normalize_test.go:937: tables appear not to be dropped: 2098114 - 2093534 = 4580
   ```
* `linux-ppc64le-power9osu` (https://build.golang.org/log/8b01ed9d81fbc80df42ad31a20de438c946f9ec0)
   ```
   normalize_test.go:937: tables appear not to be dropped: 2098114 - 2093534 = 4580
   ```

The failures are all similar, but the reported numbers vary by platform.

If a test failure on these platforms is expected, the test should be skipped.

**Comment by rsc** [comment]
/cc @dr2chase @cherrymui @jeremyfaller 
Maybe this test failure is real and the linker is failing to eliminate data it used to?

**Comment by dmitshur** [comment]
Friendly ping.

This issue currently has the label Soon, which is for regressions, serious bugs, and outages. This doesn't seem to qualify for that, so I'll remove the Soon label.

**Comment by jeremyfaller** [comment]
Sorry 'bout that. Probably got lost in the runup to 1.14 freeze. I'll take a look.

**Comment by dmitshur** [comment]
No problem, and thank you Jeremy. I just wanted to update our list of Soon issues.

**Comment by cherrymui** [comment]
My guess is that this is due to alignment padding between segments. It seems the failures are all on architectures with large alignment (usually 0x10000 i.e. 64K). Worst case the alignment padding can increase the binary size by 64K, which can shadow the 50K difference we're looking for.

If the test is checking if the table is dropped by the linker, maybe use the nm command to look for particular symbols?

**Comment by cherrymui** [comment]
Or it can add the size of sections without the paddings. But then it needs to be OS dependent: will need codepaths for ELF, Mach-O, xcoff, etc..

**Comment by cherrymui** [comment]
Or the test can use linker's -R flag to reduce the alignment. This might cause problems at run time, but we don't run the resulted binaries.
