### ISSUE TITLE
GOPATH project compile failed because of GOROOT's vendor

### ISSUE THREAD

**Issue by lunny** [golang/go#34200]
### What version of Go are you using (`go version`)?

go1.13

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

</pre></details>

### What did you do?

set the project as a gopath root and then
```
GOPATH=pwd go build
```

### What did you expect to see?

Compile succeed

### What did you see instead?

We have used a package on `golang.org/x/text` and vendor it on our projects. We set our project as a GOPATH. Then when we compile it, it will fail and return the error.

I think this is caused by `goroot/src/vendor` which added on go1.13. We can find golang.org/x/ packages on that. When compiling, go will find that vendor at first but not the vendor on gopath.

```
12:2: use of vendored package not allowed
```

**Comment by bronze1man** [comment]
Looks like https://github.com/golang/go/issues/34068

**Comment by lunny** [comment]
@bronze1man Thanks! duplicated with #34068.
