### ISSUE TITLE
cmd/go: could not import github.com/robteix/testmod/v2 (no package data for import path github.com/robteix/testmod/v2)

### ISSUE THREAD

**Issue by chingiz2387** [golang/go#34204]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.9 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\00046605\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\myProject\Go\
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=D:\myProject\Go\src\github.com\EPAY2\oauth\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\00046605\AppData\Local\Temp\go-build124838294=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
Hello everyone, when connecting the modules to the golang project, I install the module through the get-go and specify the path in the import test mode "github.com/robteix/testmod/v2"

### What did you expect to see?

import (
  testmode "github.com/robteix/testmod/v2"
) 

to see a working import without errors

### What did you see instead?
could not import github.com/robteix/testmod/v2 (no package data for import path github.com/robteix/testmod/v2)

**Comment by bcmills** [comment]
Note that the `go.mod` file in the `v2.0.0` release has a mismatched module path. (It declares its path to be `github.com/rselbach/testmod/v2`, but you are importing it as `github.com/robteix/testmod/v2`.)

In general, Go 1.13 should produce much clearer diagnostics in this sort of case. Please try this with a `go1.13` build and let us know if things are still unclear.

**Comment by hyangah** [comment]
I hope the following error message with go1.13 is clear enough to help users find the issue @chingiz2387 

<pre>
$ go get github.com/robteix/testmod/v2
go get: github.com/robteix/testmod/v2@v2.0.0: parsing go.mod:
	module declares its path as: github.com/rselbach/testmod/v2
	        but was required as: github.com/robteix/testmod/v2
</pre>

**Comment by chingiz2387** [comment]
@bcmills Hello, Can you explain in more detail "Note that the go.mod file in the v2.0.0 release has a mismatched module path. (It declares its path to be github.com/rselbach/testmod/v2, but you are importing it as github.com/robteix/testmod/v2.)" in go.mod i see that it is installed by github.com/robteix/testmod/v2 v2.0.0 or i misunderstood you...

**Comment by bcmills** [comment]
@chingiz2387, see http://golang.org/wiki/Modules#how-can-i-resolve-parsing-gomod-unexpected-module-path-and-error-loading-module-requirements-errors-caused-by-a-mismatch-between-import-paths-vs-declared-module-identity.

**Comment by hyangah** [comment]
https://github.com/robteix/testmod/blob/v2.0.0/go.mod

**Comment by bcmills** [comment]
As far as I can tell the `go` command is working as designed here, and the diagnostic seems to have gotten much clearer in Go 1.13. I don't see anything left to do, so closing this issue.
