### ISSUE TITLE
use of internal package golang.org/x/crypto/ed25519/internal/edwards25519 not allowed

### ISSUE THREAD

**Issue by Barry-China** [golang/go#34202]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
tao:src Barry$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/Barry/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/Barry/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/k0/l6n3lg0s1qb2fkyt6f2p5z3m0000gn/T/go-build717448351=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
go install github.com/micro/micro
crypto/ed25519/ed25519.go:32:2: use of internal package golang.org/x/crypto/ed25519/internal/edwards25519 not allowed

### What did you expect to see?
go install github.com/micro/micro success

### What did you see instead?
tao:go Barry$ go install github.com/micro/micro
src/crypto/ed25519/ed25519.go:34:2: use of internal package golang.org/x/crypto/ed25519/internal/edwards25519 not allowed

**Comment by ianlancetaylor** [comment]
Do you have a directory `src/crypto/ed25519`?  I don't understand where that is coming from.  That exists in Go 1.13, but you say that you are using Go 1.12.  Did you try to install Go 1.13?  Is there some confusion between different Go releases on your system?

**Comment by antong** [comment]
The reason this is not working for you @Barry-China , is because you are importing a package that only works with Go 1.13 (see https://golang.org/doc/go1.13#crypto/ed25519).

I guess the culprit is github.com/marten-seemann/qtls, but here is a minimal example:
```
package main

import "fmt"
import _ "crypto/ed25519" // Introduced into the stdlib in 1.13

func main() {
        fmt.Println("Hello world!")
}
```

Now, the reason for the confusing error message, is probably that you have checked out x/crypto (github.com/golang/crypto) into GOPATH/src. That won't work, for x/crypto to work, you need to have it in GOPATH/src/golang.org/x/crypto.

Without that package in the wrong location, you'd get a different, confusing error message:
```
package crypto/ed25519: unrecognized import path "crypto/ed25519" (import path does not begin with hostname)
```

I think this error message could be improved by future proofing known, top-level standard library paths like crypto, that may get new subdirectories in future versions.

**Comment by Barry-China** [comment]
Thank you for your answer,I upgraded golang  to the version1.13 to solved the problem.

**Comment by meganthomas** [comment]
I am still getting the same error 

xterm@test:~/go/src/github.com/libp2p/go-libp2p-examples/chat-with-rendezvous$ go build -o chat chat.go
../../go-libp2p-core/crypto/ed25519.go:5:2: cannot find package "crypto/ed25519" in any of:
        /usr/lib/go-1.10/src/crypto/ed25519 (from $GOROOT)
        /home/xterm/go/src/crypto/ed25519 (from $GOPATH)
xterm@test:~/go/src/github.com/libp2p/go-libp2p-examples/chat-with-rendezvous$

**Comment by meganthomas** [comment]
I am still getting the same error

----
xterm@rudraksh:~/go/src/github.com/libp2p/go-libp2p-examples$ cd chat-with-rendezvous/
xterm@rudraksh:~/go/src/github.com/libp2p/go-libp2p-examples/chat-with-rendezvous$ ls
chat.go  flags.go  README.md
xterm@rudraksh:~/go/src/github.com/libp2p/go-libp2p-examples/chat-with-rendezvous$ go build -o chat chat.go
../../go-libp2p-core/crypto/ed25519.go:5:2: cannot find package "crypto/ed25519" in any of:
        /usr/lib/go-1.10/src/crypto/ed25519 (from $GOROOT)
        /home/xterm/go/src/crypto/ed25519 (from $GOPATH)
xterm@rudraksh:~/go/src/github.com/libp2p/go-libp2p-examples/chat-with-rendezvous$ find /home/xterm/go/src/go
golang.org/       go.opencensus.io/ go.uber.org/
xterm@test:~/go/src/github.com/libp2p/go-libp2p-examples/chat-with-rendezvous$ find /home/xterm/go/src/golang.org/ -iname ed25519
/home/xterm/go/src/golang.org/x/crypto/ed25519
xterm@test:~/go/src/github.com/libp2p/go-libp2p-examples/chat-with-rendezvous$

**Comment by meganthomas** [comment]
i am still getting the same error 

xterm@rudraksh:~/go/src/github.com/libp2p/go-libp2p-examples$ cd chat-with-rendezvous/
xterm@rudraksh:~/go/src/github.com/libp2p/go-libp2p-examples/chat-with-rendezvous$ ls
chat.go  flags.go  README.md
xterm@rudraksh:~/go/src/github.com/libp2p/go-libp2p-examples/chat-with-rendezvous$ go build -o chat chat.go
../../go-libp2p-core/crypto/ed25519.go:5:2: cannot find package "crypto/ed25519" in any of:
        /usr/lib/go-1.10/src/crypto/ed25519 (from $GOROOT)
        /home/xterm/go/src/crypto/ed25519 (from $GOPATH)
xterm@rudraksh:~/go/src/github.com/libp2p/go-libp2p-examples/chat-with-rendezvous$ find /home/xterm/go/src/go
golang.org/       go.opencensus.io/ go.uber.org/
xterm@rudraksh:~/go/src/github.com/libp2p/go-libp2p-examples/chat-with-rendezvous$ find /home/xterm/go/src/golang.org/ -iname ed25519
/home/xterm/go/src/golang.org/x/crypto/ed25519
xterm@rudraksh:~/go/src/github.com/libp2p/go-libp2p-examples/chat-with-rendezvous$

**Comment by davecheney** [comment]
@meganthomas this issue was closed 8 months ago. It is likely that the programs you are trying to compile require a newer version of Go than 1.10, which is no longer supported.

Can you please upgrade to a supported version of Go, and if the issue persists please raise a new issue by filling in the templated provided by GitHub.
