### ISSUE TITLE
doc: godoc html format is incorrectly

### ISSUE THREAD

**Issue by paveg** [golang/go#34226]
### What version of Go are you using (`go version`)?

<pre>
$ go version  go1.13beta1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes
https://golang.org/doc/go1.13#godoc

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ikezawa-ryota/Library/Caches/go-build"
GOENV="/Users/ikezawa-ryota/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/ikezawa-ryota"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/ikezawa-ryota/.anyenv/envs/goenv/versions/1.13beta1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/ikezawa-ryota/.anyenv/envs/goenv/versions/1.13beta1/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fq/whc2twqs3y31s1nqz8t4lfm5tzk1hb/T/go-build915645964=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

git clone golang/go repository and execute grep (ripgrep) doc directory.

```bash
~/src/github.com/golang/go master
$ rg "h3.*code" ./doc
...
./doc/go1.12.html
309:<h3 id="godoc"><code>godoc</code> and <code>go</code> <code>doc</code></h3>

./doc/go1.13.html
455:<h3 id="godoc"><code>godoc</code> and <code>go</code> <code>doc</code></h3>
...
```

### What did you expect to see?

I expect https://golang.org/doc/go1.12#godoc and https://golang.org/doc/go1.13#godoc is below.

```html
// now
<h3 id="godoc"><code>godoc</code> and <code>go</code> <code>doc</code> <a class="permalink" href="#godoc">¶</a></h3>

// expect
<h3 id="godoc">godoc and go doc<a class="permalink" href="#godoc">¶</a></h3>
```

**Comment by agnivade** [comment]
Are you suggesting `godoc` and `go doc` should _not_ be within `<code>` tags ? If so, can you clarify why ? They are commands, and as is convention, should be wrapped with `<code>` tags.

**Comment by paveg** [comment]
@agnivade 
Thank for replying.

I suggested that the emphasis in this document is godoc and go doc.
But now only `and` is emphasized.

<img width="841" alt="Screen Shot 2019-09-11 at 14 07 36" src="https://user-images.githubusercontent.com/12677991/64669709-936f2700-d49d-11e9-8de8-a69d640f2d86.png">

I couldn't find a discussion, so I cut the issue, close it if expected.

**Comment by agnivade** [comment]
The entire text is under `<h3>`. So all of it is emphasized. `godoc` and `go doc` appears that way because they are inside code blocks. This is WAI.
