### ISSUE TITLE
x/tools/internal/lsp/protocol: can't reproduce code generated from typescript

### ISSUE THREAD

**Issue by fhs** [golang/go#34225]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env | grep -v [secret]
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/fhs/.cache/go-build"
GOENV="/home/fhs/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/fhs/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/big/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/big/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/fhs/go/src/golang.org/x/tools/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build768397328=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Checkout `vscode-langserver-node` at the matching commit:
```
$ cd ~
$ git clone git@github.com:microsoft/vscode-languageserver-node.git
$ cd vscode-languageserver-node
$ git reset --hard fda16d6b63ba0fbdbd21d437ea810685528a0018
$ sed -i '1812s/;$//' protocol/src/protocol.ts  # needed to make go.ts work below
```
Generate `tsprotocol.go`:
```
$ cd $GOPATH/golang.org/x/tools/internal/lsp/protocol/typescript  # master branch
$ tsc go.ts && node go.js && gofmt -w /tmp/tsprotocol.go
```
### What did you expect to see?

One line diff for the "last fetched" line.

### What did you see instead?

```
$ diff -u ../tsprotocol.go /tmp/tsprotocol.go | head
--- ../tsprotocol.go	2019-09-10 21:46:42.692636315 -0400
+++ /tmp/tsprotocol.go	2019-09-10 22:01:13.649741464 -0400
@@ -1,31 +1,11 @@
 // Package protocol contains data types and code for LSP jsonrpcs
 // generated automatically from vscode-languageserver-node
 // commit: fda16d6b63ba0fbdbd21d437ea810685528a0018
-// last fetched Fri Sep 06 2019 18:16:51 GMT-0400 (Eastern Daylight Time)
+// last fetched Tue Sep 10 2019 22:01:03 GMT-0400 (Eastern Daylight Time)
 package protocol
 
$ diff -u ../tsprotocol.go /tmp/tsprotocol.go | diffstat
 tsprotocol.go |  512 ++++++----------------------------------------------------
 1 file changed, 53 insertions(+), 459 deletions(-)
```
Full diff is here: https://gist.github.com/fhs/866f396960bfa503c64fb8a3cad8f4f5

I'm able to reproduce a matching `tsprotocol.go` for commit https://github.com/golang/tools/commit/dddb76172320be9415dc691006a78ea73ef1101e. Commit https://github.com/golang/tools/commit/a0cf054a4555933c163d9bff1b5395fa6de484ac seems to make manual change to the auto-generated file. Commit https://github.com/golang/tools/commit/fef9eaa9e42b9f5f0fb87822523507d5a1c709fa made bunch of changes without updating `go.ts`.

**Comment by pjweinb** [comment]
This is my fault. I'm about to send in changes to the typescript files, and a slightly improved README.md
