### ISSUE TITLE
go/types: reports error for iota inside function in ConstSpec

### ISSUE THREAD

**Issue by cuonglm** [golang/go#34228]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +4d08c642b6 Wed Sep 11 13:25:29 2019 +0700 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/cuonglm/Library/Caches/go-build"
GOENV="/Users/cuonglm/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/cuonglm/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/cuonglm/sources/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/cuonglm/sources/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/y4/hs76ltbn7sb66lw_6934kq4m0000gn/T/go-build072057708=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://play.golang.org/p/e9C6dFv_GFX

### What did you expect to see?

Success.

### What did you see instead?

Error:

```
2019/09/11 14:53:53 src.go:34:24: cannot use iota outside constant declaration
exit status 1
```

**Comment by mdempsky** [comment]
Minimal repro:

```
$ cat x.go
package main

import "unsafe"

const _ = unsafe.Sizeof(func() {
	const _ = 0
	_ = iota
})

$ gotype x.go
x.go:7:6: cannot use iota outside constant declaration
```

(I feel like I remember filing this issue before, but I can't find any record of it in the issue tracker.)

**Comment by mdempsky** [comment]
> (I feel like I remember filing this issue before, but I can't find any record of it in the issue tracker.)

I think this is the test case I was remembering: https://github.com/golang/go/issues/15550#issuecomment-217048744

Seems go/types is okay with `var _ int` inside the function literal but not `const _ = 0`.
