### ISSUE TITLE
x/tools/gopls: 'span' should support the import module path with upper-case

### ISSUE THREAD

**Issue by movie-travel-code** [golang/go#34230]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/henrywong/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/henrywong/workspace/gopath"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fm/bk0wqlkj523gdp9pbtnyvxmm0000gn/T/go-build295263798=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Clone **https://github.com/nytimes/gizmo** and put **gizmo** under module mode,   jump to definition for **gizmo/pubsub/kafka/config.go**: `Config *sarama.Config`. 

### What did you expect to see?
The expected trace log for the definition jump.
```shell
[Trace - 6:58:12 PM] Received response 'textDocument/definition - (5)' in 75ms.
Params: [{"uri":"file:///Users/henrywong/workspace/gopath/pkg/mod/github.com/!shopify/sarama@v1.23.1/config.go","range":{"start":{"line":20,"character":5},"end":{"line":20,"character":11}}}]
```

### What did you see instead?
There is **%21** in the uri. **%21** corresponds to **"!"**, the exclamation mark is intended, see https://github.com/golang/go/issues/26456.
```shell
[Trace - 6:58:12 PM] Received response 'textDocument/definition - (5)' in 75ms.
Params: [{"uri":"file:///Users/henrywong/workspace/gopath/pkg/mod/github.com/%21shopify/sarama@v1.23.1/config.go","range":{"start":{"line":20,"character":5},"end":{"line":20,"character":11}}}]
```
vscode-go can handle this because of https://github.com/microsoft/vscode/blob/master/src/vs/base/common/uri.ts#L478. However I think it would be better convert the **%21** back to **!** when gopls reply the result to the clients.

**Comment by stamblerre** [comment]
Does [CL 195618](https://go-review.googlesource.com/c/tools/+/195618) fix this for you?

**Comment by movie-travel-code** [comment]
It works for now, thanks!
