### ISSUE TITLE
x/build/cmd/coordinator: the "Go 1.12.x" suffix for trybots sometimes disappears

### ISSUE THREAD

**Issue by dmitshur** [golang/go#34234]
Trybots test on non-main repos by running on go tip and we have 2 builders that test the 2 current releases (1.13.x and 1.12.x). Those builders are supposed to have a suffix in the title so people can tell them apart, e.g.:

```
linux-amd64
linux-amd64 (Go 1.13.x)
linux-amd64 (Go 1.12.x)
```

I've noticed some trybot reports do not include the "Go 1.12.x" suffix in some occasions. For example:

https://go-review.googlesource.com/c/tools/+/191018/5#message-3523913181223269365a639f2de619f97c9748b8

Note it says:

```
2 of 10 TryBots failed:
Failed on linux-amd64 (Go 1.11.x): https://storage.googleapis.com/go-build-log/83bd8812/linux-amd64_473638fb.log
Failed on linux-amd64: https://storage.googleapis.com/go-build-log/61a5d114/linux-amd64_e368aff8.log
```

The second "linux-amd64" line should've been "linux-amd64 (Go 1.12.x)" because commit golang/go@61a5d114c2ede53b78bd0b02f95f7d5130526ac0 is on 1.12 release branch, not `master`.

/cc @bradfitz @toothrot

**Comment by dmitshur** [comment]
I've seen it happen to my own trybot run just now:

<details><br>

![image](https://user-images.githubusercontent.com/1924134/64697775-94895f80-d46f-11e9-93ea-2943f3d12095.png)

Note that it says "linux-amd64 rev [cf06b9aa](https://github.com/golang/go/commit/cf06b9aa81004a017e5c98422fce2fafd1f24921)", which is clearly a 1.12.x commit.

</details>

I think I have a lead where to start the investigation.

It seems to happen when a trybot builder is restarted due to a communication error. Specifically, I saw the "linux-amd64 (Go 1.12.x)" builder get a "failed to get a buildlet in 5 minutes" failure, and when it restarted, it said "linux-amd64" without the suffix.

The name is computed in [`buildStatus.NameAndBranch`](https://github.com/golang/build/blob/9b5ce82b5f7e4e56854bf17bc509caef1630354e/cmd/coordinator/coordinator.go#L3082-L3095) method, which looks correct.

So the issue is likely that the `goBranch` isn't set when a trybot builder is restarted.

**Comment by bradfitz** [comment]
Again:

<img width="483" alt="Screen Shot 2019-10-23 at 9 40 42 PM" src="https://user-images.githubusercontent.com/2621/67454109-dca6b080-f5dd-11e9-87dc-90495d3b3fcc.png">
