### ISSUE TITLE
x/tools/gopls: experimentalDisabledAnalyses doesn't work anymore

### ISSUE THREAD

**Issue by inliquid** [golang/go#34242]
I was using this setting for quite a while as per #31717
```
"gopls": {
    ...
    "experimentalDisabledAnalyses": ["composites"],
    ...
}
```
But with recent update from master it suddenly stopped working and can I see this garbage:
![изображение](https://user-images.githubusercontent.com/6797881/64730843-a2c79200-d4e8-11e9-99e9-44e9a843944a.png)

**Comment by stamblerre** [comment]
This was a mistake that crept into https://go-review.googlesource.com/c/tools/+/194278. Fixed in https://go-review.googlesource.com/c/tools/+/194682. 

We definitely need to add some tests to avoid regressions with the configuration options. I'll open a new issue.

**Comment by inliquid** [comment]
@stamblerre sorry, but it still doesn't work.

**Comment by stamblerre** [comment]
Ah sorry, should be fixed for real on master now (https://go-review.googlesource.com/c/tools/+/194818).
