### ISSUE TITLE
cmd/link: nil pointer dereference 

### ISSUE THREAD

**Issue by meme** [golang/go#34249]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +e7e2b1c2b9 Wed Sep 11 23:01:45 2019 +0000 linux/amd64
</pre>

(the latest `master`)

### Does this issue reproduce with the latest release?
Exists on 1.13, `master` and 1.12.9

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/keegan/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/keegan/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build542873266=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Created a file called `main.go`, with the following contents:
```go
package main

func main() {

}
```

Then ran the following commands:

```sh
$ go tool compile main.go
$ go tool link -buildmode=plugin main.o
```

### What did you expect to see?

As is the case with `go tool link main.o`, no output is produced and a `.so` file will be created.

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x4f80e7]

goroutine 1 [running]:
cmd/link/internal/sym.(*Symbol).AddUintXX(0x0, 0x83dda0, 0x0, 0x4, 0x80e9)
        /go/src/cmd/link/internal/sym/symbol.go:293 +0x47
cmd/link/internal/sym.(*Symbol).AddUint32(...)
        /go/src/cmd/link/internal/sym/symbol.go:149
cmd/link/internal/ld.addDwarfAddrField(0xc000056000, 0x0, 0x0)
        /go/src/cmd/link/internal/ld/dwarf.go:920 +0x88
cmd/link/internal/ld.createUnitLength(0xc000056000, 0x0, 0x0)
        /go/src/cmd/link/internal/ld/dwarf.go:912 +0x45
cmd/link/internal/ld.writeinfo(0xc000056000, 0x0, 0x852, 0x900, 0xc000080e80, 0x8, 0x8, 0xc0010ecff0, 0xc000464d08, 0xc000464cd8, ...)
        /go/src/cmd/link/internal/ld/dwarf.go:1572 +0x19c
cmd/link/internal/ld.dwarfGenerateDebugSyms(0xc000056000)
        /go/src/cmd/link/internal/ld/dwarf.go:1971 +0x517
cmd/link/internal/ld.(*Link).dodata(0xc000056000)
        /go/src/cmd/link/internal/ld/data.go:1753 +0x3491
cmd/link/internal/ld.Main(0x83dda0, 0x10, 0x20, 0x1, 0x7, 0x10, 0x692098, 0x1b, 0x68eb4d, 0x14, ...)
        /go/src/cmd/link/internal/ld/main.go:249 +0xcbb
main.main()
        /go/src/cmd/link/main.go:65 +0x1d6
```

At https://github.com/golang/go/blob/master/src/cmd/link/internal/sym/symbol.go#L289, `s` or, `self`, is `nil` and at https://github.com/golang/go/blob/master/src/cmd/link/internal/ld/dwarf.go#L1556 the `nil` symbol is loaded from the dwarf information. Strangely enough, disabling dwarf with `-dwarf=false` does not prevent this crash. 

Furthermore, when inserting the following code at the location above in `dwarf.go` to skip `nil` sections:

```go
if s == nil {
  continue
}
```

It will then trigger the following error when linking:

```
/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-502601380/go.o: relocation R_X86_64_TPOFF32 against symbol `runtime.tlsg' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

**Comment by agnivade** [comment]
@ianlancetaylor

**Comment by thanm** [comment]
Many programming tools expose features to make life easier for the developers of those tools. Consider GDB's "maintenance info program-spaces" command, or GCC's "-fdump-tree-all-all" command line options -- yes, they are exposed, but it's not expected that they be used by anyone other than developers of GCC or GDB. The go tool commands fall into the same category.

Regarding the crash on a weird combination of options -- this is surely a bug of some sort... would you like to send a patch?

**Comment by meme** [comment]
Thank you for the elaboration, I understand what you meant now. 

I suggested a patch that simply checks for `nil` before handling the symbol -- that seems to fix the issue. Though the program will still fail to link in the end (see the bottom of the original issue), so I am unable to verify that the resultant program is in working order (and that the `nil` check is an adequate one as a result). Suggestions are appreciated, else I am willing to just submit the check and assume that the linking error is a result of misuse of the tool (at least it's not a crash)
