### ISSUE TITLE
x/tools/gopls: return godoc.org reference in documentation

### ISSUE THREAD

**Issue by inliquid** [golang/go#34240]
I propose to add a feature (probably configuarable) when documentation request will result with a related `godoc.org` reference at the bottom, in same way as it's done in other editors/places.

For example, here is how standard VS Code HTML language feature returns reference to MDN for a `class` property documentation:
![изображение](https://user-images.githubusercontent.com/6797881/64726747-f4b7ea00-d4df-11e9-98d2-abfd1096792c.png)
And here is how it's done for Go in Goland:
![изображение](https://user-images.githubusercontent.com/6797881/64726946-609a5280-d4e0-11e9-856c-9b2ab05db4b9.png)
Latter have a link to `https://godoc.org/github.com/jinzhu/gorm#DB.Model`

I found it very useful.

**Comment by Southclaws** [comment]
I've picked this up https://go-review.googlesource.com/c/tools/+/200604

**Comment by stamblerre** [comment]
The above CL partially fixes this, as it doesn't handle methods or fields. A follow-up is needed to handle this.

**Comment by stamblerre** [comment]
This is complete as of the above CL.
