### ISSUE TITLE
x/tools/gopls: add tests for configuration options

### ISSUE THREAD

**Issue by stamblerre** [golang/go#34244]
We recently had a regression in the configuration options.
We should add tests to ensure that these options are applied correctly.

**Comment by andream16** [comment]
Hi @stamblerre , I would like to work on this. Can you be more specific? What should be tested?

**Comment by stamblerre** [comment]
The options are configured in https://github.com/golang/tools/blob/master/internal/lsp/source/options.go, and I think the way to test them would be by testing the different settings for features like "HoverKind" and "ExperimentalDisabledAnalyses". The options are modified through the tests (see [here](https://github.com/golang/tools/blob/d415e1c6f9573d887d4bd689c64f4fe3e417ce1e/internal/lsp/lsp_test.go#L104) and [here](https://github.com/golang/tools/blob/d415e1c6f9573d887d4bd689c64f4fe3e417ce1e/internal/lsp/source/source_test.go#L112)), but they could also be modified in the [internal/lsp/cmd](https://github.com/golang/tools/blob/master/internal/lsp/cmd/cmd_test.go) tests.

**Comment by msAlcantara** [comment]
Hi @stamblerre ,[ I created some tests for configuration options](https://github.com/msAlcantara/tools/commit/38780fe9fe29c13349a113a2acb0a4a5dbee6c5b), but the current documentation of [contributing](https://github.com/golang/tools/blob/master/gopls/doc/contributing.md) seems to be incomplete, and I would like to know if I can just send a PR on this repository on Github. Could you help me?

**Comment by stamblerre** [comment]
Awesome, thanks for doing that, @msAlcantara! You can absolutely send a PR--take a look at the instructions here: https://golang.org/doc/contribute.html, specifically https://golang.org/doc/contribute.html#sending_a_change_github.
