### ISSUE TITLE
cmd/go: incorrect message when replace target fails to resolve to correct module

### ISSUE THREAD

**Issue by myitcv** [golang/go#34256]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +396d625330 Thu Sep 12 07:45:53 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build854839250=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Consider the following [`testscript`](https://github.com/rogpeppe/go-internal/blob/master/cmd/testscript/README.md) test:

```
go mod tidy

-- tools.go --
// +build tools

package tools

import (
        _ "golang.org/x/tools/go/analysis"
        _ "golang.org/x/tools/gopls"
)

-- go.mod --
module example.com/hello

go 1.13

require (
        golang.org/x/tools v0.0.0-20190911230505-6bfd74cf029c
        golang.org/x/tools/gopls v0.1.5
)

replace golang.org/x/tools => github.com/myitcvforks/tools v0.0.0-20190911230505-6bfd74cf029c

replace golang.org/x/tools/gopls => github.com/myitcvforks/tools v0.0.0-20190911230505-6bfd74cf029c
```

### What did you expect to see?

An error telling me the replace for `golang.org/x/tools/gopls` is incorrect because the target of the replace is the module `golang.org/x/tools`

### What did you see instead?

```
go: github.com/myitcvforks/tools@v0.0.0-20190911230505-6bfd74cf029c: parsing go.mod:
        module declares its path as: golang.org/x/tools
                but was required as: github.com/myitcvforks/tools
```

cc @bcmills @jayconrod

**Comment by bcmills** [comment]
Seems to be fixed as of Go 1.16. (I'm not sure when exactly, but there have been a lot of fixes in the module loader this cycle.)

```
hello$ go mod tidy
go: golang.org/x/tools/gopls@v0.1.5 (replaced by github.com/myitcvforks/tools@v0.0.0-20190911230505-6bfd74cf029c): parsing go.mod:
        module declares its path as: golang.org/x/tools
                but was required as: golang.org/x/tools/gopls
```
