### ISSUE TITLE
Duration literals

### ISSUE THREAD

**Issue by mcandre** [golang/go#34267]
Proposal: Duration literals for Go values and associated JSON, YAML representations, in order to reduce the likelihood of mistakes in application configurations.

No more forgetting, wondering about days vs nanoseconds vs seconds vs hours months vs business quarters vs milliseconds. No more gaps and misleading statements in documentation.

No more conversion errors. Just human readable durations, direct to well-defined machine values.

ISO 8601 format for duration literals would be a good place to start.

https://www.digi.com/resources/documentation/digidocs/90001437-13/reference/r_iso_8601_duration_format.htm

**Comment by bcmills** [comment]
> No more conversion errors.

See also #20757.
