### ISSUE TITLE
doc: go:noinline directives in godoc

### ISSUE THREAD

**Issue by randall77** [golang/go#34276]
In the docs for `runtime.Callers` https://golang.org/pkg/runtime/#Callers , the text ends with `go:noinline`. We probably shouldn't include that part (or any `go:` directive) in the godoc.

This occurs in some internal packages as well, like `runtime/internal/atomic`.

**Comment by bcmills** [comment]
My impression from previous comments (https://github.com/golang/go/issues/32816#issuecomment-507721945) is that `//go:` directives are intended to be placed *before* the affected declaration, separated from the doc comment by a blank line. Does that work for `//go:noinline` directives?

**Comment by bcmills** [comment]
That does, at least, suggest that we should have a `vet` or `lint` warning for misplaced `//go:` directives. (CC @ianthehat @dominikh)

**Comment by ianlancetaylor** [comment]
I don't think we should have godoc remove these comments, as that would be confusing when the function's doc is in fact intended to include such a comment.  Similarly, I don't think a `go vet` warning would be appropriate, although a `golint` one would be fine.

Let's just fix the cases as @bcmills suggests, which is how it is supposed to be used anyhow.

**Comment by toothrot** [comment]
Adding NeedsFix, as positioning the `//go:` directives resolves the issue, and it seems straightforward.

runtime.KeepAlive is a good example: https://github.com/golang/go/blob/115e4c9c14779f2561de4299b5748b98d7dd8cf0/src/runtime/mfinal.go#L424-L427

runtime.KeepAlive docs: https://godoc.org/runtime#KeepAlive

**Comment by randall77** [comment]
Closing. `runtime.Callers` has been fixed, and it sounds like we should just move the comments instead of fixing godoc.
