### ISSUE TITLE
x/sys/windows: add ExitWindowsEx

### ISSUE THREAD

**Issue by bruceadowns** [golang/go#34271]
### What version of Go are you using (`go version`)?

<pre>
C:\Users\Bruce Downs>go version
go version go1.13 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
C:\Users\Bruce Downs>go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Bruce Downs\AppData\Local\go-build
set GOENV=C:\Users\Bruce Downs\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Bruce Downs\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\BRUCED~1\AppData\Local\Temp\go-build181801726=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Tried to find windows reboot functionality in the standard library, but it was only found for linux.

### What did you expect to see?

For Windows to have parity capability as linux.

<pre>
import "golang.org/x/sys/unix"
unix.Reboot(...)
</pre>

### What did you see instead?

Mention of ExitWindowsEx is missing in the standard library.

The following api will need to be added to /x/sys/windows:
ExitWindowsEx

The following apis will need to be moved from internal/syscall/windows:
LookupPrivilegeValue
AdjustTokenPrivileges

along with their various const dependencies.

**Comment by alexbrainman** [comment]
> I was looking to extend the standard library for the better on windows.

Sounds good to me. What exactly do you propose?

Adding @zx2c4, because he makes most changes to golang.org/x/sys/windows lately.

Alex

**Comment by zx2c4** [comment]
I've got some plans to add some token manipulation functions. I'll try to add `ExitWindowsEx` too.

**Comment by bruceadowns** [comment]
> > I was looking to extend the standard library for the better on windows.
> 
> Sounds good to me. What exactly do you propose?

Thanks @alexbrainman and @zx2c4!

My initial plan was to take the following calls:

<pre>
windows.OpenProcessToken()
LookupPrivilegeValue.Call()
AdjustTokenPrivileges.Call()
syscall.GetLastError()
ExitWindowsEx.Call()
</pre>

And make them look more like:

<pre>
windows.OpenProcessToken()
windows.LookupPrivilegeValue()
windows.AdjustTokenPrivileges()
windows.GetLastError()
windows.ExitWindowsEx()
</pre>

Some would need to be added and some would need to be ported from internal/syscall/windows. This would also include adding/moving the relevant constants.

This will offer a more streamline experience similar to https://docs.microsoft.com/en-us/windows/win32/shutdown/how-to-shut-down-the-system.

**Comment by zx2c4** [comment]
> windows.GetLastError()

This is already returned by syscall.SyscallN as one of its return values.

**Comment by alexbrainman** [comment]
> My initial plan was to take the following calls:

Try and write it yourself. And show your code, if you are not sure. We will correct it, if need be.

Maybe we could put it all into golang.org/x/sys/windows.Reboot function (or similar name). Maybe we could even put it into golang.org/x/sys.Reboot function, if there is enough interest.

Alex

**Comment by zx2c4** [comment]
@bruceadowns let me know if that implementation is suitable.

**Comment by zx2c4** [comment]
> Maybe we could put it all into golang.org/x/sys/windows.Reboot function (or similar name).

This is hard to do because different contexts require different calls. We could probably detect an interactive session and try to convert the arguments between the different types of calls, but that doesn't seem trivial.

> Maybe we could even put it into golang.org/x/sys.Reboot function, if there is enough interest.

Also a cool idea, but isn't shutdown somewhat different on different platforms, which have different notions of sessions and window stations and shutdown states and stuff?

**Comment by bruceadowns** [comment]
> @bruceadowns let me know if that implementation is suitable.

Sweet! I'll look at it later today.

**Comment by alexbrainman** [comment]
> but isn't shutdown somewhat different on different platforms, which have different notions of sessions and window stations and shutdown states and stuff?

I would not know. I am not really a Windows expert. Forget my suggestion.

Alex
