### ISSUE TITLE
x/net/html: tokenizer error

### ISSUE THREAD

**Issue by pidario** [golang/go#34281]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/dario/.local/bin"
GOCACHE="/home/dario/.cache/go-build"
GOENV="/home/dario/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dario/.local/lib/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/dario/gows/testhtmltoken/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build579414839=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I was extracting titles and meta tags from webpages and I found out that, if a title tag contains a `<` at the end, the tokenizer cannot tell when the text tag ends and the closing tag starts.

https://play.golang.org/p/KO2-PEfpccQ

### What did you expect to see?
```
tag: 'title'
text: 'title ko<'
tag: 'title'
text: 'title ok'
```

### What did you see instead?
```
tag: 'title'
text: 'title ko<</title>'
tag: 'title'
text: 'title ok'
```

**Comment by nigeltao** [comment]
Yeah, it's probably a bug in the HTML tokenizer.

It's been a while since I've looked at https://www.w3.org/TR/html52/syntax.html#tokenization. Somebody would need to figure out how it maps back to the token.go code and therefore what the spec-compliant fix is.

I don't have a lot of spare time right now. Sorry.

**Comment by pidario** [comment]
Thanks for the feedback.

Neither do I but I'll see if I can find some time to work on it.

**Comment by namusyaka** [comment]
@nigeltao Since we haven't conformed the spec in the tokenizer implementation, I've reviewed the CL and suggested the quick fix considering the whatwg spec. This is a best effort totally.
