### ISSUE TITLE
why we are not allowed to add method to existing go type (as long as they dont conflict)

### ISSUE THREAD

**Issue by acnologia000** [golang/go#34287]
### What version of Go are you using (`go version`)?

<pre>
$ go version

1.13
</pre>

### Does this issue reproduce with the latest release?

its related to language design

### What operating system and processor architecture are you using (`go env`)?
windows amd 64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

tried to add method to existing go type

### What did you expect to see?

string_var.containts("query string") to be a valid operation of string type

### What did you see instead?

err : cannot define new methods on non-local type string

**Comment by mvdan** [comment]
See https://stackoverflow.com/questions/28800672/how-to-add-new-methods-to-an-existing-type-in-go and https://github.com/golang/go/issues/21401, for instance; this has been covered in the past.
