### ISSUE TITLE
Error occurred when I call the function from dynamic library (.so)

### ISSUE THREAD

**Issue by xiaofo09** [golang/go#34289]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xiaofo/.cache/go-build"
GOENV="/home/xiaofo/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xiaofo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build062927736=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I tried to load dynamic library(.so) using cgo. My code is related to Intel SGX library. I converted "sgx_create_enclave" (unsafe pointer) to origin prototype.

```
package main

/*
#cgo LDFLAGS: -ldl
#include <dlfcn.h>
#include "include/sgx_urts.h"
*/
import "C"
import (
  "fmt"
)

type SGX_CREATE_ENCLAVE func(*C.char, C.int, *C.sgx_launch_token_t, *C.int, *C.sgx_enclave_id_t, *C.sgx_misc_attribute_t)C.sgx_status_t


func main() {
  var sgx_create_enclave SGX_CREATE_ENCLAVE
  var global_eid C.sgx_enclave_id_t

  handle := C.dlopen(C.CString("libsgx_urts.so"), C.RTLD_LAZY)
  sgx_create_enclave = (SGX_CREATE_ENCLAVE)C.dlsym(handle, C.CString("sgx_create_enclave"))

  fmt.Println("sgx_create_enclave is at %p", sgx_create_enclave)
  ret := sgx_create_enclave(C.CString("enclave.signed.so"), C.SGX_DEBUG_FLAG, nil, nil, &global_eid, nil)
}
```

### What did you expect to see?

Calling sgx_create_enclave successfully without error.

### What did you see instead?

```
# command-line-arguments
./sample.go:21:44: expected ';', found C
./sample.go:25:3: expected '}', found 'EOF'
```

**Comment by xiaofo09** [comment]
If I change line 21 like this:
`sgx_create_enclave = C.dlsym(handle, C.CString("sgx_create_enclave"))`

This error occurred:
```
# command-line-arguments
./sample.go:21:22: cannot use (func literal)() (type unsafe.Pointer) as type SGX_CREATE_ENCLAVE in assignment
```

**Comment by ianlancetaylor** [comment]
Calling `C.dlsym` gives you a C function pointer.  You can't convert a C function into a Go function, and you cannot call C function pointers directly.  See https://golang.org/cmd/cgo/#hdr-Go_references_to_C.  What you can do is pass a C function to a C function that calls it.

Closing because there is nothing to fix in the Go tools.
