### ISSUE TITLE
net/http/httptrace: panic on GotConn

### ISSUE THREAD

**Issue by cuonglm** [golang/go#34282]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +03f63654c4 Thu Sep 12 21:02:57 2019 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/cuonglm/Library/Caches/go-build"
GOENV="/Users/cuonglm/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/cuonglm/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/cuonglm/sources/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/cuonglm/sources/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/y4/hs76ltbn7sb66lw_6934kq4m0000gn/T/go-build718378058=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
package main

import (
	"context"
	"log"
	"net/http"
	"net/http/httptrace"
	"sync"
)

func gotConn(info httptrace.GotConnInfo) {
	_ = info.Conn.RemoteAddr
}

func doGet() {
	ctx := httptrace.WithClientTrace(context.Background(), &httptrace.ClientTrace{
		GotConn: gotConn,
	})

	req, _ := http.NewRequest(http.MethodGet, "https://google.com", nil)
	req = req.WithContext(ctx)

	if _, err := http.DefaultClient.Do(req); err != nil {
		log.Println(err)
	}
}

func main() {
	var wg sync.WaitGroup
	n := 1000
	wg.Add(n)

	for i := 0; i < n; i++ {
		go func() {
			defer wg.Done()
			doGet()
		}()
	}

	wg.Wait()
}
```

Thanks @tmthrgd for simpler and not racy program.

### What did you expect to see?

Run successfully.

### What did you see instead?

Panic

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12ad645]

goroutine 72 [running]:
main.gotConn(0x0, 0x0, 0x1a500101, 0xc0ce52)
	/Users/cuonglm/sources/goissues/34282/trace.go:12 +0x5
net/http.(*Transport).getConn(0x15cc420, 0xc0025eec60, 0x0, 0x135530c, 0x5, 0xc0029f1650, 0xe, 0x0, 0x0, 0x0, ...)
	/Users/cuonglm/sdk/go1.13/src/net/http/transport.go:1210 +0x394
net/http.(*Transport).roundTrip(0x15cc420, 0xc00027e900, 0x0, 0xc00020ab20, 0x100e118)
	/Users/cuonglm/sdk/go1.13/src/net/http/transport.go:522 +0x603
net/http.(*Transport).RoundTrip(0x15cc420, 0xc00027e900, 0x15cc420, 0x0, 0x0)
	/Users/cuonglm/sdk/go1.13/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc00027e900, 0x13be5a0, 0x15cc420, 0x0, 0x0, 0x0, 0xc000282050, 0x203000, 0x1, 0x0)
	/Users/cuonglm/sdk/go1.13/src/net/http/client.go:250 +0x43a
net/http.(*Client).send(0x15d1200, 0xc00027e900, 0x0, 0x0, 0x0, 0xc000282050, 0x0, 0x1, 0x13479a0)
	/Users/cuonglm/sdk/go1.13/src/net/http/client.go:174 +0xfa
net/http.(*Client).do(0x15d1200, 0xc00027e900, 0x0, 0x0, 0x0)
	/Users/cuonglm/sdk/go1.13/src/net/http/client.go:641 +0x3ce
net/http.(*Client).Do(...)
	/Users/cuonglm/sdk/go1.13/src/net/http/client.go:509
main.main.func1(0xc00001c340, 0x13c3a40, 0xc0000ceab0)
	/Users/cuonglm/sources/goissues/34282/trace.go:31 +0x18c
created by main.main
	/Users/cuonglm/sources/goissues/34282/trace.go:25 +0xeb
exit status 2
```

The program works in go1.12, panic on go1.13 as well as tip.

**Comment by agnivade** [comment]
Want to do a bisect ? :slightly_smiling_face: 

@bradfitz

**Comment by ALTree** [comment]
You have multiple goroutines calling `Do()` concurrently, the call stack looks like this (from the bottom):

```
  main.(*transport).RoundTrip()
  net/http.send()
  net/http.(*Client).send()
  net/http.(*Client).do()
```
So there's a data race at the `t.current = req` line in `RoundTrip`.

This also appears to happen in go1.12 too, btw.

**Comment by cuonglm** [comment]
> You have multiple goroutines calling `Do()` concurrently, and a call stack that looks like this (from the bottom):
> 
> ```
>   main.(*transport).RoundTrip()
>   net/http.send()
>   net/http.(*Client).send()
>   net/http.(*Client).do()
> ```
> 
> So there's a data race at the `t.current = req` line in `RoundTrip`.
> 
> The call stack is the same in go1.12, btw.

The GotConn panic is from `httptrace`, go1.12 never trigger the panic in my test.

**Comment by ALTree** [comment]
Run `go run -race test.go` in your reproducer with go1.12 and it'll report the same race.

**Comment by cuonglm** [comment]
> Run `go run -race test.go` on your reproducer with go1.12 and it'll report the same race.

Just skipping the race, here in normal run, go1.12 succeeded, while go1.13 trigger a panic.

**Comment by ALTree** [comment]
It doesn't matter. If the program has a data race, it's not a valid Go program. 

Maybe there was a 1.13 change in the runtime or in the http package that made the crash more likely to trigger.

**Comment by tmthrgd** [comment]
Here is a simpler reproducer that shows the same crash:

```go
package main

import (
	"context"
	"log"
	"net/http"
	"net/http/httptrace"
	"sync"
)

func gotConn(info httptrace.GotConnInfo) {
	_ = info.Conn.RemoteAddr
}

func main() {
	ctx := httptrace.WithClientTrace(context.Background(), &httptrace.ClientTrace{
		GotConn: gotConn,
	})

	var wg sync.WaitGroup
	n := 1000
	wg.Add(n)

	for i := 0; i < n; i++ {
		go func() {
			defer wg.Done()

			req, _ := http.NewRequest(http.MethodGet, "https://google.com", nil)
			req = req.WithContext(ctx)

			if _, err := http.DefaultClient.Do(req); err != nil {
				log.Println(err)
			}
		}()
	}

	wg.Wait()
}
```

**Comment by cuonglm** [comment]
@ALTree The example of @tmthrgd above is not racy and produce the panic.

**Comment by ALTree** [comment]
In general, it's better not to edit the original message. Now people reading the thread from the start will get confused by our initial discussion about code that doesn't exit any more. I'll mark our messages as outdate to hide them.

**Comment by tmthrgd** [comment]
I think the problem might be some kind of race condition in `queueForIdleConn` around `t.idleConn`.

This is where the call to `GotConn` with a nil `info.Conn` is happening:

https://github.com/golang/go/blob/98aa97806b94495847f7f7151d4453f5830f0d38/src/net/http/transport.go#L1196-L1199

Nothing touches `w` before `queueForIdleConn`, which can only ever return true here:

https://github.com/golang/go/blob/98aa97806b94495847f7f7151d4453f5830f0d38/src/net/http/transport.go#L936

Running the go program above in delve, I'm seeing a `persistConn` with `conn == nil` at the call to `tryDeliver` here:

https://github.com/golang/go/blob/98aa97806b94495847f7f7151d4453f5830f0d38/src/net/http/transport.go#L916

**Comment by cuonglm** [comment]
git bisect points to 43b9fcf6fe9feb0ec67a7ddb01e5b542542b47c8

**Comment by tmthrgd** [comment]
After 43b9fcf, `dialConn` can return a `persistConn` with `conn == nil` here:

https://github.com/golang/go/blob/98aa97806b94495847f7f7151d4453f5830f0d38/src/net/http/transport.go#L1535

That `persistConn` is then being put in `t.idleConn` by `tryPutIdleConn` and pulled out by `queueForIdleConn`.

When there aren't any idle connections available, x/net/http2 calls `GotConn` itself, see here:

https://github.com/golang/go/blob/98aa97806b94495847f7f7151d4453f5830f0d38/src/net/http/transport.go#L1217-L1221

Is the bug here simply that this call is missing the HTTP/2 specific check?

https://github.com/golang/go/blob/98aa97806b94495847f7f7151d4453f5830f0d38/src/net/http/transport.go#L1198-L1200

**Comment by cuonglm** [comment]
@tmthrgd `w.pc.alt == nil` guarantees HTTP/1

**Comment by tmthrgd** [comment]
CL 195237 fixes the panic, but is missing a test case.

---

@cuonglm If you're looking for a temporary workaround, either:

```go
http.DefaultTransport.(*http.Transport).DisableKeepAlives = true
```

or 

```go
http.DefaultTransport.(*http.Transport).MaxIdleConnsPerHost = -1
```

will stop the problematic `persistConn` from being put in the idle pool

**Comment by cuonglm** [comment]
@gopherbot please consider this for backport 1.13
