### ISSUE TITLE
Sorry, the SMTP package is frozen. Please fork it and add features on Github. We should have never included it in the standard library.

### ISSUE THREAD

**Issue by oslnx** [golang/go#34296]
@bradfitz, people like you shouldn't participate in these types of projects, the concept of this language is to make it easy and you do exactly the opposite.

---------
Sorry, the SMTP package is frozen. Please fork it and add features on Github. We should have never included it in the standard library. 

I'll keep this bug open to document that it's frozen though. We'll fix bugs but not add features.

_Originally posted by @bradfitz in https://github.com/golang/go/issues/16436#issuecomment-233823790_

**Comment by dsnet** [comment]
Hi @oslnx, do you have specific action item you are trying to pursue here? It's not clear to me what you are trying to accomplish.

If I understand correctly, it seems that you are objecting to @bradfitz declaring the `net/smtp` package being frozen. As the owner of the package, @bradfitz has the right to decide when to sunset and deprecate a package. It isn't reasonable to expect every author to be the perpetual owner and maintainer of all code they ever write. Maintaining code has real cost and the Go team does not have an infinite amount of resource to spend maintaining all software ever written by them. It is appropriate for authors to decide that certain packages should continue maintenance while others be deprecated.

Understandably, the deprecation of a package may not be ideal for a given user, but that is the beauty of open source. People are free to fork the code and maintain a new version of it with new features.

> people like you shouldn't participate in these types of projects, the concept of this language is to make it easy and you do exactly the opposite.

I'm not sure how this is a helpful objection. Everyone writes code that in hind-sight may have been a mistake. No one has the ability to see into a future for whether any given technical decision was a mistake or not. If you're unclear of what's helpful feedback, please see https://golang.org/conduct.

**Comment by ianlancetaylor** [comment]
Closing the issue as there doesn't seem to be any action to take.
