### ISSUE TITLE
tools/internal: tool.Main should be refactored to simplify testing.

### ISSUE THREAD

**Issue by hartzell** [golang/go#34291]
### What version of Go are you using (`go version`)?

<pre>
(alice)[14:30:23]tools>>go version
go version go1.12.9 darwin/amd64
(alice)[14:40:51]tools>>
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
(alice)[14:40:51]tools>>go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hartzell/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/hartzell/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.9/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.9/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/hartzell/tmp/golang/tools/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f7/fcb363190nz0jbypndp3nj_m0000gn/T/go-build454450712=/tmp/go-build -gno-record-gcc-switches -fno-common"
(alice)[14:41:13]tools>>
</pre></details>

# The issue

CL 194878 is making the GoPls rename functionality available from the command line.  The rename test suite includes mostly successful tests (when run on this input you should get this output), but two cases are designed to generate errors, which are passed up the call chain.

tool.Main is the main entry point for the command line tools.  It is explicitly intended to be called by application main() routines.  If/when it encounters an error it prints the error to standard error and exists with a non-zero status (2).

tool.Main is also invoked internally and from various test functions.  Exiting when the underlying functionality being exercised makes testing difficult, unnecessarily.  For example, it causes false negatives (tests fail that shouldn't) in the the work-in-progress (https://go-review.googlesource.com/c/tools/+/194878/5) to implement `gopls rename`.

A simple fix is to break the functionality into two parts, calling the outer from main() functions and calling the inner bits internally and in tests.

I have a change ready that implements this.

**Comment by hartzell** [comment]
@toothroot -- this is only used in `gopackages` and `gopls`.  Is/should it be tied to a Go release (I'm always learning...)?

**Comment by toothrot** [comment]
@hartzell Whoops! My mistake, thanks for catching this.

**Comment by hartzell** [comment]
This was fixed in [cl195338](https://go-review.googlesource.com/c/tools/+/195338).
