### ISSUE TITLE
cmd/cgo: cannot use environment variable in #cgo directive

### ISSUE THREAD

**Issue by xiaofo09** [golang/go#34303]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/xiaofo/Dropbox/instapay/bin"
GOCACHE="/home/xiaofo/.cache/go-build"
GOENV="/home/xiaofo/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xiaofo/Dropbox/instapay"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build518041470=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I created an environment variable on my linux
```
xiaofo@xiaofo-desktop:~/Dropbox/instapay/se$ export SGXSDK=/home/xiaofo/sgxsdk
xiaofo@xiaofo-desktop:~/Dropbox/instapay/se$ echo $SGXSDK
/home/xiaofo/sgxsdk
```
And I wrote following code and executed it.
```
xiaofo@xiaofo-desktop:~/Dropbox/instapay/se$ cat main.go
package main

/*
#cgo CPPFLAGS: -I$(SGXSDK)/include
#include "sgx_urts.h"
*/
import "C"

func main() {
}
xiaofo@xiaofo-desktop:~/Dropbox/instapay/se$ go run main.go
package main: /home/xiaofo/Dropbox/instapay/se/main.go: malformed #cgo argument: -I$(SGXSDK)/include
```
I tried ${SGXSDK}, $(SGXSDK), $SGXSDK, "${SGXSDK}", "$(SGXSDK)" and so on. Everything does not work. But

`#cgo CPPFLAGS: -I/home/xiaofo/sgxsdk/include`

works

### What did you expect to see?

I expected that it runs without any error.

### What did you see instead?

`package main: /home/xiaofo/Dropbox/instapay/se/main.go: malformed #cgo argument: $(SGXSDK)/include`

**Comment by xiaofo09** [comment]
or should I use directives in goenv only ?

**Comment by odeke-em** [comment]
Thank you for asking this question @xiaofo09!

We usually we use golang-nuts for searching for/asking questions like these and the issue tracker for bugs that might be a problem in Go itself.
Please see https://github.com/golang/go/wiki/Questions for resources.

A similar question and answer is at https://groups.google.com/forum/#!msg/golang-nuts/yteBY_UXsac/1XPNTV7Xe34J;context-place=msg/golang-nuts/Wh_XWeOTGak/XCJKM0U7-lMJ where Minux showed how to use the CGO_FLAGS and CGO_LDFLAGS to pass in variables before go build/install. 

cc @ianlancetaylor.
