### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by zu1k** [golang/go#34304]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/king/.cache/go-build"
GOENV="/home/king/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/king/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build325664144=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

The issue appear through the usage of clash
https://github.com/Dreamacro/clash

### What did you expect to see?
A human-readable error message, like in a case of bufio.Reader with the same io.Reader implementation
https://play.golang.org/p/AKl7_zzjhx

panic: bufio: reader returned negative count from Read

### What did you see instead?
```
panic: runtime error: slice bounds out of range [:1179] with capacity 517

goroutine 9551 [running]:
bytes.(*Buffer).ReadFrom(0xc0001cfad8, 0x9ac860, 0xc00051c5a0, 0x409bdc, 0x885140, 0x8d31e0)
  /usr/local/go/src/bytes/buffer.go:209 +0x1b9
crypto/tls.(*Conn).readFromUntil(0xc0001cf880, 0xf54308, 0xc000d80210, 0x5, 0xc000d80210, 0xc0014e9a18)
  /usr/local/go/src/crypto/tls/conn.go:802 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc0001cf880, 0xc0014e9c00, 0x5c59a6, 0xc0001cfa48)
  /usr/local/go/src/crypto/tls/conn.go:609 +0x12b
crypto/tls.(*Conn).readRecord(...)
  /usr/local/go/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).readHandshake(0xc0001cf880, 0xc000f52116, 0xc000f52180, 0x106, 0x180)
  /usr/local/go/src/crypto/tls/conn.go:993 +0x74
crypto/tls.(*Conn).clientHandshake(0xc0001cf880, 0x0, 0x0)
  /usr/local/go/src/crypto/tls/handshake_client.go:171 +0x1a4
crypto/tls.(*Conn).Handshake(0xc0001cf880, 0x0, 0x0)
  /usr/local/go/src/crypto/tls/conn.go:1362 +0x132
net/http.(*persistConn).addTLS.func2(0x0, 0xc0001cf880, 0xc0001ad090, 0xc001218f60)
  /usr/local/go/src/net/http/transport.go:1401 +0x49
created by net/http.(*persistConn).addTLS
  /usr/local/go/src/net/http/transport.go:1397 +0x1b1
```

**Comment by Dreamacro** [comment]
系统 平台 版本

**Comment by ianlancetaylor** [comment]
In this case it sounds like the reader is returning a number of bytes that is larger than the number of bytes that were requested.  That is, it sounds like there is a bug in the underlying reader.  We could explicitly test for all possible reader failures, but I don't see why it is worth it.  The important thing is that the code fails.

**Comment by toothrot** [comment]
@zu1k It's not clear to me that there is a bug in Go here, or that buffer should be changed to be defensive against all possible bugs in underlying readers. I'm going to close this issue, but please comment if I have misunderstood or you disagree. It sounds like it's worth filing a bug with clash.
