### ISSUE TITLE
how to print string which in slice  (html/template)

### ISSUE THREAD

**Issue by angelandy** [golang/go#34317]
### What version of Go are you using (`go version`)?

<pre>
$ go version
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/angelandy/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/media/angelandy/4f95d6b7-a5ba-4a10-9232-6017dcced1d8/angelandy/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.12"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.12/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build271133787=/tmp/go-build -gno-record-gcc-switches"

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
package main

import (
	"os"
	"text/template"
)

func main() {
	// Define a template.
	const tmpl = `this is a test {{.list[1]}}`

	// Prepare some data to insert into the template.

	var UserList = []string{
		"aaaaa",
		"bbbbb",
		"ccccc",
		"ddddd",
	}
	td := map[string]interface{}{
		"name":    "test",
		"list":    UserList,
	}

	// Create a new template and parse the letter into it.
	t := template.Must(template.New("tmpl").Parse(tmpl))

	t.Execute(os.Stdout, td)
}

### What did you expect to see?

i want : "  this is a test bbbbb"

**Comment by angelandy** [comment]
but It failed
panic:
 unexpected bad character U+005B '[' in command

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker for questions.  Please see https://golang.org/wiki/Questions.

In this case the problem is that the template language doesn't support indexing like `[1]`.

I think what you want is https://play.golang.org/p/Xxn_ksCzWJL.

**Comment by angelandy** [comment]
well,  thank you very much
