### ISSUE TITLE
"$GOPATH not set" - keep getting this error even though it is set

### ISSUE THREAD

**Issue by Jeff4004** [golang/go#34323]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.13

</pre>

### What operating system and processor architecture are you using (`go env`)?  Ubuntu 16.04 / AMD64 architecture

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
![go env](https://user-images.githubusercontent.com/52179214/64972296-a8b5ce00-d86e-11e9-8388-9344956e71cc.PNG)

### What did you do?   Set the $GOPATH environment variable per instructions found on numerous websites

  
sudo go get github.com/google/stenographer

### What did you see instead?
package github.com/google/stenographer:  cannot download, $GOPATH not set.

Keep getting the above error message despite verifying $GOPATH is set, and following instructions on numerous websites:

https://github.com/golang/go/wiki/SettingGOPATH
https://golang.org/doc/install
https://stackoverflow.com/questions/21001387/how-do-i-set-the-gopath-environment-variable-on-ubuntu-what-file-must-i-edit/27491937
https://stackoverflow.com/questions/21001387/how-do-i-set-the-gopath-environment-variable-on-ubuntu-what-file-must-i-edit/27491937

I'm simply trying to download/install Stenographer per instructions provided on GithHub.  Does anyone know how I can get past this error message?  

Thank you in advance for any help that can be provided.
~Jeff S.

![go env](https://user-images.githubusercontent.com/52179214/64973092-04cd2200-d870-11e9-822e-b044b5f16c8e.PNG)
![environment variables](https://user-images.githubusercontent.com/52179214/64973093-04cd2200-d870-11e9-93e0-4322f63bc0fa.PNG)

**Comment by hyangah** [comment]
what does `sudo go env` report?

**Comment by Jeff4004** [comment]
Thank you for the reply, hyangah.  The GOPATH variable was correct when doing sudo go env.  That was part of my confusion because the error message indicated it wasn't set.  But having said that, it turned out to be a permissions issue.  I changed ownership of the folder used in my GOPATH from root to myself and then was able to download Stenographer.
