### ISSUE TITLE
Package management

### ISSUE THREAD

**Issue by pureyb** [golang/go#34337]
### What version of Go are you using (`go version`)?

<pre>
$ 1.12.7

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/Users/bo/go/bin"
GOCACHE="/Users/bo/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/bo/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lv/lqhz26552n3dz3578fdm2v6r0000gn/T/go-build756509035=/tmp/go-build -gno-record-gcc-switches -fno-common"
$ go env

</pre></details>

### What did you do?

We hope to provide a unified package management platform, like node's NPM and python's PIP, without going to github clone.

### What did you expect to see?

We hope to provide a unified package management platform, like node's NPM and python's PIP, without going to github clone.

### What did you see instead?
We hope to provide a unified package management platform, like node's NPM and python's PIP, without going to github clone.

**Comment by ALTree** [comment]
Hi,

Go does have package management, in the form of modules (recently introduced). Dependencies are automatically downloaded and managed, and they don't need to be hosted on github. They can be hosted on many other places, including private servers.

For an introduction to modules, you can read the [Modules Blog Post](https://blog.golang.org/using-go-modules).

If you have further questions, please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!
