### ISSUE TITLE
x/build: add x/tools trybot for main Go repository

### ISSUE THREAD

**Issue by dmitshur** [golang/go#34348]
As @jayconrod suggested in https://github.com/golang/go/issues/34321#issuecomment-531885130, I think we should add an x/tools trybot builder for the main Go repository. It would check whether x/tools tests on master branch pass with the Go CL being tested. We can use `linux-amd64` builder type since it's quick and least expensive.

The Go standard library ships with many packages such as `go/parser`, `go/types`, and others. The x/tools repository has many tests that provide additional test coverage.

Trybots for the main Go repository already take 5-10 minutes to run, while the x/tools tests take less than 5 minutes, so it wouldn't slow anything down, just provide more test coverage.

/cc @bradfitz @andybons @toothrot

**Comment by stamblerre** [comment]
Just wanted to chime in here to say that this would be extremely helpful for people developing in x/tools. `go/packages` and `goimports` depend on the behavior of `go list`, so if a breaking change is made in the `go` command, we may only notice the problem a few hours after the CL is submitted, and then someone gets interrupted figuring out the relevant CL and required fix. It would be really helpful to know about breaking changes upfront (even if they still get submitted). If there's anything I can do to help move this forward, I'd be happy to.

**Comment by bradfitz** [comment]
@stamblerre, look at x/build/cmd/coordinator and where the recent slowbots code hooks and modifies the try set. I suspect this would also live there. We'd just add a build that's for "tools" instead of "go". There's a func getRepoHead that'll tell you which git rev of x/tools to use.

While I agree we should include x/tools by default, I also think the slowbots should let us opt in to testing any x/ repo. Maybe `TRY=x/foo`, using `x/foo` for the opt-in TRY tokens.

**Comment by stamblerre** [comment]
Thanks for the guidance, @bradfitz! Just mailed [CL 203677](https://go-review.googlesource.com/c/build/+/203677/), though I'm not sure about the correct way to test it.

**Comment by stamblerre** [comment]
As of https://golang.org/cl/203917, you should now be able to comment "TRY=x/tools" on CLs that may be relevant to changes in x/tools (see https://golang.org/cl/201203 as an example). 

@jayconrod and @bcmills: do you mind testing this out on your next few CLs to see if it works well for you? The next step would be to trigger it by default when certain directories or files are changed.

**Comment by dmitshur** [comment]
I think we're in favor of always including x/tools as described in the original issue, so I'll update the status to NeedsFix.

We can always revisit this decision and adjust it if it turns out to be more noisy than helpful.
