### ISSUE TITLE
x/xerrors: clarify documentation around stack frames 

### ISSUE THREAD

**Issue by samcgardner** [golang/go#34349]
The docs for the `x/xerrors` package currently state

```
Most of the functions and types in this package will be incorporated into the standard library's errors package in Go 1.13; the behavior of this package's Errorf function will be incorporated into the standard library's fmt.Errorf. 
```

This is not accurate. `fmt.Errorf` does _not_ provide the stack-trace functionality of `xerrors.Errorf`. Accordingly, I would suggest changing this docstring to

```
Most of the functions and types in this package have been incorporated into the standard library's errors package in Go 1.13. However, if you wish to retain the stack trace functionality of `xerrors.Errorf`, you will need to keep using this package.
```

**Comment by flibustenet** [comment]
Is there an issue to follow if stack trace will be part of go1.14 ?

**Comment by jba** [comment]
I wrote https://go-review.googlesource.com/c/xerrors/+/199317 to update the doc.

We have no work on errors planned for 1.14. We're going to wait a cycle.

**Comment by ALTree** [comment]
This was fixed in [Cl 199317]( https://go-review.googlesource.com/c/xerrors/+/199317) but the bot didn't close here (because the commit is in the xerrors repo but it references the issue without a golang/go prefix). Closing.
