### ISSUE TITLE
modules: `go.mod has non-....v1 module path` error when using gopkg.in on Go 1.13

### ISSUE THREAD

**Issue by zimnx** [golang/go#34342]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, 1.13 is latest release

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/maciej/.cache/go-build"
GOENV="/home/maciej/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY="github.com/snip,bitbucket.org/snip"
GONOSUMDB="github.com/snip,bitbucket.org/snip"
GOOS="linux"
GOPATH="/home/maciej/work"
GOPRIVATE="github.com/snip,bitbucket.org/snip"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/gobug/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build079448718=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.13 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.13
uname -sr: Linux 4.15.0-62-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
gdb --version: GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
</pre></details>

### What did you do?

```
$ cat example.go example_test.go go.mod
package example

func Foo(x int) bool {
        return x == 42
}
package example_test

import (
        "testing"
        "gopkg.in/stretchr/testify.v1/assert"
)

func TestFoo(t *testing.T) {
        assert.Equal(t, Foo(42), true, "42 should be true")
}
module example.com

go 1.12

/tmp/gobug ⌚ 11:23:54
$ go version
go version go1.12.3 linux/amd64

/tmp/gobug ⌚ 11:23:56
$ go mod tidy
go: downloading gopkg.in/stretchr/testify.v1 v1.4.0

/tmp/gobug ⌚ 11:24:00
$ go version
go version go1.13 linux/amd64

/tmp/gobug ⌚ 11:24:15
$ go mod tidy
go: downloading gopkg.in/stretchr/testify.v1 v1.4.0
example.com tested by
        example.com.test imports
        gopkg.in/stretchr/testify.v1/assert: go.mod has non-....v1 module path "github.com/stretchr/testify" at revision v1.4.0
```

### What did you expect to see?
I expect to see successfull build. There are no changes related to this in Go 1.13 changelog.

### What did you see instead?

Build is failing on 1.13, it's working on 1.12.x.

**Comment by psampaz** [comment]
Switching from 

"gopkg.in/stretchr/testify.v1/assert"

to 

"github.com/stretchr/testify/assert"

will fix this issue.

This is the correct module path as defined here

https://github.com/stretchr/testify/blob/master/go.mod#L1

**Comment by zimnx** [comment]
@psampaz I'm aware of that. I wonder why it stopped working.There are no mentions around this topic in changelog

**Comment by bcmills** [comment]
> There are no mentions around this topic in changelog

There is an entire section on it. See https://golang.org/doc/go1.13#version-validation.
