### ISSUE TITLE
Data Race: false positive?

### ISSUE THREAD

**Issue by albertvaka** [golang/go#34350]
### What version of Go are you using (`go version`)?

<pre>
1.13
</pre>

### What did you do?

Name the following test `main_test.go` and run it with `go test -race .`:

```
package main

import "testing"

func TestErino(t *testing.T) {

	mySignal := make(chan interface{})
	restartLoopSignal := make(chan interface{})

	go func() {
		for {
			select {
			case <-mySignal:
				//Do things
			case <-restartLoopSignal:
			}
		}
	}()

	// Replace mySignal
	mySignal = make(chan interface{})   // <- This gets detected as a data race

	// And restart the loop so the new mySignal channel gets picked up
	restartLoopSignal <- nil
}
```

Apparently assigning `mySignal` makes the data race detector unhappy (see below) because it is still used inside the loop. However, I break the loop right after to make sure the new channel is used. Why is this detected as incorrect? Anyone trying to write to `mySignal` by then will already be using the new channel.

```
$ go test -race .
==================
WARNING: DATA RACE
Read at 0x00c000010020 by goroutine 9:
  _/Users/albert.cintora/testerino.TestErino.func1()
      /Users/albert.cintora/testerino/main_test.go:13 +0x7f

Previous write at 0x00c000010020 by goroutine 8:
  _/Users/albert.cintora/testerino.TestErino()
      /Users/albert.cintora/testerino/main_test.go:21 +0x10e
  testing.tRunner()
      /usr/local/Cellar/go/1.13/libexec/src/testing/testing.go:909 +0x199

Goroutine 9 (running) created at:
  _/Users/albert.cintora/testerino.TestErino()
      /Users/albert.cintora/testerino/main_test.go:10 +0xdd
  testing.tRunner()
      /usr/local/Cellar/go/1.13/libexec/src/testing/testing.go:909 +0x199

Goroutine 8 (running) created at:
  testing.(*T).Run()
      /usr/local/Cellar/go/1.13/libexec/src/testing/testing.go:960 +0x651
  testing.runTests.func1()
      /usr/local/Cellar/go/1.13/libexec/src/testing/testing.go:1202 +0xa6
  testing.tRunner()
      /usr/local/Cellar/go/1.13/libexec/src/testing/testing.go:909 +0x199
  testing.runTests()
      /usr/local/Cellar/go/1.13/libexec/src/testing/testing.go:1200 +0x521
  testing.(*M).Run()
      /usr/local/Cellar/go/1.13/libexec/src/testing/testing.go:1117 +0x2ff
  main.main()
      _testmain.go:44 +0x223
==================
--- FAIL: TestErino (0.00s)
FAIL
FAIL	_/Users/albert.cintora/testerino	0.010s
FAIL
```

**Comment by randall77** [comment]
This is a race.
Your goroutine is reading from the `mySignal` variable at the same time that the parent goroutine is writing to it. The channel your inner goroutine ends up selecting on is nondeterministic (depending on whether the goroutine starts and reads `mySignal` before or after the parent goroutine continues running after the `go` statement).

I'm going to close this issue. We do not really use this bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the Questions wiki page; it has a list of good places for asking questions.
