### ISSUE TITLE
fatal: morestack on g0

### ISSUE THREAD

**Issue by Danile71** [golang/go#34363]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS="-I/usr/local/include"
CGO_CXXFLAGS="--std=c++1z"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build104421058=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I'm making docker image, build programm from sources.
programm use github.com/Danile71/go-face (cgo)
If I build programm from sources manually and start binary - works perfect, but in docker it died

### What did you see instead?
fatal: morestack on g0
SIGTRAP: trace trap
PC=0x4c3772 m=11 sigcode=128

goroutine 0 [idle]:
runtime.abort()
	/usr/local/go/src/runtime/asm_amd64.s:839 +0x2
runtime.morestack()
	/usr/local/go/src/runtime/asm_amd64.s:397 +0x25

goroutine 31 [syscall]:
runtime.cgocall(0x8ac470, 0xc0001e6588, 0x0)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc0001e6558 sp=0xc0001e6520 pc=0x46f14b
github.com/Danile71/go-face._Cfunc_facerec_recognize(0x7f35113c6fa0, 0xc00024e800, 0x7e3, 0x1, 0x0)
	_cgo_gotypes.go:184 +0x4e fp=0xc0001e6588 sp=0xc0001e6558 pc=0x8779ce
github.com/Danile71/go-face.(*Recognizer).recognize.func1(0xc0001fe010, 0xc00024e800, 0x7e3, 0x7f3500000001, 0x400)
	/go/src/github.com/Danile71/go-face/face.go:98 +0x84 fp=0xc0001e65c8 sp=0xc0001e6588 pc=0x879594
github.com/Danile71/go-face.(*Recognizer).recognize(0xc0001fe010, 0x1, 0xc00024e800, 0x7e3, 0x7e3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/Danile71/go-face/face.go:98 +0x9c fp=0xc0001e68c0 sp=0xc0001e65c8 pc=0x87800c
github.com/Danile71/go-face.(*Recognizer).RecognizeCNN(...)
	/go/src/github.com/Danile71/go-face/face.go:169
video/video_recognize/recognizer.(*Recognizer).recognition(0xc0000b3720)
	/go/src/video/video_recognize/recognizer/face.go:23 +0x136 fp=0xc0001e6fd8 sp=0xc0001e68c0 pc=0x8a8c96
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0001e6fe0 sp=0xc0001e6fd8 pc=0x4c3e21
created by video/video_recognize/recognizer.(*Recognizer).Init
	/go/src/video/video_recognize/recognizer/recognizer.go:46 +0x41f

**Comment by Danile71** [comment]
Bug only with alpine images. 
If I use golang:latest to build and debian to start binary - it works

**Comment by toothrot** [comment]
@Danile71 Could you provide a bit more info about how to reproduce the failure?

Which specific docker image are you using that it fails on? How are you installing Go on that image, or does it come with Go already?
