### ISSUE TITLE
syscall: memory corruption in *bool types generated by mksyscall_windows.go

### ISSUE THREAD

**Issue by zx2c4** [golang/go#34364]
This is an issue to track a memory corruption bug in mksyscall_windows.go and its effects various places.

Windows type PBOOL is a pointer to a 4 byte value, where 0 means false and not-0 means true. That means we should use uint32 when passing pointers, not bool, since Go bools are 1 byte, not 4. Previously, we were passing the 1 byte bool to the 4 byte argument, resulting in 3 null bytes being written somewhere bad. I observed this memory corruption in the wild, and it's not pretty.

x/sys/windows currently has one buggy function. However, lots and lots of projects use Go's mksyscall_windows.go -- it was meant for external consumption -- and it's possible that external projects are affected by this. This issue can be used to indicate the problem to these places.

CC @alexbrainman @ianlancetaylor @bradfitz

**Comment by zx2c4** [comment]
Fix history as of writing:

For x/sys/windows, my first attempt was to just get rid of *bool and pass an explicit *uint32, breaking the API: https://go-review.googlesource.com/c/sys/+/195839 .

The first attempt was rejected. Reviewers suggested instead I fix the source of the problem directly, mksyscall_windows.go, which I did: https://go-review.googlesource.com/c/go/+/196122 . Then, I was able to regenerate x/sys/windows using it: https://go-review.googlesource.com/c/sys/+/196123 .

**Comment by zx2c4** [comment]
@gopherbot please backport this to 1.13

**Comment by networkimprov** [comment]
Is 1.12 also affected?

**Comment by zx2c4** [comment]
Yes.

**Comment by networkimprov** [comment]
Can it get a backport, too?

**Comment by networkimprov** [comment]
@gopherbot backport 1.12

**Comment by networkimprov** [comment]
@zx2c4 usually gopherbot closes the issue when the commit lands. But this doesn't seem to have an associated commit yet...

**Comment by dmitshur** [comment]
> not sure why this didn't work...

@networkimprov You can only make one backport request per issue at this time, see issue #25574.
