### ISSUE TITLE
x/net/http2/h2demo: has started to cause x/net builders to fail

### ISSUE THREAD

**Issue by dmitshur** [golang/go#34361]
Issue #32528 has been resolved and all inner modules in x/net are being tested now, which includes the `golang.org/x/net/http2/h2demo` module. It contains a single package, which is a command with an `// +build h2demo` build constraint.

This is currently causing the x/net builders to report a failure, because the `go test` command reports a non-zero exit code when given an import path pattern that matches no packages:

```
h2demo $ go test golang.org/x/net/http2/h2demo/...
go: warning: "golang.org/x/net/http2/h2demo/..." matched no packages
no packages to test
h2demo $ echo $?
1
```

This makes x/net builders fail:

![image](https://user-images.githubusercontent.com/1924134/65148801-dde92a00-d9ee-11e9-8708-6a4bb70b9c74.png)

We have to fix x/net builders, but need to decide how.

### Possible Solutions

My first suggestion would be to remove the `h2demo` build constraint. If I understand correctly, it was used when `h2demo` was created in 2015, before modules, and it was a probably a way to make it not appear in users' $GOPATH/bin when they did `go get -u golang.org/x/net/...` and to avoid its dependencies from being fetched.

The `h2demo` command was carved out into a separate module in #30685 to resolve the issue of it contributing too many dependencies to x/net. I think the build constraint isn't needed anymore, but let me know what you think.

An alternative solution is to come up with a way to allow a module with zero packages to not cause a test failure. But this option doesn't seem very good.

/cc @bradfitz @jayconrod

**Comment by dmitshur** [comment]
I prototyped the idea of removing the `h2demo` build constraint in [CL 196036](https://golang.org/cl/196036). It passed all trybots except 1.12.x one, because that one ran tests in GOPATH mode, and failed since h2demo imports some third-party packages. But that can be solved via [CL 196097](https://golang.org/cl/196097).

So, that solution seems to be viable. This issue still needs decision; I just wanted to check that removing the build constraint would actually work to fix the issue.

**Comment by bradfitz** [comment]
SGTM
