### ISSUE TITLE
rand panic

### ISSUE THREAD

**Issue by yuyongbo** [golang/go#34369]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.12.5 windows/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\yuyongbo\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\gopath
set GOPROXY=direct
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\gopath\src\ccp-server\blackwordserver\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\yuyongbo\AppData\Local\Temp\go-build582312122=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
i just call this function as example:

```
if serviceInfoLen > 0 {
		return serviceInfos[thiz.curRandSeed.Intn(serviceInfoLen)].clone(), nil
}
```
So this error chance appear
```
error: index out of range [-1], callstack:
runtime.goPanicIndex
 D:/Go/src/runtime/panic.go:75
math/rand.(*rngSource).Uint64
 D:/Go/src/math/rand/rng.go:249
math/rand.(*rngSource).Int63
 D:/Go/src/math/rand/rng.go:234
math/rand.(*Rand).Int63
 D:/Go/src/math/rand/rand.go:85
math/rand.(*Rand).Int31
 D:/Go/src/math/rand/rand.go:99
math/rand.(*Rand).Int31n
 D:/Go/src/math/rand/rand.go:131
math/rand.(*Rand).Intn
 D:/Go/src/math/rand/rand.go:172
```

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
