### ISSUE TITLE
proposal: involve new people in CL reviewing 

### ISSUE THREAD

**Issue by bigmikes** [golang/go#34367]
**Motivation:**
Reviewing workload has been a clear and well-known problem for a bit. We have way more CLs than the number of who can review them, i.e. packages' owners. In fact, contributors outnumber reviewers. This very often results in longer waits to have one CL reviewed and possibly merged. Which is normal, given that reviewers probably are overwhelmed and they have to prioritize their tasks.

I am sorry I don't have data to back this up, but I think that longer waits for CL's review can discourage new contributors to make a second CL. It is just understandable that a new contributor may lose interest if they see that nobody cares about their first CL.

Moreover, owners' time can be spent more efficiently if somebody help them gardening CLs. Core team's expertise shouldn't be required for simple work such as pointing out when commit messages don't follow the format, or when API changes don't have a proposal issue, etc.

Also, it seems that this is not the first time this issue comes up: #22120. This time I would try to propose a solution for this.

**Possible solution:**
The final goal would be to increase the number of reviewers. In order to achieve that, we need to encourage new contributors to also review CLs. Of course, beginners will not have the same experience of packages' owners. In fact, their primary task should be gardening CLs (look for typos, check that everything follows the right format, obvious errors in code, etc). Hopefully, the more reviews these people do, the more they become familiar with the code base and, as a result, they can start reviewing CLs more deeply.

To involve new volunteers, we need Gerrit to include them in CC when a new CL is pushed. This can be done by introducing a third column in [owners table](https://dev.golang.org/owners). For every new CL, Gerrit can rotate the persons in this third column and add them in CL's CC. In this way, new reviewers get actively notified and this will possibly make them feel responsible.

Third column could be named _"First review pass team"_ or _"CL gardening team"_. We could provide a web page to automate registration process, where contributors can also indicate the set of packages they want to be notified of.

The above process can be improved or even changed, but the underlying idea should remain, in my opinion: we need to actively include new people in CLs through automation.

**Comment by andybons** [comment]
Proposals are generally for more concrete solutions to problems. **This is definitely a problem**, but a solution can’t be reached because we don’t know the concrete, underlying cause.

I suggest this be moved to golang-dev@ for further discussion.
