### ISSUE TITLE
x/review/git-codereview: change NNNN[/PP] feature isn't mentioned in package documentation

### ISSUE THREAD

**Issue by dmitshur** [golang/go#34378]
Running `git codereview help` mentions the following way to use the `change` command:

```
	change NNNN[/PP]
		Checkout the commit corresponding to CL number NNNN and
		patch set PP from Gerrit.
		If the patch set is omitted, use the current patch set.
```

This isn't documented in the package comment:

https://godoc.org/golang.org/x/review/git-codereview#hdr-Change

For reference, this feature was added in [CL 20101](https://golang.org/cl/20101) to resolve issue #9255.

**Comment by AndersonQ** [comment]
@dmitshur I submitted a CL for that

**Comment by dmitshur** [comment]
Fixed by [CL 254746](https://golang.org/cl/254746) (commit golang/review@9593f86427dedbe2eda472886bd2a4f8c965abf5).
