### ISSUE TITLE
ponies: generics using .(type)

### ISSUE THREAD

**Issue by gopherbot** [golang/go#3438]
by **Ryan.FireBall**:

<pre>It might be advisable to use the &quot;.(type)&quot; syntax over the reflect library,
reflect.Type, and etc.

For example:

func main () {
 var a int
 var b type
 a = 9
 b = a.(type)
 c := make(map[b]int)
 c[a] = 2
}

Possibly use .(type[0]) or variant for maps? The program could invisibly check for and
panic on type mismatch.

Just an idea.</pre>

**Comment by adg** [comment]
This hasn't been touched since before Go 1 so I'm going to close it.
