### ISSUE TITLE
strange behavior of switch statement

### ISSUE THREAD

**Issue by ivakhin** [golang/go#34397]
### What version of Go are you using (`go version`)?

<pre>
go version go1.12.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/vim/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/vim/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.7/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/vim/workspace/sw/airline-aggregation2/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4g/wh3rr_yn4s3clmj6319tqyfr0000gn/T/go-build318345949=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
https://play.golang.org/p/6UpJ027NiHw
```
package main

import (
	"fmt"
)

func main() {
	s := ""

	switch {
	case s == "":
		fmt.Println("1")
		fallthrough
	case s != "":
		fmt.Println("2")
		fallthrough
	default:
		fmt.Println("3")
	}

	fmt.Println("Hello, playground")
}
```

### What did you expect to see?
```
1
3
Hello, playground
```

### What did you see instead?
```
1
2
3
Hello, playground
```

**Comment by av86743** [comment]
Naturally, `fallthrough` does not check the `case` condition.

**Comment by ivakhin** [comment]
Thanks

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
