### ISSUE TITLE
cmd/go: include line numbers in errors for bad import statements

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#34393]
<pre>
$ go version
go version go1.13 linux/amd64
</pre>

Related to #12871 but more general. When a program such as [this one](https://play.golang.org/p/KkcsPTl50jK) is built, we see an error like:

    build $package: cannot load string: malformed module path "string": missing dot in first path element

The problem is with at least one import statement in the package, but although it mentions the package that's being built, it's not clear where the problem might lie. It would be helpful if the error message could mention at least one exact file location that the error has occurred, enabling editors to jump to that location automatically.

**Comment by jayconrod** [comment]
This error happens when we prepare module build info (the string that `go version -m` prints). `modload.PackageBuildInfo` is trying to find a module for each import path. Paths that could not be resolved to modules (typos in this case) trigger a fatal error without position information.
