### ISSUE TITLE
cmd/compile: wasm: LinkError: "data segment does not fit in memory"

### ISSUE THREAD

**Issue by Splizard** [golang/go#34395]
There is a regression from 1.12 to 1.13, a program that successfully compiles and runs on Firefox and Google Chrome in Go 1.12 will not run when compiled with Go 1.13

Firefox gives the error:
```
LinkError: "data segment does not fit in memory"
```

Google Chrome gives the error:
```
LinkError: WebAssembly.instantiate(): data segment is out of bounds
```

The project is quite large and the Web Assembly file is ~50mb when uncompressed.

I'm happy to provide further details on request, however, I don't have a trivial program that reproduces this.
I am using the appropriate wasm_exec files for both versions.

**Comment by agnivade** [comment]
Thanks @Splizard. It will be very helpful to have further details for us to debug this further.

Since it is readily reproducible for you, may I also ask you to run a `git bisect` and check which commit introduced this regression. I understand this is a time taking request, but if we know which commit caused this, it may give us an idea as to what went wrong.

**Comment by agnivade** [comment]
@neelance @cherrymui

**Comment by neelance** [comment]
This is most likely due to https://github.com/golang/go/commit/460f9c60689c38bdd938d09903f3b414f6082a7d. Could you please check if increasing the `initialSize` solves the issue?

**Comment by janpfeifer** [comment]
Same problem here (main.wasm is 33Mb size), and my project won't run on go 1.13. 

Is there a flag way to change initialSize, or does one has to recompile wasm ?

**Comment by agnivade** [comment]
You have to recompile the Go distribution with the new `initialSize`.

**Comment by janpfeifer** [comment]
Thanks Agniva.

I tried recompiling setting it to 128Mb and it still failed. When I changed it to 1 GB it got back working.

**Comment by neelance** [comment]
Let's try to come up with a minimal example that triggers this bug. Maybe a large global array?
