### ISSUE TITLE
cmd/go: new internal/goroot test broke aix, illumos, solaris builders

### ISSUE THREAD

**Issue by ALTree** [golang/go#34390]
The new internal/goroot `mod_m` test introduced in [CL 196120](https://go-review.googlesource.com/c/go/+/196120) with the fix for #34358 is [currently failing](https://build.golang.org/#) on the aix, illumos, and solaris builders, with the following error:

```
--- FAIL: TestScript (0.01s)
    --- FAIL: TestScript/mod_m (4.13s)
        script_test.go:191: 
            # It's absurd, but builds with -compiler=gccgo used to fail to build module m.
            # golang.org/issue/34358 (3.875s)
            > cd m
            $WORK/gopath/src/m
            > go build
            > exists m$GOEXE
            > rm m$GOEXE
            > [exec:gccgo] go build -compiler=gccgo
            [stderr]
            # m
            ld: 0711-317 ERROR: Undefined symbol: .runtime.setmodinfo
            ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
            collect2: error: ld returned 8 exit status
            [exit status 2]
            FAIL: testdata/script/mod_m.txt:8: unexpected command failure
            
FAIL
FAIL	cmd/go	107.473s
FAIL
```

cc @ianlancetaylor

**Comment by Helflym** [comment]
I think this is linked with [CL 196237](https://go-review.googlesource.com/c/go/+/196237). Symbol `runtime.setmodinfo` is only available in gcc-master with go1.13. In previous gcc version thus previous Go version, `runtime/debug.setmodinfo` is still linked to `runtime..z2fdebug.setmodinfo`. 


gcc-9.1.0:
```
go/runtime/debug/mod.go://go:linkname setmodinfo runtime..z2fdebug.setmodinfo
```
gcc-svn:
```
go/runtime/debug.go://go:linkname setmodinfo runtime.setmodinfo
```

Thus, gccgo version must be checked when creating `_gomod_.go`. 

AIX builder is still in gcc 8 (for various reasons) and I think it's the same for Illumos and Solaris builders.

**Comment by av86743** [comment]
Are trybots' gccgo/gcc out of sync with builders?

**Comment by ALTree** [comment]
Fixed by https://go-review.googlesource.com/c/go/+/196518
