### ISSUE TITLE
net/http: Transport.RoundTrip occasionally stalls when using http2client

### ISSUE THREAD

**Issue by grudzinski** [golang/go#34401]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/romang/.cache/go-build"
GOENV="/home/romang/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/romang/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/romang/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/romang/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build443134527=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

My server is doing a lot of requests to another servers.

### What did you expect to see?

A normal work. It works OK when http2client is disabled.

### What did you see instead?

A lot of unexpected goroutines locked in go http2 implementation.

<img width="773" alt="Screen Shot 2019-09-19 at 15 18 20" src="https://user-images.githubusercontent.com/1442433/65243406-f3df1380-daf0-11e9-9dac-4256f02ff013.png">

See the diff of profiles, this is the problem stacktrace, diff is about 1:30.

**Comment by andybons** [comment]
Without any code it is extremely difficult to help you diagnose this issue. Can you provide any more information?

@bcmills @rsc due to recent work on net/http Transport.

**Comment by bcmills** [comment]
The changes that Russ and I made should not affect HTTP/2, and shouldn't have any effect on the `(*Client).send` part of the `RoundTrip` call anyway.

@grudzinski, did this stall occur with previous `go` versions, or was this a regression in 1.13?
