### ISSUE TITLE
x/review: git codereview mail uses wrong email

### ISSUE THREAD

**Issue by rileykarson** [golang/go#34411]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.12.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rileykarson/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/rileykarson/go-workspace"
GOPROXY=""
GORACE=""
GOROOT="/Users/rileykarson/homebrew/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/Users/rileykarson/homebrew/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/81/zf5_7yzn1sxg_7kfkqsvgclw00cn8c/T/go-build474690330=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
git codereview mail
```

Following this guide: https://code.googlesource.com/gocloud/+/refs/heads/master/CONTRIBUTING.md#contributing

`git log`:

```
commit 795c92268c930c8714d3b6a4bfe1a173a1858b4a (HEAD -> add-storage-type-to-read)
Author: Riley Karson <rileykarson@google.com>
Date:   Thu Sep 19 09:53:40 2019 -0700

    bigtable: Add StorageType to ClusterInfo

    Change-Id: I7120f3ae6c4e5fdb48744613cd222eef317d841e
```

### What did you expect to see?

Success, using my Git email on this machine, rileykarson@google.com

### What did you see instead?

```
$ git codereview mail
fatal: remote error: PERMISSION_DENIED The caller does not have permission
[type.googleapis.com/google.rpc.LocalizedMessage]
locale: "en-US"
message: "No Contributor Agreement on file for user Riley Karson <rileykarson@gmail.com> (id=17848)"

[type.googleapis.com/google.rpc.RequestInfo]
request_id: "1002a9a0037c424fbd703c9708d4ae78"

[type.googleapis.com/google.rpc.RequestInfo]
request_id: "677d29bf9bf940e0aa432dedde6dff78"

(running: git push -q origin HEAD:refs/for/master)
/Users/rileykarson/go-workspace/bin/git-codereview: exit status 128
```

**Comment by andybons** [comment]
Does the same message appear if you try to upload the change directly via:

`git push origin HEAD:refs/for/master`

?

**Comment by rileykarson** [comment]
Ah, yep.

It looks like the value is being sourced from my `.gitcookies` file when I'd used that email to get a token for a `go get` cookie months back. Removing it from there caused the correct email to be used.

**Comment by andybons** [comment]
Closing as it seems that this is not an issue with git-codereview. Please comment if you feel that’s not the case.
