### ISSUE TITLE
doc: Effective Go doc misuses word "anew", resulting in confusing usage rule

### ISSUE THREAD

**Issue by kanreki** [golang/go#34415]
In Effective Go, in the section on "Redeclaration and reassignment," it says that an existing variable may appear in a short declaration if "there is at least one other variable in the declaration that is being declared anew."

Doesn't it really mean being declared for the first time? That's not what "anew" means; if anything, it means "again."

**Comment by agnivade** [comment]
@robpike

**Comment by robpike** [comment]
The word can go either way but it is the wrong choice, I agree. I will fix.
