### ISSUE TITLE
x/tools/gopls: race conditions result in confusing error message

### ISSUE THREAD

**Issue by stamblerre** [golang/go#34410]
Forked from https://github.com/microsoft/vscode-go/issues/2759, as well as several messages on Slack. 

This is a fairly unreproducible bug, but it seems that we have a race condition wherein a package may be type-checked with 2 versions of the same dependency. This seems to happen more frequently with packages with test variants. It results in error messages that read something like "type X cannot be used as type X in ...".

**Comment by stamblerre** [comment]
After investigating yesterday, the issue here seems to be that, with [CL 186839](https://go-review.googlesource.com/c/tools/+/186839), the deletion of an item from a map doesn't necessarily cause it to be garbage collected, so we may end up re-using an old cache entry when we wanted to force the type checker to recompute the entry. This will be fixed when we improve our cache invalidation strategy.

**Comment by atombender** [comment]
I'm getting something that seems to be a race condition. Could this be the same cause?

While editing code, I'll suddenly get nonsensical errors such as:

```go
switch intent.Status {
  case stripe.PaymentIntentStatusSucceeded:
^ cannot compare stripe.PaymentIntentStatusSucceeded == intent.Status (mismatched types stripe-go.PaymentIntentStatus and stripe-go.PaymentIntentStatus)
```

...which indicates that it has two sets of type information for the same imported package. The imported package has not been updated, so I don't know why gopls would keep two sets.

The problem manifests as type errors (types not assignable, comparable, ertc.) and import errors.

[gopls output here](https://gist.github.com/atombender/3896e12893dc0649a16b3559fee664f8).

I'd be happy to report as separate issue.

Running `5eefd052ad727afc5e2e7b034c752b9d3d902b3b`.

**Comment by myitcv** [comment]
Also seeing this within `govim` using `gopls` and `x/tools` v0.0.0-20190926165942-a8d5d34286bd

**Comment by stamblerre** [comment]
This error should be resolved as of the above CL.

**Comment by zikaeroh** [comment]
I'm assuming #34584 should also be closed, since it looks to be the same issue?
