### ISSUE TITLE
wasm_exec.html (+.js): LinkError: WebAssembly.instantiate(): 

### ISSUE THREAD

**Issue by prospero78** [golang/go#34424]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
GOOS=js
GOARH=wasm
$ go env

</pre></details>

### What did you expect to see?
Error in execute in brouser bin code on wasm

### What did you see instead?
LinkError: WebAssembly.instantiate(): Import #18 module="go" function="syscall/js.copyBytesToJS" error: function import requires a callable
(anonymous) @ wasm_exec.html:36
Promise.catch (async)
(anonymous) @ wasm_exec.html:35

**Comment by agnivade** [comment]
You are likely using a different wasm_exec.js than your Go version. Please check that. And if you still see this issue, please mention the exact steps to reproduce this issue. Thanks.

**Comment by prospero78** [comment]
Version of golang and scripts -- best fresh. Its not different. Im double in my computer example for WebAssebly (in this wiki on github). This message of errors -- in Chrome-console .

**Comment by agnivade** [comment]
Please mention the exact steps that you did. If you have exactly followed https://github.com/golang/go/wiki/WebAssembly#getting-started, there shouldn't be any errors.

**Comment by prospero78** [comment]
Im now repeat all step in examples.
Settings OS enviroument = true
Compile for WASM=true
Strating simple http-server=true
Coping again wasm_wxec.js from %PATH%\misc\wasm to dir projects = true
In Chrome-console repeat look error:

> Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #18 module="go" function="syscall/js.copyBytesToJS" error: function import requires a callable

**Comment by agnivade** [comment]
Hi @prospero78 , perhaps there is a language barrier here due to which I am unable to explain what is required here. We need the _exact_ commands that you executed on your system. So that we understand what _exactly_ you did.

For example- 

> Compile for WASM = true

What is the exact command you ran ? Where is the source code ?

> Coping again wasm_wxec.js from %PATH%\misc\wasm to dir projects = true

Again, what is the copy command you ran ? What is the value of %PATH% ? Note that %PATH% should be same as `$(go env GOROOT)`. Is that correct ?

You mention `projects` directory, so that means we need to create it. Please also mention that.

Please also fill the output of `go env` in the original issue template. 

We are looking for something like - the Go source file you compiled, the command you used to compile, the command used to copy the wasm_exec.js. Preferably, it should just be a list of shell commands we can copy paste and reproduce the issue. Hope that is clear now.

**Comment by prospero78** [comment]
I do not think that there is a language barrier here. Rather, it is a semantic barrier. If this barrier exists at all.
> What is the exact command you ran ? Where is the source code ?
`set GOOS=js
set GOARCH=wasm
go build -o main.wasm`
The source code is in the same directory as the compilation commands.
> Again, what is the copy command you ran ? What is the value of %PATH% ? Note that %PATH% should be same as $(go env GOROOT). Is that correct ?
% PATH% - I have installed correctly (indicates all the directories used in the work). Strictly speaking, it was the equivalent correct example of my oputi (just too lazy to write all the ways completely). 
All variables are absolutely correctly set correctly (otherwise, I would have simply been able to compile the source code for the golange in WASM)
> You mention projects directory, so that means we need to create it. Please also mention that.
My project directory is not located in the %GOPATH%\SRC directory, but in my case it does not matter.

> Please also fill the output of go env in the original issue template.
No problems.
`d:\coding\prospero78su\_test\waTest00>go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=d:\coding\golang\_home\bin
set GOCACHE=C:\Users\User\AppData\Local\go-build
set GOENV=C:\Users\User\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=d:\coding\golang\_home
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\coding\golang
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\coding\golang\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=d:\temp\go-build540987206=/tmp/go-build -gno-record-gcc-switches`

> We are looking for something like - the Go source file you compiled, the command you used to compile, the command used to copy the wasm_exec.js. Preferably, it should just be a list of shell commands we can copy paste and reproduce the issue. Hope that is clear now.
I copied wasm_exec.js via TotalCommander (with replacing an existing file, the file size is the same), so the copy command does not matter.

I'm not new to golang, I'm doing everything right (at least my programmer skills allow me to work for money in a startup). The problem is not compilation, the problem wasm wasex_exec.js malfunctioning

**Comment by agnivade** [comment]
Ok, may I ask you to just attach your Go source file and the wasm_exec.js you are using ? We can reproduce the issue on our side and see what's going wrong.

**Comment by prospero78** [comment]
No problems.
https://yadi.sk/d/Q_RKU8WqHVF37g
https://yadi.sk/d/J1rGFld67Q96iQ
https://yadi.sk/d/ds_Pi3gu5N4kNA

**Comment by agnivade** [comment]
This works fine for me @prospero78. 

> Im now run this code in %GOPATH%\src -- this no have effects. This same error with /index.html (examples from wiki) and /wasm_exec.html (+wasm_exec.js from source golang).

I do not understand this clearly. Are you saying this code works if you keep it in $GOPATH/src, but it does not work if you use wasm_exec.js from the Go source ?

**Comment by prospero78** [comment]
I apologize for the misleading answer.
This code does not work in the case of a specific path, nor in the case of a path specified in the environment.

**Comment by agnivade** [comment]
Ok, I don't know how else to proceed here. It works for me inside or outside GOPATH. The error is very specific to an incorrect wasm_exec.js, so I don't know how a different path can lead to this. Others can investigate further.

**Comment by checkmatesolo** [comment]
---------- Forwarded message ---------

**Comment by prospero78** [comment]
Thank you all for the discussion, until there is no solution to this problem.
And thanks for the link to the video with detailed instructions.
I ask you to leave this question open.

**Comment by agnivade** [comment]
Just a small note that you might get better and quicker help in a Go forum like [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)  or [Gophers Slack](https://gophers.slack.com). More people will see your issue and help you out. This issue tracker is mainly for bugs and feature proposals.

I will leave this open because it is not yet clear to me whether it is a bug or not.

**Comment by moketao** [comment]
https://github.com/moketao/show_a_wasm_link_err


visit  **index.wasmgo.err.html**,  get some err:

`Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #20 module="go" function="syscall/js.copyBytesToGo" error: function import requires a callable
Promise.then (async)
(anonymous) @ loader.js:1`


visit  **index.wasmgo.ok.html**,  all is well.

**Comment by prospero78** [comment]
I figured out what the problem was: when switching from version 1.13.1 -, the shuffling library changed. For proper operation it was necessary to remove everything and install from the very beginning (as during the first installation). After that, everything starts to work. The topic can be closed.
