### ISSUE TITLE
net/http: Flush in TimeoutHandler for Go1.13 is broken and might need a revert

### ISSUE THREAD

**Issue by pam4** [golang/go#34439]
Currently (1.13) calling `Flush` on a `ResponseWriter` exposed by `TimeoutHandler` has some undesirable effect:
1) it sends out default headers with a `200 OK` status, ignoring whatever the caller set before (e.g. `w.Header().Set(key, val)` or `w.WriteHeader(someOtherCode)`);
2) in doing so, it prevents `TimeoutHandler` to respond with `503` on timeout as promised, and it produces a `"superfluous response.WriteHeader call"` warning;
3) it doesn't flush anything.

https://play.golang.org/p/HmW2ETipalB

This is happening because `timeoutWriter.Flush` calls the underlying `Flush`, which in turn calls the underlying `WriteHeader` from a clean state: the actual header and partial body are still buffered in the wrapper (in `timeoutWriter.h` and `timeoutWriter.wbuf`).

I think `TimeoutHandler` supporting `Flush` doesn't make any sense because a `TimeoutHandler` doesn't know what to do until either the inner handler returns or the timeout is reached, therefore it needs to buffer the whole response until the end.

**EDIT:** #34198 is probably an effect.

**Comment by bcmills** [comment]
CC @cuonglm @bradfitz 

See [CL 154383](https://golang.org/cl/154383) / #29193.

**Comment by cuonglm** [comment]
Fair enough, maybe we can just make `func (tw *timeoutWriter) Flush()` becomes a no-op, so calling Flusher interface on timeout handler will do nothing.

**Comment by pam4** [comment]
@cuonglm, what's the purpose of a fake `Flush` method?
It just makes it impossible to test for the capability at runtime (the method doesn't even return an error).
> The Flusher interface is implemented by ResponseWriters that allow an HTTP handler to flush buffered data to the client.

`timeoutWriter` cannot achieve that (unless we change `TimeoutHandler` semantics), therefore it shouldn't implement the interface. If there is indeed a reason for such violation it should be clearly documented.

**Comment by cuonglm** [comment]
@pam4 I understand, but dont know if removing it break go1 compatibility or not, so better to make it do nothing, so we can prevent side effect.

**Comment by pam4** [comment]
> but dont know if removing it break go1 compatibility or not

I don't think so. The first release to have that method was 1.13 and any existing program relying on it, is certainly not working as intended. The only "side effect" I can imagine is uncovering an already existing bug.
The problems I mentioned above seem much more serious to me, but I would certainly like to hear other opinions.

**Comment by cuonglm** [comment]
> > but dont know if removing it break go1 compatibility or not
> 
> I don't think so. The first release to have that method was 1.13 and any existing program relying on it, is certainly not working as intended. The only "side effect" I can imagine is uncovering an already existing bug.
> The problems I mentioned above seem much more serious to me, but I would certainly like to hear other opinions.

So if you removed it, then all go1.13 program which rely on the interface will be broken in go1.14.

If it does not break go1 compatibility, then we can remove it . Otherwise, I think it's better to make it as a no-op, and document that timeoutWriter.Flush do nothing.

**Comment by odeke-em** [comment]
@pam4 sorry that we didn't catch this newly introduced issue earlier!
@cuonglm thank you for the no-op suggestion fix.

Perhaps we have some options from both your suggestions:
a) Making it a no-op and updating its documentation and release notes and adding a comment in its body and docs, but what else lurks when Flush is a no-op?
b) Revert it for Go1.13.X, of which Go1.13 just came out only 3 weeks ago so the blast radius won't be horrible despite it breaking compatibility briefly and then make it a point release and retroactively update the release docs as well as package docs too.

I suspect with the reasoning of being just being released 3 weeks ago, we can negotiate for a walkback as the problem is quite severe. My personal opinion is going for option b)

Kindly pinging @andybons @dmitshur @bradfitz @ianlancetaylor to help with reviewing if/how this can be done.

**Comment by pam4** [comment]
Thanks for the reply.

IMHO saying that solution `#b` breaks compatibility is not entirely accurate. The method is there but the interface was never *actually* implemented. Go 1.13 docs made a false/impossible claim and I think we should just take it back.

It's unclear to me who would benefit from option `#a`: any program using the method is *already* broken (yes, removing the method could cause a panic, but such panic would uncover a sure bug).
A no-op `Flush` would make the type assertion test useless and cause confusion if users think they are flushing but they are not.

**Comment by bradfitz** [comment]
@odeke-em, let's not use Soon for this. The Soon label is only for super urgent things, like golang.org or other sites being down. We basically don't use it.

I'm fine reverting the Flusher stuff, though. That's easier than making it work properly.

**Comment by bcmills** [comment]
@gopherbot, please backport to Go 1.13: we should minimize the window during which the erroneous method is present.

**Comment by odeke-em** [comment]
>@odeke-em, let's not use Soon for this. The Soon label is only for super urgent things, like golang.org or other sites being down. We basically don't use it.

Oh, I had assumed that this bug was very urgent. Thank you for letting me know, Brad about its usage.
I've mailed a CL https://golang.org/cl/197659, please take a look when you've got some time.
