### ISSUE TITLE
net: host string comparison in TestLookupGmailNS is case-sensitive, causes flaky test

### ISSUE THREAD

**Issue by acln0** [golang/go#34446]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +ecc7dd5469 Sat Sep 21 16:31:44 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/acln/bin"
GOCACHE="/home/acln/.cache/go-build"
GOENV="/home/acln/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/acln/src/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org"
GOROOT="/home/acln/src/go/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/acln/src/go/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/acln/src/go/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build058559209=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I ran `$ go test -run TestLookup` in the `net` package.

### What did you expect to see?
I expected the test to pass consistently.

### What did you see instead?
The test passes sometimes, but also fails like so:
```
: forge:net ; /home/acln/src/go/go/bin/go test -run TestLookup
--- FAIL: TestLookupGmailNS (0.01s)
    lookup_test.go:197: got &{ns1.google.COm.}; want a record containing google.com.
    lookup_test.go:197: got &{ns2.google.COm.}; want a record containing google.com.
    lookup_test.go:197: got &{ns3.google.COm.}; want a record containing google.com.
    lookup_test.go:197: got &{ns4.google.COm.}; want a record containing google.com.
```
or even
```
: forge:net ; /home/acln/src/go/go/bin/go test -run TestLookup
--- FAIL: TestLookupGmailNS (0.01s)
    lookup_test.go:197: got &{ns2.google.coM.}; want a record containing google.com.
    lookup_test.go:197: got &{ns3.google.coM.}; want a record containing google.com.
    lookup_test.go:197: got &{ns1.google.coM.}; want a record containing google.com.
    lookup_test.go:197: got &{ns4.google.coM.}; want a record containing google.com.
    lookup_test.go:197: got &{ns1.google.CoM.}; want a record containing google.com.
    lookup_test.go:197: got &{ns2.google.CoM.}; want a record containing google.com.
    lookup_test.go:197: got &{ns3.google.CoM.}; want a record containing google.com.
    lookup_test.go:197: got &{ns4.google.CoM.}; want a record containing google.com.
```

This is the behavior I get when I use the default name server from my ISP. With Google (8.8.8.8) or CloudFlare (1.1.1.1) DNS, the test seems to pass without flaking. I am not expert on DNS, but it is my understanding that host names are case-insensitive. Perhaps this test should consider this fact.

If it seems sensible to use case-insensitive string comparison [here](https://github.com/golang/go/blob/ecc7dd546998ad0b68e9055876db1ec82facca4b/src/net/lookup_test.go#L196), I can send a CL.

Interestingly, I couldn't get any other lookup test to fail when using the ISP's name server (which seems to consistently alter the case of the TLD for NS records it returns). I don't know if that is because that name server has a particular quirk, or because NS records are special in some way, or for some other reason that I cannot fathom.

**Comment by bcmills** [comment]
CC @mikioh @bradfitz

**Comment by bradfitz** [comment]
Please send a CL.
