### ISSUE TITLE
x/website/cmd/golangorg, x/build/cmd/tip: inconsistent tabwidth value

### ISSUE THREAD

**Issue by dmitshur** [golang/go#34448]
https://tip.golang.org uses the [default godoc presentation](https://github.com/golang/tools/blob/5eefd052ad727afc5e2e7b034c752b9d3d902b3b/godoc/pres.go#L106) tab width of 4, but https://golang.org uses a tab width of 8 (because it's being overridden in [`appinit.go`](https://github.com/golang/website/blob/9a22596c54f343a5492518326ab689efb0db34f8/cmd/golangorg/appinit.go#L104)). This results in inconsistent rendering.

https://tip.golang.org/pkg/runtime/debug/#GCStats:

![image](https://user-images.githubusercontent.com/1924134/65379162-acdc5400-dc91-11e9-98f5-6a097f89fbfd.png)

https://golang.org/pkg/runtime/debug/#GCStats:

![image](https://user-images.githubusercontent.com/1924134/65379179-02b0fc00-dc92-11e9-819c-2fcc1694e1d3.png)

They should use the same value. We need to decide which.

/cc @andybons @julieqiu

**Comment by dmitshur** [comment]
I would prefer going with 4 everywhere, because 8 is quite wide, and 4 seems more commonly used. The future discovery site (issue #33654) and godoc.org currently use a tab width of 4:

https://godoc.org/runtime/debug#GCStats:

![image](https://user-images.githubusercontent.com/1924134/65379209-61767580-dc92-11e9-8bc8-71e626f37ba5.png)

But I also realize this is a subjective preference.

**Comment by andybons** [comment]
4 is fine

**Comment by dmitshur** [comment]
This fix is deployed.
