### ISSUE TITLE
x/sys/unix: Select signature on BSDs omits integer return value, unlike Linux etc

### ISSUE THREAD

**Issue by ThomasHabets** [golang/go#34458]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 openbsd/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes. It's still in the [code in HEAD](https://github.com/golang/sys/blob/master/unix/zsyscall_openbsd_arm64.go#L1307).

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/thompa/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="openbsd"
GOOS="openbsd"
GOPATH="/home/thompa/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/openbsd_amd64"
GCCGO="gccgo"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build396939324=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Tried to build this on OpenBSD, which builds fine on Linux:
```
package main

import (
	"fmt"
	"golang.org/x/sys/unix"
	"syscall"
)

type s func(n int, r, w, e *syscall.FdSet, timeout *syscall.Timeval) (int, error)
type s2 func(n int, r, w, e *unix.FdSet, timeout *unix.Timeval) (int, error)

func main() {
	var t s
	t = syscall.Select

	var t2 s2
	t2 = unix.Select

	fmt.Println("Hello, playground", t, t2)

}
```

### What did you expect to see?

Since OpenBSD has the same POSIX semantics for Select, as far as I know, as Linux, I expect the same function prototype and for the example above to successfully build.

### What did you see instead?

On OpenBSD (and Mac, and all BSDs?) the above fails to build because syscall.Select and unix.Select only return error, not `(int, error)`.

```
$ go build t.go
# command-line-arguments
./t.go:14:4: cannot use syscall.Select (type func(int, *syscall.FdSet, *syscall.FdSet, *syscall.FdSet, *syscall.Timeval) error) as type s in assignment
./t.go:17:5: cannot use unix.Select (type func(int, *unix.FdSet, *unix.FdSet, *unix.FdSet, *unix.Timeval) error) as type s2 in assignment
```

How can I make portable programs when Go removes my ability to call `Select`?

**Comment by bcmills** [comment]
CC @tklauser

This part of the `syscall` API appears to date to [CL 29723](https://github.com/golang/go/commit/602a446b74083ac027f1d0740d1e724534222a10#diff-aea2adda394bc6caefb857f1c2368383R441), before Go's open-source release, and the first place it appears is in `syscall_darwin.go`.

Is it possible that the Darwin version of this syscall does not return the number of file descriptors from the kernel, and instead computes it on the caller side? What about the other *BSDs?

**Comment by ThomasHabets** [comment]
OpenBSD certainly claims to ["select() returns the total number of ready descriptors in all the sets"](http://man.openbsd.org/select.2).

And looking at kernel code [it looks like yes](https://github.com/openbsd/src/blob/master/sys/kern/sys_generic.c#L538).

**Comment by tklauser** [comment]
> OpenBSD certainly claims to ["select() returns the total number of ready descriptors in all the sets"](http://man.openbsd.org/select.2).

The same seems to be true for Darwin (didn't find an online source for this, checked locally on macOS 10.14), [FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=select&apropos=0&sektion=2&manpath=FreeBSD+12.0-RELEASE&arch=default&format=html#RETURN_VALUES), [NetBSD](https://www.freebsd.org/cgi/man.cgi?query=select&apropos=0&sektion=2&manpath=NetBSD+8.0&arch=default&format=html#RETURN_VALUES) and [DragonflyBSD](http://man.dragonflybsd.org/?command=select&section=2). Probably also Solaris and Illumos.

On Darwin I also checked that `unix.Select` returns the correct number of ready file descriptors (both with the Go1.12+ libSystem syscalls and the Go1.11 raw syscalls) using the following addition to `TestSelect`:

```go
        rr, ww, err := os.Pipe()
        if err != nil {
                t.Fatal(err)
        }
        defer rr.Close()
        defer ww.Close()

        if _, err := ww.Write([]byte("HELLO GOPHER")); err != nil {
                t.Fatal(err)
        }

        rFdSet := &unix.FdSet{}
        fd := rr.Fd()
        // FD_SET(fd, rFdSet)
        rFdSet.Bits[fd/unix.NFDBITS] |= (1 << (fd % unix.NFDBITS))

        n, err = unix.Select(int(fd+1), rFdSet, nil, nil, nil)
        if err != nil {
                t.Fatalf("Select: %v", err)
        }
        if n != 1 {
                t.Fatalf("Select: expected 1 ready file descriptors, got %v", n)
        }
```

How would we go about changing `Select`? I guess it should be no problem in `x/sys/unix` as it is using modules. I'm not sure about `syscall`.

/cc @bradfitz @ianlancetaylor

**Comment by bradfitz** [comment]
> How can I make portable programs when Go removes my ability to call Select?

The default answer to that is:

"Syscall must always be guarded with build tags." -- https://go-proverbs.github.io

That said, this signature should probably match everywhere.

Let's just fix x/sys/unix but not syscall.

**Comment by ThomasHabets** [comment]
Right. Yeah fixing `syscall` will break anyone doing build tags for this today. Out of curiosity, is there a policy for breaking changes to `syscall`?

**Comment by ThomasHabets** [comment]
And exposing `NFDBITS` would be helpful too.

**Comment by ianlancetaylor** [comment]
We are not going to make a breaking change to the syscall package.  We can do that if absolutely necessary, but this is not absolutely necessary.

We change x/sys/unix for a good enough reason.

**Comment by tklauser** [comment]
> And exposing `NFDBITS` would be helpful too.

https://golang.org/cl/196802 will add `NFDBITS`for Darwin and the BSDs. I'll send a follow-up CL adding it for Linux etc.
