### ISSUE TITLE
spec: a possible inconsistency for promoted methods

### ISSUE THREAD

**Issue by dotaheor** [golang/go#34454]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

true

### What did you do?

```
package main

type S struct{}

func (*S) F() {}

type T struct {
	*T
	*S
}

func (*T) M() {}

func main(){
	T{&T{}, &S{}}.F()   // no problem
	T{&T{}, &S{}}.S.F() // no problem
	T{&T{}, &S{}}.M()   // cannot take the address of T literal
	T{&T{}, &S{}}.T.M() // no problem
}

```

### What did you expect to see?

All lines should compile.

### What did you see instead?

One line fails to compile.

**Comment by dotaheor** [comment]
En, it looks the implementation is correct, it is consistent with reflection:
```
package main

import (
	"fmt"
	"reflect"
)

type S struct{}

func (*S) F() {}

type T struct {
	*T
	*S
}

func (*T) M() {}


func main(){
	T{}.F()   // no problem
	T{}.S.F() // no problem
	//T{}.M()   // cannot take the address of T literal
	T{}.T.M() // no problem
	
	_ = T{}.F   // no problem
	//_ = T{}.M // cannot take the address of T literal
	
	// <invalid reflect.Value>
	fmt.Println(reflect.ValueOf(T{}).MethodByName("M"))
	// {  <nil> <invalid Value> 0} false
	fmt.Println(reflect.TypeOf(T{}).MethodByName("M"))
	// 1
	fmt.Println(reflect.TypeOf(T{}).NumMethod())
	// {F  func(main.T) <func(main.T) Value> 0}
	fmt.Println(reflect.TypeOf(T{}).Method(0))
	
	_, ok := (interface{}(T{})).(interface{M()})
	fmt.Println(ok) // false
}
```

Maybe, a small adjustment is needed in spec?
> If S contains an embedded field T, the method sets of S and *S both include promoted methods with receiver T. The method set of *S also includes promoted methods with receiver *T.

**Comment by ianlancetaylor** [comment]
In the final example I think you are suggesting that `S` should inherit the method `M` from the embedded field `T`, even though there is a method `M` on `*S`.  I think it's clear that the language is not intended to permit that.  It's possible that the spec does not clearly state that.  I think the place to state it would be https://golang.org/ref/spec#Selectors.

CC @griesemer

**Comment by dotaheor** [comment]
@ianlancetaylor Yes, I agree.

It looks the current design views `S{}.M` as a legal but invalid selector. However I haven't found how the spec distinguishes "legal" from "valid" for selectors.

**Comment by mdempsky** [comment]
I think this is a dup of #15708. In particular, I think this is [my first example here](https://github.com/golang/go/issues/15708#issuecomment-219657241).

**Comment by dotaheor** [comment]
I agree this is a dup of https://github.com/golang/go/issues/15708, so close it.

Maybe it is good to add a complement in the https://golang.org/ref/spec#Selectors section

For a primary expression x **(always assume it is addressable)** that is not a package name, the selector expression ....
