### ISSUE TITLE
time: Parse does not cover all valid RFC1123Z dates

### ISSUE THREAD

**Issue by bodqhrohro** [golang/go#34459]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.9 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Probably, as I got the same behavior at Playground.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/bodqhrohro/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/opt/gone"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.12"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.12/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/data/progs/go/smstree/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build184744936=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/aaUf5zpzKXj

### What did you expect to see?

According to the standard, a one-digit day is valid.
```
      5.2.14  RFC-822 Date and Time Specification: RFC-822 Section 5

         The syntax for the date is hereby changed to:

            date = 1*2DIGIT month 2*4DIGIT
```

### What did you see instead?

```
parsing time "Mon, 5 Aug 2019 17:21:53 +0300" as "Mon, 02 Jan 2006 15:04:05 -0700": cannot parse "5 Aug 2019 17:21:53 +0300" as "02"
```

**Comment by gregory-m** [comment]
RFC822 also allow day to be one or two digits:
```
date        =  1*2DIGIT month 2DIGIT        ; day month year
```

For date fix is trivial but we don't have placeholder for 2 or 4 digits year.

On another way RFC1123 say:
```
  All mail software SHOULD use 4-digit years in dates, to ease
         the transition to the next century.
```

So maybe its not needed to implement it.

**Comment by bcmills** [comment]
This is unfortunate, but it's been that way since [CL 196090](https://golang.org/cl/196090), 9½(!) years ago.

CC @robpike, but I don't think we can change the constant now — at best, perhaps we could add a new constant and document the difference.

**Comment by agnivade** [comment]
FWIW, you can define your own constant without the zero padding. That can parse both zero padded and single digit days. https://play.golang.org/p/gTZHbhp7J5C

**Comment by bodqhrohro** [comment]
@agnivade I already did https://github.com/bodqhrohro/smstree/commit/5f28f5b794faa7a8c70dd1b375f4df72e94b146a

**Comment by robpike** [comment]
I think the compatibility guidelines make it hard to fix this constant. We could add another one, but I don't think it's worth it. As already said, it's easy to write one's own.

**Comment by bodqhrohro** [comment]
Okay, but it would be good to add a notice to documentation, that the constants don't completely conform the standards and should be used with caution. I was lucky to discover it this early, but others may be less lucky.

**Comment by ianlancetaylor** [comment]
This seems related to #20869.

Note that the documentation already explicitly says "RFC3339, RFC822, RFC822Z, RFC1123, and RFC1123Z are useful for formatting; when used with time.Parse they do not accept all the time formats permitted by the RFCs." (https://golang.org/pkg/time/#pkg-constants).

I don't really see anything else to do here.

**Comment by bodqhrohro** [comment]
>the documentation already explicitly says

Didn't notice that, sorry. Then yes, there's nothing to do right now. Though, would it be added in the roadmap for a next major release, if it is planned already?

**Comment by bcmills** [comment]
> Then yes, there's nothing to do right now.

Given that at least three of us chimed in on this issue without noticing the documentation, I'd say that the documentation is not very discoverable — that particular section is so verbose that this (perhaps important) detail ended up buried.

That said, I don't see a way to make it more concise without dropping something equally important, so closing.
