### ISSUE TITLE
differing results writing []byte to stdout in win and linux

### ISSUE THREAD

**Issue by eudore** [golang/go#34460]
### What version of Go are you using (`go version`)?

<pre>
$ go version
win: go version go1.13 windows/amd64
linux: go version go1.10.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go version go1.13 windows/amd64
go version go1.10.1 linux/amd64
</pre></details>

### What did you do?

run code

```golang
package main

import(
	"os"
)

func main() {
	data := make([]byte, 128)
	os.Stdout.Write(data)
	os.Stdout.Write([]byte("end"))
}
```

### What did you expect to see?

result equal in linux and win

### What did you see instead?

![截图20190923032902](https://user-images.githubusercontent.com/30709860/65393390-882bcd80-ddb2-11e9-8d86-d3df7f768830.png)

**Comment by ericlagergren** [comment]
This is likely just because of how the different terminal applications display null bytes.

Try writing printable characters, like `'A'`.

**Comment by ianlancetaylor** [comment]
This doesn't have anything to do with Go.  The same thing would happen with a similar program in a language like C.  Closing.  Please comment if you disagree.

**Comment by eudore** [comment]
I don't know this, I just think that the results are different on different platforms.

**Comment by ianlancetaylor** [comment]
Yes, the output is different on different platforms.  It's just that that doesn't have anything to do with Go.  It's because different platforms are different.
