### ISSUE TITLE
x/sys: golang.org/x/crypto/ssh/terminal fail for windows

### ISSUE THREAD

**Issue by le0pard** [golang/go#34461]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/travis/.cache/go-build"
GOENV="/home/travis/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/travis/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/travis/.gimme/versions/go1.13.linux.amd64"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/travis/.gimme/versions/go1.13.linux.amd64/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build020438651=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Building https://github.com/le0pard/certonid

Result: https://travis-ci.com/le0pard/certonid/jobs/238002946

```
--> windows/amd64 error: exit status 2
Stderr: # golang.org/x/crypto/ssh/terminal
../../../golang.org/x/crypto/ssh/terminal/util_windows.go:97:7: assignment mismatch: 2 variables but "golang.org/x/sys/windows".GetCurrentProcess returns 1 values
```

### What did you expect to see?

No errors for windows build.

### What did you see instead?

Errors. Reason looks like in this commit:

https://github.com/golang/sys/commit/2dccfee4fd3e23e10ba17b9d696cf2388c28764b

It change return values from 2 to 1. This break this code: https://github.com/golang/crypto/blob/master/ssh/terminal/util_windows.go#L97

**Comment by zx2c4** [comment]
Trivial fix on its way in that CL.

**Comment by toothrot** [comment]
Looks like a deliberate breaking API change in `x/sys/windows`

/cc @FiloSottile for x/crypto 
/cc @alexbrainman @bradfitz Do we know other places this could be broken in our x/ repos from golang/sys@2dccfee?
