### ISSUE TITLE
Golang Modules 1.13

### ISSUE THREAD

**Issue by godfather667** [golang/go#34462]
### What version of Go are you using (`go version`)? 1.13

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="=/home/thornton/GO_WorkSpace/bin"
GOCACHE="/home/thornton/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/thornton/GO_WorkSpace"
GOPROXY=""
GORACE=""
GOROOT="/home/thornton/go"
GOTMPDIR=""
GOTOOLDIR="/home/thornton/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/thornton/GO_WorkSpace/src/hello/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build927771379=/tmp/go-build -gno-record-gcc-switches"

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do? 

FIRST THE BASIC PROBLEM

Bottom Line:   Simply installed 1.13 without doing anything special
,                      It appears to think it is 1.12.9  that is why GO111MODULE must be
                      set to "on" to get go mod init to work.
I have no idea what is going wrong -  It appears to be a bad download file.

So downloaded it again - same problems! 

THE FOLLOWING SUPPORTING INFORMATION:

Just installed 1.13

I first tested the hello.dir WITHOUT go.mod using LITEIDE and it worked
Ran go test in the same directory and got the version mismatch documented below

Running go test in the same dir produces the tool version mismatch shown below

With go.mod and GO111MODULE=auto
gp mod init  failed
   "go: modules disabled inside GOPATH/src by GO111MODULE=auto; see 'go help modules'"

### What did you see instead?
Error Above

go version = go version go1.12.9 linux/amd64

The version file in go dir = 1.13

I tried setting GO111MODULE=on

go  mod init

Produced: :"go: creating new go.mod: module hello"

NOW: ran go test on dir with hello test files

Produced::

NEPTUNE:hello$go tes
# runtime/internal/sys
compile: version "go1.13" does not match go tool version "go1.12.9"
# internal/race
compile: version "go1.13" does not match go tool version "go1.12.9"
# unicode
compile: version "go1.13" does not match go tool version "go1.12.9"
# unicode/utf8
compile: version "go1.13" does not match go tool version "go1.12.9"
# internal/cpu
compile: version "go1.13" does not match go tool version "go1.12.9"
# math/bits
compile: version "go1.13" does not match go tool version "go1.12.9"
# sync/atomic
compile: version "go1.13" does not match go tool version "go1.12.9"
# runtime/internal/atomic
compile: version "go1.13" does not match go tool version "go1.12.9"
FAIL    hello [build failed]

**Comment by agnivade** [comment]
Your Go installation got messed up. Please remove the entire directory `/home/thornton/go` and then reinstall Go 1.13 again.
