### ISSUE TITLE
There is a 3.8% performance regression building in go when I upgrade from go-12.9 to go-13.0

### ISSUE THREAD

**Issue by jiebinn** [golang/go#34487]
### What version of Go are you using (`go version`)?

<pre>
13.0

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pnp/.cache/go-build"
GOENV="/home/pnp/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pnp/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="gcc-ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build249663122=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

1. wget https://phoronix-test-suite.com/releases/phoronix-test-suite-9.0.0.tar.gz
2. tar zxvf phoronix-test-suite-9.0.0.tar.gz
3. cd ~/phoronix-test-suite
./install-sh
4. phoronix-test-suite run go-benchmark
5. select the option: build

### What did you expect to see?
I hope there is no regression building in go when I upgrade from go-12.9 to go-13.0

### What did you see instead?
3.8% loss in go-benchmark(option: build)

**Comment by randall77** [comment]
Where can I get the source for the benchmark? It isn't in that download.

By "build", is this a benchmark of building Go programs? I don't think it is a large problem that builds are 3.8% slower. If you wish to continue investigating, It might help to narrow down where the extra time goes - compiler or linker? What compiler phase? Etc.
