### ISSUE TITLE
x/tools/gopls: improve highlighting

### ISSUE THREAD

**Issue by stamblerre** [golang/go#34496]
Document highlight doesn't provide highlighting for fields or multiple uses of the same function. Should it? This issue will track missing behaviors for the `textDocument/highlight` command.

**Comment by stamblerre** [comment]
@ridersofrohan will be working on this

**Comment by ridersofrohan** [comment]
Commit [0a3398](https://github.com/golang/tools/commit/0a33398bd99d3bc1734cb619084d261e3a74f147)

Improved tests for highlights by allowing you to specify what should be highlighted for each mark. Also fixed issue [#2785](https://github.com/microsoft/vscode-go/issues/2785).

**Comment by ridersofrohan** [comment]
Commit [66c5a5](https://github.com/golang/tools/commit/66c5a5ad765973056b61480fe9a4cba406ebda4d)

Adds control flow highlighting within for loops.

**Comment by stamblerre** [comment]
I think that this can be closed after https://go-review.googlesource.com/c/tools/+/208267. Thanks @ridersofrohan!
