### ISSUE TITLE
How to omit module name

### ISSUE THREAD

**Issue by zhangmiaowater** [golang/go#34493]
after go v1.12 , when i use `go mod init XXX`, i have to import XXX inside my code , how can i omit it or use some variable to replace it, because when i want to change my module name, it's an exhausting operating to replace all module name in my project

**go.mod**
`module site_repo_admin

go 1.13
`

**demo.go**
`package demo

import (
	// "fmt"
	"time"
	"site_repo_admin/app/db/mysql"
	"site_repo_admin/libs/uuid"
)
...
`

**Comment by bcmills** [comment]
Every module must have a unique path, ideally starting with a domain name that you control. That is what prevents module names from colliding, and therefore is not optional.

If for some reason you decide to change your module path, if you already have a unique path prefix it is straightforward to update the code using `sed` or similar batch-editing tools.

For example, to replace all occurrences of the prefix `example.com/foo` with `example.com/bar`:
```
sed -i s,example.com/foo,example.com/bar, $(find . -name '*.go')
```
