### ISSUE TITLE
x/tools/gopls: vet and staticcheck return "same" diagnostic

### ISSUE THREAD

**Issue by myitcv** [golang/go#34494]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +c3c53661ba Tue Sep 17 04:37:46 2019 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20190923183622-59c6680fe2c1
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.0.0-20190923183622-59c6680fe2c1
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build538251118=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Running with `staticcheck` turned on.

With the following file:

```go
package main

import "fmt"

func main() {
	fmt.Printf("%s")
}
```

the following "identical" diagnostics are returned:

```
PublishDiagnostics callback: &protocol.PublishDiagnosticsParams{
    URI:         "file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go",
    Version:     0,
    Diagnostics: {
        {
            Range: protocol.Range{
                Start: protocol.Position{Line:5, Character:1},
                End:   protocol.Position{Line:5, Character:1},
            },
            Severity:           2,
            Code:               nil,
            Source:             "printf",
            Message:            "Printf format %s reads arg #1, but call has 0 args",
            Tags:               nil,
            RelatedInformation: nil,
        },
        {
            Range: protocol.Range{
                Start: protocol.Position{Line:5, Character:11},
                End:   protocol.Position{Line:5, Character:11},
            },
            Severity:           2,
            Code:               nil,
            Source:             "SA5009",
            Message:            "Printf format %s reads arg #1, but call has only 0 args",
            Tags:               nil,
            RelatedInformation: nil,
        },
    },
}
```

### What did you expect to see?

Just one diagnostic reporting the missing argument.

### What did you see instead?

Two, as above.

---

cc @stamblerre @ianthehat

**Comment by stamblerre** [comment]
Thanks for reporting. I guess the correct solution would be to maintain some set of duplicate checks. Deduping these diagnostics as we see them wouldn't work because they may have differently worded messages, etc.

Should we disable vet checks that are provided by staticcheck or vice versa?

**Comment by myitcv** [comment]
> Should we disable vet checks that are provided by staticcheck or vice versa?

I seem to recall from Slack the other day, @dominikh mentioning that he plans to effectively subsume all vet checks in `staticcheck`. But I'll leave up to you all to decide which is the source of truth :)

**Comment by dominikh** [comment]
That is indeed the plan, but it is a long-term plan for me. And, of course, vet will continue to gain new checks, too, so I wouldn't simply replace `vet` with `staticcheck` in gopls. 

Maintaining a list of duplicate checks sounds like the correct approach. Deciding which implementation of a check to use will be the hard part. Some checks are better in staticcheck, some are better in vet… And the list will need to be kept in sync as either vet or staticcheck gain new checks that overlap.

**Comment by dominikh** [comment]
Also, this issue extends to golint as well.

**Comment by myitcv** [comment]
@stamblerre just wondering whether this is small enough to try and fix for v1.0.0? It's a bit of an annoyance to have double entries in the diagnostics.

**Comment by stamblerre** [comment]
Is it just this check that's a duplicate or are there others? I can hardcode something if it's just a few.

**Comment by myitcv** [comment]
I've only seen this one to date.
