### ISSUE TITLE
x/build: hang in ppc64 buildlet not handled

### ISSUE THREAD

**Issue by laboger** [golang/go#34500]
The ppc64 builders were seeing hangs freqently and while investigating I noticed this on farmer.golang.org:

go-be-1 (140.211.168.40:49707) version 23, host-linux-ppc64-osu: connected 113h15m55.9s, working for 113h11m26.9s

This particular hang was resolved by @bcmills 
I was asked to open an issue on the fact that this was not handled by the build system.

I believe the problem with hangs during the buildlets has been resolved by CL 196658.

**Comment by bcmills** [comment]
CC @toothrot @dmitshur

**Comment by ceseo** [comment]
I haven't seem these in a while too. Seem resolved by the recent changes that addressed builder issues.

**Comment by ianlancetaylor** [comment]
CC @bradfitz

**Comment by bradfitz** [comment]
I'm going to close this as a dup of #10921.
