### ISSUE TITLE
go mod: git setting "instead of" not work in go mod

### ISSUE THREAD

**Issue by anotherGoogleFan** [golang/go#34513]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xxx\AppData\Local\go-build
set GOENV=C:\Users\xxx\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\GoProjects
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\xxx\AppData\Local\Temp\go-build269664658=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I set in git like
```
git config --global url."git@git.example.net:".insteadOf "https://git.example.net/"
```
and it works fine.
But when I cd a project folder such as git.exmaple.net/yyy with a go.mod file, and run 
```
go get git.example.net/xxx
```
I see something like this:
```
go get git.example.net/xxx: unrecognized import path "git.example.net/xxx" (https fetch: Get https://git.example.net/xxx: x509: certificate signed by unknown authority)
```
It seems that the config in git not work here.
And...
```
go mod tidy -v
git.example.net/yyy imports
        git.example.net/xxx: cannot find module providing package git.example.net/xxx
```

**Comment by bcmills** [comment]
The `git` configuration only affects operations on the underlying `git` repo. The error that you're seeing is coming from before that, when the `go` command is attempting to resolve the repo for the requested package path.

See https://golang.org/cmd/go/#hdr-Remote_import_paths.
