### ISSUE TITLE
sync/cond: redundant code in copyChecker.check

### ISSUE THREAD

**Issue by xris-hu** [golang/go#34516]
the copy chcker implementation (src/sync/cond.go,line :81)

```go
func (c *copyChecker) check() {
	if uintptr(*c) != uintptr(unsafe.Pointer(c)) &&
		!atomic.CompareAndSwapUintptr((*uintptr)(c), 0, uintptr(unsafe.Pointer(c))) &&
		uintptr(*c) != uintptr(unsafe.Pointer(c)) {
		panic("sync.Cond is copied")
	}
}
```

the code `uintptr(*c) != uintptr(unsafe.Pointer(c))` have twice in same if branch.

**Comment by av86743** [comment]
Reviewed on https://codereview.appspot.com/11573043 .

**Comment by ALTree** [comment]
Note that `A && f( ) && A` is not equivalent to `A && f( )` if `f` changes a memory location involved in the `A` expression. So this may be intentional.

**Comment by av86743** [comment]
This is how it works:

First A - quick check that either pointer is not initialized (zero) or initialized to address different from its own (Cond was copied). On fastpath it fails, so it's all right for `&& f(  ) && A` to be "slow".
f( ) - initializes pointer with its own address if not initialized yet.
Second A - now that pointer is initialized (not zero), verifies that pointer contains its own address.

**Comment by ALTree** [comment]
I suspect it's something like that, and the code should be left as it is. cc @dvyukov

**Comment by av86743** [comment]
Originator's reasoning is as follows:
- second A computes only if f( ) holds, that is if `CompareAndSwapUintptr` returns false, that is when pointer is not changed;
- if pointer is not changed by f( ), second A should be the same as first A (that is, true.) Hence redundancy.

**Comment by av86743** [comment]
However, consider the following scenario: 

Two or more goroutines are using an uninitialized Cond so that their `f( )` compute concurrently.  Only one `f( )` will succeed to initialize pointer; all other will not.  Without "redundant" second A, these latter would all unnecessarily panic.

**Comment by ALTree** [comment]
As suspected this is working as intended. Let's use #40924 to track the possibility of adding a comment.
