### ISSUE TITLE
I want to get member's reflect.Type via struct definition, but not it's instance.

### ISSUE THREAD

**Issue by alswell** [golang/go#34521]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.4 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build414398923=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
	type MyStruct struct {
		A int `json:"a"`
	}
	obj := MyStruct{} // I need to create an object of this struct first
	fmt.Println(reflect.TypeOf(obj).Field(0).Tag.Get("json"))
	fmt.Println(reflect.TypeOf(obj).Field(0).Type)

### What did you expect to see?
I can get reflect.Type via 'MyStruct' itself, but not it's instance.
I only want to get the member's tag and type, if I need to create an object of this class first, it looks strange

### What did you see instead?
I can get reflect.Type via 'MyStruct' itself, but not it's instance.
I only want to get the member's tag and type, if I need to create an object of this class first, it looks strange

**Comment by randall77** [comment]
You can do this:
```
fmt.Println(reflect.TypeOf(MyStruct{}).Field(0).Tag.Get("json"))
fmt.Println(reflect.TypeOf(MyStruct{}).Field(0).Type)
```

It may look strange, but that's what you need to do to get a type. Types aren't first-class types in Go, you need to start with a value and ask reflect to find its type.

Do you have some concrete proposal for how it should work instead?

**Comment by mdempsky** [comment]
I don't think there's any action here.
