### ISSUE TITLE
go mod why says nothing is needed

### ISSUE THREAD

**Issue by carnott-snap** [golang/go#34532]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY="*.sc-corp.net"
GONOSUMDB="*.sc-corp.net"
GOOS="linux"
GOPATH="/home/user/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/user/.local/share/umake/go/go-lang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/.local/share/umake/go/go-lang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/trash/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build372133803=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```go
// go.mod
module mod

go 1.13

require cloud.google.com/go v0.46.3
```

```go
// main.go
package main

import _ "cloud.google.com/go/compute/metadata"

func main() {}
```

### What did you expect to see?
```sh
[user@localhost ~]$ go mod why cloud.google.com/go
# cloud.google.com/go
mod
cloud.google.com/go
```

### What did you see instead?
```sh
[user@localhost ~]$ go mod why cloud.google.com/go
# cloud.google.com/go
(main module does not need package cloud.google.com/go)
```

**Comment by mvdan** [comment]
Perhaps you meant `go mod why -m cloud.google.com/go`? `go mod why` works on packages, `go mod why -m` works on modules.

**Comment by carnott-snap** [comment]
That would be my issue. I find it confusing that the default for `go mod why` is to accept package names, and has an `-m` flag for module names, since I would expect the opposite, a `-p` flag for packages. But the feature has been released, so I guess this interface is a foregone conclusion.
