### ISSUE TITLE
cmd/go: go build output creates unexpected file when directory of same name exists

### ISSUE THREAD

**Issue by 13rac1** [golang/go#34535]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/b/.cache/go-build"
GOENV="/home/b/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build792560259=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

1. Created a basic main.go
2. Built the main.go specifying an output with the same name as an existing directory.

```
$ docker run --rm -it golang:1.13-alpine3.10 sh
/go # cd
~ # vi main.go 
~ # cat main.go 
package main

import "fmt"

func main() {
	fmt.Println("Hello")
}
~ # mkdir test
~ # go build -o test main.go 
~ # ls -l test/
total 1964
-rwxr-xr-x    1 root     root       2008649 Sep 25 18:45 command-line-arguments
```

### What did you expect to see?

An error message saying the file cannot be created.

```
$ mkdir test
$ go build -o test main.go
go build _/root: open /root/test: file exists
```
### What did you see instead?

A file created with the surprising name `/root/test/command-line-arguments`.

*This is a minor strange issue. Seemed best to document, rather than ignore.*

#31296 is related.

**Comment by jayconrod** [comment]
The intended behavior is documented in [`go help build`](https://golang.org/cmd/go/#hdr-Compile_packages_and_dependencies):

```
Build compiles the packages named by the import paths,
along with their dependencies, but it does not install the results.

If the arguments to build are a list of .go files from a single directory,
build treats them as a list of source files specifying a single package.

When compiling a single main package, build writes
the resulting executable to an output file named after
the first source file ('go build ed.go rx.go' writes 'ed' or 'ed.exe')
or the source code directory ('go build unix/sam' writes 'sam' or 'sam.exe').
The '.exe' suffix is added when writing a Windows executable.

When compiling multiple packages or a single non-main package,
build compiles the packages but discards the resulting object,
serving only as a check that the packages can be built.

When compiling packages, build ignores files that end in '_test.go'.

The -o flag forces build to write the resulting executable or object
to the named output file or directory, instead of the default behavior described
in the last two paragraphs. If the named output is a directory that exists,
then any resulting executables will be written to that directory.
```

There is a bug here, which is that the output file is named `test/command-line-arguments`. It should be named `test/main` instead.
