### ISSUE TITLE
proxy.golang.org: dial tcp 173.194.197.141:443: i/o timeout

### ISSUE THREAD

**Issue by myitcv** [golang/go#34548]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +1804bbab62 Tue Sep 24 18:20:52 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/golang.org/x/tools/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build451498395=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Happened around ~5 mins ago. Reporting in case this is something you want to investigate further.

```
go: github.com/kr/pty@v1.1.5: Get https://proxy.golang.org/github.com/kr/pty/@v/v1.1.5.info: dial tcp 173.194.197.141:443: i/o timeout
go: github.com/acarl005/stripansi@v0.0.0-20180116102854-5a71ef0e047d: Get https://proxy.golang.org/github.com/acarl005/stripansi/@v/v0.0.0-20180116102854-5a71ef0e047d.info: dial tcp 173.194.197.141:443: i/o timeout
```

### What did you expect to see?

No timeout

### What did you see instead?

Per above

cc @hyangah @heschik @katiehockman

**Comment by heschik** [comment]
Thanks for the report. An error creating the TCP connection is well before anything specific to the mirror. It could be a problem with a Google edge server, or it could be an ISP glitch, etc, but it's unlikely to be anything we can fix ourselves.

I'll leave this open in case there are any other reports, in which case we can try to get help investigating further, but hopefully it's just a one-off.

**Comment by heschik** [comment]
Seems to have been a one-off.
