### ISSUE TITLE
syscall: TestGroupCleanupUserNamespace test failure on CentOS 

### ISSUE THREAD

**Issue by walnut-tom** [golang/go#34547]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64

$ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/workspace/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/opt/app/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/app/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/opt/app/go-go1.13.1/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build811145108=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```
tar -xvf go-go1.13.1.tar.gz
cd go-go1.13.1/src
bash all.bash

##### Testing packages.
[...]
--- FAIL: TestGroupCleanupUserNamespace (0.02s)
    exec_linux_test.go:314: id command output: "uid=0(root) gid=0(root) groups=0(root) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023", expected one of ["uid=0(root) gid=0(root) groups=0(root)" "uid=0(root) gid=0(root) groups=0(root),65534(nobody)" "uid=0(root) gid=0(root) groups=0(root),65534(nogroup)" "uid=0(root) gid=0(root) groups=0(root),65534" "uid=0(root) gid=0(root) groups=0(root),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody)"]
FAIL
FAIL	syscall	3.238s
[...]
FAIL
2019/09/26 11:14:49 Failed: exit status 1
```

**Comment by tklauser** [comment]
This is due to the SELinux context information in `id` output, see http://selinuxproject.org/page/SELinux_contexts and http://selinuxproject.org/page/Guide/Contexts

We should probably add this to the range of expected strings.
