### ISSUE TITLE
sql.NullString.Valid is true for empty string.

### ISSUE THREAD

**Issue by vishichoudhary** [golang/go#34553]
### What version of Go are you using (`go version`)?

<pre>
$ go 1.11 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

</pre></details>

### What did you do?

```
var address sql.NullString
db.Query("query").Scan(&address)
log(address)
```
if address is empty string

### What did you expect to see?
`{ false}`

### What did you see instead?
`{ true}`

**Comment by dominikbraun** [comment]
If `address` is an empty string, it is correct that `adress.Valid` is `true` since an empty string is a valid value. It would have to be `NULL` for being invalid:

https://golang.org/src/database/sql/sql.go?s=4962:5012#L178

**Comment by bcmills** [comment]
Per @dominikbraun's comment this seems to be working as documented, and I don't see any way to make the documentation clearer on this point, so closing.
