### ISSUE TITLE
doc: https://golang.org/doc/devel/release.html doesn't mention Go 1.13.1

### ISSUE THREAD

**Issue by dmgk** [golang/go#34555]
https://golang.org/doc/devel/release.html is missing an entry for go1.13.1 minor revision.

**Comment by bcmills** [comment]
CC @golang/osp-team 

We should update the release process so that this gets done before the release announcement next time. 😞

**Comment by FiloSottile** [comment]
This just needs a website push, which I am about to do. It's intentionally not before the announcement in security releases, because we want to minimize the time between the first public appearance of the patches and the announcement.

**Comment by bcmills** [comment]
For security releases, we should arguably update and push `release.html` (with minimal detail) as soon as we pre-announce the release.

**Comment by dmitshur** [comment]
This is done now.

https://golang.org/doc/devel/release.html#go1.13.minor
