### ISSUE TITLE
runtime: high-percentile latency of memory allocations has regressed significantly [1.13 backport]

### ISSUE THREAD

**Issue by mknyszek** [golang/go#34556]
For some reason gopherbot wouldn't open a backport issue for me. This is a backport of #31678.

The fixes for this (once and for all) have landed in master. https://go-review.googlesource.com/c/go/+/183857/9 

The importance of this bug for a 1.13 backport is the fact that it's one of the pieces to the fix for #32828 for Go 1.13, which is a major regression in Kubernetes which is blocking them from landing.

There are two problems with Kubernetes: inline scavenging on the allocation path can really spike allocation tail latencies (this issue) and it could spiral into over-scavenging if fragmentation is not accounted for (#34149).

The fixes for both issues must be landed together to completely fix the issue.

**Comment by aclements** [comment]
I agree that we should backport this fix. This and #34149 are blocking k8s from upgrading to Go 1.13.

To be clear, the following two CLs need to be backported for this:
https://go-review.googlesource.com/c/go/+/189957/4
https://go-review.googlesource.com/c/go/+/183857/9

CL 183857 is nearly identical to a change we backported to Go 1.12. CL 189957 is necessary for CL 183857 to be most effective.
