### ISSUE TITLE
x/tools/go/analysis/passes/shadow/cmd/shadow: shadow inconsistent failures when var in code shadows a var in a test file

### ISSUE THREAD

**Issue by leighmcculloch** [golang/go#34557]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

The docker image that was in use was: `circleci/golang:1.13-stretch` and with digest `sha256:728d4283948f6f2666c6dbdcb56648a5db9056431265d296175449463a82c072`.

You can get that specific version of the image with:
```
$ docker pull circleci/golang@sha256:728d4283948f6f2666c6dbdcb56648a5db9056431265d296175449463a82c072
```

### Does this issue reproduce with the latest release?

I was not able to reproduce locally with go1.13 or go1.13.1.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/circleci/.cache/go-build"
GOENV="/home/circleci/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build650242782=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Ran `shadow ./...` in the root repository of this revision of stellar/go@c638a262494bddb19368254a8beb75e21ff77f1f.

I first installed `shadow` using go modules in a tmp directory, then changed back to the project and run `shadow ./...`.

### What did you expect to see?

Consistently either report no errors, or consistently report an error.

### What did you see instead?

Some runs pass the shadow checker, some runs fail.

An example of a failing run:

```
/tmp/tmp.AztFEDruDz /go/src/github.com/stellar/go
go: creating new go.mod: module tool
go: finding golang.org/x/tools latest
go: downloading golang.org/x/tools v0.0.0-20190925230517-ea99b82c7b93
go: extracting golang.org/x/tools v0.0.0-20190925230517-ea99b82c7b93
/go/src/github.com/stellar/go
/go/src/github.com/stellar/go/keypair/main.go:95:2: declaration of "seed" shadows declaration at line 19
```

See https://app.circleci.com/jobs/github/stellar/go/8686.

The version of `shadow` being used is from commit golang/tools@ea99b82c7b93.

Line 95 of `main.go` defines `seed` in a function:
```
$ sed '94,95!d' keypair/main.go
func FromRawSeed(rawSeed [32]byte) (*Full, error) {
        seed, err := strkey.Encode(strkey.VersionByteSeed, rawSeed[:])
```

Line 19 of `main.go` is a comment:
```
$ sed '19!d' keypair/main.go
        // through malformation or if it does not verify the message against the
```

However as @bartekn points out in https://github.com/stellar/go/pull/1778#issuecomment-535569232, `seed` is defined in `main_test.go`.

```
$ sed '17,19!d' keypair/main_test.go
var (
        address   = "GBRPYHIL2CI3FNQ4BXLFMNDLFJUNPU2HY3ZMFSHONUCEOASW7QC7OX2H"
        seed      = "SDHOAMBNLGCE2MV5ZKIVZAQD3VCLGP53P3OBSBI6UN5L5XZI5TKHFQL4"
```

Issues here:
- The output of the message is confusing because it doesn't mention that the shadowed variable is in another file, i.e. `main_test.go`.
- The failure is inconsistent. Most of the time there is no failure, then sometimes there is.

**Comment by bcmills** [comment]
CC @ianthehat @matloob

**Comment by leighmcculloch** [comment]
@ianthehat @matloob @bcmills Is this intended behavior of the shadow analyzer? Is the analyzer still intended for use or no longer maintained? Thanks!

**Comment by stamblerre** [comment]
Inconsistent failures definitely don't sound like intended behavior, so my guess is that it's not intended. However, the analyzer isn't part of the `go vet` suite or `gopls`, so it's probably not very well-maintained. We've been considering adding it as an opt-in analyzer for `gopls`, so perhaps we can take a look at this then.

**Comment by matloob** [comment]
The shadow analyzer is marked experimental. My guess is that the problem is that running shadow on the test variant of a package produces different results than running shadow on the 'production' variant of the package. Adding the test files produces a shadowing.

In any case I don't think we can enable shadow as is: it's hard to detect when a shadowing is intended and we certainly don't want to trigger for all shadowings.
