### ISSUE TITLE
C call Golang exported function with a string returned  

### ISSUE THREAD

**Issue by dingrui37** [golang/go#34565]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.9 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dingrui/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dingrui/go"
GOPROXY="https://goproxy.cn"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/dingrui/go/src/etcdagent/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build590317485=/tmp/go-build -gno-record-gcc-switches"</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dingrui/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dingrui/go"
GOPROXY="https://goproxy.cn"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/dingrui/go/src/etcdagent/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build590317485=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
C call golang exported function

### What did you expect to see?

Golang code:
```
//export EtcdGetNode
func EtcdGetNode(nodeId uint32) (int, string) {  //return a string to C
    a := "dingrui"
    b := 11111
    return b, a
}

```

Generated C code:
```
struct EtcdGetNode_return EtcdGetNode(GoUint32 p0)
{
	__SIZE_TYPE__ _cgo_ctxt = _cgo_wait_runtime_init_done();
	struct {
		GoUint32 p0;
		char __pad0[4];
		GoInt r0;
		GoString r1;
	} __attribute__((__packed__, __gcc_struct__)) a;
	struct EtcdGetNode_return r;
	a.p0 = p0;
	_cgo_tsan_release();
	crosscall2(_cgoexp_85163309d51b_EtcdGetNode, &a, 32, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
	r.r0 = a.r0;
	r.r1 = a.r1;
	return r;
}
```

GoString define：
```
#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif
```

I want to know does the returned pointer **const char *p** in GoString struct will be freed automatically by runtime（gc）？ 
In my opinion,  the var a and b will be allocated in heap memory, the address of var a contains a pointer which will point to the actual string(like char * in C language) and a length value in the memory， as shown in the following figure.

   a := "dingrui"
   
![image](https://user-images.githubusercontent.com/22718365/65739897-839c4780-e119-11e9-9171-c03909dd9172.png)

Will the pointer(0x00007ffff73e4227) be freed in runtime after return?

R## What did you see instead?

**Comment by ianlancetaylor** [comment]
An exported Go function is not permitted to return a string.  See https://golang.org/cmd/cgo/#hdr-Passing_pointers.  I'm surprised that this works at all.

Closing because there is nothing to fix.  Note that we don't use the issue tracker for questions.  See https://golang.org/wiki/Questions.

**Comment by dingrui37** [comment]
https://golang.org/cmd/cgo/#hdr-C_references_to_Go

![image](https://user-images.githubusercontent.com/22718365/65742972-20b0ad80-e125-11e9-807a-2f62db6fa9f6.png)

**Comment by ianlancetaylor** [comment]
Yes, that is from the reflect package documentation.  I'm not sure what you are trying to say.  Those functions don't return strings.

**Comment by dingrui37** [comment]
I don't see a description of this `"An exported Go function is not permitted to return a string"`， and compile result is succeeded, so I think it should be work.

**Comment by dingrui37** [comment]
//export MyFunction2
func MyFunction2(arg1, arg2 int, arg3 string) (int64, *C.char) {...}

where does the *C.char point to?

**Comment by ianlancetaylor** [comment]
> I don't see a description of this "An exported Go function is not permitted to return a string"， and compile result is succeeded, so I think it should be work.

I promise that the documentation is correct and that it doesn't work.

Perhaps the problem will be caught at runtime if you run with `GODEBUG=cgocheck=2` in the environment.

> where does the *C.char point to?

That depends on what `MyFunction2` decides to return.  As discussed later in the cgo docs, it must not be a Go pointer.  It could be allocated by, for example, `C.CString`.

**Comment by dingrui37** [comment]
Thank you. Can you tell me where there are more examples about C references to Go?

**Comment by ianlancetaylor** [comment]
There are some examples in misc/cgo/test and misc/cgo/life.

In general you will get better answers to questions if you use a forum.  See https://golang.org/wiki/Questions.

**Comment by dingrui37** [comment]
Hi, @ianlancetaylor , if I want to return an array to C caller, does it works? compile is ok.
```
//export EtcdGetAllNodes
func EtcdGetAllNodes()[]uint32 {
    a := []uint32{1,2,3}
    return a
}
```

**Comment by ianlancetaylor** [comment]
Returning an array is fine, but note that your example returns a slice.  Returning a slice is not fine.

**Comment by dingrui37** [comment]
```
//export EtcdGetAllNodes
func EtcdGetAllNodes()[5]uint32 {
    a := [5]uint32{1,2,3,4,5}
    return a
}

dingrui@dingrui ~/g/s/etcdagent> go build -o cgo/libetcdagent.so -buildmode=c-shared main.go
# command-line-arguments
./main.go:97:23: Go type not supported in export: [5]uint32
./main.go:97:23: Go type not supported in export: [5]uint32
```

**Comment by ianlancetaylor** [comment]
Oh, right, I forgot that Go functions can't return an array because there is no obvious corresponding C type.  Sorry.
