### ISSUE TITLE
cmd/compile: internal compiler error: missing posbase

### ISSUE THREAD

**Issue by toglader** [golang/go#34581]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.6 linux/arm

</pre>

### Does this issue reproduce with the latest release?

With Latest Raspbian lite distro

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="arm"
GOBIN=""
GOCACHE="/home/pi/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pi/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.11"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.11/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build107027772=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

pi@raspberrypi2:~ $ go get github.com/bettercap/bettercap

### What did you expect to see?

---

### What did you see instead?

# github.com/bettercap/bettercap/tls
go/src/github.com/bettercap/bettercap/tls/cert.go:135:22: internal compiler error: missing posbase

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new

**Comment by randall77** [comment]
@mdempsky

**Comment by mdempsky** [comment]
I'm not able to immediately reproduce this on linux/amd64, with either current Go or the Go 1.11.6 tag. (Aside: Go 1.11 is also outside of our support window, and is no longer receiving security fixes.)

If you can try running `go clean -cache -testcache -modcache` and then running `go get github.com/bettercap/bettercap` again, that would be interesting to see if you can reproduce the issue.

**Comment by toglader** [comment]
Uh?

<env>
pi@raspberrypi2:~ $ go get -u github.com/bettercap/bettercap
go tool compile: signal: segmentation fault
</env>

**Comment by mdempsky** [comment]
@toglader Yeah, hardware failure or at least SD corruption seems likely here, unfortunately. :(

I'll go ahead and close the issue. If you investigate further and start suspecting it is a Go issue (eg, reinstall and everything but Go is working normally), please let us know and we can resume looking into it.
