### ISSUE TITLE
x/sys/unix: OpenBSD: MAP_CONCEAL missing except on arm64

### ISSUE THREAD

**Issue by awnumar** [golang/go#34589]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.9 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
xpslinux :: ~ » go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/awn/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/awn/src/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build069259099=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Received a [report](https://github.com/awnumar/memcall/issues/1) of a compile fail due to the `MAP_CONCEAL` flag being missing on OpenBSD.

### What did you expect to see?

Expected to see it defined since it is supported on OpenBSD: https://man.openbsd.org/mmap.2#MAP_CONCEAL

### What did you see instead?

A grep of the code-base shows that it is indeed defined, but only on ARM64: https://github.com/golang/sys/blob/2aa67d56cdd77167a5fb51358e8c3ce04bad68bb/unix/zerrors_openbsd_arm64.go#L927

**Comment by smasher164** [comment]
./mkall.sh probably needs to be re-run on OpenBSD >= 6.5
