### ISSUE TITLE
x/tour: welcome/3 slide missing instructions for installing Go

### ISSUE THREAD

**Issue by dmitshur** [golang/go#34585]
The first slide of the tour welcomes people and explains how to change slides. The second slide mentions the choice of spoken languages. The third slide strongly suggests running the tour offline.

By the [third slide](https://tour.golang.org/welcome/3), the tour assumes users already have Go installed (and/or know how to install Go). This isn't valid for users who are being introduced to Go by being linked to the tour. It can cause unnecessary confusion as demonstrated by the experience reported in [this comment](https://github.com/golang/go/issues/24819#issuecomment-487723046).

That slide used to have instructions for installing Go, but they were lost as part of deployment changes in [CL 141857](https://golang.org/cl/141857). /cc @andybons

To fix this, we should include a link to https://golang.org/doc/install and/or https://golang.org/dl/ before the first mention of `go get` in the tour. It should also be helpful and a good teaching opportunity to point out where the `tour` binary ends up after `go get` runs successfully.

This issue is factored out from #24819, which was about a formatting bug that is resolved by now.

**Comment by Accflex** [comment]
https://accflex.com/
