### ISSUE TITLE
cmd/go: "could not load export data" regression running staticcheck

### ISSUE THREAD

**Issue by kevinburkemeter** [golang/go#34588]
Steps to reproduce:

- on a Macbook Pro running latest OS, compile Go at version 95b8cbfee93766274583bacfb98b3b0cc1dbb6cf
- run `go install golang.org/x/tools/...` with latest x/tools version
- run `go install honnef.co/go/tools/...` with either the latest tagged staticcheck release or the latest commit on master.
- run `staticcheck ./...` on any codebase, for example github.com/kevinburke/go-bindata

I expect it to report the usual set of linter errors (or none, if the linter reports no errors). Instead I get output that looks like this:

```
-: could not analyze dependency crypto/rand of github.com/kevinburke/go-bindata [github.com/kevinburke/go-bindata.test]:
	could not analyze dependency errors of crypto/rand:
	could not analyze dependency internal/reflectlite of errors:
	could not analyze dependency runtime of internal/reflectlite:
	could not analyze dependency runtime/internal/math of runtime:
	could not analyze dependency runtime/internal/sys of runtime/internal/math:
	could not load export data: cannot import "runtime/internal/sys" (unknown iexport format version 1), export data is newer version - update tool (compile)
```

I cannot reproduce with the previous commit in the Go tree (683ef8c8441d100590f5ed5c9d662e217a7130ce).

I am trying to run Go tip as my primary development environment but this is the second workflow-breaking issue I have run into in two weeks (previously #34294). I am willing to accept occasional workflow disturbances but two in two weeks that require 30-60 minutes to track down is too many.

If a change in the export data requires these tools to be updated, maybe the new versions can be released in parallel.

**Comment by kevinburkemeter** [comment]
I just ran trybots on tip for both the Go project and x/tools and both passed.

**Comment by josharian** [comment]
Dup of #34564?

**Comment by kevinburkemeter** [comment]
I don't think so... that issue seems to be that it is tedious to update the logic in two places, but the author seems to think that the listed patches fixed things. 

I am compiling go and x/tools with both of the listed commits included - the newest versions of each - and getting the error message above.

**Comment by mdempsky** [comment]
Tools need to be built against a current version of x/tools to process object files built by current cmd/compile.

**Comment by kevinburkemeter** [comment]
I could have sworn I was running staticcheck with an updated go/tools, but I guess not. Seems to work if I compile it in. Whoops.
