### ISSUE TITLE
x/tools/cmd/godoc: method expression type can be misidentified

### ISSUE THREAD

**Issue by athomason** [golang/go#34583]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +739bf6b929 Fri Sep 27 21:17:15 2019 +0000 darwin/amd64

# golang.org/x/tools v0.0.0-20190927191325-030b2cf1153e
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<pre>darwin/amd64</pre>

### What did you do?

Examine the links generated for the definition of the DefaultTransport package var under https://tip.golang.org/pkg/net/http/#DefaultTransport. Notice that the value of the Transport's DialContext field is a method expression referencing net.Dialer.DialContext, but the generated link is to a non-existent http.DialContext function, creating a broken link.

```html
<pre>var <span id="DefaultTransport">DefaultTransport</span> <a href="#RoundTripper">RoundTripper</a> = &amp;<a href="#Transport">Transport</a>{
    <a href="#Transport.Proxy">Proxy</a>: <a href="#ProxyFromEnvironment">ProxyFromEnvironment</a>,
    <a href="#Transport.DialContext">DialContext</a>: (&amp;<a href="/pkg/net/">net</a>.<a href="/pkg/net/#Dialer">Dialer</a>{
        <a href="/pkg/net/#Dialer.Timeout">Timeout</a>:   30 * <a href="/pkg/time/">time</a>.<a href="/pkg/time/#Second">Second</a>,
        <a href="/pkg/net/#Dialer.KeepAlive">KeepAlive</a>: 30 * <a href="/pkg/time/">time</a>.<a href="/pkg/time/#Second">Second</a>,
        <a href="/pkg/net/#Dialer.DualStack">DualStack</a>: <a href="/pkg/builtin/#true">true</a>,
    }).<a href="#DialContext">DialContext</a>,
    <a href="#Transport.ForceAttemptHTTP2">ForceAttemptHTTP2</a>:     <a href="/pkg/builtin/#true">true</a>,
    <a href="#Transport.MaxIdleConns">MaxIdleConns</a>:          100,
    <a href="#Transport.IdleConnTimeout">IdleConnTimeout</a>:       90 * <a href="/pkg/time/">time</a>.<a href="/pkg/time/#Second">Second</a>,
    <a href="#Transport.TLSHandshakeTimeout">TLSHandshakeTimeout</a>:   10 * <a href="/pkg/time/">time</a>.<a href="/pkg/time/#Second">Second</a>,
    <a href="#Transport.ExpectContinueTimeout">ExpectContinueTimeout</a>: 1 * <a href="/pkg/time/">time</a>.<a href="/pkg/time/#Second">Second</a>,
}</pre>
```

### What did you expect to see?

`<a href="/pkg/net/#Dialer.DialContext">DialContext</a>`

### What did you see instead?

`<a href="#DialContext">DialContext</a>`

**Comment by agnivade** [comment]
For those interested, the relevant code is in godoc/linkify.go.

**Comment by athomason** [comment]
@agnivade thanks for the link to #9613, I thought this might be a dupe but searching for DialContext didn't turn it up.

**Comment by seankhliao** [comment]
I believe this doesn't affect pkgsite.
