### ISSUE TITLE
x/tools/gopls: unified diff tests don't handle multi file patches

### ISSUE THREAD

**Issue by ianthehat** [golang/go#34580]
we test unified diff output by attempting to apply the patch and seeing if we get the right result, we do this because the actual content of the patch does not matter and may vary, only the results of applying it can be verified to be correct.
because the only way to apply a multi-file patch is to modify the original files, we cannot easily do this in a test (single file mode writes to a different file instead)
we need to consider attempting to copy the files to a temporary directory to apply the patches to test this.

**Comment by findleyr** [comment]
This may still be worth doing, but isn't in a priority and doesn't need to be tracked. Just cleaning up.
