### ISSUE TITLE
parsing go.mod: unexpected module path

### ISSUE THREAD

**Issue by qiluge** [golang/go#34596]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>
go version go1.12.7 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/qiluge/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/mnt/f/code"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/mnt/f/code/src/git.ont.io/waas/walletsvr-eth/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build409963217=/tmp/go-build -gno-record-gcc-switches"
### What did you do?

use go mod to reference self repo, but failed.

### What did you expect to see?

go mod tidy success.

### What did you see instead?
walletsvr-eth reference chainbase repo, but failed:
![image](https://user-images.githubusercontent.com/19525062/65831896-b3ea0e80-e2f0-11e9-9995-ae736a09fccd.png)

go.mod of chainbase is:
![image](https://user-images.githubusercontent.com/19525062/65831906-cebc8300-e2f0-11e9-974e-396146ee4861.png)

**Comment by tiptok** [comment]
try this 
replace git.ont.io/waas/chainbase v0.0.1 => ../chainbase

**Comment by qiluge** [comment]
wow，it worked, thank you very much. But, what is reason of this?

**Comment by bcmills** [comment]
@qiluge, search for [module path] in https://golang.org/cmd/go/#hdr-Defining_a_module.
