### ISSUE TITLE
archive/zip: 

### ISSUE THREAD

**Issue by codyoss** [golang/go#34599]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="linux"
</pre></details>

### What did you do?

I navigated to [zip.Reader example](https://golang.org/pkg/archive/zip/#example_Reader). I hit the `Run` button

### What did you expect to see?

A working example

### What did you see instead?

`2009/11/10 23:00:00 open testdata/readme.zip: No such file or directory`

**Comment by ALTree** [comment]
Thanks for the report. 

That Example works fine when run locally, it's just that it cannot be run on the playground. The run button should be disabled for these example, and this is a known issue: #9679 (website: don't show un-runnable examples as runnable)

Closing here as a dup of 9679.
