### ISSUE TITLE
How does go deal with CPU cache?

### ISSUE THREAD

**Issue by g10guang** [golang/go#34598]
### What version of Go are you using (`go version`)?

<pre>
➜  gauss git:(master) go version
go version go1.12.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

My Question is from [here](https://stackoverflow.com/questions/58155021/strange-performance-about-cpu-cache)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
➜  gauss git:(master) go env
GOARCH="amd64"
GOBIN="/Users/g10guang/go/bin"
GOCACHE="/Users/g10guang/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/g10guang/go"
GOPROXY="https://go-mod-proxy.byted.org"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/g10guang/go/src/code.byted.org/rpc/gauss/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nr/lxtqsz6x1x1gfbyp1p0jy4p00000gn/T/go-build554794250=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I just scan the 2-dimension array.

### What did you expect to see?

Always scan from row to column is faster.

### What did you see instead?

Sometimes scan rows is faster, sometimes it's not.

But Cpp scan row always faster.

**Comment by mdlayher** [comment]
Questions like this are better suited for other places. Please see https://github.com/golang/go/wiki/Questions.
