### ISSUE TITLE
x/tools/internal/lsp: TestLSP/GOPATH/CompletionSnippets flake on darwin-amd64-10_14 builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#34617]
From the `darwin-amd64-10_14` builder in https://build.golang.org/log/d8674baf25fbfd7a1da3118451ccb1b6efcedec2:

```
--- FAIL: TestLSP (240.36s)
    --- FAIL: TestLSP/GOPATH (189.27s)
        --- FAIL: TestLSP/GOPATH/CompletionSnippets (10.14s)
            --- FAIL: TestLSP/GOPATH/CompletionSnippets/deep_23_9_placeholders (10.00s)
                completion_test.go:42: /var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/tmp/TestLSP_GOPATH313029317/lsp/src/golang.org/x/tools/internal/lsp/deep/deep.go:23:9-10: couldn't find completion matching "a.b"
FAIL
FAIL	golang.org/x/tools/internal/lsp	240.631s
```

**Comment by stamblerre** [comment]
It looks like this continues to happen. @muirrn: Any reason that you know of for that test to flake?

**Comment by muirrn** [comment]
My first thought would be completion running out of budgeted time and not performing the deep search, thus not finding the `a.b` candidate. That test sets the budget to 5 seconds, so it would have to be a major hiccup. We could try just turning up the budget or tweaking tests to have unlimited budget.

**Comment by muirrn** [comment]
I guess we do see that single test taking `10.00s` in the output, so probably just the occasional slow run. I'll look at disabling the time limit for tests.

**Comment by stamblerre** [comment]
I believe the flakiness should be fixed as of the above CL.
