### ISSUE TITLE
x/exp/rand: devirtualize interfaces

### ISSUE THREAD

**Issue by josharian** [golang/go#34614]
This is a reminder/tracking issue to apply the same optimizations as https://go-review.googlesource.com/c/go/+/191538 and https://go-review.googlesource.com/c/go/+/191539 to x/exp/rand.

cc @CAFxX @robpike

**Comment by robpike** [comment]
I just tried this and things got slower.

First I did 538 and that helped, then I did 539 and things slowed down.

I will send the CL anyway but I think without the compiler support this is just pointless complexity.

**Comment by odeke-em** [comment]
I believe this issue was fixed by CL https://go-review.googlesource.com/c/exp/+/198099 so I shall close it.
