### ISSUE TITLE
cmd/compile: unnecessary sign-extensions when converting int's

### ISSUE THREAD

**Issue by marigonzes** [golang/go#34625]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version devel +2c47caa Sat Sep 28 13:50:34 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What did you do?
I tested the behavior of the Go compiler when facing conversions from `int` to `uint`/`int` values of different sizes.

### What did you expect to see?
I expected then to be compiled down to a single instruction in most cases (don't know if this assumption is correct).

### What did you see instead?
Instead, they are compiled to two instructions.

Examples (not a complete list):

1. 
```go
func f(x int8) int64 {
    return int64(x)
}
```
```asm
movblzx "".x+8(SP), AX
movbqsx AL, AX
movq    AX, "".~r1+16(SP)
```
2. 
```go
func f(x int16) uint64 {
    return uint64(x)
}
```
```asm
movwlzx "".x+8(SP), AX
movwqsx AX, AX
movq    AX, "".~r1+16(SP)
```

**Comment by andybons** [comment]
@aclements

**Comment by randall77** [comment]
Yes, this is a known problem with loading of argument values from the stack.
We do the right thing for loads from other places:
```
func f(x int8) int64 {
	return int64(x)
}
func g(p *int8) int64 {
	return int64(*p)
}
```
`f` has an extra extension operation, but `g` does not.

Instead of a generic `Arg` opcode, we would need lots of opcodes like `ArgAsInt8`. Possible, but ugly.

Or maybe there's another way to fix it?

**Comment by josharian** [comment]
#15300

**Comment by mvdan** [comment]
@josharian do you mean that this issue is a duplicate, or simply that they're related?

**Comment by josharian** [comment]
Sorry. I suspect it is a duplicate.

**Comment by randall77** [comment]
I concur.
