### ISSUE TITLE
x/tools/go/packages: test timeout on freebsd-amd64-race builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#34621]
https://build.golang.org/log/10a77e60ed1952a8bbd937801dfd04d3b8aab6d1 shows a test timeout on the `freebsd-amd64-race` builder.

It may be that the test was deadlocked, or it may be that the builder just needs a longer scale factor for running the test.

It looks like the test got stuck running a subprocess, so if the problem is a deadlock, it might help to have the `go/packages` tests terminate subprocesses when the test runs out of time so that we can get goroutine dumps. (The tests for the `go` command do something similar [here](https://github.com/golang/go/blob/ba18c7c42d4fa70e81b2304ccc3b2c01675a3af0/src/cmd/go/go_test.go#L137-L148).)

CC @ianthehat @matloob @heschik @dmitshur @toothrot @bradfitz

**Comment by bcmills** [comment]
Still timing out frequently.

**Comment by bcmills** [comment]
This also masked an apparent regression in `x/tools/gopls/test` (#35691).

**Comment by matloob** [comment]
I'm not sure what we should do. Should we decrease the timeout?

**Comment by bcmills** [comment]
Hmm, that last log only showed a `signal: killed` for `golang.org/x/tools/go/packages`, and the actual timeout was for `golang.org/x/tools/internal/lsp/cmd`.

So probably `golang.org/x/tools/internal/lsp/cmd` needs some timeouts. The failure for `golang.org/x/tools/go/packages` may have been an OOM condition instead — the co-occurrence with a failure fo `x/tools/internal/lsp/cmd` suggests a possible connection to #33951.

**Comment by dmitshur** [comment]
This may be related to #36444.

**Comment by dmitshur** [comment]
I believe this has been fixed by the builder change in [CL 227859](https://golang.org/cl/227859). There have not been timeout errors in the `x/tools/go/packages` package lately. Closing.

This is a good data point for #33986.
