### ISSUE TITLE
Day of month not correct for Sept 1752

### ISSUE THREAD

**Issue by AgentZombie** [golang/go#34623]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

```
func main() {
	t := time.Date(1752, time.September, 1, 0, 0, 0, 0, time.Now().Location())
	fmt.Println(t)
	t = t.AddDate(0, 0, 1)
	fmt.Println(t)
	t = t.AddDate(0, 0, 1)
	fmt.Println(t)
}
```

### What did you expect to see?
```
1752-09-01 00:00:00 +0000 UTC
1752-09-02 00:00:00 +0000 UTC
1752-09-14 00:00:00 +0000 UTC
```

### What did you see instead?
```
1752-09-01 00:00:00 +0000 UTC
1752-09-02 00:00:00 +0000 UTC
1752-09-03 00:00:00 +0000 UTC
```

**Comment by ianlancetaylor** [comment]
The time functions use the timezone database from the local system.  If your local system doesn't have any special behavior defined for September, 1752, then the time package won't do anything then either.

Note that September 2, 1752, is when Great Britain changed to the Gregorian calendar.  Other countries changed in different years.  So I would only expect to see unusual behavior in a Great Britain timezone.  That said, as far as I know, the usual time zone database does not record this transition, so Go's time package won't report it.  See https://www.ietf.org/timezones/tzdb-2018a/theory.html, which explains that it uses the Gregorian calendar for all past times, knowing that that is inaccurate.

This isn't something that we are going to change in Go itself, so closing.
