### ISSUE TITLE
proxy.golang.org: master stale for github.com/uber/prototool

### ISSUE THREAD

**Issue by myitcv** [golang/go#34632]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +843fec1c7d Mon Sep 30 00:45:38 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/tmp/tmp.R2rBwS6opq"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/tmp.iOHDP8kKqj/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build271662756=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

At the time of writing, https://proxy.golang.org/github.com/uber/prototool/@v/master.info returns:

```json
{"Version":"v1.8.1","Time":"2019-06-11T00:54:35Z"}
```

However the most recent commit to `master` was 21 days ago:

https://github.com/uber/prototool/commit/7df3b957ffe3d09dc57fe4e1eb96694614db8c7a

### What did you expect to see?

The more recent version returned for version `master`

### What did you see instead?

An old version

cc @katiehockman @heschik @hyangah

**Comment by hyangah** [comment]
It seems to me the mentioned commit is only on their 'dev' branch. Am I missing something?

**Comment by mvdan** [comment]
I think the confusion here is because usually the HEAD branch is master. Is it possible to do `@HEAD`?

**Comment by myitcv** [comment]
@hyangah goodness, I'd totally missed the fact the default branch for that repo is `dev`! Thanks for pointing that out.

I'd therefore ask the same question as @mvdan - is there a way we can refer to the default branch, regardless of repository?

**Comment by hyangah** [comment]
I filed #29761 and rejected.

**Comment by myitcv** [comment]
Thanks for the link. Agree, this isn't exactly the highest priority :) I'll close this based on that previous discussion.
