### ISSUE TITLE
fmt: Println(i) is 3x slower than in C

### ISSUE THREAD

**Issue by krasin** [golang/go#3463]
<pre>Go 1, Linux amd64.

What steps will reproduce the problem?

1. Consider the following Go program: (<a href="http://play.golang.org/p/ScKzejb3Oc">http://play.golang.org/p/ScKzejb3Oc</a> )

package main

import &quot;fmt&quot;

func main() {
	for i := 0; i &lt; 1&lt;&lt;25; i++ {
		fmt.Println(i)
	}
}

2. Consider the following Python program:

for i in xrange(1 &lt;&lt; 25): print i

3. And the following C program:

#include &lt;stdio.h&gt;

int main(void) {
  for (int i = 0; i &lt; 1 &lt;&lt; 25; i++) {
    printf(&quot;%d\n&quot;, i);
  }
} 

4. Build Go program with:
$ go build print.go

and C program with:
$ gcc print.c -o print_c -c99

5. Run programs:

$ time ./print &gt; /dev/null
real	0m18.336s
user	0m15.497s
sys	0m2.824s

$ time python print.py &gt; /dev/null # I use python 2.7.2
real	0m9.484s
user	0m9.473s
sys	0m0.004s

$ time ./print_c &gt; /dev/null
real	0m2.580s
user	0m2.560s
sys	0m0.020s

What is the expected output?
It's expected that Go is as fast a C and faster than Python. 

What do you see instead?
Go is painfully slow on this microbenchmark.

Which compiler are you using (5g, 6g, 8g, gccgo)?
6g (via go build)

Which operating system are you using?
Linux krasin-tupak 3.0.0-16-generic #29-Ubuntu SMP Tue Feb 14 12:48:51 UTC 2012 x86_64
x86_64 x86_64 GNU/Linux

Which version are you using?  (run 'go version')
go version go1

Please provide any additional information below.

At first, I have ran the above programs under strace and realized that C and Python
versions use buffered stdout, but Go invokes write(2) on every line. I have modified
print.c:
#include &lt;stdio.h&gt;
#include &lt;stdlib.h&gt;
#include &lt;string.h&gt;
#include &lt;unistd.h&gt;

int main(void) {
  for (int i = 0; i &lt; 1 &lt;&lt; 25; i++) {
    char buf[30];
    snprintf(buf, 30, &quot;%d\n&quot;, i);
    write(1, buf, strlen(buf)+1);
  }
}

compiled with:
$ gcc print.c -o print_c -std=c99

$ time ./print_c &gt; /dev/null
real	0m6.184s
user	0m4.104s
sys	0m2.072s

As we can see, this is not the only reason for Go to be so slow. It's not even the main
reason. C is 6x faster if stdout is buffered and 3x faster if non-buffered.

I feel like something can be optimized.</pre>

**Comment by robpike** [comment]
As of 1.4, there is allocation in Fprintln(i) that didn't used to be there. Rerunning:

Go: 11.9s
C: 3.9s

So we're back to 3X. For comparison I changed the Go program to print &i instead of i, so there's no allocation. It went down to 10.2s, still 2.5X.

Overheads still too large.

**Comment by randall77** [comment]
https://github.com/golang/go/issues/8618

I don't think anyone is working on it yet.

**Comment by bradfitz** [comment]
In magic Github syntax, that is #8618 (so the other bug is then associated with this one)

**Comment by martisch** [comment]
benchmarking the c and go program from robpike on my FreeBSD Intel G3220:

```
gcc 4.8.5 -O2: 
real	0m5.796s
user	0m5.796s
sys	0m0.000s

go tip:
real	0m5.147s
user	0m5.228s
sys	0m0.008s
```

which i guess could mean we can close the issue unless others still have radically different numbers.

```
5.01s of 5.07s total (98.82%)
Dropped 24 nodes (cum <= 0.03s)
      flat  flat%   sum%        cum   cum%
     0.75s 14.79% 14.79%      1.15s 22.68%  fmt.(*fmt).fmt_integer
     0.69s 13.61% 28.40%      0.96s 18.93%  runtime.mallocgc
     0.44s  8.68% 37.08%      0.44s  8.68%  runtime.memmove
     0.27s  5.33% 42.41%      0.48s  9.47%  sync.(*Pool).pin
     0.24s  4.73% 47.14%      0.40s  7.89%  fmt.(*fmt).pad
     0.24s  4.73% 51.87%      0.52s 10.26%  sync.(*Pool).Get
     0.22s  4.34% 56.21%      0.34s  6.71%  runtime.typedmemmove
     0.22s  4.34% 60.55%      0.45s  8.88%  sync.(*Pool).Put
     0.17s  3.35% 63.91%      0.69s 13.61%  fmt.newPrinter
     0.16s  3.16% 67.06%      0.45s  8.88%  bytes.(*Buffer).Write
     0.16s  3.16% 70.22%      1.58s 31.16%  fmt.(*pp).printArg
     0.16s  3.16% 73.37%      0.16s  3.16%  sync.runtime_procPin
     0.14s  2.76% 76.13%      0.14s  2.76%  runtime.(*mspan).sweep.func1
     0.13s  2.56% 78.70%      0.13s  2.56%  bytes.(*Buffer).grow
     0.13s  2.56% 81.26%      4.96s 97.83%  main.main
     0.13s  2.56% 83.83%      1.27s 25.05%  runtime.convT2E
     0.12s  2.37% 86.19%      3.47s 68.44%  fmt.Fprintln
     0.11s  2.17% 88.36%      1.26s 24.85%  fmt.(*pp).fmtInteger
     0.09s  1.78% 90.14%      1.67s 32.94%  fmt.(*pp).doPrintln
     0.09s  1.78% 91.91%      0.54s 10.65%  fmt.(*pp).free
     0.06s  1.18% 93.10%      0.20s  3.94%  runtime.heapBitsSweepSpan
     0.05s  0.99% 94.08%      0.09s  1.78%  bytes.(*Buffer).Reset
     0.05s  0.99% 95.07%      0.16s  3.16%  runtime.assertE2T2
     0.04s  0.79% 95.86%      0.04s  0.79%  bytes.(*Buffer).Truncate
     0.04s  0.79% 96.65%         1s 19.72%  runtime.newobject
     0.04s  0.79% 97.44%      0.04s  0.79%  runtime.prefetchnta
     0.04s  0.79% 98.22%      0.04s  0.79%  sync/atomic.LoadPointer
     0.03s  0.59% 98.82%      0.03s  0.59%  sync.runtime_procUnpin
```

**Comment by robpike** [comment]
Wow, nice work everyone!

**Comment by nuss-justin** [comment]
Arch: `amd64`
OS: `Linux 4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux`

On a i7-4720HQ with GCC 5.3.0 and Go 1.6 and Go devel +aa482f9 I get these results for the code in comment 14:

```
gcc -C0
2.34s user 0.00s system 99% cpu 2.345 total

gcc -C1
2.27s user 0.00s system 99% cpu 2.275 total

gcc -C2
2.33s user 0.00s system 99% cpu 2.333 total

gcc -C3
2.33s user 0.00s system 99% cpu 2.331 total

go build (1.6)
5.12s user 0.02s system 103% cpu 4.981 total

go build (devel +aa482f9)
4.76s user 0.02s system 103% cpu 4.634 total
```

So it's still 2x slower for me with Go tip.

CPU Profile for Go tip is:

```
4.40s of 4.45s total (98.88%)
Dropped 22 nodes (cum <= 0.02s)
      flat  flat%   sum%        cum   cum%
     0.57s 12.81% 12.81%      0.79s 17.75%  fmt.(*fmt).fmt_integer
     0.51s 11.46% 24.27%      0.70s 15.73%  runtime.mallocgc
     0.47s 10.56% 34.83%      0.47s 10.56%  runtime.memmove
     0.36s  8.09% 42.92%      0.55s 12.36%  sync.(*Pool).pin
     0.22s  4.94% 47.87%      0.56s 12.58%  bytes.(*Buffer).Write
     0.20s  4.49% 52.36%      0.20s  4.49%  bytes.(*Buffer).grow
     0.18s  4.04% 56.40%      1.44s 32.36%  fmt.(*pp).doPrintln
     0.18s  4.04% 60.45%      0.18s  4.04%  sync.runtime_procPin
     0.17s  3.82% 64.27%      1.26s 28.31%  fmt.(*pp).printArg
     0.17s  3.82% 68.09%      0.41s  9.21%  runtime.typedmemmove
     0.15s  3.37% 71.46%      3.13s 70.34%  fmt.Fprintln
     0.13s  2.92% 74.38%      0.13s  2.92%  bytes.(*Buffer).Truncate
     0.13s  2.92% 77.30%      0.22s  4.94%  fmt.(*fmt).pad
     0.13s  2.92% 80.22%      0.50s 11.24%  fmt.newPrinter
     0.12s  2.70% 82.92%      0.12s  2.70%  runtime.(*mspan).sweep.func1
     0.12s  2.70% 85.62%      0.37s  8.31%  sync.(*Pool).Get
     0.09s  2.02% 87.64%      0.44s  9.89%  sync.(*Pool).Put
     0.08s  1.80% 89.44%      0.23s  5.17%  runtime.assertE2T2
     0.07s  1.57% 91.01%      0.86s 19.33%  fmt.(*pp).fmtInteger
     0.06s  1.35% 92.36%      0.96s 21.57%  runtime.convT2E
     0.06s  1.35% 93.71%      0.18s  4.04%  runtime.heapBitsSweepSpan
     0.06s  1.35% 95.06%      0.76s 17.08%  runtime.newobject
     0.05s  1.12% 96.18%      4.30s 96.63%  main.main
     0.05s  1.12% 97.30%      0.05s  1.12%  sync.runtime_procUnpin
     0.04s   0.9% 98.20%      0.48s 10.79%  fmt.(*pp).free
     0.03s  0.67% 98.88%      0.16s  3.60%  bytes.(*Buffer).Reset
         0     0% 98.88%      0.18s  4.04%  runtime.(*mspan).sweep
         0     0% 98.88%      0.12s  2.70%  runtime.gcBgMarkWorker
         0     0% 98.88%      4.44s 99.78%  runtime.goexit
         0     0% 98.88%      0.18s  4.04%  runtime.gosweepone.func1
         0     0% 98.88%      4.30s 96.63%  runtime.main
         0     0% 98.88%      0.18s  4.04%  runtime.sweepone
         0     0% 98.88%      0.21s  4.72%  runtime.systemstack
```

Graph:
![cpu](https://cloud.githubusercontent.com/assets/6443781/14078544/064216b4-f4f7-11e5-8e6f-68246d7dbe16.png)

**Comment by martisch** [comment]
another data point around 1,25x on OS X macbook pro:

OS X 10.11.4 Intel i7 3520M

Apple LLVM version 7.3.0 (clang-703.0.29) -O2
real	0m4.202s
user	0m4.174s
sys	0m0.014s

gcc-mp-5 (MacPorts gcc5 5.3.0_0) 5.3.0
real	0m4.032s
user	0m4.010s
sys	0m0.012s

go version devel +aa482f9
real	0m5.309s
user	0m5.438s
sys	0m0.036s

**Comment by martisch** [comment]
Same Intel G3220 without GUI on Fedora 23:

gcc (GCC) 5.3.1 20151207 (Red Hat 5.3.1-2) -O2
real	0m2.534s
user	0m2.532s
sys	0m0.002s

go tip version devel +7e88826
real	0m5.039s
user	0m5.124s
sys	0m0.003s

```
readelf -s print_c | grep print
     3: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND sprintf@GLIBC_2.2.5 (2)
    36: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS print.c
    61: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND sprintf@@GLIBC_2.2.5
```

which could mean go is still 2x slower than glibc but not gcc on any platform.

**Comment by robpike** [comment]
So it's still up to 2x slower sometimes. As said a while back, Go has to do a lot more under the covers so this seems understandable.

I say we should leave the bug closed.

**Comment by rsc** [comment]
If someone wants to look into why glibc is so much faster than OS X, it's probably some trick that we could adopt for Go too. But no need to reopen this issue for it.

**Comment by martisch** [comment]
FYI: I had a quick look at glibc source yesterday but did not see anything super special besides avoiding some overhead (i did not profile it). I then optimized fmt_integer to avoid some divisions, special cased printing one argument to avoid the calculation if a space is needed between arguments, special cased printing with the v verb with an extra direct switch and avoided some overhead if width is not present and removed some defensive cleaning of format flags which should be ok after the latest patches. This brought runtime down around 20-25% on my macbook. Avoiding the allocation/interface overhead can bring it down a good chunk further at which point it seems fmt should reach glibc level.

I still plan to submit a last CL for fmt_integer (5-15%) soon. For 1.7 fmt has gone through a lot of change already and in general i am not sure it is worth extending the code with more fast paths just to optimize this micro benchmark.
