### ISSUE TITLE
go 1.13.1 local import under windows is broken

### ISSUE THREAD

**Issue by fantomgs** [golang/go#34643]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.13.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xxx\AppData\Local\go-build
set GOENV=C:\Users\xxx\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Projects
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=c:\temp\go-build495912386=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Just used local import in my project main file like:
import "./my_local_package"
"my_local_package" imports another non-local package

### What did you expect to see?
Expect succefull build

### What did you see instead?
<pre>
unexpected directory layout:
        import path: _/C_/Projects/src/checkerr/my_local_package
        root: C:\Project\src
        dir: C:\Project\src\checkerr\my_local_package
        expand root: C:\Project\src
        expand dir: C:\Project\src\checkerr\my_local_package
        separator: \
</pre>

I made some research. I'm sure it happens here:
https://github.com/golang/go/blob/release-branch.go1.13/src/cmd/go/internal/load/pkg.go#L879

Because function **build.IsLocalImport** checks psedo-import path <pre>"\_/C\_/Projects/src/checkerr/my_local_package"</pre> generated by dirToImportPath instead of <pre>"./my_local_package"</pre>

**Comment by agnivade** [comment]
I think you'll have to use `replace` directives to achieve this. I'll defer to some more knowledgeable folks @bcmills @jayconrod @thepudds.

**Comment by bcmills** [comment]
What was the exact command you invoked to build the program?

**Comment by bcmills** [comment]
Did the same command work with Go 1.12.10?
