### ISSUE TITLE
x/tools/gopls: gopls drops stderr output from GOPACKAGESDRIVER

### ISSUE THREAD

**Issue by jmhodges** [golang/go#34649]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

darwin/amd64

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jeffhodges/Library/Caches/go-build"
GOENV="/Users/jeffhodges/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jeffhodges"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vg/32jn4gdd1x3f_r9dwcryw4y00000gn/T/go-build262498199=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you expect to see?

A way to access the stderr output emitted from the `$GOPACKAGESDRIVER` binary. `gopls` drops any stderr output the driver binary prints and doesn't seem to have a way to log it to another file.

### What did you see instead?

No stderr output from the driver binary.

**Comment by stamblerre** [comment]
I think that if you want read the stderr from your go/packages driver, you will have to handle or log it through the driver. As an example, the built-in `go list` driver explicitly drops stderr [here](https://github.com/golang/tools/blob/7178990c25039b756510e51a36380458e3a96487/go/packages/golist.go#L1108).

**Comment by jmhodges** [comment]
Yeah, I saw that and I was hoping we could, on -v or some such, get stderr copied over (perhaps with a prefix on each line, but not required). The file.Open to log.SetOutput chain is long and means I have to maintain a `tail -f` somewhere.

It’s also something I have to warn anybody else who wants to make changes to the driver code, too.

**Comment by jmhodges** [comment]
I'd be up for writing that patch if y'all are interested!

**Comment by stamblerre** [comment]
@matloob is probably the right person to loop in here, as I think these changes would need to be made in `go/packages`, not `gopls`.

**Comment by matloob** [comment]
I think what we'd want to do here is to maybe log the STDERR if the user specifies a debug environment variable, similar to what we do here: https://github.com/golang/tools/blob/7178990c25039b756510e51a36380458e3a96487/go/packages/golist.go#L1105

**Comment by stamblerre** [comment]
Would it be sufficient to move that check to the beginning of the function?

**Comment by matloob** [comment]
I think we'd have to move it to the code that calls the gopackagesdriver in
go/packages/external.go

**Comment by jmhodges** [comment]
Thank you! This will make my work much easier
