### ISSUE TITLE
cmd/go: doc fails on case-insensitive search for identifier similar to keyword

### ISSUE THREAD

**Issue by DeedleFake** [golang/go#34656]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="$HOME/.cache/go-build"
GOENV="$HOME/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="$HOME/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="$HOME/.go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="$HOME/.go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build199061115=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
$ go doc importer.default
</pre>

### What did you expect to see?

<pre>
package importer // import "go/importer"

func Default() types.Importer
    Default returns an Importer for the compiler that built the running binary.
    If available, the result implements types.ImporterFrom.
</pre>

### What did you see instead?

<pre>
doc: invalid identifier "default"
exit status 1
</pre>

**Comment by andybons** [comment]
@mvdan @robpike

**Comment by robpike** [comment]
This seems more annoying to fix than it's worth, since typing the actual name will work.

**Comment by DeedleFake** [comment]
Makes sense. Maybe instead a line could be inserted in the help to document the behavior.

Alternatively, would you accept a pull request to fix it? I might look into sending one if I have time at some point.

**Comment by mvdan** [comment]
@DeedleFake I think investigating if a simple fix exists would be useful. But if the fix adds a non-trivial amount of complexity, then I'd agree with Rob that it's probably not worth merging.

A CL would be useful either way though, for future reference.

**Comment by cespare** [comment]
This bites me semi-regularly. I never type capital letters into my `go doc` query (why bother?) and so I get annoying failures every time the thing I'm looking for happens to be a keyword.

```
$ go doc sort.interface
doc: invalid identifier "interface"
exit status 1
$ go doc types.type
doc: invalid identifier "type"
exit status 1
```

**Comment by agnivade** [comment]
Reopening for the CL to close it.
