### ISSUE TITLE
net: infinite loop in LookupAddr()

### ISSUE THREAD

**Issue by mndrix** [golang/go#34660]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 openbsd/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mndrix/.cache/go-build"
GOENV="/home/mndrix/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="openbsd"
GONOPROXY=""
GONOSUMDB=""
GOOS="openbsd"
GOPATH="/home/mndrix/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/mndrix/src/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/mndrix/src/go/pkg/tool/openbsd_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/mndrix/src/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
GOROOT/bin/go version: go version go1.13.1 openbsd/amd64
GOROOT/bin/go tool compile -V: compile version go1.13.1
uname -v: GENERIC.MP#1
gdb --version: GNU gdb 6.3
</pre></details>

### What did you do?

```go
package main

import (
	"fmt"
	"net"
)

func main() {
	addr := "104.196.215.101"
	fmt.Printf("looking up %s\n", addr)
	names, err := net.LookupAddr(addr)
	if err != nil {
		panic(err)
	}
	fmt.Printf("%v\n", names)
}
```

### What did you expect to see?

```
looking up 104.196.215.101
[smtp2.shopify.com.]
```

### What did you see instead?

```
looking up 104.196.215.101
```

Hangs with 100% CPU.

**Comment by andybons** [comment]
@bradfitz @mikioh

**Comment by bradfitz** [comment]
@gopherbot, please backport to Go 1.12 and Go 1.13. This looks like a DoS vector.

**Comment by bradfitz** [comment]
@mndrix, I can't reproduce with my DNS server(s). But the bug looks real & fix looks correct.

> The tests I wrote for this issue hard code some shopify.com IP addresses. Is there a better way to test this kind of thing that isn't so fragile?

We have tests that work with in-memory fake servers. See `lookupWithFake` and `fakeDNSServer` in `dnsclient_unix_test.go`.
