### ISSUE TITLE
sort: Strings sort specifies increasing order (not lexicographic)

### ISSUE THREAD

**Issue by JurisMajors** [golang/go#34666]
I believe 'increasing order' can be too ambiguous for official documentation. Since that could be interpreted as increasing in lengths of strings instead.
`Strings sorts a slice of strings in increasing order. `

I propose for it to state `...in lexicographical order` instead.  (e.g. [Oracle Java docs do that](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#compareTo(java.lang.String)))

**Comment by ianlancetaylor** [comment]
As I just noted on the CL, the sort package sorts using the same ordering as the language itself uses.

**Comment by andybons** [comment]
Closing as the discussion on the CL seems to have concluded that we should not change this.
