### ISSUE TITLE
Golang i386 does not start

### ISSUE THREAD

**Issue by szegedim** [golang/go#34668]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12.10
</pre>

### Does this issue reproduce with the latest release?
Yes, with the latest 1.12.10

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
# curl https://dl.google.com/go/go1.12.10.linux-386.tar.gz | tar -xz
# /go/bin/go
-bash: /go/bin/go: cannot execute binary file: Exec format error
  102  history | grep curl
# uname --all
Linux Precision5520-7965 4.4.0-17134-Microsoft #706-Microsoft Mon Apr 01 18:13:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

</pre></details>

### What did you do?

# curl https://dl.google.com/go/go1.12.10.linux-386.tar.gz | tar -xz
# /go/bin/go
-bash: /go/bin/go: cannot execute binary file: Exec format error
  102  history | grep curl
# uname --all
Linux Precision5520-7965 4.4.0-17134-Microsoft #706-Microsoft Mon Apr 01 18:13:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

### What did you expect to see?
No failure

### What did you see instead?
Exec format error

**Comment by ianlancetaylor** [comment]
It looks like you are running a Microsoft version of GNU/Linux?  Have you tried downloading the amd64 version instead?

**Comment by bradfitz** [comment]
Yeah, I imagine the WSL2 kernel doesn't have CONFIG_IA32_EMULATION=y.

**Comment by szegedim** [comment]
Yes, the x64 version works. Thanks!
