### ISSUE TITLE
x/tools/gopls: invalidate snapshot when a new file is added to the package

### ISSUE THREAD

**Issue by stamblerre** [golang/go#34678]
Our metadata cache invalidation strategy relies on us knowing that a file belongs to a given package. If a new file is added to an existing package, we don't invalidate the metadata for the package, since we don't yet know which package the file belongs to. We need to do this invalidation correctly.

/cc @myitcv

**Comment by stamblerre** [comment]
Duplicate of #34678

**Comment by zikaeroh** [comment]
Isn't that this issue?

**Comment by stamblerre** [comment]
Good call. You'd think GitHub would be able to detect that.

**Comment by stamblerre** [comment]
Duplicate of https://github.com/golang/go/issues/34218

**Comment by myitcv** [comment]
@stamblerre just to confirm we're not talking about watched files here, correct? Or are you saying that watched files and new files effectively collapse down to the same underlying problem?

**Comment by stamblerre** [comment]
I think they are ultimately in the same realm, particularly because when you start watching changed files, you get a notification that a file has been created, as well as a `textDocument/didOpen`. I will make sure that it works correctly with watched files both on and off, though.
