### ISSUE TITLE
net: DNS client relies on CNAME order

### ISSUE THREAD

**Issue by iangudger** [golang/go#34677]
According to [RFC 1034, section 3.6](https://tools.ietf.org/html/rfc1034#section-3.6):

> The order of RRs in a set is not significant, and need not be preserved by name servers, resolvers, or other parts of the DNS.

The current DNS client is relying on the RR order in order to determine the CNAME ([source](https://github.com/golang/go/blob/6b85fa80519615ae5fd58154277b47d77e5cf08b/src/net/dnsclient_unix.go#L695-L696)). I think this works because most DNS servers do serve CNAMES in a significant order.

/cc @mdempsky

**Comment by mdempsky** [comment]
That code is grabbing the A/AAAA RRset owner name as a way to short circuit having to walk any CNAME chain. The logic is explained on lines 631–644.

**Comment by iangudger** [comment]
You're right.
