### ISSUE TITLE
text/template: clarify comment and docs for AddParseTree

### ISSUE THREAD

**Issue by greywolve** [golang/go#34695]
There's an incorrect (and misleading) comment [here](https://golang.org/src/text/template/template.go?s=3446:3527#L114):

```
// If the name is the name of this template, overwrite this template.
	nt := t
	if name != t.name {
		nt = t.New(name)
	}
```

It's probably mean't to be "If the name isn't...", but that's still not easy to read, and should potentially just be dropped? (It's fairly obvious what's going on)

The docs could be made more accurate instead:

```
AddParseTree adds parse tree for template with given name and associates it with t.
If the template does not already exist, it will create a new one.
If the template does exist, it will be replaced.
```

Should potentially be:

```
AddParseTree adds parse tree for template with given name and associates it with t.
If the template does not already exist, it will create a new one.
If the template does exist, it will be replaced, unless the given name matches the template's name.
```

**Comment by andybons** [comment]
Seems reasonable. @robpike in case I’m missing something.

**Comment by kumar1202** [comment]
Can I take a look on this ? 
I am starting out with open source.

**Comment by greywolve** [comment]
@kumar1202 already submitted a fix, but thanks for the offer. :)
