### ISSUE TITLE
crypto/rsa: rsa.SignPSS doesn't handle opts as nil as described

### ISSUE THREAD

**Issue by martin-juhlin** [golang/go#34696]
### What version of Go are you using (`go version`)?

Probably 1.13.1

I was browsing source code on https://golang.org and the new web page doesn't display version number.

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?
N/A

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I was reading the source code for cypto/rsa.SignPSS. That text indicate that "opts" may be nil, see description. However the first thing that function is doing is using "opts" as a non-nil value. Later the function indicate that "opts" may be nil as the description is saying. 

Links:
Description:
https://github.com/golang/go/blob/c1e46af62f2893a6beb2341ef71ffe8d3787975b/src/crypto/rsa/pss.go#L247

First usage, assume opts != nil
https://github.com/golang/go/blob/c1e46af62f2893a6beb2341ef71ffe8d3787975b/src/crypto/rsa/pss.go#L250

Later usage, check that opts can be nil
https://github.com/golang/go/blob/c1e46af62f2893a6beb2341ef71ffe8d3787975b/src/crypto/rsa/pss.go#L258

### What did you expect to see?
That SignPSS could handle nil for opts as indicated by the description.

### What did you see instead?
If "opts" is passed in as nil, an runtime exception will be thrown.

**Comment by martin-juhlin** [comment]
rsa.VerifyPSS have the same problem.

**Comment by andybons** [comment]
> If "opts" is passed in as nil, an runtime exception will be thrown.

This is incorrect. You can call functions on nil values: https://play.golang.org/p/89OmxZa5X7d

See https://github.com/golang/go/blob/master/src/crypto/rsa/pss.go#L238-L243
