### ISSUE TITLE
html/template: unexpected behaviour when using "onclick"

### ISSUE THREAD

**Issue by bakurits** [golang/go#34691]
### What did you do?
my template file looks like this
![Screenshot from 2019-10-04 14-44-22](https://user-images.githubusercontent.com/10448754/66201906-849f1d00-e6b5-11e9-9105-64273f870d2c.png)

when i trying to execute it with I get extra symbols around `onclick`
![Screenshot from 2019-10-04 14-45-40](https://user-images.githubusercontent.com/10448754/66201991-c4fe9b00-e6b5-11e9-8491-e4d26c59d390.png)

**Comment by ianlancetaylor** [comment]
Please show us a small self-contained Go program that demonstrates the problem.  Thanks.

**Comment by kevburnsjr** [comment]
@ianlancetaylor https://play.golang.org/p/T1OUlHQ4oVv

**Comment by smasher164** [comment]
I believe this is working as intended. Changing the type of `Name` to `template.JS` resolves this behavior, since it must be explicitly mentioned that the string is a trustworthy JS expression.

**Comment by Laur1nMartins** [comment]
Damn i was having this issue for a week now and just stumbled upon this Thread! Many thanks :)
