### ISSUE TITLE
Problem with slice of interfaces

### ISSUE THREAD

**Issue by massarakhsh** [golang/go#34703]
### What version of Go are you using (`go version`)?

go1.12.7 windows amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

MS Windows 7 Pro, intel core i3

### What did you do?

I move element of slice from one position to other.

func Moving() {
	var data []interface{}
	for nd := 0; nd < 5; nd++ {
		data = append(data, nd)
	}
	fmt.Println(data)
	from := 1
	to := 3
	// Move element of array from position from to to
	// Moving element
	elm := data[from]
	// Extract element from array
	data_crop := append(data[:from], data[from+1:]...)
	fmt.Println(data_crop)
	// Insert element to other position
	data_full := append(data_crop[:to], elm)
	data_full = append(data_full, data_crop[to:]...)
	fmt.Println(data_full)
}

### What did you expect to see?

[0 1 2 3 4]
[0 2 3 4]
[0 2 3 1 4]

### What did you see instead?

[0 1 2 3 4]
[0 2 3 4]
[0 2 3 1 1]

**Comment by ianlancetaylor** [comment]
Slices are references to underlying arrays, not copies.  When you assign to `data_full` in the line `data_full := append(data_crop[:to], elm)` you are also changing `data_crop`.  So that affects the next line when you append `data_crop` to `data_full`.  See https://blog.golang.org/slices.
