### ISSUE TITLE
x/net/http2/h2demo: contains expired certificates

### ISSUE THREAD

**Issue by johha** [golang/go#34729]
Hi, 

the `rootCA.pem` and `server.crt` in net/http2/h2demo/  are expired a long time ago.
Shouldn't they be removed and instead be created by user as instructed in the readme?

**Comment by agnivade** [comment]
@bradfitz @dmitshur

**Comment by dmitshur** [comment]
Seems reasonable to me to delete them. They're not used in prod, only for people wanting to try `h2demo` locally.

As part of removing them, we can improve error handling in `log.Fatal(srv.ListenAndServeTLS("server.crt", "server.key"))` to print a more helpful error message like "A certificate and matching private key not found; see README for instructions to create them." when `xerrors.Is(err, os.ErrNotExist)`.

Brad has more context here so he might have a better suggestion.

**Comment by bradfitz** [comment]
That they're expired doesn't matter much: the developer will have to click through cert warnings regardless. That's just one more reason the browser won't like the cert. That's okay.

I'd rather not delete them until there's an easy way to make the server start up in localhost TLS otherwise.

**Comment by dmitshur** [comment]
I thought there'd be no warnings in browser because the README suggested to "install [root CA] to Firefox". If there are warnings, then the above rationale makes sense.

**Comment by bradfitz** [comment]
I don't remember what that Firefox bit was about. Maybe it only let you do opt-in HTTP/2 back in the day for trusted sites?
