### ISSUE TITLE
net/http/httputil: The ReverseProxy's director cannot communicate failure

### ISSUE THREAD

**Issue by iselind** [golang/go#34733]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.9 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Not related to specific Go release

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/patriki/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/patriki/go"
GOPROXY="direct"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build120897579=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I use a [ReverseProxy](https://golang.org/pkg/net/http/httputil/#ReverseProxy) from the [httputil](https://golang.org/pkg/net/http/httputi) package.

The director field in the reverse proxy struct cannot communicate that the 'rebuilding' of the request failed. Hence, there's no way for the director to stop the request from being transported further.

### What did you expect to see?
The director should be able to return an error or by some other means tell the reverse proxy that it failed making the resulting request broken.

The result of the director failing should probably be something along the lines of HTTP 500/502 error being returned to the client and the request not sent anywhere.

### What did you see instead?
The request gets sent along as if the director succeeded, even if it didn't

**Comment by bradfitz** [comment]
For go1compat reasons, we can't change the signature, so your best bet is probably to supply a custom Transport or just have your own http.Handler/HandlerFunc that validates the request before you delegate to ReverseProxy.ServeHTTP. The ReverseProxy is just another http.Handler which are all composable.

**Comment by iselind** [comment]
Thanks for the guidance, much appreciated.

Isn't this something that could be amended next time the API is broken anyway? In my opinion, this should really be fixed so we don't have to resort to hackish solutions around this forever.

**Comment by kheraud** [comment]
Thanks for the issue, it leads me to this hack

```go
var internalErrorHeader = "X-Routing-Error"

type roundTripperFilter struct {
	parent http.RoundTripper
}

func (rtf *roundTripperFilter) RoundTrip(r *http.Request) (*http.Response, error) {
	if err, ok := r.Header[internalErrorHeader]; ok {
		return nil, errors.New(strings.Join(err, ","))
	}
	return rtf.parent.RoundTrip(r)
}

myProxy := httputil.ReverseProxy{
	Director: handler.escalateAuth,
	Transport: &roundTripperFilter{
		parent: func(r *http.Request) {
			r.Header.Add(internalErrorHeader, "An error occured in ReverseProxy.Director")
		},
	},
}
```
