### ISSUE TITLE
cmd/go: allow passing -U flag in cgo CFLAGS

### ISSUE THREAD

**Issue by nyoxi** [golang/go#34730]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, the version seems to be latest

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/nyoxi/.cache/go-build"
GOENV="/home/nyoxi/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/nyoxi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build294100251=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Include line: `#cgo CFLAGS: -Ufoo_bar` into go source code

### What did you expect to see?
Compilation with `go build` should pass.

### What did you see instead?
`go build` terminates with error: `invalid flag in #cgo CFLAGS: -Ufoo_bar`

**Comment by ianlancetaylor** [comment]
Fix is to cmd/go/internal/work/security.go.  Most likely `-U` should work like `-D`.

**Comment by gregory-m** [comment]
Last time I fixed it for `-I`, will do it for `-U`.
