### ISSUE TITLE
x/build: add macOS Catalina builder (darwin/amd64 only)

### ISSUE THREAD

**Issue by bradfitz** [golang/go#34748]
macOS Catalina is out.

We need a builder. Probably before Go 1.14 comes out.
 
/cc @toothrot @andybons @dmitshur

**Comment by dmitshur** [comment]
Just a 64-bit one, right? macOS Catalina does not support running 32-bit apps.

**Comment by bradfitz** [comment]
Can't test what doesn't exist.

Maybe in a few years we'll even be able to remove the `darwin/386` port. @rsc always liked keeping it around as an easy way to hack on the 386 port on his laptop, but sounds like that reason is going away. We might even be able to remove it earlier, once Russ upgrades his laptop.

Might be worth noting that it's going away soon in the Go 1.14 release notes.

**Comment by bradfitz** [comment]
We continue to hit Catalina bugs (most recently #35247). We need to get this builder up before the release.

/cc @cagedmantis too.

**Comment by cagedmantis** [comment]
I've confirmed with MacStadium that we need to upgrade our version of vSphere in order to run Catalina builders. I'm investigating what the upgrade process would entail.

**Comment by cagedmantis** [comment]
The macOS 10.15 Catalina builder has been added.

**Comment by haithngn** [comment]
@cagedmantis 
unfortunately https://github.com/golang/go/issues/40532 this might happen again

**Comment by cagedmantis** [comment]
@haithngn There was a follow up question on the linked issue.
