### ISSUE TITLE
x/sys/windows: compile error with Go 1.11

### ISSUE THREAD

**Issue by mtolman** [golang/go#34742]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.11.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release? 

<pre>not sure</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\mtolman\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\release-trunk\liveconsole-agent;C:\Users\mtolman\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\mtolman\AppData\Local\Temp\go-build937983166=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

Using x/sys/windows in my project now causes compilation errors when it did not previously.

Here is a sample source file:
<pre>
package main

import (
	"fmt"
	"golang.org/x/sys/windows"
)

var dll windows.DLL

func main() {
	fmt.Println("help")
}
</pre>

This used to compile but no longer does. It fails with these errors:

<pre>
..\golang.org\x\sys\windows\dll_windows.go:21:6: missing function body
..\golang.org\x\sys\windows\dll_windows.go:24:6: missing function body
</pre>

The issue looks to be caused by this merge:

https://go.googlesource.com/sys/+/ef33b2fb2c414dca4bfcf6ca59cbd1d9ad00703d

**Comment by zx2c4** [comment]
Does the issue disappear with Go 1.12 or 1.13?

@bradfitz Is 1.11 still supported?

**Comment by bradfitz** [comment]
No, it isn't.

For certain low-level or important packages, though, we try not to unnecessarily break old users. At least in some sort of best effort untested fashion, which is kinda lame. I think we should be definitive about saying "no, we don't support that" or actually make it tested.

But the current situation is somewhere in between: we don't test Go 1.11 at all, but at the same time this kinda sucks, breaking Go 1.11 users for something like this.

So maybe it's time to just say that Go 1.11 users should use an older version of this package, or something on the Go 1.11 branch (release-branch.go1.11).

**Comment by mtolman** [comment]
1.12.1 and 1.13.1 are working for me. I guess now is a good time to upgrade :) Thanks!

**Comment by bradfitz** [comment]
Okay, we'll close this then. Sorry about that.

**Comment by Shagrat2** [comment]
Bat win32 XP work only with golang 1.11

**Comment by zx2c4** [comment]
Windows XP has been unsupported by Microsoft for over 5 years.

**Comment by trinhhunganh** [comment]
@bradfitz 
I am using go1.9.3 windows/amd64 and get the same 
golang.org\x\sys\windows\dll_windows.go:21:6: missing function body
golang.org\x\sys\windows\dll_windows.go:24:6: missing function body

Do I have to upgrade go to newer version or is there a workaround?
Thank you and sorry to comment on a closed issue.
