### ISSUE TITLE
Detected a bug while using Print function in fmt package

### ISSUE THREAD

**Issue by jainthedestroyer** [golang/go#34740]
### What version of Go are you using (`go version`)?

<pre>
$ go version = go version go1.12.9 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
I think so yes....

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Jaina\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Jaina\go
set GOPROXY=
set GORACE=
set GOROOT=c:\go
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Jaina\AppData\Local\Temp\go-build778068474=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

`fmt.Print(temp.data, ' ')`
here temp.data in an int value...

### What did you expect to see?
let temp.data is 10
I see 3210

### What did you see instead?
Expected output is "10 " ( except "" ) not 3210...

**Comment by bradfitz** [comment]
This is working correctly.

See https://blog.golang.org/constants.

Your `' '` is a number, not a string.
