### ISSUE TITLE
strings: strings.Builder case memory leak

### ISSUE THREAD

**Issue by szyhf** [golang/go#34754]
### What version of Go are you using (`go version`)?

```
go version go1.13.1 darwin/amd64
```

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/foo/go/bin"
GOCACHE="/Users/foo/Library/Caches/go-build"
GOENV="/Users/foo/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/foo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xq/b3m9nkcx6jlgmnsvyz8w_05r0000gn/T/go-build019996190=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

I made an issue #34463 but there some mistake, then I make a simple demo to record the `HeapInuse` and its increasing too.

[DemoCodeOfGoPlay](https://play.golang.org/p/VgYfVxU3bdl)

### What did you expect to see?

Memory keep stable.

### What did you see instead?

Memory increasing slowly.

![image](https://user-images.githubusercontent.com/14870120/66362686-499f3100-e9b6-11e9-8af9-72eb7acd5bfd.png)

**Comment by egonelbre** [comment]
Each iteration the `pfx` is getting bigger hence you are always allocating a slightly bigger string.

See the code here https://play.golang.org/p/rZrJrrrgL4F

**Comment by szyhf** [comment]
> Each iteration the `pfx` is getting bigger hence you are always allocating a slightly bigger string.
> 
> See the code here https://play.golang.org/p/rZrJrrrgL4F

Oh……you are right ! I made another mistake.

Can you help me to see why the memory is leak in  #34463 and the core code is in (https://play.golang.org/p/o0cEeZ7o7xl)[https://play.golang.org/p/o0cEeZ7o7xl]

I made a mistake in demo, is not the same as the running one, the leak really confused me.

Tanks a lot

**Comment by egonelbre** [comment]
GitHub issues should be used for tracking bugs and proposals only. If you wish for help with debugging move the discussion to a more appropriate place.

* https://github.com/golang/go/wiki/Questions
* https://github.com/golang/go/wiki#the-go-community.

**Comment by szyhf** [comment]
@egonelbre 
Oh no, I really think there is some leaking there, but I'm can not reproduce it in a simple code. My production environment is leaking every day.

I have another try latter.

**Comment by egonelbre** [comment]
@szyhf indeed there could be a leak, but it could be in many places. It could be in the code you posted, it could be in any of the third-party libraries (bingo, ormer, database driver), some other code. Indeed it could be in Go runtime as well, but it is unlikely.

The goal is to isolate the leak - such that it clearly demonstrates where the leak is. Community sites are much better for this rather than Go language issues.

**Comment by szyhf** [comment]
@egonelbre Thanks, I'll try to reproduce it in a clear way

**Comment by szyhf** [comment]
BTW, The reason why I think there is a leak of `strings.Builder` is due to the pprof of heap shows that the Builder.WriteString() hold a lots.
