### ISSUE TITLE
go/build: reduce redundancy in error messages from Import in module mode

### ISSUE THREAD

**Issue by jayconrod** [golang/go#34752]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +a0894ea5b5 Mon Oct 7 18:50:14 2019 +0000 darwin/amd64</pre>
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jayconrod/Library/Caches/go-build"
GOENV="/Users/jayconrod/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jayconrod/go"
GOPRIVATE=""
GOPROXY="off"
GOROOT="/Users/jayconrod/Code/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/jayconrod/Code/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jayconrod/Code/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rq/x0692kqj6ml8cvrhcqh5bswc008xj1/T/go-build844872233=/tmp/go-build -gno-record-gcc-switches -fno-common"</pre></details>

### What did you do?

```
$ go mod init m
$ cat >hello.go <<EOF
package main

import (
	"fmt"
	"go/build"
	"os"
)

func main() {
	os.Setenv("GOPROXY", "off")
	_, err := build.Import("example.com/hello", ".", build.FindOnly)
	fmt.Println(err)
}
EOF
$ go run hello.go
```

### What did you expect to see?

```
cannot find module providing package example.com/hello: module lookup disabled by GOPROXY=off
```

### What did you see instead?

Package name is repeated three times, and some irrelevant implementation details are exposed.

```
go/build: importGo example.com/hello: exit status 1
can't load package: package example.com/hello: cannot find module providing package example.com/hello: module lookup disabled by GOPROXY=off


```

**Comment by bcmills** [comment]
I wrote up a related [experience report](https://github.com/bcmills/go-experience-reports/blob/master/errors.md) on the general strategy for reducing redundancy. That strategy seemed to work out pretty well for the error messages we tried last cycle.
