### ISSUE TITLE
gomobile doesn't support go1.13

### ISSUE THREAD

**Issue by orange-jacky** [golang/go#34759]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yess

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN="/Users/fredlee/Documents/develop/go/workspace/bin"
GOCACHE="/Users/fredlee/Library/Caches/go-build"
GOENV="/Users/fredlee/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/fredlee/Documents/develop/go/workspace"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/34/z2z_vp1573g5014m8k7wys100000gn/T/go-build483921249=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.13 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.13
uname -v: Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.14.1
BuildVersion:	18B75
lldb --version: lldb-1000.0.38.2
  Swift-4.2
</pre></details>

### What did you do?

/Users/fredlee/Documents/develop/go/workspace/src/app.sdk/lightControl
macbookpro:lightControl fredlee$ gomobile bind -o lightControl.aar -target=android app.sdk/lightControl
gomobile: /Users/fredlee/Documents/develop/go/workspace/bin/gobind -lang=go,java -outdir=/var/folders/34/z2z_vp1573g5014m8k7wys100000gn/T/gomobile-work-981232532 app.sdk/lightControl failed: exit status 1
type-checking package "app.sdk/lightControl" failed (/Users/fredlee/Documents/develop/go/workspace/src/app.sdk/lightControl/addr.go:4:2: could not import bytes (type-checking package "bytes" failed (/usr/local/go/src/bytes/buffer.go:12:2: could not import unicode/utf8 (/usr/local/go/src/unicode/utf8/utf8.go:28:8: expected ';', found b00000000 (and 10 more errors)))))

### What did you expect to see?

gomobile bind -o lightControl.aar -target=android app.sdk/lightControl 
it success

**Comment by agnivade** [comment]
It looks like you 1.13 installation is somehow messed up. Did this start immediately after upgrading to 1.13 ? Can you run other programs using 1.13 ?

**Comment by orange-jacky** [comment]
yes, i run gomobile after upgrading to 1.13,  and i can run my other go code using 1.13 without wrong info, only runing gomobile it failed.

**Comment by eliasnaur** [comment]
Please try `go install golang.org/x/mobile/cmd/...` to rebuild the gomobile (and gobind) tool.

**Comment by orange-jacky** [comment]
thanks, i rebuild the gomobile (and gobind) tool, it workssss

**Comment by ianlancetaylor** [comment]
Thanks for following up.
