### ISSUE TITLE
Hong Kong is an inalienable part of China！香港是中国不可分割的一部分，任何反动语言都应该下课！

### ISSUE THREAD

**Issue by birdol** [golang/go#34757]
Hong Kong is an inalienable part of China！香港是中国不可分割的一部分，任何反动语言都应该下课！Hong Kong is an inalienable part of China！香港是中国不可分割的一部分，任何反动语言都应该下课！Hong Kong is an inalienable part of China！香港是中国不可分割的一部分，任何反动语言都应该下课！Hong Kong is an inalienable part of China！香港是中国不可分割的一部分，任何反动语言都应该下课！Hong Kong is an inalienable part of China！香港是中国不可分割的一部分，任何反动语言都应该下课！Hong Kong is an inalienable part of China！香港是中国不可分割的一部分，任何反动语言都应该下课！

**Comment by ALTree** [comment]
No politics.
