### ISSUE TITLE
@bradfitz your mother died

### ISSUE THREAD

**Issue by ChinaHDJ** [golang/go#34763]
### What version of Go are you using (`go version`)?

<pre>
$ go version1.13

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?
@bradfitz fuck you

**Comment by ChinaHDJ** [comment]
NMSL

**Comment by nervouna** [comment]
Yes yes we know you love your country with a passion, but random shitposting is not helping. Express your political opinions elsewhere like facebook or twitter would be better.
