### ISSUE TITLE
作为一个中国人，要求golang开发团队，遵守一个中国原则！！！

### ISSUE THREAD

**Issue by xuecai** [golang/go#34766]
**强烈谴责Brad Fitzpatrick 支持港独的言论！
请golang开发团队的每个人，遵守一个中国原则！**

![image](https://user-images.githubusercontent.com/3841450/66391912-f4d4d800-ea00-11e9-839b-efe51e4d38fa.png)

**强烈谴责Brad Fitzpatrick 支持港独的言论！
请golang开发团队的每个人，遵守一个中国原则！**

**Comment by yomunsam** [comment]
抵制啊
