### ISSUE TITLE
context: WithCancel should return a cancel function which can accept an error

### ISSUE THREAD

**Issue by fanfuxiaoran** [golang/go#34764]
Sometimes, we run multiple go routines in a context, if one go routine fails due to an error, we 
 want to cancel the context and record the error in it.  Such as a task has several workers, each worker works independently, if a worker fails , the task is supposed to fail and report the cause.
I want to cancel the context if a worker fails due to an error, and record the error in the context.
However, the CancelFunc returned by WithCancel can not accept an error.  I think a new type of 
cancel function is needed which user can pass an error into it and can be returned by WithCancel.

**Comment by mvdan** [comment]
WithCancel can't be changed without breaking backwards compatibility. Likewise, we can't change CancelFunc. What exactly are you proposing?

**Comment by fanfuxiaoran** [comment]
ref: https://github.com/golang/go/pull/34761

**Comment by bcmills** [comment]
> Such as a task has several workers, each worker works independently, if a worker fails , the task is supposed to fail and report the cause.

That is exactly what an [`errgroup.Group`](https://godoc.org/golang.org/x/sync/errgroup#Group) does. There is typically no need to inject the error back into the controlling `Context`: the `Context` is an _input_ to the tasks, but the `error` is an _output_.

**Comment by fanfuxiaoran** [comment]
> > Such as a task has several workers, each worker works independently, if a worker fails , the task is supposed to fail and report the cause.
> 
> That is exactly what an [`errgroup.Group`](https://godoc.org/golang.org/x/sync/errgroup#Group) does. There is typically no need to inject the error back into the controlling `Context`: the `Context` is an _input_ to the tasks, but the `error` is an _output_.

Great! Thanks for your help.

**Comment by ianlancetaylor** [comment]
Is there anything else to do for this issue?
