### ISSUE TITLE
Hong Kong is an inalienable part of China！

### ISSUE THREAD

**Issue by bovenn** [golang/go#34760]
Hong Kong is an inalienable part of China！ 不要跟老子BB ！！！

**Comment by yundmb** [comment]
Hong Kong is an inalienable part of China！

**Comment by acBool** [comment]
Hong Kong is an inalienable part of China！

**Comment by wwhu668** [comment]
Hong Kong is an inalienable part of China！

**Comment by tianhanfangyan** [comment]
Hong Kong is an inalienable part of China！我不要你觉得，我要我觉得。

**Comment by acBool** [comment]
Hong Kong is an inalienable part of China！ 不要跟老子BB ！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by bovenn** [comment]
Hong Kong is an inalienable part of China！

**Comment by GHYOWEE** [comment]
HK is an inalienable part of china!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by GHYOWEE** [comment]
No Zuo No Die

**Comment by gadekuoen** [comment]
Hong Kong is an inalienable part of China!

**Comment by HarrisZeng0631** [comment]
Hong Kong is an inalienable part of China！ 不要跟老子BB ！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by kallydev** [comment]
请共同维护开源社区氛围，不要在这里发布与项目无关的政治言论。

Please jointly maintain the atmosphere of the open source community, do not post political content unrelated to the project here.
