### ISSUE TITLE
golang NMSL

### ISSUE THREAD

**Issue by 156631890** [golang/go#34762]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by agnivade** [comment]
Empty issue. Closing.

**Comment by ChinaHDJ** [comment]
+1 @bradfitz 裂妈废物
