### ISSUE TITLE
runtime: js-wasm builder broken due to timeout

### ISSUE THREAD

**Issue by katiehockman** [golang/go#34768]
The js-wasm builder is consistently failing after https://go-review.googlesource.com/c/go/+/199537 was merged. It's unclear exactly what exactly is going wrong from the test output, but this seems suspicious:

```
##### ../test/bench/go1

##### ../test

##### 
Test "test:4_10" ran over 20m0s limit (20m0.001274792s)
```

https://build.golang.org/log/0ebc31b62df29629efb94fc41ea07895f0b346bd

/cc @aclements @cherrymui @neelance

**Comment by neelance** [comment]
It hangs here:
https://github.com/golang/go/blob/ed7e43085ef2e2c6a1d62785b2d2b343a80039bc/test/goprint.go#L18-L20

The additional goroutine that handles async events now also counts for `NumGoroutine`, so it never becomes `1`.

@aclements @cherrymui I am not sure how to solve this the cleanest way. Do we need to adapt the test? Should the additional goroutine not count for `NumGoroutine`? Or should it not count as a user goroutine at all as defined by `isSystemGoroutine`?

**Comment by cherrymui** [comment]
In my opinion `runtime.NumGoroutine` should probably include the callback goroutine, as it is mostly running user code instead of runtime code. Then we should adjust the test. Unless there are a lot of code depending on the old behavior?

**Comment by cherrymui** [comment]
Related: could we start the callback goroutine lazily? Maybe at the first time a JS callback is created?

**Comment by bcmills** [comment]
If the fix for this test isn't trivial enough to apply right away, CL 199537 should be rolled back so that it does not mask other regressions on the builder. (We can roll it forward again when the fix for the test is ready.)

**Comment by neelance** [comment]
I'll have a fix ready by tomorrow. :)

**Comment by neelance** [comment]
@bradfitz Do you want to keep https://golang.org/cl/200438 ?

**Comment by bradfitz** [comment]
@neelance, yeah, it's harmless. And I like that it has a deadline now, rather than looping forever. Let's just keep it. There's nothing really wasm-specific in there.

**Comment by neelance** [comment]
All right.
