### ISSUE TITLE
database/sql: change default SQL connection lifetime to shorter value

### ISSUE THREAD

**Issue by mcandre** [golang/go#34777]
The default SQL connection lifetime appears to be zero value, with the result that connections often break from (My)SQL server side default configurations of 8 hours.

Can Go change the default connection lifetime to a lesser value, such as 6 hours or 4 hours, in order to integrate better with typical SQL servers with regular batch, idle query patterns?

https://golang.org/src/database/sql/sql.go

**Comment by ianlancetaylor** [comment]
CC @kardianos

**Comment by kardianos** [comment]
No.

Having any connection lifetime to me is... questionable at best. If you need a shorter lifetime, please set the DB pool options.
