### ISSUE TITLE
Ambiguity in time.Duration manipulation

### ISSUE THREAD

**Issue by mcandre** [golang/go#34787]
`time.Duration` currently requires non-constant, non-literal multiplication with factors, such as hours x 3, minutes x 10, to be performed with explicit casting of the factor with `time.Duration(factor)`. However, this casting can result in surprising duration products, when the programmer forgets to include the unit multiplier.

Should we therefore allow implicit casting of non-duration factors, as well as deprecate casting real values without units to durations?

**Comment by mvdan** [comment]
What exactly are you proposing? A change to the language, a change to the time package, or something else? Please clarify with examples.
