### ISSUE TITLE
Panic "len out of range" when make slice with size of 5263531936693774911

### ISSUE THREAD

**Issue by wangdayong228** [golang/go#34782]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13.1
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/dayong/Library/Caches/go-build"
GOENV="/Users/dayong/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/dayong/.gvm/pkgsets/go1.13.1/global"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/Users/dayong/.gvm/gos/go1.13.1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/dayong/.gvm/gos/go1.13.1/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5s/8wnwms_d1mn7zt6jnhgy40j80000gn/T/go-build465389192=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Test Code
```
package test

func TestMake_Size(t *testing.T) {
	_ = make([]byte, 5263531936693774911)
}
```
Run this test function, is failed
```
Running tool: /Users/dayong/.gvm/gos/go1.13.1/bin/go test -timeout 30s ipfs_test/uint_test -run ^(TestMake_Size)$

--- FAIL: TestMake_Size (0.00s)
panic: runtime error: makeslice: len out of range [recovered]
	panic: runtime error: makeslice: len out of range

goroutine 6 [running]:
testing.tRunner.func1(0xc000172100)
	/Users/dayong/.gvm/gos/go1.13.1/src/testing/testing.go:874 +0x3a3
panic(0x1459c80, 0x167c760)
	/Users/dayong/.gvm/gos/go1.13.1/src/runtime/panic.go:679 +0x1b2
ipfs_test/uint_test.TestMake_Size(0xc000172100)
	/Users/dayong/Myspace/mywork/ipfs-fuzz/uint_test/ipns_test.go:31 +0x41
testing.tRunner(0xc000172100, 0x160dad8)
	/Users/dayong/.gvm/gos/go1.13.1/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/Users/dayong/.gvm/gos/go1.13.1/src/testing/testing.go:960 +0x350
FAIL	ipfs_test/uint_test	0.034s
FAIL
Error: Tests failed.
```
### What did you expect to see?

I expect it pass, because the make function support all int value, in my os, the int range is -2^63~2^63, and my make slice size if small than 2^63 

### What did you see instead?
panic: runtime error: makeslice: len out of range [recovered]

**Comment by beoran** [comment]
The byte array would take a space of 4787154 TB. At the time I am writing this, there is no computer that supports such an amount of RAM. I guess Go just blocks such make statements since they cannot succeed anyway.

**Comment by randall77** [comment]
The max amount Go can allocate is 2^48 (on darwin/amd64, at least).
Get a C program to work with that much memory, and then reopen this issue and we'll raise the limit.
