### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by JieshuaiCui** [golang/go#34785]
src_ls222:=[]byte{64 ,58, 69, 95, 87 ,65 ,83, 40,}//if the byte is decoded by ascii85.Decoder()，it is ok! But if the byte is Decoded by ascii85.NewDecoder(),
//it will make a mistake!if i make the byte to be []byte{64 ,58, 69, 95, 87 ,65 ,83, 40,,111 ,66},is is ok! But i want the ascii85.NewDecoder() to be like the ascii85.Decoder() .
reader := bytes.NewBuffer(src_ls222)
newDecoder_reader := ascii85.NewDecoder(reader)
newDecoder_reader.read()....
That is all! Thank you!
for the current news,you and all the world are not Familiar with the Hong Kong and China,so as your project go,everything is not awalys right,do you ever come to the China or China's Hong Kong? do you know
your country's current news are always make china black? so i don't want to condemn you,because all the world knows the China very little! so if you have a chance to visit the China or China's Hong Kong,i think ,
you may be change your mind!
thank you for your reading!I am only a chinese!but i am Familiar with my country,and you don't!

**Comment by ALTree** [comment]
The Github issue tracker is *exclusively* for Go bugs. Politics is not allowed. Not even when disguised as a legitimate bug report. If you actually want to report an issue with Go, please open a new issue with no politics in it. Closing here.
