### ISSUE TITLE
all: either enforce prefix for non-master branches with automation, or remove the requirement

### ISSUE THREAD

**Issue by dmitshur** [golang/go#34793]
The process for making changes to branches other than `master` is described at https://golang.org/wiki/MinorReleases#making-cherry-pick-cls. It requires adding a "[branch-name]" prefix to the commit message. However, it doesn't describe the motivation for doing so. I've asked around and so far no one knows.

We should find out why the convention exists and document the rationale for it (so that when time passes and people forget why we're doing it, it's possible to look it up and confirm the reason is still applicable).

If it turns out the reason for doing so is still valid, we should improve tooling to catch cherry-pick CLs that have the wrong prefix.

If it turns out there is no reason to add the prefix anymore, we should change the cherry-pick process to remove that requirement.

/cc @golang/osp-team

Possibly related issue #13202.

**Comment by FiloSottile** [comment]
I am mildly in favor of keeping the prefix. It makes CLs easily distinguishable from their cherry-picks, for example. We should definitely have a bot check.

**Comment by bradfitz** [comment]
Russ is in favor of keeping them too. (Just discussed in unrelated meeting)

Once we have #18548 this is another easy check to add to that.

**Comment by katiehockman** [comment]
Can we have Gerrit auto-fill that prefix when we use the UI to create the cherry pick?

**Comment by dmitshur** [comment]
I think we've decided we want to keep this, and so it should be automated.

I'll close this in favor of #41722 which is about implementing the automated check for mismatch.
