### ISSUE TITLE
runtime: TestSelectFairness flake on linux-386 builder

### ISSUE THREAD

**Issue by cuonglm** [golang/go#34808]
Build log https://storage.googleapis.com/go-build-log/83e0a3af/linux-386_d22ef102.log

```
--- FAIL: TestSelectFairness (0.01s)
    chan_test.go:486: 4770 5230 0.477 0.02300000000000002
    chan_test.go:488: unfair select: in 10000 trials, results were 4770, 5230
FAIL
FAIL	runtime	23.698s
FAIL
2019/10/10 03:35:41 Failed: exit status 1
```

Got this when testing CL https://go-review.googlesource.com/c/go/+/200237

**Comment by bcmills** [comment]
CC @randall77 @aclements

**Comment by randall77** [comment]
We *just* crossed the threshold, the error is 0.023 and the reporting threshold is 0.022086.
We could probably turn down this test a bit - it assumes perfect random numbers and fastrand isn't quite that.
@rasky
