### ISSUE TITLE
cmd/compile: access to negative slice indices improperly permitted

### ISSUE THREAD

**Issue by AaronReboot** [golang/go#34802]
### What version of Go are you using (`go version`)?
go version go1.13.1 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/aaron/Library/Caches/go-build"
GOENV="/Users/aaron/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/aaron/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n0/33wyl5yn1x77xsgjmz3p53zw0000gn/T/go-build007240201=/tmp/go-build -gno-record-gcc-switches -fno-common"
### What did you do?

Accessed a negative slice index. Example: https://play.golang.org/p/Abpv3H1sgol

### What did you expect to see?

Expected to see error

### What did you see instead?

No error

**Comment by mvdan** [comment]
Interesting. This succeeds on 1.13.1 and master, but fails on 1.12.9. Sounds like a regression somewhere. Perhaps because of the recent improvements to the prove pass?

/cc @randall77 @rasky @zdjones

**Comment by marigonzes** [comment]
Bisected to ddef157

**Comment by networkimprov** [comment]
Don't the trybots test for this?

**Comment by ianlancetaylor** [comment]
@gopherbot Please open a backport to 1.13.

If this is indeed a compiler bug present in 1.13, we should backport it.

**Comment by bradfitz** [comment]
> Don't the trybots test for this?

Trybots only run tests that exist.

**Comment by networkimprov** [comment]
There's no tests for bounds-checking? o.o
Was this corrupting memory?

Should we open an issue re adding tests for language features which can panic?

**Comment by randall77** [comment]
There are tests that check that negative indexes panic. Those tests just don't cover this case (induction variable which starts at a negative value).

**Comment by networkimprov** [comment]
@randall77 could a negative index corrupt memory in this case?

**Comment by zdjones** [comment]
I'll look into this in detail tomorrow.

**Comment by ericlagergren** [comment]
@networkimprov yes, it can overwrite values on the stack.

**Comment by zdjones** [comment]
Found the issue, mailing the fix shortly.
