### ISSUE TITLE
net/http/httputil: ReverseProxy produces the error context canceled on high load

### ISSUE THREAD

**Issue by Refuel-ZL** [golang/go#34813]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.1 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/zl/Desktop/mywork/GO/test01/bin"
GOCACHE="/home/zl/.cache/go-build"
GOENV="/home/zl/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/zl/Desktop/mywork/GO/test01"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/home/zl/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/zl/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build605714083=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```
func proxy(proxy *httputil.ReverseProxy, c *gin.Context) {
	logger := log.New(os.Stderr, "", log.LstdFlags|log.Llongfile)
	proxy.ErrorLog = logger
	proxy.ErrorHandler = func(writer http.ResponseWriter, request *http.Request, e error) {
		logger.Printf("%v %v\n", request.URL.Path, e.Error()) --> context canceled
	}
	proxy.Transport = &http.Transport{
		DialContext: (&net.Dialer{
			Timeout:       90 * time.Second,
			KeepAlive:     90 * time.Second,
			FallbackDelay: -1 * time.Second,
		}).DialContext,
		ForceAttemptHTTP2:     false,
		MaxIdleConns:          100,
		IdleConnTimeout:       1 * time.Second,
		TLSHandshakeTimeout:   10 * time.Second,
		ExpectContinueTimeout: 1 * time.Second,
	}
	proxy.ServeHTTP(c.Writer, c.Request)
}
```

### What did you see instead?
High concurrency exception：
logger.Printf("%v %v\n", request.URL.Path, e.Error()) --> context canceled

**Comment by Refuel-ZL** [comment]
2w QPS  touch off “context canceled”

**Comment by odeke-em** [comment]
@Refuel-ZL thank you for filing this issue and welcome to the Go project!

>2w QPS touch off “context canceled”

What does that "2w" "touch off" mean? Could you please be more specific and also it would be nice if you could try to simulate/reproduce this issue for example using http://github.com/rakyll/hey or Apache bench or whichever load generator you'd like? Thank you!

**Comment by mvdan** [comment]
Closing old issues that still have the WaitingForInfo label where enough details to investigate weren't provided. Feel free to leave a comment with more details and we can reopen.
