### ISSUE TITLE
cmd/go: hang in 'go get golang.org/x/tools/cmd/godoc' in GOPATH mode

### ISSUE THREAD

**Issue by deepnum** [golang/go#34821]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13
</pre>

### Does this issue reproduce with the latest release?
..

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tanvir/.cache/go-build"
GOENV="/home/tanvir/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tanvir/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build911798959=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
```
go get golang.org/x/tools/cmd/godoc
```
it does not do any thing. 

### What did you expect to see?
install godoc

### What did you see instead?
a blank cursor on ternmnal and it hang, doesn't stop

**Comment by deepnum** [comment]
it only create the directory but don't download the code

**Comment by bcmills** [comment]
Could be a connectivity issue to `proxy.golang.org`.

What happens if you run `curl -sL https://proxy.golang.org/golang.org/x/tools/@latest`?

**Comment by bcmills** [comment]
For `go` command hangs, please provide the following additional information:

* Run the `pstree` command with the PID of the `go` process as its argument.
* Run `kill -QUIT` on the `go` process.

Post the results of both in a `<details>[…]</details>` block.

**Comment by deepnum** [comment]
```
$ ps
  PID TTY          TIME CMD
16471 pts/0    00:00:00 bash
16515 pts/0    00:00:00 lf
16570 pts/0    00:00:00 go
16584 pts/0    00:00:00 git
16585 pts/0    00:00:00 git-remote-http
16675 pts/0    00:00:00 ps
$ pstree 16570
go─┬─git───git-remote-http
   └─11*[{go}]

$ kill -QUIT 16570 
$ 


```

**Comment by deepnum** [comment]
```
$ curl -sL https://proxy.golang.org/golang.org/x/tools/@latest?
{"Version":"v0.0.0-20191010075000-0337d82405ff","Time":"2019-10-10T07:50:00Z"}
```

**Comment by bcmills** [comment]
Oh, wait, here's the other important clue! From `go env`:
```
GOMOD=""
```

That implies that you are fetching in GOPATH mode, not module mode.

So this looks like:
1. For some reason you have a connectivity issue to `https://golang.org` but not to `https://proxy.golang.org`.
2. Because your `go get` command is running in `GOPATH` mode, it is not using the proxy.

If you just want to install the `godoc` tool (and not clone its repo into `GOPATH/src`), the simple workaround is to enable module mode explicitly:

```
$ GO111MODULE=on go get golang.org/x/tools/cmd/godoc
```

**Comment by deepnum** [comment]
it works
