### ISSUE TITLE
crypto/aes: expandKeyGo inconsistent with expandKeyAsm in endiannes

### ISSUE THREAD

**Issue by xujintao** [golang/go#34823]
```
$ go version
go version go1.12 linux/amd64
```
### What did you do?
0, given key: 
```
var key = [32]byte{0x12, 0x34, 0x56, 0x78}
```
1, cpu does not support AES, select expandKey with BigEndian, enc[0] is 0x12345678
```
func expandKeyGo(key []byte, enc, dec []uint32) {
	// Encryption key setup.
	var i int
	nk := len(key) / 4
	for i = 0; i < nk; i++ {
		enc[i] = binary.BigEndian.Uint32(key[4*i:])
	}
...
```
2, cpu supports AES, use expandKeyAsm and movups, enc[0] is 0x78563412 on x86
```
// func expandKeyAsm(nr int, key *byte, enc, dec *uint32) {
// Note that round keys are stored in uint128 format, not uint32
TEXT ·expandKeyAsm(SB),NOSPLIT,$0
	MOVQ nr+0(FP), CX
	MOVQ key+8(FP), AX
	MOVQ enc+16(FP), BX
	MOVQ dec+24(FP), DX
	MOVUPS (AX), X0
	// enc
	MOVUPS X0, (BX)
	ADDQ $16, BX
	PXOR X4, X4 // _expand_key_* expect X4 to be zero
	CMPL CX, $12
	JE Lexp_enc196
	JB Lexp_enc128
Lexp_enc256:
...
```
### What did you expect to see?
consistency
### What did you see instead?
not consistency

**Comment by andybons** [comment]
Is this a user-visible problem or a code quality issue? If it's the former can you provide a repro that shows code breaking due to this behavior?

@FiloSottile

**Comment by xujintao** [comment]
Sorry, i'm wrong.
All the operation is bitwise opration, shift or xor. So endian makes no sense here.
Please close.

**Comment by ianlancetaylor** [comment]
Thanks for following up.
