### ISSUE TITLE
archive/tar: Writer produces bad tar files on Windows

### ISSUE THREAD

**Issue by DeedleFake** [golang/go#34839]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=$HOME\AppData\Local\go-build
set GOENV=$APPDATA\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=$HOME\Devel\Go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=$HOME\scoop\apps\go\current
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=$HOME\scoop\apps\go\current\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=$TEMP\tmp.a13440\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=$TEMP\go-build061456054=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

https://play.golang.org/p/dmkEunM6jGX

Running this on Linux or Darwin produces a tar file containing two files, `Test` and `Other`, as expected. Running this on Windows, however, produces a file which the `file` command identifies as `data`, not a tar file, and running any tar command against it results in errors. Running `tar -t` with the GNU `tar` command yields

<pre>
tar: This does not look like a tar archive
tar: Skipping to next header
tar: A lone zero block at 4
tar: Exiting with failure status due to previous errors
</pre>

while bsdtar, which the `tar.exe` that comes with Windows is a port of, yields

<pre>
tar : tar.exe: Error opening archive: Unrecognized archive format
</pre>

**Comment by ianlancetaylor** [comment]
CC @dsnet

**Comment by mattn** [comment]
I confirmed generated files on Linux/Windows are both same. The problem is that the generated tar file seems not friendly for Windows. Using tar.exe bundled in msys2/mingw

![image](https://user-images.githubusercontent.com/10111/66625160-1c5cb800-ec2e-11e9-9350-95e0d07615ab.png)

Using bsdtar.exe bundled in msys2/mingw

![image](https://user-images.githubusercontent.com/10111/66625184-37c7c300-ec2e-11e9-9301-90505f4af045.png)

**Comment by DeedleFake** [comment]
The same GNU tar installation on the same Linux that could read the ones produced on Linux for be was unable to read the files produced on Windows.

I haven't done a binary comparison between the two. Since `file` reports different things than I just assumed it was different. I'll try that when I get a chance.

**Comment by DeedleFake** [comment]
It was different, but...

False alarm. Sorry about that. It looks like this is a problem with PowerShell. The `|` and `>` operators appear to be corrupting the data somehow, so `go run test.go > test.tar` was creating a bad tar file. It works fine in the CMD, though.
