### ISSUE TITLE
bytes/hash: TestSmhasherSmallKeys flake on android-arm-corellium builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#34834]
From the `android-arm-corellium` builder (https://build.golang.org/log/6d0506edef76d21049f50f3d2a77cf686d063476):
```
--- FAIL: TestSmhasherSmallKeys (0.15s)
    smhasher_test.go:95: unexpected number of collisions: got=256 mean=0.000000 stddev=0.000011
FAIL
FAIL	bytes/hash	0.639s
```

CC @randall77

**Comment by randall77** [comment]
I think what is going on here is that we're getting invalid random data on startup (`_AT_RANDOM` content not actually random, or perhaps zero length, or no `_AT_RANDOM` and `/dev/urandom` isn't random).
I can reproduce the behavior on 386 by setting `GODEBUG=cpu.all=off` (to get the same hash algorithm that arm uses) and commenting out the call to `getRandomData` in `runtime/alg.go:alginit`.

We use different parts of the startup random data to make the hash length-dependent. If the startup random data is not random (all zero,  probably) then the length-dependence of the hash goes away, and that's the behavior we're seeing (the 256 length 1 hashes are colliding with some of the 256^2 length 2 hashes).

**Comment by randall77** [comment]
I guess this could happen by chance with probability ~2^-16 (top ~16 bits of two 32-bit random numbers differ by a one-bit shift).

It hasn't recurred. I'm inclined to leave this as is and see if it happens again.

**Comment by ianlancetaylor** [comment]
It hasn't happened again.  Let's close and reopen if we see it.
