### ISSUE TITLE
net: apparent deadlock in TestCloseWrite on darwin-arm64-corellium

### ISSUE THREAD

**Issue by bcmills** [golang/go#34837]
From the darwin-arm64-corellium builder (https://build.golang.org/log/0f26cd7aadb20043bcb06081b5b9c0a633bcb9fe):

```
panic: test timed out after 3m0s

goroutine 601 [running]:
testing.(*M).startAlarm.func1()
	/tmp/workdir-host-darwin-arm64-corellium-ios/go/src/testing/testing.go:1377 +0xc0
created by time.goFunc
	/tmp/workdir-host-darwin-arm64-corellium-ios/go/src/time/sleep.go:168 +0x38

[…]

goroutine 599 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x10578ce98, 0x72, 0x102f20380)
	/tmp/workdir-host-darwin-arm64-corellium-ios/go/src/runtime/netpoll.go:184 +0x3c
internal/poll.(*pollDesc).wait(0x130356718, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	/tmp/workdir-host-darwin-arm64-corellium-ios/go/src/internal/poll/fd_poll_runtime.go:87 +0x30
internal/poll.(*pollDesc).waitRead(...)
	/tmp/workdir-host-darwin-arm64-corellium-ios/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x130356700, 0x13011000f, 0x1, 0x1, 0x0, 0x0, 0x0)
	/tmp/workdir-host-darwin-arm64-corellium-ios/go/src/internal/poll/fd_unix.go:169 +0x1b8
net.(*netFD).Read(0x130356700, 0x13011000f, 0x1, 0x1, 0x130356700, 0x102e44fd4, 0x1)
	/tmp/workdir-host-darwin-arm64-corellium-ios/go/src/net/fd_unix.go:202 +0x3c
net.(*conn).Read(0x130018010, 0x13011000f, 0x1, 0x1, 0x0, 0x0, 0x0)
	/tmp/workdir-host-darwin-arm64-corellium-ios/go/src/net/net.go:184 +0x68
net.TestCloseWrite(0x13017c600)
	/tmp/workdir-host-darwin-arm64-corellium-ios/go/src/net/net_test.go:151 +0x3cc
testing.tRunner(0x13017c600, 0x102f1ee80)
	/tmp/workdir-host-darwin-arm64-corellium-ios/go/src/testing/testing.go:909 +0xb0
created by testing.(*T).Run
	/tmp/workdir-host-darwin-arm64-corellium-ios/go/src/testing/testing.go:960 +0x29c

[…]

FAIL	net	180.181s
```

CC @mikioh @bradfitz @ianlancetaylor

**Comment by bcmills** [comment]
Another one on `darwin-arm64-corellium`. Is it possible that this is a recent regression?

https://build.golang.org/log/175d78eebd4aa686657b7faf57755ff9ee52d02e

**Comment by odeke-em** [comment]
I was plagued by this failure today when preparing a CL https://go-review.googlesource.com/c/go/+/200437/3#message-6a3671e972d7a38bd009fee322ab2b627c5d43ff that happened on 9 different builders and it wasn't just for TestCloseWrite

```shell
panic: test timed out after 3m0s

goroutine 1438 [running]:
testing.(*M).startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:1377 +0xdf
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:168 +0x44

goroutine 1 [chan receive, 2 minutes]:
testing.(*T).Run(0xc0004dff00, 0x9697fe, 0x14, 0x9944a0, 0x4b9801)
	/tmp/workdir/go/src/testing/testing.go:961 +0x378
testing.runTests.func1(0xc000103600)
	/tmp/workdir/go/src/testing/testing.go:1202 +0x78
testing.tRunner(0xc000103600, 0xc00004cd98)
	/tmp/workdir/go/src/testing/testing.go:909 +0xc9
testing.runTests(0xc00009c420, 0xd6e8c0, 0x1f9, 0x1f9, 0x0)
	/tmp/workdir/go/src/testing/testing.go:1200 +0x2a7
testing.(*M).Run(0xc000100680, 0x0)
	/tmp/workdir/go/src/testing/testing.go:1117 +0x176
net/http_test.TestMain(0xc000100680)
	/tmp/workdir/go/src/net/http/main_test.go:23 +0x2b
main.main()
	_testmain.go:1118 +0x135

goroutine 39 [chan receive, 3 minutes]:
testing.(*T).Parallel(0xc000124d00)
	/tmp/workdir/go/src/testing/testing.go:814 +0x1d5
net/http.TestCmdGoNoHTTPServer(0xc000124d00)
	/tmp/workdir/go/src/net/http/http_test.go:86 +0x43
testing.tRunner(0xc000124d00, 0x992b48)
	/tmp/workdir/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/tmp/workdir/go/src/testing/testing.go:960 +0x351
```

9 of 19 TryBots failed:
Failed on freebsd-amd64-12_0: https://storage.googleapis.com/go-build-log/7f1ab5d0/freebsd-amd64-12_0_c04127fb.log
Failed on linux-amd64: https://storage.googleapis.com/go-build-log/7f1ab5d0/linux-amd64_8f96dcf8.log
Failed on linux-386: https://storage.googleapis.com/go-build-log/7f1ab5d0/linux-386_e5da7e31.log
Failed on openbsd-amd64-64: https://storage.googleapis.com/go-build-log/7f1ab5d0/openbsd-amd64-64_05cd85d9.log
Failed on linux-amd64-race: https://storage.googleapis.com/go-build-log/7f1ab5d0/linux-amd64-race_6b7636a1.log
Failed on android-amd64-emu: https://storage.googleapis.com/go-build-log/7f1ab5d0/android-amd64-emu_93d00e21.log
Failed on windows-386-2008: https://storage.googleapis.com/go-build-log/7f1ab5d0/windows-386-2008_b9f149d8.log
Failed on js-wasm: https://storage.googleapis.com/go-build-log/7f1ab5d0/js-wasm_365c9070.log
Failed on windows-amd64-2016: https://storage.googleapis.com/go-build-log/7f1ab5d0/windows-amd64-2016_92bf52aa.log

not just darwin-arm64-corellium and it wasn't for TestCloseWrite only, seems like a testing/runtime issue.

**Comment by bcmills** [comment]
@odeke-em, that looks like a very different failure mode. You want to look for the goroutines that are _not_ blocked on `testing.(*T).Parallel`, which for the links you provided seem to be exclusively `net/http.(*connReader).abortPendingRead` in `TestWriteAfterHijack`.

The defining symptom for this issue, in contrast, seems to be a hang in `net.(*netFD).Read`.

**Comment by ianlancetaylor** [comment]
I don't really see how but it's conceivable that this is a recent regression due to https://golang.org/cl/197938.

**Comment by ianlancetaylor** [comment]
The test is both fairly straightforward and not all that important.  If someone wants to debug it, great, but I would be inclined to just skip it on darwim/arm64.

**Comment by ianlancetaylor** [comment]
Hasn't happened since November 7.  I'm calling this fixed.

**Comment by bcmills** [comment]
[2020-02-26T17:59:57-c27dd0c/darwin-arm64-corellium](https://build.golang.org/log/4738df48abe883b30a06cbe425557ec739f82a06)
[2020-02-20T22:34:08-8484d40/darwin-arm64-corellium](https://build.golang.org/log/7e8d9ea4ad6e320bf375219d750ad7159c109895)
[2020-01-03T01:36:26-f376b85/darwin-arm64-corellium](https://build.golang.org/log/fe73c9f96edf7076d07ebe1579d8b8c03de8e334)

**Comment by bcmills** [comment]
[2020-03-14T04:12:41-70dc28f/darwin-arm64-corellium](https://build.golang.org/log/fb740dd28821ac63d6686458446c35732379fb61)
[2020-03-03T19:53:02-24343cb/darwin-arm64-corellium](https://build.golang.org/log/522a357b6a55bcf09cda7945b7cb8eeb66024228)
[2020-02-27T21:24:58-1c4e515/darwin-arm64-corellium](https://build.golang.org/log/b071f7a1abafbd643c36da2e8c380e069310e743)

Given the apparent slowness of the network stack on this builder (#37322, #35498, and others), I wonder if this test is deadlocking due to a race that the other builders just aren't slow enough to trigger.

**Comment by bcmills** [comment]
Or, perhaps the test is timing out somewhere and written in such a way that timeouts manifest as deadlocks?

**Comment by bcmills** [comment]
Looks like at least the `tcp` stack is affected ([2020-04-13T21:56:15-1b15c7f/darwin-arm64-corellium](https://build.golang.org/log/c64b7fcccd9636bdcf52a5d629f941410a5b97c2)):
```
--- FAIL: TestCloseWrite (0.00s)
    --- FAIL: TestCloseWrite/tcp (158.92s)
        net_test.go:172: got (0, read tcp 127.0.0.1:58175->127.0.0.1:58174: i/o timeout); want (0, io.EOF)
        net_test.go:112: got (0, read tcp4 127.0.0.1:58174->127.0.0.1:58175: i/o timeout); want (0, io.EOF)
FAIL
FAIL	net	162.420s
```

**Comment by bcmills** [comment]
`greplogs --dashboard -md -l -e '(?ms)panic: test timed out.*^net\.TestCloseWrite' --since=2021-01-01`

[2021-10-25T17:18:40-bc0eb57/windows-arm64-10](https://build.golang.org/log/318a2f4a4bc4172c294e71b5c04f647800872a38)
[2021-10-13T18:15:48-40f82f8/windows-arm64-10](https://build.golang.org/log/2679560bee7e20baf48820a7136349a22b947064)
[2021-10-11T12:42:06-59b2f51/windows-arm64-10](https://build.golang.org/log/81c61ee9c5745ccf8ca0771a579394ca1f676394)
[2021-10-09T23:29:26-b99abf3/windows-arm64-10](https://build.golang.org/log/588b329358eecf6fb2519d7efdaebadcda4d42bb)
[2021-10-05T15:58:05-f1f626d/linux-arm64-aws](https://build.golang.org/log/5c6f35165123350b83c7b9522706a4e34513574e)
[2021-09-09T01:07:21-42563f8/windows-arm64-10](https://build.golang.org/log/f4fa6c70061921e4bef658a15953062ccd15c8a6)
[2021-06-29T16:57:13-3463852/windows-arm64-aws](https://build.golang.org/log/06efa45cd16d3b11e9fe8faac8d9123dd48d55e4)
[2021-06-24T03:20:33-86d72fa/windows-arm64-aws](https://build.golang.org/log/88468dab19622c5a8457e1b881d0bdf0321ef74f)
[2021-06-09T15:44:42-e6dda19/windows-arm64-aws](https://build.golang.org/log/f1c5b96f98a357b6b56a5d95e0d500608ff0a67d)
[2021-06-08T20:19:17-da4a640/windows-arm64-aws](https://build.golang.org/log/40550ec85d63dd21f97e818b6028dc0f7509e7a8)
[2021-06-04T09:39:32-0214440/windows-arm64-aws](https://build.golang.org/log/114dd7cb01f6dff2b45a65de548a8c32fddfe597)

No deadlocks on `darwin-arm64` this year, so I'm calling this issue “hopefully fixed”.
