### ISSUE TITLE
crypto/tls: small inconsistency around error formatting on crypto/generate_cert

### ISSUE THREAD

**Issue by fenos** [golang/go#34848]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.12.5 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes, the inconsistency lives on the master branch

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/fenos/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/fenos/Documents/code/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hd/7fyxcyhn01x2pmdqrs892v4h0000gp/T/go-build120066066=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Going trough the source code and i've noticed small inconsistencies in the code around the error formatting. 

### What did you expect to see?
- All errors are consistently using `%s` for interpolating errors
- Have the error included in every fatal error report

### What did you see instead?
- using `%v` instead of `%s` https://github.com/golang/go/blob/master/src/crypto/tls/generate_cert.go#L153

- not using the interpolation correctly using the `%s` https://github.com/golang/go/blob/master/src/crypto/tls/generate_cert.go#L148

**Comment by fenos** [comment]
I intend to work on fix for this

**Comment by ianlancetaylor** [comment]
Thanks for the report.  It's fine to use `%v` to print a value of type `error`.  If anything `%v` is more common than `%s`.

The `log.Fatalf` line should probably just be `log.Fatal`.

**Comment by fenos** [comment]
@iamoryanmoshe yes absolutely, i'm just trying to make things consistent across the file. 
Would you be happy to change all the `%s` to `%v`?

On the second bit, I think it would still be good to have the error printed out within the message
