### ISSUE TITLE
runtime: code generation confusion

### ISSUE THREAD

**Issue by acln0** [golang/go#34841]
I am hacking on the runtime. In the process, I wanted to add a constant such that it ends up in the (apparently machine-generated) `defs_linux_$GOARCH.go` files. I'm confused about whether or not I should be editing these files by hand. There appears to be a code generation step described in `defs_linux.go`, but I couldn't get it to work. A `go tool cgo -cdefs` does not appear to exist anymore. `go tool cgo -godefs` does seem to exist, but that one chokes (among other things), on [this line](https://github.com/golang/go/blob/77f9b2728eb08456899e6500328e00ec4829dddf/src/runtime/defs_linux.go#L53), which cannot possibly be right.

If I fix that, I get a missing definition error for `C.MAP_PRIVATE`, which appears to be in `linux/mman.h` these days rather than `asm/mman.h`? (at least on my system, which is `Debian GNU/Linux bullseye/sid`, according to `lsb_release`)

Do these comments need an update? Am I doing something wrong or missing a detail? When 77f9b2728eb08456899e6500328e00ec4829dddf was written, was the code generation tool actually invoked?

Thanks.

**Comment by bcmills** [comment]
This discussion is probably better suited to the [golang-dev list](https://groups.google.com/forum/#!forum/golang-dev).

**Comment by ianlancetaylor** [comment]
The code generation steps in the runtime package have been broken since the runtime was converted from C to Go.  Since the files rarely change, nobody has cared enough to fix this.

This is a dup of #23341.  See the discussion there.
