### ISSUE TITLE
go/build: importGo invokes 'go list' with the wrong working directory in module mode

### ISSUE THREAD

**Issue by coreoas** [golang/go#34860]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/corentin/Library/Caches/go-build"
GOENV="/Users/corentin/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/corentin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/corentin/code/my_recipes/backend/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sz/z0q535dx2876nknnf0dfk2fh0000gn/T/go-build204703159=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I have the following (simple) project, with a main.go:
```
package main

import (
	"fmt"
	"github.com/spf13/viper"
)
func init() {
        // this is to avoid the "imported but not used" error
	viper.SetConfigFile("./main")
}
func main() {
	fmt.Println("hello")
}
```

And the following go.mod:
```
module testissue
go 1.13
require github.com/spf13/viper v1.4.0
```

I can build and run the binary, but if y run `gotype -t -e main.go` I get the following error :

```
main.go:5:2: could not import github.com/spf13/viper (type-checking package "github.com/spf13/viper" failed (/Users/corentin/go/pkg/mod/github.com/spf13/viper@v1.4.0/flags.go:3:8: could not import github.com/spf13/pflag (go/build: importGo github.com/spf13/pflag: exit status 1
error writing go.mod: open /Users/corentin/go/pkg/mod/github.com/spf13/viper@v1.4.0/go.mod298498081.tmp: permission denied

)))
zsh: exit 2     gotype -t -e main.go
```

This is only the case with viper, if i use another package, such as [cobra](https://github.com/spf13/cobra)  by the same team, there is no error.

Even wierder, if I run gotype from the [gotype extention of Sublime-Linter](https://github.com/SublimeLinter/SublimeLinter-gotype), it manages to lint correctly every time with no errors.

### What did you expect to see?
No error when running gotype, and no mention of writing a `go.mod` in an external package.

### What did you see instead?
The error mentioned above.

**Comment by coreoas** [comment]
I also opened [an issue in the viper repository](https://github.com/spf13/viper/issues/783) because I don't know if the error is caused by gotype or viper.

**Comment by katiehockman** [comment]
Not sure what's going on here. /cc @bcmills in case this is modules related, and /cc @griesemer in case this is related to gotypes.

**Comment by griesemer** [comment]
This isn't a crash, it's a properly returned error (adjusted title).

I can reproduce this, and the underlying error seems to be:

```
go/build: importGo github.com/spf13/pflag: exit status 1
error writing go.mod: open /Users/gri/pkg/mod/github.com/spf13/viper@v1.4.0/go.mod298498081.tmp: permission denied
```

which points at go/build. @bcmills ?

**Comment by bcmills** [comment]
This is directly related to a suspected existing bug in `go/build`:
https://github.com/golang/go/blob/b649bdc7f3c99c5288c91a1ce148efadd86e19a4/src/go/build/build.go#L1057-L1060

It's nice to have a concrete reproducer, though. 😅
