### ISSUE TITLE
cmd/compile: dead-code elimination for empty init functions

### ISSUE THREAD

**Issue by mdempsky** [golang/go#34869]
Adding these functions to a package should have no effect:

    func init() {}
    func init() { if false { panic(0) } }

However, today they currently still emit empty functions (complete with DWARF debugging), which get linked into the inittasks array.

It's probably a simple task for sinit.go to recognize that the init function is empty and then skip processing it further.

/cc @cuonglm

**Comment by mvdan** [comment]
Also /cc @rasky; I believe his ongoing work on removing unused "pure" init functions would already catch this by definition. See #19533.

Though that's in the linker. I assume if the compiler takes care of the trivial ones, both sides can avoid some work.
