### ISSUE TITLE
cmd/go: "go env" becomes unusable after I run "go env -w" wrongly.

### ISSUE THREAD

**Issue by dotaheor** [golang/go#34880]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

true

### What did you do?

```
$ go env -w GO111MODULE==on
$ go env
go: unknown environment setting GO111MODULE==on
$ go env -w GO111MODULE=on
go: unknown environment setting GO111MODULE==on
$ go env -w GO111MODULE=
go: unknown environment setting GO111MODULE==on
```

**Comment by mvdan** [comment]
This seems to me like a variation of #34194; that involved an invalid GOOS/GOARCH pair, while this seems to involve an unknown variable name.

/cc @bcmills @jayconrod

**Comment by mvdan** [comment]
On second thought, this involves an invalid `GO111MODULE` value. Sent a CL.
