### ISSUE TITLE
Zero-width type weirdness

### ISSUE THREAD

**Issue by thwd** [golang/go#34897]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go1.13.1
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
playground
</pre></details>

### What did you do?
I ran two slightly different programs:
 - https://play.golang.org/p/3VlI5rp7KT8
 - https://play.golang.org/p/bAxC6hzRsB7

### What did you expect to see?
Spec says "Pointers to distinct zero-size variables may or may not be equal."

I expected the answer of whether they are to be a compiler implementation decision and not behavior that changes depending on the input program.

### What did you see instead?

I see that two zero-width values are equal only when they are otherwise used. They are treated as unequal otherwise.

**Comment by cherrymui** [comment]
Implementation detail: what matters is whether the zero-width object is heap allocated or stack allocated. In some sense it is still the compiler's decision, but this decision is made depending on the input program.

Anyway, as the spec says, this is work-as-intended.

**Comment by cherrymui** [comment]
Also, I should mention, this decision may change on different versions of Go.

**Comment by randall77** [comment]
Indeed, working as intended. Or at least, spec'd.
