### ISSUE TITLE
doc: broken links to https://blog.golang.org/go-fmt-your-code

### ISSUE THREAD

**Issue by mostynb** [golang/go#34894]
I followed a reference from a random go project's git hook to https://golang.org/misc/git/pre-commit and discovered a pseudo 404/"lstat $GOROOT/misc/git/pre-commit: no such file or directory" error. So I looked around some more and found another broken link to this URL from the go blog:
https://blog.golang.org/go-fmt-your-code

It seems that this file was removed back in January:
https://go-review.googlesource.com/c/go/+/158677

I wonder if it's worth making this link work again (either just on the website but not in the git repository, or re-adding the file to the repository with a "DEPRECATED, SEE ..." comment), or maybe editing that blog entry to point to the last commit where that file existed:
https://github.com/golang/go/blob/88da9ccb98ffaf84bb06b98c9a24af5d0a7025d2/misc/git/pre-commit

**Comment by mostynb** [comment]
@agnivade ^

**Comment by agnivade** [comment]
We should definitely fix the blog link. Perhaps we can ask users to run a `git codereview hooks` to install the hooks.

@andybons

**Comment by marcsanmi** [comment]
Can I take a look at this?

**Comment by mostynb** [comment]
@marcsanmi: I didn't realise the blog was on github until now. You could submit a PR to fix the link:
https://github.com/golang/blog/blob/master/content/go-fmt-your-code.article

**Comment by marcsanmi** [comment]
Ok, tomorrow I am going to do it

**Comment by mostynb** [comment]
Looks like this was fixed:
https://github.com/golang/blog/commit/0a405bc1dde109ab821285b20eb0b0d7506bb8fb
