### ISSUE TITLE
os: Windows: Stat fails on special files like 'con'

### ISSUE THREAD

**Issue by lifenjoiner** [golang/go#34900]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 windows/386
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOHOSTARCH=386
set GOHOSTOS=windows
</pre></details>

### What did you do?

try `test_Stat-con.go` to reproduce the issue
```go
package main

import (
	"os"
)

func main() {
	_, err := os.Stat("con")
	if err != nil {
		panic(err)
	}
}
```

I have debugged and located that `GetFileAttributesEx` fails on special files like 'con':
https://github.com/golang/go/blob/902d5aa84f8340752c20b93bfd450a6cefcf3952/src/os/stat_windows.go#L61-L76

and only  'nul':
https://github.com/golang/go/blob/902d5aa84f8340752c20b93bfd450a6cefcf3952/src/os/stat_windows.go#L24-L26
https://github.com/golang/go/blob/902d5aa84f8340752c20b93bfd450a6cefcf3952/src/os/stat_windows.go#L24-L26

**reserved names**
`CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9`:
https://docs.microsoft.com/zh-cn/windows/win32/fileio/naming-a-file#naming-conventions
`CONIN$` and `CONOUT$`:
https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea#consoles

ref:
https://github.com/gcc-mirror/gcc/blob/bbcdad768752f5cab6727242515bcd15706acbea/gcc/ada/adaint.c#L1606-L1618

### What did you expect to see?
We can access these special Windows files, especially `con` for printing to stdout.

### What did you see instead?
I found sometimes we need to use stdout as a file:
https://github.com/DNSCrypt/dnscrypt-proxy/blob/858957ce91015057a1f6c5a9a24f3ea2beb48537/dnscrypt-proxy/example-dnscrypt-proxy.toml#L339-L341
But `con` doesn't work.
By doing some research, I located the code here as described.
`GetFileAttributesEx` and `CreateFile` of `Stat` failed on the reserved file name `con`, and only 'nul' is considered as the special case.

**Comment by ianlancetaylor** [comment]
Not quite sure what to do here if `GetFileAttribuesEx` fails on `CON`.  What should `os.Stat` return?

CC @alexbrainman @mattn

**Comment by mattn** [comment]
```c
#include <stdio.h>
#include <sys/stat.h>

int
main(int argc, char* argv[]) {
  FILE* fp = fopen("CON", "r");
  if (fp == NULL) {
	perror("fopen");
	return 1;
  }
  fclose(fp);

  struct stat st;
  int r = stat("CON", &st);
  printf("result of stat: %d\n", r);

  printf("st_dev = %d\n", st.st_dev);
  printf("st_ino = %d\n", st.st_ino);
  printf("st_mode = %x\n", st.st_mode);
  printf("st_nlink = %d\n", st.st_nlink);
  printf("st_uid = %d\n", st.st_uid);
  printf("st_gid = %d\n", st.st_gid);
  printf("st_rdev = %d\n", st.st_rdev);
  printf("st_size = %lu\n", st.st_size);
  return 0;
}
```

```
result of stat: 0
st_dev = 2
st_ino = 0
st_mode = 81b6
st_nlink = 1
st_uid = 0
st_gid = 0
st_rdev = 2
st_size = 0
```

In this C program, `stat(2)` return 0 with successful. Go also should return nil for err.

**Comment by mattn** [comment]
Hopefully this will work.

```diff
diff --git a/src/os/stat_windows.go b/src/os/stat_windows.go
index 3e0e0a59ed..a6830c0f6e 100644
--- a/src/os/stat_windows.go
+++ b/src/os/stat_windows.go
@@ -74,6 +74,18 @@ func stat(funcname, name string, createFileAttrs uint32) (FileInfo, error) {
 		}
 		return fs, nil
 	}
+	if err == syscall.ERROR_FILE_NOT_FOUND {
+		if attr, err := syscall.GetFileAttributes(namep); err == nil && attr == syscall.FILE_ATTRIBUTE_ARCHIVE {
+			return &fileStat{
+				name: name,
+				// hopefully this will work for CON, PRN, AUX, CONOUT$ or etc.
+				vol:   0,
+				idxhi: 0,
+				idxlo: 0,
+			}, nil
+		}
+	}
+
 	// GetFileAttributesEx fails with ERROR_SHARING_VIOLATION error for
 	// files, like c:\pagefile.sys. Use FindFirstFile for such files.
 	if err == windows.ERROR_SHARING_VIOLATION {
@@ -89,7 +101,6 @@ func stat(funcname, name string, createFileAttrs uint32) (FileInfo, error) {
 		}
 		return fs, nil
 	}
-
 	// Finally use CreateFile.
 	h, err := syscall.CreateFile(namep, 0, 0, nil,
 		syscall.OPEN_EXISTING, createFileAttrs, 0)
```

**Comment by lifenjoiner** [comment]
Thanks, you guys are really quick~

**Comment by lifenjoiner** [comment]
@mattn
If your solution works well, maybe we can remove:
https://github.com/golang/go/blob/902d5aa84f8340752c20b93bfd450a6cefcf3952/src/os/stat_windows.go#L24-L26
https://github.com/golang/go/blob/902d5aa84f8340752c20b93bfd450a6cefcf3952/src/os/stat_windows.go#L24-L26
and maybe `isWindowsNulName` can be cleaned:
https://github.com/golang/go/blob/a38a917aee626a9b9d5ce2b93964f586bf759ea0/src/os/file.go#L565-L581
WinAPI `CreateDirectory` should have covered these reserved names:
https://github.com/golang/go/blob/a38a917aee626a9b9d5ce2b93964f586bf759ea0/src/syscall/syscall_windows.go#L443-L449
confiremed by
```go
package main

import (
	"os"
)

func main() {
	err := os.Mkdir("con", os.ModePerm)
	if err != nil {
		panic(err)
	}
}
```

**Comment by lifenjoiner** [comment]
append:
on windows, `mkdir nul` goes silence and returns success, `mkdir conin$` and `mkdir conin$` have no visible effect and also  succeed, while other reserved name trigger errors ...
