### ISSUE TITLE
x/build: update arm64 builders from jessie to stretch

### ISSUE THREAD

**Issue by randall77** [golang/go#34905]
We're currently running the jessie version of Debian on the arm64 trybots.

It looks like jessie is not supported on arm64. If I run `apt-get update` on a builder, I get an error like:
```
W: Failed to fetch http://ftp.debian.org/debian/dists/jessie/Release  Unable to find expected entry 'main/binary-arm64/Packages' in Release file (Wrong sources.list entry or malformed file)
```
There is indeed no such entry in that file. `arm64` doesn't appear anywhere in it (nor does `aarch64`).
In contrast, replace `jessie` with `stretch` in that URL, and you do see `arm64` support.

[This page](https://wiki.debian.org/Arm64Port#Official_Debian_port) claims arm64 support, but I'm not sure it is correct given my troubles.

I don't know where we got this jessie version that does run on arm64. But since `apt-get` doesn't work, it's hard to load any new software onto the builders (I'm trying to rebuild the race detector, for which I need `git` and `g++` loaded).

@bradfitz @mengzhuo

**Comment by bradfitz** [comment]
I just went to file this same bug. Thanks!

**Comment by mengzhuo** [comment]
FYI, I'm using Ubuntu `bionic` arm64 and it's doing fine. 
Maybe we can contact Packet maintainer and ask them to rebuild the distro to `jessie`?

**Comment by bradfitz** [comment]
We're just docker. It's the container that's Jessie. Probably a one line upgrade.
