### ISSUE TITLE
net/http: header.WriteSubset is case sensitive

### ISSUE THREAD

**Issue by empijei** [golang/go#34918]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version devel +0e015e20cf Wed Sep 11 12:26:35 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Not relevant

### What did you do?
https://play.golang.org/p/gtm6ZUm4omF

```go
	h := http.Header{}
	exclude := map[string]bool{}
	for k, v := range headers {
		h.Add(k, v)
		exclude[k] = true
	}
	h.WriteSubset(os.Stdout, exclude)
```

### What did you expect to see?
Nothing

### What did you see instead?
All lowercase headers

### Notes
I think this should either be documented or fixed as WriteSubset is the only method for http.Header that does not perform canonicalization.

/cc @bradfitz @rsc as per https://dev.golang.org/owners
/cc @kele as we found this together

**Comment by bradfitz** [comment]
WriteSubset is so weird. Unfortunate that we had to export it.

I guess we can document it, but the existing docs are pretty clear:

> If exclude is not nil, keys where exclude[key] == true are not written.

A map lookup is never case insensitive.
