### ISSUE TITLE
time: inconsistent handling of CEST time zone

### ISSUE THREAD

**Issue by infomaniac** [golang/go#34913]
### What version of Go are you using (`go version`)?
Mac: 
`$ go version go1.13 darwin/amd64`
Docker/Linux (image `golang:1.13.1`): 
`$ go version go1.13.1 linux/amd64`

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details>
<summary>MAC <code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/myuser/Library/Caches/go-build"
GOENV="/Users/myuser/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/myuser/myproject"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zx/tn2qh7xs46d352mn58mr2dcm0000gn/T/go-build417813244=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
</details>

<details>
<summary>Docker/Linux <code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/drone/src"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build206921703=/tmp/go-build -gno-record-gcc-switches"
</details>

### What did you do?

https://play.golang.org/p/mgNY9kKCUw6

`pt, err := time.Parse("20060102 150405 MST", "20190906 062023 CEST")`
`expected := time.Date(2019, 9, 06, 04, 20, 23, 0, time.UTC)`
`diff := pt.Sub(expected)`

The same _absolute_ time created with different timezones should have 0 difference.
This works on Mac, but not on Docker/Linux.

### What did you expect to see?
`0s` duration as difference when subtracting the times. 

### What did you see instead?
On go1.13 darwin/amd64 it works as expected, difference is `0s` duration
On go1.13.1 linux/amd64 the difference is `2h0m0s` duration

**Comment by bcmills** [comment]
`CEST` is not an [IANA time zone name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

(`CET` is, but it's deprecated; `CEST` seems to exist on Windows, but the script to update thoze abbreviations apparently hasn't been run since [last June](https://golang.org/cl/120559).)

So I see (at least) two issues here:

1. The documentation for [`time.Location`](https://github.com/golang/go/blob/c2c2ba280c77e76115cf1918d91a509f6bf98390/src/time/zoneinfo.go#L17) and [`time.Equal`](https://github.com/golang/go/blob/4983a0b75b40448d3245811ddcf682a9c86fc975/src/time/time.go#L260) probably should not refer to `CEST`, since that zone does not exist in the database uniformly.
   * [`http.TestAppendTime`](https://github.com/golang/go/blob/4c7a8d63e4042d16f87bf63720e3814683b0cb4b/src/net/http/serve_test.go#L4081) should not rely on it either.

2. `time.Parse` should report a non-nil error if the time zone is unrecognized.

CC @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Timezone parsing depends on the information recorded on your system.  If you see different information on different systems, it's because they have different timezone information.  On GNU/Linux this information is stored in /usr/share/zoneinfo.

**Comment by infomaniac** [comment]
Thank you for picking up the issue.

`CET` might me deprecated, but so is `MST` which is widely used in the [go documentation](https://golang.org/pkg/time/)

**Comment by infomaniac** [comment]
> Timezone parsing depends on the information recorded on your system. If you see different information on different systems, it's because they have different timezone information. On GNU/Linux this information is stored in /usr/share/zoneinfo.

Timezone parsing should only depend on the current system if not explicitly defined.
Even if it prints with different timezones, it's absolute value should be the same.
Therefor a Time.Sub(..) should return `0s` duration.

**Comment by ianlancetaylor** [comment]
Your example expects `CEST` to map to a specific timezone offset (`+0200`).  Your example explicitly expects 6:20 CEST to be the same as 4:20 UTC.  Whether they are the same or not depends on the information your system has about the timezone `CEST`.

**Comment by ianlancetaylor** [comment]
> CET might me deprecated, but so is MST which is widely used in the go documentation

@bcmills 's point is that while `CET` and `MST` are defined as IANA timezone names but are deprecated, `CEST` isn't defined at all.

In the tzdata database `CEST` (Central Europe Summer Time) is the timezone name printed for `CST` when in daylight savings time, but it doesn't seem to be recognized as a timezone name.

**Comment by infomaniac** [comment]
> @bcmills 's point is that while CET and MST are defined as IANA timezone names but are deprecated, CEST isn't defined at all.
Correct. I agree.

But when I adapt the timezone to `CET` the outcome is the same; the time difference is `1h0m0s` on Linux. On Mac, this works again as expected.

https://play.golang.org/p/y87Gq5bVeZf
It actually seems, like the TZ isn't processed when using `time.Parse(...)` on Linux.
```
2019-09-06 05:20:23 +0000 ABC -> 2019-09-06 05:20:23 +0000 ABC, error: <nil>
2019-09-06 05:20:23 +0000 UTC -> 2019-09-06 05:20:23 +0000 UTC, error: <nil>
2019-09-06 05:20:23 +0000 XYQ -> 2019-09-06 05:20:23 +0000 XYQ, error: <nil>
0001-01-01 00:00:00 +0000 UTC -> 0001-01-01 00:00:00 +0000 UTC, error: parsing time "20190906 052023 foobarbaz" as "20060102 150405 MST": cannot parse "foobarbaz" as "MST"
2019-09-06 05:20:23 +0000 MST -> 2019-09-06 05:20:23 +0000 MST, error: <nil>
```
Yes I know that `ABC` and `XYQ` and `foobarbaz` are invalid timezones. I would expect an error for `ABC` and `XYQ`, as we get for `foobarbaz`.
But MST is defined as `−0700` and is parsed as `+0000`.

Sorry for being a nag here.

**Comment by infomaniac** [comment]
> @bcmills 's point is that while CET and MST are defined as IANA timezone names but are deprecated, CEST isn't defined at all.

Correct. I agree.

I still believe there's a problem with `time.Parse()` as it behaves differently between Linux and Mac. (I cannot verify on Windows, sorry)

https://play.golang.org/p/xPnf-sz0E6W

On Docker/Linux and Playground the output is
```
[expected true ] parsedInUTC  equal: true -- 2019-09-06 10:00:00 +0000 UTC
[expected false] parsedInMST1 equal: true -- 2019-09-06 10:00:00 +0000 MST
[expected true ] parsedInMST2 equal: false -- 2019-09-06 03:00:00 +0000 MST
[expected true ] parsedInCET equal: false -- 2019-09-06 11:00:00 +0000 CET
[expected true ] parsedInLocation1 equal: true -- 2019-09-06 12:00:00 +0200 CEST
[expected true ] parsedInLocation2 equal: true -- 2019-09-06 10:00:00 +0000 UTC
```
On Mac it is
```
[expected true ] parsedInUTC  equal: true -- 2019-09-06 10:00:00 +0000 UTC
[expected false] parsedInMST1 equal: true -- 2019-09-06 10:00:00 +0000 MST
[expected true ] parsedInMST2 equal: false -- 2019-09-06 03:00:00 +0000 MST
[expected true ] parsedInCET equal: true -- 2019-09-06 12:00:00 +0200 CEST
[expected true ] parsedInLocation1 equal: true -- 2019-09-06 12:00:00 +0200 CEST
[expected true ] parsedInLocation2 equal: true -- 2019-09-06 10:00:00 +0000 UTC
```

What is confusing is that the same code behaves differently on Mac and Linux.
Also on Mac, `CET` is parsed correctly as a timezone, but `MST` not.

Sorry for being a nag.

**Comment by ianlancetaylor** [comment]
It is normal and expected for timezone parsing to differ on different systems, because it depends entirely on the timezone data present on the system.

From the output you show it appears that your Mac has data for the `CET` timezone but the playground and your GNU/Linux system do not.

**Comment by ptman** [comment]
https://utcc.utoronto.ca/~cks/space/blog/programming/GoTimeHasLocation ?

**Comment by ianlancetaylor** [comment]
I don't think there is anything to do here, so I'm going to close this issue.  Please comment if you disagree.
