### ISSUE TITLE
doc: the wiki home page doesn't mention modules

### ISSUE THREAD

**Issue by ainar-g** [golang/go#34914]
<p>
<a href="https://github.com/golang/go/wiki">The Go wiki home page</a>
contains links to neither the modules wiki page nor to the modules
documentation on golang.org.  I could try and add them, but I'm not sure
which section to put them into and what links are considered “must-have”
in a wiki.  I can add them if someone tells me which ones to add and
where should I add them to.
</p>

**Comment by jayconrod** [comment]
Thanks for pointing this out. I added a link under "Working with Go".

FYI, we're working on adding more documentation to golang.org. That's #33637.
