### ISSUE TITLE
x/mod: move cmd/go/internal/modfile into x/mod for go.mod parsing and formatting

### ISSUE THREAD

**Issue by zshift** [golang/go#34924]
### Expose modfile parsing as an importable module

I'd like the ability to parse modfile for purpose of repo analysis across various projects and repositories. Currently, the logic exists within an internal package, and the go modfile design does not follow an existing standard. Instead of requiring a 3rd-party implementation, which would likely stray from the modfile standard in future versions, it would be convenient to expose the existing, internal package for this.

**Comment by Logibox** [comment]
A nice addition to this would be exposing `cmd/go/internal/modload` as well, so finding the modfile in a repo is possible.

**Comment by ianlancetaylor** [comment]
This seems to be underway in https://godoc.org/golang.org/x/mod.

CC @jayconrod

**Comment by jayconrod** [comment]
I'm going to triage this as a feature request in x/mod, rather than a proposal. We'll move this package over relatively soon. It's small, has few dependencies, and the API is stable.

**Comment by jayconrod** [comment]
> A nice addition to this would be exposing cmd/go/internal/modload as well, so finding the modfile in a repo is possible.

`modload` is a large package with an unstable interface and unsynchronized global state. It will not be moved to `x/mod` as it is. It's something we'd like to do eventually, but we'll need to do a lot of refactoring and restructuring first.
