### ISSUE TITLE
cmd/go: confusing docs for -dropreplace

### ISSUE THREAD

**Issue by josharian** [golang/go#34930]
I wanted to programmatically drop all replace directives for a particular module.

Based on the docs, I initially thought just using `-dropreplace=old`, with no `@v`, would drop all replace directives for that module path:

```
The -replace=old[@v]=new[@v] and -dropreplace=old[@v] flags
add and drop a replacement of the given module path and version pair.
If the @v in old@v is omitted, the replacement applies to all versions
with the old module path.
```

It sounds from this like omitting the `@v` from a `-dropreplace` flag will make it apply to (drop) all versions with the old module path. What it actually does is drop any replace directives for that module path that do not specify a version.

It might be worth clarifying the docs a little.

**Comment by josharian** [comment]
Closing in favor of #34943.

**Comment by josharian** [comment]
Re-opening as a documentation issue. Re-titled and edited content to make the concern clearer.

**Comment by ianlancetaylor** [comment]
Ping @jayconrod @bcmills .  Let's write docs for 1.14 or move to backlog.  Thanks.
