### ISSUE TITLE
float64 member in struct output from json.Marshal not right

### ISSUE THREAD

**Issue by Tomarron** [golang/go#34949]
### What version of Go are you using (`go version`)?

<pre>
$ go version : 1.12

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

type A struct {
	ID     int     `json:"id"`
	Amount float64 `json:"amount"`
}

ok case:
func main() {
	var a = A{ID: 1, Amount: 7.11}
	var b = A{ID: 2, Amount: 1.02}
	c := A{ID: 1, Amount: 0.0000}
	c.Amount = a.Amount + b.Amount
	fmt.Printf("%f==%+v\n", c.Amount, c)
	content, err := json.Marshal(c)
	fmt.Println(string(content), err)
}
output: 
8.130000=={ID:1 Amount:8.13}
{"id":1,"amount":8.13} <nil>

nok case  : 

func main() {
	var a = A{ID: 1, Amount: 8.11}
	var b = A{ID: 2, Amount: 1.02}
	c := A{ID: 1, Amount: 0.0000}
	c.Amount = a.Amount + b.Amount
	fmt.Printf("%f==%+v\n", c.Amount, c)
	content, err := json.Marshal(c)
	fmt.Println(string(content), err)
}
output: 
9.130000=={ID:1 Amount:9.129999999999999}
{"id":1,"amount":9.129999999999999} <nil>

### What did you expect to see?

9.130000=={ID:1 Amount:9.13}
{"id":1,"amount":9.13} <nil>

### What did you see instead?

9.130000=={ID:1 Amount:9.129999999999999}
{"id":1,"amount":9.129999999999999} <nil>

the boundary is 8, can any explain is this a feature or bug,if feature, why? any advice to avoid the case or solution?

**Comment by networkimprov** [comment]
Note that it is not correct to use floating point types for currency values.
https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency

**Comment by bradfitz** [comment]
See https://floating-point-gui.de

This isn't really a Go issue.

**Comment by Tomarron** [comment]
can anyone explain why 8.13 is ok,but 9.13  shows 9.129999999999999, thanks a lot!

**Comment by bradfitz** [comment]
I sent you a link above with information about floats. This isn't a Go specific thing.

**Comment by Tomarron** [comment]
thanks,I will read.
