### ISSUE TITLE
cmd/compile: expand checkptr to find conversions of smaller types into bigger

### ISSUE THREAD

**Issue by ainar-g** [golang/go#34959]
<p>
Per discussion in
<a href="https://groups.google.com/d/topic/golang-dev/SzwDoqoRVJA/discussion">golang-dev</a>.
</p>

<p>
The <code>checkptr</code> dynamic analyser doesn't find bad type
conversions between types where the destination type is greater than the
source type.  E. g.:
</p>

<pre><code>var i32sink int32

type t1 struct { a, b int32 }

type t2 struct { a, b, c, d int32 }

func main() {
	for i := 0; i < 1000; i++ {
		var badt2 = *(*t2)(unsafe.Pointer(&t1{}))
		i32sink = badt2.d
	}
}
</code></pre>

<p>
Playground link:
<a href="https://play.golang.org/p/32lWMkFPvm5">https://play.golang.org/p/32lWMkFPvm5</a>.
</p>

<p>
According to @mdempsky:
</p>

<blockquote>
Detecting that is not currently supported, but I think there may at
least be some cases where we can detect it.  (…)
</blockquote>

**Comment by randall77** [comment]
We do this sometimes in `runtime` and `reflect`. For example, see `reflect/type.go:(*rtype).Elem`. It does a switch on `t.Kind()` and then casts an `*rtype` to other types (e.g. `*arrayType`) for which the base type is larger.

So we'd need to check that the underlying object allocation is large enough. Just having the base type be larger is not in itself an error.

**Comment by mdempsky** [comment]
@randall77 Yeah. I was thinking that when we convert p to *T, we just check that p and p+sizeof(T)-1 both point into the same heap object, kinda like how we do for pointer arithmetic checking

**Comment by mdempsky** [comment]
It might also be worth recognizing `(*[VeryBig]T)(ptr)[:n:m]`, since that's a common idiom for turning pointers into slices.

**Comment by mdempsky** [comment]
CL 201778 can now detect the invalid conversion here:

```
package main

import "unsafe"

var i32sink int32

type t1 struct{ a, b int32 }

type t2 struct{ a, b, c, d int32 }

//go:noinline
func alloc() *t1 {
	return &t1{}
}

func main() {
	for i := 0; i < 1000; i++ {
		var badt2 = *(*t2)(unsafe.Pointer(alloc()))
		i32sink = badt2.d
	}
}
```

It still doesn't detect the original example, but because in that one `&t1{}` is stack allocated, and the instrumentation currently can only validate pointers to heap objects.

One solution would be to make `-d=checkptr` change escape analysis to treat conversions to unsafe.Pointer as an escaping operation, which would force the objects onto the heap and allow better runtime validation.

**Comment by ainar-g** [comment]
<p>
Holy Dennis Ritchie that was quick!  Amazing, thanks!
</p>
