### ISSUE TITLE
cmd/link: Testing packages FAIL: TestDWARF/testprogcgo

### ISSUE THREAD

**Issue by rli-diraryi** [golang/go#34987]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.12.5 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/dxxx/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/soft/golib"
GOPROXY=""
GORACE=""
GOROOT="/soft/go"
GOTMPDIR=""
GOTOOLDIR="/soft/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1j/6xv6qk8d4q3fh_4z29636mtr0000gn/T/go-build753914485=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

When I upgrade the go version to 1.13.3，by run command:
cd go-go1.13.3/src/
./all.bash 

### What did you expect to see?

I want to know why. how to fix 。

### What did you see instead?

i get The following error：
--- FAIL: TestDWARF (0.20s)
    --- FAIL: TestDWARF/testprogcgo (3.62s)
        dwarf_test.go:96: symbols testprogcgo.exe: exit status 255: /var/folders/1j/6xv6qk8d4q3fh_4z29636mtr0000gn/T/go-link-TestDWARF684622652/testprogcgo.exe [x86_64, 0.005082 seconds]:
                F73AB3D4-23C7-3E99-9186-205BE7D91A22 /private/var/folders/1j/6xv6qk8d4q3fh_4z29636mtr0000gn/T/go-link-TestDWARF684622652/testprogcgo.exe [AOUT, FaultedFromDisk]  
                    0x0000000000000000 (0x4000000) __PAGEZERO SEGMENT
                    0x0000000004000000 (0x1d0000) __TEXT SEGMENT
                        0x0000000004000000 (  0x26e0) MACH_HEADER
                        0x00000000040026e0 ( 0xcb2e8) __TEXT __text
                            0x00000000040026e0 (    0x70) runtime.text [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004002750 (    0x50) internal/cpu.Initialize [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x00000000040027a0 (   0x6d0) internal/cpu.processOptions [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004002e70 (    0x40) internal/cpu.indexByte [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004002eb0 (   0x3f0) internal/cpu.doinit [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x00000000040032a0 (    0x20) internal/cpu.cpuid [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x00000000040032c0 (    0x20) internal/cpu.xgetbv [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x00000000040032e0 (    0x10) type..hash.internal/cpu.CacheLinePad [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x00000000040032f0 (    0x10) type..eq.internal/cpu.CacheLinePad [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004003300 (    0x60) type..hash.internal/cpu.arm64 [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004003360 (    0x60) type..eq.internal/cpu.arm64 [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x00000000040033c0 (    0x80) type..hash.internal/cpu.option [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004003440 (    0xb0) type..eq.internal/cpu.option [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x00000000040034f0 (    0x60) type..hash.internal/cpu.x86 [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004003550 (    0x60) type..eq.internal/cpu.x86 [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x00000000040035b0 (    0x70) type..hash.[15]internal/cpu.option [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004003620 (    0x90) type..eq.[15]internal/cpu.option [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x00000000040036b0 (    0x20) runtime/internal/atomic.Cas64 [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x00000000040036d0 (    0x10) runtime/internal/atomic.Casuintptr [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x00000000040036e0 (    0x10) runtime/internal/atomic.Storeuintptr [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x00000000040036f0 (    0x10) runtime/internal/atomic.Store [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004003700 (    0x10) runtime/internal/atomic.Store64 [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004003710 (    0x40) internal/bytealg.countGenericString [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004003750 (    0x30) internal/bytealg.init.0 [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004003780 (    0x20) runtime.cmpstring [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x00000000040037a0 (   0x240) cmpbody [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x00000000040039e0 (    0x30) internal/bytealg.CountString [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004003a10 (   0x180) countbody [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004003b90 (    0x30) runtime.memequal [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004003bc0 (    0x30) runtime.memequal_varlen [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004003bf0 (   0x140) memeqbody [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004003d30 (    0x30) internal/bytealg.IndexString [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004003d60 (   0x2f0) indexbody [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004004050 (    0x20) internal/bytealg.IndexByte [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004004070 (    0x20) internal/bytealg.IndexByteString [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x0000000004004090 (   0x120) indexbytebody [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x00000000040041b0 (    0x10) runtime.memhash0 [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                            0x00000000040041c0 (    0x60) runtime.memhash8 [FUNC, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
 ........
                            0x0000000004203720 (   0x200) runtime.printBacklog [NameNList, MangledNameNList, NList] 
                            0x0000000004203920 (   0x400) runtime.zeroVal [NameNList, MangledNameNList, NList] 
                            0x0000000004203d20 (  0x1768) runtime.memstats [NameNList, MangledNameNList, NList] 
                        0x0000000004205488 (    0x24) __DATA __common
                            0x0000000004205488 (     0x4) salt1 [EXT, NameNList, MangledNameNList, Merged, NList] 
                            0x000000000420548c (     0x4) salt2 [EXT, NameNList, MangledNameNList, NList] 
                            0x0000000004205490 (     0x8) pnil [EXT, NameNList, MangledNameNList, NList] 
                            0x0000000004205498 (     0x4) threadSalt1 [EXT, NameNList, MangledNameNList, NList] 
                            0x000000000420549c (     0x4) threadSalt2 [EXT, NameNList, MangledNameNList, NList] 
                            0x00000000042054a0 (     0x8) p [EXT, NameNList, MangledNameNList, NList] 
                            0x00000000042054a8 (     0x4) threadExited [EXT, NameNList, MangledNameNList, NList] 
                    0x0000000004206000 ( 0x7e000) __LINKEDIT SEGMENT
            symbols[29036]: [fatal]  child process status could not be determined; exit code unavailable.
FAIL
FAIL	cmd/link	5.517s

**Comment by cherrymui** [comment]
See #32218. Closing as dup.
