### ISSUE TITLE
gopls: couldn't exec 'go [list -f {{context.GOARCH}} {{context.Compiler}} -- unsafe]'

### ISSUE THREAD

**Issue by jeremyjohn** [golang/go#35007]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jeremy/.cache/go-build"
GOENV="/home/jeremy/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY="go.mhub.my"
GONOSUMDB="go.mhub.my"
GOOS="linux"
GOPATH="/home/jeremy/Project/go"
GOPRIVATE="go.mhub.my"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build965965451=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Open my go project folder using visual code which is using go.mod

### What did you expect to see?

Visual code with go to definition and linter working

### What did you see instead?

Visual code with go to definition and linter Not Working and the following error from gopls logs

```
[Error - 4:59:46 PM] Request textDocument/definition failed.
  Message: couldn't exec 'go [list -f {{context.GOARCH}} {{context.Compiler}} -- unsafe]': exec: "go": executable file not found in $PATH *exec.Error
  Code: 0 
```

**Comment by stamblerre** [comment]
@jeremyjohn: Is the `go` command on your `$PATH`? Are you able to run `go` on the command line without problems?

**Comment by jeremyjohn** [comment]
@stamblerre Yea my go is able to run just fine.
The problem I have this is with the latest version of the go extension in visual code 0.11.7.
When i downgraded it to 0.10.2 it's using older version of gopls if not mistaken so I don't have this problem.

**Comment by jeremyjohn** [comment]
Solved, My **$PATH** was defining my **$GOROOT** before my **$GOROOT** was even define in my **.bashrc**
