### ISSUE TITLE
cmd/go: can't load package: package main: cannot find package "main" in any of: /usr/local/go/src/main (from $GOROOT)      /Users/josuezafra/go/src/main (from $GOPATH)

### ISSUE THREAD

**Issue by JZafrag** [golang/go#35000]
So I just got this error in the cmd when I tried to run a simple program: 

<code>
package main

import (
    "net/http"
)

func main() {
    http.listenAndServe(":3000", nil)
}
</code>

And the error I got while trying to run <code>go build main.go</code>:

<code>
$ go build main.go
can't load package: package main: cannot find package main in any of:

/usr/local/go/src/main (from $GOROOT)
/Users/josuezafra/go/src/main (from $GOPATH)
</code>

I'm sorry if this is not an error from Go but from myself, I literally started learning Go today

**Comment by ianlancetaylor** [comment]
Did you type exactly `go build main.go`?  It looks like you typed `go build main`.

**Comment by dylan844r** [comment]
I'm having a similar problem. I keep getting `can't load package: package .: no Go files in C:\Users\*****` every time I try to use the go build command

**Comment by ianlancetaylor** [comment]
@dylan844r What precisely do you do?

**Comment by dylan844r** [comment]
@ianlancetaylor C:\Users\shumb>go build `C:\Users\shumb>go build
can't load package: package .: no Go files in C:\Users\shumb` I was trying to use this after successfully using the `go get` tool. I've been stuck here for a while and haven't found any answers on google

**Comment by ianlancetaylor** [comment]
@dylan844r The formatting is a bit wonky but it looks like you ran a simple `go build`.  When you run `go build` with no arguments, it will build the package in your current directory.  In you case it is telling you that there is no package in your current directory.

If you ran `go get github.com/x/y`, then you can build that by running `go build github.com/x/y`.

This is not the same problem as the original issue here, which does not say `no Go files` but instead says `cannot find package main`.  Let's take discussion of this side issue elsewhere, preferably a forum; see https://golang.org/wiki/Questions.  Thanks.

**Comment by JZafrag** [comment]
@ianlancetaylor Yes I did type it correctly. Sorry for not answering earlier, I was very busy with oher things

**Comment by ianlancetaylor** [comment]
I can recreate the problem exactly if I type 

    go build main

I cannot recreate it if I type 

    go build main.go

I don't know why you are seeing what you are seeing.

**Comment by bcmills** [comment]
@JZafrag, please fill out the complete issue template. (You can get a fresh copy from https://golang.org/issue/new.)

In order to diagnose the problem, we need to know the Go version in use, the output of `go env`, and the directory layout of your source code (especially in relation to `GOPATH`, `GOROOT`, and any `go.mod` file that may be present).
