### ISSUE TITLE
DigestVerify* api 

### ISSUE THREAD

**Issue by srinics** [golang/go#35011]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
I did not checked

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build336962369=/tmp/go-build -gno-record-gcc-switches"

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?
EVP_DigestVerifyInit
EVP_DigestVerifyUpdate
EVP_DigestVerifyFinal
Evalent go api's

### What did you see instead?
only sha256/224.Sum

**Comment by srinics** [comment]
Dev/Support team can anyone comment on this ?

**Comment by smasher164** [comment]
The Go [crypto](https://golang.org/pkg/crypto/) packages are [different](https://go.googlesource.com/proposal/+/master/design/cryptography-principles.md) from OpenSSL's [EVP](https://wiki.openssl.org/index.php/EVP) interface.
For questions about Go, see https://golang.org/wiki/Questions.
