### ISSUE TITLE
net/http: Transport should close body on all errors and match Client.Do docs

### ISSUE THREAD

**Issue by odeke-em** [golang/go#35015]
I just saw CL https://go-review.googlesource.com/c/go/+/202237 by @bored-engineer (thank you Luke!) and was going to review and recommend/create a test for the CL creator.

The docs for http.Client.Do https://golang.org/pkg/net/http/#Client.Do promise that we'll always close the body even on errors and so far we missed a few spots on the trivial cases with minor oversight
https://github.com/golang/go/blob/72275c0dea7887597e3e445676674ba6af702f06/src/net/http/transport.go#L469-L495

that is:
a) if isHTTP {
b) if t.useRegisteredProtocol(req)
c) if req.Method != "" && !validMethod(req.Method) {

and I realize this is because that code has been modified piecemeal over the past decade.

This test is what we can use to bootstrap checks
```go
package main

import (
	"io"
	"net/http"
	"net/http/httptest"
	"net/url"
	"testing"
)

type bodyCloser bool

func (bc *bodyCloser) Close() error {
	*bc = true
        return nil
}

func (bc *bodyCloser) Read(b []byte) (n int, err error) {
	return 0, io.EOF
}

func TestInvalidMethodClosesBody(t *testing.T) {
	cst := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {}))
	defer cst.Close()
	var bc bodyCloser

	u, _ := url.Parse(cst.URL)
	req := &http.Request{
		Method: " ",
		URL:    u,
		Body:   &bc,
	}

	_, err := http.DefaultClient.Do(req)
	if err == nil {
		t.Fatal("Expected an error")
	}
	if !bc {
		t.Fatal("Expected body to have been closed")
	}
}
```
which currently gives
```shell
$ go test
--- FAIL: TestInvalidMethodClosesBody (0.00s)
    it_test.go:39: Expected body to have been closed
```

This issue will be to send CLs to enforce those closes as well as tests so that we don't regress.

**Comment by bored-engineer** [comment]
@odeke-em what do you think about the remaining `useRegisteredProtocol` case where an error is returned by the underlying protocol handler. In my opinion `Transport` shouldn't handle that, it should be the responsibility of the protocol handler as the handler could have already closed the request body before an error occurred. In that case I think updating the docs so that expectation is clear would be a good addition.

**Comment by odeke-em** [comment]
Thanks for the question Luke! So in the follow-up CL I didn’t touch that
either as it is the responsibility of the alternative transport protocol.
Sure, perhaps we could update the docs but finding the right wording is
tricky because there are the first conditions for which an error will
result in a req.closeBody() regardless of the transport/protocol but also
it requires referencing Transport.RegisterProtocol, at which point I think
the prose might cause more confusion. Perhaps we could add to the line

>If an alternative protocol and RoundTripper was registered with the
Transport, it is the responsibility of that RoundTripper to close the body.

But am hesitant to add more words. /cc @bradfitz
