### ISSUE TITLE
x/playground: CORS in fmt/edit routes 

### ISSUE THREAD

**Issue by mo4islona** [golang/go#35019]
Playground snippets are not working properly on third-party sites.
fmt/edit routes are blocking by CORS.

I am working on new concept of snippets that can be easily integrated in any React app or even standalone. Take a look on https://mo4islona.github.io/material-go-playground/  it has a lot of examples. But some function are not working because of CORS policy.

I have a PR that fixes routes: https://go-review.googlesource.com/c/playground/+/193798

**Comment by mo4islona** [comment]
Fix is here -  https://go-review.googlesource.com/c/playground/+/193798
Could it be merged?

**Comment by toothrot** [comment]
@mo4islona Sorry about the delay on this. I'll work on getting it deployed today, if it hasn't automatically deployed already.

**Comment by toothrot** [comment]
@mo4islona This is finally deployed. There were several issues blocking deployments to the playground that have since been resolved.
