### ISSUE TITLE
Go Run Command Error

### ISSUE THREAD

**Issue by dylan844r** [golang/go#35023]
### What version of Go are you using (`go version`)?

<pre>
$ go version 13.1

</pre>

### Does this issue reproduce with the latest release?
I don't know

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\****\AppData\Local\go-build
set GOENV=C:\Users\****\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Projects\Go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\****\AppData\Local\Temp\go-build733011846=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
Tried to use 'go run' after successfully using 'go build'
C:\Users\**********>go run github.com/Team254/cheesy-arena
2019/10/20 18:16:50 Error during startup:  no valid version found
exit status 1

C:\Users\**********>

### What did you expect to see?
The program run

### What did you see instead?

This error message: 2019/10/20 18:16:50 Error during startup:  no valid version found
exit status 1

**Comment by ianlancetaylor** [comment]
That error is coming from the program you are running.  It is not coming from the Go tools.
