### ISSUE TITLE
Go build cant load package

### ISSUE THREAD

**Issue by dylan844r** [golang/go#35022]
### What version of Go are you using (`go version`)?

<pre>
$ go version 13.1

</pre>

### Does this issue reproduce with the latest release?
I'm not sure

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\****\AppData\Local\go-build
set GOENV=C:\Users\****\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Projects\Go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\****\AppData\Local\Temp\go-build733011846=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
Tried to use 'go build' but didn't work

'C:\Users\*******>go get github.com/Team254/cheesy-arena

C:\Users\*******>go build
can't load package: package .: no Go files in C:\Users\******

C:\Users\*******>'

### What did you expect to see?
For it to complete the command

### What did you see instead?
'can't load package: package .: no Go files in C:\Users\******'

**Comment by ianlancetaylor** [comment]
As I said in the other issue, this is normal.

    go get github.com/Team254/cheesy-arena

This will fetch the package into the module cache.

    go build

This will build the package in the current directory, but there is no package in the current directory.  Running `go get` does not put a package in the current directory.  If you look in the current directory you will see no .go files.  That is what the go command is telling you.

Try running

    go build github.com/Team254/cheesy-arena

**Comment by dylan844r** [comment]
Thanks! That really helped, now the final part is for me to run it but I have now encountered this problem, 
`C:\Users\*******>go run github.com/Team254/cheesy-arena
2019/10/20 15:46:22 Error during startup:  no valid version found
exit status 1

C:\Users\*********>`
