### ISSUE TITLE
can go use dynamic library built by go build -buildmode=c-shared

### ISSUE THREAD

**Issue by wangzz719** [golang/go#35024]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.12.10
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/wangzhizhao/.cache/go-build"
GOENV="/home/wangzhizhao/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/wangzhizhao/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build447829667=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

import "C"

// #cgo CFLAGS: -I /crypto_so/c_shared
// #cgo LDFLAGS: -L /crypto_so/c_shared -lucenter_crypto
// #include "ucenter_crypto.h"
import "C"
import (
	"fmt"
	"os"
)

func Init(serviceName string) error {
	res := C.InitCryptoClient()
}

func main() {
    Init("test")
}

 `/crypto_so/c_shared` directory contains `ucenter_crypto.h` and `ucenter_crypto.so`

### What did you expect to see?
the dynamic library can work correctly 

### What did you see instead?
# command-line-arguments
/usr/bin/ld: cannot find -lucenter_crypto
collect2: error: ld returned 1 exit status

**Comment by ianlancetaylor** [comment]
This isn't really a Go issue as such.  If you use `-lucenter_crypto`, the linker will look for `libucenter_crypto.so`.  You have `ucenter_crypto.so`.  You should either rename the file, or change your `LDFLAGS` line to use `ucenter_crypto.so` rather than `-lucenter_crypto`.
