### ISSUE TITLE
x/tools/go/analysis/passes/inspect: package godoc example incorrect

### ISSUE THREAD

**Issue by nnathan** [golang/go#35028]
### What version of Go are you using (`go version`)?

1.13

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

Doesn't matter.

### What did you do?

Apply the example from the [inspect godoc](https://godoc.org/golang.org/x/tools/go/analysis/passes/inspect).

See this [playground example demonstrating the compile error](https://play.golang.org/p/51yLMPKkzMw).

### What did you expect to see?

Not a compile error.

This specific line in the godoc for inspect.go (https://github.com/golang/tools/blob/master/go/analysis/passes/inspect/inspect.go#L19) should say:

```
Requires:       []*analysis.Analyzer{inspect.Analyzer},
```

Which can be verified in this [playground example](https://play.golang.org/p/x_BAzpOLzSD).

### What did you see instead?

N/A.

**Comment by rhnvrm** [comment]
I can take up this issue :+1:

**Comment by nnathan** [comment]
You da man Ro Han.

**Comment by rhnvrm** [comment]
@nnathan :)
