### ISSUE TITLE
cmd/go: can not import module from company's private repo

### ISSUE THREAD

**Issue by JLLNANA** [golang/go#35029]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.12

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
I have auth to access to company's private repo
go: finding github.companyname.com/user1/testpublic/b v1.1.1
go: github.companyname.com/user1/testpublic/b@v1.1.1: unknown revision b/v1.1.1

github.companyname.com is the repo belongs to the company when I submit some folder like this
testpublic---|
                      b---|
                              b.go
                              go.mod (module github.companyname.com/user1/testpublic/b)
                      go.mod (module github.companyname.com/user1/testpublic)

When I import module b from other code, it will give errors like
go: finding github.companyname.com/user1/testpublic/b v1.1.1
go: github.companyname.com/user1/testpublic/b@v1.1.1: unknown revision b/v1.1.1

### What did you expect to see?

I want to publish the module with different versions to the company's private repo

**Comment by bcmills** [comment]
Please complete the issue template.
* What is the output of `go env`?
* What specific `go` commands did you run, and what errors (if any) did they output before `unknown revision`?
* What happens using the latest release (`go1.13.3`)?

For this particular case:
* Is `github.companyname.com/user1/testpublic` the repository in question?
* What tags involving `v1.1.1` does it have?
* Is there a `b/go.mod` file within the repository?

**Comment by JLLNANA** [comment]
https://github.com/golang/go/issues/31143
Solved. The same problem as this link
