### ISSUE TITLE
syscall: Windows does not respect permission bits passed to Open

### ISSUE THREAD

**Issue by bcmills** [golang/go#35033]
In the course of testing #31481, I found the following failure on the `windows` builders at patch set 3 (https://storage.googleapis.com/go-build-log/096e97bd/windows-386-2008_7b478c28.log):
```
--- FAIL: TestScript (0.00s)
    --- FAIL: TestScript/mod_cache_rw (0.29s)
        script_test.go:191: 
            # Regression test for golang.org/issue/31481. (0.000s)
            # golang.org/issue/31481: an explicit flag should make directories in the module
            # cache writable in order to work around the historical inability of 'rm -rf' to
            # forcibly remove files in unwritable directories. (0.210s)
            # After adding an extraneous file, 'go mod verify' should fail. (0.046s)
            # However, files within those directories should still be read-only to avoid
            # accidental mutations. (0.001s)
            > [!root] ! cp $WORK/extraneous.txt $GOPATH/pkg/mod/rsc.io/quote@v1.5.2/go.mod
            FAIL: testdata\script\mod_cache_rw.txt:16: unexpected command success
            
FAIL
FAIL	cmd/go	75.878s
```

This suggests that either the `root` condition in `TestScript` is failing to detect a user acting in some sort of root-like role on Windows, or else we are failing to mark the contents of the module cache read-only on Windows.

CC @jayconrod @alexbrainman @zx2c4

**Comment by zx2c4** [comment]
I'll have something on gerrit in 5 minutes.

**Comment by zx2c4** [comment]
Suggested issue title change: "syscall: Windows does not respect permission bits passed to Open"
