### ISSUE TITLE
math: inconsistent conversion from NaN to int on js/wasm

### ISSUE THREAD

**Issue by ktye** [golang/go#35034]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 windows/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?
windows/amd64
js/wasm

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
The following program converts a NaN to int32.
The conversion is different on js/wasm, if math.NaN() is used or the bit pattern, even if both seem to be identical.

<pre>
package main

import (
        "fmt"
        "math"
)

var unan = uint64(0x7FF8000000000001)

func main() {
        n := math.NaN()
        i := int32(n)
        fmt.Printf("%f %d %d\n", n, i, math.Float64bits(n))

        n = math.Float64frombits(unan)
        i = int32(n)
        fmt.Printf("%f %d %d\n", n, i, math.Float64bits(n))
}
</pre>

To run the wasm program, it is compiled with:
GOOS=js GOARCH=wasm go build -o main.wasm main.go
and loaded in a browser with the method described in github.com/golang/go/wiki/WebAssembly

### What did you expect to see?
On playground and windows/amd64 the result is as expected:
NaN -2147483648 9221120237041090561
NaN -2147483648 9221120237041090561

I expect to see the same result in the js console when running the wasm program.

### What did you see instead?
on js/wasm the result is:
NaN -2147483648 9221120237041090561
NaN 0 9221120237041090561

Both chrome and firefox give the same result.

**Comment by dmitshur** [comment]
I thought there's a chance this could be related to 64-bit vs 32-bit, so I tried on `darwin/386` in addition to `darwin/amd64`, but they both got the same result as `windows/amd64`. So this seems specific to Wasm.

/cc @neelance @cherrymui

**Comment by neelance** [comment]
Right, NaN can not be represented as an int32. Closing.
