### ISSUE TITLE
x/tools: internal error: nil Pkg importing "errors" from "mypkg"

### ISSUE THREAD

**Issue by kevinburkemeter** [golang/go#35047]
I can only reproduce this with a "package main" Go binary in the same directory as go.mod - if I have a main that's nested several directories under go.mod, I can't reproduce. I also can't reproduce in libraries.

Steps to reproduce:

- Clone https://github.com/jmhodges/justrun - I put it in GOPATH but I don't think it matters.
- Configure vim-go at tip (2aa7c9d00af14ae71fdfe46f6a52b0a4f0fac774)
- configure x/tools at tip (ed542cd5b28ad1b474f8ff7ca112cad2c3ac2dc8), golang/go at tip (93a601dd2a)

Open watch.go in neovim (guessing Vim works as well), hover over `fsnotify.NewWatcher` and type `:GoDef` + CR in the status line. I get the following error:

```
vim-go: 2019/10/21 11:26:35 internal error: nil Pkg importing "errors" from "github.com/jmhodges/justrun"
```

I might not have that much time to assist with reproductions today but let me know if you can reproduce following these steps.

**Comment by bkielbasa** [comment]
I don't think it's strictly related to Go. Maybe try to report this to vim-go.

**Comment by kevinburkemeter** [comment]
Not a vim-go issue, but my editor was configured to use godef, not lsp. Opened rogpeppe/godef#118.
