### ISSUE TITLE
crypto/x509: apply gofmt to verify.go

### ISSUE THREAD

**Issue by graywolf** [golang/go#35052]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
+$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/wolf/.cache/go-build"
GOENV="/home/wolf/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/wolf/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/wolf/devel/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build608751303=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```
+$ go fmt ./...
crypto/x509/verify.go
```

### What did you expect to see?

```
+$ go fmt ./...
+$ git diff
```

### What did you see instead?

```
+$ go fmt ./...
crypto/x509/verify.go
+$ git diff
diff --git a/src/crypto/x509/verify.go b/src/crypto/x509/verify.go
index c8bad642f0..358fca4705 100644
--- a/src/crypto/x509/verify.go
+++ b/src/crypto/x509/verify.go
@@ -578,13 +578,13 @@ func (c *Certificate) isValid(certType int, currentChain []*Certificate, opts *V
        }
        if now.Before(c.NotBefore) {
                return CertificateInvalidError{
-                       Cert: c,
+                       Cert:   c,
                        Reason: Expired,
                        Detail: fmt.Sprintf("current time %s is before %s", now.Format(time.RFC3339), c.NotBefore.Format(time.RFC3339)),
                }
        } else if now.After(c.NotAfter) {
                return CertificateInvalidError{
-                       Cert: c,
+                       Cert:   c,
                        Reason: Expired,
                        Detail: fmt.Sprintf("current time %s is after %s", now.Format(time.RFC3339), c.NotAfter.Format(time.RFC3339)),
                }
```

**Comment by slrz** [comment]
Probably the result of some earlier fine-tuning of the fmt algorithms. They are not guaranteed to give the exact same output accross Go releases, although any adjustments tend to be minor in character.

It will get fixed up the next time someone touches that file in the course of doing some actual work. Until that happens, the current state doesn't hurt anyone, I guess?

**Comment by graywolf** [comment]
Yeah I was just surprised `go fmt` on clean clone actually changed something so I've decided to make a ticket. I mean, it should be like 1 minute for someone with commit rights to fix.

**Comment by agnivade** [comment]
You are most welcome to send a patch.

**Comment by graywolf** [comment]
Seems to require having google account and signing CLA, so I leave it up to someone willing to put up with both.

**Comment by evalevanto** [comment]
I can easily claim this and send a patch.
