### ISSUE TITLE
Warn when VCS URL's do not match Go import URL's

### ISSUE THREAD

**Issue by mcandre** [golang/go#35054]
As a programmer, it's confusing when a Go project's version control URL does not match its Go import URL.

The most common result is that the Go compiler errors with messages about how it is unable to find `*.go` source files. While this situation can be mitigated through very careful application of `go mod`, Glide, git submodules, or custom shell scripts for managing code, first time Go programmers are not expected to have already mastered these tools.

What if Go presented a warning when instructed to `go get`, `go build`, `go test`, `go install`, etc., any projects whose VCS URL did not align with their Go import URL structure? That way, we encourage more projects to "just work" when accessed by Go newbies?

**Comment by slrz** [comment]
Import paths and VCS URLs are distinct concepts for good reasons. We can't just start to warn about that.

What is the actual problem you're trying to solve? How exactly do those compiler errors happen?
