### ISSUE TITLE
x/build: add FreeBSD/arm64 builder

### ISSUE THREAD

**Issue by dmitshur** [golang/go#35058]
Creating a tracking issue for the task of adding a `freebsd/arm64` builder, factored out from https://github.com/golang/go/issues/24715#issuecomment-537742727.

/cc @dmgk @bradfitz @bcmills

**Comment by dmgk** [comment]
Relevant CL: https://go-review.googlesource.com/c/build/+/198597

**Comment by dmgk** [comment]
The builder is up [1]. I haven't done steps 7-8 yet as they seem to depend on step 4 [2]

[1] https://build.golang.org/
[2] https://github.com/golang/go/wiki/DashboardBuilders#how-to-set-up-a-builder

**Comment by dmitshur** [comment]
Closing as this issue is resolved, the `freebsd-arm64-dmgk` builder has been running and passing for a while now. It's also being maintained and fixed with quick turnaround, see #37601. Thank you very much @dmgk.
