### ISSUE TITLE
debug/dwarf: 0-length array problem

### ISSUE THREAD

**Issue by kylelemons** [golang/go#3505]
<pre>I'm attempting to wrap libusb so I can interface with my kinect.  I have basic control
working and have written the bulk and interrupt code, but isochronous requires using the
asynchronous API, which cgo seems to be having trouble with.

Consider the following code:

/* iso.go */
package usb

// #include &lt;libusb-1.0/libusb.h&gt;
import &quot;C&quot;

type Transfer C.struct_libusb_transfer
/* end */

The struct is documented here:
<a href="http://libusb.sourceforge.net/api-1.0/structlibusb__transfer.html">http://libusb.sourceforge.net/api-1.0/structlibusb__transfer.html</a>

and defined here (see line 765):
<a href="http://libusb.sourceforge.net/api-1.0/libusb_8h_source.html">http://libusb.sourceforge.net/api-1.0/libusb_8h_source.html</a>

notably:
{...
struct libusb_iso_packet_descriptor iso_packet_desc[0];
...}

and cgo reports:
iso.go:7:15: struct size calculation error off=72 bytesize=64

$ gcc --version
i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM
build 2335.15.00)
Copyright (C) 2007 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ go version
go version go1

$ go env
GOROOT=&quot;/opt/go&quot;
GOBIN=&quot;&quot;
GOARCH=&quot;amd64&quot;
GOCHAR=&quot;6&quot;
GOOS=&quot;darwin&quot;
GOEXE=&quot;&quot;
GOHOSTARCH=&quot;amd64&quot;
GOHOSTOS=&quot;darwin&quot;
GOTOOLDIR=&quot;/opt/go/pkg/tool/darwin_amd64&quot;
GOGCCFLAGS=&quot;-g -O2 -fPIC -m64 -pthread -fno-common&quot;
CGO_ENABLED=&quot;1&quot;</pre>

**Comment by ianlancetaylor** [comment]
Is this still a problem?  I can't get the test case in comment 4 to reproduce with any combination of Go version or compiler.  I don't see any other complete test cases here.

If this is still a problem, we need instructions on how to reproduce it.  Thanks.

**Comment by agnivade** [comment]
Just tested with latest 1.9.2. No issues seen. Can this be an artifact of older Go versions ?
