### ISSUE TITLE
x/tools/gopls: Inconsistent deep completion for io.ErrUnexpectedEOF

### ISSUE THREAD

**Issue by psanford** [golang/go#35062]
With deep completions enabled I was trying to complete `io.u<>` to `io.ErrUnexpectedEOF` in the following code:
```
package foo

import (
	"io"
)

func IsEOF(e error) bool {
	if e == io.EOF {
		return true
	}

	if e == io.u<>

	return false
}
```
This resulted in a single suggested completion: `io.ErrUnexpectedEOF.Error()`. 

However if I type `io.un<>`: 
```
package foo

import (
	"io"
)

func IsEOF(e error) bool {
	if e == io.EOF {
		return true
	}

	if e == io.un<>

	return false
}
```
I get two suggestions: [`io.ErrUnexpectedEOF`, `io.ErrUnexpectedEOF.Error()`].

### What did you see instead?

I expected the completions to be the same for both cases.

I'm using gopls built from master as of today.

/cc @muirrn @stamblerre

**Comment by muirrn** [comment]
@psanford can you try the above CL? You will need to grab both commits.

**Comment by psanford** [comment]
With the changes applied `io.u<>` now suggests just `io.ErrUnexpectedEOF`. which seems correct to me. 

I think my core concern was getting a deeper suggestion when matching on characters only found in the shallower field (and not getting the shallower completion as an option). I think you've addressed that issue here.
