### ISSUE TITLE
hash/hashmap: replace MakeSeed with NewSeed?

### ISSUE THREAD

**Issue by mdempsky** [golang/go#35060]
In #28322, @rsc said ["it sounds like we have converged on: [...] `func NewSeed() Seed`"](https://github.com/golang/go/issues/28322#issuecomment-498831453).

@randall77 later proposed ["It might be nice to be able to serialize/deserialize a `Seed`. Probably not necessary for v1."](https://github.com/golang/go/issues/28322#issuecomment-498838310) ["...or construct a `Seed` from an `int64`."](https://github.com/golang/go/issues/28322#issuecomment-498838788)

@rsc subsequently stated ["I agree about @randall77's clarifications and added them above."](https://github.com/golang/go/issues/28322#issuecomment-501019281), incorporating the other changes @randall77 proposed in his comments (i.e., Add and Hash semantics), but not these Seed changes (which weren't addressed).

However, CL 186877 did implement `MakeSeed(uint64) Seed` rather than `NewSeed() Seed`, 

Filing as a release blocker just to make sure we're agreed on the API that we want exposed here before we're committed to supporting it.

--

My 2c: Since seeds only have meaning within a single process, it seems just as easy to simply call `hash.NewSeed` and then pass the `hash.Seed` value around as it is to generate a random `uint64`, pass that around, and call `hash.MakeSeed`.

**Comment by rsc** [comment]
CL 205069 does this (removes the argument).
