### ISSUE TITLE
runtime: TestNetpollBreak failing on netbsd-arm-bsiegert

### ISSUE THREAD

**Issue by bcmills** [golang/go#35074]
Now that #35037 is resolved, the `netbsd-arm-bsiegert` builder is showing a different failure mode, this time in `TestNetpollBreak` (https://build.golang.org/log/bc18dc9b999d2adff72d678f0608afc8a6cbc4d9):
```
--- FAIL: TestNetpollBreak (10.03s)
    proc_test.go:1020: netpollBreak did not interrupt netpoll: slept for: 10.028473916s
FAIL
FAIL	runtime	190.460s
```

CC @ianlancetaylor @mknyszek

**Comment by ianlancetaylor** [comment]
This problem has fixed itself, with the dashboard showing two successful runs after an unrelated CL.  Optimistically closing.
