### ISSUE TITLE
x/tools/gopls: ParseExported mode and go/analysis

### ISSUE THREAD

**Issue by stamblerre** [golang/go#35089]
`go/analysis` requires code from source in order to get facts for all dependencies.
Our current strategy of parsing dependencies in exported mode deletes function bodies, thereby preventing `go/analysis` from getting correct facts for dependencies.

Some possible solutions:

- Parse dependencies in full mode
  - Will fix everything easily
  - Takes up a lot of memory
- Parse dependencies in full mode, run analyses, trim ASTs, and re-cache as `ParseExported`
  - This will be hard to get right
  - This will require deleting items from the cache explicitly
  - It may throw off position information
  - This will still keep a lot of unnecessary information around in the `*types.Info` map
- Have a separate path for type-checking language features like completion, definition, etc. and  analysis.
  - Language feature path: Type-checks only a specific function in a package as well as the package's dependencies in exported form
  - Analysis path: Type-checks everything from source, caching only analysis facts

/cc @ianthehat @dominikh @muirrn

**Comment by muirrn** [comment]
Maybe a wacky idea, but has anyone ever thought about "compressing" the type info? In my experience, a lot of the memory usage is from map overhead for all the AST overlay maps in `*types.Info`. Maybe we could compress the `*types.Info` data down into slice form when not being used to save space. The assumption is that thawing the data would still be much faster than re-type checking the package.
