### ISSUE TITLE
net/http: build tag to disable HTTP/2

### ISSUE THREAD

**Issue by crawshaw** [golang/go#35082]
Background:

I am writing an iOS App Extension in Go. This particular extension is hard limited by the OS to 16MB RAM, which seems to be based on RSS. This means binary size is counted in the RAM limit, and indeed appears to dominate the RAM use. It is easy to keep heap < 5mb and stacks < 2mb, but the simplest Go programs blow out into 10mb binaries (after removing DWARF).

Suggestion:

Add a build tag to disable HTTP/2. This lets users cut 600kb off their (DWARF-less) binaries.

Experimenting with my app, it includes the HTTP client from net/http and is currently 8.6mb when compiled with `-ldflags=-w`. By deleting `h2_bundle.go` (the HTTP/2 implementation) and the few references to it in the other files of net/http, my binary size drops to 7.99mb.

**Comment by dmitshur** [comment]
Is it viable to instead make just the HTTP/1 client available in an external package, and use that instead of `net/http`?

The challenge of adding a build constraint for this is that it adds a new configuration that’ll need to be tested, and it may scale poorly when there’s also HTTP/3.

**Comment by bradfitz** [comment]
> The challenge of adding a build constraint for this is that it adds a new configuration that’ll need to be tested,

We already do similar with osusergo and netgo and have a testing story there. (test that they compile in a separate cmd/dist test). I don't think we'd need any builder coverage other than making sure it compiles.

**Comment by odeke-em** [comment]
We started some simple discourse on Twitter. I suggested
>+build !no_http2
>OR
>+build !disable_http2
>For the h2_bundle.go file

and @bradfitz replied with
>Double negatives always suck but probably unavoidable. At least we can avoid "not no". Like "not omit". Maybe omithttp2. It's not disabled. It doesn't exist. We don't generally use underscores in build tags.

and I agreed with
>Yeah:
>  +build !omithttp2
>works. I like the “omit” prefix

So a current pitch is to use `+build !omithttp2` if using building tags

**Comment by bradfitz** [comment]
The existing precedent seems to be to prefix the build tag with the package name (`netgo` for the `net` package, `osusergo` for the `os/user` package). If we kept that up it'd be `nethttpomithttp2` which is kinda a mouthful but ... specific. I'm okay with it.

We'd probably want to make the `clientServerTest` helper just `t.Skip` when http2 isn't compiled in. Hopefuly it's not much more than that.

**Comment by bradfitz** [comment]
In any case, I'm fine with this, especially if it's as small of a patch as I'm imagining. I haven't tried.

**Comment by bronze1man** [comment]
@crawshaw 
Knowing workaround to memory limit of iOS App Extension :
using go1.9.x

**Comment by dmitshur** [comment]
Changing to NeedsFix per https://github.com/golang/go/issues/35082#issuecomment-545239713. Should go back to NeedsDecision if there are complications.
