### ISSUE TITLE
syscall: checkptr failures relating to Dirent on darwin and freebsd

### ISSUE THREAD

**Issue by mdempsky** [golang/go#35092]
The freebsd and darwin -race builders are currently failing:

- [darwin](https://build.golang.org/log/75a5629d6ce36be737723c480138e7383ed820be)
- [freebsd](https://build.golang.org/log/8e167b257d222edab8e1b9500db47323d312c859)

Both of these appear to be failing due to use of syscall.Dirent.

**Comment by cuonglm** [comment]
It does not happen for me under 10.15:

```
$ env -u GO111MODULE go tool dist test -race go_test:syscall
##### Testing packages.
ok  	syscall	3.549s

ALL TESTS PASSED (some were excluded)
```

**Comment by cuonglm** [comment]
It seems that:

```
$ cd syscall
$ go test -race
```

trigger the error.
```

**Comment by cuonglm** [comment]
So it's not `-race`, but in #34972, we check with `-short`, so not all tests were run. With:

```
go test -a -gcflags=all=-d=checkptr syscall
```

The test is always false.

**Comment by tklauser** [comment]
Same happens in `golang.org/x/sys/unix` on the `freebsd-amd64-race` builder with `-d=checkptr` enabled:

https://build.golang.org/log/79e02a85654067a443293a96844a33710e123c27

**Comment by mdempsky** [comment]
I'm probably not going to have time to look into this for another week or so. If someone wants to fix this, please go for it. Otherwise, it's probably worth at least adding some `//go:nocheckptr` directives with TODOs referencing this issue to at least get the build passing again.

**Comment by cuonglm** [comment]
@mdempsky I'm investigating darwin one. Still not clearly understand the issue. If I add `runtime.KeepAlive(buf)` after this line:

https://github.com/golang/go/blob/758eb020f72a70e3e42814492daac8719a3be538/src/syscall/getdirentries_test.go#L58

Then the test pass. But it does fails again with `-d=checkptr=2`.
