### ISSUE TITLE
x/build: mac builders down

### ISSUE THREAD

**Issue by dmitshur** [golang/go#35109]
All Mac builders are currently down, as reported at https://farmer.golang.org/#health:

![image](https://user-images.githubusercontent.com/1924134/67395969-d3352e00-f574-11e9-8b97-b005e9781236.png)

This is due to an issue at our Mac provider. They've notified us about the issue and that it should be resolved on their side by now, but it's been many hours and the Mac builders haven't returned yet.

/cc @bradfitz @toothrot @cagedmantis

**Comment by bradfitz** [comment]
macstadiumd disk went read-only. Rebooted.

That's a new thing to add to the monitoring on farmer.golang.org. It's happened a few times now.

**Comment by dmitshur** [comment]
Thanks Brad.

I'll close this issue since the Mac builder outage is resolved:

![image](https://user-images.githubusercontent.com/1924134/67408908-c2da7e80-f587-11e9-8cc8-93b7100bbf7c.png)

> That's a new thing to add to the monitoring on farmer.golang.org. It's happened a few times now.

There's an open issue #32449 tracking that. I've retitled it to be more specific, we can use it for this task.
