### ISSUE TITLE
x/sys/unix: cmsgAlignOf redeclared

### ISSUE THREAD

**Issue by Sheshagiri** [golang/go#35102]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes. I only tried with `go1.12.12`

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sheshagiri/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sheshagiri/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go@1.12/1.12.12/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go@1.12/1.12.12/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/sheshagiri/workspace/extreme/waas/api/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fk/4gq46s3960z78bjbvrkbf2bh0000gp/T/go-build052242506=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
$go mod vendor

### What did you expect to see?
I see that `cmsgAlignOf ` is declared in two different go files in the same package.

### What did you see instead?
```
github.com/extremenetworks/waas/api/vendor/gol
ang.org/x/sys/unix                                                                                                                 
srv/gopath/src/github.com/extremenetworks/waas/api/vendor/golang.org/x/sys/unix/sockcmsg_unix_other.go:14:6: cmsgAlignOf redeclared
 in this block                                                                                                                     
        previous declaration at srv/gopath/src/github.com/extremenetworks/waas/api/vendor/golang.org/x/sys/unix/sockcmsg_unix.go:17
:29.                                                                                                                               
```

**Comment by tklauser** [comment]
Are you sure you correctly vendored `x/sys/unix`? I can't seem to access github.com/extremenetworks/waas to check for myself. There shouldn't be a declaration of `cmsgAlignOf` anymore in `sockcmsg_unix.go`:

https://github.com/golang/sys/blob/master/unix/sockcmsg_unix.go

It was there before but was moved by https://golang.org/cl/202179

**Comment by Sheshagiri** [comment]
unfortunately, that is a private repo. I deleted the `vendor` and cleaned my cache(go clean --modcache) and now I only see 
```
~/w/e/w/api (shesh/add-rules-endpoint-api|✚1) $ grep -iR "func cmsgAlignOf(" vendor/
vendor//golang.org/x/sys/unix/sockcmsg_unix.go:func cmsgAlignOf(salen int) int {
~/w/e/w/api (shesh/add-rules-endpoint-api|✚1) $
```

**Comment by Sheshagiri** [comment]
I tried `go get -u golang.org/x/sys/unix` and now it declared in two files.
```
~/w/e/w/api (shesh/add-rules-endpoint-api|✚1) $ go get -u golang.org/x/sys/unix
go: finding golang.org/x/sys/unix latest
go: finding golang.org/x/sys latest
~/w/e/w/api (shesh/add-rules-endpoint-api|✚2) $ go mod vendor
~/w/e/w/api (shesh/add-rules-endpoint-api|✚2) $ grep -iR "func cmsgAlignOf(" vendor/
vendor//golang.org/x/sys/unix/sockcmsg_unix_other.go:func cmsgAlignOf(salen int) int {
vendor//golang.org/x/sys/unix/sockcmsg_dragonfly.go:func cmsgAlignOf(salen int) int {
~/w/e/w/api (shesh/add-rules-endpoint-api|✚2) $
```

**Comment by tklauser** [comment]
Yes, this is where they should be declared (once for dragonfly and once for all other geese). Does the issue still persist with this vendoring?

**Comment by Sheshagiri** [comment]
Apparently one of the dependency has an older version of sys/unix pinned to it because of which I was getting the error I described in this issue. I removed that dependency and don’t see the issue anymore, so closing the issue.
