### ISSUE TITLE
HTTP2 client buffers data written and flushed by the server

### ISSUE THREAD

**Issue by igolaizola** [golang/go#35129]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
</pre></details>

### What did you do?

I have created an HTTP2 client that connects to an HTTP2 server.

On the server side I do the following:
 - write `[]byte{0xAA, 0xBB}`
 - call `flush()`
 - write `[]byte{0xCC, 0xDD}`
 - call `flush()`

On the client side I read the incoming data.

Here is the testing code:
https://play.golang.org/p/OtrJ7wW62Ud

### What did you expect to see?

On the client side I expect to do the first call to `Read()` to obtain `[]byte{0xAA, 0xBB}` and on a second call to `Read()` obtain `[]byte{0xCC, 0xDD}`

### What did you see instead?

Instead on the first call to `Read()` I obtain `[]byte{0xAA, 0xBB, 0xCC, 0xDD}`

**Comment by bradfitz** [comment]
Neither HTTP/2 nor io.Reader has semantic record boundaries. It's just a byte stream.

Closing, as I don't see any action required here on our side.
