### ISSUE TITLE
Something wrong with strings.TrimLeft when string start with '/v'

### ISSUE THREAD

**Issue by zhaozy93** [golang/go#35149]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.13.2
</pre>

### Does this issue reproduce with the latest release?
Not Sure

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Usually we use strings.TrimLeft to trim some fixed prefix, however when exec strings.TrimLeft("./csv/visitor.csv", "./csv/"), the EXPECTED result is "vistor.csv", the REAL result is "istor.csv". 

It's amazing.

https://play.golang.com/p/EeY2DKiWeRR

```
package main

import (
	"fmt"
	"strings"
)

func main() {
	fmt.Println("----------a-----------")
	a := "./csv/visitor.csv"
	fmt.Println(a)
	fff := strings.TrimLeft(a, "./csv/")
	fmt.Println(fff)

	fmt.Println("----------b-----------")
	b := "./csv/visitor.csv"
	fmt.Println(b)
	fff = strings.TrimLeft(b, "./csv")
	fmt.Println(fff)
	
	fmt.Println("----------c-----------")
	c := "./csv/visitor.csv"
	fmt.Println(c)
	fff = strings.TrimLeft(b, "./")
	fmt.Println(fff)
}

```

### What did you expect to see?

----------a-----------
./csv/visitor.csv
visitor.csv
----------b-----------
./csv/visitor.csv
visitor.csv
----------c-----------
./csv/visitor.csv
csv/visitor.csv

### What did you see instead?

----------a-----------
./csv/visitor.csv
isitor.csv
----------b-----------
./csv/visitor.csv
isitor.csv
----------c-----------
./csv/visitor.csv
csv/visitor.csv

**Comment by zhaozy93** [comment]
I think you want https://godoc.org/strings#TrimPrefix instead.

**Comment by zhaozy93** [comment]
Anyone could close this if you want.

**Comment by tmthrgd** [comment]
Check the documentation: https://golang.org/pkg/strings/#TrimLeft:

> TrimLeft returns a slice of the string s with all leading Unicode code points contained in cutset removed.
>
> To remove a prefix, use TrimPrefix instead.

The TrimLeft function is removing every character from the cutest from the start of the string whereas what you’re looking is what TrimPrefix does, which is to remove a fixed prefix from the string.

**Comment by zhaozy93** [comment]
> Check the documentation: https://golang.org/pkg/strings/#TrimLeft:
> 
> > TrimLeft returns a slice of the string s with all leading Unicode code points contained in cutset removed.
> > To remove a prefix, use TrimPrefix instead.
> 
> The TrimLeft function is removing every character from the cutest from the start of the string whereas what you’re looking is what TrimPrefix does, which is to remove a fixed prefix from the string.

yeah I have found this. stupid -_-
Thanks
