### ISSUE TITLE
x/tools/present: panic when serving presentation with .video

### ISSUE THREAD

**Issue by echlebek** [golang/go#35142]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Unknown

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/eric/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/eric/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/eric/go/src/github.com/echlebek/lisa19-etcd/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build129608040=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

In a present slide set, attempt to embed an animated svg as a video.

```
.video animated.svg
```

### What did you expect to see?

I was expecting to see the SVG rendered as a playable video, or an error.

### What did you see instead?

The HTTP handler panicked.

May be related to #17561

**Comment by dmitshur** [comment]
Thanks for reporting.

I've sent [CL 203477](https://golang.org/cl/203477) to fix this.

**Comment by echlebek** [comment]
Cheers Dmitri! :beers:
