### ISSUE TITLE
cmd/compile: cyclic interfaces cause massive memory usage

### ISSUE THREAD

**Issue by elagergren-spideroak** [golang/go#35146]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/elagergren/gopath/bin"
GOCACHE="/Users/elagergren/Library/Caches/go-build"
GOENV="/Users/elagergren/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/elagergren/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2b/74fz3jhd4wz4vnbf4z7ywzww0000gp/T/go-build398016473=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://play.golang.org/p/3-RUQ50ubib

### What did you expect to see?

*Something* other than `compile` ballooning to over 6 GB of RAM.

Maybe relates to #27256 and #26863.

**Comment by elagergren-spideroak** [comment]
I actually didn't let `compile` finish since I didn't want to lock up my machine, so maybe I overreacted.

Maybe relates to #27256 and #26863.

**Comment by mdempsky** [comment]
Interesting. If I had to guess, we're probably failing to take advantage of memoizing some of the sub-expression typechecking. In general though, anonymous and cyclic interfaces are a recurring source of issues.

Is this derived from any real world code?

**Comment by elagergren-spideroak** [comment]
Yeah, a (rudimentary) SQL generator. The anonymous interfaces are used to "mask" off methods. It's not terribly important code.

A smaller repro:

https://play.golang.org/p/PoFq8QTuiMp
```go
type A interface {
   A() interface {
      A
      B() interface{ A }
   }
}
```

**Comment by mdempsky** [comment]
Thanks for minimizing the test case.

To clarify, are you saying it uses a lot of memory but then terminates? Or it's going into an infinite loop allocating more and more memory?

(On my phone, and the play links just give a generic compilation failure error.)

**Comment by ALTree** [comment]
This looks like #1909.

**Comment by mdempsky** [comment]
@ALTree Thanks, confirmed it is a dup of that. We just go into an infinite recursion in typefmt.

@elagergren-spideroak Thanks for clarifying.
