### ISSUE TITLE
gccgo: can't compile simple example which uses github.com/valyala/fasthttp

### ISSUE THREAD

**Issue by matszpk** [golang/go#35154]
I was trying to build simple example which uses fasthttp: "https://raw.githubusercontent.com/valyala/fasthttp/v1.5.0/examples/helloworldserver/helloworldserver.go".
Go while getting and building sources just report internal error:

`github.com/valyala/fasthttp (download)`
`github.com/klauspost/compress (download)`
`github.com/valyala/bytebufferpool (download)`
`github.com/valyala/fasthttp/fasthttputil`
`# github.com/valyala/fasthttp/fasthttputil`
`go1: internal compiler error: in type_index, at go/gofrontend/export.cc:993`
`Please submit a full bug report,`
`with preprocessed source if appropriate.`
`See <https://bugs.archlinux.org/> for instructions.`

My go version: from arch linux: go version go1.12.2 gccgo (GCC) 9.2.0 linux/amd64
go env:
GOARCH="amd64"
GOBIN=""
GOCACHE="/mnt/oldsys/home/mat/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/mnt/oldsys/home/mat/docs/dev/go/fasthttp-ws"
GOPROXY=""
GORACE=""
GOROOT="/usr"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0"
GCCGO="/usr/bin/gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build979769442=/tmp/go-build -gno-record-gcc-switches -funwind-tables

I reproduced this error in Gentoo machine with go-9.2.0 compiler. this same output.
Go based on GC compiler just build this example without and problems. Also, gccgo-8.3.0 have no problems while building this example.

**Comment by dmitshur** [comment]
It seems the problem is with the `github.com/valyala/fasthttp/fasthttputil` package specifically. It's quite small. @matszpk Can you check if this can be reproduced with a smaller snippet that imports just `github.com/valyala/fasthttp/fasthttputil`?

**Comment by ianlancetaylor** [comment]
This looks like #34577, which is fixed on trunk.  I'll backport a workaround to the GCC 9 branch.

**Comment by ianlancetaylor** [comment]
Thanks for reporting the problem.

I committed a patch to fix this on GCC 9 branch: https://gcc.gnu.org/ml/gcc-patches/2019-10/msg01865.html .
