### ISSUE TITLE
proposal: time: change Ticker to provide info about skipped ticks

### ISSUE THREAD

**Issue by gopherbot** [golang/go#3516]
by **kballard**:

<pre>The interface for time.Ticker makes it impossible to determine if any ticks have been
skipped if the period is small. The difficulty lies in the fact that the underlying
timer has a &quot;when&quot; field that isn't exposed, and the client of the ticker
can't possibly know exactly what the value of &quot;when&quot; is. On each tick it's
given the time that the tick was calculated at, but without the &quot;when&quot; field,
determining if any ticks have been skipped is not possible with 100% accuracy. This is,
of course, only a problem for very small periods.

Rather than exposing the &quot;when&quot; field, it's probably much simpler and better
to simply create a second constructor that takes a Time and a Duration instead of just a
Duration. This Time is used as the initial &quot;when&quot;. Not only does this make the
code for detecting skipped ticks rather trivial, it also allows for more flexibility in
timer creation for clients that need that.</pre>

**Comment by ianlancetaylor** [comment]
The current implementation of `time.NewTicker` sends the current time (as returned by `time.Now`) on each tick.  I don't think we can do any better; Go is not a hard real time system.  If you need more precision I think you need your own mechanism outside of the standard library.

Closing.
