### ISSUE TITLE
x/website: Remove "why Golang is Sucessful by Creator of Golang Rob-pike" from the "Featured video" rotation

### ISSUE THREAD

**Issue by manisenkov** [golang/go#35171]
One of the videos that currently rotates in the "Featured video" section is "why Golang is Sucessful by Creator of Golang Rob-pike" (title spelling is preserved, [link to the video](https://www.youtube.com/watch?v=cQ7STILAS0M)). This video is just a cut copy of original Rob Pike's "Simplicity is Complicated" talk from dotGo 2015 ([link to original](https://www.youtube.com/watch?v=rFejpH_tAHM)), so it should be removed from rotation or replaced with the original one.

**Comment by agnivade** [comment]
@andybons
