### ISSUE TITLE
x/term: needs x/sys upgrade for freebsd-arm64

### ISSUE THREAD

**Issue by bcmills** [golang/go#35182]
From the `freebsd-arm64-dmgk` builder (https://build.golang.org/log/da798266d1c726e10eef98c1b2c306066d786f79):
```
go: finding golang.org/x/sys v0.0.0-20191010194322-b09406accb47
# golang.org/x/sys/unix
../../../../pkg/mod/golang.org/x/sys@v0.0.0-20191010194322-b09406accb47/unix/ztypes_freebsd_arm64.go:400:12: undefined: uint128
FAIL	golang.org/x/term [build failed]
```

There is no such failure in the builder for the `x/sys` subrepo, so presumably it just needs an update.

CC @tklauser @dmgk

**Comment by tklauser** [comment]
Fixed by https://golang.org/cl/203617
