### ISSUE TITLE
x/build: windows-amd64-longtest failing on x/mobile

### ISSUE THREAD

**Issue by bcmills** [golang/go#35185]
https://build.golang.org/log/2c7d5ffd37cce526cbf896b708d104b98a7f21f9 shows the `windows-amd64-longtest` running (and failing on) the `x/mobile` repo.

Should this builder be running x/moble at all?

CC @bradfitz @dmitshur @toothrot

**Comment by bradfitz** [comment]
No, it shouldn't.

**Comment by bcmills** [comment]
Looking at https://build.golang.org/?repo=golang.org%2fx%2fmobile, it appears that the other `longtest` builders are also running `x/mobile` for some reason.

**Comment by bcmills** [comment]
(And apparently some random `freebsd` builders on occasion..?)

**Comment by dmitshur** [comment]
```Go
buildsRepo: func(repo, branch, goBranch string) bool {
	return repo == "go" || (branch == "master" && goBranch == "master")
},
```

> It's already configured to only build go@master.

Isn't that saying "build all branches in the Go repo **plus** the master branch of any other repo as long using Go tip"?

**Comment by bradfitz** [comment]
Derp dee derp. I totally didn't read that earlier.

Okay, this is an easy fix then.
