### ISSUE TITLE
go/types: some small problems in docs

### ISSUE THREAD

**Issue by yaxinlx** [golang/go#35189]
In the docs of the [selections](https://golang.org/pkg/go/types/#Selection):
```
Selector    Kind          Recv    Obj    Type               Index     Indirect

p.x         FieldVal      T       x      int                {0}       true
p.m         MethodVal     *T      m      func (e *T) m()    {1, 0}    true
T.m         MethodExpr    T       m      func m(_ T)        {1, 0}    fals
```
Should the `Type` columns for the second and third line be `func()` and `func(_ T)`?

**Comment by yaxinlx** [comment]
And in the [func (*Scope) LookupParent] docs:
```
...  (see Insert, below) ...
```

The `Insert` method docs is shown above the `LookupParent` docs in fact.

**Comment by dmitshur** [comment]
> The `Insert` method docs is shown above the `LookupParent` docs in fact.

It's below in source code, but above in documentation (since godoc displays identifiers in alphabetical order). We can fix this by making it say just "see Insert"; the reader should be able to find `Insert` easily in either medium.

**Comment by dmitshur** [comment]
> Should the `Type` columns for the second and third line be `func()` and `func(_ T)`?

That does seem more fitting to me too. It's also what https://github.com/golang/example/tree/master/gotypes#selections uses. The current text seems to be close to what [`types.SelectionString`](https://golang.org/pkg/go/types/#SelectionString) may produce, but that is the string form of the entire selector expression, not just its type.

@griesemer Do you agree it would be an improvement, or are we missing some context?

/cc @dominikh

**Comment by griesemer** [comment]
Agreed. CL forthcoming.
