### ISSUE TITLE
x/sys/unix: TestSchedSetaffinity failing on linux-ppc64le-buildlet

### ISSUE THREAD

**Issue by bcmills** [golang/go#35184]
From `linux-ppc64le-buildlet` (https://build.golang.org/log/1e46452b18adf5f3b2ec28dfcee7bc28bf55be10):
```
--- FAIL: TestSchedSetaffinity (0.00s)
    syscall_linux_test.go:366: SchedSetaffinity: invalid argument
FAIL
FAIL	golang.org/x/sys/unix	0.568s
```

See previously #27875.

CC @tklauser @laboger

**Comment by laboger** [comment]
Can you check if the test on that system has the change from this patch?
Maybe for some reason the x/sys/unix version is not correct.
