### ISSUE TITLE
Golang show warning after updating to 1.13 on OSX Catalina 10.15

### ISSUE THREAD

**Issue by m6devin** [golang/go#35193]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.13.3 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/mgh/workspace/go/bin"
GOCACHE="/Users/mgh/Library/Caches/go-build"
GOENV="/Users/mgh/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mgh/workspace/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/mgh/workspace/goprojects/ems_city_voice_backuper/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wq/sb__d3b92nzfwck0079853kr0000gn/T/go-build880819649=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do? 

I've just updated golang from 1.12 to 1.13. After updating to 1.13, on building project it shows warning like this:
<pre>
go build -v  ems_city_voice_backuper 
# ems_city_voice_backuper
ld: warning: object file (/var/folders/wq/sb__d3b92nzfwck0079853kr0000gn/T/go-link-696217276/000014.o) was built for newer OSX version (10.15) than being linked (10.14)
ld: warning: object file (/var/folders/wq/sb__d3b92nzfwck0079853kr0000gn/T/go-link-696217276/000015.o) was built for newer OSX version (10.15) than being linked (10.14)
ld: warning: object file (/var/folders/wq/sb__d3b92nzfwck0079853kr0000gn/T/go-link-696217276/000016.o) was built for newer OSX version (10.15) than being linked (10.14)
ld: warning: object file (/var/folders/wq/sb__d3b92nzfwck0079853kr0000gn/T/go-link-696217276/000017.o) was built for newer OSX version (10.15) than being linked (10.14)
ld: warning: object file (/var/folders/wq/sb__d3b92nzfwck0079853kr0000gn/T/go-link-696217276/000018.o) was built for newer OSX version (10.15) than being linked (10.14)
ld: warning: object file (/var/folders/wq/sb__d3b92nzfwck0079853kr0000gn/T/go-link-696217276/000019.o) was built for newer OSX version (10.15) than being linked (10.14)
ld: warning: object file (/var/folders/wq/sb__d3b92nzfwck0079853kr0000gn/T/go-link-696217276/000020.o) was built for newer OSX version (10.15) than being linked (10.14)
ld: warning: object file (/var/folders/wq/sb__d3b92nzfwck0079853kr0000gn/T/go-link-696217276/000021.o) was built for newer OSX version (10.15) than being linked (10.14)
ld: warning: object file (/var/folders/wq/sb__d3b92nzfwck0079853kr0000gn/T/go-link-696217276/000022.o) was built for newer OSX version (10.15) than being linked (10.14)
ld: warning: object file (/var/folders/wq/sb__d3b92nzfwck0079853kr0000gn/T/go-link-696217276/000023.o) was built for newer OSX version (10.15) than being linked (10.14)
ld: warning: object file (/var/folders/wq/sb__d3b92nzfwck0079853kr0000gn/T/go-link-696217276/000024.o) was built for newer OSX version (10.15) than being linked (10.14)
ld: warning: object file (/var/folders/wq/sb__d3b92nzfwck0079853kr0000gn/T/go-link-696217276/000025.o) was built for newer OSX version (10.15) than being linked (10.14)
ld: warning: object file (/var/folders/wq/sb__d3b92nzfwck0079853kr0000gn/T/go-link-696217276/000026.o) was built for newer OSX version (10.15) than being linked (10.14)
ld: warning: object file (/var/folders/wq/sb__d3b92nzfwck0079853kr0000gn/T/go-link-696217276/000027.o) was built for newer OSX version (10.15) than being linked (10.14)
</pre>

**Comment by ALTree** [comment]
Thanks for the report. 

This comes up periodically for OSX; see #22281. It must be related to some kind of object cache, but - at least from reading #22281 - it appears we don't have an answer on *what* should be cleaned to make the error disappear.

I'm inclined to close this as a dup of #22281.

**Comment by ALTree** [comment]
Closing as a dup of #22281.
