### ISSUE TITLE
syscall/js: nanotime and walltime not compatible with wasm_exec.js

### ISSUE THREAD

**Issue by EntityB** [golang/go#35205]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.13.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/entityb/.cache/go-build"
GOENV="/home/entityb/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/entityb/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build157101446=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Build a minimum program for WASM

**main.go**
```go
package main

import (
	"syscall/js"
)

func main() {

	doc := js.Global().Get("document")
	body := doc.Get("body")

	message := "<h1>Hello world!</h1>"

	body.Set("innerHTML", message)
}
```

**index.html**
```html
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8" />
    <title>TinyGo WASM Boilerplate</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script src="wasm_exec.js" defer></script>
    <script src="wasm.js" defer></script>
</head>

<body>

</body>

</html>
```

**wasm.js**
```js
window.addEventListener("load", () => {
  if (!WebAssembly.instantiateStreaming) { // polyfill
    WebAssembly.instantiateStreaming = async (resp, importObject) => {
      const source = await (await resp).arrayBuffer();
      return await WebAssembly.instantiate(source, importObject);
    };
  }
  const go = new Go();
  let mod, inst;
  WebAssembly.instantiateStreaming(fetch("wasm.wasm"), go.importObject).then((result) => {
    mod = result.module;
    inst = result.instance;
    run();
  }).catch((err) => {
    console.error(err);
  });
  async function run() {
    await go.run(inst);
    inst = await WebAssembly.instantiate(mod, go.importObject); // reset instance
  }
});
```

**wasm_exec.js**
from latest master:
https://github.com/golang/go/blob/master/misc/wasm/wasm_exec.js

**build command:**
```bash
GOOS=js GOARCH=wasm go build -o ./wasm.wasm ./main.go
```

### What did you expect to see?

No errors on the webpage/console. 

`Hello world!` in the body

### What did you see instead?

Error in console: 
```
LinkError: WebAssembly.instantiate(): Import #3 module="go" function="runtime.nanotime" error: function import requires a callable
```
After fixing by renaming in wasm_exec.js:
```
LinkError: WebAssembly.instantiate(): Import #4 module="go" function="runtime.walltime" error: function import requires a callable
```

Source of the issue seems to be in this commit:
https://github.com/golang/go/commit/4af3c17f8cd37288a5bb9bc53e8b88c58f5624d1

I'm not sure what was the goal here, but something was done wrong. The `wasm_exec.js` file is not compatible now.

**Comment by cherrymui** [comment]
> `$ go version go1.13.3 linux/amd64`

> wasm_exec.js
from latest master:
https://github.com/golang/go/blob/master/misc/wasm/wasm_exec.js

If you use Go 1.13.3, you should also use wasm_exec.js from Go 1.13.3 tree.

**Comment by EntityB** [comment]
@cherrymui thanks for the advice! For some reason, I though that 1.13.3 is the master since it is the latest release :( It is working now.
