### ISSUE TITLE
path/filepath: TestEvalSymlinksAboveRoot failure on macOS

### ISSUE THREAD

**Issue by shulhan-tokenomy** [golang/go#35201]
### What version of Go are you using (`go version`)?

Go tip @ 1f3339f441 ,

2019-10-26 1f3339f441  Dan S.. > runtime:  fix dumpgoroutine() to deal with open-coded defers

### Does this issue reproduce with the latest release?

No.

### What operating system and processor architecture are you using (`go env`)?

Operating system: macOS Catalina 10.15 (19A602)

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"                                                                                                                                             
GOARCH="amd64"                                                                                                                                               
GOBIN="/Users/(redacted)/go/bin"                                                                                                                               
GOCACHE="/Users/(redacted)/Library/Caches/go-build"                                                                                                            
GOENV="/Users/(redacted)/Library/Application Support/go/env"                                                                                                   
GOEXE=""                                                                                                                                                     
GOFLAGS=""                                                                                                                                                   
GOHOSTARCH="amd64"                                                                                                                                           
GOHOSTOS="darwin"                                                                                                                                            
GONOPROXY="github.com/(redacted)"                                                                                                                              
GONOSUMDB="github.com/(redacted)"                                                                                                                              
GOOS="darwin"                        
GOPATH="/Users/(redacted)/go"
GOPRIVATE="github.com/(redacted)"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/(redacted)/share/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/(redacted)/share/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gw/38q053cd1h5ghjzyky4xqf6w0000gn/T/go-build610751110=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Rebuild Go from source.

### What did you expect to see?

Build success.

### What did you see instead?

```
ok      path    0.380s                                                                                                                                       
--- FAIL: TestEvalSymlinksAboveRoot (0.00s)                                                                                                                  
    path_test.go:1449: EvalSymlinks("/private/var/folders/gw/38q053cd1h5ghjzyky4xqf6w0000gn/T/TestEvalSymlinksAboveRoot878810328/../../../../../../../private
/var/folders/gw/38q053cd1h5ghjzyky4xqf6w0000gn/T/TestEvalSymlinksAboveRoot878810328/b/file") = "/private/var/folders/gw/38q053cd1h5ghjzyky4xqf6w0000gn/T/Test
EvalSymlinksAboveRoot878810328/a/file"                                                                                                                       
    path_test.go:1445: EvalSymlinks("/private/var/folders/gw/38q053cd1h5ghjzyky4xqf6w0000gn/T/TestEvalSymlinksAboveRoot878810328/../../../../../../../../priv
ate/var/folders/gw/38q053cd1h5ghjzyky4xqf6w0000gn/T/TestEvalSymlinksAboveRoot878810328/b/file") failed: lstat /private/../../private/var: no such file or dir
ectory
    path_test.go:1449: EvalSymlinks("/private/var/folders/gw/38q053cd1h5ghjzyky4xqf6w0000gn/T/TestEvalSymlinksAboveRoot878810328/../../../../../../../../../p
rivate/var/folders/gw/38q053cd1h5ghjzyky4xqf6w0000gn/T/TestEvalSymlinksAboveRoot878810328/b/file") = "/private/var/folders/gw/38q053cd1h5ghjzyky4xqf6w0000gn/
T/TestEvalSymlinksAboveRoot878810328/a/file"
FAIL
FAIL    path/filepath   0.380s
ok      plugin  0.385s
```

**Comment by FiloSottile** [comment]
I can't reproduce this with `go test path/filepath` at tip. Is it always failing for you?

**Comment by shulhan-tokenomy** [comment]
I try to rebuild again with tip 97592b3c14 , and its build successfully.   Seems like a glitch somewhere in my system between build.  I will close this now.  Thank you @FiloSottile .
