### ISSUE TITLE
Nil custom error returned from function not treated as nil

### ISSUE THREAD

**Issue by eduhenke** [golang/go#35217]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/henke/.cache/go-build"
GOENV="/home/henke/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/henke/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/henke/Voltbras/fohat/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build298030670=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I call a function that returns a nil `*customError`, like examplified in this code:
https://play.golang.org/p/vrQd6QQdynS

### What did you expect to see?

I expected that `err == nil`, like this code: 
https://play.golang.org/p/UJ0-c5cjlLT

### What did you see instead?

I saw that `err != nil`

**Comment by ericlagergren** [comment]
See: https://golang.org/doc/faq#nil_error
