### ISSUE TITLE
Casting does not work properly for map[string]string with encoding/json

### ISSUE THREAD

**Issue by mandeepbrar** [golang/go#35214]
### Go version: latest. The bug is reproducible on go playground

<pre>
$ go version
1.13.2. The bug is reproducible on go playground
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

Playground environment of 1.13.2

</pre></details>

### What did you do?

Assign an empty map[string]string to interface. Then decode json into map[string]string. It does not work. https://play.golang.org/p/wJ5o6R5YoiV

### What did you expect to see?

Casting working correctly. The interface reports reflect.Type as map[string]interface{} after decoding by json is complete.

### What did you see instead?

Empty map. The type of the object is changed from map[string]string to map[string]interface{} after decoding

**Comment by ianlancetaylor** [comment]
JSON decoding is based on the type of the value passed.  You are passing a value of type `*interface{}`.  If you want a `map[string]string`, then pass a `*map[string]string`.

https://play.golang.org/p/j668DEGOkck

Closing because this is working as expected.
