### ISSUE TITLE
runtime: "morestack on gsignal" on linux-arm64-packet builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#35235]
A mysterious error on the `linux-arm64-packet` builder https://build.golang.org/log/7b87e729fd62b071ed8bd6b8c709bd41a7d13e23:
```
fatal: morestack on gsignal
FAIL	os	0.111s
```

I've only seen the one failure so far, so I'm not sure whether it's related to the various changes in 1.14.

CC @aclements @ianlancetaylor @danscales

**Comment by ianlancetaylor** [comment]
Well that is an unhelpful error message.

One way to tackle this might be to add a `go:nosplitrec` annotation.  Even a version of that that reported any callees that were not `go:nosplit` would help.

**Comment by cherrymui** [comment]
The signal stack has large stack bounds, and it should be ok to call split-stack functions, as it will pass the stack bound check and not call morestack.

My experience is that this is probably some kind of mismatch between the G and the SP. The stack bound check fails because we're actually not on that stack.

**Comment by ianlancetaylor** [comment]
Ah, right, thanks.

**Comment by cherrymui** [comment]
Hmmm. The stack trace looks like that this is failing from code that added in CL 202759. It looks like `g.m.gsignal` is not nil but its stack is 0? I'll look into it.

**Comment by danscales** [comment]
Unfortunately, I am synced past 758eb02  (i'm at 59a6847039, which is at least Oct 26th).  But on the other hand, #34391 looks like it is a hang, whereas the thing that I'm running into is a SEGV.

**Comment by cherrymui** [comment]
```
diff --git a/src/runtime/proc.go b/src/runtime/proc.go
index 60a15c1e9c..2c50a08b1d 100644
--- a/src/runtime/proc.go
+++ b/src/runtime/proc.go
@@ -1190,6 +1190,7 @@ func mexit(osStack bool) {
 	// Free the gsignal stack.
 	if m.gsignal != nil {
 		stackfree(m.gsignal.stack)
+		m.gsignal = nil
 	}
 
 	// Remove m from allm.

```

Does this patch fix it? I need to leave for a while now. I'll send a CL when I come back, if this works. Thanks!

**Comment by danscales** [comment]
@cherrymui  Yes, that changed fixed the SEGV.  Just ran 100 times on linux-arm64-packet with that change with no SEGV and no repro of the "morestack on signal" issue.

**Comment by cherrymui** [comment]
Thanks, @danscales ! Sent CL http://golang.org/cl/204158 .
