### ISSUE TITLE
net: why not provide function net.ResolveAddr(network, address string) (net.Addr, error)

### ISSUE THREAD

**Issue by tensorchen** [golang/go#35244]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/niaoge/Library/Caches/go-build"
GOENV="/Users/niaoge/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY="git.code.oa.com"
GONOSUMDB="git.code.oa.com"
GOOS="darwin"
GOPATH="/Users/niaoge/go"
GOPRIVATE="git.code.oa.com"
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/Cellar/go/1.13.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/86/5sbq0ft51h3d1hv9c4g2mfym0000gn/T/go-build337064976=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```go
	var addr net.Addr
	switch node.Network {
	case "tcp", "tcp4", "tcp6":
		addr, _ = net.ResolveTCPAddr(node.Network, node.Address)
	case "udp", "udp4", "udp6":
		addr, _ = net.ResolveUDPAddr(node.Network, node.Address)
	}
	msg.WithRemoteAddr(addr)
```

### What did you expect to see?

```go
	addr, _ := net.ResolveAddr(node.Network, node.Address)
	msg.WithRemoteAddr(addr)
```

### What did you see instead?

**Comment by tensorchen** [comment]
The code involved above is the real code that implements the network framework within my company. This code happens before Dial or ListenPacket, when the network type is unknown, and I need to get net.Addr.

I think the net.ResolveAddr function that returns net.Addr helps users reduce the switch case code, isn't it?

**Comment by ianlancetaylor** [comment]
Thanks, but can you expand on the actual use case?  Why is the network type unknown?
