### ISSUE TITLE
x/tools/gopls: use VersionedTextDocumentIdentifier in TextEdits

### ISSUE THREAD

**Issue by stamblerre** [golang/go#35243]
See https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#versionedTextDocumentIdentifier for details.

We currently do not cache the file's version, which means that we return un-versioned TextEdits. If the state of `gopls` cache has not synced up with the client, we may edit the wrong code.

Possibly related: https://github.com/golang/go/issues/34955

**Comment by jpvillaseca** [comment]
Could it also be related to #35526?

**Comment by stamblerre** [comment]
I'm not sure, but #35526 seems like a different issue to me. It will be easier to tell with logs.
