### ISSUE TITLE
Go modules with using Github on init url causes error

### ISSUE THREAD

**Issue by jbramsden** [golang/go#35267]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jbramsden/Library/Caches/go-build"
GOENV="/Users/jbramsden/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jbramsden/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jbramsden/src/gomod/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pd/0gyhy71j73s7ph1xn_jrc7zc0000gn/T/go-build859523199=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Using the following as an example: [https://blog.golang.org/using-go-modules](https://blog.golang.org/using-go-modules)

But used my Github URL instead of example.com:
` go mod init github.com/jbramden/hello
`
Created a sub directory for world
```
 mkdir world
 cd world
```
added world.go with the following

```
package world

func World() string {
	return "world."
}
```

changed hello.go to call world using the import path as stated in the go mod init and called World().

```
package hello

import (
	"github.com/jbramsden/hello/world"
	"fmt"
)

func Hello() string {
	return fmt.Sprintf("Hello, %s", world.World())
}
```
then I run go test and I should see the test results.

### What did you expect to see?

> PASS
> github.com/jbramsden/hello       0.007s

### What did you see instead?
bash-3.2$ go test
hello.go:4:2: git ls-remote -q https://github.com/jbramsden/hello in /Users/jbramsden/go/pkg/mod/cache/vcs/c2625a56b67add752fe30dd618aa886e71e6f3a95817f75a91890900f68dacfc: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.

### What else did you try?
If I remove go.mod file and run
```
 rm go.mod
 go mod init example.com/hello
```
Then I change hello.go to have the correct path for import
`"example.com/hello/world`

And I rerun
`go test`

I get the expect results

> PASS
> example.com/hello       0.007s

I also tested this with other URLs other then github.com and it works correctly. E.G bitbucket.com

### What do you think is happening?
For Github it is expecting the code to be checked in and trying to download it. However this is working differently from any other URL.

**Comment by aofei** [comment]
So, is the [jbramsden/hello](https://github.com/jbramsden/hello) a private repo? If so, then see [golang.org/doc/faq#git_https](https://golang.org/doc/faq#git_https) as `go` said.

**Comment by jbramsden** [comment]
Hi aofei,

No jbramsden/hello is not a private repo, it does not exist in github.

**Comment by bcmills** [comment]
This appears to be due to a typo in your `go mod init` command:
> `go mod init github.com/jbramden/hello`

s/jbramden/jbramsden/ and you should be set, but please let us know if that doesn't work.
