### ISSUE TITLE
gofmt: allow newline-operator-chain

### ISSUE THREAD

**Issue by ellemlabs** [golang/go#35263]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.10 linux/amd64
</pre>

I apologize for submitting yet another go format "issue". I'm more so gauging the community on this idea. Furthermore, I ask that you understand I'm not sure if this type of code format has a proper name to it, I'm just calling it "newline-operator-chain" (in contrast to "operator-newline-chain").

...For the record the first time I saw this type of formatting was when I was using SQL Server Management Studio 2012. It had formatted its `select` statements in a similar way. Though I normally hate Microsoft's ways of doing things newline-operator chains look much cleaner. Enough talking, it's best I just show what I mean:

### operator-newline chain
```
if Variable1 == true && 
    Variable2 == 5 &&
    MakeSureICan() {

// ...
}


LotsOfArgs(myArg,
    anotherArg,
    bonusArg,
    thisArgToo())
```

### newline-operator chain
Much cleaner in my opinion.
```
if Variable1 == true 
    && Variable2 == 5
    && MakeSureICan() {

// ...
}


LotsOfArgs(myArg
    , anotherArg
    , bonusArg
    , thisArgToo())
```

### Looks cleaner, looks simpler
I believe that the newline-operator chain formatting looks niced due to the lining-up of the operators. This is nice to Go programmers like myself who are obsessed with readability. For instance, one could much understand the purpose of each argument in a faster manner when scanning through newline-operator chains as the operation is specified before the argument. Compared to operator-newline chains where the reader must look at 2 separate lines to fully understand the role an argument plays in the chain.

### Makes more mathematical sense
And I think is more suitable for the underlining "mathematical" nature of operators in the first place. A good chunk of *any* programming is math, thus any language should share as many aspects with math as possible. Forcing operator-newline chain formatting disobeys this property.

We'd see this in math:
```
   2
 + 4
 + 9
 - 1
----
  14
```

not:

```
   2 +
   4 +
   9 -
   1
----
  14
```

The latter (operator-newline) looks confusing and harder to follow, the readability is lacking. Which is why I think we need to allow the former (newline-operator) in Gofmt. 

In my opinion, I think Gofmt needs to **disallow** operator-newline to achieve the highest grade of readability.

**Comment by beoran** [comment]
The most important issue with this suggestion is that due to semicolon injection, the newline-operator form is a syntax error. So, to support this, it would require a fundamental change to the syntax of the language. This is unlikely to happen just for style reasons.

Compare (error)
https://play.golang.org/p/2KQxoKc8UK1
with (ok)
https://play.golang.org/p/3NVxFQPDTXh

**Comment by DongchengWang** [comment]
I would prefer the first one, because all lines break on some kind of "separators" such as `,` or `&&`. As for math, it isn't written vertically in codes and I read it horizontally.

```go
// looks great and consistent
u := User{  // breaks on "separator" `{`
        name: name,  // breaks on "separator" `,`
        age: age
}
```

**Comment by ianlancetaylor** [comment]
I think this was on golang-nuts too.  The suggestion is not possible as it breaks due to the language's semicolon insertion rules (https://golang.org/ref/spec#Semicolons).  I'm going to close this issue, but feel free to comment if you disagree.
