### ISSUE TITLE
cmd/gofmt: add blank line between functions

### ISSUE THREAD

**Issue by DongchengWang** [golang/go#35268]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, it does.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/wdc/snap/code/common/.cache/go-build"
GOENV="/home/wdc/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/wdc/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/wdc/文档/algorithms4/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build918630619=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

gofmt this code

```go
package main
import "fmt"
func add() {
}
func main() {
	fmt.Println("gofmt")
}
```

### What did you expect to see?

```go
package main

import "fmt"

func add() {
}

func main() {
	fmt.Println("gofmt")
}

```

### What did you see instead?

```go
package main

import "fmt"

func add() {
}
func main() {
	fmt.Println("gofmt")
}

```

**Comment by ALTree** [comment]
Thanks for the request.

This is a dup of  #22337, and the final decision was to not do this (see https://github.com/golang/go/issues/22337#issuecomment-337943177).

Closing here as a dup of #22337.

**Comment by DongchengWang** [comment]
Thank you!
