### ISSUE TITLE
cmd/go: confusing error "missing dot in first path element" when importing missing package

### ISSUE THREAD

**Issue by a8m** [golang/go#35273]
This issue was created as a follow-up to my comment in #34769 and [CL 203118].

When running `go build` on a module `foo`, that imports a local module `bar` without a package (no Go files), the returned error is:

```
build foo: cannot load bar: malformed module path "bar": missing dot in first path 
element
```

[CL 203118] changes the module importer to print more friendly error as:
```
main.go:3:8: module bar@ found (v0.0.0-00010101000000-000000000000, replaced by ../bar), 
but does not contain package
```

Full example exists here: https://github.com/a8m/go-issue-34769

----

If you ask yourself why creating a module without any Go files (the bar module), well, we tried to build a few Docker images and accidentally forgot to copy some of the Go files to the image. It took us hours to figure out what the "missing dot in first path element" means in this case.

[CL 203118]: https://go-review.googlesource.com/c/go/+/203118

**Comment by aayushrathore** [comment]
for me the issue was resolved after chaning the GOROOT environment variable from "/usr/loca/go/bin" to "/usr/local/go"

OS : Linux centos

**Comment by piotrkira** [comment]
For me `go list` in root path of project resolved issuse.

**Comment by Peakchen** [comment]
at windows，how to solve？
