### ISSUE TITLE
`err != nil` when `err == nil` with custom `error` type

### ISSUE THREAD

**Issue by jamoozy** [golang/go#35292]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 linux/amd64
</pre>
Though I think this works on all recent versions ... ?

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jamoozy/.cache/go-build"
GOENV="/home/jamoozy/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jamoozy/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/jamoozy/lib/go1.13.3"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/jamoozy/lib/go1.13.3/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jamoozy/silo/go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build549669925=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/wYWX4cDk3rc

### What did you expect to see?

I expected `err == nil` to return `true`.

### What did you see instead?

I saw `err == nil: false` in the output.  I suspect this has to do with what is mentioned in the laws of reflection: that instead of `err` having a pure `nil` value, it's pointing to the (value, type) tuple (`nil`, `*Err`).  However, I don't understand why this would be desirable.

Thank you for your time!

**Comment by gertcuykens** [comment]
Correct because, interface has type and value
https://yourbasic.org/golang/gotcha-why-nil-error-not-equal-nil

If you look at it from a interface perspective it just follows the rules as all other interfaces

**Comment by jamoozy** [comment]
Many thanks for the response!  I'm still curious why this is the desired behavior, though.  What kind of code relies on `nil` comparisons acting this way?

**Comment by ianlancetaylor** [comment]
You may want to look at #22729.

Basically, `nil` is overloaded.  It is the zero value of both pointer types and interface types (and also map, slice, function, and channel types).  It is entirely reasonable to store a `nil` pointer into a variable of interface type.  Such a value is no longer the zero value of its type, so comparing it with `nil` (this time the `nil` interface value, not the `nil` pointer value) must be false.
