### ISSUE TITLE
:dl Cannot install additional go version

### ISSUE THREAD

**Issue by trinhhunganh** [golang/go#35300]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.13.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/cybozu/Library/Caches/go-build"
GOENV="/Users/cybozu/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/cybozu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xr/wpp2qs2x07j05vpk2mdfbhjr0000gn/T/go-build018393545=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I followed this documentation here:
https://godoc.org/golang.org/dl/go1.9.3
To install additional go1.9.3

### What did you expect to see?
I expected to successfully install go1.9.3

### What did you see instead?
After running "go get golang.org/dl/go1.9.3",
I ran the next command "go1.9.3 download" and got this error:
-bash: go1.9.3: command not found

**Comment by cuonglm** [comment]
It's likely that you don't add `GOPATH/bin` to your `PATH`. You can also try:

```
"$GOPATH/bin/go1.9.3" download
```

**Comment by trinhhunganh** [comment]
@cuonglm 
Awesome, I could install go1.9.3 after adding bin to PATH.
Thanks a lot mate! I am closing this issue.
