### ISSUE TITLE
crypto/x509: Reference SubjectPublicKeyInfo in MarshalPKIXPublicKey

### ISSUE THREAD

**Issue by jsha** [golang/go#35313]
The godoc for [MarshalPKIXPublicKey](https://godoc.org/crypto/x509#MarshalPKIXPublicKey) and [ParsePKIXPublicKey](https://godoc.org/crypto/x509#ParsePKIXPublicKey) say, e.g. "ParsePKIXPublicKey parses a public key in PKIX, ASN.1 DER form." However, PKIX (RFC 5280), does not define a "public key" type. Instead, it [defines a SubjectPublicKeyInfo type](https://tools.ietf.org/html/rfc5280#page-17), which is what these methods are using. The docs should reference the more specific type name, and link straight to the RFC 5280 documentation for clarity.

As an aside, the [ParseECPrivateKey](https://godoc.org/crypto/x509#ParseECPrivateKey) docs incorrectly say "ParseECPrivateKey parses an EC **public** key".

If the Go team agrees this is a positive change, I'm happy to send a change.

**Comment by FiloSottile** [comment]
Thanks, please do send a CL and add me as a reviewer.
