### ISSUE TITLE
wiki/CodeReviewComments: change "ImportBlank" to "Import Blank"

### ISSUE THREAD

**Issue by ZYunH** [golang/go#35319]
Now i revert my change. Very sorry for this stupid thing.
Maybe we could leave a blank between import and Blank, in https://github.com/golang/go/wiki/CodeReviewComments

**Comment by ZYunH** [comment]
I think i have no authority to do that before, but i do the wrong thing, sorry.

**Comment by ZYunH** [comment]
Now i revert my change.  Very sorry for this stupid thing. 
Maybe we could leave a blank between `import` and `Blank`, in https://github.com/golang/go/wiki/CodeReviewComments

**Comment by FiloSottile** [comment]
Yep, that would be more consistent. Done and added to the table at the beginning. Thanks for opening an issue.
