### ISSUE TITLE
cmd/cgo: TestManyCalls test broken on s390x builder

### ISSUE THREAD

**Issue by ALTree** [golang/go#35327]
Since [CL 204957](https://go-review.googlesource.com/c/go/+/204957), the linux-s390x builder has been broken on the `TestManyCalls` test, with the following error:

```
##### ../misc/cgo/testcarchive
--- FAIL: TestManyCalls (1.11s)
    carchive_test.go:861: 
    carchive_test.go:862: exit status 160
FAIL
2019/11/02 21:55:39 Failed: exit status 1
```

example log: https://build.golang.org/log/bf247ab7fe8fc203475857c59c53d38f640bd033

cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Whoops, sorry about that.  Thanks for filing the issue.
