### ISSUE TITLE
spec: document "internal" in import paths

### ISSUE THREAD

**Issue by seebs** [golang/go#35332]
### What version of Go are you using (`go version`)?

1.13

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

Read two things:
https://golang.org/cmd/go/#hdr-Internal_Directories
https://golang.org/ref/spec

### What did you expect to see?

The spec documenting the expected/required behavior or rules about how the behavior happens.

### What did you see instead?

No mention of this.

Honestly maybe that's okay, but usually if I want to know about things that behave a lot like language features, like "a way to make a symbol visible to other code without exporting it to other users", I'd assume they'd be in the language spec. At the very least, I think maybe the spec should at least indicate that it's a common implementation trait to assign special meanings to specific paths, like "internal"?

(Honestly, the "implementation-dependent" thing seems like it opens a can of worms; I might want to be in the category C calls "implementation-defined", which is to say, it may vary between implementations, but they're required to fully describe their choices, except it's hard to see how that would be enforced...)

**Comment by mvdan** [comment]
The spec doesn't contain `GOPATH`, modules, vendoring, `*_test.go` files, `...` package patterns, nor many other details of the tooling and build system that don't concern the language spec. Why should internal packages be any different? :)

**Comment by seebs** [comment]
Good question.

One of the open and unanswered questions about the spec is: Is the intent to be sufficient that Go *programs* be portable between implementations, or just to specify the meaning of the code without getting into how we know which code is executed? For instance, the spec doesn't actually tell you that you can't just have multiple packages in a directory, and doesn't make it clear that "files in different directories with the same package name" means "different packages" rather than "a fatal error".

It might make sense to specify this kind of thing (and the _test stuff, and the special case of the foo_test package, and other stuff like that) in a way separate from the specific implementation choices of the current golang-repo implementation. I'm... not actually sure that the "spec" is the right place, but it seems like some kind of overview of that as a statement of policy/standards/expected-behavior, distinct from the current implementation, might make it easier to have confidence in compatibility between implementations.

I'm less sure than I was when I originally filed this that this specific should be in the spec, but I'm more sure that a lot of these things should have a specification *somewhere* that isn't just the current implementation docs.

**Comment by bcmills** [comment]
> I'm more sure that a lot of these things should have a specification somewhere that isn't just the current implementation docs.

We agree with that part. That's planned as part of #33637.

**Comment by ianlancetaylor** [comment]
The behavior of "internal" in an import path is a feature of the go tool.  The go tool is not the only way to build Go programs.  For example, some large Go programs are built using Bazel.  The Bazel build tool does not (as far as I know) provide any special behavior for "internal".  The Bazel tool also permits multiple Go packages in a single directory (they are distinguished using a file named `BUILD`).  So we should not document these features of the go tool as part of the Go language spec.  The correct place to document them is in the go tool documentation, and I hope that that is already done.

Given that, it's not clear to me that there is anything to do for the issue.  Is there?

**Comment by seebs** [comment]
... It wouldn't have occurred to me that this would vary between `go` and Bazel. Nevermind, then, I think this is already adequately documented where it needs to be. Thanks!
