### ISSUE TITLE
cmd/go: env -w with bad GOPATH makes go env unusable

### ISSUE THREAD

**Issue by xlionet** [golang/go#35338]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.13
</pre>

### Does this issue reproduce with the latest release?

not sure

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go: GOPATH entry cannot start with shell metacharacter '~': "~/go"
</pre></details>

### What did you do?
```
go env -w GOPATH="~/go"
```

then

```
go env
```

### What did you expect to see?

If "~" character is not allowed, prevent me before setting may more clearly!

### What did you see instead?

`go env` is broken.

```
$ go env
go: GOPATH entry cannot start with shell metacharacter '~': "~/go"
```

**Comment by ALTree** [comment]
Thanks for reporting this.

This is another variant of #34194 (env -w wit bad GOOS/GOARCH) and #34880 (env -w with bad GO111MODULE).

**Comment by xlionet** [comment]
And how to solve this problem now, reinstall go? @ALTree

**Comment by ALTree** [comment]
> And how to solve this problem now, reinstall go? 

You can manually set GOPATH to temporarily re-enable `go env`, then use `go env -w` again (with a correct path).  So:

```
$ export GOPATH=/home/alberto/myfolder
```

now `go env` should work again, so you can do:

```
go env -w GOPATH=/home/alberto/myfolder
```

**Comment by xlionet** [comment]
Thanks brother!

**Comment by ALTree** [comment]
Even if the workaround works, we probably should fix this by preventing the setting of bad GOPATH values. Let's keep this open to track that.

**Comment by xlionet** [comment]
@xlionet ok, it couldn`t be better!

**Comment by v-i-k-r-a-m** [comment]
Well, on ubuntu you can find `env` in a folder `/home/vikram/.config/go`. Just delete it or modify it in a text editor.
