### ISSUE TITLE
x/tools/go/packages: passing NeedSyntax to Load() doesn't populate Syntax field unless NeedTypes is passed

### ISSUE THREAD

**Issue by nevkontakte** [golang/go#35331]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.10 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
 $ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/aleks/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/aleks/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build037965907=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Calling `packages.Load()` with `packages.NeedSyntax` doesn't actually populate package's `Syntax` field, unless `packages.NeedTypes` is specified at the same time. This behavior seems to contradict documentation:

>      // Syntax is the package's syntax trees, for the files listed in CompiledGoFiles.
>     //
>     // The NeedSyntax LoadMode bit populates this field for packages matching the patterns.
>     // If NeedDeps and NeedImports are also set, this field will also be populated
>     // for dependencies.
>     Syntax []*ast.File

This makes it impossible to load and parse a package without simultaneously type-checking it, which may not always be desirable.

<details><summary>Minimal example to reproduce</summary>

```go
package main

import (
        "go/token"
        "log"

        "golang.org/x/tools/go/packages"
)

func main() {
        cfg := &packages.Config{
                Mode: packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles |
                   packages.NeedImports | packages.NeedDeps | packages.NeedSyntax,
                Fset: token.NewFileSet(),
        }
        pkgs, err := packages.Load(cfg, "strconv")
        if err != nil {
                log.Fatalf("package.Load() returned error: %s", err)
                return
        }
        if count := packages.PrintErrors(pkgs); count > 0 {
                log.Fatalf("Encountered errors while loading, can't continue.")
                return
        }

        packages.Visit(pkgs, func(pkg *packages.Package) bool {
                log.Printf("Package %q has %d files parsed.", pkg, len(pkg.Syntax))
                return true
        }, nil)
}
```
</details>

### What did you expect to see?

```
 $ go run main.go
2019/11/03 19:36:07 Package "strconv" has 10 files parsed.
2019/11/03 19:36:07 Package "errors" has 1 files parsed.
2019/11/03 19:36:07 Package "internal/bytealg" has 7 files parsed.
2019/11/03 19:36:07 Package "internal/cpu" has 3 files parsed.
2019/11/03 19:36:07 Package "unsafe" has 0 files parsed.
2019/11/03 19:36:07 Package "math" has 45 files parsed.
2019/11/03 19:36:07 Package "math/bits" has 2 files parsed.
2019/11/03 19:36:07 Package "unicode/utf8" has 1 files parsed.
```

### What did you see instead?

```
 $ go run main.go
2019/11/03 19:35:26 Package "strconv" has 0 files parsed.
2019/11/03 19:35:26 Package "errors" has 0 files parsed.
2019/11/03 19:35:26 Package "internal/bytealg" has 0 files parsed.
2019/11/03 19:35:26 Package "internal/cpu" has 0 files parsed.
2019/11/03 19:35:26 Package "unsafe" has 0 files parsed.
2019/11/03 19:35:26 Package "math" has 0 files parsed.
2019/11/03 19:35:26 Package "math/bits" has 0 files parsed.
2019/11/03 19:35:26 Package "unicode/utf8" has 0 files parsed.

```

**Comment by nevkontakte** [comment]
Thanks for a super-quick fix!

**Comment by matloob** [comment]
Thanks for finding the issue!

**Comment by nevkontakte** [comment]
Looks link this is not fully fixed... In particular, mode `packages.NeedImports | packages.NeedDeps | packages.NeedSyntax` doesn't behave the way I'd expect: the Syntax field is only populated for the package itself, but not any of the dependencies.

The example in my original comment currently produces this output:

```
2019/11/23 17:41:51 Package "strconv" has 10 files parsed.
2019/11/23 17:41:51 Package "errors" has 0 files parsed.
2019/11/23 17:41:51 Package "internal/bytealg" has 0 files parsed.
2019/11/23 17:41:51 Package "internal/cpu" has 0 files parsed.
2019/11/23 17:41:51 Package "unsafe" has 0 files parsed.
2019/11/23 17:41:51 Package "math" has 0 files parsed.
2019/11/23 17:41:51 Package "math/bits" has 0 files parsed.
2019/11/23 17:41:51 Package "unicode/utf8" has 0 files parsed.
```

**Comment by nevkontakte** [comment]
I think I've found a fix (https://github.com/golang/tools/pull/189).
