### ISSUE TITLE
cmd/cgo: GNU/kFreeBSD support

### ISSUE THREAD

**Issue by oerdnj** [golang/go#3533]
<pre>What steps will reproduce the problem?
If possible, include a link to a program on play.golang.org.
1. Build on Debian GNU/KFreeBSD (amd64 or i386)
2. Run test suite

What is the expected output?
Tests run

What do you see instead?
Tests hang, the buildd kills build after 150 minutes of inactivity:
! : || { cd /build/buildd-golang_1-3-kfreebsd-amd64-BYZvvB/golang-1/src &amp;&amp;
/build/buildd-golang_1-3-kfreebsd-amd64-BYZvvB/golang-1/debian/test.bash
/build/buildd-golang_1-3-kfreebsd-amd64-BYZvvB/golang-1/pkg/tool/freebsd_amd64; }
E: Caught signal 'Terminated': terminating immediately
make[1]: *** [override_dh_auto_test] Terminated
make: *** [build-arch] Terminated
Build killed with signal TERM after 150 minutes of inactivity

Which compiler are you using (5g, 6g, 8g, gccgo)?
6g,8g

Which operating system are you using?
Debian GNU/KFreeBSD

Which version are you using?  (run 'go version')
go1 with patches to allow it to compile with GNU stack

Please provide any additional information below.
The test suite just never runs on buildd and build is killed after some minutes of
inactivity.
Full buildd logs are located here...
kfreebsd-amd64:
<a href="https://buildd.debian.org/status/fetch.php?pkg=golang&amp">https://buildd.debian.org/status/fetch.php?pkg=golang&amp</a>;arch=kfreebsd-amd64&amp;ver=2%3A1-3&amp;stamp=1334365793
kfreebsd-i386:
<a href="https://buildd.debian.org/status/fetch.php?pkg=golang&amp">https://buildd.debian.org/status/fetch.php?pkg=golang&amp</a>;arch=kfreebsd-i386&amp;ver=2%3A1-3&amp;stamp=1334366206

The patches are:
<a href="http://anonscm.debian.org/gitweb/?p=pkg-google/golang.git">http://anonscm.debian.org/gitweb/?p=pkg-google/golang.git</a>;a=blob;f=debian/patches/007-use_native_dynamic_linker_on_kfreebsd.patch;h=04bf8b82007cfe65f9f3ddcd87e6539aa2a20e01;hb=HEAD
<a href="http://anonscm.debian.org/gitweb/?p=pkg-google/golang.git">http://anonscm.debian.org/gitweb/?p=pkg-google/golang.git</a>;a=blob;f=debian/patches/011-__FreeBSD_kernel__.patch;h=45be34f1229c2ac40875ad3241f1d367d726173f;hb=HEAD
<a href="http://anonscm.debian.org/gitweb/?p=pkg-google/golang.git">http://anonscm.debian.org/gitweb/?p=pkg-google/golang.git</a>;a=blob;f=debian/patches/012-sigfillset_kFreeBSD.patch;h=40f01fb42b90d0dce8e9bda6ee792f1df3226d3a;hb=HEAD
<a href="http://anonscm.debian.org/gitweb/?p=pkg-google/golang.git">http://anonscm.debian.org/gitweb/?p=pkg-google/golang.git</a>;a=blob;f=debian/patches/013-kFreeBSD-AI_MASK.patch;h=e67a34058557c47bed4b840022a0d329aec0e12e;hb=HEAD

I will disable tests on KFreeBSD for now, but it is definitely worth investigating.</pre>

**Comment by denji** [comment]
```
env CGO_ENABLED=1 GOOS=freebsd GOARCH=amd64  go build -tags "sqlite redis memcache cert" -v -o gogs_bsd64
github.com/codegangsta/cli
runtime/cgo
github.com/Unknwon/cae
github.com/Unknwon/macaron/inject
github.com/Unknwon/cae/zip
gopkg.in/ini.v1
# runtime/cgo
/usr/local/Cellar/go/HEAD/libexec/src/runtime/cgo/gcc_freebsd_amd64.c:37:2: error: implicit declaration of function 'SIGFILLSET' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
/usr/local/Cellar/go/HEAD/libexec/src/runtime/cgo/gcc_freebsd_amd64.c:37:13: error: variable 'ign' is uninitialized when used here [-Werror,-Wuninitialized]
/usr/local/Cellar/go/HEAD/libexec/src/runtime/cgo/gcc_freebsd_amd64.c:32:14: note: initialize the variable 'ign' to silence this warning
```

**Comment by minux** [comment]
@denji, this issue is about cgo for GNU/kFreeBSD, and not about cross
compiling for
FreeBSD.

In general, if you want to cross compile with cgo enabled (CGO_ENABLED=1),
you need
to have a cross compiling toolchain. In your case, that means you need a
toolchain on
OS X that build binary for FreeBSD. You can't use OS X's clang to do that.

Please seek help on the golang-nuts mailing list if you have further
questions.

**Comment by micwoj92** [comment]
Development of Debian GNU/kFreeBSD has been terminated in 2023 after long stagnation, I think this issue should be closed.

https://wiki.debian.org/Debian_GNU/kFreeBSD

In case of cleanup, in source code this is mentioned only in one file: https://github.com/golang/go/blob/82c14346d89ec0eeca114f9ca0e88516b2cda454/src/make.bash#L131
