### ISSUE TITLE
net/http not reusing connections

### ISSUE THREAD

**Issue by grantstephens** [golang/go#35345]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTOS="linux"
</pre></details>

### What did you do?
```
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"time"
)

func main() {
	url := "https://jsonplaceholder.typicode.com/posts/1"
	n := 5

	client := http.DefaultClient

	d1 := run(client, url, n, false)
	d2 := run(client, url, n, true)

	fmt.Printf("Without drain (x%d): %v\n", n, d1)
	fmt.Printf("   With drain (x%d): %v\n", n, d2)
}

func run(client *http.Client, url string, n int, drain bool) time.Duration {
	var total time.Duration
	for i := 0; i < n; i++ {
		start := time.Now()
		resp, err := client.Get(url)
		if err != nil {
			panic(err)
		}
		dec := json.NewDecoder(resp.Body)
		var body map[string]interface{}
		if err := dec.Decode(&body); err != nil {
			panic(err)
		}
		timing := time.Since(start)
		total += timing

		if drain {
			io.Copy(ioutil.Discard, resp.Body)
		}
		resp.Body.Close()
	}
	return total
}
```
Thanks to https://github.com/kevin-cantwell/tcpdraintest for this code.
This was an issue back in 2016 and works as expected when it was fixed in v1.7, which I confirmed, however on 1.13.1 it seems to be broken again.

### What did you expect to see?

I expected the two timing values to be the same.

### What did you see instead?

The timing with the drain enabled is faster, hinting at the fact that connections are not being reused.

**Comment by philpearl** [comment]
I'm not sure this is a good test. If I run the drain and non-drain cases in the opposite order I get the opposite result. If I run the test 10 times in a row I get all sorts of results
```
Without drain (x5): 128.390213ms
   With drain (x5): 481.110045ms
Without drain (x5): 89.796921ms
   With drain (x5): 78.266854ms
Without drain (x5): 85.798968ms
   With drain (x5): 56.460874ms
Without drain (x5): 107.717206ms
   With drain (x5): 118.030613ms
Without drain (x5): 47.75821ms
   With drain (x5): 49.553154ms
Without drain (x5): 43.367152ms
   With drain (x5): 47.915857ms
Without drain (x5): 53.269977ms
   With drain (x5): 45.255463ms
Without drain (x5): 72.426393ms
   With drain (x5): 49.174936ms
Without drain (x5): 47.63105ms
   With drain (x5): 65.232225ms
Without drain (x5): 48.319105ms
   With drain (x5): 54.138906ms
```

```go
	for i := 0; i < 10; i++ {
		d2 := run(&http.Client{}, url, n, true)
		d1 := run(&http.Client{}, url, n, false)

		fmt.Printf("Without drain (x%d): %v\n", n, d1)
		fmt.Printf("   With drain (x%d): %v\n", n, d2)
	}
```

**Comment by grantstephens** [comment]
Hmm, OK, must be something else then. Thank you.
