### ISSUE TITLE
WebAssembly example not work on browser on phone

### ISSUE THREAD

**Issue by lucklove** [golang/go#35341]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/joshua/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/joshua/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pb/ssv6rnq92pn_l3c9gr9rd1g80000gn/T/go-build378228854=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
As [this page](https://github.com/golang/go/wiki/WebAssembly#getting-started) shows, but change the code to:
```golang
package main

import "fmt"
import "syscall/js"

func main() {
	fmt.Println("Hello, WebAssembly!")
	js.Global().Get("document").Call("write", "Hello, WebAssembly!")
}
```

### What did you expect to see?
"Hello, WebAssembly!"

### What did you see instead?
nothing

**Comment by lucklove** [comment]
Maybe related: https://github.com/golang/go/issues/27462

**Comment by smasher164** [comment]
I am unable to reproduce this behavior.
Are you sure you are using the appropriate wasm_exec.js with
```
$ cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" .
```

**Comment by lucklove** [comment]
@smasher164 yes, I did copy coreect wasm_exec.js

**Comment by agnivade** [comment]
Please use 1.13.4 and let us know if you still see issues.

**Comment by lucklove** [comment]
@agnivade not work still
![image](https://user-images.githubusercontent.com/8718109/68184128-2e393d00-ffd9-11e9-9e24-99072eef34e5.png)

**Comment by agnivade** [comment]
Would you be able to provide the console logs from the phone ? That would be very helpful in debugging this.

**Comment by smasher164** [comment]
Could you also list your phone's OS/Browser version? For instance, I tested on iPhone X, iOS 13.1.13, Chrome 77.0.3865.103. Thanks

**Comment by lucklove** [comment]
Sorry, @agnivade , @smasher164 , my mistake, it's not chrome, it's my phone's builtin browser. This error is from safari on iPhone(my friends's phone):
![image](https://user-images.githubusercontent.com/8718109/68264345-8167ca00-0083-11ea-80ff-dab12208d6f5.png)

**Comment by lucklove** [comment]
The chrome works correctly

**Comment by agnivade** [comment]
The index.html file that you are using is incorrect. Please use the file from `"$(go env GOROOT)/misc/wasm/wasm_exec.html"`

**Comment by lucklove** [comment]
@agnivade get it! thank you!
