### ISSUE TITLE
x/tools/gopls: missing unimported package candidates

### ISSUE THREAD

**Issue by muirdm** [golang/go#35359]
Repro (assuming completeUnimported=true is configured):

1. Create a new module with contents:
```go
package main

func main() {
}
```
1. Complete `rand.`. You should see suggestions from crypto/rand and math/rand.
1. Select `rand.Int` from "crypto/rand"
1. Delete line and save ("crypto/rand" import should disappear).
1. Wait a second to make sure "crypto/rand" package handle gets GC'd 😉 
1. Complete `rand.` again. Now you only see untyped completions from "crypto/rand". I expected to see typed completions from "crypto/rand" and completions from "math/rand".

See https://youtu.be/VaOs1crVI4g

/cc @stamblerre @heschik

**Comment by heschik** [comment]
When I look at logs, I see a ton of "no file for" errors, which are coming from `findFileInPackage` in `pkg.go`. Will look tomorrow.

**Comment by heschik** [comment]
...I looked a little now. The problem is that `findFileInPackage` can't find anything for `math/rand/rand.go` because it's not in the package's dependencies any more. Annoying, since I had the package to start with when I called `packageMembers`.
