### ISSUE TITLE
x/build: update linux/s390x builder to use --reverse-type flag

### ISSUE THREAD

**Issue by bradfitz** [golang/go#35360]
@mundaym, as part of #21260 and deleting some legacy code in our build system, we need to update the linux/s390x builder to use the `--reverse-type=host-linux-390x` flag instead of `--reverse=linux-s390x-ibm`.

I emailed you an updated key.

Thanks!

**Comment by mundaym** [comment]
Thanks @bradfitz. I've updated the builder and it is now running the latest stage0 using the new key.
