### ISSUE TITLE
Go mod: what is the best practice for upgrading a library from v1 to v2

### ISSUE THREAD

**Issue by ZYunH** [golang/go#35368]
As a library developer, i'm very confused about how to upgrade my library from v1 to v2. Even in the demonstration(https://github.com/rsc/quote), there are two options.

Option 1: create a directory called v2, then copy all v1 files into V2, all subsequent changes in v2 will on this directory. Now the directory structure like

-  mypackage
    - go.mod
    - api.go
    - api_test.go
    - v2
        - api.go
        - api_test.go
        - go.mod

If there is a bug-fix in v1, you can change the files in top-level directory, then tag this commit.

Note: the v2/go.mod will includes `require "github.com/foo/mypackage/v2"` instead of `require "github.com/foo/mypackage"`

Option 2: create a branch called v1, then archive v1 code in this branch. And change `require "github.com/foo/mypackage"` to `require "github.com/foo/mypackage/v2"` in go.mod(master), all subsequent changes are same as before(also in master).

If there is a bug-fix in v1, you can change the git branch to v1, and make some changes, then tag this commit.

**Comment by ianlancetaylor** [comment]
Unlike many other projects, we don't use our issue tracker for questions.  You will get better and faster answers if you ask on a forum.  Please see https://golang.org/wiki/Questions.  Thanks.
