### ISSUE TITLE
runtime: "call not at safe point" in TestDebugCall and TestDebugCallStack

### ISSUE THREAD

**Issue by bcmills** [golang/go#35376]
From the `linux-amd64-noopt` builder (https://build.golang.org/log/593395f76446a5f9a0f49547be1ee74f3c9eb40d, and many more like it):
```
--- FAIL: TestDebugCallGrowStack (0.00s)
    debug_test.go:183: call not at safe point
FAIL
FAIL	runtime	20.235s
```

CC @aclements @mknyszek @danscales

**Comment by bcmills** [comment]
Most of the other regressions on the dashboard seem to be cleared at this point, but this one is still present.
`linux-amd64-noopt`: https://build.golang.org/log/20ee0977fa1fb3ac44a45711db66f6b4b1aadb2d

**Comment by danscales** [comment]
As far as I can tell, this only shows up on linux-amd64-noopt , i.e. only for non-optimized code.

**Comment by ianlancetaylor** [comment]
Running

    go test -gcflags="-N -l" -test.run=TestDebugCallGrowStack -test.count=100 runtime

produced 12 test failures on my laptop.

**Comment by ianlancetaylor** [comment]
The other `TestDebugCall` tests also fail intermittently.
