### ISSUE TITLE
x/tools/gopls: redundant import name added

### ISSUE THREAD

**Issue by muirdm** [golang/go#35397]
Steps to reproduce:

Starting with:
```go
package main

import "os/exec"

func main() {
	exec.CommandContext()
}
```

1. Complete at `CommandContext(<>)` and select "context.Background"
1. I expect to get an import for `"context"`, but I get `context "context"` (redundant alias).

![alias](https://user-images.githubusercontent.com/11356572/68319866-db609380-0073-11ea-9e27-70bf7b8da5d3.gif)

Also note that it says `from "context"` in the candidate description although it is not required in this case.

/cc @stamblerre @heschik

**Comment by heschik** [comment]
Silly mistake, thanks for the report. Why do you say that `from "context"` isn't necessary? It's adding a new import and I think the user should know what it is. They could have multiple context packages, or be missing the one they actually want.

**Comment by muirdm** [comment]
>  Why do you say that from "context" isn't necessary? 

In this case I happen to know that I'm getting completions from the package of the function parameter (i.e. "context"), so there is only one possibility. But you bring up a good point that there is no existing import so the user normally can't/won't.

**Comment by heschik** [comment]
That would be true in some cases, but not this one. context.Context is an interface, so I was also getting completions from x/net/context, for example. I think it's probably healthy to show it unconditionally, FWIW.
