### ISSUE TITLE
MapIndex zero value

### ISSUE THREAD

**Issue by antonmedv** [golang/go#35417]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/anton/Library/Caches/go-build"
GOENV="/Users/anton/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/anton/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/anton/.go/src/github.com/KosyanMedia/delta/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jz/2vkj2mlx1kl_mkbp2y41sxcr0000gn/T/go-build738679845=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
Try to get zero value out of map.

### What did you expect to see?
Zero value.

### What did you see instead?
panic.

I'm trying to get values from a map using reflection. If there is no key in a map `MapIndex` should return zero value (as in documentation), but instead, I get invalid value.

https://play.golang.org/p/bMTEy6vQVKL
```go
package main

import (
	"fmt"
	"reflect"
)

func main() {
	m := map[string]string{}
	v := reflect.ValueOf(m)

	value := v.MapIndex(reflect.ValueOf("miss"))
	if value.IsValid() && value.CanInterface() {
		i := value.Interface()
		fmt.Printf("1: %#v", i)

	}

	// Workaround to get zero value.
	elem := reflect.TypeOf(m).Elem()
	i := reflect.Zero(elem).Interface()
	fmt.Printf("2: %#v", i)

	value.IsZero() // panics
}
```

**Comment by go101** [comment]
This is specified in the [docs](https://golang.org/pkg/reflect/#Value.MapIndex). `It returns the zero Value if key is not found in the map or if v represents a nil map`. Please note the capitalized `Value`, it means `reflect.Value`.

I think the design is for that the function always returns one value, so no ways to return the optional `ok` value like the non-reflection way.

**Comment by randall77** [comment]
@go101, correct. `MapIndex` returns the zero `reflect.Value` on a failed lookup, not the zero element value. That return value cannot be used in any methods except `IsValid` and `String`.

Your workaround is a proper way to get the zero element.
