### ISSUE TITLE
Why  Transport's roundTrip method can implement RoundTripper's RoundTrip method?

### ISSUE THREAD

**Issue by func90** [golang/go#35410]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.13
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you see instead?
net/http/client.go
```
type RoundTripper interface{
    RoundTrip(*Request) (*Response, error)
}
```

net/http/transport.go
```
// roundTrip implements a RoundTripper over HTTP
func (t *Transport) roundTrip(req *Request) (*Response, error){
}
```

**Comment by qingyunha** [comment]
The implement is in `roundtrip.go`.

**Comment by func90** [comment]
> The implement is in `roundtrip.go`.
thx
