### ISSUE TITLE
conflict behavior when comparing nil and (*SturctName)(nil)

### ISSUE THREAD

**Issue by t57root** [golang/go#35413]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build223059799=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
package main
import (
    "fmt"
)
type A struct {
}
func (a *A) Error() string {
    return "A"
}
func t() *A {
    return nil
}
func fun1 () {
    var a error

    a = (*A)(nil)
    fmt.Printf("%#v\n", a)
    if a == nil {
        fmt.Printf("nil#1.1\n")
    }
   if a == (*A)(nil) {
       fmt.Printf("nil#1.2\n")
   }

    a = t()
    fmt.Printf("%#v\n", a)
    if a == nil {
        fmt.Printf("nil#2.1\n")
    }
   if a == (*A)(nil) {
       fmt.Printf("nil#2.2\n")
   }
}
func fun2() {
    var a *A

    a = (*A)(nil)
    fmt.Printf("%#v\n", a)
    if a == nil {
        fmt.Printf("nil#1.1\n")
    }
   if a == (*A)(nil) {
       fmt.Printf("nil#1.2\n")
   }

    a = t()
    fmt.Printf("%#v\n", a)
    if a == nil {
        fmt.Printf("nil#2.1\n")
    }
   if a == (*A)(nil) {
       fmt.Printf("nil#2.2\n")
   }
}
func main() {
    fmt.Printf("* fun1\n")
    fun1()
    fmt.Printf("* fun2\n")
    fun2()
    if nil == (*A)(nil) {
        fmt.Printf("equal\n")
    }
}
</pre>

### What did you expect to see?

<pre>
* fun1
(*main.A)(nil)
nil#1.1
nil#1.2
(*main.A)(nil)
nil#2.1
nil#2.2

* fun2
(*main.A)(nil)
nil#1.1
nil#1.2
(*main.A)(nil)
nil#2.1
nil#2.2

equal
</pre>

### What did you see instead?
<pre>
* fun1
(*main.A)(nil)
nil#1.2
(*main.A)(nil)
nil#2.2

* fun2
(*main.A)(nil)
nil#1.1
nil#1.2
(*main.A)(nil)
nil#2.1
nil#2.2

equal
</pre>

**Comment by go101** [comment]
This is not a bug. It is a confusion many new gophers may hit.
https://golang.org/doc/faq#nil_error
https://github.com/golang/go/issues/35292
https://github.com/golang/go/issues/28133
https://go101.org/article/nil.html
https://go101.org/article/interface.html
