### ISSUE TITLE
go mod incorrectly attributes latest tag to wrong version

### ISSUE THREAD

**Issue by zhilingc** [golang/go#35415]
### What version of Go are you using (`go version`)?
1.13.1

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
</pre></details>

```
GOARCH="amd64"
GOOS="darwin"
```

### What did you do?
`go get repository` (defaulting to `@latest`) getting an older version than what is available.

specifically, 
```
$ go get github.com/gojek/feast

$ cat go.mod

module github.com/zhilingc/test

go 1.13

require github.com/gojek/feast v0.1.8 // indirect

```

### What did you expect to see?
The latest version is tagged `0.3.0-alpha`, and should be the version I am getting.

`0.3.0-alpha` is valid semver and IS greater than `0.1.8`, which is retrieved instead.
```
package main

import "fmt"
import "golang.org/x/mod/semver"

func main() {
    fmt.Println(semver.IsValid("v0.3.0-alpha")) // true
    fmt.Println(semver.Max("v0.1.8", "v0.3.0-alpha")) // v0.3.0-alpha
}
```

**Comment by psampaz** [comment]
v0.3.0-alpha is a pre-release version. According to https://blog.golang.org/publishing-go-modules:

> Normal releases are preferred by the go command over pre-release versions, so users must ask for pre-release versions explicitly (for example, go get example.com/hello@v1.0.1-alpha) if your module has any normal releases.

More details here:
https://golang.org/cmd/go/#hdr-Add_dependencies_to_current_module_and_install_them

**Comment by zhilingc** [comment]
Ugh, okay. Thanks.
