### ISSUE TITLE
x/arch/armasm: thumb1/2 decoder not implemented

### ISSUE THREAD

**Issue by DKingCN** [golang/go#35416]
Thumb decoder is not implemented in armasm package, throwing errMode: `unsupported execution mode`. 

Please consider implementing it. No other package in the wild is usable. Thanks.

**Comment by bcmills** [comment]
CC @cherrymui @dianhong01 @zhangfannie

**Comment by zhangfannie** [comment]
Yes, the current disassembler does not support thumb mode, but the current assembler does not generate thumb code. Therefore, if go code links the thumb native code, you can use binutils objdump to decode the program.
@DKingCN Could you show me the scenario where you use the thumb decoder?

**Comment by DKingCN** [comment]
I am writing a tool that parses DWARF info in elf files and decode function body so I could perform instructions filtering on it. In most case it would be binaries on android.

objdump will work altho it's the last thing I would try. Thanks for your information.
