### ISSUE TITLE
reflect: type of an interface is nil

### ISSUE THREAD

**Issue by kindermoumoute** [golang/go#35427]
I am trying to understand why this code works:

```go
ioReaderType := reflect.ValueOf(struct{ ioReader io.Reader }{}).FieldByName("ioReader").Type()
fmt.Println(ioReaderType.String()) // prints "io.Reader"
```

But this one panic

```go
ioReaderType := reflect.TypeOf(io.Reader(nil))
fmt.Println(ioReaderType.String()) // panic
```

https://play.golang.org/p/F2ndRax1f4E

**Comment by randall77** [comment]
From the doc of `reflect.TypeOf`:

> TypeOf returns the reflection Type that represents the dynamic type of i. If i is a nil interface value, TypeOf returns nil.

`io.Reader(nil)` is a nil interface value. Casting`nil` to an interface type is still nil.

See the example for `reflect.TypeOf`. You want to instead do:

`reflect.TypeOf((*io.Reader)(nil)).Elem()`

Casting a `nil` *pointer* to an interface type is not nil.
