### ISSUE TITLE
inconsistent behavior of return types mixed with defer

### ISSUE THREAD

**Issue by petar-dambovaliev** [golang/go#35420]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="linux"
</pre></details>

### What did you do?

Here, we change the value of `i` through the pointer
It returns **1**, which kind of makes sense
```
func a() *int {
	i := new(int)
	defer func(){
		 *i = 1
	}()
	*i = 42
	return i
}
```

Here, we change the value of `i`  as a regular integer value
It returns **42**, it is a little bit weird
I guess the invocation of return copies `i` at that point that ignores
what happens to it later
```
func b() int {
	var i int
	defer func(){
		 i = 1
	}()
	i = 42
	return i
}
```

**Now this gets really weird**

We have defined `i` in the signature of the function
It is an integer value, as the example above
but this time the value of `i` is not **42**, it is **1**
which goes the opposite of the example above
```
func c() (i int) {
	defer func(){
		 i = 1
	}()
	i = 42
	return i
}
```

`i` is again defined in the signature of the function
at the end we return a **5** literal but the result of 
the function is **1**, which makes no sense
```
func d() (i int) {
	defer func(){
		 i = 1
	}()
	i = 42
	return 5
}

```

**Comment by randall77** [comment]
This is all intended behavior.

You're right, `return x` evaluates `x` and makes it the return value of the function. Any further modification of `x` is irrelevant.
When the return value is declared as `(i int)`, that provides a variable which *is* the return value, which can be modified during a defer (as well as during the normal body).

FYI, in example `c` and `d`, you don't need to `return i` or `return 5`, you can just `return`. That makes it clearer that the final value of the `i` variable is the return value.

**Comment by petar-dambovaliev** [comment]
> This is all intended behavior.
> 
> You're right, `return x` evaluates `x` and makes it the return value of the function. Any further modification of `x` is irrelevant.
> When the return value is declared as `(i int)`, that provides a variable which _is_ the return value, which can be modified during a defer (as well as during the normal body).
> 
> FYI, in example `c` and `d`, you don't need to `return i` or `return 5`, you can just `return`. That makes it clearer that the final value of the `i` variable is the return value.

The last two examples, it's about what I need but more of why that is possible.
Don't tell me that when I return a constant and get something else is normal. If it was intended, it's pretty weird. I think these names returns should be removed from the language. They don't provide anything except weird behavior and bugs.

**Comment by randall77** [comment]
I agree that it isn't normal. But it is the only way that a `defer` can change the function's result.
If we removed named returns, we'd have to invent some other way to do that (or remove the possibility of a `defer` changing the return value altogether).
