### ISSUE TITLE
x/mobile: gomobile bind does not work with cgo and android

### ISSUE THREAD

**Issue by anjmao** [golang/go#35426]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/anjmao/Library/Caches/go-build"
GOENV="/Users/anjmao/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/anjmao/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p8/5ggx21z124n8kxx2wfv674380000gp/T/go-build165303278=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I have this simple test package with cgo and I'm building it for android with android-ndk-r20.

```go
package test

// #include <stdlib.h>
import "C"

type cCharPointer struct {
	Ptr *C.char
}

func Hello() string {
	return "hi"
}
```

Build:
```sh
gomobile bind -o App.aar -target=android $GOPATH/mobile/test
```

### What did you expect to see?
No error. Note that:

1. It works if I specify ios target.
2. It works for both android and ios if cgo is not used.
3. It works with cgo for older gomobile version. Tested with this [commit](https://github.com/golang/mobile/commit/a27dd33d354d004b2de14a791df5af8a00f68b8e)

### What did you see instead?

Error:
```sh
gomobile: /Users/anjmao/go/bin/gobind -lang=go,java -outdir=/var/folders/p8/5ggx21z124n8kxx2wfv674380000gp/T/gomobile-work-476890504 github.com/mobile/test failed: exit status 1
[/Users/anjmao/go/src/github.com/mobile/test/test.go:4:8: could not import C (no metadata for C)]
```

**Comment by bcmills** [comment]
CC @steeve @hyangah

**Comment by anjmao** [comment]
Specifically inner gobind command fails to run gobind with these environment variables

```go
GOOS=android CGO_ENABLED=1 gobind -lang=go,java -outdir=./build/bind $GOPATH/mobile/test
```

I installed go std library for cgo with

```sh
TOOLCHAIN=/usr/local/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64
ARCH=armv7a
export AR=$TOOLCHAIN/bin/$ARCH-linux-android-ar
export AS=$TOOLCHAIN/bin/$ARCH-linux-android-as
export CC=$TOOLCHAIN/bin/$ARCH-linux-androideabi28-clang
export CXX=$TOOLCHAIN/bin/$ARCH-linux-androideabi28-clang++
export LD=$TOOLCHAIN/bin/$ARCH-linux-android-ld
export RANLIB=$TOOLCHAIN/bin/$ARCH-linux-android-ranlib
export STRIP=$TOOLCHAIN/bin/$ARCH-linux-android-strip

GOOS=android GOARCH=arm CGO_ENABLED=1 go install std
```

It would be awesome if some of you @steeve @hyangah could check if gomobile + latest android ndk + clang + cgo works for you.

**Comment by anjmao** [comment]
I found the problem. My command was missing GOARCH env variable. Full command should be

```sh
GOOS=android GOARCH=arm CGO_ENABLED=1 gomobile bind ...
```

**Comment by anjmao** [comment]
One thing I don't like is that I get this error `could not import C (no metadata for C)` even If I provide wrong CC env variable, for example setting it to CC=no-such-binary. Maybe it make sense to create separate issue for improvements validating passed env variables when using cgo as it can get really annoying then dealing with these issues.

/CC @bcmills

**Comment by zongquan** [comment]
My build environment has encountered the same problem, and trying to change the any version of Go can't be solved.

**Comment by JasonHonor** [comment]
Me too, anyone can help me ?

**Comment by bbadbeef** [comment]
> Me too, anyone can help me ?

me too. have you solve it yet?

**Comment by steeve** [comment]
Don't remember to set `CGO_ENABLED=1`

**Comment by bbadbeef** [comment]
> Don't forget to set `CGO_ENABLED=1`

I set CGO_ENABLED=1 and still get this error.
use this command :
GOOS=android GOARCH=arm CGO_ENABLED=1 gomobile bind -target=android

**Comment by bbadbeef** [comment]
i use an older version of gomobile and it works ok with cgo

**Comment by bestbug456** [comment]
@bbadbeef which version did you use?

**Comment by bbadbeef** [comment]
> @bbadbeef which version did you use?

92f3b9c works ok, the older versions are not

**Comment by cswxzx** [comment]
> > Me too, anyone can help me ?
> 
> me too. have you solve it yet?

**Comment by bestbug456** [comment]
Guys for you information for android I've start using this docker images which works fine: openpriv/android-go-mobile at the moment is updated at 10 Jul 2018.

**Comment by bbadbeef** [comment]
my go function have c type param and return value, can it be supported with gomobile?
