### ISSUE TITLE
net/http: TestLinuxSendfile failing on mips64

### ISSUE THREAD

**Issue by bcmills** [golang/go#35423]
`linux-mips64-rtrk` (https://build.golang.org/log/08c75d4dfe5a50784afe5f032e5510cdc2e4ec8f):
```
--- FAIL: TestLinuxSendfile (0.37s)
    fs_test.go:1165: no sendfile system call found in:
        [pid 11110] +++ exited with 0 +++
        [pid 11106] +++ exited with 0 +++
        [pid 11109] +++ exited with 0 +++
        [pid 11108] +++ exited with 0 +++
        [pid 11107] +++ exited with 0 +++
        +++ exited with 0 +++
FAIL
FAIL	net/http	19.315s
```

See previously #18008.

CC @bradfitz @cherrymui @bogojevic @milanknezevic

**Comment by cherrymui** [comment]
Does the builder has 64-bit user space? As seen in #18008, the strace command that is not using 64-bit ABI may not work.

**Comment by milanknezevic** [comment]
@cherrymui The builder has 32-bit user space.

**Comment by milanknezevic** [comment]
@cherrymui @bradfitz The solution could be to modify the test to check if "n64:sendfile" syscall is used on mips64. Is that ok?

**Comment by cherrymui** [comment]
I think I tried that in https://github.com/golang/go/issues/18008#issuecomment-262126140

That was a few years ago. Things may be different now.

**Comment by cherrymui** [comment]
Ok, apparently now we no longer match the arguments, so this may work.
