### ISSUE TITLE
cmd/compile: compilation of Go 1.13 package fails when importing exported interface type with overlapping methods from Go 1.14 package

### ISSUE THREAD

**Issue by mdempsky** [golang/go#35437]
At https://github.com/golang/go/issues/6977#issuecomment-551272351, @bcmills says this should work:

```
$ cat a.go
package a

type a1 interface { A() }
type a2 interface { A() }
type A interface { a1; a2 }

$ cat b.go
package b

import "./a"

var _ a.A

$ go tool compile -lang=go1.14 a.go
$ go tool compile -lang=go1.13 b.go
/tmp/zz/a.go:5:24: duplicate method A
```

**Comment by bcmills** [comment]
CC @griesemer

**Comment by mdempsky** [comment]
Relatedly, `type A = interface { a1; a2 }` should also be okay: https://github.com/golang/go/issues/6977#issuecomment-551281633

**Comment by mdempsky** [comment]
I think adding something like `case t.Pkg != nil && t.Pkg != localpkg: return` to the switch in `addMethod` in `expandiface` should work. That should suppress duplicate method errors for imported interface types.

**Comment by griesemer** [comment]
When compiling a Go 1.13 package, shouldn't we fail if we depend on a Go 1.14 feature?

**Comment by mdempsky** [comment]
> When compiling a Go 1.13 package, shouldn't we fail if we depend on a Go 1.14 feature via an import?

I'm not sure. We don't have much precedent for what it should do. For Go 1.9, we allowed a `-lang=go1.9` package to export alias types, which could then be used by `-lang=go1.8` packages. For Go 1.13, we didn't introduce any changes that could affect the type identify of exported identifiers.

I'm thinking the Go spec* needs to introduced the concept of Go language version, and it needs to be explained how differing language versions across packages should work. (* I'd also be fine with a separate document, like how the memory model is separately defined.)
