### ISSUE TITLE
Decouple static Linux binaries from libc

### ISSUE THREAD

**Issue by mcandre** [golang/go#35432]
When Go builds static Linux binaries, can these have the option of being decoupled from the specific libc implementation? I'm no kernel hacker, so I am curious if Go on Linux could be replatformed onto POSIX-standard calls moreso than any particular Linux libc interface.

Traditionally, Linux binaries have been GNU/Linux. But with the rise of alternative Linux libc implemenations (uClibC, musl, Android / Bionic, etc.), it's easy to mistakenly package a Go Linux binary in a way that other Linux users are not able to run on their particular Linux flavor. For example, Go binaries built with CentOS may run on Debian or vice-versa, but may not run on Alpine, Void Linux, OpenWrt, or busybox, as they link against different C libraries.

**Comment by randall77** [comment]
Standard Go binaries already do not use libc - they issue system calls directly.

We only use libc if you use cgo, or if you import certain packages (`net` is the common one I believe. There may be others.)

Are there specific incompatibilities you have run into? Or is this speculative?

**Comment by ianlancetaylor** [comment]
We already do this as much as possible on GNU/Linux.  I'm going to close this issue, but please comment if you have specific suggestions for things that we should change.
