### ISSUE TITLE
runtime: async preemption breaks darwin/arm

### ISSUE THREAD

**Issue by cherrymui** [golang/go#35439]
### What version of Go are you using (`go version`)?

tip (a930fede7386fd3583553b523fd6f7fa5fef1244)

### Does this issue reproduce with the latest release?

No

### What operating system and processor architecture are you using (`go env`)?

darwin/arm and darwin/arm64

### What did you do?

After async preemption is enabled, the darwin/arm64 builder starts to fail, e.g.
https://build.golang.org/log/03f727b8f91b0c75bf54ff508d7d2f00b5cad4bf

I haven't been able to get access to the builders due to the limited resource. I'll look into the failure once I get the access.

**Comment by eliasnaur** [comment]
Unfortunately, the Corellium builders have networks problem at the moment. If you have any debugging CLs you'd like me to test, please let me know. I can run the ios tests locally.

**Comment by eliasnaur** [comment]
The corellium builders are up again, so when they're through the backlog you should be able to gomote in. I've started another iOS device to speed things up.

**Comment by cherrymui** [comment]
Thanks @eliasnaur !

I was able to access the Corellium gomote and dig into what's going on. I'll send CLs shortly. It should work on darwin/arm64 now.

The problem for ARM64 doesn't seem to appear on ARM32. I couldn't access the ARM32 builder. So I still don't know if it works on ARM32.

**Comment by eliasnaur** [comment]
Very nice, thank you! Let's just submit this and see what happens. Corellium does not support arm32, so gomoting is diffcult.

**Comment by reusee** [comment]
Async preemption also causes linux/arm32 to segfault on current tip. 
uname -a: Linux OpenWrt 4.19.88 #0 SMP Fri Dec 13 11:20:09 2019 armv7l GNU/Linux
cpu info: 
processor	: 0
model name	: ARMv7 Processor rev 1 (v7l)
BogoMIPS	: 1866.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpd32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x4
CPU part	: 0xc09
CPU revision	: 1

Segfaults disappear after async preemption is disabled (GODEBUG=asyncpreemptoff=1).

**Comment by ianlancetaylor** [comment]
@reusee Can you provide more details?  The linux-arm builder seems to be working.  Thanks.

**Comment by reusee** [comment]
@ianlancetaylor It's a proxy program for internal use. I'm trying to find a reproduce program.

Sometimes it crash with 'fatal: bad g in signal handler', most times just 'Segmentation fault'.

**Comment by reusee** [comment]
I found a workaround for the segfault that is settings GOMAXPROCS to 1.

Still can't find a short reproduce. It's several thousand lines of tightly coupled codes.
