### ISSUE TITLE
This should be camelCase?

### ISSUE THREAD

**Issue by ramonmacias** [golang/go#35438]
https://github.com/golang/go/blob/953cc7490a58fa6b6e5086cc7ca2945b041c30ab/src/os/env.go#L101

I was taking a look into the os package and I find something weird, as far as I know we should use camelCase when we write the declaration of a function, but here you use Getenv instead of GetEnv, the funny thing is the next function called LookupEnv is using camelCase. Is this a mistake on the standard library or is a special case that I don't know?

Thanks

**Comment by randall77** [comment]
Yes, this is kind of unfortunate. We can't change it now, as it is exported.
(We could add GetEnv also, but it doesn't seem worth it.)

The os package to some extent, and the syscall package a lot, have weird naming conventions because at times they try to match the underlying system names.
