### ISSUE TITLE
x/tools/gopls: support cancellation

### ISSUE THREAD

**Issue by stamblerre** [golang/go#35433]
The `internal/memoize` package leaves the generator running if a context was canceled. This means that when a user is typing quickly, we can build up a lot of type-checking and analysis runs. We also don't want to return a `context.Canceled` inside of the generator, to avoid caching that error. I think that we should add support for canceling the generator to avoid this issue.

We should also consider whether or not `packages.Load` should take a context. On one hand, this is useful when a user is typing an import manually because it stops us from doing multiple `packages.Load` in rapid succession, but it also means that we might cancel a useful `packages.Load` and have to recompute it right away.

/cc @ianthehat @heschik

**Comment by heschik** [comment]
Closed in https://golang.org/cl/206879.
