### ISSUE TITLE
cmd/go: explicitly specify macOS base SDK version when compiling go binary

### ISSUE THREAD

**Issue by andybons** [golang/go#35459]
This is needed to ensure that Apple’s notarization service can check that the `go` binary is using (at minimum) the 10.9 SDK.

```
$ codesign -dvv /usr/local/go/bin/go
Executable=/usr/local/go/bin/go
Identifier=go
Format=Mach-O thin (x86_64)
CodeDirectory v=20200 size=116482 flags=0x0(none) hashes=3636+2 location=embedded
Library validation warning=OS X SDK version before 10.9 does not support Library Validation
Signature size=9042
Authority=Developer ID Application: Google, Inc. (EQHXZ8M8AV)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Oct 31, 2019 at 7:23:46 PM
Info.plist=not bound
TeamIdentifier=EQHXZ8M8AV
Sealed Resources=none
Internal requirements count=1 size=164
```

Notice `Library validation warning=OS X SDK version before 10.9 does not support Library Validation`

The SDK is not properly specified in the `go` binary:

```
$ otool -l /usr/local/go/bin/go | grep -B1 -A3 MIN_MACOS
Load command 5
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.10
      sdk n/a
```

All other binaries built with the toolchain have the correct values:

```
$ otool -l /usr/local/go/pkg/tool/darwin_amd64/vet | grep -B1 -A3 MIN_MACOS
Load command 5
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.9
      sdk 10.9
```

The fix for this will likely need to be backported. Hopefully it’s simple. 🤞 

Related issues:
+ #30488
+ #31918 
+ #34986

**Comment by andybons** [comment]
It seems that we want to specify the `-mmacosx-version-min` when compiling the `go` binary. 

#18400 is related.

**Comment by andybons** [comment]
The fact that the SDK isn’t specified in the Mach-O headers makes me wonder if the xcode toolchain we’re using to compile cgo binaries at release time may need to be updated. When I build the toolchain on a `darwin-amd64-10_11` machine, I get the same results, while when I build the toolchain locally, I get:
```
$ otool -l ../bin/go | grep -B1 -A3 MIN_MAC
Load command 5
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.10
      sdk 10.15
```
When running `xcode-select -p` on the gomote builder I get `/Library/Developer/CommandLineTools` while when I run it locally, I get `/Applications/Xcode.app/Contents/Developer`. It may be that without the full Xcode install, we won’t get the SDK version set because we don’t have the SDK installed. Yay.

@cagedmantis @toothrot @dmitshur.

**Comment by networkimprov** [comment]
cc @eliasnaur @odeke-em

**Comment by eliasnaur** [comment]
If the Go linker detects a load command in an external .o file, it will [use that](https://github.com/golang/go/blob/43ec1b12f50b9ec6edefb39a9e11226ea68d7757/src/cmd/link/internal/ld/macho.go#L394). We can't just pass `-mmacosx-version-min` to CC, because the load commands for macOS, iOS etc. are mutually exclusive. 

In internal linking mode, the Go linker [sets a default LC_VERSION_MIN_MACOSX version](https://github.com/golang/go/blob/43ec1b12f50b9ec6edefb39a9e11226ea68d7757/src/cmd/link/internal/ld/macho.go#L406). The version was bumped to 10.9 in https://go-review.googlesource.com/c/go/+/175918/.

Perhaps it's enough to update/fix the toolchain used to build Go release. However, we could also expand the linker check above ("machoPlatform == 0") to trigger when the version and sdk are less than 10.9 in external linking mode. If you do that, please keep my https://go-review.googlesource.com/c/go/+/206337 in mind to only use the macOS load command for macOS binaries.

**Comment by andybons** [comment]
@ianlancetaylor for cgo.

It may be OK to specify the `MACOSX_DEPLOYMENT_TARGET` env var when building the toolchain only and not for every cgo binary.

**Comment by networkimprov** [comment]
cc @thanm

**Comment by andybons** [comment]
Confirmed that a toolchain built using the new 10.15 builder with Xcode installed and no changes to the min deployment target gets rid of the warning from `codesign` when validating the `go` command.

```
$ codesign -dvv go/bin/go
Executable=/private/tmp/go/bin/go
Identifier=go
Format=Mach-O thin (x86_64)
CodeDirectory v=20500 size=116526 flags=0x10000(runtime) hashes=3636+2 location=embedded
Signature size=9063
Authority=Developer ID Application: Andrew Bonventre (USS93J4HN5)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Nov 21, 2019 at 7:35:42 PM
Info.plist=not bound
TeamIdentifier=USS93J4HN5
Runtime Version=10.15.0
Sealed Resources=none
Internal requirements count=1 size=164
```

The issue may or may not affect notarization, since the min SDK version is still being set to 10.10 for the `go` command no matter what builder we’re using (I was misreading the Mach-O header values above) and the minimum for notarization is 10.9. Also, the notarization service is currently not reporting any errors or warnings with the `go` binary if it’s signed, has a secure timestamp, and has the hardened runtime enabled. Whether the notarization service would throw an error with the old SDK values is up for speculation, but it’s better to be safe than sorry.

It may be fine to leave the target SDK version at the default (10.10) and not set it explicitly, but I worry about defaults changing down the road.

**Comment by andybons** [comment]
Removing release-blocker label since the default value for the base SDK is 10.10 using the 10_15 Catalina builder. Keeping open to track setting this explicitly.

**Comment by huoxingyun** [comment]
Is that the only way  to solve the problem by updating the Mac system ? @andybons

**Comment by cagedmantis** [comment]
@huoxingyun We've isolated what the fix would be and will be implementing it soon.

**Comment by belloyang** [comment]
Is there a solution to this issue?
-- Feb. 18, 2020

**Comment by toothrot** [comment]
@cagedmantis What else is needed on this issue? Should the milestone be changed to 1.15?

**Comment by ianlancetaylor** [comment]
What else needs to be done for this issue?

**Comment by jayconrod** [comment]
I believe this is resolved now, but if anyone knows differently, please reopen.

**Comment by cagedmantis** [comment]
Indeed. The work for this has been done. Thanks for closing the issue.
