### ISSUE TITLE
proposal: Go 2: allow _ to be used as an untyped variable

### ISSUE THREAD

**Issue by urandom** [golang/go#35452]
Currently, `_` is defined as a blank identifier that can be used for any type.

This proto proposal is for extending the `_` symbol to be used as an untyped variable that can be assigned to any type. The value of the constant will be the default value of the type itself.  
`_` would be a variable and not a constant in order to be used by any and all types, not just one constant types. For that reason, it also doesn't need to have a default type, although if there is a technical requirement for that, we can just pick an int as its default type.

Real life use cases for its usage would be when returning from a function:
```go
func SomeFunc(someInput int) (SomeStruct, error) {
...
    // Return a valid default value based on some input condition
    return _, _
...
    // Return the default value during error propagation, which would also make error propagation slightly easier on the fingers and eyes
    return _, err
...
}
```

Another real world example is calling a function, where some of its arguments are "optional":
```go
func SomeFunc(requiredID string, optionalName string) {
   ...
}


SomeFunc("the id", _)
```

The later use case already heavily coincides with the current usages of the blank identifier, for ignoring parts of an assignment.

**Comment by ianlancetaylor** [comment]
This looks like a dup of #19642.

**Comment by urandom** [comment]
indeed it is.
