### ISSUE TITLE
access: may-start-trybots

### ISSUE THREAD

**Issue by muirdm** [golang/go#35460]
Hello

I am requesting access to "may-start-trybots" https://go-review.googlesource.com/#/admin/groups/1030,members . My Gerrit email is muir@mnd.rs .

/cc @stamblerre

**Comment by bcmills** [comment]
Hi Muir,

Thank you for your `x/tools` contributions and for requesting Trybots access! I've added you to the `may-start-trybots` group, so you should be able to do so now.

As you've likely read at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a Trybot run.

Let us know if you have any questions or issues with it, and thanks again!
