### ISSUE TITLE
x/build/cmd/gerritbot: add magic comment or label to pause Gerritbot on a PR

### ISSUE THREAD

**Issue by bradfitz** [golang/go#35464]
When I want to take over a CL in Gerrit, I can forge the author and work in peace.

If I want to take over a CL in Gerrit that originated from Gerritbot, I need to race and get my change +2'ed and submitted before Gerritbot wakes up and overwrites my work.

I'd like to be able to leave a comment or set a label on a GitHub PR to disable Gerritbot for that PR.

/cc @andybons @dmitshur @cagedmantis @bcmills

**Comment by bcmills** [comment]
Could GerritBot just compare the timestamp of the last upload with the timestamp of the last PR update? Seems like it should only sync a PR over to Gerrit if the PR contents are newer than the latest Gerrit PatchSet.

**Comment by bradfitz** [comment]
That works too, if that's not too difficult.

**Comment by andybons** [comment]
Duplicate of #24887
