### ISSUE TITLE
runtime: TestVDSO failures on linux-arm64-packet

### ISSUE THREAD

**Issue by bcmills** [golang/go#35473]
```
--- FAIL: TestVDSO (71.53s)
    crash_test.go:95: testprog SignalInVDSO exit status: exit status 2
    crash_test.go:149: output:
        SIGQUIT: quit
        PC=0x6b4c8 m=1 sigcode=0
        
        goroutine 0 [idle]:
        runtime.usleep()
        	/workdir/go/src/runtime/sys_linux_arm64.s:148 +0x48
        runtime.sysmon()
        	/workdir/go/src/runtime/proc.go:4461 +0x9c
        runtime.mstart1()
        	/workdir/go/src/runtime/proc.go:1125 +0xb0
        runtime.mstart()
        	/workdir/go/src/runtime/proc.go:1090 +0x60
        
        goroutine 1 [running]:
        	goroutine running on other thread; stack unavailable
        
        goroutine 18 [sleep]:
        time.Sleep(0x5f5e100)
        	/workdir/go/src/runtime/time.go:247 +0xc0
        runtime/pprof.profileWriter(0x12c880, 0x40001b0018)
        	/workdir/go/src/runtime/pprof/pprof.go:765 +0x60
        created by runtime/pprof.StartCPUProfile
        	/workdir/go/src/runtime/pprof/pprof.go:750 +0x128
```

[2019-11-08T21:27:51-b7d097a/linux-arm64-packet](https://build.golang.org/log/56e305e66f6bde6b515b912e07c8a3f7f8050eab)
[2019-11-08T18:11:01-1fd3f8b/linux-arm64-packet](https://build.golang.org/log/e7305d98de0b08d01d6a7b6a0ac37b50d9cc3fb8)
[2019-11-08T16:20:17-4208dbe/linux-arm64-packet](https://build.golang.org/log/648a9deea6e8098762e95bb64ad02574f4a6e8ee)
[2019-11-07T20:34:27-4751db9/linux-arm64-packet](https://build.golang.org/log/7824a241057f781c7a4b8ce496d7f50515fe4b03)

See also #33574.

CC @ianlancetaylor @mengzhuo @nyuichi

**Comment by ianlancetaylor** [comment]
As far as I can see this means that this loop in runtime/testdata/testprog/vdso.go

```Go
	t0 := time.Now()
	t1 := t0
	for t1.Sub(t0) < time.Second {
		t1 = time.Now()
	}
```

ran for more than one minute.  Hmmm.

**Comment by ianlancetaylor** [comment]
Given that this just started to appear, I'm naturally suspicious of CL 203461 == 1b0b9809046c1862f8ea0240fe016e516c67676f.

CC @cherrymui

**Comment by cherrymui** [comment]
I think I have a guess:
- a goroutine running in VDSO. It saves the g on the signal stack before entering VDSO.
- a profiling signal comes. During the handling of the profiling signal, it calls nanotime, which saves g on the same signal stack before entering VDSO, and *clears* it after.
- while the goroutine is still in VDSO, a preemption signal comes. Now sigFetchG fetches a nil G from the signal stack (as it is cleared in the previous step), then calls badsignal, then deadlocks in lockextra (as before CL http://golang.org/cl/202759).

I think we don't want to save G if we're already on the signal stack. This seems to make it work, running 1000 iterations without failure.
