### ISSUE TITLE
runtime: TestGdb* triggers a GDB bug on the linux-mips64-rtrk builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#35475]
Several failures like this one seem to indicate that a broken `gdb` is installed on the `linux-mips64-rtrk` builder. It should either be upgraded to a fixed version, or removed (or removed from `$PATH`) so that the tests will skip.

```
--- FAIL: TestGdbPanic (3.84s)
    runtime-gdb_test.go:65: gdb version 8.2
    runtime-gdb_test.go:599: could not find '(#.* .* in )?main\.crash' in backtrace
    runtime-gdb_test.go:600: gdb output:
        Loading Go Runtime support.
        /build/gdb-XNneqN/gdb-8.2.1/gdb/mips-tdep.c:776: internal-error: bad register size
        A problem internal to GDB has been detected,
        further debugging may prove unreliable.
        Quit this debugging session? (y or n) [answered Y; input not from terminal]
        
        This is a bug, please report it.  For instructions, see:
        <http://www.gnu.org/software/gdb/bugs/>.
        
        /build/gdb-XNneqN/gdb-8.2.1/gdb/mips-tdep.c:776: internal-error: bad register size
        A problem internal to GDB has been detected,
        further debugging may prove unreliable.
        Create a core file of GDB? (y or n) [answered Y; input not from terminal]
```

Same for `TestGdbBacktrace`, `TestGdbConst`, `TestGdbAutotmpTypes`, `TestGdbPython`.

[2019-11-08T23:22:06-11da2b2/linux-mips64-rtrk](https://build.golang.org/log/839f9b1cc3cf5a336ede9d014fdfb7a790369b1c)
[2019-11-08T21:05:17-9ee6ba0/linux-mips64-rtrk](https://build.golang.org/log/ac395ddc5813096d5f55f9bd209e8eb4172f5391)

CC @bogojevic @milanknezevic

**Comment by cherrymui** [comment]
The builder has 32-bit user space. I don't think 32-bit gdb can handle 64-bit programs.

**Comment by milanknezevic** [comment]
I've build mips64 big-endian gdb and installed it onto builder and it seems that gdb tests are passing.

**Comment by cherrymui** [comment]
Thanks @milanknezevic !

I think we can close this. No more failure on dashboard now.
