### ISSUE TITLE
debug/elf: add a function to get size of ELF binary

### ISSUE THREAD

**Issue by probonopd** [golang/go#35489]
### What version of Go are you using (`go version`)?

1.13

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Linux arm64

### What did you do?

Try to find out the size of an ELF binary on disk (that has random data appended to the end of it, so I can't just use the file size)

### What did you expect to see?

A function in https://github.com/golang/go/blob/master/src/debug/elf/elf.go that would give me the size of an ELF binary on disk (based on the information in the ELF headers, not based on the size of the file). I think this functionality is basic enough to be standard library worthy.

### What did you see instead?

This functionality is seemingly not implemented there yet.

Would it be possible to add it there?

Code examples in other languages:
* [C](https://github.com/AppImage/libappimage/blob/master/src/libappimage_shared/elf.c)
* [C++](https://github.com/AppImage/libappimage/blob/master/src/libappimage/utils/ElfFile.cpp)

**Comment by agnivade** [comment]
This is a fine thing to have in a third-party library, but I don't think it needs to be in the standard library. Also see https://golang.org/doc/faq#x_in_std.

**Comment by apparluk** [comment]
_cf_: [Calculate the size of an ELF](https://forum.golangbridge.org/t/calculate-the-size-of-an-elf/16064) (Go Forum)
