### ISSUE TITLE
crypto/tls expose names for CurveID and SignatureScheme

### ISSUE THREAD

**Issue by izolight** [golang/go#35499]
The constants for CurveID and SignatureScheme don't have any String() methods.
This makes printing these values (for example in log files) awkward as there is just a number.
To workaround this one can make a map to lookup from the constants to some friendly name (the constant name). As the constants already have custom types it would be best to implement the stringer interface for them in the standard library.
The idea is similiar to #30325 
I created a first draft in  #35297

**Comment by rsc** [comment]
Adding to proposal minutes, seems headed for likely accept.

**Comment by rsc** [comment]
@katiehockman, @FiloSottile, are you in favor of this proposal?

**Comment by katiehockman** [comment]
@rsc I see no issues with doing this, and the rationale seems reasonable. The [CL for this](https://go-review.googlesource.com/c/go/+/208226/) was pretty straight-forward too.

**Comment by FiloSottile** [comment]
Same, this looks good to me.

**Comment by rsc** [comment]
Based on the discussion above, this seems like a **likely accept**.

**Comment by rsc** [comment]
No change in consensus, so accepting.
