### ISSUE TITLE
os: Open("/") fails on Windows

### ISSUE THREAD

**Issue by apmckinlay** [golang/go#35492]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\andrew\AppData\Local\go-build
set GOENV=C:\Users\andrew\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\andrew\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
</pre></details>

### What did you do?
<pre>
package main

import (
	"fmt"
	"os"
)

func main() {
	_, err := os.Open("/")
	fmt.Println(err)
}
</pre>

### What did you expect to see?

I expected it to succeed, i.e. err == nil

### What did you see instead?

It failed with:
<pre>
open /: The filename, directory name, or volume label syntax is incorrect.
</pre>

It works (err == nil) if you use a backslash:
<pre>
os.Open(`\`)
</pre>

file_windows.go openDir has:

<pre>
if len(path) == 2 && path[1] == ':' || 
	(len(path) > 0 && path[len(path)-1] == '\\') { // it is a drive letter, like C:
	mask = path + `*`
} else {
	mask = path + `\*`
}
</pre>

Since it only checks for trailing __back__ slash, for forward slash "/" it adds `\*` resulting in `/\*` which is invalid.

Obviously, the workaround is to use back slash instead of forward slash. But since forward slashes work in file paths in many/most other places, it might be worth checking for either slash in openDir.

**Comment by agnivade** [comment]
Is this a new thing, or forward slashes were always supported in Windows ?

**Comment by networkimprov** [comment]
Back- and forward-slashes have long been interchangeable on Windows.

cc @alexbrainman @mattn @zx2c4 
@gopherbot add OS-Windows

**Comment by alexbrainman** [comment]
@apmckinlay yes both / and \ should work in this situation.

Would you like to send a fix for this? This https://golang.org/doc/contribute.html is how to contribute.

Thank you.

Alex

**Comment by apmckinlay** [comment]
Sure, first time, but I’ll read the instructions.

**Comment by networkimprov** [comment]
You could post to golang-dev asking if anyone would like to implement this; that's probably the quickest path to a patch...

**Comment by mattn** [comment]
Ah, I did not read this thread. I already have my changes to fix this on my local PC. @apmckinlay do you try this soon? (please feel free to answer).

**Comment by apmckinlay** [comment]
@mattn If you have a fix already prepared that's great, go ahead. (I am travelling so I would be slow)
