### ISSUE TITLE
How to override VCS location for quirky dependencies in go.mod?

### ISSUE THREAD

**Issue by mcandre** [golang/go#35509]
Many Go libraries use a different VCS URL than the Go import path would imply, such as the /x/ libraries, the common YAML library, and any secondary forks of regular Go libraries.

For these kinds of dependencies, what is the right syntax in `go.mod` for overriding the VCS URL of the dependency?

**Comment by mvdan** [comment]
Have you tried `go mod edit -replace=old/module=github.com/you/fork`?

**Comment by thepudds** [comment]
> Many Go libraries use a different VCS URL than the Go import path would imply, such as the /x/ libraries

@mcandre This might not be helpful to answer your full question, but taking the /x/ libraries example: in the go.mod of a consumer of the /x/ libraries, the consumer uses the identity declared in the `module` line of the /x/ library of interest. For example, the golang.org/x/tools go.mod declares itself to be `module golang.org/x/tools`:

https://github.com/golang/tools/blob/master/go.mod#L1

So you would refer to it as `golang.org/x/tools` in a consumer’s go.mod file. 

In general, a module declares its identity in its go.mod via the `module` directive (e.g., a first line reading `module example.com/m` ). The go tool enforces consistency between that declared module path and the import paths used by any consumer.

This is part of how the go tool (in module mode) enforces that "import path == identity of the code" for any given package. 

If a module's go.mod file reads `module example.com/m`, then a consumer must import packages from that module using import paths that start with that module path (e.g., `import "example.com/m" `or `import "example.com/m/sub/pkg"`).

Were you hitting a specific problem?

If so, what was the specific command issued, and specific error message, if any?
