### ISSUE TITLE
x/tools/gopls: inconsistent placement of new import with local

### ISSUE THREAD

**Issue by zeebo** [golang/go#35519]
Consider a module `bug` with package `bug/bar` that exports identifier `X`. `gopls` is configured to have the local option equal to `"bug/"`. In the package `bug`, we have the source

```go
package bug

import (
	"fmt"

	"golang.org/x/tools/blog"
)

var _ = fmt.Println

type _ = blog.Config

var _ = bar.X // user has just finished typing this
```

Issuing an Organize Imports action respects the local option and leaves the import block as

```go
import (
	"fmt"

	"bug/bar"

	"golang.org/x/tools/blog"
)
```

whereas if the import for `"bug/bar"` is added through code complection, the import block will be

```go
import (
	"fmt"
	"bug/bar"

	"golang.org/x/tools/blog"
)
```

which does not respect the local option.

**Comment by heschik** [comment]
`source.addNamedImport` almost certainly needs to read the "local" configuration and does not. Not sure why we need this vs. sharing code with `source.computeImportEdits`.

**Comment by heschik** [comment]
Er...I just realized I didn't actually test this exact case. But I'm pretty sure it's fixed. If not please comment.
