### ISSUE TITLE
x/build: linux-mips* builders don't run on x/net and x/sys

### ISSUE THREAD

**Issue by tklauser** [golang/go#35529]
https://build.golang.org/?repo=golang.org%2fx%2fnet#
https://build.golang.org/?repo=golang.org%2fx%2fsys#

No builds are shown for the `linux-mips-rtrk`, `linux-mips64-rtrk`, `linux-mips64le-rtrk`, `linux-mipsle-rtrk` and  `linux-mips64le-mengzhuo` builders on master, even though the builders' corresponding policy should allow them:

https://github.com/golang/build/blob/773364d7ec5d1e0f2e7cd6698a7980beda1e577e/dashboard/builders.go#L2542-L2551

/cc @bradfitz @dmitshur @andybons

**Comment by tklauser** [comment]
#35515 related?

**Comment by bradfitz** [comment]
I suspect it's due to DisableSnapshot on those builders and coordinator not scheduling x repo work until a snapshot is available. Easy fix in coordinator.

**Comment by bradfitz** [comment]
I don't think 35515 is related.
