### ISSUE TITLE
x/tools/gopls: file changes not reflected in results

### ISSUE THREAD

**Issue by leerayven** [golang/go#35526]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.13.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ravenlli\AppData\Local\go-build
set GOENV=C:\Users\ravenlli\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\ravenlli\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ravenlli\AppData\Local\Temp\go-build991420482=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I was using vscode-go together with gopls and other go tools (all installed automatically), when I made some changes to the file inside the vscode editor, such as adding or deleting some lines, linting or auto-completion couldn't work correctly. I had to reload the window to get things right.
![image](https://user-images.githubusercontent.com/7361656/68648521-8a610b80-055b-11ea-9c74-f0e928cd0169.png)
In the above example, when my mouse cursor stops above "splitDhash", it came out the description of "blockMasks" just because I inserted an empty line at line 122.

### What did you expect to see?
Changes inside the vscode editor should be tracked.

### What did you see instead?
Changes inside the vscode editor are not tracked.

**Comment by stamblerre** [comment]
Has this happened to you more than once or was it just in this instance? If it happens often, can you share a `gopls` log from when this happens (see how to capture logs [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs)). What version of `gopls` are you using (`gopls version`)?

**Comment by leerayven** [comment]
> Has this happened to you more than once or was it just in this instance? If it happens often, can you share a `gopls` log from when this happens (see how to capture logs [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs))? What version of `gopls` are you using (`gopls version`)?

It happens often, and not only to me.

**Comment by leerayven** [comment]
It happens often, and not only to me. <pre>
$ go version
go version go1.13.4 windows/amd64
</pre>

**Comment by leerayven** [comment]
It happens often(nearly every time), and not only to me.
<pre>
$ gopls.exe version
golang.org/x/tools/gopls 0.2.0
    golang.org/x/tools/gopls@v0.2.0 h1:ddCHfScTYOG6auAcEKXCFN5iSeKSAnYcPv+7zVJBd+U=
</pre> 
some <code>gopls</code> log regarding the example <code>func splitDhash</code>:
Output</summary><br><pre>
>>

[Trace - 14:41:46.622 PM] Sending request 'textDocument/hover - (13)'.
Params: {"textDocument":{"uri":"file:///d%3A/code/goneat_video_content_sim_dhash_svr/src/streamsim/sim_handler.go"},"position":{"line":122,"character":10}}


[Trace - 14:41:46.665 PM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2019/11/13 14:41:46 38.0038ms for GOROOT=c:\\go GOPATH=D:\\code\\goneat_video_content_sim_dhash_svr;C:\\Users\\ravenlli\\go GO111MODULE= PWD=d:\\code\\goneat_video_content_sim_dhash_svr go \"env\" \"GOMOD\", stderr: \u003c\u003c\u003e\u003e stdout: \u003c\u003c\n\u003e\u003e\n"}


[Info  - 下午2:41:46] 2019/11/13 14:41:46 38.0038ms for GOROOT=c:\go GOPATH=D:\code\goneat_video_content_sim_dhash_svr;C:\Users\ravenlli\go GO111MODULE= PWD=d:\code\goneat_video_content_sim_dhash_svr go "env" "GOMOD", stderr: <<>> stdout: <<
>>

[Trace - 14:41:46.707 PM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2019/11/13 14:41:46 80.219ms for GOROOT=c:\\go GOPATH=D:\\code\\goneat_video_content_sim_dhash_svr;C:\\Users\\ravenlli\\go GO111MODULE= PWD=d:\\code\\goneat_video_content_sim_dhash_svr go \"list\" \"-m\" \"-json\" \"all\", stderr: \u003c\u003cgo list -m: not using modules\n\u003e\u003e stdout: \u003c\u003c\u003e\u003e\n"}


[Info  - 下午2:41:46] 2019/11/13 14:41:46 80.219ms for GOROOT=c:\go GOPATH=D:\code\goneat_video_content_sim_dhash_svr;C:\Users\ravenlli\go GO111MODULE= PWD=d:\code\goneat_video_content_sim_dhash_svr go "list" "-m" "-json" "all", stderr: <<go list -m: not using modules
>> stdout: <<>>

[Trace - 14:41:46.754 PM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2019/11/13 14:41:46 44.8674ms for GOROOT=c:\\go GOPATH=D:\\code\\goneat_video_content_sim_dhash_svr;C:\\Users\\ravenlli\\go GO111MODULE= PWD=d:\\code\\goneat_video_content_sim_dhash_svr go \"env\" \"GOPATH\", stderr: \u003c\u003c\u003e\u003e stdout: \u003c\u003cD:\\code\\goneat_video_content_sim_dhash_svr;C:\\Users\\ravenlli\\go\n\u003e\u003e\n"}


[Info  - 下午2:41:46] 2019/11/13 14:41:46 44.8674ms for GOROOT=c:\go GOPATH=D:\code\goneat_video_content_sim_dhash_svr;C:\Users\ravenlli\go GO111MODULE= PWD=d:\code\goneat_video_content_sim_dhash_svr go "env" "GOPATH", stderr: <<>> stdout: <<D:\code\goneat_video_content_sim_dhash_svr;C:\Users\ravenlli\go
</pre></details>

**Comment by stamblerre** [comment]
Can you please share the full `gopls` log, even if it's very long? The excerpts here are not relevant to the issue you're seeing.

**Comment by leerayven** [comment]
Here is the full <code>gopls</code> log.
[issue35526.log](https://github.com/golang/go/files/3849618/issue35526.log)

**Comment by stamblerre** [comment]
Based on your logs, it looks like `gopls` hasn't fully initialized by the time the change to the file comes in. We've recently made some changes to handle this - can you try installing `gopls` at master and reporting if you still see the same issues? To install at master, `git clone https://go.googlesource.com/tools`, cd into the `tools/gopls` directory, and run `go install`. If you still see the same issue at master, please attach the full logs.

**Comment by stamblerre** [comment]
Closing this issue as it's now almost 2 months old. @leerayven: Please open a new issue if you are still encountering problems.
