### ISSUE TITLE
runtime/pprof: panic in appendLocsForStack on linux-arm64-packet 

### ISSUE THREAD

**Issue by bcmills** [golang/go#35538]
```
panic: runtime error: slice bounds out of range [6:5]

goroutine 245 [running]:
runtime/pprof.(*profileBuilder).appendLocsForStack(0x400014d080, 0x400022e140, 0x0, 0x8, 0x40001f6568, 0x5, 0x353, 0x0, 0x4, 0x8)
	/workdir/go/src/runtime/pprof/proto.go:397 +0x5b8
runtime/pprof.(*profileBuilder).build(0x400014d080)
	/workdir/go/src/runtime/pprof/proto.go:362 +0xfc
runtime/pprof.profileWriter(0x24bd60, 0x40004bc240)
	/workdir/go/src/runtime/pprof/pprof.go:779 +0xd8
created by runtime/pprof.StartCPUProfile
	/workdir/go/src/runtime/pprof/pprof.go:750 +0x128
FAIL	runtime/pprof	4.052s
```

[2019-11-12T05:24:00-d22b573/linux-arm64-packet](https://build.golang.org/log/19d4aee46b6baabcd70ffd3f99095c586fb89a10)
[2019-11-12T01:09:31-0ee22d9/linux-arm64-packet](https://build.golang.org/log/ec31d4d0e3c976e4699229c96bd557248d286367)
[2019-11-08T18:00:31-c444ec3/linux-arm64-packet](https://build.golang.org/log/be66f69716f450aa7fdbd820126e6b266cffee7c)

CC @hyangah @randall77

**Comment by hyangah** [comment]
Using gomote, printed out the the cached location pcs and the pcs in the stack. It's flaky - all failures I got are only from TestGoroutineSwitch so far. @randall77 

<pre>
=== RUN   TestGoroutineSwitch
XXX
Cached PCs: [300657 300665 300656 300665 300656 300665]
	[{300656 <nil> runtime.nanotime /workdir/go/src/runtime/time_nofake.go 19 300416 {0x28dac8 0x386c80}}]
	[{300664 0x28dac8 runtime.checkTimers /workdir/go/src/runtime/proc.go 2623 300416 {0x28dac8 0x386c80}}]
	[{300655 <nil> runtime.nanotime /workdir/go/src/runtime/time_nofake.go 19 300416 {0x28dac8 0x386c80}}]
	[{300664 0x28dac8 runtime.checkTimers /workdir/go/src/runtime/proc.go 2623 300416 {0x28dac8 0x386c80}}]
	[{300655 <nil> runtime.nanotime /workdir/go/src/runtime/time_nofake.go 19 300416 {0x28dac8 0x386c80}}]
	[{300664 0x28dac8 runtime.checkTimers /workdir/go/src/runtime/proc.go 2623 300416 {0x28dac8 0x386c80}}]
vs New PCs: [300657 300665 300656 300665]
	[{300656 <nil> runtime.nanotime /workdir/go/src/runtime/time_nofake.go 19 300416 {0x28dac8 0x386c80}}]
	[{300664 0x28dac8 runtime.checkTimers /workdir/go/src/runtime/proc.go 2623 300416 {0x28dac8 0x386c80}}]
	[{300655 <nil> runtime.nanotime /workdir/go/src/runtime/time_nofake.go 19 300416 {0x28dac8 0x386c80}}]
	[{300664 0x28dac8 runtime.checkTimers /workdir/go/src/runtime/proc.go 2623 300416 {0x28dac8 0x386c80}}]
cached loc = 19
panic: runtime error: slice bounds out of range [6:4]

goroutine 251 [running]:
runtime/pprof.(*profileBuilder).appendLocsForStack(0x40001eef20, 0x4000454d00, 0x0, 0x8, 0x4041192478, 0x4, 0x371, 0x0, 0x6, 0x8)
	/workdir/go/src/runtime/pprof/proto.go:410 +0x8ac
runtime/pprof.(*profileBuilder).build(0x40001eef20)
	/workdir/go/src/runtime/pprof/proto.go:362 +0xfc
runtime/pprof.profileWriter(0x24be00, 0x404118aea0)
	/workdir/go/src/runtime/pprof/pprof.go:779 +0xd8
created by runtime/pprof.StartCPUProfile
	/workdir/go/src/runtime/pprof/pprof.go:750 +0x128
FAIL	runtime/pprof	31.955s
</pre>

**Comment by hyangah** [comment]
BTW, I just got an internal report on the same panic, but with linux-amd64, and with the heap profile.
