### ISSUE TITLE
CRISTIANARCIAO56

### ISSUE THREAD

**Issue by garciagonzalescristian** [golang/go#35533]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by garciagonzalescristian** [comment]
13346700!:$

**Comment by mvdan** [comment]
The issue is empty. If you want to file an issue, fill the template.
