### ISSUE TITLE
cmd/link: default to internal linking mode for PIE

### ISSUE THREAD

**Issue by cherrymui** [golang/go#35545]
When using -buildmode=pie, we used to default to internal linking mode. Then we forced external linking because internal linking was found broken. Then we fixed internal linking, but still default to external linking.

As far as I know, internal linking PIE works reasonably well, at least on Linux/AMD64 and Linux/ARM64. We may want to change the default back to internal linking mode.

**Comment by prattmic** [comment]
I saw this after filing #36028. I don't think internal linking should be enabled PIE until that is fixed, unless I'm mistaking something and it's not a common problem.

Regardless, I just sent golang.org/cl/210181 to fix that issue.
