### ISSUE TITLE
net/http/httputil: ReverseProxy - websocket connections cannot be canceled

### ISSUE THREAD

**Issue by piec** [golang/go#35559]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 linux/amd64
</pre>
(also checked master)

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Up to date Arch Linux amd64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pierre/.cache/go-build"
GOENV="/home/pierre/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pierre/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build415071953=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

* I used `httputil.NewSingleHostReverseProxy` to create a proxy to a backend server which serves websockets.
* I made a request to a backend websocket service through the proxy. The request is cancelable using `context.WithCancel(...)`.
* I canceled the request

### What did you expect to see?

I expected the reverse proxy to close the connection to the backend server.

### What did you see instead?

The connection between the reverse proxy and the backend server was preserved.

---

Hi All,

I quickly modified the `TestReverseProxyWebSocket` test to reproduce my issue https://github.com/eshard/go/commit/73147b8fc8f9cb23b71b84a9a9b8af5d39d12e5b (I modified TestReverseProxyWebSocket in place to make the diff more readable)
I also did a dirty fix: https://github.com/eshard/go/commit/98e746e9b583414fe73d622ea4c775641faa6744 which propagates the cancelation to the `handleUpgradeResponse` function. It creates an additional goroutine so it's not ideal.

I'd be happy to improve my patch with your inputs

Best regards
Pierre

**Comment by andybons** [comment]
@bradfitz @mikioh

**Comment by odeke-em** [comment]
Thank you for reporting this issue @piec and welcome to the Go project!

Apologies foe the late reply, and thanks for the patience.
Please go ahead and send a CL/PR and I’ll review it.

**Comment by odeke-em** [comment]
@piec please take a look at the feedback that I left on your change, it would be great to get this in before the code freeze which is in 4 weeks. Thank you!

**Comment by piec** [comment]
Yes I took a look at the review @odeke-em, and thank you for it.
I didn't get time to work on it yet but I'll do it in the coming days.
Cheers
