### ISSUE TITLE
go: unknown environment setting GO111MODULE=false

### ISSUE THREAD

**Issue by renyang19910211** [golang/go#35556]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.13.4 

</pre>

### What operating system and processor architecture are you using (`go env`)?
win10
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

go env -w  GO111MODULE=false，I use the wrong value for GO111MODULE，then  all go cmd is not work with the error “go: unknown environment setting GO111MODULE=false”。I also can't reset the GO111MODULE to the right value.how can i fix it?

**Comment by ALTree** [comment]
Thanks for the report. 

You hit #34880, which was recently fixed (fix will be included in go1.14).

In the meantime, you could try this:

First, manually set GO111MODULE to a correct value from the terminal, for example in powershell; that should temporarily fix `go env`, then you can try `go env -w again`, so run:

```
$env:GO111MODULE=off
```
and then:

```
go env -w GO111MODULE=off
```

Does that work?

**Comment by renyang19910211** [comment]
Yes,it worked,Thank you very much!
