### ISSUE TITLE
x/tools/gopls: remove .orig files

### ISSUE THREAD

**Issue by powerman** [golang/go#35551]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 linux/amd64
</pre>
gopls updated about 6 hours ago from latest master

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/powerman/.cache/go-build"
GOENV="/home/powerman/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY="github.com/mtgroupit"
GONOSUMDB="github.com/mtgroupit"
GOOS="linux"
GOPATH="/home/powerman/go"
GOPRIVATE="github.com/mtgroupit"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build024112428=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I've used vim-go to rename some identifier in some `main.go` using gopls (feature released 6 hours ago).

### What did you expect to see?

Identifier renamed without any other side effects.

### What did you see instead?

Identifier renamed, but also `main.go.orig` file was created. Author of this feature in vim-go said there is no option in gopls to avoid creating these backup files: https://github.com/fatih/vim-go/issues/2366#issuecomment-553169654

Please add such an option, current behaviour is really annoying.

**Comment by powerman** [comment]
```
$ gopls version
golang.org/x/tools/gopls 0.2.0
    golang.org/x/tools/gopls@v0.2.0 h1:ddCHfScTYOG6auAcEKXCFN5iSeKSAnYcPv+7zVJBd+U=
```

**Comment by stamblerre** [comment]
@ianthehat, is it ok for us to do this, or should we just put the `.orig` files in some temporary directory?

**Comment by ianthehat** [comment]
The internal rename functionality does not generate .orig files, which is why this problem does not surface in VSCode.
However if you use the gopls command line to do the rename, it does.
I think this is probably the wrong choice, we should not be making the .orig files by default, maybe there should be a flag to enable them, but most people do not want them.
I would expect that most people that would care about this kind of thing will either use their VCS or read the diff first, not use the .orig functionality?

**Comment by powerman** [comment]
After `go get -v golang.org/x/tools/gopls@latest` I still get `.orig` files. Are you sure it's fixed?

**Comment by powerman** [comment]
Any chance new `-preserve` flag is true by default?

**Comment by zikaeroh** [comment]
`@latest` currently means v0.2.1. The fix is in master. If you want this fix, you'd have to wait for a version bump, or install master.

**Comment by powerman** [comment]
I've also tried `@master` and even `@6d480e2` - no difference.

**Comment by zikaeroh** [comment]
Are you sure you've gotten both the x/tools module and the x/tools/gopls module at master? Essentially all of the important stuff (including this fix) is in x/tools, not x/tools/gopls. Cloning the whole repo and `go install`-ing it is the easiest way to get both together without too much pain (though there are other methods).

**Comment by powerman** [comment]
Thanks! After `go get -v golang.org/x/tools@master` and then `go get -v golang.org/x/tools/gopls@master` the fix is working.

**Comment by stamblerre** [comment]
Glad this is resolved. Thanks, @zikaeroh! Just as a note, running `gopls` at master is not recommended because there can be breakages.
