### ISSUE TITLE
x/tools/gopls: support pkg.go.dev in textDocument/documentLink

### ISSUE THREAD

**Issue by zikaeroh** [golang/go#35563]
`gopls` currently uses godoc.org in its `documentLink` responses. This is fine, but it'd be nice to support the new `pkg.go.dev` site as it lets you look at a specific module version's documentation.

`gopls` has the module version info for imports, so could construct links to the new site with the correct version, which would work a bit better than just pointing to godoc.org in some cases. (Looking at the implementation of `documentLink`, it would require some extra work, since right now it just uses the AST and grabs the link, versus actually needing the import info.)

Sorry to drop the issue template, but it's a feature request and I thought it'd be a bunch of stuff that didn't matter.

**Comment by stamblerre** [comment]
Thanks for the suggestion! We can quite absolutely change the links to point to pkg.go.dev, but you're right that adding the versions will be a little tougher.

**Comment by jbszczepaniak** [comment]
I would like to claim this one. Is this ready to be done, or do we wait for https://github.com/golang/go/issues/31999 ?

**Comment by stamblerre** [comment]
@jbszczepaniak: I think we can do the first step of changing the link godoc.org links to point to pkg.go.dev.

**Comment by zikaeroh** [comment]
If the version info isn't going to be used, I'd maybe consider making this configurable. The default behavior of pkg.go.dev compared to godoc.org (`@latest` vs `@master`) makes it somewhat difficult to work with some libraries like docker, where `@latest` is simply never the right thing. (That, and for people who are still working in non-module-aware repos, but these are all of course edge cases.)

**Comment by jbszczepaniak** [comment]
So what is decision here @stamblerre? Do we want to get version as well and point to the right pkg.go.dev website?

**Comment by stamblerre** [comment]
Getting the version will only be possible after https://github.com/golang/go/issues/31999 is complete, but I am fine with moving forward on changing the links. We could also add a setting to opt-out and use godoc instead, as per @zikaeroh's suggestion.

**Comment by stamblerre** [comment]
Closing this since we are now linking to https://pkg.go.dev. Using version info can be tracked in https://github.com/golang/go/issues/31999.
