### ISSUE TITLE
x/website: pages have different heading and content widths

### ISSUE THREAD

**Issue by katiehockman** [golang/go#35571]
https://golang.org and https://blog.golang.org homepages have different widths than other tabs on the site. For example, starting at https://golang.org and clicking the [Packages](https://golang.org/pkg/) tab sends you to a page with a completely different width, including the navigation bar you were just using. If you then click the Blog tab, the page has a new width again, going back to the original more narrow view.

This creates a bit of a jarring user experience. I actually thought I had been sent to a different site at one point since it looked so different, and my mouse was no longer hovering over the element I just clicked. This has accessibility implications as well, since it's important to have a consistent experience for the same elements (like a nav bar) across a site.

/cc @andybons

**Comment by jamalc** [comment]
Closing as obsoleted by the merger of golang.org and go.dev.
