### ISSUE TITLE
cmd/compile: allow println(f()) where f() is multi-valued

### ISSUE THREAD

**Issue by mdempsky** [golang/go#35576]
This program builds with go/types and gccgo, but fails to typecheck with cmd/compile:

```
package main

func f() (int, int) { return 0, 0 }

func main() {
	println(f())
}
```

**Comment by cuonglm** [comment]
This also happens with `print`, seems that `typecheckargs` is not called for `OPRINT` and `OPRINTN`.

**Comment by ALTree** [comment]
Note: this is a dup of #20656, which at the time was closed as WONTFIX.

**Comment by mdempsky** [comment]
@ALTree Thanks for pointing that out.

I agree with @griesemer that spec-compliance doesn't strictly require `println(f())` to work. But it does work with gccgo and go/types, and it's easy enough to support (e.g., CL 207118 is just a one-line change), so I think it's worth doing for consistency.

**Comment by ALTree** [comment]
@mdempsky yeah I just linked the old thread for reference. I have no opinion on this.

**Comment by mdempsky** [comment]
@ALTree Understood. I struggle with GitHub issue search, so I always appreciate folks helping cross-reference old issues. :)
