### ISSUE TITLE
doc: doc/articles/wiki test failing when GOROOT is read-only

### ISSUE THREAD

**Issue by bcmills** [golang/go#35574]
From https://build.golang.org/log/e704977e8e25fee42871ecc456d8e0045f01db3f (thanks @mengzhuo!):

```
##### ../doc/articles/wiki
go build command-line-arguments: copying /tmp/workdir-host-linux-mipsle-mengzhuo/tmp/go-build204611216/b001/exe/a.out: open get.bin: permission denied
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
2019/11/14 05:35:08 Failed: exit status 2
2019/11/14 05:35:09 FAILED
```

(Part of #28387, the continuing saga.)

**Comment by mengzhuo** [comment]
Hmm, it's failed at "bench" now.
Should I change back to root?

https://build.golang.org/log/bba58a80fa8d3740ef1d084adc6c041b9456b69e

**Comment by bcmills** [comment]
You are welcome to switch the builder back to `root` if you want, but I think we're very close to making it all the way through `make.bash` without failing.

As far as I can tell, `../test/bench/go1` is running successfully, and the next failure occurs in `test:0_10` (in the `../test` phase).

**Comment by mengzhuo** [comment]
It's fine for me and take your time :)
