### ISSUE TITLE
pkg.go.dev: recognize additional permissive licenses

### ISSUE THREAD

**Issue by jrick** [golang/go#35570]
pkg.go.dev looks great but unfortunately much of the software I write and consume is licensed under one of two permissive licenses -- the [ISC License](https://spdx.org/licenses/ISC.html) and [Blue Oak Model License](https://blueoakcouncil.org/license/1.0.0) -- and the site refuses to display anything about these modules presumably because it does not recognize the licenses.  For example, check these repos:

https://github.com/jrick/wsrpc

https://github.com/decred/cspp

That last repo is also an interesting case, because it contains internal packages copied from the Go project, which do not share the same license as the rest of the module.  The Go BSD-style license was copied into the appropriate package directories, but there may need to be more sophisticated license detection and representation features on the pkg.go.dev site (as well as future license reporting added to the go tool?).

**Comment by andybons** [comment]
Thanks for the note.

Please see https://pkg.go.dev/license-policy for more information and a method to provide feedback.
