### ISSUE TITLE
gollvm: crash llvm-goc with SIGSEGV

### ISSUE THREAD

**Issue by heylinn** [golang/go#35586]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 gollvm LLVM 10.0.0svn linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<pre>
$ uname -o -m
x86_64 GNU/Linux
</pre>

### What did you do?
I tried to build a client for docker.

There are a few steps to reproduce the error:

<pre>
$ git clone https://github.com/docker/docker-ce.git
$ cd docker-ce
$ git checkout v19.03.4
$ cd components
$ mkdir -p .gopath/src/github.com/docker
$ export GOPATH=`pwd`/.gopath:~/go
$ ln -sf `pwd`/cli .gopath/src/github.com/docker/cli
$ cd .gopath/src/github.com/docker/cli/
$ go build ./vendor/github.com/docker/docker/client
</pre>

### What did you expect to see?

Clean compilation

### What did you see instead?

<pre>
Compiler crash:
Program received signal SIGSEGV, Segmentation fault.
0x0000555555af7d97 in Bfunction::getParameterVars() ()
(gdb) bt
#0  0x0000555555af7d97 in Bfunction::getParameterVars() ()
#1  0x0000555555b0bc67 in DIBuildHelper::endFunction(Bfunction*) ()
#2  0x0000555555aa2348 in Llvm_backend::function_set_body(Bfunction*, Bstatement*) ()
#3  0x0000555555a11c71 in Function::build(Gogo*, Named_object*) ()
#4  0x0000555555a13efc in Named_object::get_backend(Gogo*, std::vector<Bexpression*, std::allocator<Bexpression*> >&, std::vector<Btype*, std::allocator<Btype*> >&, std::vector<Bfunction*, std::allocator<Bfunction*> >&) ()
#5  0x0000555555a1ef09 in Gogo::write_globals() ()
#6  0x00005555559e9278 in gollvm::driver::CompileGoImpl::invokeFrontEnd() ()
#7  0x00005555559f08e5 in gollvm::driver::CompileGoImpl::performAction(gollvm::driver::Compilation&, gollvm::driver::Action const&, llvm::SmallVector<gollvm::driver::Artifact*, 3u> const&, gollvm::driver::Artifact const&) ()
#8  0x00005555559e4863 in gollvm::driver::Driver::processAction(gollvm::driver::Action*, gollvm::driver::Compilation&, bool) ()
#9  0x00005555559e4a47 in gollvm::driver::Driver::processActions(gollvm::driver::Compilation&) ()
#10 0x000055555595cb2f in main ()
</pre>

**Comment by thanm** [comment]
I'll take a look.

**Comment by thanm** [comment]
This I think is actually a front end oddity (gcc backend doesn't mind but it causes issues with gollvm).

Reduced testcase:

Package "a"
<pre>
package a

var Avar int

func D(_ string, _ int) (uint64, string) {
	return 101, "bad"
}
</pre>

Package "b":
<pre>
package b

import "a"

func F(addr string) (uint64, string) {
	return a.D(addr, 32)
}
</pre>

I will send a tentative fix shortly.

**Comment by thanm** [comment]
@heylinn  Thank you for reporting this bug. I have a fix out for review.

**Comment by heylinn** [comment]
Thank you! I am impressed how fast you fixed it.
