### ISSUE TITLE
x/text/cmd/gotext: gotext created catalog_gen.go returns wrong value for non-existing keys

### ISSUE THREAD

**Issue by rozmansi** [golang/go#35587]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.4 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Simon\AppData\Local\go-build
set GOENV=C:\Users\Simon\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Simon\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\Simon\go\src\golang.org\x\text\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\XXX\AppData\Local\Temp\go-build215568786=/tmp/go-build -gno-record-gcc-switches
### What did you do?

1. Create a Go sample:
```Go
package main

import (
	"strings"

	"golang.org/x/text/language"
	"golang.org/x/text/message"
)

//go:generate go run golang.org/x/text/cmd/gotext -srclang=en update -out=catalog_out.go -lang=en,sl

func main() {
	prn := message.NewPrinter(language.Slovenian)

	prn.Printf("This is a test.\n")

	fruits := []string{"apple", "orange"}
	list := strings.Join(fruits, prn.Sprintf(", "))
	prn.Printf("Fruits: %s\n", list)
}
```

2. `go generate`
3. Copy `locales/sl/out.gotext.json` to `locales/sl/messages.gotext.json` and fill in "translation" members. Copy from "message" members.
4. `go generate`
5. `go build`
6. Run the executable.

### What did you expect to see?

```
This is a test.
Fruits: apple, orange
```

### What did you see instead?

```
This is a test.
Fruits: appleThis is a test.
orange
```

**Comment by andybons** [comment]
@mpvl
