### ISSUE TITLE
x/sys: installation fails

### ISSUE THREAD

**Issue by stemsin** [golang/go#35583]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\sement\AppData\Local\go-build
set GOENV=C:\Users\sement\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=c:\!ST\Development\Go
set GOPRIVATE=
set GOPROXY=localhost:8080
set GOROOT=c:\!ST\Tools.Develop\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\!ST\Tools.Develop\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\sement\AppData\Local\Temp\go-build644169734=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

go get -u golang.org/x/sys

### What did you expect to see?
Package installed

### What did you see instead?
package golang.org/x/sys: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: proxyconnect tcp: tls: first record does not look like a TLS handshake)

**Comment by mvdan** [comment]
That looks like a network issue. Have you tried again, perhaps with a different internet connection or machine?

**Comment by stemsin** [comment]
I will try tonight. But works fine for other GitHub based packages

**Comment by ALTree** [comment]
This has been in waiting for info for almost 2 years, and it was reported against a version of Go that is no longer supported, so let's archive this. If it comes out again on a recent Go version we can open a new issue.
Anyway it looked like a network issue.
