### ISSUE TITLE
pkg.go.dev: known licenses are not recognised and the site misrepresents license status of packages

### ISSUE THREAD

**Issue by kortschak** [golang/go#35595]
Note that I am aware that #35570 exists, however the method for providing feedback there is broken in that it will not work with firefox. Nor does it allow AFAICS nuanced conversation of issues, so I am reporting here.

It appears that the license recognition code used by pkg.go.dev has an unfortunately high false positive rate. Packages such as [gonum.org/v1/gonum](https://pkg.go.dev/gonum.org/v1/gonum?tab=overview) and [modernc.org/cc](https://pkg.go.dev/modernc.org/cc?tab=overview), both of which have BSD-3-clause licenses ([here](https://github.com/gonum/gonum/blob/master/LICENSE) and [here](https://gitlab.com/cznic/cc/blob/master/LICENSE)) (note also that while the source code link for modernc.org/cc is provided on the overview at pkg.go.dev, even that is missing for the Gonum page).

This harms the packages where this happens by failing to present them to users and misrepresents the licensability of the packages potentially harming them by causing potential users to move on to other packages where the license *is* accepted.

Note also that it arguably does not properly cover the owner of go.dev since other packages that import and reflect the APIs of these *lost* packages may be rendered. For example [k8s.io/kubernetes/pkg/controller/garbagecollector](https://pkg.go.dev/k8s.io/kubernetes/pkg/controller/garbagecollector?tab=doc) imports Gonum packages but does not present the Gonum license (and in fact [shows the wrong license](https://pkg.go.dev/search?q=k8s.io+gonum)). In a clearer example, [github.com/openshift/origin](https://pkg.go.dev/github.com/openshift/origin?tab=doc) vendors a number of Gonum packages and pkg.go.dev thus misrepresents the license for openshift/origin by only showing the Apache license in its LICENSE file (and also in the [search results](https://pkg.go.dev/search?q=openshift+gonum)).

**Comment by andybons** [comment]
Thanks for the issue. We are working to address the feedback widget issues on Firefox and we’re working to improve our license classification.

Please email go-discovery-feedback@google.com, as issues for pkg.go.dev are not tracked in this repository. I understand the desire to have an open, nuanced conversation, but it’s difficult to do so given the legal considerations surrounding licensing more generally. The moderators on that list are responsive and will do what they can to help.

Thanks for your patience on this.

**Comment by kortschak** [comment]
>I understand the desire to have an open, nuanced conversation, but it’s difficult to do so given the legal considerations surrounding licensing more generally.

This is high-level Catch-22 action.
