### ISSUE TITLE
pkg.go.dev: displays root package readme on sub-package page

### ISSUE THREAD

**Issue by leighmcculloch** [golang/go#35591]
### What did you do?

Viewed @stellar's Ticker service package at https://pkg.go.dev/github.com/stellar/go/services/ticker?tab=overview which is a package inside our monorepo that is a web service that has its own readme file.

### What did you expect to see?

I expected to see the readme file for the Ticker service's package, in the same way that other services like GitHub display the readme for the current package being viewed, https://github.com/stellar/go/tree/master/services/ticker.

<img width="1019" alt="Screen Shot 2019-11-14 at 10 56 26 AM" src="https://user-images.githubusercontent.com/351529/68887243-848b3780-06cd-11ea-9b5a-79afe62fd9e4.png">

### What did you see instead?

The readme for the root package of the module, which is confusing and unintuitive.

<img width="804" alt="Screen Shot 2019-11-14 at 10 54 45 AM" src="https://user-images.githubusercontent.com/351529/68887091-337b4380-06cd-11ea-88e9-fae323ea9b7d.png">

**Comment by andybons** [comment]
Thanks for the issue, but we are not currently tracking issues for pkg.go.dev here.

Per https://go.dev/about:

> Sharing feedback / Reporting an issue
> On the footer of every page there are two links, “Share Feedback” and “Report an issue”. These links will enable you to capture a screenshot of the page you are on, annotate that screenshot, and then send this directly to the go.dev team.

> Or you can send your bugs, ideas, feature requests and questions to go-discovery-feedback@google.com.
