### ISSUE TITLE
x/tools/gopls: find implementations sometimes returns interface itself

### ISSUE THREAD

**Issue by muirdm** [golang/go#35601]
For example, when I run find-implementations on the "matcher" interface in tools/internal/lsp/source/completion.go, I get back a result referring to the "matcher" interface itself.

Edit: found an example in a module based repo so I got rid of GOPATH related stuff.

**Comment by ridersofrohan** [comment]
Fixed in [#73db347](https://github.com/golang/tools/commit/73db347c3b7cb8dddf5cb12d7637682d56758cf4)
