### ISSUE TITLE
x/tools/gopls: implementations sometimes returns no results

### ISSUE THREAD

**Issue by muirdm** [golang/go#35602]
When finding implementations of an interface method I sometimes unexpectedly get back no results. In the below setup, when finding implementations on the "U()" interface method, I get back zero results when I expect one in blah.go

```
-- go.mod --
module foo

-- foo.go --
package foo

import "foo/blah"

type Foo struct {
	blah.Foo
}

type U interface {
  U() // <-- find implementations here
}

-- blah/blah.go --
package blah

type Foo struct {
}

func (Foo) U()  {
}
```

**Comment by ridersofrohan** [comment]
Fixed in [#e13f15d](https://github.com/golang/tools/commit/e13f15d1b9df00fb1b01890cd1382a7bf41b8ab7)
