### ISSUE TITLE
Valid syntax that makes absolutely no sense

### ISSUE THREAD

**Issue by essial** [golang/go#35603]
### What version of Go are you using (`go version`)?
go version go1.13.3 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\lunat\AppData\Local\go-build
set GOENV=C:\Users\lunat\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\lunat\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\lunat\AppData\Local\Temp\go-build376628234=/tmp/go-build -gno-record-gcc-switches</pre></details>

### What did you do?
I created a function that (unintentionally) did what the following basic example does:
`
func DoSomething() (val int) {
	return val
}
`

### What did you expect to see?
A compile error about not returning a value.

### What did you see instead?
It compiled and ran fine. Because of variable masking, I was setting a locally scoped variable instead of the return value, which caused it to always return 0.

**Comment by ianlancetaylor** [comment]
That is how the language works.  Named result parameters are in scope within the function body.  You can assign to them.  You can use `return` with no values to return the values that are currently in the named result parameters (https://golang.org/ref/spec#Return_statements).  You can change the values of the result parameters in deferred functions (https://golang.org/ref/spec#Defer_statements).
