### ISSUE TITLE
fix err syntax

### ISSUE THREAD

**Issue by DiskGetor** [golang/go#35609]
like this:

#pragma warning(disable:4996) 

int OpenError() {
	return 1+1;
}

int ok() {
	auto f = OpenError();
	if (f == 2) {
		_asm {
			MOV EAX,ESP
		    JMP EAX
		}
	}
	std::cout << "Hello 1!\n";
}

int main(){
	ok();
	std::cout << "Hello 2!\n";
}

func (ddk) CheckErrWithCtx(ctx interface{}, err error) interface{} {
	if err != nil {
		W.LogError(`错误 `, err.Error())
		//debug.PrintStack()
		//用汇编改RIP为rsp+8的值?
		panic(err.Error())
	}
	return ctx
}

**Comment by DiskGetor** [comment]
最后变成这样：
Hostname := W.CheckErrWithCtx(os.Hostname()).(string)

**Comment by ianlancetaylor** [comment]
I'm sorry, I don't understand this.  You are showing C code.  Are you reporting a problem in Go?  What is the problem?

**Comment by DiskGetor** [comment]
对不起，我很难表达，请看例子：

package main

import (
	"log"
	"os"
	"runtime/debug"
)

func main()  {
	CallMain()
}
func CallMain()  {
	Hostname()
	log.Println(`if err go to here`)
}

func Hostname(){
	//if err != nil {
	//
	//}
	 Hostname := CheckErrWithCtx(os.Hostname()).(string)
	 log.Println(Hostname)
}

func  CheckErrWithCtx(ctx interface{}, err error) interface{} {
	if err != nil {
		debug.PrintStack()
		//asm to-->return rsp //怎么实现汇编改变rip？ goto-->log.Println(`if err go to here`)
	}
	return ctx
}

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

We don't use the issue tracker for general questions about Go.
