### ISSUE TITLE
xml  marshal bug

### ISSUE THREAD

**Issue by 0x2d3c** [golang/go#35612]
`go version go1.13.4 linux/amd64`

xml  marshal bug

```
       type Data struct {
		Url string
	}

	var data Data
	data.Url = "http://ip:port/xxxxxxxxxx&1573776000&1573862399"

	b, _ := xml.Marshal(data)
        fmt.Println(string(b))
```

	// want: <Data><Url>rtsp://ip:port/xxxxxxxxxx&1573776000&1573862399</Url></Data>
	// result: <Data><Url>rtsp://ip:port/xxxxxxxxxx&amp;1573776000&amp;1573862399</Url></Data>

**Comment by opennota** [comment]
Not a bug.

https://www.techrepublic.com/article/beware-of-the-ampersand-when-using-xml/

**Comment by 0x2d3c** [comment]
> Not a bug.
> 
> https://www.techrepublic.com/article/beware-of-the-ampersand-when-using-xml/

thanks
