### ISSUE TITLE
syscall: add Flock implementation for Illumos

### ISSUE THREAD

**Issue by bcmills** [golang/go#35618]
On most Unix and Unix-like platforms, the Go `syscall` package provides the `Flock` function (and the associated constants `LOCK_EX`, `LOCK_SH`, `LOCK_UN`).

That functionality is not provided for Solaris, because (as far as I am aware) Oracle Solaris still does not provide the corresponding system call (see also #24684). However, it appears that the Illumos kernel has supported `flock` since 2015 (https://www.illumos.org/issues/3252).

We should update the `syscall` package to provide `Flock` on `illumos`. Then we can switch `cmd/go/internal/lockedfile/internal/filelock` over to use it, and hopefully avoid apparent kernel bugs that affect the current `Fcntl` implementation used on AIX and Solaris (#32817).

CC @jclulow @gdamore @tklauser

**Comment by jclulow** [comment]
It was my impression that the **syscall** package was effectively frozen at this stage.  Is that just from an exposed API perspective?  That is, is this OK because there's already Flock in there for other platforms?

**Comment by bcmills** [comment]
My personal view is that it's ok because:
1) there is already a `Flock` implementation (with the same semantics) on other platforms, and
2) we would use `Flock` within the standard library.

(Either of those on its own might argue for not extending the package, but given that `Flock` already exists it's simpler not to require extra build tags in order to use it from some other package.)

**Comment by bradfitz** [comment]
Yeah, it's okay to modify syscall for the reasons Bryan mentioned. (API already existing + for internal use)
