### ISSUE TITLE
x/sys/unix: TestClockNanosleep failures on linux-mipsle-rtrk builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#35622]
https://build.golang.org/log/f0d29a593ccba5704246987f49074bfca43dd1b9

```
--- FAIL: TestClockNanosleep (0.10s)
    syscall_linux_test.go:580: ClockNanosleep(CLOCK_REALTIME, TIMER_ABSTIME, &unix.Timespec{Sec:1573834610, Nsec:328568608} (=2019-11-15 17:16:50.328568608 +0100 CET m=+0.544561463), nil) = interrupted system call
FAIL
FAIL	golang.org/x/sys/unix	0.599s
```

CC @tklauser @bogojevic @milanknezevic @cherrymui

**Comment by ianlancetaylor** [comment]
Now that we use signals for preemption I guess all those calls need to check for `EINTR`.

**Comment by bcmills** [comment]
@ianlancetaylor, aren't the runtime's handlers all registered with `SA_RESTART` set?

I would expect preemption to produce spurious `EINTR` return values in some `cgo` programs due to #20400, but I don't understand why it would affect a pure-Go package test.

**Comment by ianlancetaylor** [comment]
`SA_RESTART` does not apply to all system calls.  For the Linux kernel, see http://man7.org/linux/man-pages/man7/signal.7.html, where it says that the `clock_nanosleep` system call, among others, always returns `EINTR` even if the signal was registered with `SA_RESTART`.
