### ISSUE TITLE
x/build/cmd/buildlet: removeAllIncludingReadonly doesn't remove read-only files on Plan 9

### ISSUE THREAD

**Issue by 0intro** [golang/go#35634]
CL [177457](https://golang.org/cl/177457) added the removeAllIncludingReadonly function to be able
to remove the read-only files and directories created by `go mod`.

https://github.com/golang/build/blob/c7f36d0/cmd/buildlet/buildlet.go#L1813

On Plan 9, the function returns after calling `os.RemoveAll`.
However, this doesn't work properly on Plan 9, since files cannot
be deleted from read-only directories.

The directories should be make writeable before being able to remove files.

@millerresearch

**Comment by millerresearch** [comment]
Removing the `|| runtime.GOOS == "plan9"` clause in removeAllIncludingReadonly should fix this. Also maybe correct the comment on the preceding line `s/our emphermal/are ephemeral/` ?
