### ISSUE TITLE
cmd/fix: incorrect loop variable aliasing in TestRewrite

### ISSUE THREAD

**Issue by mewmew** [golang/go#35632]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +c20b71eb37 Sat Nov 16 02:06:39 2019 +0000 linux/amd6
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/u/.cache/go-build"
GOENV="/home/u/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/u/goget:/home/u/Desktop/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/u/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/u/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/u/go/src/cmd/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build745246669=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

1. clone the go repository: `git clone https://go.googlesource.com/go.git`
2. build go as usual: `cd src; ./all.bash`
3. edit `cmd/fix/context_test.go` to ensure that the test case should FAIL.

```diff
diff --git a/src/cmd/fix/context_test.go b/src/cmd/fix/context_test.go
index 935d0d7235..f666be2fb1 100644
--- a/src/cmd/fix/context_test.go
+++ b/src/cmd/fix/context_test.go
@@ -19,7 +19,7 @@ var _ = "golang.org/x/net/context"
 `,
                Out: `package main
 
-import "context"
+import "context"x
 
 var _ = "golang.org/x/net/context"
 `,
```

4. run `go test` from the `src/cmd/fix` directory.

```
$ go test
PASS
ok  	cmd/fix	0.032s
```

5. notice that the test case passes, even though it *should* fail, given that we edited the expected output of the context rewrite rule.

6. remove call to `t.Parallel` in `cmd/fix/main_test.go`

```diff
diff --git a/src/cmd/fix/main_test.go b/src/cmd/fix/main_test.go
index ee74f24c6e..5214d67af1 100644
--- a/src/cmd/fix/main_test.go
+++ b/src/cmd/fix/main_test.go
@@ -77,7 +77,7 @@ func parseFixPrint(t *testing.T, fn func(*ast.File) bool, desc, in string, mustB
 func TestRewrite(t *testing.T) {
        for _, tt := range testCases {
                t.Run(tt.Name, func(t *testing.T) {
-                       t.Parallel()
+                       //t.Parallel()
                        // Apply fix: should get tt.Out.
                        out, fixed, ok := parseFixPrint(t, tt.Fn, tt.Name, tt.In, true)
                        if !ok {
```

7. re-run test case using `go test` from the `src/cmd/fix` directory.

```
--- FAIL: TestRewrite (2.86s)
    --- FAIL: TestRewrite/context.0 (0.00s)
        main_test.go:94: incorrect output.
        main_test.go:96: --- have
            package main
            
            import "context"
            
            var _ = "golang.org/x/net/context"
            
            --- want
            package main
            
            import "context"x
            
            var _ = "golang.org/x/net/context"
        main_test.go:133: --- /tmp/go-fix-test929058818	2019-11-15 21:39:47.643666701 -0600
            +++ /tmp/go-fix-test221839737	2019-11-15 21:39:47.643666701 -0600
            @@ -1,5 +1,5 @@
             package main
             
            -import "context"
            +import "context"x
             
             var _ = "golang.org/x/net/context"
            
FAIL
exit status 1
FAIL	cmd/fix	2.866s
```

8. notice that the test case now fails, as it should do, given that we edited the expected output of the context rewrite rule.

### What did you expect to see?

A failed test case (after having modified the expected output of the `context_test.go` test case).

### What did you see instead?

Test cases passing without error.

**Comment by bcmills** [comment]
Run the test with `-race`. You seem to be running afoul of #16520.

**Comment by bcmills** [comment]
Hrm, even with `-race` the race is undetected. That's unfortunate.

**Comment by bcmills** [comment]
Filed #35670 for the missing `-race`-mode check.
