### ISSUE TITLE
x/mobile: bind framework not found by Xcode

### ISSUE THREAD

**Issue by pontusntengnas** [golang/go#35641]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
I believe I am on the latest version

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/pontusnt/Library/Caches/go-build"
GOENV="/Users/pontusnt/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="MY_GO_PATH"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/68/_7g0dkds1zx17wwpnmh6k4wr0000gn/T/go-build239061966=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

`gomobile bind -o frameworks/ios/Shared.framework -target=ios`

This completed successfully and I got a folder named Shared.Framework with obj-c files.

I drag and drop this into Xcode 11.2.1 (11B500) to use it in my app.

### What did you expect to see?

I expected to be able to compile the app and use the framework in my Swift code.

### What did you see instead?

The Xcode project no longer compiles, but fails with:

`ld: framework not found Shared
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

I alos tried adding the absolut path to Xcode build setting `Framework search paths` without success.

Thankful for your help!

**Comment by andybons** [comment]
@eliasnaur

**Comment by eliasnaur** [comment]
> I alos tried adding the absolut path to Xcode build setting `Framework search paths` without success.
> 

FWIW, this works for me in Xcode 11.1. Did you add the path to the framework ("/path/to/Shared.framework") or the path to the containing directory ("/path/to")? Xcode expects the latter.

**Comment by pontusntengnas** [comment]
Thanks for you reply. I tried both of them without success. I really cannot understand why this is happening, there is a framework in that folder. I do not know if it matters but it is just a folder called "Shared.Framework" containing the files and not that "Lego-ish" icon that i have seen some frameworks have. 

The app is targeting iOS 13. 

I get the exact same issue trying to use the example at
`go get -d golang.org/x/mobile/example/bind/...`

**Comment by pontusntengnas** [comment]
Am I missing something? I drag n drop the framework into Xcode and it shows up nicely under "Frameworks, Libraries, and embedded content". Then I added the framework search path and tried to build.

**Comment by eliasnaur** [comment]
I installed Xcode 11.2.1 with no change: the bind example builds successfully.

> Thanks for you reply. I tried both of them without success. I really cannot understand why this is happening, there is a framework in that folder. I do not know if it matters but it is just a folder called "Shared.Framework" containing the files and not that "Lego-ish" icon that i have seen some frameworks have.
>

Did you name the framework "Shared.Framework" or "Shared.framework"?

**Comment by pontusntengnas** [comment]
I am using "Shared.framework". Capital F gives me an error when binding.

**Comment by pontusntengnas** [comment]
Okey I got it working now! What was causing the issue was probably my use of the name "Shared" when there where no Go package called "shared" in the files I was binding.

If i omit the naming of the output `-o` and just bind it, the frameworks gets a different name but this frameworks gets found by Xcode and can be used, awesome!

But then a follow up question, is it not possible to name my framework to something custom?

In my case I am binding 3 different Go packages and want to create a single output framework of that. I do this like this:

`
gomobile bind -target=ios \
    services/departure \
    services/search \
    presenters`

And then the name of the framework becomes `Departure`, so I guess it just gets the name of the first package argument I give to `bind`. 

So it works but it would be nice to name it something else. And am I doing it right when binding my 3 packages like I do?

Thanks.

**Comment by eliasnaur** [comment]
Can you send a complete example, with you xcode project ready to use and a set of packages for `gomobile bind`? The easier it is to reproduce, the better.

@hajimehoshi

**Comment by pontusntengnas** [comment]
I do not see it is as necessary as it is working for me now. Now I just wonder if I can have a custom name on the .framework output and if the way I am binding the three packages is the correct way to do it, see my above comment.

**Comment by eliasnaur** [comment]
On Sun Nov 24, 2019 at 9:19 AM Pontus Nilsson Tengnäs wrote:
> I do not see it is as necessary as it is working for me now. Now I just wonder if I can have a custom name on the .framework output and if the way I am binding the three packages is the correct way to do it, see my above comment.
> 

The `-o` option should let you name your framework any way you want,
providing the name ends with `.framework`. That's why I wanted you
to provide us with exact reproduction steps.

**Comment by pontusntengnas** [comment]
Ok I see I will try to find time to make an example and attach here.

**Comment by arjenveenhuizen** [comment]
We ran into the same issue when upgrading from xcode 10.3 to 11.3.1. `Module not found` whatever we tried or change on our `gomobile bind` command line. 

Triggered by https://github.com/golang/go/issues/35641#issuecomment-555159238 we finally figured out that we had to change the `Framework Search Paths` from `$(SRCROOT)/../../../path/to/Myframework.framework/` to `$(SRCROOT)/../../../path/to/`

**Comment by fallenlord** [comment]
I ran into the same issue today, and thanks to @pontusntengnas , I resolve it by omitting `-o` option.

I made a simple example and hope it helps @eliasnaur 

## Env

- go version go1.14.3 darwin/amd64
- Xcode 11.5
- macOS Catalina 10.15.4

<details>
<summary>
go env
</summary>
<pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/guolin/Library/Caches/go-build"
GOENV="/Users/guolin/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/guolin/Work/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/Cellar/go/1.14.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/guolin/Work/colin/go/issue/gogo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0k/r288ywwx49zcyx8dpgh5tt5r0000gn/T/go-build768315077=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
</details>

## Reproduce

Download the [issue.zip](https://github.com/golang/go/files/4774760/issue.zip) file then extract, will get two projects:

- gogo for Go
- Soso for Xcode

1. Build gogo:

```sh
cd gogo
gomobile bind -o gogo.framework -a -ldflags '-s -w' -target=ios gogo.go/fly gogo.go/swim
```

2. Open `Soso` project by Xcode
3. Add `gogo.framework` into Xcode project
4. Press `Command+Shift+R` to build project will see the error: `Framework not found gogo`

hope it helps

**Comment by ToJen** [comment]
It appears that if the framework name is different from the name of the package that was built, this ld not found error will be thrown. 
In "Example.framework/Versions/A/Modules/module.modulemap" you should see something like this:
```
framework module "Example" {
	header "ref.h"
    header "Example.objc.h"
    header "Universe.objc.h"
    header "Example.h"

    export *
}
```
I notice that `Example.framework` won't work if the root module I'm trying to import is not called Example.

**Comment by hajimehoshi** [comment]
So, fixing modulemap by using the specified framework name would solve this issue? That makes sense. I'll take a look next week.

**Comment by ToJen** [comment]
That’s my guess. It may need testing on Android and iOS apps. Happy to spend some time contributing to that @hajimehoshi.
