### ISSUE TITLE
Why the strings package's Index method returns 0 when the second parameters  is an empty string

### ISSUE THREAD

**Issue by xdlove** [golang/go#35662]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.12.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
<pre>
$ Yes
</pre>

https://github.com/golang/go/blob/master/src/strings/strings.go
![image](https://user-images.githubusercontent.com/16837938/69048631-ea165580-0a38-11ea-86c8-9235abd4234d.png)

**Comment by xdlove** [comment]
can it return -1?

**Comment by bradfitz** [comment]
The empty string is present in all strings.

We could've defined it otherwise, but we didn't, and we can't change it now.
