### ISSUE TITLE
cmd/go: do not treat branches with semantic-version names as releases

### ISSUE THREAD

**Issue by bcmills** [golang/go#35671]
https://github.com/golang/go/issues/33558#issuecomment-554879181 reports a situation in which a `v2.0.0` branch was created and subsequently removed, but `proxy.golang.org` cached a `v2.0.0+incompatible` release.

If someone creates a _branch_ named `v2.0.0`, they probably intend for that branch to contain the development _leading up to_ `v2.0.0`, not for that branch as first published to be the definitive final release of `v2.0.0`. The `go` command should not mistake the former for the latter.

CC @jayconrod @mattn @thepudds

**Comment by bcmills** [comment]
See #29731, which also involves confusion between branches and versions.

**Comment by ianlancetaylor** [comment]
Is this going to happen for 1.17?  Thanks.

**Comment by FiloSottile** [comment]
@gopherbot please open backport issues. Materializing versions from branches might be unexpected and bypass ACLs that limit the creation of tags but not branches. It's also better for the version list to be consistent across supported Go versions.

**Comment by jing-rui** [comment]
Is there any workaround for old versions(go1.15)?

**Comment by bcmills** [comment]
@jing-rui, per the Go project's [release policy](https://go.dev/doc/devel/release#policy), only the two most recent Go releases receive backport fixes.

The only workarounds I'm aware of for older versions are to upgrade, or to configure your environment to use a `GOPROXY` that itself runs an upgraded or patched version of the `go` command.
