### ISSUE TITLE
x/tools/gopls: support $/cancelRequest correctly

### ISSUE THREAD

**Issue by stamblerre** [golang/go#35679]
[CL 207598](https://go-review.googlesource.com/c/tools/+/207598) added a `(*server).CancelRequest` function that we had not previously had. We should support cancellation of a specific request.

**Comment by ianthehat** [comment]
$/cancelRequest is specially handled at the transport layer in order to be able to cancel requests out of the queue (and is fully implemented), the typescript generator used to know not to generate this function.

**Comment by stamblerre** [comment]
That's what I thought - thanks for confirming.
