### ISSUE TITLE
Bug multiplying a float32(variable(int)) with a float32 variable

### ISSUE THREAD

**Issue by gonzalochief** [golang/go#35674]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.4 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
I have not tested it

### What operating system and processor architecture are you using (`go env`)?
Mac OS Catalina
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/macbook/Library/Caches/go-build"
GOENV="/Users/macbook/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/macbook/golib:/Users/macbook/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/c3/nyj9fvvd1vn375qfvw78t3mc0000gn/T/go-build544665324=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I have a int slice with a value 155250 and multiply it by another float32 slice variable (519.0) using the float32(int) function. The result was  80574752, instead of 80574750.
The error does not show when converting to float64 variable. The issue must be in the float32() function

### What did you expect to see?

80574750

### What did you see instead?

80574752

**Comment by gonzalochief** [comment]
I also replicated the issue in the Golang playground:

package main

import "fmt"

func main() {
	var x int32 = 155250
	var y float32 = 519
	fmt.Printf("%0.8f\n", float32(x)*(y))//80,574,752
	fmt.Printf("%0.8f\n", float32(155250)*(519.00))//80,574,752
	fmt.Printf("%0.8f\n", float64(155250)*float64(519.00))//80,574,750
}

**Comment by randall77** [comment]
This is how `float32` works.
The number `80574750` is not exactly representable in `float32`. It rounds to `80574752`.
```
	fmt.Printf("%f\n", float32(80574750))
```
This also prints `80574752`.

**Comment by dmitshur** [comment]
`float32` has lower precision than `float64`, and may not be enough to represent the result of the multiplication with enough precision:

```Go
package main

import (
	"fmt"
)

func main() {
	fmt.Println(float32(155250) * float32(519))

	// Output: 8.057475e+07
}
```

Could that be reason for the result you're seeing?

**Comment by gonzalochief** [comment]
Thanks for your answers and suggestions. In fact it was as you said. a precision issue.
I have moved all variables to float 64 and it worked
