### ISSUE TITLE
x/tools/gopls:  "Go to Symbol in Workspace"  in vscode

### ISSUE THREAD

**Issue by yzliu** [golang/go#35685]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/share/go_project"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build697502227=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
CTRL+T in VSCODE  for  “Go to Symbol in Workspace...”

### What did you expect to see?
List of Symbols

### What did you see instead?
No result

**Comment by stamblerre** [comment]
`gopls` does not yet support this feature, so I think this issue belongs in the [vscode-go](https://github.com/microsoft/vscode-go) repository. https://github.com/golang/go/issues/33844 tracks the support for this feature in `gopls`.
