### ISSUE TITLE
x/tools/gopls: tsprotocol unmarshals not handling union types

### ISSUE THREAD

**Issue by myitcv** [golang/go#35688]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +0ac8739ad5 Mon Nov 18 15:11:03 2019 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20191118222007-07fc4c7f2b98
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.1.8-0.20191118222007-07fc4c7f2b98
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build331350992=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

`govim` uses a vendored version of the LSP protocol client:

https://github.com/golang/tools/blob/07fc4c7f2b9857711f6306c76424246e8d6eab64/internal/lsp/protocol/protocol.go#L69-L74

(as well as a vendored version of the jsonrpc2 code).

Following https://go-review.googlesource.com/c/tools/+/207598 we are no longer seeing concrete types be returned for calls to `CodeAction`. 

`govim` (the client of the LSP server) ends up calling via:

https://github.com/golang/tools/blob/07fc4c7f2b9857711f6306c76424246e8d6eab64/internal/lsp/protocol/tsserver.go#L745-L751

Because the new return type of `CodeAction` is `interface{}`, the subsequent unmarhsaling that happens at:

https://github.com/golang/tools/blob/07fc4c7f2b9857711f6306c76424246e8d6eab64/internal/jsonrpc2/jsonrpc2.go#L187-L189

results in use of the [standard `encoding/json` types](https://godoc.org/encoding/json#Unmarshal):

```
bool, for JSON booleans
float64, for JSON numbers
string, for JSON strings
[]interface{}, for JSON arrays
map[string]interface{}, for JSON objects
nil for JSON null
```

Which means that uses within `govim` can no longer type assert to the concrete types defined as part of the protocol that form the union type.

### What did you expect to see?

Concrete types returned by a call to `*internal/lsp/protocol.serverDispatcher.CodeAction()`

### What did you see instead?

Generic `encoding/json.Unmarshal` types returned by a call to `*internal/lsp/protocol.serverDispatcher.CodeAction()`

---

cc @stamblerre @pjweinb

**Comment by pjweinb** [comment]
what would you like it to return? The protocol says it can be one of
Command, CodeAction, or a slice of either (that is, typescript would allow
an array with some CodeActions and some Commands.

(it's easy to change)

**Comment by pjweinb** [comment]
looks like []CodeAction would match the gopls code.

**Comment by myitcv** [comment]
Concrete values of whatever is returned by `gopls`, I guess?

i.e. if `gopls` returns a `Command`, return a value of that type. If it returns `[]CodeAction`, have it return that type etc?

**Comment by pjweinb** [comment]
Hi Paul. It's  change 207898
<https://go-review.googlesource.com/c/tools/+/207898>

I would have put you on the reviewer list, but I didn't get your email
address. what should I have used?

**Comment by myitcv** [comment]
Thanks @pjweinb - I replied on the CL.
