### ISSUE TITLE
time: TestTicker flaky with a short Duration on darwin-arm64-corellium builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#35692]
```
#!watchflakes
post <- pkg == "time" && test == "TestTicker" && `\d+ .+ ticks took .+, expected`
```

`time.TestTicker` is consistently failing on the `darwin-arm64-corellium` builder (https://build.golang.org/log/ae40104c94a528ac4e0295ddf4d3fb34620250df):

```
--- FAIL: TestTicker (2.39s)
    tick_test.go:63: saw 5 errors
    tick_test.go:25: 10 20ms ticks took 535.802667ms, expected [160ms,240ms]
    tick_test.go:25: 10 20ms ticks took 388.628375ms, expected [160ms,240ms]
    tick_test.go:25: 10 20ms ticks took 461.014083ms, expected [160ms,240ms]
    tick_test.go:25: 10 20ms ticks took 459.991375ms, expected [160ms,240ms]
    tick_test.go:25: 10 20ms ticks took 539.964292ms, expected [160ms,240ms]
FAIL
FAIL	time	6.615s
```

It's not obvious to me whether that's due to a bug in `TestTicker`, a bug in the timer support on that platform, or just a really overloaded builder.

CC @ianlancetaylor @bradfitz

**Comment by ianlancetaylor** [comment]
CC @eliasnaur in case there is something known about this.

**Comment by bcmills** [comment]
(And @steeve.)

**Comment by ianlancetaylor** [comment]
I committed a workaround to make the test pass by increasing the timeouts.

It would be nice if someone could figure out why that is necessary, though.
