### ISSUE TITLE
x/tools/gopls/test: frequent failures on freebsd-amd64-race builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#35691]
`golang.org/x/tools/gopls/test` is failing frequently on the `freebsd-amd64-race` builder.

Sample log: https://build.golang.org/log/92ec5a2b1e867f332c17d8040dc14dfeedb4a719

**Comment by stamblerre** [comment]
[CL 207904](https://go-review.googlesource.com/c/tools/+/207904) and [CL 207353](https://go-review.googlesource.com/c/tools/+/207353) fixed a number of issues with the cmd tests, so I think that this should be fixed. Please reopen if we still see this now.
