### ISSUE TITLE
docker build: cannot get the github public repository, x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by dayadev** [golang/go#35702]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.4 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
yes it does

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_4/g37z5y0j0t7dppmsyxymdsx00000gn
</pre></details>

### What did you do?
I am trying to build a docker image for my repo 
```


# Build the OS
FROM golang as builder

WORKDIR /app/

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build

FROM scratch

COPY --from=builder /app/services/mysvc /app/

# At Start, run app
ENTRYPOINT ["app/cmd"]

```
### What did you expect to see?

I expected it to build the image

### What did you see instead?
```

go: github.com/fatih/structs@v1.1.0: Get https://proxy.golang.org/github.com/fatih/structs/@v/v1.1.0.mod: x509: certificate signed by unknown authority
The command '/bin/sh -c go mod download' returned a non-zero code: 1
```

Is there a way to resolve this like using insecure for go mod download

**Comment by dayadev** [comment]
I even set the GOFLAGS=-insecure and still gets the same error

**Comment by opennota** [comment]
If the proxy doesn't work for you, you can bypass it by setting `GOPROXY` to `direct`.

https://golang.org/cmd/go/#hdr-Module_downloading_and_verification

**Comment by seankhliao** [comment]
have you considered securing things properly and installing the certificate store

**Comment by dayadev** [comment]
> have you considered securing things properly and installing the certificate store

I added below to get ca certs

```

RUN apk update \
    && apk upgrade \
    && apk add --no-cache \
    ca-certificates \
    && update-ca-certificates 2>/dev/null || true
```

This one started throwing
`
go: github.com/fatih/structs@v1.1.0: git init --bare in /go/pkg/mod/cache/vcs/4e175dc22ebfab3b60339501ebf7cc58217bb317b5287a96be389837560698e2: exec: "git": executable file not found in $PATH`

**Comment by seankhliao** [comment]
Did you read the error? Are you using an old version of go in the container?

**Comment by dayadev** [comment]
> Did you read the error? Are you using an old version of go in the container?

I am using `go version go1.13.4 linux/amd64` in the container

**Comment by seankhliao** [comment]
Your current error indicates you turned off the proxy and didn't install git

You should be doing one of either add ca-certs or add git and use GOPROXY=direct

**Comment by dayadev** [comment]
> Your current error indicates you turned off the proxy and didn't install git
> 
> You should be doing one of either add ca-certs or add git and use GOPROXY=direct

I tried this but still get
`go: google.golang.org/grpc@v1.25.1: unrecognized import path "google.golang.org/grpc" (https fetch: Get https://google.golang.org/grpc?go-get=1: x509: certificate signed by unknown authority)`

My docker file like you mentioned is 

```
RUN go env -w GOPROXY=direct
RUN apk add --no-cache git
RUN apk --no-cache add ca-certificates
```

**Comment by davecheney** [comment]
Errors of this kind can be caused by SSL proxies man in the middling you’re traffic. The certificate error occurs because the docker container you’re building in knows nothing about a custom CA which is users by SSL interceptors to decrypt and resign traffic. 

Do you think this could be occurring on your network?

**Comment by toothrot** [comment]
This issue tracker is for problems with the Go tools and standard library. It's unclear that this is an issue with the Go command, or the module mirror. A better place to ask this kind of question is golang-nuts, where there are many users of Docker and Go modules. See https://golang.org/wiki/Questions.

For reference, installing git may also be necessary in your scenario:
```RUN apk update && apk add --no-cache git ca-certificates && update-ca-certificates```

**Comment by dayadev** [comment]
> Errors of this kind can be caused by SSL proxies man in the middling you’re traffic. The certificate error occurs because the docker container you’re building in knows nothing about a custom CA which is users by SSL interceptors to decrypt and resign traffic. Do you think this could be occurring on your network?
> […](#)
> On 21 Nov 2019, at 08:57, dd ***@***.***> wrote: ﻿ Your current error indicates you turned off the proxy and didn't install git You should be doing one of either add ca-certs or add git and use GOPROXY=direct I tried this but still get go: ***@***.***: unrecognized import path "google.golang.org/grpc" (https fetch: Get https://google.golang.org/grpc?go-get=1: x509: certificate signed by unknown authority) My docker file like you mentioned is RUN go env -w GOPROXY=direct RUN apk add --no-cache git RUN apk --no-cache add ca-certificates — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

@davecheney  Well when I tried to do go get outside of dockerfile, it worked fine without any issues. So, if its the network then, I believe it would have failed outside of docker file too.

**Comment by padipai** [comment]
dns
