### ISSUE TITLE
net/http2 server: dumping decompressed frames

### ISSUE THREAD

**Issue by zanitee** [golang/go#35705]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 windows/amd64
</pre>

How would one dump (for debugging purposes) http2 requests made to the server? I've looked through the http2 server code and cannot find exactly where the request is getting decrypted and decompressed.

net/http2: https://github.com/golang/net/tree/master/http2

I'm looking to output something similar to the below:

> [id=1] [  4.573] send SETTINGS frame <length=6, flags=0x00, stream_id=0>
          (niv=1)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
[id=1] [  4.574] recv SETTINGS frame <length=18, flags=0x00, stream_id=0>
          (niv=3)
          [SETTINGS_ENABLE_PUSH(0x02):0]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):4194304]
          [SETTINGS_MAX_HEADER_LIST_SIZE(0x06):10485760]
[id=1] [  4.576] recv WINDOW_UPDATE frame <length=4, flags=0x00, stream_id=0>
          (window_size_increment=1073741824)
[id=1] [  4.577] send SETTINGS frame <length=0, flags=0x01, stream_id=0>
          ; ACK
          (niv=0)
[id=1] [  4.578] recv (stream_id=1) :authority: example.com
[id=1] [  4.578] recv (stream_id=1) :method: GET
[id=1] [  4.579] recv (stream_id=1) :path: /
[id=1] [  4.579] recv (stream_id=1) :scheme: https
[id=1] [  4.579] recv (stream_id=1) accept-encoding: none
[id=1] [  4.579] recv (stream_id=1) header4: 4
[id=1] [  4.579] recv (stream_id=1) header1: 1
[id=1] [  4.579] recv (stream_id=1) user-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
[id=1] [  4.579] recv (stream_id=1) header3: 3
[id=1] [  4.579] recv (stream_id=1) header2: 2
[id=1] [  4.579] recv HEADERS frame <length=147, flags=0x05, stream_id=1>
          ; END_STREAM | END_HEADERS
          (padlen=0)
          ; Open new stream
[id=1] [  4.579] send HEADERS frame <length=71, flags=0x04, stream_id=1>
          ; END_HEADERS
          (padlen=0)
          ; First response header
          :status: 404
          server: apache
          date: Wed, 20 Nov 2019 01:42:56 GMT
          content-type: text/html; charset=UTF-8
          content-length: 150
[id=1] [  4.579] send DATA frame <length=150, flags=0x01, stream_id=1>
          ; END_STREAM

**Comment by bradfitz** [comment]
Set GODEBUG=http2debug=2. (documented in the net/http docs)
