### ISSUE TITLE
x/build/cmd/coordinator: trybot (slowbot) was in a "running" state for 2+ hours

### ISSUE THREAD

**Issue by dmitshur** [golang/go#35700]
While in the process of deploying a new version of coordinator with @cagedmantis, one of the active trybot runs was a slowbot run for patch set 2 of [CL 207858](https://golang.org/cl/207858). What stood out was that the `aix-ppc64` builder was running for excessively long and timing out:

<img src="https://user-images.githubusercontent.com/1924134/69174002-f6e58880-0ace-11ea-9148-215151d508ab.png" width=461px>

![image](https://user-images.githubusercontent.com/1924134/69174023-006ef080-0acf-11ea-8d3c-dd72c5da2697.png)

<details><br>

```
Change-ID: sys~master~Ia0b452f96b08cbb69a0b64cc2a467b5cf94e72da Commit: 25a8c4258c1770d56358edb5ade42803d2c7dca0 (status)
   Remain: 1, fails: []
  android-amd64-emu: running=false
  freebsd-386-11_2: running=false
  freebsd-amd64-11_2: running=false
  freebsd-amd64-12_0: running=false
  linux-386: running=false
  linux-amd64: running=false
  linux-amd64-race: running=false
  netbsd-amd64-8_0: running=false
  openbsd-386-64: running=false
  openbsd-amd64-64: running=false
  windows-386-2008: running=false
  windows-amd64-2016: running=false
  aix-ppc64: running=true
  darwin-amd64-10_14: running=false
  dragonfly-amd64: running=false
  illumos-amd64: running=false
  solaris-amd64-oraclerel: running=false
  linux-amd64: running=false
  linux-amd64: running=false
```

Its temporary log was:

```
  builder: aix-ppc64
      rev: 8cf5293caa7071601fa90358abdd20a0b787e178
 buildlet: (nil *buildlet.Client)
  started: 2019-11-19 15:02:52.179254691 +0000 UTC m=+317165.846668715
   status: still running

Events:
  2019-11-19T15:02:52Z checking_for_snapshot 
  2019-11-19T15:02:52Z finish_checking_for_snapshot after 25.8ms
  2019-11-19T15:02:52Z get_buildlet 
 +11724.5s (now)

Build log:


(buildlet still starting; no live streaming. reload manually to see status)
```

Relevant details for the `host-aix-ppc64-osuosl` builder at the time were as follows.

### Scheduler state

- host-aix-ppc64-osuosl: 39 waiting (oldest 90h48m54s, newest 1h24m35s, progress 3h44m22s)
    - try: 1 (oldest 2h46m21s, newest 2h46m21s)

### Buildlet pools

Reverse pool by host type (in use / total)
- host-aix-ppc64-osuosl: 1/1

### Reverse pool machine detail

power8-aix-host1 (140.211.9.26:37646) version 23, host-aix-ppc64-osuosl: connected 3h44m22.7s, working for 3h44m22.7s

### Active builds

```
aix-ppc64 rev 7719016e; running; http://power8-aix-host1 reverse peer power8-aix-host1/140.211.9.26:37646 for host type host-aix-ppc64-osuosl, 90h48m51s ago
...
  2019-11-19T17:48:03Z still_waiting_on_test go_test:net/http
  2019-11-19T17:48:33Z still_waiting_on_test go_test:net/http
  2019-11-19T17:49:03Z still_waiting_on_test go_test:net/http
   +9.7s (now)
```

</details>

Filing this issue so we can discuss and investigate if needed after coordinator is deployed. /cc @bradfitz @cagedmantis @toothrot

At first glance, I thought it was a problem that a trybot didn't timeout/retry/fail after 2 hours, but given it was in "waiting_for_machine" state, maybe waiting indefinitely is the right thing?

**Comment by bradfitz** [comment]
I don't see a problem.

AIX is slow & backlogged. I'll be surfacing the scheduler state in more places (including here). I just sent out https://go-review.googlesource.com/c/build/+/207841 which is a start.

**Comment by bradfitz** [comment]
https://farmer.golang.org/#sched says:

```
host-aix-ppc64-osuosl: 42 waiting (oldest 91h33m35s, newest 15m40s, progress 4h29m2s)
try: 1 (oldest 3h31m2s, newest 3h31m2s)
```

And down below, the single AIX machine:

```
power8-aix-host1 (140.211.9.26:37646) version 23, host-aix-ppc64-osuosl: connected 4h29m3.6s, working for 4h29m3.6s
```

It's been working for 4 hours.

That slowness should be fixed by https://go-review.googlesource.com/c/go/+/207497

**Comment by dmitshur** [comment]
Ok, so the situation was that the AIX builder was already occupied doing another build, so the slowbot was waiting for the builder to free up. That does sound like things are working as intended.

I misread it as the AIX builder being free and yet not being scheduled. I see now that it was 1/1 in use.

Thanks for confirming Brad. 👍
