### ISSUE TITLE
cmd/go: tests fail without network

### ISSUE THREAD

**Issue by mwhudson** [golang/go#35703]
### What version of Go are you using (`go version`)?

Anything after 42db1da8e9def3490ed904594ad80e1090bff654

### Does this issue reproduce with the latest release?

Not in a released version yet.

### What operating system and processor architecture are you using (`go env`)?

Ubuntu 18.04, but it doesn't matter.

### What did you do?

I build a go snap from tip daily in Launchpad (an environment where there is no network access).

### What did you expect to see?

Tests passing.

### What did you see instead?

```
go test proxy running at GOPROXY=http://127.0.0.1:43782/mod
go proxy: no archive rsc.io v1.5.2: file does not exist
go proxy: no archive rsc.io v1.0.0: file does not exist
go proxy: no archive rsc.io v1.0.0: file does not exist
go proxy: no archive rsc.io v1.0.0: file does not exist
go proxy: no archive rsc.io v1.0.0: file does not exist
go proxy: no archive rsc.io v1.1.0: file does not exist
go proxy: no archive rsc.io v1.5.1: file does not exist
go proxy: no archive example.com/newcycle v1.0.0: file does not exist
go proxy: no archive rsc.io v1.5.2: file does not exist
--- FAIL: TestScript (0.00s)
    --- FAIL: TestScript/mod_convert_tsv_insecure (0.08s)
        script_test.go:192: 
            # secure fetch should report insecure warning (0.081s)
            > cd $WORK/test
            $WORK/test
            > go mod init
            [stderr]
            go: creating new go.mod: module m
            go: copying requirements from dependencies.tsv
            go: converting dependencies.tsv: stat vcs-test.golang.org/insecure/go/insecure@6fecd21f7c0c: unrecognized import path "vcs-test.golang.org/insecure/go/insecure": https fetch: Get "https://vcs-test.golang.org/insecure/go/insecure?go-get=1": dial tcp: lookup vcs-test.golang.org on 10.189.128.2:53: no such host
            > stderr 'redirected .* to insecure URL'
            FAIL: testdata/script/mod_convert_tsv_insecure.txt:6: no match for `(?m)redirected .* to insecure URL` found in stderr
            
FAIL
FAIL	cmd/go	40.362s
```

I'm not completely sure it was 42db1da8e9def3490ed904594ad80e1090bff654 but the dates do line up.

**Comment by ianlancetaylor** [comment]
CC @bcmills @jayconrod @witchard

**Comment by oiooj** [comment]
> dial tcp: lookup vcs-test.golang.org on 10.189.128.2:53: no such host
Please change a DNS server and run test again. @mwhudson

**Comment by ianlancetaylor** [comment]
@oiooj The point is that the test should work by default when no network is available.  The cmd/go/testdata/script tests that require a network should all be marked with `[!net] skip`.

**Comment by oiooj** [comment]
Oh yes, Let me fix this.

**Comment by mwhudson** [comment]
Hi, thanks for the quick fix :)
