### ISSUE TITLE
x/build/cmd/coordinator: implement trybot set cancellation

### ISSUE THREAD

**Issue by bradfitz** [golang/go#35701]
TryBot runs can't be canceled right now. It's mostly implemented, but ends here:

```go
// cancelBuilds run in its own goroutine and cancels this trySet's                                                                                                   
// currently-active builds because they're no longer wanted.                                                                                                         
func (ts *trySet) cancelBuilds() {
        // TODO(bradfitz): implement                                                                                                                                 
}
```

So they don't actually cancel.

/cc @cagedmantis @dmitshur @bcmills

**Comment by agnivade** [comment]
Pardon the comment on a closed issue, but it wasn't clear in the CL, so I wanted to clarify: When does the cancellation happen ? Can it be triggered from the UI ? Or it is always automatic ? If so, does it happen when someone uploads a new patchset while an existing run is happening ?

**Comment by dmitshur** [comment]
I understand what's implemented now is that when a "Run-TryRun" vote is deleted, the try run is canceled. For example, see https://go-review.googlesource.com/c/sys/+/207858/3#message-dfc5c634bdb023398d74a476d3ba5f100beef00f.

**Comment by agnivade** [comment]
Thanks. That looks like one needs the "Delete-tryrun" permission bits. It would be nice to have it automatically cancel a running build when a new patchset is mailed.

**Comment by bradfitz** [comment]
@agnivade, new patchsets automatically delete the Run-TryBot vote, because we don't have https://gerrit-review.googlesource.com/Documentation/config-labels.html#label_copyMaxScore set to true on that label.

So you don't need any new permissions to cancel a trybot run. You just need to upload a new patchset.
