### ISSUE TITLE
gollvm: invalid type conversion (cannot use type syscall.Timespec as type unix.Timespec)

### ISSUE THREAD

**Issue by heylinn** [golang/go#35713]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 gollvm LLVM 10.0.0svn linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<pre>
$ uname -m -v
#1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64

$ cat /etc/debian_version 
9.4
</pre>

### What did you do?

<pre>
$ git clone https://github.com/docker/docker-ce.git
$ cd docker-ce
$ git checkout v19.03.4
$ cd components
$ mkdir -p .gopath/src/github.com/docker
$ export GOPATH=`pwd`/.gopath:~/go
$ ln -sf `pwd`/engine .gopath/src/github.com/docker/docker
$ cd .gopath/src/github.com/docker/docker
$ go build github.com/docker/docker/cmd/dockerd
$ go build -tags 'autogen netgo osusergo static_build' github.com/docker/docker/cmd/dockerd
</pre>

### What did you expect to see?
Clean compilation.

### What did you see instead?

<pre>
$ go build -tags 'autogen netgo osusergo static_build' github.com/docker/docker/cmd/dockerd                                                                                                                                                  
# github.com/docker/docker/vendor/github.com/containerd/continuity/fs
vendor/github.com/containerd/continuity/fs/copy_linux.go:54:43: error: invalid type conversion (cannot use type syscall.Timespec as type unix.Timespec)
vendor/github.com/containerd/continuity/fs/copy_linux.go:54:73: error: invalid type conversion (cannot use type syscall.Timespec as type unix.Timespec)
</pre>

The issue is reproduced for gccgo too, but I haven't checked it with the latest release of gccgo.
<pre>
$ go version
go version go1.10.3 gccgo (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0 linux/amd64
</pre>

**Comment by ianlancetaylor** [comment]
Here is a simple test case.

```Go
package p

import (
	"syscall"

	"golang.org/x/sys/unix"
)

func F() syscall.Timespec {
	return syscall.Timespec{}
}

var V = unix.Timespec(F())
```

This compiles with gc, but with gccgo gets

```
foo.go:13:22: error: invalid type conversion (cannot use type syscall.Timespec as type unix.Timespec)
   13 | var V = unix.Timespec(F())
      |                      ^
```

**Comment by ianlancetaylor** [comment]
This is because for the gc compiler the definition of `syscall.Timespec` and `unix.Timespec` are the same, but the gccgo version is different.  We might be able to use type aliases to make this work.

**Comment by heylinn** [comment]
Thank you!
After this fix I have found another type conversion error: #35739 
Sorry for reporting frequently. Hope it helps to make the project better.

**Comment by ianlancetaylor** [comment]
Please do report bugs.  Thanks.
