### ISSUE TITLE
x/tools/gopls: triggers packages.Load on ctrl-hover

### ISSUE THREAD

**Issue by heschik** [golang/go#35716]
#### Build info

```
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@(devel)
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20191017151554-a3bc800455d5 => ../
    golang.org/x/xerrors@v0.0.0-20190717185122-a985d3407aa7 h1:9zdDQZ7Thm29KFXgAX/+yaf3eVbP7djjWp/dXAppNCc=
    honnef.co/go/tools@v0.0.1-2019.2.3 h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=
```

#### Go info

```
go version go1.13.4 linux/amd64
```

### What did you do?

Hovered over an indentifier with the ctrl key held down in VSCode.

### What did you expect to see?

A hover more or less instantly.

### What did you see instead?

Delay due to a packages.Load call. The hover triggers a didOpen for the file that declares the identifier I'm hovering over, and that didOpen seems to trigger a packages.Load call on it.

**Comment by stamblerre** [comment]
As of [CL 208265](https://go-review.googlesource.com/c/tools/+/208265), we no longer call `go/packages.Load` on file opens, so this should be fixed now.
