### ISSUE TITLE
panic: JSON decoder out of sync - data changing underfoot?

### ISSUE THREAD

**Issue by Novicel** [golang/go#35725]
### What version of Go are you using (`go version`)?

<pre>
$ go version
 go 1.13.4 

</pre>

### Does this issue reproduce with the latest release?

Yes, i use the  latest release go1.13.4

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\goworkspace
set GOPRIVATE=
set GOPROXY=https://goproxy.io
set GOROOT=D:\GO
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\GO\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\13\go-build340646406=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
- [ ] main():
  ``` ...
    c := make(chan []byte, 1 << 10)
	for _, f := range files{
	    go ReadFromFile(c, f)
	}
	go ParseData(c, signal, len(files))
     ...
```
- [ ] ReadFromFile(c chan<- []byte, file string): 
    ```
    for {
		line, isPrefix, err := buf.ReadLine()
		if err != nil {
			if err != io.EOF {
				log.Printf("file:%s\t%s\n",file, err.Error())
				break
			}
			c <- line
			log.Printf("read over%s\n", file)
			break
		}
		if isPrefix {
			log.Printf("line to long：\t%s\n", file)
			break
		}
		c <- line
	}
```
- [ ] ParseData(c <-chan []byte): 
```
    for line := range c {
		l := make(map[string]interface{})
		err := json.Unmarshal(line, &l)
		if err != nil {
			log.Printf("json.Unmarshal(line, &m):\t%s\n", line)
			log.Printf("json.Unmarshal(line, &m):\t%s\n", err.Error())
			continue
		}
		lines = append(lines, l)
     }
```

### What did you expect to see?
when i program run, the func ParseData(c <-chan []byte) will panic: JSON decoder out of sync - data changing underfoot?
### What did you see instead?
panic: JSON decoder out of sync - data changing underfoot?

goroutine 42 [running]:
encoding/json.(*decodeState).value(0xc0002f3a20, 0x801480, 0xc0003182f0, 0x194, 0xc0003183b0, 0x94)
	D:/Go/src/encoding/json/decode.go:415 +0x23b
encoding/json.(*decodeState).object(0xc0002f3a20, 0x7d8320, 0xc0002962a0, 0x16, 0xc0002f3a48, 0xc00030987b)
	D:/Go/src/encoding/json/decode.go:823 +0x1399
encoding/json.(*decodeState).value(0xc0002f3a20, 0x7d8320, 0xc0002962a0, 0x16, 0xc00012de48, 0x59e724)
	D:/Go/src/encoding/json/decode.go:429 +0x74
encoding/json.(*decodeState).unmarshal(0xc0002f3a20, 0x7d8320, 0xc0002962a0, 0xc0002f3a48, 0x0)
	D:/Go/src/encoding/json/decode.go:179 +0x202
encoding/json.Unmarshal(0xc0001971e2, 0x161, 0xfae1e, 0x7d8320, 0xc0002962a0, 0x0, 0x0)
	D:/Go/src/encoding/json/decode.go:106 +0x119
novicel/dataload/ck.(*DBWorker).ParseDataNew(0xc0000e62a0, 0xc0000e6840, 0xc0001162a0, 0x1)
	E:/go_workspace/dataload/ck/ck.go:178 +0x26f
created by novicel/dataload/api.FileExec
	E:/go_workspace/dataload/api/api.go:83 +0x363

**Comment by bradfitz** [comment]
https://golang.org/pkg/bufio/#Reader.ReadLine says in part:

> The returned buffer is only valid until the next call to ReadLine. ReadLine either returns a non-nil line or it returns an error, never both.

You have a race.

The race detector should show that too. (https://blog.golang.org/race-detector)

Use ReadString instead. Or bufio.Scanner and its Text method.
