### ISSUE TITLE
misc/wasm: using wasm_exec.js in a NodeJs project

### ISSUE THREAD

**Issue by Mikerah** [golang/go#35729]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.13.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mikerah/snap/code/common/.cache/go-build"
GOENV="/home/mikerah/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mikerah/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build686789620=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I'm currently trying to use `wasm_exec.js` in a nodejs project. The way I am importing the file into my project is by using the `require` statement i.e. `const wasm_exec = require("./wasm_exec.js")`.

### What did you expect to see?
Nothing. This program doesn't print to standard output.

### What did you see instead?
The following error
`
.../wasm_exec.js:85
        }console.log(fetch);
                     ^
ReferenceError: fetch is not defined
`
It seems like this file is choosing the wrong environment and is seeking the browser environment instead of the nodejs environment.

**Comment by neelance** [comment]
`fetch` is not referenced by the wasm_exec.js on master. Your error message looks like you have a line `}console.log(fetch);` in your version of wasm_exec.js.

If you're planning to use `net/http` package, which requires `fetch`, then you should use a polyfill like https://www.npmjs.com/package/node-fetch.

**Comment by Mikerah** [comment]
I have `go version go1.13.4 linux/amd64` installed. However, looking through this repo, I see that I indeed have a different version of `wasm_exec.js` than the one in this repo. I will attempt to simply clone this repo and copy the `wasm_exec.js` file from the repo into my project and see if it fixes anything.
