### ISSUE TITLE
cmd/go: module declares its path as: golang.org/x/lint but was required as: github.com/golang/lint Makefile:12: recipe for target 'build' failed

### ISSUE THREAD

**Issue by ying2025** [golang/go#35723]
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod:
module declares its path as: golang.org/x/lint
but was required as: github.com/golang/lint
Makefile:12: recipe for target 'build' failed
make: *** [build] Error 1
zhr@ubuntu:~/gospace/src/gith

My go version is go1.13.4 linux/amd64  @bcmills

**Comment by toothrot** [comment]
@ying2025 The lint package should be imported as it's canonical path `golang.org/x/lint`. Is your code importing `github.com/golang/lint` somewhere?
