### ISSUE TITLE
cmd/go: panic during 'go mod tidy' if a line ends with an empty comment

### ISSUE THREAD

**Issue by MToolMakerJB** [golang/go#35737]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ivan.yarkov/Library/Caches/go-build"
GOENV="/Users/ivan.yarkov/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=" -mod="
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/ivan.yarkov/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/ivan.yarkov/awesomeProject11/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bf/qzrd9gxj04j10kx_8lt3pbrm0000gp/T/go-build568351457=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

module awesomeProject11
Run go mod tidy on the following example:
```
go 1.13

require (
	github.com/inconshreveable/mousetrap v1.0.0 //
	github.com/spf13/cobra v0.0.3
	github.com/spf13/pflag v1.0.5 // indirect
)
```

### What did you expect to see?

I expect it work without failing.

### What did you see instead?
I get:
```
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
cmd/go/internal/modfile.setIndirect(0xc0000c3900, 0xc00015f501)
        /usr/local/go/src/cmd/go/internal/modfile/rule.go:335 +0x31b
cmd/go/internal/modfile.(*File).SetRequire(0xc000032480, 0xc0002f5640, 0x3, 0x4)
        /usr/local/go/src/cmd/go/internal/modfile/rule.go:571 +0xb0a
cmd/go/internal/modload.WriteGoMod()
        /usr/local/go/src/cmd/go/internal/modload/init.go:673 +0x2ea
cmd/go/internal/modload.loadAll(0x78a00101, 0x7, 0xc000024048, 0x6)
        /usr/local/go/src/cmd/go/internal/modload/load.go:386 +0x215
cmd/go/internal/modload.LoadALL(...)
        /usr/local/go/src/cmd/go/internal/modload/load.go:364
cmd/go/internal/modcmd.runTidy(0x1aa5680, 0xc0000201d0, 0x0, 0x0)
        /usr/local/go/src/cmd/go/internal/modcmd/tidy.go:48 +0xb1
main.main()
        /usr/local/go/src/cmd/go/main.go:189 +0x57f
```
###
I think the problem is absence parentheses:
```
if len(com.Token) > 2 && com.Token[2] == ' ' || com.Token[2] == '\t' {
     space = ""
}

```
It should probably be:
```
if len(com.Token) > 2 && (com.Token[2] == ' ' || com.Token[2] == '\t') {
     space = ""
}

```

**Comment by fsouza** [comment]
@bcmills I've started working on this, I have a reproducer script in the main repo and a proposed fix in x/mod.

I haven't used gerrit in a while though, let me know if I do anything wrong 🙈
