### ISSUE TITLE
x/tools/go/analysis/passes/shadow: "go vet --shadow" doesn't check global variable shadowing

### ISSUE THREAD

**Issue by rnv5** [golang/go#35731]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.9 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Not tested with latest 1.13 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build945518265=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

package main

import (
	"fmt"
)

var testStr string

func main() {
	if testStr != "" {
		fmt.Println("Not empty")
	}
	testStr := "Test string"
	fmt.Println(testStr)
}

### What did you expect to see?
After executing the following command, I would expect to throw error related to shadowing
$ go vet -vettool=$(which shadow)
$

### What did you see instead?
Nothing was printed as output

**Comment by toothrot** [comment]
@rnv5 It looks like shadow supports this with the `-strict` flag:


I tested it with your sample code:

```
$ go vet -vettool="$(which shadow)" -strict .
# vet
./vet.go:13:2: declaration of "testStr" shadows declaration at line 7
```

Does this work for you?
