### ISSUE TITLE
gollvm: invalid type conversion (type has no methods)

### ISSUE THREAD

**Issue by heylinn** [golang/go#35739]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.13 gollvm LLVM 10.0.0svn linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
<pre>
$ uname -m -v

#1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64
$ cat /etc/debian_version 
9.4
</pre>

### What did you do?
<pre>
$ git clone https://github.com/docker/docker-ce.git
$ cd docker-ce
$ git checkout v19.03.4
$ cd components
$ mkdir -p .gopath/src/github.com/docker
$ export GOPATH=`pwd`/.gopath:~/go
$ ln -sf `pwd`/engine .gopath/src/github.com/docker/docker
$ cd .gopath/src/github.com/docker/docker
$ go build -tags 'autogen netgo osusergo static_build' github.com/docker/docker/cmd/dockerd
</pre>

### What did you expect to see?
Clean compilation.

### What did you see instead?
<pre>
$ go build -tags 'autogen netgo osusergo static_build' github.com/docker/docker/cmd/dockerd
# github.com/docker/docker/daemon
.gopath/github.com/docker/docker/volume/service/errors.go:70:0: error: invalid type conversion (type has no methods)
</pre>

**Comment by thanm** [comment]
I will take a look.

**Comment by Civil** [comment]
There is a minimal test case (or mostly minimal) that I've created:

main.go:
```
package main

import (
        "test/service"
)

func main() {
        _ = service.IsInUse(nil)
}
```
service/errors.go:
```
package service

const (
        errVolumeInUse conflictError = "volume is in use"
)

type conflictError string

func (e conflictError) Error() string {
        return string(e)
}

func IsInUse(err error) bool {
        return isErr(err, errVolumeInUse)
}

func isErr(err error, expected error) bool {
        return err == expected
}
```

So far to workaround the issue it is enough to:
1. Get rid of service package. If everything in main - it will compile.
2. If I manually inline isErr function - everything will be fine.
