### ISSUE TITLE
cmd/go: generate a better error message for imports of nonexistent non-module paths

### ISSUE THREAD

**Issue by RahulKandagatla** [golang/go#35734]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13
</pre>

### Does this issue reproduce with the latest release?
I dont know

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre>set GO111MODULE=
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\RAHUL\AppData\Local\go-build
set GOENV=C:\Users\RAHUL\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=386
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\go-work
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=sse2
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\RAHUL\AppData\Local\Temp\go-build469851946=/tmp/go-build -gno-record-gcc-switches</details>

### What did you do?

$go mod init github.com/xxxx

$go build

### What did you expect to see?
a builld of my project

### What did you see instead?
build github.com/xxxx: cannot load xxxx/models: malformed module path "xxxx/models": missing dot in first path element

**Comment by ALTree** [comment]
Probably a dup of #35273. Can you trip with the current tip (soon to be 1.14)? It should print a better error (if your actually in the same situation described in #35273).

**Comment by bcmills** [comment]
This has the same underlying cause as #34769.
