### ISSUE TITLE
x/build: frequent "unexpected stale targets" on linux-arm-arm5spacemonkey after bootstrapping is complete

### ISSUE THREAD

**Issue by bcmills** [golang/go#35740]
[2019-11-20T22:38:34-39a9cb4/linux-arm-arm5spacemonkey](https://build.golang.org/log/1c472bf793425147045e40d517d5a719f30e3673)
[2019-11-20T22:37:23-be04718/linux-arm-arm5spacemonkey](https://build.golang.org/log/ee5ff908ee18df7fafa6234e78068cb0cf5465bf)
[2019-11-19T06:10:03-8cf5293/linux-arm-arm5spacemonkey](https://build.golang.org/log/44761b583bef2914496ae2164c7a5aa2cba528f0)
[2019-11-19T06:08:56-1046a9c/linux-arm-arm5spacemonkey](https://build.golang.org/log/f87baffbb6a8b96f888a8c1eaa1d37d8f98d82d4)
[2019-11-16T20:31:45-6ba0be1/linux-arm-arm5spacemonkey](https://build.golang.org/log/850728261015b1f4cb0bb4d9569b06f7d8a4dc32)
[2019-11-16T02:06:39-c20b71e/linux-arm-arm5spacemonkey](https://build.golang.org/log/6583352eb3bdfd299b96628447620809b108bbca)
[2019-11-16T00:02:02-5042317/linux-arm-arm5spacemonkey](https://build.golang.org/log/f8eef96b49fb41984cbeee3476cda469918d4fd8)
[2019-11-15T22:47:41-72f333a/linux-arm-arm5spacemonkey](https://build.golang.org/log/3cf3d25d9f34ecc7ce2f6d107a8c237373f8dff3)

See also #33598, but the failure mode here is somewhat different: in that issue the failure always occurs during toolchain3 bootstrapping, whereas here it always occurs after `make.bash` is complete.

CC @jayconrod @cagedmantis @toothrot @dmitshur @bradfitz

**Comment by bcmills** [comment]
This failure mode is now happening on every build.

@esnolte, you are listed as the owner of that builder [here](https://github.com/golang/build/blob/6b2867eab46056b7c8e75fbfadfa40dc43dbdf91/dashboard/builders.go#L217). Could you please investigate?

I wonder if the problem is somehow that multiple builds are running at the same time. (A similar failure mode in #35749 turned out to be an older builder running concurrently with the current one.)

**Comment by esnolte** [comment]
The builder is in a loop filling the logs and eventually the filesystem with:

Dec 18 19:01:57 localhost logger: stage0: 2019/12/18 19:01:57 downloading https://storage.googleapis.com/go-builder-data/buildlet.linux-arm-arm5 to ./buildlet.exe ...
Dec 18 19:01:57 localhost logger: stage0: 2019/12/18 19:01:57 downloaded ./buildlet.exe (12317133 bytes)
Dec 18 19:01:57 localhost logger: stage0: 2019/12/18 19:01:57 downloaded buildlet in 200ms
Dec 18 19:01:57 localhost logger: 2019/12/18 19:01:57 buildlet starting.
Dec 18 19:01:57 localhost logger: 2019/12/18 19:01:57 unlinkat /home/builder/stage0scratch/workdir/tmp/TestModReplace2195897861/gopath/pkg/mod/rsc.io/sampler@v1.3.0/glass_test.go: permission denied

Here is the service we're running:

root@go-builder-2:/home/builder# cat /etc/service/stage0/run
#!/bin/bash

set -e

SCRATCH=~builder/stage0scratch
export TMPDIR=${SCRATCH}/tmp
export WORKDIR=${SCRATCH}/workdir

mkdir -p ${TMPDIR}
mkdir -p ${WORKDIR}
chown -R builder:builder ${SCRATCH}
cd ${SCRATCH}

export GO_BUILDER_ENV=linux-arm-arm5spacemonkey
export GO_TEST_TIMEOUT_SCALE=5
export USER=builder
export HOME=/home/builder
exec bash -c "setuidgid builder /usr/local/bin/stage0 2>&1 | logger"k

The builder is a binary installed in 2017:

root@go-builder-2:/usr/local/bin# ls -l
total 4912
-rwxr-xr-x 1 root root 5013776 Aug 29  2017 stage0

root@go-builder-2:/usr/local/bin# file stage0
stage0: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, not stripped

root@go-builder-2:/usr/local/bin# sha1sum stage0
74ae93f72bcb193778383fd7113a5310f74c2e7c  stage0

Should I delete stage0scratch and see if that helps or am I running an old builder and need to upgrade it?

- Erik

**Comment by esnolte** [comment]
I deleted stage0scratch and restarted the builder and things look better.  I'm not sure when the results will show up on https://build.golang.org/# <https://build.golang.org/#>

**Comment by bcmills** [comment]
That doesn't seem to have fixed the problem. (https://build.golang.org/log/08d3ac2849287e18678df797c542b7329dab3d3e)

**Comment by esnolte** [comment]
I've unplugged a rogue builder we no longer have access to (go-builder-3).  It looks like the other 2 builders are passing tests.

**Comment by bcmills** [comment]
Hmm, now https://farmer.golang.org/ shows 0/2 `host-linux-arm5spacemonkey` hosts available, but lists them both as connected:

> **Reverse pool by host type** (in use / total)
> * […]
> * host-linux-arm5spacemonkey: 0/2 (1 missing)

> * go-builder-1 (69.58.94.166:38292) version 24, host-linux-arm5spacemonkey: connected 50m45.9s, idle for 3.41s
> * go-builder-2 (69.58.94.166:27320) version 24, host-linux-arm5spacemonkey: connected 1h18m43.9s, idle for 10.2s

> * linux-arm-arm5spacemonkey rev a197c7bb; waiting_for_machine, 2m28s ago

**Comment by dmitshur** [comment]
> I've unplugged a rogue builder we no longer have access to (go-builder-3).  It looks like the other 2 builders are passing tests.

By now, this seems to be accurately reflected under the "Reverse pool by host type (in use / total)" section of https://farmer.golang.org/#pools:

> host-linux-arm5spacemonkey: 2/2 (1 missing)

I'm not sure why it was showing something else before.

**Comment by esnolte** [comment]
I rebooted everything 30 minutes ago.  Maybe that unwedged the builders.

**Comment by ianlancetaylor** [comment]
The original problem is still happening.

**Comment by bradfitz** [comment]
IIRC, the arm5 builders start with a cross-compiled make.bash from a linux-amd64 machine. Perhaps the two environments have drifted?

**Comment by esnolte** [comment]
What is the next step?  Should I rebuild stage0 with the most recent source?

I've cloned https://github.com/golang/build and tried building build/cmd/buildlet/stage0 but am missing dependencies like golang.org/x/build/internal/{httpdl,untar} and cloud.google.com/go/compute/metadata.

Are there directions for building stage0?

**Comment by cagedmantis** [comment]
Closing this issue as the associated builder has been removed as part of #41027.
