### ISSUE TITLE
net/http: Server.ConnContext accidentally modifies context for all connections

### ISSUE THREAD

**Issue by rkollar** [golang/go#35750]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What did you do?
Docs of ConnContext say that:
> ConnContext optionally specifies a function that modifies the context used for a new connection c.

However, it assigns this new context to a variable shared between connections in the accept loop. Thus creating a growing chain of contexts.

Example code:
```
package main

import (
	"context"
	"fmt"
	"net"
	"net/http"
)

func main() {
	server := &http.Server{
		Addr: ":4444",
		Handler: http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
			rw.Header().Set("Connection", "close")
		}),
		ConnContext: func(ctx context.Context, c net.Conn) context.Context {
			fmt.Printf("conn: %s\n", c.RemoteAddr())

			if c2 := ctx.Value("conn"); c2 != nil {
				fmt.Printf("existing: %s\n", c2.(net.Conn).RemoteAddr())
			}

			return context.WithValue(ctx, "conn", c)
		},
	}
	go func() {
		panic(server.ListenAndServe())
	}()

	var err error

	fmt.Printf("\nrequest 1:\n")
	_, err = http.Get("http://localhost:4444/")
	if err != nil {
		panic(err)
	}
	fmt.Printf("request 1 done\n")

	fmt.Printf("\nrequest 2:\n")
	_, err = http.Get("http://localhost:4444/")
	if err != nil {
		panic(err)
	}
	fmt.Printf("request 2 done\n")
}
```

### What did you expect to see?
<pre>

request 1:
conn: [::1]:34022
request 1 done

request 2:
conn: [::1]:34024
request 2 done
</pre>

### What did you see instead?
<pre>
request 1:
conn: [::1]:34022
request 1 done

request 2:
conn: [::1]:34024
existing: [::1]:34022
request 2 done
</pre>

**Comment by bradfitz** [comment]
Wow, whoops. Thanks for the report!

**Comment by rkollar** [comment]
I would like to note that this _could_ have some security implications. A large number of connections will eat both CPU and memory. For example: ![context.propagateCancel](https://user-images.githubusercontent.com/10644651/69378451-ae84c100-0cae-11ea-849b-66c641766d10.png))

**Comment by bradfitz** [comment]
@rkollar, no need to convince me of its importance; I was already planning to backport this to previous releases. I'm just waiting on a test in that PR/CL. I can take the change over if you'd like.

**Comment by rkollar** [comment]
@bradfitz I'm already working on it, but it's my first submission and I have to go over the existing tests to learn what are the conventions. You can take over if you don't want to wait.

**Comment by bradfitz** [comment]
@gopherbot, please backport to Go 1.13.

**Comment by agirbal** [comment]
Ah we just spent many hours trying to figure out why there seemed to be a massive memory leak following the use of this feature... Good catch and can't wait for fix!
