### ISSUE TITLE
runtime: TestStackWrapperStackPanic failure on windows-amd64-2016

### ISSUE THREAD

**Issue by bcmills** [golang/go#35773]
https://storage.googleapis.com/go-build-log/07ca05df/windows-amd64-2016_8338c7a2.log

```
##### GOMAXPROCS=2 runtime -cpu=1,2,4 -quick
--- FAIL: TestStackWrapperStackPanic (0.00s)
    --- FAIL: TestStackWrapperStackPanic/sigpanic (0.00s)
        --- FAIL: TestStackWrapperStackPanic/sigpanic/CallersFrames (0.00s)
            stack_test.go:676: runtime.Callers
            stack_test.go:676: runtime_test.testStackWrapperPanic.func1.1
            stack_test.go:676: runtime.gopanic
            stack_test.go:676: runtime.panicmem
            stack_test.go:676: runtime.sigpanic
            stack_test.go:676: runtime.asyncPreempt
            stack_test.go:676: runtime_test.TestStackWrapperStackPanic.func1.1
            stack_test.go:676: runtime_test.testStackWrapperPanic.func1
            stack_test.go:676: testing.tRunner
            stack_test.go:676: runtime.goexit
            stack_test.go:684: panicking wrapper runtime_test.I.M missing from stack trace
FAIL
FAIL	runtime	27.302s
```

CC @aclements @cherrymui @mknyszek @danscales

**Comment by bcmills** [comment]
Marking as release-blocker since `runtime.asyncPreempt` is involved. (We can re-evaluate that once we better understand the root cause.)

**Comment by bcmills** [comment]
[2019-11-21T14:55:12-8bbfc51/windows-amd64-2008](https://build.golang.org/log/f8ab2039cd66285c3cb46fbff33aee830ae73db1)

**Comment by ianlancetaylor** [comment]
[2019-12-05T17:23:50-50535e6/windows-amd64-2012](https://build.golang.org/log/a9b40df11e840ab3b09c5a2f64bc1ac005b9e623)
[2019-12-05T03:44:34-7bdef2d/windows-amd64-longtest](https://build.golang.org/log/9e63809cdc01c678d17205a6802bcb7973677ae0)
[2019-12-04T21:29:42-ae2e244/windows-amd64-2012](https://build.golang.org/log/d0cf743d8ec33222d3c24b028165cc44b585bea2)
[2019-11-27T20:27:15-9174e2c/windows-amd64-2016](https://build.golang.org/log/9f945a05c66224c4918725db60652e913898f859)
[2019-11-26T12:03:08-20bf6a4/windows-amd64-2016](https://build.golang.org/log/c292a2ed4f3456b54899434bc2c998791bc47284)

**Comment by ianlancetaylor** [comment]
The failure is always when running with `-test.cpu=1,2,4`.

**Comment by ianlancetaylor** [comment]
The failure is always `TestStackWrapperStackPanic/sigpanic`.

**Comment by ianlancetaylor** [comment]
The test makes a call to `I.M(nil)` which is expected to call `nil` and therefore panic.  It looks like if a preemption signal occurs as we make the call that a call to `asyncPreempt` is inserted and that call immediately panics.  The stack trace is then not what we expect.  I'm not sure why.

This doesn't seem all that crucial, though it does mean that in some failure cases we will print the wrong stack trace.

CC @aclements @cherrymui

**Comment by cherrymui** [comment]
If we preempt the thread right at the point of the exception, we may inject a asyncPreempt call, and then the exception handler runs (before asyncPreempt runs), which injects a sigpanic call. Then we could see sigpanic right on top of asyncPreempt. In traceback, normally we would not elide wrappers if it is the immediate caller of sigpanic, but we will if the immediate caller is asyncPreempt. If this is the case, we could see the stack trace like that.

I'm not familiar about the ordering of Windows' SuspendThread/ResumeThread and exception handling, so not sure if this could actually happen.

**Comment by bcmills** [comment]
I've been seeing this pretty often in TryBot runs. (Not as frequent as the `race` deadlocks, but still frequent enough to be annoying.)

[2019-12-09T15:12:29-f6774bc/windows-amd64-2012](https://build.golang.org/log/0f5a0619de93aad928520d5431c10045f5f645f4)
[2019-12-06T19:49:21-b2a5893/windows-amd64-2008](https://build.golang.org/log/d2717855667db3c237ef95848348f9d674e2f515)
[2019-12-06T01:11:02-a037582/windows-amd64-longtest](https://build.golang.org/log/9d5971cb78a3bf05e8ed5d23e48a5759a75e7a74)
[2019-12-05T22:16:02-eeb319a/windows-amd64-2012](https://build.golang.org/log/665e6feb2258628973ae7539578b75aa6f1fe9f4)
[2019-12-05T17:23:50-50535e6/windows-amd64-2012](https://build.golang.org/log/a9b40df11e840ab3b09c5a2f64bc1ac005b9e623)

**Comment by ianlancetaylor** [comment]
This hasn't happened on the builders since 2019-12-09.  The findflakes program reports only a 0.14% chance that the failure is still happening.

That said I have no idea what would have changed to fix this.

**Comment by aclements** [comment]
I can easily reproduce this at current master (817afe83578d869b36e8697344bb2d557c86b264) and at f6774bc with the following patch and script:

```diff
--- a/src/runtime/proc.go
+++ b/src/runtime/proc.go
@@ -4469,6 +4469,7 @@ func sysmon() {
 		if delay > 10*1000 { // up to 10ms
 			delay = 10 * 1000
 		}
+		delay = 10
 		usleep(delay)
 		now := nanotime()
 		next := timeSleepUntil()
@@ -4563,7 +4564,8 @@ type sysmontick struct {
 
 // forcePreemptNS is the time slice given to a G before it is
 // preempted.
-const forcePreemptNS = 10 * 1000 * 1000 // 10ms
+//const forcePreemptNS = 10 * 1000 * 1000 // 10ms
+const forcePreemptNS = 10 * 1000 // 10us
 
 func retake(now int64) uint32 {
 	n := 0
```

```sh
cd $GOROOT/src/runtime
VM=$(gomote create windows-amd64-2016)
GOOS=windows go test -c && \
gomote put $VM runtime.test.exe && \
gomote run $VM ./runtime.test.exe -test.run TestStackWrapperStackPanic/sigpanic/CallersFrames -test.count 1000000
```

Running with `./runtime.test -test.run TestStackWrapperStackPanic/sigpanic/CallersFrames -test.v`, we can see the traceback when the test passes:

```
runtime.Callers
runtime_test.testStackWrapperPanic.func1.1
runtime.gopanic
runtime.panicmem
runtime.sigpanic
runtime_test.I.M
runtime_test.TestStackWrapperStackPanic.func1.1
runtime_test.testStackWrapperPanic.func1
testing.tRunner
runtime.goexit
```

(normally it stops when it reaches `runtime_test.I.M`, but I tweaked it.)

What I don't fully understand is how we go from `asyncPreempt` to `sigpanic` in the bad traces. This is a nil panic, so the exception is synchronous. We should be injecting the sigpanic call at the exact PC/SP where the exception happens, so I don't see how `asyncPreempt` slips in there.

**Comment by aclements** [comment]
If we tweak the test to print the PC in the stack trace, we see that the `runtime.asyncPreempt` frame is at the very first instruction of `asyncPreempt`. This suggests that we injected that call and then immediately injected the `sigpanic`. Maybe it's possible in Windows for SuspendThread to stop a thread between when it causes an exception and when the VEH runs? If that's the case, preemptM would see the thread at the faulting instruction, tweak the frame to inject the asyncPreempt call, then resume the thread, which would run the VEH and tweak the frame again to inject the sigpanic call.

**Comment by cherrymui** [comment]
> Maybe it's possible in Windows for SuspendThread to stop a thread between when it causes an exception and when the VEH runs?

This is also my previous guess. One possibility would be printing the wrapper function if the previous frame is asyncPreempt. This will make the wrapper included in the stack trace. But the stack trace will look like
```
sigpanic
asyncPreempt
wrapper
...
```
which looks like asyncPreempt itself panics. I think this can happen with nil pointer dereference panics in general.

Another possibility is that when injecting a sigpanic, if the PC is the entry PC of asyncPreempt, just overwrite the PC instead of pushing another frame. This will make the stack trace correct. Losing preemption is probably not a problem, as sigpanic enters the runtime, which will probably preempt it synchronously at some point.

**Comment by cherrymui** [comment]
I implemented both approaches. Using @aclements's repro, both fix this.

Personally, I prefer option 2.

**Comment by aclements** [comment]
Thanks!

I assume by option 2 you mean overwriting the asyncPreempt frame. I certainly like that option better, as it's much more localized to the cause of the issue. Changing the traceback logic, on the other hand, is several dominoes away from the actual cause.

**Comment by cherrymui** [comment]
Yes, by option 2 I meant overwriting the asyncPreempt frame. Thanks.
