### ISSUE TITLE
os/user: "GroupIds requires cgo" when building for linux/arm with tag osusergo

### ISSUE THREAD

**Issue by mullerch** [golang/go#35770]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.13.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
λ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\chris\AppData\Local\go-build
set GOENV=C:\Users\chris\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\chris\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\chris\AppData\Local\Temp\go-build206665018=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
Cross-compile a go application for linux/arm using windows/amd64 using -tags="osusergo"
Cross-compile a go application for linux/arm using linux/amd64 using -tags="osusergo"

### What did you expect to see?
The application builds fine and uses go implementation of os/user. 
os/user.GroupIds should work fine on an application not using CGO.

### What did you see instead?
The application builds fine **but** uses CGO implementation of os/user.
os/user.GroupIds call returns "user: GroupIds requires cgo"

The same application is correctly compiled/linked with go 1.12 on linux/amd64 for linux/arm.

**Comment by bcmills** [comment]
The error message `user: GroupIds requires cgo` implies that the build _is not_ using the `cgo` implementation. It comes from here:
https://github.com/golang/go/blob/a38a917aee626a9b9d5ce2b93964f586bf759ea0/src/os/user/lookup_stubs.go#L70

So the question is, why were you _not_ getting that error on 1.12?

(What are the exact commands that you ran, and the results using `go1.12.13` and `go1.13.4` binaries from `golang.org/dl`?)

**Comment by mullerch** [comment]
I am not able to reproduce the working example with go 1.12.
Sadly I did not kept the config nor the binaries.


Regarding the docs, shouldn't the build without CGO or with -tags="osusergo" be linked against: https://github.com/golang/go/blob/a38a917aee626a9b9d5ce2b93964f586bf759ea0/src/os/user/lookup_unix.go#L172

https://golang.org/pkg/os/user/

> For most Unix systems, this package has two internal implementations of resolving user and group ids to names. One is written in pure Go and parses /etc/passwd and /etc/group. The other is cgo-based and relies on the standard C library (libc) routines such as getpwuid_r and getgrnam_r.
When cgo is available, cgo-based (libc-backed) code is used by default. This can be overridden by using osusergo build tag, which enforces the pure Go implementation.

**Comment by bcmills** [comment]
`lookupGroupId` is the implementation for the `user.LookupGroupId` function, not the `(*user.User).GroupIds` method.

**Comment by mvdan** [comment]
Closing old issues that still have the WaitingForInfo label where enough details to investigate weren't provided. Feel free to leave a comment with more details and we can reopen.
