### ISSUE TITLE
cmd/link: load of "ld -r" host object fails in -newobj mode

### ISSUE THREAD

**Issue by thanm** [golang/go#35779]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +9c6f6409ad Wed Nov 20 15:16:17 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

### What did you do?

Build a small program that links in a *.syso object that contains multiple static symbols that have the same name and section.

This is a bit elaborate, but here is a repro recipe:
<pre>
$ cat /tmp/c1.c
static void blah() { }
int c1() { return 42; }
$ cat /tmp/c2.c
static void blah() { }
int c2() { return 42; }
$ gcc -c -o c1.o /tmp/c1.c
$ gcc -c -o c2.o /tmp/c2.c
$ ld -r -o ldr.syso c1.o c2.o 
$ objdump -t ldr.syso | fgrep blah
0000000000000000 l     F .text	0000000000000007 blah
0000000000000012 l     F .text	0000000000000007 blah
$ rm c1.o c2.o 
$ cat main.go
package main
func main() {
}
$ go build .
$ go build -asmflags=all=-newobj -gcflags=all=-newobj -ldflags=-newobj .
# ...
loadelf: $WORK/b001/_pkg_.a(ldr.syso): duplicate symbol reference: blah in both main(.text) and main(.text)
$
</pre>

### What did you expect to see?

Clean build with -newobj.

### What did you see instead?

loadelf error.

**Comment by thanm** [comment]
@cherrymui , @jeremyfaller just as FYI

**Comment by thanm** [comment]
The new testcase broke the MIPS builders -- reopening while I work on that.

**Comment by thanm** [comment]
Representative failures:

<pre>
https://build.golang.org/log/98d47379c6065fd00edcd68aa384451c5deae722
    elf_test.go:202: # elf_test
        loadelf: $WORK/b001/_pkg_.a(ldr.syso): malformed elf file: invalid elf symbol index
</pre>

<pre>
https://build.golang.org/log/ad7532a8bd9457571fe394269d7a017b82abe21e
    elf_test.go:202: # elf_test
        /tmp/gobuilder-mips64/tmp/go-build246906970/b001/_pkg_.a(ldr.syso): unknown relocation type 333831; compiled without -fpic?
</pre>

**Comment by ianlancetaylor** [comment]
@thanm Anything else to do here for 1.14?

**Comment by cherrymui** [comment]
No. I think we can close this. It was reopened because the test failed on MIPS. I think that is due to a different problem.

**Comment by thanm** [comment]
https://go-review.googlesource.com/c/go/+/209317 is causing some issues with the builders (missing import). I sent a fix.
