### ISSUE TITLE
x/build/cmd/coordinator: gomote create doesn't work with older gomote clients

### ISSUE THREAD

**Issue by andybons** [golang/go#35778]
```
$ gomote create darwin-amd64-10_10
Error running create: failed to create buildlet: buildlet: failed to create remote buildlet; unexpected missing name in response
$ gomote list
user-andybons-darwin-amd64-10_10-0	darwin-amd64-10_10	host-darwin-10_10	expires in 26m11.407191056s
```

@dmitshur @cagedmantis @bradfitz @toothrot

**Comment by bradfitz** [comment]
I made a recent gomote change (https://go-review.googlesource.com/c/build/+/207841) that changed the protocol a bit but it should've been backwards compatible with old clients. Maybe not?

Try updating your gomote if you didn't?

**Comment by andybons** [comment]
Ah that did it. Thanks, Brad!

**Comment by bradfitz** [comment]
I'll repurpose this bug to be about fixing the gomote server to work with older clients.

Or just removing the server compat code I added which apparently never worked.

**Comment by andybons** [comment]
Was there a regression test?

**Comment by bradfitz** [comment]
> Was there a test?

The gomote stuff isn't wonderfully tested. It's a huge Rube Goldberg machine with huge dependencies. I haven't broken it up to be testable yet. It's just never been a priority given the limited user base. Low SLO service. :)

**Comment by andybons** [comment]
While not to derail this specific issue, testing and documentation are becoming more of a priority now that there are three additional people focused primarily on this codebase and changing things is very scary at the moment. Even if it comes at the cost of lower velocity in other areas.
