### ISSUE TITLE
Go not running on i386 hardware without SSE

### ISSUE THREAD

**Issue by 40b0a3cd** [golang/go#35789]
Here's my original bug report for OpenBSD: [https://marc.info/?l=openbsd-ports&m=157376594916571&w=2](https://marc.info/?l=openbsd-ports&m=157376594916571&w=2)

In a later post, I was able to get more debugging info, which suggests that Go is refusing to run due to lack of an SSE(?) instruction on my processor: [https://marc.info/?l=openbsd-ports&m=157384045312953&w=2](https://marc.info/?l=openbsd-ports&m=157384045312953&w=2).

It looks like the devs set GO386=387 on the build machines, but I think this might only be to disable SSE2 (the new package is still failing to run on my hardware)? [https://marc.info/?l=openbsd-ports&m=157411444311030&w=2](https://marc.info/?l=openbsd-ports&m=157411444311030&w=2)

Does anyone have any insight into what I can do to debug further or assist?

**Comment by randall77** [comment]
GO386=387 is required to run on 386 machines without SSE. Otherwise, the compiler will use SSE instructions.

See https://github.com/golang/go/wiki/MinimumRequirements#386

**Comment by 40b0a3cd** [comment]
I'm still seeing the same behavior when GO386=387.

**Comment by 40b0a3cd** [comment]
This is what is happening (even when using GO386=387):

Dump of assembler code for function runtime.check:
   0x0807fbc0 <+0>:     mov    %gs:0xfffffffc,%ecx
   0x0807fbc7 <+7>:     cmp    0x8(%ecx),%esp
   0x0807fbca <+10>:    jbe    0x807ff3b <runtime.check+891>
   0x0807fbd0 <+16>:    sub    $0x2c,%esp
   0x0807fbd3 <+19>:    movl   $0x0,0x20(%esp)
=> 0x0807fbdb <+27>:    xorps  %xmm0,%xmm0

**Comment by randall77** [comment]
The error you're seeing is from the `go` binary. The distribution itself needs to be built with GO386=387. We don't provide such a distribution on our website.
Probably the easiest way to do get such a special distribution is to download the Go source distribution to a normal (SSE-capable, 32 or 64-bit) machine, then do
```
   cd go/src
   GOARCH=386 GO386=387 ./make.bash
```
Then copy the distribution directory to the SSE-crippled machine. Then build the binaries you want also with GOARCH=386 GO386=387.

Or you could just cross-compile every binary you want from a SSE-capable machine, using the standard distribution.

**Comment by 40b0a3cd** [comment]
We are currently building with GO386=387. From the documentation, it appears that this only disables SSE2, and not SSE instructions. The documentation is a little unclear, but would setting GO386=386 disable SSE? The processor is an AMD Geode LX, which is fairly recent in terms of the embedded world.

**Comment by randall77** [comment]
There is no GO386=386. 387 and sse2 are the only options.
The function `runtime.check` is generated by the compiler. The compiler should not use any sse instructions if GO386=387.

When I build with those flags, I get code that looks 387-correct.
```
$ GOARCH=386 GO386=387 go build hello.go
$ objdump -d hello | grep -A20 'runtime.check>:'
08082210 <runtime.check>:
 8082210:	65 8b 0d 00 00 00 00 	mov    %gs:0x0,%ecx
 8082217:	8b 89 fc ff ff ff    	mov    -0x4(%ecx),%ecx
 808221d:	3b 61 08             	cmp    0x8(%ecx),%esp
 8082220:	0f 86 84 03 00 00    	jbe    80825aa <runtime.check+0x39a>
 8082226:	83 ec 34             	sub    $0x34,%esp
 8082229:	c7 44 24 20 00 00 00 	movl   $0x0,0x20(%esp)
 8082230:	00 
 8082231:	d9 ee                	fldz   
 8082233:	d9 c0                	fld    %st(0)
 8082235:	d9 5c 24 1c          	fstps  0x1c(%esp)
 8082239:	d9 ee                	fldz   
 808223b:	dd d9                	fstp   %st(1)
 808223d:	d9 c0                	fld    %st(0)
 808223f:	dd 5c 24 24          	fstpl  0x24(%esp)
 8082243:	c7 44 24 18 00 00 00 	movl   $0x0,0x18(%esp)
 808224a:	00 
 808224b:	c7 04 24 31 ce 57 4b 	movl   $0x4b57ce31,(%esp)
 8082252:	c7 44 24 04 3a 0b 00 	movl   $0xb3a,0x4(%esp)
 8082259:	00 
 808225a:	c7 44 24 08 00 ca 9a 	movl   $0x3b9aca00,0x8(%esp)
```

**Comment by 40b0a3cd** [comment]
Thank you - I'll pass this along to the ports maintainers. They had informed me that the latest packages were built with GO386=387.

I appreciate your time looking at this for me!

**Comment by cellularmitosis** [comment]
Has there been any update on this?  I just downloaded go1.13.7.linux-386.tar.gz and hit an illegal instruction.  I'm also running an AMD Geode.

```
# cat /proc/cpuinfo 
processor	: 0
vendor_id	: Geode by NSC
cpu family	: 5
model		: 5
model name	: Geode(TM) Integrated Processor by National Semi
stepping	: 2
cpu MHz		: 365.230
cache size	: 32 KB
fdiv_bug	: no
f00f_bug	: no
coma_bug	: no
fpu		: yes
fpu_exception	: yes
cpuid level	: 1
wp		: yes
flags		: fpu de pse tsc msr cx8 pge cmov mmx mmxext 3dnowext 3dnow
bugs		:
bogomips	: 730.46
clflush size	: 32
cache_alignment	: 32
address sizes	: 32 bits physical, 32 bits virtual
power management:
```

**Comment by ianlancetaylor** [comment]
@cellularmitosis This issue is closed.  No update is expected.

Have you tried setting `GO386=386` as discussed above?  But for further discussion, please use a forum.  See https://golang.org/wiki/Questions.  Thanks.

**Comment by cellularmitosis** [comment]
@ianlancetaylor I'm not sure I understand -- the latest i386 release of golang still appears to require SSE instructions, so I don't understand how this issue is closed.

There seemed to be an indication that this was going to be fixed:

> Thank you - I'll pass this along to the ports maintainers. They had informed me that the latest packages were built with GO386=387.

I was asking for an update to see if that had been done.

Thanks!

**Comment by ianlancetaylor** [comment]
@cellularmitosis The "ports maintainers" from the comment above are the OpenBSD port maintainers.  I don't know what they have done.

The Go project does not provide any 386 binary releases.

**Comment by cellularmitosis** [comment]
@ianlancetaylor Thanks, sorry for my confusion.
