### ISSUE TITLE
cmd/go/internal/modfetch: version before would have negative patch number: found an example.

### ISSUE THREAD

**Issue by leafbebop** [golang/go#35787]
In go.mod in github.com/moby/buildkit, I found [this line](https://github.com/moby/buildkit/blob/7a601252feac1493e792d082efecb66fbed75b75/go.mod#L12):
> github.com/containerd/containerd v1.4.0-0.20191014053712-acdcf13d5eaf

This is an invalid psedo version: It is in the form of "vX.Y.(Z+1)-0.yyyymmddhhmmss-abcdefabcdef" but (Z+1)=0. It is rejected by go tools.

I came through a [comment](https://github.com/golang/go/blob/05511a5c0ae238325c10b0e4e44c3f66f928e4cf/src/cmd/go/internal/modfetch/pseudo.go#L190) in cmd/go/internal/modfetch/pseudo.go, saying interested in examples of invalid pseudo versions "vX.0.0-0". Though this is not exactly the case, I think it may still be of interests of determining futher development.

**Comment by bcmills** [comment]
Thanks for the report! I've inquired about the origin of this version string on the GitHub page for the commit that introduced it (https://github.com/moby/buildkit/commit/c6641fb6d0a3c18a3a05e3a8a4be7c74bad4d4b2).

I've seen other invalid versions within `docker` and `moby` projects originating from hand-edited `go.mod` files, so I suspect that the same happened here.
