### ISSUE TITLE
x/tools/gopls: VSCode user snippets not sorting properly

### ISSUE THREAD

**Issue by muirdm** [golang/go#35782]
Imported from https://github.com/microsoft/vscode/issues/84587

In https://go-review.googlesource.com/c/tools/+/202717 I added a workaround so our completion candidate order was maintained in VSCode. I made all gopls candidates appear to be "perfect" so VSCode had no additional sorting/filtering to do. This, however, made gopls candidates always match better than other VSCode completion items, such as user snippets.

**Comment by muirdm** [comment]
@tj The above change should resolve the issue. Are you able to test it out? Rough steps are:

1. Clone https://github.com/golang/tools
1. Grab https://go-review.googlesource.com/c/tools/+/208439/ ("Download patch" from upper right "..." menu)
1. `cd gopls; go install`
1. Confirm above built `gopls` binary is first in your PATH
1. `Developer: Reload Window` in VSCode

**Comment by tj** [comment]
Awesome! That fixed it, thanks a lot, I didn't realize the language server is in charge of so much, I'll keep that in mind next time.
