### ISSUE TITLE
goroutine/pointer issue

### ISSUE THREAD

**Issue by hellodword** [golang/go#35797]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Secret\AppData\Local\go-build
set GOENV=C:\Users\Secret\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\GOPATH
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\GO\go
set GOSUMDB=sum.golang.google.cn
set GOTMPDIR=
set GOTOOLDIR=D:\GO\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\wtf\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Secret\AppData\Local\Temp\go-build211112002=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I tried to run the code: 
```go
package main

import (
	"fmt"
	"net/http"
	"time"
	"unsafe"
)

const TEST_URL = "http://dl.google.com/favicon.ico"

type My struct {
	url string
}

func (m *My) Do(i int) {

	if m.url != TEST_URL {
		panic("url = " + m.url)
	}

	fmt.Println(i, "url = "+m.url)

	var err error

	client := http.Client{
		Timeout: 3 * time.Second,
	}

	res, err := client.Head(m.url)
	if err != nil {
		return
	}

	fmt.Println("\t", res.Status)

}

func MyNew() *My {
	return &My{
		url: TEST_URL,
	}
}

func MyDo(m *My) {
	go func() {
		var i int
		for {
			m.Do(i)
			i++
		}
	}()
}

func main() {

	m := MyNew()
	pm := uintptr(unsafe.Pointer(m))
	fmt.Println("pm =", pm)

	MyDo((*My)(unsafe.Pointer(pm)))
	select {}
}

```

I built it with `GOARCH=amd64` and `GOARCH=386` on `Windows 10 1903`, they will crash after a while:

```
927 url = http://dl.google.com/favicon.ico
         200 OK
928 url = http://dl.google.com/favicon.ico
         200 OK
929 url = http://dl.google.com/favicon.ico
         200 OK
panic: url =

goroutine 6 [running]:
main.(*My).Do(0xc00008bf20, 0x392)
        D:/wtf/main.go:19 +0x2c8
main.MyDo.func1(0xc00008bf20)
        D:/wtf/main.go:49 +0x3e
created by main.MyDo
        D:/wtf/main.go:46 +0x46
```

### What did you expect to see?

I want to know the reason, and get a solution.

### What did you see instead?

```
927 url = http://dl.google.com/favicon.ico
         200 OK
928 url = http://dl.google.com/favicon.ico
         200 OK
929 url = http://dl.google.com/favicon.ico
         200 OK
panic: url =

goroutine 6 [running]:
main.(*My).Do(0xc00008bf20, 0x392)
        D:/wtf/main.go:19 +0x2c8
main.MyDo.func1(0xc00008bf20)
        D:/wtf/main.go:49 +0x3e
created by main.MyDo
        D:/wtf/main.go:46 +0x46
```

**Comment by ALTree** [comment]
> `MyDo((*My)(unsafe.Pointer(pm)))`

This is not allowed. From https://golang.org/pkg/unsafe/, what is allowed:

> (2) Conversion of a Pointer to a uintptr (**but not back to Pointer**). 
>
> Converting a Pointer to a uintptr produces the memory address of the value pointed at, as an integer. The usual use for such a uintptr is to print it. 
> 
> Conversion of a uintptr back to Pointer is not valid in general. 

Running `go vet` on your code will alert you of this:

```
$ go vet test.go

# command-line-arguments
./test.go:61:13: possible misuse of unsafe.Pointer
```

Moreover, the checkptr harness on tip (will be in Go1.14)  will catch this and crash your program immediately:

```
$ gotip run -gcflags="-d=checkptr" test.go

pm = 824634015560
panic: runtime error: unsafe pointer arithmetic

goroutine 1 [running]:
main.main()
	/home/alberto/test.go:61 +0xf6
exit status 2
```

In general, there's no reason to use `unsafe` in a program like the one you posted, so I hope you are just experimenting with `unsafe` and pointers. If you are, please refer to https://golang.org/pkg/unsafe/ to understand what you're allowed to to (and what you're not).

Closing here, since this is not a Go bug.
