### ISSUE TITLE
go get: GOPROXY=direct go get: some.url/pkg/vX@vX.Y.Z: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v6

### ISSUE THREAD

**Issue by leafbebop** [golang/go#35795]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
GOPROXY=direct go get github.com/scholl/croc/v6@v6.0.0
GOPROXY=direct go get github.com/thatisuday/nummanip/v2/calc@v2.0.0

### What did you expect to see?
command success.

### What did you see instead?
`go get github.com/schollz/croc/v6@v6.0.0: github.com/schollz/croc@v6.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v6`

`go get github.com/thatisuday/nummanip/v2/calc@v2.0.0: github.com/thatisuday/nummanip@v2.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2`

After some digging and hacking, I suspect it is because `cmd/go/internal/modfetch.runQueries` runs candicate query in parellel and sees an error when trying to query `some.url/pkg` (without the /vX in path) - it should be v0 or v1, not vX (as the tool reports) - this is not an `os.NonExist` kind of error, so the tool thinks it is vital (and fatal). Even though the parellel query with `some.url/pkg/vX` success, it uses `cmd/go/internal/base.ExitIfErrors()` to exit.

**Comment by seankhliao** [comment]
can reproduce on go1.13.1, can't reproduce on 1.13.4

**Comment by leafbebop** [comment]
Oops, I used wrong go version. Yes, it is fixed in 1.13.4. Sorry for that.
