### ISSUE TITLE
gccgo: ar: bad option: -D

### ISSUE THREAD

**Issue by zerofuko** [golang/go#35815]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go.1.10 gccgo (GCC) 8.1.0 solaris/sparc64

</pre>

### Does this issue reproduce with the latest release?

I dont know in solaris sparc. But in windows or linux amd64 this issue does not produce.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="sparc64"
GOBIN=""
GOCACHE="/export/home/nco73/.cache/go-build"
GOEXE=""
GOHOSTARCH="sparc64"
GOHOSTOS="solaris"
GOOS="solaris"
GOPATH="/export/home/nco73/go/"
GORACE=""
GOROOT="/usr/gcc/8"
GOTMPDIR=""
GOTOOLDIR="/usr/gcc/8/lib/gcc/sparcv9-sun-solaris2.11/8.1.0"
GCCGO="/usr/gcc/8/bin/gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build710471633=/tmp/go-build -gno-record-gcc-switches -funwind-tables"

</pre></details>

### What did you do?

go run cmd/main.go -env=local

### What did you expect to see?

Only "Caller Main"

### What did you see instead?
<pre>
# qwerkey/pkg/lib/connection
ar: bad option: -D
usage: ar -d[-SvV] archive file ...
       ar -m[-abiSvV] [posname] archive file ...
       ar -p[-vV][-sS] archive [file ...]
       ar -q[-cuvSV] [-abi] [posname] [file ...]
       ar -r[-cuvSV] [-abi] [posname] [file ...]
       ar -t[-vV][-sS] archive [file ...]
       ar -x[-vV][-sSCT] archive [file ...]
# qwerkey/vendor/golang.org/x/crypto/blowfish
ar: bad option: -D
usage: ar -d[-SvV] archive file ...
       ar -m[-abiSvV] [posname] archive file ...
       ar -p[-vV][-sS] archive [file ...]
       ar -q[-cuvSV] [-abi] [posname] [file ...]
       ar -r[-cuvSV] [-abi] [posname] [file ...]
       ar -t[-vV][-sS] archive [file ...]
       ar -x[-vV][-sSCT] archive [file ...]
# qwerkey/vendor/github.com/go-sql-driver/mysql
ar: bad option: -D
usage: ar -d[-SvV] archive file ...
       ar -m[-abiSvV] [posname] archive file ...
       ar -p[-vV][-sS] archive [file ...]
       ar -q[-cuvSV] [-abi] [posname] [file ...]
       ar -r[-cuvSV] [-abi] [posname] [file ...]
       ar -t[-vV][-sS] archive [file ...]
       ar -x[-vV][-sSCT] archive [file ...]
Caller Main
</pre>

I don't know why gccgo using ar -D argument instead ar -d. Application still run perfectly but I dont know if this error gives performance impact or another things.

**Comment by ianlancetaylor** [comment]
You can ignore those error messages.  This is fixed on tip.  I don't mind if someone wants to backport the fix but I don't intend to do it myself.
