### ISSUE TITLE
How do I check for common socket error conditions?

### ISSUE THREAD

**Issue by kstenerud** [golang/go#35819]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Don't know. 1.13.4 compilation is broken:
```
$ go build
# reflect
/usr/local/go/src/reflect/value.go:1410:3: //go:nocheckptr is not allowed in the standard library
/usr/local/go/src/reflect/value.go:1922:3: //go:nocheckptr is not allowed in the standard library
```

### Issue

Running the following code:

```golang
package main

import (
	"fmt"
	"net"
	"time"
)

func main() {
	l, err := net.Listen("tcp", "localhost:3344")
	if err != nil {
		fmt.Println("Error listening: ", err.Error())
		return
	}
	defer l.Close()

	go func() {
		for {
			conn, err := l.Accept()
			if err != nil {
				fmt.Println("Error accepting: ", err.Error())
				return
			}
			fmt.Printf("Conn = %v\n", conn)
		}
	}()

	time.Sleep(time.Second)
}
```

... generates (correctly) the following error:

```
Error accepting:  accept tcp 127.0.0.1:3344: use of closed network connection
```

But as I understand it, there are supposed to be declared error values we can compare against rather than using brittle string comparisons that aren't even covered by the go contract. This is apparently a big enough problem that your own tests even include an explicit check to make sure that code depending on a string comparison for this one common case doesn't break: https://golang.org/src/net/error_test.go#L501

But when I look at the source, the error isn't even exported: https://golang.org/src/internal/poll/fd.go#L20, so how exactly are we supposed to check for expected network errors in go?

**Comment by ianlancetaylor** [comment]
I think this is a dup of #4373, which has a complicated discussion.  I'm going to close this as a dup, but please comment if you disagree.
