### ISSUE TITLE
x/tools/godoc/static, x/website/content/static: missing "or" function call in package.html template

### ISSUE THREAD

**Issue by smasher164** [golang/go#35812]
For instance, https://golang.org/pkg/crypto/ displays all of the package's subdirectories above the footer, like so
![image](https://user-images.githubusercontent.com/12636891/69498416-e447c680-0eb5-11ea-9c0f-cee573da5850.png)

However, https://tip.golang.org/pkg/crypto/ does not display the package's subdirectories and positions the "Name" and "Sypnosis" columns underneath the footer, like so
![image](https://user-images.githubusercontent.com/12636891/69498450-37217e00-0eb6-11ea-8544-ccdb38028cd2.png)

EDIT: /cc @andybons

**Comment by andybons** [comment]
@dmitshur

**Comment by dmitshur** [comment]
There was a problem in the package.html template that is starting to be caught in Go 1.14. Can be reproduced with `gotip run golang.org/x/website/cmd/golang` and visiting the page. Evaluating the package.html template produces an error:

```
2019/11/25 12:32:29 packageHTML.Execute: template: package.html:217:13: executing "package.html" at <(eq $.Dirname "/src/cmd") $.DirFlat>: can't give argument to non-function eq $.Dirname "/src/cmd"
```

The error is in the following line of package.html template:

```
{{if not ((eq $.Dirname "/src/cmd") $.DirFlat)}}
```

It should instead be:

```
{{if not (or (eq $.Dirname "/src/cmd") $.DirFlat)}}
```

This change happened in CL 101295, where the intention was to remove the `(eq $.Dirname "/src")` condition as far as I understand. /cc @agnivade
