### ISSUE TITLE
x/build/cmd/gitmirror: build repo is broken due to updateDashboard failing to postCommit on a commit with 2 parents

### ISSUE THREAD

**Issue by dmitshur** [golang/go#35828]
From https://farmer.golang.org/#health right now:

<img src="https://user-images.githubusercontent.com/1924134/69566401-ffcdd280-0f84-11ea-9510-589bb9a32649.png" width="362px">

This has happened a few times in the last few days. I've fixed previous instances by restarting gitmirror, but since it keeps recurring, this will need to be investigated and fixed more.

/cc @toothrot @cagedmantis

**Comment by bradfitz** [comment]
If it helps:

```
$ for IP in $(kubectl get pods  -l app=gitmirror -o=jsonpath={.items[*].status.podIP}); do curl http://$IP:8585/debug/goroutines; done
```

.. to look at the goroutine stacks of the active pods.

**Comment by bradfitz** [comment]
If it turns out this is hanging due to updating the dashboard, note that all the code's gone as of pending https://go-review.googlesource.com/c/build/+/208697

**Comment by dmitshur** [comment]
It is. It happened again, and here are the logs:

```
[...]
2019/11/25 22:18:37 build: sending commit to dashboard: 174fe5663144a72ea7dad1b480912906854505b6[master]("devapp/owners: add owners for mod repository")
2019/11/25 22:18:37 build: updateDashboard failed in repo loop: postCommit: error: parent commit not found
2019/11/25 22:18:49 build: sending commit to dashboard: 174fe5663144a72ea7dad1b480912906854505b6[master]("devapp/owners: add owners for mod repository")
2019/11/25 22:18:49 build: updateDashboard failed in repo loop: postCommit: error: parent commit not found
2019/11/25 22:19:01 build: sending commit to dashboard: 174fe5663144a72ea7dad1b480912906854505b6[master]("devapp/owners: add owners for mod repository")
2019/11/25 22:19:01 build: updateDashboard failed in repo loop: postCommit: error: parent commit not found
[...]
```

It sounds like we can let this wait for [CL 208697](https://golang.org/cl/208697) before trying to make progress here, does that sound good to you @bradfitz?

**Comment by bradfitz** [comment]
Yup. Let's wait.

That code is all scary and it's not worth debugging. Easier to delete it all.
