### ISSUE TITLE
x/tools/gopls: a way to control staticcheck options

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#35826]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 linux/amd64
$ gopls version
golang.org/x/tools/gopls 0.2.0
    golang.org/x/tools/gopls@v0.2.1 h1:qXHEqJw4CqROYvoDXinY1ZOkyAFS+jcPOvLRK76dvwY=
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN="/home/oneofone/code/go/bin"
GOCACHE="/tmp/.gocache"
GOENV="/home/oneofone/.config/go/env"
GOEXE=""
GOFLAGS="-gcflags=-c=16"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/oneofone/code/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/src/go1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/src/go1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build965012732=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.13.4 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.13.4
uname -sr: Linux 5.3.12-arch1-1
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.30.
lldb --version: lldb version 9.0.0
gdb --version: GNU gdb (GDB) 8.3.1
</pre></details>

### What did you do?

Working on a huge codebase that doesn't pass some of the linting options in vscode.

### What did you expect to see?

A way to turn off some of the lint options in staticcheck

### What did you see instead?

1000s of lint errors, had to turn of staticcheck all together.

```
	"gopls": {
		"usePlaceholders": true,
		"completeUnimported": true,
		"staticcheck": false,
		"watchChangedFiles": true,
		"deepComplete": true
	},
```

**Comment by OneOfOne** [comment]
cc @stamblerre @ianthehat

**Comment by stamblerre** [comment]
Thanks for the report! This will be fixed in [CL 208098](https://go-review.googlesource.com/c/tools/+/208098).

**Comment by OneOfOne** [comment]
Actually, I just dug through the source trying to implement it and and found `experimentalDisabledAnalyses` which does exactly what I need.

Sorry for the noise.
