### ISSUE TITLE
Implement Getpriority and Setpriority for Windows

### ISSUE THREAD

**Issue by ItsMattL** [golang/go#35830]
### What version of Go are you using (`go version`)?

1.13

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

set GOHOSTARCH=amd64
set GOHOSTOS=windows

### Detail

The Getpriority and Setpriority methods in the syscall package lack parity between Linux and Windows.

See GetPriorityClass and SetPriorityClass for a possible comparable API on Windows.

https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getpriorityclass
https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setpriorityclass

**Comment by ianlancetaylor** [comment]
The syscall package is more or less frozen.  `GetPriorityClass` and `SetPriorityClass` are available in the golang.org/x/sys/windows package.  Use that one.
