### ISSUE TITLE
cmd/vet: -<analyzer> flags don't work when outside of GOROOT

### ISSUE THREAD

**Issue by shawn-xdji** [golang/go#35837]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +95be9b7559 Fri Nov 22 04:26:34 2019 +0000 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xiaji01/.cache/go-build"
GOENV="/home/xiaji01/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xiaji01/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/xiaji01/util/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/xiaji01/util/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build905003963=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
~/util/go$ go vet runtime/testdata/testprog
# runtime/testdata/testprog
src/runtime/testdata/testprog/deadlock.go:45:2: unreachable code
src/runtime/testdata/testprog/deadlock.go:50:2: unreachable code

~/util/go$ go vet -unreachable=false runtime/testdata/testprog
# runtime/testdata/testprog
src/runtime/testdata/testprog/deadlock.go:45:2: unreachable code
src/runtime/testdata/testprog/deadlock.go:50:2: unreachable code
```

### What did you expect to see?
-unreachable=false works even running 'go vet' outside \<go root\>/src

### What did you see instead?
the unreachable warning is not suppressed.

**Comment by shawn-xdji** [comment]
I have a local fix, would like to send it for reviewing if this is a bug.

**Comment by alandonovan** [comment]
Thanks, this does indeed look like a bug. Please do share your fix.

```
$ go version
go version devel +4a378d712d Tue Nov 26 20:21:04 2019 +0000 linux/amd64
$ cd $HOME
$ go vet -unreachable=true runtime/testdata/testprog
# runtime/testdata/testprog
go-again/src/runtime/testdata/testprog/deadlock.go:45:2: unreachable code
go-again/src/runtime/testdata/testprog/deadlock.go:50:2: unreachable code
$ go vet -unreachable=false runtime/testdata/testprog
# runtime/testdata/testprog
go-again/src/runtime/testdata/testprog/deadlock.go:45:2: unreachable code
go-again/src/runtime/testdata/testprog/deadlock.go:50:2: unreachable code
```

**Comment by shawn-xdji** [comment]
Thanks for confirming.
The flags specified on 'go vet' command line will be overwritten if:
    1. the package under vetting is resolved by searching under $GOROOT/src (after the local import fails to find a matched one), and
    2. no options for 'go tool vet' are specified
    3. no vettool is specified
There might be various fixes, I chose to replace the overwriting with appending, thought it would minimize the impact, make sense?
