### ISSUE TITLE
x/tools/cmd/guru: 'definition' cannot show declaration of a local object from a different go file

### ISSUE THREAD

**Issue by zhouhua015** [golang/go#35842]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="~/.cache/go-build"
GOENV="~/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="~/Golang"
GOPRIVATE=""
GOROOT="/snap/go/4762"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/4762/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="~/Sources/guru-test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build198801993=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

The following is my testing package

#### files:
```
- a.go
- bar.go
- foo
  - b.go
- go.mod
```
#### go.mod
```
module example.com/guru/test

go 1.13

```
#### a.go
``` golang
package guru_test

type FooA struct {
}
```

#### bar.go
``` golang
package guru_test

import "example.com/guru/test/foo"

type FooC struct {
}

func bar() {
        var x FooA
        var y foo.FooB
        var z FooC
}
```
#### foo/b.go 
``` golang
package foo

type FooB struct {
}
```

Try to show declaration of selected identifier for `FooA`:
```bash
~/Sources/guru-test$ guru definition bar.go:#99               
guru: no object for identifier
```
Try to show declaration of selected identifier for `FooB`:
```bash
~/Sources/guru-test$ guru definition bar.go:#115
~/Sources/guru-test/foo/b.go:3:6: defined here as type example.com/guru/test/foo.FooB
```
Try to show declaration of selected identifier for `FooC`:
```bash
~/Sources/guru-test$ guru definition bar.go:#127
~/Sources/guru-test/bar.go:5:6: defined here as type FooC
```

### What did you expect to see?

Show declaration `FooA` should give:
```bash
~/Sources/guru-test$ guru definition bar.go:#99    
~/Sources/guru-test/a.go:3:6: defined here as type FooA
```

### What did you see instead?

```bash
~/Sources/guru-test$ guru definition bar.go:#99               
guru: no object for identifier
```

**Comment by adonovan** [comment]
guru was deleted in https://github.com/golang/go/issues/65880; closing as obsolete.
