### ISSUE TITLE
sum.golang.org: go get golint ends with 410 Gone

### ISSUE THREAD

**Issue by Aazhar** [golang/go#35850]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/build/.cache/go-build"
GOENV="/build/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/build"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build100314052=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
<pre>
go get -u  golang.org/x/lint/golint
</pre>

### What did you expect to see?

Install golint and be able to use it 

### What did you see instead?

go: finding golang.org/x/lint latest
go: downloading golang.org/x/lint v0.0.0-20191125180803-fdd1cda4f05f
verifying golang.org/x/lint@v0.0.0-20191125180803-fdd1cda4f05f: golang.org/x/lint@v0.0.0-20191125180803-fdd1cda4f05f: reading **https://goproxy.io/sumdb/sum.golang.org/lookup/golang.org/x/lint@v0.0.0-20191125180803-fdd1cda4f05f: 410 Gone**

**Comment by katiehockman** [comment]
We'll look into this. Thanks for filing an issue. It looks like it has been resolved now (the repo link resolves now) but we'd like to figure out the underlying issue.

Also worth noting that this is coming through goproxy.io which seems to be proxying the sumdb, but still suspect this is coming from sum.golang.org.

**Comment by heschik** [comment]
We were unable to find any evidence of this problem in our logs. `v0.0.0-20191125180803-fdd1cda4f05f` was added to `sum.golang.org` at around 2019-11-254 18:12:00 UTC, shortly after its publication. After that, the sumdb record is immutable; there's no reason we would ever serve a 410.

I'd suggest following up with goproxy.io. If you find anything out, please let us know.

**Comment by godcong** [comment]
i try to get my project from `github` used `goproxy.io` with the same error...

**Comment by heschik** [comment]
If you're having a problem with `proxy.golang.org`, please file a new bug with full detail. If you're having a problem with `goproxy.io`, we can't help you with that.
