### ISSUE TITLE
mobile sdk

### ISSUE THREAD

**Issue by myroid** [golang/go#35864]
I hope that in future developments, Go on mobile will focus on building SDKs for android / iOS applications.

**Comment by smasher164** [comment]
Does https://godoc.org/golang.org/x/mobile/cmd/gomobile not satisfy your use case? Additionally, your suggestion is a proposal, it needs to be more specific on what you are looking for.

**Comment by mvdan** [comment]
What @smasher164 said. Also, this issue tracker is only for bugs and specific proposals. If you merely want to discuss the future of Go on mobile devices, use golang-nuts or one of the forums.
