### ISSUE TITLE
Buggy If Conditional Behavior?

### ISSUE THREAD

**Issue by chunter0** [golang/go#35863]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
  macOS 
    GOARCH="amd64"
    GOHOSTARCH="amd64"
    GOHOSTOS="darwin"
</pre></details>

### What did you do?

shift elements of an array inside of a for loop, when I try to shift elements it causes the function to run 4 times instead of the normal two based off input. You can see this if you run the code in the Golang playground link and then run again with line 19 uncommented.

https://play.golang.org/p/DkaqFm8VLzy

### What did you expect to see?
Elements in the array swapped based off the indexes used in the scope of if conditional.

### What did you see instead?
Elements shifted to the wrong spots because the function ran more than it should when I added that section of code in the scope.

**Comment by erifan** [comment]
I didn't see anything wrong. You have swap the elements of the array, so the "if" path run 4 times.

**Comment by chunter0** [comment]
If you comment out the swap statement then you see amt variable is only incremented twice. I’m wanting to only make a swap for each time amt is incremented so I’m not sure why when I add the swap statement to the same block it runs 4 times instead of 2


Cameron Hunter

**Comment by erifan** [comment]
https://play.golang.org/p/_zm8i7MS14A please check why it runs 4 times instead of 2, this is not a Go issue, I'll close it.
