### ISSUE TITLE
x/tools/gopls: lots of "work queue is full" messages on gopls stderr

### ISSUE THREAD

**Issue by myitcv** [golang/go#35870]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +27e50a1a25 Tue Nov 26 19:05:22 2019 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20191113223546-95cb2a1a7eae => github.com/myitcvforks/tools v0.0.0-20191119111301-0222b4b716c6
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.1.8-0.20191115202509-3a792d9c32b2 => github.com/myitcvforks/tools/gopls v0.0.0-20191119111301-0222b4b716c6
</pre>

_Note that `github.com/myitcvforks/tools v0.0.0-20191119111301-0222b4b716c6` and `github.com/myitcvforks/tools/gopls v0.0.0-20191119111301-0222b4b716c6` correspond to the `x/tools` 95cb2a1a7eae2d74d8211d4930f76e8ccd5e124f with 80313e1ba7181ff88576941b25b4beb004e348db cherry picked on top. Reason being, we can't move beyond 95cb2a1a7eae2d74d8211d4930f76e8ccd5e124f because otherwise we start tripping over the mistmatched versions problem described in https://github.com/golang/go/issues/35114_

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build598708738=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Tried to open a standard library file in Vim using `govim` (against commit 22688f740dbbae281c1de09c2b4fe6520337a124 to be precise):

```
$ pwd
/home/myitcv/dev/go/src
$ vi go/format/format.go
```

### What did you expect to see?

Normal `govim`, `gopls` and Vim startup.

### What did you see instead?

Lots of messages on `gopls` stderr:

```
work queue is full
```

Note that these messages are not logged to the `gopls` log file; it's only that we capture stderr in `govim` that we see them.

Also potentially of note:

* There are 587 calls to `go/packages.Load` that are logged from `gopls -> govim`
* There are 394 instances of the `work queue is full` message logged to `gopls` stderr

Separately, do we need all of these log messages to be sent to the client?

`govim` log: [govim.log](https://github.com/golang/go/files/3896736/govim.log)

`gopls` log: [gopls.log](https://github.com/golang/go/files/3896737/gopls.log)

---

cc @stamblerre @matloob

**Comment by ianthehat** [comment]
That was already fixed (that message no longer even exists, the queue is gone), it was a transition thing as I change the telemetry system to be more efficient.
https://go-review.googlesource.com/c/tools/+/208664

**Comment by myitcv** [comment]
Thanks - we currently can't move beyond 95cb2a1a7eae2d74d8211d4930f76e8ccd5e124f because otherwise we start tripping over the mistmatched versions problem described in #35114
