### ISSUE TITLE
x/tools/gopls: add extra testdata in gopls module

### ISSUE THREAD

**Issue by stamblerre** [golang/go#35880]
[CL 209220](https://go-review.googlesource.com/c/tools/+/209220) doesn't work because the diff algorithm in `golang.org/x/tools/internal/lsp` doesn't support sub-line diffs. We should probably have a way to add extra testdata in the `golang.org/x/tools/gopls` so that we can add extra tests that only work inside of that module.

/cc @ianthehat @heschik

**Comment by findleyr** [comment]
This is obsolete as all the code is now in the gopls module.
