### ISSUE TITLE
Why there is no floating-point CPU instruction in assembly？

### ISSUE THREAD

**Issue by elvin-du** [golang/go#35889]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.13.4 darwin/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)

2.3 GHz dual core Intel Core i5

GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/elvin/mygo/bin"
GOCACHE="/Users/elvin/Library/Caches/go-build"
GOENV="/Users/elvin/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/elvin/mygo"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Users/elvin/tools/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/elvin/tools/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/03/dxkgyg7n6r5dl2w0zmcr7rbh0000gn/T/go-build496722777=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you see instead?

Environmental Science:
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
2.3 GHz dual core Intel Core i5
Golang version:
go version go1.13.4 darwin/amd64
Golang Code:
```
Package main
Import (
"Math"
)
Func main () {
A: = 3.3
B: = 4.4
C: = a+b
print(math.Pow(a,b))
Print (c)
}
```
Compile with the following command:

```
 go build -gcflags "-N -l" main.go
```

View the assembly code with the following command:
```
 go tool objdump -S main
```

Why can't I find an instruction that starts with F? That is, floating-point instructions cannot be found?

**Comment by mpx** [comment]
Go is using more performant SSE2 instructions and registers (ADDSD / XMMn) instead of x87 (FADD and STn).

**Comment by mpx** [comment]
Please ask general Go questions like this on [golang-nuts](https://groups.google.com/forum/#!forum/golang-nuts), or another forum in future.

Github issues are intended for reporting bugs and/or feature requests.
