### ISSUE TITLE
compress/flate return ErrUnexpectedEOF even when the decompression finished successfully

### ISSUE THREAD

**Issue by madLifeZPC** [golang/go#35898]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPROXY="direct"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/52/bd76hd590sz1fsl094m08hf0m9dmwt/T/go-build177584568=/tmp/go-build -gno-record-gcc-switches -fno-common"
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Using `compress/inflate` to do data compression and decompression, the reader of inflate.go returns `ErrUnexpectedEOF` even when the data is decompressed **successfully**, check the example below.
```
package main

import (
	"fmt"
	"compress/flate"
	"bytes"
	"io/ioutil"
)

func main() {
	var b bytes.Buffer
	zw, _ := flate.NewWriter(&b, flate.BestSpeed)
	zw.Write([]byte("hello"))
	zw.Flush()
	compressed := b.Bytes()
	fmt.Println(compressed)
	
	r := flate.NewReader(bytes.NewReader(compressed))
	rawData, err := ioutil.ReadAll(r)
	fmt.Println(err) // -> unexpected EOF
	fmt.Println(string(rawData)) // -> "hello"
	
}
```

### What did you expect to see?
The error should be `nil` when decompression succeed, because we always check the error first.

### What did you see instead?
error is `ErrUnexpectedEOF`.

**Comment by opennota** [comment]
You forgot to Close the writer: https://play.golang.org/p/Chet8ii7MyO

**Comment by madLifeZPC** [comment]
Looks so, thanks!
