### ISSUE TITLE
Go windows 32 bits programs false positive? detection as Heur.AdvML.B

### ISSUE THREAD

**Issue by tsupplis** [golang/go#35897]
Cross compiling a simple hello program from macosx or linux for windows 32 results in Symantec SEP 14.2 for Mac detecting a Heur.AdvML.B.

### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.13.4 linux/amd64

$ go version
go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xxx/Library/Caches/go-build"
GOENV="/Users/xxx/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY="github.com/xxx/*"
GONOSUMDB="github.com/xxx/*"
GOOS="darwin"
GOPATH="/Users/xxx/.local.darwin/go"
GOPRIVATE="github.com/xxx/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hw/j2dd7hq141v3c2zzc6tjdq340000gn/T/go-build332660041=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

$ cat hello.go
package main
import "log"
func main() {
  log.Println("Hello, World!")
}

$ GOARCH=386 GOOS=windows go build -o hello_386.exe
---> Virus Detected in hello_386.exe

The following alternatives are not causing detection:
$ GOARCH=386 GOOS=windows go build -ldflags="-s -w" -o hello_386.exe
$ GOARCH=amd64 GOOS=windows go build -ldflags="-s -w" -o hello_amd64.exe 
$ GOARCH=amd64 GOOS=windows go build  -o hello_amd64.exe 

Previous version testing:
- go version go1.12.12 darwin/amd64 not detected
- go version go.1.13.1 Darwin/amd64 detected
- go version go1.13 darwin/amd64 detected

Finally, I reported this to Symantec as a potential false positive. Waiting for assessment.

**Comment by agnivade** [comment]
Hi @tsupplis, yes this is a common occurrence. Please see https://golang.org/doc/faq#virus. I will go ahead and close this since there is nothing to be done from our side. It is great that you have reported this to Symantec.
