### ISSUE TITLE
x/website: suggestion to define or explain what CL is in contribute.html

### ISSUE THREAD

**Issue by jfussion** [golang/go#35891]
We've replaced CL with `change` in https://go-review.googlesource.com/c/go/+/36564/ to _not_ confuse people what it means but CL is everywhere and I don't see any definition of that.

We may want to define or explain what CL is in contribute.html since we use it to refer to a PR or a change (at least that's how I understand it base on the CL linked above).

**Comment by seankhliao** [comment]
I believe the first instance of CL now has the full name: "Gopherbot will create a corresponding Gerrit change list (a "CL")"
