### ISSUE TITLE
Reslicing many slices hangs at memmove_amd64.s:418

### ISSUE THREAD

**Issue by vedranvuk** [golang/go#35901]
### What version of Go are you using (`go version`)?
<pre>
go1.13.4 linux/amd64
go1.13.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vedran/.cache/go-build"
GOENV="/home/vedran/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/vedran/Go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build348995939=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Ran the following program:
https://play.golang.org/p/a4LXg1a5mtC

### What did you expect to see?
Not sure exactly what's happening here. Maybe I'm missing something way to obvious but..

The program will hang in Recycle() and Remove() at the very last line where I re-slice b.cells. As you can see, I tried various approaches.

If I set loops in main to up to 10k it finishes ok. If I bump up loops to 100k or 1M+ the program hangs. Thought at first it's a map concurrent access issue first so tried using mutexes, sync map, etc. Didn't help.

Happens on my Archlinux, tried it on a Windows machine, both up to date. 
Go Playground returns "Program exited: process took too long."

### What did you see instead?
Program hangs with high loop number (100k+).
When ran in a debugger and pausing it drops me at memmove_amd64.s [418]

**Comment by seankhliao** [comment]
If you add progress indicators you will see that your program does progress, it's just that moving ~80MB of memory on each iteration takes time, especially since it probably doesn't fit in cache

**Comment by vedranvuk** [comment]
You are right. This code is obviously from a benchmark. So if I put a log line in a loop it slows a benchmark run enough that bench doesn't request as many loops as it would otherwise, where time to complete is suddenly magintudes higher, most likely cause of hitting some memory barrier when everything slows down to a halt. I missed that.

Sucks to hit a runtime limit, unintentionally.

My mistake, closing.
