### ISSUE TITLE
Inconsistent type of FileInfo.Size() and count of File.read()

### ISSUE THREAD

**Issue by admacro** [golang/go#35903]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Possible?

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/james/Library/Caches/go-build"
GOENV="/Users/james/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/james/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sp/n3hrxcgd3wgb8zb_3mt1w9kr0000gn/T/go-build078956692=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Sorry, I'm just curious. I just started learning Go. Anyone who can spare a 32bit os, please find out.
See code example here https://play.golang.org/p/nU0n4sRi2td.

### What did you expect to see?
The type for reporting file size should be consistent for `n` in [func (f *File) Read(b []byte) (n int, err error)](https://golang.google.cn/pkg/os/#File.Read) and  [FileInfo.Size() int64](https://golang.google.cn/pkg/os/#FileInfo).

### What did you see instead?
Possible int overflow on 32bit system.

**Comment by go101** [comment]
The `os.File.Read` method might need to be called many times to read all the content of a file. It returns the number of read bytes for each call, not essentially the file size.

**Comment by admacro** [comment]
OK, I think I get it. They are for different purposes. Count could even be int8. 

If I understood correctly, in the code example, `os.File.Read` will return only math.MaxInt32 bytes as count is int. In other words, math.MaxInt32 is the maximum number of bytes you can get for a `os.File.Read` call.
