### ISSUE TITLE
x/tools/gopls: unimported imports don't work with empty selector

### ISSUE THREAD

**Issue by muirdm** [golang/go#35915]
In code like:

```go
package main
func main() {
  context.
}
```

I expected to get candidates from "context" but I get nothing.

/cc @heschik

**Comment by heschik** [comment]
Looks like more your bag, it's failing during parsing and never running any completion code at all, I think?

`emptysel.go:5:1: expected selector or type assertion, found '}' (and 2 more errors)`

**Comment by stamblerre** [comment]
I don't think so, because we ignore errors in parsing as long as we get an AST back. I think regular completions work fine in this case.

**Comment by muirdm** [comment]
Completion in general works in this case since you get a parser error, but you also get a best effort *ast.File. The root of the issue seemed to be in `imports.ApplyFixes()`. It does not handle files with syntax errors since it needs to format the entire file. I wasn't sure if the right approach was to trim to just the imports before calling imports.ApplyFixes, or some change under imports/.

**Comment by heschik** [comment]
You're both right, of course. CL mailed.

**Comment by heschik** [comment]
I'm noticing what seems to be the same problem if the empty selector is right before a keyword on the next line.

`expected selector or type assertion, found 'if' (and 13 more errors)`

**Comment by muirdm** [comment]
Do you have a repro? It seems to work normally for me with a keyword on the next line.

**Comment by heschik** [comment]
Yeah. Using gopls built at 7a2a8a, inserting `base64.` at line 207 or on a new line after 211 of format.go causes a parse error. https://golang.org/cl/c/210200/1 fixes the bug because it usually doesn't need to parse the whole file anymore, so maybe it doesn't matter so much.

**Comment by heschik** [comment]
I think the basic gist of this is that I'm not using `cache.parseGo`, so I'm not getting AST fixups. Maybe I should be?

**Comment by stamblerre** [comment]
I don't think any of the AST fixups touch the import spec, but maybe it's worth trying this out?

**Comment by heschik** [comment]
At the time I had the problem, I was always parsing the whole file. Now I only need to do that when there's no imports yet, but I imagine the problem would still happen.

**Comment by muirdm** [comment]
I think this is resolved now. Please re-open if you disagree.
