### ISSUE TITLE
engine_android.c:425:99: error: invalid storage class specifier in function declarator

### ISSUE THREAD

**Issue by myroid** [golang/go#35913]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13.4
</pre>

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/dafan/soft/go/bin"
GOCACHE="/Users/dafan/Library/Caches/go-build"
GOENV="/Users/dafan/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=" -mod="
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/dafan/soft/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/Cellar/go/1.13.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/dafan/soft/go/src/netease.com/pe/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x4/kz8_1b4x605_47d_5sm71p4r0000gn/T/go-build649493129=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
go bind -target=android/arm

### What did you see instead?
```
……
TERM='dumb' /Users/dafan/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang -I /var/folders/x4/kz8_1b4x605_47d_5sm71p4r0000gn/T/gomobile-work-813675867/src/gobind -fPIC -marm -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -D__GOBIND_ANDROID__ -Werror -o ./_x004.o -c seq.cgo2.c
TERM='dumb' /Users/dafan/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang -I /var/folders/x4/kz8_1b4x605_47d_5sm71p4r0000gn/T/gomobile-work-813675867/src/gobind -fPIC -marm -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -D__GOBIND_ANDROID__ -Werror -o ./_x005.o -c seq_android.cgo2.c
cd /var/folders/x4/kz8_1b4x605_47d_5sm71p4r0000gn/T/gomobile-work-813675867/src/gobind
TERM='dumb' /Users/dafan/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang -I . -fPIC -marm -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I $WORK/b001/ -g -O2 -D__GOBIND_ANDROID__ -Werror -o $WORK/b001/_x006.o -c engine_android.c
# gobind
engine_android.c:425:99: error: invalid storage class specifier in function declarator
engine_android.c:425:103: error: parameter name omitted
engine_android.c:427:21: error: expected expression
rm -r -f "$WORK"
gomobile: /usr/local/Cellar/go/1.13.4/libexec/bin/go build -v -x -ldflags -w -s -buildmode=c-shared -o=/var/folders/x4/kz8_1b4x605_47d_5sm71p4r0000gn/T/gomobile-work-813675867/android/src/main/jniLibs/armeabi-v7a/libgojni.so gobind failed: exit status 2

```

**Comment by myroid** [comment]
I found the wrong reason：
```
func UpdateTeamAuth(tid string, auto int, listener IRequestListener) {
	updateTeam(tid, 3932176, strconv.Itoa(auto), listener)
}
```
and
```
func UpdateTeamAuth(tid string, auth int, listener IRequestListener) {
	updateTeam(tid, 3932176, strconv.Itoa(auth), listener)
}
```
It's the difference between `auto` and `auth`.
Auto, compile error
Auth, the compilation is successful
Amazing. Why?

**Comment by myroid** [comment]
I found the wrong reason：
I get a compile error when my argument name is `auto`
Amazing. Why?

**Comment by ianlancetaylor** [comment]
Because `auto` is a keyword in C.
