### ISSUE TITLE
x/tools/gopls: errors on builtins

### ISSUE THREAD

**Issue by inliquid** [golang/go#35910]
1. VS Code
2. gopls@master

`gopls` returns a bunch of errors when viewing `builtin.go`:
![изображение](https://user-images.githubusercontent.com/6797881/69898440-b9082000-136a-11ea-9f2c-39a27a21af00.png)

**Comment by stamblerre** [comment]
Hm, I'm not able to reproduce this. Can you please share the output of `gopls -rpc.trace -v check /path/to/go/src/builtin/builtin.go`? I would expect it to time out waiting for results after 30 seconds, actually, but the logs will be helpful.
