### ISSUE TITLE
crypto/tls: missing alert values

### ISSUE THREAD

**Issue by aviddiviner** [golang/go#35911]
In [RFC 6066](https://tools.ietf.org/html/rfc6066#section-9) there are 4 new error alerts that are defined, which are missing from crypto/tls [alert.go](https://golang.org/src/crypto/tls/alert.go).

There are:
```
certificate unobtainable (111)
unrecognized name (112)
bad certificate status response (113)
bad certificate hash value (114)
```

They should be added as constants in crypto/tls.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/me/Library/Caches/go-build"
GOENV="/Users/me/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/me/dev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```go
package main

import (
	"crypto/tls"
	"fmt"
	"net"
)

func main() {
	host := "showtimego.com"
	addr := net.JoinHostPort(host, "443")

	dialer := &net.Dialer{}
	config := &tls.Config{ServerName: host}

	conn, _ := dialer.Dial("tcp", addr)
	defer conn.Close()
	client := tls.Client(conn, config)
	defer client.Close()

	err := client.Handshake()
	fmt.Println(err) // remote error: tls: alert(112)
}
```

### What did you expect to see?

`remote error: tls: unrecognized name`

### What did you see instead?

`remote error: tls: alert(112)`

**Comment by tmthrgd** [comment]
unrecognized_name was added to tip for #18377. The others have not been, but I think that may have been intentional.

**Comment by FiloSottile** [comment]
Yeah, even if we don't send them (because we send all the wrong alerts all the time), we should be able to print their description when we get them.

The full IANA registry is here: https://www.iana.org/assignments/tls-parameters/tls-parameters.xml#tls-parameters-6
