### ISSUE TITLE
x/tools/gopls: CLI command not found: gopls

### ISSUE THREAD

**Issue by qhenkart** [golang/go#35924]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/qhenkart/Library/Caches/go-build"
GOENV="/Users/qhenkart/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/qhenkart/workspace/launchpad/glidr-dev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1v/97x4f9mj4rj9g0q79xsfl_6h0000gn/T/go-build991066472=/tmp/go-build -gno-record-gcc-switches -fno-common"
</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
installed gopls using GO111MODULE=on go get golang.org/x/tools/gopls@latest

when that didn't work, I switched my GO111MODULE mode and tried installing the other way

### What did you expect to see?

The ability to use gopls in the command line

### What did you see instead?

`command not found: gopls` .  

if I go to my GOPATH/bin I can run gopls there. Seeing the version  `version master, built in $GOPATH mode` . 

also not working in any editor

**Comment by stamblerre** [comment]
Is your `GOPATH` on your `PATH`? From your description, it sounds like it's not.

**Comment by qhenkart** [comment]
Thank you, I recently migrated my profile from bash to zsh due to an osX update and my variables were out of order. I was defining my PATH before my GOPATH definition. Silly mistake. Thanks for pointing me to it
