### ISSUE TITLE
x/tools/gopls: cannot set falsey options for gopls in emacs configuration

### ISSUE THREAD

**Issue by nevetS** [golang/go#35927]
### What version of Go are you using (`go version`)?
go version go1.13.3 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/steve/.cache/go-build"
GOENV="/home/steve/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/steve/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build937410234=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I'm using golang with emacs, per the instructions here: https://github.com/golang/tools/blob/master/gopls/doc/emacs.md

The instructions spell out:

Experimental settings can be configured via lsp-register-custom-settings:

    (lsp-register-custom-settings
     '(("gopls.completeUnimported" t t)
      ("gopls.staticcheck" t t)))

emacs-lisp does not provide a "false" for boolean.  It is typically represented as nil.

With the following in my config, I receive a warning:

    ("gopls.completeUnimported" nil nil)

The warning is:  LSP :: Invalid type <nil> for bool option "completeUnimported"

### What did you expect to see?

I expect to see no warning.

### What did you see instead?

LSP :: Invalid type <nil> for bool option "completeUnimported"

**Comment by stamblerre** [comment]
Can you share the `gopls` logs for this? How does `lsp-mode` send other requests that contain boolean values?

/cc @muirdm for Emacs expertise

**Comment by muirdm** [comment]
I think you want `("gopls.completeUnimported" nil t)`

The third element should be `t` for all boolean options.

```
(lsp-register-custom-settings PROPS)

Register PROPS.
PROPS is list of triple (path value boolean?) where PATH is the
path to the property, VALUE is either a literal value or symbol
used to retrieve the value, and BOOLEAN? is an optional flag that
should be non-nil for boolean settings.
```

**Comment by stamblerre** [comment]
Thanks for clarifying, @muirdm! Closing this issue.
