### ISSUE TITLE
CGO GoInterface

### ISSUE THREAD

**Issue by long819** [golang/go#35928]
in my go file:
```go
// Add2 ...
//export Add2
func Add2(i, j int, listener AddListener) {
	listener.addResult(i + j)
}
```
and run command:
```
go build  -buildmode=c-shared ./main.go
```
and generate c header file:
```go
……
// Add2 ...
extern void Add2(GoInt p0, GoInt p1, GoInterface p2);
……
```
How do I use the GoInterface？

**Comment by cagedmantis** [comment]
This seems like a question about using cgo. We don't really use our issue tracker for questions. More people will see your question, and you will get better answers, if you ask on a forum rather than on the issue tracker. See https://golang.org/wiki/Questions.
