### ISSUE TITLE
x/tools/gopls: doesn't report errors for disallowed uses of internal packages

### ISSUE THREAD

**Issue by stamblerre** [golang/go#35937]
Forked from https://github.com/microsoft/vscode-go/issues/2926.

Repro:
Add the following to `golang.org/x/tools/blog/blog.go`:

```go
import "golang.org/x/tools/go/internal/gcimporter"

func _() {
	gcimporter.BExportData(nil, nil)
}
```

This code will not compile, but we don't report any errors for it.

**Comment by brainflake** [comment]
Hi @stamblerre - has anyone started this? Thought I could give it a whirl.

**Comment by stamblerre** [comment]
No I don't think anyone has! Please go ahead.

The code you'll want to look at is [here](https://github.com/golang/tools/blob/009580c43b84040d00d902fd677e24bcceff9c0d/internal/lsp/cache/check.go#L343). We'll probably need to detect if the package is an allowed internal package and then add an error. Here's the formal documentation for internal packages: https://golang.org/cmd/go/#hdr-Internal_Directories.

**Comment by brainflake** [comment]
Sound good! Thanks for the pointers.

One question - is it safe to rely on the pkgPath from the metadata passed in to `typeCheck` to compare against the imported pkgPath? I've been seeing it set to `command-line-arguments` during my testing, although it may be just that my VSCode has a misconfiguration.

**Comment by stamblerre** [comment]
`command-line-arguments` can mean that your package is both outside of GOPATH and outside of a module, so if that's your setup then you may see that. But, yes, in general it is safe to compare these package paths.

**Comment by brainflake** [comment]
Great - I created a PR [here](https://github.com/golang/tools/pull/207).

While looking through the code, I found an alternative way to perform the check (using the analysis API) which seems to have the benefit of working with the `gopls` CLI as well as the server. I'm unsure of the performance comparison with using the lsp cache, but just thought I would mention it in case it had merit.

**Comment by stamblerre** [comment]
Anything in the `gopls` codebase will work with both the CLI and the server, so your change is the correct solution - thank you!

The analysis API is typically for analyses on top of type-checked code, but in the case of a package with an invalid import, it really shouldn't even type check. We could potentially add a diagnostic instead of failing to type-check, but that would have the misleading effect of showing users completions that won't compile.

**Comment by stamblerre** [comment]
Fixed via [CL 218977](https://go-review.googlesource.com/c/tools/+/218977).
