### ISSUE TITLE
x/tools/gopls: find references doesn't return all results

### ISSUE THREAD

**Issue by stamblerre** [golang/go#35936]
Forked from https://github.com/golang/go/issues/32869.

Repro case: Find references [here](https://github.com/zrepl/zrepl/blob/d091507ba57bbce9b5b12f10141bc6f26906b27c/zfs/holds.go#L78).

**Comment by juliandkatz** [comment]
When will this be released?

**Comment by stamblerre** [comment]
We are aiming to tag a new release soon, hopefully in the next week or so. I will post updates on this issue: https://github.com/golang/go/issues/33030.

**Comment by juliandkatz** [comment]
@stamblerre, any updates on this release?  This will be a super useful feature for me and I imagine many others!  Thank you

**Comment by stamblerre** [comment]
Sorry for the delay, all! A pre-release will be coming soon, once all of the issues in the gopls/v0.3.0 milestone (https://github.com/golang/go/milestone/129) have been closed.
