### ISSUE TITLE
Wiki: WebAssembly Examples Update

### ISSUE THREAD

**Issue by bgokden** [golang/go#35939]
### This about Wiki page addition:
On this page: https://github.com/golang/go/wiki/WebAssembly

I would like to add this entry under [interacting-with-the-dom](https://github.com/golang/go/wiki/WebAssembly#interacting-with-the-dom) or [Further examples](https://github.com/golang/go/wiki/WebAssembly#further-examples)

* [GoWebian](https://github.com/bgokden/gowebian) A library to build pages with pure go and add WebAssembly bindings.

This project that I started for personal use and I would like to continue working on it to support easier WebAssembly integration and code generation.

**Comment by ianlancetaylor** [comment]
OK, go ahead.  Thanks.
