### ISSUE TITLE
misleading signature of encoding/binary.BigEndian.PutUint32()

### ISSUE THREAD

**Issue by Vany** [golang/go#35943]
Hello!
Seems like `func (bigEndian) PutUint32(b []byte, v uint32)` works with byte slices, but inside it requires this slice be at least 4 elements in size.
So, this signature allow me to put empty slice here and have panic because there is no checks inside.

I propose to change this []byte to [4]byte to make this misleading signature more demanding.

**Comment by ianlancetaylor** [comment]
Thanks for the note, but we can't make that change.  It would break the Go 1 compatibility guarantee (https://golang.org/doc/go1compat).

In any case it's routine in Go for a function to expect a slice to be large enough for the operation.
