### ISSUE TITLE
x/build/cmd/gitmirror: repo build broken for a while

### ISSUE THREAD

**Issue by bsiegert** [golang/go#35944]
The Git mirroring status on farmer.golang.org has been in an error state for a while. https://farmer.golang.org/status/gitmirror says:

```
# "gitmirror" status: Git mirroring
# Notes: https://github.com/golang/build/tree/master/cmd/gitmirror
Error: repo build: broken for 179h57m8.359263516s
```

Maybe this is related to #35120?

/cc @dmitshur @bradfitz

**Comment by bradfitz** [comment]
This is addressed by CL 208697, which removes the mirroring from git to App Engine's datastore.

**Comment by dmitshur** [comment]
This issue is the same as #35828.
