### ISSUE TITLE
net/http/httputil: add sort by quality

### ISSUE THREAD

**Issue by gopherbot** [golang/go#3594]
by **raul.san@sent.com**:

<pre>There is an usefull method which could be added to the type Request in package
&quot;net/http&quot;

type Reverse struct {
	// This embedded Interface permits Reverse to use the methods of
	// another Interface implementation.
	sort.Interface
}

// Less returns the opposite of the embedded implementation's Less method.
func (r Reverse) Less(i, j int) bool {
	return r.Interface.Less(j, i)
}

// parseQualityValues returns the fields sorted by its greater quality level.
// Returns nil if there are no values associated with the header.
//
// [HTTP spec](<a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html)">http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html)</a>
// [Quality Values](<a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.9)">http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.9)</a>
func parseQualityValues(r *http.Request, header string) []string {
	valHeader := r.Header.Get(header)
	if len(valHeader) == 0 {
		return nil
	}

	qValues := make(map[float64][]string)
	qSorted := make([]float64, 0)
	result := make([]string, 0)

	// Example of string to parse for the header Accept-Language:
	//   da, en-gb;q=0.8, en;q=0.7
	for _, f := range strings.Split(valHeader, &quot;,&quot;) {
		lang := &quot;&quot;
		q := 1.0 // default

		if strings.ContainsRune(f, ';') {
			q_ := strings.Split(f, &quot;=&quot;)[1]
			q_ = strings.Trim(q_, &quot; &quot;)

			q, _ = strconv.ParseFloat(q_, 64)
			if q == 0 { // content not acceptable for the client
				continue
			}
			lang = strings.Split(f, &quot;;&quot;)[0]
			lang = strings.Trim(lang, &quot; &quot;)
		} else {
			lang = strings.Trim(f, &quot; &quot;)
		}

		if _, ok := qValues[q]; !ok {
			qValues[q] = make([]string, 0)
		}
		qValues[q] = append(qValues[q], lang)
		qSorted = append(qSorted, q)
	}

	sort.Sort(Reverse{sort.Float64Slice(qSorted)})

	for _, v := range qSorted {
		result = append(result, qValues[v]...)
	}
	return result
}</pre>

**Comment by bradfitz** [comment]
There seems to be lack of interest to add this, and/or lack of need, so I'm going to close this for now. I'm happy to entertain a patch if anybody cares enough later.
