### ISSUE TITLE
x/tools/go/packages: report ImportStack for import cycles

### ISSUE THREAD

**Issue by stamblerre** [golang/go#35964]
When `go list` detects an import cycle, it reports the following error message:

```
$ go list -e -json ~/mod1/foo/
...
"Error": {
	"ImportStack": [
		"mod1/foo",
		"mod1/foo"
	],
	"Pos": "",
	"Err": "import cycle not allowed"
}
...
```

go/packages does not propagate the `ImportStack`, so it's not possible to determine the position in the file that the offending import corresponds to. Ideally, go/packages would propagate the ImportStack in the error, which would allow `gopls` to extract a position for this error message. Even more ideally, `go list` should report a position. :smile: 

/cc @ridersofrohan @matloob @jayconrod

**Comment by ridersofrohan** [comment]
When go/packages detects an import cycle, it says that the pakcages.ErrorKind is a UnknownError not a ListError as defined on [line 38 of internal/lsp/cache/errors.go](https://github.com/golang/tools/blob/master/internal/lsp/cache/errors.go#L38)

**Comment by ridersofrohan** [comment]
This for the most part got handled in [commit/0d08730](https://github.com/golang/tools/commit/0d087302095d5a67b68da7330cad27b122905472). The packages.ErrorKind is still an UnknownError as opposed to a ListError.

**Comment by stamblerre** [comment]
@ridersofrohan: It should be a one-line fix to a kind of List on line 818 of `go/packages/golist.go`, if you or @matloob would like to mail that CL.
