### ISSUE TITLE
x/tools/gopls: cache results of packages.Load

### ISSUE THREAD

**Issue by stamblerre** [golang/go#35968]
@heschik has noticed that we often start running the same `go/packages.Load` call 3 times in parallel on VS Code starting up. This is likely because VS Code issues 3 requests, and rather than wait on the results of `packages.Load` for the second 2 requests, we just see that they are not yet cached and start loading. We should use the `internal/memoize` package for metadata requests so that the subsequent two requests can block, rather than perform redundant reloads.

**Comment by heschik** [comment]
I think this is obsoleted by the new whole-workspace load strategy.

**Comment by stamblerre** [comment]
Yes, agreed.

**Comment by stamblerre** [comment]
Re-opening, as this is actually necessary for https://github.com/golang/go/issues/34111. The main obstacle here is determining a cache key for the calls to `packages.Load`, since they depend on the entire file system state.

/cc @findleyr
