### ISSUE TITLE
text/template: incompatible change using parenthesized expression

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#35974]
Sample program:

```Go
package main

import (
	"log"
	"os"
	"text/template"
)

const source = "{{(len .FileName) gt 0}}\n"

func main() {
	t := template.Must(template.New("x").Parse(source))
	s := struct{ FileName string }{"filename"}
	if err := t.Execute(os.Stdout, &s); err != nil {
		log.Fatal(err)
	}
	s = struct{ FileName string }{""}
	if err := t.Execute(os.Stdout, &s); err != nil {
		log.Fatal(err)
	}
}
```

Using Go 1.2 through Go 1.13 this prints

```
8
0
```

Using tip this fails:

```
2019/12/04 13:45:36 template: x:1:2: executing "x" at <(len .FileName) gt 0>: can't give argument to non-function len .FileName
```

This is due to https://golang.org/cl/206124 "text/template: add error check for parenthesized first argument in pipeline", which was written to fix #31810.

Unless this example is somehow incorrect, I think that we need to roll back that CL and try again for Go 1.15.

CC @robpike

**Comment by bcmills** [comment]
I think that example is incorrect. It is evaluating `(len .FileName)` and discarding, not evaluating, the rest of the pipeline: the `ge` function is prefix, not infix.

Compare https://play.golang.org/p/SgiFOedV7UE.

**Comment by neild** [comment]
Yeah, this is subtle because cases like this one worked by accident: `len .Filename` (the portion of the pipeline which was used) is equivalent to `gt (len .Filename) 0` (what the user intended to write).

**Comment by ianlancetaylor** [comment]
OK, thanks.  I should really try to learn the template language some day.  So the change is good in that it detected a bug.

**Comment by bcmills** [comment]
Note that the corrected version of the example (https://play.golang.org/p/DizRlDZsi8C) produces boolean results instead of numeric ones:
```
true
false
```
