### ISSUE TITLE
x/sys/unix: Prctl should return (int, error)

### ISSUE THREAD

**Issue by robertlacroix** [golang/go#35978]
### What version of Go are you using (`go version`)?

<pre>
go1.13.4
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Linux on amd64

According to http://man7.org/linux/man-pages/man2/prctl.2.html the signature of prctl is

```
int prctl(int option, unsigned long arg2, unsigned long arg3, unsigned long arg4, unsigned long arg5);
```

[unix.Prctl](https://github.com/golang/sys/blob/ef0ce1748380fdf001bd0ff86a45329a12945357/unix/zsyscall_linux_amd64.go#L1221) on the other hand is not returning the int. For some options that return value is relevant, for example `PR_GET_NO_NEW_PRIVS` and others (search for `as the function result` in the man page).

Could `unix.Prctl` be changed to return `(int, error)`?

**Comment by ianlancetaylor** [comment]
I'm not sure we should touch the existing `Prctl`, as that would break existing programs.  But we should probably add a variant that returns `(int, error)`.
