### ISSUE TITLE
x/build/cmd/coordinator: us-central1-f out of resources

### ISSUE THREAD

**Issue by bradfitz** [golang/go#35987]
The coordinator's logs are full of:

```
2019/12/05 06:23:58 failed to create instance buildlet-freebsd-11-2-rn1118db6 in zone us-central1-f: ZONE_RESOURCE_POOL_EXHAUSTED 
2019/12/05 06:23:58 sched.getbuildlet: finish_create_gce_instance, after 2m34.1s; err=Error creating instance: &{Code:ZONE_RESOURCE_POOL_EXHAUSTED Location: Message:The zone 'projects/symbolic-datum-552/zones/us-central1-f' does not have enough resources available to fulfill the request.  Try a different zone, or try again later. ForceSendFields:[] NullFields:[]}; buildlet-freebsd-11-2-rn1118db6 
2019/12/05 06:23:58 Failed to create VM for host-freebsd-11_2: Error creating instance: &{Code:ZONE_RESOURCE_POOL_EXHAUSTED Location: Message:The zone 'projects/symbolic-datum-552/zones/us-central1-f' does not have enough resources available to fulfill the request.  Try a different zone, or try again later. ForceSendFields:[] NullFields:[]} 
```

And the scheduler status shows tons of builds waiting for long times:

https://farmer.golang.org/#sched

`ZONE_RESOURCE_POOL_EXHAUSTED` apparently [means that the zone is out of resources, not our quota](https://stackoverflow.com/questions/52586941/got-an-error-zone-resource-pool-exhausted-when-creating-a-new-instance-on-goog/52599392).

So, yay.

I guess we need to change zones or make it pick a random zone or something, or just ask for a VM in the region.

/cc @andybons @toothrot @dmitshur @cagedmantis @bcmills

**Comment by bradfitz** [comment]
The good news is that legacy networks at least permit us to create VMs in any zone and they can all communicate.

So should be an easy fix.

**Comment by bradfitz** [comment]
So currently we create VMs only in one zone:

https://godoc.org/golang.org/x/build/buildenv#Environment.Zone

But I guess we used to create them in multiple zones since we have this `ZonesToClean []string` field:

https://godoc.org/golang.org/x/build/buildenv#Environment.ZonesToClean

Maybe just unify those into one field "Zones" and have new instances pick a random zone.

Some helpers like this would need to take a `zone string` argument, though:

```go
// MachineTypeURI returns the URI for the environment's Machine Type.                                                                                                                                        
func (e Environment) MachineTypeURI() string {
        return e.ComputePrefix() + "/zones/" + e.Zone + "/machineTypes/" + e.MachineType
}
```

**Comment by toothrot** [comment]
I believe @cagedmantis is looking at this today.

**Comment by bradfitz** [comment]
Now we're out of SSD quota in us-central1:

```
Error: &{Code:QUOTA_EXCEEDED Location: Message:Quota 'SSD_TOTAL_GB' exceeded.  Limit: 8192.0 in region us-central1. ForceSendFields:[] NullFields:[]}
```

The easy fix is to bump our quota, but really we should delete a ton of our old VM images.
