### ISSUE TITLE
misc/cgo/testshared: TestNotes fails on Fedora 31

### ISSUE THREAD

**Issue by mpx** [golang/go#35993]
all.bash fails on Fedora 31 with tip (+cdf3db5df6) and go1.13.5:

```
##### ../misc/cgo/testshared
--- FAIL: TestNotes (0.41s)
    shared_test.go:540: read desc failed: unexpected EOF
FAIL
FAIL    misc/cgo/testshared     20.149s
FAIL
2019/12/05 23:19:18 Failed: exit status 1
```

The `readNotes` func fails during test setup.

Fedora 31 (fails)
* Linux 5.3.13-300.fc31.x86_64
* GNU C Library (GNU libc) stable release version 2.30.
* gcc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)
* GNU ld version 2.32-29.fc31

Fedora 30 (works correctly)
* Linux 5.3.11-200.fc30.x86_64
* GNU C Library (GNU libc) stable release version 2.29.
* gcc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)
* GNU ld version 2.31.1-34.fc30

Possibly Glibc or Binutils/ld related?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/m/.cache/go-build"
GOENV="/home/m/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/m/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/mark/go1.13.4"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/m/go1.13.4/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build260572232=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

Here is a decorated error to assist with debugging:

```
--- FAIL: TestNotes (0.41s)
    shared_test.go:607: read desc failed: readwithpad: got 252 bytes, want 1686352 bytes: unexpected EOF
        data = 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 b0 19 00 00 00 00 00 16 b0 19 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 60 d1 23 00 00 00 00 00 68 d1 23 00 00 00 00 00 08 00 00 00 10 00 00 00 00 01 00 00 47 41 24 01 33 61 31 00 50 bb 19 00 00 00 00 00 09 bc 19 00 00 00 00 00 08 00 00 00 10 00 00 00 00 01 00 00 47 41 24 01 33 61 31 00 60 d1 23 00 00 00 00 00 60 d1 23 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 60 d1 23 00 00 00 00 00 60 d1 23 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 16 b0 19 00 00 00 00 00 1b b0 19 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 68 d1 23 00 00 00 00 00 6d d1 23 00 00 00 00 00 
```

Fedora is an early adopter of new software releases, so this bug may occur on other platforms later as well.

**Comment by mpx** [comment]
Cc @ianlancetaylor

**Comment by siebenmann** [comment]
This failure is now happening for me on Fedora 30 with the current git tip. I thought that this might be related to binutils on Fedora 30 having recently updated to 2.31.1-36.fc30, but reverting to binutils 2.31.1-34.fc30 didn't fix the problem on my machine; it still fails with `shared_test.go:603: read desc failed: unexpected EOF`. One difference between my Fedora 30 machine and the original reporter's is that I'm now running kernel 5.3.13-200.fc30.x86_64 instead of the original reporter's 5.3.11-200 Fedora 30 kernel. However, I have another machine that still has kernel 5.3.11-200.fc30 and it too has the same issue.

**Comment by ianlancetaylor** [comment]
Looks like Fedora is adding a section `.gnu.build.attributes` that has type `SHT_NOTE` but is not in the standard ELF note format.  I don't know why that would be.  I've asked on the binutils@sourceware.org mailing list.

**Comment by ianlancetaylor** [comment]
For the record: https://sourceware.org/ml/binutils/2019-12/msg00089.html

**Comment by ianlancetaylor** [comment]
This turns out to be a bug in strip that caused a bug in the notes recorded in glibc.  This has already been fixed by updating to the current Fedora 31 glibc.  So there is nothing we need to do here on the Go side.

Thanks for reporting it.

**Comment by mpx** [comment]
Thanks for tracking it down!
