### ISSUE TITLE
x/build/env/darwin: one of our 10 Macs is down

### ISSUE THREAD

**Issue by bradfitz** [golang/go#35996]
https://farmer.golang.org/#health says:

```
macstadium_host10a missing, not seen for 11h25m2s
macstadium_host10b missing, not seen for 11h22m30s
2 machines missing, 10% of capacity
makemac daemon: vm.destroy("mac_10_12_host10a") = govc vm.destroy ...: exit status 1, govc: Unable to communicate with the remote host, since it is disconnected.
makemac daemon: vm.destroy("mac_10_15_host10b") = govc vm.destroy ...: exit status 1, govc: Unable to communicate with the remote host, since it is disconnected.
```

Looks like we lost machine 10.

This is another case that would've been handled automatically by #32033 probably. (But this particular bug is about getting it healthy again)

**Comment by cagedmantis** [comment]
I've contacted MacStadium and requested remote hands for:
macstadium_host10a
macstadium_host10b

**Comment by bradfitz** [comment]
They won't know what those mean probably, as those are VM names, not host names.

Also, they have an API for this (#32033) and also a web UI, both letting us do this without their help:

https://portal.macstadium.com/subscriptions

To figure out which IP it is, you can look at https://10.88.203.9/ui/ (see https://github.com/golang/build/tree/master/env/darwin/macstadium)

**Comment by cagedmantis** [comment]
The ticket I filed with MacStadium requests remote hands for three machines:
MacMini-5    [Network connectivity lost]
MacMini-6    [Network connectivity lost]
MacMini-10  [Not responding/ Cannot synchronize host]

While [MacMini-]5,6 seem to be back now, MacMini-10 is not.

**Comment by cagedmantis** [comment]
All three machines are now operational.
