### ISSUE TITLE
x/build/cmd/release: Go 1.13.5 windows installer cannot install if the previous version was manually uninstalled

### ISSUE THREAD

**Issue by Mng12345** [golang/go#36009]
I have deleted the windows go installer of version 1.12.7, while i can not complete the go 1.13.5 installation bacause the installer can not find the go 1.12.7 installer. Finally, i solved this problem by download the go 1.12.7 installer again.

**Comment by agnivade** [comment]
I understand that you are frustrated @Mng12345, but please be mindful of our code of [conduct](https://golang.org/conduct).

I have edited your post to tone down the language.
