### ISSUE TITLE
x/tools/gopls: find references shouldn't include starting identifier

### ISSUE THREAD

**Issue by muirdm** [golang/go#36007]
When you find references on an identifier, the identifier itself is returned as a reference in addition to other locations that reference it. I realized this defeats my editor's if-single-result-jump-straight-there logic since there will be two results even if your identifier is only referenced in one (other) spot.

Is there a reason to keep the starting identifier in the results?

**Comment by stamblerre** [comment]
Seems that LSP has helpfully provided us with an `includeDeclaration` boolean, which I suppose we are ignoring: https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_references. We should probably just respect that, and then editors can decide whether or not to show the declaration.

**Comment by stamblerre** [comment]
Actually, after taking a closer look - it seems like we mostly do respect this setting, unless the identifier was implicitly declared (which I believe only happens in a type switch). So, then I think this sounds like a client-side issue?

**Comment by muirdm** [comment]
I checked and my editor does send `"includeDeclaration": false`.

I think the identifier itself gets included during the normal scan over `Defs`.
