### ISSUE TITLE
month out of range

### ISSUE THREAD

**Issue by SaintKnoe** [golang/go#36011]
### What version of Go are you using (`go version`)?

<pre>
$ go 1.13.4

</pre>

### What did you do?

I want parse string to time 
"2017-10-26" 

### What did you expect to see?
timeformat of "2017-10-26"

### What did you see instead?
but err shows time.parseError 
the ValueElem should be "10" but it is "-10-26"
![image](https://user-images.githubusercontent.com/34902078/70292362-0841cb00-1819-11ea-882d-605e7e1ce1bc.png)

**Comment by mengzhuo** [comment]
Your format is invalid, it should be "2006-01-02"
https://play.golang.org/p/v0ZUa-38liP

**Comment by agnivade** [comment]
Great catch @mengzhuo. @SaintKnoe please let us know if that doesn't fix your issue.

**Comment by SaintKnoe** [comment]
I was so careless!!!
