### ISSUE TITLE
x/tools/gopls: type-conversions are not scored correctly

### ISSUE THREAD

**Issue by quasilyte** [golang/go#36015]
After [CL183137](https://go-review.googlesource.com/c/tools/+/183137), there is a problem with typenames completion where we want to do a type conversion.

It's caused by this check:

```diff
func (c *completer) matchingTypeName(cand *candidate) bool {
+	if !c.wantTypeName() {
+		return false
+	}
```

(Although removing it does solve this particular issue, we get other issues out of it, this is why someone more experienced with gopls needs to take a look.)

It bites when we try to autocomplete inside expression context and expect to use a type conversion:

```go
package main

import (
	"fmt"

)

type coordX float64
type coordY float64

type Point struct {
	X coordX
	Y coordY
}

func main() {
	fmt.Println(Point{
		// <> completion
		// a want to do coordX(value) here
	})	
}
```

In my understanding, a type name is a valid candidate even when not inside type expression context, since it can be an attempt to write a type-converting expression.

## Actual behavior

`coordX` is scored with `1.0`, as all other "non matching" candidates.

## Expected behavior

`coordX` is at least a little bit higher than `1.0`.

Note that `a575db70c06744141b7a52bb6c4aff8d860588c6` (a commit before mentioned CL works as expected):

![image](https://user-images.githubusercontent.com/6286655/70326571-e6ab0880-1845-11ea-996b-7ae934d9d9f7.png)

If we need to define "when a type name is appropriate outside of wantTypeName", I would say it's "an expression context that expects a type that can be acquired by doing a conversion to the given type name". So, if we autocomplete `Foo`-typed expression, `Foo` is a matching candidate (score>1).

**Comment by stamblerre** [comment]
Thank you for the report!

/cc @muirdm for completion expertise

**Comment by muirdm** [comment]
What if instead of completing to just `coordX` it offered a "literal" completion of `coordX(<>)`? Literal completions get a default score of highScore/2, so its score would be 5 instead of 1, i.e. still below the struct field names "X" and "Y".

**Comment by muirdm** [comment]
@quasilyte please try out the above change if possible.

**Comment by muirdm** [comment]
We could also take it further and offer pre-type converted candidates. For example:

```go
func complicatedMath() int

var result float64 = complicat<> // completes straight to "float64(complicatedMath())"
```

It would be cool in some situations, but it runs a bit counter to Go's "no automatic number type conversion" policy.

**Comment by quasilyte** [comment]
> please try out the above change if possible.

Sorry for the late response.

It does work as I would have expected, thank you. :open_hands: 

> It would be cool in some situations, but it runs a bit counter to Go's "no automatic number type conversion" policy.

That sounds interesting, although I usually omit the explicit type on the left, so the type doesn't need to be repeated:

```go
var result = float64(complicatedMath())
```

**Comment by muirdm** [comment]
I think this can be closed out now?

**Comment by quasilyte** [comment]
I believe so.
