### ISSUE TITLE
access: request Trybot access for mengzhuo

### ISSUE THREAD

**Issue by mengzhuo** [golang/go#36013]
Hi, core team guys.

I would like to have  "trybot access" for MIPS porting since my MIPS box only has mips64le/mipsle ability.

my Gerrit email address: mengzhuo1203@gmail.com

https://go-review.googlesource.com/#/admin/groups/1030,members

**Comment by mengzhuo** [comment]
Ping. @dmitris

**Comment by dmitris** [comment]
> Ping. @dmitris

ping-forward @dmitshur

**Comment by andybons** [comment]
Done.
