### ISSUE TITLE
month out of range

### ISSUE THREAD

**Issue by SaintKnoe** [golang/go#36010]
### What version of Go are you using (`go version`)?

<pre>
$ go 1.13.4

</pre>

### What did you do?

I want parse string to time 
"2017-10-26" 

### What did you expect to see?
timeformat of "2017-10-26"

### What did you see instead?
but err shows time.parseError 
![image](https://user-images.githubusercontent.com/34902078/70292362-0841cb00-1819-11ea-882d-605e7e1ce1bc.png)

**Comment by ianlancetaylor** [comment]
I'm sorry, I don't know what you are showing us.  Are you reporting a bug?  Tell us exactly what you did, exactly what happened, and what you expected to happen instead.  Also please fill out the bug template, which you deleted.  Thanks.

**Comment by SaintKnoe** [comment]
the ValueElem should be "10"  but it is "-10-26"
