### ISSUE TITLE
database/sql: ? vs $ inconsistency

### ISSUE THREAD

**Issue by rsc** [golang/go#3602]
<pre>do we care that you have to use different wild cards depending on the back end?

---------- Forwarded message ----------
From: zeroc8 &lt;arnold.angerer@zeroc8.com&gt;
Date: Tue, May 8, 2012 at 2:03 PM
Subject: [go-nuts] Re: Postgres pq - LastInsertId
To: golang-nuts@googlegroups.com

Am Dienstag, 8. Mai 2012 11:19:13 UTC+2 schrieb Alexander Neumann:
&gt;
&gt; Try something like this (untested):
&gt;
&gt; err := db.QueryRow(&quot;INSERT INTO foo (bar) VALUES ($1) RETURNING id;&quot;,
&gt; bar).Scan(&amp;id)
&gt;
&gt;
Thanks, works.
err := tx.QueryRow(&quot;insert into car(name) values($1) returning
id&quot;,&quot;test&quot;).Scan(&amp;id)</pre>

**Comment by nathany** [comment]
As @kardianos [points out](https://github.com/golang/go/issues/3602#issuecomment-66067036), even if placeholders were made consistent, there are other differences between the SQL syntax from one DB driver to the next.

Personally, I think it's better to leave this to the domain of SQL builders, and not start down the slippery slope of trying to have a common dialect, even if only one small aspect of it. My 2 cents.

**Comment by bradrydzewski** [comment]
I agree that this is probably out of scope for the driver. I do, however, think we could make this a bit easier to for developers to manage by exposing the driver name:

```diff
type Driver interface {
        Open(name string) (Conn, error)
+       Name() string
}
```

This would allow me to use the existing `Driver()` function to determine which driver has been loaded and adjust the SQL query as needed:

```
switch db.Driver().Name() {
case "postgres":
  // replace ? with $%d
case "mysql", "sqlite3":
}
```

This would probably require exposing either the `DB` or `Driver` in the transaction as well:

```diff
type Tx struct {
    db *DB
}

func (t *Tx) Driver() driver.Driver {
    return t.db.Driver()
}
```

I think this sort of minor change would make this problem a bit easier to deal with. I've noticed projects writing custom functions to normalize queries (see `sqlx.Rebind` as an example) most of which end up wrapping `sql.DB` just to store and provide access to the the driver name.

**Comment by kostya-sh** [comment]
The first change you propose is backward incompatible and thus cannot be done. If Name() method is added to the Driver interface then all existing drivers will stop implementing Driver interface.

**Comment by minux** [comment]
Adding new method to an existing interface is not possible under the Go 1
API guarantee.

**Comment by bradrydzewski** [comment]
We could adjust the approach the avoid breaking the API guarantee. We could store the `driverName` in the `DB` structure:

```diff
type DB struct {
    driver driver.Driver
+   name   string
    dsn    string
```

Which could be stored when opening the connection, since we have the name:

```diff
func Open(driverName, dataSourceName string) (*DB, error) {
    ...
    driveri, ok := drivers[driverName]
    ...
    db := &DB{
        driver:   driveri,
+       name:   driverName,
        dsn:      dataSourceName,
        openerCh: make(chan struct{}, connectionRequestQueueSize),
        lastPut:  make(map[*driverConn]string),
    }
    ...
}

And then exposed by a function on the `DB` struct:

+func (db *DB) Name() {
+   return db.name
+}
```

**Comment by mattn** [comment]
Note that driver name is possible to be user-defined.

https://github.com/mattn/go-sqlite3/blob/master/_example/custom_func/main.go#L65

**Comment by kardianos** [comment]
I don't see how this can be realistically done across different database vendors. For simple queries, this might be possible, but not for full T-SQL or PL/SQL or pgPL/SQL queries, esp when the query definition starts going into DDL.

If you want to expose the driver name, open a separate issue for that. The various use cases can be discussed there.

**Comment by timbunce** [comment]
I just ran across this issue as I'm stumbling my way into Go and database access.

Historical footnote:

The [Perl DBI](https://metacpan.org/pod/DBI) gained a lot by mandating [over 20 years ago](https://metacpan.org/changes/distribution/DBI) that drivers be required to support `?` for placeholders. (They can support their natural placeholders as well.) The query composition of [SQL::Abstract](https://metacpan.org/pod/SQL::Abstract) stands on the shoulders of that feature. And [DBIx::Class](https://metacpan.org/pod/DBIx::Class) builds on SQL::Abstract.

**Comment by kardianos** [comment]
@timbunce Closed issues aren't tracked. 

From your comment I'm unsure what DBI gained by requiring support for ? placeholders, nor does it address the issues presented above, such as various query dialects, nor does it address systems that don't use positional placeholders at all, but only uses named placeholders.

**Comment by timbunce** [comment]
Hello @kardianos. I appreciate that closed issues aren't tracked. It was just a historical footnote, albeit one that wasn't very clear. To your points:

* `?` placeholders allow a fragment of SQL, coupled with a corresponding list of values for any placeholders, to be passed around and later composed into larger SQL statements without needing to worry about the numbering of `$1` style placeholders, or generating and tracking arbitrary names for `:foo` style placeholders.
* Parsing sufficient to handle placeholders isn't as hard as it may seem, especially as it would be done by the drivers that know their own SQL dialect.
* `?` style placeholders can easily be converted into either of the other styles.

Subsequent to my original comment above I've discovered that [sqlx supports `?` placeholders](http://jmoiron.github.io/sqlx/#namedParams), although it barely gets a mention in the guide.

**Comment by samuelkaufman** [comment]
@timbunce if you're at all interested I've been generating SQL with DBIx::Class and using it in a go project with a reasonable amount of success. I'm now generating SQLite queries as well as the Postgresql queries I started with it has been holding up.
