### ISSUE TITLE
x/tools/gopls: nil pointer panic on current master

### ISSUE THREAD

**Issue by bmhatfield** [golang/go#36020]
### What version of Go are you using (`go version`)?

1.13.4

### Does this issue reproduce with the latest release?

This issue reproduces with current x/tools master (`3393d29b`)

### What operating system and processor architecture are you using (`go env`)?

OSX / VSCode

### What did you do?

I use VSCode with multiple "top level" folders in my workspace. Only one of these workspace top level folders is a go repository.

See also #35455 and #35468 for a description of my environment. Though the error is different, the underlying setup remains the same.

Note that the directory referenced in the error here (schema) does not have Go code within it.

```
2019/12/06 11:47:01 failed to load snapshot: no packages found for query ./...
	directory = file:///Users/bhatfield/Documents/digits/schema
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1593785]

goroutine 12691 [running]:
golang.org/x/tools/internal/lsp/cache.(*snapshot).View(0x0, 0xc001257cd0, 0x0)
	/Users/bhatfield/go/src/github.com/golang/tools/internal/lsp/cache/snapshot.go:61 +0x5
golang.org/x/tools/internal/lsp.(*Server).diagnoseSnapshot(0xc00020c960, 0x18516e0, 0x0)
	/Users/bhatfield/go/src/github.com/golang/tools/internal/lsp/diagnostics.go:20 +0x69
created by golang.org/x/tools/internal/lsp.(*Server).addFolders
	/Users/bhatfield/go/src/github.com/golang/tools/internal/lsp/general.go:173 +0x600
```

### What did you expect to see?

No crash.

### What did you see instead?

VSCode told me that gopls was repeatedly crashing

**Comment by bmhatfield** [comment]
I just spent some time trying different commits, and this error was introduced with `a5887330` - cc @stamblerre

**Comment by stamblerre** [comment]
Thank you for tracking this down! Just mailed a fix.
