### ISSUE TITLE
proxy.golang.org: invalid zip file when using the proxy

### ISSUE THREAD

**Issue by asticode** [golang/go#36035]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/asticode/Library/Caches/go-build"
GOENV="/Users/asticode/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/asticode/projects/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/asticode/bite/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xg/1_vvjbvd1vg50jcd6g4b1tqm0000gn/T/go-build242958915=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I ran the following commands:

```
$ mkdir /tmp/test
$ cd /tmp/test
$ go mod init test.com/test
$ go get github.com/asticode/go-astibob
```

### What did you expect to see?

```
go: finding github.com/asticode/go-astibob v1.0.1
go: downloading github.com/asticode/go-astibob v1.0.1
go: extracting github.com/asticode/go-astibob v1.0.1
go: downloading github.com/asticode/go-astitools v1.2.2
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/asticode/go-astilog v1.2.0
go: downloading github.com/julienschmidt/httprouter v1.3.0
go: extracting github.com/pkg/errors v0.8.1
go: extracting github.com/asticode/go-astilog v1.2.0
go: extracting github.com/julienschmidt/httprouter v1.3.0
go: extracting github.com/asticode/go-astitools v1.2.2
go: downloading github.com/mattn/go-colorable v0.1.4
go: downloading golang.org/x/crypto v0.0.0-20191205161847-0a08dada0ff9
go: downloading github.com/sirupsen/logrus v1.4.2
go: extracting github.com/mattn/go-colorable v0.1.4
go: extracting github.com/sirupsen/logrus v1.4.2
go: downloading github.com/mattn/go-isatty v0.0.10
go: downloading github.com/asticode/go-astiamqp v1.1.0
go: downloading github.com/asticode/go-astiws v1.0.1
go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.2
go: downloading golang.org/x/sys v0.0.0-20191204072324-ce4227a45e2e
go: extracting github.com/mattn/go-isatty v0.0.10
go: extracting github.com/konsorten/go-windows-terminal-sequences v1.0.2
go: extracting github.com/asticode/go-astiamqp v1.1.0
go: downloading github.com/streadway/amqp v0.0.0-20190827072141-edfb9018d271
go: extracting github.com/asticode/go-astiws v1.0.1
go: downloading github.com/gorilla/websocket v1.4.1
go: extracting github.com/streadway/amqp v0.0.0-20190827072141-edfb9018d271
go: extracting github.com/gorilla/websocket v1.4.1
go: extracting golang.org/x/crypto v0.0.0-20191205161847-0a08dada0ff9
go: extracting golang.org/x/sys v0.0.0-20191204072324-ce4227a45e2e
go: finding github.com/asticode/go-astitools v1.2.2
go: finding github.com/julienschmidt/httprouter v1.3.0
go: finding github.com/asticode/go-astilog v1.2.0
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/asticode/go-astiamqp v1.1.0
go: finding github.com/asticode/go-astiws v1.0.1
go: finding github.com/sirupsen/logrus v1.4.2
go: finding golang.org/x/crypto v0.0.0-20191205161847-0a08dada0ff9
go: finding github.com/streadway/amqp v0.0.0-20190827072141-edfb9018d271
go: finding github.com/gorilla/websocket v1.4.1
go: finding golang.org/x/sys v0.0.0-20191204072324-ce4227a45e2e
```

### What did you see instead?

```
go: finding github.com/asticode/go-astibob v1.0.1
go: downloading github.com/asticode/go-astibob v1.0.1
go get github.com/asticode/go-astibob: zip: not a valid zip file
```

### Additionnal info

This issue occured yesterday all day. When using `GOPROXY=direct` it worked fine.

Today it works fine even without `GOPROXY=direct`.

I've an idea why, but still would rather check with you guys.

Hence my questions:

- why did I get an invalid zip file error in the first place?
- why is it working now?
- did I have any solution to fix the problem yesterday instead of using `GOPROXY=direct` (invalidating the proxy cache maybe)?

Cheers

**Comment by hyangah** [comment]
Thanks a lot for the report. I filed an internal bug to investigate. 

I don't know why/whether the proxy returned a bad zip yet. If the proxy ever served a bad data,
that bad data may have been cached in the content cache on the path.
It's still strange to me that the issue lasted for a day though since our http cache ttl shouldn't be that long.

If cache is the culprit, yes, `GOPROXY=direct` is a workaround. 

@heschik @katiehockman

**Comment by heschik** [comment]
Thanks for the report. We were able to track down the issue, and the fix should roll out in the next couple of days. There was a race condition when the first download of a module version was outside the US and network conditions were imperfect.
