### ISSUE TITLE
encoding/json:How can I know which field is an "empty value" of a decoded struct?

### ISSUE THREAD

**Issue by RealBar** [golang/go#36033]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre>GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/wangyalou/go/bin"
GOCACHE="/home/wangyalou/.cache/go-build"
GOENV="/home/wangyalou/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/wangyalou/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build435379182=/tmp/go-build -gno-record-gcc-switches"</details>

### What did you do?

```
type User struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Age      int    `json:"age,omitempty"`
}

func main() {
	var u User
	d := json.NewDecoder(bytes.NewBufferString(`{"username":"foo","password":"bar"}`))
	_ = d.Decode(&u)
	fmt.Println(u.Age)
}
```
 How can I know the printed 0 is a parsed value or an empty value?

### What did you expect to see?

There should be a method that decode a json string into a struct and returns a map indicating which fields has been appeared in the the json string and which has not.

### What did you see instead?
No such method

**Comment by ianlancetaylor** [comment]
When you need to know whether a field appeared or not, use a pointer.

https://play.golang.org/p/3YIUzyrjlHb
