### ISSUE TITLE
x/tools/gopls: CL 200604 does not take into account ContentFormat

### ISSUE THREAD

**Issue by myitcv** [golang/go#36031]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +acf3ff2e8a Tue Dec 3 17:35:06 2019 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20191206204035-259af5ff87bd => /home/myitcv/gostuff/src/golang.org/x/tools
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.1.8-0.20191206204035-259af5ff87bd => /home/myitcv/gostuff/src/golang.org/x/tools/gopls
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build041971431=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Starting `gopls` with `Initialize` params as follows:

```json
{
	"Workspace": {
		"configuration": true,
		"didChangeConfiguration": {
			"dynamicRegistration": true
		},
		"didChangeWatchedFiles": {},
		"executeCommand": {},
		"symbol": {
			"symbolKind": {}
		},
		"workspaceEdit": {}
	},
	"textDocument": {
		"codeAction": {
			"codeActionLiteralSupport": {
				"codeActionKind": {
					"valueSet": null
				}
			}
		},
		"codeLens": {},
		"colorProvider": {},
		"completion": {
			"completionItem": {
				"tagSupport": {
					"valueSet": null
				}
			},
			"completionItemKind": {}
		},
		"declaration": {},
		"definition": {},
		"documentHighlight": {},
		"documentLink": {},
		"documentSymbol": {
			"symbolKind": {}
		},
		"foldingRange": {},
		"formatting": {},
		"hover": {
			"contentFormat": [
				"plaintext"
			]
		},
		"implementation": {},
		"onTypeFormatting": {},
		"publishDiagnostics": {
			"tagSupport": {
				"valueSet": null
			}
		},
		"rangeFormatting": {},
		"references": {},
		"rename": {},
		"selectionRange": {},
		"signatureHelp": {
			"signatureInformation": {
				"parameterInformation": {}
			}
		},
		"synchronization": {},
		"typeDefinition": {}
	}
}
```

Note hover content format is `plaintext`.

Then trigger a hover, and observe the following response:

```json
{
	"kind": "plaintext",
	"value": "func fmt.Println(a ...interface{}) (n int, err error)\nPrintln formats using the default formats for its operands and writes to standard output.\nSpaces are always added between operands and a newline is appended.\nIt returns the number of bytes written and any write error encountered.\n\n[Println on pkg.go.dev](https://pkg.go.dev/fmt#Println)"
}

```

Note the markdown formatting around the pkg.go.dev link.

### What did you expect to see?

No markdown formatting in the plaintext hover response.

### What did you see instead?

Markdown formatting.

It's also unclear to me that we want to unconditionally add this line to every hover documentation response. 

---

cc @stamblerre @heschik

**Comment by stamblerre** [comment]
Thanks for reporting this. I've already mailed [CL 210201](https://go-review.googlesource.com/c/tools/+/210201), which should address this.
