### ISSUE TITLE
strings: please add `UnwriteByte` to `Builder`

### ISSUE THREAD

**Issue by jech** [golang/go#36038]
Go version 1.13.

There does not seem to be a way to remove data written to a `strings.Builder`.

I'm currently doing the following:

```
func pathUrl(p []string) string {
	var b []byte
	for _, s := range p {
		t := url.PathEscape(s)
		b = append(b, t...)
		b = append(b, '/')
	}
	return string(b[0 : len(b)-1])
}
```
The last line removes the trailing slash from the accumulated buffer.  I don't see an obvious way of doing the same with a `strings.Builder`.  Perhaps it would be a good idea to add `UnwriteByte`, `UnwriteRune` and perhaps `UnwriteString` functions to `strings.Builder`?

**Comment by ianlancetaylor** [comment]
It seems to me easy enough to write

```Go
func pathUrl(p []string) string {
	var b []byte
	for i, s := range p {
		if i > 0 {
			b = append(b, '/')
		}
		t := url.PathEscape(s)
		b = append(b, t...)
	}
	return string(b)
}
```

I'm not convinced it's worth the complexity of adding `Unwrite` methods to `strings.Builder`.

**Comment by josharian** [comment]
If you are unwriting only the final byte, you could use strings.Builder and then slice away the final byte of the string.

**Comment by jech** [comment]
@ianlancetaylor, I agree that it's a matter of taste.  It becomes a little more messy when `i` is not readily available (when the components are not coming from a slice).

Feel free to close if you feel that this proposal is unlikely to gain consensus.

**Comment by renthraysk** [comment]
I'd personally deal with p[0] outside the loop, and range over p[1:], and never have to unwrite.

https://play.golang.org/p/LODpCtD3mjh

**Comment by ianlancetaylor** [comment]
I think it's always going to be straightforward to not write data, and very few `io.Writer` implementations implement `UnwriteByte`.  So I do think this is unlikely to gain consensus.
