### ISSUE TITLE
x/sys: Commit bc7efcf introduced a compilation error

### ISSUE THREAD

**Issue by brotherlogic** [golang/go#36032]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.14 linux/arm 
</pre>

### Does this issue reproduce with the latest release?

Not sure

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="arm"
GOBIN=""
GOCACHE="/home/simon/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/simon/code"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build242404953=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

go build on any binary

### What did you expect to see?

Compilation

### What did you see instead?

# golang.org/x/sys/unix
/home/simon/code/src/golang.org/x/sys/unix/zptrace_armnn_linux.go:45:57: cannot use uint64(unsafe.Sizeof(*regsout)) (type uint64) as type uint32 in field value
/home/simon/code/src/golang.org/x/sys/unix/zptrace_armnn_linux.go:51:54: cannot use uint64(unsafe.Sizeof(*regs)) (type uint64) as type uint32 in field value

**Comment by stgraber** [comment]
I was literally writing the exact same report.

```
root@go-armhf:~# go get golang.org/x/sys/unix
# golang.org/x/sys/unix
go/src/golang.org/x/sys/unix/zptrace_armnn_linux.go:45:57: cannot use uint64(unsafe.Sizeof(*regsout)) (type uint64) as type uint32 in field value
go/src/golang.org/x/sys/unix/zptrace_armnn_linux.go:51:54: cannot use uint64(unsafe.Sizeof(*regs)) (type uint64) as type uint32 in field value
root@go-armhf:~# go version
go version go1.13.5 linux/arm
```

**Comment by stgraber** [comment]
bc7efcf3b808453416a7bd2865c52f98896d1975 is the commit modifying `zptrace_armnn_linux.go` and introducing the issue.

**Comment by stgraber** [comment]
https://github.com/golang/sys/commit/bc7efcf3b808453416a7bd2865c52f98896d1975

**Comment by ianlancetaylor** [comment]
I can't think of any approach we can use here other than generating yet another zptrace file.

**Comment by happyEgg** [comment]
I had the same problem。
gomobile build -target=android
go version go1.13.5 darwin/amd64
gomobile is latest
gomobile log:
commit 5c0e7e404af8b014d8b7de89f9522bc92463f3cb (HEAD -> master, origin/master, origin/HEAD)
Author: Hajime Hoshi <hajimehoshi@gmail.com>
Date:   Wed Nov 27 22:57:30 2019 +0900

**Comment by probonopd** [comment]
Also running into this error. Getting this lately:

```
env CC=arm-linux-gnueabi-gcc CGO_ENABLED=1 GOOS=linux GOARCH=arm GOARM=5 go build -trimpath -ldflags="-s -w -X main.commit=$COMMIT" github.com/probonopd/go-appimage/src/appimaged

# golang.org/x/sys/unix

../../../go/src/golang.org/x/sys/unix/zptrace_armnn_linux.go:45:57: cannot use uint64(unsafe.Sizeof(*regsout)) (type uint64) as type uint32 in field value

../../../go/src/golang.org/x/sys/unix/zptrace_armnn_linux.go:51:54: cannot use uint64(unsafe.Sizeof(*regs)) (type uint64) as type uint32 in field value
```

https://travis-ci.com/probonopd/go-appimage/jobs/264315306#L297-L300

It the bug related to this change?

https://github.com/golang/sys/commit/bc7efcf3b808453416a7bd2865c52f98896d1975#diff-31214f098b1c4e1abcd3e80a787f6cf5

**Comment by MarcelEeken** [comment]
Also just ran into this issue

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/marcel/Library/Caches/go-build"
GOENV="/Users/marcel/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/marcel/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/marcel/prive/enmon/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0s/tlwngfxs4l76lnlk8j3z0s2h0000gn/T/go-build442831853=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Trying to cross compile for ARM target
<pre>
$ GOOS=linux GOARCH=arm GOARM=6 go build -o build/enmon_arm
# golang.org/x/sys/unix
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20191206220618-eeba5f6aabab/unix/zptrace_armnn_linux.go:45:57: cannot use uint64(unsafe.Sizeof(*regsout)) (type uint64) as type uint32 in field value
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20191206220618-eeba5f6aabab/unix/zptrace_armnn_linux.go:51:54: cannot use uint64(unsafe.Sizeof(*regs)) (type uint64) as type uint32 in field value
</pre>

**Comment by ianlancetaylor** [comment]
No need to keep reporting the problem.  https://golang.org/wiki/NoPlusOne.  Thanks.

We know there is a problem and we will either roll back the change or add a fix.

**Comment by erifan** [comment]
Sorry for the trouble. I'll fix it as soon as possible.

**Comment by bus710** [comment]
A band-aid for beginners like me, pick an older version in the go.mod like this:

```
golang.org/x/sys v0.0.0-20191126131656-8a8471f7e56d // indirect
```

**Comment by erifan** [comment]
I have sent out a fix (https://go-review.googlesource.com/c/sys/+/210322) but the page did not refresh.

**Comment by zikaeroh** [comment]
You have to write "Fixes golang/go#36032", not "Fixes #36032" to get gopherbot to recognize the issue when working from a repo other than the main Go repo.

**Comment by erifan** [comment]
@zikaeroh Thanks.

**Comment by zhangfannie** [comment]
@ianlancetaylor  What about redefining Iovec{} struct as IovecArm64{] struct in unix/zptrace_armnn_linux.go file?

**Comment by sigkill** [comment]
Also breaking P4wnP1_aloa too...

**Comment by probonopd** [comment]
> A band-aid for beginners like me, pick an older version in the go.mod like this:

What if one doesn't use modules?

**Comment by bus710** [comment]
> > A band-aid for beginners like me, pick an older version in the go.mod like this:
> 
> What if one doesn't use modules?

Not sure how many of package manager out there but for Go Dep at least:
- https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
- Edit gopkg.toml for the version entry to pick the right branch and commit.
