### ISSUE TITLE
Add encoding/binary.HostEndianness

### ISSUE THREAD

**Issue by ddevault** [golang/go#36040]
For the purpose of detecting the endianness of the host machine/toolchain. This would be equal to either binary.BigEndian or binary.LittleEndian, with which they could be compared, or it could be passed directly into binary.Read/binary.Write et al.

**Comment by bontibon** [comment]
Recently closed: [proposal: encoding/binary: add NativeEndian](https://github.com/golang/go/issues/35398)

**Comment by ddevault** [comment]
Should I leave comments in that thread or in this one? My use-case is interop with external systems which are endian-sensitive. In this case, I'm implementing the Wayland wire protocol, and Wayland packets are defined to use host endianness.

**Comment by ianlancetaylor** [comment]
I don't think anything has changed since #35398.  In any case, that is the place to leave comments, although it's unlikely to make a difference.
