### ISSUE TITLE
cmd/go: run unable to start file that begins with period

### ISSUE THREAD

**Issue by nektro** [golang/go#36045]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Untested.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/meghan/snap/code/common/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/meghan/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build591367948=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```
go run etc/.test.go
```

### What did you expect to see?
The output of the program.

### What did you see instead?
```
package main: no Go files in /home/meghan/dev/go/scratch/etc
```

**Comment by AlexRouSg** [comment]
https://golang.org/cmd/go/#hdr-Package_lists_and_patterns

> Directory and file names that begin with "." or "_" are ignored by the go tool, as are directories named "testdata".

**Comment by ALTree** [comment]
What @AlexRouSg said. Closing here.

**Comment by nektro** [comment]
Do you not feel that `go run`ing a specific file should be an exception to this rule? I would assume as a user that that definition only refers to other files and packages.

**Comment by ianlancetaylor** [comment]
The current behavior is working as documented.  We could consider changing the behavior.  But I can't see a use for Go files whose name starts with a period, so it doesn't seem like a priority.
