### ISSUE TITLE
Google Source down

### ISSUE THREAD

**Issue by santhoshashok** [golang/go#36049]
>go get https://go.googlesource.com/sys/
>fatal: unable to access 'https://go.googlesource.com/sys/': The requested URL returned error: 502

**Comment by ALTree** [comment]
Thanks for reporting this. 

This is already tracked in #36048, feel free to subscribe to that issue. Closing here as a dup.

**Comment by adlyzth** [comment]
This url "https://go.googlesource.com/net" had same problem. Please fix it. 
Thanks
