### ISSUE TITLE
gerit: getting 502 on https://go.googlesource.com/tools

### ISSUE THREAD

**Issue by bilfash** [golang/go#36048]
go version go1.13 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"

### What did you do?
go get -u golang.org/x/lint/golint

### What did you expect to see?
go lint installed

### What did you see instead?
fatal: unable to access 'https://go.googlesource.com/lint/': The requested URL returned error: 502
package golang.org/x/lint/golint: exit status 1

**Comment by bilfash** [comment]
Back to normal.

Thanks @ALTree

**Comment by bilfash** [comment]
hey, its happening again @ALTree.
may you share what happen with googlesource server?

**Comment by ALTree** [comment]
Probably a server outage. cc @heschik

**Comment by walbertus** [comment]
Experiencing the same, is there any status page for this outage?

**Comment by mkfeuhrer** [comment]
Same issue !! Can't find any status page?

**Comment by opan** [comment]
Same here :/

**Comment by goshashwat** [comment]
Same here

**Comment by caiokf** [comment]
I am having the same. Is there a status page we can reference?

**Comment by orgmatileg** [comment]
Same here

**Comment by ALTree** [comment]
Reminder we have a [NoPlusOne policy](https://github.com/golang/go/wiki/NoPlusOne). Writing "me too" or "same here" does not add much. Thank you.

**Comment by cylin743** [comment]
Same here

**Comment by VipinKrizz** [comment]
When i tried to do build the keadm.go file using go build -o keadm keadm.go i am getting this error.
fatal: unable to access 'https://go.googlesource.com/sync'
fatal: unable to access 'https://go.googlesource.com/oauth2'
fatal: unable to access 'https://go.googlesource.com/crypto'
fatal: unable to access 'https://go.googlesource.com/time'
fatal: unable to access 'https://go.googlesource.com/text'
fatal: unable to access 'https://go.googlesource.com/net'
fatal: unable to access 'https://go.googlesource.com/sys'
fatal: unable to access 'https://go.googlesource.com/gocloud'

and in the end of evey line there is  The requested URL returned error:502
Any solutions anybody??

**Comment by sumityadav-gommt** [comment]
I am experiencing the same issue, 'https://go.googlesource.com/tools/' is giving 502 error.

**Comment by bilfash** [comment]
> When i tried to do build the keadm.go file using go build -o keadm keadm.go i am getting this error.
> fatal: unable to access 'https://go.googlesource.com/sync'
> fatal: unable to access 'https://go.googlesource.com/oauth2'
> fatal: unable to access 'https://go.googlesource.com/crypto'
> fatal: unable to access 'https://go.googlesource.com/time'
> fatal: unable to access 'https://go.googlesource.com/text'
> fatal: unable to access 'https://go.googlesource.com/net'
> fatal: unable to access 'https://go.googlesource.com/sys'
> fatal: unable to access 'https://go.googlesource.com/gocloud'
> 
> and in the end of evey line there is The requested URL returned error:502
> Tried GOPROXY=https://proxy.golang.org
> this also gave error only
> Any solutions anybody??

What go version did you use?
if you use 1.13 default goproxy is https://proxy.golang.org,direct 
https://golang.org/doc/go1.13#modules

**Comment by VipinKrizz** [comment]
> > When i tried to do build the keadm.go file using go build -o keadm keadm.go i am getting this error.
> > fatal: unable to access 'https://go.googlesource.com/sync'
> > fatal: unable to access 'https://go.googlesource.com/oauth2'
> > fatal: unable to access 'https://go.googlesource.com/crypto'
> > fatal: unable to access 'https://go.googlesource.com/time'
> > fatal: unable to access 'https://go.googlesource.com/text'
> > fatal: unable to access 'https://go.googlesource.com/net'
> > fatal: unable to access 'https://go.googlesource.com/sys'
> > fatal: unable to access 'https://go.googlesource.com/gocloud'
> > and in the end of evey line there is The requested URL returned error:502
> > Tried GOPROXY=https://proxy.golang.org
> > this also gave error only
> > Any solutions anybody??
> 
> What go version did you use?
> if you use 1.13 default goproxy is https://proxy.golang.org,direct
> https://golang.org/doc/go1.13#modules

go version am using is go1.12.5 linux/arm

**Comment by puzzloholic** [comment]
All googlesource is down currently

https://android.googlesource.com
https://go.googlesource.com
https://chromium.googlesource.com

and no status page to monitor anything

**Comment by VipinKrizz** [comment]
> All googlesource is down currently
> 
> https://android.googlesource.com
> https://go.googlesource.com
> https://chromium.googlesource.com
> 
> and no status page to monitor anything
Was this happening for a long time?
because yesterday i guess working fine.

**Comment by VipinKrizz** [comment]
> All googlesource is down currently
> 
> https://android.googlesource.com
> https://go.googlesource.com
> https://chromium.googlesource.com
> 
> and no status page to monitor anything

is there any alternative way... because i have been trying to install kubeedge on RaspberryPi for the last few days.

**Comment by mkfeuhrer** [comment]
It's working now. Thanks @ALTree

**Comment by VipinKrizz** [comment]
> It's working now. Thanks @ALTree

googlesource working fine?

**Comment by heschik** [comment]
The Go team doesn't support Gerrit and as far as I'm aware there was no public incident report. We encourage use of a module proxy such as `proxy.golang.org` wherever possible.

**Comment by VipinKrizz** [comment]
@ALTree 
i am still getting the error.

**Comment by ALTree** [comment]
@VipinKrizz Please open a new issue. Fill in all the details requested in the template, including your environment and the steps you do when you encounter the error. Thanks.
