### ISSUE TITLE
Best practice for private proxy that needs to modify module sums

### ISSUE THREAD

**Issue by xytan0056** [golang/go#36046]
### What version of Go are you using (`go version`)?
go1.13

<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
N/A
</pre></details>

### What did you do?

N/A

### What did you expect to see?
N/A

### What did you see instead?
N/A

When running our own proxy in order to support `GOPROXY` in module mode, we need to write our own logic to interact with internal VCS. Since proxy.golang.org is not open sourced, we may miss some implicit requirement. (even with project like gomods/athens, we still need to write customized logic). Whenever we find the difference that our proxy is not consistent with proxy.golang.org, and decide on a fix that causes sums to change, we'll have to ask people to `go clean --modcache`. This is inefficient. 

e.g. 
1. [PR](https://go.googlesource.com/go/+/c7385e270473244ef5aa312a172f1912e99800be%5E%21/src/cmd/go/internal/modload/import.go) : in [go1.12](https://sourcegraph.com/github.com/golang/go@go1.12.9/-/blob/src/cmd/go/internal/modload/import.go#L183) checking zip contents hierarchy doesn't explicitly fail, but does so in [go1.13](https://sourcegraph.com/github.com/golang/go@go1.13.4/-/blob/src/cmd/go/internal/modload/import.go#L197:24).

2. [PR](https://go.googlesource.com/go/+/f7248f05946c1804b5519d0b3eb0db054dc9c5d6%5E%21/src/cmd/go/internal/modload/load.go) : import path is enforced for compatible v2 mods. 

However we didn't think of these case previously. So now, we need to rewrite the import path due to (2). 
```
corp.com/team/tools@v2.0.0
corp.com/team/tools/v2@v2.0.0
```
But we return the same zip for both. Due to check in (1), we have to change our proxy to include the v2 in zip prefix, resulting in zip sum changes, we'll have to `go clean --modcache`.

I'm thinking we can version the cache (at least for our internal modules), if we decide to make changes in proxy, go toolchain will recognize this and ignore old version of cache. But this somehow violate immutability of module cache.

Advice will be appreciated

**Comment by toothrot** [comment]
A better place to ask this kind of question is golang-nuts. More people will see your question, and you will get better answers, if you ask on a forum rather than on the issue tracker. See https://golang.org/wiki/Questions.
