### ISSUE TITLE
net/http fixes

### ISSUE THREAD

**Issue by rocketdv** [golang/go#36056]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 windows/amd64
</pre>

### Suggestions for `net/http`
+ allow for header order to match the order in which they were added, currently it sorts them alphabetically, and this can be fingerprinted very easily when web scraping and causes me to get blocked sometimes
+ implement [`cronet`](https://github.com/chromium/chromium/tree/master/components/cronet) or at least `tls grease` cipher, this will also stop me from getting blocked, some sites check what ciphers were sent

**Comment by bradfitz** [comment]
Header order was #24375 (closed).

TLS ciphers are not part of the net/http package.

You could probably define your own Transport.DialTLS func that shells out to `openssl s_client` if you really needed to.

Closing, as there's nothing for me to do here.

**Comment by rocketdv** [comment]
will header order ever be supported

**Comment by bradfitz** [comment]
If the right design emerges or we redo a bunch of the APIs and get to make new decisions.
