### ISSUE TITLE
x/tools/gopls: return statement steals highlighting

### ISSUE THREAD

**Issue by muirdm** [golang/go#36057]
It looks like the "return" highlighting is taking precedence over things within the return statement.

```go
type foo struct{ bar int }

func _() foo {
	return foo{
		bar: 123, // trigger highlight at the "bar"
	}
}
```

If you trigger highlighting at the "bar" in the composite literal, I expect it to highlight just the "bar" field, but it highlights the entire return statement.

/cc @ridersofrohan

**Comment by muirdm** [comment]
Thanks for looking at this. Out of curiosity why do we highlight the entire return statement instead of just the "return" keyword? If the return statement is long (esp if multiline), it's really a lot of highlighting. Similarly we highlight the entire composite literal (body) instead of just the composite literal's type name when highlighting on the type name (e.g. `foo{` in the example above).

**Comment by ridersofrohan** [comment]
We looked at what Goland does when it comes to highlighting inside of a return statement and if you highlight any field in the return list, then it will highlight the entire field and the corresponding param in the return list within the function declaration. For instance,

```
func test() (bool, int) {
    return false, 1;
}
```

When you highlight false, it will also highlight bool and if you highlight bool it will highlight all the first fields for each return statement.

In the case that you used as an example, if you just highlight the foo in the type declaration, it will only highlight the composite literal's type name, not the whole body. Highlighting inside the return statement is the only case where the whole body would get highlighted.

**Comment by muirdm** [comment]
Thanks for the explanation. I didn't realize it was connected to the function results like that.
