### ISSUE TITLE
godep save error: go/src/golang.org/x/crypto/acme" is not using a known version control system

### ISSUE THREAD

**Issue by ZacZelner** [golang/go#36051]
### What version of Go are you using (`go version`)?
$ go version
go version go1.13.4 darwin/amd64

### Does this issue reproduce with the latest release?
Downloading the latest Crypto from golang/crypto

error:

zac$ godep save
godep: dirty working tree (please commit changes): /Users/zac/go/src/github.com/astaxie/beego
godep: dirty working tree (please commit changes): /Users/zac/go/src/github.com/astaxie/beego/config
godep: dirty working tree (please commit changes): /Users/zac/go/src/github.com/astaxie/beego/context
godep: dirty working tree (please commit changes): /Users/zac/go/src/github.com/astaxie/beego/context/param
godep: dirty working tree (please commit changes): /Users/zac/go/src/github.com/astaxie/beego/grace
godep: dirty working tree (please commit changes): /Users/zac/go/src/github.com/astaxie/beego/logs
godep: dirty working tree (please commit changes): /Users/zac/go/src/github.com/astaxie/beego/session
godep: dirty working tree (please commit changes): /Users/zac/go/src/github.com/astaxie/beego/toolbox
godep: dirty working tree (please commit changes): /Users/zac/go/src/github.com/astaxie/beego/utils
godep: error while inspecting "/Users/zac/go/src/golang.org/x/crypto/acme": directory "/Users/zac/go/src/golang.org/x/crypto/acme" is not using a known version control system
godep: error while inspecting "/Users/zac/go/src/golang.org/x/crypto/acme/autocert": directory "/Users/zac/go/src/golang.org/x/crypto/acme/autocert" is not using a known version control system
godep: error loading dependencies

**Comment by agnivade** [comment]
Hello @ZacZelner - please file an issue here - https://github.com/golang/dep. Thanks.
