### ISSUE TITLE
net/http: proxied connection can be spuriously closed after dialConn as of CL 210286

### ISSUE THREAD

**Issue by bcmills** [golang/go#36070]
A timeout in `net/http.TestTransportProxy` seems to have started around [CL 210286](https://golang.org/cl/210286):
```
panic: test timed out after 3m0s

goroutine 2138 [running]:
testing.(*M).startAlarm.func1()
	/workdir/go/src/testing/testing.go:1422 +0x9
created by time.goFunc
	/workdir/go/src/time/sleep.go:168 +0x5

[…]

goroutine 2125 [chan receive]:
net/http_test.TestTransportProxy.func1(0xb08360)
	/workdir/go/src/net/http/transport_test.go:1424 +0x5a
testing.tRunner(0xb08360, 0xa3af60)
	/workdir/go/src/testing/testing.go:954 +0xc
created by testing.(*T).Run
	/workdir/go/src/testing/testing.go:1005 +0x30

[…]

goroutine 2107 [chan receive, 2 minutes]:
testing.(*T).Run(0xb08360, 0xa62860, 0x20, 0xa3af60, 0x2)
	/workdir/go/src/testing/testing.go:1006 +0x31
net/http_test.TestTransportProxy(0x875d40)
	/workdir/go/src/net/http/transport_test.go:1324 +0x6
testing.tRunner(0x875d40, 0x13aca0)
	/workdir/go/src/testing/testing.go:954 +0xc
created by testing.(*T).Run
	/workdir/go/src/testing/testing.go:1005 +0x30
FAIL	net/http	184.130s
```

[2019-12-09T21:50:59-3a3093d/js-wasm](https://build.golang.org/log/725578cad20b9ce0e7d54e0a3b7032dc1c4aedbd)
[2019-12-09T20:19:32-7d24e95/js-wasm](https://build.golang.org/log/04fda7088db5b43f87ca34b8eaeece6acd3d8616)
[2019-12-09T16:41:15-a3a630b/js-wasm](https://build.golang.org/log/45c0a3ac373760ab48e5eef7c48370472d32971a)

CC @bradfitz @ianlancetaylor

**Comment by bcmills** [comment]
That CL was the fix for #28012.

**Comment by bradfitz** [comment]
It passed the trybots at the time.
 
Does a js-wasm net.Conn not reliably interrupt a blocked Read on Close or something?

I'm fine just skipping that test on js-wasm for now.

**Comment by bcmills** [comment]
I don't know the underlying cause of the failure. The failure rate seems to be around 50%, which would explain the passing TryBot.

**Comment by bcmills** [comment]
(CC @neelance @cherrymui for the question about the js-wasm `net` implementation.)

**Comment by bradfitz** [comment]
The new code in CL 210286 adds a 1 minute timeout reading the CONNECT response if no context deadline was otherwise present.

It's possible the net/http tests are just so slow on wasm that it's straddling that 1 minute timeout already (~50% of the time?) with all the parallel tests. But, uh, TestTransportProxy isn't t.Parallel.

**Comment by bcmills** [comment]
Found the bug, I think:
https://go-review.googlesource.com/c/go/+/210286/2/src/net/http/transport.go#1588

**Comment by bradfitz** [comment]
Whoops, thanks!
