### ISSUE TITLE
x/crypto/ssh/terminal: ReadPassword reads a maximum of 254 chars on Windows

### ISSUE THREAD

**Issue by ncw** [golang/go#36071]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes (not tried tip)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\Administrator\go\src\github.com\rclone\rclone\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\2\go-build381157862=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I ran this program and typed > 254 characters

```go
package main

import (
       "os"
       "fmt"
       "golang.org/x/crypto/ssh/terminal"
)

func main() {
        val, err := terminal.ReadPassword(int(os.Stdin.Fd()))
        fmt.Println(err)
        fmt.Printf("len=%d: %q\n", len(val), val)
}
```

### What did you expect to see?

I expected to see all the characters I typed or an error message

### What did you see instead?

My input string silently truncated to the first 254 characters.

```
go run x.go
<nil>
len=254: "alskdjflaskdjfaslkdfjlskdjflaksdjflskdjfalsdkfjlsakdfjlasdkfjlaskdfjalskdfjlasdkfjlasdkfjlsadkfjlasdkfjlsadkfjadslkfjlasdkfjadslkfjlasdkfjlakdsfjldsakfjlasdkfjlsadkfjlasdkfjlskdfjlaskdfjlakdsfjladksfjlaskdfjladksfjlasdkfjalsdkfjlasdkfjladskfjasldkfjalsdf"
```

**Comment by toothrot** [comment]
/cc @FiloSottile @katiehockman @alexbrainman 

As you mentioned, this does look to be windows specific. I was not able to reproduce this on Linux.

**Comment by alexbrainman** [comment]
@ncw I can reproduce your problem.

I briefly looked at your code, and I cannot see why returned result is limited to 254 chars.

Maybe @mattn know.

Alex

**Comment by silviucm** [comment]
@ncw  @alexbrainman 
Not exactly sure if applicable, so apologies in advance, but here's a .NET doc page that mentions the 254 character limitation, due to a default internal buffer, and suggests an alternative

https://docs.microsoft.com/en-us/dotnet/api/system.console.readline?view=netframework-4.8

> By default, the method reads input from a 256-character input buffer. Because this includes the Environment.NewLine character(s), the method can read lines that contain up to 254 characters. To read longer lines, call the OpenStandardInput(Int32) method.

From what I am seeing here, it's pointing to that:
https://github.com/golang/go/blob/master/src/internal/poll/fd_windows.go#L540

In case the same API is used, that may explain what's happening

**Comment by mattn** [comment]
It is limit of ENABLE_LINE_INPUT. When using ReadConsole with ENABLE_LINE_INPUT, the input buffer always be 254 (256 - \r - \n). To solve this issue, ReadPassword stop to use ENABLE_LINE_INPUT.

```diff
diff --git a/ssh/terminal/terminal.go b/ssh/terminal/terminal.go
index 2f04ee5..39f92a2 100644
--- a/ssh/terminal/terminal.go
+++ b/ssh/terminal/terminal.go
@@ -947,9 +947,13 @@ func readPasswordLine(reader io.Reader) ([]byte, error) {
 		n, err := reader.Read(buf[:])
 		if n > 0 {
 			switch buf[0] {
-			case '\n':
+			case 8:
+				if len(ret) > 0 {
+					ret = ret[:len(ret)-2]
+				}
+			case 13:
 				return ret, nil
-			case '\r':
+			case 10:
 				// remove \r from passwords on Windows
 			default:
 				ret = append(ret, buf[0])
diff --git a/ssh/terminal/util_windows.go b/ssh/terminal/util_windows.go
index 5cfdf8f..bd21765 100644
--- a/ssh/terminal/util_windows.go
+++ b/ssh/terminal/util_windows.go
@@ -85,8 +85,8 @@ func ReadPassword(fd int) ([]byte, error) {
 	}
 	old := st
 
-	st &^= (windows.ENABLE_ECHO_INPUT)
-	st |= (windows.ENABLE_PROCESSED_INPUT | windows.ENABLE_LINE_INPUT | windows.ENABLE_PROCESSED_OUTPUT)
+	st &^= (windows.ENABLE_ECHO_INPUT | windows.ENABLE_LINE_INPUT)
+	st |= (windows.ENABLE_PROCESSED_INPUT | windows.ENABLE_PROCESSED_OUTPUT)
 	if err := windows.SetConsoleMode(windows.Handle(fd), st); err != nil {
 		return nil, err
 	}
```

**Comment by mattn** [comment]
Sorry, the code above is wrong. we must stop to use ENABLE_PROCESSED_INPUT too.

**Comment by mattn** [comment]
For the note: https://github.com/dotnet/corefx/commit/f37461280a3c843000aa79642ba700baa5a1fc30

**Comment by ncw** [comment]
I merged this fix into rclone however @Ajaja reported in https://github.com/rclone/rclone/pull/3888 that the Enter key no longer works.

I can confirm this, the little test program above fails on WIndows 10  - you can't press Enter to end the input.

**Comment by alexbrainman** [comment]
> I merged this fix into rclone however @Ajaja reported in [rclone/rclone#3888](https://github.com/rclone/rclone/pull/3888) that the Enter key no longer works.

Sorry for submitting completely broken version.

> Sorry, I missed the new issue about this #36609

Yes. The fix https://go-review.googlesource.com/c/crypto/+/215417 is out for review.

Alex
