### ISSUE TITLE
gccgo: Dead code elimination does not work if a standard package is in use.

### ISSUE THREAD

**Issue by xaionaro** [golang/go#36073]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xaionaro/.cache/go-build"
GOENV="/home/xaionaro/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xaionaro/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/xaionaro/.gimme/versions/go1.13.linux.amd64"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/xaionaro/.gimme/versions/go1.13.linux.amd64/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build136817121=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```sh
mkdir ~/gccgo-dce-bug/uselesspackage
cd ~/gccgo-dce-bug
cat > main.go <<EOF
package main
import _ "./uselesspackage"
func main() {}
EOF
cat > uselesspackage/useless_func.go <<EOF
package uselesspackage
func uselessFunc() {}
EOF
go build -compiler gccgo -gccgoflags '-flto -Os'; nm gccgo-dce-bug | grep useless
```

### What did you expect to see?

Empty output.

### What did you see instead?

```
0000000000002428 t __home_xaionaro_gccgo_dce_bug_uselesspackage.uselessFunc
```

**Comment by xaionaro** [comment]
Option `-Wl,--gc-sections` solves the case I mentioned in the ticket.

**Comment by toothrot** [comment]
@xaionaro Do you believe this issue should be closed, or is there something else to improve here?

**Comment by xaionaro** [comment]
@toothrot I think in the real case DCE still does not work. But I have no proof, yet. If I will not find any proofs in next 24 hours then I will close this issue, OK?

**Comment by xaionaro** [comment]
@toothrot confirmed, in real case it does not work:
```
root@ubuntu:~/go/src/github.com/u-root/u-root/bb# go build -compiler gccgo -gccgoflags '-flto -Os -fdata-sections -ffunction-sections -Wl,--gc-sections'; nm bb | grep Useless; strip -s bb; ls -lhd bb
00000000005ae631 T github_com_u_root_u_root_vendor_github_com_vishvananda_netlink.UselessFunc
-rwxr-xr-x 1 root root 19M Dec 10 19:45 bb
```

I've just added an useless function which is not used from anywhere. I don't know how much time it will take to isolate the problem and create a simple test case, yet. Working...

**Comment by xaionaro** [comment]
Found a test case:

```
mkdir ~/gccgo-dce-bug/uselesspackage
cd ~/gccgo-dce-bug
cat > main.go <<EOF
package main
import _ "./uselesspackage"
func main() {}
EOF
cat > uselesspackage/useless_func.go <<EOF
package uselesspackage
import "encoding/binary"
var nativeEndian binary.ByteOrder
func UselessFunc() {}
EOF
rm gccgo-dce-bug; go build -compiler gccgo -gccgoflags '-flto -Os -fdata-sections -ffunction-sections -Wl,--gc-sections'; nm gccgo-dce-bug | grep Useless
```

Expected empty output, but received:
```
00000000000024bb T __home_xaionaro_gccgo_dce_bug_uselesspackage.UselessFunc
```

**Comment by ianlancetaylor** [comment]
You need to use `-gccgoflags=all='-ffunction-sections'`.  See the discussion of the `pattern` argument to `-gccgoflags` and friends at https://golang.org/cmd/go/#hdr-Compile_packages_and_dependencies.

**Comment by xaionaro** [comment]
@iamoryanmoshe I already tried this option, it does not help.
