### ISSUE TITLE
x/build/cmd/coordinator: don't stop short when testing packages on release branches

### ISSUE THREAD

**Issue by dmitshur** [golang/go#36089]
Right now, on release branches, testing is stopped very soon after encountering the first package with a failing test. E.g., from https://build.golang.org/log/b002647c8a5f7c73883916c5327af69cfe44dd3d:

```
[...]
FAIL	cmd/go/internal/modfetch	17.181s
ok  	cmd/go/internal/modfetch/codehost	5.474s
FAIL
2019/11/07 02:35:34 Failed: exit status 1
```

Ideally we should not have failing tests on release branches for a long amount of time, but that is not the current state. Until we reach that state, it might be helpful to modify coordinator so that it keeps testing all packages even if one fails, and report the test results in the log. That way, a package that fails early doesn't make it completely impossible to see if other package tests pass or fail.

/cc @bcmills @bradfitz @cagedmantis @toothrot

**Comment by bcmills** [comment]
This would also be handy for non-release branches: it would at least somewhat mitigate the problem of known test failures masking other regressions.

**Comment by dmitshur** [comment]
I limited this issue to release branches because I thought it would have much higher benefit-to-cost ratio. If it goes well there, we can consider expanding this to other branches too (but let's discuss it more first).

People seem in favor so I'll move forward to `NeedsFix`, but really the next step is this needs investigation to determine how big or small of a change it'll take.

**Comment by dmitshur** [comment]
I'm seeing a relevant `-k` flag in `go tool dist test`:

```
$ go tool dist test -help
usage: go tool dist test [options]
[...]
  -k	keep going even when error occurred
[...]
```

If that's it, then this is a matter of arranging for that flag to be set to an appropriate value in `cmd/coordinator` when on testing a release branch.

**Comment by bradfitz** [comment]
Dup of #14305
