### ISSUE TITLE
Process  will crash immediately

### ISSUE THREAD

**Issue by e9571** [golang/go#36081]
### What version of Go are you using (`go version`)?

1.13

<pre>
$ go version 

</pre>

### Does this issue reproduce with the latest release?

YES

### What operating system and processor architecture are you using (`go env`)?

Windows，CentOS

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

ed25519.go

line：173

	if l := len(publicKey); l != PublicKeySize {
		panic("ed25519: bad public key length: " + strconv.Itoa(l))
	}

### What did you do?

I called the function **func Verify** , however, the process dies immediately.

### What did you expect to see?

I just wanna see the **False  judgement**

### What did you see instead?

Process  immediately crashed.

**Comment by seankhliao** [comment]
it is documented to panic:
> Verify reports whether sig is a valid signature of message by publicKey. It will panic if len(publicKey) is not PublicKeySize.

**Comment by ianlancetaylor** [comment]
Working as documented.
