### ISSUE TITLE
proxy.golang.org: differs from go toolchain on incompatible imports

### ISSUE THREAD

**Issue by xytan0056** [golang/go#36090]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/tanx/go/bin"
GOCACHE="/Users/tanx/Library/Caches/go-build"
GOENV="/Users/tanx/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tanx/gocode"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/tanx/sdk/go1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/tanx/sdk/go1.13/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/tanx/gocode/src/github.com/gorilla/mux/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nn/f16l5j1j2f14ctsnkk305lf00000gp/T/go-build217308097=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```
$ go1.13 list -m -versions -json github.com/hexonet/go-sdk/v2@latest
{
	"Path": "github.com/hexonet/go-sdk/v2",
	"Version": "v2.2.3",
	"Versions": [
		"v2.0.0",
		"v2.0.1",
		"v2.1.0",
		"v2.2.0",
		"v2.2.1",
		"v2.2.2",
		"v2.2.3"
	],
	"Time": "2019-10-04T15:17:43Z"
}
$ curl https://proxy.golang.org/github.com/hexonet/go-sdk/v2/@latest
not found: github.com/hexonet/go-sdk/v2@v2.2.3: invalid version: missing github.com/hexonet/go-sdk/go.mod and .../v2/go.mod at revision v2.2.3

$ curl https://proxy.golang.org/github.com/hexonet/go-sdk/@latest
{"Version":"v2.2.3+incompatible","Time":"2019-10-04T15:17:43Z"}
```

### What did you expect to see?
proxy response should match go toolchain. In this case `go list -m` should return `error` as well. This inconsistency impacts proxy project that uses `go list -m` such as gomods/Athen

**Comment by heschik** [comment]
I can't reproduce this with any of 1.13, 1.13.3, or 1.13.5.
```
$ GO111MODULE=on GOPROXY=direct go1.13 list -m -versions -json github.com/hexonet/go-sdk/v2@latest
go: finding github.com/hexonet/go-sdk/v2 v2.2.3
go list -m: github.com/hexonet/go-sdk/v2@v2.2.3: invalid version: missing github.com/hexonet/go-sdk/go.mod and .../v2/go.mod at revision v2.2.3
```

**Comment by hyangah** [comment]
@xytan0056 `go list` takes `-x` and that will give you whether your `go list` command issued the proxy and what response code the proxy returned. Can you try the command again with `-x`?
Thanks.

**Comment by xytan0056** [comment]
hmmm I just tried again. it errors out as expected. Maybe something to do with my cache
