### ISSUE TITLE
x/tools/go/packages/packagestest: support markers in go.mod files

### ISSUE THREAD

**Issue by stamblerre** [golang/go#36091]
Users of `packagestest` may want to put markers in `go.mod` files to run tests. This is particularly relevant for `gopls` handling `go.mod` files correctly.

/cc @ridersofrohan @ianthehat

**Comment by ridersofrohan** [comment]
In addition, this would be helpful for refactoring internal/lsp/mod/mod_test.go to use x/tools/go/packages/packagestest.
