### ISSUE TITLE
hash/crc32: unexpected output (?)

### ISSUE THREAD

**Issue by Anveena** [golang/go#36097]
### What version of Go are you using (`go version`)?
go1.13.4
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

	data := []byte{0x00,0xB0,0x0D,0x00,0x01,0xC1,0x00,0x00,0x00,0x01,0xF0,0x00,}
	tb := crc32.MakeTable(0x04C11DB7)
        rs := crc32.Update(0xFFFFFFFF, tb,data)
        println(rs)
//some crc hash algorithms DO NOT need reverse bit but some DO
//but "hash/crc32" in current go source version DOES NOT support both.
//https://crccalc.com/?crc=00B00D0001C100000001F000&method=crc32&datatype=hex&outtype=hex
//it's the right value.

**Comment by ALTree** [comment]
@Anveena It's not clear what kind of issue you are reporting here. Please provide a complete-runnable program, and explain in more details what you are doing and why the output you get is different from the one you expect.
