### ISSUE TITLE
gomobile android, 应用只设置jni armeabi-v7a 运行在x86的平板上出现闪退问题

### ISSUE THREAD

**Issue by 994866755** [golang/go#36100]
### What version of Go are you using (go version)?
$ go version
go version go1.13.4 windows/amd64
### Does this issue reproduce with the latest release?
Yes

用go mobile导出aar解压后只导入armeabi-v7a文件夹打包，运行在一般手机上能正常运行，运行在x86的平板上出现闪退，请问有办法解决吗？

**Comment by bcmills** [comment]
Per https://pkg.go.dev/golang.org/x/mobile/cmd/gomobile?tab=doc,
> By default, -target=android builds shared libraries for all supported instruction sets (arm, arm64, 386, amd64). A subset of instruction sets can be selected by specifying target type with the architecture name. E.g., -target=android/arm,android/386.

Did you set the `-target` flag? (What was the exact `gomobile` command that you used to build the app?)

When it crashed on the tablet, did it produce a goroutine dump or other output? (What was the cause of the crash?)

**Comment by bcmills** [comment]
CC @hyangah @steeve

**Comment by steeve** [comment]
It seems it crashed because of a missing architecture. Not sure there's a bug.

**Comment by 994866755** [comment]
使用-target是会生成所有的，但是是我将aar解压，只引用了armeabi-v7a，运行在X86会崩溃。我应用中的其它so即便是armeabi-v7a中的也能兼容x86，go生成的so没办法兼容吗?

**Comment by sunsiansong** [comment]
> 使用-target是会生成所有的，但是是我将aar解压，只引用了armeabi-v7a，运行在X86会崩溃。我应用中的其它so即便是armeabi-v7a中的也能兼容x86，go生成的so没办法兼容吗?

@994866755 老哥，既然你要跑在x86上，为什么不用x86的so，或者干脆所有so都打包进去，这样不是更直接么？是考虑节省包体么？节省体积的话要不要考虑架构拆分、分别打包？要是兼容是好的方案的话，那也不用每个架构出一个so了。

**Comment by hyangah** [comment]
@994866755 gomobile uses ndk and [this doc](https://developer.android.com/ndk/guides/abis) explains how to layout .so files. If the apk size is a concern, in many years ago, packaging a separate apk for each supported api was a one way. I didn't test it myself but according to https://developer.android.com/studio/build/configure-apk-splits.html that's no longer necessary and users need to just upload their complete app bundle.

**Comment by 994866755** [comment]
我这边情况比较特殊，我是开发SDK的，为什么不导入全部的文件夹这个是接入端决定的。
问题已解决，我更换所有so的名称，去修改Seq的代码判读当前手机的框架再去动态加载对应的so
