### ISSUE TITLE
x/website: redirect golang.org/x/<repo> to pkg.go.dev instead of godoc.org

### ISSUE THREAD

**Issue by hyangah** [golang/go#36106]
<nothing more to add>

**Comment by hyangah** [comment]
One issue I noticed is that godoc.org shows the version in the master branch, while pkg.go.dev shows the "latest released" version. For example, golang.org/x/mod shows the doc from v0.1.0 because that's the latest released version. (https://pkg.go.dev/golang.org/x/mod/semver?tab=versions)  But some users may want to see the doc for the recent version commited in the master branch. pkg.go.dev currently does not provide an easy way to achieve that unless the user already knows the pseudo version mapped from the current master commit.

@julieqiu

**Comment by zikaeroh** [comment]
Being able to easily access master was something I reported during the private beta but hasn't happened. I'd love for there to be a link to `@master` in the version list and support for `@master` in the URL.

**Comment by bradfitz** [comment]
I wish `?tab=docs` were the default without a redirect. I mean, it's already the default. I just wish it didn't redirect. The URL is much nicer without it. That's the main reason I continue to use godoc.org. Also, godoc.org gives me links to more headings.

**Comment by toothrot** [comment]
The redirect to `?tab=doc` is a compromise while the correct default tab is being investigated, giving us some flexibility to change it in the future. (my vote is for doc)

I believe the long-term goal is for this issue to happen, but there is still some feature parity gap to close. @julieqiu knows more.

**Comment by dmitshur** [comment]
This is done as of [CL 275195](https://golang.org/cl/275195).
