### ISSUE TITLE
access: may-start-trybots

### ISSUE THREAD

**Issue by titanous** [golang/go#36119]
I'd like trybot access, thanks!

Email: jonathan@titanous.com
URL: https://go-review.googlesource.com/#/admin/groups/1030,members

/cc @andybons @dmitshur

**Comment by bradfitz** [comment]
Done.

**Comment by bradfitz** [comment]
(Usual warnings apply: use your new powers carefully. Review the code before you start the trybots, in case it's malicious... the build system is mostly isolated but not perfectly.)
