### ISSUE TITLE
x/tools/gopls: does not conform to Go documentation on non-scalar GOPATH

### ISSUE THREAD

**Issue by maverickwoo** [golang/go#36120]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

I am currently one patch level behind. But based on the source code on current master shown below, I believe it will reproduce with the latest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env | sed s/$USER/user/g
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/user/go:/Users/user/go-work"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/local/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/local/lib/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="/usr/bin/clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/q_/jc67mj41687gcm21gq1z853m0000gn/T/go-build770602489=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

VSCode installed `gopls` for me, and it shows an error message when I get to a go file that is (i) in my `GOPATH` but (ii) imports an unsatisfied dependency. For example, try:
```go
package main

import "missingpackagehere"
```

The error message is:
> You are neither in a module nor in your GOPATH. Please see https://github.com/golang/go/wiki/Modules for information on how to set up your Go project.

I believe this is because my `GOPATH` is a colon-separated string:
> `GOPATH="/Users/user/go:/Users/user/go-work"`

This type of non-scalar `GOPATH`s is supported in Go 1 according to the current Go documentation https://golang.org/cmd/go/#hdr-GOPATH_environment_variable:
> The GOPATH environment variable lists places to look for Go code. On Unix, the value is a colon-separated string. On Windows, the value is a semicolon-separated string. On Plan 9, the value is a list.

However, this line of code at current master does not appear to support such non-scalar `GOPATH`s. https://github.com/golang/tools/blob/0f69de236bb709847e215a792a40aaee1cba60d9/internal/lsp/source/errors.go#L50:
```go
inGopath := strings.HasPrefix(uri.Filename(), filepath.Join(gopath, "src"))
```

### What did you expect to see?

I expect `gopls` to support `GOPATH`s allowed by the Go documentation and therefore not return the error message shown above.

### What did you see instead?

I saw the error message shown above.

**Comment by dmitshur** [comment]
The [`filepath.SplitList`](https://pkg.go.dev/path/filepath#SplitList) function should be useful for resolving this issue.
