### ISSUE TITLE
time.Since conversion exception

### ISSUE THREAD

**Issue by abcdlzy** [golang/go#36146]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\a\AppData\Local\go-build
set GOENV=C:\Users\a\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\a\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\a\AppData\Local\Temp\go-build603352082=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

calculate application execute time elapsed , source code：
<pre>

package main
import(
	"fmt"
	"strings"
	"time"
)

func main(){
	for i:=0;i<10;i++ {

		t:=time.Now()
		str1:=">>>12345678901234567890<<<"
		isStartContain:=strings.Contains(str1,">>>")
		isEndContain:=strings.Contains(str1,"<<<")

		if(isStartContain&&isEndContain){
			sIndex:=strings.Index(str1,">>>")
			eIndex:=strings.Index(str1,"<<<")
			getstr:=str1[sIndex+3:eIndex-sIndex]
			fmt.Println(getstr)
		} else {
			fmt.Println("not found")
		}
		elapsed := time.Since(t)
		elapsedInt:=int32(time.Since(t))

		fmt.Println("app elapsed:", elapsed,elapsedInt)
	}
}

</pre>

### What did you expect to see?
Time less than 1 millisecond should be displayed correctly

### What did you see instead?
![image](https://user-images.githubusercontent.com/10682959/70858909-b0f0d880-1f45-11ea-97e0-cd1723838c70.png)
![image](https://user-images.githubusercontent.com/10682959/70858913-c0702180-1f45-11ea-9fb5-99a4f2a20e35.png)

**Comment by ianlancetaylor** [comment]
When using `time.Now` the time package can only report timestamps within the clock frequency of the system.  On Windows for Go programs the default clock frequency is 1 millisecond.  There isn't anything we can do to fix this on Windows.
