### ISSUE TITLE
It would be really helpful if testing.T has assertion methods like t.AssertEqual(x, y), t.AssertNotEqual(x, y) etc?

### ISSUE THREAD

**Issue by cyantarek** [golang/go#36149]
I like to rely on standard packages whenever I can. But it seems like the testing package comes with go misses some useful features that current industry uses. One of them is result equality assertion

It would be really helpful if testing.T has assertion methods like t.AssertEqual(x, y), t.AssertNotEqual(x, y) etc

This will make the testing package more idiomatic and standard way to assert things rather than doing with if else boilerplate code all the time or having to rely on third party assertion packages.

Anyway, what I expressed in this issue is solely my own opinion. You may disagree. That's completely ok.

**Comment by robpike** [comment]
This is covered in the FAQ: 
https://golang.org/doc/faq#testing_framework
