### ISSUE TITLE
run java .class file with external library .jar in golang os/exec

### ISSUE THREAD

**Issue by m3mara** [golang/go#36156]
### What version of Go are you using (`go version`)?

<pre>
$ go version is go1.13.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
i'm not sure if it's an issue or not,
i just need to know if i can run this command 
> **java -cp .;"lib/calc.jar" Hello**
it is working just fine with cmd or bash 

### What operating system and processor architecture are you using (`go env`)?
windows 10  64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

**func command(arg ...string) (string, error) {
	out, err := exec.Command("C:/Program Files/Java/jdk-13.0.1/bin/javaw.exe", "-cp .;\"lib/calc.jar\" Hello", arg[0]).Output()
	if err != nil {
		return "", err
	}
	return string(out), nil
}**

this is were i got an error
**out, err := exec.Command("C:/Program Files/Java/jdk-13.0.1/bin/javaw.exe", "-cp .;"lib/calc.jar" Hello", arg[0]).Output()**

this line is working fine but without icluding extrnal library in java code
**out, err := exec.Command("C:/Program Files/Java/jdk-13.0.1/bin/javaw.exe", "Hello", arg[0]).Output()**

### What did you expect to see?
i expet it run 
### What did you see instead?
command:  exit status 1

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
