### ISSUE TITLE
Can't recover from go: unknown environment setting GO111MODULE=autoGO111MODULE=auto

### ISSUE THREAD

**Issue by dylankb** [golang/go#36154]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.13.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

I'm on the latest version I believe. I'm aware of the fix to prevent this type of problem in [1.14](https://go-review.googlesource.com/c/go/+/200867/)

### What operating system and processor architecture are you using (`go env`)?

`go env` is broken but I'm on a Mac - I installed my go version with via `go1.13.5.darwin-amd64.tar.gz`

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Fat fingered writing to the Go modules environment variable. What I did.

```
go env -w GO111MODULE=autoGO111MODULE=auto
```

When I meant to do

```
go env -w GO111MODULE=auto
```

It looks like a person [here](https://github.com/golang/go/issues/35321#issuecomment-551206902) was able to  I'm unable to reset the `GO111MODULE` environment variable to a good state, but I am not. It sounds like [others](https://github.com/golang/go/issues/35321#issuecomment-549359334) cannot fix their go even after a fresh install - is there any advice on how to recover from this?

```
$ go env -w GO111MODULE=off
go: unknown environment setting GO111MODULE=autoGO111MODULE=auto
go env -w GO111MODULE=on
go: unknown environment setting GO111MODULE=autoGO111MODULE=auto
$ go env -w GO111MODULE=auto
go: unknown environment setting GO111MODULE=autoGO111MODULE=auto
```

### What did you expect to see?

No error message when running `go env` or other go commands.

### What did you see instead?

`go: unknown environment setting GO111MODULE=autoGO111MODULE=auto`

**Comment by seankhliao** [comment]
looks like it should be fixed for 1.14

 but for now it is probably reading the bad config from: `/Users/<you>/Library/Application Support/go/env`, edit manually to hopefully resolve the issue

**Comment by dylankb** [comment]
Thanks @seankhliao! That fixed the issue.

**Comment by jedebarbieri** [comment]
@seankhliao Hello, where I can find this file in Windows?

**Comment by jedebarbieri** [comment]
> @seankhliao Hello, where I can find this file in Windows?

I found out the location of the env file for window: 

`C:\Users\<Your User>\AppData\Roaming\go`

file "env"

**Comment by mvdan** [comment]
@jedebarbieri this issue is closed, and is not the place to ask questions. See https://golang.org/wiki/Questions.
