### ISSUE TITLE
x/tools/gopls: doesn't work with GOPATH vendoring

### ISSUE THREAD

**Issue by ian-mi** [golang/go#36155]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.9 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes
<pre>
gopls version
golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=
</pre>

### What operating system and processor architecture are you using (`go env`)?
See logs.

### What did you do?
Performed the following steps:
1. Opened the file fake.go.
2. Added the import github.com/google/go-cmp/cmp.
3. Typed cmp.Diff.
4. Saved the file.
5. Retyped cmp.Diff.

These steps seem to reliably reproduce the issue.

### What did you expect to see?
Expected to see completion results for the newly imported package before saving the file.

### What did you see instead?
I saw no completion results for cmp.Diff before saving the file but did after saving.
[gopls.log](https://github.com/golang/go/files/3966187/gopls.log)
[lsp-trace.log](https://github.com/golang/go/files/3966188/lsp-trace.log)

**Comment by heschik** [comment]
I can't reproduce this with gopls master either in GOPATH or module mode. Can you give master a try?

**Comment by ian-mi** [comment]
Yes, I was able to reproduce the issue on master but the logs look much different.
[gopls.log](https://github.com/golang/go/files/3971214/gopls.log)
[lsp-trace.log](https://github.com/golang/go/files/3971215/lsp-trace.log)

**Comment by ian-mi** [comment]
This particular project is in GOPATH mode using vendored deps. I haven't tried to reproduce the issue in module mode.

**Comment by ian-mi** [comment]
I've also seen a similar issue when creating a new file gopls won't work in that buffer until the file is saved to disk.

**Comment by heschik** [comment]
Your logs weirdly don't mention cmp at all, but I was able to reproduce the problem by checking out knative-gcp and following the same steps.

Pretty sure this has something to do with vendoring. I get errors like
```
[Error - 3:46:18 PM] 2019/12/17 15:46:18 no dep handle: no metadata for github.com/google/knative-gcp/vendor/github.com/google/go-cmp/cmp
        package = github.com/google/knative-gcp/vendor/github.com/google/go-cmp/cmp
```
which are quite suspicious.

**Comment by heschik** [comment]
At a bare minimum, this code simply won't work with GOPATH vendoring.
https://github.com/golang/tools/blob/210e553fe1f64b5f29af9b359e51cb5216e1cd8e/internal/lsp/cache/check.go#L312

**Comment by heschik** [comment]
There's also some code path where we do `go list` on an import path, which also doesn't work; afaict you have to list the vendor path, e.g. `github.com/google/knative-gcp/vendor/github.com/google/go-cmp/cmp`.

**Comment by heschik** [comment]
That is probably happening in the `go/packages` overlay support, which needs to augment the response with the packages that are imported only in the overlay.

Sigh.
