### ISSUE TITLE
net.Dial raises ENOENT, but os.IsNotExist returns false

### ISSUE THREAD

**Issue by shabbyrobe** [golang/go#36150]
I am trying to connect to a unix socket that may not be open yet. I want to retry a few times if the connection fails and the socket file doesn't exist yet. I tried to use `os.IsNotExist` on the error, but it returns `false`, although `errors.Is(err, os.ErrNotExist)` returns `true`. This is not really causing me any direct difficulty as I can just use the latter form and keep going, but this inconsistency felt like a bit of a "principle of least astonishment" violation so I felt compelled to report. I didn't find any other direct mentions of this problem in the issue tracker.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```go
func main() {
	_, err := net.Dial("unix", "/tmp/some-file-that-definitely-does-not-exist")
	fmt.Println("errno:", int(errors.Unwrap(errors.Unwrap(err)).(syscall.Errno)))
	fmt.Println("errors.Is", errors.Is(err, os.ErrNotExist))
	fmt.Println("os.IsNotExist:", os.IsNotExist(err))
}
```

### What did you expect to see?

<pre>
errno: 2
errors.Is true
os.IsNotExist: true
</pre>

### What did you see instead?

<pre>
errno: 2
errors.Is true
os.IsNotExist: false
</pre>

**Comment by ianlancetaylor** [comment]
This is difficult to implement since the net package imports the os package, so the os package can't know about any special net package error types.  This kind of problem is exactly what `errors.Is` is intended to address.  So I think we're just going to encourage `errors.Is` going forward.

**Comment by shabbyrobe** [comment]
That makes sense. Thanks for the quick response.

Given this behaviour is reasonable to intend from your side but not reasonable to expect from mine, the documentation for `os.IsNotExist` should make this clear. It currently says:

>  IsNotExist returns a boolean indicating whether the error is known to report that a file or directory does not exist. It is satisfied by ErrNotExist as well as some syscall errors. 

It should at least say something like:

>  IsNotExist returns a boolean indicating whether the error is known by the os package to report that a file or directory does not exist. It is satisfied by ErrNotExist as well as some syscall errors, but not by errors in the net package. If you need to check for errors not known by the os pacakge, you should use 'errors.Is(err, os.ErrNotExist)' instead.

And arguably, if the plan is to favour a newer, better, faster and stronger function and idiom, it should say this instead:

> os.IsNotExist is deprecated. Use 'errors.Is(err, os.ErrNotExist)' instead.

I'm happy to put a PR together if any of these suggestions are agreeable.

**Comment by ianlancetaylor** [comment]
Go docs should ideally be both accurate and terse.  I believe that is true of the current doc.

I don't think the doc of os.IsNotExist should refer to the net package.  The net package is just one example.

I personally would be OK with adding a sentence to suggest using errors.Is instead.

**Comment by shabbyrobe** [comment]
> I personally would be OK with adding a sentence to suggest using errors.Is instead.

Great! I see your point that the `os` package should not mention `net`, but what's the best way to convey this accurately without doing so, while still protecting users from the same mistake I made?

It seems the problem is in saying "... as well as some syscall errors". It _would_ actually catch ENOENT if it wasn't wrapped in a `net.OpError`, but a `net.OpError` wrapping an ENOENT _is_ still an ENOENT, it's just missed by this implementation. This really was the source of my surprise here.

Does it make more sense to say something more like this?

> os.IsNotExist should only be used to test for errors that are returned by the os package. For errors returned by other packages, use errors.Is.

**Comment by ianlancetaylor** [comment]
Maybe we should simply change "the error" to "an error returned from this package."

**Comment by shabbyrobe** [comment]
> IsNotExist returns a boolean indicating whether an error returned by this package is known to report that a file or directory does not exist. It is satisfied by ErrNotExist as well as some syscall errors.

I think that works, especially if your goal is terseness, but I think it should still mention errors.Is. Can we say something like this after?

> Similar errors returned by other packages should be checked using errors.Is.

**Comment by ianlancetaylor** [comment]
My main concern is that it's not quite enough to refer to `errors.Is`, you also need to refer to `os.ErrNotExist`.  And actually, looking at the docs for `ErrNotExist`, is also says "from this package."  Hmmm.
