### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by sfdcrajak** [golang/go#36151]
![2019-12-15_8-05-28](https://user-images.githubusercontent.com/47048029/70863056-0c08d800-1f12-11ea-90e4-0832ffbbe52d.jpg)

### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.13.5 windows/386
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=386
set GOBIN=C:\Users\rkakayadi\Documents\GO\bin
set GOCACHE=C:\Users\rkakayadi\AppData\Local\go-build
set GOENV=C:\Users\rkakayadi\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=386
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\rkakayadi\Documents\GO
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=sse2
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\rkakayadi\AppData\Local\Temp\go-build130810254=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Download go1.13.5.windows-386.zip from https://golang.org/dl/ and unzip (Verified the SHA256 Checksum of the downloaded file matches with the checksum published for the file at https://golang.org/dl/)

### What did you expect to see?

A successful unzip of the files from the go1.13.5.windows-386.zip archive

### What did you see instead?

Attached screenshot from Windows security saying a trojan malware was detected while unzipping. Stopped the unzipping of files.

**Comment by agnivade** [comment]
Hello @sfdcrajak, this is a common problem with Windows binaries. Please see: https://golang.org/doc/faq#virus.

I will close this issue as there is nothing we can do from our side.
