### ISSUE TITLE
api: audit for Go 1.14 go1.14.txt

### ISSUE THREAD

**Issue by toothrot** [golang/go#36167]
The [Go 1.14 api/next.txt CL change](https://golang.org/cl/211517) introduced the following for Go 1.14:

## New API changes for Go 1.14

[cl 175517:](https://golang.org/cl/175517)
- [x] pkg crypto/tls, const TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 = 52393
- [x] pkg crypto/tls, const TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 uint16
- [x] pkg crypto/tls, const TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 = 52392
- [x] pkg crypto/tls, const TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 uint16
- [x] pkg crypto/tls, func CipherSuiteName(uint16) string
- [x] pkg crypto/tls, func CipherSuites() []*CipherSuite
- [x] pkg crypto/tls, func InsecureCipherSuites() []*CipherSuite

[cl 205057:](https://golang.org/cl/205057)
- [x] pkg crypto/tls, method (*ClientHelloInfo) SupportsCertificate(*Certificate) error

[cl 205062:](https://golang.org/cl/205062)
- [x] pkg crypto/tls, type Certificate struct, SupportedSignatureAlgorithms []SignatureScheme

[cl 205058:](https://golang.org/cl/205058)
- [x] pkg crypto/tls, method (*CertificateRequestInfo) SupportsCertificate(*Certificate) error
- [x] pkg crypto/tls, type CertificateRequestInfo struct, Version uint16

[cl 175517:](https://golang.org/cl/175517)
- [x] pkg crypto/tls, type CipherSuite struct
- [x] pkg crypto/tls, type CipherSuite struct, ID uint16
- [x] pkg crypto/tls, type CipherSuite struct, Insecure bool
- [x] pkg crypto/tls, type CipherSuite struct, Name string
- [x] pkg crypto/tls, type CipherSuite struct, SupportedVersions []uint16

[cl 175137:](https://golang.org/cl/175137)
- [x] pkg debug/dwarf, const AttrAddrBase = 115
- [x] pkg debug/dwarf, const AttrAddrBase Attr
- [x] pkg debug/dwarf, const AttrAlignment = 136
- [x] pkg debug/dwarf, const AttrAlignment Attr
- [x] pkg debug/dwarf, const AttrBinaryScale = 91
- [x] pkg debug/dwarf, const AttrBinaryScale Attr
- [x] pkg debug/dwarf, const AttrCallAllCalls = 122
- [x] pkg debug/dwarf, const AttrCallAllCalls Attr
- [x] pkg debug/dwarf, const AttrCallAllSourceCalls = 123
- [x] pkg debug/dwarf, const AttrCallAllSourceCalls Attr
- [x] pkg debug/dwarf, const AttrCallAllTailCalls = 124
- [x] pkg debug/dwarf, const AttrCallAllTailCalls Attr
- [x] pkg debug/dwarf, const AttrCallDataLocation = 133
- [x] pkg debug/dwarf, const AttrCallDataLocation Attr
- [x] pkg debug/dwarf, const AttrCallDataValue = 134
- [x] pkg debug/dwarf, const AttrCallDataValue Attr
- [x] pkg debug/dwarf, const AttrCallOrigin = 127
- [x] pkg debug/dwarf, const AttrCallOrigin Attr
- [x] pkg debug/dwarf, const AttrCallPC = 129
- [x] pkg debug/dwarf, const AttrCallPC Attr
- [x] pkg debug/dwarf, const AttrCallParameter = 128
- [x] pkg debug/dwarf, const AttrCallParameter Attr
- [x] pkg debug/dwarf, const AttrCallReturnPC = 125
- [x] pkg debug/dwarf, const AttrCallReturnPC Attr
- [x] pkg debug/dwarf, const AttrCallTailCall = 130
- [x] pkg debug/dwarf, const AttrCallTailCall Attr
- [x] pkg debug/dwarf, const AttrCallTarget = 131
- [x] pkg debug/dwarf, const AttrCallTarget Attr
- [x] pkg debug/dwarf, const AttrCallTargetClobbered = 132
- [x] pkg debug/dwarf, const AttrCallTargetClobbered Attr
- [x] pkg debug/dwarf, const AttrCallValue = 126
- [x] pkg debug/dwarf, const AttrCallValue Attr
- [x] pkg debug/dwarf, const AttrConstExpr = 108
- [x] pkg debug/dwarf, const AttrConstExpr Attr
- [x] pkg debug/dwarf, const AttrDataBitOffset = 107
- [x] pkg debug/dwarf, const AttrDataBitOffset Attr
- [x] pkg debug/dwarf, const AttrDecimalScale = 92
- [x] pkg debug/dwarf, const AttrDecimalScale Attr
- [x] pkg debug/dwarf, const AttrDecimalSign = 94
- [x] pkg debug/dwarf, const AttrDecimalSign Attr
- [x] pkg debug/dwarf, const AttrDefaulted = 139
- [x] pkg debug/dwarf, const AttrDefaulted Attr
- [x] pkg debug/dwarf, const AttrDeleted = 138
- [x] pkg debug/dwarf, const AttrDeleted Attr
- [x] pkg debug/dwarf, const AttrDigitCount = 95
- [x] pkg debug/dwarf, const AttrDigitCount Attr
- [x] pkg debug/dwarf, const AttrDwoName = 118
- [x] pkg debug/dwarf, const AttrDwoName Attr
- [x] pkg debug/dwarf, const AttrElemental = 102
- [x] pkg debug/dwarf, const AttrElemental Attr
- [x] pkg debug/dwarf, const AttrEndianity = 101
- [x] pkg debug/dwarf, const AttrEndianity Attr
- [x] pkg debug/dwarf, const AttrEnumClass = 109
- [x] pkg debug/dwarf, const AttrEnumClass Attr
- [x] pkg debug/dwarf, const AttrExplicit = 99
- [x] pkg debug/dwarf, const AttrExplicit Attr
- [x] pkg debug/dwarf, const AttrExportSymbols = 137
- [x] pkg debug/dwarf, const AttrExportSymbols Attr
- [x] pkg debug/dwarf, const AttrLinkageName = 110
- [x] pkg debug/dwarf, const AttrLinkageName Attr
- [x] pkg debug/dwarf, const AttrLoclistsBase = 140
- [x] pkg debug/dwarf, const AttrLoclistsBase Attr
- [x] pkg debug/dwarf, const AttrMacros = 121
- [x] pkg debug/dwarf, const AttrMacros Attr
- [x] pkg debug/dwarf, const AttrMainSubprogram = 106
- [x] pkg debug/dwarf, const AttrMainSubprogram Attr
- [x] pkg debug/dwarf, const AttrMutable = 97
- [x] pkg debug/dwarf, const AttrMutable Attr
- [x] pkg debug/dwarf, const AttrNoreturn = 135
- [x] pkg debug/dwarf, const AttrNoreturn Attr
- [x] pkg debug/dwarf, const AttrObjectPointer = 100
- [x] pkg debug/dwarf, const AttrObjectPointer Attr
- [x] pkg debug/dwarf, const AttrPictureString = 96
- [x] pkg debug/dwarf, const AttrPictureString Attr
- [x] pkg debug/dwarf, const AttrPure = 103
- [x] pkg debug/dwarf, const AttrPure Attr
- [x] pkg debug/dwarf, const AttrRank = 113
- [x] pkg debug/dwarf, const AttrRank Attr
- [x] pkg debug/dwarf, const AttrRecursive = 104
- [x] pkg debug/dwarf, const AttrRecursive Attr
- [x] pkg debug/dwarf, const AttrReference = 119
- [x] pkg debug/dwarf, const AttrReference Attr
- [x] pkg debug/dwarf, const AttrRnglistsBase = 116
- [x] pkg debug/dwarf, const AttrRnglistsBase Attr
- [x] pkg debug/dwarf, const AttrRvalueReference = 120
- [x] pkg debug/dwarf, const AttrRvalueReference Attr
- [x] pkg debug/dwarf, const AttrSignature = 105
- [x] pkg debug/dwarf, const AttrSignature Attr
- [x] pkg debug/dwarf, const AttrSmall = 93
- [x] pkg debug/dwarf, const AttrSmall Attr
- [x] pkg debug/dwarf, const AttrStrOffsetsBase = 114
- [x] pkg debug/dwarf, const AttrStrOffsetsBase Attr
- [x] pkg debug/dwarf, const AttrStringLengthBitSize = 111
- [x] pkg debug/dwarf, const AttrStringLengthBitSize Attr
- [x] pkg debug/dwarf, const AttrStringLengthByteSize = 112
- [x] pkg debug/dwarf, const AttrStringLengthByteSize Attr
- [x] pkg debug/dwarf, const AttrThreadsScaled = 98
- [x] pkg debug/dwarf, const AttrThreadsScaled Attr
- [x] pkg debug/dwarf, const ClassAddrPtr = 15
- [x] pkg debug/dwarf, const ClassAddrPtr Class
- [x] pkg debug/dwarf, const ClassLocList = 16
- [x] pkg debug/dwarf, const ClassLocList Class
- [x] pkg debug/dwarf, const ClassRngList = 17
- [x] pkg debug/dwarf, const ClassRngList Class
- [x] pkg debug/dwarf, const ClassRngListsPtr = 18
- [x] pkg debug/dwarf, const ClassRngListsPtr Class
- [x] pkg debug/dwarf, const ClassStrOffsetsPtr = 19
- [x] pkg debug/dwarf, const ClassStrOffsetsPtr Class
- [x] pkg debug/dwarf, const TagAtomicType = 71
- [x] pkg debug/dwarf, const TagAtomicType Tag
- [x] pkg debug/dwarf, const TagCallSite = 72
- [x] pkg debug/dwarf, const TagCallSite Tag
- [x] pkg debug/dwarf, const TagCallSiteParameter = 73
- [x] pkg debug/dwarf, const TagCallSiteParameter Tag
- [x] pkg debug/dwarf, const TagCoarrayType = 68
- [x] pkg debug/dwarf, const TagCoarrayType Tag
- [x] pkg debug/dwarf, const TagDynamicType = 70
- [x] pkg debug/dwarf, const TagDynamicType Tag
- [x] pkg debug/dwarf, const TagGenericSubrange = 69
- [x] pkg debug/dwarf, const TagGenericSubrange Tag
- [x] pkg debug/dwarf, const TagImmutableType = 75
- [x] pkg debug/dwarf, const TagImmutableType Tag
- [x] pkg debug/dwarf, const TagSkeletonUnit = 74
- [x] pkg debug/dwarf, const TagSkeletonUnit Tag

[cl 175138:](https://golang.org/cl/175138)
- [x] pkg debug/dwarf, method (*Data) AddSection(string, []uint8) error

[cl 192699:](https://golang.org/cl/192699)
- [x] pkg debug/dwarf, method (*LineReader) Files() []*LineFile

[cl 192698:](https://golang.org/cl/192698)
- [x] pkg debug/dwarf, method (*Reader) ByteOrder() binary.ByteOrder

[cl 126624:](https://golang.org/cl/126624)
- [x] pkg encoding/asn1, const TagBMPString = 30
- [x] pkg encoding/asn1, const TagBMPString ideal-int

[cl 200677:](https://golang.org/cl/200677)
- [x] pkg encoding/json, method (*Decoder) InputOffset() int64

[cl 203820:](https://golang.org/cl/203820)
- [x] pkg go/build, type Context struct, WorkingDir string - filed #36168 

[cl 204830:](https://golang.org/cl/204830)
- [x] pkg go/doc, func NewFromFiles(*token.FileSet, []*ast.File, string, ...interface{}) (*Package, error)
- [x] pkg go/doc, type Example struct, Suffix string
- [x] pkg go/doc, type Func struct, Examples []*Example
- [x] pkg go/doc, type Package struct, Examples []*Example
- [x] pkg go/doc, type Type struct, Examples []*Example

[cl 191257:](https://golang.org/cl/191257)
- [x] pkg go/types, method (*Checker) LookupFieldOrMethod(Type, bool, *Package, string) (Object, []int, bool)

[cl 205069:](https://golang.org/cl/205069)
- [x] pkg hash/maphash, func MakeSeed() Seed

[cl 186877:](https://golang.org/cl/186877)
- [x] pkg hash/maphash, method (*Hash) BlockSize() int
- [x] pkg hash/maphash, method (*Hash) Reset()
- [x] pkg hash/maphash, method (*Hash) Seed() Seed
- [x] pkg hash/maphash, method (*Hash) SetSeed(Seed)
- [x] pkg hash/maphash, method (*Hash) Size() int
- [x] pkg hash/maphash, method (*Hash) Sum([]uint8) []uint8
- [x] pkg hash/maphash, method (*Hash) Sum64() uint64
- [x] pkg hash/maphash, method (*Hash) Write([]uint8) (int, error)
- [x] pkg hash/maphash, method (*Hash) WriteByte(uint8) error
- [x] pkg hash/maphash, method (*Hash) WriteString(string) (int, error)
- [x] pkg hash/maphash, type Hash struct
- [x] pkg hash/maphash, type Seed struct

[cl 186877:](https://golang.org/cl/186877)
- [x] pkg log, const Lmsgprefix = 64
- [x] pkg log, const Lmsgprefix ideal-int

[cl 205317:](https://golang.org/cl/205317)
- [x] pkg math, func FMA(float64, float64, float64) float64

[cl 197838:](https://golang.org/cl/197838)
- [x] pkg math/bits, func Rem(uint, uint, uint) uint
- [x] pkg math/bits, func Rem32(uint32, uint32, uint32) uint32
- [x] pkg math/bits, func Rem64(uint64, uint64, uint64) uint64

[cl 152877:](https://golang.org/cl/152877)
- [x] pkg mime/multipart, method (*Reader) NextRawPart() (*Part, error)

[cl 152877:](https://golang.org/cl/152877)
- [x] pkg mime/multipart, method (*Reader) NextRawPart() (*Part, error)

[cl 200760:](https://golang.org/cl/200760)
- [x] pkg net/http, method (Header) Values(string) []string

[cl 61291:](https://golang.org/cl/61291)
- [x] pkg net/http, type Transport struct, DialTLSContext func(context.Context, string, string) (net.Conn, error)

[cl 201557:](https://golang.org/cl/201557)
- [x] pkg net/http/httptest, type Server struct, EnableHTTP2 bool

[cl 200760:](https://golang.org/cl/200760)
- [x] pkg net/textproto, method (MIMEHeader) Values(string) []string

[cl 194563:](https://golang.org/cl/194563)
- [x] pkg strconv, method (*NumError) Unwrap() error

[cl 187739:](https://golang.org/cl/187739)
- [x] pkg syscall (windows-386), const CTRL_CLOSE_EVENT = 2
- [x] pkg syscall (windows-386), const CTRL_CLOSE_EVENT ideal-int
- [x] pkg syscall (windows-386), const CTRL_LOGOFF_EVENT = 5
- [x] pkg syscall (windows-386), const CTRL_LOGOFF_EVENT ideal-int
- [x] pkg syscall (windows-386), const CTRL_SHUTDOWN_EVENT = 6
- [x] pkg syscall (windows-386), const CTRL_SHUTDOWN_EVENT ideal-int
- [x] pkg syscall (windows-amd64), const CTRL_CLOSE_EVENT = 2
- [x] pkg syscall (windows-amd64), const CTRL_CLOSE_EVENT ideal-int
- [x] pkg syscall (windows-amd64), const CTRL_LOGOFF_EVENT = 5
- [x] pkg syscall (windows-amd64), const CTRL_LOGOFF_EVENT ideal-int
- [x] pkg syscall (windows-amd64), const CTRL_SHUTDOWN_EVENT = 6
- [x] pkg syscall (windows-amd64), const CTRL_SHUTDOWN_EVENT ideal-int

[cl 201359:](https://golang.org/cl/201359)
- [x] pkg testing, method (*B) Cleanup(func())
- [x] pkg testing, method (*T) Cleanup(func())
- [x] pkg testing, type TB interface, Cleanup(func())

[cl 204658:](https://golang.org/cl/204658)
- [x] pkg unicode, const Version = "12.0.0"
- [x] pkg unicode, var Elymaic *RangeTable
- [x] pkg unicode, var Nandinagari *RangeTable
- [x] pkg unicode, var Nyiakeng_Puachue_Hmong *RangeTable
- [x] pkg unicode, var Wancho *RangeTable

**Comment by ianlancetaylor** [comment]
Thanks for pulling the list together.  I added a checkbox for each item so people can quickly mark off additions that are OK.

**Comment by rsc** [comment]
I went through the list checking that the additions corresponded to accepted proposals. A few did not and are fine anyway (e.g. the usual Unicode upgrade, the additional Windows constants, ...). I only found one that seems worth revisiting and filed #36168 

Once #36168 is closed I think this can be closed too.

**Comment by alexbrainman** [comment]
All windows syscall changes LGTM.

Alex

**Comment by toothrot** [comment]
#36168 resolved the issue with `pkg go/build, type Context struct, WorkingDir string` by renaming to `Dir`. 

All other changes have been checked-off. Please comment if I am mistaken.

**Comment by Rican7** [comment]
Not sure if this matters, but I figured I'd mention it.

I just went through this list and noticed a duplicate:

> [cl 152877:](https://golang.org/cl/152877)
> 
> * [x]  pkg mime/multipart, method (*Reader) NextRawPart() (*Part, error)
> 
> [cl 152877:](https://golang.org/cl/152877)
> 
> * [x]  pkg mime/multipart, method (*Reader) NextRawPart() (*Part, error)
