### ISSUE TITLE
go/build: Context.WorkingDir should just be Dir

### ISSUE THREAD

**Issue by rsc** [golang/go#36168]
CL 203820 introduced Context.WorkingDir but I don't see the API review anywhere.
It seems like it should just be "Dir".
We don't use the terminology "working dir" anywhere.

**Comment by rsc** [comment]
See also #36167.

**Comment by bcmills** [comment]
I chose `WorkingDir` because `Dir` seemed a bit ambiguous, particularly given the `ImportDir` method. That said, I don't have a strong preference either way.

(@griesemer and @jayconrod reviewed the original CL.)

I'll send some changes to switch it to Dir.

**Comment by bcmills** [comment]
(FWIW, I think I had picked up the name `WorkingDir` from `x/tools/internal/imports`, introduced in [CL 158437](https://golang.org/cl/158437).)
