### ISSUE TITLE
x/build/maintner, x/build/maintner/maintnerd/maintapi: (*netMutSource).syncSeg occasionally fails with "Access is denied." on Windows, as caught by TestGetRef failing on windows-amd64-longtest

### ISSUE THREAD

**Issue by bcmills** [golang/go#36163]
It appears that `maintner` is trying to install log segments using atomic renames:
https://github.com/golang/build/blob/0d536a3af5fb211db2c73a4499672e9c77ed06cb/maintner/netsource.go#L580-L582

Note that Windows does not actually ensure the success of atomic calls to `os.Rename` (see also #34681).

For `cmd/go` we have an internal workaround in [`cmd/go/internal/robustio`](https://tip.golang.org/pkg/cmd/go/internal/robustio), which retries errors suspected to be spurious, although at this point we're mostly switching over to explicit file-locking rather than renaming for synchronization (see also #33974).

----

[2019-12-13T18:18:58-fba2c51/windows-amd64-longtest](https://build.golang.org/log/d8eb1aae3620b96b5300e71cc70e61478a756341)

```
--- FAIL: TestGetRef (9.50s)
    api_test.go:191: getting corpus: syncing segment 27: rename C:\Users\gopher\.cache\golang-maintner\tempseg028062994 C:\Users\gopher\.cache\golang-maintner\0027.5c4a6891e9788c963979597b118bc64d1571078489b05b69be0f53be.mutlog: Access is denied.
```

CC @dmitshur @toothrot @cagedmantis @bradfitz

**Comment by bcmills** [comment]
https://build.golang.org/log/0420d03897485cb745280248cb0e951b8a866917

```
--- FAIL: TestGetRef (11.13s)
    api_test.go:191: getting corpus: syncing segment 46: rename C:\Users\gopher\.cache\golang-maintner\tempseg000044895 C:\Users\gopher\.cache\golang-maintner\0046.bb5084c76340045b19e6d06755ef9be321888b1344474d24be5fe494.mutlog: Access is denied.
```

**Comment by toothrot** [comment]
Retrying, as robustio does, seems like a good solution.

**Comment by bcmills** [comment]
If you happen to decide to use explicit file-locking instead, see #33974.

**Comment by bcmills** [comment]
I think this is basically as fixed as it's going to get, so closing.

(The implementation could stand to be refactored to use a more robust, more portable approach, but I don't think that will ever be a priority.)
