### ISSUE TITLE
net/http: apparent TestServerAllowsBlockingRemoteAddr flakes due to hard-coded timeouts

### ISSUE THREAD

**Issue by bcmills** [golang/go#36179]
```
#!watchflakes
post <- pkg == "net/http" && (test == "TestServerAllowsBlockingRemoteAddr" || `^\s+TestServerAllowsBlockingRemoteAddr \(\d+m`) && (`panic: test timed out` || `context deadline exceeded`)
```

[2019-12-16T20:38:31-f7f9866/plan9-386-0intro](https://build.golang.org/log/da216256f5c21dc78e15ecd8761dd936ec909c42)
[2019-06-12T14:58:18-65f53da/plan9-amd64-9front](https://build.golang.org/log/66df0063df47852e2051f77065a693586df3d254)

```
--- FAIL: TestServerAllowsBlockingRemoteAddr (1.08s)
    serve_test.go:1300: Request 1: Get "http://127.0.0.1:55517": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
    serve_test.go:1349: response 1 addr = ""; want "RA:21.21.21.21:21"
http.test 1018696: warning: process exceeds 100 file descriptors
FAIL
FAIL	net/http	114.189s
```

As far as I can tell, the root cause is the hard-coded `time.Second` here:
https://github.com/golang/go/blob/931fe39400006e6c272d13f2a4d46de2a6736761/src/net/http/serve_test.go#L1326-L1330

It's not obvious to me why a timeout is needed there at all. If the test deadlocks, we presumably want a goroutine dump anyway.

CC @bradfitz @0intro @fhs

**Comment by bcmills** [comment]
That's the regression test for #12943.

**Comment by HowJMay** [comment]
Is this one still one still open

**Comment by bcmills** [comment]
The failure log linked in https://github.com/golang/go/issues/57995#issuecomment-1405051874 matches this issue; I'm not sure why `watchflakes` isn't posting it here.

**Comment by bcmills** [comment]
Interesting! Those `dragonfly` failures look like actual deadlocks, not just spurious timeouts.

**Comment by bcmills** [comment]
Nope, it is still the same spurious timeout:
https://cs.opensource.google/go/go/+/master:src/net/http/serve_test.go;l=1362;drc=133e0bca0be23980604ee98589ddcacdb1262afd

It's just manifesting as a deadlock due to some synchronous cleanup code.

**Comment by bcmills** [comment]
Oops, missed another arbitrary timeout.

**Comment by bcmills** [comment]
Hopefully completely fixed this time, by [CL 476035](https://go.dev/cl/476035).
