### ISSUE TITLE
how would you fix invalid pseudo-version: revision is longer than canonical

### ISSUE THREAD

**Issue by dfang** [golang/go#36174]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mj/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mj/.gvm/pkgsets/go1.12.9/global"
GOPROXY=""
GORACE=""
GOROOT="/Users/mj/.gvm/gos/go1.12.9"
GOTMPDIR=""
GOTOOLDIR="/Users/mj/.gvm/gos/go1.12.9/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/mj/src/JD/webhookd/webhookd/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xb/dsd0_2b92x7bsl92xlzj6fbm0000gn/T/go-build849427239=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

get this [sample code](https://github.com/whosonfirst/go-webhookd#setting-up-a-webhookd-server-with-a-handy-config-file) to work

```
package main

import (
	"github.com/whosonfirst/go-webhookd/config"
	"github.com/whosonfirst/go-webhookd/daemon"
)

func main() {
	wh_config, _ := config.NewConfigFromFile("config.json")
	wh_daemon, _ := daemon.NewWebhookDaemonFromConfig(wh_config)
	wh_daemon.Start()
}
```

```
go mod init webhookd
go run main.go
go: github.com/whosonfirst/go-webhookd@v0.1.2 requires
	github.com/aaronland/go-chicken@v0.1.1 requires
	github.com/facebookgo/grace@v0.0.0-20180705000000-75cf19382434e82df4dd84953f566b8ad23d6e9e: invalid pseudo-version: revision is longer than canonical (75cf19382434)
````

if i can try go mod edit -replace ?

github.com/facebookgo/grace@v0.0.0-20180705000000-75cf19382434e82df4dd84953f566b8ad23d6e9e should replace to which version

github.com/facebookgo/grace@v0.0.0-20180705000000-75cf19382434 is not right

and there is no commit on [20180705](https://github.com/facebookarchive/grace/commits/master)

### What did you expect to see?

go run main.go works

### What did you see instead?

invalid pseudo-version: revision is longer than canonical

what would you would do to fix this before the author fix the go.mod ?

**Comment by dfang** [comment]
i create a temp dir, run go mod init test, then run go mod download -json gets the right version.

```
> go mod download -json github.com/facebookarchive/grace@75cf19382434
go: finding github.com/facebookarchive/grace 75cf19382434
{
	"Path": "github.com/facebookarchive/grace",
	"Version": "v0.0.0-20180706040059-75cf19382434",
	"Info": "/Users/mj/go/pkg/mod/cache/download/github.com/facebookarchive/grace/@v/v0.0.0-20180706040059-75cf19382434.info",
	"GoMod": "/Users/mj/go/pkg/mod/cache/download/github.com/facebookarchive/grace/@v/v0.0.0-20180706040059-75cf19382434.mod",
	"Zip": "/Users/mj/go/pkg/mod/cache/download/github.com/facebookarchive/grace/@v/v0.0.0-20180706040059-75cf19382434.zip",
	"Dir": "/Users/mj/go/pkg/mod/github.com/facebookarchive/grace@v0.0.0-20180706040059-75cf19382434",
	"Sum": "h1:AFIATPhFj7mrISc4z9zEpfm4a8UfwsCWzJ+Je5jA5Rs=",
	"GoModSum": "h1:PY9iiFMrFjTzegsqfKCcb+Ekk5/j0ch0sMdBwlT6atI="
}

```

and  then run `
go mod edit --replace github.com/facebookgo/grace@v0.0.0-20180705000000-75cf19382434=github.com/facebookarchive/grace@v0.0.0-20180706040059-75cf19382434
`

it still didn't work, 

```
go mod tidy or go run main.go
go: github.com/whosonfirst/go-webhookd@v0.1.2 requires
	github.com/aaronland/go-chicken@v0.1.1 requires
	github.com/facebookgo/grace@v0.0.0-20180705000000-75cf19382434e82df4dd84953f566b8ad23d6e9e: invalid pseudo-version: revision is longer than canonical (75cf19382434)
```

i guess i should fork github.com/aaronland/go-chicken and change go.mod there ?

but it's complicated, especially when a project have a lot of dependencies ?

**Comment by bcmills** [comment]
Upgrade your dependency on `github.com/whosonfirst/go-webhookd` to `v0.1.3`, which changes the dependency on `github.com/aaronland/go-chicken` from `v0.1.1` to `v0.2.0`, which removes the dependency on `github.com/facebookgo/grace` entirely.

**Comment by bcmills** [comment]
(In general, though, you can apply the mitigations described in https://golang.org/doc/go1.13#version-validation if the maintainer of your dependency hasn't yet committed the fix.)
