### ISSUE TITLE
archive/tar: when uncompress the tar file, found io.Reader/io.Writer some problem but don't know reason

### ISSUE THREAD

**Issue by conero** [golang/go#36176]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\~\go-build
set GOENV=C:\Users\~\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=*.corp.example.com
set GONOSUMDB=*.corp.example.com
set GOOS=windows
set GOPATH=C:\~\go
set GOPRIVATE=*.corp.example.com
set GOPROXY=https://goproxy.io,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\~\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\conero\~\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\~\go-build654453722=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

```go
func TestCase(){
	// ……
	//un-compress
	tr := tar.NewReader(fh)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break // End of archive
		}
		if err != nil {
			log.Fatal(err)
		}

		vpath := targetDir + hdr.Name
		vpath = fs.StdPathName(vpath)

		if hdr.Name == jenkins.RunDelLogFilename {
			cttBys, _ := ioutil.ReadAll(tr)
			cttStr := string(cttBys)

			fmt.Println(cttStr)
			//		/packgo-test-x2
			ioutil.WriteFile("./jc-test.log", cttBys, 0777)
			//	./jc-test.log:
			//		/packgo-test-cp
			//		/packgo-test
			//		/packgo-test-x2

			// problem:
			//       `fmt.Println(cttStr)` and `./jc-test.log ` had diffrent content. But Why?
			return
		}
		// ……
	}
	// ……
}
```

### What did you expect to see?
Content of `fmt.Println(cttStr)`  and `./jc-test.log ` is same.

### What did you see instead?
Content of `fmt.Println(cttStr)`  and `./jc-test.log ` is deffrent. So I can handler the real content.

**Comment by dmitshur** [comment]
In your snippet, there is a line that reads all bytes from the tar reader:

```Go
cttBys, _ := ioutil.ReadAll(tr)
```

The error value isn't check. Can you try adding something that checks if the error is non-nil and reports it?

**Comment by networkimprov** [comment]
ioutil.WriteFile() also returns an error which should be checked.

**Comment by conero** [comment]
I tried to add the `Error-check`, there was not error, and the result did not change.
```go
if hdr.Name == jenkins.RunDelLogFilename {
    cttBys, er := ioutil.ReadAll(tr)
    if er != nil{
        fmt.Printf(" tar content read is fail, Error: %v\r\n", er.Error())
        return
    }
    //~~
    er = ioutil.WriteFile("./jc-test.log", cttBys, 0777)
    if er != nil{
        fmt.Printf(" ./jc-test.log, Error: %v\r\n", er.Error())
        return
    }
}
```

**Comment by dmitshur** [comment]
```
// problem:
//       `fmt.Println(cttStr)` and `./jc-test.log ` had diffrent content. But Why?
```

What is the difference in the content exactly?

Are you able to make a smaller self-contained sample that we can reproduce this problem with? That will help with understanding whether the problem is a bug in `archive/tar` or elsewhere.

**Comment by conero** [comment]
@dmitshur 
```
What is the difference in the content exactly?
```
`fmt.Println(cttStr)`:  The content is `/packgo-test-x2`. And `./jc-test.log` that is what I want like: 
```
/packgo-test-cp
/packgo-test
/packgo-test-x2
```
