### ISSUE TITLE
gopls panic: runtime error: slice bounds out of range [42:40]

### ISSUE THREAD

**Issue by try876** [golang/go#36193]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, but i don't know in which case this will happen

gopls version
<pre>
golang.org/x/tools/cmd/gopls master-cmd.gopls
    golang.org/x/tools@v0.0.0-20191217221516-62a9628863c6 h1:k+WWDn7kCTlsngp5FyNxPMbHrcm0Ko5SPa8R7BR
wzwE=
</pre>
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\GOPATH;f:\go_f;
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=f:\mygo2\weatherbee\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\
Temp\go-build996460082=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

write code in vscode

go.mod file content:
<pre>
module weatherbee

go 1.13

require (
	github.com/astaxie/beego v1.12.0
	github.com/go-sql-driver/mysql v1.4.1
	github.com/go-xorm/xorm v0.7.9
	github.com/gonum/blas v0.0.0-20181208220705-f22b278b28ac // indirect
	github.com/gonum/floats v0.0.0-20181209220543-c233463c7e82 // indirect
	github.com/gonum/integrate v0.0.0-20181209220457-a422b5c0fdf2 // indirect
	github.com/gonum/internal v0.0.0-20181124074243-f884aa714029 // indirect
	github.com/gonum/lapack v0.0.0-20181123203213-e4cdc5a0bff9 // indirect
	github.com/gonum/matrix v0.0.0-20181209220409-c518dec07be9 // indirect
	github.com/gonum/stat v0.0.0-20181125101827-41a0da705a5b
	github.com/gosexy/redis v0.0.0-20150603022529-19c427d2a3bc
	github.com/kr/pretty v0.1.0 // indirect
	github.com/lib/pq v1.2.0
	github.com/shiena/ansicolor v0.0.0-20151119151921-a422bbe96644 // indirect
	github.com/shopspring/decimal v0.0.0-20191009025716-f1972eb1d1f5
	github.com/smartystreets/goconvey v1.6.4
	github.com/xiam/resp v0.0.0-20150723032330-04b037c5d609 // indirect
	gonum.org/v1/netlib v0.0.0-20191031114514-eccb95939662 // indirect
	gonum.org/v1/plot v0.0.0-20191107103940-ca91d9d40d0a
	gopkg.in/mgo.v2 v2.0.0-20190816093944-a6b53ec6cb22
	menteslibres.net/gosexy/to v0.0.0-00010101000000-000000000000 // indirect
)

replace menteslibres.net/gosexy/to => d:\GOPATH\src\menteslibres.net\gosexy\to\
</pre>

### What did you see instead?
in gopls log:

panic: runtime error: slice bounds out of range [42:40]
goroutine 25273 [running]:
golang.org/x/tools/internal/imports.(*ModuleResolver).scanDirForPackage(0xc00012e2a0, 0xc00f602ed0, 0x29, 0x5, 0xc010d50ea0, 0x28, 0x0, 0x0, 0x0,

D:/GOPATH/pkg/mod/golang.org/x/tools@v0.0.0-20191216230829-846828e8ce7c/internal/imports/mode.go:479 +0x94f
![1218132146](https://user-images.githubusercontent.com/12080607/71058020-69628a80-2199-11ea-9599-5df64492b36a.png)

**Comment by stamblerre** [comment]
Thank you for reporting this issue! /cc @heschik for goimports-related work

In an unrelated note, if you are running `gopls` from master, it is recommended to install it in module mode. You can do this by running: `GO111MODULE=on go get golang.org/x/tools/gopls@master golang.org/x/tools@master`.

**Comment by heschik** [comment]
I am really not sure how this can happen. Maybe something strange with junction points or symlinks?

Can you add an explicit panic in that code that shows dir and root.Path?

**Comment by try876** [comment]
Thanks. Maybe I ran the wrong version. I'll try the latest branch.

**Comment by JAicewizard** [comment]
Is this still reproducible with the latest version in module mode?

**Comment by try876** [comment]
I'm using v0.2.2 few days, and don't have that problem again.

**Comment by stamblerre** [comment]
Thank you for the confirmation! I'll close this issue then.

**Comment by try876** [comment]
I reproduced this problem in  v0.3.2.  
I think the problem is that I wrote the replace instruction wrong and added an extra backslash. 
And if I remove the last backslash, it will be ok.

`replace menteslibres.net/gosexy/to => d:\GOPATH\src\menteslibres.net\gosexy\to\
`


[Info  - 下午10:30:14] 2020/02/12 22:30:14 Build info
----------
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@(devel)
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=
    golang.org/x/mod@v0.1.1-0.20191105210325-c90efee705ee h1:WG0RUwxtNT4qqaXX3DPA8zHFNm/D9xaBpxzHt1WcA/E=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20191017151554-a3bc800455d5 => ../
    golang.org/x/xerrors@v0.0.0-20191011141410-1b5146add898 h1:/atklqdjdhuosWIl6AIbOeHJjicWYPqR9bpxqxYG2pA=
    honnef.co/go/tools@v0.0.1-2019.2.3 h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=

Go info
-------
go version go1.13.4 windows/amd64

set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\GOPATH;f:\go_f;
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=f:\mygo2\weatherbee\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build354943922=/tmp/go-build -gno-record-gcc-switches

[Info  - 下午10:30:17] 2020/02/12 22:30:17 go/packages.Load
	snapshot = 0
	query = [./... builtin]
	packages = 12
[Info  - 下午10:30:49] 2020/02/12 22:30:49 background imports cache refresh starting
panic: runtime error: slice bounds out of range [42:40]

goroutine 8399 [running]:
golang.org/x/tools/internal/imports.(*ModuleResolver).scanDirForPackage(0xc00d274000, 0xc00c87e870, 0x29, 0x5, 0xc01120e1b0, 0x28, 0x0, 0x0, 0x0, 0x0, ...)
	d:/_MyPro/golang_tools/internal/imports/mod.go:567 +0xbbf
golang.org/x/tools/internal/imports.(*ModuleResolver).scan.func3(0xc00c87e870, 0x29, 0x5, 0xc01120e1b0, 0x28)
	d:/_MyPro/golang_tools/internal/imports/mod.go:446 +0x8f
golang.org/x/tools/internal/gopathwalk.(*walker).walk(0xc010fb9130, 0xc01120e180, 0x2f, 0x0, 0xc01120e180, 0x2f)
	d:/_MyPro/golang_tools/internal/gopathwalk/walk.go:198 +0xfa
golang.org/x/tools/internal/fastwalk.(*walker).onDirEnt(0xc010fbb080, 0xc00c87e870, 0x29, 0xc01102f2a0, 0x5, 0xc000000000, 0x0, 0x0)
	d:/_MyPro/golang_tools/internal/fastwalk/fastwalk.go:168 +0xc2
golang.org/x/tools/internal/fastwalk.readDir(0xc00c87e870, 0x29, 0xc002ac7e50, 0x0, 0x0)
	d:/_MyPro/golang_tools/internal/fastwalk/fastwalk_portable.go:28 +0x188
golang.org/x/tools/internal/fastwalk.(*walker).walk(0xc010fbb080, 0xc00c87e870, 0x29, 0x1, 0x1, 0x0)
	d:/_MyPro/golang_tools/internal/fastwalk/fastwalk.go:195 +0x71
golang.org/x/tools/internal/fastwalk.(*walker).doWork(0xc010fbb080, 0xc01102f220)
	d:/_MyPro/golang_tools/internal/fastwalk/fastwalk.go:134 +0x17c
created by golang.org/x/tools/internal/fastwalk.Walk
	d:/_MyPro/golang_tools/internal/fastwalk/fastwalk.go:81 +0x24f
[Info  - 下午10:30:51] Connection to server got closed. Server will restart.



![image](https://user-images.githubusercontent.com/12080607/75127505-671d2f00-56fa-11ea-9ea1-fae99b4af891.png)

![image](https://user-images.githubusercontent.com/12080607/75127681-6afd8100-56fb-11ea-99c4-299c1e311fbf.png)

**Comment by stamblerre** [comment]
Thanks for the report! Reopening - @heschik, can you take a look?

**Comment by heschik** [comment]
@bcmills @jayconrod: I wonder if this could be considered a `go` command bug -- replace paths are not `Clean`ed when returned by `go list -m`.

Easy fix regardless. Thanks for the debugging.

**Comment by jayconrod** [comment]
Opened #37427 for `cmd/go`.
