### ISSUE TITLE
reflect: StructOf allows creation of invalid types

### ISSUE THREAD

**Issue by dsnet** [golang/go#36190]
At tip, the following are permitted:
```go
reflect.StructOf([]reflect.StructField{{
	Name:    "height",
	PkgPath: "path/to/bar",
	Type:    reflect.TypeOf(float64(0)),
}, {
	Name:    "age",
	PkgPath: "path/to/foo",
	Type:    reflect.TypeOf(int(0)),
}})
```
Here, the `height` and `age` fields have different `PkgPath`. To my knowledge, this is not possible for any real normally declared type. I expect this to panic.

```go
reflect.StructOf([]reflect.StructField{{
	Name:    "height",
	PkgPath: `!"#$%&'()*,:;<=>?[\]^{|}`,
	Type:    reflect.TypeOf(float64(0)),
}})
```
Here, the `PkgPath` permits characters that [the Go specification](https://golang.org/ref/spec#ImportPath) suggests not be used. Should we panic?

**Comment by dmitshur** [comment]
@dsnet Do you know if this behavior is new to 1.14, or did it exist in 1.13, 1.12 as well?

**Comment by dsnet** [comment]
This functionality was added in https://go-review.googlesource.com/c/go/+/85661, so it is specific to Go1.14.

**Comment by dsnet** [comment]
\cc @crawshaw
