### ISSUE TITLE
filepath: filepath.Walk readDirName will cause large memory leak

### ISSUE THREAD

**Issue by wcc526** [golang/go#36197]
[https://github.com/golang/go/blob/master/src/path/filepath/path.go#L363](https://github.com/golang/go/blob/master/src/path/filepath/path.go#L363)

```
  // walk recursively descends path, calling walkFn.
  func walk(path string, info os.FileInfo, walkFn WalkFunc) error {
	if !info.IsDir() {
		return walkFn(path, info, nil)
	}
	names, err := readDirNames(path)
	err1 := walkFn(path, info, err)
	// If err != nil, walk can't walk into this directory.
	// err1 != nil means walkFn want walk to skip this directory or stop walking.
	// Therefore, if one of err and err1 isn't nil, walk will return.
	if err != nil || err1 != nil {
		// The caller's behavior is controlled by the return value, which is decided
		// by walkFn. walkFn may ignore err and return nil.
		// If walkFn returns SkipDir, it will be handled by the caller.
		// So walk should return whatever walkFn returns.
		return err1
	}
```

`
	names, err := readDirNames(path)
`
the readDirNames will lead large memory if directory has large number of files

which conflict skipDir purpose.

**Comment by wcc526** [comment]
```
package main

import (
	"context"
	"path/filepath"
	"time"

	"os"
	"strings"

	log "github.com/sirupsen/logrus"

	"sort"
)

var lstat = os.Lstat // for testing
func walk(path string, info os.FileInfo, walkFn filepath.WalkFunc) error {
	if !info.IsDir() {
		return walkFn(path, info, nil)
	}
	err1 := walkFn(path, info, nil)
	if err1 != nil {
		return err1
	}
	names, err := readDirNames(path)
	log.Info("names",names)
	if err != nil {
		return err
	}
	for _, name := range names {
		filename := filepath.Join(path, name)
		fileInfo, err := lstat(filename)
		if err != nil {
			if err := walkFn(filename, fileInfo, err); err != nil && err != filepath.SkipDir {
				return err
			}
		} else {
			err = walk(filename, fileInfo, walkFn)
			if err != nil {
				if !fileInfo.IsDir() || err != filepath.SkipDir {
					return err
				}
			}
		}
	}
	return nil
}
func CustomWalk(root string, walkFn filepath.WalkFunc) error {
	info, err := os.Lstat(root)
	if err != nil {
		err = walkFn(root, nil, err)
	} else {
		err = walk(root, info, walkFn)
	}
	if err == filepath.SkipDir {
		return nil
	}
	return err
}
func readDirNames(dirname string) ([]string, error) {
	f, err := os.Open(dirname)
	if err != nil {
		return nil, err
	}
	names, err := f.Readdirnames(-1)
	f.Close()
	if err != nil {
		return nil, err
	}
	sort.Strings(names)
	return names, nil
}

func walkLarge(rootpath string) {
	ctx, cancel := context.WithTimeout(context.Background(), 7200*time.Second)
	defer cancel()
	err := CustomWalk(rootpath, func(path string, info os.FileInfo, err error) error {
		time.Sleep(1 * time.Second)
		log.Info(path)
		if err != nil {
			return nil
		}
		select {
		case <-ctx.Done():
			log.Warn("Timeout", rootpath)
			return ctx.Err()
		default:
		}

		rel, err := filepath.Rel(rootpath, path)
		if err != nil {
			return err
		}
		if uint(len(strings.Split(rel, "/"))) > 4 {
			return filepath.SkipDir
		}

		if info.IsDir() {
			if info.Name() == ".git" {
				return filepath.SkipDir
			}
			f, err := os.Open(path)
			defer f.Close()
			if err != nil {
				return filepath.SkipDir
			}
			files, err := f.Readdir(1000)
			if err != nil {
				return filepath.SkipDir
			}
			if len(files) > 999 {
				log.Warn("Skip dir ", path)
				return filepath.SkipDir
			}

		} else {
			if !info.Mode().IsRegular() {
				return nil
			}
		}
		return nil
	})
	if err != nil {
		log.Errorf("walk error [%v]\n", err)
	}
}

func main() {
	walkLarge("/")
}

```

**Comment by wcc526** [comment]
```
        err1 := walkFn(path, info, nil)
	if err1 != nil {
		return err1
	}
	names, err := readDirNames(path)
	log.Info("names",names)
	if err != nil {
		return err
	}
```

walkFn should before readDirNames

**Comment by dmitshur** [comment]
Can you please include information about what version of Go you tested with (`go version`), whether it's an issue with the latest Go 1.13.5 version, and your environment (`go env`)?

That will help with reproducing this and being able to make progress. Thanks.

**Comment by wcc526** [comment]
go version is 1.13.5

[root@el6 ~]# go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/local/:/builds/lucci/lucci-agent/:/builds/lucci/"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build288278525=/tmp/go-build"

I have pull request #36198 Please review and merge it!

When the directory has 8151134 files, it will cause 820MB meomory leak.

the root cause is "names, err := readDirNames(path)" which read the large files fo directory.

thank you for your attention to this matter @dmitshur

**Comment by agnivade** [comment]
There is already a PR for this: https://go-review.googlesource.com/c/go/+/211802.

@wcc526 - I was not aware of this issue. Could you please link this issue in your PR ? In the PR message, just add a new line "Fixes #3697"

**Comment by anmathew** [comment]
does not seem [these](https://go-review.googlesource.com/changes/go~211802/revisions/7/files/src%2Fpath%2Ffilepath%2Fpath.go/download) changes help much. walking a folder with 21k files still hogs about 82M RES size - after the walk.

**Comment by wcc526** [comment]
> does not seem [these](https://go-review.googlesource.com/changes/go~211802/revisions/7/files/src%2Fpath%2Ffilepath%2Fpath.go/download) changes help much. walking a folder with 21k files still hogs about 82M RES size - after the walk.

```
                         files, err := f.Readdir(1000)
			if err != nil {
				return filepath.SkipDir
			}
			if len(files) > 999 {
				log.Warn("Skip dir ", path)
				return filepath.SkipDir
			}
```

You should add filepath.SkipDir to skip this large files.

these changes help to user to right control the SkipDir.

Before change even if user skip large files, walk still `readDirNames(path)` whick hogs large RES size

**Comment by dajohi** [comment]
Is this just waiting on a regress test?

**Comment by seankhliao** [comment]
The API guarantees made by `filepath.Walk` mean this is unlikely to change

> The files are walked in lexical order, which makes the output deterministic but requires Walk to read an entire directory into memory before proceeding to walk that directory.

The CL has been abandoned, with the recommendation that if you need a more performant API with a different tradeoff, you could copy and modify the `Walk/WalkDir` code to suit your needs.
