### ISSUE TITLE
net/mail: ParseAddress cannot parse email address with name contains chinese character

### ISSUE THREAD

**Issue by m3ng9i** [golang/go#36200]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/username/.cache/go-build"
GOENV="/home/username/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/username/dev/go-packages/"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/username/dev/go/go1.13.5"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/username/dev/go/go1.13.5/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build697152646=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```go
package main

import (
    "fmt"
    "net/mail"
)

func main() {

    // 测试<example@example.com>
    addr1 := "=?GB2312?B?suLK1A==?= <example@example.com>"
    addr2 := "=?GB18030?B?suLK1A==?= <example@example.com>"
    addr3 := "=?GBK?B?suLK1A==?= <example@example.com>"

    var err error

    _, err = mail.ParseAddress(addr1)
    fmt.Println(err) // mail: missing word in phrase: charset not supported: "gb2312"

    _, err = mail.ParseAddress(addr2)
    fmt.Println(err) // mail: missing word in phrase: charset not supported: "gb18030"

    _, err = mail.ParseAddress(addr3)
    fmt.Println(err) // mail: missing word in phrase: charset not supported: "gbk"
}
```

### What did you expect to see?

Chinese name should be parsed correctly.

### What did you see instead?

```
mail: missing word in phrase: charset not supported: "gb2312"
```

**Comment by mvdan** [comment]
Why not use utf-8? See https://golang.org/pkg/mime/#WordDecoder:

> utf-8, iso-8859-1 and us-ascii charsets are handled by default.

I don't think we want to be implementing all possible charsets out there in the standard library. If you really need to support arbitrary charsets, you should probably supply your own word decoder via https://golang.org/pkg/net/mail/#AddressParser.

**Comment by m3ng9i** [comment]
> Why not use utf-8? See https://golang.org/pkg/mime/#WordDecoder:

Because the email is from the sender, I cannot control the charset they use.

> I don't think we want to be implementing all possible charsets out there in the standard library. If you really need to support arbitrary charsets, you should probably supply your own word decoder via https://golang.org/pkg/net/mail/#AddressParser.

Thanks for the response, I'll try to make my own word decoder.

**Comment by mvdan** [comment]
Great. I'm closing this for now. If you want to open an issue for the mime package to support many more encodings, you can do that too, but we'd probably need a good argument to add more code to the standard library.
