### ISSUE TITLE
cmd/go: go mod: replace doesn't effect in require packages

### ISSUE THREAD

**Issue by zhanw15** [golang/go#36205]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/root/go-go1.13.5"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/go-go1.13.5/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/gomod/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build037664404=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
In project A's go.mod, I require project B, when I use `go mod download` in project A, I will get error because of project B's go.mod's replace not effect.

<strong> A's go.mod </strong>
```
module github.com/zhanw15/xxxx
  
go 1.13

require (
        k8s.io/kubernetes v1.16.2
)
```
<strong> B's go.mod </strong>
```
module k8s.io/kubernetes

go 1.13

require (
	k8s.io/api v0.0.0
)

replace (
	k8s.io/api => ./staging/src/k8s.io/api
)
```

<strong> error is: </strong>
```
go: k8s.io/kubernetes@v1.16.2 requires
	k8s.io/api@v0.0.0: reading https://goproxy.cn/k8s.io/api/@v/v0.0.0.mod: 404 Not Found
```

### What did you expect to see?
replace should be effort in require packages.

**Comment by dmitshur** [comment]
Thanks for reporting.

I believe this is working as intended. This is documented at https://golang.org/cmd/go/#hdr-The_go_mod_file:

> Exclude and replace apply only in the main module's go.mod and are ignored in dependencies. See https://research.swtch.com/vgo-mvs for details.
