### ISSUE TITLE
Proposal: Revive discussion on https://github.com/golang/go/issues/5901

### ISSUE THREAD

**Issue by harrisonhjones** [golang/go#36206]
I was recommended on the gopher slack to open a proposal for this.

I'd like to reopen discussion of this issue https://github.com/golang/go/issues/5901 that @rsc opened July 17, 2013 titled `encoding/json: allow override type marshaling`. I have a use-case for being able to override the marshalers `encoding/json` uses. Some other 3p JSON encoders have something similar to what Russ proposed but none, that I can find, work as well, in theory, to what he proposed.

I've updated the comment thread on the original issue so we can continue the discussion over there, or over here. As mentioned: if we can land on a design people are happy with I'm happy to put in the work to write the code & tests.

While it would be backwards compatible we could also consider putting the new code in a different package. Perhaps `golang.org/x/encoding/json`? like `golang.org/x/image/draw` did? I'm flexible.

**Comment by dsnet** [comment]
Thanks for posting this. I'm going to close this to keep discussion on #5901.
