### ISSUE TITLE
x/sys/unix: Add wrapper for readv/writev

### ISSUE THREAD

**Issue by Merovius** [golang/go#36201]
I'd like to propose exposing `readv`/`writev` (and maybe `preadv`/`pwritev` and maybeer `preadv2`/`pwritev2`) in x/sys/unix, as `{Read,Write}v(fd int, iov [][]byte) (int, error)`.

My usecase is writing to a file in `O_APPEND` mode, which offers atomicity-guarantees per write. Issuing multiple writes loses those guarantees, so I have to resort to a) allocating a temporary buffer and concatenating the individual `[]byte`s, or b) use `unix.Syscall`. The latter is fine, but a wrapper would allow to avoid `unsafe`.

I don't personally care about the `p…` and `…v2` variants, but they could be added at the same time. I'm not sure how portable they are, though, beyond Linux.

I can send a CL if this is accepted.

**Comment by Merovius** [comment]
(See also #21676 which discusses, among other things, exposing an interface to `writev`/`readv` for `*os.File`)

**Comment by ianlancetaylor** [comment]
In general we permit adding any existing system call to x/net/unix.  Using `[][]byte` as the second argument seems right to me.  So this is fine.

**Comment by tklauser** [comment]
I assume you meant `x/sys/unix`, not `x/net/unix`?

It's fine to add the non-portable `preadv`/`pwritev`/`preadv2`/`pwritev2` variants for Linux only. We already have several wrappers for Linux-only syscalls.

**Comment by Merovius** [comment]
@tklauser yes I do, thanks, corrected :) I'll send a CL later today.

**Comment by Merovius** [comment]
I only have Linux machines, so AIUI I can't generate the constants and everything for other platforms.
Also, I mostly copied the interaction with the race-detector from Read/Write - I have no idea if that was needed or correct in this case.
