### ISSUE TITLE
Question: Is a chain of goroutines with empty select deletable?

### ISSUE THREAD

**Issue by anqurvanillapy** [golang/go#36214]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOOS=windows
</pre></details>

### What did you do?

The following code shows that the chain of goroutines `A` and `B` remains and intuitively I think they can be removed from the scheduler.  Is this necessary to remove them or any reason that removing is not a good choice or that's just not a deal?

```go
package main

import (
	"fmt"
	"runtime"
	"time"
)

func B() {
	select {}
}

func A() {
	B()
}

func main() {
	go A()
	for i := 0; i < 20; i++ {
		time.Sleep(1 * time.Second)
		fmt.Println(runtime.NumGoroutine())
	}
}
```

### What did you expect to see?

```
1
1
...
```

### What did you see instead?

```
2
2
...
```

**Comment by go101** [comment]
The proposal to remove stale goroutines was rejected before: https://github.com/golang/go/issues/19702

**Comment by anqurvanillapy** [comment]
@go101 Thanks so much for the information!  I'm closing this now.
