### ISSUE TITLE
internal/syscall/unix: SYS_FCNTL blocked by seccomp on Android

### ISSUE THREAD

**Issue by renwotao** [golang/go#36211]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13.5
Android 10 
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rhh/.cache/go-build"
GOENV="/home/rhh/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/rhh/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build178394675=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
build android arm dynamic library(.so)

### What did you expect to see?
seccomp filter can pass 

### What did you see instead?
![image](https://user-images.githubusercontent.com/8586620/71160527-b53d2e80-2282-11ea-867e-546288f5ae45.png)

hi，buddy
   when I build arm android dynamic library with golang, I test library in Android 10 env, but crash when running library.

**Comment by tklauser** [comment]
Looks like the offending syscall number is 55, which is `SYS_FCNTL` on `linux/arm`. It seems, `SYS_FCNTL64` isn't blocked on android, so we might use this one.

/cc @ianlancetaylor @eliasnaur @hyangah

**Comment by renwotao** [comment]
@tklauser thx for your reply, but build 32-bit android arm library, how to use SYS_FCNTL64? I found that golang package call SYS_FCNTL in init function.

**Comment by tklauser** [comment]
@renwotao we'll need to fix this in the Go standard libary, i.e. in `internal/syscall/unix` and all other places using `SYS_FCNTL`.

**Comment by ianlancetaylor** [comment]
Working on  a patch.
