### ISSUE TITLE
proxy.golang.org: inconsistent behavior in go.mod file checking

### ISSUE THREAD

**Issue by aofei** [golang/go#36217]
The `go help go.mod` says the `go` directive is used to set the expected language version:

> ...
> The expected language version, set by the go directive, determines
> which language features are available when compiling the module.
> Language features available in that version will be available for use.
> Language features removed in earlier versions, or added in later versions,
> will not be available. Note that the language version does not affect
> build tags, which are determined by the Go release being used.

But it didn't say what the specific format of the version should be. There is only one example we can see: `go 1.12`.

Fortunately, the `golang.org/x/mod/modfile` gives a regular expression:

https://github.com/golang/mod/blob/331c550502dddccec70ff032beba72756bb428f2/modfile/rule.go#L156

```go
var GoVersionRE = lazyregexp.New(`^([1-9][0-9]*)\.(0|[1-9][0-9]*)$`)
```

But the [proxy.golang.org](https://proxy.golang.org) doesn't follow this regular expression to check the `go.mod` files it crawls.

Check this out: https://proxy.golang.org/github.com/ihaiker/gokit/@v/v1.5.16.mod

It contains a `go 1.12.1` that cannot pass the [`modfile.Parse`](https://godoc.org/golang.org/x/mod/modfile#Parse) (I don't know why, it seems its author changed it manually), but it was cached as a legal `go.mod` file. This doesn't feel right to me.

So, is this an expected behavior? @bcmills

**Comment by bcmills** [comment]
`proxy.golang.org` only _serves_ `go.mod` files. It does not verify their syntax except to the extent that those syntax errors interfere with `go mod download`.

Also bear in mind that `go.mod` files that are invalid with the current release may become valid with a later release, so strict checking would potentially cause the proxy to be unable to serve modules created with pre-release versions of the `go` command. (That is also why `modfile.ParseLax` exists.)

**Comment by bcmills** [comment]
As far as I can tell the behavior of `proxy.golang.org` here is expected.

(CC @hyangah @heschik @katiehockman)
