### ISSUE TITLE
x/exp/shiny: Not all keyboard events are delivered on Windows

### ISSUE THREAD

**Issue by GreenLightning** [golang/go#36213]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.4 windows/amd64
</pre>

### What did you do?

Run the `basic` example on Windows and press F10.

### What did you expect to see?

Expected the following lines of output:

```
got key.Event{(CodeF10), key.Modifiers(), Press}
got key.Event{(CodeF10), key.Modifiers(), Release}
```

### What did you see instead?

No output was produced.

---

This issue also applies to pressing any key while the ALT key is pressed.

The cause of this issue is that shiny only handles the `_WM_KEYDOWN` and `_WM_KEYUP` messages, whereas under certain circumstances (namely if the key is F10 or the ALT key is pressed) Windows sends the `_WM_SYSKEYDOWN` and `_WM_SYSKEYUP` messages instead. This behavior is documented in the Windows documentation [here](https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-syskeydown).

This can be fixed by handling `_WM_SYSKEYDOWN` and `_WM_SYSKEYUP` exactly like `_WM_KEYDOWN` and `_WM_KEYUP` [here](https://github.com/golang/exp/blob/2f50522955873285d9bf17ec91e55aec8ae82edc/shiny/driver/internal/win32/win32.go#L336) and [here](https://github.com/golang/exp/blob/2f50522955873285d9bf17ec91e55aec8ae82edc/shiny/driver/internal/win32/key.go#L335).

For consistency across platforms and since key events are used for keyboard shortcuts, I would expect  all keyboard events to be delivered. I identified this as the root cause of keyboard shortcuts not working in [gdlv](https://github.com/aarzilli/gdlv). For reference, [GLFW](https://www.glfw.org/), which is a C library that also provides an abstraction layer over creating windows and receiving input, also handles both kinds of messages in the same way (see [here](https://github.com/glfw/glfw/blob/73a8ebb691813ccdc1531c1bd916c352ac0b7574/src/win32_window.c#L746)).

**Comment by alexbrainman** [comment]
@GreenLightning your explanation sounds reasonable.

Do you want to send change you described? This https://golang.org/doc/contribute.html is how to contribute.

Thank you.

Alex

**Comment by GreenLightning** [comment]
I have created a pull request at golang/exp#8.
