### ISSUE TITLE
url parse return error for valid rawurl

### ISSUE THREAD

**Issue by hainesc** [golang/go#36216]
When I use url.Parse("0.client-channel.google.com:443"), it thrown an error said
```
first path segment in URL cannot contain colon 
```
same for 3m.com:8080, As I dig into the RFC1101, it's seems a valid rawurl. Please see the detail below.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/haines/Library/Caches/go-build"
GOENV="/Users/haines/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/haines/workspace/go/"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/haines/workspace/go/src/github.com/hainesc/piculet/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7k/2l62bpb14c138xchnh4yjrkm0000gn/T/go-build759730205=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
```
package main

import (
	"fmt"
	"net/url"
)

func main() {
	host := "0.client-channel.google.com:443/abc"
	_, err := url.Parse(host)
	if err != nil {
		fmt.Println(err)
	}
}
```

https://play.golang.org/p/IFk_pAWB_fE

### What did you expect to see?

As documented in [RFC1101 section 3.1](https://tools.ietf.org/html/rfc1101#section-3.1), 
```
For example, 3Com.COM and 3M.COM are now legal
```
So I expect url.Parse working well and not return error.
### What did you see instead?

first path segment in URL cannot contain colon

**Comment by seankhliao** [comment]
The current documentation for url.Parse states:
> The rawurl may be relative (a path, without a host) or absolute (starting with a scheme). Trying to parse a hostname and path without a scheme is invalid but may not necessarily return an error, due to parsing ambiguities.

Your example is between the 2

**Comment by tv42** [comment]
RFC1101 defines DNS names, not URLs. See https://tools.ietf.org/html/rfc1738#section-5 instead. You'll see you need a scheme for a non-relative URL.

**Comment by mvdan** [comment]
What @tv42 said.
