### ISSUE TITLE
run testcase error for build pass

### ISSUE THREAD

**Issue by duchuanLX** [golang/go#36229]
Please answer these questions before submitting your issue. Thanks!

    What version of Go are you using (go version)?

    release-1.8 branch

    What operating system and processor architecture are you using (go env)?

    loongson mips

    What did you do?

    build go from source

    What did you expect to see?

    build pass

    What did you see instead?

--- FAIL: TestCloneNEWUSERAndRemapRootDisableSetgroups (0.00s)
	exec_linux_test.go:81: Cmd failed with err fork/exec /usr/bin/whoami: invalid argument, output: 
--- FAIL: TestCloneNEWUSERAndRemapRootEnableSetgroups (0.00s)
	exec_linux_test.go:81: Cmd failed with err fork/exec /usr/bin/whoami: invalid argument, output: 
--- FAIL: TestEmptyCredGroupsDisableSetgroups (0.00s)
	exec_linux_test.go:129: fork/exec /usr/bin/whoami: invalid argument
--- FAIL: TestGroupCleanupUserNamespace (0.00s)
	exec_linux_test.go:238: Cmd failed with err fork/exec /usr/bin/id: invalid argument, output: 
FAIL

**Comment by duchuanLX** [comment]
--- FAIL: TestCloneNEWUSERAndRemapRootDisableSetgroups (0.01s)
	exec_linux_test.go:106: whoami = "nfsnobody\n"; want "root"
--- FAIL: TestCloneNEWUSERAndRemapRootEnableSetgroups (0.02s)
	exec_linux_test.go:106: whoami = "nfsnobody\n"; want "root"

**Comment by ianlancetaylor** [comment]
Go 1.8 is quite old.  Do you see the same problems with Go 1.13, or with the recent Go 1.14beta1 release?

**Comment by duchuanLX** [comment]
> recent

sorry， I just need 1.8 verison，all pass。
modify 1file：syscall/exec_linux_test.go
//GidMappingsEnableSetgroups: setgroups,
 GidMappingsEnableSetgroups: true,

how build src 2 archiver package。

**Comment by duchuanLX** [comment]
> Go 1.8 is quite old. Do you see the same problems with Go 1.13, or with the recent Go 1.14beta1 release?

sorry, only Go1.8 version

**Comment by ianlancetaylor** [comment]
Sorry, we no longer support Go 1.8.

I wouldn't worry about these test failures, they are unlikely to indicate any kind of real problem with your Go installation.

**Comment by duchuanLX** [comment]
> Sorry, we no longer support Go 1.8.
> 
> I wouldn't worry about these test failures, they are unlikely to indicate any kind of real problem with your Go installation.

OK，thanks!
