### ISSUE TITLE
cmd/go: 'go list' should set the 'GoMod' field to reflect -modfile

### ISSUE THREAD

**Issue by bcmills** [golang/go#36220]
The `-modfile` flag added for #34506 allows users to substitute an arbitrary file in place of the `go.mod` file found at the module root. We (@jayconrod, @matloob, and I) were talking through the implications of that this morning, and realized that that has a very subtle interaction with `go env GOMOD`, `go list`, and tools in general.

With Go 1.13, tools may execute either `go env GOMOD` `go list -m -f '{{.GoMod}}'` to discover the location of the main module's `go.mod` file, and (if in a module) may execute `dirname $(go env GOMOD)` in order to locate the module root.

The `go env` command does not support the `-modfile` flag, so if someone sets, say, `GOFLAGS=-modfile=/tmp/foo.mod`, then `go env GOMOD` will continue to report the `go.mod` file found in the module root, rather than the one in use. That seems fine.

However, `go list` _does_ support the `-modfile` flag, so it should report the replacement `go.mod` file in the `GoMod` field. Today it does not.

(Tools that need to locate the _directory containing_ the main module should already be using the `Dir` field from `go list`, rather than the `GoMod` field.)

Today I see:
```
~/go/src$ GOFLAGS=-modfile=/tmp/foo.mod go env GOMOD
/usr/local/google/home/bcmills/go/src/go.mod

~/go/src$ GOFLAGS=-modfile=/tmp/foo.mod go list -m -f '{{.GoMod}}'
/usr/local/google/home/bcmills/go/src/go.mod
```

However, that should probably instead be:
```
~/go/src$ GOFLAGS=-modfile=/tmp/foo.mod go env GOMOD
/usr/local/google/home/bcmills/go/src/go.mod

~/go/src$ GOFLAGS=-modfile=/tmp/foo.mod go list -m -f '{{.GoMod}}'
/tmp/foo.mod
```

CC @heschik @dmitshur (in case this affects `goimports` and/or `godoc`)

**Comment by dmitshur** [comment]
The `GoMod` field in the template used by `go list -m -f` is currently documented as:

```
GoMod string // path to go.mod file for this module, if any
```

I think with the addition of the `-modfile` flag, that description becomes ambiguous. It's not verly clear if it means:

```
GoMod string // path to [original] go.mod file for this module [that may have been replaced via -modfile flag], if any
```

Or:

```
GoMod string // path to [potentially replaced via -modfile flag] go.mod file for this module, if any
```

I think it'd be worth making the documentation of the `GoMod` field such that it's not ambiguous whether it's affected by a potential `-modfile` value or not.

**Comment by heschik** [comment]
goimports and gopls should be unaffected by this either way.

**Comment by jayconrod** [comment]
@dmitshur Good idea. Added to https://golang.org/cl/212100.
