### ISSUE TITLE
cmd/go: actually allow "go run" without any arguments nor flags

### ISSUE THREAD

**Issue by mvdan** [golang/go#36235]
https://github.com/golang/go/issues/22726 was accepted and implemented a while ago. I'm really happy with it, because `go run .` is pretty useful.

I also understand the point that @rsc brought up about ambiguous flags. Not accepting `go run -foo` is reasonable, instead forcing the user to write `go run -foo .` or `go run . -foo` to clarify if the flag is for the Go tool or for the main package.

However, I don't quite undrestand why `go run` without any flags or arguments was left out:

```
$ go run
go run: no go files listed
```

The only reason I can think of is consistency, to make `go run` always require file or package arguments. Still, I'd argue that this form alone should be allowed. It's pretty convenient, and we could simply point the user in the right direction if they try to add a flag alone:

```
$ go run -foo
go run: specify a package or list of Go files to use flags
```

This would also actually mark the original proposal as implemented. I was pretty confused that the original proposal was accepted and closed, while the very idea in the title was never implemented.

At the very least, if this proposal is rejected, I think the original proposal should be retitled.

/cc @myitcv @rogpeppe @broady @rsc

**Comment by mvdan** [comment]
This got pretty much all positive feedback and no complaints, so we agreed with @bcmills to just move it to a regular issue to be fixed.

**Comment by rsc** [comment]
Please don't do this. It seems like a good idea, and then the very next thing someone wants to do is pass a _single_ argument, whether a flag or not, and it all breaks.

**Comment by rsc** [comment]
If `go run .` is not discoverable enough, it would be fine to change the message

    go run: no go files listed (use 'go run .' for current package)

**Comment by mvdan** [comment]
That's fair. It's been some time since I filed this, and I feel less strongly about it now. We now also have `go run pkg@version`, so I think it's going to be expected that one always gives arguments to `go run`.

> At the very least, if this proposal is rejected, I think the original proposal should be retitled.

I think we should still do this, though. We have an accepted and closed proposal titled `proposal: cmd/go: allow "go run" without arguments`, which is clearly not the current state of affairs.

**Comment by seankhliao** [comment]
I've retitled the other issue, closing this one as we're not doing it

**Comment by go101** [comment]
@seankhliao is there a link to the other one?
