### ISSUE TITLE
The go test was error patch the `-run` arguments

### ISSUE THREAD

**Issue by lidongdong536** [golang/go#36231]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build601011031=/tmp/go-build -gno-record-gcc-switches"
</pre>

</details>

### What did you do?

i write 3 test case to test the klog utils named ["TestKlog","TestKlog2","TestKlog"],
and i run the command `go test -v xxx_test.go`  there was some error was happen,
then i wnna test them individual,first i test "TestKlog" with `go test -v -run TestKlog xxx_test.go`
the error was go on,and then i run this command `go test -v -run TestKlog2 xxx_test.go` was PASS,
i rename the "TestKlog"->"TestKlog1" and run `go test -v -run TestKlog1 xxx_test.go`  was PASS,
i think there was some priciple can match the prefix of the test case`s name 

### What did you expect to see?
go test -v -run TestKlog1 xxx_test.go ==> only run the test case that full match the -run`s arguments,if the name wasn`t exist print error to the stdout

### What did you see instead?
no

**Comment by bcmills** [comment]
Per the [documentation](https://golang.org/cmd/go/#hdr-Testing_flags), the argument to the `run` flag is a regular expression. If you want to run only tests whose full name matches the regular expression, add the usual `^` and `$` anchors to the ends.
