### ISSUE TITLE
testing: B logs are printed on stdout, but doc says they go to stderr

### ISSUE THREAD

**Issue by megalepozy** [golang/go#36257]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
It's an issue at the documentation so the question is irrelavent

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/nimrod/.cache/go-build"
GOENV="/home/nimrod/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/nimrod/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build403478965=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Read the testing pkg documentation and saw that its incorrect at https://golang.org/pkg/testing/#B

### What did you expect to see?
"Like in tests, benchmark logs are accumulated during execution and dumped to standard output when done."

### What did you see instead?
The following is a quote from the third paragraph on Type B:
"Like in tests, benchmark logs are accumulated during execution and dumped to **standard error** when done."

It's incorrect as it state that the benchmark logs are dumped to standard error

**Comment by ALTree** [comment]
Thanks for reporting this. 

Apparently the `testing.T` documentation had the same issue, but it was fixed in [CL 24311](https://go-review.googlesource.com/c/go/+/24311). I will send a CL to fix `testing.B` too.
