### ISSUE TITLE
x/tools/gopls: inconsistent output for circular dependencies in testdata

### ISSUE THREAD

**Issue by stamblerre** [golang/go#36265]
Given 2 packages that import each other, `go list`-ing one of the packages will result in the dependency being listed as having no imports. This avoids infinite cycles, but it has the consequences of producing inconsistent results. I noticed this in `gopls`, when I first ran `go/packages` on one of these packages, followed by the other. `gopls` doesn't necessarily update dependencies after `go/packages` runs, so the result created a circular dependency. The first work-around I can think of is always updating the metadata for all dependencies, which may be too slow.

I was curious if there is any other way that this could be handled - maybe the alphabetically first package could be picked as the "top level" one, since everything in this case is broken anyway? If not, I will figure out a work-around in `gopls`, but I just wanted to raise this.

/cc @jayconrod @matloob 

Repro: 

```
$ go list -e -json -compiled -deps golang.org/x/tools/internal/lsp/testdata/circular/double/b/
{
	"ImportPath": "golang.org/x/tools/internal/lsp/circular/double/one",
        ...
	"Error": {
		"ImportStack": [
			"golang.org/x/tools/internal/lsp/testdata/circular/double/b",
			"golang.org/x/tools/internal/lsp/circular/double/one"
		],
		"Pos": "golang.org/x/tools/internal/lsp/testdata/circular/double/b/b.go:4:2",
		"Err": "..."
	}
}
{
	"ImportPath": "golang.org/x/tools/internal/lsp/testdata/circular/double/b",
         ...
	"GoFiles": [
		"b.go"
	],
	"CompiledGoFiles": [
		"b.go"
	],
	"Imports": [
		"golang.org/x/tools/internal/lsp/circular/double/one"
	],
	"Deps": [
		"golang.org/x/tools/internal/lsp/circular/double/one"
	],
	"DepsErrors": [
		{
			"ImportStack": [
				"golang.org/x/tools/internal/lsp/testdata/circular/double/b",
				"golang.org/x/tools/internal/lsp/circular/double/one"
			],
			"Pos": "golang.org/x/tools/internal/lsp/testdata/circular/double/b/b.go:4:2",
			"Err": "..."
		}
	]
}
deps golang.org/x/tools/internal/lsp/testdata/circular/double/b/

$ go list -e -json -compiled -deps golang.org/x/tools/internal/lsp/testdata/circular/double/one/
...<opposite>...
```

**Comment by jayconrod** [comment]
This is the error I'm actually seeing on the internal package. I think `/testdata/` is missing from the import in both packages, so the imported package doesn't actually exist.

<pre>
{
	"ImportPath": "golang.org/x/tools/internal/lsp/circular/double/one",
	"DepOnly": true,
	"Incomplete": true,
	"Stale": true,
	"StaleReason": "build ID mismatch",
	"Error": {
		"ImportStack": [
			"golang.org/x/tools/internal/lsp/testdata/circular/double/b",
			"golang.org/x/tools/internal/lsp/circular/double/one"
		],
		"Pos": "internal/lsp/testdata/circular/double/b/b.go:4:2",
		"Err": "no matching versions for query \"latest\""
	}
}
</pre>

The error message is pretty bad, but the behavior seems correct. Note that import errors are attached to the imported package, which may be a dummy package (that can confuse go/packages; see #36188), not the importing package.

@stamblerre Could you just confirm it's `/testdata/` that's missing? Here's the output I get after fixing the imports. It seems like what you want.

<details><pre>
$ go list -e -json -compiled -deps ./internal/lsp/testdata/circular/double/b
{
	"Dir": "/Users/jayconrod/go/src/golang.org/x/tools/internal/lsp/testdata/circular/double/one",
	"ImportPath": "golang.org/x/tools/internal/lsp/testdata/circular/double/one",
	"Name": "one",
	"Root": "/Users/jayconrod/go/src/golang.org/x/tools",
	"Module": {
		"Path": "golang.org/x/tools",
		"Main": true,
		"Dir": "/Users/jayconrod/go/src/golang.org/x/tools",
		"GoMod": "/Users/jayconrod/go/src/golang.org/x/tools/go.mod",
		"GoVersion": "1.11"
	},
	"DepOnly": true,
	"Incomplete": true,
	"Stale": true,
	"StaleReason": "stale dependency: golang.org/x/tools/internal/lsp/testdata/circular/double/b",
	"GoFiles": [
		"one.go"
	],
	"CompiledGoFiles": [
		"one.go"
	],
	"Imports": [
		"golang.org/x/tools/internal/lsp/testdata/circular/double/b"
	],
	"Deps": [
		"golang.org/x/tools/internal/lsp/testdata/circular/double/b"
	],
	"DepsErrors": [
		{
			"ImportStack": [
				"golang.org/x/tools/internal/lsp/testdata/circular/double/b",
				"golang.org/x/tools/internal/lsp/testdata/circular/double/one",
				"golang.org/x/tools/internal/lsp/testdata/circular/double/b"
			],
			"Pos": "",
			"Err": "import cycle not allowed"
		}
	]
}
{
	"Dir": "/Users/jayconrod/go/src/golang.org/x/tools/internal/lsp/testdata/circular/double/b",
	"ImportPath": "golang.org/x/tools/internal/lsp/testdata/circular/double/b",
	"Name": "b",
	"Root": "/Users/jayconrod/go/src/golang.org/x/tools",
	"Module": {
		"Path": "golang.org/x/tools",
		"Main": true,
		"Dir": "/Users/jayconrod/go/src/golang.org/x/tools",
		"GoMod": "/Users/jayconrod/go/src/golang.org/x/tools/go.mod",
		"GoVersion": "1.11"
	},
	"Match": [
		"./internal/lsp/testdata/circular/double/b"
	],
	"Incomplete": true,
	"Stale": true,
	"StaleReason": "build ID mismatch",
	"GoFiles": [
		"b.go"
	],
	"CompiledGoFiles": [
		"b.go"
	],
	"Imports": [
		"golang.org/x/tools/internal/lsp/testdata/circular/double/one"
	],
	"Deps": [
		"golang.org/x/tools/internal/lsp/testdata/circular/double/b",
		"golang.org/x/tools/internal/lsp/testdata/circular/double/one"
	],
	"Error": {
		"ImportStack": [
			"golang.org/x/tools/internal/lsp/testdata/circular/double/b",
			"golang.org/x/tools/internal/lsp/testdata/circular/double/one",
			"golang.org/x/tools/internal/lsp/testdata/circular/double/b"
		],
		"Pos": "",
		"Err": "import cycle not allowed"
	},
	"DepsErrors": [
		{
			"ImportStack": [
				"golang.org/x/tools/internal/lsp/testdata/circular/double/b",
				"golang.org/x/tools/internal/lsp/testdata/circular/double/one",
				"golang.org/x/tools/internal/lsp/testdata/circular/double/b"
			],
			"Pos": "",
			"Err": "import cycle not allowed"
		}
	]
}
</pre></details>

**Comment by stamblerre** [comment]
Thanks for looking into this. The fact that these files are in `testdata` does seem to be the problem. The missing `testdata` in the imports is handled by the test harness, but it seems like something isn't working correctly either in our tests or in gopackagestest. I confirmed that `go list` works as expected outside of the testdata. Repurposing this issue to figure out what's going on with the tests.

**Comment by stamblerre** [comment]
I think this is a duplicate of https://github.com/golang/go/issues/40332 - I don't think it's worth figuring out what's going on with the testdata.
