### ISSUE TITLE
runtime: process does not work internally, it seems the thread hangs

### ISSUE THREAD

**Issue by mmli519** [golang/go#36268]
### What version of Go are you using (`go version`)?

<pre>
go version go1.12.9 linux/arm64

</pre>

### Does this issue reproduce with the latest release?
Not test yet. Can not test on production environment

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
aarch64
</pre></details>

### What did you do?
do nothing, just run the go program

### What did you expect to see?
program run normally

### What did you see instead?
process looks normal,  while it does not work internally. After using gstack to capture the stack info, it seems that the thread hangs 

Thread 14 (Thread 0xffff9dfd80c0 (LWP 149497)):
#0  runtime.futex () at /opt/tools/go/src/runtime/sys_linux_arm64.s:417
#1  0x000000000042cb68 in runtime.futexsleep (addr=0x14f23a0 <runtime.sched+256>, val=0, ns=100000) at /opt/tools/go/src/runtime/os_linux.go:63
#2  0x000000000040be7c in runtime.notetsleep_internal (n=0x14f23a0 <runtime.sched+256>, ns=100000, ~r2=<optimized out>) at /opt/tools/go/src/runtime/lock_futex.go:193
#3  0x000000000040bf50 in runtime.notetsleep (n=0x14f23a0 <runtime.sched+256>, ns=100000, ~r2=<optimized out>) at /opt/tools/go/src/runtime/lock_futex.go:216
#4  0x00000000004330d0 in runtime.stopTheWorldWithSema () at /opt/tools/go/src/runtime/proc.go:1050
#5  0x00000000004588c8 in runtime.systemstack () at /opt/tools/go/src/runtime/asm_arm64.s:237
#6  0x00000000004333c8 in runtime.startTheWorldWithSema (emitTraceEvent=32, ~r1=<optimized out>) at /opt/tools/go/src/runtime/proc.go:1082

**Comment by networkimprov** [comment]
Can you provide a small, complete program which reproduces this problem, and tell us how you built and ran it?
