### ISSUE TITLE
why separate usages of bool and other types in flag package?

### ISSUE THREAD

**Issue by opriz** [golang/go#36263]
As been described in https://godoc.org/flag:

> The following forms are permitted:
> ```
> -flag
> -flag=x
> -flag x  // non-boolean flags only
>```
> One or two minus signs may be used; they are equivalent. The last form is not permitted for boolean flags because the meaning of the command
> 
>```
> cmd -x *
>```
> where * is a Unix shell wildcard, will change if there is a file called 0, false, etc. You must use the -flag=false form to turn off a boolean flag.

But I found not-boolean types also have the "*" problem(eg. A file named as numbers and been passed to a number flag using *), why treat bool as special case?
And in my view the "*" problem can be a problem of users' behavior, not a bug of program itself.
Howerver, this optimize can cause some problems when user not familiar with these considerations, as the inconsistent usage may cause confusion.
Can this design be a over-optimization case?

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker to ask questions.  Please use a forum instead.  See https://golang.org/wiki/Questions.  Thanks.

The point that the documentation is trying to make is that non-boolean flags always take an argument.  So writing `cmd -x *` where `-x` is a numeric flag will always take the first first as the argument, and give an error if the first file is not a number.  With boolean flags we want `-x` to be the same as `-x=true`.  If we permit `-x false`, that means that a command line like `-x *` will sometimes enable `-x` and sometimes not, depending on the name of the first file.  That ambiguity means that we cannot accept `-x false`, but only `-x=false`.
