### ISSUE TITLE
cmd/go: list modifies local go.sum even when package does not exist in queried module

### ISSUE THREAD

**Issue by kortschak** [golang/go#36260]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/user/bin"
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/user/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/tmp/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build218352463=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
~ $ mkdir tmp
~ $ cd tmp
~/tmp $ go mod init module
go: creating new go.mod: module module
~/tmp $ stat go.sum
stat: cannot stat 'go.sum': No such file or directory
~/tmp $ go list golang.org/x/tools/nonexistent
go: finding golang.org/x/tools latest
can't load package: package golang.org/x/tools/nonexistent: module golang.org/x/tools@latest found (v0.0.0-20191223235410-3721262b3e7c), but does not contain package golang.org/x/tools/nonexistent
~/tmp $ cat go.sum
golang.org/x/tools v0.0.0-20191223235410-3721262b3e7c h1:PeFrxQ8YTAKg53UR8aP/nxa82lQYIdb+pd1bfg3dBDM=
```

### What did you expect to see?

No change to go.sum.

### What did you see instead?

An addition to go.sum.

**Comment by cagedmantis** [comment]
@kortschak Thanks for creating an issue. I've been able to reproduce what you've described.
