### ISSUE TITLE
Any possibility of having HyperScan in go?

### ISSUE THREAD

**Issue by StarMonk** [golang/go#36280]
I kind of like HyperScan and would love to see "go version" of HyperScan - https://github.com/intel/hyperscan

Especially when regex is poor with go.

**Comment by ianlancetaylor** [comment]
I think it would be great if someone wants to take the ideas of HyperScan and use them to build a faster version of the regexp package.

However, I don't see a reason to open an issue about this.  Anybody can work on this.  It's not something the core Go team is likely to work on.  Making regexps faster is always desirable, but for that we need ideas more focused than "implement HypserScan."  So I'm going to close this issue.  Please comment if you disagree.
