### ISSUE TITLE
encoding/json: cause sweep increased allocation count crash on arm64

### ISSUE THREAD

**Issue by jing-rui** [golang/go#36286]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.0 linux/arm64
</pre>

go1.14.0 is build use commit 22d28a24c8
### Does this issue reproduce with the latest release?

Yes, we use master golang branch commit 22d28a24c8 without modify.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_arm64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build455143019=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

We write a program repeatedly unmarshal config.json file on arm64, run 10 process and wait about an hour some process will crash. When we switch to use jsoniter package, no crash occurs after running 3 days.

Reproduce program https://github.com/jing-rui/go-issue-36101

### What did you expect to see?

no process crash

### What did you see instead?

ref #36101

**Comment by agnivade** [comment]
Is this the same as #36101 ? I wonder why do we need a separate issue then ?

**Comment by cherrymui** [comment]
Let's discuss this in a single place. Closing this as a dup.

Also, I think this is more like a runtime issue than a json issue.
