### ISSUE TITLE
proposal: cmd/compile/gc: support external usage of functionalities

### ISSUE THREAD

**Issue by ardaguclu** [golang/go#36291]
Go compiler includes lots of useful functionalities, however only few of them are exported. 
All of the handy features are executed behind;

`func Main(archInit func(*Arch))`

For example, It would be great if escape analysis, etc. is aparted and exported from this tight coupling and used as a different module. Otherwise, the only way using the go compiler's internal/output data is the parsing the string output by setting gcflags to verbose mode(-m=2)

In order to clarify the proposal;

`var xtop []*Node` stores parsed lexical tree. There might be a way for parsing the given package into this tree and calling directly in order to simulate escape analysis. 

`escapes(xtop)`

**Comment by ALTree** [comment]
Hi, thanks for the request.

This is essentially a dup of #15108 (cmd/compile: make available as a library), so I'm closing this thread in favour of the older one. Feel free to subscribe to the other issue, but keep in mind that no decision on this has been made yet and even if this gets accepted it will definitely be a long-term job.
