### ISSUE TITLE
x/website: source code overlapping with line numbers

### ISSUE THREAD

**Issue by Surendrajat** [golang/go#36299]
### What version of Go are you using (`go version`)?

NA

### Does this issue reproduce with the latest release?

NA

### What operating system and processor architecture are you using (`go env`)?

NA

### What did you do?

I simply visited https://golang.org/src/archive/zip/register.go with the latest chrome browser(`Version 79.0.3945.88 (Official Build)`) on elementaryOS Hera and then verified with Brave browser(`Version 1.1.23 Chromium: 79.0.3945.88 (Official Build)`) as well.

### What did you expect to see?

I expect to see line numbers followed by the source.

### What did you see instead?

I see GO source overlapping the line numbers, making it hard to read

 Check screenshot:
![image](https://user-images.githubusercontent.com/11215000/71547787-98170700-29ca-11ea-8187-810b43c36c8d.png)

**Comment by RodionGork** [comment]
> with the latest chrome browser

probably it may make sense to put the **very complete** information about your browser version, so that it could be checked with exactly the same on different OS?

**Comment by Surendrajat** [comment]
@RodionGork Sure, Updated.

**Comment by seankhliao** [comment]
don't see this on arch linux, same chrome build. do you have any chrome flags/experiments/extensions enabled?

**Comment by Surendrajat** [comment]
@seankhlio I install .deb packages from official repo and have not set any such flag myself. There are extensions but I tried in incognito as well (no extension), same result. And if 'managed by your organization'(multiuser mode) is not an experiment than no, nothing.

**Comment by agnivade** [comment]
It looks like the font is also not being downloaded. Could you please post the console output of the page ? Do you also see the same result in firefox ?

**Comment by Surendrajat** [comment]
@agnivade The console is empty. I use `tor`, and it's working fine in it.
