### ISSUE TITLE
non-bool type used as if condition

### ISSUE THREAD

**Issue by cup** [golang/go#36304]
When I was first learning I tried something like this:

~~~go
package main
import "os"
func main() {
   r1, err := os.Open("day.txt")
   if err {
      println(err)
   }
   println(r1)
}
~~~

~~~
non-bool err (type error) used as if condition
~~~

I came to understand that you could only use Boolean in a condition. However I
thought I had read here https://golang.org/doc/faq or similar that the reason
is if that syntax was allowed, then Booleans would essentially have 3 states:
true, false and nil.

I cant seem to find where I read that, does anyone know where that page is?
Sorry to post here but I tried IRC and no answer, and I have been searching for
hours.

**Comment by mvdan** [comment]
Have you tried https://golang.org/wiki/Questions? There are plenty more places to ask questions that are better than the issue tracker, like the forum or Slack.

**Comment by smasher164** [comment]
Not a documentation page, but https://github.com/golang/go/issues/26712#issuecomment-410074939 demonstrates the "3 states" problem to which you refer.

As @mvdan mentioned, we don't use the issue tracker for questions. I'll go ahead and close this issue, but feel free to visit one of the resources listed on the wiki.
