### ISSUE TITLE
flag: add FlagSet usage examples

### ISSUE THREAD

**Issue by obeyda** [golang/go#36307]
### What did you expect to see?
Having some examples on the flag package's docs showing how to create subcommands with `FlagSet`.

### What did you see instead?
There's only a package example and `Value` interface usage and none of them shows how to use `FlagSet` to create subcommands.

**Comment by mvdan** [comment]
The example for https://golang.org/pkg/flag/#Value does use a flagset, but I agree that it's not easy to find. Sending a CL.

**Comment by Codinee** [comment]
I would like to work on coming up with examples for FlagSet commands usage.

**Comment by agnivade** [comment]
@Codinee - There is already an active CL for this.

**Comment by obeyda** [comment]
Any updates you can propose to this CL?

**Comment by mvdan** [comment]
@obeyda note that I asked for a rebase on the CL so we can re-test and merge.

**Comment by mvdan** [comment]
Friendly ping @obeyda, as someone else rebased the CL but now there's a missing import due to it. I know it's been some time, but if you can't fix up this patch so we can merge it, we should close the CL so someone else can take this.

**Comment by ccmtaylor** [comment]
https://go.dev/cl/545736 is marked "ready to submit" in Gerrit. What is the next step?
