### ISSUE TITLE
cmd/go: bug gives github server error

### ISSUE THREAD

**Issue by stephanwesten** [golang/go#36305]
### What version of Go are you using (`go version`)?
go version go1.13.5 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/stephanwesten/Library/Caches/go-build"
GOENV="/Users/stephanwesten/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/stephanwesten/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/stephanwesten/projects/gominikubedemo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -f
</pre></details>

macOS Catalina
10.15.2.

### What did you do?
Enter 'go bug' in terminal

Safari shows in address bar:
`https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fgolang%2Fgo%2Fissues%2Fnew%3Fbody%3D%253C%2521--%2BPlease%2Banswer%2Bthese%2Bquestions%2Bbefore%2Bsubmitting%2Byour%2Bissue.%2BThanks%2521%2B--%253E%250A%250A%2523%2523%2523%2BWhat%2Bversion%2Bof%2BGo%2Bare%2Byou%2Busing%2B%2528%2560go%2Bversion%2560%2529%253F%250A%250A%253Cpre%253E%250A%2524%2Bgo%2Bversion%250Ago%2Bversion%2Bgo1.13.5%2Bdarwin%252Famd64%250A%253C%252Fpre%253E%250A%250A%2523%2523%2523%2BDoes%2Bthis%2Bissue%2Breproduce%2Bwith%2Bthe%2Blatest%2Brelease%253F%250A%250A%250A%2523%2523%2523%2BWhat%2Boperating%2Bsystem%2Band%2Bprocessor%2Barchitecture%2Bare%2Byou%2Busing%2B%2528%2560go%2Benv%2560%2529%253F%250A%250A%253Cdetails%253E%253Csummary%253E%253Ccode%253Ego%2Benv%253C%252Fcode%253E%2BOutput%253C%252Fsummary%253E%253Cbr%253E%253Cpre%253E%250A%2524%2Bgo%2Benv%250AGO111MODULE%253D%2522%2522%250AGOARCH%253D%2522amd64%2522%250AGOBIN%253D%2522%2522%250AGOCACHE%253D%2522%252FUsers%252Fstephanwesten%252FLibrary%252FCaches%252Fgo-build%2522%250AGOENV%253D%2522%252FUsers%252Fstephanwesten%252FLibrary%252FApplication%2BSupport%252Fgo%252Fenv%2522%250AGOEXE%253D%2522%2522%250AGOFLAGS%253D%2522%2522%250AGOHOSTARCH%253D%2522amd64%2522%250AGOHOSTOS%253D%2522darwin%2522%250AGONOPROXY%253D%2522%2522%250AGONOSUMDB%253D%2522%2522%250AGOOS%253D%2522darwin%2522%250AGOPATH%253D%2522%252FUsers%252Fstephanwesten%252Fgo%2522%250AGOPRIVATE%253D%2522%2522%250AGOPROXY%253D%2522https%253A%252F%252Fproxy.golang.org%252Cdirect%2522%250AGOROOT%253D%2522%252Fusr%252Flocal%252Fgo%2522%250AGOSUMDB%253D%2522sum.golang.org%2522%250AGOTMPDIR%253D%2522%2522%250AGOTOOLDIR%253D%2522%252Fusr%252Flocal%252Fgo%252Fpkg%252Ftool%252Fdarwin_amd64%2522%250AGCCGO%253D%2522gccgo%2522%250AAR%253D%2522ar%2522%250ACC%253D%2522clang%2522%250ACXX%253D%2522clang%252B%252B%2522%250ACGO_ENABLED%253D%25221%2522%250AGOMOD%253D%2522%252FUsers%252Fstephanwesten%252Fprojects%252Fgominikubedemo%252Fgo.mod%2522%250ACGO_CFLAGS%253D%2522-g%2B-O2%2522%250ACGO_CPPFLAGS%253D%2522%2522%250ACGO_CXXFLAGS%253D%2522-g%2B-O2%2522%250ACGO_FFLAGS%253D%2522-g%2B-O2%2522%250ACGO_LDFLAGS%253D%2522-g%2B-O2%2522%250APKG_CONFIG%253D%2522pkg-config%2522%250AGOGCCFLAGS%253D%2522-fPIC%2B-m64%2B-pthread%2B-fno-caret-diagnostics%2B-Qunused-arguments%2B-fmessage-length%253D0%2B-fdebug-prefix-map%253D%252Fvar%252Ffolders%252Fj8%252F5y5yqzgx565g48mytvt40vvm0000gn%252FT%252Fgo-build485138459%253D%252Ftmp%252Fgo-build%2B-gno-record-gcc-switches%2B-fno-common%2522%250AGOROOT%252Fbin%252Fgo%2Bversion%253A%2Bgo%2Bversion%2Bgo1.13.5%2Bdarwin%252Famd64%250AGOROOT%252Fbin%252Fgo%2Btool%2Bcompile%2B-V%253A%2Bcompile%2Bversion%2Bgo1.13.5%250Auname%2B-v%253A%2BDarwin%2BKernel%2BVersion%2B19.2.0%253A%2BSat%2BNov%2B%2B9%2B03%253A47%253A04%2BPST%2B2019%253B%2Broot%253Axnu-6153.61.1~20%252FRELEASE_X86_64%250AProductName%253A%2509Mac%2BOS%2BX%250AProductVersion%253A%250910.15.2%250ABuildVersion%253A%250919C57%250Alldb%2B--version%253A%2Blldb-1100.0.30.11%250AApple%2BSwift%2Bversion%2B5.1.3%2B%2528swiftlang-1100.0.282.1%2Bclang-1100.0.33.15%2529%250A%253C%252Fpre%253E%253C%252Fdetails%253E%250A%250A%2523%2523%2523%2BWhat%2Bdid%2Byou%2Bdo%253F%250A%250A%253C%2521--%250AIf%2Bpossible%252C%2Bprovide%2Ba%2Brecipe%2Bfor%2Breproducing%2Bthe%2Berror.%250AA%2Bcomplete%2Brunnable%2Bprogram%2Bis%2Bgood.%250AA%2Blink%2Bon%2Bplay.golang.org%2Bis%2Bbest.%250A--%253E%250A%250A%250A%250A%2523%2523%2523%2BWhat%2Bdid%2Byou%2Bexpect%2Bto%2Bsee%253F%250A%250A%250A%250A%2523%2523%2523%2BWhat%2Bdid%2Byou%2Bsee%2Binstead%253F%250A%250A`

github returns server error -  500

Logging in to github before entering 'go bug' does not make a difference.

### What did you expect to see?

the page where I can enter a bug :-)

### What did you see instead?
see above

**Comment by mvdan** [comment]
I think this might be because the data is too long. I believe @myitcv ran into this recently as well, so he might have useful information for you.

**Comment by myitcv** [comment]
The issue I raised with GitHub support relates to being able to POST to the new issue end point. The original Twitter thread is here:

https://twitter.com/_myitcv/status/1205194369881583616

From the URL above it appears (at least on my setup) that being authenticated does have some effect. Copying and pasting the URL into an incognito instance of Chrome I get a 500 error; in my regular Chrome instance (where I am authenticated) I do not.

In this instance @stephanwesten it might be worth raising an issue with GitHub to see what their response is, because it appears there is a different limit imposed when authentication fails (which might make sense)

**Comment by cagedmantis** [comment]
Thank you for opening an issue @stephanwesten. I've tried to recreate the issue posted above. I was unsuccessful in my attempts at recreating the issue. Is it possible that the 500 response code from the GitHub server indicates that there was some sort of transient issue happening at the time that you posted the issue? Can you still reproduce the issue?

**Comment by stephanwesten** [comment]
Yes, just tried and i could reproduce it. Nothing interesting is running in the background.

Next, I made Firefox my default browser and then it works fine...

Using the inspector in Safari and re-loading the page I could find the following error in the inspector:
`Refused to load https://github.com/_error.js because it does not appear in the script-src directive of the Content Security Policy.` Another github problem besides returning 500.

Response in Safari:
`HTTP/1.1 500 Internal Server Error
Content-Type: text/html; charset=utf-8
Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com wss://live.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: github.githubassets.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; manifest-src 'self'; media-src 'none'; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Date: Tue, 31 Dec 2019 09:46:44 GMT
Content-Length: 161248
X-Content-Type-Options: nosniff
X-Frame-Options: deny
Server: GitHub.com
X-GitHub-Request-Id: 9708:3BB91:F967E37:17CA73B6:5E0B1904
Expect-CT: max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"
X-Request-Id: 59abff7d-81c2-4728-991a-c6966d734347
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
Status: 500 Internal Server Error`

**Comment by mvdan** [comment]
Closing old issues that still have the WaitingForInfo label where enough details to investigate weren't provided. Feel free to leave a comment with more details and we can reopen.
