### ISSUE TITLE
x/sys/unix: Getdirentries not found on darwin arm with Go 1.11

### ISSUE THREAD

**Issue by oxtoacart** [golang/go#36300]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
I'm using gomobile targeting darwin on arm
</pre></details>

### What did you do?

Compile a program that calls `Getdirentries` for darwin arm (32 bit) with Go 1.11

### What did you expect to see?

Successful compilation

### What did you see instead?

`readdirent_getdirentries.go:18:9: undefined: Getdirentries`

I think this was broken by the fix for #34400

**Comment by randall77** [comment]
@tklauser

**Comment by oxtoacart** [comment]
@tklauser That fix LGTM.
