### ISSUE TITLE
x/tools/gopls: renaming a test results in diagnostic error from test main

### ISSUE THREAD

**Issue by myitcv** [golang/go#36312]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +dcd3b2c173 Fri Dec 27 14:52:12 2019 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20191227053925-7b8e75db28f4
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.1.8-0.20191227053925-7b8e75db28f4
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build741613824=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Create these minimal files:

```
-- go.mod --
module mod.com

go 1.14

-- main.go --
package main

-- main_test.go --
package main

import "testing"

func TestThis(t *testing.T) {
}
```

Now quit your editor (such that `gopls` closes) and run:

```
go test
```

Now re-open your editor, open `main_test.go` and rename `TestThis -> TestThisAgain`

### What did you expect to see?

No diagnostic errors.

### What did you see instead?

Diagnostic error:

```
../../../../../.cache/go-build/9f/9f968e31138f43c5fd9fed9301f8c7895438d8a00b51baf3411218dad5311e4b-d|22 col 21| TestThis not declared by package main
```

---

cc @stamblerre

**Comment by stamblerre** [comment]
https://golang.org/cl/213660 just added the behavior to ignore test mains. Are you still seeing this issue with that CL?

**Comment by myitcv** [comment]
Thanks, that appears to fix it.
