### ISSUE TITLE
dial tcp : socket: too many open files

### ISSUE THREAD

**Issue by vanipolnedi** [golang/go#36311]
### What version of Go are you using (`go version`)?

<pre>
$ go version : go version go1.13 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build311150507=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
package main
import (
 "fmt"
 "io"
 "io/ioutil"
 "encoding/json"
 "net/http"
 )
 
type Struct_Response struct {
	Meta struct {
		Requestid        string
	}
} 
 
var HttpClient = &http.Client{}

func main(){
	apiUrl := "http://example.com"
	JsonStr :="teststr"
	conn_token :="1233333333333"
	req, err := http.NewRequest("POST", apiUrl, bytes.NewBuffer(JsonStr))
	if err!=nil{ 
		fmt.Println(err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("requestid", "1234")
	req.Header.Set("Authorization", "Bearer "+conn_token)
	req.Header.Set("Connection", "close")

	resp, err := HttpClient.Do(req)
	req.Close=true
	if resp!=nil && resp.StatusCode==200 {
		body, _ := ioutil.ReadAll(resp.Body)
		var Responce Struct_Response
		err := json.Unmarshal([]byte(string(body)), &Responce)
		if err != nil {
			fmt.Println(err)
		}
		io.Copy(ioutil.Discard, resp.Body)
		resp.Body.Close()
	}
}

When i load test this code, i'm getting error : **dial tcp : socket: too many open files**
By increasing ulimit its working fine ..but i want to solve this issue without setting ulimit. Any suggestions please??

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker for questions.  You will get better and faster answers for this kind of question in a forum.  Please see https://golang.org/wiki/Questions.  Thanks.

As far as I can see that program only opens one socket so I don't see why you are getting an error about too many open files.  Is there something else that you are doing, like running the program many times?  Please mention that when asking in a forum.
