### ISSUE TITLE
wiki: CodeReviewComments change - Standardize indentation

### ISSUE THREAD

**Issue by trungnn** [golang/go#36327]
Some code examples are not indented properly (use spaces instead of tabs). I think we should fix them:

https://github.com/golang/go/wiki/CodeReviewComments#imports
https://github.com/golang/go/wiki/CodeReviewComments#crypto-rand
https://github.com/golang/go/wiki/CodeReviewComments#in-band-errors

**Comment by ianlancetaylor** [comment]
Do you mean use tabs instead of spaces?  Sure, that sounds fine if it displays correctly.

**Comment by trungnn** [comment]
Yes, we should use tabs instead of spaces

**Comment by trungnn** [comment]
@ianlancetaylor do you want me to make the change? I can make it later today

**Comment by ianlancetaylor** [comment]
Sure, go ahead.  Thanks.

**Comment by trungnn** [comment]
Done. Closing this
