### ISSUE TITLE
cmd/go: add -race flag explanation on "go help testflag"

### ISSUE THREAD

**Issue by oomichi** [golang/go#36329]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 linux/amd64
$
</pre>

### Does this issue reproduce with the latest release?

Run `$ go help testflag` and see the lack of explanation for -race flag.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/oomichi/.cache/go-build"
GOENV="/home/oomichi/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/oomichi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/oomichi/go/src/k8s.io/kubernetes/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build234417289=/tmp/go-build -gno-record-gcc-switches"
$
</pre></details>

### What did you expect to see?

I'd like to see the explanation of "-race" flag to know the behavior.

### What did you see instead?

I cannot see it.

**Comment by mvdan** [comment]
It's in `go help build`, which you can see mentioned in `go help test`:

> For more about build flags, see 'go help build'.

It's a build flag, not a test flag, so it doesn't belong in `testflag`.

**Comment by cagedmantis** [comment]
Thank you for creating an issue @oomichi. I believe @mvdan's response shows that it's working as expected. Please feel free to re-open the issue if you disagree or if I misunderstood.

**Comment by oomichi** [comment]
@mvdan Thanks for your explanation, I got the meaning.
@cagedmantis Yes, @mvdan's response is good for me, it is fine to keep this as closed.

Thanks for your help :-)
