### ISSUE TITLE
import "runtime/internal/sys" error (Windows 10, WSL Ubuntu 18.04)

### ISSUE THREAD

**Issue by jly36963** [golang/go#36330]
### What version of Go are you using (`go version`)?

go version go1.13 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

Windows 10, WSL (Ubuntu 18.04)

I replaced the username with "user" in all paths below.

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build893793221=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

```go
import "runtime/internal/sys" // sys
```

### What did you expect to see?

system architecture

### What did you see instead?

failed import

`error executing "/usr/local/go/bin/go build -buildmode=plugin" in directory "/home/user/go/src/gomacro.imports/runtime/internal/sys/": exit status 1`

**Comment by bradfitz** [comment]
You can't import internal packages unless they're your internal packages.

See https://golang.org/doc/go1.4#internalpackages

**Comment by networkimprov** [comment]
You can use `import "internal/sys"` in a source file installed as .../go/src/runtime/yourfile.go, or for Windows-specific code .../go/src/runtime/yourfile_windows.go.

That requires special build instructions for anyone building your app, and may need to be re-installed after Go upgrades. But patching the runtime/stdlib is necessary in some cases.
