### ISSUE TITLE
go/types: improve error message quality for ptr receiver errors (go/types differs from go tool compile)

### ISSUE THREAD

**Issue by gertcuykens** [golang/go#36336]
In this particular case `go build` has a vastly better error message, assuming it's not vscode but gopls who is responsible for altering the original compile message.

```go
type roundTripper func(*http.Request) (*http.Response, error)

func (f roundTripper) RoundTrip(req *http.Request) (*http.Response, error) { return f(req) }

func proxy(u url.URL) http.Handler {
	return httputil.ReverseProxy{
		Transport: roundTripper(func(req *http.Request) (*http.Response, error) {
			req.Header.Set("Host", u.Host)
			return http.DefaultTransport.RoundTrip(req)
		}),
		Director: func(req *http.Request) {
			req.URL.Scheme = u.Scheme
			req.URL.Host = u.Host
			req.Header.Set("Host", u.Host)
		},
	}
}
```
![image](https://user-images.githubusercontent.com/863731/71620291-76d03980-2bc9-11ea-97cb-76c58684eb1e.png)

gopls:
```
cannot use (httputil.ReverseProxy literal) (value of type httputil.ReverseProxy) as http.Handler value in return statement: missing method ServeHTTP compiler
```

original go build compiler message:
```
cannot use httputil.ReverseProxy literal (type httputil.ReverseProxy) as type http.Handler in return argument:
        httputil.ReverseProxy does not implement http.Handler (ServeHTTP method has pointer receiver)
```

**Comment by muirdm** [comment]
gopls uses the go/types package, not the compiler, to type check. go/types doesn't provide as useful of an error message in this situation. It can probably be improved but would be subject to the Go release cycle (rather than gopls).

/cc @griesemer

**Comment by griesemer** [comment]
This is a `go/types`, not a gopls issue. Stand-alone test case: https://play.golang.org/p/LAbt1say8h2

The compiler reports:
`./prog.go:14:30: cannot use httputil.ReverseProxy literal (type httputil.ReverseProxy) as type http.Handler in return argument:
	httputil.ReverseProxy does not implement http.Handler (ServeHTTP method has pointer receiver)`

go/types reports:
`./prog.go:14:9: cannot use (httputil.ReverseProxy literal) (value of type httputil.ReverseProxy) as http.Handler value in return statement: missing method ServeHTTP`

It should not be too hard to make the `go/types` error better.
