### ISSUE TITLE
how to parse struct or interface to json string in simpler method

### ISSUE THREAD

**Issue by bluesky1024** [golang/go#36334]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
</pre></details>

### What did you do?

I expect to parse specific struct or interface, and describe them as the form of "json" or "xml".
etc:
```go
import xxpkg "github.com/a/b"

type MyStruct struct {
	ParamOne string
	ParamTwo int
	MySubStruct
}

type MyInterface interface {
	GetRespOne(int) string
	GetRespTwo(xxpkg.xxStruct) bool
}
```
```json
{
	"paramType":"interface", //or "struct"
	"locator":"xxpkg", //could we get the go module info?
	"name":"MyInterface",
	"funcList":[
		{
			"funcName":"GetRespOne",
			"inputParam":[
                                 {
                                     "locator":"-",
                                     "name":"int"
                                 }
			],
			"outputParam":[
				{
					"locator":"-",
					"type":"string"
				}
			]
		},
		{
			"funcName":"GetRespTwo",
			"inputParam":[
                                 {
                                     "locator":"xxpkg's locator",
                                     "name":"xxStruct"
                                 }
			],
			"outputParam":[
				{
					"locator":"-",
					"type":"bool"
				}
			]
		}
	]
}
```
For realize that, I tried the package "go/parse", "go/token", "go/ast". 
However, the ast tree's info is too complex which contain much information i do not need to parse.

### What did you expect to see?
I expect to search a tool to parse interface more simple and effectively.

thanks for your attention.

**Comment by cagedmantis** [comment]
For asking questions about learning the language, see one of our forums: https://golang.org/wiki/Questions

We only use this issue tracker for tracking bugs. People in the forums can explain what is happening here.
