### ISSUE TITLE
net/http: GET request with http.NoBody fails on js/wasm

### ISSUE THREAD

**Issue by tarndt** [golang/go#36339]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH=wasm GOOS=js running on Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0
</pre></details>

### What did you do?

I executed code that makes a HTTP GET request using `net/http` facilities and it failed with the following error: 
```
Fail:  Get https://localhost:8443/v1/endpoint: net/http: fetch() failed: <object>
```
I then added ``js.Global().Get("console").Call("log", args[0])`` on [line 160 of roundtrip_js.go](https://github.com/golang/go/blob/master/src/net/http/roundtrip_js.go#L160) and observed:
```
TypeError: "HEAD or GET Request cannot have a body."
    valueCall https://localhost:8443/wasm_exec.js:327
    run https://localhost:8443/wasm_exec.js:475
    <anonymous> https://localhost:8443/:9
```
_I then changed the body of the request_ created from ``http.NoBody`` to `nil` and observed a successful request being made:
- Fails: ``req, err := http.NewRequest(http.MethodGet, URL, http.NoBody)``
- Succeeds: ``req, err := http.NewRequest(http.MethodGet, URL, nil)``

**P.S.** In [roundtrip_js.go](https://github.com/golang/go/blob/master/src/net/http/roundtrip_js.go#L160) and the similar stdlib JavaScript platform code, if existing error reporting code such as:
```
err := fmt.Errorf("net/http: fetch() failed: %s", args[0].String())
```
is replaced with:
```
err := fmt.Errorf("net/http: fetch() failed: %s", js.Error{args[0]})
```
the output changes from:
```
net/http: fetch() failed: <object>
```
To
```
net/http: fetch() failed: JavaScript error: HEAD or GET Request cannot have a body.
```
which is substantially more helpful and perhaps warrants another issue. :smile_cat: 

### What did you expect to see?

Success. I expect nil and http.NoBody to function identically with respect to client `*http.Request``'s.

### What did you see instead?

Failure, GET requests under ``GOARCH=wasm GOOS=js`` fail when the request body is ``http.NoBody`` rather than ``nil``.

**Comment by lhlyu** [comment]
waiting for solution

**Comment by agnivade** [comment]
This is fixed now: https://github.com/golang/go/commit/7bfac4c3ddde3dd906b344f141a9d09a5f855c77#diff-e85f2dbad3447c4267e815cc9d014e69.

**Comment by tarndt** [comment]
@agnivade I see the logging was improved, but that diff does look to make any changes that would fix  request with `http.NoBody` from failing when `nil` succeeds (the primary issue). Was that changed in another diff?

**Comment by agnivade** [comment]
Oh my apologies, I somehow thought that the issue was about logging. Reopening.
