### ISSUE TITLE
go shorthand variable declaration - behaviour confusing with multiple variables

### ISSUE THREAD

**Issue by guysoffer** [golang/go#36356]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
windows 64 bit 
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\gs082r\AppData\Local\go-build
set GOENV=C:\Users\gs082r\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\gs082r\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\gs082r\AppData\Local\Temp\go-build292370350=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I use shorthand variable declaration for existing variables:

a := 1
{ // new block
fmt.Println(a)
a,b := 2 // a is shadowed !!
fmt.Println(a,b)
}
fmt.Println(a)

If I do the same thing without a new block, a isn't shadowed:
a := 1
fmt.Println(a)
a,b := 2 // a is assigned the new value as expected!!
fmt.Println(a,b)
fmt.Println(a)

This behaviour is very confusing for a programmer.. 
I assume go tries to put a "var" statement and skips this only if an error state would occur (multiple declaration within the same block), but the end result is quite confusing.. is there a way to change this behaviour ?

**Comment by ianlancetaylor** [comment]
The exact behavior is defined at https://golang.org/ref/spec#Short_variable_declarations.

Closing this issue as a dup of #377.
