### ISSUE TITLE
time: package has two different arrays with long month names

### ISSUE THREAD

**Issue by petar-dambovaliev** [golang/go#36359]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.1 linux/amd64
</pre>

Seems to me that there doesn't need to be code duplication here.
Do you mind if i remove it?

https://github.com/golang/go/blame/master/src/time/time.go#L288
https://github.com/golang/go/blame/master/src/time/format.go#L321

**Comment by ALTree** [comment]
For something this small, I would just send a patch. It'll get reviewed (and accepted, or rejected) directly on gerrit.

**Comment by mariush-github** [comment]
While you're there, the shortDayNames  array (line 296) could also be removed, if you reuse the longDayNames and take the first 3 characters - in this case it happens to match for all days. 

Same for  shortMonthNames  array, seems like all 3 letter months have the same first 3 letters as in longMonthNames 

also time.go: 326  there's a days array , format.go : 286 has longDayNames array

**Comment by petar-dambovaliev** [comment]
> While you're in format.go , the shortDayNames array (line 296) could also be removed, if you reuse the longDayNames and take the first 3 characters - in this case it happens to match for all days.
> 
> Same for shortMonthNames array, seems like all 3 letter months have the same first 3 letters as in longMonthNames
> 
> also time.go: 326 there's a days array , format.go : 286 has longDayNames array

Cool, i will get on it.
