### ISSUE TITLE
build pie binaries by default where supported

### ISSUE THREAD

**Issue by williamh** [golang/go#36352]
I received a report requesting that Go build pie binaries wherever they are supported by default [1].
The bug points to a patch archlinux is using, but I wanted to open this request with you before I apply the patch since it appears the patch will apply to go1.13.5 but not to master.

Can you please advise me?

[1] https://bugs.gentoo.org/show_bug.cgi?id=702598

**Comment by ianlancetaylor** [comment]
What do you want us to advise you about?  I'm not sure what you are asking.

In general it's best to send this of question to golang-nuts, rather than the issue tracker.  You will get better information that way.  See https://golang.org/wiki/Questions.  Thanks.

**Comment by williamh** [comment]
@ianlancetaylor  Sorry about the confusion. My question is what is the status of pie binaries in master? it looks like the patched file (src/cmd/go/internal/work/init.go) has changed significantly on master so the patch will not apply there. Are pie binaries going to be built everywhere they are supported by default in 1.14? Also, I will take a look at using the list next time.

**Comment by ianlancetaylor** [comment]
Go does not build PIE by default on master.

The patch https://git.archlinux.org/svntogit/community.git/tree/trunk/default-buildmode-pie.patch?h=packages/go does not apply cleanly on master but the code hasn't changed much and I think it's pretty easy to understand.  You could get the same effect as that patch by changing `case "android":` to `case "android", "linux":`.
