### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by L0rax23** [golang/go#36354]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
N/A

https://golang.org/ref/spec#Identifiers

I believe this text should read as such:

The first character in an identifier must be a letter. **(or underscore)**

**Comment by agnivade** [comment]
Please see: https://golang.org/ref/spec#letter.

> The underscore character _ (U+005F) is considered a letter.

I am going to close as there is no bug here. Please let me know if this was a mistake.
