### ISSUE TITLE
x/tools/gopls: extra autocompletion after complete keyword

### ISSUE THREAD

**Issue by stamblerre** [golang/go#36363]
<img width="1185" alt="Screen Shot 2020-01-02 at 1 44 57 PM" src="https://user-images.githubusercontent.com/5856771/71685424-4376e180-2d66-11ea-8aa7-e5097fdeffcf.png">

In this example, the full keyword `true` was typed, but it was still the 3rd ranked completion, which results in VS Code auto-inserting it if a user hits enter (intending to go to the next line).

/cc @muirdm

**Comment by muirdm** [comment]
Yeah I've been meaning to fix this. It is because `true` is an untyped bool which gets a score penalty. I'll fix it to not penalize builtin constants.
