### ISSUE TITLE
TCP Connections not closed by garbage collector

### ISSUE THREAD

**Issue by qingyunha** [golang/go#36379]
This is asked before. #541

It seems that the connection is still not closed. Should I explicitly call `runtime.SetFinalizer`.

```golang
package main

import (
        "net"
        "time"
)

func f() {
        conn, _ := net.Dial("tcp", ":8080")
        conn.Write([]byte("hello world\n"))
}

func main() {
        f()
        time.Sleep(10000 * time.Second)
}
```

**Comment by ianlancetaylor** [comment]
Your program isn't allocating any memory while it sleeps, so the garbage collector doesn't run.  Calling `runtime.SetFinalizer` won't make any difference.  Try calling `runtime.GC`.

In general we don't use the issue tracker for questions about Go.  You will normally get better and faster answers by using a forum.  See https://golang.org/wiki/Questions.  Thanks.
