### ISSUE TITLE
cmd/link: building the latest tip version fails

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#36389]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +8adc1e00aa Sat Jan 4 12:10:10 2020 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yoshiki/Library/Caches/go-build"
GOENV="/Users/yoshiki/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/yoshiki/gocode:/Users/yoshiki/exercises/gpl:/Users/yoshiki/oak"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/yoshiki/tools/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/yoshiki/tools/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pb/c7_4_d355ng5zfm4r_jg2gg00000gn/T/go-build275941764=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version devel +8adc1e00aa Sat Jan 4 12:10:10 2020 +0000 darwin/amd64
GOROOT/bin/go tool compile -V: compile version devel +8adc1e00aa Sat Jan 4 12:10:10 2020 +0000
uname -v: Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.15.2
BuildVersion:	19C57
lldb --version: lldb-1100.0.28.19
Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
</pre></details>

### What did you do?

Tried to rebuild the latest tip version with all.bash

### What did you expect to see?

No error

### What did you see instead?

```
ok  	cmd/internal/test2json	1.200s
--- FAIL: TestIssue33979 (1.59s)
    link_test.go:250: got:
        main(__TEXT/__text): relocation target undefined not defined
        want:
        main(.text): relocation target undefined not defined
FAIL
FAIL	cmd/link	17.142s
```

**Comment by ianlancetaylor** [comment]
CC @thanm @cherrymui @jeremyfaller

**Comment by mvdan** [comment]
Also remember that you just need `make.bash` to build, not `all.bash`, which also runs a number of tests.

**Comment by ALTree** [comment]
It appears that [CL 192597](https://go-review.googlesource.com/c/go/+/192597) broke some builders:

https://build.golang.org/#

(most darwin, several mips, AIX)

**Comment by aclements** [comment]
Looks like mostly an overly picky test that was just added. It's looking for "main(.text): relocation target undefined not defined\n", but it's getting:

darwin: main(__TEXT/__text): relocation target undefined not defined
linux/mips*: x.a(x3.o): unknown relocation type 11; compiled without -fpic?
aix: main.x: relocation target foo not defined

The linux/mips one seems a bit worse. My guess is there's some "go build" logic that the test isn't duplicating correctly.

@4a6f656c

**Comment by josharian** [comment]
Is the issue it is fixing critical for 1.14? If not, given where we are in the freeze, we should probably roll back and try again for 1.15.
