### ISSUE TITLE
couldn't install a pkg

### ISSUE THREAD

**Issue by umairalii** [golang/go#36388]
error attached
![image](https://user-images.githubusercontent.com/41395451/71772693-1a766c80-2f71-11ea-9821-be169fd927d4.png)

**Comment by ianlancetaylor** [comment]
You didn't fill out the issue template, you just deleted it.  Please do fill out the issue template.  Thanks.

This package can only be retrieved in module mode.  If you are using Go 1.13, set the environment variable `GO111MODULE=on`.  See `go help modules` for more information.
