### ISSUE TITLE
go mod download does not support self-signed certificates

### ISSUE THREAD

**Issue by graywolf** [golang/go#36395]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/wolf/.cache/go-build"
GOENV="/home/wolf/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/wolf/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/foo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build204289294=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Given source code:

```
+   $ tree .
.
├── aaa.go
└── go.mod

0 directories, 2 files
+   $ cat aaa.go
package foo

import (
        "127.0.0.1/foo/bar"
)
+   $ cat go.mod
module xxx

go 1.13

require 127.0.0.1/foo/bar v0.0.0
```

Now start https server with self-signed certificate

```
+   $ go mod download 127.0.0.1/foo/bar
go: 127.0.0.1/foo/bar@v0.0.0: unrecognized import path "127.0.0.1/foo/bar" (https fetch: Get https://127.0.0.1/foo/bar?go-get=1: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs)
```

Trying to use `-insecure` flag from `go get` does not work

```
+:( $ go mod download -insecure 127.0.0.1/foo/bar
flag provided but not defined: -insecure
usage: go mod download [-json] [modules]
Run 'go help mod download' for details.
```

so as far as I can tell there is currently no way to use module from server with self-signed certificate.

**Comment by oiooj** [comment]
dup of #27332
