### ISSUE TITLE
cmd/go: go.mod go get module has different behaviour than go get ./...

### ISSUE THREAD

**Issue by aspacca** [golang/go#36391]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/andrea/Library/Caches/go-build"
GOENV="/Users/andrea/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/andrea/Sources/goworkspace"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/andrea/tmp/src/github.com/dutchcoders/transfer.sh/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/36/fq4yxdhx78n39jy_w5lbdj980000gn/T/go-build877708644=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
<pre>
GO111MODULE=on GOPROXY=direct GOPATH=$(mktemp -d) go get -v github.com/dutchcoders/transfer.sh
</pre>

and
<pre>
git clone git@github.com:dutchcoders/transfer.sh.git
cd transfer.sh/
GO111MODULE=on GOPROXY=direct GOPATH=$(mktemp -d) go get -v ./...
</pre>

the two produces different results, the first failing to get dependency github.com/russross/blackfriday/v2

### What did you expect to see?
The same behaviour as the second:
<pre>
get "golang.org/x/sys": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at //golang.org/x/sys?go-get=1
get "golang.org/x/crypto": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at //golang.org/x/crypto?go-get=1
get "google.golang.org/grpc": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc?go-get=1
get "golang.org/x/oauth2": found meta tag get.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at //golang.org/x/oauth2?go-get=1
get "gopkg.in/check.v1": found meta tag get.metaImport{Prefix:"gopkg.in/check.v1", VCS:"git", RepoRoot:"https://gopkg.in/check.v1"} at //gopkg.in/check.v1?go-get=1
get "golang.org/x/net": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at //golang.org/x/net?go-get=1
get "google.golang.org/genproto": found meta tag get.metaImport{Prefix:"google.golang.org/genproto", VCS:"git", RepoRoot:"https://github.com/google/go-genproto"} at //google.golang.org/genproto?go-get=1
get "google.golang.org/appengine": found meta tag get.metaImport{Prefix:"google.golang.org/appengine", VCS:"git", RepoRoot:"https://github.com/golang/appengine"} at //google.golang.org/appengine?go-get=1
get "google.golang.org/api": found meta tag get.metaImport{Prefix:"google.golang.org/api", VCS:"git", RepoRoot:"https://code.googlesource.com/google-api-go-client"} at //google.golang.org/api?go-get=1
get "cloud.google.com/go": found meta tag get.metaImport{Prefix:"cloud.google.com/go", VCS:"git", RepoRoot:"https://code.googlesource.com/gocloud"} at //cloud.google.com/go?go-get=1
get "go.opencensus.io": found meta tag get.metaImport{Prefix:"go.opencensus.io", VCS:"git", RepoRoot:"https://github.com/census-instrumentation/opencensus-go"} at //go.opencensus.io/?go-get=1
get "gopkg.in/yaml.v2": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at //gopkg.in/yaml.v2?go-get=1
get "golang.org/x/sync": found meta tag get.metaImport{Prefix:"golang.org/x/sync", VCS:"git", RepoRoot:"https://go.googlesource.com/sync"} at //golang.org/x/sync?go-get=1
get "golang.org/x/tools": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at //golang.org/x/tools?go-get=1
get "honnef.co/go/tools": found meta tag get.metaImport{Prefix:"honnef.co/go/tools", VCS:"git", RepoRoot:"https://github.com/dominikh/go-tools"} at //honnef.co/go/tools?go-get=1
get "cloud.google.com/go/bigquery": found meta tag get.metaImport{Prefix:"cloud.google.com/go", VCS:"git", RepoRoot:"https://code.googlesource.com/gocloud"} at //cloud.google.com/go/bigquery?go-get=1
get "cloud.google.com/go/bigquery": verifying non-authoritative meta tag
get "golang.org/x/lint": found meta tag get.metaImport{Prefix:"golang.org/x/lint", VCS:"git", RepoRoot:"https://go.googlesource.com/lint"} at //golang.org/x/lint?go-get=1
get "golang.org/x/exp": found meta tag get.metaImport{Prefix:"golang.org/x/exp", VCS:"git", RepoRoot:"https://go.googlesource.com/exp"} at //golang.org/x/exp?go-get=1
get "golang.org/x/text": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at //golang.org/x/text?go-get=1
get "golang.org/x/image": found meta tag get.metaImport{Prefix:"golang.org/x/image", VCS:"git", RepoRoot:"https://go.googlesource.com/image"} at //golang.org/x/image?go-get=1
get "golang.org/x/mod": found meta tag get.metaImport{Prefix:"golang.org/x/mod", VCS:"git", RepoRoot:"https://go.googlesource.com/mod"} at //golang.org/x/mod?go-get=1
get "rsc.io/binaryregexp": found meta tag get.metaImport{Prefix:"rsc.io/binaryregexp", VCS:"git", RepoRoot:"https://github.com/rsc/binaryregexp"} at //rsc.io/binaryregexp?go-get=1
get "golang.org/x/time": found meta tag get.metaImport{Prefix:"golang.org/x/time", VCS:"git", RepoRoot:"https://go.googlesource.com/time"} at //golang.org/x/time?go-get=1
get "cloud.google.com/go/datastore": found meta tag get.metaImport{Prefix:"cloud.google.com/go", VCS:"git", RepoRoot:"https://code.googlesource.com/gocloud"} at //cloud.google.com/go/datastore?go-get=1
get "cloud.google.com/go/datastore": verifying non-authoritative meta tag
get "cloud.google.com/go/pubsub": found meta tag get.metaImport{Prefix:"cloud.google.com/go", VCS:"git", RepoRoot:"https://code.googlesource.com/gocloud"} at //cloud.google.com/go/pubsub?go-get=1
get "cloud.google.com/go/pubsub": verifying non-authoritative meta tag
get "golang.org/x/xerrors": found meta tag get.metaImport{Prefix:"golang.org/x/xerrors", VCS:"git", RepoRoot:"https://go.googlesource.com/xerrors"} at //golang.org/x/xerrors?go-get=1
get "golang.org/x/mobile": found meta tag get.metaImport{Prefix:"golang.org/x/mobile", VCS:"git", RepoRoot:"https://go.googlesource.com/mobile"} at //golang.org/x/mobile?go-get=1
get "gopkg.in/errgo.v2": found meta tag get.metaImport{Prefix:"gopkg.in/errgo.v2", VCS:"git", RepoRoot:"https://gopkg.in/errgo.v2"} at //gopkg.in/errgo.v2?go-get=1
go: downloading github.com/urfave/cli v1.22.1
go: downloading github.com/fatih/color v1.7.0
go: downloading google.golang.org/api v0.10.0
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/aws/aws-sdk-go v1.25.7
go: downloading github.com/dutchcoders/transfer.sh-web v0.0.0-20190716184912-96e06a2276ba
go: downloading github.com/PuerkitoBio/ghost v0.0.0-20160324114900-206e6e460e14
go: extracting github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/microcosm-cc/bluemonday v1.0.2
go: downloading golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
go: downloading github.com/tomasen/realip v0.0.0-20180522021738-f0c99a92ddce
go: extracting github.com/urfave/cli v1.22.1
go: extracting github.com/tomasen/realip v0.0.0-20180522021738-f0c99a92ddce
go: extracting github.com/microcosm-cc/bluemonday v1.0.2
go: extracting github.com/PuerkitoBio/ghost v0.0.0-20160324114900-206e6e460e14
go: extracting golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
go: downloading github.com/VojtechVitek/ratelimit v0.0.0-20160722140851-dc172bc0f6d2
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: extracting github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading github.com/dutchcoders/go-clamd v0.0.0-20170520113014-b970184f4d9e
go: extracting github.com/VojtechVitek/ratelimit v0.0.0-20160722140851-dc172bc0f6d2
go: downloading github.com/golang/gddo v0.0.0-20190904175337-72a348e765d2
go: extracting github.com/dutchcoders/go-clamd v0.0.0-20170520113014-b970184f4d9e
go: downloading golang.org/x/net v0.0.0-20191007182048-72f939374954
go: extracting github.com/fatih/color v1.7.0
go: extracting github.com/golang/gddo v0.0.0-20190904175337-72a348e765d2
go: extracting golang.org/x/net v0.0.0-20191007182048-72f939374954
go: downloading github.com/skip2/go-qrcode v0.0.0-20190110000554-dc11ecdae0a9
go: extracting github.com/skip2/go-qrcode v0.0.0-20190110000554-dc11ecdae0a9
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading github.com/garyburd/redigo v1.6.0
go: extracting github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading github.com/gorilla/mux v1.7.3
go: extracting github.com/garyburd/redigo v1.6.0
go: extracting github.com/gorilla/mux v1.7.3
go: downloading github.com/dutchcoders/go-virustotal v0.0.0-20140923143438-24cc8e6fa329
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0
go: extracting github.com/dutchcoders/go-virustotal v0.0.0-20140923143438-24cc8e6fa329
go: extracting github.com/cpuguy83/go-md2man/v2 v2.0.0
go: downloading github.com/mattn/go-isatty v0.0.9
go: downloading google.golang.org/appengine v1.6.4
go: extracting github.com/mattn/go-isatty v0.0.9
go: downloading golang.org/x/crypto v0.0.0-20191002192127-34f69633bfdc
go: extracting github.com/dutchcoders/transfer.sh-web v0.0.0-20190716184912-96e06a2276ba
go: extracting google.golang.org/appengine v1.6.4
go: downloading github.com/gorilla/securecookie v1.1.1
go: extracting github.com/gorilla/securecookie v1.1.1
go: downloading github.com/golang/protobuf v1.3.2
go: extracting github.com/golang/protobuf v1.3.2
go: downloading cloud.google.com/go v0.46.3
go: extracting golang.org/x/crypto v0.0.0-20191002192127-34f69633bfdc
go: downloading golang.org/x/sys v0.0.0-20191007154456-ef33b2fb2c41
go: extracting cloud.google.com/go v0.46.3
go: extracting golang.org/x/sys v0.0.0-20191007154456-ef33b2fb2c41
go: downloading github.com/mattn/go-colorable v0.1.4
go: extracting github.com/mattn/go-colorable v0.1.4
go: downloading github.com/nu7hatch/gouuid v0.0.0-20131221200532-179d4d0c4d8d
go: extracting github.com/nu7hatch/gouuid v0.0.0-20131221200532-179d4d0c4d8d
go: downloading golang.org/x/text v0.3.2
go: extracting golang.org/x/text v0.3.2
go: extracting github.com/aws/aws-sdk-go v1.25.7
go: extracting google.golang.org/api v0.10.0
go: downloading google.golang.org/grpc v1.24.0
go: downloading github.com/googleapis/gax-go/v2 v2.0.5
go: downloading go.opencensus.io v0.22.1
go: extracting github.com/googleapis/gax-go/v2 v2.0.5
go: extracting go.opencensus.io v0.22.1
go: downloading github.com/golang/groupcache v0.0.0-20191002201903-404acd9df4cc
go: extracting github.com/golang/groupcache v0.0.0-20191002201903-404acd9df4cc
go: extracting google.golang.org/grpc v1.24.0
go: downloading google.golang.org/genproto v0.0.0-20191007162740-aa923e3a3354
go: downloading github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
go: extracting github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
go: extracting google.golang.org/genproto v0.0.0-20191007162740-aa923e3a3354
go: finding github.com/fatih/color v1.7.0
go: finding github.com/urfave/cli v1.22.1
go: finding google.golang.org/api v0.10.0
go: finding github.com/mattn/go-colorable v0.1.4
go: finding github.com/mattn/go-isatty v0.0.9
go: finding github.com/PuerkitoBio/ghost v0.0.0-20160324114900-206e6e460e14
go: finding github.com/cpuguy83/go-md2man/v2 v2.0.0
go: finding github.com/VojtechVitek/ratelimit v0.0.0-20160722140851-dc172bc0f6d2
go: finding github.com/aws/aws-sdk-go v1.25.7
go: finding github.com/russross/blackfriday/v2 v2.0.1
go: finding github.com/dutchcoders/go-clamd v0.0.0-20170520113014-b970184f4d9e
go: finding github.com/dutchcoders/transfer.sh-web v0.0.0-20190716184912-96e06a2276ba
go: finding github.com/dutchcoders/go-virustotal v0.0.0-20140923143438-24cc8e6fa329
go: finding github.com/elazarl/go-bindata-assetfs v1.0.0
go: finding github.com/garyburd/redigo v1.6.0
go: finding github.com/gorilla/securecookie v1.1.1
go: finding github.com/golang/gddo v0.0.0-20190904175337-72a348e765d2
go: finding github.com/nu7hatch/gouuid v0.0.0-20131221200532-179d4d0c4d8d
go: finding github.com/gorilla/mux v1.7.3
go: finding github.com/shurcooL/sanitized_anchor_name v1.0.0
go: finding github.com/microcosm-cc/bluemonday v1.0.2
go: finding github.com/skip2/go-qrcode v0.0.0-20190110000554-dc11ecdae0a9
go: finding github.com/tomasen/realip v0.0.0-20180522021738-f0c99a92ddce
go: finding github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
go: finding golang.org/x/crypto v0.0.0-20191002192127-34f69633bfdc
go: finding golang.org/x/net v0.0.0-20191007182048-72f939374954
go: finding golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
go: finding cloud.google.com/go v0.46.3
go: finding go.opencensus.io v0.22.1
go: finding golang.org/x/text v0.3.2
go: finding google.golang.org/grpc v1.24.0
go: finding github.com/googleapis/gax-go/v2 v2.0.5
go: finding github.com/golang/groupcache v0.0.0-20191002201903-404acd9df4cc
go: finding github.com/golang/protobuf v1.3.2
go: finding google.golang.org/genproto v0.0.0-20191007162740-aa923e3a3354
github.com/aws/aws-sdk-go/aws/client/metadata
github.com/aws/aws-sdk-go/internal/sdkmath
golang.org/x/net/html/atom
github.com/shurcooL/sanitized_anchor_name
github.com/golang/groupcache/lru
go.opencensus.io
go.opencensus.io/trace/internal
go.opencensus.io/internal/tagencoding
github.com/garyburd/redigo/internal
github.com/VojtechVitek/ratelimit/memory
github.com/aws/aws-sdk-go/internal/sdkio
github.com/aws/aws-sdk-go/internal/sdkrand
github.com/aws/aws-sdk-go/internal/sdkuri
github.com/PuerkitoBio/ghost
github.com/nu7hatch/gouuid
github.com/gorilla/securecookie
github.com/aws/aws-sdk-go/aws/awserr
github.com/aws/aws-sdk-go/internal/shareddefaults
github.com/garyburd/redigo/redis
github.com/aws/aws-sdk-go/internal/ini
github.com/aws/aws-sdk-go/aws/endpoints
github.com/VojtechVitek/ratelimit
github.com/jmespath/go-jmespath
github.com/aws/aws-sdk-go/aws/credentials
github.com/aws/aws-sdk-go/aws/credentials/processcreds
github.com/dutchcoders/go-clamd
github.com/dutchcoders/go-virustotal
github.com/PuerkitoBio/ghost/handlers
github.com/aws/aws-sdk-go/aws/awsutil
github.com/dutchcoders/transfer.sh-web
github.com/elazarl/go-bindata-assetfs
github.com/golang/gddo/httputil/header
github.com/gorilla/mux
golang.org/x/net/html
github.com/russross/blackfriday/v2
github.com/skip2/go-qrcode/bitset
github.com/skip2/go-qrcode/reedsolomon
github.com/skip2/go-qrcode
github.com/tomasen/realip
golang.org/x/crypto/acme
golang.org/x/text/transform
golang.org/x/text/unicode/bidi
golang.org/x/text/unicode/norm
github.com/microcosm-cc/bluemonday
golang.org/x/text/secure/bidirule
golang.org/x/net/context
golang.org/x/net/context/ctxhttp
cloud.google.com/go/compute/metadata
golang.org/x/oauth2/internal
golang.org/x/oauth2
golang.org/x/oauth2/jws
golang.org/x/net/internal/timeseries
golang.org/x/oauth2/jwt
golang.org/x/net/trace
golang.org/x/oauth2/google
google.golang.org/grpc/grpclog
google.golang.org/grpc/connectivity
github.com/golang/protobuf/proto
google.golang.org/grpc/credentials/internal
google.golang.org/grpc/internal
google.golang.org/grpc/metadata
golang.org/x/net/idna
google.golang.org/grpc/serviceconfig
google.golang.org/grpc/resolver
google.golang.org/grpc/internal/grpcrand
google.golang.org/grpc/codes
google.golang.org/grpc/encoding
google.golang.org/grpc/internal/backoff
google.golang.org/grpc/internal/balancerload
google.golang.org/grpc/internal/envconfig
google.golang.org/grpc/internal/grpcsync
golang.org/x/net/http2/hpack
golang.org/x/crypto/acme/autocert
golang.org/x/net/http/httpguts
golang.org/x/net/http2
google.golang.org/grpc/internal/syscall
google.golang.org/grpc/keepalive
google.golang.org/grpc/stats
google.golang.org/grpc/tap
google.golang.org/grpc/naming
google.golang.org/grpc/resolver/dns
google.golang.org/grpc/resolver/passthrough
google.golang.org/api/googleapi/internal/uritemplates
google.golang.org/api/googleapi
go.opencensus.io/internal
go.opencensus.io/trace/tracestate
go.opencensus.io/trace
go.opencensus.io/trace/propagation
go.opencensus.io/plugin/ochttp/propagation/b3
go.opencensus.io/resource
go.opencensus.io/metric/metricdata
go.opencensus.io/tag
go.opencensus.io/stats/internal
go.opencensus.io/stats
go.opencensus.io/metric/metricproducer
go.opencensus.io/stats/view
go.opencensus.io/plugin/ochttp
google.golang.org/api/googleapi/transport
google.golang.org/api/transport/http/internal/propagation
github.com/mattn/go-isatty
github.com/mattn/go-colorable
github.com/fatih/color
google.golang.org/grpc/credentials
google.golang.org/grpc/encoding/proto
google.golang.org/grpc/balancer
github.com/golang/protobuf/ptypes/any
github.com/golang/protobuf/ptypes/duration
google.golang.org/grpc/balancer/base
github.com/golang/protobuf/ptypes/timestamp
google.golang.org/grpc/balancer/roundrobin
google.golang.org/genproto/googleapis/rpc/status
github.com/golang/protobuf/ptypes
google.golang.org/grpc/binarylog/grpc_binarylog_v1
google.golang.org/grpc/internal/channelz
google.golang.org/grpc/status
google.golang.org/grpc/peer
google.golang.org/grpc/internal/binarylog
github.com/cpuguy83/go-md2man/v2/md2man
github.com/urfave/cli
google.golang.org/grpc/internal/transport
github.com/aws/aws-sdk-go/aws
github.com/aws/aws-sdk-go/private/protocol/eventstream
github.com/aws/aws-sdk-go/aws/request
github.com/aws/aws-sdk-go/aws/corehandlers
github.com/aws/aws-sdk-go/aws/client
github.com/aws/aws-sdk-go/private/protocol
github.com/aws/aws-sdk-go/aws/csm
github.com/aws/aws-sdk-go/private/protocol/rest
github.com/aws/aws-sdk-go/private/protocol/query/queryutil
github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil
github.com/aws/aws-sdk-go/aws/signer/v4
github.com/aws/aws-sdk-go/aws/ec2metadata
github.com/aws/aws-sdk-go/private/protocol/query
github.com/aws/aws-sdk-go/private/protocol/json/jsonutil
github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds
github.com/aws/aws-sdk-go/service/sts
github.com/aws/aws-sdk-go/internal/s3err
github.com/aws/aws-sdk-go/private/protocol/eventstream/eventstreamapi
github.com/aws/aws-sdk-go/private/protocol/restxml
github.com/aws/aws-sdk-go/aws/credentials/endpointcreds
github.com/aws/aws-sdk-go/service/s3
github.com/aws/aws-sdk-go/aws/defaults
github.com/aws/aws-sdk-go/service/sts/stsiface
github.com/aws/aws-sdk-go/aws/credentials/stscreds
google.golang.org/grpc
github.com/aws/aws-sdk-go/aws/session
google.golang.org/api/internal
github.com/googleapis/gax-go/v2
google.golang.org/api/gensupport
google.golang.org/api/option
google.golang.org/api/transport/http
google.golang.org/api/drive/v3
github.com/aws/aws-sdk-go/service/s3/s3iface
github.com/aws/aws-sdk-go/service/s3/s3manager
github.com/dutchcoders/transfer.sh/server
github.com/dutchcoders/transfer.sh/cmd
github.com/dutchcoders/transfer.sh
</pre>

### What did you see instead?
<pre>
go: finding github.com/dutchcoders/transfer.sh v1.1.2
go: downloading github.com/dutchcoders/transfer.sh v1.1.2
go: extracting github.com/dutchcoders/transfer.sh v1.1.2
get "google.golang.org/api": found meta tag get.metaImport{Prefix:"google.golang.org/api", VCS:"git", RepoRoot:"https://code.googlesource.com/google-api-go-client"} at //google.golang.org/api?go-get=1
get "gopkg.in/check.v1": found meta tag get.metaImport{Prefix:"gopkg.in/check.v1", VCS:"git", RepoRoot:"https://gopkg.in/check.v1"} at //gopkg.in/check.v1?go-get=1
get "gopkg.in/russross/blackfriday.v2": found meta tag get.metaImport{Prefix:"gopkg.in/russross/blackfriday.v2", VCS:"git", RepoRoot:"https://gopkg.in/russross/blackfriday.v2"} at //gopkg.in/russross/blackfriday.v2?go-get=1
get "golang.org/x/net": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at //golang.org/x/net?go-get=1
get "gopkg.in/yaml.v2": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at //gopkg.in/yaml.v2?go-get=1
get "golang.org/x/oauth2": found meta tag get.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at //golang.org/x/oauth2?go-get=1
get "golang.org/x/crypto": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at //golang.org/x/crypto?go-get=1
get "google.golang.org/appengine": found meta tag get.metaImport{Prefix:"google.golang.org/appengine", VCS:"git", RepoRoot:"https://github.com/golang/appengine"} at //google.golang.org/appengine?go-get=1
get "golang.org/x/sys": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at //golang.org/x/sys?go-get=1
get "golang.org/x/sync": found meta tag get.metaImport{Prefix:"golang.org/x/sync", VCS:"git", RepoRoot:"https://go.googlesource.com/sync"} at //golang.org/x/sync?go-get=1
get "golang.org/x/lint": found meta tag get.metaImport{Prefix:"golang.org/x/lint", VCS:"git", RepoRoot:"https://go.googlesource.com/lint"} at //golang.org/x/lint?go-get=1
get "honnef.co/go/tools": found meta tag get.metaImport{Prefix:"honnef.co/go/tools", VCS:"git", RepoRoot:"https://github.com/dominikh/go-tools"} at //honnef.co/go/tools?go-get=1
get "golang.org/x/text": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at //golang.org/x/text?go-get=1
get "google.golang.org/grpc": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc?go-get=1
get "golang.org/x/tools": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at //golang.org/x/tools?go-get=1
get "cloud.google.com/go": found meta tag get.metaImport{Prefix:"cloud.google.com/go", VCS:"git", RepoRoot:"https://code.googlesource.com/gocloud"} at //cloud.google.com/go?go-get=1
get "google.golang.org/genproto": found meta tag get.metaImport{Prefix:"google.golang.org/genproto", VCS:"git", RepoRoot:"https://github.com/google/go-genproto"} at //google.golang.org/genproto?go-get=1
get "go.opencensus.io": found meta tag get.metaImport{Prefix:"go.opencensus.io", VCS:"git", RepoRoot:"https://github.com/census-instrumentation/opencensus-go"} at //go.opencensus.io/?go-get=1
get "golang.org/x/time": found meta tag get.metaImport{Prefix:"golang.org/x/time", VCS:"git", RepoRoot:"https://go.googlesource.com/time"} at //golang.org/x/time?go-get=1
get "golang.org/x/exp": found meta tag get.metaImport{Prefix:"golang.org/x/exp", VCS:"git", RepoRoot:"https://go.googlesource.com/exp"} at //golang.org/x/exp?go-get=1
go get: github.com/dutchcoders/transfer.sh@v1.1.2 requires
	gopkg.in/russross/blackfriday.v2@v2.0.1: go.mod has non-....v2 module path "github.com/russross/blackfriday/v2" at revision v2.0.
</pre>

**Comment by jayconrod** [comment]
It's expected that the two commands have different behaviors. The arguments to `go get` are package paths or patterns with `...` wildcards that match packages.

`go get -v github.com/dutchcoders/transfer.sh` will upgrade the module that provides the package `github.com/dutchcoders/transfer.sh` to the latest version, adding missing module requirements as needed. It doesn't consider other packages in that module.

`go get ./...` when run within `github.com/dutchcoders/transfer.sh` will attempt to update packages in the main module. You can't get a newer version of the main module, so the packages themselves won't be updated, but this command may still add missing module requirements.

See [`go help module-get`](https://golang.org/cmd/go/#hdr-Add_dependencies_to_current_module_and_install_them) for more information.

**Comment by jayconrod** [comment]
It looks like the cause of the error is that `github.com/dutchcoders/transfer.sh@v1.1.2` requires `blackfriday` with the wrong module path. It should be `github.com/russross/blackfriday/v2` (matching the module path declared in `blackfriday`'s `go.mod` file.

`transfer.sh` has the following `replace` directive which may be needed to work around this:

```
replace gopkg.in/russross/blackfriday.v2 v2.0.1 => github.com/russross/blackfriday/v2 v2.0.1
```

**Comment by aspacca** [comment]
@jayconrod thanks, I missed the fact that in v1.1.2 I still had the `replace` directive that I had to remove due to https://github.com/golang/go/issues/33154, using directly the `import` path github.com/russross/blackfriday/v2
