### ISSUE TITLE
gccgo: encoding/binary not working as expected

### ISSUE THREAD

**Issue by zhsj** [golang/go#36404]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.12.2 gccgo (Debian 9.2.1-21) 9.2.1 20191130 linux/amd64

and

go version go1.13 gccgo (Debian 10-20200104-1) 10.0.0 20200104 (experimental) [trunk revision 279880] linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/zhsj/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/zhsj/go"
GOPROXY="https://proxy.golang.org"
GORACE=""
GOROOT="/usr"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/gcc/x86_64-linux-gnu/9"
GCCGO="/usr/bin/x86_64-linux-gnu-gccgo-9"
CC="x86_64-linux-gnu-gcc-9"
CXX="x86_64-linux-gnu-g++-9"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build329180695=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
</pre></details>

### What did you do?

https://play.golang.org/p/hTE_ESoFu9Z

### What did you expect to see?

same output as gc, print

```
14 <nil>
10 <nil>
```

### What did you see instead?

go-9
```
e0 <nil>
48 EOF
```

go-10
```
00 <nil>
0 <nil>
```

**Comment by ianlancetaylor** [comment]
CC @cherrymui 

This looks like an escape analysis problem.  For some reason the Go frontend thinks that the underlying array of `iEncoded` does not escape from `encodeInt`.  Compiling with `-fgo-debug-escape1` I see

```
/home/iant/foo.go:21:17: note: encodeInt &(buf) does not escape
   21 |   iEncoded = buf[:]
      |                 ^
```

**Comment by cherrymui** [comment]
Thanks. It is indeed an escape analysis bug. The problem is how we handle slicing an array. In the gc compiler, slicing an array is represented in AST with an implicit OADDR node. In gccgo AST, it doesn't have that node. The escape analysis is already inserting a fake node for an & operation, but the "loop depth" is not computed correctly for that node. I'm working on a CL.

**Comment by ianlancetaylor** [comment]
Thanks for reporting the bug.  This should now be fixed on GCC tip and GCC 9 branch.
