### ISSUE TITLE
Cannot embed icon to PE file in linux

### ISSUE THREAD

**Issue by jominyor** [golang/go#36406]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/us/.cache/go-build"
GOENV="/home/us/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/us/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build934510905=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I'm trying to build windows executable file from linux. This is working without problem. Where problems comes in is when I try to embed an icon file.

I've created syso file. With that syso file, I can build my application in windows with icon. But in linux, when I use command `$ env GOOS=windows GOARCH=386 go build main.go` it generates PE file but there is no icon in it. I've double checked it on linux and windows. There is surely no icon. Is this because compiler only embeds an icon file on windows environment? 

### What did you expect to see?
PE file with icon.

### What did you see instead?
PE file without icon.

**Comment by ianlancetaylor** [comment]
You  probably need to set the environment variable `CGO_ENABLED=1` when cross-compiling.  This will require you to have a GNU/Linux -> Windows cross-compiler installed, with `CC` set to the cross-compiler.
