### ISSUE TITLE
Float Multiplication Inaccuracy

### ISSUE THREAD

**Issue by Arman-ak** [golang/go#36418]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.13.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
</pre></details>

### What did you do?
float64(10.12) * float64(10000)

For more examples...
https://play.golang.org/p/3UB-bhOVR8m

### What did you expect to see?
Expected: 101200

### What did you see instead?
Received: 101199.99999999999

**Comment by ianlancetaylor** [comment]
Please read https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html.

**Comment by Arman-ak** [comment]
Thank you.
