### ISSUE TITLE
x/tools/gopls: support ad-hoc packages with multiple files

### ISSUE THREAD

**Issue by Wingboy-Jim2** [golang/go#36416]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Jim\AppData\Local\go-build
set GOENV=C:\Users\Jim\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Jim\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Jim\AppData\Local\Temp\go-build664791186=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I started up VS Code on a directory.  There was a single package (main) spread across multiple files.  There was no go.mod file.

When looking at a file VS Code displayed multiple undeclared name errors for the current file.  

Although true that the current file does not declare that names these names were declared in other files in the same directory.

Exiting VS Code and doing a go build in the directory builds with no errors.  But entering  back into VS Code shows errors for any file that I view in the editor.

### What did you expect to see?
No errors

### What did you see instead?
Errors for undeclared names.  I get the same errors when do a gopls check on any file.

Creating a go.mod file addresses this, even if I do a gopls check on a single file.

First submitted this as a https://github.com/microsoft/vscode-go/issues/2967 before I determined that gopls seemed to be the involved.

**Comment by stamblerre** [comment]
@Wingboy-Jim2: It sounds like you are working outside of GOPATH and without modules. `gopls` will only partially work in that case, since that set up is considered "ad-hoc". It seems like the correct solution in your case is to initialize a module, as you did by adding a `go.mod` file.

**Comment by Wingboy-Jim2** [comment]
What was a pain was that I have been working in such an _ad hoc_ means for over two and a half years without any consequences.

I have not seen any reason not to initialize a module, but it would have saved me a few hours of research and aggravation if the change in requirements had been more clearly presented.  At the very least I hope that this ticket will reduce the time for anyone else functioning in such a fashion.

**Comment by stamblerre** [comment]
The recommendation to use GOPATH is pretty common in Go documentation (for example, https://golang.org/doc/install#testing), and this specific issue with `gopls` has been discussed on a number of issues, including https://github.com/golang/go/issues/33729#issuecomment-544292825. [CL 202277](https://go-review.googlesource.com/c/tools/+/202277) will add support for ad-hoc packages with multiple files, but I agree that, in the meantime, we should make the error messaging more clear. I will mail a CL to show a warning message.

**Comment by stamblerre** [comment]
@Wingboy-Jim2: This will work as you expect in `gopls/v0.3.0` (you can try it out now by running `GO111MODULE=on go get golang.org/x/tools/gopls@v0.3.0-pre3`).

Leaving this issue open, as the fix should still be made in `go/packages`.

**Comment by stamblerre** [comment]
As discussed on the above CL, the additional work-arounds in go/packages are not worth the complexity, particularly since this issue has now been addressed in `gopls`. Closing as a result.
