### ISSUE TITLE
cmd/compile: unnecessary duplicate error

### ISSUE THREAD

**Issue by rsc** [golang/go#36410]
```
$ cat /tmp/x.go
package p
import "fmt"
var _ = fmt.printf
$ go tool compile /tmp/x.go
/tmp/x.go:3:9: cannot refer to unexported name fmt.printf
/tmp/x.go:3:9: undefined: fmt.printf
$ 
```

The first error is great. The second error should be omitted.

/cc @griesemer

**Comment by cuonglm** [comment]
`go/types` reports only one, but different error message `printf not declared by package fmt`

**Comment by ALTree** [comment]
This is a dup of #22921, which is already assigned to gri. Closing here.
