### ISSUE TITLE
impossible to create my own package with name "select"

### ISSUE THREAD

**Issue by ruzhnikov** [golang/go#36426]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/noize/.cache/go-build"
GOENV="/home/noize/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/noize/development/golang"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/golang/current"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/golang/current/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build471221178=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
1. Go to GOPATH/src and create my own directory
```bash
$ cd $GOPATH/src
$ mkdir -p noize/my/data/
$ cd noize/my/data
$ mkdir select insert && cd select
$ touch select.go && vim select.go
```
write to select.go content:
```go
package select

type Data struct {
    A int
}
```
then, run go fmt or go install:
```bash
$ go fmt .
can't load package: package noize/my/data/select: 
select.go:1:9: expected 'IDENT', found 'select'
select.go:2:2: expected ';', found 'EOF'
$ go install
can't load package: package noize/my/data/select: 
select.go:1:9: expected 'IDENT', found 'select'
select.go:2:2: expected ';', found 'EOF'
```

### What did you expect to see?
I expected to see nothing as normal result of go tools working

### What did you see instead?
can't load package: package noize/my/data/select: 
select.go:1:9: expected 'IDENT', found 'select'
select.go:2:2: expected ';', found 'EOF'

**Comment by ruzhnikov** [comment]
Additionally, if I create the same content in a package noize/my/data/insert/insert.go, everything is ok:
```bash
$ cd $GOPATH/src/noize/my/data/insert
$ touch insert.go && vim insert.go
```
fill the file:
```go
package insert

type Data struct {
	A int
}
```
and run go tools
```bash
$ go fmt insert.go
$ go install
$ echo $?
0
```

**Comment by lutzhorn** [comment]
[`select` is a keyword`](https://golang.org/ref/spec#Keywords).

**Comment by ruzhnikov** [comment]
> [`select` is a keyword](https://golang.org/ref/spec#Keywords).

right, but I always thought that is only connected with variable types and names, not with packages. Maybe it worth to explain this point more clearly.

**Comment by lutzhorn** [comment]
You thought wrong. See https://golang.org/ref/spec#Package_clause
