### ISSUE TITLE
cmd/go: pager for go help

### ISSUE THREAD

**Issue by b10s** [golang/go#36424]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.13.4 linux/amd64
</pre>

`go help` has no pager as `less` is.
E.g. `go help build` prints out all doc into terminal and I have to scroll.
E.g. `perldoc -f print` or `man print` behave as I would `go help`

What do you think about it? Or maybe I did something wrong ?

**Comment by myitcv** [comment]
This has been raised previously: https://github.com/golang/go/issues/14336

I'm not clear there's been a change in the conclusions in that issue.

**Comment by ianlancetaylor** [comment]
Closing as dup of #14336.  May as well keep the discussion in one place.  Thanks.
