### ISSUE TITLE
Export constants secondsPerMinute, secondsPerHour, secondsPerDay etc. from package "time"

### ISSUE THREAD

**Issue by Cosmopolitan-Flier** [golang/go#36432]
### What version of Go are you using (`1.13`)?

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Any

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Tried to use constants from package "time":
const (
	secondsPerMinute = 60
	secondsPerHour   = 60 * secondsPerMinute
	secondsPerDay    = 24 * secondsPerHour
	secondsPerWeek   = 7 * secondsPerDay
	daysPer400Years  = 365*400 + 97
	daysPer100Years  = 365*100 + 24
	daysPer4Years    = 365*4 + 1
)

These constants are useful but they are not exported. As a result, users have to re-define them in their application code.

import (
    "time"
)

### What did you expect to see?

When these constants are exported, application developers can use them instead of re-defining them.

### What did you see instead?

Inability to use these constants.

**Comment by bradfitz** [comment]
Sorry, but this would be unnecessary API burden (godoc for users to need to skim past) for limited use.

These are trivial to redefine or copy/paste for those who need them.

**Comment by ianlancetaylor** [comment]
Also `secondsPerDay` and seconds per any larger unit is ambiguous due to daylight savings time transitions.  They can be used but only with care.
