### ISSUE TITLE
cmd/compile: error points to nonexistent file

### ISSUE THREAD

**Issue by rsc** [golang/go#36437]
The `x.go:0:` here does not make much sense given that x.go does not exist.
It seems like it should be omitted, no?

```
$ go tool compile x.go
x.go:0: open x.go: no such file or directory
```

/cc @griesemer

**Comment by griesemer** [comment]
Agreed.

**Comment by tandr** [comment]
Curious - how many scripts/tools that parse compiler output and rely on the line start being `file:linenumber` will need to be modified?
There is no way to get structured output from the compiler (say, for example --json, that would produce all errors and warnings in a nicely parseable structured format). So tools are relying on compiler output parsing.

**Comment by beoran** [comment]
FWIW, Geany has no problems with either the current behavior or the proposed `x.go: open x.go: no such file or directory` message. There's no file to open anyway. So I guess most other editors will be ok if they have smart enough compiler output parsers.
