### ISSUE TITLE
The string will have a redundant '\x00' when write this string to a file, then read it out 

### ISSUE THREAD

**Issue by JLLNANA** [golang/go#36446]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/bin"
GOCACHE="/Users/XXX/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/XXX/.gvm/pkgsets/go1.12/global"
GOPROXY=""
GORACE=""
GOROOT="/Users/XXX/.gvm/gos/go1.12"
GOTMPDIR=""
GOTOOLDIR="/Users/XXX/.gvm/gos/go1.12/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gk/4r9kl42d28gf7y9nh792stz1y8l16_/T/go-build899530892=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

	f, err := os.Create("/tmp/test.json")
	if err != nil {
		return nil, nil, err
	}
	w := bufio.NewWriter(f)
        str := "hello"
	w.Write([]byte(str))
	w.Flush()
	f.Close()
	path := f.Name()
	fileOpen, _ := os.Open(path)
	defer fileOpen.Close()
	w := bufio.NewReader(fileOpen)
	var dataByte []byte
	for {
		byte, err := w.ReadByte()
		dataByte = append(dataByte, byte)
		if err == io.EOF {
			break
		}
	}

fmt.Printf("content read from file is:%s\n , len is: %d\n", string(dataByte), len(string(dataByte)))
### What did you expect to see?
hello, 5

### What did you see instead?
hello with a special char which is '\x00' 
and length is 6
It seems there is a '\x00' has been added to the end of the file when w.Flush
If cat the test.json, you can see
hello%

**Comment by juxuny** [comment]
Maybe you should break the loop before `append`

**Comment by juxuny** [comment]
When `w.ReadByte()` returned an error, `byte` will always be assigned as the default value of byte.

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
