### ISSUE TITLE
x/build: freebsd-amd64-race builder is failing consistently on golang.org/x/tools repo

### ISSUE THREAD

**Issue by dmitshur** [golang/go#36444]
The linux-amd64-race builder is currently configured with 15 GB RAM (via the n1-standard-4 machine type). [CL 213557](https://golang.org/cl/213557) has recently increased the RAM for windows-amd64-race builder to 14.4 GB in order to work around 7.2 GB not being sufficient, as described at https://github.com/golang/go/issues/35186#issuecomment-571438725.

The `freebsd-amd64-race` builder is currently configured to use the `n1-highcpu-4` machine type, which has 3.6 GB RAM. The `freebsd-amd64-race` builder is failing quite often, which may be connected to insufficient memory:

<details><br>

```
signal: killed
FAIL	golang.org/x/tools/go/packages	217.792s
```

```
*** Test killed with quit: ran too long (10m0s).
FAIL	golang.org/x/tools/internal/imports	600.067s
```

```
panic: test timed out after 10m0s
[...]
FAIL	golang.org/x/tools/go/packages	611.592s
```

```
[...]
	package = golang.org/x/tools/internal/lsp/protocol
2020/01/07 18:44:29 Error:2020/01/07 18:44:29 no dep handle: no metadata for golang.org/x/xerrors
	package = golang.org/x/xerrors
2020/01/07 18:44:35 no dep handle: no metadata for golang.org/x/tools/internal/lsp/protocol
	package = golang.org/x/tools/internal/lsp/protocol
2020/01/07 18:44:35 Error:2020/01/07 18:44:35 no dep handle: no metadata for golang.org/x/tools/internal/lsp/protocol
	package = golang.org/x/tools/internal/lsp/protocol
2020/01/07 18:44:36 no dep handle: no metadata for golang.org/x/xerrors
	package = golang.org/x/xerrors
2020/01/07 18:44:36 Error:2020/01/07 18:44:36 no dep handle: no metadata for golang.org/x/xerrors
	package = golang.org/x/xerrors
2020/01/07 18:44:42 no dep handle: no metadata for golang.org/x/xerrors
	package = golang.org/x/xerrors
2020/01/07 18:44:43 Error:2020/01/07 18:44:42 no dep handle: no metadata for golang.org/x/xerrors
	package = golang.org/x/xerrors
--- FAIL: TestCommandLine (240.28s)
    --- FAIL: TestCommandLine/Modules (194.21s)
        --- FAIL: TestCommandLine/Modules/Diagnostics (159.73s)
            --- FAIL: TestCommandLine/Modules/Diagnostics/testy_test (151.73s)
                check.go:62: missing diagnostic "testy/testy_test.go:6:6: x declared but not used", map[]
FAIL
FAIL	golang.org/x/tools/internal/lsp/cmd	240.922s
```

```
2020/01/07 20:54:34 no dep handle: no metadata for nosuchpkg
	package = nosuchpkg
2020/01/07 20:54:51 no dep handle: no metadata for golang.org/x/tools/internal/lsp/protocol
	package = golang.org/x/tools/internal/lsp/protocol
2020/01/07 20:54:51 no dep handle: no metadata for golang.org/x/xerrors
	package = golang.org/x/xerrors
FAIL	golang.org/x/tools/internal/lsp/source	246.068s
```

</details>

If there aren't objections, I plan to bump its up RAM to be more similar in size (without exceeding the current value of 15 GB RAM used both by Linux and now Windows -race builders) to see it helps with the test failures and issues like #34621.

/cc @bradfitz @bcmills @matloob @toothrot

**Comment by dmitshur** [comment]
[CL 214433](https://golang.org/cl/214433) was deployed this morning, and the freebsd-amd64-race builder has been passing on x/tools since then:

<img src="https://user-images.githubusercontent.com/1924134/72377170-40241400-36dd-11ea-9a59-7782db8a9c9d.png" width=111px>

I'll give it more time to gather more data, and close this issue if the reliable build results continue.

**Comment by dmitshur** [comment]
The freebsd-amd64-race builder no longer failing consistently on x/tools. However, there are still occasional failures. Need to see if they are connected to limited memory, and if so, consider going up to 15 GB on the FreeBSD race builder to match the memory of Linux and Windows race builders.

**Comment by bcmills** [comment]
The failures in https://build.golang.org/log/74eea9d200fd346319a2595c2f2b2ab3f25c2a07 appear to be due to timeouts rather than data races, although it is possible that a data race failure is being masked by failure to propagate logs somewhere higher up the stack.

**Comment by dmitshur** [comment]
> I'll give it more time to gather more data, and close this issue if the reliable build results continue.

I think the build results are reliable, keeping the specific issues mentioned above in mind.

![image](https://user-images.githubusercontent.com/1924134/78688833-aaef8080-78c3-11ea-894b-44a21b416230.png)

I'll close this since the original issue is resolved, and we can follow up with more specific issues as needed.

**Comment by dmitshur** [comment]
Whoops, I misread the issue and missed the "x/tools" prefix, thinking it was about the main Go repository.

This is still a problem for x/tools:

https://build.golang.org/?repo=golang.org%2fx%2ftools

![image](https://user-images.githubusercontent.com/1924134/78689604-85af4200-78c4-11ea-9422-4785996f8024.png)

I'll re-open and look into this more later.

**Comment by dmitshur** [comment]
[CL 227859](https://golang.org/cl/227859) has been deployed earlier today. The freebsd-amd64-race builder has started to pass on x/tools:

<img width=80 src=https://user-images.githubusercontent.com/1924134/79027803-a644f980-7b5b-11ea-9e2a-8cffe2cde9fd.png>

I'll consider this resolved. If something unexpected comes up, we can re-open this issue or file a new one.
