### ISSUE TITLE
x/tools/gopls: cannot find package error while installing 

### ISSUE THREAD

**Issue by Fuxxel** [golang/go#36442]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build663267071=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.13.5 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.13.5
uname -sr: Linux 4.9.184-linuxkit
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Debian GLIBC 2.28-10) stable release version 2.28.
</pre></details>

### What did you do?

```
go get golang.org/x/tools/cmd/gopls
```

### What did you expect to see?

Successful installation of gopls

### What did you see instead?

```
package golang.org/x/tools/cmd/gopls: cannot find package "golang.org/x/tools/cmd/gopls" in any of:
        /usr/local/go/src/golang.org/x/tools/cmd/gopls (from $GOROOT)
        /go/src/golang.org/x/tools/cmd/gopls (from $GOPATH)
```

**Comment by stamblerre** [comment]
To install `gopls`, please follow the instructions [here](https://github.com/golang/tools/blob/master/gopls/doc/user.md#installation).

**Comment by Fuxxel** [comment]
Thank you for the instructions. I can confirm that this works. This also fixes your vscode Go devcontainer issue: [https://github.com/microsoft/vscode-dev-containers/issues/175](url)

**Comment by stamblerre** [comment]
Thanks for following up. Closing this issue.
