### ISSUE TITLE
x/tools/go/packages: could not import C (no metadata for C)

### ISSUE THREAD

**Issue by jayconrod** [golang/go#36441]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jayconrod/Library/Caches/go-build"
GOENV="/Users/jayconrod/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jayconrod/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go/installed"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/installed/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jayconrod/Code/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rq/x0692kqj6ml8cvrhcqh5bswc008xj1/T/go-build071831140=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I tried to load a cgo package with `golang.org/x/tools/go/packages.Load` using the mode `NeedName | NeedTypes | NeedImports | NeedDeps`. See the testscript below.

```
go run load.go

-- go.mod --
module example.com/c

go 1.13

require golang.org/x/tools v0.0.0-20200107184032-11e9d9cc0042 // indirect
-- c.go --
package c

import "C"
-- load.go --
// +build ignore

package main

import (
	"fmt"
	"log"

	"golang.org/x/tools/go/packages"
)

func main() {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedTypes | packages.NeedImports | packages.NeedDeps,
	}
	pkgs, err := packages.Load(cfg, "example.com/c")
	if err != nil {
		log.Fatal(err)
	}
	for _, pkg := range pkgs {
		fmt.Printf("package %s\n", pkg.PkgPath)
		for _, err := range pkg.Errors {
			fmt.Printf("\t%s\n", err)
		}
	}
}
```

### What did you expect to see?

```
package example.com/c
```

(no errors reported)

### What did you see instead?

```
package example.com/c
	/Users/jayconrod/Code/test/c.go:3:8: could not import C (no metadata for C)
```

This works when I add `packages.NeedSyntax` to the mode. For the tool I'm writing, I just need the types of exported definitions. I don't need to access the AST.

cc @matloob

**Comment by hajimehoshi** [comment]
I found the same error even with `packages.NeedSyntax`.
