### ISSUE TITLE
cmd/go: module operations fail to update go.mod when applying exclude directives

### ISSUE THREAD

**Issue by perj** [golang/go#36453]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pelle/.cache/go-build"
GOENV="/home/pelle/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pelle/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/pelle/meh/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build319548881=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
mkdir bug

cd bug

cat > foo.go <<EOT
package main

import (
	_ "github.com/prometheus/client_golang/prometheus"
)

func main() {}
EOT

cat > go.mod <<EOT
module github.com/perj/bug

go 1.13

require github.com/prometheus/client_golang v1.3.0

exclude github.com/stretchr/objx v0.1.1
EOT

go build

GOPROXY=none go build && echo success
```

### What did you expect to see?
success

### What did you see instead?
```
go: github.com/prometheus/client_golang@v1.3.0 requires
	github.com/prometheus/common@v0.7.0 requires
	github.com/sirupsen/logrus@v1.4.2: invalid proxy URL missing scheme: none
```

If the `exclude` line is deleted from go.mod then it works as expected, using the locally cached modules instead of downloading, I verified this using strace. Notably it does seem to be using the excluded v0.1.1 version of objx, while with the exclude line it uses v0.2.0 (both exist in ~/go/pkg/mod/).

I sometimes work without a network connection and this is stopping me from compiling my program at those times.

**Comment by bcmills** [comment]
I think @jayconrod ran across this same issue recently, but I can't find an issue filed for it.

CC @matloob

**Comment by jayconrod** [comment]
We discussed this with @rsc before the holidays. I haven't opened a proposal for this yet. I'll do so today.

The problem is that if the `go` command encounters an excluded version in the module graph, it must go out to the network to find the next higher version. This happens even if a higher version is required in the main go.mod. This makes the build non-deterministic: different versions may be available over time. The `go` command doesn't (can't?) update `go.mod` to avoid transitively required excluded module versions.

For now, I'd recommend using `replace` instead of `exclude`. This should result in the same set of versions being selected, but it won't go out to the network to list versions.

```
replace github.com/stretchr/objx v0.1.1 => github.com/stretchr/objx v0.2.0
```

**Comment by perj** [comment]
Replace does indeed seem to be a valid workaround, thanks.

**Comment by ianlancetaylor** [comment]
Are we going to do anything more with this issue?  The discussion suggests that there is a workaround.

**Comment by jayconrod** [comment]
#36465 should cover everything we need to do here, so this can be closed.
