### ISSUE TITLE
x/tools/cmd/stringer: redundant check

### ISSUE THREAD

**Issue by awilliams** [golang/go#36461]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

This issue reproduces using `x/tools/cmd/stringer` on the latest from master ([`b9c20ae`](https://github.com/golang/tools/tree/b9c20aec41a58d08b028186fa880270b804fb2e6/cmd/stringer)).

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env GOOS GOARCH
darwin
amd64
</pre></details>

### What did you do?

Ran `x/tools/cmd/stringer` on the following file: https://play.golang.org/p/H5tvJ6Edhrr

```shell
$ stringer -type=signedSingleRun,signedMultipleRuns,unsignedSingleRun,unsignedMultipleRuns -linecomment main.go
```

### What did you expect to see?

`stringer`'s output can be grouped into four categories based on the type being "stringed":
- single run: the values are consecutive, e.g. 1,2,3,4
- multiple runs: the values are nonconsecutive, e.g. 1,2,10,20
- signed: type is signed
- unsigned: type is unsigned

Using the above [playground example](https://play.golang.org/p/H5tvJ6Edhrr):

- For signed single run, the `String` method includes a check for `i < 0`:
```go
func (i signedSingleRun) String() string {
	if i < 0 || i >= signedSingleRun(len(_signedSingleRun_index)-1) {
		return "signedSingleRun(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _signedSingleRun_name[_signedSingleRun_index[i]:_signedSingleRun_index[i+1]]
}
```

- For unsigned single run, the `String` method does **not** include this check:
```go
func (i unsignedSingleRun) String() string {
	if i >= unsignedSingleRun(len(_unsignedSingleRun_index)-1) {
		return "unsignedSingleRun(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _unsignedSingleRun_name[_unsignedSingleRun_index[i]:_unsignedSingleRun_index[i+1]]
}
```

I would expect to see the same logic for the signed/unsigned multiple runs cases.

### What did you see instead?

Instead, the unsigned / multiple run case includes a redundant check for `0 <= i` in its `String` method.

Using the above [playground example](https://play.golang.org/p/H5tvJ6Edhrr):

- For signed multiple runs:
```go
func (i signedMultipleRuns) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _signedMultipleRuns_name_0[_signedMultipleRuns_index_0[i]:_signedMultipleRuns_index_0[i+1]]
	case 103 <= i && i <= 105:
		i -= 103
		return _signedMultipleRuns_name_1[_signedMultipleRuns_index_1[i]:_signedMultipleRuns_index_1[i+1]]
	default:
		return "signedMultipleRuns(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
```

- For unsigned multiple runs (comment added for emphasis):
```go
func (i unsignedMultipleRuns) String() string {
	switch {
	case 0 <= i && i <= 2: // redundant 0 <= i check
		return _unsignedMultipleRuns_name_0[_unsignedMultipleRuns_index_0[i]:_unsignedMultipleRuns_index_0[i+1]]
	case 103 <= i && i <= 105:
		i -= 103
		return _unsignedMultipleRuns_name_1[_unsignedMultipleRuns_index_1[i]:_unsignedMultipleRuns_index_1[i+1]]
	default:
		return "unsignedMultipleRuns(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
```

**Comment by mvdan** [comment]
Sure. Want to send a CL with a test?

**Comment by awilliams** [comment]
@mvdan I'd be happy to send a CL.
