### ISSUE TITLE
x/build: stop testing playground against Go 1.12

### ISSUE THREAD

**Issue by bradfitz** [golang/go#36464]
Running TryBots on x/playground showed failures with Go 1.12:

https://go-review.googlesource.com/c/playground/+/195983/17#message-343e7848e33f278f95e4672848606973671a6203

We don't need to be testing Go 1.12 there.

**Comment by dmitshur** [comment]
I believe this is resolved now, because Go 1.14 is out, so only 1.14 and 1.13 are being tested.

@toothrot Do you think anything more needs to be done, or can we close this?

**Comment by toothrot** [comment]
This is fixed by work done for #25224.
