### ISSUE TITLE
x/crypto/sha3: add tests with assembly disabled

### ISSUE THREAD

**Issue by mundaym** [golang/go#36466]
Both amd64 and s390x have assembly implementations of SHA-3. On amd64 the assembly is always used and the generic implementation is not tested at all. On s390x the generic implementation won't be tested if the SHA-3 CPU features are available. On both platforms we should add tests for the generic code to ensure it is properly tested.

Unfortunately due to the nature of the instructions involved they are implemented in different ways so this will take some thinking.

**Comment by FiloSottile** [comment]
See https://golang.org/wiki/TargetSpecific.
