### ISSUE TITLE
cmd/compile: amd64 addressing modes are unwieldy

### ISSUE THREAD

**Issue by josharian** [golang/go#36468]
There are many amd64 instructions that accept a full range of memory addressing modes. It would be nice to make use of them all.

The current approach is to give each its own op, such as `BTRQmodifyidx8` or `ANDQloadidx1`. The problem is that this generates a large number of ops and rules. To add `ANDQloadidx1`, we need to find all rules starting with `ANDQ` and add variants for `ANDQloadidx1` as appropriate. And we need to add rules (say) absorbing `SHLQ` of the index into the scale, and `ADDQ` into the offset. For an example of how many rules are involved just for adding addressing modes for `CMP`, see https://golang.org/cl/167089. And that's a fairly simple case, because there aren't many existing rules involving `CMPQ` that need indexed load analogues.

Such additions have steady incremental improvements in generated code, at the cost of developer time, reviewer time, compiler binary size, and time and memory required to build the compiler (which has proved to be an ongoing problem).

I wonder whether we can find a way to factor out some of this commonality, so we can hoover up all the incremental improvements at much less cost.

One idea is to encode the scale into AuxInt, so we'd have just `idx` instead of `idx1`, `idx2`, `idx4`, `idx8`. We'd need helper routines to tell us whether it's ok to adjust the scale in a particular way, since not all scales are available for all bit widths, but that is doable. The great shortcoming of this idea is that `idx1` ops are commutative, but the others are not. Maybe just encode the scale for 2, 4, and 8?

Another (vague) idea is to have a separate handwritten pass after lower that does nothing but addressing modes. We'd mark ops with what kind of address modes they support in which argument slots and then do all combining then. We'd still have a combinatorial number of ops, but many fewer rules.

This is actually an instance of a broader amd64 problem around having a combinatorial number of ops (base X const? X load/store/modify X addressingmode). Maybe if we structured this all appropriately, we could generate (rather than hand code) all the ops and their encodings in amd64/ssa.go and their generated rules (like we did for commutativity).

For discussion and ideas.

cc @randall77 @mvdan @martisch @cherrymui

**Comment by josharian** [comment]
Here's another example of the combinatorial rule problem with amd64.

LEAx values with non-zero offsets get split at the end of compilation into multiple LEAs to avoid slow LEAs.

Some other values can absorb the LEA offsets, which would lead to a simpler encoding. Here is a  sample rule:

```
(MOVQstoreconst [x] {sym1} (LEA(Q1|Q2|Q4|Q8|L1|L2|L4|L8|W1|W2|W4|W8) <t> [c] {sym2} ptr idx) mem) && c != 0 && ValAndOff(x).canAdd(c) ->
  (MOVQstoreconst [ValAndOff(x).add(c)] {sym1} (LEA(Q1|Q2|Q4|Q8|L1|L2|L4|L8|W1|W2|W4|W8) <t> [0] {sym2} ptr idx) mem)
```

But if you look at the number of ops that have ValAndOff-style auxints that can absorb an index, there are a bunch...the combinatorial number mentioned above. As such, even though these rules do shorten generated code I'm not inclined to add them.

---

Another possible approach here is to construct another way to write rewrite rules. We have `|` to do parallel op selection. We could have named `|`s to let you do combinatorial op selection. (Maybe the number of consecutive `|`s?) Something like this:

```
(X(a|b)(c||d) [z]) -> (Y(a|b)(c||d) [c])
```

This would generate combinations Xac, Xad, Xbc, Xbd, correlated to Yac, Yad, Ybc, Ybd. If you needed eight, you could have `(X(a|b)(c||d)(e|||f) [z])`.

Problems with this idea. (1) The syntax is lousy and I don't see a better solution. (2) It generates a lot of rewrite rules. I guess we could do this with loops instead of generation, like we did with commutativity, but that's gonna start hurting my head pretty soon.

**Comment by randall77** [comment]
I hacked together another possible strategy to fix this. Take a look and let me know what you think.

**Comment by randall77** [comment]
I'm going to close this, I think we've done enough, at least for x86. I'll open a separate issue for s390x.
