### ISSUE TITLE
proposal: Add manual garbage collection support for more lower level performance critical applications

### ISSUE THREAD

**Issue by cyantarek** [golang/go#36474]
I was reading a white paper called ixy.go which showed how to implement a low level user space network driver with Go. Very well laid paper.

They have also stated the pros and cons of using Go for this kind of applications. One thing scratched my mind is that, they said Go's garbage collector takes a lot of time at runtime.

I know, you can use debug.SetGCPercent(-1) to turn off garbage collection and use runtime.GC() for running garbage collection manually. But it would be much better to give an option to allocate and free memory when the developers want to turn off auto garbage collection.

**Comment by proyb6** [comment]
What kind of critical applications would you be using?
