### ISSUE TITLE
I want to debug Remote's Server's Go Program on my Local Win 10 with Goland, but it doesn't work

### ISSUE THREAD

**Issue by cw4t** [golang/go#36475]
### What version of Delve are you using (dlv version)?
1.3.2
### What version of Go are you using? (go version)?
go version go1.13.4 linux/amd64
### What operating system and processor architecture are you using?
Local: Win 10, Remote Server: Centos7, x86_64, GNU/Linux,
### What did you do?
I want to Use Goland to debug the Centos's Go Program with delve, but it failed!
### What did you expect to see?
Codes that can be debug on my Local win10 with GoLand
### What did you see instead?
nothing

**Comment by seankhliao** [comment]
this is a goland/delve issue not a go one, please use the appropriate forums for that

**Comment by toothrot** [comment]
This issue tracker is for problems with the Go tools and standard library. I'd recommend filing an issue with Goland.

Also, more people will see your question, and you will get better answers, if you ask on a forum rather than on the issue tracker. See https://golang.org/wiki/Questions.
