### ISSUE TITLE
x/tools/gopls: don't treat test mains as workspace packages

### ISSUE THREAD

**Issue by stamblerre** [golang/go#36473]
The initial workspace load currently runs a `go list ./...` query for the entire workspace, so we get all packages in the workspace, including test mains. We need to stop providing diagnostics for these packages, as they aren't useful. 

@jayconrod, @matloob: Is there any reliable way to detect that a package is a test main?

**Comment by jayconrod** [comment]
Generated test main packages have import paths that end with `.test`. Their package names are `main`. They should have one entry in `GoFiles`, which is inside the build cache.

```
{
	"Dir": "/Users/jayconrod/Code/test",
	"ImportPath": "m.test",
	"Name": "main",
	"Root": "/Users/jayconrod/Code/test",
	"Stale": true,
	"StaleReason": "stale dependency: m",
	"GoFiles": [
		"/Users/jayconrod/Library/Caches/go-build/4e/4ed90dfb73b1b23fb2030ce6dc74671fc821753d1018c3a52b818077266d5810-d"
	],
...
}
```

**Comment by stamblerre** [comment]
Is checking for those 3 things sufficient, or should we also check that the dependencies are exactly `os`, `testing`, and `testing/internal/testenv`?

**Comment by jayconrod** [comment]
Testing those 3 things should be sufficient. Even just the first two would be fine unless someone deliberately names their package `something.test`.

The list of imports is not stable. `testing/internal/testenv` could change. Also the `-coverpkg` flag will cause the test main to import every instrumented package, whether it's being tested or not.
