### ISSUE TITLE
x/lint/golint: looped goroutines should raise a warning

### ISSUE THREAD

**Issue by nektro** [golang/go#36484]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Untested at the time of writing

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/meghan/snap/code/common/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/meghan/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build822957010=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```
for i := 0; i < count; i++ {
	go func() {
		//
	}()
}
```

### What did you expect to see?
A warning that this is a bad pattern from go-lint.

### What did you see instead?
Nothing.

**Comment by toothrot** [comment]
There are many reasons to start a goroutine in a loop, such as starting up a pool of workers, or executing requests in parallel. See the example in https://golang.org/pkg/sync/#WaitGroup.

Could you add more details why you believe this deserves a lint warning?
