### ISSUE TITLE
database/sql: customize JSON marshalling for nullable fields

### ISSUE THREAD

**Issue by toqueteos** [golang/go#36496]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Carlos\AppData\Local\go-build
set GOENV=C:\Users\Carlos\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\code\go
set GOPRIVATE=
set GOPROXY=direct
set GOROOT=c:\go
set GOSUMDB=off
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\code\sample\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Carlos\AppData\Local\Temp\go-build116244046=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Serialize any of the `database/sql` null fields as JSON using `encoding/json`.

https://play.golang.org/p/_sFxOknJhkH

### What did you expect to see?

I expect to see all the `database/sql` null fields serialized as nulls when their `Valid == false`.

```json
{
	"bool": null,
	"float64": null,
	"int32": null,
	"int64": null,
	"string": null,
	"time": null
}
```

### What did you see instead?

The zero value.

```json
{
	"bool": {
		"Bool": false,
		"Valid": false
	},
	"float64": {
		"Float64": 0,
		"Valid": false
	},
	"int32": {
		"Int32": 0,
		"Valid": false
	},
	"int64": {
		"Int64": 0,
		"Valid": false
	},
	"string": {
		"String": "",
		"Valid": false
	},
	"time": {
		"Time": "0001-01-01T00:00:00Z",
		"Valid": false
	}
}
```

**Comment by toqueteos** [comment]
This can be solved by implementing [MarshalJSON](https://golang.org/pkg/encoding/json/#Marshaler) (and also [UnmarshalJSON](https://golang.org/src/encoding/json/decode.go?s=4749:4808#L107)) but I think it qualifies as breaking change so it'd go to Go2. Can somebody confirm it?

**Comment by toothrot** [comment]
I think the current behavior might be the least surprising to me. Null fields marshal like any normal Go struct. I believe leaving the conversion of the data to the caller's target format is best left up to the caller.

/cc @bradfitz @kardianos

**Comment by kardianos** [comment]
@toothrot

Please observe https://github.com/golang-sql/table . You can get custom table marshaling of arbitrary tables using this method.

**Comment by kardianos** [comment]
We won't add a MarshalJSON method to Rows. I will be closing this issue.

**Comment by toqueteos** [comment]
@kardianos I'm sorry but I don't understand, what has Rows to do with this issue?

**Comment by kardianos** [comment]
Looking at your play link, I see more clearly what you mean. You would like to define the methods on the Nullable structs.

Yeah, that would likely be a backwards in-compatible change.

**Comment by toqueteos** [comment]
I'm sad to hear that but I understand. Thanks!
