### ISSUE TITLE
cmd/link: paths in debug_line contain a mix of forward and backward slashes with Go 1.14beta1/Windows

### ISSUE THREAD

**Issue by aarzilli** [golang/go#36495]
What the title says. It used to be that debug_line uniformly used forward slashes `/` but now some paths have forward slashes `/` while others have backward slashes `\`.

This happens reliably when building with `go build path_to_go_file.go`, I'm not sure about other build modes.

Existing versions of Delve will have a problem with this but the fix is simple and I have already implemented it. However the behavior seems unintentional enough that I thought I'd report it.

I'm blaming cmd/link entirely without proof, it could be something else.

Since Windows doesn't have a handy utility to examine debug_line I wrote this script:

```
package main

import (
	"debug/dwarf"
	"debug/pe"
	"fmt"
	"io"
	"os"
)

func must(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	exe, err := pe.Open(os.Args[1])
	must(err)
	dw, err := exe.DWARF()
	must(err)

	rdr := dw.Reader()

	seen := make(map[string]bool)

	for {
		e, err := rdr.Next()
		must(err)
		if e == nil {
			break
		}

		if e.Tag != dwarf.TagCompileUnit {
			continue
		}

		lnrdr, err := dw.LineReader(e)
		must(err)

		if lnrdr != nil {
			var lne dwarf.LineEntry
			for {
				err := lnrdr.Next(&lne)
				if err == io.EOF {
					break
				}
				must(err)

				if !seen[lne.File.Name] {
					seen[lne.File.Name] = true
					fmt.Printf("%s\n", lne.File.Name)
				}
			}
		}

		rdr.SkipChildren()
	}

}
```

@gopherbot please add label Debugging

**Comment by aarzilli** [comment]
Does the @gopherbot thing not work anymore?

**Comment by ianlancetaylor** [comment]
CC @thanm @cherrymui @jeremyfaller

**Comment by ianlancetaylor** [comment]
Thanks for the report.  Tentatively marking as a release blocker for 1.14.
