### ISSUE TITLE
x/tools/gopls: support LSP language features for go.mod files

### ISSUE THREAD

**Issue by stamblerre** [golang/go#36501]
This is a subset of https://github.com/golang/go/issues/31999, but I felt it was useful to break it out.  Some features worth considering (please add more here as they come up):

- `textDocument/documentLink`: Clicking on a dependency could take you to the discovery site.

/cc @ridersofrohan

**Comment by stamblerre** [comment]
Following up on some discussions today:

- `go list -m -u` can be used to determine possible module upgrades. These can be offered to the user as a code lens, to avoid surfacing a potentially bothersome diagnostic.
- `go/packages` runs `go list -m`, but it doesn't provide any of these modules to the caller. Add an internal only field that `gopls` can access, much in the same way as we have done for the `forTest` field in `metadata`. See `golang.org/x/tools/internal/lsp/cache/load.go` for how that field set in `gopls`, and https://pkg.go.dev/golang.org/x/tools/internal/packagesinternal and `golang.org/x/tools/go/packages/golist.go` for how that field is set.
- `textDocument/hover` can be used to surface the output of `go mod why` on a dependency.

**Comment by stamblerre** [comment]
@ridersofrohan: Can we close this, or are there any more features remaining? The only thing that comes to mind is folding range.

**Comment by ridersofrohan** [comment]
I think we can close it. I don't know how useful folding range would be considering there are only 4 directives for go.mod files.
