### ISSUE TITLE
strange behavior serving static files

### ISSUE THREAD

**Issue by tiagoacardoso** [golang/go#36502]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tiagocardoso/.cache/go-build"
GOENV="/home/tiagocardoso/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tiagocardoso/Code/local-environment/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/tiagocardoso/Code/local-environment/test-json/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build214163253=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```golang
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/gin-gonic/contrib/static"
	"github.com/gin-gonic/gin"
)

// Foo -
func Foo(c *gin.Context) {
	c.AbortWithStatus(200)
}

func main() {

	router := gin.Default()
	router.Use(static.Serve("/", static.LocalFile("/app/public", false)))
	
	router.GET("/", Foo)

	log.Println("App is now running")

	if err := router.Run(fmt.Sprintf(":%s", "8200")); err != nil {
		log.Fatal("Failed to run the application")
	}
}
```
I'm serving a version.json which is located under public folder

### What did you expect to see?

The Content-Type using Docker image golang:1.13.5-alpine from version.json  is: text/plain; charset=utf-8

The Content-Type using Docker image golang:1.13.5 from version.json is: application/json

### What did you see instead?

The Content-Type using Docker image golang:1.13.5-alpine from version.json  should be: application/json instead of text/plain; charset=utf-8

The Content-Type using Docker image golang:1.13.5 from version.json is: application/json which is correct

I'm I missing something?

**Comment by toothrot** [comment]
I believe that `gin-gonic`'s `static` package uses `net/http`'s `FileServer.`

From the docs https://pkg.go.dev/net/http/?tab=doc#ServeContent:
> If the response's Content-Type header is not set, ServeContent first tries to deduce the type from name's file extension and, if that fails, falls back to reading the first block of the content and passing it to DetectContentType. The name is otherwise unused; in particular it can be empty and is never sent in the response.

`http.ServeContent` uses `mime` to detect by extension, so let's look there:

> The built-in table is small but on unix it is augmented by the local system's mime.types file(s) if available under one or more of these names:
```
/etc/mime.types
/etc/apache2/mime.types
/etc/apache/mime.types
```
> On Windows, MIME types are extracted from the registry.

It looks like `golang:1.13.5-alpine` doesn't include `/etc/mime.types`, so on that distribution you'll have to manually handle your mime types for static file servers, or [first install an appropriate package on alpine](https://pkgs.alpinelinux.org/contents?file=mime.types&path=&name=*&branch=edge&repo=main&arch=armhf).

I don't think this is a bug with Go or the standard library, so I will close this issue. Let me know if I am mistaken.

**Comment by tiagoacardoso** [comment]
Thank you, I really appreciate your explanation and that's what I was looking for.

Best regards :)
