### ISSUE TITLE
plugin: R15 clobbered when loading outside variables

### ISSUE THREAD

**Issue by timorl** [golang/go#36509]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/timorl/.cache/go-build"
GOENV="/home/timorl/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="[REDACTED]"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="x86_64-pc-linux-gnu-gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build858965079=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Encountered a bug when using cloudflare/bn256 inside of a plugin. After reporting it [here](https://github.com/cloudflare/bn256/issues/16) we have a minimal example [here](https://gitlab.com/tymorl/xenophobia).

The minimal example loads `1` into R15, then reads an unrelated variable and returns the contents of R15.

### What did you expect to see?

The number `1` being returned.

### What did you see instead?

Random huge numbers.

### Other

I strongly suspect this is essentially the same problem as  #18820, but with a different library. From what I understand this probably won't be changed, but I could not find any official statement that no one should expect using R15 and loading variables to work together when dynamically linking, so it is technically still a bug, right?

**Comment by armfazh** [comment]
Related #58632

**Comment by randall77** [comment]
This was fixed with CL 283474, which would have been released with Go 1.17. And by "fixed", I mean the assembler should reject the assembly when compiled as a plugin.

See #43661.
