### ISSUE TITLE
x/tools/gopls: unimported completion ranked above local variable

### ISSUE THREAD

**Issue by stamblerre** [golang/go#36519]
<img width="820" alt="Screen Shot 2020-01-12 at 8 16 14 PM" src="https://user-images.githubusercontent.com/5856771/72228867-6c725000-3578-11ea-829c-5f3015bf0db5.png">

/cc @heschik @muirdm

**Comment by muirdm** [comment]
I really had to stare at that line of code until I spotted what I did wrong.
