### ISSUE TITLE
Not found one module when I build koko.go on my Win10 sys.

### ISSUE THREAD

**Issue by cw4t** [golang/go#36515]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.4 windows/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes: Go 1.13.4
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>

D:\Work\koko\cmd>go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\v-liuning\AppData\Local\go-build
set GOENV=C:\Users\v-liuning\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\GoPath
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Software\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Software\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Work\koko\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\V-LIUN~1\AppData\Local\Temp\go-build346313126=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
go build -o koko.exe koko.go

### What did you expect to see?

Build success for have a koko.exe 

### What did you see instead?
![QQ图片20200112164139](https://user-images.githubusercontent.com/15030650/72216310-6f5e4800-355a-11ea-8bf1-3421da2f6c78.png)

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.

**Comment by cw4t** [comment]
Thank you and I figured it out 发自我的iPhone------------------ Original ------------------From: Daniel Martí  <notifications@github.com>Date: Sun,Jan 12,2020 10:44 PMTo: golang/go <go@noreply.github.com>Cc: cw4t <chasewater4truth@gmail.com>, Author <author@noreply.github.com>Subject: Re: [golang/go] Not found one module when I build koko.go on my Win10sys. (#36515)The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/golang/go/issues/36515?email_source=notifications\u0026email_token=ADSVS6SRD7WUXRBIIM3Y4I3Q5MUGRA5CNFSM4KFWPBLKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIW3TGQ#issuecomment-573421978",
"url": "https://github.com/golang/go/issues/36515?email_source=notifications\u0026email_token=ADSVS6SRD7WUXRBIIM3Y4I3Q5MUGRA5CNFSM4KFWPBLKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIW3TGQ#issuecomment-573421978",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
