### ISSUE TITLE
x/tools/gopls: "failed to cache compiled Go files" error when calling Formatting

### ISSUE THREAD

**Issue by myitcv** [golang/go#36511]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +693748e9fa Mon Jan 6 11:46:56 2020 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20200107184032-11e9d9cc0042 => github.com/myitcvforks/tools v0.0.0-20200108093634-093e5cb57410
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.1.8-0.20200107184032-11e9d9cc0042 => github.com/myitcvforks/tools/gopls v0.0.0-20200108093634-093e5cb57410
</pre>

The replace directive versions are described here:

https://github.com/govim/govim/commit/afa4918a6d4d485b6797580c76f894c41a8c2a1b

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build460580672=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

`govim` has a test that verifies the behaviour of calling `goimports` (via `CodeAction`) and then `Formatting`. 

The sequence is:

* open file
* run `CodeAction` and then `Formatting`
* compare the result vs a known golden file

We have just seen the `Formatting` call fail in one of our CI builds with the following error:

```
getting file for Format: go [list -e -json -compiled=true -test=true -export=false -deps=true -find=false -- os]: exit status 1: go build os/signal: failed to cache compiled Go files
```

### What did you expect to see?

No error

### What did you see instead?

As above. The `gopls` log is as follows: [gopls.log](https://github.com/golang/go/files/4049894/gopls.log)

---

cc @stamblerre

FYI @leitzler

**Comment by stamblerre** [comment]
This looks like a `go list` error message, so my guess is that the `go/packages.Load` must have failed for some reason, which caused this response. I mailed the above CL to remove the need for `go list` to run on a formatting request, but fundamentally we can't really do anything else about a `go list` error. In the typical case, we would try to run `go/packages.Load` again if we failed on a prior request.

**Comment by myitcv** [comment]
> but fundamentally we can't really do anything else about a go list error

I agree if the error from `go list` is a known "good" error. But in this case I'm not clear that it's an expected potential outcome from what we were trying to do at the time.

**Comment by stamblerre** [comment]
Not sure if the `go list` error was "known", but it doesn't seem like something we can necessarily avoid. Please open a new issue if you see this again. The above CL has been merged, so now `go list` errors won't affect formatting results.
