### ISSUE TITLE
doc: go-spec.html missing space before . on line 2416, OperandName = identifier | QualifiedIdent.

### ISSUE THREAD

**Issue by Conformable** [golang/go#36520]
### What version of Go are you using (`go version`)?

<pre>
go 1.13.5

(line 2416 is as of current master)

</pre>

### Does this issue reproduce with the latest release?

yes 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user2/Library/Caches/go-build"
GOENV="/Users/user2/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/user2/A/AL3/code/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8v/vpckwgfs4_547sb94qr9f4d40000gq/T/go-build564981435=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you expect to see?

"OperandName = identifier | QualifiedIdent ."

### What did you see instead?

"OperandName = identifier | QualifiedIdent."

**Comment by mvdan** [comment]
This style is used everywhere. Like `letter        = unicode_letter | "_" .`.

**Comment by networkimprov** [comment]
Well it's not crucial, but the report is valid, see last item of https://golang.org/ref/spec#Operands :-)

**Comment by mvdan** [comment]
Oh, d'oh. I read the issue backwards, my bad. I thought you were suggesting that there was an extra space.

Feel free to send a CL
