### ISSUE TITLE
Calling Elem() on a slice reflect.Value panics

### ISSUE THREAD

**Issue by kstenerud** [golang/go#36523]
### What did you do?

https://play.golang.org/p/nDTCz6lJD_f

### What did you expect to see?

The element type of the slice

### What did you see instead?

    panic: reflect: call of reflect.Value.Elem on slice Value

According to https://golang.org/pkg/reflect:

```golang
    // Elem returns a type's element type.
    // It panics if the type's Kind is not Array, Chan, Map, Ptr, or Slice.
    Elem() Type
```

In this case, the type's kind is slice, yet it still panics.

**Comment by BatmanAoD** [comment]
This does seem like valid code; why is this closed?

**Comment by kstenerud** [comment]
I was calling Elem on the value, not its type. The proper way is:

```golang
fmt.Println(v.Type().Elem())
```

**Comment by BatmanAoD** [comment]
Ah, okay! Thank you.

`Value.Elem()`, unlike `Type.Elem()`, says this:

> It panics if v's Kind is not Interface or Ptr. It returns the zero Value if v is nil. 

https://golang.org/pkg/reflect/#Value.Elem
