### ISSUE TITLE
time: Pivot year used when parsing two digit years is not documented.

### ISSUE THREAD

**Issue by takeyourhatoff** [golang/go#36549]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
Try to parse dates with two digit years.
https://play.golang.org/p/CdUxdDqG8mF

### What did you expect to see?
Documentation regarding the pivot year used when parsing two digit years.

### What did you see instead?
No mention of the pivot year used.

**Comment by ianlancetaylor** [comment]
The pivot year is 1969 (two-digit-year >= 69 => add 1900, < 69 => add 2000).  I agree that this should be documented somewhere, perhaps in the doc comment for `time.Parse`.
