### ISSUE TITLE
EOF error ocurring randomly

### ISSUE THREAD

**Issue by projectloro** [golang/go#36565]
### What version of Go are you using (`go version`)?

<pre>
go version go1.10.3 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build680614240=/tmp/go-build"

</pre></details>

### What did you expect to see?

I wasn't expecting that to happen

### What did you see instead?
EOF DATE

**Comment by mvdan** [comment]
Follow the template. What did you do?

Also, remember that the Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.

**Comment by bradfitz** [comment]
There's no information here.
