### ISSUE TITLE
cmd/go: cannot find module for path crypto/ed25519 on Rasperry Pi (debian 10.2)

### ISSUE THREAD

**Issue by emclab** [golang/go#36567]
### What version of Go are you using (`go version`)?

<pre>
$ go version: 1.13.6

</pre>

### What operating system and processor architecture are you using (`go env`)?
$ go env

warning: GOPATH set to GOROOT (/usr/local/go) has no effect
GO111MODULE="on"
GOARCH="arm"
GOBIN=""
GOCACHE="/home/pi/.cache/go-build"
GOENV="/home/pi/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/local/go"
GOPRIVATE=""
GOPROXY="on"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/pi/ipfs-cluster/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build174400929=/tmp/go-build -gno-record-gcc-switches"
<details><summary><code>go env</code> Output</summary><br><pre>

</pre></details>

### What did you see instead?
Here is the error:

go: downloading github.com/miekg/dns v1.1.12
go: downloading github.com/ipfs/go-verifcid v0.0.1
go: downloading github.com/Stebalien/go-bitfield v0.0.1
go: downloading google.golang.org/genproto v0.0.0-20190425155659-357c62f0e4bb
go: downloading github.com/ipfs/go-peertaskqueue v0.1.1
go: downloading github.com/hashicorp/raft v1.1.1
go: downloading github.com/whyrusleeping/mafmt v1.2.8
go: downloading github.com/libp2p/go-libp2p-nat v0.0.4
go: downloading github.com/ugorji/go v1.1.7
go: downloading github.com/libp2p/go-libp2p-consensus v0.0.1
go: downloading github.com/ipfs/go-todocounter v0.0.1
go: downloading github.com/vishvananda/netns v0.0.0-20190625233234-7109fa855b0f
go: downloading github.com/cskr/pubsub v1.0.2
go: downloading github.com/marten-seemann/qtls v0.4.1
go: downloading github.com/AndreasBriese/bbloom v0.0.0-20190306092124-e2d15f34fcf9
go: downloading github.com/marten-seemann/chacha20 v0.2.0
go: downloading github.com/whyrusleeping/go-keyspace v0.0.0-20160322163242-5b898ac5add1
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/ugorji/go/codec v1.1.7
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/gorilla/websocket v1.4.1
go: downloading github.com/whyrusleeping/multiaddr-filter v0.0.0-20160516205228-e903e4adabd7
go: downloading github.com/russross/blackfriday v1.5.2
go: downloading github.com/cenkalti/backoff v2.2.1+incompatible
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: downloading contrib.go.opencensus.io/exporter/prometheus v0.1.0
go: downloading github.com/ipfs/go-ipfs-chunker v0.0.1
go: downloading github.com/libp2p/go-nat v0.0.3
go: downloading github.com/whyrusleeping/go-logging v0.0.0-20170515211332-0457bb6b88fc
go: downloading github.com/whyrusleeping/go-notifier v0.0.0-20170827234753-097c5d47330f
go: downloading github.com/ipfs/go-cidutil v0.0.2
go: downloading github.com/ipfs/go-ipfs-pq v0.0.1
go: downloading github.com/ipfs/go-mfs v0.1.1
go: downloading github.com/huin/goupnp v1.0.0
go: downloading github.com/koron/go-ssdp v0.0.0-20180514024734-4a0ed625a78b
go: downloading github.com/jackpal/gateway v1.0.5
go: downloading golang.org/x/sync v0.0.0-20190423024810-112230192c58
go: downloading github.com/jackpal/go-nat-pmp v1.0.1
go: downloading github.com/whyrusleeping/chunker v0.0.0-20181014151217-fe64bd25879f
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/armon/go-metrics v0.0.0-20190430140413-ec5e00d3c878
go: downloading github.com/ipfs/bbloom v0.0.4
go: downloading gonum.org/v1/gonum v0.0.0-20190926113837-94b2bbd8ac13
go: downloading github.com/hashicorp/go-immutable-radix v1.0.0
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
build github.com/ipfs/ipfs-cluster/cmd/ipfs-cluster-service: cannot find module for path crypto/ed25519

Tried `go clean -modcache` before installation and the error is the same.

**Comment by cagedmantis** [comment]
Hi @emclab. “Could you provide an example of the code that produced the error, preferably as a [Go playground](https://play.golang.org/) link?

**Comment by FiloSottile** [comment]
crypto/ed25519 was added in Go 1.13. Are you certain you're using that Go version, and not the Go version that comes with Debian?

**Comment by emclab** [comment]
$ go version
warning: GOPATH set to GOROOT (/usr/local/go) has no effect
go version go1.13.6 linux/arm

The above is the output of the `go version`. The version 1.13.6 was installed from the source after removing the 1.11 coming with debian.

**Comment by emclab** [comment]
`cagedmantis `, sorry that there is no code associated with the error. The error is from the installation of the ipfs-cluster go version. The same error was initially posted to `ipfs` forum and it seems that it was not a bug but something possibly related to go setup env.

**Comment by FiloSottile** [comment]
Can you also provide the sequence of commands leading to the error?

**Comment by bcmills** [comment]
Are you sure that your `GOROOT` (`/usr/local/go`) matches the source directory used to build `go1.13.6`?
