### ISSUE TITLE
misc/wasm: possible bug in InstanceOf

### ISSUE THREAD

**Issue by albrow** [golang/go#36561]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, judging by the contents of the `master` branch.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
O111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alex/Library/Caches/go-build"
GOENV="/Users/alex/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/alex/programming/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/alex/.go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/alex/.go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/alex/programming/go-mod/0x-mesh/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/h1/vhbpm31925nd0whbv4qd8mr00000gn/T/go-build550535634=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I am converting [__wasm_exec.js__](https://github.com/golang/go/blob/cae9a9fd65cae6cbde0aacfea8f70e952e89f33e/misc/wasm/wasm_exec.js) to TypeScript for bundling in a TypeScript library. I noticed this compiler error:

![Screen Shot 2020-01-14 at 4 24 29 PM](https://user-images.githubusercontent.com/800857/72394236-5be1e700-36ea-11ea-8e19-3c0e9144b0c5.png)

### What did you expect to see?

I don't expect this file to compile since it wasn't written with TypeScript in mind. I was surprised by this particular error because it looks like a type mismatch.

~~I think there might be a mistake on this line. I believe it is supposed to be written as:~~
(Update: Sorry, I realized my suggestion is probably not correct).

### What did you see instead?

The code doesn't compile in TypeScript, I think due to a mismatched parentheses. If that's true, I believe this would result in a bug/incorrect behavior in `syscall/js.InstanceOf`.

**Comment by albrow** [comment]
It's also possible this is a quirk of the TypeScript compiler and the code is correct. The TypeScript compiler seems to think the signature for `setUint8` is:

```typescript
setUint8(byteOffset: number, value: number): void
```

**Comment by bradfitz** [comment]
Can you just add a ternary to appease TypeScript?

```diff
diff --git a/misc/wasm/wasm_exec.js b/misc/wasm/wasm_exec.js
index bb66cf254d..5ac4032993 100644
--- a/misc/wasm/wasm_exec.js
+++ b/misc/wasm/wasm_exec.js
@@ -440,7 +440,7 @@
 
                                        // func valueInstanceOf(v ref, t ref) bool
                                        "syscall/js.valueInstanceOf": (sp) => {
-                                               this.mem.setUint8(sp + 24, loadValue(sp + 8) instanceof loadValue(sp + 16));
+                                               this.mem.setUint8(sp + 24, (loadValue(sp + 8) instanceof loadValue(sp + 16)) ? 1 : 0);
                                        },
 
                                        // func copyBytesToGo(dst []byte, src ref) (int, bool)
```

**Comment by albrow** [comment]
@bradfitz Thanks for the reply. Ah I see. Seems like you were relying on type coercion to convert `false` to `0` and `true` to `1`. So this is not a bug.

Still, it is generally considered bad practice in JavaScript to rely on this behavior, and there's a reason the TypeScript compiler complains about it. I was going to suggest a change, but I already see there's a proposed CL to fix it. Feel free to close this issue if you want.

**Comment by bradfitz** [comment]
@albrow, I'll submit my change when the Go 1.15 tree opens.
