### ISSUE TITLE
fmt: %#g behavior not consistent

### ISSUE THREAD

**Issue by musiphil** [golang/go#36562]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="$HOME/.cache/go-build"
GOENV="$HOME/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="$HOME/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/google-golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/google-golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build990462557=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/uhRa_BD_pUX
````go
fmt.Printf("%#.4g\n", 1.234)
fmt.Printf("%#.4g\n", 0.1234)
fmt.Printf("%#.4g\n", 1.23)
fmt.Printf("%#.4g\n", 0.123)
fmt.Printf("%#.4g\n", 1.2)
fmt.Printf("%#.4g\n", 0.12)
````

### What did you expect to see?

````
1.234
0.1234
1.230
0.1230
1.200
0.1200
````
`%#.4g` should print 4 significant digits, without removing trailing zeros.

### What did you see instead?

````
1.234
0.1234
1.230
0.123
1.200
0.120
````
The trailing zero from `1.230` is erroneously removed.

**Comment by martisch** [comment]
This seems consistent with the documentation (https://godoc.org/fmt) of the `g` verb and precision:

"For floating-point values, width sets the minimum width of the field and precision sets the number of places after the decimal, if appropriate, except that for **%g/%G** precision sets the maximum number of significant digits (**trailing zeros are removed**)."

**Comment by martisch** [comment]
I see now that "#" is supposed to alter the g to not remove trailing zeros later in the documentation.

"do not remove trailing zeros for %g and %G;"

**Comment by yah01** [comment]
what are the outputs:
fmt.Printf("%#.4g",0.0)
fmt.Printf("%#.4g",0.012)

i think the correct answer are:
0.0000
0.01200

because the counting significant digits after the first non-zero digit(included)
but the case of zero is unclear.
