### ISSUE TITLE
^0 is interpreted as -1

### ISSUE THREAD

**Issue by kstenerud** [golang/go#36578]
### What did you do?

https://play.golang.org/p/2kMDzm1vAtF

```golang
package main

import (
	"fmt"
)

func main() {
	var x uint64 = ^0
	fmt.Println(x)
}
```

### What did you expect to see?

I expected it to print the highest uint64 value possible

### What did you see instead?

    ./prog.go:8:17: constant -1 overflows uint64

The logical complement of 0 should not be assumed to be signed.

**Comment by bradfitz** [comment]
See https://blog.golang.org/constants

**Comment by randall77** [comment]
Use `x := ^uint64(0)` instead.

**Comment by minux** [comment]
Need to use `^uint64(0)` as explained https://blog.golang.org/constants#TOC_11%2e
