### ISSUE TITLE
misc/wasm: Possible bug in _makeFuncWrapper

### ISSUE THREAD

**Issue by albrow** [golang/go#36585]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, judging by the contents of the `master` branch.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
O111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alex/Library/Caches/go-build"
GOENV="/Users/alex/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/alex/programming/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/alex/.go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/alex/.go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/alex/programming/go-mod/0x-mesh/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/h1/vhbpm31925nd0whbv4qd8mr00000gn/T/go-build550535634=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Related to https://github.com/golang/go/issues/36561, I came across another unexpected error 
from the TypeScript compiler.

![Screen Shot 2020-01-15 at 1 33 25 PM](https://user-images.githubusercontent.com/800857/72473485-9fe0f480-379b-11ea-9f0c-98e33018293e.png)

`this` should _usually_ be avoided in anonymous functions, due to its often unexpected behavior. It's possible that this is intended, but I wanted to point it out for two reasons:

1. It looks like it could be a bug. At the very least it is not following JavaScript best practices.
2. The current version doesn't compile in TypeScript so I wanted to get confirmation about the intended behavior so I can write a version that behaves the same way but _does_ work in TypeScript.

As a quick reminder about [the behavior of `this` inside anonymous functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this):

1. If you are not running in strict mode, `this` defaults to the global scope (e.g. `window`). In strict mode it defaults to `undefined`.
2. You can set the value of `this` by using `bind`. In order to do this, you need a reference to the function. So if we have a function called `myFunc`, you could call it this way: `myFunc.bind(myObj).call()`. This would result in `this` being set to `myObj`.

It was difficult for me to find where the function was called, but if you are _not_ calling it via `bind`, it means that `this` is always `undefined`. This might be a bug that should be addressed. On the other hand if everything still works, `this` could simply be removed:

```diff
            return function() {
-                const event = { id: id, this: this, args: arguments };
+                const event = { id: id, args: arguments };
                go._pendingEvent = event;
                go._resume();
                return event.result;
            };
```

If you are using `bind`, I would suggest simply passing in an argument to the function in order to adhere to JavaScript best practices. I'm not sure what the argument should be called since I don't have the full context of how this function is being used, but it would look something like this:

```diff
            return function(myObj) {
-                const event = { id: id, this: this, args: arguments };
+                const event = { id: id, myObj: myObj, args: arguments };
                go._pendingEvent = event;
                go._resume();
                return event.result;
            };
```

Maybe there is some reason the function can't be written that way? I'm not sure.

### What did you expect to see?

Again, I don't expect this file to compile without making changes since it wasn't written with TypeScript in mind. I was surprised by this particular error and I think it points to a potential bug.

### What did you see instead?

The TypeScript compiler complains about the usage of `this` inside an anonymous function.

**Comment by ALTree** [comment]
cc @neelance

**Comment by fabioberger** [comment]
Any update on this @neelance?

**Comment by neelance** [comment]
You don't have to use `bind`, it is much more common to assign the function to a property of some object and then call it as a method:
```js
const fn = function () { console.log("the answer:", this.answer); };
const deepThought = { answer: 42 };
deepThought.calculateAnswer = fn;
deepThought.calculateAnswer();
```
Since the wrapper function is meant to capture `this`, there is no other way to write it.

**Comment by albrow** [comment]
Ahh you're right. I didn't know about this additional quirk of `this`. I still need to find a way to satisfy the TypeScript compiler but that's my problem, not yours.
