### ISSUE TITLE
Environment configuration error

### ISSUE THREAD

**Issue by keienatinb** [golang/go#36594]
## What version of Go are you using (`go version`)?

<pre>
go version go1.13.4 windows/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?
windows and ubuntu16：04

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
</pre></details>

I want to set GO111MODULE = auto，But I wrote auto as AUTO
![image](https://user-images.githubusercontent.com/54785533/72501498-ee60c280-3871-11ea-9475-ba4bca9ee16f.png)

then
![image](https://user-images.githubusercontent.com/54785533/72501532-00dafc00-3872-11ea-8786-427a4588662b.png)

![image](https://user-images.githubusercontent.com/54785533/72501549-12240880-3872-11ea-87f1-915b3f7c3585.png)

I don't know how can I reset GO111MODULE.

**Comment by beoran** [comment]
Since this is on Windows, you can edit the environment variables as described here for GOPATH: 
https://github.com/golang/go/wiki/SettingGOPATH#windows
Please note that this issue tracker is not for asking questions, please see here:
https://github.com/golang/go/wiki/Questions

**Comment by keienatinb** [comment]
> 由于这是在Windows上，因此您可以按照以下针对GOPATH的 说明来编辑环境变量：
> [https](https://github.com/golang/go/wiki/SettingGOPATH#windows) : [//github.com/golang/go/wiki/SettingGOPATH#windows](https://github.com/golang/go/wiki/SettingGOPATH#windows)
> 请注意，此问题跟踪程序并非用于询问问题，请在此处查看：[https](https://github.com/golang/go/wiki/Questions) :
> [//github.com/golang/go/wiki/Questions](https://github.com/golang/go/wiki/Questions)

I'm so sorry,I also encountered this problem using ubuntu 16:04,Also, I restarted the cmd window, but the problem persists。

**Comment by ALTree** [comment]
Thanks for the report. 

You hit #34880, which was recently fixed (fix will be included in go1.14). The problem is that if you set a bad GO111MODULE  with go env -w, the go command itself becomes unusable.

In the meantime, you could try this:

First, manually set GO111MODULE to a correct value from the terminal, for example in powershell; that should temporarily fix `go env`, then you can try `go env -w again`, so run:

```
$env:GO111MODULE=off
```
and then:

```
go env -w GO111MODULE=off
```

Does that work?

**Comment by keienatinb** [comment]
> 感谢您的报告。
> 
> 您点击了[＃34880](https://github.com/golang/go/issues/34880)，该问题最近已得到修复（修复将包含在go1.14中）。问题是，如果使用go env -w设置了错误的GO111MODULE，则go命令本身将无法使用。
> 
> 在此期间，您可以尝试以下操作：
> 
> 首先，从端子（例如在powershell中）手动将GO111MODULE设置为正确的值；应该可以临时修复`go env`，然后您可以尝试`go env -w again`，运行：
> 
> ```
> $env:GO111MODULE=off
> ```
> 
> 接着：
> 
> ```
> go env -w GO111MODULE=off
> ```
> 
> 那样有用吗？

Thank you for your reply, I have solved this problem by manually configuring the environment variables
export GO111MODULE=auto
