### ISSUE TITLE
x/tools/gopls: add tests for references includeDeclaration setting

### ISSUE THREAD

**Issue by myitcv** [golang/go#36598]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +693748e9fa Mon Jan 6 11:46:56 2020 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20200116062425-473961ec044c
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.1.8-0.20200116062425-473961ec044c
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build642413689=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Prior to CL 211999, calling `References` would always return the definition of the identifier in question as the first reference. That appears to have changed with this CL.

Per previous work by Suzy, having the first location be the definition itself then allows the client to do custom sorting relative to the definition location.

I'm assuming this was an unintentional change?

### What did you expect to see?

The definition location for an identifier to always be returned as the first item in the returned list.

### What did you see instead?

Random locations (because the returned list has no defined order, despite it being a list)

---

cc @stamblerre @muirdm

FYI @leitzler

**Comment by stamblerre** [comment]
Submitted to fix the behavior ASAP, but re-opening to remind us to add tests for this case.
