### ISSUE TITLE
x/tools/internal/lsp/cmd: tests failing on darwin on all versions of Go

### ISSUE THREAD

**Issue by dmitshur** [golang/go#36604]
From https://build.golang.org/?repo=golang.org%2fx%2ftools, all darwin builders have recently started to fail on all supported versions of Go. It seems to have started with [CL 214419](https://golang.org/cl/214419). /cc @stamblerre

<details><br>

<img src=https://user-images.githubusercontent.com/1924134/72552939-cff4ca00-3865-11ea-9e75-b520429e97b2.png width=515>

</details>

**Comment by stamblerre** [comment]
This seems like the same error as I saw on the Android builders (which is why I disabled it). We have an I/O limit on file reads, but maybe not in the cmd tests? I'll look into it.

**Comment by stamblerre** [comment]
Things are looking better after https://go-review.googlesource.com/c/tools/+/215321. Closing.

**Comment by dmitshur** [comment]
Thanks Rebecca!
