### ISSUE TITLE
dev.boringcrypto branch behind the main releases (1.13.4b4 vs 1.13.6)

### ISSUE THREAD

**Issue by sodul** [golang/go#36611]
The latest release for dev.boringcrypto is 1.13.4b4, the latest official release is 1.13.6.

Most of the dev.boringcrypto releases happened fairly promptly after the official releases in 2019, is the plan moving forward to keep releaseing the dev.boringcrypto branches?

Pretty much what are the plans with dev.boringcrypto for 2020?

**Comment by sodul** [comment]
Ping. GoLang 1.13.7 was release a few days ago with 2 security fixes and unfortunately the dev.boringcrypto is still inactive since November 25 2019.

https://go.googlesource.com/go/+/dev.boringcrypto/misc/boring/RELEASES
https://go.googlesource.com/go/+/dev.boringcrypto

If this branch is being officially abandoned that would a be a big disappointment but knowing so would let us proactively plan to switch to an alternative solution for our needs.

**Comment by dmitshur** [comment]
@solul Thanks for the ping. There are plans to update these branches and make a BoringCrypto release, it just hasn't been done yet.

Let's wait to hear from @FiloSottile and @katiehockman.

**Comment by sodul** [comment]
I see that go1.13.7b4 is available. Thank you @FiloSottile and @dmitshur this is very much appreciated!

**Comment by FiloSottile** [comment]
Sorry for the delay!
