### ISSUE TITLE
os,fmt: Documentation should mention that os.Stdout, and fmt.Print* functions are unbuffered

### ISSUE THREAD

**Issue by kohlrabi** [golang/go#36619]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/terasa/.cache/go-build"
GOENV="/home/terasa/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/terasa/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build094455032=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.13.5 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.13.5
uname -sr: Linux 5.3.0-3-amd64
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Debian GLIBC 2.29-7) stable release version 2.29.
gdb --version: GNU gdb (Debian 8.3.1-1) 8.3.1
</pre></details>

### What did you do?

I just wanted to print formatted elements of an array, in this case I wanted to prepend a `0x` to every byte in my array. The idiomatic C routine goes somewhere along these lines:

`print.c`:
```
#include <stdio.h>

int main(int argc, char **argv)
{
    int i;
    unsigned char n[100000] = { 0 };

    for(i=0; i<100000; i++) {
        printf(" 0x%02x", n[i]);
    }
    printf("\n");

    return 0;
}
```

The performance measured by just running `time ./print` on my machine is
```
real	0m0.053s
user	0m0.018s
sys	0m0.005s
```

Naively using the same approach in go lead to disastrous performance:
`print_loop.go`:
```
package main

import "fmt"

func main() {
	var n [100000]byte

	for _, v := range n {
		fmt.Printf(" 0x%02x", v)
	}
	fmt.Printf("\n")
}
```
I `go build`, and then run the resulting binary with `time ./print_loop`:
```
real	0m0.373s
user	0m0.142s
sys	0m0.207s
```
I realize that printing all elements of a byte array is possible by using `"% x"` as format string, and passing the array to that completely, like `fmt.Printf("0x% x", n)`, but that is not exactly what I want, since it does not prepend `0x` to every byte.

I realized by "chance" and some googling (https://stackoverflow.com/questions/13422381/idiomatically-buffer-os-stdout, https://grokbase.com/t/gg/golang-nuts/158cgb3rfd/go-nuts-os-stdout-is-not-buffered=) that `os.Stdout` are **unbuffered** in go, so I immediately tried to use a `bufio.Writer`, and everything was "fine". This code is obviously much more verbose, and it is of **utmost importance** to not forget flushing the buffer, since it apparently does not happen automatically on leaving `main` (and thus exiting):

`print_buffer.go`:
```
package main

import (
	"bufio"
	"fmt"
	"os"
)

func main() {
	var n [100000]byte

	bufStdout := bufio.NewWriter(os.Stdout)
	defer bufStdout.Flush()

	for _, v := range n {
		fmt.Fprintf(bufStdout, " 0x%02x", v)
	}
	fmt.Fprintf(bufStdout, "\n")
}
```
This results in:
```
real	0m0.046s
user	0m0.025s
sys	0m0.000s
```

The issue is that neither the documentation on [`fmt.Print*`](https://golang.org/pkg/fmt/), nor the one on [`os.Stdout`](https://golang.org/pkg/os/) mention that I/O is **unbuffered**, and people using idiomatic C-style approaches to printing formatted output are in for a huge surprise. I certainly was dumbfounded as to why my simple go code performed so much worse than the equivalent C code.

### What did you expect to see?
I expect the documentation to mention the buffering behaviour of I/O operations for functions in `fmt`, and for `os.Stdin` and `os.Stdout`. The documentation for `fmt` could also link to the `os` documentation, i.e. mention explicitly that the **unbuffered** `os.Stdout` is used.

### What did you see instead?
Nothing.

**Comment by toothrot** [comment]
@kohlrabi thanks for writing this up.

> ... I immediately tried to use a bufio.Writer, and everything was "fine". This code is obviously much more verbose, and it is of utmost importance to not forget flushing the buffer, since it apparently does not happen automatically on leaving main (and thus exiting):

The flush behavior is documented for `bufio`:

> After all data has been written, the client should call the Flush method to guarantee all data has been forwarded to the underlying io.Writer.

I think this level of control is consistent with Go's API design of generally requiring the programmer to be explicit, and including tools like `defer` to make this easier to control.

I'm not sure if I agree on explicitly calling out that `*os.File` is unbuffered. Not all Go users are coming from C, and so may not have the expectation that `fmt.Printf` would be buffered.

/cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
I can't see how it makes sense to add any comment about buffering to the fmt package.

For the os package a short sentence or two somewhere might be OK.

**Comment by bitsofinfo** [comment]
agreed wasted hours of debugging on this...

**Comment by Nakilon** [comment]
It does not look to work as unbuffered. I launch the Go as a subprocess and see it puts `\n` randomly and even mixes the order.

**Comment by ianlancetaylor** [comment]
@Nakilon Unbuffered output means that concurrent output from multiple goroutines can be interleaved.

**Comment by Nakilon** [comment]
@ianlancetaylor ah, ok, I thought it means it gets flushed immediately preventing the mess.

But in my case I don't do anything concurrent, my program is pretty simple. It just accumulates JSON strings and then prints them out when asked. After this edit the issue appeared:

```diff
diff --git a/satellite.go b/satellite.go
index baec58d..479e769 100644
--- a/satellite.go
+++ b/satellite.go
@@ -12,7 +12,7 @@ func main() {
   var err error
   var line []byte
   var temp interface{}
-  var array []interface{}
+  var array [][]byte
   stdin := bufio.NewReader(os.Stdin)
   for {
     if c, err = stdin.ReadByte(); err != nil {
@@ -31,13 +31,10 @@ func main() {
       if err = json.Unmarshal(line, &temp); err != nil {
         panic(err)
       }
-      array = append(array, temp)
+      array = append(array, line)
     case 103:   // g print all and die
       fmt.Println(len(array));
-      for _, temp = range array {
-        if line, err = json.Marshal(temp); err != nil {
-          panic(err)
-        }
+      for _, line = range array {
         fmt.Println(string(line));
       }
       os.Exit(0)
```

Initially I was parsing the JSON strings (for other needs) and storing them in `[]interface{}` but then I decided that I don't need to store them parsed and started store byte sequences in `[][]byte` right as they come from the `stdin := bufio.NewReader(os.Stdin); stdin.ReadLine()`.  Now it inserts the `\n` instead of three other bytes (two commas and a digit) in one specific line at the same place whenever I run this. And if I add debug prints it even prints them in between where it put the corrupting `\n`.
Tried using `os.Stdout.Write` instead but the result is absolutely the same.
I wonder how to print to stdout in order.

**Comment by ianlancetaylor** [comment]
@Nakilon That is best discussed on a forum, not on this issue.  See https://golang.org/wiki/Questions.  Thanks.
