### ISSUE TITLE
cmd/go: why is the BurntSushi module stored as !burnt!sushi?

### ISSUE THREAD

**Issue by jadekler** [golang/go#36620]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/deklerk/go/bin"
GOCACHE="/Users/deklerk/Library/Caches/go-build"
GOENV="/Users/deklerk/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/deklerk/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/deklerk/workspace/exp/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/go-build653528057=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```
ls `go env GOPATH`/pkg/mod/github.com/
!burnt!sushi
```

### What did you expect to see?

```
ls `go env GOPATH`/pkg/mod/github.com/
BurntSushi
```

### What did you see instead?

```
ls `go env GOPATH`/pkg/mod/github.com/
!burnt!sushi
```

(ex: https://godoc.org/github.com/BurntSushi/xgb)

**Comment by myitcv** [comment]
See https://godoc.org/golang.org/x/mod/module#hdr-Escaped_Paths for the motivation but TL;DR the problem has its origins in:

> In general we cannot rely on file systems to be case-sensitive, nor can we rely on web servers, since they read from file systems

**Comment by myitcv** [comment]
I think this answers the question so I'll close the issue but shout if not.

**Comment by jadekler** [comment]
Thank you!
