### ISSUE TITLE
string is data type so while declaring implicitly it should not take string as variable name 

### ISSUE THREAD

**Issue by crombus** [golang/go#36625]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes , if we declare var string string="<>"
then we cannot declare anyother string in that code file.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/pulkitkundra/Library/Caches/go-build"
GOENV="/Users/pulkitkundra/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/pulkitkundra/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/w3/j7d_pjc12wv7b4b6nws8yrrw0000gn/T/go-build014613571=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
if we declare var string string="<>"
then we cannot declare anyother string in that code file.

### What did you expect to see?

it should not create string with var name as string.

### What did you see instead?
it is creating and further in code we are

**Comment by ALTree** [comment]
Hi,

`string` is not a keyword, but a [Predeclared Identifier](https://golang.org/ref/spec#Predeclared_identifiers). [Keywords are reserved](https://golang.org/ref/spec#Keywords):

> The following keywords are reserved and may not be used as identifiers. 

but Predeclared Identifiers are not. This a design choice, so the compiler is behaving as expected.

Closing here.
