### ISSUE TITLE
PATENTS: there may be a typo

### ISSUE THREAD

**Issue by perillo** [golang/go#36631]
The sentence
```
If you or your agent or exclusive licensee institute or
order or agree to the institution of patent litigation against any
entity ...
```
does not seem correct to me.  IMHO, there is an extra `or`.

**Comment by ianlancetaylor** [comment]
There are several "or"'s in there, but they all look right to me.  Which one do you think is extra?

**Comment by perillo** [comment]
You are right, sorry.  I assumed "institute" to be a noun instead of a verb.
