### ISSUE TITLE
x/sys/unix: pledge_openbsd.go lacks a function to pass nil for both promises and execpromises

### ISSUE THREAD

**Issue by estrogently** [golang/go#36638]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 openbsd/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/redacted/.cache/go-build"
GOENV="/home/redacted/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="openbsd"
GONOPROXY=""
GONOSUMDB=""
GOOS="openbsd"
GOPATH="/home/redacted/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/openbsd_amd64"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build858990023=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Passing nil to _promises_ or _execpromises_ prevents that value from being changed in the future (see [`pledge(2)`](https://man.openbsd.org/pledge.2). I wanted to prevent both _promises_ and _execpromises_ from being further modified.

### What did you expect to see?
For there to be a function to pass nil for both _promises_ and _execpromises_, akin to unveil_openbsd.go's [`UnveilBlock()`](https://github.com/estrogently/go/blob/master/unveil/unveil_openbsd.go#L9).

### What did you see instead?
Currently, to prevent future modification of _promises_ and _execpromises_, you need to call [`PledgePromises()`](https://github.com/golang/sys/blob/master/unix/pledge_openbsd.go#L66), which locks down _execpromises_, followed by [`PledgeExecpromises()`](https://github.com/golang/sys/blob/master/unix/pledge_openbsd.go#L98), which locks down _promises_.

This is rather unwieldy and requires you to re-specify your current _promises_ and _execpromises_ (as passing `""` to the above 2 functions would limit you to only being able to call [`_exit(2)`](https://man.openbsd.org/_exit.2)).

**Comment by esote** [comment]
I think you misunderstand what passing `NULL` to pledge does. It does not prevent future modification, for example try running:

```
#include <err.h>
#include <stdio.h>
#include <unistd.h>

int
main(void) {
	if (pledge(NULL, NULL) == -1) {
		err(1, "pledge");
	}
	if (pledge("stdio", "fork") == -1) {
		err(1, "pledge");
	}
	puts("hi");
	return 0;
}
```
This program will execute successfully. From the manual you link:

> Passing `NULL` to _promises_ or _execpromises_ specifies to not change the current value

This behavior is usually used to restrict one of the parameters without changing the other, for example restricting _promises_ without changing the existing _execpromises_ pledges.

As the function documentation says on [`PledgePromises()`](https://github.com/golang/sys/blob/master/unix/pledge_openbsd.go#L66) and [`PledgeExecpromises()`](https://github.com/golang/sys/blob/master/unix/pledge_openbsd.go#L98), these functions leave the other argument untouched.

The blocking behavior of unveil is specific to that syscall. As far as I know, the pledge syscall provides no mechanism to restrict future calls to itself.

**Comment by estrogently** [comment]
Ah, my bad, thank you for the education @esote!
