### ISSUE TITLE
x/tools/gopls: support non-vet analyses

### ISSUE THREAD

**Issue by hnlq715** [golang/go#36639]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\liqi\AppData\Local\go-build
set GOENV=C:\Users\liqi\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=git.dz11.com
set GONOSUMDB=git.dz11.com
set GOOS=windows
set GOPATH=F:\gopath
set GOPRIVATE=git.dz11.com
set GOPROXY=https://mirrors.aliyun.com/goproxy/
set GOROOT=C:\Go
set GOSUMDB=off
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=F:\gopath\src\dubbo-samples\golang\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\liqi\AppData\Local\Temp\go-build457304122=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you expect to see?
just like https://github.com/golang/tools/tree/master/go/analysis/passes/nilness
support nilness detection for code analysis

**Comment by stamblerre** [comment]
Thanks for raising this issue! I think we can expand its scope to include all of the analyses in https://github.com/golang/tools/tree/master/go/analysis/passes.

@ianthehat, @matloob: Is there any reason we haven't added them before / any reason to exclude them?

**Comment by matloob** [comment]
I don't know what the reason was that we hadn't added them before, but my guess was that we started conservative when we added the initial set, and just neglected to add others when we expanded the set of analyses we used to include non-vet analyses.

**Comment by stamblerre** [comment]
Closing this issue as we've added `nilness`, `deepequalerrors`, `errorsas`, and `testinggoroutine`.
