### ISSUE TITLE
go/token: articulate what "base offset" is in FileSet.AddFile docs

### ISSUE THREAD

**Issue by jadekler** [golang/go#36648]
https://golang.org/pkg/go/token/#FileSet.AddFile

> AddFile adds a new file with a given filename, base offset, [...]

What is "base offset"? How does one calculate it? There are only self-references in this godoc, and Google search doesn't return anything obviously useful.

**Comment by ianlancetaylor** [comment]
Assigning to @griesemer for a doc update.

**Comment by griesemer** [comment]
@jadekler A `token.Pos` is simply a byte offset from a file's base offset, which is the offset corresponding to the file's first byte. The next file's base offset is usually the current file's base offset plus the file size + 1 (for padding). This maps a set (list) of files' positions to contiguous integer values. Usually you don't need to worry about this, just provide a negative value (-1) and `AddFile` will take care of it.

I'll add a bit more documentation.

**Comment by jadekler** [comment]
Thank you! This helps a lot.

**Comment by ianlancetaylor** [comment]
@griesemer Still want to do this doc fix for 1.15?
