### ISSUE TITLE
Custom type braces in if statement

### ISSUE THREAD

**Issue by guiguan** [golang/go#36645]
This will lead to a compilation error (`expected ';', found '{'`):

```go
type Hash [32]byte

func main() {
  a := Hash{}
  if a == Hash{} {
  }
}
```

The workaround is to surround it with parentheses:

```go
type Hash [32]byte

func main() {
  a := Hash{}
  if a == (Hash{}) {
  }
}
```

However, the primitive type works fine without parentheses:

```go
type Hash [32]byte

func main() {
  a := Hash{}
  if a == [32]byte{} {
  }
}
```

Is this a parsing bug or expected behavior?

**Comment by kortschak** [comment]
This is [expected behaviour](https://golang.org/ref/spec#Composite_literals);

> A parsing ambiguity arises when a composite literal using the TypeName form of the LiteralType appears as an operand between the keyword and the opening brace of the block of an "if", "for", or "switch" statement, and the composite literal is not enclosed in parentheses, square brackets, or curly braces. In this rare case, the opening brace of the literal is erroneously parsed as the one introducing the block of statements. To resolve the ambiguity, the composite literal must appear within parentheses.

**Comment by guiguan** [comment]
@kortschak okay, thank you
