### ISSUE TITLE
net/http: Client support for Expect: 100-continue

### ISSUE THREAD

**Issue by bradfitz** [golang/go#3665]
<pre>The http Client should probably support Expect: 100-continue.  The server does.

It does introduce a new round-trip, though, so we should probably only send it when the
data size exceeds some threshold.  Probably the same threshold we use for consuming
request bodies when a handler doesn't (maxPostHandlerReadBytes).

I think we could see if we know the size of the request body (just as NewRequest does,
checking for a few known types), but if the Body is non-nil and the ContentLength is
&lt;=0 (unknown), we instead slurp up the Body into a bytes.Buffer to see if it's &gt;=
someThreshold.  If so, we replace the Body with a io.MultiReader(slurped, rest) and
proceed to do a 100-continue.  If not, we blast it away HTTP/1.0-style.</pre>

**Comment by anacrolix** [comment]
I believe this is the cause for issues I'm having PUT-ing to a server that redirects me. The body in the initial PUT request is prematurely consumed, despite my having set Expect: 100-continue. If there is Expect: 100-continue in the request, the body needs to be withheld from the request until a 100 Continue is received from the server.

**Comment by matope** [comment]
Although I'm not sure if it were a right implementation, I've sent my small patch for this issue.
https://go-review.googlesource.com/#/c/10091/

**Comment by mattn** [comment]
@bradfitz ping

**Comment by bradfitz** [comment]
The Go tree is currently in freeze for the Go 1.5 release. The freeze started on May 1st, and this was sent after May 1st, and this was not tagged as a Go 1.5-blocking issue.

As such, this has to wait until Go 1.6.

I've marked that CL with R=close so it doesn't show up on our dashboard, but pinging this thread at any time will make it reappear. Please reply to this bug after August 1st and we can begin the code review.

Thanks for working on this, though!

**Comment by matope** [comment]
@bradfiz OK, I catch on your timeline. I'll ping you again this August!

@mattn Thanks for your pinging!

**Comment by rhinoman** [comment]
I've been having issues with this as welI (using Go with CouchDB) and I really hope this gets in sometime so I can remove the ugly hack-around in my code :+1:

**Comment by drnic** [comment]
For golang-backed servers, is there a way to increase the max size before it starts the `100-continue` protocol?

**Comment by drnic** [comment]
My body seems to be only 2000+ characters of JSON, so am not sure what triggers to `100-continue` sequence (and causes my golang client to hang until timeout)

**Comment by anacrolix** [comment]
@bradfitz can we get this in now?

**Comment by bradfitz** [comment]
I replied with some initial review feedback.

**Comment by matope** [comment]
@bradfitz Thank you for your feedback! I revised my patch a few weeks ago.
I think my patch got better but I'm not sure if it is enough.
If you are free, could you please look through that?

**Comment by bradfitz** [comment]
Replied on Gerrit.

**Comment by matope** [comment]
@bradfitz Thank you for your review comments. 

I've just updated my CL on Gerrit.
I fixed a issue that my previous code couldn't flush request header before waiting response.
I added some explicit codes for canceling sending body when the response status was not 100.
