### ISSUE TITLE
what is a number

### ISSUE THREAD

**Issue by sguillia** [golang/go#36652]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
If 1.13.6 is the latest, yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/user/go/bin"
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/user/Applications/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/Applications/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build572282906=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/HtKRTnckwXN

**main.go**
```go
package main

func foo(a, b string) {

}

func main() {
        foo(42)
}
```

```
$ go build
```

### What did you expect to see?

```
$ go build
# _/home/user/prog/go-repro
./main.go:8:5: not enough arguments in call to foo
        have (int)
        want (string, string)
```

### What did you see instead?
```
$ go build
# _/home/user/prog/go-repro
./main.go:8:5: not enough arguments in call to foo
        have (number)
        want (string, string)
```

Just wondering why `number` instead of `int` :blush: 

 number does not seem to be a basic type: https://tour.golang.org/basics/11

**Comment by proyb6** [comment]
When you read this,
http://www.differencebetween.info/difference-between-integer-and-number

`number` is correct in my opinion.

**Comment by OneOfOne** [comment]
There's from `gopls`, not `vscode-go`, also it says number because at that point in the program, `42` is an untyped constant, it's not just an `int`.

Read more about untyped constants: 

- https://blog.golang.org/constants
- https://stackoverflow.com/a/22625253/145587

**Comment by sguillia** [comment]
Thank you @OneOfOne
