### ISSUE TITLE
cmd/go: get error for symlinks in GOPATH

### ISSUE THREAD

**Issue by sguillia** [golang/go#36653]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
If 1.13.6 is the latest, yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/sg/go/bin"
GOCACHE="/home/sg/.cache/go-build"
GOENV="/home/sg/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/sg/Applications/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/sg/Applications/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build163278137=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

**Step 1**
Create the `/home/user` directory so you can reproduce in a clean environment

**Step 2**
`export GOPATH=/home/user/go`

**Step 3**
Set-up the following hierarchy

tree view
```
$ tree /home/user
/home/user
├── go
│   └── src
│       └── github.com
│           └── sguillia
│               └── foo -> /home/user/projects/foo
└── projects
    └── foo
        ├── bar
        │   └── bar.go
        └── main.go
```

find view
```
$ find /home/user
/home/user
/home/user/projects
/home/user/projects/foo
/home/user/projects/foo/bar
/home/user/projects/foo/bar/bar.go
/home/user/projects/foo/main.go
/home/user/go
/home/user/go/src
/home/user/go/src/github.com
/home/user/go/src/github.com/sguillia
/home/user/go/src/github.com/sguillia/foo
```

main.go

```go
package main

import "github.com/sguillia/foo/bar"

func main() {
	bar.Bar()
}
```

bar.go

```go
package bar

import "fmt"

func Bar() {
	fmt.Println("Hello world")
}
```

 `/home/user/go/src/github.com/sguillia/foo` is a symlink to `/home/user/projects/foo`

**Step 4**

```
cd /home/user/projects/foo
go get -d -u .
```

### What did you expect to see?

I expected go to update `foo`, as if there was no symlink.

### What did you see instead?

```
package _/home/user/projects/foo: unrecognized import path "_/home/user/projects/foo" (import path does not beg
in with hostname)
```

### Additional notes

When removing the symlink, it works fine. Here is a working hierarchy:

tree view

```
$ tree /home/user
/home/user
├── go
│   └── src
│       └── github.com
│           └── sguillia
│               └── foo
│                   ├── bar
│                   │   └── bar.go
│                   └── main.go
└── projects
```

find view

```
/home/user
/home/user/projects
/home/user/go
/home/user/go/src
/home/user/go/src/github.com
/home/user/go/src/github.com/sguillia
/home/user/go/src/github.com/sguillia/foo
/home/user/go/src/github.com/sguillia/foo/bar
/home/user/go/src/github.com/sguillia/foo/bar/bar.go
/home/user/go/src/github.com/sguillia/foo/main.go
```

I can do `go get -d -u .` from within `/home/user/go/src/github.com/sguillia/foo`.

But I believe I should be able to do it also with the previous hierarchy.

### Note

Actually I don't care about go updating `foo`, I can just git pull. I'd like go to update the possible other dependencies of the project, and this bug or unimplemented feature prevents the update of other dependencies whose folder layout is supported.

Best

**Comment by toothrot** [comment]
Have you tried using Go Modules? The `replace` directive supports this flow explicitly. 
See https://github.com/golang/go/wiki/Modules#gomod and https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive
