### ISSUE TITLE
cmd/compile: cannot regenerate rules files using non-tip compiler

### ISSUE THREAD

**Issue by josharian** [golang/go#36663]
Until recently, it was possible to use a non-tip compiler to regenerate the rules files. This is important, since it (a) prevents you from needing tip to compile to regenerate rules and (b) allows you to use a stable compiler.

That no longer works. Using 1.13 I get:

```
$ go run *.go
build command-line-arguments: cannot load cmd/internal/obj/riscv: package cmd/internal/obj/riscv is not in GOROOT (/Users/josh/go/1.13/src/cmd/internal/obj/riscv)
```

Using 1.14 beta 1, I get:

```
$ go run *.go
RISCV64Ops.go:9:8: use of internal package cmd/internal/obj/riscv not allowed
```

cc @randall77 @4a6f656c

**Comment by 4a6f656c** [comment]
@josharian - I guess we'll just have to duplicate the register names and numbers, like the other platforms do...

**Comment by josharian** [comment]
@4a6f656c yes. unfortunate, but there you are.

**Comment by josharian** [comment]
I'd really like this to get fixed soon. It is a serious annoyance when working on rules.
