### ISSUE TITLE
x/tools/gopls: "reply not invoked with a valid call" error showing up

### ISSUE THREAD

**Issue by muirdm** [golang/go#36662]
I've started to see the `reply not invoked with a valid call` error in gopls stderr output on master. We seem to be attempting to reply to "$/cancelRequest" notifications after changes in https://go-review.googlesource.com/c/tools/+/214582 .

/cc @heschik

**Comment by heschik** [comment]
Thanks for the initial diagnosis, I'd noticed this but not gotten around to investigating.
