### ISSUE TITLE
x/mobile/cmd/gomobile: gomobile init fails in an empty module

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#36668]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hajimehoshi/Library/Caches/go-build"
GOENV="/Users/hajimehoshi/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/hajimehoshi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ht/ky_bwgzs4bd5z1hh02k34x_h0000gn/T/go-build725172147=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

1. Create an empty directory and go.mod file

```
$ mkdir gomobileinit
$ cd gomobileinit
$ go mod init foo
```

2. Run gomobile init

```
$ gomobile init
```

### What did you expect to see?

No errors.

### What did you see instead?

```
$ gomobile init
gomobile: exit status 1
```

The cause is that go-list fails with an empty module:

```
$ go list -e -f '{{range context.ReleaseTags}}{{if eq . "go1.14"}}{{.}}{{end}}{{end}}'
build .: cannot find module for path .
```

With a Go file only with `package main` in the directory, this succeeds.

CC @hyangah

**Comment by hajimehoshi** [comment]
CC @matloob

**Comment by matloob** [comment]
You're running the go list command from gomubile, right?

When you run the command `go list -e -f '{{range context.ReleaseTags}}{{if eq . "go1.14"}}{{.}}{{end}}{{end}}'` you're implicitly telling go list to list the package `.`, the current directory. And that package doesn't exist so go mobile complains.

If you want that command to always succeed you can add a package you know always to exist, such as something in the standard library.

**Comment by hajimehoshi** [comment]
> When you run the command `go list -e -f '{{range context.ReleaseTags}}{{if eq . "go1.14"}}{{.}}{{end}}{{end}}'` you're implicitly telling go list to list the package ., the current directory. And that package doesn't exist so go mobile complains.

Yes, that's right. I wanted to confirm this was expected. It was a little surprise that just checking the release tag failed in an empty module.

**Comment by hajimehoshi** [comment]
FYI, the behavior is different between Go 1.14 and older.

```
$ go list -e 
build .: cannot find module for path .

$ go1.14beta1 list -e 
_/Users/hajimehoshi/test/empty
```
