### ISSUE TITLE
cmd/go: get fails to use ssh on non-standard port for private repos

### ISSUE THREAD

**Issue by Tatsujinichi** [golang/go#36666]
### What version of Go are you using (`go version`)?

go version go1.13.6 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### What did you do?

private gitlab repo, accessible only through ssh, via non-standard port
go get will continue to try to use port 22
 
Because you can not specify a port anywhere besides the .gitconfig using url insteadOf
There is no nice way around this.
I tried using the port in GOPRIVATE envvar, but no good.

I expect that "go get" would allow me to specifying a port.  Right now that is not allowed.

**Comment by bcmills** [comment]
> ### What did you do?

In that section of the issue report, please describe the specific commands that you executed in enough detail that we can reproduce the problem you're having. A general description is usually not sufficient.

> Because you can not specify a port anywhere besides the .gitconfig using url insteadOf

Note that you _can_ specify a port in your global `.gitconfig`. Beyond that, if you want to customize the way that the `go` command resolves an import path to a repo location and protocol, you'll need to use an HTTPS server as described in https://tip.golang.org/cmd/go/#hdr-Remote_import_paths.

At this time, we are not likely to add further customization points beyond that protocol. If you believe that you have a compelling use-case, please add an [experience report](https://blog.golang.org/toward-go2#TOC_5.3.) describing it — and also describing why the existing alternatives are not suitable.

**Comment by dnutiu** [comment]
I have the same problem.
I use the company's Bitbucket server which is using ssh over a non-standard port which means any port except port 22. Port 5555 for example.

I tried 
```
➜  export GOPRIVATE="bitbucket.xxx.com/proj/lib"                                         
➜  git config --global url."git@bitbucket.xxx.com:5555".insteadOf "https://bitbucket.xxx.com"
```

but when I run `go get ./...` I get:

```
ssh: connect to host bitbucket.xxx.com port 22: No route to host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
package bitbucket.xxx.com/proj/lib/module: exit status 128
```
