### ISSUE TITLE
cmd/go: go help packages should document that in module mode import paths must be fully qualified 

### ISSUE THREAD

**Issue by perillo** [golang/go#36680]
`go help packages`, for go1.13.6, also available at
https://golang.org/pkg/cmd/go/#hdr-Package_lists_and_patterns,
in an example about a *unique prefix that belongs to you*, says:
```
For example, paths used internally at Google all begin with 'google'
```

I don't know if *Google* is still using `'google'` and *GOPATH mode*.  However I think the documentation should say (here or somewhere else) that in *module mode* non fully qualified import path like `'google'` are rejected by the go tool.

**Comment by toothrot** [comment]
The linked documentation does recommend reading `go help importpath`, which covers this in some detail. 

Relative import paths are also supported: https://golang.org/cmd/go/#hdr-Relative_import_paths

**Comment by perillo** [comment]
Just to clarify, I'm referring to the error message emitted by `go build`:
```
cannot load google/xxx: malformed module path "google/xxx": missing dot in first path element
```

However, I noted that `go mod init google/xxx` does not report problems.
Also if in a source file inside `google/xxx` I import `google/xxx/a`, `go build` does not complain.

So non qualified importpath are allowed if they belong to the current module, but disallowed if they belong to an external required module.  In this case the example in the documentation is valid, probably.
