### ISSUE TITLE
x/build: cmd/gitmirror not mirroring proposal repository

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#36682]
The most recent changes to https://go.googlesource.com/proposal are not being mirrored to https://github.com/golang/proposal.  The latest change on the latter is from October 23, 2019.  The lasest change on the former is from today (January 21, 2020).

CC @toothrot @dmitshur

**Comment by dmitshur** [comment]
Looking. [farmer.golang.org](https://farmer.golang.org) is currently reporting that gitmirror status is "ok". Something must be wrong.

**Comment by dmitshur** [comment]
From logs:

```
2020/01/17 18:02:20 Not mirroring repo proposal
```

This might be a misconfiguration.

**Comment by dmitshur** [comment]
More repos that aren't being mirrored from logs:

```
2020/01/17 18:02:20 Not mirroring repo grpc-review
2020/01/17 18:02:20 Not mirroring repo gollvm
2020/01/17 18:02:20 Not mirroring repo sublime-build
2020/01/17 18:02:20 Not mirroring repo proposal
2020/01/17 18:02:20 Not mirroring repo sublime-config
```

However, they should be mirrored per https://github.com/golang/build/blob/d3fb66653c7bebb6834247367b68f647100d98b5/repos/repos.go#L55-L58.

`cmd/gitmirror` was last deployed 46 days ago. I think it just needs to be redeployed to pick up the changes from [CL 210461](https://golang.org/cl/210461) where "proposal" and other repos were added to be mirrored.

**Comment by dmitshur** [comment]
After redeploying:

```
2020/01/21 22:42:43 Not mirroring repo grpc-review
2020/01/21 22:42:43 Not mirroring repo gollvm
```

This is consistent with the configuration in the latest version of the `golang.org/x/build/repos` package (see [here](https://github.com/golang/build/blob/d3fb66653c7bebb6834247367b68f647100d98b5/repos/repos.go#L90-L91)).

The proposal, sublime-build, and sublime-config repos should be mirrored now. I'll close this as resolved, but please let me know if there's anything more to do here.
