### ISSUE TITLE
build: bootstrap build of go fails on windows amd64

### ISSUE THREAD

**Issue by lovettchris** [golang/go#36691]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

trying to use the go bootstrap version 1.4 (as per https://golang.org/doc/install/source) to build the latest go sources.  But it fails.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCHAR=6
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=
set GORACE=
set GOROOT=c:\go
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

</pre></details>

### What did you do?

Downloaded and unpacked go1.4.windows-amd64.zip to c:\go
set GOROOT_BOOTSTRAP=c:\go
set GOROOT_FINAL=d:\go
cloned the latest github.com/golang/go
cd src
all.bat

### What did you expect to see?

Successful build of the new version of go.

### What did you see instead?

d:\git\golang\go\src>all.bat
Building Go cmd/dist using c:\go
Building Go toolchain1 using c:\go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for windows/amd64.
// runtime/cgo
gcc_libinit_windows.c: In function 'x_cgo_sys_thread_create':
gcc_libinit_windows.c:57:12: error: implicit declaration of function '_beginthread'; did you mean 'OpenThread'? [-Werror=implicit-function-declaration]
  thandle = _beginthread(func, 0, arg);
            ^~~~~~~~~~~~
            OpenThread
cc1: all warnings being treated as errors
go: failed to remove work dir: GetFileInformationByHandle C:\Users\Chris\AppData\Local\Temp\go-build549624342\NUL: Incorrect function.
go tool dist: FAILED: d:\git\golang\go\pkg\tool\windows_amd64\go_bootstrap install -gcflags=all= -ldflags=all= std cmd: exit status 2
The system cannot find the batch label specified - fail
go: failed to remove work dir: GetFileInformationByHandle C:\Users\Chris\AppData\Local\Temp\go-build900619142\NUL: Incorrect function.

**Comment by ALTree** [comment]
This is caused by the the gcc toolchain you are using. 

What is it?

**Comment by ianlancetaylor** [comment]
Anyone know if `_beginthread` is declared in any standard Windows header file?

**Comment by ALTree** [comment]
Win docs says <process.h>

**Comment by ianlancetaylor** [comment]
Hmmm, we already `#include <process.h>` in runtime/cgo/gcc_libinit_windows.c.

**Comment by ALTree** [comment]
I don't know if this is useful, but I've seen that error in the past when trying to build from source on windows with a cygwin gcc (which anyway is not officially supported for bootstrapping Go on windows)

**Comment by bradfitz** [comment]
See also all the related conversation in #35006.

This might even be a dup.

**Comment by alexbrainman** [comment]
> See also all the related conversation in #35006.

I agree https://github.com/golang/go/issues/35006#issuecomment-546573751 might help.

@lovettchris download http://musl.cc/x86_64-w64-mingw32-native.zip, unzip it anywhere, add bin subdirectory to your PATH, and try again.

You can also

set CGO_ENABLED=0

and that will build Go without any gcc installed. You won't be able to do Cgo, if you do that.

Thank you.

Alex
