### ISSUE TITLE
bytes: TestGrow is flaky

### ISSUE THREAD

**Issue by bcmills** [golang/go#36695]
[2020-01-19T20:36:10-df2999e/android-arm-corellium](https://build.golang.org/log/cf93614cc6aa6a6990f0d2966dfc320313dbd08e)

See previously #24647. The fix for that issue (in [CL 104235](https://golang.org/cl/104235)) only seems to have been applied to the `strings` package, not `bytes` — it probably just needs to be ported over.

(CC @dmitshur @toothrot @cagedmantis)

**Comment by bradfitz** [comment]
There is no bytes.Builder.

**Comment by bcmills** [comment]
Correct, but the problem we fixed with `strings.Builder` maps cleanly onto `bytes.Buffer`.

**Comment by HowJMay** [comment]
May I give it a try?

**Comment by bcmills** [comment]
@HowJMay, sure!

**Comment by HowJMay** [comment]
May I ask how can I run this test?

**Comment by HowJMay** [comment]
I have pushed a PR for this issue.
