### ISSUE TITLE
x/tools/gopls: race in updateAnalyzers

### ISSUE THREAD

**Issue by stamblerre** [golang/go#36699]
Seen on [CL 215743](https://go-review.googlesource.com/c/tools/+/215743), which was not related.

This is specific to the tests in `golang.org/x/tools/gopls/test`, because they pass an options modification function (with the signature `func(*source.Options)`) that updates the analyzers map. All of the command tests use this type of function, but only the gopls/test ones modify a map. A possible solution would be to have a mutex on the options before modifying them.

**Comment by stamblerre** [comment]
I'm actually not sure how to fix this effectively since all of the fields in the options are exported. 
@heschik, @ianthehat: Do you have any suggestions here?

**Comment by heschik** [comment]
I set `GORACE=history_size=7` and had no luck getting the other side of the race.

**Comment by stamblerre** [comment]
After offline discussion with @ianthehat, @heschik will look into the possibility of setting `GORACE=history_size` to a much higher value so that we can see where the previous write is.

**Comment by zikaeroh** [comment]
#36872's logs actually show the other side of the race:

```
Previous read at 0x00c0001ce168 by goroutine 911:
  golang.org/x/tools/internal/lsp/source.analyses()
      /tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/source/diagnostics.go:183 +0x174
  golang.org/x/tools/internal/lsp/source.Diagnostics()
      /tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/source/diagnostics.go:91 +0x739
  golang.org/x/tools/internal/lsp.(*Server).diagnose.func1.1()
      /tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/diagnostics.go:58 +0x1cb
```
