### ISSUE TITLE
cmd/dist: error when GOROOT is inside a module

### ISSUE THREAD

**Issue by marwan-at-work** [golang/go#36701]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14beta1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, go1.14beta1 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/marwansulaiman/Library/Caches/go-build"
GOENV="/Users/marwansulaiman/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB="obstructed..."
GOOS="darwin"
GOPATH="/Users/marwansulaiman/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/marwansulaiman/marwan/uhh/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qs/msp1047d0yz4dgtrnp5rnhdc0000gn/T/go-build178043932=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

1. Go to golang.org/dl and download the Go1.14beta1 for MacOS. Specifically `go1.14beta1.darwin-amd64.pkg` 

2. `git clone https://go.googlesource.com/go`

3. `cd go/src` 

4. `./make.bash`

### What did you expect to see?

Go successfully compiles

### What did you see instead?

```
./make.bash
Building Go cmd/dist using /usr/local/go. (go1.14beta1 darwin/amd64)
Building Go toolchain1 using /usr/local/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
go: github.com/DataDog/datadog-go@v3.2.0+incompatible: no http in bootstrap go command
go tool dist: FAILED: /Users/marwansulaiman/marwan/uhh/go/pkg/tool/darwin_amd64/go_bootstrap install -gcflags=all= -ldflags=all= -i cmd/asm cmd/cgo cmd/compile cmd/link: exit status 1
```

**Comment by ianlancetaylor** [comment]
Do any of the parents of the directory in which you are doing the build contain a `go.mod` file that refers to `github.com/DataDog`?

CC @bcmills @jayconrod

**Comment by marwan-at-work** [comment]
@ianlancetaylor bingo! 😄 

I accidentally had a go.mod file a few parent directories up...I wonder if make.bash can catch that by any chance? 

Running `go list -m -json` showed that to me as well 

```
go list -m -json
{
	"Path": "one",
	"Main": true,
	"Dir": "/Users/marwansulaiman/marwan",
	"GoMod": "/Users/marwansulaiman/marwan/go.mod",
	"GoVersion": "1.13"
}
```
