### ISSUE TITLE
doc/go1.14: RISC-V status

### ISSUE THREAD

**Issue by ainar-g** [golang/go#36708]
<p>
(I'm not sure if making issues about draft documents is allowed, so
please feel free to close.)
</p>
<p>
<a href="https://tip.golang.org/doc/go1.14">https://tip.golang.org/doc/go1.14</a>
doesn't seem to mention the new RISC-V port anywhere.  AFAIK, the port
will probably enter Go 1.14 in some way, even if highly experimental, so
I think it needs to be documented.
<p>

**Comment by bradfitz** [comment]
Thanks for filling!

**Comment by toothrot** [comment]
(just posting this for bookkeeping, the RISC-V port is tracked in #27532)

/cc @4a6f656c

**Comment by josharian** [comment]
One item in particular the release notes should call out is that the assembly syntax may not yet be finalized. See https://github.com/riscv/riscv-go/issues/5. AFAICT, that has not been addressed during upstreaming.
