### ISSUE TITLE
x/website/go.dev/_content/blog: auto-deploy latest master version

### ISSUE THREAD

**Issue by dmitshur** [golang/go#36707]
Currently, when a blog post is being published to [blog.golang.org](https://blog.golang.org), it needs to go through code review in Gerrit, get +2ed, and then submitted to the master branch. Afterwards, someone on the @golang/osp-team needs to manually redeploy the blog.

Even though the process to deploy the blog has been [simplified](https://github.com/golang/blog#deploying), it's still manual effort and a context switch. It requires more coordination.

I propose we automate this process so that the latest `master` commit of x/blog repo is always published to blog.golang.org. That will mean to publish a new blog post, one needs only to submit the Gerrit change. Fixing up typos can also be done by fixing the `master` branch, and not require additional redeploys.

This can be implemented by reusing the [`golang.org/x/build/cmd/tip`](https://pkg.go.dev/golang.org/x/build/cmd/tip) server that does automatic deploys for [tip.golang.org](https://tip.golang.org) and [talks.golang.org](https://talks.golang.org).

Thoughts?

**Comment by toothrot** [comment]
This is great. Hopefully it is as easy as the simple `master` scenario from #32606.

**Comment by dmitshur** [comment]
An update on this issue. I brought it up and discussed it while talking with @rsc today.

We were in agreement that doing this should be reasonable, given some pre-conditions:

- we should create a separate permission group for people who can +2/submit CLs in x/blog instead of reusing the same group of people who have +2/submit rights for code in all other repos
- we should communicate this change clearly to those people before it is implemented, so that everyone who is responsible for publishing blog posts is aware that submitting a post CL to master branch will cause it to be auto-deployed

Based on that conversation and the 👍 reactions from @toothrot, @cagedmantis, and @bcmills, I think it should be reasonable to move this issue from NeedsDecision to NeedsFix state. I'll wait 7 days to give people a chance to comment further before doing that.

Implementation details can be investigated and discussed after we agree that it is okay auto-deploy latest master blog content. Some of the options available include reusing `golang.org/x/build/cmd/tip`'s auto-deploy functionality, reusing the playground's auto-deploy approach as @toothrot suggested in the comment above, or coming up with something else.

**Comment by dmitshur** [comment]
Russ is making progress towards this now, [CL 321670](https://golang.org/cl/321670) being one step.
