### ISSUE TITLE
all: switch to Go 1.14 as default inside Google

### ISSUE THREAD

**Issue by bradfitz** [golang/go#36717]
Tracking bug for switching to Go 1.14 inside Google.

When all internal blocking bugs & performance regressions are fixed and the default is flipped, then this can be closed.

This is a blocker for rc1, per our normal policy. (rc1 == Google's using it themselves already)

/cc @andybons @ianlancetaylor @griesemer @dmitshur @toothrot @neild

**Comment by neild** [comment]
The switch has been flipped.
