### ISSUE TITLE
os.Setenv does not set the environment in defer

### ISSUE THREAD

**Issue by netbrain** [golang/go#36724]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/netbrain/.cache/go-build"
GOEXE=""
GOFLAGS=" -mod="
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/netbrain/dev/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/netbrain/dev/doams/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build101884634=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```
func env() func() {
	os.Setenv("FOO", "BAR")
	return func() {}
}

func TestThatEnvVarIsPresent(t *testing.T) {
	env()
	if os.Getenv("FOO") != "BAR" {
		t.Fatal("expected env var to be present")
	}
}

func TestThatEnvVarIsPresentInDefer(t *testing.T) {
	defer env()
	if os.Getenv("FOO") != "BAR" {
		t.Fatal("expected env var to be present")
	}
}

=== RUN   TestThatEnvVarIsPresent
--- PASS: TestThatEnvVarIsPresent (0.00s)
=== RUN   TestThatEnvVarIsPresentInDefer
--- FAIL: TestThatEnvVarIsPresentInDefer (0.00s)
    defer_test.go:23: expected env var to be present
FAIL

```
For some reason, this does however work on the playground
https://play.golang.org/p/fuvbQDm5MtI

### What did you expect to see?
Passing tests

### What did you see instead?
The last test failed

**Comment by AlexRouSg** [comment]
`defer env()` doesn't run `env()` until afater the parent function returns. If you did `defer env()()`, `env()` will be called at that line but the function returned by `env()` will not be called until the parent function returns. 

The reason it runs in the playground is that it runs `TestThatEnvVarIsPresent` before `TestThatEnvVarIsPresentInDefer` so the env var is already set before the function was even called. See https://play.golang.org/p/FimDEGG58ah

**Comment by netbrain** [comment]
Hah, thank you, this makes perfect sense now.

**Comment by RicohRick** [comment]
<<love yourself & rem mat 12:12"..
