### ISSUE TITLE
go module no matching versions for query "latest"

### ISSUE THREAD

**Issue by maxnosib** [golang/go#36729]
created a new "dictionary" package
plugged it in another package "handlers"
both packages are in the "internal" folder

$ go build
go: finding api.git/internal/dictionary latest
go: finding api.git/internal latest
build api.git: cannot load api.git/internal/dictionary: no matching versions for query "latest"

I don’t understand why he doesn’t perceive it as a project package but try to pull off as if an external dependence

**Comment by maxnosib** [comment]
sorry the problem was in the name of the package directory which did not match the name of the package

**Comment by kr-jaydeepp** [comment]
Can't package name be different from directory which holds the package ?

**Comment by harai** [comment]
From iOS 14 onward, Safari officially supports WebP along with the corresponding `Accept` header value `image/webp`.

The only remaining major OS/browser which doesn't support WebP is macOS Safari.

# Ref

* https://blog.ideamans.com/2020/07/ios14-webp-picture-accept.html
* https://tarosky.slack.com/archives/C015ZBT459B/p1608510291000100?thread_ts=1607492541.001300&cid=C015ZBT459B

**Comment by gastrodon** [comment]
@harai How is this relevant?
