### ISSUE TITLE
net/http: support status code 102 (Processing) in ResponseWriter

### ISSUE THREAD

**Issue by majewsky** [golang/go#36734]
HTTP status code 102 (Processing) is defined by [RFC 2518, section 10.1](https://tools.ietf.org/html/rfc2518#section-10.1):

> This status code SHOULD only be sent when the server has a reasonable expectation that the request will take significant time to complete. [...] The server MUST send a final response after the request has been completed.

As of now (Go 1.13.6), there is no way to actually send a 102 response because ResponseWriter.WriteHeader() can only be called once. Any successive calls are rejected ([here](https://github.com/golang/go/blob/8d7be1e3c9a98191f8c900087025c5e78b73d962/src/net/http/server.go#L1121-L1125)).

Since the ResponseWriter interface cannot be extended without breaking backwards compatibility, a new interface should be added (and implemented by the existing ResponseWriter implementations) that exposes a function for sending an interim response with status 102.

**Comment by toothrot** [comment]
WebDAV specific features might be better suited for `x/net/webdav`. I'm not positive we could make this change in `net/http` while maintaining API compatibility.

/cc @bradfitz @nigeltao

**Comment by bradfitz** [comment]
I don't think we'd need API changes. We could just permit WriteHeader(102) followed by a non-1xx status later

**Comment by Artheriom** [comment]
Hey,

Any update about this ? It would be a nice feature

**Comment by madCode** [comment]
Hey @dunglas! What's the status of the linked PR? I see it's been in progress since Feb of 2021.

**Comment by dunglas** [comment]
@madCode it is ready, waiting for a final review by the core team.
