### ISSUE TITLE
cmd/go: go list reports a confusing StaleReason

### ISSUE THREAD

**Issue by perillo** [golang/go#36737]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/manlio/.local/bin"
GOCACHE="/home/manlio/.cache/go-build"
GOENV="/home/manlio/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY="github.com/perillo"
GONOSUMDB="github.com/perillo"
GOOS="linux"
GOPATH="/home/manlio/.local/lib/go:/home/manlio/src/go"
GOPRIVATE="github.com/perillo"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/mod/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build719321233=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.13.6 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.13.6
uname -sr: Linux 5.4.13-arch1-1
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.30.
gdb --version: GNU gdb (GDB) 8.3.1
</pre></details>

### What did you do?

From outside of a Go module (e.g. in the `\tmp` directory), and `GO111MODULE=on`
```
go clean -modcache -cache
go install golang.org/x/tools/go/packages
go list -f '{{ .StaleReason }}' golang.org/x/tools/go/packages
```

### What did you expect to see?

An empty StaleReason

### What did you see instead?

```
not installed but available in build cache
```

This seems confusing, since the documentation of `Stale` is `would 'go install' do anything for this package?`.  However `go install` will do nothing for this package, excluding making it available in the build cache and module cache.

Without first `go install`, I get

```
stale dependency: golang.org/x/tools/go/internal/gcimporter
```

**Comment by bcmills** [comment]
This is fixed in go1.14beta1 via #32027.

```
$ export GO111MODULE=on

$ go1.14beta1 install golang.org/x/tools/go/packages
can't load package: cannot find module providing package golang.org/x/tools/go/packages: working directory is not part of a module

$ go1.14beta1 list -f '{{ .StaleReason }}' golang.org/x/tools/go/packages
can't load package: cannot find module providing package golang.org/x/tools/go/packages: working directory is not part of a module
```
