### ISSUE TITLE
crypto/x509: MarshalPKCS8PrivateKey doc says RSA private key while it supports more than that

### ISSUE THREAD

**Issue by bigmikes** [golang/go#36735]
Doc of [`x509.MarshalPKCS8PrivateKey`](https://golang.org/pkg/crypto/x509/#MarshalPKCS8PrivateKey) says:

> MarshalPKCS8PrivateKey converts an **RSA** private key to PKCS#8, ASN.1 DER form.

But immediately after doc says that it also supports ECDSA and ED25519 key types:

> The following key types are currently supported: *rsa.PrivateKey, *ecdsa.PrivateKey and ed25519.PrivateKey. Unsupported key types result in an error.

I think that the "RSA" word in first line should be removed.

If this is confirmed, I can take care of this doc fix.

**Comment by katiehockman** [comment]
Yep that just looks like a typo to me. I'd be happy to patch that. @FiloSottile do you agree that this is a bug?

**Comment by FiloSottile** [comment]
Yep, it's a typo. Go ahead!

**Comment by katiehockman** [comment]
@gopherbot please backport to 1.13 and 1.14
