### ISSUE TITLE
cmd/link: implement external linking for riscv64

### ISSUE THREAD

**Issue by 4a6f656c** [golang/go#36739]
There is currently no support for external linking on riscv64 - this is a tracking bug for adding support.

**Comment by 4a6f656c** [comment]
I have external linking support implemented for linux/riscv64 - I'll attempt to get this cleaned up for the next development cycle:

```
$ ~/src/go/bin/go build -ldflags=-linkmode=external hello.go
$ ldd hello
        linux-vdso.so.1 (0x0000001555571000)
        libpthread.so.0 => /lib/riscv64-linux-gnu/libpthread.so.0 (0x000000155557a000)
        libc.so.6 => /lib/riscv64-linux-gnu/libc.so.6 (0x0000001555595000)
        /lib/ld-linux-riscv64-lp64d.so.1 (0x0000001555556000)
$ ./hello
Hello, World!
```

**Comment by xnox** [comment]
> I have external linking support implemented for linux/riscv64 - I'll attempt to get this cleaned up for the next development cycle:
> 
> ```
> $ ~/src/go/bin/go build -ldflags=-linkmode=external hello.go
> $ ldd hello
>         linux-vdso.so.1 (0x0000001555571000)
>         libpthread.so.0 => /lib/riscv64-linux-gnu/libpthread.so.0 (0x000000155557a000)
>         libc.so.6 => /lib/riscv64-linux-gnu/libc.so.6 (0x0000001555595000)
>         /lib/ld-linux-riscv64-lp64d.so.1 (0x0000001555556000)
> $ ./hello
> Hello, World!
> ```

Do you have code for this somehwere? even if not clean?

**Comment by 4a6f656c** [comment]
@xnox - there is a commit on top of Go 1.14.2 [here](https://github.com/4a6f656c/go/commit/ed4e48cd8190a39634590555eea669a4274a47ef). This will need reworking somewhat for upstreaming, given the linker changes during the current development cycle (what is due to become Go 1.15).
