### ISSUE TITLE
x/tools/gopls: handle replace directives

### ISSUE THREAD

**Issue by stamblerre** [golang/go#36745]
We watch all of the files in the module root for changes on-disk, and we also use changes to the current module as a heuristic for when it's necessary to rescan for imports. We should also track replace directives and watch file changes in replace targets.

**Comment by stamblerre** [comment]
Fixed as of #239198, though VS Code does not support watching directories outside of the workspace root.

**Comment by kevlar700** [comment]
> Fixed as of [CL 239198](https://go-review.googlesource.com/c/tools/+/239198), though VS Code does not support watching directories outside of the workspace root.

Is this fixable, otherwise it seems to me that this means extending modules via the filesystem and package main is a better solution than replace and named modules? Not reliable on Windows unfortunately but workable on Unix systems.

**Comment by stamblerre** [comment]
The title of this issue is a bit misleading--specifically, the issue is that on-disk changes to replaced modules will not be reflected to the editor because of limitations to VS Code's file watching API. `gopls` should still generally work with replaced modules. @kevlar700: If you are having an issue with the VS Code Go extension, please take a look at the [Troubleshooting guide](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md) and [file a new issue](https://github.com/golang/vscode-go/issues/new/choose).

**Comment by kevlar700** [comment]
> If you are having an issue with the VS Code Go extension, please take a look at the [Troubleshooting guide](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md) and [file a new issue](https://github.com/golang/vscode-go/issues/new/choose).

I think one issue might be that more people are using replace than perhaps should be?

"https://www.mail-archive.com/golang-nuts@googlegroups.com/msg41347.html"

Not sure whether to file an issue about documentation somewhere?

**Comment by stamblerre** [comment]
Replace directives should work with `gopls`, and it's perfectly fine to use them if they fit your use case. In fact, `gopls` uses a nested module with a replace directive itself. As I mentioned above, if your set-up is causing issues with VS Code Go and `gopls`, we'll be happy to take a look and investigate the problem.
