### ISSUE TITLE
doc/go1.14: GOINSECURE needs a release note

### ISSUE THREAD

**Issue by bcmills** [golang/go#36746]
I was reading through https://nullprogram.com/blog/2020/01/21 (via Golang Weekly) and realized that we forgot to add a release note for #32966.

`GOINSECURE` is a nice feature for local development, so we should make sure it is mentioned in the release notes.

CC @jayconrod @matloob

**Comment by bcmills** [comment]
CC @skeeto

**Comment by skeeto** [comment]
Wonderful! Thanks for the heads up, Bryan! I had no idea. I've updated 
my article with a note about GOINSECURE.
