### ISSUE TITLE
go.dev: fixed-width font is half the size of surrounding body text in pkg.go.dev pages

### ISSUE THREAD

**Issue by myitcv** [golang/go#36748]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/govim/govim@v0.0.26/cmd/govim?tab=overview
 
### What is your user agent?

``` 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.66 Safari/537.36
``` 
  
### Screenshot
 
![Screen Shot 2020-01-24 at 19 35 14](https://user-images.githubusercontent.com/3374574/73098153-b1837400-3ee0-11ea-93b2-69aadc1cf4d5.png)
 

 
### What did you do?
 
 Loaded the page
 
 
### What did you expect to see?
 
Consistent font sizes in the README section.

 
### What did you see instead?

Fixed-width fonts about half the size of the surrounding body text.

**Comment by cespare** [comment]
Notes:

* The page loads three web fonts: Work Sans, Roboto, and Source Code Pro
* The code elements on the screenshotted page are in `monospace` (leaving it up to the platform) but the surrounding text is Roboto
* Fixed-width text elsewhere (such as the Doc tab) uses the font stack `"Go Mono", "Source Code Pro", monospace;` (I don't know where Go Mono is supposed to come from)

Anyway, I think a simple fix is to make all the `code` elements and any other fixed-width text uniformly use the same fixed-width font stack.

Here's how it looks today on my machine (Ubuntu/Chrome):

![screen_20200124114424](https://user-images.githubusercontent.com/318501/73104174-a281cf00-3eaa-11ea-87ed-05acc8ce1e1a.png)

Here's how it looks if I add the style

```
code {
    font-family: "Go Mono", "Source Code Pro", monospace;
}
```

![screen_20200124130424](https://user-images.githubusercontent.com/318501/73104227-cfce7d00-3eaa-11ea-8a3b-dcd486f0163c.png)

**Comment by julieqiu** [comment]
Thanks for the suggestion, @cespare! I'll work on adding this fix.

**Comment by julieqiu** [comment]
Fixed.
