### ISSUE TITLE
codereview: hg clpatch is too strict

### ISSUE THREAD

**Issue by bradfitz** [golang/go#3674]
<pre>It'd be nice of hg clpatch's hgpatch could deal with a little fuzz (perhaps falling back
to using system patch, if available).

Example log:

$ hg clpatch 6255053
abort: codereview <a href="https://golang.org/issue/6255053">issue #6255053</a> is out of date: patch and recent changes conflict
(050271fb599f-&gt;40dc2beda77f)

$ hg clpatch --ignore_hgpatch_failure 6255053
edit src/pkg/net/http/request.go: patch did not apply cleanly
6255053:
	net/http: avoid a bunch of unnecessary CanonicalHeaderKey calls
	
	CanonicalHeaderKey didn't allocate, but it did use unnecessary
	CPU in the hot path, deciding it didn't need to allocate.
	
	I considered using constants for all these common header keys
	but I didn't think it would be prettier. &quot;Content-Length&quot; looks
	better than contentLength or hdrContentLength, etc.

	Reviewer: golang-dev@googlegroups.com, dave@cheney.net
		dave: LGTM. Nice 
	CC: 
	Files:

$ curl <a href="http://codereview.appspot.com/download/issue6255053_2005.diff">http://codereview.appspot.com/download/issue6255053_2005.diff</a> | patch -p2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5949    0  5949    0     0   6640      0 --:--:-- --:--:-- --:--:--  7040
patching file pkg/net/http/header.go
patching file pkg/net/http/request.go
Hunk #2 succeeded at 732 with fuzz 2.
patching file pkg/net/http/server.go
patching file pkg/net/http/transfer.go</pre>

**Comment by rsc** [comment]
Obsolete
