### ISSUE TITLE
gopls: go get (…)/gopls@master fails

### ISSUE THREAD

**Issue by ainar-g** [golang/go#36751]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, as of e948d2b73e.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ainar/.cache/go-build"
GOENV="/home/ainar/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ainar/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/ainar/go/go1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/ainar/go/go1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build387560314=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

``` sh
$ env GO111MODULE=on go get golang.org/x/tools/gopls@master
go: finding golang.org master
go: finding golang.org/x/tools/gopls master
go: finding golang.org/x master
go: finding golang.org/x/tools master
# golang.org/x/tools/gopls/internal/hooks
../../go/pkg/mod/golang.org/x/tools/gopls@v0.1.8-0.20200124170513-3f4d10fc73b4/internal/hooks/analysis.go:17:21: non-integer slice index a.Name
../../go/pkg/mod/golang.org/x/tools/gopls@v0.1.8-0.20200124170513-3f4d10fc73b4/internal/hooks/analysis.go:24:21: non-integer slice index a.Name
../../go/pkg/mod/golang.org/x/tools/gopls@v0.1.8-0.20200124170513-3f4d10fc73b4/internal/hooks/analysis.go:27:21: non-integer slice index a.Name
../../go/pkg/mod/golang.org/x/tools/gopls@v0.1.8-0.20200124170513-3f4d10fc73b4/internal/hooks/hooks.go:19:9: options.URLRegexp undefined (type *source.Options has no field or method URLRegexp)
```

### What did you expect to see?

No errors.

### What did you see instead?

* `non-integer slice index a.Name`
* `options.URLRegexp undefined (type *source.Options has no field or method URLRegexp)`

**Comment by bcmills** [comment]
See previously #34076.

**Comment by ainar-g** [comment]
<p>
So, if I read that other thread correctly, does that mean that one
should never use <code>go get</code> to get the “fresh” gopls from
<code>master</code>?  What are the official instructions if one wants to
use the development version to e.g. test new features or report bugs
quicker?  I can't seem to find anything about that in the
<a href="https://github.com/golang/tools/tree/20e5918576e8ce1b25875e18e037a6a89a60544b/gopls/doc">docs</a>.
</p>

**Comment by stamblerre** [comment]
You can install it by running `GO111MODULE=on go get golang.org/x/tools/gopls@master golang.org/x/tools@master`. But no, it isn't recommended unless you are tolerant to things breaking every now and then. We publish pre-releases before we are ready to make releases, so those would be another way to get a more polished version of the latest features.

**Comment by ainar-g** [comment]
<p>
That command worked, thanks!  I still think that this “no
<code>@master</code>” policy should be documented though.  I assume
won't be the only one who uses <code>@master</code>.
</p>

**Comment by stamblerre** [comment]
It's documented [here](https://github.com/golang/tools/blob/master/gopls/doc/user.md#installation), but if you think it could be more explicit, we'd be open to contributions that update the wording.
