### ISSUE TITLE
x/tools/gopls: incorrect active parameter for signature help

### ISSUE THREAD

**Issue by stamblerre** [golang/go#36766]
Borrowing the repro from saibing/bingo#20:

```go
package main

func foo(a, b int) int {
	return 42
}

func main() {
	foo(<>
}
```

Looks like we return `b` as the active parameter instead of `a` when signature help is triggered at the marked position.

**Comment by oblitum** [comment]
Notice that the issue does not happen when the parentheses pair is expanded. To trigger the problem it's needed to type opening parentheses. It happen when it's left open and there isn't a closing one.
