### ISSUE TITLE
x/tools/go/packages: GoFiles should be sorted

### ISSUE THREAD

**Issue by perillo** [golang/go#36763]
The `GoFiles` field in `packages` is the concatenation of `GoFiles` and `CgoFiles` from `go list`.
`go list` returns the two fields sorted (although it seems to not be documented), but `packages` does not sort its own `GoFiles`.

**Comment by mvdan** [comment]
Could you clarify why you think this is important? Is it for consistency with `go list`, or to have deterministic behavior?

**Comment by perillo** [comment]
The order returned by `packages` **is** deterministic.  It is just not the order one may expect.

**Comment by matloob** [comment]
I'd prefer not to specify the ordering of GoFiles. We want it to be deterministic but I think that otherwise, the more flexibility the api has, the better.

**Comment by perillo** [comment]
It seems reasonable, and `go help list` does not document that the files are sorted.

Thanks.

**Comment by matloob** [comment]
Okay, I'll close. Thanks!
