### ISSUE TITLE
cmd/go: go list starts the Package.Error.Err field with a newline

### ISSUE THREAD

**Issue by perillo** [golang/go#36762]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.  I can reproduce it with go1.14beta1

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/manlio/.local/bin"
GOCACHE="/home/manlio/.cache/go-build"
GOENV="/home/manlio/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY="github.com/perillo"
GONOSUMDB="github.com/perillo"
GOOS="linux"
GOPATH="/home/manlio/.local/lib/go:/home/manlio/src/go"
GOPRIVATE="github.com/perillo"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/code/git/github.com/golang/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build700153789=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.13.6 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.13.6
uname -sr: Linux 5.4.13-arch1-1
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.30.
gdb --version: GNU gdb (GDB) 8.3.1
</pre></details>

### What did you do?

```
go1.14beta1 list -e -json /tmp/empty.go
```
Where empty.go is an empty file.

### What did you expect to see?

```
{
	"Dir": "/tmp",
	"ImportPath": "command-line-arguments",
	"Match": [
		"/tmp/empty.go"
	],
	"Incomplete": true,
	"Error": {
		"ImportStack": [
			"main"
		],
		"Pos": "",
		"Err": "/tmp/empty.go:1:1: expected 'package', found 'EOF'"
	}
}
```

### What did you see instead?

```
{
	"Dir": "/tmp",
	"ImportPath": "command-line-arguments",
	"Match": [
		"/tmp/empty.go"
	],
	"Incomplete": true,
	"Error": {
		"ImportStack": [
			"main"
		],
		"Pos": "",
		"Err": "\n/tmp/empty.go:1:1: expected 'package', found 'EOF'"
	}
}
```

There is a '\n' at the begin of the Err string.

**Comment by mvdan** [comment]
This appears to be on purpose: https://github.com/golang/go/blob/69660ed7e05b8fccf071210cb0963aba8edc5ec3/src/cmd/go/internal/base/base.go#L182-L193

I'm not sure if I agree with the logic applying to `go list -e -json`, though. The error is just a string field, so it doesn't make sense for it to start with a newline - especially when there's only one error.

/cc @bcmills @jayconrod @matloob

**Comment by matloob** [comment]
Just for my curiousity, is this breaking something or is it purely an aesthetic concern?

**Comment by perillo** [comment]
It is just a non expected behavior.

If i'm implementing a wrapper around `go list -e -find -json`, probably I would not think of trimming the error string.

**Comment by jayconrod** [comment]
Related to #36087. Another problem for tools wrapping `go list -e -json` is that the error position is not reported correctly.

[CL 210938](https://go-review.googlesource.com/c/go/+/210938) (work in progress) would fix this for the common case where there's only one scan error.
