### ISSUE TITLE
strconv: add ParseComplex

### ISSUE THREAD

**Issue by pjebs** [golang/go#36771]
strconv.ParseComplex(s string, bitSize int) (complex128, error)

**Comment by pjebs** [comment]
I don't think it should import `regexp` or `strings` to keep the package small. It is heavily recommended by gopherjs for exactly this reason.

**Comment by josharian** [comment]
Exactly what format(s) do you think it should accept?

**Comment by ianlancetaylor** [comment]
Note that the language doesn't define any format for a complex expression.  Instead it defines an imaginary literal (an integer or floating point constant followed by `i`).  Any complex constant is simply a constant expression that includes at least one imaginary literal.  So I think @josharian is asking a good question here.  We don't want the strconv package to have to parse an arbitrary expression.

That said, we do have an implicit definition for parsing a complex constant in `fmt.Scan`, implemented in the method `fmt.(*ss).complexTokens` (https://golang.org/src/fmt/scan.go#L740).  This syntax doesn't seem to have any user-visible documentation.  We could decide to move that method over to `strconv.ParseComplex`.

**Comment by pjebs** [comment]
Let me know with what I've done so far after addressing your concerns.

https://github.com/golang/go/pull/36815

**Comment by pjebs** [comment]
It will accept:
```
- (±34.3±234.2i)
- ±34.3±234.2i
- exponential form
- hexadecimal form
- NaN
- ±Inf±Infi
- only real
- only imag
```

**Comment by pjebs** [comment]
Any news on this?

**Comment by rsc** [comment]
`fmt.Print` and `fmt.Scan` do have an implicit format for complex numbers:
FLOAT+/-FLOATi or (FLOAT+/-FLOATi)
They format and accept both decimal and hex floats, and NaN and Inf for either or both FLOATs.

For floats we have:

func ParseFloat(s string, bitSize int) (float64, error)
func FormatFloat(f float64, fmt byte, prec, bitSize int) string

It seems like we'd need

func ParseComplex(s string, bitSize int) (complex128, error)
func FormatComplex(c complex128, fmt byte, prec, bitSize int) string

This seems like it is a hole we forgot to fill. 

/cc @robpike @griesemer

**Comment by robpike** [comment]
Seems like a reasonable thing to add, in parallel with float64 support as @rsc says. It would be good to see if the fmt package adapts well to using it.

**Comment by pjebs** [comment]
What should `FormatComplex` return?
With brackets or without brackets?

**Comment by rsc** [comment]
FormatComplex should probably put in the parens, same as fmt.
The question of hex or decimal is controlled by the fmt byte,
like in Printf: 'x' gets hex.

For example, I believe these tests from fmt show what fmt='x' prec=3 should do:

```
fmt_test.go:532:	{"%.3x", 0i, "(0x0.000p+00+0x0.000p+00i)"},
fmt_test.go:538:	{"%.3x", 1 + 2i, "(0x1.000p+00+0x1.000p+01i)"},
fmt_test.go:542:	{"%.3x", -1 - 2i, "(-0x1.000p+00-0x1.000p+01i)"},
```

**Comment by pjebs** [comment]
cool. implemented FormatComplex. Will do unit tests later.

**Comment by rsc** [comment]
Based on the discussion, this seems like a **likely accept**.

**Comment by rsc** [comment]
No change in consensus, so accepted.

**Comment by pjebs** [comment]
So what happens now? Well it be in go 1.15?

**Comment by ianlancetaylor** [comment]
Accepting the proposal means that it is OK to make the change.  In this case you've already sent a CL, so now the appropriate maintainers need to review it.  It can be in 1.15 if it gets reviewed and accepted.

**Comment by odeke-em** [comment]
Here is an initial prototype using the logic already in strconv.ParseFloat https://play.golang.org/p/sK3o9iBNJ55. @pjebs I shall take a look at your CL.

**Comment by pjebs** [comment]
Is it possible to keep strings package out because it's heavily used in environments like gopher.js

**Comment by odeke-em** [comment]
For sure, @pjebs, thanks for letting me know :) Let's take it to your CL, where I've posted feedback.

**Comment by pjebs** [comment]
@odeke-em Thank you for the feedback. I'll make various adjustments. I was told we were only accepting `(N=Ni)` format as per https://github.com/golang/go/issues/36771#issuecomment-578534156

**Comment by odeke-em** [comment]
Gotcha! My interpretation of that comment was more of: the format isn’t
defined and yes we shouldn’t be accepting arbitrary expressions. However
 the Go parser and compilers accept either of these forms for complex
constants:
   REAL JOINING_SIGN IMAG
   IMAG JOINING_SIGN REAL
So I think that naturally Go users will have an expectation of being able
to use any of:
   -30-50i
   -50i-30
Or:
   -50i
Or:
   -30

As well as other forms of IEEE 754 floats for the constants. As Ian
mentioned a complex is just a constant affixed with an “i”.

Your CL currently accepts: -30-50i but not -50i-30. I think we can make it
accept the latter form, by meeting in the middle for a hybrid of
suggestions.

**Comment by pjebs** [comment]
I got confused because the @ianlancetaylor pointed me to the "implicit definition" that Go currently accepts and it states:

```
// complexTokens returns the real and imaginary parts of the complex number starting here.
// The number might be parenthesized and has the format (N+Ni) where N is a floating-point
// number and there are no spaces within.
```

**Comment by ianlancetaylor** [comment]
The format we accepted for this proposal is exactly the one in https://github.com/golang/go/issues/36771#issuecomment-603991941 , which is simpler and more constraining than what @odeke-em suggests above.

**Comment by odeke-em** [comment]
Thank you for the clarification on the interpretation and what was
accepted, Ian. Alright, in the future after we’ve merged the related CL. If
users request for it, would it be logical for us to accept Ni+N as well?

**Comment by pjebs** [comment]
In that case, @odeke-em can you remove the comments you made that are related to the expanded definition. I believe there were only cosmetic adjustments left.

**Comment by odeke-em** [comment]
Acknowledged, thank you @pjebs and @ianlancetaylor for the clarification. I shall update my comments on the CL.

**Comment by pjebs** [comment]
@odeke-em Finished amending PR based on your comments.

The only thing I didn't change was your suggestion that I change `IEEE754` to `IEEE 754` because the `ParseComplex` doc comments are directly from `ParseFloat` function and that's how it was in there.

Thanks for the review.
Also noticed to my surprise that you stared my https://github.com/rocketlaunchr/dbq package.

**Comment by odeke-em** [comment]
>@odeke-em Finished amending PR based on your comments.

Awesome, I shall take a look and I'll also kindly rope in @griesemer for the final look.

>Also noticed to my surprise that you star'd my https://github.com/rocketlaunchr/dbq package.

Aye aye. Nice work and ergonimcs, I hope to use it sometime in the future!

**Comment by pjebs** [comment]
The code already rejects malformed parenthesis

**Comment by pjebs** [comment]
@odeke-em 

Issues:

> PS8, Line 10
> This suggestion wasn't added.

Am I meant to change the commit message for my initial commit? Is that how I do it?

> We need to ensure that malformed parenthesis throw out an error e.g.:

The `ParseFloat` function already takes care of rejecting malformed parenthesis. There is no need to cater for it. See test cases.

> This code isn't intuitive to me on what it does.
Would be nice to explain the logic of how we figure out what's real what's imaginary.

I have added more detailed comments to explain the logic. I feel that the algorithmic approach is simpler once the logic is understood.

> Hexadecimal values e.g. ±0x10.3p±8±0x3p3i

**The ParseComplex function leverages on ParseFloat. I can't get even ParseFloat to accept hexadecimal values. See: https://play.golang.org/p/E1s39kCdmbV**

Can you please look at the playground and tell me what I'm doing wrong?

**Comment by odeke-em** [comment]
Thanks for the ping Pj!

Please use the CL or the respective PR to respond to code review comments
otherwise we now no longer have threaded conversations related to the code.
Please add those comments to the PR or better, even log in and comment
directly on the CL. I can’t correlate them via email and the actual CL :)

**Comment by pjebs** [comment]
@odeke-em I responded on the official site.

**Comment by pjebs** [comment]
@ianlancetaylor @griesemer Will this make it to Go1.15?

**Comment by griesemer** [comment]
I've started looking at the code.
