### ISSUE TITLE
cmd/go: document that `go mod init` can guess the module path when inside GOPATH

### ISSUE THREAD

**Issue by perillo** [golang/go#36775]
`go mod help init` says:

```
If possible, init will guess the module path from import comments
(see 'go help importpath') or from version control configuration.
```

However when calling `go mod init` (on an empty project) inside `$GOPATH`, the module path is correctly guessed.

On the other hand, when `go mod init` is called outside `$GOPATH`, it reports an error:

```
go: cannot determine module path for source directory /tmp/go/test (outside GOPATH, module path must be specified)
```

This is not documented.

**Comment by jayconrod** [comment]
[CL 214381](https://go-review.googlesource.com/c/go/+/214381) will address this.

**Comment by perillo** [comment]
CL 214381  should also update the original documentation of the `go mod` command.

**Comment by jayconrod** [comment]
@perillo The main issue for module documentation is #33637.

When the module reference documentation is complete, we'll re-evaluate the `go help` documentation. I would like the module reference documentation to be the canonical reference for most of these topics. `go help` would just show brief summaries of commands and flags. It's hard to read this kind of reference documentation in the terminal without links or formatting.

**Comment by dmoles** [comment]
On a related note, the help for `go mod help init` still says "If possible, init will guess the module path … from version control configuration" even though this functionality seems to have been removed in https://golang.org/cl/172019.
