### ISSUE TITLE
x/website: Potential reference to wrong variable name "TitleValidator"

### ISSUE THREAD

**Issue by atc0005** [golang/go#36779]
While reading this article:

https://golang.org/doc/articles/wiki/

I got to the point where the author is explaining how the `makeHandler` function uses the regex created earlier to validate the `title` provided by the user.

> The closure extracts the title from the request path, and validates it with the `TitleValidator` regexp.

The actual variable name is `validPath`. From the way the explanation is written, it seems that the text should instead be:

> The closure extracts the title from the request path, and validates it with the `validPath` regexp.

---

Many thanks for writing this article. I learned a lot and plan to reference it often as I continue to learn more about Go and writing web apps.

**Comment by agnivade** [comment]
Interested in sending a PR ?

**Comment by atc0005** [comment]
> @agnivade Interested in sending a PR ?

Looks like @howjmay beat me to it (thanks!). When I initially submitted this I was also unsure whether I was misreading the quoted line. Glad to see that I was correct and had the right understanding. :)

**Comment by HowJMay** [comment]
Don't worry I can close my PR now. I thought you may be not willing fix this by yourself. I am sorry 😵

**Comment by atc0005** [comment]
> @HowJMay Don't worry I can close my PR now. I thought you may be not willing fix this by yourself. I am sorry

No, no, it was an honest (non-sarcastic) Thank You for submitting your PR. Please, by all means please proceed with your PR. I was actually really impressed that someone was already actively working to resolve the issue.
