### ISSUE TITLE
x/website: Example for math/rand has index offset error

### ISSUE THREAD

**Issue by onggunhao** [golang/go#36777]
![image](https://user-images.githubusercontent.com/518024/73135819-0a6d1c80-4047-11ea-8ac1-e596b0ab5862.png)

**Comment by ianlancetaylor** [comment]
Why?  `rand.Intn(n)` is documented as returning a value that is `>= 0` and `< n`.

**Comment by onggunhao** [comment]
You're right, my mistake. Closing this issue.
