### ISSUE TITLE
cmd/compile: output cost while inlining function with `Debug['m'] > 1`

### ISSUE THREAD

**Issue by TennyZhuang** [golang/go#36780]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/data/1/zty/.cache/go-build"
GOENV="/data/1/zty/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/data/1/zty/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/data/1/zty/rclone/contrib/tidb/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build691466518=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

`go build -gcflags=-m=2 .`

If a function can not be inline, the error message will output the cost:

```
"%v: cannot inline %v: function too complex: cost %d exceeds budget %d\n"
```

But if a function is inlinable, only

```
%v: can inline %#v as: %#v { %#v }\n"
```

is output without cost. The behavior is not very consistent, and the cost info is also useful to user who try to optimize his code.

### What did you expect to see?

```
%v: can inline %#v with cost %d as: %#v { %#v }\n"
```

### What did you see instead?

```
%v: can inline %#v as: %#v { %#v }\n"
```

**Comment by TennyZhuang** [comment]
If the debug info improvement make sense, I'd like to submit a PR.

**Comment by josharian** [comment]
Sounds fine to me. Feel free to send a change. Note that we are in the code freeze now, so it won’t be reviewed and/or submitted until Go 1.14 is released.
