### ISSUE TITLE
crypto/x509: incorrect mention of "EC Public Key" for ParseECPrivateKey docs, should be "EC Private Key"

### ISSUE THREAD

**Issue by matthew119427** [golang/go#36788]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.13.5

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Manjaro Linux x64

### What did you expect to see?
Documentation should read `This kind of key is commonly encoded in PEM blocks of type "EC PRIVATE KEY".`

### What did you see instead?
The documentation for x509#ParseECPrivateKey states `This kind of key is commonly encoded in PEM blocks of type "EC PUBLIC KEY".`, however we're parsing a private key here, the block wouldn't be "EC PUBLIC KEY".
![image](https://user-images.githubusercontent.com/40540813/73152291-534fc000-409d-11ea-9a7b-190cf2af06e7.png)

**Comment by odeke-em** [comment]
Thank you for reporting this issue @matthew119427 and welcome to the Go project! Thank you @agnivade for the triage!

@matthew119427, this issue has been fixed for Go1.14 by @katiehockman's commit https://github.com/golang/go/commit/ee04dbf430de4343a3406253a132267bea38d3e6 aka CL https://go-review.googlesource.com/c/go/+/207918 and you can see the change on https://tip.golang.org/pkg/crypto/x509/#ParseECPrivateKey
<img width="661" alt="Screen Shot 2020-01-29 at 9 34 35 PM" src="https://user-images.githubusercontent.com/4898263/73385995-2c80cc00-42df-11ea-8760-a28fae552944.png">

Please keep noticing and reporting anything unusual. Thank you!
