### ISSUE TITLE
x/pkgsite: add a 'y' keyboard shortcut to canonicalise URL with version

### ISSUE THREAD

**Issue by myitcv** [golang/go#36807]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/govim/govim/cmd/govim/config?tab=doc

### What is your user agent?

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.66 Safari/537.36
</pre>

### Screenshot

<img width="818" alt="Screen Shot 2020-01-27 at 19 07 01" src="https://user-images.githubusercontent.com/3374574/73205104-3916f000-4138-11ea-8308-9a0cc191ef94.png">

### What did you do?

Navigated to said page.

### What did you expect to see?

On GitHub, the `y` keyboard shortcut allows the viewer to canonicalise the URL for the version of a file you are viewing:

<img width="872" alt="Screen Shot 2020-01-27 at 19 08 31" src="https://user-images.githubusercontent.com/3374574/73205194-71b6c980-4138-11ea-8883-c970447ac406.png">

For example, at the time of writing, hitting `y` whilst on:

https://github.com/govim/govim/blob/master/cmd/govim/config/config.go

updates the address bar URL to be:

https://github.com/govim/govim/blob/013f992e25f23cbc4a778d1eb472e719d276de32/cmd/govim/config/config.go

I think a similar option should be offered on pkg.go.dev. For example, at the time of writing, hitting `y` whilst on:

https://pkg.go.dev/github.com/govim/govim/cmd/govim/config?tab=doc

would update the address bar URL to be:

https://pkg.go.dev/github.com/govim/govim@v0.0.27/cmd/govim/config?tab=doc

### What did you see instead?

No option to do this.

**Comment by kush-patel-hs** [comment]
I'll like to take this on

**Comment by kush-patel-hs** [comment]
Ready for review https://go-review.googlesource.com/c/pkgsite/+/239179!. I used GIthub's behaviour of the URL update does not reload page (it simply replaces history).
