### ISSUE TITLE
x/build/dashboard: host-linux-ppc64le-power9-osu is not using GOPPC64=power9

### ISSUE THREAD

**Issue by ceseo** [golang/go#36802]
While inspecting the dashboard, I noticed that the POWER9 builders aren't actually generating POWER9 code. This was probably an oversight when we moved to Docker.

I'll submit a CL to fix this shortly.

**Comment by bradfitz** [comment]
I'll reopen this until somebody on the @golang/osp-team re-deploys the coordinator.

**Comment by dmitshur** [comment]
I was considering deploying now, but there is an active gomote session (/cc @cagedmantis). I'm not sure if there is work that would be lost if reset now, so I'll leave redeploying for another better time.

**Comment by dmitshur** [comment]
Now turned out to be a better time. The latest version of coordinator (golang/build@5bb938ef020fb4b7f22d366b1e0dc8f9b425cc2f) is deployed now.
