### ISSUE TITLE
go.dev: change "copy" link to be full import statement

### ISSUE THREAD

**Issue by myitcv** [golang/go#36809]
### What is the URL of the page with the issue?

https://pkg.go.dev/testing?tab=doc

### What is your user agent?

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.66 Safari/537.36
</pre>

### Screenshot

<img width="928" alt="Screen Shot 2020-01-27 at 19 19 44" src="https://user-images.githubusercontent.com/3374574/73206064-20a7d500-413a-11ea-8667-91c3641f80d0.png">

### What did you do?

Visited the above page.

### What did you expect to see?

Firstly, the presence of the "copy" link to the right of the package path is welcomed: thank you!

However, godoc has this nice feature whereby the first thing at the top of the page is a complete import statement:

<img width="750" alt="Screen Shot 2020-01-27 at 19 20 14" src="https://user-images.githubusercontent.com/3374574/73206128-459c4800-413a-11ea-9b95-af54ddec95e7.png">

I'd like to suggest that we change pkg.go.dev to behave in the same way, such that clicking on the "copy" link would result in the following contents on the clipboard:

```
import "testing"
```

### What did you see instead?

Only `testing` is copied to the clipboard.

**Comment by jba** [comment]
We did that because most of the time, the file in which you'd like to paste the result already has an import block, with parens.

But perhaps we're missing other use cases of this feature?

**Comment by myitcv** [comment]
> We did that because most of the time, the file in which you'd like to paste the result already has an import block, with parens.

If this is the case, then I think making the copied value `"testing"` would have been a better choice, no?

However I'm not clear that "most of the time" there will be an existing import declaration group (if that's the name given to a `go/ast.GenDecl` which has a valid `Lparen` and `Rparen`) - is there something that points to this likely being the case?

Regardless, if the copied value is `import "testing"` then it can trivially be added as a new import declaration and then tools like `gopls`/`goimports` can tidy things up.

**Comment by jba** [comment]
Let me ask you: why is `import "testing"` better than `"testing"` or `testing`?

**Comment by myitcv** [comment]
Because I can paste it directly into any `.go` file without needing to make any further changes to the import (group).

**Comment by jba** [comment]
Sounds reasonable. Will do.

**Comment by jba** [comment]
This has been fixed and will appear after the next deployment, sometime next week.

**Comment by jba** [comment]
Live now.

**Comment by myitcv** [comment]
Thank you!
