### ISSUE TITLE
x/pkgsite: keyboard shortcut '/' should focus the search box

### ISSUE THREAD

**Issue by myitcv** [golang/go#36805]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/govim/govim?tab=doc

### What is your user agent?

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.66 Safari/537.36
</pre>

### Screenshot

<img width="902" alt="Screen Shot 2020-01-27 at 18 55 20" src="https://user-images.githubusercontent.com/3374574/73204314-a7f34980-4136-11ea-8129-d8345d116f7f.png">

### What did you do?

Tried to focus the search input box using `/`

### What did you expect to see?

Focus shifting to the search box

### What did you see instead?

Nothing happened.

This was a useful feature of godoc, e.g. try that keyboard shortcut on https://godoc.org/github.com/govim/govim

<img width="703" alt="Screen Shot 2020-01-27 at 18 55 45" src="https://user-images.githubusercontent.com/3374574/73204403-c9eccc00-4136-11ea-878f-519de1822e58.png">

**Comment by kush-patel-hs** [comment]
Sounds like a useful feature :) I will add

**Comment by kush-patel-hs** [comment]
jump.js is becoming more like keyboard_shortcuts.js https://go-review.googlesource.com/c/pkgsite/+/240297, but this should do it! Open to suggestions. It is working locally for me.
