### ISSUE TITLE
go.dev: search for golang.org/x/tools/internal/ returns nothing

### ISSUE THREAD

**Issue by myitcv** [golang/go#36803]
### What is the URL of the page with the issue?

https://pkg.go.dev/search?q=golang.org%2Fx%2Ftools%2Finternal%2F

### What is your user agent?

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.66 Safari/537.36
</pre>

### Screenshot

<img width="767" alt="Screen Shot 2020-01-27 at 18 50 31" src="https://user-images.githubusercontent.com/3374574/73203919-ea685680-4135-11ea-9cde-8d5dde9c4c51.png">

### What did you do?

Searched for `golang.org/x/tools/internal/`

### What did you expect to see?

Results for `golang.org/x/tools/internal/...`

### What did you see instead?

Nothing

**Comment by julieqiu** [comment]
This seems to be a bug - I would expect `https://pkg.go.dev/search?q=golang.org/x/tools/internal` to redirect to `https://pkg.go.dev/golang.org/x/tools/internal`.

**Comment by julieqiu** [comment]
This should be fixed.
