### ISSUE TITLE
go.dev: include '¶' permalinks in all package doc subheadings

### ISSUE THREAD

**Issue by myitcv** [golang/go#36808]
### What is the URL of the page with the issue?

https://pkg.go.dev/testing?tab=doc

### What is your user agent?

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.66 Safari/537.36
</pre>

### Screenshot

<img width="967" alt="Screen Shot 2020-01-27 at 19 12 01" src="https://user-images.githubusercontent.com/3374574/73205552-1b965600-4139-11ea-88a2-9c5a37b8cd1f.png">

### What did you do?

Tried to link to the "Benchmarks" subsection of the `testing` package docs.

### What did you expect to see?

Each subheading to be a link such that hovering over it (the heading) a `¶` symbol should appear, like on godoc:

<img width="891" alt="Screen Shot 2020-01-27 at 19 12 17" src="https://user-images.githubusercontent.com/3374574/73205714-7def5680-4139-11ea-8664-2068967e8dac.png">

Clicking that link should then change to the address bar URL to include the fragment. For example on godoc, for the "Benchmarks" subsection we end up with the URL:

https://godoc.org/testing#hdr-Benchmarks

### What did you see instead?

No ability to link to subsections of package documentation.

**Comment by julieqiu** [comment]
Would you mind clarifying if you are able to link subsections today using the same URL scheme from godoc.org? For example:

https://pkg.go.dev/testing?tab=doc#hdr-Benchmarks 

takes me to:
![image](https://user-images.githubusercontent.com/5943521/73297368-7b443e00-41d9-11ea-9030-43ad519b23d9.png)

My understanding is that this issue is specifically asking to add a clickable `¶` symbol next to each subheading.

/cc @dmitshur

**Comment by myitcv** [comment]
@julieqiu 

> Would you mind clarifying if you are able to link subsections today using the same URL scheme from godoc.org?

As you demonstrated, that appears to work (not that I had tried)

> My understanding is that this issue is specifically asking to add a clickable ¶ symbol next to each subheading.

Exactly, as per the original description:

> _Each subheading to be a link such that hovering over it (the heading) a ¶ symbol should appear, like on godoc:_
>
> _Clicking that link should then change to the address bar URL to include the fragment. For example on godoc, for the "Benchmarks" subsection we end up with the URL:_

**Comment by dmitshur** [comment]
I've sent a CL that should fix this issue once it is deployed. We can keep this issue open to confirm everything is working as expected.

**Comment by tooolbox** [comment]
This is super important, thank you @dmitshur !

**Comment by dmitshur** [comment]
This fix has been deployed and it's working as expected. For example, see:

- https://pkg.go.dev/testing#hdr-Benchmarks
- https://pkg.go.dev/cmd/go#hdr-Generate_Go_files_by_processing_source
- https://pkg.go.dev/robpike.io/ivy#hdr-User_defined_operators

![image](https://user-images.githubusercontent.com/1924134/77773011-650efe80-701f-11ea-8aff-475790da21c0.png)

Note that it may not appear on some existing package versions until they've been reprocessed, but they should work on all new versions. Please let us know if you spot any other issues.
