### ISSUE TITLE
io: use syscalls like copy_file_range in Copy when possible

### ISSUE THREAD

**Issue by mvdan** [golang/go#36817]
@stapelberg just [made me aware](https://twitter.com/zekjur/status/1221901014225297408) of the [copy_file_range](https://manpages.debian.org/unstable/manpages-dev/copy_file_range.2.en.html) syscall. Quoting the summary:

> The copy_file_range() system call performs an in-kernel copy between two file descriptors without the additional cost of transferring data from the kernel to user space and then back into the kernel. It copies up to len bytes of data from the source file descriptor fd_in to the target file descriptor fd_out, overwriting any data that exists within the requested range of the target file.

It's also already supported by the sys repo: https://godoc.org/golang.org/x/sys/unix#CopyFileRange

When calling `Copy`, given that the conditions below are met:

* `runtime.GOOS == "linux"`
* Linux is version 4.5 or newer (when it was added)
* The source and destination are `*os.File`

Then, the syscall would be used to make a faster copy. I presume that we could do something similar on other platforms in the future, if they have similar syscalls.

I think `CopyN` and `CopyBuffer` could also be included here, but they are left out initially for the sake of simplicity. For example, `CopyBuffer` could simply ignore the buffer argument when taking the syscall shortcut, as no user space memory is required.

There is only one tricky detail here, to my mind:

> If src implements the WriterTo interface, the copy is implemented by calling src.WriteTo(dst). Otherwise, if dst implements the ReaderFrom interface, the copy is implemented by calling dst.ReadFrom(src). 

To not break semantics and backwards compatibility, if either of those methods exists, the syscall shortcut can't be taken. One would rely on the method having a similar syscall shortcut, if needed. Luckily, it seems like `os.File` implements neither method, so we're in the clear.

**Comment by networkimprov** [comment]
Isn't splice(2) and/or sendfile(2) already called by io.Copy?
http://man7.org/linux/man-pages/man2/splice.2.html
http://man7.org/linux/man-pages/man2/sendfile.2.html

copy_file_range(2) is recommended on a kernel >= 5.3
http://man7.org/linux/man-pages/man2/copy_file_range.2.html

**Comment by ianlancetaylor** [comment]
`splice` and `sendfile` are called by `io.Copy` via the `(*TCPConn).ReadFrom` method.  I think we could add a `(*os.File).ReadFrom` method that calls `copy_file_range`.

**Comment by beoran** [comment]
While this can be a good performance improvement, only on kernels > 5.3 cross-file-system copies are supported.  A fallback must be implemented in case copy_file_range returns -EXDEV.

**Comment by mvdan** [comment]
@ianlancetaylor thanks for the insight. I semeed to rememer splice being used for TCP. Feel free to retitle the issue to be about os.File.ReadFrom.

@beoran the original proposal did mention this, but in the context of `io.Copy`. I'm not sure if there is an agreed upon way to handle fallbacks in `io.ReaderFrom`. I guess calling `io.Copy` is one option.

**Comment by ianlancetaylor** [comment]
The same fallback issues arise for `splice`.  In that case if the `ReadFrom` method is unable to use `splice`, or `sendfile`, we call `genericReadFrom` in the net package, which is simply

```Go
func genericReadFrom(w io.Writer, r io.Reader) (n int64, err error) {
	// Use wrapper to hide existing r.ReadFrom from io.Copy.
	return io.Copy(writerOnly{w}, r)
}
```

**Comment by mvdan** [comment]
It seems like we generally agree that this is doable, so I'm going to replace NeedsDecision with NeedsFix. If anyone wants to work on this, feel free to send a CL.

**Comment by acln0** [comment]
I am going to work on this and send a CL soon.

**Comment by ianlancetaylor** [comment]
There is a discussion at https://lore.kernel.org/linux-fsdevel/20210126233840.GG4626@dread.disaster.area/T/#m05753578c7f7882f6e9ffe01f981bc223edef2b0 that suggests that perhaps the Go standard library should not use `copy_file_range` after all.

CC @acln0

**Comment by acln0** [comment]
Spooky. It seems like we should remove all of the `copy_file_range` code indeed. I can send a CL soon-ish if you'd like me to, but I don't know if the tree is open yet.

Now that we have `(*os.File).ReadFrom` and we can't remove it anymore, maybe we can look into hooking up the existing splice code, as the e-mails suggest. But I think we should start with just removing all the `copy_file_range` code and leaving a generic `io.Copy` forwarder behind in `(*os.File).ReadFrom`.

**Comment by beoran** [comment]
Yes, from that discussion on the Linux kernel mailing list, it seem to me that copy_file_range seems to be a Linux system call that is hard to use correctly in the general case, since it's not easy to fall back to other system calls in case it fails. Getting rid of it might cost us some performance but does have the benefit of simplifying code and lowering the requirements for the Linux kernel version.

**Comment by mvdan** [comment]
@beoran reopened.

If a future Linux release makes copy_file_range easier to use correctly, we could always try using it again.

**Comment by ianlancetaylor** [comment]
I've opened an issue for the recently discovered problem at #44272.  Let's use that for this specific problem rather than this general issue.
