### ISSUE TITLE
x/pkgsite: searching for modules isn't supported

### ISSUE THREAD

**Issue by mvdan** [golang/go#36814]
The current search functionality works on packages alone. That's fine, and useful - but quite limited in the module world.

For example, when I visit https://pkg.go.dev/search?q=sh, I'd expect to see https://pkg.go.dev/mod/mvdan.cc/sh/v3. Particularly since the query string is an exact match with the basename of the module path.

However, because it happens to not be a Go package, it doesn't show up at all as neither a module nor a package. A few sub-packages show up later, but they are scattered, and aren't nearly as useful.

I see two ways this could be addressed:

1) Make the search work for both packages and modues, allowing to trim it down with selectors like `is:module`. Think like GitHub search, where you can search for both issues and PRs at once, but then trim it down via `is:issue`.
2) Keep the search as it is now, but also add a "module search" page.

I think 1 is far better, since most people will just use the default search page, leaving out many of their potentially useful results hidden away.

**Comment by dmitshur** [comment]
To consider one more related data point, `go4.org` is an example of a module that does not have a Go package at the root. Searching for "go4.org" finds many packages in that module:

https://pkg.go.dev/search?q=go4.org

Perhaps a part of the problem affecting the case described in the original issue is that "sh" is a short word, and so it's hard to use it to find specific results reliability.

**Comment by mvdan** [comment]
I don't think the short word is related here - like you said, it's just an example. It's also an exact match for the basename of a module path, so the search shouldn't be particularly tricky at all.

**Comment by julieqiu** [comment]
This will be addressed #47321, so closing this issue.
