### ISSUE TITLE
x/pkgsite: add site version details to the bottom of pkg.go.dev pages

### ISSUE THREAD

**Issue by myitcv** [golang/go#36810]
### What is the URL of the page with the issue?

https://pkg.go.dev/testing?tab=doc

### What is your user agent?

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.66 Safari/537.36
</pre>

### Screenshot

<img width="865" alt="Screen Shot 2020-01-27 at 19 23 56" src="https://user-images.githubusercontent.com/3374574/73206313-9744d280-413a-11ea-8e21-0f2fa38199a0.png">

### What did you do?

Visited the aforementioned link.

### What did you expect to see?

A site version identifier at the bottom of the page.

### What did you see instead?

Nothing. 

Adding a site version identifier will, I think, help with the reporting of issues and communication of when fixes/features land.

**Comment by mvdan** [comment]
We should also include the details to report feedback. Sending a private email is no longer the best method; using this issue tracker is.

**Comment by julieqiu** [comment]
Thanks for the suggestion @myitcv! At the moment, you can get site version information if you look at the page source and look at the `version` query param on any static asset, for example:   

![image](https://user-images.githubusercontent.com/5943521/73295025-e3445580-41d4-11ea-8a28-99acea170876.png)

@mvdan - would you mind filing a separate issue for the feedback suggestion?

**Comment by julieqiu** [comment]
Closing this issue since you can view version details on the source page, and we now use the Go issue tracker for discussing feedback.
