### ISSUE TITLE
x/pkgsite: support viewing a package @master

### ISSUE THREAD

**Issue by myitcv** [golang/go#36811]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/moby/moby/client?tab=doc

### What is your user agent?

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.66 Safari/537.36
</pre>

### Screenshot

<img width="830" alt="Screen Shot 2020-01-27 at 19 52 45" src="https://user-images.githubusercontent.com/3374574/73208596-a463c080-413e-11ea-901f-3cba3c7a87c1.png">

### What did you do?

Visited the aforementioned link.

### What did you expect to see?

The current docs for `github.com/moby/moby/client`, like on godoc:

https://godoc.org/github.com/docker/docker/client

(notice https://github.com/docker/docker redirects to https://github.com/moby/moby)

### What did you see instead?

Per the screenshot, at the time of writing, docs for v1.13.1, which was tagged on Feb 8, 2017.

The godoc version is looking at `~master` at any given moment in time.

The current advice from the project maintainers is to use `master` of this package/module:

* https://github.com/moby/moby/issues/40185#issuecomment-568483750
* https://github.com/moby/moby/issues/40235

Hence only godoc.org works as a means of viewing "current" docs for `github.com/moby/moby/client`.

**Comment by julieqiu** [comment]
We're actively working on designing a better flow, but the workaround for this right now is to do the following:

1. Get the semantic version from proxy.golang.org using the .info endpoint. For example:
https://proxy.golang.org/github.com/moby/moby/@v/master.info currently shows:
```
{
    "Version": "v1.4.2-0.20200128034134-2ebaeef943cc",
    "Time": "2020-01-28T03:41:34Z"
}
```
Note. This will also automatically fetch the module for the proxy and populate it on pkg.go.dev, if it does not already exist (per instructions at https://go.dev/about#adding-a-package). It may take a minute or two for the package to appear on pkg.go.dev, if it is not already there.

3. Visit `pkg.go.dev/<import-path>@<semantic-version>` for the package documentation, in this case:
https://pkg.go.dev/github.com/moby/moby/client@v1.4.2-0.20200128034134-2ebaeef943cc.


We know that this isn't the best user experience, and are working on a better workflow.

**Comment by mewmew** [comment]
> We know that this isn't the best user experience, and are working on a better workflow.

How about a "Fetch latest version from master" link added to the bottom of pages on `pkg.go.dev` in similar fashion to the "Refresh now" link of `godoc.org`?

![screenshot_2020-02-24_23:32:24](https://user-images.githubusercontent.com/1414531/75197239-12130480-575e-11ea-9db4-c018c85483b4.png)

**Comment by hugelgupf** [comment]
Hey Julie, do you have any updates on the progress? This is a major blocker for us (u-root) to go.dev :( Thanks!

**Comment by julieqiu** [comment]
@hugelgupf thanks for letting us know! We deprioritized this feature temporarily to work on open sourcing (#36747) and with our product/UX teams to address [UX issues](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen++label%3AUX+label%3Ago.dev+). I don't have an exact timeline on when this feature will be ready, but we are aiming for within the next month or so.

Out of curiosity, does the workaround in https://github.com/golang/go/issues/36811#issuecomment-579404726 work for your use case (aside from the suboptimal user experience)?

**Comment by julieqiu** [comment]
You can now view a package at master using the URL, `https://pkg.go.dev/<path>@master`. For example, https://pkg.go.dev/github.com/moby/moby/client@master.

**Comment by SamWhited** [comment]
Are there limits to this? With the exception of the example you posted, none of the common packages I use appear to work. They all use vanity URLs, so maybe this has something to do with it?

**Comment by julieqiu** [comment]
@SamWhited - mind sharing what they are? I can look into it.

**Comment by SamWhited** [comment]
@julieqiu here are two of mine that appear to be exhibiting this behavior: https://pkg.go.dev/code.soquee.net/otp@master or https://pkg.go.dev/mellium.im/xmpp@master

**Comment by SamWhited** [comment]
Oh, apparently I have to "request" them or it 404s? I hadn't visited the actual page to click the link. I don't know what that means, but it's confusing

**Comment by julieqiu** [comment]
That's because that `code.soquee.net/otp@master` and `mellium.im/xmpp@master` weren't in our database yet. In the future, visiting these pages will automatically refresh master. 

Feel free to [file a new issue](https://golang.org/s/discovery-feedback) with any UI suggestions.

**Comment by hugelgupf** [comment]
Hi @julieqiu,

a lot of repositories are now moving to renaming their default branches to `main`. It seems that [master is hard-coded](https://github.com/golang/pkgsite/blob/97f6af5c05b8660bfd394820ce97fcc929215ae3/internal/discovery.go#L24) in pkgsite. Would it be possible to support some kind of magic version string that gets the default branch, whatever it may be named? This may end up being the reason that I move some of my repos back to `master`, which I'd like to avoid.

Let me know if I should open another issue for this.

Thanks!

**Comment by myitcv** [comment]
@hugelgupf - this issue is closed. Please open a new issue.

FWIW the means by which `git` can determine the default remote (`origin` in this case) branch looks like this:

```
git remote set-head origin -a
```

which then updates the following:

```
$ cat .git/refs/remotes/origin/HEAD
ref: refs/remotes/origin/main
```

**Comment by anacrolix** [comment]
In my experience, this only seems fixed for vanity URLs. More general module names don't work, like https://pkg.go.dev/github.com/anacrolix/torrent@master.
