### ISSUE TITLE
encoding/xml: unclear tag conflicts when dealing with namespaces

### ISSUE THREAD

**Issue by directionless** [golang/go#36813]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64

</pre>

### What did you do?

I'm trying to serialize some structs to xml.  I'm looking for output like
```xml
<Parent>
   <Child ABool="true"></Child>
   <Child xmlns="http://schemas.example.com/childb" ABool="true"></Child>
   <ABool>true</ABool>
</Parent>
```

But the obvious way to do that results in `main.Parent field "ChildA" with tag "" conflicts with field "ChildB" with tag ""`

If I set a namespace on ChildA, it works. But I don't think I should need to.

Example in https://play.golang.org/p/vUU6C5PiWk_C

**Comment by cagedmantis** [comment]
For asking questions about learning the language, see one of our forums: https://golang.org/wiki/Questions. We only use this issue tracker for tracking bugs. People in the forums can explain what is happening here.
