### ISSUE TITLE
ERROR WHILE CHECKOUT IT SAYS ERROR TOKENIZING. #BRAINTREE #PAYPAL #COMMAND LINE TOOL HUB

### ISSUE THREAD

**Issue by abhizeet007** [golang/go#36829]
![D](https://user-images.githubusercontent.com/50789510/73276171-456d7c80-420e-11ea-9ba4-30e5acfbe8b9.jpeg)

**Comment by ianlancetaylor** [comment]
I don't see anything related to Go here.  Please comment if you disagree and explain why you think this is an issue for the Go language.
