### ISSUE TITLE
Go newbie and LockOSThread

### ISSUE THREAD

**Issue by davetbo** [golang/go#36823]
Hello all,

I'm a Go noob (but I've been programming in php, javascript, and python for years).  I'm working on a program with a systray icon (getlantern/systray) and one of the menu items will open a settings dialog (for which I'm using go-sciter). 

I'm running into the LockOSThread crash.  I found this wiki article that seems useful:
https://github.com/golang/go/wiki/LockOSThread#solutions

However I have what's maybe a stupid question. At the bottom of that solution the author says:
```
And then other functions you write in package sdl can be like

func Beep() {
	do(func() {
		// whatever must run in main thread
	})
}
```
My problem is that I can't figure out where to call that Beep() function from and have it actually get called.  Any suggestions as to where in that solution one would call the extra functions that need to get run in the main thread?  I've tried many possible locations in that sdl.go file and none of them seem to work. I'm debugging by trying to call a Beep() {do(func() {...})} that just prints something to let me know it got in there, but it never does.

I appreciate your time and advice.

Thanks,
Dave

PS--here's my environment info:

I am running go version go1.13.6 darwin/amd64.  Here's my go env: 
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/davetbo/Library/Caches/go-build"
GOENV="/Users/davetbo/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/davetbo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/w2/dy449vjn1qq1hrn5bjg8ctd80000gn/T/go-build356227026=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by ianlancetaylor** [comment]
We've found that programming questions are more effectively answered not on the issue tracker, but in a forum.  You will get better and faster answers.  Please see https://golang.org/wiki/Questions.  Thanks.

(I don't really understand your question myself and I'm not sure what the answer is.)
