### ISSUE TITLE
cmd/go: make go mod download -json return the exit status 0 in case of errors

### ISSUE THREAD

**Issue by perillo** [golang/go#36833]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.  But at least with `go1.14beta1` `go mod download -json` does not print debug message on stderr.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/manlio/.local/bin"
GOCACHE="/home/manlio/.cache/go-build"
GOENV="/home/manlio/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY="github.com/perillo"
GONOSUMDB="github.com/perillo"
GOOS="linux"
GOPATH="/home/manlio/.local/lib/go:/home/manlio/src/go"
GOPRIVATE="github.com/perillo"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build524871395=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.13.6 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.13.6
uname -sr: Linux 5.4.15-arch1-1
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.30.
gdb --version: GNU gdb (GDB) 8.3.1
</pre></details>

### What did you do?

```
go mod download -json github.com/perillo/null
echo $?
```

In case of errors, the process exit status will be `1`, making it more complex to handle the `go mod download` output.

```
{
	"Path": "github.com/perillo/null",
	"Error": "module github.com/perillo/null: not a known dependency"
}
1
```

`go mod download -json` should return an exit status `0` in case of errors, the same as `go list -m -e -json`.

**Comment by perillo** [comment]
There is a similar issue in #35380.

However it suggests to change the documentation.  I suggest to change the implementation to match `go list -m -e -json`.  In alternative `go mod download` should support the `-e` flag.

**Comment by perillo** [comment]
I would like to change the issue title.

I think that `go mod download`  *should* print on `stderr` the errors encountered, as with `go list -json` (without the `-e` flag).

The reason is that the user can **simply** print the error returned by `Command.Run` *and* the content of `stderr`, instead of processing all the modules and check the Error field.

**Comment by perillo** [comment]
`go mod download` has another issue.
The `Module.Error` field is defined as `string` instead of `*ModuleError` as defined in `go list -m`.
What is the reason for the difference?

**Comment by cagedmantis** [comment]
@perillo As you mentioned above, there has been a discussion about the original issue mentioned here on #35380. Do you think commenting on that issue would sufficiently help you express your suggested solution?

**Comment by perillo** [comment]
Yes, thanks.

**Comment by cagedmantis** [comment]
Great, thank you. Closing this issue.
