### ISSUE TITLE
x/build: add Amazon EC2 ARM instances for builders

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#36841]
As @bradfitz noted, we should explore adding ephemeral AWS ARM instances for both 32-bit and 64-bit ARM builds.

@toothrot @dmitshur

**Comment by toothrot** [comment]
See also #36170, for discussion of some of our requirements on ARM builders. We still have work to do there, but it might be worth taking care of it all at once.

**Comment by bradfitz** [comment]
@toothrot, if we did this bug, that bug would be not applicable.

We'd run each buildlet in its own VM (like we do on GCE, except using AWS), not using Docker (like Packet & Scaleway & PPC{,64}, etc).

We now have quota from AWS to run this for free, so it's just a matter of writing an AWSBuildletPool implementation.

**Comment by toothrot** [comment]
I understand that, but I wanted to make sure some of the other requirements were still being paid attention to, like creating a highcpu builder.
