### ISSUE TITLE
x/tools/gopls: detect pseudoversions in `gopls version`

### ISSUE THREAD

**Issue by stamblerre** [golang/go#36847]
We originally started tagging releases on master, which means that `gopls@master` reports its version as a pseudoversion starting with v0.1.8 (the last tag on master). This is misleading for users, at it makes its seem that `master` is behind `latest`. We should instead detect the pseudoversion and output something else when the user is at master.

**Comment by bcmills** [comment]
Better still, add some pre-release tags on the `master` branch.

(For example, you could tag the first commit after `gopls-release-branch.0.2` as `gopls/v0.3.0-dev` so that all of the pseudo-versions sort as pre-releases for `v0.3.0`.)

**Comment by stamblerre** [comment]
We've come to the realization that we probably won't be principled about tagging pre-release tags on master, and with that approach, the automatic version detection in VS Code version won't work for users that opt-into pre-releases. As an alternative, we're considering deleting all of the tags on master so that the pseudoversion appears as `v0.0.0`. This will have the effect of invalidating those pre-existing pseudoversions, which we've concluded is fine since they are old anyway and no one should depend on the `gopls` module.

**Comment by stamblerre** [comment]
We have since deleted all of the tags that were created on the master branch. Closing.
