### ISSUE TITLE
x/tour: bug/feedback reporter links to the wrong issue tracker

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#36843]
The feedback reporter on the top of each tour page links to the creation of an issue in the golang/tour issue tracker instead of the golang/go issue tracker. The documentation in the golang/tour repository directs the users to create an issue in the golang/go issue tracker.

**Comment by ALTree** [comment]
But we have always used the golang/tour issue tracker for the tour issues. It's the README that is wrong IMO. 

(unless you are planning to change this policy)

**Comment by cagedmantis** [comment]
@altree The link and the README should align. Let's ask the greater @golang/osp-team.

**Comment by dmitshur** [comment]
I believe the intention is for issues related to the content of the tour to be reported in the golang/tour issue tracker. The feedback reporter on the top of each tour page links to the right place.

Issues related to the _code_ in the golang.org/x/tour repository should be in the main Go issue tracker with a prefix of "tour:".

I think the README in x/tour repository can be made more clear.
