### ISSUE TITLE
x/tools/cmd/godoc: godoc should have a version flag

### ISSUE THREAD

**Issue by llimllib** [golang/go#36849]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/llimllib/go/bin"
GOCACHE="/Users/llimllib/Library/Caches/go-build"
GOENV="/Users/llimllib/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/llimllib/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org"
GOROOT="/usr/local/Cellar/go/1.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/llimllib/mct/backend/master/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r4/mc760j7j6xjdgr5p5hxk_xrw0000gq/T/go-build055316358=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

`godoc -version`

### What did you expect to see?

A version number

### What did you see instead?

```console
$ godoc -version
flag provided but not defined: -version
```

The godoc team suggests upgrading to the latest version to get module support: https://groups.google.com/forum/#!msg/golang-nuts/adEisyiOlwo/Q_5jL9ZKAwAJ

But there's no way to tell what version of godoc you are using, making it difficult to know if you have properly upgraded (especially since there are no documents on upgrading godoc (!))

**Comment by seankhliao** [comment]
godoc is frozen.
