### ISSUE TITLE
cmd/compile: confusing error message for 'a == x && b = y'

### ISSUE THREAD

**Issue by josharian** [golang/go#36858]
```go
package p

func f(a, b string) {
	if a == "a" && b = "b" {
	}
}
```

```
$ go tool compile x.go
x.go:4:25: syntax error: assignment a == "a" && b = "b" used as value
```

The conjunction isn't an assignment; the second conjunct is.

**Comment by josharian** [comment]
go/types says `x.go:4:5: expected boolean expression, found assignment (missing parentheses around composite literal?)`. Note that column 5 is the beginning of the conjunction.

**Comment by alain91** [comment]
I would like to have a look on this issue.
Could you confirm, the error message with go/types seems more relevant and would be the solution to use in go tool compile

**Comment by josharian** [comment]
I thought the original error message was pretty good. It is just being applied too broadly. It should read something like:

`syntax error: assignment b = "b" used as value`

And have its location be that of b = “b”, not of the entire conjunction.

**Comment by cuonglm** [comment]
It seems that the parser think the `LHS` of assignment is `a == "a" && b` and the `RHS` is `b`.

**Comment by cuonglm** [comment]
@josharian This is probably a simple fix for binary op:

```
diff --git a/src/cmd/compile/internal/syntax/parser.go b/src/cmd/compile/internal/syntax/parser.go
index f3c2c60ec8..ae26c4a396 100644
--- a/src/cmd/compile/internal/syntax/parser.go
+++ b/src/cmd/compile/internal/syntax/parser.go
@@ -1888,7 +1888,12 @@ done:
                // further confusion.
                str := String(s)
                if as, ok := s.(*AssignStmt); ok && as.Op == 0 {
-                       str = "assignment " + str
+                       prefix := "assignment "
+                       if lhs, ok := as.Lhs.(*Operation); ok && lhs.Y != nil {
+                               as.Lhs = lhs.Y
+                               str = String(as)
+                       }
+                       str = prefix + str
                }
                p.syntaxError(fmt.Sprintf("%s used as value", str))
        }
```

not sure it's applied for unary op or not 🤔

**Comment by josharian** [comment]
I don’t know much about the parser. Maybe mail that as a CL and discuss with mdempsky or gri? In any case it is easier to discuss diffs in a CL.

**Comment by alain91** [comment]
It seems that "help wanted" is no more required. I let Cuonlm finalize the fix.

**Comment by cuonglm** [comment]
Seems not worth to fix as pointing out by @griesemer in https://github.com/golang/go/issues/23385

**Comment by griesemer** [comment]
@cuonglm Since I was already investigating this a bit more, I just sent out at CL.
