### ISSUE TITLE
x/playground: Read sensitive information of sandbox golang testing on website

### ISSUE THREAD

**Issue by dwikikusuma** [golang/go#36860]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
Read sensitve information on `/etc/group`

### What did you expect to see?
It's should not return any information as another output in `exec.Command`
![No return in golang demo terminal](https://user-images.githubusercontent.com/25258929/73342382-05130a80-42b1-11ea-860e-34ef8c22184f.png)

### What did you see instead?
The server return group sandbox information
https://golang.org/pkg/io/ioutil/#example_ReadFile
![return information group in golang demo terminal](https://user-images.githubusercontent.com/25258929/73342440-24aa3300-42b1-11ea-8322-63cd414e41cb.png)

Best Regards,
Thanks

**Comment by toothrot** [comment]
I don't believe the contents of our gvisor hosted containerized filesystem are secret. Our treatment of this changed in http://golang.org/cl/195983 (by @bradfitz). 

There's no persistence between runs, so I believe this to be generally OK.

**Comment by bradfitz** [comment]
Yeah that's all fake. Not a security issue.

**Comment by dmitshur** [comment]
Thanks for confirming. I'll close this because there's nothing to do.
