### ISSUE TITLE
x/crypto: commits lost from 1.13 release branch

### ISSUE THREAD

**Issue by rittneje** [golang/go#36866]
We have a mirror job for the x/crypto repo. It is now failing because commit 8b5121be2f68d8fc40bb06467003bdde1040a094 was applied on top of commit 5c40567a22f818bd14a1ea7245dad9f8ef0691aa. So the following commits have vanished from the head of release-branch.go1.13:

- 57b3e21c3d5606066a87e63cfe07ec6b9f0db000
- ea8f1a30c4438cc8b13f05538385ad8dc6049b43
- cc06ce4a13d484c0101a9e92913248488a75786d
- 4def268fd1a49955bfb3dda92fe3db4f924f2285
- 60c769a6c58655dab1b9adac0d58967dd517cfba

Was this expected?

**Comment by ALTree** [comment]
See https://github.com/golang/go/issues/36842#issuecomment-579432439:

> The release branches in x/crypto are really internal implementation details, they are not documented and not covered by our security policies, and I didn't know anyone actually used them. 

I'm closing here as a dup, but feel free to subscribe to that other thread. I'm afraid the conclusion is "do not track those branches, only master is supposed to be tracked".
