### ISSUE TITLE
go/build: TestImportDirNotExist fails when running all.bash

### ISSUE THREAD

**Issue by vovapi** [golang/go#36867]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/vladimir/Library/Caches/go-build"
GOENV="/Users/vladimir/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/vladimir/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rn/t2tk57cn2h7f2kbbhpy0vx7h0000gq/T/go-build571665734=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
Running on macOS Catalina 10.15.2
</details>

### What did you do?
I follow [contribution guide](https://golang.org/doc/contribute.html#sending_a_change_gerrit)
```
$ git clone https://go.googlesource.com/go
$ cd go/src
$ ./all.bash  
```

### What did you expect to see?

```
...
ALL TESTS PASSED
```

### What did you see instead?
```
...
--- FAIL: TestImportDirNotExist (0.03s)
    build_test.go:346: Import(full, 0) got error: "package go/build/doesnotexist is not in GOROOT (/Users/vladimir/golang/go/src/go/build/doesnotexist)", want "cannot find package" error
    build_test.go:346: Import(full, FindOnly) got error: "package go/build/doesnotexist is not in GOROOT (/Users/vladimir/golang/go/src/go/build/doesnotexist)", want "cannot find package" error
FAIL
FAIL    go/build        0.884s
...
FAIL
go tool dist: Failed: exit status 1
```

### Possible cause
The issue seems to be caused by GO111MODULES turned on by default. If I set `GO111MODULES=off` in run.bash everything works fine.

**Comment by bcmills** [comment]
This appears to have regressed in [CL 199840](https://golang.org/cl/199840). Should be a pretty easy fix.

**Comment by bcmills** [comment]
I was mistaken. The actual regression was in [CL 210339](https://golang.org/cl/210339).

**Comment by bcmills** [comment]
I was mistaken again. 😅

I actually bisected the failure properly this time, and it's from [CL 203820](https://golang.org/cl/203820), for #34860.

**Comment by vovapi** [comment]
Yep. I bisected it too and got [CL 203820](https://golang.org/cl/203820)
