### ISSUE TITLE
go/build: doesn't properly use backslashes on Windows

### ISSUE THREAD

**Issue by al45tair** [golang/go#36861]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\alastair.houghton\AppData\Local\go-build
set GOENV=C:\Users\alastair.houghton\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\work\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ALASTA~1.HOU\AppData\Local\Temp\go-build003328866=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I was trying to use operator-sdk on Windows. I know, I know, I'm on Windows...

The <tt>operator-sdk generate k8s</tt> command was putting files in the wrong place. The _reason_ for this is that, on Windows, the <tt>IsLocalImport()</tt> function in <tt>src/go/build/build.go</tt> gets passed a path that looks like this:

<pre>.\\pkg\\apis\\foobar\\v1alpha1</pre>

whereupon it returns <tt>false</tt>, because it's looking for forward slashes.

### What did you expect to see?
Everything in build.go should probably work on Windows. Right now, I can see a number of other things that won't as well.

<tt>IsLocalImport()</tt> should presumably just use <tt>filepath.IsAbs()?</tt>

### What did you see instead?
There's code in <tt>src/go/build/build.go</tt> that is clearly not right for Windows because it relies on pathnames containing slashes where on Windows they're going to contain backslashes instead.

**Comment by al45tair** [comment]
OK, so using `filepath.IsAbs()` didn't work. The following change, however, does appear to fix things:

```
diff --git a/src/go/build/build.go b/src/go/build/build.go
index e89aa7708d..4b77cba901 100644
--- a/src/go/build/build.go
+++ b/src/go/build/build.go
@@ -1829,8 +1829,12 @@ var ToolDir = getToolDir()
 // IsLocalImport reports whether the import path is
 // a local import path, like ".", "..", "./foo", or "../foo".
 func IsLocalImport(path string) bool {
-       return path == "." || path == ".." ||
-               strings.HasPrefix(path, "./") || strings.HasPrefix(path, "../")
+       if path == "." || path == ".." {
+               return true
+       }
+       slashPath := filepath.ToSlash(path)
+       return strings.HasPrefix(slashPath, "./") ||
+               strings.HasPrefix(slashPath, "../")
 }

 // ArchChar returns "?" and an error.
```

I'm not sure this is necessarily the correct fix, and building a new version of Go on Windows was... fun. (Maybe the docs for that need clarifying a bit; some of the tests appear to fail, at least on my box here, but nothing relating to this change - they fail with the original code too.)

**Comment by heschik** [comment]
> IsLocalImport reports whether the import path is...

Import paths are slash separated. The upstream project shouldn't be using `IsLocalImport` on filesystem paths.

**Comment by al45tair** [comment]
OK, in which case the bug would seem to be upstream in `k8s.io/gengo`. I'll fix it there instead. Thanks :-)
