### ISSUE TITLE
x/pkgsite: examples missing playground links

### ISSUE THREAD

**Issue by myitcv** [golang/go#36865]
### What is the URL of the page with the issue?

https://pkg.go.dev/regexp?tab=doc#example-MatchString

### What is your user agent?

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.66 Safari/537.36
</pre>

### Screenshot

<img width="1022" alt="Screen Shot 2020-01-29 at 13 09 25" src="https://user-images.githubusercontent.com/3374574/73359422-b3f71c80-4298-11ea-9e77-dbfb86a4051d.png">

### What did you do?

Visited the link above to view the example.

### What did you expect to see?

Expected to see a link that takes me to the example in the Go Playground, like godoc.org

<img width="726" alt="Screen Shot 2020-01-29 at 13 09 44" src="https://user-images.githubusercontent.com/3374574/73359457-cb360a00-4298-11ea-9dbd-d87331fac409.png">

### What did you see instead?

No link.

**Comment by muv1** [comment]
Yes thanks, I came here looking for this. If you visit the current site:

<https://golang.org/pkg/io#Copy>

You get complete example, with `package main` and everything. The example itself
is even editable without leaving the page, which is nice. You can run the
exmaple from the same page, or hit "Share" and it takes you to:

<https://play.golang.org>

Now if you visit the same page with the new site:

<https://pkg.go.dev/io#Copy>

You dont get a complete example, everything is stripped except for pretty much
the function call itself. The example is not editable. The example is not
runnable. No "Share" button is available to test with the playground. Overall
I would say its a worse experience, and I wont be updating my links.

I get that some might want to clean things up and remove cruft, but at a minimum
the playground links should be put back in. For myself, full, complete examples
are a critical part of the learning process. Please put them back in.

**Comment by muv1** [comment]
https://github.com/golang/go/issues/37819

**Comment by AceroM** [comment]
This feature is now code complete and will be available soon on pkg.go.dev.The output should look like this:
![Kapture 2020-08-20 at 11 38 04](https://user-images.githubusercontent.com/21187304/90796128-eb80f100-e2dc-11ea-94b8-bd0b67056f00.gif)
This will work for all playable examples on pkg.go.dev.

If you would like to test it out locally, you can do so by:
Running `go run ./devtools/cmd/experiment create executable-examples` to enable the experiment flag
Setting [this CSS class](https://github.com/golang/pkgsite/blob/56517e4b414745c963a2b1b9250c236631d9011f/content/static/css/stylesheet.css#L1219) to `display: flex;`

**Comment by nu8** [comment]
https://github.com/golang/go/issues/41403

**Comment by mvdan** [comment]
Why was this issue closed? Has it been fixed? Please specify when closing.

**Comment by nu8** [comment]
@mvdan have you checked? I do agree with you - but if you check playground links have been added to the new site

**Comment by AceroM** [comment]
> Why was this issue closed? Has it been fixed and deployed? Please specify when closing.

Sorry about that! 😅 As @nu8 mentioned The "play" button is deployed now and should appear in packages with examples.
