### ISSUE TITLE
x/tools/go/analysis: migrate golint to use go/analysis

### ISSUE THREAD

**Issue by stamblerre** [golang/go#36869]
This is a key missing piece in the `gopls` analysis suite, and it has come up repeatedly as an issue for editor clients (see https://github.com/microsoft/vscode-go/issues/2517 for a recent example). Creating a tracking issue here since `golint` has its own issue tracker and its own issue for this (https://github.com/golang/lint/issues/463).

Something worth considering is whether this means that `golint` will be moved into `x/tools` or if it should remain its separate repository.

/cc @matloob

**Comment by matloob** [comment]
cc @hyangah, who I think has done some work on this.

I think golist should stay in a separate repository. We could put the passes in tools (though I'd prefer not to) but the binary itself should not be in tools.

**Comment by stamblerre** [comment]
Seems like @hyangah has a stack of changes to convert `golint` to `go/analysis`, starting with [CL 212797](https://go-review.googlesource.com/c/lint/+/212797). I think that if these CLs go in, we can start adding them into `gopls`.

**Comment by dominikh** [comment]
Relevant: https://github.com/golang/go/issues/38968

**Comment by mvdan** [comment]
https://github.com/golang/go/issues/38968 is accepted and golint is deprecated and being frozen this week - closing.
