### ISSUE TITLE
x/build/dashboard: missing trybot for linux-riscv64

### ISSUE THREAD

**Issue by bcmills** [golang/go#36871]
golang.org/x/build/dashboard.TestTryBotsCompileAllPorts started failing at [CL 216758](https://golang.org/cl/216758). It appears that we are missing a TryBot build for `linux-riscv64`, and thus the port is apparently not complete after all.

CC @4a6f656c @bradfitz @ianlancetaylor @dmitshur @cagedmantis @toothrot

**Comment by dmitshur** [comment]
[CL 216765](https://golang.org/cl/216765) was reverted via [CL 217723](https://golang.org/cl/217723), so re-opening.
