### ISSUE TITLE
x/tools/gopls: add regression testing

### ISSUE THREAD

**Issue by stamblerre** [golang/go#36879]
We've been using the `govim` tests for regression testing, which creates unnecessary load on @myitcv in filing and reproducing issues. It also places too much reliance on one specific editor client. We should develop our own regression tests that use a fake client.

/cc @findleyr

**Comment by stamblerre** [comment]
A couple thoughts as I work on https://golang.org/cl/225317:

- It would be helpful to be able to get the `gopls` logs for a test after it runs.
- One useful application for generating tests from logs would be the ability to automatically generate a sequence of calls to the appropriate functions for a sequence of text synchronization events. In my case, the repro is a bit complicated, and I still haven't been able to get the right ordering--the issue reproduces differently in VS Code and in my test. It would be great if I could just pass my VS Code log into a generator and have it produce the correct series of calls. (cc @pjweinb)

**Comment by findleyr** [comment]
Closing this now that the regtest framework is somewhat mature and documented, and we have decent test coverage. We will continue to add more tests and improve the framework, but I believe this tracking issue has served its purpose. In the future, we should open new issues for any specific regtest bugs or feature requests.
