### ISSUE TITLE
`release-branch.go1.13` is behind the `go1.13.7` tag

### ISSUE THREAD

**Issue by reedobrien** [golang/go#36873]
The `release-branch.go1.13` is behind the `go1.13.7` tag.

It appears that the `release-branch.go.1.13-security` branch was not merged into `release-branch.go1.13`.

It also appears that `release-branch.go1.12` is behind the `go1.12.16` tag.

_ediited to add 1.12 and minor formatting adjustment_.

**Comment by mvdan** [comment]
Why would anyone depend on those branches, though? The only stable and supported versions are the tagged ones. I don't think there is a guarantee that `release-branch.go1.13` equals the latest released `1.13.x`. For example, if the team is working on `1.13.8` for a week, it will be ahead of `1.13.7`, and potentially unstable.

**Comment by OneOfOne** [comment]
I personally have a script to build the latest 3 versions of go + tip based on `release-branch.*` and `master`, I can imagine a few people do that as well.

**Comment by mvdan** [comment]
I'm arguing that that's not what you should be doing :) You should be listing https://golang.org/dl/?mode=json to figure out what the latest Go `1.13.x` is, and download that specific version.

If it was up to me, branches like `release-branch.go1.10` would be deleted, because those branches shouldn't see any more updates. The 1.4 bootstrap version already has its own separate branch for that very purpose.

**Comment by siebenmann** [comment]
If you keep your own copy of the Go git repo and pull from upstream, detached tags such as these will not be pulled automatically and updating your local repo to the latest remote tag (and its commits) is not particularly pleasant and ergonomic. It's rather simpler for people if the tags are on the release branches so you can set your repo to track them, pull and fast-forward, and then build to get the latest version.

(Detaching go 1.13.7 and go 1.12.16 from their branches is also a break with historical practice in minor version updates.)

**Comment by josharian** [comment]
@siebenmann I run `git fetch origin --tags` to grab the latest tags.

**Comment by josharian** [comment]
@OneOfOne could you modify that script to use the tags instead? Also, if you published that (modified) script somewhere, I'd probably use it.

**Comment by OneOfOne** [comment]
@josharian https://github.com/OneOfOne/dotfiles/blob/04f0f32f66635a874ee0381f6a9c7a30600f6f76/.env.d/10-code.zsh#L58

mainly ```
function addgotree {
	local v="$1"
	pushd /usr/src/go >/dev/null && trap "popd >/dev/null" EXIT
	git pull --all || return 1
	git worktree remove ../go$v
	git branch -d go$v &>/dev/null
	git worktree add ../go$v --track -b go$v --checkout origin/release-branch.go$v || return 1
	rebuildgo $v
}

function removegotree {
	local v="$1"
	pushd /usr/src/go >/dev/null && trap "popd >/dev/null" EXIT
	git worktree remove ../go$v
	git branch -d go$v &>/dev/null
	rm -v ~/bin/go$v
}

function rebuildgo {
	local v="$1"
	pushd "/usr/src/go$v/src" >/dev/null && trap "popd >/dev/null" EXIT
	rm -rf ../pkg ../bin $GOPATH/pkg &>/dev/null

	git reset --hard || return 1
	git clean -fdx || return 1
	git pull -v || return 1

	env GOROOT_BOOTSTRAP=/usr/lib/go CC=gcc GOGC=off bash make.bash || return 1

	if [ "$v" != "" ]; then
		../bin/go clean -r -cache -testcache &>/dev/null
		ln -s $PWD/../bin/go ~/bin/go$v
	fi

	echo -------------------------------
	echo updated $(../bin/go version)
	echo -------------------------------
}
```

**Comment by mvdan** [comment]
Thinking outloud, I wonder if an endpoint like `/dl?mode=json&version=1.13.x` would be useful. It's not rocket science to do it yourself, but it requires at least a few lines of non-trivial shell, and parsing JSON is always difficult to do in portable shell.

**Comment by reedobrien** [comment]
good to know that it isn't what we're supposed to do, but it has been kept up to date since... as long I can remember. Closing since it is a faulty assumption, and I'll figure out a different workflow.

**Comment by reedobrien** [comment]
FWIW, [this also documents](https://golang.org/doc/devel/release.html) using release branches:
Specifically it says:

To update to a specific release, use:
```
git pull
git checkout release-branch
```

**Comment by reedobrien** [comment]
Reopening since there are conflicting instructions. Happy to open a doc issue for the last comment, or just leave this for tracking.

**Comment by FiloSottile** [comment]
@reedobrien Good catch on the docs, sent a CL to change them to

```
git fetch --tags
git checkout go1.X
```

I'll close this by making the merges, which anyway we should be making soon after a release just to make sure they aren't forgotten. It's still inadvisable to use the development release branches rather than the tags.

/cc @dmitshur

**Comment by reedobrien** [comment]
🤔 development release branches.

Thanks for updating the docs, and for all the great work @FiloSottile @mvdan, et al. 

I knew I didn't magically decide to do it myself. It is kind of cool that it hasn't been an issue for many fine years. I've updated my process for building as well. 

Cheers,
Reed

**Comment by FiloSottile** [comment]
> 🤔 development release branches.

They are the branches where the releases are developed :)

**Comment by dmitshur** [comment]
We have submitted [CL 217061](https://golang.org/cl/217061), which has resolved this issue.

```
$ git merge-base --is-ancestor go1.13.7 origin/release-branch.go1.13
$ echo $?
0
```
