### ISSUE TITLE
strconv.contains should be public

### ISSUE THREAD

**Issue by purpleidea** [golang/go#36877]
### What version of Go are you using (`go version`)?

<pre>
git master
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GNU+Linux

If you look at the `strconv` code, you'll see:

```
// contains reports whether the string contains the byte c.
func contains(s string, c byte) bool {
	return bytealg.IndexByteString(s, c) != -1
}
```

I'd like to use this function, because I have a modified version of the `Unquote` and `UnquoteChar` functions that I have written. Unfortunately, I can't use this one because it's not public. Can you either make this public and/or make the `bytealg` function public? It's in an internal package which you can't import.

Thanks!

**Comment by OneOfOne** [comment]
https://pkg.go.dev/strings/?tab=doc#IndexByte

```
// IndexByte returns the index of the first instance of c in s, or -1 if c is not present in s.
func IndexByte(s string, c byte) int {
	return bytealg.IndexByteString(s, c)
}
```

**Comment by purpleidea** [comment]
@OneOfOne This is very helpful, thanks!
