### ISSUE TITLE
x/tools/go/expect: add better marker support for // indirect in go.mod files

### ISSUE THREAD

**Issue by ridersofrohan** [golang/go#36894]
Currently in `go/expect` when a user wants to add a marker for `go.mod` files, we have a special case if they are trying to mark `// indirect`:

```
//@mark(IndirectMarker, "// indirect")
require golang.org/x/tools v0.0.0-20191219192050-56b0b28a00f7 // indirect
```

This is a little confusing and is the only case where the marker has to be on the line above. As a result, there should be a better way to do this that is more intuitive that does not require having a special case just for this.

This issue is an extension of #36091 

/cc @stamblerre @ianthehat

**Comment by findleyr** [comment]
The logic that this issue referred to no longer exists. Closing.
