### ISSUE TITLE
type of math.MaxInt64 should be int64 instead of int 

### ISSUE THREAD

**Issue by vitesse-ftian** [golang/go#36901]
### What version of Go are you using (`go version`)?
1.13
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?

Yes, repro-ed on go playground

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

https://play.golang.org/p/LGRoTC_euz0

### What did you expect to see?
Should compile, 

### What did you see instead?
Compiler complaining math.MaxInt64 is of type int.

**Comment by randall77** [comment]
This is intended behavior.

`math.MaxInt64` is an ideal constant. It does not have a type as such. Your `imax` variable gets the default type for integer constants, which is `int`. You should instead do either of these:
```
imax := int64(math.MaxInt64)
var imax int64 = math.MaxInt64
```
See the "default type" section of https://blog.golang.org/constants

**Comment by ianlancetaylor** [comment]
For the record, previously discussed in #19261, #23086, and #23163.  See also #23087.
