### ISSUE TITLE
std,cmd: add a unit test to ensure that src/go.mod and src/cmd/go.mod are in sync

### ISSUE THREAD

**Issue by bcmills** [golang/go#36907]
In https://github.com/golang/go/issues/36851#issuecomment-580438655, @FiloSottile noticed that the `std` module and the `cmd` module currently depend on different commits of the `golang.org/x/sys` module.

We should prevent such skew in the future. It should be straightforward to write a test that uses `go list` (or a similar approach) to check that the versions required by `std` and `cmd` agree for the modules in the intersection of their dependencies.

**Comment by ianlancetaylor** [comment]
It's not wholly clear to me why we need to vendor golang.org/x/sys in two different places.

**Comment by FiloSottile** [comment]
See also #36852.

**Comment by bcmills** [comment]
@ianlancetaylor: `std` needs `golang.org/x/sys/cpu`, whereas `cmd` needs `golang.org/x/sys/unix`.

We don't put `std` and `cmd` in the same module because we want to make it easy to see that `std` does not depend on anything unexpected, especially outside of `x/`. In contrast, `cmd` depends on a few modules external to the project (`github.com/ianlancetaylor/demangle` and `github.com/google/pprof`).

**Comment by bcmills** [comment]
@FiloSottile, note that the test described in #36852 requires network access (in order to download the pristine dependencies for comparison), while the test described here can (at least partially) be computed offline from the contents of `src/vendor/modules.txt` and `src/cmd/vendor/modules.txt`.

**Comment by dmitshur** [comment]
This issue is currently labeled as early-in-cycle for Go 1.15. That [time is now](https://groups.google.com/d/msg/golang-dev/y0yM_Xi665Q/mk35pLnjCAAJ), so friendly ping. If it no longer needs to be done early in cycle, that label can be removed.

**Comment by dmitshur** [comment]
I'm very glad this test exists and found it to work well while developing [CL 231657](https://golang.org/cl/231657). Thank you @bcmills and @FiloSottile!

<details><br>

Here's an excerpt from a moment when the x/sys versions diverged between the two modules; the test reported it correctly.

```
--- FAIL: TestDependencyVersionsConsistent (0.00s)
    moddeps_test.go:217: Modules within GOROOT require different versions of golang.org/x/sys.
    moddeps_test.go:229: cmd	requires v0.0.0-20191204072324-ce4227a45e2e
    moddeps_test.go:229: std	requires v0.0.0-20200323222414-85ca7c5b95cd
FAIL
FAIL	cmd/internal/moddeps	10.795s
```

</details>
