### ISSUE TITLE
Go Reference Manual Needed

### ISSUE THREAD

**Issue by Conformable** [golang/go#36906]
### What version of Go are you using (`go version`)?

<pre>
$ 1.13.5
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user2/Library/Caches/go-build"
GOENV="/Users/user2/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/user2/A/AL3/code/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8v/vpckwgfs4_547sb94qr9f4d40000gq/T/go-build470115836=/tmp/go-build -gno-record-gcc-switches -fno-common"

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?
Integrated, comprehensive, up to date reference manual 

### What did you see instead?
WSOGMM

**Comment by Conformable** [comment]
Left off this part:

**Comment by Conformable** [comment]
It has surely been a pleasure learning Go from scratch at version 1.13 after so much hard work has been completed. I do not say that ironically. I like it. But I have noticed that the documentation for Go is widely dispersed -- everything is out there, somewhere., but... Specifically, the language spec is nice, and Effective Go is also nice. And so are the blog posts, the wiki, stackoverflow, issues, and the various tutorials written by many people. But as time goes by some of the material is dated and not necessarily the latest and best stuff. Also, the language specification may be all an expert needs, since everything is already perfectly understood, but for someone beginning with the language, it reads like software -- lots of function calls that need to be unfolded (178 grammar production rules invoking each other :-)

Given that Google is a trillion dollar company and that there are 1500 Go contributors, it should not be impossible to write a definitive reference manual that pulls everything together for each topic. I note the goal of Go from the home page:

"Go is an open source programming language that makes it easy to build simple, reliable, and efficient software."

I think that a reference manual would go a long way towards making that statement true(r), especially the "easy" part.

(Sorry if this is an old proposal. I did do some hunting...)

**Comment by ianlancetaylor** [comment]
I agree that the Go documentation could and should be more coherent, but it's not obvious to me that this is the right approach.  This is probably a dumb question, but can you explain what would be in the reference manual?  For example, what would the table of contents look like?

There are a number of good books out there about Go.  Do any of them serve the role you are looking for?

(Although Google is a trillion dollar company, the Go team at Google is very small.)

**Comment by Conformable** [comment]
A reference manual for the Go language would be much longer than the language specification because all related information about a topic/task would be incorporated into a single section/chapter, even though that might mean redundancy with other sections. Take Arrays and Slices as an example. The rules covering these closely related topics are spread throughout the language specification in Types, Declarations, Expressions, Built-in Functions, etc. Or, an even better example is Error Handling, which is spread across Built-in Functions, Errors and Panics plus the Errors package documentation. A definitive reference chapter would be titled "Error Handling" and cover all aspects, including return values. (The language spec coverage of errors seems sparse to me, BTW.)

Probably the Table of Contents would have much in common with the language specification but would incorporate other information as well, and would have task oriented sections. Like Modules, Internationalilzation, File Handling, Network Access, and so on...the things that user-programmers need to do -- as opposed to the things that language programmers need to write code for. Mathematically, take the grammar production rules and unfold them from 178 rules into 600 or however many, so that each variation/form of each rule is presented with explanations and examples. 

re: "(Although Google is a trillion dollar company, the Go team at Google is very small.)" 
--> I appreciate that. However, perhaps it would make sense to hire documentation experts to craft a reference manual for Go. Invest some money. I bet the process would produce benefits because the process of explaining things instructionally is educational. I generally like to write the user manual before coding based on the theory that if I cannot explain it in English then how can I write it in code? If it is difficult to explain then maybe it needs simplifying. (Not saying that is the case here but there would be gains.)

**Comment by ianlancetaylor** [comment]
Thanks for the detailed suggestions.

There are already, as I mentioned, books about Go.  Quite a few, in fact: https://golang.org/wiki/Books.  Do you think any of them are useful?

It's not a big deal, but the people at Google who can "invest some money" may have heard in passing that there is a programming language called Go, but I doubt it's a topic they pay much attention to.

**Comment by networkimprov** [comment]
>It's not a big deal, but the people at Google who can "invest some money" may have heard in passing that there is a programming language called Go, but I doubt it's a topic they pay much attention to.

You wouldn't say the same about their counterparts at Oracle (and Sun before them) re Java, nor at Microsoft re C#/.NET. So I'd say that's a key factor limiting the development and adoption of Go.

**Comment by Conformable** [comment]
Actually, I had  to read a Java book and then do things badly before I could do much. But back in the day, when IBM 370's with 4MB of RAM were hot, I spent a lot of time reading the Cobol Reference Manual. Enough to get a job as a trainee off the street. Punch cards, etc. I also had a course book. 

However, with Go I have been attempting to stick with the "Official" documentation unless I'm stuck. 

It is possible that better documentation would increase acceptance of Go beyond its already massive popularity. For example, it seems clear that the UI for Go programs is expected to be batch console or internet/html. Which is fine with me, but do I need to learn Javascript as well? There's a lot to consider here, many different technologies to put together. It's gonna take some time.

My next project -- after I finsih a baby package to manage parameters, messages and keyboard UI for my own little projects, is to sort the Go grammar production rules using Google PageRank algorithm based on each rule's references by other rules. That will, I think, inform me of the correct study sequence and where to devote the most time.

Another idea is to parse all of the Go documentation and code -- packages, lang spec, tools, etc. -- and develop an index of references. Perhaps the index topics could also be PageRank'ed to determine the most vital topics to be studied and documented. Once a topic is selected all of the references to it will define its true meaning and it will just need some explaining...a narrative.

I think also that a reference manual would be prescriptive as well as descriptive, explaining
the why's and how-to's in addition to the what's legal. Imagine if someone took all of the Unicode math symbols, provided a grammar for them with syntax trees and definitions, and then said, "Ok, people, now start mathing!"  Of course, Go already has the standard library packages which form, in a sense, the fundamental Go theorems which may be used to construct new Go theorems/programs; very helpful...

**Comment by bcmills** [comment]
#33637 describes a sort of “reference manual” for Go modules, at least.

**Comment by Conformable** [comment]
Upon reflection: consider that the language specification must necessarily be abstract, implementation agnostic and suitable for programming the language and tools. A "Go Programming Reference Manual" should not be those things, but could refer to the language spec from time to time. 

The needs of programmers writing applications in Go are concrete and practical, not abstract and theoretic. As an example of the distinction: where the language spec definitely cannot refer to the standard library packages, the Go Programming Reference should, because they're pretty well locked in after 10 years of work. The library packages such as "errors" are widely used and integrated into "The Go Way", especially version 1.13 -- Is(), As(), Unwrap(), etc. And use of errors is closely related to use of panic and defer as part of "Error Handling", the topic, for which there is most definitely a "Go Way" of doing it. So, I envision a Programming Reference to incorporate the essential information from the language specification and integrate information from the standard library as well as the tools (e.g. modules).

Sure this is a lot of work. I don't plan to die on this hill, as they say. But if Google isn't interested in making an investment by hiring documentation authors, perhaps since Go has 1500 contributors, it could be crowdsourced. Starting with a table of contents. I'll begin: Program Initialization, Program Termination, File I/O, Sorting, Searching, Data Structures, Databases, Arrays and Slices, Mathematical Computation, Network I/O, Concurrency, Parallelization, Debugging, Testing, Logging, Printing, Keyboard I/O, Graphics, Restart and Recovery...plus the lang spec stuff: variables, constants, control, and so on. Then, once the main topics are selected, begin writing each as a chapter by crowdsourcing the sub-topics to be covered. And just go chapter by chapter -- one by one, or in parallel, depending. Note: a lot of the stuff has already been written and just needs to be integrated and brought up to date with the most current "Go Way".

**Comment by networkimprov** [comment]
@Conformable did you work through https://tour.golang.org?

**Comment by Conformable** [comment]
Partly.

**Comment by cagedmantis** [comment]
For asking questions about learning the language, see one of our forums: https://golang.org/wiki/Questions. We only use this issue tracker for tracking bugs. People in the forums can guide you towards great Go resources.

**Comment by Conformable** [comment]
Well, it wasn't a question for me -- it is my opinion. The Language Specification is not a reference manual for application programmers, else there wouldn't be the need to keep writing blog posts, etc. And it has many things missing. For example, "/=" occurs exactly once in the text; it is listed as an operator, that's it. 

All in all, the information needed is "out there" on the net and in books. It's in many places...

If there is any interest, I did manage to get a sort of the EBNF grammar production rules in the go-spec.html document: 
https://github.com/Conformable/MiscNotesAndReports/blob/master/GoGrammarRulesByPageRank.csv

I suppose we could say it lists the elements of Go by grammatical importance. 
Probably go do the same thing for packages in the standard library.
