### ISSUE TITLE
cmd/go: 'go get' appears to have no way to specify a branch in it that contains a `/`

### ISSUE THREAD

**Issue by CyrusNajmabadi** [golang/go#36902]
Extracting this bug out of the doc conversation that happened here https://github.com/golang/go/issues/30851

Currently `go get` claims to be able to allow you to get a module hosted at a location with a given branch name.  i.e. `go get github.com/pulumi/pulumi@some_branch`.  However, there seems to be no way to make this work if the branch has a `/` in it.  i.e. neither `go get github.com/pulumi/pulumi@cyrusn/somefix` nor `go get github.com/pulumi/pulumi@features/2.0` work.

This effectively makes `go get` and modules non-viable for projects that use a very common and *legal* naming strategy for branches. Note that both `git` and `github` are fine with this sort of naming, and it's encouraged in many repos (as it helps keep the list of branches from getting very cluttered).

`go get` should not arbitrarily restrict the set of branch names it accepts.  

Workarounds:
You can write `go get ...@deadbeef`. however this only gives you a point-in-time version of the module.  There does not seem to be a way to get all the functionality normaly present with a branch-link if the branch contains a `/`.

**Comment by hausdorff** [comment]
It's worth noting that there are a lot of people on that issue complaining about this. The skepticism expressed by maintainers that no one does this in the world is completely unwarranted. I've seen people do this at every company I've ever been in, and it is trivially easy to find Go projects on GitHub that actively use this strategy _currently_. For starters: basically any project that has to keep secrets back from PRs will use this strategy.

How can we help to fix this?

**Comment by CyrusNajmabadi** [comment]
agreed.  The original was closed with this comment:

> Technically you could have a branch name with slashes in it. I sincerely doubt that many, if any, repositories containing Go code will have such branches.

Which was responded to with several dozen downvotes.  

Even if this is a current heuristic for `go get`, there can certainly be fixes made here to deal with the issue.  For example, allowing someone a way to just explicit specify a branch name with no restrictions from the `go` tool as to what it should be.  

`Heuristics` (as stated by @bcmills  [here](https://github.com/golang/go/issues/30851#issuecomment-473041898)) are a bad thing.  When it comes to this sort of decision, there should be a clear and easy way for people to specify the things they have that are otherwise entirely legal and normal today.

**Comment by bcmills** [comment]
> i.e. neither `go get github.com/pulumi/pulumi@cyrusn/somefix` nor `go get github.com/pulumi/pulumi@features/2.0` work.

When you say they don't work — what is the failure mode today?

(I would expect those to successfully resolve to a pseudo-version when fetching directly from source control, but not when fetching from a proxy.)

**Comment by grellyd** [comment]
This issue presents itself as:

`go get github.com/org/repo@namespace/branch: github.com/org/repo@namespace/branch: invalid version: version "branch" invalid: disallowed version string`

A workaround at this time is to `git log` the sha of the namespaced branch and then `go get` using that sha. 

EG: `go get github.com/org/repo@sha`

**Comment by grellyd** [comment]
What further information is needed? Happy to help provide more details to move past the `WaitingForInfo` stage.

**Comment by bcmills** [comment]
@grellyd, please file a new issue. (The issue template has headings and descriptions for all of the needed information.)

It would be especially helpful to see how the behavior varies with different settings for `GOPROXY` (default vs. `direct`) and `GOPRIVATE` (unset vs. something that matches the module in question).

**Comment by grellyd** [comment]
@bcmills I had a vain hope that commenting would automatically re-open the existing issue. :joy: Oh well. New issue incoming.
