### ISSUE TITLE
x/tools/gopls: stylistic diagnostics emitted for generated code

### ISSUE THREAD

**Issue by muirdm** [golang/go#36914]
In particular the staticcheck "ST*" stylistic checks seem to be reporting diagnostics for generated code. I think the staticcheck standalone driver suppresses stylistic errors for generated files.

To reproduce, ensure gopls staticcheck integration is enabled and create a file foo.gen.go:

```go
// Code generated by robot.
// DO NOT EDIT!

package foo

var REALLY_Good_Name = 1
```

I expect to see no diagnostic for "REALLY_Good_Name" but I get ST1003.

**Comment by dominikh** [comment]
The issue here seems to be that your "code generated by" comment doesn't match the agreed upon format, nor any of the explicit exceptions that staticcheck handles. See https://github.com/golang/go/issues/13560 and https://github.com/golang/go/issues/13560#issuecomment-277804473 in particular.

**Comment by muirdm** [comment]
I based my comment off of tools/internal/lsp/source/util.go:
```go
// Matches cgo generated comment as well as the proposed standard:
//	https://golang.org/s/generatedcode
var generatedRx = regexp.MustCompile(`// .*DO NOT EDIT\.?`)
```

This updated repro still reports the stylistic warning:
```go
// Code generated by robot. DO NOT EDIT
package foo
var FOO_Bar = 1
```

The generated file suppression is in the staticcheck driver, no in the checks themselves, right? I didn't see any code in gopls trying to skip analyses based on generatedness.

**Comment by muirdm** [comment]
Ah, nevermind. I see the fact now in `ReportfFG`.

**Comment by dominikh** [comment]
For people watching at home: AFAIK gopls has no notion of hiding diagnostics in generated files, but the checks in staticcheck use a special analysis (`honnef.co/go/tools/facts.Generated`) to detect generated files. As such, using staticcheck's analyses in gopls (or any other runner) still benefits from the detection of generated files. Each analysis itself gets to decide whether a diagnostic should be hidden from generated files or not, without the runner's involvement.

**Comment by stamblerre** [comment]
FWIW, `gopls` does [detect generated files](https://github.com/golang/tools/blob/d6d1b0d85358d89bbcc8ec54529aaa4ce6984462/internal/lsp/source/util.go#L144) in some cases (for example, if you start to edit the file). We don't hide diagnostics because you would want to know if it doesn't compile, but I guess what you're saying is that we can also rely on staticcheck to make a reasonable decision about if a diagnostic is worth showing in a generated file?

**Comment by dominikh** [comment]
> but I guess what you're saying is that we can also rely on staticcheck to make a reasonable decision about if a diagnostic is worth showing in a generated file?

That is correct.
