### ISSUE TITLE
gollvm: build failure: no matching function for call to [std::string](llvm::StringRef, int, const int&)

### ISSUE THREAD

**Issue by Grissess** [golang/go#36912]
Hello!

On a work machine, with some of the repositories set up before I started, I'm trying to get a build of gollvm working following [these instructions](https://go.googlesource.com/gollvm/#building). After making sure the repositories were up to date--namely, according to `git remote -v` and `git log`:

- `https://github.com/llvm/llvm-project.git`: llvm/llvm-project@480391035c730b7b8a58601ef54e0543824ba931
- `https://go.googlesource.com/gollvm`: c1e41505d0c621c29ff9e35fa776699121bc90ab
- `https://go.googlesource.com/gofrontend`: d796680b5a78f686ed118578e81d5b1adf48508d
- `https://github.com/libffi/libffi.git`: libffi/libffi@b844a9c7f1ca792a1dfb0c09d5dae576178e6729
- `https://github.com/ianlancetaylor/libbacktrace.git`: ianlancetaylor/libbacktrace@559ab7cab4a6002124863d493bd09a376a690e76

...the build fails with the following error in [gollvm]/bridge/go-sha1.cpp (not a code block to allow that long CFLAGS line to wrap):

[327/1929] Building CXX object tools/gollvm/bridge/CMakeFiles/LLVMCppGoFrontEnd.dir/go-sha1.cpp.o
FAILED: tools/gollvm/bridge/CMakeFiles/LLVMCppGoFrontEnd.dir/go-sha1.cpp.o 
/usr/bin/c++  -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/gollvm/bridge -I/home/alshamar/llvm-project/llvm/tools/gollvm/bridge -I/usr/include/libxml2 -Iinclude -I/home/alshamar/llvm-project/llvm/include -Itools/gollvm/external/install/include -I/home/alshamar/llvm-project/llvm/tools/gollvm/gofrontend/go -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -g    -fno-exceptions -fno-rtti -std=c++14 -MD -MT tools/gollvm/bridge/CMakeFiles/LLVMCppGoFrontEnd.dir/go-sha1.cpp.o -MF tools/gollvm/bridge/CMakeFiles/LLVMCppGoFrontEnd.dir/go-sha1.cpp.o.d -o tools/gollvm/bridge/CMakeFiles/LLVMCppGoFrontEnd.dir/go-sha1.cpp.o -c /home/alshamar/llvm-project/llvm/tools/gollvm/bridge/go-sha1.cpp
/home/alshamar/llvm-project/llvm/tools/gollvm/bridge/go-sha1.cpp: In member function ‘virtual std::__cxx11::string Llvm_Sha1_Helper::finish()’:
/home/alshamar/llvm-project/llvm/tools/gollvm/bridge/go-sha1.cpp:49:52: error: no matching function for call to ‘std::__cxx11::basic_string<char>::basic_string(llvm::StringRef, int, const int&)’
   std::string result(ctx_->final(), 0, checksum_len);
                                                    ^
In file included from /usr/include/c++/8/string:52,
                 from /home/alshamar/llvm-project/llvm/tools/gollvm/bridge/go-system.h:10,
                 from /home/alshamar/llvm-project/llvm/tools/gollvm/gofrontend/go/go-sha1.h:10,
                 from /home/alshamar/llvm-project/llvm/tools/gollvm/bridge/go-sha1.cpp:12:

(Omitted thereafter is an inane amount of "note: candidate" suggestions.)

Any help getting this build working would be appreciated :)

**Comment by ianlancetaylor** [comment]
CC @cherrymui @thanm

**Comment by Grissess** [comment]
Confirmed that the fix works--thanks!
