### ISSUE TITLE
go/types: what is the new method (*Checker).LookupFieldOrMethod?

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#36916]
On tip, there is a new exported method in go/types: `(*Checker).LookupFieldOrMethod`.  That method was not in 1.13.  The doc comment for this method is (https://tip.golang.org/pkg/go/types/#Checker.LookupFieldOrMethod)

> LookupFieldOrMethod is like the external version but completes interfaces as necessary.

I'm not sure what this means.  What is "the external version?"  I don't think it's the function `LookupFieldOrMethod`, as that just calls this method on a `nil` `*Checker`, so they do the same thing.

I checked to see if the method could be renamed to `lookupFieldOrMethod`, but `Checker` already has a method with that name.

I think this new exported method needs better documentation, and it needs to be mentioned in the release notes.  Or, it needs to be unexported.

The method was added for #6977.

**Comment by dmitshur** [comment]
Since this affects the public API, I understand we should block the rc1 on having a decision on how to resolve this issue. Please let me know if that isn't the case.

**Comment by ianlancetaylor** [comment]
Good point, I agree.

**Comment by griesemer** [comment]
It probably doesn't need to exported - will investigate.
