### ISSUE TITLE
x/tools/gopls: references fails with 'no identifier found'

### ISSUE THREAD

**Issue by stamblerre** [golang/go#36917]
Filing this now so I don't forget, but the repro case won't be great. I was working in `golang.org/x/tools/internal/lsp/cache` package in `golang.org/x/tools/internal/lsp/cache/snapshot.go`. I did find references on a field of snapshot, specifically on `s.ids`. It works fine if you run find references from the definition of the field, but it failed when I called it on a use of the field.

/cc @muirdm

**Comment by muirdm** [comment]
On first attempt I can't reproduce anything like that. `no identifier found` means we didn't find an `*ast.Ident` at the requested position. Maybe you had a syntax error that was messing up the AST, or maybe content was out of sync somehow? Can you reproduce it?

**Comment by stamblerre** [comment]
Ah yes - just realized what it was! It was a map lookup - `s.ids[uri]`.

**Comment by stamblerre** [comment]
The issue seems to exist only on master, not on `gopls/v0.3.0-pre3`.

**Comment by stamblerre** [comment]
I'm so sorry for the bother - it was my own [CL](https://go-review.googlesource.com/c/tools/+/217139) that's causing it. I'll investigate why it's happening.
