### ISSUE TITLE
Golang json unmarshalling underscores

### ISSUE THREAD

**Issue by Iampato** [golang/go#36923]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13.7
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
package main

import (
	"encoding/json"
	"fmt"
)

type User struct {
	UserID string `json:"user_id"`
}

func main() {

	myjson :=  {"user_id":"4567856D-433XFDF454"}
	var x User
	json.Unmarshal([]byte(myjson), &x)

	fmt.Printf("%s\n", myjson)
	fmt.Printf("%s\n", x)
}
```

### What did you expect to see?
userid value <b>NOT</b> being empty string

### What did you see instead?

After unmarshal userid value is empty string

**Comment by mvdan** [comment]
This is [not valid code](https://play.golang.org/p/wMQMEtGZwHJ). Please provide a playground link that actually shows what you mean.

**Comment by Iampato** [comment]
I found the solution `just append backslashes before and after the json` to it try the playground below

https://play.golang.org/p/-evkFkfClax
