### ISSUE TITLE
Issue with type conversion from float64 to string

### ISSUE THREAD

**Issue by neetikh** [golang/go#36922]
GO version- go1.13.1

when converting from float64 to string - GO is changing the value for Odd numbers.

**SAMPLE CODE-**

package main
import (
	"fmt"
	"strconv"
)
func main() {
	var g float64
	g = 12643612166373552
	var ss string
	ss = strconv.FormatFloat(g, 'f', 0, 64)
	fmt.Println(ss)
	
	var g1 float64
	g1 = 12643612166373557
	var ss1 string
	ss1 = strconv.FormatFloat(g1, 'f', 0, 64)
	fmt.Println(ss1)
}

**OUTPUT-** 
12643612166373552
12643612166373556

**EXPECTED OUTPUT-**
12643612166373552
12643612166373557

**Comment by erikdubbelboer** [comment]
That is expected for 64 bit floating point numbers. From [the wiki on 64 bit floats](https://en.wikipedia.org/wiki/Double-precision_floating-point_format#IEEE_754_double-precision_binary_floating-point_format:_binary64):
```
Between 252=4,503,599,627,370,496 and 253=9,007,199,254,740,992 the representable
numbers are exactly the integers. For the next range, from 253 to 254, everything is
multiplied by 2, so the representable numbers are the even ones, etc. Conversely, for
the previous range from 251 to 252, the spacing is 0.5, etc. 
```

**Comment by randall77** [comment]
You can print out the representable float64 numbers in this range. Do at the end of your example:
```
	fmt.Println("\n")
	for i := 0; i < 4; i++ {
		fmt.Println(strconv.FormatFloat(g, 'f', 0, 64))
		g = math.Nextafter(g, 1e100)
```
You'll see that `12643612166373557` is not representable as a float64. It gets rounded to `12643612166373556`.
