### ISSUE TITLE
x/text/language: possible error in the handler example of the package documentation

### ISSUE THREAD

**Issue by palmamartin** [golang/go#36928]
On line [36](https://github.com/golang/text/blob/master/language/doc.go#L36) of the documentation the cookie value is passed using `lang.String()` to `language.MatchStrings` . I assume it should be `lang.Value` instead.

Current documentation:
```go
lang, _ := r.Cookie("lang")
...
tag, _ := language.MatchStrings(matcher, lang.String(), accept)
```
Proposed fix:
```go
lang, _ := r.Cookie("lang")
...
tag, _ := language.MatchStrings(matcher, lang.Value, accept)
```

If my proposed solution is right I can provide CL to fix the documentation.

**Comment by ianlancetaylor** [comment]
CC @mpvl

**Comment by palmamartin** [comment]
I might understand why `lang.String()` is used in the example - due to the fact that there is no error checking when retrieving the cookie. If the cookie does not exists a call to `lang.Value` would result  in a runtime error. Sorry for the noise.
