### ISSUE TITLE
go.dev: add support for bookmarklet to navigate from repository to doc

### ISSUE THREAD

**Issue by ucirello** [golang/go#36929]
### What is the URL of the page with the issue?
https://github.com/golang/tools
 
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
 
 
### Screenshot
 

![image](https://user-images.githubusercontent.com/138827/73552102-790df980-43fc-11ea-83cc-d7edc1934fc6.png)

 
 
 
### What did you do?
 
1. Browse to https://github.com/golang/tools
1. replace the bookmarklet base url from `godoc.org` to `pkg.go.dev`
1. invoke bookmarklet
 
 
### What did you expect to see?
https://pkg.go.dev/github.com/golang/tools
(which is the equivalent of https://godoc.org/github.com/golang/tools)
 
 
### What did you see instead?
The home page with the URL pre-filled in.

**Comment by tonglil** [comment]
This is a big user experience need, as often you start on GitHub and want to navigate to the doc page for more info.

The bookmarklet also works when you are in the tree of the repository, regardless of commit/branch/tag, eg:

https://github.com/hashicorp/vault/tree/master/vault/replication
https://godoc.org/github.com/hashicorp/vault/vault/replication

**Comment by julieqiu** [comment]
Thanks for the feedback! We'll work on this, and I also added it to #39144. 

/cc @fflewddur @Joanne881107

**Comment by AceroM** [comment]
This should now be fixed! You can find more information about the pkg.go.dev bookmarklet at: https://go.dev/about#bookmarklet.

**Comment by tonglil** [comment]
Unfortunately the bookmarklet does not navigate to subdirectories or work when viewing a file.

I have modified it so it does:
```js
javascript:(function(){const pathRegex=window.location.pathname.match(/([^\/]+)(?:\/([^\/]+))?/g);const host=window.location.hostname;if(pathRegex){url='https://pkg.go.dev/'+host+'/'+pathRegex[0];if(pathRegex.length>2){for(var i=2;i<pathRegex.length;i++){if(!pathRegex[i].match(/\.go/)){url+='/'+pathRegex[i]}else if(pathRegex[i].match(/\//)){url+='/'+pathRegex[i].match(/(.*)\//)[1]}}}window.location=url}else{alert('There was an error navigating to pkg.go.dev!')}})();
```
