### ISSUE TITLE
x/website: relative links in blog.golang.org posts 404s when followed from the golang.org homepage

### ISSUE THREAD

**Issue by s-chand** [golang/go#36930]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
I visited the Golang.org web page and got a link to an error page which was referenced as though it was available.

I have attached images

### What did you expect to see?
The reference to Go 2 Here we come to work or atleast not to display an error

### What did you see instead?

I got an lstat error message
![Screenshot 2020-01-31 at 16 41 36](https://user-images.githubusercontent.com/1958765/73552963-6cfc5900-4449-11ea-9406-fcc8754e5e04.png)
![Screenshot 2020-01-31 at 16 41 51](https://user-images.githubusercontent.com/1958765/73553019-843b4680-4449-11ea-908e-56ee12d4b827.png)

**Comment by ALTree** [comment]
Thanks for reporting this.

If you click on that link from the homepage, it goes to golang.org/go2-here-we-come, which 404s, while if you open the blog post (https://blog.golang.org/go1.15-proposals) and then click on the link, it goes to blog.golang.org/go2-here-we-come, which is correct.

cc @toothrot @cagedmantis @dmitshur

**Comment by dmitshur** [comment]
Thanks for the report. When making a [code review suggestion](https://go-review.googlesource.com/c/blog/+/216199/1/content/go1.15-proposals.article#12) in CL 216199, I didn't take it into account that blog posts are embedded directly on golang.org, and thus cannot use relative relative links to other blog.golang.org pages.

I'll send a fix by rolling back [CL 216626](https://golang.org/cl/216626) which implemented my faulty suggestion, and file an issue about catching this potential problem via a test.
