### ISSUE TITLE
x/pkgsite: text can cause overflow on smaller viewports

### ISSUE THREAD

**Issue by ucirello** [golang/go#36935]
### What is the URL of the page with the issue?

https://pkg.go.dev/crypto/tls?tab=doc 
 
 
### What is your user agent?
 
Mozilla/5.0 (Linux; Android 10; Pixel 4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.136 Mobile Safari/537.36 
 
 
### Screenshot
Check the screenshots below

 
 
 
### What did you do?
 
Opened the page from a link sent by someone else.
 
 
 
### What did you expect to see?
 
The perfect filled space that we currently have for godoc.org
![image](https://user-images.githubusercontent.com/138827/73557040-61873e80-4405-11ea-9f2c-ed91f520e08e.png)

 
 
### What did you see instead?
![image](https://user-images.githubusercontent.com/138827/73557008-53392280-4405-11ea-81cf-48eed4606fc8.png)

**Comment by andybons** [comment]
This is because a few pieces of text on https://pkg.go.dev/crypto/tls?tab=doc are causing overflow. Adding `word-break: break-word` to the appropriate CSS styles should solve the issue.

**Comment by julieqiu** [comment]
This issue has been fixed. Closing this issue.
