### ISSUE TITLE
go.dev: rename "pkg" subdomain to "doc"

### ISSUE THREAD

**Issue by icholy** [golang/go#36934]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/

### Problems
 
* Having the first character be "p" makes typing the url difficult.
* It's inconsistent with previous documentation tools `godoc.org`, `go doc`, `godoc`.

### Alternative

https://doc.go.dev/

**Comment by aofei** [comment]
Yup. This "pkg" makes "go.dev" even more ugly, no offensive.

However, I think the best way here is to leave [godoc.org](https://godoc.org) alone. As usual, let it continue to be the favorite online documentation reader for Gophers.

Still hard to believe that the Go team is about to deprecate [godoc.org](https://godoc.org). I can't think of any reason why they would do this. 💔

It would be wonderful if "godoc.org" is owned by the community, I really love this domain. ☹️

**Comment by TapirLiu** [comment]
Is it for `.org` is owned by a private company now, and Google trust self more than another private company? ;D

**Comment by andybons** [comment]
Thanks for the feedback. The domain choice was discussed at length before launch. We feel it’s important to communicate via the domain that this site is much more than just documentation, so doc.go.dev isn’t an appropriate choice.

However, the _domain_ godoc.org isn’t going anywhere. Users will always be able to use it as a mechanism for reaching documentation just like you can now. It will simply be redirecting to documentation served by pkg.go.dev. More info on the redirection is [here](https://blog.golang.org/pkg.go.dev-2020).

Thanks
