### ISSUE TITLE
x/website, x/blog: rewrite relative links as absolute when embedding a blog post

### ISSUE THREAD

**Issue by dmitshur** [golang/go#36944]
Most blog posts use absolute links when pointing to other blog posts or pages on blog.golang.org, but there are some that use relative links, and blog post authors may pick one or the other. When reading blog posts at https://blog.golang.org, both work.

Relative links become broken when embedded directly on the golang.org website, because they start being relative to golang.org rather than the intended blog.golang.org domain.

See #36930 where this happened.

Either the website should rewrite relative links so they are not broken, or if that is too disruptive, then a test should be added that would catch when blog post authors use relative links.

**Comment by seankhliao** [comment]
Doesn't seem relevant anymore as the blog index doesn't embed posts
