### ISSUE TITLE
x/tools/gopls: reduce memory usage

### ISSUE THREAD

**Issue by stamblerre** [golang/go#36943]
This is a general tracking issue for memory usage in `gopls`. We need to collect data and set goals for usage for a given project size. We also need to work towards reducing the memory usage when staticcheck is enabled (though that may be a separate issue).

#### If you have a specific problem with `gopls` using too much memory on your machine, please create a new issue so that we can investigate it separately.  

Please include your editor settings and memory debug information with your issue. These are automatically written to the temporary directory (`/tmp` for Unixes) with names like `gopls.1234-5GiB-withnames.zip`. If you are uncomfortable sharing the package names of your code, you can share the `-nonames` zip instead.

**Comment by mnrce** [comment]
I just upgrade `gopls` to v0.3.0 today so that I'm able to rename symbols / find reference across package, but the memory usage is very high: 
![image](https://user-images.githubusercontent.com/13317164/73721524-08960e00-4757-11ea-9c84-6a7e272306cd.png)

I'm using Ubuntu 16.04

gopls version:

> 
> golang.org/x/tools/gopls v0.3.0
>     golang.org/x/tools/gopls@v0.3.0 h1:l9KKK1/n6CIbfgaUvHBWAvCfOxcl1N+KSOK79OlPIao=

go version:

> go1.13.4 linux/amd64

**Comment by patrikeh** [comment]
As the comment above, I've have had problems with massive memory usage since upgrading to 0.3.0 yesterday, sometimes upward of 12 GB.

<img width="530" alt="Screen Shot 2020-02-04 at 11 29 12 AM" src="https://user-images.githubusercontent.com/11718936/73736748-9d8e0c80-4741-11ea-9e89-3248a0dbca1a.png">

macOS Mojave 10.14.6
go version go1.13 darwin/amd64
golang.org/x/tools/gopls@v0.3.0 h1:l9KKK1/n6CIbfgaUvHBWAvCfOxcl1N+KSOK79OlPIao=

**Comment by guiguan** [comment]
<img width="343" alt="Screen Shot 2020-02-04 at 9 52 18 pm" src="https://user-images.githubusercontent.com/940189/73739011-9397f800-4799-11ea-80c4-05265f64e30e.PNG">

same here. I don't understand why such a good lang has such a shit lang server :(

**Comment by myitcv** [comment]
@guiguan there is absolutely no need for language like that. Please, keep the feedback constructive. 

FWIW this has already been fixed on `master` via https://go-review.googlesource.com/c/tools/+/217677

**Comment by stamblerre** [comment]
I'm sorry that you all encountered this bug - we had a memory leak that was a bit tricky to reproduce, but as @myitcv said, we believe that we've fixed it. You can try it out by downloading the pre-release for the next version of `gopls` (`go get golang.org/x/tools/gopls@v0.3.1-pre1`). Please report here if you still see the excessive memory usage with that version.

**Comment by vincepri** [comment]
@stamblerre On the latest master, gopls is using more than 30GB when developing with some kubernetes sub-projects

**Comment by heschik** [comment]
@vincepri per the bold section in the original issue, please file a new issue with repro instructions, even if they're just "check this repository out and open it."

**Comment by trajber** [comment]
@stamblerre @heschik 

I'm using the latest master and the memory usage is relatively large for a small/medium project. (~1.5GB)
Unfortunately I cannot share the project, but I can send you the pprof heap file for gopls, if it helps :man_shrugging: 

# Build info
```
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.3.1 h1:yNTWrf4gc4Or0UecjOas5pzOa3BL0WDDyKDV4Wz5VaM=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=
    golang.org/x/mod@v0.1.1-0.20191105210325-c90efee705ee h1:WG0RUwxtNT4qqaXX3DPA8zHFNm/D9xaBpxzHt1WcA/E=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20200206141423-2529d2857af7 h1:BtAc3ytYUhbzaL+TpDGZSBVecmz6ra8/VYiIwtasXXc=
    golang.org/x/xerrors@v0.0.0-20191011141410-1b5146add898 h1:/atklqdjdhuosWIl6AIbOeHJjicWYPqR9bpxqxYG2pA=
    honnef.co/go/tools@v0.0.1-2019.2.3 h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=
 ``` 

[Here you can find the pprof heap file](https://github.com/golang/go/files/4165962/pprof.gopls.alloc_objects.alloc_space.inuse_objects.inuse_space.047.pb.gz)

Let me know if you need any more info from my side that can be useful for you.

**Comment by heschik** [comment]
@trajber Unfortunately I don't see any signs of a bug in your profile. That doesn't mean there isn't one, but 1.5GiB is not completely out of line for a project with a lot of dependencies, and without access to the source it's very difficult to judge. Sorry, but I don't think there's going to be much we can do in the short term. Hopefully you will benefit from general optimizations we make in the future.

**Comment by Jacalz** [comment]
When not using a huge monorepo and slowly running out of memory, I usually see `gopls` hanging out at around 800MB to 1GB of memory when browsing smaller repositories.

**Comment by stamblerre** [comment]
@Jacalz: Responded to you on https://github.com/golang/go/issues/37670#issuecomment-614732451, so let's continue the conversation on that issue.

**Comment by heschik** [comment]
I think the commits I pushed today have improved things significantly for large projects. I'll keep looking for a little bit.

**Comment by itzmanish** [comment]
![Screenshot from 2020-06-23 22-15-09](https://user-images.githubusercontent.com/12438068/85431687-7d030980-b59f-11ea-8485-3bb4c888837f.png)

The memory uses not as much users commented before. Not even close but yet giving half a GB is big. However it provides better and fast autocomplete.

**Comment by mangas** [comment]
![image](https://user-images.githubusercontent.com/1640325/86279622-3b431600-bbd2-11ea-9405-be67f10341b4.png)

I just updated to latest and now I have this 🔥

**Comment by heschik** [comment]
From the first comment:

**If you have a specific problem with gopls using too much memory on your machine, please create a new issue so that we can investigate it separately.**

There will be zip files in /tmp with additional memory diagnostic information. Please include one of them. If you are uncomfortable sharing the package names of your code you can pick one with a `-nonames` suffix, otherwise please upload a `-`-withnames` file.

**Comment by stamblerre** [comment]
There have been a number of memory improvements in `gopls` at `master`. Please try out with the instructions on https://github.com/golang/tools/blob/master/gopls/doc/user.md#unstable-versions, or wait for the next release.

**Comment by raghav-clumio** [comment]
@stamblerre just switched to master and it dropped my ram usage from 10 gigs to 1.5gb! Great work guys!
