### ISSUE TITLE
x/build: linux-riscv64-unleashed builder missing

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#36958]
Right now on https://farmer.golang.org/try?commit=c2537a47, a trybot run for https://golang.org/cl/217305, every trybot completed hours ago, except for riscv64.  For that one I see at present

```
linux-riscv64-unleashed rev c2537a47 (trybot set for Ib0a78ee); waiting_for_machine; (nil *buildlet.Client), 4h10m0s ago
  2020-02-01T01:20:53Z checking_for_snapshot 
  2020-02-01T01:20:53Z finish_checking_for_snapshot after 0s
  2020-02-01T01:20:53Z get_buildlet 
 +14999.6s (now)
```

This is too slow for a trybot.

CC @dmitshur @toothrot @bradfitz

**Comment by ianlancetaylor** [comment]
CC @FiloSottile as FYI since it is his CL.

**Comment by FiloSottile** [comment]
FWIW, I explicitly requested the riscv64 builder via [SlowBots](https://github.com/golang/go/wiki/SlowBots), but it looks like it just isn't getting scheduled at all, so that builder might be broken?

**Comment by bradfitz** [comment]
Not running yet. It's almost ready but I got distracted.

**Comment by dmitshur** [comment]
https://farmer.golang.org says:

```
host-linux-riscv64-unleashed: 0/0 (1 missing)
```

/cc @bradfitz as builder owner per https://farmer.golang.org/builders. Are you able to look into this?

**Comment by dmitshur** [comment]
@bradfitz Friendly ping, do you know if you'll be able to look into this, or is there a better person to talk to about the `host-linux-riscv64-unleashed` builder?

**Comment by bradfitz** [comment]
I have negative free time lately with the lockdown & two kids & no child care.

Want to set it up? I gave you root on the box. Search your email for riscv and 2205 (the port number).

**Comment by andybons** [comment]
Sorry, but we (the Go release team) don’t have the time to maintain an additional builder and as you don’t have time to do so either, we will likely remove it from the build dashboard unless another volunteer steps up.

**Comment by dmitshur** [comment]
@bradfitz Thanks for the update, that is understandable.

Also thank you for the offer, but maintaining a builder for the riscv64 architecture is not something I have the bandwidth or interest to do at this time.

**Comment by bradfitz** [comment]
Don't remove it. I'll either find somebody to run it, or I'll do it late one night.

**Comment by 4a6f656c** [comment]
@dmitshur @andybons as a reminder, I've also offered to run a builder for riscv64, however I'm still blocked on https://github.com/golang/go/issues/25498#issuecomment-570783627 (which is also preventing Go from having openbsd/arm and openbsd/arm64 builders)...

**Comment by bradfitz** [comment]
I started the builder the other day but forgot to close this bug.

**Comment by dmitshur** [comment]
Thank you @bradfitz!
