### ISSUE TITLE
x/tools/gopls: orphaned files fallback fails in ad-hoc packages

### ISSUE THREAD

**Issue by stamblerre** [golang/go#36951]
Given the directory structure:

```
a/
└── b
    └── main.go

1 directory, 1 file
```

where `a` is outside of both GOPATH and a module, opening directory `a` will result in no diagnostics for `main.go`. The workspace load will fail because we will only load the top-level directory, but the orphaned file fallback should kick in so this is a bug.

**Comment by Wisgon** [comment]
I got the same error, I found that if I set "go.languageServerExperimentalFeatures" {"diagnostics": false}，everything works fine.
