### ISSUE TITLE
cmd/compile: should accept converting slices of named byte types to strings

### ISSUE THREAD

**Issue by josharian** [golang/go#36965]
```go
package p

type B byte

func f() {
	var x []B
	_ = string(x)
}
```

go/types accepts this code. Go 1.12, 1.13, and 1.14beta1 all reject it with:

```
x.go:7:12: cannot use x (type []B) as type []byte in argument to runtime.slicebytetostring
```

Noticed while looking at #36890.

Easy fix, will plan to do for 1.15.

**Comment by networkimprov** [comment]
Also needs fix for `rune`. Playground said:
```
cannot use r (type []R) as type []rune in argument to runtime.slicerunetostring
```

**Comment by josharian** [comment]
Actually, go/types may be wrong here. From the spec, on conversions:

> A non-constant value x can be converted to type T in any of these cases:
> ...
> x is an integer or a slice of bytes or runes and T is a string type.
> x is a string and T is a slice of bytes or runes.

It doesn’t say that T is a slice whose elements have underlying type byte or rune.

cc @griesemer for spec clarification

cc @ianlancetaylor for gccgo

**Comment by dotaheor** [comment]
dup of https://github.com/golang/go/issues/23536?

**Comment by josharian** [comment]
Yes, it appears so. Unfortunately it doesn’t appear that that issue was brought to a conclusion.
