### ISSUE TITLE
x/blog: broken link on the "Next steps for pkg.go.dev" post

### ISSUE THREAD

**Issue by cespare** [golang/go#36968]
The blog post [Next steps for pkg.go.dev](https://blog.golang.org/pkg.go.dev-2020) has a broken link. The link text is "file an issue on the Go issue tracker" and the destination is https://golang.org/x/discovery-feedback (which is a 404) but it should instead be https://golang.org/s/discovery-feedback.

/cc @julieqiu

**Comment by julieqiu** [comment]
Thanks for letting me know!
