### ISSUE TITLE
wiki: update the Modules page for Go 1.14

### ISSUE THREAD

**Issue by ainar-g** [golang/go#36967]
<p>
<a href="https://github.com/golang/go/wiki/Modules">The <i>Modules</i>
page</a> currently only mentions Go 1.14 as the “finalisation” release:
</p>
<blockquote>
(…)  Modules are an experimental opt-in feature in Go 1.11, with the
plan of incorporating feedback and finalizing the feature for Go 1.14.
(…)
</blockquote>
<p>
But the page doesn't list the changes that were made to the
<code>go</code> command in the <i>Recent Changes</i> section.  It
probably needs to be updated during the Go 1.14 release.
</p>

**Comment by bcmills** [comment]
CC @thepudds @jayconrod @matloob

**Comment by jayconrod** [comment]
Updated introduction, but it will need another update after 1.14 ships so we can list changes and link to the release notes.

Setting myself a calendar reminder to check on that.

**Comment by jayconrod** [comment]
Added highlights from Go 1.14 release notes.
