### ISSUE TITLE
Go mod vendor fails to recognize go.mod changes

### ISSUE THREAD

**Issue by Shukla-Ankur** [golang/go#36978]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
The latest release gives another error-verifyinggo.mod: reading https://sum.golang.org/lookup/repo: 410 Gone

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/name/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/name/Go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f2/vy8173v12hl_yphqzsx2ldmc0000gp/T/go-build425746352=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Created a private repo with a go.mod file
Updated the go.mod file to use a different version of a dependency
Ran ```go clean --modcache```
ran ```go clean -cache```
ran ```export GO111MODULE=on && go mod vendor```

### What did you expect to see?
Code should build properly

### What did you see instead?
go mod pulls the previous version of repo declared in go.mod file

**Comment by agnivade** [comment]
Your issue does not seem like something that needs a private repo. Could you upload a public repo and provide detailed steps to reproduce this ? Could you also try with 1.14beta1 and verify that it fails with it too ?
