### ISSUE TITLE
time: Time.Before() should reuse t.sec() and u.sec()

### ISSUE THREAD

**Issue by geraldss** [golang/go#36987]
Looking at the source code for Time.After() and Time.Before(), Time.After() reuses t.sec() and u.sec(), whereas Time.Before() does not and often calls each method twice.

https://golang.org/src/time/time.go

**Comment by tpaschalis** [comment]
I'm on it, let me wrap up a PR for this.

**Comment by nilsmagnus** [comment]
@tpaschalis are you still looking at this? If not, I would gladly submit a PR :smile:
