### ISSUE TITLE
Readdirnames does not behave according to documentation

### ISSUE THREAD

**Issue by chtisgit** [golang/go#36984]
# What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
This is the latest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/christian/.cache/go-build"
GOENV="/home/christian/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/christian/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build441917012=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Call the Readdirnames method of an os.File with <b>n</b> larger than zero until no more results are available. 
https://play.golang.org/p/CErZEJ9Cp-v

### What did you expect to see?
It is expected to return io.EOF when no more results are available.
The comment of Readdirnames contains this:

> // If n > 0, Readdirnames returns at most n names. In this case, if
> // Readdirnames returns an empty slice, it will return a non-nil error
> // explaining why. At the end of a directory, the error is io.EOF.

### What did you see instead?
It returns an empty slice and a nil error.

**Comment by AlexRouSg** [comment]
`names, e := f.Readdirnames(N)`
`if err != nil {`

You are assigning the error to `e` but checking for `err`

**Comment by chtisgit** [comment]
Thank you, I was not reviewing this carefully enough. Sorry for that.
As the function works with the fix pointed out by @AlexRouSg I'm closing this issue because it is invalid.
