### ISSUE TITLE
go.dev: provide insight into the criteria and selection process behind licenses approved by pkg.go.dev

### ISSUE THREAD

**Issue by mewmew** [golang/go#36983]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/llir/llvm/ir?tab=doc 
 
### What is your user agent?
 

 
 Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0
 
### Screenshot
 

 
![screenshot_2020-02-02_16:24:57](https://user-images.githubusercontent.com/1414531/73610526-9bf50500-45d8-11ea-8a96-60a7cd04924a.png)
 
### What did you do?
 

 
 Try to navigate to the package documentation of [github.com/llir/llvm](https://github.com/llir/llvm) on `pkg.go.dev`.
 
### What did you expect to see?
 
 Similar result to that of GoDoc.org. https://godoc.org/github.com/llir/llvm/ir
 
### What did you see instead?

Nothing. `“Doc” not displayed due to license restrictions.`

### Additional information

Note, this issue is raised in light of the "Next steps for pkg.go.dev" article on the Go blog.

> To minimize confusion about which site to use, later this year we are planning to redirect traffic from godoc.org to the corresponding page on pkg.go.dev. We need your help to ensure that pkg.go.dev addresses all of our users' needs. We encourage everyone to begin using pkg.go.dev today for all of their needs and provide feedback. 

Preventing users from browsing the documentation is definitely a regression. Thus redirecting from godoc.org to pkg.go.dev is not a valid solution, at least not for this project, until the issue with license detection has been resolved.

**Comment by jba** [comment]
The `github.com/llir/llvm` module is licensed under a 0-clause BSD license, which is not on our [list of approved licenses](https://pkg.go.dev/license-policy).

Some approved licenses are extremely close to 0-BSD; you may find that one of them adequately expresses your intent.

**Comment by mewmew** [comment]
Thanks for the feedback Jonathan.

> The github.com/llir/llvm module is licensed under a 0-clause BSD license, which is not on our list of approved licenses.

Indeed, 0-clause BSD is not on the list of approved licenses of `pkg.go.dev`. May I ask what selection process governs which OSI-approved licenses end up on the list of approved `pkg.go.dev` licenses?

Making this transparent may help Go developers have an increased understanding of why the license of their project is or is not recognized.

Asking project maintainers to change the license of their project is a strong thing to do, and warrants insight into the criteria for license approval of `pkg.go.dev`.

> Some approved licenses are extremely close to 0-BSD; you may find that one of them adequately expresses your intent.

I definitely agree with you that there are licenses that are similar to 0-clause BSD on the list, e.g. [ISC](https://opensource.org/licenses/ISC) and [MIT](https://opensource.org/licenses/MIT). None of these licenses express exactly the same as 0-clause BSD though, as they both may be considered 1-clause BSD licenses; in other words, they require that the permission notice appear in all derivative works.

My point is not to argue specifically about 0-clause BSD vs. ISC, MIT, or BSD 2-clause; but rather to express the wish from a Go community member and Go project maintainer for `pkg.go.dev` to provide further insight into the selection process and the criteria for approving the use of an OSI-approved license on `pkg.go.dev`.

With kind regards,
Robin Eklind

**Comment by jba** [comment]
0-BSD is now approved.

I can't discuss our selection criteria in detail here, but we have just widened them considerably.

**Comment by jba** [comment]
We now accept both BSD-0 and Unlicense, and we show README and docs for
your module: https://pkg.go.dev/github.com/llir/llvm.
