### ISSUE TITLE
x/pkgsite: add support for dark mode

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [golang/go#36980]
### What is the URL of the page with the issue?
 All Pages (noticed explicitly on my first use, which was [os.ProcessState.Success](https://pkg.go.dev/os?tab=doc#ProcessState.Success))
 
 
### What is your user agent?
 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0
 
### What did you expect to see?
 Support for my already configured system wide dark mode (via [CSS prefers-colour-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme))

Or at the very least a toggle button somewhere to enable something less eye-searing for those of us working at night or in the dark
 
 
### What did you see instead?
I didnt. I was blinded.

But in all seriousness, a beautifully designed, if bright white docs page. Which instantly clashed with the rest of my system as it is configured to have a dark GTK theme, et al.

On the old godoc.org, I managed this though a stylus theme, but I'd much rather have first party support on pkg.go.dev.

**Comment by julieqiu** [comment]
We're currently discussing this request with our UX team, along with other design feedback we've received for the site. We want to review design feedback we have received as part of a broader redesign, as opposed to make piecemeal decisions. I'll update this issue once we have decided on any changes.

/cc @fflewddur

**Comment by Jacalz** [comment]
This is very much needed. I keep burning my eyes on the white background. We all know the memes about developers using dark themes ;)

**Comment by Fusl** [comment]
This isn't just about "the memes", this is about people suffering from light sensitivity or photophobia.

**Comment by andybons** [comment]
Folks, unless there’s something new to add, please upvote the original comment instead of commenting with support.

Per golang.org/wiki/NoPlusOne.

**Comment by ewen-lbh** [comment]
Here's a set of css rules that switches pkg.go.dev to dark mode, it was pretty quick to make thanks to the use of CSS variables!
Could be used as a starting point or (more likely) for folks who can't wait for this issue to be resolved. Of course it's not perfect (namely I didn't bother to modify the color of purple & turquoise icons with `filter:`s), but it gets the job done:


![image](https://user-images.githubusercontent.com/39094199/119243214-01ba2700-bb65-11eb-94b1-2f7aca27b0fa.png)

I tested it on qutebrowser v2.2.1 (QtWebEngine 5.15.3, Chromium 87.0.4280.144)

Here's the gist: <https://gist.github.com/ewen-lbh/d486b8fd662208d9019cf12b6a47caba>

**Comment by jamalc** [comment]
Dark theme is now live on pkg.go.dev and will change based on the systems preferred color scheme.

**Comment by A-UNDERSCORE-D** [comment]
Looks great!

**Comment by mrg0lden** [comment]
It was working on my machine yesterday, but today it doesn't 🤔

**Comment by jspc** [comment]
Is there any way to toggle it? I'm kinda in the opposite boat- I struggle with contrast, so I have dark mode at the system level so I can make out system menus better, and then use light mode on sites so I can read pages easier.

**Comment by cespare** [comment]
The deprecated tag could use some work in dark mode.

![screen_20210727014546](https://user-images.githubusercontent.com/318501/127124791-c8b4af8a-deec-4b34-8c87-422d451ccce7.png)

**Comment by julieqiu** [comment]
> Is there any way to toggle it? I'm kinda in the opposite boat- I struggle with contrast, so I have dark mode at the system level so I can make out system menus better, and then use light mode on sites so I can read pages easier.

You can press `t` to toggle dark mode. This will be documented (#47421).

> The deprecated tag could use some work in dark mode.

@cespare - since this issue is closed, would you mind [filing a new issue](https://golang.org/s/pkgsite-feedback)?

**Comment by cespare** [comment]
I'll leave it to someone more motivated about dark mode.

**Comment by cameronelliott** [comment]
I accidentally hit 't' (not knowing I had hit 't') and entered the one-way dark-mode. 
Maybe a sun/moon toggle or something so people don't have to clear their cookies would be nice?

**Comment by bombela** [comment]
Press `t` until the setting becomes `auto` again. You can observe the current state by pressing `?`.

**Comment by dmitshur** [comment]
@eliasp Yes, it's still supported and should work.

Scroll to the bottom and look for a sun/moon/halfway icon. Clicking it will toggle between light, dark, and auto modes:

![image](https://user-images.githubusercontent.com/1924134/234161243-ba6e030e-269d-45c4-b759-eebf8d12e539.png)

(The `t` key was used temporary during development and has no effect now.)

If it's still not working or you're seeing some problem, please file a new issue. Thanks.
