### ISSUE TITLE
Android & Golang dependency : Impossible to generate a signed Bundle

### ISSUE THREAD

**Issue by Greelings** [golang/go#36993]
Everything works fine in debug mode. However, it is impossible to generate a signed Bundle with Android Studio. I get the following error:

`File 'root / lib / GOLANG-LICENSE' uses reserved file or directory name 'lib'`

I don't import the golang library directly, it is part of the library (kassensichv) I use.

Any idea where this issue can come from?

**Comment by agnivade** [comment]
Please fill the issue template, so that we can understand how to debug this issue ourselves.
