### ISSUE TITLE
x/tools/gopls: respect GOPRIVATE setting when linking to pkg.go.dev (hover, documentLink)

### ISSUE THREAD

**Issue by stamblerre** [golang/go#36998]
Reported on Slack. We shouldn't over links to packages covered by `GOPRIVATE`.

**Comment by hyangah** [comment]
Just want mention a different use case: organizations that run their internal doc servers would want the linkTarget to point to their doc servers. OTOH, I expect they can easily set up private proxies to avoid depending on GOPRIVATE.

**Comment by stamblerre** [comment]
There's actually one more case where this needs to be handled - https://pkg.go.dev links get generated for import statements through the `textDocument/documentLink` request.

**Comment by heschik** [comment]
I think this is fixed?

**Comment by stamblerre** [comment]
Let's rename the issue to cover the document link case as well.

**Comment by findleyr** [comment]
Yeah, I will get to the documentLink eventually.  Can leave this assigned to me.

**Comment by sandipb** [comment]
Is it an additional bug that all this pkg.go.dev hover and link activity is still going on even when `GO111MODULE` is set to `off` in the environment? Isn't this a Go modules feature?

**Comment by findleyr** [comment]
@sandipb: yes, GOPRIVATE relates to proxy behavior when using modules.  This bug is about hiding links to package documentation when paths match GOPRIVATE.  If paths are private, it's likely that those links will be broken anyway.

But as you say, that only applies to module mode.  Are you saying that if GO111MODULE=off, we shouldn't link to package documentation?  Or are you saying if GO111MODULE=off we shouldn't check GOPRIVATE?  There may be a bug, I'm not sure I understand your question.

**Comment by sandipb** [comment]
Hi @findleyr sorry for the delay in the response.

I meant, if `GO111MODULE=off`, regardless of the value of GOPRIVATE, are links pointing to proxies like pkg.dev expected? I assumed that pkg.dev based hosted docs was part of the module infrastructure.

**Comment by findleyr** [comment]
Hi @sandipb -- both godoc.org and pkg.go.dev host package documentation.  They are not proxies.  Unlike godoc.org, pkg.go.dev is "module-aware", so you can see package documentation for older module versions.

In GOPATH mode, it still seems reasonable to link to package documentation for the package import path.  In any case, if I recall correctly we link to the latest version of documentation, so whether using modules or not the linked package documentation might be for a newer version than what you are importing.

**Comment by stamblerre** [comment]
Agree with everything @findleyr said here, but wanted to add a quick point of clarification on the last statement:

> In any case, if I recall correctly we link to the latest version of documentation, so whether using modules or not the linked package documentation might be for a newer version than what you are importing.

We do link to the correct version of the docs ([code here](https://github.com/golang/tools/blob/master/internal/lsp/source/hover.go#L170)), so if you are using modules, you will get the correct versions.

However, as @findleyr said, even if you are not using modules, these documentation links to https://pkg.go.dev are still useful.

**Comment by sandipb** [comment]
Ack. Thanks, folks, for the clarification.
