### ISSUE TITLE
cmd/go: 'go list' in module mode reports GOPATH Root and Target fields when the main module is in GOPATH/src

### ISSUE THREAD

**Issue by perillo** [golang/go#37015]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14beta1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/manlio/.local/bin"
GOCACHE="/home/manlio/.cache/go-build"
GOENV="/home/manlio/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="github.com/perillo"
GONOSUMDB="github.com/perillo"
GOOS="linux"
GOPATH="/home/manlio/.local/lib/go:/home/manlio/src/go"
GOPRIVATE="github.com/perillo"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/manlio/sdk/go1.14beta1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/manlio/sdk/go1.14beta1/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build892397541=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.14beta1 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.14beta1
uname -sr: Linux 5.5.1-arch1-1
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.30.
gdb --version: GNU gdb (GDB) 8.3.1
</pre></details>

### What did you do?

From inside a module root directory, where `pkg` is a non *main* package.
```
go list -f 'Target: {{ .Target }}, Root: {{ .Root }}' ./pkg
```

### What did you expect to see?

An empty `Target`, since with `GO111MODULE=on` the package archives are no more installed in `$GOPATH`.

### What did you see instead?

```
Target: /home/manlio/src/go/pkg/linux_amd64/github.com/perillo/gocmd/pkglist.a, Root: /home/manlio/src/go
```

NOTE: if it is decided that `Target` will be left empty, I hope that `Root` will remain.

**Comment by bcmills** [comment]
Hmm, interesting.

In a module root outside of `GOPATH`, I get:
```
example.com$ go1.14beta1 list -f '{{.ImportPath}}: {{.Target}} (from {{.Root}})' ./foo
example.com/foo:  (from /tmp/tmp.x68zurPJpH/example.com)
```
And `go install` is a no-op.

However, in a module contained within `GOPATH`, I get:
```
~/src/golang.org/x/mod$ go1.14beta1 list -f '{{.ImportPath}}: {{.Target}} {{.Root}}' ./zip
golang.org/x/mod/zip: /usr/local/google/home/bcmills/pkg/linux_amd64/golang.org/x/mod/zip.a /usr/local/google/home/bcmills

~/src/golang.org/x/mod$ ls ~/pkg/linux_amd64/golang.org/x/mod/zip.a
ls: cannot access '/usr/local/google/home/bcmills/pkg/linux_amd64/golang.org/x/mod/zip.a': No such file or directory

~/src/golang.org/x/mod$ go1.14beta1 install ./zip

~/src/golang.org/x/mod$ ls ~/pkg/linux_amd64/golang.org/x/mod/zip.a
/usr/local/google/home/bcmills/pkg/linux_amd64/golang.org/x/mod/zip.a
```

So it appears that we are still computing (and using) the `GOPATH`-mode `Root` and `Target` even in module mode. I suspect this is related to #34860 and/or #29111.

CC @jayconrod @matloob

**Comment by bcmills** [comment]
The relevant branch seems to be here:
https://github.com/golang/go/blob/c8a91ed24932be7248eefed58ade4bb978b62f55/src/go/build/build.go#L545
https://github.com/golang/go/blob/c8a91ed24932be7248eefed58ade4bb978b62f55/src/go/build/build.go#L592

We probably should not be following the `IsLocalImport` branch in module mode at all.

**Comment by matloob** [comment]
I think we should follow the `IsLocalImport` branch in module mode, but skip the branches that check if the package exists in of the `GOPATH` `src` directories.
