### ISSUE TITLE
x/tools/gopls: create link for release note for each version

### ISSUE THREAD

**Issue by hyangah** [golang/go#37019]
VSCode Go extension detects availability of newer versions of gopls automatically (by querying  `proxy.golang.org`) and suggest upgrade. I want to see the update suggestion message window include the link to the release note. 

Currently #33030 serves as a place for release note announcement which makes sense since `gopls` evolves quickly. I can use the link to the issue but that's rather distracting as more versions are published. Alternatively we can create a short link (encoded with the version tag) for each tagged version and make it point to the corresponding comments. Post v1.0, we can still use the link format to point to the official, formal release note.

**Comment by heschik** [comment]
Perhaps we should just edit the latest minor version's release notes into the top comment.

**Comment by heschik** [comment]
Done. I vote we keep the notes from the most recent minor series at https://github.com/golang/go/issues/33030#issuecomment-510151934, as I've done now.

**Comment by stamblerre** [comment]
Agreed. Closing this issue.
