### ISSUE TITLE
cmd/go: `go build -race -n` produces no output

### ISSUE THREAD

**Issue by dfava** [golang/go#37013]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes; it reproduces on the latest stable release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/danielsf/Library/Caches/go-build"
GOENV="/Users/danielsf/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/danielsf/Dropbox/edu/uio.no/favasynthesis/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.7/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rq/c7265gd14vlc3gzwwn9prm5h0000gn/T/go-build187366826=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Ran `go build -n -race sortnp.go`

### What did you expect to see?

Expected to see build commands printed to stderr or stdout.

### What did you see instead?

Nothing; there was no output and the tool existed with exit status 0.

**Comment by bcmills** [comment]
> ### What did you do?

I'm not able to reproduce this behavior running `go build -n -race sortnp.go` with an arbitrary Go source file. Please provide the exact set of commands you ran (and, ideally, a source file) to reproduce the problem.

**Comment by dfava** [comment]
I first noticed the behavior on a machine that initially had go1.13.5 and was upgraded to go1.13.7 via `go get golang.org/dl/go1.13.7`.  That machine has since been decommissioned and I cannot reproduce the behavior.
