### ISSUE TITLE
proxy.golang.org: not able to install package github.com/denisenkom/go-mssqldb

### ISSUE THREAD

**Issue by yhjhoo** [golang/go#37011]
### What version of Go are you using (`go version`)?
go version go1.13.5 windows/amd64

### Does this issue reproduce with the latest release?
yes

### What did you do?
go get github.com/denisenkom/go-mssqldb

### What did you expect to see?
download go-mssqldb driver

### What did you see instead?
cannot load github.com/denisenkom/go-mssqldb

**Comment by bcmills** [comment]
Please fill out the complete issue template, including `go env`, the exact commands that you ran, and the complete error message you received.
