### ISSUE TITLE
x/build: golang.org/x/xerrors repository isn't on build.golang.org dashboard

### ISSUE THREAD

**Issue by dmitshur** [golang/go#37020]
We need to add post-submit builders for the golang.org/x/xerrors repository.

/cc @golang/osp-team

**Comment by dmitshur** [comment]
This will get resolved as part of #34744, which is something I'm working on now and it should happen over the next few weeks.

If someone wants to solve it independently of #34744 sooner, feel free to leave a comment here.

**Comment by seankhliao** [comment]
the x/xerrors repo is all but abandoned, is this still necessary?

**Comment by dmitshur** [comment]
We solved this during the migration to LUCI, golang.org/x/xerrors has post-submit builders visible on its dashboard (e.g., https://ci.chromium.org/p/golang/g/x-xerrors-gotip/console). It's still not visible on build.golang.org but we don't need to worry about that. Might as well close this since there's nothing actionable left.
