### ISSUE TITLE
x/build: misc-compile-other failed building linux-riscv64 on master

### ISSUE THREAD

**Issue by dmitshur** [golang/go#37022]
The `misc-compile-other` trybot failed on a revert CL in https://go-review.googlesource.com/c/go/+/217721/1#message-9811efced365690ee611f620906e7ecf9b175a15:

```
### Building linux-riscv64
# internal/bytealg
internal/bytealg/indexbyte_riscv64.s:9:1: [riscv64] IndexByte: unknown variable s; offset 0 is b_base+0(FP)
internal/bytealg/indexbyte_riscv64.s:10:1: [riscv64] IndexByte: unknown variable s_len; offset 8 is b_len+8(FP)
internal/bytealg/indexbyte_riscv64.s:32:1: [riscv64] IndexByteString: unknown variable p; offset 0 is s_base+0(FP)
internal/bytealg/indexbyte_riscv64.s:33:1: [riscv64] IndexByteString: unknown variable b_len; offset 8 is s_len+8(FP)
```

_(Source: https://storage.googleapis.com/go-build-log/bd45c843/misc-compile-other_598ce4f1.log.)_

Need to investigate why this happened and where the fix belongs.

/cc @4a6f656c @golang/osp-team

**Comment by bcmills** [comment]
I think we should roll back CL 216758 and turn off the TryBot for 1.14. A port without a passing builder is not “complete”, and the 1.14 release is not supposed to be gated on the RISC-V development work that went in during the freeze.

**Comment by dmitshur** [comment]
This started to happen now because coordinator was redeployed yesterday (see https://github.com/golang/go/issues/36802#issuecomment-581700676), and it picked up the change in x/build/dashboard:

```Go
addMiscCompile("-other", "^(windows-arm|linux-s390x|linux-riscv64|dragonfly-amd64)$")
```

@toothrot is sending a CL to remove that trybot.

**Comment by dmitshur** [comment]
I tested that trybots are passing on master branch by sending an empty [CL 217739](https://golang.org/cl/217739), and they are:

> TryBots are happy.

**Comment by 4a6f656c** [comment]
FTR the failure should be addressed by https://golang.org/cl/217777, which fixed the offset names in internal/bytealg.
