### ISSUE TITLE
go.dev: README font size for code blocks are too large

### ISSUE THREAD

**Issue by fzipp** [golang/go#37025]
The font size for code blocks in the README on the Overview page is exceptionally tall. It's bigger than the headlines. Compare it to the font size for code blocks on the Doc page, which looks
reasonable.

![go dev code block font size - too tall](https://user-images.githubusercontent.com/598327/73785089-ecb25c80-4796-11ea-864f-3e9e0c1ff266.png)

![go dev code block font size - good](https://user-images.githubusercontent.com/598327/73785117-fb990f00-4796-11ea-8877-a99d29e2c39f.png)

**Comment by julieqiu** [comment]
Thanks for the feedback! There is a fix in review for this.

**Comment by julieqiu** [comment]
This is now fixed.

See https://pkg.go.dev/github.com/spf13/viper?tab=overview:
![image](https://user-images.githubusercontent.com/5943521/75707530-01e2b400-5c8d-11ea-9ffb-caa5ccd76588.png)
