### ISSUE TITLE
cmd/go: 'go build -race' with a cross-compiled GOOS should not suggest setting CGO_ENABLED

### ISSUE THREAD

**Issue by MasterDimmy** [golang/go#37021]
<pre>
$ go version
go version go1.13.7 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\8\AppData\Local\go-build
set GOENV=C:\Users\8\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\gopath
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Go\src\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=d:\TEMP\go-build345576314=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

i compile this file for test:
<details>
package main

import (
 "fmt"
)

func main() {
	c := make(chan bool)
	m := make(map[string]string)
	go func() {
		m["1"] = "a" // First conflicting access.
		c <- true
	}()
	m["2"] = "b" // Second conflicting access.
	<-c
	for k, v := range m {
		fmt.Println(k, v)
	}
}
</details>

with

```
set CGO_ENABLED=1
set GOOS=linux
set GO_ARCH=amd64
go build -race
```

### What did you expect to see?

success compile

### What did you see instead?

```
# runtime/cgo
gcc_linux_amd64.c: In function '_cgo_sys_thread_start':
gcc_linux_amd64.c:66:2: error: implicit declaration of function 'sigfillset' [-Werror=implicit-function-declaration]
   66 |  sigfillset(&ign);
      |  ^~~~~~~~~~
cc1.exe: all warnings being treated as errors
```

Note, that
```
set CGO_ENABLED=1
set GOOS=linux
go build 
```
is succecced, but i need to compile with "-race" detector. If CGO_ENABLED=0

```
set CGO_ENABLED=0
set GOOS=linux
go build -race
```

then i got
```
go build: -race requires cgo; enable cgo by setting CGO_ENABLED=1
```

**Comment by bcmills** [comment]
Cross-compiling programs with C dependencies is generally not supported, and the runtime support for `-race` mode relies on C dependencies.

If you want to build a race-enabled binary, you need to either compile for GOOS=windows or build the binary on a Linux machine.

**Comment by bcmills** [comment]
Probably the best we can do here is emit a clearer diagnostic for cross-compiled `-race` builds. (We should not prompt the user to “enable cgo” if we don't have reason to believe that such a build would succeed.)

CC @jayconrod @matloob

**Comment by MasterDimmy** [comment]
just try to cross compile this:
```
package main

import (
"fmt"
)

func main() {
c := make(chan bool)
m := make(map[string]string)
go func() {
m["1"] = "a" // First conflicting access.
c <- true
}()
m["2"] = "b" // Second conflicting access.
<-c
for k, v := range m {
fmt.Println(k, v)
}
}
```

from windows\amd64  to linux\amd64  with gox

**Comment by MasterDimmy** [comment]
I think "'go build -race' with a cross-compiled GOOS should not suggest setting CGO_ENABLED" is not what this issue is for, that is another issue\suggestion.

Current issue is unavailability to crosscompile "-race" with gox.

**Comment by bcmills** [comment]
@MasterDimmy, the fact that `go test -race` has C dependencies is not something we can feasibly fix. (The race detector uses a fairly extensive C library, and the folks on the Go project are not in a position to rewrite it from scratch in pure Go.)

If you want to volunteer to rewrite the race-detector library in pure Go, you're welcome to do so, but as far as “things we can feasibly plan to fix” are concerned, a better error message for this case is about the limit.

**Comment by ChrisSalisbury** [comment]
I think @bcmills was probably intending that anyone with this problem take the rewrite suggestion as an impractical solution and to instead use one of the work-arounds he suggested, but I was curious and found that https://git.llvm.org/git/compiler-rt.git from https://github.com/golang/go/blob/master/src/runtime/race/README is dead (maybe worth a separate issue if anyone has the energy to write it). For anyone else interested, there are some svn links on this page, though: https://github.com/google/sanitizers/wiki/ThreadSanitizerDevelopment

**Comment by keyan** [comment]
@bcmills I took a stab at just modifying the error message in https://github.com/golang/go/pull/38670. I'm just trying getting my feet wet and orient myself in the codebase.

**Comment by ianlancetaylor** [comment]
Wait, I'm not following the suggestion here.  Cross-compiling cgo code works fine if you have a cross-compiler.

We may want a general fix to do better checking of whether you are using a cross-compiler when doing a cross-build that uses cgo.  But that seems separate from the narrow issue of "go build -race", which should work if a cross-compiler is installed.

**Comment by keyan** [comment]
I misunderstood Bryan's comment:

> Cross-compiling programs with C dependencies is generally not supported

If I understand correctly now, the short term move is just to not mention setting CGO_ENABLED because that isn't sufficient on its' own and it is too verbose to explain that you need to have a cross-compiler installed?
