### ISSUE TITLE
doc: id="runtime" appears twice in the 1.14 release notes

### ISSUE THREAD

**Issue by c-yan** [golang/go#37036]
id="runtime" appears twice in the https://github.com/golang/go/blob/master/doc/go1.14.html
This is invalid because the id must be unique throughout the HTML document.
(https://github.com/golang/go/blob/master/doc/go1.13.html has the same problem. ref: https://go-review.googlesource.com/c/go/+/192977)

**Comment by c-yan** [comment]
related: #36878

**Comment by agnivade** [comment]
@dmitshur

**Comment by dmitshur** [comment]
Thanks for letting us know! I'll send a fix.
