### ISSUE TITLE
Internal compiler error when trying to compare two imaginary literals

### ISSUE THREAD

**Issue by cfhay** [golang/go#37051]
Noticed this on play.golang.org with go version 1.13.7

https://play.golang.org/p/tGaOYxdrz2n

This expression causes an internal compiler error:

```go
5i < 7i
```
It should just say "invalid operation: 5i < 7i (operator < not defined on complex numbers)" or similar. The issue doesn't happen when at least one of the arguments is typed (only happens with untyped constants).

**Comment by cuonglm** [comment]
Duplicated of https://github.com/golang/go/issues/32723

**Comment by odeke-em** [comment]
Thank you for this report @cfhay and thank you for the surfacing the duplicate bug!

@cfhay this bug is fixed on Go tip aka the Go1.14* betas, please try out the beta as per https://golang.org/dl/#unstable and report bugs that you encounter!

Thank you!
