### ISSUE TITLE
cmd/go: the `go run` command works with symlinks, but `go test` doesn't like them?

### ISSUE THREAD

**Issue by ORESoftware** [golang/go#37062]
<pre>
$ go version:
go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

I symlink a folder to $GOPATH like so:

```
ln -sf "$HOME/codes/golang/foo"  "$GOPATH/src/channelmeter/foo"

```

I get this warning:

```
warning: ignoring symlink /Users/alex/go/src/channelmeter/foo
```

when I run this:

```
go test -coverprofile out.html all 
```

but when I use `go run` it can handle the symlink.
So it seems like `go test` cannot handle the same symlinks that `go run` can.

**Comment by bcmills** [comment]
> when I use `go run` it can handle the symlink

Please fill out the complete issue template. Specifically, in the “**What did you do?**” section, provide the exact commands you ran and their output.
