### ISSUE TITLE
x/tools/gopls: failures when switching from GOPATH to modules

### ISSUE THREAD

**Issue by stamblerre** [golang/go#37069]
Reported by @tbpg (please correct me if I'm mistaken here).

Repro steps:
1) Open a package that was previously set up to work in GOPATH mode.
2) Initialize a module.
3) There is a missing dependency - add it to the `go.mod`.
4) Errors about the missing dependency do not go away.

**Comment by tbpg** [comment]
The missing dependency was a package within the project.

Kind of like this:

```
.
├── bar
│   └── bar.go
└── foo.go # imported myproject/bar
```

When I opened `foo.go`, there was an error about not being able to find `myproject/bar`. So, I did `go mod init example.com/myproject` then changed the import to `example.com/myproject/bar`.

Then I still got the error that `myproject/bar` was not found (_not_ an error about `example.com/myproject/bar`)

**Comment by stamblerre** [comment]
I am not able to reproduce this when running through the repro steps myself in `gopls`, but I am able to reproduce this in a regression test, which leads me to believe that this is an issue caused by https://github.com/golang/go/issues/40340. Going to close this as a duplicate, but put up a CL with this repro case as a regression test.
