### ISSUE TITLE
x/website: make it safer to make changes to templated HTML pages

### ISSUE THREAD

**Issue by dmitshur** [golang/go#37072]
Right now we rely on https://tip.golang.org (served by the [`golang.org/x/build/cmd/tip`](https://pkg.go.dev/golang.org/x/build/cmd/tip) command), the server that automatically deploys and serves the [latest x/website and Go repository commits](https://tip.golang.org/_tipstatus), for sharing draft release notes such as at https://tip.golang.org/doc/go1.14.

Always showing the latest Go+x/website commits means that changes to the draft release notes are previewed very quickly, which is great for seeing the latest state and for spotting problems very quickly. However, release notes use template processing, and if there is an error in the template, an error is displayed. That makes editing the draft release notes a risky process, which can cause times where draft release notes can't be viewed (see #37070 recently).

We should find a way to make the process safer, but hopefully without negatively affecting the convenience of being able to see the latest commits without manual effort.

/cc @golang/osp-team

**Comment by bcmills** [comment]
> people often rightfully do not run trybots before submitting changes

#37047 is closely related, in that it would also (ideally) detect issues in generated HTML during TryBot runs.

**Comment by bcmills** [comment]
This just bit me on [CL 217877](https://golang.org/cl/217877), too — and it _did_ have a TryBot +1.

I think we really do need to test the rendered templates in some form. (Reopening.)

**Comment by dmitshur** [comment]
The scope of this issue was about the draft release notes, and that's been fixed. I'll revert it to that.

Opened #37090 to track testing improvements for catching problems on pages that still use template mode.
