### ISSUE TITLE
runtime: golang 1.14.rc1 3-5% performance regression from golang 1.13 during protobuf marshalling

### ISSUE THREAD

**Issue by howardjohn** [golang/go#37086]
<pre>
$ go1.14rc1 version
go version go1.14rc1 linux/amd64
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

This is an issue with the latest release

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/local/google/home/howardjohn/.cache/go-build"
GOENV="/usr/local/google/home/howardjohn/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/local/google/home/howardjohn/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/usr/local/google/home/howardjohn/go/src/istio.io/istio/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build462288476=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Ran a benchmark for our application on go 1.13 and go 1.14rc1. performance took about a ~5% hit.

```
$ go test ./pilot/pkg/proxy/envoy/v2/ -bench=BenchmarkEDS -run=^$ -benchmem -benchtime=20s
goos: linux
goarch: amd64
pkg: istio.io/istio/pilot/pkg/proxy/envoy/v2
BenchmarkEDS/100/1-6              264200             90238 ns/op            8964 B/op        361 allocs/op
BenchmarkEDS/1000/1-6              30642            775560 ns/op           62452 B/op       3061 allocs/op
BenchmarkEDS/10000/1-6              3147           6909406 ns/op          604528 B/op      30086 allocs/op
BenchmarkEDS/100/100-6              3217           7292090 ns/op          876827 B/op      35645 allocs/op
BenchmarkEDS/1000/100-6              355          67245095 ns/op         6318974 B/op     307880 allocs/op
BenchmarkEDS/10000/100-6              34         657385493 ns/op        70324914 B/op    3240990 allocs/op
PASS
ok      istio.io/istio/pilot/pkg/proxy/envoy/v2 176.394s
```

```
$ go1.14rc1 test ./pilot/pkg/proxy/envoy/v2/ -bench=BenchmarkEDS -run=^$ -benchmem -benchtime=20s
goos: linux
goarch: amd64
pkg: istio.io/istio/pilot/pkg/proxy/envoy/v2
BenchmarkEDS/100/1-6              246732             97406 ns/op            8964 B/op        361 allocs/op
BenchmarkEDS/1000/1-6              29126            823575 ns/op           62454 B/op       3061 allocs/op
BenchmarkEDS/10000/1-6              3036           7492450 ns/op          604574 B/op      30087 allocs/op
BenchmarkEDS/100/100-6              3120           7801905 ns/op          876848 B/op      35645 allocs/op
BenchmarkEDS/1000/100-6              339          70948842 ns/op         6323512 B/op     307986 allocs/op
BenchmarkEDS/10000/100-6              33         689077376 ns/op        70629433 B/op    3248162 allocs/op
PASS
ok      istio.io/istio/pilot/pkg/proxy/envoy/v2 180.654
```

### What did you expect to see?

Hopefully performance improves or remains constant

### What did you see instead?

Performance decrease

### Additional Info

This benchmark is basically just doing a bunch of protobuf marshalling.

Profile shows 1.14 spends 16% of time on gcBgMarkWorker, but 1.13 only 14.5%.

CPU profiles:
[profiles.tar.gz](https://github.com/golang/go/files/4166487/profiles.tar.gz)

Let me know if there is more info I can provide, I realize these reports typically need a lot of info to track down the root cause. You might/should be able to reproduce by running the same command after checking out the repo at this PR: https://github.com/istio/istio/pull/20899

**Comment by mknyszek** [comment]
@howardjohn Thanks so much for the issue and the detailed information. Looking into it.

**Comment by odeke-em** [comment]
@howardjohn thank you for the report! Just a comment that in the future you can also use benchstat https://godoc.org/golang.org/x/perf/cmd/benchstat for an isolated summary of benchmark results.

**Comment by ianlancetaylor** [comment]
Uses of `runtime.aeshash64` in Go 1.13 should have been replaced by uses of `runtime.memhash64` in Go 1.14.

Oh, I see, this program must be using hash maps with keys of interface types.  See https://golang.org/cl/191198.  Perhaps we should have a release note for that?

**Comment by mknyszek** [comment]
@ianlancetaylor Yeah that's right. @cherrymui and I dug a little deeper and it's actually map with keys of type `reflect.Type` that is causing >70% of the `mapaccess1` calls. :)

**Comment by ianlancetaylor** [comment]
Might be worth adding a special case for pointers in `runtime.typehash`, to call the sized `memhash` function rather than the general one.  For 1.14.1.

**Comment by randall77** [comment]
Certainly we could swap the order of the regular memory check and the `kind` switch, and add a `kindPtr` case.

**Comment by cherrymui** [comment]
I think if regular memory check is true, we could special case 32-bit and 64-bit sizes?

**Comment by SlinSo** [comment]
i am not sure if this is related, but i saw some differences in map access performance, too. In my case I am not using interface{} as a key, but instead a map[int]int

https://github.com/SlinSo/random/blob/master/mapaccess_test.go

pprof excerpt:
go1.13.8:
0.73s  9.53% 82.64%      0.73s  9.53%  runtime.aeshash64

go1.14rc1:
1230ms 15.81% 66.20%     1410ms 18.12%  runtime.memhash64Fallback
140ms  1.80% 97.43%      140ms  1.80%  runtime.memhash64

**Comment by randall77** [comment]
That's a bug. Yikes!
Fix coming.

**Comment by randall77** [comment]
(Unrelated to this issue, though.)

**Comment by thepudds** [comment]
@randall77 is the intent for this to be tracked as a back port candidate? Ian had mentioned in https://github.com/golang/go/issues/37086#issuecomment-583161919 

> Might be worth adding a special case for pointers in runtime.typehash, to call the sized memhash function rather than the general one. For 1.14.1.

**Comment by randall77** [comment]
@gopherbot please open a backport issue.

I don't think this performance regression [qualifies for a backport](https://github.com/golang/go/wiki/MinorReleases), but I'll let the release guys make that call.

**Comment by odeke-em** [comment]
@randall77 oddly it didn't backport for Go1.14.1, it only created PRs for 1.12 and 1.13.

**Comment by dmitshur** [comment]
Made #37613 for 1.14.
