### ISSUE TITLE
x/tools/go/types/typeutil: wrong computed method set

### ISSUE THREAD

**Issue by dotaheor** [golang/go#37081]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.7 linux/amd64
</pre>

### What did you do?

```
package main

import (
	"fmt"
	"go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"log"
	"reflect"
	
	"golang.org/x/tools/go/types/typeutil"
)

const input = `
package abc

type Conn struct {
	frameReader
	PayloadType int
}

type frameReader interface {
	PayloadType() byte
}
`

var fset = token.NewFileSet()

func main() {
	f, err := parser.ParseFile(fset, "hello.go", input, 0)
	if err != nil {
		log.Fatal(err)
	}

	conf := types.Config{Importer: importer.Default()}
	info := &types.Info{Types: make(map[ast.Expr]types.TypeAndValue)}
	pkg, err := conf.Check("cmd/hello", fset, []*ast.File{f}, info)
	if err != nil {
		log.Fatal(err)
	}
	
	ct := pkg.Scope().Lookup("Conn").Type()
	
	var cache typeutil.MethodSetCache
	var methetset = cache.MethodSet(ct)
	fmt.Println(methetset)
		// MethodSet {
		// 	method (cmd/hello.Conn) PayloadType() byte
		// }
	
	fmt.Println(reflect.TypeOf(Conn{}).NumMethod())
		// 0
}

type Conn struct {
	frameReader
	PayloadType int
}

type frameReader interface {
	PayloadType() byte
}
```

### What did you expect to see?

Type `Conn` has no methods.

### What did you see instead?

Type `Conn` has one method.

**Comment by ianlancetaylor** [comment]
But `Conn` does have a method, from the embedded `frameReader` type.  Why should it have no methods?

**Comment by dotaheor** [comment]
But reflect says it hasn't.

**Comment by ianlancetaylor** [comment]
Did you reverse "what did you expect to see" and "what did you see instead"?

Hmmm, looks like you did.  When I run the program, it prints `0` for `NumMethod`.

**Comment by ianlancetaylor** [comment]
Oh, sorry, I get it now.  The method should be hidden by the field of the same name.  The reflect package sees that, but golang.org/x/tools/go/types/typeutil does not.

We appreciate the bug reports, but it will save time if you can say more clearly what the issue is, rather than leaving us to work it out.  Thanks.

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by griesemer** [comment]
Smaller reproducer: https://play.golang.org/p/TRM-fN9nvVd

The primary function `types.LookupFieldOrMethod` correctly reports a field, but `types.NewMethodSet` returns the method. Looks like a bug in the method set computation.

(As an aside, types.NewMethodSet is not directly used by `go/types, so there's no danger of `go/types` directly being compromised by this - it was requested for `x/tools/go/types/typeutil`. I should have said no at that time... :-)
