### ISSUE TITLE
wiki: Go-Release-Cycle has an out of date statement on backporting policy

### ISSUE THREAD

**Issue by dmitshur** [golang/go#37097]
There is a statement in the [Release Maintenance](https://golang.org/wiki/Go-Release-Cycle#release-maintenance) section of the Go Release Cycle wiki page that is out of date:

> Minor releases to address non-security problems for Go 1.x stop once Go 1.x+1 is released.

I plan to edit the page to make it say:

> Minor releases to address non-security problems for Go 1.x stop once Go 1.x+2 is released.

This is because we've accepted a backport policy clarification in proposal #34536, which makes it clear that the last two releases are supported equally.

(Filing this issue before making the change, as documented in the first paragraph of that wiki page.)

/cc @rsc @andybons @cagedmantis @toothrot

**Comment by dmitshur** [comment]
Note that the very next sentence in that section talks about security problems being fixed in the last two releases:

> Minor releases to address non-security problems for Go 1.x stop once Go 1.x+1 is released.
>
> Minor releases to address security problems for Go 1.x stop once Go 1.x+2 is released. For more about security updates, see the [security policy](https://golang.org/security).

So there is also an option to combine the two into something like:

> Minor releases to address non-security and security problems for Go 1.x stop once Go 1.x+2 is released. For more about security updates, see the [security policy](https://golang.org/security).

**Comment by dmitshur** [comment]
This issue has received 2 thumbs up from release team members, and no concerns have been raised. It's small and obvious fix, so it doesn't seem like more discussion is needed.

I'll proceed with making the change.

**Comment by dmitshur** [comment]
Fixed in wiki commit [`e05fa49b`](9ff3369f6ecc15fb42b2cc60fecf748e4b...e05fa49b7665efbbca0004e7425468818648fd13).

**Comment by mvdan** [comment]
I think the text is now repetitive and confusing:

> Minor releases to address non-security problems for Go 1.x stop once Go 1.x+2 is released.
> Minor releases to address security problems for Go 1.x stop once Go 1.x+2 is released.

Why have two almost exact sentences? I had to read them twice to make sure the only difference was security vs non-security. They should be merged, in my opinion.

**Comment by dmitshur** [comment]
@mvdan Do you think the suggested combined phrasing in https://github.com/golang/go/issues/37097#issuecomment-583182330 would work well?

**Comment by mvdan** [comment]
Sure. Though saying "non-security and security" feels a bit weird, like saying "all important and non-important bugs" when one could just say "all bugs".
