### ISSUE TITLE
misc/wasm: On WSL, test code works when served over HTTPS / HTTP/2; not with HTTP 1.1

### ISSUE THREAD

**Issue by Gregory-Ledray** [golang/go#37095]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.13.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes?

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/greg/.cache/go-build"
GOENV="/home/greg/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/greg/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/mnt/c/Users/gledr/Polyapp_Apps/gocode/src/gitlab.com/polyapp-open-source/buggyHTTP/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build313322648=/tmp/go-build -gno-record-gcc-swit
ches"
</pre></details>

### What did you do?
```
package main

import (
	"github.com/rs/cors"
	"net/http"
	"os"
	"runtime"
	"time"
)

func main() {
	mux := http.NewServeMux()
	fs := http.FileServer(http.Dir("./serveThis"))
	mux.Handle("/", fs)
	handler := cors.New(cors.Options{
		AllowCredentials: true,
		AllowedMethods:   []string{"GET", "POST", "PUT"},
		AllowedOrigins:   []string{"https://localhost:*", "http://localhost:*", "*"},
		AllowedHeaders:   []string{"Accept", "Accept-Language", "Accept-Encoding", "Content-Type", "Content-Length", "Authorization"},
		MaxAge:           120,
	}).Handler(mux)
	server := &http.Server{
		Addr:           ":5100",
		Handler:        handler,
		IdleTimeout:    60 * time.Second,
		ReadTimeout:    60 * time.Second,
		WriteTimeout:   60 * time.Second,
		MaxHeaderBytes: 1 << 20,
	}

	var err error

	// working (the errors are expected - it succeeded because it says in the browser:
	// --- FAIL: TestAlwaysFail (0.00s)
	// main_integration_test.go:25: always fail
	tlsPath := ""
	if runtime.GOOS == "windows" {
		tlsPath = os.Getenv("TLSPATH") + "\\\\"
	} else {
		tlsPath = os.Getenv("TLSPATH") + string(os.PathSeparator)
	}
	err = server.ListenAndServeTLS(tlsPath+"server.crt", tlsPath+"server.key")

	// TODO not working
	// error in Firefox: DOMException: "The operation was aborted. "
	// error in Chrome: Failed to load resource: the server responded with a status of 404 (Not Found)
	// next error in Chrome: Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH
	// next error in Chrome: TypeError: Could not download wasm module
	// err = server.ListenAndServe()

	if err != nil {
		panic(err)
	}
}

```
### What did you expect to see?
Explained in the comments, but the file in the repo is a test file compiled to WASM and being loaded into the browser to help me run the tests. I expect it to run the tests, which it does do when using TLS.

### What did you see instead?
When using HTTP 1.1 (aka ListenAndServe, not ListenAndServeTLS) the WASM file fails to load.

### Reproduction Info
You can use the repo here with these instructions: 
```
git clone https://gitlab.com/polyapp-open-source/buggyHTTP
cd buggyHTTP
go build
./buggyHTTP
```
Then open a browser to https://localhost:5100 and see that it works (this is the https version, after all).

Go back and switch which lines are being used to serve the files. Rebuild and serve.

### Notes
* I've seen this happen if I compile in WSL.
* **It does NOT happen if I compile the Go program with Windows**.
* I did a lot of stumbling around to try to solve this problem before realizing the problem was not using TLS / HTTP 2. You can read about that, and instructions on how to build the binary, here: https://github.com/chromedp/chromedp/issues/571

**Comment by agnivade** [comment]
I am unable to reproduce this on Linux. Your included wasm_exec.js was outdated for 1.14, so I used the wasm_exec.html and wasm_exec.js from the 1.14 toolchain and just compiled a simple Hello world binary. Serving those with the main.go in `ListenAndServe` works fine for me.

I see that you mention that it happens in WSL and not in Windows. However, the wasm file should be the same throughout. Is the contents of the wasm file different under different platforms? Does the same binary (built on WSL) work when you run the HTTP server in different platforms?
