### ISSUE TITLE
x/website: https://golang.org/doc/articles/wiki/

### ISSUE THREAD

**Issue by rpoe** [golang/go#37093]
The website https://golang.org/doc/articles/wiki/
uses in the section "Other Tasks" this sentence:
"Spruce up the page templates by making them valid HTML and adding some CSS rules"

This sentence uses a word unknown to google translator.

IMHO. This is a typo.

### Does this issue reproduce with the latest release?
Seen last on 2020-02-06 at 22:00 CET

### What did you do?
View the website.

### What did you expect to see?
"Sprout"

### What did you see instead?
"Spruce"

**Comment by ianlancetaylor** [comment]
"Spruce" is an English word and there is nothing wrong here.

See https://www.merriam-webster.com/dictionary/spruce%20up .
