### ISSUE TITLE
x/website: make it safer to make changes to templated HTML pages

### ISSUE THREAD

**Issue by dmitshur** [golang/go#37090]
Issue #37072 was about making it safer to make changes to draft release notes. But the golang.org website (and in turn, the tip copy at tip.golang.org) still has many pages that use templates.

Right now, if a change introduces an error on one of the templated pages, there isn't a test or trybot that catches that error. We should find a way to automate finding this kind of a problem, otherwise it can lead to broken pages on golang.org (when manually deployed, if the deployment regression tests don't catch it) and tip.golang.org (which is automatically deployed as soon as the CL is submitted).

See [CL 217877](https://golang.org/cl/217877) and [CL 218217](https://golang.org/cl/218217) for a recent occurrence that should ideally be caught in the future.

/cc @bcmills @golang/osp-team

**Comment by jba** [comment]
I  just wrote [templatecheck](https://pkg.go.dev/github.com/jba/templatecheck), a package that validates templates after they are parsed. It might help with this issue.

**Comment by dmitshur** [comment]
The original issue stated:

> Right now, if a change introduces an error on one of the templated pages, there isn't a test or trybot that catches that error.

This is no longer the case today. As documented in `golangorg`'s [README](https://github.com/golang/website/tree/master/cmd/golangorg#testing), x/website now has tests that check various pages for expected status code and content. If a template error is introduced, those tests will fail and will be caught by TryBots, or during deployment (if TryBots were accidentally missed).

Closing as fixed. Thanks to Russ who authored the [`webtest`](https://golang.org/x/website/internal/webtest) package and its integration into deployment.
