### ISSUE TITLE
x/pkgsite: support ` Refresh now` like godoc.org

### ISSUE THREAD

**Issue by yo8** [golang/go#37106]
### What did you do?

View documents on `pkg.go.dev`.

### What did you expect to see?

Latest documents.

### What did you see instead?

Out-of-date documents, even its counterpart on `godoc.org` was updated a few days ago.

**Comment by mewmew** [comment]
Related to #36811

**Comment by julieqiu** [comment]
Thanks for the feedback! We are currently working on a fix for this. Also related is #37002

**Comment by julieqiu** [comment]
This is now supported by visiting `pkg.go.dev/<path>@master`. There is a separate bug to update the UI to make this feature more discoverable (#41278) and support other default branches  (#41312).

**Comment by jxsl13** [comment]
I'm just wondering, why the README is not being updated with the version push like GitHub.com/1234/package@v1.2.0
