### ISSUE TITLE
Fake?

### ISSUE THREAD

**Issue by felipemoz** [golang/go#37109]
Hi guys!

I was discussing with a colleage to adopt Go as API Service to get better performance results.
He has argumented that: "I found a paper, writer by language founders, that do not recommend Go to do this job because there is not a lot of package to support it".

Of course I requested to him to show me the paper or share the link of that. He could not found it.

To me, that is a fake information. 
But anyone have any paper who explain or support this argument?

**Comment by jeremyfaller** [comment]
This is a discussion best held on mailing lists, or forums. It's not really a bug report.

I'd ask at StackOverflow or reddit. Perhaps someone there can help you.

**Comment by ianlancetaylor** [comment]
That said, I don't remember any such paper by the language founders, and if there were such a paper it must have been written many years ago.  Things are different now.
