### ISSUE TITLE
x/pkgsite: show the version when a symbol was added to a package

### ISSUE THREAD

**Issue by ptman** [golang/go#37102]
### What is the URL of the page with the issue?
 
 pkg.go.dev
 
### What did you expect to see?
 
The same info as on e.g. https://golang.org/pkg/context/ about which version introduced changes.

**Comment by julieqiu** [comment]
@ptman do you mean what version of the package, or site version (#36810)?

**Comment by ptman** [comment]
@julieqiu in case of golang.org/pkg/ which only shows stdlib packages, it tells which go release (1.7 introduced context). If you can handle package versions for more than stdlib then that would be a welcome addition.

**Comment by dmitshur** [comment]
For reference, adding this feature to golang.org/pkg for the Go standard library (only) was issue #5778, and it was implemented in [CL 85396](https://golang.org/cl/85396) and [CL 124495](https://golang.org/cl/124495).

**Comment by julieqiu** [comment]
See https://github.com/golang/go/issues/42933 also for additional context.

**Comment by cespare** [comment]
What precisely is a "package version" as mentioned in the issue title?

Is the plan to implement this for the stdlib only, or for third-party code as well?

**Comment by julieqiu** [comment]
@cespare update the title - this issue is for both stdlib and third party packages

**Comment by julieqiu** [comment]
This feature is now live on https://beta.pkg.go.dev! 

You can opt-in to redirect your requests to pkg.go.dev to beta.pkg.go.dev by visiting https://pkg.go.dev/?betaredirect=on.

Here are some screenshots:

**Main page** (https://beta.pkg.go.dev/github.com/lib/pq#ConnectorNoticeHandler)

![image](https://user-images.githubusercontent.com/5943521/114941217-dda25200-9e10-11eb-8162-ebd4d2a4e4d8.png)


**Versions page** (https://beta.pkg.go.dev/github.com/lib/pq?tab=versions)
![image](https://user-images.githubusercontent.com/5943521/114941136-c06d8380-9e10-11eb-81fc-6901844639e6.png)

**Comment by julieqiu** [comment]
This feature is now live for all packages on pkg.go.dev!

If you come across any bugs, please [file an issue](https://golang.org/s/pkgsite-feedback).
