### ISSUE TITLE
x/website: show release dates on downloads page

### ISSUE THREAD

**Issue by myitcv** [golang/go#37105]
Looking through https://golang.org/dl/, it would be nice to be able to see when a Go version was released. Otherwise you have to cross manually cross reference with golang-nuts.

e.g. https://groups.google.com/d/msg/golang-nuts/s8EXcSSJ5cg/bjzWK9DABAAJ

This information might be available elsewhere, but the downloads page would also seem to be a good place to make it available?

**Comment by seankhliao** [comment]
Folding into #40488 which has more activity
