### ISSUE TITLE
cmd/go: `go help get` should show module-get not GOPATH get

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#37103]
<pre>
$ go version
go version go1.14rc1 linux/amd64
</pre>

Running `go help get` prints the help for the GOPATH usage. As modules are now the preferred approach, I think that `go help get` should be changed to produce the current `go help module-get` output and the current page be moved to`go help gopath-get`.

**Comment by jayconrod** [comment]
`go help get` shows either `go help module-get` or `go help gopath-get` depending on whether modules are enabled. So if `GO111MODULE` is `auto` or not set, and you're outside a module, it will show the GOPATH version. I think it's the only command that works that way.

IMO, it's good to be consistent with module mode. Perhaps though we should show a note at the top indicating which version you're looking at?

**Comment by rogpeppe** [comment]
> IMO, it's good to be consistent with module mode. Perhaps though we should show a note at the top indicating which version you're looking at?

I think so... I have to say I was very surprised by the help output being context-dependent. I tend to run `go help` in an arbitrary directory because I thought it didn't matter.

Maybe include a sentence at the top of the help, e.g.

    Module mode is currently enabled so this is the help for the module-aware version of "go get".
    To see the GOPATH version, use "go help gopath-get".

?

**Comment by seankhliao** [comment]
I believe this is done (though the sentence is at the bottom)
