### ISSUE TITLE
go.dev:  Import paths not canonicalized

### ISSUE THREAD

**Issue by devgopkg** [golang/go#37114]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/search?q=devgopkg
 
### What is your user agent?
 
Unimportant 
 
### Screenshot
 
 
<img width="597" alt="Screen Shot 2020-02-07 at 8 47 10 AM" src="https://user-images.githubusercontent.com/60748590/74048199-9ad02900-4986-11ea-8e8a-89061b45438b.png">

 
### What did you do?
 
1. Create repo `github.com/devgopkg/nothere`
2. Rename repo to `github.com/devgopkg/here`
3. Add Go code
4. `go get` original repo name, variations on current name
 
### What did you expect to see?
 
 I expected to see one search result for `github.com/devgopkg/here`.  
 
### What did you see instead?

I saw what is in the screen shot.

I did not expect to see a search result for a path where I never had Go code.  I did not expect paths with case different from the actual repo path.

**Comment by bcmills** [comment]
The canonical import path is defined by the `module` directive in the `go.mod` file. Prior to the introduction of modules, the canonical import path was defined by [`// import` comments](https://golang.org/cmd/go/#hdr-Import_path_checking).

I note that the package you linked has neither a `go.mod` file nor an `// import` comment. If you want to communicate the canonical path to `pkg.go.dev` — or to any other Go user, for that matter! — then you should add one or both of those.
