### ISSUE TITLE
crypto/cipher: NewGCMWithNonceSize allows zero-length nonce

### ISSUE THREAD

**Issue by katiehockman** [golang/go#37118]
`cipher.NewGCMWithNonceSize` allows for any nonce size, including one that is zero length. This is not allowed by NIST SP 800-38D and encrypting with such an IV leaks the authentication key.

[NIST SP 800-38D](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf):

> The bit lengths of the input strings to the authenticated encryption function shall meet the
> following requirements:
> ...
> 1 ≤ len(IV) ≤ 264-1

Allowing a zero-length nonce opens the package up to misuse, and there is never a valid reason to do this. It could be argued that `cipher.NewGCMWithNonceSize` isn't meant to be as safe, and the recommended approach is to use `cipher.NewGCM`, however this is a hardening measure that has no negative side effects, in my opinion.

[cipher.NewGCMWithNonceSize docs](https://pkg.go.dev/crypto/cipher?tab=doc#NewGCMWithNonceSize):

> Only use this function if you require compatibility with an existing cryptosystem that uses non-standard nonce lengths. All other users should use NewGCM, which is faster and more resistant to misuse.

/cc @FiloSottile

**Comment by katiehockman** [comment]
@FiloSottile suggested that we backport this fix as well.

**Comment by networkimprov** [comment]
@gopherbot please open backport, at suggestion of @FiloSottile.

**Comment by networkimprov** [comment]
@dmitshur, also needs 1.14 backport...

**Comment by dmitshur** [comment]
I'll repurpose the 1.12 one. It won't be getting this backport.

**Comment by networkimprov** [comment]
Backport issue for 1.12 is now #37418
