### ISSUE TITLE
Mongo connection string working in Mongo CLI but not in Go

### ISSUE THREAD

**Issue by zampetti** [golang/go#37124]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.13

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output: GO111MODULE=""
GOARCH="amd64"
GOBIN="/go/bin"
GOCACHE="/Users/<last name>/Library/Caches/go-build"
GOENV="/Users/<last name>/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/<last name>"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/users/<last name>/mpp-api/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gw/5pn51zl11g516c17wkkjyxq40000gn/T/go-build995863659=/tmp/go-build -gno-record-gcc-switches -fno-common"</summary><br><pre>
$ go env
</pre></details>

### What did you do?
I restarted my computer and now my mongo connection string, which had been working, no longer works. The error I receive is: `unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.` When I use the exact same connection string in the Mongo CLI, it works as expected.

### What did you expect to see?
I expected to get a functioning mongo Client:
```
//Set mongo client options
clientOptions := options.Client().ApplyURI("mongodb://" + env.MongoDBCnn.User + ":" + env.MongoDBCnn.Pw + "@" + env.MongoDBCnn.Host + ":" + env.MongoDBCnn.Port + "/?authSource=" + env.MongoDBCnn.Name)

//Create mongo client
client, err := mongo.Connect(context.TODO(), clientOptions)

```

### What did you see instead?
Authentication errors, despite the fact that the user and password I'm using are confirmed to be correct by logging in to the Mongo CLI

**Comment by AlexRouSg** [comment]
This report sounds like a issue with the mongo driver/package. Please report it to https://jira.mongodb.org/browse/GODRIVER or which ever mongo package you are using.

If instead you are asking for help, please read https://github.com/golang/go/wiki/Questions
