### ISSUE TITLE
cmd/go: credentials from .netrc are not applied to URLs containing an explicit port

### ISSUE THREAD

**Issue by dhowden** [golang/go#37130]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Run a go mod proxy on a custom port (i.e. https://myproxy.mydomain.com:4433).

Setup .netrc:

```
machine myproxy.mydomain.com
  login username
  password secret
```

Note: the .netrc spec defines the `machine` property as the `machine name`: https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html.

Set `GOPROXY` env variable:

```
export GOPROXY="myproxy.mydomain.com:4433"
```

### What did you expect to see?

Auth credentials passed in proxy requests.

### What did you see instead?

No auth credentials passed in proxy requests.

### Work around

Note: it is possible to get around this by adding the port to the `machine name` property in the .netrc file.

```
machine myproxy.mydomain.com:4433
  login username
  password secret
```

CC: @bcmills

**Comment by marwan-at-work** [comment]
Hi there :wave: 

Just FYI this is a bit of a breaking change. 

Using Go 1.14.4, all `machine` values must have a PORT associated and the lack of PORT would cause Go to not forward credentials. 

But using the latest Go build from master, the behavior is totally reversed. 

Therefore, a Proxy maintainer must tell their users to set _both_ a machine with a port _and_ a machine without a port in their `.netrc` file just to make sure we cover our bases with whatever Go version they have. 

CC: @bcmills

**Comment by jayconrod** [comment]
I think the 1.14 behavior was buggy, and the 1.15 behavior is correct, so let's not change this further.

The [netrc spec](https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html) (such as it is) doesn't say anything about ports. My assumption is that the machine name is supposed to be just a host name without a port.

That seems to be consistent with curl's behavior. Given a netrc file, curl won't match entries with a port as part of a machine name. It will match entries without a port when the destination has a port.
