### ISSUE TITLE
x/pkgsite: use pkg.go.dev as source to determine impacts of breaking changes

### ISSUE THREAD

**Issue by sylr** [golang/go#37135]
Although it seems `pkg.go.dev` [does not provide API](https://github.com/golang/go/issues/36785) for the moment it is something currently discussed according to https://blog.golang.org/pkg.go.dev-2020.

One feature of `pkg.go.dev` is to track who imports what and that could be useful to determine the consequences of modifying public structs and methods.

If `pkg.go.dev` could provide an API to list packages which import specified packages, a tool could be written to assert the magnitude of the disruption a series of git commits in a project would provoke in the go eco-system.

Such tool could be part of the go mod toolchain, e.g.:

```shell
$ go mod what origin/master..HEAD
Changes from origin/master to HEAD modified following exported signatures:
  github.com/org/go-lib/pkg/pkg1.New(...) (modified)
  github.com/org/go-lib/pkg/pkg2.NewWithContext(...) (deleted)
  github.com/org/go-lib/pkg/pkg2.Struct{...} (modified)
These changes would impact:
  github.com/big-corp/oss-project/pkg/pkg1
  github.com/oss-org/oss-project/v2/pkg/pkg3
```

Thoughts ?

**Comment by beoran** [comment]
This is not a bad idea to asses the status of open source Go code, but let's keep in mind the millions of lines of closed source code in corporations all over the world. It would cause quite a few problems for closed source Go code if a breaking change was made to Go or the standard library just because it doesn't cause problems in open source Go code.

**Comment by sylr** [comment]
Yes you’re absolutely right.

Nonetheless the opensource side of things would already give a good assessment of what would happen.

Also if pkg.go.dev were to be open sourced, this tool could benefit corporations which would have deployed their own instance. That could a great value for a dev to know what his changes in an internal projet would means in the entire go source code of his enterprise.

Also I see this tool as a mean to sensibilise people to adopt the go module versioning by giving them the implications of not releasing new major versions of their lib when breaking changes happen.

**Comment by bcmills** [comment]
CC @jayconrod @jba

**Comment by dmitshur** [comment]
Also /cc @julieqiu per [owners](https://dev.golang.org/owners).

**Comment by seankhliao** [comment]
i think until there's an api, any usage seems speculative.
