### ISSUE TITLE
PowerRegisterSuspendResumeNotification error on Azure App Services with go 1.13.7

### ISSUE THREAD

**Issue by kpfaulkner** [golang/go#37149]
### What version of Go are you using (`go version`)?

<pre>
Go version 1.13.7 (also with 1.13.6/5/4.. )   but works with 1.13
</pre>

### Does this issue reproduce with the latest release?

1.13.7 yes

Believe this might be related to issue 35447

### What operating system and processor architecture are you using (`go env`)?

Note, building is fine (details below are just from the compile machine). It's on Azure App Services where the error happens (runtime).

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
C:\Users\kenfa\projects\gorepo> go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\kenfa\AppData\Local\go-build
set GOENV=C:\Users\kenfa\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\kenfa\projects\gopath
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\users\kenfa\packages\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\users\kenfa\packages\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\kenfa\AppData\Local\Temp\go-build929673298=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
Running a binary (windows executable) in an Azure App Service generates the stack trace:

A simple repro can be achieved with:

package main

import "fmt"

func main() {
  fmt.Printf("hello world\n")
}

### What did you expect to see?

hello world

### What did you see instead?

runtime: PowerRegisterSuspendResumeNotification failed with errno= 5
fatal error: runtime: PowerRegisterSuspendResumeNotification failure

runtime stack:
runtime.throw(0x4dbc9c, 0x37)
	c:/users/kenfa/packages/go/src/runtime/panic.go:774 +0x79 fp=0x82fdd8 sp=0x82fda8 pc=0x42cf09
runtime.monitorSuspendResume()
	c:/users/kenfa/packages/go/src/runtime/os_windows.go:307 +0x20a fp=0x82fe80 sp=0x82fdd8 pc=0x42992a
runtime.goenvs()
	c:/users/kenfa/packages/go/src/runtime/os_windows.go:544 +0x1ba fp=0x82fed8 sp=0x82fe80 pc=0x42a2aa
runtime.schedinit()
	c:/users/kenfa/packages/go/src/runtime/proc.go:554 +0xa9 fp=0x82ff30 sp=0x82fed8 pc=0x42f8f9
runtime.rt0_go(0x82ff60, 0x7fff2bc184d4, 0x82ff60, 0x0, 0x7fff2bc184d4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	c:/users/kenfa/packages/go/src/runtime/asm_amd64.s:214 +0x13d fp=0x82ff38 sp=0x82ff30 pc=0x452e5d

**Comment by networkimprov** [comment]
@kpfaulkner, what are specifics of Azure App Services config?

This has appeared before in #35447 and #36557.

@gopherbot add OS-Windows release-blocker
cc @zx2c4 @aclements @ianlancetaylor

**Comment by networkimprov** [comment]
@gopherbot add OS-Windows
@gopherbot add release-blocker

**Comment by kpfaulkner** [comment]
@networkimprov In this case I simply made a free tier app service plan via the Azure Portal and made an empty app service within that.   I can make up a set of powershell/az commands to do the same if it helps, but if using the UI it's literally app service plan -> windows -> <tier of your choice>

The quickest way to deploy in this case is just drag/drop the go-built exe file via the SCM web interface. I can provide screen shots with literal step-by-step if it helps.

**Comment by zx2c4** [comment]
I'm pretty sure my original fix for this issue rather than the whack a mole as was requested by interlocuteurs is preferable.

If you want a hybrid, warn on new error codes, but don't bring down the entire runtime. The Linux kernel in recent years has adopted this policy too, preferring WARN_ON to BUG_ON.

**Comment by networkimprov** [comment]
Prob should be milestoned to 1.14.

**Comment by networkimprov** [comment]
@gopherbot please backport. It's another instance of this regression...

**Comment by alexbrainman** [comment]
@kpfaulkner please see, if you can test this change

https://golang.org/cl/219657

> I'm pretty sure my original fix for this issue rather than the whack a mole as was requested by interlocuteurs is preferable.

I agree. My approach did not work.

Alex

**Comment by dmitshur** [comment]
Friendly ping @kpfaulkner. Did you see the message @alexbrainman has posted above? Are you able to test [CL 219657](https://golang.org/cl/219657) and let us know if it fixes this issue for you? Thanks.

**Comment by kpfaulkner** [comment]
Ah, didn't see that. Currently traveling. Will look at that in the next few days.
