### ISSUE TITLE
Template URL escape

### ISSUE THREAD

**Issue by bajro17** [golang/go#37154]
I have problem with escaping URL in my template. I using GORM and have type Tag struct with field URL I pass this to template but template escape url. I also see before is available to use | unescape pipe but this dont exist anymore? 

### What version of Go are you using (`go version`)?

<pre>
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?

I want see literal URL 

### What did you see instead?
escaped URL

**Comment by mvdan** [comment]
You didn't fill the template completely. Also, remember that the Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
