### ISSUE TITLE
x/tools/internal/lsp: client won't receive replies after cancelled request

### ISSUE THREAD

**Issue by leitzler** [golang/go#37159]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 darwin/amd64
github.com/golang/tools@61798d64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
As a part of adding the LSP `DocumentHighlight` feature to `govim` I noticed that it sometimes hangs when I use it in medium sized projects.

In `govim` we vendor the internal lsp files from golang.org/x/tools and use them to communicate with `gopls`.

In the logs I see that govim successfully sends a `$cancelRequest` to `gopls`, and gets a response. But the request after (in this case a `CodeAction`) never returns.

When dumping the goroutines in `govim` I saw that requesting goroutine was waiting for a response on `rchan` at https://github.com/golang/tools/blob/1ace956b0e17ff85a6f9bdf6973af28a26234113/internal/jsonrpc2/jsonrpc2.go#L175.

It's a bit tricky to reproduce with my `govim` branch, so I created a quick hack in a forked version of tools, https://github.com/leitzler/tools/tree/cancel-hang-repro/repro.
There are two flags for the repro, `-gopls` that specifies `gopls` binary path, and `-cancel-delay` that specifies a delay in `ns` before the `DocumentHighlight` request is cancelled. Default it is 1000ns, which seems to work fine on my machine, but must probably be changed to reproduce the issue.
Too short and the client will cancel the request before it's even sent, too long and gopls will respond before the cancel occurs.

Note that according to gopls logs, it looks like the response is sent, but it never seems to reach the client.

The repro isn't beautiful but seems to work and, per discussion on Slack with @findleyr, probably enough to pinpoint the problem.

### What did you expect to see?
Requests processed as usual after a cancel.

### What did you see instead?
The client hangs.

**Comment by myitcv** [comment]
cc @stamblerre @findleyr

**Comment by findleyr** [comment]
@leitzler huge thanks for that repro! After debugging your program I was able to reproduce in a gopls test.
