### ISSUE TITLE
x/crypto/chacha20: panic with valid counter value

### ISSUE THREAD

**Issue by rod-hynes** [golang/go#37157]
### What version of Go are you using (`go version`)?

Go 1.13.7

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

darwin/amd64

### What did you do?

Ran the following test, which reproduces the panic.

Note that this test uses the pending CL https://github.com/golang/crypto/pull/108, which adds the SetCounter method to x/crypto/chacha20. While the panic on the last valid counter value, 2^32-1, is present in the current x/crypto/chacha20, it's unlikley to be hit in typical use as the counter value cannot be set and always starts at 0.

```
func TestIETFQUICHeaderProtection(t *testing.T) {
	var key [32]byte
	var nonce [12]byte
	var block [64]byte
	c, _ := NewUnauthenticatedCipher(key[:], nonce[:])
	c.SetCounter(0xffffffff)
	c.XORKeyStream(block[:], block[:])
}
```

Background:

IETF ChaCha20 allows 2^32 blocks: https://tools.ietf.org/html/rfc7539#section-2.3.2.

IETF QUIC ChaCha20-based header protection, https://tools.ietf.org/html/draft-ietf-quic-tls-24#section-5.4.4, initializes the ChaCha20 counter with "4 bytes of [...] sampled ciphertext", so it's possible to have any counter value in [0, 2^32-1] and attempt to encrypt one block.

We hit this panic in production while using https://github.com/lucas-clemente/quic-go, which uses a recent fork of x/crypto/internal/chacha20 that exposes a function to set the counter value.

Related issue: https://github.com/lucas-clemente/quic-go/issues/2326.

### What did you expect to see?

Successful test run.

### What did you see instead?

```
=== RUN   TestIETFQUICHeaderProtection
--- FAIL: TestIETFQUICHeaderProtection (0.00s)
panic: chacha20: counter overflow [recovered]
	panic: chacha20: counter overflow

goroutine 7 [running]:
testing.tRunner.func1(0xc000094100)
	/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x1117dc0, 0x1187e60)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
golang.org/x/crypto/chacha20.(*Cipher).XORKeyStream(0xc000034eb0, 0xc000034e70, 0x40, 0x40, 0xc000034e70, 0x40, 0x40)
	/Users/Work/Code/gopath/src/github.com/lukechampine/crypto/chacha20/chacha_generic.go:206 +0x393
golang.org/x/crypto/chacha20.TestIETFQUICHeaderProtection(0xc000094100)
	/Users/Work/Code/gopath/src/github.com/lukechampine/crypto/chacha20/chacha_test.go:32 +0x161
testing.tRunner(0xc000094100, 0x1169418)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
exit status 2
FAIL	golang.org/x/crypto/chacha20	0.322s
```

Here is a fix implemented by @lukechampine: https://github.com/lukechampine/crypto/commit/d3e589b4e01df3bbbbfde424de7fcc0b607f6636 (briefly discussed here: https://github.com/golang/crypto/pull/108#issuecomment-579802871).

**Comment by MaxSem** [comment]
CC @FiloSottile
