### ISSUE TITLE
x/tools/gopls: Load concurrency error reported to LSP client

### ISSUE THREAD

**Issue by myitcv** [golang/go#37164]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +b7689f5aa3 Fri Jan 31 06:02:00 2020 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20200207224406-61798d64f025
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.1.8-0.20200207224406-61798d64f025
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build541509370=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

This is a follow up to https://github.com/golang/go/issues/36772#issuecomment-579410518

In https://github.com/golang/go/issues/36772 we encountered a number of errors, one of which was caused by two runs of `cmd/go` resulting in racey reads/writes to `go.mod`.

This is a followup issue to record a further error we are seeing be reported:

```
Params: {"type":1,"message":"2020/02/11 06:58:10 Load concurrency error, will retry serially: go [list -f {{context.GOARCH}} {{context.Compiler}} -- unsafe]: exit status 1: go: updates to go.mod needed, but contents have changed\n"}
```

`gopls` log file: [gopls.log](https://github.com/golang/go/files/4185049/gopls.log)

### What did you expect to see?

No error level log message; `gopls` did not fail here.

### What did you see instead?

Per above.

---

cc @stamblerre @heschik 

FYI @leitzler

**Comment by stamblerre** [comment]
@heschik: I'll leave it up to you to decide what you want to log here. It seems fine to me to log an error, so I'm not sure that this requires a change.

**Comment by heschik** [comment]
I would be happy to make it a warning but we don't have those yet.

**Comment by myitcv** [comment]
My understanding of an error being logged from server to client is that the client/user should do something with that error, i.e. investigate/report it. Hence why I'm pushing to try and eliminate all errors that are not actually errors, as well as having generic assertions in tests that verify we haven't seen any errors in the course of normal behaviour. However, if this understanding is wrong, please correct me!

> It seems fine to me to log an error

Is `gopls` able to recover from this situation? 

If it can, then I don't think this should be reported as an error. 

If it can't, what are we expecting the client/user to do with the error? 

cc @findleyr given discussions about `govim` tests.

**Comment by stamblerre** [comment]
> My understanding of an error being logged from server to client is that the client/user should do something with that error, i.e. investigate/report it.

I'm not sure that I agree. To me, there is a distinction between a logged message (`window/logMessage`) versus a shown message (`window/showMessage`), and the client should only worry about messages that we show the user.

> Is `gopls` able to recover from this situation?
> If it can, then I don't think this should be reported as an error.

If `gopls` can't recover from an error, I think that we should show an error to the user and shut down the server. Having errors in the log helps us with troubleshooting and distinguishes informational messages from genuine error reports. We can aim to decrease the number of logged error messages, but I don't think that we can ever guarantee that zero error messages will be logged. In this case, an error has occurred and we log to indicate that we are attempting to recover from it.

I'm going to go ahead and close this issue. Please re-open if you have further thoughts, but I don't think it's incorrect for us to log the error here.

**Comment by leitzler** [comment]
What I would expect, and I could be totally wrong, is that a log message that tells me:
> Failed to xyz, will retry automatically

Is, at most, a warning. As opposite to:
> Failed to xyz, won't retry (max retries exceeded for example)

That is an error.

The `logMessage` intention is to tell the client to log something, and if the log did contain a lot of errors that I as a user was meant to ignore, then I'd stop looking at the log. In my experience severities are a nice way to get the users attention. A retry isn't something that always needs my attention if it succeeds the second time.

I'm not saying that we should re-open the issue, just wanted to share my thoughts.

**Comment by stamblerre** [comment]
I agree that this particular error message could probably be a warning. I've updated https://github.com/golang/go/issues/36880 to reflect that we should support warnings in logs. I just want to discourage relying on the contents of `gopls` logs for tests.
