### ISSUE TITLE
crypto/x509: parse additional fields in CertificateRequest

### ISSUE THREAD

**Issue by chauncyc** [golang/go#37172]
### What version of Go are you using (`go version`)?

<pre>
$ 1.13.4

</pre>

`ParseCertificate` parses many common extensions and puts them in the `Certificate` struct. I'd like for `ParseCertificateRequest` to do the same. Specifically, I currently manually parse the following fields from `CertificateRequest.Extensions`, and would like for them to be added to `CertificateRequest`, with the corresponding changes to `ParseCertificateRequest` and `CreateCertificateRequest`, exactly as they're implemented for `Certificate`:

- KeyUsage
- ExtKeyUsage
- UnknownExtKeyUsage
- IsCA
- MaxPathLen
- BasicConstraintsValid
- MaxPathLenZero
- SubjectKeyId
- PolicyIdentifier

**Comment by FiloSottile** [comment]
Sounds good, we should even be able to share code with the Certificate parser.

**Comment by rsc** [comment]
Adding to proposal minutes, seems headed for likely accept.

**Comment by rsc** [comment]
Based on the discussion above this seems like a **likely accept**.

**Comment by rsc** [comment]
No change in consensus, so accepted.

**Comment by FiloSottile** [comment]
Did not happen for Go 1.15.
