### ISSUE TITLE
cmd/go: unused function addModFlag in internal/modcmd/mod.go

### ISSUE THREAD

**Issue by perillo** [golang/go#37189]
In `internal/modcmd/mod.go` there is a function `addModFlags` that is never used:

```
func addModFlags(cmd *base.Command) {
        cmd.Flag.StringVar(&cfg.ModFile, "modfile", "", "")
}
```

The flag is set in the `internal.work.AddModCommonFlags` function, so it was probably not removed in https://golang.org/cl/202564.

**Comment by jayconrod** [comment]
Thanks. CL 219197 will remove this.

**Comment by perillo** [comment]
Thanks.

By the way; I find it unusual that no tool reported this problem.  Non even `staticcheck -unused.whole-program` .
