### ISSUE TITLE
x/pkgsite: README relative image links are broken

### ISSUE THREAD

**Issue by kindermoumoute** [golang/go#37194]
In tab `overview` all relative urls from the `README.md` are correctly replaced to absolute urls using GitHub's base url. This should be done as well for relative image path. 

### What did you do?
Go to https://pkg.go.dev/github.com/scaleway/scaleway-sdk-go?tab=overview

### What did you expect to see?
Image rendering correctly

### What did you see instead?
Broken image link

**Comment by jba** [comment]
The problem here is that the `img` link is in HTML, not Markdown. We currently traverse the markdown, but not the HTML embedded within it.

**Comment by jamalc** [comment]
@kindermoumoute - this should now be fixed.
