### ISSUE TITLE
Testing: console output and json file print out at the same time?

### ISSUE THREAD

**Issue by qzhao17** [golang/go#37204]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.13.5
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
</pre></details>

### What did you do?
go test -v -json > gotest.json

### What did you expect to see?
I am looking for a way to print out on the console and generate the json file at the same time.

### What did you see instead?
only json file without console output

**Comment by networkimprov** [comment]
See unix `tee` command.

**Comment by muirdm** [comment]
This looks like a general programming question, not a Go issue. See https://github.com/golang/go/wiki/Questions.

> I am looking for a way to print out on the console and generate the json file at the same time.

Since test output goes to stdout, you can separate your console output using stderr, e.g. `fmt.Fprintln(os.Stderr, "my console output")`.

**Comment by qzhao17** [comment]
🤔For example, if using 'go test -v -json > gotest.json test_folder_name'. The whole test output will be stored in gotest.json. 
if using 'go test test_folder_name', it will print out some following information.
?   	github.com/script/local	[no test files]
ok  	github.com/script/inputfilters	(cached)

I am looking for a way to keep both. Any thoughts on it?

**Comment by networkimprov** [comment]
Post your Q on golang-nuts mailing list.

**Comment by qzhao17** [comment]
Suggestion from Gohphers slack:
Step 1. `go test -json test_folder_name | tee gotest.json`
Step2.  pipe the output file into tools like `jq`, `awk` to prettify
