### ISSUE TITLE
cmd/vet: warn about more malformed JSON struct tags

### ISSUE THREAD

**Issue by pfwgbe** [golang/go#37210]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, the problem appears with 1.13.8 as well.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/XYZ/Library/Caches/go-build"
GOENV="/Users/XYZ/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB="example.com/*"
GOOS="darwin"
GOPATH="/Users/XYZ/go"
GOPRIVATE=""
GOPROXY="http://proxy.example.com"
GOROOT="/Users/XYZ/go/go1.13.4"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/XYZ/go/go1.13.4/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fm/6cbjfz6s33qbxn77r5lt89cc0000gp/T/go-build495195143=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I ran `go vet` on the following code:
```go
package main

import (
	"fmt"
	"encoding/json"
)

type S struct {
	Foo int `json:"fnord.foo"`
}

func main() {
	data := []byte(`
		{
			"fnord": {
				"foo": 1
			}
		}
	`)

	var s S
	err := json.Unmarshal(data, &s)
	if err != nil {
		panic(err)
	}
	fmt.Printf("%#v\n", s)
}
```

### What did you expect to see?
I expected `go vet` to warn me about the undecodable parts of the struct, with something like "`encoding/json` does not support dot-separated paths"

### What did you see instead?
`go vet` did not print any output and had a zero exit value, indicating that there are no problems with the code.

**Comment by josharian** [comment]
Seems reasonable. Should fit nicely into the existing vet struct tags check. Should be pretty straightforward to implement for anyone wanting to try their hand on vet.

cc @mvdan @robpike

**Comment by seankhliao** [comment]
I don't think this is something that can be flagged,
`{"fnord.foo": 1}` is a valid json object that is supported by the current syntax https://go.dev/play/p/faEAfGx8uzE

cc @mvdan

**Comment by mvdan** [comment]
I tend to agree with @seankhliao, and we likely can't change the existing behavior either. Also note that vet has a frequency criteria for its checks, and I have never encountered this kind of mistake myself.

cc @dsnet in case he disagrees here

**Comment by seankhliao** [comment]
Closing as we appear to be in agreement that this isn't something we can do.
