### ISSUE TITLE
cmd/go: "package not found" error is less useful than GOPATH's when the missing package could have been in the main module

### ISSUE THREAD

**Issue by heschi** [golang/go#37214]
Given the following setup:
```
-- gopath/src/example.com/go.mod --
module example.com

go 1.14
-- gopath/src/example.com/main.go --
package main

import (
        "fmt"

        "example.com/mypkg"
)

func main() {
        fmt.Println(mypkg.Message)
}
-- gopath/src/example.com/mypackage/doc.go --
package mypackage

const Message = "sup"
```

and then running:

```
$ export GOPATH=$PWD/gopath
$ cd gopath/src/example.com
$ GO111MODULE=off go run main.go
main.go:6:2: cannot find package "example.com/mypkg" in any of:
	.../go/src/example.com/mypkg (from $GOROOT)
	../gopath/src/example.com/mypkg (from $GOPATH)
```

This is clear and actionable: there are two directories that could have contained the package, and neither did. You can ls the directories, compare the paths to the filesystem, etc.

In module mode:

```
$ GO111MODULE=on gotip run main.go
go: finding module for package example.com/mypkg
main.go:6:2: cannot find module providing package example.com/mypkg: unrecognized import path "example.com/mypkg": reading https://example.com/mypkg?go-get=1: 404 Not Found
```

This is much less actionable. Why is it going to the Internet for a package that should be on the local filesystem? Did it look anywhere first, and if so where? (If example.com were a GitHub URL the error would be different, but talking about private repos isn't any more helpful here.)

In case it wasn't obvious, the problem is a typo: the package is named mypackage, not mypkg. I think the GOPATH error gives a new user a fighting chance of finding their mistake; the module error needs at least a basic understanding of package-to-module resolution, and nested modules (!) to make any sense.

Concretely, I would like to see the module mode error look more like the GOPATH error:

```
main.go:6:2: cannot find package "example.com/mypkg" in any of:
   	.../go/src/example.com/mypkg (standard library)
	../gopath/src/example.com/mypkg (module example.com)
       https://example.com/mypkg (module example.com/mypkg): unrecognized import path "example.com/mypkg": reading https://example.com/mypkg?go-get=1: 404 Not Found
```

@bcmills @jayconrod

**Comment by bcmills** [comment]
> ```
> main.go:6:2: cannot find package "example.com/mypkg" in any of:
> ```
> ```
> 	.../go/src/example.com/mypkg (standard library)
> ```

This line would be misleading: we would not even check that directory, because the first component of the missing import path contains a dot.

> ```
> 	../gopath/src/example.com/mypkg (module example.com)
> ```

This one we can perhaps fix. (Compare https://github.com/golang/go/issues/33568#issuecomment-546938088.)

If we don't have any candidate modules to check in the first place, we produce an error message like:
```
package example.com/mypkg is not in the main module (example.com)
```
(That comes from [here](https://github.com/golang/go/blob/509592d188f6a30bb65b27a24f4c6f68716ea063/src/cmd/go/internal/modload/query.go#L448).)

And note that if `example.com` were some existing module _other than_ the main module, we would produce something like:
```
module example.com@latest found (v1.2.3), but does not contain package example.com/mypkg
```

So probably we should mention the main module in some form here too. But we need to be careful about how we describe the file path, because it is entirely possible that `../gopath/src/example.com/mypkg` _does_ exist, but is in an unpublished nested module with its own `go.mod` file (rather than the main module).

**Comment by heschik** [comment]
Sure, I didn't mean to dictate any specifics. I was more arguing for a philosophy of error reporting: for each location looked up, there should be some variety of not found error, and if resolution eventually fails, the resulting message should detail each location searched and why it didn't work. So for the case at the end of your comment, I would hope for something like `../gopath/src/example.com/mypkg (module example.com): is hidden by nested module example.com/mypkg`. I'm assuming things about the structure of the code, of course.

**Comment by heschik** [comment]
Also, I'd like to see the same thing for replace targets, not just the main module.

**Comment by iwdgo** [comment]
Message seems now inline with expectations:

```
>gotip version
go version devel go1.17-aa4e0f528e Fri Jul 16 02:43:48 2021 +0000 windows/amd64

>gotip run main.go
main.go:6:9: no required module provides package example.com/mypkg; to add it:
        go get example.com/mypkg

```
