### ISSUE TITLE
x/tools/gopls: using a lot of memory

### ISSUE THREAD

**Issue by ajeecai** [golang/go#37223]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, I have update gopls with `GO111MODULE=on go get golang.org/x/tools/gopls@master golang.org/x/tools@master`

$ gopls version
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.1.8-0.20200213144451-3187b3c41574 h1:cDdkE3V1eIXwN6tdzqVXVYz3RkYVbE8y0n+sn6klUn4=

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ajee/.cache/go-build"
GOENV="/home/ajee/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ajee/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build734902289=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Use vs code 1.42.0, download https://github.com/asticode/go-astilectron-demo and browse its code, after a bit change then save to make gopls activated. 

### What did you expect to see?
From htop, this memory used by gopls should not be excessive. 

### What did you see instead?
The memory usage is soar, up to 9G, sometimes 12G by gopls, and it never goes down.
![image](https://user-images.githubusercontent.com/3023271/74520491-a6a58780-4f52-11ea-92ad-5ae4bf51f969.png)

The similar issue is discussed in https://github.com/golang/go/issues/30309, @stamblerre  encourages to open a new issue. 

The pprofile svg file is attached as required (in zip file as github required). Any information needed, pls tell me. 

Thanks 

[pprof001.zip](https://github.com/golang/go/files/4203876/pprof001.zip)

**Comment by stamblerre** [comment]
It seems like analysis is causing the high memory usage. Can you try disabling it by adding the following to your VS Code settings?

```json5
"gopls": {
	"experimentalDisabledAnalyses": [
		"asmdecl", "assign", "atomic", "atomicalign", 
		"bools", "buildtag", "cgocall", "composite", "copylock",      
		"errorsas", "httpresponse", "loopclosure", "lostcancel",
		"nilfunc", "printf", "shift", "stdmethods", 
		"structtag", "tests", "unmarshal", "unreachable", "unsafeptr",
		"unusedresult", "deepequalerrors", 
		"sortslice", "testinggoroutine"
	],
},
```

We also just released gopls/v0.3.2 - can you try downloading that to see if affects anything? (`GO111MODULE=on go get golang.org/x/tools/gopls@v0.3.2`).

**Comment by heschik** [comment]
Can you check your /tmp directory for files named `gopls.*`? It should have written out some profiles. They're named after the size of the heap; please upload the ones from the biggest heaps.

**Comment by ajeecai** [comment]
Hi, I just tried, adding the options in vs code setting doesn't help. And I also update to 0.3.2, looks the same, memory up to 9G. Please see the attached zip file which includes svg for memory profile. Also I didn't find any files name gopls.* under /tmp, instead in my home directory there is a folder named pprof which contains some files with gopls, then I include one is generated at the same timestamp in the zip. Anything else please tell me.

Thanks  
[pp.zip](https://github.com/golang/go/files/4208636/pp.zip)

**Comment by stamblerre** [comment]
Thanks for the profiles. Looks like the inspect analysis is still using the majority of the memory. I've disabled in analyses in [CL 219897](https://go-review.googlesource.com/c/tools/+/219897) - can you try rebuilding `gopls` with that CL patched in and see if that resolves the problem?

This can be done with the following steps:

```shell
$ cd $(mktemp -d)
$ git clone https://go.googlesource.com/tools
$ cd tools
$ git fetch "https://go.googlesource.com/tools" refs/changes/97/219897/1 && git cherry-pick FETCH_HEAD
$ cd gopls
$ go install
```

This supports @heschik's theory that analyses aren't being canceled in time, and that we are running too many analyses concurrently.

**Comment by ajeecai** [comment]
Hi,  good news with CL 219897, now the memory stays low even I remove experimentalDisabledAnalyses from the vs code config.

**Comment by heschik** [comment]
Cool, that confirms that it was a problem with analyses. Can you see if https://golang.org/cl/219958 (which is on master now) also helps?

**Comment by ajeecai** [comment]
Hi @heschik , I just git clone https://go.googlesource.com/tools and go install from head, it seems working, no memory soar.

**Comment by stamblerre** [comment]
Thanks for confirming! I'll mark this as closed, and https://golang.org/cl/219958 will be part of the gopls/v0.4.0 release.

**Comment by nikkolasg** [comment]
Just want to report my case here since related: Using vim-go, that uses gopls underneath, I see my memory usage just growing, need to restart vim after a couple of hours each time. With latest updated binaries using vim-go `:GoUpdateBinaries`.

**Comment by stamblerre** [comment]
@nikkolasg: Just to confirm, the output of `gopls version` is `v0.3.4`?

**Comment by nikkolasg** [comment]
```
golang.org/x/tools/gopls v0.3.4
    golang.org/x/tools/gopls@v0.3.4 h1:4GC7q/pXQ/tsxHBGVdsMdlB4gCxVC06m/7rIXg1Px4E=
```
Yes!

**Comment by stamblerre** [comment]
Thanks! Yes, hopefully we can debug this. There should be some files named `gopls.PID`- in your temporary directory, named after heap sizes. Please upload the pair for the largest heap -- I would like to see a goroutine dump that matches this heap dump.

**Comment by nikkolasg** [comment]
Any idea where I can find this file ? Only thing relevant I find in `/tmp` is `gopls_stderrsq5q_qoo.log` but it's empty.

**Comment by stamblerre** [comment]
Maybe try looking in whatever the value of `TMPDIR` is on your machine? ([This](https://pkg.go.dev/os?tab=doc#TempDir) might be helpful.)

**Comment by nikkolasg** [comment]
my tmpdir is empty , so I'm using the same tmpdir as what go returns I guess ? 
`find . -name gopls.PID` didn't return anything in `/tmp` ... Maybe vim-go changes that but I don't see it.

**Comment by stamblerre** [comment]
Ah, the `PID` means it will be a process ID, so you may want to run something like `find . -name "gopls.*"`. If nothing turns up still, then maybe @heschik can advise.

**Comment by nikkolasg** [comment]
nothing turns out there as well :/ 
`/tmp:%  find . -name "gopls.*"`

**Comment by EnriqueL8** [comment]
I'm hitting the same problem as well. Same version and nothing found with the `find . -name "gopls.*"`.

**Comment by heschik** [comment]
It would be very, very surprising if recent versions of gopls hadn't written of those files to /tmp while using a problematic amount of memory. Can you triple-check that there isn't an old version anywhere, and that it's actually gopls using the memory?

**Comment by nikkolasg** [comment]
Nice  ! In fact it was YouCompleteMe that used an old version, no vim-go, I found it by running your command. Updated it manually and so far it works good !
Thanks a lot !

**Comment by ericwq** [comment]
i might find the correct setup method for gopls. see the [post](https://github.com/josa42/coc-go/issues/76#issuecomment-678752724)
