### ISSUE TITLE
spec: valid assignment does not compile but according to https://golang.org/ref/spec#Assignability, it should

### ISSUE THREAD

**Issue by ecpy** [golang/go#37222]
### What version of Go are you using (`go version`)?
go version go1.13.5 linux/amd64 
### Does this issue reproduce with the latest release?
ys

### What operating system and processor architecture are you using (`go env`)?
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/edward/.cache/go-build"
GOENV="/home/edward/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/edward/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build917785383=/tmp/go-build -gno-record-gcc-switches"
```
 
 
### What did you do?
```go
package main

func main() {
   type B float32
   var b B = float32(0)   
}
```
doesnt compile

### What did you expect to see?
it compiles

### What did you see instead?
```sh
./main.go:7:6: cannot use float32(0) (type float32) as type B in assignment
```

**Comment by TapirLiu** [comment]
Which rule? I know one of the rules is like:
```golang
package main

func main() {
   type B float32
   var b B = B(float32(0))
   _ = b
}
```

**Comment by ecpy** [comment]
rule #2: x's type V and T have identical underlying types and at least one of V or T is not a defined type.

**Comment by AlexRouSg** [comment]
> at least one of V or T is **not** a **defined type**

https://golang.org/ref/spec#Numeric_types
> To avoid portability issues **all numeric types are defined types**

https://golang.org/ref/spec#Type_definitions

> A type definition creates a new, distinct type with the same underlying type and operations as the given type, and binds an identifier to it.
> 
> TypeDef = identifier Type .
> The new type is called a defined type.

Both `float64` and `B` are defined types.

**Comment by ecpy** [comment]
But defined types are defined as non-internal new type  in the documentation?

**Comment by AlexRouSg** [comment]
Where does it say that?

**Comment by dpinela** [comment]
@AlexRouSg A small correction:

> https://golang.org/ref/spec#Type_definitions
> 
> > Each type T has an underlying type: If T is one of the predeclared boolean, numeric, or string types, or a type literal, the corresponding underlying type is T itself.
> 
> The underlying type of `B` is `B` and not `float32`

This is incorrect - the underlying type of `B` is in fact `float32` (per another part of the spec, which you quoted earlier). That spec clause applies only to the predeclared types, of which `B` is not one.

**Comment by beoran** [comment]
It will work if you use an alias type:

```go
package main

func main() {
	type B = float32
	var b B = float32(0)
	_ = b
}
```
https://play.golang.org/p/nI6-mjihFf2


The original does not work because both `B` and `float32`are defined types. In my example, `B`is not a defined type but a type alias, which does work. This might be more of a documentation or question issue. See here for better places to ask questions about Go: https://github.com/golang/go/wiki/Questions

**Comment by ianlancetaylor** [comment]
You can't assign directly from one defined type to another without a conversion.  In the original example, both `B` and `float32` are defined types.  This is working as expected and intended.

**Comment by ecpy** [comment]
if so, what types are undefined?

**Comment by beoran** [comment]
Aliases, such as rune are not defined types. Constants can be of undefined type as well  A type which you define using type, as well as all built in types are defined types.

https://play.golang.org/p/Cd-BejkvvmY

**Comment by ianlancetaylor** [comment]
A defined type is a type with a name that is not an alias.  See "Type definitions" at https://golang.org/ref/spec#Type_declarations.  A type that does not have a name is not a defined type (I wouldn't call it an undefined type, though).  An example of a type without a name is `[]byte`.

**Comment by beoran** [comment]
Interesting. An anonymous struct value is also not of a defined type. 

```go

package main

import (
	"fmt"
)

type Buffer []byte
type S struct {
	I int
	S string
}

func main() {
	unnamed := []byte {'a', 'b', 'c'}
	var named Buffer = unnamed
	fmt.Printf("named: %v\n", named)
	unnamed2 := struct {
			I int
			S string
		} { I: 7, S : "hi"}
	var named2 S = unnamed2
	fmt.Printf("named2: %v\n", named2)
	unnamed = named
	unnamed2 = named2
} 
```
https://play.golang.org/p/nRlbuq1Dwrs
I hope all these examples make it more clear.
