### ISSUE TITLE
Question: Why pointers' zero value is not the zero value of what they points to?

### ISSUE THREAD

**Issue by alvaroloes** [golang/go#37224]
This is a question to get some information before thinking about a possible proposal regarding zero values.

**Could you please let me know or point me to an authoritative document where I can read about the reasons why the zero value of a pointer is `nil` instead of a pointer to the zero value of what it points to?**

Is it because of performance or memory? Simplicity in the runtime?

Example:
```go
type Pet struct {
	name string
	kind string
}
type Person struct {
	name    string
	age     int
	friends []Person
	pet     Pet
}

// Current Go
var person1 Person // { name: "", age: 0, friends: [], pet: <nil> }
var person2 *Person // <nil>

// Assuming the zero value of a pointer is a pointer to the zero value of what it points to, then:
var person1 Person // { name: "", age: 0, friends:[], pet: &{ name: "", kind: "" } }
var person2 *Person // &{ name: "", age: 0, friends:[], pet: &{ name: "", kind: "" } }
```

Thanks!

**Comment by mvdan** [comment]
See the very top of the issue template:

> For questions please use one of our forums: https://github.com/golang/go/wiki/Questions

**Comment by alvaroloes** [comment]
This is the thread: https://groups.google.com/forum/#!topic/golang-nuts/Q4BS8Xrbg7M
