### ISSUE TITLE
x/pkgsite: incorrect go source code download path for generating documentation

### ISSUE THREAD

**Issue by johanavril** [golang/go#37240]
### What is the URL of the page with the issue?
 https://go.dev/about
 
 
### What is your user agent?
 Chrome 80 on Linux

 
 
 
### Screenshot
![image](https://user-images.githubusercontent.com/38969878/74587192-30705600-5022-11ea-9c11-2ab303e3ebdf.png)

 
 
 
### What did you do?
 accessing the page

 
 
 
### What did you expect to see?
 the go source code path to be proxy.golang.org/&lt;module&gt;/@v/&lt;version&gt;.zip
 
 
### What did you see instead?
the go source code path is proxy.golang.org/&lt;module&gt;@&lt;version&gt;.zip

**Comment by johanavril** [comment]
Hi @julieqiu , I want to try to help fix this, but I cant seem to find the source code for this page on [pkgsite repo](https://github.com/golang/pkgsite).
And the issue is moved, previously it was on **Adding a package section**, now it moved to **Documentation section**.

**Comment by julieqiu** [comment]
Thanks! This should now be fixed in both sections.
