### ISSUE TITLE
x/mobile: Undefined symbols for architecture

### ISSUE THREAD

**Issue by samzhiwei** [golang/go#37241]
### What version of Go are you using (`go version`)?

<pre>
The latest version

</pre>

### Does this issue reproduce with the latest release?

</pre></details>

### What did you do?
Follow [the guide](https://github.com/golang/go/wiki/Mobile#building-and-deploying-to-ios-1) step by step

### What did you expect to see?
Use gomoblie to build a framework for iOS

I try to build a .framework for iOS. After draging .framewok file in to a new demo project and build it in iPhoneX. Importing .framework is fine , and Xcode can completion the code automatically.

But Xcode log:

> ld: warning: ignoring file ~/Libgodemo.framework/Libgodemo, file is universal (4 slices) but does not contain the arm64 architecture: ~/Libgodemo.framework/Libgodemo
> Undefined symbols for architecture arm64:
>   "_LibgodemoGreetings", referenced from:
>       @objc ViewController.viewDidLoad() -> () in ViewController.o
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

The same problem come out in iOS simulator (Undefined symbols for architecture x86_64)

Then, I check the .framework file architecture symbol use `lipo -info`
Log:

> Architectures in the fat file: ~/Libgodemo.framework/Versions/A/Libgodemo are: armv7 i386 x86_64 arm64 

The .framework file is support arm64, but Xcode ignore the file due to its  unsupport arm64. Any idea for this?

**Comment by toothrot** [comment]
Can you please provide the output of `go version` and `go env` from the issue template? This information is critical in investigating this kind of issue.

/cc @hyangah

**Comment by hiteshjoshi** [comment]
I am going through the same issue. I think its similar to this https://github.com/golang/go/issues/28517

**Comment by hiteshjoshi** [comment]
Greeter.framework is compiled by gomobile , dragged to xcode as library.
The error is 
```
ld: warning: ignoring file /Users/hitesh/Downloads/GoMobileTest/Greeter.framework/Greeter, file is universal (4 slices) but does not contain the arm64 architecture: /Users/hitesh/Downloads/GoMobileTest/Greeter.framework/Greeter

Undefined symbols for architecture arm64:
  "_GreeterNewGreeter", referenced from:
      GoMobileTest.ViewController.viewDidLoad() -> () in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

```
go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hitesh/Library/Caches/go-build"
GOENV="/Users/hitesh/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Volumes/Projects/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/hitesh/sdk/go1.13.3"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/hitesh/sdk/go1.13.3/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b3/vc02w5c12d9ghxn16_jnb4gc0000gn/T/go-build555747915=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

```
go version go1.13.3 darwin/amd64
gomobile version +4c31acb Sun Mar 29 12:56:38 2020 +0000 (android,ios); androidSDK=
```

**Comment by hiteshjoshi** [comment]
Basically, I was just giving this post a shot.
https://medium.com/@matryer/tutorial-calling-go-code-from-swift-on-ios-and-vice-versa-with-gomobile-7925620c17a4
