### ISSUE TITLE
How to disable the proxy of go get

### ISSUE THREAD

**Issue by weixingsun** [golang/go#37248]
Doc only address how to enable it, not disabling it. 
Go config http.proxy http://IP:port

**Comment by seankhliao** [comment]
https://golang.org/cmd/go/#hdr-Module_downloading_and_verification

**Comment by weixingsun** [comment]
@seankhliao thanks for your quick reply, I checked the documents, and it said that go get uses git config, the I removed it using: git config --global --unset http.proxy
and then disable vars : unset http_proxy https_proxy GOPROXY

unfortunately, my system still complains : Failed to connect to github.com port 443: Connection timed out
looks like it is not my problem.
Thanks anyway
