### ISSUE TITLE
x/tools/gopls: errors while trying to write a struct literal

### ISSUE THREAD

**Issue by urandom** [golang/go#37259]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 darwin/amd64
</pre>

<pre>
$ gopls version
golang.org/x/tools/gopls v0.3.2
    golang.org/x/tools/gopls@v0.3.2 h1:eP1aj1AvT6ynElQH6KP0mmOT2gnWa1gYclHL4wGUbMo=
</pre>

### What operating system and processor architecture are you using (`go env`)?
Happens on both linux and macosx

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/viktor.kojouharov/Library/Caches/go-build"
GOENV="/Users/viktor.kojouharov/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/viktor.kojouharov/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD="/Users/viktor.kojouharov/projects/feature-toggles/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ky/99mqlqrd2rd46chcz3tqmxkw0000gn/T/go-build162991808=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

While I'm writing the fields and values of a struct in neovim 0.5.0 using the built-in lsp facilities, I get interruptions and the following messages:

{name:_CURSOR_}

<pre>
LSP[gopls] 2020/02/17 09:01:01 failed to fix AST: unable to parse defer or go from *ast.BadStmt: no defer or go statement found
</pre>

### What did you expect to see?
Nothing.

### What did you see instead?
failed to fix AST: unable to parse defer or go from *ast.BadStmt: no defer or go statement found

**Comment by urandom** [comment]
Followup, it seems that this error is being shown *after a while*. On initial server start, there are no problems. And it doesn't just occur when writing structs, but also various other kinds of statements

**Comment by stamblerre** [comment]
This is an error that appears in the `gopls` logs, and it's not part of the diagnostics that should be published to the user. I think that this may be a bug in neovim LSP client, and I would recommend moving this issue to that repository.

**Comment by stamblerre** [comment]
Thanks! Closing in favor of the upstream issue.
