### ISSUE TITLE
go.dev: issue processing go.felesatra.moe/animanager

### ISSUE THREAD

**Issue by darkfeline** [golang/go#37258]
### What did you do?

1. Run `curl proxy.golang.org/go.felesatra.moe/animanager/@v/v0.17.0.info` to confirm existence.
2. Check https://index.golang.org/index?since=2020-02-16T00:00:00Z to confirm indexing:

    ```
    {"Path":"go.felesatra.moe/animanager","Version":"v0.17.0","Timestamp":"2020-02-16T11:22:16.96407Z"}
    ```

    It is currently Mon 17 Feb 2020 05:40:58 AM UTC as of bug creation time.
3. Visit https://pkg.go.dev/go.felesatra.moe/animanager

### What did you expect to see?

Package/module docs

### What did you see instead?

404 page

I see that there are a handful of other bugs expressing confusion around adding packages to pkg.go.dev, and it seems that a number of people including me are confused around how to add a package to pkg.go.dev.

**Comment by proyb6** [comment]
FYI https://groups.google.com/forum/#!msg/golang-dev/mfiPCtJ1BGU/OZ9cU3SgBgAJ

**Comment by jba** [comment]
You did everything right. This is a problem with pkg.go.dev's module processing logic. We've never seen a zip file with a directory entry before&mdash;`go mod download` does not generate them&mdash;so we treated it as an error. We have a CL out with a fix. I'll ping this bug when that fix is in production.

**Comment by jba** [comment]
Working now in production.
