### ISSUE TITLE
Provide a way to pass maps to go with cgo

### ISSUE THREAD

**Issue by spellr** [golang/go#37267]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.15 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/speller/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/speller/go"
GOPROXY=""
GORACE=""
GOROOT="/opt/go"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build238739411=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I'm trying to pass a map from C++ to go, and to process it there.
main.go:
```golang
package main

import (
    "C"
    "fmt"
)

func main() {}

//export PrintMap
func PrintMap(m map[string]string) {
    fmt.Println(m)
}
```

Which "compiles" to:
```c
typedef void *GoMap;

extern void PrintMap(GoMap p0);
```

But there's no way to call this function from C++.
I can't initialize a GoMap in C++/C, and to pass it to my go code.

**Comment by ianlancetaylor** [comment]
There is no way to do this.  You can't create a Go map in pure C code.  You need to call Go code to build the map.

Note that Go code cannot return a map to C code, as that would break the pointer passing rules.  You'll need to have the Go code store the map in a global variable and have the Go code that uses the map read that global variable.  If you need multiple maps you'll need to have the Go code that creates the map return some sort of handle, and have the Go code that uses the map look up the handle to get the map.

**Comment by spellr** [comment]
So you're saying there's no way to use that `GoMap` type.
Maybe it's better to no `typedef` in the header file?
Or even to not export this function that uses `GoMap`, since it can be used?

**Comment by ianlancetaylor** [comment]
I guess you could use this function if Go passes a map to C code and the C code passes that map to `PrintMap`.
