### ISSUE TITLE
go.dev: license not detected for github.com/decomp/decomp

### ISSUE THREAD

**Issue by mewmew** [golang/go#37268]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/decomp/decomp
 
### What is your user agent?
 

 
Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0
 
### Screenshot
 

 
![screenshot_2020-02-17_21:24:16](https://user-images.githubusercontent.com/1414531/74684329-ea56f600-51cb-11ea-9d3d-ac27b9cbb740.png)
 
### What did you do?
 

 
 Try to navigate to the package documentation of [github.com/decomp/decomp](https://github.com/decomp/decomp) on `pkg.go.dev`.
 
### What did you expect to see?
 
 Similar result to that of GoDoc.org. https://godoc.org/github.com/decomp/decomp
 
### What did you see instead?

Nothing. `Licenses: none detected.`

### Additional information

The root of the repository contains [UNLICENSE](https://github.com/decomp/decomp/blob/master/UNLICENSE), and GitHub correctly recognizes the license as UNLICENSED.

![screenshot_2020-02-17_21:26:40](https://user-images.githubusercontent.com/1414531/74684460-44f05200-51cc-11ea-9ade-ec53c4b409ec.png)

**Comment by toothrot** [comment]
@mewmew Thanks for reporting! Please see the pkg.go.dev license policy at https://pkg.go.dev/license-policy. The filename in this issue isn't currently supported.

/cc @julieqiu who can help explain more.

**Comment by mewmew** [comment]
Thanks for the feedback @toothrot,

I thought UNLICENSED was supported already, but now realize it is to be supported in the future, as indicated by @rsc in https://groups.google.com/d/msg/golang-dev/mfiPCtJ1BGU/OZ9cU3SgBgAJ

> - The next rev of the site will display docs for CC0- and Unlicense-licensed modules. That will happen ideally next week. More generally, we continue to work down the list of most common licenses in the Go ecosystem and accommodate what we can. At some point I hope to have a blog post talking about why licensing is important generally and what we can and can't use, but for now just please understand that we are doing what we can to make pkg.go.dev work as well as possible for as much of the Go ecosystem as possible. We're not done yet.

I'll leave this issue open until pkg.go.dev has support for UNLICENSED.

Cheers,
Robin

**Comment by toothrot** [comment]
To be clear, I believe it may be the case that the specific filename `UNLICENSED` is not currently supported, but "Unlicense" is listed at https://pkg.go.dev/license-policy.

**Comment by julieqiu** [comment]
We plan to support the filename `UNLICENSE` in the future. We'll close this issue once the change is live on pkg.go.dev.

/cc @jba

**Comment by jba** [comment]
The license is now detected and we show the README and docs: https://pkg.go.dev/mod/github.com/decomp/decomp@v0.0.0-20200129164823-f7110dc2f795.
