### ISSUE TITLE
does go module replace will support inherit

### ISSUE THREAD

**Issue by yhyddr** [golang/go#37261]
Both go moudle's replace and exclude take effect only for the current build and are not propagated to other projects.

### What did you not expect to see?
![image](https://user-images.githubusercontent.com/32089134/74642958-e9fc3200-51ae-11ea-92ed-b0cdd48f556d.png)

when other module import article module, would get an error.
```bash
go: github.com/article@v0.0.0 requires github.com/test@v0.0.0: 
reading https://goproxy.cn/github.com/test/@v/v0.0.0.mod: 404 Not Found
```

**Comment by toothrot** [comment]
I don't believe that replace directives will ever be propagated. This would be a big enough change to require a proposal: https://github.com/golang/proposal#proposing-changes-to-go. I'll close this issue for now.

The proposed feature would be a huge surprise to the developer when managing dependencies, giving dependencies the power to change the meaning of an import.

/cc @bcmills @jayconrod

**Comment by jayconrod** [comment]
This is very much intentional. `replace` and `exclude` are intended for local development and fixing short-term problems with dependencies.

The ecosystem cannot scale if replacements are used everywhere, since conflicts can't be resolved.
