### ISSUE TITLE
x/tools/gopls: only show outside of GOPATH/modules warning once

### ISSUE THREAD

**Issue by stamblerre** [golang/go#37279]
See https://github.com/microsoft/vscode-go/issues/3055.

**Comment by stamblerre** [comment]
I think the correct fix for this would be to show the warning only once, on view creation, instead of on diagnostics.

**Comment by myitcv** [comment]
What about only showing the warning if the user actively tries to do something via `gopls`?

i.e. the initial attempt to pre-load the workspace can fail, it only becomes relevant if the user actually does something within that workspace, i.e. open a `.go` file.

**Comment by stamblerre** [comment]
Right now, we only show the warning if the user is working outside of GOPATH/modules and has a dependency we cannot resolve. This has been an acceptable approximation of "something went wrong and here's a hint", but it can cause the warning to pop up when the user is just typing an import manually. I think showing it once only if we see errors in the package (caused by dependencies) is probably the best fix because we don't want to bother the user unnecessarily (and opening an ad-hoc package is not necessarily wrong).

**Comment by pjweinb** [comment]
If the workspace outside GOPATH/modules we show this message a lot if the user has code with diagnostics. I think it would be better only to show it if it's the inital load or the user is changing configuration (and there are other errors). I have a CL.
