### ISSUE TITLE
x/tour: translate error

### ISSUE THREAD

**Issue by edoardottt** [golang/go#37287]
Contesto: https://go-tour-ita.appspot.com/basics/11

I tipi int, uint, **_and_** uintptr sono grandi normalmente 32 bit su sistemi da 32-bit e 64 bit su sistemi da 64-bit. Quando hai bisogno di un valore intero dovresti usare int a meno che tu non abbia particolari necessità di usare tipi di interi di dimensioni diverse o unsigned. 

I think that **and** isn't correct. It would be '**e**', the conjunction in italian.
Ps: I'm italian-native.

**Comment by toothrot** [comment]
Thanks for the report! 

Issues for Tour are tracked at https://github.com/golang/tour/issues. Please re-file there.
