### ISSUE TITLE
x/tools/gopls: function signature show target alias not type alias when hover on function

### ISSUE THREAD

**Issue by wingyplus** [golang/go#37283]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +4b4370066f Mon Dec 30 09:34:53 2019 +0000 darwin/amd64
$ gopls version
golang.org/x/tools/gopls v0.3.1
    golang.org/x/tools/gopls@v0.3.1 h1:yNTWrf4gc4Or0UecjOas5pzOa3BL0WDDyKDV4Wz5VaM=
</pre>

### What did you do?

I used gopls with emacs lsp-mode and hover on function name `FromGeo` in [h3](https://github.com/uber/h3-go) library. 

### What did you expect to see?

function signature on hover should return `h3.H3Index`

### What did you see instead?

It's returns `h3._Ctype_ulonglong`

<img width="819" alt="Screen Shot 2563-02-18 at 21 33 40" src="https://user-images.githubusercontent.com/484530/74745824-0c697a80-5297-11ea-9dec-b1f506888a7e.png">

**Comment by wingyplus** [comment]
For more information `h3.H3Index` alias from type `C.H3Index` (https://pkg.go.dev/github.com/uber/h3-go?tab=doc#H3Index) and `C.H3Index` is type `uint64_t` in h3 C library [here](https://github.com/uber/h3/blob/master/src/h3lib/include/h3api.h.in#L55).

**Comment by wingyplus** [comment]
Oh, or perhaps it's not work with cgo?

**Comment by wingyplus** [comment]
it's seems it received `_Ctype_ulonglong` after calling `types.Checker.Check()` in [L381](
https://github.com/golang/tools/blob/master/internal/lsp/cache/check.go#L381)

**Comment by ridersofrohan** [comment]
Not sure how much we can do if that is coming directly from `go/types`

**Comment by wingyplus** [comment]
Another reproduce case is:

```
// source
package main

// #include<stdint.h>
// typedef uint64_t Index;
import "C"
import "fmt"

type Index = C.Index

func main() {
	var a Index
	fmt.Println(a)
}
```

After request autocomplete I got `Index` is type uint64.

<img width="1440" alt="Screen Shot 2563-03-03 at 17 38 51" src="https://user-images.githubusercontent.com/484530/75768203-7d6c6000-5d76-11ea-8fd4-263a8bf6bd33.png">

**Comment by stamblerre** [comment]
We will probably need to do the same thing that we did for placeholders here (https://golang.org/cl/208497).
