### ISSUE TITLE
How about fail to build when index out of bounds?

### ISSUE THREAD

**Issue by 243083df** [golang/go#37282]
For example code below compiled with -gcflags="-d=ssa/check_bce/debug=1" trigger 
Found IsInBounds
```
package main

func main() {
        a := []int{1,2,3,4,5}
        for i:=0; i<len(a);i++ {
                _ = a[i+1]
        }
}
```
when this code not trigger "Found IsInBounds"
```
package main

func main() {
        a := []int{1,2,3,4,5}
        for i:=0; i<len(a) - 1;i++ {
                _ = a[i+1]
        }
}
```

So why do not throw error if this detected?

**Comment by toothrot** [comment]
We don't really use our issue tracker for questions. More people will see your question, and you will get better answers, if you ask on a forum rather than on the issue tracker. See https://golang.org/wiki/Questions

**Comment by ALTree** [comment]
@243083df Even if the compiler can statically prove that the code contains an OOB array access, it cannot refuse to compile the program because nothing in the Language Specification says that that program is not valid, I believe.
