### ISSUE TITLE
Sandbox Process

### ISSUE THREAD

**Issue by ws7789337** [golang/go#37296]
![Screenshot_20200218-153026_YouTube](https://user-images.githubusercontent.com/49947778/74813741-6da34500-52bb-11ea-936c-b25cf66fb8f1.jpg)
![Screenshot_20200218-144741_X-plore](https://user-images.githubusercontent.com/49947778/74813744-6ed47200-52bb-11ea-919f-4c0c64169efe.jpg)
![Screenshot_20200218-153022_YouTube](https://user-images.githubusercontent.com/49947778/74813745-6f6d0880-52bb-11ea-9eb7-f204ce5bb141.jpg)
![Screenshot_20200218-144318_Google Play services](https://user-images.githubusercontent.com/49947778/74813747-70059f00-52bb-11ea-82af-0db87a8253e7.jpg)
![1582088164792](https://user-images.githubusercontent.com/49947778/74813748-7136cc00-52bb-11ea-8717-381fe22c558f.jpg)
![Screenshot_20200218-153014_YouTube](https://user-images.githubusercontent.com/49947778/74813749-7136cc00-52bb-11ea-8627-e78b9bae8fd3.jpg)
![Screenshot_20200218-144314_Google Play services](https://user-images.githubusercontent.com/49947778/74813753-7267f900-52bb-11ea-830f-9b26cb9211e0.jpg)
![Screenshot_20200218-153117_YouTube](https://user-images.githubusercontent.com/49947778/74813755-73008f80-52bb-11ea-891b-9fc8a253516c.jpg)
![Screenshot_20200218-144306_Google Play services](https://user-images.githubusercontent.com/49947778/74813756-7431bc80-52bb-11ea-9efa-20ae0f9d8747.jpg)
![Screenshot_20200218-153111_YouTube](https://user-images.githubusercontent.com/49947778/74813758-74ca5300-52bb-11ea-8eaa-3061d4c5bf7b.jpg)
![Screenshot_20200218-145045_Google Play services](https://user-images.githubusercontent.com/49947778/74813762-7562e980-52bb-11ea-84fc-dde4e512666f.jpg)
![Screenshot_20200217-173208_Google Play services](https://user-images.githubusercontent.com/49947778/74813764-75fb8000-52bb-11ea-9999-5135ddf11c3b.jpg)
![Screenshot_20200218-144245_Google Play services](https://user-images.githubusercontent.com/49947778/74813766-76941680-52bb-11ea-871d-542f82706ada.jpg)
![Screenshot_20200218-144239_Google Play services](https://user-images.githubusercontent.com/49947778/74813767-772cad00-52bb-11ea-832d-e1312c51009f.jpg)
![Screenshot_20200218-145039_Google Play services](https://user-images.githubusercontent.com/49947778/74813768-77c54380-52bb-11ea-83ca-8efe765de597.jpg)
![Screenshot_20200218-144233_Google Play services](https://user-images.githubusercontent.com/49947778/74813769-785dda00-52bb-11ea-8cc8-85aa43a12725.jpg)
![Screenshot_20200218-153054_YouTube](https://user-images.githubusercontent.com/49947778/74813773-798f0700-52bb-11ea-9d09-ed55f5943251.jpg)
![Screenshot_20200218-145032_Google Play services](https://user-images.githubusercontent.com/49947778/74813777-7ac03400-52bb-11ea-9672-56e4a912f864.jpg)
![Screenshot_20200218-144221_Google Play services](https://user-images.githubusercontent.com/49947778/74813778-7b58ca80-52bb-11ea-9893-438db9d37206.jpg)
![Screenshot_20200218-145026_Google Play services](https://user-images.githubusercontent.com/49947778/74813782-7d228e00-52bb-11ea-9f29-21cc334bd99e.jpg)
![Screenshot_20200218-145017_Google Play services](https://user-images.githubusercontent.com/49947778/74813786-7dbb2480-52bb-11ea-9cc4-0030eb410ecc.jpg)
![Screenshot_20200218-144038_Google Play  #services](https://user-images.githubusercontent.com/49947778/74813787-7eec5180-52bb-11ea-8552-e6348411490f.jpg)

### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by ALTree** [comment]
This does not seem to be relevant to the Go project. Closing.
