### ISSUE TITLE
Values of millisecond lost when using Mongo Driver to read time and Unmarshalling int into time.Time 

### ISSUE THREAD

**Issue by Abhaykumar1** [golang/go#37293]
Version : go 1.13
Mongo Driver Version : go.mongodb.org/mongo-driver v1.2.1

I'm fetching the Date stored in MongoDB. The value stored in DB is
reservedDate: 2020-02-19T07:11:23.890+00:00

After Unmarshalling the response into time.Time field the value becomes 
"reservedDate": "2020-02-19T07:11:23.89Z"

890 MilliSecond become 89, similarlly 100 becomes 1. The trailing Zeros are getting truncated.

**Comment by mvdan** [comment]
Why are you filing this issue here? You should probably file it with the mongo driver you're using.

**Comment by Abhaykumar1** [comment]
Version : go 1.13

When the defined time has trailing zero after the millisecond
	trailingZero = "2020-02-19T07:11:23.890+00:00"
	noTrailingZero = "2020-02-19T07:11:23.891+00:00"

GO removes the trailing zero.  The time becomes

2020-02-19 07:11:23.89 +0000 UTC
2020-02-19 07:11:23.891 +0000 UTC

This is an issue when other consuming application tries to consume this by defining a date formatter to get time from String value. The formatter does the strict matching.

for example in java
String pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSz";
SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);

It will throw an exception while parsing 2020-02-19 07:11:23.89 +0000 UTC while will perfectly work for 2020-02-19 07:11:23.891 +0000 UTC


Code To Replicate
const (
	trailingZero = "2020-02-19T07:11:23.890+00:00"
	noTrailingZero = "2020-02-19T07:11:23.891+00:00"
)

func main() {
	parseAndPrint(trailingZero)
	parseAndPrint(noTrailingZero)
}

func parseAndPrint(timeString string) {
	parsed, err := time.Parse(time.RFC3339, timeString)
	if err != nil {
		panic(err)
	}	
	fmt.Println(parsed)
}
