### ISSUE TITLE
x/website: download the archive link points to generic download page

### ISSUE THREAD

**Issue by nickgerace** [golang/go#37309]
Thank you in advance!

### What version of Go are you using (`go version`)?

Not applicable.

### Does this issue reproduce with the latest release?

[Yes.](https://golang.org/doc/install?download=go1.13.8.linux-amd64.tar.gz)

### What operating system and processor architecture are you using (`go env`)?

Fedora 31 on amd64

### What did you do?

I tried to copy the link from [here](https://golang.org/doc/install?download=go1.13.8.linux-amd64.tar.gz); specifically, where it says "Download the archive and extract it into /usr/local, creating a Go tree in /usr/local/go". The "Download the archive" portion is a hyperlink to the Go tarball.

### What did you expect to see?

I expected for the hyperlink to be "https://dl.google.com/go/go1.13.8.linux-amd64.tar.gz" instead of "https://golang.org/dl/".

### What did you see instead?

The "Download the archive" hyperlink resolves to "https://golang.org/dl/" and not "https://dl.google.com/go/go1.13.8.linux-amd64.tar.gz".

**Comment by ALTree** [comment]
Hi,

well, the link on "Download the archive" points to the generic dl page because pointing to the linux/amd64 archive would be wrong for anyone not running linux on amd64, right? I'm not sure why you'd expect the link to point to the linux/amd64 archive. Have I misunderstood your report?

**Comment by nickgerace** [comment]
Hi - You know what? I was totally off base here. You are correct. My apologies.

For some reason, I had though in the past that the installation instructions used the Linux amd64 link as an example. 

I apologize :). I can either close this or the team can.

**Comment by ALTree** [comment]
No problem and thanks for following up. Closing.
