### ISSUE TITLE
cmd/go: TestExecutableGOROOT occasionally fails with "text file busy"

### ISSUE THREAD

**Issue by josharian** [golang/go#37306]
Noticed on the build dashboard today:

https://build.golang.org/log/b1c4550d9629753e0fc2909f97f5610c385b0846

@matloob

**Comment by bcmills** [comment]
[2020-02-20T05:04:39-49f8d45/freebsd-arm64-dmgk](https://build.golang.org/log/b832085339d0902be3bb37fc64983ede2a8cb80a)
[2020-02-20T00:34:12-06fa4c9/linux-386-sid](https://build.golang.org/log/64d57cc44d0e0ad89a4bac1c20b681984ae950c6)
[2020-02-19T21:59:50-e5f5607/linux-386-387](https://build.golang.org/log/c52c613f77df2b60a6d0fe202ed601e2989dcd42)
[2020-02-19T21:58:05-635f4b9/linux-386](https://build.golang.org/log/b1c4550d9629753e0fc2909f97f5610c385b0846)
[2019-05-01T16:33:17-cbe2b14/aix-ppc64](https://build.golang.org/log/2313e3dbc3a8c7b14c2e1b7c9db7a70a60ae214d)

**Comment by matloob** [comment]
Hm, the only change we made to this test is adding the t.Parallel() call. I'll see if I can figure out what the problem is.

**Comment by josharian** [comment]
I vaguely recall that a few years ago several of us undertook an effort to speed up all.bash. That included sprinkling a bunch of t.Parallel calls. Several of those had to get backed out, particularly in the runtime and cmd/go, because they caused flakiness. In some cases it was scheduling delays, in others assumptions that no one else shared resources we were tracking (fds), in others it was mutating global testing state like hooks.

Which doesn’t shed much light in this case; it is just to say “just adding t.Parallel” is known to be a common cause of flakiness. :)

**Comment by matloob** [comment]
Yup, that gives me more confidence that it was the right call to convert tests to the script framework rather than put in t.Parallel. I'll remove this particular t.Parallel at if I can't figure out what's going on by EOD.

**Comment by bcmills** [comment]
A hypothesis: perhaps the filesystem can't keep up during the parallel portion of the test, and certain kernels fail with `ETXTBSY` when attempting to execute a binary that has not yet been flushed to the filesystem?

I would be inclined to add a `df.Sync()` at the end of the `copyFile` helper function to see if that helps.

**Comment by matloob** [comment]
Okay, let's see if it helps. Sent a CL to add the Sync in.

**Comment by bcmills** [comment]
Well, there goes that theory:
https://build.golang.org/log/60bf5a1fb2bf300903733c248c3ea30f3f4bec52

At least the negative signal was immediate! 😅

**Comment by bcmills** [comment]
Oh, sweet! This is a symptom of #22315.

**Comment by bcmills** [comment]
Actually, it's not. That issue is talking about a bug that occurs _despite_ `O_CLOEXEC`, but we're not even setting that yet. Let's try adding `O_CLOEXEC` to the `os.OpenFile` call.

**Comment by matloob** [comment]
alright, another CL on its way!

**Comment by bcmills** [comment]
Reading #22315 in more detail, I suspect that it will still apply.

A more extreme solution might be to have `TestExecutableGOROOT` fork off a separate subprocess to copy the executable file. When that subprocess exits, we will know that the file does not remain open on any thread.

A less extreme solution might be to move the `copyFile` call ahead of the call to `tg.parallel()`.

I think we can ditch the `Sync`, too.

**Comment by matloob** [comment]
I've decided to go for the most extreme solution: to just convert the test to the script framework.

**Comment by bcmills** [comment]
I wonder whether that will even work — I don't think the `cp` command in `script_test.go` currently executes in a subprocess...
