### ISSUE TITLE
cmd/go: 'go help get' should not document the -v flag

### ISSUE THREAD

**Issue by perillo** [golang/go#37301]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14rc1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/manlio/.local/bin"
GOCACHE="/home/manlio/.cache/go-build"
GOENV="/home/manlio/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/manlio/.local/lib/go:/home/manlio/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/manlio/sdk/go1.14rc1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/manlio/sdk/go1.14rc1/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build166081677=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.14rc1 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.14rc1
uname -sr: Linux 5.5.4-arch1-1
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.31.
gdb --version: GNU gdb (GDB) 9.1
</pre></details>

### What did you do?

`go help get` is missing the documentation of the `-v` flag, that is present in `go help gopath-get`:

```
The -v flag enables verbose progress and debug output.
```

Thanks.

**Comment by jayconrod** [comment]
The `-v` flag is not specific to `go get` in either mode. It's shared with other build commands and documented in `go help build`. In `GOPATH` mode, it causes `go get` to print a couple extra lines, but it doesn't do anything interesting in module mode.

It should probably be removed from `go help gopath-get` and the summary line of `go help module-get`. No real need to mention it in either place.

**Comment by perillo** [comment]
This is not true.
```
$  GOPROXY=direct go get -v gopkg.in/yaml.v1
get "gopkg.in/yaml.v1": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v1", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v1"} at //gopkg.in/yaml.v1?go-get=1
go: finding gopkg.in/yaml.v1 latest
go: downloading gopkg.in/yaml.v1 v1.0.0-20140924161607-9f9df34309c0
go: extracting gopkg.in/yaml.v1 v1.0.0-20140924161607-9f9df34309c0
gopkg.in/yaml.v1
```

The documentation of the `-v` flag for the `go build` command is
```
print the names of packages as they are compiled
```

This means that the `-v` flag for `go get` is different.
It doesn't do anything interesting in module mode, only because it uses the proxy by default.

**Comment by bcmills** [comment]
@perillo, that output does not appear to be from a Go 1.14 build.

But to the extent that `-v` prints things beyond compiled packages, it probably should not. (See #23662.)

**Comment by bcmills** [comment]
(Specifically, see https://github.com/golang/go/issues/23662#issuecomment-411957787.)

**Comment by perillo** [comment]
Seems reasonable, thanks.

There seems to be a proposal about printing network progress, maybe a `-vv` flag?

**Comment by bcmills** [comment]
> There seems to be a proposal about printing network progress

That's #15959.
