### ISSUE TITLE
hash/maphash: first call of the Reset method doesn't reset internal state 

### ISSUE THREAD

**Issue by ALTree** [golang/go#37315]
The new `hash/maphash` package has a [`Reset` method](https://tip.golang.org/pkg/hash/maphash/#Hash.Reset) documented as:

> Reset discards all bytes added to h. (The seed remains the same.) 

Moreover, the [`Sum64` doc](https://tip.golang.org/pkg/hash/maphash/#Hash.Sum64) says:

> Sum64 returns h's current 64-bit value, which **depends on h's seed and the sequence of bytes added to h since the last call to Reset**

So it appears it would be reasonable to expect this to print two times the same value:

```
package main

import (
	"fmt"
	"hash/maphash"
)

func main() {
	h := new(maphash.Hash)

	h.WriteString("hello")
	fmt.Printf("%#x\n", h.Sum64())

	h.Reset()

	h.WriteString("hello")
	fmt.Printf("%#x\n", h.Sum64())
}
```

But it doesn't:

```
$ gotip run hash.go
0xdf1aabcc36e56272
0x5a04b54a5a2174d6
```

This is because even if the seed remains the same and "all the previously added bytes are discarded", *the internal state of the Hash is maintained*, even after the `h.Reset()` call.

Is this the desired behaviour? If it is, the documentation should probably be amended to make it clear what to expect after a call to the `Reset` method.

cc @alandonovan @randall77

**Comment by vovapi** [comment]
There's seems to be a bug in a Hash because if you reset and hash again you'll get the same result as the second one:

```go
package main

import (
    "fmt"
    "hash/maphash"
)

func main() {
    h := new(maphash.Hash)

    h.WriteString("hello")
    fmt.Printf("%#x\n", h.Sum64()) // 0x48e0352e23362dd2

    h.Reset()

    h.WriteString("hello")
    fmt.Printf("%#x\n", h.Sum64()) // 0xf9395b015acc3ffb

    h.Reset()

    h.WriteString("hello")
    fmt.Printf("%#x\n", h.Sum64()) // 0xf9395b015acc3ffb
}
```

The first hash sum seems to be ignoring all the data that was put through it and returning sum as it has an empty state:

```go
package main

import (
    "fmt"
    "hash/maphash"
)

func main() {
    h1 := new(maphash.Hash)

    h1.WriteString("hello")
    sum1 := h1.Sum64() // first call on initSeed

    h1.Reset()

    fmt.Println(sum1 == h1.Sum64()) // true

    h2 := new(maphash.Hash)
    h2.SetSeed(h1.Seed())
    sum2 := h2.Sum64()

    fmt.Println(sum1 == sum2) // true
}
```

I think the issue is that the first Sum64 calls `initSeed`, which initializes the random seed using `SetSeed`. `SetSeed` discards previously written data.
