### ISSUE TITLE
fatal: morestack on g0 while running a server for half-year

### ISSUE THREAD

**Issue by absolute8511** [golang/go#37313]
### What version of Go are you using (`go version`)?

<pre>
go 1.10.8
</pre>

### What operating system and processor architecture are you using (`go env`)?
Linux 2.6.32-696.30.1.el6.x86_64

### What did you do?
We are running the nsq service for nearly half-year, suddenly we encounter the below fatal.  I saw many 
 copystack in some goroutines (some unrelated goroutines were removed),  I am not sure is there anything issue that many stacks grow may cause this problem? Any suggestion for this? Thank you.

<pre>
fatal: morestack on g0
SIGTRAP: trace trap
PC=0x457182 m=1 sigcode=128

goroutine 0 [idle]:
runtime.morestack()
        /opt/go/src/runtime/asm_amd64.s:451 +0x22

goroutine 1 [chan receive, 162478 minutes]:
github.com/youzan/nsq/vendor/github.com/judwhite/go-svc/svc.Run(0xd98fe0, 0xc42000c698, 0xc420119360, 0x5, 0x5, 0x1b, 0xd93d20)
        /data/gopath/src/github.com/youzan/nsq/vendor/github.com/judwhite/go-svc/svc/svc_other.go:30 +0x116
main.main()
        /data/gopath/src/github.com/youzan/nsq/apps/nsqd/nsqd.go:213 +0x153

goroutine 5 [syscall, 162478 minutes]:
os/signal.signal_recv(0x0)
        /opt/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
        /opt/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /opt/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 24574003807 [running]:
        goroutine running on other thread; stack unavailable
created by github.com/youzan/nsq/internal/protocol.TCPServer
        /data/gopath/src/github.com/youzan/nsq/internal/protocol/tcp_server.go:29 +0x1e6

goroutine 5734 [running]:
        goroutine running on other thread; stack unavailable
created by github.com/youzan/nsq/nsqd.NewChannel
        /data/gopath/src/github.com/youzan/nsq/nsqd/channel.go:241 +0x777

goroutine 24687137549 [copystack]:
github.com/youzan/nsq/nsqd.stepOffset(0xc49383fb00, 0x27, 0xcb582af920, 0x1e, 0x1e1, 0x4d87256, 0xbc32ec352, 0x81f8f7, 0x19a9, 0x1e1, ...)
        /data/gopath/src/github.com/youzan/nsq/nsqd/diskqueue_reader.go:507 +0x1052
github.com/youzan/nsq/nsqd.(*diskQueueReader).internalConfirm(0xcb661bcb00, 0xbc32edcfb, 0x81f8f8, 0x20, 0xc4d140)
        /data/gopath/src/github.com/youzan/nsq/nsqd/diskqueue_reader.go:615 +0x138
github.com/youzan/nsq/nsqd.(*diskQueueReader).ConfirmRead(0xcb661bcb00, 0xbc32edcfb, 0x81f8f8, 0x0, 0x0)
        /data/gopath/src/github.com/youzan/nsq/nsqd/diskqueue_reader.go:266 +0xae
github.com/youzan/nsq/nsqd.(*Channel).ConfirmBackendQueue(0xc42d188900, 0xc482484f00, 0x0, 0x0, 0xc482484f00)
        /data/gopath/src/github.com/youzan/nsq/nsqd/channel.go:874 +0x5de
github.com/youzan/nsq/nsqd.(*Channel).internalFinishMessage(0xc42d188900, 0x2970fe3, 0xcaa3f67d20, 0x13, 0x400000081f8f9, 0x0, 0x0, 0x0, 0x7f83d9666400, 0x0, ...)
        /data/gopath/src/github.com/youzan/nsq/nsqd/channel.go:1023 +0xada
github.com/youzan/nsq/nsqd.(*Channel).FinishMessageForce(0xc42d188900, 0x2970fe3, 0xcaa3f67d20, 0x13, 0x400000081f8f9, 0xc44e48b900, 0xd27c58, 0x1, 0x1d, 0xc44e48b9e0, ...)
        /data/gopath/src/github.com/youzan/nsq/nsqd/channel.go:971 +0x88
github.com/youzan/nsq/consistence.(*NsqdCoordinator).FinishMessageToCluster.func1(0xc434b58a20, 0xc4202c8200)
        /data/gopath/src/github.com/youzan/nsq/consistence/nsqd_coordinator_cluster_write.go:1098 +0xae
github.com/youzan/nsq/consistence.(*NsqdCoordinator).doSyncOpToCluster(0xc420342180, 0xc7ff15e400, 0xc4358ce400, 0xc4624920f0, 0xd2d898, 0xc57fb73600, 0xcb6d303468, 0xd2d8a0, 0xc7ff15e4e0, 0xcb6d303450, ...)
        /data/gopath/src/github.com/youzan/nsq/consistence/nsqd_coordinator_cluster_write.go:370 +0x207
github.com/youzan/nsq/consistence.(*NsqdCoordinator).FinishMessageToCluster(0xc420342180, 0xc42d188900, 0x2970fe3, 0xcaa3f67d20, 0x13, 0x400000081f8f9, 0xcb6d303500, 0xabd862)
        /data/gopath/src/github.com/youzan/nsq/consistence/nsqd_coordinator_cluster_write.go:1157 +0x3c7
github.com/youzan/nsq/nsqdserver.(*context).FinishMessage(0xc4202beac0, 0xc42d188900, 0x2970fe3, 0xcaa3f67d20, 0x13, 0x400000081f8f9, 0x1a, 0x1)
        /data/gopath/src/github.com/youzan/nsq/nsqdserver/context.go:226 +0x112
github.com/youzan/nsq/nsqdserver.(*protocolV2).FIN(0xc6f4b18cf0, 0xce093b6480, 0xc7ff15e4b0, 0x2, 0x2, 0x20, 0x1, 0xc43234de00, 0x300000002, 0xc43234de00)
        /data/gopath/src/github.com/youzan/nsq/nsqdserver/protocol_v2.go:1159 +0x328
github.com/youzan/nsq/nsqdserver.(*protocolV2).Exec(0xc6f4b18cf0, 0xce093b6480, 0xc7ff15e4b0, 0x2, 0x2, 0x20, 0x0, 0x2, 0x0, 0x0)
        /data/gopath/src/github.com/youzan/nsq/nsqdserver/protocol_v2.go:394 +0x1198
github.com/youzan/nsq/nsqdserver.(*protocolV2).IOLoop(0xc6f4b18cf0, 0xd9d7e0, 0xc6f4b18cd8, 0x4, 0xc499f13cb8)
        /data/gopath/src/github.com/youzan/nsq/nsqdserver/protocol_v2.go:272 +0x6e9
github.com/youzan/nsq/nsqdserver.(*tcpServer).Handle(0xc42aedb040, 0xd9d7e0, 0xc6f4b18cd8)
        /data/gopath/src/github.com/youzan/nsq/nsqdserver/tcp.go:48 +0x531
created by github.com/youzan/nsq/internal/protocol.TCPServer
        /data/gopath/src/github.com/youzan/nsq/internal/protocol/tcp_server.go:29 +0x1e6^@^@^@

goroutine 24687137727 [copystack]:
github.com/youzan/nsq/nsqd.stepOffset(0xc43a1fa120, 0x27, 0xc4944898a0, 0x1e, 0x1e1, 0x4d87256, 0xbc32ec352, 0x81f8f7, 0x19a9, 0x1e1, ...)
        /data/gopath/src/github.com/youzan/nsq/nsqd/diskqueue_reader.go:507 +0x1052
github.com/youzan/nsq/nsqd.(*diskQueueReader).internalConfirm(0xc6e2e11f00, 0xbc32edcfb, 0x81f8f8, 0x20, 0xc4d140)
        /data/gopath/src/github.com/youzan/nsq/nsqd/diskqueue_reader.go:615 +0x138
github.com/youzan/nsq/nsqd.(*diskQueueReader).ConfirmRead(0xc6e2e11f00, 0xbc32edcfb, 0x81f8f8, 0x0, 0x0)
        /data/gopath/src/github.com/youzan/nsq/nsqd/diskqueue_reader.go:266 +0xae
github.com/youzan/nsq/nsqd.(*Channel).ConfirmBackendQueue(0xc47df44d80, 0xc4eb87b2c0, 0x0, 0x0, 0xc4eb87b200)
        /data/gopath/src/github.com/youzan/nsq/nsqd/channel.go:874 +0x5de
github.com/youzan/nsq/nsqd.(*Channel).internalFinishMessage(0xc47df44d80, 0x2970fe2, 0xcaa3f67d00, 0x13, 0x400000081f8f9, 0x0, 0x0, 0x0, 0x7f83d9683d00, 0x0, ...)
        /data/gopath/src/github.com/youzan/nsq/nsqd/channel.go:1023 +0xada
github.com/youzan/nsq/nsqd.(*Channel).FinishMessageForce(0xc47df44d80, 0x2970fe2, 0xcaa3f67d00, 0x13, 0x400000081f8f9, 0xc85d614200, 0xd27c58, 0x1, 0x1d, 0xc85d6142c0, ...)
        /data/gopath/src/github.com/youzan/nsq/nsqd/channel.go:971 +0x88
github.com/youzan/nsq/consistence.(*NsqdCoordinator).FinishMessageToCluster.func1(0xc434b58a20, 0xc4202c8200)
        /data/gopath/src/github.com/youzan/nsq/consistence/nsqd_coordinator_cluster_write.go:1098 +0xae
github.com/youzan/nsq/consistence.(*NsqdCoordinator).doSyncOpToCluster(0xc420342180, 0xc8e0c6f100, 0xc4358ce400, 0xc4341d2b90, 0xd2d898, 0xc48820a830, 0xca4f9c5468, 0xd2d8a0, 0xc8e0c6f170, 0xca4f9c5450, ...)
        /data/gopath/src/github.com/youzan/nsq/consistence/nsqd_coordinator_cluster_write.go:370 +0x207
github.com/youzan/nsq/consistence.(*NsqdCoordinator).FinishMessageToCluster(0xc420342180, 0xc47df44d80, 0x2970fe2, 0xcaa3f67d00, 0x13, 0x400000081f8f9, 0xca4f9c5500, 0xabd862)
        /data/gopath/src/github.com/youzan/nsq/consistence/nsqd_coordinator_cluster_write.go:1157 +0x3c7
github.com/youzan/nsq/nsqdserver.(*context).FinishMessage(0xc4202beac0, 0xc47df44d80, 0x2970fe2, 0xcaa3f67d00, 0x13, 0x400000081f8f9, 0x0, 0x0)
        /data/gopath/src/github.com/youzan/nsq/nsqdserver/context.go:226 +0x112
github.com/youzan/nsq/nsqdserver.(*protocolV2).FIN(0xc6f4b18ce0, 0xc4f5872000, 0xc8e0c6f140, 0x2, 0x2, 0x20, 0x1, 0xc43ff0c180, 0x300000002, 0xc43ff0c180)
        /data/gopath/src/github.com/youzan/nsq/nsqdserver/protocol_v2.go:1159 +0x328
github.com/youzan/nsq/nsqdserver.(*protocolV2).Exec(0xc6f4b18ce0, 0xc4f5872000, 0xc8e0c6f140, 0x2, 0x2, 0x20, 0x0, 0x2, 0x0, 0x0)
        /data/gopath/src/github.com/youzan/nsq/nsqdserver/protocol_v2.go:394 +0x1198
github.com/youzan/nsq/nsqdserver.(*protocolV2).IOLoop(0xc6f4b18ce0, 0xd9d7e0, 0xce43ba13d0, 0x4, 0xc499f13c94)
        /data/gopath/src/github.com/youzan/nsq/nsqdserver/protocol_v2.go:272 +0x6e9
github.com/youzan/nsq/nsqdserver.(*tcpServer).Handle(0xc42aedb040, 0xd9d7e0, 0xce43ba13d0)
        /data/gopath/src/github.com/youzan/nsq/nsqdserver/tcp.go:48 +0x531
created by github.com/youzan/nsq/internal/protocol.TCPServer
        /data/gopath/src/github.com/youzan/nsq/internal/protocol/tcp_server.go:29 +0x1e6^@

goroutine 24808882062 [runnable]:
github.com/youzan/nsq/vendor/github.com/absolute8511/gorpc.(*Client).CallTimeout(0xc42b60e600, 0xb5d560, 0xc44bfb6ec0, 0xb2d05e00, 0x1, 0xcfa880, 0xa, 0xc433fc8ea0)
        /data/gopath/src/github.com/youzan/nsq/vendor/github.com/absolute8511/gorpc/client.go:240 +0x137
github.com/youzan/nsq/vendor/github.com/absolute8511/gorpc.(*DispatcherClient).CallTimeout(0xc42ba8cc20, 0xcfa880, 0xa, 0xb5b560, 0xc5557086e0, 0xb2d05e00, 0x410079, 0xc5557086e0, 0xb0, 0xa8)
        /data/gopath/src/github.com/youzan/nsq/vendor/github.com/absolute8511/gorpc/dispatcher.go:490 +0x106
github.com/youzan/nsq/vendor/github.com/absolute8511/gorpc.(*DispatcherClient).Call(0xc42ba8cc20, 0xcfa880, 0xa, 0xb5b560, 0xc5557086e0, 0xc42f83a400, 0x612810da6, 0x7f83d967fd58, 0x0)
        /data/gopath/src/github.com/youzan/nsq/vendor/github.com/absolute8511/gorpc/dispatcher.go:481 +0x66
github.com/youzan/nsq/consistence.(*NsqdRpcClient).CallWithRetry(0xc42addaf00, 0xcfa880, 0xa, 0xb5b560, 0xc5557086e0, 0x47fe82f, 0x612810da6, 0x2b9bc28, 0x0)
        /data/gopath/src/github.com/youzan/nsq/consistence/nsqd_rpc_client.go:157 +0xa3
github.com/youzan/nsq/consistence.(*NsqdRpcClient).PutMessage(0xc42addaf00, 0xc4606afdf0, 0xc4606afd40, 0x4000002b9bc29, 0x1, 0x4000002b9bc29, 0x612810b27, 0x27f, 0x2b9bc28, 0x1, ...)
        /data/gopath/src/github.com/youzan/nsq/consistence/nsqd_rpc_client.go:466 +0x124
github.com/youzan/nsq/consistence.(*NsqdCoordinator).internalPutMessageToCluster.func6(0xc42addaf00, 0xc4b900bdc0, 0x1c, 0xc4606afd40, 0x0)
        /data/gopath/src/github.com/youzan/nsq/consistence/nsqd_coordinator_cluster_write.go:164 +0x314
github.com/youzan/nsq/consistence.(*NsqdCoordinator).doSyncOpToCluster(0xc420342180, 0xc44b91ad01, 0xcbaa8ed000, 0xc476dbf9a0, 0xc49031f1c8, 0xc44b91acc0, 0xc49031f1e8, 0xc44b91acf0, 0xc44b91ad20,
0xc49031f1b0, ...)
        /data/gopath/src/github.com/youzan/nsq/consistence/nsqd_coordinator_cluster_write.go:436 +0x372
github.com/youzan/nsq/consistence.(*NsqdCoordinator).internalPutMessageToCluster(0xc420342180, 0xc486bc5a40, 0xca7251e780, 0xcd6a00, 0xca7251e780, 0x1166ec0, 0xed5df44e0, 0xbf8b7158220cc435, 0xbf8b
7158220cc435, 0x22a267031d8b3e, ...)
        /data/gopath/src/github.com/youzan/nsq/consistence/nsqd_coordinator_cluster_write.go:185 +0x57f
github.com/youzan/nsq/consistence.(*NsqdCoordinator).PutMessageToCluster(0xc420342180, 0xc486bc5a40, 0xca7251e780, 0x49d, 0xc78a6dcf04, 0xc45fdeea02, 0x20d, 0x6aa, 0xca7251e780, 0x1)
        /data/gopath/src/github.com/youzan/nsq/consistence/nsqd_coordinator_cluster_write.go:34 +0x48
github.com/youzan/nsq/nsqdserver.(*context).PutMessage(0xc4202beac0, 0xc486bc5a40, 0xc45fdeec0f, 0x51, 0x49d, 0xd96720, 0xc44bfb6ea0, 0x0, 0xc486bc5a40, 0x0, ...)
        /data/gopath/src/github.com/youzan/nsq/nsqdserver/context.go:196 +0x101
github.com/youzan/nsq/nsqdserver.(*protocolV2).internalPubExtAndTrace(0xc8572e03e0, 0xc98f9ef200, 0xc476dbf950, 0x3, 0x3, 0xcf0001, 0x0, 0x0, 0x0, 0x0, ...)
        /data/gopath/src/github.com/youzan/nsq/nsqdserver/protocol_v2.go:1597 +0xfe0
github.com/youzan/nsq/nsqdserver.(*protocolV2).PUBEXT(0xc8572e03e0, 0xc98f9ef200, 0xc476dbf950, 0x3, 0x3, 0x20, 0x1, 0xcf665ccf00, 0x300000002, 0xcf665ccf00)
        /data/gopath/src/github.com/youzan/nsq/nsqdserver/protocol_v2.go:1416 +0x64
github.com/youzan/nsq/nsqdserver.(*protocolV2).Exec(0xc8572e03e0, 0xc98f9ef200, 0xc476dbf950, 0x3, 0x3, 0x1, 0xc476dbf950, 0x3, 0x3, 0x0)
        /data/gopath/src/github.com/youzan/nsq/nsqdserver/protocol_v2.go:404 +0xeaa
github.com/youzan/nsq/nsqdserver.(*protocolV2).IOLoop(0xc8572e03e0, 0xd9d7e0, 0xc82ea68e00, 0x4, 0xc649498db8)
        /data/gopath/src/github.com/youzan/nsq/nsqdserver/protocol_v2.go:272 +0x6e9
github.com/youzan/nsq/nsqdserver.(*tcpServer).Handle(0xc42aedb040, 0xd9d7e0, 0xc82ea68e00)
        /data/gopath/src/github.com/youzan/nsq/nsqdserver/tcp.go:48 +0x531
created by github.com/youzan/nsq/internal/protocol.TCPServer
        /data/gopath/src/github.com/youzan/nsq/internal/protocol/tcp_server.go:29 +0x1e6

rbx    0xc4200c4000
rcx    0x45aa85
rdx    0x17
rdi    0x2
rsi    0xd0397a
rbp    0xc4200d2388
rsp    0xc4200d2350
r8     0xc709a20000
r9     0x1000
r10    0xec000
r11    0x202
r12    0x42f170
r13    0xf1
r14    0x11
r15    0x0
rip    0x457182
rflags 0x206
cs     0x33
fs     0x0
gs     0x0

</pre>

**Comment by davecheney** [comment]
This looks like memory corruption. Have you tried running your program under the race detector? See https://blog.golang.org/race-detector .

**Comment by absolute8511** [comment]
> This looks like memory corruption. Have you tried running your program under the race detector? See https://blog.golang.org/race-detector .

I have many unit tests running in race mode and found no race currently.

**Comment by davecheney** [comment]
Cool. Thanks for confirming.

**Comment by bcmills** [comment]
Half a year is about on par for memory corruption from thermal or cosmic-ray bit flips, especially depending on what kind of memory and CPU you're running on...

**Comment by bcmills** [comment]
Also note that (per https://golang.org/doc/devel/release.html#policy) Go 1.10.8 has not been supported since Go 1.12 was released (which was 2019-02-25).

Please let us know if you observe a similar failure using a supported release. (Note that Go 1.12 itself will become unsupported soon, when Go 1.14 is released.)

**Comment by tokers** [comment]
It seems the program called `runtime.morestack` on `g0` and ultimately got the error message "fatal: morestack on g0", which was written by `runtime.badmorestackg0` at asm_amd64.s:447(https://github.com/golang/go/blob/go1.10.8/src/runtime/asm_amd64.s#L447), while the trace tells us the position is asm_amd64.s:415, Which are contradictory with each other.

> goroutine 0 [idle]:
runtime.morestack()
        /opt/go/src/runtime/asm_amd64.s:451 +0x22

**Comment by tokers** [comment]
It seems the "g0" was trying to call the "runtime.morestack" and incurred an assertion failure.

**Comment by ianlancetaylor** [comment]
A g0 should never run out of stack space and should never call `morestack`.  Something has gone wrong.  If this is not repeatable, then I would suspect memory corruption.

(That said, it might perhaps be possible for a g0 to run out of stack space if there is a deeply recursive sequence of Go code calling C code calling Go code calling C code, etc.  I haven't tried.)

**Comment by absolute8511** [comment]
No cgo is used in this service.

**Comment by agnivade** [comment]
Please try again with 1.14 and let us know. If you see the exact same issue again, we can reopen this.
