### ISSUE TITLE
net/http/pprof: Index func does not set Content-Type header to text/html

### ISSUE THREAD

**Issue by eudore** [golang/go#37311]
### Does this issue reproduce with the latest release?

yes

### What did you do?

if global set response header `X-Content-Type-Options=nosniff`,pprof.Index response is text not is html in chrome.

read current [golang.org](https://golang.org/src/net/http/pprof/pprof.go?s=8810:8860#L254) net/http/pprof library sourcecode,pprof.Index func is not set header `content-type: text/html; charset=utf-8`,so chrome show is text.

------------ update ---------
my http server not is net/http.Server, will not defualt set content-type, so response does not exist context, and appear this error.

**Comment by eudore** [comment]
This issue has two conditions: add security header `X-Content-Type-Options` and not use net/http.Server(use Server will not add default `content-type: text/html; charset=utf-8`).

`X-Content-Type-Options` is security header not recommend add to pprof.Index, Because possible nginx proxy add the is header, Finally added two of this header.

No problem adding headers after testing,  Please consider not adding `X-Content-Type-Options` in pprof.Index

**Comment by hyangah** [comment]
@eudore I am afraid I don't understand what you want. My CL simply made the handler consistent with other existing handllers (Symbol, Profile, Trace, Cmdline, and error cases). If that's not what you want, send a PR with a clear explanation on why that's not desirable. Thanks.

**Comment by eudore** [comment]
only add header `content-type: text/html; charset=utf-8`, No need X-Content-Type-Options.

**Comment by eudore** [comment]
I think it's my server's default content-type problem, so I issue it off.
Thank you golang developers and supporters for their support.
