### ISSUE TITLE
x/blog: builds failing on release-branch.go1.12 due to missing dependencies

### ISSUE THREAD

**Issue by bcmills** [golang/go#37337]
In [CL 218517](https://golang.org/cl/218517), we added an external dependency to the `x/website` repo.

Somehow, that resulted in test failures for the `x/blog` repo (https://build.golang.org/log/c8db93d879bffec55c15c341dc5082bdde79a770):
```
../website/markdown/markdown.go:16:2: cannot find package "github.com/yuin/goldmark" in any of:
	/workdir/go/src/github.com/yuin/goldmark (from $GOROOT)
	/workdir/gopath/src/github.com/yuin/goldmark (from $GOPATH)
../website/markdown/markdown.go:17:2: cannot find package "github.com/yuin/goldmark/renderer/html" in any of:
	/workdir/go/src/github.com/yuin/goldmark/renderer/html (from $GOROOT)
	/workdir/gopath/src/github.com/yuin/goldmark/renderer/html (from $GOPATH)
```

It appears that the `x/blog` tests on `release-branch.go1.12` are not running in module mode. They probably should be.

CC @jayconrod @dmitshur @cagedmantis @toothrot

**Comment by dmitshur** [comment]
golang.org/x repos are intentionally tested in GOPATH mode on release-branch.go1.12 branches, and in module mode (as long as a go.mod file is present) on release-branch.go1.13 branches and newer.

Third-party packages in golang.org/x repos are only supported in module mode.

No packages in x/blog import x/website/markdown package yet, so it's strange that it is attempted to be built in GOPATH mode. Need to understand why that is.

**Comment by dmitshur** [comment]
Okay, the `golang.org/x/website/content/static` package imports `x/website/markdown`, and `x/blog` imports `golang.org/x/website/content/static`.

**Comment by jayconrod** [comment]
> Builders have support for testing with third-party packages in golang.org/x repos only in module mode.

How does the builder set up the workspace? I assumed the builder would `go get` the packages to be tested, but when I tried that locally with Go 1.12.17, it checked out `github.com/yuin/goldmark`, and I didn't run into any error with the `go test` command.

> No packages in x/blog import x/website/markdown package yet, so it's strange that it is attempted to be built in GOPATH mode. Need to understand why that is.

I didn't think about this when I added the Markdown rendering, but `content/static/gen.go` is not excluded by build constraints, so `golang.org/x/website/markdown` is imported by the regular version of `golang.org/x/website/content/static`.

Perhaps instead, all the generator code should be moved from `gen.go` to `makestatic.go`. `gen.go` should just have a `//go:generate` pragma.

**Comment by dmitshur** [comment]
> How does the builder set up the workspace?

Answered in person, but for posterity, the code is in [`buildStatus.runSubrepoTests`](https://github.com/golang/build/blob/b077d0cce971fb98919ea3514515f8d08750a600/cmd/coordinator/coordinator.go#L2564) of [cmd/coordinator](https://pkg.go.dev/golang.org/x/build/cmd/coordinator).
