### ISSUE TITLE
Install Go modules from downloads 

### ISSUE THREAD

**Issue by clevere** [golang/go#37339]
Go version: 1.13
OS/Arch: Windows 10/AMD_64

Note: I am unable to use Go itself to download dependencies, the workstation firewall whitelists apps with Internet access and what sites they can access. Go is not whitelisted (and Git can't access googlecode sites either). My only means of downloading dependencies is via web browser.

Steps:
1. download the zip file for the dependency from Github
2. unzip the download into $GOPATH/src/<company>/<package>
3. switch into $GOPATH/src/<company>/<package>
4. run "go install"
5. switch to project repo under $GOPATH/src/project
6. run "go build"

I expect the project to have everything it needs to start compiling. Instead, it tries to download dependencies and times out because Internet access is blocked.

This is a problem I've solved for Python, Perl, and a few others when I've needed to. I would give up, but the only software that does what what I need is written in Go, and I don't have Red Hat package to install.

**Comment by bcmills** [comment]
In theory, at least, you can download the `.info`, `.mod`, and `.zip` files yourself from https://proxy.golang.org and hand-place them into a `GOPROXY` directory. See https://tip.golang.org/cmd/go/#hdr-Module_proxy_protocol.

That said, for a typical program you would need to download and place a _lot_ of module dependencies. It may be more effective to get your IT operator to whitelist the `go` command for access to `https://proxy.golang.org` and `https://sum.golang.org`.

Since this is a local firewall problem rather than a bug in the `go` command, we don't plan to address this within the Go project. Sorry.

(CC @jayconrod @matloob)

**Comment by clevere** [comment]
More people have limited Internet access, than work in shops where they can download anything they want on a whim:

- corporate developers
- people in 3rd world countries who go to an Internet cafe with a thumb drive to download
- kids behind school firewalls

At least give us a straightforwardly documented workaround.

**Comment by bcmills** [comment]
The documented workaround is to use a `GOPROXY`.

For corporate developers and kids behind school firewalls, if your IT department wants you to be able to download Go modules, then they can run a proxy that supplies only their approved modules. If they want you to be able to download anything at all, then they can allow access to `proxy.golang.org`.

Folks who go to an Internet cafe can run `go mod download` to populate the local module cache.

**Comment by clevere** [comment]
There are modules for which I don't find any data in proxy.golang.org.  The documentation says, "GET $GOPROXY/<module>/@v/list returns a list of known versions of the given module, one per line."

However, https://proxy.golang.org/github.com/anmitsu/go-shlex/@v/list returns an empty (zero bytes) page. However, https://github.com/anmitsu/go-shlex is a real Go module.

I see this in the documentation, however: Even when downloading directly from version control systems, the go command synthesizes explicit info, mod, and zip files and stores them in its local cache, $GOPATH/pkg/mod/cache/download, the same as if it had downloaded them directly from a proxy. The cache layout is the same as the proxy URL space, so serving $GOPATH/pkg/mod/cache/download at (or copying it to) https://example.com/proxy would let other users access those cached module versions with GOPROXY=https://example.com/proxy. 

So my question is: given a zip file, what must I do to synthesize the info and mod files?

Side note:
- If IT department (of which I am a member) didn't want me downloading open source software at all, I wouldn't have browser access to Github at all. Or Gitlab. Or any of a few hundred other sites.
- No Internet cafe owner in their right mind lets users install their own software, so `go mod download` isn't a thing for those users either.
- I can automate the download and placement of as many module dependencies as I want. I just can't do it with `go get`. That's what Selenium and Python are for.

**Comment by Manuthor** [comment]
I agree with @clevere "So my question is: given a zip file, what must I do to synthesize the info and mod files?".

Any chance to have an update on this?
