### ISSUE TITLE
strings: Docs & Examples unclear about difference between ToTitle and ToUpper

### ISSUE THREAD

**Issue by dionysius** [golang/go#37334]
### What version of Go are you using (`go version`)?

The current documentation on https://golang.org/pkg/strings/

### Does this issue reproduce with the latest release?

Yes, using the examples inside the strings package documentation

### What operating system and processor architecture are you using (`go env`)?

None providable

### What did you do?

Copied `strings.ToTitle` example to `strings.ToUpper` and changed `ToTitle()` to `ToUpper()`:
```
package main

import (
	"fmt"
	"strings"
)

func main() {
	fmt.Println(strings.ToUpper("her royal highness"))
	fmt.Println(strings.ToUpper("loud noises"))
	fmt.Println(strings.ToUpper("хлеб"))
}
```

### What did you expect to see?

A difference in output.

### What did you see instead?

Example ToTitle (unmodified) outputs:
```
HER ROYAL HIGHNESS
LOUD NOISES
ХЛЕБ
```

Example ToUpper (modified as described above) outputs:
```
HER ROYAL HIGHNESS
LOUD NOISES
ХЛЕБ
```

No difference. So for me it is unclear which function is now the correct one to use for an imaginary case.

**Comment by dionysius** [comment]
Or in other words:
```
package main

import (
	"fmt"
	"strings"
)

func main() {
	a := strings.ToTitle("her royal highness, loud noises, хлеб")
	b := strings.ToUpper("her royal highness, loud noises, хлеб")
	fmt.Println(a == b)
}

// outputs:
// true
```

Document an example that can help the user decide which function is the right one to use for his case

**Comment by toothrot** [comment]
Title case and Upper case of a character have distinct definitions in unicode to allow for specific characters that have distinctive differences: https://unicode.org/faq/casemap_charprop.html#4

ǳ, in latin, is one for example: http://www.fileformat.info/info/unicode/char/01f3/index.htm

It's hard to find a good example to add that doesn't add confusion to people who aren't already familiar with this feature of unicode.

```go
package main

import (
	"fmt"
	"strings"
)

func main() {
	fmt.Println(strings.ToUpper("ǳz")) // ǱZ
	fmt.Println(strings.ToTitle("ǳz")) // ǲZ
}
```

What would you suggest?

/cc @griesemer

**Comment by griesemer** [comment]
Assigned to @mpvl who is our local Unicode expert.

**Comment by dionysius** [comment]
> It's hard to find a good example to add that doesn't add confusion to people who aren't already familiar with this feature of unicode.

True! After thinking about it for a short while I know what the difference means now as well. I thought, why not help and raise an small issue to make the difference a little more clear in the docs to be - in the future - quicker to decide what to use for a specific case.

I think just add a little ToTitle specific string for the ToTitle example and we're good to go.

**Comment by fenollp** [comment]
Quoting https://unicode.org/faq/casemap_charprop.html#4 (@toothrot's link):
> Titlecase is also used in forming a sentence by capitalizing the first word, and for forming proper names.
> The titlecase mapping in the Unicode Standard is the __mapping applied to the initial character in a word__.

(emphasis mine)

To recap: `strings.Title()` (which mapped on words) is deprecated and replaced with `strings.ToTitle()` which maps on letters.
Why was it named `ToTitle` when it seems to not even match the Unicode description?

**Comment by ianlancetaylor** [comment]
`strings.Title` is not being replaced by `strings.ToTitle`.  Those two functions do different things.

**Comment by dionysius** [comment]
Hi all, I didn't plan go leave this issue open. Don't know why I reopened it. I suggest to open a new one and link to this if needed.
