### ISSUE TITLE
cmd/compile: illegal instruction (core dumped) on FreeBSD ARM64

### ISSUE THREAD

**Issue by artooro** [golang/go#37345]
### What version of Go are you using? 1.14rc1

<pre>
go version go1.14rc1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/artooro/Library/Caches/go-build"
GOENV="/Users/artooro/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/artooro/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9z/jlqzn0wj4g12dg0ykj78dyph0000gn/T/go-build674964893=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

This can be reproduced by a very basic program, for example:

```
package main

import "fmt"

func main() {
	fmt.Println("Hello world")
}
```

Compile with the following environment variables.

```
GOOS=freebsd
GOARCH=arm64
```

Tried to run it on a Marvell Armada 3720LP (88F3720) dual core ARM Cortex A53.

### What did you expect to see?

For the program to print "Hello World"

### What did you see instead?

I get the following output: `Illegal instruction (core dumped)`

Here is the core dump file of that test program.
[testfreebsdarm64.core.zip](https://github.com/golang/go/files/4233397/testfreebsdarm64.core.zip)

**Comment by ianlancetaylor** [comment]
Can you run the program under gdb to find out exactly what the illegal instruction is?

**Comment by bcmills** [comment]
See also #35851 (`SIGILL` on `darwin/arm64`).

**Comment by artooro** [comment]
@ianlancetaylor when running in gdb here is the output.

```
(gdb) source go/src/runtime/runtime-gdb.py
Loading Go Runtime support.
(gdb) run
Starting program: /root/testfreebsdarm64 

Program received signal SIGILL, Illegal instruction.
runtime.getisar0 () at /usr/local/go/src/runtime/sys_freebsd_arm64.s:522
522	/usr/local/go/src/runtime/sys_freebsd_arm64.s: No such file or directory.
```

**Comment by ianlancetaylor** [comment]
Thanks.  Please use `x/i $pc` to see the exact instruction.

**Comment by artooro** [comment]
Ok I think this is what you're looking for.

```
(gdb) x/i $pc
=> 0x66030 <runtime.getisar0>:	mrs	x0, id_aa64isar0_el1
```

Sorry my first time using gdb.

**Comment by ianlancetaylor** [comment]
Thanks.

Does anybody know why that instruction would trigger an illegal instruction interrupt?  As far as I can tell it should be supported on any ARMv8 processor.  Is it a privileged instruction?

CC @cherrymui @4a6f656c @tklauser @4ad

**Comment by cherrymui** [comment]
Reading the manual, it looks to me the register id_aa64isar0_el1 is privileged. It seems accessing the register is user mode is "UNDEFINED". Maybe @zhangfannie can confirm.

**Comment by ianlancetaylor** [comment]
CC @Mikaelurankar @bsd-hacker @myfreeweb

**Comment by MikaelUrankar** [comment]
yes, id_aa64isar0_el1 is privileged. The FreeBSD kernel traps the exception and returns correct values to userland (at least on "recent" version of FreeBSD, I think it appears in FreeBSD 12.0, not sure it works in 11.x)
@artooro, what version do you run?

**Comment by myfreeweb** [comment]
Yes, it appears in 12.0.

12.0 also introduced the 64-bit-inodes ABI, and IIRC go uses it, not the legacy one. So forget about 11.x and older.

**Comment by zhangfannie** [comment]
@cherrymui yes, id_aa64isar0_el1 is not accessible in user mode.

**Comment by shawn-xdji** [comment]
could the 'features' of /proc/cpuinfo be shared? Thanks.

**Comment by MikaelUrankar** [comment]
What's /proc/cpuinfo?

**Comment by tklauser** [comment]
`/proc/cpuinfo` is only available on Linux, not on FreeBSD.

**Comment by shawn-xdji** [comment]
> `/proc/cpuinfo` is only available on Linux, not on FreeBSD.

Thanks a lot, I've no idea of the difference.

Out of curiosity, does FreeBSD kernel have the same feature of 'mrs emulation' as linux's, a similar issue could be reproduced on an arm64 machine with linux kernel before 4.10 where the feature is not present, a higher version works fine.

**Comment by myfreeweb** [comment]
@shawn-xdji yes! @MikaelUrankar mentioned this above!!! This is why the register is read.

> linux kernel before 4.10

And for FreeBSD that version is 12.0.

Which as I already mentioned is the minimum version **for other reasons too**.

**Comment by ianlancetaylor** [comment]
@artooro What version of FreeBSD are you using?

**Comment by ianlancetaylor** [comment]
Would somebody who understands the details like to update https://golang.org/wiki/MinimumRequirements?  Thanks.

**Comment by artooro** [comment]
@ianlancetaylor yeah I'm using 11.3 so yeah if it requires FreeBSD 12.0+ that would explain things.

**Comment by tklauser** [comment]
Given that the originally reported problem occurs on FreeBSD 11.3 and we now explicitly document that `freebsd/arm64` is only supported on FreeBSD 12.0 and later, I think we can close this.
