### ISSUE TITLE
go/types: reported type of call to make() depends on whether argument is a const or var

### ISSUE THREAD

**Issue by benjaminjkraft** [golang/go#37349]
(Issue template below; in short this repros on 1.13 and tip.)

The [documentation of `go/types`](https://godoc.org/go/types#Info) says:
```
    // For (possibly parenthesized) identifiers denoting built-in
    // functions, the recorded signatures are call-site specific:
    // if the call result is not a constant, the recorded type is
    // an argument-specific signature. Otherwise, the recorded type
    // is invalid.
```

For `make()` the signature seems a bit _too_ call-site specific: it depends on whether the len and cap arguments are consts or vars.  If the arguments are constant (e.g. `make([]int, 10)`), the type is something plausible: `func([]int, int) []int`.  But if an argument is a variable (e.g. `var length = 10; make([]int, 10)`) the type is different, and strange: `func([]int) []int`.  In particular, while it's arguable whether any of these types "make sense", this means the (non-variadic) function has more arguments than its supposed type's parameters, which is confusing to a static analysis.  (Of course, Go itself is fine with it.)

The following [more complete example](https://play.golang.org/p/GYZrAdOnfff) repros on both play.golang.org and tip.golang.org.

It looks like this issue goes all the way back to https://github.com/golang/tools/commit/0c4522091728c38bf1b9f0ddb94376d08a2be22a when this behavior of `go/types` was added -- in the [code](https://github.com/golang/go/blob/master/src/go/types/builtins.go#L444) `sizes` is the number of _constant_ arguments.

I'm not sure if fixing this would be considered a compatibility break; if not it could be documented as a bug.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 linux/amd64
</pre>
(also repros on tip.golang.org)

### Does this issue reproduce with the latest release?
yes, latest and tip

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/benkraft/.cache/go-build"
GOENV="/home/benkraft/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/benkraft/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/benkraft/<redacted>/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/g
o-build562912148=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/GYZrAdOnfff

### What did you expect to see?

```
builtin make has type func([]int, int, int) []int
builtin make has type func([]int, int, int) []int
builtin make has type func([]int, int, int) []int
builtin make has type func([]int, int, int) []int
```

### What did you see instead?

```
builtin make has type func([]int, int) []int
builtin make has type func([]int) []int
builtin make has type func([]int, int) []int
builtin make has type func([]int, int, int) []int
```

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by griesemer** [comment]
This is just a bug. Fix forthcoming.

Also, it turns out that it doesn't report the correct types for non-constant non-integer arguments. Filed separate issue #37393 .
