### ISSUE TITLE
x/crypto/argon2: argument memory should be defined like uint64

### ISSUE THREAD

**Issue by tredoe** [golang/go#37356]
The argument 'memory' at both functions 'IDKey' and 'Key' has been defined using an uint32, but it is insufficient to set a memory of at least 4GB. (https://pkg.go.dev/golang.org/x/crypto/argon2)

And like it is indicated at the [RFC](https://tools.ietf.org/html/draft-irtf-cfrg-argon2-08#section-4), it is suggested:

> Backend server authentication, that takes 0.5 seconds on a
> 2 GHz CPU using 4 cores
> -- Argon2id with 8 lanes and 4 GiB of RAM.

>  Key derivation for hard-drive encryption, that takes
> 3 seconds on a 2 GHz CPU using 2 cores
> -- Argon2id with 4 lanes and 6 GiB of RAM.

**Comment by renthraysk** [comment]
Memory parameter is in KiB not bytes. 
4GiB / 1024 fits in an uint32.

"The time parameter specifies the number of passes over the memory and the memory parameter specifies the **size of the memory in KiB**. For example memory=64*1024 sets the memory cost to ~64 MB. The number of threads can be adjusted to the numbers of available CPUs. The cost parameters should be increased as memory latency and CPU parallelism increases. Remember to get a good random salt." 
https://pkg.go.dev/golang.org/x/crypto/argon2?tab=doc
