### ISSUE TITLE
x/tools/gopls: 5x slowdown in cmd tests

### ISSUE THREAD

**Issue by findleyr** [golang/go#37365]
While investigating #37318, I noticed that tests for golang.org/x/tools/internal/lsp/cmd were also timing out.  For example: https://build.golang.org/log/a7e57b48b2eb87387651b04e268638d5b1b25f9d

Looking into *this*, it appears that cmd tests got significantly slower recently.  Bisecting, it looks like this is a result of https://github.com/golang/tools/commit/6dcdf1db2c06ad0ebe311c58b8cda17392eb42c2.  These tests went from ~6s to ~30s on my workstation.  That's surprising.

```
[nyc:tools2]> go test -count=1 ./internal/lsp/cmd                                                                     
ok      golang.org/x/tools/internal/lsp/cmd     5.937s                                                                
[nyc:tools2]> git bisect good                                                                                         
6dcdf1db2c06ad0ebe311c58b8cda17392eb42c2 is the first bad commit
commit 6dcdf1db2c06ad0ebe311c58b8cda17392eb42c2
Author: Rebecca Stambler <rstambler@golang.org>
Date:   Thu Jan 30 21:29:41 2020 -0500
                                                           
    internal/lsp/cache: refactor functions that return PackageHandles
```

CC @stamblerre @ianthehat

**Comment by findleyr** [comment]
Highlight tests appear to be the main contributors to the slowdown. For example:
```
nyc:tools2]> go test -run=TestCommandLine/Modules/../testdata/lsp/Highlight -count=1 ./internal/lsp/cmd
ok      golang.org/x/tools/internal/lsp/cmd     12.115s
[nyc:tools2]> git checkout HEAD~1
Previous HEAD position was 6dcdf1db internal/lsp/cache: refactor functions that return PackageHandles
HEAD is now at 009580c4 internal/lsp/source: export FindFileInpackage
[nyc:tools2]> go test -run=TestCommandLine/Modules/../testdata/lsp/Highlight -count=1 ./internal/lsp/cmd
ok      golang.org/x/tools/internal/lsp/cmd     2.363s
```

**Comment by ridersofrohan** [comment]
`go test -run=TestCommandLine/Modules/../testdata/lsp/Highlight -count=1 ./internal/lsp/cmd`

Ran this test with some logging to see how long segments of code take to run and the part that takes up the most amount of time is running packages.load, which takes on average 200ms. The main difference is that now running this test calls packages.load 52 times, once for each highlight marker.
