### ISSUE TITLE
cmd/compile/internal/ssa: occasional "exit status 541111823" on windows-386-2008 builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#37360]
```
#!watchflakes
post <- `exit status 541111823`
```

The test for `cmd/compile/internal/ssa` occasionally exits with status `541111823` (and no other output) on the `windows-386-2008` builder:
[2020-02-21T01:48:01-1bc116b/windows-386-2008](https://build.golang.org/log/1bfd9ebef52bd164184c9643bc3302b1bf009e1d)
[2020-01-09T19:50:42-10bfe5b/windows-386-2008](https://build.golang.org/log/26a6b76c4d384b6780473f9b670b8ac0044df887)

I wonder if perhaps it is running out of address space? I seem to recall that that test is one of the most memory-intensive in the standard library.

CC @dmitshur @cagedmantis @toothrot @alexbrainman @networkimprov @randall77 @josharian @martisch

**Comment by josharian** [comment]
Alex, do you know what that exit code means? Googling yields no results.

Possibly related: https://github.com/golang/go/issues/36309. The problem there appeared to have been compiling the test; the changes that I just submitted over the last day or so fixed it in that issue by reducing memory required to build package ssa.

If it keeps happening, it’d be useful to know what’s happening when it fails—compiling the test, running the test (which one), etc.

**Comment by networkimprov** [comment]
cc @zx2c4 @mattn

**Comment by alexbrainman** [comment]
> I wonder if perhaps it is running out of address space?

I tried running this test on my computer. And its memory usage does not look any different from any other Go program. I uses Task Manager to view memory performance.

```
c:\Users\Alex\dev\go\src>go version
go version devel +ebe49b2c29 Sun Feb 23 01:23:41 2020 +0000 windows/386

c:\Users\Alex\dev\go\src>go test -short -count=1 cmd/compile/internal/ssa
ok      cmd/compile/internal/ssa        0.428s

c:\Users\Alex\dev\go\src>go test -short -count=10 cmd/compile/internal/ssa
ok      cmd/compile/internal/ssa        3.165s
```

> Alex, do you know what that exit code means? Googling yields no results.

I don't know. Unfortunately. Usually exit code corresponds to some real Windows error number. But this one does not look like an error number.

I am out of ideas. Sorry.

Alex

**Comment by bcmills** [comment]
[2020-04-15T03:25:21-8f53fad/windows-386-2008](https://build.golang.org/log/2a40558c6b8c696f2d0bc35b4cd977c792044897)
[2020-04-13T17:38:02-614a713/windows-386-2008](https://build.golang.org/log/01fa0f5c8b9a8e37c4e82e35ddb8ad6d1733456f)
[2020-04-12T15:37:29-3afa741/windows-386-2008](https://build.golang.org/log/04b7adcb19409fd35d8544067b069fe5712ca040)
[2020-03-24T00:04:19-6a9d850/windows-386-2008](https://build.golang.org/log/399f51aee283beb2e42fce7e9df53224efa58916)

And none from before 2020-01-09.
