### ISSUE TITLE
cmd/go: inconsistency when go build -o is a file or directory

### ISSUE THREAD

**Issue by perillo** [golang/go#37379]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14rc1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/manlio/.local/bin"
GOCACHE="/home/manlio/.cache/go-build"
GOENV="/home/manlio/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/manlio/.local/lib/go:/home/manlio/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/manlio/sdk/go1.14rc1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/manlio/sdk/go1.14rc1/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build934357574=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.14rc1 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.14rc1
uname -sr: Linux 5.5.4-arch1-1
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.31.
gdb --version: GNU gdb (GDB) 9.1
</pre></details>

### What did you do?

`go build -o path` behave differently when `path` is a file or directory.

As an example, `go build -o file ./pkg`, will build an executable if `pkg` is a *main* package or an archive otherwise.

On the other hand, `go build -o dir ./...`, will build all the *main* packages, saving the files in the build directory, using the last segment of the *importpath* as the name.  This is done **even** if two executable happen to have the same name, without any notice.

For consistency, `go build -o dir ./...` should save the archive files in the build directory, when processing non *main* packages, using the same algorithm used for *main* packages.

I suspect that building an archive file is here only for compatibility reason.

**Comment by bcmills** [comment]
CC @jayconrod @matloob

**Comment by bcmills** [comment]
> This is done even if two executable happen to have the same name, without any notice.

That seems like an independent bug. File it as a separate issue?

**Comment by bcmills** [comment]
> For consistency, `go build -o dir ./...` should save the archive files in the build directory, when processing non main packages, using the same algorithm used for main packages.

I don't think I understand what you mean. Do you expect `go build` to write archive files into `dir`, or to build the archive files but not copy them in?

More generally (and following https://github.com/golang/go/issues/36784#issuecomment-583498323): what is the concrete problem that you're trying to address where the current behavior of the `-o` flag is causing trouble?
