### ISSUE TITLE
cmd/asm: riscv64 assembler claims that 4294967295 does not fit in 32 bits

### ISSUE THREAD

**Issue by josharian** [golang/go#37382]
After some compiler tweaks, I got this complaint out of the RISCV64 assembler:

```
# cmd/compile/internal/ssa
cmd/compile/internal/ssa/compile.go:429:45: 00038 (/Users/josh/go/tip/src/cmd/compile/internal/ssa/regalloc.go:2555)	MOV	$4294967295, X3: constant 4294967295 too large: immediate does not fit in 32-bits: 4294967295
cmd/compile/internal/ssa/compile.go:429:45: 00068 (/Users/josh/go/tip/src/cmd/compile/internal/ssa/regalloc.go:2636)	MOV	$4294967295, X3: constant 4294967295 too large: immediate does not fit in 32-bits: 4294967295
```

But 4294967295 does fit (barely!) in 32 bits. So either the error message is wrong, or the instruction should get encoded.

(My compiler changes aren't ready to share, but you should be able to reproduce just with assembly.)

cc @4a6f656c

**Comment by robpike** [comment]
Not only that, the message has bad grammar: s/32-bits/32 bits/
src/cmd/internal/obj/riscv/obj.go:884

The test seems to think you have a signed immediate, in which case the error is correct, if poorly worded.

**Comment by mengzhuo** [comment]
This issue fixed by https://go-review.googlesource.com/c/go/+/345050, closed
