### ISSUE TITLE
Go get not working

### ISSUE THREAD

**Issue by saloni61** [golang/go#37389]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.8 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
don't know

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\my\AppData\Local\go-build
set GOENV=C:\Users\my\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\myProj
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\saloni\AppData\Local\Temp\go-build955997130=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
go get github.com/gorilla/websocket

### What did you expect to see?

install successfully

### What did you see instead?

```
go get github.com/gorilla/websocket
# cd .; git clone -- https://github.com/gorilla/websocket E:\myProj\src\github.com\gorilla\websocket
Cloning into 'E:\myProj\src\github.com\gorilla\websocket'...
fatal: unable to access 'https://github.com/gorilla/websocket/': getaddrinfo() thread failed to start

package github.com/gorilla/websocket: exit status 128
```

**Comment by sidharth-tp** [comment]
For me this is working fine

**Comment by ALTree** [comment]
Hi,

this is an issue with git and your internet connection, not a Go problem. See for example:
https://stackoverflow.com/questions/59517290/getting-access-denied-while-cloning-using-git-clone-command

Closing here, since this is not a Go bug.
