### ISSUE TITLE
x/net: ipv4 header total length on GOOS darwin is incorrectly marshaled

### ISSUE THREAD

**Issue by pete911** [golang/go#37398]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.8 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.8/libexec"
GOSUMDB="sum.golang.org"
GOTOOLDIR="/usr/local/Cellar/go/1.13.8/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
</pre></details>

### What did you do?
Set the ipv4 header total length field

```
// ...

iph := &ipv4.Header{
	Version:  ipv4.Version,
	Len:      ipv4.HeaderLen,
	TOS:      0,
	TotalLen: ipv4.HeaderLen + len(msg),
	TTL:      64,
	Protocol: protocol,
	Dst:      dst,
	Src:      src,
}

ip, _ := iph.Marshal()

// ... packet has incorrectly set total length - ip[2:4] bytes are reversed
```

### What did you expect to see?
for example if packet total length is `37` I expect to see `[0 37]` set on byte index 2 and 3 (`ip[2:4]`)

### What did you see instead?
for example if packet total length is `37` I see `[37 0]` set on byte index 2 and 3 (`ip[2:4]`)

**Comment by vovapi** [comment]
I think this duplicates #32118

**Comment by pete911** [comment]
thanks @vovapi , it is indeed duplicate. closing this issues.
