### ISSUE TITLE
go.dev: documentation font is not user friendly towards dyslexic people

### ISSUE THREAD

**Issue by empijei** [golang/go#37411]
### What is the URL of the page with the issue?
 Any godoc page with code examples e.g. https://pkg.go.dev/golang.org/x/net/html?tab=doc
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/1256049/75165559-deff4f80-5722-11ea-990d-05bd2a950510.png)

### What did you do?
Visited the page
 
### What did you expect to see?
Docs in a font I can read
 
### What did you see instead?
Docs in a font I can't read.

Serifs and small kerning can make it much harder for dyslexic users to read text. The new style of godoc makes it worse than it used to be, which was already pretty tough to read.

This only affect code blocks as they are the only ones with little kerning and serifs.

/cc @julieqiu

**Comment by empijei** [comment]
Was the font changed recently? It looks like it now renders with Source Code Pro instead of Go Mono. If so thank you, this is much better to read.

**Comment by andybons** [comment]
If Go Mono is not installed on your system, it falls back to Source Code Pro. That could be why you’re seeing it rendered that way.

**Comment by julieqiu** [comment]
@empijei we plan to change the default font to `Source Code Pro` to improve readability. The change should be live in the next deployment. Glad to hear it would create a better experience!

**Comment by empijei** [comment]
Thank you so much for this!

**Comment by julieqiu** [comment]
Fixed.
