### ISSUE TITLE
cmd/go: using go get to install new versions of go doesn't seem to work

### ISSUE THREAD

**Issue by superlazyname** [golang/go#37428]
From this docs page,

https://golang.org/doc/install#extra_versions

>  It may be useful to have multiple Go versions installed on the same machine, for example, to ensure that a package's tests pass on multiple Go versions. Once you have one Go version installed, you can install another (such as 1.10.7) as follows:
> ```
> $ go get golang.org/dl/go1.10.7
> $ go1.10.7 download
> ```

Note: I ran all of these commands as root, this shouldn't be a permissions issue.

I attempted to install go1.12.17 via go 1.10.1, using the guide in the wiki.

I attempted to run `go get golang.org/dl/go1.12.17`, it completed without any message (error or otherwise), however it didn't seem to do anything.

- Attempting `go1.12.17 download` gives me `bash: go1.12.17: command not found`.
- `which go1.12.17` comes back with no results
- There appears to be nothing new in /usr/bin/, /usr/local/bin/, and no files have been downloaded to the directory I'm in
- `go version` shows that it's still running `go version go1.10.1 linux/386`

On a whim I tried installing something older thinking maybe this command only works for downgrading go, but attempting to install go1.9.1 gave me the same result.

If it matters, go1.10.1 is from apt, I'm running Ubuntu 18.04; the `go get` method for installing multiple go versions sounds handy but I'm OK with uninstalling the official go version from Canonical and getting a different version from a PPA, that was my fix for this previously.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="386"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_386"
GCCGO="gccgo"
GO386="387"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build682500140=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

**Comment by superlazyname** [comment]
It looks like the `go get` command downloaded the file to `/root/go/bin`, and that folder wasn't added to path.

It might be worth adding this destination path to the docs, or maybe having the `go get` command say where the binary was saved. The go download command worked properly after I was able to find the go1.12.17 executable. It's a bit confusing because `which go` goes to `/usr/bin/go`, not `/home/root/go`.

**Comment by seankhliao** [comment]
`go get` downloads to `$GOPATH/bin` as usual, if you had `$GOPATH/bin` in `$PATH` (as is recommended) and ran it as a normal user it would have worked (for your user, `go get` is not a replacement for global installs)

**Comment by superlazyname** [comment]
Understood, thanks.

- Is it normal to have go in both /usr/bin/go and ~/go or is that an apt package quirk? 
- Do typical installs only have go in ~/go? It seems like that's an easier route.

**Comment by cagedmantis** [comment]
Hi @superlazyname. This seems like it's working as expected. Please comment if you disagree. I will be closing the issue.

**Comment by mitar** [comment]
I had the same problem.

> if you had $GOPATH/bin in $PATH (as is recommended)

Where it is recommended? Not in [getting started doc](https://golang.org/doc/install). If you follow just instructions there, on Linux, you do:

* Run `tar -C /usr/local -xzf go$VERSION.$OS-$ARCH.tar.gz`
* Add `export PATH=$PATH:/usr/local/go/bin` to `.profile`, which makes `go` work great.
* Then you do `go get golang.org/dl/go1.10.7`, something happens.
* You try `go1.10.7 download` and it fails because it is not found in `PATH`.

I think that document should mention that you should set `GOPATH` and/or set `$GOPATH/bin` to `PATH` as well.

**Comment by jayconrod** [comment]
@mitar Setting the directory where `go get` and `go install` write binaries is covered in [How to write Go code](https://golang.org/doc/code.html). But that page is meant to be read after the install instructions, so it should probably be mentioned there as well.

I'll reopen this issue and take a look soon.

**Comment by mitar** [comment]
Thanks. Yes, I have heard about `GOPATH`, but then when I was reading documentation it was not mentioned. So I assumed that with new support for modules it is not necessary anymore.

**Comment by superlazyname** [comment]
@cagedmantis is it possible for go to give a useful error message or something in this case?

**Comment by jayconrod** [comment]
@superlazyname It probably should give a better message, yes. #35912 is the tracking issue for that.

**Comment by iwdgo** [comment]
Instructions were updated by https://go-review.googlesource.com/c/go/+/254365
The current page of reference to handle multiple versions of go is https://go.dev/doc/manage-install
which explains how to use `go install` to download another version using the installed package.

It seems that issue can be closed.

**Comment by dongocanh96** [comment]
> Instructions were updated by https://go-review.googlesource.com/c/go/+/254365 The current page of reference to handle multiple versions of go is https://go.dev/doc/manage-install which explains how to use `go install` to download another version using the installed package.
> 
> It seems that issue can be closed.

The instruction in go document is unclear.
After run `go install golang.org/dl/go<version>@latest`, a binary file will be downloaded in `$HOMe/go/bin/`
Move to that directory, then run `./go<version> download`. And the version you need will be installed at /`home/<username>/sdk/`

**Comment by vitalygudza** [comment]
[SOLVED] for me: 
`go1.10.7 download` - now works! As said gopherbot (https://github.com/golang/go/issues/37428#issuecomment-642826458) you need to add path for bin folder (where you have go binaries):
`PATH=$PATH:$HOME/go/bin`

**Comment by koxon** [comment]
This is still unclear. I'm just following the doc here: [https://go.dev/doc/manage-install#linux-mac-bsd](https://go.dev/doc/manage-install#linux-mac-bsd)
And it's not mentioned anywhere that my new go binary file will be in `~/go/bin/`
Bad starting experience and 15 min lost because of it. Please fix this for future users.

**Comment by dongocanh96** [comment]
> This is still unclear.
> 
> I'm just following the doc here: https://go.dev/doc/manage-install#linux-mac-bsd And it's not mentioned anywhere that my new go binary file will be in `~/go/bin/` ... or add this path to $PATH at install time?
> 
> Bad first experience and 15 min lost because of it. Please fix this for future users.

Can you give more detail about your problem? You can't find go binary file or don't know how to add the version you need to path?

**Comment by koxon** [comment]
> Can you give more detail about your problem? You can't find go binary file or don't know how to add the version you need to path?

@dongocanh96 I read this in the [doc](https://go.dev/doc/manage-install#linux-mac-bsd):

```
To install additional Go versions, run the `go install command`, specifying the download location of the version you want to install. The following example illustrates with version 1.10.7:

$ go install golang.org/dl/go1.10.7@latest
$ go1.10.7 download
```

I totally missed the [go install command](https://go.dev/cmd/go/#hdr-Compile_and_install_packages_and_dependencies) link which explain things in details.  So being new to `go` I didn't know my installs were going in `~/go/bin/`. 

`go1.10.7 download` only works if the `~/go/bin/` folder is in your $PATH. 

If you add to the documentation the binary location or add a comment saying that `go install` will install the new version in the `~/go/bin` that would help new users.

**Comment by dongocanh96** [comment]
> If you add the binary location to the documentation or add a comment saying that `go install` will install the new version in the `~/go/bin` that would help new users.

No, the binary file will be downloaded in `~/go/bin` , run that binary file and the version you need will be installed in  `$HOME/sdk/`. To use that version, you need to add the following line to `~/.bashrc`
`alias go<version>=$HOME/sdk/go<version>/bin/go`
I don't know why the documents don't specify this, but I had the same problem as the OP and after observing, I realized how to fix it.

**Comment by bdave-apptio** [comment]
> > If you add the binary location to the documentation or add a comment saying that `go install` will install the new version in the `~/go/bin` that would help new users.
> 
> No, the binary file will be downloaded in `~/go/bin`, run that binary file with `./go<version> download` and the version you need will be installed in `$HOME/sdk/`. To use that version, you need to add the following line to `~/.bashrc` `alias go<version>=$HOME/sdk/go<version>/bin/go` After saving & exit, you need to run `source ~/.bashrc` and in some cases, you should restart the terminal. I don't know why the document doesn't specify this, but I had the same problem as the OP and after observing, I realized how to fix it.

This worked. Thanks a lot.
