### ISSUE TITLE
cmd/go: 'no such tool "api"' when running 'go tool api' from downloaded tarball

### ISSUE THREAD

**Issue by ronaldpetty** [golang/go#37424]
It seems `go tool api` was removed at some point.  The webpage still exists though, maybe for backward compatibility.  If the later is true, should it be updated to explain why it was removed?  Not sure if this is the right forum for web related updates.

Tool doesn't exist in 1.13.

```
$ go version
go version go1.13.8 linux/amd64

$ go tool api
go tool: no such tool "api"
```

page exists:

```
user@ubuntu:~/go/src/lab-overview$ curl -LI https://golang.org/cmd/api
HTTP/1.1 301 Moved Permanently
Date: Mon, 24 Feb 2020 20:54:50 GMT
Content-Type: text/html; charset=utf-8
Location: /cmd/api/
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Via: 1.1 google
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000

HTTP/1.1 200 OK
Date: Mon, 24 Feb 2020 20:54:50 GMT
Content-Type: text/html; charset=utf-8
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Via: 1.1 google
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
```

**Comment by ianlancetaylor** [comment]
As far as I can tell `go tool api` exists on tip and in Go 1.13.  How did you build your Go installation?

**Comment by ronaldpetty** [comment]
Hello Ian,

I had simply used curl -sLO
https://dl.google.com/go/go1.13.8.linux-amd64.tar.gz

I will recreate my VM later this week and see if I can recreate it once
more (and confirm nothing else weird has happened, but so far can't
remember anything odd).

Ron

**Comment by ALTree** [comment]
`go tool api` in not shipped in the pre-compiled binaries we have on the download page, you only get it if you build Go from the git repository. See #13030.

**Comment by ronaldpetty** [comment]
Thanks @ALTree , after reading #13030, it seems that removing 'api' from 'go tool' list would make sense if it's only used for internal development.  I haven't dug deeper but it sounds like the recommendation was that in 1.6?  I am unfamiliar with how the tools are all build/used/exposed; but happy to learn if this makes sense.

**Comment by jayconrod** [comment]
`go tool` doesn't have an explicit list of tools: it just checks the `pkg/tool/GOOS_GOARCH/` directory.

But why remove it anyway? It doesn't make sense to ship a binary (#13030), but it's still used for building and releasing Go itself.

I checked the versions of Go I have installed (a mix dating back to 1.10): none have a binary `api`, so I don't think there's been any recent change here.

**Comment by ronaldpetty** [comment]
If you type "go tool" it does not list 'api'.  I believe in the past it was
showing, so maybe at some point it was removed and I might just be running
on stall information.  I guess this be closed.  I learned a little more
about how it all works, so thanks for that!

**Comment by jayconrod** [comment]
`go tool` without arguments lists files in the `tool` directory, so if you had `cmd/api` installed before, you might have seen that. No need to change that though I think.
