### ISSUE TITLE
go.dev: detect licenses for modules not at their repository roots

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#37437]
@jba brought up an issue where pkg.go.dev fails to detect a license for a module that is not at thei repository root. Example:

https://pkg.go.dev/gioui.org/example

The reason is that while the repository for the gioui.org/example module,

   https://git.sr.ht/~eliasnaur/gio/tree

does have detectable licenses, the module rooted at

   https://git.sr.ht/~eliasnaur/gio/tree/master/example

doesn't.

@jba points out that pkg.go.dev works in terms of module zip files, which only contain files in the module tree. The module zip for gioui.org/example does not contain the UNLICENSE nor LICENSE-MIT files from the parent directory.

However, forcing licensing files at every module root feels like bending too much for the licensing detection tool. I don't particularly mind copying the license files to my nested modules gioui.org/example and gioui.org/cmd, but I would not appreciate this restriction if I had an otherwise non-Go repository that happened to contain a minor Go module in a subdirectory.                                                                                                   

### What did you expect to see?
A license detected on https://pkg.go.dev/gioui.org/example.

### What did you see instead?
No licenses detected for https://pkg.go.dev/gioui.org/example.

**Comment by myitcv** [comment]
> @jba points out that pkg.go.dev works in terms of module zip files, which only contain files in the module tree. The module zip for gioui.org/example does not contain the UNLICENSE nor LICENSE-MIT files from the parent directory

I personally think this is the correct position; otherwise if I install/use the module via proxy.golang.org there will be no license distributed with the code I am using, which seems wrong.

The module is the unit of source code exchange and versioning; it seems a sensible requirement to have the license be part of that.

**Comment by mvdan** [comment]
I agree that this is a bit bizarre, though. Do we expect an open source monorepo with dozens of published modules to contain dozens of exact copies of its license? If that's what we expect, I don't think it has been communicated well enough.

**Comment by heschik** [comment]
Note that this is all confused by the fact that the `go` command automatically propagates `LICENSE` files -- not `LICENCE`, not `LICENSE.md`, just `LICENSE` -- from the repository root to nested modules, and that decision can't be changed because it would break checksums.

**Comment by eliasnaur** [comment]
I didn't know about the LICENSE propagation. That's sort of good news. For me in particular if pkg.go.dev supports dual-licensed projects where the licenses are merged into one LICENSE file.

**Comment by eliasnaur** [comment]
I created a testing branch of gioui.org with the merged LICENSE file, [here](https://git.sr.ht/~eliasnaur/gio/commit/6da9fabec9a39c249457bfbfccccfca42750a5ef), tagged "license-debug".

Is there a way to test whether pkg.go.dev accepts the merged LICENSE without pushing the change to master? [licensecheck](https://pkg.go.dev/github.com/google/licensecheck?tab=doc) doesn't seem offer a cli version.

**Comment by eliasnaur** [comment]
I'm lazy, so I opted to simply merge the licenses into LICENSE and push to master. It worked! See

https://pkg.go.dev/mod/gioui.org?tab=licenses
and the submodules
https://pkg.go.dev/mod/gioui.org/example?tab=licenses
https://pkg.go.dev/mod/gioui.org/cmd?tab=licenses

I'm closing this issue because I'm happy: license propagation works without awkward duplication and the licensing babble is confined to a single file, LICENSE. Thanks for the tip, @heschik.
