### ISSUE TITLE
what the help man ? 

### ISSUE THREAD

**Issue by Darkells** [golang/go#37435]
I am very angry, my project boase on go module.  
Now golang is 1.13.5
Why can't I import a local package

i just test simple ,
tree
- com.dark.fish
    - util
        - Util.go
- main.go

cannot find module providing package com.dark.fish/util/Util

GO111MODULE="auto"
Why?

**Comment by hnishi** [comment]
I think you should use the replace directive.

```
replace com.dark.fish/util/Util => com.dark.fish/util/Util v0.0.0
```

https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive

**Comment by mattn** [comment]
@Darkells As @hnishi mentioned, you need to use replace directive.

```
$ mkdir foo
$ cd foo
$ cat > main.go
package main

import (
	"com.dark.fish/util"
)

func main() {
	util.DoSomething()
}
^D

$ cat > go.mod
module foo

replace com.dark.fish/util => ./com.dark.fish/util
^D

$ pushd .
$ mkdir -p com.dark.fish/util
$ cd com.dark.fish.util
$ cat > Util.go
package util

func DoSomething() {
	println("do something")
}
^D

$ go mod init com.dark.fish/util
$ popd
$ go build
$ ./foo
```
This is issue tracker of Go. Please ask like this on [golang-nuts](https://groups.google.com/forum/#!forum/golang-nuts) or somewhere.

**Comment by mvdan** [comment]
Like @mattn said, this is not the place to ask questions.
