### ISSUE TITLE
Incorrect Install Information on Main Website

### ISSUE THREAD

**Issue by solderjs** [golang/go#37434]
The official documentation on the main website is grossly out of date:
https://golang.org/doc/install#testing

### What did you expect to see?

Simpler documentation suitable for the current version of go1.13+

### What did you see instead?

It's instructing users to set `GOPATH` and place code inside of it... which will only lead to frustration and sadness.

> Create your workspace directory, $HOME/go. (If you'd like to use a different directory, you will need to set the GOPATH environment variable.)

**Comment by ALTree** [comment]
Thanks for reporting this.

The issue was tracked at #37042 and it has already been fixed in the version that will come with Go1.14, you can see a preview here: https://tip.golang.org/doc/install#testing

Closing here.
