### ISSUE TITLE
all: Go 1.14 release status

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#37445]
Issue tracking the go1.14 release by releasebot.

**Comment by cagedmantis** [comment]
## PROBLEMS WITH RELEASE

  - open issue #27155 is tagged release-blocker
  - open issue #29252 is tagged release-blocker
  - doc/contrib.html does not list major version go1.14
  - **Found errors during release. Stopping!**

## Log

    2020/02/25 10:58:14 starting
    2020/02/25 10:58:14 working in /usr/local/google/home/amedee/go-releasebot-work/go1.14
    2020/02/25 10:58:14 $ git clone https://go.googlesource.com/go /usr/local/google/home/amedee/go-releasebot-work/go1.14/gitmirror
    2020/02/25 10:58:29 $ git config gc.auto 0
    2020/02/25 10:58:29 $ git fetch origin release-branch.go1.14
    2020/02/25 10:58:29 $ git clone --reference /usr/local/google/home/amedee/go-releasebot-work/go1.14/gitmirror -b release-branch.go1.14 https://go.googlesource.com/go /usr/local/google/home/amedee/go-releasebot-work/go1.14/gitwork
    2020/02/25 10:58:30 $ git codereview change relwork
    2020/02/25 10:58:30 $ git config gc.auto 0
    2020/02/25 10:58:32 an associated security release branch "release-branch.go1.14-security" does not exist; assuming it has been merged and deleted, so proceeding as usual
    2020/02/25 10:58:32 $ git rev-parse go1.14
    2020/02/25 10:58:32 Release status issue title: "all: Go 1.14 release status"
    2020/02/25 10:58:35 Release status issue: https://golang.org/issue/37445
    

There were problems with the release, see above for details.

**Comment by cagedmantis** [comment]
## Log

    2020/02/25 11:19:45 starting
    2020/02/25 11:19:45 working in /usr/local/google/home/amedee/go-releasebot-work/go1.14
    2020/02/25 11:19:45 $ git fetch origin master
    2020/02/25 11:19:47 $ git fetch origin release-branch.go1.14
    2020/02/25 11:19:49 $ git clone --reference /usr/local/google/home/amedee/go-releasebot-work/go1.14/gitmirror -b release-branch.go1.14 https://go.googlesource.com/go /usr/local/google/home/amedee/go-releasebot-work/go1.14/gitwork
    2020/02/25 11:19:50 $ git codereview change relwork
    2020/02/25 11:19:50 $ git config gc.auto 0
    2020/02/25 11:19:50 an associated security release branch "release-branch.go1.14-security" does not exist; assuming it has been merged and deleted, so proceeding as usual
    2020/02/25 11:19:50 $ git rev-parse go1.14
    2020/02/25 11:19:50 Release status issue title: "all: Go 1.14 release status"
    2020/02/25 11:19:50 Release status issue: https://golang.org/issue/37445
    2020/02/25 11:19:50 $ git add VERSION
    2020/02/25 11:19:50 $ git commit -m go1.14
    
    Change-Id: Ic949a6caa8d55115630d0e8e7c9480b54c987b31
     VERSION
    2020/02/25 11:19:51 $ git codereview mail -trybot
    2020/02/25 11:19:55 $ go get golang.org/x/build/cmd/release
    2020/02/25 11:20:39 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target src -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/231be9af00ff21e7ee977b9bc2ec83a732443ae3_699694875 -rev 231be9af00ff21e7ee977b9bc2ec83a732443ae3
    2020/02/25 11:20:39 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target linux-armv6l -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/231be9af00ff21e7ee977b9bc2ec83a732443ae3_699694875 -rev 231be9af00ff21e7ee977b9bc2ec83a732443ae3
    2020/02/25 11:20:39 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target darwin-amd64 -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/231be9af00ff21e7ee977b9bc2ec83a732443ae3_699694875 -rev 231be9af00ff21e7ee977b9bc2ec83a732443ae3
    2020/02/25 11:20:39 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target linux-386 -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/231be9af00ff21e7ee977b9bc2ec83a732443ae3_699694875 -rev 231be9af00ff21e7ee977b9bc2ec83a732443ae3
    2020/02/25 11:20:39 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target freebsd-amd64 -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/231be9af00ff21e7ee977b9bc2ec83a732443ae3_699694875 -rev 231be9af00ff21e7ee977b9bc2ec83a732443ae3
    2020/02/25 11:20:39 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target windows-386 -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/231be9af00ff21e7ee977b9bc2ec83a732443ae3_699694875 -rev 231be9af00ff21e7ee977b9bc2ec83a732443ae3
    2020/02/25 11:20:39 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target linux-s390x -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/231be9af00ff21e7ee977b9bc2ec83a732443ae3_699694875 -rev 231be9af00ff21e7ee977b9bc2ec83a732443ae3
    2020/02/25 11:20:39 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target linux-arm64 -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/231be9af00ff21e7ee977b9bc2ec83a732443ae3_699694875 -rev 231be9af00ff21e7ee977b9bc2ec83a732443ae3
    2020/02/25 11:20:39 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target linux-ppc64le -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/231be9af00ff21e7ee977b9bc2ec83a732443ae3_699694875 -rev 231be9af00ff21e7ee977b9bc2ec83a732443ae3
    2020/02/25 11:20:39 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target linux-amd64 -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/231be9af00ff21e7ee977b9bc2ec83a732443ae3_699694875 -rev 231be9af00ff21e7ee977b9bc2ec83a732443ae3
    2020/02/25 11:20:39 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target freebsd-386 -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/231be9af00ff21e7ee977b9bc2ec83a732443ae3_699694875 -rev 231be9af00ff21e7ee977b9bc2ec83a732443ae3
    2020/02/25 11:20:39 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target windows-amd64 -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/231be9af00ff21e7ee977b9bc2ec83a732443ae3_699694875 -rev 231be9af00ff21e7ee977b9bc2ec83a732443ae3
    2020/02/25 12:05:00 
    
    The release is ready.
    
    Please review and submit https://go-review.googlesource.com/q/Ic949a6caa8d55115630d0e8e7c9480b54c987b31
    and then run the release stage.

**Comment by cagedmantis** [comment]
## PROBLEMS WITH RELEASE

  - open issue #37400 is tagged release-blocker
  - **Found errors during release. Stopping!**

## Latest build: go1\.14

src not started
linux\-386 not started
linux\-armv6l not started
linux\-amd64 not started
linux\-arm64 not started
freebsd\-386 not started
freebsd\-amd64 not started
windows\-386 not started
windows\-amd64 not started
darwin\-amd64 not started
linux\-s390x not started
linux\-ppc64le not started

## Log

    2020/02/25 12:41:40 starting
    2020/02/25 12:41:40 working in /usr/local/google/home/amedee/go-releasebot-work/go1.14
    2020/02/25 12:41:40 $ git fetch origin master
    2020/02/25 12:41:42 $ git fetch origin release-branch.go1.14
    2020/02/25 12:41:44 $ git clone --reference /usr/local/google/home/amedee/go-releasebot-work/go1.14/gitmirror -b release-branch.go1.14 https://go.googlesource.com/go /usr/local/google/home/amedee/go-releasebot-work/go1.14/gitwork
    2020/02/25 12:41:45 $ git codereview change relwork
    2020/02/25 12:41:46 $ git config gc.auto 0
    2020/02/25 12:41:46 an associated security release branch "release-branch.go1.14-security" does not exist; assuming it has been merged and deleted, so proceeding as usual
    2020/02/25 12:41:46 Release status issue title: "all: Go 1.14 release status"
    2020/02/25 12:41:46 Release status issue: https://golang.org/issue/37445
    

There were problems with the release, see above for details.

**Comment by cagedmantis** [comment]
## Latest build: go1\.14

src ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.14/go1.14.src.tar.gz))
linux\-386 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.14/go1.14.linux-386.tar.gz))
linux\-armv6l ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.14/go1.14.linux-armv6l.tar.gz))
linux\-amd64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.14/go1.14.linux-amd64.tar.gz))
linux\-arm64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.14/go1.14.linux-arm64.tar.gz))
freebsd\-386 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.14/go1.14.freebsd-386.tar.gz))
freebsd\-amd64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.14/go1.14.freebsd-amd64.tar.gz))
windows\-386 ([zip](https://golang-release-staging.storage.googleapis.com/go1.14/go1.14.windows-386.zip)) ([msi](https://golang-release-staging.storage.googleapis.com/go1.14/go1.14.windows-386.msi))
windows\-amd64 ([zip](https://golang-release-staging.storage.googleapis.com/go1.14/go1.14.windows-amd64.zip)) ([msi](https://golang-release-staging.storage.googleapis.com/go1.14/go1.14.windows-amd64.msi))
darwin\-amd64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.14/go1.14.darwin-amd64.tar.gz))
linux\-s390x ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.14/go1.14.linux-s390x.tar.gz))
linux\-ppc64le ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.14/go1.14.linux-ppc64le.tar.gz))

## Log

    2020/02/25 13:30:26 starting
    2020/02/25 13:30:26 working in /usr/local/google/home/amedee/go-releasebot-work/go1.14
    2020/02/25 13:30:26 $ git fetch origin master
    2020/02/25 13:30:26 $ git fetch origin release-branch.go1.14
    2020/02/25 13:30:26 $ git clone --reference /usr/local/google/home/amedee/go-releasebot-work/go1.14/gitmirror -b release-branch.go1.14 https://go.googlesource.com/go /usr/local/google/home/amedee/go-releasebot-work/go1.14/gitwork
    2020/02/25 13:30:27 $ git codereview change relwork
    2020/02/25 13:30:28 $ git config gc.auto 0
    2020/02/25 13:30:28 an associated security release branch "release-branch.go1.14-security" does not exist; assuming it has been merged and deleted, so proceeding as usual
    2020/02/25 13:30:28 Release status issue title: "all: Go 1.14 release status"
    2020/02/25 13:30:28 Release status issue: https://golang.org/issue/37445
    2020/02/25 13:30:28 $ git rev-parse go1.14
    2020/02/25 13:30:52 $ git tag go1.14 20a838ab94178c55bc4dc23ddc332fce8545a493
    2020/02/25 13:30:52 $ git push origin go1.14
    2020/02/25 13:30:56 $ go get golang.org/x/build/cmd/release
    2020/02/25 13:31:45 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target darwin-amd64 -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/20a838ab94178c55bc4dc23ddc332fce8545a493_438808823 -rev 20a838ab94178c55bc4dc23ddc332fce8545a493 -skip_tests
    2020/02/25 13:31:45 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target linux-armv6l -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/20a838ab94178c55bc4dc23ddc332fce8545a493_438808823 -rev 20a838ab94178c55bc4dc23ddc332fce8545a493 -skip_tests
    2020/02/25 13:31:45 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target linux-s390x -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/20a838ab94178c55bc4dc23ddc332fce8545a493_438808823 -rev 20a838ab94178c55bc4dc23ddc332fce8545a493 -skip_tests
    2020/02/25 13:31:45 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target src -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/20a838ab94178c55bc4dc23ddc332fce8545a493_438808823 -rev 20a838ab94178c55bc4dc23ddc332fce8545a493 -skip_tests
    2020/02/25 13:31:45 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target linux-386 -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/20a838ab94178c55bc4dc23ddc332fce8545a493_438808823 -rev 20a838ab94178c55bc4dc23ddc332fce8545a493 -skip_tests
    2020/02/25 13:31:45 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target windows-amd64 -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/20a838ab94178c55bc4dc23ddc332fce8545a493_438808823 -rev 20a838ab94178c55bc4dc23ddc332fce8545a493 -skip_tests
    2020/02/25 13:31:45 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target windows-386 -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/20a838ab94178c55bc4dc23ddc332fce8545a493_438808823 -rev 20a838ab94178c55bc4dc23ddc332fce8545a493 -skip_tests
    2020/02/25 13:31:45 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target linux-amd64 -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/20a838ab94178c55bc4dc23ddc332fce8545a493_438808823 -rev 20a838ab94178c55bc4dc23ddc332fce8545a493 -skip_tests
    2020/02/25 13:31:45 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target freebsd-amd64 -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/20a838ab94178c55bc4dc23ddc332fce8545a493_438808823 -rev 20a838ab94178c55bc4dc23ddc332fce8545a493 -skip_tests
    2020/02/25 13:31:45 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target freebsd-386 -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/20a838ab94178c55bc4dc23ddc332fce8545a493_438808823 -rev 20a838ab94178c55bc4dc23ddc332fce8545a493 -skip_tests
    2020/02/25 13:31:45 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target linux-arm64 -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/20a838ab94178c55bc4dc23ddc332fce8545a493_438808823 -rev 20a838ab94178c55bc4dc23ddc332fce8545a493 -skip_tests
    2020/02/25 13:31:45 $ /usr/local/google/home/amedee/go-releasebot-work/go1.14/gopath/bin/release -target linux-ppc64le -user amedee -version go1.14 -tools release-branch.go1.14 -net release-branch.go1.14 -staging_dir /usr/local/google/home/amedee/go-releasebot-work/go1.14/release-staging/20a838ab94178c55bc4dc23ddc332fce8545a493_438808823 -rev 20a838ab94178c55bc4dc23ddc332fce8545a493 -skip_tests
    2020/02/25 13:50:14 closing milestone Go1.14
    2020/02/25 13:50:14 
    
    The release run is complete! Refer to the playbook for the next steps.
    
    Thanks for riding with releasebot today.

**Comment by dmitshur** [comment]
I believe this release is done, so I'll close this.

@cagedmantis Let me know if there's anything left to do and if it should be re-opened.
