### ISSUE TITLE
syscall: if $LD_PRELOAD is set, use connect(), execve() in libc

### ISSUE THREAD

**Issue by gopherbot** [golang/go#3744]
by **hongruiqi**:

<pre>cgoLookupHost may return nil addrs with no err report, which leads to the index out of
range in the net.hostPortToIP by indexing addrs[0].

go version weekly.2012-03-27 +5e3661048f2e</pre>

**Comment by ymmt2005** [comment]
FWIW, transparent proxy can be done without using LD_PRELOAD.
I have blogged one such solution using Go on Linux.
http://ymmt2005.hatenablog.com/entry/2016/03/13/Transparent_SOCKS_proxy_in_Go_to_replace_NAT

**Comment by bradfitz** [comment]
I don't think this is ever going to happen.

We don't like calling into C from Go more than we have to, and have moved to minimize when we do so (e.g. we prefer our own DNS resolver when possible).

I agree with the page that @ymmt2005 referenced, which says: "Using iptables is far better than LD_PRELOAD for transparent proxy."
