### ISSUE TITLE
`go test` should respect relative paths

### ISSUE THREAD

**Issue by ORESoftware** [golang/go#37456]
I am on:

```
go version go1.13.7 linux/amd64
```

when we run:

```bash
export pkg_dir='some/relative/path'

go test "$pkg_dir"
```

it only works if `$pkg_dir` an absolute path, or relative to GOPATH, and it won't work if if it's relative to CWD/PWD. 

This is very frustrating for newbs and even pros who forget the rule that paths relative to PWD/CWD don't work. Here is my suggestion:

1. if it's an absolute path, stat $pkg-dir as an absolute path
2. if not an absolute path, stat it relative to GOPATH
3. if it's not relative to GOPATH, then stat it is as relative to CWD

this should be a non-breaking change, except for those who have failing paths, who will then hit a real path if it's not relative to GOPATH, but now relative to a local path (given PWD)

**Comment by mvdan** [comment]
You should read `go help packages`.

**Comment by ORESoftware** [comment]
@mvdan  if there is something related in here, then maybe quote the important text for other users

**Comment by mvdan** [comment]
Just read the very first paragraph:

> An import path that is a rooted path or that begins with a . or .. element is interpreted as a file system path and denotes the package in that directory.

In particular, just use `./some/relative/path`. For more questions, see https://golang.org/wiki/Questions.

**Comment by ORESoftware** [comment]
@mvdan that's a dumb answer, since this potential fix obviates the need for the `./`

right?

**Comment by thepudds** [comment]
Hello @ORESoftware, one thing to consider is that something like `go test -v math/rand` currently means to test the standard library `math/rand` package. You can try running that to see what happens.

If I understood your proposal, it would mean something like `go test -v math/rand` would become ambiguous, including if you happened to have a `math/rand` directory sitting there.

On the other hand, if you do `go test -v ./math/rand` today, its meaning is clear with the leading `./`.

Sorry if I misunderstood what you are proposing.
