### ISSUE TITLE
Os.Stat() File permissions representation 

### ISSUE THREAD

**Issue by luke-goddard** [golang/go#37457]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/luke/go/bin"
GOCACHE="/home/luke/.cache/go-build"
GOENV="/home/luke/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/luke/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/luke/go/src/gosec/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build651612000=/tmp/go-build -gno-record-gcc-switches"
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I need to use golang to get the file permissions of a given file (specifically the SUID bit). Here are the permissions of an example file. 
```
$ touch example_file.test
$ chmod 7777 example_file.test
$ ls -ltra example_file.test
	-rwsrwsrwt 1 luke users 0 Feb 25 21:53 example_file.test
	
$ stat -c "%a %n" example_file.test
     7777 example_file.test
```

Here is a tiny program illustrating the issue. 
```
func main() {
	info, _ := os.Stat("example_file.test")
        fmt.Println(info.Mode().String())			             // ugtrwxrwxrwx
        fmt.Println(info.Mode().Perm().String())		         // -rwxrwxrwx
        fmt.Printf("permissions: %#o\n", info.Mode().Perm())     // permissions: 0777
}
```
The golang results are inconsistant because `ugtrwxrwxrwx != 0777`. 

The following quote from the documentation indicates that this might be a cross-platform compatibility issue. 

> A FileMode represents a file's mode and permission bits. The bits have
> the same definition on all systems, so that information about files
> can be moved from one system to another portably. Not all bits apply
> to all systems. The only required bit is ModeDir for directories.
> 
> type FileMode uint32 The defined file mode bits are the most
> significant bits of the FileMode. The nine least-significant bits are
> the standard Unix rwxrwxrwx permissions. The values of these bits
> should be considered part of the public API and may be used in wire
> protocols or disk representations: they must not be changed, although
> new bits might be added.

Is this a limitation of go?

### What did you expect to see?

7777

### What did you see instead?
0777

**Comment by ianlancetaylor** [comment]
The `Perm` method is documented as returning the permission bits.  The SUID bit is not a permission bit.
