### ISSUE TITLE
x/tools/cmd/goimports: rewrite 0X->0x, 0O->0o as gofmt does

### ISSUE THREAD

**Issue by cespare** [golang/go#37453]
In Go 1.13, gofmt started canonicalizing hex literals written as `0XABC` as `0xABC` and also started rewriting the newly introduced octal literals written as `0O123` as `0o123`. But goimports doesn't do this rewriting. This means that code formatted by goimports may be further altered by gofmt, which I think we've always tried to avoid.

**Comment by heschik** [comment]
Hm. I generally agree, but `gofmt` is implicitly versioned as part of the Go distribution, whereas `goimports` is free-floating. So under what circumstances should we do the rewrite? `goimports` built with 1.13+? go1.13+ in the `go` directive of a `go.mod`? Would require more thought.

**Comment by cespare** [comment]
> So under what circumstances should we do the rewrite? goimports built with 1.13+?

Yes, exactly this.

This is already how goimports works today and those of us who care about getting a particular behavior of goimports to match gofmt already know that we need to match the goimports build version of Go with the gofmt Go version.

For instance, in Go 1.11 gofmt changed the alignment of certain literals (see 542ea5ad91367d2b40589942cc5757a4d5f43f97). If I build (tip) goimports with Go 1.10, I get the Go 1.10 gofmt alignment. If I build goimports with Go 1.11, I get the Go 1.11 gofmt alignment.

**Comment by heschik** [comment]
Maybe...but messing with someone's spacing feels different than preventing their code from compiling. Perhaps if we did it around 1.15 when there'd be some expectation everyone will have support for the new literals.

**Comment by cespare** [comment]
@heschik I think you're confusing this with a different issue (possibly #33363). I'm not talking about preventing anyone's code from compiling. This is about:

* Changing 0X to 0x, both of which are valid in all versions of Go.
* Changing 0O to 0o, both of which only exist in Go 1.13+.

**Comment by heschik** [comment]
Oh. Sorry, not paying enough attention. Sure, yes, let's do it. Do you happen to have the gofmt CL handy? Do you want to send a CL?

**Comment by cespare** [comment]
The original gofmt change was [CL 160184](http://golang.org/cl/160184).

I can send a goimports CL at some point if nobody beats me to it.

**Comment by dmitshur** [comment]
Now that Go 1.16 is out, the [supported](https://golang.org/doc/devel/release.html#policy) Go versions are 1.16 and 1.15. Both of them [perform this canonicalization](https://golang.org/doc/go1.15#go/format) during `go/format`, which `cmd/goimports` uses for final formatting. So there's no need to do anything more in `goimports` itself, it just works:

```
$ gofmt -d foo.go 
[...]
 package foo
 
-const N = 0XABC
+const N = 0xABC
 
-const M = 0O123
+const M = 0o123

$ goimports -d foo.go             
[...]
 package foo
 
-const N = 0XABC
+const N = 0xABC
 
-const M = 0O123
+const M = 0o123
```
