### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by yl604636754** [golang/go#37463]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.11
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
mac系统 
</pre></details>

### What did you do?
我知道runtime里面有监听goroutine的处理，当一个goroutine运行时间比较长就会移入global队列中，我但是当每个P执行完成之后又会从global往回拿goroutine。如果我的创建了多个goruntine时候，并且每个groruntine里面都是for {}，go程序就会出问题。

### What did you expect to see?
我希望runtime里面监听goroutine的模块中，加入for { }检测。如果有for{}.应该多去创建thread

**Comment by mvdan** [comment]
The template was only partially filled, and in chinese. Sorry, but we can't understand.
