### ISSUE TITLE
internal/go115: add package

### ISSUE THREAD

**Issue by josharian** [golang/go#37468]
[Moved from a discussion with @bcmills in [CL 220692](https://go-review.googlesource.com/c/go/+/220692).]

I propose we add a new package, internal/go115, to help with adding features gates for minor things like new compiler optimizations.

The contents would look something like:

enabled.go

```go
// +build !go115gatedisabled

package go115

// Gate controls whether feature f is enabled.
// If there is an issue filed, f should be of the form "issueNNNN".
func Gate(f string) bool {
  return true
}
```

disabled.go

```go
// +build go115gatedisabled

package go115

func Gate(f string) bool {
  return false
}
```

Rationale:

* This makes it easy and convenient to use feature gates, including in places like rewrite rules where there's no local spot to define a constant.
* This makes it possible to create a builder that runs with all feature gates disabled, to prevent code rot of disabled features.
* This provides a single, easy control point for doing things like feature bisection.
* This makes it easier to write tooling to find and remove feature gates. With constants, you need to deal with language variation like `const go115Foo` vs `const (\n\tgo115Foo`. `go115.Gate` will have no false positives.  For regular Go (but not, say, rewrite rules), it would be easier to write a tool to automatically find (and remove) all go115.Gate instances.

For discussion. I'd like to get to a decision reasonably quickly, though, since I have a few CLs waiting only on a decision about how to spell feature gates.

**Comment by bcmills** [comment]
CC @golang/osp-team

**Comment by bcmills** [comment]
I don't mind consolidating the gates into a package, but I don't understand the benefit of string literals over constants.

Constants would not only provide clear points at which to attach documentation (such as a description of the feature or a link to a tracking issue), but also provide a clearer, centralized overview of which gated features are present and enabled.

**Comment by dmitshur** [comment]
From the "Planning Go 1.15" mail, the rule that everyone must follow is simple:

> The flag *must be findable* by a simple grep for the string "go115"

I think adding a `internal/go115` package is fine. A `go115.DoNewRiskyThing` constant would satisfy the rule.

I suggest starting with a simple bool constant and go from there. I don't see the need to start using strings or build constraints; those should come later when the need for them is more clear.

If someone doesn't want to use the `internal/go115` package for their constant, that's fine too. It just needs to findable via the string "go115" .

**Comment by josharian** [comment]
People could use string constants if they wanted. I probably would, in regular Go code. But for rewrite rules, that constant ends up being in another file somewhere. And often it’d be appropriate to have one constant per rule, in which case requiring a constant is just overhead. And strings have the benefit of being easily grepped for, and being fairly descriptive.

Or did you mean using int constants? We could have an iota in package go115, but I’m worried that’d end up being a lot of line noise. But what it really comes down to is that I want to be able to add a one-line optimization rule in one line.

**Comment by dmitshur** [comment]
@josharian How many flags do you anticipate needing? Remember that each flag needs its own tracking release-blocker issue. If we were to do this practice for Go 1.14, I'd expect it would've had 3-6 such flags.

**Comment by josharian** [comment]
Oh, you mean constant bools. One downside to constant bools is you have to add two of them, one enabled and one disabled. Assuming we want to be able to test disabled features—and if we don’t do that, we may find that feature gates don’t help because the code is broken without the feature enabled.

The other downside, mentioned above, is tooling. If you want to do a bisection to find what feature can be disabled to fix a bug, it’d be a lot easier if you could just write some code in a function instead of manually changing a bunch of constants each iteration. Or having to write a tool to modify constants.

**Comment by josharian** [comment]
> Remember that each flag needs its own tracking release-blocker issue.

The email said they were needed for all risky changes, and explicitly said that all compiler changes that changed generated code were deemed risky. So I was trying to take that at its word and gate all new optimizations. I have at least a half dozen out for review now, and have another dozen that I need to finish up and mail.

**Comment by dmitshur** [comment]
It may make sense to group many smaller individual risky changes together behind a single large flag, rather than having more small flags.

We don't have plans to actively test flag combinations during the Go 1.15 development cycle as part of the builders yet. They're for humans to use when we get closer to beta/RC in case we need to investigate hard-to-diagnose issues. Having fewer flags should be fine; it's meant to serve as a coarse debugging aid.

**Comment by dmitshur** [comment]
> The email said they were needed for all risky changes, and explicitly said that all compiler changes that changed generated code were deemed risky.

They're meant for changes that are both risky and potentially hard to diagnose. I think what @aclements wrote [here](https://groups.google.com/d/msg/golang-dev/y0yM_Xi665Q/QJLNloE0CQAJ) is very good guidance. Sorry if the email was confusing, but I certainly didn't mean for all compiler changes to require a flag regardless of the cost of doing so. The flags should be added when they're helpful to humans.

**Comment by cherrymui** [comment]
I think the idea is to gate large changes that are hard to revert. For small changes we can just revert them in the case that it is necessary, without gating.

**Comment by josharian** [comment]
I see. Thanks, @cherrymui, that's a very helpful rule of thumb. That didn't come across in the earlier email. I don't entirely see how that's any different from what we have done in the past, and I do still worry about code rot in the feature-flag-disabled case unless it is actively tested...but I'm also fine leaving those concerns to other people to worry about. :) It sounds like this new policy doesn't impact anything I'm doing. And this proposed package is indeed thus not necessary.
