### ISSUE TITLE
runtime: emit better errors from checkptr

### ISSUE THREAD

**Issue by dominikh** [golang/go#37488]
Currently, checkptr checks for four different kinds of mistakes; two of them concerning alignment, two of them concerning pointer arithmetic. However, it only emits two different kinds of errors, one per class of mistakes. It would be helpful to know which specific kind of mistake I made. Did I ignore alignment, or did I straddle multiple objects?

Furthermore, the errors themselves can be confusing. `unsafe pointer conversion` will point to a line of code that uses `unsafe.Pointer` conversion; it is not immediately obvious that these two uses of the word "unsafe" mean different things – checkptr really complains about potentially broken pointer conversions.

**Comment by josharian** [comment]
@mdempsky

**Comment by mdempsky** [comment]
All good points. I'm open to improving the error messages.

Some suggestions:

```
checkptr: misaligned pointer conversion
checkptr: converted pointer straddles multiple allocations
checkptr: pointer arithmetic computed bad pointer value
checkptr: pointer arithmetic result points to invalid allocation
```

I'm also wondering if "checkptr:" should change to "unsafe:" for consistency with warnings about packages runtime and sync, or if it should stay "checkptr" to make the compiler flag connection clearer.

**Comment by cespare** [comment]
Related to #37298.

**Comment by dominikh** [comment]
I'm torn between the two prefixes, both have their advantage; I'm slightly leaning towards "checkptr:", because then people might not wonder as much why `unsafe` reports errors when using the race detector and not otherwise. Definitely makes it easier to google for "checkptr".

Your suggestions definitely improve upon the current messages, and we'll have a whole cycle to bikeshed them to death :-)
