### ISSUE TITLE
net/http/httptest: function NewRecorder() isn't registering hits in coverage report

### ISSUE THREAD

**Issue by bjm88** [golang/go#37492]
### What version of Go are you using (`go version`)?
go version go1.13.4 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
MacOS X

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Finding that go's coverage report is not counting our integration test api calls.  We use Gin's Mock router and httptest.NewRecorder() to simulate http requests within process, its like a normal go test at end of day.   Details submitted her under HTTP GIN project also:
https://github.com/gin-gonic/gin/issues/2267

### What did you expect to see?
Coverage report shows hits on our api endpoints from Gin to go services, all normal go packages.  We know we have tests that do hit these areas, they just dont show up in coverage report.  All other tests/unit tests show up properly.  

### What did you see instead?
Coverage report missing all coverage from these simulated http calls which is the bulk of our tests in our testing strategy actually.  They lead to the most coverage. Internal to go not sure why the system thinks they are not covered or if we are somehow capturing the coverage incorrectly....

????  Any help is greatly appreciated.  I assume many others have this issue if trying to track coverage.....

**Comment by bjm88** [comment]
Seems this was asked a while back also, seems like a major issue for testing if true...
https://github.com/golang/go/issues/23485

**Comment by cagedmantis** [comment]
Hi @bjm88. We don't really use our issue tracker for questions. More people will see your question, and you will get better answers, if you ask on a forum rather than on the issue tracker. See https://golang.org/wiki/Questions.
