### ISSUE TITLE
x/tools/internal/lsp: test failures due to data corruption

### ISSUE THREAD

**Issue by bcmills** [golang/go#37507]
This could be a symptom of #37269, of #36605, or of some other undiagnosed memory-corruption bug. (I note goroutines in both `golang.org/x/tools/go/packages.Load` and `golang.org/x/tools/internal/fastwalk.Walk` in the stack dump.)

https://build.golang.org/log/4924e7126d7b849af0daebadc00289e321818f5e

<pre>
020/02/26 22:48:02 no dep handle: no metadata for nosuchpkg
	package = nosuchpkg
2020/02/26 22:48:15 unable to compute error positions: no file for  in package golang.org/x/tools/internal/lsp/danglingstmt
	package = golang.org/x/tools/internal/lsp/danglingstmt
2020/02/26 22:48:15 unable to compute error positions: no file for  in package golang.org/x/tools/internal/lsp/danglingstmt
	package = golang.org/x/tools/internal/lsp/danglingstmt
2020/02/26 22:48:44 initial workspace load failed: couldn't run 'go': chdir /tmp/workdir/tmp/TestLSP_GOPATH210517143/lsp/src: no such file or directory
2020/02/26 22:48:44 initial workspace load failed: err: exit status 1: stderr: 2020/02/26 22:48:44 cannot determine current directory: getwd: no such file or directory

2020/02/26 22:49:32 no dep handle: no metadata for nosuchpkg
	package = nosuchpkg
2020/02/26 22:49:41 unable to compute error positions: no file for  in package golang.org/x/tools/internal/lsp/danglingstmt
	package = golang.org/x/tools/internal/lsp/danglingstmt
2020/02/26 22:49:41 unable to compute error positions: no file for  in package golang.org/x/tools/internal/lsp/danglingstmt
	package = golang.org/x/tools/internal/lsp/danglingstmt
2020/02/26 22:49:52 diagnose: could not generate diagnostics for go.mod file: err: exit status 1: stderr: golang.org/x/tools/internal/lsp/bad imports
	nosuchpkg: package nosuchpkg is not in GOROOT (/tmp/workdir/go/src/nosuchpkg)

2020/02/26 22:49:54 quick fixes failed: err: exit status 1: stderr: golang.org/x/tools/internal/lsp/bad imports
	nosuchpkg: package nosuchpkg is not in GOROOT (/tmp/workdir/go/src/nosuchpkg)

	file = file:///tmp/workdir/tmp/TestLSP_Modules744837051/lsp/suggestedfix/has_suggested_fix.go
<b>fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]</b>
…
FAIL	golang.org/x/tools/internal/lsp	161.038s
</pre>

CC @findleyr @stamblerre @ianthehat @matloob

**Comment by heschik** [comment]
Freebsd doesn't have an oversized dirent, so I don't think it was #37269. I fixed it anyway. I don't have any good guesses for the correct cause.

**Comment by bcmills** [comment]
See also #37602, #37688.

**Comment by heschik** [comment]
Glancing at the builders, I don't see any occurrences. Closing.
