### ISSUE TITLE
cmd/go: "no go-import meta tags" when fetching from a private GitLab repo

### ISSUE THREAD

**Issue by 2at2** [golang/go#37504]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yeap

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/strebul/Library/Caches/go-build"
GOENV="/Users/strebul/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY="*gitlab.com*"
GONOSUMDB="*gitlab.com*"
GOOS="darwin"
GOPATH="/Users/strebul/dev/gospace"
GOPRIVATE="*gitlab.com*"
GOPROXY="direct"
GOROOT="/Users/strebul/.gvm/gos/go1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/strebul/.gvm/gos/go1.13/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/strebul/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kz/4rf1vvhj2kb910mwtq44qzvr0000gn/T/go-build698625701=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

<pre>
go mod init
go get gitlab.com/strebul/test_lib
go get gitlab.com/strebul/test_lib: unrecognized import path "gitlab.com/strebul/test_lib" (parse https://gitlab.com/strebul/test_lib?go-get=1: no go-import meta tags ())
</pre>

# CURL

<pre>
curl https://gitlab.com/strebul/test_lib?go-get=1
</pre>

`<html><head><meta name="go-import" content="gitlab.com/strebul/test_lib git https://gitlab.com/strebul/test_lib.git" /><meta name="go-source" content="gitlab.com/strebul/test_lib https://gitlab.com/strebul/test_lib https://gitlab.com/strebul/test_lib/-/tree/master{/dir} https://gitlab.com/strebul/test_lib/-/blob/master{/dir}/{file}#L{line}" /></head><body>go get https://gitlab.com/strebul/test_lib</body></html>`

### What did you expect to see?
I want to obtain dependency.

With golang 1.14

<pre>
go get gitlab.com/strebul/test_lib
go get gitlab.com/strebul/test_lib: unrecognized import path "gitlab.com/strebul/test_lib": reading https://gitlab.com/strebul/test_lib?go-get=1: 500 Internal Server Error
</pre>

**Comment by bcmills** [comment]
If the server is returning status 500, there isn't really anything the `go` command can do about that. (Open an issue with GitLab.)

FWIW, here's what I get:
```
example.com$ go version
go version devel +7bb33179 Thu Feb 27 05:56:21 2020 +0000 linux/amd64

example.com$ go mod init example.com
go: creating new go.mod: module example.com

example.com$ go get gitlab.com/strebul/test_lib
go get gitlab.com/strebul/test_lib: module gitlab.com/strebul/test_lib: git ls-remote -q origin in /tmp/tmp.GIerny0Ddu/_gopath/pkg/mod/cache/vcs/fe81d9efa2646d8017d2a3c892b3f5b0f3070c2aaf4304e69e8a35ab3e5b45e8: exit status 128:
        fatal: could not read Username for 'https://gitlab.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
```

Note that with Go 1.14, in order to access private GitLab repos you'll probably need to put some sort of credential in your `.netrc` file.

**Comment by bcmills** [comment]
Also, `go1.13` is missing quite a few critical patches. On the 1.13 line, you'll want to use `go1.13.8` instead.

**Comment by bcmills** [comment]
Please follow up with GitLab about the 500's and let us know if you're still having trouble.

**Comment by 2at2** [comment]
I did it before my test. I've putted my credentials to .netrc. For quick investigation I can add your email to repository  gitlab.com/strebul/test_lib.

**Comment by 2at2** [comment]
I've installed go1.13.8 and there is the same error.

<pre>
go version
go version go1.13.8 darwin/amd64

go get gitlab.com/strebul/test_lib
go get gitlab.com/strebul/test_lib: unrecognized import path "gitlab.com/strebul/test_lib" (parse https://gitlab.com/strebul/test_lib?go-get=1: no go-import meta tags ())
</pre>

**Comment by bcmills** [comment]
Yeah, I'm not sure why you'd be getting that error. If you can, add GitLab user `bcmills` to the repo.

**Comment by 2at2** [comment]
I've added you.

**Comment by bcmills** [comment]
Thanks, I see it. I should have some time to look into this later this week.

**Comment by bcmills** [comment]
Here's what I'm seeing with Go 1.14, with a GitLab access token in my `.netrc` file:

```
example.com$ go version
go version go1.14 linux/amd64

example.com$ go mod init example.com
go: creating new go.mod: module example.com

example.com$ GOPRIVATE=gitlab.com/strebul go get -d gitlab.com/strebul/test_lib
go: downloading gitlab.com/strebul/test_lib v0.0.0-20200227153846-ae6ce9befc25
go: gitlab.com/strebul/test_lib upgrade => v0.0.0-20200227153846-ae6ce9befc25
go get: gitlab.com/strebul/test_lib@v0.0.0-20200227153846-ae6ce9befc25: parsing go.mod:
        module declares its path as: test_lib
                but was required as: gitlab.com/strebul/test_lib
```

and basically the same with Go 1.13.8:

```
example.com$ go version
go version go1.13.8 linux/amd64

example.com$ go mod init example.com
go: creating new go.mod: module example.com

example.com$ GOPRIVATE=gitlab.com/strebul go get -d gitlab.com/strebul/test_lib
go: finding gitlab.com/strebul/test_lib latest
go: downloading gitlab.com/strebul/test_lib v0.0.0-20200227153846-ae6ce9befc25
go: extracting gitlab.com/strebul/test_lib v0.0.0-20200227153846-ae6ce9befc25
go get: gitlab.com/strebul/test_lib@v0.0.0-20200227153846-ae6ce9befc25: parsing go.mod:
        module declares its path as: test_lib
                but was required as: gitlab.com/strebul/test_lib
```

Both of those error messages seem to be accurate.

**Comment by bcmills** [comment]
If I leave out `GOPRIVATE`, the error message is worse but still doesn't match the reported `no go-import meta tags` error:

```
example.com$ go version
go version go1.14 linux/amd64

example.com$ go mod init example.com
go: creating new go.mod: module example.com

example.com$ go get -d gitlab.com/strebul/test_lib
go: downloading gitlab.com/strebul/test_lib v0.0.0-20200227153846-ae6ce9befc25
go get gitlab.com/strebul/test_lib: gitlab.com/strebul/test_lib@v0.0.0-20200227153846-ae6ce9befc25: verifying module: gitlab.com/strebul/test_lib@v0.0.0-20200227153846-ae6ce9befc25: reading https://sum.golang.org/lookup/gitlab.com/strebul/test_lib@v0.0.0-20200227153846-ae6ce9befc25: 410 Gone
        server response:
        not found: gitlab.com/strebul/test_lib@v0.0.0-20200227153846-ae6ce9befc25: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /tmp/gopath/pkg/mod/cache/vcs/fe81d9efa2646d8017d2a3c892b3f5b0f3070c2aaf4304e69e8a35ab3e5b45e8: exit status 128:
                fatal: could not read Username for 'https://gitlab.com': terminal prompts disabled
```

**Comment by bcmills** [comment]
Is it possible that your machine is configured to use a proxy for HTTPS requests, and that proxy is somehow rewriting GitLab's response in a way that removes the `go-import` tags?

**Comment by 2at2** [comment]
Hi,

I've compiled golang 1.14 with my fixes (file src/cmd/go/internal/web/http.go:96) and seen that gitlab responded with 500 status code on request with Authorization: Basic ***. 
After some checks I've deleted auth data from my .netrc and got successful response with go-import meta. I don't know what updates gitlab made but I am going to report about that.

Finally to obtain private repository from gitlab:
- Do not put credentials to .netrc
- You need to add 
`[url "git@gitlab.com:"]
        insteadOf = https://gitlab.com/` 
to $HOME/.gitconfig
