### ISSUE TITLE
wiki: errors in Chrome OS setup instructions

### ISSUE THREAD

**Issue by manxbug** [golang/go#37511]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.14

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Chrome OS

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Following the instruction on https://github.com/golang/go/wiki/ChromeOS I hit some snags due to some errors in the instructions.

### What did you expect to see?
Create a Workspace
To keep this simple just create a folder called /usr/local/go/work. Also, create a folder called src inside /usr/local/go/work/.

The src folder already exists in /usr/local/go/ but this folder is actually for the source for go itself. If you compile from this folder your program ends up in /usr/local/go/bin instead of /usr/local/go/work

In the test section to says:
Now, run go install hello. Then, run ${GOPATH}/bin/hello and you should see Hello, Chrome OS!.

If you follow the instructions in "Set Path", you can just type hello to run instead.

### What did you see instead?

Create a Workspace
To keep this simple just create a folder called /usr/local/go/work. Also, create a folder called src inside /usr/local/go.

**Comment by ianlancetaylor** [comment]
The wiki is maintained by users of Go.  I encourage you to correct it.  Thanks.

**Comment by manxbug** [comment]
Thanks. Sorry. I didn't even realize it was a wiki.

**Comment by andybons** [comment]
Seems that the edits were made.
