### ISSUE TITLE
cmd/go: 'go build ./...' in module mode outside of a module traverses the filesystem instead of failing fast

### ISSUE THREAD

**Issue by perillo** [golang/go#37521]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.
It also reproduces with `go1.13` but not with `go1.12`.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/manlio/.local/bin"
GOCACHE="/home/manlio/.cache/go-build"
GOENV="/home/manlio/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="github.com/perillo/go-init"
GONOSUMDB="github.com/perillo/go-init"
GOOS="linux"
GOPATH="/home/manlio/.local/lib/go:/home/manlio/src/go"
GOPRIVATE="github.com/perillo/go-init"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build500333414=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.14 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.14
uname -sr: Linux 5.5.5-arch1-1
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.31.
gdb --version: GNU gdb (GDB) 9.1
</pre></details>

### What did you do?

By accident I typed `go build ./...` from inside my home directory, and I notice that it took a lot of time, spinning my hard disk.

```
$ sync
$ sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches'
$ time go build ./...                                                                                                                                                       
go: cannot find main module, but found .git/config in /home/manlio
	to create a module there, run:
	go mod init
go build ./...  13.39s user 14.64s system 19% cpu 2:20.65 total
```

Called again, with warm cache:
```
$ time go build ./...                                                                                                                                                       
go: cannot find main module, but found .git/config in /home/manlio
	to create a module there, run:
	go mod init
go build ./...  5.18s user 3.44s system 112% cpu 7.647 total
```

This only happens from inside my home directory, where there is a `.git/config` file.
Also, `go build` traverse the filesystem the entire filesystem only when the `./...` pattern is specified.

```
$ time go build                                                                                                                                                             
go: cannot find main module, but found .git/config in /home/manlio
	to create a module there, run:
	go mod init
go build  0.02s user 0.04s system 6% cpu 1.031 total
```
(with no cached data in the kernel).

**Comment by bcmills** [comment]
Heh, that's odd. I can reproduce it as well. Thanks for the report!

**Comment by bcmills** [comment]
CC @jayconrod @matloob

**Comment by bcmills** [comment]
> It also reproduces with `go1.13` but not with `go1.12`.

I'm also seeing a very slow `go build ./...` with `go1.12` when in `GOPATH` mode. So I suspect that what's happening here is that somehow the module-mode `go build` is trying to resolve `./...` _before_ it realizes that it isn't even in a module.

**Comment by perillo** [comment]
You are right.
It has nothing to do with a potential config file to convert.  The issue title should be changed.

Thanks.

**Comment by perillo** [comment]
Unfortunately `go` can not simply ignore the pattern, as an example with `go list std`.

**Comment by perillo** [comment]
Here is another example where a using a `...` pattern will cause `go list` to return a confusing warning, instead of reporting an error since the current working directory is not part of a module:

```
go list github.com/perillo/...
go: warning: "github.com/perillo/..." matched no packages
``

**Comment by bcmills** [comment]
That `go list` pattern is arguably correct: you can `go list` packages in the standard library when outside of a module, and no package in the standard library matches the pattern `github.com/perillo/...`.

**Comment by perillo** [comment]
But the first path element has a dot, so it can not be a standard library package.

**Comment by bcmills** [comment]
That's true. At any rate, it is clearly _not_ the same issue as the unnecessary filesystem walk for `./...`, so to the extent that it is worth addressing at all, it should be a separate issue.
