### ISSUE TITLE
x/pkgsite: example links do not open examples

### ISSUE THREAD

**Issue by rsc** [golang/go#37520]
Start at https://pkg.go.dev/strings?tab=doc#pkg-examples
and click on Fields, or jump straight to
https://pkg.go.dev/strings?tab=doc#example-Fields

Either way, the page ends up positioned on the “> Example” for Fields,
but it doesn't open the example. It's not obvious at first what has happened.

At the least, the example should be opened.

I also wonder if the page can be adjusted to display the Fields definition
and docs, assuming they fit onto the same screen as the example.

**Comment by julieqiu** [comment]
Thanks for the feedback! I'll work with our UX team on improving this.

/cc @fflewddur

**Comment by julieqiu** [comment]
Fixed.
