### ISSUE TITLE
crypto/x509: Certificate parsing/verification supports non-compliant dNSName constraints

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#37535]
`crypto/x509` supports dNSName name constraints which contain a leading period (i.e. `.example.com`), which are only valid for URIs per RFC 5280 (a [comment in `matchDomainConstraint` notes this, but implements it anyway](https://golang.org/src/crypto/x509/verify.go#L471)). Per https://github.com/golang/go/issues/16347 this seems to have mainly been implemented to maintain compatibility with OpenSSL and NSS, which allow these malformed constraints.

The current behavior in `Certificate.Verify` matches validation of URI constraints, requiring one or more labels to be appended to the name when a leading period is present. Given this is unspecified behavior, per 5280, this should be at least documented somewhere. Depending on the efforts to clarify this behavior (see https://www.rfc-editor.org/errata/eid5997) it may make sense to deprecate support for these constraints altogether (while I'm not sure about prevalence of this misuse in internal PKIs, these constraints are not allowed in the public web PKI).

**Comment by rolandshoemaker** [comment]
Just to add a bit of clarity after sleeping on this: I don't think the current behavior is explicitly dangerous as the implementation allows for more restrictive constraints than 5280 specifies. I think the main issue here is that because the behavior is unspecified the expectation of how the constraint should be treated may differ between the user and crypto/x509, which could lead to undesired verification behavior. Hence why I think this should, at the least, be publicly documented.

**Comment by briansmith** [comment]
> Just to add a bit of clarity after sleeping on this: I don't think the current behavior is explicitly dangerous as the implementation allows for more restrictive constraints than 5280 specifies.

I agree with that.

> https://www.rfc-editor.org/errata/eid5997

Note that this errata report seems to suggest treating a leading dot the same as when no leading dot is present, which would not have the desired effect. I emailed Ryan about it. I agree with the semantics documented in the CL.
