### ISSUE TITLE
x/image/font/gofont: Go Mono font readability for users

### ISSUE THREAD

**Issue by dmitshur** [golang/go#37532]
In issue #37411, it has been reported that:

> Serifs and small kerning can make it much harder for dyslexic users to read text.

In the original blog post that announced the Go fonts, https://blog.golang.org/go-fonts, the Go Mono font is described as:

> The Go Mono fonts have slab-shaped serifs, giving them a sturdy appearance.

If I understand correctly, this property can lead to an outcome where the Go Mono may offer a bad readability experience for some users. It's hard for me to know whether this is something that can be fixed in the fonts or not. I wanted to file this issue so that this can be investigated by those who are more familiar with the topics of typography and accessibility, and perhaps there can be some sort of improvement implemented (or, alternatively, document that this is unfortunately not something that can be fixed in the font itself).

/cc @nigeltao @robpike @empijei @katiehockman

**Comment by empijei** [comment]
I would say that most dyslexic people already have browser extensions to force different fonts on pages that use hard to read ones.

It was just disappointing to me that I had to add the go documentation to the list of less accessible portals when my workstation started using the Go font instead of Source Code Pro (the fallback).

**Comment by nigeltao** [comment]
Thanks for the feedback. Sorry for the late reply.

> It's hard for me to know whether this is something that can be fixed in the fonts or not.

It would be up to the type foundry, Bigelow & Holmes, and largely out of the Go team's control. I can pass the feedback on, but still, I would expect that this isn't something they could easily fix. Changing the fundamental look of the monospaced font would essentially be creating a new font.

**Comment by nigeltao** [comment]
I will also note that https://github.com/golang/go/issues/37411#issuecomment-592746260 has been marked fixed.
