### ISSUE TITLE
Cross comiple static library for linux-mips

### ISSUE THREAD

**Issue by fantasyRqg** [golang/go#37544]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/TYAndroid/.cache/go-build"
GOENV="/home/TYAndroid/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/TYAndroid/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build487958631=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

<details><summary><code>cross compile go env</code> Output</summary><br><pre>
$ CGO_ENABLED=1 CC="/home/TYAndroid/toolChains/opt/mips-gcc540-glibc222-64bit-r3.3.0/bin/mips-linux-gnu-gcc" CXX="/home/TYAndroid/toolChains/opt/mips-gcc540-glibc222-64bit-r3.3.0/bin/mips-linux-gnu-g++" GOPATH="/home/TYAndroid/Personal/rqg/ai_pad_sdk_hisilicon/src/go" GOOS=linux GOARCH=mips CGO_CFLAGS="-I/home/TYAndroid/Personal/rqg/ai_pad_sdk_hisilicon/src/go/../../third_party/sqlcipher/include/sqlcipher" CGO_LDFLAGS="-g -O2 /home/TYAndroid/Personal/rqg/ai_pad_sdk_hisilicon/src/go/../../third_party/sqlcipher/libs/mips/libsqlcipher.a /home/TYAndroid/Personal/rqg/ai_pad_sdk_hisilicon/src/go/../../third_party/openssl/libs/mips/libcrypto.a -ldl /home/TYAndroid/Personal/rqg/ai_pad_sdk_hisilicon/src/go/../../output/mips/ipc/go/glue_c.o" go env
GO111MODULE=""
GOARCH="mips"
GOBIN=""
GOCACHE="/home/TYAndroid/.cache/go-build"
GOENV="/home/TYAndroid/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/TYAndroid/Personal/rqg/ai_pad_sdk_hisilicon/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
GOMIPS="hardfloat"
AR="ar"
CC="/home/TYAndroid/toolChains/opt/mips-gcc540-glibc222-64bit-r3.3.0/bin/mips-linux-gnu-gcc"
CXX="/home/TYAndroid/toolChains/opt/mips-gcc540-glibc222-64bit-r3.3.0/bin/mips-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-I/home/TYAndroid/Personal/rqg/ai_pad_sdk_hisilicon/src/go/../../third_party/sqlcipher/include/sqlcipher"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2 /home/TYAndroid/Personal/rqg/ai_pad_sdk_hisilicon/src/go/../../third_party/sqlcipher/libs/mips/libsqlcipher.a /home/TYAndroid/Personal/rqg/ai_pad_sdk_hisilicon/src/go/../../third_party/openssl/libs/mips/libcrypto.a -ldl /home/TYAndroid/Personal/rqg/ai_pad_sdk_hisilicon/src/go/../../output/mips/ipc/go/glue_c.o"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -mabi=32 -march=mips32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build647522201=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Cross comiple static library for linux-mips

### What did you expect to see?
Build success

### What did you see instead?

<details><summary><code>CGO_ENABLED=1 GOOS=linux GOARCH=mips go build -buildmode=c-archive</code> Output</summary><br><pre>

/usr/lib/go-1.13/pkg/tool/linux_amd64/asm -trimpath "$WORK/b087=>" -I $WORK/b087/ -I /usr/lib/go-1.13/pkg/include -D GOOS_linux -D GOARCH_mips -shared -D GOMIPS_hardfloat -gensymabis -o $WORK/b087/symabis ./asm_mipsx.s
cat >$WORK/b087/importcfg << 'EOF' # internal
\# import config
EOF
/usr/lib/go-1.13/pkg/tool/linux_amd64/compile -o $WORK/b087/_pkg_.a -trimpath "$WORK/b087=>" -shared -p runtime/cgo -std -installsuffix shared -buildid 58OGoR3cGwa5mSwzdK-t/58OGoR3cGwa5mSwzdK-t -goversion go1.13.4 -symabis $WORK/b087/symabis -D "" -importcfg $WORK/b087/importcfg -pack -asmhdr $WORK/b087/go_asm.h ./callbacks.go ./callbacks_traceback.go ./iscgo.go ./setenv.go $WORK/b087/_cgo_gotypes.go $WORK/b087/cgo.cgo1.go $WORK/b087/_cgo_import.go
\# runtime/cgo
flag provided but not defined: -shared
usage: compile [options] file.go...
  -%	debug non-static initializers
  -+	compiling runtime
  -B	disable bounds checking
  -C	disable printing of columns in error messages
  -D path
    	set relative path for local imports
  -E	debug symbol export
  -I directory
    	add directory to import search path
  -K	debug missing line numbers
  -L	show full file names in error messages
  -N	disable optimizations
  -S	print assembly listing
  -V	print version and exit
  -W	debug parse tree after type checking
  -asmhdr file
    	write assembly header to file
  -bench file
    	append benchmark times to file
  -blockprofile file
    	write block profile to file
  -buildid id
    	record id as the build id in the export metadata
  -c int
    	concurrency during compilation, 1 means no concurrency (default 1)
  -complete
    	compiling complete package (no C or assembly)
  -cpuprofile file
    	write cpu profile to file
  -d list
    	print debug information about items in list; try -d help
  -dwarf
    	generate DWARF symbols (default true)
  -dwarfbasentries
    	use base address selection entries in DWARF (default true)
  -dwarflocationlists
    	add location lists to DWARF in optimized mode (default true)
  -e	no limit on number of errors reported
  -gendwarfinl int
    	generate DWARF inline info records (default 2)
  -goversion string
    	required version of the runtime
  -h	halt on error
  -importcfg file
    	read import configuration from file
  -importmap definition
    	add definition of the form source=actual to import map
  -installsuffix suffix
    	set pkg directory suffix
  -j	debug runtime-initialized variables
  -l	disable inlining
  -lang string
    	release to compile for
  -linkobj file
    	write linker-specific object to file
  -live
    	debug liveness analysis
  -m	print optimization decisions
  -memprofile file
    	write memory profile to file
  -memprofilerate rate
    	set runtime.MemProfileRate to rate
  -mutexprofile file
    	write mutex profile to file
  -newescape
    	enable new escape analysis (default true)
  -nolocalimports
    	reject local (relative) imports
  -o file
    	write output to file
  -p path
    	set expected package import path
  -pack
    	write to file.a instead of file.o
  -r	debug generated wrappers
  -s	warn about composite literals that can be simplified
  -smallframes
    	reduce the size limit for stack allocated objects
  -std
    	compiling standard library
  -symabis file
    	read symbol ABIs from file
  -traceprofile file
    	write an execution trace to file
  -trimpath prefix
    	remove prefix from recorded source file paths
  -v	increase debug verbosity
  -w	debug type checking
  -wb
    	enable write barrier (default true)
</pre></details>

<details><summary><code>/usr/lib/go-1.13/pkg/tool/linux_amd64/compile</code> Output</summary><br><pre>
$ /usr/lib/go-1.13/pkg/tool/linux_amd64/compile
usage: compile [options] file.go...
  -%	debug non-static initializers
  -+	compiling runtime
  -B	disable bounds checking
  -C	disable printing of columns in error messages
  -D path
    	set relative path for local imports
  -E	debug symbol export
  -I directory
    	add directory to import search path
  -K	debug missing line numbers
  -L	show full file names in error messages
  -N	disable optimizations
  -S	print assembly listing
  -V	print version and exit
  -W	debug parse tree after type checking
  -asmhdr file
    	write assembly header to file
  -bench file
    	append benchmark times to file
  -blockprofile file
    	write block profile to file
  -buildid id
    	record id as the build id in the export metadata
  -c int
    	concurrency during compilation, 1 means no concurrency (default 1)
  -complete
    	compiling complete package (no C or assembly)
  -cpuprofile file
    	write cpu profile to file
  -d list
    	print debug information about items in list; try -d help
  -dwarf
    	generate DWARF symbols (default true)
  -dwarfbasentries
    	use base address selection entries in DWARF (default true)
  -dwarflocationlists
    	add location lists to DWARF in optimized mode (default true)
  -dynlink
    	support references to Go symbols defined in other shared libraries
  -e	no limit on number of errors reported
  -gendwarfinl int
    	generate DWARF inline info records (default 2)
  -goversion string
    	required version of the runtime
  -h	halt on error
  -importcfg file
    	read import configuration from file
  -importmap definition
    	add definition of the form source=actual to import map
  -installsuffix suffix
    	set pkg directory suffix
  -j	debug runtime-initialized variables
  -l	disable inlining
  -lang string
    	release to compile for
  -linkobj file
    	write linker-specific object to file
  -live
    	debug liveness analysis
  -m	print optimization decisions
  -memprofile file
    	write memory profile to file
  -memprofilerate rate
    	set runtime.MemProfileRate to rate
  -msan
    	build code compatible with C/C++ memory sanitizer
  -mutexprofile file
    	write mutex profile to file
  -newescape
    	enable new escape analysis (default true)
  -nolocalimports
    	reject local (relative) imports
  -o file
    	write output to file
  -p path
    	set expected package import path
  -pack
    	write to file.a instead of file.o
  -r	debug generated wrappers
  -race
    	enable race detector
  -s	warn about composite literals that can be simplified
  -shared
    	generate code that can be linked into a shared library
  -smallframes
    	reduce the size limit for stack allocated objects
  -std
    	compiling standard library
  -symabis file
    	read symbol ABIs from file
  -traceprofile file
    	write an execution trace to file
  -trimpath prefix
    	remove prefix from recorded source file paths
  -v	increase debug verbosity
  -w	debug type checking
  -wb
    	enable write barrier (default true)
</pre></details>

### Guess
'-shared' flag seems be removed when cross compile mips static library

Does golang support cross compile mips static library ?

**Comment by fantasyRqg** [comment]
after search source code found mips not support `-shared` flag

`// supportsDynlink reports whether or not the code generator for the given
// architecture supports the -shared and -dynlink flags.
func supportsDynlink(arch *sys.Arch) bool {
	return arch.InFamily(sys.AMD64, sys.ARM, sys.ARM64, sys.I386, sys.PPC64, sys.S390X, sys.MIPS)
}`

is it hard to support cross compile mips static library

**Comment by ALTree** [comment]
This is tracked at #21222. Reading the latest message, it seems that someone has been working on it, but it hasn't yet been committed. I'm closing here, feel free to subscribe to that thread for updates.
