### ISSUE TITLE
x/exp/cmd/gorelease: don't accept invalid -version increments

### ISSUE THREAD

**Issue by jayconrod** [golang/go#37558]
`gorelease` should report an error when the `-version` flag is set to a version much higher than any current version. New versions should be consistent with [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

For example, if the only known version of a module (as reported by `go list -m -versions`) is `v1.2.3`, then `-version` may be set to `v1.2.4` or `v1.3.0`. `v1.2.5` and `v1.4.0` would be rejected. `v1.3.1` would also be rejected, since the patch version is not set to zero.

This check would not apply to pre-release versions (e.g., `v1.5.0-pre`) or to versions with major version `v0`.

**Comment by qmuntal** [comment]
> New versions should be consistent with Semantic Versioning.

I can't find in the semantic versioning spec where it specifies that all version increments shall be 1 unit steps, to my understanding it only requires incremental versions, thus skipping versions is allow.

This policy could be too much strict for the CI/CD pipelines that automatically increment the patch using an auto-incremented counter that are hard to reset in case of build failure, p.e. when using a [counter](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#counter) in azure devops.

**Comment by jayconrod** [comment]
It looks like the requirement to increment version numbers by 1 was dropped between semver 1.0.0 and 2.0.0. There's some [discussion](https://github.com/semver/semver/issues/356) on their issue tracker. So enforcing increment-by-1 is too strict. I'll close this issue.

> This policy could be too much strict for the CI/CD pipelines that automatically increment the patch using an auto-incremented counter that are hard to reset in case of build failure, p.e. when using a counter in azure devops.

Using a build counter as a patch version number should work, but I think it's going to be inconvenient in a lot of cases. If there's a compatible change to the API or to visible functionality, you should increment the minor version number and set the patch version number to zero; a counter can't do that. If there are builds on different branches sharing the same counter, it won't grow together with version numbers either.

**Comment by qmuntal** [comment]
Just for completeness, the comment [gorelease.go#L109-L112](https://github.com/golang/exp/blob/master/cmd/gorelease/gorelease.go#L109-L112) should be deleted so no one tries to implement this idea without knowing about this discussion.

> If there's a compatible change to the API or to visible functionality, you should increment the minor version number and set the patch version number to zero; a counter can't do that. If there are builds on different branches sharing the same counter, it won't grow together with version numbers either.

@jayconrod thanks for the advice, I do take care of this cases.
