### ISSUE TITLE
x/mobile/cmd/gomobile: bind command hangs with Go1.14 

### ISSUE THREAD

**Issue by xfxdev** [golang/go#37557]
### What version of Go are you using (`go version`)?

<pre>
go version go1.14 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="~/Library/Caches/go-build"
GOENV="~/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="~/Development/project/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="~/Development/project/go/src/golang.org/x/mobile/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/75/c4jxlwtn76lglc7lrfvz71500000gn/T/go-build704965559=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
`gomobile bind -o app/hello.aar -target=android golang.org/x/mobile/example/bind/hello`

### What did you expect to see?
generate the aar file

### What did you see instead?
stuck at this build, nothing output, no log, no error.

**Comment by cagedmantis** [comment]
Seems similar/related to #36665

/cc @hyangah @eliasnaur

**Comment by changkun** [comment]
This issue is outdated as we are currently not experiencing the issue in Go 1.16 according to https://github.com/golang/go/issues/36665#issuecomment-871882089. Close.
