### ISSUE TITLE
x/exp/cmd/gorelease: main module should not require newer version of itself

### ISSUE THREAD

**Issue by jayconrod** [golang/go#37567]
Suppose that module `example.com/main` requires `example.com/a@v1.0.0`, which requires `example.com/main@v1.5.0`. `gorelease` should report an error when run on `example.com/main` with a proposed version lower than `v1.5.0`. A lower version will not be usable, since MVS will always upgrade the module to a higher version.

**Comment by ackFacu** [comment]
I think this is not supposed to work, independent of the version. This is a cyclic dependency, and golang doesn't support that as far as I know.

**Comment by jayconrod** [comment]
Go allows cyclic dependencies in modules, just not packages.

**Comment by jadekler** [comment]
Can I suggest a new title? 

"x/exp/cmd/gorelease: when main module has cycle to itself, only allow versions greater than latest in cycle"

Or, something to that affect? The current title and description don't seem to match: the title says "cycles are not allowed", the description says "cycles are allowed but version has to be greater than greatest in cycle".

**Comment by jadekler** [comment]
Thoughts after looking into this for a while: 

- Ignore if v0
- Else,
  1. `go mod graph`
  2. Look for same module path
  3. Throw away versions not in same major as suggested
  4. Get latest
  5. See if suggested > latest, report err if not

Does that sound about right @jayconrod ?

**Comment by jayconrod** [comment]
@jadekler I don't think that's quite right: it's okay if a module requires a lower version of itself; a higher version should be an error though.

For example, suppose we're running `gorelease` in module A with `-version=v0.5.0`. A requires B at `v0.1.0`, and B requires A at `v0.6.0`. That should be an error because if anyone requires module A at `v0.5.0`, they'll get `v0.6.0` instead because A v0.5.0 transitively requires a higher version of itself. So the `v0.5.0` won't be usable. It would be okay if B required A at `v0.4.0` instead, or if we were preparing to tag A `v0.6.1`.

The approach you outlined should work except the condition at the end needs to be flipped. Also, this should apply at all major versions including v0.

**Comment by jadekler** [comment]
> Also, this should apply at all major versions including v0.

SG!

-----

Rewriting step `v` in more clear logic:

```
// version == suggested or requested version
if version < latestVersion {
  // report err
}
```

> For example, suppose we're running gorelease in module A with -version=v0.5.0. A requires B at v0.1.0, and B requires A at v0.6.0. That should be an error because if anyone requires module A at v0.5.0, they'll get v0.6.0 instead because A v0.5.0 transitively requires a higher version of itself. [...]
>
> The approach you outlined should work except the condition at the end needs to be flipped.

Logic above seems to hold, AFAICT? `version = v0.5.0`, `latestVersion = v0.6.0`, `version < latestVersion == true` so we err.

Probably missing something though - please let me know if I am!
