### ISSUE TITLE
cmd/go: TestScript/get_update_all changes mtimes in GOROOT/bin

### ISSUE THREAD

**Issue by bcmills** [golang/go#37573]
[2020-02-28T20:15:38-964fac3/linux-amd64-longtest](https://build.golang.org/log/4811a74d508d2c54990e15581d8a24e170321e60)

`test_race_install_cgo` was converted to a script test in [CL 214426](https://golang.org/cl/214426). The old test was not run in parallel, and asserted that `go test -race -i runtime/race` did not reinstall `cmd/cgo`.

I suspect that this flake was caused by some _other_ test somehow overwriting `cmd/cgo` when it should not have.

**Comment by bcmills** [comment]
[2020-03-01T05:45:39-1e9665d/windows-amd64-longtest](https://build.golang.org/log/11b5b5c6ced3c50ed9f0a3db48b2b161770c6ffe)

**Comment by dmitshur** [comment]
Another failure on [windows-amd64-longtest at a7f918c1](https://build.golang.org/log/a3640732285f496cf5c5660ca4205e1f06de7487) from today.

**Comment by bcmills** [comment]
[2020-03-16T22:31:39-2fbca94/windows-amd64-longtest](https://build.golang.org/log/f3091f15cddfcfa9766f9d1c1c4961495844ac48)
[2020-03-15T00:17:52-dad94e7/windows-amd64-longtest](https://build.golang.org/log/4d456733326201f730476f3fa3a0aeafdac334d0)
[2020-03-13T19:06:00-be72e3c/linux-amd64-longtest](https://build.golang.org/log/d7bf084d1cc1a87f72f6478e9a97a3b55496a519)
[2020-03-11T19:59:39-f6a0d72/windows-amd64-longtest](https://build.golang.org/log/9acb13a5d31178aabf033d71a2c15c363e96b492)
[2020-03-09T20:19:25-5fac45a/linux-amd64-longtest](https://build.golang.org/log/6fb7bf6a64306e11d394076c6e61ce232f89a4c6)

I think this is a pairwise-incompatibility with some other test, but so far I haven't been able to track it down running each `cmd/go` test pairwise with `test_race_install_cgo` with a high `-count`.

**Comment by bcmills** [comment]
I'm hoping that [CL 223745](https://golang.org/cl/223745) does the trick, but there may be other interactions lurking.

**Comment by bcmills** [comment]
That CL didn't do it: https://build.golang.org/log/d9ad32ca35be46c7fac61bf609655f3e3100a803

At least the feedback was quick!

**Comment by bcmills** [comment]
FINALLY found it!

Doesn't seem to reproduce at all when running as a not-root user. That's why it was so [redacted] hard to track down.

For some reason, `get_update_all` adjusts file _attributes_ (but not content!) on ~everything in `GOROOT/pkg/tool`, but _only_ when running as root.

```
~/bisect/src$ sudo ../bin/go test cmd/go -run='TestScript/(get_update_all|test_race_install_cgo)'
go test proxy running at GOPROXY=http://127.0.0.1:41653/mod
--- FAIL: TestScript (0.02s)
    --- FAIL: TestScript/test_race_install_cgo (0.95s)
        script_test.go:202:
            # Tests Issue #10500 (0.938s)
            > [!race] skip
            > ! stale cmd/cgo
            > env GOBIN=$WORK/bin
            > go install mtime sametime
            > go tool -n cgo
            [stdout]
            /usr/local/google/home/bcmills/bisect/pkg/tool/linux_amd64/cgo
            > cp stdout cgopath.txt
            > exec $GOBIN/mtime cgopath.txt # get the mtime of the file whose name is in cgopath.txt
            [stdout]
            "2020-03-17T23:53:40.190152563-04:00"
            > cp stdout cgotime_before.txt
            > ? go test -race -i runtime/race
            > exec $GOBIN/mtime cgopath.txt # get the mtime of the file whose name is in cgopath.txt
            [stdout]
            "2020-03-17T23:54:37.402358823-04:00"
            > cp stdout cgotime_after.txt
            > exec $GOBIN/sametime cgotime_before.txt cgotime_after.txt
            [stderr]
            time in cgotime_before.txt (2020-03-17 23:53:40.190152563 -0400 EDT) is not the same as time in cgotime_after.txt (2020-03-17 23:54:37.402358823 -0400 EDT)[exit status 1]
            FAIL: testdata/script/test_race_install_cgo.txt:22: unexpected command failure

FAIL
FAIL    cmd/go  2.813s
FAIL
```

**Comment by bcmills** [comment]
I think I've figured out what's going on.

Our own test from [CL 12174](https://golang.org/cl/12174) (2015) was rendered unparallelizable by our own intentional breakage of the non-intrusive behavior that test was relying on in [CL 76590](https://golang.org/cl/76590) (2017).

https://github.com/golang/go/blob/938ad552cdfdb1707acedcc641c8f8ada642644d/src/cmd/go/internal/work/exec.go#L1465-L1476

**Comment by bcmills** [comment]
Retitled for the diagnosed root cause.

**Comment by bcmills** [comment]
Retitled again. After discussion with @rsc, we decided that the `mtime` change is correct and should be kept, and instead we should prohibit the test version of the `cmd/go` binary from attempting to change metadata in `GOROOT/bin`.
