### ISSUE TITLE
Allow to construct an unsigned constant from a signed one

### ISSUE THREAD

**Issue by zhiqiangxu** [golang/go#37579]
Sometimes it's useful to represent negative number as positive one, like:

```golang
type (
	// SignedType for input
	SignedType int64
	// UnsignedType for output
	UnsignedType uint64
)

const mask = UnsignedType(-1)
```

The above doesn't compile now.

It will be more obvious that this kind of restrict is annoying if go finally supports generics, in that case `mask` may be a value corresponding to the number type(`int16`,`int32`,`int64` etc).

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker for questions about the language.  You will get better and faster answers on a forum.  See https://golang.org/wiki/Questions.  Thanks.

In this case I recommend that you write

```Go
const mask = ^UnsignedType(0)
```
