### ISSUE TITLE
crypto/tls: improve ConnectionState docs

### ISSUE THREAD

**Issue by divjotarora** [golang/go#37572]
Issue #36736 proposes using `tls.ConnectionState` for extra verification during the TLS handshake. Before this is done, it would be good to improve documentation for certain fields to make it clear what the format of each field is. For example, one open question from me is whether or not each chain in `VerifiedChains` is of the form peer->issuer-of-peer->issuer-of-issuer-of-peer->...

**Comment by odeke-em** [comment]
You might be interested in this change @retornam.

**Comment by ianlancetaylor** [comment]
Moving milestone to backlog.
