### ISSUE TITLE
cmd/compile: use some partial register instructions on amd64?

### ISSUE THREAD

**Issue by josharian** [golang/go#37593]
This is the standard way to check whether a value is 32 bit:

```go
func is32bit(x int64) bool {
	return x == int64(int32(x))
}
```

On amd64, this compiles to a MOVLQSX and a CMPQ. However, it could compile to just a TESTL of the top half of the register.

Is there a reason that we don't have any optimizations like this, other than that no one has bothered to write any yet?

**Comment by randall77** [comment]
How would you do that, exactly?

**Comment by josharian** [comment]
I haven’t written the code to check that this actually works, but something like:

Add OpAMD64TESTLU (U for upper), which takes a reg and generates flags.

Add a rewrite rule for the pattern above.

During instruction generation, emit a TESTL that refers to the top half of the register assigned by regalloc.

**Comment by randall77** [comment]
I didn't know you could do that.
The only instructions I know that access the non-lowest part of an integer register are the byte operations that access AH, BH, CH, DH (bits 8-15).

Even if such an instruction exists, I don't see how you would use it. We need to test that bits 32-63 match bit 31. How would you factor bit 31 into the equation? (`x == int64(uint32(x))` might be doable, though.)

**Comment by josharian** [comment]
Oh. I see now I misinterpreted something I read. Never mind. Nothing to see here. 🐑
