### ISSUE TITLE
Hardcoded use of 8.8.8.8 nameserver causes go mod tidy to fail

### ISSUE THREAD

**Issue by dmartin1** [golang/go#37590]
When importing a project hosted on an internal GitHub enterprise server `go mod tidy` fails due to use of 8.8.8.8 nameserver rather than system DNS settings.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, I'm currently running the latest release, 1.14.

### What operating system and processor architecture are you using (`go env`)?

macOS Catalina
Version 10.15.3

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
</pre></details>

### What did you do?

<pre>
go mod init
go mod tidy
</pre>

### What did you expect to see?

I expected a fully formed `go.mod` file to be created with current dependencies and versions defined.

### What did you see instead?

Rather than using system-defined DNS servers for host name resolution it appears that `go mod tidy` has a fixed reference to the 8.8.8.8 nameserver.  8.8.8.8 is not listed as a resolver, confirmed by `scutil --dns`.  git.[internal].com (true domain is masked in this post) resolves just fine with other applications (e.g. ping, go get, host)

<pre>
    git.[internal].com/[project]: git.[internal].com/[project]@vX.X.X: verifying module: git.[internal].com/[project]@vX.X.X: reading https://sum.golang.org/lookup/git.[internal].com/[project]@vX.X.X: 410 Gone
    server response: not found: git.[internal].com/[project]@vX.X.X: unrecognized import path "git.[internal].com/[project]" (https fetch: Get https://git.[internal].com/[project]?go-get=1: dial tcp: lookup git.[internal].com on 8.8.8.8:53: no such host)
</pre>

`go get git.[internal].com/[project]` works just fine as well.

**Comment by jrockway** [comment]
I think that message is actually from the Go module proxy (as indicated by `server response:`), not from `go mod tidy`.  Check out this documentation: https://golang.org/cmd/go/#hdr-Module_configuration_for_non_public_modules

**Comment by dmartin1** [comment]
Yup, that resolved it.  Makes sense given that there wouldn't be a checksum in sum.golang.org.  I appreciate the help!
