### ISSUE TITLE
x/pkgsite: support GitLab nested groups

### ISSUE THREAD

**Issue by steveazz** [golang/go#37592]
### What did you do?

Visit https://pkg.go.dev/gitlab.com/gitlab-org/security-products/analyzers/common/v2

### What did you expect to see?

A Go module showing godocs, show README, version. something similar to https://pkg.go.dev/gitlab.com/akita/akita?tab=doc

### What did you see instead?

It's treated like a subdirectory o godocs, empty README. 

### Information

GitLab supported nested groups https://docs.gitlab.com/ee/user/group/subgroups/index.html#subgroups where you can have projects inside of those groups such as https://gitlab.com/gitlab-org/security-products/analyzers/common. This package should be considered as the root of the module.

**Comment by julieqiu** [comment]
Thanks for the feedback! We're currently discussing this request with our UX team. We'll post on this issue with any updates.

/cc @fflewddur

**Comment by tnir** [comment]
@steveazz Thanks for filing this 🙇

**Comment by julieqiu** [comment]
https://pkg.go.dev/gitlab.com/gitlab-org/security-products/analyzers/common/v2 seems very similar to https://gitlab.com/gitlab-org/security-products/analyzers/common to me. Would you mind elaborating on what you're looking for?

**Comment by bcmills** [comment]
There have been a number of GitLab bugs surrounding the `go-import` metadata they serve for subgroups; see:
* https://gitlab.com/gitlab-org/gitlab/-/issues/36354
* https://gitlab.com/gitlab-org/gitlab-foss/-/issues/32149
and other duplicates of those issues.

It appears that some or all of them have been resolved within the past year or so.

It isn't clear to me whether those fixes have addressed the issues reported here.

**Comment by tnir** [comment]
As bugs on gitlab.com were fixed in 2020-10, this problem looks fixed now. Thanks for confirming.
