### ISSUE TITLE
gomobile android 打包apk真的非常慢

### ISSUE THREAD

**Issue by mgr9525** [golang/go#37596]
<pre>
$ go version
   go1.13.8 windows/amd64
</pre>

感觉是不是每次都会重新下载 .mod 里面的 package。
一开始并不是很慢，但是文件多起来之后gomobile bind 就变得很慢。
![image](https://user-images.githubusercontent.com/9899755/75662544-3d3fab80-5caa-11ea-83e9-10f7de816b47.png)
why??
编译也没有日志，也不知道什么情况。
怎么解决？

**Comment by mvdan** [comment]
Sorry, but the project generally works in English. Also note that there is an issue template you should follow.
