### ISSUE TITLE
net/http: document when (RoundTripper).RoundTrip may return a nil *Response

### ISSUE THREAD

**Issue by bcmills** [golang/go#37599]
(Factored out from #37598.)

The `net/http.RoundTripper` interface is currently ambiguous about what happens in case of errors.

Its documentation says:
> ```go
>     // RoundTrip executes a single HTTP transaction, returning
>     // a Response for the provided Request.
> ```

but:
> ```go
>     // … RoundTrip must return err == nil if it obtained
>     // a response, regardless of the response's HTTP status code.
>     // A non-nil err should be reserved for failure to obtain a
>     // response.
> ```

Unfortunately, it does not specify whether “failure to obtain a response” may correspond to a nil `*Response`, or only one that is only partially populated.

CC @bradfitz @rsc

**Comment by bcmills** [comment]
The answer appears to be that `RoundTrip` **should** return a nil `*Response` if it returns a non-nil `error`.
https://github.com/golang/go/blob/c436eadbc36704012be727457f464d8fbf950638/src/net/http/client.go#L252-L257

**Comment by seankhliao** [comment]
seems to have been declined in [CL 230740](https://go.dev/issue/230740)
