### ISSUE TITLE
appending two slices with default ends modifies base slice

### ISSUE THREAD

**Issue by xeviknal** [golang/go#37604]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13.7
</pre>

### Does this issue reproduce with the latest release?
Yes, go1.14

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xcanalma/.cache/go-build"
GOENV="/home/xcanalma/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xcanalma/.gvm/pkgsets/go1.14/global"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/xcanalma/.gvm/gos/go1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/xcanalma/.gvm/gos/go1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build278629003=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
https://play.golang.org/p/ys0shvSiHkW

### What did you expect to see?
I expect that both append and slice[] operator don't modify the slice variable.
```
[2 3 5 7 11 13]
[2 3 11 13]
[2 3 5 7 11 13]
```

### What did you see instead?
```
[2 3 5 7 11 13]
[2 3 11 13]
[2 3 11 13 11 13]
```

**Comment by renthraysk** [comment]
If don't want to modify the backing memory of a slice with append, limit the capacity, which will force append to allocate a new slice plus memory.
```
s2 := append(s[0:2:2], s[4:]...)
```

**Comment by dmitshur** [comment]
I believe that behavior matches what is written in the [Go specification](https://golang.org/ref/spec). Do you see an inconsistency?

Also see https://golang.org/wiki/SliceTricks.

**Comment by xeviknal** [comment]
Thanks for the explanation. Once the behind the scenes of a slice is clear, the append methods makes more sense. However, it looks like the passed array is read-only and a new array is returned.

Didn't know the 3-index operand. Interesting one. Thanks and closing the issue.
