### ISSUE TITLE
misc/cgo/test: occasional "handler not on signal stack" failures on aix-ppc64 builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#37609]
[2020-03-02T17:40:00-5e4da0a/aix-ppc64](https://build.golang.org/log/520fd069ef1d9a946e47ac9b02e73ea047ed4700)
[2020-02-26T17:58:41-a1103dc/aix-ppc64](https://build.golang.org/log/47d830a711ec72173e735abada1025362ea14cce)
[2020-01-02T21:41:13-ffbc027/aix-ppc64](https://build.golang.org/log/5cb0d8ae9bfe3f78ef91f519cb5a5a3c6fdf6af5)

```
##### ../misc/cgo/test
PASS
scatter = 110176d70
sqrt is: 0
hello from C
ok  	misc/cgo/test	7.066s
signal 16 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

runtime stack:
runtime.throw(0x100177747, 0x39)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/panic.go:1112 +0x68 fp=0x110186460 sp=0x110186420 pc=0x100037b08
runtime.sigNotOnStack(0x1000000000)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/signal_unix.go:871 +0x7c fp=0x110186490 sp=0x110186460 pc=0x100051c7c
runtime.adjustSignalStack(0x1000110780, 0xa0001000020aa80, 0x110186570, 0x110028770)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/signal_unix.go:489 +0x288 fp=0x110186528 sp=0x110186490 pc=0x1000508d8
runtime.sigtrampgo(0x1010168b98, 0x110186980, 0x1101866d0)
	/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/src/runtime/signal_unix.go:432 +0x148 fp=0x1101865b0 sp=0x110186528 pc=0x100050518
runtime: unexpected return pc for sigtramp called from 0x1100181b0
```

CC @ianlancetaylor @trex58 @Helflym

**Comment by ianlancetaylor** [comment]
Signal 16 appears to be `SIGURG` so this is most likely related to preemption.

Can't see why this would only happen on AIX.

**Comment by bcmills** [comment]
Maybe the AIX-specific detail is just timing? (Perhaps the other builders end up live enough not to trigger any preemption signals.)

**Comment by Helflym** [comment]
I can't manage to reproduce it on my environment for now. 
It might come from [misc/cgo/test/sigaltstack.go](https://github.com/golang/go/blob/master/misc/cgo/test/sigaltstack.go) which indeed doesn't add the `SA_ONSTACK`. And it would be trigger because AIX is slow enough to have a preemption signals to happen during this test. Would it be possible ? 
Note that there is no mention of this test during the panic, it might also be a problem with the `restoreSignalStack()` function.

**Comment by ianlancetaylor** [comment]
As far as I can see misc/cgo/test/sigaltstack.go doesn't call `sigaction`, which is where the `SA_ONSTACK` flag needs to be used.

But it's definitely worth checking whether that is the specific test where this problem occurs.  There may be some disagreement between the Go runtime and the AIX C library about how `sigaltstack` works.

**Comment by Helflym** [comment]
`man sigaltstack` on AIX doesn't mention that `sigaction` must be called for the new stack to be taken into account. So, I'm guessing that once `sigaltstack` has been called the next signal will go on the new stack which doesn't have the SA_ONSTACK flag. 

Would it be a problem on Linux to add the SA_ONSTACK flag ?

**Comment by Helflym** [comment]
Adding a `for{}` after `c.changeSignalStack()` is triggering the bug everytime. However, that's not the case on Linux, even with the `for` everything is fine. 

However, adding `SA_ONSTACK` before calling `sigaltstack` doesn't work either. `EINVAL` is returned

**Comment by ianlancetaylor** [comment]
I don't understand where you are adding `SA_ONSTACK`.

**Comment by Helflym** [comment]
> I don't understand where you are adding `SA_ONSTACK`.

[Here](https://github.com/golang/go/blob/master/misc/cgo/test/sigaltstack.go#L24). I thought that adding `SA_ONSTACK` would force the signal to be delivered on the new stack. But `sigaltstack` doesn't allow `ss_flags` to be `SA_ONSTACK`

**Comment by ianlancetaylor** [comment]
`SA_ONSTACK` is a flag for `sigaction`.  It's not a flag for `sigaltstack`.

**Comment by Helflym** [comment]
Yeah, I didn't know that before. 
But on Linux, if `sigaltstack` is called without `sigaction` what's happening ? The next signal is supposed to be delivered on the new stack only if the previous `sigaction` have been made with `SA_ONFLAG` ?

**Comment by Helflym** [comment]
Alright, I know what's going on... And we already had this problem within the runtime (cf https://go-review.googlesource.com/c/go/+/164012). 
The stack is simply too tight for the actual go handler.
