### ISSUE TITLE
x/build: freebsd-arm64-dmgk builder is down

### ISSUE THREAD

**Issue by bcmills** [golang/go#37601]
https://build.golang.org/log/3e774b42219c4198c3c0e4155ab4f355c7842d15
```
# time.test
/tmp/workdir-host-freebsd-arm64-dmgk/go/pkg/tool/freebsd_arm64/link: flushing $WORK/b061/time.test: input/output error
FAIL	time [build failed]
FAIL
go: creating work dir: mkdir /tmp/workdir-host-freebsd-arm64-dmgk/tmp/go-build151329030: no space left on device
```

And https://farmer.golang.org/ reports that this builder is missing.

It's not clear to me why this builder should have run out of space. (Is something misconfigured such that it is failing to clean up temporary directories after a run?)

See also #35058.

CC @dmgk @dmitshur @toothrot @cagedmantis @andybons

**Comment by dmgk** [comment]
@bcmills I was rebuidling world to update to the latest 12.1-STABLE and it ran out of space overnight. Should be fixed now.
