### ISSUE TITLE
Add hook for event - server bind to address/port

### ISSUE THREAD

**Issue by ORESoftware** [golang/go#37606]
go version: 1.13

I am looking for an API that allows me to listen for initial bind to the address/port

![Screenshot from 2020-03-02 11-33-42](https://user-images.githubusercontent.com/11139560/75710709-da362080-5c79-11ea-97b6-b88ea933aef4.png)

so it would like this:

### before 
```golang
s := &http.Server{
	Addr:           fmt.Sprintf("%s:%d", serverAddress, portNumber),
	Handler:        m,
	ReadTimeout:    0, // 1 * time.Minute,
	WriteTimeout:   30 * time.Minute,
	MaxHeaderBytes: 1 << 20,
}
```

### after 
```golang
s := &http.Server{
	Addr:           fmt.Sprintf("%s:%d", serverAddress, portNumber),
	Handler:        m,
	ReadTimeout:    0, // 1 * time.Minute,
	WriteTimeout:   30 * time.Minute,
	MaxHeaderBytes: 1 << 20,
        OnBind: func(){
             fmt.Println("server is listening on: ", s.Addr)
        }
}
```

there is no easy way to hook into this even given the existing api, it would require a refactor into separate Listen and Serve calls which should be unnecessary.

**Comment by ianlancetaylor** [comment]
The Go project doesn't use the issue tracker for questions.  You will get better and faster answers by using a forum.  See https://golang.org/wiki/Questions.

I don't personally understand your question.  Why not just use `net.Listen` and `http.(*Server).Serve`?
