### ISSUE TITLE
all: remove darwin/386

### ISSUE THREAD

**Issue by andybons** [golang/go#37610]
Per #34749, we’re going to remove darwin/386 for Go 1.15. This is a tracking issue for that work.

Some affected files (taken from above issue. Thanks, @bradfitz):

```
./runtime/rt0_darwin_386.s
./runtime/cgo/gcc_darwin_386.c
./runtime/signal_darwin_386.go
./runtime/defs_darwin_386.go
./runtime/sys_darwin_386.s
./debug/macho/testdata/gcc-386-darwin-exec
./debug/macho/testdata/fat-gcc-386-amd64-darwin-exec
./debug/macho/testdata/clang-386-darwin.obj
./debug/macho/testdata/clang-386-darwin-exec-with-rpath
./cmd/vendor/golang.org/x/sys/unix/zsyscall_darwin_386.1_11.go
./cmd/vendor/golang.org/x/sys/unix/asm_darwin_386.s
./cmd/vendor/golang.org/x/sys/unix/zerrors_darwin_386.go
./cmd/vendor/golang.org/x/sys/unix/syscall_darwin_386.go
./cmd/vendor/golang.org/x/sys/unix/zsyscall_darwin_386.s
./cmd/vendor/golang.org/x/sys/unix/zsysnum_darwin_386.go
./cmd/vendor/golang.org/x/sys/unix/zsyscall_darwin_386.go
./cmd/vendor/golang.org/x/sys/unix/ztypes_darwin_386.go
./syscall/asm_darwin_386.s
./syscall/zerrors_darwin_386.go
./syscall/syscall_darwin_386.go
./syscall/zsyscall_darwin_386.s
./syscall/zsysnum_darwin_386.go
./syscall/zsyscall_darwin_386.go
./syscall/ztypes_darwin_386.go
```

But also stuff in ~debug/macho~ (see below comment), cmd/link, etc.

**Comment by ianlancetaylor** [comment]
Just a note that I don't think we should remove any 386 support from debug/macho.  The debug/macho package is for analyzing Mach-O files, and we should continue to support examining Mach-O 386 files even if we can no longer generate them.

**Comment by andybons** [comment]
@ianlancetaylor sgtm. Thanks for the note.

**Comment by FiloSottile** [comment]
Can we drop the darwin/386 builders from tip? I am failing them in CL 227037 but it's not worth fixing them since we are dropping the target.

**Comment by dmitshur** [comment]
@FiloSottile Yes, we should stop running those builders on tip (but they should still run on 1.14 and older release branches).

The `misc-compile-darwin` builder get its list of exact GOOS/GOARCH pairs from `go tool dist list` output (see [here](https://github.com/golang/build/blob/61705b562fc995a53af15476c91f6ad3dcf1aae8/dashboard/builders.go#L1513-L1517) and [here](https://github.com/golang/go/blob/fff7509d472778cae5e652dbe2479929c666c24f/src/buildall.bash#L39)). So it'll stop being tested on as soon as `darwin/386` is removed from tip.

I see @bradfitz already sent [CL 226985](https://golang.org/cl/226985) for that. If you want, you could rebase your CL on top to test it.
