### ISSUE TITLE
when f != f is true?

### ISSUE THREAD

**Issue by boaz-foux** [golang/go#37619]
https://github.com/golang/go/blob/5b15941c61f478b8ed08b76a27186527ba73d273/src/syscall/js/js.go#L82

**Comment by randall77** [comment]
When f is a floating-point NaN (or a struct or array containing such a beast).

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only. Please see https://github.com/golang/go/wiki/Questions for some more appropriate forums for your question.

**Comment by boaz-foux** [comment]
got it..,
if you'll be kind to answer: 
https://stackoverflow.com/questions/60502238/when-does-unequal-operator-of-the-reference-is-true-in-go
it will be great.
