### ISSUE TITLE
plugin: unclear how to reference a package under test from a plugin

### ISSUE THREAD

**Issue by gonzojive** [golang/go#37618]
Testing interactions between a plugin and a package under test is complicated.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/red/.cache/go-build"
GOENV="/home/red/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/red/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/red/git/go_example_failed_plugin_test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build817699318=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Tried to reference the package being tested by `go test` from a plugin. It's unclear how to do this, and thus how to test interactions between plugins and packages being tested.

Reproduction is here:
https://github.com/gonzojive/go_example_failed_plugin_test

```shell
git clone https://github.com/gonzojive/go_example_failed_plugin_test
cd go_example_failed_plugin_test
go test codeloader/*.go
```

### What did you expect to see?

All tests should pass

### What did you see instead?

```
$  go test codeloader/*.go
will reference project root "/home/red/git/go_example_failed_plugin_test" when compiling pluginsThe code was loaded!--- FAIL: TestConfig_CompileAndLoadCompileTimeCode (1.21s)
    --- FAIL: TestConfig_CompileAndLoadCompileTimeCode/show_example_of_interaction_of_a_plugin_with_a_non-test_package#01 (0.59s)
        codeloader_test.go:144: manipulates RegisteredPlugins: got [], want ["interaction confirmed"]
FAIL
FAIL    command-line-arguments  1.223s
FAIL
```

**Comment by seankhliao** [comment]
I believe the answer is you can't, and you should use testing's black box testing support (package foo_test) and import the package you need to reference.
