### ISSUE TITLE
runtime: golang 1.14.rc1 3-5% performance regression from golang 1.13 during protobuf marshalling [1.14 backport]

### ISSUE THREAD

**Issue by dmitshur** [golang/go#37613]
@randall77 requested issue #37086 to be considered for backport to the next 1.14 minor release.

> @gopherbot ple​ase open a backport issue.
> 
> I don't think this performance regression [qualifies for a backport](https://github.com/golang/go/wiki/MinorReleases), but I'll let the release guys make that call.

**Comment by randall77** [comment]
Turns out we need to backport this patch anyway to fix #37721 .
So it's not just a performance thing.

**Comment by dmitshur** [comment]
Approved as this is a regression in 1.14 only and has no workaround, and is needed to backport a fix for a serious issue #37721.
