### ISSUE TITLE
time: document that RFC3339 accepts invalid formats when used with Parse

### ISSUE THREAD

**Issue by xdg** [golang/go#37616]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
It reproduces on play.golang.org and the underlying issue is still present in the source.

### What operating system and processor architecture are you using (`go env`)?

darwin/amd64

### What did you do?

Parsed a faulty ISO 8601 string with a single-digit hour using `time.RFC3339`.  E.g. `2020-02-02T2:02:02Z`.

### What did you expect to see?

I expected this parse to error because [RFC-3339 sec 5.6](https://tools.ietf.org/html/rfc3339#section-5.6) defines the following token, requiring two digits for the hour:
```
time-hour       = 2DIGIT  ; 00-23
```

### What did you see instead?

The parse succeeded.

This could be fixed by changing `time.RFC3339` to `2006-01-02T03:04:05Z07:00`.  If this is deemed a backward incompatible change, adding a new `time.RFC3339Strict` constant would also be an acceptable option.

See https://play.golang.org/p/6qyFYfx6pMr for example with one and two-digit years with `time.Parse3339` and the stricter version.

**Comment by ianlancetaylor** [comment]
As the documentation says, " RFC3339, RFC822, RFC822Z, RFC1123, and RFC1123Z are useful for formatting; when used with time.Parse they do not accept all the time formats permitted by the RFCs."

We can't change `time.RFC3339` because that would break backward compatibility.

We aren't going to add a new constant just to use with `time.Parse`, because we already document that these constants don't do the right thing when used with `time.Parse`.

**Comment by xdg** [comment]
> when used with time.Parse they do not accept all the time formats permitted by the RFCs

I hear your point, but the existing documentation says only that they don't accept all formats permitted. The docs don't say that they do ***accept*** formats ***prohibited*** by the RFCs, which is what I demonstrate.

If you don't want to change the existing constant (which I fully accept), or provide correct constants (which I question), what do you think about one or both of these:

* adding documentation to caveat that they accept prohibited formats
* providing an example of the stricter RFC3339 format (so that users can copy/paste it for use)

I'm happy to send a PR if we can agree in advance on what it should generally contain.

**Comment by antong** [comment]
The title and description mention two digit "year". Is this intentional, or should it say "hour"?

**Comment by xdg** [comment]
Yes, thanks.  Fixed the title.

**Comment by ianlancetaylor** [comment]
I don't think it is possible to write a time format that works with `time.Parse` and that accepts exactly and only the time formats permitted by RFC 3339.  The `time.RFC3339` value produces a valid RFC 3339 time format when used with `time.Time.Format`.  It does not and cannot work with `time.Parse`.

I'm fine with adding a clause saying that the various formats accept invalid strings when used with `time.Parse`.  Maybe we can shorten the existing clause while we're at it.
