### ISSUE TITLE
cmd/cgo: fails to generate certain types with Go 1.14

### ISSUE THREAD

**Issue by tklauser** [golang/go#37621]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, it also reproduces with tip. However, it doesn't reproduce with go1.13.8

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tklauser/.cache/go-build"
GOENV="/home/tklauser/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tklauser/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/tklauser/src/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build562307077=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
$ cat repro.go
package unix

/*
#include &lt;time.h&gt;
#include &lt;linux/errqueue.h&gt;
*/
import "C"

type Timespec C.struct_timespec

type ScmTimestamping C.struct_scm_timestamping

$ go1.14 tool cgo -godefs repro.go
// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs cgo-fail-go1.14.go

package unix

type Timespec struct {
	Sec	int64
	Nsec	int64
}

type ScmTimestamping struct {
	Ts [3]_Ctype_struct_timespec
}
</pre>

For some reason cgo is unable to resolve `__Ctype_struct_timespec` to `Timespec` in Go 1.14, while it does with Go 1.13 (see below). This looks like a regression to me.

Found while trying to update the code generation in `golang.org/x/sys/unix` to use Go 1.14.

### What did you expect to see?

<pre>
$ go1.13.8 tool cgo -godefs repro.go
// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs cgo-fail-go1.14.go

package unix

type Timespec struct {
	Sec	int64
	Nsec	int64
}

type ScmTimestamping struct {
	Ts [3]Timespec
}
</pre>

### What did you see instead?

See output of `go1.14 tool cgo -godefs repro.go` above.

**Comment by tklauser** [comment]
@gopherbot please consider this for backport to 1.14, it's a regression.

**Comment by tklauser** [comment]
> Found while trying to update the code generation in `golang.org/x/sys/unix` to use Go 1.14.

FWIW, this was the resulting diff when I tried to regenerate the files in `x/sys/unix`:

```
diff --git a/unix/linux/Dockerfile b/unix/linux/Dockerfile
index 0e4a930959aa..e93b354c56ab 100644
--- a/unix/linux/Dockerfile
+++ b/unix/linux/Dockerfile
@@ -18,9 +18,9 @@ RUN git clone --branch v5.5 --depth 1 https://kernel.googlesource.com/pub/scm/li
 RUN git clone --branch release/2.31/master --depth 1 git://sourceware.org/git/glibc.git
 
 # Get Go
-ENV GOLANG_VERSION 1.13.7
+ENV GOLANG_VERSION 1.14
 ENV GOLANG_DOWNLOAD_URL https://golang.org/dl/go$GOLANG_VERSION.linux-amd64.tar.gz
-ENV GOLANG_DOWNLOAD_SHA256 b3dd4bd781a0271b33168e627f7f43886b4c5d1c794a4015abf34e99c6526ca3
+ENV GOLANG_DOWNLOAD_SHA256 08df79b46b0adf498ea9f320a0f23d6ec59e9003660b4c9c1ce8e5e2c6f823ca
 
 RUN curl -fsSL "$GOLANG_DOWNLOAD_URL" -o golang.tar.gz \
     && echo "$GOLANG_DOWNLOAD_SHA256  golang.tar.gz" | sha256sum -c - \
diff --git a/unix/ztypes_linux.go b/unix/ztypes_linux.go
index 6c81e7515c87..ee0f94a1f393 100644
--- a/unix/ztypes_linux.go
+++ b/unix/ztypes_linux.go
@@ -1757,7 +1757,7 @@ const (
 )
 
 type ScmTimestamping struct {
-       Ts [3]Timespec
+       Ts [3]_Ctype_struct_timespec
 }
 
 const (
diff --git a/unix/ztypes_linux_s390x.go b/unix/ztypes_linux_s390x.go
index a111387b3ac5..44d756de41c7 100644
--- a/unix/ztypes_linux_s390x.go
+++ b/unix/ztypes_linux_s390x.go
@@ -165,12 +165,12 @@ const (
 )
 
 type PtraceRegs struct {
-       Psw                      PtracePsw
+       Psw                      _Ctype_struct__user_psw_struct
        Gprs                     [16]uint64
        Acrs                     [16]uint32
        Orig_gpr2                uint64
-       Fp_regs                  PtraceFpregs
-       Per_info                 PtracePer
+       Fp_regs                  _Ctype_struct__user_fpregs_struct
+       Per_info                 _Ctype_struct__user_per_struct
        Ieee_instruction_pointer uint64
 }
```

**Comment by ianlancetaylor** [comment]
See also #37479.  I guess we need to figure this out.

**Comment by bcmills** [comment]
Possibly a side-effect of [CL 181857](https://golang.org/cl/181857)?

**Comment by tklauser** [comment]
> Possibly a side-effect of [CL 181857](https://golang.org/cl/181857)?

Yes, [CL 181857](https://golang.org/cl/181857) seems to have introduced this regression. If I revert the CL, the generated code is as expected.

@ianlancetaylor also traced down #37479 to the same CL.
