### ISSUE TITLE
x/pkgsite: flag packages that are no longer present in the latest version of the containing module

### ISSUE THREAD

**Issue by bcmills** [golang/go#37631]
### What is the URL of the page with the issue?

https://pkg.go.dev/golang.org/x/tools/cmd/vet?tab=doc 

### What is your user agent?

```
Mozilla/5.0 (X11; CrOS x86_64 12607.82.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.123 Safari/537.36 
``` 
  
### Screenshot

![cmd-vet](https://user-images.githubusercontent.com/5200974/75789543-d9fc5a80-5d37-11ea-922c-fb925547f7b2.png)
![old-tools](https://user-images.githubusercontent.com/5200974/75789542-d9fc5a80-5d37-11ea-9a59-ed843bdc185b.png)
 

### What did you do?
 
Directly open the doc page for package `golang.org/x/tools/cmd/vet`.

### What did you expect to see?
 
A prominent warning that the package in question no longer exists, ideally with similar style/coloration to the (currently-red) “Go to latest” link on the module overview page.

### What did you see instead?

A normal documentation page for a very old version of `golang.org/x/tools/cmd/vet`, which was removed from the repo [back in 2016](https://golang.org/cl/20810), along with a cheerful blue “Latest” badge.

**Comment by bcmills** [comment]
(FYI @julieqiu @jba @findleyr)

**Comment by julieqiu** [comment]
Thanks for the feedback! 

/cc @fflewddur

**Comment by jba** [comment]
We now show an icon on the Latest badge:

![image](https://user-images.githubusercontent.com/18483045/104742684-bd330080-5718-11eb-9b92-e014a38063a0.png)

Clicking on the icon brings up the tooltip "This package is not in the latest version of its module."
