### ISSUE TITLE
x/blog:

### ISSUE THREAD

**Issue by Ramya743** [golang/go#37649]
Hi,

### What version of Go are you using (`go version`)?
$ go version
'go' is not recognized as an internal or external command,
operable program or batch file.

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
$ go env
'go' is not recognized as an internal or external command,
operable program or batch file.

### What did you do?
I have downloaded go 1.14 and while extracting go 1.14 ,some of the exe in go 1.14 got deleted from Mcafee.

### What did you expect to see?
I want to install the go 1.14 without deleting any exe in go 1.14

### What did you see instead?
Some of the .exe files got deleted from go 1.14 by Mcafee. I have observed the notifications from Mcafee.
Here attached the screenshot for reference.
![Screenshot (5)](https://user-images.githubusercontent.com/38774951/75859050-55850700-5e1f-11ea-9a5c-89bf3873a9f6.png)

Please provide a soultion for this.

Thank you,
G.Ramya

**Comment by agnivade** [comment]
Please don't create duplicate (https://github.com/golang/go/issues/37648) issues. Thanks.
