### ISSUE TITLE
Suggestion: Allow for emojiC/ASM Code Embedding

### ISSUE THREAD

**Issue by castrated** [golang/go#37668]
Perhaps allow for things that can be accomplished memory-wise in the style of emojiC/ASM in with Go?
Alternatively, I could add complete porting to Go from emojiC/ASM.

**Comment by dmitshur** [comment]
Thanks for making an issue. It's not clear what this suggestion is referring to, can you elaborate please?

**Comment by castrated** [comment]
in emojiC/ASM, you can make entire functions into a non-assigned emoji series.
so if you wanted to say, make 😆("%d"); work within 😋😋😋, you can, so long as it isn't already being used for something else.
in the event a memory address doesn't have a hex/UTF-8 equivalent, Fs are added to the address series until be becomes either one or multiple emojis, and thus becoming a new addressable emoji for storage.
this allows for secure memory addressing and a lot more customization to code.

**Comment by dmitshur** [comment]
Sorry, I'm having trouble understanding what this suggestion is referring to concretely.

Can you please answer the following 3 questions from the issue template, perhaps that can help make it more clear:

-	What did you do?
-	What did you expect to see?
-	What did you see instead?

Thanks!

**Comment by castrated** [comment]
-     What did you do?

spoke in the golang discord about the potential of golang
-     What did you expect to see?

emoji memory addressing in golang
-     What did you see instead?

no emoji memory addressing in golang

**Comment by ianlancetaylor** [comment]
Are you referring to https://github.com/castrated/emojiC?  We aren't going to support that in Go.

**Comment by castrated** [comment]
darn, ok
worth a shot

**Comment by ALTree** [comment]
Closing, then.
