### ISSUE TITLE
go script should work in ideal world

### ISSUE THREAD

**Issue by ORESoftware** [golang/go#37666]
I am on go version
```
go version go1.13.7 linux/amd64
```

something like this should work:

```bash
#!/usr/bin/env bash

go run <(cat  <<EOF
package main

import "log"

func main(){
  log.Println("here 123")
}
EOF
)
```

if I run it I get:

> go: cannot find main module, but found .git/config in /home/oleg/codes/channelmeter/cm-scripts
>         to create a module there, run:
>         go mod init
>

**Comment by cherrymui** [comment]
```
% cat hello.go
//usr/bin/env go run "$0"; exit
package main; func main() { println("hello") }
% chmod +x hello.go
% ./hello.go
hello
```

It needs to be named .go to work.
