### ISSUE TITLE
net/http/httputil: data race in DumpRequestOut

### ISSUE THREAD

**Issue by schreik** [golang/go#37669]
### What version of Go are you using (`go version`)? 
1.12.17 

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?

I am using AWS Go SDK code has a call to
<pre>
	b, err := httputil.DumpRequestOut(t.HTTPRequest, logBody)
</pre>

Unit test are running with GORACE=1 and fail inside the DumpRequestOut. 

From the look at the code, DumpRequestOut creates a Go routine at line 115, which reads from req.Body, and then immediately changes req.Body to "save" at line 128 without waiting for routine to finish

<pre>
	// Wait for the request before replying with a dummy response:
	go func() {
		req, err := http.ReadRequest(bufio.NewReader(pr))
		if err == nil {
			// Ensure all the body is read; otherwise
			// we'll get a partial dump.
			io.Copy(ioutil.Discard, req.Body)
			req.Body.Close()
		}
		dr.c <- strings.NewReader("HTTP/1.1 204 No Content\r\nConnection: close\r\n\r\n")
	}()

	_, err := t.RoundTrip(reqSend)

	req.Body = save
</pre>

### What did you expect to see?
No data race.

### What did you see instead?
<pre>
WARNING: DATA RACE
Write at 0x00c00072a040 by goroutine 66:
  net/http/httputil.DumpRequestOut()
      /usr/local/go/src/net/http/httputil/dump.go:128 +0x72e
  github.com/aws/aws-sdk-go/aws/client.logRequest()
      go/src/github.com/aws/aws-sdk-go/aws/client/logger.go:59 +0x130
  ...

Previous read at 0x00c00072a040 by goroutine 146:
  net/http.newTransferWriter()
      /usr/local/go/src/net/http/transfer.go:96 +0x10b7
  net/http.(*Request).write()
      /usr/local/go/src/net/http/request.go:601 +0x623
  net/http.(*persistConn).writeLoop()
      /usr/local/go/src/net/http/transport.go:1982 +0x321
</pre>

**Comment by odeke-em** [comment]
Hello @schreik, thank you for filing this issue and welcome to the Go project!

So we got the same bug report in https://github.com/golang/go/issues/32571, and @agnivade fixed it for Go1.14 with CL https://go-review.googlesource.com/c/go/+/182037 aka commit https://github.com/golang/go/commit/e7a4ab427d0df0f1b18c5899552bed6e3bc75266. This issue had existed for a while.

Could you please try upgrading to Go1.14?

Thank you.

**Comment by schreik** [comment]
@odeke-em Thanks for looking into it! Our build system is quite complicated and we have periodic schedule go upgrade rollout. It will take a bit of time for me to learn how to upgrade go for my test only. I will try to build an isolated test to repro the issue.

Looking at the commit you mentioned though, it does not look like it will solve the issue, since modification of `req.Body` at line 135 is not synchronized with reading the value in go routine at line 124-125.

Thanks

**Comment by nerd2** [comment]
We see (I believe) the same issue with Go 1.14.1

```
==================
WARNING: DATA RACE
Read at 0x00c0024d7640 by goroutine 131:
  net/http.newTransferWriter()
      GOROOT/src/net/http/transfer.go:83 +0x15a6
  net/http.(*Request).write()
      GOROOT/src/net/http/request.go:631 +0x61e
  net/http.(*persistConn).writeLoop()
      GOROOT/src/net/http/transport.go:2280 +0x331

Previous write at 0x00c0024d7640 by goroutine 295:
  net/http/httputil.DumpRequestOut()
      GOROOT/src/net/http/httputil/dump.go:147 +0x7d5
  repo.jazznetworks.com/vaion/vaion/lib/http_client.(*loggingRoundTripper).RoundTrip()
      lib/http_client/http_logging_round_tripper.go:22 +0x5e4
  net/http.send()
      GOROOT/src/net/http/client.go:252 +0x6a3
  net/http.(*Client).send()
      GOROOT/src/net/http/client.go:176 +0x1ca
  net/http.(*Client).do()
      GOROOT/src/net/http/client.go:699 +0x2cc
  net/http.(*Client).Do()
      GOROOT/src/net/http/client.go:567 +0x587
```

**Comment by nerd2** [comment]
Potential fix
```
@@ -96,10 +96,8 @@
 	// switch to http so the Transport doesn't try to do an SSL
 	// negotiation with our dumpConn and its bytes.Buffer & pipe.
 	// The wire format for https and http are the same, anyway.
-	reqSend := req
+	reqSend := *req
 	if req.URL.Scheme == "https" {
-		reqSend = new(http.Request)
-		*reqSend = *req
 		reqSend.URL = new(url.URL)
 		*reqSend.URL = *req.URL
 		reqSend.URL.Scheme = "http"
@@ -142,7 +140,7 @@
 		}
 	}()
 
-	_, err := t.RoundTrip(reqSend)
+	_, err := t.RoundTrip(&reqSend)
 
 	req.Body = save
 	if err != nil {
```

**Comment by bcmills** [comment]
@nerd2, if you have a fix, please [contribute it](https://golang.org/doc/contribute.html)! 🙂

**Comment by bcmills** [comment]
@schreik, the race-detector output that you provided looks like it is on the server side, but `DumpRequestOut` is specifically intended for the client side. Have you opened an issue with https://github.com/aws/aws-sdk-go to verify that the usage on their side is correct?

**Comment by bcmills** [comment]
@nerd2, I can't see the source code for `repo.jazznetworks.com/vaion/vaion/lib/http_client`. Are you sure that the race isn't being introduced there? (A standalone reproducer would be very helpful.)

**Comment by fraenkel** [comment]
This is the same issue as #38352.
One cannot call DumpRequestOut in the middle of the Request processing because the Body can be manipulated by the Transport and will be drained by DumpRequestOut.

**Comment by nerd2** [comment]
Well that's fun! Unfortunately the race is inside DumpRequestOut itself, racing between the local transport and the cancellation of the request context.
I have updated https://github.com/nerd2/bugs/blob/master/37669/dump_test.go to remove the transport wrapping and actual request making which was unnecessary.

`==================
WARNING: DATA RACE
Read at 0x00c00018a540 by goroutine 217:
  net/http.newTransferWriter()
      /usr/local/go/src/net/http/transfer.go:83 +0x15a6
  net/http.(*Request).write()
      /usr/local/go/src/net/http/request.go:631 +0x61e
  net/http.(*persistConn).writeLoop()
      /usr/local/go/src/net/http/transport.go:2281 +0x33e

Previous write at 0x00c00018a540 by goroutine 66:
  net/http/httputil.DumpRequestOut()
      /usr/local/go/src/net/http/httputil/dump.go:147 +0x7d5
  github.com/nerd2/bugs/37669.testDumpRoundTripRace()
      /home/sam/go/src/github.com/nerd2/bugs/37669/dump_test.go:52 +0x692
  github.com/nerd2/bugs/37669.TestDumpRoundTripRace.func1()
      /home/sam/go/src/github.com/nerd2/bugs/37669/dump_test.go:23 +0x52
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:992 +0x1eb

Goroutine 217 (running) created at:
  net/http.(*Transport).dialConn()
      /usr/local/go/src/net/http/transport.go:1648 +0xc33
  net/http.(*Transport).dialConnFor()
      /usr/local/go/src/net/http/transport.go:1365 +0x14f

Goroutine 66 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1043 +0x660
  github.com/nerd2/bugs/37669.TestDumpRoundTripRace()
      /home/sam/go/src/github.com/nerd2/bugs/37669/dump_test.go:22 +0xc4
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:992 +0x1eb
==================
`

**Comment by odeke-em** [comment]
Hasn’t yet been fixed.

**Comment by odeke-em** [comment]
Gobot, this issue is still valid.

**Comment by bcmills** [comment]
Reverted the fix CL due to failing tests, so reopening.
