### ISSUE TITLE
x/crypto: Add git tag

### ISSUE THREAD

**Issue by itsmontoya** [golang/go#37678]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GO111MODULE=""
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOOS="darwin"
GOPROXY="https://proxy.golang.org,direct"
GOSUMDB="sum.golang.org"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/panda/go/src/github.com/Hatch1fy/boards/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?
Attempted to set proper version for go mod dependencies when importing `x/crypto`

### What did you expect to see?
Any version, even `v0.1.0`

### What did you see instead?
No version set. Each library has a slightly different variant depending on which timestamp they are using.

**Comment by ALTree** [comment]
Closing as a dup of #21324.
