### ISSUE TITLE
proposal: Go 2: allow conversion of defined types of directional channels

### ISSUE THREAD

**Issue by Anaminus** [golang/go#37691]
Consider the following program:

```go
package main

func main() {
	type Channel chan int
	type SendChannel chan<- int
	type ReceiveChannel <-chan int

	var channel Channel
	var send SendChannel
	var receive ReceiveChannel
	_, _, _ = channel, send, receive

	// Not allowed:
	send = SendChannel(channel)       // cannot convert channel (variable of type Channel) to SendChannel
	receive = ReceiveChannel(channel) // cannot convert channel (variable of type Channel) to ReceiveChannel

	// Allowed:
	send = SendChannel((chan<- int)(channel))
	receive = ReceiveChannel((<-chan int)(channel))
}
```

As demonstrated, it is not allowed to convert a defined bidirectional channel type to a defined unidirectional channel type. This is caused by the following condition in the [Go spec](https://golang.org/ref/spec#Assignability):

> ### Assignability
> ...
> - x is a bidirectional channel value, T is a channel type, x's type V and T have identical element types, **and at least one of V or T is not a defined type.**

However, it *is* allowed to first convert to a non-defined type, then to the defined type. If I can convert a defined type V to an intermediate non-defined type, then to a defined type T, then I should be able to convert directly from V to T.

To clarify, the proposal is not to change assignability, but to add a [conversion](https://golang.org/ref/spec#Conversions) case that allows the conversion of a defined bidirectional channel type to a defined unidirectional channel type, where the element types are identical.

**Comment by ianlancetaylor** [comment]
For language change proposals, please fill out the template at https://go.googlesource.com/proposal/+/refs/heads/master/go2-language-changes.md .

When you are done, please reply to the issue with `@gopherbot` `please` `remove` `label` `WaitingForInfo`.

Thanks!
