### ISSUE TITLE
x/tools/gopls: "Not a method" logspam

### ISSUE THREAD

**Issue by findleyr** [golang/go#37696]
As reported in #37687 by @myitcv.
> We also see quite a lot of noise on gopls stderr, like:
```
2020/03/05 09:28:57 Not a method...
2020/03/05 09:28:57 Not a method...
2020/03/05 09:28:57 Not a method... status.code="OK"
```

We should start by making this log more self-explanatory, and look into why this condition is triggering so often.

CC @stamblerre

**Comment by ianthehat** [comment]
This was fixed by https://go-review.googlesource.com/c/tools/+/222065

**Comment by findleyr** [comment]
Ah, ok. Thanks!
