### ISSUE TITLE
dl: remove older versions of go

### ISSUE THREAD

**Issue by perillo** [golang/go#37692]
Currently there are 96 versions of `go`, of which 13 release candidate and 13 beta.
What about removing, for Go <= 1.x, all intermediate versions, keeping only the last patched version?

The full list is:
  - go1.5.4
  - go1.6.4
  - go1.7.6
  - go1.8.7
  - go1.9.7
  - go1.10.8
  - go1.11.9
  - go1.12.9
  - go1.13.8

**Comment by tklauser** [comment]
FWIW, I find it quite convenient to be able to also quickly and easily fetch old release candidates, beta versions and "outdated" point releases when tracking down regressions. I'd thus propose to keep these versions.

**Comment by perillo** [comment]
You can always fetch any versions by cloning the `dl` repository, run the `genv` tool followed by `go get`.

The possible problems with having all versions are:

  - Long list of packages in https://godoc.org/golang.org/dl
    (assuming people actually look at the documentation)
  - Accidentally downloading an *old* version

They are not really strong points, so I guess keeping the *old* version is not a problem.

**Comment by dmitshur** [comment]
Thanks for the suggestion.

We generally don't remove old packages. When they're no longer developed, we [freeze](https://golang.org/wiki/Frozen) them, and when they're redundant or unnecessary, we [deprecate](https://golang.org/wiki/Deprecated) them.

Old `golang.org/dl/...` packages are helpful for people who want to try old versions of Go, perhaps to compare something against a newer version. Issue #37156 is just 3 weeks old and was about making even more older Go versions easily accessible.

In the end, as you said, there aren't strong reasons to remove them.

**Comment by perillo** [comment]
Just for clarification, I was not suggesting to remove, as an example, all `go1.8*` versions, just `go1.8 - go.1.8.6`, keeping only `go1.8.7`.

**Comment by dmitshur** [comment]
Sorry, I overlooked that part. I think the same arguments still apply; we don't want to delete packages and there's a chance someone may want to compare patch releases of old Go versions.
