### ISSUE TITLE
x/tools/gopls: version from master needs metadata

### ISSUE THREAD

**Issue by DavidGamba** [golang/go#37698]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/david/.cache/go-build"
GOENV="/home/david/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/david/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/david/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/david/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build109890223=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```
$ go get golang.org/x/tools/gopls
$ gopls version
version master, built in $GOPATH mode

```

### What did you expect to see?

Version information that includes metadata from the commit the version was pulled from.

```
$ gopls version
golang.org/x/tools/gopls v0.0.0+6a641547
```

### What did you see instead?

No useful version information to point back to a specific commit.

**Comment by stamblerre** [comment]
Building `gopls` in `GOPATH` mode is not supported. Please download `gopls` by running `GO111MODULE=on go get golang.org/x/tools/gopls@master` and you should get the results that you expect.

**Comment by DavidGamba** [comment]
Thanks for the response @stamblerre.  Still no metadata:

```
$ GO111MODULE=on go get golang.org/x/tools/gopls@master
go: downloading golang.org/x/tools v0.0.0-20200306161513-8287d625a0c7
go: downloading golang.org/x/tools/gopls v0.1.8-0.20200306161513-8287d625a0c7
go: golang.org/x/tools/gopls master => v0.1.8-0.20200306161513-8287d625a0c7
go: downloading golang.org/x/tools v0.0.0-20191130070609-6e064ea0cf2d
go: downloading golang.org/x/xerrors v0.0.0-20190717185122-a985d3407aa7
# golang.org/x/tools/gopls/internal/hooks
/home/david/go/pkg/mod/golang.org/x/tools/gopls@v0.1.8-0.20200306161513-8287d625a0c7/internal/hooks/hooks.go:19:9: options.URLRegexp undefined (type *source.Options has no field or method URLRegexp)
```

```
$ gopls version
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@(devel)
```

**Comment by stamblerre** [comment]
Ah, I'm sorry I made a mistake in the original command. It should be:

```
GO111MODULE=on go get golang.org/x/tools/gopls@master golang.org/x/tools@master
```

**Comment by DavidGamba** [comment]
Thanks so much, that did it!
