### ISSUE TITLE
can not load package

### ISSUE THREAD

**Issue by penglzy** [golang/go#37701]
{
	"resource": "/e:/study-project/golang-study/src/test.study.com/dayTest/hello.go",
	"owner": "go",
	"severity": 8,
	"message": "can't load package: package _/E_/study-project/golang-study/src/test.study.com/dayTest: cannot find package \"_/E_/study-project/golang-study/src/test.study.com/dayTest\" in any of:\n\tC:\\Go\\src\\_\\E_\\study-project\\golang-study\\src\\test.study.com\\dayTest (from $GOROOT)\n\tE:\\study-project\\mycode\\src\\_\\E_\\study-project\\golang-study\\src\\test.study.com\\dayTest (from $GOPATH)\n",
	"source": "go",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 13
}

**Comment by ianlancetaylor** [comment]
Are you trying to report a bug?  Tell us exactly what you did, exactly what happened, and what you expected to happen instead.

Also, please fill out the issue template.  Don't just delete it.  It's there for a reason.

Thanks.

It looks like maybe you wrote

```Go
import "/E/study-project/golang-study/src/test.study.com/dayTest"
```

?  Don't do that.  Import paths are not absolute paths.
