### ISSUE TITLE
proposal: Provide declared types sync-map to promote from assertion

### ISSUE THREAD

**Issue by fwhezfwhez** [golang/go#37705]
To Design a map used like sync.Map, but its key and value has fixed type, for example:
```go
type Model struct{}
var m = make(synMap[int]Model, 0)
m.Set(5, Model{})
m.Get(5)
```

I can use it as cache which only serves for a certain model.And its code can be auto-generated.

Assume I want to design a 2nd-cache for model `UserInfo`, and code included by `//Header` and `// Tail` is auto-generated. `sync.Map` can realize it anyway but when I load a value, I have to assert from `interface{}` to `UserInfo` which might cost much.

```go
// Header
// Auto-generate by xxxxx
type UserInfo struct{
    Username string
    Addr string
}
var UserInfoCache = make(syncMap[string]UserInfo,0)
// Tail

func main() {
    UserInfoCache.Set("golang", UserInfo{
        Username: "golang",
        Addr: "America",
    })
   fmt.Println(UserInfoCache.Get("golang"))
}
```

**Comment by ianlancetaylor** [comment]
If we had generics (#15292) you could do this using generics.  Closing this issue in favor of the more general one.
