### ISSUE TITLE
CGO wrapper of managed library, dependent on Microsoft Visual Studio C++ redistributable 

### ISSUE THREAD

**Issue by bsrdjan** [golang/go#37706]
Considering that CGO packages shall be compiled with MinGW rather than Visual Studio toolset on Windows, are there any known issues or best practices or good examples to follow, for interfacing to managed Microsoft libraries?

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker for questions.  You will get better and faster answers on a forum.  See https://golang.org/wiki/Questions.

I don't myself know the answer to your question.  Sorry.
