### ISSUE TITLE
Connecting to Oracle Database with password Containing "@"

### ISSUE THREAD

**Issue by EagleShare** [golang/go#37707]
### What version of Go are you using (`go version`)?

<pre>
1.13.4 

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
windows/amd64

</pre></details>

Connecting to oracle database using sql/database with Open function

Tried both possibilities which didn't work

db, err := sql.Open("goracle", "system/oracle@2019@localhost:1521/orcl")
db, err := sql.Open('goracle', 'system/"oracle@2019"@localhost:1521/orcl')

### What did you expect to see?

Successful connection to Database.

### What did you see instead?
params=oracle://sytem:SECRET-PfbiAOWC07c=@2019"%40localhost:1521/orcl?connectionClass=GORACLE&poolIncrement=1&poolMaxSessions=1000&poolMinSessions=1&sysdba=0&sysoper=0&sysasm=0&standaloneConnection=0&enableEvents=0&heterogeneousPool=0&prelim=0&poolWaitTimeout=3000&poolSessionMaxLifetime=3600&poolSessionTimeout=300 extAuth=0: ORA-12154: TNS:could not resolve the connect identifier specified

**Comment by xhit** [comment]
First, your password need to be parsed with url.QueryEscape(password) 

Second, goracle was moved to godror.

Third, you need to create this issue in godror github repo because this repo is for Go programming language.

**Comment by ianlancetaylor** [comment]
This doesn't seem to be something that we can fix in the Go repository, so closing.
