### ISSUE TITLE
x/pkgsite: "popular packages" algorithm might be off

### ISSUE THREAD

**Issue by empijei** [golang/go#37703]
### What is the URL of the page with the issue?
 https://pkg.go.dev/
 
 
### What is your user agent?
 non relevant
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/1256049/76033033-7e022380-5f3b-11ea-947d-8caf612892b5.png)

### What did you do?
 
Visited the page and took a look at the popular packages.
 
### What did you expect to see?
 A list of the popular packages sorted by some criteria, may it be dependents count or amount of times it was looked for on the site. I would also expect this to take into account the update frequency of the package to not advertise stale packages.
 
### What did you see instead?
 Some popular packages in a surprising order.

The current order is
* github.com/sirupsen/logrus [![Sourcegraph](https://sourcegraph.com/github.com/sirupsen/logrus/-/badge.svg)]()
* github.com/gin-gonic/gin   [![Sourcegraph](https://sourcegraph.com/github.com/gin-gonic/gin/-/badge.svg)]()
* github.com/spf13/cobra     [![Sourcegraph](https://sourcegraph.com/github.com/spf13/cobra/-/badge.svg)]()
* github.com/spf13/viper     [![Sourcegraph](https://sourcegraph.com/github.com/spf13/viper/-/badge.svg)]()
* github.com/golang/glog     [![Sourcegraph](https://sourcegraph.com/github.com/golang/glog/-/badge.svg)]()
* github.com/labstack/echo   [![Sourcegraph](https://sourcegraph.com/github.com/labstack/echo/-/badge.svg)]()
* github.com/urfave/cli      [![Sourcegraph](https://sourcegraph.com/github.com/urfave/cli/-/badge.svg)]()
* github.com/gorilla/mux     [![Sourcegraph](https://sourcegraph.com/github.com/gorilla/mux/-/badge.svg)]()
* net/http
* encoding/json

This is unexpected for many reasons:
* How is cobra more popular than json?
* Why is the stdlib mixed with external packages?
* glog has not been updated in 5 years and I think it to be quite self explanatory so I don't think it is here because it is commonly looked for in the docs. If the reason it is here is that It has 43k dependents why is it not above viper which only has 9.7k?
* Testify has 9k dependents, why is it not here while echo is?

Could you please shed some light on the algorithm behind this list? Will the list auto update if the lookups or dependents amount change?

Is the currently displayed list working as intended?

Thanks in advance.

**Comment by mvdan** [comment]
I am similarly confused by "featured packages". Who is featuring them? Is the list generated? Is the list changed or updated periodically?

What worries me the most about these short lists is that they encourage blindly following advice on what's popular and featured. If I am new to Go and visit that page, I might come to the conclusion that logrus is the most popular and idiomatic way to do logging, or that gin is the best way to write http servers. When, in practice, popularity is very hard to measure and shouldn't be front and center when choosing what module to use.

**Comment by mholt** [comment]
My $0.02: I think both lists are not helpful. I think they should just be removed. Or better yet, replaced with a couple tips about how to search effectively, like example search queries, especially pertaining to versions and/or forks.

**Comment by julieqiu** [comment]
Thanks for the feedback! @mholt - that suggestion makes a lot of sense.

We are currently working with our product and UX teams on updates to the homepage.

/cc @spf13 @fflewddur

**Comment by jamalc** [comment]
We launched a redesigned homepage today and removed the popular packages section so I'll close this issue.
