### ISSUE TITLE
why sql generated by gorm are all like `select * from xxx`

### ISSUE THREAD

**Issue by jingyugao** [golang/go#37709]
### What did you do?
```
var s Student
db.Debug().Model(&Student{}").Where("id=1").Find(&s)
```
### What did you expect to see?
sql generated by gorm is 
`select id,name from student where id = 1`

### What did you see instead?
sql generated by gorm is 
`select * from student where id = 1`

SQL generated by gorm select all field from table,
 this is not wrong,but why not replace `*` by the real columns?

**Comment by jingyugao** [comment]
I think we can do this by `db.Model` method。 We can get all field of the struct, then replace *

**Comment by CAFxX** [comment]
I think you should ask on https://github.com/jinzhu/gorm, as the ORM functionality you are referring to is implemented by gorm, not by go or it's standard library.

**Comment by ALTree** [comment]
I agree with @CAFxX, this is a question for the gorm repository. Closing here.
