### ISSUE TITLE
Printing a Time instance radically changes behaviour/result

### ISSUE THREAD

**Issue by iivvoo** [golang/go#37710]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 linux/amd64
</pre>

(also confirmed on 1.12.7, 1.13.8, 1.14)

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ivo/.cache/go-build"
GOENV="/home/ivo/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ivo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go1.13.5"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go1.13.5/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build180433269=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

When trying to write a unit test to trigger an overflow issue, I noticed weird behaviour depending on whether I printed a Time value or not.

The following code will print the time.Time `Changed` depending on wheter an argument is passed or not. With repeated invocations, no print will always result in "200 ok", with print it will randomly print Ok / Not good.

```package main

import (
	"fmt"
	"time"
	"os"
)


func Check(print bool) int16 {
	var Current int16 = 200

        Changed := time.Now().Add(-98100 * time.Second)

	if print {
		// Changed.String() or printing it gives completely different, near random results
		//Changed.String()
		fmt.Println("x", Changed)
	}

	since := time.Since(Changed)

	steps := int(since / 30)

	newValue := int16(steps*10)

        //fmt.Println("a", since, steps, newValue)

	if newValue > Current {
		return Current
	}
	return newValue
}

func main() {
	print := len(os.Args) > 1

        if v := Check(print); v < 0 {
                fmt.Println("Not good", v)
	} else {
	        fmt.Println("ok", v)
	}
}
```
(playground doesn't reliably reproduce this)

#### With print

```
$ for i in `seq 10`; do /opt/go1.13.5/bin/go run time.go x; done
x 2020-03-05 10:52:33.174483326 +0100 CET m=-98099.999963313
Not good -9048
x 2020-03-05 10:52:33.318909812 +0100 CET m=-98099.999963107
Not good -14998
x 2020-03-05 10:52:33.461707234 +0100 CET m=-98099.999970989
Not good -12738
x 2020-03-05 10:52:33.61566391 +0100 CET m=-98099.999944078
ok 200
x 2020-03-05 10:52:33.787522681 +0100 CET m=-98099.999963818
Not good -4928
x 2020-03-05 10:52:33.956882845 +0100 CET m=-98099.999947761
ok 200
x 2020-03-05 10:52:34.164568146 +0100 CET m=-98099.999957760
ok 200
x 2020-03-05 10:52:34.37969668 +0100 CET m=-98099.999957835
Not good -1398
x 2020-03-05 10:52:34.89087561 +0100 CET m=-98099.999966284
Not good -6858
x 2020-03-05 10:52:35.098330405 +0100 CET m=-98099.999956116
ok 200
```
#### Without print
```
$ for i in `seq 10`; do /opt/go1.13.5/bin/go run time.go; done
ok 200
ok 200
ok 200
ok 200
ok 200
ok 200
ok 200
ok 200
ok 200
ok 200
```

### What did you expect to see?

I would not expect to see a different result depending on wheter `Changed` was printed or not.

### What did you see instead?

Consistent results with or without the print, and consistent Ok or Not Good, not a random mix (but that might be related to the overflow issue itself).

**Comment by ianlancetaylor** [comment]
All you are testing is how long `fmt.Println` takes to run.

If you don't call `fmt.Println`, then `since` will be very close to `-98100 * time.Second`, which when converted to `int` is `98100000000000`.  Dividing that by `30` gives `3270000000000`.  Multiplying by `10` and converting to `int16` gives `22528`.  That is larger than `200`, so we return `200`.

But if you do call `fmt.Println`, lets say that takes 37,000 nanoseconds.  Then `since` converted to `int` will be `98100000037000`, dividing that by 30 will be `3270000001233`, multiplying by `10` will be `32700000012330` which in hex is `0x1dbd8fe2882a`, and converting that to `int16` will be `0x882a` which is `-30678`.  Your program will see a negative number and print `Not good`.

So all you are testing here is how long it takes to run `fmt.Println`.
