### ISSUE TITLE
x/tools/gopls: support multi-project workspaces

### ISSUE THREAD

**Issue by heschik** [golang/go#37720]
This is a place to discuss multi-project workspaces in `gopls`. Design doc forthcoming.

**Comment by heschik** [comment]
Apparently I never actually attached the design doc. It's here: https://github.com/golang/proposal/blob/master/design/37720-gopls-workspaces.md

**Comment by hyangah** [comment]
What I am concerned about is the proposed super-module may cause what `gopls` sees to be different from what other tools (the go command, debugger, etc) integrated to the editors outside `gopls` will see. That can be a source of confusion potentially. If we take this path, I think we need a way to make the go command and other tool to use the same approach and provide consistent views.

**Comment by stamblerre** [comment]
De-duping this with https://github.com/golang/go/issues/32394, as that issue has been more popular.

**Comment by stamblerre** [comment]
Duplicate of https://github.com/golang/go/issues/32394
