### ISSUE TITLE
runtime: fatal error polling some file descriptors on macOS Mojave

### ISSUE THREAD

**Issue by jbardin** [golang/go#37726]
### What version of Go are you using (`go version`)?

<pre>
go1.14
master
</pre>

### Does this issue reproduce with the latest release?
 Yes

### What operating system and processor architecture are you using (`go env`)?

<pre>
darwin_amd64
macOS Mojave
</pre>

### What did you do?

The following test file crashes on macOS Mojave

```
package main

import (
	"os"
	"testing"
	"time"
)

func TestFD(t *testing.T) {
	os.NewFile(4, "")
	time.Sleep(time.Second)
}
```

With the output:

```
$ go test fd_test.go
runtime: netpoll: break fd ready for -2
fatal error: runtime: netpoll: break fd ready for something unexpected

runtime stack:
runtime.throw(0x29c482a, 0x39)
/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:1112 +0x72
runtime.netpoll(0x176414, 0xc00004c001)
/usr/local/Cellar/go/1.14/libexec/src/runtime/netpoll_kqueue.go:140 +0x30a
runtime.findrunnable(0xc00004e800, 0x0)
/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:2323 +0x72b
runtime.schedule()
/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:2520 +0x2fc
runtime.park_m(0xc000182600)
/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:2690 +0x9d
runtime.mcall(0x80000)
/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:318 +0x5b
...
```

The same error was seen in #35566, but that fix was only for the test in question.
This isn't directly related to testing however, as we've seen this with normal production binaries.

**Comment by chenweiyj** [comment]
I have found that if the _test file is compiled first with `-c` flag, and run the executable object, the runtime error won't occur.

**Comment by chenweiyj** [comment]
Also, in macos when calling `os.NewFile(4, "")`, it will crash if and only if the `fd` equals 4.

**Comment by maurorappa** [comment]
nothing yet ? :(

**Comment by toothrot** [comment]
@maurorappa While every issue is important to us, please try to be patient as many of us are also juggling personal health and responses to the pandemic.

**Comment by ianlancetaylor** [comment]
What is the real code doing that causes this problem?  While clearly using `os.NewFile(4, "")` ought to work, why is this an important case?

**Comment by ianlancetaylor** [comment]
If the problem only happens with file descriptor 4, then it's because file descriptor 4 is being used by the runtime package.  The runtime package treats the descriptor specially, and only expects it to be polled for read.  Using `os.NewFile(4, ''")` is expected to fail.

**Comment by jbardin** [comment]
A number of our tools run primarily in a subprocess, and the main process passes stdin, stdout and stderr in via `Cmd.ExtraFiles` in order to provide access to things like the raw terminal. This of course puts the original stdout in FD 4, which we need to convert into a File to use.

**Comment by ianlancetaylor** [comment]
@jbardin Can you show a complete example that demonstrates the problem, and show what happens when you run it?  The example above is different in relevant ways from what you are describing.  Thanks.

**Comment by jbardin** [comment]
Thanks @ianlancetaylor, I'll try to put together a standalone example, (need to find a Mojave machine to debug on). The test example above has the exact same fatal error output as what we're experiencing, so thought it might be close enough.

I did however confirm that simply passing stdin, stdout, stderr on 3, 4, 5 works, so there must be something else involved here, and it also seems strange it's related to a specific OS version as well.

**Comment by ianlancetaylor** [comment]
I'm fairly certain that the error `break fd ready for something unexpected` can only happen if a program erroneously uses the file descriptor number that happens to have been created to use to wake up a sleeping `kevent`.

**Comment by jbardin** [comment]
Thanks again Ian, I see what's going on now. I had time to track this down and find where the file descriptors were being used in the incorrect process.

**Comment by ianlancetaylor** [comment]
Thanks for following up.
