### ISSUE TITLE
go 1.14 overlapping-interface does not work on mac os 

### ISSUE THREAD

**Issue by bigwhite** [golang/go#37728]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes. go 1.14 is the latest version.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tonybai/Library/Caches/go-build"
GOENV="/Users/tonybai/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tonybai/Go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Users/tonybai/.bin/go1.14"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/Users/tonybai/.bin/go1.14/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/tonybai/go/src/github.com/bigwhite/experiments/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cz/sbj5kg2d3m3c6j650z0qfm800000gn/T/go-build199896134=/tmp/go-build -gno-record-gcc-switches -fno-common"

$uname -a
Darwin tonybaideMacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

</pre></details>

### What did you do?

I run the code below with go 1.14 under mac os 10.15. the  go 1.14 i use is downloaded from  https://dl.google.com/go/go1.14.darwin-amd64.tar.gz

<pre>
//overlapping_interface.go
package main

type I interface {
	f()
	String() string
}
type J interface {
	g()
	String() string
}

type IJ interface {
	I
	J
}

func main() {
	var _ IJ
}

</pre>

But on linux, the code run with go 1.14 is ok.

### What did you expect to see?

go run ok without compiler error.

### What did you see instead?

<pre>
$go run overlapping_interface.go
# command-line-arguments
./overlapping_interface.go:14:2: duplicate method String

</pre>

**Comment by randall77** [comment]
I can't reproduce. Both 1.14 and tip work fine for me.
Are you sure you're getting the correct version of Go? Run `go version`, and make sure you haven't set `GOROOT`.

**Comment by bigwhite** [comment]
I set GOROOT to the folder which is unzipped from https://dl.google.com/go/go1.14.darwin-amd64.tar.gz.  I have also doubt whether I have  downloaded the wrong version of Go. so I remove the old one and re-download and install it from https://dl.google.com/go/go1.14.darwin-amd64.tar.gz  again. Afer re-runing the code above.  the overlapping interface still does not work. 


then I remove the GOROOT env manually and use the below approach to install go 1.14:

<pre>
➜  /Users/tonybai git:(master) ✗ $go get golang.org/dl/go1.14
go: finding golang.org/dl latest
go: downloading golang.org/dl v0.0.0-20200302224518-306f3096cb2f
go: extracting golang.org/dl v0.0.0-20200302224518-306f3096cb2f

➜  /Users/tonybai git:(master) ✗ $go1.14 download
Downloaded   0.0% (    14448 / 124931758 bytes) ...
Downloaded   0.3% (   391280 / 124931758 bytes) ...
Downloaded   3.5% (  4388976 / 124931758 bytes) ...
Downloaded   6.8% (  8550512 / 124931758 bytes) ...
Downloaded   9.8% ( 12187760 / 124931758 bytes) ...
Downloaded  12.9% ( 16119920 / 124931758 bytes) ...
Downloaded  16.1% ( 20084848 / 124931758 bytes) ...
Downloaded  19.3% ( 24049776 / 124931758 bytes) ...
Downloaded  22.9% ( 28604528 / 124931758 bytes) ...
Downloaded  27.1% ( 33912944 / 124931758 bytes) ...
Downloaded  31.5% ( 39385200 / 124931758 bytes) ...
Downloaded  37.0% ( 46200944 / 124931758 bytes) ...
Downloaded  41.2% ( 51443824 / 124931758 bytes) ...
Downloaded  47.5% ( 59340912 / 124931758 bytes) ...
Downloaded  51.8% ( 64747632 / 124931758 bytes) ...
Downloaded  55.8% ( 69728368 / 124931758 bytes) ...
Downloaded  63.5% ( 79329392 / 124931758 bytes) ...
Downloaded  71.4% ( 89143940 / 124931758 bytes) ...
Downloaded  75.5% ( 94345421 / 124931758 bytes) ...
Downloaded  83.4% (104202240 / 124931758 bytes) ...
Downloaded  92.5% (115554516 / 124931758 bytes) ...
Downloaded 100.0% (124931758 / 124931758 bytes)
Unpacking /Users/tonybai/sdk/go1.14/go1.14.darwin-amd64.tar.gz ...
Success. You may now run 'go1.14'


➜  /Users/tonybai git:(master) ✗ $go1.14 env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tonybai/Library/Caches/go-build"
GOENV="/Users/tonybai/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tonybai/Go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Users/tonybai/sdk/go1.14"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/Users/tonybai/sdk/go1.14/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cz/sbj5kg2d3m3c6j650z0qfm800000gn/T/go-build236598550=/tmp/go-build -gno-record-gcc-switches -fno-common"


</pre>

I use the new installed go1.14 to build the original demo code:

<pre>
➜  /Users/tonybai/Go/src/github.com/bigwhite/experiments/go1.14-examples git:(master) $go1.14 version
go version go1.14 darwin/amd64
➜  /Users/tonybai/Go/src/github.com/bigwhite/experiments/go1.14-examples git:(master) $go1.14 build overlapping_interface.go
# command-line-arguments
./overlapping_interface.go:14:2: duplicate method String
</pre>

It still does not work as expected. Is there anything wrong with my install process?

**Comment by bigwhite** [comment]
And here the build log with -x -v:

```
➜  /Users/tonybai/Go/src/github.com/bigwhite/experiments/go1.14-examples git:(master) $go1.14 build -x -v overlapping_interface.go
WORK=/var/folders/cz/sbj5kg2d3m3c6j650z0qfm800000gn/T/go-build369480074
command-line-arguments
mkdir -p $WORK/b001/
cat >$WORK/b001/importcfg << 'EOF' # internal
# import config
EOF
cd /Users/tonybai/Go/src/github.com/bigwhite/experiments/go1.14-examples
/Users/tonybai/sdk/go1.14/pkg/tool/darwin_amd64/compile -o $WORK/b001/_pkg_.a -trimpath "$WORK/b001=>" -p command-line-arguments -lang=go1.12 -complete -buildid 00YuEePKlhV_qKTnJcVK/00YuEePKlhV_qKTnJcVK -goversion go1.14 -D _/Users/tonybai/Go/src/github.com/bigwhite/experiments/go1.14-examples -importcfg $WORK/b001/importcfg -pack -c=4 ./overlapping_interface.go
# command-line-arguments
./overlapping_interface.go:14:2: duplicate method String
```

**Comment by randall77** [comment]
```
 -lang=go1.12
```
I suspect this argument to `compile` is causing the issue. Where is that coming from?
I do not see that when I run `go clean -cache` and then:
```
 gowork % ~/sandbox/readonly/bin/go run -x -v issue37728.go 
WORK=/var/folders/z9/dty110711l9cr9w3ktv1_2380000gn/T/go-build095594805
command-line-arguments
mkdir -p $WORK/b001/
cat >$WORK/b001/importcfg << 'EOF' # internal
# import config
packagefile runtime=/Users/khr/sandbox/readonly/pkg/darwin_amd64/runtime.a
EOF
cd /Users/khr/gowork
/Users/khr/sandbox/readonly/pkg/tool/darwin_amd64/compile -o $WORK/b001/_pkg_.a -trimpath "$WORK/b001=>" -p main -complete -buildid ZAllgnn3N9izb5gf0t2G/ZAllgnn3N9izb5gf0t2G -dwarf=false -D _/Users/khr/gowork -importcfg $WORK/b001/importcfg -pack -c=4 ./issue37728.go
/Users/khr/sandbox/readonly/pkg/tool/darwin_amd64/buildid -w $WORK/b001/_pkg_.a # internal
cp $WORK/b001/_pkg_.a /Users/khr/Library/Caches/go-build/2d/2d11e3f500c7d48997219b622d084ee7ee5608bfcd3d9f3100569b239c1f2164-d # internal
cat >$WORK/b001/importcfg.link << 'EOF' # internal
packagefile command-line-arguments=$WORK/b001/_pkg_.a
packagefile runtime=/Users/khr/sandbox/readonly/pkg/darwin_amd64/runtime.a
packagefile internal/bytealg=/Users/khr/sandbox/readonly/pkg/darwin_amd64/internal/bytealg.a
packagefile internal/cpu=/Users/khr/sandbox/readonly/pkg/darwin_amd64/internal/cpu.a
packagefile runtime/internal/atomic=/Users/khr/sandbox/readonly/pkg/darwin_amd64/runtime/internal/atomic.a
packagefile runtime/internal/math=/Users/khr/sandbox/readonly/pkg/darwin_amd64/runtime/internal/math.a
packagefile runtime/internal/sys=/Users/khr/sandbox/readonly/pkg/darwin_amd64/runtime/internal/sys.a
EOF
mkdir -p $WORK/b001/exe/
cd .
/Users/khr/sandbox/readonly/pkg/tool/darwin_amd64/link -o $WORK/b001/exe/issue37728 -importcfg $WORK/b001/importcfg.link -s -w -buildmode=exe -buildid=iCJGWHdK0Gyocdby3Esk/ZAllgnn3N9izb5gf0t2G/JVkIFId4vW7dVTugFwCX/iCJGWHdK0Gyocdby3Esk -extld=clang $WORK/b001/_pkg_.a
$WORK/b001/exe/issue37728
```

**Comment by bigwhite** [comment]
It is really weird. I clean the cache and re-run it . the -lang=go1.12 still in the option list in go1.14 compiler. Which config or environment vars can cause the -lang option be passed to go compiler?

**Comment by bigwhite** [comment]
I found the cause. It is the go version in go.mod which exist in the root path of  the project.

```
➜  /Users/tonybai/Go/src/github.com/bigwhite/experiments git:(master) ✗ $cat go.mod
module github.com/bigwhite/experiments

go 1.12
``` 

Sorry for wasting your time. I will close this issue. So appreciate for helping me.
