### ISSUE TITLE
cmd/cgo: CGo Exported Function has an empty line between it and its documentation block

### ISSUE THREAD

**Issue by nathan-fiscaletti** [golang/go#37722]
I'm writing a library in Go that I'm compiling to a native library using CGo, however when the functions are exported they have this annoying empty line between the function declaration and the documentation comment.

As an example, let's say I have this in my go file

```go
/**
 * Prints an integer.
 *
 * @param p0 an integer to print.
 */
//export PrintInteger
func PrintInteger(val C.int) {
    fmt.Printf("%v", val);
}
```

Once it's exported in my C header file, it looks like this

```c
/**
 * Prints an integer.
 *
 * @param p0 an integer to print.
 */

extern void PrintInteger(int p0);
```

That empty line for the most part isn't a problem, but on some IDEs when parsing that header file they have difficulty properly displaying the intellisense, making consumption of the header slightly more difficult. Especially when you factor in the way that cgo [renames function parameters](https://stackoverflow.com/questions/57511799/how-do-i-get-proper-parameter-names-in-cgo-exported-functions)

I've found _what i believe_ is the area in the go source code that causes this:

https://github.com/golang/go/blob/master/src/cmd/cgo/out.go#L922

```go
if len(exp.Doc) > 0 {
    fmt.Fprintf(fgcch, "\n%s", exp.Doc)
}
fmt.Fprintf(fgcch, "\nextern %s;\n", s)
```

I feel like perhaps that `\n` before the `extern` keyword shouldn't be there. Unless this is intentional?

**Comment by ianlancetaylor** [comment]
Seems like the newline before the doc comment shouldn't affect this.

**Comment by ianlancetaylor** [comment]
Sorry, misunderstood.

I'm surprised this makes a difference in a C header file.  Do editors expect there to be no blank line between C docs and C declarations?

**Comment by nathan-fiscaletti** [comment]
It's certainly an issue when using Android Studio (where i tend to do most of my work). The same header file works fine in XCode (the other IDE i use), and in Visual Studio Code. So far i've only run into the issue in Android Studio, but it seems like a pretty stupid problem to have.
