### ISSUE TITLE
Private/public struct members in non-Latin languages

### ISSUE THREAD

**Issue by kstenerud** [golang/go#37731]
How do you specify whether a struct field is exported or not when the field names are in a non-Latin language that doesn't have the concept of uppercase and lowercase?

For example:

export/inner/inner.go:

```golang
package inner

type X struct {
	名前 string // How do I change the visibility?
}

func NewX(名前 string) *X {
	return &X{名前: 名前}
}
```

export/main.go:
```golang
package main

import (
	"export/inner"
	"fmt"
)

func main() {
	v := inner.NewX("長島")

	// ./main.go:12:46: v.名前 undefined (cannot refer to unexported field or method 名前)
	fmt.Printf("こんにちは、%vさん\n", v.名前)
}
```

**Comment by mattn** [comment]
Probably this is the same topic as https://github.com/golang/go/issues/5763

**Comment by ALTree** [comment]
As @mattn said, this is #5763, and also #22188 for the search for a solution to this issue. Regarding your question, what it's usually done is to put an upper-case latin letter at the beginning of the name to export it.

Closing here as a question (which was answered) and a dup of #22188 (for a solution).
