### ISSUE TITLE
x/blog:

### ISSUE THREAD

**Issue by yunxuanxs** [golang/go#37732]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.14 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
go1.14 windows/amd64

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I see a error example from your blog.

There is a example for defer statements to ensure that the files are always closed.
Example:
<pre>
    src, err := os.Open(srcName)
    if err != nil {
        return
    }
    // If error when file open, this statement can not be executed. 
    defer src.Close()
    dst, err := os.Create(dstName)
    if err != nil {
        return
    }
    // If error when file open, this statement can not be executed. 
    defer dst.Close()
</pre>
It's can not ensure that the files are always closed.

Url: https://blog.golang.org/defer-panic-and-recover

### What did you see instead?

<pre>
    src, err := os.Open(srcName)
    defer src.Close()
    if err != nil {
        return
    }
    dst, err := os.Create(dstName)
    defer dst.Close()
    if err != nil {
        return
    }
</pre>

**Comment by randall77** [comment]
Are you suggesting we defer the `Close` before checking for the error?
I don't think that is right. If there was an error, then the returned `*File` does not need to be closed (it will be nil).

Perhaps the godoc for `os.Open` and `os.Create` could be clearer on this point.

**Comment by yunxuanxs** [comment]
Oh, yes, You are right.
Thanks for your answer.
