### ISSUE TITLE
cmd/compile: optimize LEAQ address calculations

### ISSUE THREAD

**Issue by rillig** [golang/go#37736]
### What version of Go are you using?

go version go1.13.1 windows/amd64

### What did you do?

https://play.golang.org/p/Wvp_nntNomk

### What did you expect to see?

~~~plain
line 12: LEAQ 0x2(CX)(CX*1), DX
~~~

### What did you see instead?

~~~plain
line 12: LEAQ 0(CX)(CX*1), DX
line 12: LEAQ 0x2(DX), DX
~~~

I'm not sure whether merging these two instructions would make a large difference, I just expect the optimizer to know the instruction set well enough to make this optimization.

**Comment by randall77** [comment]
This is intentional. See #21735.
