### ISSUE TITLE
cmd/internal/moddeps: the lastest tip version fails

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#37749]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +b5c66de089 Sun Mar 8 19:03:08 2020 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yoshiki.shibata/Library/Caches/go-build"
GOENV="/Users/yoshiki.shibata/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="github.com/kouzoh/*"
GONOSUMDB="github.com/kouzoh/*"
GOOS="darwin"
GOPATH="/Users/yoshiki.shibata/gocode"
GOPRIVATE="github.com/kouzoh/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/yoshiki.shibata/tools/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/yoshiki.shibata/tools/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g5/3v328m31769f1hylbmcvt6x00000gp/T/go-build569234592=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version devel +b5c66de089 Sun Mar 8 19:03:08 2020 +0000 darwin/amd64
GOROOT/bin/go tool compile -V: compile version devel +b5c66de089 Sun Mar 8 19:03:08 2020 +0000
uname -v: Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76
lldb --version: lldb-1100.0.30.12
Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
</pre></details>

### What did you do?

Building with all.bash.

### What did you expect to see?

No failure with the build

### What did you see instead?

Building with all.bash always fails:

```
ok  	cmd/internal/goobj	1.883s
--- FAIL: TestAllDependenciesVendored (0.03s)
    moddeps_test.go:99: 'go list -json -m' in /Users/yoshiki.shibata/tools/go/doc/articles/wiki: exit status 1
        go list -m: not using modules
        
--- FAIL: TestDependencyVersionsConsistent (0.00s)
    moddeps_test.go:148: 'go list -json -m' in /Users/yoshiki.shibata/tools/go/doc/articles/wiki: exit status 1
        go list -m: not using modules
        
FAIL
FAIL	cmd/internal/moddeps	0.604s
```

**Comment by bcmills** [comment]
What, if any, local changes do you have vs. `origin/master`?

Is the `GO111MODULE` setting in your `go env` output accurate?

**Comment by bcmills** [comment]
I can reproduce the observed symptoms using `go env -w GO111MODULE=off`. I'm not sure whether that's the original cause, but I can at least fix that case.
