### ISSUE TITLE
cmd/go: get / build fails if a commented import declaration exists after package declaration

### ISSUE THREAD

**Issue by 42wim** [golang/go#37747]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build075745121=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

`go get github.com/42wim/matterbridge` (which includes a vendor that has a commented import path)

Simplified version below:

```
package main // import "something"

func main() {
}
```

### What did you expect to see?

A working build.

### What did you see instead?

```
root@363dc3fb8e36:/testing# go get github.com/42wim/matterbridge
/go/src/github.com/42wim/matterbridge/vendor/github.com/shazow/ssh-chat/sshd/terminal.go:10:2: code in directory /go/src/github.com/42wim/matterbridge/vendor/github.com/shazow/ssh-chat/sshd/terminal expects import "golang.org/x/crypto/ssh/terminal"
```

Or for the simplified version

```
root@363dc3fb8e36:/mytest# go build
can't load package: package .: code in directory /mytest expects import "something"
```

`go run main.go` works fine

Issue seems to be introduced in go 1.13
Can not reproduce it  in go 1.12.17

**Comment by toothrot** [comment]
This is a feature of go import paths, see the full text of `go help importpath`, in the section titled "Import path checking":

https://pkg.go.dev/cmd/go?tab=doc#hdr-Import_path_checking

It is disabled if you are using modules. What is the output of `go env` when you are using go 1.12.17?

/cc @bcmills @jayconrod

**Comment by 42wim** [comment]
The `go env` output with go1.12.17 below

GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build400551887=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by jayconrod** [comment]
Seems like this is working as intended, so I'll close.

In `GOPATH` mode, `// import` comments force a package to only be imported with a canonical path. If a package is forked (which seems to be the case here), then `// import` comments must be updated or removed.

As @toothrot said, `// import` comments are not applied in module mode, but a similar restriction is applied through the module path in `go.mod` files.

I'm not sure why you wouldn't see errors in `go1.12.17`. The error is the correct behavior though.
