### ISSUE TITLE
x/crypto: Request a pty puts stderr in stdout

### ISSUE THREAD

**Issue by ling2yt** [golang/go#37758]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

didn't check

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?

I want to get stderr from stderr pipe and get stdout from stdout pipe

### What did you see instead?
the stderr was combined to stdout stream

**Comment by ianlancetaylor** [comment]
What exactly did you do?
