### ISSUE TITLE
proxy.golang.org: tag info&sumcheck for incorrect commit node

### ISSUE THREAD

**Issue by oGre222** [golang/go#37769]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build384765387=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
<details><summary><code>curl https://api.github.com/repos/weibreeze/breeze-go/releases/tags/v0.1.0 </code><code>show:"created_at": "2019-08-12T02:50:47Z"</code> Output</summary><br><pre>
{
  "url": "https://api.github.com/repos/weibreeze/breeze-go/releases/19219528",
  "assets_url": "https://api.github.com/repos/weibreeze/breeze-go/releases/19219528/assets",
  "upload_url": "https://uploads.github.com/repos/weibreeze/breeze-go/releases/19219528/assets{?name,label}",
  "html_url": "https://github.com/weibreeze/breeze-go/releases/tag/v0.1.0",
  "id": 19219528,
  "node_id": "MDc6UmVsZWFzZTE5MjE5NTI4",
  "tag_name": "v0.1.0",
  "target_commitish": "master",
  "name": "release v0.1.0",
  "draft": false,
  "author": {
    "login": "rayzhang0603",
    "id": 2917437,
    "node_id": "MDQ6VXNlcjI5MTc0Mzc=",
    "avatar_url": "https://avatars3.githubusercontent.com/u/2917437?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rayzhang0603",
    "html_url": "https://github.com/rayzhang0603",
    "followers_url": "https://api.github.com/users/rayzhang0603/followers",
    "following_url": "https://api.github.com/users/rayzhang0603/following{/other_user}",
    "gists_url": "https://api.github.com/users/rayzhang0603/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rayzhang0603/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rayzhang0603/subscriptions",
    "organizations_url": "https://api.github.com/users/rayzhang0603/orgs",
    "repos_url": "https://api.github.com/users/rayzhang0603/repos",
    "events_url": "https://api.github.com/users/rayzhang0603/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rayzhang0603/received_events",
    "type": "User",
    "site_admin": false
  },
  "prerelease": false,
  "created_at": "2019-08-12T02:50:47Z",
  "published_at": "2019-08-12T03:02:41Z",
  "assets": [

  ],
  "tarball_url": "https://api.github.com/repos/weibreeze/breeze-go/tarball/v0.1.0",
  "zipball_url": "https://api.github.com/repos/weibreeze/breeze-go/zipball/v0.1.0",
  "body": "release v0.1.0\r\nadapt protocol 0.1.x, it not compatible with v0.0.x"
}
</pre></details>

$ curl https://proxy.golang.org/github.com/weibreeze/breeze-go/@v/v0.1.0.info
{"Version":"v0.1.0","Time":"2019-08-01T01:51:21Z"}

$ curl https://sum.golang.org/lookup/github.com/weibreeze/breeze-go@v0.1.0
127293
github.com/weibreeze/breeze-go v0.1.0 h1:+++pO6wSn6jNsX6iNnSYjiQsSVPWGD4O/iA0yzGw7s8=
github.com/weibreeze/breeze-go v0.1.0/go.mod h1:qUQStJ6KIU3odtTwdpoRGz6Bu8zkwIoh49TKpbFzoMI=

go.sum database tree
854218
IvNeLkjuR4CwXxWgmSaLmv76klQ33a77uaPDhPQb7c8=

— sum.golang.org Az3grtH1vHsUelsxwmi97EugHdfjVK1efVlbBCD1sIMyQxwh5Nq3WW5qfIHt+Nf/FQ70JRMx22kQg5q2SVxQQM9BqAc=

$ curl https://goproxy.io/github.com/weibreeze/breeze-go/@v/v0.1.0.info
{"Version":"v0.1.0","Time":"2019-08-12T02:50:47Z"}

### What did you expect to see?
$ curl https://proxy.golang.org/github.com/weibreeze/breeze-go/@v/v0.1.0.info
{"Version":"v0.1.0","Time":"2019-08-12T02:50:47Z"}

$ curl https://sum.golang.org/lookup/github.com/weibreeze/breeze-go@v0.1.0
...
github.com/weibreeze/breeze-go v0.1.0 h1:<strong>7uALKaS/Nxv2O2vSwrS0+3KybL58Y2rWyYaRKgl/YOw=</strong>(before 1.13 sumcheck hash)
...

### What did you see instead?
actual, github.com/weibreeze/breeze-go@v0.1.0 tag commit hash is 745bbab56a31ed514662fa23c7748999c206bafa (tag: v0.1.0). sum&proxy used commit hash is 16003c2df404b1b8ebfaf619dfc7b0eebcd67b88 ,this is before tag:v0.1.0 by three commit nodes

**Comment by hyangah** [comment]
`proxy.golang.org` and `sum.golang.org` observed and downloaded `github.com/weibreeze/breeze-go@v0.1.0` at 2019-08-02 17:07:14 UTC for the first time.  Given the result of `curl https://api.github.com/repos/weibreeze/breeze-go/releases/tags/v0.1.0`, I guess the origin changed the tag. Retagging or modifying version tags after a module/version is published is not supported.

**Comment by hyangah** [comment]
@weibreeze Can you confirm what happened in the version tagging? Once published, version tags must not be modified. The fix is to release a new version `v0.1.1`  and discourage use of `v0.1.0`.

**Comment by rayzhang0603** [comment]
@hyangah we did retagging in this version. I will release a new version to fix it. thanks~

**Comment by oGre222** [comment]
@hyangah @hyangah  Thanks,I'll close
