### ISSUE TITLE
x/pkgsite: don't imply that vN.x.y is the latest version when vN+1 exists

### ISSUE THREAD

**Issue by cespare** [golang/go#37765]
### What is the URL of the page with the issue?
 
For example: https://pkg.go.dev/github.com/cespare/xxhash?tab=doc
 
### What is your user agent?
 
N/A
 
### Screenshot
 
![screen_20200309145922](https://user-images.githubusercontent.com/318501/76261141-95306200-6216-11ea-976c-e14ccbf79539.png)
 
### What did you do?
 
Viewed the v1 documentation for a module that also has a v2.

### What did you expect to see?

No v1 version of my module should be marked as "Latest" since v2 exists.

### What did you see instead?

v1.1.0 was marked as "Latest".

I understand that v1 and v2 are essentially two different modules, and that the discovery site is showing that v1.1.0 is the latest version of the v1 module. However, this may mislead users into thinking that v1.1.0 is somehow up-to-date. I do not want new users of my module to use v1.1.0; I want them to use the real latest version of the module which is v2.1.1 at the moment.

Ideally, when viewing v1.1.0, the users would see on the page that v2 exists and is the latest major module version. There ought to be a link to quickly go to the latest version, just as there is a red "Go to latest" link when viewing the not-latest-minor-version page ([example](https://pkg.go.dev/github.com/cespare/xxhash/v2@v2.1.0?tab=doc)):

![screen_20200309150757](https://user-images.githubusercontent.com/318501/76261716-d412e780-6217-11ea-8b93-d27661f2bb2a.png)

This is related to #36969, where the search ranking also pushes users toward using the old major version of my module.

Right now it seems that the discovery site has very little notion of the relationship between different major versions of the same module. Please consider how to make this site more friendly for maintainers of v2+ modules.

**Comment by julieqiu** [comment]
Thanks for the feedback! We understand that this is confusing and plan to fix it as part of an upcoming round of UX changes. 

/cc @fflewddur

**Comment by bcmills** [comment]
I think there are two different notions of “latest” at play here.

One is “what is the latest implementation of this API?”, and for that notion, `v1.1.0` is correct.

The other is “what is the latest variant of this API that addresses the same general use-cases?”, and that notion is better answered by `v2.1.1`.

It may be worthwhile to surface both of those answers in some fashion.

**Comment by AceroM** [comment]
We’re planning to add a banner to pkg.go.dev, to indicate when there is a newer major version. Here is a mock: 
![image](https://user-images.githubusercontent.com/21187304/91735750-bac17700-eb7a-11ea-9c9b-ee61cdada80d.png)

**Comment by myitcv** [comment]
Looks great! However, I'd suggest the `pkg.go.dev/` prefix is redundant/misleading in this case. Because the module path of the latest major version is `github.com/russross/blackfriday/v2` - the user will just so happen to be viewing that via pkg.go.dev

**Comment by AceroM** [comment]
> Looks great! However, I'd suggest the `pkg.go.dev/` prefix is redundant/misleading in this case. Because the module path of the latest major version is `github.com/russross/blackfriday/v2` - the user will just so happen to be viewing that via pkg.go.dev

Thanks! We had it as the module path at first but we didn't want users thinking they would redirect to github.com/...

**Comment by cespare** [comment]
I agree with @myitcv -- it seems better to phrase this in terms of actual module names.

The fact that package/module names look an awful lot like github.com/[other hosting provider] URLs is just one of those things that Go users have to get used to. I attached a few examples at the bottom where module names are links within pkg.go.dev already.

But it also seems to me that the message could simply be:

> The latest major version is [v2](https://pkg.go.dev/github.com/russross/blackfriday/v2)

That draws attention to the major version number, which is the important part of the message.

---

![link1](https://user-images.githubusercontent.com/318501/91748257-91055180-eb74-11ea-926a-c80b68fca537.png)

![link2](https://user-images.githubusercontent.com/318501/91748265-94004200-eb74-11ea-8259-6a4bfdbc1422.png)

**Comment by AceroM** [comment]
> But it also seems to me that the message could simply be:
> The latest major version is v2
> That draws attention to the major version number, which is the important part of the message.
Thanks @cespare for your suggestion! We will update the text accordingly. 🙂
