### ISSUE TITLE
cmd/compile: automatically combine passes in ssa.html when contents are unchanged

### ISSUE THREAD

**Issue by josharian** [golang/go#37766]
ssa.html has a lot of columns. It'd help both the user and the browser if we could eliminate some of them.

Some passes have no impact at all on the function (e.g. arch specific passes on other architectures, or the writebarrier pass on a function with no pointer writes).

I suggest that the SSA HTML writer hash the function contents, maybe just by printing the function using stringFuncPrinter into a hash.Hash. Then, if a pass has had no impact, combine the two columns. So instead of a "generic cse" column followed by a "phiopt" column, we'd have a single column called something like  "generic cse = phiopt" (and maybe more than two).

The `expandedDefault` array may need tweaking to support this.

cc @randall77 @bradford-hamilton

**Comment by josharian** [comment]
@bradford-hamilton feel 100% free to ignore this. I'm only cc'ing you optimistically. :)

**Comment by bradford-hamilton** [comment]
@josharian I like this idea a lot - I think I'll look into it a bit and see what I can come up with. If anyone else has interest or more context here and wants to claim it feel free!  Think I'll try it either way for the learns.

**Comment by josharian** [comment]
I played with this a tiny bit after filing the issue. I have a sketch of it along with quite a few TODOs left. I’d love for you to get it over the finish line! I’ll put my WIP up somewhere a bit later for you.

**Comment by josharian** [comment]
@bradford-hamilton all yours, unless/until I hear otherwise from you. :)

**Comment by bradford-hamilton** [comment]
@josharian thanks! Sounds good to me.

**Comment by randall77** [comment]
I believe this is done.
