### ISSUE TITLE
x/net/html: Weird behavior with comment parsing

### ISSUE THREAD

**Issue by empijei** [golang/go#37771]
This bug was found by fuzzing. See master issue #27848

### What version of Go are you using (`go version`)?
1.14

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Not relevant

### What did you do?

https://play.golang.org/p/kSpNN8dsXkk

```go
func main() {
	Render([]byte("<html><!--!--> <head></head><body></body></html>"))
	fmt.Println()
	Render([]byte("<html><!--! --><head></head><body></body></html>"))
}

func Render(b []byte) {
	nodes, err := html.ParseFragment(bytes.NewReader(b), nil)
	if err != nil {
		panic(err)
	}
	var sb strings.Builder
	for _, n := range nodes {
		if err := html.Render(&sb, n); err != nil {
			fmt.Println(err)
			panic("cannot render parsed HTML")
		}
	}
	fmt.Println(sb.String())
}
```

### What did you expect to see?
```html
<html><!--!--> <head></head><body></body></html>

<html><!--! --><head></head><body></body></html>
```

### What did you see instead?

```html
<html><!--!--> <head></head><body></body></html>--><head></head><body></body></html>

<html><!--! --><head></head><body></body></html>
```

 ### Comment
I find this to be a rather odd behavior. It looks like the bang after the open comment tag confuses the parser into believing the entire rest of the string is still inside the comment. I don't know if this is intended but I don't think it should be.

Modern browsers seem to agree with my assessment: https://www.w3schools.com/code/tryit.asp?filename=GCOZ59QJSL6W

Edit: this happens also with "<" and other symbols.

/cc @katiehockman @FiloSottile @LMMilewski

**Comment by ewjoachim** [comment]
Here is a simpler version that triggers the same bug with the tokenizer, so the issue is with the tokenization and not the parsing:
```go
package main

import (
	"fmt"
	"strings"

	"golang.org/x/net/html"
)

func main() {

	text := "<!--!--><h1>Hey</h1>"

	tkn := html.NewTokenizer(strings.NewReader(text))

	for {

		tt := tkn.Next()
		if tt == html.ErrorToken {
			return
		}
		fmt.Println(tt)
		t := tkn.Token()
		fmt.Println("  ", t.Data)

	}
}
```
