### ISSUE TITLE
runtime: created thread still not exit while goroutine has exit for a long time

### ISSUE THREAD

**Issue by linqh1** [golang/go#37772]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.10 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes, still in version `go version go1.14 linux/amd64`

but <b>less threadcreate</b>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build006288910=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I open 2 goroutines and do http request in loop, last 120 seconds

mock-echo-server.go: https://play.golang.org/p/n8oe5bLP3SS

build and run (listen on 127.0.0.1:9876)
`
./mock-echo-server
`

http-client.go: https://play.golang.org/p/99AXCkBZp8q

build and run (do http request(127.0.0.1:9876) for 120 seconds and sleep, pprof listen on 127.0.0.1:11111)
`
./http-client
`

### What did you expect to see?
1 hour gone, the threadcreate number should decrease to normal

### What did you see instead?
threadcreate number is still keep in maxium(70+ for go 1.11.10, 20+ for go 1.14)

image for prrof, since http request has been stop for 1 hour

go 1.11
![image](https://user-images.githubusercontent.com/42435177/76303218-583e9b00-62fc-11ea-88f4-78dbf48ad2f0.png)

go 1.14
![image](https://user-images.githubusercontent.com/42435177/76303249-62609980-62fc-11ea-9bc7-1d3344516f09.png)

I wonder why `http-client.go` still keep those idle threads while most of goroutine has exit for a long time.

Is there a way to stop those idle threads?

**Comment by toothrot** [comment]
From [the docs](https://golang.org/pkg/runtime/pprof/):

> threadcreate - stack traces that led to the creation of new OS threads

Is this not a cumulative number?

It's not clear to me that this is a bug. See https://golang.org/wiki/Questions for help debugging Go. I will close this issue, but please comment if you feel I am incorrect.

**Comment by linqh1** [comment]
> From [the docs](https://golang.org/pkg/runtime/pprof/):
> 
> > threadcreate - stack traces that led to the creation of new OS threads
> 
> Is this not a cumulative number?
> 
> It's not clear to me that this is a bug. See https://golang.org/wiki/Questions for help debugging Go. I will close this issue, but please comment if you feel I am incorrect.

I check the thread count of `http-client` process, it does keep 69 threads alive
`cat /proc/210686/status | grep Threads`
`Threads:	69`

**Comment by ianlancetaylor** [comment]
Threads created by the Go runtime do not normally exit.
