### ISSUE TITLE
x/pkgsite: do not show packages of a module at the top level

### ISSUE THREAD

**Issue by typeless** [golang/go#37788]
### What is the URL of the page with the issue?
https://pkg.go.dev/search?q=gui
https://pkg.go.dev/search?q=gitea

### What did you do?
Searching for GUI packages

### What did you expect to see?
A list of modules. Packages and sub-packages of a same module should not show in a scattered manner. 
Also, some projects have more than one forks/mirrors and the same packages would show repeatedly, which is confusing.

When searching at pkg.go.dev, it shows all packages and sub-packages of a module and the packages of different modules are interspersed. It makes the result look scattered. I propose that pkg.go.dev only shows modules at the top level and only expands the view of packages of a module when explicitly chosen by the user.

It is probably related to https://github.com/golang/go/issues/26827.

**Comment by julieqiu** [comment]
Thanks for the feedback! This seems to be related to #36814, #36806. Also #37810 for tracking.

**Comment by julieqiu** [comment]
This will be addressed #47321, so closing this issue.
