### ISSUE TITLE
x/sys/unix: add support for L2TPIP sockaddr on Linux

### ISSUE THREAD

**Issue by tomparkin** [golang/go#37787]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tom/.cache/go-build"
GOENV="/home/tom/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tom/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build096416278=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Linux kernel supports L2TPv3 (RFC3931) IP-encapsulated tunnels using two special sockaddr structures which include the L2TP control connection ID.  These structures "struct sockaddr_l2tpip" and "struct sockaddr_l2tpip6" are not currently represented in x/sys/unix, meaning that Go programs cannot conveniently create L2TPv3 IP encapsulated tunnels.

The unix package should be extended to include types for the L2TPIP-specific sockaddr structures.

**Comment by tomparkin** [comment]
I have been working on code to implement this support, current version here:

https://github.com/tomparkin/sys/commit/ec1d125b70f93db64a52dbe3a5cd2b7d70666e3c

This is still work-in-progress.  Although I have unit tested my changes I'd like to test them further.

**Comment by tklauser** [comment]
@tomparkin Feel free to send a CL/PR once you have a version ready for review.

**Comment by tomparkin** [comment]
PR here: https://github.com/golang/sys/pull/60

I'm not sure how to automatically associate the PR with this issue :-(

**Comment by tklauser** [comment]
> PR here: [golang/sys#60](https://github.com/golang/sys/pull/60)
> 
> I'm not sure how to automatically associate the PR with this issue :-(

Just add `Fixes golang/go#37787` in the PR description.
