### ISSUE TITLE
make.bat: should use \r\n instead of \n as line delimiters

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#37791]
### What version of Go are you using (`go version`)?

<pre>
go version devel +b5c66de089 Sun Mar 8 19:03:08 2020 +0000 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, it does.

### What did you do?

@rasky was changing src/make.bat file in CL 96495 and he was having unexpected errors of

`The system cannot find the batch label specified - ...`

while making changes to make.bat file. It appears Windows cmd.exe sometimes fails with this error when its executing batch file with only `\n` as delimiters.  As soon as you replace `\n` with `\r\n`, everything works as expected.

@rasky send me these links with gruesome details (for anyone who is interested)

https://web.archive.org/web/20160305063042/help.wugnet.com/windows/system-find-batch-label-ftopict615555.html

https://stackoverflow.com/questions/232651/why-the-system-cannot-find-the-batch-label-specified-is-thrown-even-if-label-e/6419068

He is also provided small repro batch file - [good_and_bad.zip](https://github.com/golang/go/files/4317035/good_and_bad.zip)

And indeed I can reproduce the problem on my currently updated Windows 10.

```
C:\Users\Alex\AppData\Local\Temp\a>good

C:\Users\Alex\AppData\Local\Temp\a>goto BROWSER

C:\Users\Alex\AppData\Local\Temp\a>bad

C:\Users\Alex\AppData\Local\Temp\a>goto BROWSER
The system cannot find the batch label specified - BROWSER

C:\Users\Alex\AppData\Local\Temp\a>
```

I think, we should change all *.bat files in the source tree to use `\r\n` instead of `\n`.

This is what CL 96495 does. And I am happy to +2 the CL, but decided to post here in case someone objects.

Also @bradfitz (while reviewing CL 96495) said

> Please still add a test.
> 
> I want to make sure our release zip files absolutely have the right line endings.
> 
> Will the Gerrit *.tar.gz serving endpoint respect this gitattributes file? I'm not sure.
> 

What kind of test do we want? How can we verify Gerrit *.tar.gz?

I am sure Microsoft will not change anything, but adding @jstarks FYI.

Thank you.

Alex

**Comment by rasky** [comment]
I second @bradfitz idea of having tests, but I have no clue how I can write a test for this. Can somebody give me an idea?

For instance, I could add a test within `test/` that walks all GOROOT, find all batch files, and verify that they contain at least a "CRLF" sequence (or, if we want to be more precise, that it never contains a LF without a preceding CR -- but at this point I think we're testing git behavior rather than our own configuration). This might be slowish though -- I know we we want to keep all.sh fast. So maybe we could check just `make.bat`, or hardcode a list of other batch files that are committed as of today.

But I have no clue where I am supposed to write code that checks Gerrit downloads.

@alexbrainman let me know how you prefer to proceed

**Comment by alexbrainman** [comment]
> For instance, I could add a test within `test/` that walks all GOROOT, find all batch files, and verify that they contain at least a "CRLF" sequence (or, if we want to be more precise, that it never contains a LF without a preceding CR

I would only test *.bat files in src directory. Your testing approach sounds good to me. It is difficult to say where to put the test. Maybe in cmd/go/go_test.go?

> But I have no clue where I am supposed to write code that checks Gerrit downloads.

No clue.

Lets wait for a day or two. Hopefully others will chime in. Maybe even Brad will reply.

Thank you.

Alex

**Comment by rasky** [comment]
@alexbrainman nobody chimed in. I will write a simple test that works only on the working copy and rebase the CL, so that you can approve it

**Comment by alexbrainman** [comment]
> I will write a simple test that works only on the working copy and rebase the CL, so that you can approve it

Sounds good to me. As we agreed.

Alex
