### ISSUE TITLE
How to consume a non-module package in go modules?

### ISSUE THREAD

**Issue by chihkaiyu** [golang/go#37797]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/chihkaiyu/.cache/go-build"
GOENV="/home/chihkaiyu/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/chihkaiyu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/chihkaiyu/Documents/playground/golang/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build728875867=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I try to add this package as my dependency.  
https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/go/src/AccessToken/AccessToken.go

### What did you expect to see?
I thought go modules could consume non-module package. Am I missing something here?

### What did you see instead?
Go modules complains about `go.mod` not exist.
```
$ go mod tidy
go: github.com/AgoraIO/Tools/DynamicKey/AgoraDynamicKey/go/src/AccessToken@v0.0.0-20190826130428-f39dcc149cc1: invalid version: missing github.com/AgoraIO/Tools/DynamicKey/AgoraDynamicKey/go/src/AccessToken/go.mod at revision f39dcc149cc1
```

### Minimum reproduce code
main.go
```go
package main

import (
	"fmt"

	"github.com/AgoraIO/Tools/DynamicKey/AgoraDynamicKey/go/src/AccessToken"
)

func main() {
	fmt.Println(accesstoken.getVersion())
}
```

go.mod
```
module golang

go 1.14

require github.com/AgoraIO/Tools/DynamicKey/AgoraDynamicKey/go/src/AccessToken v0.0.0-20190826130428-f39dcc149cc1

```

**Comment by toothrot** [comment]
For asking questions about learning the language, see one of our forums: https://golang.org/wiki/Questions. We only use this issue tracker for tracking bugs. People in the forums can explain what is happening here.

In this case, your require statement should be the name of the repo:

```
require github.com/AgoraIO/Tools v0.0.0-20190826130428-f39dcc149cc1
```

Also note that `getVersion()` is not exported and is unusable in your package.
