### ISSUE TITLE
net: SplitHostPort() doesn't respect RFC5952 section 6

### ISSUE THREAD

**Issue by pierre-emmanuelJ** [golang/go#37817]
`go version go1.13.1 linux/amd64`

repreduced with latest stable version of GO
https://play.golang.org/p/O2OIUNDXPZ_9

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOENV="/home/ubuntu/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build274095054=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

to repreduce the issue:

According to the following screenshot of the RFC5952 section 6, `net.SplitHostPort()` doesn't respect it.
the function doesn't support `<ipv6>:<port>` parsing and support only`[<ipv6>]:<port>`.

![image](https://user-images.githubusercontent.com/15922119/76517841-58ef4280-645e-11ea-9c78-fc43450363bd.png)

https://play.golang.org/p/O2OIUNDXPZ_9

### What did you expect to see?

2a04:c44:e00:147a:441:aaff:fe00:1d2:8080 parsed to ip=2a04:c44:e00:147a:441:aaff:fe00:1d2 port=8080

### What did you see instead?

error output: too many colons in address

**Comment by seankhliao** [comment]
This RFC is for host/port in text, `net` works with URIs, which the RFC says MUST follow RFC3986, which specifies the square brackets must be included

- [RFC 5952 Section 6 (this issue)](https://tools.ietf.org/html/rfc5952#section-6)
- [RFC 3986 Section 3.2.2 Host](https://tools.ietf.org/html/rfc3986#section-3.2.2)

**Comment by AlexDyukov** [comment]
[godoc](https://godoc.org/net#SplitHostPort) :
`A literal IPv6 address in hostport must be enclosed in square brackets, as in "[::1]:80", "[::1%lo0]:80".`

**Comment by pierre-emmanuelJ** [comment]
Thanks for your reply.
https://golang.org/src/net/ip.go#L572 it's mentioned  `// and RFC 5952.`.

**Comment by toothrot** [comment]
@pierre-emmanuelJ I agree with the above comments that this seems to be working as intended. 

Are you proposing that this should be changed? Are you intending to use the value for Dial, or something else?

**Comment by pierre-emmanuelJ** [comment]
If you think it's a good idea to add this feature, I'm not against 😃. If I have time I'll add my contribution

**Comment by seankhliao** [comment]
How are you proposing to handle the ambiguity in addresses that have a `::`?

**Comment by toothrot** [comment]
@pierre-emmanuelJ It would help to know how you intend to use the value, or why you would need this kind of change.
