### ISSUE TITLE
something wrong might happen during memory dynamic allocation for array

### ISSUE THREAD

**Issue by redsnapper2006** [golang/go#37814]
something wrong might happen during memory dynamic allocation for array
(otherwise, I am using `append` in wrong way, if so, feel free to correct me)

below code works for []int{1,2,3,4}
not work for []int{1,2,3,4,5}
when input array goes to []int{1,2,3,4,5,6}
still not work correctly in item `5` instead of `6` even `6` is the last one.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
YES, 1.14 is

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xxx/Library/Caches/go-build"
GOENV="/Users/xxx/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xxx/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xxx/my_gitrepo/go/S/78-subsets/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2g/w39rx1hn2791chnt1m7w2p9m0000gn/T/go-build831985032=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```

func subsets(nums []int) [][]int {
	if len(nums) == 0 {
		return [][]int{}
	}
	buf := [][]int{[]int{}, []int{nums[0]}}
	for i := 1; i < len(nums); i++ {
		size := len(buf)
		for j := 0; j < size; j++ {
			buf = append(buf, append(buf[j], nums[i]))
		}
	}
	return buf
}

func main() {
	fmt.Println(subsets([]int{1, 2, 3, 4, 5, 6}))
}
```

### What did you expect to see?
```
[[] [1] [2] [1 2] [3] [1 3] [2 3] [1 2 3] [4] [1 4] [2 4] [1 2 4] [3 4] [1 3 4] [2 3 4] [1 2 3 4] [5] [1 5] [2 5] [1 2 5] [3 5] [1 3 5] [2 3 5] [1 2 3 5] [4 5] [1 4 5] [2 4 5] [1 2 4 5] [3 4 5] [1 3 4 5] [2 3 4 5] [1 2 3 4 5] [6] [1 6] [2 6] [1 2 6] [3 6] [1 3 6] [2 3 6] [1 2 3 6] [4 6] [1 4 6] [2 4 6] [1 2 4 6] [3 4 6] [1 3 4 6] [2 3 4 6] [1 2 3 4 6] [5 6] [1 5 6] [2 5 6] [1 2 5 6] [3 5 6] [1 3 5 6] [2 3 5 6] [1 2 3 5 6] [4 5 6] [1 4 5 6] [2 4 5 6] [1 2 4 5 6] [3 4 5 6] [1 3 4 5 6] [2 3 4 5 6] [1 2 3 4 5 6]]
```

### What did you see instead?
```
[[] [1] [2] [1 2] [3] [1 3] [2 3] [1 2 3] [4] [1 4] [2 4] [1 2 4] [3 4] [1 3 4] [2 3 4] [1 2 3 6] [5] [1 5] [2 5] [1 2 5] [3 5] [1 3 5] [2 3 5] [1 2 3 6] [4 5] [1 4 5] [2 4 5] [1 2 4 6] [3 4 5] [1 3 4 6] [2 3 4 6] [1 2 3 5 5] [6] [1 6] [2 6] [1 2 6] [3 6] [1 3 6] [2 3 6] [1 2 3 6] [4 6] [1 4 6] [2 4 6] [1 2 4 6] [3 4 6] [1 3 4 6] [2 3 4 6] [1 2 3 6 6] [5 6] [1 5 6] [2 5 6] [1 2 5 6] [3 5 6] [1 3 5 6] [2 3 5 6] [1 2 3 6 6] [4 5 6] [1 4 5 6] [2 4 5 6] [1 2 4 6 6] [3 4 5 6] [1 3 4 6 6] [2 3 4 6 6] [1 2 3 5 5 6]]
```

**Comment by randall77** [comment]
This is how `append` works. It does not necessarily copy the underlying array, so two appends onto the same slice may overwrite each other.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only. Please see https://github.com/golang/go/wiki/Questions for some more appropriate forums for your question.

**Comment by randall77** [comment]
Try appending onto `buf[j][:len(buf[j]):len(buf[j])]`, that will force a copy.

**Comment by ianlancetaylor** [comment]
Please read https://golang.org/blog/slices.
