### ISSUE TITLE
go.dev: insert space after Example

### ISSUE THREAD

**Issue by gopherclass** [golang/go#37816]
### What is the URL of the page with the issue?
https://pkg.go.dev/golang.org/x/text@v0.3.2/encoding/ianaindex?tab=doc#example-Index

Though I tested at the link, you are able to observe anywhere where Example exists. 
 
### What is your user agent?
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

Latest chrome

### Screenshot
 
<img width="702" alt="example box" src="https://user-images.githubusercontent.com/56159921/76516651-287bc880-649f-11ea-95ff-8e9af9d66b79.png">

 
### What did you do?
 

 
1. Open the link.
2. Click Example text.
 
### What did you expect to see?
It's design proposal, not real bug. I think space should be inserted after Example box (after `Output: ` in the image).

**Comment by julieqiu** [comment]
Thanks for the feedback! We will plan to address this as part of an upcoming round of UX changes.

/cc @fflewddur

**Comment by julieqiu** [comment]
This is fixed. Thanks @Sajmani for the contribution!
