### ISSUE TITLE
x/tools/gopls: high CPU on leftover daemon process after update

### ISSUE THREAD

**Issue by findleyr** [golang/go#37829]
Forked from @zikaeroh's comment on #34111:
https://github.com/golang/go/issues/34111#issuecomment-597374272

> One thing I've noticed after doing a couple of gopls upgrades with this enabled is that the unused process seems to use CPU when I change my project's files even when no session is attached (e.g. I ask VSC to restart the language server, I get a new gopls serve process as the build ID changed, then edit a file while watching htop).

> Is gopls doing some sort of extra file watching? I had thought it was only using LSP's file watcher, but the fact that it's responding to edits for files it doesn't have "open" is strange.

**Comment by zikaeroh** [comment]
Note that the update here is on `gopls`, not VS Code itself (though I do trigger an "update" by asking it to restart `gopls` and it runs the new binary).

**Comment by findleyr** [comment]
Thanks, that's what I meant (an update trigger from VSCode) but it was poorly worded. Updated the title.

**Comment by findleyr** [comment]
My best guess was that this was due to redundant gopls processes (binary identity is included in auto-discovery), but this is hard to diagnose/fix, and very minor impact. Unfortunately, it's unlikely that this will ever be fixed directly (though it may be improved by fixes to server shutdown in the new version of the jsonrpc2 library). Closing this issue as infeasible.
