### ISSUE TITLE
cmd/compile: functions with type switches cannot be inlined

### ISSUE THREAD

**Issue by aebrahim** [golang/go#37837]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
N/A 1.14 is the latest release

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
</pre></details>

### What did you do?
go build -gcflags="-m -m" demo.go
[demo.go.txt](https://github.com/golang/go/files/4327544/demo.go.txt)

### What did you expect to see?
Inlining of small function after #13071

### What did you see instead?
./demo.go:15:6: cannot inline SomeFunc: unhandled op TYPESW

**Comment by randall77** [comment]
I think we just need to figure out what cost we should assign it.
