### ISSUE TITLE
a problem about cgo(Error arguments passing when c cod call go function)

### ISSUE THREAD

**Issue by william-zk** [golang/go#37841]
### What version of Go are you using (`go version`)?

<pre>
$ go-1.12 and go-1.13 all find this problem

</pre>

### Does this issue reproduce with the latest release?

I'm not sure problem has been fixed in go1.14

### What operating system and processor architecture are you using (`go env`)?

macos and linux-amd64 all find this problem

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
</pre></details>

### What did you do?

my code is below:
```
/*
void call_func(void (*cb) (int))
{
    int a = 0;
    cb(a);
}
*/
import "C"
import (
	"reflect"
	"unsafe"
)

func foo(i C.int) {
	print(int(i))
}

func main() {
	C.call_func((*[0]byte)(unsafe.Pointer(reflect.ValueOf(foo).Pointer())))
}
```
### What did you expect to see?

These code  are expected to print "0" to stdout

### What did you see instead?

I get "4515468" or some other strange number, it seems that the process of address passing was wrong when c code call go function. I do know that use "//export foo" , then call corresponding c function is the right way. I hope to find out the reason of this phenomenon, thanks for answering:-)

**Comment by bcmills** [comment]
Go's calling convention is not the same as C's calling convention — you cannot simply use `unsafe` to convert a Go function value to a C function pointer.

See https://golang.org/cmd/cgo/#hdr-C_references_to_Go for how to export a Go function using the C calling convention. (But you may need some forward-declaration workarounds if you want to use it as a callback in the same package: see #19837, #19836, and #19835.)
