### ISSUE TITLE
crypto/x509: check that private key matches the issuer

### ISSUE THREAD

**Issue by shoobyban** [golang/go#37845]
I have checked several examples and couldn't find out why my client certificate was invalid, until @FiloSottile pointed out that I'm trying to sign the cert with its own key.

A check is possible as we pass the public key.

https://github.com/golang/go/blob/c3b9042132efc4e9f3485cd12b07acd1ca9c7d57/src/crypto/x509/x509.go#L2084

Behaviour: after successful creation of certificate on connection checks fail with "x509: ECDSA verification failure"

Expected behaviour: CreateCertificate would return an error stating signing with own key will not be a successful tactic.

**Comment by odeke-em** [comment]
@FiloSottile shall we move this perhaps to the Go1.16 milestone or are thinking of more work on this during Go1.15? Thank you!

**Comment by FiloSottile** [comment]
Yep, definitely slipped to Go 1.16.

**Comment by odeke-em** [comment]
Moving this to Go1.17, as we didn’t get action for Go1.16.
