### ISSUE TITLE
go.dev: 500 internal server errors being returned

### ISSUE THREAD

**Issue by myitcv** [golang/go#37847]
### What is the URL of the page with the issue?

https://pkg.go.dev/golang.org/x/tools/imports?tab=doc

### What is your user agent?

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.66 Safari/537.36
</pre>

### Screenshot

<img width="750" alt="Screen Shot 2020-03-13 at 20 59 00" src="https://user-images.githubusercontent.com/3374574/76659229-c2aa4200-656d-11ea-85ed-b9c5455ca4d4.png">

### What did you do?

Visit the page

### What did you expect to see?

The page loaded as normal

### What did you see instead?

500 internal server error, roughly 2 mins ago

**Comment by toothrot** [comment]
Thank you! We're looking into it and will post here once we have more info.

**Comment by toothrot** [comment]
This appears to have resolved, but we do not have any details to add at this time as to what caused the issue. I'm going to close the issue for now.
