### ISSUE TITLE
Why doesn't "net/http" server return the Connection in response header !?

### ISSUE THREAD

**Issue by tech-a-go-go** [golang/go#37850]
Hi there,

Here is my server which returns a current time.
I accessed this server with Chrome. 
I checked the response header with chrome's development tool but Connection header is missing 
 in the response header even though chrome sent "Connection: keep-alive" in request header.
Why why why !?!?!?!?
Are there any options to send Connection header in response or what ?
How can I enable keep-alive for this server ?
```
package main

import (
	"io"
	"net/http"
	"time"
)

func ShowTime(w http.ResponseWriter, _ *http.Request) {
	now := time.Now().Format(time.RFC3339Nano)
	io.WriteString(w, now)
}

func main() {
	http.HandleFunc("/", ShowTime)
	log.Fatal(http.ListenAndServe(":1234", nil))
}
```

Cheers

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker for questions.  You will get better and faster answers in a forum.  Please see https://golang.org/wiki/Questions.  Thanks.

HTTP keep-alives are enabled by default for net/http.Server.  See https://golang.org/pkg/net/http/#Server.SetKeepAlivesEnabled.  I have no explanation for what you are seeing.
