### ISSUE TITLE
x/sync: semaphore.Weighted.Acquire should try to notify other waiters when canceled

### ISSUE THREAD

**Issue by zhiqiangxu** [golang/go#37852]
When `Release`, if the remaining tokens are not enough for the front waiter, no waiters will be notified.

So if the canceled waiter is the front one, it should try to notify following waiters if there are remaining tokens.

I found this bug when implementing a cancelable rwmutex based on semaphore:

https://github.com/zhiqiangxu/util/blob/master/mutex/crwmutex.go

This bug can be verified by this test:

https://github.com/zhiqiangxu/util/blob/master/mutex/crwmutex_test.go#L43

I've submitted a PR here: https://github.com/golang/sync/pull/10

**Comment by cagedmantis** [comment]
This has been fixed via: https://go-review.googlesource.com/c/sync/+/223418
