### ISSUE TITLE
net/http/httputil: dumps `CONNECT` httpRequest  not correctly

### ISSUE THREAD

**Issue by fdistorted** [golang/go#37858]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/andrii/.cache/go-build"
GOENV="/home/andrii/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="gitlab.com"
GONOSUMDB="gitlab.com"
GOOS="linux"
GOPATH="/home/andrii/go"
GOPRIVATE="gitlab.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build663872885=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

here is example of [code](https://play.golang.org/p/rnzMnKN37_1)

### What did you expect to see?
output should be:
```
dump request
CONNECT google.com:80 HTTP/1.1
Host: google.com:80
```

### What did you see instead?

I see:
```
dump request
CONNECT / HTTP/1.1
Host: google.com:80
```

**Comment by seankhliao** [comment]
client requests should use `DumpRequestOut` https://golang.org/pkg/net/http/httputil/#DumpRequestOut

**Comment by cagedmantis** [comment]
@seankhliao is correct. Client requests should use `DumpRequestOut` as noted in the documentation linked above. This is working as intended.
