### ISSUE TITLE
cmd/go: builtin test timeout conflicts with -count

### ISSUE THREAD

**Issue by dvyukov** [golang/go#37856]
```
$ go test -count=100000 fmt
SIGQUIT: quit
PC=0x459371 m=0 sigcode=0
...
*** Test killed with quit: ran too long (10m0s).
FAIL	fmt	600.023s
```

Hit on my package with just -count=10 (tests runs for longer). I would expect this to not fail (should finish in 15 mins or so).

go version go1.12 linux/amd64

**Comment by ALTree** [comment]
See #12446 and #17337.

**Comment by dvyukov** [comment]
dup of #12446
