### ISSUE TITLE
Timezone location is returned as "Local" instead of "/etc/localtime" location

### ISSUE THREAD

**Issue by subbu11** [golang/go#37855]
I want to retrieve timezone location of my system

```
t = time.Now()
tzLoc = t.Location().String()
```
tzLoc is returned as "Local".

I have checked the `time` package source code. As per the source-code, if `TZ` is not set, then `/etc/localtime` is referred.

`TZ` environment variable is not set, and following is the `/etc/localtime` on my system

`lrwxrwxrwx. 1 root root 38 Jan 16 06:33 /etc/localtime -> ../usr/share/zoneinfo/America/New_York`

Ideally, time package should return `America/New_York`, but still it is returning as `Local`

What should I do to get timezone location as `America/New_York` ?

**Comment by andig** [comment]
time docs say:

> No TZ means use the system default /etc/localtime. TZ="" means use UTC. TZ="foo" means use file foo in the system timezone directory.

So I'd expect this to return `America/New_York`

**Comment by ianlancetaylor** [comment]
The default local timezone is always reported with the name `"Local"`.  The timezone database does not store names like `America/New_York`, so there is no simple way for the time package to determine that name.  It's true that in your case it could be done by using `readline` on /etc/localtime to determine the name of the file being read, but that isn't a general mechanism.

You'll find that the `Local` timezone uses the correct timezone offset and the correct daylight saving time transitions.  The only thing it doesn't provide is the name.  The timezone database provides "name -> timezone data".  It doesn't provide "timezone data -> name".

**Comment by andybons** [comment]
This is showing up in search results for open issues. Reopening and closing to hopefully trigger whatever indexing is needed.
