### ISSUE TITLE
x/tools/gopls: "method textDocument/completion did not reply"

### ISSUE THREAD

**Issue by foxcpp** [golang/go#37859]
#### What did you do?

1. Use gopls with [LanguageClient-neovim](github.com/autozimu/LanguageClient-neovim).
2. Open the file with the following contents:
```go
package main

import "net"

type S struct {
	F int
}

func main() {
	s := S{}

}
```
3. Place the cursor on the empty line in main and type `s.F, a = net`, 
4. LanguageClient-neovim triggers completion to show `net` contents.

- The issue is not specific to the `net` package, but does not affect all packages. `errors` works correctly. `net`, `os` and `github.com/wireguard/wgctrl-go` do not.
- I do not know whether the issue is specific to the LanguageClient-neovim behavior or not.
- If the package is not imported and completeUnimported is enabled, completion is shown correctly.

#### What did you expect to see?

Completion popup with things exported by `net` .

#### What did you see instead?

gopls exits, no completion is shown. LanguageClient-neovim prints the following messages:
```
[LC] Error: Failure { jsonrpc: Some(V2), error: Error { code: InternalError, message: "method \"textDocument/completion\" did not reply", data: N
one }, id: Num(3) }
[LC] sending on a disconnected channel
[LC] sending on a disconnected channel
```
Last two are likely related to the gopls process exiting.

#### Build info

```
golang.org/x/tools/gopls v0.3.3
    golang.org/x/tools/gopls@v0.3.3 h1:mTFqRDJQmpSsgDDWvbtGnSva1z9uX2XcDszSWa6DhBQ=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=
    golang.org/x/mod@v0.1.1-0.20191105210325-c90efee705ee h1:WG0RUwxtNT4qqaXX3DPA8zHFNm/D9xaBpxzHt1WcA/E=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20200227200655-6862ededa516 h1:OX66ZzpltgCOuBSGdaeT77hS2z3ub2AB+EuGxvGRBLE=
    golang.org/x/xerrors@v0.0.0-20191011141410-1b5146add898 h1:/atklqdjdhuosWIl6AIbOeHJjicWYPqR9bpxqxYG2pA=
    honnef.co/go/tools@v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=
```

#### Go info

```
go version go1.14 linux/amd64

GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/foxcpp/.go/bin"
GOCACHE="/home/foxcpp/.cache/go-build"
GOENV="/home/foxcpp/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/foxcpp/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/foxcpp/gopls-bug/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build364981597=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by foxcpp** [comment]
[gopls.txt](https://github.com/golang/go/files/4333324/gopls.txt)


gopls log with `-rpc.trace`. Also uploaded to https://hastebin.com/herurufoma.

**Comment by muirdm** [comment]
Should be fixed by https://go-review.googlesource.com/c/tools/+/221020. The fix will be included in the next release. You can install from master in the meantime if you are hitting it a lot (it is triggered by the undeclared "a" identifier in the assignment.

**Comment by foxcpp** [comment]
Verified it is fixed at golang.org/x/tools/gopls@v0.1.8-0.20200316182129-bd88ce97550a. Thanks!

**Comment by stamblerre** [comment]
Thanks for confirming! I'll try to release `gopls/v0.3.4` with this fix in the next few days.
