### ISSUE TITLE
cmd/go: inconsistent vendoring in c:\Go\src

### ISSUE THREAD

**Issue by bathildis** [golang/go#37864]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\bathi\AppData\Local\go-build
set GOENV=C:\Users\bathi\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Go\src\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\bathi\AppData\Local\Temp\go-build653975358=/tmp/go-build -gno-record-gcc-switches    
</pre></details>

### What did you do?

$ go get github.com/PuerkitoBio/goquery

### What did you expect to see?
It was the first time I downloaded external code and I just wrote code like this and run and it failed.
```
package main
import (
	"fmt"
)
func main() {
	fmt.Println("test")
}
```

I tried to go mod vendor and go mod tidy but it didn't work

### What did you see instead?
```
go: inconsistent vendoring in c:\Go\src:
	github.com/PuerkitoBio/goquery@v1.5.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/net@v0.0.0-20200202094626-16171245cfb2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/net@v0.0.0-20191126235420-ef20fe5d7933: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod

run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory
exit status 1
Process exiting with code: 1
```

**Comment by rajender** [comment]
It looks like your GOROOT & GOPATH pointing to same directory. Can you change GOPATH to different dirrctory and try?

**Comment by sidney-cardozo** [comment]
I have the exact same issue when installing this goquery package. @bathildis how did you solve this?

**Comment by Aminoragit** [comment]
same problem did u solved?
