### ISSUE TITLE
Go latest update to 1.14   crashes into machine code on mac os 10.11.6 

### ISSUE THREAD

**Issue by rbrooker002** [golang/go#37861]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by rbrooker002** [comment]
Here is the crash info in the terminal after I followed all instruction on updating go on mac osbuild hello.go
SIGILL: illegal instruction
PC=0x1066040 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
	/usr/local/go/src/runtime/preempt_amd64.s:8 fp=0xc00004cef0 sp=0xc00004cee8 pc=0x1066040
fmt.init()
	/usr/local/go/src/fmt/scan.go:465 fp=0xc00004cef8 sp=0xc00004cef0 pc=0x10e6540
runtime.doInit(0x1a80520)
	/usr/local/go/src/runtime/proc.go:5414 +0x8a fp=0xc00004cf28 sp=0xc00004cef8 pc=0x1043aca
runtime.doInit(0x1a80ec0)
	/usr/local/go/src/runtime/proc.go:5409 +0x57 fp=0xc00004cf58 sp=0xc00004cf28 pc=0x1043a97
runtime.doInit(0x1a850c0)
	/usr/local/go/src/runtime/proc.go:5409 +0x57 fp=0xc00004cf88 sp=0xc00004cf58 pc=0x1043a97
runtime.main()
	/usr/local/go/src/runtime/proc.go:190 +0x1ce fp=0xc00004cfe0 sp=0xc00004cf88 pc=0x103702e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00004cfe8 sp=0xc00004cfe0 pc=0x10647d1

rax    0x1a80520
rbx    0xb
rcx    0x0
rdx    0x1a80578
rdi    0xc000092180
rsi    0x10e6540
rbp    0xc00004cf18
rsp    0xc00004cee8
r8     0x2910490d
r9     0x203000
r10    0x2
r11    0x11
r12    0xf5
r13    0x55555555555555
r14    0x171acac
r15    0x38
rip    0x1066040
rflags 0x10202
cs     0x2b
fs     0x0
gs     0x0

**Comment by ianlancetaylor** [comment]
Dup of #37459.
