### ISSUE TITLE
cmd/compile: sw_64cpu compile failed

### ISSUE THREAD

**Issue by Ccaomei** [golang/go#37877]
I recently in the winning ShenWei CPU compilation go1.14 kirin system source code, compile problem: go1.14 / SRC/runtime/runtime1. Go: 162-22: internal compiler error: 'check' : panic during opt while compiling the check:
Runtime error: floating point error

Please take a look at it for me. Thank you very much！！！

**Comment by Ccaomei** [comment]
I used the riscv64 instruction set to compile, and the environment variable was set to export GOHOSTARCH=riscv64, export GO_GCFLAGS=all=-d=checkptr=0

**Comment by josharian** [comment]
Thanks for the report. Some questions. Can you share the source code that you were compiling? Does the error happen reliably, or only once? If I read correctly, you were compiling on your riscv64 machine. How did you bootstrap the toolchain that you were using?

**Comment by josharian** [comment]
cc @4a6f656c

**Comment by Ccaomei** [comment]
I was in the bid kirin, sw_64 CPU, compiled go1.14, I changed the code in the CMD /dist/main.go file, detected sw_64 arch, set it to riscv64 instruction set, and then execute.Every time it happens, it's inevitable.

**Comment by 4a6f656c** [comment]
I presume you're referring to the [Sunway](https://en.wikipedia.org/wiki/Sunway_(processor)) architecture?

If so, I highly doubt these are [RISC-V](http://riscv.org/) based, hence would not expect riscv64 to work on this hardware (but I could be wrong).

**Comment by Ccaomei** [comment]
Yes, it is at Sunway architecture. I would like to ask you how to solve the compilation problem that I am currently encountering. Is there any solution? @4a6f656c

**Comment by Ccaomei** [comment]
@4a6f656c Do you know how to compile go source code on Sunway CPU?

**Comment by randall77** [comment]
You might be able to use gccgo on your platform. Presumably gcc works?
The standard Go distribution will not work. It cannot target that architecture, as far as I can tell (although the wikipedia page for Sunway doesn't provide enough details to be 100% sure).
