### ISSUE TITLE
go.dev: broken links on license policy page for non-OSI licenses

### ISSUE THREAD

**Issue by lazyhacker** [golang/go#37872]
### What is the URL of the page with the issue?

https://pkg.go.dev/license-policy
 
### What is your user agent?
 
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36  
 
### What did you do?
 
Clicked Unlicence and  CCO-1 links and resulted in a page not found.

### What did you expect to see?
 
 Either no links or links to pages that has info about those licenses.
 
### What did you see instead?

page not found

**Comment by julieqiu** [comment]
Thanks for letting us know!

/cc @jba

**Comment by jba** [comment]
This is fixed at head and will be in the next release.
