### ISSUE TITLE
getting below error while creating binary for simple-json plugin using go command go build -o ./dist/simple-plugin_windows_amd64.exe 

### ISSUE THREAD

**Issue by atulyadav** [golang/go#37878]
### What operating system and processor architecture are you using (`go env`)? WIndows 10

![image](https://user-images.githubusercontent.com/1940584/76749147-0be2d780-67a2-11ea-8cb5-1370d05bd437.png)

**Comment by cagedmantis** [comment]
Hi @atulyadav. This issue tracker is for problems with the Go tools and standard library. Perhaps the issue tracker for the package you are using may be more useful: https://github.com/grafana/simple-json-backend-datasource/issues
