### ISSUE TITLE
cmd/compile: sporadic memory corruption on 386 (32-bit) builders

### ISSUE THREAD

**Issue by bcmills** [golang/go#37881]
Various `sweep increased allocation count` errors have started cropping up in or near `go/build` invocations in various `go` commands.

[2020-03-15T08:13:55-32dbccd/linux-386-clang](https://build.golang.org/log/d1a42f1618c479c0cbf7b721f458aac8806d06d4)
[2020-03-14T07:03:15-d774d97/linux-386-sid](https://build.golang.org/log/d1d5fc7d70be5472f1681f7579f2450afcfa229e)
[2020-03-16T20:59:27-ff1eb42/linux-386-387](https://build.golang.org/log/af84c9e3f3fd8b3d1c3598dda2b38786d86318a9)
[2020-03-15T08:13:55-32dbccd/linux-386-clang](https://build.golang.org/log/d1a42f1618c479c0cbf7b721f458aac8806d06d4)
[2020-03-14T07:03:15-d774d97/linux-386-sid](https://build.golang.org/log/d1d5fc7d70be5472f1681f7579f2450afcfa229e)
[2020-03-13T20:43:12-e2a9ea0/openbsd-386-62](https://build.golang.org/log/8ecd5c6af8dea7a0b0a5ab78e169da80331d9d23)

Since `go/build` is involved, this may be related to the `go/types` crash cluster (#37602, #37507, #37690).

CC @griesemer @matloob @aclements @danscales @mknyszek @cherrymui

**Comment by bcmills** [comment]
These `found bad pointer in Go heap` errors seem to fit the same root cause:

[2020-03-16T22:31:39-2fbca94/linux-386-sid](https://build.golang.org/log/5e0e65dc455119f07f82ad7c497ed1e90957c8ca)
[2020-03-13T19:43:47-cbcb031/openbsd-386-62](https://build.golang.org/log/789a8908e3b13a05a0ee5891e66272f46b5ce3d5)

**Comment by bcmills** [comment]
This appears to be a dramatic uptick in memory corruption across the board on the 32-bit builders.

Given that it is only appearing on the 32-bit builders, and that we have not (to my knowledge) made any particularly racy or dangerous changes in `cmd/go` this cycle, marking as release-blocker for Go 1.15.

**Comment by bcmills** [comment]
I also can't rule out a compiler bug as the cause, given the number of changes to the rewrite rules so far. (CC @josharian @randall77)

**Comment by bcmills** [comment]
The first failure in this cluster was the same day that [CL 222782](https://golang.org/cl/222782) (#36468) was merged, so I suspect that may be related.

**Comment by bcmills** [comment]
Note that some of the affected builders are also TryBots:
https://go-review.googlesource.com/c/go/+/223745/5#message-7c0b4f426d49ae03a1ec88007cf714c5134d4800

**Comment by ianlancetaylor** [comment]
https://storage.googleapis.com/go-build-log/a19069d2/linux-386_272d029f.log

**Comment by jayconrod** [comment]
https://storage.googleapis.com/go-build-log/29e1c579/linux-386_8cf5204b.log

**Comment by randall77** [comment]
I'm kinda stumped on this one. I've tried to reproduce to no avail, and pouring over CL 222782 doesn't reveal anything that might cause intermittent issues like this.

On a possibly related note, I just mailed [a change](https://go-review.googlesource.com/c/go/+/224219) to add more addressing mode modifications for amd64. When that goes in, whether or not we start seeing this on amd64 will be illuminating.

**Comment by ianlancetaylor** [comment]
https://storage.googleapis.com/go-build-log/21f151d5/windows-386-2008_10977dff.log

**Comment by griesemer** [comment]
I have not followed this much and I am shooting from the hip here, but perhaps rolling back the rewrite rule changes  just to rule them out might be helpful (and then role them back in, selectively). That would be cheap in terms of man-power.

**Comment by mknyszek** [comment]
I think this is another example? This time in a trybot. https://storage.googleapis.com/go-build-log/899dcded/linux-386_238c26dc.log

**Comment by rasky** [comment]
New failure today, so I think CL224457 has not fixed it:
https://storage.googleapis.com/go-build-log/1437e11f/windows-386-2008_f0315367.log

**Comment by randall77** [comment]
Looks like that last CL didn't help - there was still a failure:
https://build.golang.org/log/91e3e48c8707daaafebec715e68ffea4d1e2adec
(freebsd 12_0 386)
Time to remove some more of that CL.

**Comment by randall77** [comment]
I might have figured out what is wrong. Read the description of the CL above for all the gory details.
I'm not 100% sure, but enough so to try and submit this again and see what happens (I still can't reproduce outside trybots).

**Comment by bcmills** [comment]
Unfortunately, https://build.golang.org/log/b634dbda2b877a9859e65cd5eba87577e9e33dee looks like it may be another instance of this failure after the most recent attempt.

```
freebsd-386-12_0 at 9ceb1e5f5caca5666f9db50864c45ca1f88da1df
…

##### ../misc/reboot
Building Go cmd/dist using /tmp/workdir/go. (devel 9ceb1e5f5caca5666f9db50864c45ca1f88da1df freebsd/386)
Building Go toolchain1 using /tmp/workdir/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for freebsd/386.
# crypto/tls
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x862b4c0]

goroutine 38 [running]:
cmd/compile/internal/gc.buildssa(0x0, 0x2, 0x0)
	/tmp/workdir/tmp/reboot-goroot082852438/src/cmd/compile/internal/gc/ssa.go:297 +0xb0
cmd/compile/internal/gc.compileSSA(0x0, 0x2)
	/tmp/workdir/tmp/reboot-goroot082852438/src/cmd/compile/internal/gc/pgen.go:296 +0x4c
cmd/compile/internal/gc.compileFunctions.func2(0x3a59ccc0, 0x39016c70, 0x2)
	/tmp/workdir/tmp/reboot-goroot082852438/src/cmd/compile/internal/gc/pgen.go:361 +0x35
created by cmd/compile/internal/gc.compileFunctions
	/tmp/workdir/tmp/reboot-goroot082852438/src/cmd/compile/internal/gc/pgen.go:359 +0xf7
go tool dist: FAILED: /tmp/workdir/tmp/reboot-goroot082852438/pkg/tool/freebsd_386/go_bootstrap install -gcflags=all= -ldflags=all= std cmd: exit status 2
--- FAIL: TestRepeatBootstrap (98.43s)
    reboot_test.go:50: exit status 2
```

**Comment by cherrymui** [comment]
This looks somewhat different. The original failure looks like the GC found (temporary) bad pointers. The new one is a segfault.

**Comment by randall77** [comment]
I'm going to declare this fixed. The original CL with fixed rules is in, both for 386 and amd64.
I'm not seeing any similar failures on the dashboard since the fixes went in.
