### ISSUE TITLE
runtime: Is it necessary to use atomic.Loaduintptr on gp.stackguard0?

### ISSUE THREAD

**Issue by Jerome-Tan** [golang/go#37880]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
It's not an issue, just curiosity.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Reading the source code of runtime.

### What did you expect to see?
Read/write operation on `gp.stackguard0` does not require any atomic operations.

### What did you see instead?
Atomic operations on` gp.stackguard0` are used in only one place: runtime/stack.go.

```go
func newstack() {
    ... ...
    // NOTE: stackguard0 may change underfoot, if another thread
    // is about to try to preempt gp. Read it just once and use that same
    // value now and below.
    preempt := atomic.Loaduintptr(&gp.stackguard0) == stackPreempt
    ... ...
}
```
If there is a data race, why not all use atomic operations?

**Comment by cagedmantis** [comment]
For asking questions about learning the language, see one of our forums: https://golang.org/wiki/Questions. We only use this issue tracker for tracking bugs. People in the forums can explain what is happening here.
