### ISSUE TITLE
 struct field tag `xml:"id,attr""` not compatible with reflect.StructTag.Get: key:"value" pairs not separated by spaces

### ISSUE THREAD

**Issue by Auenc** [golang/go#37887]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go1.14 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\USER\AppData\Local\go-build
set GOENV=C:\Users\USER\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\USER\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Go\src\flow-to-code\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\USER\AppData\Local\Temp\go-build139608754=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
Used XML reflect on struct without space separated attributes 

```
type Root struct {
	XMLName xml.Name `xml:"root"`
	ID      string   `xml:"id,attr""`
	MxCells []MxCell `xml:"mxCell"`
}
``` 

### What did you expect to see?
No error. Linux and mac work as expected, windows does not.

### What did you see instead?
Error: 
``` struct field tag `xml:"id,attr""` not compatible with reflect.StructTag.Get: key:"value" pairs not separated by spaces```

**Comment by ianlancetaylor** [comment]
This error message, which is from `go vet` or `go test`, should not vary based on operating system.

The error is correct: you have a double `"` in the tag for `ID`.

**Comment by Auenc** [comment]
But it doesn't error on Linux or Mac with the same code base and same environment? So it does have a different error based on operating system?

**Comment by ianlancetaylor** [comment]
No, as I said, the error should not depend on the operating system.

If you are certain that you are running the exact same version of Go on different operating systems, and that you are using identical input files, please show us exact and complete reproduction instructions.  Thanks.

**Comment by Auenc** [comment]
I'll edit my post tomorrow to show the same example. If I'm unable to prove exactly, I could potentially show that fresh installs on Windows/Mac/Linux have this behaviour. 

What I can say in the mean time is that it seams that Linux/Mac seem to be automatically escaping the additional quote, whereas windows isn't. Part of me is worried this might be down to OS internals and we might not be able to catch the difference; although, I don't know why this would be.
