### ISSUE TITLE
x/pkgsite: clicking a link to an anchor for an example does not show the example

### ISSUE THREAD

**Issue by dcormier** [golang/go#37884]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/aws/aws-sdk-go/service/dynamodb/expression?tab=doc#pkg-examples
 
### What is your user agent?

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:73.0) Gecko/20100101 Firefox/73.0`

### Screenshot

Clicking this link (bottom of image):

<img width="919" alt="image" src="https://user-images.githubusercontent.com/216265/76774047-c90d0980-6779-11ea-8bd4-a40f031a81e9.png">

Results in the browser going here:

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/216265/76774099-e0e48d80-6779-11ea-9b18-b3f782f64fda.png">
 
### What did you do?

I clicked a link in the `Examples` section.
 
### What did you expect to see?
 
The example I clicked.
 
### What did you see instead?

I saw the page just below the anchor for the example, with the anchor itself hidden by the page navigation header and not visible at all.

**Comment by julieqiu** [comment]
This issue seems to be related to #37520. Also related - #37819.

**Comment by julieqiu** [comment]
This fix is now live on pkg.go.dev.
