### ISSUE TITLE
reflect: potential change required in DeepEqual

### ISSUE THREAD

**Issue by obourdon** [golang/go#37897]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/XXX/Library/Caches/go-build"
GOENV="/Users/XXX/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/XXX/.gvm/pkgsets/go1.13.7/global"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/XXX/.gvm/gos/go1.13.7"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/XXX/.gvm/gos/go1.13.7/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/XXX/Documents/WORK/SquareScale/HASHICORP/terraform-provider-aws/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/k0/35x3347j4s18t_h4z932f3nr0000gn/T/go-build598493337=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

[See issue # 11059 in Terraform AWS Provider](https://github.com/terraform-providers/terraform-provider-aws/issues/11059)

and more specifically [this part](https://github.com/terraform-providers/terraform-provider-aws/issues/11059#issuecomment-599631533)

DeepEqual fails because of the following item which is however perfectly identical in both cases:

```
 F: (schema.SchemaSetFunc) 0x4ec7530,
```

### What did you expect to see?

If pointer addresses are identical `true` should be returned so something like:
```
	case Func:
		if v1.IsNil() && v2.IsNil() {
			return true
		}
		// Can't do better than this:
		return v1 == v2
```
might be better (IMHO)

### What did you see instead?

DeepEqual returns false

**Comment by obourdon** [comment]
After reading a bit more about function comparison, which does not seem very obvious, may be we could just parameterize the DeepEqual call so that this check can be disabled ? Just wondering ...

**Comment by bcmills** [comment]
Per https://golang.org/ref/spec#Comparison_operators:
> Slice, map, and function values are not comparable. However, as a special case, a slice, map, or function value may be compared to the predeclared identifier `nil`.

And per the `reflect.DeepEqual` documentation:
> Func values are deeply equal if both are nil; otherwise they are not deeply equal.

Any change to that behavior would violate the [Go 1 compatibility policy](https://golang.org/doc/go1compat).

**Comment by ianlancetaylor** [comment]
Sorry, we aren't going to make this change in `reflect.DeepEqual`.  There are many possible ways of doing equality comparisons.  `DeepEqual` is one of them.  Many people find it useful, but there are many possible variants.  We don't want to try to provide all those variants.  You can use `DeepEqual` as a template for your own equality function.

**Comment by obourdon** [comment]
@ianlancetaylor @bcmills many thanks for this feedback, I fully understand.Many thanks again
