### ISSUE TITLE
Unexpected result from filepath.Dir

### ISSUE THREAD

**Issue by jeroenrinzema** [golang/go#37890]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jeroen/Library/Caches/go-build"
GOENV="/Users/jeroen/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jeroen/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jeroen/Documents/github.com/jexia/maestro/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kq/7dj9_9jn4ks2r3q9dj8ryvsw0000gn/T/go-build352828235=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

filepath.Dir is returning a unexpected result when [providing a path containing a pattern](https://play.golang.org/p/QVCMVtKVYIm). `./**/*.txt` is provided but `**` is returned while `./` is expected.

```go
package main

import (
	"fmt"
	"path/filepath"
)

func main() {
	dir := filepath.Dir("./**/*.txt")
	fmt.Println(dir)
}
```

### What did you expect to see?
`filepath.Dir("./**/*.txt)` should return `./` instead of `**`.

### What did you see instead?
`filepath.Dir("./**/*.txt)` returned `**` instead.

**Comment by ianlancetaylor** [comment]
Thanks for the bug report, but this is working as documented and intended.  `filepath.Dir` is intended for use for real path names, not glob patterns.  In this case `filepath.Dir` drops the last path component, leaving `"./**"`, and then passes that to `filepath.Clean`, leaving `"**"`.
