### ISSUE TITLE
runtime: "sweep increased allocation count" on windows-386

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#37909]
https://storage.googleapis.com/go-build-log/2690739d/windows-386-2008_44cddfd5.log from https://go-review.googlesource.com/c/go/+/223754/1#message-76dbd38ce7b6e38b8fa2bcbbb2a0a919f5120d42

```
go build slices.go failed: exit status 2
Output:
runtime: nelems=512 nalloc=7 previous allocCount=6 nfreed=65535
fatal error: sweep increased allocation count
```

**Comment by randall77** [comment]
Dup of #37881 .
