### ISSUE TITLE
go build suddenly does not produce command executable

### ISSUE THREAD

**Issue by charles-dexter-ward** [golang/go#37904]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\a.mondati\AppData\Local\go-build
set GOENV=C:\Users\a.mondati\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\a.mondati\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\a.mondati\PROGETTI\golang\gitlabpendingbranches\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ABE77~1.MON\AppData\Local\Temp\go-build192886646=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
Building a command (package main).
It seems related to imported packages. But nothing has changed between yesterday and today.
No errors is given during build process.
If all the packages are removed (and removing the dependent code) than the executable is built.
Cross compiling for other architectures works.

### What did you expect to see?
The built executable

### What did you see instead?
The executable seems generated but it's immediately deleted.

**Comment by davecheney** [comment]
Is you AV software quarantining or deleting the final binary?

**Comment by charles-dexter-ward** [comment]
I checked and it did not seem the AV was the guilty.
However, today it works again, after a complete reboot (yesterday there was no way). :|

It's a mistery.  Maybe the issue can be considered as solved. But the cause is unknown.

**Comment by bcmills** [comment]
Given that rebooting fixed it, this seems unlikely to be due to a bug in `go build`, so closing. (We don't retain any long-running state beyond what is stored in the filesystem.)

**Comment by charles-dexter-ward** [comment]
The only other strange thing I noticed is that the VSCode Go plugin reported "Analysis tools missing" and even confirming the installation some of them were not installed (golint, gocode-gomod, go-outline, goimports, in particular).
Now it works again.
