### ISSUE TITLE
net/http: request canceled (Client.Timeout exceeded while reading body)

### ISSUE THREAD

**Issue by xiejunshi** [golang/go#37916]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.13.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

no

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/tools/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/tools/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build380477337=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/GitRj9yIY8j
The file stream returned from the server is about 30M. At the same time as io.copy, the disk io reaches 100%. The network environment is as follows
![image](https://user-images.githubusercontent.com/37329665/76942795-4a5eca80-6939-11ea-965e-a84d6ac88a5e.png)

### What did you expect to see?
I want to know why the error is returned and then how to circumvent the error

### What did you see instead?
The error code of line 51 is printed as follows:
net/http: request canceled (Client.Timeout exceeded while reading body)

**Comment by fraenkel** [comment]
You set a 30s timeout on the client.

**Comment by xiejunshi** [comment]
> You set a 30s timeout on the client.

https://play.golang.org/p/R0zj8dkj4Qw
In my code, the testClient above is actually used. I have set the timeout equal to 30 seconds. Is it wrong?
