### ISSUE TITLE
x/pkgsite: add import / imported by counts

### ISSUE THREAD

**Issue by tooolbox** [golang/go#37912]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/CloudyKit/jet
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36 
 
### Screenshot
 
![imports](https://user-images.githubusercontent.com/4984708/76918995-d4992700-6884-11ea-8c59-d36ba1f9f0b2.png)
 
### What did you do?
 
Visited the page.
 
### What did you expect to see?
 
 ![godoc imports](https://user-images.githubusercontent.com/4984708/76919022-e7136080-6884-11ea-91ae-543cf90474ca.png)
 
### What did you see instead?

From the main Doc page, you can't see how many imports/imported-by the package has.

One of the useful things about the Godoc pages was at the bottom you could get an instant gauge of how popular or in-use the package was based on the "imported by" count.  You could also get an instant gauge of how-many-dependencies-am-i-committing-to-if-i-use-this-package based on the "imports" count.  Both of these pieces of data were visible on the page only by scrolling, and if you wanted to know the details you could click through the link.

My suggestion would be to include the count in the tab bar.  So, taking the above example, the tab bar entry for imports would say `Imports (20)` and the imported-by would say `Imported By (123)`.  Just to be clear, your tab bar would look like:

```
Doc | Overview | Subdirectories | Versions | Imports (20) | Imported By (123) | Licenses
```

I think that it's better to make the info available at a glance rather than now requiring more clicks to see the same thing.  Thanks!

-----------------------------------

*...Somewhat off the point but related is that, while the `Imported By` tab has counts on the page, the `Imports` tab is divided into `Imports` and `Standard Library Imports` with no counts next to them&mdash;at least for the package I chose as an example.  It would be good to have counts in there.*

**Comment by julieqiu** [comment]
Thanks for the detailed feedback! We're currently working with our UX team to add this info, along with addressing other design suggestions. I'll post on this issue once we have any updates.

/cc @fflewddur

**Comment by julieqiu** [comment]
This feature is now available on [beta.pkg.go.dev](https://beta.pkg.go.dev). See https://github.com/golang/go/issues/41585#issuecomment-718143563 for details.

Closing this issue for https://github.com/golang/go/issues/41586.
