### ISSUE TITLE
cmd/go: go mod tidy -v does not print information about modules removed from go.sum

### ISSUE THREAD

**Issue by SunRunAway** [golang/go#37924]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```
go help mod tidy

usage: go mod tidy [-v]

Tidy makes sure go.mod matches the source code in the module.
It adds any missing modules necessary to build the current module's
packages and dependencies, and it removes unused modules that
don't provide any relevant packages. It also adds any missing entries
to go.sum and removes any unnecessary ones.

The -v flag causes tidy to print information about removed modules
to standard error.

```

```
go mod tidy -v
echo $?
```

### What did you expect to see?

Print information about removed modules as the documentation says

### What did you see instead?

no information printed.

**Comment by bcmills** [comment]
Duplicate of #33284

**Comment by bcmills** [comment]
Actually, maybe not. What information did you expect it to print?

Ideally, please provide a code sample, such as a reference to a specific repository and commit, for which `go mod tidy` removes modules from the dependency graph (as reported by `go mod graph`) but does not print that those modules have been removed.

**Comment by SunRunAway** [comment]
Hi, @bcmills 
Thanks for your reply. Sorry for the lack of information.
Normally when I use `go mod tidy -v`, it will print the unused package.

For example, this repository (https://github.com/SunRunAway/testgomod) works normally.
```
[sunrunaway:/tmp/testgomod]$ go mod tidy -v
unused go.uber.org/atomic
```


But in this repository (https://github.com/SunRunAway/tidb/tree/964f9baa063c5ce282dfeee60678762e0bdc4c46), 

When I run `go mod tidy -v`, it prints nothing but actually removed two line in the `go.sum` file.
```
[sunrunaway:...src/github.com/pingcap/tidb]$ git checkout 964f9baa063c5ce282dfeee60678762e0bdc4c46                                                   (964f9baa0) 
HEAD is now at 964f9baa0 build: `make tidy` should reports error
[sunrunaway:...src/github.com/pingcap/tidb]$ git status -s                                                                                           (964f9baa0) 
[sunrunaway:...src/github.com/pingcap/tidb]$ go mod tidy -v                                                                                          (964f9baa0) 
[sunrunaway:...src/github.com/pingcap/tidb]$ git status -s                                                                                          (964f9baa0✱) 
 M go.sum
```

**Comment by bcmills** [comment]
`go.sum` entries are checksums, not dependencies. (Dependencies are listed in the `go.mod` file and in the `go.mod` files of the module versions listed therein.)

`go mod tidy` only prints information about dependencies removed from the `go.mod` graph, not the `go.sum` file.

**Comment by bcmills** [comment]
As far as I can tell this is working as documented, but please let us know if you have additional detail that may indicate a bug.

**Comment by SunRunAway** [comment]
Thank you for your patient explanation. Sorry for bothering you.
Have no other questions.
