### ISSUE TITLE
x/tools/go/analysis: warn on Printf(fmt)

### ISSUE THREAD

**Issue by neild** [golang/go#37935]
Consider the code:

```go
msg := fmt.Sprintf("could not adumbrate %v: %v", subject, err)
log.Printf(msg)
return msg
```

The `log.Printf` call will interpret `msg` as a format string, causing unexpected results if `msg` contains formatting characters.

We could warn on a call to a formatting function with a single non-constant parameter. These calls can always be safely converted to the equivalent non-formatting function.

```go
msg := "some string"
fmt.Printf(msg) // warning: printf with non-constant format string and no format parameters

x := "parameter"
fmt.Printf(msg, x) // no warning: we can't validate that msg is a valid format, but this could be correct

var a []interface{}
fmt.Printf(msg, a...) // no warning: again, we can't validate that msg is a valid format, but this could be correct
```

**Comment by matloob** [comment]
I wouldn't mind accepting a contribution that adds this check, especially because it seems pretty simple to add.

**Comment by seankhliao** [comment]
I think this is no longer relevant now that vet warn on "non-constant format string in call to log.Printf"
