### ISSUE TITLE
x/tools/internal/lsp/cache: improve method of getting end positions for errors

### ISSUE THREAD

**Issue by ridersofrohan** [golang/go#37936]
When we calculate end positions for errors that originate from go/packages. We do some kind of syntax analysis, but some issues arise when adding new characters to the list in [internal/lsp/cache/errors.go#L208](https://github.com/golang/tools/blob/ba25ddc8556632eb7465fa8a7b297d3698b18821/internal/lsp/cache/errors.go#L208)

```go
if width := bytes.IndexAny(data[offset:], " \n,():;[]"); width > 0 {
	return ...
}
```

Take the sample program below:

```
__ main.go __
package main

import "golang.org/whatever"

func main() {
    if y/2 == 10 { return }
}
```
We will have two errors: (1) "undeclared name: y" and (2) "could not import golang.org/whatever (no package for import golang.org/whatever)".

In the current state, the diagnostic for error 1 will be on "y+2" and the diagnostic for error 2 will be on "golang.org/whatever".

Now, the diagnostic for error 1 should only underline "y" since that is the undeclared name, to fix this I could add "/" to the character list in [internal/lsp/cache/errors.go#L208](https://github.com/golang/tools/blob/ba25ddc8556632eb7465fa8a7b297d3698b18821/internal/lsp/cache/errors.go#L208) but then the diagnostic on error 2 would now underline "golang.org" rather than "golang.org/whatever".

I think gopls needs a better way to compute the end positions for type errors.

**Comment by stamblerre** [comment]
Superseded by https://github.com/golang/go/issues/42290.
