### ISSUE TITLE
x/build: create builder that runs with GOEXPERIMENT set to 'staticlockranking' (once lock ranking change is in)

### ISSUE THREAD

**Issue by danscales** [golang/go#37937]
Once my changes https://go-review.googlesource.com/c/go/+/222925 (enable build tag corresponding to `GOEXPERIMENT` value) and https://go-review.googlesource.com/c/go/+/207619 (enforce static lock ranking in the runtime when `GOEXPERIMENT` enabled) are checked in, we will want to enable a builder (probably just for linux/amd64) that runs with `GOEXPERIMENT` equal to `staticlockranking`.

This will not only test that the lock ranking is not being violated in the runtime (hence helping to avoid deadlocks related to lock acquisition ordering), but will also test that the buildtags are correctly set for a different `GOEXPERIMENT` value.

**Comment by dmitshur** [comment]
@danscales Do you think just a post-submit builder (not a part of the default trybot set) is sufficient, or do you think including this builder in trybots would be helpful too?

**Comment by danscales** [comment]
Yes, I think a post-submit builder will be fine.  This static lock ranking will only affect people who do fairly significant changes to the Go runtime, and those folks will hopefully also know when it will be useful to run the static lock ranking checks before checkin (because they changed the way certain runtime locks are used).

**Comment by dmitshur** [comment]
I see. For those CLs, it'll be possible to run the new builder via [SlowBots](https://golang.org/wiki/SlowBots) by asking for that builder specifically with something like `TRY=linux-amd64-staticlockranking`.

I understand it should test only the main Go repository. Let me know if think it would be helpful to test some/many/all golang.org/x repos as well.

**Comment by danscales** [comment]
> I see. For those CLs, it'll be possible to run the new builder via [SlowBots](https://golang.org/wiki/SlowBots) by asking for that builder specifically with something like `TRY=linux-amd64-staticlockranking`.
> 
> I understand it should test only the main Go repository. Let me know if think it would be helpful to test some/many/all golang.org/x repos as well.

No, there will be no need to run such a builder for any other repo other than the main Go repo.

Thanks for figuring out the necessary builder work!

I hope to get my first change (222925) submitted today or tomorrow, and then it may be a few more days before I get the full 'static lock ranking' change (207619) submitted.

**Comment by dmitshur** [comment]
Sounds good.

Thinking about it more, it should be useful to get the builder up and running starting with the latest existing commit on master, and ensure it's passing. Then, when you're ready to land your changes, you can use the builder via SlowBot (to confirm everything is working as expected, your changes and the builder).

I'll update the CL to remove the DNS.

**Comment by dmitshur** [comment]
[CL 224078](https://golang.org/cl/224078) is deployed now, and the linux-amd64-staticlockranking builder has started running. It is currently failing, as expected, because the experiment hasn't landed yet:

```
unknown experiment staticlockranking
```

_(Source: https://build.golang.org/log/afcc33b62c57fa7eee7a3807a81d081a8c9eff28)_

@danscales Please feel free to test your change with the new builder via [SlowBots](https://golang.org/cl/SlowBots) when it's ready, and let me know if anything more needs to be adjusted on the side of the builder.

/cc @andybons

**Comment by danscales** [comment]
OK, thank you for doing all this, @dmitshur .  Will let you know how it goes with the SlowBots when I'm ready.
