### ISSUE TITLE
x/crypto/ssh: AES256-CBC isn't supported for passphrase-protected OpenSSH keys

### ISSUE THREAD

**Issue by RKinsey** [golang/go#37939]
Someone over in @FiloSottile's age repo filed an issue a couple weeks ago (FiloSottile/age#100) because age reported an error on an older Ed25519 SSH key. Until v7.6 in 2017, OpenSSH used AES256-CBC as its default for password protected keys, and many of those keys are still in use.  
   
~~The easiest demonstration is to use [age](https://github.com/FiloSottile/age) and these keys: [ed25519_pass.zip](https://github.com/golang/go/files/4351442/ed25519_pass.zip)  
Run
`age -r ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDne4/teO42zTDdjNwxUMNpbfmp/dxgU4ZNkC3ydgcug -o out.age [file of your choice]`  
then   
`age -d -i /path/to/private/key /path/to/out.age`  
The passphrase is `password`~~  

~~It should report something like `Error: failed to decrypt SSH key file: ssh: unknown cipher "aes256-cbc", only supports "aes256-ctr"` along with some age-specific boilerplate.~~
Edit: A playground is even better: https://play.golang.org/p/IUdSKrVgMpT  

This happens because x/crypto/ssh only checks for CTR-mode AES in [crypto/ssh/keys.go#L1249-L1251](https://github.com/golang/crypto/blob/1b76d66859c6111b3d5c3ea6600ea44dc188bf12/ssh/keys.go#L1249-L1251). The error isn't triggered with RSA keys generated by the same OpenSSH version, as they're labeled RSA PRIVATE KEY rather than OPENSSH PRIVATE KEY.  

I'm partway through a fix, but I want to make sure that this wasn't an intentional move to discourage using older keys before I put too much effort into it.

**Comment by FiloSottile** [comment]
We are not going to support creating keys with that algorithm, but unless
it's particularly complex or broken we should probably support reading
them. I assume OpenSSH still supports them?

>

**Comment by martinseener** [comment]
@FiloSottile i'm still using them with OpenSSH daily (on macOS 10.5.3 and Linux Mint 19.3/Ubuntu 18.04).
