### ISSUE TITLE
The issue with variable scope

### ISSUE THREAD

**Issue by mrjazz** [golang/go#37947]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
go version go1.13.8 linux/amd6
</pre>

Was reproduced for both

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/denis/.cache/go-build"
GOENV="/home/denis/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/denis/go/rental_car_golang_migrator"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/denis/.go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/denis/.go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build624672185=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```
package main

import (
	"context"
	"fmt"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)


func findAllValues() chan bson.M {
	connStr := "mongodb://localhost:27018"
	var mongoClient, _ = mongo.Connect(context.TODO(), options.Client().ApplyURI(connStr))

	items := mongoClient.Database("example").Collection("values")
	cursor, _ := items.Find(context.TODO(), bson.M{})

	channel := make(chan bson.M)
	go func() {
		var value bson.M
		for cursor.Next(context.TODO()) {
			cursor.Decode(&value)
			channel <- value
		}
		close(channel)
	}()

	return channel
}

func main() {
	chnlWithRecords := findAllValues()
	for i := range chnlWithRecords {
		fmt.Println(i)
	}
}

Output:
map[_id:ObjectID("5e6fb943a3e9c891fe1783fd") value:1]
map[_id:ObjectID("5e6fb943a3e9c891fe1783fd") value:1]
map[_id:ObjectID("5e6fb943a3e9c891fe1783ff") value:3]
map[_id:ObjectID("5e6fb943a3e9c891fe1783ff") value:3]
map[_id:ObjectID("5e6fb943a3e9c891fe178401") value:5]
map[_id:ObjectID("5e6fb943a3e9c891fe178401") value:5]
map[_id:ObjectID("5e6fb943a3e9c891fe178403") value:7]
map[_id:ObjectID("5e6fb943a3e9c891fe178403") value:7]

After moving value variable inside the loop:
channel := make(chan bson.M)
go func() {
	for cursor.Next(context.TODO()) {
		var value bson.M
		cursor.Decode(&value)
		channel <- value
	}
	close(channel)
}()

Then it works properly:

map[_id:ObjectID("5e6fb943a3e9c891fe1783fc") value:0]
map[_id:ObjectID("5e6fb943a3e9c891fe1783fd") value:1]
map[_id:ObjectID("5e6fb943a3e9c891fe1783fe") value:2]
map[_id:ObjectID("5e6fb943a3e9c891fe1783ff") value:3]
map[_id:ObjectID("5e6fb943a3e9c891fe178400") value:4]

============================================

Another way to reproduce the issue:

func findAllValues() chan bson.M {
	connStr := "mongodb://localhost:27018"
	var mongoClient, _ = mongo.Connect(context.TODO(), options.Client().ApplyURI(connStr))

	items := mongoClient.Database("example").Collection("values")
	cursor, _ := items.Find(context.TODO(), bson.M{})

	channel := make(chan bson.M)
	go func() {
		var value bson.M
		for cursor.Next(context.TODO()) {
			cursor.Decode(&value)
			value = bson.M{"value": "ok"}
			channel <- value
		}
		close(channel)
	}()
	return channel
}

Output will be:
map[_id:ObjectID("5e6fb943a3e9c891fe1783fd") value:1]
map[value:ok]
map[_id:ObjectID("5e6fb943a3e9c891fe1783ff") value:3]
map[value:ok]
map[_id:ObjectID("5e6fb943a3e9c891fe178401") value:5]
map[value:ok]
map[_id:ObjectID("5e6fb943a3e9c891fe178403") value:7]
map[value:ok]
map[_id:ObjectID("5e6fb943a3e9c891fe178405") value:9]

Reinitializing value inside the loop fix the issue

```

**Comment by bcmills** [comment]
Please fill out the complete issue template. What did you expect to see and why, and what did you see instead?

**Comment by mrjazz** [comment]
The code is working if you'll run it with any mongodb collection, but in fact, mongo driver seems isn't an issue here. 

Here is how it should work:
https://gist.github.com/mrjazz/cb0f2218ea7f223ddc2808436091ac39/b2929b210ac335f7c7e22d0ac24ce9a4fad98ecf

Here is the code that doesn't work properly:
https://gist.github.com/mrjazz/cb0f2218ea7f223ddc2808436091ac39/9d4ec897c778fad60c587dee64192c0c454fe223

Here is the small difference (moving the value variable into the loop scope):
https://gist.github.com/mrjazz/cb0f2218ea7f223ddc2808436091ac39/revisions

**Comment by bcmills** [comment]
This is a regular old aliasing bug. `bson.M` is a map type, and maps are reference-like. After you send `value` on the channel, the next `cursor.Decode` decodes into the same underlying map.

The race detector should report this (build and test with `-race`). Please let us know if it does not.

**Comment by mrjazz** [comment]
Yes, you are right. Flag -race helps detects it. What is the correct way to avoid such bugs? Thanks

**Comment by bcmills** [comment]
For a start, always test with the race detector whenever you write concurrent code.

(https://golang.org/doc/articles/race_detector.html has more detail.)

**Comment by bcmills** [comment]
Closing, since this seems to be working in line with the language spec and the race detector successfully reports the bug.

**Comment by mrjazz** [comment]
Thanks @bcmills
