### ISSUE TITLE
what does ## explicit mean?

### ISSUE THREAD

**Issue by StinkyLord123** [golang/go#37946]
### What version of Go are you using (`go version`)?
$ go version 1.14
<pre>
can anyone tell me what is the ## explicit for? i need to understand its effect on the modules.txt file

</pre>

### Does this issue reproduce with the latest release?
my project is breaking after trying to parse "modules.txt" file on go version 1.14 (works fine on go 1.13.5

### What operating system and processor architecture are you using (`go env`)?
windows 10

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\PhilipAbed\AppData\Local\go-build
set GOENV=C:\Users\PhilipAbed\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\PhilipAbed\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\PHILIP~1\AppData\Local\Temp\go-build988577882=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you expect to see?

a working parsing of the modules.txt

### What did you see instead?
modules.txt broke since there's an extra "## explicit"

**Comment by bcmills** [comment]
The `vendor/modules.txt` file format is not intended for other tools to consume.
(`go list` is the supported API for external tools to query dependency information: see https://golang.org/cmd/go/#hdr-List_packages_or_modules.)

The `## explicit` entries were added for #33848.
