### ISSUE TITLE
cmd/go: relax module consistency checks if vendor/modules.txt is missing

### ISSUE THREAD

**Issue by dmgk** [golang/go#37948]
Strong consistency checks in go1.14 and requirement that `vendor/modules.txt` must be present make it hard to package Go software (e.g. as FreeBSD ports).

Because network is not available during the port build, ports are built in `-mod=vendor` mode. All required dependencies are fetched beforehand and then unpacked into vendor directory simulating the result of `go mod vendor`, except that `vendor/modules.txt` is not present. If software's go.mod specifies `go.14`, missing `vendor/modules.txt` is a hard error (`... is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt`) and working around it requires patching go.mod back to `go1.13`

Proposed change relaxes module consistency checks and switches back to go1.13 behaviour if `vendor/modules.tx` is not present during the build.

**Comment by jayconrod** [comment]
Could you say more about why `go mod vendor` can't be used build the `vendor` directory? That's the only supported mechanism for building a `vendor` directory in module mode.

Also, why not build a `vendor/modules.txt` file that satisfies the consistency check? Information from that file is used in several commands, so it's important that it's present and accurate.

**Comment by dmgk** [comment]
@jayconrod Because network is not available during the build. The list of required dependencies is generated from `vendor/modules.txt` (after `go mod vendor`) and committed along with port and vendor dir contents is then reconstructed using that list. We don't keep `vendor/modules.txt` because (a) it wasn't required with go1.13 and (b) dependencies list is already consistent with go.mod by construction.

**Comment by jayconrod** [comment]
If you have a full copy of `vendor/modules.txt` at an earlier point in the build, why not keep that? It sounds like you're able to run `go mod vendor` at some point, so I don't understand why it needs to be rebuilt after that.

You may be able to construct the `vendor` directory using `go mod vendor` offline by adding `replace` directives to `go.mod`, or an alternative `go.mod` file specified with `-modfile`. A local `GOPROXY` implementation may also be an option.

I don't think we should disable the `vendor/modules.txt` consistency check though. It's important.

**Comment by yurivict** [comment]
Alternatively, you can add an option to go to wave the consistency check.

(A full copy of vendor/modules.txt is available at some point during the port maintainer update, but it's problematic to keep it into the build phase within the FreeBSD ports framework.)

**Comment by yurivict** [comment]
The design of Go assumes that network is available at all times during build, while during package build the network is not available for security reasons. The new consistency checking exacerbate this conflict, putting more and more burden on port developers/maintainers.

**Comment by bcmills** [comment]
The consistency check does not use the network, by design. It compares the lexical contents of the `go.mod` and `vendor/module.txt` files.

And note that `replace` directives also avoid the network. I would expect that in most packaging systems, a `replace` directive would express the intended substitution more clearly than a `vendor` tree.

**Comment by mvdan** [comment]
Closing old issues that still have the WaitingForInfo label where enough details to investigate weren't provided. Feel free to leave a comment with more details and we can reopen.
