### ISSUE TITLE
internal/poll: stop using dedicated threads on Windows

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#37956]
In the internal/poll package, on Windows, if the function `CancelIoEx` is not available on the system, we use dedicated threads for I/O so that requests can be canceled using the older `CancelIo` function.

According to https://docs.microsoft.com/en-us/windows/win32/fileio/cancelioex-func, `CancelIoEx` is available on Windows Vista, Windows Server 2008, and newer.

According to https://golang.org/wiki/MinimumRequirements, as of the Go 1.11 release we require at least Windows 7, or Windows 2008R2, or higher.

According to https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions, Windows 7 is newer than Windows Vista.

Therefore, I believe that all supported Windows systems support `CancelIoEx`, and we can remove the (rather complex) code that works using `CancelIo`.

@alexbrainman @mattn Do you agree?

**Comment by alexbrainman** [comment]
@ianlancetaylor I agree. We should remove all code that calls CancelIo, because it should not be needed now.

Do you want me to do the honors?

Alex

**Comment by ianlancetaylor** [comment]
I can do it, unless you would like to.  Thanks.
