### ISSUE TITLE
runtime: require GetQueuedCompletionStatusEx in Windows netpoll code

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#37957]
In the runtime package, on Windows, if the function `GetQueuedCompletionStatusEx` is not available on the system, we use the simpler but slower `GetQueuedCompletionStatus` function.

According to https://docs.microsoft.com/en-us/windows/win32/fileio/getqueuedcompletionstatusex-func, `GetQueuedCompletionStatusEx` is available on Windows Vista, Windows Server 2008, and newer.

According to https://golang.org/wiki/MinimumRequirements, as of the Go 1.11 release we require at least Windows 7, or Windows 2008R2, or higher.

According to https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions, Windows 7 is newer than Windows Vista.

Therefore, I believe that all supported Windows systems support `GetQueuedCompletionStatusEx`, and we can remove the code that uses `GetQueuedCompletionStatus`.

@alexbrainman @mattn Do you agree?

**Comment by alexbrainman** [comment]
@ianlancetaylor I agree. We can remove all code that calls GetQueuedCompletionStatus.

Do you want me to do the honors?

Alex

**Comment by ianlancetaylor** [comment]
(Same answer.)  I can do it, unless you would like to.  Thanks.

**Comment by mattn** [comment]
I agree with you
