### ISSUE TITLE
Can we have a built-in general-purpose glob matching?

### ISSUE THREAD

**Issue by hsluoyz** [golang/go#37964]
I'm from Casbin community. My user sent me a PR to add glob pattern matching support: https://github.com/casbin/casbin/pull/164. The glob pattern matching is done by a 3rd-party library: https://github.com/gobwas/glob . However, I don't want to bring another dependency. I think glob matching is very commonly-needed feature, so can we build it into Go built-in library like regex?

I noticed there's a `filepath.Glob()` here: https://golang.org/pkg/path/filepath/#Glob but it's only for matching file names. Can we broaden it to a general-purpose string matching? Thanks.

**Comment by ianlancetaylor** [comment]
We already have `filepath.Match` (https://golang.org/pkg/path/filepath/#Match).  That seems to me to be what you are suggesting.  Are you thinking of something different?

**Comment by hsluoyz** [comment]
@iamoryanmoshe thanks for your answer!

What's the difference between https://golang.org/pkg/path/filepath/#Match and https://golang.org/pkg/path/#Match except OS difference described in this post? https://stackoverflow.com/questions/50637904/what-is-the-difference-between-path-match-and-filepath-match

**Comment by mvdan** [comment]
> If I want to have a general-purpose glob matching that have the same behavior for all OSes, should I use `path.Match()` instead?

Yes. It doesn't seem like there's anything to do here, so I'm closing this issue.
