### ISSUE TITLE
runtime/pprof: panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by tonyghita** [golang/go#37967]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Build an application that is continuously capturing profiles with go1.14.1. Previously, this application was running 1.14 without issue.

### What did you expect to see?

No panics.

### What did you see instead?

Panic in `runtime/pprof.runtime_expandFinalInlineFrame` with the following stack trace
![image](https://user-images.githubusercontent.com/779738/77190248-25339e80-6a96-11ea-893e-fbb01c840322.png)

**Comment by tonyghita** [comment]
Perhaps related? https://github.com/golang/go/issues/37447

**Comment by randall77** [comment]
@hyangah

**Comment by randall77** [comment]
@gopherbot, please open a backport issue for 1.14.
