### ISSUE TITLE
incorrect compile error detected

### ISSUE THREAD

**Issue by latenite4** [golang/go#37979]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>
 go version
go version go1.13.8 linux/amd64

### Does this issue reproduce with the latest release?
latest release is 1.14.1 and it has **other/different compile errors on AMD64**
go version
go version go1.14.1 linux/amd64

**strange new errors with v1.14.1**
go build
 runtime/internal/atomic
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:18:6: Load redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:16:24
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:24:6: Loadp redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:22:32
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:30:6: Load64 redeclared in this block

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 18.04 and AMD x86

<details><summary><code>go env</code> Output</summary><br><pre>

</pre></details>
$ go env
go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN="/home/user01/go/bin"
GOCACHE="/home/user01/.cache/go-build"
GOENV="/home/user01/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user01/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build282016982=/tmp/go-build -gno-record-gcc-switches"

i do not have GOPATH set.

### What did you do?
go build
# globalinfo
./info1.go:194:6: alarmString declared and not used  **<< incorrect error message**
go run gets the same error

the compiler should see that alarmString (from line 194) is used on line 199 and 203. it does recognize that other vars are globally declared and used in 'if' block (refer to returnString string
	alarmFlag bool  lines 192,193). this is clearly a corner case where the compiler is declaring a wrong error.

pwd
/home/user01/go/src/globalinfo
user01@linux-system:~/go/src/globalinfo$ lsb_release -d
Description:	Ubuntu 18.04.4 LTS

![image](https://user-images.githubusercontent.com/1754972/77217331-a8cda980-6aef-11ea-990c-ec561da17717.png)

### What did you expect to see?

no compile error

### What did you see instead?
go build
# globalinfo
**./info1.go:194:6: alarmString declared and not used**
user01@linux-system:~/go/src/globalinfo$ 

the 2 go files can be cloned from https://github.com/latenite4/globalinfo.git

i looked at similar issues but they seemed to be different.

**Comment by latenite4** [comment]
when i 1st remove /usr/local/go and then went back and reinstalled 1.14.1 and then retried the build,
i see that v1.14.1 compiler detects that same wrong compile error. **so the problem still exists in v1.14.1**

Rod M

**Comment by latenite4** [comment]
problem still exists in v1.14.1.  i accidentally closed this issue.

**Comment by randall77** [comment]
This is intentional. This code:
```
func f(b bool) {
	var x int
	if b {
		x = 8
	} else {
		x = 9
	}
}
```
does not compile for the same reason. There are writes to `x`, but no reads from it. That's what the error is telling you.

It's hard to tell from your screenshot whether that is the case for `alarmString` as the whole function is not shown. But I suspect that's what is happening.

Adding a `_ = x` to `f` "fixes" the problem in the example above. Try that in your code and see what happens.
