### ISSUE TITLE
gob: encoding / decoding time results in slightly different values

### ISSUE THREAD

**Issue by adam-hanna** [golang/go#37986]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.13.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
?

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/vagrant/go/bin"
GOCACHE="/home/vagrant/.cache/go-build"
GOENV="/home/vagrant/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/vagrant/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/vagrant/.gvm/gos/go1.13.1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/vagrant/.gvm/gos/go1.13.1/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/vagrant/apps/dev-null/bitmex-market-maker/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build946903390=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

[Playground](https://play.golang.org/p/p82eCF1bwLj)

```go
package main

import (
	"bytes"
	"encoding/gob"
        "fmt"
	"log"
	"time"
)

// MarshalBinary marshals an interface into a bytes array
func MarshalBinary(msg interface{}) ([]byte, error) {
	var buff bytes.Buffer // Stand-in for the network.

	// Create an encoder and send a value.
	enc := gob.NewEncoder(&buff)
	if err := enc.Encode(&msg); err != nil {
		log.Printf("err marshalling msg: %v\n%v", msg, err)
		return nil, err
	}

	return buff.Bytes(), nil
}

// UnmarshalBinary unmarshals binary data into an interface
func UnmarshalBinary(b []byte) (interface{}, error) {
	buff := bytes.NewBuffer(b)
	// Create a decoder and receive a value.
	dec := gob.NewDecoder(buff)

	var msg interface{}
	if err := dec.Decode(&msg); err != nil {
		log.Printf("err decoding bytes:\n%v", err)
		return nil, err
	}

	return msg, nil
}

func main() {
	gob.Register(time.Time{})

	t1 := time.Now()

	b, err := MarshalBinary(t1)
	if err != nil {
		log.Fatalf("err marshaling:\n%v", err)
	}

	It, err := UnmarshalBinary(b)
	if err != nil {
		log.Fatalf("err unmarshaling:\n%v", err)
	}

	t2, _ := It.(time.Time)

	fmt.Printf("t1: %v\nt2: %v", t1, t2)
}
```

### What did you expect to see?
```bash
t1: 2009-11-10 23:00:00 +0000 UTC m=+0.000000001
t2: 2009-11-10 23:00:00 +0000 UTC m=+0.000000001
```

### What did you see instead?

```bash
t1: 2009-11-10 23:00:00 +0000 UTC m=+0.000000001
t2: 2009-11-10 23:00:00 +0000 UTC
```

**Comment by ianlancetaylor** [comment]
This is expected.  See the discussion of monotonic clocks at https://golang.org/pkg/time.  A time that passes through gob will not in general have a correct monotonic clock value, so the value is not preserved.
