### ISSUE TITLE
runtime: "pipe failed with -89" at program startup(mipsle only), timer related netpoll init.

### ISSUE THREAD

**Issue by xtaci** [golang/go#37997]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
mipsle
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?
proper startup 

### What did you see instead?
root@weiw-e4200:/opt/bin/a# ./client_linux_mipsle.0322 --help
NAME:
kcptun - client(with SMUX)

USAGE:
client_linux_mipsle.0322 [global options] command [command options] [arguments...]

VERSION:
20200322

COMMANDS:
help, h Shows a list of commands or help for one command

GLOBAL OPTIONS:
--localaddr value, -l value local listen address (default: ":12948")
--remoteaddr value, -r value kcp server address (default: "vps:29900")
--key value pre-shared secret between client and server (default: "it's a secrect") [$KCPTUN_KEY]
--crypt value aes, aes-128, aes-192, salsa20, blowfish, twofish, cast5, 3des, tea, xtea, xor, sm4, none (default: "aes")
--mode value profiles: fast3, fast2, fast, normal, manual (default: "fast")
--conn value

**runtime: pipe failed with -89**
**fatal error: runtime: pipe failed**

goroutine 6 [running]:
runtime.throw(0x40afd2, 0x14)
/usr/local/go/src/runtime/panic.go:1114 +0x60 fp=0xc285d0 sp=0xc285bc pc=0x4cd0c
runtime.netpollinit()
/usr/local/go/src/runtime/netpoll_epoll.go:40 +0x20c fp=0xc28608 sp=0xc285d0 pc=0x489a0
runtime.netpollGenericInit()
/usr/local/go/src/runtime/netpoll.go:112 +0xa0 fp=0xc28610 sp=0xc28608 pc=0x46cf4
runtime.doaddtimer(0xc1e000, 0xc3e884)
/usr/local/go/src/runtime/time.go:271 +0x1e8 fp=0xc2863c sp=0xc28610 pc=0x756a0
runtime.addInitializedTimer(0xc3e884)
/usr/local/go/src/runtime/time.go:258 +0x8c fp=0xc28658 sp=0xc2863c pc=0x75480
runtime.addtimer(0xc3e884)
/usr/local/go/src/runtime/time.go:248 +0x88 fp=0xc28664 sp=0xc28658 pc=0x753c4
time.startTimer(0xc3e884)
/usr/local/go/src/runtime/time.go:207 +0x3c fp=0xc2866c sp=0xc28664 pc=0x751c4
time.NewTimer(0x0, 0x0, 0x0)
/usr/local/go/src/time/sleep.go:93 +0xf8 fp=0xc28690 sp=0xc2866c pc=0xead00
github.com/xtaci/kcp-go/v5.(*TimedSched).sched(0xc48060)
/home/xtaci/go/pkg/mod/github.com/xtaci/kcp-go/v5@v5.5.11/timedsched.go:64 +0x5c fp=0xc287e4 sp=0xc28690 pc=0x225f28
runtime.goexit()
/usr/local/go/src/runtime/asm_mipsx.s:651 +0x4 fp=0xc287e4 sp=0xc287e4 pc=0x87d64
created by github.com/xtaci/kcp-go/v5.NewTimedSched
/home/xtaci/go/pkg/mod/github.com/xtaci/kcp-go/v5@v5.5.11/timedsched.go:56 +0x118

goroutine 1 [runnable]:
syscall.Syscall(0xfa4, 0x1, 0xc6c434, 0x5, 0x5, 0x2, 0x0)
/usr/local/go/src/syscall/asm_linux_mipsx.s:17 +0x10
syscall.write(0x1, 0xc6c434, 0x5, 0x8, 0x0, 0x0, 0x0)
/usr/local/go/src/syscall/zsyscall_linux_mipsle.go:914 +0x60
syscall.Write(...)
/usr/local/go/src/syscall/syscall_unix.go:214
internal/poll.(*FD).Write(0xc3e080, 0xc6c434, 0x5, 0x8, 0x0, 0x0, 0x0)
/usr/local/go/src/internal/poll/fd_unix.go:268 +0x174
os.(*File).write(...)
/usr/local/go/src/os/file_unix.go:280
os.(*File).Write(0xc0c0f8, 0xc6c434, 0x5, 0x8, 0x8, 0x0, 0x0)
/usr/local/go/src/os/file.go:153 +0x7c
text/tabwriter.(*Writer).write0(0xc6c420, 0xc6c434, 0x5, 0x8)
/usr/local/go/src/text/tabwriter/tabwriter.go:254 +0x60
text/tabwriter.(*Writer).writeN(0xc6c420, 0xc6c434, 0x8, 0x8, 0xd)
/usr/local/go/src/text/tabwriter/tabwriter.go:268 +0xac
text/tabwriter.(*Writer).writePadding(0xc6c420, 0xf, 0x24, 0x600)
/usr/local/go/src/text/tabwriter/tabwriter.go:293 +0x114
text/tabwriter.(*Writer).writeLines(0xc6c420, 0x0, 0x0, 0x1c, 0xcdcb00)
/usr/local/go/src/text/tabwriter/tabwriter.go:324 +0x30c
text/tabwriter.(*Writer).format(0xc6c420, 0x0, 0x0, 0x1c, 0x0)
/usr/local/go/src/text/tabwriter/tabwriter.go:409 +0x2ec
text/tabwriter.(*Writer).format(0xc6c420, 0x0, 0x0, 0x1d, 0xc53300)
/usr/local/go/src/text/tabwriter/tabwriter.go:403 +0x1f0
text/tabwriter.(*Writer).flushNoDefers(0xc6c420)
/usr/local/go/src/text/tabwriter/tabwriter.go:520 +0xe0
text/tabwriter.(*Writer).flush(0xc6c420, 0x0, 0x0)
/usr/local/go/src/text/tabwriter/tabwriter.go:502 +0x94
text/tabwriter.(*Writer).Flush(...)
/usr/local/go/src/text/tabwriter/tabwriter.go:495
github.com/urfave/cli.printHelpCustom(0x47fa10, 0xc0c0f8, 0x41a1cc, 0x41f, 0x3e4080, 0xc01340, 0x0)
/home/xtaci/go/pkg/mod/github.com/urfave/cli@v1.21.0/help.go:258 +0x3ac
github.com/urfave/cli.printHelp(0x47fa10, 0xc0c0f8, 0x41a1cc, 0x41f, 0x3e4080, 0xc01340)
/home/xtaci/go/pkg/mod/github.com/urfave/cli@v1.21.0/help.go:262 +0x68
github.com/urfave/cli.ShowAppHelp(0xc86210, 0xc86201, 0x40)
/home/xtaci/go/pkg/mod/github.com/urfave/cli@v1.21.0/help.go:143 +0x19c
github.com/urfave/cli.(*App).Run(0xc01340, 0xc0a040, 0x2, 0x2, 0x0, 0x0)
/home/xtaci/go/pkg/mod/github.com/urfave/cli@v1.21.0/app.go:222 +0x8e0
main.main()
/home/xtaci/go/src/github.com/xtaci/kcptun/client/main.go:457 +0x11dc

goroutine 7 [runnable]:
github.com/xtaci/kcp-go/v5.(*TimedSched).prepend(0xc48060)
/home/xtaci/go/pkg/mod/github.com/xtaci/kcp-go/v5@v5.5.11/timedsched.go:100
created by github.com/xtaci/kcp-go/v5.NewTimedSched
/home/xtaci/go/pkg/mod/github.com/xtaci/kcp-go/v5@v5.5.11/timedsched.go:58 +0x154

goroutine 8 [runnable]:
main.sigHandler()
/home/xtaci/go/src/github.com/xtaci/kcptun/client/signal.go:18
created by main.init.0
/home/xtaci/go/src/github.com/xtaci/kcptun/client/signal.go:15 +0x44

**Comment by ianlancetaylor** [comment]
Please include the actual `go env` output.  Thanks.

**Comment by ianlancetaylor** [comment]
What are the `GOARCH` and `GOOS` values that you use to build the failing binary?

**Comment by ianlancetaylor** [comment]
Looks like on MIPS errno value `89` is `ENOSYS`, so it looks like the problem is that this system does not have the `pipe2` system call.  The errno value is being returned as a positive number when the code expects a negative number.

**Comment by ianlancetaylor** [comment]
Can you see if https://golang.orgcl/224592 fixes the problem?  Thanks.

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport for 1.14.

This is a fatal crash with no workaround on mips systems running Linux kernels that do not support `pipe2`.

**Comment by xtaci** [comment]
the original issue, report by a mipsle user, https://github.com/xtaci/kcptun/issues/771

**Comment by xtaci** [comment]
> What are the `GOARCH` and `GOOS` values that you use to build the failing binary?

env CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOMIPS=softfloat  go build ...

**Comment by xtaci** [comment]
> Please include the actual `go env` output. Thanks.

 The building environtment, not the runtime environtment:
```
╰─$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xtaci/.cache/go-build"
GOENV="/home/xtaci/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xtaci/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/xtaci/go/src/github.com/xtaci/kcptun/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build179104364=/tmp/go-build -gno-record-gcc-switches"

╰─$ uname -a
Linux DESKTOP-7FL7RC4 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

╰─$ go version
go version go1.14.1 linux/amd64
```

**Comment by ianlancetaylor** [comment]
Any luck trying the patch above?  Thanks.

**Comment by xtaci** [comment]
I'll try that

**Comment by sryze** [comment]
I have the same problem when running a program cross-compiled for MIPS, my build command looks like this:

```
GOOS=linux GOARCH=mips go build
```

go version go1.15.2 windows/amd64

Full output:

```
runtime: pipe failed with -89
fatal error: runtime: pipe failed

goroutine 1 [running, locked to thread]:
runtime.throw(0x92e401, 0x14)
        c:/go/src/runtime/panic.go:1116 +0x60 fp=0x10b8d20 sp=0x10b8d0c pc=0x4d1a0
runtime.netpollinit()
        c:/go/src/runtime/netpoll_epoll.go:45 +0x20c fp=0x10b8d58 sp=0x10b8d20 pc=0x48e6c
runtime.netpollGenericInit()
        c:/go/src/runtime/netpoll.go:122 +0xac fp=0x10b8d60 sp=0x10b8d58 pc=0x48170
internal/poll.runtime_pollServerInit()
        c:/go/src/runtime/netpoll.go:114 +0x34 fp=0x10b8d64 sp=0x10b8d60 pc=0x830b4
sync.(*Once).doSlow(0xe876a0, 0x9579d0)
        c:/go/src/sync/once.go:66 +0x168 fp=0x10b8d90 sp=0x10b8d64 pc=0x92140
sync.(*Once).Do(...)
        c:/go/src/sync/once.go:57
internal/poll.(*pollDesc).init(0x10b0154, 0x10b0140, 0x109e100, 0x10b0140)
        c:/go/src/internal/poll/fd_poll_runtime.go:38 +0x190 fp=0x10b8da8 sp=0x10b8d90 pc=0xfe87c
internal/poll.(*FD).Init(0x10b0140, 0x9213a5, 0x4, 0x1000002, 0x0, 0x0)
        c:/go/src/internal/poll/fd_unix.go:62 +0xb0 fp=0x10b8dbc sp=0x10b8da8 pc=0xff7b8
os.newFile(0x3, 0x109e020, 0x12, 0x1, 0x0)
        c:/go/src/os/file_unix.go:155 +0x110 fp=0x10b8de4 sp=0x10b8dbc pc=0x10a9f0
os.openFileNolog(0x109e020, 0x12, 0x0, 0x0, 0xa03790, 0x4, 0x4)
        c:/go/src/os/file_unix.go:224 +0x1e4 fp=0x10b8e10 sp=0x10b8de4 pc=0x10acf0
os.OpenFile(0x109e020, 0x12, 0x0, 0x0, 0x18, 0x400, 0xc0)
        c:/go/src/os/file.go:327 +0x6c fp=0x10b8e30 sp=0x10b8e10 pc=0x1088b8
os.Open(...)
        c:/go/src/os/file.go:307
google.golang.org/protobuf/internal/detrand.binaryHash(0x0, 0x0)
        C:/Users/szx/AppData/Roaming/GoPackages/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/detrand/rand.go:38 +0x80 fp=0x10b8e88 sp=0x10b8e30 pc=0x330b8c
google.golang.org/protobuf/internal/detrand.init()
        C:/Users/szx/AppData/Roaming/GoPackages/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/detrand/rand.go:30 +0x34 fp=0x10b8e94 sp=0x10b8e88 pc=0x330f08
runtime.doInit(0xdb24e0)
        c:/go/src/runtime/proc.go:5625 +0xcc fp=0x10b8ea8 sp=0x10b8e94 pc=0x5fe6c
runtime.doInit(0xdb2520)
        c:/go/src/runtime/proc.go:5620 +0x80 fp=0x10b8ebc sp=0x10b8ea8 pc=0x5fe20
runtime.doInit(0xdb1a00)
        c:/go/src/runtime/proc.go:5620 +0x80 fp=0x10b8ed0 sp=0x10b8ebc pc=0x5fe20
runtime.doInit(0xdb2500)
        c:/go/src/runtime/proc.go:5620 +0x80 fp=0x10b8ee4 sp=0x10b8ed0 pc=0x5fe20
runtime.doInit(0xdb6860)
        c:/go/src/runtime/proc.go:5620 +0x80 fp=0x10b8ef8 sp=0x10b8ee4 pc=0x5fe20
runtime.doInit(0xdb7c40)
        c:/go/src/runtime/proc.go:5620 +0x80 fp=0x10b8f0c sp=0x10b8ef8 pc=0x5fe20
runtime.doInit(0xdb67a0)
        c:/go/src/runtime/proc.go:5620 +0x80 fp=0x10b8f20 sp=0x10b8f0c pc=0x5fe20
runtime.doInit(0xdb5ba0)
        c:/go/src/runtime/proc.go:5620 +0x80 fp=0x10b8f34 sp=0x10b8f20 pc=0x5fe20
runtime.doInit(0xdbab00)
        c:/go/src/runtime/proc.go:5620 +0x80 fp=0x10b8f48 sp=0x10b8f34 pc=0x5fe20
runtime.doInit(0xdb5920)
        c:/go/src/runtime/proc.go:5620 +0x80 fp=0x10b8f5c sp=0x10b8f48 pc=0x5fe20
runtime.doInit(0xdb4220)
        c:/go/src/runtime/proc.go:5620 +0x80 fp=0x10b8f70 sp=0x10b8f5c pc=0x5fe20
runtime.doInit(0xdb6d40)
        c:/go/src/runtime/proc.go:5620 +0x80 fp=0x10b8f84 sp=0x10b8f70 pc=0x5fe20
runtime.doInit(0xdb9180)
        c:/go/src/runtime/proc.go:5620 +0x80 fp=0x10b8f98 sp=0x10b8f84 pc=0x5fe20
runtime.doInit(0xdb65c0)
        c:/go/src/runtime/proc.go:5620 +0x80 fp=0x10b8fac sp=0x10b8f98 pc=0x5fe20
runtime.doInit(0xdb4620)
        c:/go/src/runtime/proc.go:5620 +0x80 fp=0x10b8fc0 sp=0x10b8fac pc=0x5fe20
runtime.main()
        c:/go/src/runtime/proc.go:191 +0x1f4 fp=0x10b8fec sp=0x10b8fc0 pc=0x505b8
runtime.goexit()
        c:/go/src/runtime/asm_mipsx.s:651 +0x4 fp=0x10b8fec sp=0x10b8fec pc=0x88a44
```

**Comment by ianlancetaylor** [comment]
@sryze This bug is closed and we believe that it is fixed.  You may be encountering a different problem with the same symptoms. 
 Please open a new issue with full details about how to recreate the problem.  Thanks.
