### ISSUE TITLE
regexp: behavior on invalid UTF-8 input is undocumented and inconsistent

### ISSUE THREAD

**Issue by abacabadabacaba** [golang/go#38006]
<pre>
$ go version
go version go1.14.1 linux/amd64
</pre>

The [documentation](https://golang.org/pkg/regexp/) for regexp package says that "All characters are UTF-8-encoded code points". However, it doesn't say anything about what happens if the input is not valid UTF-8.

The current behavior on invalid UTF-8 is not consistent. For example, when matching against the string `"\xff"`, the pattern `a` doesn't match, the pattern `\x{fffd}` doesn't match either, but the pattern `a|\x{fffd}` surprisingly does match.

The documentation should be updated to specify the behavior of regexp package on invalid UTF-8 input. Also, the behavior should be made more consistent (for example, always convert every undecodeable byte into `\ufffd`).

**Comment by andig** [comment]
Different issue but similar context: it would also be interesting to use regexes with "binary" patterns irrespective of utf8 code points. Seems this is not supported at all (while it is in python).

**Comment by davecheney** [comment]
@andig please open a new issue for binary regex. Thank you.
