### ISSUE TITLE
syscall/js: copyBytesTo(Go|JS) could accept Uint8ClampedArray

### ISSUE THREAD

**Issue by aurium** [golang/go#38011]
syscall/js: copyBytesTo(Go|JS) could accept Uint8ClampedArray

When compiling Go to WebAssembly (with go 1.13) you can get a great help from `syscall/js` to interact with JS and web APIs.

One limitation is in reading and updating canvas pixel data with `(get|put)ImageData`, because we need an intermediary translation between `Uint8ClampedArray` and `Uint8Array`. Oderwise `CopyBytesToGo` panics, also we can't use a `ImageData` like object with `Uint8Array` data, or the `putImageData` will fail.

However, `Uint8ClampedArray` is just a sugary `Uint8Array`. I see no problem to make `copyBytesTo(Go|JS)` accepts that as a source or destiny.

### What did you do?

```js
// jsImgData = js.Value of Uint8ClampedArray
imgData := make([]uint8, jsImgData.Length())
// fill imgData with magic...
js.CopyBytesToJS(jsImgData, imgData)
```

### What did you expect to see?

`jsImgData` filled to be puted in a canvas

### What did you see instead?

The log `syscall/js: CopyBytesToJS: expected dst to be an Uint8Array`.

**Comment by andybons** [comment]
@neelance @cherrymui
