### ISSUE TITLE
time: LoadLocation doesn't work on Linux if tzdata dependency not installed

### ISSUE THREAD

**Issue by ololosha228** [golang/go#38013]
### What version of Go are you using (`go version`)?

`go version go1.12.7 linux/amd64`

### Does this issue reproduce with the latest release?

Yeup, on all go versions

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ololosha228/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ololosha228/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build504687575=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Absolutely same thing as in #21881  ([code example](https://play.golang.org/p/VuJ3ofkdk8)). Problem is that zoneinfo is **so** large for packing it in binary file (800kb). But: as on windows, zone info package **is not required for any Linux distro**.

How did i found this issue: when you packing your go binary even with `-ldflags '-d -s -w'`  (static build for non-libc distros), using `time.LoadLocation()` always require `tzdata` dependency. This is awful, when you trying to pack your app in docker images without package manager (busybox, custom enterprise images). That's bad behavior.

_Actually, same problem is with net/http, when you try to connect using tls/ssl. but with https problem is explainable: ssl certificates updates often._

### What did you expect to see?

Working example on pure linux system. Basically i expect to see way to manage this issue.

### What did you see instead?

Program doesn't working 🙃

**Comment by ianlancetaylor** [comment]
I've filed #38017 as a proposal for a time/tzdata package.  Please comment or emoji vote there about this idea.  Thanks.

**Comment by leighmcculloch** [comment]
Does anyone know how non-Go problems address this issue on Linux distributions?

**Comment by ololosha228** [comment]
@leighmcculloch it **IS** go problem, cause time package forcely load data from constant folder, and you can't change tzdata path. This issue not about go as language, but go as standart library.

So, yes, this problem is related to go as it could be.

**Comment by ololosha228** [comment]
@andybons could you please add `ExpertNeeded` and `OS-Linux` labels to this issue?

**Comment by ianlancetaylor** [comment]
@ololosha228 That doesn't really answer @leighmcculloch 's question, though.  It seems like a good question to me.

I'll add the `OS-Linux` label but I'm not clear on why this is `ExpertNeeded`.

**Comment by dmitshur** [comment]
Re-opening as [CL 224588](https://golang.org/cl/224588) was rolled back in [CL 228200](https://golang.org/cl/228200).
