### ISSUE TITLE
gccgo: add support for -fgo-importcfg

### ISSUE THREAD

**Issue by stapelberg** [golang/go#38025]
`cmd/compile` and `cmd/link` got support for `-importcfg` in commits https://github.com/golang/go/commit/4d6b08de709f0914f640e0bc738e094443687bbf and https://github.com/golang/go/commit/4f2269edbd1b3e09484001c9cc7897b49c828b45, respectively.

The go tool already has support for conditionally using -fgo-importcfg when running gccgo: https://github.com/golang/go/blob/bb929b7452b5b8a6a584a94a110c98b0c6543a6e/src/cmd/go/internal/work/gccgo.go#L81-L92

…but gccgo itself doesn’t implement the `-fgo-importcfg` flag yet.

Adding support will allow us to drop a special case in our build system.

Filing this issue for tracking the addition as per @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Fixed by https://go.dev/cl/506095.
