### ISSUE TITLE
crypto/ecdsa: builders with long tests are failing in crypto/ecdsa.TestEqual

### ISSUE THREAD

**Issue by danscales** [golang/go#38035]
The builders with long tests (GO_TEST_SHORT=0) are failing in crypto.dsa.TestEqual.  For example:

https://build.golang.org/log/eaeb045adcbf56e2df980dc0cb8c17554dc2b50a

Looks like it started happening with change   5c9bd49,  https://go-review.googlesource.com/c/go/+/223754  @FiloSottile 

### What version of Go are you using (`go version`)?

Running on current gc tip

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Happens on linux-amd64 and bunch of other architectures.

**Comment by FiloSottile** [comment]
Reverted in CL 225077. I know what to fix.
