### ISSUE TITLE
cmd/go: misplaced error message about case-insensitive file name collision

### ISSUE THREAD

**Issue by rsc** [golang/go#38034]
This error should say the problem is in math, not reflect:

```
$ cd go/src/math
$ go build cmd/go
$ echo package math >Asinh.go
$ go build cmd/go
../reflect/value.go:8:2: case-insensitive file name collision: "Asinh.go" and "asinh.go"
$ 
```

/cc @bcmills @jayconrod @matloob

**Comment by bcmills** [comment]
I wonder if @matloob's [CL 224660](https://golang.org/cl/224660) already fixes this — it's at least very nearby.

**Comment by andybons** [comment]
@matloob @bcmills any update on this? Thanks.

**Comment by matloob** [comment]
This still exists at head. I'll send a fix
