### ISSUE TITLE
cmd/go: document using 'go list' to download modules needed to build packages

### ISSUE THREAD

**Issue by jayconrod** [golang/go#38031]
`go list -test ./...` can be used to download the modules needed to build tests of the packages matched by `./...`. This is usually a smaller set of modules than `go mod download all` (or equivalent `go mod download`) would select, so it's a useful command when building small Docker images.

This should be documented as a FAQ on https://github.com/golang/go/wiki/Modules.

Related #36460: fewer modules will be downloaded by `go mod download all` when lazy module loading is implemented.

**Comment by mvdan** [comment]
It also wasn't clear to me that `go mod download` was synonymous with `go mod download all`. Maybe `go help mod download` could be made a bit more explicit.

**Comment by mvdan** [comment]
Two more genuine use cases occurred to me, even in the face of lazy module loading being impemented:

* If one only wants non-test deps to be downloaded, `go list ./...` can download far less than `go list -test ./...`
* If one only wants deps required for a specific set of tags, `go list -tags=xxx ./...` might also avoid other unnecessary deps

And, like @jayconrod mentioned on slack, if one only needs the deps for a subset of the packages, like `go list ./cmd/...` if that's all that one needs to build offline later.

**Comment by jayconrod** [comment]
Added FAQ: https://github.com/golang/go/wiki/Modules#how-do-i-download-modules-needed-to-build-specific-packages-or-tests
