### ISSUE TITLE
encoding/json: encoding.UnmarshalText() produces unexpected values when json.Unmarshaling.

### ISSUE THREAD

**Issue by rkolp** [golang/go#38046]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, however it seems `v1.13.X` is working properly.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/<redacted>/Library/Caches/go-build"
GOENV="/Users/<redacted>/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/<redacted>/develop/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/<redacted>/develop/go/src/github.com/<redacted>/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2w/0n_2xt5x51sbnz4__k1slqnw0000gn/T/go-build451039144=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I tried to implement `encoding.TextUnmarshaler` for unmarshaling JSON. However when escaped characters are added to the end of a JSON value the unmarshaled value becomes mangled and includes JSON formatting characters.

```
package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

type RC string

func (r *RC) UnmarshalText(b []byte) error {
	*r = RC(fmt.Sprintf("RC_%s", strings.ToUpper(string(b))))
	return nil
}

type incident struct {
	Regions map[RC]Region `json:"regions"`
}

type Region struct {
	Facets []Facet `json:"facets"`
}

type Facet struct {
	SOE string `json:"sensitivity_override_explanation"`
}

func main() {
	r := `
	{
		"regions": {
			"US": {
				"facets": [{
				"sensitivity_override_explanation": "43423432423\\r"
				}]
			}
		}
	}
	`
	i := new(incident)

	if err := json.Unmarshal([]byte(r), &i); err != nil {
		fmt.Println(err)
		return
	}

	for k := range i.Regions {
		fmt.Printf("key: %q\n", k)
	}
}
```

### What did you expect to see?

`key: "RC_US"`

### What did you see instead?
`key: "RC_US\": {\n\t\t\t"`

**Comment by andybons** [comment]
@mvdan

**Comment by rkolp** [comment]
Looks like someone else ran into this issue as well: https://github.com/golang/go/issues/38105

**Comment by mvdan** [comment]
Thanks @rkolp. It looks like @dsnet already did a bisect and a backport issue there, so let's consolidate both issues into that one. I realise this issue is older, so apologies for the mishap.
