### ISSUE TITLE
distribute all the files cmd/go requires to run inside of cmd/go

### ISSUE THREAD

**Issue by mobop** [golang/go#38048]
instead of providing many files and dirs that is required to place at right place, Provide a single file 'go' that contains all off it.

**Comment by ianlancetaylor** [comment]
Sorry, I'm not sure what you mean.  Once the go tool is compiled, it doesn't need any of the files in cmd/go.

**Comment by mobop** [comment]
@ianlancetaylor i mean the files distributed with go tarball

**Comment by ianlancetaylor** [comment]
You mean the entire standard library?  That is used for many purposes, including documentation and analysis, by many different programs including very important ones like gopls.  I don't think we're going to remove all of it.  Sorry.
