### ISSUE TITLE
gccgo: producing wrong objectfiles on AIX 7.1 

### ISSUE THREAD

**Issue by ken997** [golang/go#38043]
### What version of Go are you using (`go version`)?

I want to use go 1.13

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

AIX 7.1, Processor Type: PowerPC_POWER7, CPU Type: 64-bit, Kernel Type: 64-bit

### What did you do?

I tried to build Gccgo on AIX 7.1. Within the build, Gccgo is building object files, which usually include .go_export sections. Out of these object files .gox files (for example atomic.gox) are created with the command "objcopy -j .go_export sync/.libs/atomic.o"

### What did you expect to see?
I checked the object files and expected to see the .go_export section.

### What did you see instead?
Only 3 sections: .text, .data and .debug. The build of gccgo fails with the Error "./sync/atomic.gox exists but does not contain any Go export data".

### This is where object files are created inside the build
libtool: compile: /OS/COMPSRV/trunk/user1/src/gccgo-obj/./gcc/gccgo -B/OS/COMPSRV/trunk/user1/src/gccgo-obj/./gcc/ -B/opt/freeware/gcc9/powerpc-ibm-aix7.1.5.0/bin/ -B/opt/freeware/gcc9/powerpc-ibm-aix7.1.5.0/lib/ -isystem /opt/freeware/gcc9/powerpc-ibm-aix7.1.5.0/include -isystem /opt/freeware/gcc9/powerpc-ibm-aix7.1.5.0/sys-include -O2 -g -I . -c -fgo-pkgpath=sync/atomic ../.././../gccgo-src/libgo/go/sync/atomic/doc.go ../.././../gccgo-src/libgo/go/sync/atomic/value.go -fPIC -o sync/.libs/atomic.o

### The configure options to reproduce

languages="--enable-languages=go,c,c++"
options="CC=/opt/freeware/bin/gcc --without-gnu-ar --without-gnu-as --with-gnu-ld --with-gmp-include=/usr/include/gmp --disable-bootstrap --with-gmp-lib=/usr/lib --with-mpfr-include=/usr/include/mpfr --with-mpfr-lib=/usr/lib --with-mpfr=/usr/include --with-mpc=/usr/include --disable-nls --disable-libquadmath --disable-libssp --disable-lto --disable-libgomp"
multilib="--enable-multilib"
shared="--enable-shared"
static="--enable-static"
 $srcdir/configure --prefix=$prefix "$languages" $options $shared $static $multilib "$version" && gmake -j$jobs

### Further Informations
I am using gcc 8.3 and building the gccgo 9.2

Sorry if this isn't an issue and AIX 7.1 is just not supported. But I hope somebody can help me.

**Comment by ianlancetaylor** [comment]
CC @Helflym

**Comment by Helflym** [comment]
I think the problem comes from "objcopy". It doesn't work as expected on AIX. 
Therefore, we (BullFreeware) have created a special RPM [binutils-gccgov1](http://www.bullfreeware.com/pkg?id=3554), which provides a better tool for .go_export named "copycsect". 
Our GccGo RPM have a patch [gcc-9.1.0-libgo-configure-use-copycsect-instead-of-objcopy.patch.txt](https://github.com/golang/go/files/4379581/gcc-9.1.0-libgo-configure-use-copycsect-instead-of-objcopy.patch.txt) to replace "objcopy" by "copycsect" in libgo's Makefile. 
Tell me if it does fix your problem. 

Is there any reason you need 9.2 over 9.1 ?

**Comment by ken997** [comment]
Thank you very much for helping me Helflym. This fixes my problem. I installed the binutils-gccgov1 and changed the configure and configure ac as described in the patch. I only chose a new gccgo version to use go modules, but I think it is also available at 9.1.
