### ISSUE TITLE
database/sql: incorrect count for DBStats.MaxLifetimeClosed for connections not closed in background goroutine

### ISSUE THREAD

**Issue by colinking** [golang/go#38058]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.8 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Based on the latest `master`, yeah.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/colinking/Library/Caches/go-build"
GOENV="/Users/colinking/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY="github.com/segment*"
GONOSUMDB="github.com/segment*"
GOOS="darwin"
GOPATH="/Users/colinking/dev"
GOPRIVATE="github.com/segment*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.8/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.8/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/colinking/dev/src/github.com/segmentio/cell-ctlstore/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p6/62gms5fd2sd51_yf9qzbrs9c0000gn/T/go-build662696632=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

We were tracking the number of closed connections over the lifetime of a process with [`MaxLifetimeClosed`](https://github.com/golang/go/blob/6b6414cab49fcc035e1f20bafdb723077e7d36bb/src/database/sql/sql.go#L1076) from [`DBStats`](https://github.com/golang/go/blob/6b6414cab49fcc035e1f20bafdb723077e7d36bb/src/database/sql/sql.go#L1063) after setting a max connection lifetime with [`SetConnMaxLifetime`](https://github.com/golang/go/blob/6b6414cab49fcc035e1f20bafdb723077e7d36bb/src/database/sql/sql.go#L941).

### What did you expect to see?

We expected `MaxLifetimeClosed` to be incremented once for every connection that was closed due to `SetConnMaxLifetime`.

### What did you see instead?

Only connections closed via the background goroutine ([`connectionCleaner`](https://github.com/golang/go/blob/6b6414cab49fcc035e1f20bafdb723077e7d36bb/src/database/sql/sql.go#L989)) were counted. Connections that are closed in [`conn`](https://github.com/golang/go/blob/6b6414cab49fcc035e1f20bafdb723077e7d36bb/src/database/sql/sql.go#L1189) ([here](https://github.com/golang/go/blob/6b6414cab49fcc035e1f20bafdb723077e7d36bb/src/database/sql/sql.go#L1212-L1215) and [here](https://github.com/golang/go/blob/6b6414cab49fcc035e1f20bafdb723077e7d36bb/src/database/sql/sql.go#L1264-L1267)) because it determines they are expired (and currently free) were not counted.

If this is the expected behavior, then I'm happy to open a PR with a fix.

**Comment by andybons** [comment]
@bradfitz @kardianos @kevinburke

**Comment by kardianos** [comment]
Yes, I believe you are correct. Those are closed due to max lifetime, but are not recorded in Stats.

Please keep this [CL](https://go-review.googlesource.com/c/go/+/216197) in mind if you send a patch.
