### ISSUE TITLE
x/tools/gopls: invoking `go version` causes a crash on Windows

### ISSUE THREAD

**Issue by inliquid** [golang/go#38062]
1. go1.14
2. VS Code

Today, after upgrade to latest from master, `gopls` started to crash with the error:
`panic: err: exit status 1: stderr: go: creating work dir: mkdir C:\Windows\go-build728148707: Access is denied.`

Previous version was compiled smth like ~1-2 days ago, so it's recent change.
```
C:\Users\***>echo %TMP%
C:\Users\***\AppData\Local\Temp

C:\Users\***>echo %TEMP%
C:\Users\***\AppData\Local\Temp
```

**Comment by stamblerre** [comment]
Thanks for the report! I am able to reproduce the crash on Windows. It's caused by https://golang.org/cl/225137 - specifically by calling `go version` in `golang.org/x/tools/internal/lsp/debug/info.go`. Probably we have to set a different working directory for the command? I'll take a look today.

**Comment by inliquid** [comment]
Problem is still there...
