### ISSUE TITLE
cmd/internal/obj: failed TestPCALIGN at read only GOROOT

### ISSUE THREAD

**Issue by mengzhuo** [golang/go#38069]
The linux-mengzhuo-mips64le builder has set goroot as read-only after build completed.

https://build.golang.org/log/97aac799817dbca76dda86e7df6fb044cf1a92fa

git bisect that [CL 207117](https://go-review.googlesource.com/c/go/+/207117)  runs `go tool asm -S test.s` without clarified the outfile to tmp path.

**Comment by andybons** [comment]
@cherrymui

**Comment by cherrymui** [comment]
I already sent CL https://go-review.googlesource.com/c/go/+/225440 for that. Thanks.

**Comment by cherrymui** [comment]
Fixed by the CL above.
