### ISSUE TITLE
x/playground: support multifile playground code

### ISSUE THREAD

**Issue by gopherbot** [golang/go#3806]
by **ajmani**:

<pre>play.golang.org is used frequently on the list to share example code, report bugs, and
discuss solutions to coding problems.  But since it only populates one source file,
there's no way to use play.golang.org to discuss issues around visibility (exported vs.
unexported symbols), which is an important element of API design.  It would be great if
play.golang.org could support multiple text windows for different files that are then
compiled and linked into a single binary.</pre>

**Comment by dlsniper** [comment]
This one seems easy enough to encourage new gophers to contribute to it, should it get a label to mark it as such?

**Comment by bradfitz** [comment]
Sure. It used to be much harder when it ran on internal Google infrastructure, but nowadays it's just a Docker container.

**Comment by ysmolsky** [comment]
Don't want to be a party pooper, but do we really need to have this? I mean, it's been 6 years already and nobody wanted even to try to implement it... Would it be a game changer if we had such a feature? What about relation to go modules? I am thinking out loud just to initiate a feedback from the community. 

@andybons

**Comment by andybons** [comment]
I'm less inclined to want this feature given the number of other services that provide it (https://repl.it comes to mind). The maintenance burden for something like this would be very high. I would need to understand why the playground would need to be in this space to begin with. Would the impact be worth the effort?

I like that play.golang.org (and various methods of embedding it) are relatively simple implementations that are highly effective. If users wish for something more with more features, they can get it via the other tools that exist (for example, https://goplay.space/).

Multiple files seems like overkill for this product.

**Comment by ysmolsky** [comment]
I wanted to implement this feature when I finished the first patch to playground. But now after some time and some more work done, I see the ratio of `profit/maintenace_cost` as close to zero. I appreciate the inarticulate simplicity of playground, both externally and internally.

**Comment by andybons** [comment]
Closing since other products do it better than we wish to at the moment.

**Comment by ysmolsky** [comment]
It is possible to run tests and examples in Playground: https://play.golang.org/p/5Ef482JD2Lp
