### ISSUE TITLE
x/build/dashboard: macOS builders should specify filesystem case sensitivity in Notes field

### ISSUE THREAD

**Issue by dmitshur** [golang/go#38076]
It should be easy to find out whether the filesystem is case sensitive or insensitive (macOS offers both options).

We can put this information in the [`Notes`](https://github.com/golang/build/blob/2bf41cd70ade4691877019a878f4ad34d42be1b5/dashboard/builders.go#L732) field, so it'll show up at https://farmer.golang.org/builders.

/cc @cagedmantis @toothrot @heschik

**Comment by andybons** [comment]
I think it should only be noted if it is _not_ the default configuration for macOS (this applies for any builder, really). I don’t see this configuration value being worthy enough to call out specifically.

**Comment by dmitshur** [comment]
When writing up this issue, I also initially hesitated about suggesting using the `Notes` field, because I noticed all the linux builders don't specify it either.

However, the main point of this issue is:

> It should be easy to find out whether the filesystem is case sensitive or insensitive (macOS offers both options).

When I had to look this up recently, I first checked https://farmer.golang.org/builders, then https://github.com/golang/build/tree/master/env/darwin/macstadium, then some internal documents, and couldn't find an answer. The only reliable way to confirm an answer was to `gomote` into a builder, as @cagedmantis has done.

I don't mind too much whether this information is placed in `Notes` or elsewhere, but I think it should be easy to look up an answer to this question more quickly in the future. The filesystem case sensitivity is a configurable option when installing macOS, so it's not easy to have complete confidence about what the default on macOS builders is.

@andybons Do you think it'd be better to document this somewhere else, or should we just rely on `gomote` to look up an answer in the future if we need to again?

**Comment by andybons** [comment]
> Do you think it'd be better to document this somewhere else, or should we just rely on gomote to look up an answer in the future if we need to again?

How many users have reported issues that are related to case-insensitivity? What is the default behavior when installing macOS? We should assume, and document otherwise, that our builders were installed with the default setting for any option.

If there is a need to find out what the behavior is, then gomoting is the right answer in this case. We should only be documenting behavior that is outside the norm for a particular OS/platform/VM.

**Comment by andybons** [comment]
Closing per discussion with @dmitshur outside of this issue.
