### ISSUE TITLE
x/pkgsite: display table of contents (TOC) in command documentation

### ISSUE THREAD

**Issue by dmitshur** [golang/go#38073]
### What is the URL of the page with the issue?

https://pkg.go.dev/cmd/go

### Screenshot

![image](https://user-images.githubusercontent.com/1924134/77559693-da999400-6e92-11ea-9958-d2444b044ad4.png)

### What did you do?
 
Visited command documentation. As an example, see https://pkg.go.dev/cmd/go, but this applies to any command (package with name "main").

### What did you expect to see?

A table of contents, like on https://golang.org/cmd/go:

![image](https://user-images.githubusercontent.com/1924134/77560741-39abd880-6e94-11ea-8130-05cde3c7fb2c.png)

### What did you see instead?

No table of contents.

This is a feature request to have feature parity with previous documentation rendering on golang.org and the [`godoc`](http://pkg.go.dev/golang.org/x/tools/cmd/godoc) package documentation viewer.

/cc @julieqiu

**Comment by myitcv** [comment]
> A table of contents, like on https://golang.org/cmd/go:

Did you perhaps intend for the comparison here to be with https://godoc.org/cmd/go?

**Comment by dmitshur** [comment]
I meant to compare with golang.org. godoc.org doesn't implement this feature.

Some implementation notes.

golang.org renders (via [x/tools/godoc](http://pkg.go.dev/golang.org/x/tools/godoc) package) the table of contents on the frontend via a generateTOC function here:

- https://github.com/golang/tools/blob/a49f79bcc2246daebe8647db377475ffc1523d7b/godoc/static/godocs.js#L369

pkg.go.dev does not need to do this on the frontend, it can render a table of contents on the backend (together with the where all of package documentation rendering currently happens).

This table of contents is applicable only for commands; library packages already have a table contents (it displays the functions, types, methods, etc.).

x/tools/godoc uses a div named "manual-nav" to disable the frontend from generating a table of contents for non-commands. See:

- https://github.com/golang/tools/blob/a49f79bcc2246daebe8647db377475ffc1523d7b/godoc/static/godocs.js#L33-L35
- https://github.com/golang/tools/blob/a49f79bcc2246daebe8647db377475ffc1523d7b/godoc/static/package.html#L57-L58

**Comment by jamalc** [comment]
Here is a mockup of the TOC feature.

<img width="1470" alt="Screen Shot 2021-02-17 at 11 10 25 AM" src="https://user-images.githubusercontent.com/18269441/108232430-c432a180-7110-11eb-9f22-cf073d140073.png">

**Comment by hyangah** [comment]
Index and "Jump to" feature for command documentations would be nice too.

**Comment by jamalc** [comment]
@hyangah that's a good idea, would you file that under a new issue? We'll need some discussion and UX review to figure out how it would work.
