### ISSUE TITLE
x/tools/gopls: support a workspace root that is a parent of GOPATH

### ISSUE THREAD

**Issue by stamblerre** [golang/go#38078]
See discussion in https://github.com/microsoft/vscode-go/issues/3124#issuecomment-603557847. It should be fairly trivial to implement this, but it may require modifying the root directory of the view, which is why it's filed under this milestone.

> ```
> /a/
> | - go/     <-- GOPATH
>      |- src/
>          | - b/...
>          | - c/...

**Comment by stamblerre** [comment]
@heschik, @findleyr: Do you think it's worth supporting something like this? It would mean setting the view's root URI to the $GOPATH/src directory instead of the top-level directory. My main concern is--what do we do if the user creates a module under `a`? Seems like it would be too confusing to manage and possibly not worth it.

**Comment by heschik** [comment]
No, I don't.

**Comment by hyangah** [comment]
That kind of directory structure and trick was evolved as a workaround for the pre-modules era.
Given that Go is moving away from `GOPATH` based source management, I think it's better for those users and us to think about how to migrate the code base to modules mode and figure out what prevents getting rid of the `GOPATH` hack.

**Comment by stamblerre** [comment]
I agree. With Go 1.16, this should be less of an issue. Also, I think it's reasonable to ask users to open $GOPATH/src as a workspace folder if they absolutely need to.

I will close this issue then.
