### ISSUE TITLE
使用go get 出现问题

### ISSUE THREAD

**Issue by yangQingYu123** [golang/go#38084]
<pre>
$ go version 13.5 window/amd64

</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
F:\go\src\kratos\cmd>go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\1\AppData\Local\go-build
set GOENV=C:\Users\1\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=F:\go
set GOPRIVATE=
set GOPROXY=https://mirrors.aliyun.com/goproxy/,direct
set GOROOT=D:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
</pre></details>

使用go get 的问题
go get -u github.com/bilibili/kratos/tool/testcli
go get github.com/bilibili/kratos/tool/testcli: module github.com/bilibili/kratos/tool/testcli: Get https://mirrors.aliyun.com/goproxy/github.com/bilibili/kratos/tool/testcli/@v/list: proxyconnect tcp: dial tcp: lookup proxy: no such host

**Comment by bcmills** [comment]
This seems like a problem with `mirrors.aliyun.com`, not the `go` command. Please file an issue with them instead.
