### ISSUE TITLE
 not compatible with the version of Windows

### ISSUE THREAD

**Issue by xilingit** [golang/go#38088]
fork/exec C:\Users\xilin\AppData\Local\Temp\go-build275391226\b001\exe\main.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

go1.14  win10

**Comment by cagedmantis** [comment]
Please provide more information about what was done to receive an error. What architecture is this running on? How can I reproduce this error? Was Go installed via a package?
