### ISSUE TITLE
internal compiler error: missing import reader for time.Time.IsZero

### ISSUE THREAD

**Issue by fwhezfwhez** [golang/go#38086]
### What version of Go are you using (`go version`)?
go 1.12.17
<pre>
$ go version
set GOARCH=amd64
set GOBIN=G:\go_workspace\GOPATH\bin
set GOCACHE=C:\Users\DELL\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=G:\go_workspace\GOPATH
set GOPROXY=https://goproxy.io
set GORACE=
set GOROOT=E:\go1.12
set GOTMPDIR=
set GOTOOLDIR=E:\go1.12\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fmessage-length=0 -fdebug-prefix-map=C:\Users\DELL\AppData\Local\Temp\go-build762241074=/tmp/go-build -gno-record-gcc-switches
</pre>

### Does this issue reproduce with the latest release?
no, it only occurs when I run debug

### What operating system and processor architecture are you using (`go env`)?
windows amd64

</pre></details>

### What did you do?
click ide vscode debug / click goland debug.

### What did you see instead?
```go
# shangraomajiang/config
<autogenerated>:1: internal compiler error: missing import reader for time.Time.IsZero

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
```

**Comment by andybons** [comment]
Go 1.12 is no longer supported. Can you update to 1.13 or 1.14? It’s unclear if this is a Go issue of a workspace setup issue. Have you followed the instructions at https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code ?

Without knowing what command is being used to invoke the debugger, it’s difficult to diagnose this problem.
