### ISSUE TITLE
net: ParseCIDR returns IP of size 16 and not 4 for IPv4

### ISSUE THREAD

**Issue by lzap** [golang/go#38097]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Fedora 31

### What did you do?

ParseCIDR does not return IP of expected size, at least according to the contract https://golang.org/pkg/net/#IP.To16 where it reads "If ip is not an IP address (it is the wrong length), To16 returns nil." Although the implementation of the IP address should be hidden, functions To4 and To16 actually do not follow the documentation. I want to use them to determine if the parsed IP address is IPv4 or IPv6, looks like it can't be done in any other way.

Reproducer: https://play.golang.org/p/eEiQOZkOWnu

**Comment by andybons** [comment]
@bradfitz @mikioh

**Comment by cespare** [comment]
In general IPv4 address may be represented as IPv6.

> I want to use them to determine if the parsed IP address is IPv4 or IPv6, looks like it can't be done in any other way.

You can: the way to do it is to check whether it's an IPv4 address or not (so see if `To4` returns nil). If it doesn't, you have an IPv4 address. If it does, you have an IPv6 address which does not represent an IPv4 address. Example:

https://play.golang.org/p/eY-VUtGE5Jr

> Although the implementation of the IP address should be hidden, functions To4 and To16 actually do not follow the documentation.

They do. The address you have *is* the right length to be an IP address.

**Comment by lzap** [comment]
Okay, thanks.
