### ISSUE TITLE
x/tools/cmd/guru: Can't find references if two packages have the same top-level name

### ISSUE THREAD

**Issue by coreyog** [golang/go#38094]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/cogburn/Library/Caches/go-build"
GOENV="/Users/cogburn/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/cogburn/src/goprojects"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/36/t5tp3n552gj71zsh8949yb6m0000gn/T/go-build983642327=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
The structure of our API looks like this:

```
handlers
    /a
    /b
    /c
service
    /a
    /b
    /c
```

Inside handlers is where we register routes, validate the payload, and generally do all the HTTP stuff. Then handlers calls a function in the corresponding service package, e.g. `handlers/a` will import and call functions in `service/a`. Here we do the business logic.

If I'm inside the `handlers/a` namespace and I "Find All References" in vscode on a function defined in `service/a` then guru only finds the references in `handlers/a`. I believe guru gets confused on which namespace "a" is in the code.

== handlers/a/a.go ==
```
package a

import (
  "service/a"
)

func DoSomething() {
  a.DoIt() // "Find All References" on the DoIt function only searches handlers/a and not service/a
}
```

### What did you expect to see?

I expect to see the references from the imported package.

### What did you see instead?

A list of references containing only the usages in the current package.

**Comment by andybons** [comment]
@alandonovan @josharian

**Comment by adonovan** [comment]
guru was deleted in https://github.com/golang/go/issues/65880; closing as obsolete.
