### ISSUE TITLE
db.Query does not always expand the parameter

### ISSUE THREAD

**Issue by graywolf-at-work** [golang/go#38098]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
+:( $ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/wolf/.cache/go-build"
GOENV="/home/wolf/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="go.showmax.cc"
GONOSUMDB="go.showmax.cc"
GOOS="linux"
GOPATH="/home/wolf/go"
GOPRIVATE="go.showmax.cc"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/wolf/tmp/trigger_test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build944301925=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Using the pq adapter (`github.com/lib/pq`) and database/sql I've tried dropping a table:

```
_, err := db.Query("DROP TABLE $1", "test")
if err != nil {
panic(err)
}
```

Documentation ( https://godoc.org/database/sql#DB.Query ) does not suggested that this should not work.

### What did you expect to see?

```
panic: pq: table "test" does not exist
```

### What did you see instead?

```
panic: pq: syntax error at or near "$"
```

**Comment by illegaluid** [comment]
it seems better report to github.com/lib/pq ~_~

**Comment by illegaluid** [comment]
Maybe you should  try 
db.Query(`DROP TABLE $1`, "test")

and it seems better report to  github.com/lib/pq

**Comment by illegaluid** [comment]
> Maybe you should try
> db.Query(`DROP TABLE $1`, "test")
> 
> and it seems better report to github.com/lib/pq

`DROP..

**Comment by graywolf-at-work** [comment]
Ok, I did not know how this exactly works and who is responsible for it. I'll open bug report on lib/pq instead.
