### ISSUE TITLE
encoding/json: mangled unmarshal string result

### ISSUE THREAD

**Issue by AllenX2018** [golang/go#38105]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, it reproduces with the latest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
</pre></details>

### What did you do?
I create a type whose real type is string and implement `encoding.TextUnmarshaler` and `encoding.TextUnmarshaler`. I use this type as a map's key type. Then I just simply do a roundtrip test with `encoding/json`'s `Marshal` and `Unmarshal` function. When my input json contains non-ascii characters, something unexpected happened.
```go
type KeyString string

func (k KeyString) MarshalText() ([]byte, error) {
	return []byte("Prefix__" + k), nil
}

func (k *KeyString) UnmarshalText(text []byte) error {
	*k = KeyString(strings.TrimPrefix(string(text), "Prefix__"))
	return nil
}

func test() {
	b := []byte(`{"开源":"12345开源"}`)
	m := make(map[KeyString]string)

	if err := json.Unmarshal(b, &m); err == nil {
		fmt.Println(m)
		s, _ := json.Marshal(m)
		fmt.Println(string(s))
	}
}
```

### What did you expect to see?
```
Output:
map[开源:12345开源]
{"开源":"12345开源"}
```

### What did you see instead?
```
Output:
map[开��:12345开源]
{"开\ufffd\ufffd�":"12345开源"}
```

**Comment by dsnet** [comment]
\cc @mvdan 

Git bisect indicates 54697702e435bddb69c0b76b25b3209c78d2120a.

Since this is a regression for go1.14, the fix should be probably be cherry-pick worthy for the go1.14 releases branch.

**Comment by dsnet** [comment]
@gopherbot, please open a backport issue for 1.14.

**Comment by mvdan** [comment]
Thanks @dsnet - I'll try to have a look at it this weekend.
