### ISSUE TITLE
go.dev: overview tab should show README.md, not README.go

### ISSUE THREAD

**Issue by adamluzsi** [golang/go#38109]
## Overview tab shows the wrong readme file

In my project, I have a README.md and a README.go.
One for the project overview, and one for the package level godoc.
On the overview tab in pkg.go.dev, the README.go is displayed instead of the markdown file as for the other projects.

[link to an example](https://pkg.go.dev/github.com/adamluzsi/testcase?tab=overview).

### Does this issue reproduce with the latest release?
yes

### What did you do?
I made two file in my project
- README.md
- README.go

### What did you expect to see?
overview tab present the README.md content like for the other projects.

### What did you see instead?
README.go content was displayed without as plain text.

### PS

Dear Go Team,

I'm not 100% sure if showing the README.md on the overview tab is an expected behavior actually for pkg.go.dev.

Keep up the good work Go Team!

Kind Regards,
Adam

**Comment by julieqiu** [comment]
Thanks for the feedback! We'll work on a fix for this specific issue to prefer README.md over README.go.

We are planning to address the overview tab as a whole as part of an upcoming round of UX changes.
/cc @fflewddur

**Comment by adamluzsi** [comment]
Dear @juliequi, 

Thank you for helping!!! This is not blocking me. I wish good health to everyone! 

Cheers
Adam

**Comment by julieqiu** [comment]
Fixed.

**Comment by adamluzsi** [comment]
Thank you so much for fixing my issue,
I really appreciate it!
