### ISSUE TITLE
x/tools/internal/lsp/regtest: change behavior when awaiting diagnostics

### ISSUE THREAD

**Issue by stamblerre** [golang/go#38113]
Struggled to come up with a good issue description, so sorry if it's not clear. 

As I've been writing more regtests, I've noticed that waiting on diagnostics can be tedious if you're not certain what the diagnostic should be - you end up having to wait 30 seconds for the tests to run just to confirm that you made a mistake in the column number or something like that. Is it reasonable for the regtests to see that a diagnostic came in for the file in question, but it was just not the expected one, and then exit early?

/cc @findleyr

**Comment by findleyr** [comment]
I started working on something related to this in https://golang.org/cl/225158 earlier this week, but ran into strange problems with the non-standard request that I haven't figured out.

You can also change the timeout in reg_test.go -- that's what I do when writing a new test.

**Comment by findleyr** [comment]
@stamblerre I think this was fixed (at least as well as it can be) by https://golang.org/cl/229977. Do you agree?

**Comment by stamblerre** [comment]
Yep! Let's close.
