### ISSUE TITLE
[WASM] js.Func.Invoke() callback stuck indefinitely in/after fmt.Println()

### ISSUE THREAD

**Issue by markus-wa** [golang/go#38129]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>GOARCH=wasm GOOS=js PATH="$PATH:/opt/go/current/misc/wasm" go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="wasm"
GOBIN=""
GOCACHE="/home/mark/.cache/go-build"
GOENV="/home/mark/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="js"
GOPATH="/home/mark/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go/go-1.14.1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/go-1.14.1/pkg/tool/linux_amd64"
GCCGO="gccgo"
GOWASM=""
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/home/mark/dev/demoinfocs-wasm/app/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build721813713=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

`GOARCH=wasm GOOS=js PATH="$PATH:/opt/go/misc/wasm" go test`

```go
package main

import (
	"fmt"
	"sync"
	"syscall/js"
	"testing"
)

func TestWasmIssue(t *testing.T) {
	fmt.Println("Hello")

	wg := new(sync.WaitGroup)

	handleResult := func(this js.Value, result []js.Value) interface{} {
		wg.Done()                // no problem
		fmt.Println("Finished!") // prints, but seems to block forever
		fmt.Println("...")       // this doesn't
		wg.Done()
		fmt.Println("WaitGroup done")
		return nil
	}
	handleResultJS := js.ValueOf(js.FuncOf(handleResult))

	wg.Add(2)

	handleResultJS.Invoke()

	wg.Wait()
}
```

notes:
- `os.Stdout.WriteString()` (and `os.Stderr`) behave the same

### What did you expect to see?

```
Hello
Finished
...
WaitGroup done
```

### What did you see instead?

```
Hello
Finished
```

after that it's stuck indefinitely. 1 CPU is maxed out.
with go version 1.13.7 I ran into #35256.

seems like the `stdout` writer might be blocking?

with go 1.11 it worked (though the API of `syscall/js` was quite a bit different back then, so not exactly the same code).

**Comment by agnivade** [comment]
fmt.Println is a blocking call. You cannot block anything in the callback.

https://golang.org/pkg/syscall/js/?GOOS=js&GOARCH=wasm#FuncOf

Closing, as this is WAI.
