### ISSUE TITLE
go.dev: no repo link

### ISSUE THREAD

**Issue by willfaught** [golang/go#38124]
See https://pkg.go.dev/git.paulbsd.com/paulbsd/weather/src/data?tab=overview.

There's no convenient link to the repo anywhere on the page that I can find, unlike godoc.org. This would be very useful. There's a button next to the package path that looks like it opens a new window for the repo, but it actually just copies a Go import statement for the package to the clipboard, which is confusing. I couldn't tell what the button was actually doing until I hovered over it.

**Comment by heschik** [comment]
On the page you linked to, there is a link to the repository under the "Source Code" header, next to the text "Repository:".

**Comment by willfaught** [comment]
Ah, I missed that, it must have been the non-GitHub .git extension that threw me off. Thanks.
