### ISSUE TITLE
cmd/go: go get github.com/hakluke/hakrevdns: copying /tmp/go-build114431271/b001/exe/a.out: open /home/ahsan/go/bin/hakrevdns: permission denied

### ISSUE THREAD

**Issue by Ahsan-x** [golang/go#38128]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?
Window wsl
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ahsan/.cache/go-build"
GOENV="/home/ahsan/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ahsan/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build230505770=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
just installed the latest version of go from source code and when i try to use go get i face the error

**Comment by bcmills** [comment]
Please fill out the complete issue template. What was the exact command you ran, and what was the full error output? (Redact any paths that you don't want to share.)

**Comment by Ahsan-x** [comment]
Thank you bcmills I uninstalled go and installed it again and it fixed the problem.
