### ISSUE TITLE
/x/tools/cmd/yacc

### ISSUE THREAD

**Issue by PeterlitsZo** [golang/go#38133]
(sorry because I kown it is a stupid question)
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
emmm... I think it is my problem

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/peter/.cache/go-build"
GOENV="/home/peter/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/peter/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build636313802=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```
go get -u golang.org/x/tools/cmd/goyacc
go tool yacc
```

### What did you expect to see?
something useful like usage

### What did you see instead?
```
go tool: no such tool "yacc"
```

p.s. I try to search how to run yacc in Google, but the message to too useless. I hope you can help me... Thanks

**Comment by seankhliao** [comment]
the tool is called goyacc

**Comment by mvdan** [comment]
What @seankhliao said. Also see the `go get` docs at https://golang.org/pkg/cmd/go/internal/get/.

**Comment by PeterlitsZo** [comment]
thanks for your advices, `^_^`

**Comment by PeterlitsZo** [comment]
advice for other friends:

if you try `goyacc` but it does not work, try to use `find / -name "goyacc" 2> /dev/null` to find where is the `\go\bin` dir, and then add it to your PATH.
