### ISSUE TITLE
Proposal: Improve dead code ilimination when using CGO

### ISSUE THREAD

**Issue by Keithcat1** [golang/go#38135]
### What version of Go are you using (`go version`)?
                                                
<pre>
$ go version
go version go1.14.1 windows/amd64                                                                                              

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Build an executable that uses a large C library statically linked.

### What did you expect to see?

A smaller executable
### What did you see instead?
A kind-of large executable.

I'm not completely sure about this, but when Go links, either statically or dynamically, I think it includes a reference to all C functions wrapped with CGO in the resulting executable, even if those functions are never called.
It would help to only include required C symbols. This could in theory help the C compiler do dead code ilimination with static libraries. Adding the CFLAGS -ffunction-sections -fdata-sections, and LDFLAGS -Wl,-gc-sections could also do something.
Thanks.

**Comment by ianlancetaylor** [comment]
When using cgo, the Go linker builds an object file containing all the Go code, and it passes that object file to the C linker.  The Go linker will discard any unused Go code.  So the only references to C functions will be from Go code that might be called.  Everything else is up to the C linker.

I agree with your `CFLAGS` and `LDFLAGS` suggestion, but I don't think that Go should do that by default.  I think that the C compilation and linking should use just a few simple options, not options like `-ffunction-sections` or `-Wl,--gc-sections` that can cause some programs to break.

So I don't think there is anything to do here.
