### ISSUE TITLE
runtime: incorrect sanity checks in the page allocator

### ISSUE THREAD

**Issue by rasky** [golang/go#38130]
While investigating the optimizations performed by my prove CL 196679, I found out these two instances of what looks like dead code:

https://github.com/golang/go/blob/d99fe1f40dfacfdebee22c13ed4471fd50f2cc1a/src/runtime/mpagealloc.go#L726-L734

https://github.com/golang/go/blob/d99fe1f40dfacfdebee22c13ed4471fd50f2cc1a/src/runtime/mpagealloc.go#L768-L773

That branch is never taken because `pallocBits.find()` return an unsigned number:
https://github.com/golang/go/blob/d99fe1f40dfacfdebee22c13ed4471fd50f2cc1a/src/runtime/mpallocbits.go#L197-L206

Given the documentation, it looks like the failure is reported as `^uint(0)` so the above checks are probably wrong.

/cc @aclements @mknyszek

**Comment by mknyszek** [comment]
Ah! Thank you. I'll fix that right away.

Earlier on in the review process the return value was indeed an int, but this was used as a shift in multiple places, so I changed the whole `pallocBits` API to return `uint`s.

Luckily these are just sanity checks, but if there is a bug in the page allocator, it could lead to bad pointers being returned (and possibly memory corruption).

**Comment by mknyszek** [comment]
Uploaded a fix. We may want to backport this. Like I said before, if there's a bug in the page allocator that would cause these sanity checks to fail, it would manifest as memory corruption as opposed to the immediate failure it was supposed to be.

CC @bcmills who has been tracking a bunch of the memory corruption issues.
CC @randall77 @cherrymui who have been looking into some of the memory corruption issues.

**Comment by rasky** [comment]
I wonder whether this should become a vet check. I think with vet, we can at least find very simple instance (eg: unsigned number < 0); prove is able to find similar always-true or always-false conditions in more complicated situations which vet wouldn't be able to; but prove of course cannot emit a compile-time error.

Maybe this should go into what @dr2chase was doing, that is a log of "important information" written by the compiler during compilation.
