### ISSUE TITLE
unicode variable not allowed

### ISSUE THREAD

**Issue by pjebs** [golang/go#38147]
```go
t€ := fromPrice.Value / frR
```
Compiler spits out error: `invalid identifier character U+20AC '€'`

I was under the impression it should be allowed as per the spec: https://golang.org/ref/spec#Identifiers

**Comment by seankhliao** [comment]
> `identifier = letter { letter | unicode_digit } .`

> `letter = unicode_letter | "_" .`

> `unicode_letter = /* a Unicode code point classified as "Letter" */ .`


€ is classified as `Currency Symbol`
