### ISSUE TITLE
encoding/json.Unmarshal doesn't deal with conflicting keys

### ISSUE THREAD

**Issue by icco** [golang/go#38141]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nat/Library/Caches/go-build"
GOENV="/Users/nat/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/nat/Projects"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org"
GOROOT="/usr/local/Cellar/go/1.14.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/nat/Projects/relay/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x_/nv225yzx4d32q31hf_g735cc0000gn/T/go-build148188573=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

a.go
```go
package lib

import (
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
)

type Data struct {
	*A
	*B
}

type A struct {
	Episodes []struct {
		ID             int    `json:"id"`
		EpisodeNumber  int    `json:"episodeNumber"`
		SeasonNumber   int    `json:"seasonNumber"`
		Title          string `json:"title"`
		QualityVersion int    `json:"qualityVersion"`
	} `json:"episodes"`
	EventType string `json:"eventType"`
	Series    struct {
		ID     int    `json:"id"`
		Title  string `json:"title"`
		Path   string `json:"path"`
		TvdbID int    `json:"tvdbId"`
	} `json:"series"`
}

type B struct {
	Albums []struct {
		ID             int    `json:"id"`
		Title          string `json:"title"`
		QualityVersion int    `json:"qualityVersion"`
	} `json:"albums"`
	EventType string `json:"eventType"`
	Artist    struct {
		ID   int    `json:"id"`
		Name string `json:"name"`
		Path string `json:"path"`
		MbID string `json:"mbId"`
	} `json:"artist"`
}

func Parse(b io.Reader) (string, error) {
	var data Data

	buf, err := ioutil.ReadAll(b)
	if err != nil {
		return "", err
	}

	if err := json.Unmarshal(buf, &data); err != nil {
		return "", fmt.Errorf("decoding json to structured data: %w", err)
	}

	if data.A != nil {
		return data.A.EventType, nil
	}

	if data.B != nil {
		return data.B.EventType, nil
	}

	return "", fmt.Errorf("no valid type data")
}
```

a_test.go
```go
package lib

import (
	"strings"
	"testing"
)

func TestParse(t *testing.T) {
	tests := map[string]struct {
		Have string
		Want string
	}{

		"A": {
			Have: `{
  "episodes": [
    {
      "id": 123,
      "episodeNumber": 1,
      "seasonNumber": 1,
      "title": "Test title",
      "qualityVersion": 0
    }
  ],
  "eventType": "Test",
  "series": {
    "id": 1,
    "title": "Test Title",
    "path": "C:\\testpath",
    "tvdbId": 1234
  }
}`,
			Want: "Test",
		},
		"B": {
			Have: `{
  "albums": [
    {
      "id": 123,
      "title": "Test title",
      "qualityVersion": 0
    }
  ],
  "eventType": "Test",
  "artist": {
    "id": 1,
    "name": "Test Name",
    "path": "C:\\testpath",
    "mbId": "aaaaa-aaa-aaaa-aaaaaa"
  }
}`,
			Want: "Test",
		},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			got, err := Parse(strings.NewReader(tc.Have))
			if err != nil {
				t.Error(err)
			}

			if got != tc.Want {
				t.Errorf("ReaderToMessage(%q) returned %q wanted %q", tc.Have, got, tc.Want)
			}
		})
	}
}
```
### What did you expect to see?

I expected the tests to pass.

### What did you see instead?

The EventType field on both structs is empty.

**Comment by seankhliao** [comment]
Conflicting fields from embedded structs can only be accessed through `.EmbededType.Field` and not `.Field` directly, so json has nowhere to unmarshal to

**Comment by icco** [comment]
That makes sense, is there a common way to change this code to deal with this case?

Otherwise, it does feel like a bug because it silently fails. 

I wonder if it would be worth adding to go vet or something to prevent people from doing this.

**Comment by mvdan** [comment]
> That makes sense, is there a common way to change this code to deal with this case?

The general answer here is don't use anonymous struct fields that introduce ambiguity. There is also `json:"-"` if you want to skip an entire anonymous field, to let another one be used completely.

> Otherwise, it does feel like a bug because it silently fails.

There is no failure. It's just not doing what you think it should.

> I wonder if it would be worth adding to go vet or something to prevent people from doing this.

The program above is valid, so `vet` shouldn't complain about it.

I believe [the docs](https://golang.org/pkg/encoding/json/#Marshal) are already pretty unambiguous about this case:

> Anonymous struct fields are usually marshaled as if their inner exported fields were fields in the outer struct, subject to the usual Go visibility rules amended as described in the next paragraph.

If you think the docs could be made clearer, suggestions or patches are welcome. But there isn't a bug here, as far as I can tell.

**Comment by icco** [comment]
Sorry, @mvdan I think you're talking about the inverse case? I'm decoding JSON that I don't control. Depending on the circumstances, the source sends different JSON. There are no conflicting keys in this JSON except the "event_type" key. 

I've created two types to cover each different situation. Even if the types have different names for the struct value `EventType` (for instance if I called one `EventTypeA` and the other `EventTypeB`). But because they have the same `json:` tag, neither gets filled. This seems like a bug to me.

The code also works if there is just one type, with no conflicting `json:` tag. The docs are talking about turning structs into json, I care about turning json into structs.

In UnMarshal, the docs say:

> To unmarshal JSON into a struct, Unmarshal matches incoming object keys to the keys used by Marshal (either the struct field name or its tag), preferring an exact match but also accepting a case-insensitive match. By default, object keys which don't have a corresponding struct field are ignored (see Decoder.DisallowUnknownFields for an alternative).

I guess the change I'd make to the docs is add the sentence: `If there are two fields with the same tag, anywhere in the underlying struct (or it's children), Go will not decode into either.`

**Comment by mvdan** [comment]
The rules for anonymous structs (i.e. following the Go visibility rules) are the same when unmarshaling - that's why I linked them earlier. If you want to make that clearer, we can, but we should point to the existing rules (already documented) instead of explaining the same rules in a different way.

**Comment by icco** [comment]
I see, I misunderstood. You're referring to #3 below. Thank you.

> 1) Of those fields, if any are JSON-tagged, only tagged fields are considered, even if there are multiple untagged fields that would otherwise conflict.
> 2) If there is exactly one field (tagged or not according to the first rule), that is selected.
> 3) Otherwise there are multiple fields, and all are ignored; no error occurs.

Re your comment `The general answer here is don't use anonymous struct fields that introduce ambiguity.` How would you change the above code to have the tests pass? My understanding of https://blog.golang.org/json is that anonymous structs are the best practice here.

**Comment by networkimprov** [comment]
Define a struct type with all the possible fields; use pointers so that json inputs which lack a field yield nil. 
```
type Data struct {
   EventType int
   Artist *struct {...}
   Albums []struct {...}
   Series *struct {...}
   Episodes []struct {...}
}
```

**Comment by icco** [comment]
Cool. Thanks.
