### ISSUE TITLE
url.go --> Get method key parameter should not be case sensitive

### ISSUE THREAD

**Issue by zsy619** [golang/go#38155]
### What version of Go are you using (`go version`)?

<pre>
go version go1.14.1 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?
GO111MODULE=""
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOCACHE="/Users/zsy/Library/Caches/go-build"
GOENV="/Users/zsy/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zsy/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/97/824ymy115zz8_d75p7b9dx200000gn/T/go-build145530837=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?
modif key compare,not be case sensitive

### What did you see instead?
go/src/net/url/url.go modify:
	for i, k := range v {
		if strings.ToLower(i) == strings.ToLower(key) {
			return k[0]
		}
	}

**Comment by zsy619** [comment]
url param should not be case-insensitive
Why is it case sensitive here？only use map type？
It should be based on the actual application
![image](https://user-images.githubusercontent.com/6278792/77893685-cc8aaf80-72a6-11ea-91cd-f78d52b41b8b.png)

**Comment by ALTree** [comment]
Hi,

`Values` is documented to be case sensitive:

> type Values
> 
> Values maps a string key to a list of values. It is typically used for query parameters and form values. **Unlike in the http.Header map, the keys in a Values map are case-sensitive**. 

I guess on things that are supposed to be used for "query parameters and form values" it's better to be case sensitive(?)

I'm closing here since I don't believe this is a bug; the method is working as documented. Comment if you disagree and we'll re-open.

**Comment by zsy619** [comment]
ok
