### ISSUE TITLE
x/website:  some thing out of date  at doc/effective_go.html#composite_literals

### ISSUE THREAD

**Issue by luchuanbing123** [golang/go#38154]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.14 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?
a := [...]string{"no error", "Eio", "invalid argument"}
s := []string{"no error", "Eio", "invalid argument"}
m := map[int]string{1: "no error", 2: "Eio", -1: "invalid argument"}

### What did you see instead?
is there some thing out of date   
at https://golang.org/doc/effective_go.html#composite_literals  

![image](https://user-images.githubusercontent.com/4416199/77889996-52a3f780-72a1-11ea-8908-91ef57de6b2a.png)

**Comment by bcmills** [comment]
These entries are correct. The point of that example is to illustrate that the same syntax can be used for slice or array indices and for map keys.
