### ISSUE TITLE
x/net/publicsuffix: Release as a separate module

### ISSUE THREAD

**Issue by tamalsaha** [golang/go#38169]
### What did you expect to see?

Since https://github.com/golang/net/tree/master/publicsuffix includes a generated 
table.go file, it will be really helpful if the publicsuffix can be made its own module. This will allow us to use the latest publicsuffix module with an old version of x/net module.

**Comment by bcmills** [comment]
Why do you want to use an old version of `x/net`?

**Comment by tamalsaha** [comment]
We have a dependency on Kubernetes. We just use whatever go.mod automatically picks based on that dependency.

**Comment by bcmills** [comment]
Sure, but why is that preferable to using an upgraded `x/net`? (What, if any, harm does a newer `x/net` cause?)

**Comment by ALTree** [comment]
This has been in waiting for info for more than a year, usecase still unclear, seems like there's not a lot of interest in making pubblicsuffix its own module, I think we can close.
