### ISSUE TITLE
Widows firewall remove my .exe build file

### ISSUE THREAD

**Issue by mrostamii** [golang/go#38160]
Don't use "go run", if it bothers your firewall. Use "go build -o a.exe && a.exe" or something similar instead. Would that work for you?

Alex

_Originally posted by @alexbrainman in https://github.com/golang/go/issues/13479#issuecomment-161926670_

---------

I did it but the problem is still here. I'm uploading a file and the import list is as the section below:

```
import (
	"bytes"
	"fmt"
	"io"
	"io/ioutil"
	"mime/multipart"
	"net/http"
	"os"
	"path/filepath"
)
```

**Comment by ianlancetaylor** [comment]
What exactly  are you doing?  What exactly happens?  Thanks.

See also https://golang.org/doc/faq#virus.

**Comment by mrostamii** [comment]
The source code:  
```

package main

import (
	"bytes"
	"fmt"
	"io"
	"io/ioutil"
	"mime/multipart"
	"net/http"
	"os"
	"path/filepath"
)

func main() {

	url := "http://xx.xx.xx.xx:xx/upload/image"
	method := "POST"

	//to get the file from input
	fmt.Printf("Enter the file name that located on: C:/")
	var inputPath string
	fmt.Scanln(&inputPath)
	var uploadingFilePath string = "C:/" + inputPath

	payload := &bytes.Buffer{}
	writer := multipart.NewWriter(payload)
	file, errFile1 := os.Open(uploadingFilePath)
	defer file.Close()
	part1,
		errFile1 := writer.CreateFormFile("file", filepath.Base(uploadingFilePath))
	_, errFile1 = io.Copy(part1, file)
	if errFile1 != nil {

		fmt.Println(errFile1)
	}
	err := writer.Close()
	if err != nil {
		fmt.Println(err)
	}

	client := &http.Client{}
	req, err := http.NewRequest(method, url, payload)

	if err != nil {
		fmt.Println(err)
	}
	req.Header.Set("Content-Type", writer.FormDataContentType())
	res, err := client.Do(req)
	defer res.Body.Close()
	body, err := ioutil.ReadAll(res.Body)

	fmt.Println(string(body))
	fmt.Printf("\nCongrats, the File has uploaded.\n\nHit the 'ENTER' key to exit.\n	 MIMTech")
	var input string
	fmt.Scanln(&input)
}

```

**Comment by ianlancetaylor** [comment]
Thanks, but what exact command do you run?  What is the exact output?

**Comment by mrostamii** [comment]
I forgot, thank you for the response.

---
I run:

    go build .\HttpUploadDownload-Checker\main.go

The output is:

    go build command-line-arguments: open C:\Users\MRT\AppData\Local\Temp\go-build076108262\b001\exe\a.out.exe: Operation did not complete successfully because the file contains a virus or potentially unwanted software.  

In addition, I disabled the Windows Defender and made a build file (`.exe`). After I enabled the Windows Defender, the build file can be run just one time then a Windows Defender notification appears.

**Comment by ianlancetaylor** [comment]
Yes, sorry, this is covered by https://golang.org/doc/faq#virus.  There isn't really anything we can do about it.  Some Windows virus checkers complain about some Go binaries, and this has to be fixed by the virus checker.
