### ISSUE TITLE
x/exp/cmd/gorelease: requirements are incomplete

### ISSUE THREAD

**Issue by carnott-snap** [golang/go#38164]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOOS="linux"
GOPATH="/home/user/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/user/.local/share/umake/go/go-lang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/.local/share/umake/go/go-lang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build393300957=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```sh
go get golang.org/x/exp/cmd/gorelease
go mod tidy
gorelease 
```

### What did you expect to see?
```
Suggested version: v2.0.2 (with tag v2.0.2)
```

### What did you see instead?
```
Inferred base version: v2.0.1
go.mod: requirements are incomplete.
Run 'go mod tidy' to add missing requirements.
```

**Comment by jayconrod** [comment]
Could you say more about your project's structure? Does `go mod tidy` make any changes to your `go.mod` file? Do you have any `replace` or `exclude` directives? If you have a minimal reproducible example, that would be helpful.

`gorelease` loads all the packages in the module as if it were not the main module (ignoring `replace` or `exclude` directives). If something imports a package that is not provided by any module in the build list, `gorelease` will report this error.

**Comment by carnott-snap** [comment]
Unfortunately the specific module is closed source and a little complex, happy to debug things manually till I can extract a reproducer.

The affected module is a submodule, and it contins a number of packages including an `internal`, and `_examples`. It is currently tagged at `sub/v2.0.1`. `go mod tidy` does not make any changes and exits with status `0`. It does not contain any `replace` or `exclude`  directives.

**Comment by jayconrod** [comment]
It might have something to do with the `_examples` directory, though I'm not sure what. That would be ignored by `go list ./...`, which is close to what `gorelease` uses to build a package list. It should also be ignored by `go mod tidy` though.

**Comment by carnott-snap** [comment]
I have narrowed down the root cause, but still cannot reproduce it outside this repo. It appears to relate to a single test import that only exists in one `xxx_test.go` file. When that import statement is removed (along with the references) `gorelease` works.

Is there some debugging I can do to diff the _list_ that `go mod tidy` does with `gorelease`?

**Comment by carnott-snap** [comment]
Further investigation suggests that it is an interaction between this dependency and a previous release of the current module, both of which were untidy (missing `h1`s from `go.sum`).

What is the general recovery strategy for "gorelease cannot process of the previous release"? It would be nice to be able to diff the old api, but I get that some failures are too systemic.

**Comment by jayconrod** [comment]
> It appears to relate to a single test import that only exists in one xxx_test.go file.

Very strange. I don't think `gorelease` loads tests, so this shouldn't cause new requirements to be added to `go.mod`.

There's not a direct way to debug this, but the relevant function in `gorelease` is [loadPackages](https://go.googlesource.com/exp/+/refs/heads/master/cmd/gorelease/gorelease.go#836).

 > Further investigation suggests that it is an interaction between this dependency and a previous release of the current module, both of which were untidy (missing h1s from go.sum). This would explain why go mod tidy does nothing, the real ask is to mod tidy a previous release.

This shouldn't cause an issue. Only the `go.sum` file for the main module matters; the `go` command ignores other `go.sum` files. And in any case, this error is only shown if a `require` line is added to `go.mod` during the loading process, and only for the release version (the checked out code).

Clearly a needed improvement is that `gorelease` should say *which* requirements are added or updated.

But it still sounds like since `go mod tidy` doesn't make any change to `go.mod`, this error shouldn't be happening at all.
