### ISSUE TITLE
runtime: comment in map.go misspells loadFactorDen variable name

### ISSUE THREAD

**Issue by maronghe** [golang/go#38174]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/logan/Library/Caches/go-build"
GOENV="/Users/logan/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/logan/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wx/ld5h9gvx15gfqnnsvfs_g3t40000gn/T/go-build945589872=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
May this a small issue for go doc.  I found that in the map.go `src/runtime/map.go`  
For this one `Represent as loadFactorNum/loadFactDen, to allow integer math`. I can not find the `loadFactDen` in this file. We all know that it is the `loadFactorDen`. But for a preciseness team, I think we are looking for the best doc above other language. So I kindly hope to change `loadFactDen` to `loadFactorDen `. So can I create a Pull Request in the [Go code review](https://go-review.googlesource.com/q/status:open) ?

### What did you expect to see?

`Represent as loadFactorNum/loadFactDen, to allow integer math` 

### What did you see instead?
`Represent as loadFactorNum/loadFactorDen, to allow integer math`

**Comment by ALTree** [comment]
Hi,

you mean just updating the comment al line 69 to spell the variable name "loadFactorDen" (which is the correct name the variable has) instead of "loadFactDen"? Yeah sure. Please send a change.

**Comment by maronghe** [comment]
> Hi,
> 
> you mean just updating the comment at line 69 to spell the variable name "loadFactorDen" (which is the correct name the variable has) instead of "loadFactDen"? Yeah sure. Please send a change.

Hi @ALTree , Thank you for your replying.
I am so honor to become a contributor. But I'm in China. But When I try to commit a change and execute 

`git clone https://go.googlesource.com/go && (cd go && f=`git rev-parse --git-dir`/hooks/commit-msg ; mkdir -p $(dirname $f) ; curl -Lo $f https://gerrit-review.googlesource.com/tools/hooks/commit-msg ; chmod +x $f)`.

 It returns

`fatal: unable to access 'https://go.googlesource.com/go/': Failed to connect to go.googlesource.com port 443: Operation timed out`.

So I need some time to resolve it. 
Perhaps It may be all the China Contributors' the problem we are facing. 
So I will update change after resolved it. For the above time out problem. 

Does anyone know how to resolve it?

**Comment by ALTree** [comment]
If go.googlesource.com/go is blocked from your location and you're familiar with the github workflow, you could tru to send your change request via github. 

See: https://golang.org/doc/contribute.html#sending_a_change_github
