### ISSUE TITLE
encoding/json: marshal result of string type struct field with ",string" option change in go1.14

### ISSUE THREAD

**Issue by AllenX2018** [golang/go#38173]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
</pre></details>

### What did you do?
This issue is actually a separate issue from discussions below #38126. 
```go
type T struct {
	F1 string `json:"F1,string"`
}

t := T {
	"aaa\tbbb",
}

b, _ := json.Marshal(t)
fmt.Println(string(b))
```

### What did you expect to see?
Before go 1.14:

```
{"F1":"\"aaa\\tbbb\""}
```

Autually I'm not sure which of the output results is correct. I think it was introduced by [0e015e20](https://github.com/golang/go/commit/0e015e20cfe7265635af605d274ff8dc2de5b3a2) but I don't know why it has to be changed like that. I want to figure out which of them exactly match the godoc's description:

> The "string" option signals that a field is stored as JSON inside a JSON-encoded string

### What did you see instead?
After go1.14:

```
{"F1":"\"aaa\tbbb\""}
```

**Comment by mvdan** [comment]
@gopherbot, please open a backport issue for 1.14.

I think this is a regression - https://go-review.googlesource.com/c/go/+/193604 was a good change, but we didn't properly think of all the edge cases. I have a fix nearly ready. CC @breml @dsnet
