### ISSUE TITLE
runtime: go generate makes changes

### ISSUE THREAD

**Issue by josharian** [golang/go#38188]
Some recent CL (don't know which one) causes running 'go generate' in the runtime package to make changes. Those changes cause ppc64 breakage. See CL 226679 and https://storage.googleapis.com/go-build-log/779d2501/linux-ppc64le-buildlet_c7e20015.log

I don't plan to investigate further.

cc @cherrymui @laboger

**Comment by cherrymui** [comment]
Is this new? I thought it has been like this for a long time. I always manually clean it up if I run `go generate`.

**Comment by josharian** [comment]
Maybe it's not new. I assumed it must be, since it seemed like the kind of thing that I would absolutely want to fix ASAP.
