### ISSUE TITLE
net: failure with "limit on … simultaneously alive goroutines is exceeded" on darwin-amd64-race builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#38184]
[2020-03-31T18:10:56-2d77d33/darwin-amd64-race](https://build.golang.org/log/388eebd1f83ad2d336eff62942631feadeb330b6)

```
race: limit on 8128 simultaneously alive goroutines is exceeded, dying
FAIL	net	14.688s
FAIL
go tool dist: Failed: exit status 1
```

This is the first I've seen this error.

**Comment by ianlancetaylor** [comment]
For those who don't know, the error message is from the race detector.

https://github.com/llvm/llvm-project/blob/master/compiler-rt/lib/sanitizer_common/sanitizer_thread_registry.cpp#L152

**Comment by jarreds** [comment]
Seeing this error as well. I realize the test suite that's generating this is pretty extraordinary, but it would be great to have a knob we can turn to enable a higher number.

**Comment by ianlancetaylor** [comment]
@jarreds The race detector code is maintained as part of LLVM, outside of the Go project.  That would be the place to ask.

**Comment by Deleplace** [comment]
Updated link to the race detector error message:

https://github.com/llvm/llvm-project/blob/main/compiler-rt/lib/sanitizer_common/sanitizer_thread_registry.cpp#L150
