### ISSUE TITLE
errors: inconsistency between os.IsNotExist and errors.Is with wrapped error

### ISSUE THREAD

**Issue by orlangure** [golang/go#38198]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yury/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
</pre></details>

### What did you do?

[Playground](https://play.golang.org/p/X-YphtafMRi)

```go
package main

import (
	"errors"
	"fmt"
	"io/ioutil"
	"os"
)

func main() {
	_, err := ioutil.ReadFile("foobar")
	fmt.Println("original error:", err)

	fmt.Println("os.IsNotExist", os.IsNotExist(err))
	fmt.Println("errors.Is", errors.Is(err, os.ErrNotExist))
	
	fmt.Println("wrapping with Errorf")
	
	err = fmt.Errorf("can't read file: %w", err)

	fmt.Println("os.IsNotExist", os.IsNotExist(err))
	fmt.Println("errors.Is", errors.Is(err, os.ErrNotExist))
}

// Output:
// original error: open foobar: No such file or directory
// os.IsNotExist true
// errors.Is true
// wrapping with Errorf
// os.IsNotExist false
// errors.Is true
```

### What did you expect to see?
Consistent reporting in both `errors.Is` and `os.IsNotExist` with both wrapped and not wrapped `no such file or directory` error.

### What did you see instead?
The original error returned by `ioutil.ReadFile` is recognized as `ErrNotExist` by both `errors.Is` and `os.IsNotExist`.
Error wrapped with `fmt.Errorf("text: %w", err)` is no longer recognized by `os.IsNotExist`, but still recognized by `errors.Is`.

**Comment by andybons** [comment]
@neild @jba

**Comment by neild** [comment]
For better or worse, we chose not to change the definition of `os.IsNotExist` and other preexisting predicate functions to unwrap errors. This is intentional behavior.

**Comment by orlangure** [comment]
Thank you. Does it mean the we should always use `errors.Is`, and consider `os.IsNotExist` deprecated?

**Comment by neild** [comment]
You should use `errors.Is` if you want the check to unwrap errors.

**Comment by harshavardhana** [comment]
Would it be helpful to update the os.IsNotExist documentation to ensure that users end up using errors.Is() instead of os.IsNotExist when applicable?

**Comment by ianlancetaylor** [comment]
@harshavardhana That has been done for the future 1.16 release for #41122 in https://golang.org/cl/268897.

There is nothing to do here, so closing this issue.  Please comment if you disagree.

**Comment by harshavardhana** [comment]
> There is nothing to do here, so closing this issue. Please comment if you disagree.

This looks good @ianlancetaylor - thank you
