### ISSUE TITLE
x/pkgsite: broken source links in autogenerated API docs

### ISSUE THREAD

**Issue by seehuhn** [golang/go#38205]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/seehuhn.de/go/websocket?tab=doc
 
### What is your user agent?
 

 
 `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36`
 
### Screenshot
 

 
<img width="636" alt="Screenshot 2020-04-01 at 22 26 13" src="https://user-images.githubusercontent.com/584729/78188392-0ce55b80-7468-11ea-932d-e70fca29e9ee.png">

### What did you do?
 

 
 I clicked on the blue `Conn` shown at the top of the screenshot.
 
### What did you expect to see?
 
 I hoped to reach the [source code of `Conn`](https://github.com/seehuhn/go-websocket/blob/d82c32d/conn.go#L38).
 
### What did you see instead?

The link led to `https://github.com/seehuhn/go-websocket.git/blob/v1.0.0/conn.go#L38`, but this page does not exist so the browser showed an 404 error message.  The problem can be fixed by changing `go-websocket.git` to `go-websocket` in the URL.

**Comment by julieqiu** [comment]
Thanks for the feedback, @seehuhn! We will work on a fix for this. Related: #37819

**Comment by shaqque** [comment]
It looks like this is a problem with the meta tag at [https://www.seehuhn.de/go/websocket?go-get=1](https://www.seehuhn.de/go/websocket?go-get=1):

```
<meta name="go-import" content="seehuhn.de/go/websocket git https://github.com/seehuhn/go-websocket.git">
```

In particular, note the output of `go help importpath` specifies that
> The meta tag has the form:
>
>     <meta name="go-import" content="import-prefix vcs repo-root">
> ...
> The repo-root is the root of the version control system containing a scheme and **not containing a .vcs qualifier.**
(emphasis added)

**Comment by shaqque** [comment]
I've filed an issue upstream in seehuhn/go-websocket#1. Closing this issue in favor of that one. Feel free to comment on this issue again or open a new one if the problem has not been resolved.

**Comment by seehuhn** [comment]
Thank you for your feedback.  I will change the meta tags on my site, so the problem should be solved.

Nevertheless, I just want point out that the corresponding link on godoc.org works even with my current meta tag (click the "Conn" link at https://godoc.org/seehuhn.de/go/websocket#Conn to see this).  So in a sense, one could see this change as a regression.
