### ISSUE TITLE
net: UDPConn.WriteToUDP not sending anything on Windows

### ISSUE THREAD

**Issue by jmarkel44** [golang/go#38202]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\jmarkel\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\repo
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\jmarkel\AppData\Local\Temp\go-build202622878=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
Trying to run an mdns query using the hashicorp/mdns client

https://github.com/hashicorp/mdns

### What did you expect to see?
Expected to see a list of devices with mDNS services. 

### What did you see instead?
No results. 
Please see the attached call stack.

With Wireshark running, I was not seeing any packets when the program was invoked.
![windows](https://user-images.githubusercontent.com/3406342/78174820-7f7e1900-741f-11ea-99ad-b14b84827b7f.png)

It's as if the call into the dll (WSASentTo()) to send the UDP message is not working correctly, though no errors are thrown when stepping through the code.

**Comment by andybons** [comment]
Without code to reproduce this (ideally a minimal reproduction), it is extremely difficult to diagnose what is going on. Do you have an example client/server setup you could provide? Perhaps this would also be more appropriate for https://github.com/hashicorp/mdns/issues/80 and once you’ve determined it’s an issue with the Go toolchain, you could then revisit this issue.

**Comment by jmarkel44** [comment]
```
package main

import (
        "fmt"
        "github.com/hashicorp/mdns"
)

func main() {
        // Make a channel for results and start listening
        fmt.Println("searching for new entries")
        entriesCh := make(chan *mdns.ServiceEntry, 4)
        go func() {
                for entry := range entriesCh {
                        fmt.Printf("Got new entry: %v\n", entry)
                }
        }()

        // Start the lookup
        mdns.Lookup("_ssh._tcp", entriesCh)
        close(entriesCh)
}
```

Please see the call stack for verification of the Golang toolchain.

**Comment by andybons** [comment]
Does this work as expected on platforms other than Windows?

**Comment by jmarkel44** [comment]
yeah, works great on a Pi. see attachment.  

![pi_mdns](https://user-images.githubusercontent.com/3406342/78176864-d1746e00-7422-11ea-8a55-1ea9084abfaf.png)

**Comment by andybons** [comment]
Thanks. That’s helpful.

Can you attach text instead of images, please? Images are harder to read and hurt accessibility.

**Comment by andybons** [comment]
@mikioh @alexbrainman

**Comment by jmarkel44** [comment]
Sure.  Will do.

**Comment by andybons** [comment]
Tentatively marking this a release blocker for 1.15 while we gather more info.

**Comment by andybons** [comment]
Could be because of any of the known bugs outlined here: https://golang.org/pkg/net/#pkg-note-BUG

**Comment by jmarkel44** [comment]
Just wanted to note I've updated Go (same problem, however)

go version go1.14.1 windows/amd64

**Comment by jmarkel44** [comment]
Any updates on this or any potential workarounds?

**Comment by andybons** [comment]
@jmarkel44 it’s been two days. Please be patient.

**Comment by jmarkel44** [comment]
There's a Timeout in the Lookup function. The code above is the recommended way to use the library too, based on github.com/hashicorp/mdns. 

As noted, this works perfectly on a RPi.

Thanks.

**Comment by ianlancetaylor** [comment]
I'm sure you're right, but when I look at that program it looks clearly incorrect.  Humor me.  Thanks.

**Comment by jmarkel44** [comment]
What results are you getting when running the program?

**Comment by ianlancetaylor** [comment]
I don't have a Windows system.

**Comment by ianlancetaylor** [comment]
But on my GNU/Linux system I get

```
searching for new entries
2020/04/03 13:09:02 [INFO] mdns: Closing client {0xc000010030 0xc000010038 0xc000010040 0xc000010048 1 0xc0000181e0}
```

**Comment by jmarkel44** [comment]
so if you do something like 

`$ dns-sd -B _workstation._tcp`

are there any mDNS devices on the network?

**Comment by ianlancetaylor** [comment]
I don't have `dns-sd` installed.

It would not surprise me if there are no mDNS devices on the network.

**Comment by alexbrainman** [comment]
@jmarkel44 

I never used this package github.com/hashicorp/mdns - I don't know what it does. But I tried running your program on Linux:

```
searching for new entries
2020/04/05 16:52:10 [INFO] mdns: Closing client {0xc000010030 0xc000010038 0xc000010040 0xc000010048 true 0xc000068180 {1 0}}
2020/04/05 16:52:10 [ERR] mdns: Failed to read packet: read udp4 0.0.0.0:55783: use of closed network connection
```

and on Windows

```
searching for new entries
2020/04/05 16:54:47 [ERR] mdns: Failed to bind to udp6 port: listen udp6 [ff02::fb]:5353: setsockopt: not supported by windows
2020/04/05 16:54:48 [INFO] mdns: Closing client {0xc00014c020 0xc00014c028 0xc00014c030 <nil> true 0xc000108180 {1 0}}
2020/04/05 16:54:48 [ERR] mdns: Failed to read packet: read udp4 0.0.0.0:54096: use of closed network connection
```

And 2 outputs looks very similar to me.

If you think the problem is in `UDPConn.WriteToUDP`, please, create small program that we can run on our computers to investigate. Do not assume we have Wireshark installed or other special tools available.

Thank you.

Alex

**Comment by jmarkel44** [comment]
So this came down to a set-interface issue on the windows platform. traversing the entire list of possible interfaces resolves the issue we were seeing with mdns package. 

Thanks for the help!

Closing the ticket.

**Comment by arojoal** [comment]
> So this came down to a set-interface issue on the windows platform. traversing the entire list of possible interfaces resolves the issue we were seeing with mdns package.
> 
> Thanks for the help!
> 
> Closing the ticket.

Please, could you provide a code example of the solution?
