### ISSUE TITLE
"encoding/gob"  gob: type gocv.Mat has no exported fields

### ISSUE THREAD

**Issue by tangtang666** [golang/go#38218]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.14
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
I want to use a socket to send a pic Gocv.Mat

	conn, _ := net.Dial("tcp", "localhost:8090")
	encoder := gob.NewEncoder(conn)
	//var chip gocv.Mat
	fmt.Println("start read pic")
	gocv.IMRead("test2/1.png", 0)
	img := gocv.NewMat()
	fmt.Println("start send pic")
	err := encoder.Encode(img)
	fmt.Println(err)

**Comment by mdlayher** [comment]
The error is correct. You cannot gob encode a type with no exported fields.

This is not an issue with Go, please see https://github.com/golang/go/wiki/Questions.
