### ISSUE TITLE
cmd/go: go module with a private repo on specific port

### ISSUE THREAD

**Issue by rootblack45** [golang/go#38213]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rootblack45/Library/Caches/go-build"
GOENV="/Users/rootblack45/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/rootblack45/Projects/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qh/bpc7h6_96yg0nqdm3ztr_3p00000gn/T/go-build518112140=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I want to use go mod with a private repo. My GitLab running on port 19547 and GitLab SSH running on port 36000. I try to config git config to specific port but still got an error

### What did you see instead?

> git.rootblack45.io/mymodule: cannot find module providing package git.rootblack45.io/mymodule: unrecognized import path "git.rootblack45.io/mymodule": https fetch: Get "https://git.rootblack45.io/mymodule?go-get=1": dial tcp <IP>:443: i/o timeout

**Comment by bcmills** [comment]
The [remote import path protocol](https://golang.org/cmd/go/#hdr-Remote_import_paths) expects the initial HTTPS (or HTTP) response from the default port (Go package paths are not URLs, and do not include port numbers). The response from that server should include the port (if needed) in the VCS URL that it returns.

**Comment by rootblack45** [comment]
> The [remote import path protocol](https://golang.org/cmd/go/#hdr-Remote_import_paths) expects the initial HTTPS (or HTTP) response from the default port (Go package paths are not URLs and do not include port numbers). The response from that server should include the port (if needed) in the VCS URL that it returns.

A default port is running another service. I know that Go package paths are not URLs. I don't know that the response from the server is included the port or not. But I had tried to change .gitconfig file to pull Go package by SSH instead of HTTP but it, not work
