### ISSUE TITLE
crypto/x509: can set pathlen in certificate when not CA

### ISSUE THREAD

**Issue by m-j-jam** [golang/go#38216]
RFC 5280 prohibits setting path lengths when not a CA.
From section 4.2.1.9

CAs MUST NOT include the pathLenConstraint field unless the cA
boolean is asserted and the key usage extension asserts the
keyCertSign bit.

This isn't restricted by the library, and means you can create invalid certificates. These are now failing checks in the latest version of OpenSSL (https://github.com/openssl/openssl/issues/11456)

The relevant code is around

https://github.com/golang/go/blob/801cd7c84d42dcf18256416524aa0d31d6305830/src/crypto/x509/x509.go#L1746

Something like
if !template.IsCA {
    maxPathLen = -1
}
would probably fix, but I'm not an expert in either Go or security, so don't want to change critical code.

**Comment by andybons** [comment]
@katiehockman @FiloSottile

**Comment by katiehockman** [comment]
Yes this looks like something we should fix. Let's aim for 1.15. Thanks for filing the issue.

/cc @FiloSottile if you want to comment further
