### ISSUE TITLE
bug: errors.Unwrap() returns nil for non-wrapped errors

### ISSUE THREAD

**Issue by kolyshkin** [golang/go#38227]
Is it possible to make `errors.Unwrap()` return its argument as is if it's not unwrappable? Currently, in case the argument is not an unwrappable error, it returns `nil`, which doesn't make sense (to me).

### What version of Go are you using (`go version`)?

```console
$ go version
go1.13.6 linux/amd64
$ go1.14 version
go version go1.14 linux/amd64
```

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go1.14 env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kir/.cache/go-build"
GOENV="/home/kir/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/kir/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/kir/sdk/go1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/kir/sdk/go1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build274341033=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Consider the following code:
```go
package main

import (
	"errors"
	"syscall"
)

func foo(name string) {
	file, err := file.Open(name)
	if err != nil {
		return err
	}
	defer file.Close()

	var st syscall.Stat_t
	err = syscall.Fstat(file.Fd(), &st)
	if err != nil {
		return err
	}

	// ... and so on
}

func main() {
	err := foo("/path/to/file")
	if err != nil {
		if errors.Unwrap(err) == syscall.EBUSY {

			// handle EBUSY
		}
	}
}

```
### What did you expect to see?

Code detects `EBUSY` underlying error returned from both `os.Open` (wrapped in `os.PathError`) and 
`syscall.Fstat()` (not wrapped, syscall.Errno is returned directly).

### What did you see instead?

`EBUSY`, if returned from `syscall.Fstat()`, is not detected by the code :(

**Comment by ianlancetaylor** [comment]
It looks to me like you should use `errors.Is` rather than calling `errors.Unwrap` directly.

**Comment by kolyshkin** [comment]
Here is an example from the code I'm working on:

```go
// isIgnorableError returns whether err is a permission error (in the loose
// sense of the word). This includes EROFS (which for an unprivileged user is
// basically a permission error) and EACCES (for similar reasons) as well as
// the normal EPERM.
func isIgnorableError(err error) bool {
        // Is it an ordinary EPERM?
        if os.IsPermission(err) {
                return true
        }
        // Handle some specific syscall errors.
        errno := errors.Unwrap(err)
        return errno == unix.EROFS || errno == unix.EPERM || errno == unix.EACCES
}
```

This (as I found out) won't work if an error is not wrapped.

> It looks to me like you should use errors.Is rather than calling errors.Unwrap directly.

Reimplementing it with `errors.Is()` does not look very elegant to me, since the error will be unwrapped 3 times in the worst-case scenario.

Perhaps making errors.Is() last argument variadic might help in this particular scenario (exceopt it would contradict the meaning of "Is").

**Comment by kolyshkin** [comment]
OK it seems that `errors.As()` should be used in the case described in a previous comment. Sorry, didn't mean to use issues for learning go :-\

```go
        var errno syscall.Errno
        if errors.As(err, &errno) { 
                return errno == unix.EROFS || errno == unix.EPERM || errno == unix.EACCES
        }
```

I still find `errors.Unwrap()` behavior odd wrt returning `nil` for unwrappable errors.

**Comment by ianlancetaylor** [comment]
I think it's best to think of `errors.Unwrap` as a helper function.  The real functions are `errors.Is` and `errors.As`.  Those functions are slightly easier to implement if `errors.Unwrap` returns `nil` when it has finished unwrapping.  Otherwise you need a weird `err == errors.Unwrap(err)` test.

I'm going to close this since it seems that you got your code working, and since `errors.Unwrap` is in the 1.13 and 1.14 releases I don't think we can change it now.
