### ISSUE TITLE
x/tools/gopls: show hover information for runes

### ISSUE THREAD

**Issue by stamblerre** [golang/go#38239]
From https://github.com/microsoft/vscode-go/issues/3149:

> In Go, runes can be expressed as single-quoted readable glyphs, single-quoted escaped `\u` codes, or number literals (usually hex). It’s often hard to know what a particular rune is, short of extensive commenting as in [this example](https://github.com/golang/go/blob/master/src/unicode/tables.go#L7108).
> 
> It would be very helpful in VSCode to hover over _any_ of these forms to get info on the rune, such as:
> 
> * visual glyph (if any)
> * description e.g. “ARABIC THOUSANDS SEPARATOR”
> * `\u` representation
> * hex representation
> 
> Thanks for the consideration, happy to discuss.

This can be implemented using https://pkg.go.dev/golang.org/x/text/unicode/runenames.

**Comment by jhchabran** [comment]
If this ticket is still up to date, I'd like to implement it. 

Is that okay if I take it @stamblerre?

**Comment by stamblerre** [comment]
Absolutely, @jhchabran! Please comment here if you need any additional guidance.

**Comment by jhchabran** [comment]
Thanks! I think I need some guidance regarding the marker tests. 

I [wrote some regtests for hovering runes](https://github.com/jhchabran/tools/pull/1/files#diff-af70ec1234370a37044ce3ebd3fa4eeb9f28dcdfabd5e11dd5fd6ab77be88b70), but I am unsure how to proceed with the marker tests and even if I should write some for this feature.

From what I understand, roughly speaking, the `@hover("something", mark)` works by matching `something` and checking that hovering it references the object that was marked. 

Hovering a rune does not reference anything, so I don't see how I could express that with a marker test, assuming I understood how it presently works. Maybe some self-reference? 

Do you think I should dig into the markers more and eventually see how they could be made to work with the rune hovering or the regtests would be enough for such an "isolated" feature?

**Comment by stamblerre** [comment]
Thanks for working on this! The regtests might be sufficient for this case, but if you'd like to add marker-based tests, you could also adjust the way that the `@hover` test works, here: https://github.com/golang/tools/blob/062bf4eb8ab9c68e2c22214899f3e17b66ddbbf3/internal/lsp/tests/tests.go#L437.

**Comment by jhchabran** [comment]
Thanks for the pointer! I spent a bit more time on the markers and got how they work. 
It now basically looks like this: 

```go
// internal/lsp/testdata/basiclit/baciclit.go
// (...) 
_ = '\U0001F30A' //@hovertooltip("'\\U0001F30A'", "'🌊', U+1F30A, WATER WAVE")
```

Another marker called `@hovertooltip` was added because modifying the `@hover` to make it work with expecting a reference to a definition **or** a direct string representation of the expected result is probably too convoluted and unclear to read.  

➡️ Is that okay to have added another one? I think it makes sense especially if there are other hovers that may be added later on. 

I also get the feeling that renaming `@hover` to `@hoverdef` would make more sense now, but that's probably better to discuss it over a CL rather than here.

**Comment by stamblerre** [comment]
Yep, totally fine to add a new marker type! Happy to continue the conversation over a CL.

**Comment by jhchabran** [comment]
@stamblerre Being the first time I submit a CL, I just wanted to be sure that I am not missing anything that would block the process. Is there something else to do on my part before my CL (see above) gets reviewed ? 

If not, I'll happily wait until someone reviews it :)

**Comment by stamblerre** [comment]
Thanks for pinging this, @jhchabran! Looks like something went wrong and owners didn't get added as reviewers. I've added myself and will take a look soon.
