### ISSUE TITLE
x/exp/cmd/gorelease: module go directive compatibility

### ISSUE THREAD

**Issue by carnott-snap** [golang/go#38240]
I recall the impact of updating the `go` directive, e.g. `go 1.11` -> `go 1.14`, on compatibility being discussed in [CL 197299](https://go-review.googlesource.com/c/exp/+/197299) but do not see a resolution. Does `gorelease` currently ignore this, and what should it do?

**Comment by andybons** [comment]
@jayconrod

**Comment by jayconrod** [comment]
Thanks for the reminder. `gorelease` currently ignores this, but I think the resolution was that we *should* increment the minor version when the `go` version changes.

Let's track this in #37564. I've added a comment there.
