### ISSUE TITLE
The gopls show error message

### ISSUE THREAD

**Issue by lukexue** [golang/go#38243]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/Luke/Library/Caches/go-build"
GOENV="/Users/Luke/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/Luke/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/Luke/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/Luke/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6k/cnnvcn5s5qq0nwhk1b51833c0000gn/T/go-build257193198=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

2020/04/04 11:31:54 failed to parse matching URL: parse "218.6.64.250:60039": first path segment in URL cannot contain colon
[Error - 11:31:54 AM] 2020/04/04 11:31:54 failed to parse matching URL: parse "218.6.64.250:60039": first path segment in URL cannot contain colon
2020/04/04 11:31:54 failed to parse matching URL: parse "112.5.17.114:3306": first path segment in URL cannot contain colon
2020/04/04 11:31:54 failed to parse matching URL: parse "112.5.125.129:3078": first path segment in URL cannot contain colon
[Error - 11:31:54 AM] 2020/04/04 11:31:54 failed to parse matching URL: parse "112.5.125.129:3078": first path segment in URL cannot contain colon
[Error - 11:31:54 AM] 2020/04/04 11:31:54 failed to parse matching URL: parse "112.5.17.114:3306": first path segment in URL cannot contain colon
[Info  - 11:31:55 AM] 2020/04/04 11:31:55 go/packages.Load
	snapshot = 8
	query = [./]
	packages = 1
[Info  - 11:32:11 AM] 2020/04/04 11:32:11 background imports cache refresh starting
[Info  - 11:32:11 AM] 2020/04/04 11:32:11 background refresh finished after 94.940187ms
	Error = <nil>

### What did you see instead?
<img width="936" alt="截圖 2020-04-04 上午11 32 18" src="https://user-images.githubusercontent.com/2391716/78417803-6a47fb00-7668-11ea-8d40-f946706cea1f.png">

**Comment by stamblerre** [comment]
@lukexue: Is there a feature of `gopls` that isn't working? Those error messages are probably harmless--they are being reported by a feature that tries to determine if there are any clickable links in your code.

One thing I did notice is that it looks like `gopls` thinks you are outside of your GOPATH and outside of a module - is this intentional?

**Comment by stamblerre** [comment]
I believe that these errors should be eliminated by https://golang.org/cl/227559. Please reopen if not.
