### ISSUE TITLE
net/http2: "http2: stream closed" on medium file

### ISSUE THREAD

**Issue by zoic21** [golang/go#38247]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build656777711=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I used http2 to tunneling connexion between client and server (based on https://github.com/mmatczuk/go-http-tunnel project, with some change like used last version of goland http2). When client is based on aarch64 (I can't reproduce on x86_64 for now) and file to transfert size is medium size (~200ko) connexion is cut and I get "http2: stream closed". It's transfert only about first 129ko.

### What did you expect to see?

Transfert file completly

### What did you see instead?

Only first 129ko

Maybe it's just a buffer size to tweak for my usage but I'am not sure.

Thank in advance

**Comment by zoic21** [comment]
For information if I revert to golang.org/x/net v0.0.0-20200324143707-d3edc9973b7e problem disapear

**Comment by andybons** [comment]
Can you post example code (preferably a minimal example)? d3edc9973b7e is the latest commit on x/net. When you say “revert” do you mean upgrade to use the latest x/net in the go distribution you’re using?
