### ISSUE TITLE
give me commit rights

### ISSUE THREAD

**Issue by ret394** [golang/go#38241]
can fix issues. can't do silly things in https://golang.org/doc/contribute.html

**Comment by ALTree** [comment]
Hi @ret394, you don't need commit rights to contribute to the project and to fix issues. The usual workflow is that you send a patch, which is reviewed and merged by a code owner. You don't need commit rights for this. See https://golang.org/doc/contribute.html

Commit rights are given to existing contributors after a long-ish period of sustained contributions to the project, usually to enable them to garden the issue tracker and review and commit other contributor's patches. 

I'm closing here, but please feel free to start contributing to the project if you wish, again by following the guide at https://golang.org/doc/contribute.html.

**Comment by ALTree** [comment]
Oh, and a note:

> can't do silly things in https://golang.org/doc/contribute.html

people with commit rights still need to do "the silly things" in https://golang.org/doc/contribute.html. You don't get to skip any of that if you have commit rights. The process for contributing is exactly the same for everyone. The only difference is that you can push the merge button by yourself after the review.

**Comment by ret394** [comment]
thanks. have a nice day. keep up the
