### ISSUE TITLE
cmd/compile: missing trim column in ssa.html

### ISSUE THREAD

**Issue by josharian** [golang/go#38242]
It is the final column. I suspect the recent collapse-duplicate-columns CL has a bug.

cc  @bradford-hamilton

**Comment by bradford-hamilton** [comment]
Oh no, I will take a look and see whats going on.

**Comment by bradford-hamilton** [comment]
It looks like maybe `stackframe` and `trim` are missing.. Strange, but I'll keep you posted and submit a CL once I figure out whats going on.
