### ISSUE TITLE
x/build/cmd/release: ARMv7 binaries are not available on storage.googleapis.com

### ISSUE THREAD

**Issue by giacomovalenti** [golang/go#38256]
ARMv7 isn't anymore available from downloads

### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by ALTree** [comment]
Hi,

> from downloads

Where? Please link the page you're looking at. 

> anymore

When did you believe this changed?

Looking at recent and old releases at https://golang.org/dl/ we always had two for linux/arm:

- linux-arm64.tar.gz | ARMv8 
- linux-armv6l.tar.gz | ARMv6

And these are still present in the latest releases.

**Comment by giacomovalenti** [comment]
until yesteday i was able to download https://storage.googleapis.com/golang/go1.11.13.linux-armv7l.tar.gz. 
You wrote about armv8 and armv6. where is armv7l?
 Please help I need it

**Comment by ALTree** [comment]
I'm not sure you're supposed to access these storage.googleapi.com urls directly and if we guarantee any kind of availability on binaries you find there, but cc @dmitshur for investigation.

**Comment by giacomovalenti** [comment]
I was using it since long time ago ; can you tell me what i can do to obtain the same results? i was able to install go using this scripts
#!/bin/bash
set -e

VERSION="1.14"

[ -z "$GOROOT" ] && GOROOT="$HOME/.go"
[ -z "$GOPATH" ] && GOPATH="$HOME/go"

OS="$(uname -s)"
ARCH="$(uname -m)"

case $OS in
    "Linux")
        case $ARCH in
        "x86_64")
            ARCH=amd64
            ;;
        "armv6")
            ARCH=armv6l
            ;;
        "armv8")
            ARCH=arm64
            ;;
        .*386.*)
            ARCH=386
            ;;
        esac
        PLATFORM="linux-$ARCH"
    ;;
    "Darwin")
        PLATFORM="darwin-amd64"
    ;;
esac

**Comment by ianlancetaylor** [comment]
CC @dmitshur @andybons

**Comment by andybons** [comment]
Looking...

**Comment by andybons** [comment]
@giacomovalenti we never had armv7l uploaded to the golang storage bucket nor https://golang.org/dl. We chose armv6; for [maximum compatibility](https://go.googlesource.com/build/+/master/cmd/release/release.go#149) with all raspberry pi models (#13669). The script you posted even specifies armv6l as the desired architecture.

https://dl.google.com/go/ is the better place to download these, and mirrors https://storage.googleapis.com/golang/, so I’d alter your script to use that instead.

https://dl.google.com/go/go1.14.1.linux-armv6l.tar.gz should work on all 32-bit raspberry pi models.
