### ISSUE TITLE
x/tools/gopls: Suggestion - Offer pre-release versions of gopls to Visual Studio Code extension users

### ISSUE THREAD

**Issue by deoren** [golang/go#38254]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.14.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\deoren\AppData\Local\go-build
set GOENV=C:\Users\deoren\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\deoren\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\deoren\AppData\Local\Temp\go-build172406058=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Ask if it was possible to opt-in to `gopls` pre-release versions similar to how `Visual Studio Code - Insiders` handles PowerShell extension updates:

- PowerShell
  - the stable extension
- PowerShell Preview
  - a semi-regular update of pre-release extension code updates

A toggle within Visual Studio Code to *allow* pre-release versions of `gopls` would be useful, if not offering a separate "preview" extension that offers the latest of stable or pre-release builds of `gopls`.

### What did you expect to see?

Option for installation of pre-release versions.

### What did you see instead?

Offered `gopls` releases appear to be limited to stable releases.

### Other

I understand that the behavior I am describing appears to be centered on Visual Studio Code specifically, but I assume that there would need to be integration of some kind between this official project and the Visual Studio Code extension.

Related issue in that repo:

https://github.com/microsoft/vscode-go/issues/3153

**Comment by stamblerre** [comment]
This is actually something that only needs to be handled on the client side (in this case, VS Code, but it could any editor). We also already have this set up with the Go Nightly extension, as I mentioned on https://github.com/microsoft/vscode-go/issues/3153. Go Nightly is still pretty new, which is why we haven't encouraged people to use it yet, so thanks for filing these issues to ask!

**Comment by deoren** [comment]
> This is actually something that only needs to be handled on the client side (in this case, VS Code, but it could any editor). We also already have this set up with the Go Nightly extension, as I mentioned on [microsoft/vscode-go#3153](https://github.com/microsoft/vscode-go/issues/3153). Go Nightly is still pretty new, which is why we haven't encouraged people to use it yet, so thanks for filing these issues to ask!

Thanks @stamblerre. I can only imagine the number of duplicate requests that you get; thanks for being so kind in your response.
