### ISSUE TITLE
x/website/internal/dl: linux/arm64 port is misreported by File.PrimaryPort as not first class

### ISSUE THREAD

**Issue by ALTree** [golang/go#38258]
Background:  #35593 (all: make linux/arm64 a first-class port). It was accepted, so the linux/arm64 port is a First Class Port.

According to [PortingPolicy § First Class Ports](https://github.com/golang/go/wiki/PortingPolicy#first-class-ports), for a first class port:

> Official binaries are provided 

also it is noted that

> We distribute binaries for other GOOS/GOARCH pairs (other "ports"), but they are not "first class" by this definition

But in the [download page](https://golang.org/dl/) I see that for go 1.13.9 and go 1.14.1 `linux-arm64.tar.gz  |  ARMv8` is listed under "Other Ports", which *I believe* is where we put ports we provide binaries for even if they're not First Class. Since arm64 is first class, it should be in the section above, with the other First Class Ports.

cc @dmitshur

**Comment by dmitshur** [comment]
Thanks for reporting and providing relevant background.

This looks like a bug in the [`golang.org/x/website/internal/dl`](https://golang.org/x/website/internal/dl) package. It maintains a [map of primary ports](https://github.com/golang/website/blob/f2dce3f0e5f72f51d157bbc1bb0766cd0722ed7a/internal/dl/dl.go#L92-L99), and I suspect we need to update that to match #35593.

**Comment by dmitshur** [comment]
Thank you for sending a CL and fixing this issue, @ALTree.
