### ISSUE TITLE
x/tools/gopls: unable to find package

### ISSUE THREAD

**Issue by eric642** [golang/go#38271]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
PS D:\code\go_work\servermap\source\go-apps\src\meeting> go env
set GO111MODULE=off
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\eric\AppData\Local\go-build
set GOENV=C:\Users\eric\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\code\go;D:\code\go_work\go-env\source\libs;
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=C:\mingw64\bin\gcc.exe
set CXX=C:\mingw64\bin\g++.exe
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\eric\AppData\Local\Temp\go-build096526254=/tmp/go-build -gno-record-gcc-switches 
</pre></details>

### What did you do?

**my settings.json:**
 "go.useLanguageServer": true,
    "go.alternateTools": {
        "go-langserver": "gopls"
    },
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true
    },
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
    },
    "gopls": {
        "usePlaceholders": true,
        "enhancedHover": true
    },
    "go.toolsGopath": "D:\\code\\go",
    "go.gopath": "D:\\code\\go_work\\go-env\\source\\libs;D:\\code\\go_work\\servermap\\source\\go-apps",
**my project path** :D:\code\go_work\servermap\source\go-apps\src\meeting
vscode hit :
![image](https://user-images.githubusercontent.com/19191915/78546375-df196180-782f-11ea-9b02-98c8a0978292.png)

**Comment by stamblerre** [comment]
@eric642: Can you please share the output of `gopls -rpc.trace -v check path/to/file.go`?
