### ISSUE TITLE
x/build/cmd/coordinator: include full set of tests (rather than limited trybot set) when a builder is requested via SlowBots

### ISSUE THREAD

**Issue by dmitshur** [golang/go#38279]
Our builder configuration in the `golang.org/x/build/dashboard` package defines a ShouldRunDistTest function that controls what cmd/dist tests are run for each builder.

That function gets one parameter, `isTry bool`, which is whether it is a trybot (pre-submit) run. Most builders are configured to skip some slow tests for trybot runs, in order to speed them up. A full set of tests runs on post-submit builder runs.

When a builder is explicitly requested via the [SlowBots](https://golang.org/wiki/SlowBots) UI, it should run that builder as if it's a post-submit build run and not skip some slow tests that are skipped per normal configuration.

As an example, this would be helpful in [CL 227002](https://golang.org/cl/227002) where its desirable to be able to run a full set of tests before submitting the CL.

/cc @toothrot @cagedmantis @andybons @randall77

**Comment by randall77** [comment]
@cuonglm
