### ISSUE TITLE
x/tools/gopls: fails to link some scheme-less URLs

### ISSUE THREAD

**Issue by heschik** [golang/go#38285]
We use the Relaxed regex from https://github.com/mvdan/xurls to find URLs to linkify. That regex accepts URLs without schemes like `golang.org` rather than `http://golang.org`, which we then parse with `url.Parse`. That works okay for most URLs. (From `url.Parse`: "Trying to parse a hostname and path without a scheme is invalid but may not necessarily return an error, due to parsing ambiguities.").

However, for at least some URLs with colons, e.g. `127.0.0.1:80`, parsing fails ("first path segment in URL cannot contain colon") and the URL is not linkified. `golang.org:8080` works for reasons I haven't dug into.

**Comment by heschik** [comment]
cc @mvdan

**Comment by mvdan** [comment]
This seems like more of a problem with the URL parsing, than xurls per se, no? I'm happy to discuss bugs and enhancements, but I'm sure if there are any here for me :)

As an idea, perhaps try https://golang.org/pkg/net/#SplitHostPort before https://golang.org/pkg/net/url/#Parse. That could help you support `ipv4:port` and `[ipv6]:port`, if changing the behavior of `url.Parse` is not possible.

**Comment by stamblerre** [comment]
Thanks for the advice, @mvdan! You're right - it's strictly a `gopls` issue. I ended up finding https://github.com/golang/go/issues/18824, which I used to fix this.
