### ISSUE TITLE
mutex crash

### ISSUE THREAD

**Issue by caleb-letsgo** [golang/go#38288]
Some function in my application will crash occasionally, specifically on the use of mutex. The general structure of the function is as follows:

```
func test() {
	var chMutex sync.Mutex

	for _, node ;= range nodeList {
		go func() {
			chMutex.Lock()
			……
			chMutex.Unlock()
		}
	}


	chMutex.Lock()
	……
	chMutex.Unlock()
	
	// maybe exit earlier than go routine
}
```

Occasionally it crashes：
panic: runtime error: invalid memory address or nil pointer dereference
sync.(*Mutex).Lock(0x1) C:/Go/src/sync/mutex.go:74 +0x1d

I've tried many versions of golang, and this is a problem. But it's not easy to reproduce.
I wonder if this problem is caused by the fact that chMutex is a local variable and test() exits early while goroutine continues to execute？

**Comment by bcmills** [comment]
What happens when you run your program under the [race detector](https://golang.org/doc/articles/race_detector.html)?

**Comment by randall77** [comment]
> I wonder if this problem is caused by the fact that chMutex is a local variable and test() exits early while goroutine continues to execute？

That in itself would not be a problem. `chMutex` will be allocated on the heap and will survive beyond the lifetime of `test`'s stack frame.

**Comment by caleb-letsgo** [comment]
It's hard to reproduce. It comes out once in a while. You can see this kind of crash on Windows, but not on android.

**Comment by caleb-letsgo** [comment]
I used the win10 system

**Comment by agnivade** [comment]
Hi @caleb-letsgo - could you please answer @bcmills' question [here](https://github.com/golang/go/issues/38288#issuecomment-610455238) ? Thanks.

**Comment by caleb-letsgo** [comment]
Oddly, when I ran the go run-race test.go, there was no output of any race content. I've tested it many times.

`

	ch := make(chan infRes, scount)
	chClosed := false
	var chMutex sync.Mutex

	header := http.Header{}
	// ....header setting

	for _, node := range nodeList {
		go func(node Node, scheme, path string) {
			//...
			r, e := f.requestINF(urlStr, header, ctx)
			if e == nil {
				chMutex.Lock()
				if !chClosed {
					ch <- infRes{node, r}
				}
				chMutex.Unlock()
			} else {
				if r != nil {
					chMutex.Lock()
					if !chClosed {
						ch <- infRes{node, r}
					}
					chMutex.Unlock()
				} else {
					chMutex.Lock()
					if !chClosed {
						ch <- infRes{node, nil}
					}
					chMutex.Unlock()
					if r != nil {
						r.Body.Close()
					}
				}
			}
		}(node, scheme, path)
	}

	// Wait response 
	for i := 0; i < scount; i++ {
		select {
		case res := <-ch:
			r := res.res
			if r == nil {
				err = ErrINFTimeout
				continue
			}

			// The server has responsed, let's anaylys the status code
			switch r.StatusCode {
			case http.StatusSwitchingProtocols:
				//.....
				r.Body.Close()
				chMutex.Lock()
				close(ch)
				chClosed = true
				chMutex.Unlock()
				return
			case http.StatusMovedPermanently:
				//....
				r.Body.Close()
				chMutex.Lock()
				close(ch)
				chClosed = true
				chMutex.Unlock()
				return
			case http.StatusUnauthorized:
				//.....
				r.Body.Close()
				chMutex.Lock()
				close(ch)
				chClosed = true
				chMutex.Unlock()
				return
			case http.StatusNotFound:
				err = ErrHTTP404
				r.Body.Close()
				chMutex.Lock()
				close(ch)
				chClosed = true
				chMutex.Unlock()
				return
			//.....
			}
			r.Body.Close()
		case <-time.After(time.Second * 4):
			//.....
			chMutex.Lock()
			close(ch)
			chClosed = true
			chMutex.Unlock()
			return
		}
	}

	close(ch)
	return

`

**Comment by networkimprov** [comment]
What version of Windows, and what version of Go?

cc @alexbrainman @aclements
@gopherbot add OS-Windows

**Comment by caleb-letsgo** [comment]
It has appeared on the Windows 7 Ultimate and Windows 10 home versions. Go 1.12.17 and go 1.11

**Comment by networkimprov** [comment]
Can you try Go 1.14 or 1.13? 1.12 and earlier are no longer supported.

**Comment by caleb-letsgo** [comment]
I tried Go 1.14 for about a week and the problem never came up.
