### ISSUE TITLE
x/build/dashboard, x/build/app/appengine: add ability to mark builders with a known issue

### ISSUE THREAD

**Issue by dmitshur** [golang/go#38283]
Currently, all builder failures are displayed the same way on the [build.golang.org](https://build.golang.org) dashboard, with a red "fail" text linking to the failure log:

![image](https://user-images.githubusercontent.com/1924134/78605574-d160dd80-7829-11ea-909a-632edf7ca93f.png)

Due to new OS versions, new ports, or new features, there are times when a builder is just being added. It is infeasible to guarantee a builder will report useful results as soon as it is added. Trying to make that the case would cause additional overhead and stress, without a good reason.

We can add a field to the [`dashboard.BuildConfig`](https://pkg.go.dev/golang.org/x/build/dashboard#BuildConfig) struct to mark builders as having a known issue and display such builders on the build.golang.org dashboard in a way that makes it easier to see that it's not a new regression that needs to be investigated anew (by many people looking at build.golang.org).

/cc @toothrot @cagedmantis @andybons @bcmills @danscales

**Comment by dmitshur** [comment]
Here's what I've prototyped locally (note the linux-amd64-staticlockranking builder column displayed in gray):

![image](https://user-images.githubusercontent.com/1924134/78606099-bfcc0580-782a-11ea-9ac4-dd81f139cb3b.png) ![image](https://user-images.githubusercontent.com/1924134/78606173-e1c58800-782a-11ea-8df6-48d90783cc55.png)

I realize that copying the issue number out of a tooltip isn't easy. I'm open to a suggestion how to make it better with the constraint that it shouldn't take up additional space and keeping in mind it doesn't need to be done often.

**Comment by dmitshur** [comment]
A test version is deployed and can temporarily be seen at https://20200406t174434-dot-build-dot-golang-org.appspot.com. It looks like this:

![image](https://user-images.githubusercontent.com/1924134/78608441-ef7d0c80-782e-11ea-87e4-e0f8bc66c1c1.png)

**Comment by bcmills** [comment]
> I realize that copying the issue number out of a tooltip isn't easy. I'm open to a suggestion how to make it better with the constraint that it shouldn't take up additional space and keeping in mind it doesn't need to be done often.

The builder name at the top of the column isn't currently hyperlinked. Perhaps add a hyperlink from the header to the bug?
