### ISSUE TITLE
time: quote original text in error returned by ParseDuration

### ISSUE THREAD

**Issue by bruce-ricard** [golang/go#38295]
I am trying to parse some time strings using the standard library. I am trying to parse the time "for breakfast" (literally). 

### What did you expect to see?
I would expect to see an error message explaining clearly what I did wrong.

### What did you see instead?
> time: invalid duration for breakfast

That's not very helpful.
> time: invalid duration "for breakfast"

would be highly more useful for debugging.

Please think of using quotation marks for [quoted text](https://en.wikipedia.org/wiki/Quotation) when writing natural language like English. 

This part of [the code](https://github.com/golang/go/blob/5bd145413a84be1afa74a82767384d9e224f7069/src/time/format.go#L1404-L1462) in particular, contains quite a few occurrences of quoted text without quotation marks.

I am happy to submit a PR if you agree this is a good change.

**Comment by ianlancetaylor** [comment]
I see that `time.Parse` returns a `time.ParseError` which does quote the value, so, sure, we should do this.  This doesn't need to be a proposal, so retitling.

**Comment by obeyda** [comment]
hi, I would like to help, can i work on this?

**Comment by ianlancetaylor** [comment]
@obeyda Thanks for offering.  In this case it seems like @bruce-ricard is already planning to send in a change, according to the initial bug submission.

**Comment by bruce-ricard** [comment]
@obeyda if you *want* to help and work on it, go ahead. I can help you by reviewing your change if you want to. Let me know.

**Comment by obeyda** [comment]
@bruce-ricard sure thing, I'll start working on this and submit a CL.
