### ISSUE TITLE
flag package misinterprets command line options when a value is missing

### ISSUE THREAD

**Issue by uokuyucu** [golang/go#38296]
### What version of Go are you using (`go version`)?
1.13.8
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go@1.13/1.13.8/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go@1.13/1.13.8/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nf/kms4y6x540vcglvfp76jxygm0000gn/T/go-build732521134=/tmp/go-build -gno-record-gcc-switches -fno-common"

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
- write a simply code with at least two command line arguments with at least one of them requiring an argument.
```
args.InputVersion = flag.String("input_format", "json", "Use json or pb")
args.FilePath = flag.String("filepath", "", "Read from file.")
***
```
- from command line, call this binary with a deliberate mistake;
`my_program --input_format --filepath /a/b/c`

### What did you expect to see?
It should error complaining that input_format was given without a value.

### What did you see instead?
This will parse `-filepath` as the value for input_format option and not giving any errors.

**Comment by ianlancetaylor** [comment]
This is intended behavior.  Otherwise it would be impossible to pass a value starting with `-` as an argument to a command line option.

**Comment by uokuyucu** [comment]
@ianlancetaylor in that case, are we’re supposed to validate and detect the error from parsed value? For this example, I will see the value of inputVersion as “-fileinput” and figure out something is wrong? Does this sound reasonable?

**Comment by ianlancetaylor** [comment]
There is no one solution that is always correct.  If the `-input_format` flag only takes certain values, then it makes sense to look at the value you got and report an error if it is invalid.

**Comment by networkimprov** [comment]
A `flag.IsOpt(arg)` function could tell you whether an arg matches any of the possible flags for this app.

@uokuyucu that might be worth a new proposal issue...

**Comment by ianlancetaylor** [comment]
As it happens, `flag.IsOpt(arg)` is already available as `flag.Lookup(arg) != nil`.

**Comment by networkimprov** [comment]
Aha, missed that in the docs, as it's under `type Flag`.

**Comment by ianlancetaylor** [comment]
Looks like a case where godoc's heuristics have led it astray.
