### ISSUE TITLE
math/big: typo in documentation for Int.Exp

### ISSUE THREAD

**Issue by hallazzang** [golang/go#38304]
https://github.com/golang/go/blob/97711bfd60575b2f51e212b0b5181729597e9091/src/math/big/int.go#L467-L473

On line 469, it says `... x and n are not relatively prime, ...` but there's no `n` in anywhere.
It should be `m` instead.

**Comment by randall77** [comment]
While someone is here, it says both `m>0` and `the sign of m is ignored`. That first part should probably be `m != 0`.

**Comment by hallazzang** [comment]
@randall77 maybe just removing that `(i.e. the sign of  m is ignored)` is fine enough?

**Comment by randall77** [comment]
I guess it all depends on what it actually does for m<0.

**Comment by hallazzang** [comment]
I think leaving `(i.e. the sign of m is ignored)` and change `m > 0` to `m != 0` makes much sense.
