### ISSUE TITLE
time: ???

### ISSUE THREAD

**Issue by Pavil** [golang/go#38302]
### What version of Go are you using (`go version`)?
go version go1.14.1 darwin/amd64

<pre>
$ go version
go version go1.14.1 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
Docs for time package are out of date.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
Docs for time package are out of date.

</pre></details>

### What did you do?
Docs for time package are out of date.

Docs for time package are out of date.

### What did you expect to see?

Docs for time package are out of date.

### What did you see instead?
Docs for time package are out of date.

**Comment by ALTree** [comment]
> **What did you do?**
>
> Docs for time package are out of date.

The sentence you wrote does not answer the question.

> **What did you expect to see?**
> 
> Docs for time package are out of date.

The sentence you wrote does not answer the question.

Please fill in the issue template explaining 
- what part of the doc is out of date
- what did you expect to see

**Comment by ret394** [comment]
> Please fill in the issue template explaining

some info is provided. don't rename titles and add labels in this manner.

**Comment by randall77** [comment]
@ret394: That's part of what we do when we triage incoming issues. See https://github.com/golang/go/wiki/HandlingIssues

There isn't enough info to act on this issue at present. We need more detail as @ALTree asked for.
