### ISSUE TITLE
Go build fails breaks termcaps

### ISSUE THREAD

**Issue by thdelmas** [golang/go#38307]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="linux"
</pre></details>

### What did you do?

go build

### What did you expect to see?

error message and nothing else

### What did you see instead?

error message and nothing else BUT this breaks my termcaps almost each time (espescially when vim is open)

**Comment by ianlancetaylor** [comment]
What do you mean by "this breaks my termcaps"?

**Comment by thdelmas** [comment]
Typically vim is open in xterm tab and my go compil in another when go compil fails and I return in vim, the display is fully changed like another encoding or just bad terncaps config since vim is based on it
I have check all my termcaps config and cannot reproduce the situation better close this issue, could come from xterm, or a bad exit value of go build that is not handle correctly
