### ISSUE TITLE
x/playground: upgrade runsc version

### ISSUE THREAD

**Issue by prattmic** [golang/go#38317]
The root playground fs contains a `__runsc_containers__` entry, which was removed from runsc in July 2019: https://play.golang.org/p/_bvQjtzhkuR, https://github.com/google/gvisor/commit/04cbb13ce9b151cf906f42e3f18ce3a875f01f63

Downloading the runsc binary from https://go.googlesource.com/playground/+/refs/heads/master/sandbox/cloud-init.yaml#15, `runsc --version` is not supported. This flag was added to runsc in April 2019: https://github.com/google/gvisor/commit/7543e9ec2043af7d071373aeec04b92a98051087

Together, these make it seem like the runsc build is quite old? Once the new playground is stable, we'll want to be sure to update runsc regularly (official releases: https://github.com/google/gvisor/releases) to keep up with security fixes.

**Comment by toothrot** [comment]
Thanks, @prattmic!

Tagging #25224 for context.

**Comment by toothrot** [comment]
Deployed. We'll now stay up to date when we restart our sandbox instances.
