### ISSUE TITLE
x/tools/go/loader: TestStdlib is failing on tip because TestTempFile was moved

### ISSUE THREAD

**Issue by dmitshur** [golang/go#38318]
[CL 226877](https://golang.org/cl/226877) has moved the function `TestTempFile` from `io/ioutil` internal test to external test. `TestStdlib` is now failing:

```
$ gotip test
[...]
--- FAIL: TestStdlib (10.54s)
    stdlib_test.go:103: package "io/ioutil" has no func "TestTempFile"
    stdlib_test.go:117: GOMAXPROCS:            8
    stdlib_test.go:118: #Source lines:         1303424
    stdlib_test.go:119: Load/parse/typecheck:  10.070588601s
    stdlib_test.go:120: #MB:                   1068
FAIL
exit status 1
FAIL	golang.org/x/tools/go/loader	19.542s
```

Spotted on [build.golang.org](https://build.golang.org/?repo=golang.org%2fx%2ftools).

/cc @ianthehat @matloob per [owners](https://dev.golang.org/owners).

**Comment by stamblerre** [comment]
Out of curiosity, why wasn't this issue caught in https://golang.org/cl/226877? I thought the tools TryBots had been configured to run on changes in the Go repo?

**Comment by dmitshur** [comment]
@stamblerre It's because `TestStdlib` is [skipped](https://github.com/golang/tools/blob/0037cb7812fa1343616f77d5e8457b530a8f5bcc/go/loader/stdlib_test.go#L34-L36) in -short mode. Only longtest post-submit builders run in non-short test mode.

**Comment by stamblerre** [comment]
Ah, thanks for clarifying!
