### ISSUE TITLE
GOPROXY problem

### ISSUE THREAD

**Issue by vic85290** [golang/go#38312]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/Téléchargements/evilginx2/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build517475408=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.14.1 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.14.1
uname -sr: Linux 5.4.0-kali4-amd64
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2020.1
Codename:	kali-rolling
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Debian GLIBC 2.29-10) stable release version 2.29.
</pre></details>

### What did you do?
root@kali:~/Téléchargements/evilginx2# go get -u github.com/kgretzky/evilginx2               

### What did you see instead?

go: golang.org/x/sys upgrade => v0.0.0-20200408040146-ea54a3c99b9b                                                                           
go: golang.org/x/net upgrade => v0.0.0-20200324143707-d3edc9973b7e                                                                           
go: gopkg.in/ini.v1 upgrade => v1.55.0                                                                                                       
go: golang.org/x/text upgrade => v0.3.2                                                                                                      
go: github.com/mattn/go-isatty upgrade => v0.0.12                                                                                            
go: github.com/cenkalti/backoff/v4 upgrade => v4.0.2                                                                                         
go: golang.org/x/crypto upgrade => v0.0.0-20200406173513-056763e48d71                                                                        
go: github.com/gorilla/mux upgrade => v1.7.4                                                                                                 
go: gopkg.in/yaml.v2 upgrade => v2.2.8                                                                                                       
go: gopkg.in/square/go-jose.v2 upgrade => v2.4.1                                                                                             
go: github.com/tidwall/pretty upgrade => v1.0.1
go: github.com/pelletier/go-toml upgrade => v1.7.0
go: github.com/mattn/go-colorable upgrade => v0.1.6
go: github.com/spf13/cast upgrade => v1.3.1
go: github.com/miekg/dns upgrade => v1.1.29
go: github.com/spf13/afero upgrade => v1.2.2
go: github.com/tidwall/gjson upgrade => v1.6.0
go: github.com/spf13/jwalterweatherman upgrade => v1.1.0
go: github.com/fsnotify/fsnotify upgrade => v1.4.9
go: github.com/spf13/pflag upgrade => v1.0.5
go: github.com/mitchellh/mapstructure upgrade => v1.2.2
github.com/elazarl/goproxy
/root/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20200315184450-1f3cb6622dad/ctx.go:46:2: not enough arguments to return
/root/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20200315184450-1f3cb6622dad/ctx.go:46:12: ctx.proxy undefined (type *ProxyCtx has no field or method proxy, but does have Proxy)
/root/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20200315184450-1f3cb6622dad/ctx.go:50:5: ctx.proxy undefined (type *ProxyCtx has no field or method proxy, but does have Proxy)
/root/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20200315184450-1f3cb6622dad/ctx.go:62:8: ctx.proxy undefined (type *ProxyCtx has no field or method proxy, but does have Proxy)
/root/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20200315184450-1f3cb6622dad/https.go:76:69: unknown field 'proxy' in struct literal of type ProxyCtx (but does have Proxy)
/root/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20200315184450-1f3cb6622dad/https.go:199:77: unknown field 'proxy' in struct literal of type ProxyCtx (but does have Proxy)
/root/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20200315184450-1f3cb6622dad/proxy.go:105:70: unknown field 'proxy' in struct literal of type ProxyCtx (but does have Proxy)

**Comment by ret394** [comment]
> but does have Proxy)

what does this mean?

no https://github.com/elazarl/goproxy/releases

**Comment by bcmills** [comment]
The tags in the `github.com/elazarl/goproxy` repo are non canonical [semantic versions](https://semver.org), so the `go` command does not use them. Thus, you're getting the latest commit (https://github.com/elazarl/goproxy/commit/1f3cb6622dad84fad2c5416d502fe4c2c2dce48b) instead of the highest tag (`v1.1`), and the package you're building appears to be broken at that commit.

You'll need to file an issue with http://github.com/elazarl/goproxy; as far as I can tell this has nothing to do with the Go toolchain or standard library.
