### ISSUE TITLE
Implicit cast of named pointer types on return

### ISSUE THREAD

**Issue by Sebi2020** [golang/go#38310]
### What version of Go are you using (`go version`)?

<pre>
go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code>
</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sebi/.cache/go-build"
GOENV="/home/sebi/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/sebi/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/go-1.14"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build548338872=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
https://play.golang.org/p/IejMIwRoVTG

I declared a named pointer type: `type IntPtr *int` that is implicitly casted by go. 

### What did you expect to see?
Consistent behaviour with Pointer and Non-Pointer types. No implicit casting.

### What did you see instead?
Go implicitly casts the named pointer type but does not allow implicit casts of named non-Pointer types. (See example on playground. Comment out if you wish to see the compiler error for non-Pointer types.)

**Comment by randall77** [comment]
This is intentional. `int` is a defined type (aka named type), but `*int` is not. Implicit casts are allowed from a type that is not defined to one that is.
