### ISSUE TITLE
cmd/go: install fails to detect changes in build flags when deciding whether or not to update a binary

### ISSUE THREAD

**Issue by gopherbot** [golang/go#3832]
by **douglas@mayle.org**:

<pre>Before filing a bug, please check whether it has been fixed since the
latest release. Search the issue tracker and check that you're running the
latest version of Go:

Run &quot;go version&quot; and compare against
<a href="http://golang.org/doc/devel/release.html">http://golang.org/doc/devel/release.html</a>  If a newer version of Go exists,
install it and retry what you did to reproduce the problem.

Thanks.

What steps will reproduce the problem?
If possible, include a link to a program on play.golang.org.
1. Create the directory $GOHOME/src/install_error and create the two files:
cat &gt;main_notag.go &lt;&lt; EOF
// +build !tag

package main

import &quot;fmt&quot;

func main() {
  fmt.Println(&quot;No tag build.&quot;)
}
EOF

cat &gt;main_tag.go &lt;&lt; EOF
// +build tag

package main

import &quot;fmt&quot;

func main() {
  fmt.Println(&quot;Tag build.&quot;)
}
EOF

2. go install install_error
3. go install -tags tag install_error

What is the expected output?
&quot;Tag build.&quot;

What do you see instead?
&quot;No tag build.&quot;

Which compiler are you using (5g, 6g, 8g, gccgo)?
This is darwin 32-bit, which I guess makes it 6g?  I installed go from source

Which operating system are you using?
OSX

Which version are you using?  (run 'go version')
go version weekly.2012-03-27 +695f65745351

Please provide any additional information below.
Whenever you change source files, go install will correctly update the binary on disk. 
If you change build tags, however, even though it might make for a change in binary, the
install is abandoned.</pre>

**Comment by rsc** [comment]
The general case of build flags like -gcflags is still not handled, but the case you gave of install tags is fixed for Go 1.5.
