### ISSUE TITLE
go.dev: pkg.go.dev should work for e.g. git.sr.ht

### ISSUE THREAD

**Issue by ptman** [golang/go#38326]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/git.sr.ht/~f4814n/matrix
 
### What is your user agent? 

Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0

### Screenshot

404 Not Found
 
### What did you do?

Navigated to the page
 
### What did you expect to see?
 
Something like https://godoc.org/git.sr.ht/~f4814n/matrix
 
### What did you see instead?

404 Not Found

**Comment by dmitshur** [comment]
It does work for that package. See https://go.dev/about#adding-a-package.

**Comment by ptman** [comment]
Mea culpa. Maybe in that case the 404 page should instruct in how to fix it, or even try it automatically?

**Comment by dmitshur** [comment]
It does have instructions. See https://github.com/golang/go/issues/36986#issuecomment-581607196.

Perhaps you overlooked them?

Issue #37002 is tracking automatic fetching.

**Comment by ptman** [comment]
Clearly. Thank you
