### ISSUE TITLE
Cannot scan my query

### ISSUE THREAD

**Issue by Serhioromano** [golang/go#38327]
I have a query with an unpredictable number of columns. Here is my query.

```sql
SHOW TABLE STATUS LIKE '%'
```

I can see what fields it returns but I do not need all of them. I cannot select only some of them. And from one MySQL version to another results may vary.

In your Scan function you have

https://github.com/golang/go/blob/98b6c6aca6fd4185f97dc40137707f4d8df8aa7c/src/database/sql/sql.go#L3072-L3074

It looks like an unnecessary limitation. Why not just populate names that are there and sleep the rest? Why does it have to conform?

Is it possible somehow to get a result to an interface without defining every column beforehand? Just get what is there and then work with it.

**Comment by thehowl** [comment]
You can read the number of fields using [`rows.Columns()`](https://golang.org/pkg/database/sql/#Rows.Columns). So you can do the following:

```go
type fakeScanner struct{}
func (f fakeScanner) Scan(interface{}) error { return nil }

args := make([]interface{}, len(rows.Columns()))
// put fakeScanner as default for all args
for i := 0; i < len(args); i++ {
	args[i] = fakeScanner{}
}
// specify the args you want to store
var b string
args[4] = &b
err := rows.Scan(args...)
```

Of course, you might say this is a bit of an ugly solution, and I agree. So you can use [sqlx's Get function](https://jmoiron.github.io/sqlx/#getAndSelect) together with a struct where you specify only the fields that interest you, and then you use the [Unsafe](https://jmoiron.github.io/sqlx/#safety) method to ignore unused columns.

Spitting an error when there is a mismatch between columns and scans is helpful to immediately identify places where we might have forgotten to add a scan destination or the column. It has personally occurred to me many times and I've always found it quite handy for the general case. In exceptions like yours, there are existing workarounds, so I think it's best to keep it the way it is.

**Comment by Serhioromano** [comment]
How do I get access to rows? In the other topic, they said that result is a stream and we do nтещ know the amount or records there.

Here is my current code. I get this result with `db.Query()`

```go
for result.Next() {
		var fld = Field{}
		err = result.Scan(
			&fld.COLUMN_NAME,
			&fld.COLUMN_DEFAULT,
			&fld.IS_NULLABLE,
			&fld.DATA_TYPE,
			&fld.COLUMN_TYPE,
			&fld.EXTRA,
			&fld.COLUMN_KEY,
		)
		if err != nil {
			panic("Scan tables" + err.Error())
		}

		out = append(out, fld)
	}
```

How do I get access to .Columns()?

**Comment by thehowl** [comment]
We don't know the amount of records (rows), but we do know the amount of columns. In your case, you would access it using `result.Columns()` (because it is of type *sql.Rows).

Here is a working program showing it:

https://gist.github.com/thehowl/f2c3d9e1a7ae99323a4359838bf63462

**Comment by Serhioromano** [comment]
> We don't know the amount of records (rows), but we do know the amount of columns. In your case, you would access it using `result.Columns()` (because it is of type *sql.Rows).
> 
> Here is a working program showing it:
> 
> https://gist.github.com/thehowl/f2c3d9e1a7ae99323a4359838bf63462

This example is so revealing! Thank you. I've learned a log about GO in general и this example.
