### ISSUE TITLE
x/tools/gopls: change behavior of dependency upgrade suggestions

### ISSUE THREAD

**Issue by stamblerre** [golang/go#38339]
Some users have mentioned that the upgrade code lenses are a little invasive because they are shown per-line. Here are some general thoughts / ideas for how to handle this:

- Don't show upgrades for pseudoversions? Or only for pseudoversions older than some amount of time (1 month? more?).
- Offer upgrades as code actions instead of code lenses. The "upgrade all" could still be a code lens, but this way we could offer more granular updates. Someone may not want to update to a new major version, but they may want to update to a new minor or patch release - code actions give more options.

**Comment by hyangah** [comment]
Or is there any way to disable some of the code lenses?
As we add more code lenses, we will have more diverse opinions about them.

**Comment by stamblerre** [comment]
> Or is there any way to disable some of the code lenses?

There is a `"editor.codeLens"` setting, but I don't think you can configure it per-code lens.

**Comment by stamblerre** [comment]
We now have per-code lens configuration. While I would like to eventually make this improvement, I don't think it's necessary for v1.0.

**Comment by stamblerre** [comment]
https://golang.org/cl/271297 removed the per-require upgrade code lenses, so we should prioritize adding the upgrades as diagnostics paired with suggested fixes. I think they should be treated similarly to how fillstruct works in Go files--we don't want to use a visible underlined diagnostic since it may bother the user visually (if they specifically chose a lower version), but when they click on the require, they should be prompted to upgrade it.

/cc @heschik

**Comment by nopyhe** [comment]
It's not a good idea to drop per-dependency update notification when the alternative method not ready. I also have to stay on gopls v0.5.3.

**Comment by stamblerre** [comment]
The "Upgrade all dependencies" code lens still appears at the top of the `go.mod` file. We will be improving the UX of the per-dependency upgrade feature, and it was removed for the reasons described in the [release notes](https://github.com/golang/tools/releases/tag/gopls%2Fv0.5.4).

**Comment by nopyhe** [comment]
@stamblerre Can we have a code lens like "Check for upgrade" to trigger upgrade suggestions for each require in a go.mod file as before.
I don't want to click every require to check whether it can be upgraded or not when I need to upgrade some of them.

**Comment by stamblerre** [comment]
Thanks for the suggestion--we will consider that option. Would the "upgrade all direct dependencies" code lens work for you?

**Comment by nopyhe** [comment]
@stamblerre Not really. I want to keep all my dependencies up to date. But there are some reasons I can't upgrade all of them. For example, some dependencies have a  breaking change and it needs some time to handle, which is not the top priority.

**Comment by stamblerre** [comment]
That's fair, but it should still make it a little simpler to upgrade all dependencies and then revert the ones you don't want to upgrade. I think the per-require code action will work well for most cases, because it will allow us to offer multiple versions, but I do also like the idea of a "check for updates" command that we could expose as a code lens.

**Comment by xiegeo** [comment]
I would like to add a user experience report.

I don't find the per line code lenses invasive. In fact, it's the most useful feature. I only goto the go.mod file to check for potential upgrades.

I work on some projects that suffer from upstream breaking Semitic Versioning, but if go tooling makes keeping certain versions back easier, more developers will feel freer to break SV. This will end up making the development experience worth.

"but it should still make it a little simpler to upgrade all dependencies and then revert the ones you don't want to upgrade. "
Unfortunately, not. Upgrade all can error out with compatibility errors. It's more "I can't" than "I won't".

If "Upgrade direct dependencies" is a useful workflow, that should be added to the command line tooling first instead as a gopls only feature.

**Comment by stamblerre** [comment]
We reworked the user experience in gopls/v0.6.5, and you can see an explanation of the new workflow in the [release notes](https://github.com/golang/tools/releases/tag/gopls%2Fv0.6.5). Closing this issue as a result.
