### ISSUE TITLE
unicode/utf8 returns that 0x00 is valid

### ISSUE THREAD

**Issue by madeken** [golang/go#38336]
`utf8.Valid([]byte{108, 0, 108})` returns `true`  yet almost universally a 0x00 in a string is not considered valid utf8 and passing it to external systems will cause issues (e.g. postgres throws "invalid byte sequence for utf8"), which makes it difficult to sanitize user input.

**Comment by bcmills** [comment]
`utf8.Valid` is not wrong here. U+0000 is a valid UTF-8 character. (Search for `U+0000` in https://tools.ietf.org/html/rfc3629.)
