### ISSUE TITLE
cmd/go: failed to fetch private repo with multiple error situations

### ISSUE THREAD

**Issue by xrfang** [golang/go#38345]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xrfang/.cache/go-build"
GOENV="/home/xrfang/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE="git2.likeit.cn"
GONOPROXY="git2.likeit.cn"
GONOSUMDB="git2.likeit.cn"
GOOS="linux"
GOPATH="/home/xrfang/go"
GOPRIVATE="git2.likeit.cn"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build271669497=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I tried to migrate a project to use go modules: create empty `go.mod` file in the project source dir, then run `go build ./...`.

### What did you expect to see?
The project should be built successfully.

### What did you see instead?

Got problem described here: https://stackoverflow.com/questions/60341591   I tried to ask new question on SO but get down voted.    Then, I did the following test:

```
$ go get -v git2.likeit.cn/go/likesync
unrecognized import path "git2.likeit.cn/go/likesync": https fetch: Get "https://git2.likeit.cn/go/likesync?go-get=1": dial tcp 192.168.90.231:443: connect: connection refused
```
i.e. Go insist to get the repo via HTTPS but the private repo only provide HTTP.  The problem was reported in #37943.  However it re-appeared, despite the fact that all env was set according to that issue.

Then, I created an empty mod in that directory:

```
$ go mod init test
go: creating new go.mod: module test
$ go get -v git2.likeit.cn/go/likesync
get "git2.likeit.cn/go/likesync": found meta tag get.metaImport{Prefix:"git2.likeit.cn/go/likesync", VCS:"git", RepoRoot:"http://git2.likeit.cn/go/likesync.git"} at //git2.likeit.cn/go/likesync?go-get=1
get "git2.likeit.cn": found meta tag get.metaImport{Prefix:"git2.likeit.cn", VCS:"git", RepoRoot:"http://git2.likeit.cn//.git"} at //git2.likeit.cn/?go-get=1
get "git2.likeit.cn/go": found meta tag get.metaImport{Prefix:"git2.likeit.cn/go", VCS:"git", RepoRoot:"http://git2.likeit.cn/go/.git"} at //git2.likeit.cn/go?go-get=1
go: git2.likeit.cn/go/likesync upgrade => v1.5.3
go get: git2.likeit.cn/go/likesync@v1.5.3: parsing go.mod:
	module declares its path as: git.likeit.cn/go/likesync
	        but was required as: git2.likeit.cn/go/likesync
```

This time, it does not insist on HTTPS, but found an **old location** of the repo.   There is a **likesync** package under `git.likeit.cn/go/likesync`, in that repo, there **indeed** has a go.mod file states:  `module git.likeit.cn/go/likesync`.   This repo was abandoned, albeit still accessible.

 In the new repo **git2**.likeit.cn/go/likesync, their is **no** go.mod file.   My problem is, **WHY** and **HOW** does the go build system find `git.likeit.cn` as the project ONLY refer to `git2.likeit.cn`??

**Comment by andybons** [comment]
@bcmills @matloob @jayconrod

**Comment by bcmills** [comment]
Are you sure that the repository at http://git2.likeit.cn/go/likesync.git _at the commit tagged `v1.5.3`_ does not have a `go.mod` file declaring `module git.likeit.cn/go/likesync`?

**Comment by xrfang** [comment]
@bcmills I will verify that tomorrow. However, the key problem is even if we have a go.mod file at git.likeit.cn/go/likesync@1.5.3, it does not explain **why** the go command try to find the module at git.likeit.cn?? in the entire project, there is only reference to **git2**.likeit.cn?

This is unbelivable... or, is it sooo intelligent to check git\d*.likeit.cn??

**Comment by bcmills** [comment]
Nothing in that `go` command output indicates that it ever attempted to fetch anything from `git.likeit.cn`. The reported error is a path mismatch for the `go.mod` file found for git<b>2</b>.likeit.cn/go/likesync@v1.5.3.

**Comment by bcmills** [comment]
Per [`go help get`](https://golang.org/cmd/go/#hdr-Module_queries):
> By default, get looks up the latest tagged release version, such as v0.4.5 or v1.2.3. If there are no tagged release versions, get looks up the latest tagged pre-release version, such as v0.0.1-pre1. If there are no tagged versions at all, get looks up the latest known commit.

**Comment by xrfang** [comment]
@bcmills OK.  So the behavior is by design.  Shall I close this ticket, or is there anything to investigate, given the different behavior of not having a go.mod, and having a go.mod?

**Comment by bcmills** [comment]
I don't think there is anything more to do here, so closing. Please do let us know if you run into other issues, though. (We know that the documentation & test coverage for private repos still needs some polish.)
