### ISSUE TITLE
x/build: closing a PR leaves the Gerrit CL open

### ISSUE THREAD

**Issue by stamblerre** [golang/go#38347]
Another issue I noticed because of https://github.com/golang/tools/pull/218. The underlying PR has been closed by the contributor, but the Gerrit CL is still open (https://golang.org/cl/225297). It would be cool if the closing of the PR would trigger the CL to be abandoned in Gerrit.

**Comment by ALTree** [comment]
This was reported as #23850.

**Comment by stamblerre** [comment]
Ah, my bad, I should've check. Thanks for letting me know!

**Comment by stamblerre** [comment]
Duplicate of #23850
