### ISSUE TITLE
x/tools/gopls: undeclared types after adding new declarations in test file via git merge

### ISSUE THREAD

**Issue by stamblerre** [golang/go#38358]
This needs a regression test and a fix. Reported as a result of a git merge that brought in new type declarations in a new test file. This is in an in-package test, in case that matters.

**Comment by pjweinb** [comment]
Do we have a reproducible example of this?

**Comment by stamblerre** [comment]
I do have a regression test in progress that we can probably build off of: https://go-review.googlesource.com/c/tools/+/233657.
