### ISSUE TITLE
x/sys/unix: TestOpenat2 failing on ARM builders

### ISSUE THREAD

**Issue by bcmills** [golang/go#38357]
`TestOpenat2`, added in [CL 227280](https://golang.org/cl/227280), is failing with `operation not permitted` on multiple ARM builders:
https://build.golang.org/log/93bf4826da2c7a6f4ae3d423435e773d9a5783c4
https://build.golang.org/log/0e555617f2a3b124e7604af976cf4f56d182b74a

Either the test should be fixed ASAP or the CL should be reverted.

CC @kolyshkin @tklauser @ianlancetaylor for `x/sys`, @andybons for builder status

**Comment by andybons** [comment]
Let’s just revert.

**Comment by kolyshkin** [comment]
Can't we just revert a test case?

**Comment by bcmills** [comment]
If the test is supposed to verify the functionality, then a falling test indicates that either the functionality is broken, or the test doesn't accurately describe the conditions under which it is supposed to work.

Either way, there's little harm in reverting the change: it can be re-submitted with a fix once someone figures out why the test is falling.
