### ISSUE TITLE
trimpath should support two delimiter ; and : for windows and linux respectively

### ISSUE THREAD

**Issue by jansoneo** [golang/go#38350]
### What version of Go are you using (`go version`)?

<pre>
go version go1.14.2 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/xxx/xxxx/goProject/bin"
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xxx/goProject:/home/xxx/xxxx/golang-lib:/home/xxx/xxxx/golang-lib"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build036860533=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What question?

I use `go build -gcflags=all=-trimpath=$GOPATH-asmflags=all=-trimpath=$GOPATH-ldflags "-w -s" main.go` to remove the prefix.

 I expect to see that this operation should have the same effect in linux as in windows but unfortunately,  it works in windows and not in linux.

Further, I find source code about it in `$GOROOT//src/cmd/internal/objabi/line.go + 42`,  it support only ";" as delimiter so only works in windows platform.

**Comment by bcmills** [comment]
The `-trimpath` compiler flag is mostly intended to support the `cmd/go` `-trimpath` flag, which needs no arguments. Could you give some more detail about your use-case? (Why do you want to trim only GOPATH?)

**Comment by gityjx** [comment]
> The `-trimpath` compiler flag is mostly intended to support the `cmd/go` `-trimpath` flag, which needs no arguments. Could you give some more detail about your use-case? (Why do you want to trim only GOPATH?)

Thanks for your answer, the case is: When I use pprof to analysis my program, I need to know which line (in source code) triggers my issue(cpu or heap etc.), but the source code is not found if the code is built in another computer with a different gopath. So I have to remove the specific gopath to make my program can be analysis by using pprof with source code in any computer.

**Comment by bcmills** [comment]
In general you need three steps to resolve paths from pprof:
1. Obtain the path to the package in which the error occurred.
2. Map that path to a filesystem directory.
3. Open the indicated file within that directory.

Step (1) should work with the `cmd/go` `-trimpath` flag, not just selective use of the `cmd/compile` `-trimpath` flag in `-gcflags`. Step (2) in general requires version information (typically from knowing the main module used for the build).

So I still don't see how the `go build -gcflags=…` approach provides any benefit over `go build -trimpath`. Could you elaborate?

**Comment by jansoneo** [comment]
thank you, `go build -trimpath`  indeed is better than `go build -gcflags=…` for my case, the reason that I use  `go build -gcflags=…`  innstead of  `go build -trimpath`  is that I don't know  `go build -gcflags=…` can be replaced by  `go build -trimpath`.
