### ISSUE TITLE
x/build/cmd/coordinator: doesn't seem to be reporting the right elapsed time for aix-ppc64 trybot

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#38363]
When I look at https://farmer.golang.org/try?commit=37ab01eb right now, at Fri 10 Apr 2020 06:48:51 PM UTC, I see

```
aix-ppc64 | (running) | aix-ppc64 rev 37ab01eb (trybot set for Id0c34c2); running; http://power8-aix-host1 reverse peer power8-aix-host1/140.211.9.26:52500 for host type host-aix-ppc64-osuosl, 2h37m19s ago ...
                      |   2020-04-10T16:39:15Z finish_write_go_src_tar after 5.48s
                      |   2020-04-10T16:39:15Z make_and_test
                      |    2020-04-10T16:39:15Z make src/make.bash
                      |  +7692.8s (now)
```

The timestamps are more than 50,000 seconds ago, not 7692 seconds ago.

Why do we see the wrong elapsed time?

And what is happening with the AIX builder?

Thanks.

CC @dmitshur

**Comment by dmitshur** [comment]
> The timestamps are more than 50,000 seconds ago

Which timestamps are you referring to? The ones I see in the snippet above are from 3~ hours ago:

```Go
t, err := time.Parse(time.RFC3339, "2020-04-10T16:39:15Z")
if err != nil { panic(err) }
fmt.Println(time.Since(t))
// Output: 3h5m32.054424s
```

For context, `aix-ppc64` is a reverse builder and there is only one instance. The coordinator was redeployed 3.5 hours ago ([farmer.golang.org](https://farmer.golang.org) displays "Uptime 3h35m55s."). It seems https://farmer.golang.org/try?commit=37ab01eb was the first trybot run that picked up the `aix-ppc64` builder, but the builder is stuck on:

```
Building Go cmd/dist using /opt/freeware/lib/golang. (go1.13 aix/ppc64)
Building Go toolchain1 using /opt/freeware/lib/golang.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
```

It might be worth canceling that trybot run (by deleting the Run-TryBot+1 vote) and letting it try again, perhaps the next time it won't get stuck. But if that doesn't help, then there must be something up with the builder.

/cc @trex58

**Comment by ianlancetaylor** [comment]
I'm sorry, you're right, I did misread the timestamps.  I'll close this issue.

**Comment by panjf2000** [comment]
Again, it gets stuck in the same place.
https://farmer.golang.org/try?commit=efd5d44c

**Comment by panjf2000** [comment]
```
Building Go cmd/dist using /opt/freeware/lib/golang. (go1.13 aix/ppc64)
Building Go toolchain1 using /opt/freeware/lib/golang.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
```
