### ISSUE TITLE
Go uses invalid PKG_CONFIG

### ISSUE THREAD

**Issue by ydnar** [golang/go#38361]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ydnar/Library/Caches/go-build"
GOENV="/Users/ydnar/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/ydnar/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/ydnar/development/REDACTED/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="/usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6g/1gng3zts0t39s_qbtt7p0wsc0000gn/T/go-build410649026=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

`go test ./...` fails when building a `cgo` package because the `go` binary was built with an invalid value in `PKG_CONFIG`: https://github.com/Homebrew/brew/issues/5068#issuecomment-612121846

Should Go preserve the `PKG_CONFIG` value it was built with, when it could be running on a completely different system that doesn’t have that path?

```shell
$ go env PKG_CONFIG
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config
```

Given that Homebrew’s `pkg-config` shim is only valid at build time, not runtime, does it make sense to bake-in and use the `PKG_CONFIG` variable?

### What did you expect to see?

`cgo` using the locally-installed `pkg-config`.

### What did you see instead?

`cgo` tried to use the nonexistent `pkg-config` at the baked-in `PKG_CONFIG` environment variable.

**Comment by ianlancetaylor** [comment]
This isn't a problem with the Go distribution.  The Go distribution's default for `PKG_CONFIG` is simply `pkg-config`.  Your installation was built with the environment variable `PKG_CONFIG` set to a full path, and the Go build has preserved that value.  That is intended behavior.  If you don't want that behavior, you should ask whoever built your installation to change their build procedure.

In the meantime you can always set the environment variable `PKG_CONFIG` to override the default value.

**Comment by ydnar** [comment]
> If you don't want that behavior, you should ask whoever built your installation to change their build procedure.

Sure, no problem: https://github.com/Homebrew/brew/pull/7321

**Comment by ydnar** [comment]
While this may be intended behavior, baking the value of a generically-named environment variable into Go at build time for a critical tool like `pkg-config` isn’t a great idea.

Maybe for Go 2 rename it to `GO_PKG_CONFIG` so it won’t be accidentally clobbered?

**Comment by ianlancetaylor** [comment]
It seems to me that it's the right default for individual builds.  People who build installations for distribution are expected to take more care.  The full set of environment variables that are treated this way can be found in src/make.bash.

But please free to open an issue for changing the way that we handle these environment variables when building a release.  This kind of handling is separate from the Go 1 compatibility process and would not have to wait for Go 2.
