### ISSUE TITLE
Implemented interface results in invalid memory or nil pointer derefernce

### ISSUE THREAD

**Issue by amitlevy21** [golang/go#38367]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
I updated to `go1.14.2` and it still happends

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Elad\AppData\Local\go-build
set GOENV=C:\Users\Elad\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Elad\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\Elad\Desktop\amit\test\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Elad\AppData\Local\Temp\go-build201605738=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

Here is a minimal runnable program:
[test.zip](https://github.com/golang/go/files/4463043/test.zip)

I ran `go test ./ride`
The issue happens in `ride/route_test.go`:
```go
func TestAddStation(t *testing.T) {
	stationID := int64(2)
	n := network.NewNetwork()
	r := route{stationsIds: []int64{1, 2, 3}}
	p := &n // inlining this did not help
	// if err := p.AddStation(stationID); err != nil {
	// 	t.Errorf("DEBUG: %s", err)
	// }
	if err := r.AddStation(stationID, p); err != nil {
		t.Errorf("error while adding station: %s", err)
	}
	if r.stationsIds[len(r.stationsIds)-1] != stationID {
		t.Errorf("station id %d was not added", stationID)
	}
}
```
Uncommenting the commented lines fixes the issue for some reason.

`ride/route.go` contains a struct `route` which has a method `AddStation`, which receives an interface `stationAdder`, which contains a function with the name `AddStation`. 
`network/network.go` has a struct `Network` which implements `stationAdder`, the test `TestAddStation` compiles but causes the issue.

### What did you expect to see?

```
$ go test ./ride
ok      example.com/test/ride   0.544s
```

### What did you see instead?
```
$ go test ./ride
--- FAIL: TestAddStation (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x50e2b5]

goroutine 6 [running]:
testing.tRunner.func1.1(0x52f0a0, 0x658350)
        c:/go/src/testing/testing.go:940 +0x2fc
testing.tRunner.func1(0xc000110120)
        c:/go/src/testing/testing.go:943 +0x400
panic(0x52f0a0, 0x658350)
        c:/go/src/runtime/panic.go:969 +0x174
example.com/test/ride.(*route).AddStation(0xc000037f50, 0x2, 0x584480, 0xc00002c520, 0x4d1716, 0x620500)
        C:/Users/Elad/Desktop/amit/test/ride/route.go:28 +0x95
example.com/test/ride.TestAddStation(0xc000110120)
        C:/Users/Elad/Desktop/amit/test/ride/route_test.go:16 +0xf4
testing.tRunner(0xc000110120, 0x563578)
        c:/go/src/testing/testing.go:991 +0xe3
created by testing.(*T).Run
        c:/go/src/testing/testing.go:1042 +0x35e
FAIL    example.com/test/ride   0.353s
FAIL
```

**Comment by ALTree** [comment]
I'm a little confused by this bug report. The test is throwing because here in `(r *route) AddStation`:

```
if err := a.AddStation(stationID); !strings.Contains(err.Error(), "exist") {
```

you are not checking whether `err` is `nil` before calling `err.Error()`. If you replace the line with

```
if err := a.AddStation(stationID); err != nil && !strings.Contains(err.Error(), "exist") {
```

the test no longer panics. The reason the test doesn't panic when you comment this line in the test:

```
if err := p.AddStation(stationID); err != nil {
```

is that `p` and `n` are pointers to the same `route`, so the `p.AddStation(stationID)` call adds a `stationID` to both `n` and `p` (they're the same, really), so later in the test, this check fails:

```
if err := checkStationToItself(last, stationID); err != nil {
	return err
}
```

(err is `station 2 already exist`), which means that `AddStation` exists before reaching the erroneous line I pointed out above.

Overall, it seems like the program is behaving as expected.

**Comment by amitlevy21** [comment]
@ALTree You're right. I was trying to find the problem in `a.AddStation` instead.
Thank you for your time and detailed explanation!
