### ISSUE TITLE
crypto/x509: CGO_ENABLED=0 x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by kotyara85** [golang/go#38365]
### What version of Go are you using (`go version`)?
go version go1.12.14 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?
We're using akamai zta, which means the path is our cli tool -> sso -> website

### What did you expect to see?
Downloaded page

### What did you see instead?
x509: certificate signed by unknown authority

This only works if CGO_ENABLED=1, but we need to build darwin & windows images inside linux docker image

Is there a way to avoid this error?

InsecureSkipVerify: false won't fix this issue, cause it won't be able to pass sso auth.

**Comment by andybons** [comment]
Can you provide a small program that demonstrates this behavior?

**Comment by andybons** [comment]
@FiloSottile @katiehockman

**Comment by kotyara85** [comment]
This fix didn't solve the problem on 1.14.3

**Comment by FiloSottile** [comment]
This fix will be released in Go 1.15, not a minor release.
