### ISSUE TITLE
errors: example code for errors.As has extraneous code

### ISSUE THREAD

**Issue by katiehockman** [golang/go#38369]
The example code for `errors.As` (viewed at https://pkg.go.dev/errors?tab=doc#As) is the [entire contents of the `wrap_test.go` file](https://github.com/golang/go/blob/go1.14.1/src/errors/wrap_test.go). It should be just `func ExampleAs() { ... }` I presume.

In talking this over with @FiloSottile, this may be a more systemic issue which can be improved in `godoc`. For example, we have the same issue with the [chacha20poly1305.NewX](https://pkg.go.dev/golang.org/x/crypto/chacha20poly1305?tab=doc#NewX) example code. However, perhaps we should fix the example for the errors package for now either way.

While we're in there, perhaps we should check if there are any improvements to the documentation for errors as tracked in https://github.com/golang/go/issues/31716.

/cc @jba @mpvl

**Comment by jba** [comment]
The package doc for `testing` says
>The entire test file is presented as the example when it contains a single example function, at least one other function, type, variable, or constant declaration, and **no test or benchmark functions**.

(Emphasis mine.) The `wrap_test.go` does have a test function, so the whole file shouldn't be displayed as the example.

So I think this is a bug in the `testing` package.

**Comment by FiloSottile** [comment]
@dmitshur, is this a godoc bug?

**Comment by antong** [comment]
Is this a consequence of #38376 ?

**Comment by dmitshur** [comment]
Yes. @jba's analysis is correct. It's a regression in `go/doc` package in Go 1.14, filed #38409. Thanks for spotting and reporting.

**Comment by FiloSottile** [comment]
Looks like this is now tracked in #31716 and #38409.
