### ISSUE TITLE
x/tools/go/packages: package loader in 1.14 broke go doc examples?

### ISSUE THREAD

**Issue by posener** [golang/go#38376]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build760461752=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I try to load package examples. In 1.13 I get the right example, in 1.14 I get the entire file and replaces the example code with `func main() { ... }`.
Look at [pkg.go.dev](https://pkg.go.dev/github.com/posener/fuzzing?tab=doc#example-package) or [go doc](https://godoc.org/github.com/posener/fuzzing#example-package) examples.

### What did you expect to see?

What was shown in go 1.13 - only the example code.

### What did you see instead?

The entire test file with the example code replaced with `func main() { ... }`.

### More details

The code below behaves differently in 1.13 and 1.14:

```go
package main

import (
	"fmt"
	"go/doc"
	"os"

	"golang.org/x/tools/go/packages"
)

func main() {
	cfg := &packages.Config{Mode:  packages.LoadAllSyntax, Tests: true}
	pkgs, err := packages.Load(cfg, "github.com/posener/fuzzing")
	if err != nil {
		os.Exit(1)
	}
	if packages.PrintErrors(pkgs) > 0 {
		os.Exit(1)
	}

	for _, pkg := range pkgs {
		fmt.Println(pkg.Name)
		examples := doc.Examples(pkg.Syntax...)
		if len(examples) > 0 {
			fmt.Println(examples[0].Play)
		}
	}
}
```

In 1.13 `fmt.Println(examples[0].Play)` prints `nil` for the `fuzzing` package, though in 1.14 it prints non-nil object. This breaks what gddo expects in https://github.com/golang/gddo/blob/master/doc/builder.go#L233. I think.

**Comment by andybons** [comment]
@matloob

**Comment by antong** [comment]
Is this the reason why https://golang.org/pkg/errors/#example_As is broken? Compare:

- https://web.archive.org/web/20200102210830/https://golang.org/pkg/errors/#As (go1.13.5, OK)
- https://web.archive.org/web/20200228053452/https://golang.org/pkg/errors/#As (go1.14, messed up).

**Comment by dmitshur** [comment]
Thanks for reporting. The bug is in `doc.Examples`, not in the package loader. See issue #38409.
