### ISSUE TITLE
cmd/go: relative path in 'CC' environment variable should be rejected explicitly

### ISSUE THREAD

**Issue by vedantroy** [golang/go#38372]
### What version of Go are you using (`go version`)?
<pre>
1.14.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
I'm on 1.14.1, is that recent enough? It seems troublesome to upgrade to 1.14.2

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vedantroy/.cache/go-build"
GOENV="/home/vedantroy/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/vedantroy/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="./bin/clang"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="--sysroot=./share/wasi-sysroot -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build024786726=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```
GO111MODULE=on go get golang.org/x/tools/gopls@latest
```

### What did you expect to see?
gopls get updated.

### What did you see instead?
```
go: golang.org/x/tools/gopls latest => v0.4.0
# runtime/cgo
fork/exec ./bin/clang: no such file or directory
```
I have clang installed on my system though. So not sure what the issue is.

**Edit**: I seem to have fixed this issue. Not sure how, but the VsCode Go extension had me click a button that recompiled a bunch of packages. I'll still leave this issue open though, because the error was confusing, and I don't know how to fix it.

**Edit 2**: My CC variable was mis-configured because earlier I had ran a shell script that messed with my environment. It is worth noting that whatever fix is implemented should probably explicitly mention the CC variable is the root cause because I had no idea until this issue was filed.

**Comment by bcmills** [comment]
The `CC` environment variable must specify an absolute path, not a relative one.

The fact that `cmd/go` does not diagnose that problem explicitly is a bug.

CC @jayconrod @matloob

**Comment by obeyda** [comment]
I would like to help on this, maybe we need to add checks for `CC` and `CXX` here https://github.com/golang/go/blob/7580937524965d6b4acd39d36f8447b1919e1816/src/cmd/go/internal/envcmd/env.go#L105

**Comment by bcmills** [comment]
Possibly, but we also need to ensure that the user doesn't get stuck with a bad `CC` value through running `go env -w` or similar.

So in addition to the check in `envcmd.MkEnv`, we may also need something akin to the GOOS/GOARCH check:
https://github.com/golang/go/blob/82fcf749bde1aae839ce520edfff04d2daf70987/src/cmd/go/internal/envcmd/env.go#L264-L266

**Comment by obeyda** [comment]
I am relatively new to this, so i have some questions: in `go env -w` we can report failure by `base.Fatalf`, but what should we do in envcmd.MkEnv? print an error and ignore is (set it to the default value)?

**Comment by bcmills** [comment]
Since a bad `CC` value affects most commands that attempt to build, perhaps we should check `CC` and `CXX` during `cmd/go/internal/work.BuildInit` instead of in `envcmd.MkEnv`.

**Comment by obeyda** [comment]
Can someone please review this?
