### ISSUE TITLE
go.dev: make links to examples automatically unfold example

### ISSUE THREAD

**Issue by kortschak** [golang/go#38381]
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/twpayne/go-vfs/vfst?tab=doc#example-NewTestFS
 
 
### What is your user agent?
 

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0
 
 
### What did you do?
 

Navigate to https://pkg.go.dev/github.com/twpayne/go-vfs/vfst?tab=doc#example-NewTestFS and expect to see that the example is unfolded as it is in the case of documentation examples on golang.org like this https://tip.golang.org/pkg/fmt/#example_Errorf, but see that it isn't.
 
 
### What did you expect to see?

Unfolded examples.
 
 
### What did you see instead?

Folded example.

**Comment by julieqiu** [comment]
Thanks for the feedback! Adding this to #37819.

**Comment by dmitshur** [comment]
Is this issue different from #37520?

**Comment by kortschak** [comment]
No. This is a duplicate. Thanks.
