### ISSUE TITLE
sort.SearchStrings finds string even if exact string is not found

### ISSUE THREAD

**Issue by Prithvipal** [golang/go#38386]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/prithvipalsingh/Library/Caches/go-build"
GOENV="/Users/prithvipalsingh/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/prithvipalsingh/PRITHVI/Github"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hs/c705kkdj0db6fb0npphggk3m0000gn/T/go-build902606486=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Executed following program:

```
package main

import (
	"fmt"
	"sort"
)

func main() {
	strs := []string{
		"Delhi",
		"Mumbai",
		"Jaipur",
		"Chandigarh",
	}
	sort.StringSlice(strs).Sort()
	fmt.Println(strs)
	n := sort.SearchStrings(strs, "Jai")
	fmt.Println(n)
}
```
Please note in above program that I have provided "Jai" to search string. I have not provided "Jaipur" which is availalbe in the string slice.

### What did you expect to see?
4
I would expect 4 as output because when the string is not found in slice then the SearchString returns the length of the slice. 

### What did you see instead?
2

**Comment by seankhliao** [comment]
Working as expected
> The return value is the index to insert x if x is not present

**Comment by jonyhy96** [comment]
According to the comment  of the function:
```
// SearchStrings searches for x in a sorted slice of strings and returns the index
// as specified by Search. The return value is the index to insert x if x is not
// present (it could be len(a)).
// The slice must be sorted in ascending order.
//
func SearchStrings(a []string, x string) int {
```
It is returning the position of the slice that you can insert your string.

**Comment by Prithvipal** [comment]
@seankhliao and @joe2far Thank you for the reply.

I still have a question. If we see the above code provided by me, I have given the subset of the string available in the slice. The string available at index 2(after sorting) is "Jaipur" but I have provided "Jai" as input to the SearchString. The SearchString returns the index even there is no exact match of the string. So my question is, does the SearchString function check for a subset of the string available in the slice?

**Comment by bradfitz** [comment]
For Go questions, see https://golang.org/wiki/Questions
