### ISSUE TITLE
feature request: allow assigning of slice of interfaces to another slice of interfaces provided the first interface satisfies the second

### ISSUE THREAD

**Issue by AyushG3112** [golang/go#38385]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/ayush/projects/gojects/bin"
GOCACHE="/home/ayush/.cache/go-build"
GOENV="/home/ayush/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="github.com/ayushg3112/*"
GONOSUMDB="github.com/ayushg3112/*"
GOOS="linux"
GOPATH="/home/ayush/projects/gojects"
GOPRIVATE="github.com/ayushg3112/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build648362932=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Playground link: https://play.golang.org/p/q_CVk9PRhQF

### What did you expect to see?
Since an `io.ReadCloser` satisfies a `io.Reader`, a `[]io.ReadCloser` should theoretically always satisfy a `[]io.Reader`, so the playground link should work.

### What did you see instead?

``` console
./prog.go:9:6: cannot use make([]io.ReadCloser, 50) (type []io.ReadCloser) as type []io.Reader in assignment
```

**Comment by ccbrown** [comment]
What should happen if you try to modify a Reader slice “satisfied” by a ReadCloser slice?

```go
var readers []io.Reader = readClosers
readers[0] = strings.NewReader(“”)
```

What is `readClosers[0]` now?

**Comment by networkimprov** [comment]
@AyushG3112 what you want isn't assignment, but
```
r := []io.Reader{nil}
c := []io.ReadCloser{nil}
copy(r, c)
r = append(r, c...)
```

But you won't see that added to the language, as you could do it with generics.

**Comment by ianlancetaylor** [comment]
This is related to these FAQs, although they don't address it precisely:

https://golang.org/doc/faq#convert_slice_of_interface
https://golang.org/doc/faq#convert_slice_with_same_underlying_type

In general Go does not support converting slices of one type to slices of a different types, even if the element types are themselves convertible.  This is unlikely to change.

I'm going to close this issue.  If you want this to change in the language, you would need to make a full language change proposal.  See https://golang.org/s/proposal and https://go.googlesource.com/proposal/+/refs/heads/master/go2-language-changes.md.  But I think it's fairly unlikely that such a language change would be accepted.
