### ISSUE TITLE
Memory distribution 

### ISSUE THREAD

**Issue by kensang248** [golang/go#38399]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.14.2
</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 18.04.4 LTS
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pc/.cache/go-build"
GOENV="/home/pc/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pc/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build346505967=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Problem in capacity of Memory distrubion when appending an Array.
I run this code on both play.golang.org and VScode but 2 different results

https://play.golang.org/p/jQb9mPQSvXP

### What did you expect to see?

the same result 

### What did you see instead?
Different capacity

**Comment by randall77** [comment]
This is expected. This is how `append` works, growing capacity as needed. You might want to read https://blog.golang.org/slices and see if the behavior you're seeing makes sense.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only. Please see https://github.com/golang/go/wiki/Questions for good places to ask questions like this.
