### ISSUE TITLE
cmd/compile: -1.0 * 0.0 doesn't yield -0.0

### ISSUE THREAD

**Issue by perillo** [golang/go#38396]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/manlio/.local/bin"
GOCACHE="/home/manlio/.cache/go-build"
GOENV="/home/manlio/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE="*.local"
GONOPROXY=""
GONOSUMDB="*.local"
GOOS="linux"
GOPATH="/home/manlio/.local/lib/go:/home/manlio/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build291401117=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.14.2 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.14.2
uname -sr: Linux 5.6.3-arch1-1
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.31.
gdb --version: GNU gdb (GDB) 9.1
</pre></details>

### What did you do?

https://play.golang.org/p/F9vVfqkyonb

### What did you expect to see?

```
-0
```

This is the result returned by *C* and *Python*.

### What did you see instead?

```
0
```

Is the only way to get a negative zero in *Go* `math.Copysign(0.0, -1.0)` ?

Thanks.

**Comment by perillo** [comment]
Dividing zero by the negative infinite correctly yields a negative zero.
https://play.golang.org/p/Vby8qc8gEUK

**Comment by randall77** [comment]
You're running afoul of the ideal constant arithmetic in Go. This code generates a -0:
```
func main() {
     var x float64 = -1.0
     var y float64 = 0.0
     z := x*y
     println(z)
}
```
Constant arithmetic has its own rules. It is exact(-ish) and doesn't behave like IEEE754.

**Comment by perillo** [comment]
The Go specification says
```
Numeric constants represent exact values of arbitrary precision and do not overflow. Consequently, there are no constants denoting the IEEE-754 negative zero, infinity, and not-a-number values.
```

But I assumed this only means that `-0` yields `0`.  It is not clear, at least to me, that `-1.0 * 0.0` yields `0`.  The same with `float32(-1.0) * float32(0.0)` yielding `0`.

Thanks.
