### ISSUE TITLE
cmd/go: clean --modcache fails if disk is full

### ISSUE THREAD

**Issue by bradfitz** [golang/go#38395]
If your disk is full and you reach for `go clean --modcache` to get some of your disk back, this isn't ideal:

```
$ go clean --modcache
go: creating work dir: mkdir /tmp/go-build419219692: no space left on device
```
 
/cc @bcmills

**Comment by bradfitz** [comment]
Previously, related: #28680

**Comment by bcmills** [comment]
CC @jayconrod @matloob 

This seems like another one of those places where we're calling `base.Fatalf` or equivalent but should instead be returning an error for the specific command to report.
