### ISSUE TITLE
x/tools/gopls: add regtests for adding/deleting files

### ISSUE THREAD

**Issue by matthewmueller** [golang/go#38407]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/m/Library/Caches/go-build"
GOENV="/Users/m/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/m/Go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4f/tcxcr6_55v9bp38d8g4hjlf80000gn/T/go-build860054194=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I created a broken Go program 😬

https://play.golang.org/p/AGtHpgFoOts

### What did you expect to see?

Proper syntax highlighting where I made my mistake.

In this case, `func (*u Up) Run` should be `func (u *Up) Run`

### What did you see instead?

Nada. Nothing. Formatting fails, but that's about it.

![image](https://user-images.githubusercontent.com/170299/79124634-0b3b6200-7d9d-11ea-95b3-2afa2d62a4e6.png)

If I go into the gopls logs on VSCode, I see the following:

```
[Error - 3:35:20 PM] Request textDocument/codeAction failed.
  Message: computing fix edits: /Users/m/Code/app/commands/migrate/migrate.go:20:7: expected identifier (and 1 more errors)
  Code: 0 
[Error - 3:35:20 PM] Request textDocument/formatting failed.
  Message: 20:7: expected identifier (and 1 more errors)
  Code: 0 
```

**Comment by stamblerre** [comment]
I'm not able to reproduce this - this is the error I see:

<img width="675" alt="Screen Shot 2020-04-13 at 11 37 05 AM" src="https://user-images.githubusercontent.com/5856771/79134074-1b424a00-7d7b-11ea-9bdf-14b5172f0b00.png">

What directory did you have open when you saw this? It's possible that if the file wasn't in the directory at the root of your workspace, then `gopls` didn't report diagnostics for it (something we will be fixing in `gopls/v0.5.0`).

If you still have the full logs for this, those would be helpful to see.

**Comment by matthewmueller** [comment]
Hey @stamblerre, thanks for the quick response! 

I'm not quite up on the lingo for what a VSCode Workspace means, but here's my projects directory structure. I opened it with `code .`:

```
.
├── commands
│   ├── migrate
│   └── web
├── controllers
│   ├── pages
│   └── users
├── go.mod
├── go.sum
├── internal
│   ├── env
│   └── log
├── main.go
├── migrate
│   └── migrate.go
└── views
    └── pages
```

I'm sadly not able to reproduce this issue reliably. If I open VSCode fresh, it does properly show the error:

![image](https://user-images.githubusercontent.com/170299/79227332-01c6fe00-7e60-11ea-9bd6-b6147373f1f0.png)

What I can say is that over time, as I'm adding and deleting files, it eventually fails stops reporting. 

It sounds like 0.5.0 might provide a solution for this issue though? 😬🙏

**Comment by stamblerre** [comment]
Ah, ok so then it looks like your workspace is configured correctly and the diagnostics should be propagating. In the future when this happens, I'd suggest capturing detailed `gopls` logs (https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs) so that we can see what sequence of edits led to this state.

The process of cache invalidations after adding and deleting files is not perfect yet, so it's likely that that was the cause. I will be adding more integration tests soon, so I'll retitle this issue to make sure I add a few cases for adding and deleting files.

**Comment by matthewmueller** [comment]
Okay sounds good. Do I also need to enable trace logs or is the default log output detailed enough?

**Comment by stamblerre** [comment]
You'll want to add the `-rpc.trace` flag to `go.languageServerFlags`.

**Comment by stamblerre** [comment]
Another case to add a regression test for: https://github.com/microsoft/vscode-go/issues/3179#issuecomment-614896921.

**Comment by matthewmueller** [comment]
Closing since I this appears to be addressed 🙌
