### ISSUE TITLE
golang.org: why it uses jquery?

### ISSUE THREAD

**Issue by mobop** [golang/go#38410]

**Comment by ALTree** [comment]
Why it shouldn't?

**Comment by changkun** [comment]
Obviously, this is a historical issue. golang.org was born before those frontend fancy stuff. During that age, jQuery was dominant and enables fast implementation of DOM manipulation for this simple purpose website. Name several examples: jQuery is used to perform AJAX requests; it is also used to construct the line numbers of the playground; and so on.

One could argue that we can do it in vanilla JS or more fancily with those three popular library/frameworks but apparently the answer is **not necessarily**. If you interested in doing it, send a CL then you can talk about it with Go team if the proposed changes can get approve.

**Comment by andybons** [comment]
@mobop please stop asking one-line questions with little context here and elsewhere ([1](https://github.com/denoland/deno/issues/4800), [2](https://github.com/golang/go/issues/38483)) where attempts from contributors to explain rationale have been met by responses that could be interpreted as you acting in bad faith.

Please read our [Code of Conduct](https://golang.org/conduct), specifically the section on [Gopher values](https://golang.org/conduct#values)

Closing as this is a question and we no longer support questions on the issue tracker. If you’d like to ask historical questions about Go’s development you can email golang-dev@googlegroups.com.

Thanks.
