### ISSUE TITLE
x/tools/gopls: formatting on save inserts an unnecessary package clause

### ISSUE THREAD

**Issue by hyangah** [golang/go#38412]
When using with VS Code

## settings
gopls version 0.4.0
go1.14, darwin/amd64
VS Code Go extension 0.14.0-beta.6
go extension setting: `"go.useLanguageServer": true,`

##  how to repro:

$ cat main.go
package main
func main() { }

Open the it from the code, and save the file again (command+s). That triggers text edit like:

![image](https://user-images.githubusercontent.com/4999471/79132284-0ca66380-7d78-11ea-85e0-824047ba9da7.png)

Attached the gopls log.  [code.log](https://github.com/golang/go/files/4470050/code.log)

File save was requested after the message 7. 
So, message 8 is the one triggered by my action.

Note: when triggering the formatting using "Format Document"  (e.g. right click -> "Format Document") the formatting works as expected.

**Comment by stamblerre** [comment]
Thanks for the report! Looks like this is caused by the codeAction (import organization). I know that it adds a fake package clause if it doesn't find one, but this doesn't seem to be that. I'll investigate.
