### ISSUE TITLE
net/http: client does not quote URL consistently like "protocol scheme" in returned errors

### ISSUE THREAD

**Issue by as** [golang/go#38421]
The HTTP client should quote the URL and protocol scheme consistently. Look at the result of this call to `http.Get` with an empty URL string:

```
fmt.Println(http.Get(""))
// <nil> Get : unsupported protocol scheme ""
```

I can't immediately see that there's an empty string in this output, I only see that the protocol is empty.

### What did you expect to see?
```
<nil> Get "": unsupported protocol scheme ""
```

### What did you see instead?
```
<nil> Get : unsupported protocol scheme ""
```

https://play.golang.org/p/ppBzVyfctb6

**Comment by mlowicki** [comment]
@as which version are you using? I've tested locally with `go version go1.14.1 linux/arm` and it looks fine:
```
<nil> Get "": unsupported protocol scheme ""
```

I've checked https://play.golang.org/p/ppBzVyfctb6 and I'm getting there:
```
<nil> Get "": unsupported protocol scheme ""
<nil> Get "example.com": unsupported protocol scheme ""
<nil> Get "ftp://example.com": unsupported protocol scheme "ftp"
```

**Comment by as** [comment]
The issue is not reproducible in the latest version. At the time of writing, the playground link successfully reproduced it (week ago). As of the latest version, it does not. Closing.
