### ISSUE TITLE
x/tools/gopls: "expected declaration, found 'package'" after cutting and pasting a file's contents

### ISSUE THREAD

**Issue by stamblerre** [golang/go#38424]
I've noticed that the `go list` empty file error message will sometimes reappear in this case. This needs both a fix and a regression test.

**Comment by segevfiner** [comment]
I'm seeing this issue. Looks like something like starting with an empty file or removing it's content, then typing the `package` statement, waiting a bit, and continuing on to write some other stuff in the file, like a `func main`. Is this the gopls in memory representation of the file getting messed up or something?
