### ISSUE TITLE
x/time/rate: documentation of Limiter.ReserveN does not return bool

### ISSUE THREAD

**Issue by yvesf** [golang/go#38434]
### Does this issue reproduce with the latest release?
yes, latest release of time/rate contains this documentation string

### What did you expect to see?
```go
...
// ReserveN returns false if n exceeds the Limiter's burst size.
// Usage example:
...
func (lim *Limiter) ReserveN(now time.Time, n int) *Reservation {
```

### What did you see instead?
```go
...
// On the returned Reservation OK() returns false if n exceeds the Limiter's burst size.
// Usage example:
...
func (lim *Limiter) ReserveN(now time.Time, n int) *Reservation {
```

**Comment by andybons** [comment]
I would word it slightly differently:

> // The returned Reservation’s OK() method returns false if n exceeds the Limiter's burst size.

**Comment by obeyda** [comment]
@andybons , I can fix that, should i send a cl?

**Comment by andybons** [comment]
@obeyda sure.

**Comment by obeyda** [comment]
CL pushed https://go-review.googlesource.com/c/time/+/228357
