### ISSUE TITLE
x/tools/go/packages: "-: cannot find package "nonexist" in any of: ..."

### ISSUE THREAD

**Issue by mdempsky** [golang/go#38444]
When I run `go build nonexist`, I get:

```
package nonexist: cannot find package "nonexist" in any of:
	/home/mdempsky/wd/go/src/nonexist (from $GOROOT)
	/home/mdempsky/go/src/nonexist (from $GOPATH)
```

But using go/packages.Load and go/packages.PrintErrors (full code below), I get:

```
-: cannot find package "nonexist" in any of:
	/home/mdempsky/wd/go/src/nonexist (from $GOROOT)
	/home/mdempsky/go/src/nonexist (from $GOPATH)
```

Is there some parser code that thinks "package nonexist:" is not a valid source position, so it gets mapped to "-:"?

Demo code:

```
package main

import "golang.org/x/tools/go/packages"

func main() {
	cfg := &packages.Config{Mode: packages.NeedName}
	pkgs, err := packages.Load(cfg, "nonexist")
	if err != nil {
		panic(err)
	}
	packages.PrintErrors(pkgs)
}
```

/cc @matloob @heschik

**Comment by matloob** [comment]
cc @stamblerre 

Errors are associated with positions in a file, and if there's no position, the error is printed with a `-`. See the documentation of error here. https://pkg.go.dev/golang.org/x/tools/go/packages?tab=doc#Error

The error's already associated with a package, so the error doesn't print its own package to avoid redundancy.

**Comment by mdempsky** [comment]
Can we make "go build" follow the same convention then? I.e., make it print "-:" instead of "package nonexist:"?

**Comment by matloob** [comment]
@jayconrod @bcmills 

I don't know if that's the right thing to do here: the closer analogue to what go packages does is `go list -e -json`: and with those you get a very similar result:

```
$ go list -e -json nonexist
{
	"ImportPath": "nonexist",
	"Match": [
		"nonexist"
	],
	"Incomplete": true,
	"Error": {
		"ImportStack": [
			"nonexist"
		],
		"Pos": "",
		"Err": "package nonexist is not in GOROOT (/usr/local/go/src/nonexist)"
	}
}
```

**Comment by mdempsky** [comment]
Looks like cmd/go's "package nonexist:" output comes from:

https://github.com/golang/go/blob/a55645fa3481413b335561924d8fa626ce440ad4/src/cmd/go/internal/load/pkg.go#L396

**Comment by bcmills** [comment]
I don't think `-:` is a particularly helpful prefix. (Helpful to tools, perhaps, but confusing to humans.)

That said, `package nonexist: cannot find package "nonexist"` is unpleasantly redundant too. This failure message is a lot smoother in module mode than in GOPATH mode:

```
example.com$ GO111MODULE=on go build nonexist
package nonexist is not in GOROOT (/usr/local/google/home/bcmills/sdk/gotip/src/nonexist)

example.com$ GO111MODULE=off go build nonexist
package nonexist: cannot find package "nonexist" in any of:
        /usr/local/google/home/bcmills/sdk/gotip/src/nonexist (from $GOROOT)
        /tmp/tmp.00bJBNCJEL/_gopath/src/nonexist (from $GOPATH)
```

If someone wants to fix the GOPATH-mode error message to match the module-mode one, that seems like it would be an improvement, but unless we see something similar in module mode I don't think it's worth spending much time on.

**Comment by matloob** [comment]
On the go/packages side, one thing we can do is just drop the "-:" on the error's String method. That might be nicer for users if the package?

**Comment by seankhliao** [comment]
cmd/go now prints:
> package nonexist is not in std (/home/user/sdk/gotip/src/nonexist)

and go/packages prints:
> -: package nonexist is not in std (/home/user/sdk/gotip/src/nonexist)

**Comment by matloob** [comment]
Those look good to me. We're not printing setting a redundant pos from the go command and printing that from go packages, we indicate there's no position with "-".

In golang.org/x/tools/go/packages.Error.Error, we explicitly print "-:" when the pos is empty, which I think is reasonable.
