### ISSUE TITLE
inconsistent behavior of defined type

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [golang/go#38449]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gmikhalkin/.cache/go-build"
GOENV="/home/gmikhalkin/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/gmikhalkin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/5646"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/5646/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build997606175=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Create new type:
```
type A {}

func (A) print() {
    fmt.Println("test")
}
```

Define one more type that points to it:
```
type B A
```

Run this code:
```
func main() {
	a := A{t: "test"}
	b := a
	b.print()
}
```

[Reproducible example](https://play.golang.org/p/UawfatTJL6P)

### What did you expect to see?
If i run this code:
```
func main() {
	b := B{}
	b.print()
}
```

It throws an error `b.print undefined (type B has no field or method print)`. And that's what i expect in both cases, because [specification states](https://golang.org/ref/spec#Type_declarations) that:
> It[defined type] does not inherit any methods bound to the given type

[Reproducible example](https://play.golang.org/p/JLlNBPuZINw)

### What did you see instead?

It successfully executes `print` method.

**Comment by KonstantinGeist** [comment]
In the first example, the variable is typed as A. Type B isn't used at all.
