### ISSUE TITLE
gopls: VS Code breakpoints being deleted on file save

### ISSUE THREAD

**Issue by kkotowick** [golang/go#38451]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.14
</pre>

### Does this issue reproduce with the latest release?
Yes (this is the latest release).

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOOS=windows
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
</pre></details>

### What did you do?

Saved a open .go file in VS Code that contained breakpoints.

### What did you expect to see?

The file save and the breakpoints remain.

### What did you see instead?

The file saved and the breakpoints all disappeared.

**Comment by stamblerre** [comment]
`gopls` isn't responsible for debugging in VS Code, so I would suggest opening this issue in the [VS Code Go](https://github.com/microsoft/vscode-go) repository instead.
