### ISSUE TITLE
proposal: runtime: delete Stack

### ISSUE THREAD

**Issue by robpike** [golang/go#3845]
<pre>Now that runtime.Stack exists, its value added is pretty small. Maybe for Go 2.</pre>

**Comment by rsc** [comment]
In Go 1.6 we changed debug.Stack to be a convenience wrapper around runtime.Stack, for #12363. Whereas runtime.Stack requires passing an allocated buffer at the call site, debug.Stack takes care of allocation and also of making sure the buffer is bug enough to hold the complete stack.

Leaving this open but note that now debug.Stack is actually nicer than runtime.Stack. If we're going to remove one, it might make sense to unexport runtime.Stack instead.

**Comment by robpike** [comment]
That sounds like the right answer now.

**Comment by bradfitz** [comment]
debug.Stack only returns the current goroutine, though.

If runtime.Stack is removed, how would one implement, say, a /debug/goroutinez debug endpoint?

**Comment by ianlancetaylor** [comment]
`runtime.Stack` takes an argument saying whether to return all goroutines.  `runtime/debug.Stack` provides a nicer API for dumping only the current goroutine.  There are uses for both, and no good way to replace one with the other.  So I think there is nothing to do here.  If someone wants to propose additional API for runtime/debug, that is fine.
