### ISSUE TITLE
x/tools/gopls: hide gofmt -s diagnostics (and others?) in generated files

### ISSUE THREAD

**Issue by zikaeroh** [golang/go#38467]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

I generated code with `gqlgen`. One of the generated files (matches that DO NOT EDIT regex) contains non gofmt-simplified code.

#### What did you expect to see?

No non-syntax diagnostics; the file is generated.

#### What did you see instead?

Diagnostics like: "redundant type from array, slice, or map composite literal"

Since I have quick fix on save enabled, and some diagnostics have suggested fixes, if I save the file then I'll accidentally change the file even though it's generated.

Other linters (staticcheck, golangci-lint) will ignore these files, and I can't recall seeing messages from `gopls` before in these files, so I'm not sure if it's a new issue or not.

#36914 seems related, but was specifically for staticcheck.

#### Build info

```
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.0.0-20200415034506-5d8e1897c761 h1:Ypqqmv003QzoDmadLMADUJ5LozvN33kS5Zr7zr+AtPU=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.2.0 h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
    golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=
    golang.org/x/tools@v0.0.0-20200415034506-5d8e1897c761 h1:FVw4lelfGRNPqB3C8qX1m+QyeM2vzToIwlFhEZX42y8=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=
```

#### Go info

```
go version go1.14.2 linux/amd64

```

**Comment by stamblerre** [comment]
We can support this, but I'm curious if it would be useful for vet/staticcheck errors to appear in these generated files, since sometimes they can provide warnings about bugs.
