### ISSUE TITLE
x/tools/gopls: don't access the network for `go mod tidy` diagnostics

### ISSUE THREAD

**Issue by stamblerre** [golang/go#38462]
A few reports of issues with `gopls` when the user has no internet (one on Slack, one on https://github.com/microsoft/vscode-go/issues/3105).

I wonder if there is a way we can have a regression test this - maybe by configuring something in the environment? @findleyr

**Comment by OneOfOne** [comment]
Any use of outside network should be opt-in, or at least provide a way to disable it.

**Comment by findleyr** [comment]
Following https://golang.org/cl/228235, the regtests use a proxy within our control. If we have examples of how gopls breaks without a network connection, we should be able to reproduce.

**Comment by mingoal** [comment]
@findleyr 
suggest scenario:
 in go file, include one package which has no local cache,
1. without network connection, will `gopls` hang or not?
2. with network connection which requires http proxy, will `gopls` hang or not?

**Comment by stamblerre** [comment]
I believe the only remaining task here is to remove network access for the `go mod tidy` diagnostics.

@heschik, is there anything else I'm missing?

**Comment by heschik** [comment]
That's it as far as I know.
