### ISSUE TITLE
x/mod/zip: frequent TestVCS failures with 'exit status 128'

### ISSUE THREAD

**Issue by bcmills** [golang/go#38466]
```
--- FAIL: TestVCS (0.00s)
    --- FAIL: TestVCS/rsc.io_quote@v1.2.1 (31.77s)
        zip_test.go:944: fetch -f --depth=1 origin refs/tags/v1.2.1:refs/tags/v1.2.1: exit status 128
FAIL
FAIL	golang.org/x/mod/zip	37.493s
```

Some examples (a full list is hard to obtain due to #35515):
* https://build.golang.org/log/ccfe7667f4a8078f0abb9f1690bb60b9c16b6667
* https://build.golang.org/log/770a0e7b2932494a0088282e8c368b83d0b4b429
* https://build.golang.org/log/8e4f13ddce054d013f61ca4107aff0aad92c2aee
* https://build.golang.org/log/48b37e8f22936ba040107609992fb71851f7eaea
* https://build.golang.org/log/409017b9f72dc739589429803dd6fcf3cb3fb533

The specific repository that fails seems to vary from run to run. It's not clear to me whether this is a bug in `x/mod/zip`, a bug in `git`, a network issue on the `linux-amd64-longtest` builder, or unreliability in the upstream `git` servers.

CC @jayconrod @matloob @andybons

**Comment by jayconrod** [comment]
I'm not too worried about git failures on this test. `x/mod/zip` doesn't directly interact with VCS tools; the test just does that to simulate how `cmd/go` drives it.

I would like to resolve the flakiness though. Perhaps a download error like this should cause the test to skip instead of fail.
