### ISSUE TITLE
cmd/go: do not lookup *.go domains

### ISSUE THREAD

**Issue by rsc** [golang/go#38478]
I accidentally ran "go get x.go foo" instead of "go run x.go foo".
The go command did:
```
go get x.go: unrecognized import path "x.go": https fetch: Get "https://x.go/?go-get=1": dial tcp: lookup x.go: no such host
```

It should probably instead reject the whole command if the first path ends in `.go`, to make this common mistake fail quicker and with a better error.

/cc @jayconrod @bcmills @matloob

**Comment by jayconrod** [comment]
Related #32483 and #34653.

When we load packages for build commands, we check whether arguments ending with `.go` refer to existing files. If they don't, we treat them as package paths, since there are packages whose names end with `.go`.

We should check this in `go get`, too, so those packages can still be updated.

**Comment by rsc** [comment]
In my case the file did exist, so let's at least get this check into `go get`.

**Comment by justplesh** [comment]
I will try to fix this bug. 
Summarizing the task: we need to reject paths, which **domain** looks like `*.go`, but it's okay when the URL path ends with `.go` like `github.com/nats-io/nats.go`. 
By all means, if I've got it wrong, please correct me.

**Comment by jayconrod** [comment]
@justplesh It's a little simpler. For each argument, just consider the path (not counting any `@version` suffix). If the path ends with `.go` and either contains no slashes or refers to an existing file (not a directory), then report an error.

That should catch common mistakes without breaking real packages.
