### ISSUE TITLE
x/build/dashboard: enable/trigger build tracking for release-branch.go1.4 through go1.10

### ISSUE THREAD

**Issue by jfkw** [golang/go#38473]
Distribution packagers bootstrapping from early versions of go with the goal of building current versions of go would benefit from build.golang.org dashboards for those historical releases. This would show at a glance successful initial builds on various architectures e.g. armv6l in go1.6, s390x in go1.7.1, ppc64le in go1.7.4, etc.

Please consider to enable and/or manually trigger build.golang.org builds for:

- https://build.golang.org/?repo=&branch=release-branch.go1.4
- https://build.golang.org/?repo=&branch=release-branch.go1.5
- https://build.golang.org/?repo=&branch=release-branch.go1.6
- https://build.golang.org/?repo=&branch=release-branch.go1.7
- https://build.golang.org/?repo=&branch=release-branch.go1.8
- https://build.golang.org/?repo=&branch=release-branch.go1.9
- https://build.golang.org/?repo=&branch=release-branch.go1.10

**Comment by andybons** [comment]
Sorry, but this would add an enormous burden on an already oversubscribed build infra team.

Keeping the issue open for discussion, but it’s unlikely we’ll add support for releases that far back.

What specific problem that you’ve experienced would this solve?
