### ISSUE TITLE
go test: can't load package: package ... is not in GOROOT

### ISSUE THREAD

**Issue by BigBoulard** [golang/go#38486]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/me/Library/Caches/go-build"
GOENV="/Users/me/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/me/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/me/dev/go/github.com/bigboulard/myproject/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1g/fytltrn578gg3xgp3c_sglhw0000gq/T/go-build003375880=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```bash
/Users/me/dev/go/github.com/bigboulard/myproject
├── go.mod
├── go.sum
├── main.go // it executes normally
└── model
    ├── contacts.go
    └── contacts_test.go
```

```go
package model

import (
	"fmt"
	"testing"
)

func BenchmarkGenRandValueV1(b *testing.B) {
	fmt.Println(GenRandValueV1(10, 30))
}

func BenchmarkGenRandValueV2(b *testing.B) {
	fmt.Println(GenRandValueV2(10, 30))
}
```

### What did you expect to see?
an execution

### What did you see instead?
```bash
Running tool: /usr/local/go/bin/go test -benchmem -run=^$ _/Users/me/dev/go/github.com/bigboulard/myproject/model -bench ^(BenchmarkGenRandValueV1)$

can't load package: package _/Users/me/dev/go/github.com/bigboulard/myproject/model is not in GOROOT (/usr/local/go/src/_/Users/me/dev/go/github.com/bigboulard/myproject/model)
Error: Benchmarks failed.
```

**Comment by antong** [comment]
Please refer to the documentation for "go test". "go test" does not take a path as argument, but a list of packages. So, run "go test github.com/bigboulard/myproject/model", "go test ./model", "go test ./..." or something that makes sense for you. Also, what is that underscore in the beginning of the path, as in "_/Users/..." ?

**Comment by BigBoulard** [comment]
Ok. So my understanding is that VSCode generates a bad command.
(According to the doc, -run option takes path as a regex)

> -run regexp
>         Run only those tests and examples matching the regular expression.

**Comment by BigBoulard** [comment]
VSCode just needed a restart after a few plugin installations. Thx.

**Comment by antong** [comment]
No, -run takes the a regex to filter the name of the test function. For example '-run Foo' would only run the test functions which Foo matches, such as TestFoo1, TestFooBar etc., but not TestXyz. https://golang.org/pkg/testing/#hdr-Subtests_and_Sub_benchmarks
