### ISSUE TITLE
x/tools/gopls: deleted files are being treated like orphaned files

### ISSUE THREAD

**Issue by stamblerre** [golang/go#38498]
Repro: Create and delete a package with one Go file in it. The logs will contain `packages.Load`s for this file that no longer exists, causing a huge slowdown. Somehow it never gets marked as "unloadable".

**Comment by heschik** [comment]
I can't reproduce this, at least not after https://golang.org/cl/238028.

**Comment by stamblerre** [comment]
Neither can I. Closing.

**Comment by stamblerre** [comment]
Reopening - I just had this happen to me. I deleted a file through the VS Code interface, and then immediately began experiencing a slowdown (laggy diagnostics). Looking at the logs, we were still constantly reloading the file and getting 0 packages for it.
