### ISSUE TITLE
x/tools/cmd/stringer: support for hex values

### ISSUE THREAD

**Issue by maltegrosse** [golang/go#38491]
Stringer works perfect on on multiple types, but using a hex value does not return the const name by giving integer as input.

### What version of Go are you using (`go version`)?

<pre>
$ go version 1.13

</pre>

### Does this issue reproduce with the latest release?

Feature Request, yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
...
set GOHOSTARCH=amd64
set GOHOSTOS=windows
...
</pre></details>

### What did you do?

<pre>
type SomeState uint32

//go:generate stringer -type=SomeState
const (
	StateOne   SomeState = 0x01 // dec 1
	StateTwo   SomeState = 0x02 // dec 2
	StateThree SomeState = 0x03 // dec 3
)
</pre>
returns generated:
<pre>
// Code generated by "stringer -type=SomeState"; DO NOT EDIT.

package go_mytest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateOne-1]
	_ = x[StateTwo-2]
	_ = x[StateThree-3]
}

const _SomeState_name = "StateOneStateTwoStateThree"

var _SomeState_index = [...]uint8{0, 8, 16, 26}

func (i SomeState) String() string {
	i -= 1
	if i >= SomeState(len(_SomeState_index)-1) {
		return "SomeState(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SomeState_name[_SomeState_index[i]:_SomeState_index[i+1]]
}

</pre>

### What did you expect to see?

<pre>
fmt.Println(SomeState(1))
</pre>
should return 
<pre>
"StateOne"
</pre>

### What did you see instead?
<pre>
SomeState(1)
</pre>

**Comment by robpike** [comment]
It works fine for me. Are you including somestate_stringer.go in your build? You can test this by trying 

```
fmt.Println(SomeState(1).String())
```

I think this is what's wrong, and if you try this variant it won't compile because the String method is not compiled into the binary.

**Comment by maltegrosse** [comment]
Thank you for your quick reply.  I double checked using .String() without any success.

I currently use it for my dbus modem manager wrapper (work in progress)

https://github.com/maltegrosse/go-modemmanager

It works fine for all enums (and these are alooot :) except of: 

https://github.com/maltegrosse/go-modemmanager/blob/master/enums.go#L424
which includes hex numbers. (the others including hex numbers havent tested yet)

I am not sure if stringer messed something up or my limited coding skills are the reason for that strange behavior. :) 

perhaps a quick go get and trying
`fmt.Println(modemmanager.MMSmsDeliveryState(256))
	fmt.Println(modemmanager.MMSmsDeliveryState(256).String())`
would help to clarify this.
