### ISSUE TITLE
x/build: windows arm builder missing

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#38493]
The windows arm builder has been missing for some time now:
`host-windows-arm-iotcore: 0/0 (1 missing)`

We should work to bring the builder back if possible.

/cc @andybons @dmitshur @toothrot

**Comment by cagedmantis** [comment]
@jordanrh1 Would you be able to update us on the status of the `host-windows-arm-iotcore`?

**Comment by dmitshur** [comment]
Issues #26148 and #32135 are related.

**Comment by thanm** [comment]
>>We should work to bring the builder back if possible.

It would be great to see the windows arm builder back up and working again, but given the circumstances (how long it has been MIA), maybe it would be better to just remove it. If the owner complains -- great, then we can swing into action and put it back into service. If not, let's move on.

**Comment by cagedmantis** [comment]
We have been unable to communicate with the builder maintainer for some time now. I'm going to work on removing the builder.
