### ISSUE TITLE
x/tools/internal/lsp/regtest: closing workspace sometimes fails on Windows

### ISSUE THREAD

**Issue by findleyr** [golang/go#38490]
Due to Windows' default file locking behavior, and the fact that gopls often shells out to the `go` command, closing our regtest workspaces (`./internal/lsp/fake.Workspace`) sometimes fails on windows with an error message like this:

```
C:\Users\gopher\AppData\Local\Temp\1\goplstest-ws-regtest-857411125: The process cannot access the file because it is being used by another process
```

In https://golang.org/cl/228231 I try to avoid this by deferring workspace cleanup until the end of the regtest test suite, but this is just a workaround and may break in the future.  Also, this doesn't fix the problem for other test suites, such as `./internal/lsp/lsprpc`.

One possible solution is to simply retry this cleanup until it succeeds or times out, but this is bound to be problematic. In testing it can take anywhere from 10ms to 1s for such a retry to succeed, and the retry behavior introduces a bunch of complexity that should be unnecessary.

A better solution may be related to something else we've discussed: ensure that all work done on behalf of gopls is captured in a span, and expose an API that can signal when gopls work has completed (for a workspace? for a snapshot?).  If that is not sufficient, we may want to extend this to a control plane that allows (among other things) manually terminating any processes associated with a workspace.

/cc @stamblerre @ianthehat

**Comment by findleyr** [comment]
This is in fact still a problem after the above change: https://storage.googleapis.com/go-build-log/85afa2eb/windows-amd64-2016_3d74be50.log

Need to make this fail silently again.  CC @heschik

**Comment by stamblerre** [comment]
Saw this recently: https://storage.googleapis.com/go-build-log/2333c629/windows-386-2008_d05c3521.log.

**Comment by findleyr** [comment]
Just saw this. Yes, this was fixed!
