### ISSUE TITLE
dev.boringcrypto branch behind the main releases (1.14.1b4 vs 1.14.2)

### ISSUE THREAD

**Issue by sodul** [golang/go#38492]
Similar to #36611

We are currently on 1.13.8b4 and are looking forward to upgrade to 1.14 so we can take advantage of the improvements, notably the improve management of go.mod.

Since 1.14.2 has a significant amount of bug fixes we want to skip 1.14.0 and 1.14.1 and go straight to 1.14.2.

Can you give us some input on the timeline?

Thanks again for maintaining this great branch!!!

**Comment by andybons** [comment]
@katiehockman @FiloSottile

**Comment by FiloSottile** [comment]
The release is in progress, should be done today!

**Comment by sodul** [comment]
Thanks a lot @FiloSottile !!!
