### ISSUE TITLE
gccgo: support openwrt

### ISSUE THREAD

**Issue by predators46** [golang/go#38500]
please support ggcgo openwrt I really need it, the gccgo openwrt master branch status is broken. I really don't know what I have to do. 

regrads 
Victims of sacrifice

**Comment by ianlancetaylor** [comment]
I'm sorry, if you want us to do something then we need a lot more information.  I've never used openwrt for anything.  Please tell us exactly what you did and exactly what happened.

**Comment by predators46** [comment]
thank you for the reply. I have successfully made gccgo on OpenWrt and tried to make the hello.go file and it worked. I have another problem when I make a gccgo file and the import doesn't work. I will include an error log

`  aarch64_gccgo -Wall -o ps_static_libgo server.go -static-libgo                 server.go:11:64: error: import file 'github.com/aztecrabbit/brainfuck-psiphon-pro-go/src/libpsiphon' not found
  "github.com/aztecrabbit/brainfuck-psiphon-pro-go/src/libpsiphon"
                                                                ^
server.go:12:34: error: import file 'github.com/aztecrabbit/libinject' not found
  "github.com/aztecrabbit/libinject"
                                  ^
server.go:13:31: error: import file 'github.com/aztecrabbit/liblog' not found
  "github.com/aztecrabbit/liblog"
                               ^
server.go:14:40: error: import file 'github.com/aztecrabbit/libproxyrotator' not found
  "github.com/aztecrabbit/libproxyrotator"
                                        ^
server.go:15:36: error: import file 'github.com/aztecrabbit/libredsocks' not found
  "github.com/aztecrabbit/libredsocks"
                                    ^
server.go:16:33: error: import file 'github.com/aztecrabbit/libutils' not found
  "github.com/aztecrabbit/libutils"
                                 ^
server.go:34:31: error: expected package
  ProxyRotator *libproxyrotator.Config
                               ^
server.go:35:25: error: expected package
  Inject       *libinject.Config
                         ^
server.go:37:26: error: expected package
  Psiphon      *libpsiphon.Config
                          ^
server.go:169:9: error: expected declaration
         <td id="LC107" class="blob-code blob-code-inner js-file-line">
         ^
server.go:182:73: error: expected ';' or newline after top level declaration
         <td id="LC110" class="blob-code blob-code-inner js-file-line"> }</td>
                                                                         ^
server.go:191:188: error: expected declaration
 n> <span class=pl-s1>flagFrontend</span> <span class=pl-c1>!=</span> <span class=pl-s>&quot;&quot;</span> <span class=pl-c1>||</span> <span class=pl-s1>flagWhitelist</span> <span class=pl-c1>!=</span> <span class=pl-s>&quot;&quot;</span> {</td>
                                                                                             ^

server.go:191:194: error: expected declaration
 an class=pl-s1>flagFrontend</span> <span class=pl-c1>!=</span> <span class=pl-s>&quot;&quot;</span> <span class=pl-c1>||</span> <span class=pl-s1>flagWhitelist</span> <span class=pl-c1>!=</span> <span class=pl-s>&quot;&quot;</span> {</td>
                                                                                             ^

server.go:191:320: error: expected declaration
 > <span class=pl-s1>flagWhitelist</span> <span class=pl-c1>!=</span> <span class=pl-s>&quot;&quot;</span> {</td>
                                                                                             ^

server.go:191:326: error: expected declaration
 n class=pl-s1>flagWhitelist</span> <span class=pl-c1>!=</span> <span class=pl-s>&quot;&quot;</span> {</td>
                                                                                             ^

server.go:195:189: error: expected declaration
 n> <span class=pl-s1>flagFrontend</span> <span class=pl-c1>==</span> <span class=pl-s>&quot;&quot;</span> {</td>
                                                                                             ^

server.go:195:195: error: expected declaration
 an class=pl-s1>flagFrontend</span> <span class=pl-c1>==</span> <span class=pl-s>&quot;&quot;</span> {</td>
                                                                                             ^

server.go:199:162: error: expected declaration
 >   <span class=pl-s1>flagFrontend</span> <span class=pl-c1>=</span> <span class=pl-s>&quot;*&quot;</span></td>
                                                                                             ^

server.go:199:169: error: expected declaration
 an class=pl-s1>flagFrontend</span> <span class=pl-c1>=</span> <span class=pl-s>&quot;*&quot;</span></td>
                                                                                             ^

server.go:203:74: error: expected ';' or newline after top level declaration
         <td id="LC115" class="blob-code blob-code-inner js-file-line">  }</td>
                                                                          ^
server.go:207:190: error: expected declaration
 > <span class=pl-s1>flagWhitelist</span> <span class=pl-c1>==</span> <span class=pl-s>&quot;&quot;</span> {</td>
                                                                                             ^

server.go:207:196: error: expected declaration
 n class=pl-s1>flagWhitelist</span> <span class=pl-c1>==</span> <span class=pl-s>&quot;&quot;</span> {</td>
                                                                                             ^

server.go:211:163: error: expected declaration
    <span class=pl-s1>flagWhitelist</span> <span class=pl-c1>=</span> <span class=pl-s>&quot;*:*&quot;</span></td>
                                                                                             ^

server.go:211:172: error: expected declaration
 class=pl-s1>flagWhitelist</span> <span class=pl-c1>=</span> <span class=pl-s>&quot;*:*&quot;</span></td>
                                                                                             ^

server.go:215:74: error: expected ';' or newline after top level declaration
         <td id="LC118" class="blob-code blob-code-inner js-file-line">  }</td>
                                                                          ^
server.go:228:240: error: expected declaration
 span class=pl-en>Split</span>(<span class=pl-s1>flagFrontend</span>, <span class=pl-s>&quot;,&quot;</span>),</td>
                                                                                             ^

server.go:228:247: error: expected declaration
 ass=pl-en>Split</span>(<span class=pl-s1>flagFrontend</span>, <span class=pl-s>&quot;,&quot;</span>),</td>
                                                                                             ^

server.go:232:74: error: expected ';' or newline after top level declaration
         <td id="LC122" class="blob-code blob-code-inner js-file-line">  }</td>
                                                                          ^
server.go:297:160: error: expected declaration
 e"> <span class=pl-s1>liblog</span>.<span class=pl-en>LogInfo</span>(<span class=pl-s>&quot;Domain Fronting running on port &quot;</span><span class=pl-c1>+</span><span class=pl-s1>Inject</span>.<span class=pl-c1>Config</span>.<span class=pl-c1>Port</span>, <span class=pl-s>&quot;INFO&quot;</span>, <span class=pl-s1>liblog</span>.<span class=pl-c1>Colors</span>[<span class=pl-s>&quot;G1&quot;</span>])</td>
                                                                                             ^

server.go:297:198: error: expected declaration
 pan class=pl-en>LogInfo</span>(<span class=pl-s>&quot;Domain Fronting running on port &quot;</span><span class=pl-c1>+</span><span class=pl-s1>Inject</span>.<span class=pl-c1>Config</span>.<span class=pl-c1>Port</span>, <span class=pl-s>&quot;INFO&quot;</span>, <span class=pl-s1>liblog</span>.<span class=pl-c1>Colors</span>[<span class=pl-s>&quot;G1&quot;</span>])</td>
                                                                                             ^

server.go:297:349: error: expected declaration
 span>.<span class=pl-c1>Config</span>.<span class=pl-c1>Port</span>, <span class=pl-s>&quot;INFO&quot;</span>, <span class=pl-s1>liblog</span>.<span class=pl-c1>Colors</span>[<span class=pl-s>&quot;G1&quot;</span>])</td>
                                                                                             ^

server.go:297:359: error: expected declaration
 n class=pl-c1>Config</span>.<span class=pl-c1>Port</span>, <span class=pl-s>&quot;INFO&quot;</span>, <span class=pl-s1>liblog</span>.<span class=pl-c1>Colors</span>[<span class=pl-s>&quot;G1&quot;</span>])</td>
                                                                                             ^

server.go:297:455: error: expected declaration
 an>, <span class=pl-s1>liblog</span>.<span class=pl-c1>Colors</span>[<span class=pl-s>&quot;G1&quot;</span>])</td>
                                                                                             ^

server.go:297:463: error: expected declaration
 an class=pl-s1>liblog</span>.<span class=pl-c1>Colors</span>[<span class=pl-s>&quot;G1&quot;</span>])</td>
                                                                                             ^

server.go:301:160: error: expected declaration
 e"> <span class=pl-s1>liblog</span>.<span class=pl-en>LogInfo</span>(<span class=pl-s>&quot;Proxy Rotator running on port &quot;</span><span class=pl-c1>+</span><span class=pl-s1>ProxyRotator</span>.<span class=pl-c1>Config</span>.<span class=pl-c1>Port</span>, <span class=pl-s>&quot;INFO&quot;</span>, <span class=pl-s1>liblog</span>.<span class=pl-c1>Colors</span>[<span class=pl-s>&quot;G1&quot;</span>])</td>
                                                                                             ^

server.go:301:196: error: expected declaration
 <span class=pl-en>LogInfo</span>(<span class=pl-s>&quot;Proxy Rotator running on port &quot;</span><span class=pl-c1>+</span><span class=pl-s1>ProxyRotator</span>.<span class=pl-c1>Config</span>.<span class=pl-c1>Port</span>, <span class=pl-s>&quot;INFO&quot;</span>, <span class=pl-s1>liblog</span>.<span class=pl-c1>Colors</span>[<span class=pl-s>&quot;G1&quot;</span>])</td>
                                                                                             ^

server.go:301:353: error: expected declaration
 span>.<span class=pl-c1>Config</span>.<span class=pl-c1>Port</span>, <span class=pl-s>&quot;INFO&quot;</span>, <span class=pl-s1>liblog</span>.<span class=pl-c1>Colors</span>[<span class=pl-s>&quot;G1&quot;</span>])</td>
                                                                                             ^

server.go:301:363: error: expected declaration
 n class=pl-c1>Config</span>.<span class=pl-c1>Port</span>, <span class=pl-s>&quot;INFO&quot;</span>, <span class=pl-s1>liblog</span>.<span class=pl-c1>Colors</span>[<span class=pl-s>&quot;G1&quot;</span>])</td>
                                                                                             ^

server.go:301:459: error: expected declaration
 an>, <span class=pl-s1>liblog</span>.<span class=pl-c1>Colors</span>[<span class=pl-s>&quot;G1&quot;</span>])</td>
                                                                                             ^

server.go:301:467: error: expected declaration
 an class=pl-s1>liblog</span>.<span class=pl-c1>Colors</span>[<span class=pl-s>&quot;G1&quot;</span>])</td> `

I took the file from here

**Comment by predators46** [comment]
if you want to see the results of my build you can access the repo here

[http://52.224.11.127/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_glibc/](url)

**Comment by predators46** [comment]
I made an environmental path

export PATH=/home/ubuntu/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_glibc/bin:$PATH

alias aarch64_gccgo='aarch64-openwrt-linux-gccgo -Wl,-R,/home/ubuntu/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_glibc/lib/gcc/aarch64-openwrt-linux-gnu/8.4.0 -L /home/ubuntu/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_glibc/lib'

export STAGING_DIR=~/openwrt/staging_dir/

**Comment by predators46** [comment]
file that i use
`package main

import (
	"flag"
	"fmt"
	"os"
	"runtime"
	"strings"
	"time"

	"github.com/aztecrabbit/brainfuck-psiphon-pro-go/src/libpsiphon"
	"github.com/aztecrabbit/libinject"
	"github.com/aztecrabbit/liblog"
	"github.com/aztecrabbit/libproxyrotator"
	"github.com/aztecrabbit/libredsocks"
	"github.com/aztecrabbit/libutils"
)

const (
	appName        = "Brainfuck Tunnel"
	appVersionName = "Psiphon Pro Go"
	appVersionCode = "1.3.200205"

	copyrightYear   = "2020"
	copyrightAuthor = "Aztec Rabbit"
)

var (
	InterruptHandler = new(libutils.InterruptHandler)
	Redsocks         = new(libredsocks.Redsocks)
)

type Config struct {
	ProxyRotator *libproxyrotator.Config
	Inject       *libinject.Config
	PsiphonCore  int
	Psiphon      *libpsiphon.Config
}

func init() {
	InterruptHandler.Handle = func() {
		libpsiphon.Stop()
		libredsocks.Stop(Redsocks)
		liblog.LogKeyboardInterrupt()
	}
	InterruptHandler.Start()
}

func main() {
	liblog.Header(
		[]string{
			fmt.Sprintf("%s [%s Version. %s]", appName, appVersionName, appVersionCode),
			fmt.Sprintf("(c) %s %s.", copyrightYear, copyrightAuthor),
		},
		liblog.Colors["G1"],
	)

	config := new(Config)
	defaultConfig := new(Config)
	defaultConfig.ProxyRotator = libproxyrotator.DefaultConfig
	defaultConfig.Inject = libinject.DefaultConfig
	defaultConfig.Inject.Type = 2
	defaultConfig.Inject.Rules = map[string][]string{
		"akamai.net:80": []string{
			"video.iflix.com",
			"videocdn-2.iflix.com",
			"iflix-videocdn-p1.akamaized.net",
			"iflix-videocdn-p2.akamaized.net",
			"iflix-videocdn-p3.akamaized.net",
			"iflix-videocdn-p6.akamaized.net",
			"iflix-videocdn-p7.akamaized.net",
			"iflix-videocdn-p8.akamaized.net",
		},
	}
	defaultConfig.Inject.Payload = ""
	defaultConfig.Inject.Timeout = 5
	defaultConfig.PsiphonCore = 4
	defaultConfig.Psiphon = libpsiphon.DefaultConfig

	if runtime.GOOS == "windows" {
		defaultConfig.Psiphon.CoreName += ".exe"
	}

	libutils.JsonReadWrite(libutils.RealPath("config.json"), config, defaultConfig)

	var flagPro = true
	var flagRefresh = false
	var flagVerbose = false
	var flagFrontend string
	var flagWhitelist string

	flag.BoolVar(&flagPro, "pro", flagPro, "Pro Version?")
	flag.BoolVar(&flagRefresh, "refresh", flagRefresh, "Refresh Data")
	flag.BoolVar(&flagVerbose, "verbose", flagVerbose, "Verbose Log?")
	flag.StringVar(&flagFrontend, "f", flagFrontend, "-f frontend-domains (e.g. -f cdn.com,cdn.com:443)")
	flag.StringVar(&flagWhitelist, "w", flagWhitelist, "-w whitelist-request (e.g. -w akamai.net:80)")
	flag.IntVar(&config.PsiphonCore, "c", config.PsiphonCore, "-c core (e.g. -c 4) (1 for Pro Version)")
	flag.StringVar(&config.Psiphon.Region, "r", config.Psiphon.Region, "-r region (e.g. -r sg)")
	flag.IntVar(&config.Psiphon.Tunnel, "t", config.Psiphon.Tunnel, "-t tunnel (e.g. -t 4) (1 for Reconnect Version)")
	flag.IntVar(&config.Psiphon.TunnelWorkers, "tw", config.Psiphon.TunnelWorkers, "-tw tunnel-workers (e.g. -tw 6) (8 for Pro Version)")
	flag.IntVar(&config.Psiphon.KuotaDataLimit, "l", config.Psiphon.KuotaDataLimit, "-l limit (in MB) (e.g. -l 4) (0 for Pro Version (unlimited))")
	flag.Parse()

	if !flagPro {
		config.Psiphon.Authorizations = make([]string, 0)
	}

	if flagRefresh {
		libpsiphon.RemoveData()
	}

	if flagFrontend != "" || flagWhitelist != "" {
		if flagFrontend == "" {
			flagFrontend = "*"
		}
		if flagWhitelist == "" {
			flagWhitelist = "*:*"
		}

		config.Inject.Rules = map[string][]string{
			flagWhitelist: strings.Split(flagFrontend, ","),
		}
	}

	ProxyRotator := new(libproxyrotator.ProxyRotator)
	ProxyRotator.Config = config.ProxyRotator

	Inject := new(libinject.Inject)
	Inject.Redsocks = Redsocks
	Inject.Config = config.Inject

	go ProxyRotator.Start()
	go Inject.Start()

	time.Sleep(200 * time.Millisecond)

	liblog.LogInfo("Domain Fronting running on port "+Inject.Config.Port, "INFO", liblog.Colors["G1"])
	liblog.LogInfo("Proxy Rotator running on port "+ProxyRotator.Config.Port, "INFO", liblog.Colors["G1"])

	if _, err := os.Stat(libutils.RealPath(config.Psiphon.CoreName)); os.IsNotExist(err) {
		liblog.LogInfo(fmt.Sprintf(
			"Exception:\n\n"+
				"|	 File '%s' not exist!\n"+
				"|	 Exiting...\n"+
				"|\n",
			config.Psiphon.CoreName),
			"INFO", liblog.Colors["R1"],
		)
		return
	}

	Redsocks.Config = libredsocks.DefaultConfig
	Redsocks.Start()

	for i := 1; i <= config.PsiphonCore; i++ {
		Psiphon := new(libpsiphon.Psiphon)
		Psiphon.ProxyRotator = ProxyRotator
		Psiphon.Config = config.Psiphon
		Psiphon.ProxyPort = Inject.Config.Port
		Psiphon.KuotaData = libpsiphon.DefaultKuotaData
		Psiphon.ListenPort = libutils.Atoi(ProxyRotator.Config.Port) + i
		Psiphon.Verbose = flagVerbose

		go Psiphon.Start()
	}

	InterruptHandler.Wait()
} `

**Comment by predators46** [comment]
I found this guide. but I have to export file.gox, but I don't understand how to export file.gox

https://www.sajalkayan.com/post/golang-openwrt-mips.html

**Comment by predators46** [comment]
`                                           ^
ubuntu@ubuntu:~/openwrt$ aarch64_gccgo -v -u -d github.com/aztecrabbit/brainfuck-psiphon-pro-go         aarch64-openwrt-linux-gccgo: error: github.com/aztecrabbit/brainfuck-psiphon-pro-go: No such file or directory
Reading specs from /home/ubuntu/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_glibc/lib/gcc/aarch64-openwrt-linux-gnu/8.4.0/specs
COLLECT_GCC=aarch64-openwrt-linux-gccgo
COLLECT_LTO_WRAPPER=/home/ubuntu/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_glibc/libexec/gcc/aarch64-openwrt-linux-gnu/8.4.0/lto-wrapper
Target: aarch64-openwrt-linux-gnu
Configured with: /home/ubuntu/openwrt/build_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_glibc/gcc-8.4.0/configure --with-bugurl=http://bugs.openwrt.org/ --with-pkgversion='OpenWrt GCC 8.4.0 r12999-edf812e25c' --prefix=/home/ubuntu/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_glibc --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --target=aarch64-openwrt-linux-gnu --with-gnu-ld --enable-target-optspace --disable-libgomp --disable-libmudflap --disable-multilib --disable-libmpx --disable-nls --without-isl --without-cloog --with-host-libstdcxx=-lstdc++ --with-gmp=/home/ubuntu/openwrt/staging_dir/host --with-mpfr=/home/ubuntu/openwrt/staging_dir/host --with-mpc=/home/ubuntu/openwrt/staging_dir/host --disable-decimal-float --with-diagnostics-color=auto-if-env --enable-libssp --enable-__cxa_atexit --with-headers=/home/ubuntu/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_glibc/include --enable-languages=c,c++,go --enable-shared --enable-threads --with-slibdir=/home/ubuntu/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_glibc/lib --enable-lto --with-libelf=/home/ubuntu/openwrt/staging_dir/hostThread model: posix
gcc version 8.4.0 (OpenWrt GCC 8.4.0 r12999-edf812e25c) 
ubuntu@ubuntu:~/openwrt$ `

**Comment by ianlancetaylor** [comment]
It looks like you are trying to build by running gccgo directly.  Don't do that unless you really know what you are doing.  Build using `go build`.

**Comment by predators46** [comment]
It looks like GCCGO on OpenWRT can't go build, maybe there is no hope of using GCCGO on OpenWRT

**Comment by predators46** [comment]
thanks for the reply, I think it's enough to end here I will close this problem, but in my heart I want to use gccgo on OpenWrt but in the master branch GCCOO status is broken as long as eglibc is deleted in OpenWrt
