### ISSUE TITLE
proposal: cmd/go: command line flag to add icon for windows executable

### ISSUE THREAD

**Issue by pjebs** [golang/go#38509]
There should be a command line flag to `go build` to add an icon to the executable file.

**Comment by ianlancetaylor** [comment]
I would guess that you can do this by adding a file with a `.syso` extension with an appropriate resource section.  That seems more convenient than a `go build` option, since it will work even if you forget to use the command line option.

**Comment by pjebs** [comment]
A syso file can be used to embed all sorts of different resources and not just a icon.
I assume adding an icon would be the overwhelming use-case. Generating a sysco file using an external application such as https://github.com/josephspurrier/goversioninfo would be overkill if one merely wants to add an icon and nothing else.

**Comment by ianlancetaylor** [comment]
I don't understand why generating a .syso file is overkill.  Sure, it can do a lot more than add an icon.  So what?  If you want to add an icon, you have to have an icon file.  It's one more command, run exactly once, to turn that icon file into a .syso file.  Then you're done.

A .syso file has another advantage: it is always there, so you don't have to add a command line option when you run `go build` or `go install`.  It just works.

**Comment by rsc** [comment]
This proposal has been added to the [active column](https://golang.org/s/proposal-status#active) of the proposals project
and will now be reviewed at the weekly proposal review meetings.
— rsc for the proposal review group

**Comment by tc-hib** [comment]
> I assume adding an icon would be the overwhelming use-case.

I don't think so.
The only resource that may really be necessary is the manifest.

The icon is cosmetic, and we often want to add "version info" because it is also displayed in the explorer:

![image](https://user-images.githubusercontent.com/55949036/126556956-e306cf21-e4fa-4ad5-b67d-306a48b587dd.png)

**Comment by rsc** [comment]
Based on the discussion above, this proposal seems like a **[likely decline](https://golang.org/s/proposal-status#likely-decline)**.
— rsc for the proposal review group

**Comment by rsc** [comment]
No change in consensus, so **[declined](https://golang.org/s/proposal-status#declined)**.
— rsc for the proposal review group
