### ISSUE TITLE
crypto/rsa: hexadecimal string not accepted as argument to PrivateKey.Sign

### ISSUE THREAD

**Issue by Altruiste1** [golang/go#38511]
### What version of Go are you using (`go version`)?

<pre>
$ go version
 go1.13
</pre>

### Does this issue reproduce with the latest release?
yes
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
 darwin/amd64
</pre></details>

### What did you do?

When I was using rsa2 way for signature found a problem, Java support with signature string generated sha256 in this paper, and put the paper into hex byte, after rsa2 signature, but go seems barely support, only support for the direct generation rsa2 signature, when I try to do like Java, triggered panic at compile time, "crypto/rsa: input must be hashed message".

java代码
```Java
//digest through SHA256 and convert to hexadecimal
public static byte[] sha256X16(String data, String encoding) {
		byte[] bytes = sha256(data, encoding);
		StringBuilder sha256StrBuff = new StringBuilder();
		for (int i = 0; i < bytes.length; i++) {
			if (Integer.toHexString(0xFF & bytes[i]).length() == 1) {
				sha256StrBuff.append("0").append(
						Integer.toHexString(0xFF & bytes[i]));
			} else {
				sha256StrBuff.append(Integer.toHexString(0xFF & bytes[i]));
			}
		}
		try {
			return sha256StrBuff.toString().getBytes(encoding);
		} catch (UnsupportedEncodingException e) {
			LogUtil.writeErrorLog(e.getMessage(), e);
			return null;
		}
	}
// generate rsa2Sign
//// data：[]byte("285fd3e7cbb9b79881647f74205a369dc6ab68b4227e3f07bc47e352dedbd122")
		public static byte[] signBySoft256(PrivateKey privateKey, byte[] data)
			throws Exception {
		byte[] result = null;
		Signature st = Signature.getInstance(BC_PROV_ALGORITHM_SHA256RSA);
		st.initSign(privateKey);
		st.update(data);
		result = st.sign();
		Signature signature = Signature.getInstance("SHA256withRSA");
		signature.initSign(privateKey);
		signature.update(data);
		String sign=Base64.encodeBase64String(signature.sign());
		return result;
	}

```
//golang Code snippet
```Go
         //s := sha256.New()
	//_, err := s.Write([]byte(signData))
	//if err != nil {
	//	panic(err)
	//}
	//hashByte := s.Sum(nil)
	//var digestStr string
	//for _,v:=range hashByte{
	//	digestStr+=strconv.FormatInt(int64(v), 16)
	//}
	//signByte, err := this.PrivateKey.Sign(rand.Reader, hashByte, crypto.SHA256)
	//if err != nil {
	//	panic(err)
	//}
    signDigest:= []byte("285fd3e7cbb9b79881647f74205a369dc6ab68b4227e3f07bc47e352dedbd122")
    signByte, err := this.PrivateKey.Sign(rand.Reader, signDigest, crypto.SHA256)
    if err != nil {
        panic(err)
    }
   signedStr:=base64.StdEncoding.EncodeToString(signByte)
```
### What did you expect to see?
After golang converts the digest to hexadecimal and signs it, it gets the same result as a Java signature
### What did you see instead?
err:crypto/rsa: input must be hashed message
It appears to check the hash value and length of the digest，After commenting out the code  I got a signature, but the result was not consistent with what Java got

**Comment by andybons** [comment]
@katiehockman @FiloSottile

**Comment by FiloSottile** [comment]
The Go crypto libraries never encode or decode hex, but operate on raw bytes, as the primitives are defined. Use encoding/hex to decode your hash.
