### ISSUE TITLE
x/pkgsite: show README.md of "subpackages" in overview tab

### ISSUE THREAD

**Issue by sbinet** [golang/go#38513]
currently, go.dev does a nice job for presenting the `README.md` page for the "top-level" module (usually corresponding to the root of a repository) when clicking on the "overview" page:
- https://pkg.go.dev/go-hep.org/x/hep?tab=overview

it would be nice if, when going to "subdirectories", the "overview" tab could display the corresponding `README.md` page, if any.

_i.e._, it would be nice if the following link (`"hplot"` subdir of `go-hep.org/x/hep` module):
- https://pkg.go.dev/go-hep.org/x/hep@v0.26.0/hplot?tab=overview

would display the README page of:
- https://github.com/go-hep/hep/blob/master/hplot/README.md
(with all the nice images)

that would help with creating nice looking documentation+examples for packages that need to show images (which isn't the core thing of godoc _per se_)

**Comment by julieqiu** [comment]
Thanks for the feedback! We are planning to add this feature in an upcoming round of design changes.

**Comment by julieqiu** [comment]
This feature is now available on [beta.pkg.go.dev](https://beta.pkg.go.dev). See https://github.com/golang/go/issues/41585#issuecomment-718143563 for details.

Closing this issue for https://github.com/golang/go/issues/41586.

**Comment by sbinet** [comment]
thanks! looking great.
