### ISSUE TITLE
reflect: should not be allowed to invoke methods on unexported embedded fields

### ISSUE THREAD

**Issue by mdempsky** [golang/go#38521]
Test program: https://play.golang.org/p/Jnga2_6Rmdf

Currently the v.M() and v.u.M() calls successfully print "M", but the v.u2.M() call panics due to accessing an unexported field.

I think the v.u.M() line should also panic. v.u is unexported just like v.u2, and the promoted method is already exposed on v's method set, so there's no need to be able to invoke v.u.M() via reflection. (This distinguishes it from accessing promoted *fields*, which requires allowing traversal through unexported fields.)

I think reflect.Value.Method should have been updated to use v.flag.ro() in golang.org/cl/66331 like all the other methods. I suspect I just overlooked it because it didn't fit the pattern of all the other cases.

/cc @ianlancetaylor

**Comment by mvdan** [comment]
Do we want to merge this change now, and see if anyone raises an issue about it during the freeze and betas/RCs?

**Comment by ianlancetaylor** [comment]
I can't help but note that the sample program shows a terrible error message.

    reflect: reflect.flag.mustBeExported using value obtained using unexported field
