### ISSUE TITLE
runtime: "fatal error: PowerRegisterSuspendResumeNotification failure" when run golang hello world binary in Azure web app

### ISSUE THREAD

**Issue by ruixue8080** [golang/go#38523]
### What version of Go are you using (`go version`)?

<pre>
I build my "hello world" golang program binary locallly(binary built is "go-hello-world.exe"), which install go version  go1.14 windows/amd64

</pre>

### Does this issue reproduce with the latest release?

Not test

### What operating system and processor architecture are you using (`go env`)?

The binary is build in Windows system

### What did you do?
I built my hello world binary locally using go version 1.14, and upload this binary into Azure web app. I suppose under Azure webs app, I can run this binary, however, it throw exception: 
runtime: PowerRegisterSuspendResumeNotification failed with errno= 5
fatal error: runtime: PowerRegisterSuspendResumeNotification failure

### What did you expect to see?

I expect when I run "go-hello-world.exe" in Azure web app, it can be run successfully, and output "hello world" 

### What did you see instead?
it throw exception:
runtime: PowerRegisterSuspendResumeNotification failed with errno= 5
fatal error: runtime: PowerRegisterSuspendResumeNotification failure

**Comment by networkimprov** [comment]
I think this is fixed in 1.14.2. Could you run `go version` and report which release you have?

First reported in #37149
@gopherbot add OS-Windows

**Comment by ruixue8080** [comment]
go version go1.14 windows/amd64
I build the exe file in environment which installed version "go1.14 windows/amd64", but the environment which run the "go-hello-world.exe" do not install go, will this matter? My understanding is that there is no need to install go package to run the exe file.

**Comment by ruixue8080** [comment]
@networkimprov thanks a lot, I reinstall go version 1.14.2, it works now!

**Comment by networkimprov** [comment]
Glad to help. Correct, you do not need Go installed on the environment where the app runs.

You can close this issue.
