### ISSUE TITLE
go1.13.10 command not found

### ISSUE THREAD

**Issue by billythakidd04** [golang/go#38533]
### What version of Go are you using (`go version`)?

<pre>
$ go get golang.org/dl/go1.13.10
$ go1.13.10 download
go1.13.10: command not found
$ go version
go version go1.14.2 linux/amd64
</pre>

Following [these instructions](https://golang.org/doc/install#extra_versions)
### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
 go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/thakidd/.cache/go-build"
GOENV="/home/thakidd/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/thakidd/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build484129548=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you expect to see?
I expected to be able to side load 1.13.10

**Comment by agnivade** [comment]
This is likely a problem with your $GOPATH/bin not part of $PATH. And not an issue with Go.

Are you able to "go get" other binaries ? Like `go get golang.org/x/perf/cmd/benchstat` ?
