### ISSUE TITLE
x/blog: https://blog.golang.org/10years missing images

### ISSUE THREAD

**Issue by andrius4669** [golang/go#38532]
I randomly noticed https://blog.golang.org/10years not having any images, even though there are links for them I see no img elements.
https://web.archive.org/web/20191109121218/https://blog.golang.org/10years properly have them.

### What did you expect to see?
![Screenshot from 2020-04-20 03-07-28](https://user-images.githubusercontent.com/4699695/79703375-1c600380-82b4-11ea-820d-09c35f320ddc.png)

### What did you see instead?
![Screenshot from 2020-04-20 03-04-28](https://user-images.githubusercontent.com/4699695/79703340-da36c200-82b3-11ea-9774-e2f422432eae.png)

**Comment by andrius4669** [comment]
(tested in both chromium and firefox but it's missing stuff in HTML so irrelevant)

**Comment by andrius4669** [comment]
https://archive.vn/Tp0lc captured for the record

**Comment by mvdan** [comment]
@dmitshur @andybons

**Comment by smasher164** [comment]
Bisecting blog identifies https://github.com/golang/blog/commit/d69e13551fa530db489dc386e648795a15bc11a9 as the first bad commit, which pulls in https://github.com/golang/tools/commit/e609210bcd3f from x/tools.
/cc @rsc

**Comment by egonelbre** [comment]
It looks like `tools/present` parsing doesn't support `.image` nested inside an `a` tag anymore:
```
<a href="10years/gopher10th-large.jpg">
.image 10years/gopher10th-small.jpg _ 850
</a>
```

**Comment by seankhliao** [comment]
Closing as this appears to be fixed

**Comment by egonelbre** [comment]
@seankhliao there still seems to be a formatting issue here https://go.dev/blog/gophergala.

![2021-09-14 14_24_31-Window](https://user-images.githubusercontent.com/192964/133249138-d2792e25-caf6-4fd0-a488-87e7f637fbc0.png)
