### ISSUE TITLE
not support mips64le go installation package for make docker official image (https://golang.org/dl/)

### ISSUE THREAD

**Issue by XiaodongLoong** [golang/go#38536]
Recently I make golang docker images based on debian:stretch image with the guidance of  
 the `docker-library/official-images` project. In order to make golang docker image that I need, I must download the golang software installation package from URL: https://golang.org/dl/, but I cannot found the software installation package on linux-mips64el.

### What version of Go are you using (`go version`)?
version golang1.6 +  support mips64le arch.
<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOOS=linux
GOARCH=mips64le
</pre></details>

### What did you expect to see?
Everybody can download the golang installation package on mips64le from  [https://golang.org/dl/](url)

**Comment by ALTree** [comment]
Hi,

from the [Porting Policy page](https://github.com/golang/go/wiki/PortingPolicy#first-class-ports), First Class Ports section:

> Some ports are considered "first class". The distinction is mostly about releases and distribution.
>
> A first class port has these properties:
>    - Broken builds block releases
>        + All contributors are effectively responsible for these ports (You break it, you fix it, or find someone who can.)
>    - Official binaries are provided
>       + Requires Google's Go team to own the builder machine
>    - Installation is documented at https://golang.org/doc/install
>
> Graduating a port to "first class" is at the discretion of the Go team at Google.

Follows a list of the First Class Ports. ppc64le is not a first class port, so official binaries are not provided. Users need to build the toolchain themselves: https://golang.org/doc/install/source

**Comment by XiaodongLoong** [comment]
Do we need to provide you with machines on mips64le cpu arch? Is the simulation based on qemu or virtual machine solution OK?

**Comment by ianlancetaylor** [comment]
We don't have the resources to build Go releases for every single target that Go supports.

Instead of providing us with machines, I recommend that you build mips64le releases yourself and make them available for anyone who wants them.  Thanks.
