### ISSUE TITLE
I hope that I can also use GOPROXY to download package in GOPATH mode

### ISSUE THREAD

**Issue by rocket049** [golang/go#38535]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/fuhz/.cache/go-build"
GOENV="/home/fuhz/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="*.gitee.com"
GONOSUMDB="*.gitee.com"
GOOS="linux"
GOPATH="/home/fuhz/go"
GOPRIVATE="*.gitee.com"
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build333641992=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you expect to see?

I hope that I can also use goproxy to download package in gopath mode. I'm a programmer in China. I like golang very much. In China, it is very slow to visit GitHub, and even unable to access golang.org. Only in module mode can packages be downloaded at high speed through goproxy.io. At present, in some cases, we still have to work in gopath mode. At present, my method is to download the package in module mode, and then copy the package to the vendor directory with the 'go mod vendor' command. If we can download the package directly through goproxy mode, we can greatly improve the work efficiency. Therefore, I strongly recommend to implement this function.

**Comment by kingreatwill** [comment]
Then use go module!

**Comment by mvdan** [comment]
GOPROXY is a setting for go module proxies, so it will only work in module mode, and to download modules. It can't be used to download single packages. See `go help goproxy`.

GOPATH will be gradually replaced with modules. If you encounter issues using module mode, please file issues. Aside from that, I think using module mode should be fine for practically everyone today.

**Comment by rocket049** [comment]
If I can use module mode, I will use module mode, but module mode is not omnipotent. Some packages cannot be used in module mode, such as 'github.com/therecipe/qt', which I often use.

**Comment by mvdan** [comment]
If some packages cannot be used in module mode due to a bug, please file that bug. I think that's the right course of action, instead of trying to add features to GOPATH mode.

**Comment by bcmills** [comment]
We don't plan to significantly improve GOPATH mode at this point.

As @mvdan suggests, if there are problems that prevent you from using packages in module mode, please ensure that issues have been filed for those specific problems. (Feel free to mention specific impacted packages on issues in the issue tracker — having concrete examples helps us to understand and prioritize those issues.)

**Comment by rocket049** [comment]
This is a simple example:

```
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/widgets"
)

func main() {
	app := widgets.NewQApplication(len(os.Args), os.Args)
	window := widgets.NewQDialog(nil, core.Qt__Window)
	window.SetWindowTitle("Hello Friend")
	layout := widgets.NewQVBoxLayout()
	label := widgets.NewQLabel2("Hello Friend!", window, core.Qt__Widget)
	layout.AddWidget(label, 1, 0)
	window.SetLayout(layout)
	app.SetActiveWindow(window)
	window.Show()
	app.Exec()
}

```

[how to](https://github.com/therecipe/qt/wiki/Installation-on-Linux)
