### ISSUE TITLE
runtime: can preempt running G asynchronously by sending sigurg while asyncpreemptoff is set

### ISSUE THREAD

**Issue by koushki** [golang/go#38531]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.14.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build332853226=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
While using `GODEBUG=asyncpreemptoff=1` if you send a `sigurg` sig to a thread, the scheduler will preempt the running G.

```go
package main

import (
	"fmt"
	"runtime"
	"time"
	"golang.org/x/sys/unix"
)

func main() {
	runtime.GOMAXPROCS(1)
	go func() {
		fmt.Printf("tid %d\n", unix.Gettid())
		for {
		}
	}()
	time.Sleep(time.Second)
	fmt.Println("Done!")
}
```
then run it with asyncpreemptoff
```
GODEBUG=asyncpreemptoff=1 go run main.go
tid 2782
```
now use the tid to send the sig 
```
kill -s sigurg 2782
```

### What did you expect to see?
Since we use `asyncpreemptoff=1` i expect the app **shouldn't** be finished!

### What did you see instead?
the program prints `Done!`

**Comment by ianlancetaylor** [comment]
CC @aclements @cherrymui

**Comment by cherrymui** [comment]
We could do let SIGURG not preempt if asyncpreemptoff is set.

I wonder what is the reason behind this. Are you running a program that you don't want to be preempted and it also receives  external SIGURGs?

**Comment by koushki** [comment]
I don't have specific use case, i was checking how preemption is implemented and find this problem, however i think if somebody wants to use `asyncpreemptoff` flag, he/she wants to prevent preemption for some specific reason, but this is only my assumption.

**Comment by networkimprov** [comment]
Backport candidate?

Also the CL didn't include a test to verify that preemption is disabled...

**Comment by cherrymui** [comment]
I don't think this needs backport. As @koushki noted, it doesn't seem to affect any real program (for now).

**Comment by networkimprov** [comment]
And re the lack of a test for preemption disabled?
