### ISSUE TITLE
x/pkgsite: prerelease info truncated in version list

### ISSUE THREAD

**Issue by rsc** [golang/go#38542]
---------- Forwarded message ---------
From: <volf.tomas@gmail.com>
Date: Mon, Apr 20, 2020 at 1:55 PM
Subject: [golang-dev] pkg.go.dev does not display whole version
To: golang-dev <golang-dev@googlegroups.com>

I have a module using semantic versioning (1.0.0-pre-release+1), which
according to https://semver.org/ should be correct semver. However when
I check my package at pkg.go.dev:

https://pkg.go.dev/mod/git.sr.ht/~graywolf/gomemcache?tab=versions

I see

 v1 – git.sr.ht/~graywolf/gomemcache 
   v1.0.0 (8786112) – 0 hours ago 
   v1.0.0 (58609c4) – 1 hour ago 

without listing the whole version string. I think that is kinda confusing. Sincehttps://go.dev/about mentions this mailing list to send suggestiongs to, I thinkit would be nice to list whole version string.
Have a nice day,W.

**Comment by julieqiu** [comment]
Thanks for the feedback! The reason this was truncated was to make the version string more readable for pseudoversions, since they can be pretty long. I agree that this is less precise, and we might want to consider display the version string as is. 

/cc @spf13 @fflewddur for product/UX input

**Comment by spf13** [comment]
Agree this needs fixing. I think there is a solution that handles the case of pseudoversions explicitly by shortening that pattern to something reasonable, and then allows for any other versions like this to be displayed.

**Comment by freeformzSFDC** [comment]
FWIW: "1.0.0-pre-release+1" is 19 characters, "1.0.0 (8786112)" is 15 characters.  So the difference in visible space is ~4-8 characters AFAICT.

**Comment by julieqiu** [comment]
In this case, the full version string would be `v1.0.0-pre-release.0.20200420093620-87861123c523`. See https://proxy.golang.org/git.sr.ht/~graywolf/gomemcache/@latest.

**Comment by spf13** [comment]
I see, I misunderstood, this example is itself a pseudoversion, not a released version. It's less clear what to do here. Maybe just truncate the pseudoversion portion of the version string? Not sure if that makes sense or would be hard to do reliably.

**Comment by spf13** [comment]
@Joanne881107, any ideas? :)

**Comment by bcmills** [comment]
You might consider stripping off the “base” from which the pseudo-version is derived¹ and reporting that along with the commit hash.

That said, I'm not sure what's wrong with showing the complete pseudo-version in the first place...

¹https://github.com/golang/go/blob/e221a75deab7843d5414154000f5bea7abcb60c3/src/cmd/go/internal/modfetch/pseudo.go#L149-L154

**Comment by Joanne881107** [comment]
There are 2 places we would need to display the version number:
1. Version info on the header: In this case, it's better to truncate the version string to make it more readable. My suggestion is maybe use "1.1.0-pre-release" instead? Or truncated the string as "1.1.0-pre-release...23", when hover on the string, show a tooltip display the entire string. 
2. Version info in "versions" tab: In this case, I think it's fine to display the entire string.

**Comment by julieqiu** [comment]
The suggestions from https://github.com/golang/go/issues/38542#issuecomment-618068063 have been implemented. Logic for the truncated version string is described in https://go-review.googlesource.com/c/pkgsite/+/254578.

See https://github.com/golang/go/issues/42280 as a follow up for usability improvements for truncated version strings.
