### ISSUE TITLE
"gofmt -d" should have non-zero exit if there is a diff

### ISSUE THREAD

**Issue by belm0** [golang/go#38551]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### What did you do?

```
$ gofmt -d .
(... diff ...)
$ echo $?
0
```
### What did you expect to see?

Exit value of 1, since there is a diff.

Presence of a diff is the error case, meaning that the code requires formatting.  Then for example, makefile targets to check formatting can simply be "gofmt -d ." and do the right thing.

### What did you see instead?

exit value of 0

**Comment by ALTree** [comment]
Hi, 

this was requested in #24230 and #24427, and rejected. As noted in #24230, you can already check if `gofmt -l` is empty. Closing here as a dup of #24230.
