### ISSUE TITLE
Go build fails with: "argument list too long"

### ISSUE THREAD

**Issue by ronanwatkins** [golang/go#38569]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rwatkins/Library/Caches/go-build"
GOENV="/Users/rwatkins/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/rwatkins/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tg/vy60kxxx5p11s39hg7hsjvd40000gn/T/go-build869462835=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Ran "go build" on our project directory which contains 1919 go files

### What did you expect to see?
Go building successfully (As happens with my teammates who have the same setup)

### What did you see instead?
/usr/local/go/pkg/tool/darwin_amd64/compile: fork/exec /usr/local/go/pkg/tool/darwin_amd64/compile: argument list too long

**Comment by ALTree** [comment]
Thanks for reporting the issue. This is a dup of #37768, so I'm closing here in favour of the older thread. Feel free to subscribe to that one.
