### ISSUE TITLE
x/tools/gopls: add configuration to disable links on hover

### ISSUE THREAD

**Issue by shreyaskarnik** [golang/go#38573]
I am using gopls with VSCode and have the following setup in settings:
```json
"go.languageServerExperimentalFeatures": {
    "documentLink": false,
  }
```

but still I see links to the documents 
![image](https://user-images.githubusercontent.com/311217/79913642-cf298200-83d8-11ea-9593-fd1e2c06f7fd.png)

### What version of Go are you using (`go version`)?

<pre>
$ go version go1.14.2 darwin/amd64

</pre>

gopls version information 
```
golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=
```

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
</pre></details>

### What did you expect to see?
I expected the links to be disabled

**Comment by stamblerre** [comment]
`documentLink` refers to the feature that makes links that appear in strings or comments clickable. There is no setting to control the links to the documentation that appear on hover (other than `"gopls": { "hoverKind": "NoDocumentation"` }, which would remove all documentation as well as the links).

**Comment by shreyu86** [comment]
@stamblerre thanks for the response! This release of gopls has been very stable and feature packed 🙌 ! Thanks again to everyone who made this possible!

**Comment by stamblerre** [comment]
Glad to hear that it's working for you, @shreyu86! Thank you for the kind words!

I'll leave this issue open to see if we can add another configuration to remove the links on hover.

**Comment by stamblerre** [comment]
Sorry for the delay on this, @shreyaskarnik! I just realized we do have that configuration, actually.
Does adding the following your `settings.json` resolve the issue?

```json5
"gopls": {
	"linkTarget": ""
}
```

**Comment by stamblerre** [comment]
Looks like that worked. Closing this issue.

**Comment by shreyaskarnik** [comment]
Thanks @stamblerre that worked!
