### ISSUE TITLE
runtime code question

### ISSUE THREAD

**Issue by zxxshaycormac** [golang/go#38585]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xieyc.KST\AppData\Local\go-build
set GOENV=C:\Users\xieyc.KST\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS= -mod=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\workplace
set GOPRIVATE=
set GOPROXY=http://goproxy.cn,direct
set GOROOT=D:\Go
set GOSUMDB=goproxy.cn
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\workplace\src\navi\kvp-mps\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\xieyc.KST\AppData\Local\Temp\go-build502711282=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I just looked at the code and had some questions.

### What did you expect to see?

I think when `len(_p_.runq) == 0` the `n` will be zero too.
If `n == 0` then `sched.runqsize -= n` will not going to change `sched.runqsize` length.
But we still do `gp := sched.runq.pop()` pop from `sched.runq`.
Won't this cause `sched.runqsize` to be different from `len(sched.runq)`?
Wouldn't that make a difference?

### What did you see instead?

You can go to `go/src/runtime/proc.go` `func globrunqget` to see this
```go
// Try get a batch of G's from the global runnable queue.
// Sched must be locked.
func globrunqget(_p_ *p, max int32) *g {
	if sched.runqsize == 0 {
		return nil
	}

	n := sched.runqsize/gomaxprocs + 1
	if n > sched.runqsize {
		n = sched.runqsize
	}
	if max > 0 && n > max {
		n = max
	}
	if n > int32(len(_p_.runq))/2 {
		n = int32(len(_p_.runq)) / 2
	}

	sched.runqsize -= n

	gp := sched.runq.pop()
	n--
	for ; n > 0; n-- {
		gp1 := sched.runq.pop()
		runqput(_p_, gp1, false)
	}
	return gp
}
```

**Comment by mdlayher** [comment]
The Go issue tracker is not used for questions. I would recommend posting this to a mailing list such as golang-nuts, as there are a lot of knowledgeable folks there who will likely have more context. Thanks!
