### ISSUE TITLE
x/tools/gopls:  whether or not the files are under git affects gopls's behaviour?

### ISSUE THREAD

**Issue by zbelial** [golang/go#38582]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes. 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/mnt/Personal/Bin/go-tools"
GOCACHE="/home/lucency/.cache/go-build"
GOENV="/home/lucency/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/lucency/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/mnt/Personal/Bin/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/mnt/Personal/Bin/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build444708836=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I use Emacs 27 + eglot.
I want to use another module in a module and I want to put all files under a git repo. 

0. Suppose you're in a directory D, which is not a git repo **NOW**.
1. Follow the Working Example in the accepted answer in the next link. When you finish and open osinf.go, things(I mean go to definition, hover and completion) work well.
[so link](https://stackoverflow.com/questions/52328952/how-to-use-a-module-that-is-outside-of-gopath-in-another-module)
2. Close osinf.go and exit Emacs.
3. Execute `git init . && git add .` in diretory D.
4. Reopen osinf.go, things do not work now.

### What did you expect to see?
Go to definition, completion work as expected.

### What did you see instead?
You are neither in a module nor in your GOPATH.

### Other
It seems that when files are under git, gopls will take that into account and ignore(?) go.mod in some degree. 
Is this the expected behaviour? If so, is there any way to work around it? 

Thanks.

**Comment by stamblerre** [comment]
Whether or not the files are tracked in git should have no effect on the functionality of `gopls`. Can you please provide `gopls` logs where you are seeing this behavior?

**Comment by zbelial** [comment]
Hi @stamblerre , thanks for you reply.
1. Sorry that I've not found how to get `gopls` logs now. I tried to use `gopls serve -logfile $HOME/gopls.log` to start gopls in Emacs, but  gopls.log was empty.  But
2. I found something else. 
Suppose the following is the dir layout.
```
D
├── osinf
│   ├── go.mod
│   └── osinf.go
└── pretty
    ├── go.mod
    └── pretty.go
```
If D is under git, then `eglot` will use D as the project root (`eglot` uses another package, `project`,  to guess the project root, and `project` checks whether there is `.git` (or `.hg` ...) in directory tree upwards ), and pass D as `:rootUri` and `:rootPath` to `gopls`. 

But if D is **NOT** under git, `eglot` just uses the current directory ( `D/osinf` or `D/pretty` here) as project root and starts two `gopls` instances respectively when opening osinf.go and pretty.go 

So maybe this is the reason why `gopls` behaves differently?

**Comment by stamblerre** [comment]
Ah, yes that's probably it. Is there any way for you to manually configure the project root? You'll need to open `gopls` with the root of your module or a subdirectory (though this is something we're working on improving in the future). This may be something to ask in the `eglot` issue tracker.

**Comment by zbelial** [comment]
It is Emacs, in which you can do anything you want to do :) So Yes, I've figured out how to configure the project root. 
`gopls` works great for me now, thank you and all guys who hard work for this project. 
I'll close this issue now.
Wish you a good day!
