### ISSUE TITLE
runtime: TestLockedDeadlock2 failure on solaris-amd64-oraclerel builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#38598]
[2020-04-22T17:30:07-81df5e6/solaris-amd64-oraclerel](https://build.golang.org/log/f507db243d80b65c73bc4d433e2abe9929f9a105)

See previously #35393, #35274.

The test was terminated with `SIGQUIT` after a full minute, so it appears that the deadlock detector failed to trigger.

It's not obvious to me whether this is a regression or an existing low-probability bug, so I'm milestoning it to Go 1.15 but not marking it release-blocker just yet.

CC @ianlancetaylor @aclements

**Comment by ianlancetaylor** [comment]
This seems to have happened exactly once.  Closing optimistically as a machine flake.
