### ISSUE TITLE
database/sql: TestTxCannotCommitAfterRollback failures on windows-amd64-2008 builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#38597]
[2020-04-22T16:45:05-141b11d/windows-amd64-2008](https://build.golang.org/log/1a02c2c1eb605b64cf5ab9061a5249ca3325840d)
[2020-04-20T20:22:51-7004be9/windows-amd64-2008](https://build.golang.org/log/b02b78c1c77f5a2a874962a566feef7621acd617)

These failures occurred just after [CL 227278](https://golang.org/cl/227278) for #38058 (which, coincidentally, appears to have been merged without a corresponding regression test).

Marking as release-blocker for Go 1.15, since this appears to be a regression.

CC @kardianos @odeke-em @colinking

**Comment by kardianos** [comment]
@bcmills The commit right before is not relevant. I'm not sure a new test for that commit would be beneficial.

The flaking test is a new test merged in https://go-review.googlesource.com/c/go/+/216240 two days ago. The CL fixes a real issue, but harder to test for. I'll look into the Test to try to determine why it is flaking.

**Comment by dmitshur** [comment]
@gopherbot Please backport to Go 1.14. This is a fix for a flaky test. A flaky test makes release testing more difficult and less accurate.
