### ISSUE TITLE
runtime: TestSegv consistently failing on NetBSD

### ISSUE THREAD

**Issue by bcmills** [golang/go#38595]
The `TestSegv` function added in [CL 228900](https://golang.org/cl/228900) is failing consistently on the NetBSD 9.0 builders:

```
--- FAIL: TestSegv (0.00s)
    --- FAIL: TestSegv/Segv (0.01s)
        crash_cgo_test.go:569: 
        crash_cgo_test.go:571: expected crash from signal
    --- FAIL: TestSegv/SegvInCgo (0.01s)
        crash_cgo_test.go:569: 
        crash_cgo_test.go:571: expected crash from signal
…
FAIL
FAIL	runtime	41.529s
```

[2020-04-22T00:01:14-e5bd6e1/netbsd-386-9_0](https://build.golang.org/log/7fdd891fa8dd6a4899c04f758d9f41ea6ced27c8)
[2020-04-22T00:01:14-e5bd6e1/netbsd-amd64-9_0](https://build.golang.org/log/dd547a9133c41d38ea6c4c0e5a7c5d8541c7b7b2)

It's not clear to me whether the problem is in the test, the runtime, or the NetBSD kernel.

CC @ianlancetaylor @aclements

**Comment by josharian** [comment]
Doesn't look like this is NetBSD-only. Looking at build.golang.org right now I see

darwin/amd64: https://build.golang.org/log/bf1f5e4990da13a459eec28e6eb3741ea253a084

linux/386: https://build.golang.org/log/bb4f8f764caf625ad4f339399c0fe0e65fdb6986

**Comment by ianlancetaylor** [comment]
https://golang.org/cl/229484 should fix this, waiting for review by @bcmills .

**Comment by bcmills** [comment]
Sorry, wasn't aware that it was ready for another pass. (There are unresolved comments on PS1.)

**Comment by ianlancetaylor** [comment]
Sorry, I must have forgotten to hit send.
