### ISSUE TITLE
x/tools/gopls: VS Code extension showing warning in Terratest

### ISSUE THREAD

**Issue by dariagrudzien** [golang/go#38590]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
</pre></details>

### What Go VS Code extension are you using

`0.14.0`

### What did you do?

I am working on Terratest, and therefore my directory looks more or less like this:
```
./terraform
./terraform/output.tf
./terraform/main.tf
./terraform/test
./terraform/test/go.mod
./terraform/test/main_unit_test.go
./terraform/test/go.sum
./terraform/Makefile
./terraform/variables.tf
./terraform/provider.tf
```
I have VS Code open at the `terraform` directory level, I am working in the `main_unit_test.go` file.

### What did you see?

A warning: `You are neither in a module nor in your GOPATH. If you are using modules, please open your editor at the directory containing the go.mod. `

### What did you expect to see?

`Go` extension in VS Code working properly. My `go.mod` file is buried in a subdirectory, but I'm not able to open VS Code in that directory - I need to see the files I'm working on outside of the `test` directory. I wish there was a way to configure the extension to look for `go.mod` somewhere else.

**Comment by stamblerre** [comment]
> `Go` extension in VS Code working properly. My `go.mod` file is buried in a subdirectory, but I'm not able to open VS Code in that directory - I need to see the files I'm working on outside of the `test` directory. I wish there was a way to configure the extension to look for `go.mod` somewhere else.

You can add the directory to your workspace through File > Add Folder to Workspace. I recognize this is not the ideal workflow, as you will see the directory in two places in the outline on the left-hand side, but it should resolve the issue. We're working on addressing this for `gopls/v0.6.0`.
