### ISSUE TITLE
x/tools/gopls: corrupted file= query with files of different cases

### ISSUE THREAD

**Issue by stamblerre** [golang/go#38602]
See the discussion on https://github.com/microsoft/vscode-go/issues/3193.

/cc @heschik for case-insensitive file systems

**Comment by heschik** [comment]
I tracked this down.

```
panic: GetFile on  /tmp/scratch/case-insensitive import collision
golang.org/x/tools/internal/lsp/cache.(*snapshot).GetFile
golang.org/x/tools/internal/lsp/source.clearReports
golang.org/x/tools/internal/lsp/source.Diagnostics
golang.org/x/tools/internal/lsp.(*Server).diagnose.func2
```

`clearReports` probably shouldn't register a file that doesn't already exist, and we should ideally not treat `case-insensitive import collision: "example.com/foo/x" and "example.com/Foo/x"` as an error in the file "case-insensitive import collision".

**Comment by stamblerre** [comment]
Ah, thanks for tracking this down. I was probably too ambitious when I removed "FindFile" from the snapshot. Do you have a good sense of how we could write a regtest for this? I guess we would have to check on the condition of no diagnostics for "case-insensitive import collision"?

**Comment by heschik** [comment]
Are you more worried about the gratuitous Loads or the fact that the diagnostic got swallowed? I don't know how to write a test for the former, but the latter should be easy.

**Comment by stamblerre** [comment]
Really the former, but I think the latter could account for both? I'll try to figure out a good regtest for this. I can have a fix out for this soon - unless you already have one?
