### ISSUE TITLE
x/build: add a Windows ARM builder

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#38607]
We used to have a Windows ARM builder which was removed because it was no longer supported #38493. We should explore a new service or maintainer in order to restore the builder type.

/cc @andybons @dmitshur @toothrot

**Comment by toothrot** [comment]
Referencing #36439 as the main issue for the Windows ARM port.

**Comment by zx2c4** [comment]
Most of you should have received a private correspondance from me with disk images and instructions so that it's easy to launch a Windows 10 ARM64 builder on EC2/GCP from any x86 machine using qemu. If you didn't receive that from me, and you're on the Google team configuring the new builder, please pipe up.

**Comment by cagedmantis** [comment]
@zx2c4 Thank you for the disk images. We will update the corresponding issues as soon as we begin working on them.

**Comment by zx2c4** [comment]
I have physical ARM hardware running Windows that I would be happy to add as a builder to Go's pool.

**Comment by cagedmantis** [comment]
Note that this issue is in support of #26148

**Comment by cagedmantis** [comment]
@alexbrainman @zx2c4 While there isn't a license that permits us to run Windows arm in a virtualized environment, i'm not sure if there is any reason why contributors would not be allowed to provide builders on machines that are licensed to run this version of Windows. The previous arm builders we had were provided by Microsoft. I'm going to investigate and respond on this issue once I have an answer.

**Comment by zx2c4** [comment]
My builder runs on baremetal arm64 hardware without virtualization.

**Comment by alexbrainman** [comment]
@cagedmantis 

> While there isn't a license that permits us to run Windows arm in a virtualized environment,

Fair enough.

> i'm not sure if there is any reason why contributors would not be allowed to provide builders on machines that are licensed to run this version of Windows.

I don't have windows arm or arm64 machine (and I never used / seen before). Let's see what @zx2c4 have. Maybe he is willing to run it as a builder.

Alex

**Comment by zx2c4** [comment]
As I've mentioned repeatedly, I have physical baremetal non virtualized arm64 hardware that I bought for the explicit purpose of jump starting windows/arm64 development.

**Comment by cagedmantis** [comment]
@zx2c4 Please feel free to add a builder as per https://github.com/golang/go/wiki/DashboardBuilders

**Comment by aclements** [comment]
Once we do have builders for this, we should make sure they have mingw-llvm installed and that its GCC compatibility wrapper is in PATH (see the comments on [CL 271178](https://golang.org/cl/271178)).

**Comment by zx2c4** [comment]
> Once we do have builders for this, we should make sure they have mingw-llvm installed and that its GCC compatibility wrapper is in PATH (see the comments on [CL 271178](https://golang.org/cl/271178)).

System already configured that way :) Everything is all set, just waiting on the Go mailing list now.

**Comment by zx2c4** [comment]
![image](https://user-images.githubusercontent.com/10643/99798650-ab2a4c80-2b31-11eb-960c-6ff5e16cb0c2.png)

Has a gcc for each environment, depending on which one you need.

**Comment by zx2c4** [comment]
So, specifically for here, here's the situation for the ARM builder:

![image](https://user-images.githubusercontent.com/10643/99807728-36124380-2b40-11eb-9310-3cf94241f0f7.png)

**Comment by toothrot** [comment]
> As I've mentioned repeatedly, I have physical baremetal non virtualized arm64 hardware that I bought for the explicit purpose of jump starting windows/arm64 development.

Jason, we've spoken over email about why there were delays. I am sorry if you found our messaging to be unclear. I would like to remind you to read over the values and code of conduct, which are available here: https://golang.org/conduct#values. Please try to be charitable in understanding that we're doing what we can.

**Comment by zx2c4** [comment]
Don't worry, I've always assumed that your responses have been in good faith; there's no presumption of malice.

Anyway, following the go-ahead from @cagedmantis, I've spent the last two days getting the new build server perfected and clean for this purpose, and am just waiting on the key to add it to the pool:

![image](https://user-images.githubusercontent.com/10643/99821452-5945ee80-2b52-11eb-99c3-dd400aa6c499.png)

Brand new clean windows install with all the native arm tools are ready to go.

**Comment by cagedmantis** [comment]
I've responded via email with the host and private builder key.

**Comment by zx2c4** [comment]
windows/arm is back!
