### ISSUE TITLE
runtime: pageAlloc.allocToCache updates pageAlloc.searchAddr in an invalid way

### ISSUE THREAD

**Issue by mknyszek** [golang/go#38605]
Currently the page allocator's `allocToCache` method can update the search address in such a way that it doesn't point into memory contained in `pageAlloc.inUse`, which violates a documented property.

The result of this is an occasional crash. A similar bug was fixed prior to the Go 1.14 release with https://golang.org/cl/216697, but that failed to take into account `allocToCache`. This is causing real failures and we should fix it ASAP. We should also backport it as there is no workaround available when you do run into it.

**Comment by mknyszek** [comment]
@gopherbot Please open a backport issue for 1.14.

**Comment by mknyszek** [comment]
CC @aclements @prattmic

**Comment by networkimprov** [comment]
This and the CL mentioned in the issue aren't a factor in 1.13?

**Comment by mknyszek** [comment]
@networkimprov That's correct.
