### ISSUE TITLE
is same pointer name make in twice diffient size then get same memory?

### ISSUE THREAD

**Issue by liandeliang** [golang/go#38611]
Is same pointer name make in twice diffient size then get same memory? 

Sorry, i do not sure it is a bug, thanks. 

Below simple code, i want to allocate 2 diffient array used same variable name, but result give me same array.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\liand\AppData\Local\go-build
set GOENV=C:\Users\liand\AppData\Roaming\go\env  
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=code.aliyun.com
set GONOSUMDB=code.aliyun.com
set GOOS=windows
set GOPATH=D:\work\go
set GOPRIVATE=code.aliyun.com
set GOPROXY=https://goproxy.io
set GOROOT=D:\develop\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\develop\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=D:\work\cryptocoin\api\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\liand\AppData\Local\Temp\go-build377423766=/tmp/go-build -gno-record-gcc-switches 
</pre></details>

### What did you do?

		a := make([]int, 0)
		p1 := &a

		a = make([]int, 1)
		p2 := &a

		log.Printf("len(p1)=%d,len(p2)=%d", len(*p1), len(*p2))

### What did you expect to see?

		len(p1)=0,len(p2)=1

### What did you see instead?

		len(p1)=1,len(p2)=1

**Comment by ianlancetaylor** [comment]
You set `p1` to the address of `a`.  When you change `a`, you change the value to which `p1` points.  That's how pointers work.

I'm going to close this because it isn't a bug.

For questions about using Go, you will get faster and better answers in a forum rather than in the issue tracker.  See https://golang.org/wiki/Questions.
