### ISSUE TITLE
why incompitable struct tag isn't caught at compile time

### ISSUE THREAD

**Issue by mobop** [golang/go#38614]
compiler doesn't produce any error if a struct tag is `key:value`
where it should be `key:"value"`

**Comment by cuonglm** [comment]
Please fill in the template issue if you see it's the issue, Github issue tracker is not for Q&A.

FYI, Go spec define struct tag as string https://golang.org/ref/spec#Tag, so it can be in any form.

**Comment by mobop** [comment]
it defines as key vlaue pairs optionally separated by space

**Comment by mvdan** [comment]
What @cuonglm said. `go vet` already checks incorrect syntax for common struct tag keys like `json`.

**Comment by mobop** [comment]
but what's the reason for not giving a compiler error

**Comment by mvdan** [comment]
Like @cuonglm said, the spec [only defines struct tags as strings](https://golang.org/ref/spec#Struct_types). They are parsed and evaluated at run-time.

**Comment by seankhliao** [comment]
see #23637

**Comment by ALTree** [comment]
Closing here since your question has been answered and as noted this somewhat qualifies as a dup of  #23637.
