### ISSUE TITLE
cmd/compile: support named values on RHS of rewrite rules

### ISSUE THREAD

**Issue by josharian** [golang/go#38621]
I'd like to change the amd64 splitload rules to use (TESTQ x x) instead of (CMPQconst [0] x) when possible. However, there's no way to write (TESTQ x x) on the RHS of a rewrite rule unless x is already present on the LHS. You can spell out x twice, but then it generates two distinct values. In normal rewrite rules, we rely on a subsequent CSE to clean that up. But no CSE runs after splitload. Plus that is inefficient. I'd like to be able to write something like:

`(CMP(Q|L|W|B)constload {sym} [vo] ptr mem) && valOnly(vo) == 0 -> (TEST(Q|L|W|B) x:(MOV(Q|L|W|B)load {sym} [offOnly(vo)] ptr mem) x)`

Comments?

cc @mvdan @randall77

**Comment by mvdan** [comment]
How does this compare to https://github.com/golang/go/issues/37423? Both seem to want to add syntax for similar reasons.

**Comment by josharian** [comment]
#37423 contemplates calculating reusable Go values with Go expressions. This contemplates generating reusable ssa.Values with s-exprs.

**Comment by randall77** [comment]
That syntax seems fine to me. We already do it on the LHS.
