### ISSUE TITLE
x/build: host-plan9-386-0intro builder is missing

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#38629]
The TryBot is stuck on CL 228645 because the plan9-386-0intro builder seems to be gone.

* host-plan9-386-0intro: 184 waiting (oldest 74h37m37s, newest 24m36s, progress 25h22m54s)
    * try: 1 (oldest 24m36s, newest 24m36s)

host-plan9-386-0intro: 0/0 (1 missing)

(The plan9-arm-0intro builders instead seem online but days behind.)

**Comment by 0intro** [comment]
I'm currently looking a it. Thanks.

**Comment by 0intro** [comment]
It should be fixed now.
