### ISSUE TITLE
playground: Map based program timesout

### ISSUE THREAD

**Issue by ardan-bkennedy** [golang/go#38622]
### What version of Go are you using (`go version`)?

Current version of the Go playground

### Does this issue reproduce with the latest release?

Only happening on the playground

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

https://play.golang.org/p/0KFlxby2a0z

### What did you expect to see?

Program should output the ranging of the map

### What did you see instead?

timeout running program

**Comment by randall77** [comment]
Maybe a dup of #38546 ? Adding another string to one of the printfs fixes it.

**Comment by ianlancetaylor** [comment]
Yes, I think it's a cached time out.  Even changing a comment fixes the problem.

Closing as a dup of #38546.

**Comment by toothrot** [comment]
This has been resolved by #38546. I tested the linked snippet, and it works correctly now.
