### ISSUE TITLE
runtime: SIGSEGV during runtime init, in gcenable

### ISSUE THREAD

**Issue by wadey** [golang/go#38639]
### What version of Go are you using (`go version`)?

go1.14.2

### Does this issue reproduce with the latest release?

It appears to be a rare crash, hard to reproduce.

### What operating system and processor architecture are you using (`go env`)?

linux amd64

### What did you do?

Just started a Go process, got this SIGSEGV, the second goroutine is still in `gcenable`, so it looks like this is during runtime init.

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x6c0 pc=0x4191cc]

runtime stack:
runtime.throw(0xb11cd0, 0x2a)
        runtime/panic.go:1116 +0x72
runtime.sigpanic()
        runtime/signal_unix.go:679 +0x46a
runtime.(*mcache).prepareForSweep(0x0)
        runtime/mcache.go:179 +0x2c
runtime.acquirep(0xc000030800)
        runtime/proc.go:4278 +0x3d
runtime.stoplockedm()
        runtime/proc.go:1979 +0xca
runtime.schedule()
        runtime/proc.go:2454 +0x4a6
runtime.park_m(0xc000000180)
        runtime/proc.go:2690 +0x9d
runtime.mcall(0x0)
        runtime/asm_amd64.s:318 +0x5b

goroutine 1 [runnable, locked to thread]:
runtime.gopark(0xb24840, 0xc00007a058, 0x170e, 0x2)
        runtime/proc.go:304 +0xe0
runtime.chanrecv(0xc00007a000, 0x0, 0xc000000101, 0x410101)
        runtime/chan.go:525 +0x2e7
runtime.chanrecv1(0xc00007a000, 0x0)
        runtime/chan.go:407 +0x2b
runtime.gcenable()
        runtime/mgc.go:217 +0xac
runtime.main()
        runtime/proc.go:166 +0x115
runtime.goexit()
        runtime/asm_amd64.s:1373 +0x1
```

**Comment by randall77** [comment]
@mknyszek

**Comment by mknyszek** [comment]
Hm. This implies the `mcache` is nil. I'm not sure what that implies (especially so early on in the init process; all the `P`s and `mcache`s should've been initialized already!), but it can't be good. I'll investigate.

**Comment by ianlancetaylor** [comment]
A stab in the dark: does your code call `runtime.GOMAXPROCS` from an `init` function?

**Comment by wadey** [comment]
It does not set GOMAXPROCS, here is the main package (tag v1.2.0): https://github.com/slackhq/nebula/blob/v1.2.0/cmd/nebula/main.go

**Comment by mknyszek** [comment]
There isn't much to go on here, but I had one hypothesis: in Go 1.14.2, when `procresize` is first called, it sets the 0th `p`'s `mcache` to the bootstrap `mcache`, which `mallocinit` just places on whatever `m` is doing the initializing (that `m` later gets the 0th `p` in `procresize`). I was thinking that maybe the 0th `p` has its `mcache` set to nil as the result of `g.m.mcache` becoming nil between `mallocinit` and `gcenable`. Looking through all the code that gets executed in between, I don't see how this could happen. There are (potential) heap allocations all through there and they don't fail.

With that being said, things might be different given that in Go 1.15, `m`s no longer have an `mcache` pointer, only `p`s do, so the bootstrap `mcache` is more explicit (the malloc code just uses `mcache0` when none exists and it's bootstrapping). The fact that the `mcache` is assigned as `getg().m.mcache` in `p.init` is a bit fishy to me.

**Comment by mknyszek** [comment]
I may be getting a core dump for an application which crashed with this issue, so I might know more soon. 🤞

**Comment by mknyszek** [comment]
False alarm, turns out the code dump was for a binary from an old Go version which died for a different reason.

**Comment by ianlancetaylor** [comment]
We don't know what is happening here.  Rolling milestone forward to 1.16.

**Comment by aclements** [comment]
Ping @mknyszek . Roll to 1.17?

**Comment by mknyszek** [comment]
Roll to 1.17 but I have had no way of reproducing this at all, and haven't seen it pop up anywhere. Unless @wadey has any more details or has reproduced this, we should probably just put it into WaitingForInfo.

**Comment by wadey** [comment]
I have no other info and I have not seen this failure since. Could have just been a fluke hardware issue .
