### ISSUE TITLE
go/types: pointer method error less useful than the compiler's

### ISSUE THREAD

**Issue by atombender** [golang/go#38658]
#### What did you do?

I was very confused with what was wrong with my code:

![Screen Shot 2020-04-25 at 15 11 57](https://user-images.githubusercontent.com/50314/80288641-357b1100-8707-11ea-9dce-e6e33cedc90c.jpg)

Since gopls frequently errors out for whatever reason, I decided to check what `go build` says:

![Screen Shot 2020-04-25 at 15 12 13](https://user-images.githubusercontent.com/50314/80288640-34e27a80-8707-11ea-9139-946859158716.jpg)

The object here is a `zerolog.Logger` (from [zerolog](https://github.com/rs/zerolog)), which provides `Warn` on a pointer receiver.

#### What did you expect to see?

Compiler error should be same as what `go build` gives.

#### What did you see instead?

Wrong compiler error.

#### Build info

```
golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@(devel)
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.2.0 h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
    golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=
    golang.org/x/tools@v0.0.0-20200407041343-bf15fae40dea => ../
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=
```

#### Go info

```
go version go1.14 darwin/amd64

```

**Comment by stamblerre** [comment]
Ah, thanks for reporting! This is another instance of a go/types error differing from a compiler error. I'll try to get a fix in for 1.15.
