### ISSUE TITLE
reflect.DeepEqual trippin

### ISSUE THREAD

**Issue by mcandre** [golang/go#38650]
Empty slices are functionally equal to `nil` through the Go system. You can do `bb1 := []int{}` or `var bb2 []int` and get the same runtime behavior.

`reflect.DeepEqual` is a nuisance with its insistence that `bb1` is not `bb2`. This breaks tests. This breaks QuickCheck. Gah!

**Comment by mdlayher** [comment]
There's nothing to be done here, so closing.

**Comment by ALTree** [comment]
See  #12918, in particular https://github.com/golang/go/issues/12918#issuecomment-147720864:

> This is working as intended. reflect.DeepEqual aims to replicate the language's == operator for cases where the language permits a comparison. []byte{} == nil will return false.
