### ISSUE TITLE
x/tools/gopls: completion in interface{} vararg for interface{} value adds invalid "..."

### ISSUE THREAD

**Issue by zikaeroh** [golang/go#38652]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

```go
package main

import "log"

var v interface{}

func main() {
	log.Println()
}
```

Then did a completion inside the `Println` call.

#### What did you expect to see?

`v` offered, and when accepted inserts `v` to produce `log.Println(v)`.

#### What did you see instead?

It inserts `v...` instead, leaving the invalid `log.Println(v...)`.

Note that if I type out `v` (rather than manually triggering), then I can get it to not insert `...`, but if I re-trigger the completion after the `v` and accept it, instead of a no-op it adds `...` as well.

Logs: https://gist.github.com/zikaeroh/cd93cf199d3eaba8714c937890832859

#### Build info

```
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.0.0-20200423205358-59e73619c742 h1:Z2r4hP5f43sniIXn35RsRnebH6wNlYkr2xOTUGcgjAU=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.2.0 h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
    golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=
    golang.org/x/tools@v0.0.0-20200423205358-59e73619c742 h1:9OGWpORUXvk8AsaBJlpzzDx7Srv/rSK6rvjcsJq4rJo=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=
```

#### Go info

```
go version go1.14.2 linux/amd64

```

**Comment by stamblerre** [comment]
Thanks for the report! /cc @muirdm for completions work

**Comment by muirdm** [comment]
Thanks! It was a silly goof.
