### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by DaddyJack** [golang/go#38653]
### What version of Go are you using (`go version`)?

<pre>
$ go version
tour of go
</pre>

### Does this issue reproduce with the latest release?

not relevant

### What operating system and processor architecture are you using (`go env`)?
not relevant
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
not relevant
</pre></details>

**Comment by ianlancetaylor** [comment]
No bug report.
