### ISSUE TITLE
x/tools/gopls: hoverKind FullDocumentation is incorrectly escaping various characters

### ISSUE THREAD

**Issue by jsravn** [golang/go#38656]
### What version of Go are you using (`go version`)?

<pre>
❯ gopls version                          
golang.org/x/tools/gopls v0.3.4
    golang.org/x/tools/gopls@v0.3.4 h1:4GC7q/pXQ/tsxHBGVdsMdlB4gCxVC06m/7rIXg1Px4E=
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
❯ go env                                 
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/james/.cache/go-build"
GOENV="/home/james/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/james/go:/home/james/godev"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build613753881=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I have set `"hoverKind": "FullDocumentation"` as added in https://github.com/golang/go/issues/32561. This works, but it inserts a lot of escaped characters into the markdown description that it doesn't need to. I'm not quite sure why.

Here is an example for `fmt#Errorf`:

```markdown

[`fmt.Errorf` on pkg.go.dev](https://pkg.go.dev/fmt#Errorf)

Errorf formats according to a format specifier and returns the string as a
value that satisfies error\\.

If the format specifier includes a \\%w verb with an error operand,
the returned error will implement an Unwrap method returning the operand\\. It is
invalid to include more than one \\%w verb or to supply it with an operand
that does not implement the error interface\\. The \\%w verb is otherwise
a synonym for \\%v\\.
```

Rendering this via markdown (inside Emacs via lsp-mode) produces this:

![image](https://user-images.githubusercontent.com/522123/80281358-69076c80-8702-11ea-99a9-93e69422d657.png)

I'm also seeing html entities being escaped:

![image](https://user-images.githubusercontent.com/522123/80284964-c3f88e00-8719-11ea-96fa-32f4c7106c4f.png)

In the raw JSON this looks like `\u0026nbsp;`.

### What did you expect to see?

Full documentation without any escape characters.

### What did you see instead?

Full documentation with lots of embedded escape characters.

**Comment by jsravn** [comment]
Actually I think the `&nbsp;` is a bug on the lsp-mode/emacs side.  But I'm not sure why gopls is returning e.g. `\\.` for punctuation. I'd expect `\.`.

**Comment by jsravn** [comment]
^ Nevermind, I confirm gopls is indeed returning escaped &, that's why I see `&nbsp;` in the render.

**Comment by stamblerre** [comment]
This is probably because lsp-mode is requesting its hover results to be formatted in Markdown. There is an option on the language client's end to request plaintext results, but a lot of clients choose Markdown because users may have other plugins installed that display Markdown nicely. I would recommend opening up an issue to offer a configuration in lsp-mode or seeing if you can install a plugin to format the hover.

**Comment by jsravn** [comment]
I see this is expected based on the LSP spec. So I'll dig further on the lsp-mode side.

**Comment by jsravn** [comment]
lsp-mode change to handle this at https://github.com/emacs-lsp/lsp-mode/pull/1614.

@stamblerre do you know why gopls returns so much whitespace around indents though?

For example here is the original godoc:
```
// Expect wraps an actual value allowing assertions to be made on it:
//    Expect("foo").To(Equal("foo"))
```

And the MarkupContent inserts 2 lines between the sentence and the following indent:
```json
  "contents": {
    "value": "```go\nfunc ..Expect(actual interface{}, extra ...interface{}) ..Assertion\n```\n\n[`gomega.Expect` on pkg.go.dev](https://pkg.go.dev/github.com/onsi/gomega@v1.5.0#Expect)\n\nExpect wraps an actual value allowing assertions to be made on it\\:\n\n\n&nbsp;&nbsp;&nbsp;&nbsp;Expect(\"foo\").To(Equal(\"foo\"))\n\n\nIf Expect is passed more than one argument it will pass the \\*first\\* argument to the matcher\\.\nAll subsequent arguments will be required to be nil\\/zero\\.\n\nThis is convenient if you want to make an assertion on a method\\/function that returns\na value and an error \\- a common patter in Go\\.\n\nFor example, given a function with signature\\:\n\n\n&nbsp;&nbsp;&nbsp;&nbsp;func MyAmazingThing() (int, error)\n\n\nThen\\:\n\n\n&nbsp;&nbsp;&nbsp;&nbsp;Expect(MyAmazingThing()).Should(Equal(3))\n\n\nWill succeed only if \\`MyAmazingThing\\(\\)\\` returns \\`\\(3, nil\\)\\`\n\nExpect and Ω are identical\n",
    "kind": "markdown"
  }
```

**Comment by stamblerre** [comment]
I believe that this is done to make the indent render properly in the Markdown. I'm not an expert, but this is the code that does the conversion: https://github.com/golang/tools/blob/f3a5411a4c3bfd7b6429abf664039dc43b37d985/internal/lsp/source/comment.go#L40.

I would imagine that the extra whitespace will not be there in the plaintext mode.
