### ISSUE TITLE
x/pkgsite: function does not appear in table of contents

### ISSUE THREAD

**Issue by stamblerre** [golang/go#38666]
The function `Expect` appears on the page https://pkg.go.dev/github.com/onsi/gomega?tab=doc#Expect, but it is not listed in the table of contents.

**Comment by go101** [comment]
It is shown under "type Assertion", though I also feel this is some confused.

**Comment by julieqiu** [comment]
/cc @dmitshur for input - this is also how it is currently displayed on godoc.org.

![image](https://user-images.githubusercontent.com/5943521/80813653-71472800-8b98-11ea-9e7a-de1d8b9a242b.png)

**Comment by go101** [comment]
This problem has been discussed before: https://github.com/golang/go/issues/28006

**Comment by dmitshur** [comment]
Per comments above, `Expect` is considered to be a "factory function" for `Assertion`, so it's displayed underneath it.

The code for this is in `go/doc` (see https://github.com/golang/go/issues/39813#issuecomment-649636776). I don't see anything to do here, so let's close this. We can use #39813 as the tracking issue for considering changes to the "factory function" behavior.
