### ISSUE TITLE
Memory freed by GC doesn't seem to claim properly when same slice variable is initialised in a loop

### ISSUE THREAD

**Issue by naveenkak** [golang/go#38663]
I am initialising the same slice variable in a loop, why is the memory going up?
Since I am making the same variable point to a different memory every time, earlier memory should be cleaned up.
https://play.golang.org/p/g-UY3AqlInV

package main

import (
	"fmt"
	"runtime"
	//"time"
)
var testslice [] byte 
var m runtime.MemStats

func main() {

        
        for i := 0; i < 100; i++{
	testslice = make([]byte, 100000)
	fmt.Printf("test slice length %d", len(testslice))
	runtime.ReadMemStats(&m)
	fmt.Printf(" memory allocated %d %d\n",  m.Alloc, m.NumGC)
	//runtime.GC()
        }	
		
}

test slice length 100000 memory allocated 224592 0
test slice length 100000 memory allocated 331104 0
test slice length 100000 memory allocated 437616 0
test slice length 100000 memory allocated 544128 0
test slice length 100000 memory allocated 650640 0
test slice length 100000 memory allocated 757152 0
test slice length 100000 memory allocated 863664 0
test slice length 100000 memory allocated 970176 0
test slice length 100000 memory allocated 1076688 0
test slice length 100000 memory allocated 1183200 0
test slice length 100000 memory allocated 1289712 0
test slice length 100000 memory allocated 1396224 0
test slice length 100000 memory allocated 1502736 0
test slice length 100000 memory allocated 1609248 0
test slice length 100000 memory allocated 1715760 0
test slice length 100000 memory allocated 1822272 0
test slice length 100000 memory allocated 1928784 0
test slice length 100000 memory allocated 2035296 0
test slice length 100000 memory allocated 2141808 0
test slice length 100000 memory allocated 2248320 0
test slice length 100000 memory allocated 2354832 0
test slice length 100000 memory allocated 2461344 0
test slice length 100000 memory allocated 2567856 0
test slice length 100000 memory allocated 2674368 0
test slice length 100000 memory allocated 2780880 0
test slice length 100000 memory allocated 2887392 0
test slice length 100000 memory allocated 2993904 0
test slice length 100000 memory allocated 3100416 0
test slice length 100000 memory allocated 3206928 0
test slice length 100000 memory allocated 3313440 0
test slice length 100000 memory allocated 3419952 0
test slice length 100000 memory allocated 3526464 0
test slice length 100000 memory allocated 3632976 0
test slice length 100000 memory allocated 3739488 0
test slice length 100000 memory allocated 3846000 0
test slice length 100000 memory allocated 3952512 0
test slice length 100000 memory allocated 4059024 0
test slice length 100000 memory allocated 4165536 0
test slice length 100000 memory allocated 326192 1
test slice length 100000 memory allocated 432720 1
test slice length 100000 memory allocated 539248 1
test slice length 100000 memory allocated 645776 1
test slice length 100000 memory allocated 752304 1
test slice length 100000 memory allocated 858832 1
test slice length 100000 memory allocated 965360 1
test slice length 100000 memory allocated 1071888 1
test slice length 100000 memory allocated 1178416 1
test slice length 100000 memory allocated 1284944 1
test slice length 100000 memory allocated 1391472 1
test slice length 100000 memory allocated 1498000 1
test slice length 100000 memory allocated 1604528 1
test slice length 100000 memory allocated 1711056 1
test slice length 100000 memory allocated 1817584 1
test slice length 100000 memory allocated 1924112 1
test slice length 100000 memory allocated 2030640 1
test slice length 100000 memory allocated 2137168 1
test slice length 100000 memory allocated 2243696 1
test slice length 100000 memory allocated 2350224 1
test slice length 100000 memory allocated 2456752 1
test slice length 100000 memory allocated 2563280 1
test slice length 100000 memory allocated 2669808 1
test slice length 100000 memory allocated 2776336 1
test slice length 100000 memory allocated 2882864 1
test slice length 100000 memory allocated 2989392 1
test slice length 100000 memory allocated 3095920 1
test slice length 100000 memory allocated 3202448 1
test slice length 100000 memory allocated 3308976 1
test slice length 100000 memory allocated 3415504 1
test slice length 100000 memory allocated 3522032 1
test slice length 100000 memory allocated 3628560 1
test slice length 100000 memory allocated 3735088 1
test slice length 100000 memory allocated 3841616 1
test slice length 100000 memory allocated 3948144 1
test slice length 100000 memory allocated 4054672 1
test slice length 100000 memory allocated 4161200 1
test slice length 100000 memory allocated 4266880 2
test slice length 100000 memory allocated 1178776 2
test slice length 100000 memory allocated 1178808 2
test slice length 100000 memory allocated 646360 2
test slice length 100000 memory allocated 752888 2
test slice length 100000 memory allocated 859416 2
test slice length 100000 memory allocated 965944 2
test slice length 100000 memory allocated 1072472 2
test slice length 100000 memory allocated 1179000 2
test slice length 100000 memory allocated 1285528 2
test slice length 100000 memory allocated 1392056 2
test slice length 100000 memory allocated 1498584 2
test slice length 100000 memory allocated 1605112 2
test slice length 100000 memory allocated 1711640 2
test slice length 100000 memory allocated 1818168 2
test slice length 100000 memory allocated 1924696 2
test slice length 100000 memory allocated 2031224 2
test slice length 100000 memory allocated 2137752 2
test slice length 100000 memory allocated 2244280 2
test slice length 100000 memory allocated 2350808 2
test slice length 100000 memory allocated 2457336 2
test slice length 100000 memory allocated 2563864 2
test slice length 100000 memory allocated 2670392 2
test slice length 100000 memory allocated 2776920 2
test slice length 100000 memory allocated 2883448 2

Beginning memory was 224592 and end its 2883448.

If I explicitly call runtime.GC() within loop then memory stays same.

**Comment by randall77** [comment]
This is all behaving as expected. What about this do you think is wrong?

The garbage collector works in batches. It does not collect unreferenced items immediately.

**Comment by ianlancetaylor** [comment]
The Go project does not use the issue tracker for questions.  Please use a forum for this discussion.  See https://golang.org/wiki/Questions.  Thanks.

**Comment by naveenkak** [comment]
> This is all behaving as expected. What about this do you think is wrong?
> 
> The garbage collector works in batches. It does not collect unreferenced items immediately.

Sorry to bother you again..
But at the end of program, this is the o/p
**test slice length 100000 memory allocated 2883448 2**
which is way more than than the start of program ( 225K)...

Are you saying GC will run again in the background and free up the memory? 
How to verify that?
