### ISSUE TITLE
Is assigning a pointer atomic in go

### ISSUE THREAD

**Issue by SmallSmartMouse** [golang/go#38667]
In my project，i encounter problems,this is my code:
`var data map[string]string

func main() {

	go func() {
		v := data["d"]
		fmt.Println(v)

	}()
	go func() {

		temp := make(map[string]string)
		temp["a"] = "a"
		data = temp
	}()
}
`
one coroutine read the map or list, but one coroutine modify the map or list，is the step:		`data = temp` atomic ,and is there any problem or bug，

**Comment by randall77** [comment]
This is a race condition, and is invalid code.
Run with the `-race` flag and you will see an error.

More generally, pointer assignment *is* atomic, but you need more than that to make an example like yours work.

The Go project does not use the issue tracker for questions. Please use a forum for this discussion. See https://golang.org/wiki/Questions. Thanks.

**Comment by SmallSmartMouse** [comment]
Hi @randall77 
In forum I dont get a response. In the example code,Is  reassignment of the global data map with the temp one I created  atomic? 
Is the step of taking   the address of the map,then assigning the address to the global map address pointer atomic?
```
var data *map[string]string
temp :=make(map[string]string)
data=&temp
```
thanks.

**Comment by lsytj0413** [comment]
> Hi @randall77
> In forum I dont get a response. In the example code,Is reassignment of the global data map with the temp one I created atomic?
> Is the step of taking the address of the map,then assigning the address to the global map address pointer atomic?
> 
> ```
> var data *map[string]string
> temp :=make(map[string]string)
> data=&temp
> ```
> 
> thanks.

there is nothing about **atomic**，just about the exec order between two goroutine.

**Comment by ianlancetaylor** [comment]
I'm sorry, this is still the wrong place to ask questions.  If one forum didn't help, try a different one.  Don't try back here.  Sorry, and thanks for respecting our approach to questions.
