### ISSUE TITLE
spec: when do struct comparisons panic? 

### ISSUE THREAD

**Issue by bradfitz** [golang/go#38676]
Should the spec clarify when a struct comparison panics?

e.g.

https://play.golang.org/p/4NUu89RI27t
```
package main

import "fmt"

func cmp(a, b S) {
	defer func() {
		if recover() != nil {
			fmt.Println("panic")
		}
	}()
	if a == b {
		fmt.Println("equal")
	} else {
		fmt.Println("not-equal")
	}
}

type S struct{ a, b interface{} }

func main() {
	var f func()
	cmp(S{1, f}, S{2, f})
	cmp(S{f, 1}, S{f, 2})
}
```

Is it okay for implementations to have different answers to those two prints?

(Background: https://go-review.googlesource.com/c/go/+/230207, `cmd/compile: improve generated eq algs for structs containing interfaces` from @josharian)

/cc @griesemer @ianlancetaylor @mdempsky

**Comment by josharian** [comment]
I believe the relevant part of the spec is:

> A comparison of two interface values with identical dynamic types causes a run-time panic if values of that type are not comparable. This behavior applies not only to direct interface value comparisons but also when comparing arrays of interface values or structs with interface-valued fields.

A very literal reading of the spec suggests Brad’s program should print “panic, panic”. Currently it prints “not-equal, panic”. The CL Brad linked to would not change the output for this particular program, but for similar programs, it might change the output to “not-equal, not-equal”.

**Comment by randall77** [comment]
It would be unfortunate if, when comparing `[100]interface{}`, we had to compare all 100 entries even when the first entry reports `!=`.
Not the end of the world, though.

**Comment by mdempsky** [comment]
I think this is #8606

**Comment by bradfitz** [comment]
@mdempsky, thanks! Closing this one as a duplicate.

**Comment by go101** [comment]
If both of the filed names are changed to `_`, then the comparisons results are `equal`. Bug?

```golang
package main

import "fmt"

func cmp(a, b S) {
	defer func() {
		if recover() != nil {
			fmt.Println("panic")
		}
	}()
	if a == b {
		fmt.Println("equal")
	} else {
		fmt.Println("not-equal")
	}
}

type S struct{_, _ interface{} }

func main() {
	var f func()
	cmp(S{1, f}, S{2, f}) // equal
	cmp(S{f, 1}, S{f, 2}) // equal
}
```

**Comment by mdempsky** [comment]
https://golang.org/ref/spec#Comparison_operators:

"Two struct values are equal if their corresponding **non-blank** fields are equal."
