### ISSUE TITLE
type switch malfunction

### ISSUE THREAD

**Issue by ondi** [golang/go#38675]
### What version of Go are you using (`go version`)?

<pre>
go version devel +09630172d4 Sat Apr 25 23:15:50 2020 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/.cache/go-build"
GOENV="/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/.go/pkg/mod"
GOOS="linux"
GOPATH="/.go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Downloads/goroot"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Downloads/goroot/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build114983298=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/j22d9WvVCDn

### What did you expect to see?

INTEGER: int64 0 is_zero=true, is_not_zero=false
INTEGER: int64 1 is_zero=false, is_not_zero=true

### What did you see instead?

INTEGER: int64 0 is_zero=false, is_not_zero=true
INTEGER: int64 1 is_zero=false, is_not_zero=true

**Comment by cuonglm** [comment]
This works as expected, since when you use `case int, int64`, the type of `v` inside that case is `interface{}`.

**Comment by ondi** [comment]
> This works as expected, since when you use `case int, int64`, the type of `v` inside that case is `interface{}`.

Why?
%T inside this case says that it's a int64

**Comment by cuonglm** [comment]
> > This works as expected, since when you use `case int, int64`, the type of `v` inside that case is `interface{}`.
> 
> 
> 
> Why?
> 
> %T inside this case says that it's a int64
> 

It’s evaluated at runtime, at compile time, you don’t know whether it’s `int` or `int64`.

When you use 2 or more types in typed switch, the lhs variable will have the same type as the rhs. In your case, it means `v` have  the same type as `value`.

**Comment by MrWormHole** [comment]
@cuonglm as he stated, you have v which is an empty interface{} object. You are trying to compare your interface object to an integer. What %v does inside a string is essentialy do type assertion to check if it is castable to a fundemental value types like string, char, int, float. Hopefully this helps you to understand more.

```
package main

import (
	"fmt"
)

func test(value interface{}){
	switch v := value.(type){
		case int, int64:
			fmt.Printf("INTEGER: %T %v is_zero=%v, is_not_zero=%v\n", v, v, v.(int64) == 0, v.(int64) != 0)
		default:
			fmt.Printf("OTHER: %T\n", v)
	}
}

func main() {
	a := int64(0)
	test(a)
	a = 1
	test(a)
}
```

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
