### ISSUE TITLE
strconv: redundant type conversion to int

### ISSUE THREAD

**Issue by semyon-dev** [golang/go#38682]
### What version of Go are you using (`go version`)?

<pre>
go v1.14.2
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
Linux, amd64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/semyon/.cache/go-build"
GOENV="/home/semyon/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/semyon/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build588385711=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you see?
[From strconv.ParseInt() line 206](https://golang.org/src/strconv/atoi.go?s=4757:4824#L169):

```
if bitSize == 0 {
	bitSize = int(IntSize)
}
```
Redundant type conversion to int. We can just do this:

```
if bitSize == 0 {
	bitSize = IntSize
}
```
IntSize is already int (from line 52):
```
const intSize = 32 << (^uint(0) >> 63)

// IntSize is the size in bits of an int or uint value.
const IntSize = intSize
```
My suggestion works for both 32bit and 64bit platforms.

**Comment by smasher164** [comment]
I annotated `IntSize` as of type int, ran [unconvert](https://github.com/mdempsky/unconvert) on the strconv package at [tip](1cf357981ee9ec838555585d52f86ca60097c6b1), and found the following
```
/Users/akhil/Projects/go/src/strconv/atoi.go:99:16: unnecessary conversion
		bitSize = int(IntSize)
		             ^
/Users/akhil/Projects/go/src/strconv/atoi.go:206:16: unnecessary conversion
		bitSize = int(IntSize)
		             ^
```

As a sidenote, more evidence for https://github.com/mdempsky/unconvert/issues/20?
