### ISSUE TITLE
runtime/cgo: build fails on linux-arm with "size of array '_check_for_64_bit_pointer_matching_GoInt' is negative"

### ISSUE THREAD

**Issue by alevchuk** [golang/go#38693]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.6 linux/arm
</pre>

### Does this issue reproduce with the latest release?

Yes. I tired building `go1.13.10`

bootstrap versions tried go1.11.6 and go-1.7

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="arm"
GOBIN=""
GOCACHE="/home/monitoring/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/monitoring/gocode"
GOPROXY=""
GORACE=""
GOROOT="/home/monitoring/src/go"
GOTMPDIR=""
GOTOOLDIR="/home/monitoring/src/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/monitoring/src/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build264984488=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
cd go/src
./all.bash
```

### What did you expect to see?

Build success as usual (on Pi 4s this always builds fine).

### What did you see instead?

```
~/src/go/src $ ./all.bash

Building Go cmd/dist using /usr/lib/go-1.7.
Building Go toolchain1 using /usr/lib/go-1.7.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/arm64.
# runtime/cgo
In file included from _cgo_export.c:4:
cgo-gcc-export-header-prolog:25:14: error: size of array '_check_for_64_bit_pointer_matching_GoInt' is negative
go tool dist: FAILED: /home/monitoring/src/go/pkg/tool/linux_arm64/go_bootstrap install -gcflags=all= -ldflags=all= std cmd: exit status 2
```

**Comment by andybons** [comment]
@ianlancetaylor

**Comment by ianlancetaylor** [comment]
The bug title and your `go env` output suggest that you are building for linux/arm, but the output is for a build of linux/arm64.  The error looks like you are cross-compiling, but that you are using a native compiler rather than a cross-compiler.

Why does the all.bash output say `Building packages and commands for linux/arm64.` ?

**Comment by alevchuk** [comment]
I'm not familiar with go code base, `all.bash` is part of that.

I tried `export GOARCH=arm` and got the same error.
> Building Go cmd/dist using /usr/lib/go-1.11. (go1.11.6 linux/arm)
says arm
while:
> Building packages and commands for host, linux/arm64.
arc64

btw, I'm running a 32 bit OS (Rasbian) on 64 bit hardware

**Comment by ianlancetaylor** [comment]
It sounds like the Go build process is misunderstanding your system.  I think you may need to set both `GOHOSTARCH=arm` and `GOARCH=arm` when running `all.bash`.

**Comment by chowyu08** [comment]
I have the same question when build arm64
`# runtime/cgo
In file included from _cgo_export.c:4:
cgo-gcc-export-header-prolog:25:14: error: size of array ‘_check_for_64_bit_pointer_matching_GoInt’ is negative
`

**Comment by ALTree** [comment]
This was probably caused by incorrect env variables and there hasn't been any update for about a year, I think we can close.
