### ISSUE TITLE
cmd/compile: can't specify value for blank fields of array types.

### ISSUE THREAD

**Issue by go101** [golang/go#38690]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```golang
package main

import "fmt"

func cmpS(a, b S) {
	defer func() {
		if recover() != nil {
			fmt.Println("panic")
		}
	}()
	fmt.Println(a == b)
}

type S struct{x int; _ [2]int}

func main() {
	cmpS(S{1, [2]int{2}}, S{1, [2]int{3}}) // cannot use _ as value
}
```

### What did you expect to see?

Compiles ok.

### What did you see instead?

Failed to compile. 

BTW, it compiles ok with gccgo.

**Comment by ianlancetaylor** [comment]
The error messages looks wrong but it's not obvious to me that the program should work.  Is a composite literal allowed to set the value of a `_` field?

**Comment by mdempsky** [comment]
We allow initializing blank, non-array-typed fields in non-keyed composite literals, so we should probably allow blank, array-typed fields too.

**Comment by ianlancetaylor** [comment]
OK, SGTM.

**Comment by go101** [comment]
It looks struct literals also have this problem, but slice literals not.
And not all such array/struct literals have this problem.
It looks this problem only happens in binary operator operations.

```golang
package main


type T = struct{y int} // struct literals also fail to compile
//type T = [1]int
//type T = []int // slice literals are ok
type S struct{x int; _ T}

var x, y = S{1, T{2}}, S{1, T{2}} // ok

func main() {
	println(S{1, T{2}}.x == S{1, T{3}}.x) // cannot use _ as value
}
```

**Comment by josharian** [comment]
Does it also only happen in structs with <= 4 fields? If so, the bug might be in the inlined struct comparison code in walkCompare in walk.go.

**Comment by cuonglm** [comment]
> Does it also only happen in structs with <= 4 fields? If so, the bug might be in the inlined struct comparison code in walkCompare in walk.go.

Seems that involves alias type, using struct directly compiling ok.

**Comment by cuonglm** [comment]
> > Does it also only happen in structs with <= 4 fields? If so, the bug might be in the inlined struct comparison code in walkCompare in walk.go.
> 
> Seems that involves alias type, using struct directly compiling ok.

Ah no, so it works with 0-field struct.
