### ISSUE TITLE
x/build: host-aix-ppc64-osuosl is missing 

### ISSUE THREAD

**Issue by Helflym** [golang/go#38691]
AIX builder is missing. The VM has to be restarted this morning, but something went wrong during the restart. 
It should be up tomorrow.  I'll post updates on this issue, if it needs more time.

**Comment by thanm** [comment]
Thanks for looking into this.

**Comment by Helflym** [comment]
Closing. Everything seems alright. 
I might restart it once just to check that my modification is working correctly.

**Comment by thanm** [comment]
It looks as though the builder is having issues again. According to  https://farmer.golang.org/

host-aix-ppc64-osuosl: 52 waiting (oldest 5h48m3s, newest 1m20s, progress 9m4s)
gomote: 1 (oldest 1m20s, newest 1m20s)

Is this expected?  I kicked off a "gomote create" just now and it is still running after 10 mins.

It would be great if the aix-ppc64 builder were working today, it is one the critical path right at the moment for the new linker effort.

**Comment by thanm** [comment]
Update: my "gomote create" finally went through. Closing the issue again, hopefully it will behave.

**Comment by Helflym** [comment]
yes, the machine is just busy building the delayed commits I think.

**Comment by Helflym** [comment]
I've been warn that the machine will be down again on Thursday 30st of April from 6 GMT to 12 GMT.
