### ISSUE TITLE
database/sql: TestTxCannotCommitAfterRollback flake

### ISSUE THREAD

**Issue by mknyszek** [golang/go#38701]
The test introduced by this change golang.org/cl/216240 has been flaking (albeit rarely) on both dashboard builders and trybots.

`greplogs` reveals:

```
2020-04-22T16:45:05-141b11d/windows-amd64-2008
2020-04-20T20:22:51-7004be9/windows-amd64-2008
```

and I have a trybot failure for an [unrelated change](https://go-review.googlesource.com/c/go/+/229998): https://storage.googleapis.com/go-build-log/b4a5cdf0/linux-amd64-race_056b784c.log

The failure, to repeat it here, is:

```
--- FAIL: TestTxCannotCommitAfterRollback (0.00s)
    sql_test.go:2802: sql: no rows in result set
FAIL
FAIL	database/sql	0.724s
```

CC @kardianos @odeke-em

**Comment by kardianos** [comment]
Those two failures were already noted and fixed with https://go-review.googlesource.com/c/go/+/229478 .

**Comment by mknyszek** [comment]
Got it, my mistake was I only looked for open issues, and the base for my CL was a bit behind. Sorry for the noise.
