### ISSUE TITLE
x/build: increment internal/goversion at the beginning of the release cycle

### ISSUE THREAD

**Issue by heschik** [golang/go#38704]
internal/goversion determines what release tags are in effect. It should be incremented at the beginning of each cycle as part of unfreezing the tree, otherwise who knows when someone will remember to do it. (I just noticed a couple days ago, the week before the freeze. It's not clear to me anyone would have caught it before the beta.)

@dmitshur

**Comment by dmitshur** [comment]
Thanks for reporting. I agree we should ensure this is done at an appropriate time, and not forgotten if someone doesn't send a CL manually.

Looking at some historical data, this used to be done anywhere between very early and late in the development cycle:

- Bumped to 1.14 on [Oct 1, 2019](https://golang.org/cl/198318) (28 days away from Go 1.13 release)
- Bumped to 1.13 on [Feb 20, 2019](https://golang.org/cl/163082) (5 days away from Go 1.12 release)
- Bumped to 1.12 on [Nov 2, 2018](https://golang.org/cl/147219) (70 days away from Go 1.11 release)
- Bumped to 1.11 on [Feb 13, 2018](https://golang.org/cl/93775) (3 days away from Go 1.10 release)
- Bumped to 1.10 on [Aug 25, 2017](https://golang.org/cl/59151) (1 day away from Go 1.9 release)

Doing it predictably at the beginning of the development cycle should be an improvement.

/cc @cagedmantis @toothrot @andybons

**Comment by dmitshur** [comment]
We've added this step to an internal part of release process, so it should happen for the next release and onwards. Closing.

**Comment by dmitshur** [comment]
I've created a recurring release-blocking issue to make this internal part of the release process more visible and easier to track, see #40705.
