### ISSUE TITLE
cmd/compile: prove bounds for & of positive values

### ISSUE THREAD

**Issue by bmkessler** [golang/go#38717]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Compile

```go
package main

func test(foo []byte, i int) {
	_ = foo[63]
	r := i & 63
	_ = foo[r]
}

func main() {}
```

`go build -gcflags="-d=ssa/check_bce/debug=1"`

### What did you expect to see?

Just the first bounds check for the initial length of the slice
```
./test.go:4:9: Found IsInBounds
```

Because prove should be able to deduce that the masked value is bounded by 63 and so is already in bounds.

`r := i&m && m >= 0 --> 0 <= r <= m`

### What did you see instead?

Both accesses require a bounds check.

```
./test.go:4:9: Found IsInBounds
./test.go:6:9: Found IsInBounds
```

This is related to #38476

@rasky @josharian @zdjones

**Comment by zdjones** [comment]
I think this is because prove doesn't make inferences inolving binary operations. I have some CLs I've neglected, to which I could hope to someday add inference over bitwise operations (my employer eliminated our 20% time).

**Comment by randall77** [comment]
Yes, I believe it is.
