### ISSUE TITLE
runtime: throw with mSpanList.Insert exception on Go1.12

### ISSUE THREAD

**Issue by tokers** [golang/go#38718]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go/1.12.13
</pre>

### Does this issue reproduce with the latest release?

It cannot be reproduced stably. We have not yet reproduced it with the latest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go@1.12/1.12.13/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go@1.12/1.12.13/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3h/68msm91n7z9dvjhlxz5ms_z00000gn/T/go-build535753989=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

<details><summary><code>uname -a</code> Output</summary><br><pre>
$ uname -a
Linux 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64
</pre></detail>

### What did you do?

We just run Istio Pilot on our product environment (Virtual Machine). It runs for a long while and it's the first time we meet that scenario.

### What did you expect to see?

No fatal error and process panic.

### What did you see instead?

Process panic.

![image](https://user-images.githubusercontent.com/10428333/80470085-146b2800-8974-11ea-9687-51bfad1cc512.png)

**Comment by andybons** [comment]
Go 1.12 is no longer supported. If you are able to provide code that reproduces this on a supported release (1.13 or 1.14) that would be helpful. Thanks.

**Comment by tokers** [comment]
The probability to reproduce it is very small, so that'd be a long time waiting :(. Anyway, we will follow up this issue and paste any useful information.

**Comment by ALTree** [comment]
We don't have a reproducer and 1.12 is no longer supported. I'm closing this issue, feel free to open a new one if you hit this on 1.15.
