### ISSUE TITLE
x/website/internal/dl: make https://golang.org/dl/{file} URLs more useful

### ISSUE THREAD

**Issue by dmitshur** [golang/go#38713]
Go binary downloads have been available at the URL `https://golang.org/dl/{file}` since at least 2015 (see [CL 14842](https://golang.org/cl/14842)). That URL serves a 302 Found redirect to another URL which serves the actual bytes. The exact target of redirection is an implementation detail that has changed over the years (e.g., most recently in [CL 76971](https://golang.org/cl/76971)).

The `https://golang.org/dl/{file}` URL is short, memorable, has golang.org in it, and has been around for long enough that it's temping to perceive to be more future-proof than any URL it happens to point to (similar to how https://golang.org/issue/123 is more future-proof than a direct link to an issue tracker, https://code.google.com/p/go/issues/detail?id=123).

However, as far as I can tell so far, it doesn't seem to be used on golang.org or documented anywhere:

1.	The links on the https://golang.org/dl/ HTML page point directly the redirect target of `https://golang.org/dl/{file}`, which is `https://dl.google.com/go/{file}` [since 2017](https://golang.org/cl/76971).
2.	The API endpoint at https://golang.org/dl/?mode=json has filenames only.
3.	Package [`golang.org/x/website/internal/dl`](https://pkg.go.dev/golang.org/x/website/internal/dl) documentation doesn't mention it.

The only documentation seems to be the source code. That makes it difficult to recommend as a future-proof URL (to use in scripts, etc.) despite the favorable properties above.

Also see #22648 (it was about the redirect target URLs).

/cc @andybons @mvdan @adg @broady @bradfitz

**Comment by dmitshur** [comment]
I think we can fix this issue by changing the links on the https://golang.org/dl/ HTML page to use `https://golang.org/dl/{file}`. That will help establish them as canonical URLs, and make it less troublesome if we ever need to change where the actual bytes are served from. If someone wants to be able to do `curl` without `-L` flag, they can continue to use the redirect target.

Am I missing any context? Thoughts?

**Comment by bradfitz** [comment]
IIRC the original point of that handler was just to make `go get golang.org/dl/go1.n.m` work (as in https://twitter.com/golang/status/1248018480479096833 etc).

But once we had the go-get metadata, we needed to do something the URLs about non-cmd/go clients. That was never the goal, though.

**Comment by dmitshur** [comment]
In 2015, `getHandler` was serving the list of downloads (the https://golang.org/dl/ page), the files themselves (via redirect), and 404 for everything else. This is from [CL 14842](https://golang.org/cl/14842):

```Go
func getHandler(w http.ResponseWriter, r *http.Request) {
	name := strings.TrimPrefix(r.URL.Path, "/dl/")
	if name == "" {
		listHandler(w, r)
		return
	}
	if !fileRe.MatchString(name) {
		http.NotFound(w, r)
		return
	}
	http.Redirect(w, r, gcsBaseURL+name, http.StatusFound)
}
```

The ?go-get=1 handler code path for `golang.org/dl/go1.n.m` commands was added in 2018 via [CL 123679](https://golang.org/cl/123679).

**Comment by dmitshur** [comment]
There haven't been concerns or objections raised regarding the solution I suggested in https://github.com/golang/go/issues/38713#issuecomment-620264105. I plan to proceed with it soon. In the unlikely case we learn of something that goes poorly as a result, this will be easy to undo.
