### ISSUE TITLE
x/playground: tzdata not present on playground

### ISSUE THREAD

**Issue by ecc1** [golang/go#38727]
The ParseInLocation example panics when run on the website:
```
2012-07-09 05:02:00 +0000 CEST
panic: time: missing Location in call to Date

goroutine 1 [running]:
time.Date(0x7dc, 0x7, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go-faketime/src/time/time.go:1371 +0x630
time.parse(0x4d0251, 0xb, 0x4d025c, 0xb, 0x0, 0x0, 0x0, 0x0, 0xc000052180, 0x0, ...)
	/usr/local/go-faketime/src/time/format.go:1187 +0x2f0d
time.ParseInLocation(...)
	/usr/local/go-faketime/src/time/format.go:824
main.main()
	/tmp/sandbox338262955/prog.go:18 +0x1a7
```

**Comment by andybons** [comment]
`time.LoadLocation` is returning an error: `unknown time zone Europe/Berlin`

**Comment by andybons** [comment]
Many of the time examples are not functioning: https://golang.org/pkg/time/#example_ParseInLocation

@toothrot

**Comment by andybons** [comment]
@toothrot let me know if I can help with this at all.

**Comment by toothrot** [comment]
Looks like we're missing zoneinfo:

```
UTC unknown time zone Europe/Berlin
```

**Comment by toothrot** [comment]
Fixed, deployed sandbox, and cleared cache.

Thanks for reporting!

**Comment by ianlancetaylor** [comment]
For what it's worth, once the playground uses 1.15 you could just compile the program with `-tags timetzdata`.
