### ISSUE TITLE
x/mod: expose API to do GOPRIVATE matching

### ISSUE THREAD

**Issue by mvdan** [golang/go#38725]
That is: https://github.com/golang/go/blob/863424beb2ef735c273af87801bf56f252285889/src/cmd/go/internal/str/path.go#L54-L96

`go help module-private` does briefly mention the semantics:

> The variable is a comma-separated list of glob patterns (in the syntax of Go's path.Match) of module path prefixes.

However, I don't think that's quite detailed enough to implement this from scratch, and it's still pretty tricky and prone to errors to do.

I realise that package pattern matching wasn't exposed as a library on purpose, to encourage tool authors to use `go list` instead. However, I don't think this falls under the same bucket since there's no way to do this via the go tool, and because GOPRIVATE matching should be a very cheap operation - it doesn't involve any disk or network I/O for example, unlike patterns like `cmd/...`.

**Comment by bcmills** [comment]
CC @jayconrod @matloob

**Comment by jayconrod** [comment]
Seems like a good thing to have. Maybe in `module` we could add:

```
func MatchPatterns(path, patterns string) bool
```

where `path` is a module path and `patterns` is a string in the format expected by `GOPRIVATE` and friends?

**Comment by bcmills** [comment]
I might be inclined to use a different name, since these patterns are looser than our usual “module path patterns”: they implicitly apply to prefixes, and they support the full glob syntax instead of just `...`.

Maybe `module.MatchPrefixPatterns`?

**Comment by mvdan** [comment]
My only thought on the matter is that the "patterns" parameter should go first, to match what people are used to from the standard library - look at `path.Match`, for example.

**Comment by stamblerre** [comment]
Just came across this issue and wanted to add my support for this. @findleyr already added `IsGoPrivatePath` functionality to `gopls` as part of https://github.com/golang/go/issues/36998, so it would be really nice to move that logic into x/mod. What's the next step for this issue? Can we mail a CL?

**Comment by jayconrod** [comment]
Sure, CLs welcome. It should go into `golang.org/x/mod/module` with the signature:

```
func MatchPrefixPatterns(patterns, path string) bool
```

That can land immediately, and we can tag a prerelease version if that's useful. We should update `cmd/go` to use the logic in `x/mod` after 1.16 development is open.

**Comment by findleyr** [comment]
In retrospect I probably should have made an effort to put this in x/mod before copying...

I can send a CL.
