### ISSUE TITLE
x/sys/unix: add support for timerfd syscalls on Linux

### ISSUE THREAD

**Issue by itwaseasy** [golang/go#38733]
### What version of Go are you using (`go version`)?

<pre>
go version go1.14.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pugachev/.cache/go-build"
GOENV="/home/pugachev/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pugachev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/5646"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/5646/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/pugachev/work/golang_xsys/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build463295103=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

The project I'm working on uses epoll for low-level network code. And lack of timerfd support in x/sys/unix is a problem for me because I have to invent various workarounds for timers.

I'd like to submit a patch for this, if nobody objects.

### What did you expect to see?

Support for timerfd in x/sys/unix package.

### What did you see instead?

No support at the moment.

**Comment by tklauser** [comment]
> I'd like to submit a patch for this, if nobody objects.

Please feel free to send a CL.

Quoting @ianlancetaylor from https://groups.google.com/d/msg/golang-dev/A2QnYWHoAao/uCNaGGLiBAAJ:

> That said, x/sys is all about unportable features.  If someone wants
to add the timerfd system calls, I think that would be OK.  I agree
that they would be hard to use in a Go program, but the same is true
of other functions already in x/sys.
