### ISSUE TITLE
image: NewUniform doesn't have documentation

### ISSUE THREAD

**Issue by dmitshur** [golang/go#38739]
The [`image.NewUniform`](https://golang.org/pkg/image/#NewUniform) function is exported and should have a comment per https://golang.org/doc/effective_go.html#commentary.

This came up when I realized it's not clear whether it's better to write `image.NewUniform(c)` or `&image.Uniform{c}`. I thought maybe `image.NewUniform` is deprecated like `image.ZP`, but that's not the case given it doesn't even have a comment. But it's not easy to feel confident using an exported method in the Go standard library when it's not documented.

https://blog.golang.org/image-draw prefers `&image.Uniform{c}` style, but it's also from 2011. `NewUniform` was renamed from `NewColorImage` in 2011, so it has existed for quite a while.

/cc @nigeltao @robpike

**Comment by nigeltao** [comment]
I agree that `image.NewUniform` needs a doc comment. I'll send out a (trivial) CL.

As for which of `image.NewUniform(c)` or `&image.Uniform{c}` is better, I think they're equally good, similar to `io.LimitReader(r, n)` and `&io.LimitedReader{R:r, N:n}`. I wouldn't mark either of them as deprecated. In hindsight, we could have only picked one, especially as composite literals are no longer a scary and new feature, but we can't change that now.
