### ISSUE TITLE
x/tools/cmd/goimports: put std, cmd packages in separate blocks

### ISSUE THREAD

**Issue by jayconrod** [golang/go#38735]
This came up in [CL 228378](https://go-review.googlesource.com/c/go/+/228378) and many others. If we delete all the imports from `src/cmd/go/internal/modload/modfile.go` then run `goimports`, we should see `cmd` imports in a separate group from `std` imports:

```
import (
	"fmt"
	"io/ioutil"
	"path/filepath"

	"cmd/go/internal/base"
	"cmd/go/internal/cfg"
	"cmd/go/internal/modfetch"

	"golang.org/x/mod/modfile"
	"golang.org/x/mod/module"
	"golang.org/x/mod/semver"
)
```

Instead, all the `std` and `cmd` imports are grouped together.

```
import (
	"cmd/go/internal/base"
	"cmd/go/internal/cfg"
	"cmd/go/internal/modfetch"
	"fmt"
	"io/ioutil"
	"path/filepath"

	"golang.org/x/mod/modfile"
	"golang.org/x/mod/module"
	"golang.org/x/mod/semver"
)
```

`goimports` does the right thing if at least one `cmd` import is already in a separate group. It combines the groups when adding the first `std` or `cmd` import though.

**Comment by heschik** [comment]
To be clear, do you really want it in three sections, or do you just want `cmd/` grouped with `golang.org/x`? Because the latter seems like a bug that should be fixed. The former would be more of a job for `-local`.

**Comment by bcmills** [comment]
The existing files in `cmd/go` mostly have it in three sections, so we would like to retain that.

But it looks like the existing files in `cmd/compile` make no such distinction. Perhaps we should reformat `cmd` to eliminate it too, and collapse down to only two sections.

**Comment by heschik** [comment]
Not sure what you'd like me to do here. I can change it so that `cmd/` is grouped with `golang.org`, but `-local` is the only way to get three groups, and in general `goimports` will never merge groups, so if you want to collapse down to two you're going to have to give it some help.

**Comment by jayconrod** [comment]
After some discussion, we're leaning toward just combining `std` and `cmd` sections.

I was not at all aware of the `-local` flag, so it looks like that's there if we decide otherwise.

I'll close this. Looks like there's nothing to do on the `goimports` side.
