### ISSUE TITLE
access: request for Gerrit access

### ISSUE THREAD

**Issue by zhangfannie** [golang/go#38738]
Hi Go team:

I'm Fannie Zhang (fannie.zhang@arm.com) from Arm, I'd like to request for Gerrit access.

I have been working on Golang optimization and new features enablement for more than three years on full time, and submitted about a number of patches on assembler, linker and compiler. I have understood and adhered to the relevant specifications of the go community, and I have been participating in code review and issue fixing work actively. I'll continue working on Golang, so in order to make it easier for me to contribute to the Golang, please approve my request, thanks!

**Comment by ALTree** [comment]
cc @andybons @dmitshur

**Comment by andybons** [comment]
Fannie has [47 merged changes](https://go-review.googlesource.com/q/owner:Fannie.Zhang%2540arm.com+status:merged) over 2 years and was also vetted by @cherrymui who is a frequent reviewer on those changes.

Providing +2 access.

**Comment by andybons** [comment]
Done.

**Comment by zhangfannie** [comment]
Thank you.
