### ISSUE TITLE
cmd/compile: generates invalid instruction when using bit shifts on amd64

### ISSUE THREAD

**Issue by kynrai** [golang/go#38746]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/steve/go/bin"
GOCACHE="/Users/steve/Library/Caches/go-build"
GOENV="/Users/steve/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/steve/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/steve/Projects/kynrai/invalid_instruction/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sm/hgxsvgvx3h93cb_0cwyj39g80000gn/T/go-build850937365=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Using bit shifts to store data when a sequence of code causes a invalid instruction error:
`invalid instruction: 00080 (invalid_test.go:22)	ANDQ	$9223372034707292159, CX`

I have minimised the code example to the smallest amount of code that will reproduce the error.

```go
package invalid

import (
	"testing"
)

type ValuesMask uint64

func (v *ValuesMask) PrintBits() {
	for i := 0; i < 64; i++ {
	}
}

func TestMask(t *testing.T) {
	v := ValuesMask(0)
	v.PrintBits()

	v &^= (1 << 31)

	v |= 1 << 63

	v &^= (1 << 63)
}
```

### What did you expect to see?

No error? or a pointer related error at worst

### What did you see instead?
`invalid instruction: 00080 (/Users/steve/Projects/kynrai/invalid_instruction/invalid_test.go:22)	ANDQ	$9223372034707292159, CX`

**Comment by marigonzes** [comment]
This code stopped compiling between go1.11 and go1.12, so I did a bisection and commit c6bf9a8 popped up, which seems right.

**Comment by ALTree** [comment]
Thank for reporting this, and thanks @marigonzes for the bisection.

cc @randall77

**Comment by josharian** [comment]
I suspect converting those rules to be strongly typed will fix this. Is anyone currently working on typing the amd64 rules? (We’ll need a test added either way.)

**Comment by ALTree** [comment]
It appears that just making this rule typed:

```
(BTR(L|Q)const [c] (BTR(L|Q)const [d] x)) => (AND(L|Q)const [^(1<<uint32(c) | 1<<uint32(d))] x)
```
fixes at least the reproducer above. I don't think anyone is working on these amd64 rules at the moment. Will send a change to see if that's enough.

**Comment by randall77** [comment]
```
(BTR(L|Q)const [c] (BTR(L|Q)const [d] x)) -> (AND(L|Q)const [^(1<<uint32(c) | 1<<uint32(d))] x)
```
That rule is just wrong. We need c<32 and d<32 as preconditions.
Just typing it won't help - it will still lose the upper bits of the mask (for the `Q` version, at least).

**Comment by ALTree** [comment]
Thanks. Holding the change for now then.
