### ISSUE TITLE
cmd/compile: several arm64 code-gen issues

### ISSUE THREAD

**Issue by shawn-xdji** [golang/go#38740]
### What version of Go are you using (`go version`)?

<pre>
$ go version
tip
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Several code-gen (optimization) issues relevant to utilizing CMN/CMP instructions on arm64 were spotted recently, it will take time to identify all of them, create a placeholder issue tracker for updating.

example:

A condition like "if (x1+3) < 0" gets translated to the following instructions, that is transforming to "if x1 < -3"
   cmn     x0, #0x3
   b.ge    <else branch>

But such transformation doesn't hold true, in case executing 'cmn' set the overflow flag, internally 'cmn' is an alias of the 'adds' instruction which performs add with carry set operation.

**Comment by shawn-xdji** [comment]
working on collecting all scenarios that hit the problem and a fix.

**Comment by shawn-xdji** [comment]
[rewriteARM64_test.txt](https://github.com/golang/go/files/4590742/rewriteARM64_test.txt)
Attaching an initial version of the negative scenarios identified so far.

**Comment by randall77** [comment]
This issue is causing incorrect code generation on (at least) arm64 and arm.
It's a pretty esoteric case (comparisons after integer overflow), so I don't think it should block beta1, but should be fixed before release.

**Comment by randall77** [comment]
... and will probably need backporting as well, depending on what the fix looks like.

**Comment by randall77** [comment]
I think this is now fixed. Please reopen if you think there's more to do here.
