### ISSUE TITLE
Deleting values from URL query parameter is not working

### ISSUE THREAD

**Issue by Abhaykumar1** [golang/go#38750]
go version go1.13.3 windows/amd64

Trying to remove the value of the query parameter from the request (r *http.Request)

Doing this 
r.URL.Query().Del("activityDate")

Expect the value to be removed from the header
but when I log the value 
logger.Printf("activityDate: %v", r.URL.Query().Get("activityDate"))

I get value still present in the request activityDate: 2020-04-29

**Comment by andybons** [comment]
`Query()` parses the *URL values using the `RawQuery` property and returns a `Values` object from that. Unless you set `RawQuery`, nothing will change.

https://golang.org/src/net/url/url.go?s=29179:29207#L1021

**Comment by Abhaykumar1** [comment]
Thank you, I used the RawQuery to set the values. Its working now

**Comment by andybons** [comment]
Great. Glad that helped.
