### ISSUE TITLE
cmd/go: `go mod download` needs a --verbose option

### ISSUE THREAD

**Issue by ORESoftware** [golang/go#38756]
go version 1.13

https://github.com/golang/go/issues/12197

```
Step 20/32 : RUN go mod download -v
 ---> Running in 06ada58d25d7
flag provided but not defined: -v
usage: go mod download [-json] [modules]
Run 'go help mod download' for details.

```

**Comment by bcmills** [comment]
Please fill out the complete issue template. What information would you expect `go mod download -v` to print?

**Comment by ORESoftware** [comment]
The same info as `go install -v` :(

**Comment by jayconrod** [comment]
`go install -v` prints each package as it's built. `go mod download` doesn't work with packages, so it can't really do that.

So what would `-v` mean here? Print each module when it starts downloading? Show a progress bar? Print other metadata about the modules? It would help if you could give an example.

**Comment by hyangah** [comment]
fyi - there is `go mod download -x` if you want to know what's happening behind.

**Comment by ORESoftware** [comment]
i guess worst case scenario, go mod download -v is an alias for go mod download -x?

**Comment by jayconrod** [comment]
The `-x` flag was added to `go mod download` in 1.14 (`go mod download -x`). Can you try it there and see if it does what you want?

**Comment by ORESoftware** [comment]
I am stuck on 1.13 for the moment, unfortunately

**Comment by jayconrod** [comment]
Sorry, our [policy](https://github.com/golang/go/wiki/MinorReleases) is only to backport fixes for security issues, serious problems with no workaround, and documentation fixes. We won't backport `-x` to 1.13 or 1.14. The freeze for 1.15 begins tomorrow, so there isn't time to add new features for that. So this would be for 1.16 at the earliest.

But we still don't really understand what you want. If you need something different from `-x`, please say what that is and give an example.

**Comment by ORESoftware** [comment]
Ultimately I was expecting `go mod download -v` to print much of the same info that `go install -v` does, that was all.

**Comment by jayconrod** [comment]
`go install -v` prints each package as it's built. `go mod download` doesn't work with packages, so it can't really do that.

All module commands print information about modules being downloaded to stderr by default, so it doesn't seem like there's anything else to do here.
