### ISSUE TITLE
x/tools/gopls: high memory usage with VS Code remote dev in github.com/cockroachdb/cockroach

### ISSUE THREAD

**Issue by stamblerre** [golang/go#38752]
Report on Slack:

> huh, has anyone seen gopls taking 25+ 35 GiB of ram / getting OOMKilled?
strangely, it seems fine run locally on my laptop, where I only have 16gb total, but when I use VSCode’s remote dev feature, checking out the exact same codebase, but on a much bigger and beefier cloud VM, it gets OOMkilled a couple times a day with reported vm of 35GB. (edited) 

Profiles:
[gopls.30591-26GiB-goroutines.txt](https://github.com/golang/go/files/4553194/gopls.30591-26GiB-goroutines.txt)
[gopls.30591-26GiB-heap.pb.gz](https://github.com/golang/go/files/4553195/gopls.30591-26GiB-heap.pb.gz)

Local changes: https://github.com/cockroachdb/cockroach/compare/master...dt:gopls-oom?expand=1

/cc @heschik

**Comment by knz** [comment]
This issue has been addressed: #38080

which seems to reduce RAM usage considerably.

**Comment by heschik** [comment]
Great!
