### ISSUE TITLE
dyld: malformed mach-o image in newest Go version

### ISSUE THREAD

**Issue by buihdk** [golang/go#38765]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.14.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/khoa.bui/Library/Caches/go-build"
GOENV="/Users/khoa.bui/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/khoa.bui/Developer/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/khoa.bui/Developer/go/src/gitlab.myteksi.net/gophers/go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vm/9_12bl356vlgk_v57gbyywy40000gq/T/go-build402714995=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I ran this script `db.sh todolist`
<details><summary><code>db.sh</code></summary><br><pre>
set -e

GOSRC=$GOPATH/src/gitlab.myteksi.net/gophers/go
source "$GOSRC/scripts/env-vars.sh" "$GOSRC" "-ci" >/dev/null 2>&1
exec python -u "$GOSRC/scripts/db.py" "$@"
</pre></details>

<details><summary><code>db.py</code></summary><br><pre>
#!/usr/bin/env python
from __future__ import print_function

import re
import os
import json
import argparse
import itertools
import socket
import subprocess

pkg_prefix = 'gitlab.myteksi.net/gophers/go'
sql_dir = 'resources/sql'
go_path = os.environ['GOPATH']
code_dir = os.path.join(go_path, 'src', pkg_prefix)
mysql_host = os.environ.get('MYSQL_HOST', 'localhost')
mysql_port = os.environ.get('MYSQL_PORT', '3306')
mysql_root_password = os.environ.get('MYSQL_ROOT_PASSWORD', '')
postgres_host = os.environ.get('POSTGRES_HOST', 'localhost')
d_env = dict(os.environ, MYSQL_PWD='{}'.format(mysql_root_password))
all_dbs = {}
all_users = {}

def need_migration(ci_file):
    with open(ci_file) as f:
        ci = json.load(f)
    for task in ci.get('BeforeTest', []):
        if task['TYPE'] == 'migrate_mysql':
            if task.get('MigrateSQLDir', ''):
                return True
    return False

def get_services(folders):
    concise = lambda f: f[len(code_dir) + 1:]
    return sorted(list(set(map(concise, itertools.chain(*(get_service(folder) for folder in folders))))))

def get_service(folder):
    f = folder
    while f != code_dir:
        ci = os.path.join(f, 'ci.json')
        if os.path.isfile(ci) and need_migration(ci):
            return [f]
        f = os.path.dirname(f)
    return [root for root, dirs, files in os.walk(folder)
            if 'ci.json' in files and need_migration(os.path.join(root, 'ci.json'))]

def get_sql_files(folder):
    return sorted([os.path.join(root, f)
                   for root, dirs, files in os.walk(folder)
                   for f in files
                   if re.match(r'.*\.sql$', f)])

def run_mysql(cmd):
    subprocess.check_call(
        ['mysql', '-uroot', '-h', mysql_host, '-P', mysql_port,'-e', cmd], env=d_env
    )

def run_postgres(name, cmd, isfile=False):
    subprocess.check_call(['psql', '-U', 'postgres', '-h', postgres_host, '-w', '-d', name, ('-f' if isfile else '-c'), cmd])

# This is the old legacy way of doing things
def init_tables(db):
    print("Creating schemas for %s ..." % db['name'])
    sql_folder = os.path.join(sql_dir, db['sql_dir']) if 'sql_dir' in db else sql_dir

    sqls = get_sql_files(sql_folder)
    errors = []
    for sql in sqls:
        with open(sql) as f:
            content = f.read()
        p = subprocess.Popen(
            [
                'mysql',
                '-uroot',
                '-h',
                mysql_host,
                '-P',
                mysql_port,
                db['name']
            ],
            stdin=subprocess.PIPE,
            env=d_env
        )
        p.communicate(input=str.encode(re.sub(r'^--\s*\+migrate Down[\s\S]*', r'', content, flags=re.M)))
        if p.returncode != 0:
            errors.append(sql)

    print('Imported %d sql files' % (len(sqls) - len(errors)))
    if errors:
        print('>> Failed to import these sql files: \n\t%s' % '\n\t'.join(errors))
        exit(-2)

# This is the new versioned mysql route
def migrate_mysql_tables(db, action):
    sql_folder = os.path.join(sql_dir, db['sql_dir'])
    db_dir = os.path.dirname(os.path.dirname(sql_folder))
    conf_file = os.path.join(sql_folder, 'dbconfig.yml')

    command = {'init':'up', 'down-to-bottom': 'down'}.get(action, action)
    p = subprocess.check_call(["sql-migrate", command, "-config=" + conf_file] + (
        ['-limit=0'] if action == 'down-to-bottom' else []), cwd=db_dir)
    if p:
        print ("Error applying schema for %s" % db['name'])
        # One probable cause could be miss-configuration of config
        mysql_migration_warning_message()
        exit(-1)

def migrate_postgres_tables(db):
    [run_postgres(db['name'], f, True)
            for f in get_sql_files(db['sql_dir'])]

# This will run any specified data population
def populate_database(db):
    if ('populate_dir' in db) and (db['populate_dir'] != ''):
        print('Populating database with %s' % db['populate_dir'][len(code_dir) + 1:])
        with open(db['populate_dir']) as f:
            subprocess.check_call(
                [
                    'mysql',
                    '-uroot',
                    '-h',
                    mysql_host,
                    '-P',
                    mysql_port,
                    db['name']
                ],
                stdin=f,
                env=d_env
            )
    else:
        print('No data population configured for %s' % db['name'])

def create_and_grant_mysql(name, user, password, sql_dir):
    if name not in all_dbs:
        run_mysql('DROP DATABASE IF EXISTS %s; CREATE DATABASE %s;' % (name, name))
        all_dbs[name] = sql_dir
        print("Created database %s" % name)
    else:
        if sql_dir != all_dbs[name]:
            print("Database %s has different directories for migration '%s' vs '%s'" % (name, all_dbs[name], sql_dir))
            exit(-4)
        print("Database %s has been created before; skip" % name)

    if user in all_users and password != all_users[user]:
        print("Database username %s has different passwords '%s' and '%s'" % (user, all_users[user], password))
        exit(-5)

    if user == 'root':
        print('root is not allowed as a database username.')
        exit(-6)

    all_users[user] = password

    def get_ips():
        result = ['127.0.0.1', 'localhost']
        try:
            result.append(socket.gethostbyname(socket.gethostname()))
        except socket.gaierror:
            pass
        return result

    # use the update syntax for MySQL 8.x while keeping backwards compatibility
    for host in get_ips():
        run_mysql("CREATE USER IF NOT EXISTS '%s'@'%s' IDENTIFIED BY '%s';" % (user, host, password))
        run_mysql("GRANT ALL PRIVILEGES ON %s.* TO '%s'@'%s';" % (name, user, host))
    run_mysql('FLUSH PRIVILEGES;')

def create_and_grant_postgres(name):
    run_postgres('postgres', 'DROP DATABASE IF EXISTS %s;' % name)
    run_postgres('postgres', 'CREATE DATABASE %s OWNER postgres;' % name)
    print('Create postgres %s' % name)

def can_connect_mysql(cmd):
    """This method will check if we connect to MySQL.
    It uses current env vars, like rest of the code."""
    try:
        subprocess.check_output(
            [
                'mysql',
                '-uroot',
                '-h',
                mysql_host,
                '-P',
                mysql_port,
                '-e',
                cmd
            ],
            env=d_env
        )
    except subprocess.CalledProcessError as err:
        # in case of non-zero exit from subprocess this will happen, which would mean we failed to connect.
        return False
    return True

def mysql_migration_warning_message():
    print("\n\n"
          "NOTE: This script assumes that you are using the default MySQL installation.\n"
          "If you have changed MySQL's root password, you will see `Access Denied` error messages from MySQL.\n"
          "In such case try setting the following env vars to their appropriate values:\n\n"
          "MYSQL_HOST\n"
          "MYSQL_PORT\n"
          "MYSQL_USER\n"
          "MYSQL_PASSWORD\n"
          "MYSQL_ROOT_PASSWORD\n")
    exit(-4)

def migrate_mysql(db, action):
    # Check if we cannot talk to MySQL print the warning and exit
    if can_connect_mysql("clear") is False:
        mysql_migration_warning_message()

    skip = db['name'] in all_dbs

    if action == 'test':
        for a in ('create', 'up', 'down-to-bottom', 'up', 'datapop'):
            migrate_mysql_with_skip(db, a, skip)
    else:
        migrate_mysql_with_skip(db, action, skip)

def migrate_mysql_with_skip(db, action, skip):
    print('=> %s: ' % action, end='')
    if action in ('init', 'create'):
        create_and_grant_mysql(db['name'], db['user'], db['password'], db['sql_dir'])

    if not skip and action in ('init', 'up', 'down', 'down-to-bottom', 'status'):
        migrate_mysql_tables(db, action)

    if action in ('init', 'datapop'):
        populate_database(db)

def migrate_postgres(db, action):
    if action in ('init', 'test'):
        create_and_grant_postgres(db['name'])
        migrate_postgres_tables(db)

def init_service(service, max_len, action):
    os.chdir(os.path.join(code_dir, service))

    prefix = 30 + (max_len - len(service)) // 2
    suffix = 60 + max_len - len(service) - prefix
    print('-' * prefix + service + '-' * suffix)

    with open('ci.json') as f:
        ci = json.load(f)

    # perform versioned creation of databases and run their sql
    [migrate_mysql(dict(
        name=task['DBName'],
        user=task['TestUser'],
        password=task['TestPassword'],
        populate_dir=re.sub(r'\$CODE_DIR', code_dir, task.get('PopulateSQL', '')),
        sql_dir=re.sub(r'\$CODE_DIR', code_dir, task['MigrateSQLDir'])), action)
        for task in ci.get('BeforeTest', [])
        if task['TYPE'] == 'migrate_mysql' and 'MigrateSQLDir' in task]

    [migrate_postgres(dict(
        name=task['DBName'],
        sql_dir=re.sub(r'\$CODE_DIR', code_dir, task['MigrateSQLDir'])), action)
        for task in ci.get('BeforeTest', [])
        if task['TYPE'] == 'migrate_postgres']

def init(folders, action):
    services = get_services(folders)
    max_len = max([len(s) for s in services] + [0])
    for service in services:
        init_service(service, max_len, action)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Migrate databases.')
    parser.add_argument('paths', nargs='*', default=[''])
    group = parser.add_mutually_exclusive_group()
    group.add_argument('-up', '--up', action='store_const', const='up', dest='action', default='init')
    group.add_argument('-down', '--down', action='store_const', const='down', dest='action')
    group.add_argument('-status', '--status', action='store_const', const='status', dest='action')
    group.add_argument('-create', '--create', action='store_const', const='create', dest='action')
    group.add_argument('-datapop', '--datapop', action='store_const', const='datapop', dest='action')
    group.add_argument('-test', '--test', action='store_const', const='test', dest='action')

    args = parser.parse_args()

    print('~~~ Start to initialize mysql/postgres databases ~~~')

    if '' in args.paths:
        print('-'*97 +
              "\nWarning: it's faster to pass in a folder as a parameter.\nFor example: db.sh dispatcher/grab-id")

    init([os.path.realpath(os.path.join(code_dir, p)) for p in args.paths], args.action)

    print('~~~ End to initialize mysql/postgres databases ~~~')
</pre></details>

### What did you expect to see?
<pre>
$ ../scripts/db.sh todolist

~~~ Start to initialize mysql/postgres databases ~~~
------------------------------todolist/cmd/server------------------------------
=> init: Created database todolist
Applied 0 migrations
No data population configured for todolist
~~~ End to initialize mysql/postgres databases ~~~
</pre>

### What did you see instead?
<pre>
~~~ Start to initialize mysql/postgres databases ~~~
------------------------------todolist/cmd/server------------------------------
=> init: Created database todolist
dyld: malformed mach-o image: segment __DWARF has vmsize < filesize
Traceback (most recent call last):
  File "/Users/khoa.bui/Developer/go/src/gitlab.myteksi.net/gophers/go/scripts/db.py", line 305, in <module>
    init([os.path.realpath(os.path.join(code_dir, p)) for p in args.paths], args.action)
  File "/Users/khoa.bui/Developer/go/src/gitlab.myteksi.net/gophers/go/scripts/db.py", line 283, in init
    init_service(service, max_len, action)
  File "/Users/khoa.bui/Developer/go/src/gitlab.myteksi.net/gophers/go/scripts/db.py", line 270, in init_service
    if task['TYPE'] == 'migrate_mysql' and 'MigrateSQLDir' in task]
  File "/Users/khoa.bui/Developer/go/src/gitlab.myteksi.net/gophers/go/scripts/db.py", line 231, in migrate_mysql
    migrate_mysql_with_skip(db, action, skip)
  File "/Users/khoa.bui/Developer/go/src/gitlab.myteksi.net/gophers/go/scripts/db.py", line 240, in migrate_mysql_with_skip
    migrate_mysql_tables(db, action)
  File "/Users/khoa.bui/Developer/go/src/gitlab.myteksi.net/gophers/go/scripts/db.py", line 109, in migrate_mysql_tables
    ['-limit=0'] if action == 'down-to-bottom' else []), cwd=db_dir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sql-migrate', 'up', u'-config=/Users/khoa.bui/Developer/go/src/gitlab.myteksi.net/gophers/go/todolist/databases/mysql/dbconfig.yml']' returned non-zero exit status -6
</pre>

**Comment by thanm** [comment]
Thanks for the report.

Could you please post the "go build" command in question?

**Comment by buihdk** [comment]
> Thanks for the report.
> 
> Could you please post the "go build" command in question?

@thanm I did not run the `go build` command. I ran `go build cmd/server/main.go` and got no issue. However, if I execute the attached `db.sh` script which in turn executes the attached `db.py` script, I get the error `dyld: malformed mach-o image: segment __DWARF has vmsize < filesize` in the report.

**Comment by thanm** [comment]
Yes, I get that you are running a large and complicated script-- that's why I asked about the "go build" command.  I'm happy to debug problems with "go build", but I'm not sure I'm the right person to be debugging a python script. 

Looking at the first part of your python script, I see

```
pkg_prefix = 'gitlab.myteksi.net/gophers/go'
sql_dir = 'resources/sql'
go_path = os.environ['GOPATH']
code_dir = os.path.join(go_path, 'src', pkg_prefix)

```
This suggests that the script is using a forked copy of Go, as opposed to a release copy. What vintage is "gitlab.myteksi.net/gophers/go"?

**Comment by buihdk** [comment]
The "gitlab.myteksi.net/gophers/go" is just the directory, print(code_dir) will give `/Users/khoa.bui/Developer/go/src/gitlab.myteksi.net/gophers/go`.

In go.mod, the go version is 1.13

**Comment by thanm** [comment]
Again, for me to debug this, I need to see the "go build" command that's being run.  If you can help me out with that, then I can try to take a closer look.

**Comment by buihdk** [comment]
Hi @thanm, seems like you were right, the "gitlab.myteksi.net/gophers/go" was using an older version of Go and I managed to update to the latest version and now it doesn't have that issue anymore. Thank you for spending your time to support and help me to debug this issue! I will close this issue now.

**Comment by thanm** [comment]
Thanks, good to hear you were able to figure things out.
