### ISSUE TITLE
Go truncates the trailing zeros in the milli second values 

### ISSUE THREAD

**Issue by Abhaykumar1** [golang/go#38778]
Version : go 1.13

When the defined time has trailing zero after the millisecond
trailingZero = "2020-02-19T07:11:23.890+00:00"
noTrailingZero = "2020-02-19T07:11:23.891+00:00"

GO removes the trailing zero. The time becomes

2020-02-19 07:11:23.89 +0000 UTC
2020-02-19 07:11:23.891 +0000 UTC

This is an issue when other consuming application tries to consume this by defining a date formatter to get time from String value. The formatter does the strict matching.

for example in java
String pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSz";
SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);

It will throw an exception while parsing 2020-02-19 07:11:23.89 +0000 UTC while will perfectly work for 2020-02-19 07:11:23.891 +0000 UTC

Code To Replicate
const (
trailingZero = "2020-02-19T07:11:23.890+00:00"
noTrailingZero = "2020-02-19T07:11:23.891+00:00"
)

func main() {
parseAndPrint(trailingZero)
parseAndPrint(noTrailingZero)
}

func parseAndPrint(timeString string) {
parsed, err := time.Parse(time.RFC3339, timeString)
if err != nil {
panic(err)
}
fmt.Println(parsed)
}

**Comment by ianlancetaylor** [comment]
If you want trailing zeroes, use your own format string rather than the default one.  For example, here is a modification of your program:

```Go
package main

import (
	"fmt"
	"time"
)

const (
	trailingZero   = "2020-02-19T07:11:23.890+00:00"
	noTrailingZero = "2020-02-19T07:11:23.891+00:00"
)

func main() {
	parseAndPrint(trailingZero)
	parseAndPrint(noTrailingZero)
}

func parseAndPrint(timeString string) {
	parsed, err := time.Parse(time.RFC3339, timeString)
	if err != nil {
		panic(err)
	}
	fmt.Println(parsed)
	fmt.Println(parsed.Format("2006-01-02 15:04:05.000000000 -0700 MST"))
}
```

**Comment by Abhaykumar1** [comment]
How do we specify the pattern for the values read directly in the struct? I've a struct 

type activity struct {
    ActivityDate  time.Time `json:"activityDate" bson:"activityDate"`
}

I read the data in this struct from MongoDB by using cur.Decode(&act)
and write the response back using the json encoder
json.NewEncoder(w).Encode(activity)
 
Is there a way when we define the struct we can specify the date format?

**Comment by ianlancetaylor** [comment]
As far as I know there is not.

Why does it matter whether a trailing zero is present or not?
