### ISSUE TITLE
access: Trybot access

### ISSUE THREAD

**Issue by dfava** [golang/go#38787]
Would it be possible for me to get Trybot access ("may-start-trybots")?
My Gerrit email address is danielsfava@gmail.com
Thanks, Daniel

Trybot access: https://go-review.googlesource.com/#/admin/groups/1030,members

See https://golang.org/wiki/GerritAccess

**Comment by ALTree** [comment]
Hi,

from the https://golang.org/wiki/GerritAccess page:

> Only ask for access if you're an active member of the community. New contributors should participate in the Gerrit code review process for some time before requesting access.

It looks like you currently have zero contributions (commits) in the Go repository. tybots access is given to people after a period of sustained contributions to the project (in the form of merged commits).

**Comment by mvdan** [comment]
To add to what @ALTree said - it's still very much possible to contribute to Go without trybot access. Others can start them for you, and it happens all the time.

**Comment by andybons** [comment]
@ALTree and @mvdan are correct. Sorry. Please try again once you’ve contributed more.
