### ISSUE TITLE
crypto/tls: add DH Parameters support

### ISSUE THREAD

**Issue by okudayukiko** [golang/go#38788]
### What did you expect to see?
Add DH Paramters support, like nginx `ssl_dhparam`
https://nginx.org/en/docs/http/ngx_http_ssl_module.html
`openssl dhparam 3072`

**Comment by ianlancetaylor** [comment]
CC @FiloSottile

**Comment by FiloSottile** [comment]
We don't support DH key exchanges, in part precisely because of the need for parameters, but mostly because ECDH is always a better choice.

**Comment by okudayukiko** [comment]
> We don't support DH key exchanges, in part precisely because of the need for parameters, but mostly because ECDH is always a better choice.

In our test, Using dhparam will more secure, even use ECDHE key exchange.
