### ISSUE TITLE
x/build: dragonfly-amd64-5_8 does not have SSH configured

### ISSUE THREAD

**Issue by andybons** [golang/go#38796]
This is needed for gomote configurations.

@tuxillo @bcmills

**Comment by tuxillo** [comment]
what's exactly needed?

**Comment by bcmills** [comment]
I'm not sure, but the error message I'm seeing comes from here:
https://github.com/golang/build/blob/7858236789478677d65917de2425af562568774a/cmd/coordinator/remote.go#L650-L663

**Comment by bcmills** [comment]
It appears to need SSH public-key authentication for some user (typically either `gopher` or `root`), with the username configured in `golang.org/x/build/dashboard/builders.go`. I assume @andybons can get you the public key.

**Comment by bcmills** [comment]
Or, if you'd prefer to diagnose #38797 yourself, that would work too. 😉

**Comment by tuxillo** [comment]
If you provide the public key I can add it to the root user.

**Comment by andybons** [comment]
@tuxillo is there a builder key present on the host per step 1 of https://github.com/golang/go/wiki/DashboardBuilders#how-to-set-up-a-builder ? (don’t paste it here)

**Comment by tuxillo** [comment]
Yes, sure. Otherwise it would not even connect as far as I can tell:

```
# ls -l ~/.gobuildkey-host-dragonfly-amd64-5_8
-rw-r--r--  1 root  wheel  33 Apr 14 16:37 /root/.gobuildkey-host-dragonfly-amd64-5_8
```

**Comment by dmitshur** [comment]
> what's exactly needed?

The host config for the `dragonfly-amd64-5_8` builder has the empty string value for the [`SSHUsername`](https://github.com/golang/build/blob/916311cec4e1738aae572fe49767cebdc0351144/dashboard/builders.go#L726) field in the golang.org/x/build/dashboard package:

https://github.com/golang/build/blob/916311cec4e1738aae572fe49767cebdc0351144/dashboard/builders.go#L363-L369

The empty string means "disable SSH access on this builder".

It needs to be set to a non-empty value, then coordinator needs to be redeployed.

**Comment by dmitshur** [comment]
@tuxillo Could you please send a CL that updates the `SSHUsername` field in the x/build/dashboard package and add me as a reviewer? Thank you.

/cc @bradfitz Do you know if there are any tasks to do on the side of the reverse builder (by the builder owner) when enabling SSH access?

**Comment by bradfitz** [comment]
The buildlet binary is responsible for editing the authorized_keys file on the host. Finding the path to the appropriate file has needed some tweaks for different OSes over time. It's likely to work automatically on DragonFly at this point but if not, that's the place to look.

**Comment by dmitshur** [comment]
Thanks Brad.

@tuxillo If it's helpful to you, I can create the CL and make you a reviewer, but you'll need to tell me what username I should specify for your builder. Let me know how you'd like to proceed. Thanks.

**Comment by bradfitz** [comment]
IIRC it needs to be the user that runs the builder. The main reason it's not automatic is that some builder owners don't want to permit SSH into their network.

**Comment by tuxillo** [comment]
The DragonFly builders run in VMs so the user will be `root`.

@dmitshur I'll create the PR.

**Comment by tuxillo** [comment]
Let me know if anything else is needed on my side.

**Comment by dmitshur** [comment]
Will do. Re-opening to track coordinator deployment.

**Comment by dmitshur** [comment]
Coordinator is re-deployed, and I've verified that it's possible to ssh into a `dragonfly-amd64-5_8` gomote instance now. /cc @bcmills
