### ISSUE TITLE
doc: include fix for #34437 in Go 1.14 release notes

### ISSUE THREAD

**Issue by theckman** [golang/go#38801]
Hello,

I wanted to reach out and see whether there is an interest in the fix for #34437 being included in the Go release notes. Someone I know was finally working through upgrading to Go 1.14 and ran in to some peculiar issues with their JSON being unmarshaled differently. Here is that commit on our side:

- https://github.com/golang/go/commit/fb9af8411eaa3e38d2f72e28a305772f50042657#diff-4299c3082a8bb7e546723132c992fa4c

It took them some time to figure it out, while it having been mentioned in the release notes could have saved them some time (as they looked there first). I understand we can't document all fixes without the release notes becoming silly, but wondered whether that change may meet the bar of inclusion.

Cheers!

**Comment by dylan-bourque** [comment]
I am @theckman 's "someone I know" and this issue cost me several hours today.  We had a test that was failing for me locally using Go 1.14.2 but passing for others and in all of our CI pipelines.  After quite a bit of investigation and experimentation I was able to determine that the failure was specific to Go 1.14+.

Admittedly, this particular test was using bad/invalid test data (an invalid enum value in a JSON test data file for an enum that implements `encoding/json.TextUnmarshaler`).  That being said, I checked the 1.14 release notes first and was not able to find any mention of this change in behavior so I (and several coworkers) continued to dig for clues about why this test was failing now.

**Comment by mvdan** [comment]
A somewhat similar issue was https://github.com/golang/go/issues/37308, though it was filed before the final release and the notes were published.

> I understand we can't document all fixes without the release notes becoming silly, but wondered whether that change may meet the bar of inclusion.

Like in the other case, this is a bugfix to make the behavior follow the docs more closely. I don't oppose adding this to the release notes, but I'm not sure if it's normal for them to be updated this late, or if we can consider it important enough given that it hasn't raised any other flags since the pre-releases or final release over two months ago.

I'd definitely be in favor of tweaking the release notes if this discussion took place during the beta or release candidate, though.

**Comment by theckman** [comment]
@mvdan people will be upgrading to 1.14+ for a long while still. What harm is there in adding this now?

**Comment by ianlancetaylor** [comment]
I don't know anything about this particular issue but I think it's fine to update the release notes after the release has gone out.  We've done it before.

**Comment by dmitshur** [comment]
As Ian mentioned, it shouldn't be an issue to update the release notes after the release. We don't want to do it too often and too much after a release as that adds noise, but there haven't been too many request to add missing things to Go 1.14 release notes as far as I know.

Changes to the behavior of the `encoding/json` package seem like something that's helpful to include to me, and there will be more people updating to Go 1.14 over time, so I'm in favor of doing it.

@mvdan, you're one of `encoding/json` owners, so if you're okay with it, feel free to move this issue to NeedsFix state.

/cc @cuonglm who worked on the CL, and @dsnet @bradfitz per [owners](https://dev.golang.org/owners).

**Comment by cuonglm** [comment]
👍 for updating 1.14.x release note

**Comment by mvdan** [comment]
As long as the release team is happy with updating the release notes at this point, I don't have a problem with the change. That's what I tried to say in my previous comment.

**Comment by dmitshur** [comment]
@gopherbot Please open an issue to backport this to Go 1.14 when the fix is available. This is a documentation fix.
