### ISSUE TITLE
pkg.go.dev: totally wrong README shown

### ISSUE THREAD

**Issue by hugelgupf** [golang/go#38804]
### What did you do?

went to https://pkg.go.dev/github.com/u-root/u-root?tab=overview

### What did you expect to see?

readme from https://github.com/u-root/u-root/blob/master/README.md

### What did you see instead?

readme from https://github.com/u-root/u-root/blob/master/.circleci/images/README.md

**Comment by julieqiu** [comment]
Thanks for reporting! This should be fixed. The readme at https://github.com/u-root/u-root/blob/v6.0.0/README.md is now shown.
