### ISSUE TITLE
Plan to add cryptography ISO/ IEC 10118-3:2018 algorithm support?

### ISSUE THREAD

**Issue by itlabers** [golang/go#38811]
The sm2/3/9 cryptographic algorithm is officially an ISO/IEC international standard

**Comment by ianlancetaylor** [comment]
CC @FiloSottile

**Comment by FiloSottile** [comment]
Standardization is not the bar for inclusion in the Go standard libraries. You can read more about what we aim for at https://golang.org/design/cryptography-principles
