### ISSUE TITLE
riscv64: LR saved before SP update

### ISSUE THREAD

**Issue by embeddedgo** [golang/go#38828]
go version go1.14.2 linux/amd64

The source below

```go
package main

func abcd(a *uint32, b uint32) {
	*a += b	
}

var a uint32

func main() {
	abcd(&a, 3)
}
```

compiled on AMD64 with

```
GOARCH=riscv64 go build -gcflags '-l'
```

generates the following assemble for main.main

```
000000000007ae28 <main.main>:
   7ae28:       01023503                ld      a0,16(tp) # 10 <internal/cpu.processOptions-0x10ff0>
   7ae2c:       00256863                bltu    a0,sp,7ae3c <main.main+0x14>
   7ae30:       ffffbf97                auipc   t6,0xffffb
   7ae34:       028f82e7                jalr    t0,40(t6) # 75e58 <runtime.morestack_noctxt>
   7ae38:       ff1ff06f                j       7ae28 <main.main>
   7ae3c:       fe113423                sd      ra,-24(sp)
   7ae40:       fe810113                addi    sp,sp,-24
   7ae44:       000a0197                auipc   gp,0xa0
   7ae48:       9f418193                addi    gp,gp,-1548 # 11a838 <main.a>
   7ae4c:       00313423                sd      gp,8(sp)
   7ae50:       0030019b                addiw   gp,zero,3
   7ae54:       00312823                sw      gp,16(sp)
   7ae58:       00000f97                auipc   t6,0x0
   7ae5c:       fb8f80e7                jalr    -72(t6) # 7ae10 <main.abcd>
   7ae60:       00013083                ld      ra,0(sp)
   7ae64:       01810113                addi    sp,sp,24
   7ae68:       00008067                ret
```

The problem is with the frame allocation sequence

```
sd      ra,-24(sp)
addi    sp,sp,-24
```

As you can see the `ra` (link-register) is saved **before** allocate memory on the stack.

This is perhaps not a problem in case of typical goroutine stack because probably nothing use it concurrently with the goroutine. I'm unsure about typical OS environment (maybe it can interfere with signal handling) but it's serious bug in case of bare metal programming.

I'm working on noos/riscv64 port. If a trap occur between `sd  ra,-24(sp)` and `addi sp,sp,-24` the trap handler can clobber `ra` on the stack if it use the same stack.

I think the proper sequence should be

```
addi    sp,sp,-24
sd      ra,0(sp)
```

that is, *allocate before use*.

I  can probably try fix it myself but first I want ask the riscv64 maintainer about it. Is there something special I'am not aware?

**Comment by cherrymui** [comment]
We intentionally save LR before allocating the frame. If we update SP first without saving LR, if we get a signal right after this instruction, we'll have wrong return address in the frame and stack unwinding will fail. We do this on all other LR architectures as well.

On Linux, Go uses alternate signal stack, and nothing is expected to write below SP. On platforms where we cannot use  alternate signal stack (e.g. iOS), we save LR, update SP, and save LR again, to make it signal safe. You'll probably need to do something similar if your platform could write below SP (or, better try to avoid it, if possible).

**Comment by embeddedgo** [comment]
> On platforms where we cannot use alternate signal stack (e.g. iOS), we save LR, update SP, and save LR again, to make it signal safe.

It seems the frame allocation need to be done depending on the target platform. I will make the appropriate changes to my branch.

Thanks!
