### ISSUE TITLE
go.1.14.2.windows-386 detected by Microsoft as having trojans Wacatac & Blueteal

### ISSUE THREAD

**Issue by learncdo** [golang/go#38821]
### What version of Go are you using (`go version`)?

<pre>
1.14.2
</pre>

### Does this issue reproduce with the latest release?
Yes.  When this has happened, with previous versions of Go, it's always been a false positive.  But maybe still worth investigating.  If a false positive, it would make sense to raise the issue with Microsoft.

### What operating system and processor architecture are you using ?
Windows 386

</pre></details>
![go-detected-as-trojan](https://user-images.githubusercontent.com/63755439/80896187-b5255480-8ca0-11ea-9fab-8cf3b0aad69a.jpg)

### What did you do?
Download 1.14.2.  Run Microsoft Security Essentials.  See .msi file flagged

**Comment by ALTree** [comment]
It certainly is a false positive. We can't keep track of all the antivirus false positives, so we usually ask the user to report the mistake to their antivirus vendor, if they care (see https://golang.org/doc/faq#virus).

I'm closing this issue, since this is a known issue.
