### ISSUE TITLE
can `url.ParseQuery` parse respond content from a form include array inputs or ajax complex array/json

### ISSUE THREAD

**Issue by conero** [golang/go#38823]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.14.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\11066\AppData\Local\go-build
set GOENV=C:\Users\11066\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=*.corp.example.com
set GONOSUMDB=*.corp.example.com
set GOOS=windows
set GOPATH=~\go
set GOPRIVATE=*.corp.example.com
set GOPROXY=https://goproxy.io,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=~\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=~\go-build745412882=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

_A example code like that:_
```go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/url"
	"strings"
)

func main() {
	//m, err := url.ParseQuery(`x=1&y=2&y=3;z`)
	m, err := url.ParseQuery(`router_id=1&role_list[0]=1&role_list[1]=2`)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(toJSON(m))
}

func toJSON(m interface{}) string {
	js, err := json.Marshal(m)
	if err != nil {
		log.Fatal(err)
	}
	return strings.ReplaceAll(string(js), ",", ", ")
}
```

_The case like:_
![20200503140514](https://user-images.githubusercontent.com/19564821/80907184-36372700-8d47-11ea-854e-f9197ae4f861.png)

### What did you expect to see?
`url.ParseQuery` parse array/map llike `router_id=1&role_list[0]=1&role_list[1]=2`

**Comment by networkimprov** [comment]
What was the output of your program above, and what output did you expect?

**Comment by conero** [comment]
I am so sorray that the question is not clear, finally I figure out it.
