### ISSUE TITLE
runtime: increase in memory usage and different GC behavior upgrading from 1.13.10 to 1.14.2

### ISSUE THREAD

**Issue by BorisKozo** [golang/go#38827]
Note that I read carefully through #37927 and #35112 but it seems those issues were handled already.

### What version of Go are you using (`go version`)?

Upgrade 1.13.10 -> 1.14.2

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

Windows 10 (reproduces on other Windows versions as well)

### What did you do?

Run my application memory benchmark

### What did you expect to see?

Same or better results as in 1.13.10

### What did you see instead?

Worse results

I have to add that our application is resource critical so every increase in memory or CPU usage raises eyebrows immediately.

I compiled our application with both GO 1.13.10 and 1.14.2 and the CPU and memory behavior are inconsistent between the two versions as the later consumes more memory (enough to trigger the benchmark failure). The behavior of the memory release is also different (see charts below) as there is no visible de-allocation of memory in 1.14.2. 
I also tried changing the GOGC to various values but even at 10 the memory did not reach the behavior of 1.13.10 and CPU usage was considerable

![go_13_GC_100](https://user-images.githubusercontent.com/1912858/80911206-a476ec00-8d3d-11ea-8b1f-ef06e4e7422c.png)

Initial run compiled with GO 1.13.10

Same code was compiled and run on the same machine with GOGC values as follows:
![go_14_GC_10](https://user-images.githubusercontent.com/1912858/80911222-c53f4180-8d3d-11ea-9bfe-896cb7441559.png)

GOGC = 10

![go_14_GC_50](https://user-images.githubusercontent.com/1912858/80911227-cb352280-8d3d-11ea-9922-72b017d10be2.png)

GOGC = 50

![go_14_GC_100](https://user-images.githubusercontent.com/1912858/80911234-d12b0380-8d3d-11ea-8896-85c726587e97.png)

GOGC = 100

![go_14_GC_200](https://user-images.githubusercontent.com/1912858/80911244-dbe59880-8d3d-11ea-8b51-ea314f3bdf70.png)

GOGC = 200

![go_14_GC_500](https://user-images.githubusercontent.com/1912858/80911249-e1db7980-8d3d-11ea-83a0-79002dfd5006.png)

GOGC = 500

in Issue #37525  @mknyszek mentions that another issue will be opened but I could not find the new issue.

Thanks.

**Comment by agnivade** [comment]
Would you be able to share the output of setting `GODEBUG=gctrace=1,gcpacertrace=1` in 1.13.10 vs 1.14.2 ? That would help us a lot in the investigation. Thanks ?

@aclements @mknyszek

**Comment by BorisKozo** [comment]
Hi, I generated the traces:
1.13.10
[trace_1_13_10.txt](https://github.com/golang/go/files/4570312/trace_1_13_10.txt)

and
1.14.2
[trace_1_14_2.txt](https://github.com/golang/go/files/4570316/trace_1_14_2.txt)


Look at the chart for 1.14.2, doesn't appear to be releasing anything and I am running with GOGC=100

![2020-05-03_1554](https://user-images.githubusercontent.com/1912858/80914798-bdd86200-8d56-11ea-8bd3-d0d722e8e2b8.png)

**Comment by mknyszek** [comment]
Regarding memory release, #38617 brought our attention to a bug on Windows where in Go 1.14 the background scavenger wasn't running at all (the synchronous/eager scavenger and debug.FreeOSMemory should still work though). It's not clear to me yet that this is exactly the same problem, but try patching Go with https://golang.org/cl/229997 and see if it helps. Based on the traces you provided, I could see it helping.

Even with that patch, you may not be seeing the same log as in Go 1.13.10 with `GODEBUG=gctrace=1` because we moved the scavenge trace under its own flag, which prints once per GC cycle. The flag for Go 1.14+ is `GODEBUG=scavtrace=1`.

**Comment by networkimprov** [comment]
@gopherbot add OS-Windows

**Comment by BorisKozo** [comment]
@mknyszek I compiled master at https://github.com/golang/go/commit/a1ffbe9c69c716c597f74bd281ca9166e0d54ff5 
and it seems the problem has been resolved.
![go_14_fix](https://user-images.githubusercontent.com/1912858/81001659-c0b77d80-8e50-11ea-803e-a86dd014d9ba.png)


Thank you very much!
Which release is this fix planned to?

**Comment by networkimprov** [comment]
I posted a backport request. If there's no intervening security update, it will land in 1.14.3.

**Comment by BorisKozo** [comment]
Thank you
