### ISSUE TITLE
x/playground: ip 152.32.128.0/24 from HK region is blocked

### ISSUE THREAD

**Issue by shiayoung** [golang/go#38822]
When i access url https://play.golang.org/p/sdHPDx64aor, i get the follow error:

> Unavailable For Legal Reasons
> Viewing and/or sharing code snippets is not available in your country for legal reasons. This message might also appear if your country is misdetected. If you believe this is an error, please file an issue.

Please release these ip sets, thanks!

**Comment by ALTree** [comment]
```
func allowShare(r *http.Request) bool {
	if r.Header.Get("X-AppEngine-Country") == "CN" {
		return false
	}
	return true
}
```

`HK` is not there (only `CN`), so I guess it may be a bad IP-region association indeed. geolocation issues are usually assigned to @broady I believe.

**Comment by shiayoung** [comment]
@broady Please help!

**Comment by kaiterramike** [comment]
Hello from China! Looks like you're blocking some IPs from Japan too, in this block: 50.7.159.0/24

**Comment by shiayoung** [comment]
> Hello from China! Looks like you're blocking some IPs from Japan too, in this block: 50.7.159.0/24

May be blocked by the proxy server provider.

**Comment by smartfly** [comment]
me too. how to solve this problem。

https://play.golang.org/p/TOCPfm34I5p chrome note：

Unavailable For Legal Reasons
Viewing and/or sharing code snippets is not available in your country for legal reasons. This message might also appear if your country is misdetected. If you believe this is an error, please file an issue.
