### ISSUE TITLE
go upgrade

### ISSUE THREAD

**Issue by Matteoserafini-lab** [golang/go#38835]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.13

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env pop os 20.04  amd64

</pre></details>

### What did you do?

```
matgab@pop-os:~$ go get golang.org/dl/go1.14.2
matgab@pop-os:~$ go1.14.2 download
go1.14.2: command not found
matgab@pop-os:~$ 
```

### What did you expect to see?
downloading

### What did you see instead?
go1.14.2: command not found

**Comment by bcmills** [comment]
> `$ go env pop os 20.04  amd64`

That is not the output produced by the `go` command that comes with the Go toolchain. Perhaps your OS is providing some other `go` command?

Otherwise, you need to make sure that the install location for `go get` (either `$GOPATH/bin` or `$GOBIN`) is in your shell's `PATH` environment variable.
