### ISSUE TITLE
os: investigate why Stat(non-existent-file) on Windows with builders returns error prefixed with "CreateFile"

### ISSUE THREAD

**Issue by odeke-em** [golang/go#38841]
Coming here from an unexpected trybot failure in https://storage.googleapis.com/go-build-log/ee4c7a10/windows-amd64-2016_e7a90c70.log
and CL [230941](https://go-review.googlesource.com/c/go/+/230941/3#message-fde71f88c105af21fbd4ba6c4ab172203da96517)

where the relevant code is https://play.golang.org/p/El2eXIywXlu or inlined below
```go
package main

import (
	"log"
	"os"
	"strings"
)

func main() {
	got := "open x.go: no such file or directory\n"
	_, sysNotExistErr := os.Stat("x.go")
	if sysNotExistErr == nil {
		// Oddly the file might exist, do nothing and just report the original failure.
		log.Fatalf("Expected an error %q\n", got)
	}

	want := strings.Replace(sysNotExistErr.Error(), "stat x.go:", "open x.go:", -1) + "\n"
	if got != want {
		log.Fatalf("Expected an error, but got:\n\t%q\nwant:\n\t%q", got, want)
	}
}
```
but oddly on the Windows builder it returned
```shell
# go run run.go -- fixedbugs/issue36437.go
incorrect output
Expected an error, but got:
	"open x.go: The system cannot find the file specified.\n"
want:
	"CreateFile x.go: The system cannot find the file specified."
```

The "CreateFile x.go" is quite unexpected. Perhaps we should investigate as to how "CreateFile" got invoked?

Kindly cc-ing @alexbrainman.

**Comment by muhammadharis** [comment]
It seems that the error that is being returned is from line 83 of `stat_windows.go`.

**Comment by networkimprov** [comment]
CreateFile is the WinApi name for Posix open(2). It only creates filesystem entries in certain cases.

Why is the fix for #36437 examining the error string instead of `if !os.IsNotExist(err)`?

**Comment by iWdGo** [comment]
On Windows, `os.Stat` attempts several calls to cope with various file types. Some details on the rationale are [here](https://github.com/golang/go/issues/19922).
The following could help to check error message content.

```
if !os.IsNotExist(sysNotExistErr) {
	log.Fatalf("Expected a not exist error")
}

s := "x.go:0"
if n := strings.LastIndex(sysNotExistErr.Error(), s); n != -1 {
	log.Fatalf("Line number is unexpected: %s", sysNotExistErr.Error()[n:len(s)])
}
```

For the records, no index number shows on Windows 10 and `go version go1.14.2 windows/amd64` and `os.Stat` returns `...CreateFile x.go: The system cannot find the file specified.`

**Comment by alexbrainman** [comment]
> CreateFile is the WinApi name for Posix open(2). It only creates filesystem entries in certain cases.

Correct. `CreateFile` Windows API is generally used to open files

https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea

There is no `open` syscall on Windows. It will be confusing, if we just blindly replace `CreateFile` with `open` string. For example, the errors you see relate directly to `CreateFile` API, and have different meaning when returned for different APIs.

Alex

**Comment by odeke-em** [comment]
Got it, thank you @muhammadharis @networkimprov @iWdGo @alexbrainman for the answers! SGTM.
