### ISSUE TITLE
Incorrect handling of literal -0.0

### ISSUE THREAD

**Issue by kstenerud** [golang/go#38842]
### What version of Go are you using (`go version`)?

Latest. See playground: https://play.golang.org/p/M0iIlaKMKfY

### What did you do?

https://play.golang.org/p/M0iIlaKMKfY

```golang
package main

import (
	"fmt"
	"math"
)

func main() {
	v1 := math.Float64frombits(0x8000000000000000)
	v2 := -0.0
	v3 := -(0.0)
	v4 := 0.0
	v4 = -v4
	fmt.Printf("%v\n", v1)
	fmt.Printf("%v\n", v2)
	fmt.Printf("%v\n", v3)
	fmt.Printf("%v\n", v4)
}
```

### What did you expect to see?

```
-0
-0
-0
-0
```

### What did you see instead?

```
-0
0
0
-0
```

**Comment by randall77** [comment]
This is intentional, and how [constant expressions](https://golang.org/ref/spec#Constant_expressions) work.

> Constant expressions are always evaluated exactly; intermediate values and the constants themselves may require precision significantly larger than supported by any predeclared type in the language.

In particular, there is no constant `-0`. That's a float64-ism. Once you have a float64 *variable*, then you're in IEEE-754 land.

**Comment by kstenerud** [comment]
But this puts go at odds with all other languages. If you have to keep remembering that the negative sign is effectively ignored in some situations in go, won't this added cognitive load lead to subtle bugs?

Isn't the point of go to make it harder to write buggy code?

**Comment by randall77** [comment]
There's a tradeoff. For instance, in Go you can write `(1<<64)/10` and get a reasonable answer. In C you cannot.
I agree that generating a floating-point `-0` is more challenging in Go. That seems like a reasonable tradeoff to me. How many people need a `-0`?

You may want to read through https://blog.golang.org/constants
