### ISSUE TITLE
when ruuning gomobile bind -target ios  , facing following error,,,,,  go build -tags ios -buildmode=c-archive -o /var/folders/k7/h5trb9cj6qsgfg03bhjjqh780000gn/T/gomobile-work-016455997/fcgoclient-arm.a ./gobind failed: exit status 2

### ISSUE THREAD

**Issue by Prabhudev-kannadoss** [golang/go#38846]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by Prabhudev-kannadoss** [comment]
Installed dependencies:
1. go version:  go1.14 darwin/amd64

2. dep information:
version  : v0.5.4
build date : 2019-09-29
git hash : 1f7c19e
go version : go1.13
go compiler : gc
platform : darwin/amd64
features : ImportDuringSolve=false

3.gomobile version : 
gomobile version +4c31acb Sun Mar 29 12:56:38 2020 +0000 (android,ios); androidSDK=

4.protoc version : 
libprotoc 3.7.1

**Comment by dmitshur** [comment]
Can you please provide answers to the questions in the issue template. Specifically, "what did you do", "what did you expect to see", "what did you see instead". Thanks.
