### ISSUE TITLE
x/tools/gopls: wrong package expected

### ISSUE THREAD

**Issue by atombender** [golang/go#38866]
#### What did you do?
I had some test files (no errors) in a folder named `security` which erroneously all had `package namespaces` at the top. I changed these to `package security` to fit the folder name.

#### What did you expect to see?

No error.

#### What did you see instead?

After this, gopls complains that the line `package security` is wrong, with:

```
package namespaces; expected security
```

Restarting gopls is the only way to get rid of the error.

#### Log

[gopls.log](https://github.com/golang/go/files/4578790/gopls.log)

#### Build info

```
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.0.0-20200501005904-d351ea090f9b h1:CAqIXUMd9mH3t2O1DRj2IWu0Zh75A4fWPA+YjJOmXdE=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.2.0 h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
    golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=
    golang.org/x/tools@v0.0.0-20200430221153-f26c0dd9827d h1:8emZwJTManptbFnp36i5fbhO/1vUs3rfnh5e3Th8HEQ=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=
```

#### Go info

```
go version go1.14 darwin/amd64

```

**Comment by stamblerre** [comment]
I expect that this has been fixed in Go 1.16 with #41598. Please create a new issue if you encounter problems when switching package names in the future.
