### ISSUE TITLE
x/tools/gopls: stops working after changing branches

### ISSUE THREAD

**Issue by atombender** [golang/go#38878]
#### Description
Edited code in a single file. Gopls suddenly stopped reporting any errors. I could not get gopls to function again, and had to reload. Unfortunately, I could not reproduce the problem even when I went through the same editing steps that I remembered.

[gopls.log](https://github.com/golang/go/files/4581914/gopls.log). Note: Scrubbed of `textDocument/didOpen` notifications, as this is a private repo.

#### Build info

```
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.0.0-20200501005904-d351ea090f9b h1:CAqIXUMd9mH3t2O1DRj2IWu0Zh75A4fWPA+YjJOmXdE=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.2.0 h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
    golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=
    golang.org/x/tools@v0.0.0-20200430221153-f26c0dd9827d h1:8emZwJTManptbFnp36i5fbhO/1vUs3rfnh5e3Th8HEQ=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=
```

#### Go info

```
go version go1.14 darwin/amd64

```

**Comment by stamblerre** [comment]
From what I can tell in your log, it looks like you switched branches, which caused `gopls` to reload a lot of packages by their package path. My guess is that the files in the `github.com/sanity-io/gradient/pkg/security` test package did not exist on the original branch, and they were treated like file creations, resulting in https://github.com/golang/go/issues/38423. See the error message:

```
 [Error - 11:36:31 AM] 2020/05/05 11:36:31
	message="failed to load workspace packages, skipping diagnostics"
	error=github.com/sanity-io/gradient/pkg/security [github.com/sanity-io/gradient/pkg/security.test] has no metadata
	snapshot=241
	directory=file:///Users/alex/Projects/Sanity/gradient
```

`gopls` then appeared to be stuck because no new diagnostics were not being propagated.

**Comment by atombender** [comment]
Ah, that's possible. I wasn't switching branches, though; I was rebasing, which I guess can trigger the same problem.

**Comment by heschik** [comment]
The test that supposedly repros this problem is enabled -- do we think the bug is fixed?

**Comment by stamblerre** [comment]
Yeah, I think at this point enough things have changed that bugs in watching files will appear in different ways than this case.
