### ISSUE TITLE
freeze exception: net/http/cgi: reject invalid header names

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#38889]
While working on CL 231419, I noticed we trim spaces around the names of the headers generated by CGI programs. This is not as serious as #34540 because the CGI program output is presumably trusted, but CGI is such a generic interface that I'd feel better if we didn't do anything potentially risky like that.

I'd like to request a freeze exception to land [CL 232277](https://golang.org/cl/232277) this week.

/cc @andybons @rsc

**Comment by andybons** [comment]
I think this is OK as it’s small and security related. Will wait for @rsc to confirm.

**Comment by rsc** [comment]
SGTM, thanks.
