### ISSUE TITLE
Fix the spec for slice expressions

### ISSUE THREAD

**Issue by kedarmhaswade** [golang/go#38894]
### What version of Go are you using (`go version`)?
It's the version of spec that applies here: I am looking at the [**Version of Jan 14, 2020**](https://golang.org/ref/spec).

<pre>
$ go version -- does not matter
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
Does not matter

</pre></details>

### What did you do?
Checked the spec for slice expressions for a string.

### What did you expect to see?

See below.

### What did you see instead?
See https://golang.org/ref/spec#Slice_expressions which says:

> constructs a substring or slice. The indices low and high select which elements of operand a appear in the result. The result has indices starting at **0** and length equal to high - low. After slicing the array a ...

I expect to see:

> constructs a substring or slice. The indices low and high select which elements of operand a appear in the result. The result has indices starting at **`low`** and length equal to high - low. After slicing the array a ...

Unfortunately, the spec also fails to clarify what should happen in a substring or a subslice operation when `low` equals the length of the string or slice as returned from the `len` builtin function. Since `low` is expected to be the inclusive index, I thought `s[len(s):]` may cause panic (although, since `high` defaults to `len(s)`, `high-low` equals `len(s)-len(s) = 0`), but apparently it either returns an empty string or an empty slice in some go implementations that I have tried. In either case, spec should clarify this.

**Comment by ianlancetaylor** [comment]
The existing text is correct.  The result of a slice expression is itself a slice.  That new slice, the result, has indices starting at `0` and length equal to `high - low`.

I think the spec is clear that `s[len(s):]` returns a slice with zero elements (or in the case of a slice of a string it returns the empty string).  As you say, in that case `high - low` is `0`, so you get a slice with length `0`.

**Comment by kedarmhaswade** [comment]
Understood. I think the subsequent statement `For arrays or strings, the indices are in range if 0 <= low <= high <= len(a)` states it more clearly than what precedes it. I missed that statement. In hindsight, maybe the spec should describe strings separately from arrays and slices, just like https://golang.org/ref/spec#Index_expressions does. A mild annoyance is that with `str` that represents a string value, an index `len(str)` is out of range, whereas a substring/slice expression `len(str):` is not!
