### ISSUE TITLE
x/pkgsite: slower loads than godoc.org

### ISSUE THREAD

**Issue by crawshaw** [golang/go#38892]
Comparing two package doc page loads in Chrome's network inspector. Caching disabled, from Sydney Australia. Best of several loads:

https://godoc.org/net/http
```
8 requests
162 kB transferred
515 kB resources
Finish: 1.36 s
DOMContentLoaded: 1.21 s
Load: 1.23 s
```

https://pkg.go.dev/net/http

```
18 requests
163 kB transferred
388 kB resources
Finish: 2.05 s
DOMContentLoaded: 1.59 s
Load: 1.68 s
```

The total transferred content is roughly the same, but time to DOMContentLoad and final Load is significantly longer. The qualitative result is pkg.go.dev feels like the slow option.

**Comment by julieqiu** [comment]
Thanks for the feedback, @crawshaw! We'll work on making this experience better.

**Comment by wxolp** [comment]
An alternative is the GoDocs site, which seems to be at least twice as fast at the numbers you gave:

https://godocs.io/net/http

~~~
5 requests
104 KB transferred
334 KB resources
Finish: 615 ms
DOMContentLoaded: 563 ms
Load: 565 ms
~~~
