### ISSUE TITLE
Unintuitive pointer type definition behavior

### ISSUE THREAD

**Issue by JohnReedLOL** [golang/go#38890]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 darwin/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/john-michaelreed/Library/Caches/go-build"
GOENV="/Users/john-michaelreed/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/john-michaelreed/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/john-michaelreed/sdk/go1.14.2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/john-michaelreed/sdk/go1.14.2/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/np/j2pvl5cd1mj8gkh66ml36j3m0000gn/T/go-build797644004=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Pointer type definitions (ex. `type SPtrType *S`) behave the same as pointer type aliases (ex. `type SPtrType = *S`), but the definitions produce different types while the aliases produce the same type.

In the below image (click to enlarge) there is automatic conversion between types `*main.S` and `main.SPtrType` despite the fact that they are two different types at runtime:

![Unintuitive pointer type definition behavior](https://i.ibb.co/mSS5yjc/Screen-Shot-2020-05-05-at-7-13-58-PM.png)

This is the same program, but with a type alias `type SPtrType = *S`  instead of type definition `type SPtrType *S`:
![Pointer type aliases](https://i.ibb.co/bLXYgMv/Screen-Shot-2020-05-05-at-9-46-54-PM.png)

Type definitions aren't supposed to behave exactly the same as type aliases.

### What did you expect to see?

In the first screenshot, I expected that `*main.S` and `main.SPtrType` would behave like two different types. Without casting, I expected a compile error when passing a variable of type `*main.S` in place of a `main.SPtrType`.

### What did you see instead?

I see pointer type definitions behaving the same as pointer type aliases. 

Like imagine that you had type definition `type SType S` and then you had one variable of type `S` and another variable of type `SType`. You couldn't pass in an `S` in place of an `SType`. But if you had type definition `type STypePtr *S` and then you had one variable of type `*S` and another variable of type `SPtrType`, you could pass in a `*S` in place of a `SPtrType` as if they were the exact same type. This is unintuitive.

**Comment by go101** [comment]
@JohnReedLOL You can post code between two ``` lines to get better readibility.

**Comment by ianlancetaylor** [comment]
Yes, please post your code as text inside ``` or as links to play.golang.org, not as screenshots.  Thanks.

**Comment by ianlancetaylor** [comment]
The different behavior between `type Stype S` and `type StypePtr *S` is as described at https://golang.org/ref/spec#Assignability.  The key point is that `S` is a defined type and `*S` is not.

This is basically a question about how the language works.  We don't use the issue tracker for questions.  Please ask questions in a forum instead.  See https://golang.org/wiki/Questions.  Thanks.

**Comment by JohnReedLOL** [comment]
@ianlancetaylor Oh, I see. `S` is a defined type but `struct {}` is not a defined type, just like `SPtrType` is a defined type but `*S` is not a defined type. The reason you can't assign an `S` to an `SType` is because both of them are defined types. I understand.
