### ISSUE TITLE
error when downloading the mysql driver

### ISSUE THREAD

**Issue by aditya-09** [golang/go#38911]
### Does anyone know how to resolve errors when downloading the mysql driver like this?

<pre>
$ go: inconsistent vendoring in C:\Go\src:
        github.com/go-sql-driver/mysql@v1.5.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt

run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory

</pre>

**Comment by toothrot** [comment]
For asking questions about learning the language, see one of our forums: https://golang.org/wiki/Questions. We only use this issue tracker for tracking bugs. People in the forums can explain what is happening here.

**Comment by aditya-09** [comment]
okey thanks...
