### ISSUE TITLE
x/tools/gopls: forgets/complains about unchanged types/code 

### ISSUE THREAD

**Issue by bmhatfield** [golang/go#38924]
### What version of Go are you using (`go version`)?

<pre>
% go version
go version go1.14.2 darwin/amd64
</pre>

Notably, I update `gopls` manually very regularly. I am running from a `go install` from current master: `a1532b81`. This issue affects (possibly many) previous commits as well (it was not introduced in `a1532b81`).

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOOS="darwin"
</pre></details>

### What did you do?
This reproduces frequently, but not reliably enough to come up with a process.

In general, I have a large-ish codebase. While changing code (_unrelated_ code to what breaks), I frequently will see various other directories highlight red in VSCode.

Some things that I am _not_ doing might be relevant here:
- I am not changing branches/rebasing/otherwise moving files around.
- I am not editing code that should directly affect the code that starts breaking

### What did you expect to see?

I expect only actual compilation/code errors to be displayed as errors.

### What did you see instead?

Looking at the errors, I see stuff like:

<img width="452" alt="Screen Shot 2020-05-07 at 1 31 52 PM" src="https://user-images.githubusercontent.com/1119967/81330974-defac480-906e-11ea-979d-d56e7a35a00d.png">

and

<img width="822" alt="Screen Shot 2020-05-07 at 12 35 41 PM" src="https://user-images.githubusercontent.com/1119967/81330995-e6ba6900-906e-11ea-9aa4-c84927989201.png">

Neither error is valid. Neither error is related to changed code. The second error in particular is _clearly_ not valid, as the error itself is tautologically inconsistent (type `a` cannot be used as type `a`).

Using VSCode's `Go: Restart Language Server` resolves the issue for some period of time, but it tends to come back in minutes-to-hours. One thing I noticed is there does tend to be _some_ consistency to the code it becomes unhappy about - given the same general work, it will start complaining about the same exact (but still unrelated and unchanged) type, in the same file, at the same location.

Happy to gather more information here as appropriate.

**Comment by bmhatfield** [comment]
I caught part of this live again.

A clue:

I have a function definition which exists in file A. That function definition returns a type which exists in a package (P) different than A's package. The import that provides that type to file A is import aliased.

The `*invalid` error occurs in file B, in a separate package from A - it does not import P (aliased or unaliased).

If I open the file (A) with the function definition (and the import alias), both files stop reporting errors. If I close the file with the function definition, both files start reporting errors again.

**Comment by stamblerre** [comment]
Thanks for the detailed report! The second issue you described should be covered by https://github.com/golang/go/issues/38403, which was just resolved. Please upgrade to master and do let us know if you see this issue again.

Regarding the first issue, can you share your logs when you see this happen? Details on how to capture them [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs).

**Comment by bmhatfield** [comment]
Thanks! I've just upgraded, and I will continue watching! What luck that this just got closed, very exciting :-)

**Comment by bmhatfield** [comment]
It's been about a week, and I have not seen this issue since upgrading past the point where #38403 was fixed. Closing this for now, I will file a new issue with as much information as I can capture if it recurs.
