### ISSUE TITLE
x/sys/unix: Gettimeofday broken on Darwin: doesn't set the time.

### ISSUE THREAD

**Issue by wbl** [golang/go#38925]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/watsonladd/Library/Caches/go-build"
GOENV="/Users/watsonladd/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="code.cfops.it,github.com/cloudflare"
GONOSUMDB="code.cfops.it,github.com/cloudflare"
GOOS="darwin"
GOPATH="/Users/watsonladd/go"
GOPRIVATE="code.cfops.it,github.com/cloudflare"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ps/_z7r371n1kdf72n71mlyf28h0000gp/T/go-build470647461=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```
package main

import (
	"fmt"

	"golang.org/x/sys/unix"
)

func main() {
	time := unix.Timeval{}
	err := unix.Gettimeofday(&time)
	if err != nil {
		panic(err)
	}
	fmt.Printf("sec=%d\n", time.Sec)
	fmt.Printf("%+v\n", time)
}
```

### What did you expect to see?
The current time

### What did you see instead?
All zeros

**Comment by ianlancetaylor** [comment]
I imagine that this was broken when the Darwin support was converted to use libc.  Someone probably needs to drop the various `Gettimeofday` implementations in syscall_darwin_CPU.go and just call the libc function.

**Comment by abemotion** [comment]
https://golang.org/src/cmd/vendor/golang.org/x/sys/unix/syscall_darwin_386.go#L27
https://golang.org/src/cmd/vendor/golang.org/x/sys/unix/syscall_darwin_arm.go#L25

These type conversion are wrong in `Gettimeofday`. (comment too)
`gettimeofday` returns `(sec int64, usec int32, err error)`
but sec is converted from int64 to int32.

**Comment by tklauser** [comment]
@wbl thanks for the report. I've sent a fix at https://golang.org/cl/232803 and this works on `darwin/amd64` for me with your code snippet. Does this fix the issue for you as well?

**Comment by wbl** [comment]
I might need some step by step instructions on how to check out the tree and run the newly built tool against my example: not that experienced with gerrit.

@Lekensteyn was the original discoverer of this issue: I just passed it on.

**Comment by tklauser** [comment]
@wbl you should be able to get the CL into your local clone of `golang.org/x/sys` using `git fetch "https://go.googlesource.com/sys" refs/changes/03/232803/2 && git checkout FETCH_HEAD`

**Comment by wbl** [comment]
It worked for me! Thanks for your instructions.
