### ISSUE TITLE
x/tools/gopls: issue with named imports

### ISSUE THREAD

**Issue by stamblerre** [golang/go#38927]
See the repro case here: https://github.com/atombender/gopls-issue-38403.

/cc @atombender

**Comment by heschik** [comment]
I reduced the test case to these two files:

```
package mypkg

func One() {
}
```
```
package mypkg

import net_url "net/url"

func Two() *net_url.URL {
	return nil
}
```

One significant finding: if you save the second file while it's got the error, it actually gets rewritten to `*url.URL`. That strongly hints that the AST is getting messed with, possibly by an analyzer.

**Comment by heschik** [comment]
Commenting out https://cs.opensource.google/go/tools/+/master:internal/lsp/source/types_format.go;drc=b8428586f46299aff9dbc7b128617219c087700f;l=222 fixes the bug. I suspect https://cs.opensource.google/go/tools/+/master:internal/lsp/source/types_format.go;drc=b8428586f46299aff9dbc7b128617219c087700f;l=290 is writing to an un-cloned AST node.

**Comment by heschik** [comment]
https://cs.opensource.google/go/tools/+/master:internal/lsp/source/types_format.go;l=381;drc=b8428586f46299aff9dbc7b128617219c087700f doesn't return the cloned node, so it falls through and returns the original.
