### ISSUE TITLE
x/website: doc typo, bar has 'documents' menu instead of 'documentation'

### ISSUE THREAD

**Issue by itoocode** [golang/go#38930]
The website navigation has 'Documents' menu, please make it as 'Docs' or  'Documentation' 
![image](https://user-images.githubusercontent.com/15245455/81340763-0339be00-90ce-11ea-998d-92ce40dc5b1f.png)

**Comment by ALTree** [comment]
Hi,

documents seems okay to me... I think docs would be misleading because people call "docs" the packages documentation, that is under "Packages".
