### ISSUE TITLE
encoding/json: TextMarshaler type map key is not supported

### ISSUE THREAD

**Issue by AllenX2018** [golang/go#38940]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
</pre></details>

### What did you do?
https://play.golang.org/p/ArLLY9n2uo3

### What did you expect to see?
Output:{"MANUAL__aaa":"bbb"}

### What did you see instead?
Output:{"aaa":"bbb"}

**Comment by mvdan** [comment]
This is on purpose and documented; see https://github.com/golang/go/issues/28827.

**Comment by mvdan** [comment]
Here's the order, as per the docs:

```
- keys of any string type are used directly
- encoding.TextMarshalers are marshaled
- integer keys are converted to strings
```

To force json to use your marshaler, don't let your type be a string type: https://play.golang.org/p/xMmVspIdMMS

You could argue the first two options should be reversed in the order, but I don't think we can change the documented behavior at this point without breaking a good portion of users.
