### ISSUE TITLE
Panic occurred when handle Segmentation fault signal

### ISSUE THREAD

**Issue by coldnight** [golang/go#38944]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Don't konw, we did not tried.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/data/jenkins/workspace/gohere"
GOPROXY=""
GORACE=""
GOROOT="/root/go"
GOTMPDIR=""
GOTOOLDIR="/root/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build208195420=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

This is our online service, and we use `cgo` to invoke our C++ code, recently we find our service crashed something. So,

1. We setted `GOTRACEBACK=crash`
2. `# ulimit -c unlimited`
3. Started the service again to expect another crash

### What did you expect to see?

We want a core file and use gdb to see what happend.

### What did you see instead?

We seen this with gdb and the core file:

```
Core was generated by `xxxxx'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000603e3e in runtime.(*sigctxt).preparePanic (c=0xc001389258, gp=<optimized out>, sig=<optimized out>) at /root/go/src/runtime/signal_linux_amd64.go:20
20              return (*sigcontext)(unsafe.Pointer(&(*ucontext)(c.ctxt).uc_mcontext))
Loading Go Runtime support.
```

I want to know is this normal?

**Comment by agnivade** [comment]
Yes, this is the result of using `unsafe` in your code. Unless you are sure there are no bugs, your code can crash.

If you think there's a bug in Go rather than in your code, please post a short reproducer containing the code that triggers this. But given the fact that there is cgo and unsafe involved, it is unlikely that there is any bug here.

If you use Go 1.14 with `-race`, you can get the benefits of the `-d=checkptr` flag which adds instrumentation to ensure that unsafe rules are followed properly. https://tip.golang.org/doc/go1.14#compiler.

**Comment by coldnight** [comment]
Thanks for your reply, but I want to know how to get the real reason of the crash?

**Comment by agnivade** [comment]
It's a bug in your code, due to which a segmentation fault occurs. That's the real reason. I'm afraid I cannot explain any better than this.

**Comment by coldnight** [comment]
OK, I expect an crash detail of my code in core dump, but currently I only got a signal handle panic.
