### ISSUE TITLE
Unable to build in i386 HP mini-laptop machine

### ISSUE THREAD

**Issue by byteshiva** [golang/go#38948]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 linux/386

uname -a 
Linux siva-HP-Mini-110-1100 4.15.0-99-generic #100-Ubuntu SMP  i686 i686 i686 GNU/Linux

which go 
/usr/bin/go

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

GO111MODULE=""
GOARCH="386"
GOBIN=""
GOCACHE="/home/siva/.cache/go-build"
GOENV="/home/siva/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/siva/github/byteshiva.github.io/goprojects/workspace"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_386"
GCCGO="gccgo"
GO386="387"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build764920817=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
https://play.golang.com/p/HmnNoBf0p1z

### What did you expect to see?
Hello, playground

### What did you see instead?
/usr/local/go/src/sync/pool.go:8:2: C source files not allowed when not using cgo or SWIG: atomic_386.c defs.c float.c heapdump.c lfstack.c malloc.c mcache.c mcentral.c mem_linux.c mfixalloc.c mgc0.c mheap.c msize.c os_linux.c os_linux_386.c panic.c parfor.c proc.c runtime.c signal.c signal_386.c signal_unix.c stack.c string.c sys_x86.c vlrt.c

**Comment by ALTree** [comment]
Those .c files were removed from the toolchain years ago, when it was ported from C to Go. 

I'm pretty sure your Go installation is completely broken (you probably unzipped Go1.14 over the old folder without deleting it first).

Please nuke the /usr/local/go folder and re-install Go from scratch.

**Comment by byteshiva** [comment]
Deleted /usr/local/bin and reinstall go

logs:
https://gist.github.com/byteshiva/8f0087ed4490a6bfc1c45aa406ae3e91

now its throws 
go: cannot find GOROOT directory: /usr/local/go

maybe i should delete the cache do before reinstall

**Comment by ALTree** [comment]
You have GOROOT set to the wrong path somewhere (your current session, or you bashprofile). Just unset it. You don't need to set it.

**Comment by byteshiva** [comment]
I don't remember how I set `GOROOT` in bash shell. Maybe I used some tool which I forgot.

To fix it I unset GOROOT in ~/.bashrc file, Now above simple go example works. Thanks @ALTree 

Steps 
Temporary for the bash session.
```
set | grep $GOROOT
unset GOROOT
```

or 

Permanent 
```
vim ~/.bashrc 
unset GOROOT
```


```
```

```

**Comment by ALTree** [comment]
Nice. Closing here, then.
