### ISSUE TITLE
cmd/doc: prints two leading blank lines for cmd/link/internal/amd64

### ISSUE THREAD

**Issue by willfaught** [golang/go#38943]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/Will/Library/Caches/go-build"
GOENV="/Users/Will/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/Will/Developer/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/Will/Developer/go/src/github.com/willfaught/turbine/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bx/qk0phsxd265fqj512dnnpg080000gn/T/go-build007327064=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.14.2 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.14.2
uname -v: Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G87
lldb --version: lldb-1100.0.30.12
Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
</pre></details>

### What did you do?

```
$ go doc cmd/link/internal/amd64
```

### What did you expect to see?

```
$ go doc cmd/link/internal/amd64
package amd64 // import "cmd/link/internal/amd64"

func Addcall(ctxt *ld.Link, s *sym.Symbol, t *sym.Symbol) int64
func Init() (*sys.Arch, ld.Arch)
func PADDR(x uint32) uint32
```

### What did you see instead?

```
$ go doc cmd/link/internal/amd64


package amd64 // import "cmd/link/internal/amd64"

func Addcall(ctxt *ld.Link, s *sym.Symbol, t *sym.Symbol) int64
func Init() (*sys.Arch, ld.Arch)
func PADDR(x uint32) uint32
```

Seems to happen for other internal link packages too.

**Comment by agnivade** [comment]
This actually got fixed by 670cb9c37769f07fd8c2aac6270a9f2342d2b970. Closing.
