### ISSUE TITLE
cmd/go: does not rebuild when source files are removed

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#3895]
<pre>This is how I broke our build.

% pwd
/home/rog/src/go/src/local/gobug
% ls
% cat &gt; foo.go
package foo
var X = 0
^D
% cat &gt; bar.go
package foo
var Y = 0
^D
% cat &gt; foo_test.go
package foo_test
import (
	&quot;testing&quot;
	foo &quot;local/gobug&quot;
)
func TestX(t *testing.T){
	_ = foo.X
}
^D
% go test
PASS
ok  	local/gobug	0.011s
% go install
% rm foo.go      # as it happens, i actually moved it elsewhere.
% go build
% go install
% go test
PASS
ok  	local/gobug	0.011s
# everything looks just fine, so i pushed to trunk here, breaking
# the build.
% touch *.go
% go test
# local/gobug_test
./foo_test.go:7: undefined: foo.X
FAIL	local/gobug [build failed]
% 

I wonder if the go tool should look at the mtime of the
directory as well as the source files when determining
whether to rebuild.</pre>

**Comment by anacrolix** [comment]
I take it in the example in comment 31, that 'a' and 'b' are analogous to object files, 'a.in' and 'b.in', source files, and that 'foo' is a package/library file, such as foo.a. If 'a.in' is newer than 'a', than 'a' is rebuilt, and then so is 'foo'. But why can't we have that if an object file exists, and a corresponding source file does not, then the extraneous object file is removed and the package rebuilt?

**Comment by tv42** [comment]
@anacrolix Source files and object files don't map 1:1, multiple sources are combined into one .a. See comments 13 and 16.
