### ISSUE TITLE
map: a key-value pair may be GC

### ISSUE THREAD

**Issue by yah01** [golang/go#38976]
### What version of Go are you using (`go version`)?

<pre>
go version go1.14.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/bytedance/Library/Caches/go-build"
GOENV="/Users/bytedance/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="*.byted.org,*.everphoto.cn,git.smartisan.com"
GONOSUMDB="*.byted.org,*.everphoto.cn,git.smartisan.com"
GOOS="darwin"
GOPATH="/Users/bytedance/go"
GOPRIVATE="*.byted.org,*.everphoto.cn,git.smartisan.com"
GOPROXY="https://go-mod-proxy.byted.org,https://goproxy.cn,https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/bytedance/go/src/github.com/yah01/cykv/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lm/th9x2pm904s3jwxzcymh3v940000gn/T/go-build053050234=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I made a map `checker := make(map[string]int64)`, and generated many random strings (about 23 million, with length not greater than 6, character set is all lowercase English letters), for every string `str`, I did `checker[str]++`.
I output all strings to a file (my log file), I did a checking by doing `value, exist := checker[str]`(before did `checker[str]++`), and I noticed that `value == 0` and `exist == false` when a string appeared for the second time. This does not always happen for every string that appeared for the second time.

Code: https://github.com/yah01/cykv/tree/debug
Run the test `TestMapCorrect()` and check _debug.log_ file

### What did you expect to see?
`value == 1` and `exist == true`

### What did you see instead?
`value == 0` and `exist == false`

**Comment by seankhliao** [comment]
I believe the error is somewhere in your "optimize" package and its use of `unsafe`

adding another map `m2` and storing values with `m2["salt"+str]` (forcing a new allocation of the string) results in the following, note the mismatched map sizes
```
checker[QQAXU]=1, len(checker)=7482834 m2[QQAXU]=2 len(m2)=7482831
```

**Comment by randall77** [comment]
I don't see a bug in maps here, although it is hard to tell. I suspect a bug in your map, not the builtin map.
With this patch:
```
diff --git a/cykv_test.go b/cykv_test.go
index c45c202..855499f 100644
--- a/cykv_test.go
+++ b/cykv_test.go
@@ -66,8 +66,10 @@ func TestMapCorrect(t *testing.T) {
 
        startTime := time.Now()
        maxCount := int64(0)
+       var strs []string
        for i := 0; i < int(60e6); i++ {
                str := genRandomStr(TestStrLen)
+               strs = append(strs, str)
                realValue, exist := checker[str]
                checker[str]++
                debugLog.Printf("Start: key=%+v, bytes=%+v", str, []byte(str))
@@ -78,8 +80,14 @@ func TestMapCorrect(t *testing.T) {
 
                if value != checker[str] {
                        debugBuf.Flush()
-                       t.Logf("wrong map, the value before incresing: %+v, exist=%+v", realValue, exist)
-                       t.Fatalf("value: %+v, real: %+v", value, checker[str])
+                       n := 0
+                       for _, s := range strs {
+                           if s == str {
+                              n++
+                           }
+                       }
+                       t.Logf("wrong map, the value before incresing: %+v, exist=%+v, slice=%d", realValue, exist, n)
+                       t.Fatalf("value: %+v, real: %+v slice=%d", value, checker[str], n)
                }
 
                passCount++
```
I get an error like:
```
    cykv_test.go:90: value: 2, real: 1 slice=1
```
Which means the builtin map is correct, and the map you get with `NewMap` is wrong.

**Comment by yah01** [comment]
> I believe the error is somewhere in your "optimize" package and its use of `unsafe`
> 
> adding another map `m2` and storing values with `m2["salt"+str]` (forcing a new allocation of the string) results in the following, note the mismatched map sizes
> 
> ```
> checker[QQAXU]=1, len(checker)=7482834 m2[QQAXU]=2 len(m2)=7482831
> ```

You're right, looks like the `unsafe` causing the wrong result...

**Comment by yah01** [comment]
> I don't see a bug in maps here, although it is hard to tell. I suspect a bug in your map, not the builtin map.
> With this patch:
> 
> ```
> diff --git a/cykv_test.go b/cykv_test.go
> index c45c202..855499f 100644
> --- a/cykv_test.go
> +++ b/cykv_test.go
> @@ -66,8 +66,10 @@ func TestMapCorrect(t *testing.T) {
>  
>         startTime := time.Now()
>         maxCount := int64(0)
> +       var strs []string
>         for i := 0; i < int(60e6); i++ {
>                 str := genRandomStr(TestStrLen)
> +               strs = append(strs, str)
>                 realValue, exist := checker[str]
>                 checker[str]++
>                 debugLog.Printf("Start: key=%+v, bytes=%+v", str, []byte(str))
> @@ -78,8 +80,14 @@ func TestMapCorrect(t *testing.T) {
>  
>                 if value != checker[str] {
>                         debugBuf.Flush()
> -                       t.Logf("wrong map, the value before incresing: %+v, exist=%+v", realValue, exist)
> -                       t.Fatalf("value: %+v, real: %+v", value, checker[str])
> +                       n := 0
> +                       for _, s := range strs {
> +                           if s == str {
> +                              n++
> +                           }
> +                       }
> +                       t.Logf("wrong map, the value before incresing: %+v, exist=%+v, slice=%d", realValue, exist, n)
> +                       t.Fatalf("value: %+v, real: %+v slice=%d", value, checker[str], n)
>                 }
>  
>                 passCount++
> ```
> 
> I get an error like:
> 
> ```
>     cykv_test.go:90: value: 2, real: 1 slice=1
> ```
> 
> Which means the builtin map is correct, and the map you get with `NewMap` is wrong.

Thanks, I found something wrong in my optimize package...
