### ISSUE TITLE
cmd/go: Using go modules in a child cmd directory with local path in replace directive needs valid version

### ISSUE THREAD

**Issue by montanaflynn** [golang/go#38972]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/montanaflynn/Library/Caches/go-build"
GOENV="/Users/montanaflynn/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="github.com/mathpix/api/util"
GONOSUMDB="github.com/mathpix/api/util"
GOOS="darwin"
GOPATH="/Users/montanaflynn/Development/go"
GOPRIVATE="github.com/mathpix/api/util"
GOPROXY="direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/montanaflynn/Development/go/src/github.com/montanaflynn/notify-cli/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/j1/q0f3l2dj5lj89gr14gzfnw080000gn/T/go-build774174740=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Created a [new project](https://github.com/montanaflynn/notify-cli) with a `./cmd/notify/` directory to allow users to use as a library or install a cli program easily using `go get github.com/montanaflynn/notify-cli/cmd/notify`.

The [`./cmd/notify/go.mod`](https://github.com/montanaflynn/notify-cli/blob/v0.0.7/cmd/notify/go.mod) is set to use the local package path using `replace directive` along with require set to version v0.0.0 as mentioned in the [wiki replace section](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive):

> In Go 1.11, for direct dependencies a require directive is needed even when doing a replace. For example, if foo is a direct dependency, you cannot do replace foo => ../foo without a corresponding require for foo. If you are not sure what version to use in the require directive, you can often use v0.0.0 such as require foo v0.0.0. This was addressed in Go 1.12 with #26241. 

```
require github.com/montanaflynn/notify-cli v0.0.0
replace github.com/montanaflynn/notify-cli => ../../
```

### What did you expect to see?

I expected `go get github.com/montanaflynn/notify-cli/cmd/notify` to work.

### What did you see instead?

```
go: downloading github.com/montanaflynn/notify-cli/cmd/notify v0.0.0-20200508151944-ea02fb5189fc
go: github.com/montanaflynn/notify-cli/cmd/notify upgrade => v0.0.0-20200508151944-ea02fb5189fc
go get: github.com/montanaflynn/notify-cli/cmd/notify@v0.0.0-20200508151944-ea02fb5189fc requires
	github.com/montanaflynn/notify-cli@v0.0.0: reading github.com/montanaflynn/notify-cli/go.mod at revision v0.0.0: unknown revision v0.0.0
```

If I change the require directive to a valid version it works:

```
require github.com/montanaflynn/notify-cli v0.0.6
```

Even though it's said to require v0.0.6 it does successfully use the local path to install the latest version. I've had a lot of confusion surrounding the migration to go modules and I think this is a common pattern a lot of Go developers are using so I think a best practice example in the wiki would be helpful. Also I wonder why the require is needed at all or if there's a better way to signal that the it's a local dependency.

**Comment by seankhliao** [comment]
separate modules are independent, there is no guarantee the parent directories exist

that said the wiki also recommends against multi module repositories for most use cases

**Comment by toothrot** [comment]
I'm not certain there is a bug here. If you want the module at `github.com/montanaflynn/notify-cli/cmd/notify` to always be the same version as `github.com/montanaflynn/notify-cli`, it may be better not to have a second module at `cmd/notify`. 

/cc @bcmills, who may be able to explain this better.
See also #27542 and #27056

**Comment by bcmills** [comment]
I agree with @seankhliao and @toothrot's assessment. For your use-case, it is likely preferable to keep the command within the same module as the library.

If you want to maintain a separate module and allow it to be fetched with `go get`, then you need to maintain accurate version requirements for that module. Separate modules are stored separately within the module cache, so without a version requirement the `go` command has no way to determine which version of `github.com/montanaflynn/notify-cli` actually corresponds to `../../`.

**Comment by bcmills** [comment]
@montanaflynn, could you explain why you wanted to split `cmd/notify` into a separate module to begin with? As far as I can tell, the best we can do here is likely to better document the reasons not to do that...

**Comment by jakesyl** [comment]
@bcmills one use case is dependency management. We have something of a standard library in go internally that has a ton of depdencies and it's a bit of a pain to have to install them all for every repo in our ci workflow. We would like to version them in lcok step though for sanity's sake

**Comment by montanaflynn** [comment]
@seankhliao @toothrot @bcmills thanks, I removed the second cmd module and my problem went away. I was under the impression that in order to use the library I needed to create a module with it as a dependency.

**Comment by bcmills** [comment]
Thanks for following up. Since you have a viable alternative and the `go` command seems to be working as designed, I'm going to close out this issue, but we'll continue to keep an eye out for related usability and documentation issues.
