### ISSUE TITLE
x/tools/gopls: advice for the warning of "You are neither in a module nor in your GOPATH"

### ISSUE THREAD

**Issue by wondar-chan** [golang/go#38979]
i actually use "go mod init appname" to generate a go.mod, but the vocode go extention still warns me that  "You are neither in a module nor in your GOPATH"

**Comment by PaluMacil** [comment]
This is the issue tracker for the language runtime and not where the vscode package is maintained. [Microsoft maintains the extension and it's hosted at microsoft/vscode-go].(https://github.com/microsoft/vscode-go). I can still advise: exit and reload. The way the vs code extension works, it doesn't recheck for your module file after you make it, so you are seeing an error that's out of date. The command Go: Restart Language Server (hit F1 to enter) might also recheck for module mode.

**Comment by stamblerre** [comment]
`gopls` should actually handle the creation of a `go.mod` file. @wondar-chan: What is the root directory that you have open in VS Code? It has to be the one that contains the `go.mod` file or a subdirectory.
