### ISSUE TITLE
reflect: DeepEqual always returns true for unexported C structures in dynamic library

### ISSUE THREAD

**Issue by zhuah** [golang/go#38980]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOOS="darwin"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O3"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O3"
CGO_FFLAGS="-g -O3"
CGO_LDFLAGS="-g -O3"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mh/1m52c3f528bgn228cmszj8pr0000gn/T/go-build145184058=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
create two instance of C structure, and set pointer of it as member of Go structure,
call `reflect.DeepEqual` on two Go structure.

### What did you expect to see?
I expect `DeepEqual `returns `false` since Go doesn't knows the detail of C structure, 
i have dig into the source code of `reflect.DeepEqual` and found that it will iterate over structure fields, but the fields slice is empty for such C structures.

### What did you see instead?
it returns `true`.

**Comment by davecheney** [comment]
Thank you for your issue. Can you please provide a short runnable example which demonstrates the problem.

**Comment by zhuah** [comment]
@davecheney 
[deepequal.zip](https://github.com/golang/go/files/4607133/deepequal.zip)
extract it and just `make run`.
```sh
➜  deepequal tree .
.
├── Makefile
├── clib
│   ├── deepequal.c
│   └── deepequal.h
└── deepequal.go

1 directory, 4 files
➜  deepequal
```

**Comment by ianlancetaylor** [comment]
The Go code doesn't have any information about the C structures.  As far as `reflect.DeepEqual` knows, it has two pointers to empty structs.  Since the empty structs have no fields, they are equal.

I don't see anything else we can do here.

**Comment by zhuah** [comment]
If defines the C structure in .h file, the go runtime could correctly recognize structure members.

it may be better that returns false by default for those unexported structures, just like function comparison.
```Go
	case Func:
		if v1.IsNil() && v2.IsNil() {
			return true
		}
		// Can't do better than this:
		return false
```

**Comment by ianlancetaylor** [comment]
The `reflect.DeepEqual` function doesn't know anything about cgo, and it shouldn't know anything about cgo.  I can't think of any way to implement that suggestion.

And even if we could implement it, I don't understand why it is correct.  The truth is that we simply don't know whether the values are equal or not.  I don't see why returning `false` is any better than returning `true`.

This is different from the case of comparing `func` values, which cannot be compared in the language at all.  Functions are neither equal nor unequal; they are incomparable.  Struct values are (normally) comparable, so there is an answer as to whether they are deep-equal or not.  It's just that in this case `reflect.DeepEqual` can't determine it.  The current implementation happens to return `true`; I don't see why it is any better to happen to return `false`.
