### ISSUE TITLE
x/mobile: file is universal (4 slices) but does not contain the arm64 architecture

### ISSUE THREAD

**Issue by dsanghan** [golang/go#38981]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/dev/Library/Caches/go-build"
GOENV="/Users/dev/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/dev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/dev/go/src/github.com/ProtonMail/gopenpgp/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/j8/c5jk9r4j7s5dgj8hvk7k0wmm0000gp/T/go-build996154893=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Follow instructions here: https://github.com/ProtonMail/gopenpgp

```
cd $GOPATH
mkdir -p src/github.com/ProtonMail/
cd $GOPATH/src/github.com/ProtonMail/
git clone git@github.com:ProtonMail/gopenpgp.git
cd gopenpgp
sh build.sh
```

Add the generated frameworks to any objective-c project & call any function.

### What did you expect to see?

Would be able to use generated framework without issue.

### What did you see instead?

```
ld: warning: ignoring file /Users/dev/Developer/canary/Canary/Canary-iOS/Crypto.framework/Crypto, file is universal (4 slices) but does not contain the arm64 architecture: /Users/dev/Developer/canary/Canary/Canary-iOS/Crypto.framework/Crypto
Undefined symbols for architecture arm64:
  "_CryptoNewKey", referenced from:
      -[CanaryCorePGPManager migrateKeys] in CanaryCorePGPManager.o
ld: symbol(s) not found for architecture arm64
```

**Comment by changkun** [comment]
It seems that it is an issue with the provided module https://github.com/ProtonMail/gopenpgp as the module did not support Go Modules. At the moment, https://github.com/ProtonMail/gopenpgp/commit/b5823b9dee5eb52b1a8f3294ec66772de6decf12 have updated their build process, which seems to suggest this issue has become obsolete. Therefore close this due to outdated.
