### ISSUE TITLE
cmd/go: go list -e -compiled -json does not populate Error when cgo preprocessing fails

### ISSUE THREAD

**Issue by dominikh** [golang/go#38990]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 linux/amd64
go version devel +57e32c4fbd Sun May 10 14:43:46 2020 +0000 linux/amd64
</pre>

### What's wrong

When cgo preprocessing fails, `go list -json -compiled -e` prints an error on stderr and exits with a non-zero status, but it does not populate the Error field of the package. It is possible to detect that something went wrong because CompiledGoFiles isn't populated, but we can't tell _why_ it failed. Two common reasons are a missing C compiler, and missing libraries.

### Example output

```
$ CC=/does/not/exist go list -json -compiled -e runtime/cgo
# runtime/cgo
fork/exec /does/not/exist: no such file or directory
{
	"Dir": "/nix/store/sylhlk3fd3xik0d8hqrm20zxnfc3x7m4-go-1.14.1/share/go/src/runtime/cgo",
	"ImportPath": "runtime/cgo",
	"Name": "cgo",
	"Doc": "Package cgo contains runtime support for code generated by the cgo tool.",
	"Target": "/nix/store/sylhlk3fd3xik0d8hqrm20zxnfc3x7m4-go-1.14.1/share/go/pkg/linux_amd64/runtime/cgo.a",
	"Root": "/nix/store/sylhlk3fd3xik0d8hqrm20zxnfc3x7m4-go-1.14.1/share/go",
	"Match": [
		"runtime/cgo"
	],
	"Goroot": true,
	"Standard": true,
	"Stale": true,
	"StaleReason": "build ID mismatch",
	"GoFiles": [
		"callbacks.go",
		"callbacks_traceback.go",
		"iscgo.go",
		"mmap.go",
		"setenv.go",
		"sigaction.go"
	],
	"CgoFiles": [
		"cgo.go"
	],
	"IgnoredGoFiles": [
		"callbacks_aix.go",
		"dragonfly.go",
		"freebsd.go",
		"netbsd.go",
		"openbsd.go",
		"signal_darwin_armx.go"
	],
	"CFiles": [
		"gcc_context.c",
		"gcc_fatalf.c",
		"gcc_libinit.c",
		"gcc_linux_amd64.c",
		"gcc_mmap.c",
		"gcc_setenv.c",
		"gcc_sigaction.c",
		"gcc_traceback.c",
		"gcc_util.c"
	],
	"HFiles": [
		"libcgo.h",
		"libcgo_unix.h"
	],
	"SFiles": [
		"asm_amd64.s",
		"gcc_amd64.S"
	],
	"CgoCFLAGS": [
		"-Wall",
		"-Werror"
	],
	"CgoLDFLAGS": [
		"-lpthread"
	],
	"Imports": [
		"C",
		"unsafe"
	],
	"Deps": [
		"unsafe"
	]
}
```

Related: #34229 and #25842

/cc @bcmills @matloob @heschik

**Comment by jayconrod** [comment]
This has the same root cause as the two linked issues: #34229 and #25842

Currently, `go list -e` populates the `Error` field with errors it encounters when loading the package dependency graph. It should also populate the `Error` field with errors encountered when running cgo, the compiler, and other commands.

**Comment by SeanTolstoyevski** [comment]
This issue also occurs when coding a CGO module with VSCode.

now is there anything that can be making?

**Comment by thalesfsp** [comment]
> This issue also occurs when coding a CGO module with VSCode.
> 
> now is there anything that can be making?

Do u know how to disable this message on VSCode?

**Comment by zyfdegh** [comment]
@SeanTolstoyevski @thalesfsp  There's no quick solution currently, but to figure out what's wrong VSCode running `go list` command, execute this manually 
```sh
go list -e -json -compiled -x  /absolute/path/to/yourpkg/src.go
```

For me, it outputs
```sh
WORK=/tmp/go-build2892322839
mkdir -p $WORK/b001/
cd /absolute/path/to/yourpkg
TERM='dumb' CGO_LDFLAGS='"-g" "-O2" "-L/absolute/path/to/yourpkg/lib" "-lMp42Pack"' /usr/lib/go/pkg/tool/linux_amd64/cgo -objdir $WORK/b001/ -importpath command-line-arguments -- -I $WORK/b001/ -g -O2 -I/absolute/path/to/yourpkg/include/dms -std=c99 ./src.go
# command-line-arguments
In file included from services/packservice/src.go:10:
services/packservice/include/dms/DMSPackWapper.h:1:10: fatal error: iostream: No such file or directory
    1 | #include <iostream>
      |          ^~~~~~~~~~
compilation terminated.
{
        "Dir": "/absolute/path/to/yourpkg",
        "ImportPath": "command-line-arguments",
        "Name": "packservice",
        "Match": [
                "/absolute/path/to/yourpkg/src.go"
        ],
        "Stale": true,
        "StaleReason": "build ID mismatch",
        "CgoFiles": [
                "src.go"
        ],

# ... more JSON, but no 'CompiledGoFiles' field, VSCode cannot interpret
```

**Comment by FH0** [comment]
There are two errors in my cgo program, but I can run it fine. I've searched a lot but still don't know how to fix these two errors that shouldn't be there. I'll just have to try my luck here.

![image](https://user-images.githubusercontent.com/32861476/182273173-11f849aa-04f7-49fe-8bba-3a2b419a1e49.png)

![image](https://user-images.githubusercontent.com/32861476/182273599-0da0e70d-e037-4bcc-a450-c3237d9d16e6.png)

![image](https://user-images.githubusercontent.com/32861476/182273239-3b0d4e1e-3b81-4a54-8dbb-6032dbe023a5.png)

```bash
root@ubuntu2004 /root/go/src/learn
# go list -e -json -compiled -x main.go
WORK=/tmp/go-build172218443
mkdir -p $WORK/b001/
cd /root/go/src/learn
TERM='dumb' CGO_LDFLAGS='"-g" "-O2"' /usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/b001/ -importpath command-line-arguments -- -I $WORK/b001/ -g -O2 ./main.go
cd $WORK
gcc -fno-caret-diagnostics -c -x c - -o /dev/null || true
gcc -Qunused-arguments -c -x c - -o /dev/null || true
gcc -fdebug-prefix-map=a=b -c -x c - -o /dev/null || true
gcc -gno-record-gcc-switches -c -x c - -o /dev/null || true
cd $WORK/b001
TERM='dumb' gcc -I /root/go/src/learn -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -o ./_x001.o -c _cgo_export.c
TERM='dumb' gcc -I /root/go/src/learn -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -o ./_x002.o -c main.cgo2.c
TERM='dumb' gcc -I /root/go/src/learn -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -o ./_cgo_main.o -c _cgo_main.c
cd /root/go/src/learn
TERM='dumb' gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -o $WORK/b001/_cgo_.o $WORK/b001/_cgo_main.o $WORK/b001/_x001.o $WORK/b001/_x002.o -g -O2
TERM='dumb' /usr/local/go/pkg/tool/linux_amd64/cgo -dynpackage main -dynimport $WORK/b001/_cgo_.o -dynout $WORK/b001/_cgo_import.go
{
        "Dir": "/root/go/src/learn",
        "ImportPath": "command-line-arguments",
        "Name": "main",
        "Target": "/root/go/bin/main",
        "Root": "/root/go",
        "Match": [
                "main.go"
        ],
        "Stale": true,
        "StaleReason": "stale dependency: fmt",
        "CgoFiles": [
                "main.go"
        ],
        "CompiledGoFiles": [
                "/root/.cache/go-build/23/23c8fe3c2183dd4d83d20fc531e6cd5bf2b241f58b7d34e14637c5613006c72d-d",
                "/root/.cache/go-build/13/135d992523728ea58aba4fa664090b30fed3f393c098cec69dafe491fa19151f-d",
                "/root/.cache/go-build/20/208f6d19c1a23764cd62b4ec0928985a90bf7a1604e95051639db0f0f7d1e439-d"
        ],
        "Imports": [
                "C",
                "fmt",
                "unsafe",
                "runtime/cgo",
                "syscall"
        ],
        "Deps": [
                "errors",
                "fmt",
                "internal/abi",
                "internal/bytealg",
                "internal/cpu",
                "internal/fmtsort",
                "internal/goarch",
                "internal/goexperiment",
                "internal/goos",
                "internal/itoa",
                "internal/oserror",
                "internal/poll",
                "internal/race",
                "internal/reflectlite",
                "internal/syscall/execenv",
                "internal/syscall/unix",
                "internal/testlog",
                "internal/unsafeheader",
                "io",
                "io/fs",
                "math",
                "math/bits",
                "os",
                "path",
                "reflect",
                "runtime",
                "runtime/cgo",
                "runtime/internal/atomic",
                "runtime/internal/math",
                "runtime/internal/sys",
                "runtime/internal/syscall",
                "sort",
                "strconv",
                "sync",
                "sync/atomic",
                "syscall",
                "time",
                "unicode",
                "unicode/utf8",
                "unsafe"
        ]
}
```

![image](https://user-images.githubusercontent.com/32861476/182273485-8fa536c5-fc34-4ef4-9ba8-843cbcff5831.png)

**Comment by FH0** [comment]
![image](https://user-images.githubusercontent.com/32861476/184463590-597864ce-09f6-440d-88b9-5c821f4ae05f.png)

After I commented line 81, the problem was solved.

**Comment by toriato** [comment]
There may be a problem caused by the architecture of the C toolchain you are using being different from the `GOARCH` environment variable. 
If you are using vscode, you can try setting the `GOARCH` value through the `build.env`.
```json
{
  "gopls": {
    "build.env": {
      "GOARCH": "386"
    }
  }
}
```

**Comment by Xosrov** [comment]
I was getting this issue using the mingw version of Go with CGo. Adding these lines to `settings.json` fixed it:
```json
"go.goroot": "C:\\msys64\\mingw64\\lib\\go",
    "go.testEnvVars": {
        "CGO_ENABLED": 1,
        "PATH": "C:\\msys64\\mingw64\\bin"
    },
    "go.toolsEnvVars": {
        "CGO_ENABLED": 1,
        "PATH": "C:\\msys64\\mingw64\\bin"
    },

```
It also fixes the gcc not found problems when testing cgo code from vscode.

**Comment by StitchyKid** [comment]
> ![image](https://user-images.githubusercontent.com/32861476/184463590-597864ce-09f6-440d-88b9-5c821f4ae05f.png)
> 
> After I commented line 81, the problem was solved.

could you show what file you are editing ? i can't tell exactly what you're doing i know it is json but how do i get to it ?

**Comment by FH0** [comment]
@StitchyKid 
![image](https://user-images.githubusercontent.com/32861476/226522599-a41bd4f0-7160-4971-b460-180318b1ceb0.png)

**Comment by hash-rabbit** [comment]
when i set 
<img width="909" alt="image" src="https://github.com/golang/go/assets/24784215/3ed18074-183e-4359-9f7c-a443e43e3827">
and set CGO_ENABLE:1,like this
<img width="326" alt="image" src="https://github.com/golang/go/assets/24784215/7551dcae-261e-4b2c-87ba-5dcdef8344fa">
it fixed

**Comment by bcmills** [comment]
I have hidden a bunch of off-topic comments for this issue.

Folks, if you are dealing with a problem that does not match the problem described in the issue title, please either file a separate issue or start a thread on `golang-nuts`. This issue is not the place for troubleshooting cgo usage in VSCode.

**Comment by thalesfsp** [comment]
> I have hidden a bunch of off-topic comments for this issue.
> 
> Folks, if you are dealing with a problem that does not match the problem described in the issue title, please either file a separate issue or start a thread on `golang-nuts`. This issue is not the place for troubleshooting cgo usage in VSCode.

Sure, it's 3y old issue.....

**Comment by samthanawalla** [comment]
Unfortunately, I can't reproduce this issue on 1.22 so perhaps it was already fixed :D Let me know if you are still running into this issue!

**Comment by gandarez** [comment]
Having the same issue with Go 1.24

**Comment by sandviklee** [comment]
Hey 👋🏻, I'm running go 1.24.1 om darwin/arm64:

I fixed my error with just changing my C compiler to gcc rather than using clang

```bash
export CC=gcc
```

worked for me!
