### ISSUE TITLE
cmd/doc: -src flag misbehaves on some systems [1.14 backport]

### ISSUE THREAD

**Issue by adg** [golang/go#38993]
Under go1.14.2, if you run `go doc -src strings.Compare` on macOS you get [a bunch of unrelated comments](https://gist.github.com/adg/2eebefdad5c85327a981605a8500d5fd).

Commit 585e31df63f6879c03b285711de6f9dcba1f2cb0 fixes this issue, but it is not applied in the current release (go1.14.2). It would be great to get this trivial fix cherry picked into the next point release.

(Apologies if I should be using @gopherbot to create this issue; I would have but there wasn't a corresponding issue for the original fix.)

**Comment by andybons** [comment]
Approved as this is a minor change with no workaround.

**Comment by andybons** [comment]
@adg can you create the cherry-pick CL (per https://golang.org/wiki/MinorReleases) and add me as a reviewer?

**Comment by adg** [comment]
> Note that only the authors of the original CL (or maintainers with the "impersonate" permission) have the ability to create the cherry-pick.

I don't have that permission anymore it seems. :)
