### ISSUE TITLE
net/http: Status shouldn't include StatusCode

### ISSUE THREAD

**Issue by kkroo** [golang/go#38996]
In parsing: `HTTP/1.1 200 OK`

`StatusCode` is correctly set to `200` but `Status` is parsed to `200 OK` when it should only be `OK`. This leads to inconsistency with `http.StatusText` which only returns `OK` instead of `200 OK`

https://github.com/golang/go/blob/master/src/net/http/response.go#L176
https://github.com/golang/go/blob/master/src/net/http/status.go#L85

**Comment by mdlayher** [comment]
I suspect it is too late to modify this behavior, since the field is documented to return a string in https://golang.org/pkg/net/http/#Response.

**Comment by toothrot** [comment]
I don't see how this can be changed without breaking a lot of software. The current code is behaving as documented.

/cc @bradfitz @rsc

**Comment by seankhliao** [comment]
closing as unfortunate
