### ISSUE TITLE
vector insert performance difference

### ISSUE THREAD

**Issue by zfLQ2qx2** [golang/go#39001]
### What version of Go are you using (`go version`)?

<pre>
go version go1.14.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Is the latest release

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xxx/Library/Caches/go-build"
GOENV="/Users/xxx/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xxx/xxx"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m0/qrd0w3g15xvd7t0jx7m3dt500000gn/T/go-build695738032=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Benchmarked these two functions to insert one slice into another at index i.

```
package main

import "testing"

func BenchmarkVectorInsertAppend(b *testing.B) {
        array1 := []int{1, 3, 4, 5}
        array2 := []int{2, 4, 6, 8}
        i := 1

        for n := 0; n < b.N; n++ {
                array1 = append(array1[:i], append(array2, array1[i:]...)...)
        }
        b.ReportAllocs()
}

func BenchmarkVectorInsertCopy(b *testing.B) {
        array1 := []int{1, 3, 4, 5}
        array2 := []int{2, 4, 6, 8}
        i := 1

        for n := 0; n < b.N; n++ {
                array3 := make([]int, len(array1)+len(array2))
                copy(array3, array1[:i])
                copy(array3[i:], array2)
                copy(array3[len(array2)+i:], array1[i:])
        }
        b.ReportAllocs()
}
```

### What did you expect to see?

I was expecting both functions to preform around the same for a base type like int

### What did you see instead?

The version of the function using append performs significantly worse then the version with copy

```
BenchmarkVectorInsertAppend-8   	   52489	    124675 ns/op	  843972 B/op	       1 allocs/op
BenchmarkVectorInsertCopy-8     	40859722	        31.2 ns/op	      64 B/op	       1 allocs/op
```

**Comment by ALTree** [comment]
The two benchmarks are doing completely different things, as the totally unrealistic `843kB` per OP of allocations performed by the 1st benchmark clearly suggests.

Hint: print `array1` in the first benchmark to see what you're doing wrong.

Closing here, since the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions.
