### ISSUE TITLE
field fail_if_not_matches_regexp not found in type config.plain

### ISSUE THREAD

**Issue by bljusruk** [golang/go#39018]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
The latest one available as golang:1.14-alpine is 1.14 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/app/blackbox-exporter/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build911595323=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Built blackbox_exporter within Docker image. Cloned the latest blackbox_exporter from https://github.com/prometheus/blackbox_exporter.git

The command to build blackbox_exporter:

docker build --tag bbex /home/mirov/workspace/sa20sre/blackbox-exporter

Build finished successfully.

Tried to start the image by executing the command:

docker run -it -p 9115 bbex:latest

gave me the following error:

level=info ts=2020-05-12T14:05:44.396Z caller=main.go:212 msg="Starting blackbox_exporter" version="(version=0.16.0, branch=master, revision=36b75845788c22cd33511f5c61a6ea6df4cc8f16)"
level=info ts=2020-05-12T14:05:44.396Z caller=main.go:213 msg="Build context" (gogo1.14.2,userroot@1855291a76a9,date20200512-13:59:26)=(MISSING)
level=error ts=2020-05-12T14:05:44.397Z caller=main.go:216 msg="Error loading config" err="error parsing config file: yaml: unmarshal errors:\n  line 24: field fail_if_not_matches_regexp not found in type config.plain"

The blackbox_exporter.yml config file is bellow.

### What did you expect to see?
I'm expecting image to be started without errors.

### What did you see instead?
I saw the following error:

level=info ts=2020-05-12T14:05:44.396Z caller=main.go:212 msg="Starting blackbox_exporter" version="(version=0.16.0, branch=master, revision=36b75845788c22cd33511f5c61a6ea6df4cc8f16)"
level=info ts=2020-05-12T14:05:44.396Z caller=main.go:213 msg="Build context" (gogo1.14.2,userroot@1855291a76a9,date20200512-13:59:26)=(MISSING)
level=error ts=2020-05-12T14:05:44.397Z caller=main.go:216 msg="Error loading config" err="error parsing config file: yaml: unmarshal errors:\n  line 24: field fail_if_not_matches_regexp not found in type config.plain"

**Comment by bljusruk** [comment]
![config](https://user-images.githubusercontent.com/52827396/81705570-78f7ae00-946f-11ea-8526-a4a5c2f1eda6.png)

**Comment by ianlancetaylor** [comment]
I think you've filed this issue with the wrong project.  There seems to be a problem parsing your YAML file, but that isn't running any code written by the Go project.  It just happens to be written in Go.

**Comment by bljusruk** [comment]
@ianlancetaylor I'm sorry. You're right. This is not the go issue at all. It' blackbox_exporter issue. Please close it.

**Comment by ianlancetaylor** [comment]
Thanks for following up.
