### ISSUE TITLE
Documentation licensing

### ISSUE THREAD

**Issue by marianc** [golang/go#39028]
I am relatively new to Golang and one of the main learning resources is Golang documentation. Therefore I started to use the documentation, but later I found that, apparently, the code examples are licensed under BSD license.

> [Copyright](https://golang.org/doc/copyright.html) (on the very bottom of every page)
Except as noted, the contents of this site are licensed under the Creative Commons Attribution 3.0 License, and code is licensed under a BSD license.

The only code from the documentation site is the code from the examples.

Is my understanding correct? If I include code from the documentation examples in my projects, I have to comply to BSD license?

For instance, in one of my projects I copied and added an entire snippet of code from '[Iteration order](https://blog.golang.org/maps#TOC_7.)' and adapted it to my needs, but compliance to BSD does not feel right as you can see [here](https://github.com/marianc/go-gqlgen-graphql-server-typescript-client/blob/master/Tools/03.GraphSchemaGenerator/modules/generatorUtils.go). In order to master the language one has to use the documentation and enforcing BSD in this way may not be convenient for some projects. Can you please provide some clarification?

Thank you for your help.

**Comment by ianlancetaylor** [comment]
The source code files in the Go project all have comments like this:

```Go
// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
```

The `LICENSE` file then contains the relevant license.

In your case you might quote those three lines but say something like "Portions copyright 2020 The Go Authors", and add the Go license to your `LICENSE` file.

I don't see that as substantially different from adhering to the Creative Commons Attribution 3.0 Attribution license.

**Comment by marianc** [comment]
@ianlancetaylor. Thank you for your quick answer.

So, indeed the BSD license is enforced thru documentation. If a target project uses BSD everything is simple, but if it uses another type of license (like GPL) things may become complicated or confusing in terms of licensing.

Nevertheless this is a useful clarification and advice. Thank you again.
