### ISSUE TITLE
os: hangs in os.(*Process).blockUntilWaitable on android-amd64-emu

### ISSUE THREAD

**Issue by bcmills** [golang/go#39023]
I've only seen one log like this so far, but it contains three of the same apparent hang:
[2020-05-11T22:38:32-8c1db77/android-amd64-emu](https://build.golang.org/log/267b5f1dca62229319f35be2c2a3d7d8021065a1)

This was at [CL 232862](https://golang.org/cl/232862), and may be related to that change (CC @ianlancetaylor).

Tentatively marking as release-blocker, at least until we better understand whether it is a bug in the builder or in the standard library.

**Comment by ianlancetaylor** [comment]
I don't think this is a hang in `blockUntilWaitable`.  In each case the program that is hanging is misc/android/go_android_exec.  That is a fairly simple program that runs adb and waits for it to complete.  While waiting for it to complete, go_android_exec will be sleeping in `blockUntilWaitable`.  In this case, it appears that adb does nothing; specifically `adb wait-for-device` does nothing.  Then eventually the test harness times out and kills go_android_exec, and we see the kind of stack traces shown in the log.  That log does not show any successful tests; all tests fail with the same error.  The problem has not recurred.  So I think this was simply a case of the Android device not responding.  Closing.
