### ISSUE TITLE
question: How to remove directory information?

### ISSUE THREAD

**Issue by KittyTechnoProgrammer** [golang/go#39035]
### What version of Go are you using (`go version`)?

<pre>

go version go1.14.2 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/kittytechno/go/bin"
GOCACHE="/home/kittytechno/.cache/go-build"
GOENV="/home/kittytechno/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/kittytechno/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build970436955=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

strings a go executable

### What did you expect to see?

no directory information

### What did you see instead?

my directory information

I was trying to make a release of a go project, and I strings the executable, and I found that my directory information was stored inside. Even though I stripped debugging information.
 
Example :

/home/kittytechno/go_projects/src/github.com/mitchellh/go-ps/process_windows.go
and their is much more information after. This is a little scary that someone can just strings the executable and get information on my directories. 

Is there a way to remove that directory information?

**Comment by ALTree** [comment]
> Is there a way to remove that directory information?

Yes, call `go build` with the `-trimpath` flag. Closing here since we don't really use the issue tracker for questions. It's just for Go bugs.
