### ISSUE TITLE
x/build: aix-ppc64 builder was missing

### ISSUE THREAD

**Issue by dmitshur** [golang/go#39031]
From https://farmer.golang.org/#pools:

```
host-aix-ppc64-osuosl: 0/0 (1 missing)
```

/cc @trex58 Are you able to look into this? Thank you.

/cc @toothrot @cagedmantis @andybons

**Comment by dmitshur** [comment]
This looks to be resolved now:

```
host-aix-ppc64-osuosl: 1/1
```

@trex58 Did you take some action, or was it perhaps some temporary network issue preventing the aix builder from connecting?

**Comment by Helflym** [comment]
It's just the providers of our buildfarm which are making a few updates recently, I forget to warn you as they say it might be only 1h.
