### ISSUE TITLE
net http  ,only a question,about how to request http://**.**.com/%,the non-ascii word how to treat?

### ISSUE THREAD

**Issue by Goend** [golang/go#39037]
if you left your code,it's very perfect,thanks a lot

**Comment by Goend** [comment]
__

**Comment by davecheney** [comment]
Thank you for raising this issue. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
