### ISSUE TITLE
gccgo: does not build go tool

### ISSUE THREAD

**Issue by gopherbot** [golang/go#3904]
by **viriketo**:

<pre>I'm trying with gccgo 4.7.1, with the source of go 1.0.2.

I go to src/cmd/go, and run:
$ gccgo -o go `ls *.go | grep -v _test.go | grep -v bootstrap | grep -v doc`
It builds fine.

Then I try to run:
$ ./go build -compiler gccgo 
list.go:8:2: import &quot;bufio&quot;: cannot find package
build.go:8:2: import &quot;bytes&quot;: cannot find package
...

And it complains that it can't find any go pkg (in import statements).

On #go-nuts, nsf pointed me to pkg/go/build/build.go:364. It has code meant to work only
if built with gc.

I'm trying this on linux-x86_64, but I'm doing this to have a 'go' command working in
linux-mips64.</pre>

**Comment by ianlancetaylor** [comment]
The gccgo build now builds a copy of the go tool.  This will be in the GCC 5 release.
