### ISSUE TITLE
cmd/go: refactor mvsReqs.Max for better readability

### ISSUE THREAD

**Issue by robpike** [golang/go#39042]
At head (go version devel +e90b0ce68b Sat May 2 20:22:19 2020 +0000 darwin/amd64) I see this function in src/go/cmd/go/internal/modload/mvs.go:

```
func (*mvsReqs) Max(v1, v2 string) string {
	if v1 != "" && semver.Compare(v1, v2) == -1 {
		return v2
	}
	return v1
}
```

I believe that "return v1" is wrong if v1 is empty, and the code should be something like:

```
func (*mvsReqs) Max(v1, v2 string) string {
	if v1 == "" || semver.Compare(v1, v2) == -1 {
		return v2
	}
	return v1
}
```

but I am not confident of the semantics this function requires. Moreover, since Compare protects against bad parses, it's possible no checking is required:

```
func (*mvsReqs) Max(v1, v2 string) string {
	if semver.Compare(v1, v2) == -1 {
		return v2
	}
	return v1
}
```

**Comment by myitcv** [comment]
cc @bcmills @jayconrod

**Comment by jayconrod** [comment]
I *think* this is working as intended, but the code could be refactored for better readability.

`mvsReqs.Max` is run as part of MVS. At the point it's called, all `go.mod` files have been read, and all versions have been canonicalized. The only module with the version `""` should be the main module, which must be chosen over any other version required by its transitive dependencies. For this reason, `""` compares higher than any other string.

We should refactor this for better readability. We should explain why [`semver.Max`](https://pkg.go.dev/golang.org/x/mod/semver?tab=doc#Max) is not used instead.

**Comment by bcmills** [comment]
> We should explain why `semver.Max` is not used instead.

That reason is #32700.
