### ISSUE TITLE
crypto/tls: OCSP and SCTs are dropped in resumed connections [freeze exception]

### ISSUE THREAD

**Issue by katiehockman** [golang/go#39075]
On resumed connections, the OCSP response and SCTs are dropped on the floor on the client-side. In the case of TLS 1.3, those parameters are available within the `Certificate` on the `sessionStateTLS13` provided to the client, but just currently aren't being used. In the case of TLS 1.2, those parameters aren't included in the session state at all, since the certificates are just passed along as raw bytes. So fixing this for TLS 1.2 and earlier versions will require an update to the `sessionState` structure.

This will be particularly relevant now that 1.15 will include a [VerifyConnection callback](https://tip.golang.org/pkg/crypto/tls/#Config) on the [ConnectionState](https://tip.golang.org/pkg/crypto/tls/#ConnectionState), which devs will use to access the OCSP responses and SCTs and do any necessary verification against them. Fixing this would be a stabilization fix for that new feature to align with user expectations.

/cc @FiloSottile

**Comment by rolandshoemaker** [comment]
@katiehockman I'd be interested in taking a crack at this, but don't want to tread on your toes if you're already working on it/planning on it.

**Comment by katiehockman** [comment]
Go for it! The earliest I would work on it would be the week of May 25, so if you beat me to it then great :)

I'll go ahead and assign it to you for now, and if needed can assign it back to myself later on.

**Comment by FiloSottile** [comment]
@rsc @golang/osp-team I'd like to ask for a freeze exception to land this fix. The bug is old in the context of Conn.ConnectionState, but the same structure is now passed to the (new in Go 1.15) VerifyConnection callback. Landing VerifyConnection without this fix will make the former not work correctly in the affected scenarios. The CL is ready and pretty safe.

**Comment by rsc** [comment]
CL and rationale looks good to me. Approved.
