### ISSUE TITLE
modules: replace directive with moved dependency not working consistently

### ISSUE THREAD

**Issue by dominicbarnes** [golang/go#39081]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dominic/.cache/go-build"
GOENV="/home/dominic/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="github.com/segment*"
GONOSUMDB="github.com/segment*"
GOOS="linux"
GOPATH="/home/dominic/dev"
GOPRIVATE="github.com/segment*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/dominic/Desktop/go-modules-bug/go.mod"
CGO_CFLAGS="-I/home/dominic/src/db2/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/home/dominic/src/db2/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build523802799=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

My project is using a dependency ([bitbucket.org/phiggins/db2cli](https://bitbucket.org/phiggins/db2cli)) that has a test package with another dependency ("odbc") which has recently moved from [Google Code](https://code.google.com/archive/p/odbc/) to [Github](https://github.com/alexbrainman/odbc).

#### main.go
```go
package main

import _ "bitbucket.org/phiggins/db2cli"

func main() {}
```

#### go.mod
```
module bug-report

go 1.14
```

Since this dependency isn't a direct one, I'm still able to run many commands (eg: `go mod vendor`, `go test`) without any trouble. However, upon trying to run `go mod tidy`, I get the following error:

```
go: finding module for package code.google.com/p/odbc
bug-report imports
	bitbucket.org/phiggins/db2cli tested by
	bitbucket.org/phiggins/db2cli.test imports
	code.google.com/p/odbc: cannot find module providing package code.google.com/p/odbc: unrecognized import path "code.google.com/p/odbc": parse https://code.google.com/p/odbc?go-get=1: no go-import meta tags ()
```

Once I realized this was a moved dependency, I addressed this with the following `replace` directive in my `go.mod`:

```
replace code.google.com/p/odbc => github.com/alexbrainman/odbc latest
```

Unfortunately, `go mod tidy` still does not work fully, though as far as I understand the `replace` directive is what should be used to resolve such an issue.

### What did you expect to see?

I would expect the `replace` directive to allow `go mod tidy` to continue working, notably to prune unused dependencies.

### What did you see instead?

Running `go mod tidy` prints this error just before exiting with error code 1:

```
go: github.com/alexbrainman/odbc@v0.0.0-20200426075526-f0492dfa1575 used for two different module paths (code.google.com/p/odbc and github.com/alexbrainman/odbc)
```

Consequently, `go mod tidy` no longer prunes unused dependencies. On a related note, the command `go mod why` prints this same error and also fails to work as designed.

**Comment by seankhliao** [comment]
an unfortunate consequence of the way modules work

the odbc package declares it's module name as `github.com/alexbrainman/odbc` [here](https://github.com/alexbrainman/odbc/blob/master/go.mod) but was required as `code.google.com/p/odbc` in your dependency and in your replace

I believe the only correct fix is to update the dependency to use the new path (or since it appears inactive, fork the repo and fix it yourself)

**Comment by bcmills** [comment]
See also #26904.

**Comment by cagedmantis** [comment]
@dominicbarnes I'm going to mark this as a duplicate issue and close it since there is already an existing issue #26904. Please feel free to follow up if you feel this issue was closed in error.
