### ISSUE TITLE
Convert nano time to string return garbage?

### ISSUE THREAD

**Issue by proyb6** [golang/go#39089]
### What version of Go are you using (`go version`)?
1.14.3

### Does this issue reproduce with the latest release?
I think earlier may have the same issue, I have checked other repos have used the same approach.

### What operating system and processor architecture are you using (`go env`)?
NA

### What did you do?

Converting nano time to string

```fmt.Println(string(time.Now().UnixNano()))```

### What did you expect to see?

As expected number return by nano time.

### What did you see instead?
A question mark character

https://play.golang.com/p/7NfnDfYy4_N

**Comment by acln0** [comment]
string(x) doesn't do what you think it does when x is an integer. It interprets x as a unicode code point and creates a string with the UTF-8 encoding of said code point, if possible. For your particular case, it isn't possible, so you get an encoding of unicode.ReplacementChar instead: https://play.golang.org/p/qLfoV6dj_AK

To format an integer into a string, use the fmt or strconv package.
