### ISSUE TITLE
query (LINQ) library for Go.

### ISSUE THREAD

**Issue by liuguijunhao** [golang/go#39090]
### What version of Go are you using (`go version`)?

<pre>
$ go 1.14+
</pre>

What did you do?
Supports arrays, slices, maps, strings, channels and custom collections
General Fast Iterative Query，and Simple 、easy

Example .net(c#) :
  query := from s in collections   where c.courseName == "history" select s.stuName
  fmt.Printf(query , collections)

**Comment by ALTree** [comment]
Hi,

this is a dup of  #32926. See in particular https://github.com/golang/go/issues/32926#issuecomment-508220574. There's not enough details here to qualify as a proposal.
