### ISSUE TITLE
x/exp/cmd/gorelease: output all errors for bad filenames in module

### ISSUE THREAD

**Issue by myitcv** [golang/go#39091]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +881d540540 Thu May 14 21:41:46 2020 +0000 linux/amd64
$ git rev-parse HEAD
00229845015e38294862ecd9909318241789d41c
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/myitcv/gostuff/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
GOAMD64="alignedjumps"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/golang.org/x/exp/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build883487326=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Ran the following test:

```
mod=example.com/patherrors
dir=x
base=none
success=false
-- want --
-- .mod --
module example.com/patherrors
-- .git/HEAD --
-- x/go.mod --
module example.com/x

go 1.12
-- x/testdata/don't_call_file_this_1.txt --
-- x/testdata/don't_call_file_this_2.txt --
```

### What did you expect to see?

Two errors relating to bad file names.

### What did you see instead?

One error:

```
$ go test ./...
--- FAIL: TestRelease (0.00s)
    --- FAIL: TestRelease/patherrors/bad_filenames (0.00s)
        gorelease_test.go:292: unexpected error: create zip /tmp/673926975/x: malformed file path "testdata/don't_call_file_this_1.txt": invalid char '\''
FAIL
FAIL    golang.org/x/exp/cmd/gorelease  1.709s
FAIL
```

cc @jayconrod

**Comment by jayconrod** [comment]
Blocked by #36058
