### ISSUE TITLE
Error comparisons in templates not working until 1.14

### ISSUE THREAD

**Issue by timlind** [golang/go#39108]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13
</pre>

### Does this issue reproduce with the latest release?

No.

### What operating system and processor architecture are you using (`go env`)?

This is erroring on google app engine 1.13 and locally on 1.13, but not on 1.14

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
````
data := struct{
   Errors []error
   KnownErrors map[string]error
}{
   []error{ErrEmailExists},
   map[string]error{ErrEmailExists}
}

template.Execute(w, data)

{{range .Errors}}
{{if eq . $.KnownErrors.ErrEmailExists}}
Already registered.
{{end}}
{{end}}

````
### What did you expect to see?

Already registered.

### What did you see instead?

error calling eq: invalid type for comparison

**Comment by ALTree** [comment]
This is expected. A proposal to make `eq` support al comparable types (#33740) was accepted and the fix merged for Go1.14. So it won't work in go1.13, but it does on 1.14. 

I don't think the change qualifies for a backport (we only backport fixes for serious security issues or problems with no workaround), so I'm not sure there's anything else left to do. I'm closing this issue a Working As Intended, but feel free to comment if you disagree.

**Comment by timlind** [comment]
Maybe some pointers to a workaround if there is one? Even trying to call and compare Error seemed to fail.

**Comment by timlind** [comment]
Ok, just tried it out on a playground and .Error comparisons work fine.
