### ISSUE TITLE
improve error massage output style

### ISSUE THREAD

**Issue by kolokd** [golang/go#39112]
like how gcc does it.
compiler error massage in go is hard to understand and the compiler doesn't give any hint

**Comment by ianlancetaylor** [comment]
Thanks, but this issue is too vague to be useful.  Please tell us exactly what you did, exactly what happened, and what you expected to happen instead.  Thanks.

**Comment by kolokd** [comment]
i just started learning go.
if i forget to type ; in c gcc tells me to add a ; and where to add it in the terminal.
but if i place { in a new line go doesn't say that i should remove the newline.

**Comment by ianlancetaylor** [comment]
Thank you, but in order for us to make it better, we really need to see your exact program and your exact error message.  You know exactly what you are doing.  We have to guess, and experience tells me that we will guess wrong and will fix the wrong problem.  Please help us make Go better by telling us exactly what you are doing and exactly what you see.  Thanks.

**Comment by kolokd** [comment]
sorry as english isn't my native lang i am unable to explain it properly.
just take a look at the output style of gcc and compare it with go. 
gcc's output is more user friendly. i get error message and some advise how to fix it. 

if i put { on a newline go says missing function body. but there is a function body is available. but it can't see it.

**Comment by kolokd** [comment]
go damn github. why it doesn't have monospace font for comments on issue.

**Comment by kolokd** [comment]
why even golang use github. it's a proprietary software. golang could use selfhosted gitlab. everything nice and easy.

**Comment by ianlancetaylor** [comment]
Thanks for filing the issue.  Closing in the absence of additional information.

For questions about Go please see https://golang.org/wiki/Questions.
