### ISSUE TITLE
proposal: Go 2: Better C FFI performance! (Discussion)

### ISSUE THREAD

**Issue by phtdacosta** [golang/go#39115]
I just started learning Go as my job requires to, but as a _quite_ seasoned C programmer, I've checked lots of articles pointing out Go's C FFI poorer performance when compared with Rust's C FFI for example.

Maybe it is due the fact that Go has GC? Would disabling Go's GC help this inter-operation with C?

I am afraid I did not find any proposal related to that, so I would like to leave this point here, and at least, I can learn myself something I forgot to mention in my observation. Thank y'all, in overall, Go is awesome.

**Comment by martisch** [comment]
I dont think anybody is opposed to having better C calling performance. For a proposal however this need to explain concretely how this would be achieved. Disabling GO Gc is not an option as this would run programs out of memory.

To discuss ideas please use the forums:  https://golang.org/wiki/Questions
Once there is a more concrete proposal how to improve performance feel free to open a new issue. The proposal as currently stated has no actionable content.
