### ISSUE TITLE
Go 1.14 makes the file read-only using ioutil.writefile ("d:/test.txt", []byte("data"), os.modeappend)

### ISSUE THREAD

**Issue by xunxinyuan** [golang/go#39125]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.14
1.14.3
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Develop\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Develop\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build038315006=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
Go 1.12 And 1.13 is OK

### What did you expect to see?
Do not modify file properties

### What did you see instead?
Go 1.14.x makes the file read-only using ioutil.writefile ("d:/test.txt", []byte("data"), os.modeappend)
Go 1.12 & 1.13 is OK
OS ： Windows10

**Comment by martisch** [comment]
What is the full program?

```
func main() {
   ioutil.WriteFile("d:/test.txt", []byte("data")
}
```

Does the file exist before? With which permissions?

**Comment by bcmills** [comment]
Per https://golang.org/doc/go1.14#windows:

> On Windows, creating a file via [`os.OpenFile`](https://golang.org/pkg/os#CreateFile) with the [`os.O_CREATE`](https://golang.org/pkg/os/#O_CREATE) flag, or via [`syscall.Open`](https://golang.org/pkg/syscall#Open) with the [`syscall.O_CREAT`](https://golang.org/pkg/syscall#O_CREAT) flag, will now create the file as read-only if the bit `0o200` (owner write permission) is not set in the permission argument. This makes the behavior on Windows more like that on Unix systems.

`os.ModeAppend` does not set *any* permission bits, so you are requesting a file that cannot be read, written, or executed, and `ioutil.WriteFile` is giving you as close to that as it can on Windows.

**Comment by alexbrainman** [comment]
Dup of #38225 ?

Alex
