### ISSUE TITLE
why not get the method using reflect

### ISSUE THREAD

**Issue by mlboy** [golang/go#39126]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.13.8 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

```golang
package main

import (
	"fmt"
	"reflect"
)

type t1 struct{}

func (t *t1) Name() string {
	return "tbl_t1"
}
func main() {
	m := t1{}
	rv := reflect.ValueOf(m)
	fn := rv.MethodByName("Name")
	fmt.Println(fn)
        // <invalid reflect.Value> ??????
}
```

why not get the method ?

keep 2 point : 
![image](https://user-images.githubusercontent.com/1733903/82203690-33872500-9936-11ea-818f-60e5f44fc8b5.png)

**Comment by D1CED** [comment]
You have to use `m := &t1{}`, because the method is declared on the pointer.

**Comment by martisch** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For asking questions, see: https://github.com/golang/go/wiki/Questions
