### ISSUE TITLE
x/tools/internal/lsp/regtest: test output is much too verbose

### ISSUE THREAD

**Issue by bcmills** [golang/go#39130]
### What version of Go are you using (`go version`)?

<pre>
~/src/golang.org/x/tools$ go version
go version devel +810c27e9be Wed May 13 11:59:26 2020 +0000 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
~/src/golang.org/x/tools$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/local/google/home/bcmills/.cache/go-build"
GOENV="/usr/local/google/home/bcmills/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/usr/local/google/home/bcmills/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/local/google/home/bcmills"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/google/home/bcmills/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/google/home/bcmills/go/pkg/tool/linux_amd64"
GCCGO="/usr/local/google/home/bcmills/bin/gccgo"
GOAMD64="alignedjumps"
AR="ar"
CC="gcc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/usr/local/google/home/bcmills/src/golang.org/x/tools/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build713277181=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```
~/src/golang.org/x/tools$ git fetch "https://go.googlesource.com/tools" refs/changes/12/234112/3 && git checkout FETCH_HEAD

~/src/golang.org/x/tools$ go test ./internal/lsp/regtest >regtest.txt

~/src/golang.org/x/tools$ du -h regtest.txt
108K    regtest.txt
```

### What did you expect to see?

A comprehensible, human-readable report of test failures, along with a small amount of contextual information relevant to those failures.

### What did you see instead?

108 KiB of unfiltered logs that appear to be mostly irrelevant to the actual test case that failed.

It appears that something within the test is piping all output of subprocesses directly to `os.Stdout` or `os.Stderr`, rather than saving the output to a buffer and using `t.Logf` or similar to associate the buffered logs with a specific test case.

CC @findleyr @stamblerre @ianthehat

**Comment by findleyr** [comment]
I agree, though some of this output was added to help diagnose hard-to-reproduce flakes:
 - gopls RPC logs
 - goroutine profile

I'll see if there's somewhere else I can write these artifacts.
