### ISSUE TITLE
x/build/devapp/owners: some entries show up as "@" in rendered HTML

### ISSUE THREAD

**Issue by dmitshur** [golang/go#39132]
From https://dev.golang.org/owners:

<img width=448px src=https://user-images.githubusercontent.com/1924134/82246744-40dee800-9913-11ea-8708-1e99b7b945be.png>

The "@" links point to https://github.com.

This looks related to [CL 230077](https://golang.org/cl/230077). /cc @stamblerre @andybons

**Comment by stamblerre** [comment]
Yep, looks like the @ are all of the tools team owners. I guess something is looking for a GitHub username for the group. Maybe I can create a GitHub group for the tools team and link to it?
