### ISSUE TITLE
x/pkgsite: inconsistent imported by numbers

### ISSUE THREAD

**Issue by dotchev** [golang/go#39138]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/search?q=mux 
https://pkg.go.dev/github.com/gorilla/mux?tab=doc
 
### What is your user agent?
 
Google Chrome Version 81.0.4044.138 (Official Build) (64-bit)
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/4962228/82291232-4b4fbf00-99b1-11ea-981d-e26aab60b70a.png)
 
![image](https://user-images.githubusercontent.com/4962228/82291320-71755f00-99b1-11ea-8416-643441c8ee89.png) 
 
### What did you do?
 
Searched for "mux" in pkg.go.dev
 
### What did you expect to see?

Expected Imported by numbers in the search result and in the package page to be the same 
 

### What did you see instead?

Different Imported by numbers for the same package - 9381 vs 12162

**Comment by julieqiu** [comment]
Thanks for the feedback! We'll look into this.
