### ISSUE TITLE
proposal, go/cmd: go build -o existing_dir_name should show an error

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [golang/go#39145]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gmikhalkin/.cache/go-build"
GOENV="/home/gmikhalkin/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/gmikhalkin/.gvm/pkgsets/go1.14.3/global"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/gmikhalkin/.gvm/gos/go1.14.3"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/gmikhalkin/.gvm/gos/go1.14.3/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/gmikhalkin/Projects/feature_toggle_management/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build894912669=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Project structure:
```
/project_name
    /app
    main.go
```

If run `go build -o app .`, it will create executable `project_name` in `app` directory

### What did you expect to see?
Some kind of error message, that would say that there's already directory with such name.

**Comment by mvdan** [comment]
Did you see `go help build`?

> The -o flag forces build to write the resulting executable or object to the named output file or directory

Changing this would mean changing the documented behavior, and likely breaking many users.

**Comment by GrigoriyMikhalkin** [comment]
I see, missed that. Closing the issue then
