### ISSUE TITLE
how to use pluginpath in golang 1.13 or golang 1.14

### ISSUE THREAD

**Issue by ztgameming** [golang/go#39142]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/zhangyinming/goproject"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/root/zhangyinming/goBin/go1.14/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/zhangyinming/goBin/go1.14/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/zhangyinming/securityProject/packServer/apk-pack-server/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build258459112=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

	I use plugin mode to build a dynamic library with custom definition pluginpath,but when load in another program it display can't find the symbol.  It works weel in golang 1.12.

        go build -buildmode=plugin --ldflags="-pluginpath=plugin_version_1" -o server01.so exported.go
 	plugin.Open("soDir/server01"): could not find symbol Init: /mydir/soDir/server01.so: undefined symbol: plugin_version_1.Init

### What did you expect to see?
	 should load normal

### What did you see instead?
	nothing

**Comment by cagedmantis** [comment]
Could you provide an example of the code that produced the error?

**Comment by folivora-ice** [comment]
> Could you provide an example of the code that produced the error?
I also encountered the same problem
this is my directory structure:
```
test/
  - main.go
  - go.mod
  - plugins/
    - helloworld/
      - main.go
```
```golang
// test/plugins/helloworld/main.go

package main

import (
	"fmt"
)

func init() {
	fmt.Println("plugin hello has been loaded")
}

func Hello(name string) {
	fmt.Println("Hello " + name)
}
```
```golang
// test/main.go
package main

import (
	"fmt"
	"plugin"
)

func getPluginMethod(pluginPath, method string) (interface{}, error) {
	plugin, err := plugin.Open(pluginPath)
	if nil != err {
		return nil, err
	}

	return plugin.Lookup(method)
}

func main() {
	fmt.Println("begin main")

	helloSymbol, err := getPluginMethod("./lib/hello.so", "Hello")
	if nil != err {
		fmt.Println(err.Error())
		return
	}
	hello, ok := helloSymbol.(func(name string))
	if !ok {
		fmt.Println("hello must be func(string)")
		return
	}

	hello("World")
}
```
> **build command**
    
    go build -o lib/hello.so --buildmode=plugin --ldflags="-pluginpath=hello" test/plugins/helloworld

**Comment by RaynorGu** [comment]
@ztgameming  @folivora-ice did you solve this problem, How can I solve it?

**Comment by YankunLi** [comment]
@ztgameming @folivora-ice  did you solve this problem, How can I solve it?

**Comment by YankunLi** [comment]
@ztgameming @folivora-ice  did you solve this problem, How can I solve it?

**Comment by YIDWang** [comment]
The same question in go version go1.17.9 darwin/amd64

**Comment by ray2011** [comment]
> The same question in go version go1.17.9 darwin/amd64

dont use pluginpath option,  just copy code to different directory.
