### ISSUE TITLE
question: why Go uses github?

### ISSUE THREAD

**Issue by kolokd** [golang/go#39141]
Github is a proprietary software. 

Go could use gitlab or self hosted gitlab like Gnome does.

This issue needs to be addressed. 
please don't close this issue without proper answer. 
I want answer from core team.

Thanks.

**Comment by mvdan** [comment]
I can sympathize with the intent, and I would also strongly prefer open source, but note that this happened six years ago. You should read that thread first: https://groups.google.com/forum/#!topic/golang-dev/sckirqOWepg%5B1-25%5D

**Comment by ALTree** [comment]
Note that the github repository is just a mirror. 

The actual canonical repository is the one at https://go.googlesource.com/go/, which AFAIK is hosted by google and served using gitiles, [which is open source](https://gerrit.googlesource.com/gitiles/). 

The main contribution channel is sending patches via gerrit (https://go-review.googlesource.com/), which, again, is open source. Github is not involved.

The only piece of github closed-source code that the project uses is the issue tracker, I believe.

**Comment by mdlayher** [comment]
While I understand your concern, the Go issue tracker is not used for questions and you will likely be able to find and/or discuss an answer on a mailing list such as golang-nuts.

Closing per https://github.com/golang/go/wiki/Questions.

**Comment by kolokd** [comment]
the amount of time i used github, In my opinion github is a totally stupid website. Both design and engineering.
