### ISSUE TITLE
x/build/cmd/coordinator: run TryBots for older versions of Go on x/tools

### ISSUE THREAD

**Issue by stamblerre** [golang/go#39159]
`gopls` needs to have a more lenient policy than https://golang.org/doc/devel/release.html#policy, since it's fairly common for users to remain on older versions of Go and continue requiring an editor.

We have historically broken `gopls` support for older Go versions (https://github.com/golang/go/issues/39146) because TryBots with older Go versions do not run on x/tools. We are still undecided on how many Go versions to go back, but we do need this support.

I'm happy to set this up myself, but I just wanted to file this issue in case there are any problems with this.

**Comment by stamblerre** [comment]
@dmitshur has just brought to my attention that the builders don't support Go versions before 1.13 currently, so we'd need to add that support first. Our current thinking is to support 2 years back, so Go 1.11 - present. We'd probably only need one Linux builder for each version, much like the Go 1.13 builder that runs now.

/cc @cagedmantis @toothrot

**Comment by dmitshur** [comment]
As @stamblerre mentioned above (I was too slow to comment), we should consider how this would affect the support window for builders, if at all. At this time, we're able to stop supporting a builder that was needed for version Go 1.n as soon Go 1.n+2 is released. We don't always make use of this ability, but it enables to reduce maintenance costs sometimes.

Some builders are less expensive/difficult to maintain than others. The Linux builder is one of the least difficult builder types to maintain and keep available for longer.

I understand your current proposal is to make the `linux/amd64` builder for Go 1.n available for the x/tools repository until Go 1.n+4 is released. Given there will be no more changes to release branches of those old Go versions, I don't foresee much additional maintenance that would need to be done to keep the builder operational, so this seems reasonable. I welcome thoughts from others.

Also /cc @andybons.

**Comment by stamblerre** [comment]
> **Edit:** I'll bring this up with the release team and discuss more with them.

Thanks @dmitshur! I know how to write the code for this, but I guess it would have to wait until the infrastructure is there. Maybe, to start, we can add syntax to trigger TryBots for a specific version of Go manually (or does this already exist?). We will need this support before we make any progress on https://github.com/golang/go/issues/39146, since without it, we're bound to regress.

**Comment by stamblerre** [comment]
The CI that @findleyr setup (https://github.com/golang/go/issues/39146#issuecomment-662140260) has proven to be sufficient for this. I don't think we need this any longer, so closing.
