### ISSUE TITLE
database/sql: collect database metric information using dbstats 

### ISSUE THREAD

**Issue by 4orty** [golang/go#39161]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.14

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
windows/amd64
</pre></details>

### What did you do?

Purpose: I want to get database metric information in go application.
So here is a source code.

db, err := sql.Open("postgres", connectionInfo)

dbstat := db.Stats()
db.SetMaxOpenConns(20)
fmt.Println(dbstat.MaxOpenConnections)

### What did you expect to see?

I expected the printed number is 20

### What did you see instead?

The result of the code was 0 (default value)

When i took a look at dbstat struct, I realized that all the type of field assigned int or string, not pointer. 
Is there any problem that change fields of DBstat struct to pointer value?
If it assigned pointer value, it seems like can collect database metric information in real time.

**Comment by seankhliao** [comment]
`db.Stats()` should be called when you need the data,
this is the same as the other metrics exposed by the stdlib, ex in `runtime`

having unprotected pointers to mutable data races possible

**Comment by cagedmantis** [comment]
As mentioned by @seankhliao, `db.Stats()` should be called at the point when you are ready to collect the data. It should not be able to mutate the state of `DB`.

I'm going to close this issue since this is working as expected. Please feel free to follow up if this was done in error.

**Comment by 4orty** [comment]
@cagedmantis  Thanks for reply. If i want to collect DB metrics every second, is it ok to call db.Stats() every second?
