### ISSUE TITLE
testing: rename t.TempDir to t.Mkdir

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#39169]
The originally proposed name for `testing.T.TempDir` was `Mkdir`. The name was changed during the proposal process. There has been [some confusion](https://github.com/golang/go/issues/38850#issuecomment-630963753) about the intended semantics: is it more like `ioutil.TempDir` or `os.TempDir` ?

To avoid the confusion, I suggest that we use the originally proposed name, `Mkdir`. It's then very clear that the method is creating a new directory. The fact that the method has no arguments is a clear indication that the directory name is chosen by the method itself rather than by the caller.

**Comment by rsc** [comment]
Mkdir does not convey "this is temporary". (It's not ioutil.Mkdir.) Let's leave it as TempDir. I understand the conflict with os.TempDir, but more people know about ioutil.TempDir anyway. Thanks.

**Comment by rogpeppe** [comment]
Fair enough. Will close.
