### ISSUE TITLE
go\src\gonum.org\v1\gonum\lapack\gonum\lapack.go:39:15: syntax error: unexpected p, expecting semicolon or newline or )

### ISSUE THREAD

**Issue by iamapickle** [golang/go#39162]
### What version of Go are you using (`go version`)? 

<pre>
$ go version
1.11.1

</pre>

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\AppData\Local\Temp\go-build643855302=/tmp/go-build -gno-record-gcc-switches

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do? go get github.com/go-gota/gota/dataframe
and go get github.com/sjwhitworth/golearn/trees

###Everytime, i try to install a package from Github i get the error as mentioned in title. Irrespective of which package it is, almost all packages i'm trying to get from Github are giving this error.

**Comment by kortschak** [comment]
The current version of Gonum requires at least Go 1.13.

**Comment by iamapickle** [comment]
> The current version of Gonum requires at least Go 1.13.

thanks

**Comment by agnivade** [comment]
Closing, as this is not a Go bug.
