### ISSUE TITLE
os: Symlink on Windows with a to-be-created directory path silently creates a link of the wrong type

### ISSUE THREAD

**Issue by bcmills** [golang/go#39183]
(Discovered via debugging on #38772.)

### What version of Go are you using (`go version`)?

<pre>
gopher@SERVER-2016-V7- C:\workdir\go\src>..\bin\go version
go version devel gomote.XXXXX windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
gopher@SERVER-2016-V7- C:\workdir\go\src>..\bin\go version
go version devel gomote.XXXXX windows/amd64

gopher@SERVER-2016-V7- C:\workdir\go\src>..\bin\go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\gopher\AppData\Local\go-build
set GOENV=C:\Users\gopher\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\gopher\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\gopher\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\workdir\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\workdir\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set GOAMD64=alignedjumps
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\workdir\go\src\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=
C:\Users\gopher\AppData\Local\Temp\go-build141789646=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

```
	err := os.Symlink(to, from)
	if err != nil {
		t.Fatalf(…)
	}

	err = os.Mkdir(to, 0755)
	if err != nil {
		t.Fatalf(…)
	}

	…

	file, err := os.Open(from)
	if err != nil {
		t.Fatalf(…)
	}
	file.Close()
```

[CL 234737](https://golang.org/cl/234737) contains a complete example.

### What did you expect to see?

Either a non-nil error from the call to `os.Symlink`, or a successful call to `os.Open`.

### What did you see instead?

```
gopher@SERVER-2016-V7- C:\workdir\go\src>..\bin\go test os -run=TestSymlink.*
--- FAIL: TestSymlinkBeforeTargetFileExists (0.00s)
    os_test.go:908: Open("earlysymlinktestfrom") failed: open earlysymlinktestfrom: Access is denied
.
FAIL
FAIL    os      0.052s
FAIL
```

### Diagnosis

The Windows `CreateSymbolicLinkA` system call requires a flag to indicate whether the destination is a file or a directory. (If `SYMBOLIC_LINK_FLAG_DIRECTORY` is set, the symlink is a directory symlink; otherwise, it is a file symlink.)

The current implementation of `os.Symlink` on Windows uses a call to `os.Stat` to determine which kind of link to create. Unfortunately, if that `Stat` call fails, `Symlink` assumes that it is a file rather than reporting the error to the caller:
https://github.com/golang/go/blob/567556d78657326c99b8fa84ec2a5ee511a0941b/src/os/file_windows.go#L337-L338

That assumption seems like a mistake. If a Windows user needs to create a symlink to a not-yet-existing file or directory on Windows, they should be made aware that the call is missing essential information (the destination type), and can then make an explicit choice to use [`golang.org/x/sys/windows.CreateSymbolicLink`](https://pkg.go.dev/golang.org/x/sys/windows?tab=doc#CreateSymbolicLink) instead of `os.Syscall` if they are able to supply the missing information.

I think we should change `os.Symlink` at the beginning of the Go 1.16 cycle so that it propagates the `Stat` error instead of implicitly assuming that the destination is a file.

CC @fraenkel @alexbrainman @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Sounds right to me, alas.

**Comment by alexbrainman** [comment]
> That assumption seems like a mistake.

I don't see why it is mistake.

> If a Windows user needs to create a symlink to a not-yet-existing file or directory on Windows, they should be made aware that the call is missing essential information (the destination type),

Sure. It is nice to have this information. But I don't see how you can provide information about the file / directory that has not been created yet.

> and can then make an explicit choice to use [`golang.org/x/sys/windows.CreateSymbolicLink`](https://pkg.go.dev/golang.org/x/sys/windows?tab=doc#CreateSymbolicLink) instead of `os.Syscall` if they are able to supply the missing information.

I don't see what you are proposing here. Please try again.

> I think we should change `os.Symlink` at the beginning of the Go 1.16 cycle so that it propagates the `Stat` error instead of implicitly assuming that the destination is a file.

It looks like Windows CreateSymbolicLink API succeeds without target file or directory, I don't see why we should second guess API intentions and fail `os.Symlink`.

/cc @mattn since he loves symlinks

Alex

**Comment by mattn** [comment]
os.Symlink should return normal when the target does not exist. As you say, because Windows symbolic link itself has an attribute (file or directory), I feel that it is nonsense to change it dynamically or to make an empty directory. It is also not atomic. I feel that adding new Symlink or SymlinkTo, which allows us to specify attributes in x/sys/windows, is sufficient. The current os.Symlink is returning a proper error.

It's not possible to simulate all UNIX behavior on Windows perfectly.

**Comment by bcmills** [comment]
@mattn 
> The current os.Symlink is returning a proper error.

No, it isn't — and that's the point. `os.Symlink` is returning `nil` (indicating successful creation of the link); the error in the test comes from the subsequent `os.Open` attempting to read through the link.

**Comment by bcmills** [comment]
@alexbrainman 

> I don't see what you are proposing here. Please try again.

I am proposing that:
* When the target does not exist, `os.Symlink` on Windows should return an explicit error (instead of creating a file-only symlink and returning a nil error).
* When the target does exist, `os.Symlink` on Windows should create a link of the corresponding type (as it does today).

That will eliminate false-negative (nil) returns for symlinks to _directories_ that do not yet exist, at the cost of some false-positive (error) returns for symlinks to _files_ that do not yet exist. However, if the user knows that the link target will eventually be a file, they can use `CreateSymbolicLink` directly to eliminate the false-positive errors.

I believe that the majority of calls to `os.Symlink` are for targets that _do_ exist, regardless of type, so I expect the number of false-positive errors in practice to be low.

> It looks like Windows CreateSymbolicLink API succeeds without target file or directory,

That is correct.

> I don't see why we should second guess API intentions and fail `os.Symlink`.

The API of `os.Symlink` is narrower than `CreateSymbolicLink`. When the link target does not exist, `CreateSymbolicLink` receives an extra bit of explicit information that `os.Symlink` lacks: the intended type of the link target, passed as a flag to `CreateSymbolicLink` but not available to `os.Symlink`.

**Comment by bcmills** [comment]
Heh, my investigation into a fix uncovered a related bug for symlinks starting with a slash or backslash (#19937). We were invoking `Stat` on the wrong path for those, but the bug was masked by the error never being surfaced.

`isAbs` returns `false` for such a path, but it is not appropriate to prefix the destination for such a path as we do today:
https://github.com/golang/go/blob/567556d78657326c99b8fa84ec2a5ee511a0941b/src/os/file_windows.go#L331-L335

**Comment by bcmills** [comment]
https://golang.org/cl/234879 contains the proposed fix. I think it is telling that none of the test fixes required falling back to `CreateSymbolicLink`, although that may be necessary for a few test fixes in the `x/` repos.

**Comment by networkimprov** [comment]
The proposed change would break my app. I create symlinks to non-existent files to implement reliable storage when creating a new file. 

Bryan, why shouldn't your use case use x/sys/windows to do this?

**Comment by bcmills** [comment]
@networkimprov, if you know that you are creating symlinks to nonexistent files or directories on Windows, then it is indeed possible to use `x/sys/windows` to create them; see https://go-review.googlesource.com/c/tools/+/234112/9/go/packages/packagestest/export_windows.go.

We could consider an alternate change instead: fix the relative-link bug, but change the _documentation_ for `os.Symlink` to describe the current behavior of creating file-only symlinks when `oldpath` does not yet exist. That would maintain support for your Windows-specific use-case, but allow more bugs in portable programs to go undetected, or to be detected only arbitrarily later during execution (at `Open` rather than `Symlink`).

On balance, I prefer making code that relies on Windows-specific behavior use a Windows-specific system call explicitly, and returning an error for portable programs when `os.Syscall` is unable to provide portable behavior.

**Comment by networkimprov** [comment]
I also ship my app on MacOS & Linux; it works the same there. I never create files for those symlink targets; the symlinks are placeholders that are removed after the temp file for a new file is fsync()'d.

It's not common to create __any__ symlinks in apps that run on Windows, because it requires Admin privs on Win7. What's your scenario that needs symlinks to future directories?

**Comment by bcmills** [comment]
@networkimprov, for the code from which this issue was discovered, it is possible to restructure the code to avoid creating symlinks to nonexistent directories. However, discovering the current “assume file” behavior as the source of the bug was quite difficult due to the lack of error-reporting. It is the lack of error-reporting that needs to be fixed, not the inability to create dangling symlinks.

**Comment by bcmills** [comment]
The fact that an arbitrary 50/50 guess happens to work for your program does not make it appropriate for `os.Symlink` to make an arbitrary 50/50 guess.

**Comment by networkimprov** [comment]
Could os.Open() correctly report the cause of the failure? "Access denied" isn't "File/Path not found". Maybe it could Stat() the filename on access-denied.
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/

Go on Windows has a variety of filesystem glitches, including:
Rename/Remove() of open files,
FileInfo.Sys() missing fileId,
RemoveAll() with long names down-tree, and
bad syscall.Errno mappings.

I've resorted to patching the stdlib locally. C'est la Go.

**Comment by bcmills** [comment]
Even if we changed `os.Open` to try to better diagnose symlinks of the wrong type, that wouldn't make those symlinks any less mysterious if read by non-Go programs.

**Comment by networkimprov** [comment]
If your Go program calls the filesystem, it must test that on __every OS__ it supports. This problem is easy to surface, as (IIUC) any attempt to treat a symlink-to-file as a directory yields access-denied, regardless of whether the target exists.

Were it my call, I'd add `os.SymlinkNowhere(p string, t SymlinkType)`. That would make changing the current behavior worth considering. Failing that, I'd say we should simply document this for os.Symlink() and add it to the list of GOOS=windows filesystem glitches.

Sadly, even in Win10, you have to enable "Developer Mode" to create symlinks without admin privs, so they'll probably remain uncommon on Windows.
https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinka

cc @jstarks in case John has any thoughts...

**Comment by alexbrainman** [comment]
@bcmills 

> > I don't see why we should second guess API intentions and fail `os.Symlink`.
> 
> The API of `os.Symlink` is narrower than `CreateSymbolicLink`. When the link target does not exist, `CreateSymbolicLink` receives an extra bit of explicit information that `os.Symlink` lacks: the intended type of the link target, passed as a flag to `CreateSymbolicLink` but not available to `os.Symlink`.

But that is not what symlinks created with CreateSymbolicLink API do. For example, they could point to a file on another volume / drive, and that drive might not be mounted all the time. It is obviously fine for symlinks point to non-existing file / directory.

Did you read

https://docs.microsoft.com/en-us/windows/win32/fileio/hard-links-and-junctions

?

Alex

**Comment by jstarks** [comment]
I don't have any creative solutions for this problem, unfortunately. We run into a similar issue when trying to determine what symlink type to create when creating symbolic links in WSL. If the target doesn't exist, or if the target type changes after creating the symlink, then we get it wrong. This breaks symlink accesses from Windows (but not from WSL since we interpret the symlinks there, ignoring the type flag).

Ideally we would change Windows to not require this distinction, but so far we don't think that's practical.

**Comment by bcmills** [comment]
@alexbrainman 

> But that is not what symlinks created with CreateSymbolicLink API do. For example, they could point to a file on another volume / drive, and that drive might not be mounted all the time. It is obviously fine for symlinks point to non-existing file / directory.

Yes. But they still need to point to the correct _type_ of non-existing target — a file (`0x0`), or directory (`SYMBOLIC_LINK_FLAG_DIRECTORY`) — which `os.Symlink` does not allow the caller to specify. The problem is that the `os.Symlink` API does not encode enough information to set that flag correctly for nonexistent targets. (The symlink _can_ be created with the correct flag by calling `CreateSymbolicLink` directly — but that requires information from the caller that `os.Symlink` does not receive.)

> Did you read
> https://docs.microsoft.com/en-us/windows/win32/fileio/hard-links-and-junctions

I don't think that document is relevant to this issue..? This issue is specifically about symbolic links, not junctions or hard-links. (I haven't checked whether an analogous bug exists for `os.Link`, but I have no reason to suspect that it would.)

**Comment by bcmills** [comment]
@networkimprov 

> This problem is easy to surface, as (IIUC) any attempt to treat a symlink-to-file as a directory yields access-denied, regardless of whether the target exists.

It is empirically easy to detect the _symptom_ of this problem (the `Access is denied` error) but it is difficult to trace that symptom to the underlying _cause_ — and all too tempting for someone unfamiliar with the nuances of Windows to dismiss the problem as “Windows is flaky” instead of “`os.Symlink` lied about creating a usable symlink”. The change I propose is to surface the problem at the call that introduces it, instead of deferring detection of the problem to potentially an entirely separate process that tries to consume the link down the line.

**Comment by bcmills** [comment]
@networkimprov 

> Were it my call, I'd add `os.SymlinkNowhere(old, new string, t SymlinkType)`. That would make changing the current behavior worth considering. Failing that, I'd say we should simply document this for `os.Symlink()` and add it to the list of `GOOS=windows` filesystem glitches.

`os.SymlinkNowhere` seems misnamed, because it would spuriously succeed even when `old` exists, or would incur needless extra overhead on all other platforms to ensure that the target does _not_ exist.

But to be honest I don't think we even need to expand the `os` API for this. In most cases, it is trivial to ensure that the link target exists (and is the correct type) before constructing the symlink, and the `os` package does not in general try to cover portability problems for unusual cases.

For the few programs that actually do need to create symlinks to nonexistent targets, `windows.CreateSymbolicLink` seems sufficient, and it's easy enough for users to write their own portable wrappers using `+build` constraints.

**Comment by networkimprov** [comment]
> it is difficult to trace that symptom to the underlying cause 

I did suggest documenting the cause!

Since you're proposing to _contract_ the os API, I don't see why expanding it is off the table :-) Go offers a lot of things from Unix that Windows can't do.

Anyway, you have my views, I'll stop repeating myself.

**Comment by bcmills** [comment]
Thinking about this some more: even if we decide to retain the current `os.Symlink` behavior for nonexistent targets, I think it is important that we change it to propagate `Stat` errors for which `os.IsNotExist` returns `false`.

Otherwise, it would be possible to successfully create a directory on a network share, then lose the connection to that share, then “successfully” create a symlink to that directory, and end up with a symlink that is still permanently broken once the share is reconnected.

**Comment by networkimprov** [comment]
Symlink currently proceeds even if Stat got an error on the target that's not IsNotExist(err)?

Sounds like a bug; in file utils, I always return an unexpected error, in case the filesystem is hosed!

**Comment by alexbrainman** [comment]
@bcmills 

> > But that is not what symlinks created with CreateSymbolicLink API do. For example, they could point to a file on another volume / drive, and that drive might not be mounted all the time. It is obviously fine for symlinks point to non-existing file / directory.
> 
> Yes. But they still need to point to the correct _type_ of non-existing target — ...

The target type can change after symlink is created. What do you propose to do about that?

The target can get deleted after symlink is created. What do you propose to do about that?

See this test https://play.golang.org/p/APh87cnpUgC - it works fine at this moment on both Linux and Windows. It will fail on Windows after your proposed change.

Symlinks currently work independent of their target - that is how they are designed. You propose to break that design to fix file / directory flag on Windows. I say it is not worth it. Linux has the same problem where symlink stops working when target is removed / does not exist. That is what everyone expects. I consider file / directory flag bug to be in the same boat as symlink pointing to non-existing target.

> > Did you read
> > https://docs.microsoft.com/en-us/windows/win32/fileio/hard-links-and-junctions
> 
> I don't think that document is relevant to this issue..? This issue is specifically about symbolic links, not junctions or hard-links. (I haven't checked whether an analogous bug exists for `os.Link`, but I have no reason to suspect that it would.)

I provided this document to point to hard links description. I do not know what you are building, but maybe you should use hard links instead. Hard links won't work without targets. That is what you want. Don't you?

> Thinking about this some more: even if we decide to retain the current `os.Symlink` behavior for nonexistent targets, I think it is important that we change it to propagate `Stat` errors for which `os.IsNotExist` returns `false`.
> 
> Otherwise, it would be possible to successfully create a directory on a network share, then lose the connection to that share, then “successfully” create a symlink to that directory, and end up with a symlink that is still permanently broken once the share is reconnected.

This is already happening now. Imagine you create symlink to a file, and then replace file with directory of the same name. We cannot do anything about it. Why should we worry about symlinks to be correct at the moment of their creation?

Alex

**Comment by bcmills** [comment]
> The target type can change after symlink is created. What do you propose to do about that?
>
> The target can get deleted after symlink is created. What do you propose to do about that?

I propose that functions should report a non-nil error when they do not have enough information to perform the operation that the user requested. If they have enough information to perform the operation, and do so successfully, then what happens afterward is irrelevant.

`os.Symlink`, as documented today, “creates `newname` as a symbolic link to `oldname`.”

On POSIX systems, `os.Symlink` does not need to report an error for missing targets, because the arguments passed to `os.Symlink` contain all of the information needed to construct a _working_ symbolic link to `oldname`, regardless of when `oldname` is created and with what type.

On Windows, the arguments passed to `os.Symlink` _do not_ contain all of the information needed to construct a _working_ symbolic link to `oldname`. `os.Symlink` needs additional information, which it can usually (but not always) obtain from the filesystem itself via `os.Stat`.

**Comment by bcmills** [comment]
> See this test https://play.golang.org/p/APh87cnpUgC - it works fine at this moment on both Linux and Windows. It will fail on Windows after your proposed change.

If a real-world program writes a symlink without ever attempting to read through that symlink, then there is likely a much deeper problem with that program, or a way that the program could be expressed more clearly without the use of write-only symlinks.

(I am aware of exactly one program that intentionally uses write-only symlinks — the one mentioned by @networkimprov earlier.)

**Comment by bcmills** [comment]
> I provided this document to point to hard links description. I do not know what you are building, but maybe you should use hard links instead. Hard links won't work without targets. That is what you want. Don't you?

Please bear in mind that among our [Gopher values](https://golang.org/conduct#values) is to “be charitable”. If you don't know what I am building, then ask — or read the issues and CLs to which I have already referred to see for yourself what they are doing.

What I want is to be able to more easily debug failures in programs that unintentionally create symbolic links of the incorrect type, such as `golang.org/x/tools/go/packages/packagestest` prior to [CL 234112](https://golang.org/cl/234112).

**Comment by bcmills** [comment]
> This is already happening now. Imagine you create symlink to a file, and then replace file with directory of the same name. We cannot do anything about it. Why should we worry about symlinks to be correct at the moment of their creation?

The current behavior reacts to what could well be a temporary failure (say, a network outage, or an expired credential) by constructing a _permanently_-broken symlink — one that will not work even once the temporary failure has been resolved.

The `os.Symlink` implementation for POSIX systems does not have that behavior. If the link target exists but is unavailable when the symlink is created, then the link will be correct and fully usable whenever the link target becomes available again.

**Comment by networkimprov** [comment]
FWIW, targetless symlinks serving as placeholders may indeed be accessed, and return file-not-found, indicating that there isn't a usable file at the symlink location.

I rather doubt I'm the only developer using this feature; it's been viable for decades. Perhaps I'm the only one doing it in Go on Windows, since Windows symlinks are inconvenient to create.

**Comment by alexbrainman** [comment]
@bcmills 

I din't think we are making progress in our discussion, because we are repeating ourselves. I will just sum up my position here and let others decide.

I agree there is a problem here, that Go can create symlink of wrong type. You propose to solve this problem by verifying target file type during symlink creation.

I don't see how your solution is an improvement.

Your change will break perfectly valid Go programs, like https://play.golang.org/p/APh87cnpUgC 

You change will make some programs - https://play.golang.org/p/APh87cnpUgC - behave differently on different OS.

Your change will still allow for symlinks of wrong type to exists. The program cannot control what happens to the target file. So, if someone removes `abc` directory, and creates `abc` file after symlink to `abc` was created, the symlink will still be broken.

> > I do not know what you are building, but maybe you should use hard links instead. Hard links won't work without targets. That is what you want. Don't you?
> 
> Please bear in mind that among our [Gopher values](https://golang.org/conduct#values) is to “be charitable”. If you don't know what I am building, then ask — or read the issues and CLs to which I have already referred to see for yourself what they are doing.

I did ask here. I am trying to understand why you created an issue in the first place.  I don't see how I offended you or anyone else here. If I did offend, I apologize.

You said

> Symlink assumes that it is a file rather than reporting the error to the caller 
> go/src/os/file_windows.go
> 
> Lines 337 to 338 in 567556d
> 
>  fi, err := Stat(destpath) 
>  isdir := err == nil && fi.IsDir() 
> That assumption seems like a mistake. If a Windows user needs to create a symlink to a not-yet-existing file or directory on Windows, they should be made aware that the call is missing essential information (the destination type), and can then make an explicit choice to use

The `That assumption seems like a mistake` is an opinion, and not fact.

I also looked at CL 234737 and issue 38772. These weren't helpful either.

> What I want is to be able to more easily debug failures in programs that unintentionally create symbolic links of the incorrect type, such as `golang.org/x/tools/go/packages/packagestest` prior to [CL 234112](https://golang.org/cl/234112).

So you want to make your change to be able to debug easier. Fair enough. But see my points above about downsides of your change.

Alex

**Comment by networkimprov** [comment]
Agreed, documentation is the best solution.

Russ, do you believe that someone who needs to create a non-existent directory-target symlink on Windows should resort to x/sys/windows? If I needed that, I'd probably patch my local stdlib, because I'm already patching it for the glitches listed in https://github.com/golang/go/issues/39183#issuecomment-632784149

We could consider an os API `AlignSymlink(target, symlink string) error` which would fix a broken symlink, and accept constants in _target_ for `SymlinkTypeFile` and `SymlinkTypeDir`.

**Comment by ianlancetaylor** [comment]
Thanks for writing down all the cases.  I agree that we should just document.

For people using Windows who need to create a symlink to a directory that does not yet exist, I think the approach is either 1) create the directory first; 2) use x/sys/windows.

I don't think we need an `AlignSymlink` function.  It should be reliable to remove the symlink and recreate it.  Accessing the symlink won't work while it is removed, but it won't work before it is removed wither.

**Comment by bcmills** [comment]
> 4. Target cannot be accessed for some temporary reason (maybe permission denied, expired credentials). os.Symlink succeeds on both systems. Later accesses fail on both systems until reason is fixed. Once reason is fixed, later access succeeds on Unix, fails on Windows if target is/was directory (we assumed file).

> 4. Unix and Windows agree on "target was really a file" or "target was fundamentally broken" and disagree on "target was really a directory". If we change, they start disagreeing on "target was really a file" too.

I think this analysis disregards the possibility of repeatable (or repeating) processes, which are the de-facto standard way to deal with temporary problems such as network failures or expired credentials.

Consider a related case:

4(a). Target cannot be access for some temporary reason, in an idempotent program that (manually or automatically) retries failed operations until either the operation reports success or the link exists. Today, `os.Symlink` “succeeds” on both systems, but the resulting link is unusable on Windows if the target is a directory.

In contrast, if we propagate non-`IsNotExist` errors, then the process will succeed immediately on Unix and (provided that the OS returned a correct error code) will retry until success on Windows.

Case 4(a) demonstrates that the existing “local compatibility” leads to an incompatibility at the level of the larger program, and the “new incompatibility” of reporting an error instead introduces a new _compatibility_ (in that the two overall programs would then produce equivalent final results).

**Comment by networkimprov** [comment]
Bryan, how would the program you describe acquire Admin privs on Windows? Or check its privs and exit if not Admin? Check .UID from os/user.Current()?

Currently, users run my app from a .cmd script that escalates its privs via PowerShell. Eventually I'll create an installer to grant the app Admin privs.

**Comment by bcmills** [comment]
> Bryan, how would the program you describe acquire Admin privs on Windows? Or check its privs and exit if not Admin? Check .UID from os/user.Current()?

Windows 10 allows non-Admin users to have the `Create symbolic links` right. (See https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links.)

That said, it's not too difficult to probe for the symlink capability by checking whether `os.Symlink` can create a symlink to a known-local target — see https://github.com/golang/go/blob/master/src/internal/testenv/testenv_windows.go. (As far as I can tell, an `os.Symlink` to a file created by the same process within a temp directory should only fail if the disk is full, and AFAIK a full disk should always be indicated by `ERROR_DISK_FULL`.)

**Comment by networkimprov** [comment]
From earlier in thread:
_Sadly, even in Win10, you have to enable "Developer Mode" to create symlinks without admin privs, so they'll probably remain uncommon on Windows._
https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinka

PS: enabling Developer Mode requires Admin privs :-)

**Comment by dmitshur** [comment]
This issue is currently labeled as early-in-cycle for Go 1.16.
That [time is now](https://groups.google.com/d/msg/golang-dev/qtxOW0x4Rrw/0rB32h12BQAJ), so this is a friendly ping so the issue is looked at again.

**Comment by rsc** [comment]
We didn't quite resolve this above, but it looks like Ian and I both believe this is a documentation issue and that we shouldn't change anything now.

**Comment by odeke-em** [comment]
Thanks for the input everyone, given the current conviction for a documentation change, I shall punt this to Go1.17. Cheers.
