### ISSUE TITLE
Gerrit: references to GitHub PRs should be linkified for all valid GitHub repo names, even ones with a dash character

### ISSUE THREAD

**Issue by stamblerre** [golang/go#39181]
Currently, mirrored PRs only have short references to the original PR, not actual links (for example, https://golang.org/cl/234717). This makes it difficult to navigate between the two. The `golang/go#1234` links should be made clickable like links to issues.

**Comment by dmitshur** [comment]
This already works for most repositories. For example, [CL 234658](https://golang.org/cl/234658) was imported from https://github.com/golang/go/pull/39176, and Gerrit correctly linkifies the PR mention:

![image](https://user-images.githubusercontent.com/1924134/82615351-2b2e2480-9b98-11ea-96a4-4c639e98d625.png)

![image](https://user-images.githubusercontent.com/1924134/82615360-31bc9c00-9b98-11ea-9e9f-f6679c7d7848.png)

I suspect there's regexp pattern used to match these, and the pattern currently rejects repository names like "vscode-go" that contain dashes. We should update the pattern in Gerrit to match all valid GitHub repository names.

**Comment by stamblerre** [comment]
Ah, thanks you're just ahead of me. I had just noticed that issues were also not getting links, but gopherbot's cl2issues task worked fine. Where is the regex defined?

**Comment by dmitshur** [comment]
I don't know exactly without first looking more, but it should be somewhere in the repository's Gerrit configuration. E.g., see https://gerrit-review.googlesource.com/Documentation/config-gerrit.html#commentlink.name.match.

**Comment by andybons** [comment]
It’s in an internal gerrit.config file specific to the Go host.

**Comment by dmitshur** [comment]
The relevant commentlink match regexp in Go host's internal gerrit config by now includes "-" as one of the possible character names in org/repo names, so a mention like `golang/vscode-go#82` (from [CL 234717](https://go.dev/cl/234717) in the original issue report) is correctly linked to `https://github.com/golang/vscode-go/pull/82`:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/1924134/179552979-bfee823e-ccb2-4b2e-9e74-e79bb35d18dc.png">

Closing as fixed. (It was actually fixed on May 26, 2020 via cl/313222876, we just forgot to close this issue.)
