### ISSUE TITLE
cmd/go: go get reports "path does not match GOPRIVATE/GONOPROXY"

### ISSUE THREAD

**Issue by heschik** [golang/go#39180]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +f7f9c8f2fb Wed May 20 15:57:15 2020 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

No.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
...
GONOPROXY="github.com/heschik"
GONOSUMDB="github.com/heschik"
GOPRIVATE="github.com/heschik"
GOPROXY="https://proxy.golang.org,direct"
...

</pre></details>

### What did you do?

`/tmp $ GO111MODULE=on ~/go/bin/go get golang.org/x/tools@master`

### What did you expect to see?

`go: golang.org/x/tools master => v0.0.0-20200519205726-57a9e4404bf7`

### What did you see instead?

`go get golang.org/x/tools@master: path does not match GOPRIVATE/GONOPROXY`

**Comment by jayconrod** [comment]
This is likely a regression due to [CL 226460](https://go-review.googlesource.com/c/go/+/226460).
