### ISSUE TITLE
net/http/cgi: Serve function passes a *http.Request value with a nil Body

### ISSUE THREAD

**Issue by gazerro** [golang/go#39190]
The `cgi.Serve` function passes to the `http.Handler` a `*http.Request` value with a `nil` Body field when the request "Content-Length" header is not greater than zero.

But the documentation of `Request.Body` states:

`// For server requests, the Request Body is always non-nil`

As a conseguence, if the  `http.Handler` calls the `Request.ParseForm` method a "missing form body" panic occurs.

**Comment by bcmills** [comment]
Want to send a CL for when the tree opens for Go 1.16? (A regression test using `httptest.Server` seems straightforward.)

**Comment by gazerro** [comment]
@bcmills Yes, I will send a CL with a regression test.
