### ISSUE TITLE
Bug: The go test command cannot parse custom args with flag.Parse()

### ISSUE THREAD

**Issue by the1mills** [golang/go#39206]
#### What version of Go are you using (`go version`)?

<pre>
go version go1.14 darwin/amd64
</pre>

#### Does this issue reproduce with the latest release?
yes 1.14

#### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alex/Library/Caches/go-build"
GOENV="/Users/alex/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/alex/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/alex/go/src/github.com/channelmeter/cp-go-api/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qh/l8tr6tfd3gv7fmdg0b5z0p340000gn/T/go-build971392475=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I ran: 

```
go test -v github.com/cm/some-pkg -- --env=local
```

### What did you expect to see?

I expected flag.Parse() to capture the flag

### What did you see instead?

the --env flag is not captured, even though it appears in the args list when I use:

```
  fmt.Println(len(os.Args), os.Args)
```

I see:

```
[/var/folders/qh/l8tr6tfd3gv7fmdg0b5z0p340000gn/T/go-build589736069/b001/roles.test -test.timeout=10m0s -test.v=true  -- --env=local]
```

I put the Q on SO first: 
https://stackoverflow.com/questions/61944527/how-to-pass-custom-flags-to-go-test?noredirect=1#comment109560255_61944527

**Comment by paulgriffiths** [comment]
This is not a bug. From the documentation for package flag:

> Flag parsing stops just before the first non-flag argument ("-" is a non-flag argument) or after the terminator "--".

and your `--env` flag appears after the terminator "--", so it's correctly not being parsed.

**Comment by as** [comment]
This is a common idiom you will see in many command line tools, not just Go.

`--` terminates the argument parser explicitly, because sometimes you have arguments, such as file names, that start with `-` which you want to capture as a value instead of a flag.

**Comment by ORESoftware** [comment]
well then you know what i am trying to do. so what is the solution?

**Comment by pschultz** [comment]
Flags in tests are really no different than in any other program, except that you don't get to call flag.Parse() yourself:

```go
package main

import (
	"flag"
	"log"
	"os"
	"testing"
)

var x = flag.Bool("env", false, "")

// run with `go test --env`
func TestFlags(t *testing.T) {
	log.Println(os.Args)     // /tmp/go-build197321626/b001/tmp.lW3vriEIbp.test -test.timeout=10m0s --env
	log.Println(flag.Args()) // []
	log.Println(*x)          // true
}
```

To treat arguments as flags create a dedicated FlagSet:

```go
// run with `go test -- --env`
func TestArgs(t *testing.T) {
	fs := flag.NewFlagSet("my-test", flag.ContinueOnError)
	y := fs.Bool("env", false, "")

	log.Println(os.Args)     // [/tmp/go-build483180072/b001/tmp.lW3vriEIbp.test -test.timeout=10m0s -- --env]
	log.Println(flag.Args()) // [--env]

	if err := fs.Parse(flag.Args()); err != nil {
		t.Fatal(err)
	}

	log.Println(*y) // true
}
```

**Comment by mvdan** [comment]
The docs for the interaction between `testing` and `flag.Parse` were a bit ambiguous, so I made them clearer a couple of weeks ago in https://github.com/golang/go/issues/38952.

If anything is still confusing, please suggest doc improvements. Aside from that, I agree that the current behavior seems to be correct.
