### ISSUE TITLE
x/build: support an x/tools SlowBot for platforms other than linux-amd64

### ISSUE THREAD

**Issue by bcmills** [golang/go#39201]
I suspect that pending [CL 234879](https://golang.org/cl/234879) may break some `x/tools` tests on Windows specifically, but it's a huge pain to set up a `gomote` instance capable of testing `x/tools` in a realistic configuration (see #32430), and I don't keep a Windows development workstation running otherwise.

The current SlowBot support allows me to add an `x/tools` run for `linux-amd64` by adding a comment with:
```
TRY=x/tools
```

And it currently allows me to add a Windows long-test run by adding a comment with:
```
TRY=windows-amd64-longtest
```

Unfortunately, it does not seem to support the combination of the two: a run for `x/tools` in the `windows-amd64-longtest` configuration. It would be very convenient for me if it did.

CC @golang/osp-team @stamblerre @ianthehat

**Comment by dmitshur** [comment]
SlowBots are intended to allow custom and slow testing, so I believe this is in scope. It's a matter of figuring out a syntax for it and implementing the feature.

As a starting point, I'll suggest the following syntax:

```
# picks default linux-amd64 builder to test x/tools
TRY=x/tools
```

```
# tests x/tools with windows-amd64-longtest builder
TRY=x/tools@windows-amd64-longtest
```

**Comment by findleyr** [comment]
This is now deployed to the coordinator and seems to work, so closing. Please re-open if any issues.
