### ISSUE TITLE
cmd/go2go: tests fail on windows in draft go packages supporting contracts (CL 187317)

### ISSUE THREAD

**Issue by AndrewWPhillips** [golang/go#39211]
### In Brief

I believe there is a portability bug in src/cmd/go2go/main.go.  Uses of the string `":"` in four places (lines 80, 83, 115, and 129) should be replaced with `string(os.PathListSeparator)`.  Without this fix go2go.exe has a bug on Windows and several of the go2go tests (in src/cmd/go2go/go2go_test.go) fail.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +af2b592260 Wed Apr 22 14:12:34 2020 -0700 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

NA

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\XXX\AppData\Local\go-build
set GOENV=C:\Users\XXX\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\XXX\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\XXX\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\goroot
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\goroot\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\XXX\Temp\go-build665904782=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

$ git clone https://go.googlesource.com/go goroot
$ cd goroot
$ git fetch "https://go.googlesource.com/go" refs/changes/17/187317/16
$ git checkout FETCH_HEAD
$ cd src
$ .\all.bat

### What did you expect to see?

...
ALL TESTS PASS

### What did you see instead?

...
ok      cmd/go/internal/work    1.799s
--- FAIL: TestGO2PATH (38.62s)
    go2go_test.go:58: running [go build -o C:\Users\XXX\Temp\go2gotest404412347\go2go.exe]
    --- FAIL: TestGO2PATH/alg (0.34s)
        go2go_test.go:115: running [C:\Users\XXX\Temp\go2gotest308375555\go2go.exe test] in C:\Users\XXX\Temp\go2go308375555\testdata\go2path\src\alg
        go2go_test.go:118: alg
        go2go_test.go:119: alg.go2:6: cannot find package "contracts" in any of:
                D:\goroot\src\contracts (from $GOROOT)
                C:\Users\XXX\Temp\go2go724857963:C:\Users\XXX\Temp\go2gotest308375555\testdata\go2path:C:\Users\XXX\go\src\contracts (from $GOPATH)
            D:\goroot\bin\go [test] failed: exit status 1
        go2go_test.go:122: error testing alg: exit status 1
    --- FAIL: TestGO2PATH/chans (1.42s)
 ...
[further similar errors]
FAIL
FAIL    cmd/go2go       42.767s
...

**Comment by ALTree** [comment]
cc @griesemer @ianlancetaylor

**Comment by bsiegert** [comment]
Issues in pending CLs should generally be posted in the code review thread, not here.

**Comment by AndrewWPhillips** [comment]
Thanks @bsiegert I tried to find a better place, or even submit a pull request but could not find any info on how to do so.  Could you tell me where the code review thread is or point me to some doc, please?

**Comment by griesemer** [comment]
Thanks for the bug report. You can comment here: https://go-review.googlesource.com/c/go/+/187317 .

Note that this is a rough prototype and there are a lot of things that don't work correctly (and we know about it).
