### ISSUE TITLE
Question: why there is no race condition in this case ?

### ISSUE THREAD

**Issue by fkarakas** [golang/go#39212]
```package main

import "time"

type counter struct {
	count []int
}

func main() {
	c := counter{}
	c.count = make([]int, 2)

	go func() {
		for i := 0; i < 1000; i++ {
			c.count[0] = i
		}
	}()

	go func() {
		total := 0
		for {
			total += c.count[1]
		}
	}()

	time.Sleep(15 * time.Second)
}
```

**Comment by ALTree** [comment]
Accessing different elements of an array is not a race condition; each element counts as a separate variable.

We don't use the github issue tracker for asking questions about the language, so I'm closing here.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks.
