### ISSUE TITLE
x/pkgsite: add repository link on documentation page

### ISSUE THREAD

**Issue by tonglil** [golang/go#39218]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/sirupsen/logrus?tab=doc
https://pkg.go.dev/github.com/sirupsen/logrus@v1.6.0?tab=doc 
https://pkg.go.dev/github.com/sirupsen/logrus?tab=doc#AddHook
 
### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0
 
 

### What is the issue?
 
There are no links to the github/source repository from the doc pages.
I don't want to click two clicks to go to the source:
![gif](https://user-images.githubusercontent.com/3250776/82710461-c62a0b80-9c37-11ea-94b8-3eaa321efd53.gif)
 
### What did you expect to see?

1. I want to be able to click on this to go to the source:
<img width="284" alt="image" src="https://user-images.githubusercontent.com/3250776/82710917-e6a69580-9c38-11ea-95c3-8e732e35279d.png">
This is godoc.org's behavior when you click on the package name:
<img width="304" alt="image" src="https://user-images.githubusercontent.com/3250776/82711174-75b3ad80-9c39-11ea-8232-342da56e0362.png">

2. I should also be able to click on any tag version to get to the source's tree of that version:
<img width="307" alt="image" src="https://user-images.githubusercontent.com/3250776/82710941-f6be7500-9c38-11ea-94c4-db280c756c4f.png">

3. I should be taken to the `master` branch when i click on the function reference, instead i am taken to a tagged version, even though I am on a "tagless" version of the doc site (https://pkg.go.dev/github.com/sirupsen/logrus?tab=doc#AddHook is not @version).
This is godoc.org's behavior.
 
### What did you see instead?

1. I can't click on it, need to copy and paste + hit enter.

2. I can't click on it. 

3. I am taken to https://github.com/sirupsen/logrus/blob/v1.6.0/exported.go#L50 instead of https://github.com/sirupsen/logrus/blob/master/exported.go#L50

**Comment by tonglil** [comment]
### Bonus

The static site banner covers links to examples:
![gif](https://user-images.githubusercontent.com/3250776/82711430-46ea0700-9c3a-11ea-8ab1-e33432b1fcc7.gif)

**Comment by julieqiu** [comment]
This feature is now available on [beta.pkg.go.dev](https://beta.pkg.go.dev). See https://github.com/golang/go/issues/41585#issuecomment-718143563 for details.

Closing this issue for https://github.com/golang/go/issues/41586.
