### ISSUE TITLE
FreeBSD: exec.Command blocks the program at start a service

### ISSUE THREAD

**Issue by tredoe** [golang/go#39226]
### Version of system
FreeBSD 12.1

### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.14.3 freebsd/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/foo/.cache/go-build"
GOENV="/home/foo/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="freebsd"
GOPATH="/home/foo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/home/foo/go/pas/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build780223111=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I use `exec.Command` to try to start a service but it only works to stop it:  
https://play.golang.org/p/rO6frqON2F6

### What did you expect to see?
I expect that the program finishes.

### What did you see instead?
The program remains stopped; I've to press Ctrl+C to interrup it.  

After, I use `sudo service firebird status` and it shows that the service was started correctly. The issue is that the Go program remains blocked.

**Comment by ianlancetaylor** [comment]
You are running into the problem described at #23019.
