### ISSUE TITLE
Check go1.14.3 in virustotal

### ISSUE THREAD

**Issue by mougrim** [golang/go#39223]
### What version of Go are you using (`go version`)?
go1.14.3

### Does this issue reproduce with the latest release?
yes

### What did you do?

I've downloaded official last release of go for linux [https://dl.google.com/go/go1.14.3.linux-amd64.tar.gz](https://dl.google.com/go/go1.14.3.linux-amd64.tar.gz) from [https://golang.org/dl/](https://golang.org/dl/).

And uploaded it to VirusTotal [https://www.virustotal.com/gui/file/1c39eac4ae95781b066c144c58e45d6859652247f7515f0d2cba7be7d57d2226/detection](https://www.virustotal.com/gui/file/1c39eac4ae95781b066c144c58e45d6859652247f7515f0d2cba7be7d57d2226/detection).

### What did you expect to see?

Message "No engines detected this file".

### What did you see instead?

Is see message "One engine detected this file":
BitDefenderTheta (antivirus): Gen:NN.Mirai.34122.

![Screenshot_20200523_113929](https://user-images.githubusercontent.com/1057709/82726057-3f823680-9cea-11ea-91a6-5bb9d8e9ece0.png)

It can be mistake, but I think better to double check it.

**Comment by ALTree** [comment]
Happens so often we have a FAQ about this: https://golang.org/doc/faq#virus

If the checksum is fine the binary you downloaded is fine.

I suggest reporting the issue to the antivirus vendor. Closing here.
