### ISSUE TITLE
'stdlib.h' file not found under macOS Catalina 10.15.4

### ISSUE THREAD

**Issue by tonyleung815** [golang/go#39232]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.14.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
macOS Catalina 10.15.4 
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xxx/Library/Caches/go-build"
GOENV="/Users/xxx/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xxx/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ml/3l4vgms54755dkmjmxztvj780000gn/T/go-build772202264=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

xcode-select --install
go run main.go

### What did you expect to see?
Hello world !

### What did you see instead?
runtime/cgo
_cgo_export.c:3:10: fatal error: 'stdlib.h' file not found

I had installed the Command Line Tools by $xcode-select --install

**Comment by proyb6** [comment]
Problem is related to macOS


https://stackoverflow.com/questions/51761599/cannot-find-stdio-h/52511046#52511046

**Comment by proyb6** [comment]
Related https://github.com/golang/go/issues/27921

**Comment by ianlancetaylor** [comment]
What happens if you write a C file

```C
#include <stdlib.h>
#include <stdio.h>

int main() { printf("Hello, world\n"); return 0; }
```

and try to compile that using `cc main.c`?

If you get the same error about `stdlib.h`, then the problem is with your C compiler installation, not with Go.

**Comment by tonyleung815** [comment]
> Related #27921

Thanks for sharing, one of the comment in that issue works for me:
$ brew unlink llvm@4

**Comment by tonyleung815** [comment]
> What happens if you write a C file
> 
> ```c
> #include <stdlib.h>
> #include <stdio.h>
> 
> int main() { printf("Hello, world\n"); return 0; }
> ```
> 
> and try to compile that using `cc main.c`?
> 
> If you get the same error about `stdlib.h`, then the problem is with your C compiler installation, not with Go.

Thanks for following up, below are my test result:
cc ok
gcc ok
clang: 'stdlib.h' file not found

The problem has been solved after I run: brew unlink llvm@4

**Comment by malajisi** [comment]
From the discuss above and my issue( I installed an older version clang6 pkg and leave an export in my .bash_profile), all these caused by clang. So
FIRST check the environment in terminal with 
`clang -v`
Change to use the Xcode installed clang, for macOS Catalina 10.15.4 is 11 or 12. All will done.
