### ISSUE TITLE
 Does `hostLookupOrder` function in `net/conf.go` need to check nil pointer?

### ISSUE THREAD

**Issue by psy-core** [golang/go#39239]
I just read the source code about `hostLookupOrder` function in  `net` library:

https://github.com/golang/go/blob/f65ad0dda7ffef9397d1aaa47259ad4d4f12474f/src/net/conf.go#L130

I noticed that `r.preferGo()` not check if r is nil.

but the function `canUseCgo` in this `conf.go` just call it with this:

https://github.com/golang/go/blob/f65ad0dda7ffef9397d1aaa47259ad4d4f12474f/src/net/conf.go#L118

which `Resolver` param is nil.  Am i missing something?

**Comment by davecheney** [comment]
In Go it is ok to call a method on a nil value. net.Resolver deals with this internally

https://github.com/golang/go/blob/f65ad0dda7ffef9397d1aaa47259ad4d4f12474f/src/net/lookup.go#L157

**Comment by psy-core** [comment]
That's incredible. I never thought It could be used like this. Thank you very much.
