### ISSUE TITLE
Add descriptions for path.Clean and filepath.Clean 

### ISSUE THREAD

**Issue by HowJMay** [golang/go#39236]
### What version of Go are you using (`go version`)?

<pre>
$ go version
</pre>
go version go1.14 Linux/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
</pre></details>

Linux on x86

### What did you expect to see?

The description of the documents for `path.Clean` and `filepath.Clean` not mention the difference between them. The implementation and the test cases are almost the same (the test cases are exactly the same). Do we need to append some description about the difference between the usage of these two functions to the current documents?

**Comment by ianlancetaylor** [comment]
The difference between `path.Clean` and `filepath.Clean` is that the former works on slash-separated paths, and the latter works on paths separated using OS-specific separator characters (such as backslash on Windows).  This is documented in the function docs if you read closely, and it is documented in the package docs of the path and filepath/path packages.
