### ISSUE TITLE
1.13.5 version, sometimes run subprocess hang

### ISSUE THREAD

**Issue by yutongprogram** [golang/go#39249]
### What version of Go are you using (`go version`)?

<pre>
1.13.5
</pre>

### What did you do?
cmd := exec.CommandContext(ctx, "bash", "-c", "xxx")
cmd.Run()   hang

### What did you expect to see?
![image](https://user-images.githubusercontent.com/5012741/82859042-31315600-9f48-11ea-988a-410c3c75bb0a.png)

gdb parent prcoess，all thread futex in /usr/local/src/runtime/sys_linux_amd64.s:536
![image](https://user-images.githubusercontent.com/5012741/82859059-43ab8f80-9f48-11ea-9dd1-7d862311276c.png)

strace parent process's thread
![image](https://user-images.githubusercontent.com/5012741/82859065-4a3a0700-9f48-11ea-8f01-dc6a823fe460.png)

**Comment by davecheney** [comment]
Can you please

1. Provide a short, runnable, code sample that exhibits the problem. 
2. Assert this issue is present with the latest version of go 1.14

**Comment by yutongprogram** [comment]
I can't  reproduce bugs steadily. I have checked syslog and hardware,  nothing useful.
Maybe someone have meet this problem. 
So any idea?

It's a  deamonset to run user's cmd
code demo 
```
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/exec"
	"os/signal"
	"strings"
	"syscall"
)

func main() {
	ctx, cancel := context.WithCancel(context.TODO())

	cmdStr := strings.Join(os.Args[1:], "")

	cmd := exec.CommandContext(ctx, "bash", "-c", cmdStr)

	exitCh := make(chan int)
	go runJob(cmd, cancel, exitCh)

	var exitCode = 0
	select {
	case exitCode = <-exitCh:
		log.Println("Exit Code: ", exitCode)
	}

	// If pid is negative, but not -1, sig shall be sent to all processes (excluding an unspecified set of system processes)
	// whose process group ID is equal to the absolute value of pid, and for which the process has permission to send a signal.
	err := syscall.Kill(-cmd.Process.Pid, syscall.SIGKILL)
	if err != nil {
		fmt.Println("Warning sending SIGKILL to customer processes group, err: ", err.Error())
	}

	os.Exit(exitCode)
}

func runJob(cmd *exec.Cmd, cancel context.CancelFunc, exitCh chan<- int) {
	defer func() {
		if r := recover(); r != nil {
			// Recovered from panic. This is just a safe net.
			log.Println("Panic when running job! ", r)
		}
		cancel()
	}()

	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	cmd.Stderr = os.Stderr
	cmd.Stdout = os.Stdout

	go signalDeamon(cmd)

	if err := cmd.Run(); err != nil {
		log.Println("Run cmd error:", err.Error())
	}

	success := cmd.ProcessState != nil && cmd.ProcessState.Success()
	defer func(ok bool) {
		var exitCode = 0
		w := cmd.ProcessState.Sys().(syscall.WaitStatus)
		if w.Exited() {
			exitCode = w.ExitStatus()
		} else if w.Signaled() {
			exitCode = int(w.Signal())
		} else {
			exitCode = 1
		}

		exitCh <- exitCode
	}(success)

}

func signalDeamon(cmd *exec.Cmd) {
	c := make(chan os.Signal, 1)
	signal.Notify(c, syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM)
	s := <-c

	_ = cmd.Process.Signal(s)
}

```

**Comment by davecheney** [comment]
Thank you for providing a sample. There are a few things that can probably be used to cut down this reproduced to the core issue

1. Can you do away with the signalDeamon code. If you don't want the parent process to handle those signals you can do something like this
```
c := make(chan os.Signal, 1)
signal.Notify(c, syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM)
go func() { <- c }
```
The child will still respond to those signals and `w.Signaled()` will report true.

**Comment by davecheney** [comment]
Also consider returning the exit code directly from `runJob`
```
	go runJob(cmd, cancel, exitCh)

	var exitCode = 0
	select {
	case exitCode = <-exitCh:
		log.Println("Exit Code: ", exitCode)
	}
```
Is equivalent to 
```
exitCode := runJob(cmd, cancel)
```
As the main goroutine cannot move past the select block until something is sent over `exitCh`

**Comment by yutongprogram** [comment]
I'll try, thanks. if any idea, please @yutongprogram  , thinkyou

**Comment by mvdan** [comment]
Closing old issues that still have the WaitingForInfo label where enough details to investigate weren't provided. Feel free to leave a comment with more details and we can reopen.

Also, see https://golang.org/wiki/Questions.
