### ISSUE TITLE
x/blog: make snippet more flexible in slices blog

### ISSUE THREAD

**Issue by afrouzMashaykhi** [golang/go#39240]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

in https://blog.golang.org/slices blog at `Passing slices to functions` can't change or play with AddOneToEachElement function.
 

### What did you expect to see?

adding AddOneToEachElement function to the try it snippet to try or change the function.

### What did you see instead?
unable to change AddOneToEachElement function.

**Comment by ianlancetaylor** [comment]
I'm sorry, I don't understand what you mean.  Can you show an example of how you think the blog post should be changed?  Thanks.

**Comment by afrouzMashaykhi** [comment]
I think It's good to have 
```
func AddOneToEachElement(slice []byte) {
    for i := range slice {
        slice[i]++
    }
}
```
in runnable snippet just like other functions in the blog.
```
func AddOneToEachElement(slice []byte) {
    for i := range slice {
        slice[i]++
    }
}
func main() {
    slice := buffer[10:20]
    for i := 0; i < len(slice); i++ {
        slice[i] = byte(i)
    }
    fmt.Println("before", slice)
    AddOneToEachElement(slice)
    fmt.Println("after", slice)
}
```

**Comment by Quaqmre** [comment]
Hi afrouzMashaykhi , if u want to run  example code with custom slice manipulater function just write your custom function with different name in code area then change 'AddOneToEachElement' function name to your new function name.(u can click the code are and write some code)
![image](https://user-images.githubusercontent.com/44048737/83329217-e76ea580-a290-11ea-954e-c68fafb53c93.png)

I hope it will help u,

**Comment by afrouzMashaykhi** [comment]
yeah thanks @Quaqmre . But I think it will be good to have that option too, just like other functions in the blog. hom?

**Comment by Quaqmre** [comment]
Maybe u right it will be much helpfull for developers,but this issue releated with https://github.com/golang/blog project , u can reopen this issue on blog project ı think.

And I checked source code of gddo and snippets can doable more flexible with small changes,
If u want to make changes and send pull request look at 
https://github.com/golang/blog/blob/master/content/slices.article
line of 185

.code slices/prog010.go /^func/,/^}/
to
.code -edit slices/prog010.go /^func/,/^}/
...

**Comment by afrouzMashaykhi** [comment]
@Quaqmre  thanks for your help
