### ISSUE TITLE
Glide to go mod

### ISSUE THREAD

**Issue by ssk199441** [golang/go#39243]
I am using the go 1.14 version we are tried to move from glide package manager to go mod. when we tried to give go mod it .it creates go mod file with the public dependency repository. It shows error for dependencies in a  private repository(Path is not correct). 

For the public repositories, it read from glide.yaml and glide.lock files. The public repository starts with github.com but it differs for a private repository.

How to mention the private repository in go mod file that is present in bitbucket

What  is the minimum version of go needed to change to go mod

**Comment by seankhliao** [comment]
see https://golang.org/cmd/go/#hdr-Module_configuration_for_non_public_modules

and https://github.com/golang/go/wiki/Questions for places to ask questions

**Comment by mdlayher** [comment]
See above. Closing.
