### ISSUE TITLE
net/mail: Parsing address "foo@bar.com <foo@bar.com>" fails

### ISSUE THREAD

**Issue by ThomasHabets** [golang/go#39258]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.14 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes. And play.golang.org

### What operating system and processor architecture are you using (`go env`)?

Debian Linux amd64

### What did you do?

Try to parse an address using `net/mail`.

https://play.golang.org/p/PzvfiO0LVT7

```go
package main

import (
	"fmt"
	"net/mail"
)

func main() {
	_, err := mail.ParseAddressList("foo@bar.com <foo@bar.com>")
	if err != nil {
		fmt.Println("Error: ", err)
	}
}

```

### What did you expect to see?

For it to be accepted. I don't know if it's standards compliant, but it's unambiguous to me.

### What did you see instead?

Parsing the address failed with an error. "Expected comma".

**Comment by ianlancetaylor** [comment]
I believe this is correct according to RFC 5322.  The `@` character is not permitted in a comment, so `foo@bar.com` must be an e-mail address.  There is then a comma missing before the next e-mail address, which is `<foo@bar.com>`.

**Comment by ThomasHabets** [comment]
Reading that more carefully, yes I think you're right. It works quoted, which also seems correct.
