### ISSUE TITLE
two switch cases to the same logic doesn't work

### ISSUE THREAD

**Issue by eliashanna78** [golang/go#39267]
Hi,
I develop Go using goland, I noticed that using:

switch x:
case y:
case z:
   logic1

default:
    logic2

If I enter the switch with value y, I will jump to default behaviour (logic2) and not what I expected which is logic1, would be nice if I could use this syntax.

Thanks,
Elias

**Comment by davecheney** [comment]
The syntax you want is
```
switch x {
case x, y:
   logic1
default:
  logic2
}
```
Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.

**Comment by eliashanna78** [comment]
Hi,
Sorry for the misuse.
And thanks for the explanation.
Elias

**Comment by davecheney** [comment]
You're welcome, and welcome to Go!
