### ISSUE TITLE
x/tools/gopls: error when renaming interface method involving type aliases

### ISSUE THREAD

**Issue by inliquid** [golang/go#39269]
1. VS Code
2. gopls@master

Trying to rename this method:
```go
type Fetcher interface {
	Data(ctx context.Context, collection, id string) (d *bson.M, ok bool)
}
```

Got this error:
```
[Error - 14:18:06] Request textDocument/rename failed.
  Message: internal error: during renaming of abstract method func (gitlab.com/***/***/pkg/service.Fetcher).Data(ctx context.Context, collection string, id string) (d *go.mongodb.org/mongo-driver/bson/primitive.M, ok bool)	changedMethods=false, coupled method=func (*gitlab.com/***/***/pkg/service.FetcherGeneric).Data(ctx context.Context, collection string, id string) (*go.mongodb.org/mongo-driver/bson/primitive.M, bool)	Please file a bug report
  Code: 0 
```

**Comment by heschik** [comment]
M is a type alias: https://pkg.go.dev/go.mongodb.org/mongo-driver/bson?tab=doc#M.

**Comment by inliquid** [comment]
So? I know what it is.

**Comment by heschik** [comment]
I made that comment and renamed the issue because I'm fairly certain that the bug is related to the alias. I didn't fully investigate but it seemed like a useful fact for whoever ends up handling the bug.

Is that a problem somehow? Your comment comes off as rather aggressive and I don't really understand why.

**Comment by inliquid** [comment]
For the moment that you were answering we were like talking to each other. I didn't understand what you meant by your response and asked to clarify. If you wrote that it was just a useful observation "for whoever ends up handling the bug", I wouldn't reply.

Is that a problem somehow?

**Comment by heschik** [comment]
This is an issue tracker, not a chat system, so generally I don't assume things are directed at me unless they @ me. I think you'd have better interactions if you made the same assumption and asked an actual question rather than just saying "So?". But that's up to you.
