### ISSUE TITLE
Compilation error with ARM processor (reoccurance)

### ISSUE THREAD

**Issue by Martin555** [golang/go#39263]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 linux/arm

# Also tried with 1.11, 1.12 and 1.13
</pre>

### Does this issue reproduce with the latest release?

Not sure, 1.14.3 is not available for arm yet.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build692618928=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

go build on https://github.com/dwoja22/ffmpeg-webrtc
-> Works flawlessly on Ubuntu amd64

### What did you expect to see?

Compilation

### What did you see instead?

<pre>
[22:13 martin@orangepizero ffmpeg-webrtc]$ go build
# golang.org/x/sys/unix
../pkg/mod/golang.org/x/sys@v0.0.0-20191206220618-eeba5f6aabab/unix/zptrace_armnn_linux.go:45:57: cannot use uint64(unsafe.Sizeof(*regsout)) (type uint64) as type uint32 in field value
../pkg/mod/golang.org/x/sys@v0.0.0-20191206220618-eeba5f6aabab/unix/zptrace_armnn_linux.go:51:54: cannot use uint64(unsafe.Sizeof(*regs)) (type uint64) as type uint32 in field value
</pre>

The same problem has been reported in issue #36032, which has been closed by gopherbot.

**Comment by randall77** [comment]
Those line numbers look like they don't correspond to tip. Could you retry with the latest x/sys?

**Comment by ianlancetaylor** [comment]
Yes, this was fixed by https://golang.org/cl/210322.  You need to update your sources.

**Comment by Martin555** [comment]
@ianlancetaylor which sources are you referring to and how can I update them? The mentioned fix was merged in December 2019 and the installed go1.14.2 was released on 2020/04/08.

Thank you.

**Comment by ianlancetaylor** [comment]
Sorry, I was referring to the golang.org/x/sys sources.  You need a newer version of the golang.org/x/sys/unix package.

**Comment by Martin555** [comment]
@ianlancetaylor thank you very much! Now it compiles flawlessly.
