### ISSUE TITLE
x/tools/gopls: repeats completion prefix for identifiers in comments

### ISSUE THREAD

**Issue by heschik** [golang/go#39262]
With `gopls` at tip, completing in comments doesn't overwrite the completion prefix. For example, in:

```
package main

// Foo<>
func FooDoesAThing() {}
```

you get a completion that yields

```
package main

// FooFooDoesAThing
func FooDoesAThing() {}
```

cc @clintjedwards

**Comment by clintjedwards** [comment]
@heschik looking at it

**Comment by clintjedwards** [comment]
Apologies, I've been super busy with other projects. Taking a look at this, this week.

**Comment by clintjedwards** [comment]
I've poked and prodded at this over the last week and I've mostly been stuck trying to parse the logic around how the prefixes are handled for other instances of this issue. Unfortunately, I'm no close to solving it and I'm going through a move and job switch at the moment so I can't dedicate any time in the near term.

Throwing back to the pool for someone else to hopefully pick up. Apologies!
