### ISSUE TITLE
unexpected missing return at end of func with switch cases exhausting all possible values of a type

### ISSUE THREAD

**Issue by bboozzoo** [golang/go#39268]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/maciek/.cache/go-build"
GOENV="/home/maciek/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="<edited>"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/maciek/code/go/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/maciek/code/go/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build201835476=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

The following piece of code does not compile, even though all possible values of given type are handled in cases and return.

```
func foo(val bool) error {
	switch val {
	case true:
		return nil
	case false:
		return nil
//	default: // WAT?
//		return nil
	}
}
```
See https://play.golang.org/p/gUjEufse8gF

Adding a `default` case that returns makes the code compile too.

### What did you expect to see?
no errors

### What did you see instead?
```
./prog.go:16:1: missing return at end of function
```

**Comment by randall77** [comment]
This error follows from the definition of [terminating statements](https://golang.org/ref/spec#Terminating_statements), and the use of that definition in [function declarations](https://golang.org/ref/spec#Function_declarations).

The definition of terminating statement does not include exhaustive switches over finite data types. Maybe it could, but it can get tricky. What about this:
```
x := true
y := false
switch val {
    case x: return nil
    case y: return nil
}
```
or this
```
switch {
    case val == true:
    case val == false:
}
```
or this
```
switch {
    case val:
    case !val:
}
```

**Comment by randall77** [comment]
To fix this issue, we'd have to change the spec. That requires going through the [proposal process](https://github.com/golang/proposal) and specifying what exactly the new rule would be.

I'm going to close this issue. Feel free to go through the proposal process if you have a spec change you think would work.
