### ISSUE TITLE
using consts in the same line

### ISSUE THREAD

**Issue by eliashanna78** [golang/go#39266]
Hi,
I don't know if this is intended, but using:
const x,y,z := 1,2,x+y doesn't compile, or at least in GoLand.
Is this an intended error? because before compiling I don't get any kind of warning.
and if I split this to two lines it will work.
Thanks,
Elias

**Comment by davecheney** [comment]
This is a syntax error

https://play.golang.org/p/v5G80Dgu-2c

Thank you for raising this issue. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
