### ISSUE TITLE
GOPATH/bin directory is empty

### ISSUE THREAD

**Issue by tianyirenjian** [golang/go#39277]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.3 windows/386
</pre>

### Does this issue reproduce with the latest release?
Always.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\tianyi\AppData\Local\go-build
set GOENV=C:\Users\tianyi\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=sse2
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\tianyi\AppData\Local\Temp\go-build574742406=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

My GOPATH/bin directory is empty. For example, I install `github.com/go-bindata/go-bindata` it says I can run `go-bindata.exe`, the executable file is not exists。Other package has the same problem.

### What did you expect to see?
GOPATH/bin should have `go-bindata.exe` and orther executable files.
My company computer has those files, but my home computer doesn't have.

### What did you see instead?
I see nothing.

**Comment by rsc** [comment]
Please send the output of 

    go install github.com/go-bindata/go-bindata
    go list -f {{.Target}} github.com/go-bindata/go-bindata

Thanks.

**Comment by tianyirenjian** [comment]
```
λ go install github.com/go-bindata/go-bindata
go: downloading github.com/go-bindata/go-bindata v3.1.2+incompatible

λ go list -f {{.Target}} github.com/go-bindata/go-bindata # shows nothing.
```

**Comment by fsouza** [comment]
You need to install the main package (`go install github.com/go-bindata/go-bindata/go-bindata`).

**Comment by tianyirenjian** [comment]
It works!
I have to install with `go get github.com/go-bindata/go-bindata/...`, there are three `.` behind the command.

Thank you.
