### ISSUE TITLE
x/build: weird builder failure

### ISSUE THREAD

**Issue by randall77** [golang/go#39282]
This slowbots builder (linux-arm-scaleway) is failing in a very strange mode. Something about "unexpected stale targets".
The same builder on the dashboard seems to be working, though.

https://farmer.golang.org/try?commit=3716ec78
https://storage.googleapis.com/go-build-log/3716ec78/linux-arm_a8d0de94.log

An older trybot run from that same CL, same problem:

https://storage.googleapis.com/go-build-log/a945aa5b/linux-arm_79ba9160.log

The CL in question should not make the bot fail in this way. It should maybe cause a test to fail, but the build is failing *much* earlier than the test that could/should fail.

@golang/osp-team 
@shawn-xdji

**Comment by andybons** [comment]
Similar message to #22709 but not necessarily the same underlying cause.

**Comment by andybons** [comment]
@rsc also.

**Comment by bcmills** [comment]
Seems very closely related to #35740 and #33598.

**Comment by cherrymui** [comment]
I think this is #35628 .

**Comment by cherrymui** [comment]
(This is because in try-bot mode the linux-arm builder is doing some cross-compile-then-copy-files-over thing, unlike the regular builder runs.)

**Comment by randall77** [comment]
I concur with Cherry, looks like #35628. Closing as dup.
