### ISSUE TITLE
go.dev: Refresh times?

### ISSUE THREAD

**Issue by hhrutter** [golang/go#39298]
Hello!

How long does it take until pushed changes to the Go doc of a repo show up on go.dev?
The old Godoc site had a handy REFRESH button.

Thanks for your hard work,
Horst

**Comment by seankhliao** [comment]
https://go.dev/about#adding-a-package

**Comment by hhrutter** [comment]
thx, 
I was looking for a change introduced by a commit that's not been released.
My bad
