### ISSUE TITLE
GODEBUG = madvdontneed = 1 does not seem to take effect

### ISSUE THREAD

**Issue by sxfworks** [golang/go#39295]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.1 linux/amd64
go version go1.12.4 linux/amd64
go version go1.13.4 linux/amd64
go version go1.14 linux/amd64
go version go1.14.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes，it still exists

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build216433097=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you expect to see?

The same copy of golang code is compiled with go1.10 / go1.11, and the running memory is relatively stable. After the flow pressure is stabilized, the memory drops slightly, and after compiling with go1.12 / go1.13 / go1.14, the process memory is after the sudden burst of traffic pressure, it has been going up. If you do this repeatedly, it will lead to the process because of OOM is killed, compared with the golang version, it is found that MADV_FREE was introduced after go1.12, so use GODEBUG = madvdontneed = 1 ./bin way to start the program, multiple tests still did not alleviate this problem.

**Comment by davecheney** [comment]
The `GODEBUG` variable is easy to get wrong, there is little validation provided so the exact invocation is critical. Can you please

1. Provide the exact steps you used so that someone without access to your environment can reproduce them. At a minimum a screenshot, or preferably the text of the commands that you used, should be provided.
2. How are you determining memory usage. Please be as specific as possible.

**Comment by sxfworks** [comment]
I mainly control the start, stop and restart specific service file contents of the program through systemctl as follows:

**Comment by sxfworks** [comment]
1.I mainly control the start, stop and restart specific service file contents of the program through systemctl as follows: 
⁣ 
⁣[Unit]
Description=exam
After=network.target

[Service]
User=exam
Group=exam
Type=simple
ExecStartPre="ulimit -c unlimited"
Envirment="GODEBUG=madvdontneed=1"
ExecStart=/opt/bin/binary_name
PrivateTmp=true
Restart=always

[Install]
WantedBy=multi-user.target
⁣
⁣2.I determine the memory usage rate, currently mainly through the following means:
 (1) VIRT and RES in top. In the version of go1.12+, VIRT and RES are always going up and not going down
 (2) Print some content in runtime.MemStats to metrics for display, the specific display is as follows:
![image](https://user-images.githubusercontent.com/43680567/83132915-a9e50d80-a114-11ea-8166-226a68e21206.png) 
![image](https://user-images.githubusercontent.com/43680567/83132957-b8332980-a114-11ea-8f63-c1c644ec43cc.png) 
![image](https://user-images.githubusercontent.com/43680567/83132985-bf5a3780-a114-11ea-91e9-8227aa0aacff.png)
![image](https://user-images.githubusercontent.com/43680567/83133014-cb45f980-a114-11ea-940e-6658cf13e31b.png)
⁣(3) Memory monitoring of the whole system
![image](https://user-images.githubusercontent.com/43680567/83133052-d9941580-a114-11ea-96f9-e293c4a17f18.png)

**Comment by mdlayher** [comment]
> Envirment=

I see a typo in your systemd config. What happens if you fix this?

**Comment by sxfworks** [comment]
> > Envirment=
> 
> I see a typo in your systemd config. What happens if you fix this?

When I use go1.12 + or higher for stress testing, the golang heap does not return to the system. Repeated stress testing will lead to OOM. I have consulted that by setting GODEBUG = madvdontneed = 1, the GC can be adjusted to return the memory To the operating system, so this environment variable is set

**Comment by sxfworks** [comment]
When I use go1.10 / go1.11, the golang heap will be returned to the operating system, and will not be killed by the Linux system because of OOM

**Comment by mdlayher** [comment]
I'm not sure you understand my point: "Envirment" is a misspelling of "Environment" in your systemd unit. You should fix the typo in the unit, reload the configuration, and then report back if the issue persists.

**Comment by doudouwyh** [comment]
Hi, every one!
i use this to run my server, but rss still very high
GODEBUG=madvdontneed=1 ./my_server

pls tell me why, and how to use madvdontneed, thx!

**Comment by mdlayher** [comment]
Please see https://github.com/golang/go/wiki/Questions.
