### ISSUE TITLE
reflect.Value.MethodByName is not returning zero value when not found

### ISSUE THREAD

**Issue by kstenerud** [golang/go#39307]
### What version of Go are you using (`go version`)?

play.golang.org

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

play.golang.org

### What did you do?

https://play.golang.org/p/Rnjm3-DT5Il
```golang
package main

import (
	"fmt"
	"reflect"
)

func main() {
	v := reflect.ValueOf(1)
	m := v.MethodByName("String")
	if !m.IsValid() {
		fmt.Println("Invalid")
	}
	if m.IsZero() {
		fmt.Println("Zero")
	}
}
```

### What did you expect to see?

```
Zero
```

### What did you see instead?

```
Invalid
panic: reflect: call of reflect.Value.IsZero on zero Value

goroutine 1 [running]:
reflect.Value.IsZero(0x0, 0x0, 0x0, 0x1)
	/usr/local/go-faketime/src/reflect/value.go:1111 +0x4b6
main.main()
	/tmp/sandbox851150891/prog.go:14 +0xf1
```

According to https://golang.org/pkg/reflect/#Value.MethodByName "It returns the zero Value if no method was found."

**Comment by ianlancetaylor** [comment]
The zero `Value` is not the value for which the `IsZero` method returns `true`; it is the `Value` for which the `IsValid` method returns `false`.  See the docs for `IsValid`, which say "It returns false if v is the zero Value."  See also the docs for `Value`, which say "The zero Value represents no value. Its IsValid method returns false, its Kind method returns Invalid, its String method returns "<invalid Value>", and all other methods panic. "

**Comment by kstenerud** [comment]
That's incredibly confusing, having a "zero" value that panics on `IsZero()`. Surely there's a more elegant way to structure the API?

**Comment by ianlancetaylor** [comment]
Well, perhaps there is.  Too late now, though, per https://golang.org/doc/go1compat.
