### ISSUE TITLE
x/tools/internal/imports: fails with empty file on disk

### ISSUE THREAD

**Issue by stamblerre** [golang/go#39315]
The repro case for this issue can be found in a `gopls` regression test in https://golang.org/cl/235581.

I have noticed that when the file is empty on disk, but the source provided includes content with a missing import, the `goimports` behavior will not succeed. Similarly, if the file has content on disk, but is empty in the overlay, an import will be added (this looks very bizarre in the editor).

/cc @heschik

**Comment by stamblerre** [comment]
@heschik noted that the regression test doesn't appear to run any code actions. However, the log does contain code actions, just slightly out-of-order:

```
[Trace - 00:20:09.201 AM] Sending request 'textDocument/codeAction - (2)'.
Params: {"textDocument":{"uri":"file:///var/folders/c5/cdxx0hzn6v3cvfn42kwt2tj000crcx/T/goplstest-sandbox-regtest-012468612/work/hello/hello_x_test.go"},"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"context":{"diagnostics":null,"only":["source.organizeImports"]}}


[Trace - 00:20:09.242 AM] Received response 'textDocument/codeAction - (2)' in 41ms.
Result: null


[Trace - 00:20:09.243 AM] Sending request 'textDocument/formatting - (3)'.
Params: {"textDocument":{"uri":"file:///var/folders/c5/cdxx0hzn6v3cvfn42kwt2tj000crcx/T/goplstest-sandbox-regtest-012468612/work/hello/hello_x_test.go"},"options":{"tabSize":0,"insertSpaces":false}}


[Trace - 00:20:09.243 AM] Received response 'textDocument/formatting - (3)' in 0ms.
Result: []


[Trace - 00:20:09.243 AM] Sending notification 'textDocument/didChange'.
Params: {"textDocument":{"version":3,"uri":"file:///var/folders/c5/cdxx0hzn6v3cvfn42kwt2tj000crcx/T/goplstest-sandbox-regtest-012468612/work/hello/hello_x_test.go"},"contentChanges":[{"text":"package hello_test\n\nimport (\n\t\"testing\"\n)\n\nfunc TestHello(t *testing.T) {\n\thello.Hello()\n}\n"}]}


[Trace - 00:20:09.243 AM] Sending notification 'textDocument/willSave'.
Params: {"textDocument":{"uri":"file:///var/folders/c5/cdxx0hzn6v3cvfn42kwt2tj000crcx/T/goplstest-sandbox-regtest-012468612/work/hello/hello_x_test.go"},"reason":1}


[Trace - 00:20:09.244 AM] Sending notification 'textDocument/didSave'.
Params: {"textDocument":{"version":3,"uri":"file:///var/folders/c5/cdxx0hzn6v3cvfn42kwt2tj000crcx/T/goplstest-sandbox-regtest-012468612/work/hello/hello_x_test.go"}}
```

The `textDocument/didChange` appears to have happened after the code actions, even though they should be triggered as part of the save, which happens after. I checked the file content that `gopls` sees, and it is the correct content, so I think it's only the log that has the incorrect ordering.

@heschik, do you see this behavior?

/cc @findleyr

**Comment by heschik** [comment]
Boy did I overthink this. goimports [gives up on a directory](https://cs.opensource.google/go/tools/+/master:internal/imports/fix.go;l=1328;drc=444c5ef18e2dcf07f4781026521f5688541a2174) if there's a parse error, and your empty file with no package statement causes a parse error.

Easy fix if you care.

**Comment by stamblerre** [comment]
I do, because if someone creates a new file and doesn't save it for whatever reason, they won't get `goimports` till it's saved. Plus I think that will play with our package reloading and could lead to some bad state. I can make the fix if you like.
