### ISSUE TITLE
go.mod replace is not heritable

### ISSUE THREAD

**Issue by enuoCM** [golang/go#39310]
### What version of Go are you using (`go version`)?

<pre>
go1.14.3 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
...
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
...
</pre></details>

### What did you do?

Project B (latest version is v1.0.0) with mod file:

```
module github.com/xxx/b

go 1.14

require (
    ...
    github.com/xxx/a v1.2.0
)

replace github.com/xxx/a => github.com/xxx/a-fork v1.2.1
```

Project C with mod file:
```
module github.com/xxx/c

go 1.14

require (
    ...
    github.com/xxx/b v1.0.0
)
```
Build project C, the code of C still references to **github.com/xxx/a v1.2.0**

### What did you expect to see?
The code of C should reference to **github.com/xxx/a-fork v1.2.1** instead

### What did you see instead?
The code of C references to **github.com/xxx/a v1.2.0**

**Comment by seankhliao** [comment]
working as intended https://github.com/golang/go/wiki/Modules#gomod

> exclude and replace directives only operate on the current (“main”) module. exclude and replace directives in modules other than the main module are ignored when building the main module. The replace and exclude statements, therefore, allow the main module complete control over its own build, without also being subject to complete control by dependencies.

**Comment by enuoCM** [comment]
@seankhliao  I see. Thanks. But should this be a drawback? With this, it's hard and unreliable to require other modules which have **replace** .
