### ISSUE TITLE
x/pkgsite: license not detected on pkg.go.dev

### ISSUE THREAD

**Issue by josh-newman** [golang/go#39318]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/apache/arrow/go/arrow?tab=overview 
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
 
### Screenshot
 
http://web.archive.org/web/20200530011330/https://pkg.go.dev/github.com/apache/arrow/go/arrow?tab=overview 
 
### What did you do?

Just visited the page. 
 
### What did you expect to see?
 
Documentation for package github.com/apache/arrow/go/arrow.
 
### What did you see instead?

A message saying documentation could not be shown because of license restrictions. The repository, github.com/apache/arrow, has the Apache 2.0 license [at its root](https://github.com/apache/arrow/blob/master/LICENSE.txt), which the pkg.go.dev license policy accepts. [godoc.org shows documentation for this package](https://godoc.org/github.com/apache/arrow/go/arrow), too.

**Comment by josh-newman** [comment]
I just discovered #37437, which seems like the same issue. That reporter worked around it before it was fixed. In this case, github.com/apache/arrow is not my code, so I'd still be interested in seeing pkg.go.dev recognize the existing license.

**Comment by jba** [comment]
The problem here is that `pkg.go.dev` only sees the tree rooted at the module (location of the `go.mod` file). What we actually consume is a zip file of that tree, handed to us by https://proxy.golang.org. We don't have the repo (although, as you can tell from the site, we do display a link to it). So the license file must appear at the repo root.

I filed apache/arrow#7351.

**Comment by josh-newman** [comment]
Thanks for looking into this, @jba. I'm seeing now that the [arrow module page](https://web.archive.org/web/20200605234031/https://pkg.go.dev/github.com/apache/arrow/go/arrow?tab=overview) fetched commit apache/arrow@6a1cdbc which is after the license copy in apache/arrow#7355,

**Comment by josh-newman** [comment]
(Sorry, I closed this accidentally.)

**Comment by jba** [comment]
I commented on the PR (but don't have permission to reopen the Jira issue, AFAICT).

**Comment by jba** [comment]
gopherbot is right for the wrong reasons: this problem is fixed as of the latest version: https://pkg.go.dev/github.com/apache/arrow/go/arrow.
