### ISSUE TITLE
go fmt: lack new line

### ISSUE THREAD

**Issue by kzhui125** [golang/go#39319]
hello, when running `go fmt` on this file, I expect there is a new line above `func main() {`

https://play.golang.org/p/X0GCtsBymTl

```go
package main

import (
	"fmt"
)

func test() {
	fmt.Println()
}
func main() {
	fmt.Println("Hello, playground")
}
```

**Comment by yonlugoh** [comment]
The test() function was never called
This works
`package main

import (
	"fmt"
)

func test() {
	fmt.Println()
}
func main() {
	test()
	fmt.Println("Hello, playground")
}`

**Comment by ALTree** [comment]
Hi, this is a dup of #22337. See in particular https://github.com/golang/go/issues/22337#issuecomment-337943177 for an answer. Closing here.
