### ISSUE TITLE
Checking if variable is less than negative integer fails to compile

### ISSUE THREAD

**Issue by Keithcat1** [golang/go#39325]
The following won't compile:
package main
i mport(

)
func main() {
	x:=-500
	println(x< -100)
}

However, if you add a space, it works:
package main
import(

)
func main() {
	x:=-500
	println(x< -100)
}
I'm getting the following compile error:
.\q.go:7:11: syntax error: unexpected <-, expecting comma or )

**Comment by mvdan** [comment]
In Go, `<-` is an operator. See https://golang.org/ref/spec#Operators_and_punctuation. See https://golang.org/wiki/Questions for questions in the future.

**Comment by Keithcat1** [comment]
Can it be implemented for ints then so it acts normally?

**Comment by mvdan** [comment]
`<-` is an opeartor for channels, not integers: https://golang.org/ref/spec#Channel_types
