### ISSUE TITLE
go.dev: easy way to update packages

### ISSUE THREAD

**Issue by aclements** [golang/go#39336]
### What is the URL of the page with the issue?
https://pkg.go.dev/github.com/aclements/go-misc/stress2
 
### What is your user agent?
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36

### Screenshot
![image](https://user-images.githubusercontent.com/2688315/83375934-8df49c80-a39e-11ea-931f-75bf8e459863.png)

### What did you do?
I pushed a new package/module to github.com/aclements/go-misc/stress2.

### What did you expect to see?
I expected pkg.go.dev to try fetching the module since it wasn't in its cache, or at least to provide an easy way to pull the latest version (a link or button).

### What did you see instead?
A 404 page. It includes [a link](https://go.dev/about#adding-a-package) to instructions on how to add a package, but those instructions aren't easy to follow. The package I pushed is a "main" package, so it's not going to be imported by something else that would pull it into the cache. And since I haven't version tagged it, I have no idea how to form the appropriate proxy.golang.org request. Finally, if this was an existing package I had updated and I simply wanted to refresh the documentation, pkg.go.dev wouldn't even offer me the link to the instructions.

**Comment by aclements** [comment]
Fishing around some more, this appears to be related to #37106, #37002, and #36811. Feel free to close as a dup if you feel this bug doesn't add anything. Thanks!

**Comment by julieqiu** [comment]
Thanks for the added context, @aclements! Understanding your user journey is really helpful. Going to close this since we are already addressing this feature in the issues you linked, and will post updates there.
