### ISSUE TITLE
x/tools/internal/gocommand: documentation doesn't state what Run{,Piped,Raw} do and what they returns

### ISSUE THREAD

**Issue by dmitshur** [golang/go#39333]
There are 3 exported identifiers with the word "Run" in package [`golang.org/x/tools/internal/gocommand`](https://pkg.go.dev/golang.org/x/tools/internal/gocommand). None of them say what the identifiers do and what they return. Each one says "it's like this other Run variant". This makes it hard to know how to use the API of `gocommand` package.

```Go
// RunPiped is like Run, but relies on the given stdout/stderr
func (i *Invocation) RunPiped(ctx context.Context, stdout, stderr io.Writer) error

// Run calls Runner.RunRaw, serializing requests if they fight over go.mod changes.
func (runner *Runner) Run(ctx context.Context, inv Invocation) (*bytes.Buffer, error)

// RunRaw calls Invocation.runRaw, serializing requests if they fight over go.mod changes.
func (runner *Runner) RunRaw(ctx context.Context, inv Invocation) (*bytes.Buffer, *bytes.Buffer, error, error)
```

Documentation for `Invocation.runRaw` isn't readily visible because it's an unexported identifier:

```Go
// RunRaw is like RunPiped, but also returns the raw stderr and error for callers
// that want to do low-level error handling/recovery.
func (i *Invocation) runRaw(ctx context.Context) (stdout *bytes.Buffer, stderr *bytes.Buffer, friendlyError error, rawError error)
```

It has named return values that help.

The `Runner` type is documented as follows:

```
// An Runner will run go command invocations and serialize them if it sees a concurrency error.
```

Perhaps that should be made more visible on the methods, and their `*bytes.Buffer` and `error` results can be given names like `stdout`, `stderr` to help clarify what's what.

/cc @heschik

**Comment by stamblerre** [comment]
There have been a number of changes to this package recently, and the documentation has been improved as a result. Closing.
