### ISSUE TITLE
x/mobile/cmd/gomobile: bind failure

### ISSUE THREAD

**Issue by bianzhifeng** [golang/go#39339]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.14.3
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

gomobile bind -target=ios xxx

### What did you expect to see?

command-line-arguments failed: exit status 1
no exported names in the package "command-line-arguments"
no exported names in the package "command-line-arguments"
no exported names in the package "command-line-arguments"
no exported names in the package "command-line-arguments"

### What did you see instead?

success

**Comment by dmitshur** [comment]
@bianzhifeng Thanks for the report. Can you please provide the following information:

- `go env` output
- what package did you run it on

/cc @hyangah @hajimehoshi
