### ISSUE TITLE
remote debug bug when go1.9.7 build cross platform  

### ISSUE THREAD

**Issue by zhangzhanli** [golang/go#39340]
Recently, I used go1.9.7 to build programs in Windows with goos=linux which would run on linux. But something wrong happened. The program running on linux works well but it doesn't work with remote debugging(in windows client to debug program running in linux, use dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec program).   I think go build produced the wrong paths for source code. For example,  when I go build D:\dos\1.go, it would produce D:\dos/D:/dos/1.go for source. I think this kind of action may lead to problem when debuging cross platform.

**Comment by davecheney** [comment]
@zhangzhanli Go 1.9.7 is out of support, see https://golang.org/s/release for details.

Can you please try to reproduce your issue with Go 1.14 and confirm if this is still a problem.

**Comment by zhangzhanli** [comment]
> @zhangzhanli Go 1.9.7 is out of support, see https://golang.org/s/release for details.
> 
> Can you please try to reproduce your issue with Go 1.14 and confirm if this is still a problem.

I see this kind of problem solved since go1.11, Thank you.

**Comment by davecheney** [comment]
Thank you for confirming.
