### ISSUE TITLE
x/tools/gopls: support post-fix completion snippets

### ISSUE THREAD

**Issue by liuwangchen** [golang/go#39354]
hope
![image](https://user-images.githubusercontent.com/25526033/83398308-b1b4f280-a431-11ea-9119-bf8e9117e97e.png)
↓
![image](https://user-images.githubusercontent.com/25526033/83398337-bf6a7800-a431-11ea-9747-81d278801b91.png)

**Comment by liuwangchen** [comment]
very nice~

**Comment by liuwangchen** [comment]
![image](https://user-images.githubusercontent.com/25526033/85986828-63d6de80-ba1f-11ea-80be-c98d8d8d3383.png)
↓
![image](https://user-images.githubusercontent.com/25526033/85986880-73562780-ba1f-11ea-9c3c-1228fa1694fb.png)
↓
![image](https://user-images.githubusercontent.com/25526033/85986902-7b15cc00-ba1f-11ea-8deb-85a54ff9971b.png)

hope support bracket post-fix snippet

**Comment by muirdm** [comment]
See https://github.com/golang/go/issues/39507#issuecomment-732397473.

@stamblerre should we close this issue in favor of #39507? Or should we use this issue to track the postfix stuff?

**Comment by stamblerre** [comment]
We can close it in favor of #39507 -- didn't realize we had both open. Thanks! Looking forward to playing with the postfix suggestions!
