### ISSUE TITLE
mkdir /somewhere: permission denied

### ISSUE THREAD

**Issue by ferismed** [golang/go#39350]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.3 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

I don't know, this is the first time I use go

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/somewhere/else/bin"
GOCACHE="/Users/fernandamedina/Library/Caches/go-build"
GOENV="/Users/fernandamedina/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/fernandamedina/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bh/6765jwl10tl6hq1p9zcz9fjw0000gn/T/go-build916815074=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I installed go package and filled instructions and then :
go get golang.org/dl/go1.10.7

I had this result:
go get golang.org/dl/go1.10.7: mkdir /somewhere: permission denied

### What did you expect to see?

installed go1.10.7 in case I needed when I started to automate

### What did you see instead?
go get golang.org/dl/go1.10.7: mkdir /somewhere: permission denied

**Comment by magical** [comment]
Your `go env` output shows that `GOBIN` is set to ```GOBIN="/somewhere/else/bin"```.

`go get` is trying to create that path and failing because you do not have permission to modify the root directory.

Try setting `GOBIN` to a directory that already exists or is somewhere that you control.

**Comment by mdlayher** [comment]
See above. Closing, I don't think there's anything more to do here.
