### ISSUE TITLE
x/tools/gopls: off by one error in name function rename

### ISSUE THREAD

**Issue by WBare** [golang/go#39364]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14.3 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.14.3

### Describe the bug
When changing a function name which is preceded by a multiline /* */ style doc comment, the name change makes two mistakes.
1) it moves the function name within the comment from the line immediately after the starting /* up one line and touching the starting /*
2) it leaves the last character from the old name appended to the end of the new name.

Maybe it is somehow related to two char Windows end of line CR/LF.

### Steps to reproduce the behavior:

Add this code to a .go file:

    /*
    Test description
    */
    func Test() {
        return
    }

Now place your cursor in the function name Test() and press F2 to change the name.  Type the new name Gronk.  The result will be:

    /*Gronkt description
    */
    func Gronk() {
        return
    }

**Comment by stamblerre** [comment]
Thanks for the report @WBare. You are right to say that this relates to Windows line endings. I'll take a look at this and see if it's fixable, but in the meantime, we do suggest always using Unix line endings, as `gofmt` always uses them.
