### ISSUE TITLE
go test with a specific run regex does not exclude tests

### ISSUE THREAD

**Issue by dprotaso** [golang/go#39362]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yup

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/dprotaso/Library/Caches/go-build"
GOENV="/Users/dprotaso/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/dprotaso/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/dprotaso/work/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qn/bxc0sm8j5dgcx260_4r3vr7w0000gn/T/go-build148028377=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```go
package main

import "testing"

func TestIngressConformance(t *testing.T) {
	t.Run("update", func(t *testing.T) {})
	t.Run("silo", func(t *testing.T) {})
}
```

Run the tests with a regex to exclude the `update` subtest

```
go test -v -run '/[^u]'
```

### What did you expect to see?

`TestIngressConformance/silo` runs

### What did you see instead?

`update` subtest runs even though it shouldn't have matched the regex

```
=== RUN   TestIngressConformance
=== RUN   TestIngressConformance/update
=== RUN   TestIngressConformance/silo
--- PASS: TestIngressConformance (0.00s)
    --- PASS: TestIngressConformance/update (0.00s)
    --- PASS: TestIngressConformance/silo (0.00s)
PASS
ok  	blah	0.006s
```

**Comment by dprotaso** [comment]
Figured it out - so the run input is split along `/` with each split-string treated as a regex.

`[^u]` does match update since it's not anchored.

Thus my regex would need to be `^[^u]`

**Comment by feiguoL** [comment]
> ^[^u]

it don't take effect, tha all command is? go test -v -run '^[^u]'?
