### ISSUE TITLE
cmd/internal/obj/arm64: minor mistake in pre-increment example

### ISSUE THREAD

**Issue by fwessels** [golang/go#39367]
The following URL contains a minor mistake: https://golang.org/pkg/cmd/internal/obj/arm64/ 

Under point 2 ("Go uses .P and .W suffixes to indicate post-increment and pre-increment.") there is a mismatch between the Go assembly and the GNU syntax (for the pre-increment with .W suffix).

Specifically Go assembly loads a signed-byte with `MOVB` whereas the GNU syntax loads an (unsigned) 64-bit double-word with `ldr`.

So either the example should be this

```
MOVB.W 16(R16), R10        <=>      ldrsb x10, [x16,#16]!
```

or 

```
MOVD.W 16(R16), R10        <=>      ldr x10, [x16,#16]!
```

or even 

```
MOVBU.W 16(R16), R10        <=>     ldrb x10, [x16,#16]!
```

**Comment by cherrymui** [comment]
cc @zhangfannie

**Comment by zhangfannie** [comment]
@fwessels  Thank you for pointing out the mistake in https://golang.org/pkg/cmd/internal/obj/arm64/. The arm64 go assembler has the correct encoding for  instruction " MOVB.W 16(R16), R10 ", we just have a typo in this document. I will submit a patch to fix this error. Thanks.

**Comment by fwessels** [comment]
Yes, correct, it is just a documentation error, luckily not in the assembler itself.
