### ISSUE TITLE
package sort do sort.Slice(), The result is not the intended result

### ISSUE THREAD

**Issue by imkos** [golang/go#39370]
### What version of Go are you using (`go version`)?

<pre>
golang 1.14.4 & golang 1.13.12

</pre>

### Does this issue reproduce with the latest release?

https://play.golang.org/p/2CDG2pa4OmU

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>

</pre></details>

### What did you expect to see?

```
njo: [{"feeType":1001,"transType":0,"transactionAmount":355710},{"feeType":1401,"transType":0,"transactionAmount":2775},{"feeType":1602,"transType":0,"transactionAmount":220000},{"feeType":1802,"transType":0,"transactionAmount":4162},{"feeType":1602,"transType":1,"transactionAmount":10000}]
```

### What did you see instead?

```
njo: [{"feeType":1001,"transType":0,"transactionAmount":355710},{"feeType":1401,"transType":0,"transactionAmount":2775},{"feeType":1602,"transType":0,"transactionAmount":220000},{"feeType":1602,"transType":1,"transactionAmount":10000},{"feeType":1802,"transType":0,"transactionAmount":4162}]
```

**Comment by davecheney** [comment]
Thank you for providing a sample program. I believe you are asking why values with different transaction amounts are not sorted as you expected. If this is the case this is because yoursorting algorithm does not take the amount into consideration.

https://play.golang.org/p/zYvtpCb-7b6

If I misunderstood your question, would you please clarify.

**Comment by randall77** [comment]
Your comparison function is incorrect. It isn't antisymmetric. You must add the middle condition here:
```
func(i, j int) bool {
		if fbs[i].TransType < fbs[j].TransType {
			return true
		}
		if fbs[i].TransType > fbs[j].TransType {
			return false
		}
		// only if TransType are equal, should you compare FeeType
		if fbs[i].FeeType < fbs[j].FeeType {
			return true
		}
		return false
	}
```

**Comment by imkos** [comment]
Thanks for the reply, I read the reply from randall77, it is indeed a problem with my code
