### ISSUE TITLE
runtime: runtime-gdb.py does not work on RHEL

### ISSUE THREAD

**Issue by laboger** [golang/go#39387]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +9984ef8 Wed Jun 3 19:07:55 2020 +0000 linux/ppc64le
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?
@dr2chase 
I just tried to do a build on a ppc64le RHEL8 system and this test fails in the same way as on the dashboard for s390x. The bad output is:
```
Loading Go Runtime support.
        Traceback (most recent call last):
          File "/data/golang/workdir/go/src/runtime/runtime-gdb.py", line 33, in <module>
            majorgdbversion = int(splitgdbversion[0])
        ValueError: invalid literal for int() with base 10: 'Red Hat Enterprise Linux 8'
```
Looks like the recent update to parse the gdb version is not handling Red Hat output correctly?
The ppc64le builders are not Red Hat so they aren't failing on the dashboard.

**Comment by laboger** [comment]
s390x failure https://build.golang.org/log/9fccb7c7e19963939b7d4a57c68a45296776ab02

**Comment by dr2chase** [comment]
Fixed as of a few minutes ago, latest change uses regexps for all possible inputs instead of parsing version "numbers".  See https://go-review.googlesource.com/c/go/+/236280

**Comment by laboger** [comment]
Thanks! I noticed you had started a CL for this after I opened the issue. Just tried it out and works fine.
