### ISSUE TITLE
[Help wanted]How to locate dependency using go module?

### ISSUE THREAD

**Issue by fwhezfwhez** [golang/go#39399]
After execute `go mod tidy`, a dependency `github.com/klauspost/reedsolomon` is download and put into go.sum,but my project actually not import it. Some of my import packages might inner import `github.com/klauspost/reedsolomon`.

So, how can I know which package I import has imported `github.com/klauspost/reedsolomon`

**Comment by davecheney** [comment]
You can use `go mod graph` to print out the dependency graph of module imports. Use `go help mod graph` for an explanation of the output.

Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.
Please see https://golang.org/wiki/Questions for good places to ask questions.

**Comment by fwhezfwhez** [comment]
3q
