### ISSUE TITLE
cmd/go, cmd/cgo: “ build constraints exclude all Go files“ error

### ISSUE THREAD

**Issue by lbbxsxlz** [golang/go#39398]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>
go version go1.14.4 linux/amd64
### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lbbxsxlz/.cache/go-build"
GOENV="/home/lbbxsxlz/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/lbbxsxlz/workspace/GO"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/lbbxsxlz/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/lbbxsxlz/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build451549208=/tmp/go-build -gno-record-gcc-switches"
### What did you do?

```go
package main

import "C"
import (
        "debug/elf"
        "errors"
        "io/ioutil"
        "log"
)

func CreateUuidFile(progfile, sectionname, filename string)(error) {
        ef, err := elf.Open(progfile)
        if err != nil {
                log.Printf("open elf fail \n")
                return errors.New("open elf fail \n")
        }
        defer ef.Close()

        section := ef.Section(sectionname)
        if section == nil {
                log.Printf("get uuid section fail \n")
                return errors.New("get uuid section fail \n")
        }

        data, err:= section.Data()
        if err != nil {
                log.Printf("get uuid data fail \n")
                return errors.New("get get uuid data fail \n")
        }

        err = ioutil.WriteFile(filename, data, 0666)
        if err != nil {
                log.Printf("WriteFile data fail \n")
                return errors.New("WriteFile data fail \n")
        }

        ef.Close()
        return nil
}

func main() {
        if err := CreateUuidFile("/home/31770/sonia", ".uuid", "sonia-uuid.txt"); err != nil {
                log.Fatal("CreateUuidFile fail")
        }
}
```

### What did you expect to see?

 "GOOS=linux GOARCH=arm64 go build -o elfTest_arm64 elfTest.go"  build  no errors   

### What did you see instead?

can't load package: package main: build constraints exclude all Go files in /home/lbbxsxlz/workspace/GO

"GOOS=linux GOARCH=arm64 go build -o elfTest_arm64 elfTest.go"  build fail
"GOOS=linux GOARCH=arm go build -o elfTest_arm elfTest.go"  build fail

**Comment by cherrymui** [comment]
Try setting `CGO_ENABLED=1`, and `CC` to a C cross compiler. For cross-compilation, cgo is disabled by default. You need to enable it explicitly. And you'll need a C cross compiler.

debug/elf is probably not related.

**Comment by lbbxsxlz** [comment]
> Try setting `CGO_ENABLED=1`, and `CC` to a C cross compiler. For cross-compilation, cgo is disabled by default. You need to enable it explicitly. And you'll need a C cross compiler.
> 
> debug/elf is probably not related.

Thank you!
