### ISSUE TITLE
cmd/go: "--" after the first "--" is not considered as file

### ISSUE THREAD

**Issue by cuonglm** [golang/go#39392]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +429d2c548d Wed Jun 3 22:07:42 2020 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```
$ cat main.go
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello, playground")
}
$ go run -- main.go -- anything
```

### What did you expect to see?

Run fails, error reports like any *nix commands:

```
$ cat -- main.go -- anything
...
cat: --: No such file or directory
cat: anything: No such file or directory
```

### What did you see instead?

Run success.

**Comment by davecheney** [comment]
`--`, in gnu flags speak, says to the flag parser, _anything after `--` is not a flag, even if it starts with a `-`. It's still up the program what it wants to do with those arguments.
```
[/var/folders/wh/k4ydm2jx2tb5tgfvdcddl3ym0000gn/T/go-build621388717/b001/exe/main -- anything]
(~/src) % cat main.go
package main

import (
        "fmt"
        "os"
)

func main() {
        fmt.Println(os.Args)
}
(~/src) % go run -- main.go -- anything
[/var/folders/wh/k4ydm2jx2tb5tgfvdcddl3ym0000gn/T/go-build725222586/b001/exe/main -- anything]
```

**Comment by cuonglm** [comment]
> `--`, in gnu flags speak, says to the flag parser, anything after `--` is not a flag, even if it starts with a `-`. It's still up the program what it wants to do with those arguments.
> 
> ```
> 
> (~/src) % cat main.go
> 
> package main
> 
> 
> 
> import (
> 
>         "fmt"
> 
>         "os"
> 
> )
> 
> 
> 
> func main() {
> 
>         fmt.Println(os.Args)
> 
> }
> 
> (~/src) % go run -- main.go -- anything
> 
> [/var/folders/wh/k4ydm2jx2tb5tgfvdcddl3ym0000gn/T/go-build725222586/b001/exe/main -- anything]
> 
> ```
> 
> In the case of the `cat` example you gave, cat expects each of the arguments provided it to be files, so the second `--` is treated as a file named `--`. I don't see why `go run` should follow those semantics

IIRC, it’s POSIX.

Maybe at least we should add documentation for that?

**Comment by davecheney** [comment]
> IIRC, it’s POSIX.

Yes, you are completely correct. I realised after I wrote this that `--` probably isn't just a GNUism.

> Maybe at least we should add documentation for that?

I don't understand what there is to document, the second `--` isn't interpreted as a file because its passed to main.go as os.Args. If anything its the operation of the first `--` that is confusing to me.
