### ISSUE TITLE
x/website: golang.org/pkg/ page contains a link to a website with expired HTTPS certificate and "Service Unavailable" content

### ISSUE THREAD

**Issue by stephenwvickers** [golang/go#39408]
https://golang.org/pkg/#community includes a link to http://go-search.org/.

That link is currently serving a redirect to https, but the HTTPS certificate has expired on February 23, 2020. The content being currently served is "503 Service Unavailable".

**Comment by davecheney** [comment]
I'm sorry to hear that. Sadly this is not a service run by the go team, I'm sorry I don't know who does run it.

**Comment by stephenwvickers** [comment]
Why not remove it from https://golang.org/pkg/?

**Comment by davecheney** [comment]
Ping @dmitshur

**Comment by dmitshur** [comment]
Thanks for reporting. We'll take a look.

/cc @andybons @julieqiu

**Comment by stephenwvickers** [comment]
@dmitshur no worries, and apologies for not setting an appropriate title originally.

**Comment by dmitshur** [comment]
@stephenwvickers No problem, the "x/website:" prefix was a great start! I've edited the issue to make it more specific and easier to understand.

If you're interested in learning more, there is useful information in [CONTRIBUTING.md#filing-issues](https://github.com/golang/go/blob/master/CONTRIBUTING.md#filing-issues) and [wiki/HandlingIssues](https://github.com/golang/go/wiki/HandlingIssues).
