### ISSUE TITLE
go.dev: change default font to Helvetica

### ISSUE THREAD

**Issue by dalu** [golang/go#39401]
### What is the URL of the page with the issue?
 
 any
 
### What is your user agent?
 
firefox
chromium
chrome 
 
 
### Screenshot
 

 
![Screenshot from 2020-06-04 14-11-16](https://user-images.githubusercontent.com/2694548/83755097-58390780-a66d-11ea-889a-787db0588b00.png)
![Screenshot from 2020-06-04 14-11-22](https://user-images.githubusercontent.com/2694548/83755107-5b33f800-a66d-11ea-815f-4f03d519d62d.png)

with Helvetica font
![Screenshot from 2020-06-04 14-15-57](https://user-images.githubusercontent.com/2694548/83755479-f036f100-a66d-11ea-8bec-cf5d5e285245.png)
 
### What did you do?
 
navigate to pkg.go.dev 
 
### What did you expect to see?
 
`font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;`
the same as on godoc.org, as very readable font
it might not seem like much but roboto is not a friendly font on the eye, especially with so much condensed text
 
### What did you see instead?

`font-family: Roboto, Arial, sans-serif;`

**Comment by spf13** [comment]
Go.dev follows the Go Brand Guide. We will not make a one off change on this site.

To change the brand guide we would need a very compelling case that Roboto lacked readability.

**Comment by dalu** [comment]
Then change the brand guide

**Comment by ianlancetaylor** [comment]
This seems to be a style preference, and we have a style.  Thanks for the suggestion, though.

**Comment by dalu** [comment]
Re-open the issue

**Comment by ianlancetaylor** [comment]
Please be respectful.  In case you were not aware, this issue tracker is governed by a code of conduct, which can be found at https://golang.org/conduct.  Thanks.

I apologize for my confusing use of "we".  I've edited my comment to refer to the Go project.

I will be happy to reopen the issue if you add a new argument, one that is based on research or on widely followed standards, not one based on personal preference.  Thanks.

I expect that it is possible to write a browser extension to change the typeface to anything you prefer.  That might be a more profitable approach to take here.
