### ISSUE TITLE
cmd/go/internal/auth: the .netrc parser doesn't understand passphrases with spaces

### ISSUE THREAD

**Issue by ainar-g** [golang/go#39403]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ainar/.cache/go-build"
GOENV="/home/ainar/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/tmp/g"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/ainar/go/go1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/ainar/go/go1.14/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build748023900=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
With this in my `.netrc`:
```
machine my.git.host login ainar-g password "very long and secure passphrase"
```
I did:
```
$ go get my.git.host/go-package
```

### What did you expect to see?
Package in my `GOPATH`.

### What did you see instead?
401 from the server.  I assume that it's because the `.netrc` parser doesn't understand quoted passphrases with spaces.  IIRC, they're not standard, but are a common extension.  [Current code](https://github.com/golang/go/blob/b371f189dfdfb2454a20ec276de55fe884d6ff9f/src/cmd/go/internal/auth/netrc.go#L42) just uses `strings.Fields`.

**Comment by dmitshur** [comment]
> IIRC, they're not standard, but are a common extension.

How would it affect users that happen to have a double quote character in their password?

**Comment by ainar-g** [comment]
<p>Good question.  According to
<a href="https://stackoverflow.com/a/12675195/1892060">this <i>StackOverflow</i> answer</a>
the two widely-used <code>.netrc</code> parsers that allow spaces are
<i>GNU ftp</i> and the <i>Net::Netrc</i> module in Perl.  The
<a href="https://github.com/guillemj/inetutils/blob/cca748a6cfcfee7e0e0387e527d4d96a7dadbe81/ftp/ruserpass.c#L362">C source code</a>
of the first one suggests that it simply scans until the next double
quote.  My Perl and PCRE are a bit rusty, but the
<a href="https://github.com/Perl/perl5/blob/d9bfa782f8cc54abdbea9c0a91d1b25a9ab98736/cpan/libnet/lib/Net/Netrc.pm#L90">regexp in the Perl source code</a>
seems to suggest a similar behaviour.  So, if the user has
a double-quote inside the password, they're probably fine, but if the
password starts with a double-quote, there is no way to express that in
<code>.netrc</code>.</p>

**Comment by bcmills** [comment]
The Go `.netrc` parser is based on the description in https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html, which says:

> [Tokens] may be separated by spaces, tabs, or new-lines:

That implies that, for example,
```
machine a.example.com password "hunter2 machine b.example.com password opensesame"
```
should be parsed as
```
machine a.example.com
password "hunter2
machine b.example.com
password opensesame"
```

You could argue that real passwords should not contain quote characters, but that's not particularly different from arguing that real passwords should not contain spaces...

**Comment by bcmills** [comment]
So the question is: is there an authoritative (or semi-authoritative) reference for quote-escaping in `.netrc` files, and/or for why passwords should prefer ` ` over `"`?

**Comment by ainar-g** [comment]
@bcmills  Who was supposed to add more info?  I apologise if it was me, because as far as I know, there aren't any more authoritative references than the current implementations I mentioned.

**Comment by jayconrod** [comment]
(Answering for @bcmills since he's out of office today)

My understanding is that [The .netrc file](https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html) is the best source on this format. If there's a more authoritative source though, please let us know.

I think we should stick to the spec, such as at is. If every tool has its own interpretation of this file, that's not a good situation for anyone.

**Comment by ainar-g** [comment]
@jayconrod  The thing about that file is that it uses two words that may or may not mean the same thing: “name” and “string”.  This “string” may be just another name for a non-space string of characters or it may mean that `"a b c"` is a “string” and a “token” in and of itself.  The source code of *GNU ftp*, which I linked above, seems to think that it's the latter and not the former.

I don't think there is a good solution here, to be honest.  **I assume**, that passphrases with spaces are more common than those with double quotes, but there are already implementations that don't allow spaces.

**Comment by jayconrod** [comment]
> The following **tokens** are recognized; they may be separated by spaces, tabs, or new-lines:
> ...
> ‘login **name**’
> ...
> ‘password **string**’
> Supply a password. If this token is present, the auto-login process will supply the specified string if the remote server requires a password as part of the login process. Note that if this token is present in the .netrc file for any user other than anonymous, ftp will abort the auto-login process if the .netrc is readable by anyone besides the user.

This doesn't seem ambiguous to me: *name* and *string* are just descriptive names. Tokens may be separated by spaces, tabs, or newlines; there's no other restriction on characters within tokens; nothing says quotes should have special meaning.

Is GNU ftp implementing something else? I don't think their source code alone is convincing.

**Comment by 89z** [comment]
Space is a valid character for a password. More common these days would be people using them with a passphrase, which is totally valid. However as others have said, the current spec doesnt account for this situation at all. It assumes all tokens are separated by whitespace, so if your password has a space, then it would be considered two tokens.

I think what OP was getting at, is that this is a poor spec, which I agree it is.  However until if an when its updated, it will be hard to justify deviating from the spec. One popular implementation is cURL, which as can be seen just assumes tokens are separated by whitespace:

https://github.com/curl/curl/blob/33ba0ecf/lib/netrc.c#L87
