### ISSUE TITLE
proposal: Go compiler can be smarter

### ISSUE THREAD

**Issue by cyantarek** [golang/go#39414]
As a well wisher of Go, I found the contents of this article to be really valid.

https://lemire.me/blog/2020/06/04/the-go-compiler-needs-to-be-smarter/

P.S: I'm not the original author of this article

**Comment by randall77** [comment]
We don't really need meta-issues like this one to keep track of optimizations. 
Feel free to pick out particular benchmarks you think are not compiled optimally and file issues for those.
I'm going to close this one.
