### ISSUE TITLE
crypto/x509: SKID generation is over full spki, rather than just the subjectPublicKey

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#39429]
https://go-review.googlesource.com/c/go/+/227098 introduced automatic SKID generation when one isn't provided using method (1) from RFC 5280 Section 4.2.1.2. The hash provided is over the full SPKI structure, rather than just the subjectPublicKey BIT STRING as defined, which makes it out of line with certain other implementations that assume this is how the SKID is generated.

This is unlikely to break anything major, but if the goal is to use the RFC 5280 method as defined it would make sense to stick to that construction.

**Comment by dmitshur** [comment]
Thanks for reporting this @rolandshoemaker.

That CL was for to fix issue #26676.

/cc @katiehockman @FiloSottile

**Comment by FiloSottile** [comment]
Ah, good catch, looks like I got this wrong in the review even if Katie had suggested using the correct value. Better fix this for Go 1.15.
