### ISSUE TITLE
cmd/go: can not modify the go mod library version

### ISSUE THREAD

**Issue by cplayer** [golang/go#39425]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/cplayer/Library/Caches/go-build"
GOENV="/Users/cplayer/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/cplayer/DailyDocuments/Workspace/go-workspace/gopath"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,https://goproxy.io,direct"
GOROOT="/usr/local/Cellar/go/1.14.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tg/t3b_z3zx53949bs3dtx2w78h0000gn/T/go-build828205142=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Here is the github link of my program:
https://github.com/cplayer/knative.flow/tree/master/client

I want to use k8s.io/client-go@v0.18.3 as my client-go library.
After I modify the client-go version in go.mod, I run "go build main.go", the version of client-go will be replaced by v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible, which is definitely not a right version.

<pre>
$ go build main.go
# k8s.io/client-go/rest
../../gopath/pkg/mod/k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
        have (*versioned.Decoder)
        want (watch.Decoder, watch.Reporter)
</pre>

### What did you expect to see?
The program should use v0.18.3 as the client-go library version.

### What did you see instead?
The program use the old version(which only supported k8s 1.10) as the client-go library version.

**Comment by bcmills** [comment]
What does `go mod graph` report about your dependencies on `k8s.io/client-go`?

Go's version selection uses semantic-versioning precedence, and `v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible` does indeed have higher precedence than `v0.18.3`, so if one of your transitive dependencies already requires the higher version then you cannot force a lower one. (You could perhaps `replace` the higher version with the source code from the lower one to fix your immediate build, but that would not fix the build for anyone else who depends on your module.)

**Comment by cplayer** [comment]
Hi, Here is my `go mod graph | grep client-go` output:
<details>
<summary><code>go mod graph | grep client-go</code> Output</summary><br><pre>
$ go mod graph | grep client-go
knative.flow/client k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible
github.com/google/go-containerregistry@v0.0.0-20200123184029-53ce695e4179 k8s.io/client-go@v0.17.0
github.com/google/go-containerregistry@v0.1.0 k8s.io/client-go@v0.17.4
github.com/tektoncd/pipeline@v0.10.1 k8s.io/client-go@v0.17.0
github.com/vdemeester/k8s-pkg-credentialprovider@v1.17.4 k8s.io/client-go@v0.17.4
github.com/aws/aws-k8s-tester@v0.9.3 k8s.io/client-go@v0.17.3
github.com/google/go-containerregistry@v0.0.0-20191010200024-a3d713f9b7f8 k8s.io/client-go@v0.0.0-20180910083459-2cefa64ff137
github.com/google/go-containerregistry@v0.0.0-20200115214256-379933c9c22b k8s.io/client-go@v0.17.0
github.com/aws/aws-k8s-tester@v0.0.0-20190114231546-b411acf57dfe k8s.io/client-go@v9.0.0+incompatible
helm.sh/helm/v3@v3.1.1 k8s.io/client-go@v0.17.2
k8s.io/cloud-provider@v0.17.4 k8s.io/client-go@v0.17.4
k8s.io/apiserver@v0.17.2 k8s.io/client-go@v0.17.2
k8s.io/client-go@v0.17.2 sigs.k8s.io/yaml@v1.1.0
k8s.io/client-go@v0.17.2 k8s.io/utils@v0.0.0-20191114184206-e782cd3c129f
k8s.io/client-go@v0.17.2 k8s.io/klog@v1.0.0
k8s.io/client-go@v0.17.2 k8s.io/apimachinery@v0.17.2
k8s.io/client-go@v0.17.2 k8s.io/api@v0.17.2
k8s.io/client-go@v0.17.2 google.golang.org/appengine@v1.5.0
k8s.io/client-go@v0.17.2 golang.org/x/time@v0.0.0-20190308202827-9d24e82272b4
k8s.io/client-go@v0.17.2 golang.org/x/oauth2@v0.0.0-20190604053449-0f29369cfe45
k8s.io/client-go@v0.17.2 golang.org/x/net@v0.0.0-20191004110552-13f9640d40b9
k8s.io/client-go@v0.17.2 golang.org/x/crypto@v0.0.0-20190820162420-60c769a6c586
k8s.io/client-go@v0.17.2 github.com/stretchr/testify@v1.4.0
k8s.io/client-go@v0.17.2 github.com/spf13/pflag@v1.0.5
k8s.io/client-go@v0.17.2 github.com/peterbourgon/diskv@v2.0.1+incompatible
k8s.io/client-go@v0.17.2 github.com/imdario/mergo@v0.3.5
k8s.io/client-go@v0.17.2 github.com/gregjones/httpcache@v0.0.0-20180305231024-9cad4c3443a7
k8s.io/client-go@v0.17.2 github.com/gophercloud/gophercloud@v0.1.0
k8s.io/client-go@v0.17.2 github.com/googleapis/gnostic@v0.0.0-20170729233727-0c5108395e2d
k8s.io/client-go@v0.17.2 github.com/google/uuid@v1.1.1
k8s.io/client-go@v0.17.2 github.com/google/gofuzz@v1.0.0
k8s.io/client-go@v0.17.2 github.com/google/btree@v1.0.0
k8s.io/client-go@v0.17.2 github.com/golang/protobuf@v1.3.2
k8s.io/client-go@v0.17.2 github.com/golang/groupcache@v0.0.0-20160516000752-02826c3e7903
k8s.io/client-go@v0.17.2 github.com/gogo/protobuf@v1.2.2-0.20190723190241-65acae22fc9d
k8s.io/client-go@v0.17.2 github.com/evanphx/json-patch@v4.2.0+incompatible
k8s.io/client-go@v0.17.2 github.com/davecgh/go-spew@v1.1.1
k8s.io/client-go@v0.17.2 github.com/Azure/go-autorest/autorest/adal@v0.5.0
k8s.io/client-go@v0.17.2 github.com/Azure/go-autorest/autorest@v0.9.0
k8s.io/client-go@v0.17.2 cloud.google.com/go@v0.38.0
k8s.io/client-go@v0.17.4 sigs.k8s.io/yaml@v1.1.0
k8s.io/client-go@v0.17.4 k8s.io/utils@v0.0.0-20191114184206-e782cd3c129f
k8s.io/client-go@v0.17.4 k8s.io/klog@v1.0.0
k8s.io/client-go@v0.17.4 k8s.io/apimachinery@v0.17.4
k8s.io/client-go@v0.17.4 k8s.io/api@v0.17.4
k8s.io/client-go@v0.17.4 google.golang.org/appengine@v1.5.0
k8s.io/client-go@v0.17.4 golang.org/x/time@v0.0.0-20190308202827-9d24e82272b4
k8s.io/client-go@v0.17.4 golang.org/x/oauth2@v0.0.0-20190604053449-0f29369cfe45
k8s.io/client-go@v0.17.4 golang.org/x/net@v0.0.0-20191004110552-13f9640d40b9
k8s.io/client-go@v0.17.4 golang.org/x/crypto@v0.0.0-20200220183623-bac4c82f6975
k8s.io/client-go@v0.17.4 github.com/stretchr/testify@v1.4.0
k8s.io/client-go@v0.17.4 github.com/spf13/pflag@v1.0.5
k8s.io/client-go@v0.17.4 github.com/peterbourgon/diskv@v2.0.1+incompatible
k8s.io/client-go@v0.17.4 github.com/imdario/mergo@v0.3.5
k8s.io/client-go@v0.17.4 github.com/gregjones/httpcache@v0.0.0-20180305231024-9cad4c3443a7
k8s.io/client-go@v0.17.4 github.com/gophercloud/gophercloud@v0.1.0
k8s.io/client-go@v0.17.4 github.com/googleapis/gnostic@v0.0.0-20170729233727-0c5108395e2d
k8s.io/client-go@v0.17.4 github.com/google/uuid@v1.1.1
k8s.io/client-go@v0.17.4 github.com/google/gofuzz@v1.0.0
k8s.io/client-go@v0.17.4 github.com/google/btree@v1.0.0
k8s.io/client-go@v0.17.4 github.com/golang/protobuf@v1.3.2
k8s.io/client-go@v0.17.4 github.com/golang/groupcache@v0.0.0-20160516000752-02826c3e7903
k8s.io/client-go@v0.17.4 github.com/gogo/protobuf@v1.2.2-0.20190723190241-65acae22fc9d
k8s.io/client-go@v0.17.4 github.com/evanphx/json-patch@v4.2.0+incompatible
k8s.io/client-go@v0.17.4 github.com/davecgh/go-spew@v1.1.1
k8s.io/client-go@v0.17.4 github.com/Azure/go-autorest/autorest/adal@v0.5.0
k8s.io/client-go@v0.17.4 github.com/Azure/go-autorest/autorest@v0.9.0
k8s.io/client-go@v0.17.4 cloud.google.com/go@v0.38.0
k8s.io/apiserver@v0.17.4 k8s.io/client-go@v0.17.4
k8s.io/legacy-cloud-providers@v0.17.4 k8s.io/client-go@v0.17.4
k8s.io/metrics@v0.17.2 k8s.io/client-go@v0.17.2
k8s.io/component-base@v0.17.0 k8s.io/client-go@v0.17.0
k8s.io/client-go@v0.17.0 sigs.k8s.io/yaml@v1.1.0
k8s.io/client-go@v0.17.0 k8s.io/utils@v0.0.0-20191114184206-e782cd3c129f
k8s.io/client-go@v0.17.0 k8s.io/klog@v1.0.0
k8s.io/client-go@v0.17.0 k8s.io/apimachinery@v0.17.0
k8s.io/client-go@v0.17.0 k8s.io/api@v0.17.0
k8s.io/client-go@v0.17.0 google.golang.org/appengine@v1.5.0
k8s.io/client-go@v0.17.0 golang.org/x/time@v0.0.0-20190308202827-9d24e82272b4
k8s.io/client-go@v0.17.0 golang.org/x/oauth2@v0.0.0-20190604053449-0f29369cfe45
k8s.io/client-go@v0.17.0 golang.org/x/net@v0.0.0-20191004110552-13f9640d40b9
k8s.io/client-go@v0.17.0 golang.org/x/crypto@v0.0.0-20190820162420-60c769a6c586
k8s.io/client-go@v0.17.0 github.com/stretchr/testify@v1.4.0
k8s.io/client-go@v0.17.0 github.com/spf13/pflag@v1.0.5
k8s.io/client-go@v0.17.0 github.com/peterbourgon/diskv@v2.0.1+incompatible
k8s.io/client-go@v0.17.0 github.com/imdario/mergo@v0.3.5
k8s.io/client-go@v0.17.0 github.com/gregjones/httpcache@v0.0.0-20180305231024-9cad4c3443a7
k8s.io/client-go@v0.17.0 github.com/gophercloud/gophercloud@v0.1.0
k8s.io/client-go@v0.17.0 github.com/googleapis/gnostic@v0.0.0-20170729233727-0c5108395e2d
k8s.io/client-go@v0.17.0 github.com/google/uuid@v1.1.1
k8s.io/client-go@v0.17.0 github.com/google/gofuzz@v1.0.0
k8s.io/client-go@v0.17.0 github.com/google/btree@v1.0.0
k8s.io/client-go@v0.17.0 github.com/golang/protobuf@v1.3.2
k8s.io/client-go@v0.17.0 github.com/golang/groupcache@v0.0.0-20160516000752-02826c3e7903
k8s.io/client-go@v0.17.0 github.com/gogo/protobuf@v1.2.2-0.20190723190241-65acae22fc9d
k8s.io/client-go@v0.17.0 github.com/evanphx/json-patch@v4.2.0+incompatible
k8s.io/client-go@v0.17.0 github.com/davecgh/go-spew@v1.1.1
k8s.io/client-go@v0.17.0 github.com/Azure/go-autorest/autorest/adal@v0.5.0
k8s.io/client-go@v0.17.0 github.com/Azure/go-autorest/autorest@v0.9.0
k8s.io/client-go@v0.17.0 cloud.google.com/go@v0.38.0
k8s.io/component-base@v0.17.6 k8s.io/client-go@v0.17.6
k8s.io/component-base@v0.17.4 k8s.io/client-go@v0.17.4
k8s.io/client-go@v0.17.3 sigs.k8s.io/yaml@v1.1.0
k8s.io/client-go@v0.17.3 k8s.io/utils@v0.0.0-20191114184206-e782cd3c129f
k8s.io/client-go@v0.17.3 k8s.io/klog@v1.0.0
k8s.io/client-go@v0.17.3 k8s.io/apimachinery@v0.17.3
k8s.io/client-go@v0.17.3 k8s.io/api@v0.17.3
k8s.io/client-go@v0.17.3 google.golang.org/appengine@v1.5.0
k8s.io/client-go@v0.17.3 golang.org/x/time@v0.0.0-20190308202827-9d24e82272b4
k8s.io/client-go@v0.17.3 golang.org/x/oauth2@v0.0.0-20190604053449-0f29369cfe45
k8s.io/client-go@v0.17.3 golang.org/x/net@v0.0.0-20191004110552-13f9640d40b9
k8s.io/client-go@v0.17.3 golang.org/x/crypto@v0.0.0-20190820162420-60c769a6c586
k8s.io/client-go@v0.17.3 github.com/stretchr/testify@v1.4.0
k8s.io/client-go@v0.17.3 github.com/spf13/pflag@v1.0.5
k8s.io/client-go@v0.17.3 github.com/peterbourgon/diskv@v2.0.1+incompatible
k8s.io/client-go@v0.17.3 github.com/imdario/mergo@v0.3.5
k8s.io/client-go@v0.17.3 github.com/gregjones/httpcache@v0.0.0-20180305231024-9cad4c3443a7
k8s.io/client-go@v0.17.3 github.com/gophercloud/gophercloud@v0.1.0
k8s.io/client-go@v0.17.3 github.com/googleapis/gnostic@v0.0.0-20170729233727-0c5108395e2d
k8s.io/client-go@v0.17.3 github.com/google/uuid@v1.1.1
k8s.io/client-go@v0.17.3 github.com/google/gofuzz@v1.0.0
k8s.io/client-go@v0.17.3 github.com/google/btree@v1.0.0
k8s.io/client-go@v0.17.3 github.com/golang/protobuf@v1.3.2
k8s.io/client-go@v0.17.3 github.com/golang/groupcache@v0.0.0-20160516000752-02826c3e7903
k8s.io/client-go@v0.17.3 github.com/gogo/protobuf@v1.2.2-0.20190723190241-65acae22fc9d
k8s.io/client-go@v0.17.3 github.com/evanphx/json-patch@v4.2.0+incompatible
k8s.io/client-go@v0.17.3 github.com/davecgh/go-spew@v1.1.1
k8s.io/client-go@v0.17.3 github.com/Azure/go-autorest/autorest/adal@v0.5.0
k8s.io/client-go@v0.17.3 github.com/Azure/go-autorest/autorest@v0.9.0
k8s.io/client-go@v0.17.3 cloud.google.com/go@v0.38.0
k8s.io/component-base@v0.17.2 k8s.io/client-go@v0.17.2
knative.dev/pkg@v0.0.0-20200515002500-16d7b963416f k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible
k8s.io/cloud-provider@v0.17.0 k8s.io/client-go@v0.17.0
knative.dev/pkg@v0.0.0-20200520073958-94316e20e860 k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible
k8s.io/apiextensions-apiserver@v0.17.2 k8s.io/client-go@v0.17.2
k8s.io/apiserver@v0.17.0 k8s.io/client-go@v0.17.0
k8s.io/kubectl@v0.17.2 k8s.io/client-go@v0.17.2
knative.dev/pkg@v0.0.0-20200505191044-3da93ebb24c2 k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible
knative.dev/pkg@v0.0.0-20200428194351-90fc61bae7f7 k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible
k8s.io/cli-runtime@v0.17.2 k8s.io/client-go@v0.17.2
k8s.io/cli-runtime@v0.17.3 k8s.io/client-go@v0.17.3
k8s.io/test-infra@v0.0.0-20191212060232-70b0b49fe247 k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible
k8s.io/client-go@v0.17.6 sigs.k8s.io/yaml@v1.1.0
k8s.io/client-go@v0.17.6 k8s.io/utils@v0.0.0-20191114184206-e782cd3c129f
k8s.io/client-go@v0.17.6 k8s.io/klog@v1.0.0
k8s.io/client-go@v0.17.6 k8s.io/apimachinery@v0.17.6
k8s.io/client-go@v0.17.6 k8s.io/api@v0.17.6
k8s.io/client-go@v0.17.6 google.golang.org/appengine@v1.5.0
k8s.io/client-go@v0.17.6 golang.org/x/time@v0.0.0-20190308202827-9d24e82272b4
k8s.io/client-go@v0.17.6 golang.org/x/oauth2@v0.0.0-20190604053449-0f29369cfe45
k8s.io/client-go@v0.17.6 golang.org/x/net@v0.0.0-20191004110552-13f9640d40b9
k8s.io/client-go@v0.17.6 golang.org/x/crypto@v0.0.0-20200220183623-bac4c82f6975
k8s.io/client-go@v0.17.6 github.com/stretchr/testify@v1.4.0
k8s.io/client-go@v0.17.6 github.com/spf13/pflag@v1.0.5
k8s.io/client-go@v0.17.6 github.com/peterbourgon/diskv@v2.0.1+incompatible
k8s.io/client-go@v0.17.6 github.com/imdario/mergo@v0.3.5
k8s.io/client-go@v0.17.6 github.com/gregjones/httpcache@v0.0.0-20180305231024-9cad4c3443a7
k8s.io/client-go@v0.17.6 github.com/gophercloud/gophercloud@v0.1.0
k8s.io/client-go@v0.17.6 github.com/googleapis/gnostic@v0.0.0-20170729233727-0c5108395e2d
k8s.io/client-go@v0.17.6 github.com/google/uuid@v1.1.1
k8s.io/client-go@v0.17.6 github.com/google/gofuzz@v1.0.0
k8s.io/client-go@v0.17.6 github.com/google/btree@v1.0.0
k8s.io/client-go@v0.17.6 github.com/golang/protobuf@v1.3.2
k8s.io/client-go@v0.17.6 github.com/golang/groupcache@v0.0.0-20160516000752-02826c3e7903
k8s.io/client-go@v0.17.6 github.com/gogo/protobuf@v1.2.2-0.20190723190241-65acae22fc9d
k8s.io/client-go@v0.17.6 github.com/evanphx/json-patch@v4.2.0+incompatible
k8s.io/client-go@v0.17.6 github.com/davecgh/go-spew@v1.1.1
k8s.io/apiextensions-apiserver@v0.16.4 k8s.io/client-go@v0.16.4
k8s.io/client-go@v0.17.6 github.com/Azure/go-autorest/autorest/adal@v0.5.0
k8s.io/client-go@v0.17.6 github.com/Azure/go-autorest/autorest@v0.9.0
k8s.io/client-go@v0.17.6 cloud.google.com/go@v0.38.0
k8s.io/legacy-cloud-providers@v0.17.0 k8s.io/client-go@v0.17.0
k8s.io/apiserver@v0.16.4 k8s.io/client-go@v0.16.4
k8s.io/client-go@v0.16.4 cloud.google.com/go@v0.38.0
k8s.io/client-go@v0.16.4 github.com/Azure/go-autorest/autorest@v0.9.0
k8s.io/client-go@v0.16.4 github.com/Azure/go-autorest/autorest/adal@v0.5.0
k8s.io/client-go@v0.16.4 github.com/davecgh/go-spew@v1.1.1
k8s.io/client-go@v0.16.4 github.com/evanphx/json-patch@v4.2.0+incompatible
k8s.io/client-go@v0.16.4 github.com/gogo/protobuf@v1.2.2-0.20190723190241-65acae22fc9d
k8s.io/client-go@v0.16.4 github.com/golang/groupcache@v0.0.0-20160516000752-02826c3e7903
k8s.io/client-go@v0.16.4 github.com/golang/protobuf@v1.3.1
k8s.io/client-go@v0.16.4 github.com/google/gofuzz@v1.0.0
k8s.io/client-go@v0.16.4 github.com/googleapis/gnostic@v0.0.0-20170729233727-0c5108395e2d
k8s.io/client-go@v0.16.4 github.com/gophercloud/gophercloud@v0.1.0
k8s.io/client-go@v0.16.4 github.com/gregjones/httpcache@v0.0.0-20170728041850-787624de3eb7
k8s.io/client-go@v0.16.4 github.com/imdario/mergo@v0.3.5
k8s.io/client-go@v0.16.4 github.com/peterbourgon/diskv@v2.0.1+incompatible
k8s.io/client-go@v0.16.4 github.com/spf13/pflag@v1.0.3
k8s.io/client-go@v0.16.4 github.com/stretchr/testify@v1.3.0
k8s.io/client-go@v0.16.4 golang.org/x/crypto@v0.0.0-20190611184440-5c40567a22f8
k8s.io/client-go@v0.16.4 golang.org/x/net@v0.0.0-20190812203447-cdfb69ac37fc
k8s.io/client-go@v0.16.4 golang.org/x/oauth2@v0.0.0-20190604053449-0f29369cfe45
k8s.io/client-go@v0.16.4 golang.org/x/time@v0.0.0-20181108054448-85acf8d2951c
k8s.io/client-go@v0.16.4 google.golang.org/appengine@v1.5.0
k8s.io/client-go@v0.16.4 k8s.io/api@v0.16.4
k8s.io/client-go@v0.16.4 k8s.io/apimachinery@v0.16.4
k8s.io/client-go@v0.16.4 k8s.io/klog@v0.4.0
k8s.io/client-go@v0.16.4 k8s.io/utils@v0.0.0-20190801114015-581e00157fb1
k8s.io/client-go@v0.16.4 sigs.k8s.io/yaml@v1.1.0
k8s.io/apiserver@v0.17.6 k8s.io/client-go@v0.17.6
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a github.com/Azure/go-autorest@v11.1.2+incompatible
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a github.com/davecgh/go-spew@v1.1.1
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a github.com/dgrijalva/jwt-go@v0.0.0-20160705203006-01aeca54ebda
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a github.com/evanphx/json-patch@v0.0.0-20190203023257-5858425f7550
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a github.com/gogo/protobuf@v0.0.0-20171007142547-342cbe0a0415
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a github.com/golang/groupcache@v0.0.0-20160516000752-02826c3e7903
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a github.com/golang/protobuf@v1.2.0
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a github.com/google/btree@v0.0.0-20160524151835-7d79101e329e
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a github.com/google/gofuzz@v0.0.0-20170612174753-24818f796faf
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a github.com/googleapis/gnostic@v0.0.0-20170729233727-0c5108395e2d
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a github.com/gophercloud/gophercloud@v0.0.0-20190126172459-c818fa66e4c8
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a github.com/gregjones/httpcache@v0.0.0-20170728041850-787624de3eb7
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a github.com/imdario/mergo@v0.3.5
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a github.com/peterbourgon/diskv@v2.0.1+incompatible
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a github.com/spf13/pflag@v1.0.1
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a github.com/stretchr/testify@v1.2.2
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a golang.org/x/crypto@v0.0.0-20181025213731-e84da0312774
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a golang.org/x/net@v0.0.0-20190812203447-cdfb69ac37fc
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a golang.org/x/oauth2@v0.0.0-20190402181905-9f3314589c9a
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a golang.org/x/time@v0.0.0-20161028155119-f51c12702a4d
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a google.golang.org/appengine@v1.5.0
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a k8s.io/api@v0.0.0-20190918195907-bd6ac527cfd2
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a k8s.io/klog@v0.3.1
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a k8s.io/utils@v0.0.0-20190221042446-c2654d5206da
k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a sigs.k8s.io/yaml@v1.1.0
k8s.io/apiextensions-apiserver@v0.17.6 k8s.io/client-go@v0.17.6
k8s.io/test-infra@v0.0.0-20200407001919-bc7f71ef65b8 k8s.io/client-go@v9.0.0+incompatible
k8s.io/apiextensions-apiserver@v0.0.0-20190918201827-3de75813f604 k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a
k8s.io/component-base@v0.16.4 k8s.io/client-go@v0.16.4
k8s.io/apiserver@v0.0.0-20190918200908-1e17798da8c1 k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a
knative.dev/pkg@v0.0.0-20200605170718-b7125260dc6f k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible
knative.dev/pkg@v0.0.0-20200603222317-b79e4a24ca50 k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible
sigs.k8s.io/controller-runtime@v0.3.0 k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a
sigs.k8s.io/controller-runtime@v0.5.0 k8s.io/client-go@v0.17.2
</details>

As you mentioned, the `v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible` is definitely a higher version than `v0.18.3`, but according to the https://github.com/kubernetes/client-go/blob/master/INSTALL.md, the `v0.18.3` tag is for kubernetes version 1.18, which supported newer version of kubernetes.

You mentioned to replace the source code, you mean replace the `v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible` with the `v0.18.3` version's commit?

**Comment by bcmills** [comment]
It looks like your main dependency on `v11.0.1-…` is via `knative.dev/pkg`, so in order to drop below `v11.0.1` you'll need to either drop that dependency, or send that project a PR to switch it over to a `v0` version of the dependency and then update your dependency on `knative.dev/pkg` to pull in the patch.

**Comment by bcmills** [comment]
For a long-term fix, consider adding a report of your experience to kubernetes/client-go#749.

Ultimately, it's up to the Kubernetes folks to decide whether or how to update their versioning strategy to bring the tagged versions in line with semantic versioning. (I don't see any plausible way that the `go` command could interpret `v0.18.3` as higher than, say, `v1.5.1`, let alone `v11.0.1`.)

**Comment by cplayer** [comment]
Thanks for mentioning that issue, I'm gonna use `replace` as a temporary solution.
