### ISSUE TITLE
runtime: out of memory: cannot allocate 327434997084454912-byte block (4096000 in use) fatal error: out of memory

### ISSUE THREAD

**Issue by 153104373** [golang/go#39423]
Excuse me.I want to write a DLL for RSA encryption and decryption. In golang, there is no problem with the program, but I have exported it as a DLL file. I want to call it with C #, and the result indicates that there is not enough memory. How can I solve it?The source file is dll_code.zip.thanks
![1](https://user-images.githubusercontent.com/59162160/83905631-98df7080-a794-11ea-966e-71f8e0f867ce.png)
![2](https://user-images.githubusercontent.com/59162160/83905637-9da42480-a794-11ea-8c7e-fd5daf6203a9.png)
![3](https://user-images.githubusercontent.com/59162160/83905648-a137ab80-a794-11ea-87f4-3a7edafe7a8e.png)

[main.txt](https://github.com/golang/go/files/4737576/main.txt)

**Comment by 153104373** [comment]
[main (1).txt](https://github.com/golang/go/files/4737608/main.1.txt)

**Comment by 153104373** [comment]
[dll_code.zip](https://github.com/golang/go/files/4737619/dll_code.zip)

**Comment by 153104373** [comment]
[main.txt](https://github.com/golang/go/files/4737620/main.txt)

**Comment by 153104373** [comment]
This code is in zip

**Comment by jeremyfaller** [comment]
Without know which version of Go you're using your stack traces aren't the most helpful, and how you're building the binary is important here, which you also don't specify. Without that data, and guessing, I don't think you're building the go code correctly as a shared library.

I'm not terribly familiar with building DLLs in Windows with Go, but the answers over at StackOverflow look correct to me:

https://stackoverflow.com/questions/40573401/building-a-dll-with-go-1-7

I'd bet if you start from that as an example, you'll have it going in no time.

Closing this issue as it doesn't really seem to be a Go issue to me.

**Comment by 153104373** [comment]
My  go version is  go1.14.2 windows/amd64
