### ISSUE TITLE
x/sys/windows: missing process working size system calls

### ISSUE THREAD

**Issue by awnumar** [golang/go#39422]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes. The currently exposed system calls can be seen at https://pkg.go.dev/golang.org/x/sys/windows?tab=doc

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/awn/.cache/go-build"
GOENV="/home/awn/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/awn/projects/src/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/awn/projects/src/sys/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build786429694=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

When using `VirtualLock` (which is available in the standard library) on Windows sometimes this fails due to the process's limit being reached. See https://github.com/awnumar/memcall/issues/3 for an example.

The workaround for this in the [docs](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtuallock) is to call [SetProcessWorkingSetSize](https://docs.microsoft.com/en-gb/windows/win32/api/winbase/nf-winbase-setprocessworkingsetsize).

### What did you expect to see?

The SetProcessWorkingSetSize and related system calls exposed in the `x/sys/windows` API. 

### What did you see instead?

They are not defined.

**Comment by dmitshur** [comment]
Thanks for sending a PR that'll fix this issue @awnumar.

It's expected that this issue will need to transition to the NeedsFix state before you should proceed with the change. There's more information [here](https://golang.org/doc/contribute.html#before_contributing).
