### ISSUE TITLE
random string generator

### ISSUE THREAD

**Issue by mostafasolati** [golang/go#39439]
I think it would be nice if there is a random string generator in the standard library.
It can be in math/rand package.

**Comment by mvdan** [comment]
You can aready read random bytes: https://golang.org/pkg/math/rand/#Read

If that is not enough, you should clarify why. As far as I can see, as long as you can obtain any amount of random bytes, you can do anything from there.

**Comment by mostafasolati** [comment]
Thanks for your response. Yes, there is rand.Read but you don't have control on the output characters sometimes you need to generate a random string based on a given character set.
I think of something like.
rand.String("AZXEgewdd1234$#!@*&")

**Comment by mvdan** [comment]
That's a higher level abstraction you could build on top of random bytes or integers. There's really no reason to put it in the package API. Different people will want different kinds of "random strings" too, so I also doubt that a single API would be universally useful.
