### ISSUE TITLE
How can I make sure I have  installed Go in mips

### ISSUE THREAD

**Issue by leonardodream** [golang/go#39438]
I can not make sure I have installd Go in mips，So  what  should I do?

**Comment by leonardodream** [comment]
When I input "go --version"，the system said  command  not  found to  me，it's means that I have not install the Golang，right？

**Comment by leonardodream** [comment]
mips系统是不是内置了go，我需要再重装的时候选什么配置么？

**Comment by leonardodream** [comment]
Whether the operating system has built-in Golang module?My OS is NeoKylin，mips64

**Comment by ianlancetaylor** [comment]
For questions about Go, please see https://golang.org/wiki/Questions.

I agree that it sounds like you have not installed Go.  If you want help, please use a forum, and please see exactly what you did to install Go.
