### ISSUE TITLE
mips32: object is FP32 while it claim as FPXX

### ISSUE THREAD

**Issue by wzssyqa** [golang/go#39435]
[MIPS32: switch to fpxx from fp32 or even fp64](https://github.com/golang/go/issues/39289)
In Long term, we should switch to FPXX or FP64, so I keep #39289 open

To add .gnu.attributes and .MIPS.abiflags section, currently we can just use -mfp32 option to gcc:
```
--- a/src/cmd/go/internal/work/exec.go
+++ b/src/cmd/go/internal/work/exec.go
@@ -2411,7 +2411,7 @@ func (b *Builder) gccArchArgs() []string
        case "mips64", "mips64le":
                return []string{"-mabi=64"}
        case "mips", "mipsle":
-               return []string{"-mabi=32", "-march=mips32"}
+               return []string{"-mabi=32", "-march=mips32", "-mfp32"}
        case "ppc64":
                if cfg.Goos == "aix" {
                        return []string{"-maix64"}
```

**Comment by wzssyqa** [comment]
For exe that is not linked with libc etc, It will contains no .gnu.attributes and .MIPS.abiflags section, kernel will treat them as FP32. It make it just work.

**Comment by draganmladjenovic** [comment]
@cherrymui

**Comment by cherrymui** [comment]
The proposed change looks good to me. Want to send a CL? Thanks.

I think you may also want to do a similar change in cmd/cgo/gcc.go.

For a side note,  I wonder if we want to pass softfloat flags to C compiler if softfloat is set.

Also cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
I agree about passing `-msoft-float` when appropriate.

Do we currently assume 32-bit floating point registers in the Go compiler?  If so I agree about passing `-mfp32`.  At some point the Go linker will need to generate the appropriate sections.

**Comment by cherrymui** [comment]
> Do we currently assume 32-bit floating point registers in the Go compiler?

Yes.

**Comment by wzssyqa** [comment]
> Do we currently assume 32-bit floating point registers in the Go compiler? If so I agree about passing `-mfp32`. At some point the Go linker will need to generate the appropriate sections.

Yes. #39289 is about it.
Now we spilt a ldc1 into 2 lwc1, which makes assume 32-bit float FPR.
Before we assume that we are full FPXX support, we need more investment.

**Comment by wzssyqa** [comment]
Or, should we split it to 2 patch?

**Comment by wzssyqa** [comment]
what's more should I do?

**Comment by cherrymui** [comment]
> what's more should I do?

As far as I can tell, nothing. Thanks for sending the CL.
