### ISSUE TITLE
go get not working

### ISSUE THREAD

**Issue by GabielFemi** [golang/go#39452]
### What version of Go are you using (`go version`)?

<pre>
go.1.14.3

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
linux-amd64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?
src folder containing github.com/gorilla/mux

### What did you see instead?
only a pkg directory in my "gopath" with mod "sumdb" as subfolders.

**Comment by davecheney** [comment]
Hi @GabielFemi, could you please finish filling out the template, you missed the “what did you do” section.

**Comment by GabielFemi** [comment]
I figured the mistake out. I've fixed it, tho'
