### ISSUE TITLE
runtime: minpc or maxpc invalid on windows/arm

### ISSUE THREAD

**Issue by zx2c4** [golang/go#39465]
I installed 386 go 1.14.4 onto Windows 10 arm64 to C:\go. Then I cross compiled go 1.14.4 for Windows using `CGO_ENABLED=0 GOOS=windows GOARCH=arm GOARM=7 ./make.bash`, and then copied bin/ and pkg/ over to C:\go\bin and C:\go\pkg. Then I ran `.\all.bat` inside of the latest git master (e64675a79 as of writing) and kaboom:

![image](https://user-images.githubusercontent.com/10643/84096794-04595600-a9c0-11ea-9575-41aade5fb015.png)

cc @aclements @alexbrainman @rozmansi

**Comment by zx2c4** [comment]
Running a second time gives me:

![image](https://user-images.githubusercontent.com/10643/84097299-6797b800-a9c1-11ea-8ea2-f91bc4862874.png)

I wonder if this is another variant of #38440 hitting more often by virtue of being inside of an emulator.

**Comment by msuiche** [comment]
It would be nice if there was a native ARM64 build of golang for Windows. Linux has one, why not Windows?

**Comment by zx2c4** [comment]
What's the relevance of your request (which is handled [by this issue](https://github.com/golang/go/issues/36439)) to this bug report? I agree with you, but I don't see how it helps here.

**Comment by thanm** [comment]
I'd like to point out that we don't seem to have any Windows/ARM builders at the moment, and the person nominally listed as the Windows/ARM port seems to be MIA.  It is hard to see how to work on this bug without a functioning builder.

**Comment by toothrot** [comment]
Please follow #38607 for planning around Windows ARM builders, and add any help you can there.

**Comment by zx2c4** [comment]
Closing in favor of https://github.com/golang/go/issues/42786
