### ISSUE TITLE
x/tools/gopls: implement callHierarchy

### ISSUE THREAD

**Issue by josh-tepper-clarifai** [golang/go#39461]
I'd love to see gopls implement the new LSP Call Hierarchy feature.  I'd look forward to using it in VSCode which already supports it.

This was discussed as a "Preview Feature" in the VSCode release notes from March:
https://code.visualstudio.com/updates/v1_33#_preview-features

At the time, this LSP API was still in preview, but with the upcoming 3.16 LSP specification, I believe that this is no longer the case:
https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/

As you can see from the screenshot included in the VSCode release notes, VSCode provides a nice ui when the language server implements this:
![call-hierarchy](https://user-images.githubusercontent.com/60625808/84081218-8a1ed680-a9ab-11ea-823d-947d26d09f57.png)

I see that others have requested this feature on the vscode-go repo, but I don't see a ticket here:
https://github.com/microsoft/vscode-go/issues/2682

I share the sentiment of the other user: this would be a great addition and would be very useful for me in my day to day work.

**Comment by josh-tepper-clarifai** [comment]
I wanted to follow up on this ticket.  I think that this type of interface would be a big asset when trying to quickly understand a piece of code

**Comment by stamblerre** [comment]
Agreed! We intend to support all LSP features in the future, but this isn't as high priority as some other bug fixes / features that we're currently working on.

**Comment by josh-tepper-clarifai** [comment]
Got it.  Sounds good

**Comment by dandua98** [comment]
Closed by commit b793a13
