### ISSUE TITLE
contribution best practice

### ISSUE THREAD

**Issue by mostafasolati** [golang/go#39469]
Hi everyone.
I have a question, I don't know if it's a good place to ask or not. 
I apologize in advance if it's not the proper place.

I want to add examples for some methods of a package. What is best practice for doing that?
An example in each CL or multiple examples in one CL?

**Comment by martisch** [comment]
Hi,

It is better to ask these kind of questions on the golang-dev mailing list or #contributing in Gophers Slack. See https://github.com/golang/go/wiki/Questions.

My personal opinion is that it matters how many lines there are in the CL, how complex the examples are and how closely related they are. For examples in different pakages I would start with separate CLs.
