### ISSUE TITLE
Is this expected? time.Now().Before(time.Unix(2<<62 - 1, 0))  = false

### ISSUE THREAD

**Issue by keenangebze** [golang/go#39477]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Not yet tested

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/nakama/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/nakama/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build340274852=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
package main

import (
        "fmt"
        "time"
)

func main() {
        today := time.Now()
        future := time.Unix(2<<62 - 1, 0)

        fmt.Println(today, future)
        fmt.Println(today.Before(future))
}

```

### What did you expect to see?
```
2020-06-09 21:40:19.250234793 +0700 WIB m=+0.000164020 292277026596-12-04 22:30:07 +0700 WIB
true
```

### What did you see instead?
```
2020-06-09 21:40:19.250234793 +0700 WIB m=+0.000164020 292277026596-12-04 22:30:07 +0700 WIB
false
```

**Comment by seankhliao** [comment]
https://golang.org/pkg/time/#Unix
> Not all sec values have a corresponding time value. One such value is 1<<63-1 (the largest int64 value).

**Comment by ALTree** [comment]
What @seankhliao said. Note that `2<<62 == 1<63`. Closing here, since this is working as documented.
