### ISSUE TITLE
Go mod error loading requirements and unknown revisions

### ISSUE THREAD

**Issue by leguminosa** [golang/go#39475]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

haven't tried

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/nakama/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/nakama/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/nakama/workspace/tokopedia/rechargeapp/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build149754141=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
$ go mod tidy -v
</pre>

### What did you expect to see?

process success

### What did you see instead?

<details><summary><code>go mod tidy -v</code> Output</summary><br><pre>
$ go mod tidy -v
Fetching https://gopkg.in/go-playground/assert.v1?go-get=1
Fetching https://gopkg.in/ini.v1?go-get=1
Fetching https://gopkg.in/h2non/gock.v1?go-get=1
Fetching https://gopkg.in/resty.v1?go-get=1
Parsing meta tags from https://gopkg.in/h2non/gock.v1?go-get=1 (status code 200)
Parsing meta tags from https://gopkg.in/resty.v1?go-get=1 (status code 200)
Parsing meta tags from https://gopkg.in/ini.v1?go-get=1 (status code 200)
Parsing meta tags from https://gopkg.in/go-playground/assert.v1?go-get=1 (status code 200)
get "gopkg.in/ini.v1": found meta tag get.metaImport{Prefix:"gopkg.in/ini.v1", VCS:"git", RepoRoot:"https://gopkg.in/ini.v1"} at https://gopkg.in/ini.v1?go-get=1
get "gopkg.in/resty.v1": found meta tag get.metaImport{Prefix:"gopkg.in/resty.v1", VCS:"git", RepoRoot:"https://gopkg.in/resty.v1"} at https://gopkg.in/resty.v1?go-get=1
get "gopkg.in/go-playground/assert.v1": found meta tag get.metaImport{Prefix:"gopkg.in/go-playground/assert.v1", VCS:"git", RepoRoot:"https://gopkg.in/go-playground/assert.v1"} at https://gopkg.in/go-playground/assert.v1?go-get=1
get "gopkg.in/h2non/gock.v1": found meta tag get.metaImport{Prefix:"gopkg.in/h2non/gock.v1", VCS:"git", RepoRoot:"https://gopkg.in/h2non/gock.v1"} at https://gopkg.in/h2non/gock.v1?go-get=1
go: finding gopkg.in/ini.v1 v1.44.0
go: finding gopkg.in/resty.v1 v1.9.1
go: finding gopkg.in/ini.v1 v1.42.0
go: finding gopkg.in/go-playground/assert.v1 v1.2.1
go: finding gopkg.in/h2non/gock.v1 v1.0.15
go: gopkg.in/h2non/gock.v1@v1.0.15: unknown revision v1.0.15
go: gopkg.in/go-playground/assert.v1@v1.2.1: unknown revision v1.2.1
go: gopkg.in/resty.v1@v1.9.1: unknown revision v1.9.1
go: gopkg.in/ini.v1@v1.42.0: unknown revision v1.42.0
go: gopkg.in/ini.v1@v1.44.0: unknown revision v1.44.0
go: error loading module requirements
</pre></details>

**Comment by leguminosa** [comment]
yes I installed `gvm` yesterday shortly after creating this ticket,

<pre>
$ gvm list

gvm gos (installed)

=> go1.13
   system

</pre>

and then `go mod tidy -v` succeed.

And I ran those commands from my (zsh) terminal outside vscode.

Then I had problem when doing things from vscode terminal / tools (run `go mod tidy -v`, automated coverage test on save, problems tab) and when I check `go version`, `go env` from vscode terminal, it still shows 1.12.7 and old GOPATH (as opposed to new one by gvm)

What is the solution for those so that my vscode is aligned with the gvm ? 

Then I also found gvm extension on vscode, I installed it, set the go to 1.13 like I did before, and finally the go version on vscode matches with the terminal outside vscode.

**Comment by bcmills** [comment]
I have no idea about `gvm` or how it works. Generally extensions like `vscode` should use whichever `go` command is first in `$PATH`, so you might check what `PATH` you're running `vscode` with. (If you're starting `vscode` using a GUI, typically that environment is set in your `.profile` script rather than `.zshrc`, and you'll need to log out and back in to pick up changes.)

**Comment by leguminosa** [comment]
well...since I have used the gvm ext inside the vscode, ofc now the `$PATH` or anything has already pointed to the go version I chose via gvm...so in a nutshell this problem is solved.

Anyway thank you for your assistance and pointing out the root cause (outdated go version) of the original problem. Have a good day.
