### ISSUE TITLE
cmd/go: don't follow an infinite number of redirects

### ISSUE THREAD

**Issue by oiooj** [golang/go#39482]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/data/golang"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build483816322=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
go get -d golang.kxv.io/too/many/redirects
```

`golang.kxv.io/too/many/redirects` will redirects 15 times now, go cmd will hangs until all redirects finished. It's very dangerous.

### What did you expect to see?

success

### What did you see instead?

Go cmd hangs

/cc @bcmills @jayconrod @FiloSottile

**Comment by oiooj** [comment]
Should this fix back port to `go1.14`? @bcmills @ianlancetaylor

**Comment by jayconrod** [comment]
I'd lean toward not backporting. [MinorReleases](https://github.com/golang/go/wiki/MinorReleases) describes the changes that should be backported: fixes for security issues, serious problems with no workaround, and documentation fixes.

This fix provides a good error message when we send a request to a misconfigured server (as opposed to hanging in a redirect loop). I don't think it's a security issue though.

**Comment by bcmills** [comment]
I'm ambivalent on backporting. On the one hand, a hung `go` command can be very difficult to diagnose. On the other hand, it's easy to terminate such a command to un-stick it.
