### ISSUE TITLE
go.dev: Package version not showing up.

### ISSUE THREAD

**Issue by jcgregorio** [golang/go#39486]
The v1.3.0 version of github.com/skia-dev/go2ts is not appearing on pkg.go.dev.

### What is the URL of the page with the issue?

 https://pkg.go.dev/github.com/skia-dev/go2ts?tab=versions
 
### What is your user agent?
 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
 
 
 
### Screenshot
![screenshot](https://user-images.githubusercontent.com/1726460/84181478-f73b7600-aa56-11ea-83fc-0c696f3d88ac.jpeg)
 
 
 
 
### What did you do?
I followed the directions and ran the following to try to get it to update:

 GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/skia-dev/go2ts@v1.3.0

That command succeeds w/o error. 
 
### What did you expect to see?
I expected the page to update to include the v1.3.0 release. 
 
 
### What did you see instead?

v1.3.0 release doesn't show up.

**Comment by kispilz** [comment]
That's because their corporate identity is getting in the way of rational human decisions thus obstructing their thoughtflow with stupid, too much processor air vs sane common sense.

Careful you might by banned for criticizing the corporate overlords for their website.

**Comment by jcgregorio** [comment]
I'm sorry, this comment is not helpful and adds nothing to the discussion.

> That's because their corporate identity is getting in the way of rational human decisions thus obstructing their thoughtflow with stupid, too much processor air vs sane common sense.
> 
> Careful you might by banned for criticizing the corporate overlords for their website.

**Comment by julieqiu** [comment]
@jcgregorio - thanks for reporting! It seems like there was a delay - the latest version should now be v1.3.0. We are working on adding support for #37002, so that this process is more intuitive in the future.
