### ISSUE TITLE
regexp: MatchString run time could be independent of the string length

### ISSUE THREAD

**Issue by opennota** [golang/go#39480]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.14.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xxx/.cache/go-build"
GOENV="/home/xxx/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xxx/gocode"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/home/xxx/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/home/xxx/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/xxx/gocode/src/gitlab.com/opennota/tl/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build900652540=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

`go test -bench=.`

https://play.golang.org/p/VD6DFGlxha-

### What did you expect to see?

Both benchmarks show about the same ns/op. 

### What did you see instead?

```
BenchmarkLength1-4      13320451                89.7 ns/op
BenchmarkLength1M-4      8138482               143 ns/op
```

The difference seems to be constant, but it's a bit surprising.

**Comment by randall77** [comment]
Run the CPU profiler and see where the extra time is going.

**Comment by opennota** [comment]
It looks like RE2 uses backtracking for strings which are short enough, and does not for longer ones. So this difference in speed is probably expected.
