### ISSUE TITLE
Why is the UDP transport locked in the WriteTo function？

### ISSUE THREAD

**Issue by YIDWang** [golang/go#39496]
![image](https://user-images.githubusercontent.com/20499178/84225444-b48aa400-ab11-11ea-9bba-5fdf9af1871c.png)
Udp is a bounded transport and does not need to be thread-safe.

**Comment by YIDWang** [comment]
Can you help me out?

**Comment by ianlancetaylor** [comment]
Please use text, not images.  Images are much harder to read.  Thanks.

We don't use the issue tracker for questions.  If you want to ask a question, you will get better and faster answers using a forum.  See https://golang.org/wiki/Questions.

We lock the `FD` to ensure that nothing else changes it during the `write` operation.  UDP sockets don't need to be thread safe, but the `FD` structure is handling other things as well, notably the interaction with the runtime poller.
