### ISSUE TITLE
x/build/cmd/release: leave oldlink binary out of RC1 (if the beta doesn't uncover serious linker issues)

### ISSUE THREAD

**Issue by toothrot** [golang/go#39509]
As part of https://golang.org/s/better-linker, we now build a binary called `oldlink` in our release of Go. While it may be useful to include in the beta, we should make a decision on whether this is included in the RC or final releases of Go 1.15, vs asking people to rebuild it on their own if necessary.

/cc @cherrymui @aclements @golang/osp-team

**Comment by aclements** [comment]
It was really @toothrot 's suggestion, so I think we're all in agreement. :)

**Comment by dmitshur** [comment]
> A test may fail if the old linker is not present. We could change the test to skip if the binary does not exist.

@cherrymui Which test were you referring to?

I can try to find anything by taking go1.15beta1, removing the `oldlink` binary, then seeing if anything comes up during `go test std cmd`.

**Comment by cherrymui** [comment]
> @cherrymui Were you referring to a specific test? 

`TestOldLink` in `cmd/link`.

**Comment by dmitshur** [comment]
Thanks!

This is how the test fails when `oldlink` binary isn't present:

```
$ go test -v -run=TestOldLink -count=1 cmd/link
=== RUN   TestOldLink
    link_test.go:558: [/tmp/tmp.AG3oE0Ne/go/bin/go run -gcflags=all=-go115newobj=false -asmflags=all=-go115newobj=false -ldflags=-go115newobj=false /tmp/TestOldLink814981397/main.go]: exit status 2:
        # command-line-arguments
        2020/07/14 18:36:02 invoke oldlink failed:fork/exec /tmp//tmp.AG3oE0Ne/go/pkg/tool/darwin_amd64/oldlink: no such file or directory
--- FAIL: TestOldLink (0.14s)
FAIL
FAIL	cmd/link	0.269s
```

It's going to affect people who try to run `go test cmd/link` after installing a binary release of Go from https://golang.org/dl.

Given that 1.15 is shipping a new linker, it's better to avoid misleading test failures, so skipping the test if `oldlink` binary isn't available seems like a good solution.

**Comment by toothrot** [comment]
The binary was removed from releases in https://golang.org/cl/242643, but the commit message incorrectly failed to mention the repository to reference this issue.
