### ISSUE TITLE
Proposal: create a plugin from byte array.

### ISSUE THREAD

**Issue by yur4uj** [golang/go#39508]
It would be nice to create a Plugin from general byte array, not only from file system path.

**Comment by yur4uj** [comment]
> What does that mean? Can you show an example of how it might work?

For now we could create a plugin with
  plugin.Open("/some/path")
But what if we received a plugin from network. We should save it first to filesystem and only than open.

It might work like this
  var arr []byte
  ...
  plugin.Open(arr)
Also with this kind of the creation it becomes possible to guarantee data integrity.

**Comment by ianlancetaylor** [comment]
The way that plugins are currently implemented requires the plugin to be in a separate file.  If we added this new feature, it would be implemented by writing the byte array out to a file first.  Given that implementation constraint, I'm not sure this is very useful.
