### ISSUE TITLE
Unable to install Go to Definition with "go get github.com/zmb3/gogetdoc: mkdir /xxx/: read-only file system"

### ISSUE THREAD

**Issue by aliciayuting** [golang/go#39510]
### What version of Go are you using (`go version`)?  

<pre>
$ go version go1.14.3 darwin/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOTOOLDIR="/usr/local/Cellar/go/1.14.3/libexec/pkg/tool/darwin_amd64"
</pre></details>

### What did you do?
I have tried to change my Read/write authority but it doesn't work.
I've also tried to export paths:
export GOPATH=$HOME/gocode
export PATH=$PATH:$GOPATH/bin

But when I tried to run and install, it its still giving me the error of 
"go get github.com/zmb3/gogetdoc: mkdir /xxx/: read-only file system"

"go get -v github.com/zmb3/gogetdoc"

### What did you expect to see?

I was expecting it to be installed

### What did you see instead?

It gave me error message, and when I tried to go to definition of a function, it is showing "no definition found", even though the function is defined in the same file.

Thank you for your help in advance.

**Comment by toothrot** [comment]
We don't really use our issue tracker for questions. More people will see your question, and you will get better answers, if you ask on a forum rather than on the issue tracker. See https://golang.org/wiki/Questions. People in the forums can explain what is happening here.
