### ISSUE TITLE
buffer.go  Grow() size=500.7MB fatal error: out of memory

### ISSUE THREAD

**Issue by robinsoon** [golang/go#39517]
[buffer.go]

sw.rawData.Bytes()
Buffer Flush
CREATE bytes.Buffer C:\Users\robin\AppData\Local\Temp\excelize-054951619
buf.Grow()  size= 525019669

grow( 525019669 ) tryGrowByReslice
grow( 525019669 ) cap= 0
grow( 525019669 ) makeSlice <<Error
--------------------------------------------------------------------
runtime: out of memory: cannot allocate 525025280-byte block (62652416 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x7b6a60, 0xd)
	D:/Productivity/Go/src/runtime/panic.go:774 +0x64
runtime.largeAlloc(0x1f4b2a15, 0x101, 0x33b40958)
	D:/Productivity/Go/src/runtime/malloc.go:1140 +0x108
runtime.mallocgc.func1()
	D:/Productivity/Go/src/runtime/malloc.go:1033 +0x39
runtime.systemstack(0x345d3ef0)
	D:/Productivity/Go/src/runtime/asm_386.s:399 +0x53
runtime.mstart()
	D:/Productivity/Go/src/runtime/proc.go:1146

<pre>
$ go version 1.13.5 windows/amd64

</pre>

buffer.go  Grow(525019669) 
size=500.7MB 
fatal error: out of memory

**Comment by davecheney** [comment]
What are the details of the system you are running on?
