### ISSUE TITLE
x/pkgsite: searching for "youtube" only show results for github.com/youtube/vitess 

### ISSUE THREAD

**Issue by nickkeets** [golang/go#39525]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/search?q=youtube
 
 
### What did you do?
 
I searched for "youtube" on go.dev
 
 
### What did you expect to see?
 
 Different packages about youtube. I was looking for a package to download youtube videos.

 
### What did you see instead?

Pages and pages of submodules (?) of the github.com/youtube/vitess project. With the exception of the very first result, the first non-vitess result is on page 4 and the next one on page 17.

**Comment by julieqiu** [comment]
This will be addressed #47321, so closing this issue.
