### ISSUE TITLE
cmd/cgo: -godefs mishandles enum value

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#39534]
Reduced test case:

```Go
package p

// enum { IFF_UP = 0x1 };
import "C"

const IFF_UP = C.IFF_UP
```

Running `go tool cgo -godefs x.go` with Go 1.14 produces

```Go
const IFF_UP = 0x1
```

With tip it produces

```Go
const IFF_UP = int32
```

Although `-godefs` is not seriously supported, we shouldn't break it like this.

This may be due to https://golang.org/cl/230037.  CC @mdempsky

**Comment by mdempsky** [comment]
I can look into it, unless you're already doing that.

**Comment by ianlancetaylor** [comment]
I'm looking at it.  I have a fix.

**Comment by tklauser** [comment]
Thanks a lot for fixing this @ianlancetaylor. Just noticed the same behavior while trying to re-generate `x/sys/unix` with go1.15beta1.
