### ISSUE TITLE
regexp/syntax: quadratic time for compilation in some cases

### ISSUE THREAD

**Issue by andybalholm** [golang/go#39542]
As discussed on https://groups.google.com/forum/#!topic/golang-nuts/8M-qVbRKIWA

Playground link to illustrate: https://play.golang.org/p/82UBmyfyqV-

Regular expressions with large numbers of empty alternations are taking a long time to compile. The time required is roughly quadratic in the length of the regex. 

The quadratic algorithm is building the patchlist by repeatedly appending to it. Since it is a linked list with no tail pointer, appending to it is O(n). The `append` method is found in regexp/syntax/compile.go, at line 42.

I don't know that this is exactly a bug, but it is surprising that although executing a regex is linear-time, compiling one isn't. It probably doesn't affect any useful regex, but it might be a DOS vector.

**Comment by krader1961** [comment]
Note that it isn't just empty alternations such as "`x||y`". This affects any alternation where the length of the alternatives is not equal to one. So it also affects "`a|xy|b`" and "`a|b*|c`" but not "`a|b|c`". For any regex written by a human, where the number of alternate values is small, the cost to compile this pattern isn't a problem. But, as the O.P., points out it could be used as a DOS vector by stringing together a huge number of alternatives using the "`|`" operator.

P.S., I haven't looked at the source code but it appears that "`a|b`" is treated as "`[ab]`" based on the runtime cost of compiling such a regex when that pattern is extremely long. However, "`aa|bb`" does not receive that special treatment as it is also quite costly to compile when that pattern is repeated thousands of times.

**Comment by ianlancetaylor** [comment]
CC @rsc in case this has already been addressed in RE2.

**Comment by andybalholm** [comment]
@krader1961 If it happens with longer alternations too, though we don't need to worry about it for regexes written by humans, it could be an issue with regexes written by computers. If I remember right, I've seen JS profanity filters that had their banned word list as a regex, all joined by pipe characters. That style of regex could be a problem if it has thousands of words.

**Comment by junyer** [comment]
Unsurprisingly, "append" is essentially identical in RE2.

**Comment by junyer** [comment]
Fixed in RE2 as per https://github.com/google/re2/commit/e9d517989f66f2e0a24cde42f4d2424dd3e4a9b9. Who wants to make the corresponding change for Go?

**Comment by andybalholm** [comment]
@junyer I'll give it a try.
