### ISSUE TITLE
modules: reuse code between different versions

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [golang/go#39548]
I working on [this](https://github.com/GrigoriyMikhalkin/sqlboiler-paginate) package which has several versions. Versions code located in `vN` packages, and pretty much identical, except for one dependency, which should have different versions. So there's common code for `PaginateParams` and `PaginateParamsParser` between this versions.

My question is, what is best way to reuse this code between different versions? Looks like, if this code is located somewhere else in root module, then root module will be considered as dependency and will be present in `go.mod`. Is there way to avoid that, or should i just replicate code for each version?

**Comment by toothrot** [comment]
For asking questions about learning the language, see one of our forums: https://golang.org/wiki/Questions. We only use this issue tracker for tracking bugs. People in the forums can explain what is happening here.
