### ISSUE TITLE
cmd/compile: can not decrement atomic uint64(0)

### ISSUE THREAD

**Issue by Sasasu** [golang/go#39553]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
https://play.golang.org/p/Qf-Pfg1vzeZ

```go
package main

import "sync/atomic"

func main() {
	var foo uint64 = 1
	atomic.AddUint64(&foo, ^(0))
}
```
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
> on goplayground

</pre></details>

### What did you do?
`atomic.AddUint64(&foo, ^(0))`

according to this
https://github.com/golang/go/blob/509ee7064207cc9c8ac81bc76f182a5fbb877e9b/src/sync/atomic/doc.go#L103-L106

### What did you expect to see?
compile success, decrement `uint64(0)` got undefined behavior.

### What did you see instead?
`constant -1 overflows uint64`

**Comment by DisposaBoy** [comment]
I see you fixed the original issue by switching to `atomic.Add`**U**`int64`.
I think the new error is guarding against what's usually a bug since you can't store a negative number in an unsigned integer.

**Comment by davecheney** [comment]
As the comment says ^uint64(0) is what you need to use. 

https://play.golang.org/p/Ru41D6UTSUb
