### ISSUE TITLE
x/crypto/ed25519: a correction and a suggestion for adding comments for crypto/ed25519

### ISSUE THREAD

**Issue by zhangzhanli** [golang/go#39554]
Firstly, a correction should be in  edwards25519.go:725. There's a mistake in the comment of "FeSub(&u, &u, &p.Z) // y = y^2-1". According to ed's paper, it should have been u = y^2-1.

Secondly, in edwards25519.go:562 " func fePow22523(out, z *FieldElement)" , we can't know what it will do just by the name of the function. Although it's a internal func, I still suggest  adding comments for it, like this:

```
// to cal z ^ (2^252 - 3)
func fePow22523(out, z *FieldElement) {
	var t0, t1, t2 FieldElement
	var i int

	FeSquare(&t0, z)	//2
	for i = 1; i < 1; i++ {
		FeSquare(&t0, &t0)
	}
	FeSquare(&t1, &t0)	//4
	for i = 1; i < 2; i++ {
		FeSquare(&t1, &t1)	//8
	}
	FeMul(&t1, z, &t1)	//9
	FeMul(&t0, &t0, &t1)	//11
	FeSquare(&t0, &t0)	//22
	for i = 1; i < 1; i++ {
		FeSquare(&t0, &t0)
	}
	FeMul(&t0, &t1, &t0)	//31
	FeSquare(&t1, &t0)
	for i = 1; i < 5; i++ {
		FeSquare(&t1, &t1)	//1f
	}
	FeMul(&t0, &t1, &t0)	//0x3ff denoted by 10 1
 	FeSquare(&t1, &t0)
	for i = 1; i < 10; i++ {
		FeSquare(&t1, &t1)
	}
	FeMul(&t1, &t1, &t0)	//20 1
	FeSquare(&t2, &t1)
	for i = 1; i < 20; i++ {
		FeSquare(&t2, &t2)
	}
	FeMul(&t1, &t2, &t1)	//40 1
	FeSquare(&t1, &t1)
	for i = 1; i < 10; i++ {
		FeSquare(&t1, &t1)
	}
	FeMul(&t0, &t1, &t0)	//50 1
	FeSquare(&t1, &t0)
	for i = 1; i < 50; i++ {
		FeSquare(&t1, &t1)
	}
	FeMul(&t1, &t1, &t0)	//100 1
	FeSquare(&t2, &t1)
	for i = 1; i < 100; i++ {
		FeSquare(&t2, &t2)
	}
	FeMul(&t1, &t2, &t1)	//200 1
	FeSquare(&t1, &t1)
	for i = 1; i < 50; i++ {
		FeSquare(&t1, &t1)
	}
	FeMul(&t0, &t1, &t0)	//250 1
	FeSquare(&t0, &t0)
	for i = 1; i < 2; i++ {
		FeSquare(&t0, &t0)
	}
	FeMul(out, &t0, z)	//2^252 - 3
}
```

**Comment by FiloSottile** [comment]
Thank you @zhangzhanli! I spotted and fixed the typo while working one the same code some time ago (https://go-review.googlesource.com/c/go/+/273087) and then commented the Pow22523 body in a derived library that might at some point replace internal/edwards25519 (https://github.com/FiloSottile/edwards25519/commit/8cc8037b17d3c01c3fdf880a2591b7867c3c555b#diff-d06d8ddac2c1a54fad38937cab472d1d7c8afc5641984292e3ced64cc175a2a1R334-R382) partially based on your comments.
