### ISSUE TITLE
go.dev: No way to trigger pkg.go.dev update on Package that *was* missing a license

### ISSUE THREAD

**Issue by ecnepsnai** [golang/go#39564]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/ecnepsnai/logtic
 
### What is your user agent?
 
N/A
 
### Screenshot
 
![Screenshot_2020-06-12 logtic package · pkg go dev](https://user-images.githubusercontent.com/1607109/84536466-c0f23680-aca2-11ea-9242-d27c4be26d38.png)
 
### What did you do?
 
I forgot to include a license on my package, but later corrected it and added a valid MIT license.

Github correctly recognizes the license: https://github.com/ecnepsnai/logtic/blob/master/LICENSE

However I see no way to trigger pkg.go.dev to re-check the package.

I opened https://proxy.golang.org/github.com/ecnepsnai/logtic/@v/v1.4.0.info and have waited 24 hours now with no update.
 
### What did you expect to see?
 
pkg.go.dev to update after including a license
 
### What did you see instead?

pkg.go.dev still showing that there's no valid license

**Comment by julieqiu** [comment]
Thanks for reporting! https://pkg.go.dev/github.com/ecnepsnai/logtic now shows v1.4.0 for me.

We are working on #37002 and #37106 to make this experience better for the future.
