### ISSUE TITLE
x/image/font/sfnt: Integer overflow bug

### ISSUE THREAD

**Issue by dejadejade** [golang/go#39577]
See below fix. x (GlyphIndex) is uint16, and x * 4 can easily get overflowed, this will end up returning incorrect advance or bounding box for a glyph.

```
diff --git a/font/sfnt/sfnt.go b/font/sfnt/sfnt.go
index b6045e7..fc782d8 100644
--- a/font/sfnt/sfnt.go
+++ b/font/sfnt/sfnt.go
@@ -1522,7 +1522,7 @@ func (f *Font) GlyphBounds(b *Buffer, x GlyphIndex, ppem fixed.Int26_6, h font.H
                x = n
        }
 
-       buf, err := b.view(&f.src, int(f.hmtx.offset)+int(4*x), 2)
+       buf, err := b.view(&f.src, int(f.hmtx.offset)+int(x)*4, 2)
        if err != nil {
                return fixed.Rectangle26_6{}, 0, err
        }
@@ -1602,7 +1602,7 @@ func (f *Font) GlyphAdvance(b *Buffer, x GlyphIndex, ppem fixed.Int26_6, h font.
                x = n
        }
 
-       buf, err := b.view(&f.src, int(f.hmtx.offset)+int(4*x), 2)
+       buf, err := b.view(&f.src, int(f.hmtx.offset)+int(x)*4, 2)
        if err != nil {
                return 0, err
        }

```

### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by hrsmntbygo** [comment]
# Go developers are harrassing me

- actively going against my Adsense sites
- actively attacking my github account
- actively deranking my page rank

You want war, you will get war, I promise you that
