### ISSUE TITLE
request: Move from Github

### ISSUE THREAD

**Issue by ghost** [golang/go#39580]
don't do this to us. move to a free software

**Comment by ciami7** [comment]
fuck you github

**Comment by beoran** [comment]
There is something to be said for hosting our code on platforms which are open source, such as gitlab or gitorious. However there is also the inconveniences that go with moving everything as well.

**Comment by ALTree** [comment]
The canonical location for the Go Project repositoritories is https://go.googlesource.com which is powered by gitiles, which is open source (github is just a mirror). Patches and codereviews are handled at gerrit, which is open source. 

The only part of the project that is actually primarily github based is the issue tracker.

One can 1) get the source code and 2) contribute to the project (including sending patches and fixing bugs) without having a github account. You'll have to browse the github issue tracker if you're looking for issues to fix, but you can do that without an account. You can't create a new issue without a github account; and I agree that this is unfortunate.

In general, the project is much less dependant on github that it seems. Request to move away from github has been rejected in the past, and this issue doesn't seem to add much of interest to the discussion, so I'm closing this issue.
