### ISSUE TITLE
Could you please rename master branch?

### ISSUE THREAD

**Issue by blacklivesmatterplease** [golang/go#39589]
Go team has already removed references to those words in other code as I see. Why not change the branch name?

Please consider alternatives such as canary, develop and edge as main has a toxic history associated with it in Asian culture - https://www.nakasendoway.com/the-japanese-family-system/

**Comment by ALTree** [comment]
"master" as used in the branch name comes from latin and just means "main", "principal", "central"; it has nothing to to with slavery or asian family dynamics.
