### ISSUE TITLE
encoding/csv should support quoted content containing escaped quotes like stringified JSON

### ISSUE THREAD

**Issue by cfedersp** [golang/go#39581]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.12.9
</pre>

### Does this issue reproduce with the latest release?

YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/charlesfederspiel/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/charlesfederspiel/projects/golang-demos/ratelimited-priorityqueue/fanout"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/charlesfederspiel/projects/gerrit2/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0p/wk563vb57wnbjrq60dntc2mw0000gn/T/go-build751745538=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I attempted to read a db dump containing a mix of individual column values and json that was formatted in CSV format. encoding/csv panicked on the escaped quotes within the properly quoted json.

### What did you expect to see?

Quoted content should be gracefully placed into a single field value, no matter what is between the quotes.

### What did you see instead?
panic

**Comment by hrsmntbygo** [comment]
# Go developers are harrassing me

- actively going against my Adsense sites
- actively attacking my github account
- actively deranking my page rank

You want war, you will get war, I promise you that

**Comment by cfedersp** [comment]
is fixed by Gerrit change submitted same day.
Change-Id: I5203d6cf468185b3b8f948bc53b352bb70a1ee53

**Comment by ianlancetaylor** [comment]
Can you show us an example of data that was not correctly handled by encoding/csv?  Thanks.

Note that we are very unlikely to add new features to encoding/csv at this point.  There are too many variants of CSV.  We will only patch the package to support the format described in RFC 4180.  If your CSV data does not follow RFC 4180, you should copy and modify encoding/csv to fit your needs.
