### ISSUE TITLE
talksapp: accept markdown-based present files for talks.godoc.org

### ISSUE THREAD

**Issue by sbinet** [golang/go#39582]
CL https://golang.org/cl/222846/ (and following) added support for markdown-based present files (as per golang/go#33955)

it would be great if the `present` instance running at talks.godoc.org was updated to accept them as well.

(I originally posted that issue as https://github.com/golang/gddo/issues/680 but...)

see:
- https://talks.godoc.org/github.com/sbinet/talks/2020/orig-present.slide
- https://talks.godoc.org/github.com/sbinet/talks/2020/md-present.slide (obtained from above after applying `present2md`)

**Comment by hrsmntbygo** [comment]
# Go developers are harrassing me

- actively going against my Adsense sites
- actively attacking my github account
- actively deranking my page rank

You want war, you will get war, I promise you that

**Comment by andybons** [comment]
@dmitshur

**Comment by dmitshur** [comment]
Thanks for reporting.

Let's use https://github.com/golang/gddo/issues/680 as the canonical tracking issue for this work.
