### ISSUE TITLE
go/ast: mention strconv.Unquote in BasicLit documentation

### ISSUE THREAD

**Issue by tenntenn** [golang/go#39590]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tenntenn/Library/Caches/go-build"
GOENV="/Users/tenntenn/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tenntenn/Documents/gopath"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wm/76fqhrc52ls25p4cmjrjbdqh0000gp/T/go-build969893907=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

https://golang.org/pkg/go/ast/#BasicLit

### What did you expect to see?

I propose improve the document of `ast.BasicLit`.

When `BasicLit.Kind` is `token.STRING`, we must call `strconv.Unquote` to get unquoted string value.

So I think the document of `ast.BasicLit` should refer to `strconv.Unquote`.

### What did you see instead?

https://golang.org/pkg/go/ast/#BasicLit

**Comment by ALTree** [comment]
Thanks for the report.

A note from the Proposal Process doc:

> Significant changes to the language, libraries, or tools must be first discussed, and sometimes formally documented, before they can be implemented.

Stress on "significant changes". I don't think a suggestion like this one has to Go trough the heavyweight Proposal Process, so I've changed this to a regular issue with a `needsDecision` label.

**Comment by tenntenn** [comment]
@ALTree 
I got it! Thank you.

**Comment by mvdan** [comment]
The strconv docs do bring this up:

> Unquote and UnquoteChar unquote Go string and rune literals. 

However, I agree that it's not really an answer, because many developers new to go/ast will not know the strconv package all that well. A quick mention in the ast package sounds good to me.

**Comment by mvdan** [comment]
I think you want to mention Unquote for string literals, UnquoteChar for rune literals, ParseInt for integer literals, and ParseFloat for floating point literals. I think that covers all the basic literal kinds, minus IMAG, which I'm not sure about.

**Comment by ALTree** [comment]
> you want to mention Unquote for string literals, UnquoteChar for rune literals, ParseInt for integer literals, and ParseFloat for floating point literals.

This could be okay for completeness' sake but to add a datapoint: I was bitten a couple times by the fact that for strings Value holds `"aaaa"` **including** the `"` chars; on the other hand I never had a problem with e.g. `int`s. 

Mostly because you see that the interface holds a string, so you imagine that for an `int` you'll get a string with the number in it: `1`, and you'll have to call `ParseInt` to get a Go value; on the other hand for `string`s we have this gotcha that the literal is `"aaaa"`, so `go/ast` will return a 6-chars string with `"`s in it. 

So just documenting the string-literal special case with a suggestion to call `Unquote` would help, even if we don't do the same for all the other types. But helping with all of them is fine, too.

**Comment by mvdan** [comment]
Agreed. We don't need to be exhaustive here. Will review now.
