### ISSUE TITLE
regexp: backreference to capturing group breaks if followed by underscore

### ISSUE THREAD

**Issue by ghost** [golang/go#39594]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.14.4
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/a/.cache/go-build"
GOENV="/home/a/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/a/.local/share/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build462357482=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Minimal case: [Play](https://play.golang.org/p/G9urCZ4i_3w)

### What did you expect to see?

I expect the pattern `"$2_$1"` to work without needing to escape into `"${2}_$1"`, as in python etc.

**Comment by andybons** [comment]
@rsc

**Comment by antong** [comment]
This may be counter-intuitive, but if I interpret the documentation correctly, I think this is the way it is supposed to work:

> In the template, a variable is denoted by a substring of the form $name or ${name}, where name is a non-empty sequence of letters, digits, and **underscores.**
> ...
> In the $name form, name is taken to be as long as possible: $1x is equivalent to ${1x}, not ${1}x, and, $10 is equivalent to ${10}, not ${1}0. 

So, the template in the example "$2_$1" is the same as "${2_}${1}", not "${2}_${1}".

**Comment by mattn** [comment]
### JavaScript
```javascript
console.log('foo,bar'.replace(/(\w+),(\w+)/, '$2_$1'));
```
Result is `bar_foo`

### Perl
```perl
my $a = 'foo,bar';
$a =~ s/(\w+),(\w+)/\2_\1/;
warn $a;
```
Result is `bar_foo`

### Ruby
```ruby
puts 'foo,bar'.sub(/(\w+),(\w+)/, '\2_\1')
```
Result is `bar_foo`

So, I propose to fix the behavior of Go.

**Comment by seankhliao** [comment]
Closing as this is consistent with how RE2 handles variables in other implementations as well.
E.g. https://regex101.com/r/LGHaWN/1 marks the replacement as invalid.
