### ISSUE TITLE
cmd/go: clarify "does not contain package" error?

### ISSUE THREAD

**Issue by kstenerud** [golang/go#39593]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\karl\AppData\Local\go-build
set GOENV=C:\Users\karl\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\karl\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\karl\code\winsrv\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\karl\AppData\Local\Temp\go-build530336870=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

**main.go**:

```golang
package main

func main() {

}
```

**go.mod**:

```
module mymod

go 1.13

require golang.org/x/sys v0.0.0-20190204203706-41f3e6584952
```

`go build`

### What did you expect to see?

I expected it to download that version of sys.

### What did you see instead?

```
go: finding module for package golang.org/x/sys
main.go:4:2: module golang.org/x/sys@latest found (v0.0.0-20200610111108-226ff32320da), but does not contain package golang.org/x/sys
```

I wanted version `20190204203706-41f3e6584952` but it's attempting to download `20200610111108-226ff32320da` instead, and also failing for some reason.

**Comment by bcmills** [comment]
> ### What did you do?

Please post the actual program that reproduces the problem. This one does not — the `main.go` file seems to have been oversimplified.

```
mymod$ txtar * </dev/null
-- go.mod --
module mymod

go 1.13

require golang.org/x/sys v0.0.0-20190204203706-41f3e6584952
-- main.go --
package main

func main() {

}

mymod$ go build

mymod$ cat go.mod
module mymod

go 1.13

require golang.org/x/sys v0.0.0-20190204203706-41f3e6584952
```

From the error message you are reporting, I suspect that your actual program includes the line

```go
import (
	"golang.org/x/sys"
)
```

which provokes `go build` to attempt to find some version of a module containing the _package_ `golang.org/x/sys`. The module `golang.org/x/sys` does not have any `.go` source files at its root, so there is no such package (as the error message states).

**Comment by bcmills** [comment]
CC @jayconrod @matloob 

I'm not sure how we could make this clearer without also making it too verbose, but if you have a specific suggestion we could consider it.

**Comment by bcmills** [comment]
CC @jayconrod @matloob 

I'm not sure how we could make this clearer without also making it too verbose, but if you have a specific suggestion we could consider it.

**Comment by kstenerud** [comment]
Maybe keep the current error msg, plus append "No go files found. Are you sure you have the correct import location?"

**Comment by Antonboom** [comment]
+1

**Comment by omkarjoshi** [comment]
hey guys I am also facing same issue. 

My project tree is below,

github.com/
└── omkarjoshi
    └── go-modules
        ├── api
        │   └── api.go
        ├── core
        │   └── print.go
        └── go.mod

My module file = 

module omkar/omkarjoshi/appmodule

go 1.15

replace github.com/omkarjoshi/go-modules/core v0.0.0 => ../../../github.com/omkarjoshi/go-modules

module github.com/omkarjoshi/go-modules@latest found (v0.0.0-20200823212604-5a8df914cc79), but does not contain package github.com/omkarjoshi/go-modules/core

**Comment by grantcurell** [comment]
+1
