### ISSUE TITLE
os.Chmod file.Chmod different behavior on Windows

### ISSUE THREAD

**Issue by TACIXAT** [golang/go#39606]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Didn't try.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOHOSTARCH=amd64
set GOHOSTOS=windows
</pre></details>

### What did you do?

It does not work with `file.Chmod()`.

```go
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()

	fi, err := f.Stat()
	if err != nil {
		return err
	}

	m := fi.Mode()

	err = f.Chmod(m | 0222)
	if err != nil {
		return err
	}
```

### What did you expect to see?

Success.

### What did you see instead?

`chmod C:\Users\me\prog\proj\file.txt: not supported by windows`

It does work with `os.Chmod()`.

```go
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()

	fi, err := f.Stat()
	if err != nil {
		return err
	}

	m := fi.Mode()

	err = os.Chmod(path, m | 0222)
	if err != nil {
		return err
	}
```

I am sure there is some technical explanation for this, but from an API perspective it is a bit annoying.

**Comment by bcmills** [comment]
CC @alexbrainman @mattn 

Could this be due to other stray bits in `m`? (What happens if you use `(m&os.ModePerm)|0222` instead?

**Comment by alexbrainman** [comment]
I briefly looked at this, and it appears that syscall.Fchmod is not implemented, while syscall.Chmod is. I don't remember why it happened this way.

I also noticed that os.TestChmod is skipped on windows. os.TestChmod actually checks that os.File.Chmod works. So, I would start by making os.TestChmod run on windows, and see where it gets you.

I don't see problem implementing syscall.Fchmod, given that we already have syscall.Chmod implementation.

Alex
