### ISSUE TITLE
x/build: plan9-arm builder failing

### ISSUE THREAD

**Issue by fhs** [golang/go#39605]
`plan9-arm` builder has been failing for recent commits, as well as this TryBot run: https://storage.googleapis.com/go-build-log/6840e38d/plan9-arm_1d4b8428.log

Most of the failures have this error:
```
fossil/fossil: walk: newfid 0x1110 in use
```
See:
- TryBot link above
- https://build.golang.org/log/49039afa663cffea812b9d0df77b69ccfb30cdae
- https://build.golang.org/log/848d7a680908b60810bbfe01c958b51295e67166
- https://build.golang.org/log/2037a6b5387075df2a6a8ca19e8af947d6a948bf

Other errors ("clone failed", "i/o on hungup channel")  may be related:
- https://build.golang.org/log/fea5a34fff7e7498d3271e89a79779fd0d259558
- https://build.golang.org/log/5d0213ac92d31b44d6d5dd1c05e03eb8f14fb004

/CC @0intro 

@gopherbot add label Builders, NeedsInvestigation, OS-Plan9

**Comment by 0intro** [comment]
@millerresearch

**Comment by millerresearch** [comment]
Bizarre. I was doing some filesystem cache experiments on a client machine yesterday. It shouldn't be possible for an out-of-spec client to confuse the server enough to interfere with other client sessions, but that might be what happened. I've restarted the builders and I'll keep and eye on them.

**Comment by millerresearch** [comment]
The restarted builders each succeeded with make.rc and then failed to write back the snapshot with context time exceeded.  I wonder if the timeout deadline is long enough to allow for several builders contending for a domestic ADSL connection?

**Comment by millerresearch** [comment]
It turns out the bottleneck for writing back snapshots was not ADSL bandwidth but a slow AoE connection. I've reconfigured and the builders are more reliable now. OK to close the issue, I think.
