### ISSUE TITLE
x/tools/go/pointer: explore Pavlogiannis’s algorithms for APA

### ISSUE THREAD

**Issue by smasher164** [golang/go#39604]
Andreas Pavlogiannis submitted [this paper](https://arxiv.org/abs/2006.01491) to CoRR which presents upper and lower bounds for Andersen's pointer analysis and its variants. Additionally, they present several algorithms for solving them. These include
1. An algorithm to solve exhaustive APA in O(n^3).
2. An algorithm to solve sparse APA in O(n^(3/2)).
3. An algorithm to solve bounded APA with a sub-cubic upper bound.
    - They introduce bounded APA as a practical variant, where they bound the number of statements of the form "_∗a = b represents an indirect assignment c = b, where c is pointed by a_".

Note that these solutions compute reachability on a Dyck graph, which is a flow graph with edges for pointer references and dereferences. We should explore the use of these algorithms in go/pointer’s solver. 

Thoughts?
@alandonovan

**Comment by alandonovan** [comment]
go/pointer is unfortunately not in a good state, as pointer analysis, by its nature, requires making assumptions about the internals of other packages, which makes it very fragile. It usually breaks on each Go release, and few people have sufficient understanding of pointer analysis to fix the breakage.

I think we should delete the package altogether.
