### ISSUE TITLE
x/pkgsite: make LICENSE detection optional in pkgsite codebase (not in pkg.go.dev)

### ISSUE THREAD

**Issue by marwan-at-work** [golang/go#39602]
### Overview

Now that `pkgsite` is open sourced (congrats btw!), developers can run the server for sharing documentation of their private code amongst their internal teams. 

However, private code almost always does not have a LICENSE file in its root repository because employees typically sign a separate agreement stating that the internal code is not to be copied or shared. 

This means that `pkgsite` won't be able to show any documentation for most of the internal code out there (or at least the ones I've worked with as it is hard to quantify what you cannot access). 

One option is to go around and add an appropriate LICENSE for all of the private code that both `pkgsite` can detect: https://pkg.go.dev/license-policy and is an appropriate LICENSE for private code. However, most of the licenses that pkgsite detects seem to be open-source oriented which is a non-starter for private modules. Even if there was a LICENSE that was meant for private-code, it doesn't guarantee that all teams can use it within their private repositories as it requires approvals from their company's legal entities. 

### Proposal
Therefore, it seems like the best option is to add a new configuration to `pkgsite` that bypasses the LICENSE check all together so that developers running the server for their internal teams don't need to go add a LICENSE to all of their private modules while still benefiting from using pkgsite and be able to give feedback! 

Thanks!

**Comment by MicahParks** [comment]
This does not solve this issue, as it is not a pull request, but I have a project that will hard code license respecting off and run `pkgsite` as a docker container. It has a few other use cases too.

I could figure out how to solve this with a flag, then create & submit pull request, unless the Go team is already on the issue.

I was able to use `sed` commands in the `Dockerfile`  I made to manipulate some booleans that allowed the docs to build for projects without permissive licenses. You can see the affected files/lines in any of the `athens.Dockerfile` files in the below projects.

[GitLab project](https://gitlab.com/MicahParks/private-pkgsite)
[GitHub mirror](https://github.com/MicahParks/private-pkgsite)
