### ISSUE TITLE
Can i build static library with 'go build' for android platform?

### ISSUE THREAD

**Issue by flame2017** [golang/go#39608]
When i tried to build a static library with 'go build' tools, i got this error:

**Comment by flame2017** [comment]
# command-line-arguments
invalid value "c-archive" for flag -buildmode: buildmode c-archive not supported on android/arm
.....

it`s a cross-compile Project, my environment is :
export GOOS=android
export GOARCH=arm
export GOARM=7
export CGO_ENABLED=1
export CC=/app/go-hoofoo/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi28-clang
export CXX=/app/go-hoofoo/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi28-clang++

**Comment by flame2017** [comment]
the compile command was: go build -buildmode=c-archive -o libfoo.a  *.go

**Comment by flame2017** [comment]
Can any body help me ?

**Comment by mdlayher** [comment]
Please see https://github.com/golang/go/wiki/Questions.
