### ISSUE TITLE
cmd/go2go: fails to build the testdata

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#39617]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +ad307489d4 2020-06-16 05:49:35 +0000 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/oneofone/code/go/bin"
GOCACHE="/home/oneofone/.cache/go-build"
GOENV="/home/oneofone/.config/go/env"
GOEXE=""
GOFLAGS="-gcflags=-c=16"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/usr/src/go2/src/cmd/go2go/testdata/go2path/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/src/go2/src/cmd/go2go/testdata/go2path"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/src/go2"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/src/go2/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/usr/src/go2/src/cmd/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build427285826=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```sh
$ export GOPATH=/usr/src/go2/src/cmd/go2go/testdata/go2path
$ cd $GOPATH/src/slices
$ go2 tool go2go test
type checking failed for slices
slices.go2:10:2: could not import alg (type checking failed for alg
/tmp/go2go918845650/src/alg/alg.go2:8:8: could not import constraints (open /usr/src/go2/src/cmd/vendor/constraints: no such file or directory)
/tmp/go2go918845650/src/alg/alg.go2:12:5: cannot compare a < b (operator < not defined for T)
/tmp/go2go918845650/src/alg/alg.go2:20:5: cannot compare a < b (operator < not defined for T)
)
```

and without explicit `GOPATH`:

```sh
type checking failed for slices
slices.go2:10:2: could not import alg (cannot find package "alg" in any of:
/usr/src/go2/src/alg (from $GOROOT)
/home/oneofone/go/src/alg (from $GOPATH))
slices.go2:11:2: could not import constraints (cannot find package "constraints" in any of:
/usr/src/go2/src/constraints (from $GOROOT)
/home/oneofone/go/src/constraints (from $GOPATH))
slices_test.go2:46:18: cannot convert 1 (untyped int constant) to Elem
slices_test.go2:46:32: cannot convert 1 (untyped int constant) to Elem
```

**Comment by ianlancetaylor** [comment]
You need to set `GO2PATH`, not `GOPATH`, to find .go2 packages.  Closing, but please comment if it still doesn't work.
