### ISSUE TITLE
x/pkgsite: data race when handling errors rendering the status page

### ISSUE THREAD

**Issue by uhthomas** [golang/go#39611]
### What is the URL of the page with the issue?
 
 N/A
 
### What is your user agent?
 

 
N/A 
 
### Screenshot
 

 
 N/A
 
### What did you do?
 

 
 N/A
 
### What did you expect to see?
 
 Out of curiosity, I was reading the source for pkgsite, and came across [this func](https://github.com/golang/pkgsite/blob/5ae7386a8ff7d9caec4c44f8ce68f402793f3954/internal/worker/server.go#L342) which has a racy assignment to `errString`.
 
### What did you see instead?

A non-racy assignment to `errString`.

---

Is this tracked elsewhere? If not, I don't mind picking it up 😄

**Comment by julieqiu** [comment]
It's not - feel free to send a fix! 

/cc @jba

**Comment by uhthomas** [comment]
Will get on it 😄

**Comment by jba** [comment]
Good catch!

**Comment by uhthomas** [comment]
Not sure why the GopherBot didn't pick it up, but the changes can be found [here](https://go-review.googlesource.com/c/pkgsite/+/238041).

**Comment by julieqiu** [comment]
Fixed by https://go-review.googlesource.com/c/pkgsite/+/238041.
