### ISSUE TITLE
Ternary Operator Needed

### ISSUE THREAD

**Issue by hashweather** [golang/go#39612]
I strongly think that a ternary operator is needed on Go

Here is why

I have a struct

```
type VerificationStatus struct {
	StatusCode    int
	StatusMessage string
	StatusData    interface{}
}

```

I wish to send that struct based on a json marshal like below
```

data, err := json.Marshal(struct {
					requestId string
				}{
					requestId: string(responseData),
				})
```

Now to send it back this is the long code I have to write
```

            if err != nil {
					return VerificationStatus{
						StatusCode:    http.StatusConflict,
						StatusMessage: "Verification Failed",
					}
				} else {
					return VerificationStatus{
						StatusCode:    http.StatusOK,
						StatusMessage: "Verification Started",
						StatusData:    data,
					}
				}
```

If we had a ternary operator I could have just done this
```

return VerificationStatus{
						StatusCode:    http.StatusOK,
						StatusMessage: "Verification Started",
						StatusData:    err==nil ? data : err.Error(),
					}
```

Thanks for this amazing language though.

**Comment by mvdan** [comment]
This has been discussed before: https://github.com/golang/go/issues/33171

If you think you have something new to add, please file a new proposal while filling the form at https://github.com/golang/proposal/blob/master/go2-language-changes.md.

**Comment by martisch** [comment]
> Now to send it back this is the long code I have to write

Currently without the trenary operator there is a more compact way to write this then the long version:
```
if err != nil {
  data = err.Error()
}
return VerificationStatus{
    StatusCode:       http.StatusOK,
    StatusMessage:    "Verification Started",
    StatusData:       data,
}
```
