### ISSUE TITLE
CGo-enabled cross compilation (amd64 -> arm64) failed

### ISSUE THREAD

**Issue by vps-eric** [golang/go#39615]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/eric/.cache/go-build"
GOENV="/home/eric/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/eric/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/eric/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build999407722=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
<pre>
$ cat main.go
package main

import "C"

func main() {
        fmt.Println("Hello world")
}
$ # Compile for NanoPi R2S, an arm64 system running Alpine Linux
$ env GOOS=linux GOARCH=arm64 CGO_ENABLED=1 CC=arm-linux-gnueabihf-gcc go build -o tester.arm
</pre>

### What did you expect to see?
Successful build

### What did you see instead?
<pre>
# runtime/cgo
In file included from _cgo_export.c:4:
cgo-gcc-export-header-prolog:25:14: error: size of array ‘_check_for_64_bit_pointer_matching_GoInt’ is negative
</pre>

**Comment by cherrymui** [comment]
> CC=arm-linux-gnueabihf-gcc

This looks like an ARM32 compiler. ARM64 GCC is usually named aarch64-* (e.g. aarch64-linux-gnu-gcc). Could you double check?

**Comment by vps-eric** [comment]
@cherrymui Changing the cross compiler resolved the error (but the binary still doesn't run properly on the R2S). Thank you for your help.
