### ISSUE TITLE
Can't seem to import modules from other directory trees

### ISSUE THREAD

**Issue by cleblanc189** [golang/go#39618]
I've been going through hell coverting out project to use modules.  I now realize the module name can't end in `v1`  but I still can't seem to solve all the problems.  I created a simple minimal example to show the error.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Not sure

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\chris_Leblanc\AppData\Local\go-build
set GOENV=C:\Users\chris_Leblanc\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\chris_Leblanc\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=c:/cygwin/bin/x86_64-w64-mingw32-gcc.exe
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\eng\PeterFreshman\test.go\src\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\CHRIS_~1\AppData\Local\Temp\go-build311953050=/tmp/go-build -gn
o-record-gcc-switches
</pre></details>

### What did you do?
I've created two servers that require the use of two services, but I can't seem to properly include the service module from my server module.

https://github.com/cleblanc189/test.go
cd src && go mod tidy

### What did you see instead?

go: test.go/src/server/v1beta1@v0.0.0 requires
        test.go/src/service/v1beta1@v0.0.0: unrecognized import path "test.go/src/service/v1beta1" (https fetch: Get https://test.go/src/ser
vice/v1beta1?go-get=1: dial tcp: lookup test.go: no such host)

**Comment by bcmills** [comment]
You have added a `replace` directive for <code>test.go/src/<b>server</b>/v1beta1</code>. The error occurs when resolving an import of <code>test.go/src/<b>service</b>/v1beta1</code>.

(However, note that for the vast majority of uses, we recommend a single module at the repo root rather than nested modules for subdirectories. This would be a lot simpler with a single module for `test.go/src` as a whole.)

**Comment by bcmills** [comment]
(Note that, by design, only `replace` directives from the main module's `go.mod` file are applied.)

**Comment by cleblanc189** [comment]
Thanks Brian.  Not sure how I got the idea that I needed modules everywhere.  It was my mistake.  I eventually found the error was caused by some files generated from protobufs which didn't have the correct include path.  A more verbose output would have helped me a lot (I come from the land of C compilers)
