### ISSUE TITLE
cmd/go2go: confusing error message when embedding interface with type list

### ISSUE THREAD

**Issue by jimmyfrasche** [golang/go#39626]
https://go2goplay.golang.org/p/UjyJ-OVe8Vk

```go
type Embed interface { type int }
type x interface { Embed }
```
results in `undefined: Embed` instead of allowing the interface to be embedded

Discovered trying to see what the error message was for https://go2goplay.golang.org/p/j1suJ2sWWT1

**Comment by ianlancetaylor** [comment]
Thanks.  This should be fixed now.
