### ISSUE TITLE
cmd/go2go: inferring an unimported type results in confusing error

### ISSUE THREAD

**Issue by benjaminjkraft** [golang/go#39625]
Consider the following code ([playground](https://go2goplay.golang.org/p/pNxkGqHpBbc)):

```go
package main

import (
	"io/ioutil"
)

func F(type T, U)(func(T) (U, error)) {}

func main() {
	F(ioutil.ReadAll) // F(io.Reader, []byte)(ioutil.ReadAll)
}
```

Note that in the call to `F`, the type parameter `T` ends up being inferred as `io.Reader`, which is not explicitly imported (although of course it is transitively).  This results in the following confusing errors:
```
./prog.go2:9: cannot use ioutil.ReadAll (type func(io.Reader) ([]byte, error)) as type func(<T>) ([]byte, error) in argument to instantiate୦୦F୦io୮aReader୦୮6୮7byte
./prog.go2:7: undefined: io in io.Reader
```

Adding a blank import `_ "io"` works around the problem; presumably this shouldn't be necessary.

**Comment by ianlancetaylor** [comment]
Interesting.  This is a bug in the translation tool.  Thanks for reporting it.

**Comment by ianlancetaylor** [comment]
Thanks.  This is now fixed in the dev.go2go branch.
