### ISSUE TITLE
x/pkgsite: replace all internal Googler links

### ISSUE THREAD

**Issue by mvdan** [golang/go#39621]
I see links like `TODO(b/139530312)`, which I assume is an issue link I can't access or at least some text that doesn't make any sense to me.

If we're going to use this issue tracker alone in the future, like other x repos, we should replace all of those with links to issues here. Some TODOs are this way already, such as `TODO(golang/go#38513)`.

Current counts:

```
$ git log -1 --oneline
7f80893 (HEAD -> master, origin/master, origin/HEAD) internal/database: fix bug with error handling in transact
$ git grep 'TODO(b/' | wc -l
26
$ git grep 'TODO(.*#' | wc -l
8
```

/cc @julieqiu @jba

**Comment by julieqiu** [comment]
Thanks for catching! We'll work on fixing these.

**Comment by dmitshur** [comment]
There are a few more instances that can be found without the "TODO" prefix:

```
$ git log -1 --oneline --no-decorate
08e8e66 internal/worker: add /poll and /enqueue endpoints.
$ git grep -E 'b/[0-9]{4}' | wc -l
      12
```

**Comment by dmitshur** [comment]
Only 7 more to go after [CL 240187](https://golang.org/cl/240187).
