### ISSUE TITLE
x/pkgsite: fix links that should be versioned

### ISSUE THREAD

**Issue by julieqiu** [golang/go#39630]
We should version the following links on the details pages with the semantic version at the time of request:

- [ ] module
- [x] breadcrumbs
- [x] packages on Subdirectories tab
- [x] package source link

Related: #39621

**Comment by gmelodie** [comment]
I could try my hand at this if no one else has already started :)

**Comment by julieqiu** [comment]
Please do! :)

**Comment by Hallicopter** [comment]
Hi @julieqiu, could you elaborate on the issue a bit? I would like to help since the issue has become inactive for a while now.

**Comment by julieqiu** [comment]
@Hallicopter this issue looks to be out of date - closing this issue. Thanks for looking into it!
