### ISSUE TITLE
Could golang net package automatically add `Expect: 100-continue` header if body size > 1024

### ISSUE THREAD

**Issue by xqzhang2015** [golang/go#39637]
### What version of Go are you using (`go version`)?

```sh
go version go1.13.3 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```sh
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
```

### What did you expect to see?

* C++ libcurl library could automatically add `Expect: 100-continue` header if body size > 1024. Do golang net package support it?

```cpp
/* EXPECT_100_THRESHOLD is the request body size limit for when libcurl will
 * automatically add an "Expect: 100-continue" header in HTTP requests. When
 * the size is unknown, it will always add it.
 *
 */
#ifndef EXPECT_100_THRESHOLD
#define EXPECT_100_THRESHOLD 1024
#endif
```

**Comment by davecheney** [comment]
Adding the header is one thing, the client _and_ the server has to also have expect support.

Expect support was added back in the day when modems were so slow you didn't want to try to send a large request only to find the server hung up 80% of the way through because the request was larger than it permitted.

What is the problem you are trying to solve?

**Comment by xqzhang2015** [comment]
@davecheney thanks for the reply.

Not for a specific problem. The main idea is to follow up RFC protocol and conform to most HTTP client libraries, which could help to avoid potential issues for development.

**Comment by davecheney** [comment]
Thanks for your reply. I’d like to see some analysis on which clients, and more importantly, servers correctly implement expect 100. From my experience the prevalence of expect usage is very low.

**Comment by bradfitz** [comment]
I think this would probably cause more troubles overall. Also, the Request.Body length can be unknown.

**Comment by xqzhang2015** [comment]
@davecheney agree with the idea that _"the prevalence of expect usage is very low"_

**Comment by davecheney** [comment]
Based on the responses so far I am closing this ticket for now.
