### ISSUE TITLE
x/pkgsite: add second module to testdata for frontend.testServer

### ISSUE THREAD

**Issue by julieqiu** [golang/go#39631]
Add a second module to testdata for frontend.testServer, so that we can verify that we are getting the latest version:

https://github.com/golang/pkgsite/blob/a2ecf39/internal/frontend/server_test.go#L570

Related: #39621

**Comment by AndersonQ** [comment]
I can take it :)

**Comment by julieqiu** [comment]
Thank you!

**Comment by AndersonQ** [comment]
The current "ordinary" module already has got multiple versions. Then I just added a check to ensure the latest version is the one loaded.
I believe it should cover the issue, right?

**Comment by julieqiu** [comment]
Yup, thanks for the fix! :)
