### ISSUE TITLE
x/pkgsite: delete from module from version_map in postgres.DeleteModule

### ISSUE THREAD

**Issue by julieqiu** [golang/go#39633]
See:
https://github.com/golang/pkgsite/blob/df627db60a835a59120b45fe7af59779840aa522/internal/postgres/insert_module_test.go#L312

Related: #39621

**Comment by bharaththiruveedula** [comment]
@julieqiu we have to remove that line, or do we have corresponding issue in this issue tracker? I couldn't see any issue with title "check removal from version_map"

Can I work on this issue?

**Comment by bharaththiruveedula** [comment]
@julieqiu can I work on this? 

I am new to this repo. I am planning to the same approach as in https://github.com/golang/pkgsite/blob/df627db60a835a59120b45fe7af59779840aa522/internal/postgres/insert_module_test.go#L307 but with "version_map" table. Is my approach correct?

**Comment by julieqiu** [comment]
For sure! Thanks @bharaththiruveedula - here's the relevant info for this:

At the moment, when we call [postgres.DeleteModule](https://github.com/golang/pkgsite/blob/df627db60a835a59120b45fe7af59779840aa522/internal/postgres/insert_module.go#L691) we will delete from the following tables:

- modules, which results in cascaded deletes to several other tables
- imports_unique

We also want to delete from the version_map table.

The task here would be to add that to postgres.DeleteModule, and also add a test.

**Comment by bharaththiruveedula** [comment]
Thanks for giving the context. I will work on this @julieqiu

**Comment by julieqiu** [comment]
Fixed by https://go-review.googlesource.com/c/pkgsite/+/238637.
