### ISSUE TITLE
generics advice

### ISSUE THREAD

**Issue by buffge** [golang/go#39644]
## 1. Whether to consider using < >
because () is for func param, when generics layers too long people can't see clearly
l think java and typescript's generics syntax  is very good.
if using <> type also can be removed
```go
package main

import (
	"fmt"
)

func Print<T>(s []T) {
	for _, v := range s {
		fmt.Print(v)
	}
}

func main() {
	Print([]string{"Hello, ", "playground\n"})
}
```
## 2. generics param default type
```go
func Print<T = int>(s []T) {
     // xxx
}
```

**Comment by davecheney** [comment]
Please see this FAQ entry.

https://go.googlesource.com/proposal/+/refs/heads/master/design/go2draft-type-parameters.md#why-not-use-the-syntax-like-c_and-java

**Comment by martisch** [comment]
This is covered in the FAQ of the design draft:
https://go.googlesource.com/proposal/+/refs/heads/master/design/go2draft-type-parameters.md#why-not-use

**Comment by martisch** [comment]
To quote @ianlancetaylor from similar proposals like: #36457

Please also feel free to add a link to this issue to https://github.com/golang/go/wiki/Go2GenericsFeedback. We don't think it will be helpful to keep multiple generics syntax issues open simultaneously, spreading the discussion to too many different places.

There is also dicsussions continuing on at #15292.

Using <...> for type parameters has come up multiple times and has its own problems see e.g.: #15292 (comment) and following.
