### ISSUE TITLE
cmd/link: panic when adding a rsrc section in Windows PE

### ISSUE THREAD

**Issue by tc-hib** [golang/go#39658]
### What version of Go are you using (`go version`)?

<pre>
go version go1.15beta1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

not 1.14.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
</pre></details>

### What did you do?

I tried to build a Windows exe file with a syso file containing a rsrc section.

### What did you expect to see?

An exe file produced without error.

### What did you see instead?

```
panic: runtime error: slice bounds out of range [72:0]

goroutine 1 [running]:
cmd/link/internal/ld.addpersrc(0xc000091500)
        c:/go/src/cmd/link/internal/ld/pe.go:1490 +0x33d
cmd/link/internal/ld.Asmbpe(0xc000091500)
        c:/go/src/cmd/link/internal/ld/pe.go:1568 +0x253
cmd/link/internal/amd64.asmb2(0xc000091500)
        c:/go/src/cmd/link/internal/amd64/asm.go:842 +0xfa
cmd/link/internal/ld.Main(0x121f860, 0x20, 0x20, 0x1, 0x7, 0x10, 0x0, 0x0, 0x107f875, 0x1b, ...)
        c:/go/src/cmd/link/internal/ld/main.go:349 +0x1509
main.main()
        c:/go/src/cmd/link/main.go:68 +0x1fc```

**Comment by cherrymui** [comment]
Thanks for the report. Would it be possible to share your syso file, or perhaps any syso file that contains a rsrc section? So I'll try to reproduce it myself for debugging. Thanks.

**Comment by tc-hib** [comment]
Sure, here it is.

[linker_rsrc.zip](https://github.com/golang/go/files/4796501/linker_rsrc.zip)

**Comment by cherrymui** [comment]
@tc-hib thanks very much for the file. CL https://golang.org/cl/238779 fixes the linker crash. Could you try that and check if the content of the rsrc is generated correctly? Thanks.

**Comment by tc-hib** [comment]
It works, thank you very much.
My application has an icon and version information. It is readable by resource extractors and compresses correctly with UPX.
So I'd say the rsrc section is perfectly integrated.

I've read the comments in the CL.
Here are two syso files without any copyright notice.
One is very small, the other one has a manifest.
[rsrc_syso.zip](https://github.com/golang/go/files/4803102/rsrc_syso.zip)

You can create a syso file with windres or [rsrc](https://github.com/akavel/rsrc) indeed.
I didn't try windres, but akavel/rsrc seems to produce not so good rsrc sections, most probably because of a lack of alignment of resource data.
There's also [goversioninfo](https://github.com/josephspurrier/goversioninfo) which is based on akavel/rsrc.

**Comment by cherrymui** [comment]
@tc-hib thanks for confirming! I managed to create a rsrc syso using windres on the builder machine. Thanks for the information.
