### ISSUE TITLE
s390x evaluation weirdness with 1.13, 1.14. Works with 1.10, 1.12

### ISSUE THREAD

**Issue by panlinux** [golang/go#39651]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 linux/s390x
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?
Ubuntu Groovy on s390x
<details><summary><code>go env</code>
</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="s390x"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOENV="/home/ubuntu/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="s390x"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_s390x"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -march=z196 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build209301451=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Run example.go **on s390x** (works elsewhere): https://play.golang.org/p/CGraP0pNaJi

### What did you expect to see?
No errors in the output, i.e.:
```
--- t:
{Easy! {1 [3 4]}}

--- t dump:
a: Easy!
b:
  c: 1
  d: [3, 4]


--- m:
map[a:Easy! b:map[c:1 d:[3 4]]]

--- m dump:
a: Easy!
b:
  c: 1
  d:
  - 3
  - 4
```
This code comes from the gopkg.in/yaml.v2 example in their [README.md](https://github.com/go-yaml/yaml/blob/v2/README.md) except I replaced "c: 1" with "c: 1.0" in the `data` variable.

### What did you see instead?
```
ubuntu@groovy-s390x:~$ ./example 
2020/06/17 13:14:58 error: yaml: unmarshal errors:
  line 4: cannot unmarshal !!float `1.0` into int
```

Initially I thought it was a bug in `gopkg.in/yaml.v2`, and filed an [issue](https://github.com/go-yaml/yaml/issues/629) there, but I suspect something in go itself now, because either of these silly changes make the code work:

1. Just printf in https://github.com/go-yaml/yaml/blob/v2/decode.go#L502, for debugging purposes, made it work:
```diff
--- a/decode.go
+++ b/decode.go
@@ -500,6 +500,7 @@ func (d *decoder) scalar(n *node, out reflect.Value) bool {
                                return true
                        }
                case float64:
+                       fmt.Printf("DEBUG: int64(resolved) = %d\n", int64(resolved))
                        if resolved <= math.MaxInt64 && !out.OverflowInt(int64(resolved)) {
                                out.SetInt(int64(resolved))
                                return true
```
Output:
```
ubuntu@groovy-s390x:~$ ./example 
DEBUG: int64(resolved) = 1
--- t:
{Easy! {1 [3 4]}}

--- t dump:
a: Easy!
b:
  c: 1
  d: [3, 4]


--- m:
map[a:Easy! b:map[c:1 d:[3 4]]]

--- m dump:
a: Easy!
b:
  c: 1
  d:
  - 3
  - 4
```
2. Or this change:
```diff
--- a/decode.go
+++ b/decode.go
@@ -500,7 +500,8 @@ func (d *decoder) scalar(n *node, out reflect.Value) bool {
                                return true
                        }
                case float64:
-                       if resolved <= math.MaxInt64 && !out.OverflowInt(int64(resolved)) {
+                       is_overflow := out.OverflowInt(int64(resolved))
+                       if resolved <= math.MaxInt64 && !is_overflow {
                                out.SetInt(int64(resolved))
                                return true
                        }
```
Also makes it work and produces the correct output:
```
ubuntu@groovy-s390x:~$ rm example
ubuntu@groovy-s390x:~$ go build example.go
ubuntu@groovy-s390x:~$ ./example 
--- t:
{Easy! {1 [3 4]}}

--- t dump:
a: Easy!
b:
  c: 1
  d: [3, 4]


--- m:
map[a:Easy! b:map[c:1 d:[3 4]]]

--- m dump:
a: Easy!
b:
  c: 1
  d:
  - 3
  - 4
```

**Comment by panlinux** [comment]
The Ubuntu golang-1.14 package carries these patches: https://git.launchpad.net/ubuntu/+source/golang-1.14/tree/debian/patches:

- [0001-Disable-test-for-UserHomeDir.patch](https://git.launchpad.net/ubuntu/+source/golang-1.14/tree/debian/patches/0001-Disable-test-for-UserHomeDir.patch)
- [0002-Fix-Lintian-warnings-about-wrong-interpreter-path.patch](https://git.launchpad.net/ubuntu/+source/golang-1.14/tree/debian/patches/0002-Fix-Lintian-warnings-about-wrong-interpreter-path.patch)
- [0003-Fix-FTBFS-on-HOME-managed-with-git.patch](https://git.launchpad.net/ubuntu/+source/golang-1.14/tree/debian/patches/0003-Fix-FTBFS-on-HOME-managed-with-git.patch)
- [0001-cmd-link-add-support-for-external-linking-on-linux-r.patch](https://git.launchpad.net/ubuntu/+source/golang-1.14/tree/debian/patches/0001-cmd-link-add-support-for-external-linking-on-linux-r.patch)
- [0002-cmd-link-cmd-internal-obj-riscv-add-TLS-support-for-.patch](https://git.launchpad.net/ubuntu/+source/golang-1.14/tree/debian/patches/0002-cmd-link-cmd-internal-obj-riscv-add-TLS-support-for-.patch)
- [0003-cmd-compile-cmd-internal-obj-riscv-move-g-register-o.patch](https://git.launchpad.net/ubuntu/+source/golang-1.14/tree/debian/patches/0003-cmd-compile-cmd-internal-obj-riscv-move-g-register-o.patch)
- [0004-cmd-dist-cmd-go-runtime-add-support-for-cgo-on-linux.patch](https://git.launchpad.net/ubuntu/+source/golang-1.14/tree/debian/patches/0004-cmd-dist-cmd-go-runtime-add-support-for-cgo-on-linux.patch)
- [0001-cmd-go-accept-smart-quotes-when-checking-for-missing.patch](https://git.launchpad.net/ubuntu/+source/golang-1.14/tree/debian/patches/0001-cmd-go-accept-smart-quotes-when-checking-for-missing.patch)
- [80b61c03926762061f4ad247883d50829c58404a.patch](https://git.launchpad.net/ubuntu/+source/golang-1.14/tree/debian/patches/80b61c03926762061f4ad247883d50829c58404a.patch)

**Comment by panlinux** [comment]
I downloaded https://dl.google.com/go/go1.14.4.linux-s390x.tar.gz and with that binary the example.go code also fails in the same way on s390x.

**Comment by mundaym** [comment]
Thanks for the bug report @panlinux. I've seen a bug in the compiler show up in yaml.v3 before as #38195. That bug should be fixed in go 1.14.4 though, so its probably something different. I'll take a look.

**Comment by mundaym** [comment]
Smaller reproducer:

```go
// Test that float -> integer conversion doesn't clobber
// flags.

package main

//go:noinline
func f(x, y float64, a, b *bool, r *int64) {
        *a = x < y    // set flags
        *r = int64(x) // clobber flags
        *b = x == y   // use flags
}

func main() {
        var a, b bool
        var r int64
        f(1, 1, &a, &b, &r)
        if a || !b {
                panic("comparison incorrect")
        }
}
```

The floating point <-> integer conversion instructions set the condition code but the compiler wasn't aware of that behavior causing an incorrect condition code to be seen by a load-on-condition instruction. [CL 238628](https://golang.org/cl/238628) fixes the issue. Sorry about that.

**Comment by mundaym** [comment]
I'll take a look at backporting the fix once the CL has been approved.

**Comment by panlinux** [comment]
Thanks a lot @mundaym !

**Comment by mundaym** [comment]
@gopherbot please consider this for a backport

This is a bug that affects the control flow of a program running on s390x and therefore can result in it behaving incorrectly. The fix is simple and safe and only affects s390x.
