### ISSUE TITLE
reflect.DeepEqual varient that returns an error describing the inequality

### ISSUE THREAD

**Issue by sjpotter** [golang/go#39652]
currently, DeepEqual is just a bool that returns true/false if things are equal or not.  However, as has been seen in the past via Qs (ex "while is an empty map and a nil map not equal according to DeepEquall") as well as that it can be difficult to understand deeply nested structures for why they are not equal.  It be useful (at least during development) to have a varient that returned the reason for DeepEqual returning false.

The primary reason I can see for not wanting to do it is that since it be more expensive, you would probably want to do it as a separate implementation from DeepEqual which would involve code duplication and if one doesn't view it gaining them a lot.

**Comment by andybons** [comment]
I believe a package like https://github.com/google/go-cmp is better suited for this use case.

Closing for now, but feel free to comment if you’d like to re-open.
