### ISSUE TITLE
cmd/go2go: instantiating struct w/ generic embedded member fails

### ISSUE THREAD

**Issue by shanemhansen** [golang/go#39671]
### What version of Go are you using (`go version`)?

Go2go playground: https://go2goplay.golang.org/p/xwo0nvioxDT

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Used the lock type mentioned in the generics draft. 

https://go.googlesource.com/proposal/+/refs/heads/master/design/go2draft-type-parameters.md

https://go2goplay.golang.org/p/xwo0nvioxDT

It appears that when you use generic struct embedding AND attempt to instantiate the generic struct you get an error: "undefined: T"

### What did you expect to see?

I expected the program to compile.

### What did you see instead?

```
# play
./prog.go2:16: undefined: T
```

**Comment by shanemhansen** [comment]
Notice that the types/methods will compile, the error only occurs when they are used. The following code from the draft spec compiles: https://go2goplay.golang.org/p/xPQmnRMC2kV

**Comment by shanemhansen** [comment]
Downloaded go2go and examined the generated source. It appears that embedded generic types are left alone during instantiation, but post instantiation the generic "T" type is no longer defined. Generated incorrect code:

```go
//line main.go2:7
type instantiate୦୦Lockable୦string struct {
//line main.go2:11
 T
        mu sync.Mutex
}
```

Correct code (I think) with T replaced with the instantiated type:

```go
//line main.go2:7
type instantiate୦୦Lockable୦string struct {
//line main.go2:11
 T string
        mu sync.Mutex
}
```

**Comment by ianlancetaylor** [comment]
Thanks, this should be fixed now.
