### ISSUE TITLE
MIPS32: add .gnu.attributes and .MIPS.abiflags sections to the output object

### ISSUE THREAD

**Issue by wzssyqa** [golang/go#39677]
MIPS32 uses .gnu.attributes and .MIPS.abiflags to mark the ABI that
    the object is using, and the kernel will set the correct FP mode for it.
    
    Currrently we have no these 2 sections and thus since kernel will
    treat the objects as FP32. To support FPXX and FP64 in future,
    we should add support of these 2 sections.
    
    More details about FP32/FPXX/FP64 are explained in:
        https://web.archive.org/web/20180828210612/https://dmz-portal.mips.com/wiki/MIPS_O32_ABI_-_FR0_and_FR1_Interlinking

**Comment by wzssyqa** [comment]
this bug blocks #39289

**Comment by wzssyqa** [comment]
I figure out a WIP patch: 
   https://github.com/wzssyqa/go/tree/add-section
RFC, and more test is needed.
Once we have more test, I will submit a CL.

**Comment by mengzhuo** [comment]
PING
