### ISSUE TITLE
cmd/go2go: recursive constraints doesn't work correctly

### ISSUE THREAD

**Issue by tdakkota** [golang/go#39680]
### What version of Go are you using (`go version`)?
n/a

### Does this issue reproduce with the latest release?
n/a

### What operating system and processor architecture are you using (`go env`)?
n/a

### What did you do?
https://go2goplay.golang.org/p/jWH4GUTN-pX

### What did you expect to see?
<pre>
type checking failed for main
prog.go2:54:2: Ident does not satisfy Expr (struct{} not found in Expr, Stmt)
prog.go2:55:2: Ident does not satisfy Node (struct{} not found in Expr, Stmt)
</pre>

or just
<pre>
type checking failed for main
prog.go2:55:2: Ident does not satisfy Node (struct{} not found in Expr, Stmt)
</pre>

### What did you see instead?
<pre>
type checking failed for main
prog.go2:54:2: Ident does not satisfy Expr (struct{} not found in ⊥)
prog.go2:55:2: Ident does not satisfy Node (struct{} not found in Expr, Stmt)
</pre>

**Comment by tdakkota** [comment]
Another example

**Comment by beoran** [comment]
In the latter example there is the constraint
```go
type constr(type T) interface {
	type T
}
```
I think that such a constraint is meaningless since, if I understand correctly, it simply reduces to the type T itstelf. E.g. such a `constr(int)` simply would be `int`. What is the practical use of such a recursive constraint? If there isn't any it should probably be not be allowed.

**Comment by tdakkota** [comment]
First example is example of practical use. It's `ast.Node`, but for Go2.
I just tried use type constraint to make a tagged union.

**Comment by andybons** [comment]
@ianlancetaylor @griesemer

**Comment by tdakkota** [comment]
Change
https://github.com/golang/go/blob/5e754162cd1bbff48258d9bd9c784fd6ea3d98e6/src/go/types/type.go#L829-L837
to 
```go
func optype(typ Type) Type {
	if t := typ.TypeParam(); t != nil {
		u := t.Bound().allTypes
		if u != nil && typ != u { // prevent infinite recursion
			return u
		}
		return theTop
	}
	return typ
}
```
resolves the problem

**Comment by griesemer** [comment]
Your first example is simply incorrect code: Given an interface `E` embedded in an interface `I` as in:
```Go
type I interface { E; type ... }
```
the resulting type list of `I` is the intersection of the type lists declared in `I` and `E`. This is so we preserve the general property that if `I` embeds `E` then `I` implements `E`. This is also documented in the design draft.

This code works: https://go2goplay.golang.org/p/5ddBkbO2ZJb

**Comment by bcmills** [comment]
@beoran 
> I think that such a constraint is meaningless since, if I understand correctly, it simply reduces to the type `T` itstelf. 

As currently implemented, if `T` is an interface, then type `T` itself matches all subtypes of `T` (that is, all interface and concrete types that implement `T`), whereas `interface { type T }` matches only (literal and defined) types whose underlying type is _exactly_ the same interface type (with no additional methods).

**Comment by griesemer** [comment]
@tdakkota Thanks for your 2nd example and the suggested fix. It is exactly right.

This is now fixed in dev.go2go.
