### ISSUE TITLE
access: trybot access

### ISSUE THREAD

**Issue by leitzler** [golang/go#39694]
Gerrit email: leitzler@gmail.com
Trybot access ("may-start-trybots")
https://go-review.googlesource.com/#/admin/groups/1030,members

**Comment by ianlancetaylor** [comment]
CC @andybons @dmitshur

**Comment by dmitshur** [comment]
Hi Pontus,

Thank you for your contributions, and for requesting trybot access! I've added you to the `may-start-trybots` group, so you should be able to do so now.

As you've probably seen at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to skim CLs before starting a trybot run.

Let us know if you have any questions or issues with it, and thanks again!

**Comment by leitzler** [comment]
Yes, have seen it. Thank you!
