### ISSUE TITLE
x/pkgsite: add redirect link to Sourcegraph for method caller / uses of a particular type

### ISSUE THREAD

**Issue by joshuabezaleel** [golang/go#39703]
### What is the URL of the page with the issue?
Every package detail page. I first noticed it when accessed https://godoc.org/golang.org/x/tools/go/ssa#FieldAddr
 
 
### What is your user agent?
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
 
 
 
### Screenshot
![image](https://user-images.githubusercontent.com/7043511/85099844-ba2a6d00-b228-11ea-8b2e-5de15750bdd7.png)

 
 
 
### What did you do?
 Hover to the right of the type/function.

 
 
 
### What did you expect to see?
 See a "Uses" link that list the method callers for a function and the one who use the type for a type which will then redirects to Sourcegraph for that particular function/type. For example, function `Common()` will redirect to this [link](https://sourcegraph.com/github.com/golang/tools/-/blob/go/ssa/ssa.go#L1392:16$references).
 
![image](https://user-images.githubusercontent.com/7043511/85099789-90714600-b228-11ea-822a-61b05ef2aa0d.png)

 
![image](https://user-images.githubusercontent.com/7043511/85099962-1097ab80-b229-11ea-9420-4a2e8b5e1075.png)

### What did you see instead?
I saw both the pilcrow (¶) for the type/function link and the Uses redirect link at the old godoc.org, but only saw pilcrow for every package at the new pkg.go.dev.

**Comment by joshuabezaleel** [comment]
I am not that experience to Go and pretty new to the codebase but if no one is interested I think I can give this issue a shot :slightly_smiling_face:

**Comment by julieqiu** [comment]
@joshuabezaleel - feel free to send a CL!

**Comment by seankhliao** [comment]
I believe sour
