### ISSUE TITLE
cmd/dist: No way to run verbose / for tests

### ISSUE THREAD

**Issue by stevenh** [golang/go#39714]
### What version of Go are you using (`go version`)?

<pre>
go version go1.14.4 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/data/go/bin"
GOCACHE="/home/steveh/.cache/go-build"
GOENV="/home/steveh/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/data/go:/home/steveh/code"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/steveh/code/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build968762670=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Tried to run tests pkg with verbose and force e.g.
`./run.bash -run=net/http -v -count=1`

### What did you expect to see?
The `net/http` always run with verbose enabled.

### What did you see instead?
The following error when run with `-count=1`
`flag provided but not defined: -count`
No verbose details from the tests from `-v`

**Comment by bcmills** [comment]
Um... Why use `run.bash` in that case instead of `go test` directly?

**Comment by stevenh** [comment]
Because they fail due to the use of an internal package:
```
net/http> go test
transfer.go:15:2: use of internal package net/http/internal not allowed
```

**Comment by bcmills** [comment]
Are you using a `go` binary built from a different `GOROOT`? (What does `go list .` report for the package path?)

**Comment by ianlancetaylor** [comment]
@stevenh That shouldn't happen.  Check that the `go` tool that is on your `PATH` has a `GOROOT` that matches the directory that you are testing.

For me:

```
> cd `go env GOROOT`/src/net/http
> go test -test.short
PASS
ok  	net/http	4.098s
```

**Comment by stevenh** [comment]
Yes of course, totally obvious now you mentioned it.

Either resetting `GOROOT` or just relative pathing to it to run the correct `go` fixes the issue.
