### ISSUE TITLE
proposal: syntax for raw string literal that allow to preserve indentation level

### ISSUE THREAD

**Issue by edcded** [golang/go#39718]
an approach like zig - https://ziglang.org/documentation/master/#Multiline-String-Literals

**Comment by edcded** [comment]
there is a warning message in wiregurd-go 
 https://git.zx2c4.com/wireguard-go/tree/main.go

which has 10 call to `fmt.Fprintln`, but it can be done a single call to `fmt.Fprint` using raw string literal. But in order to keep to keep the code nicer i need to put ` on the msg declaration line and on the next lines have the message. Doing that add a newline at the first character. which i can remove via slice expression.

But still the code look ugly, all on a sudden it breaks indentation level.

**Comment by DeedleFake** [comment]
While I don't necessarily agree with this particular syntax, I do think that nicer raw strings are something that need to get added at some point. Remember, code is read more than it's written, and the current raw strings can cause some extremely ugly code sometimes.

**Comment by mvdan** [comment]
Please note that you should fill https://github.com/golang/proposal/blob/master/go2-language-changes.md when proposing a language change.

**Comment by edcded** [comment]
@mvdan i have sent you an email

**Comment by ianlancetaylor** [comment]
Please see #32590.  This is probably a dup of that issue.

**Comment by ianlancetaylor** [comment]
@edcded 

For language change proposals, please fill out the template at https://go.googlesource.com/proposal/+/refs/heads/master/go2-language-changes.md .

When you are done, please reply to the issue with `@gopherbot` `please` `remove` `label` `WaitingForInfo`.

Please fill out the template as a comment in this issue, rather than as an e-mail.

Thanks!

**Comment by mvdan** [comment]
Please don't send me private emails. It's fine if you can't reply here right now, you can do it later. Any text you write to me in private isn't useful.

**Comment by edcded** [comment]
> Please see #32590. This is probably a dup of that issue.

I don't think so. I property to have a way to preserve indentation level.

like how zig does it.

**Comment by edcded** [comment]
you do what you want. I am not interested anymore.

**Comment by edcded** [comment]
sorry, I am still interested. I was frustrated.

**Comment by edcded** [comment]
@ddevault can you do something?

**Comment by edcded** [comment]
😭😫
