### ISSUE TITLE
cmd/go2go: poor diagnostics for type-lists of interface types used as type constraints

### ISSUE THREAD

**Issue by bcmills** [golang/go#39711]
I was experimenting a bit with type-lists as type constraints, since a type-list containing only interface types is conceptually itself an interface.

The program in https://go2goplay.golang.org/p/oobylbuDcfp does not produce an error today. Should it?

The program in https://go2goplay.golang.org/p/Y2yzWbOOS9t produces a misleading `T is not an interface` error (even though `T` is _necessarily_ an interface).

The program in https://go2goplay.golang.org/p/82ff4-1eW5- produces a spurious `duplicate type … in type list` error.

(CC @ianlancetaylor @griesemer)

**Comment by griesemer** [comment]
```Go
package main

import (
	"fmt"
)

type EmptyInterface interface {
	type interface{}
}

func Return(type T EmptyInterface, T2 T)(x T2) T2 {
	return x
}

func main() {
	fmt.Println(Return(interface{}, interface{})(0))
}
```
is valid.

`Return` is instantiated with two empty interfaces as types. First, the type parameters `T` and `T2` are substituted leading to the type parameter signature `(type interface{} EmptyInterface, interface{} interface{})`. Then we check constraints: `interface{}` is a type that's in the type list of `EmptyInterface`, and the 2nd `interface{}` implements its constraint which is `interface{}`. So the instantiation is valid. Now we check the argument passing: `x` is of type `interface{}`, and we can assign a 0 to it. The result is of type `interface{}` and contains the `int` value 0. LGTM!

**Comment by griesemer** [comment]
```Go
package main

import (
	"fmt"
	"syscall"
)

type Stringy interface {
	type fmt.Stringer, error
}

func Return(type T Stringy, T2 T)(x T2) T2 {
	return x
}

func main() {
	fmt.Println(Return(error, syscall.Errno)(syscall.ENOSYS))
}
```
is valid and the error is incorrect.

`Return` is instantiated with `T = error`, and `T2 = syscall.Errno`. Then we check constraints: `error` must satisfy `Stringy` which it does because there's no methods but `error` is in the type list. `syscall.Errno` must satisfy `error` (because `T` was substituted with `error`), which it does because `syscall.Errno` implements `error`.

**Comment by griesemer** [comment]
The last program
```Go
package main

import (
	"fmt"
	"syscall"
)

type Stringy interface {
	type interface{ Error() string }, interface{ String() string }
}

func Return(type T Stringy, T2 T)(x T2) T2 {
	return x
}

func main() {
	fmt.Println(Return(error, syscall.Errno)(syscall.ENOSYS))
}
```
is valid (same reasons as before) and the error message is incorrect (the reason is that the interface are compared before they are "completed" and then they look the same).

**Comment by griesemer** [comment]
In summary, the last two programs shouldn't produce an error, but the first one is correct (and actually runs).

**Comment by griesemer** [comment]
Correction: The first program is correct, the 2nd one (likely) incorrect per the current design (see edited comment above), and the last program is correct and shouldn't report an error.

**Comment by griesemer** [comment]
Fixed error for last program on dev.go2go. Filed separate issue #39723 for 2nd program. Closing.
