### ISSUE TITLE
cmd/go: go get -u fails in a module containing local only replace

### ISSUE THREAD

**Issue by rajveermalviya** [golang/go#39729]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yep

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/var/home/rajveer/.cache/go-build"
GOENV="/var/home/rajveer/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/var/home/rajveer/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org"
GOROOT="/var/home/rajveer/.local/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/var/home/rajveer/.local/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build081973779=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
<details><summary><code>go.mod</code></summary><br><pre>
module mycompany.com/A
go 1.14
require (
	google.golang.org/api v0.26.0
	mycompany.com/B v0.0.0-00010101000000-000000000000
)
replace mycompany.com/B => ../B
</pre></details>
`go get -u -v`
Tried to update all dependencies containing a **local only** replace, i.e the specified module domain doesn't exists. Here mycompany.com domain is just hypothetical.

### What did you expect to see?
Probably ignore the local replaced dep when running `go get -u`  

### What did you see instead?
<pre>
go get: upgrading mycompany.com/B@v0.0.0-00010101000000-000000000000: module mycompany.com/B: reading https://proxy.golang.org/mycompany.com/B/@v/list: 410 Gone
        server response: not found: mycompany.com/B@latest: unrecognized import path "mycompany.com/B": https fetch: Get "https://mycompany.com/B?go-get=1": dial tcp: lookup mycompany.com/B on 8.8.8.8:53: no such host
</pre>

**Comment by bcmills** [comment]
This is likely fixed by [CL 258220](https://golang.org/cl/258220) and [CL 266018](https://golang.org/cl/266018).

@rajveermalviya, could you try a `go` command built from head (either [build from source](https://golang.org/doc/install/source#head) or use [`golang.org/dl/gotip`](https://pkg.go.dev/golang.org/dl/gotip)), and let us know whether this is fixed?

**Comment by rajveermalviya** [comment]
yep can confirm it's fixed, tested with `gotip`

```sh
rajveer@toolbox ~/P/G/t/A [1]> gotip version
go version devel +feccfb8 Mon Nov 9 14:41:38 2020 +0000 linux/amd64

rajveer@toolbox ~/P/G/t/A> gotip get -u -v
go: downloading google.golang.org/api v0.35.0
go: downloading honnef.co/go/tools v0.0.1-2020.1.6
go: downloading golang.org/x/tools v0.0.0-20201105220310-78b158585360
go: downloading golang.org/x/mod v0.3.0
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
google.golang.org/api
mycompany.com/B
```

**Comment by bcmills** [comment]
Great, thanks for confirming!
