### ISSUE TITLE
x/pkgsite: package level Example quotes entire file, not just function code

### ISSUE THREAD

**Issue by mroth** [golang/go#39727]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/mroth/weightedrand@v0.2.2?tab=doc#example-package
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15
 

### Screenshot
 
_Package Example function in godoc.org:_
<img width="730" alt="Screen Shot 2020-06-20 at 10 09 17 AM" src="https://user-images.githubusercontent.com/40650/85203826-477bc900-b2de-11ea-9096-38c2a012e745.png">

_Package Example unction in pkg.go.dev:_
<img width="993" alt="Screen Shot 2020-06-20 at 10 09 52 AM" src="https://user-images.githubusercontent.com/40650/85203830-49de2300-b2de-11ea-8061-0fd77db95fdd.png">
 (snipped...)
 
### What did you do?
 
Use a package level Example function in the godocs for a module.
 
### What did you expect to see?
 
 The example code and output for the Example function only rendered at the top of the package documentation page.
 
### What did you see instead?

The "code" section of the example function contains the source of the *entire file*, not just the Example function.

**Comment by mvdan** [comment]
Possibly related (or even a duplicate) of https://github.com/golang/go/issues/39006.
