### ISSUE TITLE
x/tools/cmd/present: Markdown code blocks are formatted without background color

### ISSUE THREAD

**Issue by autarch** [golang/go#39730]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

This isn't an issue with the go core.

I _did_ install the latest version of `present` with `go get -u golang.org/x/tools/cmd/present`

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/autarch/.cache/go-build"
GOENV="/home/autarch/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="github.com/ActiveState"
GONOSUMDB="github.com/ActiveState"
GOOS="linux"
GOPATH="/home/autarch/go"
GOPRIVATE="github.com/ActiveState"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build349158934=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I converted my slides to Markdown formatting.

### What did you expect to see?

With the legacy syntax, a code block (indented by 4 spaces or a tab) would be formatted with a grey background and a border around the entire block.

### What did you see instead?

With the Markdown syntax, there is no background or border.

**Comment by robpike** [comment]
This is intentional. The presentation design, however it is formatted, is minimalist, and Markdown only specifies fonts, bullets and so on, not tonality.

**Comment by cagedmantis** [comment]
The issue has been responded to. Adding the tools team for visibility:

/cc @golang/tools-team

**Comment by stamblerre** [comment]
Sounds like we can probably close this.
