### ISSUE TITLE
cmd/go2go: calling a generic function with the same type argument(s) in two different files generates duplicate code

### ISSUE THREAD

**Issue by firelizzard18** [golang/go#39749]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +0a030888da Sat Jun 20 04:46:40 2020 +0000 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
</pre></details>

### What did you do?

I ran `go tool go2go build` on https://gitlab.com/firelizzard/go-iter/-/tree/master/issues/i1

### What did you expect to see?

A successful build

### What did you see instead?

```
a.go2:9: instantiate୦୦A୦int redeclared in this block
        previous declaration at a.go2:9
```

Both `b.go` and `c.go` define `func instantiate୦୦A୦int(m [](int), i int) { ... }`

**Comment by DylanMeeus** [comment]
Just ran into this myself, it does indeed break the build.

**Comment by ianlancetaylor** [comment]
Thanks for the test case.  This is now fixed on the dev.go2go branch.

**Comment by DylanMeeus** [comment]
@ianlancetaylor that was fast, thanks!
