### ISSUE TITLE
cmd/go2go: panics with unimplemented Spec *ast.TypeSpec

### ISSUE THREAD

**Issue by zerbitx** [golang/go#39741]
### What did you do?

Tried to run: https://go2goplay.golang.org/p/BFTD2DdjyeP

### What did you expect to see?

 1 :  1,      1
 2 :  1,      2
 3 :  2,      6
 4 :  3,     24
 5 :  5,    120
 6 :  8,    720
 7 : 13,   5040
 8 : 21,  40320
 9 : 34, 362880

### What did you see instead?
panic: unimplemented Spec *ast.TypeSpec

### Other notes

This was a first attempt at porting the non-generic version here: https://gist.github.com/wancw/4301d95cea1169631435

Also tried [this](https://go2goplay.golang.org/p/cBpwO62RaYw) alternative. It doesn't panic, but asked for an operand and I'm not sure why.

**Comment by acln0** [comment]
I got the same panic with this program: https://go2goplay.golang.org/p/YbigQFHT_RZ

**Comment by randall77** [comment]
I got this as well, from this program: https://go2goplay.golang.org/p/Q-Axa9uUaJL

**Comment by ianlancetaylor** [comment]
Thanks for the test case.  This should be fixed now on the dev.go2go branch.
