### ISSUE TITLE
iota logic mismatch

### ISSUE THREAD

**Issue by watson-2018** [golang/go#39751]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.13.10 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="linux"
GOHOSTARCH="amd64"
GOHOSTOS="linux"

</pre></details>

### What did you do?

```
type myConst int

const (
        zero myConst = iota
        one
        three = iota + 1
        foure
        five = iota + 1
)

func testIota() {
        // 3 4 5 why not 3 4 6
        fmt.Println(three, foure, five)
}
```

### What did you expect to see?

why output is 3 4 5  not 3 4 6

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
