### ISSUE TITLE
x/pkgsite: test pathNotFoundErrorNew

### ISSUE THREAD

**Issue by jba** [golang/go#39759]
Add a test that checks `pathNotFoundErrorNew` in internal/frontend/details.go.

**Comment by AndersonQ** [comment]
I can help with this issue :)
However I have a question, the idea is to test the function `pathNotFoundErrorNew` or the ones using `pathNotFoundErrorNew`?

**Comment by julieqiu** [comment]
Thanks, @AndersonQ! This issue is about testing function using `pathNotFoundErrorNew`. It is related to this:
https://github.com/golang/pkgsite/blob/master/internal/frontend/server_test.go#L832

**Comment by AndersonQ** [comment]
Thanks! Looking into it :)
