### ISSUE TITLE
x/tools: use GOMODCACHE where appropriate

### ISSUE THREAD

**Issue by heschik** [golang/go#39761]
Audit x/tools for assumptions that the module cache is in GOPATH[0]/pkg/mod and fix them to use GOMODCACHE when it's available. goimports and gopls are probably both affected.

**Comment by mvdan** [comment]
Good point - I'll bring this up on the tools call tomorrow, as I'm sure some external tools would also be affected. We should fix these before the final 1.15 release is out.

**Comment by stamblerre** [comment]
A quick grep indicates that the packages to fix are, as one would expect, `internal/imports`, `go/packages`, and `internal/lsp`. The issues appear to be mostly in tests.
