### ISSUE TITLE
cmd/go2go: Type aliases of generic types fail to compile

### ISSUE THREAD

**Issue by firelizzard18** [golang/go#39768]
The design draft ([Appendix > Generic type aliases](https://go.googlesource.com/proposal/+/refs/heads/master/design/go2draft-type-parameters.md#generic-type-aliases)) indicates that the following would work:

```go
package pkg

type Vector(type T) []T
type VectorAlias = Vector
var v Vector(int)
```

However, it doesn't: https://go2goplay.golang.org/p/Gnfiupx2_xT

```
type checking failed for main
prog.go2:4:20: cannot use generic type Vector(type T) without instantiation
```

### What version of Go are you using (`go version`)?

`go2goplay.golang.org` and `go version devel +da7932368b Mon Jun 22 19:06:44 2020 +0000 linux/amd64`

**Comment by griesemer** [comment]
At the moment only [this](https://go2goplay.golang.org/p/1i6in1waVOH) works.

This is a current limitation of the prototype.

**Comment by griesemer** [comment]
Turns out this was trivial to fix. Now implemented on dev.go2go. In the playground when it gets updated.

@firelizzard18 Thanks for bringing this to my attention.
