### ISSUE TITLE
cmd/go: how do you automatically delete multiple versions in the mod directory

### ISSUE THREAD

**Issue by Aquarian-Age** [golang/go#39765]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xuan/.cache/go-build"
GOENV="/home/xuan/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"

</pre></details>

### What did you do?

 automatically delete multiple versions in the mod directory
ls google.golang.org/
api@v0.20.0       appengine@v1.6.5                             genproto@v0.0.0-20191028173616-919d9bdd9fe6  grpc@v1.27.1
appengine@v1.0.0  appengine@v1.6.6                             genproto@v0.0.0-20200413115906-b5235f65be36  protobuf@v1.23.0
appengine@v1.1.0  genproto@v0.0.0-20180817151627-c66870c02cf8  grpc@v1.18.0
appengine@v1.4.0  genproto@v0.0.0-20180831171423-11092d34479b  grpc@v1.21.1
appengine@v1.6.1  genproto@v0.0.0-20190626174449-989357319d63  grpc@v1.24.0

### What did you expect to see?
ls google.golang.org/
api@v0.20.0                                       grpc@v1.27.1
appengine@v1.6.6                             protobuf@v1.23.0
genproto@v0.0.0-20190626174449-989357319d63  grpc@v1.24.0

**Comment by icholy** [comment]
If your module cache is getting to big, just delete it with `go clean --modcache`.

**Comment by cagedmantis** [comment]
@Aquarian-Age We don't really use our issue tracker for questions. More people will see your question, and you will get better answers, if you ask on a forum rather than on the issue tracker. See https://golang.org/wiki/Questions.
