### ISSUE TITLE
cmd/go2go: misleading error for embedded struct field of type parameter

### ISSUE THREAD

**Issue by bcmills** [golang/go#39774]
https://go2goplay.golang.org/p/596K-mmE-Jm was an attempt to define a generic test case equivalent to https://play.golang.org/p/f8yMpNN3aDn:

```go
package main

type I interface{}

type S(type T) struct {
	*T
}

func main() {
	_ = S(I){}
}
```

I did not expect https://go2goplay.golang.org/p/596K-mmE-Jm to compile, but the error message that it gives seems wrong:
```
# play
./prog.go2:6: undefined: T
```

compared with
```
./prog.go:6:3: embedded type cannot be a pointer to interface
```
for the non-generic version.

I expected the go2go version to instead produce some sort of error message referring to the fact that `T` could be an interface type.

**Comment by ianlancetaylor** [comment]
Thanks.  Fixed on dev.go2go branch.
