### ISSUE TITLE
go.dev: module proxy protocol link has trailing "<Paste>" string

### ISSUE THREAD

**Issue by ericchiang** [golang/go#39772]
It looks like this isn't actually part of golang.org/x/pkgsite so I can't send a patch :)
 
### What is the URL of the page with the issue?
 
https://go.dev/about
 
### What is your user agent?
 
N/A
 
### Screenshot

Let me know if you need one.
 
### What did you do?
 
```
% curl -s https://go.dev/about | grep 'Module proxy protocol'
<li>Making a request to proxy.golang.org for the module version, to any endpoint specified by the <a href="https://golang.org/cmd/go/#hdr-Module_proxy_protocol%3CPaste%3E" rel="noreferrer" target="_blank">Module proxy protocol</a>. For example:</li>
```
 
 
### What did you expect to see?
 
```
href="https://golang.org/cmd/go/#hdr-Module_proxy_protocol"
```
 
### What did you see instead?

```
href="https://golang.org/cmd/go/#hdr-Module_proxy_protocol%3CPaste%3E"
```

**Comment by julieqiu** [comment]
Thanks for the bug report, @ericchiang! We'll work on a fix.

**Comment by julieqiu** [comment]
This has been fixed.
