### ISSUE TITLE
x/tools/gopls: bad diagnostics for indirect dependency

### ISSUE THREAD

**Issue by stamblerre** [golang/go#39784]
Reported by @hyangah on chat:

> while trying to repro a user's issue report, I encountered this repo and think how the current presentation about missing indirect dependency can be confusing.
>
> In this code https://github.com/kstenerud/go-concise-encoding/blob/master/builder_array.go#L29, gopls says "github.com/cockroachdb/apd is not in your go.mod file."  
>
> It is because "github.com/cockroachdb/apd/v2" depends on "github.com/cockroachdb/apd". And the current "go.mod" has only v2 module.  Actual fix is to add the missing indirect dependency to go.mod. 
>
> But I think it can be somewhat confusing to users who are new to modules. I got 52 error messages (one for each .go file that imports v2), but zero error for the actual go.mod. Why isn't gopls sending this diagnostics msg for the go.mod file, but each individual files that have indirect dependencies?

**Comment by heschik** [comment]
Just remembered that this bug is probably very specific to this situation. The missing dep code uses naive prefix checking to decide which module to complain about, and it probably isn't realizing that `/v2` provides the package despite `go mod tidy` wanting to add v1.
