### ISSUE TITLE
cmd/go2go: translation considers package x_test to be part of package x

### ISSUE THREAD

**Issue by firelizzard18** [golang/go#39801]
Go 1 allows `package a_test` to reference `package b` and `package b` to reference `package a`. go2go considers this to be an import cycle.

`go test` will succeed with the following, but `go tool go2go test` will issue a circular import error (if .go is changed to .go2)

```go
--- a/a.go ---
package a

func F() {}

--- b/b.go
package b

import "./a"

func F() { a.F() }

--- b/b_test.go ---
package b_test

import "testing"
import "./b"

func Test(*testing.T) { b.F() }
```

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +da7932368b Mon Jun 22 19:06:44 2020 +0000 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
</pre></details>

### What did you do?

* `git clone https://gitlab.com/firelizzard/go-iter`
* `cd go-iter/issues/i4`
* `go tool go2go build`

### What did you expect to see?

A successful build

### What did you see instead?

```
type checking failed for i4_test
i4_test.go2:6:2: could not import gitlab.com/firelizzard/go-iter/issues/i4/a (type checking failed for a
/tmp/go2go529617879/src/gitlab.com/firelizzard/go-iter/issues/i4/a/a.go2:3:8: could not import gitlab.com/firelizzard/go-iter/issues/i4 (type checking failed for i4_test
/tmp/go2go529617879/src/gitlab.com/firelizzard/go-iter/issues/i4/i4_test.go2:6:2: could not import gitlab.com/firelizzard/go-iter/issues/i4/a (circular import when processing "gitlab.com/firelizzard/go-iter/issues/i4/a")
)
)
```

**Comment by ianlancetaylor** [comment]
Thanks.  Yes, this is a known deficiency in the translation tool.  I'll leave this issue open but I have no plans to fix this.  If anyone else wants to tackle it, that would be fine.

**Comment by ALTree** [comment]
The go2go branch is [no longer maintained](https://go.googlesource.com/go/+/refs/heads/dev.go2go/README.go2go.md):

> This branch was published in 2020 and is no longer being maintained. The generics proposal has been accepted and development is now focused on implementing the proposal in the ordinary Go tools.

So I think we can close here.
