### ISSUE TITLE
os: File.Sync should return *PathError on Plan 9

### ISSUE THREAD

**Issue by fhs** [golang/go#39800]
`File.Sync` currently returns `*SyscallError` on Plan 9. It should return `*PathError` so that the error type matches other systems.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +master Sat Jun 20 01:48:54 EDT 2020 plan9/amd64
</pre>

### What did you do?

Run:
```go
package main

import (
	"fmt"
	"os"
)

func main() {
	err := os.Stderr.Sync()
	if err != nil {
		fmt.Printf("%T: %v\n", err, err)
	}
}
```

### What did you expect to see?

Filename in the error, for example on Linux:
```
*os.PathError: sync /dev/stderr: invalid argument
```

### What did you see instead?
```
*os.SyscallError: fsync: permission denied
```

@gopherbot add labels OS-Plan9, NeedsFix

**Comment by ianlancetaylor** [comment]
CC @0intro
