### ISSUE TITLE
go2goplay: use a distinctive UI from play.golang.org

### ISSUE THREAD

**Issue by dolmen** [golang/go#39809]
### What version of Go are you using (`go version`)?

https://go2goplay.golang.org/

### Does this issue reproduce with the latest release?

yes

### What did you expect to see?

A clear marker that this is not a stable release of Go and that languages features are experimental.

This is important when a block of go2go code is shared on social media so that readers would not be confused thinking that the language features used are available in the production version currently available. The About page is not enough.

### What did you see instead?

Exactly the same layout as https://play.golang.org/

Only the about page mention a different commit than play.golang.org.

### Fix

Here are some ideas:
- add a big label "experimental" in the title, with a link to https://blog.golang.org/generics-next-step
- add a ribbon "experimental", with a link to https://blog.golang.org/generics-next-step
- replace "The Go Playground" with "The go2go Playground"

**Comment by ianlancetaylor** [comment]
CC @andybons

**Comment by dolmen** [comment]
I'm satisfied with the current state. Thanks @andybons!
