### ISSUE TITLE
crypto/ecdsa: broken link in references

### ISSUE THREAD

**Issue by kcalvinalvin** [golang/go#39808]
The referenced link is no longer accessible.

https://github.com/golang/go/blob/9f33108dfa22946622a8a78b5cd3f64cd3e455dd/src/crypto/ecdsa/ecdsa.go#L20

**Comment by HowJMay** [comment]
How about using [RFC documentation](https://tools.ietf.org/html/rfc3686) instead?

**Comment by mostynb** [comment]
http://kiosk.nada.kth.se/nada/kurser/kth/2D1441/semteo03/lecturenotes/assump.pdf

**Comment by fmeyer** [comment]
@mostynb 

The new link which points to http://kiosk.nada.kth.se/nada/kurser/kth/2D1441/semteo03/lecturenotes/assump.pdf is also dead. 

I'd rather use the WebArchive version. https://web.archive.org/web/20040719170906/https://www.nada.kth.se/kurser/kth/2D1441/semteo03/lecturenotes/assump.pdf
