### ISSUE TITLE
x/tools/gopls: support fillstruct for anonymous structs

### ISSUE THREAD

**Issue by stamblerre** [golang/go#39803]
The fix needs to be made in the analysisinternal package: https://github.com/golang/tools/blob/master/internal/analysisinternal/analysis.go#L110.

/cc @joshbaum

**Comment by dnwe** [comment]
RE: the original placeholder comment "// TODO: anonymous structs, but who does that"

This may already be well known, but the one place where that is key is when you're filling a slice of some struct:
```go
ss := &appsv1.StatefulSet{
	Spec: appsv1.StatefulSetSpec{
		Template: v1.PodTemplateSpec{
			Spec: v1.PodSpec{
				Containers: []v1.Container{
					{}
				},
			},
		},
	},
}
```
Currently you'd have to add the redundant v1.Container in front of the `{}` to allow you to call the fillstruct codeaction, and then remove the redundant v1.Container afterwards
