### ISSUE TITLE
about syntax of generic

### ISSUE THREAD

**Issue by cossbow** [golang/go#39811]
I'm very concerned about the generics of golang. 
I have a small proposal to use angle bracket < > to identify generic parameter types, which has a higher degree of variability than parenthesis (), making it easier to read the code.
`
func PrintSlice(type T)(s []T) {
	for _, v := range s {
		fmt.Printf("%v ", v)
	}
	fmt.Print("\n")
}
`
vs
`
func PrintSlice<type T>(s []T) {
	for _, v := range s {
		fmt.Printf("%v ", v)
	}
	fmt.Print("\n")
}
`

**Comment by mvdan** [comment]
Please read the draft first. This is very explicitly discussed there.

**Comment by cossbow** [comment]
Sorry!
