### ISSUE TITLE
Effective go book: log.Logger must be replaced with job.Logger

### ISSUE THREAD

**Issue by yifu** [golang/go#39810]
I am reading the Effective go book. I thing I found a typo. In the following paragraph:

> Embedding types introduces the problem of name conflicts but the rules to resolve them are simple. First, a field or method X hides any other item X in a more deeply nested part of the type. If log.Logger contained a field or method called Command, the Command field of Job would dominate it.

`log.Logger` must be replaced with `job.Logger`, I guess.

**Comment by ianlancetaylor** [comment]
Thanks, but the text is correct as written.  It's saying that when you embed `log.Logger` in `job.Logger`, the fields of `job.Logger` hide the fields of `log.Logger`.
