### ISSUE TITLE
internal/cfg: GOROOT_FINAL isn't included in KnownEnv, hard to tell if that's a bug or intentional

### ISSUE THREAD

**Issue by dmitshur** [golang/go#39819]
I've noticed the current [`cfg.KnownEnv`](https://pkg.go.dev/internal/cfg#KnownEnv) list does not include the `GOROOT_FINAL` environment variable.

We know from #39385 that `GOROOT_FINAL` has some (albeit indirect) effect on the behavior of the Go command (fortunately, `GOROOT_FINAL_OLD` no longer does).

Should `GOROOT_FINAL` be included in `cfg.KnownEnv`, or is it intentional that it's not listed?

The documentation for `KnownEnv` is somewhat brief:

```
// KnownEnv is a list of environment variables that affect the operation
// of the Go command.
```

It'd be nice to clarify if it's meant to be an exhaustive list or not, and whether some env vars should be intentionally left out or not.

/cc @bcmills @matloob @jayconrod

**Comment by dmitshur** [comment]
> `GOROOT_FINAL` has some (albeit indirect) effect

It might be indirect enough to be considered no effect. Perhaps the scope of these env vars are vars that can be set after a Go tree has been installed, and cmd/go tests are out of scope. I wasn't sure from the documentation, which is in large part what this issue is about.

**Comment by bcmills** [comment]
Hmm, that's an interesting question. The main purpose of `cfg.KnownEnv` is to control which variables may be stored (and read) from the `go/env` configuration file, but today we do not read `GOROOT_FINAL` from that file:
https://github.com/golang/go/blob/daf70d6c1688a1ba1699c933b3c3f04d6f2f73d9/src/cmd/go/internal/cfg/cfg.go#L336-L344

On the other hand, it really does affect the behavior of `cmd/go` for all binaries that depend on `std`, not just during `make.bash`.

**Comment by bcmills** [comment]
Note that there are a few other environment variables that affect compiler behavior that are also not supported in `go/env` or tracked as test inputs:
* `GO_GCFLAGS` (#18222)
* `GOSSAFUNC`, `GOSSAHASH` (#31290; see especially https://github.com/golang/go/issues/31290#issuecomment-482094899)
* possibly`GOCLOBBERDEADHASH`, and `GO_SSA_PHI_LOC_CUTOFF` (but I couldn't find any remaining sites in the code that actually consume these variables, so maybe they're gone now).
* `GSHS_LOGFILE`:
   https://github.com/golang/go/blob/7e71c9c3edbf5b7a8608d6f739c20420a618e0ab/src/cmd/compile/internal/ssa/func.go#L734
   https://github.com/golang/go/blob/567556d78657326c99b8fa84ec2a5ee511a0941b/src/cmd/go/internal/work/exec.go#L286-L292

However, `GOROOT_FINAL` is somewhat different from those in that it is interpreted directly by `cmd/go`.

**Comment by iwdgo** [comment]
GOROOT_FINAL has been removed following https://github.com/golang/go/issues/62047.
Nothing seems left to do to resolve this issue.

**Comment by qiulaidongfeng** [comment]
@dmitshur I noticed this issue while searching on github, now that GOROOT_FINAL has been removed, please close this issue.

**Comment by dmitshur** [comment]
It’s true that GOROOT_FINAL is removed in Go 1.23, so it’s no longer relevant. As https://github.com/golang/go/issues/39819#issuecomment-648880776 points out, there are more env vars that might need consideration. But perhaps that can be deferred until there’s a concrete need. Closing for now.
