### ISSUE TITLE
cmd/pprof: allow auto assigned http port

### ISSUE THREAD

**Issue by howardjohn** [golang/go#39820]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/howardjohn/.cache/go-build"
GOENV="/home/howardjohn/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/howardjohn/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/howardjohn/go/src/istio.io/istio/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build230957294=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Ran `go tool pprof --http=:0 /tmp/profile`

### What did you expect to see?
A browser window opens to localhost:<SOME_RANDOM_PORT>, where the port is autoassigned from a random free port

### What did you see instead?
Browser opens to `localhost:0` which doesn't work

This would be useful so I don't have to worry about manually changing ports when viewing multiple profiles

**Comment by davecheney** [comment]
Use -htttp=:

**Comment by howardjohn** [comment]
Thanks @davecheney ! I verified that works and its actually pretty well documented I just didn't read it well

>   Misc options:
>    -http              Provide web interface at host:port.
>                       Host is optional and 'localhost' by default.
>                       Port is optional and a randomly available port by default

**Comment by hyangah** [comment]
Filed https://github.com/google/pprof/issues/546 upstream.

**Comment by hyangah** [comment]
Oh. ok.
