### ISSUE TITLE
Internal compiler error: 'main': not lowered: v139, Move SSA UNSAFEPTR UNSAFEPTR SSA  Please file a bug report including a short program that triggers the error.

### ISSUE THREAD

**Issue by qeetell** [golang/go#39830]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.14.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Deepin 15 [Linux]; AMD 64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ibrahim/.cache/go-build"
GOENV="/home/ibrahim/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ibrahim/go:/home/ibrahim/Repo"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build473479359=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I tried to install a module containing a file containing the following [go install]:

<pre>
package main

import (
	"fmt"
	pkge "github.com/qeetell-aaaa/aaaaaaab"
)

func main () {
	aome := []byte {1, 2}
	bome := pkge.RemoveLastByte (aome)
	come := pkge.RemoveLastByte (bome)
	dome := pkge.RemoveLastByte (come)
	eome := pkge.RemoveLastByte (dome)
	fome := pkge.RemoveLastByte (eome)
	fmt.Println (aome, bome, come, dome, eome, fome)
}
</pre>

### What did you expect to see?

[1, 2] [1] [] [] [] []

### What did you see instead?

\# github.com/qeetell-aaaa/aaaaaaab/RemoveLastByte_Test
./test.go:10:30: internal compiler error: 'main': not lowered: v139, Move SSA UNSAFEPTR UNSAFEPTR SSA

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new

**Comment by randall77** [comment]
Well, it should run and panic with `makeslice: len out of range` when the size passed to `make` goes negative.

But the compiler shouldn't crash.
This works correctly in 1.11. It starts failing in 1.12. It continues to fail though and including 1.14, then works correctly again at tip.

So there's nothing to do for tip. I'm leaning against backporting a fix for this. It only happens for a program that would otherwise be guaranteed to panic. And it has been broken for a really long while without anyone noticing.

**Comment by qeetell** [comment]
Thanks @randall77

**Comment by randall77** [comment]
Probably a dup of https://github.com/golang/go/issues/36259, which was fixed in February.
