### ISSUE TITLE
[generics] could not find function body in _test packages

### ISSUE THREAD

**Issue by kovetskiy** [golang/go#39839]
```
go version devel +2dc2987ac87 Tue Jun 23 23:41:16 2020 +0000 linux/amd64
```

working directory: `bug2`

`bug2_test.go`
```
package bug2_test

import "testing"

func TestT(t *testing.T) {
	x([]int{1}, 1)
}

func x(type T)(v []T, t T) {

}
```

Error: (the same with go2go test)
```
> go tool go2go build
could not find function body for "x"
```

The bug doesn't appear if:
a) I change package name to bug2, or
b) I move x function to another package (and export it)

**Comment by ianlancetaylor** [comment]
Thanks.  This test case, at least, should now be fixed on the dev.go2go branch.  I wouldn't be very surprised if there are problems in this area.
