### ISSUE TITLE
go.dev: highlight above "Discover Packages" is less helpful than it should be

### ISSUE THREAD

**Issue by kortschak** [golang/go#39847]
This is a UX issue following on from #39767. I don't believe it fits into the form of the x/pkgsite page issue report, so this is freeform-ish.

The upper menu for the page includes a pale blue highlight bar above the "Discover Packages" item. In the current incarnation of the page, this appears as an obstructed widget (hence the confusion in the ref'd issue).

It is unclear what the purpose of the highlight above the item in them menu is for, though presumably to draw attention to it. It doesn't really do this well given its pale colouring and perhaps another approach should be chose. Or alternatively just let people read the text, which could remain bolded as it is currently.

 
### What is the URL of the page with the issue?

https://pkg.go.dev/

### What is your user agent?
 

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0

 
### Screenshot

![Screenshot from 2020-06-23 10-22-48](https://user-images.githubusercontent.com/275221/85348702-88244e00-b53b-11ea-93d8-f7727ccf7d35.png)

**Comment by julieqiu** [comment]
Thanks for the feedback, @kortschak! 

/cc  @Joanne881107 @spf13 @fflewddur for product / UX input

**Comment by spf13** [comment]
I agree with this feedback. It's something to consider as we look to improve the site design. 

FWIW, the primary indication here is the bolded text. The color bar is stylistic first and functional second.
