### ISSUE TITLE
VSCode-Go: improper warning about project root

### ISSUE THREAD

**Issue by xrfang** [golang/go#39845]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xrfang/.cache/go-build"
GOENV="/home/xrfang/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xrfang/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build145582574=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

My Go projects usually have the following directory structure:

/
- Makefile
- bin/   //compiled binaries go here
- conf/    //for possible configurations
- docs/
- resources/  //static resources, e.g. images, html / css / js files
- src/   //go source code, including go.mod and go.sum, may have subdirectories

### What did you expect to see?

I expect vscode-go to analyze code structrue and assist editing smoothly.

### What did you see instead?

It often add warnings about code errors here and there, which are abosolutely correct, (compiles ok), and  consistantly shows warning:

You are neither in a module nor in your GOPATH. If you are using modules, please open your editor at the directory containing the go.mod. If you believe this warning is incorrect, please file an issue: https://github.com/golang/go/issues/new.

I would suggest the vscode-go plugin to add an option like  **go.source.root**, which defaults to the project root, but may be changed, such as **src** in my case, so that the tools can work as expected.

**Comment by stamblerre** [comment]
This is a known issue, and one that we are currently working on addressing in `gopls` (before it reaches v1.0). In the meantime, I recommend using VS Code's "Add Folder to Workspace" feature, which allows you to open your directory at the root, but to also have `gopls` still work on your subdirectory.

**Comment by xrfang** [comment]
Goot to know.   I'd like to propose a better option than adding a configuration, just let gopls to find where is go.mod located, and use that directory and its project root.

**Comment by xrfang** [comment]
I also found that by using your suggestion of adding folder to project workspace, I will have to deal with the .gitignore file, otherwise, vscode will show a LOT of changed files under pkg/ which was already ignored.
