### ISSUE TITLE
cmd\go2go: unexported names can't be used in a library's generic function

### ISSUE THREAD

**Issue by argusdusty** [golang/go#39840]
### What version of Go are you using (`go version`)?

<pre>
C:\Users\argusdusty\Code\src\foo>go version
go version devel +2dce748bd8 Wed Jun 24 22:35:01 2020 +0000 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

reproduces with 2dce748

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
C:\Users\argusdusty\Code\src\foo>go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\argusdusty\AppData\Local\go-build
set GOENV=C:\Users\argusdusty\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\argusdusty\Code\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\argusdusty\Code
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Gosrc
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Gosrc\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ARGUSD~1\AppData\Local\Temp\go-build612910630=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

foo/lib/lib.go2:
```go
package lib

func unexportedFunc() {
	println("Hello, World!")
}

func ExportedFunc(type T)(t T) {
	unexportedFunc()
}
```

foo/foo.go2:
```go
package main

import "foo/lib"

func main() {
	lib.ExportedFunc(0)
}
```
`C:\Users\argusdusty\Code\src\foo>go tool go2go build`

### What did you expect to see?

Successful compilation.

### What did you see instead?

`.\foo.go2:7: undefined: unexportedFunc`

foo.go:
```go
// Code generated by go2go; DO NOT EDIT.


//line foo.go2:1
package main

//line foo.go2:1
import "foo/lib"

//line foo.go2:5
func main() {
//line foo.go2:5
 instantiate୦lib୦ExportedFunc୦int(0)
//line foo.go2:7
}
//line foo.go2:6
func instantiate୦lib୦ExportedFunc୦int(t (int)) {
	unexportedFunc()
}

//line :1
type Importable୦ int
//line :1
type _ lib.Importable୦
```

**Comment by ianlancetaylor** [comment]
Yes, that isn't going to work with the go2go tool, which is just for experimentation.  There are a number of cases it can't handle, and that is one of them.  This is only a deficiency of the go2go tool; any actual implementation of generics would not have this problem.

I just added a note to the go2go tool docs.
