### ISSUE TITLE
cmd/go2go: pkg names collision after import with rename

### ISSUE THREAD

**Issue by kovetskiy** [golang/go#39853]
```
go version devel +4dfbf5ab9c7 Thu Jun 25 02:57:14 2020 +0000 linux/amd64
```

`main.go`:
```
package main

import (
        lib1 "bug/lib1"
        lib2 "bug/lib2"
)

func main() {
        impl1 := lib1.Bug(int){X: 1}
        impl2 := lib2.Bug(int){X: 1}
        _ = impl1
        _ = impl2
}
```

`lib1/a.go` and `lib2.go` are identical:
```
package lib

type Bug(type T) struct {
        X T
}
```

```
$ go tool go2go build
a.go2:5: lib redeclared as imported package name
        previous declaration at a.go2:5
a.go2:4: instantiate୦lib୦Bug୦int redeclared in this block
        previous declaration at a.go2:13
/usr/lib/go/bin/go [build] failed: exit status 2
```

**Comment by ianlancetaylor** [comment]
Thanks.  This is a bug in the translation tool that lets people experiment with generics.  I'll leave this issue open, but I don't expect to fix this.  While experimenting with generics, don't rename your imports.  If someone else wants to fix it, that would be fine.

**Comment by ALTree** [comment]
The go2go branch is [no longer maintained](https://go.googlesource.com/go/+/refs/heads/dev.go2go/README.go2go.md):

> This branch was published in 2020 and is no longer being maintained. The generics proposal has been accepted and development is now focused on implementing the proposal in the ordinary Go tools.

So I think we can close here.
