### ISSUE TITLE
cmd/go2go: Looks like the type checker fails to report an error.

### ISSUE THREAD

**Issue by mmaedel** [golang/go#39852]
Looks like the type checker fails to report an error.

Smaller test case:

```Go
package main

type Optional(type T) struct {
	p   T
	set bool
}

func (o Optional(T)) Val() (T, bool) {
	return o.p, true
}

type Box(type T) interface {
	Val() (T, bool)
}

func F1(type V interface{}, A, B Box(V))() {}

func main() {
	F1(int, Optional(int), Optional(string))()
}
```

This requires that both `Optional(int)` and `Optional(string)` implement `Box(int)`.  `Optional(int)` does implement it, but `Optional(string)` does not.  The type checker passes this without error but probably should not.

_Originally posted by @ianlancetaylor in https://github.com/golang/go/issues/39754#issuecomment-647687191_

**Comment by mmaedel** [comment]
Hello

I am not able to confirm if this happens with the dev.go2go branch (https://go.googlesource.com/go/+/refs/heads/dev.go2go/README.go2go.md), because I did not build it.

But the following reproduces in the Go playground at https://go2goplay.golang.org:

with https://go2goplay.golang.org/p/SvjDqoK0Avc you get a **program exit**.

but with e.g.:

https://go2goplay.golang.org/p/4W1iYApaV74

or 

https://go2goplay.golang.org/p/S9HkrNZ2YX-

...

you get an **error message**: 

"type checking failed for main" + additional import failure

Not sure if this is an _issue_  in the go2 branch.

regards Matthias

**Comment by ianlancetaylor** [comment]
Thanks, but this is already covered by #39754.  We don't need another issue for it.

(When I said in #39754 that we should have a separate issue, I was referring to your comment, not to my comment.)
