### ISSUE TITLE
cmd/go2go: Having a _test.go2 file that is alphabetically first makes the package unimportable

### ISSUE THREAD

**Issue by argusdusty** [golang/go#39851]
### What version of Go are you using (`go version`)?

<pre>
C:\Users\argusdusty\Code\src\foo>go version
go version devel +4dfbf5ab9c Thu Jun 25 02:57:14 2020 +0000 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

reproduces with 4dfbf5a

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
C:\Users\argusdusty\Code\src\foo>go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\argusdusty\AppData\Local\go-build
set GOENV=C:\Users\argusdusty\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\argusdusty\Code\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\argusdusty\Code
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Gosrc
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Gosrc\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ARGUSD~1\AppData\Local\Temp\go-build897251974=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

foo/lib/a_test.go2:
```go
package lib
```

foo/lib/lib.go2:
```go
package lib

func Func() {
	println("Hello, World!")
}
```

foo/foo.go2:
```go
import "foo/lib"

func main() {
	lib.Func()
}
```

`C:\Users\argusdusty\Code\src\foo>go tool go2go build`

### What did you expect to see?

Successful compilation.

### What did you see instead?
`.\foo.go2:7: undefined: lib.Importable୦`

Renaming `a_test.go2` to `lib_test.go2` resolves the issue and builds/runs successfully. Viewing the generated .go files shows `type Importable୦ int` is being placed in the alphabetically first file, even if that is a _test.go file.

This can also be replicated by attempting to import `"github.com/argusdusty/sort2"` which has `export_test.go2` as the alphabetically first file.

**Comment by ianlancetaylor** [comment]
Thanks.  This is now fixed on the dev.go2go branch.
