### ISSUE TITLE
x/tools/gopls: fillstruct return invalid code when using pointers to builtin type

### ISSUE THREAD

**Issue by leitzler** [golang/go#39854]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 darwin/amd64
$ go list -m golang.org/x/tools golang.org/x/tools/gopls
golang.org/x/tools@v0.0.0-20200624163319-25775e59acb7
golang.org/x/tools/gopls@v0.0.0-20200624163319-25775e59acb7
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
n/a
</pre></details>

### What did you do?
Called the fillstruct code action on the following code:
```go
package main

type Foo struct {
    a *bool
    b *int
    c *string
}

func main() {
    _ = Foo{}
}
```

### What did you expect to see?
Valid code, using `new(..)` instead?

### What did you see instead?
```go
package main

type Foo struct {
    a *bool
    b *int
    c *string
}

func main() {
    _ = Foo{
        a: &false,
        b: &0,
        c: &"",
    }
}
```

/cc @joshbaum

**Comment by heschik** [comment]
Is `new` actually useful? I assumed the idea of filling the struct in was that you could easily change the values. But `new` can only give zero values. Why not nil?

**Comment by leitzler** [comment]
@heschik probably not useful but acts more consistent with pointer-to-struct for example. And gives the user a direct hint that just `nil` would hide. I really have no strong opinion except that it shouldn't produce invalid code at least :)
