### ISSUE TITLE
net/mail Error while parsing an email address with string literal(\n) inside a quoted string

### ISSUE THREAD

**Issue by TVenuMadhav** [golang/go#39856]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version 1.11.5 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
yes,  https://play.golang.org/p/RPf1mhjMTby (playground go1.14.3)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tvm/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tvmv/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gn/9krbz6jn7dlcglg8y_2plq5c0000gp/T/go-build519177471=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://play.golang.org/p/RPf1mhjMTby

```
package main

import (
	"fmt"
	"net/mail"
)

func main() {
	sample_addresses := []string{"\"Testing \n Parsing\" <abc@def.com>", "\"Testing \\n Parsing\" <abc@def.com>"}
	
	for i := range sample_addresses {
		addr, err := mail.ParseAddress(sample_addresses[i])
		if err != nil {
			fmt.Println(i, "[ERROR]: ", err)
		} else {
			fmt.Println(i, "[NO ERROR]: ", addr.Name, addr.Address)
		}
	}
}
```

### What did you expect to see?
```
0 [NO ERROR]:  Testing \n Parsing abc@def.com
1 [NO ERROR]:  Testing n Parsing abc@def.com
```
### What did you see instead?
```
0 [ERROR]:  mail: missing word in phrase: mail: bad character in quoted-string: '\n'
1 [NO ERROR]:  Testing n Parsing abc@def.com
```

**Comment by davecheney** [comment]
According to https://tools.ietf.org/html/rfc5322#section-3.2.4, a quoted string may only contain ascii values, 33, 35-91 , and 93-126.

`\n` is ascii 10 which is not valid according to my reading of section 3.2.4.

Can you explain how you came across this arguably invalid address, does it appear in the wild?

**Comment by TVenuMadhav** [comment]
Thanks,

`Can you explain how you came across this arguably invalid address, does it appear in the wild?` 

No, The email fields were generated

I had `\n` in the name field after generating the email and the parsing using mail package (similar to above example) raised the error

I also want to point out that '\t' in the quoted string, somehow gets parsed (even though it is ascii 9) https://play.golang.org/p/Pgwes5n-N5y

**Comment by davecheney** [comment]
I don’t disagree that mail.Parse can be inconsistent, see #39591, but it’s important to recognise any changes should drive towards better compliance with the RFC, so starting from what is valid according to the spec is probably a good place to start.

**Comment by mvdan** [comment]
Closing old issues that still have the WaitingForInfo label where enough details to investigate weren't provided. Feel free to leave a comment with more details and we can reopen.
