### ISSUE TITLE
x/tools/gopls: "illegal line number"-panic in fillstruct

### ISSUE THREAD

**Issue by leitzler** [golang/go#39855]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 darwin/amd64
$ go list -m golang.org/x/tools golang.org/x/tools/gopls
golang.org/x/tools@v0.0.0-20200624163319-25775e59acb7
golang.org/x/tools/gopls@v0.0.0-20200624163319-25775e59acb7
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
n/a
</pre></details>

### What did you do?
Called the fillstruct code action on the following code trying to fill Foo:

```go
package main

type Foo struct {
        a map[int]struct{}
        b map[int]*bool
}

func main() {
    _ = Foo{}
}
```

### What did you expect to see?
No panic

### What did you see instead?
Panic in the analyser: `analysis fillstruct for package x panicked: illegal line number`

//cc @joshbaum

**Comment by stamblerre** [comment]
I think this should be fixed by https://golang.org/cl/239751. Are you still seeing it with that CL?

**Comment by danp** [comment]
I was having this issue as well with v0.4.2-pre1 and just confirmed that gopls at tools/tip (including 239751) is no longer erroring on fillstruct where v0.4.2-pre1 was. Thanks!

**Comment by stamblerre** [comment]
Perfect, thanks for following up! Closing.
