### ISSUE TITLE
x/website: missing alt tags on gopher images in 3 pages

### ISSUE THREAD

**Issue by nel417** [golang/go#39861]
### What version of Go are you using (`go version`)?

<pre>
go version go1.14.4 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

No, This is a website issue

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nl/Library/Caches/go-build"
GOENV="/Users/nl/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/nl/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3c/ddb5w67960nd39gnzw3mysqc0000gn/T/go-build542050604=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

A few pages on the Go website, Documents, Project, And Help, are scoring a 90 SEO and 93 accessibility because of missing alt tags. Via Lighthouse

### What did you expect to see?
Images with alt tags

### What did you see instead?
No alt tags, most pages have 100 accessibility and SEO, but these 3 pages were off.

**Comment by ianlancetaylor** [comment]
Thanks.  Since you already know specific pages that have problems, it would help a lot if you could mention them.

**Comment by dmitshur** [comment]
> A few pages on the Go website, Documents, Project, And Help,

From that description, I understand it's these URLs:

-	https://golang.org/doc/ - two img.gopher elements are missing alt attribute
-	https://golang.org/project/ - img.gopher is missing alt attribute
-	https://golang.org/help/ - img.gopher is missing alt attribute

They are indeed missing alt attribute on the gopher images. Please let us know if I misunderstood, @nel417.

/cc @andybons

**Comment by nel417** [comment]
@dmitshur yes, looks perfect. Those are the images and URLs I was seeing that were missing a few alt tags.

**Comment by nohe427** [comment]
Made a change here : https://go-review.googlesource.com/c/website/+/240257

Not sure where the help file nor where the project file is located at.  Any guidance would be appreciated.

**Comment by dmitshur** [comment]
> Not sure where the help file is located at. Any guidance would be appreciated.

That file is still in the main Go repository, [here](https://github.com/golang/go/blob/12c01f7698cd257b7d2e4795b0f8a971ec8533b6/doc/help.html).

**Comment by nohe427** [comment]
Hi @dmitshur - thanks for the quick review.  I made changes to the commit message and I think I got the tests passing now after running `go generate golang.org/x/website/content/static`.  This seems to have made the failing tests pass, but I do not seem to have the ability to re-fire the trybots.  Any guidance would be appreciated.

**Comment by dmitshur** [comment]
Thank you. I can re-run the trybots now.

**Comment by nohe427** [comment]
Hi @dmitshur - Would you want the alt tag for the footer updated to also reflect a lowercase 'g'.  i.e., change the alt tag from "The Go Gopher" to "The Go gopher" in the alt attribute for the footer on each page?

**Comment by dmitshur** [comment]
@nohe427 I didn't see there was already precedent for it on the same page, thanks for spotting that. Looks like it's not consistent with the blog post. Oh well, we're going with an empty string alt attribute, so let's not change other things for now.

**Comment by nohe427** [comment]
Hi @dmitshur - thanks for the quick turn around!  Updated the specified pages with empty alt tags.  Let me know if there is anything else needed before submitting.

**Comment by nohe427** [comment]
Thanks for the +2 to review.  It seems I am unable to submit with the codereview.  Is there something I am missing?

**Comment by dmitshur** [comment]
No worries, I can submit for you. (You can read more about Gerrit access [here](https://golang.org/wiki/GerritAccess).) I just wanted to give you a chance to update the commit message if you wanted. I'll submit soon.

The update will be live on golang.org after the next time it's redeployed. The change in the /help/ file will take longer, because it's in the main Go repo, so it'll get updated when 1.15 is out.

**Comment by nohe427** [comment]
@dmitshur - ahh okay.  Many thanks!  Thank you for the quick reviews and turnaround time.

**Comment by dmitshur** [comment]
Thank you for contributing a fix for this issue!
