### ISSUE TITLE
x/blog: in /wire blog post, go generate example not working (?)

### ISSUE THREAD

**Issue by jeffdahl** [golang/go#39872]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.3 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/nas/jeff/.cache/go-build"
GOENV="/nas/jeff/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/nas/jeff/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build483193468=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<code>go generate</code> did nothing, while <code>wire</code> worked.

### What did you expect to see?
A wire generated file.

### What did you see instead?
No wire generated file.

**Comment by ALTree** [comment]
Hi,

> What did you do?
>
> go generate did nothing, while wire worked.

I'm not sure what this means. Can you add more details (are you reading a blog post on blog.golang.org? Which one?)?

**Comment by D1CED** [comment]
This one most likely: https://blog.golang.org/wire

**Comment by jeffdahl** [comment]
Yes, I was following the example at https://blog.golang.org/wire where it states:
`Now we run go generate to execute wire:

$ go generate
wire.go:2:10: inject initUserStore: no provider found for ConnectionInfo (required by provider of *mysql.DB)
wire: generate failed`

At this point, I did not realize one is required to run `wire` before `go generate`.

**Comment by dmitshur** [comment]
It seems that error is expected. The next paragraph says:

> Oops! We didn't include a `ConnectionInfo` or tell Wire how to build one. Wire helpfully tells us the line number and types involved. We can either add a provider for it to `wire.Build`, or add it as an argument:
>
> [...]
>
> Now `go generate` will create a new file with the generated code:

Did you follow those steps?

Also, what's the output if you run `go generate -x`?
