### ISSUE TITLE
runtime: Segmentation Fault when initializing slice: type []string

### ISSUE THREAD

**Issue by udishamir** [golang/go#39875]
### What version of Go are you using (`go version`)?  

<pre>
$ go version go1.10.4 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build512368729=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
initialized slice:
var myslice []string = []string{"abcdefg", " ABCDEFG"} <<-- pay attention to the space in the second element 

### What did you expect to see?
warning, not crash

### What did you see instead?
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x528886]

**Comment by randall77** [comment]
Please provide a full program that crashes, with reproduction instructions.
That line definitely shouldn't segfault, space or not.

**Comment by udishamir** [comment]
Ok, ill check whats up on my side again,
