### ISSUE TITLE
cmd/cgo: C.void broken by CL 230037

### ISSUE THREAD

**Issue by mdempsky** [golang/go#39877]
Given:

```
package p
import "C"
var x *C.void
```

cgo now emits:

```
type _Ctype_void = _Ctype_void

type _Ctype_void [0]byte
```

in `_cgo_gotypes.go`. It used to only emit the second line.

The type alias needs to be suppressed.

**Comment by rsc** [comment]
FWIW, here is a list of references to C.void in a snapshot of latest modules from the proxy from March 2020. Not a ton but more than I expected.

[voids.txt](https://github.com/golang/go/files/4839657/voids.txt)
