### ISSUE TITLE
crypto/x509/pkix: Name.String overwrites ExtraNames backing store

### ISSUE THREAD

**Issue by rsc** [golang/go#39873]
CL 229864 added code to Name.String that looks like:

	if len(n.ExtraNames) == 0 {
		for _, atv := range n.Names {
			...
			n.ExtraNames = append(n.ExtraNames, atv)
		}
	}

ahead of the existing

	return n.ToRDNSequence().String()

This code has a subtle bug: if n.ExtraNames has len 0 but non-zero cap, this loop scribbles over n.ExtraName's backing store. By convention, String methods don't mutate the receiver, but this one does.

The code should add

	n.ExtraNames = nil // avoid writing on caller's slice backing store

just before the for loop.

A test of Name.String would also be good.
(I'm surprised this package has no tests at all.)

**Comment by g13013** [comment]
@cagedmantis does this issue require the `Name.String` test to be accepted ? 

PS: I've never contributed to Golang and started yesterday

**Comment by g13013** [comment]
@cagedmantis @rsc
The [CL](https://go-review.googlesource.com/c/go/+/240317) contains the fix for this issue.

> A test of Name.String would also be good.
> (I'm surprised this package has no tests at all.)

It turned out that the tests for this package where under the `x509` package in  `crypto/x509/x509_test.go` file

should I move the test as part of this issue ?

**Comment by g13013** [comment]
After a quick look, it seems that moving tests to `pkix` package would lead to duplication in test fixtures.

**Comment by odeke-em** [comment]
Here is a test for @rsc's mentioned bug, that we can perhaps use in the fix to prevent regressions
```go
package pkix_test

import (
	"encoding/asn1"
	"reflect"
	"testing"
	"crypto/x509/pkix"
)

// Issue 39873: Ensure that invoking Name.String() when ExtraNames is empty
// but with a non-zero capacity, won't overwrite the backing store.
func TestNameDotStringDoesnotOverwriteBackingSlice(t *testing.T) {
	backing := make([]pkix.AttributeTypeAndValue, 0, 5)
	backing = append(backing, pkix.AttributeTypeAndValue{
		Type: asn1.ObjectIdentifier([]int{1, 2, 3, 4, 5}), Value: "original.org",
	})
	n := &pkix.Name{
		Locality: []string{"Gophertown"},
		Names: []pkix.AttributeTypeAndValue{
			{Type: asn1.ObjectIdentifier([]int{1, 2, 3, 4, 5}), Value: "tbd.org"},
		},
		ExtraNames: backing[:0],
	}
	if g, w := n.String(), "1.2.3.4.5=#13077462642e6f7267,L=Gophertown"; g != w {
		t.Errorf(".String mismatch\nGot:  %q\nWant: %q", g, w)
	}
	wantExtraNames := []pkix.AttributeTypeAndValue{
		{Type: asn1.ObjectIdentifier([]int{1, 2, 3, 4, 5}), Value: "example.org"},
	}
	if false && !reflect.DeepEqual(n.ExtraNames, wantExtraNames) {
		t.Fatalf("ExtraNames mismatch\nGot:  %+v\nWant: %+v\n", n.ExtraNames, wantExtraNames)
	}
	wantBacking := []pkix.AttributeTypeAndValue{
		{Type: asn1.ObjectIdentifier([]int{1, 2, 3, 4, 5}), Value: "original.org"},
	}
	if !reflect.DeepEqual(backing, wantBacking) {
		t.Fatalf("Backing mismatch\nGot:  %+v\nWant: %+v\n", backing, wantBacking)
	}
}
```
