### ISSUE TITLE
encoding/xml: roll back case-insensitive xml check

### ISSUE THREAD

**Issue by rsc** [golang/go#39876]
Consider this program:

```
package main

import (
	"encoding/xml"
	"fmt"
	"log"
)

type Obj struct {
	SchemaLocation string `xml:"http://www.w3.org/2001/XMLSchema-instance schemaLocation,attr,omitempty"`
	Data           int
}

var x = Obj{"wherever", 9}

func main() {
	enc, err := xml.Marshal(&x)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(string(enc))
}
```

https://play.golang.org/p/i4ok93G8oUu

In Go 1.14, it prints

```
<Obj xmlns:XMLSchema-instance="http://www.w3.org/2001/XMLSchema-instance" XMLSchema-instance:schemaLocation="wherever"><Data>9</Data></Obj>
```

In Go 1.15 beta, it prints 

```
<Obj xmlns:_XMLSchema-instance="http://www.w3.org/2001/XMLSchema-instance" _XMLSchema-instance:schemaLocation="wherever"><Data>9</Data></Obj>
```

Note the \_ before XMLSchema. 

This change from CL 203417 is documented in the release notes, but it and the release notes description should probably be rolled back. As implemented there is no way to emit this tag anymore - in Go 1.15 there seems to be no way to write a program that generates that output. We need to provide some way to keep programs like this from breaking, or at least to be able to fix them when they do break. 

For Go 1.15, let's just roll back the change.

**Comment by ianlancetaylor** [comment]
CC @odeke-em

**Comment by tgulacsi** [comment]
But why?

According to https://github.com/golang/go/issues/35151#issuecomment-546290210, anything starting with xml should be treated as reserved.

**Comment by odeke-em** [comment]
@tgulacsi as Russ mentioned it introduces a breaking behavior, but we unfortunately have run out of time as Go1.15 will be released in a few days. Please don’t be discouraged, Go aims for as much compatibility and we have the Go1 compatibility promise to hold up as our mandate. We can try again early enough for Go1.16 and address both issues. Your contribution was awesome, and Russ even sent the release note for it. n Go1.16. I look forward to us tackling this again early for feedback, and I look forward to reviewing your changes again, if you’ve got bandwidth. Thank you!

**Comment by tgulacsi** [comment]
I'm not offended, just flabbergasted :)
My original problem (#35151) had just the same example: XMLInstance.
If we can't change/specify the attribute namespace tag name, then how will we resolve this issue?

I just don't care about this shit thing XML with namespaces for beans, but sadly for living I have to interact with other Enterprise things that think XML is THE BEST thing for data interchange and RPC.

This XMLInstance issue came to me as the other end has reported it as an error.
So since then I'm replacing the attribute tags in the encoded XML - works, but really not nice: a hack.

My main question is for a real example where _XMLInstance causes problems: here it is not clarified!

**Comment by andybons** [comment]
@tgulacsi from doing extensive testing on internal targets we’ve identified some programs and/or tests that rely on the previous output. This is typically a signal that programs outside of the corpus of tests we run are also affected, so we are rolling back with the intention of trying again in Go 1.16. Again, this is not to say your change will never make it in, but when we make a call late in the cycle it’s typically a conservative one.

We do appreciate your contributions and are happy to revisit this in the next cycle.

**Comment by ianlancetaylor** [comment]
@tgulacsi In particular it looks like we need some mechanism to let programs emit tags that start with "xml", even if that is technically invalid.  Those programs work today, and it doesn't seem like a good idea to break them without giving them a path forward.
