### ISSUE TITLE
cmd/go2go: no checking for missing function body

### ISSUE THREAD

**Issue by tdakkota** [golang/go#39888]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +4dfbf5ab9c Thu Jun 25 02:57:14 2020 +0000 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
n/a

### What operating system and processor architecture are you using (`go env`)?
n/a
### What did you do?
https://go2goplay.golang.org/p/tSna2j-6Epe

### What did you expect to see?
Something like
```
./prog.go:3:6: missing function body
```

### What did you see instead?
Successful compilation.

**Comment by ianlancetaylor** [comment]
What command are you running?

This is what I see:

```
> go tool go2go run ~/foo.go2
# command-line-arguments
./foo.go2:3: missing function body
/home/iant/gogen/bin/go [run foo.go] failed: exit status 2
```

**Comment by tdakkota** [comment]
I ran
`$ go run cmd/go2go translate ./issue.go2`

**Comment by tdakkota** [comment]
Seems already fixed. Closing.
