### ISSUE TITLE
cmd/go2go: embedding doesn't seem to work?

### ISSUE THREAD

**Issue by lavalamp** [golang/go#39881]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +1b08acee45 Thu Jun 25 23:22:18 2020 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, as of commit 1b08acee45f9215029c34abbb4edaefcfd1d5218

### What did you do?

```
$ go tool go2go run err.go2 
# command-line-arguments
./err.go2:8: undefined: embedPair
./err.go2:8: type a is not an expression
./err.go2:8: type b is not an expression
```

where err.go2 is:

```
package main

type a struct{}
type b struct{}
type c struct{}

type embedPair(type T, U) struct {
        T
        U
}

func main() {
        _ = embedPair(embedPair(a, b), c){}
}
```

It gives a different error in the playground: https://go2goplay.golang.org/p/2h7HWFVkvW2

(a couple days ago it crashed, so this is better than it was)

### What did you expect to see?

I expected it to construct a type like:

```
type x struct {
  a
  b
}

type y struct {
  x
  c
}
```

Only `x` will be unnamed, so I'm not sure how this is supposed to work, which is why I was trying it.

### What did you see instead?

It gives confusing error messages.

**Comment by dpinela** [comment]
I am running into (possibly) the same problem (this is simplified from a more complicated function):

```go
package main

func P(type T, U)(x T, y U) struct {
	T
	U
} {
	return struct {
		T
		U
	}{x, y}
}

func main() {
	_ = P(5, "apples")
}
```

**Comment by ianlancetaylor** [comment]
Thanks.  These test cases should now be fixed on the dev.go2go branch.
