### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by Darthsoviet** [golang/go#39887]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/Darthsoviet/twitter-go-react?tab=overview
 
### What is your user agent?
 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

 
 
 
### Screenshot
![Captura de pantalla (39)](https://user-images.githubusercontent.com/31465914/85910088-9c3da900-b7e2-11ea-977f-4b945c5c6157.png)

 

 
 
 
### What did you do?

nothing I think i just pushed the package. but it doesn't suppose to be there,

**Comment by dmitshur** [comment]
Can you please provide answers to the questions "What did you expect to see?" and "What did you see instead?" in the issue template? Otherwise, it's hard to tell what this issue is about. Thanks.

Also please see https://pkg.go.dev/license-policy, as it might be relevant.

/cc @julieqiu

**Comment by Darthsoviet** [comment]
i just want to remove that package, I better send a mail to go-discovery-feedback@google.com thanks for the assist :)
