### ISSUE TITLE
x/pkgsite: license detection fails for github.com/golang/freetype

### ISSUE THREAD

**Issue by jba** [golang/go#39894]
The [LICENSE file at the current master](https://github.com/golang/freetype/blob/e2365dfdc4a05e4b8299a783240d4a7d5a65d4e4/LICENSE) describes an OR of two licenses, which are provided in a subdirectory.

I don't know if the licensing can be altered to be more acceptable to pkg.go.dev.

/cc @nigeltao

**Comment by nigeltao** [comment]
I doubt that the `github.com/golang/freetype` license can be altered. It's the same your-choice-of-two license as the C Freetype repository: https://www.freetype.org/license.html

**Comment by jba** [comment]
We now accept this license, and the docs and README are visible at pkg.go.dev.
