### ISSUE TITLE
go 1.14 context.WithValue value is map type error

### ISSUE THREAD

**Issue by kjcx** [golang/go#39909]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.14.4
</pre>

### Does this issue reproduce with the latest release?

yes 1.13 is right

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?

package main

import (
	"context"
	"fmt"
)

func main(){
	var md = make(map[string]string)
	md["test"] = "it a map"
	ctx := context.WithValue(context.TODO(),"key",md)
	fmt.Println(ctx)
}
context.TODO.WithValue(type string, val <not Stringer>

context WithValue donot write map type

### What did you see instead?
can write map

**Comment by davecheney** [comment]
Do you mean that when you printed the value of `ctx` it was missing some information?
