### ISSUE TITLE
net/mail: ParseDate Does not correctly parse RFC5322 timezone

### ISSUE THREAD

**Issue by NDagestad** [golang/go#39906]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
...
GOARCH="amd64"
GOHOSTARCH="amd64"
GOOS="linux"
...
</pre></details>

### What did you do?
https://play.golang.org/p/BFTQrcW9JzP
```go
package main

import (
	"fmt"
	"net/mail"
)

func main() {
	t, err := mail.ParseDate("Sun, 28 Jun 2020 21:51:24 UT")
	if err != nil {
		fmt.Printf("%v\n", err)
	} else {
		fmt.Printf("%s\n", t)
	}
}
```

### What did you expect to see?
```
2020-06-28 21:51:24 +0000 UT
```

### What did you see instead?
```
mail: header could not be parsed
```

# Research

I looked at the source and found where the problem lies.
`time.Parse()` does not accept UT as a valide timezone even though rfc5322 allows it ([section 4.3](https://tools.ietf.org/html/rfc5322#section-4.3)) because `time.parseTimeZone()` does not see a timezone with less than 3 characters as valid.

This could be fixed by adding a special case in `email.ParseDate()` if the timezone is "UT" and change it to something `time.Parse()` accepts, or adding yet another special case to `time.Parse()`.

**Comment by iWdGo** [comment]
Somehow duplicates #39260 as obsolete time zones are not supported.

**Comment by NDagestad** [comment]
Do you mean it should not be fixed ?
I get that obsolete timezones should not be generated, but there are many mail servers still sending email with them in their date fields.
Regardless, all the obsolete timezones should be treated the same way, don't you think ?

**Comment by ianlancetaylor** [comment]
I think the point is that any fix in this area may as well fix both issues at the same time.

**Comment by jimist** [comment]
@ianlancetaylor I'm going for this if it's not a work in progress. 
It will be my first contribution to Go Repo, any tips would be appreciated. :-D

**Comment by ianlancetaylor** [comment]
@jimist Go for it.  Thanks.  The place to change is probably `net/mail.ParseDate`.

**Comment by jimist** [comment]
@ianlancetaylor 
As a follow-up explanation, the tests of UT were used for testing if any timezone with T shouldn't work and they're now **valid**.
Since UT is just a standard, I replaced it with UTC to be used as the timezone.
