### ISSUE TITLE
cmd/go2go: "Failed: exit status 1" while compiling "dev.go2go" branch

### ISSUE THREAD

**Issue by Dentrax** [golang/go#39914]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.8 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""

GOARCH="amd64"

GOBIN=""

GOCACHE="/Users/ft/Library/Caches/go-build"

GOENV="/Users/ft/Library/Application Support/go/env"

GOEXE=""

GOFLAGS=""

GOHOSTARCH="amd64"

GOHOSTOS="darwin"

GONOPROXY=""

GONOSUMDB=""

GOOS="darwin"

GOPATH="/Users/ft/go"

GOPRIVATE=""

GOPROXY="https://proxy.golang.org,direct"

GOROOT="/usr/local/Cellar/go/1.13.8/libexec"

GOSUMDB="off"

GOTMPDIR=""

GOTOOLDIR="/usr/local/Cellar/go/1.13.8/libexec/pkg/tool/darwin_amd64"

GCCGO="gccgo"

AR="ar"

CC="clang"

CXX="clang++"

CGO_ENABLED="0"

GOMOD="/Users/ft/go/src/goroot/src/go.mod"

CGO_CFLAGS="-g -O2"

CGO_CPPFLAGS=""

CGO_CXXFLAGS="-g -O2"

CGO_FFLAGS="-g -O2"

CGO_LDFLAGS="-g -O2"

PKG_CONFIG="pkg-config"

GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nq/vxjjn3311fg4q263qsxrghpcpzgp66/T/go-build598399094=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Trying to compile **Go 2** from `dev.go2go` branch as described in the [installation guide](https://golang.org/doc/install/source).

`CGO_ENABLED=0 ./all.bash`

I checked `dmesg` and memory usage as described by @bradfitz [this message](https://github.com/golang/go/issues/19488#issuecomment-285573539) and I couldn't see anything there. I've checked the memory values while it was compiling, and still had `50%` free RAM to use. I couldn't see a killed process in `dmesg` either.

But unlike `all.bash`,`./make.bash` exits with `0`. Builds succeeds.

### What did you expect to see?

Supposed to be build succeeds.

### What did you see instead?

`go tool dist: Failed: exit status 1`

**Comment by ianlancetaylor** [comment]
Please show us the last 100 lines or so of output.  Thanks.

**Comment by Dentrax** [comment]
I was able to compile `dev.go2go` branch with success using both of Go 1.15 and 1.16. I was opened the issue without implementing the full output. That's my mistake. I think we can close this issue. 🙏
