### ISSUE TITLE
net/http/server.go: [feature support] Will ListenAndServeTLS(certFile, keyFile string) support []byte parameter for encrypted private key?

### ISSUE THREAD

**Issue by baolinCloud** [golang/go#39916]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.14.2
</pre>

### Does this issue reproduce with the latest release?

1.14.2

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
amd64/linux
</pre></details>

### What did you do?
I need to new a https server with encrypted private key file, but ListenAndServeTLS only support filepath parameter.

1.  execute openssl cmd to decrypted the private key file to []byte.
2.  use tls.X509KeyPair to generate certificate.
3. tls.NewListener

With much work to do which same with the function  ListenAndServeTLS(certFile, keyFile string), the only differnece is the parameter type.

### What did you expect to see?

 ListenAndServeTLS(certBytes, keyBytes []bytes)

**Comment by antong** [comment]
net/http [Server](https://golang.org/pkg/net/http/#Server) has a [TLSConfig](https://golang.org/pkg/crypto/tls/#Config) member for which you can specify Certificates or a GetCertificates funtion.

Please also see https://github.com/golang/go/wiki/Questions .

**Comment by baolinCloud** [comment]
TLSConfig works，thanks!
