### ISSUE TITLE
run golang cpu profile for 5mins but only got 1.64mins (32.69%) samples

### ISSUE THREAD

**Issue by qibobo** [golang/go#39922]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.10
</pre>

In the container, the golang process used 100% of the CPU. When I took a 5minutes CPU profile, the result shows that only 1.64mins (32.69%) samples are returned. Is it normal?
```
go tool pprof autoscaler_cpuprofile.out
File: autoscaler
Type: cpu
Time: Jun 29, 2020 at 11:21pm (CST)
Duration: 5.01mins, Total samples = 1.64mins (32.69%)
```

**Comment by networkimprov** [comment]
Some discussion of profiler shortcomings is here:
https://groups.google.com/forum/#!topic/golang-dev/LCJyvL90xv8

**Comment by qibobo** [comment]
@networkimprov 
Seems the answer you provided is not relevant to my question.

**Comment by networkimprov** [comment]
This issue tracker is for bug reports and proposals. You'll get more & quicker responses to questions by posting on golang-nuts or golang-dev. I referred you to a discussion where folks would answer your question.

**Comment by qibobo** [comment]
@networkimprov thank you.
