### ISSUE TITLE
x/tools/gopls: support fillstruct for "anonymous struct" struct fields

### ISSUE THREAD

**Issue by joshbaum** [golang/go#39929]
The fix needs to be made at this [TODO](https://github.com/golang/tools/blob/f1c4188a97a1cbc0a5408db2e5b0d7b0dca73271/internal/analysisinternal/analysis.go#L113) in the analysisinternal package.

Edited by @stamblerre to add an example. Consider the following struct definition and literal.

```go
package main

type Foo struct {
    Bar struct { Baz int }
}

func main() {
    foo := Foo{<>}
}
```

Expected:

```go
package main

type Foo struct {
    Bar struct { Baz int }
}

func main() {
    foo := Foo{
        Bar: struct { Baz int }{
            Baz: 0,
        },
    }
}
```

Currently, `fillstruct` will not even be suggested for the `Foo` literal. This can be fixed by addressing the TODO linked above.

**Comment by stamblerre** [comment]
Fixed in https://golang.org/cl/249999.
