### ISSUE TITLE
x/pkgsite: Add Github Gopherbot -> Gerrit review

### ISSUE THREAD

**Issue by kush-patel-hs** [golang/go#39926]
### What is your user agent?
 
N/A
 
 
 
### Screenshot
 
N/A
 
 
### What did you do?

Open a PR on Github for x/pkgsite
 
 
### What did you expect to see?

Gopherbot imports the PR to Gerrit for code review
 
 
 
### What did you see instead?

No import to Gerrit for code review

**Comment by dmitshur** [comment]
> Open a PR on Github for x/pkgsite

What was the PR you opened?

**Comment by kush-patel-hs** [comment]
Sorry I haven't opened one yet on GH (I just decided to use Gerrit), I saw this one though https://github.com/golang/pkgsite/pull/1 which did not get sent to Gerrit.

**Comment by dmitshur** [comment]
That PR was created at 2020-06-17T03:22:44Z and closed at 2020-06-17T03:23:01Z (17 seconds later). It may take GerritBot a minute or two to import a PR, so it looks like it just didn't get a chance to.

I don't think there's an issue here, you should be able to send either Gerrit CLs or GitHub PRs as documented at https://golang.org/wiki/GerritBot to contribute code changes. If you try it and run into a problem, please don't hesitate to reopen this issue or file a new one. Thanks.
