### ISSUE TITLE
runtime: deadlock on blocking call

### ISSUE THREAD

**Issue by pigfox** [golang/go#39928]
This happens when compiling Go code into wasm with:
**GOOS=js GOARCH=wasm go build -o ./Go/assets/main.wasm wasm.go**

### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.14.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/peter/.cache/go-build"
GOENV="/home/peter/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/local/go:/home/peter/work"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/5830"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/5830/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build651075817=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Attempted to make a request from compiled Wasm code. 
```
func query(this js.Value, args []js.Value) interface{} {
	var rv interface{}

	c1 := make(chan string)
	go func() {
		c1 <- makeRequest()
	}()

	target:= fmt.Sprintf("%s", args[0]) + "Result"

	select {
	case color := <-c1:
		js.Global().Get("document").Call("getElementById", target).Set("innerHTML", color)
	}
	return rv
}
```

### What did you expect to see?
A string in a HTML element.

### What did you see instead?
fatal error: all goroutines are asleep - deadlock!
wasm_exec.js:47 
wasm_exec.js:47 goroutine 1 [select (no cases)]:

**Comment by dmitshur** [comment]
Thanks for reporting. This may be a problem in the code rather than the Go runtime. In order to investigate, we'll need to know how `query` being called. Can you provide more information on that please?

@neelance Is there a restriction on where blocking calls can be made (e.g., inside callbacks), and do you know if we've documented it somewhere? I'm not finding it in https://golang.org/wiki/WebAssembly.

**Comment by agnivade** [comment]
It is documented here: https://golang.org/pkg/syscall/js/#FuncOf.

**Comment by pigfox** [comment]
@dmitshur  You can clone the repo: https://github.com/pigfox/wasm and view the error.

**Comment by dmitshur** [comment]
Yep, that code is making `query` the callback handler by setting an element's onclick property:

```
onclick="query('colors');
```

The deadlock is working as intended per documentation at https://golang.org/pkg/syscall/js/#FuncOf. (Thanks @agnivade.)
