### ISSUE TITLE
Short variable declaration redeclares instead of assigns for multi-variable declaration

### ISSUE THREAD

**Issue by aaronbuchwald** [golang/go#39934]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13.8
</pre>

### Does this issue reproduce with the latest release?

Yes

Short variable declaration redeclares variable instead of using pre-existing variable

```
func main() {
	a, b := 5, 6
	if b == 6 {
		a, c := 7, 8
		if c == 5 {
			return
		}
	}
	fmt.Printf("%d", a)
}
```

variables a and b are declared using short variable declaration in the first statement. Then, after using short variable declaration to declare a, c within the body of the if statement, it reports that the variable a here is declared but not used.

Expected behavior is that the short variable declaration within the if body, should declare the new variable c and reference the already existing variable a.

**Comment by ianlancetaylor** [comment]
Using `:=` only redeclares variables declared in the same block.  It does not redeclare variables declared in an enclosing block.

This is documented at https://golang.org/ref/spec#Short_variable_declarations .
