### ISSUE TITLE
Transport.TLSNextProto

### ISSUE THREAD

**Issue by Abdelboushaba** [golang/go#39939]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by odeke-em** [comment]
Welcome to the Go project @Abdelboushaba, and thank you for filing this issue!

Could you please add some more context as to what your issue is? Please update the title as well as try to fill out the issue template. That will help in diagnosing the problem. Thank you!
