### ISSUE TITLE
for loop: breaks even if condition valuates to true

### ISSUE THREAD

**Issue by amitbasuri** [golang/go#39933]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/amitbasuri/Library/Caches/go-build"
GOENV="/Users/amitbasuri/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=" -mod="
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/amitbasuri/goWork"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/amitbasuri/sdk-go/go1.13.6"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/amitbasuri/sdk-go/go1.13.6/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/amitbasuri/goWork/src/go-algo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9c/68n6djhd0yld73s97pfgyz0r0000gq/T/go-build587761073=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.13.6 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.13.6
uname -v: Darwin Kernel Version 17.7.0: Sun Dec  1 19:19:56 PST 2019; root:xnu-4570.71.63~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G10021
lldb --version: lldb-902.0.79.7
  Swift-4.1
</pre></details>

### What did you do?
I was solving https://leetcode.com/explore/interview/card/top-interview-questions-medium/108/trees-and-graphs/786/ 
I figured out something weird happening with the `for` loop, Please find my code below.
https://play.golang.org/p/gD8uCtJURYq

### What did you expect to see?
The loop  `for root != nil || len(stack) > 0 { ...}` should not exit if the value evaluates to `true` on the previous iteration.

### What did you see instead?
The loop exits even if it evaluates to `true`.

**Comment by ianlancetaylor** [comment]
The statement

```Go
    root := stack[len(stack)-1]
```

shadows the `root` variable used by the loop condition.  You may want to use `=` rather than `:=` there.
