### ISSUE TITLE
cmd/go2go: making a slice of generics struct doesn't compile

### ISSUE THREAD

**Issue by li-go** [golang/go#39936]
### What did you do?
https://go2goplay.golang.org/p/ZBpMABeQ0r8
```go
package main

import (
	"fmt"
)

type Item(type T) struct {
	Val T
}

func NewItems(type T)(size int) []Item(T) {
	// Not compile: cannot use generic type Item(type T) without instantiation
	return make([]Item(T), size)
}

func main() {
	items := NewItems(int)(2)
	fmt.Printf("items = %#v\n", items)
}
```

### What did you expect to see?
Making a slice of generics struct compiles

### What did you see instead?
type checking failed

**Comment by li-go** [comment]
If I pre-define a generics type of the slice, it compiles.
https://go2goplay.golang.org/p/Wun2YoiGVcg
```go
package main

import (
	"fmt"
)

type Item(type T) struct {
	Val T
}

type Items(type T) []Item(T)

func NewItems(type T)(size int) []Item(T) {
	return make(Items(T), size)
}

func main() {
	items := NewItems(int)(2)
	fmt.Printf("items = %#v\n", items)
}
```

**Comment by tdakkota** [comment]
If you add parentheses, it compiles too.
https://go2goplay.golang.org/p/OSGzqlKrMsM
```go
return make([](Item(T)), size)
```

**Comment by ianlancetaylor** [comment]
This is another instance of the ambiguity described at https://go.googlesource.com/proposal/+/refs/heads/master/design/go2draft-type-parameters.md#instantiating-types-in-type-literals .
