### ISSUE TITLE
cmd/go2go: test for go/types fails

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#39935]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +71c7be55eb Mon Jun 29 16:07:10 2020 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yoshiki/Library/Caches/go-build"
GOENV="/Users/yoshiki/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/yoshiki/gocode/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/yoshiki/gocode:/Users/yoshiki/exercises/gpl:/Users/yoshiki/oak"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/yoshiki/tools/go2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/yoshiki/tools/go2/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r3/f30_9n8958j4ndrjyl1k7mp40000gn/T/go-build555842162=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version devel +71c7be55eb Mon Jun 29 16:07:10 2020 +0000 darwin/amd64
GOROOT/bin/go tool compile -V: compile version devel +71c7be55eb Mon Jun 29 16:07:10 2020 +0000
uname -v: Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101
lldb --version: lldb-1103.0.22.10
Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
</pre></details>

### What did you do?

Rebuild with all.bash

### What did you expect to see?

All tests pass.

### What did you see instead?

```
ok  	go/token	0.270s
--- FAIL: TestCheck (21.30s)
    check_test.go:273: fixedbugs/issue39754.go2:24:25: no error expected: "Optional(string) does not satisfy Box(V) (missing method Val)"
    check_test.go:332: --- main: 1 source positions with expected (but not reported) errors:
    check_test.go:335: fixedbugs/issue39754.go2:24:40: "does not satisfy Box(V) (missing method Val)"
FAIL
FAIL	go/types	22.642s
```

**Comment by griesemer** [comment]
Thanks. The fix for #39754 contained a broken test.
