### ISSUE TITLE
go.dev: package is present on godoc.org, but not on pkg.go.dev after rename

### ISSUE THREAD

**Issue by gavv** [golang/go#39941]
Hi,

Earlier, documentation of my package was present both on godoc.org and pkg.go.dev.

On June, 27 (3 days ago) I've renamed github organization to which the package belongs.

Now I've the following situation:

* old URL:

  * godoc.org: present (https://godoc.org/github.com/roc-project/roc-go/roc)
  * pkg.go.dev: present (https://pkg.go.dev/github.com/roc-project/roc-go/roc)

* new URL:

  * godoc.org: present (https://godoc.org/github.com/roc-streaming/roc-go/roc)
  * pkg.go.dev: **not present** (https://pkg.go.dev/github.com/roc-streaming/roc-go/roc)

Notes:

* the rename was `roc-project` -> `roc-streaming`
* only organization name changed, the repo name didn't
* the repo had no go.mod when by the moment of rename (now it has)
* the repo has no version tags or branches and has no explicit version in go.mod (it's still WIP)

I've also tried to follow [these instructions](https://go.dev/about#adding-a-package), but failed.

For new URL:

```
$ curl -i https://proxy.golang.org/github.com/roc-streaming/roc-go/roc/@v/v1.0.0.info
HTTP/1.1 410 Gone
Access-Control-Allow-Origin: *
Content-Type: text/plain; charset=UTF-8
Date: Tue, 30 Jun 2020 07:24:19 GMT
Expires: Tue, 30 Jun 2020 07:54:18 GMT
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0
Content-Length: 99
Cache-Control: public, max-age=1798
Age: 726
Alt-Svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"

$ GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/roc-streaming/roc-go/roc@v1.0.0
go get github.com/roc-streaming/roc-go/roc@v1.0.0: github.com/roc-streaming/roc-go/roc@v1.0.0: reading https://proxy.golang.org/github.com/roc-streaming/roc-go/roc/@v/v1.0.0.info: 410 Gone
	server response: not found: github.com/roc-streaming/roc-go/roc@v1.0.0: invalid version: unknown revision roc/v1.0.0
```

And for old URL (just in case...):

```
$ curl -i https://proxy.golang.org/github.com/roc-project/roc-go/roc/@v/v1.0.0.info  
HTTP/1.1 410 Gone
Access-Control-Allow-Origin: *
Cache-Control: public, max-age=1798
Content-Type: text/plain; charset=UTF-8
Date: Tue, 30 Jun 2020 07:36:36 GMT
Expires: Tue, 30 Jun 2020 08:06:34 GMT
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0
Content-Length: 97
Alt-Svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"

$ GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/roc-project/roc-go/roc@v1.0.0  
go get github.com/roc-project/roc-go/roc@v1.0.0: github.com/roc-project/roc-go/roc@v1.0.0: reading https://proxy.golang.org/github.com/roc-project/roc-go/roc/@v/v1.0.0.info: 410 Gone
	server response: not found: github.com/roc-project/roc-go/roc@v1.0.0: invalid version: unknown revision roc/v1.0.0
```

**Comment by heschik** [comment]
I'm not sure why you're fetching v1.0.0 given that there are no released versions. If you do `go get github.com/roc-project/roc-go/roc` everything should work fine.

We don't use the issue tracker for questions; if you need help please see https://github.com/golang/go/wiki/Questions.

**Comment by gavv** [comment]
Forgot to mention that I also tried `v0.0.0` and it didn't work too. I didn't find a way to make a request without specifying the version when using curl. My bad, I didn't think to try go get without version... That's stupid :) Sorry for bothering, thanks!
