### ISSUE TITLE
cmd/go2go: generics embedding not working as proposed

### ISSUE THREAD

**Issue by bjg2** [golang/go#39944]
### What version of Go are you using (`go version`)?

go2go playground (https://go2goplay.golang.org/)

### Does this issue reproduce with the latest release?

/

### What operating system and processor architecture are you using (`go env`)?

/

### What did you do?

Embeded generic parameter:

```
package main

import (
	"fmt"
)

type A struct {
	Something int
}

type B(type T) struct {
	T
	Common int
}

func main() {
	test := &B(A){
		T: A{
			Something: 2,
		},
		Common: 12,
	}
	fmt.Println(test)
}
```

### What did you expect to see?

That it is embeded, as described in the proposition:

![image](https://user-images.githubusercontent.com/6639273/86120499-b6260700-bad4-11ea-952e-52715402cb42.png)

### What did you see instead?

```
# play
./prog.go2:12: undefined: T
```

**Comment by andybons** [comment]
@griesemer @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Thanks for the bug report.  This works on the current dev.go2go branch.  The playground is not up to date with the branch yet.

**Comment by andybons** [comment]
The playground has been updated and this example now works: https://go2goplay.golang.org/p/GX4u5kjnwtt

**Comment by bjg2** [comment]
Yes it does now, thanks!

**Comment by ianlancetaylor** [comment]
Thanks @andybons!
