### ISSUE TITLE
cmd/vet: false positive 

### ISSUE THREAD

**Issue by martinrode** [golang/go#39949]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/martin/go/bin"
GOCACHE="/Users/martin/Library/Caches/go-build"
GOENV="/Users/martin/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/martin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/martin/go/src/github.com/programmfabrik/fylr/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4f/l31kb4n521d6g89qxrwcx69h0000gp/T/go-build954182719=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

main.go
```
// +build "go1.14"

package main

var myCmd string = ""

func main() {
	// empty
	println("henk")
}
```

dummy.go
```
package main

func init() {
	myCmd = "horst"
}
```
$ go vet

### What did you expect to see?

* go vet should not report an issue
* when compiling without the dummy.go file, go vet also wrongly reports an issue

### What did you see instead?

* vet: ./dummy.go:4:2: undeclared name: myCmd
* the problems are caused by the "+build" line

**Comment by seankhliao** [comment]
the version tags look like `// +build go1.14` without the quotes

vet is correct in reporting that the current configuration has an undefined variable. Also your code does not compile

**Comment by ianlancetaylor** [comment]
Closing because as commented above this seems to be correct behavior.  Please comment if you disagree.

**Comment by martinrode** [comment]
Ok, I just realized the +build tag **with the quotes is wrong**. It would be an improvement if go vet / go build would report that rather than the misleading error messages.
