### ISSUE TITLE
cmd/go2go: design corner cases when passing interface type arguments

### ISSUE THREAD

**Issue by tdakkota** [golang/go#39961]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +08b9fd164c Tue Jun 30 19:00:27 2020 +0000 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
n/a

### What operating system and processor architecture are you using (`go env`)?
- windows/amd64
- Go2go playground

### What did you do?
This code compiles https://go2goplay.golang.org/p/-5nF8t38Ebr - it's incorrect.

But this code does not compile https://go2goplay.golang.org/p/MdJl77uLB-g.
```go
package main

import (
	"fmt"
)

type AwesomeMap(type V interface {
	type interface{}
}) map[string]V

type A interface {
	type interface{}
	Method()
}

func main() {
	var i AwesomeMap(A)
	fmt.Println(i)
}
```

### What did you expect to see?
Compilation error in both cases.
`type interface{}` can't satisfy `interface {Method();}`

### What did you see instead?
Successful compilation.

**Comment by ianlancetaylor** [comment]
CC @griesemer 

Sorry, I'm not sure what you are saying.  You have two different examples.  One compiles, one doesn't (because `AwesomeMap` is not defined).  Under "what did you see instead" you listed both "successful compilation" and a type checking error.

Can you clarify the bug report?  Thanks.

**Comment by tdakkota** [comment]
Updated.

**Comment by griesemer** [comment]
There's a couple of issues here. In
```Go
type AwesomeMap(type V interface {
	type interface{}
}) map[string]V

var _ AwesomeMap(interface {
	type interface{}
	Method()
})
...
```
it's not clear if we should permit a type argument that itself contains a type list (this is a design question). Also, should it be possible to pass a type argument that is an interface with `Method` to a type parameter that must be an interface (but doesn't have any methods)? I think that's another open design question. It's not clear to me that this should be legal or illegal for that matter.

**Comment by griesemer** [comment]
The 2nd example behaves more sane (error reported), but I think the current design draft is unclear about exactly should happen in these cases.
