### ISSUE TITLE
x/pkgsite: combine the queue logic in /poll-and-queue and /requeue 

### ISSUE THREAD

**Issue by julieqiu** [golang/go#39975]
At the moment, we enqueue modules to the task queue via these two endpoints:

- `/poll-and-queue`: enqueues new modules from the index

- `/requeue`: enqueues modules with status 50x

As a result, when we are are reprocessing modules, new modules might end up taking longer to be proccessed. For example: https://github.com/golang/go/issues/39564 and https://gophers.slack.com/archives/C0VPK4Z5E/p1591981603268600.

Rather than calling `s.queue.ScheduleFetch` in [handleIndexAndQueue](https://github.com/golang/pkgsite/blob/08e8e660a65bf3ad770682a02fc3298b12e251b4/internal/worker/server.go#L315), we should change the enqueuing logic as follows:

- [ ] Separate `/poll-and-queue` and `/requeue` into these two endpoints:

- `/poll`: polls the module index and inserts into module version states
- `/enqueue`: call postgres.GetNextModulesToFetch to figure out which modules to enqueue next

- [ ] Change [postgres.GetNextModulesToFetch](https://github.com/golang/pkgsite/blob/35d44197af7f48418271f5bcb637fe55fd94b1dd/internal/postgres/requeue.go#L72) to prioritize enqueuing modules with status=0, ahead of modules with status 50x

- [ ] Deprecate `/poll-and-queue` and `/requeue`

**Comment by julieqiu** [comment]
Related commits:

https://github.com/golang/pkgsite/commit/08e8e660a65bf3ad770682a02fc3298b12e251b4
https://github.com/golang/pkgsite/commit/35d44197af7f48418271f5bcb637fe55fd94b1dd

**Comment by jba** [comment]
This was fixed by https://golang.org/cl/239480 and deployed.
