### ISSUE TITLE
Can't test error against poll.TimeoutError

### ISSUE THREAD

**Issue by chuacw** [golang/go#39971]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=K:\Development\Go\
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=K:\Development\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=K:\Development\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\1\go-build426989442=/tm
p/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

        c, err := icmp.ListenPacket("ip6:ipv6-icmp", "::")
	c.IPv6PacketConn().SetHopLimit(ttl)
	c.IPv6PacketConn().SetControlMessage(ipv6.FlagHopLimit, true)
	c.SetReadDeadline(time.Now().Add(30 * time.Millisecond))
	rb := make([]byte, 1500)
        n, fromIP, err := c.ReadFrom(rb)

       if errors.Is(err, poll.TimeoutError) // this can't compile because poll.TimeoutError is internal

**Comment by D1CED** [comment]
possibly a dup of #39798

**Comment by ianlancetaylor** [comment]
You didn't say why you want to do that (i.e., this is an XY problem), but I would guess that what you are trying to do is fixed in the upcoming Go 1.15 release via the new error `os.ErrDeadlineExceeded`.  See https://tip.golang.org/doc/go1.15#net and the `SetDeadline` method of https://tip.golang.org/pkg/net/#Conn.
