### ISSUE TITLE
io: Copy reports ErrShortWrite for long writes

### ISSUE THREAD

**Issue by jnjackins** [golang/go#39978]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +c875503cf7 Sun Jun 28 03:14:10 2020 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOOS="darwin"
GOPROXY="https://proxy.golang.org,direct"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you do?

I implemented a buggy io.Writer which sometimes writes too many bytes (i.e., more that the length of the []byte parameter to the Write method), and used io.Copy to write to it.

https://play.golang.org/p/UeO1GCEvmNP

### What did you expect to see?

A reasonable error message (indicating that the wrong number of bytes were written, or too many bytes were written)

### What did you see instead?

ErrShortWrite.

Based on the documented meaning of this error variable, I believe io.Copy is using it incorrectly in this case.
> ErrShortWrite means that a write accepted fewer bytes than requested but failed to return an explicit error.

For what it's worth, this came up while debugging real code: the Writer in question buffers writes and was buggy.

**Comment by ianlancetaylor** [comment]
For the record, `bufio.Scanner` recently started returning `bufio.ErrBadReadCount` for a similar case, which displays as `bufio.Scanner: Read returned impossible count`.
