### ISSUE TITLE
x/time/rate: When limit higher burst, Allow() will return true higher burst

### ISSUE THREAD

**Issue by yankooo** [golang/go#39970]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.17 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/Library/Caches/go-build"
GOEXE=""
GOFLAGS=" -mod="
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/go"
GOPROXY="direct"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/workspace/time/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cs/47hjwvp92qqb75_p9fxxm3v40000gn/T/go-build201946329=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>

### What did you do?

Run the following on amd64:

``` golang
package main

import (
	"fmt"
	"golang.org/x/time/rate"
	"sync"
	"sync/atomic"
	"time"
)

func main() {
	now := time.Now()
	t := time.After(time.Second)

	limit := rate.Limit(100)
	burst := 10
	l := rate.NewLimiter(limit, burst)

	var count int
	for {
		select {
		case <-t:
			fmt.Printf("%ds, %d\n", time.Now().Sub(now).Nanoseconds()/1e9, count)
			return
		default:
			if l.Allow() {
				count++
			}
		}
	}
}
```

### What did you expect to see?

```
1s, 10
```

### What did you see instead?

```
1s, 110
```
I confuse about `count` is not equals burst size. When I set Limit=100, burst=10, it's should Allow() for max calls is burst.

**Comment by D1CED** [comment]
Lets go through this to clear up your confusion.

You start with a full bucket of size 10.
So 10 tokens can be retrieved effectively immediately.
During the second you wait the bucket gets refilled at 100/s.
So every 100/s of a second Allow returns true.
So all in all you should see 109 to 110 tokens being drawn.

Maybe what you actually want is to have a bucket size of 100 and a refill rate of 10 (and start with an empty bucket)?

As there seems to be nothing wrong here please consider closing this issue.
