### ISSUE TITLE
x/pkgsite: support fetching the latest and master versions of the standard library

### ISSUE THREAD

**Issue by julieqiu** [golang/go#39973]
At the moment, [stdlib.Zip](https://github.com/golang/pkgsite/blob/89c2272/internal/stdlib/stdlib.go#L262) only supports fetching a [release version](https://github.com/golang/pkgsite/blob/89c2272/internal/stdlib/stdlib.go#L211) of the standard library. 

We want [stdlib.Zip](https://github.com/golang/pkgsite/blob/89c2272/internal/stdlib/stdlib.go#L262) to also support fetching the latest and master versions, for use in #37002 and #36811.

- [x] [stdlib.Zip](https://github.com/golang/pkgsite/blob/89c2272/internal/stdlib/stdlib.go#L262) supports version = "latest"
- [ ] [stdlib.Zip](https://github.com/golang/pkgsite/blob/89c2272/internal/stdlib/stdlib.go#L262) supports version = "master"

**Comment by kush-patel-hs** [comment]
I can change stdlib.Zip!

**Comment by kirandasika98** [comment]
Hi @julieqiu , Can I pick up the task to support fetching from `master`?
