### ISSUE TITLE
x/pkgsite: correctly resolve master in internal/proxy/test_helper.go

### ISSUE THREAD

**Issue by julieqiu** [golang/go#39985]
See https://github.com/golang/pkgsite/blob/master/internal/proxy/test_helper.go#L90

**Comment by gmelodie** [comment]
I could give this a `go` if that's ok :)

**Comment by julieqiu** [comment]
Please do! :)

**Comment by Stexxe** [comment]
@julieqiu could you please clarify how to reproduce this problem?

**Comment by julieqiu** [comment]
@Stexxe this issue looks outdated, so I'm going to close this issue. Thanks for looking at it!
