### ISSUE TITLE
cmd/go2go: cannot use make(map[int]X) (value of type map[int]X) as map[int]X value in struct literal

### ISSUE THREAD

**Issue by arl** [golang/go#39982]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +d014fca6d4 Wed Jul 1 20:30:10 2020 +0000 linux/amd64</pre>

### Does this issue reproduce with the latest release?

It does with latest commit of the `dev.go2go` experimental branch: d014fca6d4

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/aurelien/.cache/go-build"
GOENV="/home/aurelien/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/aurelien/godev/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/aurelien/godev"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/aurelien/dev/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/aurelien/dev/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build789085526=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

A bit of context: I'm currently experimenting with the generics draft by trying to use it to develop a generics cache library.
I compacted the code into a single-file reproducer to make debugging easier but the actual code imports various packages, among which the `list` package of the `dev.go2go` source tree (generic replacement for `container/list`).

The original cache is based off a simple `map` where the value is a `*list.Element(*entry(K)`.

```go
package main

type (
	Element(type TElem) struct{}

	entry(type K comparable) struct{}

	Cache(type K comparable) struct {
		data map[K]*Element(*entry(K))
	}
)

func main() {
	_ = Cache(int){
		data: make(map[int](*Element(*entry(int)))), // cannot use make(map[int](*Element(*entry(int)))) (value of type map[int]*Element(*entry(int))) as map[int]*Element(*entry(int)) value in struct literal
	}
}
```

It does the same on the playground: https://go2goplay.golang.org/p/qoMgsPA5ifd 

### What did you expect to see?

a successful compilation since the provided map is, AFAICT, of the same type as the `Cache.data` type.

### What did you see instead?

The error reported above:
```
cannot use make(map[int](*Element(*entry(int)))) (value of type map[int]*Element(*entry(int))) as map[int]*Element(*entry(int)) value in struct literal
```

**Comment by ianlancetaylor** [comment]
This seems like a failure in the type checker.  At least, I don't see why it shouldn't work.

**Comment by griesemer** [comment]
Definitely a type-checker failure.

**Comment by griesemer** [comment]
Fixed on dev.go2go.

**Comment by arl** [comment]
I just tested with 85ed317eb2 and now both listing (top and 2nd comments of this issue) give the same error:

```sh
$ go tool go2go run issue39982.go2
# command-line-arguments
./issue39982.go2:25: instantiate୦୦Element୦୮1main୮aentry୮8int୮9 redeclared in this block
        previous declaration at ./issue39982.go2:29
/home/aurelien/dev/go/bin/go [run issue39982.go] failed: exit status 2
```
Let me know whether you prefer a new issue for this.

**Comment by griesemer** [comment]
@arl, thanks for this. I admit I only tested type-checking for this case. Reopening.

**Comment by griesemer** [comment]
@ianlancetaylor Not sure if this is still a type-checker issue or a translator issue at this point.

**Comment by ianlancetaylor** [comment]
Thanks.  Translator is fixed on dev.go2go branch.
