### ISSUE TITLE
cmd/go2go: build tags not supported correctly

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#39998]
commit d014fca6d4924b15f0eccb3c8ca6a7f968d88f40

The go2go tool doesn't seem to recognise go build tags, which means that it's not possible to use external packages that use them (I was bitten when trying to import github.com/frankban/quicktest, for the record).

Here's a testscript reproducer:

```
exec go tool go2go build

-- go.mod --
module example.com/test

go 1.15
-- x_111.go2 --
// +build go1.11

package foo

var x = 34
-- x_112.go2 --
// +build go1.12

package foo

var x = 34
```

**Comment by tdakkota** [comment]
It happens because translator does not copy magic comments from `.go2` source.

```go
//go:noinline
func Foo() {
}
```
becomes 
```go
//line <original code line>
func Foo() {
}
```

**Comment by josharian** [comment]
FWIW, how go-fuzz handles this is by looking for initial comments and //go directives, saving them, manipulating the code (inserting coverage), and then re-inserting the comments. See functions initialComments and trimComments and related code in go-fuzz-build.

**Comment by griesemer** [comment]
I don't know off-hand how much effort is needed to make this work, but we may decide to not do anything about it. Keep in mind this is a prototype to explore the generics mechanisms; anything and everything may change as we go forward.

**Comment by ianlancetaylor** [comment]
It's not just a matter of magic comments.  The type checker gets a list of files, and it expects that build tags have already been applied at that point to remove files that it shouldn't see.

I don't mind if somebody fixes this, but I don't plan to work on it myself.  The go2go tool is meant to be an experimental translation tool, it's not meant to handle all details of how Go packages are built.

**Comment by maguro** [comment]
I have a submitted a simple PR that should be helpful to most people tinkering with generics via go2go, https://github.com/golang/go/pull/45146.

**Comment by maguro** [comment]
The PR has been merged.
