### ISSUE TITLE
OAuth2 Endpoint for Google Updated

### ISSUE THREAD

**Issue by bwjjohnson** [golang/go#39994]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
I'm building an OAuth app, and it looks like the endpoint for authorization for OAuth2 for google is: https://pkg.go.dev/golang.org/x/oauth2/google?tab=doc#pkg-variables

```
var Endpoint = oauth2.Endpoint{
        AuthURL:   "https://accounts.google.com/o/oauth2/auth",
        TokenURL:  "https://oauth2.googleapis.com/token",
        AuthStyle: oauth2.AuthStyleInParams,
}
```

### What did you expect to see?
But it looks like https://developers.google.com/identity/protocols/oauth2/web-server#httprest recommends this endpoint:

> Google's OAuth 2.0 endpoint is at https://accounts.google.com/o/oauth2/v2/auth. This endpoint is accessible only over HTTPS.

I already asked this question on golang nuts last week, with no response: https://groups.google.com/g/golang-nuts/c/_3Eu_yfWzEc

**Comment by namaggarwal** [comment]
Hi,

You should open an issue in this repo https://github.com/golang/oauth2

**Comment by bwjjohnson** [comment]
Thanks! https://github.com/golang/oauth2/issues/428
