### ISSUE TITLE
runtime/mpallocbits.go  pallocBits.summarize function problem

### ISSUE THREAD

**Issue by lmtwb** [golang/go#39990]
### example
       var p1 pageBits
	p1[0]=0b00000000_00000000_00000000_00000001_00000000_00000000_00000000_00000000
	p1[1]=0b00000000_00000000_00000000_00000001_00000000_00000000_00000000_11110000
	p1[2]=0b00000000_00000000_00000000_00000001_00000000_00000000_00000000_11110000
	p1[3]=0b00000000_00000000_00000000_00000001_00000000_00000000_00000000_11110000
	p1[4]=0b00000000_00000000_00000000_00000001_00000000_00000000_00000000_11110000
	p1[5]=0b00000000_00000000_00000000_00000001_00000000_00000000_00000000_00000000
	p1[6]=0b00000000_00000000_00000000_00000000_00000000_00000000_00000000_11110000
	p1[7]=0b00000000_00000000_00000000_00000001_00000000_00000000_00000000_01010000
        p1summarize()
       
       // return start:32   max:63  end:31
       // I think it should return start:32 max:88 end31
      // What is the strategy of this summarizefunction when calculating max

**Comment by ianlancetaylor** [comment]
CC @mknyszek

**Comment by lmtwb** [comment]
I think the function summarize has a bug, @mknyszek  think?

**Comment by randall77** [comment]
Why would max be 88? The max is 63. The high 31 zeroes of p1[4] and the low 32 zeroes of p1[5].

**Comment by lmtwb** [comment]
> Why would max be 88? The max is 63. The high 31 zeroes of p1[4] and the low 32 zeroes of p1[5].

@randall77 ，  I think it should be The high 56 zeroes of p1[6] and the low 32 zeroes of p1[5].Where do I understand the deviation?

**Comment by randall77** [comment]
The bits are ordered from low to high in each word, then in increasing word index. So the high 56 zeroes of p1[6] are adjacent to the low 4 zeroes of p1[7], not the low 32 zeroes p1[5].

This doesn't look like a bug to me.

**Comment by lmtwb** [comment]
@randall77 Thank you for your answer, you're right.
