### ISSUE TITLE
runtime % result in less zeros values

### ISSUE THREAD

**Issue by MasterDimmy** [golang/go#40004]
### What version of Go are you using (`go version`)?

<pre>
$ go version
 go1.14.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
AMD64
Windows
</pre></details>

### What did you do?

fmt.Printf("x=%d", (115-303)%1626)

output: 
x=-188

https://play.golang.org/p/yYVbpJYbp-L

### What did you expect to see?

x=1438 

### What did you see instead?

x=-188

Reminder by module deviding cant be less zero !

**Comment by D1CED** [comment]
`%` is remainder not modulo. https://stackoverflow.com/questions/13683563/whats-the-difference-between-mod-and-remainder

**Comment by randall77** [comment]
This is as specified in the spec: https://golang.org/ref/spec#Arithmetic_operators
