### ISSUE TITLE
cmd/vet: go vet should issue warning for nonsense json tags

### ISSUE THREAD

**Issue by jdef** [golang/go#40007]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.13.9 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

unsure, not tested

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE=...redacted
GOENV=...redacted
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=...redacted
GONOSUMDB=...redacted
GOOS="linux"
GOPATH=...redacted
GOPRIVATE=...redacted
GOPROXY=...redacted
GOROOT="/usr/local/go-1.13.9"
GOSUMDB=...redacted
GOTMPDIR=""
GOTOOLDIR="/usr/local/go-1.13.9/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=...redacted
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build172171850=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```go
type Foo struct {
  Bar string `json:"bar:omitempty"`
}
```

```
go vet ./...
```
(no warnings)

### What did you expect to see?

vet should warn about a possible typo: s/:omitempty/,omitempty/

### What did you see instead?

no warning, just confusing app behavior

**Comment by seankhliao** [comment]
`bar:omitempty` is a valid tag though

```go
package main

import (
	"encoding/json"
	"fmt"
)

type Foo struct {
	B string `json:"bar:omitempty"`
}

type Foo2 struct {
	B string `json:"bar,omitempty"`
}

func main() {
	b := []byte(`{"bar:omitempty": "baz"}`)

	var foo Foo
	json.Unmarshal(b, &foo)
	fmt.Println("with tag:", foo)

	// with "fixed" tag
	var foo2 Foo2
	json.Unmarshal(b, &foo2)
	fmt.Println("with fixed tag:", foo2)
}
```
outputs
```txt
with tag: {baz}
with fixed tag: {}
```

**Comment by jdef** [comment]
That's why it should be a warning, not an error. This particular example is
almost certainly a typo that will lead to unexpected behavior.

**Comment by seankhliao** [comment]
I'm going to close this as it would be somewhat backwards incompatible.
If you feel strongly about it, please file a proposal with evidence to support that it meets go vet's bar for both frequency and accuracy.
