### ISSUE TITLE
Compile error: cannot use res (type []chan x) as type []<-chan x in return argument

### ISSUE THREAD

**Issue by scorsi** [golang/go#40010]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/scorsi/Library/Caches/go-build"
GOENV="/Users/scorsi/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/scorsi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ld/l11ndr2d3xsclhqxbjjhmkbw0000gn/T/go-build147800266=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

[Check it out on play.golang.org](https://play.golang.org/p/jSAfLwWqGT1)

The code is as simple as that:
```go
func myFunc() []<-chan int {
	var res []chan int
	return res
}
```

### What did you expect to see?

When we don't use a slice, returning a receive-only channel works. Example:
```go
func myFunc() <-chan int {
	var res chan int
	return res
}
```
Why it'sn't the case for slice of chan ?

### What did you see instead?

A compile error.

**Comment by ianlancetaylor** [comment]
That is how the language works.  The fact that you can assign `chan int` to `<-chan int` doesn't mean that you can assign `[]chan int` to `[]<-chan int`.  The language rules are documented at https://golang.org/ref/spec#Assignability .

**Comment by scorsi** [comment]
Thanks for your comment, how could I achieve this ? By recreating another slice of channels in receive-only mode ? Could go infer the type here to avoid that ?

**Comment by ajr360** [comment]
@scorsi I found this issue as I have exactly the same problem. The only way around it that I found was to create a new slice and copy the elements from the `[]chan int` to the `[]<-chan int` one at a time, in a loop.  Of course, this is ugly, slow (for a slice of millions of chans) and add a lot of unnecessary strain on the GC.  I suggest you make a language change proposal.
