### ISSUE TITLE
cmd/go2go: translator deletes generic objects without type parameters

### ISSUE THREAD

**Issue by tdakkota** [golang/go#40015]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +85ed317eb2 Thu Jul 2 00:33:43 2020 +0000 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
n/a

### What operating system and processor architecture are you using (`go env`)?
- windows/amd64
- Go2go playground

### What did you do?
https://go2goplay.golang.org/p/ABjdAJsVfgj

### What did you expect to see?
Successful compilation or error like `generic function should have at least one type parameter`

### What did you see instead?
```
./prog.go2:16: undefined: Print
```
It's go compiler's output, not go2go.

**Comment by tdakkota** [comment]
For other objects does not work too.
```go
package main

type S(type) struct{}

func main() {
	var _ S // compiler error: ./prog.go2:6: undefined: S
	var _ S() // go2go error: S is not a generic type
	var _ S(int) // go2go error: S is not a generic type
}
```

https://go2goplay.golang.org/p/_ebbO1tDKjW

**Comment by ianlancetaylor** [comment]
The initial test case is fixed on the dev.go2go branch.

I think the test case in https://github.com/golang/go/issues/40015#issuecomment-653312807 is acting correctly in reporting `S is not a generic type`.  If there are no type parameters, there should be no type arguments.  We could also change that around.  It doesn't seem very important at present.
