### ISSUE TITLE
x/pkgsite: add postgres.GetLicenses function to return licenses for a given path

### ISSUE THREAD

**Issue by julieqiu** [golang/go#40027]
As part of the new data model migration (#39629), we will have a single function get licenses for a given path (regardless of whether that path is a package, module, or directory). 

This function will replace the existing [LegacyGetPackageLicenses](https://github.com/golang/pkgsite/blob/df627db60a835a59120b45fe7af59779840aa522/internal/postgres/licenses.go#L48) and [LegacyGetModuleLicenses](https://github.com/golang/pkgsite/blob/df627db60a835a59120b45fe7af59779840aa522/internal/postgres/licenses.go#L23).

The function signature will be:
```
GetLicenses(ctx context.Context, fullpath, modulePath, resolvedVersion string)([]*licenses.License, error)
```
The function will execute the query below:

```
SELECT
    l.types,
    l.file_path,
    l.contents,
    l.coverage
FROM
    licenses l
INNER JOIN
    paths p
ON
    p.module_id=l.module_id
INNER JOIN
    modules m
ON
    p.module_id=m.id
WHERE
    p.path = $1
    AND m.module_path = $2
    AND m.version = $3;
```

Only licenses relevant to the path should be returned. A license applies to the path if the license is in the path directory, or any of its parent directories.

**Comment by amarjeetanandsingh** [comment]
Hi @julieqiu
If allowed, may I pick this up?

**Comment by julieqiu** [comment]
Please do! :)

**Comment by amarjeetanandsingh** [comment]
Hi @julieqiu 
Thanks for allowing me to work on this issue ))

Just to confirm if I understood it correctly, we need to implement -
`func (db *DB) GetLicenses(ctx context.Context, fullPath, modulePath, resolvedVersion string) (_ []*licenses.License, err error) {`
in `internal/postgres/postgres.go` file to fetch the list of licenses at the given `fullPath & modulePath`.

I am correct? 

If yes, then `internal.DataSource` interface will have `GetLicenses( )` as contract. 
As a result, `DataSource` in `internal/proxydatasource` will also need an implementation of `GetLicenses()`.

**Comment by julieqiu** [comment]
Thank you for contributing! :)

That is correct. I would add the function to [internal/postgres/licenses.go](https://github.com/golang/pkgsite/blob/master/internal/postgres/licenses.go) though, as opposed to `internal/postgres/postgres.go`.

**Comment by amarjeetanandsingh** [comment]
ohh yeah...
Thanks @julieqiu for correcting me.
Will try to implement tomorrow.

**Comment by amarjeetanandsingh** [comment]
@julieqiu 
Is there a way to load data data in my local docker postgres? Any doc you can point to?

**Comment by julieqiu** [comment]
Yup! Check out [doc/worker.md#populating-data-locally-using-the-worker](https://github.com/golang/pkgsite/blob/master/doc/worker.md#populating-data-locally-using-the-worker) for instructions.

By the way, if you have other questions, feel free to reach out in the #pkgsite channel on [Gophers Slack](https://invite.slack.golangbridge.org)!
