### ISSUE TITLE
cmd/go2go: parse error on multiple type parameters inside a type parameter

### ISSUE THREAD

**Issue by beoran** [golang/go#40021]
On the playground this fails to compile in ThisDoesNot with prog.go2:20:7: expected ')', found ',' (and 1 more errors):

https://go2goplay.golang.org/p/fDM1HQlOGUF

```go
package main

import (
	"fmt"
)

type Any = interface{}
type Super(type S) interface {
   type S
} 

type N(type S Any, X Super(S)) Any
type L(type X) Any

type ThisWorks(type S,X) interface {
   N(S,X)
} 

type ThisDoesNot(type S Any, X Super(S)) interface {
	L(N(S,X))
}

func main() {
	fmt.Prinf("OK")
}
```

I would expect it to compile though. Is this so?

**Comment by ianlancetaylor** [comment]
In this code

```Go
type ThisDoesNot(type S Any, X Super(S)) interface {
	L(N(S,X))
}
```

`L(N(S, X))` looks like a method definition.  You need to write this as

```Go
type ThisDoesNot(type S Any, X Super(S)) interface {
	(L(N(S,X)))
}
```

Yes, this is awkward.  This is mentioned at https://go.googlesource.com/proposal/+/refs/heads/master/design/go2draft-type-parameters.md#embedding-an-instantiated-interface-type .

**Comment by beoran** [comment]
Ah, I see. This is indeed an akward syntax. Please consider coming up with something better. Also, a better parse error would be useful here.
