### ISSUE TITLE
x/pkgsite: create GetModuleInfo function

### ISSUE THREAD

**Issue by julieqiu** [golang/go#40032]
As part of the new data model migration (#39629), we will need a function return the [ModuleInfo](https://github.com/golang/pkgsite/blob/20e1c1312d3530a9c6c35572247f276bdde5f551/internal/discovery.go#L34) for a given module_path and version. 

This function will eventually replace the existing [LegacyGetModuleInfo](https://github.com/golang/pkgsite/blob/df627db60a835a59120b45fe7af59779840aa522/internal/postgres/details.go#L283) function.

The function signature will be:

```
GetModuleInfo(ctx context.Context, modulePath string, resolvedVersion string) (_ *internal.ModuleInfo, err error)
```

The function will execute the query below:

```
SELECT
    module_path,
    version,
    commit_time,
    version_type,
    source_info,
    redistributable,
    has_go_mod
FROM
    modules
WHERE
    module_path=$1
    AND version=$2;
```

Unlike [LegacyGetModuleInfo](https://github.com/golang/pkgsite/blob/df627db60a835a59120b45fe7af59779840aa522/internal/postgres/details.go#L283), it is expected that the version passed into the function will always be a semantic version (i.e. GetModuleInfo will NOT need to handle the case where `resolvedVersion == internal.LatestVersion`).

**Comment by namaggarwal** [comment]
Hello @julieqiu, Can I pick this up ?

**Comment by julieqiu** [comment]
Yes, please do!
