### ISSUE TITLE
x/tools/gopls: 

### ISSUE THREAD

**Issue by PatrickZhao12** [golang/go#40040]
#### What did you see instead?
gopls doesn't work

#### Build info

```
golang.org/x/tools/gopls 0.4.1
    golang.org/x/tools/gopls@v0.4.1 h1:0e3BPxGV4B3cd0zdMuccwW72SgmHp92lAjOyxX/ScAw=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.2.0 h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
    golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=
    golang.org/x/tools@v0.0.0-20200513154647-78b527d18275 h1:e7nYe9s94RHunFJ7b+mmPxiQMOKMVSqYASToWb1EcHs=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=
```

#### Go info

```
go version go1.14.2 darwin/amd64

```

**Comment by kockok** [comment]
I got `go generate exited with an error, check gopls logs` error, however, no link was provided.
So, I still don't have a clue as to where the log is located and just see the logs.

**Comment by thepudds** [comment]
Hi @PatrickZhao12 and @kockok, What editors are you using, and can you say a bit more about the symptoms of what you are observing?

Also, the logs are very useful for triaging what might be going wrong.  The gopls troubleshooting guide has some very useful instructions for how to gather data for reporting a problem, including how to gather logs:

https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md

Also, @kockok, are you seeing the exact same problem as @PatrickZhao12? If not, it probably makes sense to open a separate new issue for your specific case.

**Comment by stamblerre** [comment]
Closing this issue as the original report is empty. @kockok: Please do file a new issue if you're interested in investigating this further.
