### ISSUE TITLE
verb %S in fmt.printf

### ISSUE THREAD

**Issue by dallion** [golang/go#40046]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/?/Library/Caches/go-build"
GOENV="/Users/?/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/?/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kr/kf10p6js72q6stpcp409bf840000gn/T/go-build286212471=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

unknow verb `%S` in fmt.printf

[https://play.golang.org/p/wVQDRLCpH3I](url)

### What did you expect to see?

some error like Printf format %S has unknown verb S

### What did you see instead?

value: %!S(string=Malibu Point 10880, 90265)

**Comment by ianlancetaylor** [comment]
See the section on "Format errors at https://golang.org/pkg/fmt.
