### ISSUE TITLE
cmd/go2go: embedded generic pointer field cannot be referred to by name

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#40059]
commit 34f76220c32bfe7766ca074d5ae69d6f716b9b2c

The [following program](https://go2goplay.golang.org/p/33kgMJoKBbk) fails, but it should be OK by my reading of the draft proposal. It works when the embedded field isn't a pointer.

```
package main

func main() {
	var s S(int)
	_ = s.E
}

type S(type T) struct {
	*E(T)
}

type E(type T) struct {}
```

It prints this error:
```
./prog.go2:5: s.E undefined (type instantiate୦୦S୦int has no field or method E)
```

**Comment by ianlancetaylor** [comment]
Thanks.  This is now fixed on the dev.go2go branch (fix was https://golang.org/cl/241125, which I thought would fix a different case, but turned out to fix this as well).
