### ISSUE TITLE
all: standard library packages should not use upper-case paths

### ISSUE THREAD

**Issue by rsc** [golang/go#40065]
crypto/x509/internal/macOS was added on May 7.
It is the first standard library package with upper-case letters.
They should be lowercased, following the standard all-lower-case convention.
(For example it is syscall/internal/windows not syscall/internal/Windows.)

I believe this is the only one, but if there are others, they should be fixed too.

**Comment by crawshaw** [comment]
Two other directories but they are not actual packages:

```
find . -type d -name "*[A-Z]*"
./cmd/link/testdata/testIndexMismatch
./cmd/link/testdata/testBuildFortvOS
./crypto/x509/internal/macOS
```
