### ISSUE TITLE
cmd/go2go: generic function type assignment fails to type check correctly

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#40060]
commit 34f76220c32bfe7766ca074d5ae69d6f716b9b2c

The [following program](https://go2goplay.golang.org/p/WE5R7I4GChS) seems like it should compile OK, but it does not:

```
package main

func main() {
}

type S1(type T) struct {
	x S2(T)
}

type S2(type T) struct {
	y sfunc(T)
}

type sfunc(type T) func(*S1(T))

func (*S1(T)) a() {}

func (i *S1(T)) b(f sfunc(T)) {
	i.x.y = f
}
```

It produces the error:

```
prog.go2:19:10: cannot use f (variable of type sfunc(T)) as sfunc(T) value in assignment
```

**Comment by ianlancetaylor** [comment]
This looks like a bug in the type checker.

**Comment by griesemer** [comment]
One of the functions is not properly instantiated.

**Comment by rogpeppe** [comment]
Note that it works OK if the apparently unrelated method `a` is removed, which is odd.

**Comment by rogpeppe** [comment]
This now works correctly on tip.
