### ISSUE TITLE
cmd/gc: seems expand stack uneccessary

### ISSUE THREAD

**Issue by zylthinking** [golang/go#40069]
### What version of Go are you using (`go version`)?
<pre>
1.14
</pre>

### Does this issue reproduce with the latest release?
Yes

### The problem:
run go tool compile -S a.go
the function
```
func a() uintptr {
    var x [1024]uintptr
    for i := 0; i < len(x); i++ {
        x[i] = uintptr(time.Now().Unix())
    }   
    return x[0]
}
```
output as:
```
"".a STEXT size=239 args=0x8 locals=0x2028
	0x0000 00000 (a.go:6)	TEXT	"".a(SB), ABIInternal, $8232-8
	0x0000 00000 (a.go:6)	MOVQ	(TLS), CX
	0x0009 00009 (a.go:6)	MOVQ	16(CX), SI
	0x000d 00013 (a.go:6)	PCDATA	$0, $-2
	0x000d 00013 (a.go:6)	CMPQ	SI, $-1314
	0x0014 00020 (a.go:6)	JEQ	229
	0x001a 00026 (a.go:6)	LEAQ	896(SP), AX
	0x0022 00034 (a.go:6)	SUBQ	SI, AX
	0x0025 00037 (a.go:6)	CMPQ	AX, $9000
	0x002b 00043 (a.go:6)	JLS	229
	0x0031 00049 (a.go:6)	PCDATA	$0, $-1
	0x0031 00049 (a.go:6)	SUBQ	$8232, SP
	0x0038 00056 (a.go:6)	MOVQ	BP, 8224(SP)
	0x0040 00064 (a.go:6)	LEAQ	8224(SP), BP
```
I don't know why 768 more bytes is needed in the following line:
	0x0025 00037 (a.go:6)	CMPQ	AX, $9000

Should't it be CMPQ	AX, $8232?
In some cases when there less than 9000 bytes but more than 8232,  stack expand is triggered unecessarily

**Comment by martisch** [comment]
I dont think reserving 8232 bytes for the stack will suffice because later the function`a` calls  `time.Now(SB) ` which itself will need stack space ontop of the used 8232. `time.Now ` then calls other functions e.g. time.local ... . And this continues recursively. Reserving just 8232 will trigger another stack growth in the other leave functions.

**Comment by martisch** [comment]
Feel free to reopen the issue if you think there is a bug here and the above explanation why this is more than 8232 is wrong.
