### ISSUE TITLE
x/pkgsite: duplicate documentation indexes for some packages

### ISSUE THREAD

**Issue by findleyr** [golang/go#40078]
Today, visiting some documentation pages (say https://pkg.go.dev/go/types) displays two documentation indexes: one above the `Overview` heading, and one below.

![image](https://user-images.githubusercontent.com/57144380/86635561-3b139380-bfa1-11ea-8e02-30d5027e5b3a.png)

**Comment by findleyr** [comment]
CC @andybons @jba @julieqiu

**Comment by dmitshur** [comment]
Re-opening this until the fix is completely deployed.

**Comment by jba** [comment]
Deployed.
