### ISSUE TITLE
cmd/go: include GOMODCACHE in documented list of environment variables

### ISSUE THREAD

**Issue by dmitshur** [golang/go#40089]
Go 1.15 adds the `GOMODCACHE` environment variable (#34527). It's mentioned in the release notes ([CL 230537](https://golang.org/cl/230537)). Should it also be included in the list at https://tip.golang.org/cmd/go/#hdr-Environment_variables?

/cc @jayconrod @matloob @bcmills

**Comment by tpaschalis** [comment]
If it's included, would it go under *General-purpose environment variables*? Could I suggest something like
```
GOMODCACHE
	The directory where the go command will cache module downloads. 
	It defaults to GOPATH/pkg/mod.
```

**Comment by dmitshur** [comment]
There's a CL out to fix this (that just needs review), I think we don't want to release Go 1.15 without this, so marking release-blocker so this isn't missed by accident.
