### ISSUE TITLE
x/pkgsite: add function to set up test queue

### ISSUE THREAD

**Issue by julieqiu** [golang/go#40098]
There are a couple of places in the code where we want to set up a queue for testing:

- `internal/frontend/server_test.go`: https://github.com/golang/pkgsite/blob/master/internal/frontend/server_test.go#L992-L999
- `internal/testing/integration/frontend_test.go`: TODO - add link

It would be useful to have a single setupQueue function for use in testing.

**Comment by tayoogunbiyi** [comment]
I'd like to have a go at this.

**Comment by tayoogunbiyi** [comment]
> * `internal/frontend/server_test.go`: https://github.com/golang/pkgsite/blob/master/internal/frontend/server_test.go#L992-L999
> * `internal/testing/integration/frontend_test.go`: TODO - add link
> 
> It would be useful to have a single setupQueue function for use in testing.


The link for where the code is duplicated within `internal/testing/integration/frontend_test.go` is https://github.com/golang/pkgsite/blob/master/internal/testing/integration/frontend_test.go#L205-L211

**Comment by amarjeetanandsingh** [comment]
@julieqiu 
May I give it a try?

**Comment by julieqiu** [comment]
@amarjeetanandsingh please do!

**Comment by BLasan** [comment]
@julieqiu Can I work on this?

**Comment by ya5u** [comment]
@julieqiu queue.InMemory seems to be working effectively as a test helper and to be invoked by no other than test code. Isn't it necessary to create another function?

**Comment by julieqiu** [comment]
Nope - this issue seems to be outdated. Thanks for taking a look!
