### ISSUE TITLE
x/pkgsite: add function to set up queue

### ISSUE THREAD

**Issue by julieqiu** [golang/go#40097]
We use the same `newQueue` logic in `cmd/frontend` and `cmd/worker`:

- `cmd/worker`: https://github.com/golang/pkgsite/blob/41e1cccbb27a6960bda31600e32960cf99d31b51/cmd/worker/main.go#L146
- `cmd/frontend`: https://github.com/golang/pkgsite/blob/41e1cccbb27a6960bda31600e32960cf99d31b51/cmd/frontend/main.go#L161

It would be nice to have a single function to reduce duplication.

**Comment by akolar** [comment]
Mind if I take a stab at this?

**Comment by julieqiu** [comment]
Please do!
