### ISSUE TITLE
x/tools/internal/lsp/regtest: regression tests for on-disk file changes failing on darwin builders

### ISSUE THREAD

**Issue by dmitshur** [golang/go#40099]
The test added in [CL 238917](https://golang.org/cl/238917) are not passing on darwin builders:

![image](https://user-images.githubusercontent.com/1924134/86809786-3ce56180-c04a-11ea-8411-e103074f5d17.png)

_(From https://build.golang.org/?repo=golang.org%2fx%2ftools.)_

The errors mention "context deadline exceeded" and the tests are running for over 8 minutes:

```
[...]
            runner.go:210: Shutdown: context deadline exceeded
FAIL
FAIL	golang.org/x/tools/internal/lsp/regtest	530.597s
```

/cc @stamblerre

**Comment by stamblerre** [comment]
Looks like my CL still hasn't fixed the issue. I believe that this is the same builder that is mentioned in https://github.com/golang/go/issues/39802, and I'm not sure how to debug this further given that it is specific to this builder. I suppose I can try using Gomote, but before I do that, @dmitshur, are there any known issues with that builder?

**Comment by dmitshur** [comment]
> are there any known issues with that builder?

I can't think of anything relevant off the top of my head, and the "notes" field at https://farmer.golang.org/builders is empty. In general, the darwin builders are known to be more troublesome compared to some other builders, and "darwin-amd64-10_12" is the oldest darwin builder. (The older a builder, the more likely it is to have problems that might be fixed in newer versions.) If this turns out to be a builder problem, we should try to fix it or document it. /cc @cagedmantis @toothrot

Debugging via a Gomote should be a good way to try learn more.

**Comment by andybons** [comment]
Bumping this up as other failures may be hidden by this if they’re not fixed.

We should investigate further using gomote and if no underlying cause can be found soon, we should at least disable the test with a bug to track re-enabling it.

**Comment by stamblerre** [comment]
Yep, sorry about the delay, I plan to take a look at this soon. We shouldn't disable the tests though, because this is clearly a problem specific to one builder.

**Comment by findleyr** [comment]
I believe this has long since been resolved.
