### ISSUE TITLE
x/pkgsite: add tests for frontend.LatestVersion

### ISSUE THREAD

**Issue by julieqiu** [golang/go#40107]
Add tests for [frontend.latestMinorVersion](https://github.com/golang/pkgsite/blob/d69d7c2318ee395d3cea2330d3f00c52955429dc/internal/frontend/latest_version.go#L50), which is used to return the latest version of a path.

**Comment by vikramcse** [comment]
@julieqiu I would like to work on this issue. can I pick this?

**Comment by julieqiu** [comment]
Please do!

**Comment by vikramcse** [comment]
@julieqiu I have gone through `TestServer` test from `server_test.go` file. I am thinking to write the test cases for `latestVersion` in similar way.

```
1. testCases := []serverTestCase{
		{
			name:           "module packages tab latest version",
			urlPath:        fmt.Sprintf("/mod/%s?tab=packages", sample.ModulePath),
			wantStatusCode: http.StatusOK,
			// Fall back to the latest version.
			want: in("",
				in("div.DetailsHeader-version", text("v1.0.0"))),
		},
	}
```

2. insertTestModules()	
3. create a server i.e s = NewServer()
4. create a middeware `middleware.LatestVersion(s.LatestVersion)` as s.LatestVersion is intended to be a parameter of `middleware.LatestVersion`
5. call latestVersion method i.e s.latestVersion(context.Background(), packagePath, modulePath, pageType)
```
6. for _, tc := range testCases {
		a. create a httptest.NewRecorder()
		b. create a new httptest request to the urlPath
		c. parse the res.Body
		d. here in res.Body we can check compare the `requested` and `want` version
	}
```

Before moving forward with this solution, can you please let me know that is this the right approach?

**Comment by kirandasika98** [comment]
Hi @julieqiu, Can I pickup this issue? If, @vikramcse is okay with it?
