### ISSUE TITLE
x/build: Gerrit new patchset comments break SlowBots

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#40106]
The Gerrit UI switched from change messages to patchset comments. This broke SlowBots because they look for the `TRY=` line only in change messages.

https://go-review.googlesource.com/c/go/+/241274/2#message-0074141e27123306d3396d09a5d3215ce2413706

**Comment by dmitshur** [comment]
I've looked into this and know what needs to be done to restore service:

- update maintapi to extract TRY= comments from inline comments (where they now end up)
  - [likely] add [List Change Comments](https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#list-change-comments) to x/build's gerrit API client package, use it to fetch inline comments
  - modify logic in tryWorkItem
- redeploy maintnerd

Working on a fix CL.
