### ISSUE TITLE
x/tools/gopls: improve daemon logging behavior

### ISSUE THREAD

**Issue by findleyr** [golang/go#40105]
Right now, when gopls is in daemon mode, we by default start the daemon with `-logfile=auto`.  Note that the daemon does not log RPC traces -- only direct calls to log.Printf, of which there are few.  RPC trace logging is left to the sidecar, so that RPCs from multiple sessions are not intermingled.

This means that the gopls daemon creates a mostly (or entirely) empty logfile, which causes clutter and can lead to confusion when looking for actual RPC logs.  Arguably, we should instead:
 - disable daemon logging by default.  It is configurable via `-remote.logfile`, so can be enabled if necessary
 - log a message at the start of the daemon logs to say something to the effect of "I am a daemon"
 - log from the daemon when sessions connect and disconnect

**Comment by findleyr** [comment]
It would be good to also differentiate the daemon logfile by name (e.g. `/tmp/gopls-daemon-<pid>.log`).

CC @bhcleek -- I noticed this from a user report using vim-go, in https://github.com/golang/vscode-go/issues/299.  It is confusing that the current default vim-go settings results in an empty logfile, most of the time.  This is my bad, for making the default logging behavior of the daemon inconsistent with the default logging behavior of the sidecar.  I'll fix this soon, but wanted you to be aware: it would be good to get the fix in before the next vim-go release.  Thanks for using daemon mode!

**Comment by bhcleek** [comment]
@findleyr are you asking for vim-go to use `--remote.logfile=$TMPDIR/gopls-daemon-$PID.log` in its default configuration?

**Comment by findleyr** [comment]
@bhcleek sorry for being unclear. No change needed in vim-go: I'll make this the default behavior for gopls.

**Comment by bhcleek** [comment]
Thanks for clarifying!
