### ISSUE TITLE
net/http

### ISSUE THREAD

**Issue by juzidong** [golang/go#40120]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.36

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
When I got a 302 Redirect with Location containing  a '\t', the http.client went wrong. 
func (c *Client) do(req *Request) (retres *Response, reterr error) {
...
			u, err := req.URL.Parse(loc)
			if err != nil {
				resp.closeBody()
				return nil, uerr(fmt.Errorf("failed to parse Location header %q: %v", loc, err))
			}
...
}

### What did you expect to see?
I'd like to see the Location should replace all '\t' with "" before Parse().

**Comment by seankhliao** [comment]
that does not appear to be a valid go version

can you show an example of a Location you are getting?
