### ISSUE TITLE
Unable to build application for linux on windows machine

### ISSUE THREAD

**Issue by rakeshrvce** [golang/go#40129]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 windows/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\krr\AppData\Local\go-build
set GOENV=C:\Users\krr\AppData\Roaming\go\env
set GOEXE=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=linux
set GOPATH=C:\Users\krr\go;
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\RakeshKR\AG\GO\git_code\go\airgroup\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=C:\Users\krr\AppData\Local\Temp\go-build015935298=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
On windows mingw-w64 is installed for gcc and CGO_ENABLED is set to 1 which is needed for confluent-kafka-go library.
I am trying to build the application(which internally uses this library) for ubuntu on windows machine but compilation is failing.
compilation command: go build -o packet-handler myapp/main.go

### What did you expect to see?
Application compiling successfully

### What did you see instead?
$ go build -o packet-handler myapp/main.go
runtime/cgo
gcc_linux_amd64.c: In function '_cgo_sys_thread_start':
gcc_linux_amd64.c:61:2: error: unknown type name 'sigset_t'; did you mean '_sigset_t'?
sigset_t ign, oset;
^~~~~~~~
_sigset_t
gcc_linux_amd64.c:66:2: error: implicit declaration of function 'sigfillset' [-Werror=implicit-function-declaration]
sigfillset(&ign);
^~~~~~~~~~
gcc_linux_amd64.c:61:16: error: unused variable 'oset' [-Werror=unused-variable]
sigset_t ign, oset;
^~~~
cc1.exe: all warnings being treated as errors

**Comment by cherrymui** [comment]
Is your C compiler targeting Linux? You need a C cross compiler that targets Linux, and set CC environment variable to its path.

**Comment by rakeshrvce** [comment]
If you look at my go env, cc is set to gcc and I am using following gcc verison:
$ gcc --version
gcc.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by ianlancetaylor** [comment]
That C compiler targets mingw, not GNU/Linux.

In order to build a GNU/Linux program on WIndows, with `CGO_ENABLED=1`, you need to have a cross-compiler that targets GNU/Linux.

Closing because while the situation is unfortunate, there isn't really anything we can do in the Go toolchain to fix this.  To build C code that runs on GNU/Linux you must have a C compiler that produces GNU/Linux code.

**Comment by rakeshrvce** [comment]
Is there any way I can make C compiler targets to GNU on windows?

**Comment by ianlancetaylor** [comment]
Sure, but we are the wrong people to ask about that.  A web search for "cross compile from windows to linux" pulls up a number of promising pages.

**Comment by alexbrainman** [comment]
> Is there any way I can make C compiler targets to GNU on windows?

I do not know. Maybe try

http://musl.cc/

Perhaps, @zv-io, can help.

> but we are the wrong people to ask about that. A web search for "cross compile from windows to linux" pulls up a number of promising pages.

I am not sure we should be the wrong people. If we support Mingw on Windows, we should provide link to download the tools. gcc is never installed on Windows, and Windows users rarely know what it is and how to install it. See, for example, https://github.com/golang/go/issues/35006#issuecomment-568191018

Alex

**Comment by ianlancetaylor** [comment]
@alexbrainman I think the use of the word "GNU" was confusing here.  This issue here isn't getting a GNU compiler that runs on Windows and generates programs that run on Windows.  It's about getting a compiler that runs on Windows and generates programs that run on GNU/Linux.

**Comment by alexbrainman** [comment]
> It's about getting a compiler that runs on Windows and generates programs that run on GNU/Linux.

I understand what you meant, Ian. I suspect there is a version of gcc that runs on Windows and generates Linux binaries. It might be listed on http://musl.cc/

Alex

**Comment by ianlancetaylor** [comment]
Ah, OK, sorry.

**Comment by zv-io** [comment]
@ianlancetaylor @alexbrainman The toolchains at https://musl.cc/ are capable of at least:

* Windows --> Linux (https://win.musl.cc/) *not updated as frequently; plan to do that today.
* Mac --> Linux (https://mac.musl.cc/)
* Linux --> Windows (https://musl.cc/i686-w64-mingw32-cross.tgz, https://musl.cc/x86_64-w64-mingw32-cross.tgz)
* Windows --> Windows (https://musl.cc/i686-w64-mingw32-native.zip, https://musl.cc/x86_64-w64-mingw32-native.zip)

If others are needed, just let me know.

**Comment by rakeshrvce** [comment]
I need it for windows 10 machine to ubuntu 18(i.e. windows to linux). Should i pick this one x86_64-linux-musl-cross.zip ?
What is the naming format followed to name the these file on https://win.musl.cc/ ? How to read these file?

**Comment by zv-io** [comment]
> I need it for windows 10 machine to ubuntu 18(i.e. windows to linux). Should i pick this one x86_64-linux-musl-cross.zip ?

Yes, that is correct.

> What is the naming format followed to name the these file on https://win.musl.cc/ ? How to read these file?

Anything that is a `.zip` file will run on Windows, so the name is the *target* platform. For example, `x86_64-linux-musl` produces binaries built for `x86_64` Linux.

I do not know if this will work for your intended purpose (it may require fiddling with environment variables and build flags).

**Comment by alexbrainman** [comment]
> @ianlancetaylor @alexbrainman The toolchains at https://musl.cc/ are capable of at least:

Thanks for your help, @zv-io.

@ianlancetaylor can we refer users to this website for pre-built Mingw binaries? I think this will be helpful to Windows cgo users.

Alex
