### ISSUE TITLE
x/mobile/cmd/gomobile: test failed w/ "Apple Development" certificate

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#40134]
Now building an iOS app requires "iPhone Developer" certification.

https://github.com/golang/mobile/blob/33b80540585f2b31e503da24d6b2a02de3c53ff5/cmd/gomobile/build_iosapp.go#L157-L160

I'm not confident, but should "Apple Development" certification also work?

CC @hyangah @eliasnaur

**Comment by eliasnaur** [comment]
FWIW, Gio doesn't hardcode the certificate name; rather, it finds the certificate matching the app ID:

https://git.sr.ht/~eliasnaur/gio/tree/master/cmd/gogio/iosbuild.go#L80

**Comment by dmitshur** [comment]
I've run into this too when investigating iOS support recently, and temporarily changed to "Apple Development" locally. I haven't followed up on that yet, but just wanted to add a data point.

**Comment by hajimehoshi** [comment]
@dmitshur Thanks. Do you think checking "Apple Development" as fallback would make sense?

**Comment by hajimehoshi** [comment]
ping @dmitshur

**Comment by changkun** [comment]
This should also be fixed in CL 346151. We can close it directly.

(Sorry again for not referring to it directly in the CL.)

cc @hajimehoshi

**Comment by hajimehoshi** [comment]
Thanks!
