### ISSUE TITLE
proposal: (dev.go2go) remove the .go2 extension

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#40137]
I propose to merge the `go2go` tool with `cmd/go`, removing the `.go2` extension and start porting some parts of the stdlib to generics.

This would allow easier testing and expose the compiler to more test cases mixing generic and non-generic code.

**Comment by ianlancetaylor** [comment]
The go2go tool is an experimental translation tool intended to make it easier for people to see how the generics design draft works in practice.  The tool was written to be thrown away.  We won't be merging it into cmd/go.  Instead, we will use it to move toward a real language proposal, which will then have a real implementation, with code review and everything.
