### ISSUE TITLE
x/tools/cmd/goimports: goimports removes valid import path

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [golang/go#40148]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.3 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gmikhalkin/.cache/go-build"
GOENV="/home/gmikhalkin/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/gmikhalkin/.gvm/pkgsets/go1.14.3/global"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/gmikhalkin/.gvm/gos/go1.14.3"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/gmikhalkin/.gvm/gos/go1.14.3/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build597149176=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

After i run `goimports -w` on file https://github.com/GrigoriyMikhalkin/sqlboiler-paginate/blob/master/examples/simple_net_example.go it removes valid import `"github.com/grigoriymikhalkin/sqlboiler-paginate/v4"`. It's important to note that package name(`paginate`) differs from module name.

**Comment by heschik** [comment]
This is a small bug but mostly working as intended. I'm assuming you were working outside of GOPATH. The examples directory is not a module, so goimports can't find its dependencies outside of GOPATH, and therefore can't determine that the package's name is `paginate`. If you run it inside of GOPATH, or make the examples directory a module with valid dependencies, goimports will work fully.

Ideally the dependency would be kept if its name is unknown but goimports is already complicated enough and people generally can compile the code they're working on. Once you run it once the import will be given an explicit name and goimports will understand it's in use.

**Comment by csterritt** [comment]
For anyone trying to solve this later, the fix is simple.  Change an import like:

~~~ go
import "gopkg.in/olahol/melody.v1"
~~~

That `goimports` will remove (because the package name is `melody`) with:

~~~ go
import melody "gopkg.in/olahol/melody.v1"
~~~
