### ISSUE TITLE
x/pkgsite: hide banner when scrolling down

### ISSUE THREAD

**Issue by knuesel** [golang/go#40144]
The banner on pkg.go.dev offers package search and general navigation links: Why Go, Getting Started, Discover Packages, About.

These are generally not useful when reading the documentation of a particular package, and the banner takes a lot of space on the  screen. Why not let it go out of view when scrolling down on the page?

**Comment by ALTree** [comment]
Thanks for the report. This was reported as #37110, so I'm closing here in favour of the older thread.
