### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by jesseorr** [golang/go#40154]
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/google/uuid?tab=doc
 
 
### What is your user agent?
 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

 
 
 
### What did you do?
 I loaded the page, took no actions.

 
 
 
### What did you expect to see?
 Golang documentation, explaining UUID functions within Go.
 
 
### What did you see instead?
Black Lives Matter

### Why its broken?
I don't care about BLM, or WLM, or any of this political non-sense. I am here to write code. You are here to support code writers, not give political statements.

**Comment by ALTree** [comment]
> You are here to support code writers, not give political statements.

Unfortunately the people that control the go.dev website think otherwise. This is a dup of #39850, see the comments there for a link to a mailing list discussion about this. Closing here.
