### ISSUE TITLE
gccgo: value comparison with interface is broken

### ISSUE THREAD

**Issue by zhsj** [golang/go#40152]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 gccgo (Debian 20200616-1) 11.0.0 20200616 (experimental) [master revision beaf12b49ae:aed76232726:b70eeb248efe2b3e9bdb5e26b490e3d8aa07022d] linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/zhsj/.cache/go-build"
GOENV="/home/zhsj/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/zhsj/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/gcc/x86_64-linux-gnu/10"
GCCGO="/usr/lib/gcc-snapshot/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build551180179=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
</pre></details>

### What did you do?

``` go
package main

import (
        "fmt"
)

func t(args ...interface{}) bool {
        x := true
        return x == args[0]
}

func main() {
        fmt.Println(t("x" == "x" && "y" == "y"))
}
```

### What did you expect to see?

same as gc, print "true"

### What did you see instead?

print "false"

**Comment by ianlancetaylor** [comment]
Thanks for reporting this bug.  It is now fixed on GCC trunk.
