### ISSUE TITLE
cmd/go: unable to build with a v4 module

### ISSUE THREAD

**Issue by pierrec** [golang/go#40156]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 windows/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\XXX\AppData\Local\go-build
set GOENV=C:\Users\XXX\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\XXX\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\XXX\go\src\github.com\pierrec\tmp\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\XXX\AppData\Local\Temp\go-build610762850=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

See issue https://github.com/pierrec/lz4/issues/77

### What did you expect to see?

A successful build.

### What did you see instead?

go: finding module for package github.com/pierrec/lz4/internal/lz4errors
go: finding module for package github.com/pierrec/lz4/internal/lz4block
go: finding module for package github.com/pierrec/lz4/internal/lz4stream
..\..\..\..\pkg\mod\github.com\pierrec\lz4\v4@v4.0.0\lz4.go:14:2: module github.com/pierrec/lz4@latest found (v2.5.2+incompatible), but does not contain package github.com/pierrec/lz4/internal/lz4block
..\..\..\..\pkg\mod\github.com\pierrec\lz4\v4@v4.0.0\lz4.go:15:2: module github.com/pierrec/lz4@latest found (v2.5.2+incompatible), but does not contain package github.com/pierrec/lz4/internal/lz4errors
..\..\..\..\pkg\mod\github.com\pierrec\lz4\v4@v4.0.0\reader.go:7:2: module github.com/pierrec/lz4@latest found (v2.5.2+incompatible), but does not contain package github.com/pierrec/lz4/internal/lz4stream

**Comment by jayconrod** [comment]
This doesn't look like a bug with the Go command itself, so I'll close this issue.

I commented on pierrec/lz4#77 though. Happy to answer further questions there.
