### ISSUE TITLE
x/tools: installation blocked by virus scanner

### ISSUE THREAD

**Issue by duckwheel** [golang/go#40164]
### What version of Go are you using (`go version`)?

<pre>
go version
go version go1.14 darwin/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
compiler@nexus6 ~ % go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/compiler/Library/Caches/go-build"
GOENV="/Users/compiler/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/compiler/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z0/_qxnvkt90kn73_d2qt42jnlc0000gn/T/go-build033977144=/tmp/go-build -gno-record-gcc-switches -fno-common"
compiler@nexus6 ~ %
</pre></details>

### What did you do?

go get -u -v golang.org/x/tools/...

### What did you expect to see?
clean install of go support tools

### What did you see instead?
et "golang.org/x/tools/internal/lsp/regtest": verifying non-authoritative meta tag
get "golang.org/x/tools/internal/stack": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at //golang.org/x/tools/internal/stack?go-get=1
get "golang.org/x/tools/internal/stack": verifying non-authoritative meta tag
get "golang.org/x/tools/internal/stack/gostacks": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at //golang.org/x/tools/internal/stack/gostacks?go-get=1
get "golang.org/x/tools/internal/stack/gostacks": verifying non-authoritative meta tag
get "golang.org/x/tools/internal/stack/stacktest": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at //golang.org/x/tools/internal/stack/stacktest?go-get=1
get "golang.org/x/tools/internal/stack/stacktest": verifying non-authoritative meta tag
open /var/folders/z0/_qxnvkt90kn73_d2qt42jnlc0000gn/T/go-build614940412/b126/exe/a.out: permission denied
I'm currently running a deep virus scan on my Mac but this is the first time i have come across this updating tools
not sure if its a false positive?

![Screenshot 2020-07-11 at 14 59 14](https://user-images.githubusercontent.com/68154882/87225754-1d6e7180-c387-11ea-9269-20be6be943dd.png)

**Comment by agnivade** [comment]
Yes, this is a false positive. Please see: https://golang.org/doc/faq#virus.

I will go ahead and close this because I don't think there is anything we can do here. Please let me know if I am mistaken.
