### ISSUE TITLE
x/pkgsite: shortcut redirect fails if a trailing slash is added

### ISSUE THREAD

**Issue by akolar** [golang/go#40166]
pkg.go.dev supports shortcuts for packages from the standard library (for example, https://pkg.go.dev/http redirects to https://pkg.go.dev/net/http). However, these don't work if a trailing / is appended to the URL.

Opening https://pkg.go.dev/http/ results in a redirect to https://pkg.go.dev/http/net/http (and not https://pkg.go.dev/net/http).

Below are the request and the server's response (shortened):
```
> GET /http/ HTTP/2
> Host: pkg.go.dev
> user-agent: curl/7.71.0
> accept: */*
> 
< HTTP/2 302 
[...]
< location: /http/net/http
```

In the case of https://github.com/golang/pkgsite/blob/master/internal/frontend/details.go#L432, the `url` parameter to `http.Redirect()` is a relative path. Therefore, the (full) redirect path is constructed by appending the relative URL to the current location (https://golang.org/src/net/http/server.go#L2082). 

I have a CL ready but it is based on a fix for golang/go#39663.

Related: golang/go#39663.

**Comment by andybons** [comment]
@julieqiu

**Comment by julieqiu** [comment]
Thanks @akolar! #39663 has been fixed. Feel free to rebase, and I'll review https://golang.org/cl/242138.
