### ISSUE TITLE
proxy.golang.org: module upgrade not detecting new tag

### ISSUE THREAD

**Issue by kevingentile** [golang/go#40170]
### What version of Go are you using (`go version`)?

<pre>
$ go version
  version go1.14.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes, using latest stable release

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kevingentile/Library/Caches/go-build"
GOENV="/Users/kevingentile/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/kevingentile/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/kevingentile/golinks-daemon/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gq/3dt_qkm13qj2rpzqqhmdydfw0000gn/T/go-build868196028=/tmp/go-build -gno-record-gcc-switches -fno-common"</code></summary><br><pre>
$ go env
</pre></details>
### What did you do?
```
go clean -modcache
go get github.com/govice/golinks@v0.1.1
```

### What did you expect to see?
Package upgraded to recently pushed tag (from v0.1.0 -> v0.1.1

### What did you see instead?
```
go: github.com/govice/golinks@v0.1.1/go.mod: verifying module: github.com/govice/golinks@v0.1.1/go.mod: reading https://sum.golang.org/lookup/github.com/govice/golinks@v0.1.1: 410 Gone
        server response: not found: github.com/govice/golinks@v0.1.1: invalid version: unknown revision v0.1.1
```

It's worth noting that prior to attempting this upgrade I deleted two invalid tags from the `govice/golinks` repository (`v0` and `v.0.1.1`)

**Comment by kevingentile** [comment]
Tried this upgrade again ~11 hours after posting this issue and it succeeded.

**Comment by andybons** [comment]
@katiehockman @hyangah @heschik

**Comment by heschik** [comment]
The tag was added a few minutes after this issue was posted. I haven't fully verified but this is almost certainly a case where the version was fetched before it actually existed. In that case `proxy.golang.org` will cache its nonexistance for up to about half an hour.

**Comment by kevingentile** [comment]
Is there a way to flush the cache from my end? @heschik

**Comment by heschik** [comment]
Sorry, no; generally we just suggest you make sure not to try to fetch it before you tag it. Or just wait a little while.

Setting `GOPRIVATE` for modules you own will avoid accidentally fetching them early, though by the same token doesn't guarantee that they have been successfully fetched.
