### ISSUE TITLE
x/pkgsite: size of the top banner

### ISSUE THREAD

**Issue by nanokatze** [golang/go#40181]
I find the banner at the top of every page following me around as I scroll the page make the experience somewhat claustrophobic. Would it be possible to make it somewhat shorter and/or have it not be stuck to my viewport as I scroll, similar to how it currently is on godoc.org?

### What is the URL of the page with the issue?
 
Any, for example https://pkg.go.dev/golang.org/x/tools/cmd/goyacc?tab=doc
 
### What is your user agent?
 
Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
 
### Screenshot

The screen the following was observed on is a 1920×1080 of a 14" laptop computer (Thinkpad T460). Firefox has its layout.css.devPixelsPerPx parameter set to a random value of 1.42 to account for the increased pixel density but even on 96ppi screen with default settings the banner is still somewhat annoying.

![gnome-shell-screenshot-G0CNN0](https://user-images.githubusercontent.com/25141408/87256907-1c703980-c486-11ea-8a81-2fa582f1b647.png)

### What did you expect to see?

![gnome-shell-screenshot-LUIGN0](https://user-images.githubusercontent.com/25141408/87257037-1464c980-c487-11ea-8ca8-6abd69bbefeb.png)

**Comment by ALTree** [comment]
Thanks for the report. This was already reported as #37110, so I'm closing here in favour of the older thread.

**Comment by nanokatze** [comment]
Oops, sorry, my bad for not finding the dup.
