### ISSUE TITLE
runtime: remove the mlock hack in Go 1.15

### ISSUE THREAD

**Issue by DanielShaulov** [golang/go#40184]
The resolution to #35777 was to `mlock` the top of stack on "affected" kernels. But then it was discovered that major distros use kernels that appear by the version number to be affected but are actually patched (#37436). It was also discovered that docker under systemd has a very low limit on `mlock`ed pages (same issue). The resolution for that was to stop reporting failures of `mlock` and delay the warning until a crash is caught.

There is a TODO comment in the code to remove all of that hack for Go 1.15, since unpatched kernels are unlikely to be encountered, but Go 1.15 is due to be released in a short time and the code is still there.

I think it is important to remove the workaround since Ubuntu 20.04 LTS uses a patched 5.4.0 kernel. This means that any user on Ubuntu 20.04 will still unnecessarily mlock pages, and if he runs in a docker container, that warning will be displayed for **every crash**, disregarding the fact that his kernel is not really buggy. So those users might be sent on a wild goose chase trying to understand and read all this info, and it will have nothing to do with their bug, probably for the entirety of Ubuntu 20.04 life cycle.

Relevant code is in `src/runtime/os_linux_x86.go`

**Comment by ALTree** [comment]
> There is a TODO comment in the code to remove all of that hack for Go 1.15 [...] but Go 1.15 is due to be released in a short time and the code is still there.

Can you link where this TODO is? The only relevant comment I found was on [CL 223121](https://go-review.googlesource.com/c/go/+/223121), but it says:

> // TODO(austin): Remove this after Go 1.15 when we remove the
> // mlockGsignal workaround

and "after Go 1.15" means for Go 1.16.

**Comment by nemith** [comment]
Since the kernel detection is done based off of major/minor numbers we actually have to apply a patch to internal builds of the compiler to include our own kernel builds which are not affected but fall in the affected range.   I would love for this to be removed or at least optionally bypassed

**Comment by networkimprov** [comment]
I don't think this needs further info to be actionable...

@gopherbot remove WaitingForInfo

**Comment by aclements** [comment]
@nemith , can you explain why you need to patch the compiler? As of Go 1.14.1, the only effect of an mlock failure is an additional message if there's an uncaught panic, so I don't understand why that requires patching.

**Comment by ianlancetaylor** [comment]
If there is a way to detect the patched kernel, perhaps by reading /proc/version, I think we could implement that safely enough in 1.15.

**Comment by networkimprov** [comment]
Re kernel version sources, see this and comments immediately preceding it: https://github.com/golang/go/issues/37436#issuecomment-591652000

**Comment by aclements** [comment]
There's one deciding factor here: is the kernel patch widespread enough that the workaround is no longer necessary? I'm sure all the distros have it, but people aren't necessarily on top of upgrading their kernels. Unfortunately, I have no idea how to figure out the answer to this, and I think we should be fairly conservative about this given the nature of the kernel bug.

**Comment by lootch** [comment]
On 7/13/20, Daniel Shaulov <notifications@github.com> wrote:
> The resolution to #35777 was to `mlock` the top of stack on "affected"
> kernels. But then it was discovered that major distros use kernels that
> appear by the version number to be affected but are actually patched
> (#37436).

It may be a bitch to do and contrary to Go best practices, but an
"alert" (nag?) mode that notifies users that the kernel they run under
needs a patch, or even better, gives them the ability to check if
their kernel needs attention may be the only politically correct
answer here.

Something that can easily be removed once the user has attended to it.
Or, perhaps better, something they can add as part of the installation
and drop as soon as possible.

Lucio.

**Comment by networkimprov** [comment]
A compromise solution: omit the mlock workaround for a few major distros when the version is known to include the kernel fix.

More distros could be added in later 1.15.1+ releases by folks who can test them.

**Comment by ianlancetaylor** [comment]
@DanielShaulov Would it address your problem if we provided an environment variable to disable the use of `mlock`, as in `GODEBUG=mlock=0`?

**Comment by ianlancetaylor** [comment]
CL 243658 adds `GODEBUG=mlock=0` to disable the use of `mlock`.  If that fixes the problem, we can commit that for 1.15 (and perhaps 1.14.7) and then repurpose this issue for removing this code for 1.16.

**Comment by DanielShaulov** [comment]
Hi, I am very sorry for not responding, didn't get notifications until I got pinged.

@ALTree Here is the relevant TODO, it says "in Go 1.15" and not "after Go 1.15":
https://github.com/golang/go/blob/11f92e9dae96939c2d784ae963fa7763c300660b/src/runtime/os_linux_x86.go#L31-L33
But I see that the other places used "after Go 1.15", so this one might have been a mistake?

@networkimprov At the very least - all the 5.4.0 kernels that Ubuntu ever published were patched (I checked all the 5.4.0-* tags in their git). So I think just checking for that will cover a pretty large set of false positive.
Redhat family can be checked to see if they have an LTS release stuck with a kernel version in the "bad" range, but if not then their problem is much smaller than Ubuntu's.

@ianlancetaylor See above about the confusion about the version it was supposed to be fixed. I am OK with re-purposing the issue for 1.16,  I was just worried that this was just forgotten and be left like this for the whole duration of Ubuntu 20.04.
But I still think adding another check for the major distros as networkimprov suggested is a good idea.
I don't think the `DEBUG=mlock=0` thing would really solve the issue. Developers will still spend time looking into those issue, reading the wiki, running the test program, just to find out that their kernel is already patched, and their issue lies elsewhere.
But the resolution for this can wait for Go 1.16 I guess.

**Comment by ianlancetaylor** [comment]
@DanielShaulov Thanks.  Since the `GODEBUG` environment variable won't help, I'll drop that CL.

I'm not sure how to proceed with checking major distros.  What we need is some mapping from the `/proc/version` string to kernels that are known to be fixed.

**Comment by DanielShaulov** [comment]
Well - first we need to get our distro name, for that I think [/etc/os-release](https://www.freedesktop.org/software/systemd/man/os-release.html) is the most reliable way. We just need the `NAME=` field. (And if we fail that, no big deal, we just fall back to current behavior of just checking official kernel release).

Then, looking at https://github.com/golang/go/issues/37436#issuecomment-591652000 we can probably just parse the end of the kernel release (the part after `-` which is currently discarded in `parseRelease`) and save it as `tail`,
And then in `osArchInit`, we can just `switch` on the distro name an have our per-distro logic.

For Ubuntu, it is a dead simple `if major == 5 && minor >= 4 { return }`, and doesn't even need the `tail`, since all 5.4.x kernels in Ubuntu are patched. (other distros might need the `tail`)

**Comment by ianlancetaylor** [comment]
https://golang.org/cl/244059 is code that skips the mlock on Ubuntu 5.4 systems, based on reading `/proc/version`.

**Comment by networkimprov** [comment]
@ianlancetaylor you could leave this issue open for discussion of other distros during the 1.16 cycle.

**Comment by ianlancetaylor** [comment]
In the 1.16 cycle we're going to remove the `mlock` calls (#35979).

**Comment by networkimprov** [comment]
But you may add other distros to the don't-mlock list in 1.15.x.

**Comment by ianlancetaylor** [comment]
@networkimprov True, but I don't see that as a reason to keep this issue open.  There is no action that we would take to close the issue.
