### ISSUE TITLE
cmd/go2go: embedded types ignored in interface implementation

### ISSUE THREAD

**Issue by JavierZunzunegui** [golang/go#40199]
*This is not a generics proposal, but reporting a bug in the generics branch. First presented in [golang-nuts](https://groups.google.com/g/golang-nuts/c/v10JCQFm9_E).*

### What version of Go are you using (`go version`)?

generics branch (from https://go2goplay.golang.org/)

### Does this issue reproduce with the latest release?

No, just generics branch

### What operating system and processor architecture are you using (`go env`)?

N/A (in https://go2goplay.golang.org/)

### What did you do?

Assigned a generic type to an interface satisfied by a struct embedded in it.
https://go2goplay.golang.org/p/fOJIhgnbOxC

### What did you expect to see?

It would implement the interface, and compile.

### What did you see instead?

It doesn't implement the interface, and therefore doesn't compile.

**Comment by andybons** [comment]
@ianlancetaylor @griesemer

**Comment by mmaedel** [comment]
Hi can you please change title?

cmd/go2go...

**Comment by griesemer** [comment]
@mmaedel Done.

**Comment by griesemer** [comment]
This code passes the type-checker. Likely an issue with the translator phase.

**Comment by griesemer** [comment]
Test case updated to new syntax: https://go2goplay.golang.org/p/Ssd4Ws7F91G

**Comment by JavierZunzunegui** [comment]
Just checking in - is this bug being looked into?
And particularly, has there been any discussion within the go team about [Type embedding in generic types](https://groups.google.com/g/golang-nuts/c/v10JCQFm9_E)?

**Comment by griesemer** [comment]
See https://go.googlesource.com/proposal/+/refs/heads/master/design/go2draft-type-parameters.md#embedded-type-parameter-methods.

We know about this bug, but it's not urgent. Note that dev.go2go is a prototype. Not everything will be supported.

**Comment by ianlancetaylor** [comment]
The decision here is that we don't permit embedded fields to be type parameters.  The current compiler gives an error.
