### ISSUE TITLE
x/pkgsite: go package info not updated on every release

### ISSUE THREAD

**Issue by Delta456** [golang/go#40202]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/Delta456/box-cli-maker?tab=doc

 
### What is your user agent?
 
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
 
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/28479139/87426162-6da23980-c5fc-11ea-9757-945cd101e457.png)

 
### What did you do?
 
Released a new version of my Go Package a month ago https://github.com/Delta456/box-cli-maker/releases/tag/v1.3.1

 
### What did you expect to see?
 
Package information updated 
 
 
### What did you see instead?

Package information not updated yet.

**Comment by andybons** [comment]
The [About page](https://go.dev/about#adding-a-package) has info on updating packages. Was either step performed?

**Comment by Delta456** [comment]
@andybons I get this with `https://proxy.golang.org/github.com/Delta456/box-cli-maker/@v/1.3.1.info` 

```
bad request: invalid escaped module path "github.com/Delta456/box-cli-maker"
```

but if I lower case my name like `https://proxy.golang.org/github.com/delta456/box-cli-maker/@v/1.3.1.info` then I get:

```
not found: github.com/delta456/box-cli-maker@1.3.1: invalid version: unknown revision 1.3.1
``` 

This is related to https://github.com/moul/golang-repo-template/issues/51 as well. I think it cannot get requests as my name starts with capital.

**Comment by julieqiu** [comment]
https://pkg.go.dev/github.com/Delta456/box-cli-maker now shows v1.3.1 as the latest version. I am also working on #37002 to improve the flow for adding a new package. Closing this issue.

**Comment by Delta456** [comment]
@julieqiu Thank you so much!

**Comment by Delta456** [comment]
I would like to know how this happened though.

**Comment by Delta456** [comment]
@julieqiu Heads up. I have released another version of my module yesterday and it doesn't shows updated info.
