### ISSUE TITLE
x/website: Make website search case-insensitive

### ISSUE THREAD

**Issue by mleonhard** [golang/go#40217]
### What did you do?

My golang program needs to find out if a path refers to an existing directory.  I needed to find out how to do that.  Here's what I did:
1. Go to https://golang.org/
1. Look around for a search button.
1. Click the three-bars icon to display the menu.
1. Click in the Search box.
1. Type `isdir` and hit ENTER.
1. Looked for the appropriate function.

### What did you expect to see?
A link to [FileInfo.IsDir() bool](https://golang.org/pkg/os/#FileInfo)

### What did you see instead?
Irrelevent links.  Here's a screenshot:
![Screen Shot 2020-07-14 at 15 49 50](https://user-images.githubusercontent.com/520739/87483902-c0262a80-c5e9-11ea-80d8-05a4c1aebd92.png)

**Comment by rsc** [comment]
Search box removed (#44357).
