### ISSUE TITLE
x/website: show search box on smaller viewports

### ISSUE THREAD

**Issue by mleonhard** [golang/go#40220]
### What did you do?

1. Go to https://golang.org/
1. Look around for a search button.
1. Click the three-bars icon to display the menu.
1. See the Search box.

### What did you expect to see?

The search box appearing at the top or side of the page, like other official language documentation sites:
- [C#](https://docs.microsoft.com/en-us/dotnet/csharp/)
- [Python 3](https://docs.python.org/3/)
- [Rust](https://doc.rust-lang.org/std/index.html)
- [Erlang](https://erlang.org/doc/search/)
- [Java](https://docs.oracle.com/en/java/)
- [Ruby](https://docs.ruby-lang.org/en/master/)
- [TCL](https://tcl.tk/doc/)
- [OCaml](https://ocaml.org/docs/)
- [TypeScript](https://www.typescriptlang.org/docs/home.html)
- [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference)
- [Bazel](https://www.bazel.build)
- [TensorFlow API](https://www.tensorflow.org/api_docs/)
- [PostgreSQL](https://www.postgresql.org/docs/12/index.html)
- [Dart](https://dart.dev)

### What did you see instead?

Golang's search box is hidden behind a menu.  Out of all the language documentation websites I found, Golang's is the only one that hides the search box.

**Comment by andybons** [comment]
As a note, the search box is only hidden behind a menu when the viewport width is below a certain threshold. It should not always be hidden.

![image](https://user-images.githubusercontent.com/365204/87564306-3bd9b300-c68e-11ea-9719-b65a06a745bd.png)

Renaming this issue to be about making the search box visible on all viewport sizes.

**Comment by magical** [comment]
It looks like the search box may be removed entirely (#44357), in which case this issue can be closed.

**Comment by dmitshur** [comment]
Indeed, this isn't relevant by now, closing.
