### ISSUE TITLE
proposal:strconv.ParseBool produces a detailed error message that points to the use of Golang

### ISSUE THREAD

**Issue by sean2Yi** [golang/go#40232]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sean/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sean/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/sean/Documents/workspace4/assets/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2z/g1hqw0lj415_z5dlz9gxpz600000gn/T/go-build331636948=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

	result, err := strconv.ParseBool("test")
	if err != nil {
		t.Errorf("%v", err)
	}

### What did you expect to see?
<pre>
parsing "test": invalid syntax
</pre>

### What did you see instead?
<pre>
strconv.ParseBool: parsing "test": invalid syntax
</pre>

strconv.ParseBool produces a detailed error message that points to the use of Golang.
I suggest to remove strconv.ParseBool string from the error message due to the security vulnerability.

**Comment by ALTree** [comment]
If you don't want this kind of detail to leak, intercept the error and print your own. But we certainly cannot change every single error the compiler, the runtime and the standard library packages print to make them not leak the fact that the binary was built using Go.
