### ISSUE TITLE
x/pkgsite: consolidate keyboard shortcut behavior across site

### ISSUE THREAD

**Issue by andybons** [golang/go#40246]
There are few places where we handle keyboard shortcuts on the site, and these should be consolidated into a sensible design to more easily avoid conflicts and code duplication.

**Comment by AceroM** [comment]
In most popular websites (reddit, github etc...) typing "?" would bring up a dialog to open up keyboard shortcuts, would this be something we can consider?

**Comment by andybons** [comment]
@AceroM That exists right now at least on the Doc tab. It seems to make sense to have it on other pages, but that’s not really what this issue is about.

**Comment by andybons** [comment]
Apologies @AceroM as I didn’t exactly clarify what this issue was about 😄 .

This issue is about coming up with a solid architecture design on the frontend for handling keyboard shortcuts in code. It’s not focused on visual design or UI elements on the page.
