### ISSUE TITLE
gccgo: undefined reference when linking

### ISSUE THREAD

**Issue by zhsj** [golang/go#40252]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 gccgo (Debian 20200715-1) 11.0.0 20200715 (experimental) [master revision fff15bad1ab:53319423ecb:7a9fd18598e638b55c591624e753fb7a88abe1ab] linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/zhsj/.cache/go-build"
GOENV="/home/zhsj/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/zhsj/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/gcc/x86_64-linux-gnu/10"
GCCGO="/usr/lib/gcc-snapshot/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/t/tt/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build400584759=/tmp/go-build -gno-record-gcc-switches -funwind-tables"

</pre></details>

### What did you do?

I don't know how to describe the problem. I just find it when building [elvish](https://github.com/elves/elvish).

I have reproduced the problem with following code.

```
==> ./pkgb/pkgb.go <==
package pkgb

import "bugtest/pkga"

type B interface{
        GetA() pkga.A
}



==> ./test.go <==
package main

import (
        "bugtest/pkga"
        "bugtest/pkgc"
)

type testA struct {
}

func (testA) Func() {
}

type testB struct {
        a pkga.A
}

func (b testB) GetA() pkga.A {
        return b.a
}
func main() {
        b := testB{testA{}}
        pkgc.Test(b)
}

==> ./pkgc/pkgc.go <==
package pkgc

import (
        "bugtest/pkga"
        "bugtest/pkgb"
)

func test(b pkgb.B, f func(pkga.A)) {
        f(b.GetA())
}

func Test(b pkgb.B) {
        test(b, pkga.A.Func)
}

==> ./pkga/pkga.go <==
package pkga

type A interface {
        Func()
}

==> ./go.mod <==
module bugtest

go 1.14

```

### What did you expect to see?

Build without error.

### What did you see instead?

```
# bugtest
/usr/bin/ld: /home/zhsj/.cache/go-build/ea/ea4b9775947f0eae0848aa6de3b1dd2e84c3f5cbb5d5164df059bb4d2099acaa-d(_go_.o): in function `bugtest..z2fpkgc.Test':
/tmp/t/tt/ /tmp/t/tt/pkgc/pkgc.go:13: undefined reference to `bugtest..z2fpkgc.bugtest..z2fpkgc..thunk0..f'
collect2: error: ld returned 1 exit status
```

**Comment by andybons** [comment]
@ianlancetaylor @thanm @cherrymui

**Comment by mdempsky** [comment]
Here's a more minimal reproducer:

```
$ cat go.mod
module bug

go 1.14

$ cat a/a.go
package a

type I interface {
	Func()
}

func Call() {
	f := I.Func
	f(nil)
}

$ cat main.go
package main

import "bug/a"

func main() {
	a.Call()
}

$ go build .
# bug
/usr/bin/ld: $WORK/b001/_pkg_.a(_go_.o): in function `bug..z2fa.Call':
/tmp/tt/ /tmp/tt/a/a.go:9: undefined reference to `bug..z2fa.bug..z2fa..thunk0..f'
/usr/bin/ld: /tmp/tt/ /tmp/tt/a/a.go:9: undefined reference to `bug..z2fa.bug..z2fa..thunk0..f'
collect2: error: ld returned 1 exit status
```

**Comment by ianlancetaylor** [comment]
Thanks for the reduced test case.

The inlinable version of `a.Call` is

```
func Call () <inl:91>
 // /tmp/x/src/a/a.go:7
 var f <type 2> = a..thunk0 //8
 (f)($convert(<type 1>, $nil)) //9
```

Here the reference to `I.Func` has changed to a reference to `a..thunk0`.  The bug is that we don't generate a function descriptor for that thunk function.  Probably we need to generate the inlinable version differently here.

**Comment by zhsj** [comment]
Hi,

Could this be backported to gcc10? It seems that Debian will use gcc10 for its next stable release.

**Comment by ianlancetaylor** [comment]
@zhsj The change was already backport to GCC 10 branch on August 14.  GCC repository commit 1925bff7f21e5aaffb9a7fcf1356e67472d64b03.
