### ISSUE TITLE
x/pkgsite: clarify expected input on pkg.go.dev/badge

### ISSUE THREAD

**Issue by ostcar** [golang/go#40258]
### What is the URL of the page with the issue?
https://pkg.go.dev/badge/
 
 
### What is your user agent?
 

Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0

 
 
 
### Screenshot
 

![screenshot](https://user-images.githubusercontent.com/977937/87718289-c109b880-c7b1-11ea-9a66-aab2ac8bbb0e.png)
 
 
 
### What did you do?
 

Open the page.
 
 
 
### What did you expect to see?
The form-field called `URL` should either be called `package` or accept an URL with an (https-)schema.

 
 
 
### What did you see instead?
The Form-Field is called URL, but if you paste an URL with an protocol-schema, it creates an invalid link to pkg.go.dev.

The example text in the empty form-field (when empty) shows an example URL with an schema. This example creates an invalid badge.

I already reported it [here](https://github.com/golang/go/issues/36982#issuecomment-659198248) but was ask to create a new issue.

**Comment by jamalc** [comment]
We chose to label the input "URL" to clarify that the tool is not limited to packages. The form does accept full URLs but the schema and host are trimmed from the input box once they are submitted. On second look that may be somewhat misleading.

It could be a better experience to keep the full URL in the input box after the badge is created OR to label the input something like Path and clarify that it can be any pkg.go.dev URL path and is not limited to packages. I think in any case we should accept full URL or a pkg.go.dev path as input.

**Comment by seankhliao** [comment]
I think this was done at some point.
It works with:
```
https://pkg.go.dev/example.com/module
https://example.com/module
example.com/module
```
