### ISSUE TITLE
pointer 0xc000437168 to unallocated span span.base()=0xc000430000 span.limit=0xc000438000 span.state=0

### ISSUE THREAD

**Issue by MarErm27** [golang/go#40268]
### What version of Go are you using (`go version`)?
I've tried  go1.14.2,  go1.14.4 and some older versions
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
I've tried two
AMD Ryzen™ 7 2700X, Windows
and
Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz, Linux

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
I've described it here https://github.com/Iwark/spreadsheet/issues/52

### What did you expect to see?
I've tried to update Google Sheets cell and it works well in debug regime

### What did you see instead?
It returns an error when I run it not in debug regime

**Comment by MarErm27** [comment]
Here runtime\mbitmap.go
in function findObject
I changed this statement
		// The following ensures that we are rigorous about what data
		// structures hold valid pointers.
		if debug.invalidptr != 0 {
			badPointer(s, p, refBase, refOff)
		}
to this
		// The following ensures that we are rigorous about what data
		// structures hold valid pointers.
		if debug.invalidptr != 0 {
			return
			badPointer(s, p, refBase, refOff)
		}

and it works... I probably shouldn't leave it like this...

**Comment by prattmic** [comment]
cc @mknyszek

**Comment by MarErm27** [comment]
Hi, I was creating a client multiple times but I had to create it once and to use it. After I've done it like this error is gone.
