### ISSUE TITLE
x/build/env/linux-arm64/packet: 8 Packet linux/arm64 machines missing (mid-July 2020)

### ISSUE THREAD

**Issue by dmitshur** [golang/go#40261]
From https://farmer.golang.org:

![image](https://user-images.githubusercontent.com/1924134/87721216-14fda880-c784-11ea-9690-76ab02a37ecc.png)

May be similar to #37922.

/cc @andybons @cagedmantis @toothrot

**Comment by andybons** [comment]
Restarted the machine. Let’s see if that works.

**Comment by andybons** [comment]
Machine is back up and farmer.golang.org is happy.
