### ISSUE TITLE
encoding/json: Avoid "invalid use of ,string struct tag, trying to unmarshal %q into %v" when target type matches

### ISSUE THREAD

**Issue by andig** [golang/go#40266]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/andig/Library/Caches/go-build"
GOENV="/Users/andig/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/andig/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/andig/htdocs/evcc/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/73/89ycv7qn51j4kbm04jsz9b840000gn/T/go-build573766352=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Unmarshal

    { "ser":"<serial>" }

into 

    type api struct { Serial string `json:ser,string` }

### What did you expect to see?

No error

### What did you see instead?

    invalid use of ,string struct tag, trying to unmarshal "ser" into api.Serial"

While the error can easily be worked around by omitting the string tag, it shouldn't error as the types are compatible. That is- unless this error message is intended to ensure that the json user is 100% aware of the json schema he consumes.

**Comment by seankhliao** [comment]
The `string` option has the specific meaning of representing a double encoded value, not just mangle it into a string

**Comment by mvdan** [comment]
What @seankhliao said. A valid input would be like:

```
{ "ser": "\"doubly encoded string\"" }
```
