### ISSUE TITLE
x/tools/gopls: support converting array to slice when completing

### ISSUE THREAD

**Issue by muirdm** [golang/go#40277]
When working with arrays you often need to convert them to slices. It would be nice if gopls offered completion candidates that did this for you:

```go
package main

import "os"

func main() {
	var a [32]byte
	os.Stdout.Write(<>) // offer `a[:]` as a candidate
}
```

**Comment by hasheddan** [comment]
Happy to take this one if no one else is already working on it!

/cc @stamblerre @muirdm

**Comment by muirdm** [comment]
I'm not working on it. Happy to give pointers if needed!

**Comment by hasheddan** [comment]
@muirdm I am still interested in tackling this, but was out of office last week so I haven't gotten to it yet. Would likely have time this weekend, but certainly understand if the team needs to go ahead and move forward :)

**Comment by muirdm** [comment]
No worries, take your time.
