### ISSUE TITLE
Strftime or YYYY-MM-DD hh:mm:ss alternative time formatting

### ISSUE THREAD

**Issue by sirkon** [golang/go#40287]
Hi!

Would it be a viable option to introduce alternative time formatting approach?

It is long time already I only code Go, everything is good, but `time.Format` proves again and again it was not really good decision for folks like me: I still remember how to do formatting with strftime despite years I didn't touch it, yet I need to go to `time.RFC3339` to remember what numbers I need to apply after just a couple of months when I was not using it.

This may be different for others of course, but I may be not alone.

So, may be to introduce `time.Strftime`?

Another alternative could be `YYYY-MM-DD hh:mm:ss` where, unlike in Java, everything longer than an hour + zone format uses capitals and everything else uses lowercase. IMO it is even easier to memorize than strftime format.

**Comment by akavel** [comment]
See also: #25572

**Comment by ianlancetaylor** [comment]
Dup of #444, #8390, #25294.

This doesn't seem to add anything that was not covered by those earlier issues, so closing as a duplicate.
