### ISSUE TITLE
cmd/gofmt: don't remove spaces when combining binary and unary *

### ISSUE THREAD

**Issue by peidaqi** [golang/go#40288]
### What version of Go are you using (`go version`)?

go1.14.4

### Problem

I understand that gofmt will try to remove spaces between operator and operand, so that it's easier to tell the association. However, this creates weird situations when the star operator is involved with pointers. For example:
    
	x := 10
	p1 := &x
	p2 := &x
	fmt.Println(10 * *p1 * *p2)
  
works as expected, but if we add a 1 in the last line:
    
	x := 10
	p1 := &x
	p2 := &x
	fmt.Println(10**p1**p2 + 1)

where the 10 **p1 **p2 would be very easily confused as an exponential operator - which golang doesn't have.

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by ALTree** [comment]
This is #2098, in particular see https://github.com/golang/go/issues/2098#issuecomment-66057837.

**Comment by griesemer** [comment]
If we rewrite your example as desired, we get:
```Go
fmt.Println(10 * *p1 * *p2 + 1)
```
which is better for the multiplications, but worse for the addition as it lost its difference from the multiplications which have higher precedence. As has been pointed out above, this was discussed almost 10 years ago and we decided to leave it alone. The better solution is to introduce parentheses to increase readability when it's problematic. Also, this is not a very common situation.
