### ISSUE TITLE
x/pkgsite: remove github.com/dsyx/serial-go

### ISSUE THREAD

**Issue by dsyx** [golang/go#40305]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/dsyx/serial-go?tab=doc
 
### What is your user agent?
 

 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.40
 
### Screenshot
 

 
 
![image](https://user-images.githubusercontent.com/34703581/87943573-d132d800-cad0-11ea-99c2-cb48ec1634e0.png)

 
### What did you do?
 

 
This is my package, but after I changed the name, its old copy is still on go.dev. In fact, the module address pointed to by this packet is invalid.
 
### What did you expect to see?
 
I think go.dev should remove it. go.dev should remove such non-existent modules.

**Comment by dsyx** [comment]
I don't think the title should be changed. In theory, this will happen to all renamed packages. @toothrot

**Comment by julieqiu** [comment]
Removed. https://pkg.go.dev/github.com/dsyx/serial-go should now return a 404.

**Comment by dsyx** [comment]
If other Go packages change their names, will this phenomenon still happen? @julieqiu

**Comment by julieqiu** [comment]
Yes - package authors will need to notify us when they want a package removed. See a related comment on this topic here: https://github.com/golang/go/issues/38897#issuecomment-624632570

**Comment by dsyx** [comment]
Thanks. Will go.dev automatically delete non-existent packages in the future?
