### ISSUE TITLE
x/playground: version stated on "About" page is sometimes one version behind

### ISSUE THREAD

**Issue by dmitshur** [golang/go#40319]
The current latest Go release is Go 1.14.6.

Clicking the About button at https://play.golang.org now says:

> The playground uses the latest stable release of Go.
> The current version is [go1.14.5](https://play.golang.org/p/Ztyu2FJaajl).

However, running the https://play.golang.org/p/Ztyu2FJaajl program suggests the actual playground program execution uses Go 1.14.6. So it's only the frontend that's on the previous version.

So it's not a big deal, but need to understand why this happens and fix it.

/cc @toothrot

**Comment by dmitshur** [comment]
By now (after some number of days have passed), it says "The current version is go1.14.6." on the About page.

**Comment by dmitshur** [comment]
As another data point, https://play.golang.org/p/Ztyu2FJaajl says "go1.15" now (which was [just released](https://groups.google.com/forum/#!topic/golang-announce/Z-cY6ZdGdEU)) but the About page still says "The current version is go1.14.7."

**Comment by toothrot** [comment]
The playground builds the sandbox environment at the latest version of Go, but builds the front-end code at the bootstrap version. This is mostly because the Go artifacts aren't available 

We should also run the front-end at the latest version of Go.

Fixing it this way is blocked by #44502.

**Comment by toothrot** [comment]
Fixed and deployed.
