### ISSUE TITLE
Write flag is turned on when deleting a key from a map, even if the key doesn't exist

### ISSUE THREAD

**Issue by amitdavidson234** [golang/go#40327]
### What version of Go are you using (`go version`)?
 go1.13 darwin/amd64

### Does this issue reproduce with the latest release?
 Yes

### What operating system and processor architecture are you using (`go env`)?

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/amdavidson/Library/Caches/go-build"
GOENV="/Users/amdavidson/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/amdavidson/dev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3p/ydb2x5ls4b94ysv8bw2m8_48fvsncb/T/go-build154927085=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you expect to see?
map write flag is shouldn't be set if the key in the map doesn't exist. 

### What did you see instead?
map write flag is set when deleting an item even if the key doesn't exist in the map.

### What did you do?
The issue arises when 2 goroutines access the map at the same time. The first reads an item from the map, and the second deletes a key from it. Even if no key is found and no write was made, the reading goroutine will suffer concurrent read-write since the write flag is turned on before we check to see if the key exists.

https://github.com/golang/go/blob/11f92e9dae96939c2d784ae963fa7763c300660b/src/runtime/map.go#L709
Few lines before it is mentioned the write flag is turned on only after t.hasher ran since it may panic and no commit (write) will be made. This problem I suggested is similar.

**Comment by mvdan** [comment]
> The issue arises when 2 goroutines access the map at the same time. The first reads an item from the map, and the second deletes a key from it. Even if no key is found and no write was made

Why would you want to do this in the first place, though? At best, it makes no sense. At worst, it's considered a data race, which is why the runtime panics.

**Comment by martisch** [comment]
Concurrently reading and attempting to write or delete a key is a data race. The data race detection during normal runtime is best effort and might not trigger for all data races.
https://golang.org/doc/faq#atomic_maps

If the goroutine attempting deletion is known always to not delete a key to goroutine does not need to try to delete the key. If the goroutine sometimes actually deletes a key then this will trigger a data race warning even if the map implementation is changed to not set the hashWriting flag when no actual internal structure is changed.

In the current implementation there might not be a write to internal data structures but in the future there might be e.g. for bookkeeping and internal reorgantzaiion of the map for shrinking (even if no key was found).
