### ISSUE TITLE
x/pkgsite: support to set minimum log level

### ISSUE THREAD

**Issue by amarjeetanandsingh** [golang/go#40339]
Right now there isn't a proper way to disable a log level.

For example, if you want to disable the `Debug` logs, you need to comment out [this line](https://github.com/golang/pkgsite/blob/master/internal/log/log.go#L156) 

I feel **there should be better way to setup the minimum log level below which, no logs should be printed**. 

For example- 
If we consider the log severity sequence as `Debug < Info < Error < Fatal` and the log level is set to `Info`, the `Debug` logs shouldn't be printed but `Info` `Error` & `Fatal` should be printed.

If allowed, I would like to work on the implementation.

/cc @julieqiu

**Comment by julieqiu** [comment]
Thanks, @amarjeetanandsingh! Feel free to send a CL for this issue.

**Comment by amarjeetanandsingh** [comment]
@julieqiu 
**How to take the log level as input?** 
### 1)
Like other configs, I think we should use `GO_DISCOVERY_LOG_LEVEL` env variable to set the log level config. Then get the log level value in log package from config and put a check before logging.

**Is approach (1) acceptable?**

----
### 2)
Other way i can think of is to take the log level as command line arg. But I am not sure this would be good approach in this context.

**Comment by jba** [comment]
I'm okay with this idea. Namely:
- The internal/config package will read and store GO_DISCOVERY_LOG_LEVEL.
- Th internal/log package will use that config value to drop log messages below the level.
- The default will be the empty string, meaning "show all levels." We do not want to change default behavior. In particular, we use the Stackdriver log viewer to filter logs for us, so there is no upside to filtering the Stackdriver logs on the client and a big downside of losing valuable debugging information.
