### ISSUE TITLE
x/pkgsite: don't save zero-length readmes

### ISSUE THREAD

**Issue by jba** [golang/go#40336]
If a readme file is zero-length, don't write it to the DB.

Example: https://github.com/docker/go-connections/blob/master/sockets/README.md

**Comment by amarjeetanandsingh** [comment]
Hi @jba 

Just to confirm, you mean if the `readme` file content is empty, there shouldn’t have any entry in `readmes` table?

If yes, is putting a content check in `internal/postgres/insert_module.go` would be a good place?
Like adding `d.Readme.Contents != "" `  [here](https://github.com/golang/pkgsite/blob/9d8c5ddc56ee57a4afbe15d5680bb1e65efb6fd9/internal/postgres/insert_module.go#L419) would help?

**Comment by jba** [comment]
`makeValidUnicode` can return an empty string given a non-empty one (if it's all zeroes), so I think the check should happen after that call.
