### ISSUE TITLE
x/mobile: reduce size of generated artifacts

### ISSUE THREAD

**Issue by ToJen** [golang/go#40348]
The size of Go builds can be shrunk with the `ldflags` build option like this:
`go build -ldflags '-s -w' -o my_app.exe`

This can be reduced further with [UPX](https://upx.github.io/) as such:
`upx -o my_app_min.exe my_app.exe`

More on this [here](https://lukeeckley.com/post/useful-go-build-flags).

I'm able to pass the `ldflags` into gomobile like this:
`gomobile bind -ldflags '-s -w' -target=android github.com/my/app`.

I would like to "inject" UPX somewhere in the bind process to reduce the size of my generated `.aar` and `.framework`. 

A possible flow is this:
1. Build: `go build -ldflags '-s -w' -o my_app.exe`
2. Shrink: `upx -o my_app_min.exe my_app.exe`
3. Pass into gomobile:`gomobile bind --from-build=my_app_min.exe -target=android github.com/my/app`

**Comment by ToJen** [comment]
@toothrot @hyangah what's a place to start the investigation. I believe many users will benefit from a smaller aar and framework. Would it make sense at all to achieve it this way?

**Comment by ToJen** [comment]
i believe it will be somewhere here:
android: https://github.com/golang/mobile/blob/master/cmd/gomobile/bind_androidapp.go#L52
ios: https://github.com/golang/mobile/blob/master/cmd/gomobile/bind_iosapp.go#L38

**Comment by BenLubar** [comment]
Another way to reduce the size of the APK would be to generate an AAB instead, which would mean an x86 device would only receive x86 code and an ARM device would only get ARM code.

As it currently stands, the APK contains 4 copies of all native code, which totals about 100 megabytes for my app after zip compression.

**Comment by ToJen** [comment]
@BenLubar I came across [this article](https://rogchap.com/2020/09/14/running-go-code-on-ios-and-android/) which doesn't use gomobile. It may be possible to achieve my suggestions with the author's approach.
