### ISSUE TITLE
net/dial.go local variable `d` conflicted with receiver `d`

### ISSUE THREAD

**Issue by edocevol** [golang/go#40361]
### Does this issue reproduce with the latest release?

Yes

### What did you do?

change `d, ok := ctx.Deadline()` to `dl, ok := ctx.Deadline()`

### What did you expect to see?

```go
if dl, ok := ctx.Deadline(); ok {
	earliest = minNonzeroTime(earliest, dl)
}
```

### What did you see instead?
```go
if d, ok := ctx.Deadline(); ok {
	earliest = minNonzeroTime(earliest, d)
}
```

**Comment by davecheney** [comment]
This is ok according to the scoping rules in Go, the `d` in the scope of the `if` shadows another declaration in the outer scope. If you feel strongly that this should be changed, please consider `deadline`.

**Comment by davecheney** [comment]
removed the proposal title element, this is not a proposal according to the definition.

**Comment by mdlayher** [comment]
The author submitted and subsequently closed a pull request with no further comment, so I assume there is nothing to be done here. Closing.
