### ISSUE TITLE
x/pkgsite: inconsistent license detection

### ISSUE THREAD

**Issue by dsnet** [golang/go#40377]
On the per-package page for [`github.com/dsnet/compress/bzip2`](https://pkg.go.dev/github.com/dsnet/compress/bzip2?tab=licenses), it properly detects the license as BSD-3-Clause.

On the per-module page for [`github.com/dsnet/compress`](https://pkg.go.dev/mod/github.com/dsnet/compress?tab=licenses), it reports that there are no licenses detected.

I expect this to be consistent. Either both have licenses available, or both do not.

\cc @julieqiu

**Comment by jba** [comment]
This is now working (the module page shows BSD-3), but I don't know why (I didn't do anything). It may have been a transient state due to reprocessing or the use-paths experiment being enabled.

**Comment by dsnet** [comment]
Bugs that fix themselves. My favorite ;P
