### ISSUE TITLE
Go Hello World Program taking too long to run

### ISSUE THREAD

**Issue by VaishakVk** [golang/go#40374]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.14.6 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Windows 10 and i7
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\vaishakv\AppData\Local\go-build  
set GOENV=C:\Users\vaishakv\AppData\Roaming\go\env    
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\vaishakv\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\vaishakv\AppData\Local\Temp\go-build777313446=/tmp/go-build -gno-record-gcc-switches

### What did you do?

- Tried disabling the antivirus

### What did you expect to see?
- Run Hello World program in less than a second

### What did you see instead?
- Program runs in 8 - 10 seconds

**Comment by mdlayher** [comment]
There isn't enough information here to provide any kind of diagnosis, but this appears to be a usage question or a matter related to the configuration of your system. See https://github.com/golang/go/wiki/Questions, closing.
