### ISSUE TITLE
module net/http/request addCookie error

### ISSUE THREAD

**Issue by henrycjchen** [golang/go#40383]
When I init a request without a header, it will cause a error if I use AddCookie
```go
req := http.Request{}
req.AddCookie(&http.Cookie{
	Name: "access_token",
	Value: "123",
})
// assignment to entry in nil map 
```
Should method AddCookie check the header and init it, or the coder init the header before use AddCookie?
(relevant code: https://github.com/golang/go/blob/78c20c81aaa7d8d8a4aa2132806f51fb68f33a1e/src/net/http/request.go#L433)
PTAL.

**Comment by davecheney** [comment]
Why not use `http.NewRequest`?

**Comment by henrycjchen** [comment]
Thanks for reminding, it should work.

**Comment by mdlayher** [comment]
See also https://github.com/golang/go/wiki/Questions. Looks like this is resolved, closing.
