### ISSUE TITLE
cmd/go2go: failure use Square brackets to Instantiate when there are two type parameter

### ISSUE THREAD

**Issue by donnol** [golang/go#40380]
[example](https://go2goplay.golang.org/p/N723N7AnNQq)

key code: 

```
...
var m = Map[int, string]
...
```

instead, use Parentheses is good.

**Comment by ianlancetaylor** [comment]
Thanks for the test case.  It works on the tip of the dev.go2go branch.  The playground hasn't been fully updated yet.
