### ISSUE TITLE
x/mobile/cmd/gomobile: Go1.15beta1 cannot generate Objective-c bindings if target includes amd64

### ISSUE THREAD

**Issue by libnat** [golang/go#40390]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15beta1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="darwin"
</pre></details>

### What did you do?
`gomobile bind -v -target=ios .` 
`gomobile bind -v -target=ios/amd64 .` 
Both fail with the same error.

### What did you expect to see?
Generate objective-c framework

### What did you see instead?
```
clang: error: invalid argument '-mmacosx-version-min=10.11' not allowed with '-mios-simulator-version-min=7.0'
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
```

**Comment by hajimehoshi** [comment]
CC @hyangah @eliasnaur @dmitshur

**Comment by hajimehoshi** [comment]
Confirmed the issue.

I'm not sure where `-mmacosx-version-min=10.11` came from. I think this is from Go 1.15 compiler, but is that true?

**Comment by hajimehoshi** [comment]
```
$ find . -name "*.go" | xargs grep "mmacosx-version-min"                                                                                                                                                                                      
./src/crypto/x509/root_cgo_darwin_amd64.go:#cgo CFLAGS: -mmacosx-version-min=10.11
```

My guess is that this should be omitted when `ios` build tag exists.

**Comment by hajimehoshi** [comment]
This issue does not happen with the latest Go, then the next version of Go 1.15 has already fixed this issue.

(Probably https://github.com/golang/go/commit/72019cf3128af1b8f48f7ec5f04bc04a98c23131 fixed this?)

**Comment by hajimehoshi** [comment]
Go 1.15 rc1, which was released 30 minutes ago, did not cause this issue. Let me close this.

**Comment by dmitshur** [comment]
Thanks for investigating and confirming this is fixed, Hajime.
