### ISSUE TITLE
FIX the ticker memory leak

### ISSUE THREAD

**Issue by Dontmindmes** [golang/go#40395]
Hey, i made a program that sends requests to my HTTP website using a ticker and everytime the ticker runs my memory goes up gradually by 0.1-0.50 and does not go back down. Memory is not being released could be please be fixed? the application is turning to google chrome

**Comment by networkimprov** [comment]
Could you fill out the new-issue template, and provide a complete Go program that demonstrates this? That would let us track down a Go bug, or point out any mistakes in your code. Thanks!

@gopherbot add WaitingForInfo

**Comment by ianlancetaylor** [comment]
Note that the docs for `time.NewTicker` clearly say "Stop the ticker to release associated resources."

**Comment by Dontmindmes** [comment]
There is also a very high CPU usage of 13%

**Comment by ianlancetaylor** [comment]
At the moment there is no action we can take here.  If you want to help us fix something, please provide a test case that we can run to see the problem.  Thanks.
