### ISSUE TITLE
cmd/go: -o option to go build not accepted at end

### ISSUE THREAD

**Issue by kjk** [golang/go#40402]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\kjk\AppData\Local\go-build
set GOENV=C:\Users\kjk\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\kjk\go
set GOPRIVATE=
set GOPROXY=direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\kjk\AppData\Local\Temp\go-build301216802=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

This used to work (in 1.13, I think) but fails in 1.14.4:

```
> go.exe build -tags api -trimpath  -o ..\presstige_api.exe .
can't load package: package -o is not in GOROOT (c:\go\src\-o)
can't load package: package ../presstige_api.exe: cannot find package "." in:
        C:\Users\kjk\src\presstige\presstige_api.exe
```

Note: If I do `go build -o ...` it works.

Maybe putting `-o` option at end was never supposed to work but it is a regression.

**Comment by seankhliao** [comment]
This never worked
```
17:23:19 ~/testrepo-113 0:00:00
master » go1.11.13 build . -o out
can't load package: package -o: unknown import path "-o": cannot find module providing package -o
can't load package: package out: unknown import path "out": cannot find module providing package out

17:23:27 ~/testrepo-113 0:00:00
master » go1.12.17 build . -o out
can't load package: package -o: unknown import path "-o": cannot find module providing package -o
can't load package: package out: unknown import path "out": cannot find module providing package out

17:23:33 ~/testrepo-113 0:00:00
master » go1.13.10 build . -o out
can't load package: package -o: malformed module path "-o": leading dash
can't load package: package out: malformed module path "out": missing dot in first path element

17:23:40 ~/testrepo-113 0:00:00
master » go1.14.6 build . -o out
can't load package: package -o is not in GOROOT (/home/arccy/sdk/go1.14.6/src/-o)
can't load package: package out is not in GOROOT (/home/arccy/sdk/go1.14.6/src/out)
```

**Comment by jtarchie** [comment]
@seankhliao it looks like the report does have packages, the last `.` there.

**Comment by seankhliao** [comment]
ahh, in that case :shrug: The same command still works on linux

**Comment by bcmills** [comment]
I can only reproduce this on Linux if I add an explicit empty-string argument to the `-trimpath` flag.

```
example.com$ go build -tags api -trimpath  -o ..\whatever.exe .

example.com$ go build -tags api -trimpath '' -o ..\whatever.exe .
go: finding module for package ..whatever.exe
package -o is not in GOROOT (/usr/local/google/home/bcmills/sdk/gotip/src/-o)
malformed module path "..whatever.exe": leading dot in path element
```

**Comment by bcmills** [comment]
@kjk, does this still reproduce for you if you remove the doubled space after the `-trimpath` flag?
