### ISSUE TITLE
runtime: memory leak was observed in tcp client go program - RSS memory keeps growing

### ISSUE THREAD

**Issue by santhoshkarthi** [golang/go#40404]
### What version of Go are you using (`go version`)?

<pre>
go1.14.3

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

set GO111MODULE=
set GOARCH=arm
set GOBIN=
set GOCACHE=C:\Users\irhpoq\AppData\Local\go-build
set GOENV=C:\Users\irhpoq\AppData\Roaming\go\env
set GOEXE=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=linux
set GOPATH=D:\Karthik\Skills\Golang\GolangTraining-master
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set GOARM=7
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-fPIC -marm -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\irhpoq\AppData\Local\Temp\go-build269194878=/tmp/go-build -gno-record-gcc-switches
$ go env

</pre></details>

### What did you expect to see?
I see RSS memory (Physical RAM) memory was keep growing in the **"top"** in linux

### What did you see instead?
It should not grow

**Comment by santhoshkarthi** [comment]
Code : 
package main

import (
	"bufio"
	"fmt"
	"net"
	"time"
)

func tcpThread() {
	fmt.Println("Entered tcp Thread...")
	conn, err := net.Dial("tcp", "127.0.0.1:8081")
	if err != nil {
		fmt.Println(err)
		return
	}
	for {
		Msg := "This is just a message"
		fmt.Fprintf(conn, Msg+"\n")
		fmt.Println("Message was sent to tcp server...")
		message, _ := bufio.NewReader(conn).ReadString('\n')
		fmt.Print("Message from tcp server: " + message)
		time.Sleep(10 * time.Second)
	}
}

func main() {
	fmt.Println("Entered into main")
	go tcpThread()
	select {}
}

**Comment by santhoshkarthi** [comment]
I have just written in simple TCP client and it would send message to TCP server every 10 sec

**Comment by ianlancetaylor** [comment]
I doubt this is related to the problem, but the statement `bufio.NewReader(conn).ReadString('\n')` does not work correctly.  On a TCP connection this is going to read ahead and collect any data that follows the newline, and then it will throw it away.  You need to call `bufio.NewReader` outside of the loop.

**Comment by ianlancetaylor** [comment]
What does the TCP server do?

**Comment by davecheney** [comment]
Unrelated
```
	go tcpThread()
	select {}
```
rather than starting a goroutine then going to sleep; just call `tcpThread` directly from main.

**Comment by santhoshkarthi** [comment]
@ianlancetaylor 

TCP Server Code,
`package main

import (
	"bufio"
	"fmt"
	"net"
)

// only needed below for sample processing

func main() {

	fmt.Println("Launching server...")

	// listen on all interfaces

	ln, _ := net.Listen("tcp", ":8081")

	// accept connection on port
	defer ln.Close()
	conn, _ := ln.Accept()

	// run loop forever (or until ctrl-c)

	for {

		// will listen for message to process ending in newline (\n)

		message, err := bufio.NewReader(conn).ReadString('\n')
		if err != nil {
			fmt.Println(err)
			return
		}

		// output message received

		fmt.Print("Message Received: ", string(message))

		// sample process for string received

		newmessage := "success"

		// send new string back to client

		conn.Write([]byte(newmessage + "\n"))

	}

}
`

**Comment by davecheney** [comment]
@santhoshkarthi thank you for the code sample. 

Before we continue can you please check all error values in your sample code and address the issue @ianlancetaylor highlighted earlier,  https://github.com/golang/go/issues/40404#issuecomment-663901768

**Comment by santhoshkarthi** [comment]
@davecheney  sure I will check and let you know, Thanks for your support

**Comment by santhoshkarthi** [comment]
TCP Client
===========================
`package main

import (
	"fmt"
	"net"
	"time"
)

func tcpThread() {
	fmt.Println("Entered tcp Thread...")
	conn, err := net.Dial("tcp", "127.0.0.1:8081")
	if err != nil {
		fmt.Println(err)
		return
	}
	for {
		Msg := "This is just a message"
		fmt.Fprintf(conn, Msg+"\n")
		fmt.Println("Message was sent to tcp server...")
		time.Sleep(10 * time.Second)
	}
}

func main() {
	fmt.Println("Entered into main")
	go tcpThread()
	select {}
}
`
TCP Server.go
==========================
`package main

import (
	"bufio"
	"fmt"
	"net"
)

// only needed below for sample processing

func main() {

	fmt.Println("Launching server...")

	// listen on all interfaces

	ln, _ := net.Listen("tcp", ":8081")

	// accept connection on port
	defer ln.Close()
	conn, _ := ln.Accept()

	// run loop forever (or until ctrl-c)

	for {

		// will listen for message to process ending in newline (\n)

		message, err := bufio.NewReader(conn).ReadString('\n')
		if err != nil {
			fmt.Println(err)
			return
		}

		// output message received

		fmt.Print("Message Received: ", string(message))

	}

}
`

**Comment by santhoshkarthi** [comment]
TCP_server.go
=======================

`package main

import (
	"fmt"
	"net"
	"time"
)

func tcpThread() {
	fmt.Println("Entered tcp Thread...")
	conn, err := net.Dial("tcp", "127.0.0.1:8081")
	if err != nil {
		fmt.Println(err)
		return
	}
	for {
		Msg := "This is just a message"
		fmt.Fprintf(conn, Msg+"\n")
		fmt.Println("Message was sent to tcp server...")
		time.Sleep(10 * time.Second)
	}
}

func main() {
	fmt.Println("Entered into main")
	go tcpThread()
	select {}
}`

**Comment by santhoshkarthi** [comment]
@davecheney @ianlancetaylor  I removed below line, 
_bufio.NewReader(conn).ReadString('\n')_
Even after that my RSS memory is keep increasing

**Comment by santhoshkarthi** [comment]
Do I need to flush STDOUT buffer?

**Comment by davecheney** [comment]
No, stdout is not buffered in Go

**Comment by davecheney** [comment]
Thank you for your sample code. You called it tcp server but there is no server there, only a client which connects to 127.0.0.1:8081 and sends it a short string every 10 seconds.

**Comment by santhoshkarthi** [comment]
Sorry @davecheney  Yeah that is tcp client code, Now i dont see frequently increasing but slowly increasing after removing below line,
**"message, _ := bufio.NewReader(conn).ReadString('\n')"**

but tcp_server RSS memory is increasing quickly(every 1 sec increasing 4 bytes)

**Comment by santhoshkarthi** [comment]
TCP_Server code,
`package main

import (
	"bufio"
	"fmt"
	"net"
)

// only needed below for sample processing

func main() {

	fmt.Println("Launching server...")

	// listen on all interfaces

	ln, _ := net.Listen("tcp", ":8081")

	// accept connection on port
	defer ln.Close()
	conn, _ := ln.Accept()

	// run loop forever (or until ctrl-c)

	for {

		// will listen for message to process ending in newline (\n)
		message, err := bufio.NewReader(conn).ReadString('\n')
		if err != nil {
			fmt.Println(err)
			return
		}
		// output message received

		fmt.Print("Message Received: ", string(message))

		// sample process for string received

		//newmessage := "success"

		// send new string back to client

		//conn.Write([]byte(newmessage + "\n"))

	}

}
`

**Comment by davecheney** [comment]
Can you please post the version of the code with the error handling changes I suggested as well as addressing this line

> message, err := bufio.NewReader(conn).ReadString('\n')

Constructing a new bufio.Reader on each iteration is not correct.

**Comment by santhoshkarthi** [comment]
Are you asking for tcp_server or tcp_client or both?

**Comment by davecheney** [comment]
This code, https://github.com/golang/go/issues/40404#issuecomment-664416397

**Comment by santhoshkarthi** [comment]
@davecheney  if i move **"message, err := bufio.NewReader(conn).ReadString('\n')"**,  it is printing **"fmt.Print("Message Received: ", string(message))"** with last received message continuously

**Comment by davecheney** [comment]
That is expected. The mistake is you should not construct a NewRedeader inside the loop, construct it outside the loop then call ReadString inside the loop to read a line at a time.

**Comment by santhoshkarthi** [comment]
TCP_server code

` package main

import (
	"bufio"
	"fmt"
	"net"
)

// only needed below for sample processing

func main() {

	fmt.Println("Launching server...")

	// listen on all interfaces

	ln, _ := net.Listen("tcp", ":8081")

	// accept connection on port
	defer ln.Close()
	conn, _ := ln.Accept()

	// run loop forever (or until ctrl-c)
	message, err := bufio.NewReader(conn).ReadString('\n')
	if err != nil {
		fmt.Println(err)
		return
	}

	for {

		// will listen for message to process ending in newline (\n)
	
		// output message received

		fmt.Print("Message Received: ", string(message))

		// sample process for string received

		//newmessage := "success"

		// send new string back to client

		//conn.Write([]byte(newmessage + "\n"))

	}

}
`

**Comment by santhoshkarthi** [comment]
This is what you are asking me to do right @davecheney ?

**Comment by davecheney** [comment]
Please review https://github.com/golang/go/issues/40404#issuecomment-664425811

and confirm if the original problem is fixed.

**Comment by santhoshkarthi** [comment]
sure @davecheney I will check that, Thanks

**Comment by santhoshkarthi** [comment]
@davecheney yeah now it is somewhat okay but still it is slowly increasing, 
![image](https://user-images.githubusercontent.com/31926208/88556735-f8485700-d046-11ea-9855-caac2c6afb85.png)
after 5 mins, it was increased to "1920" bytes from 1888 bytes
![image](https://user-images.githubusercontent.com/31926208/88556804-0dbd8100-d047-11ea-9149-43e9505487f0.png)

**Comment by santhoshkarthi** [comment]
where as tcp_client was stable

**Comment by santhoshkarthi** [comment]
New TCP server code, based on your suggestion,
`
package main

import (
	"bufio"
	"fmt"
	"io"
	"net"
)

// only needed below for sample processing

func main() {

	fmt.Println("Launching server...")

	// listen on all interfaces

	ln, _ := net.Listen("tcp", ":8081")

	// accept connection on port
	defer ln.Close()
	conn, _ := ln.Accept()

	// run loop forever (or until ctrl-c)
	message := bufio.NewReader(conn)
	for {

		// will listen for message to process ending in newline (\n)

		// output message received

		msg, err := message.ReadString('\n')
		if len(msg) == 0 && err != nil {
			if err == io.EOF {
				break
			}
		}
		fmt.Print("Message Received: ", string(msg))

		// sample process for string received

		//newmessage := "success"

		// send new string back to client

		//conn.Write([]byte(newmessage + "\n"))

	}

}

`

**Comment by davecheney** [comment]
I believe those values are in kilobytes, so the process grew by 32 kilobytes in 5 minutes. Does it grow steadily, or are the jumps quantised? Does the growth continue if you leave the process? If you export `GODEBUG=gctrace=1` does the output match the growth in memory usage as reported by top?

**Comment by santhoshkarthi** [comment]
yeah it grows steadily, after I left the process ideal, now it grew up to 2164 KB from 1888KB, approx 300KB in 20 mins

**Comment by santhoshkarthi** [comment]
Attaching tcp_server code for your reference,
====================================
`package main

import (
	"bufio"
	"fmt"
	"io"
	"net"
)

// only needed below for sample processing

func main() {

	fmt.Println("Launching server...")

	// listen on all interfaces

	ln, _ := net.Listen("tcp", ":8081")

	// accept connection on port
	defer ln.Close()
	conn, _ := ln.Accept()

	// run loop forever (or until ctrl-c)
	message := bufio.NewReader(conn)
	for {

		// will listen for message to process ending in newline (\n)

		// output message received

		msg, err := message.ReadString('\n')
		if len(msg) == 0 && err != nil {
			if err == io.EOF {
				break
			}
		}
		fmt.Print("Message Received: ", string(msg))

		// sample process for string received

		//newmessage := "success"

		// send new string back to client

		//conn.Write([]byte(newmessage + "\n"))

	}

}
`

**Comment by santhoshkarthi** [comment]
Is this because I am creating new variable "msg, and err" everytime,
msg, err := message.ReadString('\n')
@davecheney

**Comment by davecheney** [comment]
I don’t think so, once that variable falls out of scope it’s storage should be freed by the garbage collector. The gctrace data I asked you to collect would confirm it. Do you have that data?

**Comment by santhoshkarthi** [comment]
@davecheney I am running GO program in imx6ul(ARMv7) embedded board, It does not have go compiler installed, I am just cross compiling go code in my Host PC and running it in my target. So is it possible to export "GODEBUG=gctrace=1" in the target

**Comment by davecheney** [comment]
yes, those variables affect the go binary at run time, https://godoc.org/runtime

**Comment by santhoshkarthi** [comment]
So I just add this line into my go code, **"GODEBUG=gctrace=1"**Would that work sir?

**Comment by davecheney** [comment]
This is an environment variable, export it in the same shell as you run the program.

**Comment by santhoshkarthi** [comment]
@davecheney , yeah I have exported it in my target linux machine, where would i get the expected result/output?

**Comment by davecheney** [comment]
It will be printed to stderr as the program runs. Consult the documentation for more detail, https://godoc.org/runtime.

**Comment by santhoshkarthi** [comment]
@davecheney Program is running for around 20 mins, and RAM memory was grew up from 4536KB to 4720KB but still there is no garbage collected message printed in the console, like "gc # @#s #%: #+#+# ms clock, #+#/#/#+# ms cpu, #->#-># MB, # MB goal, # P"
Is it possible to identify why RAM memory is growing

**Comment by davecheney** [comment]
It it likely that you did not correctly set the environment variable.

**Comment by santhoshkarthi** [comment]
"export=GODEBUG=gctrace=1" this is what i did

**Comment by davecheney** [comment]
Can you show what you did? A screenshot or a copy an paste of the terminal session if possible?

**Comment by santhoshkarthi** [comment]
root@ccimx6ulsbc:/home/root# export GODEBUG=gctrace=1

**Comment by davecheney** [comment]
Can you should me more? What happened after you set the environment variable and ran the program?

**Comment by santhoshkarthi** [comment]
after I set the variable and ran the program nothing was printed, I think i have mentioned that my Embedded board does not have GO compiler installed, I am just cross compiling in host machine and running the binary in my target,

**Comment by davecheney** [comment]
Yes, this is supported. 

To assist you we need to see more than one line. Please review https://github.com/golang/go/issues/40404#issuecomment-665058457

**Comment by davecheney** [comment]
Based on the discussion in #40448 I am closing this as a duplicate.
