### ISSUE TITLE
math/big: z.Exp(x, y, m) does not return, stuck in a dead loop 

### ISSUE THREAD

**Issue by rqg0717** [golang/go#40421]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\User\AppData\Local\go-build
set GOENV=C:\Users\User\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\Go\workspace
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\User\AppData\Local\Temp\go-build471823414=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

func main() {
z := big.NewInt(0)
x := big.NewInt(54493)
y := big.NewInt(2636432291)
z.Exp(x, y, nil) <- program stuck at here, running forever and does not return...
fmt.Println("result: ", *z)
}

### What did you expect to see?
expect to see  z = x**y 

### What did you see instead?
nothing...

**Comment by martisch** [comment]
Are you sure its stuck forever and not just taking a long time?
54493**2636432291 is going to be a huge number. Do you know any other programming language that is able to compute it in reasonable time on your computer?

(Im trying to compute the number of ram that is needed to present the number and will report back)

**Comment by martisch** [comment]
`54493 > 2**15 and 2636432291 > 2**31`. So we have `54493**2636432291 > (2**15)**(2**31)` = `2**(32.212.254.720)` which means at least 4.026.531.840 bytes ~= 4 gigabyte  to represent the number exactly in ram (uncompressed). Since we rounded down twice it might as well be 8 gigabyte ram and that doesnt count in overhead for internal datastructures. Computing the number converting it to base 10 and printing it out will take a while. If the base 10 is computed as a whole we need about a byte per character to represent around `log(10,2) ~= 3.32 bits` So we have `32.212.254.720 / log(10,2) ~= 32gigabyte` ram needed to represent and print the number in base 10.

**Comment by robpike** [comment]
Using ivy, we can easily calculate its logarithm base 2:

```
2636432291 * 2 log 54493
41481054344.5
```

So the number is 2 to the power of that, or 2**41,481,054,344.5 or 10 to the power of 12,487,041,609.5, more than 12 billion decimal digits. Your machine needs 41.4/8 or 5.2GB of memory just to hold the result. As is explained above, you really need much more than that, and converting it to decimal to print it.... well, it won't happy today.

**Comment by martisch** [comment]
Based on DDR4 system total memory bandwidth on a normal computer being about 32 gigabyte/sec from RAM If we assume doubling the number needs to be done at least 2**31 times and is done sequentially as a whole each time I guesstimate 4 years runtime. Surely cache local strategies will be able to improve on that on the other side the computer also needs to do the multiplications and write out the results so I think a few years give or take will be needed.

Does computing this number came up in a real world scenario or is based on some LeetCode question asking about the last digits of the result of this exponentiation?
https://github.com/rqg0717/LeetCode

**Comment by rqg0717** [comment]
> Using ivy, we can easily calculate its logarithm base 2:
> 
> ```
> 2636432291 * 2 log 54493
> 41481054344.5
> ```
> 
> So the number is 2 to the power of that, or 2**41,481,054,344.5 or 10 to the power of 12,487,041,609.5, more than 12 billion decimal digits. Your machine needs 41.4/8 or 5.2GB of memory just to hold the result. As is explained above, you really need much more than that, and converting it to decimal to print it.... well, it won't happen today.

How about a 256-bit big integer please? I need to calculate 256-bit int ** 256-bit int...

**Comment by rqg0717** [comment]
> Does computing this number came up in a real world scenario or is based on some LeetCode question asking about the last digits of the result of this exponentiation?
> https://github.com/rqg0717/LeetCode

I need it in https://github.com/rqg0717/Homomorphic-encryption in a real world scenario. Thank you.

**Comment by rqg0717** [comment]
> Are you sure its stuck forever and not just taking a long time?
> 54493**2636432291 is going to be a huge number. Do you know any other programming language that is able to compute it in reasonable time (how long does it take?) on your computer without filling up all the ram and e.g. swapping to disk which will make it even slower?

Yes, we have not faced any issue using C# in https://github.com/rqg0717/Homomorphic-encryption

**Comment by deltamualpha** [comment]
Your C# example is using https://en.wikipedia.org/wiki/Modular_exponentiation, not computing the exponent directly, which is the only way to achieve this in a reasonable time period for crypto purposes.

**Comment by dgryski** [comment]
In C# you're doing the modular reductions as the computation proceeds

```
BigInteger em = ((g.modPow(m, nsqr)) * (r.modPow(n, nsqr))) % nsqr;
```

In Go, you're doing all the math first and then the modular reduction.

```
gm.Exp(&g, m, nil)
rn.Exp(&rn, &n, nil) 
```

I believe this should be

```
gm.Exp(&g, m, &nsqr)
rn.Exp(&rn, &n, &nsqr) 
```

**Comment by rqg0717** [comment]
> In C# you're doing the modular reductions as the computation proceeds
> 
> ```
> BigInteger em = ((g.modPow(m, nsqr)) * (r.modPow(n, nsqr))) % nsqr;
> ```
> 
> In Go, you're doing all the math first and then the modular reduction.
> 
> ```
> gm.Exp(&g, m, nil)
> rn.Exp(&rn, &n, nil) 
> ```
> 
> I believe this should be
> 
> ```
> gm.Exp(&g, m, &nsqr)
> rn.Exp(&rn, &n, &nsqr) 
> ```

You are absolutely right! Thank you very much and sorry for the trouble.

**Comment by rqg0717** [comment]
> Your C# example is using https://en.wikipedia.org/wiki/Modular_exponentiation, not computing the exponent directly, which is the only way to achieve this in a reasonable time period for crypto purposes.

You are absolutely right! Thank you very much and sorry for the trouble.
