### ISSUE TITLE
proposal: encoding/json: add *json.Decoder to return type of DisallowUnknownFields

### ISSUE THREAD

**Issue by KaiserKarel** [golang/go#40443]
For strict json parsing using encoding/json, one has to write the following quite often:

```go
var mystruct Mystruct
decoder := json.NewDecoder(request.Body)
decoder.DisallowUnknownFields()
err := decoder.Decode(&mystruct)
```

Instead, being able to chain these calls makes the API more pleasant to use:

```go
var mystruct Mystruct
err := json.NewDecoder(request.Body)
    .DisallowUnknownFields()
    .Decode(&mystruct)
```

It's also less error prone, as the decoder cannot be reused. 

Technically this is a breaking change, since the DisallowUnknownFields might by passed as a function pointer, although I cannot imagine any use for that. Alternatively, We could add a `Strict` method to the decoder, to avoid breaking existing code.

**Comment by ianlancetaylor** [comment]
We can agree or disagree as to whether this would be a good idea, but it doesn't matter because we can't make this change.  It would break the Go 1 compatibility guarantee (https://golang.org/doc/go1compat).  Sorry.
