### ISSUE TITLE
x/tools/gopls: set up govim regression tests to run at govim@main

### ISSUE THREAD

**Issue by stamblerre** [golang/go#40451]
@heschik has mentioned that, now that we have our own regression tests, it feels like it's time to stop relying on the `govim` tests to run on each CL.

When the govim tests fail, we have started rewriting them into our own regression tests, which seems like the right approach. I think the govim tests are a little brittle - particularly because pinning a `govim` version means we don't get updates as we change `gopls`. For example, https://golang.org/cl/227033 can't be submitted because we need to bump the version of govim in our CI, but we can't bump the version because of other failures.

It is nice to be able to catch things earlier, so maybe we could have the govim tests running for `gopls` at master and present those results in a dashboard?

/cc @findleyr

**Comment by findleyr** [comment]
FWIW, we can easily set the up to run as a post-submit on master. Not sure about getting them in a public dashboard, however.

**Comment by stamblerre** [comment]
Post-submit sounds OK to me, as long as we have a good way to update to later versions of govim, etc. I'd just like to be able to submit breaking CLs without making our govim tests useless.

**Comment by findleyr** [comment]
> I'd just like to be able to submit breaking CLs without making our govim tests useless.

You mean 'useless' in the sense that they're already failing?  That will still happen if you submit a breaking CL... but I think you mean just that it would be good to keep things more closely in sync.  As long as you don't mind getting an email for every failure until things are fixed, I'll set them up to run gopls@master and govim@master.

**Comment by stamblerre** [comment]
> You mean 'useless' in the sense that they're already failing? That will still happen if you submit a breaking CL... but I think you mean just that it would be good to keep things more closely in sync.

Yeah exactly. Having them both run at master would be great, so then we can send a PR to govim whenever we make a breaking change.

**Comment by findleyr** [comment]
BTW, our current CI _is_ passing at govim@main, because we're running with `-short`. As part of switching to a different CI system, I think we can run all tests (not just --short), which will pull in some failing tests.

**Comment by stamblerre** [comment]
Agreed - let's do that.

**Comment by stamblerre** [comment]
@findleyr: Can this be closed now?

**Comment by findleyr** [comment]
Yup!
