### ISSUE TITLE
net/http: wrong/undocumented response behaviors when unsupported HTTP version is used

### ISSUE THREAD

**Issue by urbanishimwe** [golang/go#40454]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?
created a server with the most minimal configurations
```
package main

import (
        "fmt"
        "net/http"
)

func main() {
        if err := http.ListenAndServe(":8001", http.HandlerFunc(handler)); err != nil {
                fmt.Println(err)
        }
}

func handler(w http.ResponseWriter, r *http.Request) {
        fmt.Fprint(w, "")
}
```
made a TCP request
```
printf "GET / HTTP/2.0\r\nHOST: 127.0.0.1:80\r\n\r\n" | nc 127.0.0.1 8001
```

### What did you expect to see?
as in https://tools.ietf.org/html/rfc7231#section-6.6.6
```
505 HTTP Version Not Supported\r\n...
```

### What did you see instead?
```
HTTP/1.1 400 Bad Request: unsupported protocol version\r\nContent-Type: text/plain; charset=utf-8\r\nConnection: close\r\n\r\n400 Bad Request: unsupported protocol version
```
I think the server should also indicate the body length if there is any.

**Comment by networkimprov** [comment]
@gopherbot remove Documentation

**Comment by bcmills** [comment]
Please provide the steps to reproduce as a Go program, not (just) a Unix command-line. (How did you configure the server on the Go side?)

**Comment by urbanishimwe** [comment]
> (How did you configure the server on the Go side?)

Basic configurations like this can reproduce the error
```
package main

import (
        "fmt"
        "net/http"
)

func main() {
        if err := http.ListenAndServe(":8001", http.HandlerFunc(handler)); err != nil {
                fmt.Println(err)
        }
}

func handler(w http.ResponseWriter, r *http.Request) {
        fmt.Fprint(w, "")
}
```

**Comment by urbanishimwe** [comment]
@gopherbot remove WaitingForInfo

**Comment by bradfitz** [comment]
I'd never heard of 505. Seems fine.

/cc @neild

**Comment by urbanishimwe** [comment]
I think the `": unsupported protocol version"` after `"400 Bad Request"` shouldn't be there.
since the response has body, it could be nice to provide `Content-Length` header for easy parsing(?)
