### ISSUE TITLE
x/website: page showing .go source file under doc/articles has invalid link to documentation

### ISSUE THREAD

**Issue by selahaddinh** [golang/go#40471]
### What version of Go are you using (`go version`)?
not related

$ go version

</pre>

### Does this issue reproduce with the latest release?
not related

### What operating system and processor architecture are you using (`go env`)?
not related

### What did you do?
I was reading the code example at the following article:
https://golang.org/doc/articles/wiki/final.go
the link included at the beggining of the site didn t work:
the href at: 'Documentation: doc/articles/wiki'

### What did you expect to see?
I expected to see the the link to move me to the page :
  I expected link to redirect me to: 
golang.org/doc/articles/wiki/

### What did you see instead?
it sends me to: 
https://golang.org/pkg/doc/articles/wiki/
which is not avaliable :/

**Comment by dmitshur** [comment]
Thanks for reporting. This looks like a bug that needs to be fixed.

Where did you get to the URL https://golang.org/doc/articles/wiki/final.go from?

**Comment by selahaddinh** [comment]
From this article: https://golang.org/doc/articles/wiki/
         under, '**Try it out!**' section header 
                the href at '**Click here to view the final code listing**.' 
                        (<a href="final.go">Click here to view the final code listing.</a>)

**Comment by seankhliao** [comment]
Closing as this appears to have been fixed
