### ISSUE TITLE
cmd/go2go: generated code leads to cmd/compile internal error

### ISSUE THREAD

**Issue by griesemer** [golang/go#40486]
Extracted from crash 9 of #39634 :

https://go2goplay.golang.org/p/-YZdFhVx8UX

cc: @ianlancetaylor

**Comment by ianlancetaylor** [comment]
This does not get a compiler crash if I translate it and then `go build` with current tip.  So the crash will probably be fixed if we update dev.go2go to current mainline.

That said it does get an error with tip, so there is something wrong with the translation tool.

**Comment by ianlancetaylor** [comment]
Does not crash on tip.  Correctly gets an error.
