### ISSUE TITLE
x/tools/gopls: fail to recover from deletion of go.mod file

### ISSUE THREAD

**Issue by stamblerre** [golang/go#40487]
I deleted a `go.mod` file in a directory inside of GOPATH and got the following error message:

`[Trace - 01:33:15.594 AM] Received notification 'window/logMessage'.
Params: {"type":1,"message":"2020/07/30 01:33:15 The code in the workspace failed to compile (see the error message below).\nIf you believe this is a mistake, please file an issue: https://github.com/golang/go/issues/new.: stat /Users/rstambler/code/src/foo/go.mod: no such file or directory\n\tsnapshot=9\n\tdirectory=file:///Users/rstambler/code/src/foo\n"}`

**Comment by drgrib** [comment]
This is also happening for me in a Python directory in which I have no `.go` files.

**Comment by stamblerre** [comment]
@drgrib: It sounds like you're seeing this error as a result of a different issue (unless you deleted a `go.mod` file in this directory?). Do you mind filing a new issue so we can continue the discussion there?

**Comment by drgrib** [comment]
@stamblerre Actually, I just realized I had a subdirectory with a `.go` file in it I was unaware of, so I was mistaken.

**Comment by stamblerre** [comment]
@drgrib: Ok. If there's still a problem, please file a new issue so we can discuss there.
