### ISSUE TITLE
json.Rawmessage decodes `null` as `"null"`

### ISSUE THREAD

**Issue by ohait** [golang/go#40495]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

i can reproduce on `go version go1.14 linux/amd64`

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/oha/.cache/go-build"
GOENV="/home/oha/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/oha/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/oha/sdk/go1.13.1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/oha/sdk/go1.13.1/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build838880304=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```
package main

import (
        "encoding/json"
        "testing"
)

type Frame struct {
        Data json.RawMessage `json:"data"`
}

func TestJson(t *testing.T) {
        f := Frame{Data: nil}
        t.Logf("%#v (%q)", f, f.Data)

        j, _ := json.Marshal(f)
        t.Logf("json: %s", j)

        var f2 Frame
        json.Unmarshal(j, &f2)
        t.Logf("%#v (%q)", f2, f2.Data)
}
```

### What did you expect to see?

`f.Data` and `f2.Data` should be the same (nil)

### What did you see instead?
```
=== RUN   TestJson
--- PASS: TestJson (0.00s)
    json_test.go:14: main.Frame{Data:json.RawMessage(nil)} ("")
    json_test.go:17: json: {"data":null}
    json_test.go:21: main.Frame{Data:json.RawMessage{0x6e, 0x75, 0x6c, 0x6c}} ("null")
PASS
```
json.Unmarshal decode `null` as `"null"`

**Comment by ohait** [comment]
note, if `json:"data,omitempty"` than everything works as expected

**Comment by DisposaBoy** [comment]
I think you're just seeing the result of using the `%q` format which quotes things. Maybe you meant to use `%s`.

**Comment by ohait** [comment]
i included also the %#v which shows how `json.RawMessage(nil)` is turned into `json.RawMessage{0x6e, 0x75, 0x6c, 0x6c}` which are the ascii of `null`

**Comment by seankhliao** [comment]
I believe this is working as intended, `json.RawMessage` specifically means not to parse the data and store it as is in json

**Comment by ohait** [comment]
> I believe this is working as intended, `json.RawMessage` specifically means not to parse the data and store it as is in json

oh yes, i see it now. if further Unmarshalled, it returns nil.
