### ISSUE TITLE
cmd/compile: improve implementation of OFORUNTIL inductive fact detection 

### ISSUE THREAD

**Issue by randall77** [golang/go#40502]
This issue is for followon improvements to #40367. We had to disable some optimizations for that issue, which we should reenable/improve for 1.16.
@choleraehyq @zdjones @dr2chase @cherrymui

**Comment by choleraehyq** [comment]
I’ll do the isSameOrPlainSuccessor optimization and reenable these two test cases later.

**Comment by zdjones** [comment]
I see that we listed https://golang.org/cl/246157 as an update to this issue, not a fix. I think that should have been a fix.

 This issue was just to correct/reenable the OFORUNTIL fact detection that was made more conservative by the fix in #40367. 246157 corrected that logic.

**Comment by randall77** [comment]
Ok, closing.
