### ISSUE TITLE
why will the command "go mod tidy" download the dependencies?  

### ISSUE THREAD

**Issue by starichat** [golang/go#40508]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by cfclong** [comment]
just an official command to help you download dependency quickly

**Comment by cagedmantis** [comment]
We don't really use our issue tracker for questions. More people will see your question, and you will get better answers, if you ask on a forum rather than on the issue tracker. See https://golang.org/wiki/Questions.
