### ISSUE TITLE
cannot find package runtime/cgo (using -importcfg)

### ISSUE THREAD

**Issue by xijiz** [golang/go#40505]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.17 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xijiz/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/xijiz/repohub/bowen/backend"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build930370573=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

When I run `go run main.go`, I encountered the following problem:

```
# command-line-arguments
cannot find package runtime/cgo (using -importcfg)
cannot find package encoding/binary (using -importcfg)
/usr/local/go/pkg/tool/linux_amd64/link: cannot open file : open : no such file or directory
```

I have imported a binary-package named `gotvm.a` which calls C APIs.

I also checked the directory `ls /usr/local/go/pkg/linux_amd64/runtime`:

> cgo.a  debug.a  internal  pprof  pprof.a  race.a  trace.a

### What did you expect to see?
I want to run this program without error.

**Comment by cagedmantis** [comment]
For asking questions about learning the language, see one of our forums: https://golang.org/wiki/Questions. We only use this issue tracker for tracking bugs. People in the forums can explain what is happening here.
