### ISSUE TITLE
cmd/cgo: undefined reference to SINGLE function

### ISSUE THREAD

**Issue by Shanduur** [golang/go#40512]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/shanduur/.cache/go-build"
GOENV="/home/shanduur/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/shanduur/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build113119094=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Little bit of backstory:
- I started working with the GoCV, and I found I am missing one key feature for my project. I decided to implement it by myself, so I created a [fork](https://github.com/Shanduur/gocv/tree/features2d/drawMatches) and started writing it. I crumbled into some issues, that I fortunately fixed, but finally I am stuck with error. I am also using other functions calling CGO code from this particular file (`features2d.go`), and they are working as they should.

To reproduce the problem, install [my fork](https://github.com/Shanduur/gocv/tree/features2d/drawMatches) of GoCV (for example with `make install` after performing `go get` inside GoCV src folder) and try to run `cmd/hello-sift/main.go` file on `features2d/drawMatches` branch.

### What did you expect to see?

Working program, without compilation problem.

### What did you see instead?

```
$ go run ./cmd/hello-sift/main.go /home/shanduur/Pictures/box.png /home/shanduur/Pictures/box_in_scene.png
# gocv.io/x/gocv
/usr/bin/ld: $WORK/b032/_x006.o: in function `_cgo_9737641c630c_Cfunc_DrawMatches':
/tmp/go-build/cgo-gcc-prolog:333: undefined reference to `DrawMatches'
collect2: error: ld returned 1 exit status
```

**Comment by mdempsky** [comment]
It seems like you figured out the issue: https://github.com/Shanduur/gocv/commit/6ea721366e0bec264445ab226258ca0addf8c347

**Comment by mdempsky** [comment]
For posterity, the issue was features2d.h had:

```
extern "C" void DrawMatches(..., struct DMatch matches1to2[], ...);
```

but features2d.cpp had:

```
void DrawMatches(..., struct DMatches matches1to2, ...) { ... }
```

C++ allows function overloading, so the compiler treats this as a definition of a separate function from the one declared as `extern "C"`.

**Comment by Shanduur** [comment]
Yup, figured this out, it was my mistake. Thanks for help!

**Comment by mdempsky** [comment]
In the future, if you discover the root cause of an issue like this, it would be polite to update the issue with those further details. I spent a fair bit of time investigating and struggling to reproduce this issue before discovering you'd already fixed it.
