### ISSUE TITLE
Dockerfile build fails with unknown revision

### ISSUE THREAD

**Issue by kotyara85** [golang/go#40524]
We're using bitbucket and go get cannot fetch private repositories inside docker container.
git clone works just fine

### What version of Go are you using (`go version`)?

<pre>
1.13
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
linux x64

### What did you expect to see?
go get not failing

### What did you see instead?
go get fails with `unknown revision`

**Comment by networkimprov** [comment]
Did you see #27344 and other issues linked in that thread? I googled: golang bitbucket.

@gopherbot add WaitingForInfo

**Comment by kotyara85** [comment]
Im getting a different error. I can git clone with private key injected into the container

**Comment by networkimprov** [comment]
Did you review all comments in that issue and the linked issues?

In any case, you should give details on how to reproduce your problem in #25982, and post a pointer to that in #27344. Someone in one of those threads might be able to help.

Then please close this issue.

**Comment by ALTree** [comment]
No updates for almost a year, I think we can close here.
