### ISSUE TITLE
x/pkgsite: The Universal Permissive License (UPL) not detected

### ISSUE THREAD

**Issue by zehliu** [golang/go#40529]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/oracle/nosql-go-sdk/nosqldb?tab=doc
 
 
### What is your user agent?
 

 
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:68.0) Gecko/20100101 Firefox/68.0`
 
 
### Screenshot
 

 
https://pkg.go.dev/github.com/oracle/nosql-go-sdk/nosqldb?tab=doc

### What did you do?
 

 
Visit this page https://pkg.go.dev/github.com/oracle/nosql-go-sdk/nosqldb?tab=doc
 
### What did you expect to see?
 
The license is detected and the "Doc" tab shows documents.

Our repo github.com/oracle/nosql-go-sdk uses the The Universal Permissive License (UPL) license, can you make the license detector recognize the UPL license? Thanks.

You can get a copy of the license at https://github.com/oracle/nosql-go-sdk/blob/master/LICENSE.txt or https://oss.oracle.com/licenses/upl/ , or on the Open Source Initiative web site at https://opensource.org/licenses/UPL .

### What did you see instead?

_“Doc” not displayed due to license restrictions.
See our license policy._

**Comment by jba** [comment]
Docs are now visible.
