### ISSUE TITLE
syntax highlight for go doc

### ISSUE THREAD

**Issue by GopherJ** [golang/go#40525]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cheng/.cache/go-build"
GOENV="/home/cheng/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/cheng/go/1.14.4"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/cheng/.goenv/versions/1.14.4"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/cheng/.goenv/versions/1.14.4/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/cheng/Projects/Ubudu/Rust/sbl_manager/dispatcher/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build264484111=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

1. go doc time

### What did you expect to see?

syntax highlight

### What did you see instead?

no syntax highlight

**Comment by GopherJ** [comment]
There is a closed issue:

https://github.com/golang/go/issues/13178

It's really surprising that some members of golang think it's not useful to have syntax highlight. At least it helps to read...., I'm not sure how developers being able to read:

![image](https://user-images.githubusercontent.com/33961674/89102493-1547a600-d40a-11ea-9c6a-c0221637c34d.png)

**Comment by mvdan** [comment]
Please clarify how this issue is any different than the previous one. Simply disagreeing with an issue's outcome doesn't really add anything meaningful to the discussion. It most likely will be closed as well, as a duplicate.

If you want to make a strong case, what new are you bringing to the discussion that wasn't already brought up in the previous issue?

**Comment by GopherJ** [comment]
@mvdan Let's close it then since go isn't that open to community's requests.

**Comment by mvdan** [comment]
To be clear, that's not what I said. I only asked you to make a stronger case so that this issue isn't closed as a duplicate. It's your choice to draw your own conclusions or close the issue entirely, though :)
