### ISSUE TITLE
x/build: 3 of 6 corellium iOS and Android builders are missing

### ISSUE THREAD

**Issue by dmitshur** [golang/go#40523]
From https://farmer.golang.org#pools:

- host-android-arm64-corellium-android: 0/0 (3 missing)
- host-darwin-arm64-corellium-ios: 0/0 (3 missing)

Their results have stopped showing up on https://build.golang.org since around Jul 17.

/cc @znly per [builder owners](https://farmer.golang.org/builders). Are you able to take a look at this? Thanks.

/cc @cagedmantis @toothrot @andybons

**Comment by dmitshur** [comment]
These builders were added in #31722. Perhaps @znly isn't the best GitHub account to ping about this, because it's an organization.

/cc @eliasnaur @bradfitz @steeve Do you know who would be a good person to ping to look into this issue? Thank you.

**Comment by eliasnaur** [comment]
All the builders were turned off at Corellium. Perhaps someone on the Go team would like access to the Corellium dashboard for when it happens in the future? I'm not actively checking the build.golang.org dashboard.

**Comment by steeve** [comment]
Let me know if you need to add people to the org.

**Comment by dmitshur** [comment]
Thank you for looking at this issue. I see that some of the builders are back, although it seems to be 3 out of 6 in total so far:

```
host-android-arm64-corellium-android: 1/1 (2 missing)
host-darwin-arm64-corellium-ios: 0/2 (1 missing)
```

I think it's helpful to have more clarity about the builder owner. We do keep an eye on the build dashboard regularly, so it's okay if you don't do it. As long as we're able to reach the builder owner when we spot an issue, then us not having access is okay. If this happens more often, we can can revisit this.

Please let me know if you think we should change the current builder owner entry ([this](https://github.com/golang/build/blob/cc98a763482e7a1a92f2b0486b50a8b1155e5672/dashboard/builders.go#L566) line) to something that's better for the future.

**Comment by eliasnaur** [comment]
> Thank you for looking at this issue. I see that some of the builders are back, although it seems to be 3 out of 6 in total so far:
> 
> ```
> host-android-arm64-corellium-android: 1/1 (2 missing)
> host-darwin-arm64-corellium-ios: 0/2 (1 missing)
> ```
> 

FWIW, there are only two Android corellium hosts and two iOS corellium hosts.

> I think it's helpful to have more clarity about the builder owner. We do keep an eye on the build dashboard regularly, so it's okay if you don't do it. As long as we're able to reach the builder owner when we spot an issue, then us not having access is okay. If this happens more often, we can can revisit this.
> 
> Please let us know if you think we should change the current builder owner entry ([this](https://github.com/golang/build/blob/cc98a763482e7a1a92f2b0486b50a8b1155e5672/dashboard/builders.go#L566) line) to something that's better for the future.

I'd love someone on the Go team could do the resetting, which means someone should have access to the Corellium dashboard. I'm also ok doing the infrequent manual restarts.

Ideally, there should be external monitoring of Corellium and automatic restarts. Corellium is not really built for continuous integration. There's an ongoing lawsuit where Apple is trying to shut Corellium down, so motivation is low :)

**Comment by dmitshur** [comment]
> FWIW, there are only two Android corellium hosts and two iOS corellium hosts.

I see. That means we can update [`ExpectNum`](https://github.com/golang/build/blob/cc98a763482e7a1a92f2b0486b50a8b1155e5672/dashboard/builders.go#L568) accordingly.

> I'd love someone on the Go team could do the resetting, which means someone should have access to the Corellium dashboard. I'm also ok doing the infrequent manual restarts.
>
> Ideally, there should be external monitoring of Corellium and automatic restarts. Corellium is not really built for continuous integration. There's an ongoing lawsuit where Apple is trying to shut Corellium down, so motivation is low :)

Thanks for explaining.

Would you be able to send a CL adding a README https://github.com/golang/build/tree/master/env/corellium with a description of how to do the resets?

I'll close this issue since the builders are back. Thanks again.

**Comment by eliasnaur** [comment]
> Would you be able to send a CL adding a README https://github.com/golang/build/tree/master/env/corellium with a description of how to do the resets?
> 

Sure: https://go-review.googlesource.com/c/build/+/249358
