### ISSUE TITLE
x/tools/gopls: first change check is broken

### ISSUE THREAD

**Issue by tennashi** [golang/go#40531]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
tennashi@pon-home ~/c/s/g/g/t/gopls (master)> go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tennashi/.cache/go-build"
GOENV="/home/tennashi/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tennashi/code"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/tennashi/.asdf/installs/golang/1.14.4/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/tennashi/.asdf/installs/golang/1.14.4/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/tennashi/code/src/github.com/golang/tools/gopls/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build167933104=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I edited the file to match [this](https://github.com/golang/tools/blob/b5fad4ed8dd65a3d7aae567b1f4e751b8ca72837/internal/lsp/source/util.go#L201) regular expression.

### What did you expect to see?
[This](https://github.com/golang/tools/blob/b5fad4ed8dd65a3d7aae567b1f4e751b8ca72837/internal/lsp/text_synchronization.go#L149) notification is sent to the LSP client (I use [vim-lsp](https://github.com/prabirshrestha/vim-lsp)) only on the first edit.

### What did you see instead?
It was never sent.

The following patch should fix it.

```diff
diff --git a/internal/lsp/text_synchronization.go b/internal/lsp/text_synchronization.go
index 7fc4161a..d516775f 100644
--- a/internal/lsp/text_synchronization.go
+++ b/internal/lsp/text_synchronization.go
@@ -151,7 +151,9 @@ func (s *Server) didChange(ctx context.Context, params *protocol.DidChangeTextDo
                }); err != nil {
                        return err
                }
+               s.changedFiles[uri] = struct{}{}
        }
+
        return nil
 }

@@ -347,7 +349,7 @@ func (s *Server) wasFirstChange(uri span.URI) bool {
                s.changedFiles = make(map[span.URI]struct{})
        }
        _, ok := s.changedFiles[uri]
-       return ok
+       return !ok
 }

 func (s *Server) changedText(ctx context.Context, uri span.URI, changes []protocol.TextDocumentContentChangeEvent) ([]byte, error) {
```

**Comment by stamblerre** [comment]
Thanks for catching this! Please feel free to send your patch as a contribution.
