### ISSUE TITLE
pkg.go.dev | README is not rendered even with the MIT License

### ISSUE THREAD

**Issue by gkarthiks** [golang/go#40539]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

I have a go module github.com/gkarthiks/k8s-discovery with the `MIT License` and the README.md is not rendered in the pkg.go.dev site.

### What did you expect to see?

The readme to be rendered and displayed

### What did you see instead?

```README not displayed due to license restrictions. See our license policy.```

**Comment by icholy** [comment]
You need to tag a new release.

**Comment by gkarthiks** [comment]
got it. Let me close this for now and after my new release I can check again. Thanks @icholy
