### ISSUE TITLE
Makefile:81: recipe for target 'go-get' failed

### ISSUE THREAD

**Issue by manjeetsorout** [golang/go#40533]
go version:  go1.14 linux/amd64

my gopath is correct but i'm still getting the following error:

make
  >  Checking if there is any missing dependencies...
package go.mongodb.org/mongo-driver/bson: /home/manjeet-profedge/golib/iamserverBitBucket/paceiam/src/go.mongodb.org/mongo-driver exists but /home/manjeet-profedge/golib/iamserverBitBucket/paceiam/src/go.mongodb.org/mongo-driver/.git does not - stale checkout?
package go.mongodb.org/mongo-driver/bson/primitive: cannot find package "go.mongodb.org/mongo-driver/bson/primitive" in any of:
        /usr/local/go/src/go.mongodb.org/mongo-driver/bson/primitive (from $GOROOT)
        /home/manjeet-profedge/golib/iamserverBitBucket/paceiam/src/go.mongodb.org/mongo-driver/bson/primitive (from $GOPATH)
package go.mongodb.org/mongo-driver/mongo: cannot find package "go.mongodb.org/mongo-driver/mongo" in any of:
        /usr/local/go/src/go.mongodb.org/mongo-driver/mongo (from $GOROOT)
        /home/manjeet-profedge/golib/iamserverBitBucket/paceiam/src/go.mongodb.org/mongo-driver/mongo (from $GOPATH)
package go.mongodb.org/mongo-driver/mongo/options: cannot find package "go.mongodb.org/mongo-driver/mongo/options" in any of:
        /usr/local/go/src/go.mongodb.org/mongo-driver/mongo/options (from $GOROOT)
        /home/manjeet-profedge/golib/iamserverBitBucket/paceiam/src/go.mongodb.org/mongo-driver/mongo/options (from $GOPATH)
package golang.org/x/crypto/bcrypt: /home/manjeet-profedge/golib/iamserverBitBucket/paceiam/src/golang.org/x/crypto exists but /home/manjeet-profedge/golib/iamserverBitBucket/paceiam/src/golang.org/x/crypto/.git does not - stale checkout?
Makefile:81: recipe for target 'go-get' failed
make: *** [go-get] Error 1

**Comment by mvdan** [comment]
You didn't fill the issue template, and this contains nearly no useful information for a bug report, so I'm closing this.

In the future, remember that the Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
