### ISSUE TITLE
x/tools/gopls: expensive `go list` process on startup

### ISSUE THREAD

**Issue by GAZ082** [golang/go#40530]
### What version of Go are you using (`go version`)?
<pre>
go version go1.14.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gabriel/.cache/go-build"
GOENV="/home/gabriel/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="github.com/GAZ082/*"
GONOSUMDB="github.com/GAZ082/*"
GOOS="linux"
GOPATH="/home/gabriel/go"
GOPRIVATE="github.com/GAZ082/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build770371537=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Hi. I open a project and after gopls loads for some reason the process "go -list" start to consume a lot of CPU and memory. I kill the go process and restart the language server and again starts to consume CPU and mem. If I leave it alone it may very well fill up my 16 GB of ram.
Check gif:

![gocrazy](https://user-images.githubusercontent.com/100194/89115217-1c979f80-d45c-11ea-9b87-760e257aa95a.gif)

### What did you expect to see?
Not a go process running rogue, that's for sure.

### What did you see instead?
A rogue go process!

**Comment by stamblerre** [comment]
@GAZ082: Are you opening `gopls` at the root of a very large module? The `go list` call on startup is used to load all of the code in your workspace, so it's likely to be expensive if there are a lot of packages there. If you are working in a public repository, can you please share a repro case?

**Comment by GAZ082** [comment]
> @GAZ082: Are you opening `gopls` at the root of a very large module? The `go list` call on startup is used to load all of the code in your workspace, so it's likely to be expensive if there are a lot of packages there. If you are working in a public repository, can you please share a repro case?

Thanks Reb, I'll double check and get you back.

**Comment by GAZ082** [comment]
Cant replicate. Will close. Thanks!
