### ISSUE TITLE
x/xerrors: tests broken (via vet error) with go1.15rc1

### ISSUE THREAD

**Issue by rhysh** [golang/go#40536]
### What version of Go are you using (`go version`)?

<pre>
$ go1.15 version
go version go1.15rc1 darwin/amd64
$ go1.14 version
go version go1.14.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

The issue is present in the latest release candidate, go1.15rc1. It is a regression from the latest release, go1.14.6.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rhys/Library/Caches/go-build"
GOENV="/Users/rhys/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/rhys/go/pkg/mod"
GONOPROXY="*"
GONOSUMDB="*"
GOOS="darwin"
GOPATH="/Users/rhys/go"
GOPRIVATE="*"
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/tmp/xerr/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/49/zmds5zsn75z1283vtzxyfr5hj7yjq4/T/go-build982147191=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
$ mkdir /tmp/xerr && cd /tmp/xerr && go mod init xerr
go: creating new go.mod: module xerr

$ go get golang.org/x/xerrors@master
go: golang.org/x/xerrors master => v0.0.0-20191204190536-9bdfabe68543

$ go1.15 test golang.org/x/xerrors
# golang.org/x/xerrors_test
/Users/rhys/go/pkg/mod/golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543/fmt_test.go:398:43: Sprint arg e causes recursive call to Error method
FAIL	golang.org/x/xerrors [build failed]
FAIL

$ go1.14 test golang.org/x/xerrors
ok  	golang.org/x/xerrors	0.302s

$ go1.15 version
go version go1.15rc1 darwin/amd64

$ go1.14 version
go version go1.14.6 darwin/amd64
```

### What did you expect to see?

I expected the tests for the golang.org/x/errors package to succeed without errors.

### What did you see instead?

A new vet check in Go 1.15, enabled by default when running tests, detects what looks like a bug in a type that x/xerrors defines for the purpose of testing itself. https://github.com/golang/xerrors/blob/9bdfabe68543/fmt_test.go#L398

**Comment by bcmills** [comment]
I can reproduce this locally using `go1.15rc1`. Should be an easy fix.

**Comment by bcmills** [comment]
`release-blocker` for Go 1.15 via #11811.

**Comment by bcmills** [comment]
CC @toothrot

**Comment by bcmills** [comment]
Should be fixed at head, but may need a backport to `release-branch.go1.15`.

#37020 is the issue to add this repo to the build dashboard.

**Comment by bcmills** [comment]
@gopherbot, please backport to 1.15.
