### ISSUE TITLE
all: Add copyright title to file

### ISSUE THREAD

**Issue by QiangHeisenberg** [golang/go#40540]
Some files lack copyright titles, do they not need to be added? Or is copyright restricted? In addition, I want to know how the year is determined.

Files lacking copyright titles such as:
src/runtime/pprof/internal/profile/proto_test.go
src/runtime/pprof/label.go
src/runtime/defs_linux_arm.go
src/runtime/defs_linux_arm64.go
src/runtime/defs_linux_amd64.go
...
There are a lot more. Need to add? I am very happy to do this job. Thank you.

**Comment by davecheney** [comment]
> src/runtime/pprof/internal/profile/proto_test.go

This file does not appear to exist at head

> src/runtime/pprof/label.go

This file carries a copyright message at head

> src/runtime/defs_linux_arm.go

This file requires a copyright header, I cannot advise you on the correct date, I suggest making your best guess and discussing it in code review.

> src/runtime/defs_linux_arm64.go

This file may be auto generated according to the current comment. 

> src/runtime/defs_linux_amd64.go

ditto

/cc @dmitshur

**Comment by QiangHeisenberg** [comment]
thank you, @davecheney ,Thank you for your reply.
