### ISSUE TITLE
cmd/go: regression in behavior of DepsErrors

### ISSUE THREAD

**Issue by dominikh** [golang/go#40544]
The behavior of the DepsErrors field in the output of `go list -json -e` has changed between Go 1.14 and tip.

In GOPATH-mode, have two packages `sandbox/foo` and `sandbox/bar`, with `sandbox/foo/foo.go` containing

```
package pkg

import "sandbox/bar"
```

and `sandbox/bar/bar.go` containing 

```
ackage bar
```

Running `go list -e -json .` in `sandbox/foo` with Go 1.14.4 would produce the following DepsErrors:

```
	"DepsErrors": [
		{
			"ImportStack": [
				"sandbox/foo",
				"sandbox/bar"
			],
			"Pos": "foo.go:3:8",
			"Err": "\n../bar/bar.go:1:1: expected 'package', found ackage"
		}
	],
```

the ImportStack would clearly indicate that this issue occurs in the sandbox/bar package.

However, running the same command with tip (f92337422ef2ca27464c198bb3426d2dc4661653) produces the following output:

```
	"DepsErrors": [
		{
			"ImportStack": [
				"sandbox/foo"
			],
			"Pos": "foo.go:3:8",
			"Err": "expected 'package', found ackage"
		}
	],
```

the ImportStack is truncated, and it is impossible to tell which package the error is coming from. This was caused by 641918ee09cb44d282a30ee8b66f99a0b63eaef9 (/cc @matloob). 

Interestingly, between 1.14 and 641918ee09cb44d282a30ee8b66f99a0b63eaef9, 74d6de03fd7db2c6faa7794620a9bcf0c4f018f2 _improved_ on the error, by using a more accurate value for Pos:

```
	"DepsErrors": [
		{
			"ImportStack": [
				"sandbox/foo",
				"sandbox/bar"
			],
			"Pos": "../bar/bar.go:1:1",
			"Err": "expected 'package', found ackage"
		}
	],
```

**Comment by bcmills** [comment]
Just to set expectations, this may or may not make `go1.15rc2`. (I agree that it's a regression, but it doesn't seem severe enough to hold up the release if everything else is ready.)

CC @matloob @jayconrod
