### ISSUE TITLE
go/printer: comments were unexpected inserted in `import` decl

### ISSUE THREAD

**Issue by oraluben** [golang/go#40546]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.15beta1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yyc/Library/Caches/go-build"
GOENV="/Users/yyc/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/yyc/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/yyc/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/Users/yyc/go/go1.15beta1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/yyc/go/go1.15beta1/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/yyc/GolandProjects/fuzz-test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7y/t_wypjhs6hq78tzsj85w2xgw0000gn/T/go-build457538297=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://play.golang.org/p/65fHR5rtBXR

What I'm trying to do here is inserting an `import` decl in the front of a simple go source file, and as shown, an unexpected comment appeared in the middle of the inserted import, which breaks the source file.

### What did you see instead?
Buggy version and expected version (fixed with some ad-hoc logic) are both in the above link.

`<del>`
I believe what happened here is after remembering the offset of one comment at https://github.com/golang/go/blob/6f264801a76bbf1a0defacba4230efaefc47598c/src/go/printer/printer.go#L137, the offset will not be updated even if new content printed, so `commentBefore` https://github.com/golang/go/blob/6f264801a76bbf1a0defacba4230efaefc47598c/src/go/printer/printer.go#L153 will unexpected returns true for the next but not reached comment.
`</del>`

I can draft a patch if I'm not misunderstanding about the root cause.

update: the guess above is incorrect, still investigating.

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by dgryski** [comment]
Given that this breaks go-fuzz, does that increase the priority for 1.15 ?

**Comment by griesemer** [comment]
Just seeing this (I was on vacation last week). It's too later for 1.15.

**Comment by oraluben** [comment]
I think I can hardly say this is a bug in go/printer. For instance we have one comment at position n, and we inserted some statements without any position information just before n, it's hard to tell where should the comment be, in the middle of those inserted statements or after.

One workaround useful to go-fuzz would be giving all inserted statements a not accurate but less than position of subsequent comment. How this would work could be found at https://play.golang.org/p/KNEE2J4FrWt.
