### ISSUE TITLE
pkg.go.dev: defect rendering of readme.md

### ISSUE THREAD

**Issue by hhrutter** [golang/go#40547]
MacOS 10.4.16
Chrome: 84.0.4147.89
Go: go1.14.6 darwin/amd64

This issue is about package: https://github.com/pdfcpu/pdfcpu

### What did you expect to see?
The correct rendering of the readme: https://github.com/pdfcpu/pdfcpu

### What did you see instead?
A corrupt rendering of the readme; https://pkg.go.dev/mod/github.com/pdfcpu/pdfcpu

At the end of the readme there is a markdown table showing all contributors.
The rendering of this table seems to be corrupt.

**Comment by icholy** [comment]
You need to tag a new release.

**Comment by ALTree** [comment]
Didn't you already report this as #39297? 

If this is an additional issue, can you explain how?

**Comment by hhrutter** [comment]
Sorry, my bad!
I was unable to find out if I had already reported this.
I am gonna close this as #39297 is still pending.
Sorry again :(

**Comment by ALTree** [comment]
No problem. Thanks for checking!
