### ISSUE TITLE
doc/go1.15: add note about crypto/tls error wrapping change

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#40554]
After https://go-review.googlesource.com/c/go/+/227840 http.Client and tls.Client will now return an opaque `tls.permanentError` in place of what were previously public error types (i.e. `net.OpErr`). This means that in order to get the previously top level error users need to use `errors.As` (or `errors.Unwrap`) to get the useful error (best practice should presumably be to always use `errors.As` but directly casting to `net.OpErr` is definitely quite common).

cc @FiloSottile @katiehockman

**Comment by katiehockman** [comment]
Yeah that sounds good. I'll take care of that. Thanks @rolandshoemaker.

**Comment by UladBohdan** [comment]
Hi @rolandshoemaker @katiehockman 

I've noticed the original description of this issue refers to direct casting of errors to `net.OpError` type, I can see how it was affected and I can see how error check was modified in tests to handle new behaviour https://go-review.googlesource.com/c/go/+/227840/4/src/crypto/tls/handshake_server_test.go

However, I can't really see why the final description of the change https://go-review.googlesource.com/c/go/+/247698/4/doc/go1.15.html refers to assertion of `net.Error` type. From what I see, `net.Error` interface type was not really affected: new `permanentError` type also implements `net.Error`, therefore casting will not be broken https://go-review.googlesource.com/c/go/+/227840/4/src/crypto/tls/conn.go

Could you please explain this to me? Does go1.15 really affect `net.Error` but not other public error types from `net` package i.e. `net.OpError`?

**Comment by FiloSottile** [comment]
Yeah the release note should probably say "the original error" rather than "the original net.Error". I'll send a CL later if no one beats me to it.
