### ISSUE TITLE
cmd/go2go: unhelpful error message with generic map key type

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#40551]
For this test case:

```Go
package p

type Set[type T] map[T]bool

var V Set[func()]
```

the type checker reports

```
foo.go2:3:22: invalid map key type T
```

This is accurate but cryptic.  It would be better if the error message said something like `map key type T does not have comparable constraint`.

CC @griesemer

**Comment by griesemer** [comment]
Fixed by https://golang.org/cl/247258.
