### ISSUE TITLE
Option for Go-frame object file export

### ISSUE THREAD

**Issue by mcandre** [golang/go#40555]
.SO's, .OBJ's, etc. are great for inter-language usage!

But for Go plugins, it would be helpful to offer a Go-specific object file format.

That way, users don't always have to enable cgo in order to load Go plugins. They would have the choice of sticking to the tried and true C plugin interface, or running with pure Go plugins.

(Go may already have this? No clue.)

**Comment by ianlancetaylor** [comment]
It's a good idea but it's a huge project.  I don't think it's going to help to have an issue open for this without at least some sort of design.
