### ISSUE TITLE
x/pkgsite: make better use of horizontal space

### ISSUE THREAD

**Issue by andybons** [golang/go#40557]
With the new side navigation changes launched for documentation, we aren’t taking advantage of the amount of horizontal space we have (especially on wider viewports). This is to track investigating alternatives so that we can better use the space available.

https://stripe.com/docs/api does this rather well in my opinion.

**Comment by salewski** [comment]
It would be nice if something could be done to prevent the horizontal scrollbars and truncated content, as can be seen in the first screenshot below.

The page of the first screenshot is:
   * https://pkg.go.dev/golang.org/x/oauth2?tab=doc

The page in the first screenshot is at 100% zoom, in `chromium`.

**User-Agent:** `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36`

Despite there being tons of unused space on both sides of the page, the main content is still truncated. While I appreciate that overly wide columns of text are difficult to read, having the data truncated and needing to side-scroll -- especially multiple individual things to side-scroll -- is always worse.

![screenshot-horiz-scrolling](https://user-images.githubusercontent.com/997214/89590518-17e53980-d816-11ea-93cb-97c35671d290.png)

For the sake of comparison, below is a screenshot of that content on `godoc.org`, on the page:
   * https://godoc.org/golang.org/x/oauth2

There is less information displayed vertically, but none of it is truncated:

![screenshot-godoc org](https://user-images.githubusercontent.com/997214/89591623-a9ee4180-d818-11ea-86a1-2b4175a17e74.png)

**Comment by mholt** [comment]
Just found this, but also made a related comment at https://github.com/golang/go/issues/40612#issuecomment-670275328

**Comment by julieqiu** [comment]
In case anyone missed it, mocks for the CL above are at https://github.com/golang/go/issues/40612#issuecomment-675735671
