### ISSUE TITLE
Add highlight for golang code, golang doc/blog or go doc

### ISSUE THREAD

**Issue by laoshaw** [golang/go#40560]
Nearly all other languages have these and many of us are used to highlighted API, manpages, and webpages these days, they're essentially an extension to IDE, many could complain if IDE/vim/emacs/browser suddenly make the code and document black/white only.

Highlight improves readability and speed up the time to find key areas, please re-consider and add it to go doc from website and command line tools. Thank you.

**Comment by toothrot** [comment]
I'm sorry, it's not clear to me where you need this change to happen. Plenty of editors have support for highlighting Go code. This issue tracker is for problems with the Go tools and standard library.
