### ISSUE TITLE
x/build: freebsd-amd64-race builder should be updated to use a newer FreeBSD version

### ISSUE THREAD

**Issue by dmitshur** [golang/go#40562]
The `freebsd-amd64-race` builder currently uses `host-freebsd-11_1-big`. Go 1.13 and newer require FreeBSD 11.2 or newer. We should update this builder accordingly.

If our assumption is that newer stable releases of FreeBSD have fewer bugs, we should likely use the latest stable version we have a builder for, since the goal of a -race builder is to catch data races in the Go code.

/cc @toothrot @cagedmantis @andybons

**Comment by paulzhol** [comment]
@dmitshur I've updated `env/freebsd-amd64` to allow building a 11.3-RELEASE images in https://golang.org/cl/186038.
I should also test and add a 12.1-RELEASE now, with 12.2 due in two months. I can't create the images though, brad used to do it I think.

**Comment by problame** [comment]
@paulzhol What is the timeline for landing the 12.2 builder? I have reason to believe that there has been a regression in the Go runtime that leads to crashes starting with FreeBSD 12.2 ( #43873 ).

**Comment by paulzhol** [comment]
@problame I can't create the images in the project's internal GCP account. Ping @dmitshur,  @cagedmantis now that Go 1.16 is out maybe there's more time to add the builders.
Also FreeBSD 13.0 will be released in about a month now.

**Comment by dmitshur** [comment]
For now I'll resolve this specific issue by updating freebsd-amd64-race to use the available FreeBSD version, 12.0.

Please file a separate issue about adding new builders that target newer versions of FreeBSD. Thank you.

**Comment by paulzhol** [comment]
Thanks @dmitshur, I've opened created https://github.com/golang/go/issues/44431.
