### ISSUE TITLE
x/blog: Link does not exist given in blog post of playground

### ISSUE THREAD

**Issue by dsaw** [golang/go#40568]
### Does this issue reproduce with the latest release?
Issue is coming when reading blog post here - [https://blog.golang.org/playground](https://blog.golang.org/playground)

### What did you do?
Click on links given in the following section of post.

> The implementation can be found in [net_nacl.go](https://github.com/golang/go/blob/master/src/syscall/net_nacl.go#L461). A good place to start reading is [netFile](https://github.com/golang/go/blob/master/src/syscall/net_nacl.go), the network socket implementation of the fileImpl interface.

### What did you expect to see?
The implementation page on Github .

### What did you see instead?
Page not found

**Comment by ianlancetaylor** [comment]
I just want to mention that that blog post is describing an older version of the playground, not the one that is currently running.

**Comment by ianlancetaylor** [comment]
CC @andybons

**Comment by andybons** [comment]
Should be relatively easy to point to a previous commit (instead of master) where this file exists.

**Comment by ianlancetaylor** [comment]
I wonder if we should also add a note to the blog explaining that it does not describe the current version.

**Comment by andybons** [comment]
> I wonder if we should also add a note to the blog explaining that it does not describe the current version.

We should definitely do this.
