### ISSUE TITLE
x/pkgsite: documentation too large for google.golang.org/api/compute/v1

### ISSUE THREAD

**Issue by jba** [golang/go#40576]
https://pkg.go.dev/google.golang.org/api@v0.30.0/compute/v1?tab=doc says "documentation too large".

**Comment by jba** [comment]
The github.com/aws/aws-sdk-go/service/ec2 package also has doc too large to display.

**Comment by jba** [comment]
Also github.com/ying32/govcl/vcl/api.

The largest of these is the aws package, at over 15M.

**Comment by codyoss** [comment]
Another example, similar to original post: cloud.google.com/go/compute/apiv1/computepb

**Comment by seankhliao** [comment]
it works now

**Comment by jba** [comment]
Apparently compute is again too large.
