### ISSUE TITLE
x/tools/gopls: add documentation for eglot

### ISSUE THREAD

**Issue by ilohmar** [golang/go#40582]
### What version of Go are you using (`go version`)?
1.14.2
### Does this issue reproduce with the latest release?
yes
### What operating system and processor architecture are you using (`go env`)?
Linux amd64
### What did you do?
Look up Emacs integration documentation
### What did you expect to see?
At least a mention of the "eglot" package.
### What did you see instead?
Only the "lsp-mode" package.

Eglot works nicely with gopls.
To the best of my knowledge, lsp-mode will never be integrated more tightly with Emacs, while eglot is on track for that.
Please consider mentioning eglot in https://github.com/golang/tools/blob/master/gopls/doc/emacs.md.
With go-mode, eglot, and gopls properly installed, all it takes is
```elisp
(add-hook 'go-mode-hook #'eglot-ensure)
```
I can supply a config snippet to auto-format code (as in the lsp-mode config example) if it helps.

**Comment by muirdm** [comment]
That doc is community maintained, so please open a PR adding an eglot section. Thanks!

**Comment by muirdm** [comment]
The docs now contain info about eglot so I think this can be closed.

**Comment by ilohmar** [comment]
That's great, I (obviously) did not get to it...  Thanks a lot!
