### ISSUE TITLE
x/tour: Russian-language AppEngine app returns an error https://tour.golang.org/welcome/2

### ISSUE THREAD

**Issue by Fenimorkin** [golang/go#40591]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
I try to run Russian tutorial

### What did you see instead?
I found that 1.9 is depricated and tutorial doesnt work

**Comment by martisch** [comment]
Can you give a link to the russian tutorial that doesnt work?

**Comment by ALTree** [comment]
We don't control or deploy the tour translations. This should be reported to the Russian tour owner, at https://github.com/kalimatas/go-tour-ru.

**Comment by hyangah** [comment]
Some other translations linked from https://tour.golang.org/welcome/2 are not available either due to the same reason.
Should we file issues separately? 
Should we delete the links from the official tour sites if they don't respond?

**Comment by ALTree** [comment]
> Should we file issues separately?

I would file an issue in the tracker of the translations that don't work. Optionally, we could turn this one into a meta-issue to coordinate the effort, with a bulleted list of the external issue we opened.

**Comment by ALTree** [comment]
I've opened https://github.com/golang/tour/issues/1039 to track this. Closing here.
