### ISSUE TITLE
x/sys/unix: add Pipe2 function for Solaris

### ISSUE THREAD

**Issue by andy-js** [golang/go#40613]
The Pipe2 function is missing from the syscall package on Solaris.  Solaris has pipe2 so it could be added.

**Comment by andy-js** [comment]
See: https://github.com/golang/go/pull/40614

**Comment by tklauser** [comment]
The `syscall` package is frozen and no new functionality should be added to it (only bug fixes):

https://github.com/golang/go/blob/6f08e89ec3280bf6577c2bdb01243cbeeb1a259d/src/syscall/syscall.go#L21-L25

However, we may add `Pipe2` for Solaris to the `golang.org/x/sys/unix` package.

**Comment by andy-js** [comment]
I'll do that.  Thanks.

**Comment by tklauser** [comment]
We can leave this open to track the issue. Issues for `x/sys` are also in the Go issue tracker, denoted by the `x/sys`prefix in the subject line. Also see https://github.com/golang/sys#report-issues--send-patches
