### ISSUE TITLE
x/tools/gopls: hang saving files / 100% CPU on master/90696ccd

### ISSUE THREAD

**Issue by bmhatfield** [golang/go#40626]
### What version of Go are you using (`go version`)?

`go version go1.14.6 darwin/amd64`

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

OSX/x86_64

### What did you do?

I keep my local gopls regularly updated from `master`. Sometime in the past 24h, a commit was introduced that has caused significant performance / hanging issues with gopls for me locally. Nothing is logged when this happens.

Commits Tried:

`90696ccd` - hanging/100% CPU
`b4d825fe` - hanging/100% CPU
`d55f2edd` - hanging/100% CPU

`fec4f28e` - working normally

### What did you expect to see?

Normal gopls functionality.

### What did you see instead?

100% CPU in activity monitor, VSCode not performing autocompletes/cannot code navigate/cannot save files due to waiting for code actions.

**Comment by bmhatfield** [comment]
This *may* have been fixed in: https://github.com/golang/tools/commit/ee49e490f2e5ab5b4d84b0707a810bec7b25c65f - I am running from `9099c90c` and it seems to be working again.

**Comment by stamblerre** [comment]
Yep, that should be it. Sorry that you picked up that bug.
