### ISSUE TITLE
x/pkgsite: builtin should be ranked higher in search

### ISSUE THREAD

**Issue by komuw** [golang/go#40622]
# What is the URL of the page with the issue?
https://pkg.go.dev/search?q=builtin

# What is your user agent?
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.59 Safari/537.36

# screenshot
<img width="973" alt="Screenshot 2020-08-06 at 20 04 37" src="https://user-images.githubusercontent.com/5163857/89560694-191b6400-d820-11ea-8340-139bc01dca87.png">

# What did you do?
Visited the page.

# What did you expect to see?
The stdlib `builtin` package listed as the first result; https://pkg.go.dev/builtin/?tab=doc

# What did you see instead?
A list of packages, with the stdlib one not been one of them

**Comment by mvdan** [comment]
Perhaps this is because builtin is not a normal package, it's not a package you can import. So if they have any "sort by" parameters like "number of packages that import this package", then that should always be 0 for builtin.

**Comment by mvdan** [comment]
(To clarify, I agree this is likely a bug; I'm just guessing what the cause might be)

**Comment by Deleplace** [comment]
I had the same experience today, IMO we may indeed regard this as a bug.
