### ISSUE TITLE
x/tools/gopls: extract variable suggests extracting an *ast.ImportSpec

### ISSUE THREAD

**Issue by stamblerre** [golang/go#40635]
<img width="486" alt="Screen Shot 2020-08-07 at 2 01 09 AM" src="https://user-images.githubusercontent.com/5856771/89614197-f2762100-d851-11ea-83bd-5ff368c85dfc.png">

I actually would expect this to create a named import for me, which might be nice, but would requiring replacing all occurrences in the file.

/cc @joshbaum

**Comment by muirdm** [comment]
This already works with rename, right? I think that is a better fit than extract to variable.

**Comment by stamblerre** [comment]
Oh fair point, I forgot that rename handles that. Then we should just not support extraction here.

**Comment by joshbaum** [comment]
This is symptom of logic living in canExtractVariable. We check if it is an ast.Expr, but then leave the actual checking if its a valid ast.Expr type to extractVariable. This is why the lightbulb is on, but it won't actually do anything. Should we move this logic into canExtractVariable? We could just have a barebones switch statement in there that explicitly checks the type.

**Comment by stamblerre** [comment]
> EDIT: This is actually an *ast.BasicLit, not an *ast.ImportSpec. This is why the lightbulb is showing up. It does not actually extract anything because extractVariable does not find a place to insert the extraction. In pathEnclosingInterval -> path[0] is the basic lit and path[1] is the import spec. Do we want to special case this to prevent the lightbulb?

Yes, please - let's do that.
