### ISSUE TITLE
x/website/internal/dl: include docs on how to init datastore or memcache dependencies

### ISSUE THREAD

**Issue by kevinburke1** [golang/go#40630]
I am trying to make changes to the /dl page, but this page requires the ability to pull data from a memcache or Cloud datastore in order to render the page contents, and it does not look like there is documentation on how to put the necessary data in the Cloud datastore.

**Comment by dmitshur** [comment]
Unrelated to documentation, please be sure to discuss changes to the /dl page in an issue first.

**Comment by kevinburke** [comment]
My idea was to try to fall back to loading the release history from internal/history if the datastore is not initialized, but everything seems too tightly coupled to google cloud to make that work.

**Comment by dmitshur** [comment]
As of [CL 362496](https://go.dev/cl/362496) (CC @rsc), a copy of live server data is embedded in the `golangorg` binary, allowing the go.dev/dl/ page to be rendered and developed locally without needing to set up a datastore or memcache client. With that, I think this issue is resolved.
