### ISSUE TITLE
gollvm: set the shell variable correctly in CMakeLists.txt

### ISSUE THREAD

**Issue by timmyyuan** [golang/go#40631]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15rc1 gollvm LLVM 12.0.0git linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, I run the configure step of gollvm in a docker container (ubuntu 18.04), but fail with following logs:
```
-- Performing Test SPLIT_STACK_FUNCTIONAL
-- Performing Test SPLIT_STACK_FUNCTIONAL - Success
-- starting libgo configuration.
CMake Error at tools/gollvm/cmake/modules/GoVars.cmake:41 (message):
  fatal: shell missing or not functional
Call Stack (most recent call first):
  tools/gollvm/libgo/CMakeLists.txt:11 (include)


-- Configuring incomplete, errors occurred!
See also "/root/release/CMakeFiles/CMakeOutput.log".
See also "/root/release/CMakeFiles/CMakeError.log".
```

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I fetch a fresh gollvm to a docker container (ubuntu 18.04) then configure the building by
```
cmake ../llvm -DCMAKE_INSTALL_PREFIX=/root/gollvm -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_ASSERTIONS=On -DLLVM_ENABLE_RTTI=On -DLLVM_USE_LINKER=gold -G Ninja
```

### What did you expect to see?

no errors

### What did you see instead?

configuration failed

**Comment by timmyyuan** [comment]
The root cause is the ${shell} variable is incorrectly setting in CMakeLists.txt if there is no such a SHELL environment variable exists. I think I can submit a patch to fix this issue.

**Comment by ianlancetaylor** [comment]
CC @thanm @cherrymui

**Comment by thanm** [comment]
Yes please, feel free to submit a patch.  I seem to recall at least one other person running into this same issue. Another option would be to require folks to set SHELL prior to running cmake (e.g. update the build instructions).
