### ISSUE TITLE
%.2f exception

### ISSUE THREAD

**Issue by w22296437978** [golang/go#40648]
![image](https://user-images.githubusercontent.com/39508539/89701390-1ed09100-d969-11ea-8f9d-22348f255f5b.png)

**Comment by robpike** [comment]
The printed result is correct due to rounding. 0.505 will be rounded up to 0.51. The print routines round, they don't truncate.

Just for fun, I tried it in C as well, and `printf("%.2f\n", 1823.505)` prints `1823.51` in C too.

Working as intended.

**Comment by w22296437978** [comment]
> 由于四舍五入，打印结果正确。0.505将四舍五入为0.51。打印例行程序不会截断。
> 
> 只是为了好玩，我也在C语言中进行了尝试，并且也在C语言中进行了`printf("%.2f\n", 1823.505)`打印`1823.51`。
> 
> 按预期工作。

but 2.445 > 2.44

**Comment by w22296437978** [comment]
![image](https://user-images.githubusercontent.com/39508539/89701929-424a0a80-d96e-11ea-9048-8598cb2a28ac.png)
How could this be?

**Comment by robpike** [comment]
To avoid bias, rounding a number ending in the digit 5 alternates between rounding up and rounding down, which means that overall all rounded numbers, half round up and half round down.

1 2 3 4 round down.
6 7 8 9 round up
5 rounds up half the time and down half the time.

See this program:

```
package main

import (
	"fmt"
)

func main() {
	for _, x := range ([]float64{0.005, 0.015, 0.025, 0.035, 0.045, 0.055, 0.065, 0.075, 0.085, 0.095}) {
		fmt.Printf("%.2f\n", x)
	}
}
```

which prints

```
0.01
0.01
0.03
0.04
0.04
0.06
0.07
0.07
0.09
0.10
```

**Comment by ianlancetaylor** [comment]
https://cr.yp.to/2005-590/goldberg.pdf
