### ISSUE TITLE
gollvm: *** struct epoll_event data.fd offset unknown , while compiling on Windows 10 (64bit)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [golang/go#40656]
I will try to be short: I got the following, while running CMake, on "x64 Native Tools Command Prompt for VS 2019":

>cmake -DCMAKE_INSTALL_PREFIX='D:\' -DCMAKE_BUILD_TYPE=Release -DGOLLVM_DEFAULT_LINKER=link -G Ninja ../llvm-project/llvm

-- Looking for alloca - not found
-- Looking for memcpy
-- Looking for memcpy - not found
-- Performing Test HAVE_SYNC_BOOL_COMPARE_AND_SWAP_4
-- Performing Test HAVE_SYNC_BOOL_COMPARE_AND_SWAP_4 - Failed
-- Performing Test HAVE_SYNC_BOOL_COMPARE_AND_SWAP_8
-- Performing Test HAVE_SYNC_BOOL_COMPARE_AND_SWAP_8 - Failed
-- Performing Test HAVE_AS_X86_AES
-- Performing Test HAVE_AS_X86_AES - Failed
CMake Error at tools/gollvm/cmake/modules/AutoGenGo.cmake:386 (message):
  ***** struct epoll_event data.fd offset unknown**
Call Stack (most recent call first):
  tools/gollvm/libgo/CMakeLists.txt:323 (mkepoll)

I was tracking down to these lines - it could be related to one them:

[https://go.googlesource.com/gollvm/+/e5452d9188dade7d731f5c4b5b88d308d3383da6/cmake/modules/AutoGenGo.cmake#337
](https://go.googlesource.com/gollvm/+/e5452d9188dade7d731f5c4b5b88d308d3383da6/cmake/modules/AutoGenGo.cmake#337
)
[https://go.googlesource.com/gollvm/+/e5452d9188dade7d731f5c4b5b88d308d3383da6/cmake/modules/AutoGenGo.cmake#347](https://go.googlesource.com/gollvm/+/e5452d9188dade7d731f5c4b5b88d308d3383da6/cmake/modules/AutoGenGo.cmake#347)

Ivan

**Comment by cherrymui** [comment]
Currently gollvm does not support Windows, so it is expected not to work. If you want to work on it, that is great. Otherwise there is no need to file a bug report, as it is technically not a bug. Thanks.
