### ISSUE TITLE
question: What's the status of dropping the binary package?

### ISSUE THREAD

**Issue by cyantarek** [golang/go#40650]
Hi, our company uses the binary library heavily to encode and decode our custom made binary protocol over UDP.

I came across the issue where @rsc proposed to drop the binary package altogether.

As you already guessed, this will be a real problem for us. As we're planning to write more custom binary protocols for our internal use. And if the binary package is dropped, we got a real headache already.

So, may I know what's the final decision? And if you're gonna drop it, what should people like us do?

Thanks.

**Comment by ALTree** [comment]
> I came across the issue where @rsc proposed to drop the binary package altogether.

No such thing. 

You're probably thinking of #28152 (cmd/go: drop support for binary-only packages), which is a completely different thing (it's about binary-only Go packages, without source code). The `encoding/binary` package that you're using is not going anywhere. And it couldn't: Go has a strict [backward compatibility promise](https://golang.org/doc/go1compat):

> It is intended that programs written to the Go 1 specification will continue to compile and run correctly, unchanged, over the lifetime of that specification.

Your programs using `encoding/binary` are safe, and they'll keep working in the future.
