### ISSUE TITLE
proxy.golang.org: 

### ISSUE THREAD

**Issue by tiegz** [golang/go#40666]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.14.6
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="~/go/bin"
GOCACHE="~/Library/Caches/go-build"
GOENV="~/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="~/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lk/1yyswjf11xn090cy46x9387m0000gn/T/go-build733499197=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Fetch the versions for etcd via: `curl https://proxy.golang.org/github.com/etcd-io/etcd/@v/list`

### What did you expect to see?

I expected to see all published git tags of this module.

### What did you see instead?

I saw all tags except the `v3.4.*` tags (which started being published Aug 2019)

**Comment by andybons** [comment]
This looks to be https://github.com/etcd-io/etcd/issues/11154
