### ISSUE TITLE
cmd/go: limit simultaneous connections when downloading modules

### ISSUE THREAD

**Issue by bantl23** [golang/go#40671]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.14.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

New feature

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vagrant/.cache/go-build"
GOENV="/home/vagrant/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="aetd-git.gsfc.nasa.gov"
GONOSUMDB="aetd-git.gsfc.nasa.gov"
GOOS="linux"
GOPATH="/home/vagrant/go"
GOPRIVATE="aetd-git.gsfc.nasa.gov"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build974215287=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

go build -v

### What did you expect to see?

Modules downloaded properly

### What did you see instead?

Modules downloaded properly

### Feature request

We currently use go as for all of our code. We have go libraries as dependencies which use a private repository.  I have setup the `go env` `GOPRIVATE` correctly.

The server hosting our private repository currently only allows ssh connections to git. I have successfully setup git to pull modules over ssh using `git config --global url."git@<private_repo>:".insteadOf "https://<private_repo>/"`

However our IT policy stats that we can only have 10 simultaneous ssh connections to our git repository.

This policy is implemented using the 10:30:x where after 10 simultaneous connections the drop rate is 30%.

If any code has more than 10 libraries then our CI/CD pipeline fails because of that rule and because go build -v pulls dependencies simultaneously.

The feature I'm requesting is to somehow limit the number of simultaneously connections to a host when downloading modules.

What comes to mind is a command line option in `go mod download` to limit simultaneous connections or maybe an env variable.

Thanks for your consideration.

**Comment by bcmills** [comment]
@bantl23, as of https://go.dev/cl/473277 (Go 1.21) you should be able to set something like `GODEBUG=cmdgonetlimit=10` in your environment to limit the number of simultaneous connections.

Please give that a try, and if it works for you perhaps we can consider adding a flag for it instead of just a `GODEBUG`.
