### ISSUE TITLE
x/crypto/scrypt: memory not released after hash is calculated

### ISSUE THREAD

**Issue by cheng762** [golang/go#40687]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 linux/amd64
</pre>

### What did you do?

when I concurrent call   scrypt.Key   ,the memory not released after FreeOSMemory,here is the code
```
package main

import (
	"fmt"
	"log"
	"runtime/debug"
	"time"

	"golang.org/x/crypto/scrypt"
)

func main() {
	for i := 0; i < 30; i++ {
		go func() {
			key, _ := scrypt.Key(
				[]byte(""), // Input data.
				[]byte(""), // Salt.
				1<<18,      // Scrypt parameter N.
				16,         // Scrypt parameter r.
				1,          // Scrypt parameter p.
				64)         // Output hash length.

			fmt.Println(key)
		}()
	}

	time.Sleep(20 * time.Second)
	log.Println("free")
	debug.FreeOSMemory()

	// Keep the process running.
	time.Sleep(500 * time.Second)
}

```

**Comment by davecheney** [comment]
@cheng762 under linux we can only ask the operating system to take back memory from the processes address space, we cannot _tell_ the operating system to do this. The operating system can, and often does, ignore this request unless it is under memory pressure from other processes.

You can verify that the scavenger ran by exporting this environment variable `GODEBUG=gctrace=1` and running your process again. You will probably have to increase the amount of time to wait.

I encourage you to review #

**Comment by andybons** [comment]
@davecheney is correct. Closing for now as there does not seem to be anything to do. Please feel free to comment if you feel otherwise.
