### ISSUE TITLE
os/fsnotify: add new package

### ISSUE THREAD

**Issue by rsc** [golang/go#4068]
<pre>Issue for creating standard fsnotify package (current exp/inotify)</pre>

**Comment by rjeczalik** [comment]
Just in case someone lands here from the search there's also another library with API similar to `os/signal` - https://github.com/rjeczalik/notify.

**Comment by baptistedonaux** [comment]
Well ! It's a good new because only two libraries work but each has specific running (recursive or not…). Make a « official » lib is good to unify the golang environment. +1

**Comment by nathany** [comment]
At this point I don't know if it makes sense to have os/fsnotify in the standard library. Maybe an x/fsnotify package to benefit from Gerrit, the cross-platform builders, and the CLA process. That would also make it  more official, but without have a compatibility promise.

Whether that's based on the current revision of fsnotify or @rjeczalik's library, I'm not sure. I've been meaning to take a closer look at notify.

**Comment by nathany** [comment]
At this point, and in light of [burnout among the core team](https://github.com/golang/go/issues/17244#issuecomment-250284721), I think this issue can be safely closed. Please correct me if I'm wrong.

* With `internal/` packages, tools like guru, godoc, and even the go command can *technically* make use of fsnotify or @rjeczalik's notify without needing a public API in standard library or x/. 
* Fsnotify will remain under a BSD license (3-clause or 2-clause), but perhaps there is a caveat with the CLA situation if it is a non-Google project?
* In time, we will hopefully have a way to ensure that (foundational) libraries like fsnotify and grpc-go run everywhere that Go does. #17312

If anyone reading this has the bandwidth and interest in file system notifications, you are certainly welcome to contribute as much or little as you like over at https://github.com/fsnotify. Thanks.

**Comment by ALTree** [comment]
Closing this, as requested.
