### ISSUE TITLE
CGO_ENABLED=0 dial tcp: lookup example.com on 75.75.75.75:53: no such host

### ISSUE THREAD

**Issue by kotyara85** [golang/go#40686]
This error happens when the binary compiled with CGO_ENABLED=0 for darwin platform.
Possibly the same issue with linux & windows.

### What version of Go are you using (`go version`)?
<pre>
go version go1.13.10 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
CGO_ENABLED=0 go run main.go

### What did you expect to see?
No error

### What did you see instead?
FATA[2020-08-11T00:13:51-07:00] Get example.com: dial tcp: lookup example.com on 75.75.75.75:53: no such host

**Comment by davecheney** [comment]
The DNS server at 75.75.75.75:53 told your program that it did not have a record for example.com. 

Why do you think this is a problem with Go?

**Comment by kotyara85** [comment]
I changed a real hostname for security reasons. 
If I compile with CGO_ENABLED=1 it works just fine, so yes it’s a go issue.

**Comment by rsc** [comment]
I can't reproduce this problem using this program:

```
package main

import (
	"log"
	"net"
)

func main() {
	_, err := net.Dial("tcp", "www.google.com:80")
	if err != nil {
		log.Fatal(err)
	}
}
```

It succeeds with and without CGO_ENABLED=0. Do other host names resolve? Is the problem specific to 75.75.75.75?

**Comment by kotyara85** [comment]
We use akamai EAA client, that's when the error occurs. Only CGO_ENABLED=1 fixes this issue.

**Comment by davecheney** [comment]
It sounds like this specific client injects itself NSS, which requires your go binary to use the system libc name resolver. When cgo is disabled the system libc name resolver cannot be used as that requires cgo. 

Does this answer your question?

**Comment by mvdan** [comment]
Closing old issues that still have the WaitingForInfo label where enough details to investigate weren't provided. Feel free to leave a comment with more details and we can reopen.
