### ISSUE TITLE
go get -insecure no longer works properly

### ISSUE THREAD

**Issue by KlavsKlavsen** [golang/go#40688]
When running go get (using a proxy - http_proxy and https_proxy set), go get fails:
 Step 8/14 : RUN go get -v -t -insecure  .
 ---> Running in c5cda739048f
go: github.com/gkarthiks/k8s-discovery@v0.18.3: Get "https://proxy.golang.org/github.com/gkarthiks/k8s-discovery/@v/v0.18.3.mod": x509: certificate signed by unknown authority

Using golang:1.14-alpine image to build.

This seems that it should have worked - as far as I can tell, it was fixed atleast here: https://github.com/golang/go/issues/13197

**Comment by seankhliao** [comment]
please fill out the issue template next time

use [GOINSECURE](https://golang.org/doc/go1.14#go-env-vars)
