### ISSUE TITLE
cmd/compile: loops prevent bounds checking elimination

### ISSUE THREAD

**Issue by elichai** [golang/go#40704]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.14
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
If I do some copies between arrays with a loop like:
```go
func Convert(a *[32]byte, b *[4]uint64) {
	for i := 0; i < 4; i++ {
		binary.LittleEndian.PutUint64(a[i*8:], b[i])
	}
}
```
it bounds check on each array on every iteration.

but if I unroll it, it can figure out that it will never go out of bounds and eliminate the checks:
```go
func Convert(a *[32]byte, b *[4]uint64) {
		binary.LittleEndian.PutUint64(a[:], b[0])
		binary.LittleEndian.PutUint64(a[8:], b[1])
		binary.LittleEndian.PutUint64(a[16:], b[2])
		binary.LittleEndian.PutUint64(a[24:], b[3])
}
```
godbolt: https://godbolt.org/z/E3c5r4

This means that when implementing performance critical code (ie cryptography) I find myself unrolling loops of 8-16 because they end up on pprof which really sucks for readability

**Comment by randall77** [comment]
We don't propagate known ranges through multiplies at the moment. Shouldn't be too hard to do in prove.go.

**Comment by gtank** [comment]
Another cryptography implementer chiming in! It would be great to see this improved, and ideally for operations other than multiplication as well. It would specifically allow me to improve the readability of my code without suffering a notable (~30% on one task, see https://github.com/gtank/blake2/pull/2#discussion_r548232683) performance penalty for not unrolling the loop.
