### ISSUE TITLE
time: UnixNano thinks year 1 comes after 1720

### ISSUE THREAD

**Issue by vsekhar** [golang/go#40702]
UnixNano gives inconsistent results. Specifically, it believes the year 1 comes after the year 1720.

```
package main

import (
	"fmt"
	"time"
)

func main() {
	t1 := time.Date(1, 1, 1, 0, 0, 0, 0, time.UTC)
	t2 := time.Date(1720, 12, 30, 0, 0, 0, 0, time.UTC)
	t3 := time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC)	
	
	fmt.Printf("%s: %d\n", t1, t1.UnixNano())
	fmt.Printf("%s: %d\n", t2, t2.UnixNano())
	fmt.Printf("%s: %d\n", t3, t3.UnixNano())
}
```

```
0001-01-01 00:00:00 +0000 UTC: -6795364578871345152
1720-12-30 00:00:00 +0000 UTC: -7857820800000000000
1970-01-01 00:00:00 +0000 UTC: 0
```

https://play.golang.org/p/XrtNdpfNFk1

**Comment by andybons** [comment]
@ianlancetaylor

**Comment by ALTree** [comment]
You can't call UnixNano on a date before the year 1678; this is clearly documented:

https://golang.org/pkg/time/#Time.UnixNano

> UnixNano returns t as a Unix time, the number of nanoseconds elapsed since January 1, 1970 UTC. **The result is undefined if the Unix time in nanoseconds cannot be represented by an int64 (a date before the year 1678 or [...] )**

So your `t1.UnixNano()` call is not valid.

**Comment by vsekhar** [comment]
:facepalm: Thanks.
