### ISSUE TITLE
x/pkgsite: comments in example code are not visible

### ISSUE THREAD

**Issue by cgxeiji** [golang/go#40710]
Sometimes, adding comments to the examples can help illustrate how a package works.

While godoc.org shows comments in the [example code](https://godoc.org/github.com/cgxeiji/servo#ex-package), pkg.go.dev does not ([example code in pkg.go.dev](https://pkg.go.dev/github.com/cgxeiji/servo?tab=doc#example-package)) for the same package.

I do not know if this is intended behavior, or if comments in examples should be avoided.

Thank you

**Comment by dmitshur** [comment]
Thanks for reporting. Comments in the example code should be shown. They're shown on golang.org (x/tools/cmd/godoc) and on godoc.org (as you said). This looks like a bug in x/pkgsite.

/cc @julieqiu @jba @jamalc per [owners](https://dev.golang.org/owners).

**Comment by julieqiu** [comment]
Fixed.
