### ISSUE TITLE
x/pkgsite: landing page for docs provides no structural information at a glance.

### ISSUE THREAD

**Issue by empijei** [golang/go#40715]
This is a UX issue.

When reading docs on a package there are two important pieces of information a programmer is after: an overview (AKA the package comment) and a list of functions, types and their constructors.

When visiting the old godoc this is how it is presented:
![image](https://user-images.githubusercontent.com/1256049/89999733-7df71400-dc8f-11ea-8080-af04df4d7d5f.png)
As you can see there is the package name, the overview and at a glance you get all you need to construct and use types in the package.

When visiting the new pkg.go.dev this is what the user is presented with:
![image](https://user-images.githubusercontent.com/1256049/89999829-a4b54a80-dc8f-11ea-9a42-61c7396fbc34.png)
to get the same kind of information of the old doc the user has to click 9 times to expand all folded menus, and it uses *way* more space.
For a small package like `io` I had to flip my screen in vertical mode to take the screenshot below.
![image](https://user-images.githubusercontent.com/1256049/89999943-ca425400-dc8f-11ea-8c4b-e9acbc860e68.png)
Please also note that the only way to know the parameters of `NewSectionReader` is to hover it with the mouse as the left pane is not resizable.

It would be nice to have an overview of the package structure, types and functions at a glance, without having to dig into folds. This view:
![image](https://user-images.githubusercontent.com/1256049/90000594-ac292380-dc90-11ea-961f-9e62f7185860.png)
provides no information as it is going to be identical for every package I visit.

Note that this, at least for me, is a big enough reason to stop using pkg.go.dev since it does not provide the information I am always after, but this is a personal opinion and I don't know if others might feel the same.

**Comment by myitcv** [comment]
Possibly a dup of #40612?

**Comment by andybons** [comment]
@empijei I have a CL to expand all items by default. While I understand this doesn’t cover all of your concerns, would you consider that mitigation sufficient for this bug? We can track further improvements on #40612.

Let me know what you think.

**Comment by empijei** [comment]
This is indeed a dup of #40612, sorry for not finding it.

My bug also adds that the space taken by the fully expanded list is way more than it used to. I'll close this and add the comment on the other bug. Thanks.
