### ISSUE TITLE
doc: in 1.15 release notes, warn that -buildmode=pie will prevent static builds

### ISSUE THREAD

**Issue by ALTree** [golang/go#40719]
[From the Go1.15 release notes](https://golang.org/doc/go1.15#linker):

> The linker now defaults to internal linking mode for -buildmode=pie on linux/amd64 and linux/arm64 [...]

This means this classical incantation for static builds, that worked on Go1.14:

```
go build \
-buildmode pie \
-ldflags '-extldflags "-fno-PIC -static"' \
[...]
```

will instead *silently produce dynamically linked binaries* in Go 1.15.

We already had a report of a user that was stumped by the change: #40711. 

Should we warn about this in the linker section of the 1.15 release notes?

cc @ianlancetaylor @cherrymui @dmitshur

**Comment by cherrymui** [comment]
I don't think it prevent static build. You can still use external linking with `-ldflags=-linkmode=external` (which was the default in Go 1.14). In Go 1.15, we changed the default but not remove external linking.

Maybe the linker can warn if it is internal linking but `-extldflags` is specified? (Not sure, maybe there are tools that pass no-op `-extldflags` unconditionally.)

I'm not sure we need to update the release notes. We only changed the default, and `'-extldflags "-fno-PIC -static"' ` is already not the default, technically. Maybe we could add "External linking mode can still be requested with `-ldflags=-linkmode=external`".

**Comment by ALTree** [comment]
"will prevent static builds... unless you add an additional flag, that wasn't needed before" is what I meant. I know that you can still build static binaries. I'm just not sure that's easy to understand reading that sentence about the linker in the release notes.
