### ISSUE TITLE
x/pkgsite: remove package from go dev website

### ISSUE THREAD

**Issue by ZiyaoQiao** [golang/go#40733]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/mod/github.com/ZiyaoQiao/oci-go-sdk
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg/84.0.522.58
 
 
### Screenshot

![image](https://user-images.githubusercontent.com/13175637/90044678-d70c7b00-dc82-11ea-9957-ca41e7088e18.png)

 
### What did you expect to see?
 
Remove this package, it's not supposed to be visible

**Comment by andybons** [comment]
@jba @jamalc

**Comment by julieqiu** [comment]
Fixed.
