### ISSUE TITLE
GC test found very strange, do not understand

### ISSUE THREAD

**Issue by ruyi789** [golang/go#40734]
`package main

import (
	"fmt"
	"runtime"
	"time"
	"unsafe"
)

type ast struct {
	a int
}

func (a *ast) free() {
	cnt++
	fmt.Println("ast_free", unsafe.Pointer(a))
}

type bst struct {
	a *ast
	b **bst
}

func (b *bst) free() {
	cnt++
	fmt.Println("bst_free", unsafe.Pointer(b))
}

var cnt int

func testfreeCall2() {
	a := new(ast)
	b := new(bst)
	b.b = &b
	runtime.SetFinalizer(a, (*ast).free)
	runtime.SetFinalizer(b, (*bst).free)

	b.a = new(ast)                         //Try to block this
	runtime.SetFinalizer(b.a, (*ast).free) //Try to block this

	fmt.Println("testfreeCall2__", unsafe.Pointer(a), unsafe.Pointer(b), unsafe.Pointer(b.a))
}
func testfreeCall1() {
	a := new(ast)
	b := new(bst)

	runtime.SetFinalizer(a, (*ast).free)
	runtime.SetFinalizer(b, (*bst).free)
	b.a = new(ast)
	runtime.SetFinalizer(b.a, (*ast).free)

	fmt.Println("testfreeCall1__", unsafe.Pointer(a), unsafe.Pointer(b), unsafe.Pointer(b.a))
}

func main() {

	//testfreeCall1() //+3
	testfreeCall2() //+1
	//testfreeCall2() //+1
	testfreeCall1() //+3

	time.Sleep(1000 * 1000 * 100)
	for i := 0; i < 5; i++ {
		runtime.GC()
		fmt.Println("status:", cnt, i)
		time.Sleep(1000 * 1000 * 100)
	}

	fmt.Println("exit")
}
`

**Comment by martisch** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

See https://github.com/golang/go/wiki/Questions for ressources to ask questions.

**Comment by ruyi789** [comment]
is the GC bug

**Comment by randall77** [comment]
If you think there's a bug, please fill out the new issue template. In particular, what did you do? What did you expect to see? What did you see instead?
(If you have that, you can post it here and reopen this issue.)
