### ISSUE TITLE
cmd/go: create zip: malformed file path: invalid char '→'

### ISSUE THREAD

**Issue by ConnectionRefused** [golang/go#40749]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.14.7 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\rixCloud\AppData\Local\go-build
set GOENV=C:\Users\rixCloud\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOOS=windows
set GOPATH=D:\source
set GOPRIVATE=rixcloud.moe
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\rixCloud\AppData\Local\Temp\go-build047531450=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
```
go test
```

### What did you expect to see?
Repo can be imported as a dependency.

### What did you see instead?
![image](https://user-images.githubusercontent.com/52200558/90115755-1c19d580-dd87-11ea-82fc-ad8a46fd08a9.png)

**Comment by martisch** [comment]
Please specify the exact commands and sourcecode used to reproduce the error.
From the issue filed its unclear where go test was run and with which code.

**Comment by jayconrod** [comment]
I think this is working as intended: module paths may not contain the character `→`. I've copied the full list of requirements below.

If none of the module or package paths in this build actually contain the `→` character, please add enough information for us to reproduce the problem, and we can reopen this and investigate.

------

A module path must satisfy the following requirements:

* The path must consist of one or more path elements separated by slashes
  (`/`, U+002F). It must not begin or end with a slash.
* Each path element is a non-empty string made of up ASCII letters, ASCII
  digits, and limited ASCII punctuation (`+`, `-`, `.`, `_`, and `~`).
* A path element may not begin or end with a dot (`.`, U+002E).
* The element prefix up to the first dot must not be a reserved file name on
  Windows, regardless of case (`CON`, `com1`, `NuL`, and so on).

If the module path appears in a `require` directive and is not replaced, or
if the module paths appears on the right side of a `replace` directive,
the `go` command may need to download modules with that path, and some
additional requirements must be satisfied.

* The leading path element (up to the first slash, if any), by convention a
  domain name, must contain only lower-case ASCII letters, ASCII digits, dots
  (`.`, U+002E), and dashes (`-`, U+002D); it must contain at least one dot and
  cannot start with a dash.
* For a final path element of the form `/vN` where `N` looks numeric (ASCII
  digits and dots), `N` must not begin with a leading zero, must not be `/v1`,
  and must not contain any dots.
  * For paths beginning with `gopkg.in/`, this requirement is replaced by a
    requirement that the path follow the [gopkg.in](https://gopkg.in) service's
    conventions.
