### ISSUE TITLE
runtime: pcdata is -2 and 12 locals stack map entries error on nil pointer [1.15 backport]

### ISSUE THREAD

**Issue by randall77** [golang/go#40742]
@randall77 requested issue #40629 to be considered for backport to the next 1.15 minor release.

> This patch:
> ```
> +++ b/src/cmd/compile/internal/ssa/func.go
> @@ -274,6 +274,9 @@ func (f *Func) freeValue(v *Value) {
>         if len(v.Args) != 0 {
>                 f.Fatalf("value %s still has %d args", v, len(v.Args))
>         }
> +       if v == f.LastDeferExit {
> +               println("FREEING THE LASTDEFEREXIT")
> +       }
>         // Clear everything but ID (which we reuse).
>         id := v.ID
> ```
> triggers a bunch of times during make.bash. Both 1.14.2 and tip. Looks like we need to fix this for the release - I think we're just getting lucky that we don't stack copy or gc trace such cases normally (stack copy is only likely to happen with an unrecovered panic?), or that the random other instruction's liveness map is correct (or good enough).

**Comment by aclements** [comment]
@randall77 , how do you feel about backporting this given the relatively high complexity of the CL? Is there a simpler fix that might be safer to backport?

**Comment by randall77** [comment]
I don't think there's really anything simpler. I could revert a bunch of the code deletion, but since it isn't called anyway (and is buggy regardless) I'm not sure that would help. The actual code addition is small.
I'm open to suggestions though.

**Comment by randall77** [comment]
@dmitshur Why did this issue's fix not go out with 1.15.2? It looks like it didn't make it to CherryPickApproved, but why didn't it get to that state?

**Comment by dmitshur** [comment]
@randall77 For a backport issue to get to CherryPickApproved state, someone on the release team needs to approve it. We've discussed this issue in past release meetings but a decision hasn't been made yet (though we are quite close by now). If there is a backport issue that you believe is critical and a minor release should not be made without that backport issue being considered (and either approved, or we find agreement not to block on it), the release-blocker label should be used to indicate that.

Also please see what I wrote [here](https://groups.google.com/d/msg/golang-dev/6b-rdo-i8sA/mFNHbaIzAgAJ) about the timing of backport issues and minor releases.

**Comment by randall77** [comment]
Ok, just wanted to make sure it wasn't missed.

**Comment by toothrot** [comment]
Approved. This is a serious issue with no workaround. As @dmitshur said, sorry for the delay.
