### ISSUE TITLE
encoding/json: cyclic maps and slices are not detected

### ISSUE THREAD

**Issue by lujjjh** [golang/go#40745]
[The documentation](https://golang.org/pkg/encoding/json/#Marshal) says:

> JSON cannot represent cyclic data structures and Marshal does not handle them. Passing cyclic structures to Marshal will result in an error.

However, there are still cases result in an infinite recursion in Go 1.15.

It seems that 64c9ee9 does not handle cyclic maps or slices:

```go
package main

import "encoding/json"

func main() {
	x := map[string]interface{}{}
	x["x"] = x
	json.Marshal(x)
}
```

and

```go
package main

import "encoding/json"

func main() {
	x := []interface{}{nil}
	x[0] = x
	json.Marshal(x)
}
```

_Originally posted by @lujjjh in https://github.com/golang/go/issues/10769#issuecomment-673223740_

**Comment by mvdan** [comment]
I agree that this is probably a case we missed and should be fixed. Do you want to send a CL?

**Comment by eaglexiang** [comment]
great, new test case `TestSliceNoCycle` was created, but why there is no `TestSliceCycle` now and even no `TestPointerCycle` in the past.

**Comment by lujjjh** [comment]
> great, new test case `TestSliceNoCycle` was created, but why there is no `TestSliceCycle` now and even no `TestPointerCycle` in the past.

@eaglexiang Thank you for reviewing the code. Since marshalling cyclic structures results in a `UnsupportedValueError`, these cases are tested in `TestUnsupportedValues`.
