### ISSUE TITLE
x/pkgsite: overlarge box around the Example selector

### ISSUE THREAD

**Issue by pjweinb** [golang/go#40759]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/io/ioutil?tab=doc#example-WriteFile
 
### What is your user agent?
 

 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
 
 
### Screenshot

 
 
![image](https://user-images.githubusercontent.com/5406755/90159504-7ce0e800-dd5e-11ea-9066-50b55f55fb72.png)

 
### What did you do?
 

 
 search for ioutil. Under Examples, click on WriteFile. I get a box that includes a couple of lines of the documentation for WriteFile. If it goes away, clicking on whitespace right after 'permissions' brings it back.
 
### What did you expect to see?
 
 a smaller box or no box at all
 
### What did you see instead?
a box that is too large

**Comment by jamalc** [comment]
Closing this in favor of #42698.
