### ISSUE TITLE
x/pkgsite: no page description on Google search results

### ISSUE THREAD

**Issue by joshuabezaleel** [golang/go#40752]
### What is the URL of the page with the issue?
Example for package drijalva/jwt-go: https://www.google.com/search?q=dgrijalva+jwt+pkg+go+dev
 
 
### What is your user agent?
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
 
 
 
### Screenshot
 
![Screen Shot 2020-08-13 at 4 56 41 PM](https://user-images.githubusercontent.com/7043511/90122958-4b7d1200-dd88-11ea-98c1-0b2f7bf03d86.png)
![Screen Shot 2020-08-13 at 4 57 37 PM](https://user-images.githubusercontent.com/7043511/90122912-3d2ef600-dd88-11ea-960b-ea19df51837e.png)

 
### What did you do?
 
Search for "dgrijalva jwt-go pkg go dev" on Google. 
 
 
### What did you expect to see?
 
 Meta page description of the package on the Google search result. 
 
### What did you see instead?

No information/description of the package on the Google search result compared to the search result for the godoc.

**Comment by seankhliao** [comment]
I think also related, since the html description meta tag is the same for every page, it makes previews such as in slack hard to distinguish
![2020-08-13-185629](https://user-images.githubusercontent.com/11343221/90163808-e11f9e00-dd96-11ea-850b-30e4931cbdaa.png)
