### ISSUE TITLE
github api empty for releases

### ISSUE THREAD

**Issue by vvitayau** [golang/go#40768]
### What version of Go are you using (`go version`)?

https://api.github.com/repos/golang/go/releases is empty and does not match https://github.com/golang/go/releases 

### What did you expect to see?

```
$ curl --silent https://api.github.com/repos/golang/go/releases | jq -r '.[].name'
  go1.15
  go1.15rc2
  go1.14.7
  go1.13.15
  ...
```

### What did you see instead?

```
$ curl --silent https://api.github.com/repos/golang/go/releases
  [
  
  ]
```

**Comment by ALTree** [comment]
This is expected: we don't create github releases.

See #15966 for an issue tracking this.

**Comment by andybons** [comment]
This seems to be a GitHub UX issue, as we don’t create explicit GitHub releases, but they list the git tags.

Not sure what to do, here.

**Comment by networkimprov** [comment]
For a tag list: https://api.github.com/repos/golang/go/git/refs/tags
