### ISSUE TITLE
cmd/compile: build time increased in go 1.15

### ISSUE THREAD

**Issue by valenok-husky** [golang/go#40781]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.15 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

No.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/n.galushko/go/bin"
GOCACHE="/Users/n.galushko/Library/Caches/go-build"
GOENV="/Users/n.galushko/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/n.galushko/go/pkg/mod"
GONOPROXY="gitlab.inplatlabs.ru/*"
GONOSUMDB="gitlab.inplatlabs.ru/*"
GOOS="darwin"
GOPATH="/Users/n.galushko/go"
GOPRIVATE="gitlab.inplatlabs.ru/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/n.galushko/Projects/vkpay/go_vkpay/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2b/dlwj9v052dddcbf2lcxt0_lw0000gp/T/go-build902696119=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I compared three projects: remark42, kittenhouse, nda project (35k loc). I checked build time and binary size on my macbook pro 15 2017 i7 2.9Ghz. Build options: `go clean -cache && time go build`. See the result on chart (less is better).
<img width="724" alt="Снимок экрана 2020-08-13 в 22 12 32" src="https://user-images.githubusercontent.com/3104866/90222577-06eb8800-de15-11ea-8694-fce32da9cc9b.png">

### What did you expect to see?

Build time has not changed.

### What did you see instead?
Build time increased about 8-9%.

**Comment by seankhliao** [comment]
I don't see any slowdown

```
16:43:26 ~/remark42/backend/app
master » for i in {1..5}; do time go1.14.7 build -a ./... ; done
go1.14.7 build -a ./...  76.53s user 6.19s system 354% cpu 23.336 total
go1.14.7 build -a ./...  78.38s user 6.26s system 356% cpu 23.746 total
go1.14.7 build -a ./...  78.69s user 5.88s system 358% cpu 23.567 total
go1.14.7 build -a ./...  77.73s user 6.35s system 357% cpu 23.526 total
go1.14.7 build -a ./...  78.43s user 6.19s system 357% cpu 23.697 total

16:46:40 ~/remark42/backend/app
master » for i in {1..5}; do time go1.15 build -a ./... ; done
go1.15 build -a ./...  74.71s user 6.26s system 358% cpu 22.612 total
go1.15 build -a ./...  75.35s user 6.34s system 359% cpu 22.693 total
go1.15 build -a ./...  76.03s user 6.32s system 359% cpu 22.929 total
go1.15 build -a ./...  76.50s user 6.12s system 358% cpu 23.036 total
go1.15 build -a ./...  76.34s user 6.03s system 358% cpu 22.964 total

16:50:34 ~/remark42/backend/app
master » for i in {1..5}; do go clean -cache && time go1.14.7 build ./... ; done
go1.14.7 build ./...  47.73s user 3.49s system 346% cpu 14.779 total
go1.14.7 build ./...  48.94s user 3.43s system 348% cpu 15.026 total
go1.14.7 build ./...  48.57s user 3.41s system 349% cpu 14.860 total
go1.14.7 build ./...  48.11s user 3.56s system 349% cpu 14.779 total
go1.14.7 build ./...  48.25s user 3.30s system 348% cpu 14.778 total

16:51:58 ~/remark42/backend/app
master » for i in {1..5}; do go clean -cache && time go1.15 build ./... ; done
go1.15 build ./...  45.39s user 3.50s system 352% cpu 13.879 total
go1.15 build ./...  45.32s user 3.48s system 351% cpu 13.869 total
go1.15 build ./...  45.56s user 3.47s system 352% cpu 13.922 total
go1.15 build ./...  45.79s user 3.46s system 351% cpu 14.008 total
go1.15 build ./...  45.80s user 3.56s system 349% cpu 14.111 total
```

**Comment by valenok-husky** [comment]
Hmm… interesting. I installed golang from .dmg form official site. How did you install ?

**Comment by seankhliao** [comment]
`go get golang.org/dl/go1.x.y`

**Comment by valenok-husky** [comment]
Maybe. I can reinstall golang via your way and check build time the day after tomorrow.

**Comment by networkimprov** [comment]
Possibly due to #40727? 

@gopherbot add OS-Darwin
