### ISSUE TITLE
go/types, types2: type parameter order is significant when it should not be

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#40789]
commit 722af87f629540fdde659875619c3887831ffc10

The [following program](https://go2goplay.golang.org/p/OfHdYz3fQjT) fails with the error "K does not satisfy comparable", in the `copyMap` function definition when AFAICS `K` is declared correctly as having a comparable constraint.

```
package main

import "fmt"

func main() {
	m := map[string]int{
		"a": 6,
		"b": 7,
	}
	fmt.Println(copyMap[map[string]int, string, int](m))
}

type Map[K comparable, V any] interface {
	type map[K] V
}

func copyMap[M Map[K, V], K comparable, V any](m M) M {
	m1 := make(M)
	for k, v := range m {
		m1[k] = v
	}
	return m1
}```

If the type parameters are reordered to put `K` first, the example [works OK](https://go2goplay.golang.org/p/JwcN6NspdYu).

**Comment by AndrewWPhillips** [comment]
Here's something simpler to demonstrate the problem.
```
package main

type A[X comparable] interface {
	type []X
}

func f[B A[X], X comparable]() B {
	return nil
}

func main() {
}

```

**Comment by griesemer** [comment]
Thanks for this. Another case where the prototype type-checks too eagerly. This is a problem we need to solve in general in a real implementation (probably requires a two-phase approach). Addressing this should resolve a large number of bugs (not just with generics but elsewhere as well).

**Comment by griesemer** [comment]
The above CL fixes this issue for types2. The initial example still doesn't fully compile due to an unrelated error in the compiler.

**Comment by griesemer** [comment]
This was fixed in the type checkers by

https://golang.org/cl/331690 in `types2`
https://golang.org/cl/335034 in `go/types`
