### ISSUE TITLE
cmd/go2go: square bracket syntax doesn't work for multiple type arguments

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#40788]
commit 722af87f629540fdde659875619c3887831ffc10

The [following program](https://go2goplay.golang.org/p/m6URcAXsdNR) gives a syntax error. Using the round bracket syntax for instantiating the function works as expected. It appears that the parser doesn't allow the new square bracket syntax with multiple type parameters.

```
package main
import "fmt"

func main() {
	fmt.Println(double[int, int](24, 56))
}

func double[type T, S](x S, y T) (S, T) {
	return x, y
}
```

**Comment by ainar-g** [comment]
It [seems to work][1] if the declaration of `double` precedes its first use.

[1]: https://go2goplay.golang.org/p/paeGnsWUEMj

**Comment by ianlancetaylor** [comment]
The parser currently decides that it will use square brackets based on the first parameterized declaration.  If the first use of square brackets it is a use rather than a declaration, it doesn't always understand it.  This is a temporary hack until we settle on a syntax.
