### ISSUE TITLE
cmd/go2go: inappropriate "cannot use generic type without instantiation" error

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#40791]
commit 722af87f629540fdde659875619c3887831ffc10

The [following program](https://go2goplay.golang.org/p/5A19aNU-Uod) fails with the error "cannot use generic type Pair(type A, B) without instantiation", but the type does seem to be instantiated correctly.

```
package main
import "fmt"

func main() {
	fmt.Println(zeroS(int)())
}

type S(type T) struct {
	T T
}

func zeroS(type T)() S(T) {
	m := make([]S(T), 1)
	return m[0]
}
```

If we add a type alias, [it works](https://go2goplay.golang.org/p/sT4G8aR5R9z).

**Comment by ainar-g** [comment]
I don't know if it's related, but it [seems to work][1] when you use square brackets.

[1]: https://go2goplay.golang.org/p/A9ENcDxzKbm

**Comment by rogpeppe** [comment]
Ah, interesting! I was using round brackets because originally I had more than one type parameter so couldn't use square brackets because of issue #40788. https://go2goplay.golang.org/p/v35cQ-jcbEd

**Comment by ianlancetaylor** [comment]
Yes, this is the syntactic ambiguity of `[]S(T)` when using parentheses.  You have to write it as `[](S(T))`.  Or use square brackets.
