### ISSUE TITLE
x/tools/gopls: the code in the workspace failed to compile

### ISSUE THREAD

**Issue by kittyhappy** [golang/go#40790]
### What version of Go are you using (`go version`)?

<pre>
go version go1.15 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\www\AppData\Local\go-build
set GOENV=C:\Users\www\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=E:\GoProject\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\GoProject\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=E:\Go
set GOSUMDB=sum.golang.google.cn
set GOTMPDIR=
set GOTOOLDIR=E:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\www\AppData\Local\Temp\go-build025204942=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
when I use vscode open my gopath folder, it shows that The code in the workspace failed to compile (see the error message below) and go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- ./]: exit status 1: go: cannot find main module; see 'go help modules': packages.Load error.

**Comment by dmitshur** [comment]
Are you using the vscode-go extension? If so, what version is it?

Have you tried the troubleshooting steps described in https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md?

/cc @stamblerre

**Comment by hyangah** [comment]
Looks like `GO111MODULE=on` but there is no `go.mod` (i.e. `GOMOD=NUL`). 
Please see https://github.com/golang/vscode-go/issues/275#issue-648468015 and make sure to open vscode from the folder with `go.mod` file.

**Comment by mrlay** [comment]
i have met the same problems, version 0.16.1.  i have set go.mod file correctly(GOMOD is ok).  But the promotion is always occured when i open modify etc...

**Comment by stamblerre** [comment]
@mrlay: Please provide your `gopls` logs. Information on how to capture them can be found [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs).

**Comment by kittyhappy** [comment]
I have solved this question

> i have met the same problems, version 0.16.1. i have set go.mod file correctly(GOMOD is ok). But the promotion is always occured when i open modify etc...

I have solved this problem in vscode.In setting json,I add  "go.buildOnSave": "workspace",

**Comment by stamblerre** [comment]
Glad you were able to solve it. I'm going to close this issue. @mrlay, please file a new issue to continue this discussion.

**Comment by PICKQUE** [comment]
I also encountered the same type of error in the vscode and go plugins
my go env

> set GO111MODULE=on
> set GOARCH=amd64
> set GOBIN=
> set GOCACHE=C:\Users\admin\AppData\Local\go-build
> set GOENV=C:\Users\admin\AppData\Roaming\go\env
> set GOEXE=.exe
> set GOFLAGS=
> set GOHOSTARCH=amd64
> set GOHOSTOS=windows
> set GOINSECURE=
> set GONOPROXY=
> set GONOSUMDB=
> set GOOS=windows
> set GOPATH=E:\Go
> set GOPRIVATE=
> set GOPROXY=https://goproxy.cn,direct
> set GOROOT=D:\Go
> set GOSUMDB=sum.golang.org
> set GOTMPDIR=
> set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
> set GCCGO=gccgo
> set AR=ar
> set CC=gcc
> set CXX=g++
> set CGO_ENABLED=1
> set GOMOD=NUL
> set CGO_CFLAGS=-g -O2
> set CGO_CPPFLAGS=
> set CGO_CXXFLAGS=-g -O2
> set CGO_FFLAGS=-g -O2
> set CGO_LDFLAGS=-g -O2
> set PKG_CONFIG=pkg-config
> set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\admin\AppData\Local\Temp\go-build384423178=/tmp/go-build -gno-record-gcc-switches

`The code in the workspace failed to compile (see the error message below). If you believe this is a mistake, please file an issue: https://github.com/golang/go/issues/new. go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- ./]: exit status 1: go: cannot find main module; see 'go help modules' : packages.Load error`

**Comment by stamblerre** [comment]
@PICKQUE: Please make sure to open your workspace to your module root (the directory containing the `go.mod` file). This is currently a requirement of `gopls`, but we're working on changing that in future versions. If that doesn't resolve the problem, please file a new issue.

**Comment by mrlay** [comment]
@kittyhappy  thanks your advice, which help solve it.  @PICKQUE you can try create a  *.code-workspace project files, and add the configurations which @kittyhappy adviced, may be the case would be solved.

**Comment by PICKQUE** [comment]
> @PICKQUE: Please make sure to open your workspace to your module root (the directory containing the `go.mod` file). This is currently a requirement of `gopls`, but we're working on changing that in future versions. If that doesn't resolve the problem, please file a new issue.

i'm sure the root directory exist the go.mod and the go version is 1.15(i'm upgrade yesterday，but it's not work

**Comment by youguanxinqing** [comment]
> Looks like `GO111MODULE=on` but there is no `go.mod` (i.e. `GOMOD=NUL`).
> Please see [golang/vscode-go#275 (comment)](https://github.com/golang/vscode-go/issues/275#issue-648468015) and make sure to open vscode from the folder with `go.mod` file.

Wonderful! Solved my problem!

**Comment by azi-v** [comment]
> @PICKQUE: Please make sure to open your workspace to your module root (the directory containing the `go.mod` file). This is currently a requirement of `gopls`, but we're working on changing that in future versions. If that doesn't resolve the problem, please file a new issue.

I have sloved this problem by using `go mod init` command ;

**Comment by wenchao5211** [comment]
When I was developing Golang with Vscode on MacOS, vscode prompt  "The code in the workspace failed to compile (see the error message below). If you believe this is a mistake, please file an issue: https://github.com/golang/go/issues/new. go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- ./]: exit status 1: go: cannot find main module; see 'go help modules' : packages.Load error"
I have tried all the above solutions, but they still don't work. I am very upset. What should I do

**Comment by stamblerre** [comment]
@wenchao5211: Please follow the steps in the [troubleshooting guide](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md) and file a new issue so we can help you understand the problem.

**Comment by D4v1dW3bb** [comment]
I had the same problem. I found out that if first ran: go module init ....... Then found out that I had to set GO111MODULE to on. Still the same error. 
When removing the go.sum file  and re running go module init .......  Error was gone.

**Comment by StoryJC** [comment]
I also have this problem. How can I solve it?
The code in the workspace failed to compile (see the error message below). If you believe this is a mistake, please file an issue: https://github.com/golang/go/issues/new. go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- ./]: exit status 1: go: cannot find main module; see 'go help modules' : packages.Load error

**Comment by D4v1dW3bb** [comment]
> Unsupported
>
>  Open a directory that contains a module in a subdirectory. gopls will not work in this case.

For vscode I have a workaround, do not know if this work for other editors.

My directory structure is:

```
Projects
  Someproject1
    microservice1
      go.mod
      go.sum
      main.go
    microservice2
      go.mod
      go.sum
      main.go
  Someproject2
  ...
```
opening "Somepoject1" in vscode causes a problem.
To solve this I have made a second directory structure:

```
Workspaces
```
If i start working on a project for the first time I open the respective directory in "Workspace"s  in vscode. Then I save the workplace in the same place. Then I add al the microservice directories from the corresponding project directory in "Projects" to the workspace. When closing the workspace I save it.
If I want to start working on an existing workspace I choose open workspace and choose the right workspace file.

it's a little bit of work to setup but it works.

no errors any more

**Comment by A7cc** [comment]
Sorry, I got it resolved, but thank you very much!

---Original---
