### ISSUE TITLE
x/pkgsite: package documentation should immediately reflect UI changes

### ISSUE THREAD

**Issue by shaqque** [golang/go#40807]
Currently, we need to reprocess the database on any UI changes (e.g. changes to the HTML templates), which can take several hours. Users who request packages that were not yet reprocessed will see the old HTML version, which when coupled with potentially new CSS changes, can have unexpected results. See #40078

We should allow the frontend to prioritize the reprocessing of any package that a user requests, so that users will always see the latest UI changes when viewing documentation.

**Comment by julieqiu** [comment]
Fixed.
