### ISSUE TITLE
x/tools/gopls: "go list" leaks in CPU usage

### ISSUE THREAD

**Issue by mxschmitt** [golang/go#40813]
Issue Type: <b>Bug</b>

Happens over time, not sure how to reproduce it currently. I will see in the next few days if its reproducible. Happened since a few weeks, so the last VSCode update is not causing it. 

Extension version: 0.16.1
VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:03:27.059Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.69GB free)|
|Process Argv|-psn_0_143415485|
|Screen Reader|no|
|VM|0%|
</details>

See htop:
![image](https://user-images.githubusercontent.com/17984549/90322302-107b0a00-df53-11ea-8e45-2db8d8048968.png)
The full command which is causing the high CPU usage
```
go list -modfile=/var/folders/nq/zpr698s164v26n4v45mfkzw80000gq/T/go.3ca87dc125e97a69f07220750af22332c34224f1.022321034.mod -e -json -compiled=true -test=true -export=false -deps=true -find=false -modfile=/var/folders/nq/zpr698s164v26n4v45mfkzw80000gq/T/go.3ca87dc125e97a69f07220750af22332c34224f1.022321034.mod -- github.com/mxschmitt/playwright-golang
```

Go version: 1.14.7 darwin/amd64

Since the process is directly launched under `launchd` - and by that not a subprocess, I'm not fully sure if this is related to this Visual Studio Code extension. Also if I close it, it stays open. I don't use any other Go editor, only command line tools for "go run" and "go test".

Related: https://github.com/golang/go/issues/39116

**Comment by stamblerre** [comment]
This `go list` call looks like it's coming from the language server, so transferring this issue to that issue tracker.
The next time you see this, please upload your `gopls` logs as well. Instructions on how to capture them [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs).
In this case, did the `github.com/mxschmitt/playwright-golang` package exist?

**Comment by mxschmitt** [comment]
Thanks! Yep it does exist on my local machine. I enabled debug logs on the language server and upgraded additionally to Go 1.15. I keep you updated here in this issue 👍

**Comment by mxschmitt** [comment]
I'll close it for now, seems like the newest update has fixed it (worked around 3 working days with it without any issues). Thanks!
