### ISSUE TITLE
x/sys/unix: Android x86_64 emulator crashes when using the pipe syscall

### ISSUE THREAD

**Issue by cmcewen** [golang/go#40828]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.15 darwin/amd64
</pre>

I am using gomobile to compile a library to run on Android

### Does this issue reproduce with the latest release?

Yes - it is an issue in golang.org/x/sys

### What operating system and processor architecture are you using (`go env`)?

I am running a library compiled with gomobile running on the AOSP API 29  x86_64 emulator

### What did you do?

Ran the app and called the library

### What did you expect to see?

The app run fine

### What did you see instead?

The app crashed:
```08-10 17:54:49.398  5047  5047 F DEBUG   : Build fingerprint: 'Android/sdk_phone_x86_64/generic_x86_64:9/PSR1.180720.012/4923214:userdebug/test-keys'
08-10 17:54:49.398  5047  5047 F DEBUG   : Revision: '0'
08-10 17:54:49.398  5047  5047 F DEBUG   : ABI: 'x86_64'
08-10 17:54:49.398  5047  5047 F DEBUG   : pid: 4938, tid: 4958, name: XXXXX
08-10 17:54:49.398  5047  5047 F DEBUG   : signal 31 (SIGSYS), code 1 (SYS_SECCOMP), fault addr --------
08-10 17:54:49.398  5047  5047 F DEBUG   : Cause: seccomp prevented call to disallowed x86_64 system call 22
```

Using strace I was able to track it down to pipe:
`9930  rt_tgsigqueueinfo(9900, 9930, SIGSYS, {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x7d49d5a145a6, si_syscall=__NR_pipe, si_arch=AUDIT_ARCH_X86_64}) = 0`

**Comment by ianlancetaylor** [comment]
Do you see the same problem if you call `syscall.Pipe`?  Seems to me that you would, but it would be nice to check.  Thanks.

**Comment by cmcewen** [comment]
This PR was able to fix the crash for me: https://github.com/golang/sys/pull/75
