### ISSUE TITLE
cmd/go: cannot find module providing package code.google.com/p/ftp4go

### ISSUE THREAD

**Issue by mukhtar13** [golang/go#40824]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/username/.cache/go-build"
GOENV="/home/username/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY="gitlab.example.com/*"
GONOSUMDB="gitlab.example.com/*"
GOOS="linux"
GOPATH="/home/username/go-workspace"
GOPRIVATE="gitlab.example.com/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/username/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/username/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/username/go-workspace/src/gitlab.example.com/bdr/BBS/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build052994486=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
run below command init is successful but make fails as it gives an error "cannot find module providing package code.google.com/p/ftp4go"
the package "code.google.com/p/ftp4go" is used in code and directory is available in the vendor directory.
go mod init gitlab.example.com/x/y
make

### What did you expect to see?
make should run successful
and if not possible to download the library it should skip the package "code.google.com/p/ftp4go" and complete the make as package is available in vendor directory if I don't use go mod the make is successful.

### What did you see instead?
cannot find module providing package code.google.com/p/ftp4go

**Comment by dmitshur** [comment]
> make should run successful

What does "make" refer to? Is it the `make` command that executes a Makefile? If so, please either point to it, or share what command it runs. Otherwise it's not possible to understand where the problem is.

> and if not possible to download the library it should skip the package "code.google.com/p/ftp4go"

What is "it" in this context? Can you please clarify?
