### ISSUE TITLE
x/tools/gopls: returns with non-0 exit code on server restart / shutdown

### ISSUE THREAD

**Issue by rchl** [golang/go#40832]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.14.5 darwin/amd64
gopls 0.4.4
</pre>

### Does this issue reproduce with the latest release?

Yes?

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
(valid build configuration = false)
(build flags: [])
GOINSECURE=
GOPATH=/Users/me/go
GOROOT=/usr/local/Cellar/go/1.14.5/libexec
GO111MODULE=
GONOPROXY=
GOPROXY=https://proxy.golang.org,direct
GOSUMDB=sum.golang.org
GOCACHE=/Users/me/Library/Caches/go-build
GOMOD=
GOMODCACHE=
GONOSUMDB=
GOPRIVATE=
GOFLAGS=
</pre></details>

### What did you do?

1. Open a go file in VSCode
2. Trigger `Go: Restart Language Server` from the command palette

### What did you expect to see?

In the go server logs, there should be no:
```
gopls: failed reading header line: EOF
```
message

### What did you see instead?

I see the aforementioned message in the logs and the server is exiting with exit code 2.

I think the relevant code is here:
https://github.com/golang/tools/blob/cc40288be83943c50bf80a9702fb35bd5e580e8d/internal/jsonrpc2/stream.go#L110-L114
And the problem might be that it's not doing what the comment there says. The comment says:
> // read the header, stop on the first empty line

but since the `s.in.ReadString('\n')` call is looking for a newline, I think it will return non-nil `err` when it sees an empty line. Thus we'll never get to the graceful, empty-line handling lower in the code.

**Comment by stamblerre** [comment]
Thanks for the report! I haven't seen this issue before--are you able to consistently reproduce it when you restart the language server?

/cc @findleyr @ianthehat

**Comment by rchl** [comment]
Yes. I can consistently reproduce it.

Note that I'm not a VSCode user. I'm using Sublime Text where non-zero exit code returned from the server triggers a "crash dialog" so that's why I've noticed it. But as I've said, I've also reproduced this with VSCode (at least the same stderr message as I can't see the exit code in vscode
