### ISSUE TITLE
cmd/compile: bug due to typo in (*.internal/types.Type).cmp for TSSA

### ISSUE THREAD

**Issue by PraxisProject** [golang/go#40837]
https://github.com/golang/go/blob/51ac0f0f4cb432204dee3d434335fd1e61ca8446/src/cmd/compile/internal/types/type.go#L1029
```
xname := t.Extra.(string)
```
should ACTUALLY BE:
```
xname := x.Extra.(string)
```

**Comment by odeke-em** [comment]
Thank you @PraxisProject for this report and welcome to the Go project! Great catch with a code audit, we’ve had that in for 3 years. If you’ve got time could you please send a patch and you’ll become a Go contributor too.

/cc @josharian @randall77

**Comment by PraxisProject** [comment]
Heyo. Submitted PR.
