### ISSUE TITLE
x/sys/unix: support AF_CAN in anyToSockaddr

### ISSUE THREAD

**Issue by skladd** [golang/go#40842]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="linux"
CGO_ENABLED="1"
</pre></details>

### What did you do?

Calling e.g. unix.Recvmsg for a SocketCAN socket (AF_CAN)

<details><summary>Example program</summary><br>
 First set up VCAN interface and generate data (via canutils):

```
$ sudo ip link add dev vcan0 type vcan && sudo ip link set up vcan0
$ cangen vcan0 -g 4 -I 42A -L 2 -D 1234 -v -v
```

```go
package main

import (
	"fmt"
	"net"

	"golang.org/x/sys/unix"
)

const ifaceName = "vcan0"

func main() {
	var (
		err   error
		iface *net.Interface
		fd    int
	)

	if iface, err = net.InterfaceByName(ifaceName); err != nil {
		panic(err)
	}

	if fd, err = unix.Socket(unix.AF_CAN, unix.SOCK_RAW, unix.CAN_RAW); err != nil {
		panic(err)
	}

	if err = unix.SetsockoptInt(fd, unix.SOL_SOCKET, unix.SO_TIMESTAMPNS, 1); err != nil {
		panic(err)
	}

	if err = unix.Bind(fd, &unix.SockaddrCAN{Ifindex: iface.Index}); err != nil {
		panic(err)
	}

	b := make([]byte, 256)
	oob := make([]byte, 256)
	var (
		n, oobn, recvflags int
		from unix.Sockaddr
	)

	// returns error
	n, oobn, recvflags, from, err = unix.Recvmsg(fd, b, oob, 0)

	fmt.Printf("unix.Recvmsg() b: %v, oob: %v, recvflags: %v, from: %v, err: \"%v\"\n", b[:n], oob[:oobn], recvflags, from, err)
}
```
</details>

### What did you expect to see?

```
unix.Recvmsg() b: [42 4 0 0 2 0 0 0 18 52 0 0 0 0 0 0], oob: [32 0 0 0 0 0 0 0 1 0 0 0 29 0 0 0 3 150 58 95 0 0 0 0 178 148 5 0 0 0 0 0], recvflags: 4, from: &{7 0 0 {0 0 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]}}, err: "<nil>"
```

### What did you see instead?

Method returns error EAFNOSUPPORT "address family not supported by protocol" and from `<nil>`.

```
unix.Recvmsg() b: [42 4 0 0 2 0 0 0 18 52 0 0 0 0 0 0], oob: [32 0 0 0 0 0 0 0 1 0 0 0 29 0 0 0 65 150 58 95 0 0 0 0 174 73 9 0 0 0 0 0], recvflags: 4, from: <nil>, err: "address family not supported by protocol"
```

### Comments

Obviously, private unix.anyToSockaddr is called by unix.Recvmsg and returns EAFNOSUPPORT as AF_CAN is not yet supported. SockaddrCAN and AF_CAN support was added via #16188 by @ianlancetaylor and @elliotmr.

Perhaps something like

```go
	case AF_CAN:
		pp := (*RawSockaddrCAN)(unsafe.Pointer(rsa))
		sa := &SockaddrCAN{
			Ifindex: int(pp.Ifindex),
		}
		return sa, nil
```

in the switch statement in anyToSockaddr() would be sufficient.

**Comment by tklauser** [comment]
> ```go
> 	case AF_CAN:
> 		pp := (*RawSockaddrCAN)(unsafe.Pointer(rsa))
> 		sa := &SockaddrCAN{
> 			Ifindex: int(pp.Ifindex),
> 		}
> 		return sa, nil
> ```
> 
> in the switch statement in anyToSockaddr() would be sufficient.

I think you'll also need to set `sa.Addr`, other than that it looks like this should be sufficient. Want to send a CL?

**Comment by skladd** [comment]
`SockaddrCAN` has no field `Addr`, but I do not know what has to be done here. In fact, I am not really interested in the returned `from` socket. Instead, I stumbled on the `EAFNOSUPPORT` error.

CLA is signed.

**Comment by tklauser** [comment]
> `SockaddrCAN` has no field `Addr`, but I do not know what has to be done here.

Right. My mistake, I was looking at `RawSockaddrCAN`.

I think we need to fill `sa.RxID` and `sa.TxID` from `pp.Addr`, basically reverse what `(*SockaddrCAN).sockaddr()` does.
