### ISSUE TITLE
cmd/go2go: constraint type inference fails

### ISSUE THREAD

**Issue by JakeMont** [golang/go#40859]
The "Element constraint example" in the "Constraint type inference" section of the Type Parameters Draft Design [(here)](https://go.googlesource.com/proposal/+/refs/heads/master/design/go2draft-type-parameters.md#element-constraint-example) fails when run in the go2go playground:
https://go2goplay.golang.org/p/VBEVxYVbF62
```
package main

import (
	"fmt"
)

type Number interface {
	type int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, uintptr, float32, float64
}

type MySlice []int

type SC[type E] interface {
	type []E
}

func DoubleDefined[type S SC[E], E Number](s S) S {
	r := make(S, len(s))
	for i, v := range s {
		r[i] = v + v
	}
	return r
}

func main() {
	
	// Expicit types work fine
	fmt.Println(DoubleDefined[MySlice, int](MySlice{1}))

	// Constraint type inference does not work?
	fmt.Println(DoubleDefined(MySlice{1}))
}
```

**Output:**
```
type checking failed for main
prog.go2:31:38: cannot infer E (prog.go2:17:34) ([main.MySlice <nil>])
```

The failure is in the second call to `DoubleDefined`, which is supposed to work according to the design. This is the point of the design doc example.

**Comment by griesemer** [comment]
Interestingly this works fine when running this example in the type checker test harness, but not when running it outside. Investigating.

**Comment by griesemer** [comment]
@iant: The go2go tool needs to set `types.Config.InferFromConstraints` to true, otherwise constraint type inference is not enabled.

**Comment by griesemer** [comment]
Fixed in the dev.go2go branch. Will come to the playground sometime soon.
