### ISSUE TITLE
x/pkgsite: horizontal scrollbar shows needlessly

### ISSUE THREAD

**Issue by myitcv** [golang/go#40858]
### What is the URL of the page with the issue?

https://pkg.go.dev/

### What is your user agent?

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.59 Safari/537.36
</pre>

### Screenshot

<img width="1920" alt="Screen Shot 2020-08-18 at 11 55 18" src="https://user-images.githubusercontent.com/3374574/90504931-b6906500-e149-11ea-9247-a5c2ab144f0f.png">

### What did you do?

* Visit the above page
* Start typing in the search box

### What did you expect to see?

No horizontal scrollbar

### What did you see instead?

The horizontal scrollbar appears

**Comment by julieqiu** [comment]
I can't reproduce this issue at 100% zoom:

<img width="1277" alt="Screen Shot 2020-08-18 at 9 25 07 AM" src="https://user-images.githubusercontent.com/5943521/90518381-b8036280-e134-11ea-817b-21da96c8ae16.png">

/cc @jamalc to investigate

**Comment by myitcv** [comment]
FYI this only happens when working on my MacBook Pro with no external device attached, and the resolution scaled to "More space" (i.e. highest resolution)

**Comment by andybons** [comment]
@myitcv something looks like it’s overflowing. Can you repro this in an incognito window as well?

**Comment by myitcv** [comment]
> Can you repro this in an incognito window as well?

Yes, I can.

The horizontal scrollbar appears to be showing in order to deal with the reduced amount of horizontal space because the vertical scrollbar is showing - I'll emphasise that's a pure guess given the amount of scrolling that appears possible with the horizontal scrollbar.

**Comment by Omkar76** [comment]
Are you still facing this issue? I believe I fixed this in golang/pkgsite#18 for an another issue. 
/cc @myitcv

**Comment by myitcv** [comment]
Thanks - doesn't appear to be an issue any longer.
