### ISSUE TITLE
x/pkgsite: licence not yet showing up after it was added to a module

### ISSUE THREAD

**Issue by gnuy** [golang/go#40863]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/gnuy/subdivx-get
 
### What is your user agent?
 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0

 
 
 
### Screenshot  
![DeepinScreenshot_select-area_20200818120421](https://user-images.githubusercontent.com/12873650/90530214-860df280-e16c-11ea-8068-2d2eb35e562f.png)
 

 

 
### What did you do?
 Created a Go project on GitHub without a license and added that license later. I'm filing this issue as recommended [here](https://pkg.go.dev/license-policy).

 
 
 
### What did you expect to see?
 The license in the site being the MIT license. 
 
### What did you see instead?
 The license in the site is still *no legal advice*

**Comment by dmitshur** [comment]
Version v0.0.0 (1a772ed) of the github.com/gnuy/subdivx-get module is being displayed in the screenshot you shared. That version does not have a LICENSE file:

https://github.com/gnuy/subdivx-get/tree/1a772eddf252/LICENSE (404)

The LICENSE file was added 2 hours ago in commit [2219d5c4](https://github.com/gnuy/subdivx-get/commit/2219d5c4774052f284aafa4a461d08a7132459c9).

It seems that this is working as intended. When pkg.go.dev starts displaying the newer version of the module, it should recognize the license.

/cc @julieqiu @jba @jamalc per [owners](https://dev.golang.org/owners).

**Comment by julieqiu** [comment]
I just refreshed the version: 

![image](https://user-images.githubusercontent.com/5943521/90537964-e6406c80-e14b-11ea-9f25-ab0166e6b3d1.png)
