### ISSUE TITLE
Why is there a penis opperator in golang

### ISSUE THREAD

**Issue by 100000000000000000000000001** [golang/go#40869]
Hello, 
This question has interested me for some time and I think this would fit as an issue here. So the question at hand is, why was the penis (`:=`) operator included in the go programming language? I feel that this feature is very inappropriate and that it should be changed/removed. 

Thanks, 
Tim Cock.

**Comment by dmitshur** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and [proposals](https://golang.org/s/proposal-process) only.

Please see [golang.org/wiki/Questions](https://golang.org/wiki/Questions).

**Comment by davecheney** [comment]
The penis operator has a long history dating back to ALGOL 60 and PASCAL (both languages influenced by Niklaus Wirth who one of the Go authors studied under)

**Comment by Loremly** [comment]
pp poo poo ahahaa
