### ISSUE TITLE
x/pkgsite: don't display README section if it is empty

### ISSUE THREAD

**Issue by julieqiu** [golang/go#40867]
If a package doesn't have a README, don't display it.

### What did you do?
 
Visited https://pkg.go.dev/github.com/gnuy/subdivx-get@v0.0.0-20200818145511-51d3e492f137?tab=overview

 
### What did you expect to see?
 
No README section:

![image](https://user-images.githubusercontent.com/5943521/90538536-af1e8b00-e14c-11ea-935f-ed0b90802386.png)

### What did you see instead?

An empty README section:

![image](https://user-images.githubusercontent.com/5943521/90538274-55b65c00-e14c-11ea-9549-7f2ba7c3fcc9.png)

**Comment by ironbatshashank** [comment]
Instead of displaying no readme section, how about we autogenerate a readme section? I think it'll be more helpful.

**Comment by julieqiu** [comment]
@ironbatshashank - what are your thoughts on what that would look like?

**Comment by IamCathal** [comment]
I think if there was to be some auto generated content it would be a bit difficult:

Pros
* There is some more content on the screen and it doesn't look sparse

Cons
* Would have to pull stats from the repo like stars/language and description possibly? Getting a usable structure of information from this that would work for all repos without a readme would be difficult. If a repo didn't have a readme in the first place I don't think they'd have much else information to take add generate our own.
* Maybe nitpicking but users would expect this readme to be the actual readme and if the generated version and the actual version weren't the same it could lead to some confusion.

I would opt for just a simple box of placeholder text saying something like "Looks like this project doesn't have a readme yet" or something similar. It requires minimal work to implement and can't break. I've not contributed to a golang project before but I'd be up for learning the process of contributing after completing the contributing guide.

**Comment by julieqiu** [comment]
> I would opt for just a simple box of placeholder text saying something like "Looks like this project doesn't have a readme yet" or something similar. It requires minimal work to implement and can't break. 

Thanks for the input, @IamCathal! Let's go with that suggestion.

> I've not contributed to a golang project before but I'd be up for learning the process of contributing after completing the contributing guide.

If you're interested in contributing this fix, let me know. Happy to help you get started and answer any questions in [#pkgsite Slack](https://app.slack.com/client/T029RQSE6/C0166L4QGJV/thread/C88U9BFDZ-1592853959.129500). 

https://github.com/golang/pkgsite/blob/master/CONTRIBUTING.md#getting-started is a good starting point.

**Comment by IamCathal** [comment]
I failed to get the DB setup about 4 times on my own and couldn't progress with this issue, thank you very much @rahulw for the help with the setup.
