### ISSUE TITLE
net/http: permit splice from socket to ResponseWriter

### ISSUE THREAD

**Issue by PaulForgey** [golang/go#40888]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 darwin/amd64
</pre>

(my complaint actually helps linux and is a non-issue on darwin, but I target linux hosts too)

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/pforgey/Library/Caches/go-build"
GOENV="/Users/pforgey/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/pforgey/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/pforgey/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/pforgey/goroot"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/pforgey/goroot/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD="/Users/pforgey/goroot/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ck/hxb66hs93wd58w5ylk4v0vfxk_3ncr/T/go-build576313242=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Assumed a simple io.Copy() between a socket and an http.ResponseWriter would go through splice()

### What did you expect to see?
To be treated like io.Copy() between two spliceable FDs

### What did you see instead?
A surprising, but not unreasonable workaround to issue #5660 caused by the fact we start writing headers immediately before the source reader is readable.

Instead of going through the trouble of determining if the source is a file before proceeding along the presumed sendfile (but maybe splice!) route, I have successfully tested a local patch (attached) which does a small read instead. Regardless of needsSniff(), this satisfies the sniff step, but also waits for the source to be actually readable.

A small body of < 512 (sniffLen) bytes would have little benefit from sendfile/splice, and we were already doing a syscall round trip. Would the extra and and write of 512 bytes from kernel->user->kernel have a significant impact in the overall case of the larger bodies? I'm not too sure it would, but it is a legitimate point to object with, but it wouldn't be the first example of zero copy network code slopping a little bit of the initial data portion like that. For the smaller bodies, it may actually have slightly less setup time.

(removed gist link to patch and submitting a PR instead)

**Comment by davecheney** [comment]
@PaulForgey please remove the link to your patch so it does not taint the reviewers. Please see https://golang.org/doc/contribute.html or send a PR to this repository and a robot will convert it into a gerrit change list.

**Comment by ianlancetaylor** [comment]
CC @bradfitz

**Comment by odeke-em** [comment]
The red herring in this issue is that it broadly claims that splice won’t work, but perhaps we could say that we are fixing the problem of responding before the source is ready. I think the prior one was a bold claim which threw me off. I’ll review your CL shortly but will need to confirm that splice gets invoked. Thank you for working on this.

**Comment by PaulForgey** [comment]
> The red herring in this issue is that it broadly claims that splice won’t work, but perhaps we could say that we are fixing the problem of responding before the source is ready. I think the prior one was a bold claim which threw me off. I’ll review your CL shortly but will need to confirm that splice gets invoked. Thank you for working on this.

if you are coming from a regular file, it will work.
