### ISSUE TITLE
cmd/go2go: nonsensical recursive type compiles

### ISSUE THREAD

**Issue by benjaminjkraft** [golang/go#40884]
Here are two types ([playground](https://go2goplay.golang.org/p/g0ShhBStNxW)):
```go
type A[type X] interface{ a(X) }
type B[type X A[B]] interface{ b(X) }
```
The type `A[B]` is semantically invalid; `B` needs to be instantiated.  But this seems to be allowed currently.

In fact if we modify `A` a bit we can even supposedly implement `B` ([playground](https://go2goplay.golang.org/p/1iV__ylGWOj)):
```go
type A[type X] interface{ b(B[X]) }
type B[type X A[B]] interface{ b(X) }
type S struct{}
func (_ S) b(A[int]) {}
var _ B[A[int]] = S{}
```

**Comment by griesemer** [comment]
This code now reports a proper cycle error ([playground](https://gotipplay.golang.org/p/0DJzt-S6GmH)). Closing.
