### ISSUE TITLE
cmd/go: support reusing GOMODCACHE system wide

### ISSUE THREAD

**Issue by flibustenet** [golang/go#40895]
#### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 linux/amd64
</pre>

Given the new possibility to set `GOMODCACHE` i would like to make it system wide as i have only trusted users on my server it would let me gain disk space and download speed if the directory could be the same for all users.
But the perms prevent it, for security reason i believe.

Is there a workaround ? Or could it be a proposal for a such a feature ?

_I'm aware of running a local proxy but it's overkill for me and will duplicate again the cache._

**Comment by GrigoriyMikhalkin** [comment]
I'm not sure, what's problem here -- you can create common directory like `/home/common`, make it accessible to every trusted user and store mod cache there. Or, probably, i misunderstood your problem?

**Comment by flibustenet** [comment]
Sorry i should give an example:

```
# ls -ld /ocean/gomodcache
drwxrwxr-x 4 root www-user 4096 août  19 16:57 /ocean/gomodcache

wilk@thinkpad:/tmp/t$ go env |grep GOMODCACHE
GOMODCACHE="/ocean/gomodcache"

wilk@thinkpad:/tmp/t$ go get github.com/gorilla/mux
go: downloading github.com/gorilla/mux v1.7.4

ania@thinkpad:/tmp/t$ go get github.com/gorilla/mux
go get: open /ocean/gomodcache/github.com/gorilla/mux@v1.7.4: permission denied

ania@thinkpad:/tmp/t$ go get github.com/pkg/errors
go: writing stat cache: mkdir /ocean/gomodcache/cache/download/github.com/pkg: permission denied
go: downloading github.com/pkg/errors v0.9.1
go get github.com/pkg/errors: mkdir /ocean/gomodcache/cache/download/github.com/pkg: permission denied

thinkpad:/ocean# ls -ld gomodcache/*
drwxr-xr-x 3 wilk wilk 4096 août  19 17:00 gomodcache/cache
drwxr-xr-x 3 wilk wilk 4096 août  19 17:00 gomodcache/github.com
```

The directories are created without writing permission to group and others and the owner is the first user who go get something.

**Comment by GrigoriyMikhalkin** [comment]
You need to set `setgid` bit for this directory, like `chmod g+s /ocean/gomodcache`. In that case, all new files and subdirectories will inherit group from parent directory

**Comment by flibustenet** [comment]
Yes for the group, but there is still no write permission on the group.
I tried also with `-modcacherw` but it's only for files and owner.

**Comment by GrigoriyMikhalkin** [comment]
Try to set [acl](https://wiki.archlinux.org/index.php/Access_Control_Lists) for group on this directory: `setfacl -Rdm g:www-user:rwx /ocean/gomodcache`. Did it helped?

**Comment by flibustenet** [comment]
No, i believe go get explicitly set group without write.

**Comment by GrigoriyMikhalkin** [comment]
That's strange, that works for me.

**Comment by GrigoriyMikhalkin** [comment]
Here's how i tried to reproduce you problem, feel free to update my steps if i do something wrong:

Create group:
```
groupadd test
```

Create user and add him to group:
```
useradd testuser
usermod -a -G test testuser
```

Create common directory and assign needed permissions:
```
mkdir /home/common
chmod g+rwx /home/common
chmod g+s /home/common
setfacl -Rdm g:test:rwx /home/common/
```

Login as new user and download module:
```
su testuser
export GOMODCACHE="/home/common/"
cd some_module
go get github.com/grigoriymikhalkin/sqlboiler-paginate/v4
```

And that works just fine.

**Comment by flibustenet** [comment]
The first user who `go get` works, it's the next user which cannot. Can you come back to the first user and `go get` something ?

**Comment by GrigoriyMikhalkin** [comment]
Ah, i see. Indeed, i get this error from first user.

**Comment by dmitshur** [comment]
I'm not sure if this is meant to be supported and whether it's already possible (if done in a certain way).

/cc @jayconrod @matloob @bcmills @mvdan

**Comment by jayconrod** [comment]
What is your `umask` setting? What are the permissions on the directories where the `permission denied` errors are happening?

The `go` command creates most cache directories with mode 0777, but people usually have a umask of 0022, so that becomes 0755.
