### ISSUE TITLE
encoding/binary: binary.Read doesn't respect byteOrder when []byte is passed

### ISSUE THREAD

**Issue by nokute78** [golang/go#40891]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/taka/.cache/go-build"
GOENV="/home/taka/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/taka/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/taka/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/taka/go/src/github.com/nokute78/go-bit/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build405174845=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I tried to read 6 bytes using binary.Read in BigEndian.
https://play.golang.org/p/RUvRdkc0a0W

### What did you expect to see?

```
ret(big)=ffeeddccbbaa
ret(lit)=aabbccddeeff
```

### What did you see instead?
binary.Read returns same value and it seems to ignore byteOrder.

```
ret(big)=aabbccddeeff
ret(lit)=aabbccddeeff
```

Background: 

The GUID Partition Table (GPT)  has mixed endian GUID.
Refer to https://developer.apple.com/library/archive/technotes/tn2166/_index.html#//apple_ref/doc/uid/DTS10003927-CH1-SECTION2
```
 the GUID for the ESP partition type is shown in the documentation as C12A7328-F81F-11D2-BA4B-00A0C93EC93B, but the bytes written to disk are 0x28 0x73 0x2a 0xc1 0x1f 0xf8 0xd2 0x11 0xba 0x4b 0x00 0xa0 0xc9 0x3e 0xc9 0x3b.
```

The GUID is encoded like
* 4bytes (Little Endian)
* 2bytes (Little Endian)
* 2bytes (Little Endian)
* 2bytes (Big Endian)
* **6bytes (Big Endian)** 

The point is the last 6bytes `0x00 0xa0 0xc9 0x3e 0xc9 0x3b`. It is encoded as Big Endian.
How can we get using binary.Read ?
Does binary.Read support such case?

**Comment by davecheney** [comment]
This is because the byte ordering is the byte ordering of the target type which has no meaning when the target is only 8 bits wide

**Comment by nokute78** [comment]
@davecheney Thank you for comment.

> the target is only 8 bits wide.

It is an element size (not an entire slice).
So binary.Read supports only 1,2,4,8,16 bytes which are the size of numeric types, right ? 

> guid is 16 bytes. That’s it, no endianness needed.

I think we should take care endianness.

MS supports  a [GUID API](https://docs.microsoft.com/en-us/dotnet/api/system.guid.-ctor?view=netcore-3.1#System_Guid__ctor_System_Int32_System_Int16_System_Int16_System_Byte_System_Byte_System_Byte_System_Byte_System_Byte_System_Byte_System_Byte_System_Byte_) to avoid Guid endianness issue. (refer to Remarks)


https://docs.microsoft.com/en-us/archive/blogs/openspecification/guids-and-endianness-endi-an-ne-ssinguid-or-idne-na-en-ssinguid

**Comment by davecheney** [comment]
> So binary.Read supports only 1,2,4,8,16 bytes which are the size of numeric types, right ?

it supports integer types of varying but sizes. If you decode into something larger than a byte then endianness comes into play.

**Comment by randall77** [comment]
`binary.Read` does not support what you are trying to do.

`binary.Read` ignores the endian argument if the data you're reading into is a byte slice. You have to read into a larger type, e.g. `int32`, for endianness to matter.

You can always reverse your byte slice after reading.

```
func reverse(b []byte) {
   for i := 0; i < len(b)/2; i++ {
       b[i], b[len(b)-1-i] = b[len(b)-1-i], b[i]
   }
}
```

**Comment by nokute78** [comment]
@davecheney @randall77 Thank you for comment and example code !

I understood binary.Read doesn't support what I want to do.
So, I close this issue.
