### ISSUE TITLE
x/tools/gopls: find-references results returned in random order

### ISSUE THREAD

**Issue by muirdm** [golang/go#40904]
Find-references (and find-implementations, and go-to-definition) should give results back in a consistent order. Currently I see a random order (sometimes it is random every time, other times it seems consistent for a while then changes). For example:

```go
package main

func _() {
	var foo int
	
	_ = foo
	_ = foo
}
```

<details>
<summary>
Finding references on "var <strong>foo</strong> int" I get back lines [5, 6] then [6, 5] in the next request.
</summary>

```
Trace - 09:43:37 AM] Sending request 'textDocument/references - (14764)'.
Params: {
  "textDocument": {
    "uri": "file:///Users/muir/scratch/foo/foo.go"
  },
  "position": {
    "line": 3,
    "character": 5
  },
  "context": {
    "includeDeclaration": false
  }
}


[Trace - 09:43:37 AM] Received response 'textDocument/references - (14764)' in 5ms.
Result: [
  {
    "range": {
      "end": {
        "character": 8,
        "line": 5
      },
      "start": {
        "character": 5,
        "line": 5
      }
    },
    "uri": "file:///Users/muir/scratch/foo/foo.go"
  },
  {
    "range": {
      "end": {
        "character": 8,
        "line": 6
      },
      "start": {
        "character": 5,
        "line": 6
      }
    },
    "uri": "file:///Users/muir/scratch/foo/foo.go"
  }
]

[Trace - 09:43:42 AM] Sending request 'textDocument/references - (14766)'.
Params: {
  "textDocument": {
    "uri": "file:///Users/muir/scratch/foo/foo.go"
  },
  "position": {
    "line": 3,
    "character": 5
  },
  "context": {
    "includeDeclaration": false
  }
}


[Trace - 09:43:42 AM] Received response 'textDocument/references - (14766)' in 0ms.
Result: [
  {
    "range": {
      "end": {
        "character": 8,
        "line": 6
      },
      "start": {
        "character": 5,
        "line": 6
      }
    },
    "uri": "file:///Users/muir/scratch/foo/foo.go"
  },
  {
    "range": {
      "end": {
        "character": 8,
        "line": 5
      },
      "start": {
        "character": 5,
        "line": 5
      }
    },
    "uri": "file:///Users/muir/scratch/foo/foo.go"
  }
]
```

</details>

Perhaps we can sort first by file name, then secondarily by offset within file? Maybe also sort files from the starting package first?

Clients can still customize the sorting if they want, but I think gopls should return consistent results and results within a file should be ordered as they appear in the file.

**Comment by myitcv** [comment]
Related: https://github.com/golang/go/issues/32572

**Comment by muirdm** [comment]
> Related: #32572

Thanks, forgot about that discussion.

To cover my bases I opened https://github.com/emacs-lsp/lsp-mode/issues/2099 with regard to my client not sorting.

@myitcv do govim and vim-go sort the results?

**Comment by myitcv** [comment]
@muirdm 

> do govim and vim-go sort the results?

`govim` does, yes:

https://github.com/govim/govim/blob/be5a1e7a2db7f531a4f49cc1a2982a59f9478ac2/cmd/govim/util.go#L139-L182

Notice the workaround required for not sorting when we know the first result to be the definition location.

**Comment by myitcv** [comment]
cc @bhcleek for `vim-go`

**Comment by bhcleek** [comment]
yes, vim-go also sorts them: https://github.com/fatih/vim-go/blob/bd56f5690807d4a92652fe7a4d10dc08f260564e/autoload/go/lsp.vim#L836

**Comment by stamblerre** [comment]
I continue to maintain that clients should sort if they want sorted results, but we should also probably return deterministic results. I'll send a CL to sort the results.

**Comment by myitcv** [comment]
> I continue to maintain that clients should sort if they want sorted results, but we should also probably return deterministic results. I'll send a CL to sort the results.

The problem as I understand it is that nowhere in the spec is it declared that the first result will be the definition (there could, in other languages, be other nuances). Hence, to avoid clients having to special case the sort, the server needs to define the meaning and hence sort the results.

**Comment by stamblerre** [comment]
Oh wow, I genuinely didn't realize that wasn't in the spec. I wonder why we did it that way then. In that case, I'm really not sure how the results should be sorted at all.

**Comment by bhcleek** [comment]
I also tend to believe that sorting shouldn't be guaranteed and that it's up to clients to do that if they want to present sorted results and that a server guaranteed deterministic order isn't worth the trouble.

**Comment by myitcv** [comment]
@bhcleek

> up to clients to do that if they want to present sorted results

How does a generic LSP client do this in a language agnostic way? How does the client know that it should sort `references[1:]` instead of the entire `references` slice (because I would venture to suggest it _does_ make sense for the first reference to be the definition in the case of Go).

@stamblerre 

> I'm really not sure how the results should be sorted at all.

As a first cut my suggestion would be:

* definition first
* then results within the main module, ordered lexicographically 
* then results from outside the main module, ordered lexicographically

**Comment by bhcleek** [comment]
> How does a generic LSP client do this in a language agnostic way?

I don't understand the question. What needs to be language agnostic about sorting locations?

> How does the client know that it should sort references[1:] instead of the entire references slice (because I would venture to suggest it does make sense for the first reference to be the definition in the case of Go).

Why should the definition be first as a general rule? I'll grant you that I can see reasons for that, but ultimately I think it should be up to the client, not the server.
