### ISSUE TITLE
x/tools/playground: deletes compiled user binary too early, before it has finished executing and sending output

### ISSUE THREAD

**Issue by owulveryck** [golang/go#40902]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/olivier.wulveryck/Library/Caches/go-build"
GOENV="/Users/olivier.wulveryck/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/olivier.wulveryck/GOPROJECTS/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/olivier.wulveryck/GOPROJECTS"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/olivier.wulveryck/GOPROJECTS/src/golang.org/x/tools/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n3/_n442h65067_9gzjq31vh06r0000gn/T/go-build691133751=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I am writing a slide to use with the latest version of present (188abfa75333b8777a65738f357c6cb2e1e49365).
I use the `play` capability, but when I try to run any simple code from the browser, it fails with the message:

`program exited: signal: killed`

### What did you expect to see?

The result of the program

### What did you see instead?

`program exited: signal: killed`

### Diagnostic.

I looked into MacOS log files, and it complains with:
```
Unable (errno: 2) to read file at <private> for process path: <private> library path: (null)
Terminating process due to Gatekeeper rejection: 5582, <private>
``` 

I made a debug session, and it looks like `present` is removing the binary prematurely; therefore, MacOS is killing it.

Removing this line, 
https://github.com/golang/tools/blob/cf83efe03cf89b09f33be7e464f1c95f6c3393aa/playground/socket/socket.go#L362
fixes the error.

The file produced by the execution process are cleaned here https://github.com/golang/tools/blob/cf83efe03cf89b09f33be7e464f1c95f6c3393aa/playground/socket/socket.go#L207

I can submit the fix if this is ok.

**EDIT**, the link to the fix in socket.go was leading to the wrong line

**Comment by dmitshur** [comment]
Thanks for reporting.

> I made a debug session, and it looks like present is removing the binary prematurely; therefore, MacOS is killing it.

Do you mind describing the fix you have in mind? What event do you think the playground should wait for before it's okay to remove the binary?

**Comment by owulveryck** [comment]
I am thinking of simply removing the https://github.com/golang/tools/blob/cf83efe03cf89b09f33be7e464f1c95f6c3393aa/playground/socket/socket.go#L362

The cleanup process is actually done in the `func (p *process) end(err error)` which occurs after the `cmd.Wait`.

Removing this line should not lead to any garbage left on the filesystem.

**Comment by dmitshur** [comment]
That seems reasonable. There's event a comment on a line below in that method:

```Go
p.path = path // to be removed by p.end
```

Thanks. I'll move this issue to NeedsFix state.

**Comment by dmitshur** [comment]
I could reproduce the issue on macOS and confirmed that [CL 249777](https://golang.org/cl/cl/249777) fixes it.
