### ISSUE TITLE
x/build: go1.10.8 release tag mismatch source/binary from golang.org

### ISSUE THREAD

**Issue by zhangyoufu** [golang/go#40918]
go1.10.8 was tagged at commit b0cb374daf646454998bac7b393f3236a2ab6aca `[release-branch.go1.10-security] go1.10.8`, while the actually shipped source/binary from golang.org is commit bd0449f8d16a5ac1b1962c7ea07d764a7f18eca7 `[release-branch.go1.10] all: merge release-branch.go1.10-security into release-branch.go1.10`.

**Comment by ALTree** [comment]
Not sure trying to retroactively change this would be advisable, since it's an old release...

 but cc @dmitshur @andybons

**Comment by dmitshur** [comment]
Thanks for spotting and reporting this.

This is indeed an old release which is not supported by now, so we're unlikely to make any changes to it.

However, we should investigate to see if this is a valid issue. If so, we should understand what happened, and ensure have measures in place so a problem of this kind doesn't happen in future releases.

Those two commits have identical trees:

```
$ git diff b0cb374daf646454998bac7b393f3236a2ab6aca bd0449f8d16a5ac1b1962c7ea07d764a7f18eca7
$
```

How did you determine which commit was used in the release?

**Comment by zhangyoufu** [comment]
I was confused by commit c731a7daf4e0db719c944f3c2073bed86c9fbf51. It was cherry-picked to ed3af1d472dad80cf070848917b80276ecb6a652.

I was applying some patch to 1.10.8, generated by `git format-patch go.1.10.8..my-branch`. It generated a patch series including `0001-release-branch.go1.10-net-pass-if-at-least-one-match.patch`, which fails to apply to 1.10.8 source/binary downloaded from golang.org, because the changes are already there.

Sorry for the noise.
