### ISSUE TITLE
x/exp/cmd/gorelease: allow major version comparisons

### ISSUE THREAD

**Issue by carnott-snap** [golang/go#40913]
Currently `gorelease` does not allow comparing between major versions. E.g. (on v2.0.0) `gorelease -base v1.0.0` yields:
```
gorelease: can't compare major versions: base version v1.0.0 does not belong to module path/to/module/v2
```

While I can understand that this is not part of the normal release flow, it is incredibly useful for generating changelog data, or just figuring out what changed between two releases. Furthermore this is annoying to do with `apidiff` directly, because it requires `NEW` be discoverable in the main module:
```sh
git checkout v1.0.0
apidiff path/to/module path/to/module/v2
```

/cc @jayconrod

**Comment by jayconrod** [comment]
This is a subset of #39666, which should be fixed by [CL 238839](https://go-review.googlesource.com/c/exp/+/238839) as soon as that's reviewed.

Leaving this open to be fixed by another CL though since it would be handy to say `-base=v1.0.0` instead of `-base=example.com/mod@v1.0.0`.
