### ISSUE TITLE
time: Parse defaults year is 0000 while Time{} is 0001

### ISSUE THREAD

**Issue by mtt0** [golang/go#40925]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output </summary><br><pre>
$ go env
</pre></details>
irrelevant

### What did you do?
[code on Playgroud](https://play.golang.org/p/a0D5ugQmu42)
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	fmt.Println("default time", time.Time{})

	if t, err := time.Parse("03:04:05.000000", "00:00:02.816500"); err != nil {
		fmt.Println(err)
		return
	} else {
		fmt.Println("parsed time: ", t, " duration: ", t.Sub(time.Time{}).Milliseconds())
	}

	// workaround
	if t, err := time.Parse("2006-01-02 03:04:05.000000", "0001-01-01 00:00:02.816500"); err != nil {
		fmt.Println(err)
		return
	} else {
		fmt.Println("workaround parsed time: ", t, " duration: ", t.Sub(time.Time{}).Milliseconds())
	}
}
```

### What did you expect to see?
Output:
```txt
default time 0001-01-01 00:00:00 +0000 UTC
parsed time:  0001-01-01 00:00:02.8165 +0000 UTC  duration:  2816
workaround parsed time:  0001-01-01 00:00:02.8165 +0000 UTC  duration:  2816
```

### What did you see instead?
Output:
```txt
default time 0001-01-01 00:00:00 +0000 UTC
parsed time:  0000-01-01 00:00:02.8165 +0000 UTC  duration:  -31622397183
workaround parsed time:  0001-01-01 00:00:02.8165 +0000 UTC  duration:  2816
```

**Comment by dmitshur** [comment]
[`time.Time`](https://pkg.go.dev/time#Time) documentation states:

> The zero value of type Time is January 1, year 1, 00:00:00.000000000 UTC.

[`time.Parse`](https://pkg.go.dev/time#Parse) documentation says:

> Elements omitted from the value are assumed to be zero or, when zero is impossible, one, so parsing "3:04pm" returns the time corresponding to Jan 1, year 0, 15:04:00 UTC (note that because the year is 0, this time is before the zero Time).

**Comment by ianlancetaylor** [comment]
Yes, there is no bug here.  The code is behaving as documented and intended.  Closing, but please comment if you disagree.
