### ISSUE TITLE
syscall/js: RangeError Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by lianghx-319** [golang/go#40923]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOOS="darwin"
GOPATH="/Users/user/go"
GOROOT="/usr/local/Cellar/go/1.14.4/libexec"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/user/Code/*****/*****/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/77/tr6w8vyx32l9yslxgbgvtb540000gp/T/go-build659170482=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
1. exec a golang wasm
2. load two files to wasm about 120MB each
3. get some call back from wasm to js
4. finally got a negative int to DateView.getUint32
![image](https://user-images.githubusercontent.com/27187946/90732385-999c9300-e2fd-11ea-8ec0-0352f7a10f75.png)

### What did you expect to see?
I want to know how to fix it or avoid it 😭

**Comment by agnivade** [comment]
Looks like an incorrect memory address being generated. Are you able to post a code sample that triggers this?

/cc @neelance

**Comment by lianghx-319** [comment]
Unfortunately, I can't post a code sample here. But there is another weird behavior:
- Here has there functions code with golang build into wasm
- After read those two files, this error occurs when calling `function A`
- After read those two files, this time I call `function B` first, no error; Then I call `function A`, no error either.

Finally, If those files are small file under 20MB, this error will not occur.

**Comment by lianghx-319** [comment]
> Sorry, I have no idea what is causing this. I would need to be able to reproduce it to investigate.

Here is a sample code, occur this error. https://github.com/lianghx-319/golang-issue-40923

Maybe deploy a online preview soon.

**Comment by aakselrod** [comment]
Hi, random passer-by here! I found this issue last week because I was getting the same error message. This week, I tried updating to Go 1.15 and rebuilding my code, and this error message seems to have gone away. I haven't attempted to track it down any further.

**Comment by F3n67u** [comment]
> > Sorry, I have no idea what is causing this. I would need to be able to reproduce it to investigate.
> 
> Here is a sample code, occur this error. https://github.com/lianghx-319/golang-issue-40923
> 
> Maybe deploy a online preview soon.

Hello, @agnivade, I am colleague of lianghx-319 . Could take a look at this reproduce repo? 

It seem that this bug is caused by high memory use. We have optimized memory use of golang wasm in our internal project code which reduce the whole tab memory footprint to about 1.3G with the same file, then this error message gone away. 

The error we are specifically running into seems this one - 
https://groups.google.com/a/chromium.org/g/chromium-dev/c/IKZvzuBP9QE
2GB memory limit per renderer (i.e. per tab)

**Comment by agnivade** [comment]
Without looking too much into it, and just looking at the symptoms, I would guess you are hitting the limits of the wasm linear memory. Currently, wasm linear memory supports only 32 bit addresses, which limits its total size to 4GiB. So anything above that will not work (and is likely causing an overflow for a 32 bit number). I think we just need to handle this case better and throw a nice error message.

Digging into the reproducer should verify if this is indeed the case.

In any case, it might help if you could try with 1.15. That has a number of optimizations which might generally help you to reduce memory usage.

**Comment by F3n67u** [comment]
> Without looking too much into it, and just looking at the symptoms, apart from the Chrome memory limit, it might also be possible that you are hitting the limits of the wasm linear memory. Currently, wasm linear memory supports only 32 bit addresses, which limits its total size to 4GiB. So anything above that will not work (and is likely causing an overflow for a 32 bit number). I think we just need to handle this case better and throw a nice error message.
> 
> Digging into the reproducer should verify if this is indeed the case. What is the behavior in other browsers?
> 
> In any case, it might help if you could try with 1.15. That has a number of optimizations which might generally help you to reduce memory usage.

The overall memory our website use is about 2GiB, so it not likely that 32 bits addr will overflow.
