### ISSUE TITLE
x/tools/gopls: markdown code block should be space not &nbsp;

### ISSUE THREAD

**Issue by wingyplus** [golang/go#40947]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

<pre>
$ gopls version
golang.org/x/tools/gopls 0.4.3
    golang.org/x/tools/gopls@v0.4.3 h1:irz7Q+XdHNECamFKbNWKvMV2Ak6zBbwdwbZndG4545I=
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/thanabodee/Library/Caches/go-build"
GOENV="/Users/thanabodee/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="**HIDDEN**/*"
GONOSUMDB="**HIDDEN**/*"
GOOS="darwin"
GOPATH="/Users/thanabodee"
GOPRIVATE="**HIDDEN**/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/thanabodee/tools/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/thanabodee/tools/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/thanabodee/src/github.com/wingyplus/md_to_con_table/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x7/tl6gyzn92vzcr35t94xgt6y00000gp/T/go-build295258946=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I using gopls with `vim-lsp` (together with neovim). When calling `LspHover`, I see like the image below:

![Screen Shot 2563-08-21 at 11 05 51](https://user-images.githubusercontent.com/484530/90856112-6c0e2300-e3ab-11ea-8ed7-2bc46ce813fa.png)

### What did you expect to see?
4 space characters.

### What did you see instead?
4 `&nbsp;`.

### More information
Padding was introduced by https://go-review.googlesource.com/c/tools/+/197760 (and related to #34161). But the original converter which written in TypeScript in this [line](https://github.com/microsoft/vscode-go/blob/e3c70486365680580cf57260b4d8905c1dc93527/src/godocToMarkdown.ts#L369) use 4 space padding. I think it can be replace by space characters which is a valid markdown syntax.

**Comment by wingyplus** [comment]
May I ask which markdown spec use in lsp. I didn't see it in lsp specification.

**Comment by wingyplus** [comment]
It seems gopls use GitHub markdown as a markdown specification (https://github.github.com/gfm/). Not sure it's.

**Comment by stamblerre** [comment]
Thanks for this report. Based on the way that [`blackfriday.Run`](https://pkg.go.dev/github.com/russross/blackfriday/v2?tab=doc#Run) is displayed on https://pkg.go.dev, I agree that this is not correct. Here is the before and after in VS Code:

Before:
<img width="1128" alt="Screen Shot 2020-08-25 at 10 17 17 PM" src="https://user-images.githubusercontent.com/5856771/91251780-27c3af80-e72a-11ea-9523-971ad0ca2ce5.png">

After:
<img width="1092" alt="Screen Shot 2020-08-25 at 10 18 14 PM" src="https://user-images.githubusercontent.com/5856771/91251773-25615580-e72a-11ea-9209-410d05f4d696.png">
