### ISSUE TITLE
x/pkgsite: support versions tab for directory view

### ISSUE THREAD

**Issue by julieqiu** [golang/go#40942]
The URL https://pkg.go.dev/golang.org/x/mod?tab=subdirectories currently shows information for `v0.1.0` of that module.

It would be useful to be able to click on the `Versions` tab to see what other versions are known. At the moment, that tab is greyed out.

**Comment by rahulw** [comment]
Hey @julieqiu `mod` is a directory that has packages and commands. In this directory, some of the packages like [lazyregexp](https://pkg.go.dev/golang.org/x/mod@v0.3.0/internal/lazyregexp?tab=versions) have two versions available `v0.2.0` and `v0.3.0` and other packages like [gosumcheck](https://pkg.go.dev/golang.org/x/mod@v0.3.0/gosumcheck?tab=versions) have three different versions. In this case, if we decide to make the tab `Versions` clickable what information should be visible on that tab?

Please let me know what your thoughts are about this. Thanks!

**Comment by julieqiu** [comment]
It should return the package available in the module version corresponding to that path. So for `https://pkg.go.dev/golang.org/x/mod@v0.3.0`, only show packages in `v0.3.0` of golang.org/x/mod.

You should be able to just add a `tabVersions` case to [fetchDetailsForDirectory](https://github.com/golang/pkgsite/blob/52e89c1eaa1d89f2bdffabbacfbe251e1dab4adc/internal/frontend/tabs.go#L209), and use the existing  [fetchVersionDetails](https://github.com/golang/pkgsite/blob/52e89c1eaa1d89f2bdffabbacfbe251e1dab4adc/internal/frontend/versions.go#L64).

Note that this will only work with the [new data model](https://github.com/golang/go/issues/39629), so you will need to add the experiments `use-path-info` and `use-directories` locally. You can do that by running:

`go run devtools/cmd/experiment/experiment.go create use-path-info`
`go run devtools/cmd/experiment/experiment.go create use-directories`

**Comment by rahulw** [comment]
Thanks for the explanation. I will give this try and send a change list by Friday EOD.

Thanks,

**Comment by rahulw** [comment]
Apologies for the delay. Starting work on this now.

**Comment by rahulw** [comment]
Thanks for your help, Julie.

After I created a migration, I was able to add `use-path-info` experiment but `use-directories` experiment is not working. I get error - `2020/09/19 17:30:39 Experiment "use-directories" does not exist.` whenever I run the command 
`go run devtools/cmd/experiment/experiment.go create use-directories`. Do you have suggestions about how to fix this error?

On a side note - I added the password to postgres manually by modifying [devtools/migrate_db.sh ](https://github.com/golang/pkgsite/blob/master/devtools/migrate_db.sh#L21) file. Do you think this should use `GO_DISCOVERY_DATABASE_PASSWORD` environment variable?

Thanks for all your help

**Comment by rahulw** [comment]
Hello,
I managed to fix the issues I mentioned in the previous comment and added a new function as suggested in the [third comment](https://github.com/golang/go/issues/40942#issuecomment-680035549).
While running the server locally I could only see the beta version of the website which did not display the versions tab explicitly. I am unsure if the fix worked or not. Please let me know if I mixed up something.

Thanks,

**Comment by julieqiu** [comment]
We just launched a redesign of pkg.go.dev (see https://github.com/golang/go/issues/41585#issuecomment-718143563), so closing this issue as out of date. Thanks for taking the time to look into it @rahulw!
