### ISSUE TITLE
x/pkgsite: add support for syntax highlighting of code blocks

### ISSUE THREAD

**Issue by codyoss** [golang/go#40952]
# What is the URL of the page with the issue?
 Any containing code blocks. Example: https://pkg.go.dev/cloud.google.com/go/storage?tab=doc#hdr-Objects
 
### What is your user agent?
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36`

### Screenshot
![Screen Shot 2020-08-21 at 9 42 20 AM](https://user-images.githubusercontent.com/6331106/90909258-bfc04280-e392-11ea-9f32-fbd57be02f34.png)

### What did you do?
Navigate to the page.
 
### What did you expect to see?
Code blocks with syntax highlighting.
 
### What did you see instead?
Code blocks as plain text.

**Comment by Groxx** [comment]
While I would also like this: maybe it's a better fit for a generic syntax highlighter browser plugin?  Without _code blocks_ it does seem pretty hard / flaky / possibly frustrating to try to guess and highlight with built-in behavior.
