### ISSUE TITLE
encode/pem: cannot load certificate from os.Getenv

### ISSUE THREAD

**Issue by danielsussa** [golang/go#40957]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Only the latest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kanczuk/.cache/go-build"
GOENV="/home/kanczuk/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="github.com/pismo/*"
GONOSUMDB="github.com/pismo/*"
GOOS="linux"
GOPATH="/home/kanczuk/go"
GOPRIVATE="github.com/pismo/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go/bin"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/bin/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/kanczuk/go/src/github.com/pismo/api-cards-tokenization/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build053400513=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
I've tried to load a PEM certificate using os.Getenv and parsing as a byte array to the AppendCertsFromPEM from x509 package. But when I load from env, it's <strong>aways load as a literal string</strong> and cannot be add to certificates pool. I can only load from a file, but never from a variable loaded from system. 

There is a test for this case: https://play.golang.org/p/zTAPhyz7p5S (the literal on os.Setenv(``) is only for test proposal)

### What did you expect to see?

```go
func main() {
	caCertPool := x509.NewCertPool()
	ok := caCertPool.AppendCertsFromPEM([]byte(os.Getenv("CERTIFICATE")))
	fmt.Println(ok)
}
// output = true
```

### What did you see instead?

```go
func main() {
	caCertPool := x509.NewCertPool()
	ok := caCertPool.AppendCertsFromPEM([]byte(os.Getenv("CERTIFICATE")))
	fmt.Println(ok)
}
// output = false
```

**Comment by asad-urrahman** [comment]
OR use the double quotation marks for certificate contents.
see here (https://play.golang.org/p/40DI3hQ35Z4)

**Comment by davecheney** [comment]
Thank you for your comments. This appears to be working as intended.
