### ISSUE TITLE
cmd/compile: aliases should be used in error messages

### ISSUE THREAD

**Issue by rsc** [golang/go#40965]
Consider 

```
package main

func main() {
	var (
		x rune
		y int
	)
	y = x
}
```

(https://play.golang.org/p/gA4OC1S_718).

The compiler error is:

    ./prog.go:8:4: cannot use x (type rune) as type int in assignment

Note the error (correctly) says rune, not int32. When we introduced rune and byte as aliases we were careful to preserve the right printing even though the two names were equivalent.

It appears the compiler does not extend the same courtesy to explicitly-defined aliases. If instead we use:

```
package main

func main() {
	var (
		x RUNE
		y int
	)
	y = x
}

type RUNE = int32
```
(https://play.golang.org/p/_7cffE6QOjo).

then the compiler error is:

    ./prog.go:8:4: cannot use x (type int32) as type int in assignment

It should say RUNE not int32.

**Comment by ALTree** [comment]
As it was pointed out, this is already tracked as #21866.
