### ISSUE TITLE
cmd/go: 'go list' should support -u=patch

### ISSUE THREAD

**Issue by jerome-laforge** [golang/go#41006]
# Background

Currently, it is not possible to list available update module only for patch.
For example:
```go
module github.com/test/test

go 1.15

require go.mongodb.org/mongo-driver v1.3.6
```

I want to know if a new patch version if available (here v1.3.7 and not v1.4.0), but I don't know how to do.
The given example here https://github.com/golang/go/wiki/Modules#how-to-upgrade-and-downgrade-dependencies is for direct with minor and patch (I just want patch). And yet, the v1.3.7 has been released (https://pkg.go.dev/mod/go.mongodb.org/mongo-driver@v1.3.7).

```bash
$ go list -u -m all | grep "go.mongodb.org/mongo-driver"
go.mongodb.org/mongo-driver v1.3.6 [v1.4.0]
```

# Description
I propose to add -u=patch (as already proposed for `go get`)
```bash
$ go list -u=patch -m all | grep "go.mongodb.org/mongo-driver"
go.mongodb.org/mongo-driver v1.3.6 [v1.3.7]
```

**Comment by bcmills** [comment]
CC @jayconrod @matloob 

Honestly, I'm surprised that `list` doesn't already support `-u=patch`. (I think we should just do this — no need for a formal proposal.)

**Comment by goto1134** [comment]
@bcmills , seems like the review is stuck on waiting for your reply. Could you come back to it when it'll be convenient for you?

**Comment by samthanawalla** [comment]
@rsc @matloob and I discussed this today.
We're going to wait on #67420 to get approved and add this functionality alongside it.
I will close this issue in favor of the other one. :)

**Comment by samthanawalla** [comment]
Marking as duplicate
