### ISSUE TITLE
x/tools/gopls: support custom initial workspace load patterns

### ISSUE THREAD

**Issue by stamblerre** [golang/go#41019]
The `./` and `./...` patterns used for the initial workspace load are specific to `go list` and may not be supported by other go/packages drivers. We should allow users to specify their own patterns based on their drivers via a configuration.

**Comment by ianthehat** [comment]
When we talked about this during the go/packages design we decided that the meanings of some of the core go list patterns would be required for all drivers, and it was up to the driver to translate to something approximately meaningful.

**Comment by ianthehat** [comment]
Also, I think this is probably not needed for 1.0 (nobody is using a different driver yet as far as I can tell)

**Comment by stamblerre** [comment]
Makes sense--sounds like drivers should be supporting `./` and `./...` then. Closing this.
