### ISSUE TITLE
x/build/cmd/gopherbot: ignore Go versions in backport comments after the first period?

### ISSUE THREAD

**Issue by bcmills** [golang/go#41012]
@gopherbot  opened two backport issues in response to https://github.com/golang/go/issues/40999#issuecomment-679293109. However, I had only intended to open one: the second sentence was intended to explain why *not* to open a second backport issue.

Perhaps we could improve the GopherBot parsing heuristics to only backport to versions mentioned in the first sentence?

(CC @golang/osp-team)

**Comment by dmitshur** [comment]
Thanks for report. I understand this issue is the same as #27489.
