### ISSUE TITLE
x/build: freebsd-arm-paulzhol builder is offline

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#41028]
Per https://farmer.golang.org:
```
host-freebsd-arm-paulzhol: 0/0 (1 missing)
```

/cc @andybons @dmitshur @toothrot @paulzhol

**Comment by paulzhol** [comment]
It has been down for several months, I've restored it only this weekend. It keeps dying from out of memory every few builds as far as I can tell.

**Comment by paulzhol** [comment]
I think I am hitting https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=224479#c32 (the work dir, and everything writable on the builder is in a tmpfs /tmp mount and I was using an NFS swapfile - tried with mdconfig and without).
I switched the builder to use a partition based swap. It is still backed by an NFS file, but the hypervisor is managing that device.

**Comment by cagedmantis** [comment]
@paulzhol Thank you!
