### ISSUE TITLE
runtime: TestCgoCCodeSIGPROF failures with SIGQUIT

### ISSUE THREAD

**Issue by bcmills** [golang/go#41036]
[2020-08-25T20:04:27-8381408/openbsd-amd64-64](https://build.golang.org/log/e0988837c8f789308677733f21a97448408f88fd)

See also #38333.

**Comment by bcmills** [comment]
CC @ianlancetaylor @aclements

**Comment by bcmills** [comment]
https://storage.googleapis.com/go-build-log/cd187ecc/linux-arm-aws_8ef98ffa.log (a `linux-amd64-aws` TryBot)

**Comment by cherrymui** [comment]
Is there any new failure for this? Thanks.

**Comment by bcmills** [comment]
Looks like the last one on the dashboard was 2021, and that one had a different stack (not in `mstart1`). 🤔

`greplogs -l -e 'FAIL: TestCgoCCodeSIGPROF .*(?:\n[ ]{4}.*)*SIGQUIT'`
[2021-09-15T03:29:41-b26d325/linux-ppc64le-power9osu](https://build.golang.org/log/78d62c082a63fb7a180ce61a8a4cf338fd30a469)
[2020-08-25T20:04:27-8381408/openbsd-amd64-64](https://build.golang.org/log/e0988837c8f789308677733f21a97448408f88fd)

**Comment by mknyszek** [comment]
Since this is a test failure and unlikely to impact beta users, I'm going to mark this as okay-after-beta1.

**Comment by cherrymui** [comment]
It seems the last failure is [2022-01-05T21:11:50-88cafe0/freebsd-arm64-dmgk](https://build.golang.org/log/73fed4e64b886e0cfc68f88859d22e5741c365d0)
If there is no more failure maybe we can close this? (We can reopen if there is any new failure.)

**Comment by prattmic** [comment]
> It seems the last failure is [2022-01-05T21:11:50-88cafe0/freebsd-arm64-dmgk](https://build.golang.org/log/73fed4e64b886e0cfc68f88859d22e5741c365d0)

This looks like it is TestGoroutineParallelism2. TestCgoCCodeSIGPROF is just waiting behind t.Parallel.

The last case I see is the one @bcmills listed.

`greplogs --dashboard -md -l -e "(?s)FAIL: TestCgoCCodeSIGPROF.*SIGQUIT"`
[2021-09-15T03:29:41-b26d325/linux-ppc64le-power9osu](https://build.golang.org/log/78d62c082a63fb7a180ce61a8a4cf338fd30a469)
