### ISSUE TITLE
x/pkgsite: multi-module projects have confusing versions

### ISSUE THREAD

**Issue by julieqiu** [golang/go#41032]
https://pkg.go.dev/cloud.google.com/go@v0.46.2/storage says cloud.google.com/go/storage v0.46.2 is the latest.

<img width="1183" alt="Screen Shot 2020-08-25 at 1 54 44 PM" src="https://user-images.githubusercontent.com/5943521/91209973-8b25f100-e6da-11ea-88a4-254c2f6e36b8.png">

https://pkg.go.dev/cloud.google.com/go@v0.46.1/storage has a `Go to latest` badge which will take the user to v0.46.2.

But, cloud.google.com/go/storage was carved into its own module after v0.46.2. So, if you go straight to https://pkg.go.dev/cloud.google.com/go/storage (which currently shows https://pkg.go.dev/cloud.google.com/go/storage@v1.10.0), you will get 

<img width="1212" alt="Screen Shot 2020-08-25 at 1 54 33 PM" src="https://user-images.githubusercontent.com/5943521/91209955-83664c80-e6da-11ea-9f43-4014dd4a40f1.png">

**Comment by bcmills** [comment]
#37631 is closely related.
