### ISSUE TITLE
x/pkgsite: please remove github.com/garyburd/redigo it is no longer actively being developed

### ISSUE THREAD

**Issue by I-Cat** [golang/go#41040]
### What did you see instead?

==

https://pkg.go.dev/github.com/garyburd/redigo/redis?tab=doc

This package is discountunied and not at github.com/garyburd/redigo

Please remove or up date thank you

**Comment by wingyplus** [comment]
I think that pkgsite can mark the package on website to deprecated or something when the repository is archived. Not sure about implementation but it would be easy to tell user who find on the that, ok don't use it.

**Comment by I-Cat** [comment]
Ok Thanks for your imput.

**Comment by jba** [comment]
We don't have a deprecation feature yet; see #40357 for a proposal and discussion.

The author of the package or module can have it removed by following the instructions under "Removing a package" on https://go.dev/about.

**Comment by I-Cat** [comment]
Sorry But I am not the author.

**Comment by jba** [comment]
I emailed Gary Burd at the address on his GitHub profile to ask his permission.

**Comment by garyburd** [comment]
Do not remove the package.  Although the package is unmaintained and there's [a replacement](https://godoc.org/github.com/gomodule/redigo/redis) for the package, the package is still in use.

The repository is [archived](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-repositories).  Pkg.go.dev should remove archived packages from search results or move archived packages to the bottom of the search results.

**Comment by jba** [comment]
Filed #41126.
