### ISSUE TITLE
x/pkgsite: https://pkg.go.dev/github.com/pioz/faker

### ISSUE THREAD

**Issue by pioz** [golang/go#41047]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/pioz/faker
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
 
### Screenshot

![screenshot](https://i.imgur.com/vXmU9Ux.png)
 
### What did you do?
 
I see 404, not found.
 
### What did you expect to see?
 
The doc of my package faker in https://github.com/pioz/faker version 0.1.2. 
 
### What did you see instead?

I see 404, not found.

**Comment by cagedmantis** [comment]
May I ask why you are using the replace directive in [this manner](https://github.com/pioz/faker/blob/master/go.mod#L5)?

**Comment by jba** [comment]
It's not there because you told us to remove it, in an email to go-discovery-feedback on August 21.

**Comment by pioz** [comment]
I needed to remove the package github.com/pioz/faker on pkg.go.dev because before was a fork of another package, but then I decided to write my own package. In fact, the current REAL version is v0.1.2 but in pkg.go.dev you could see that the last version is the v1.5.0 (the last version of the fork). 
So I thought about requesting the package be removed and then visit the package page on pkg.go.dev, and clicking the “Request” button, but then I saw that it is not possible. What I would like is to see in https://pkg.go.dev/github.com/pioz/faker the doc about faker on github.com/pioz/faker version 0.1.2.

I hope this is possible otherwise I will have to change the package name, but I don't want to. 🙏🏻

**Comment by pioz** [comment]
> May I ask why you are using the replace directive in [this manner](https://github.com/pioz/faker/blob/master/go.mod#L5)?

I was trying things out, and I forgot to remove that line of code. 🥺

**Comment by jba** [comment]
We can't remove specific versions of a module. If you tag version v1.6.0 and we un-remove it, then you will see your package as the latest and therefore the default, but the forked package will still be there at v1.5.0. Do you want us to un-remove it?

**Comment by pioz** [comment]
Yes, please unremove it.

**Comment by jba** [comment]
Done.

**Comment by pioz** [comment]
I still see 404 :(

**Comment by jba** [comment]
Fixed (but it's still showing v1.5.0 by default).

**Comment by pioz** [comment]
@jba Today I see again 404. Yesterday I was seeing the page correctly. :(

**Comment by jba** [comment]
I think I know what's going on. We're going to have to re-deploy. We'll do that Monday morning.

**Comment by julieqiu** [comment]
Fixed.
