### ISSUE TITLE
cmd/go2go: please update gofmt

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#41053]
Now the translator rejects the following code with `generic.go2:10:20: expected operand, found 'type' (and 4 more errors)`

```go
type genericStream[type T any] struct {
    prevReq  chan struct{}
    prevData chan T
    nextReq  chan struct{}
    nextData chan T
}

func newGenericStream[type T any](gs *genericStream[T]) *genericStream[T] {
    return &genericStream[T]{
        prevReq:  gs.nextReq,
        prevData: gs.nextData,
        nextReq:  make(chan struct{}),
        nextData: make(chan T), 
    }   
}
```

So I just modified like this:

```go
type genericStream[T any] struct {
    prevReq  chan struct{}
    prevData chan T
    nextReq  chan struct{}
    nextData chan T
}

func newGenericStream[T any](gs *genericStream[T]) *genericStream[T] {
    return &genericStream[T]{
        prevReq:  gs.nextReq,
        prevData: gs.nextData,
        nextReq:  make(chan struct{}),
        nextData: make(chan T), 
    }   
}
```
Now the translator translate this code, but `gofmt` will insert the deleted `type` again.

`gofmt` is important because it is the only tool to format *.go2 files.

Or this might be an issue for the translator.

**Comment by griesemer** [comment]
Thanks for this issue. I missed that. Will take care of this today or tomorrow.

**Comment by griesemer** [comment]
This should be fixed now in the dev.go2go branch with https://golang.org/cl/250998.

**Comment by YoshikiShibata** [comment]
@griesemer Thanks for the fix!!!
