### ISSUE TITLE
x/pkgsite: github.com/gotailwindcss/tailwind not updated after adding license

### ISSUE THREAD

**Issue by bradleypeabody** [golang/go#41055]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/gotailwindcss/tailwind?tab=overview
 
### What is your user agent?
 

 
 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
 
### Screenshot
 

 
 
![image](https://user-images.githubusercontent.com/3239710/91371444-d8cb5800-e7c5-11ea-9a72-05e3bb6ced5b.png)

 
### What did you do?
 

Browsed to https://pkg.go.dev/github.com/gotailwindcss/tailwind?tab=overview - noticed missing license message, added, license, refreshed paged multiple times over the course of several hours.
 
### What did you expect to see?
 
The documentation, or at least a different error message.  Commit reference should be latest commit 18fbd6a

I also would expect some mechanism or instructions linked from somewhere on this page to indicate how to force/request an update if it is not automatic.
 
### What did you see instead?

It shows message about missing license.  License was added about 3 hours ago: https://github.com/gotailwindcss/tailwind/commit/09b9e3febc61bab5ae9f2e92dd336137817cd82f

The commit mentioned, 91cc231, is from 3 days ago.

No indication of how to refresh or otherwise correct the problem (at least that I could see/find).

**Comment by jba** [comment]
See the instructions under "Adding a package" on https://go.dev/about. Basically, someone has to `go get` a version through the proxy for us to eventually see it. We haven't seen 09b... yet.

**Comment by bradleypeabody** [comment]
Thanks and I did get this to work by visiting https://proxy.golang.org/github.com/gotailwindcss/tailwind/@latest and then https://proxy.golang.org/github.com/gotailwindcss/tailwind/@v/18fbd6a.info and then waiting for a bit.

Can I suggest something like the following to make this process more obvious:
* A link on the Overview page for the package, perhaps called something like "Update this Package".
* That link should give a simple URL at proxy.golang.org to cause such an update to occur, rather than requiring the maintainer to construct it.
* It should cover how repos that do not yet have explicit version numbers work (common for new projects just being created before they have a roadmap).  E.g. I'm still not clear on which of the above URLs caused the update, because of the caching.  I'm sure I could carefully read through the documentation on proxy.golang.org to figure out exactly what happened, but...
* I also hazard that it should not require me to have to understand how proxy.golang.org works in order to use it.
* It should set the expectation that there is a cache timeout for the new update to appear.

My rationale on this is that as a maintainer, the most common thing I would want to do with pkg.go.dev is "update this to the latest", and while now I understand more about the process, it has not be particularly obvious how all this is supposed to work, and specifically what I need to do as a maintainer to get my stuff to show up as quickly as possible.

**Comment by jba** [comment]
If you visit the URL path `YOUR_MODULE@master`, it will 404 with a button to load the latest version. 

We can consider putting that button on the overview page.

**Comment by julieqiu** [comment]
Closing this issue, since https://pkg.go.dev/github.com/gotailwindcss/tailwind has been updated. I'll open a separate issue for the suggestions in https://github.com/golang/go/issues/41055#issuecomment-682057601.
