### ISSUE TITLE
x/tools/gopls: bad error messages when changing package names

### ISSUE THREAD

**Issue by stamblerre** [golang/go#41061]
Repro case:

```
-- go.mod --
module mod.com
-- foo/foo.go --
package foo
-- foo/bar_test.go --
package foo_
```

Modifying foo/bar_test.go to contain `package foo_test` results in bad error messages (it doesn't recover from expecting that its name is `foo_`.

**Comment by pjweinb** [comment]
Is this a duplicate of #38866?

**Comment by stamblerre** [comment]
Possibly, but I think there are also issues with transitioning from a regular package to an x test.

**Comment by jadekler** [comment]
I've got a repro based on the above testcase, and will start taking a peek soon. Is anyone else working on this, though? Don't want to step on toes. =)

**Comment by pjweinb** [comment]
Go right ahead. i was going to look at #38866 but there's other things to do.

**Comment by stamblerre** [comment]
Let's close this now that the test has been enabled.
