### ISSUE TITLE
Panic with Go versions < 1.15.0 when reading (http.Response).Body

### ISSUE THREAD

**Issue by atc0005** [golang/go#41071]
## Overview

The steps below reproduce a panic with Go versions earlier than `1.15beta1`. If Go 1.15 has the correct behavior, should Go 1.14.x also behave the same?

## Go versions tested

Panics:

- 1.13.14
- 1.13.15
- 1.14.0
- 1.14.1
- 1.14.2
- 1.14.3
- 1.14.4
- 1.14.5
- 1.14.6
- 1.14.7

Does not panic:

- 1.15beta1
- 1.15rc1
- 1.15rc2

## Instructions

1. ```cd /tmp```
1. ```git clone https://github.com/atc0005/go-teams-notify```
1. ```git checkout go-panic-repro```
1. ```docker run --rm -it -v `pwd`:`pwd` -w `pwd` golang:1.15.0 go test -v ./...```
1. ```docker run --rm -it -v `pwd`:`pwd` -w `pwd` golang:1.14.7 go test -v ./...```

### Passing

```ShellSession
=== RUN   TestTeamsClientSend
    send_test.go:100: OK: test 0; test.error is of type *fmt.wrapError, err is of type *fmt.wrapError
    send_test.go:100: OK: test 1; test.error is of type *errors.errorString, err is of type *errors.errorString
2020/08/27 09:18:25 RoundTripper returned a response & error; ignoring response
    send_test.go:100: OK: test 2; test.error is of type *url.Error, err is of type *url.Error
2020/08/27 09:18:25 RoundTripper returned a response & error; ignoring response
    send_test.go:100: OK: test 3; test.error is of type *url.Error, err is of type *url.Error
    send_test.go:100: OK: test 4; test.error is of type *errors.errorString, err is of type *errors.errorString
--- PASS: TestTeamsClientSend (0.00s)
PASS
ok      github.com/atc0005/go-teams-notify/v2   0.005s
```

### Failing

```ShellSession
=== RUN   TestTeamsClientSend
    send_test.go:100: OK: test 0; test.error is of type *fmt.wrapError, err is of type *fmt.wrapError
    send_test.go:100: OK: test 1; test.error is of type *errors.errorString, err is of type *errors.errorString
2020/08/27 09:18:39 RoundTripper returned a response & error; ignoring response
    send_test.go:100: OK: test 2; test.error is of type *url.Error, err is of type *url.Error
2020/08/27 09:18:39 RoundTripper returned a response & error; ignoring response
    send_test.go:100: OK: test 3; test.error is of type *url.Error, err is of type *url.Error
--- FAIL: TestTeamsClientSend (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4d68bd]

goroutine 19 [running]:
testing.tRunner.func1.1(0x6e28e0, 0x99af10)
        /usr/local/go/src/testing/testing.go:988 +0x30d
testing.tRunner.func1(0xc0000ca480)
        /usr/local/go/src/testing/testing.go:991 +0x3f9
panic(0x6e28e0, 0x99af10)
        /usr/local/go/src/runtime/panic.go:969 +0x166
io/ioutil.readAll.func1(0xc00010b6c0)
        /usr/local/go/src/io/ioutil/ioutil.go:30 +0x101
panic(0x6e28e0, 0x99af10)
        /usr/local/go/src/runtime/panic.go:969 +0x166
bytes.(*Buffer).ReadFrom(0xc00010b648, 0x0, 0x0, 0xc0000932b0, 0x0, 0x0)
        /usr/local/go/src/bytes/buffer.go:204 +0x7d
io/ioutil.readAll(0x0, 0x0, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:36 +0xe3
io/ioutil.ReadAll(...)
        /usr/local/go/src/io/ioutil/ioutil.go:45
github.com/atc0005/go-teams-notify/v2.teamsClient.Send(0xc000097650, 0x74596e, 0x26, 0x73b510, 0xb, 0x741bdb, 0x1d, 0x0, 0x0, 0x0, ...)
        /tmp/go-teams-notify/send.go:70 +0x2ab
github.com/atc0005/go-teams-notify/v2.TestTeamsClientSend(0xc0000ca480)
        /tmp/go-teams-notify/send_test.go:89 +0x55e
testing.tRunner(0xc0000ca480, 0x7526e8)
        /usr/local/go/src/testing/testing.go:1039 +0xdc
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1090 +0x372
FAIL    github.com/atc0005/go-teams-notify/v2   0.014s
FAIL
```

## References

- Changes that triggered the panic behavior
  - <https://github.com/atc0005/go-teams-notify/pull/43/commits/6db6217e7daac6da6ed43dd7cf02032a22c84af2>

- Apparent "fix" for the panic
  - <https://github.com/atc0005/go-teams-notify/pull/43/commits/414b97a31efc543cbef48ed51847882e1fde55d7>
    - specifically [line 123](https://github.com/atc0005/go-teams-notify/pull/43/commits/414b97a31efc543cbef48ed51847882e1fde55d7#diff-f78e54225b3d916938acc1771ac7811aR123)
  - note: this does not appear to be strictly *required* for Go 1.15beta1, rc1, rc2 or the 1.15.0 release

**Comment by davecheney** [comment]
There is a bug in your test
```
2020/08/27 09:18:25 RoundTripper returned a response & error; ignoring response
```
This is the fix
```
(~/devel/go-teams-notify) % git diff
diff --git a/send_test.go b/send_test.go
index 6a1d6d1..8824f67 100644
--- a/send_test.go
+++ b/send_test.go
@@ -116,6 +116,9 @@ func TestTeamsClientSend(t *testing.T) {
                client := NewTestClient(func(req *http.Request) (*http.Response, error) {
                        // Test request parameters
                        assert.Equal(t, req.URL.String(), test.reqURL)
+                       if test.resError != nil {
+                               return nil, test.resError
+                       }
                        return &http.Response{
                                StatusCode: test.resStatus,

@@ -124,7 +127,7 @@ func TestTeamsClientSend(t *testing.T) {

                                // Must be set to non-nil value or it panics
                                Header: make(http.Header),
-                       }, test.resError
+                       }, nil
                })
                c := &teamsClient{httpClient: client}
```

**Comment by atc0005** [comment]
Thank you @davecheney, I'll file that and review the changes.

The behavior you note precedes me (confirmed all the way back to v1.2.0) and I had yet to dig into it deep enough to understand all aspects of the test. I'm not sure I would have caught this specific issue for some time (I am still very new to Go).

Regarding the issue I opened here and the difference in behavior between Go 1.14 and 1.15: do you know if Go 1.15's handling of the code within the `go-panic-repro` branch is intentionally different than Go 1.14?

**Comment by davecheney** [comment]
Use the source, Luke.  https://github.com/golang/go/commits/7fbd8c75c6c57e713069a3a405e5cde26cfae090/src/net/http/client.go

**Comment by atc0005** [comment]
> @davecheney: Use the source, Luke. https://github.com/golang/go/commits/7fbd8c75c6c57e713069a3a405e5cde26cfae090/src/net/http/client.go

Fair enough, and thank you for the pointer. 

I didn't realize it was that easy to learn the answer (golang/go#38095, 2d77d3330537e11a0d9a233ba5f4facf262e9d8c). I also failed to realize the scope of your involvement with the project! It appears that I also misunderstood the backporting policy (lots of learning today). 

Based on what you've noted, it doesn't appear that the changes made in 12d02e7d8e7df75ccbf07ec40028329fcc35c55b and 2d77d3330537e11a0d9a233ba5f4facf262e9d8c for golang/go#38095 will be backported to Go 1.14.

That said, thank you for your time, the pointers and your suggested fixes to the current faulty test. I'll go ahead and close this out.

**Comment by davecheney** [comment]
No worries, glad you’ve been able to solve the problem.
