### ISSUE TITLE
cmd/go2go: gofmt doesn't work

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#41079]
go2 version:
```
$ git rev-parse HEAD
af1adc5d8ce8125ae953359402989eb8c14988c5
```

Thanks for fixing gofmt, but another problem.

I declare `Builder` as following:

```go
// Builder is a mutable builder for a Stream. This allows the creation of a
// Stream by generating elements individually and adding them to the Builder.
type Builder[type T any] struct {
}

// Add adds an element to the stream being built.
func (b *Builder[T]) Add(t T) {
    panic("Not Implemented Yet")
}
```
With this declaration, I can compile and run  the following code:

```go
func TestBuilder(t *testing.T) {
    var builder Builder[int]

    for i := 0; i < 100; i++ {
        builder.Add(i)
    }
}
```

However, after gofmt which deletes `type`  from the `Builder` declaration as following:

```go
type Builder[T any] struct {
}
```
Then the testing code above will not be compiled:

```
builder_test.go2:6:21: expected ';', found '['
```

Line 6 is `    var builder Builder[int]` in the above testing code.

**Comment by ianlancetaylor** [comment]
I can't recreate this problem at dev.go2go revision af1adc5d8ce8125ae953359402989eb8c14988c5.  Can you a complete test case?  Thanks.

**Comment by YoshikiShibata** [comment]
@ianlancetaylor 

I changed the subject because the problem happens with gofmt.

If I put everything into one .go2 file, there is no problem. But,

builder.go2:
```
package main

type Builder[T any] struct {
    built bool
    data  []T 
}

func (b *Builder[T]) Add(t T) {
    if b.built {
        panic("Already built state")
    }   
    b.data = append(b.data, t)
}
```

builder_test.go2:
```
package main

import "testing"

func TestBuilder(t *testing.T) {
    var builder Builder[int]

    for i := 0; i < 100; i++ {
        builder.Add(i)
    }   
}
```

Then
```
$ gofmt -w builder_test.go2
builder_test.go2:6:21: expected ';', found '['
```

**Comment by ianlancetaylor** [comment]
Thanks, this should be fixed now on the dev.go2go branch.

**Comment by YoshikiShibata** [comment]
@ianlancetaylor Thanks for the fix. It works now.
