### ISSUE TITLE
cmd/compile/internal/gc: panic in buildssa

### ISSUE THREAD

**Issue by bcmills** [golang/go#41077]
There appears to be a regression in `buildssa` that occasionally causes panics in the builders:

```
        panic: runtime error: invalid memory address or nil pointer dereference
        [signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xaafefc]
        
        goroutine 26 [running]:
        cmd/compile/internal/gc.buildssa(0x0, 0x2, 0x0)
        	/workdir/go/src/cmd/compile/internal/gc/ssa.go:315 +0xfc
        cmd/compile/internal/gc.compileSSA(0x0, 0x2)
        	/workdir/go/src/cmd/compile/internal/gc/pgen.go:317 +0x5d
        cmd/compile/internal/gc.compileFunctions.func2(0xc00081a6c0, 0xc000393e40, 0x2)
        	/workdir/go/src/cmd/compile/internal/gc/pgen.go:382 +0x4d
        created by cmd/compile/internal/gc.compileFunctions
        	/workdir/go/src/cmd/compile/internal/gc/pgen.go:380 +0x129
```

[2020-08-27T18:33:37-ac2a1f8/linux-amd64-sid](https://build.golang.org/log/85e383bebd7c9f36214467023dcddfb0668dbd21)
[2020-08-14T17:45:39-a20cb4c/linux-amd64-nocgo](https://build.golang.org/log/3e455fab10045e66721b52868ae9ad2d5fb802eb)

Marking as release-blocker at least until we understand whether it is actually a regression.

CC @randall77 @dr2chase @mdempsky @cuonglm

**Comment by bcmills** [comment]
This may be a duplicate of (or related to) #38463.

**Comment by bcmills** [comment]
May also be related to #32026.

**Comment by randall77** [comment]
I'm pretty sure this is a dup of #38463. Closing in favor of that one.
