### ISSUE TITLE
x/mobile/cmd/gomobile: does not support ARMv7 builds for ios

### ISSUE THREAD

**Issue by basdevelop** [golang/go#41074]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.7 darwin/amd64

 gomobile version
gomobile version +973feb4 Sat Aug 1 11:21:45 2020 +0000 (android,ios); androidSDK=/Users/wsli/Library/Android/sdk/platforms/android-30

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/wsli/go/bin"
GOCACHE="/Users/wsli/Library/Caches/go-build"
GOENV="/Users/wsli/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/wsli/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.7/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0j/8lghc3kd7yx2c_1lp9zhc6_h0000gn/T/go-build149931103=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
gomobile bind -v -o $(BINDIR)/xxx.framework -target=ios

### What did you expect to see?

frameworks support armv7

### What did you see instead?
 missing required architecture armv7 

ld: warning: Could not find or use auto-linked framework

**Comment by farawaaay** [comment]
+1 for this issue

**Comment by hajimehoshi** [comment]
Go 1.15 no longer supports `darwin/arm`.

**Comment by martisch** [comment]
As seen in the release notes Go 1.15 dropped darwin/arm support:
https://golang.org/doc/go1.15#darwin

Issue for dropping support since new IOS versions do not support 32bit arm https://github.com/golang/go/issues/34751

**Comment by ToJen** [comment]
What's the solution?

**Comment by ToJen** [comment]
Related to https://github.com/golang/go/issues/41300

**Comment by hajimehoshi** [comment]
No solution here. iOS ARMv7 (32bit) is no longer supported by Go.

**Comment by ToJen** [comment]
Ok, what's the best way to run gomobile so that it doesn't try to use arm even though the machine is amd64. Or maybe I should ask, how does one specify the iOS arch to use?

**Comment by hajimehoshi** [comment]
You can specify the architecture by giving e.g, `-target=ios/arm64` to gomobile-build or gomobile-bind. Or, just specifying `-target=ios` should include arm64 version and amd64 version. Your machine's architecture doesn't matter here for iOS (as long as you use macOS).
