### ISSUE TITLE
runtime: _rt0_amd64_windows_lib stack frame not aligned, violates Microsoft x64 ABI

### ISSUE THREAD

**Issue by zhangyoufu** [golang/go#41075]
The actual frame size of `_rt0_amd64_windows_lib` is 0x58 (incl. return address and saved rbp), which does not conform to Microsoft x64 ABI (align to 0x10).

https://github.com/golang/go/blob/73a5c372410adb272b6a63484c9a9de5e93e986c/src/runtime/rt0_windows_amd64.s#L12-L37

[I ran into this issue](https://stackoverflow.com/a/63613284/1016460) when I managed to run latest Go on Windows Server 2003 x64 (unsupported, yes I know). `misc/cgo/testcarchive` failed with `runtime: failed to create new OS thread (22)`, because `NtCreateThread` does not accept an unaligned `ThreadContext` pointer (at 0xXXXXXX8). 

Save and restore these registers looks strange for me. `RBX` is callee-saved, but we didn't tamper it. `RAX`/`RCX`/`RDX` are volatile, we don't have to save and restore them.

```
TEXT _rt0_amd64_windows_lib(SB),NOSPLIT|NOFRAME,$0
        // Create a new thread to do the runtime initialization and return.
        MOVQ    $_rt0_amd64_windows_lib_go(SB), CX
        MOVQ    $0, DX
        MOVQ    _cgo_sys_thread_create(SB), AX
        JMP     AX
```
This works for me. I don't think this change will break JNI usage, as mentioned in #30944.

**Comment by alexbrainman** [comment]
> [I ran into this issue](https://stackoverflow.com/a/63613284/1016460) when I managed to run latest Go on Windows Server 2003 x64 (unsupported, yes I know). `misc/cgo/testcarchive` failed with `runtime: failed to create new OS thread (22)`, because `NtCreateThread` does not accept an unaligned `ThreadContext` pointer (at 0xXXXXXX8).

Is there any way for me to reproduce this problem? Regardless, please send your change, if you like, and I will review it.

> Save and restore these registers looks strange for me. `RBX` is callee-saved, but we didn't tamper it. `RAX`/`RCX`/`RDX` are volatile, we don't have to save and restore them.

We definitely need to leave 4 words on stack for AX, BX. DX and CX. I agree we don't need to restore BX. DX and CX. I am not familiar with BP here. But I suggest you leave code alone as is, just add code to align stack before CreateThread.

Thank you.

Alex

**Comment by odeke-em** [comment]
Thank you for the report and suggestion for the change, @zhangyoufu! Thank you @alexbrainman for the response, and for imploring a CL; @zhangyoufu please go ahead, the tree for Go1.17 will open soon and it would be nice to have you as a contributor. Punting this to Go1.17.
