### ISSUE TITLE
testing: Don't silently ignore nested t.Cleanup calls

### ISSUE THREAD

**Issue by prashantv** [golang/go#41085]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/opt/go/path/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/opt/go/path"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/user/.gimme/versions/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/.gimme/versions/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/go-test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build146632005=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Call `t.Cleanup` from inside of a cleanup function,

```go
package main

import (
	"fmt"
	"testing"
)

func TestCleanup(t *testing.T) {
	t.Cleanup(func() {
		fmt.Println("cleanup initial")
		t.Cleanup(func() {
			fmt.Println("nested cleanup")
		})
	})

	fmt.Println("run test")
}
```

### What did you expect to see?

Either the newly added `Cleanup` function to be run immediately after the initial clean up (to respect LIFO order) or for the `Cleanup` call to cause the test to be marked as failed.

### What did you see instead?

The nested cleanup function is ignored silently,
```
=== RUN   TestCleanup
run test
cleanup initial
--- PASS: TestCleanup (0.00s)
PASS
ok  	command-line-arguments	0.004s
```

**Comment by seankhliao** [comment]
I believe this is a misuse of `t.Cleanup`, your second call is only registered when the first one is run (at the end of the tests) and not at the beginning of the test

**Comment by cagedmantis** [comment]
This does seem like a misuse of `t.Cleanup`. Silently failing seems odd though.

/cc @mpvl

**Comment by ianlancetaylor** [comment]
CC @rogpeppe

**Comment by ianlancetaylor** [comment]
I'll send a CL.
