### ISSUE TITLE
x/website: ref/mod go.mod section has broken ids

### ISSUE THREAD

**Issue by seankhliao** [golang/go#41080]
### What version of Go are you using (`go version`)?

current website

### Does this issue reproduce with the latest release?

repros with https://tip.golang.org/ref/mod

### What operating system and processor architecture are you using (`go env`)?

Google Chrome | 85.0.4183.83

### What did you do?

visit  https://golang.org/ref/mod and click on the `require directive` link in table of contents

### What did you expect to see?

link/jump to "require directive" section

`<h3 id="go.mod-require" class="mod-require"><code>require</code> directive</h3>`

### What did you see instead?

link/jump to "go.mod files" section

`<h3 id="go" class="mod-require"><code>require</code> directive</h3>`

### additional info

it appears that the entire "go.mod files" section has their ids truncated to just `go`

**Comment by jayconrod** [comment]
[CL 248617](https://go-review.googlesource.com/c/website/+/248617) fixes this.

@bcmills @matloob Please review 🥺
