### ISSUE TITLE
x/website: Black Lives Matter

### ISSUE THREAD

**Issue by cybercrypt13** [golang/go#41094]
### What version of Go are you using (`go version`)?

<pre>
$ go version
Not related which is the entire point!!
</pre>

### Does this issue reproduce with the latest release?

Yes, it irritates me the same every time I open your page.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
The summary is that you need to remove Black Lives Matters banner from the site.  
GO is not a political statement and is instead an open source project.  
I know Google is so far left they can't see straight any longer but I don't 
understand why we need to get a programming language involved.  
BLM is a terrorist organization by every definition and even the Democrats are 
starting to distance themselves from them.  They are nothing more than a bunch 
of lesbian marxist that want nothing short of destroying the United States.  
They have said it numerous times on interviews and on their website.  They have 
received millions of dollars in donations yet have donated not a single penny to 
helping anyone out but themselves.

So by supporting them you are also supporting the destruction of the United States 
which I can't stand behind.  Please identify why you think a BLM banner needs to be 
blasted across your website yet you have never had any other banner supporting the 
fight against child traffic, child porn, abortions or any other subject matter.

I can only add that you must also be racist since all the other lives must not matter to you.  
An open source project that hundreds of people give their time to, should not be involved
 in political statements of any kind and I ask that you remove the banner.

thank you,

Glenn
</pre></details>

### What did you do?
I read it and was disappointed.

### What did you expect to see?

Nothing

### What did you see instead?
Ignorance

**Comment by ALTree** [comment]
This is a dup of #39850 (and a few others). See the comments there for a link to a mailing list discussion about the matter. The bottom line -if you don't feel like reading the whole thing- is that it was decided that the banner won't be removed.

> Yes, it irritates me the same every time I open your page.

If you use an adblocker, adding this line:

```
go.dev##.Banner
```

to the filter list will make the banner disappear.

Closing here.

**Comment by andreypanin** [comment]
Thank you, @ALTree .

**Comment by cybercrypt13** [comment]
I love how you guys are perfectly ok throwing social justice in our faces but when we complain you shut down the entire argument.  I would even bet most of you aren't even from the US and have no idea what is really going on here.  You probably get all of your news from CNN.
