### ISSUE TITLE
cmd/compile: ambiguous TODO in ssa/html.go

### ISSUE THREAD

**Issue by xiyichan** [golang/go#41098]
### What version of Go are you using (`go version`)?

<pre>
$ go version
master
</pre>

### What did you do?
cmd/compile/internal/ssa/html.go:122

![image](https://user-images.githubusercontent.com/34647972/91591249-3bbc1b00-e98f-11ea-8178-a44cea4b972f.png)

Use GOSSAFUNC to generate ssa.html.
This is the original state.
![image](https://user-images.githubusercontent.com/34647972/91591819-1b409080-e990-11ea-9d16-fbc38368e57b.png)

Is this hoping to be optimized like this?
![image](https://user-images.githubusercontent.com/34647972/91591513-9ce3ee80-e98f-11ea-92ed-f0c666a065e1.png)

Or other styles?

**Comment by randall77** [comment]
@bradford-hamilton

**Comment by ALTree** [comment]
The comment was introduced in afc480bab447c0fefe26a69e4221d93673021e98.

**Comment by xiyichan** [comment]
Maybe not the letters are rotated 90 degrees. Could it be that the title is rotated 90 degrees?

**Comment by josharian** [comment]
See https://go-review.googlesource.com/c/go/+/226209/comment/d6b6d7d5_a01a22b1/. TL;DR: It'd better to use `sideways-lr` instead of `vertical-lr`, but it's not widely enough available: https://caniuse.com/#search=sideways-lr

**Comment by xiyichan** [comment]
> See https://go-review.googlesource.com/c/go/+/226209/comment/d6b6d7d5_a01a22b1/. TL;DR: It'd better to use `sideways-lr` instead of `vertical-lr`, but it's not widely enough available: https://caniuse.com/#search=sideways-lr

ok，I try to use sideways-lr.

**Comment by bradford-hamilton** [comment]
> > See https://go-review.googlesource.com/c/go/+/226209/comment/d6b6d7d5_a01a22b1/. TL;DR: It'd better to use `sideways-lr` instead of `vertical-lr`, but it's not widely enough available: https://caniuse.com/#search=sideways-lr
> 
> ok，I try to use sideways-lr.but only firefox support this.

Hey, I think I'm seeing the confusion and sorry this is my fault... The comment should actually say 180 degrees. The original look that we wanted with `sideways-lr` reads from bottom to top & left to right. @xiyichan does that help some?

**Comment by xiyichan** [comment]
> > > See https://go-review.googlesource.com/c/go/+/226209/comment/d6b6d7d5_a01a22b1/. TL;DR: It'd better to use `sideways-lr` instead of `vertical-lr`, but it's not widely enough available: https://caniuse.com/#search=sideways-lr
> > 
> > 
> > ok，I try to use sideways-lr.but only firefox support this.
> 
> Hey, I think I'm seeing the confusion and sorry this is my fault... The comment should actually say 180 degrees. The original look that we wanted with `sideways-lr` reads from bottom to top & left to right (if I'm remembering correctly). @xiyichan does that help some?

yes, It should be rotated 180 degrees.I try to use other css to achieve.

**Comment by xiyichan** [comment]
> > > > See https://go-review.googlesource.com/c/go/+/226209/comment/d6b6d7d5_a01a22b1/. TL;DR: It'd better to use `sideways-lr` instead of `vertical-lr`, but it's not widely enough available: https://caniuse.com/#search=sideways-lr
> > > 
> > > 
> > > ok，I try to use sideways-lr.but only firefox support this.
> > 
> > 
> > Hey, I think I'm seeing the confusion and sorry this is my fault... The comment should actually say 180 degrees. The original look that we wanted with `sideways-lr` reads from bottom to top & left to right (if I'm remembering correctly). @xiyichan does that help some?
> 
> yes, It should be rotated 180 degrees.I try to use other css to achieve.

like this?
![image](https://user-images.githubusercontent.com/34647972/91632469-57690500-ea13-11ea-8d55-07c6576093f0.png)

**Comment by bradford-hamilton** [comment]
@xiyichan yes actually that is very similar, if not exactly what we wanted!

**Comment by bradford-hamilton** [comment]
> > > > > See https://go-review.googlesource.com/c/go/+/226209/comment/d6b6d7d5_a01a22b1/. TL;DR: It'd better to use `sideways-lr` instead of `vertical-lr`, but it's not widely enough available: https://caniuse.com/#search=sideways-lr
> > > > 
> > > > 
> > > > ok，I try to use sideways-lr.but only firefox support this.
> > > 
> > > 
> > > Hey, I think I'm seeing the confusion and sorry this is my fault... The comment should actually say 180 degrees. The original look that we wanted with `sideways-lr` reads from bottom to top & left to right (if I'm remembering correctly). @xiyichan does that help some?
> > 
> > 
> > yes, It should be rotated 180 degrees.I try to use other css to achieve.
> 
> like this?
> ![image](https://user-images.githubusercontent.com/34647972/91632469-57690500-ea13-11ea-8d55-07c6576093f0.png)

@xiyichan yes actually that is very similar, if not exactly what we wanted!

**Comment by xiyichan** [comment]
> > > > > > See https://go-review.googlesource.com/c/go/+/226209/comment/d6b6d7d5_a01a22b1/. TL;DR: It'd better to use `sideways-lr` instead of `vertical-lr`, but it's not widely enough available: https://caniuse.com/#search=sideways-lr
> > > > > 
> > > > > 
> > > > > ok，I try to use sideways-lr.but only firefox support this.
> > > > 
> > > > 
> > > > Hey, I think I'm seeing the confusion and sorry this is my fault... The comment should actually say 180 degrees. The original look that we wanted with `sideways-lr` reads from bottom to top & left to right (if I'm remembering correctly). @xiyichan does that help some?
> > > 
> > > 
> > > yes, It should be rotated 180 degrees.I try to use other css to achieve.
> > 
> > 
> > like this?
> > ![image](https://user-images.githubusercontent.com/34647972/91632469-57690500-ea13-11ea-8d55-07c6576093f0.png)
> 
> @xiyichan yes actually I think this is exactly what we wanted!

@bradford-hamilton ok,I will submit a CL.
