### ISSUE TITLE
x/pkgsite: forward slash does not initiate find in page on Firefox

### ISSUE THREAD

**Issue by emilal** [golang/go#41093]
### What is the URL of the page with the issue?
https://pkg.go.dev/k8s.io/client-go/kubernetes?tab=doc

 
 
### What is your user agent?
 

Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0
 
 
### Screenshot
 

![Screenshot_2020-08-28 kubernetes package · pkg go dev](https://user-images.githubusercontent.com/17849499/91564103-63d05d80-e940-11ea-8765-af65ff23a044.png)
 
 
### What did you do?
 

 
Used the '/' key
 
 
### What did you expect to see?
 
 Firefox' "find in page"
 
### What did you see instead?

Nothing. Something on the site seems to break '/' searching. (It was also broken on godoc.org, where it highlighted a search box that didn't search in the page.)

**Comment by jamalc** [comment]
Fixed
