### ISSUE TITLE
x/pkgsite: page titles are not descriptive

### ISSUE THREAD

**Issue by jba** [golang/go#41105]
home page: Current page title reads "pkg.go.dev" which contains no semantic content beyond the URL. A better page title would be "Home - Go Package Discovery"

search results page: Current page title reads "[query string] - pkg.go.dev" this does not indicate the purpose of this page. A better title would be "Results for [query string] - Go Package Discovery"

details page: Current title reads "[package name] package - pkg.go.dev" this is not descriptive, and can be confusing if the user has searched for a package exactly, and opened the details page in a new tab. For instance, searching "logrus" and opening the logrus package details in new tab will show two tabs "logrus package - pkg.go.dev" and "logrus - pkg.go.dev" which do not clearly distinguish between Results and Details pages. A better title for details page would be "[package name] Package Details - Go Package Discovery"

**Comment by sudo-sturbia** [comment]
@jba I would like to claim this if it's possible.

**Comment by jba** [comment]
@jamalc WDYT?
