### ISSUE TITLE
cmd/go: preserve sums for contents of modules required by go.mod

### ISSUE THREAD

**Issue by jayconrod** [golang/go#41103]
### What version of Go are you using (`go version`)?

`3b6c812f3defa90bfd7dbddf24bc6135adc5a7eb`

### Does this issue reproduce with the latest release?

No, this is a regression in 1.16 development, probably caused by [CL 237017](https://go-review.googlesource.com/c/go/+/237017).

### What did you do?

`go get` any module that has no package in its root directory.

```
go mod init m
go get golang.org/x/tools
grep 'golang.org/x/tools [^/]* ' go.sum
```

`go get` will add a sum for the module's `go.mod` file to `go.sum`, but it won't add a sum for the module's content to `go.sum`.

### What did you expect to see?

`go get` should add sums for the module's `go.mod` file and its content to `go.sum`.

### What did you see instead?

`go get` only adds a sum for the module's `go.mod` file.

**Comment by ekalinin** [comment]
Looks like it fixed:

```
➜ git log -n1 | head -n5
commit ba0fab3cb731fe9a383bd61c3480cccfe32bb1f4
Author: Ian Lance Taylor <iant@golang.org>
Date:   Sat Aug 29 14:11:18 2020 -0700

    debug/elf: run relocation tests in parallel

➜ ./make.bash

➜ go version               
go version devel +ba0fab3cb7 Sun Aug 30 03:53:59 2020 +0000 linux/amd64

➜ cat cmd/go/testdata/script/mod_get_gosum_fill.txt      
go mod init m
go get rsc.io/sampler
grep 'rsc.io/sampler [^/]* ' go.mod
grep 'rsc.io/sampler [^/]* ' go.sum
cmp go.sum x.sum
-- x.sum --
golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c h1:pvCbr/wm8HzDD3fVywevekufpn6tCGPY3spdHeZJEsw=
golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c/go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=
rsc.io/sampler v1.99.99 h1:iMG9lbEG/8MdeR4lgL+Q8IcwbLNw7ijW7fTiK8Miqts=
rsc.io/sampler v1.99.99/go.mod h1:T1hPZKmBbMNahiBKFy5HrXp6adAjACjK9JXDnKaTXpA=

➜ go test cmd/go -run=TestScript/mod_get_gosum_fill   
ok  	cmd/go	(cached)
```

**Comment by jayconrod** [comment]
@ekalin `rsc.io/sampler` has a package in its root directory, so it's not affected by this issue.

This is specifically about modules without packages in their root directories, like `golang.org/x/tools`.
