### ISSUE TITLE
x/exp/cmd/gorelease: current and prior versions should not be considered valid

### ISSUE THREAD

**Issue by jadekler** [golang/go#41110]
```
deklerk at deklerk-macbookpro in ~/workspace/lean on garbage
$ git tag
v0.1.0
deklerk at deklerk-macbookpro in ~/workspace/lean on garbage
$ gorelease -version=v0.1.0
Inferred base version: none
v0.1.0 is a valid semantic version for this release.
$ gorelease -version=v0.0.1
Inferred base version: none
v0.1.0 is a valid semantic version for this release.
```

As you can see, gorelease is fine with a proposed version that is equivalent to an existing version, and a proposed version that is before an existing version. Most likely the issue is that it is not inferring the existing version.

**Comment by jayconrod** [comment]
Let's consolidate this with #37562, which is pretty similar. I've added a note there that `gorelease` should report a diagnostic if an existing version is specified explicitly.

Prior versions are fine, as long as they don't already exist. For example, someone might tag a new minor release `v1.4.0`, then later tag new patch releases on an old branch `v1.3.5`, `v1.3.6`.

**Comment by jadekler** [comment]
SGTM.
