### ISSUE TITLE
internal/poll: fcntl() should loop on EINTR

### ISSUE THREAD

**Issue by networkimprov** [golang/go#41115]
The internal/poll.fcntl sites need an EINTR loop. The docs list `EINTR` for some features, and darwin `F_FULLFSYNC` hits the disk.
https://man7.org/linux/man-pages/man2/fcntl.2.html

https://github.com/golang/go/blob/master/src/internal/poll/fcntl_libc.go
https://github.com/golang/go/blob/master/src/internal/poll/fcntl_syscall.go
https://github.com/golang/go/blob/master/src/internal/poll/fd_fsync_darwin.go
possibly others...

It might be worth a comment on poll.CloseFunc, to note that errors don't mean failure, so retry is incorrect:
https://man7.org/linux/man-pages/man2/close.2.html

Also, seems like a backport fix...

@gopherbot add NeedsFix
cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Note that we never call `fcntl` with the operations that the GNU/Linux man page says can return `EINTR`.

I guess we do need a loop on Darwin, though.

**Comment by ianlancetaylor** [comment]
We aren't going to backport any changes in this area, any `EINTR` errors are not a regression.

**Comment by networkimprov** [comment]
I'd worry that some other `fcntl()` op might return `EINTR` -- if not now, later.
