### ISSUE TITLE
x/tools/internal/imports: should not use "." in the first component to decide standard library

### ISSUE THREAD

**Issue by linzhp** [golang/go#41118]
[x/tools/internal/imports](https://github.com/golang/tools/blob/84ab570110b3eba77a314c79f9f7734fe681a60c/internal/imports/fix.go#L53-L59) uses "." in the first component of import path to decide whether an import is a standard library. This is not reliable as some orgs may prefix generated code with "mock", "proto" etc to keep them separate from regular code.

A more reliable approach is [github.com/bazelbuild/bazel-gazelle/language/go.IsStandard](https://github.com/bazelbuild/bazel-gazelle/blob/master/language/go/resolve.go#L177-L179).

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zplin/Library/Caches/go-build"
GOENV="/Users/zplin/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zplin/gocode/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zplin/gocode"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bf/3ympgpy92txgknkb4z30dldh0000gn/T/go-build397579031=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by mvdan** [comment]
I disagree; see https://github.com/golang/go/issues/32819. In particular:

> Import paths without dots are reserved for the standard library and toolchain.

It's true that this is not well documented yet, but that's why the issue linked above is open.

/cc @bcmills @heschik

**Comment by linzhp** [comment]
OK. Since this is intentional, I will close this ticket.
