### ISSUE TITLE
cmd/go2go: usage of interface with type list not as type constraint shouldn't be allowed

### ISSUE THREAD

**Issue by tdakkota** [golang/go#41124]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +ea8318cad7 Sat Aug 29 01:02:37 2020 +0000 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
n/a

### What operating system and processor architecture are you using (`go env`)?
- go2go playground
- windows/amd64

### What did you do?
https://go2goplay.golang.org/p/fD4PjTJLgdz

### What did you expect to see?
Successful compilation or better error message.

### What did you see instead?
```
# play
./prog.go2:8: undefined: Nat
```

**Comment by tdakkota** [comment]
Seems like bug in the translation tool
```go
type Nat interface {
	type Zero, Succ
}

type Zero struct{}
type Succ struct{ Nat }
```
becomes

```go
type Zero struct{}
type Succ struct{ Nat }

type Importable୦ int
```
where Nat is not defined.

**Comment by ianlancetaylor** [comment]
This shouldn't pass the type checker.  You aren't allowed to embed an interface with a type list into a struct.  An interface with a type list can only be used as a type constraint, not as a general type.

So, yes, the translation tool mishandles it, but this code shouldn't get to the translation tool at all.

**Comment by tdakkota** [comment]
```go
var _ map[A]struct{}
var _ map[int]A
var _ []A
var _ chan A
```
https://go2goplay.golang.org/p/TKaDmb6jrop
passes the type checker too

**Comment by griesemer** [comment]
Fixed on dev.go2go branch.
