### ISSUE TITLE
Go Get goes silent while not doing anything

### ISSUE THREAD

**Issue by gitcloneguy** [golang/go#41131]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.6 linux/arm
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="arm"
GOBIN=""
GOCACHE="/home/pi/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pi/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.11"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.11/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build866718468=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

i did go get -u rsc.io/2fa, just as stated in the docs for https://github.com/rsc/2fa
 go get just goes silent, no output, no install.

### What did you expect to see?

be able run 2fa

### What did you see instead?
command not found

**Comment by ianlancetaylor** [comment]
Is `/home/pi/go/bin` on your `PATH`?

**Comment by gitcloneguy** [comment]
no, will add. I installed go with apt-get, yet you can still run the command go somehow

**Comment by gitcloneguy** [comment]
it seems that has gotten me further but now I have ":~ $ go get -u rsc.io/2fago
# cd .; git clone https://github.com/rsc/2fago /home/pi/go/src/rsc.io/2fago
Cloning into '/home/pi/go/src/rsc.io/2fago'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package rsc.io/2fago: exit status 128"

**Comment by gitcloneguy** [comment]
this is probably nothing to do with go so I will close the issue

**Comment by gitcloneguy** [comment]
ok so I added go's bin to my path, but now when I export the path it says: 


 export $PATH
-bash: export: `/home/pi/.nvm/versions/node/v14.2.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin': not a valid identifier

and go get goes silent again

**Comment by ianlancetaylor** [comment]
You have to write `export PATH`, not `export $PATH`.  This doesn't have anything to do with Go, it's how Unix shells work.

**Comment by gitcloneguy** [comment]
alright, let's re lets do export PATH. it went silent
