### ISSUE TITLE
x/tools/cmd/present: improper handling of "pressing enter" while editing

### ISSUE THREAD

**Issue by Hamza141** [golang/go#41139]
### What version of Go are you using (`go version`)?
<pre>
go version go1.15 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Hamza\AppData\Local\go-build
set GOENV=C:\Users\Hamza\AppData\Roaming\go\env  
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Hamza\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Hamza\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Projects\tools\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=R:\Temp\go-build900148230=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Given the following `.slide` file
<pre>
Let's break stuff

* Time to break
.play -edit break.go
</pre>

And the following `go` file
<pre>
package main

import (
	"fmt" // this is a comment
)

func main() {
	fmt.Println("Hello world!")
}
</pre>

Running go present and navigating to the second slide with the editable code.

Importing `time` in the slide while presenting like so
<pre>
package main

import (
	"fmt" // this is a comment
        "time"
)

func main() {
	fmt.Println("Hello world!")
}
</pre>

And then running the code.

### What did you expect to see?
There should be an error because `time` is not in use.

### What did you see instead?
It still shows the `Hello world!` output.

### Further explanation (with pics)
I investigated this further and it looks like the issue is on the html side.

Here's how the html looks like initially
![image](https://user-images.githubusercontent.com/14940503/91646782-bbde9100-ea20-11ea-9bc6-864ba7969aa9.png)

Pressing enter in the slide code adds another `<pre>` tag that essentially splits the code
![image](https://user-images.githubusercontent.com/14940503/91646765-9c476880-ea20-11ea-9d5d-9f011bf5021c.png)

Typing `"time"` doesn't add a new span for it
![image](https://user-images.githubusercontent.com/14940503/91646772-aa958480-ea20-11ea-8885-d4b815fabfb5.png)

This results in `"time"` getting interpreted as being on the same line as the comment (`// this is a comment`).
Therefore, the snippet complies and runs.

**Comment by dmitshur** [comment]
I can reproduce the issue in Chrome and Safari. Relying on `contenteditable="true"` for this seems, and I would guess browsers changed its implementation at some point so it no longer inserts <BR>s. But that code was written very long ago. Also handling the "PRE" tag seems reasonable, let's do it for now before trying to do more.
