### ISSUE TITLE
cmd/vet: warn when return value of context.WithValue is lost

### ISSUE THREAD

**Issue by ancarda** [golang/go#41149]
### What version of Go are you using (`go version`)?

    go version go1.14.7 linux/amd64

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

Not Applicable, but anyway...

<details><summary><code>go env</code></summary><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ancarda/.cache/go-build"
GOENV="/home/ancarda/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ancarda/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build172081220=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/NY8BWaciqad

```go
package main

import (
	"context"
	"fmt"
)

func f(ctx context.Context) {
	context.WithValue(ctx, "foo", -6)
}

func main() {
	ctx := context.TODO()
	f(ctx)
	fmt.Println(ctx.Value("foo"))
}
```

### What did you expect to see?

An error indicating that line 9 has a bug; that is, `WithContext` returns a new context but is not returned. Perhaps something like:

    ./main.go:9:2: Context.WithValue returns a new instance, which is lost.

### What did you see instead?

When I run `go vet` on this code, I don't get any errors.

**Comment by dmitshur** [comment]
/cc @alandonovan per [owners](https://dev.golang.org/owners).

It may be relevant that according to [this tweet](https://twitter.com/dominikhonnef/status/1299941220563775489) and issue https://github.com/dominikh/go-tools/issues/819, this check is planned to be added to staticcheck.

Also /cc @davecheney @Sajmani @dominikh FYI.

**Comment by alandonovan** [comment]
Add context.WithValue to this list?
https://github.com/golang/tools/blob/master/go/analysis/passes/unusedresult/unusedresult.go#L47

**Comment by ancarda** [comment]
Thanks @alandonovan, I've filed a PR here: https://github.com/golang/tools/pull/248 :slightly_smiling_face:

**Comment by dmitshur** [comment]
The x/tools commit will need to be vendored into the main repository so that `cmd/vet` picks it up. See [CL 236138](https://golang.org/cl/236138) for a past example.

Reopening for that.
