### ISSUE TITLE
image/gif: Decode reads the entire animated gif image, even though it returns only the first frame (while DecodeAll exists to read and return all frames)

### ISSUE THREAD

**Issue by kawaiiDango** [golang/go#41142]
### What version of Go are you using (`go version`)?
1.15

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\arn\AppData\Local\go-build
set GOENV=C:\Users\arn\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\arn\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\arn\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\arn\AppData\Local\Temp\go-build610476046=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

<pre>
func test() *image.Image {
	resp, _ := httpClient.Get("https://media.giphy.com/media/URdTwRx7YNcoefXsoi/giphy.gif")
	defer resp.Body.Close()

	fmt.Println("decode started")
	img, err := gif.Decode(resp.Body)
	if err != nil {
		fmt.Println(err)
		panic("gif error")
	}
	fmt.Println("decoded")
	return &img
}
</pre>

### What did you expect to see?

It should stop reading from the stream and return as soon as it is done decoding the first frame. Saves a lot of time and bandwidth for large animated gifs from the network.

### What did you see instead?

reads the entire stream of an animated gif (4.5 MB in this case), taking over a minute for large gifs on a slow connection in this case

**Comment by dmitshur** [comment]
There is a [`DecodeAll`](https://pkg.go.dev/image/gif#DecodeAll) function that reads a GIF image and returns all relevant information. The [`Decode`](https://pkg.go.dev/image/gif#Decode) function returns only the first frame and an error, however it still reads everything.

If I understand correctly, this a feature request to change the behavior of `Decode` so it stops short, in contrast to `DecodeAll`.

However, it would mean `Decode` would no longer reports an error if there is a problem reading something past the first frame.

/cc @nigeltao @robpike per [owners](https://dev.golang.org/owners).

**Comment by nigeltao** [comment]
Sounds like a reasonable behavior change, although I don't have much spare time to work on this.

**Comment by NathanBaulch** [comment]
FWIW, I needed this along with a few other more advanced animated gif features (encoding gifs one frame at a time, comment metadata, etc) so I forked `image/gif` and implemented them here: https://github.com/NathanBaulch/gifx
