### ISSUE TITLE
x/tools/gopls: compilation error pop-up

### ISSUE THREAD

**Issue by PICKQUE** [golang/go#41140]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.15

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\admin\AppData\Local\go-build
set GOENV=C:\Users\admin\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=E:\Go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\Go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\Go\project\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\admin\AppData\Local\Temp\go-build752024006=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

i'm using the vscode as my go-editor, but found the error massage when i try to save this file(ctrl + s)
![image](https://user-images.githubusercontent.com/38390188/91677466-56e87f80-eb75-11ea-9ca5-551070204988.png)

### What did you expect to see?
it'not error message

**Comment by stamblerre** [comment]
Can you please share your `gopls` logs? Information on how to capture them can be found [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs).

**Comment by PICKQUE** [comment]
gopls  error log
like this
![image](https://user-images.githubusercontent.com/38390188/91832796-71efe800-ec78-11ea-83e7-f22b4b370e9e.png)

**Comment by stamblerre** [comment]
You have a typo in your `"go.languageServerFlags"` settings - it should be "serve" not "server".

**Comment by PICKQUE** [comment]
the error message like this?  Is this because of my file upload naming problem?
```
[Trace - 09:56:01.871 AM] Sending request 'textDocument/codeAction - (57)'.
Params: {"textDocument":{"uri":"file:///e%3A/Go/gochat/main.go"},"range":{"start":{"line":0,"character":0},"end":{"line":46,"character":0}},"context":{"diagnostics":[],"only":["source.organizeImports"]}}


[Trace - 09:56:01.872 AM] Received response 'textDocument/codeAction - (57)' in 1ms.
Result: null


[Trace - 09:56:01.874 AM] Sending request 'textDocument/formatting - (58)'.
Params: {"textDocument":{"uri":"file:///e%3A/Go/gochat/main.go"},"options":{"tabSize":4,"insertSpaces":false}}


[Trace - 09:56:01.874 AM] Received response 'textDocument/formatting - (58)' in 0ms.
Result: []


[Trace - 09:56:01.915 AM] Sending notification 'textDocument/didSave'.
Params: {"textDocument":{"uri":"file:///e%3A/Go/gochat/main.go","version":14}}


[Trace - 09:56:02.011 AM] Received notification 'window/logMessage'.
Params: {"type":1,"message":"2020/09/02 09:56:02 go/packages.Load: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- ./]: exit status 1: go: cannot find main module; see 'go help modules'\n\n\tsnapshot=19\n\tdirectory=\n\tquery=[./]\n\tpackages=0\n"}


[Trace - 09:56:02.011 AM] Received notification 'window/showMessage'.
Params: {"type":1,"message":"The code in the workspace failed to compile (see the error message below).\nIf you believe this is a mistake, please file an issue: https://github.com/golang/go/issues/new.\ngo [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- ./]: exit status 1: go: cannot find main module; see 'go help modules'\n: packages.Load error"}


[Trace - 09:56:02.011 AM] Received notification 'window/logMessage'.
Params: {"type":1,"message":"2020/09/02 09:56:02 The code in the workspace failed to compile (see the error message below).\nIf you believe this is a mistake, please file an issue: https://github.com/golang/go/issues/new.: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- ./]: exit status 1: go: cannot find main module; see 'go help modules'\n: packages.Load error\n\tsnapshot=19\n\tdirectory=file:///E:/Go\n"}


[Error - 上午9:56:02] 2020/09/02 09:56:02 go/packages.Load: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- ./]: exit status 1: go: cannot find main module; see 'go help modules'

	snapshot=19
	directory=
	query=[./]
	packages=0

[Error - 上午9:56:02] 2020/09/02 09:56:02 The code in the workspace failed to compile (see the error message below).
If you believe this is a mistake, please file an issue: https://github.com/golang/go/issues/new.: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- ./]: exit status 1: go: cannot find main module; see 'go help modules'
: packages.Load error
	snapshot=19
	directory=file:///E:/Go

[Trace - 09:56:31.873 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/09/02 09:56:31 background imports cache refresh starting\n"}


[Info  - 上午9:56:31] 2020/09/02 09:56:31 background imports cache refresh starting

[Trace - 09:56:31.953 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/09/02 09:56:31 background refresh finished after 80.0042ms\n"}
```

**Comment by stamblerre** [comment]
This issue looks different - please make sure to open your workspace to your module root (the directory containing the `go.mod` file). In your case, I think this would be the `E:\Go\gochat` directory. This is currently a requirement of `gopls`, but we're working on changing that in future versions.

**Comment by PICKQUE** [comment]
but i have this mod file
![image](https://user-images.githubusercontent.com/38390188/91933680-12e3af00-ed1c-11ea-994e-9b4141534b5e.png)

**Comment by stamblerre** [comment]
Yes, but you need to open the `gochat` directory in VS Code, not the top-level directory. This is a current limitation of `gopls` that we are working on addressing. You can also use View -> Add Folder to Workspace and add the gochat directory this way.

**Comment by PICKQUE** [comment]
yes it's working and thankyou very much and hope you have a good sleep
