### ISSUE TITLE
x/website: error and suggestion for tutorials pages

### ISSUE THREAD

**Issue by yoshizzle** [golang/go#41150]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.15
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/josh/.cache/go-build"
GOENV="/home/josh/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/josh/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/josh/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/josh/projects/go/greetings/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build087138363=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I noticed two errors on the tutorial site:

1. https://golang.org/doc/tutorial/call-module-code - Step 3, the line should read:

fmt.Println(message) and not (greeting)

2. https://golang.org/doc/tutorial/handle-errors - Step 1, the "nil" being returned with "message" should probably be blue and bold to match the other new lines of code to be added.

### What did you expect to see?

1. message being printed instead of greeting
2. bolding of new code

### What did you see instead?

as reported above

**Comment by dmitshur** [comment]
Thanks for the report.

/cc @stevetraut
