### ISSUE TITLE
Denial-of-Service at net/url.(*URL).Query by "//%2f"

### ISSUE THREAD

**Issue by dwisiswant0** [golang/go#41153]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/dw1/.go/bin"
GOCACHE="/home/dw1/.cache/go-build"
GOENV="/home/dw1/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dw1/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/6274"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/6274/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build141242694=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```go
package main

import (
	"fmt"
	"net/url"
)

func main() {
	raw := "//%2f?id=1"
	prs, _ := url.Parse(raw)
	qry := prs.Query()

	fmt.Println(qry)
}
```

Initially, I tried to parse query from URLs under several conditions:

| String        	| Status    	|
|---------------	|-----------	|
| `/%2f?id=1`   	| OK        	|
| `//?id=1`     	| OK        	|
| `//%2f?id=1`  	| **PANIC** 	|
| `///?id=1`    	| OK        	|
| `///%2f?id=1` 	| OK        	|

### What did you expect to see?

```go
map[id:[1]]
```

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x49a342]

goroutine 1 [running]:
net/url.(*URL).Query(0x0, 0xa)
        /snap/go/6274/src/net/url/url.go:1032 +0x22
main.main()
        /tmp/query-test.go:11 +0x48
exit status 2
```

**Comment by davecheney** [comment]
I don’t think we can accept this bug report as your sample does not check the error returned from URL.Parse

**Comment by dwisiswant0** [comment]
Aight, but from the conditions that I describe, if I check for an error return:
`invalid URL escape "%2f"`

| String        	| Status    	|
|---------------	|-----------	|
| `/%2f?id=1`   	| PASSED        	|
| `//?id=1`     	| PASSED        	|
| `//%2f?id=1`  	| **NOPE** 	|
| `///?id=1`    	| PASSED        	|
| `///%2f?id=1` 	| PASSED        	|

**Comment by davecheney** [comment]
Would you be able to rewrite your issue report to include correct error handling. Thank you

**Comment by dwisiswant0** [comment]
On it.

**Comment by rsc** [comment]
url.Parse is working correctly here: https://play.golang.org/p/0rVDegfUUIk.
You may not realize that two leading slashes mark a [protocol-relative URL](https://www.paulirish.com/2010/the-protocol-relative-url/).
The parse error happens because %2f is not a valid host name,
in contrast to "x" and "" (an omitted host name).
