### ISSUE TITLE
database/sql: cannot select query when args number is huge

### ISSUE THREAD

**Issue by GlebZabl** [golang/go#41163]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/zabludovsky/go/bin"
GOCACHE="/home/zabludovsky/.cache/go-build"
GOENV="/home/zabludovsky/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="gl.rosst.ru/backend/*"
GONOSUMDB="gl.rosst.ru/backend/*"
GOOS="linux"
GOPATH="/home/zabludovsky/go"
GOPRIVATE="gl.rosst.ru/backend/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/zabludovsky/go/src/awesomeProject1/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build174435943=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
```
package main

import (
	"database/sql"
	"fmt"
	"strconv"

	_ "github.com/lib/pq"
)

func main()  {
	err := selectFromDb(65536)
	if err != nil{
		panic(err)
	}

	println("where was no errors!")
}

func selectFromDb(argsNumber int) (err error){
	//open connect to postgres database, put your database connection string below, instead of second argument
	db, err := sql.Open("postgres", "postgres://mayber:password@localhost:5432/test?sslmode=disable")
	if err != nil {
		return
	}

	//preparing query, you can call this func with argsNumber = 10(or some not huge number)
	//to check that it is working correct
	var args []interface{}
	query := "SELECT id FROM test_tbl WHERE id IN ("
	for i := 0; i < argsNumber; i++ {
		args = append(args, strconv.Itoa(i))
		query = fmt.Sprintf("%s $%d, ", query, i+1)
		fmt.Printf("preparing query, %d/%d \n", i, argsNumber)
	}
	query = fmt.Sprintf("%s);", query[:len(query)-2])
	fmt.Println("preparing finished:")

	//uncomment string bellow to see result query and check it
	//fmt.Println(query)


	//preparing query
	stmt, err := db.Prepare(query)
	if err != nil {
		return
	}

	//selecting
	rows, err := stmt.Query(args...)
	if err != nil{
		return
	}

	//closing db connection
	err = rows.Close()
	if err != nil{
		return
	}

	return
}
```

### What did you expect to see?
```
preparing query, 0/65536
preparing query, 1/65536
...
preparing query, 60535/65536
preparing finished:
where was no errors!
```

### What did you see instead?
```
preparing finished:
panic: sql: expected 0 arguments, got 65536
```
for more details https://github.com/GlebZabl/golang_postgres_bug

**Comment by ainar-g** [comment]
<p>PostgreSQL&#xA0;doesn't support more than&#xA0;65535 query
parameters.&#x2003;See
the&#xA0;<a href="https://github.com/postgres/postgres/blob/7559d8ebfa11d98728e816f6b655582ce41150f3/src/interfaces/libpq/fe-exec.c#L1304">source code</a>.&#x2003;The&#xA0;error
message is weird, but&#xA0;it's <em>probably</em> an&#xA0;error
in&#xA0;<code>github.com/lib/pq</code>,
and&#xA0;not&#xA0;<code>database/sql</code>, although I'm
not&#xA0;sure.</p>

**Comment by GlebZabl** [comment]
@ainar-g nope, that is not postgres limit. i've try query with even 65540 in usual jetbrains db console and it works fine. If you want to make sure, just copy my code, replace 36th string with ```fmt.Printf("preparing query, %d/%d \n", i, argsNumber)```, uncomment printing final query to console(40th string), copy that to your db console and execute. So it is exactly database/sql lib bug, connected with parsing query string

**Comment by GlebZabl** [comment]
@ainar-g I've took a look on source, you have posted, now its really weird that  it works from console, anyway, that is not correct error message and it have to be fixed.

**Comment by ainar-g** [comment]
<p>If&#xA0;you remove the&#xA0;dollar signs, then&#xA0;they are
not&#xA0;parameters, they are literal
values.&#x2003;That's&#xA0;different.&#x2003;There&#xA0;either&#xA0;isn't
a&#xA0;limit on&#xA0;those or&#xA0;it's higher.</p> 

<p>The&#xA0;error message is confusing and&#xA0;should be fixed,
but&#xA0;again, I'm not&#xA0;sure if&#xA0;that's
<code>database/sql</code>'s fault
or&#xA0;the&#xA0;driver's.&#x2003;It's&#xA0;probably the&#xA0;drivers'
responsibility to&#xA0;report such&#xA0;errors.</p>

**Comment by GlebZabl** [comment]
yep, you are right about parameters, it was my stupid mistake.

**Comment by GlebZabl** [comment]
@ainar-g 
find this error rising in src/database/sql/convert.go:201

**Comment by GlebZabl** [comment]
okey, i`ve create pr to github.com/lib/pq with fix, but i think it will take a long time from their side until it will be merged, so it will be great from developers of database/sql to fix it on this library layer.

**Comment by kardianos** [comment]
What is the bug in database/sql? I didn't see it articulated above.

**Comment by GlebZabl** [comment]
@kardianos it will be great if  call of sql.Tx.Prepare() from database/sql will throw some correct error(something like "number of args more then allowed") when it was created with sql.Db initialized with driver "postgres" and args number in query string($1,$2....) more then 65535, because https://github.com/lib/pq (standard postgreSQL driver) throws incorrect error(sql: expected 0 arguments, got 65536) and it goes right through database/sql layer to developers and really confused them.

**Comment by kardianos** [comment]
This limit is specific to postgresql. Yes, the driver should probably error out here. The sql package allows for it to return an error.

I cannot check for this number, as it is by far not the only driver out there. SQL Server also has a limit, but it is different. I cannot know the limit for each database, only the drivers will.

I don't think this is fixable at this layer.
