### ISSUE TITLE
cmd/asm: default include directories should include $GOROOT/pkg/include

### ISSUE THREAD

**Issue by fuzxxl** [golang/go#41166]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 freebsd/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/fuz/.cache/go-build"
GOENV="/home/fuz/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOINSECURE=""
GOMODCACHE="/home/fuz/src/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="freebsd"
GOPATH="/home/fuz/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-I$HOME/include -I/usr/local/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L$HOME/lib -L/usr/local/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build184679857=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Save the following source file as `foo.s`:

    echo '#include "textflag.h"' >foo.s
    go tool asm foo.s

### What did you expect to see?

Nothing.

### What did you see instead?

    foo.s:2: #include: open textflag.h: no such file or directory

The `asm` tool should by default search `$GOROOT/pkg/include` for include files because nearly every Go assembly file will include at least `textflag.h`.  This path is searched when assembling files through `go tool build`, so this discrepancy seems strange and unexpected to me.  Not having to manually specify `-I $GOROOT/pkg/include` would be a nice quality of nice quality of life improvement.

**Comment by cherrymui** [comment]
As you noted, the `-I` flag is passed by the go command if you use go build (or go run, go test, etc.). The assembler is not expected to be invoked by hand in general, although it is possible. If you do that, it is up to you to pass the flag.

Closing as working as intended.

**Comment by fuzxxl** [comment]
That's unfortunate to hear.  I have been using the `asm` tool a lot lately to inspect what the assembler does and to ensure that it does what I intend to do (especially wrt. macro expansions).  Wouldn't it be possible to at least have a short hand convenience option for this behaviour?  Right now, the usability is just very poor.

**Comment by dmitshur** [comment]
@fuzxxl Can this be addressed at a higher level (i.e., a convenience wrapper around `cmd/asm` that takes into account the typical workflow you're describing)?

**Comment by fuzxxl** [comment]
@dmitris Possibly.  But apart from providing the right search path for include directories, I have no idea what else this wrapper would do.  The only idea I have is adding a flag `-S` to `go build` that would invoke `compile` or `asm` on all source files listed in addition to/instead of compilation.  Not sure what the best solution is here.
