### ISSUE TITLE
crypto/x509: CreateCertificate should return a meaningful error instead of panic when passed an unknown ExtKeyUsage

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#41169]
`x509.CreateCertificate` panics if passed a template containing an unknown ExtKeyUsage, [example](https://play.golang.org/p/MOHpd1vMj2O). Probably it'd make more sense to return an error along the lines of `Unknown extended key usage`.

**Comment by FiloSottile** [comment]
(In general, I'd like all crypto functions with an error return value to stop ever returning a panic for any reason at all.)

**Comment by tpaschalis** [comment]
I'll give this a shot tomorrow if there's no objection. I see three cases where a panic is called in the *crypto/x509* package, we could possibly eliminate all of them.
