### ISSUE TITLE
CWE-295 in go SDK，client message was malformed, however, in the server tls authentication, it was found that Go's crypto\x509\x509.go passed authenticated.

### ISSUE THREAD

**Issue by wangting1995** [golang/go#41175]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.14.6
$ grpc version  1.26.0
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
  A certification validation error occurred when using Defensics Fuzz that is a tool for checking security vulnerabilities to test the gRPC service port with SSL authentation.
  We have used the Defensics Fuzz Testing Tool to test the grpc service port. The tool distorted the client certificate signature content and tried to establish communication. The packet capture showed that the client message was malformed, however, in the server tls authentication, it was found that Go's crypto\x509\x509.go passed authentication.
   We highly suspected it that a flaw in Go language tls authentication
Please confirm whether the go language has this error?

### What did you expect to see?

authentication failed

### What did you see instead?
authentication passed

**Comment by davecheney** [comment]
@wangting1995 without a way to reproduce your issue we cannot investigate. Please update the issue to include a self contained program that demonstrates the issue. Thank you.

**Comment by networkimprov** [comment]
@wangting1995 please email more info to security@golang.org. Please do not post it here.
More: https://golang.org/security

cc @FiloSottile 

@gopherbot remove WaitingForInfo

**Comment by FiloSottile** [comment]
Closing this as there is not enough information for an investigation. Please follow golang.org/security if you have a report.
