### ISSUE TITLE
runtime: panic reported on wrong line on deferred statements

### ISSUE THREAD

**Issue by fracasula** [golang/go#41180]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/francesco/.cache/go-build"
GOENV="/home/francesco/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/francesco/go/pkg/mod"
GONOPROXY="github.com/netdata/*"
GONOSUMDB="github.com/netdata/*"
GOOS="linux"
GOPATH="/home/francesco/go"
GOPRIVATE="github.com/netdata/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2 -Wno-incompatible-pointer-types"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build091588623=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

If we try to `close` a `nil` channel on a `defer`, or if we try to call a `nil` function on a `defer`, then we get a `panic` on the `return` statement while the line with the `defer` is not reported in the stack trace.

https://play.golang.org/p/mcO-A4WRWXC

https://play.golang.org/p/eQnYvAcaLCD

### What did you expect to see?

I'd expect to see the `defer` statement in the `panic` stack trace. If you look at the links to the playground above, line 10 is not reported, we can see only lines 12 and 16.

### What did you see instead?

I see only lines 12 and 16, not line 10 (the one with the `defer`).

**Comment by dmitshur** [comment]
Thanks for reporting. Do you know if this happens with older releases too?

/cc @aclements @randall77 @mknyszek @prattmic per [owners](https://dev.golang.org/owners).

**Comment by fracasula** [comment]
@dmitshur I was running on 1.14.3 when I noticed and upgraded to 1.15.1 later just to check if this had been fixed by a newer release. So 1.14.3 is definitely affected. I checked now with 1.13.5 and it is affected as well.

**Comment by randall77** [comment]
This is intentional. We report the line number of the return point, because that's where the defer is executed (not where it is queued up). Discussion of maybe changing the behavior is at #29797. Closing as a dup.
