### ISSUE TITLE
cmd/asm: ARM64 VLD1 from pseudo-register FP results in asm: illegal combination

### ISSUE THREAD

**Issue by paultag** [golang/go#41183]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.1 linux/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOENV="/home/ubuntu/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ubuntu/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/golang/go-1.15"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/golang/go-1.15/pkg/tool/linux_arm64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ubuntu/go/src/hz.tools/sdr/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build634724932=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Using the `VLD1` instruction with a pseudo register such as `FP` results in an `asm: illegal combination`.

For instance, when I try and load the `[4]float32` as a `S4`, I get an `asm: illegal combination` even though the variant using the actual registers works fine.

```
// func x([4]float32, []float32)
TEXT ·x(SB), $0-40
    VLD1 f+0(FP), [V2.S4]
```

### What did you expect to see?

My data in `V2` as an `S4`

### What did you see instead?

```
asm: illegal combination: 00000 (.s:27)	VLD1	a+16(FP), [V2.S4] PSAUTO_8 NONE NONE LIST, 3 13
asm: illegal combination: 00000 (.s:27)	VLD1	a+16(FP), [V2.S4] PSAUTO_8 NONE NONE LIST, 3 13
asm: illegal combination: 00000 (.s:27)	VLD1	a+16(FP), [V2.S4] PSAUTO_8 NONE NONE LIST, 3 13
asm: illegal combination: 00000 (.s:27)	VLD1	a+16(FP), [V2.S4] PSAUTO_8 NONE NONE LIST, 3 13
asm: assembly failed
```

**Comment by paultag** [comment]
My workaround for this, for my fellow nerds who stumble upon this, is to change `[4]float32` to a `*[4]float32`, `MOVD` that to a register, then do a `VLD (R1), [V2.S4]`. Not ideal, but it beats having to work out how to do this by hand :)

**Comment by cherrymui** [comment]
VLD1 instruction doesn't take an offset for the source, so it must be (Rx) instead of something like 16(Rx), also not a symbolic offset like f+0(FP).

You don't have to change the signature of the function. You could MOVD the _address_ of the argument to a register, then VLD1 from there, like `MOVD $f+0(FP), R1; VLD1 (R1), [V2.S4]`.

**Comment by paultag** [comment]
Thanks, @cherrymui !
