### ISSUE TITLE
cmd/go2go: format in playground creates invalid code

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#41195]
The Format button in https://go2goplay.golang.org/ adds a `type` prefix to all the type parameters, which it then rejects as a syntax error.
To reproduce, just go to https://go2goplay.golang.org/ and click Format, then Run.

**Comment by griesemer** [comment]
I assumed this was fixed with https://go-review.googlesource.com/c/go/+/251278 but I guess not. Trying once more.

The real fix is to remove all the various parsing and printing modes again, now that we have presumably settled on the type parameter list syntax.

**Comment by griesemer** [comment]
This is now also fixed in the playground after a recent update.
