### ISSUE TITLE
cmd/go: go install -v -i ... hangs indefinitely with Go 1.15.1 but not 1.13.4

### ISSUE THREAD

**Issue by bullet45** [golang/go#41207]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=C:\Google\GOPATH\bin
set GOCACHE=C:\Users\Will2010\AppData\Local\go-build
set GOENV=C:\Users\Will2010\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Google\GOPATH\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Google\GOPATH
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Google\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Google\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Will2010\AppData\Local\Temp\go-build443042886=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
In Powershell
go get -v -u gopkg.in/couchbase/gocb.v2

Then I tried 
go get -v -u -d gopkg.in/couchbase/gocb.v2
and all packages were downloaded and cursor returned successfully

go install -v -i ...
Hangs indefinitely

### What did you expect to see?
download and install packages

### What did you see instead?
hangs after download

**Comment by davecheney** [comment]
Is there any anti virus or firewall software that may be interfering?

**Comment by bullet45** [comment]
I looked and I don't think so.  Plus, I ended up going back a couple versions to 
go1.13.4.windows-amd64.msi

And I have NO problems now.  Everything is working successfully now including install with go get ...
So I have to believe it is an issue with 
go version go1.15.1 windows/amd64
and 
go1.15.1.windows-amd64.msi

**Comment by dmitshur** [comment]
`go install -v -i ...` means to install packages matching the import path pattern `...`, which matches all packages. Is that what you were trying to do, or did you mean to install fewer packages (perhaps just the ones in a specific project)?

Maybe it matched many packages and was taking a long time to install them. What was CPU usage? What happens if you run `go list ...`?

/cc @bcmills @jayconrod @matloob per [owners](https://dev.golang.org/owners).

**Comment by bullet45** [comment]
This is a brand new install on a new laptop and yes I meant to "install" all of the packages I got.  (...)
At any rate, I'm working on 1.13 now - and don't have time to debug this.  I'll upgrade again with a newer version later.  This ticket may be closed.
