### ISSUE TITLE
cmd/go2go: unexpected successful compilation

### ISSUE THREAD

**Issue by komkom** [golang/go#41203]
### What version of Go are you using (`go version`)?

https://go2goplay.golang.org/

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

google chrome

### What did you do?

I wrote the following
https://go2goplay.golang.org/p/30SD7t_sLOa

### What did you expect to see?

To see a compilation error. 
Or is this expected to compile and `go vet` will warn about it?

### What did you see instead?

Successful compilation

**Comment by rsc** [comment]
I don't believe it is an error to write an unsatisfiable constraint. The design draft even gives an example.
But the one in your program looks perfectly satisfiable to me:

https://go2goplay.golang.org/p/vdIhKL71Lyt

**Comment by komkom** [comment]
Thanks for this! 
But isn't it strange that it is possible to have code with unsatisfiable constraints. Shouldn't it be possible to detect this?
BTW in the example above I was missing that I[X] can implement the same interface as X. 
So is this a correct example for an unsatisfiable constraint https://go2goplay.golang.org/p/YrPhYRchDSH ?

**Comment by griesemer** [comment]
As @rsc pointed out, it is perfectly fine to write constraints that cannot be satisfied. (As an aside, your example can be satisfied: https://go2goplay.golang.org/p/VO-7h04CiAd .) This is not an issue with the prototype; it is permitted by the design draft.

Your 2nd example's constraint can also be satisfied: https://go2goplay.golang.org/p/nkhNZ1cBx-f.

Even in non-generic Go it is possible to write nonsensical code.
