### ISSUE TITLE
os: ExpandEnv: curly brackets not matched correctly

### ISSUE THREAD

**Issue by sding3** [golang/go#41208]
### What version of Go are you using (`go version`)?

go version go1.14.4 linux/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/shang/.cache/go-build"
GOENV="/home/shang/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/shang/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/shang/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build728725462=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Ran the following code:

```
package main

import (
	"fmt"
	"os"
)

func main() {
	s := `${${foo}}`
	handleError(os.Setenv("HOME", "~"))
	handleError(os.Setenv("foo", "HOME"))
	handleError(os.Setenv("{foo}", "bar"))
	handleError(os.Setenv("{${foo}}", "baz"))
	fmt.Println(os.ExpandEnv(s))
}

func handleError(e error) {
	if e != nil {
		panic(e)
	}
}
```

### What did you expect to see?

I expect to see any one of `~`,`${HOME}`,`${bar}`, the empty string, or `baz`

### What did you see instead?

`}`

---

Slightly related: https://github.com/golang/go/issues/35752

**Comment by ianlancetaylor** [comment]
This is working as documented.  `os.ExpandEnv` is not the shell, it's just a simple one level expander.  In the string `${${foo}}`, it replaces `${var}` with the value of `var` in the environment.  In this case `var` is `${foo`. That is the string that appears from `${` to the next `}`.  That string has no value in the environment, so it is replaced with the empty string.  That leaves just the trailing `}`, which is what you see.

**Comment by vatine** [comment]
This is also (effectively) what bash does:
```
test$ echo $foo
bar
test$ echo $bar
gazonk
test$ echo ${${foo}}
bash: ${${foo}}: bad substitution
```
