### ISSUE TITLE
x/tools/gopls: consider supporting script directories with multiple programs

### ISSUE THREAD

**Issue by stamblerre** [golang/go#41206]
Currently, `gopls` only supports directories with a single main, no matter whether you open a single file or a directory. For single files, we load the entire directory, no matter what. Some users create directories with multiple mains, which they run using `go run file.go`. Should `gopls` support such directories? If so, how should it work?

**Comment by bcmills** [comment]
Most single files intended for use with `go run` should be tagged `// +build ignore` or similar, and they necessarily each declare a `func main`. Perhaps you could use unusual build constraints plus `func main` as a heuristic for which mode to use?

**Comment by myitcv** [comment]
Previous discussion: https://github.com/golang/go/issues/33595

**Comment by myitcv** [comment]
Looking at the arguments against this, if someone can come up with a good enough name for the file that contains the build-ignore `main` package, they can use that name for a subdirectory `./internal/$NAME` thereby obviating the need for any kind of single-file support in `gopls`.

The counter argument to this is that there is lots of preexisting code out there that does following the single-file approach.

**Comment by mvdan** [comment]
> Perhaps you could use unusual build constraints plus `func main` as a heuristic for which mode to use?

I think this would work reasonably well. I think it would have covered nearly all the times I've encountered gopls to error in this way.

> they can use that name for a subdirectory `./internal/$NAME` thereby obviating the need for any kind of single-file support in `gopls`.

While I see the point, I disagree. There's nothing wrong with build-tag-ignored one-off programs being part of an existing package. An extra directory with just one file will be more verbose, and an oddity that has never been needed in Go before. Coming up to all those users and telling them they need to change their workflow just to please gopls, and objectively for no other good reason, seems like it won't end well :)

**Comment by quasilyte** [comment]
I don't think this idiom is very common, but apart from the `build ignore` tag there is also a pattern where you put your "scripts" under a "_" prefixed folder, like `_scripts`. This excludes Go files as per-file ignore would, but still keeps them usable with `go run ./_scripts/gendocs.go`.

**Comment by heavenisme** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by findleyr** [comment]
Closing this as gopls recognizes standalone scripts based on the "standaloneTags" setting (which defaults to "ignore").
