### ISSUE TITLE
net/rpc: use of global logger in Server.register

### ISSUE THREAD

**Issue by dangerousvasil** [golang/go#41221]
https://github.com/golang/go/blob/a15df605fc4aa6347494fd55a5c4c6544b0eb981/src/net/rpc/server.go#L267

**Comment by dangerousvasil** [comment]
https://github.com/golang/go/blob/a15df605fc4aa6347494fd55a5c4c6544b0eb981/src/net/rpc/server.go#L244

**Comment by randall77** [comment]
That's what its spec says it does:

```
// It returns an error if the receiver is not an exported type or has
// no suitable methods. It also logs the error using package log.
```

**Comment by mdlayher** [comment]
I'm not sure there's anything to be done here. The behavior is documented and `net/rpc` is frozen anyway, per https://golang.org/pkg/net/rpc/.

I'm going to close this out.
