### ISSUE TITLE
x/tools/gopls: imports differs from goimports

### ISSUE THREAD

**Issue by powerman** [golang/go#41225]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.1 linux/amd64
$ gopls version
golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/powerman/.cache/go-build"
GOENV="/home/powerman/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/powerman/go/pkg/mod"
GONOPROXY="github.com/dentalcpdpro,github.com/mtgroupit,gitlab.qarea.org"
GONOSUMDB="github.com/dentalcpdpro,github.com/mtgroupit,gitlab.qarea.org"
GOOS="linux"
GOPATH="/home/powerman/go"
GOPRIVATE="github.com/dentalcpdpro,github.com/mtgroupit,gitlab.qarea.org"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/home/powerman/tmp/go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build538437635=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```sh
$ cat fmt.go 
package main
func F(*testing.T, time.Time) {}
$ gopls imports fmt.go 
package main

import (
	"testing"
	"time"
)
func F(*testing.T, time.Time) {}
$ goimports fmt.go 
package main

import (
	"testing"
	"time"
)

func F(*testing.T, time.Time) {}
```

### What did you expect to see?

Same output as produced by goimports (empty lines around `import()` block).

### What did you see instead?

Empty line only before but not after `import()` block.

Related: https://github.com/fatih/vim-go/issues/2993

**Comment by stamblerre** [comment]
The `gopls` imports logic is a bit different from `goimports`--it specifically separates import organization from formatting, whereas `goimports` also runs `gofmt`. To get the same experience on the command-line, you would need to run both `gopls imports` and `gopls format`. I would still recommend using `goimports` on the command line, as the `gopls` CLI is meant more to replicate the individual requests.

We might consider a `gopls` command to do both importing and formatting, if you're interested in making a contribution.
