### ISSUE TITLE
cmd/go: inconsistent vendoring in github.com/shurcooL/httpfs and github.com/shurcooL/vfsgen

### ISSUE THREAD

**Issue by donutloop** [golang/go#41229]
I use github.com/shurcooL/vfsgen to generate an asset server and the dep is part of my main application 

### What version of Go are you using (`go version`)?

<pre>
go version go1.15.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/donutloop/.cache/go-build"
GOENV="/home/donutloop/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/donutloop/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/donutloop/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/nix/store/7l6qqnn7dwgpkw633j0d15265dqg503l-go-1.15/share/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/nix/store/7l6qqnn7dwgpkw633j0d15265dqg503l-go-1.15/share/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/donutloop/workspace/src/gitlab.com/lightmeter/controlcenter/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/run/user/1000/go-build732026711=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

```
go mod vendor 
go build 
```

### What did you expect to see?

A successful build

### What did you see instead?

go: inconsistent vendoring in /build/controlcenter-9329fec:
        github.com/shurcooL/httpfs@v0.0.0-20190707220628-8d4bc4ba7749: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/shurcooL/vfsgen@v0.0.0-20200824052919-0d455de96546: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt

**Comment by dmitshur** [comment]
I can't seem to reproduce this:

```
$ export GOPATH=$(mktemp -d)
$ cd $(mktemp -d)
$ git clone https://gitlab.com/lightmeter/controlcenter && cd controlcenter
$ git checkout 9329fecbbdca835b8c3ddf7beda4171cfe6d6a71
$ git status
HEAD detached at 9329fec
nothing to commit, working tree clean
$ go mod vendor 
$ go build 
$ echo $?
0
```

Are you able to provide more information for how to reproduce it?

I've also noticed that running `go mod tidy` produces non-zero output. If the issue happens reproducibly for you, does running `go mod tidy` before `go mod vendor && go build` resolve it for you?

**Comment by donutloop** [comment]
Executing go mod tidy and God mod vendor doesn't help.

* Please install nix package manager on your machine
* Checkout this branch and go to this file https://gitlab.com/lightmeter/controlcenter/-/blob/playground-nixos/packging/nixos/default_v2.nix
* Execute 'nix-build -E 'with import <nixpkgs> { };  callPackage ./default_v2.nix {}'

**Comment by jayconrod** [comment]
I couldn't reproduce this, even at `9329fecbbdca835b8c3ddf7beda4171cfe6d6a71`.

Can you reproduce this without Nix? The code that checks `go.mod` and `vendor/modules.txt` for consistency is relatively small, and if there's an issue that only reproduces on Nix, it seems likely that it's a problem with Nix or the build configuration, not a bug in the go command.
