### ISSUE TITLE
GO Module Tag Issue

### ISSUE THREAD

**Issue by viveknangal** [golang/go#41235]
### What version of Go are you using (`go version`)?

<pre>
go version go1.15.1 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/vivekaggarwal/Library/Caches/go-build"
GOENV="/Users/vivekaggarwal/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/vivekaggarwal/code/golang/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/vivekaggarwal/code/golang"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/q5/0cpzy36s0tx5lqgyy3csq5f00000gp/T/go-build630375978=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
GO is unable to fetch the TAGS for the module 
```
 go list -m -versions github.com/viveknangal/module
```
Because of above issue , Pseudo versions are getting updated in the go.mod file (below output)
```
require github.com/viveknangal/module v0.0.0-20200905160009-e0c20193512d // indirect
```
### What did you expect to see?
The above should return the Tags present on the Github "github.com/viveknangal/module" & the **Tag v1.1.0** should be updated in the **go.mod** file

### What did you see instead?
None of the TAGS returned

**Comment by seankhliao** [comment]
from https://golang.org/ref/mod#versions

> ach version starts with the letter v, followed by a semantic version.
