### ISSUE TITLE
x/website: doc/install has outdated filename for linux

### ISSUE THREAD

**Issue by ipriver** [golang/go#41232]
There is a command on [doc/install page](https://golang.org/doc/install) that uses an outdated filename that is being shown as an example of how to install go for Linux:
`tar -C /usr/local -xzf go1.14.3.linux-amd64.tar.gz`

### What did you expect to see?

`tar -C /usr/local -xzf` command should use the latest archive filename for the current go version

### What did you see instead?

`go1.14.3.linux-amd64.tar.gz` filename is statically defined in the markup.

**Comment by jgeiger-trane** [comment]
Thanks. I searched for x/website since that's the issue that's created for the "Report an issue" on the website.
