### ISSUE TITLE
path/filepath: Rel() fails for UNC volumes when trailing slash is omitted

### ISSUE THREAD

**Issue by tmm1** [golang/go#41230]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.1 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\micro\AppData\Local\go-build
set GOENV=C:\Users\micro\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\micro\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\micro\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\micro\AppData\Local\Temp\go-build149210574=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

```go
package main

import (
        "fmt"
        "path/filepath"
)

func main() {
        fmt.Println(filepath.VolumeName(`\\host\share`))
        fmt.Println(filepath.VolumeName(`\\host\share\`))

        rel, err := filepath.Rel(`\\host\share`, `\\host\share\file.txt`)
        fmt.Printf("rel: %v\n", rel)
        fmt.Printf("err: %v\n", err)

        rel, err = filepath.Rel(`\\host\share\`, `\\host\share\file.txt`)
        fmt.Printf("rel: %v\n", rel)
        fmt.Printf("err: %v\n", err)
}
```

```
\\host\share
\\host\share

rel:
err: Rel: can't make \\host\share\file.txt relative to \\host\share

rel: file.txt
err: <nil>
```

### What did you expect to see?

Expected both invocations of `filepath.Rel` to return the same relative path

### What did you see instead?

First invocation returns an error

cc @alexbrainman

**Comment by tmm1** [comment]
I wrote a failing test here: https://go-review.googlesource.com/c/go/+/253197

```
PS C:\Users\micro\code\go\src> ../bin/go test -v .\path\filepath\ -run TestRel
=== RUN   TestRel
    path_test.go:1209: Rel("\\\\host\\share", "\\\\host\\share\\file.txt"): want "file.txt", got error: Rel: can't make \\host\share\file.txt relative to \\host\share
    path_test.go:1212: Rel("\\\\host\\share", "\\\\host\\share\\file.txt")="", want "file.txt"
--- FAIL: TestRel (0.00s)
FAIL
FAIL    path/filepath   0.260s
FAIL
```

**Comment by alexbrainman** [comment]
> Rel: can't make \\host\share\file.txt relative to \\host\share

Thank you for your report.

I suspect we never implemented Rel bits for UNC rooted paths. I don't have time to do it now. But I will review contribution.

Generally, you should not use Rel on windows. For example, filepath.Rel is broken when we walking from one drive to another. It has no meaning for something like filepath.Rel(c:\a\, d:\a\b).

Alex

**Comment by tmm1** [comment]
Thanks! I understand the limitations of `filepath.Rel`. I'm using it in the context of `filepath.Walk` to get a relative path from the base path I'm walking.

My CL only contains a failing test. I did attempt to make it pass but I wasn't sure where best to fix this case.

**Comment by tmm1** [comment]
I could use some advice on the best way to make this failing test pass.

**Comment by ianlancetaylor** [comment]
Sorry, I'm not sure quite what you are asking.  It seems that you've found a bug in the path/filepath package.  Are you asking how to modify the package so that your test passes?

**Comment by networkimprov** [comment]
cc @rasky @mattn

**Comment by tmm1** [comment]
Yea I'm just confused about where is best to fix this. It's not clear to me if the bug lies in `filepath.Clean`, `filepath.VolumeName` or `filepath.Rel`

**Comment by tmm1** [comment]
I updated my CL with the dumbest possible thing I could do to make the test pass. It still feels like I'm missing a simpler solution, but maybe a special case is the best.

https://go-review.googlesource.com/c/go/+/253197

If someone wants to experiment, here's a playground link with all the windows-specific code paths: https://play.golang.org/p/GhDba2BSex9

**Comment by ianlancetaylor** [comment]
I think the right place to fix this is `filepath.Rel`.

I commented on your CL.  Thanks.
