### ISSUE TITLE
cmd/compile: "<node DDD>" instead of "..." in errors with [...]T

### ISSUE THREAD

**Issue by ainar-g** [golang/go#41247]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
It doesn't reproduce with Go 1.13.  It does reproduce with Go 1.14, 1.15, and `+721819e7ba`.  Going to rebuild a more fresh Go, try the tip, and update the issue in a moment.

Update: also reproduces with:

<pre>$ go version
go version devel +5cc030aa19 Sun Sep 6 20:23:50 2020 +0000 linux/amd64</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ainar/.cache/go-build"
GOENV="/home/ainar/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ainar/go/pkg/mod"
GONOPROXY="REDACTED"
GONOSUMDB="REDACTED"
GOOS="linux"
GOPATH="/home/ainar/go"
GOPRIVATE="REDACTED"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/ainar/go/go1.15"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/ainar/go/go1.15/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build723473563=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/rHDhklq4E7D

```go
func f() [2]int {
	return [...]int{2: 0}
}
```

### What did you expect to see?
In Go 1.13:

```none
# command-line-arguments
go/tmp.go:4:17: cannot use [3]int literal (type [3]int) as type [2]int in return argument
```

### What did you see instead?

```none
# command-line-arguments
go/tmp.go:4:17: cannot use [<node DDD>]int literal (type [3]int) as type [2]int in return argument
```

* * *

I saw that on @davecheney's Twitter and tried looking up “node DDD” in existing issues.  There didn't seem to be one, so I filed this one.

**Comment by cuonglm** [comment]
I think this change is intentional, see [this CL](https://go-review.googlesource.com/c/go/+/197604) for mode details.

**Comment by josharian** [comment]
I’m pretty sure @mdempsky did not intend for <node DDD> to show up in user-facing error messages.

**Comment by mdempsky** [comment]
Oops. Yeah, that error message is wrong.

It should say either `[3]int literal` or `[...]int literal`.

**Comment by ainar-g** [comment]
That was quick!  Now the message is:

<pre># command-line-arguments
go/tmp.go:4:17: cannot use [...]int literal (type [3]int) as type [2]int in return argument</pre>

Thanks, everyone!
