### ISSUE TITLE
go fmt provider json format

### ISSUE THREAD

**Issue by Wang-Jun-Chao** [golang/go#41241]
In many case, we want to print data infomation in json format. For simplicity, can fmt provide json format verb?

**Comment by davecheney** [comment]
Go fmt formats go code as source code. What is the value of emitting the go ast as json? What problem would that allow you to solve?

**Comment by AlexRouSg** [comment]
@davecheney I think he ment the `fmt` package and wnats something like `fmt.Printf("%json", v)`
That does something like:
```
b, err := json.Marshal(v)
if err != nil {
	fmt.Println("error:", err)
}
fmt.Printf("%s", string(b))
```
