### ISSUE TITLE
x/tools/gopls: errors with non-existent directory in a multi-folder workspace

### ISSUE THREAD

**Issue by segevfiner** [golang/go#41255]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.1 darwin/amd64

$ gopls version
golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/<snip>/Library/Caches/go-build"
GOENV="/Users/<snip>/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/<snip>/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/<snip>/go"
GOPRIVATE="github.com/OceanCodes"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b_/c6yh0ksn63d1yy192x2p9f4c0000gn/T/go-build483292181=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

1. Create a multi-folder workspace with one of the folders missing and others having go modules projects.
2. Open it in VS Code.
3. gopls will error:
```
Error loading workspace folders (expected 10, got 9)
failed to load view for file:///path/to/missing/folder: invalid workspace configuration: no such file or directory
```

### What did you expect to see?
It should just ignore that folder. It's common to end up in a situation like that when working on multiple branches.

A workaround for now is to create that directory, leaving it empty. But that has to be done again from time to time when moving between branches.

### What did you see instead?
It errors.

**Comment by stamblerre** [comment]
In this case, does `gopls` fail to work or does it just show an error message? I haven't tested this out yet, but based on the code it should just show an error and then continue to work for the other folders in the workspace.

**Comment by segevfiner** [comment]
It does seem to work. But I remember I had an issue with it also not working, but that might have been caused by something else as I'm not currently able to reproduce it not working. If I'll manage to reproduce a case where this specifically causes something to not work, I'll update here.

**Comment by segevfiner** [comment]
I just had a workspace where I had a missing folder and gopls will not respond to changes to any go file and refresh build errors when that happened.

Using gopls 0.5.1 and VS Code 1.50.0.

**Comment by stamblerre** [comment]
Thank you for the update, but unfortunately it's difficult to investigate without a log or a concrete repro case. Instructions on how to capture a log can be found here: https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs.

**Comment by stamblerre** [comment]
Closing, as there has not been any activity on this issue for over a month.
