### ISSUE TITLE
valueCtx call Value can cause panic

### ISSUE THREAD

**Issue by Wang-Jun-Chao** [golang/go#41254]
in context/context.go, I find some sence can lead valueCtx.Value panic
```
// create valueCtx, pass nil parent Context
func WithValue(parent Context, key, val interface{}) Context {
	if key == nil {
		panic("nil key")
	}
	if !reflectlite.TypeOf(key).Comparable() {
		panic("key is not comparable")
	}
	return &valueCtx{parent, key, val}
}

// get value
func (c *valueCtx) Value(key interface{}) interface{} {
	if c.key == key {
		return c.val
	}
	return c.Context.Value(key) //  if c.Context is nil, then call Value will panic !!!
}
```

**Comment by davecheney** [comment]
Thank you for raising this issue. Would you please supply a runnable code sample that shows the problem. Thank you

**Comment by Wang-Jun-Chao** [comment]
case code 
```
package main

import (
	"context"
	"fmt"
)

func main() {
	ctx := context.WithValue(nil, "test-key", "test-val")
	val := ctx.Value("not-exist-key")

	fmt.Println(val)
}
```

result
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x106ff9f]

goroutine 1 [running]:
context.(*valueCtx).Value(0xc00006a180, 0x10ac320, 0x10e9f50, 0x10e9f30, 0x10ac320)
        /usr/local/go/src/context/context.go:553 +0x3f
main.main()
        /Users/wangjunchao/go/src/wangjunchao/value_context_panic/value_context_panic.go:10 +0x82
```

**Comment by davecheney** [comment]
Please don’t pass nil as the parent context. This is documented in the package preamble. 

> Do not pass a nil Context, even if a function permits it. Pass context.TODO if you are unsure about which Context to use.

https://godoc.org/context

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.

It seems like Dave clarified your problem above, so I'm closing this for now. In the future, please try one of the forums for questions.

**Comment by royprotim** [comment]
Is the line 
```go
return c.Context.Value(key)
```
Concurrent Safe? 

The s
<img width="1008" alt="Screenshot 2021-05-04 at 3 57 19 PM" src="https://user-images.githubusercontent.com/18380085/116992390-8d256280-acf3-11eb-91ce-878038857e57.png">
tack trace of error I am receiving is attached

**Comment by mvdan** [comment]
Please don't comment on old issues that were closed as questions. See the wiki link I shared.
