### ISSUE TITLE
Possible bug in Go regarding UTF-8 strings?

### ISSUE THREAD

**Issue by T200proX7** [golang/go#41256]
Maybe someone from here can help me regarding this problem. I mentioned all details on Stackoverflow - please see here:
https://stackoverflow.com/questions/63767694/go-mysql-insert-incorrect-string-value-xc3

I have tried so far several options and solutions but i am still having the same issue.
I am not sure if its a bug? I have no idea.

Would be great to find a way to fix it.
Thank you.

**Comment by mdlayher** [comment]
Please see https://github.com/golang/go/wiki/Questions. Closing.
