### ISSUE TITLE
 go run -gcflags '-unused_pkgs' main.go isnt working

### ISSUE THREAD

**Issue by machinexa2** [golang/go#41258]
### What version of Go are you using (`go version`)?
go 1.14.7 linux/amd64

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
root@kali-linux:~/Music# go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/opt/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build022602942=/tmp/go-build -gno-record-gcc-switches"

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
https://stackoverflow.com/questions/19560334/how-to-disable-golang-unused-import-error
followed this

### What did you expect to see?
no error on not using var and imports

### What did you see instead?
error

**Comment by ALTree** [comment]
```go run -gcflags '-unused_pkgs' ```

That's not a supported option. Read [that answer](https://stackoverflow.com/a/22693545) in full:

> To get around this, I changed around my compiler to allow optional flags for allowing unused variables and imports in my code. 

They changed the compiler code to add that option, it's not something that works on the official Go compiler.

Closing here since this is not  a bug.
