### ISSUE TITLE
Time error?

### ISSUE THREAD

**Issue by owenzhou** [golang/go#41270]
# Time error?

``` go
package main

import(
	"fmt"
	"time"
)

func main(){
	timeLayout := "2006-01-02 15:04:05"

	t := "1990-08-17 13:14:15"

	t2 := "2000-08-17 13:14:15"

	loc, _ := time.LoadLocation("Asia/Shanghai")

	stamp, _ := time.ParseInLocation(timeLayout, t, loc)

	stamp2, _ := time.ParseInLocation(timeLayout, t2, loc)

	fmt.Println( "Datetime:", time.Unix(stamp.Unix(), 0) )

	fmt.Println( "Datetime:", time.Unix(stamp2.Unix(), 0) )
}
```

# Result
- Datetime: 1990-08-17 12:14:15 +0800 CST
Datetime: 2000-08-17 13:14:15 +0800 CST

<hr/>

## Why is there an hour difference?

**Comment by cespare** [comment]
The reason is that Daylight Savings Time was observed in China between 1986 and 1991.

I'm going to close this issue since it doesn't appear to be a bug in Go. Please use https://github.com/golang/go/wiki/Questions if you have further questions. Thanks.

**Comment by owenzhou** [comment]
Oh, Thank you!
