### ISSUE TITLE
x/pkgsite: add option to refresh a package on the package page

### ISSUE THREAD

**Issue by julieqiu** [golang/go#41278]
Following up on https://github.com/golang/go/issues/41055#issuecomment-682057601:

At the moment, we provide support for refreshing a package by visiting `pkg.go.dev/<path>@master`, but it's not obvious that this feature is available. 

We should add a way to make this process more obvious, such as by adding an "Update this package" button. 

/cc @jamalc @jba

**Comment by 89z** [comment]
https://github.com/golang/go/issues/37106

**Comment by opennota** [comment]
> At the moment, we provide support for refreshing a package by visiting `pkg.go.dev/<path>@master`

That doesn't seem to work: https://pkg.go.dev/gitlab.com/opennota/morph@master

The latest version is tagged v1.0.2, but `https://pkg.go.dev/gitlab.com/opennota/morph` still shows v1.0.1.

**Comment by jba** [comment]
It's now at v1.0.2. Perhaps the usual processing lag.
