### ISSUE TITLE
math: math.Floor bugged on products of certain float64 numbers

### ISSUE THREAD

**Issue by Baltan00** [golang/go#41283]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/h/.cache/go-build"
GOENV="/home/h/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/h/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/h/go"
GOPRIVATE=""
GOPROXY=""
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/h/Documents/go/abc/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build051312685=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/jk8bVwTo3HQ

### What did you expect to see?
A correct floor results.

### What did you see instead?
When I tried to get the floor of 680.0*0.35, I got 237 instead of 238.

**Comment by chanxuehong** [comment]
```golang
package main

import (
	"fmt"
)

func main() {
	var a, b float64 = 680, 0.35
	fmt.Println(a, b, a*b)
}
```

it prints
```text
680 0.35 237.99999999999997
```

**Comment by beoran** [comment]
680.0 * 0.35 = 680 * 35 / 100 = 23800 / 100 = 238. The floor result is correct.

On Ruby, this multiplication gives the incorrect result of 237.99999999999997. 

I'm impressed that Go manages to get this right. But still, don't use floating point for exact calculations, such as calculations involving money.

**Comment by randall77** [comment]
This is not a bug. 0.35 is not exactly representable as a floating point number, so there will be rounding error. If that error is downwards, then taking the floor gets you the integer almost 1 lower than the product.
