### ISSUE TITLE
x/sys/cpu: add support for detecting AVX-512

### ISSUE THREAD

**Issue by clausecker** [golang/go#41288]
I would like to detect the availability of AVX-512 and its subsets (F, CD, VL, BW, DQ, IFMA, VBMI, ...) using the `golang.org/x/sys/cpu` package.  However, no such flags are available.  Please add a way to detect the availability of AVX-512 and its specific sub features. If desired, I can try writing a patch for this myself.

**Comment by randall77** [comment]
A patch would be great, thanks.

**Comment by justplesh** [comment]
@fuzxxl Hi, if you will change your mind about doing it by yourself - plz ping me, I will handle this.

**Comment by fuzxxl** [comment]
@justplesh If you would like to do this I would be very happy.  Gives me more time to spend writing my paper.

**Comment by justplesh** [comment]
@clausecker ok, so I'll work on this

**Comment by clausecker** [comment]
@justplesh Any progress on this one?

**Comment by justplesh** [comment]
@clausecker will start in a few days

**Comment by clausecker** [comment]
@justplesh If it's in more than week, I think I'll just do it myself.  I have been holding up writing AVX-512 code for two weeks no and would like to begin soon-ish.

**Comment by justplesh** [comment]
@clausecker I'll try this weekend

**Comment by justplesh** [comment]
@clausecker so, the patch is ready, hopefully, it will be merged soon

**Comment by martisch** [comment]
Note that osxsave needs to be checked for zmm register support before allowing use of AVX-512.

**Comment by justplesh** [comment]
> Note that osxsave needs to be checked and zmm register support (similar to avx and ymm registers) before allowing use of AVX-512.

If I understood correctly, we can just check if AVX is supported.

**Comment by martisch** [comment]
The current code does not check xgetbv for zmm and opmask support which i think os needed.

**Comment by justplesh** [comment]
> The current code does not check xgetbv for zmm and opmask support which i think is needed for safe use. The avx code only checks xmm and ymm support in the os which is not sufficient to make sure the os correctly handles zmm state save and restore.

Yep, you are right. Will handle it.

**Comment by clausecker** [comment]
Thank you for the patch!  This'll be very useful.

**Comment by justplesh** [comment]
No problem :) Will be happy to work on the next issues!
