### ISSUE TITLE
runtime: "fatal error: unexpected signal during runtime execution" on windows-amd64-longtest builder of Go 1.15.2 commit

### ISSUE THREAD

**Issue by dmitshur** [golang/go#41296]
We've observed the following failure during `runtime` tests on a `windows-amd64-longtest` slowbot on a commit for the upcoming Go 1.15.2:

```
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x12efa46]

runtime stack:
runtime.throw(0x151e8d7, 0x2a)
	C:/workdir/go/src/runtime/panic.go:1116 +0x79 fp=0xc0709ff8f8 sp=0xc0709ff8c8 pc=0x12bc659
runtime.sigpanic()
	C:/workdir/go/src/runtime/signal_windows.go:240 +0x285 fp=0xc0709ff928 sp=0xc0709ff8f8 pc=0x12d1745
runtime.(*pageAlloc).chunkOf(...)
	C:/workdir/go/src/runtime/mpagealloc.go:331
runtime.CheckScavengedBitsCleared.func1()
	C:/workdir/go/src/runtime/export_test.go:905 +0x186 fp=0xc0709ff960 sp=0xc0709ff928 pc=0x12efa46
runtime.systemstack(0x0)
	C:/workdir/go/src/runtime/asm_amd64.s:370 +0x6b fp=0xc0709ff968 sp=0xc0709ff960 pc=0x12f4e0b
runtime.mstart()
	C:/workdir/go/src/runtime/proc.go:1116 fp=0xc0709ff970 sp=0xc0709ff968 pc=0x12c18e0

goroutine 20213428 [running]:
runtime.systemstack_switch()
	C:/workdir/go/src/runtime/asm_amd64.s:330 fp=0xc0001a92c0 sp=0xc0001a92b8 pc=0x12f4d80
[...]
FAIL	runtime	143.911s
```

See [here](https://go-review.googlesource.com/c/go/+/253717/1#message-c1837523011ceb181c0cfff0399db6db44352946) for more context and the complete build log.

The `windows-amd64-longtest` slowbot passed all tests on the second try, so this failure is intermittent. It doesn't seem to happen often, but it may be connected to (or the same as) issues #41285, #41099.

I've tried running `go test -timeout=0 -count=5 runtime` on a machine with Windows 10, and it passed.

We should see if there's any useful information in this particular instance, and if not, this issue can probably be closed as a duplicate.

/cc @randall77 @ianlancetaylor @toothrot @andybons

**Comment by dmitshur** [comment]
This must've happened during execution of `TestScavengedBitsCleared` test, since that's the only place `CheckScavengedBitsCleared` is called.

**Comment by mknyszek** [comment]
Oh, yeah, `CheckScavengedBitsCleared` is just wrong. There's also another place where this could happen. We should just ignore a `nil` result from `chunkOf` because the `chunks` index is sparse.

**Comment by randall77** [comment]
@mknyszek Does this need backporting?

**Comment by mknyszek** [comment]
It's only an issue in our own tests, and it's going to be really rare because it requires the address space to be discontiguous (we do have tests that intentionally do make the address space discontiguous, but those don't run these particular functions).

But, maybe that's a good reason to backport it too, to at least rule out this failure on release branches or folks running `all.bash`. It's a fairly safe change.

**Comment by andybons** [comment]
Let’s backport :)

**Comment by mknyszek** [comment]
> Let’s backport :)

Sounds good!

@gopherbot Please open a backport issue for 1.15.

**Comment by mknyszek** [comment]
@gopherbot Please open a backport issue for 1.14.

**Comment by dmitshur** [comment]
@mknyszek GopherBot is lazy (#25574), you'll need to create it manually.
