### ISSUE TITLE
x/pkgsite: Not updated module version after release

### ISSUE THREAD

**Issue by hbollon** [golang/go#41298]
### What is the URL of the page with the issue?
My library project : https://pkg.go.dev/mod/github.com/hbollon/go-edlib

 
### What is your user agent?
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
 
### Screenshot
 
![Capture d’écran de 2020-09-09 18-47-37](https://user-images.githubusercontent.com/27230141/92628438-1acbc200-f2cd-11ea-9254-4bb2e8730af8.png)
 
 
### What did you do?
Two days ago, I pushed a tag for my new version ("v1.1.0") and created a release with it on Github.

 
### What did you expect to see?
My new module version and updated documentation
 
 
### What did you see instead?
No changes compared to the version 1.0.0 on pkg.go.dev but I can run ```bash go get github.com/hbollon/go-edlib@v1.1.0``` without any issues

I tried these solutions to update it according to some topics on the web without success: 
- Force pkg cache upgrade with Makefile : 
```Makefile
update-pkg-cache:
	GOPROXY=https://proxy.golang.org GO111MODULE=on \
	go get github.com/$(USER)/$(PACKAGE)@v$(VERSION)
```
- Run : 
```sh 
curl https://sum.golang.org/lookup/github.com/hbollon/go-edlib@v1.1.0 
```

If anyone has any idea why pkg.go.dev is not updating I am interested. It's possible that I forgot a step ^^
GoDoc is well updated

**Comment by jamalc** [comment]
We have some additional tips [here](https://go.dev/about#adding-a-package). I was able to force an update by visiting https://pkg.go.dev/github.com/hbollon/go-edlib@v1.1.0 and pressing the request button.

When a package or module version is not found the page will look like this:

<img width="954" alt="Screen Shot 2020-09-09 at 2 24 59 PM" src="https://user-images.githubusercontent.com/18269441/92638435-42f4fa00-f2a8-11ea-972a-7ce7cfb9b01c.png">

**Comment by hbollon** [comment]
So simple haha, thanks a lot @jamalc !
