### ISSUE TITLE
x/tools/gopls: working with TinyGo

### ISSUE THREAD

**Issue by adamijak** [golang/go#41290]
```
package main
import "machine"
import "time"

func main() {
    led := machine.Led
    led.Configure(machine.PinConfig{Mode: machine.PinOutput})
    for {
        led.Low()
        time.Sleep(time.Millisecond * 300)
        led.High()
        time.Sleep(time.Millisecond * 1000)
    }
}
```
Setting ` GOPATH="/path/to/go:/usr/lib/tinygo/src"`  allows me to include machine. 
But still I get error `Led not declared in package machine`. That's caused by first line of board_bluepill.go is set to `// +build bluepill`. Its not detected as "machine package".

Any syggestions how to fix this to get gopls working with tinygo.

**Comment by stamblerre** [comment]
You will need to add the following to your configuration:

```
"gopls": {
    "env": {
        "GOFLAGS": "-tags=bluepill"
    }
}
```

**Comment by adamijak** [comment]
Thanks that worked perfectly.
###SOLUTION###
`export GOPATH="/path/to/go:/path/to/tinygo"` in my case `/usr/lib/tinygo`
Create `touch .vim/coc-settings.json` in your local tinygo project repository.
Put this code in .vim/coc-setings.json `
{
        "go.goplsEnv": {
                "GOFLAGS": "-tags=bluepill"
        }
}
`
