### ISSUE TITLE
x/mobile/cmd/gomobile: bind command fails for iOS with Go 1.15

### ISSUE THREAD

**Issue by ToJen** [golang/go#41300]
<pre>
$ go version
go version go1.15 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/path/to/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/path/to/go"
GOPRIVATE=""
GOROOT="/usr/local/Cellar/go/1.15/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/path/to/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/05/01234/T/go-build111673491=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```bash
gomobile bind -v -ldflags '-s -w' -target=ios -o=MyLib.framework github.com/user/mylib-go/...

```

### What did you expect to see?

Normal binding output.

### What did you see instead?

```bash
gomobile: go [-e -json -compiled=true -test=false -export=false -deps=false -find=true -tags=ios -- github.com/user/mylib-go/...]: exit status 2: cmd/go: unsupported GOOS/GOARCH pair darwin/arm
```

Is this related to https://golang.org/doc/go1.15#darwin?

**Comment by ToJen** [comment]
@hajimehoshi @dmitshur just curious how gomobile detects the system is darwin/arm when the system says otherwise: 
```
$ go env GOOS GOARCH
darwin
amd64
```

I'm temporarily downgrading to go@1.14

**Comment by dmitshur** [comment]
Is this issue different from #39575, which was fixed?

What version of `gomobile` are you using?

**Comment by ToJen** [comment]
No longer a problem, my gomobile was outdated
