### ISSUE TITLE
x/tools/gopls: how do you use -skip-cleanup?

### ISSUE THREAD

**Issue by jadekler** [golang/go#41306]
How does one use the `-skip-cleanup` flag?

When I do, `go test -v ./... -run Foo/bar -skip-cleanup`, I confusingly get a usage warning but the test also runs (apparently without the flag, because the temp dir is not deleted).

Am I using it incorrectly?

**Comment by stamblerre** [comment]
I was able to use it in the following way:

```
go test ./internal/lsp/ -run=TestLSP/Modules/testdata/upgradedep/Link/go.mod -skip-cleanup -v
```

Does that work for you?

**Comment by jadekler** [comment]
I'm running `gopls/` tests - maybe that makes a difference?

I tried,

```
$ cd gopls
$ go test ./internal/regtest -run=TestDeklerkRename/singleton -skip-cleanup -v
[...]
$ ls /var/folders/n3/n33wx2bs307ck7t4qpwb6csw00h16k/T/gopls-regtest-896525474/TestDeklerkRename/singleton/gopls-sandbox-605086105
ls: /var/folders/n3/n33wx2bs307ck7t4qpwb6csw00h16k/T/gopls-regtest-896525474/TestDeklerkRename/singleton/gopls-sandbox-605086105: No such file or directory
```

No flag error this time - which is great! - but still getting "directory not found". 🤔

**Comment by jadekler** [comment]
FWIW I'm able to modify `gopls/internal/regtest/runner.go:408` to force skip cleanup!

**Comment by stamblerre** [comment]
Ah, the skip cleanup flag name for the regression tests is slightly different: https://github.com/golang/tools/blob/17fc728d0d1efaff9bd884307e377e5b1469e08b/gopls/internal/regtest/reg_test.go#L25.

**Comment by jadekler** [comment]
Ahhh! Thank you!
