### ISSUE TITLE
cmd/compile: Dividing complex128 by zero does not report an error

### ISSUE THREAD

**Issue by xiyichan** [golang/go#41308]
### What version of Go are you using (`go version`)?

<pre>
$ go version
master
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?
```go
package main
  
import (
     "fmt"
)
func main() {
    var x complex128 = complex(1, 2) // 1+2i
    fmt.Println(x/ 0)
}

```

### What did you expect to see?
an error

### What did you see instead?
![image](https://user-images.githubusercontent.com/34647972/92673304-6756e200-f34d-11ea-8e90-d0a5f42f689a.png)

**Comment by ianlancetaylor** [comment]
Please paste text as text, not as an image.  Thanks.

This is expected behavior.  In floating point arithmetic, dividing a finite value by zero gives you an infinity, not an error.  See "Floating-point operators" at https://golang.org/ref/spec#Arithmetic_operators.

**Comment by xiyichan** [comment]
```go
package main

import (
	"testing"
)
func TestConstInt(t *testing.T){
	const x int =1
	t.Log(x/0)
}
func TestVarInt(t *testing.T){
	var x int =2
	t.Log(x/0)
}
func TestVarFloat64(t *testing.T){
	var x float64 =2.222
	t.Log(x/0)
}
func TestConstFloat64(t *testing.T){
	const x float64 =2.222
	t.Log(x/0)
}
func TestConstComplex(t *testing.T){
	const x complex128=complex(1,2)
	t.Log(x/0)
}
func TestVarComplex(t *testing.T){
	var x complex128=complex(1,2)
	t.Log(x/0)
}
```
This is the test code I wrote.  Why use const to modify float64 and complex will cause errors.

**Comment by ianlancetaylor** [comment]
In Go, constant arithmetic does not use the same rules as variable arithmetic.  In particular, constant floating point values have no infinity, or NaN, or negative zero.  See https://golang.org/ref/spec#Constant_expressions .

In general for questions about the language it's better to use a forum.  You will get better and faster answers.  See https://golang.org/wiki/Questions.
