### ISSUE TITLE
x/tools/gopls: didChangeConfiguration ignores the new configuration

### ISSUE THREAD

**Issue by ainar-g** [golang/go#41311]
<p>I&#xA0;was trying to&#xA0;enable <code>staticcheck</code> using
<code>gopls</code> version <code>v0.5.0-pre1</code>
and&#xA0;<code>natebosch/vim-lsc</code>,
but&#xA0;couldn't.&#x2003;The&#xA0;plugin configuration&#xA0;was:</p> 

```vim
let g:lsc_server_commands = {
\   'go': {
\     'name': 'gopls',
\     'command': 'gopls serve',
\     'log_level': -1,
\     'suppress_stderr': v:true,
\     'workspace_config': {
\       'staticcheck': v:true,
\     },
\   },
\ }
```

<p>I&#xA0;also used <code>-rpc.trace</code> and&#xA0;made sure
that&#xA0;<code>gopls</code> actually receives the&#xA0;configuration
with&#xA0;the&#xA0;<code>workspace/didChangeConfiguration</code>
method.&#x2003;I&#xA0;inspected the&#xA0;code, and&#xA0;it seems
like&#xA0;parameter <code>changed</code> of&#xA0;the&#xA0;server implementation
is currently&#xA0;ignored:</p> 

```go
func (s *Server) didChangeConfiguration(ctx context.Context, changed interface{}) error {
	// go through all the views getting the config
	for _, view := range s.session.Views() {
		options := view.Options()
		if err := s.fetchConfig(ctx, view.Name(), view.Folder(), &options); err != nil {
			return err
		}
		view, err := view.SetOptions(ctx, options)
		if err != nil {
			return err
		}
		go func() {
			snapshot, release := view.Snapshot(ctx)
			defer release()
			s.diagnoseDetached(snapshot)
		}()
	}
	return nil
}
```

<p>If&#xA0;I&#xA0;enable <code>stderr</code> logging and&#xA0;add
a&#xA0;<code>log.Printf("%#v", changed)</code> there, I&#xA0;can see,
that&#xA0;the&#xA0;parameters are&#xA0;there:</p>

<pre>[lsc:Error] StdErr from gopls: 2020/09/10 12:19:36 &protocol.DidChangeConfigurationParams{Settings:map[string]interface {}{"staticcheck":true}}</pre>

<p>Is&#xA0;this a&#xA0;bug?&#x2003;Is there&#xA0;any additional
information I&#xA0;should&#xA0;add?</p>

**Comment by ainar-g** [comment]
<p>@stamblerre&#x2003;Thanks for&#xA0;looking into&#xA0;this
so&#xA0;quickly!&#x2003;I&#xA0;applied the&#xA0;patch in&#xA0;the&#xA0;CL (patch
set 5), but&#xA0;that&#xA0;didn't solve
the&#xA0;issue.&#x2003;<code>options.Staticcheck</code> remains
<code>false</code> before&#xA0;and&#xA0;after&#xA0;<code>s.fetchConfig</code>
as&#xA0;well&#xA0;as at&#xA0;the&#xA0;end of&#xA0;<code>updateAnalyzers</code>,
so&#xA0;no&#xA0;analysis is run.&#x2003;Am I&#xA0;missing
something?&#x2003;(And&#xA0;is it better to&#xA0;leave such comments
on&#xA0;the&#xA0;CL&#xA0;itself?)</p>

**Comment by stamblerre** [comment]
Thanks for testing it out! It's fine/probably easier to leave comments here.
Do you see the second `workspace/configuration` method in the log when fetchConfig runs for the second time, and does it return `"staticcheck": true`? I only tested with VS Code, but it fixed the issue there.

**Comment by ainar-g** [comment]
<p>@stamblerre&#x2003;Ah,&#xA0;I&#xA0;see what's wrong
now.&#x2003;<code>vim-lsc</code> assumes, that&#xA0;the&#xA0;server just accepts
the&#xA0;configuration that&#xA0;the&#xA0;client sent
with&#xA0;<code>didChangeConfiguration</code>.&#x2003;It doesn't know
or&#xA0;respond to&#xA0;<code>configuration</code>.&#x2003;I&#xA0;cobbled
together a&#xA0;patch to&#xA0;<code>vim-lsc</code> that&#xA0;fixes that,
and&#xA0;<i>voilà</i>, <code>staticcheck</code> works now.&#x2003;I'll send
the&#xA0;patch to&#xA0;the&#xA0;maintainers
of&#xA0;that&#xA0;client.&#x2003;Sorry for&#xA0;the&#xA0;noise!</p>

**Comment by stamblerre** [comment]
Perfect--thanks for doing that! And definitely not noise - there was a `gopls` bug here too.
