### ISSUE TITLE
cmd/go: inconsistent result when go build output is a non-existent directory

### ISSUE THREAD

**Issue by XSAM** [golang/go#41313]
### What version of Go are you using (`go version`)?

go1.15 darwin/amd64

### Does this issue reproduce with the latest release?

Yes

### What did you do?

<details>
<summary>Project Hierarchy</summary>

```
.
├── go.mod
└── main.go
```

</details>

The first time to build, `go` complain about an existent directory that is actually created by `go` itself and not exists before the build.

```bash
$ go build -o bin/ main.go
go build command-line-arguments: build output "bin/" already exists and is a directory
```

<details>
<summary>Project Hierarchy</summary>

```
.
├── bin
├── go.mod
└── main.go
```

</details>

The second time to build. Since the directory already exists, `go` works fine at this time.

```bash
$ go build -o bin/ main.go
```

<details>
<summary>Project Hierarchy</summary>

```
.
├── bin
│   └── main
├── go.mod
└── main.go
```

</details>

### What did you expect to see?

An idempotent result from `go build`.

1. Keep complaining about the directory

```
$ go build -o bin/ main.go
go build command-line-arguments: build output "bin/" already exists and is a directory
$ go build -o bin/ main.go
go build command-line-arguments: build output "bin/" already exists and is a directory
```

2. Allow `go build` output is an inexistent directory

-----

I prefer the second solution since it's more convenient for users.

Pros:
- No need to create a directory by users.
- Easy to write a common build command in scripts. (Putting binary in a directory seems like a common convention to build)

Before: `go build -o bin/foo .` `go build -o bin/bar .` (We need to change the output name)
After: `go build -o bin/ .`

- Consistency. `go build -o bin/foo .` also creates the directory for users.

**Comment by andybons** [comment]
@bcmills @matloob @jayconrod
