### ISSUE TITLE
playground: no obvious way to remove content

### ISSUE THREAD

**Issue by stevegilbert23** [golang/go#41320]
There is no obvious way to remove content on the go playground (for example, someone accidentally posts proprietary code).

This issue: https://github.com/golang/go/issues/18530 
attempted to address this.  It was closed over 2 years ago and has "soon" label.  It indicates there is a "contact us first" link in the "About" content which I do not see and consequently there isn't an obvious way to know who to or even how to contact a person or group about content removal (or any other issues with the playground).

Is it possible to complete 18530 and/or put contact information into "About" on the playground?

**Comment by ALTree** [comment]
But it's there, click on the About button and scroll down:

> Any requests for content removal should be directed to security@golang.org. Please include the URL and the reason for the request. 

That sentence was added in the commit that fixes #18530. Can you clarify what else you think it's missing?

**Comment by rsc** [comment]
It's there:

<img width="709" alt="Screen Shot 2020-09-10 at 10 55 52 AM" src="https://user-images.githubusercontent.com/104030/92749598-40e87500-f354-11ea-9b3a-76fcb64a34b4.png">

And when it's off screen there is a visible scroll bar:

<img width="710" alt="Screen Shot 2020-09-10 at 10 56 03 AM" src="https://user-images.githubusercontent.com/104030/92749624-4776ec80-f354-11ea-8f04-aa0807a695fc.png">

Also I can tell you that we get something around one removal request per week, so people are finding that text.

**Comment by stevegilbert23** [comment]
My apologies @rsc , @ALTree - I think I had the right side of my browser window off the screen at the time and did not see the scroll bar and the end of the yellow frame cleanly cut the text between paragraphs.
