### ISSUE TITLE
runtime: "fatal error: unexpected signal during runtime execution" on windows-amd64-longtest builder of Go 1.15.2 commit [1.14 backport]

### ISSUE THREAD

**Issue by dmitshur** [golang/go#41322]
@mknyszek requested issue #41296 to be considered for backport to the next 1.14 minor release.

> @gopherbot Ple​ase open a backport issue for 1.14.

**Comment by dmitshur** [comment]
Approved as this is a test fix, needed to reduce false-positives during pre-release testing. This backport applies to both 1.15 (#41317) and 1.14 (this issue).

**Comment by mknyszek** [comment]
Ah, thank you! I'm sorry for not getting to it sooner.

**Comment by dmitshur** [comment]
@mknyszek Not a problem!
