### ISSUE TITLE
x/pkgsite: github.com/newrelic/go-agent/v3/newrelic does not recognize license

### ISSUE THREAD

**Issue by v3n** [golang/go#41333]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/newrelic/go-agent/v3@v3.9.0/newrelic?tab=doc
 
### What is your user agent?
 ```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
 ```
  
### What did you do?
 

 
https://pkg.go.dev/github.com/newrelic/go-agent/v3@v3.9.0/newrelic?tab=doc
 
### What did you expect to see?
 
Go documentation.
 
### What did you see instead?

A notice that says godoc could not identify the license for the package. Package is licensed Apache-2.0, which is on the list of accepted licenses.

**Comment by jamalc** [comment]
The reason we did not identify a license is because the zip file returned by http://proxy.golang.org/github.com/newrelic/go-agent/v3/@v/v3.9.0.zip doesn't contain that license file, though I'm not sure why.

/cc @katiehockman @hyangah @heschik for input on this.

**Comment by heschik** [comment]
This module uses the major directory (not major branch) model, so its files are here: https://github.com/newrelic/go-agent/tree/v3.9.0/v3 and there is no license there.

**Comment by jba** [comment]
I don't think there's anything for the pkgsite team to do here, so closing.
