### ISSUE TITLE
x/pkgsite: new major version not surfaced when it does not yet have a release tag

### ISSUE THREAD

**Issue by tbpg** [golang/go#41345]
### What is the URL of the page with the issue?

https://pkg.go.dev/gopkg.in/yaml.v3?tab=doc
 
 
### What is your user agent?
 
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
 
### Screenshot
 
<img width="1090" alt="yaml" src="https://user-images.githubusercontent.com/26876514/92941934-fb44ae80-f41e-11ea-89d7-259ae5182616.png">

 
### What did you do?
 
1. Searched for `yaml` on pkg.go.dev: https://pkg.go.dev/search?q=yaml
1. Saw "v3" near the top, so I assumed it was the latest.
    ![image](https://user-images.githubusercontent.com/26876514/92942092-2af3b680-f41f-11ea-9db7-fb4ca9b9d2d1.png)

 
### What did you expect to see?
 
A clear explanation of what version I should use. 
 
### What did you see instead?

I didn't expect v3 to be so high if v2 is the latest. Also, v3 is a later SemVer, but pkg.go.dev says v2 is the latest SemVer. Also, the v3 version was published Jun 15, 2020 while v2 was released May 6, 2020.

cc @julieqiu

**Comment by julieqiu** [comment]
Thanks for the feedback!

We're going to make these changes to pages like this:

- The banner message will say "The latest major version is v3. The latest major version with tagged releases is v2."
- The versions tab will list the v3 module, with the message "No tagged versions in this module."

Here's a mock:
![image](https://user-images.githubusercontent.com/5943521/94029457-d3dcd280-fd8a-11ea-9110-c34ccccc154c.png)

**Comment by julieqiu** [comment]
This will be fixed in the next deploy.


Here's the updated UI for the current site:


![image](https://user-images.githubusercontent.com/5943521/98172433-652d8180-1ebf-11eb-9b7e-62abf213ec00.png)


And on the redesign site at https://beta.pkg.go.dev:

![image](https://user-images.githubusercontent.com/5943521/98172350-36afa680-1ebf-11eb-862b-d95ebe4b7129.png)

**Comment by tbpg** [comment]
Thank you!
