### ISSUE TITLE
x/pkgsite: proposal: add link on Not Found page

### ISSUE THREAD

**Issue by fgergo** [golang/go#41347]
https://pkg.go.dev/nosuchpackage returns "404 Not Found" as it should.
I'd propose to add a link below the error message, something like this:
<a href="https://go.dev/about#adding-a-package">Add a package to pkg.go.dev.</a>

background: #41318

**Comment by seankhliao** [comment]
the functionality exists when you use a proper package path, ex: https://pkg.go.dev/github.com/nosuch/package

**Comment by fgergo** [comment]
@seankhliao You probably misunderstood the proposal.
Please take a look again at the proposed link and maybe have a look at #41318 .

**Comment by seankhliao** [comment]
This is what I see right now: a button with "Request <package>" (you may have to use a not negatively cached url).
Does this not do what your proposal covers?
![2020-09-12-002712](https://user-images.githubusercontent.com/11343221/92978023-dbe56a00-f48e-11ea-8ffd-f3953a65e8ad.png)

**Comment by fgergo** [comment]
no it doesn't.
details in #41318
