### ISSUE TITLE
x/tools/gopls: add `type` to the hover for types

### ISSUE THREAD

**Issue by gertcuykens** [golang/go#41357]
For some reason tools beside go doc like to get rid of the keyword type for example, granted in most cases a experienced go developer instantly knows the symbol refers to a const, var, func or type. But in some cases especially this first one, it's very easily misunderstood that HandlerFunc is a type. For example the name contains Func and and the definition contains func, so it's very crustial to not leave out the word type in the beginning to not confuse people who are new to go. Yes type it's in the description at least but that just lucky somebody put it in the comment.

![image](https://user-images.githubusercontent.com/863731/93000540-75615a00-f529-11ea-8039-dadb9d51ef48.png)

![image](https://user-images.githubusercontent.com/863731/93000575-99bd3680-f529-11ea-866c-33dafed68ea5.png)

![image](https://user-images.githubusercontent.com/863731/93000596-b78a9b80-f529-11ea-8047-12ed1baab17f.png)

Fortunately func is always included, but that's not a excuse to drop type var const

![image](https://user-images.githubusercontent.com/863731/93000588-af326080-f529-11ea-89b1-909380349b5e.png)

`go doc json` for example is very consistent in that regard making sure to always start with func type const or var

![image](https://user-images.githubusercontent.com/863731/93001036-68923580-f52c-11ea-885a-82119433e19f.png)

**Comment by pjweinb** [comment]
To be clear, this looks like a request for clearer Hover messages. Is that right?

**Comment by gertcuykens** [comment]
@pjweinb I think I described it a bit more precise then that :) In summary just don't remove `type const var func` in the beginning of a hover message. Thank you

example:

go doc http.HandlerFunc

```
package http // import "net/http"
type HandlerFunc func(ResponseWriter, *Request)
The HandlerFunc...
func (f HandlerFunc) ServeHTTP(w ResponseWriter, r *Request)
```

in hover message you get

```
HandlerFunc func(ResponseWriter, *Request)
http.HandlerFunc on pkg.go.dev
The HandlerFunc....
```

A person new to go thinks this
HandlerFunc = func(ResponseWriter, *Request)
so that means i can do this
HandlerFunc(ResponseWriter, *Request)
definitely a function because I read 
...Func and func...

compiler error message haha wrong its a type

New go user ??? ok i am going to stick to js instead go is way to confusing

**Comment by stamblerre** [comment]
I think the only case where a keyword is not present in the hover message is in the case of types, which is likely because of the way we format their hover. We can consider adding `type` to hover messages.

**Comment by nasjp** [comment]
I tried hovering in Goland and the 'type' is displayed.
It seems to be the problem with vscode-go, not gopls.

![golang](https://user-images.githubusercontent.com/39974389/94668406-f5215e00-034a-11eb-9685-55a11ab21de8.png)

**Comment by stamblerre** [comment]
@nasjp: Goland does not use `gopls`, so this is a `gopls` issue.
