### ISSUE TITLE
cmd/api: omit vendored dependencies when run inside the 'std' module

### ISSUE THREAD

**Issue by cherrymui** [golang/go#41358]
### What version of Go are you using (`go version`)?

tip (b459bc8152210c14b66e23351690ff774cd68d2c)

### Does this issue reproduce with the latest release?

No.

### What did you do?

Currently, at tip (b459bc8152210c14b66e23351690ff774cd68d2c), running all.bash, at the end it prints 2000+ lines of new APIs of vendored golang.org/x packages. This is very verbose. And they are not even part of the standard library API, which I thought the API check is for. Could we not emit those? Thanks.

**Comment by bcmills** [comment]
This is probably somehow related to my changes to the `all` package pattern. I'll take a look.

**Comment by bcmills** [comment]
Bisected to [CL 251159](https://golang.org/cl/251159).

**Comment by cherrymui** [comment]
Thanks @bcmills
