### ISSUE TITLE
all: TryBots don't complain about not gofmt code in the package

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#41352]
I was doing codereview of

https://go-review.googlesource.com/c/go/+/250077

and discovered that patch set 2 was not gofmted, but TryBot did not complain about it.

I have asked CL author to gofmt his code. Is that something should be enforced by TryBots automatically? Maybe have a test that verifies that all appropriate code is gofmted.

Maybe it is OK to submit un formatted code. Feel free to close this issue then.

Thank you.

Alex

**Comment by tklauser** [comment]
Also see #18548 which proposes something similar with additional checks (e.g. copyright headers).

**Comment by alexbrainman** [comment]
Thanks @tklauser for the reference. It does indeed looks like a duplicate. So closing my issue.

Mind you, given #18548 is nearly 3 years old, does not give me much confidence. :-)

Alex
