### ISSUE TITLE
cmd/compile,test: issue24491b.go seems flaky on linux-386-sid

### ISSUE THREAD

**Issue by cuonglm** [golang/go#41361]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +5f1b12bfbe Sun Sep 13 04:35:35 2020 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cuonglm/.cache/go-build"
GOENV="/home/cuonglm/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/cuonglm/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/cuonglm/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/cuonglm/sources/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/cuonglm/sources/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/cuonglm/sources/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build629252996=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you expect to see?

`go tool dist test` passes.

### What did you see instead?

Test fails on builder: https://build.golang.org/log/72b1813880f8c739753c10320bc0ca2745aa73f9

```
go run run.go -- fixedbugs/issue24491b.go
exit status 2
panic: GC late

goroutine 1 [running]:
main.after(0x900e018)
	/workdir/go/test/fixedbugs/issue24491b.go:39 +0x54
main.main()
	/workdir/go/test/fixedbugs/issue24491b.go:45 +0x2e

FAIL	fixedbugs/issue24491b.go	0.111s
2020/09/13 04:48:44 Failed: exit status 1
go tool dist: FAILED
```

The test was added in 1f4521669416a2e14fb0b84481447f4a93f19878, and builder on this commit passed. The builder fails when commit 5f1b12bfbeb04ca6dbecbf064f5e5a42d8ba4b5a was submitted, it's a refactoring only, so it's not clear to me yet why the test can be failed.

cc @mdempsky

**Comment by cuonglm** [comment]
Hmm, seems the test itself is flaky, it's also failed in arm for commit 1f4521669416a2e14fb0b84481447f4a93f19878

https://build.golang.org/log/92bdd2a76057a83c2a446d140634708d57aaf169

**Comment by mdempsky** [comment]
Oh, probably because `runtime.GC()` doesn't guarantee the finalizer has run. (I guess that's why I used channels in the other test cases I wrote.)

That's probably the best fix here too. Change done to a channel; make the finalizer close it; have `before` check that it's not closed (non-blocking receive using `select`); and have `after` check that it is closed (blocking receive).
