### ISSUE TITLE
x/tools/cmd/guru: could pointsto analysis for unassigned interfaces be improved?

### ISSUE THREAD

**Issue by siadat** [golang/go#41370]
### What version of Go are you using?

<pre>
$ go version
go version go1.15 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sina/Library/Caches/go-build"
GOENV="/Users/sina/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/sina/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/sina/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/sina/clones/tools/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/l1/gr_t1lss4837728b1sqz919m0000gn/T/go-build472257919=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
```
cat issue41370/issue.go
```
```go
package main

func main() {
	var i interface{} = nil
	_ = i
}
```
```
#	_ = i
#	    ^
#	    58
$ guru -scope ./issue41370/ pointsto ./issue41370/issue.go:#58
```

### What did you expect to see?

```
guru: this interface{} cannot contain any dynamic types
```

### What did you see instead?

```
guru: pointer analysis did not find expression (dead code?)
```

**Comment by siadat** [comment]
ssadump shows that the first two lines are commented. Is this an ssa optimization?

```
func main():
0:                                                                entry P:0 S:0
        ; var i interface{} @ 4:6 is nil:interface{}
        ; var i interface{} @ 5:6 is nil:interface{}
        return
```

When I set `var i interface{} = 555` ssadump show:

```
func main():
0:                                                                entry P:0 S:0
        t0 = make interface{} <- int (555:int)                      interface{}
        ; var i interface{} @ 4:6 is t0
        ; var i interface{} @ 5:6 is t0
        return
```

**Comment by siadat** [comment]
I realized I could build the naive SSA form using -N

```
func main():
0:                                                                entry P:0 S:0
        t0 = local interface{} (i)                                 *interface{}
        *t0 = nil:interface{}
        t1 = *t0                                                    interface{}
        rundefers
        return
```

I'm exploring the code and slowing getting there lol

**Comment by siadat** [comment]
Okay, got it lol. All I had to do was ti add `ssa.NaiveForm`
```
prog := ssautil.CreateProgram(lprog, ssa.GlobalDebug|ssa.NaiveForm)
```

Now guru pointsto's message is a lot better (for my use):

```
this interface{} cannot contain any dynamic types.
```

**Comment by siadat** [comment]
I solved my problem by patching the liftAlloc function
```diff
 func liftAlloc(df domFrontier, alloc *Alloc, newPhis newPhiMap, fresh *int) bool {
+       switch deref(alloc.Type()).Underlying().(type) {
+       case *types.Interface:
+               return false
+       }
```

I am living this issue open in case anyone is interested in commenting :)

**Comment by stamblerre** [comment]
@siadat: We welcome any patches if you're interested in contributing, but `guru` is largely unmaintained so we won't work on making any changes ourselves.

**Comment by siadat** [comment]
Thank you for the replies! :) Is guru being replaced by something else? golps comes to mind which (if I'm not mistaken) uses analysers from github.com/dominikh/go-tools. So, would it be correct to say the focus from guru is shifted to golps plus github.com/dominikh/go-tools?

**Comment by siadat** [comment]
Regarding this issue: I'd love to help! :) Enabling ssa.NaiveForm in guru will change the output of the pointsto subcommand for inputs other than the one reported in this issue. (I can write an example if you want.) So, I think a good fix would follow one of these two approaches:

- patch the [ssa.lift](https://github.com/golang/tools/blob/c537a342ddf6c0a44a4f7b5eafa9be47eb9bd29e/go/ssa/lift.go#L131) func so that the empty interface is not lifted but other things are.
- add a `-N` flag to guru that enables ssa.NaiveForm. It is analogous to ssadump's `-N`

The first approach is complex and feels like a hack for such a special scenario. I would go for the second approach. Let me know what you think :)

**Comment by adonovan** [comment]
guru was deleted in https://github.com/golang/go/issues/65880 and the pointer analysis was deleted long before; closing as obsolete.
