### ISSUE TITLE
why not has method Remove in http.ServeMux?

### ISSUE THREAD

**Issue by zsy619** [golang/go#41376]
### What did you do?

Add or remove HttpHandler at golang runtime

### What did you expect to see?

// Remove url from m, Regularization is not considered
func (mux *ServeMux) Remove(url string) {
	mux.mu.Lock()
	defer mux.mu.Unlock()
	delete(mux.m, url)
}

**Comment by toothrot** [comment]
A better place to ask this kind of question is golang-nuts. See https://golang.org/wiki/Questions.
