### ISSUE TITLE
access: +2 and Editors for roland@

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#41384]
@rolandshoemaker joined the Go Security team 🎉 

Please grant him access to GitHub (https://github.com/orgs/golang/teams/go-approvers, @rolandshoemaker) and Gerrit (https://go-review.googlesource.com/#/admin/groups/1005,members, rolandshoemaker@gmail.com). 

See https://golang.org/wiki/GithubAccess. /cc @golang/osp-team

**Comment by andybons** [comment]
Done. Welcome, Roland!
