### ISSUE TITLE
cmd/go: get downloads main~1 commit, not main

### ISSUE THREAD

**Issue by josharian** [golang/go#41388]
Reproduce:

Create a new repo and `go mod init`. Run `go get -v -u github.com/tailscale/depaware`. Then cat go.mod.

Result:

require github.com/tailscale/depaware v0.0.0-20200914201916-3f1070fd0d55 // indirect

Expected:

require github.com/tailscale/depaware v0.0.0-20200914232109-e09ee10c1824 // indirect

Note that you can force upgrade by `go get -u github.com/tailscale/depaware@e09ee10c1824`.

`3f1070fd0d55` is HEAD~1; `e09ee10c1824` is HEAD. `go get` should thus pick `e09ee10c1824`.

cc @jayconrod @bcmills 

cc @danderson

**Comment by bcmills** [comment]
This sounds like the `proxy.golang.org` cache TTL again (#38065). Did you try `GONOPROXY=github.com/tailscale/depaware`?

**Comment by josharian** [comment]
Yep, it was the cache. :/ Closing as a duplicate.
