### ISSUE TITLE
x/pkgsite: <div role="tablist"> on Details Page inappropriately nested in Nav region

### ISSUE THREAD

**Issue by kmstorer** [golang/go#41381]
### What version of Go are you using (`go version`)?

<pre>
NA

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Tablist on details page is nested within a nav region. Screen reader users expect to see nav regions only at the top of each page, and this is disorienting.

### What did you expect to see?
Proposal: Tablist should be removed and all content consolidated to one page.

**Comment by jamalc** [comment]
Obsolete. We're no longer using the tablist role on pkgsite.
