### ISSUE TITLE
access: restore try/slow-bot and abandon rights for martisch

### ISSUE THREAD

**Issue by martisch** [golang/go#41392]
With the trust rule changes and account cleanups in https://github.com/golang/go/issues/40699
more than trust rights have been stripped from some accounts.

Please restore rights to run try/slow bots and abandon changes on gerrit for account https://go-review.googlesource.com/q/owner:martisch%2540uos.de
 
/cc @golang/osp-team

**Comment by FiloSottile** [comment]
I've added that account to may-start-trybots and may-abandon-changes.

Note that you still have all approver rights (including TryBot and Abandon) on your google.com account.
