### ISSUE TITLE
x/pkgsite: add "Package files" section for commands

### ISSUE THREAD

**Issue by LeGEC** [golang/go#41396]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/google/gopacket/examples/httpassembly?tab=doc
 
### What is your user agent?
 
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0
 
### Screenshot
 
not relevant
 
### What did you do?

Just went to the doc page for this package
 
### What did you expect to see?

A `Package files` section, with links to the underlying code files, as the former `godoc.org` site would offer :

https://godoc.org/github.com/google/gopacket/examples/httpassembly?tab=doc
has a `main.go` link, which leads to :
https://github.com/google/gopacket/blob/master/examples/httpassembly/main.go

### What did you see instead?

I found no such link, in none of the tabs of the `pkg.go.dev` version for this url.

---

In this specific case, there is no public symbol to "document", and the documentation clearly implies "go read the code of the main function", so the lack of `Package files` section is particularly emphasized here.

**Comment by jba** [comment]
We'll be adding a Package Files section soon.

**Comment by julieqiu** [comment]
This feature is now available on [beta.pkg.go.dev](https://beta.pkg.go.dev). See https://github.com/golang/go/issues/41585#issuecomment-718143563 for details, and https://beta.pkg.go.dev/github.com/google/gopacket/examples/httpassembly#section-sourcefiles as an example.

Closing this issue for https://github.com/golang/go/issues/41586.
