### ISSUE TITLE
cmd/go: Unclear error running go program: go tool asm -V=full: unexpected output:

### ISSUE THREAD

**Issue by andronedev** [golang/go#41408]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.2 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\AndroneDev\AppData\Local\go-build
set GOENV=C:\Users\AndroneDev\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\AndroneDev\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\AndroneDev\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ANDRON~1\AppData\Local\Temp\go-build284386398=/tmp/go-build -gno-record-gcc-switches
GOROOT/bin/go version: go version go1.15.2 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.15.2
</pre></details>

### What did you do?

PS C:\Users\AndroneDev\Desktop\MesProjets\cryptord\server> go run main.go
go tool asm -V=full: unexpected output:

![image](https://user-images.githubusercontent.com/31452517/93255072-a8118980-f799-11ea-826b-bcd46e1fb28d.png)

Failed to build ..

**Comment by toothrot** [comment]
Could you provide an example of the code that produced the error, preferably as a [Go playground](https://play.golang.org/) link?
