### ISSUE TITLE
std,cmd: add test to ensure that all bundled packages are in sync with go.mod version

### ISSUE THREAD

**Issue by dmitshur** [golang/go#41409]
We've had issues in the past where version skew could be introduced if people forgot to update one part of the distribution without also updating another (e.g., versions in src/go.mod and src/cmd/go.mod). A very effective solution was adding a test that fails when skew is detected.

I believe we still need to address this for net/http's bundled copies of `golang.org/x/net/http2` and `golang.org/x/net/internal/socks`. Right now, it's possible to update the bundled copy independently from the src/go.mod version, but it's not clear that flexibility is something we want to keep.

See #41375 where this came up. Also relevant is #25285.

I plan to revisit my review of [CL 189818](https://golang.org/cl/189818) (which fixes issue #32031), the trade-offs have changed by now (especially given #41330).

/cc @toothrot @bcmills @FiloSottile

**Comment by bcmills** [comment]
#36852 is also related: ideally the `TryBot` should flag any CL that causes the selected version of `x/net/http2` to diverge from the version from which `h2_bundle.go` was generated.

**Comment by dmitshur** [comment]
> Right now, it's possible to update the bundled copy independently from the src/go.mod version, but it's not clear that flexibility is something we want to keep.

Discussion so far suggests we do not want to keep this flexibility. That means we need a test that will detect automatically when a regression happens.

I'll modify this issue to be about adding that test. The test should be skipped in -short test mode, so it will be executed on longtest builders (and via SlowBot requests).

This is similar/related to #36852 (go.mod and vendor directory being in sync) and to #36907 (go.mod of different modules being in sync).

A general approach to the test that I've discussed with @bcmills could look like this:

1. Update x/tools in cmd/go.mod to include [CL 189818](https://golang.org/cl/189818) after it is submitted (/cc @FiloSottile)
2. Use cmd/bundle as part of the test to write what the bundle should look like to a temporary directory.
3. Detect if the bundle file in tree is different from the file generated as part of the test.

This approach can avoid needing to rely on `git` in the test.

**Comment by dmitshur** [comment]
Managing backports can become much more expensive if skew is introduced in a new major Go release. This has happened in Go 1.15 (see https://github.com/golang/go/issues/41375#issuecomment-713766922 and [CL 258540](https://golang.org/cl/258540)), and I think it's important we have an automated measure so we can be confident it can't happen for future Go releases due to human error.

I'm going to make this a release-blocker for Go 1.16: we should either resolve this issue by adding a test, or if there isn't enough time, we must manually verify that there is no skew introduced in Go 1.16 release candidates and the final release.

CC @golang/release.
