### ISSUE TITLE
gollvm: syscall.DT_UNKNOWN is no defined, during the build process, for rkt

### ISSUE THREAD

**Issue by advancedwebdeveloper** [golang/go#41404]
Hello again.
I was trying to build an archived project, [rkt](https://github.com/rkt/rkt) - so I expected to use stable source code base, for testing purposes.

### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>
go version go1.15rc2 gollvm LLVM 12.0.0git linux/amd64

### Does this issue reproduce with the latest release?
Probably.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> 
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/oceanfish81/.cache/go-build"
GOENV="/home/oceanfish81/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/oceanfish81/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/oceanfish81/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/tools"
GCCGO="/usr/local/bin/llvm-goc"
AR="ar"
CC="/usr/bin/clang"
CXX="/usr/bin/clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build520867872=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
</summary><br><pre>
$ go env

</pre>

</details>

### What did you do?

I was searching for Go files - and tried to build inside a sub-folder:

> ~/rkt/common$ go build
> # _/home/oceanfish81/rkt/common
> ./common.go:480:29: error: reference to undefined identifier 'syscall.DT_UNKNOWN'

@thanm , that's not the only constant for auto-generation (as for today).

> ./common.go:530:3: error: goarm is not a function; '//go:linkname' is only supported for functions

@cherrymui , are you familiar with the cause of this bug?

Ivan

**Comment by advancedwebdeveloper** [comment]
[https://github.com/golang/sys/blob/master/unix/zerrors_linux.go#L490](https://github.com/golang/sys/blob/master/unix/zerrors_linux.go#L490) - DT_UNKNOWN is expected to have 0x0 value

Ivan

**Comment by thanm** [comment]
I'll update my patch in 254941 for DT_UNKNOWN.

Regarding go:linkname only supported for functions -- this is a known issue, see https://github.com/golang/go/issues/30771 for example.  The rkt code in question (reaching into the runtime to grab references to unexported variables) is not something that we want to encourage-- a package like this can potentially break on any new Go release as runtime internals change.

**Comment by thanm** [comment]
>>./common.go:480:29: error: reference to undefined identifier 'syscall.DT_UNKNOWN'

This problem should now be fixed at head.  The issue with go:linkname being applied to an unexported variable in the runtime package is still open, however, that will require a more general solution outside of gollvm in particular. Closing this bug, please reopen if need be.
