### ISSUE TITLE
x/tools/gopls: suppress adding URLs to hover

### ISSUE THREAD

**Issue by flw-cn** [golang/go#41417]
In vim, the URL in the hover document given by gopls is actually unclickable because the popup window does not capture focus. However, the presence of these URLs can affect the sentence flow of the document text.

I know there's a feature in vim called conceal that hides them, but since URLs are usually long, actually hiding them leaves a huge black hole, like this:

<img width="990" alt="image" src="https://user-images.githubusercontent.com/5546718/93297196-662d2580-f823-11ea-99e6-752e9e4c221b.png">

I looked at the source code for these modules and found that the original documentation comments did not contain URLs, so they should have been added actively by gopls.

I know that some GUI editors like vscode have this feature that is very useful, as they often have an integrated browser that can easily display what the link is pointing to. But in other term-based editors, actually opening the URL is not very convenient and breaks the train of thought.

So is it possible to request an option to turn this feature off?

**Comment by stamblerre** [comment]
This feature is available through the `linksInHover` setting: https://github.com/golang/tools/blob/master/gopls/doc/settings.md#linksinhover-bool.

**Comment by flw-cn** [comment]
> This feature is available through the `linksInHover` setting: https://github.com/golang/tools/blob/master/gopls/doc/settings.md#linksinhover-bool.

Thanks! It does work!
