### ISSUE TITLE
x/build/dashboard: linux-386-longtest log missing the failure reason

### ISSUE THREAD

**Issue by bcmills** [golang/go#41426]
https://build.golang.org/log/bcb53a27f560f5363c22056d02f2a968ca351370 is marked as a failure in the build dashboard:

![image](https://user-images.githubusercontent.com/5200974/93343891-04f35b00-f7ff-11ea-9933-f9a22bce8710.png)

However, the log doesn't indicate what failed: the log does not include the word `FAIL` or any output that includes a goroutine dump, timeout indication, or signal. (It looks like it might have either hung or crashed during the API check, but without a goroutine or process dump there is no clear way to diagnose the problem further.)

**Comment by bcmills** [comment]
CC @toothrot

**Comment by toothrot** [comment]
Thanks, that's odd. I'll see what I can find out about that particular build.

**Comment by bcmills** [comment]
Duplicate of #39349.
