### ISSUE TITLE
net/http: Memory leak when we cannot access  remote url

### ISSUE THREAD

**Issue by omarsy** [golang/go#41422]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13
</pre>

### What operating system and processor architecture are you using (`go env`)?
Windows
<details><summary><code>go env</code> 

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\SESA571965\AppData\Local\go-build
set GOENV=C:\Users\SESA571965\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\SESA571965\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\SESA571965\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\SESA571965\Documents\EdgeCore.omar\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\SESA57~1\AppData\Local\Temp\go-build800121138=/tmp/go-build -gno-record-gcc-switches

</summary><br><pre>
$ go env
</pre></details>

### What did you do?
When I run this code with a non-existent url. I have memory leak

```
package main

import (
	"crypto/tls"

	"net/http"
	"net/url"
	"strings"
)

func main() {
	tr := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}
	client := &http.Client{Transport: tr}
	for true {
		login(client)
	}
}

func login(client *http.Client) error {
	loginURL, err := url.Parse("https://notAccessibleAdress")
	if err != nil {
		return err
	}
	form := url.Values{}
	form.Add("grant_type", "password")
	form.Add("username", "c.username")
	form.Add("password", "c.password")
	r, err := http.NewRequest("POST", loginURL.String(), strings.NewReader(form.Encode()))
	if err != nil {
		return err
	}
	r.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := client.Do(r)
	if resp != nil {
		defer resp.Body.Close()
	}
	defer client.CloseIdleConnections()
	return err
}

```

**Comment by davecheney** [comment]
Can you please describe how you have determined you have a memory leak so someone can attempt to reproduce what you see. 

Which tools did you use, how did you run them, what output did you see, and how did you determine that this was a leak?
