### ISSUE TITLE
x/tools/gopls: switch default to -mod=readonly

### ISSUE THREAD

**Issue by stamblerre** [golang/go#41437]
In CLs [253799](https://go-review.googlesource.com/c/tools/+/253799) and [254756](https://go-review.googlesource.com/c/tools/+/254756), @heschik switched to explicitly using `-mod=mod` to preserve the current behavior of `gopls` with Go 1.16. Since `-mod=mod` will be deprecated, we need an alternative approach for the future.

A proposed solution has been to run `go mod tidy` before `gopls` runs `go/packages.Load`. This can be done with `-modfile` or in the temporary workspace module. This way, we preserve the existing behavior that allows users to edit modules that don't compile, but we still offer `go mod tidy` diagnostics. These diagnostics should be upgraded to errors (with Go 1.16).

/cc @jayconrod @findleyr

**Comment by stamblerre** [comment]
Another thing: Our model of textual updates to the `go.mod` does not allow for analogous updates to the `go.sum`, so we should use `go` commands instead of edits wherever possible.

**Comment by stamblerre** [comment]
@heschik is there any work left here?

**Comment by heschik** [comment]
I suppose not.
