### ISSUE TITLE
cmd/compile: About simplifying the if of typecheck1

### ISSUE THREAD

**Issue by xiyichan** [golang/go#41446]
### What version of Go are you using (`go version`)?

<pre>
$ go version
master
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?

I find a todo tag in line 2106 of the file cmd/compile/internal/gc/typecheck.go.Is this simplifying the 'if'?
```go
if (top&ctxStmt != 0) && top&(ctxCallee|ctxExpr|ctxType) == 0 && ok&ctxStmt == 0 {
	if !n.Diag() {
		yyerror("%v evaluated but not used", n)
		n.SetDiag(true)
	}
	n.Type = nil
	return n
}
```
I found that this code will enter the 'if' when top is equal to 0001. Can it be changed like this?
```go
if top&ctxStmt == ctxStmt && ok&ctxStmt == 0 {
	if !n.Diag() {
		yyerror("%v evaluated but not used", n)
		n.SetDiag(true)
	}
	n.Type = nil
	return n
}
```
Then another 'if' I have no idea to simplify.

**Comment by mdempsky** [comment]
You can run `all.bash` in `$GOROOT/src` to see if Go still builds and the regression tests still pass. I suspect tests will fail though. (I trust that rsc included that middle comparison for a reason.)

**Comment by xiyichan** [comment]
@mdempsky I passed all. bash.

**Comment by mdempsky** [comment]
Interesting. If you want to upload a CL for that, I'll review it.

It would be nice if we can change all 4 of those if statements into something like:

```
if top & ok == 0 {
    switch {
    case ...:
        yyerror(...)
    ...
    default:
        Fatalf(...)
    }
    n.Type = nil
    return n
}
```

I don't know off hand how to fill in the ...s though.

**Comment by xiyichan** [comment]
I try to uplaod a CL, but maybe not all can be simplified.
