### ISSUE TITLE
net/http: Protocol upgrade from HTTP1.1 to h2c(HTTP2) when the request contains payload body, is failing.

### ISSUE THREAD

**Issue by rakheshkumbi** [golang/go#41445]
When client sends request to upgrade from http1.1 to http2 and the request contains the payload body, the server fails to upgrade to http2. (RFC 7540 section 3.2)
And observed the following error.
2020/09/17 12:11:10 http: response.Write on hijacked connection from fmt.Fprintf (print.go:205)

GO Versions
go version go1.15.2 linux/amd64

Steps to Reproduce
1)  Run the server.
2) Capture the packets using wireshark
3) send upgrade request from curl and include payload body
sudo curl -vs -o /dev/null --http2 --request GET --data '{"username":"xyz","password":"xyz"}' http://localhost:8090/hello

Expected behavior:
The HTTP2 upgrade should be successful and the server should send the response back to the client.

Code Snippets
```go
package main

import (
        "fmt"
        "net"
        "net/http"
        "os"

        "golang.org/x/net/http2"
        "golang.org/x/net/http2/h2c"
)


func main() {
        H2CUpgrade()
}

func H2CUpgrade() {
        h2s := &http2.Server{}

        handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
                fmt.Fprintf(w, "Hello, %v, http: %v", r.URL.Path, r.TLS == nil)
                return

        })

        server := &http.Server{
                Addr:    "0.0.0.0:8090",
                Handler: h2c.NewHandler(handler, h2s),
        }

        fmt.Printf("Listening [0.0.0.0:8090]...\n")
        server.ListenAndServe()
}
```

**Comment by rakheshkumbi** [comment]
Network trace:

![image](https://user-images.githubusercontent.com/46817533/93432980-dc915c80-f8e3-11ea-9588-781c77be28ec.png)

**Comment by networkimprov** [comment]
cc @fraenkel

**Comment by fraenkel** [comment]
Its broken, but so is h2c. If you attempt to do a POST instead of GET which is more common with data, you get the same error.
There are no tests for h2c, so I am more concerned that there is more than just this example that is broken.

**Comment by rakheshkumbi** [comment]
Thank you for the update @fraenkel. Do we have any solution or workaround for this?

**Comment by seankhliao** [comment]
closing as dup of #38064

**Comment by linchuan4028** [comment]
any update on this issue? I believe that I encounter the same problem.
