### ISSUE TITLE
Gomobile xcframework generation

### ISSUE THREAD

**Issue by palyvoda** [golang/go#41457]
Is it possible to generate .xcframework file with gomobile? 

I built the .framework file with gomobile with the following command:

> gomobile bind -target ios -o ../frameworks/MyFramework.framework

After that I tried to build .xcframework file with this command 

> xcodebuild -create-xcframework -framework "MyFramework.framework"
> -output "MyFramework.xcframework"

But it shows error:

> error: binaries with multiple platforms are not supported
> '/Users/nicco/myFramework/MyFramework.framework/MyFramework'

So looks like the problem is in gomobile framework generation process. 

So I see 2 solutions:
 1. To generate .xcframework file with gomobile. 
 2. Change the .framework build process for being able to convert .framework generated file to .xcframework

How to do it?

**Comment by tpaschalis** [comment]
Thanks for taking the time to open this issue. Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

Check https://github.com/golang/go/wiki/Questions for other venues to ask your question.

**Comment by jerson** [comment]
Hi @valself this could help to generate and xcframework

you need to generate a framework for each architecture

```bash
gomobile bind -ldflags="-w -s" -target=ios/arm64 -o arm64.framework github.com/jerson/openpgp-mobile/openpgp
gomobile bind -ldflags="-w -s" -target=ios/amd64 -o amd64.framework github.com/jerson/openpgp-mobile/openpgp
```
and then just merge with xcode command

```bash
xcodebuild -create-xcframework \
	-framework arm64.framework \
	-framework amd64.framework \
	-output Openpgp.xcframework
```

and thats all, hope this help
