### ISSUE TITLE
x/pkgsite: missing urls for some licenses

### ISSUE THREAD

**Issue by qlcom** [golang/go#41454]
### What is the URL of the page with the issue?
 https://pkg.go.dev/license-policy
 
### What did you expect to see?
all of the license should point to url that describe the license.
 

### What did you see instead?
but some of them don't

**Comment by sudo-sturbia** [comment]
@julieqiu I was wondering if you accept CLs for this? If yes, do you have a preference for the remaining links, for example spdx.org/licenses? Thanks!
