### ISSUE TITLE
x/website: workshop.chromeexperiments.com is down

### ISSUE THREAD

**Issue by bfanger** [golang/go#41465]
http://workshop.chromeexperiments.com/examples/gui referenced from popular library https://github.com/dataarts/dat.gui

Reports 
```
Go 1.9 is no longer available. Please refer to https://goo.gl/aESk5L for more information.
```

This is not a problem with golang, but doesn't do it any good either.

A more generic "Oops! an error occurred, contact the maintainer of the site, Error details: https://goo.gl/aESk5L" 

Preferably with the mailto link to the maintainer would be better.

**Comment by ALTree** [comment]
Thanks for reporting this, but it has nothing to do with the Go open source project. Google Cloud decided to remove support for older Go versions. That message is printed by Google Cloud, not by Go.
