### ISSUE TITLE
cmd/compile: compiler regression due to deferred call to variadic unsafe-uintptr function

### ISSUE THREAD

**Issue by mdempsky** [golang/go#41460]
This used to compile (albeit with possible memory corruption), but now fails to compile with `cannot use a0 (type []uintptr) as type uintptr in argument to f`:

```
package p

import "unsafe"

//go:noinline
//go:uintptrescapes
func f(...uintptr) {}

func g(p unsafe.Pointer) {
	defer f(uintptr(p))
}
```

Probably due to CL 253457.

I think there are two issues here:

1. In `wrapCall`, we need to set the newly created call as a `...`-style call if the original one was. (The above code was already rewritten to `defer f([]uintptr{uintptr(p)}...)` earlier in the compiler.)
2. `wrapCall` also needs to look for `uintptr(p)` conversions within the final `[]uintptr{...}...` argument.

/cc @cuonglm @ianlancetaylor

**Comment by cuonglm** [comment]
The first issue is quite easy to fix, the second is tricky. Seems we have to convert from slice of uintptr to slice of unsafe.Pointer?
