### ISSUE TITLE
x/pkgsite: github.com/muktihari/expr

### ISSUE THREAD

**Issue by muktihari** [golang/go#41475]
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/muktihari/expr
 
### What is your user agent?
 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
 

### What did you do?
 I deleted my repository and create new one under the same name
 

### What did you expect to see?
 repository deleted and refreshed with the new one
 
 
### What did you see instead?
repository is still the old one, same as before

**Comment by muktihari** [comment]
_$ go mod download_ still stuck with the old version too. Can you delete it and let it get the new one, thank you!

**Comment by jba** [comment]
The module proxy (https://proxy.golang.org), which both pkg.go.dev and `go mod download` use,  will never replace an existing module@version with a new one. You'll need to change the version number. v1.0.1 should do it. After applying the tag, use `go mod download` or `go get`, then wait a few minutes and look on pkg.go.dev.
