### ISSUE TITLE
x/tools/gopls: change the module path and upgrade imports within the module

### ISSUE THREAD

**Issue by godcong** [golang/go#41471]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.14.7 windows/amd64
</pre>　

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
//Has nothing to do with env
</pre></details>

### What did you do?

Now I usually modify the `go.mod` file.
Then modify some imports one by one.

### What did you expect to see?
Sometimes a project may permanently move to a new address.
I hope `go mod` has any way to directly migrate my project to the new address.
Possible comannd like:
```
//I created a new project,use:
go mod init github.com/nameA/projectA

//When I need to migrate to a new address like nameB/projectB, to use:
go mod change github.com/nameA/projectA github.com/nameB/projectB 
```
Then all the imports of the project point to the new address.

### What did you see instead?
Now I don't seem to see a similar function.
If there is no such feature, I hope it can be added.
If there is already have a similar functions, I hope to get some help.

**Comment by toothrot** [comment]
There are a number of tools for renaming import paths already. I am not sure that `go mod` is the appropriate place. If you need help finding such a tool, asking on one of the forums at http://golang.org/wiki/Questions is the best.

/cc @bcmills @jayconrod @matloob

**Comment by bcmills** [comment]
@marwan-at-work has a [`mod`](https://pkg.go.dev/mod/github.com/marwan-at-work/mod) tool that will do this for major versions, I believe.

Such a tool would be out-of-place in `cmd/go`, which generally does not edit source files for you. But perhaps it would be a reasonable feature for `gopls` (CC @stamblerre).

**Comment by godcong** [comment]
Yes, `go mod` is not necessary.
Any extension that can achieve this function will do.
Because manual modification may bring some errors caused by human operation errors.
