### ISSUE TITLE
x/tools/gopls: deep completion misranked

### ISSUE THREAD

**Issue by muirdm** [golang/go#41489]
See below screenshot. I expect `&bytes.Buffer{}` to be the first candidate, but for some reason packages are winning.

![Screen Shot 2020-09-18 at 2 29 38 PM](https://user-images.githubusercontent.com/11356572/93646691-8a236f00-f9bb-11ea-9092-179db4300451.png)

**Comment by stamblerre** [comment]
@muirdm: This is with `gopls` at master (and the deep completion CL), I assume?

/cc @heschik @dandua98

**Comment by muirdm** [comment]
> This is with gopls at master (and the deep completion CL), I assume?

Yes, master at e94ab72881893c257f5cecf9e0ed1b9d5c72f6e7. I've been noticing it for a while, though.

**Comment by dandua98** [comment]
Was not able to reproduce on master, strange. Seemed to be ordered as expected for me.

![image](https://user-images.githubusercontent.com/24802378/93648202-38d5a880-f9d8-11ea-8bd3-ff7f2854e3dc.png)

**Comment by muirdm** [comment]
It seems my editor has suddenly started changing the order of candidates for some reason 😠 . Sorry!
