### ISSUE TITLE
wasm_exec.js not working in Gnome3+ Extensions

### ISSUE THREAD

**Issue by abergmeier** [golang/go#41482]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What did you do?

```javascript
"use strict";

const Gio = imports.gi.Gio;
const GLib = imports.gi.GLib;
const GObject = imports.gi.GObject;
const St = imports.gi.St;

const ExtensionUtils = imports.misc.extensionUtils;
const Me = ExtensionUtils.getCurrentExtension();
const Main = imports.ui.main;
const PanelMenu = imports.ui.panelMenu;

// This imports wasm_exec.js
const WasmExec = Me.imports.wasm_exec; 

const go = new WasmExec.Go();
WebAssembly.instantiateStreaming(fetch("foo.wasm"), go.importObject).then((result) => {
    go.run(result.instance);
});
```

### What did you expect to see?
Should load just fine.

### What did you see instead?
Errors with:

```
Sep 18 20:19:02 9300 gnome-shell[5474]: JS ERROR: Extension stackdriver@abergmeier.github.com: ReferenceError: require is not defined
                                        @/home/andreas/.local/share/gnome-shell/extensions/stackdriver@abergmeier.github.com/wasm_exec.js:105:22
                                        @/home/andreas/.local/share/gnome-shell/extensions/stackdriver@abergmeier.github.com/wasm_exec.js:588:3
                                        @/home/andreas/.local/share/gnome-shell/extensions/stackdriver@abergmeier.github.com/extension.js:13:18
```

Seems like the problem is with using

```
const nodeCrypto = require("crypto");
```

So probably there is the need to define a `require`.

**Comment by abergmeier** [comment]
Working on that in https://github.com/abergmeier/go/pull/1

**Comment by agnivade** [comment]
Thanks for the report. Yet another environment to support :)

/cc @neelance

**Comment by neelance** [comment]
We can check for the existence of `require`, but that won't help you much. Your environment needs to provide `crypto.getRandomValues` as well as `TextEncoder` and `TextDecoder`. You should polyfill them.

**Comment by abergmeier** [comment]
> We can check for the existence of require, but that won't help you much. Your environment needs to provide crypto.getRandomValues as well as TextEncoder and TextDecoder. You should polyfill them.

I have `require` hooked up. There are polyfills for `TextEncoder` and `TextDecoder` in place.
Currently I have problems hooking up hrettimer.

Now even though I might be able to fix all this (an then have to get through the horrible Gerrit process), how would we test, that this does not break with future GJS/Golang releases?

**Comment by abergmeier** [comment]
Will take the more portable browser implementation now. And thus the current js implementation should be sufficient.
