### ISSUE TITLE
x/pkgsite: malformed function signature on LHS index

### ISSUE THREAD

**Issue by cespare** [golang/go#41486]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/go-chi/chi
 
### What is your user agent?
 
    Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
 
### Screenshot
 
![screen_20200918125259](https://user-images.githubusercontent.com/318501/93639480-e7182880-f9ad-11ea-91c3-71ed3e52cb2a.png)

### What did you do?
 
Navigated to a package page
 
### What did you expect to see?
 
The signature of the function in question is

    func (mx *Mux) Group(fn func(r Router)) Router

so if the LHS needs to abbreviate it perhaps it should be

    (mx) Group(fn)
 
### What did you see instead?

    (mx) Group(fnfunc(r))

Which is weird because it has part of the argument type (which other signatures don't have) and because there's no space (so it reads `fnfunc`).

**Comment by ya5u** [comment]
@cespare If it's abbreviated like any other method, the following style would be better in your example, I think.

```
(mx) Group(fn)
```

**Comment by cespare** [comment]
@ya5u yes, I suppose you're right. I updated the description.
