### ISSUE TITLE
x/tools/gopls: Go to pkg.go.dev

### ISSUE THREAD

**Issue by gertcuykens** [golang/go#41488]
Hover space is precious, only the most necessary description should be in it

![image](https://user-images.githubusercontent.com/863731/93644169-bc57bf80-fa01-11ea-9a43-63682311faa9.png)

`http.HandlerFunc on pkg.go.dev`

is not the place for it, it should be in the right click menu `Go to pkg.go.dev` instead

![image](https://user-images.githubusercontent.com/863731/93644354-1bb5cf80-fa02-11ea-9df3-31e5e05cd015.png)

**Comment by stamblerre** [comment]
`gopls` has no way of adding to the context menu, and it's not part of the language server protocol.
You can set "linksInHover": false to disable this feature.

**Comment by gertcuykens** [comment]
ok fair enough, I disable it thanks. Maybe I should created the ticket on https://github.com/golang/vscode-go then instead although I doubt this can be done without modifying gopls first so that a separate call to gopls can be made on right click updating the navigation menu. Anyway i will create ticket on vscode-go instead. 

![image](https://user-images.githubusercontent.com/863731/93649862-3fcade00-fa0d-11ea-82ea-caafe5096d4b.png)

**Comment by gertcuykens** [comment]
actually i wasn't able to disable it in vscode

tried following settings
````
  "gopls": {
    "linksInHover": false
  },
```
and looking for option go.linksInHover 

https://github.com/golang/tools/blob/gopls/v0.5.0/gopls/doc/user.md doesn't mention other posiblilities

**Comment by stamblerre** [comment]
It should be mentioned here: https://github.com/golang/tools/blob/gopls/v0.5.0/gopls/doc/settings.md, but I believe it's still considered an experimental option which is why it's not.

```json5
"gopls": {
		"linksInHover": false,
}
```

Does work for me however. Can you please share a `gopls` log (https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs) from when you see this happening?

**Comment by gertcuykens** [comment]
You are correct seems I wasn't using v.0.5 but after `go get -u golang.org/x/tools/gopls` my vscode broke 
```
~/Desktop/src master % gopls version                     
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.5.0 h1:XEmO9RylgmaXp33iGrWfCGopVYDGBmLy+KmsIsfIo8Y=
```
```
[Trace - 01:06:14.752 AM] Received notification 'window/logMessage'.
Params: {"type":1,"message":"2020/09/19 01:06:14 module suggested fixes failed:  is not a go.mod file\n\tdirectory=file:///Users/gert/Desktop/src\n"}

[Error - 1:06:14 AM] 2020/09/19 01:06:14 module suggested fixes failed:  is not a go.mod file
	directory=file:///Users/gert/Desktop/src
```
I have a workspace src with several different seperate go modules. But this is out of the scope of this ticket will troubleshoot it on mailing list or slack.

Thanks anyway for feedback

**Comment by stamblerre** [comment]
You can update by running `GO111MODULE=on go get golang.org/x/tools/gopls@v0.5.0` or by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools". Sounds like you may have downloaded a bad version because 
`gopls` at master should only be downloaded by running `GO111MODULE=on go get golang.org/x/tools/gopls@master golang.org/x/tools@master`.

**Comment by gertcuykens** [comment]
Did upgrade trough "Go: Install/Update Tools"
gopls version now tells v0.5.0 instead of master but the commit hash seem the same 
```
~/Desktop/src master % gopls version
golang.org/x/tools/gopls v0.5.0
    golang.org/x/tools/gopls@v0.5.0 h1:XEmO9RylgmaXp33iGrWfCGopVYDGBmLy+KmsIsfIo8Y=
```
I dont have the error message any more but it also can't compile the source code
```
[Trace - 01:36:40.333 AM] Sending request 'textDocument/hover - (8)'.
Params: {"textDocument":{"uri":"file:///Users/gert/Desktop/src/proxy/gzip.go"},"position":{"line":35,"character":7}}

[Trace - 01:36:40.334 AM] Received response 'textDocument/hover - (8)' in 0ms.
Result: null
```
Anyway you don't have to worry about it I will create specific tickets if I find the cause.
