### ISSUE TITLE
gccgo: no Go files in /usr/src/golang.org/x/net/http/httpguts

### ISSUE THREAD

**Issue by zhsj** [golang/go#41499]
### What version of Go are you using (`go version`)?

```
go version go1.14.6 gccgo (Debian 10.2.0-7) 10.2.0 linux/amd64
```

and

```
go version go1.15rc2 gccgo (Debian 20200809-1) 11.0.0 20200809 (experimental) [master revision fb9e3f79464:8ad857c7881:94d4f4387de8264ee289cf71f692d59ca6ac36f8] linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/zhsj/.cache/go-build"
GOENV="/home/zhsj/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/data/zhsj/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/gcc/x86_64-linux-gnu/10"
GCCGO="/usr/bin/x86_64-linux-gnu-gccgo-10"
AR="ar"
CC="x86_64-linux-gnu-gcc-10"
CXX="x86_64-linux-gnu-g++-10"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build792107422=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
</pre></details>

### What did you do?

```
$ ls $GOPATH/src/golang.org/x/net/http/httpguts
guts.go  httplex.go  httplex_test.go

$ export GO111MODULE=off

$ cat test.go
package main

import (
        _ "golang.org/x/net/http/httpguts"
)

func main() {}

$ go run test.go
```

### What did you expect to see?

`go run test.go` without error

### What did you see instead?
```
go build golang.org/x/net/http/httpguts: no Go files in /usr/src/golang.org/x/net/http/httpguts
```

It happens with GOPATH, and GO111MODULE=off, and without vendor dir.

**Comment by ianlancetaylor** [comment]
I'm not sure what is happening here, but it must have something to do with the fact that golang.org/x/net/http/httpguts is vendored into the standard library.

**Comment by zhsj** [comment]
Probably it's same as #41368

I just found someone is trying to build containerd with gollvm, then I double checked the gccgo build result. We build go packages with gccgo on ppc64 in Debian. https://buildd.debian.org/status/logs.php?pkg=containerd&arch=ppc64
