### ISSUE TITLE
Mongo GO Driver and error with runtime/syscall_windows.go file 

### ISSUE THREAD

**Issue by LukasDeco** [golang/go#41492]
### What version of Go are you using (`go version`)?

<pre>
go version go1.15.2 windows/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Owner\AppData\Local\go-build
set GOENV=C:\Users\Owner\AppData\Roaming\go\env  
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Owner\go\pkg\mod
set GONOPROXY=github.com/LukasDeco/
set GONOSUMDB=github.com/LukasDeco/
set GOOS=windows
set GOPATH=C:\Users\Owner\go
set GOPRIVATE=github.com/LukasDeco/
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Go\src\occasionally-api\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Owner\AppData\Local\Temp\go-build043299782=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I was able to use a mongo-go driver on my local windows set up. Now I can't

### What did you expect to see?

My app start up on go run

### What did you see instead?

Exception 0xc0000005 0x0 0x7ff9be532fff 0x2125f2d0000
PC=0x2125f2d0000

syscall.loadsystemlibrary(0xc00022fb40, 0xc00022b200, 0xc00022b200, 0x1f)
        c:/go/src/runtime/syscall_windows.go:136 +0xe7
syscall.LoadDLL(0xb57753, 0xa, 0x336531, 0xa53f20, 0x29)
        c:/go/src/syscall/dll_windows.go:81 +0x16a
syscall.(*LazyDLL).Load(0xc000004140, 0x0, 0x0)
        c:/go/src/syscall/dll_windows.go:245 +0xc8
syscall.(*LazyProc).Find(0xc00005d7d0, 0x0, 0x0)
        c:/go/src/syscall/dll_windows.go:300 +0xbf
syscall.(*LazyProc).mustFind(...)
        c:/go/src/syscall/dll_windows.go:318
syscall.(*LazyProc).Addr(...)
        c:/go/src/syscall/dll_windows.go:327
syscall._DnsQuery(0xc000026840, 0x21, 0x0, 0xc00029ef98, 0x0, 0x0, 0x0)
        c:/go/src/syscall/zsyscall_windows.go:1699 +0x4c
syscall.DnsQuery(0xc00022cc00, 0x28, 0x21, 0x0, 0xc00029ef98, 0x0, 0xc00027c678, 0xc00027c674)
        c:/go/src/syscall/zsyscall_windows.go:1695 +0xb5
net.(*Resolver).lookupSRV(0x10fb7c0, 0xced7c0, 0xc0000200b0, 0xb552dd, 0x7, 0xb51dee, 0x3, 0xc0000267a9, 0x1a, 0x0, ...)
        c:/go/src/net/lookup_windows.go:252 +0x125
net.LookupSRV(0xb552dd, 0x7, 0xb51dee, 0x3, 0xc0000267a9, 0x1a, 0xcdd860, 0xc000201ae0, 0xa53da0, 0xc00027c558, ...)
        c:/go/src/net/lookup.go:420 +0xac
go.mongodb.org/mongo-driver/x/mongo/driver/dns.(*Resolver).fetchSeedlistFromSRV(0x10e7f60, 0xc0000267a9, 0x1a, 0x1, 0x0, 0x0, 0xc000267110, 0x1, 0x1)
        C:/Users/Owner/go/pkg/mod/go.mongodb.org/mongo-driver@v1.3.4/x/mongo/driver/dns/dns.go:78 +0xb9
go.mongodb.org/mongo-driver/x/mongo/driver/dns.(*Resolver).ParseHosts(0x10e7f60, 0xc0000267a9, 0x1a, 0x1, 0x0, 0x0, 0xc000267100, 0x1, 0x1)
        C:/Users/Owner/go/pkg/mod/go.mongodb.org/mongo-driver@v1.3.4/x/mongo/driver/dns/dns.go:34 +0xfe
go.mongodb.org/mongo-driver/x/mongo/driver/connstring.(*parser).parse(0xc00029f3f0, 0xc000026780, 0x59, 0xc00027c41c, 0xc00027c418)
        C:/Users/Owner/go/pkg/mod/go.mongodb.org/mongo-driver@v1.3.4/x/mongo/driver/connstring/connstring.go:205 +0xaf3
go.mongodb.org/mongo-driver/x/mongo/driver/connstring.Parse(0xc000026780, 0x59, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/Owner/go/pkg/mod/go.mongodb.org/mongo-driver@v1.3.4/x/mongo/driver/connstring/connstring.go:27 +0xb2
go.mongodb.org/mongo-driver/mongo/options.(*ClientOptions).ApplyURI(0xc00029fcc0, 0xc000026780, 0x59, 0x59)
        C:/Users/Owner/go/pkg/mod/go.mongodb.org/mongo-driver@v1.3.4/mongo/options/clientoptions.go:163 +0xdb
main.ConnectDB()
        c:/go/src/occasionally-api/connection.go:23 +0xab
main.main()
        c:/go/src/occasionally-api/main.go:60 +0x5d
rax     0x7ff9bb0049d2
rbx     0x7ff9bb0049d0
rcx     0x77
rdi     0xffffffffffbadd11
rsi     0x0
rbp     0x0
rsp     0x2f683ff090
r8      0x97c
r9      0x97c
r10     0x97c
r11     0x97c
r12     0xc000007a
r13     0x0
r14     0x7ff9bb0049d2
r15     0x7ff9be330000
rip     0x2125f2d0000
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b
exit status 2

I'm not sure whether I should have posted this here or with the mongodb people. The top of the stack trace is the windows syscall file, so I figured I'd see if you guys could see anything of importance here. Everything was working fine and then now this. Also, this isn't necessarily consistent. It is happening MOST of the time, but not all of the time.

Thanks!

**Comment by davecheney** [comment]
Have you rules out interference by anti virus software?

**Comment by LukasDeco** [comment]
There haven't been any changes in my antivirus software since this started.

**Comment by LukasDeco** [comment]
Hmm, actually I just uninstalled stupid webroot and it worked. I'm cautiously thinking it's fixed. How did yo know?

**Comment by davecheney** [comment]
Chalk another one up to Webroot
