### ISSUE TITLE
x/pkgsite: remove kore package

### ISSUE THREAD

**Issue by Ankizle** [golang/go#41498]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/mod/github.com/tusklang/kore
 
### What is your user agent?
 

 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4267.0 Safari/537.36
 
### What did you see instead?

Please remove package github.com/tusklang/kore from pkg.go.dev. I replaced it with github.com/tusklang/tools

**Comment by julieqiu** [comment]
Done.
