### ISSUE TITLE
package GOB "GobEncode()" looping

### ISSUE THREAD

**Issue by archfoe** [golang/go#41496]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.2 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xxx/.cache/go-build"
GOENV="/home/xxx/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/xxx/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xxx/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/6439"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/6439/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build340516344=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

In package:
```
package gob

	switch ut.externalEnc {
	case xGob:
LINE:478	data, err = v.Interface().(GobEncoder).GobEncode() //<--HERE!!!!
	case xBinary:
```

### What did you expect to see?
I had a code:

```
func (ad AgentData) GobEncode() ([]byte, error) {
	var byteData bytes.Buffer
	err := gob.NewEncoder(&byteData).Encode(ad)
	return byteData.Bytes(), err
}
```
end it was creating endless loop from 
```
	err := gob.NewEncoder(&byteData).Encode(ad)
```
back to calling the the function:
```
func (ad AgentData) GobEncode() ([]byte, error) {
```

### What did you see instead?
I traced the code and found that my function:
```
func (ad AgentData) GobEncode() ([]byte, error)
```
has the same name as the package GOB function:

```
LINE:478	data, err = v.Interface().(GobEncoder).GobEncode() //<--HERE!!!!
```

The fix was to rename my function to a different name but still this is a bug.

**Comment by mdempsky** [comment]
It sounds like this is working as intended. encoding/gob provides extension points for users to write optional, custom encoding methods (see https://golang.org/pkg/encoding/gob/#GobEncoder), and you accidentally implemented that interface.
