### ISSUE TITLE
x/tools/gopls: variable in third party package is not highlighted

### ISSUE THREAD

**Issue by normal-cock** [golang/go#41506]
### What version of Go are you using (`go version`)?

```
$ go version
go version go1.14 darwin/amd64

$ gopls version
golang.org/x/tools/gopls v0.5.0
    golang.org/x/tools/gopls@v0.5.0 h1:XEmO9RylgmaXp33iGrWfCGopVYDGBmLy+KmsIsfIo8Y=
```

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
</pre></details>

### What did you do?

nothing

### What did you expect to see?

Code in **my package**:
![image](https://user-images.githubusercontent.com/2618306/93707530-27200c80-fb62-11ea-8176-16fba0e68caa.png)

### What did you see instead?

Code in **third party package**:
![image](https://user-images.githubusercontent.com/2618306/93707541-3f902700-fb62-11ea-8c86-0fc134b9680d.png)

**Comment by stamblerre** [comment]
Can you please share the `gopls` log when you encounter this? It can be found by following the steps [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs).
