### ISSUE TITLE
Go's syntax is special for the sake of particularity, not for brevity

### ISSUE THREAD

**Issue by HuangChangHuai** [golang/go#41533]
# Go's syntax is special for the sake of particularity, not for brevity
# That was weird

**Comment by HuangChangHuai** [comment]
So we why don't  design a personalized syntax format, even if it's use python theme. 
It's all open source projects. 
Why can't we work together to create the fastest, simplest and most readable programming language in the world

**Comment by ianlancetaylor** [comment]
What you are talking about is a different language, not Go.  It's fine to discuss that, but the Go issue tracker is not the right place.  So I'm closing this issue.

Please feel free to use a forum; see https://golang.org/wiki/Questions.  Thanks.
