### ISSUE TITLE
x/playground: Deadlock running context timeout on play.golang.org

### ISSUE THREAD

**Issue by Xeoncross** [golang/go#41534]
The following context timeout deadlocks on play.golang.org but works fine using several recent versions of the Go compiler.

https://play.golang.org/p/7vqNz9WXa6o

```
ctx, cancel := context.WithTimeout(context.Background(), time.Millisecond)
defer cancel()

<-ctx.Done()	
err := ctx.Err()
```

### What did you expect to see?

```
net.Error: context.deadlineExceededError
```

### What did you see instead?

```
timeout running program
```

*Update* Looks like #39016 is related. If we remove the dependency on "net" then the deadlock seems to resolve.

https://play.golang.org/p/NM3xC6_R1_Q

**Comment by cagedmantis** [comment]
@Xeoncross This does seem similar to the bug reported in #39016. I'm going to close this issue since it seems to be a duplicate issue. Would you mind adding the sample case and description to the previous issue?
