### ISSUE TITLE
regexp: implement backtracking search

### ISSUE THREAD

**Issue by rsc** [golang/go#4154]
<pre>In the spirit of RE2's multiple implementations, one possible way to make regexp faster
for easy regexps is to use actual backtracking. We'd only do this for those regexps
where we can compute that backtracking is okay. It would be something like the BitState
execution in RE2 but perhaps the details would be different. We do have a reliable
stack, unlike in C++.</pre>

**Comment by cespare** [comment]
@rsc How does your comment on https://golang.org/cl/2153 relate to this issue?

**Comment by bradfitz** [comment]
So I guess the community should work on their own `regexp` package if the stdlib one is going to be pure and slow?
