### ISSUE TITLE
x/blog:

### ISSUE THREAD

**Issue by sumitgupta153** [golang/go#41541]
### What version of Go are you using (`go version`)?

<pre>
$ go version
I am using go playground and want to point to a blog where example does not seem correct.
https://blog.golang.org/defer-panic-and-recover
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
NA
</pre></details>

### What did you do?

I am just going through go documentation to understand defer, panic, recover. The example does not seem correct.

### What did you expect to see?

    Deferred functions may read and assign to the returning function's named return values.

In this example, a deferred function increments the return value i after the surrounding function returns. Thus, this function returns 2:

func c() (i int) {
    defer func() { i++ }()
    return i
}

### What did you see instead?

    Deferred functions may read and assign to the returning function's named return values.

In this example, a deferred function increments the return value i after the surrounding function returns. Thus, this function returns 2:

func c() (i int) {
    defer func() { i++ }()
    return 1
}

**Comment by ianlancetaylor** [comment]
Try it yourself and see.  With `return 1` the function `c` returns `2`, as the text says.  If you change it to `return i`, then `c` returns `1`.
