### ISSUE TITLE
dwarf: missing type: type.runtime.eface

### ISSUE THREAD

**Issue by XyzenX** [golang/go#41559]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.2 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

OS: Ataraxia Linux 
Arch: amd64
Libc: musl

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="/usr/lib/ccache/bin/gcc"
CXX="/usr/lib/ccache/bin/g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build523840654=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Tried to compile [snapd](https://github.com/snapcore/snapd).

### What did you expect to see?

Build successful.

### What did you see instead?

```
# github.com/snapcore/snapd/cmd/snap
/usr/lib/go/pkg/tool/linux_amd64/link: dwarf: missing type: type.runtime.eface
```

**Comment by thanm** [comment]
I am unable to reproduce this on my work machine (Debian/amd64) using Go 1.15.2.  Is there anything unusual about your configuration?  The error in question seems very improbable; "eface" is a key type used in the Go runtime -- if the linker can't find a type descriptor for it, this suggests a damaged/corrupted installation (bad runtime.a).
