### ISSUE TITLE
go test: .* regexp works correctly only when quoted

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [golang/go#41550]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/greesha/.cache/go-build"
GOENV="/home/greesha/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/greesha/.gvm/pkgsets/go1.15/global/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/greesha/.gvm/pkgsets/go1.15/global"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/greesha/.gvm/gos/go1.15"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/greesha/.gvm/gos/go1.15/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/greesha/WorkProjects/besttarif/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build984587522=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Run command `go test -run .* ./package_name/`.

### What did you expect to see?
If regexp is quoted `go test -run '.*' ./package_name/`-- this command will run all tests in package.

### What did you see instead?
Instead i get:
```
go: finding module for package .gitignore
go: finding module for package .idea
go: finding module for package .git
no Go files in /home/greesha/WorkProjects
malformed module path ".git": leading dot in path element
malformed module path ".gitignore": leading dot in path element
malformed module path ".idea": leading dot in path element
```

**Comment by myitcv** [comment]
This is working as expected. Your shell is expanding the unquoted `*` to be any file/directory in the current directory that begins with a `.` _before_ `go test` is invoked. 

As you have discovered, you need to quote the command in order that `.*` is passed verbatim to the `go` command.
