### ISSUE TITLE
net/http/pprof: imports html/template which causes larger binaries

### ISSUE THREAD

**Issue by egonelbre** [golang/go#41569]
https://github.com/golang/go/blob/0242d461c9293d50f429fc9bdc41a02510b86995/src/net/http/pprof/pprof.go#L64 is using `html/template` which causes the compiler go into conservative mode. `html/template` internally uses `text/template`, which in turn contains a call to `MethodByName`.

It seems that the `pprof` usage of `html/template` is trivial and could be replaced by basic string printing. Of course this means it won't be taking advantage of `html/template` security model.

Does this sound reasonable? I can make a PR, if it does.

**Comment by rsc** [comment]
Sure, go ahead.
