### ISSUE TITLE
cmd/go2go: orderedmap.NewOrdered returns -1 for less than and greater than cases

### ISSUE THREAD

**Issue by rcdmk** [golang/go#41574]
Hi folks,

I was talking a look at the nice code examples for generics in Go 2 path and found a small big in one of them.

**What version of Go are you using (go version)?** Go 2
**What operating system and processor architecture are you using?** N/A
**What did you do?** Read the code at `/src/cmd/go2go/testdata/go2path/src/`
**What did you expect to see?** Correct examples on how to use generics.
**What did you see instead?** One bug in `orderedmap.NewOrdered`.

https://github.com/golang/go/blob/e9e897e0feea35b7e623d91587241bf33af2294c/src/cmd/go2go/testdata/go2path/src/orderedmap/orderedmap.go2#L42-L49

This probably shouldn't be negative 1: https://github.com/golang/go/blob/e9e897e0feea35b7e623d91587241bf33af2294c/src/cmd/go2go/testdata/go2path/src/orderedmap/orderedmap.go2#L48

**Comment by ALTree** [comment]
cc @ianlancetaylor @griesemer

**Comment by griesemer** [comment]
Thanks. Yes, that looks like a typo.

**Comment by griesemer** [comment]
Fixed in dev.go2go repo. Thanks for reporting.
