### ISSUE TITLE
cmd/go: error for 'go list' on a missing package is too terse with implicit '-mod=readonly'

### ISSUE THREAD

**Issue by bcmills** [golang/go#41576]
When `-mod=readonly` is set by default (see #40728), and `go list` fails to find a package named on the command line, it gives an error message of the form `cannot find module providing package …`.

However, with `-mod=mod` the command resolves the missing package and succeeds.

I think that behavior is a bit too subtle. The error message should explain why it didn't _try_ to find a module providing the package, and/or suggest using `go get` to resolve that package.

CC @jayconrod @matloob 

```
example.com$ go version
go version devel +150bd4ff Wed Sep 23 07:51:17 2020 +0000 linux/amd64

example.com$ go mod init example.com
go: creating new go.mod: module example.com

example.com$ go list golang.org/x/text
cannot find module providing package golang.org/x/text

example.com$ go list -mod=mod golang.org/x/text
go: finding module for package golang.org/x/text
go: downloading golang.org/x/text v0.3.3
go: found golang.org/x/text in golang.org/x/text v0.3.3
golang.org/x/text
```

**Comment by bcmills** [comment]
Marked as release-blocker for 1.16, because this situation is much more likely to occur given #40728.

**Comment by mvdan** [comment]
I just got surprised by this too. I had to think about it twice to remember that I should now do `go mod tidy`.
