### ISSUE TITLE
access: Approver, Trybot for Roberto

### ISSUE THREAD

**Issue by empijei** [golang/go#41571]
See https://golang.org/wiki/GerritAccess

Approver, Trybot access request for roberto@golang.org

https://go-review.googlesource.com/#/admin/groups/1005,members
https://go-review.googlesource.com/#/admin/groups/1030,members

**Comment by cagedmantis** [comment]
Hi Roberto,

Thank you for contributing to the Go project! I've discussed this request with the team (/cc @golang/osp-team), and we agreed to grant you access. I've added you to the `may-start-trybots` and `approvers` groups now.

Please be familiar with the rules for voting and submitting changes as described at https://golang.org/wiki/GerritAccess#approver-access-approvers. If you're unsure or have any questions, please don't hesitate to ask us.

Additionally, as described at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a trybot run.

Thank you again for contributing, your help is greatly appreciated!
