### ISSUE TITLE
x/pkgsite: show more than 10 results per page

### ISSUE THREAD

**Issue by seankhliao** [golang/go#41594]
### What is the URL of the page with the issue?
 
 The search results page, ex:
https://pkg.go.dev/search?q=port+scan
 
### What is your user agent?
 

 
 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
 
### Screenshot
 

 
 skip
 
### What did you do?
 

 
 Perform a search
 
### What did you expect to see?
 
 Option to (permanently?) show more than 10 results per page
 
### What did you see instead?

results fixed at 10 per page

This is more of an issue for when there aren't well established/overwhelmingly popular libraries, or when the search is for something generic, where browsing through a longer page results would make the discovery process easier.

**Comment by MistaTwista** [comment]
There is a *limit* query param, to do what you need, currently its max value is 100, [example](https://pkg.go.dev/search?limit=50&page=1&q=port+scan)

I can implement this feature at frontend, I think it should be somewhere here `content/static/html/pages/search.tmpl` or there `content/static/html/helpers/_pagination.tmpl`

**Comment by jba** [comment]
See #47315

**Comment by hyangah** [comment]
Currently pkgsite shows 25 in the first page and provides an option to see more results (with `limit` parameter 100) at the bottom of the page. 

Closing.
