### ISSUE TITLE
x/pkgsite: subdirectories tab less than center column width

### ISSUE THREAD

**Issue by seankhliao** [golang/go#41592]
### What is the URL of the page with the issue?
 
The subdirectory tab
 https://pkg.go.dev/go.opentelemetry.io/otel@v0.11.0?tab=subdirectories
 
### What is your user agent?
 

 
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36`
 
### Screenshot
 

 
 
![2020-09-23-194552](https://user-images.githubusercontent.com/11343221/94049787-b08b4500-fdd5-11ea-8a35-deaca39af8aa.png)

 
### What did you do?
 

 
 visit the tab
 
### What did you expect to see?
 
 The table expanding to the full width of the center column, indicated by the line under the tab switcher
 
### What did you see instead?

narrow table / empty space to the right.

This appears to be a mismatch between the`max-width` of the containing div `.DetailsContent` (`60em`) and the table `table.Directories` (`800px`)

**Comment by julieqiu** [comment]
This tab has been deprecated in favor of a directories section in the redesign. Check it out at [beta.pkg.go.dev](https://beta.pkg.go.dev), and see #41586 for details.

Closing this issue for #41586.
