### ISSUE TITLE
misc/wasm: webassembly performance worse than JavaScript?

### ISSUE THREAD

**Issue by lianghx-319** [golang/go#41599]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.14.8
</pre>

### Does this issue reproduce with the latest release?

[benchmark link](https://lianghx-319.github.io/WebAssembly-benchmark/)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

macOS

test in chrome and firefox.
</pre></details>

#### Fibonacci
Same code implement in C/C++, Golang and Javascript
![image](https://user-images.githubusercontent.com/27187946/94096605-18ce3b00-fe57-11ea-86b9-7f345ec524fd.png)

#### SumInt
For some reason, I can't implement the same as C/C++ in Golang. It's very hard to pass an array to golang wasm, then get the element like slice. So I call js.Value.Index(i).Int() a lot.
![image](https://user-images.githubusercontent.com/27187946/94097547-461be880-fe59-11ea-9d4d-3cfa549f55c4.png)

### What did you expect to see?

Are there someway to improve golang wasm performance?

**Comment by cherrymui** [comment]
I briefly looked at the source code of the benchmarks. It seems the Go case does a lot more work than the JavaScript case. In each iteration, it invokes a callback from JS side, enters the Go runtime, which schedules a goroutine to run the function. It is much more than just computing a number, which is basically what the JS function does.

It is true that there is a non-trivial cost for calling from JS to Go. In practice, you may want to reduce the number of crosses, do as much work on one side as possible then cross to the other side and do as much work.

**Comment by lianghx-319** [comment]
> I briefly looked at the source code of the benchmarks. It seems the Go case does a lot more work than the JavaScript case. In each iteration, it invokes a callback from JS side, enters the Go runtime, which schedules a goroutine to run the function. It is much more than just computing a number, which is basically what the JS function does.
> 
> It is true that there is a non-trivial cost for calling from JS to Go. In practice, you may want to reduce the number of crosses, do as much work on one side as possible then cross to the other side and do as much work.

The `fib` case is almost the same as JS. But the `sum` case, I cannot find a better way to get a JS array in Golang.

**Comment by neelance** [comment]
## `fib` case
This is probably due to the overhead of `fib` calling itself. This overhead is necessary to enable goroutines with webassembly. The proposal https://github.com/WebAssembly/funclets could improve this, but it has been stalled for a long time and I think it is unlikely that it will ever land. WebAssebly coroutines may be another solution, but I can't even find a proposal for them yet.

## `sum` case:
As @cherrymui already said, using `syscall/js` to cross the boundary from Go to JS is slow. A better way to implement this would be to use a TypedArray, copy it to Go and then do the calculation.

**Comment by neelance** [comment]
There is no specific improvement apparent at the moment. Closing.
