### ISSUE TITLE
x/tools/gopls: improve documentation

### ISSUE THREAD

**Issue by stamblerre** [golang/go#41591]
Our current documentation is not very user-friendly and rarely updated.
We should add more information about workflows, features, example configurations, etc.
We should also try to autogenerate as much as possible (https://github.com/golang/go/issues/33544).

**Comment by ainar-g** [comment]
<p>Will&#xA0;the&#xA0;code actions be documented in&#xA0;this issue
as&#xA0;well, or&#xA0;should I&#xA0;file a&#xA0;separate&#xA0;one?</p>

<p>Also,&#xA0;I&#xA0;think I'll be able to&#xA0;contribute some docs
regarding&#xA0;Neovim's (currently nightly-only) native LSP support
in&#xA0;the&#xA0;next few days.&#x2003;Whom should I&#xA0;set
as&#xA0;a&#xA0;reviewer?</p>

**Comment by stamblerre** [comment]
I think we can include an overview of code actions as part of this documentation effort.
You can feel free to add me as a reviewer, but you can also not assign a reviewer and one will get added automatically.

**Comment by stamblerre** [comment]
This issue is probably too general to be useful for tracking purposes. We have made a number of documentation improvements recently, and we are currently working on more. Will close this as a result. If anyone has concerns about our existing documentation, please file a new issue.
