### ISSUE TITLE
spec: a small imperfection in spec

### ISSUE THREAD

**Issue by yaxinlx** [golang/go#41612]
There is one line in spec:
```
x == y+1 && <-chanPtr > 0
```

The name `chanPtr` looks not very nature. Is `chanInt` better?

**Comment by ianlancetaylor** [comment]
Thanks for noticing.  I was able to trace that line all the way back to March 2008 in revision https://go.googlesource.com/go/+/73823d236a063e9e1fd326c07797be3a08b79edb .  Back then I think `chan_ptr` (as this line was written back then) indicated a pointer to a channel, as at that time channels were always written as pointer types (as in `*chan int`).

I agree that today `chanInt` would make more sense here.

CC @griesemer
