### ISSUE TITLE
cmd/compile/internal/logopt: optimizer logging directory doesn't handle Windows

### ISSUE THREAD

**Issue by stamblerre** [golang/go#41614]
We're having trouble working with the GC optimization details on Windows in `gopls`.
It seems that [`checkLogPath`](https://github.com/golang/go/blob/0f55d37d440d83f206bfc00b4a2521c1a0bb258b/src/cmd/compile/internal/logopt/log_opts.go#L274) expects absolute paths to start with `/`, which is not true for Windows file paths (`C:\x\y\z`, etc.). We tried passing a file URI, but that also doesn't work, as file URIs should be of the form `file:///C:/x/y/z`, not `file://C:/x/y/z`. We can work around this with https://golang.org/cl/256940, but I think there are some issues with URI parsing here.

If it's helpful, here is the code that translates between file URIs and filenames in `gopls`: https://github.com/golang/tools/blob/06f3a46a9d1e4913ecf04347e6eea61252bf3c41/internal/span/uri.go.

/cc @pjw @dr2chase

**Comment by dr2chase** [comment]
Darn it, sorry.  
Looks I stepped on an industry-standard rake.
