### ISSUE TITLE
x/build: add builder for ios/arm64

### ISSUE THREAD

**Issue by dmitshur** [golang/go#41610]
[CL 254740](https://golang.org/cl/254740) has added GOOS=ios to the output of `go tool dist list`. `TestTryBotsCompileAllPorts` in x/build/dashobard is failing because we don't yet have a builder (real or misc-compile one) covering the new ios/arm64 pair.

This is the tracking issue to add a builder. We may want to repurpose or clone the existing darwin-arm64-corellium builder for this. Need to think about how to best make this work for Go 1.16 and Go 1.15+1.14 (or maybe we don't try to support 1.15+1.14 because iOS is an experimental port).

/cc @cagedmantis @toothrot @cherrymui

**Comment by dmitshur** [comment]
> We may want to repurpose or clone the existing darwin-arm64-corellium builder for this.

This seems to be our best bet so far. @eliasnaur Are you able to assist with this transition?

@steeve Following up on your offer at https://github.com/golang/go/issues/40523#issuecomment-676423221, are you okay with giving access to the the Corellium dashboard to 3 people on the Go team (myself, @cagedmantis and @toothrot)?

> Need to think about how to best make this work for Go 1.16 and Go 1.15+1.14 (or maybe we don't try to support 1.15+1.14 because iOS is an experimental port).

The [current build policy](https://github.com/golang/build/blob/52a5443f4f3444f6bd726002b56cf32e82844fcf/dashboard/builders.go#L2126-L2128) for the `darwin-arm64-corellium` builder is to build only the master branch on the main Go repository. So, we don't need to do anything to keep 1.15 and 1.14 working since they're out of scope.

Ideally we should modify the host and builder names to use the new GOOS value for iOS. However, changing the host name means a new builder key will become required. @eliasnaur Does supplying a different builder key require rebuilding device snapshots? If it's a lot of trouble, maybe we can keep the host name as is and rename the builder only.

**Comment by steeve** [comment]
@dmitshur Absolutely. I sent invites to you all on your golang.org addresses.

**Comment by eliasnaur** [comment]
> > We may want to repurpose or clone the existing darwin-arm64-corellium builder for this.
> 
> This seems to be our best bet so far. @eliasnaur Are you able to assist with this transition?

Sure, let me know what you want me to do. Have you seen https://github.com/golang/build/tree/master/env/corellium, in particular the `ios` directory?

I believe there are two iOS builders at the moment, which means you should be able to experiment with the other. It may be enough to `scp` an updated https://github.com/golang/build/blob/master/env/corellium/ios/files/builder.sh and updated builder key (see https://github.com/golang/build/blob/da0cd803ac9a4447a7ef245838cc6ac90b012a4c/env/corellium/ios/install.sh#L33).

**Comment by dmitshur** [comment]
@steeve Thanks for the answer and sorry that my comment was possibly misleading. There are more steps we need to take on our side before we'd be able to offer help with directly managing the dashboard, and I don't expect that will be resolved quickly.

@eliasnaur I should be able to help review CLs for x/build if you're open to take on this work. It's no problem and completely understandable if you don't have the bandwidth to get to this.

**Comment by steeve** [comment]
> @steeve Thanks for the answer and sorry that my comment was possibly misleading. There are more steps we need to take on our side before we'd be able to offer help with directly managing the dashboard, and I don't expect that will be resolved quickly.

No worries, let me know once you folks are ready.
