### ISSUE TITLE
net/http: TestHTTP2UpgradeClosesConnection failure on solaris-amd64-oraclerel builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#41629]
[2020-09-25T01:47:40-fa04d48/solaris-amd64-oraclerel](https://build.golang.org/log/6a6b15a570fdf314f5f5fea2b4d1c9ef327f4951)

```
--- FAIL: TestHTTP2UpgradeClosesConnection (17.51s)
    serve_test.go:1096: body not closed after 5s
FAIL
FAIL	net/http	20.671s
```

Could just be a slow builder, although 5 seconds seems like a long time.

CC @bradfitz @neild

**Comment by networkimprov** [comment]
cc @fraenkel

**Comment by fraenkel** [comment]
A bit difficult to figure out what went wrong but given that sending a request and receiving a response took 12s, I would say something was wrong before we hit this timeout.

**Comment by bcmills** [comment]
`greplogs --dashboard --md -l -e 'FAIL: TestHTTP2UpgradeClosesConnection .*(?:\n    .*)*body not closed after' --since=2021-01-01`

[no results]

Closing as “possibly fixed”.
