### ISSUE TITLE
x/pkgsite: documentation not shown for package correctly detected as Apache-2.0 licensed

### ISSUE THREAD

**Issue by fvbommel** [golang/go#41636]
### What is the URL of the page with the issue?

<https://pkg.go.dev/github.com/docker/docker-ce/components/cli/cli/command/config>
 
### What is your user agent?
 
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0 
 
### Screenshot

![image](https://user-images.githubusercontent.com/4797722/94336245-e13fca00-ffe1-11ea-8372-b9573ffba752.png)
 
### What did you do?

I opened the page.
 
### What did you expect to see?
 
Documentation, something like [the godoc.org version](https://godoc.org/github.com/docker/docker-ce/components/cli/cli/command/config).
 
### What did you see instead?

> License: [Apache-2.0](https://pkg.go.dev/github.com/docker/docker-ce/components/cli/cli/command/config?tab=licenses#lic-0)

Followed by

> “Doc” not displayed due to license restrictions.  
>  
> See our [license policy](https://pkg.go.dev/license-policy).

According to the linked license policy "Apache-2.0" should be an allowed license.

Interestingly, clicking the license name leads to the Licenses tab, which bears a similar message:

> “Licenses” not displayed due to license restrictions.  
>  
> See our [license policy](https://pkg.go.dev/license-policy).

**Comment by jamalc** [comment]
This is no longer an issue in the latest version, v0.0.0-...-d116887. 

The module github.com/docker/docker-ce@v0.0.0-...-4484c46 contains no license at the root. Maybe the license at github.com/docker/docker-ce/@v0.0.0-...-4484c46/components/cli should have been sufficient. @jba @julieqiu could you take a look?

**Comment by jba** [comment]
Today, master has a LICENSE file. But the repo is marked deprecated and to be archived. I don't think there's anything for us to do here.
