### ISSUE TITLE
【final reason is the anti-virus software, you need to shut it down or add white list】this version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher. 

### ISSUE THREAD

**Issue by ApexPredator1** [golang/go#41631]
content of test1.go：
```
package main

import "fmt"

func main() {
	fmt.Println("hello world")
}
```

i run "go run test1.go"，and then an error occured: 
```
fork/exec C:\Users\preda\AppData\Local\Temp\go-build387128326\b001\exe\test1.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```

here is "go version" result：
```
go version go1.15.2 windows/amd64
```

here is "systeminfo" result：
![image](https://user-images.githubusercontent.com/42485943/94275266-53c88f80-ff79-11ea-856e-6eead798f533.png)

here is "go env" result：
```
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\preda\AppData\Local\go-build
set GOENV=C:\Users\preda\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=G:\softwares\gopath
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=G:\softwares\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=G:\softwares\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\preda\AppData\Local\Temp\go-build639531722=/tmp/go-build -gno-record-gcc-switches
```

I saw that someone had this problem, but his problem was closed and not solved
![image](https://user-images.githubusercontent.com/42485943/94273378-eb78ae80-ff76-11ea-8752-e96eaed8608f.png)

**Comment by seankhliao** [comment]
please fill out the issue template properly, in particular the output of `go version`, and the Windows OS version

**Comment by ApexPredator1** [comment]
> please fill out the issue template properly, in particular the output of `go version`, and the Windows OS version

ok

**Comment by andybons** [comment]
@ianlancetaylor @aclements

**Comment by ianlancetaylor** [comment]
Does this happen for a simple "hello, world" program, or does it only happen when you use the sync/atomic package?

**Comment by ApexPredator1** [comment]
> Does this happen for a simple "hello, world" program, or does it only happen when you use the sync/atomic package?

yes，even if there is a simple "hello, world" program, it will report an error, and there is a strange phenomenon: it behaves differently depending on the code, it can run normally for example1 below when i right-click "Run go build test1.go",but it report an error(Error running "go build test1.go") when i run example2 by right clicking "Run go build test1.go"

example1:
![image](https://user-images.githubusercontent.com/42485943/94652769-225f1380-032d-11eb-8090-2b79c1361189.png)

example2:
![image](https://user-images.githubusercontent.com/42485943/94652887-4cb0d100-032d-11eb-9482-ed28422e7be0.png)
![image](https://user-images.githubusercontent.com/42485943/94652934-589c9300-032d-11eb-8dea-bbab2b92b237.png)

**Comment by networkimprov** [comment]
What anti-virus software is running on the machines you've used, and have you tried disabling/uninstalling it?

**Comment by ApexPredator1** [comment]
> What anti-virus software is running on the machines you've used, and have you tried disabling/uninstalling it?

OMG!  it works! i add the path "C:\Users\sangfor\AppData\Local\Temp" to my anti-virus software's white list, problem solved! thanks for your tip

**Comment by networkimprov** [comment]
Could you retitle the issue to name the anti-virus software so that others can find this issue?

Also, if problem solved you can close the issue too :-)

@gopherbot remove WaitingForInfo

**Comment by ApexPredator1** [comment]
> Could you retitle the issue to name the anti-virus software so that others can find this issue?
> 
> Also, if problem solved you can close the issue too :-)
> 
> @gopherbot remove WaitingForInfo

OK

**Comment by networkimprov** [comment]
Hi, sorry, can you name the specific anti-virus product in the title?

The title beginning should look like: `runtime: Product_Name anti-virus causes "this version of %1 is ... "`

**Comment by ApexPredator1** [comment]
> Hi, sorry, can you name the specific anti-virus product in the title?
> 
> The title beginning should look like: `runtime: Product_Name anti-virus causes "this version of %1 is ... "`

OK
