### ISSUE TITLE
gollvm: absent build targets for generating archived binaries + libs

### ISSUE THREAD

**Issue by advancedwebdeveloper** [golang/go#41632]
There is no way to generate an installation archive, after building gollvm.

[](https://go.googlesource.com/gollvm/#using) - Ninja interprets external build folder as an out-of-date, so I am not sure how I could find a workaround. Maybe using GNU make would solve this. The only thraightforward option is to add a target, suitable for Ninja/GNU Make/whatever else , to generate an archive file (instead of "installation" target).

**Comment by thanm** [comment]
What exactly do you mean by an installation archive? Why not just tar up the contents of the CMAKE_INSTALL_PREFIX directory once the installation ninja target is complete?

**Comment by advancedwebdeveloper** [comment]
> What exactly do you mean by an installation archive? Why not just tar up the contents of the CMAKE_INSTALL_PREFIX directory once the installation ninja target is complete?

Probably cause coppied files would be mixed with various non-related files, in few system folders. So extracting that has no sense.

So the demand is still here.

**Comment by thanm** [comment]
Sorry, but I am still not clear on what you are asking for.
