### ISSUE TITLE
net/http/httputil: ReverseProxy.handleUpgradeResponse should copy response header back to http.ResponseWriter

### ISSUE THREAD

**Issue by aofei** [golang/go#41634]
In the `ReverseProxy.ServeHTTP`, we should always copy the response header returned by the upstream back to our `http.ResponseWriter` (when everything is fine). But currently we've missed this point in the implementation of WebSocket reverse proxy, which may affect users. For example, someone may want to log response headers in their middleware.

**Comment by davecheney** [comment]
@aofei thank you for raising this issue. Would you be able to explain why this change is needed. For example, what can you not do currently that you would be able to do with this change?

**Comment by aofei** [comment]
Hi @davecheney,

The main purpose of this change is to make the behavior of WebSocket reverse proxy **consistent with other types**.

In other types of reverse proxy (non-WebSocket) scenarios, we can directly access our `http.ResponseWriter.Header` to get all the response headers returned by the upstream. Thanks to this line:

https://github.com/golang/go/blob/8266570ba71fd6af9c07d8fac945b3710010dfc7/src/net/http/httputil/reverseproxy.go#L313

But for the WebSocket reverse proxy, we can't do this. Because the [`ReversePorxy.handleUpgradeResponse`](https://github.com/golang/go/blob/8266570ba71fd6af9c07d8fac945b3710010dfc7/src/net/http/httputil/reverseproxy.go#L540) writes those response headers directly to the client through the hijacked connection, without copying them to our `http.ResponseWriter.Header`. In this case, those response headers are "invisible" to us (although we can still get them by hacking the `ReverseProxy.ModifyResponse`).

**Comment by andybons** [comment]
@bradfitz

**Comment by bradfitz** [comment]
Seems reasonable. Leaving for @neild for reviewing the implementation & test.
