### ISSUE TITLE
net/http/httputil: ReverseProxy flush immediately additional case

### ISSUE THREAD

**Issue by jsign** [golang/go#41642]
While using `ReverseProxy` in a _stream-based_ HTTP API I got hit by the default value of `FlushInterval`. This API used a `Transfer-Encoding: chunked` and `Content-Length: -1` for the intention of a stream-based response.

The default value of `FlushInterval` isn't latency based nor _flush immediately_ which seems fine in general, but in this particular case, the end client (talking with the reverse-proxy) wasn't seeing any stream messages since they were being buffered until the HTTP response finished, which in this case was never since only gets canceled by the client.

Looking at `ReverseProxy` implementation the solution was simple, just use `FlushInterval = -1` to signal to flush immediately. Interestingly, the exact same situation was in a [TODO](https://github.com/golang/go/blob/ad618689ef06e9dca86c0e2b9b38a2c1b9266f4a/src/net/http/httputil/reverseproxy.go#L409) comment which from my point of view sounds like it might be a good idea to implement.

I'm opening the discussion to see if makes sense. If that's the case, I can propose a PR if we decide is a good idea to also flush immediately on `Content-Length: -1` or other decided case in addition to the current exception `Content-Type: "text/event-stream"`.

**Comment by aofei** [comment]
FYI, [Caddy's approach](https://github.com/caddyserver/caddy/blob/c94f5bb7dd3c98d6573c44f06d99c7252911a9fa/modules/caddyhttp/reverseproxy/streaming.go#L88-L124).

**Comment by andybons** [comment]
@bradfitz

**Comment by bradfitz** [comment]
Doing that TODO from line 409 seems reasonable.

/cc @neild

**Comment by jsign** [comment]
Sounds good, I can take care of this. I'll make a PR in the next days.

**Comment by networkimprov** [comment]
cc @odeke-em as possible reviewer.

**Comment by odeke-em** [comment]
Thank you for the tag @networkimprov :) I've provided my review.

**Comment by odeke-em** [comment]
@dmitshur should we perhaps backport this change?

**Comment by dmitshur** [comment]
This was a TODO comment added 2 years ago that was only reported 2 weeks ago. That suggests to me it's not a very serious issue, and fine to leave for 1.16.
