### ISSUE TITLE
x/image/font/opentype: fail to parse arcade_n.ttf

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#41658]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hajimehoshi/Library/Caches/go-build"
GOENV="/Users/hajimehoshi/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/hajimehoshi/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/hajimehoshi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/60/khbk2xqn1c5bml1byjn89dwc0000gn/T/go-build345053018=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

1. Download arcade_n.ttf from ~http://9031.com/fonts/#arcade~ https://www.dafont.com/arcade-ya.font
2. Parse it with `opentype.Parse`

### What did you expect to see?

No error

### What did you see instead?

Error `sfnt: invalid OS/2 table` from `opentype.Parse`

At lease, this can be parsed with `github.com/golang/freetype/truetype`. I'm not sure which the font or the opentype library is to blame.

CC @nigeltao

**Comment by hajimehoshi** [comment]
Sorry but `Arcade-Regular.ttf` was an old version and seems no longer available in the website. Let me close this.

**Comment by hajimehoshi** [comment]
Refound the font file at https://www.dafont.com/arcade-ya.font

**Comment by andybons** [comment]
@nigeltao
