### ISSUE TITLE
x/tools/gopls: blank identifiers ("_") show up in Outline view

### ISSUE THREAD

**Issue by aohren** [golang/go#41654]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
```
go version go1.15.2 darwin/amd64
```
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
```
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:23:52.277Z (2 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```
- Check your installed extensions to get the version of the VS Code Go extension 
```
0.17.0
```
- Run `go env` to get the go development environment details
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/adam/Library/Caches/go-build"
GOENV="/Users/adam/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/adam/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/adam/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/local/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/local/lib/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="/usr/bin/clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xs/311gpt813yj9rkcwb6qgfz340000gn/T/go-build917392284=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
### Share the Go related settings you have added/edited

```
    "go.formatTool": "goimports",
    "go.docsTool": "guru",
    "go.useLanguageServer": true,
    "go.addTags": {
    
    },
```

### Describe the bug
Package level blank identifier s("_") show up in the Outline view as just "_". This looks especially bizarre when setting package level variables from a multivalued return function by discarding one of the returned values. 

Here's a screenshot of what I mean:
<img width="1317" alt="Screen Shot 2020-09-27 at 12 39 28" src="https://user-images.githubusercontent.com/6468226/94364156-330a5200-00bf-11eb-8249-2ca8f0b8a5c5.png">

### Steps to reproduce the behavior:

Rendering this `main.go` in the editor shows three _ identifiers in the Outline view:

```
package main

var (
	InstanceA, _ = NewMyType()
	InstanceB, _ = NewMyType()
	InstanceC, _ = NewMyType()
)

type MyType struct{}

func NewMyType() (*MyType, error) {
	return &MyType{}, nil
}

func main() {

}
```

**Comment by stamblerre** [comment]
Thanks for the report! This is an issue with the language server, so I've transferred it to the language server's issue tracker. We'll aim to get this fixed for a future release.
