### ISSUE TITLE
cmd/compile: missed opportunity to coalesce reads/writes

### ISSUE THREAD

**Issue by josharian** [golang/go#41663]
```go
package p

import "encoding/binary"

func f(b []byte, x *[8]byte) {
	_ = b[8]
	t := binary.LittleEndian.Uint64(x[:])
	binary.LittleEndian.PutUint64(b, t)
}
```

This should compile down to two MOVQs on amd64, one to load from x and one to write to b.

Instead, it compiles to a series of smaller MOVxs. The coalescing rules may need more cases added.

cc @randall77 @dr2chase @martisch @mundaym

**Comment by agarciamontoro** [comment]
I'd like to work on this one!

**Comment by mundaym** [comment]
@agarciamontoro Thanks for offering to take a look. I suspect the best place to start is to add a new test in `test/codegen/memcombine.go`. You'll want to check that no small MOV* operations are generated using the annotations, for example:

```go
func f(b []byte, x *[8]byte) {
	_ = b[8]
        // amd64:`MOVQ\s[A-Z]+,\s1\([A-Z]+\)`,-`MOVB`,-`MOVW`,-`MOVL`
	binary.LittleEndian.PutUint64(b, binary.LittleEndian.Uint64(x[:]))
}
```

After verifying that your new test fails the tricky bit will be trying to figure out why the existing rules don't work. Most likely another optimization is being applied first and that is interfering with the pattern match. `GOSSAFUNC` will be useful for trying to figure out what is going on. You can find the optimization rules for load/store merging on AMD64 in https://github.com/golang/go/blob/874b3132a84cf76da6a48978826c04c380a37a50/src/cmd/compile/internal/ssa/gen/AMD64.rules#L1500-L1995.

Finally if you get a chance, try and check that other architectures optimize the pattern too. `arm64`, `ppc64le` and `s390x` all also do unaligned load/store merging.

**Comment by mundaym** [comment]
Aside: it would be really nice to do the unaligned load/store merging optimizations in a generic optimization pass. These rules are quite hard to maintain when there are a lot of optimizations that might interfere with the target patterns.

**Comment by mvdan** [comment]
As a quick aside, when new rules are added, is there anything to warn us about them making other rules suddenly trigger less often? With the huge amount of rules we have today, it's practically impossible to foresee that kind of interaction.

I guess we can keep adding more and more tests to cover common cases, but it still feels like some sort of tooling would be nice. I imagine there are a few rules today that basically never trigger anymore, for example.

**Comment by mundaym** [comment]
@mvdan I use compilecmp a lot (https://github.com/josharian/compilecmp). That at least tells me when the generated code for a function grows significantly (often a sign I've broken a pre-existing rewrite rule). In practice the codegen tests are also fairly good at catching a lot of stuff, there is quite a lot of coverage there now.

**Comment by agarciamontoro** [comment]
Thank you for all the detailed info, I'll start investigating as soon as possible! I may get back to you in the following days with questions, this would be my first contribution to the project :)

**Comment by josharian** [comment]
I just bumped into this again. @agarciamontoro anything I can do to help you out here?

**Comment by agarciamontoro** [comment]
Hi @josharian, sorry for the ghosting here, life got in the way!

I did take a look into this a couple of weeks ago and learned quite a lot about how everything works. However, I got stuck when trying to identify which rules apply to the generated code here. My initial idea was to simply add a new rule that covers this specific issue, but I wanted to first find the root cause of the wrong rule (or rules).

The problem is that we're generating code to store a byte, then a long, then a word, and finally the last byte.
```
v34 (+79) = MOVQload <uint64> v7 v1
v171 (+84) = MOVBstore <mem> v248 v34 v1
v168 (+85) = SHRQconst <uint64> [8] v34
v216 (+89) = SHRQconst <uint64> [40] v34
v180 (+91) = SHRQconst <uint64> [56] v34
v219 (88) = MOVLstore <mem> [1] v248 v168 v171
v243 (90) = MOVWstore <mem> [5] v248 v216 v219
v255 (91) = MOVBstore <mem> [7] v248 v180 v243
```

There are of course rules for the "normal" cases, where we coalesce sequential byte stores in a quad. But there is not something for converting the sequence B, L, W, B into a Q. We could add a specific rule for that, but I would like to know why we have this weird sequence in the first place (which is where I got stuck).

If you could give me a hint on where to look at to debug this, it would be awesome.

**Comment by josharian** [comment]
No worries on disappearing. It’s been a tough, unpredictable year for everyone.

It’s not easy to debug ssa rewrite rules. There’s a logging mode you can use: pass the compiler the flag `-d=ssa/lower/debug=2`. But the output may be voluminous. And managing rewrite rule dependencies is a headache. As long as there’s a codegen test I’d personally be comfortable just matching the 1-4-2-1 pattern.

Don’t hesitate to ask if there’s more we can help with.

**Comment by agarciamontoro** [comment]
Thank you for the tip, I'll try to investigate the issue with the logging mode. If there's not any success, I'll simply match the weird pattern, I already have the codegen test.

Thanks for the help!

**Comment by josharian** [comment]
Marking this as Go 1.17. It is a regression, I've encountered it in multiple codebases, it has come up multiple times in Gopher Slack, and it is impacting design decisions in inet.af/netaddr.

**Comment by agarciamontoro** [comment]
Expect something from my side this weekend, @josharian, I'm on vacation now and have a bit more time. If I'm not able to solve it by then, I'll let it free :)

**Comment by josharian** [comment]
We have a few months yet before 1.17, so no rush. :)

**Comment by agarciamontoro** [comment]
It looks like a have a working rule, both for `amd64`:

```
(MOVBstore [7] p1 (SHRQconst [56] w)
  x1:(MOVWstore [5] p1 (SHRQconst [40] w)
  x2:(MOVLstore [1] p1 (SHRQconst [8] w)
  x3:(MOVBstore p1 w mem))))
  && x1.Uses == 1
  && x2.Uses == 1
  && x3.Uses == 1
  && clobber(x1, x2, x3)
  => (MOVQstore p1 w mem)
```

and for `s390x`, using its corresponding ops:

```
(MOVBstore [7] p1 (SRDconst w)
  x1:(MOVHBRstore [5] p1 (SRDconst w)
  x2:(MOVWBRstore [1] p1 (SRDconst w)
  x3:(MOVBstore p1 w mem))))
  && x1.Uses == 1
  && x2.Uses == 1
  && x3.Uses == 1
  && clobber(x1, x2, x3)
  => (MOVDBRstore p1 w mem)
```

The current rules seem to already optimize the generated code both for `arm64` and `ppc64le`, so I did not need to do anything else there.

This change makes the new codegen test pass, but I do have a couple of questions before submitting a patch:

1. I'm not sure if these rules are too specific (both the pattern itself and the constants in the move and shift ops). Maybe specificity is not an issue at this step (you already said that you were ok matching the 1-4-2-1 pattern), but I'm curious about how you evaluate/measure that (if there is a need to evaluate that at all). I'm mostly concerned about avoidable performance issues that could arise from adding overly-specific rules that match weird patterns.
2. I tested this for other architectures using the `--all_codegen` flag (as in `go run test/run.go --all_codegen -- test/codegen/memcombine.go`), but I'm not sure whether this is the right approach. Should I do anything else to test this for other architectures other than `amd64`?

**Comment by agnivade** [comment]
Nice work @agarciamontoro.

1. I'll let @josharian answer that. But we usually look at the impact of the change and how widespread it is. If it has a significant impact, and the change is minimal, it should be okay to add a specific pattern. But the question does come up as to why just use 1 and not the rest of 4!-1 patterns.
2. is the right approach. As long as you have architecture specific annotations, you don't need to do anything else.

**Comment by agarciamontoro** [comment]
Thank you, @agnivade!

> But the question does come up as to why just use 1 and not the rest of 4!-1 patterns.

Yup, that's a good question. The specific pattern I used is the one generated when compiling the function in the description of the issue. My guess is that this happens because of the order of the previously applied rules, but I was not able to identify the ones that caused the problem: the output from `-gcflags=-d=ssa/lower/debug=2` is indeed voluminous, and from what I saw, it logs every value changed instead of every rule applied (which can affect multiple values), so it's hard to keep track of what's happening. Is there some other debug mode I don't know of that we could use here?

I can probably come up with a rule that covers all the cases, but do we have proof of the other cases actually happening? I'm not sure how we could check that.

**Comment by josharian** [comment]
Yay!

> I'm not sure if these rules are too specific (both the pattern itself and the constants in the move and shift ops). Maybe specificity is not an issue at this step (you already said that you were ok matching the 1-4-2-1 pattern), but I'm curious about how you evaluate/measure that (if there is a need to evaluate that at all).

The specificity is fine. This is a particular pattern that arises, so this is the pattern we match. It would be nice eventually do to something more principled around how we order and apply rewrite rules, but it gets very weedy very quickly, and this is Good Enough. And we have codegen tests to prevent regressions.

> I'm mostly concerned about avoidable performance issues that could arise from adding overly-specific rules that match weird patterns.

The incremental cost of adding additional rewrite rules is very low.

If you're curious, you could add an `&& noteRule("1421")` to the LHS of the rule and re-run make.bash to see how often it triggers. Or use `compilecmp -fn=changed` to see what functions get optimized. But in this case, because we know it shows up in the wild, that supporting evidence is not too critical.

**Comment by agarciamontoro** [comment]
Just sent the change matching the specific pattern. Thank you for the tip on the `noteRule`, though, it's super useful!
