### ISSUE TITLE
Struct Reflection result is wrong

### ISSUE THREAD

**Issue by CengSin** [golang/go#41667]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.2 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/cengsin/Library/Caches/go-build"
GOENV="/Users/cengsin/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/cengsin/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/cengsin/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/cengsin/GolandWS/GoModuleDemo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dt/4jzmc_m167s8cy0b5pw0qgmm0000gn/T/go-build998003084=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.15.2 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.15.2
uname -v: Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2
lldb --version: lldb-1103.0.22.10
Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
</pre></details>

### What did you do?

```go


type A2 struct {
	Name string
}

func main() {
	Func1(&A2{})
}

func Func1(values ...interface{}) {
	for _, value := range values {
		Func2(value)
	}
}

func Func2(values ...interface{}) {
	Func3(values)
}

func Func3(values ...interface{}) {
	Func4(values)
}

func Func4(values interface{}) {
	modelType := reflect.TypeOf(values)
	for modelType.Kind() == reflect.Slice || modelType.Kind() == reflect.Array || modelType.Kind() == reflect.Ptr {
		modelType = modelType.Elem()
	}
	fmt.Println(modelType.Kind())
}
```

#### output:

```
/private/var/folders/dt/4jzmc_m167s8cy0b5pw0qgmm0000gn/T/___go_build_GoModuleDemo_go__2_
interface
```

Should be a structure type, the result becomes an interface

### What did you expect to see?

result is Struct

### What did you see instead?

```go

type A2 struct {
	Name string
}

func main() {
	Func1(&A2{})
}

func Func1(values ...interface{}) {
	for _, value := range values {
		Func2(value)
	}
}

func Func2(values ...interface{}) {
	for _, value := range values {
		Func3(value)
	}
}

func Func3(values ...interface{}) {
	for _, value := range values {
		Func4(value)
	}
}

func Func4(values interface{}) {
	modelType := reflect.TypeOf(values)
	for modelType.Kind() == reflect.Slice || modelType.Kind() == reflect.Array || modelType.Kind() == reflect.Ptr {
		modelType = modelType.Elem()
	}
	fmt.Println(modelType.Kind())
}
```

This way is the correct result

**Comment by D1CED** [comment]
What gets passed to Func4 is different in both versions. If we add the statement `fmt.Printf("%#v\n", values)` this becomes apparent.

The first version produces `[]interface {}{[]interface {}{(*main.A2)(0xc000010060)}}` (arbitrary pointer value) while the second version outputs &main.A2{Name:""}.

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
