### ISSUE TITLE
db.ExecContext successfully executes query, but returns obscure driverResult error

### ISSUE THREAD

**Issue by AndrewYinLi** [golang/go#41671]
Go version: 1.12.7

Couldn't find anything on this error: `sql.driverResult{Locker:(*sql.driverConn)(0xc00023ef80), resi:5}`
Query: `UPDATE deployment.users SET deactivated = $1 WHERE (email LIKE $2 AND deactivated = $3 AND created <= $4 AND organization_id = $5`

The query successfully executes as intended but I'm concerned about this error.

**Comment by AndrewYinLi** [comment]
It's 4am and I'm tired. Resolved the issue on my end.

**Comment by davecheney** [comment]
@AndrewYinLi I'm glad to hear you fixed your issue. Please consider upgrading to Go 1.15 or later. Go 1.12 is _very_ not supported.
