### ISSUE TITLE
plugin: cyclic dependencies are allowed

### ISSUE THREAD

**Issue by FloThinksPi** [golang/go#41672]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.15.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/REDACTED/.cache/go-build"
GOENV="/home/REDACTED/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/REDACTED/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build171908665=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Normally golang prohibits cyclic imports on compile time.

                    project/first
                     ^           \    
                    /             \
                   /               \ 
                  /                \/
         project/third <--- project/second

However if one uses plugins(each package in an own plugin) and load all thre plugins dynamically in a program, it is allowed (plugin load does not fail). However the result (in the case of my implementation mistake where i noticed it) is an infinite loop as all involved functions call themselfs in a cycle.

### What did you expect to see?
Out of uniformity i expected that cyclic imports are also not possible in plugins.
I expected the plugin load to fail on the last of the 3 plugins when the cycle "closes"

### What did you see instead?
Cyclic imports are possible and result in e.g. infinite loops.

Is this a conscious design choice ? I did not find any documentation for this behaviour.
If necessary to understand it i could make a minimal code example.

**Comment by andybons** [comment]
@ianlancetaylor

**Comment by FloThinksPi** [comment]
Hm one may need to add here that i pass the function from plugin 1 in an empty interface trough the main programm to plugin 2 which casts it to a struct specified in plugin 1 and vice versa. I think this is why cyclic imports happened and the compiler could not know since it only sees empty interfaces being passed around, although plugin 1 imports the struct of plugin 2 and vice versa.

**Comment by cherrymui** [comment]
Could you share a code example? I'm not sure how you can build something with import cycles into plugins.

**Comment by FloThinksPi** [comment]
@cherrymui i build this: https://github.com/FloThinksPi/go-plugin-cyclic-dependencie-test
While doing it i noticed the plugins three and four are not real cyclic imports, they are more like this:
```
                plugin_example/main
                 ^           ^    
                /             \
               /               \ 
              \/               \/
     plugins/three      plugins/four
               ^              ^    
               |              |
               |              | 
               \/             \/
plugins/fourInterface      plugins/threeInterface
```

Also i think as this is evaluated at runtime there is no option for the compiler or pluginloader to know it ?
