### ISSUE TITLE
gofmt should respect "./..." notation, just like other standard Go tools

### ISSUE THREAD

**Issue by mcandre** [golang/go#41677]
Getting gofmt to properly recurse over all Go project files is a hassle. Please have `gofmt` interpret `./...` path notation to expand to all project Go source files, just like other standard Go tools behave.

**Comment by slrz** [comment]
`go fmt ./...` will invoke the gofmt program on all files matched by the pattern.

**Comment by mvdan** [comment]
What @slrz said, you want `go fmt`.
