### ISSUE TITLE
cmd/compile: ppc64le: Invalid n or b for CLRLSLDI: 30 28

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#41683]
On current tip (874b3132a84cf76da6a48978826c04c380a37a50, CL 247477) this valid code gets an incorrect compilation error with `GOARCH=ppc64le`.

I believe this is due to CL 252097.  CC @laboger @ceseo @pmur 

```Go
package p

func F(s int32, n uint64) uint64 {
	c := (s >> 1) & 0xffffff
	return uint64(c)<<48
}
```

This is the compilation error with `GOARCH=ppc64le`.  Note the missing `%v` message.

```
foo.go:5:2: Invalid n or b for CLRLSLDI: 30 28
%!v(MISSING)
```

**Comment by ceseo** [comment]
Looking into it.

**Comment by laboger** [comment]
I see the problem. The rules that use AND need to do more checking of mask length and shift count.
