### ISSUE TITLE
x/crypto/nacl/auth: Sum() copies Size bytes into KeySize sized array

### ISSUE THREAD

**Issue by sauerbraten** [golang/go#41692]
The auth package's Sum() function currently uses the `KeySize` constant to allocate an array for the authenticator to return (of type `[Size]byte`). It works fine since both constants are equal to 32, but https://github.com/golang/crypto/blob/5c72a883971a4325f8c62bf07b6d38c20ea47a6a/nacl/auth/auth.go#L43 should still use the `Size` constant for clarity.

The original NaCl C++ API uses the equivalent `BYTES` constant (not `KEYBYTES`): https://github.com/jeremywohl/nacl/blob/515c9bf085b5154d553ecf04288936850819c788/crypto_auth/wrapper-auth.cpp#L8

**Comment by FiloSottile** [comment]
Good catch, we'd welcome a PR to fix this.
