### ISSUE TITLE
x/blog:  Go Concurrency Patterns: Pipelines and cancellation

### ISSUE THREAD

**Issue by mihailstefanov** [golang/go#41693]
In 
 [Go Concurrency Patterns: Pipelines and cancellation](https://blog.golang.org/pipelines), blog post is  example which state like this

```go

// Start an output goroutine for each input channel in cs.  output
// copies values from c to out until c is closed or it receives a value
// from done, then output calls wg.Done.
output := func(c <-chan int) {
        for n := range c {
            select {
            case out <- n:
            case <-done:
            }
        }
        wg.Done()
    }
```

I think it will never reach wg.Done(), or may be I am wrong?

**Comment by ALTree** [comment]
The `range` loop will terminate when the channel is closed. So yes, it'll reach wg.Done (as long as the input channel is closed).

**Comment by mihailstefanov** [comment]
But if you read carefully, "or it receives a value from done, then output calls wg.Done." So will not be closed in case it receives done! In such case selecting on done is useless.

**Comment by ALTree** [comment]
The text just above says 

> (We'll discuss in a moment how to allow this loop to return early.)

And then a snippet below shows that the final implementation is 

```
 output := func(c <-chan int) {
        defer wg.Done()
        for n := range c {
            select {
            case out <- n:
            case <-done:
                return
            }
        }
    }
```

The blogpost is incrementally building a working solution.

**Comment by mihailstefanov** [comment]
So comment is misleading then. Missing goto :)
