### ISSUE TITLE
language: math symbols in identifier

### ISSUE THREAD

**Issue by qlcom** [golang/go#41707]
why math symbols like `∇`, `√` can't be used as identifier?

**Comment by cespare** [comment]
[Go only allows letters and digits](https://golang.org/ref/spec#Characters) in identifiers. ∇ and √ are Unicode math symbols (category Sm) and therefore are not allowed.

See https://github.com/golang/go/wiki/Questions for asking general questions about Go. Thanks!

**Comment by qlcom** [comment]
> ∇ and √ are Unicode math symbols (category Sm) and therefore are not allowed.

What is the reason for it?

**Comment by ianlancetaylor** [comment]
Please see https://golang.org/wiki/Questions.  Thanks.
