### ISSUE TITLE
all: reset master to remove accidental merge CL

### ISSUE THREAD

**Issue by dmitshur** [golang/go#41718]
The merge [CL 258525](https://golang.org/cl/258525) was accidentally merged into the master branch, rather than the intended branch.

I'll rewrite history to revert master to the parent commit, which is `846dce9d05f19a1f53465e62a304dea21b99f910`.

**Comment by dmitshur** [comment]
This is now done.

If you've submitted a CL to master branch recently and it's not there now, please re-send it.

**Comment by networkimprov** [comment]
What was the HEAD right before history was rewritten?

**Comment by dmitshur** [comment]
It was previously `48e542e58588bc75faacd63439f40e57db80b2f1` at the time of the force push.

From looking, the only CL I see dropped was [CL 258437](https://golang.org/cl/258437). It was re-sent as [CL 258677](https://golang.org/cl/258677).
