### ISSUE TITLE
x/tools/gopls: add unit tests for snapshot.clone

### ISSUE THREAD

**Issue by stamblerre** [golang/go#41719]
It could also probably benefit from being refactored -- it is getting very long and complicated.

See https://golang.org/cl/258121.

**Comment by findleyr** [comment]
I factored out some of the cloning logic into cache/workspace.go, which has unit tests.  We could probably carve it up a bit more though.

**Comment by findleyr** [comment]
This is unfeasible without a refactoring, so let's not keep this issue around.
