### ISSUE TITLE
encoding/json: invalid use of ,string struct tag, trying to unmarshal "" into int

### ISSUE THREAD

**Issue by andig** [golang/go#41731]
### What version of Go are you using (`go version`)?

<pre>
$ go version
latest (playground)
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
playground
</pre></details>

### What did you do?

Unmarshal  json (https://play.golang.org/p/Ka8kdddUHKu):

	s := struct{
		Val int `json:",string,omitempty"`
	}{}
	
	println(json.Unmarshal([]byte(`{"val":""}`), &s))

### What did you expect to see?

Since val is `""`, the error as such  is expected, however I  would expect the `omitempty` to make a  difference and hence return `nil` error. According to https://golang.org/pkg/encoding/json/:

> The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string.

### What did you see instead?

Error: invalid use of ,string struct tag, trying to unmarshal "" into int

### Reasoning

To give flexibility in handling external json input it is preferable to  handle the `omitempty` tag before handling further validations like `string`. In this case the order seems to be different.

If effect, `,string,omitempty` should allow `""` to be unmarshaled into numeric zero values.

**UPDATE** I realize this might indeed be more a proposal as `omitempty`  seems to be documented and take effect only for marshaling but not unmarshaling.

**Comment by andybons** [comment]
@andig if you’d like this to be a proposal, could you update the first comment and subject accordingly? See https://golang.org/s/proposal for more info. Thanks!

**Comment by andig** [comment]
Closing this one. I feel the scope I'm asking about is much too narrow for a proper proposal. A proposal if any should consider a wider range of encoding (and potentially decoding) issues.
