### ISSUE TITLE
os.RemoveAll Bug?

### ISSUE THREAD

**Issue by xywf221** [golang/go#41747]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\Administrator\GoLandProjects\rim-mod\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build420660114=/tmp/go-build -gno-record-gcc-switches
GOROOT/bin/go version: go version go1.15 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.15
</pre></details>

### What did you do?

I tried to delete the folder, but the program crashed and exited。

```go
package main

import (
	"fmt"
	"os"
)

func main() {
	os.RemoveAll("E:/test/a")
	fmt.Println("safe exit")
}
```
E:/test/a is here 
[2012631342_ultra_vanilla_theme.zip](https://github.com/golang/go/files/5316028/2012631342_ultra_vanilla_theme.zip)
this is game mods , unzip in a folder with permissions . run code 

### What did you expect to see?
output safe exit

### What did you see instead?
program crashed and exited。

**Comment by davecheney** [comment]
> program crashed and exited。

Can you please provide the _entire_ crash output, as text, if possible.

**Comment by xywf221** [comment]
> > program crashed and exited。
> 
> Can you please provide the _entire_ crash output, as text, if possible.

He just collapsed, but there was no output, as if it had suddenly died

**Comment by davecheney** [comment]
Are you sure this was a problem with the Go program you wrote and not your antivirus software?

**Comment by xywf221** [comment]
> Are you sure this was a problem with the Go program you wrote and not your antivirus software?

I don't install antivirus  software, but you remind me that it may be my problem
