### ISSUE TITLE
x/tools/gopls: format of workspace/didChangeConfiguration parameters?

### ISSUE THREAD

**Issue by ilohmar** [golang/go#41767]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/il/.cache/go-build"
GOENV="/home/il/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/il/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/il/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build462115165=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Send a workspace/didChangeConfiguration request, with any of various parameters: `usePlaceholders`, `gofumpt`, `completeUnimported` etc.

I am working on the integration and configuration from Emacs' `eglot.el`, and my problem is that most configuration is described in terms of VS Code --- so it is specific to one editor, something that, ironically, LSP was supposed to get rid of... ;)

I am looking for a description of the actual settings parameter for the request.  Here is an *example* for a specific parameter:
```
[client-notification] Sat Oct  3 14:23:15 2020:
(:jsonrpc "2.0" :method "workspace/didChangeConfiguration" :params
          (:settings
           (:gopls
            (:gofumpt t))))
```
The format looks alien, but the settings parameter would transmit as
```
{
  "gopls": {
    "gofumpt": true
  }
}
```
which looks fine to me.  The request does not trigger any error.

### What did you expect to see?

A change in behavior.

### What did you see instead?

No change in behavior -- neither any formatting according to the stricter gofumpt rules, nor a behavior in completion items (cannot disable completion of unimported symbols) etc.

I tried to rule out all Emacs/eglot-specific error sources as best I could.  I also tried to check the wider-spread alternative `lsp-mode` handling as well as the gopls source itself, but could not find what I was looking for --- pointers appreciated.

gopls works fine with eglot out of the box, it is just the config changes that elude me.  Thanks for any help!

**Comment by stamblerre** [comment]
The `didChangeConfiguration` message should contain just this `{ "gofumpt": true }` part, not the `"gopls"` part--I think that should fix the issue.

**Comment by ilohmar** [comment]
Thanks for your reply.  I will try to make good use of this info for the Emacs/eglot integration, as soon as I find the time...

**Comment by stamblerre** [comment]
Currently, `gopls` doesn't actually read the content in the `didChangeConfiguration`, but rather just re-requests the `workspace/configuration`. We should probably change it to read the altered settings, but it should still work with the client either way.
