### ISSUE TITLE
playground: unable to use methods from errors package

### ISSUE THREAD

**Issue by bynov** [golang/go#41789]
### What version of Go are you using (`go version`)?

<pre>
Current go playground version - 1.14.8
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
Go playground

</pre></details>

### What did you do?

I've tried to use `errors.Wrap`, `errors.As`, `errors.Is` methods in playground but it seems like it doesn't work at all. Link: [https://play.golang.org/p/G12jcrJOrts](https://play.golang.org/p/G12jcrJOrts)

### What did you expect to see?

I've expected `errors.*` methods to work

### What did you see instead?

It's not working :(

**Comment by seankhliao** [comment]
`errors.Wrap` is not defined for the stdlib: https://golang.org/pkg/errors/
perhaps you were thinking of the third part package? https://godoc.org/github.com/pkg/errors#Wrap

**Comment by bynov** [comment]
> `errors.Wrap` is not defined for the stdlib: https://golang.org/pkg/errors/
> perhaps you were thinking of the third part package? https://godoc.org/github.com/pkg/errors#Wrap

Oops, I've missed it. Thanks for explanation, we can close that issue (:
