### ISSUE TITLE
I cannot play Go tour with korean language. And issues are not answered at kr page(https://github.com/atomaths/go-tour-kr/issues/4)

### ISSUE THREAD

**Issue by beurre369** [golang/go#41786]
### What version of Go are you using (`go version`)?
On web

### What did you do?
at the tour of go( https://tour.golang.org/welcome/2 ), I clicked the '한국어' button.

### What did you expect to see?
Tour of Go with korean

### What did you see instead?
Go 1.9 is no longer available. Please refer to https://goo.gl/aESk5L for more information.

**Comment by ALTree** [comment]
In addition to being currently offline, that korean translation was also quite outdated (last re-deployment was ~6 years ago). There's a new up-to-date translation at https://go-tour-ko.appspot.com.

Also see https://github.com/golang/tour/issues/1027.

**Comment by beurre369** [comment]
Thank you!!!
​
-----Original Message-----

**Comment by dmitshur** [comment]
Closing as duplicate of golang/tour#1027.
