### ISSUE TITLE
x/net/http2: 

### ISSUE THREAD

**Issue by magicalo** [golang/go#41784]
### What version of Go are you using (`go version`)?

<pre>
$go version 
go1.15.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
linux/amd64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/larry/.cache/go-build"
GOENV="/home/larry/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/vinny/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/larry/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build920193825=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Simple TLS server that serves files.
curl --http1.1 --insecure -v -i https://Larry-UbuntuP0:8443/myfile.txt
works perfect.
curl --insecure -v -i https://Larry-UbuntuP0:8443/myfile.txt
consistently returns 
* HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
* stopped the pause stream!
* Connection #0 to host Larry-UbuntuP0 left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

Create a simple TLS server using defaults.  Serve up some file content.
Run the curl commands shown.

### What did you expect to see
File contents returned like HTTP 1.1 does

### What did you see instead?
Error shown above.

**Comment by davecheney** [comment]
@magicalo before we can investigate we need you to provide some sample code that demonstrates the issue. Thank you

**Comment by ivanjaros** [comment]
can you even run http2 as insecure? isn't http2 inherently tls?

**Comment by seankhliao** [comment]
> can you even run http2 as insecure? isn't http2 inherently tls?

@ivanjaros not by default, but with h2c

**Comment by networkimprov** [comment]
@gopherbot add WaitingForInfo
