### ISSUE TITLE
cmd/go2go: Embedded type list type checking is confusing

### ISSUE THREAD

**Issue by joiky** [golang/go#41783]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?

n/a

### What operating system and processor architecture are you using (`go env`)?

+ go2go playground

### What did you do?

It's puzzling

[https://go2goplay.golang.org/p/kAXN5YfIUod](https://go2goplay.golang.org/p/kAXN5YfIUod)

### What did you expect to see?

+ Successful compilation
<pre>
int
string
int
</pre>

+ OR failed compilation

### What did you see instead?

<pre>
int
Unknown
Unknown
</pre>

**Comment by ianlancetaylor** [comment]
Thanks.  This is discussed in the design draft at https://go.googlesource.com/proposal/+/refs/heads/master/design/go2draft-type-parameters.md#identifying-the-matched-predeclared-type .

We considered permitting switching on T, but it wasn't clear that it was what people wanted.  See the discussion at https://groups.google.com/d/msg/golang-nuts/iAD0NBz3DYw/VcXSK55XAwAJ (it is mixed in with other discussion in that thread).
