### ISSUE TITLE
How to add modern e2k processor architecture?

### ISSUE THREAD

**Issue by kolkov** [golang/go#41794]
Hi! MCST produces its own microprocessors based on the perspective e2k architecture, how can we add support for this architecture to the Golang?

Thanks!

http://mcst.ru
http://mcst.ru/programmnoe-obespechenie-elbrus 
https://en.wikipedia.org/wiki/Elbrus_2000#:~:text=The%20Elbrus%202000%2C%20E2K%20(Russian,instruction%20set%20architectures%20(ISA)%3A

**Comment by ianlancetaylor** [comment]
See https://golang.org/wiki/PortingPolicy.

In general we do not use the issue tracker for questions.  You will get better and faster answers if you use a forum.  See https://golang.org/wiki/Questions.  Thanks.
