### ISSUE TITLE
x/build/dashboard: only run linux-386-387 builder on Go 1.15 and older

### ISSUE THREAD

**Issue by dmitshur** [golang/go#41799]
The linux-386-387 builder has started to fail since [CL 258957](https://golang.org/cl/258957).

Support for GO386=387 is being dropped in Go 1.16, so the builder can be deleted.

**Edit:** It shouldn't be outright deleted, it should provide coverage for Go 1.15 and 1.14 where it's still supported. Thank you @bcmills for spotting this.

/cc @cagedmantis @toothrot @randall77

**Comment by randall77** [comment]
Is this just https://go-review.googlesource.com/c/go/+/257963/ , or is there more to do?

**Comment by dmitshur** [comment]
@randall77 It's also [CL 259449](https://golang.org/cl/259449).
