### ISSUE TITLE
x/pkgsite: change GetNestedModules to return nested modules for series

### ISSUE THREAD

**Issue by julieqiu** [golang/go#41802]
At the moment, [GetNestedModules](https://github.com/golang/pkgsite/blob/5ab64318efa0a62169c2dcaf2088631fa179cad8/internal/postgres/details.go#L24) figures out which nested modules to return using the module_path. However, this means that modules will not be returned when the major version is v2 or higher. 

For example, `GetNestedModules(ctx, "golang.org/x/tools/v2")` will not return `golang.org/x/tools/gopls` and it should.

**Comment by trongbq** [comment]
@julieqiu I will work on this one.

**Comment by julieqiu** [comment]
Thanks, @trongbq!
