### ISSUE TITLE
low stdout performance with many writes

### ISSUE THREAD

**Issue by ivanjaros** [golang/go#41808]
I was watching one of Jonathan Blow's videos on youtube where he mentioned how slow the CLI became over the years and how printing a dumb text on the screen is slower than rendering 60 frames of AAA game(not his words). And that resonated with me because I have observed this behavior myself many times now when I have a ton of writes into stdout the cli is just incredibly slow/laggy so I usually avoid it. I think this is because there is some kind of slow buffer in the background that batches the writes and somehow makes stdout slow or, most likely, it is a rendering issue. So I was wondering if this could be "fixed" in Go somehow or if this is a OS issue where the OS makes the CLI slow? If so, I was wondering if we could use some kind of simple built-in 2d/3d engine to render the console ourselves instead of the OS provided CLI?

**Comment by ALTree** [comment]
Definitely an issue on the CLI-side of things. Some terminal emulators are in fact so slow that piping commands with a lot of output to /dev/null will speed up the command. Not something that can be fixed on the programming language side.

**Comment by ivanjaros** [comment]
it's quite sad that we just accept this as being normal. seems that OS devs are slacking off. ah well...
