### ISSUE TITLE
x/pkgsite: please exclude play-with-go.dev/... and gopher.live/... from pkg.go.dev indexing

### ISSUE THREAD

**Issue by myitcv** [golang/go#41814]
### What is the URL of the page with the issue?

https://pkg.go.dev/search?q=gopher.live

### What is your user agent?

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.59 Safari/537.36
</pre>

### Screenshot

n/a

### What did you do?

Visited https://pkg.go.dev/search?q=gopher.live

### What did you expect to see?

No results

### What did you see instead?

Lots of results.

Modules play-with-go.dev/... and gopher.live/... are essentially throw-away.

I can demonstrate my ownership of these domains as required.

cc @julieqiu

**Comment by jba** [comment]
We've excluded those two prefixes from direct access, but they will still appear in search. #41817.

**Comment by myitcv** [comment]
Thank you. Looks like we should close this issue now and I can follow #41817 ?

**Comment by julieqiu** [comment]
Yup!
