### ISSUE TITLE
x/crypto/ssh: KeyboardInteractiveChallenge error message is incorrect

### ISSUE THREAD

**Issue by packrat386** [golang/go#41823]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.15.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

I haven't checked, but the error message is the same on the master branch.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/acoyle/.cache/go-build"
GOENV="/home/acoyle/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/acoyle/go/pkg/mod"
GOOS="linux"
GOPATH="/home/acoyle/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build040277230=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

When using the [ssh.KeyboardInteractiveChallenge](https://godoc.org/golang.org/x/crypto/ssh#KeyboardInteractiveChallenge) authentication method, I returned `answers []string` that was larger in size than the the input `questions []string`. I then passed this config to [ssh.Dial](https://godoc.org/golang.org/x/crypto/ssh#Dial).

### What did you expect to see?

`ssh.Dial` should fail with an error message saying too many answers were provided for the questions asked by the challenge.

### What did you see instead?

`ssh.Dial` failed with the error message `ssh: not enough answers from keyboard-interactive callback`.

**Comment by packrat386** [comment]
This seems like it should be pretty trivial to change, and I'd be happy to submit a PR. The contribution guide said it was best to submit an issue first so I filed this as well.

**Comment by dmitshur** [comment]
Yes, filing an issue and discussing it first is very helpful, thanks.

CC @FiloSottile per [owners](https://dev.golang.org/owners).
