### ISSUE TITLE
x/build/dashboard: remove darwin-386-10_14 builder when Go 1.14 stops being supported

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#41829]
On https://golang.org/cl/259903 I asked for a darwin-386 slowbot.  I got one, but it doesn't work, presumably because the darwin/386 port has been removed (#37610).

It seems to me that asking for a darwin-386 slowbot should simply ignore the request rather than run a broken slowbot.

Thanks.

CC @dmitshur @cagedmantis

**Comment by ianlancetaylor** [comment]
Failing slowbot run: https://storage.googleapis.com/go-build-log/f8e55402/darwin-386-10_14_298c3ae5.log

**Comment by dmitshur** [comment]
Go 1.14 is still supported, and it supports the `darwin/386` port. Once it becomes unsupported (i.e., in 4~ months), we will remove the `darwin-386-10_14` builder and its [slowbot alias](https://github.com/golang/build/blob/a9f75ee9992b28221ceec0c56af51265ea857ce2/dashboard/builders.go#L47).

There is a separate enhancement idea that we can do sooner. I filed #41831 about it.

**Comment by ianlancetaylor** [comment]
OK, thanks.

**Comment by dmitshur** [comment]
Resolved in [CL 293771](https://golang.org/cl/293771).
