### ISSUE TITLE
spec: one imperfection

### ISSUE THREAD

**Issue by go101** [golang/go#41835]
The line in spec is not accurate:
```
var p = 1<<s == 1<<33         // illegal if ints are 32bits in size: 1 has type int, but 1<<33 overflows int
```

The line is always legal.

**Comment by go101** [comment]
Sorry, it looks the comment says the 2nd "1".

**Comment by go101** [comment]
There is still an imperfection: `a[1.0<<s]` will always panic. So it would be better to change the comment from
```
// 1.0 has type int; x == a[0] if ints are 32bits in size
```
to
```
// 1.0 has type int; This line compiles okay but panics at run time.
```

**Comment by ianlancetaylor** [comment]
I'm not sure any change is required here, but CC @griesemer .

**Comment by go101** [comment]
It is that `a[0]` is a non-existing element if ints are 32bits in size.

**Comment by ianlancetaylor** [comment]
Understood, I just don't think it is unclear.

**Comment by griesemer** [comment]
I agree with @ianlancetaylor - this seems clear enough.

That said, the change I'd make is declare a separate independent array, rather than using `a` that's declared on the next line. Then there's no confusion.

I will make the change as it's trivial.
