### ISSUE TITLE
x/tools/gopls: fix import organization in a multi-module workspace

### ISSUE THREAD

**Issue by stamblerre** [golang/go#41836]
Tracking issue for the work to fully support `goimports` in a multi-module workspace.
This will require tracking all `go.mod`s in a workspace in the ProcessEnv, and possibly writing the workspace module out to disk.

@heschik is working on a plan for this.

**Comment by stamblerre** [comment]
@findleyr: Can this be closed?

**Comment by findleyr** [comment]
> @findleyr: Can this be closed?

No, I just added a handle for the snapshot workspace directory. The work of hooking up imports has not been done.

**Comment by stamblerre** [comment]
Ok, thanks for clarifying. Are you planning to work on that or should @heschik do that final step?

**Comment by findleyr** [comment]
I _thought_ Heschi was going to do it, but I might be misremembering. Happy to do it if needed.

**Comment by stamblerre** [comment]
Ok sounds good--I'll leave it assigned to Heschi, just wasn't sure if you'd spoken offline.

**Comment by oldCoderException** [comment]
Hey there...  I just thought I'd add that the lack of this feature is affecting me as well.  Please see my "experience report" on the golang group at:  https://groups.google.com/g/golang-nuts/c/2Xcfb4f7ans
Requiring that any module be at the root in VSCode has had a somewhat significant impact on my development workflow.  I look forward to this being resolved.  :)  thanks guys!

**Comment by oldCoderException** [comment]
I may have commented on the wrong issue?  Should it have been https://github.com/golang/go/issues/32394?  Sorry, it's a bit confusing.
