### ISSUE TITLE
x/tools/gopls: infer workspace modules from a user-provided gopls.mod

### ISSUE THREAD

**Issue by stamblerre** [golang/go#41837]
Tracking issue for the work @findleyr has been doing on the user-provided `gopls.mod` file, which can be used to override gopls's automatically created workspace module.

The remaining tasks are:
- [ ] Do not search for workspace modules in the presence of a `gopls.mod`, and instead populate the modules map by looking at the `gopls.mod`'s requires.
- [x] Handle on-disk modifications to the `gopls.mod`
- [x] Detecting a `gopls`.mod: We should look "upwards" for a `go.mod` or a `gopls.mod`, stopping at the first `gopls.mod`. The `gopls.mod` always beats the `go.mod`.

**Comment by stamblerre** [comment]
@findleyr: Can this be closed?

**Comment by findleyr** [comment]
> @findleyr: Can this be closed?

Yep!
