### ISSUE TITLE
x/tools/gopls: merge workspace folders into a single view by default

### ISSUE THREAD

**Issue by stamblerre** [golang/go#41842]
Because `gopls` has only supported one workspace folder per view until this point, many users are used to opening multiple workspace folders. Now that `gopls` supports multi-module workspaces, we should try to prefer to make one view as much as possible. If this causes problems for the user, they will either need to disable workspace module mode or create a `gopls.mod` configuration file.

**Comment by findleyr** [comment]
We decided not to do that. Users should have the flexibility of choosing multiple workspaces or a single workspace module. The go.work proposal makes this easier.
