### ISSUE TITLE
x/pkgsite: Help remove the package github.com/viney-shih/goroutine

### ISSUE THREAD

**Issue by viney-shih** [golang/go#41844]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/viney-shih/goroutine
 
 
### What is your user agent?
 

 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

 
 
### Screenshot
 
<img width="1369" alt="goroutines_package_·_pkg_go_dev" src="https://user-images.githubusercontent.com/6994109/95304455-3966ae00-08b7-11eb-84ea-e0bf38c74f84.png">
 
 
### What did you do?
 
I am the author of pachage `goroutines`. Please help remove `https://pkg.go.dev/github.com/viney-shih/goroutine` I am going to register another package name for it.
 
 
### What did you expect to see?
 
page `https://pkg.go.dev/github.com/viney-shih/goroutine` and it's related data in DB are removed
 
### What did you see instead?

I am going to register `goroutines` but failed. I type the following command and returns as below. 

```
❯ GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/viney-shih/goroutines@v1.0.0
go: downloading github.com/viney-shih/goroutines v1.0.0
go get: github.com/viney-shih/goroutines@v1.0.0: parsing go.mod:
        module declares its path as: github.com/viney-shih/goroutine
                but was required as: github.com/viney-shih/goroutines

```

**Comment by jba** [comment]
Unfortunately our exclusion code will block `github.com/viney-shih/goroutines` if we exclude `github.com/viney-shih/goroutine` (it just looks for a prefix).

If you just change the go.mod of `github.com/viney-shih/goroutines` to have the same module path, that should fix your problem.

**Comment by viney-shih** [comment]
@jba I have got your point and fixed `go.mod` issue. 

However, I got two docs now. 
`https://pkg.go.dev/github.com/viney-shih/goroutines` and `https://pkg.go.dev/github.com/viney-shih/goroutine`

I want to keep `goroutines` version. Could you please remove `https://pkg.go.dev/github.com/viney-shih/goroutine` for me?

Thanks.

**Comment by jba** [comment]
This requires changing our exclusion logic, so it's not a simple fix. I'll start working on it shortly.

**Comment by jba** [comment]
Done.
