### ISSUE TITLE
x/website: widen "Download" button on /doc/install page so text doesn't wrap excessively

### ISSUE THREAD

**Issue by stevetraut** [golang/go#41856]
This is an issue requesting a change to documentation.

In the download button at https://golang.org/doc/install, the button text wraps, making it a little harder to read. Widening it a bit will give us two lines of unwrapped text for all three OSes.

Looks like changing the width value in the download class will work. It's currently 9.375rem -- it could be 16rem. 

```
.download {
  width: 16rem;
}
```

@rsc @dmitshur

**Comment by seankhliao** [comment]
can you show a screenshot? are you using font scaling? because it looks fine (single line) for

**Comment by dmitshur** [comment]
This is what https://golang.org/doc/install looks like at 100% scaling in Chrome on macOS for me:

![image](https://user-images.githubusercontent.com/1924134/95413384-44423280-08f9-11eb-845b-b6968d9fbfd9.png)

With the suggested 16rem width:

![image](https://user-images.githubusercontent.com/1924134/95413432-6936a580-08f9-11eb-8445-8d05f4a523c2.png)

Making it wider on the https://golang.org/doc/install page seems fine. We should take care that it doesn't affect other pages inadvertently (e.g., https://golang.org/dl/ also has buttons with the "download" class).

**Comment by stevetraut** [comment]
The .download width style rule on https://golang.org/dl/ appears to be superseded by the .downloadBox width, which is set to 280px. 

I suggest we change .download width to 17.5rem, which is equivalent to 280px. That will make the buttons on both pages the same width. Just in case.
