### ISSUE TITLE
x/website: update /doc/install/source page after GO386 changes

### ISSUE THREAD

**Issue by ALTree** [golang/go#41861]
The [Installing Go from source](https://tip.golang.org/doc/install/source#environment) page says (in the section dedicated to Env Variables):

> $GO386 (for 386 only, default is auto-detected if built on either 386 or amd64, 387 otherwise)
> 
> This controls the code generated by gc to use either the 387 floating-point unit (set to 387) or SSE2 instructions (set to sse2) for floating point computations.
> - GO386=387: use x87 for floating point operations; should support all x86 chips (Pentium MMX or later).
> - GO386=sse2: use SSE2 for floating point operations; has better performance than 387, but only available on Pentium 4/Opteron/Athlon 64 or later.

The section should be updated to reflect the planned 1.16 deprecation of 387, and the softfloat support.

cc @dmitshur

**Comment by dmitshur** [comment]
Thanks for spotting this @ALTree.

@randall77 Would you like to send a CL for this? The file that needs to be updated is in x/website, [here](https://github.com/golang/website/blob/687f4169bf23a4a462373f44ec4aae8716d6d20a/content/static/doc/install-source.html#L665-L676). (There's also an old copy of it in the main repo, but that needs to be deleted; I re-opened https://github.com/golang/go/issues/40496#issuecomment-705641649 for that.)

**Comment by dmitshur** [comment]
Reopening because the x/website CL was reverted in [CL 261557](https://golang.org/cl/261557). x/website needs to be modified when Go 1.16 is released. I'll move this to Go 1.17 milestone with early-in-cycle.
