### ISSUE TITLE
x/tools/gopls: set up extended regtest CI

### ISSUE THREAD

**Issue by findleyr** [golang/go#41865]
In https://golang.org/cl/259137, I configured the regtests to only run in 'singleton' mode by default (communicating with the server via stdin/stdout).

This change was made because also running in 'forwarded' mode provides only fractionally more test coverage, and causes the tests to run more than 2x longer. Particularly on Darwin and Android builders, the regtests have gotten quite slow.

By running in parallel on Linux, the regtests can be made to run in <10s.  We should set up extended CI (using Kokoro) to run the regtests in forwarded mode, and possibly even more modes: run with a separate daemon process, run with all experiments enabled, run in a nested module, etc.

This would achieve coverage of various execution modes without slowing down the builders.

CC @stamblerre

**Comment by bcmills** [comment]
Would it make sense to condition the additional modes on `!testing.Short()` rather than a separate Kokoro workflow?

That way the Go project's `longtest` builders could provide coverage for them.

**Comment by stamblerre** [comment]
As part of this, we could possibly also run `staticcheck` and various other linters in Kokoro.

**Comment by findleyr** [comment]
This was done a long time ago.
