### ISSUE TITLE
gollvm: 

### ISSUE THREAD

**Issue by advancedwebdeveloper** [golang/go#41880]
<pre>
$ go version
</pre>
go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64

<details><summary><code>go env</code> go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/oceanfish81/.cache/go-build"
GOENV="/home/oceanfish81/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/oceanfish81/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/oceanfish81/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/oceanfish81/gollvm_dist"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
AR="ar"
CC="/usr/bin/clang"
CXX="/usr/bin/clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build938164654=/tmp/go-build -gno-record-gcc-switches -funwind-tables"</summary><br><pre>
$ go env

</pre></details>

I was trying to build [wl](https://github.com/dkolbly/wl) project, using my ["release"](https://drive.google.com/file/d/1n7vV2GPG09oftZj7jWceH3o23A5VOaYG/view?usp=sharing) build of gollvm.

> ~/golang_projects/wl/ui/examples/img$ go run image.go
> /tmp/go-build853824791/b001/exe/image: symbol lookup error: /lib/libgo.so.12git: undefined symbol: main.main
> exit status 127
> 
> ~/golang_projects/wl/ui/examples/img$ file /lib/libgo.so.12git
> /lib/libgo.so.12git: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, with debug_info, not stripped
> 
> ~/golang_projects/wl/ui/examples/img$ go run img.go
> # command-line-arguments
> ./img.go:39:14: error: reference to undefined name 'ImageFromFile'

Running a pre-compiled executable lad to this:

> ~/go/bin/img ~/go/src/github.com/dkolbly/wl/ui/examples/img/bsd_daemon.jpg
> Connect to Wayland server failed dial unix /run/user/1000/wayland-0: connect: no such file or directory
. This is some sort of misconfiguration, on Ubuntu 20.04, related to [Wayland](https://wayland.freedesktop.org/).
I will try to resolve this, to ensure that there wouldn't be any other runtime issues.

CC @dkolbly @sternix
CC @thanm @cherrymui

**Comment by ianlancetaylor** [comment]
I would not expect `go run image.go` to work, as the `main` function is in img.go.

**Comment by ianlancetaylor** [comment]
Dup of #41881.
