### ISSUE TITLE
access: Approver Access ("approvers")

### ISSUE THREAD

**Issue by mengzhuo** [golang/go#41898]
Gerrit email: mzh@golangcn.org

Approver Access ("approvers")

https://go-review.googlesource.com/#/admin/groups/1005,members

Hi, @dmitshur 

I need approver access some well test CLs takes too long to submit (i.e. https://go-review.googlesource.com/c/go/+/180757)

**Comment by cherrymui** [comment]
@mengzhuo sorry for the delay. Please ping me if a CL does not get a response for ~a week. Thanks.

**Comment by mengzhuo** [comment]
> @mengzhuo sorry for the delay. Please ping me if a CL does not get a response for ~a week. Thanks.

Hi, Cherry
I just wish that I can take the load off for you :)

**Comment by dmitshur** [comment]
Thank you for making the request @mengzhuo, we will consider it.

**Comment by benshi001** [comment]
Mengzhou has been around for a long time, and made many commits.

I think he need not two +2 votes for his future CLs, so giving him the approver access can simplify his future work.

Actually I am an approver but less use my access.

**Comment by toothrot** [comment]
You're good to go. Thanks for your contributions!
