### ISSUE TITLE
json.NewDecoder Decode not return err when input invalid

### ISSUE THREAD

**Issue by zhoujie0101** [golang/go#41899]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 darwin/amd64
</pre>

### What did you do?

<pre>
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
)

func main() {
	p := "404 not found"
	var m interface{}
	dec := json.NewDecoder(bytes.NewBuffer([]byte(p)))
	dec.UseNumber()
	err := dec.Decode(&m)
        // the err is nil
	if err != nil {
		fmt.Println(err)
	}
        // 404
	fmt.Println(m)

	err = json.Unmarshal([]byte(p), &m)
        // the err is not nil
	if err != nil {
		fmt.Println(err)
	}
        // 404
	fmt.Println(m)
}
</pre>

### What did you expect to see?
both m is 404, but the first err is nil, and the second err is "invalid character 'n' after top-level value". Maybe both should reutrn error?

**Comment by fraenkel** [comment]
see https://github.com/golang/go/issues/36225

**Comment by zhoujie0101** [comment]
> see https://github.com/golang/go/issues/36225

thanks

**Comment by mvdan** [comment]
Closing as a dup.
