### ISSUE TITLE
net/http: request.Clone doesn't deep copy TransferEncoding

### ISSUE THREAD

**Issue by dqu123** [golang/go#41907]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes, bug exists in master: https://github.com/golang/go/blob/master/src/net/http/request.go#L385

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/david/Library/Caches/go-build"
GOENV="/Users/david/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/david/cs/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5r/35kn30hd119486nmd0sjcy8c0000gn/T/go-build221526405=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

- initialize http.Request with TransferEncoding
- clone request
- modify original request TransferEncoding
https://play.golang.org/p/aSFm22u_TGZ

### What did you expect to see?
cloned request TransferEncoding should not changed by changes to the original request after it has been copied.

### What did you see instead?
cloned request TransferEncoding was modified by changing original request TransferEncoding

**Comment by odeke-em** [comment]
Thank you for catching this @dqu123 and welcome to the Go project! Good eyes.

@gopherbot please backport this issue.
