### ISSUE TITLE
Freeze functions for package-level collections

### ISSUE THREAD

**Issue by mcandre** [golang/go#41904]
Please provide standard functions for generating immutable collections, including slices and hashmaps, safe for use as package-level members.

I think it is too late to require pointers in order to modify collections, at least within Go 1.x. We may have to superimpose a freeze() function returning an immutable, potentially type-distinct, flavor of collections.

Rust has this. Ruby has this. Haskell has this. Clojure has this. Python has third party libraries for this.

C/C++ probably require wrapper functions, meaning that developers can easily expose mutable collections without intending to.

**Comment by go101** [comment]
Do you mean https://github.com/golang/go/issues/6386?

**Comment by mvdan** [comment]
Duplicate, and also closing as per https://github.com/golang/go/issues/41739#issuecomment-703303783.
