### ISSUE TITLE
net/rpc: Client.Go allocates a buffered channel with large capacity (10) instead of small (1) when done is nil

### ISSUE THREAD

**Issue by furthergo** [golang/go#41901]
### What version of Go are you using (`go version`)?
<pre>
 go1.15 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes (go1.15)
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOOS="darwin"
GOPATH="~/go"
GOROOT="/usr/local/Cellar/go/1.15/libexec"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you do?
```golang
// net/rpc/client.go

// Go invokes the function asynchronously. It returns the Call structure representing
// the invocation. The done channel will signal when the call is complete by returning
// the same Call object. If done is nil, Go will allocate a new channel.
// If non-nil, done must be buffered or Go will deliberately crash.
func (client *Client) Go(serviceMethod string, args interface{}, reply interface{}, done chan *Call) *Call {
	call := new(Call)
	call.ServiceMethod = serviceMethod
	call.Args = args
	call.Reply = reply
	if done == nil {
		done = make(chan *Call, 10) // buffered.
	} else {
		// If caller passes done != nil, it must arrange that
		// done has enough buffer for the number of simultaneous
		// RPCs that will be using that channel. If the channel
		// is totally unbuffered, it's best not to run at all.
		if cap(done) == 0 {
			log.Panic("rpc: done channel is unbuffered")
		}
	}
	call.Done = done
	client.send(call)
	return call
}
```
In the function `func (client *Client) Go(serviceMethod string, args interface{}, reply interface{}, done chan *Call) *Call`, when caller passes `done == nil`, Go will **allocate a new channel with buffer 10**,  which used to notify current Call is finished. 

### What did you expect to see?
It's enough to create a channel with capacity 1
```golang
if done == nil {
    done = make(chan *Call, 1)  // buffered
}
```

### What did you see instead?
```golang
if done == nil {
    done = make(chan *Call, 10) // buffered.
}
```

**Comment by dmitshur** [comment]
If this is a question, please see https://golang.org/wiki/Questions.

If this is a bug, please fill in the questions in the issue template.

**Comment by furthergo** [comment]
Updated

**Comment by furthergo** [comment]
> If this is a question, please see https://golang.org/wiki/Questions.
> 
> If this is a bug, please fill in the questions in the issue template.

Updated

**Comment by dmitshur** [comment]
Thanks for filling in the template.

Please be aware that package `net/rpc` is frozen and not accepting new features.

I don't believe there's an issue here. Capacity 1 is enough for when the frequency of requests is very small. But it will not be enough if there are many requests happening in a short amount of time. The user can always supply a custom non-nil done channel with their desired capacity, but 10 seems like a reasonable default otherwise.

Also note the comment in the snippet you included:

```
// If caller passes done != nil, it must arrange that
// done has enough buffer for the number of simultaneous
// RPCs that will be using that channel. If the channel
// is totally unbuffered, it's best not to run at all.
```

So I'll close as this is working as intended and there's no issue here.

CC @robpike per [owners](https://dev.golang.org/owners).
