### ISSUE TITLE
x/tools/gopls: errors.As warning for no apparent reason

### ISSUE THREAD

**Issue by pofl** [golang/go#41903]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pofl/.cache/go-build"
GOENV="/home/pofl/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/pofl/Documents/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pofl/Documents/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/linuxbrew/.linuxbrew/Cellar/go/1.15.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/linuxbrew/.linuxbrew/Cellar/go/1.15.2/libexec/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc-5"
CXX="g++-5"
CGO_ENABLED="1"
GOMOD="/home/pofl/dwh-kafka2pubsub/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build040311524=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

![image](https://user-images.githubusercontent.com/14232537/95657798-bb084700-0b16-11eb-8ad4-3056c0077e57.png)

### What did you expect to see?

no complaints

### What did you see instead?

warning "second argument to errors.As must be a non-nil pointer to either a type that implements error, or to any interface type"

**Comment by stamblerre** [comment]
I believe what you want here is `errors.As(err, e)`, since `*connErr` implements error, and the second argument must be a pointer to a type that implements error.

**Comment by stamblerre** [comment]
Mistyped in the earlier response--I meant `errors.As(err, &e)`.

**Comment by pofl** [comment]
You're right. Damn, go is so quirky sometimes.
