### ISSUE TITLE
dev.go2go: please rebase against master or at least 1.15.

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#41909]
I used to manually rebase it but the changes are a bit too much atm.

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by griesemer** [comment]
As this is a prototype and we wanted to keep a clean history of changes, in the past I have simply rebased the entire sequence of commits on top of master, and then rewritten the history in the repo.

Is this still acceptable?

**Comment by OneOfOne** [comment]
@griesemer  Yep that would be perfect.

**Comment by griesemer** [comment]
Just FYI: This may happen as needed; but it's not urgent as this branch is just a prototype.
