### ISSUE TITLE
x/pkgsite: ASCII graphics on pkg.go.dev looks worse than on godoc.org

### ISSUE THREAD

**Issue by amlinux** [golang/go#41919]
### What is the URL of the page with the issue?

https://pkg.go.dev/google.golang.org/protobuf/reflect/protoreflect
 
 
### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
  
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/449322/95672448-2f87c800-0ba1-11eb-8aa4-5c5d70022546.png)

 
### What did you expect to see?

Diagrams formatted with a fixed-width font, like on godoc.org. 
 
 
### What did you see instead?

Boxes don't look like boxes.

**Comment by jba** [comment]
cc @jamalc @AceroM

**Comment by jamalc** [comment]
Done.
