### ISSUE TITLE
cmd/link: collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by felipeweb** [golang/go#41915]
Please file a new issue at golang.org/issue/new using this template:

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.2 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/felipeweb/go/bin"
GOCACHE="/home/felipeweb/.cache/go-build"
GOENV="/home/felipeweb/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/felipeweb/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/felipeweb/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/linuxbrew/.linuxbrew/Cellar/go/1.15.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/linuxbrew/.linuxbrew/Cellar/go/1.15.2/libexec/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc-5"
CXX="g++-5"
CGO_ENABLED="1"
GOMOD="/home/felipeweb/projects/getupcloud/undistro/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build303208127=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.15.2 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.15.2
uname -sr: Linux 5.4.0-1024-gcp
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.31-0ubuntu9) stable release version 2.31.
</pre></details>

### What did you do?

make test on https://github.com/kubernetes-sigs/cluster-api

### Additional context

This error began after I upgrade the version of k8s modules from v0.18.9 to v0.19.2

we just exclude tests for now https://github.com/kubernetes-sigs/cluster-api/commit/2fb95900850630b6594172cd8afcda1aebd37eca#diff-bebcf249b0c23c2726a5a915ea21a6932d2a09e9c6cc2e828cc760c919f557d5R442

### What did you expect to see?

go test exited with code 0

### What did you see instead?

```
# github.com/getupio-undistro/undistro/client/cluster.test
/home/linuxbrew/.linuxbrew/Cellar/go/1.15.2/libexec/pkg/tool/linux_amd64/link: running gcc-5 failed: exit status 1
collect2: error: ld returned 1 exit status

FAIL    github.com/getupio-undistro/undistro/client/cluster [build failed]
```

**Comment by dmitshur** [comment]
Please provide more information about how to reproduce the error. "go test ./..." is not enough information. What repository did you run that in?

**Comment by ianlancetaylor** [comment]
Also note that gcc-5 is quite old.  The current version is gcc-10.

**Comment by felipeweb** [comment]
Sorry for that! information updated.

**Comment by dmitshur** [comment]
From your report, the error happens when testing the `github.com/getupio-undistro/undistro/client/cluster` package, but that package doesn't appear to be available publicly.

Is it possible to reduce this to a smaller reproducible sample? That would help with the investigation. Thanks.

**Comment by felipeweb** [comment]
Yes, the undistro package is private, but  the part that are failing is
just a small copy of cluster-api's cluster package

**Comment by felipeweb** [comment]
closing because old gcc seems to be the cause
