### ISSUE TITLE
syscall/Stat: hang on 3hours with many goroutine stat nfs path

### ISSUE THREAD

**Issue by mzyfree** [golang/go#41929]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.8 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Not yet try to reproduce on latest release

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build323519428=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
write a go binary command which starts 100 goroutine to fstat 100 different nfs client mount path when nfs server is down.
nfs mount options(vers=4.1,rsize=1048576,wsize=1048576,namlen=255,soft,proto=tcp,timeo=600,retrans=2,sec=sys)

### What did you expect to see?
total command run time should be 3min with the mount option(timeo=600,retrans=2)

### What did you see instead?
total command run time is 3hour30min with the mount option(timeo=600,retrans=2)

### Anything else
strace log
[strace-log](https://github.com/mzyfree/tugger/blob/master/test/mzy.out)
fstat nfs path log
[fstat-log](https://github.com/mzyfree/tugger/blob/master/test/mzy-debug.stat)

**Comment by rsc** [comment]
Have you tried the same with a threaded C program?
