### ISSUE TITLE
x/pkgsite: remove github.com/becle/api_gen package

### ISSUE THREAD

**Issue by becle** [golang/go#41927]
### What is the URL of the page with the issue?

pls remove this page.
 https://pkg.go.dev/mod/github.com/becle/api_gen/
 
 
### What is your user agent?
 

 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
 
 
### Screenshot
 

 
<img width="1166" alt="スクリーンショット 2020-10-12 16 55 31" src="https://user-images.githubusercontent.com/5004670/95720152-d0fb4080-0cab-11eb-8fd3-ca13b5629ae6.png">

 
 
### What did you expect to see?
 
 pls remove this page.
 https://pkg.go.dev/mod/github.com/becle/api_gen/

**Comment by ALTree** [comment]
cc @julieqiu @jba

**Comment by jba** [comment]
Done.
