### ISSUE TITLE
gollvm: go tool: no such tool "pprof"

### ISSUE THREAD

**Issue by advancedwebdeveloper** [golang/go#41921]
Hi.
Got this:
> $ go tool -n pprof
> go tool: no such tool "pprof"
.
What should I install, to support this, for gollvm?

CC @thanm @cherrymui @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Neither gccgo nor GoLLVM currently support the pprof tool.

**Comment by advancedwebdeveloper** [comment]
And what is missing, for such a support scenario?

**Comment by thanm** [comment]
Keep in mind that you are free to use upstream pprof in such situations.

**Comment by ianlancetaylor** [comment]
Somebody would need to copy the pprof code from the gc toolchain to the gofrontend toolchain, and arrange to build it as part of gotools.  I don't think there would be any major problems doing that.  As @thanm says the program would be essentially the same.

**Comment by advancedwebdeveloper** [comment]
I will try to digg into it, soon
