### ISSUE TITLE
Failed in running Install/Update Tools

### ISSUE THREAD

**Issue by renyuan-gu** [golang/go#41946]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\renyuan.gu\AppData\Local\go-build
set GOENV=C:\Users\renyuan.gu\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\renyuan.gu\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\renyuan.gu\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\renyuan.gu\AppData\Local\Temp\go-build233076810=/tmp/go-build -gno-record-gcc-switches
map=C:\Users\renyuan.gu\AppData\Local\Temp\go-build817582666=/tmp/go-build -gno-record-gcc-switches
GOROOT/bin/go version: go version go1.15.2 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.15.2
</pre></details>

### What did you do?
Firstly I thought this probably a problem with proxy server, but even I put username and PW in global config file, it did not work well.

### What did you expect to see?
tools succeed to install

### What did you see instead?
Installing github.com/mdempsky/gocode FAILED

1 tools failed to install.

this is an example, actually all 17 tools failed to install.

**Comment by ALTree** [comment]
Please provide clear reproduction steps. You'll need to include the exact sequence of commands you were running when you saw the error, and the exact output you received.

**Comment by renyuan-gu** [comment]
Steps to Reproduce:

1. Installation of latest released go (1.15.2 windows/amd64)
2. Installation of Go extension in VSCode, v0.17.2
3. add GOPATH info in setting.json
  {
        ......
       "go.gopath": "%USERPROFILE%/go"
}
4. Ctrl-Shift-P
5. Go: Install/Update Tools

Output:
Tools environment: GOPATH=%USERPROFILE%/go
Installing 17 tools at %USERPROFILE%\go\bin in module mode.
  gocode
  gopkgs
  go-outline
  go-symbols
  guru
  gorename
  gotests
  gomodifytags
  impl
  fillstruct
  goplay
  godoctor
  dlv
  gocode-gomod
  godef
  goreturns
  golint

Installing github.com/mdempsky/gocode FAILED
Installing github.com/uudashr/gopkgs/v2/cmd/gopkgs FAILED
Installing github.com/ramya-rao-a/go-outline FAILED
Installing github.com/acroca/go-symbols FAILED
Installing golang.org/x/tools/cmd/guru FAILED
Installing golang.org/x/tools/cmd/gorename FAILED
Installing github.com/cweill/gotests/... FAILED
Installing github.com/fatih/gomodifytags FAILED
Installing github.com/josharian/impl FAILED
Installing github.com/davidrjenni/reftools/cmd/fillstruct FAILED
Installing github.com/haya14busa/goplay/cmd/goplay FAILED
Installing github.com/godoctor/godoctor FAILED
Installing github.com/go-delve/delve/cmd/dlv FAILED
Installing github.com/stamblerre/gocode FAILED
Installing github.com/rogpeppe/godef FAILED
Installing github.com/sqs/goreturns FAILED
Installing golang.org/x/lint/golint FAILED

17 tools failed to install.

gocode: failed to install gocode(github.com/mdempsky/gocode): Error: Command failed: c:\go\bin\go.exe get -v github.com/mdempsky/gocode
go: GOPATH entry is relative; must be absolute path: "%USERPROFILE%/go".
For more details see: 'go help gopath'
 undefined  
gopkgs: failed to install gopkgs(github.com/uudashr/gopkgs/v2/cmd/gopkgs): Error: Command failed: c:\go\bin\go.exe get -v github.com/uudashr/gopkgs/v2/cmd/gopkgs
go: GOPATH entry is relative; must be absolute path: "%USERPROFILE%/go".
For more details see: 'go help gopath'
 undefined  
go-outline: failed to install go-outline(github.com/ramya-rao-a/go-outline): Error: Command failed: c:\go\bin\go.exe get -v github.com/ramya-rao-a/go-outline
go: GOPATH entry is relative; must be absolute path: "%USERPROFILE%/go".
For more details see: 'go help gopath'
 undefined  
go-symbols: failed to install go-symbols(github.com/acroca/go-symbols): Error: Command failed: c:\go\bin\go.exe get -v github.com/acroca/go-symbols
go: GOPATH entry is relative; must be absolute path: "%USERPROFILE%/go".
For more details see: 'go help gopath'
 undefined  
guru: failed to install guru(golang.org/x/tools/cmd/guru): Error: Command failed: c:\go\bin\go.exe get -v golang.org/x/tools/cmd/guru
go: GOPATH entry is relative; must be absolute path: "%USERPROFILE%/go".
For more details see: 'go help gopath'
 undefined  
gorename: failed to install gorename(golang.org/x/tools/cmd/gorename): Error: Command failed: c:\go\bin\go.exe get -v golang.org/x/tools/cmd/gorename
go: GOPATH entry is relative; must be absolute path: "%USERPROFILE%/go".
For more details see: 'go help gopath'
 undefined  
gotests: failed to install gotests(github.com/cweill/gotests/...): Error: Command failed: c:\go\bin\go.exe get -v github.com/cweill/gotests/...
go: GOPATH entry is relative; must be absolute path: "%USERPROFILE%/go".
For more details see: 'go help gopath'
 undefined  
gomodifytags: failed to install gomodifytags(github.com/fatih/gomodifytags): Error: Command failed: c:\go\bin\go.exe get -v github.com/fatih/gomodifytags
go: GOPATH entry is relative; must be absolute path: "%USERPROFILE%/go".
For more details see: 'go help gopath'
 undefined  
impl: failed to install impl(github.com/josharian/impl): Error: Command failed: c:\go\bin\go.exe get -v github.com/josharian/impl
go: GOPATH entry is relative; must be absolute path: "%USERPROFILE%/go".
For more details see: 'go help gopath'
 undefined  
fillstruct: failed to install fillstruct(github.com/davidrjenni/reftools/cmd/fillstruct): Error: Command failed: c:\go\bin\go.exe get -v github.com/davidrjenni/reftools/cmd/fillstruct
go: GOPATH entry is relative; must be absolute path: "%USERPROFILE%/go".
For more details see: 'go help gopath'
 undefined  
goplay: failed to install goplay(github.com/haya14busa/goplay/cmd/goplay): Error: Command failed: c:\go\bin\go.exe get -v github.com/haya14busa/goplay/cmd/goplay
go: GOPATH entry is relative; must be absolute path: "%USERPROFILE%/go".
For more details see: 'go help gopath'
 undefined  
godoctor: failed to install godoctor(github.com/godoctor/godoctor): Error: Command failed: c:\go\bin\go.exe get -v github.com/godoctor/godoctor
go: GOPATH entry is relative; must be absolute path: "%USERPROFILE%/go".
For more details see: 'go help gopath'
 undefined  
dlv: failed to install dlv(github.com/go-delve/delve/cmd/dlv): Error: Command failed: c:\go\bin\go.exe get -v github.com/go-delve/delve/cmd/dlv
go: GOPATH entry is relative; must be absolute path: "%USERPROFILE%/go".
For more details see: 'go help gopath'
 undefined  
gocode-gomod: failed to install gocode-gomod(github.com/stamblerre/gocode): Error: Command failed: c:\go\bin\go.exe get -v -d github.com/stamblerre/gocode
go: GOPATH entry is relative; must be absolute path: "%USERPROFILE%/go".
For more details see: 'go help gopath'
 undefined  
godef: failed to install godef(github.com/rogpeppe/godef): Error: Command failed: c:\go\bin\go.exe get -v github.com/rogpeppe/godef
go: GOPATH entry is relative; must be absolute path: "%USERPROFILE%/go".
For more details see: 'go help gopath'
 undefined  
goreturns: failed to install goreturns(github.com/sqs/goreturns): Error: Command failed: c:\go\bin\go.exe get -v github.com/sqs/goreturns
go: GOPATH entry is relative; must be absolute path: "%USERPROFILE%/go".
For more details see: 'go help gopath'
 undefined  
golint: failed to install golint(golang.org/x/lint/golint): Error: Command failed: c:\go\bin\go.exe get -v golang.org/x/lint/golint
go: GOPATH entry is relative; must be absolute path: "%USERPROFILE%/go".
For more details see: 'go help gopath'
 undefined

**Comment by renyuan-gu** [comment]
Problem solved, it's all in setting.json, thank you

**Comment by ALTree** [comment]
Nice, thanks for the follow up.
