### ISSUE TITLE
crypto/x509: IsEncryptedPEMBlock returns false on valid encrypted keys. ParseRawPrivateKeyWithPassphrase fails on PKCS8 format encrypted key.

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [golang/go#41949]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/harikrishnanbalagopal/Library/Caches/go-build"
GOENV="/Users/harikrishnanbalagopal/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/harikrishnanbalagopal/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/harikrishnanbalagopal/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/harikrishnanbalagopal/go/src/github.com/konveyor/testkey/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/09/5yjxv27n6njfskvvmkv9v8m40000gn/T/go-build525969776=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.15.2 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.15.2
uname -v: Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021
lldb --version: lldb-1103.0.22.10
Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
</pre></details>

### What did you do?
Example with the command to use to generate the keys and the keys themselves:
https://play.golang.org/p/F2nUIO_S6hT

Called `x509.IsEncryptedPEMBlock` on `pem.Block`s created using `pem.Decode`.
`pem.Decode` is called on valid encrypted RSA private keys generated using the following commands:
`ssh-keygen -m PEM -t rsa -b 4096 -C 'foobar@example.com'`
`ssh-keygen -m PKCS8 -t rsa -b 4096 -C 'foobar@example.com'`
`ssh-keygen -m RFC4716 -t rsa -b 4096 -C 'foobar@example.com'`

Also called `ssh.ParseRawPrivateKeyWithPassphrase` on each of those keys.

### What did you expect to see?
The `x509.IsEncryptedPEMBlock` function should report true in all the cases given in the example.
The `ssh.ParseRawPrivateKeyWithPassphrase` should succeed on the `PKCS8` key instead of failing as it does in the example.

Note that `ssh-keygen -yf mykey` is able to detect that the file is a valid encrypted key and decrypt it given the correct password in all the 3 cases. So `IsEncryptedPEMBlock` and `ParseRawPrivateKeyWithPassphrase` should be able to handle them as well.

### What did you see instead?
`x509.IsEncryptedPEMBlock` incorrectly returns false when given the `pem.Block`s of the `PKCS8` and `RFC4716` keys.

`ssh-keygen` lets you specify the format for the key file using the `-m` flag:
https://www.man7.org/linux/man-pages/man1/ssh-keygen.1.html
There are 3 supported formats: `PEM`, `PKCS8` and `RFC4716`. `x509.IsEncryptedPEMBlock` only reports correctly on keys generated using `PEM`. This is because keys generated using `PKCS8` and `RFC4716` no longer have headers that indicate that the data is encrypted and the decryption algorithm to use. `x509.IsEncryptedPEMBlock` checks for those headers in order to determine whether the data is encrypted: https://github.com/golang/go/blob/5b509d993d3a3a212b4033815be8b7b439fac672/src/crypto/x509/pem_decrypt.go#L99-L102

Interestingly the `ssh.ParseRawPrivateKeyWithPassphrase` function fails on `PKCS8` but is able to handle `RFC4716` because of this special case: https://github.com/golang/crypto/blob/master/ssh/keys.go#L1156-L1158

I have tried the example with `go version go1.15.2 darwin/amd64` and the latest `golang.org/x/crypto v0.0.0-20201012173705-84dcc777aaee` on my Macbook Pro `macOS Catalina 10.15.6`

**Comment by networkimprov** [comment]
cc @FiloSottile

**Comment by HarikrishnanBalagopal** [comment]
I wrote a small example showing how we can get the decryption algorithm info from the encrypted PEM:
https://play.golang.org/p/FOgT9XUbwBM

We can set the `DEK-Info` header using this info and then we can use https://golang.org/pkg/crypto/x509/#DecryptPEMBlock to decrypt it as usual.

**Comment by HarikrishnanBalagopal** [comment]
@FiloSottile @toothrot I just created a quick and dirty version of how it could detect and decrypt the private key:
https://github.com/HarikrishnanBalagopal/go/commit/3db571491410b67b2c026d04c8b48636fce7d2cc

One major issue is that PKCS8 format encrypted private keys use `PBKDF2` as the key derivation function:
https://tools.ietf.org/html/rfc8018#appendix-A.4

Since `PBKDF2` is an extension it can't be used to implement the std library functions.
https://pkg.go.dev/golang.org/x/crypto/pbkdf2

**Comment by FiloSottile** [comment]
`IsEncryptedPEMBlock`, `DecryptPEMBlock` and `EncryptPEMBlock` don't refer generally to any encrypted format (like PKCS#8) encoded as PEM, but specifically to RFC 1423 PEM encryption. That encryption format is legacy and broken by design, so we should deprecate it, not mix it with newer formats that encourage its use.

We can address this confusion with better docs in the deprecation message.

**Comment by HarikrishnanBalagopal** [comment]
@FiloSottile I submitted a PR to add a warning in the docs for each of those 3 functions.
I think `ParseRawPrivateKeyWithPassphrase` still needs to be fixed to handle `PKCS8` but that is on a completely different repo so I linked the PR to close the issue.

**Comment by HarikrishnanBalagopal** [comment]
@FiloSottile but what about `ssh.ParseRawPrivateKeyWithPassphrase` ?
`ssh` is an extension and should be able to support `PKCS8` encrypted private keys using https://pkg.go.dev/golang.org/x/crypto/pbkdf2
