### ISSUE TITLE
Fuck Black Lives Matter

### ISSUE THREAD

**Issue by cherryland** [golang/go#41945]
### What version of Go are you using (`go version`)?

<pre>
$ go version
Not related which is the entire point!!

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>

The summary is that you need to remove Black Lives Matters banner from the site.  
GO is not a political statement and is instead an open source project.  

</pre></details>

### What did you expect to see?

Source Code

### What did you see instead?

Racial Division promoted by the assholes Sundar Pichai, Larry Page and Sergey Brin

**Comment by fakkunamae** [comment]
Amazing, but hardly anyone in this soy milk infused """""website""""" has anything like the credability to stand up to this. Standard github proceedure is for terrified codemonkeys to roll over while the lead management pushes more social justice onto them for fear of being """"unhirable"""" by assholes that where going to replace them with an overseas department anyway.

**Comment by Rascalov** [comment]
Sir, this is a basket weaving forum.

**Comment by cherryland** [comment]
In a couple of minutes some spineless asshole will be beamed down from Google's Death Star to change the title, because it's a little bit 'too spicy' and his boss told him to do so.
