### ISSUE TITLE
wiki: add a page with a table for Go-related livestreams

### ISSUE THREAD

**Issue by mvdan** [golang/go#41955]
Such a table would be useful to find regular livestreams mainly related to Go, such as Go coding or teaching aspects of the language to newcomers. It would be similar to https://github.com/golang/go/wiki/Conferences, but exclusively for regular livestreams.

Conferences, podcasts, and meetups would not be applicable in this table even if they have livestreams, because they all have their aggregated lists already.

The table could have the following columns:

* Name
* Topic (up to 40 characters)
* Frequency (Daily, Weekly, Twice per week, Monthly, etc)
* Link (Twitch, Youtube, etc)

I already have three entries to kickstart the table: @mdlayher, @stapelberg, and @mdempsky. I plan to add myself to the list soon enough :)

**Comment by rsc** [comment]
Please go ahead.

**Comment by mvdan** [comment]
Done: https://github.com/golang/go/wiki/Livestreams

I filled the info for the three people I know, please update your information as each of you see fit. @stapelberg I could not find how frequent your livestreams are.

I didn't include @jordanlewis as his livestreams seem to be around CockroachDB - I'll leave it up to him to decide if that qualifies as a "Go livestream" :)

**Comment by jordanlewis** [comment]
I stream once or twice a week. The topic is definitely CockroachDB, but it's CockroachDB internals, and CockroachDB is a Go program with lots of interesting Go problems to look at and talk about. Go questions do come up every stream. So, I'd be honored to be on the wiki, and will add myself unless you have an issue with it!

**Comment by mvdan** [comment]
None at all, sounds good! It was just hard to judge what the content was like without actually watching entire videos :)
