### ISSUE TITLE
sort: Stable merge is unstable if Less does not define a strict weak order

### ISSUE THREAD

**Issue by alandonovan** [golang/go#41951]
The block merge portion of sort.Stable does not appear to be stable when a sequence contains unordered pairs of values (e.g. NaN < x).

See https://play.golang.org/p/h_m2BDF5n63

```
	type F []float64
	func (p F) Less(i, j int) bool { return p[i] < p[j] } // note: IEEE-754 ordering, not sort.Float64s ordering

	// len=20: uses insertion sort
	a := F{4, 2, NaN, 3, 1, 4, 2, NaN, 3, 1, 4, 2, NaN, 3, 1, 4, 2, NaN, 3, 1}
	sort.Stable(a)
	fmt.Println(a, len(a)) // [2 4 NaN 1 2 3 4 NaN 1 2 3 4 NaN 1 2 3 4 NaN 1 3] 20
	
	// len=21: merges two insertion-sorted blocks
	b := F{4, 2, NaN, 3, 1, 4, 2, NaN, 3, 1, 4, 2, NaN, 3, 1, 4, 2, NaN, 3, 1, 0}
	sort.Stable(b)
	fmt.Println(b, len(b)) // [2 4 NaN 0 1 2 3 4 NaN 1 2 3 4 NaN 1 2 3 4 NaN 1 3] 21
```
	
Observe that the final 0 has migrated into the second NaN-bracketed portion.

Note that we are defining Less as `float64 < float64` without the special handing that sort.Float64s does.

`go version devel +5b509d993d Tue Oct 13 08:36:41 2020 +0000 linux/amd64`

**Comment by alandonovan** [comment]
Perhaps the solution here is to document: "sort.Interface.Less must define a partial order, and float64 < float64 is not a partial order because it is not transitive (a < b and not c < b => a < c) for NaN values. Therefore do not use float64 < float64 for sorting."

C++ and Python's sort functions (std::stable_sort, sorted) are similarly unstable in the presence of NaN. Java's solution is to require a total order: java.lang.Double.compareTo is similar to Go's sort.Float64s but additionally orders -0.0 < 0.0.

**Comment by rsc** [comment]
As you figured out, the bug here is that Less isn't a less-than function.

**Comment by smasher164** [comment]
@alandonovan Is it okay to close this issue, since #34915 is resolved?
