### ISSUE TITLE
Golang download incorrect format 

### ISSUE THREAD

**Issue by bishgupp** [golang/go#41959]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
while working on m local mac and also via a LinuxAcademy Cloud CentOS vm

[root@6f63fcad301c tmp]# curl -O "https://golang.org/dl/go1.15.2.linux-amd64.tar.gz"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    75  100    75    0     0    797      0 --:--:-- --:--:-- --:--:--   797
[root@6f63fcad301c tmp]# ls -l
total 4
-rw-rw-r--. 1 cloud_user cloud_user 75 Oct 13 20:37 go1.15.2.linux-amd64.tar.gz
drwxr-xr-x. 2 root       root       19 Oct 13 17:10 hsperfdata_root
drwx------. 2 cloud_user cloud_user 24 Oct 13 15:42 ssh-vdRqQLd42Gs7
drwx------. 3 root       root       17 Oct 13 15:42 systemd-private-005a7aaa0fb94a7083433a6ae176b798-bolt.service-Sa3En3
drwx------. 3 root       root       17 Oct 13 15:41 systemd-private-005a7aaa0fb94a7083433a6ae176b798-chronyd.service-wu8Liu
drwx------. 3 root       root       17 Oct 13 15:42 systemd-private-005a7aaa0fb94a7083433a6ae176b798-colord.service-I8GoTG
drwx------. 3 root       root       17 Oct 13 15:42 systemd-private-005a7aaa0fb94a7083433a6ae176b798-fwupd.service-MmSimM
drwx------. 3 root       root       17 Oct 13 15:41 systemd-private-005a7aaa0fb94a7083433a6ae176b798-ModemManager.service-gEbAxp
drwx------. 3 root       root       17 Oct 13 15:42 systemd-private-005a7aaa0fb94a7083433a6ae176b798-rtkit-daemon.service-syOiLy
drwx------. 2 cloud_user cloud_user  6 Oct  2 01:04 tracker-extract-files.1001
[root@6f63fcad301c tmp]# file go1.15.2.linux-amd64.tar.gz 
go1.15.2.linux-amd64.tar.gz: HTML document, ASCII text

### What did you expect to see?
a tar.gz formated file

### What did you see instead?
an html file

**Comment by seankhliao** [comment]
follow the redirects (curl -L)

**Comment by davecheney** [comment]
Closing as answered
