### ISSUE TITLE
go mod download : no congruence between  command result and help description 

### ISSUE THREAD

**Issue by jaun-rg** [golang/go#41982]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15
</pre>

### Does this issue reproduce with the latest release?
generate the follow project:
```shell
.
├── go.mod
├── go.sum
└── main.go
```

go.mod generate with `go mod init project/test` and install dependencies with `go get google.golang.org/grpc `

```go
module project/test

go 1.15

require (
	google.golang.org/grpc v1.33.0
)

``` 

go mod download (with an existent go.mod and main.go)
and 
go help mod download 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/${user}/Library/Caches/go-build"
GOENV="/Users/${user}/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/${user}/go-workspace/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/${user}/go-workspace"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tk/v867zc1j74
</pre></details>

### What did you do?
When running the command `go mod download `  in directory with a go.mod and main.go files, this command return
```bash
go mod download: no modules specified (see 'go help mod download')
```

### What did you expect to see?
According to `go help mod download`:
> _"... With no arguments, download applies to all dependencies of the main module (equivalent to 'go mod download all'). ..."_

using the command `go mod download all` the dependencies are installed as expected

**Comment by seankhliao** [comment]
Your env indicates you are not in a module

**Comment by jaun-rg** [comment]
This is not case; The project was generated with `go module init ...`

**Comment by bcmills** [comment]
I'm not able to reproduce the reported behavior with the steps described. Please provide the exact sequence of commands for which you observed the problem.

```
test$ go version
go version go1.15.3 linux/amd64

test$ go mod init project/test
go: creating new go.mod: module project/test

test$ cat > main.go
package main

func main() {}

test$ go get -d google.golang.org/grpc
go: downloading google.golang.org/grpc v1.33.0
go: google.golang.org/grpc upgrade => v1.33.0
go: downloading golang.org/x/net v0.0.0-20190311183353-d8887717615a
go: downloading golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: downloading github.com/golang/protobuf v1.3.3
go: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
go: downloading golang.org/x/text v0.3.0

test$ go mod download

test$
```
