### ISSUE TITLE
x/text: incorrect convert from utf8 to gb18030

### ISSUE THREAD

**Issue by xiongjiwei** [golang/go#41990]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.8 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
https://play.golang.org/p/HzLLJkSCkd3

### What did you expect to see?

`AAA1`

### What did you see instead?
`83389837`

**Comment by robpike** [comment]
You are printing  the output using %x, which will show the bytes of the result as hex values. Use %s instead. The output will still not be AAA1, but it will be more plausible. Here is a slightly rewritten version. https://play.golang.org/p/xiGoO_bnxh-

Please let us know if this addresses the issue for you.

**Comment by xiongjiwei** [comment]
@robpike thank you for your commet, but I use %x for purpose, unicode codepoint `\u+e000` encoded by `gb18030` should be `AAA1`.

**Comment by kennytm** [comment]
For reference, "\x83\x38\x98\x37" is the GB18030 encoding of U+F014, not U+E000. Both characters are within the PUA though.

(Also the bug is still not fixed.)
