### ISSUE TITLE
x/term: Why IsTerminal reports `true` on redirected `stdout`?

### ISSUE THREAD

**Issue by gabyx** [golang/go#42003]
### What version of Go are you using (`go version`)?
1.15.2

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/gabyx/Library/Caches/go-build"
GOENV="/Users/gabyx/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/gabyx/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/gabyx/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/gabyx/Desktop/githooks/githooks/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jf/0dqq5t6x0rxd9kkp8vmc18gc0000gn/T/go-build702825481=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
```
package main

import (
	"fmt"
	"golang.org/x/term"
	"os"
)

func main() {
    if term.IsTerminal(int(os.Stdout.Fd())) {
        fmt.Println("Is Terminal")
    }
}
```
and run it with `./run 1> Log.txt`.

### What did you expect to see?
No output in Log.txt because `stdout` is redirected?

### What did you see instead?
`Is Terminal` in Log.txt

**Comment by ianlancetaylor** [comment]
Your program doesn't compile:

```
foo.go:10:33: cannot use os.Stdout.Fd() (type uintptr) as type int in argument to term.IsTerminal
```

When I fix that, the program behaves as I expect:

```
> ./foo
Is Terminal
> ./foo > /tmp/x.txt
> cat /tmp/x.txt
>
```

Show us a way to reproduce the problem.

**Comment by gabyx** [comment]
Updated

**Comment by gabyx** [comment]
Really. I am on Darwin macOs in a Zsh shell. There it happens.

**Comment by gabyx** [comment]
I will provide more infos!

**Comment by davecheney** [comment]
@gabyx I am using darwin with zsh, I cannot reproduce your findings
```
(~/src) % go build term.go && ./term | tee log.out
(~/src) % cat log.out
(~/src) % go build term.go && ./term > log.out
(~/src) % cat log.out
(~/src) %
```

**Comment by gabyx** [comment]
Thx for that report. I will investigate later in 2 days

Von meinem iPhone gesendet

**Comment by gabyx** [comment]
Sorry for your precious time. I used the compiled code under a hook invoked by `git commit` which is where I got confused -> git attaches its stderr to both stdout/stderr of the hook executable... hm...

This works fine.
