### ISSUE TITLE
cmd/go: panic in base.SetFromGOFLAGS

### ISSUE THREAD

**Issue by tie** [golang/go#42013]
### What version of Go are you using (`go version`)?

```
go version devel +66e66e7113 Sun Sep 13 19:17:09 2020 +0000 darwin/amd64
```

### What did you do?

```
GOFLAGS='=' gotip env
GOFLAGS='-trimpath =' gotip env
GOFLAGS='= -trimpath' gotip env
```

### What did you expect to see?

```
go: parsing $GOFLAGS: non-flag "="
```

### What did you see instead?

```
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
cmd/go/internal/base.SetFromGOFLAGS(0x195a938)
	/go/src/cmd/go/internal/base/goflags.go:101 +0x9a7
main.main()
	/go/src/cmd/go/main.go:188 +0x755
```

**Comment by bcmills** [comment]
Neat find! Thanks for the report.

**Comment by obeyda** [comment]
Hello, can I help on this issue?

**Comment by bcmills** [comment]
@obeyda, sure! Start with a new test case replicating the panic in `src/cmd/go/testdata/script`.

**Comment by obeyda** [comment]
On second thought, I think it would make more sense to silently ignore the bad flag instead of showing an error, since this only happens in `env` and `bug` commands, and these commands are used when debugging...
see comment on: https://go.googlesource.com/go/+/refs/heads/master/src/cmd/go/internal/base/goflags.go#40

**Comment by bcmills** [comment]
Yep. When `hideErrors` is false, `InitGOFLAGS` should report the invalid flags, so `SetFromGOFLAGS` can ignore invalid flags unconditionally. (Either the error has already been reported in `InitGOFLAGS`, or we don't care to report it at all.)
