### ISSUE TITLE
x/tools/go/analysis/passes/buildtag: buildtag check triggers on multiline comment that mentions "+build" at start of line

### ISSUE THREAD

**Issue by dmitshur** [golang/go#42019]
`gotip test golang.org/x/build/cmd/release` failed before [CL 263117](https://golang.org/cl/263117) with:

```
$ gotip test   
# golang.org/x/build/cmd/release
./releaselet.go:609:1: +build comment must appear before package clause and be followed by a blank line
```

Because `release` had a multiline comment that mentioned "+build", and the lines happened to be split such that "+build" was at the start of a line:

```
// runSelfTests contains the tests for this file, since this file is
// +build ignore. This is called by releaselet_test.go with an
// environment variable set, which func main above recognizes.
func runSelfTests() {
```

I've fixed `release` by adjusting the comment to avoid beginning with "// +build" in [CL 263117](https://golang.org/cl/263117). CC @4a6f656c.

@rsc, is this a false-positive in vet that can/should also be fixed, or is it not a false-positive?

**Comment by dmitshur** [comment]
Now that x/build test failure is fixed, I've retitled to be about the buildtag check.

As far as I can tell, this is working as intended and this issue should be closed. But I'll let @rsc or @matloob confirm.

**Comment by rsc** [comment]
Working as intended: that might have been a real misplaced // +build line.
