### ISSUE TITLE
Why not define this layout as a standard const value?

### ISSUE THREAD

**Issue by wk30** [golang/go#42012]
https://github.com/golang/go/blob/af8748054b40e9a1e529e42a0f83cc2c90a35af6/src/time/format.go#L451

**Comment by mvdan** [comment]
Read the docs:

```
// The returned string is meant for debugging; for a stable serialized
// representation, use t.MarshalText, t.MarshalBinary, or t.Format
// with an explicit format string.
```

The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.

**Comment by wk30** [comment]
@mvdan I think it's inappropriate because json.Marshal and many other methods use this function for time.Time to convert a string. So I demand to define this layout as a const valiable. Also, this annotation here is not that good.

**Comment by mvdan** [comment]
> json.Marshal and many other methods use this function for time.Time to convert a string

That doesn't seem to be true: https://golang.org/src/time/time.go?s=38148:38191#L1230

Again, I would suggest that you use the forums for these questions before filing bugs.

> So I demand

That comes off a bit aggressive, but I assume you didn't mean it that way.

**Comment by wk30** [comment]
No,I mean strongly suggest,not that way.The json.marshal may be not a correct example,I mean we use time.Time.String very frequently,so made this layout as a constant may be very pretty or made the string function use time.RFC3339Nano layout would also be better(the second way may be not compatible),otherwise we should define the same layout ourself and it's duplicated.
