### ISSUE TITLE
net/http: http.nothingWrittenError incompatible with errors.Is/As

### ISSUE THREAD

**Issue by zeisss** [golang/go#42020]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.15.2
</pre>

### Does this issue reproduce with the latest release?

I think so, yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zeisss/Library/Caches/go-build"
GOENV="/Users/zeisss/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zeisss/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zeisss/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x0/0_rddyy16qn1sy9n_pclmxqh0000gn/T/go-build239938081=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

1. Performed a http request via `net/http.Client`
2. Received a `net/http.nothingWrittenError` (`write tcp 172.31.16.237:54422->1.2.3.4:80: write: connection reset by peer`)
3. Tried checking it with `var opError *net.OpError; if errors.As(err, &opsError) { ... }` to map to a user friendly errorcode
4. Error gets reported as an unknown error Rollbar, thus I know it is a `http.nothingWrittenError`.

### What did you expect to see?

I expected `errors.As()` to return true for this error

### What did you see instead?

I saw `errors.As()` returning false. 

I believe the problem to occur, since the error is neither the right type nor does `Unwrap()` return the `OpError` error at any point (since it is directly in `http.nothingWrittenError`. The same problem can be observed for `errors.Is()`. See https://play.golang.org/p/0XhEPLe0bRy

### Use Case

We are running a load test generator written in Go and we need to provide our users with an aggregated error report, thus we need to be able to unpack and understand the errors we receive.

**Comment by toothrot** [comment]
It seems like implementing `Unwrap` on `net/http.nothingWrittenError` makes sense to me. Alternatively, as it's not exported, it could be changed to work with errors.Is/As, which is essentially what it is doing before that existed.

/cc @neild 

I'd be happy to do this change if others agree.

**Comment by neild** [comment]
I don't see a problem in principle, but I wonder if we should be returning `nothingWrittenError` at all. Perhaps it should be unwrapped before being returned to the user, as is done with `transportReadFromServerError` here:

https://go.googlesource.com/go/+/refs/heads/master/src/net/http/transport.go#605

I haven't traced all the code pathways, so I'm not sure if adding a case for `nothingWrittenError` at that location would be sufficient or not.

**Comment by zeisss** [comment]
If it makes a difference: nothing written is an information we would be happy to expose to our users. We are currently thinking about using "net/http/httptrace" for that though, so I guess nothing gets lost if you never return `nothingWrittenError`.

**Comment by zeisss** [comment]
This still occures with `go version go1.17.3 linux/amd64`.

**Comment by elagergren-spideroak** [comment]
Friendly ping about this issue. Do we have an idea which direction we want to go wrt unwrapping `nothingWrittenError` or making it implement `Unwrap`?

**Comment by konradreiche** [comment]
This has been fixed recently, see: https://github.com/golang/go/pull/56451

**Comment by zeisss** [comment]
I agree, https://github.com/golang/go/commit/531ba0c8aae9efe25e33bf0bfa40f4941d8c5ab8 should fix this and went live with Go 1.20.
