### ISSUE TITLE
encoding/asn1: support indefinite form 

### ISSUE THREAD

**Issue by lxShaDoWxl** [golang/go#42021]
Hi! asn1 encode incorrect support ISO/IEC 8825-1:2015 
https://www.itu.int/ITU-T/recommendations/rec.aspx?rec=12483&lang=ru
> Length octets 
> Two forms of length octets are specified. These are:
> a) the definite form (see 8.1.3.3); and
> b) the indefinite form (see 8.1.3.6). 

not work form "b"

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.9 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/viktor/.cache/go-build"
GOENV="/home/viktor/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/viktor/main/projects/golang"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/viktor/main/projects/golang/src/incraft/soap-test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build647107160=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Usage asn1.Unmarshal
https://play.golang.org/p/a1FhCy3nUvj

### What did you expect to see?
success unmarshal bytes

### What did you see instead?
asn1: syntax error: indefinite length found (not DER)

**Comment by toothrot** [comment]
See also #12267

/cc @FiloSottile @agl

**Comment by lxShaDoWxl** [comment]
bad no support BER (Basic Encoding Rules)
it wasn't just called **basic**))

**Comment by FiloSottile** [comment]
encoding/asn1 intentionally only implements DER, as that's what almost all cryptography packages that depend on it need.

> Package asn1 implements parsing of DER-encoded ASN.1 data structures, as defined in ITU-T Rec X.690.
