### ISSUE TITLE
cmd/objdump: TestDisasmExtld fails with "no runtime.symtab symbol found" on AIX

### ISSUE THREAD

**Issue by dmitshur** [golang/go#42025]
On the aix-ppc64 builder:

```
--- FAIL: TestDisasmExtld (2.79s)
    objdump_test.go:157: Running [/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/bin/go build -o /ramdisk8GB/workdir-host-aix-ppc64-osuosl/tmp/TestObjDump382551457/hello-b8671a8435298d43c67d864e10c70b6b.exe -ldflags=-linkmode=external fmthello.go]
    objdump_test.go:210: Running [/ramdisk8GB/workdir-host-aix-ppc64-osuosl/tmp/TestObjDump382551457/testobjdump.exe -s main.main /ramdisk8GB/workdir-host-aix-ppc64-osuosl/tmp/TestObjDump382551457/hello-b8671a8435298d43c67d864e10c70b6b.exe]
    objdump_test.go:214: objdump "fmthello.exe": exit status 1
        objdump: disassemble /ramdisk8GB/workdir-host-aix-ppc64-osuosl/tmp/TestObjDump382551457/hello-b8671a8435298d43c67d864e10c70b6b.exe: no runtime.symtab symbol found
FAIL
FAIL	cmd/objdump	4.421s
```

_(Source: https://build.golang.org/log/ba1d49d26254c0260ab1e229800f45ad6768ee55.)_

This looks related to #40972, [CL 262779](https://golang.org/cl/262779), and [CL 263137](https://golang.org/cl/263137).

CC @cherrymui @Helflym.

**Comment by cherrymui** [comment]
Thanks. In CL 263137 I refactored the skipping logic. The old code skips TestDisasmExtld  for PPC64, with a comment that it doesn't support external linking. I replaced it with MustHaveCGO (which covers external linking). But on AIX/PPC64, which does support cgo and external linking, the test needs to be skipped for a different reason. I'll update.
