### ISSUE TITLE
syscall: flaky TestExec failure on macOS: signal: Illegal instruction

### ISSUE THREAD

**Issue by rsc** [golang/go#42023]
Happened once during all.bash:

	--- FAIL: TestExec (0.14s)
	    exec_unix_test.go:254: 
	        signal: illegal instruction
	FAIL
	FAIL	syscall	1.026s

Can't reproduce.

**Comment by rsc** [comment]
Can't reproduce with "go test -short syscall" but happened again during all.bash on my Mac. Hmm.

**Comment by rsc** [comment]
I see - looks like the fix for #41702 was incorrect and CL 262817 needs to be submitted.

**Comment by ianlancetaylor** [comment]
The fix wasn't incorrect so much as incomplete.
