### ISSUE TITLE
x/pkgsite: Source links lead to invalid branch ids

### ISSUE THREAD

**Issue by amlinux** [golang/go#42038]
### What is the URL of the page with the issue?

https://pkg.go.dev/google.golang.org/grpc/status 
 
 
### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36 
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/449322/96335048-be9b5100-1075-11eb-90fe-d81a52ce0af3.png) 
 
### What did you do?
 
Clicked on the outlined links 
 
### What did you expect to see?

Source code at https://github.com/grpc/grpc-go/blob/master/status/status.go#L100
 
### What did you see instead?

404 page at https://github.com/grpc/grpc-go/blob/v1.33.0/status/status.go#L100

Note "v1.33.0" that doesn't exist.

**Comment by jba** [comment]
It seems that grpc deleted a tag. pkg.go.dev knows about v1.33.0, as does the proxy:
```
> curl $GOPROXY/google.golang.org/grpc/@v/v1.33.0.info
{"Version":"v1.33.0","Time":"2020-10-08T18:59:09Z"}
```
But it's not on the repo.

I don't think we should try to work around this case. It shouldn't happen (you're not supposed to delete tags), and if it does it should be short-lived, until a new release is published. (To be clear, a new release will fix the problem for the default, latest-version page, but the source links on the v1.33.0 will be broken until the tag is re-created.)

This case is another argument against the way we currently do source linking. See #39559 for more on that.
