### ISSUE TITLE
x/pkgsite:github.com/micro/micro/v3

### ISSUE THREAD

**Issue by asim** [golang/go#42045]
I believe it would be useful if there was way to display docs for projects with any license or at the very least make it simpler to add new licenses to the policycheck. Given the state of cloud and how cloud providers are abusing open source, we're using a new license written by Heather Meeker that prevents it from being hosted as a service. Its still open source, you just can't profit from it if you're AWS.

There is an open PR to add the license but being blocked because its not in the SPDX list. Some help would be useful. https://github.com/google/licensecheck/pull/33. Otherwise please allow a way to display code that doesn't have expected licenses. 

### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/micro/micro/v3?tab=overview
 
### What is your user agent?
 
Mozilla/5.0 (X11; CrOS x86_64 13421.53.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36 
 
### Screenshot
 
https://imgur.com/TGsstvM
 
### What did you do?

Making use of the Polyform Shield license
 
### What did you expect to see?
 
The godocs for Micro
 
### What did you see instead?

Blank screen because Micro does not have an appropriate license.

**Comment by jba** [comment]
Sorry for the delay on this.

Even if this had an SPDX ID and licensecheck recognized it, we've been advised that we cannot interpret it as granting us the rights we need to display the README and documentation.
