### ISSUE TITLE
x/website: with go ou

### ISSUE THREAD

**Issue by popeye8777** [golang/go#42048]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by popeye8777** [comment]
> ### What version of Go are you using (`go version`)?
> $ go version
> 
> ### Does this issue reproduce with the latest release?
> ### What operating system and processor architecture are you using (`go env`)?
> `go env` Output
> ### What did you do?
> ### What did you expect to see?
> ### What did you see instead?

$ go python

**Comment by popeye8777** [comment]
$ go python

**Comment by ALTree** [comment]
Doesn't seem like a Go bug, closing.
