### ISSUE TITLE
fmt.Print Float64 out of range

### ISSUE THREAD

**Issue by klikpaspor** [golang/go#42041]
fmt.Print float64 out of range

```
package main

import (
	"fmt"
)

func main() {
	selisih := 2270667198.58155
	fmt.Print(selisih)
}

```

![a](https://user-images.githubusercontent.com/42468310/96347051-4f4f4c80-10c9-11eb-8592-e514af0d7a3b.png)

**Comment by randall77** [comment]
I don't see a bug here.

**Comment by ALTree** [comment]
I think OP is confused by the scientific notation. 

@klikpaspor please see https://en.wikipedia.org/wiki/Scientific_notation#E_notation. The number that was printed is correct. Closing here.
