### ISSUE TITLE
Variable declared but not used

### ISSUE THREAD

**Issue by addy1997** [golang/go#42044]
I wrote a program for palindrome. After compiling I am getting an error that says "remainder" declared but not used. How to get rid of this error? The code is given below

```
package main
import (
        
         "fmt"
)

func Palindrome(number int) {

    var remainder, temp int
    var reverse int = 0
    

    temp = number
    
    for{
        remainder = number%10
        reverse = reverse*10 + number
        number/=10
        
    if(number==0){
      break
    }
  }
    if(temp==reverse){
        fmt.Printf("%d is a Palindrome",temp)
    }else{
        fmt.Printf("%d is not a Palindrome",temp)
    }
  
}    

func main() {
    number:=456
    Palindrome(number)
}
```

**Comment by ALTree** [comment]
Remove the `reminder` variable, is not used anywhere, and in Go unused variables are a compilation error. Closing here.

**Comment by addy1997** [comment]
> Remove the `reminder` variable, it's not used anywhere, and in Go unused variables are a compilation error. Closing here.

Its again giving me the error.

**Comment by ALTree** [comment]
That's because you're still declaring the variable. As I wrote:

> Remove the reminder variable

Remove the declaration.
