### ISSUE TITLE
cmd/go: get with GIT_CONFIG ignores env variable

### ISSUE THREAD

**Issue by valery-barysok** [golang/go#42055]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.15.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/user/work/sunnycat/bin"
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/user/go/pkg/mod"
GONOPROXY="github.com/user/*"
GONOSUMDB="github.com/user/*"
GOOS="darwin"
GOPATH="/Users/user/go"
GOPRIVATE="github.com/user/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/k9/h8z58c7n2wxf9gd6rm0m_bd40000gp/T/go-build919199640=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

<pre>
export GIT_CONFIG=$(pwd)/.gitconfig
#[url "ssh://git@github.com"]
#	insteadOf = https://github.com

$ go get -u github.com/user/module
</pre>

### What did you expect to see?

`go get` takes into account GIT_CONFIG env variable

### What did you see instead?

<pre>
# cd .; git clone -- https://github.com/user/module /Users/user/go/src/github.com/user/module
Cloning into '/Users/user/go/src/github.com/user/module'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/user/module: exit status 128
</pre>

**Comment by cagedmantis** [comment]
Can you run `git config --list --show-origin` to ensure the configuration settings are as expected?

**Comment by valery-barysok** [comment]
@cagedmantis,
I run this command from different places and it works as expected. I see the configuration setting based on GIT_CONFIG value.

**Comment by valery-barysok** [comment]
@cagedmantis, Do you need additional info?

**Comment by valery-barysok** [comment]
I use `direnv` to manage environment variables depends on current directory and I think the issue arises when go changes directory  under the hood while executes `go get -u ` operation.

**Comment by cagedmantis** [comment]
@valery-barysok Thanks for the additional information. I am not able to reproduce this, even with some `direnv` experiments. I am going to loop in the maintainers of the go command for good measure.

/cc @bcmills @jayconrod @matloob

**Comment by bcmills** [comment]
@valery-barysok, `go get` does not change its own working directory, but it does invoke `git` in a different directory (namely, in the Go module cache).

The `go` command doesn't know anything about `direnv` or about the `GIT_CONFIG` environment variable, so if you're going that route it's on you to ensure that your `GIT_CONFIG` environment variable is set appropriately for commands executed in the module cache (and, for that matter, in temporary directories).

**Comment by bcmills** [comment]
@valery-barysok, can you confirm that your `GIT_CONFIG` setting applies to subdirectories of `$(go env GOMODCACHE)`?

**Comment by valery-barysok** [comment]
@bcmills, I can confirm that `direnv` also configured in the same way as for dir where i execute `go get`. As expected it does not work but `git clone` works in both places.

**Comment by valery-barysok** [comment]
@bcmills, I debugged go source code and seems like issue actually happens inside git itself when go executes `git ls-remote -q origin`. It is succeeded if I put `.gitconfig` file to user home directory instead of custom place for this operation.

**Comment by valery-barysok** [comment]
I resolved the issue by using XDG_CONFIG_HOME env variable instead of GIT_CONFIG.

So GIT_CONFIG is wrong way to provide custom place for git config file because it works with limited list of commands.
