### ISSUE TITLE
access: deklerk -> github.com/golang org

### ISSUE THREAD

**Issue by jadekler** [golang/go#42068]
See https://golang.org/wiki/GithubAccess

I'd like to request access to the golang org. I hope this is the right way to do so - https://github.com/golang/go/wiki/GitHubAccess seems to indicate Yes! but is more about `go-assignees` and `go-approvers`, whereas I'm hoping for access to the golang github org. :smile:

**Comment by mvdan** [comment]
Can you clarify why you want access to the github org? You mean full write access to create repositories and so on? I'm in go-approvers and I can't do that nor edit any org settings, for example - not that I would need to do those things.

**Comment by jadekler** [comment]
Oh gosh, no, the least access possible. I'm mostly in it for the badge, which I admit is a terrible reason.

I'm not sure how `go-approvers` and `go-assignees` (are there others?) relate to the github org. If both confer the badge, then `go-assignees` would be excellent: it would be mildly convenient to be able to be assigned to issues.

**Comment by mvdan** [comment]
Gotcha :) I can see that go-assigners is a group in the entire org, but nothing more. I imagine go-assignees is also for the entire org.

**Comment by jadekler** [comment]
cc @dmitshur

**Comment by toothrot** [comment]
Invite sent!

**Comment by jadekler** [comment]
Thank you!!

**Comment by dmitshur** [comment]
@jadekler I think this was just about the organization badge, but I've also added you to `go-approvers` and `go-assignees` groups now since you you have a strong history of high-quality contributions to the Go project, and we'd like you to be able to continue to do so with less overhead. Thank you! (CC @jayconrod, @golang/release)

**Comment by jadekler** [comment]
Thank you so much, this means a lot to me!
