### ISSUE TITLE
x/build: improve trybot aliases for ppc64

### ISSUE THREAD

**Issue by laboger** [golang/go#42067]
I frequently see changes being made to code related to PPC64 which only use TRY=ppc64 for testing those changes. While I understand that this seems like the right default for code related to ppc64, this actually runs only the linux-ppc64 trybot, which tests only big endian and has limited linking capabilities (internal linking only, no cgo, no others like plug-ins or pie). So this selection is not the best default and does not provide good coverage for PPC64 testing.

I understand the naming is unfortunate because in the Go source code PPC64 usually used as a general term for code generation that applies to linux-ppc64, linux-ppc64le, linux-ppc64le-power9, and aix-ppc64.

Could we change the ppc64 alias in build/dashboard/builders.go to run the linux-ppc64le buildlet? This is really the most commonly used Power target for Go and provides the most linking capability. If someone REALLY wanted to run ppc64 big endian they could still use the linux-ppc64 alias.

I'd also like to have an alias for ppc64le on power9, maybe ppc64lep9.

I could make the change but I don't know how to test it. @dmitshur

**Comment by dmitshur** [comment]
> I frequently see changes being made to code related to PPC64 which only use TRY=ppc64 for testing those changes. [...] Could we change the ppc64 alias in build/dashboard/builders.go to run the linux-ppc64le buildlet?

We currently have the following aliases related to ppc64:

```
"aix":            "aix-ppc64",
"linux-ppc64":    "linux-ppc64-buildlet",
"linux-ppc64le":  "linux-ppc64le-buildlet",
"ppc64":          "linux-ppc64-buildlet",
"ppc64le":        "linux-ppc64le-buildlet",
```

I think longer aliases need to be precise, and "linux-ppc64", "linux-ppc64le" should get the expected builder. But a short alias such as "ppc64" can be modified to point to the builder we think is most fitting. (Ideally, in the future, "ppc64" should expand to multiple builders to provide sufficient coverage, and people can use a longer alias if they want a very specific single builder.)

We should remove "ppc64le" to avoid or making it seem like "ppc64" gets the big endian one.

> I'd also like to have an alias for ppc64le on power9, maybe ppc64lep9.

How about "linux-ppc64le-power9" so it's clear it's a specific target?

@laboger Do you mind sending a mail to golang-dev@ to notify people who rely on PPC64 aliases about this change and direct them to this issue if they want to express support for it or share concerns? It'd be nice to get some more feedback from others before we make a change to slowbot aliases.

Also CC @toothrot, @cagedmantis.

**Comment by laboger** [comment]
Thanks, I agree with all your suggestions, especially at some point to have one keyword to run all 4 variations. I will send a note to golang-dev to gather more opinions.

- ppc64 alias will run the ppc64le buildlet
- long names will specify the exact buildlet and there will be a new name for power9 that is easier to remember: aix-ppc64, linux-ppc64, linux-ppc64le,linux-ppc64le-power9

**Comment by dmitshur** [comment]
Sound good, thanks for doing that.

I've remembered that we have a test that ensures each GOOS/GOARCH term has *some* slowbot alias. But given how similar `ppc64{,le}` are, I think it's fine for us to modify the test so that a slowbot alias for "ppc64" also satisfies the requirement for "ppc64le".

**Comment by cherrymui** [comment]
Maybe we could add "ppc64x"?

**Comment by laboger** [comment]
>Maybe we could add "ppc64x"?

And what would ppc64x run?

**Comment by cherrymui** [comment]
> And what would ppc64x run?

BE and LE. Basically, `*ppc64*`.

**Comment by laboger** [comment]
> BE and LE. Basically, *ppc64*.

Yes, that sounds great once we get multiple trybots to run for a single alias.

**Comment by laboger** [comment]
One other suggestion, although maybe this belongs in a different issue. If I have a CL and specify a new TRY list, it doesn't rerun the trybots unless the CL has changed since the last TRY (at least that appears to be the way it works.) It seems that if a new TRY list is specified it should rerun it?

**Comment by cherrymui** [comment]
I _think_ it actually runs, but Go Bot doesn't print a message when it starts. It will print a message when it finishes.

**Comment by laboger** [comment]
Look at this CL: https://go-review.googlesource.com/c/go/+/266202. Shouldn't the message say which slowbots ran on the last one? Or maybe it is still using the first set of keywords which were not correct.

**Comment by dmitshur** [comment]
This appears to be issues #42084 and #38235. Please add a comment there so we have more data points.

**Comment by laboger** [comment]
How about these aliases:
- ppc64 runs linux-ppc64le
- ppc64be can be added to run linux-ppc64 (although this should be rarely used. aix-ppc64 will test ppc64 big endian.)
- ppc64lep9 can be added to run linux-ppc64le-power9osu
- linux-ppc64le-power9 can be added to run linux-ppc64le-power9osu

Right now we have names with linux- and short names without linux-.

**Comment by cherrymui** [comment]
> ppc64 runs linux-ppc64le

I think this is confusing, as the GOARCH of big-endian PPC64 is actually ppc64. In all other cases, if an alias matches a GOARCH, it runs that GOARCH. This would be weird.

**Comment by laboger** [comment]
After moving the LUCI the names are selected so this is no longer a problem.
