### ISSUE TITLE
x/website: Date/Time in Playground set to fixed value

### ISSUE THREAD

**Issue by doomguy** [golang/go#42074]
### What version of Go are you using (`go version`)?
n/a

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
n/a

### What did you do?
https://play.golang.org/p/rlm4zFwKDjE
(Output current time in Playground)

### What did you expect to see?
A date in 2020.

### What did you see instead?
2009-11-10 23:00:00 +0000 UTC m=+0.000000001

**Comment by davecheney** [comment]
@doomguy yes, time is fixed in the playground to permit caching of build results. see the about button in the top right hand corner.
