### ISSUE TITLE
provide a way to return from main function with non-zero exit code and run all deferred function

### ISSUE THREAD

**Issue by ghost** [golang/go#42078]
`os.Exit` allows to set a non-zero status code, but it exit the program immediately and no deferred functions are run.

**Comment by davecheney** [comment]
panic?

**Comment by bhwk** [comment]
> panic?

no.

**Comment by ianlancetaylor** [comment]
```Go
func main() {
    os.Exit(realMain())
}

func realMain() int {
    ...
    return 1
}
```

**Comment by mdlayher** [comment]
Since the author deleted their account and Ian provided an easy solution, I'm going to close this.
