### ISSUE TITLE
path/filepath: EvalSymlinks fails on Windows when passed a UNC share root path

### ISSUE THREAD

**Issue by kevpar** [golang/go#42079]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\kevpar\AppData\Local\go-build
set GOENV=C:\Users\kevpar\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\kevpar\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\kevpar\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\kevpar\Source\repos\test\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\kevpar\AppData\Local\Temp\go-build377379998=/tmp/go-build -gno-record-gcc-switches
GOROOT/bin/go version: go version go1.15.3 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.15.3
</pre></details>

### What did you do?

main.go
```golang
package main

import "path/filepath"

func main() {
	p, err := filepath.EvalSymlinks(`\\localhost\c$`)
	if err != nil {
		panic(err)
	}
	println(p)
}
```

Repro:
```
> go run .
```

### What did you expect to see?

```
\\localhost\c$
```

### What did you see instead?

```
panic: The system cannot find the file specified.

goroutine 1 [running]:
main.main()
        C:/Users/kevpar/Source/repos/test/main.go:8 +0xad
exit status 2
```

### Details

This is due to `EvalSymlinks` using the Windows API [FindFirstFile](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstfilea) to attempt to resolve each path component after the volume name. Since `\\localhost\c$` is parsed as the volume name with an empty path following it, this results in a call to `FindFirstFile` for the path of `\\localhost\c$`, which fails with `The system cannot find the file specified.`.

The failure from `FindFirstFile` is expected. Per the documentation for that function:

> On network shares, you can use an lpFileName in the form of the following: "\\\\Server\Share\*". However, you cannot use an lpFileName that points to the share itself; for example, "\\\\Server\Share" is not valid.

One important occurrence of this bug is with Kubernetes. The containerd/containerd runtime uses `EvalSymlinks` to resolve each container mount path on the host. When a mount path is the root of a UNC share (or a symlink to the share root), then `EvalSymlinks` fails, preventing the container from starting. More discussion on this in kubernetes/kubernetes#94213.

As a workaround, if the path to `EvalSymlinks` has a `\` appended, the function works properly, as it hits a conditional that causes an early return, before calling `FindFirstFile`. However, it would be good to fix the source of this issue as well.

Note: This repros for all UNC share roots passed to `EvalSymlinks`. I used the admin share (`\\localhost\c$`) in the example, as that allows a repro without needing access to an external network share, which makes testing easier.

**Comment by kevpar** [comment]
It looks like this can be fixed by just changing the line [here](https://github.com/golang/go/blob/master/src/path/filepath/symlink_windows.go#L71) to also have a case for `len(path) == 0`. This will effectively skip the loop where it tries to resolve later path components using `FindFirstFile`, which is fine, since if `path` is empty, there are no later path components.

However, I'm currently getting an error when trying to run tests in `src/path/filepath`, even without making any changes. So I am probably doing something wrong :)

```
> go test .
# std/path/filepath
package std/path/filepath_test
        match_test.go:9:2: use of internal package internal/testenv not allowed
FAIL    std/path/filepath [setup failed]
FAIL
```

**Comment by kevpar** [comment]
I got the tests to work, and have a fix PR out now.

#42096

**Comment by networkimprov** [comment]
EvalSymlinks is hopelessly broken on Windows (documented within #40180), a replacement in in the works: #37113.

And I believe there's an open issue for this specific problem.
