### ISSUE TITLE
cmd/go: missing `go install path@version` hint in `go run path@version` error

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#42087]
#40276 implements `go install` support for the `path@version` syntax. However the error message from other commands only mention `go get`.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +893f0a9e8f Tue Oct 20 11:01:46 2020 +0200 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?
```
$ go run gioui.org/cmd/gogio@latest
package gioui.org/cmd/gogio@latest: can only use path@version syntax with 'go get'
```

### What did you expect to see?
The error mentioning `go install`

### What did you see instead?
The error only mentioning `go get`

**Comment by toothrot** [comment]
@jayconrod Any update on this issue as a release blocker for Go 1.16?

**Comment by jayconrod** [comment]
[CL 282121](https://go-review.googlesource.com/c/go/+/282121) will fix this.
