### ISSUE TITLE
x/tools/gopls: hangs while loading the workspace

### ISSUE THREAD

**Issue by adityaramani** [golang/go#42081]
Issue Type: <b>Bug</b>

As soon as I load up my remote workspace, the bottom status bar reports the above message and it does not seem to resolve itself. 
Not able to use any features like find definition or cmd + click to go to def.

Strangely this is happening only in this particular workspace, on all other workspaces everything loads fine

Extension version: 0.17.2
VS Code version: Code - Insiders 1.51.0-insider (2ed16d0ce8713a5dfed9729071141be0ccf7fbec, 2020-10-14T05:48:54.391Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.19.46-4.19.1-amd64-9cf031ffa09555f2
Remote OS version: Linux x64 4.19.46-4.19.1-amd64-9cf031ffa09555f2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id 7baeac86-2290-4972-98c4-52269f5e9bbd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 198.18.66.201|
|OS|Linux x64 4.19.46-4.19.1-amd64-9cf031ffa09555f2|
|CPUs|Intel(R) Xeon(R) CPU E31270 @ 3.40GHz (8 x 1734)|
|Memory (System)|15.64GB (0.56GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 198.18.66.201|
|OS|Linux x64 4.19.46-4.19.1-amd64-9cf031ffa09555f2|
|CPUs|Intel(R) Xeon(R) CPU E31270 @ 3.40GHz (8 x 1734)|
|Memory (System)|15.64GB (0.56GB free)|
|VM|0%|
</details>

**Comment by stamblerre** [comment]
I've just revisited this to try to reproduce, and I'm afraid I'm not able to.
@mbolt35: Are you still able to repro this with the latest version (v0.5.3) of `gopls`?

The first issue that you point out is still a problem, but I think it will be addressed by https://github.com/golang/go/issues/38462 (right now, we try to reload packages whenever an import statement is changed, but if we switch to `GOPROXY=off`, the latency will go away).
