### ISSUE TITLE
could I bind a g with a p, the g only schedule by the p?

### ISSUE THREAD

**Issue by Mstch** [golang/go#42091]
could I bind a g with a p, the g only schedule by the p?

**Comment by lu4p** [comment]
Please use Stackoverflow or Reddit to ask such questions, this is for issues in the go language.
Also provide more context: https://stackoverflow.com/help/how-to-ask

**Comment by cagedmantis** [comment]
We don't really use our issue tracker for questions. More people will see your question, and you will get better answers, if you ask on a forum rather than on the issue tracker. See https://golang.org/wiki/Questions.
