### ISSUE TITLE
x/crypto/ssh:  session.Output()  run a time-cost command hangs without returning

### ISSUE THREAD

**Issue by danny-wang** [golang/go#42090]
### go 1.16

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

       session, err := client.NewSession()
	defer session.Close()
	if err != nil {
		logger.GetLogInstance().ErrorLogger.Error(fmt.Sprintf("new session error: %s", err.Error()))
		return "", err
	}

	result, err := session.Output(command)   // code stuck here
	if err != nil {
		logger.GetLogInstance().ErrorLogger.Error(fmt.Sprintf("Failed to run command:%s, Err:%s", command, err.Error()))
		return "", err
	}
	logger.GetLogInstance().DebugLogger.Debug("run command:", command, " result:", string(result))
	return string(result), nil

**Comment by cagedmantis** [comment]
@danny-wang What is in the command being executed?
