### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by archonsd** [golang/go#42104]
You have a typo on the page..

Your line is `func viewHandler(w http.ResponseWriter, r *http.Request) {` and you're missing the closing quotation mark.  It's in the "Using net/http to serve wiki pages" section, about 9 lines under the section heading.  The correct line is:

`func viewHandler(w http.ResponseWriter, r *http.Request") {` (note the second quote at the end of 'http.Request'.

**Comment by dmitshur** [comment]
What is the URL of the page where you're seeing this? Can you please include a screenshot?

**Comment by archonsd** [comment]
It was this page:  "https://golang.org/doc/articles/wiki/" but I'm mistaken..  instead of two quotes, it's an asterisk.  I think I misread it.  Apologies.
