### ISSUE TITLE
x/tools/gopls: support opening a directory that contains a single module

### ISSUE THREAD

**Issue by stamblerre** [golang/go#42108]
A common workflow is opening a directory that contains a module in a subdirectory. Currently, this is only supported with `experimentalWorkspaceModule` enabled, but we should support this in any mode. This is effectively the reverse of `expandWorkspaceToModule`.

With multiple modules, this will not work without `experimentalWorkspaceModule`. Note that we may need handling if the user creates a new module in a higher level directory during the session.

**Comment by ppggff** [comment]
How do I specify which subdirectory?
I have a project with `go.mod` in the `src` subdir, and some mod cache in pkg dir, such as:
/src
      go.mod
/pkg/mod
      cache
      github.com

**Comment by stamblerre** [comment]
I would suggest just opening the `src` directory if you only intend to edit that module--there is no way to configure a module for `gopls` to choose.

**Comment by indierojo** [comment]
Thanks for adding this! Great QoL fix for a few of my projects - it works exactly as I would expect.
