### ISSUE TITLE
x/build/cmd/gomote: confused about support for linux/arm64

### ISSUE THREAD

**Issue by randall77** [golang/go#42101]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by randall77** [comment]
```
$ gomote create linux-arm64-aws
# still creating linux-arm64-aws after 5s; 0 requests ahead of you
# still creating linux-arm64-aws after 10s; 0 requests ahead of you
user-khr-linux-arm64-aws-3
$ gomote put14 user-khr-linux-arm64-aws-3
2020/10/20 17:03:54 Builder type "linux-arm64-aws" not known to this gomote binary. Update your gomote binary. TODO: teach gomote to fetch build configs from the server (Issue 30929)
```

`gomote` seems to be able to make this builder just fine, but it can't `put14` to it.

@golang/osp-team

**Comment by randall77** [comment]
I also can't `gomote destroy` any of the instances I've created.

```
$ gomote list
user-khr-linux-arm64-aws-0	linux-arm64-aws	host-linux-arm64-aws	expires in 14m51.281981674s
user-khr-linux-arm64-aws-1	linux-arm64-aws	host-linux-arm64-aws	expires in 17m50.734081255s
user-khr-linux-arm64-aws-2	linux-arm64-aws	host-linux-arm64-aws	expires in 20m45.278456395s
user-khr-linux-arm64-aws-3	linux-arm64-aws	host-linux-arm64-aws	expires in 21m15.707480138s
$ gomote destroy user-khr-linux-arm64-aws-0
2020/10/20 17:12:44 Builder type "linux-arm64-aws" not known to this gomote binary. Update your gomote binary. TODO: teach gomote to fetch build configs from the server (Issue 30929)
```

**Comment by cherrymui** [comment]
Have you tried updating your gomote binary?

With gomote on my machine, I can push or destroy. put14 fails with a different message.
```
$ VM=user-cherryyz-linux-arm64-aws-0
$ gomote put14 $VM
No GoBootstrapURL defined for "user-cherryyz-linux-arm64-aws-0"; ignoring. (may be baked into image)
$ gomote push $VM
2020/10/20 20:32:38 Remote doesn't have "src/cmd/go/testdata/mod/rsc.io_quote_v2.0.0.txt"
2020/10/20 20:32:38 Remote doesn't have "src/cmd/vet/testdata/assign/assign.go"
2020/10/20 20:32:38 Remote doesn't have "src/runtime/defs_linux_mipsx.go"
2020/10/20 20:32:38 Remote doesn't have "test/fixedbugs/bug319.go"
2020/10/20 20:32:38 Remote doesn't have "src/cmd/api/testdata/src/issue21181/indirect/p.go"
2020/10/20 20:32:38 Remote doesn't have 9253 files (only showed 5).
2020/10/20 20:32:38 Remote lacks a VERSION file; sending a fake one
2020/10/20 20:32:41 Uploading 9254 new/changed files; 24220261 byte .tar.gz
$ gomote destroy $VM
$
$ gomote list
$
```

**Comment by cagedmantis** [comment]
@randall77 After updating the `gomote` binary, are you able to destroy successfully? 

`gomote put14` deploys the bootstrap version of Go defined in [goBootstrapURLTmpl](https://go.googlesource.com/build/+/refs/heads/master/dashboard/builders.go#702). Oftentimes, if the bootstrap version is already included in the image then the value isn't set. `linux-arm64-packet` and `linux-arm64-aws` have the same bootstrap version of Go included at `/usr/local/go-bootstrap`. If you would like us to set `goBootstrapURLTmpl` in order to be able to put the Go bootstrap version in the work directory, we can do that.

**Comment by randall77** [comment]
> @randall77 After updating the gomote binary, are you able to destroy successfully?

I thought I had tried that, but it looks like it didn't actually take. I think I had an older version checked out in my gopath that was overriding my attempts to update it. Blowing everything local away and then updating fixed it.

Sorry for the noise.
