### ISSUE TITLE
x/tools/gopls: add regtests for multiple workspace folders

### ISSUE THREAD

**Issue by stamblerre** [golang/go#42111]
We currently have no test coverage for multiple workspace folders (not using `experimentalWorkspaceModule`). We can add a new mode to the regression tests to cover this case.

**Comment by stamblerre** [comment]
Reopening because this isn't just for nested modules--we need to add tests for multiple workspace folders, each containing a module.

**Comment by findleyr** [comment]
Ah, wrong issue. My bad!

**Comment by findleyr** [comment]
I don't think this is a high priority anymore, since workspaces are now our recommended way to work on multiple modules simultaneously.

**Comment by findleyr** [comment]
We've got several tests, and can add more if and when we have specific things to test for multiple folders. Closing as obsolete.
