### ISSUE TITLE
crypto/x509: consider removing support for signing with RSA-MD5

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#42125]
MD5 is _very broken_, which is why we don't implement support for _verifying_ certificates that use the RSA-MD5 (`MD5WithRSA`) signature algorithm. We do still support _signing_ new certificates with RSA-MD5 though, which is not ideal as it introduces some inconsistency around how we handle certificates (i.e. see https://go-review.googlesource.com/c/go/+/264019).

Presumably we still provide support because at some point in the past there were still some users of RSA-MD5 certificates, and we're only allowing them to _create_ broken certificates rather than verifying them (and thus relying on them). Unless there are still significant use cases I'd suggest we just completely axe support for this broken signature algorithm, reducing our support burden, and hopefully further dissuading anyone from making a serious mistake in their choice of algorithms.

**Comment by ianlancetaylor** [comment]
@rolandshoemaker This is in the Go 1.18 milestone.  What is the status of this for the 1.18 release?  Thanks.

**Comment by rolandshoemaker** [comment]
We decided to pre-announce this in 1.18, and disable it in 1.19, I've moved it to the right milestone.
