### ISSUE TITLE
flag: make the "default" word localizable

### ISSUE THREAD

**Issue by kpym** [golang/go#42124]
In `flag` module we can write all help messages in any language, but the "default" keyword stays in english. 

It will be nice if the [corresponding code](https://github.com/golang/go/blob/b04eb73a6891e81e2e611ee93b3aa8c4769d5967/src/flag/flag.go#L530-L532) could be made "translatable".

**Comment by ALTree** [comment]
Thanks for the request. AFAIK almost nothing in the standard library is localizable, english is the default. So I think it would feel a little "out of place" maybe?

**Comment by kpym** [comment]
@ALTree I understand, but this library is an user interface library. Heaving some log message in english is ok, but producing user interface that has only few non translated words is strange.

Probably this should not be properly "translatable", but only made customizable. As we have `flag.Usage` maybe we can have `flag.DefaultMsg` that can be defined to display the default values ?

**Comment by ianlancetaylor** [comment]
It seems to me that programs that support localization should use the `flag.Usage` function to control the usage message.  They shouldn't call `PrintDefaults` but should use their own locale-appropriate mechanisms.

**Comment by ianlancetaylor** [comment]
Alternatively, use an `io.Writer` that reads the documented format of `PrintDefaults` and applies its own localization as appropriate.

**Comment by kpym** [comment]
@ianlancetaylor Thank you for your advice. I think you are right.

**Comment by kpym** [comment]
Here is an example of how we can do this:

```go
// Replace "default" with "par défaut" in `flag.PrintDefaults`
func PrintDefaultsFr() {
        // save and restore the output (os.Stderr by default)
	original := flag.CommandLine.Output()
	defer flag.CommandLine.SetOutput(original)
	
	// redirect the output to new buffer
	buf := new(bytes.Buffer)
	flag.CommandLine.SetOutput(buf)
	
	// print the defaults in french
	flag.PrintDefaults()
	original.Write(bytes.ReplaceAll(buf.Bytes(), []byte("default"), []byte("par défaut")))
}
```
[Check it in the playground.](https://play.golang.org/p/8UPWCpVhq6L)
