### ISSUE TITLE
x/text: unreachable code or out of bound in internal/number/decimal.go

### ISSUE THREAD

**Issue by novinova** [golang/go#42147]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.14.

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Doesn't mean.
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Looked through source code. And got one question.
Is this code correct in internal/number/decimal.go:385?

```
if scale > len(scales) { 
         mult = math.Pow(10, float64(scale))
} else {
         mult = scales[scale] //out of bound, isn't it?
}
```

Is else branch unreachable or there is some trick with go slices?

**Comment by ianlancetaylor** [comment]
CC @mpvl
