### ISSUE TITLE
redundant assignment statement for _,file := range files { file := file ...}

### ISSUE THREAD

**Issue by XiaodongLoong** [golang/go#42141]
There is a redundant assignment statement, I think it is no meaning:
https://github.com/golang/go/blob/4c7a18d74ae4d574313c01e95de66be06e3a3e82/src/cmd/go/script_test.go#L52

**Comment by pierrec** [comment]
It is not redundant, it makes a copy of the file for the parallel test below.
See [concurrency](https://golang.org/doc/effective_go.html#concurrency).

**Comment by martisch** [comment]
Note there is a long standing issue to detect the type of error that would be the case if this needed copy was not made. https://github.com/golang/go/issues/16520

I assume also the race detector would complain if the copy was not there.

**Comment by XiaodongLoong** [comment]
Thanks, I have gained knowledge!

**Comment by XiaodongLoong** [comment]
I write some code to test this issue:
```
package main

import "fmt"

func main() {
        a := []int{1,2,3}
        for x := range a {
                fmt.Println(x)
                fmt.Println(&x)
                x := x
                fmt.Println(&x)
        }
}
```
test `logs:`
$ go run main.go 
0
0xc00007e010
0xc00007e030
1
0xc00007e010
0xc00007e040
2
0xc00007e010
0xc00007e050
