### ISSUE TITLE
x/pkgsite: change "BUGs" heading to "Bugs"

### ISSUE THREAD

**Issue by julieqiu** [golang/go#42153]
At the moment, the heading for the bugs section is "BUGs". As an example, see https://pkg.go.dev/sync/atomic#pkg-note-BUG:

![image](https://user-images.githubusercontent.com/5943521/96933123-e92e4500-148d-11eb-8342-00990bda0fb3.png)

The heading should be "Bugs", which is what is displayed on https://golang.org/pkg/sync/atomic/#pkg-note-BUG:

![image](https://user-images.githubusercontent.com/5943521/96933164-fa775180-148d-11eb-9c58-70a9b33089fc.png)

The URL should not change.

**Comment by jeromedoucet** [comment]
Hello ! I will take this one if everyone agrees.

**Comment by julieqiu** [comment]
Please do, thank you!

Here are the places that need to be changed:

Current page:
- https://github.com/golang/pkgsite/blob/4309cd76ea71e3ae3b6cbfb46b3670fd44c734c1/internal/godoc/dochtml/legacy_body.go#L48
https://github.com/golang/pkgsite/blob/4309cd76ea71e3ae3b6cbfb46b3670fd44c734c1/internal/godoc/dochtml/legacy_body.go#L178
- https://github.com/golang/pkgsite/blob/4309cd76ea71e3ae3b6cbfb46b3670fd44c734c1/internal/godoc/dochtml/legacy_sidenav.go#L88

Redesigned page (see #41587 for context):
- https://github.com/golang/pkgsite/blob/4309cd76ea71e3ae3b6cbfb46b3670fd44c734c1/internal/godoc/dochtml/template_body.go#L53
- https://github.com/golang/pkgsite/blob/4309cd76ea71e3ae3b6cbfb46b3670fd44c734c1/internal/godoc/dochtml/template_body.go#L185
- https://github.com/golang/pkgsite/blob/4309cd76ea71e3ae3b6cbfb46b3670fd44c734c1/internal/godoc/dochtml/template_sidenav.go#L95

It might make sense to make the change here, 
https://github.com/golang/pkgsite/blob/4309cd76ea71e3ae3b6cbfb46b3670fd44c734c1/internal/godoc/dochtml/dochtml.go#L152

But this will need a bit of investigation.

**Comment by jeromedoucet** [comment]
Thanks for the tips !

**Comment by jeromedoucet** [comment]
I find two more places that maybe need to be changed (inside a `<select>`).

- for the current page => https://github.com/golang/pkgsite/blob/4309cd76ea71e3ae3b6cbfb46b3670fd44c734c1/internal/godoc/dochtml/legacy_sidenav.go#L150
- for the redesigned => https://github.com/golang/pkgsite/blob/4309cd76ea71e3ae3b6cbfb46b3670fd44c734c1/internal/godoc/dochtml/template_sidenav.go#L151

Can you confirm me that this need to be changed too ?

**Comment by julieqiu** [comment]
Yup, good catch!
