### ISSUE TITLE
cmd/compile: improved error for "too many arguments for return"

### ISSUE THREAD

**Issue by smoogle** [golang/go#4215]
<pre>1. What is a short input program that triggers the error?

func foo {
 return 1
}

2. What is the full compiler output?

too many arguments to return

3. What version of the compiler are you using?  (Run it with the -V flag.)

1.0.2

It would be nice if the above error message suggested you forgot the return type, and
potentially even suggested what it should be.</pre>

**Comment by odeke-em** [comment]
I've mailed CL https://go-review.googlesource.com/#/c/25156.
