### ISSUE TITLE
x/build: add linux-arm64-hisilicon builder

### ISSUE THREAD

**Issue by AllenX2018** [golang/go#42163]
OP: https://groups.google.com/g/golang-dev/c/Y6gDLcp7CcM

I'm a developer from Hisilicon and we want add 2 linux/arm64 builders to Go build system for our consumers who use Huawei cloud.

https://www.huaweicloud.com/intl/en-us/pricing/index.html?tab=detail#/ecs 
 
overview of the machines:

Kunpeng  920
ISA: arm64 v8
OS: openeuler (a distro of Linux )

my email: hvn00b@gmail.com (Please forgive we can't show our company email address to public)

Thanks

@cagedmantis @toothrot @dmitshur

**Comment by cherrymui** [comment]
I think we already have good linux-arm64 builder coverage. Adding more builders that are not maintained by the Go team comes with more complexity than benefit.

**Comment by AllenX2018** [comment]
@cherrymui OK

Please be free to reopen this issue if linux/arm64 builder is needed.
