### ISSUE TITLE
package of "golang.org/x/crypto/acme/autocert"

### ISSUE THREAD

**Issue by kuokuanyo** [golang/go#42164]
Hello, I have a question and want to ask you. When I use the "golang.org/x/crypto/acme/autocert" package in go and call http.Serve(autocert.NewListener("www.hilive.com.tw "), r) We use https certificate for our domain, when I use this syntax and then CentOS enables the service, it happens continuously" 2020/10/23 09:17:10 http: TLS handshake error from 117.135.87.191:5481 : Acme / autocert: The host "tw.trojan.scloudlab.xyz" is not configured in HostWhitelist. Such an error, may I ask where the problem occurred?
I originally executed the same syntax on another centos host but no such error occurred.
![image](https://user-images.githubusercontent.com/53857275/96986519-52788b80-1554-11eb-81ba-6da7ac026c8e.png)

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
