### ISSUE TITLE
x/pkgsite: jump to identifier no longer working

### ISSUE THREAD

**Issue by myitcv** [golang/go#42167]
### What is the URL of the page with the issue?

https://pkg.go.dev/cuelang.org/go@v0.3.0-alpha4/cue

### What is your user agent?

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.59 Safari/537.36
</pre>

### Screenshot

n/a

### What did you do?

Pressed `f` and `F`

### What did you expect to see?

The "jump to identifier" dialog

### What did you see instead?

Nothing

**Comment by jamalc** [comment]
The change that caused this issue has been reverted.
