### ISSUE TITLE
x/pkgsite: COPYING.md file blocks rendering of github.com/ProtonMail/proton-bridge

### ISSUE THREAD

**Issue by kortschak** [golang/go#42175]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/mod/github.com/ProtonMail/proton-bridge@v1.3.3
 
### What did you do?
 

Navigate to link above and browse.
 
 
### What did you expect to see?
 
Docs and packages and a visible README.
 
### What did you see instead?

Pages blocked by LICENSE restrictions.

This is due I think to the COPYING.md file which is taken to be a LICENSE but is instead a notice about licensing and third party licenses in the repo. I don't know what the best approach is here, perhaps asking them to rename that file?

**Comment by jamalc** [comment]
That's exactly right about the COPYING.md file. Requesting that the file be renamed is the best approach.
