### ISSUE TITLE
release: look for CLs with +2 but no Trust+1

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#42176]
As part of the transition to the release freeze, we should look for CLs that have a +2 but no Trust+1.  Those CLs should all be reviewed for Trust+1 purposes, and, if no problems are found, submitted.

CC @dmitshur @cagedmantis @toothrot

**Comment by dmitshur** [comment]
@toothrot has previously suggested this Gerrit search query:

https://go-review.googlesource.com/q/label:Code-Review%253D%252B2+label:Untrusted%253Dreject

There are 3.5~ pages of results (at 25 CL/page) at this time.

**Comment by dmitshur** [comment]
https://go-review.googlesource.com/q/label:Code-Review%253D%252B2+label:Untrusted%253Dreject+repo:go+branch:master narrows it down to just the main repository, main branch. There are 58 matching open CLs.

**Comment by dmitshur** [comment]
Many CLs have been submitted since last time. I've looked over some of them and reviewed for Trust where it was the only missing thing. By now, the same query finds 15 CLs (down from 58). Many of those 15 have remaining work or need attention from someone, although maybe not all.

**Comment by dmitshur** [comment]
The query above (slightly modified to additionally filter out CLs that are waiting on author or have a -2 review) by now finds only 8 CLs. Of those, 6 are sent by people who have the ability to grant Trust+1 themselves. The other 2 were being actively evaluated for readiness for submission.

Given we're in the freeze and the week to submit in-flight changes has passed, I don't think there's more to do here.

**Comment by cagedmantis** [comment]
I was hoping that this issue would become a recurring issue that we kept open for each release.

**Comment by dmitshur** [comment]
@cagedmantis I was previously thinking this was needed for the Go 1.16 release only because the Trust requirement is new, and some CLs that could previously be submitted now needed an extra vote. But it does seem such a situation can continue to happen in the future if a CL is sent by someone without ability to self-Trust+1, and reviewed only with a single Core-Review+2. Thanks for pointing this out.

Maybe in the future this can be factored out to happen continuously as part of normal code review and not need to be tied as closely to the start of the release freeze, but I guess it'll work to make this issue recurring until that happens.

**Comment by ianlancetaylor** [comment]
Just a note that this is a steady ongoing problem that we ought to address somehow.  It doesn't have anything to do with releases.  We have a somewhat patchy and unreliable system for getting reviewers to look at CLs, but we don't have any system at all for getting CLs that have a +2 over the finish line to submission.

**Comment by dmitshur** [comment]
Ian came up with an idea for us to add a weekly task for someone on the Go team (we have a weekly rotation we can make use of) to look for CLs that have been reviewed but just need trust to become submittable, and try to review them for trust.

https://go-review.googlesource.com/q/label:Code-Review%253D%252B2+label:Untrusted%253Dreject+-label:Code-Review%253D-2+-hashtag:wait-author+-age:1w finds CLs with CR+2 but no trust (without CR-2 or wait-author hashtag) that are no more than a week old. Perhaps it's a good place to look for the purpose of a weekly task. CC @toothrot.

**Comment by toothrot** [comment]
We're actively looking for these issues as a weekly task. We can close this unless it becomes an issue again.
