### ISSUE TITLE
syscall/js: ValueOf should not panic if the underlying type(kind) is supported

### ISSUE THREAD

**Issue by mihaiav** [golang/go#42188]
### What version of Go are you using (`go version`)?

<pre>
$ go version devel +dd150176c3 Fri Jul 3 03:31:29 2020 +0000 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
darwin x64
</pre></details>

### What did you do?
package main
 import "syscall/js"

func main(){
 type X string
  x := X("hello")
  v := js.ValueOf(x)
}

### What did you expect to see?
x being converted to a js value. 

### What did you see instead?
panic: ValueOf: invalid value

I believe this is due the fact that the string value passed on is a typed.  Therefore this is a feature/improvement request to make ValueOf accept values whose underlying type matches the accepted types.

**Comment by dmitshur** [comment]
CC @neelance.

**Comment by neelance** [comment]
This would require a dependency from `syscall/js` to `reflect`, which is at least something that we definitely want to avoid or maybe even impossible to do.

**Comment by dmitshur** [comment]
@neelance Have you also considered [`internal/reflectlite`](https://pkg.go.dev/internal/reflectlite)?

**Comment by neelance** [comment]
At first glance it seems like it wouldn't be able to turn `type X string` into a plain `string`.

**Comment by neelance** [comment]
I'll close this issue for now, since it is very unlikely to happen due to the necessary `reflect` dependency. I also think that since `syscall/js` is a very low-level package, there need to be intermediate layers that hide it from user code and offer a nicer interface than `syscall/js` ever could.
