### ISSUE TITLE
"golang.org/x/crypto/acme/autocert" error

### ISSUE THREAD

**Issue by kuokuanyo** [golang/go#42203]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\User\AppData\Local\go-build
set GOENV=C:\Users\User\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\User\go\src
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\User\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\User\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\User\AppData\Local\Temp\go-build854140990=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
When I use the "golang.org/x/crypto/acme/autocert" package in go and call http.Serve (autocert.NewListener("www.hilive.com.tw"), r) to use https for our domain Credentials, when I use this syntax and then centos to enable the service, it happens continuously" 2020/10/23 09:17:10 http: TLS handshake error from 117.135.87.191:5481: acme/autocert: HostWhitelist is not configured "tw .trojan.scloudlab.xyz". Such an error, where did the problem occur?

![image](https://user-images.githubusercontent.com/53857275/97142851-70383180-179c-11eb-9874-36fd4dbfecde.png)
![image](https://user-images.githubusercontent.com/53857275/97142860-7a5a3000-179c-11eb-9a36-d576e26684af.png)

### What did you expect to see?
"Http: TLS handshake error from 58.247.22.169:14692: acme/autocert: host "tw.trojan.scloudlab.xyz" not configured in HostWhitelist" error will no longer appear

**Comment by kuokuanyo** [comment]
> ### What version of Go are you using (`go version`)?
> $ go version
> ![image](https://user-images.githubusercontent.com/53857275/97142694-1c2d4d00-179c-11eb-9029-f39e841a29cc.png)
> 
> ### Does this issue reproduce with the latest release?
> yes
> 
> ### What operating system and processor architecture are you using (`go env`)?
> `go env` Output
> 
> $ go env
> ![image](https://user-images.githubusercontent.com/53857275/97142766-41ba5680-179c-11eb-925b-07dab7311c61.png)
![image](https://user-images.githubusercontent.com/53857275/97144160-ea69b580-179e-11eb-9f01-6dade06a4674.png)

> ### What did you do?
> When I use the "golang.org/x/crypto/acme/autocert" package in go and call http.Serve (autocert.NewListener("www.hilive.com.tw"), r) to use https for our domain Credentials, when I use this syntax and then centos to enable the service, it happens continuously" 2020/10/23 09:17:10 http: TLS handshake error from 117.135.87.191:5481: acme/autocert: HostWhitelist is not configured "tw .trojan.scloudlab.xyz". Such an error, where did the problem occur?
> 
> ![image](https://user-images.githubusercontent.com/53857275/97142851-70383180-179c-11eb-9874-36fd4dbfecde.png)
> ![image](https://user-images.githubusercontent.com/53857275/97142860-7a5a3000-179c-11eb-9a36-d576e26684af.png)
> 
> ### What did you expect to see?
> "Http: TLS handshake error from 58.247.22.169:14692: acme/autocert: host "tw.trojan.scloudlab.xyz" not configured in HostWhitelist" error will no longer appear
> 
> ### What did you see instead?

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
