### ISSUE TITLE
dl: embed directive not working with gotip

### ISSUE THREAD

**Issue by carlmjohnson** [golang/go#42213]
### What version of Go are you using (`go version`)?

<pre>
$ gotip version
go version devel +c800222 Sun Oct 25 20:56:22 2020 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ gotip env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/adhoc/bin"
GOCACHE="/Users/adhoc/Library/Caches/go-build"
GOENV="/Users/adhoc/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/adhoc/src/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/adhoc/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/adhoc/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/adhoc/sdk/gotip/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/var/folders/p7/jc4qc9n94r3f6ylg0ssh1rq00000gs/T/tmp.eGCNfh4R/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p7/jc4qc9n94r3f6ylg0ssh1rq00000gs/T/go-build525352014=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Run this:

example.txt: "abc123"

go.mod:

```
module example

go 1.16
```

example.go:

```go
package main

import (
	"fmt"
	_ "embed"
)

func main() {
	//go:embed example.txt
	var x string
	fmt.Println(x)
}
```

### What did you expect to see?
abc123

### What did you see instead?

```
$ gotip run .
# example
./example.go:9:4: invalid go:embed: build system did not supply embed configuration
```

- - - -

Is this just a temporary error as development proceeds, or does gotip need to be modified to work with embeds?

**Comment by ALTree** [comment]
What makes you think that the work on `embed` is done? 

[This CL](https://go-review.googlesource.com/c/go/+/243945/) hasn't been merged yet, so I don't think you can expect `embed` to work on tip right now.

**Comment by carlmjohnson** [comment]
Okay. Could just be too early then. I saw that the embed package is there and wanted to test it out. Will close until more CLs are closed.
