### ISSUE TITLE
x/sys/windows/svc: test failures with "The specified service has been marked for deletion."

### ISSUE THREAD

**Issue by bcmills** [golang/go#42211]
```
--- FAIL: TestExample (0.54s)
    svc_test.go:88: CreateService(myservice) failed: The specified service has been marked for deletion.
FAIL
FAIL	golang.org/x/sys/windows/svc	0.559s
…
--- FAIL: TestMyService (0.52s)
    mgr_test.go:258: UpdateConfig failed: The specified service has been marked for deletion.
FAIL
FAIL	golang.org/x/sys/windows/svc/mgr	0.547s
```

[2020-10-18T23:04:17-eeed37f/windows-amd64-longtest](https://build.golang.org/log/245b31c31021a56934a96c833172117b2fc91884)
[2020-10-09T02:54:20-dfb3f7c/windows-amd64-longtest](https://build.golang.org/log/f577a0bf76780553fbabe85a0bac4539bb73663b)
[2020-08-19T03:55:08-9a32b3a/windows-amd64-longtest](https://build.golang.org/log/24e3520efc4d4a951cd36791378f09dd2502244d)
[2020-08-17T15:53:16-9781c65/windows-amd64-longtest](https://build.golang.org/log/054317da9e4b661b5a6221a4138c8045b449a170)
[2020-08-17T08:59:35-3ff754b/windows-amd64-longtest](https://build.golang.org/log/f55fc6cfc9c1ee377f537efe8fc96a5f50751c06)
[2019-11-20T15:59:48-bd43791/windows-amd64-longtest](https://build.golang.org/log/19efa1a6e99657768291ded9bb2bcb35077193bd)
[2019-11-20T13:05:36-6bfc516/windows-amd64-longtest](https://build.golang.org/log/a1ddbf5b6da6062e186a2902785a944bdd61d8a6)
[2019-11-19T19:55:28-f068ffe/windows-amd64-longtest](https://build.golang.org/log/df578e49294e77c24fed0b4c962e704f274d7d4d)
[2019-11-19T06:07:38-e882bf8/windows-amd64-longtest](https://build.golang.org/log/8b936fcf4783e3ad1dce2e2d11265468c1c899c7)
[2019-11-18T13:31:27-cf1e2d5/windows-amd64-longtest](https://build.golang.org/log/7515f39f0f1e2896e23ca6a409fce16b36aa1fb7)
[2019-11-18T07:38:50-2f86c98/windows-amd64-longtest](https://build.golang.org/log/5b9c735c51f3aec992349c7eab6ac9f01d069104)
[2019-11-15T15:19:21-52ab431/windows-amd64-longtest](https://build.golang.org/log/13194b44315944a2d877c1452ac618c6786d7e9b)
[2019-11-05T14:28:33-ac3223d/windows-amd64-longtest](https://build.golang.org/log/b330ec3333accfaf8c3b0f0957ba3b15b7bf6482)
[2019-10-29T15:55:21-f43be2a/windows-amd64-longtest](https://build.golang.org/log/7578d278d4bc3a597568558bbf0037ab5923abd2)
[2019-10-25T09:01:51-53bf42e/windows-amd64-longtest](https://build.golang.org/log/4d6f7fde28770e7997676274e3743667a4407e4d)
[2019-10-25T02:14:31-6c3a3bf/windows-amd64-longtest](https://build.golang.org/log/1942f5f0db1e943961f472de008524965b91c49b)
[2019-10-24T07:30:52-e66fe6e/windows-amd64-longtest](https://build.golang.org/log/cbfe46cfeb2b8c0c3b647f4c5a056c31e3e7dde7)
[2019-10-23T14:50:28-b69606a/windows-amd64-longtest](https://build.golang.org/log/e414072d2f9f3c57022358b54874a99e54296cd1)
[2019-10-22T10:09:44-742c48e/windows-amd64-longtest](https://build.golang.org/log/3d3987d1c190e93b9213da18432915b3d27ac3f3)

CC @alexbrainman @zx2c4

**Comment by networkimprov** [comment]
cc @mattn

**Comment by alexbrainman** [comment]
@bcmills thank you for creating this issue.

The error message is ERROR_SERVICE_MARKED_FOR_DELETE returned from DeleteService

https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-deleteservice

Interestingly, when we see a failure, both golang.org/x/sys/windows/svc and golang.org/x/sys/windows/svc/mgr tests fail. To me this sounds like package tests interfere with each other. In fact both test install the same service (same name and source). I wonder, if golang.org/x/sys/windows/svc and golang.org/x/sys/windows/svc/mgr run at the same time. Is this possible? If yes, then this can certainly happen.

I have seen this error before DeleteService was run while service process was still running.

I have also run

for /l %i in (1 1 10) do go test -count=1 golang.org/x/sys/windows/svc/...

and this command runs fine.

```
c:\Users\Alex\dev\src\golang.org\x\sys\windows\svc>go test -count=1 golang.org/x/sys/windows/svc/...
ok      golang.org/x/sys/windows/svc    3.475s
?       golang.org/x/sys/windows/svc/debug      [no test files]
ok      golang.org/x/sys/windows/svc/eventlog   0.057s
?       golang.org/x/sys/windows/svc/example    [no test files]
ok      golang.org/x/sys/windows/svc/mgr        0.108s

c:\Users\Alex\dev\src\golang.org\x\sys\windows\svc>go test -count=1 golang.org/x/sys/windows/svc/...
ok      golang.org/x/sys/windows/svc    3.508s
?       golang.org/x/sys/windows/svc/debug      [no test files]
ok      golang.org/x/sys/windows/svc/eventlog   0.061s
?       golang.org/x/sys/windows/svc/example    [no test files]
ok      golang.org/x/sys/windows/svc/mgr        0.056s

c:\Users\Alex\dev\src\golang.org\x\sys\windows\svc>go test -count=1 golang.org/x/sys/windows/svc/...
ok      golang.org/x/sys/windows/svc    3.410s
?       golang.org/x/sys/windows/svc/debug      [no test files]
ok      golang.org/x/sys/windows/svc/eventlog   0.112s
?       golang.org/x/sys/windows/svc/example    [no test files]
ok      golang.org/x/sys/windows/svc/mgr        0.069s
```

But, if I interrupt my test by pressing Ctrl+C, this happens

```
c:\Users\Alex\dev\src\golang.org\x\sys\windows\svc>go test -count=1 golang.org/x/sys/windows/svc/...
exit status 3221225786
FAIL    golang.org/x/sys/windows/svc    1.339s
?       golang.org/x/sys/windows/svc/debug      [no test files]
ok      golang.org/x/sys/windows/svc/eventlog   0.076s

c:\Users\Alex\dev\src\golang.org\x\sys\windows\svc>
```

and I can see service process is still running. I used Process Explorer

https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

and I know service executable is called a.exe

![image](https://user-images.githubusercontent.com/9796621/97931326-7b551800-1dc1-11eb-9a1b-38bebf659a8f.png)

And indeed, if I start my test again, I see the error.

```
c:\Users\Alex\dev\src\golang.org\x\sys\windows\svc>for /l %i in (1 1 10) do go test -count=1 golang.org/x/sys/windows/svc/...

c:\Users\Alex\dev\src\golang.org\x\sys\windows\svc>go test -count=1 golang.org/x/sys/windows/svc/...
--- FAIL: TestExample (0.58s)
    svc_test.go:82: Delete failed: The specified service has been marked for deletion.
FAIL
FAIL    golang.org/x/sys/windows/svc    0.633s
?       golang.org/x/sys/windows/svc/debug      [no test files]
ok      golang.org/x/sys/windows/svc/eventlog   0.060s
?       golang.org/x/sys/windows/svc/example    [no test files]

c:\Users\Alex\dev\src\golang.org\x\sys\windows\svc>
```

But, if I stop service with

`sc stop myservice`

I can see a.exe process disappears. And I can run my test again.

```
c:\Users\Alex\dev\src\golang.org\x\sys\windows\svc>for /l %i in (1 1 10) do go test -count=1 golang.org/x/sys/windows/svc/...

c:\Users\Alex\dev\src\golang.org\x\sys\windows\svc>go test -count=1 golang.org/x/sys/windows/svc/...
ok      golang.org/x/sys/windows/svc    3.500s
?       golang.org/x/sys/windows/svc/debug      [no test files]
ok      golang.org/x/sys/windows/svc/eventlog   0.087s
?       golang.org/x/sys/windows/svc/example    [no test files]
ok      golang.org/x/sys/windows/svc/mgr        0.081s

c:\Users\Alex\dev\src\golang.org\x\sys\windows\svc>go test -count=1 golang.org/x/sys/windows/svc/...
ok      golang.org/x/sys/windows/svc    3.583s
?       golang.org/x/sys/windows/svc/debug      [no test files]
ok      golang.org/x/sys/windows/svc/eventlog   0.060s
?       golang.org/x/sys/windows/svc/example    [no test files]
ok      golang.org/x/sys/windows/svc/mgr        0.067s
```

Alex

**Comment by bcmills** [comment]
> I wonder, if golang.org/x/sys/windows/svc and golang.org/x/sys/windows/svc/mgr run at the same time. Is this possible?

Yes, tests of different packages can and often do run at the same time.

**Comment by zx2c4** [comment]
Using a random service name might help

**Comment by alexbrainman** [comment]
> Yes, tests of different packages can and often do run at the same time.

I am surprised. Are you talking about builders or `go test` command in general?

> Using a random service name might help

Good half-advice. I will rename service in one of the tests - that should be good enough. I don't like the `random` bit - it is easier to manage / write code when things have known predefined names.

Thank you.

Alex

**Comment by bcmills** [comment]
> > Yes, tests of different packages can and often do run at the same time.
>
> I am surprised. Are you talking about builders or `go test` command in general?

Both? Note that it is also possible for a user to run `go test` on a package multiple times simultaneously. For example, I often run `go test -short ./...` in one terminal and `go test -race ./...` simultaneously in another. The `golang.org/x/...` tests should be written in such a way that they also reliably pass when run in that way.

**Comment by bcmills** [comment]
(The `-p` flag controls how many test binaries a single invocation of `go test` can run in parallel; see https://tip.golang.org/cmd/go/#hdr-Compile_packages_and_dependencies.)

**Comment by alexbrainman** [comment]
> For example, I often run `go test -short ./...` in one terminal and `go test -race ./...` simultaneously in another. 

I don't do that.

> The `golang.org/x/...` tests should be written such that they reliably pass when run that way.

No argument from me.

> The `-p` flag controls how many test binaries a single invocation of `go test` can run in parallel;

Sure. I hardly ever use anything more than `go test`.

Alex
