### ISSUE TITLE
pkg.go.dev: remove github.com/sid-agrawal/samplebankapi

### ISSUE THREAD

**Issue by sid-agrawal** [golang/go#42219]
### What is the URL of the page with the issue?
 github.com/sid-agrawal/samplebankapi
 
 
### What is your user agent?
 

 NA
 
 
### Screenshot
 

 NA
 
 
### What did you do?
 

 NA
 
 
### What did you expect to see?
 NA
 
 
### What did you see instead?
NA

**Comment by dmitshur** [comment]
Hi @sid-agrawal, can you please confirm if this is a request to remove the `github.com/sid-agrawal/samplebankapi` module from https://pkg.go.dev?

CC @jamalc.

**Comment by sid-agrawal** [comment]
Yes. Confirmed.

**Comment by jamalc** [comment]
Done.
