### ISSUE TITLE
cmd/go: do not skip the cmd/go tests for linux/mips64le

### ISSUE THREAD

**Issue by XiaodongLoong** [golang/go#42223]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.3 linux/mips64le
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="mips64le"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="mips64le"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_mips64le"
GCCGO="gccgo"
GOMIPS64="hardfloat"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/usr/local/go/src/cmd/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -mabi=64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build999960069=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I run cmd/go tests on linux/mips64le platform, the cmd/go tests all skiped.
```
# go test -test.v cmd/go -run=Script/ -work -count=1
WORK=/tmp/go-build534713729 === RUN TestScript
script_test.go:42: skipping external tests on linux/mips64le
--- SKIP: TestScript (0.00s)
PASS
ok cmd/go 6.613s
```

### What did you expect to see?
The cmd/go tests all can run and  all get "PASS" result on linux/mips64le.

**Comment by ianlancetaylor** [comment]
For the record, we started skipping them in https://golang.org/cl/33425.  We skip them because the boards we were using are slow, and in general these tests act the same on all targets, so running them on multiple targets didn't help coverage.

But I think it would be reasonable to have some way to actually run them.

CC @bcmills @jayconrod

**Comment by XiaodongLoong** [comment]
https://farmer.golang.org/builders#host-linux-mipsle-mengzhuo
The builder(host-linux-mipsle-mengzhuo) is a 3A4000(2.0Ghz/47 bit VMA) box and it runs well on Linux/mips64le by far. It seems enough for the architecture coverage.

https://groups.google.com/g/golang-dev/c/p_4y1rxhoe4/m/keSRwlYvAgAJ

**Comment by cherrymui** [comment]
The builder isn't fast enough that we want to run more tests on it. Also, as @ianlancetaylor said, it doesn't help much to enable this test on this particular builder.

I agree with @ianlancetaylor that there probably should be a way to actually run the test on demand.

**Comment by bcmills** [comment]
I think the `skipExternal = true` cases in `func init` should be moved into the `testenv.Builder() != ""` condition.

I agree that we still don't want to run these tests on the Go project's builders, but we should not assume that our builders are the only ones running the tests on these platforms.

**Comment by bcmills** [comment]
Or, at the very least, perhaps we should use `skipExternal = testing.Short()` instead of `skipExternal = true`. That way, users can indicate their willingness to wait via the `-short` flag.
