### ISSUE TITLE
Go DOC benchmark fails to start

### ISSUE THREAD

**Issue by GUITERII** [golang/go#42222]
code copied from : benchmark_test.go
go version go1.15.2 linux/amd64

https://golang.org/src/context/benchmark_test.go?h=maxprocs

execute without error on Linux manjaro but returns no visible value : nothing printed() !!!
failed to start...
thanks

**Comment by davecheney** [comment]
@GUITERII thank you for raising this issue. Can you please complete [the issue](https://github.com/golang/go/blob/master/.github/ISSUE_TEMPLATE) template
