### ISSUE TITLE
cmd/go: include file name in error message for bad import

### ISSUE THREAD

**Issue by gopherbot** [golang/go#4223]
by **peter.waller**:

<pre>Mailing list discussion is here:

<a href="https://groups.google.com/forum/?fromgroups=#">https://groups.google.com/forum/?fromgroups=#</a>!topic/golang-dev/4oYo21jEGuU

At maximum verbosity, `go get` does not give enough information as to what is causing
the failure if it encounters an invalid import. Ideally, it would always report the
package/file/line number where the invalid import is located. Otherwise it could be
buried somewhere deep in a dependency tree.

Example:

   $ go get -d -v -n github.com/go-gl/...
    import &quot;sdl&quot;: import path doesn't contain a slash
    package sdl: unrecognized import path &quot;sdl&quot;

There is something in the code that raises this error talking about the error detail
being irrelevant. I don't understand why.

<a href="http://golang.org/src/cmd/go/vcs.go#L322">http://golang.org/src/cmd/go/vcs.go#L322</a></pre>

**Comment by ysmolsky** [comment]
Example in the topic is not reproducible. So I made this:
```
% go get -d -v -n github.com/ysmolsky/import-error/...
github.com/ysmolsky/import-error (download)
# cd /Users/thorn/go/src/github.com/ysmolsky/import-error; git sync/update
package github.com/ysmolsky/import-error/t1
	imports sdl: unrecognized import path "sdl" (import path does not begin with hostname)
```
Reported error is somewhat better. It tells the package where problem happened. But it does not tell the file/line.

**Comment by matloob** [comment]
GOPATH go get is no longer supported. As of Go 1.24, if we try to do a `go get` that has a bad import, we get the following:

```
go: example.com/baz imports
	sdl: package sdl is not in std (/Users/matloob/devgo/src/sdl)
```

This should now be tracked in #41688, which is a newer issue that tracks adding line numbers to the import stacks printed by (*loadPkg).stackText. See specifically Jay's comment https://github.com/golang/go/issues/41688#issuecomment-754963172
