### ISSUE TITLE
x/tools/go/packages: unexpected test failure TestOverlayChangesPackageName

### ISSUE THREAD

**Issue by katiehockman** [golang/go#42234]
The TryBots are failing in https://go-review.googlesource.com/c/go/+/265078 on the TestOverlayChangesPackageName test, as well as other various gopls tests. 

The full failure can be seen here: https://storage.googleapis.com/go-build-log/f32b11d4/linux-amd64_01b6165f.log

The error starts out:

```
--- FAIL: TestOverlayChangesPackageName (0.09s)
    --- FAIL: TestOverlayChangesPackageName/GOPATH (0.04s)
        overlay_test.go:45: failed to load: unsupported version of go: exit status 2: flag provided but not defined: -overlay
            usage: go list [-f format] [-json] [-m] [list flags] [build flags] [packages]
            Run 'go help list' for details.
    --- FAIL: TestOverlayChangesPackageName/Modules (0.06s)
        overlay_test.go:45: failed to load: unsupported version of go: exit status 2: flag provided but not defined: -overlay
            usage: go list [-f format] [-json] [-m] [list flags] [build flags] [packages]
            Run 'go help list' for details.
```

This is a one line CL which is just a revert to add a blank identifier import back into x509.go. Is there something wrong with the change, or is there something wrong with the test? I ran it twice and it failed both times, so it doesn't seem to be a flake.

**Comment by heschik** [comment]
Please rebase your CL. See https://go-review.googlesource.com/c/tools/+/263984/comment/db5f9e00_6448a8a7/.

**Comment by heschik** [comment]
@stamblerre

**Comment by katiehockman** [comment]
Thanks, that resolved it.
