### ISSUE TITLE
syscall: mksyscall.pl broken on Darwin/OS X

### ISSUE THREAD

**Issue by xylo04** [golang/go#42241]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/chris/Library/Caches/go-build"
GOENV="/Users/chris/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/chris/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/chris/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/chris/git/pat/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zt/9q4fnj295_x8c94qllxhs34w0000gn/T/go-build329619136=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://github.com/la5nta/pat/pull/222 - attempting to update our project's dependencies, but OS X has apparently deprecated the symbol `unix.SYS_IOCTL` that our serial I/O library uses. The serial library uses the `mksyscall.pl` to generate its system calls.

<pre>
git clone --branch update-deps https://github.com/xylo04/pat.git && cd pat
go get -u
./make.bash
</pre>

### What did you expect to see?
<pre>
Building Pat v0.10.0...
Enjoy!
</pre>

### What did you see instead?
<pre>
# github.com/albenik/go-serial/v2
../../go/pkg/mod/github.com/albenik/go-serial/v2@v2.0.0/zsyscall_darwin.go:16:27: undefined: unix.SYS_IOCTL
</pre>

**Comment by ianlancetaylor** [comment]
I don't think we ever really intended to support mksyscall.pl for use in anything other than building the syscall or golang.org/x/sys/unix packages themselves.

That said, are you passing the `-darwin` option?

**Comment by xylo04** [comment]
I'm not a maintainer of https://github.com/albenik/go-serial so I'm having a tough time deciphering. However, It looks like I can regenerate their file, and passing the `-darwin` flag to `mksyscall.pl` does generate different bindings without the `SYS_IOCTL` naughty word. Let me see if that fixes the compile issue further up the stack.

**Comment by xylo04** [comment]
Ok, this feels gross but it seems to be working. Does [this PR][1] look like what you'd expect to see?

[1]: https://github.com/albenik/go-serial/pull/17

**Comment by ianlancetaylor** [comment]
Personally I would recommend not running the unsupported mksyscall.pl script, and instead calling the appropriate `IoctlNNN` function from golang.org/x/sys/unix.

**Comment by ianlancetaylor** [comment]
Closing this issue because I don't think there is anything to do on the Go side.  Please comment if you disagree.
