### ISSUE TITLE
futex_wait_queue_me 

### ISSUE THREAD

**Issue by shenmingxing** [golang/go#42242]
i see /proc/xx/stack  , process block ,not print log and connect is ESTABLISHED
[<0>] futex_wait_queue_me+0xbb/0x120
[<0>] futex_wait+0x105/0x260
[<0>] do_futex+0x10f/0x1e0
[<0>] __x64_sys_futex+0x13f/0x170
[<0>] do_syscall_64+0x57/0x190
[<0>] entry_SYSCALL_64_after_hwframe+0x44/0xa9

**Comment by ianlancetaylor** [comment]
Is this a bug report?  Please fill out the bug template.  Please explain exactly what you did, exactly what happened, and what you expected to happen instead.
