### ISSUE TITLE
database/sql: failures in TestTxStmtDeadlock starting Oct. 28

### ISSUE THREAD

**Issue by bcmills** [golang/go#42259]
```
--- FAIL: TestTxStmtDeadlock (0.01s)
    sql_test.go:2835: unexpected error while executing stmt, err: sql: statement is closed
FAIL
FAIL	database/sql	0.624s
```

Possibly due to [CL 250178](https://golang.org/cl/250178) (@tz70s, @odeke-em @kardianos).
(Possibly another deadlock similar to the one fixed in that CL.)

Marking as release-blocker because deadlock and test-regression.

[2020-10-28T19:19:04-bc0d7fd/freebsd-amd64-12_0](https://build.golang.org/log/6143f84b42f5398cddaaa86e6b12a55e33d4e691)
[2020-10-28T16:55:17-d4c1ad8/openbsd-386-64](https://build.golang.org/log/6a15dc10c117ace8ea5399a35cc4bf017444f008)

**Comment by kardianos** [comment]
@bcmills Sorry. My fault. I'll look into ASAP.

**Comment by tz70s** [comment]
Yes sorry was due to error check I didn't aware of, the test was introduced by that CL as well instead of existing regression.
