### ISSUE TITLE
x/pkgsite: replace links to godoc.org in x/* repos

### ISSUE THREAD

**Issue by findleyr** [golang/go#42251]
A number of packages within x/ repos still link to self-documentation hosted on godoc.org (for example: x/tools/cmd/stringer, x/tools/cmd/present).  Given that the plan is to eventually redirect this traffic to pkg.go.dev (https://blog.golang.org/pkg.go.dev-2020), we should proactively update these links to point to pkg.go.dev.

CC @julieqiu

**Comment by julieqiu** [comment]
Related CLs:

https://go-review.googlesource.com/c/oauth2/+/276016
https://go-review.googlesource.com/c/tools/+/275235
https://go-review.googlesource.com/c/website/+/275195

**Comment by julieqiu** [comment]
This should be fixed. Feel free to reopen if anything was missed.
