### ISSUE TITLE
x/pkgsite: add a way to opt in to https://beta.pkg.go.dev/

### ISSUE THREAD

**Issue by myitcv** [golang/go#42260]
### What is the URL of the page with the issue?

https://pkg.go.dev/

### What is your user agent?

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.59 Safari/537.36
</pre>

### Screenshot

n/a

### What did you do?

Visited https://pkg.go.dev/

### What did you expect to see?

I would like to be able to set a cookie/other that allows https://pkg.go.dev/ to in effect be https://beta.pkg.go.dev/, in much the same way that users can opt-in to being redirected to https://pkg.go.dev/ from godoc.

### What did you see instead?

No option to "opt in" to https://beta.pkg.go.dev/

**Comment by julieqiu** [comment]
If anyone is interested in working on this feature, here's the code for how users can opt-in to always being redirected from godoc.org to pkg.go.dev: https://github.com/golang/gddo/blob/721e228c7686d830b5decc691a4dc7e6a6e94888/gddo-server/main.go#L1161
