### ISSUE TITLE
x/tools/gopls: The code in the workspace failed to compile

### ISSUE THREAD

**Issue by hlbbt** [golang/go#42268]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.15
</pre>

### What operating system and processor architecture are you using (`go env`)?
go version go1.15.3 windows/amd64

![image](https://user-images.githubusercontent.com/52640622/97523916-600f9480-19de-11eb-89bd-e4a20a5de062.png)

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
![image](https://user-images.githubusercontent.com/52640622/97524052-b1b81f00-19de-11eb-91e2-a75f358c7dcb.png)

When I write code, I want a code tip, 
If I hit any keypad, vscode would prompt a message in the lower right corner, which is quite annoying
Then I found a way, set `"go.useLanguageServer": false,`  This is not the case at this point 
However, code prompts are slow at this point, very very slow. 

When I changed it `"go.useLanguageServer": true,`  again, The code indicates that the speed is normal and fast,
But, Here's another tip vscode the lower right,Quite annoying 

### What did you expect to see?
![image](https://user-images.githubusercontent.com/52640622/97524499-ce088b80-19df-11eb-9d3e-12deee0289ee.png)

I don't want to see this hint, No problem running the program

**Comment by ianlancetaylor** [comment]
Please cut and paste text as text in the issue report.  Please do not attach images of text.  Ordinary text is much easier to read than images.  Thanks.

**Comment by LinSimmons-bitzh** [comment]
The code in the workspace failed to compile (see the error message below).
If you believe this is a mistake, please file an issue: https://github.com/golang/go/issues/new.
go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- ./]: exit status 1: go: cannot find main module; see 'go help modules'
: packages.Load error

**Comment by heschik** [comment]
To work on a Go project, you need to open the folder of that project as the main VS Code folder. See https://github.com/golang/tools/blob/master/gopls/doc/user.md#the-set-of-workspace-folders. In your case you need to open the `hello` directory.
