### ISSUE TITLE
x/pkgsite: Can't see package on pkg.go.dev but can download via go get

### ISSUE THREAD

**Issue by zachwhaley** [golang/go#42273]
### What is the URL of the page with the issue?
https://pkg.go.dev/github.com/trendmicro/new-release-version/ 
 
### What is your user agent?
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36

 
### Screenshot
![Screen Shot 2020-10-29 at 11 47 36 AM](https://user-images.githubusercontent.com/2996465/97605381-8df3d980-19dc-11eb-8629-2d445ec38aa7.png)

### What did you do?
I'm new to Go in general and I tried to add my package to the pkg.go.dev site.  While trying to do so I hit a number of issues such as, trying to set my first version to v2.0 without denoting this in my module name.  In the process creating a v2 page for my package (see https://pkg.go.dev/github.com/trendmicro/new-release-version/v2) when I actually wanted a v1 page
 
### What did you expect to see?
I believe I've fixed all known issues with my tags and module version and I'm able to successfully download my module via this command

```
GOPROXY=https://proxy.golang.org GO111MODULE=on go get -v -u github.com/trendmicro/new-release-version@v1.0.0
```

Also the proxy URL seems to work https://proxy.golang.org/github.com/trendmicro/new-release-version/@v/v1.0.0.info

But the pkg.go.dev site still says my package is invalid :(

### What did you see instead?
pkg.go.dev thinks my package is invalid.

**Comment by jamalc** [comment]
Hi @zachwhaley, we have reprocessed the module with the issue and now the package is available on the site.
