### ISSUE TITLE
gollvm: how to compile go source with using -mllvm XXX

### ISSUE THREAD

**Issue by wyw900807** [golang/go#42286]
I want to use gollvm to compile go source file and use -mllvm XXX to transfer the additional arguments to LLVM. There is a go source file,

//"hello.go"
package main
import "fmt"
func main() {
   fmt.Println("Hello world")
}

But when I input llvm-goc -mllvm XXX -c hello.go, the console outputs "error: import file 'fmt' not found". However, when I input 
go build -mllvm XXX hello.go , the console outputs "flag provided but not defined". 

Thank you!

**Comment by ianlancetaylor** [comment]
I don't know what the `-mllvm` option does, but try

```
go build -gccgoflags=-mllvm=XXX hello.go
```

**Comment by wyw900807** [comment]
It works. Thank you very much !
