### ISSUE TITLE
x/blog, x/tour, x/talks: {blog,tour,talks}.golang.org are missing redirect from HTTP to HTTPS

### ISSUE THREAD

**Issue by The-Compiler** [golang/go#42281]
When accessing `http://golang.org`, a redirect to HTTPS is made:

```
$ http http://golang.org
HTTP/1.1 302 Found
Content-Length: 42
Content-Type: text/html; charset=utf-8
Date: Thu, 29 Oct 2020 21:47:40 GMT
Location: https://golang.org/
Via: 1.1 google

<a href="https://golang.org/">Found</a>.
```

When doing the same with `http://tour.golang.org`, no such redirect is happening:

```
$ http http://tour.golang.org
HTTP/1.1 200 OK
Cache-Control: private
Content-Encoding: gzip
Content-Length: 882
Content-Type: text/html; charset=utf-8
Date: Thu, 29 Oct 2020 21:48:35 GMT
Server: Google Frontend
Strict-Transport-Security: max-age=31536000; preload
Vary: Accept-Encoding
X-Cloud-Trace-Context: 893d14db0c7307f3d2e69cf2094d46b5

<!doctype html>
<html lang="en" ng-app="tour">
[...]
```

On top of that, the website doesn't actually work when served via HTTP - it's blank and various errors are logged:

![image](https://user-images.githubusercontent.com/625793/97636167-f96b9480-1a38-11eb-82c3-5d61fd15cb88.png)

This isn't a problem for browsers which support [HSTS Preloading](https://hstspreload.org/) - but for [browsers/libraries which don't](https://bugreports.qt.io/browse/QTBUG-88036), this means the website will be broken (and not redirect to the proper HTTPS variant).

This can be reproduced in Firefox by starting it with a new profile (e.g. `mkdir /tmp/ffprofile; firefox --profile /tmp/ffprofile`),
opening `about:config`, setting `network.stricttransportsecurity.preloadlist` to false and then visiting tour.golang.org.

**Comment by dmitshur** [comment]
I've checked and this applies to {blog,talks}.golang.org as well.

All 3 are hosted on App Engine. This is a matter of configuring their respective app.yaml to set "secure: true" for all paths. I'll send CLs for this.

CC @golang/release, @golang/security.

**Comment by dmitshur** [comment]
This is fixed now.
