### ISSUE TITLE
net/url: parseQuery() better support for array parse.

### ISSUE THREAD

**Issue by ainilili** [golang/go#42293]
### What version of Go are you using (`go version`)?

<pre>
$ 1.15.3
</pre>

### Does this issue reproduce with the latest release?
yes
### What did you do?
```go
import (
	"fmt"
	"net/url"
)

func main(){
	query := "params=fo,fu,n%2Cico"
	values, err := url.ParseQuery(query)
	if err != nil{
		panic(err)
	}
	for _, vs := range values{
		for _, v := range vs{
			fmt.Println(v)
		}
	}
}
```
### What did you expect to see?
```powershell
fo
fu
n,ico
```
### What did you see instead?
```powershell
fo,fu,n,ico
```
When an Array parameter is passed by ``URL`` or ``application/ x-www-Form-urlencoded`` mode, many clients will define the request content in a comma-separated way, so can this expectation be met?

**Comment by seankhliao** [comment]
That does not appear to be standard behaviour https://url.spec.whatwg.org/#urlencoded-parsing

And in this case, how would valid values containing commas be preserved?

**Comment by imxyb** [comment]
I also think this is more of a business scenario, not suitable for general use

**Comment by ainilili** [comment]
> That does not appear to be standard behaviour https://url.spec.whatwg.org/#urlencoded-parsing
> 
> And in this case, how would valid values containing commas be preserved?

If a valid value needs to contain a comma, just escape it to ``%2C`` before initiating the request. But then again, it's not standard.

**Comment by ainilili** [comment]
> I also think this is more of a business scenario, not suitable for general use



> > That does not appear to be standard behaviour https://url.spec.whatwg.org/#urlencoded-parsing
> > And in this case, how would valid values containing commas be preserved?
> 
> If a valid value needs to contain a comma, just escape it to `%2C` before initiating the request. But then again, it's not standard.

However, while this practice is not standard, if it becomes standard, it may be possible to request data transfers:
```
tags=a&tags=b&tags=c
```
simplified to:
```
tags=a,b,c
```
Of course, this is just a personal thought. xD

**Comment by ainilili** [comment]
> I also think this is more of a business scenario, not suitable for general use

Well, in order not to break the standards, I should implement this functionality in the application framework layer.
