### ISSUE TITLE
x/pkgsite: prefer directing the user to the same package in the highest tagged major version

### ISSUE THREAD

**Issue by mvdan** [golang/go#42292]
When I navigate to https://beta.pkg.go.dev/mvdan.cc/sh/syntax, clicking on "The highest tagged major version is v3" takes me to https://beta.pkg.go.dev/mvdan.cc/sh/v3, not https://beta.pkg.go.dev/mvdan.cc/sh/v3/syntax.

I guess this is fine as a fallback, if `v3/syntax` doesn't exist as a package. But if the same sub-package exists in the new major version of the module, I think we should directly link there. Otherwise I have to go into "directories" and find it again.

Split off from https://github.com/golang/go/issues/41588#issuecomment-718871174. CC @julieqiu

**Comment by julieqiu** [comment]
If anyone is interested in working on this, we'd love to accept a contribution for this feature!

The current implementation always looks for the highest major version of the module:
https://github.com/golang/pkgsite/blob/98f3bcc459fdc73d18ee7cad633696139c7be97b/internal/postgres/version.go#L110

We could use the `paths.v1_path` column, like in [GetVersionsForPath](https://github.com/golang/pkgsite/blob/67c71896622f8c62206fe21a9498de0e74085af0/internal/postgres/version.go#L59) to determine the highest major version for a package.

**Comment by mvdan** [comment]
> We could use the `paths.v1_path` column, like in [GetVersionsForPath](https://github.com/golang/pkgsite/blob/67c71896622f8c62206fe21a9498de0e74085af0/internal/postgres/version.go#L59) to determine the highest major version for a package.

Hmm, I don't agree there. If I'm in `/v2/foo`, the latest major version of the module is v4, and `/v3/foo` exists but `/v4/foo` does not, I still think we should point the user towards v4 and not v3.

The detail is that the link should be to `/v4/foo` if the package exists there, and if the package does not exist, we can fall back to linking to `/v4`. Falling back to `/v3/foo` seems like a worse option, because then the user might not even notice that v4 is probably what they should use instead.

**Comment by julieqiu** [comment]
> If I'm in `/v2/foo`, the latest major version of the module is v4, and `/v3/foo` exists but `/v4/foo` does not, I still think we should point the user towards v4 and not v3.

@mvdan I agree this should be the behavior. 

My comments in https://github.com/golang/go/issues/42292#issuecomment-719619124 are suggestions for how to get started, in case anyone is interested in working on this issue.

**Comment by Catzkorn** [comment]
Hi @julieqiu & @mvdan 

I'd like to work on this issue, it will be my first contribution to the Go project. Is there anything else I need to do to claim this issue?

**Comment by julieqiu** [comment]
Nope, all yours! Check out the [CONTRIBUTING.md](https://github.com/golang/pkgsite/blob/master/CONTRIBUTING.md) for how to get started. If you have questions, feel free to reach out in the #pkgsite channel on [Gophers slack](https://invite.slack.golangbridge.org).

**Comment by Catzkorn** [comment]
Great! Thank you Julie :)

**Comment by Catzkorn** [comment]
CL for this here: https://go-review.googlesource.com/c/pkgsite/+/274413

Not sure why gobot hasn't linked.
