### ISSUE TITLE
x/build/env/linux-arm64/packet: 8 Packet linux/arm64 machines missing (late-October 2020)

### ISSUE THREAD

**Issue by dmitshur** [golang/go#42304]
https://farmer.golang.org/#health reports:

![image](https://user-images.githubusercontent.com/1924134/97756132-c2e15880-1ad0-11eb-80ce-e3b2fa23d040.png)

<details><br>

```
# "packet" status: Packet linux/arm64 machines
# Notes: https://github.com/golang/build/tree/master/env/linux-arm64/packet
Warn: packet01 missing, not seen for 1h14m46s
Warn: packet02 missing, not seen for 1h14m38s
Warn: packet03 missing, not seen for 1h14m37s
Warn: packet04 missing, not seen for 1h14m38s
Warn: packet05 missing, not seen for 1h14m42s
Warn: packet06 missing, not seen for 1h14m33s
Warn: packet07 missing, not seen for 1h14m43s
Warn: packet08 missing, not seen for 1h14m39s
Error: 8 machines missing, 100% of capacity
```

</details>

This has happened previously (where a restart was required to fix the issue):

- #40261 (last occurrence, 106 days ago)
- #37922
- #37371
- #35708
- #35524
- #32543
- #31112
- etc.

This builder is needed for making releases. Applying Soon label.

CC @golang/release.

**Comment by dmitshur** [comment]
The machine became unresponsive. As in previous occurrences, restarting via Packet UI fixed it.

**Comment by cagedmantis** [comment]
I would like to consider using the linux-arm64-aws builder as the one used for releases.

**Comment by dmitshur** [comment]
@cagedmantis That sounds great! Want to open an issue and send a CL to make us use that builder starting with Go 1.16 Beta 1? See #40563 and [CL 246597](https://golang.org/cl/246597) for precedent.

**Comment by cagedmantis** [comment]
@dmitshur Sounds like a plan.
