### ISSUE TITLE
x/pkgsite: Remove aaronsky/asc-go/asc from pkg.go.dev

### ISSUE THREAD

**Issue by aaronsky** [golang/go#42320]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/aaronsky/asc-go/asc
 
### What is your user agent?
 

 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0 
 
### Screenshot
 

 
<img width="1340" alt="Screen Shot 2020-11-01 at 13 14 21" src="https://user-images.githubusercontent.com/10502938/97810755-2a6be500-1c44-11eb-82b0-9471b6d2f172.png">

 
### What did you do?
 

 
I am the author of package `asc-go`. Would it be possible to remove [aaronsky/asc-go/asc](https://pkg.go.dev/github.com/aaronsky/asc-go/asc)? I have moved and renamed the package to `cidertool/asc-go/asc`, which can be found at https://pkg.go.dev/github.com/cidertool/asc-go/asc. I'm looking to remove it from GoDoc too, though based on the information there I have to send an email to make that happen. 
 
### What did you expect to see?
 
`aaronsky/asc-go/asc` removed from pkg.go.dev, so that `cidertool/asc-go/asc` is the only available listing. 
 
### What did you see instead?

Both versions of the package displayed with roughly equal prominence.

**Comment by jba** [comment]
Done (may still be present for a short time until it expires from the cache).

**Comment by aaronsky** [comment]
Thank you! I can see that the requested package has been taken care of. I appreciate it!

I overlooked that pkg.go.dev is also reflecting my example packages in that repo too. If it isn't too much trouble, could you look at the other packages listed at this page too? ~> https://pkg.go.dev/github.com/aaronsky/asc-go

**Comment by jba** [comment]
So you'd like to remove everything with the prefix `github.com/aaronsky/asc-go`, is that right?

**Comment by aaronsky** [comment]
Yes, that sounds right. The new package source is `github.com/cidertool/asc-go`, and everything at `github.com/aaronsky/asc-go` should be delisted. 

Thank you!

**Comment by jba** [comment]
Done.
