### ISSUE TITLE
context: allow pre-allocation of valueCtx

### ISSUE THREAD

**Issue by RaduBerinde** [golang/go#42329]
In various CockroachDB workloads, `context.WithValue` shows up as a few percentage points in profiles (similar to any other object allocation). In many cases, we also allocate an object for the value that is associated with the context. We would like to consolidate these allocations by embedding `valueCtx` inside a bigger struct, so that we can allocate both objects together.

Note that we can't have our own implementation of `Context` without losing some efficiency because `parentCancelCtx` won't be aware of it.

My proposal is to export the `valueCtx` type (or an alias) and provide a method or `WithValue` variant to initialize it. Would this kind of addition to the API be acceptable? (I can post the change if yes)

**Comment by zikaeroh** [comment]
It was my impression that [CL 196521](https://go-review.googlesource.com/c/go/+/196521) modified `parentCancelCtx` such that it no longer uses known types to traverse upwards, but instead uses a value to quickly look up the parent cancel context.

Meaning, you should be able to write this code:

```go
type myValueContext struct {
    context.Context
    key   interface{}
    value *SomeValue
}

func (v myValueContext) Value(key interface{}) interface{} {
    if key == v.key {
        return v.value
    }
    return v.Context.Value(key)
)
```

And it only incur a single allocation (ignoring my placeholder types).

**Comment by RaduBerinde** [comment]
Ah, awesome! Yeah that does it. I had checked the source at https://golang.org/src/context/context.go?s=8419:8483#L222 but I guess it's outdated.
