### ISSUE TITLE
internal/poll: CopyFileRange returns EIO on CentOS 7 ( Linux Kernel 3.10.0-1127) when io.Copy in  mounted CIFS

### ISSUE THREAD

**Issue by meiyang1123** [golang/go#42334]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.15.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/path/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go/path"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/go/root/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/go/root/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/code/goldeneyes/common/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build111842700=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

run  at CentOS Linux release 7.8.2003 (Kernel 3.10.0-1127.el7.x86_64) 

### What did you do?

I set up a samba service , share a directory, allow user to read and create and write.

Then, mount the share directory at CentOS 7 /mnt/test

build a example:

```
func main() {
	fmt.Println(CopyFile(os.Args[1], os.Args[2]))
}

func CopyFile(src string, dst string) (int64, error) {
	srcFile, err := os.Open(src)
	if err != nil {
		return -1, err
	}
	defer srcFile.Close()

	dstFile, err := os.OpenFile(dst, os.O_RDWR|os.O_CREATE|os.O_TRUNC, os.ModePerm)
	if err != nil {
		return -1, err
	}
	defer dstFile.Close()
	return io.Copy(dstFile, srcFile)
}
```
`go build  -o gocopy`
Run gocopy on CentOS7 : 
<pre>
[root@localhost ~]# ./gocopy 1.txt 2.txt
18 &lt;nil&gt;
[root@localhost ~]# ./gocopy /mnt/test/1.txt 1.txt
18 &lt;nil&gt;
[root@localhost ~]# ./gocopy 1.txt /mnt/test/2.txt
18 &lt;nil&gt;
[root@localhost ~]# ./gocopy /mnt/test/1.txt /mnt/test/2.txt
0 write /mnt/test/2.txt: copy_file_range: input/output error
</pre>

Follow the source code，found：

On success case, copyFileRange return ENOSYS . But when  copy two file on cifs will return  EIO

### What did you expect to see?

copy success

**Comment by tklauser** [comment]
Thanks for the report @meiyang1123.

Previously: #40893, #40731. I think the fix should be similar, i.e. we should handle `syscall.EIO` like we already do for  `syscall.EXDEV, syscall.EINVAL, syscall.EOPNOTSUPP, syscall.EPERM`.

Given that the previous two issues were backported, I assume we should backport this as well?

/cc @ianlancetaylor

**Comment by tklauser** [comment]
@meiyang1123 Could you check that https://golang.org/cl/266940 fixes the issue for you? Thanks.

**Comment by meiyang1123** [comment]
> @meiyang1123 Could you check that https://golang.org/cl/266940 fixes the issue for you? Thanks.

Yes ，It works for me.

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport issues for 1.15.

This is an unlikely error, but if it occurs there is no workaround.
