### ISSUE TITLE
runtime: allocSpan called from wbufFlush that runs with an unwired P

### ISSUE THREAD

**Issue by Helflym** [golang/go#42339]
There is a new failure on aix/ppc64 builder related to getMCache: 
https://build.golang.org/log/fa90b60048ac7f99bc84523d236948a1f090b4c3
https://build.golang.org/log/a5515473b2094744ca0ff0d19c330fa66ca6184a

It seems to appear only on AIX for now.

According to @mknyszek, this isn't related to #42305.

**Comment by mknyszek** [comment]
OK I see what's going on here. We're going into a syscall and handing off our P, but the GC is trying to terminate and so asks each P to flush its workbuf. Technically we're flushing the workbuf with a P, but this P has already been released from the G and the M (via `handoffp(releasep())` in `entersyscallblock_handoff`) and I had assumed that the page/span allocator is always called with a P, but this is a rare case where it isn't (and it didn't technically have this requirement before).

Unfortunately, I believe this means we need to just support this case, so there needs to be a fallback for updating the stats when we don't have a P (either that or we plumb the `mcache` through, though that sounds onerous).

Also, this is a potential problem on all platforms, not just `aix/ppc64`. Definitely a release-blocker.

**Comment by mknyszek** [comment]
CC @prattmic @aclements

**Comment by mknyszek** [comment]
The `aix/ppc64` builder seems to pass! Thanks @Helflym for the prompt report and for filing an issue.

**Comment by mknyszek** [comment]
Ah, it occurs to me that this failure isn't exactly common on `aix/ppc64` so that's not necessarily proof of a fix, but I definitely do understand the problem. I suppose I'll land and we'll reopen this issue if we see it again?
