### ISSUE TITLE
x/build/dashboard: add misc-compile-darwinarm64 trybot

### ISSUE THREAD

**Issue by dmitshur** [golang/go#42341]
@cherrymui has notified me that the darwin/arm64 port now supports internal linking, meaning we can cross-compile for darwin/arm64 without needing a C compiler.

Let's add a misc-compile trybot for it, since it's possible now. As all misc-compiler trybots, it will run buildall.bash to cross-compile & vet std+cmd packages, but not run any tests. It should first be added as a normal post-submit builder with a non-zero KnownIssue (similar to [CL 257617](https://golang.org/cl/257617)) before being graduated to a proper trybot.

This helps with #39782 (but doesn't replace it, since a misc-compile builder doesn't run any tests).

@cherrymui Starting with what Go commit do you expect it to work?

CC @golang/release.

**Comment by cherrymui** [comment]
I think it should start to work after CL https://go-review.googlesource.com/c/go/+/265121 , a.k.a. b85c2dd56c4ecc7bf445bd1615467ecd38598eee.

**Comment by dmitshur** [comment]
Great, I've made that commit required in [CL 267105](https://golang.org/cl/267105).

**Comment by dmitshur** [comment]
There's a bit more to do before this TryBot becomes alive; reopening.

**Comment by dmitshur** [comment]
It's working as expected so far. Here's a TryBot run from a recent CL:

![image](https://user-images.githubusercontent.com/1924134/98374054-20643080-200e-11eb-9aaf-5d4a0ef3b7c7.png)

<details><summary>Build Log</summary><br>

```
  success: true

Build log:
misc-compile-darwinarm64 at 9b04918db6f33a5a6c63fb3f04a178883fd4851e

:: Running /workdir/go/src/buildall.bash with args ["/workdir/go/src/buildall.bash" "^darwin-arm64$"] and env ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" "HOSTNAME=buildlet-linux-jessie-rn9bc54d5" "DEBIAN_FRONTEND=noninteractive" "HOME=/root" "USER=root" "GO_STAGE0_NET_DELAY=100ms" "GO_STAGE0_DL_DELAY=400ms" "WORKDIR=/workdir" "GOROOT_BOOTSTRAP=/workdir/go1.4" "GO_BUILDER_NAME=misc-compile-darwinarm64" "GOROOT_BOOTSTRAP=/go1.4" "GO_DISABLE_OUTBOUND_NETWORK=1" "TMPDIR=/workdir/tmp" "GOCACHE=/workdir/gocache"] in dir /workdir/go/src

Building Go cmd/dist using /go1.4. (go1.4 linux/amd64)
Building Go toolchain1 using /go1.4.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/amd64.
---
Installed Go for linux/amd64 in /workdir/go
Installed commands in /workdir/go/bin

### Building darwin-arm64
```

</details>

In contrast with [CL 268057](https://golang.org/cl/268057) which intentionally adds invalid code for macOS arm64 only:

![image](https://user-images.githubusercontent.com/1924134/98376300-43dcaa80-2011-11eb-94d8-37dd2a81f7d6.png)

<details><summary>Build Log</summary><br>

```
  success: false

Build log:
misc-compile-darwinarm64 at 7641155bd44b5facb893b63e2e49042b96e758fc

:: Running /workdir/go/src/buildall.bash with args ["/workdir/go/src/buildall.bash" "^darwin-arm64$"] and env ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" "HOSTNAME=buildlet-linux-jessie-rn520e6d2" "DEBIAN_FRONTEND=noninteractive" "HOME=/root" "USER=root" "GO_STAGE0_NET_DELAY=100ms" "GO_STAGE0_DL_DELAY=200ms" "WORKDIR=/workdir" "GOROOT_BOOTSTRAP=/workdir/go1.4" "GO_BUILDER_NAME=misc-compile-darwinarm64" "GOROOT_BOOTSTRAP=/go1.4" "GO_DISABLE_OUTBOUND_NETWORK=1" "TMPDIR=/workdir/tmp" "GOCACHE=/workdir/gocache"] in dir /workdir/go/src

Building Go cmd/dist using /go1.4. (go1.4 linux/amd64)
Building Go toolchain1 using /go1.4.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/amd64.
---
Installed Go for linux/amd64 in /workdir/go
Installed commands in /workdir/go/bin

### Building darwin-arm64
# bufio
bufio/bad_darwin_arm64.go:5:1: syntax error: non-declaration statement outside function body

Build(s) failed.


Error: all script failed: exit status 1
```

</details>

**Comment by dmitshur** [comment]
This is live, so closing. If there are issues, please let me know.
