### ISSUE TITLE
gollvm:build faild on ubuntu20

### ISSUE THREAD

**Issue by KunPengRen** [golang/go#42355]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.2 linux/amd64
</pre>

### What did you do?
Hi all, I complied gollvm use  ninja floow https://go.googlesource.com/gollvm/#installing
The command I used
cmake -DCMAKE_BUILD_TYPE=Debug -DLLVM_USE_LINKER=gold -G Ninja ../llvm-project/llvm
ninja gollvm

Then I got errors like bellow output

[2545/3627] Generating /home/kunpeng/Documents/project/gollvm/build-debug/tools/gollvm/libgo/gen-sysinfo.go
FAILED: tools/gollvm/libgo/gen-sysinfo.go.tmp 
cd /home/kunpeng/Documents/project/gollvm/build-debug/tools/gollvm/libgo && /home/kunpeng/Documents/project/gollvm/build-debug/./bin/llvm-godumpspec --macrotmp=/home/kunpeng/Documents/project/gollvm/build-debug/tools/gollvm/libgo/sysinfo.macros.txt --object=/home/kunpeng/Documents/project/gollvm/build-debug/tools/gollvm/libgo/sysinfo.o --output=/home/kunpeng/Documents/project/gollvm/build-debug/tools/gollvm/libgo/gen-sysinfo.go.tmp
error: At most two relocations per offset are supported
error: At most two relocations per offset are supported
.......
error: At most two relocations per offset are supported
llvm-godumpspec: /home/kunpeng/Documents/project/gollvm/llvm-project/llvm/tools/gollvm/libgo/godumpspec/godumpspec.cpp:1104: bool GoDumpHelper::generateType(const llvm::DWARFDie&, TypeNameDisp): Assertion `qtyp.isValid()' failed.
 #0 0x000055ccdf446bf6 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/kunpeng/Documents/project/gollvm/llvm-project/llvm/lib/Support/Unix/Signals.inc:563:22
 #1 0x000055ccdf446cb1 PrintStackTraceSignalHandler(void*) /home/kunpeng/Documents/project/gollvm/llvm-project/llvm/lib/Support/Unix/Signals.inc:630:1
 #2 0x000055ccdf44494d llvm::sys::RunSignalHandlers() /home/kunpeng/Documents/project/gollvm/llvm-project/llvm/lib/Support/Signals.cpp:71:20
 #3 0x000055ccdf446543 SignalHandler(int) /home/kunpeng/Documents/project/gollvm/llvm-project/llvm/lib/Support/Unix/Signals.inc:405:1
 #4 0x00007f9df4bf73c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #5 0x00007f9df469d18b gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x4618b)
 #6 0x00007f9df467c859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x25859)
 #7 0x00007f9df467c729 __tls_get_addr (/lib/x86_64-linux-gnu/libc.so.6+0x25729)
 #8 0x00007f9df468df36 (/lib/x86_64-linux-gnu/libc.so.6+0x36f36)
 #9 0x000055ccded55d66 GoDumpHelper::generateType(llvm::DWARFDie const&, TypeNameDisp) (.localalias) /home/kunpeng/Documents/project/gollvm/llvm-project/llvm/tools/gollvm/libgo/godumpspec/godumpspec.cpp:1105:26
#10 0x000055ccded55b57 GoDumpHelper::generateType(llvm::DWARFDie const&, TypeNameDisp) (.localalias) /home/kunpeng/Documents/project/gollvm/llvm-project/llvm/tools/gollvm/libgo/godumpspec/godumpspec.cpp:1051:39
#11 0x000055ccded53c8f GoDumpHelper::generateFcnType(llvm::DWARFDie const&) /home/kunpeng/Documents/project/gollvm/llvm-project/llvm/tools/gollvm/libgo/godumpspec/godumpspec.cpp:618:9
#12 0x000055ccded55cfb GoDumpHelper::generateType(llvm::DWARFDie const&, TypeNameDisp) (.localalias) /home/kunpeng/Documents/project/gollvm/llvm-project/llvm/tools/gollvm/libgo/godumpspec/godumpspec.cpp:1092:29
#13 0x000055ccded55b57 GoDumpHelper::generateType(llvm::DWARFDie const&, TypeNameDisp) (.localalias) /home/kunpeng/Documents/project/gollvm/llvm-project/llvm/tools/gollvm/libgo/godumpspec/godumpspec.cpp:1051:39
#14 0x000055ccded55c14 GoDumpHelper::generateType(llvm::DWARFDie const&, TypeNameDisp) (.localalias) /home/kunpeng/Documents/project/gollvm/llvm-project/llvm/tools/gollvm/libgo/godumpspec/godumpspec.cpp:1072:28
#15 0x000055ccded52ada GoDumpHelper::visitType(llvm::DWARFDie const&) /home/kunpeng/Documents/project/gollvm/llvm-project/llvm/tools/gollvm/libgo/godumpspec/godumpspec.cpp:407:25
#16 0x000055ccded52681 GoDumpHelper::enqueueType(llvm::DWARFDie const&) /home/kunpeng/Documents/project/gollvm/llvm-project/llvm/tools/gollvm/libgo/godumpspec/godumpspec.cpp:349:1
#17 0x000055ccded528bb GoDumpHelper::readDwarf(llvm::DWARFCompileUnit*) /home/kunpeng/Documents/project/gollvm/llvm-project/llvm/tools/gollvm/libgo/godumpspec/godumpspec.cpp:374:18
#18 0x000055ccded569d1 visitObjectFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GoDumpHelper&, ObjectState&, llvm::raw_ostream&) /home/kunpeng/Documents/project/gollvm/llvm-project/llvm/tools/gollvm/libgo/godumpspec/godumpspec.cpp:1242:10
#19 0x000055ccded56cf0 main /home/kunpeng/Documents/project/gollvm/llvm-project/llvm/tools/gollvm/libgo/godumpspec/godumpspec.cpp:1281:8
#20 0x00007f9df467e0b3 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b3)
#21 0x000055ccded51afe _start (/home/kunpeng/Documents/project/gollvm/build-debug/./bin/llvm-godumpspec+0x4d1afe)
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /home/kunpeng/Documents/project/gollvm/build-debug/./bin/llvm-godumpspec --macrotmp=/home/kunpeng/Documents/project/gollvm/build-debug/tools/gollvm/libgo/sysinfo.macros.txt --object=/home/kunpeng/Documents/project/gollvm/build-debug/tools/gollvm/libgo/sysinfo.o --output=/home/kunpeng/Documents/project/gollvm/build-debug/tools/gollvm/libgo/gen-sysinfo.go.tmp 
Aborted (core dumped)
ninja: build stopped: subcommand failed.

If there anything to solve the problem?

**Comment by thanm** [comment]
Thanks for the report.

**Comment by thanm** [comment]
This should now be fixed on tip, with https://go-review.googlesource.com/c/gollvm/+/267478 and https://go-review.googlesource.com/c/gollvm/+/267479 ... please reopen if not.
