### ISSUE TITLE
os: Readdirnames(-1) changed nil-ness behavior

### ISSUE THREAD

**Issue by rsc** [golang/go#42367]
It's unclear exactly which direction it changed, but something about one of the zero-length-slice-return cases in Readdirnames changed from nil to non-nil or vice versa and broke some picky tests inside Google. 

There was no intent to change this behavior of Readdirnames, so it should be fixed. I will do that.

**Comment by odeke-em** [comment]
Thanks for filing this @rsc! I believe that it is from here
![Screen Shot 2020-11-03 at 1 47 52 PM](https://user-images.githubusercontent.com/4898263/98044109-39d16680-1ddb-11eb-939b-e06430f4b011.png)
https://go-review.googlesource.com/c/go/+/261540

We were supposed to unconditionally return names whether there was an error or not.
I noticed it as an oddity while re-reading through the CL, but it got merged before I could finish thinking about it the change, so interesting to see that tests caught it, sorry I didn't speak up earlier  😁
