### ISSUE TITLE
Building Go doesn't work

### ISSUE THREAD

**Issue by OfshoX** [golang/go#42366]
I am trying to build Go and I get this error, what does this mean?

```
Building Go cmd/dist using /usr/local/Cellar/go/1.15.2/libexec. (go1.15.2 darwin/amd64)
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD

go tool dist: FAILED: git rev-parse --abbrev-ref HEAD: exit status 128
```

**Comment by davecheney** [comment]
Thank you for raising this issue. Could you please complete the issue template so someone debugging this issue knows the exact steps you used so they can attempt to recreate them.

**Comment by ianlancetaylor** [comment]
What are the exact steps that you took to produce that error?

This kind of error happens when trying to build the tip of Go development but not using a git repository.
