### ISSUE TITLE
x/perf/cmd/benchstat: output format compatability breaks

### ISSUE THREAD

**Issue by changkun** [golang/go#42371]
After CL [263804](https://golang.org/cl/263804), the format of benchmark results contains `pkg` and `cpu` information.
This breaks the compatibility with benchstat such that outputs from previous versions cannot be consumed and compared to the outputs from the tip (9848e93cb7). For instance,

```
$ benchstat 115.txt 116.txt

```

Expect a compared result but no output at the moment. A workaround could just delete the output regarding these two lines:

```
pkg: main
cpu: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
```

But a fix to the benchstat that ignores the change from the CL would be great.

**Comment by martisch** [comment]
The pkg label is not new it has been there before CL 263804.

The fix could be that for grouping benchstat should just ignore the cpu label.

**Comment by changkun** [comment]
Interesting. I can't reproduce the issue anymore, and not sure how the pkg tag was lost from the 115 outputs.

Close and sorry...
