### ISSUE TITLE
go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- ./]: exit status 1: go: cannot find main module; see 'go help modules' : packages.Load error

### ISSUE THREAD

**Issue by syflss** [golang/go#42394]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.3 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
I install the go extension in vs-code and it tell me fail to compile
![error img](https://tva1.sinaimg.cn/large/0081Kckwly1gkeehyygcxj30uo0ey771.jpg)

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
