### ISSUE TITLE
different package downloaed from "go mod tidy" and "go mod downloaded"

### ISSUE THREAD

**Issue by zhangmingld** [golang/go#42392]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13.5
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?
I have an project which contains part of cobra@v0.0.5 as an dependency, when i use "go mod download", all the dependency defined of cobra is downloaded.

But when i use "go mod tidy", only the dependency of the used part of cobra is downloaded.

In fact,
When using "go mod download", i got the following 
go: finding github.com/spf13/cast v1.3.0
go: finding github.com/spf13/cobra v0.0.5
go: finding github.com/spf13/jwalterweatherman v1.0.0
go: finding github.com/spf13/pflag v1.0.3
go: finding github.com/spf13/viper v1.3.2

When using "go mod tidy", only got cobra@v0.0.5 and pflagv1.0.3, which is the accurate dependency of the cobra part i am using.

### What did you expect to see?
i want to know why it happens

**Comment by bcmills** [comment]
> ### What version of Go are you using (`go version`)?

Note that per the [release policy](https://golang.org/doc/devel/release.html#policy), Go 1.13.5 is no longer supported. Please update to a supported release (1.15.3 or 1.14.10).


> ### What did you do?

Please give the exact commands that you ran. (Did you run `go mod download` without arguments, or did you request specific modules?)

`go mod download` does not examine the package-imports within your module: it downloads all modules reachable from your transitive dependencies, regardless of whether those modules are actually needed to build any package. Lazy loading (#36460) will reduce the set of transitive dependencies, but `go mod download` will still fundamentally download more than strictly necessary in some cases.

**Comment by zhangmingld** [comment]
Hi @bcmills 

Thank you , i got it.
