### ISSUE TITLE
cmd/link: `link` reports "symbol listed multiple times" if go:linkname into both vendor package and non-vendor package

### ISSUE THREAD

**Issue by chenzhuoyu** [golang/go#42401]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/myusername/Library/Caches/go-build"
GOENV="/Users/myusername/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/myusername/GolangProjects/pkg/mod"
GONOPROXY="*.mycompanydomain.org"
GONOSUMDB="*.mycompanydomain.org"
GOOS="darwin"
GOPATH="/Users/myusername/GolangProjects"
GOPRIVATE="*.mycompanydomain.org"
GOPROXY="https://go-mod-proxy.mycompanydomain.org,https://goproxy.cn,https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.3/libexec"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/myusername/Sources/tests/test_go/main/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/h3/c5bgpd9921d0tbkpf5n9vh2w0000gn/T/go-build518026853=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

1. Create a directory structure like this:
```
.
├── foo
│   ├── foo.go
│   └── go.mod
└── main
    ├── go.mod
    └── main.go
```

```go
// $ cat foo/go.mod 
module github.com/chenzhuoyu/env

go 1.15
```

```go
// $ cat foo/foo.go 
package foo

var bar string

func GetBar() string {
    return bar
}

func init() {
    bar = ""
}
```

```go
// $ cat main/go.mod 
module github.com/chenzhuoyu/linker_issue

go 1.15

replace github.com/chenzhuoyu/foo v0.0.0 => ../foo

require github.com/chenzhuoyu/foo v0.0.0
```

```go
// $ cat main/main.go 
package main

import (
    _ `unsafe`

    `github.com/chenzhuoyu/foo`
)

//go:linkname v1 github.com/chenzhuoyu/foo.bar
var v1 string

//go:linkname v2 github.com/chenzhuoyu/linkname/vendor/github.com/chenzhuoyu/foo.bar
var v2 string

func main() {
    v1 = v2
    foo.GetBar()
}

```

2. Build the `main` package.

```bash
$ cd main
$ go build .
```

### What did you expect to see?

The `main` package builds just fine.

### What did you see instead?

```
$ go build .
# github.com/chenzhuoyu/linker_issue
2020/11/05 23:56:41 symbol go.info.github.com/chenzhuoyu/foo.bar listed multiple times
```

### I have also tried:

* `go 1.14.10` works fine.

```
$ cd main
$ ls
go.mod  main.go
$ /usr/local/opt/go@1.14/bin/go version
go version go1.14.10 darwin/amd64
$ /usr/local/opt/go@1.14/bin/go build .
$ ls
go.mod  linker_issue*  main.go
```

* Passing `-ldflags='-w'` to the compiler also works fine.

```
$ go build -ldflags='-w' .
$ ls
go.mod  linker_issue*  main.go
```

* After searching for several hours, I found these related issues, but they are not very helpful to me.

https://github.com/golang/go/issues/11699
https://github.com/golang/go/issues/15926
https://github.com/golang/go/issues/28159

**Comment by thanm** [comment]
I'll take a look.

**Comment by thanm** [comment]
A note before getting into the details of the bug:  please be aware that the behavior + implementation of "//go:linkname" is explicitly **not** covered by the Go 1 compatibility guarantee; the fact that importing "unsafe" is required is intended to reinforce this.

As the toolchain changes over time, the implementation and behavior of "//go:linkname" can evolve. There are uses of "//go:linkname" that may work with version X of the Go toolchain and then not work with version X+1.  For example, using "//go:linkname" to reach from package A into a dependent package B to access one of B's non-exported symbols is something that works today, but may very well not work with future versions of Go.

Regarding the Go program in the bug:

This program contains behavior that happened to work with the Go 1.14 toolchain implementation of "//go:linkname" but does not work with Go 1.15. In Go 1.14, linking and symbol resolution is done using an entirely name-driven basis; all (or virtuall all) symbols are named, and at link time two symbols with the same name wind up mapping to same linker symbol, regardless of which package or compilation unit the symbol was defined in.

What this means is that for Go 1.14 when you write

```
  //go:linkname v1 github.com/chenzhuoyu/foo.bar
  var v1 string
```

this has the effect of making "v1" (defined in main.go) and "bar" (defined in foo.go) virtually the same symbol at link time. If you look in the final binary produced by Go 1.14 for this example, there are only two "foo.bar" variables.

In Go 1.15 we moved to a new object file format and a new way of doing symbol resolution. For most regular Go symbol definitions (variables, functions) the compiler assigns the symbol an index within the object file; when the linker reads the object file, it sees the symbol (roughly) as a tuple <P,S> where P is a numeric package ID and S is a numeric symbol ID. 

What this means for Go 1.15 is that there are actually three "foo.bar" strings: one defined in package foo and two in package main; each has a unique identity using the new index-based scheme. Two of the three symbols happen to have the same name, which results in a collision during DWARF generation.

**Comment by cherrymui** [comment]
I'm not sure I understand the issue.

> github.com/chenzhuoyu/linkname/vendor/github.com/chenzhuoyu/foo.bar

Where do you vendor this? I didn't see any vendor directory or any vendor command.

Also, do you run into this issue in real code, or just this synthetic example?

**Comment by chenzhuoyu** [comment]
> Where do you vendor this? I didn't see any vendor directory or any vendor command.

I don't, I just write it there.

> Also, do you run into this issue in real code, or just this synthetic example?

I ran into this issue in real code in our library, it is only used for unittests, so there are a lot of "hacks" in it. The code above is just a simplification.

Some of our legacy projects use `dep` to manage dependencies, so the code needs to work with both vendored projects and non-vendored projects, but upgrading to Go 1.15.3 breaks a lot of our tests. :(

Maybe we should consider refactoring the library and get rid of `go:linkname`, but that will be a lot of work. :(

**Comment by chenzhuoyu** [comment]
> A note before getting into the details of the bug: please be aware that the behavior + implementation of "//go:linkname" is explicitly **not** covered by the Go 1 compatibility guarantee; the fact that importing "unsafe" is required is intended to reinforce this.

We only use "//go:linkname" for unittests, not in our production code.

There are some not-so-well-designed libraries that come with a lot of side-effects (performing I/O within `init`, reading environment variables, etc), which can cause our tests to be very unstable.

The "//go:linkname" is a way we found to "hack" these libraries and set them into a certain state for our tests.

> As the toolchain changes over time, the implementation and behavior of "//go:linkname" can evolve. There are uses of "//go:linkname" that may work with version X of the Go toolchain and then not work with version X+1. For example, using "//go:linkname" to reach from package A into a dependent package B to access one of B's non-exported symbols is something that works today, but may very well not work with future versions of Go.

Should I conside "//go:linkname" as some sort of "undefined behavior" ?

**Comment by ianlancetaylor** [comment]
I wouldn't say that `//go:linkname` is undefined behavior.  But it is unsafe, and it is not covered by the Go 1 compatibility guarantee.  If you choose to use it, you must be prepared to adjust your use with each new Go release.

In general I would advise against using it.
