### ISSUE TITLE
runtime: misc/cgo/testtls failing on openbsd-386-62, openbsd-amd64-62

### ISSUE THREAD

**Issue by prattmic** [golang/go#42408]
There are numerous of these failures on http://build.golang.org (386 only until #42237 is fixed).

https://build.golang.org/log/131aa06b3b531ffe83df8b656838bebe8427a850

```
##### ../misc/cgo/test
# misc/cgo/test
/tmp/workdir/tmp/go-build911004276/b057/_x008.o: In function `issue12030conv':
./test.go:621: warning: warning: sprintf() is often misused, please use snprintf()
/tmp/workdir/tmp/go-build911004276/b057/_x008.o: In function `testSendSIG':
./test.go:244: warning: warning: rand() may return deterministic values, is that what you want?
# misc/cgo/test.test
/tmp/workdir/tmp/go-link-304024764/000007.o: In function `issue12030conv':
/tmp/workdir/go/misc/cgo/test/test.go:621: warning: warning: sprintf() is often misused, please use snprintf()
/tmp/workdir/tmp/go-link-304024764/000007.o: In function `testSendSIG':
/tmp/workdir/go/misc/cgo/test/test.go:244: warning: warning: rand() may return deterministic values, is that what you want?
PASS
ok  	misc/cgo/test	37.185s
# misc/cgo/test
/tmp/workdir/tmp/go-build387635104/b057/_x008.o: In function `issue12030conv':
./test.go:621: warning: warning: sprintf() is often misused, please use snprintf()
/tmp/workdir/tmp/go-build387635104/b057/_x008.o: In function `testSendSIG':
./test.go:244: warning: warning: rand() may return deterministic values, is that what you want?
PASS
ok  	misc/cgo/test	36.523s
# misc/cgo/test
/tmp/workdir/tmp/go-build883801992/b058/_x008.o: In function `issue12030conv':
test.cgo2.c:(.text+0xc1b): warning: warning: sprintf() is often misused, please use snprintf()
/tmp/workdir/tmp/go-build883801992/b058/_x008.o: In function `testSendSIG':
test.cgo2.c:(.text+0x3b0): warning: warning: rand() may return deterministic values, is that what you want?
# misc/cgo/test.test
/tmp/workdir/tmp/go-link-701675411/000007.o: In function `issue12030conv':
test.cgo2.c:(.text+0xc1b): warning: warning: sprintf() is often misused, please use snprintf()
/tmp/workdir/tmp/go-link-701675411/000007.o: In function `testSendSIG':
test.cgo2.c:(.text+0x3b0): warning: warning: rand() may return deterministic values, is that what you want?
PASS
ok  	misc/cgo/test	36.424s
PASS
ok  	misc/cgo/testtls	0.035s
PASS
ok  	misc/cgo/testtls	0.138s
signal: segmentation fault (core dumped)
FAIL	misc/cgo/testtls	0.080s
2020/11/04 19:27:09 Failed: exit status 1
PASS
ok  	misc/cgo/nocgo	0.021s
PASS
ok  	misc/cgo/nocgo	0.035s
signal: segmentation fault (core dumped)
FAIL	misc/cgo/nocgo	0.090s
2020/11/04 19:27:13 Failed: exit status 1
skipped due to earlier error
skipped due to earlier error
go tool dist: FAILED
```

These started after http://golang.org/cl/267318, which re-enabled these tests.

These also show up on openbsd-amd64-62 with the fix for #42237.

cc @4a6f656c @cherrymui

**Comment by cherrymui** [comment]
It fails at the third run of `misc/cgo/testtls` and `misc/cgo/nocgo`, which are built with `-static`. Maybe static linking doesn't work on OpenBSD?

**Comment by cherrymui** [comment]
Others are warnings. Probably fine.

**Comment by 4a6f656c** [comment]
I'll take a look, but I manually tested here on 6.2 when the trybot was being difficult and as far as I know it worked. In short, the OpenBSD 6.2 builders should be retired - the only supported versions of OpenBSD are 6.7 and 6.8 - 6.2 was EOL when 6.4 was released in October 2018 (even the 6.4 builders are also more than a year EOL).

**Comment by prattmic** [comment]
Between here and #42237 there seems to be consensus that we just don't care about OpenBSD 6.2 any more.

Perhaps https://github.com/golang/go/wiki/OpenBSD#building-from-source needs an update?

**Comment by bcmills** [comment]
> Between here and #42237 there seems to be consensus that we just don't care about OpenBSD 6.2 any more.

#35712 (add an OpenBSD 6.8 builder) is probably relevant.

**Comment by 4a6f656c** [comment]
> Between here and #42237 there seems to be consensus that we just don't care about OpenBSD 6.2 any more.
> 
> Perhaps https://github.com/golang/go/wiki/OpenBSD#building-from-source needs an update?

There are probably parts of that wiki page that need updating, however the relevant part is:

https://github.com/golang/go/wiki/OpenBSD#longterm-support

(I think building from source was more so tracking whether it was possible, rather than if it was EOL :))

**Comment by aclements** [comment]
Just clarifying that the consensus here is that dropping OpenBSD 6.2 will fix this issue? It wasn't clear to me that we figured out that this is definitely specific to 6.2.

**Comment by aclements** [comment]
Dropping 6.2 is covered by #42426, so if that's what we need to do, we can close this issue.

**Comment by aclements** [comment]
Ping. Do we know that this is definitely a OpenBSD 6.2 issue?

**Comment by aclements** [comment]
`greplogs -dashboard -e "testtls.*\nsignal:.*seg" -l` shows that this happened exclusively on OpenBSD 6.2. Also, the last occurrence was [2020-11-12T21:21:29-f016172/openbsd-386-62](https://build.golang.org/log/e58d519b62b140acc0d795b500c122086eb43f5f), which is the [day we dropped the 6.2 builder](https://golang.org/cl/268880).

Hence, closing.
