### ISSUE TITLE
PRI HTTP method is missing

### ISSUE THREAD

**Issue by OGKevin** [golang/go#42419]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.15
</pre>

### Does this issue reproduce with the latest release?
Yes

### Details
According to this documentation: https://httpwg.org/specs/rfc7540.html#n-pri-method-registration about http/2 there is a new HTTP method introduced called "PRI". This method however is not listed in https://github.com/golang/go/blob/b7e0adfee28b516a0dcceb5ecf0e5a695b38c61f/src/net/http/method.go. 

Is a PR to add this method to the list welcome?

**Comment by davecheney** [comment]
No thank you. It is generally considered that those constants were unnecessary. If you want to assert the method is PRI, the literal constant `"PRI"` is both more compact and more descriptive.

**Comment by mdlayher** [comment]
Per Dave's response, I've also seen enough general disdain for these constants to feel pretty safe about closing this one out.

**Comment by OGKevin** [comment]
Thats a shame. Thanks for the feedback 👍🏾.
