### ISSUE TITLE
fmt: sloppy struct field arrangement could be re-done for efficiency/RAM reduction

### ISSUE THREAD

**Issue by odeke-em** [golang/go#42413]
Coming here from tip ecc3f51, with a tool we've developed at Orijtech, Inc, it reported
```shell
/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/fmt/format.go:41:10: struct has size 112,
could be 104, rearrange to struct{buf *buffer; wid int; prec int; intbuf [68]byte; fmtFlags} for
optimal size
```
because
https://github.com/golang/go/blob/ecc3f5112ebaf23c4b1ac4c5eedfa406d82ecc9a/src/fmt/format.go#L41-L52

which when rearranged would become 7.14% more efficient as per https://play.golang.org/p/I8aIwwdbZYw.

Similar to https://github.com/golang/go/issues/42412

**Comment by martisch** [comment]
I tried around with this alot in the past and back then it always made format slower potentially due to alignment change on the buffer.

We should benchmark fmt before making this change.

**Comment by odeke-em** [comment]
Thanks @martisch, and you are right about the RAM-no-savings: we added size class recognition and it no longer complains. Should we close this issue then?

**Comment by martisch** [comment]
Since there are no ram savings I would say lets close this for now. Im not sure its worth toying with that structure ordering for performance gains. They would need to be verified outside microbenchmarks to make sure anyway.
