### ISSUE TITLE
crypto/x509: failed to load system roots and no roots provided

### ISSUE THREAD

**Issue by Poor12** [golang/go#42414]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.4 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tiechengshen/Library/Caches/go-build"
GOENV="/Users/tiechengshen/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/tiechengshen/go/src/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tiechengshen/go/src"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/j7/rm372g_j5hn4k7d2x_vz43bw0000gn/T/go-build603228894=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.15.4 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.15.4
uname -v: Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2
lldb --version: lldb-1100.0.30.6
Apple Swift version 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)
</pre></details>

### What did you do?

go get github.com/golang/glog

### What did you expect to see?

go get success

### What did you see instead?

go get github.com/golang/glog: module github.com/golang/glog: Get "https://goproxy.io/github.com/golang/glog/@v/list": x509: failed to load system roots and no roots provided; SecTrustSettingsCopyCertificates error: -25300

**Comment by bcmills** [comment]
CC @FiloSottile @katiehockman

**Comment by Poor12** [comment]
It seems system error. I reinstalled the system and fixed it.

**Comment by wawa0210** [comment]
I reproduced the problem, very strange. The version of my macos is Catalina 10.15.7 (recently upgraded). If I install the latest version of golang 1.15, this problem will occur. It was normal before the mac was upgraded. If I roll back the golang version to 1.14.12, everything is normal. It seems to be caused by the compatibility of mac os Catalina 10.15.7 and golang 1.15

**Comment by Poor12** [comment]
Yeah,my situation is just the same.@wawa0210

**Comment by wawa0210** [comment]
I suggest that you can reopen this issue for further follow-up by the community

**Comment by wmenjoy** [comment]
yeah, the same problem for me.

**Comment by aidenwei** [comment]
Is there any update? On my MacOS Catalina 10.15.6, both go 1.15 and 1.16 meet x509 problem, but go 1.14 succeeds. What should I do if I want to use go 1.16 or even more updated versions?

**Comment by shuiRong** [comment]
same here.
go version go1.16.2 darwin/amd64
macOS Big Sur 11.4 Beta
```
Error: Get "https://www.zhihu.com/hot": x509: 
failed to load system roots and no roots provided; SecTrustSettingsCopyCertificates error: -2070
```

**Comment by wawa0210** [comment]
@shuiRong  @aidenwei  @wmenjoy

I have solved the problem. It should be a certificate problem in the keychain access of mac. It seems that there is a certificate authority. I edited it and it was ok. I don’t remember the specific certificate. You can try

**Comment by ysrotciv** [comment]
I met the same problem. 
My go version is go1.15.3 darwin/amd64.
My macOS version is Big Sur 11.1.

I solved this problem by trust DigiCert Global Root CA in keychain.

**Comment by aidenwei** [comment]
> I met the same problem.
> My go version is go1.15.3 darwin/amd64.
> My macOS version is Big Sur 11.1.
> 
> I solved this problem by trusting DigiCert Global Root CA in keychain.

Trust DigiCert Global Root CA in keychain works! Thanks to @ysrotciv .

**Comment by yhf20071** [comment]
> I met the same problem.
> My go version is go1.15.3 darwin/amd64.
> My macOS version is Big Sur 11.1.
> 
> I solved this problem by trusting DigiCert Global Root CA in keychain.

It works. Thanks to @ysrotciv

**Comment by mowangdk** [comment]
It works(*^▽^*) Thanks to @ysrotciv
