### ISSUE TITLE
cmd/compile: rearrange hairyVisitors to reduce struct slop and reclaim 33.33% space wasted

### ISSUE THREAD

**Issue by odeke-em** [golang/go#42416]
Coming here from tip ecc3f51, with one of the static analysis tools, we have developed at Orijtech, Inc., we've found a
struct that we could re-arrange and reclaim 33.33% of the RAM each struct uses

```shell
$ structslop .
cmd/compile/internal/gc/inl.go:300:19: struct has size 40 (size class 48), could be 32 (size class 32),
rearrange to  struct{reason string; usedLocals map[*Node]bool; budget int32; extraCallCost int32} for
optimal size (33.33% savings)
```
hairyVisitors seems like a potentially frequently created struct, so these savings could directly be quantifiable in compilations.

**Comment by rsc** [comment]
This one is again not something that there are many of. This variable is declared as a local to hold state before a recursive walk of a function body. It's a miniscule percentage of a tiny fraction of the overall compiler memory usage.

**Comment by odeke-em** [comment]
Can be closed.
