### ISSUE TITLE
cmd/compile: make compiler reorganize user structs without having user code modify fields so userland readability can come first

### ISSUE THREAD

**Issue by odeke-em** [golang/go#42428]
Coming here from an offline discussion with @aclements, in regards to a new static analysis pass ["structslop" that Orijtech, Inc. just released](https://medium.com/orijtech-developers/efficient-struct-packing-guided-pass-for-go-92255872ec72) and related issues:
* https://github.com/golang/go/issues/42412
* https://github.com/golang/go/issues/42415
* https://github.com/golang/go/issues/42416

The concern is that by having a static analysis pass that coerces users into statically optimized changes that might have adverse effects, like ruining their readability, ruining co-location and cache line blowing.

A compiler pass as @aclements mentioned would solve these issues, but another benefit would be scalable development whereby every Go developer would get these benefits without having to run a separate pass, it won't interfere with code reviews nor blindly make recommendations that few people can reason about.

/cc @cuonglm @martisch @randall77 @aclements @dr2chase @mknyszek.

**Comment by odeke-em** [comment]
A somewhat similar proposal that's currently on hold https://github.com/golang/go/issues/36606, brought to my attention offline by @rsc.

**Comment by rsc** [comment]
We can't reorder fields until there is a way to signal "don't reorder fields". That way was going to be and may still be //go:packed (#36606), but that work is put to the side to focus on generics. 

Past discussion about reordering struct fields is #10014.

**Comment by rsc** [comment]
This issue can probably be closed as a duplicate of #36606. I don't think we need to keep both open.

**Comment by odeke-em** [comment]
SGTM, thank you @rsc for chiming in with the background.
