### ISSUE TITLE
x/pkgsite: missing struct docs

### ISSUE THREAD

**Issue by codyoss** [golang/go#42425]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/google.golang.org/genproto/googleapis/cloud/secretmanager/v1#Secret 
 
### Screenshot
 
[pkg.go.dev]( https://pkg.go.dev/google.golang.org/genproto/googleapis/cloud/secretmanager/v1#Secret ):
![Screen Shot 2020-11-06 at 8 29 32 AM](https://user-images.githubusercontent.com/6331106/98383882-4a1b5880-200a-11eb-9e76-3667afc2a97e.png)

[godoc.org](https://godoc.org/google.golang.org/genproto/googleapis/cloud/secretmanager/v1#Secret):
 
![Screen Shot 2020-11-06 at 8 30 29 AM](https://user-images.githubusercontent.com/6331106/98383937-5bfcfb80-200a-11eb-979e-1cdda4ee4f8e.png)

 
### What did you do?
 
Navigate to pkg.go.dev to look up some docs. 
 
### What did you expect to see?
 
 Struct field docs.
 
### What did you see instead?

No documentation. Here is the source for the docs: [source](https://github.com/googleapis/go-genproto/blob/9d023cd09d72d450c89eb46256c900c4a8b8a0d6/googleapis/cloud/secretmanager/v1/resources.pb.go#L110).

**Comment by jba** [comment]
Thanks for finding this. I first feared that it was a bug in some recent work we've been doing on documentation rendering, but it actually predates that. It's related to that long field tag on `Labels`: overly long field tags turn off all other comments in a declaration. Should have a fix by Monday.

**Comment by dmitshur** [comment]
I think this is related to #38699. This seems like a slightly different type of occurrence (one where godoc.org isn’t affected), but the root problem might be the same. I started working on a fix for it in [CL 240217](https://golang.org/cl/240217), although there’s a merge conflict to resolve by now.

**Comment by jba** [comment]
The comments are back but the "contains filtered or unexported fields" message is not in the right place. Leaving this open.
