### ISSUE TITLE
x/tools/imports: remove duplicate imports when one is _-imported

### ISSUE THREAD

**Issue by josharian** [golang/go#42432]
If you run goimports on this code:

```go
package p

import (
  _ "crypto/sha1"
)

var _ = sha1.Sum
```

You get:

```go
package p

import (
	"crypto/sha1"
	_ "crypto/sha1"
)

var _ = sha1.Sum
```

Note the duplicate imports. We could remove the _ import.

**Comment by FiloSottile** [comment]
Note that https://golang.org/cl/250497 was reverted in https://golang.org/cl/265078, because while the naked import might be removed if the package is not explicitly used anymore, the _ import expresses the intention to import it regardless. goimports should probably preserve that.

**Comment by josharian** [comment]
Ah, makes sense. Thanks.
