### ISSUE TITLE
The plugin always tells me that there is a error

### ISSUE THREAD

**Issue by kands-code** [golang/go#42435]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\31280\AppData\Local\go-build
set GOENV=C:\Users\31280\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\31280\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\31280\go
set GOPRIVATE=
set GOPROXY=https://goproxy.io
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\31280\AppData\Local\Temp\go-build854252234=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I just want to use vscode to write my go code. But when I ready to write, The plugin always tell me I have an error, even there is nothing in the editor.

Just open an go file.

The prompt is like this:

![image](https://user-images.githubusercontent.com/59006329/98432193-b4112c00-20f6-11eb-8a22-8016016d4d16.png)

### What did you expect to see?

I do not want to see the prompt. Because it makes me anxious.

### What did you see instead?

Code hint function is also very slow.

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
