### ISSUE TITLE
cmd/go: mod tidy doesn't look in GOPATH when converting a legacy GOPATH project

### ISSUE THREAD

**Issue by dwschulze** [golang/go#42441]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.14
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
Ubuntu 19.10  
amd64

</pre></details>

### What did you do?

Migrating legacy GOPATH code to use modules.  Following [this blog post](https://blog.golang.org/migrating-to-go-modules) I run `go mod init bitbucket.org/username/reponame.git/integration-project/golang/lctlk8s` in the project root directory.  Then I run `go mod tidy` it gives

**$GOPATH/go.mod exists but should not**

If I change to the src/ directory and create the go.mod and run go tidy it fails to find to code in the current project and GOPATH:

go mod tidy
bitbucket.org/username/reponame.git/integration-project/golang/lctlk8s/cmd/lctlk8s imports
        internal/composerestclient: package internal/composerestclient is not in GOROOT (/home/dean/bin/go1.14.linux-amd64/go/src/internal/composerestclient)
bitbucket.org/username/reponame.git/integration-project/golang/lctlk8s/internal/composerestclient imports
        pkg/lctlutil: package pkg/lctlutil is not in GOROOT (/home/dean/bin/go1.14.linux-amd64/go/src/pkg/lctlutil)

Is this a bug in `go mod tidy` for not looking in the GOPATH, or is the blog post just wrong about how to migrate a legacy GOPATH project?

Here's my tree under the project root:

└── src
    ├── cmd
    │   └── lctlk8s
    │       └── lctlk8s.go
    ├── internal
    │   ├── composerestclient
    │   │   ├── compose.rest.client.go
    │   │   ├── json.strings.go
    │   │   ├── rest.client.structs.go
    │   │   └── version.go
    └── pkg
        ├── lctlutil
        │   ├── readascii.go
        │   └── readconf.go

**Comment by dwschulze** [comment]
The problem is that before you can run `go mod tidy` on the legacy project you have to add the module name to the import statements.  That needs to be included in that blog post.  Also the project used in the blog post has already been converted to modules so it doesn't illustrate anything.

**Comment by bcmills** [comment]
@stevetraut is working on new tutorial content for modules.

(We should take this feedback into account in the tutorials.)

**Comment by stevetraut** [comment]
I think the first place folks will look for information about what the command requires to run usefully is in the reference for go mod tidy. This behavior should be reflect in other module docs, but I don't think people will look there first because it's less immediate.

**Comment by bcmills** [comment]
In this case, I think what we're missing is probably a tutorial on “converting a GOPATH project to use modules” when the existing `GOPATH` contains packages that are intended to go in _different_ modules.

(Our existing blog post assumes that the whole `GOPATH` project is a single module, so it doesn't describe how to use `replace` directives to wire in other dependencies from outside of that module that can't — or can't yet — be fetched using `go get`.)

**Comment by stevetraut** [comment]
Can we set aside the content delivery vehicle for a moment and focus on what users need to be successful? What bits of information does a user need to have in order to successfully migrate GOPATH code to modules?

**Comment by bcmills** [comment]
In this particular case, the user needs to know that they should add `replace` directives in the `go.mod` file for their new module for for any existing dependencies that cannot be fetched using `go get`.

**Comment by bcmills** [comment]
At this point I'm not sure that it's worth adding a lot of new documentation on converting legacy projects, as a significant fraction of projects have already been converted to modules.
