### ISSUE TITLE
gollvm: At most two relocations per offset are supported, on Ubuntu(18?) (Github Actions)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [golang/go#42448]
I was investigating Microsoft's Github Actions.

[Here](https://github.com/advancedwebdeveloper/clang_test_cpu_features/blob/main/.github/workflows/llvm.yml) is my workflow config. scenario.
Check the version of the guest OS [here](https://github.com/actions/virtual-environments#available-environments).

Extracting one of the logs:
> $make --version && m4 --version && autoconf --version && automake --version
> GNU Make 4.1
> Built for x86_64-pc-linux-gnu
> m4 (GNU M4) 1.4.18
> autoconf (GNU Autoconf) 2.69
> automake (GNU automake) 1.15.1
.

Here is the error log:

https://gist.github.com/advancedwebdeveloper/4e79bbb26042f54cc1e780814c597e10

[logs_32.zip](https://github.com/golang/go/files/5506583/logs_32.zip)

**Comment by advancedwebdeveloper** [comment]
CC @hashtagchris @anthonysterling

**Comment by thanm** [comment]
The "At most two relocations per offset are supported" error is unrelated. 

Looking at your build log, you are trying to build and run gollvm with "make"-- this is not supported. Please use ninja instead. Thanks.
