### ISSUE TITLE
x/net: ReadBatch fails if conn passed to ipv4.New{Packet}Conn is not a net.{TCP/UDP}Conn

### ISSUE THREAD

**Issue by marten-seemann** [golang/go#42444]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/marten/Library/Caches/go-build"
GOENV="/Users/marten/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/marten/src/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/marten/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/q0/b5ynf00142l7bl9sp8y098zr0000gn/T/go-build393900320=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

When passing a wrapped connection to `ipv4.NewPacketConn()`, calls to `ReadBatch()` will fail with an `invalid connection` error:
```go
type wrappedConn { *net.UDPConn }
conn := ipv4.NewPacketConn(&wrappedConn{...})
conn.ReadBatch() // will return the "invalid connection" error
```

This is unexpected, as `NewPacketConn` accepts a `net.PacketConn`, and does not require a `net.UDPConn`.
Analogously for `NewConn` with a `net.TCPConn`.

The problem here is that the constructor calls `socket.NewConn`, which does a type assertion: https://github.com/golang/net/blob/ff519b6c91021e6316e1df005bc19f266994ddda/internal/socket/rawconn.go#L21-L41, which will fail if the `UPDConn` is wrapped.

### What did you expect to see?

I expected `ReadBatch` to work.

### What did you see instead?

See above.

**Comment by marten-seemann** [comment]
While one could argue that `ipv4.New{Packet}Conn` should take a concrete type (`net.TCPConn` / `net.UDPConn`) instead of an interface, there's a solution that doesn't require a breaking API change, while at the same time allowing for wrapped connections to be used: In that case `socket.NewConn()` would have to do an interface assertion instead of a type assertion. 

This is easy to accomplish, since `TCPConn`, `UDPConn` as well as `IPConn` each have methods that are unique to that type. For example, the `UDPConn` can be identified by its `ReadMsgUDP` method, the `IPConn` by its `ReadMsgIP` and the `TCPConn` by `SetLinger`. There are other methods that would also achieve the same result.

`socket.NewConn` would then look something like this:
```go
func NewConn(c net.Conn) (*Conn, error) {
	var err error
	var cc Conn
	if tcpConn, ok := c.(interface {
		SyscallConn() (syscall.RawConn, error)
		SetLinger() error
	}); ok {
		cc.network = "tcp"
		cc.c, err = tcpConn.SyscallConn()
	} else if udpConn, ok := c.(interface {
		SyscallConn() (syscall.RawConn, error)
		ReadMsgUDP(b, oob []byte) (n, oobn, flags int, addr *net.UDPAddr, err error)
	}); ok {
		cc.network = "udp"
		cc.c, err = udpConn.SyscallConn()
	} else if ipConn, ok := := c.(interface {
		SyscallConn() (syscall.RawConn, error)
		ReadMsgIP(b, oob []byte) (n, oobn, flags int, addr *net.IPAddr, err error)
	}); ok {
		cc.network = "ip"
		cc.c, err = ipConn.SyscallConn()
	} else
		return nil, errors.New("unknown connection type")
	}
	if err != nil {
		return nil, err
	}
	return &cc, nil
}
```

**Comment by networkimprov** [comment]
cc @odeke-em @ianlancetaylor

**Comment by marten-seemann** [comment]
Suggested fix: https://go-review.googlesource.com/c/net/+/271927.
