### ISSUE TITLE
`os.Args` parsing with quotes is somehow incorrect on Windows platform

### ISSUE THREAD

**Issue by marjune163** [golang/go#42443]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\vm\AppData\Local\go-build
set GOENV=C:\Users\vm\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\vm\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\vm\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\vm\AppData\Local\Temp\go-build776387174=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Source `test.go`:
```go
package main

import (
	"fmt"
	"os"
)

func main() {
	if len(os.Args) > 1 {
		fmt.Println(os.Args[1])
	}
}
```

run:
```cmd
go run test.go "D:\Data\"
```

### What did you expect to see?
Outputs `D:\Data\`

### What did you see instead?
Outputs `D:\Data\"`

**Comment by AlexRouSg** [comment]
You need to write `\\` instead of `\` as the shell/terminal will interpret it specially. 
e.g. `\n` will be translated to a newline character and `\"` would usually mean literal `"` insetad of quoting

**Comment by marjune163** [comment]
Thanks a lot!
