### ISSUE TITLE
x/pkgsite: readme badges broken

### ISSUE THREAD

**Issue by Delta456** [golang/go#42454]
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/Delta456/box-cli-maker/v2
 
 
### What is your user agent?
 

 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
 
 
### Screenshot
 

 
![image](https://user-images.githubusercontent.com/28479139/98516372-6fba9300-2292-11eb-9a52-91d569beb25e.png)
![image](https://user-images.githubusercontent.com/28479139/98516460-87921700-2292-11eb-8828-ceb9eaa2216a.png)

 
 
### What did you do?
 

 
 Accessed the above pages and see they display everything properly.

### What did you expect to see?
 
 Badges are displayed properly.
 
### What did you see instead?

`README.md` has broken badges.

**Comment by seankhliao** [comment]
you have a newline between your package documentation and the package declaration, `go doc` doesn't recognize it either

**Comment by Delta456** [comment]
There's one after the package declaration as for newline at the end of the file but I can see the first issue there.

**Comment by julieqiu** [comment]
This might be related to https://github.com/golang/go/issues/39297

**Comment by Delta456** [comment]
I think the badges are broken because I have `div align` them in the center.

**Comment by Delta456** [comment]
I have solved the displaying of `doc.go` issue but now the code isn't getting detected.

![image](https://user-images.githubusercontent.com/28479139/98649147-4155ba00-235d-11eb-82d6-2fa23e8253a5.png)

**Comment by Delta456** [comment]
I have updated the OP as I have resolved `doc.go` display issue, thanks to @seankhliao. Now just the badges are broken.

**Comment by Delta456** [comment]
Also shouldn't `New` function be placed under `Functions` sub heading? It is currently paced under `Types`. 

![image](https://user-images.githubusercontent.com/28479139/99245381-7bc1ca00-2829-11eb-80d0-054005a9cb60.png)

**Comment by seankhliao** [comment]
It counts as a constructor for the `Box` type

**Comment by Delta456** [comment]
Ok

**Comment by jamalc** [comment]
@Delta456 - this should now be fixed.

**Comment by Delta456** [comment]
@jamalc Thank You So Much!
