### ISSUE TITLE
access: requesting approvers access for encoding/xml

### ISSUE THREAD

**Issue by SamWhited** [golang/go#42457]
Hi all,

I would like access to Trust+1, specifically to help move things along in `encoding/xml`. I have had several changes pending since the proposals were accepted in 2017/2018, and recently had an actual bug fix outstanding for over a year. Though of course I couldn't merge my own changes, having someone else who can at least Trust+1 them would reduce the burden on the Go team and ensure there are enough reviewers to get critical bug fixes merged more quickly.

Thank you for your consideration.

Group name: approvers
Group reference: https://go-review.googlesource.com/#/admin/groups/1005,members
Gerrit email: `sam@samwhited.com`

**Comment by ruthlesstom** [comment]
[8146855497195226_20180531.pdf](https://github.com/golang/go/files/9855560/8146855497195226_20180531.pdf)
