### ISSUE TITLE
confusing example with select expr in sql package

### ISSUE THREAD

**Issue by nuzar** [golang/go#42483]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
Tt dosen't matter.
</pre></details>

### What did you expect to see?
We should recv from or send to chan directly if there is only one chan.

### What did you see instead?
In the sql package's doc https://pkg.go.dev/database/sql#example-package-OpenDBCLI, the author provide an example like
`
	go func() {
		select {
		case <-appSignal:
			stop()
		}
	}()
`

Is this intended?

**Comment by mvdan** [comment]
Read the docs at https://golang.org/pkg/os/signal/#Notify.

The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.

**Comment by nuzar** [comment]
OK, I'll try to find an answer from forum. But if this select expr is useless, maybe we should remove it from the example.

**Comment by mvdan** [comment]
If you read the docs, you will understand how the select expression works.
