### ISSUE TITLE
so crazy constraint! it's throw a error info if I defined one variable but not use it

### ISSUE THREAD

**Issue by YUbuntu0109** [golang/go#42481]
### What did you expect to see?
hey bro as a beginner I had learned the `Golang` language today, I found that it's will throw error tip if you defined variables or import one moudle in program but not use it . . . so crazy constraint compare to `Java` or `Python`. . . wish this issue will be improved in the feature version. . .

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.

**Comment by YUbuntu0109** [comment]
> The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.

ok bro thanks.

**Comment by YUbuntu0109** [comment]
> > The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
> 
> ok sorry bro.
