### ISSUE TITLE
x/pkgsite: gap below unit header is a bit large on desktop viewports

### ISSUE THREAD

**Issue by andybons** [golang/go#42490]
See screenshot below for the area I’m talking about. I think it could be tightened up a bit.

Great job, team!

<img width="1244" alt="Screen Shot 2020-11-10 at 3 24 10 PM" src="https://user-images.githubusercontent.com/365204/98729578-1e310780-2369-11eb-8876-88d056f57a7b.png">

**Comment by jamalc** [comment]
Oh yeah, good call. I'll take this.
