### ISSUE TITLE
cmd/go: support -overlay for the go mod subcommand

### ISSUE THREAD

**Issue by stamblerre** [golang/go#42491]
Currently, there is no way to pass the `-overlay` flag to `go mod tidy` or other such commands.

/cc @matloob

**Comment by matloob** [comment]
cc @jayconrod @bcmills 

This is a bug, we should fix this for 1.16

**Comment by heschik** [comment]
Is this going to land for 1.16?

**Comment by stamblerre** [comment]
@matloob: Will this be fixed for 1.16?

**Comment by jayconrod** [comment]
It looks like this was implemented in [CL 272126](https://go-review.googlesource.com/c/go/+/272126).

@matloob Please reopen if there's anything left to do here.
