### ISSUE TITLE
Cannot sign darwin / arm64 binaries (dyld_info out of place)

### ISSUE THREAD

**Issue by gjasny** [golang/go#42507]
Hello,

Code-signing of Darwin `arm64` binaries fails.

### What version of Go are you using (`go version`)?

<pre>
$ go version

go version devel +f2e186b877 Wed Nov 11 06:26:05 2020 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

N/A due to lacking arm64 support

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/gregorj/Library/Caches/go-build"
GOENV="/Users/gregorj/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/gregorj/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/gregorj/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/gregorj/src/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/gregorj/src/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="devel +f2e186b877 Wed Nov 11 06:26:05 2020 +0000"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/gregorj/Git/xcgopretty/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2m/qlwtkgc92k50mntftntz0k3w0000gn/T/go-build070598418=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

MacOS: 10.15.7
Xcode: 12.1

### What did you do?

Created an empty main.go:
```go
package main

func main() {


}
```

```
GOOS=darwin GOARCH=arm64 /Users/gregorj/src/go/bin/go build -o simple.arm64
codesign --sign MY_IDENTITY ./simple.arm64

codesign_allocate: fatal error: file not in an order that can be processed (dyld_info out of place): /Users/gregorj/Git/xcgopretty/simple.arm64
```

Signing an `amd64` binary works as expected.

Do you have an idea what's going on?

Thanks,
Gregor

**Comment by cherrymui** [comment]
Thanks for reporting. I don't know what the requirements for code-signing are, but I'll look into it.

**Comment by cherrymui** [comment]
@gjasny does CL https://go-review.googlesource.com/c/go/+/269377 help? (I don't know how to run code signing myself locally to test.)

You can check out the CL by
```
git fetch https://go.googlesource.com/go refs/changes/77/269377/1 && git checkout FETCH_HEAD
```
and rebuild the Go toolchain.

Thanks.

**Comment by gjasny** [comment]
Thank you for fixing this so fast. The codesign tool is now happy.

**Comment by gjasny** [comment]
Once that change hits master, are there nightly builds of golang published somewhere so that I don't have to wait for an 1.16 release?

**Comment by cherrymui** [comment]
Thanks for confirming!

No, we don't have nightly builds. Go 1.16 beta will be coming soonish, probably early December.
