### ISSUE TITLE
`Illegal instruction (core dumped)` when running go on FreeBSD 12.2 on i386 Pentium III 

### ISSUE THREAD

**Issue by sanjayregmi** [golang/go#42503]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.15.2,1
</pre>

### Does this issue reproduce with the latest release?
Yes for the version packaged with FreeBSD which is noted above.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

Of course the command dumps an error but here is the system details:
uname -a >> FreeBSD bsd 12.2-RELEASE FreeBSD 12.2-RELEASE r366954 GENERIC  i386
sysctl hw.model hw.machine hw.ncpu >>
hw.model: Intel(R) Pentium(R) III Mobile CPU       800MHz
hw.machine: i386
hw.ncpu: 1
</pre></details>

### What did you do?

type 'go' without quotes to get the error:
`Illegal instruction (core dumped)`

### What did you expect to see?
Go to run.

### What did you see instead?
`Illegal instruction (core dumped)`

**Comment by randall77** [comment]
If you haven't already, try running with `GO386=387`. See https://github.com/golang/go/wiki/MinimumRequirements#386
(Note: this will change to `GO386=softfloat` in 1.16.)

If you could show us the output of the freebsd equivalent of `cat /proc/cpuinfo` (`dmidecode`? `sysctl hw`? Not sure.), that might help. In particular, does it have sse2?

**Comment by martisch** [comment]
There are no Pentium III with SSE2 (was introduced in Pentium 4) so this could just be not having compiled the binary with GO386=387 to avoid the SSE2 instructions that CPU doesnt support.
