### ISSUE TITLE
x/pkgsite: uncaught JS errors on FireFox -- "Failed to execute 'close' on dialog"

### ISSUE THREAD

**Issue by eliben** [golang/go#42518]
### What is the URL of the page with the issue?
 
http://localhost:8080/github.com/gin-gonic/gin 
 
### What is your user agent?

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0
 
### Screenshot
 
![ff](https://user-images.githubusercontent.com/1130906/98841819-7e718900-23fd-11eb-932a-24883848702f.png)

 
### What did you do?

Press 'f' to jump to symbol, then select one of the identifiers 
 
### What did you expect to see? What did you see instead?

The jump works, but FireFox developer console prints out the error shown in the screenshot.

**Comment by jamalc** [comment]
Can't reproduce this one, its possible we've fixed it already. Please re-open if its still happening.
