### ISSUE TITLE
access: approvers access for x/tools

### ISSUE THREAD

**Issue by leitzler** [golang/go#42510]
Hi,

I would like access to Trust+1, mainly to shorten the process when authoring CL:s in x/tools.

Gerrit email: leitzler@gmail.com

https://go-review.googlesource.com/#/admin/groups/1005,members

**Comment by cagedmantis** [comment]
Hi Pontus,

Thank you for contributing to the Go project and helping with the tools! I've discussed this request with the teams (/cc @golang/release and @golang/tools-team ), and we agreed to grant you access. I've added you to the `may-start-trybots` and `approvers` groups now.

As you've probably seen at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a trybot run.

Similarly, please be aware of the rules for submitting and voting on CLs described at https://golang.org/wiki/GerritAccess#approver-access-approvers. If you're unsure or have any questions, please don't hesitate to ask us.

Thank you again, your help is greatly appreciated!

**Comment by leitzler** [comment]
Thanks for the trust, I make sure to ask if anything is unclear!
