### ISSUE TITLE
x/pkgsite: Failing to fetch new version of github.com/shazow/ssh-chat

### ISSUE THREAD

**Issue by shazow** [golang/go#42526]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/shazow/ssh-chat
 
### What is your user agent?

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.27 Safari/537.36
 
### Screenshot
 

![image](https://user-images.githubusercontent.com/6292/98864257-92d27780-2437-11eb-827d-15afc51b4019.png)
 
 
### What did you do?

Try to load a newer tag (v1.9 or v1.10) than the last one indexed by pkg.go.dev (v1.8.2, a year ago).
 
### What did you expect to see?
 
Docs for the v1.10 tag of my repo
 
### What did you see instead?

v1.10 is not found, v1.9 is not found, only v1.8.2 loads.

---

I'm sure this is somehow my fault, the ssh-chat repo went through a few iterations of migrating to go modules. I can't tell if ultimately it was done incorrectly, or whether I somehow got it into a broken state that can't be repaired.

I tried pushing newer tags, I tried messing with the go.mod file, but it's not obvious to me what's wrong.

If this is my error, it might be helpful if the "Not found" page linked to some documentation about what to do if I was expecting to see a valid version but it's not showing up. :)

**Comment by tobiaskohlbau** [comment]
Version v1.10 is not SemVer compatible try tagging v1.10.0 and fetching again. This should resolve your issue.

Citing from [here](https://github.com/golang/go/wiki/Modules#modules):
> Modules must be semantically versioned according to semver, usually in the form v(major).(minor).(patch), such as v0.1.0, v1.2.3, or v1.5.0-rc.1. The leading v is required. If using Git, tag released commits with their versions. Public and private module repositories and proxies are becoming available (see FAQ below).

**Comment by shazow** [comment]
@tobiaskohlbau You're absolutely right! Thank you.
