### ISSUE TITLE
x/pkgsite: remove github.com/youthlin/streams

### ISSUE THREAD

**Issue by youthlin** [golang/go#42531]
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/youthlin/streams
 
 
### What is your user agent?
N/A
 
### Screenshot
N/A
 
 
### What did you do?
N/A
 
 
### What did you expect to see?
Remove this package since `github.com/youthlin/streams` doesn't exist now. 
It has been rename to `github.com/youthlin/stream`

### What did you see instead?
godoc.org can remove automaticly, but pkg.go.dev not.

**Comment by julieqiu** [comment]
Done
