### ISSUE TITLE
x/pgksite: dev mode doesn't actually serve non-minified JS

### ISSUE THREAD

**Issue by eliben** [golang/go#42540]
The usage of `./cmd/frontend` says:

```
  -dev
    	enable developer mode (reload templates on each page load, serve non-minified JS/CSS, etc.)
```

However, from some experimentation this doesn't appear to be happening. If I modify a .js file and re-run the frontend, the modification is not applied until I compile the .js file into a minified version with `./devtools/compile_js.sh`.

Perhaps I'm holding it wrong?

A quick look at the code makes me believe this indeed isn't implemented. While in devMode the server calls `parsePageTemplates` anew each time a template is requested, the template files directly refer to minified JS, e.g.:

```
  <script>
    loadScript("/static/js/playground.min.js");
  </script>
```

**Comment by eliben** [comment]
Related to #40960

**Comment by jamalc** [comment]
Thanks for bringing this up, we definitely want to tackle this as part of #40960. More detailed plans coming soon.
