### ISSUE TITLE
runtime: "sweep increased allocation count" on linux/arm64 during bootstrap

### ISSUE THREAD

**Issue by bcmills** [golang/go#42543]
[2020-11-11T20:26:44-b641f0d/linux-arm64-packet](https://build.golang.org/log/5442553355a3a2c377d2ca54841a6f08049905a2)

Possibly related to #32026; see also #21729.

CC @aclements @mknyszek

**Comment by cherrymui** [comment]
Looks like the bootstrap compiler crashes? It could be due to an old bug in the bootstrap toolchain.

**Comment by bcmills** [comment]
`greplogs --dashboard -md -l -e '# bootstrap/.*\n(.*\n)*fatal error: sweep increased allocation count' --since=2021-01-01`

[2022-03-20T16:05:03-6673d5d/linux-arm64-packet](https://build.golang.org/log/9dc1a0e50599b2021e18f73f767bf2c75b280912)

**Comment by bcmills** [comment]
This should be fixed by #44505, assuming that that actually happens as planned for Go 1.19.

**Comment by ianlancetaylor** [comment]
Rolling forward to 1.20 milestone.

**Comment by rsc** [comment]
Builders are now on Go 1.17. This should stop happening.

**Comment by aclements** [comment]
There have been no occurrences of this since the 2022-03-02 log @bcmills linked above, and we have reason to believe this is fixed, so I'm going to close this. If it does happen again, we can reopen.
