### ISSUE TITLE
feature: regexp: support pattern '\1'

### ISSUE THREAD

**Issue by Eraac** [golang/go#42549]
Add the possibility to use the contents in capture in a regex with the pattern `\1`

These kinds of regex doesn't work `(\d+):\1`; `\1` should be equal to the content of the first capture `\d+`
```
# https://play.golang.org/p/6jLRaiw2-BC
panic: regexp: Compile(`(\d+):\1`): error parsing regexp: invalid escape sequence: `\1`
```

This will be useful for some app who use the package regexp (ex. prometheus)

**Comment by mvdan** [comment]
See previous questions, like https://stackoverflow.com/questions/23968992/how-to-match-a-regex-with-backreference-in-go.

**Comment by ianlancetaylor** [comment]
This is working as designed, sorry.  See the discussion at https://swtch.com/~rsc/regexp/.
