### ISSUE TITLE
encoding/asn1: string type tags are not documented to work in Unmarshal

### ISSUE THREAD

**Issue by mjg59** [golang/go#42570]
### What version of Go are you using (`go version`)?

1.14

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

linux amd64

### What did you do?

I have the following struct:

```
type ComponentIdentifierV2 struct {
        ComponentClass           ComponentClass
        ComponentManufacturer    string
        ComponentModel           string
        ComponentSerial          string                `asn1:"optional,tag:0"`
        ComponentRevision        string                `asn1:"optional,tag:1"`
        ComponentManufacturerID  int                   `asn1:"optional,tag:2"`
        FieldReplaceable         bool                  `asn1:"optional,tag:3"`
        ComponentAddresses       []ComponentAddress    `asn1:"optional,tag:4"`
        ComponentPlatformCert    CertificateIdentifier `asn1:"optional,tag:5"`
        ComponentPlatformCertURI string                `asn1:"optional,tag:6"`
        Status                   asn1.Enumerated       `asn1:"optional,tag:7"`
}
```

Note that ComponentRevision is tag:1, so context specific. The fact that it's a string means that getUniversalType() will return PrintableString, and this will not be overridden because there's no explicit tag type in the encoded stream.

The spec definition of this struct is:

```
ComponentIdentifier ::= SEQUENCE {
componentClass ComponentClass,
componentManufacturer UTF8String (SIZE (1..STRMAX)),
componentModel UTF8String (SIZE (1..STRMAX)),
componentSerial[0] IMPLICIT UTF8String (SIZE (1..STRMAX)) OPTIONAL,
componentRevision [1] IMPLICIT UTF8String (SIZE (1..STRMAX)) OPTIONAL,
componentManufacturerId [2] IMPLICIT PrivateEnterpriseNumber OPTIONAL,
fieldReplaceable [3] IMPLICIT BOOLEAN OPTIONAL,
componentAddresses [4] IMPLICIT SEQUENCE(SIZE(1.. MAX)) OF ComponentAddress OPTIONAL
componentPlatformCert [5] IMPLICIT CertificateIdentifier OPTIONAL,
componentPlatformCertUri [6] IMPLICIT URIReference 
}
```

ie, componentRevision is a UTF8String, not a PrintableString. The certificate I'm parsing has an @ sign in, which is legitimate in a UTF8String but not a PrintableString. Since we have no explicit information in the stream to treat this as a UTF8String we continue treating it as a PrintableString, and then fail because of the "invalid" character.

### What did you expect to see?

A string containing an @ sign.

### What did you see instead?

asn1: syntax error: PrintableString contains invalid character

**Comment by mjg59** [comment]
This actually works if I do:

`asn1:"utf8,optional,tag:1"`

which is documented as doing something in Marshal() but not in Unmarshal().

**Comment by ericchiang** [comment]
I can take the documentation fix
