### ISSUE TITLE
x/talks/content/2012: {waza,concurrency}.slide are broken because of a # comment on top

### ISSUE THREAD

**Issue by nasuku** [golang/go#42572]
The links to the slides from the blog page https://blog.golang.org/waza-talk are broken.

Would be great if the links are fixed. If not, atleast remove the broken link.

**Comment by dmitshur** [comment]
Thanks for reporting. Are you referring to the link to https://talks.golang.org/2012/waza.slide?

It looks like the link is okay, but the slides themselves are broken.

I think it's related to #33955; those slides have [a comment on top](https://github.com/golang/talks/blob/0327d39cfe0334e69cc5f31a4d69910c81f169a4/content/2012/waza.slide#L1-L3) that begins with "#" and it makes `present` wrongly select the new Markdown format. CC @rsc.

**Comment by dmitshur** [comment]
As reported in #42639, this is also affecting https://talks.golang.org/2012/concurrency.slide, which is linked from https://tour.golang.org/concurrency/11.

**Comment by dmitshur** [comment]
This was resolved in [CL 284392](https://golang.org/cl/284392), as part of similar issue #43455.
