### ISSUE TITLE
net/http: race in http2Transport [1.14 backport]

### ISSUE THREAD

**Issue by dmitshur** [golang/go#42586]
@answer1991 requested issue #31192 to be considered for backport to the next 1.14 minor release.

> Kubernetes team had already announced GOAWAY feature in [Kubernetes v1.19 release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md). However, if Kubernetes enable GOAWAY feature, the client will receive unexpected 500 status code errors which I described at #41234, and there is no workaround. I think backport is necessary.
>
> @gopherbot ple​ase backport, as Kubernetes is affected and there is no workaround.

(The corresponding 1.15 backport request is #42539.)

**Comment by answer1991** [comment]
We should also backport #42498.

**Comment by cagedmantis** [comment]
We are taking a little more time to review this before deciding.

**Comment by toothrot** [comment]
This is a serious issue with no workaround. Approved.

**Comment by dmitshur** [comment]
To resolve this backport issue, [CL 253259](https://golang.org/cl/253259) (for #31192) and [CL 269058](https://golang.org/cl/269058) (for #42498) will need to be backported to the x/net's `release-branch.go1.14` branch, and then the bundled copy of `golang.org/x/net/http2` in `net/http` needs to be updated. The process is described in https://golang.org/wiki/MinorReleases#making-cherry-pick-cls.

**Comment by dmitshur** [comment]
(This was closed early due to #29599.)

Reopening for updating the vendored/bundled version in the the main repository.

**Comment by dmitshur** [comment]
Closed by merging a2e2011637b47572f66cb2715b887737bb0e191f to `release-branch.go1.14`.
