### ISSUE TITLE
cmd/compile: missed obvious BCE

### ISSUE THREAD

**Issue by josharian** [golang/go#42603]
Simplified from some real code:

```go
func f(b []byte, x int, p *uint16) {
	switch x {
	case 0:
		if len(b) < 20 {
			return
		}
		*p = binary.BigEndian.Uint16(b[:2])
	case 1:
		if len(b) < 40 {
			return
		}
		*p = binary.BigEndian.Uint16(b[:2])
	}
}
```

The compiler inserts a bounds check on the first `binary.BigEndian.Uint16(b[:2])`, but not the second one. If you remove the `case 1` case, the compiler can eliminate the bounds check!

cc @zdjones @randall77

**Comment by zdjones** [comment]
A quick look at the SSA that prove sees, and my intuition says that prove should indeed be removing both checks. I will look into this more.

**Comment by cuonglm** [comment]
The problem is that we only keep 1 slice len/cap SSA value in fact table, so when updating fact table for it, we don't update in all places. In the meantime, you can do:

```
func f(b []byte, x int, p *uint16) {
	l := len(b)
	switch x {
	case 0:
		if l < 20 {
			return
		}
		*p = binary.BigEndian.Uint16(b[:2])
	case 1:
		if l < 40 {
			return
		}
		*p = binary.BigEndian.Uint16(b[:2])
	}
}
```

to help compiler proving them.
