### ISSUE TITLE
cmd/go: go1.15.5 breaks LDFLAGS=-std=c++14

### ISSUE THREAD

**Issue by aykevl** [golang/go#42606]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, with Go 1.15.5 released a few days ago.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ayke/.cache/go-build"
GOENV="/home/ayke/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ayke/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ayke:/home/ayke"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build201769525=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I put two files in a new directory.
`main.go`:

```go
package main

// void hello(void);
import "C"

func main() {
	C.hello()
}
```

`main.cpp`:
```cpp
#include <cstdio>

extern "C"
void hello(void) {
	printf("hello!\n");
}
```

And then I ran this code using

    CGO_LDFLAGS=-std=c++14 go run .

### What did you expect to see?

The following message should be printed:

    hello!

This works in Go 1.15.4 at least. I've also tested some version of Go 1.14 in which it works.

### What did you see instead?

    go build runtime/cgo: invalid flag in go:cgo_ldflag: -std=c++14

It seems to me that `-std=c++14` is a perfectly safe flag, I've been using it for quite some time.

I suspect https://github.com/golang/go/issues/42562 is the cause.

**Comment by ALTree** [comment]
cc @ianlancetaylor

**Comment by aykevl** [comment]
It looks like I have a workaround.

**Comment by ianlancetaylor** [comment]
Yes, my apologies.  Because it was a security patch that was kept quiet until the release, it was hard to do proper widescale testing.  The workaround is to copy `CGO_LDFLAGS` into `CGO_LDFLAGS_ALLOW`.  This will be fixed in the next release.

Closing as a dup of #42567.

**Comment by aykevl** [comment]
Oops, looks like I didn't properly search for duplicates first.
Thank you for the quick response!
