### ISSUE TITLE
The Ugly Generic,might as well not have it.

### ISSUE THREAD

**Issue by Yanwenjiepy** [golang/go#42608]
Go doesn't really need a generic, and it's better to optimize performance than to get a generic for Go to have a generic as a feature.

Some developers with experience in other languages want to use features in Go that they use in other languages, and then they ask Go to add this or that feature (there's always someone who wants to add try-catch to Go's error handling).

For now, many people don't feel that Go needs generics very much, and the existing generic proposal isn't very well liked (many people complain that it doesn't use `<>` but instead uses `[]`).

Go is Go, Go has its own style, simple, efficient, and engineered.

**Comment by mdlayher** [comment]
This is an issue tracker. I'm closing this.
