### ISSUE TITLE
x/build: add a Windows ARM64 builder

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#42604]
A builder should be added in support of the Windows/arm64 port #36439

Note: this is independent of #38607 which adds a Windows arm builder.

@golang/release

**Comment by zx2c4** [comment]
I have a ARM64 builder now, with a preinstalled gcc for each architecture supported on the machine:

![image](https://user-images.githubusercontent.com/10643/99798714-c5fcc100-2b31-11eb-979d-aec043f6ec4d.png)

**Comment by zx2c4** [comment]
CC @aclements @alexbrainman @jstarks

**Comment by toothrot** [comment]
As mentioned in cl/322655, we occasionally hit a CLOCK_WATCHDOG_TIMEOUT or failure to boot the vm with `-smp` set higher than 4. I'm still investigating a fix to this. 

With `-smp 4`, it takes us about 33 minutes from VM creation to completion to run a build, which is longer than I'd like. Also, I'd like to use all the resources we're paying for on the `a1.metal` instances.

**Comment by zx2c4** [comment]
Looks like you guys have this sorted now for arm64. My arm builder is running the same 64-bit OS, but simply building for GOARCH=arm GOARM=7 GOOS=windows and testing that. You guys should be able to do the same with better resources than my raspi. So, I'll be decommissioning that shortly, and you can build a new one on AWS as you've done for 64-bit.

**Comment by toothrot** [comment]
@zx2c4 Sounds good. Thanks so much for your assistance! Your help was very useful in getting this set up, and thanks for providing builders in the interim.

**Comment by toothrot** [comment]
Filed #47018 and #47017 to cover some of the remaining work on this buildlet. I'll leave this open until the existing configuration is checked in.
