### ISSUE TITLE
x/tools/go/ssa: BuilderMode methods do not handle `BareInits` option

### ISSUE THREAD

**Issue by mlevesquedion** [golang/go#42614]
The documentation for `ssa.BuilderMode` states:
```go
const BuilderModeDoc = `Options controlling the SSA builder.
The value is a sequence of zero or more of these letters:
...
I	build bare [I]nit functions: no init guards or calls to dependent inits.
`
```

In fact, the `I` option is not handled by the `String` and `Set` methods on `BuilderMode`. In practice, this means that using the `BareInits` option is inaccessible through e.g. `ssadump`:

```shell
$ ssadump -build=I main.go
invalid value "I" for flag -build: unknown BuilderMode option: 'I'
```

**Comment by findleyr** [comment]
CC @alandonovan 

I accepted this fix, but probably should have confirmed that this was an accidental omission in https://golang.org/cl/5172. If not, please let me know and I'll revert.
