### ISSUE TITLE
x/mobile: failed to pull the signing certificate to determine your team ID

### ISSUE THREAD

**Issue by arcln** [golang/go#42615]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.4 darwin/amd64
gomobile master (973feb43)
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/arthur/Library/Caches/go-build"
GOENV="/Users/arthur/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/usr/local/go/path/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/usr/local/go/path"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/arthur/Code/Misc/mobile/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sp/h4_s8zf552v7rdr_gfp3bbdw0000gn/T/go-build678027763=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

`$ gomobile build -target=ios -bundleid=com.example.test golang.org/x/mobile/example/basic`

### What did you expect to see?

The app should be successfully built.

### What did you see instead?

`gomobile: failed to pull the signing certificate to determine your team ID: exit status 44`

This is due to [build_iosapp.go:159](https://github.com/golang/mobile/blob/973feb4309de5c3aad0553fc987d76abf1fa58f7/cmd/gomobile/build_iosapp.go#L159) that has hardcoded "iPhone Developer" for the certificate name. I don't have an Apple developer account so I don't have any "iPhone Developer" certificate in my keychain. However I do have an "Apple Developer" certificate that is able to sign the app for development. I should be able to use it.

I fixed this by adding a `-codesign` flag to the `gomobile build` command, that takes a string and passes it to `security -c` instead of the hard-coded "iPhone Developer". I also added a special value "none" to completely bypass code signing. Should I submit thoose changes?

**Comment by imWildCat** [comment]
@cagedmantis @hyangah Hi, any suggestion for running this test locally?

**Comment by changkun** [comment]
This should be fixed in [CL 346151](https://go-review.googlesource.com/c/mobile/+/346151). We may close it directly.

(Sorry for not referring to it directly in the CL.)

cc @dmitshur @hajimehoshi

**Comment by dmitshur** [comment]
Thanks for fixing this @changkun. Closing.
