### ISSUE TITLE
cmd/go: `go get all` tries to update package in GOROOT, throws permission error

### ISSUE THREAD

**Issue by FallenWarrior2k** [golang/go#42620]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/<redacted>/.cache/go-build"
GOENV="/home/<redacted>/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/<redacted>/.local/share/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/<redacted>/.local/share/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build135625205=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I use Go as provided by my distro's (Arch Linux) package manager. As such, my GOROOT is a directory that my user does not have permission to make changes to.
I also have the [`community/libguestfs`](https://www.archlinux.org/packages/community/x86_64/libguestfs/) package installed for unrelated reasons. This package, however, installs some files to GOROOT:
```
$ pacman -Ql libguestfs | grep `go env GOROOT`
libguestfs /usr/lib/go/
libguestfs /usr/lib/go/pkg/
libguestfs /usr/lib/go/pkg/linux_amd64/
libguestfs /usr/lib/go/pkg/linux_amd64/libguestfs.org/
libguestfs /usr/lib/go/pkg/linux_amd64/libguestfs.org/guestfs/
libguestfs /usr/lib/go/pkg/linux_amd64/libguestfs.org/guestfs/guestfs.a
libguestfs /usr/lib/go/src/
libguestfs /usr/lib/go/src/pkg/
libguestfs /usr/lib/go/src/pkg/libguestfs.org/
libguestfs /usr/lib/go/src/pkg/libguestfs.org/guestfs/
libguestfs /usr/lib/go/src/pkg/libguestfs.org/guestfs/guestfs.go
libguestfs /usr/lib/go/src/pkg/libguestfs.org/guestfs/guestfs_010_load_test.go
libguestfs /usr/lib/go/src/pkg/libguestfs.org/guestfs/guestfs_020_create_test.go
libguestfs /usr/lib/go/src/pkg/libguestfs.org/guestfs/guestfs_030_create_flags_test.go
libguestfs /usr/lib/go/src/pkg/libguestfs.org/guestfs/guestfs_040_create_multiple_test.go
libguestfs /usr/lib/go/src/pkg/libguestfs.org/guestfs/guestfs_050_handle_properties_test.go
libguestfs /usr/lib/go/src/pkg/libguestfs.org/guestfs/guestfs_060_explicit_close_test.go
libguestfs /usr/lib/go/src/pkg/libguestfs.org/guestfs/guestfs_070_optargs_test.go
libguestfs /usr/lib/go/src/pkg/libguestfs.org/guestfs/guestfs_100_launch_test.go
libguestfs /usr/lib/go/src/pkg/libguestfs.org/guestfs/guestfs_900_rstringlist_test.go
```

### What did you expect to see?
`go get all` should continue to work normally.

### What did you see instead?
Ever since installing this package, `go get all` (with or without `-u`) fails with `go get pkg/libguestfs.org/guestfs: mkdir /usr/lib/go/pkg/linux_amd64/pkg: permission denied`.

**Comment by seankhliao** [comment]
This is a packaging issue with `community/libguestfs`, the issue should be raised in Arch's bugtracker for this

**Comment by bcmills** [comment]
Agreed; this does not appear to be a bug in the `go` command proper. It is expected that users cannot reinstall a stale binary in `GOROOT/src` when they do not have permission to write to `GOROOT/pkg`.

On the other hand, it is _not_ expected that distros add their own package to `GOROOT/src`. That location is reserved for the Go standard library.
