### ISSUE TITLE
x/website: HTTP 500 error for concurrency slides

### ISSUE THREAD

**Issue by flwyd** [golang/go#42639]
The page https://talks.golang.org/2012/concurrency.slide (linked from https://tour.golang.org/concurrency/11) returns an HTTP 500 error with message `unexpected EOF`.  The other slide deck linked from that tour page, https://talks.golang.org/2013/advconc.slide, works fine.

**Comment by dmitshur** [comment]
Thanks for reporting.

This is another instance of #42572, so I'll merge this issue into that one.
