### ISSUE TITLE
x/pkgsite: does not recognize HPND license

### ISSUE THREAD

**Issue by aecay** [golang/go#42643]
### What is the URL of the page with the issue?
 
 <https://pkg.go.dev/bazil.org/fuse>
 
### What did you do?
 
The pkg.go.dev site for the https://github.com/bazil/fuse package does not show the package's documentation because of a license issue.  The licensecheck result for the package's [LICENSE](https://github.com/bazil/fuse/blob/master/LICENSE) is:

```
95.8% of text covered by licenses:
BSD-3-Clause at [0:1532] IsURL=false
HPND at [1594:2529] IsURL=false
BSD-2-Clause at [2643:4165] IsURL=false
```
 
[HPND](https://spdx.org/licenses/HPND.html) (historial permission notice and disclaimer) is not included on the list of [recognized licenses](https://pkg.go.dev/license-policy).  Can that license be added to the list?  It is [OSD-compliant](https://opensource.org/licenses/HPND).
 
### What did you expect to see?
That the documentation for this package would be displayed
 
### What did you see instead?
A license error.

**Comment by jamalc** [comment]
Legal has approved this license and it has been added to the acceptable list, however, it looks like there is a lot of variation in the ‘official’ license text which may be hard to automatically detect and validate. /cc @jba

**Comment by jba** [comment]
The license is now recognized and accepted, and the docs are displayed.
