### ISSUE TITLE
Building gollvm with Github Actions: "grep: gen-sysinfo.go: No such file or directory" and "error: At most two relocations per offset are supported"

### ISSUE THREAD

**Issue by advancedwebdeveloper** [golang/go#42651]
### What version of Go are you using (`go version`)?

gollvm aka Go 1.15.5

### Does this issue reproduce with the latest release?
Indeed

### What operating system and processor architecture are you using (`go env`)?
 Ubuntu  18.04.5  LTS, adopted for Azure's instances

### What did you do?

I was trying to use Github Actions to automate gollvm's release process.
[My run](https://github.com/advancedwebdeveloper/clang_test_cpu_features/actions/runs/364964903)

### What did you expect to see?
Successful compilation of libgo and all required sub-targets.

### What did you see instead?
Well, I see that llvm-goc is built.
I see that the back-end test suite ran successfully.
But some auto-generation not working normally, for gen-sysinfo.go.

Consider checking archived logs [here](https://github.com/advancedwebdeveloper/clang_test_cpu_features/suites/1505829196/logs) and a single file/raw listing [here](https://github.com/advancedwebdeveloper/clang_test_cpu_features/commit/d1d2e11167c99f900aaece864d4fa46047c47f85/checks/1403757486/logs) .

I see the first occurrence of reported file absence at

> 2020-11-15T23:36:42.1083177Z [1537/2664] Creating /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/build_release/tools/gollvm/libgo/tmp-os_user_linknames.go
> 2020-11-15T23:36:42.1089654Z **grep: gen-sysinfo.go: No such file or directory** 
. It is repeating dozens of times.

> 2020-11-15T23:36:42.8153253Z [1560/2664] Generating /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/build_release/tools/gollvm/libgo/gen-sysinfo.go
> 2020-11-15T23:36:42.8164171Z error: At most two relocations per offset are supported

Probably a verbose logging should be enabled, to track this.
Btw is it depending on Clang's version?

I think it is triggered [here](https://github.com/llvm/llvm-project/blob/0ec5baa1324d61e79bc21a1307ea52aa43a12352/llvm/lib/DebugInfo/DWARF/DWARFContext.cpp#L1816) .

CC @thanm @cherrymui @ianlancetaylor

**Comment by thanm** [comment]
Thanks for the report. 

"At most two relocations per offset" is a red herring, but the problem with gen-sysinfo.go looks like a missing dependency. I will send a CL.

**Comment by thanm** [comment]
Checked in https://go.googlesource.com/gollvm/+/4576dabb5d51054895d04c16d03daba36291c82a with fix, closing now. Please reopen if there are still issues, thanks.
