### ISSUE TITLE
cmd/link: unknown relocation type 284 on netbsd-arm64

### ISSUE THREAD

**Issue by bsiegert** [golang/go#42660]
In the cases where none of the other current sources of flakiness prevent finishing the build, the test run on the `netbsd-arm64-bsiegert` builder finishes with this error:

```
##### ../misc/cgo/test
PASS
ok  	misc/cgo/test	41.606s
# misc/cgo/test.test
/var/gobuilder/buildlet/tmp/go-build335358639/b057/_pkg_.a(_x001.o): unknown relocation type 284; compiled without -fpic?
FAIL	misc/cgo/test [build failed]
2020/11/13 17:12:45 Failed: exit status 2
go tool dist: FAILED
```
https://build.golang.org/log/bead76b2d0066e4561eea39a0d55057e96cd8813
https://build.golang.org/log/3c34916162f58056f80512f3486dc9f99fb65883
https://build.golang.org/log/31691975f27101b3386bbfe816fcc99a3d0c2edd

The earliest instance of this is after https://go-review.googlesource.com/c/go/+/269337 was submitted, hence /cc @aclements @ianlancetaylor.

**Comment by cherrymui** [comment]
284 is R_AARCH64_LDST16_ABS_LO12_NC. The linker supports R_AARCH64_LDST{8,32,64,128}_ABS_LO12_NC, R_AARCH64_LDST32_ABS_LO12_NC. Maybe it should support R_AARCH64_LDST16_ABS_LO12_NC as well.

cc @erifan

**Comment by erifan** [comment]
Ok, I'll take a look.
