### ISSUE TITLE
dev.regabi: create dev branch for register ABI implementation

### ISSUE THREAD

**Issue by aclements** [golang/go#42668]
The Go runtime/compiler team would like to continue developing support for the register ABI (#40724) during the code freeze so it can be landed when Go 1.17 opens for development. Hence, we're requesting the creation of a "dev.regabi" branch. It can be branched off of whatever the current "master" is.

/cc @golang/osp-team

**Comment by dmitshur** [comment]
Done. `dev.regabi` is created and currently points to commit 0968d2d599189229145b1000cec55d9df47fbc98.

As a friendly observation, the code freeze is intended to shift focus on completing the Go 1.16 release, but I understand the Go runtime/compiler team will exercise careful judgement when balancing where to spend their time, taking into account any release-blocking issues. Thank you.
