### ISSUE TITLE
x/tools/cmd/getgo: uses incorrect "latest" url

### ISSUE THREAD

**Issue by fmpwizard** [golang/go#42676]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.5.55
</pre>

But the golang/tools commit that has this problem is the latest as of today 2020/11/17

 `9036a0f9af11674fea137b794a0a2e6aef6882e1`

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Not relevant but: 

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/wizard/.cache/go-build"
GOENV="/home/wizard/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/mnt/extra/gopath/pkg/mod"
GONOPROXY="github.com/tradellama"
GONOSUMDB="github.com/tradellama"
GOOS="linux"
GOPATH="/mnt/extra/gopath"
GOPRIVATE="github.com/tradellama"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/mnt/extra/code/work/tradellama/goat/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build370880754=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

1. `curl -LO https://get.golang.org/$(uname)/go_installer && chmod +x go_installer && ./go_installer -i`
2.  Got:

Welcome to the Go installer!
Would you like to install Go? Y/n [Y]: y
The latest go version is go1.15.4, install that? Y/n [Y]: 

### What did you expect to see?

go1.15.5 being offered

### What did you see instead?

go.1.15.4

### Possible fix:

this line

https://github.com/golang/tools/blob/master/cmd/getgo/download.go#L24

gets the version that the golang.org site "runs" but at this this time, the site doesn't run the latest. We should instead use:

https://golang.org/dl/?mode=json

Which was suggested on the mailing list
https://groups.google.com/g/golang-nuts/c/kweFo4TE4N0/m/XyH-tI0OBQAJ

**Comment by dmitshur** [comment]
CC @golang/release.

**Comment by dmitshur** [comment]
I agree that switching it to use the https://golang.org/dl/?mode=json API endpoint is the right fix.

**Comment by dmitshur** [comment]
@fmpwizard [CL 270878](https://golang.org/cl/270878) has some outstanding review comments, once addressed it should be good to submit. Are you able to take a look?

**Comment by fmpwizard** [comment]
Hi @dmitshur yes, I'll take care of the comments, it may be a few more days but I'm still planning on addressing them.
Thank you!

**Comment by dmitshur** [comment]
That sounds good, thank you!
