### ISSUE TITLE
gccgo: Can't use golang.org/x/sys/unix

### ISSUE THREAD

**Issue by WinLinux1028** [golang/go#42683]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/yjsnpi/.cache/go-build"
GOENV="/home/yjsnpi/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/yjsnpi/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/yjsnpi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/yjsnpi/go/src/golang.org/x/sys/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build182228207=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I tryed to compile Discord bot in gccgo. (It can build on gc)
But gccgo errors.

### What did you see instead?
/home/yjsnpi/go/src/golang.org/x/sys/unix/gccgo.go:21: error: undefined reference to 'golang.x2eorg..z2fx..z2fsys..z2funix.realSyscallNoError'
/home/yjsnpi/go/src/golang.org/x/sys/unix/gccgo.go:28: error: undefined reference to 'golang.x2eorg..z2fx..z2fsys..z2funix.realSyscall'
/home/yjsnpi/go/src/golang.org/x/sys/unix/gccgo.go:35: error: undefined reference to 'golang.x2eorg..z2fx..z2fsys..z2funix.realSyscall'
/home/yjsnpi/go/src/golang.org/x/sys/unix/gccgo.go:42: error: undefined reference to 'golang.x2eorg..z2fx..z2fsys..z2funix.realSyscall'
/home/yjsnpi/go/src/golang.org/x/sys/unix/gccgo.go:48: error: undefined reference to 'golang.x2eorg..z2fx..z2fsys..z2funix.realSyscallNoError'
/home/yjsnpi/go/src/golang.org/x/sys/unix/gccgo.go:53: error: undefined reference to 'golang.x2eorg..z2fx..z2fsys..z2funix.realSyscall'
collect2: error: ld returned 1 exit status

**Comment by ianlancetaylor** [comment]
What version of gccgo are you using?

Have you tried building using the version of the go tool that comes with gccgo, rather than the version of the go tool distributed with the gc toolchain?

**Comment by WinLinux1028** [comment]
I used Go 1.15.5( https://golang.org/dl/ ) and latest gccgo( https://gcc.gnu.org/git/?p=gcc.git;a=shortlog;h=refs/heads/devel/gccgo )

**Comment by ianlancetaylor** [comment]
To use tip gccgo you'll need to use the version of the go tool that comes with gccgo, not the version from the Go 1.15.5 release.  (The tip gc release should work also.)

**Comment by WinLinux1028** [comment]
Thank you, I'll try it.

**Comment by WinLinux1028** [comment]
The probrem was fixed.
Thank you to answer the question!
