### ISSUE TITLE
x/pkgsite: Forks are counted as imports

### ISSUE THREAD

**Issue by lu4p** [golang/go#42697]
### What is the URL of the page with the issue?

Example: https://pkg.go.dev/github.com/lu4p/binclude?tab=importedby
 
 
### Screenshot
 

![Screenshot_2020-11-18 binclude · pkg go dev(1)](https://user-images.githubusercontent.com/46541492/99530922-455b8a80-29a2-11eb-968e-9d312de321d3.png)

 
### How to reproduce
 

Create a repo on github with a subpackage which imports the root package:

Example:
```
github.com/user/foo - root package
github.com/user/foo/cmd/foo - imports foo
```
Then fork the repo with another user.
 

### What did you expect to see?
Package has no importers.
 
### What did you see instead?
Package is imported by the fork.

**Comment by bcmills** [comment]
This appears to be correct. If you click through the link, you'll find exactly one version of that module (`v0.0.0-20200630183912-8068350e017e`), and at that version it really is a [distinct module](https://github.com/audiolion/binclude/blob/8068350e017e7d1c0720902a3488505e838b18c1/go.mod#L1) that [imports packages from](https://github.com/audiolion/binclude/blob/8068350e017e7d1c0720902a3488505e838b18c1/bincludegen/gen.go#L17) the upstream module.
