### ISSUE TITLE
x/tools/gopls: set experimentalDiagnosticsDelay to 250ms by default

### ISSUE THREAD

**Issue by stamblerre** [golang/go#42693]
We are still ironing out the details of this setting (https://golang.org/cl/269677 will address some of them), but eventually, it should be enabled by default.

**Comment by myitcv** [comment]
Can you explain what this setting will actually do, or point me towards a CL/similar?

**Comment by stamblerre** [comment]
Here are the docs for it: https://github.com/golang/tools/blob/master/gopls/doc/settings.md#experimentaldiagnosticsdelay-timeduration. Basically it's debouncing for the full workspace diagnostics--we compute the diagnostics for the changed files right away, and then wait this duration to compute diagnostics for the full workspace (reverse dependencies).

**Comment by myitcv** [comment]
Thank you very much  - for some reason I didn't even think to search the option documentation (which in hindsight was silly of me).

**Comment by stamblerre** [comment]
Historically, we haven't kept the docs very up-to-date, so no worries 😄
