### ISSUE TITLE
go/types: failure to report errors on test/fixedbugs/issue20232.go

### ISSUE THREAD

**Issue by mdempsky** [golang/go#42695]
While integrating go/constant into cmd/compile, I discovered that go/types isn't actually handling the test case from #20232 correctly. In particular, this variation on the test case demonstrates two latent issues:

```
package p

const _ uint8 = 6e5518446744
const _ = 0 * 1e+1000000000
```

1. go/types fails to report any error about 6e5518446744; it should report that it's too large of a constant, or that it overflows uint8.
2. go/types crashes on the second case, due to multiplying 0 by infinity; again, it should instead gracefully report a constant-too-large error instead.

/cc @griesemer

**Comment by griesemer** [comment]
There's at the very least a missing test in operand.setConst:
```Go
if x.val.Kind() == constant.Unknown {
        x.mode = invalid
}
```

**Comment by griesemer** [comment]
The 2nd example is already reported as #20583.
