### ISSUE TITLE
x/pkgsite: use squirrel where appropriate

### ISSUE THREAD

**Issue by jba** [golang/go#42708]
[Squirrel](https://pkg.go.dev/github.com/Masterminds/squirrel) may help with some of our dynamically constructed queries. Try it out.

**Comment by julieqiu** [comment]
Thanks @johanbrandhorst for the suggestion! We got this idea from your GopherCon talk: https://www.gophercon.com/agenda/session/227419.

**Comment by julieqiu** [comment]
It might make sense to check out https://github.com/kyleconroy/sqlc instead.

**Comment by julieqiu** [comment]
Closing this issue since we are now using squirrel in several places in the codebase.
