### ISSUE TITLE
x/pkgsite: search shortcut key doesn't work consistently across site

### ISSUE THREAD

**Issue by fflewddur** [golang/go#42704]
Using the '/' shortcut for search works on package/module pages (e.g., https://pkg.go.dev/flag), but doesn't work on the home page or search results pages (e.g., https://pkg.go.dev/search?q=command). I expected the shortcut keys to behave consistently across the site.

### What is the URL of the page with the issue?
 
https://pkg.go.dev/search?q=command
https://pkg.go.dev/
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 
 
### What did you do?
 
Pressed the '/' search shortcut key.
 
### What did you expect to see?
 
I expected focus to move to the search box, as it does on package/module pages.
 
### What did you see instead?

Nothing happened :(

**Comment by julieqiu** [comment]
The search keyboard shortcut should also work consistently across *go.dev. See https://github.com/golang/go/issues/45268.

**Comment by jamalc** [comment]
Done.

**Comment by julieqiu** [comment]
Reopened because of #42704.
