### ISSUE TITLE
Estimating blockers for supporting gollvm on RISC-V (qemu). Fedora 33

### ISSUE THREAD

**Issue by advancedwebdeveloper** [golang/go#42702]
It is just a brief survey - but I am currently dealing with a messy setup, for qemu.

I have upgraded, after bootstrapping( [the manual](https://fedoraproject.org/wiki/Architectures/RISC-V/Installing) ) and I am able to boot 

> Fedora (5.8.0-1.0.riscv64.fc33.riscv64) 33 (Rawhide)

kernel, under qemu.

I see a very abstract 

> $ cat /proc/cpuinfo
> processor	: 0
> hart		: 0
> isa		: rv64imafdcsu
> mmu		: sv48
. Doesn't really help.
I will suggest trying other emulators - but would have to compile those myself.

I have some concerns about gmp, mpfr and mpc (since RISC-V assumes some extensions, to cover such demands) - I feel that it might have more sense to get rid of overlaying, for the end-user use cases (which gollvm project itself achieves).
Will share that via https://groups.google.com/g/golang-nuts , later (with cross-referencing, of course).

CC @tekkamanninja @carlosedp

**Comment by thanm** [comment]
This does not seem to be describing a Go bug -- if you have a question, probably best to ask in a forum, as you mention.
