### ISSUE TITLE
x/pkgsite: content overflows horizontally on startpage using safari

### ISSUE THREAD

**Issue by emmanuelay** [golang/go#42718]
### What is the URL of the page with the issue?
https://pkg.go.dev
 
 
### What is your user agent?
 
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15
```
  
### Screenshot
 
<img width="263" alt="Skärmavbild 2020-11-19 kl  08 44 31" src="https://user-images.githubusercontent.com/624838/99636610-ee0df680-2a43-11eb-8880-f5ed7526477e.png">

### What did you do?

Resize the window once.  
 
### What did you expect to see?

I expected a normal responsive behavior.
 
### What did you see instead?

Scrollbars indicating there is a horizontal overflow.
After looking through the elements of the startpage I found the culprit is in the class  **.Questions**, more specific this style:
```
width: 100vw;
``` 
..when disabled, the overflow stops appearing.

**Comment by Omkar76** [comment]
Seeing same issue on firefox and chrome

**Comment by Omkar76** [comment]
The problem was caused by oversized `.Questions` div (faq). Removing `width:100vw` solved the problem. I have made a PR for the same https://github.com/golang/pkgsite/pull/18
