### ISSUE TITLE
x/tools/gopls: const tokenized as a string

### ISSUE THREAD

**Issue by stamblerre** [golang/go#42715]
<img width="619" alt="Screen Shot 2020-11-19 at 12 55 41 AM" src="https://user-images.githubusercontent.com/5856771/99627312-0c530280-2a02-11eb-99b3-7ad2b38f0ed1.png">

In the above screenshot, the `mod` const is tokenized as a string, leading it to appear the same as a string in the given function.

To repro, add the following to any file in `golang.org/x/tools/gopls/internal/regtest`:

```go
func TestUseOfInvalidMetadata(t *testing.T) {
	const mod = `
-- go.mod --
module mod.com

go 1.12
-- main.go --
package main

import "mod.com/a"

func _() {
	a.Hello()
}
-- a/a.go --
package a

func Hello() {}
`
	run(t, mod, func(t *testing.T, env *Env) {

	})
}
```

/cc @pjweinb

**Comment by pjweinb** [comment]
And also the assignment of tokens to predeclared identifiers is inconsistent. (true, false, nil, iota)
