### ISSUE TITLE
cmd/compile: ICE: 'NameCon': Unexpected Load as selector, leaf=v549 = IData <*uint8> v502, selector=v502 = Load <EdgeType> v289 v136

### ISSUE THREAD

**Issue by dmgk** [golang/go#42727]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +5ba1c3f290 Thu Nov 19 04:02:59 2020 +0000 freebsd/amd64
</pre>

### Does this issue reproduce with the latest release?

No, tip only

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dmgk/.cache/go-build"
GOENV="/home/dmgk/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOINSECURE=""
GOMODCACHE="/home/dmgk/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="freebsd"
GOPATH="/home/dmgk/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/dmgk/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/dmgk/opt/go/pkg/tool/freebsd_amd64"
GOVCS=""
GOVERSION="devel +5ba1c3f290 Thu Nov 19 04:02:59 2020 +0000"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build207921525=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version devel +5ba1c3f290 Thu Nov 19 04:02:59 2020 +0000 freebsd/amd64
GOROOT/bin/go tool compile -V: compile version devel +5ba1c3f290 Thu Nov 19 04:02:59 2020 +0000
uname -v: FreeBSD 12.2-STABLE r367758 XOMBO
lldb --version: lldb version 10.0.1 (git@github.com:llvm/llvm-project.git revision llvmorg-10.0.1-0-gef32c611aa2)
  clang revision llvmorg-10.0.1-0-gef32c611aa2
  llvm revision llvmorg-10.0.1-0-gef32c611aa2
gdb --version: GNU gdb (GDB) 9.2 [GDB v9.2 for FreeBSD]
</pre></details>

### What did you do?

```
go get github.com/MichaelMure/git-bug@0.7.1
```

### What did you expect to see?

`go get` completing without errors.

### What did you see instead?

```
$ go get github.com/MichaelMure/git-bug@0.7.1
# github.com/MichaelMure/git-bug/graphql/connections
../go/pkg/mod/github.com/!michael!mure/git-bug@v0.0.0-20200404104824-2d64b85db71a/graphql/connections/connection_template.go:46:10: internal compiler error: 'NameCon': Unexpected Load as selector, leaf=v549 = IData <*uint8> v502, selector=v502 = Load <EdgeType> v289 v136


goroutine 7 [running]:
runtime/debug.Stack(0xdb6fc0, 0xc0000c0008, 0x0)
        /home/dmgk/opt/go/src/runtime/debug/stack.go:24 +0x9f
cmd/compile/internal/gc.Fatalf(0xc00044bac0, 0x38, 0xc0006a6f30, 0x3, 0x3)
        /home/dmgk/opt/go/src/cmd/compile/internal/gc/subr.go:199 +0x1b0
cmd/compile/internal/gc.(*ssafn).Fatalf(0xc00045f320, 0x2e0a000000002, 0xcb858c, 0x32, 0xc00007b8c0, 0x2, 0x2)
        /home/dmgk/opt/go/src/cmd/compile/internal/gc/ssa.go:7105 +0x1a5
cmd/compile/internal/ssa.(*Func).Fatalf(...)
        /home/dmgk/opt/go/src/cmd/compile/internal/ssa/func.go:652
cmd/compile/internal/ssa.expandCalls.func6(0xc000838040, 0xc000836bb0, 0x8, 0xc93d09, 0x5, 0x8)
        /home/dmgk/opt/go/src/cmd/compile/internal/ssa/expand_calls.go:251 +0xf26
cmd/compile/internal/ssa.expandCalls.func6(0xc000838040, 0xc000838040, 0x0, 0x11da020, 0x0, 0x1)
        /home/dmgk/opt/go/src/cmd/compile/internal/ssa/expand_calls.go:350 +0x20f2
cmd/compile/internal/ssa.expandCalls(0xc000490840)
        /home/dmgk/opt/go/src/cmd/compile/internal/ssa/expand_calls.go:922 +0x233d
cmd/compile/internal/ssa.Compile(0xc000490840)
        /home/dmgk/opt/go/src/cmd/compile/internal/ssa/compile.go:96 +0x98d
cmd/compile/internal/gc.buildssa(0xc0004902c0, 0x2, 0x0)
        /home/dmgk/opt/go/src/cmd/compile/internal/gc/ssa.go:469 +0x11ba
cmd/compile/internal/gc.compileSSA(0xc0004902c0, 0x2)
        /home/dmgk/opt/go/src/cmd/compile/internal/gc/pgen.go:319 +0x5d
cmd/compile/internal/gc.compileFunctions.func2(0xc0003b2a80, 0xc0000b6790, 0x2)
        /home/dmgk/opt/go/src/cmd/compile/internal/gc/pgen.go:384 +0x4d
created by cmd/compile/internal/gc.compileFunctions
        /home/dmgk/opt/go/src/cmd/compile/internal/gc/pgen.go:382 +0x129
```

**Comment by cherrymui** [comment]
cc @dr2chase
