### ISSUE TITLE
go/cmd: concurrent commands like 'go get'

### ISSUE THREAD

**Issue by maomaoguo2017** [golang/go#42722]
hi.
just a simple question.

https://github.com/golang/go/blob/5ba1c3f290ef8f3c373c560d3608325b07f44f7a/src/cmd/go/internal/modload/init.go#L952
is this meaning i can't to run concurrent commands which need change the go.mod or go.sum ?
like:
```
go get <mod1 URL> &
go get <mod2 URL> &
go get -u <mod3 URL> &
```

**Comment by bcmills** [comment]
That's correct. The expectation is that you set up the dependencies you need in a sequence of zero or more sequential `go get` commands, and then you can concurrently invoke `go build`, `go test`, and so on as much as you like.

There isn't a good way for commands like `go get` to incorporate concurrent changes without starting over completely, and we don't want to keep the files locked for an arbitrarily long time while `go get` is working — that would just result in the same kind of sequential operation that you can already do by leaving off the `&`.
