### ISSUE TITLE
net, internal/poll: kernelVersion helper miscalculates minor version component

### ISSUE THREAD

**Issue by dmitshur** [golang/go#42733]
In `kernelVersion`, after reaching the end of the major version component, the accumulated `value` is used. But it isn't reset to zero after, so the minor version component computation is polluted.

This can be reproduced on the playground, see https://play.golang.org/p/U8-OWl-gzR4.

The fix is to add one line:

```Go
value = 0
```

Both copies of `kernelVersion` helper were introduced recently and can be fixed in time for Go 1.16.

CC @cuonglm, @ianlancetaylor.

**Comment by ianlancetaylor** [comment]
Thanks for noticing.
