### ISSUE TITLE
encoding/json: omitempty does not work with time.Time values

### ISSUE THREAD

**Issue by zosmac** [golang/go#42735]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
```
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/keefe/Library/Caches/go-build"
GOENV="/Users/keefe/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/keefe/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/keefe/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5g/n63n_wf97rx7td0yzcj3k5sc0000gn/T/go-build072440525=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
</pre></details>

### What did you do?

Added `json:",omitempty"` tag to a time.Time field of a structure. Was hoping to omit the value from JSON when the time value is uninitialized. Got this instead:
```
"Timestamp": "0001-01-01T00:00:00Z",
```

```
package main

import "fmt"
import "time"
import "encoding/json"

type data struct {
	Timestamp time.Time
}
func main() {
	d := data{}
	buf, _ := json.Marshal(d)
	fmt.Printf("%s\n", buf)
}
```

### What did you expect to see?

{}

### What did you see instead?

{"Timestamp":"0001-01-01T00:00:00Z"}

**Comment by zosmac** [comment]
I see an old issue from 2014: #5902, that appeared to touch on this but little discussion.

**Comment by davecheney** [comment]
Thank you for raising this issue. I would argue that the code above is not correct as it is ignoring the error value. The general approach to error handling in the majority of Go code is, if there is an error, the state of any other return values is undefined, and shouldn’t be consulted if err != nil

**Comment by zosmac** [comment]
The following updated example code clarifies the intent of using the json omitempty tag and verifies that a Zero time value is encoded without error:

```
package main

import (
	"fmt"
	"time"
	"encoding/json"
)

type data struct {
	Timestamp time.Time `json:",omitempty"`
}
func main() {
	d := data{}
	buf, err := json.Marshal(d)
	fmt.Printf("%s %v\n", buf, err)
}
```
Returns:

```
{"Timestamp":"0001-01-01T00:00:00Z"} <nil>
```

**Comment by zosmac** [comment]
Dave,
Thank you for your prompt reply.

When I run an updated version of the sample code, with the error return value captured, it shows that the time Zero value is Marshaled without error. I have added this updated sample to the issue.

Have a nice evening.
Keefe


package main

import "fmt"
import "time"
import "encoding/json"

type data struct {
	Timestamp time.Time `json:",omitempty"`
}
func main() {
	d := data{}
	buf, err := json.Marshal(d)
	fmt.Printf("%s %v\n", buf, err)
}

Returns:

{"Timestamp":"0001-01-01T00:00:00Z"} <nil>



On Nov 19, 2020, at 9:11 PM, Dave Cheney <notifications@github.com> wrote:


Thank you for raising this issue. I would argue that the code above is not correct as it is ignoring the error value. The general approach to error handling in the majority of Go code is, if there is an error, the state of any other return values is undefined, and shouldn’t be consulted if err != nil

**Comment by davecheney** [comment]
Thank you for clarifying. Would you consider renaming your issue to something like “encoding/json: omitempty does not work with time.Time” values?

**Comment by davecheney** [comment]
Although it is closed, https://github.com/golang/go/issues/4357#issuecomment-218683975, seems to capture your issue.

**Comment by zosmac** [comment]
Thank you for this link. It references another couple of issues, including this lengthy one #11939 which will take me a bit to digest. A lot of good discussion there.

On Nov 19, 2020, at 9:33 PM, Dave Cheney <notifications@github.com> wrote:


Although it is closed, #4357 (comment) <https://github.com/golang/go/issues/4357#issuecomment-218683975>, seems to capture your issue.

**Comment by zosmac** [comment]
This phrasing is much clearer. Thank you for the excellent suggestion.

On Nov 19, 2020, at 9:31 PM, Dave Cheney <notifications@github.com> wrote:

encoding/json: omitempty does not work with time.Time” values

**Comment by mvdan** [comment]
Closing as a dup of #11939.

**Comment by zosmac** [comment]
Daniel, Dave,
Thank you for your guidance here, I appreciate your input. 
I will plug into #11939 to lend my support to the discussion. 
Take care and stay safe.

Sent from Keefe’s iPad

On Nov 20, 2020, at 5:26 AM, Daniel Martí <notifications@github.com> wrote:

﻿
Closing as a dup of #11939.
