### ISSUE TITLE
cmd/compile: constant expression overflow doesn't report an error

### ISSUE THREAD

**Issue by griesemer** [golang/go#42732]
https://play.golang.org/p/Ro-SJWdCh35

The compiler reports an error if a constant literal is too large to represent, but it doesn't if we exceed that value in constant arithmetic.

**Comment by mdempsky** [comment]
It looks like we incorrectly allow infinity as a constant, but we correctly error about any attempts to turn it into a typed value.

I think my CLs to switch cmd/compile to use go/constant should fix this.

**Comment by mdempsky** [comment]
At tip we now ICE instead, because of the failure to report an error message.

Relatedly, I realized I missed that XOR can also cause overflow, so this currently ICEs as well while trying to report the overflow error:

```
const MaxInt512 = (1 << 256 - 1) * (1 << 256 + 1)
const _ = ^MaxInt512 // computes -1 << 512
```
