### ISSUE TITLE
x/tools/gopls: import autocomplete appends suggestion instead of replacing

### ISSUE THREAD

**Issue by RomanKornev** [golang/go#42748]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.15.2 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- Version: 1.51.1
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.18.1
- Run `go env` to get the go development environment details
	- GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/df/Library/Caches/go-build"
GOENV="/Users/df/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/df/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/df/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gd/ck6ncspn19115_7mxytyzw840000gp/T/go-build892077481=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Share the Go related settings you have added/edited

`"go.useLanguageServer": true,`

### Describe the bug
Autocompleting `import mat` produces `import mat"math/"`

### Steps to reproduce the behavior:
1. Type `import mat`
2. Enter or Tab
3. See `import mat"math/"` instead of `import "math"`

### Screenshots or recordings
<img width="151" alt="image" src="https://user-images.githubusercontent.com/5807561/99777984-2127b700-2b24-11eb-95ee-e27767fbee51.png">

**Comment by muirdm** [comment]
@stamblerre do you want to suppress completions in this case or fix the insertion? Without quotes they could be typing the optional name of the import, so popping up the completions wouldn't make sense.

**Comment by stamblerre** [comment]
Suppressing completions sounds like it might be easiest, but it would be helpful to add the quotes for people who are new to Go. I think people who are typing a named import would know to ignore the completion results, so I think adding the quotes should be fine. What do you think?

**Comment by muirdm** [comment]
I would vote for suppression. It's a fluke completions show up at all, and it would require some finagling to fix the insertion. It's a good point about new Gophers, but as long as a squiggly shows up with a useful message I think they will be okay.

**Comment by stamblerre** [comment]
Sounds good--suppression sounds like a better path forward.
