### ISSUE TITLE
internal/poll: Splice() creates and destroys pipes in high frequency, wasting system resources

### ISSUE THREAD

**Issue by panjf2000** [golang/go#42740]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/root/dev/go/bin"
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/dev/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/dev/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/data/dev/golang/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build736136467=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
We were transmitting large amounts of data over the network, based on a mass of TCP sockets among goroutines.
The data transmission between TCP sockets in Go is optimized by the underlying splice() call on Linux which creates and destroys a new pipe every time at present, costing a mass of system resources and may slow down the performance.

For instance, if we started 50,000 concurrent socket goroutines to transfer data over the network, resulting in `64KB(pipe buffer on Linux) * 50,000 ≈ 3GB`, it cost too many system resources and it may have the Processes OOM in extreme circumstances.

### What did you expect to see?

Reusing the pipe buffers when calling splice(), save system resources, and improve performance.

### What did you see instead?

High system resource consumption and inefficient processes.

**Comment by ianlancetaylor** [comment]
Reusing pipe descriptors makes sense to me, but I don't understand your example.  Currently the pipes, and their buffers, only exist as long as they are being used.  Even with a pipe pool, if you have 50,000 concurrent routines using splice, you are going to be using all that memory and will face the risk of an OOM.  Having a pool doesn't reduce the resources required by concurrent use.

**Comment by panjf2000** [comment]
My initial thought was to create a pipe pool that limits the total number of pipes and blocks or fails if it runs out of the capacity of the pool, like HAProxy: https://github.com/haproxy/haproxy/blob/v2.4-dev0/src/pipe.c#L66-L67, but after a second thought, I reckon that is not a rational choice for Go (as a programming language), so I think it would be a better idea for a pipe pool to just cache rather than limit pipes.

**Comment by networkimprov** [comment]
This should be reopened?

**Comment by panjf2000** [comment]
We're now trying to fix it rather than just revert it, thanks for asking, and stay tuned if you'd like.
@networkimprov

**Comment by networkimprov** [comment]
Right, and the issue should be re-opened, so that gopherbot can close it when the correct fix is merged.
