### ISSUE TITLE
crypto/rsa: pss may have wrong salt length

### ISSUE THREAD

**Issue by zhangzhanli** [golang/go#42741]
crypto/rsa/pss.go : 272 in latest version of go

When  PSSOptions's saltLength is PSSSaltLengthAuto, we just try to maximize the length of salt. But there are some problems with it where the bit length of N of private key is congruent to 1 module 8.  (i.e.  bitlen(N) == 8k + 1) .  Under these situations, when checking emLen in crypto/rsa/pss.go : 50 which is equal to hLen+sLen+1, we will alway get an error "key size too small for PSS signature". And I didn't see there are such problems with openssl. So, maybe we need a change?

**Comment by martisch** [comment]
Cc @FiloSottile

**Comment by FiloSottile** [comment]
Yep, this is broken and has been broken at least since Go 1.13, so not a Go 1.16 fix. Scheduling for 1.17, thank you!

https://play.golang.org/p/hgTw2zJW2OI

**Comment by odeke-em** [comment]
@zhangzhanli thank you for the catching this, and thanks @martisch and @FiloSottile for the triaging and responses.

@zhangzhanli, the Go1.17 tree is now open, and if you are interested in becoming a Go contributor, please go ahead and send a CL or PR, as you please— it would be awesome to have you as a contributor to the Go project!
