### ISSUE TITLE
x/website: Version page does not return the latest stable version

### ISSUE THREAD

**Issue by tbaud0n** [golang/go#42744]
When I visit https://golang.org/VERSION (or the text version https://golang.org/VERSION?m=text) it indicates that the latest version is 1.15.4 but the download page indicates that the stable version is 1.15.5.

I expect that the versions match between the version page and the download page

**Comment by AlexRouSg** [comment]
`https://golang.org/VERSION` is the version that the site is running.
For latest released version use `https://golang.org/dl/?mode=json`

**Comment by ALTree** [comment]
Yes as AlexRouSg said that VERSION endpoint is just serving the VERSION file of the Go version the is being served at the moment by the website. Use https://golang.org/dl/?mode=json for a stable endpoint that list releases. Closing here.
