### ISSUE TITLE
cmd/go: do not update go.mod and go.sum with imports found in .gitignore

### ISSUE THREAD

**Issue by mkungla** [golang/go#42763]
`go.mod` and `go.sum` should not be updated from paths found in `.gitignore` which may contain resources or experimental code.

**Comment by ianlancetaylor** [comment]
I don't think the go tool should be aware of the Git specific .gitignore file.

See also #30058.

**Comment by ianlancetaylor** [comment]
CC @bcmills @jayconrod

**Comment by mkungla** [comment]
@seankhliao Can you elaborate your reaction?

**Comment by seankhliao** [comment]
Same as above, the go tool should not be aware of git ignore things and the dependencies for your experiments still need to be tracked somewhere

**Comment by mkungla** [comment]
Well, this behavior can now be achieved by placing an empty `go.mod` file in that directory.

**Comment by bcmills** [comment]
I agree with @ianlancetaylor and @seankhliao: the `go` command should not try to interpret vcs-specific files. Plus, we already have at least two mechanisms to ignore files: `// +build ignore` to ignore files, and dropping in a `go.mod` file to ignore directory subtrees.I don't see a pressing need for yet another.
