### ISSUE TITLE
os/exec: windows: support simple way of launching process with username/password

### ISSUE THREAD

**Issue by rgl** [golang/go#42773]
Currently os.exec allow us to use a Token to create a process under a different user, but its not clear how to do that; so please provide an proper example :-)

Please note that https://github.com/golang/go/issues/35653 or https://github.com/golang/go/issues/21105 are somewhat related to this, but they were closed by using the more complex CreateProcessWithLogon function and didn't provide an example of starting a process under a different user.

Also, I think it would also be useful to add support for setting the user domain/username/password in [syscall.SysProcAttr](https://github.com/golang/go/blob/go1.15.5/src/syscall/exec_windows.go#L221) and internally use [CreateProcessWithLogonW/CreateProcessWithLogon function](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createprocesswithlogonw) instead of [CreateProcessAsUserW/CreateProcessAsUser](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessasuserw) ([as done in Go](https://github.com/golang/go/blob/1e3b535b6eb7f13eb6d903f7998c384a36e9bba8/src/syscall/exec_windows.go#L345)).

If that makes sense, I can try to create a PR that adds the following properties to syscall.SysProcAttr:

- Domain
- Username
- Password

And use CreateProcessWithLogonW to launch the process when Username is set.

BTW, [dotnet also uses the CreateProcessWithLogon function](https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs#L563-L567).

What do you think?

**Comment by ianlancetaylor** [comment]
CC @alexbrainman @mattn @zx2c4 

Can you suggest exactly what fields would be added to `syscall.SysProcAttr`, and how they would be documented?  Thanks.

**Comment by zx2c4** [comment]
I'm pretty familiar with these APIs and can probably do that but... what are you actually trying to accomplish? Most folks should probably not be passing password strings and such around. Do you have a use case in mind?

**Comment by rgl** [comment]
I'm playing with the idea of improving the [nomad raw_exec driver](https://github.com/hashicorp/nomad/issues/9210#issuecomment-731820942) to somehow use non-administrator/system accounts. One of that ways is to use CreateProcessWithLogon; others are to somehow use Group Managed Service Accounts and/or Local Service Accounts (these do not have a user managed password, as such, are more convenient to use; but these seem to require the application to run (or be wrapped) as a Windows service).

**Comment by zx2c4** [comment]
I don't know too much about that, so I might be guessing incorrectly at some of the details. It sounds like you have a system service running highly privileged, and you'd like it to create processes running as less privileged users, as specified through a configuration file? And this should be done non-interactively?

**Comment by rgl** [comment]
Its exactly that :-)

Nomad is running as a windows service (under the SYSTEM account) and acting as a init/service manager (akin to systemd) for the processes its starts as child processes; that is, it launches the process as a child process, captures their output as logs, re-launches then when they die, etc.

**Comment by zx2c4** [comment]
Gotcha, okay. So in that case, if you're already running as Local System, you don't want to use these APIs that require a password. Rather, mint a token using something like `NtCreateToken`, and then pass that to the `Token` field:

```go
attrs := &os.ProcAttr{
                Sys: &syscall.SysProcAttr{
                        Token: syscall.Token(theTokenThatYouJustMade),
                },
}
```

And then `attrs` is passed to `os.StartProcess` like usual.

**Comment by rgl** [comment]
Interesting! So we can mint any user token, load its profile, and start the process?

If so, I think that the only thing missing is an example of this in the documentation 🙂

**Comment by zx2c4** [comment]
> If so, I think that the only thing missing is an example of this in the documentation

I don't think it's the job of Go's documentation to provide walkthroughs of how to use rarely used NT APIs, especially ones involving manual token creation.

**Comment by rgl** [comment]
Thank you! I will try to get it working.

**Comment by qmuntal** [comment]
Nothing to do here (based on previous comments), closing.
