### ISSUE TITLE
interface{} & unsafe.Pointer: the value of original variable changed after assigning to interface{}.data

### ISSUE THREAD

**Issue by MMMMMMoSky** [golang/go#42776]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, the output of the codes below on my machine is the same as [golang playground](https://play.golang.org/) (1.15.5)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOOS="darwin"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lp/dkglnlh92pn1x64wv1mr06_40000gp/T/go-build123819166=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

First I had `var i int`, and assigned it to an empty interface `var e interface{} = i`.

Then I tried to modify the value which `e.data` point to. Unexpectedly, `i` was changed too. `i` is a variable, but not pointer, **so I think it's value should NOT be changed.**

Just run the code below, see the output.

```go
package main

import (
	"fmt"
	"unsafe"
)

func main() {
	issue(101, 233) // both < 256
	issue(253, 886) // oldVal < 256
	issue(987, 254) // newVal < 256
	issue(998, 258) // both >= 256

	// Try this four calls, the output will be more strange.
	// issue(100, 255) // both < 256
	// issue(255, 999) // oldVal < 256
	// issue(999, 255) // newVal < 256
	// issue(999, 256) // both >= 256
}

// type eface struct {
// 	  _type *_type
// 	  data  unsafe.Pointer
// }
// data is *int (unsafe.Pointer(&i))
func issue(oldVal, newVal int) {
	fmt.Printf("\n==== running issue(%d, %d) ====\n", oldVal, newVal)

	var (
		i             = oldVal // int
		e interface{} = i
	)
	pdata := unsafe.Pointer(uintptr(unsafe.Pointer(&e)) + unsafe.Sizeof(&i))
	data := unsafe.Pointer(*(**int)(pdata))

	fmt.Printf("      i,   &i = %d, %p\n", i, &i)
	fmt.Printf("  *data, data = %d, %p\n", *((*int)(data)), data)

	// when 0 <= oldVal < 256, i will be changed, WHY???
	*((*int)(data)) = newVal
	fmt.Printf("\n  exec *((*int)(data)) = %d\n\n", newVal)

	fmt.Printf("      i,   &i = %d, %p\n", i, &i)
	fmt.Printf("  *data, data = %d, %p\n", *((*int)(data)), data)
}
```

Maybe it's a feature/bug about small integer cache...?

**Comment by randall77** [comment]
You are not allowed to write to the location pointed to by the data field of an interface. Interfaces are assumed to be immutable.
(Just like you can't write to the backing store of a string, or the type pointer of an interface, or lots of other things.)

**Comment by MMMMMMoSky** [comment]
**Interfaces are assumed to be immutable.**
Got it, thanks~

**Comment by ShiinaOrez** [comment]
> You are not allowed to write to the location pointed to by the data field of an interface. Interfaces are assumed to be immutable.
> (Just like you can't write to the backing store of a string, or the type pointer of an interface, or lots of other things.)

Here is the reason of WHY NUMBER LESS THAN 256 CAUSE CHANGE? https://golang.org/doc/go1.15#runtime

**Comment by MMMMMMoSky** [comment]
Then I studied the source code about interface, seen `staticuint64s`.

I know I actually changed the value in `staticuint64s`.

Maybe `fmt.Printf` used it and so print another value, but not `i`.

**Comment by MMMMMMoSky** [comment]
**So it's all my mistake.** sorry 😅

Be ⚠️CAREFUL⚠️ playing with `unsafe`, stop C behavior.
