### ISSUE TITLE
cmd/compile: ICE: 'NameCon': not lowered: v502, Load INTER PTR SSA

### ISSUE THREAD

**Issue by dmgk** [golang/go#42784]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +d902791b50 Mon Nov 23 05:57:35 2020 +0000 freebsd/amd64
</pre>

### Does this issue reproduce with the latest release?

No, tip only.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dmgk/.cache/go-build"
GOENV="/home/dmgk/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOINSECURE=""
GOMODCACHE="/home/dmgk/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="freebsd"
GOPATH="/home/dmgk/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/dmgk/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/dmgk/opt/go/pkg/tool/freebsd_amd64"
GOVCS=""
GOVERSION="devel +d902791b50 Mon Nov 23 05:57:35 2020 +0000"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build206452789=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version devel +d902791b50 Mon Nov 23 05:57:35 2020 +0000 freebsd/amd64
GOROOT/bin/go tool compile -V: compile version devel +d902791b50 Mon Nov 23 05:57:35 2020 +0000
uname -v: FreeBSD 12.2-STABLE r367758 XOMBO
lldb --version: lldb version 10.0.1 (git@github.com:llvm/llvm-project.git revision llvmorg-10.0.1-0-gef32c611aa2)
  clang revision llvmorg-10.0.1-0-gef32c611aa2
  llvm revision llvmorg-10.0.1-0-gef32c611aa2
gdb --version: GNU gdb (GDB) 9.2 [GDB v9.2 for FreeBSD]
</pre></details>

### What did you do?

`go get github.com/MichaelMure/git-bug@0.7.1`

### What did you expect to see?

`go get` completing without errors.

### What did you see instead?

```
$ go get github.com/MichaelMure/git-bug@0.7.1
# github.com/MichaelMure/git-bug/graphql/connections
go/pkg/mod/github.com/!michael!mure/git-bug@v0.0.0-20200404104824-2d64b85db71a/graphql/connections/connection_template.go:46:10: internal compiler error: 'NameCon': not lowered: v502, Load INTER PTR SSA

goroutine 29 [running]:
runtime/debug.Stack(0xdb70e0, 0xc0000c0008, 0x0)
        /home/dmgk/opt/go/src/runtime/debug/stack.go:24 +0x9f
cmd/compile/internal/gc.Fatalf(0xc000a25e30, 0x8, 0xc0004a7060, 0x2, 0x2)
        /home/dmgk/opt/go/src/cmd/compile/internal/gc/subr.go:199 +0x1b0
cmd/compile/internal/gc.(*ssafn).Fatalf(0xc0005145a0, 0x2e0a000000002, 0xc924a3, 0x2, 0xc000b6fcd0, 0x1, 0x1)
        /home/dmgk/opt/go/src/cmd/compile/internal/gc/ssa.go:7105 +0x1a5
cmd/compile/internal/ssa.(*Func).Fatalf(...)
        /home/dmgk/opt/go/src/cmd/compile/internal/ssa/func.go:652
cmd/compile/internal/ssa.checkLower(0xc0004ed080)
        /home/dmgk/opt/go/src/cmd/compile/internal/ssa/lower.go:36 +0x41a
cmd/compile/internal/ssa.Compile(0xc0004ed080)
        /home/dmgk/opt/go/src/cmd/compile/internal/ssa/compile.go:96 +0x98d
cmd/compile/internal/gc.buildssa(0xc000490420, 0x1, 0x0)
        /home/dmgk/opt/go/src/cmd/compile/internal/gc/ssa.go:469 +0x11ba
cmd/compile/internal/gc.compileSSA(0xc000490420, 0x1)
        /home/dmgk/opt/go/src/cmd/compile/internal/gc/pgen.go:319 +0x5d
cmd/compile/internal/gc.compileFunctions.func2(0xc00006a4e0, 0xc00052e1a0, 0x1)
        /home/dmgk/opt/go/src/cmd/compile/internal/gc/pgen.go:384 +0x4d
created by cmd/compile/internal/gc.compileFunctions
        /home/dmgk/opt/go/src/cmd/compile/internal/gc/pgen.go:382 +0x129
```

See also https://github.com/golang/go/issues/42727

**Comment by randall77** [comment]
@dr2chase

**Comment by cuonglm** [comment]
Small reproducer:

```
package p

type iface interface {
	m()
}

type it interface{}

type makeIface func() iface

func f() {
	var im makeIface
	e := im().(it)
	g(e)
}

//go:noinline
func g(i it) {}
```

`expand_calls` phase somehow generates:

```
v10 (?) = Addr <*uint8> {type."".it} v3
v16 (13) = SP <uintptr>
v14 (?) = OffPtr <*uintptr> [0] v16
v9 (?) = OffPtr <**uint8> [8] v16
v24 (?) = OffPtr <**uint8> [0] v16
v29 (?) = OffPtr <**uint8> [16] v16
v31 (?) = OffPtr <*it> [8] v16
v32 (13) = Load <it> v31 v6
v11 (13) = Load <*uint8> v24 v6
```
