### ISSUE TITLE
go/types: bad constant integer->string conversion for out-of-bounds integers

### ISSUE THREAD

**Issue by mdempsky** [golang/go#42790]
The package below statically converts the constant 1<<32 to a string (which should be "\uFFFD", because it's outside of the valid Unicode range). It then checks that the length matches the expected length (which is 3).

cmd/compile correctly accepts this package, but go/types and gccgo do not. go/types used to handle this correctly. I believe this is a regression introduced by CL 220844 (6052838bc325049505aba9c3b87256161f9e05e8).

```
package p
const _ = -uint(len(string(1<<32)) - len("\uFFFD"))
```

/cc @griesemer @ianlancetaylor

**Comment by griesemer** [comment]
The go/types conversion code now incorrectly uses `string(rune(codepoint))` where in the past it used the correct `string(codepoint)`.

We probably should revisit commit [`6052838`](https://github.com/golang/go/commit/6052838bc325049505aba9c3b87256161f9e05e8) to ensure we didn't introduce other bugs elsewhere.
