### ISSUE TITLE
Negative uint rewinds to max

### ISSUE THREAD

**Issue by ivanjaros** [golang/go#42806]
### What version of Go are you using (`go version`)?

<pre>go version go1.15 windows/amd64</pre>

When `uint` is decreased into negative value, it does not return `constant .... overflows int` error but instead it will return 18446744073709551615. So there is no overflow guard for unsigned integers.

This works as expected:
```
fmt.Println(1<<64)

returns error: constant 18446744073709551616 overflows int
```

this does not:
```
	var u uint
	fmt.Println(u)
	u--
	fmt.Println(u)

prints
0
18446744073709551615
```

**Comment by martisch** [comment]
Overflow at runtime is allowed https://golang.org/ref/spec#Integer_overflow.

**Comment by AlexRouSg** [comment]
Might want to see #19624 and #30209 for proposals to change this.
