### ISSUE TITLE
x/tools/gopls: handle go.sum file changes like go.mod changes after -mod=readonly

### ISSUE THREAD

**Issue by stamblerre** [golang/go#42815]
With `-mod=readonly` (https://golang.org/cl/268597), changes to `go.sum` files will affect the results of `packages.Load`. We should handle changes to `go.sum` files in `(*snapshot).clone` and invalidate metadata in the same way that we do for `go.mod` files.

/cc @heschik

**Comment by heschik** [comment]
I don't think the description is quite correct. Specifically, a change to `go.sum` can take a broken `packages.Load` and fix it; if the load succeeded, then `go.sum` changes cannot be relevant. (Technically, they could break it, but I don't think we care about that.) So it's less that we should invalidate, and more that we should try again to fix any invalid metadata.
