### ISSUE TITLE
x/pkgsite: "/" key should place the cursor on the search bar on the homepage and search page

### ISSUE THREAD

**Issue by jadekler** [golang/go#42819]
This is a feature request to add similar behavior as youtube, drive, etc.

**Comment by julieqiu** [comment]
This should have already been fixed in https://github.com/golang/go/issues/36805. @jadekler - could you confirm if that is the feature you are requesting?

**Comment by jadekler** [comment]
Yes, that is the feature. It appears to have regressed.

**Comment by julieqiu** [comment]
The feature works for me on Chrome 86 on macOS (Catalina). Which URL are you looking at and what browser are you using?

**Comment by jadekler** [comment]
Ah, it does indeed work on a specific package. Apologies.

However, it does not work on the homepage (pkg.go.dev). Not sure if this bug should be re-purposed to address that specific page?

**Comment by julieqiu** [comment]
>  Not sure if this bug should be re-purposed to address that specific page?

Yup! Updated the title.

**Comment by julieqiu** [comment]
There's actually already an issue filed for this. Closing as a duplicate of #42704.
