### ISSUE TITLE
encoding/json: Can json add newline between each elements in slice or map

### ISSUE THREAD

**Issue by caoruidong** [golang/go#42824]
How can I write a slice/map to file in json format with new line between elements? Or only third party libs support it?
### What did you expect to see?
a little compacter but still human readable
```
[
{"Name":"xx","Age":1},
{"Name":"test","Age":18}
]
```
or
```
[{"Name":"xx","Age":1},
{"Name":"test","Age":18}]
```

### What did you see instead?
Marshal: not so human readable
```[{"Name":"xx","Age":1},{"Name":"test","Age":18}]```
MarshalIntent: too many lines, mostly more than one screen, low information density
```
[
{
"Name": "xx",
"Age": 1
},
{
"Name": "test",
"Age": 18
}
]
```

**Comment by jimen0** [comment]
Hi @caoruidong,

You can do it by using [`json.MarshalIndent`](https://pkg.go.dev/encoding/json#MarshalIndent). Here's an example: https://play.golang.org/p/VBxgYEd4BK5

```go
package main

import (
	"encoding/json"
	"fmt"
	"log"
)

func main() {
	data := map[string]int{"a": 1, "b": 2}

	b, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("%s\n", b)
}
```

**Comment by martisch** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For asking questions, see: https://github.com/golang/go/wiki/Questions

**Comment by caoruidong** [comment]
Thanks @jimen0 , do you have any ideas about slice?
