### ISSUE TITLE
x/pkgsite: request for removal of cpmech/gosl packages

### ISSUE THREAD

**Issue by cpmech** [golang/go#42822]
Just want to remove my package gosl from your database (CGO is not supported by you). Thanks.

**Comment by jba** [comment]
We'd be happy to delete it, but honestly it looks fine:
![image](https://user-images.githubusercontent.com/18483045/100236705-04acc580-2efc-11eb-8b77-7dd26cc41d5b.png)

I clicked through to some package documentation and it also seems fine.

I'm not sure what you mean when you say we don't support cgo. We don't compile or run your code, so the fact that it uses cgo shouldn't matter.

**Comment by cpmech** [comment]
Hi, thanks for your time. If the new (current/master) version can be shown on your website, then perfect.
