### ISSUE TITLE
x/tools/gopls: could not import  xxxx (no package for import xxxx)

### ISSUE THREAD

**Issue by wu0407** [golang/go#42828]
### What version of Go are you using (`go version`)?

<pre>
$ go version
v1.15.5
gopls v0.5.3
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xiaoqing\AppData\Local\go-build
set GOENV=C:\Users\xiaoqing\AppData\Roaming\go\env  
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\git\kubernetes\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\xiaoqing\AppData\Local\Temp\go-build185837246=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

use vscode 1.51.1 to open kubernets project, gopls report 115k+ problems

### What did you expect to see?
no error

### What did you see instead?
gopls server log output
[gopls-server.txt](https://github.com/golang/go/files/5597238/gopls-server.txt)

**Comment by stamblerre** [comment]
Can you please share your `gopls` settings (you can find them by opening the Command Palette with Ctrl+Shift+P and selecting "Preferences: Open Settings (JSON))? Also, can you please share a more verbose `gopls` log by adding `-rpc.trace` to your `go.languageServerFlags` configuration? More details here: https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs.

**Comment by wu0407** [comment]
gpls settings:
```
{
    "files.eol": "\n",
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "editor.renderWhitespace": "all",
    "editor.renderControlCharacters": true,
    "files.autoSave": "afterDelay",
    "go.formatTool": "goimports",
    "workbench.activityBar.visible": true,
    "editor.minimap.enabled": false,
    "editor.wordWrap": "on",
    "go.toolsEnvVars": {
    //    "GOFLAGS": "-tags=linux"
    },
    "go.docsTool": "gogetdoc",
    "go.languageServerFlags": [


    
    ],
    "go.useLanguageServer": true,
    "go.languageServerExperimentalFeatures": {


        "diagnostics": true,
        "documentLink": true
    }
}
```

**Comment by wu0407** [comment]
pls server log with `-rpc.trace` option:
[gopls-server-202011261057.txt](https://github.com/golang/go/files/5600193/gopls-server-202011261057.txt)

**Comment by wu0407** [comment]
![the snapshot](https://user-images.githubusercontent.com/7602218/100532842-81131180-3238-11eb-9087-4b2bebcd0205.png)

**Comment by wu0407** [comment]
If disable the gopls server get the `cannot find package "." in:
	D:\git\kubernetes\vendor\k8s.io\apimachinery\pkg\types`
![20201129123123](https://user-images.githubusercontent.com/7602218/100533433-229d6180-323f-11eb-8560-f44f64b6524b.png)

**Comment by wu0407** [comment]
find some error that `couldn't run 'go': fork/exec C:\Program Files\Go\bin\go.exe: The filename or extension is too long.`  in the go.mod, and  find like issue https://github.com/therecipe/qt/issues/657 search by google .
so uninstall the tdm-gcc,  it work is ok

**Comment by wu0407** [comment]
gopls server log  after uninstall tdm-gcc

[gopls-server-uninstall-tdm-gcc.txt](https://github.com/golang/go/files/5612403/gopls-server-uninstall-tdm-gcc.txt)

**Comment by wu0407** [comment]
becuase go auto  use  vendor  directory if the "go" version in the main module's go.mod file is
1.14 or higher,  but vendor modules.txt not contain all dependence.  so set  to  mod model vscode, it is resolve the ploblem. 
```
   "go.toolsEnvVars": {
    "GOFLAGS": "-mod=mod"
    },
```

gopls-server log
```
[Error - Received] 16:00:21.289 PM #21 source error list:
	file:///D:/git/kubernetes/go.mod:11:1-11:70: err: exit status 1: stderr: go: inconsistent vendoring in D:\git\kubernetes:
	bitbucket.org/bertimus9/systemstat@v0.0.0-20180207000608-0eeff89b0690: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/Azure/azure-sdk-for-go@v43.0.0+incompatible: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/Azure/go-autorest/autorest@v0.9.6: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/Azure/go-autorest/autorest/adal@v0.8.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/Azure/go-autorest/autorest/to@v0.2.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/GoogleCloudPlatform/k8s-cloud-provider@v0.0.0-20200415212048-7901bc822317: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/JeffAshton/win_pdh@v0.0.0-20161109143554-76bb4ee9f0ab: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
```

**Comment by stamblerre** [comment]
I don't see the inconsistent vendoring error message in your previous log, but inconsistent vendoring will certainly cause problems. You should have seen a diagnostic message with a suggested fix to run `go mod vendor`, but in any case, I'm glad you were able to resolve the issue.

**Comment by wu0407** [comment]
yes,  i don't reproduce inconsistent vendoring error message
