### ISSUE TITLE
x/tools/gopls: incorrectly tokenized import statements

### ISSUE THREAD

**Issue by stamblerre** [golang/go#42831]
<img width="495" alt="Screen Shot 2020-11-25 at 11 50 37 AM" src="https://user-images.githubusercontent.com/5856771/100257965-827ccb00-2f14-11eb-80f0-7000e8016a04.png">

See the colors in this block:

```go
import (
    "fmt"
    "os"
)
```

The entirety of `"fmt"` and the closing quote of `"os"` are tokenized as strings, and `"os` is tokenized as a namespace. My guess is that there's something off about the positions.

/cc @pjweinb

**Comment by pjweinb** [comment]
quite right. It is off by 1. Thank you.

**Comment by pjweinb** [comment]
and embarrassing too. It's just like that in my golden test output, and I
never noticed.

**Comment by pjweinb** [comment]
My colors are different. How are you getting that?
package main

import (
"fmt"
"os"
)

func main() {
fmt.Println()
os.Exit(0)
}

**Comment by pjweinb** [comment]
hmm, lost the colors. But in your block, I don't think semantic tokens is on. With semantic tokens, fmt and Println would have different types and different colors. (As would os and Exit)
<img width="175" alt="Screen Shot 2020-11-26 at 07 58 18" src="https://user-images.githubusercontent.com/5406755/100353972-5ff2bc80-2fbd-11eb-881b-ac68efa5ea25.png">

**Comment by stamblerre** [comment]
I thought semantic tokens was on, but you're right, I can no longer reproduce.
