### ISSUE TITLE
gollvm: golang.org/x/mod/semver package is not compiling on Ubuntu 20.04 (Github Actions)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [golang/go#42843]
Hi.
All jobs for https://github.com/advancedwebdeveloper/clang_test_cpu_features/runs/1446453097 failed.
Here is what I see [here](https://github.com/advancedwebdeveloper/clang_test_cpu_features/commit/c147becf73c0cbe6e2cb0567244ed0ba53174841/checks/1446453041/logs):

> [1497/2668] Building Go package 'golang.org/x/mod/semver' (non-PIC)
> FAILED: tools/gollvm/libgo/golang.org/x/mod/semver.o 
> cd /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/build_release/tools/gollvm/libgo && /usr/local/bin/cmake -E make_directory ./golang.org/x/mod && /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/build_release/./bin/llvm-goc -c -o /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/build_release/tools/gollvm/libgo/golang.org/x/mod/semver.o -fgo-pkgpath=golang.org/x/mod/semver -I . /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/golang.org/x/mod/semver/semver.go
> 
> 0.	Program arguments: /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/build_release/./bin/llvm-goc -c -o /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/build_release/tools/gollvm/libgo/golang.org/x/mod/semver.o -fgo-pkgpath=golang.org/x/mod/semver -I . /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/golang.org/x/mod/semver/semver.go
> 1.	Running pass 'Function Pass Manager' on module 'gomodule'.
> 2.	Running pass 'Combine redundant instructions' on function '@golang_0org_1x_1mod_1semver.parse'
>  Segmentation fault (core dumped)

That's coming from Clang 11.

**Comment by ianlancetaylor** [comment]
I can build the package with gccgo using `go build`.

I'm not sure how to interpret that output but it looks like a middle-end bug.

**Comment by ianlancetaylor** [comment]
CC @thanm @cherrymui

**Comment by advancedwebdeveloper** [comment]
My workflow (Github Actions) could be modified, to trace anything that you would require.
Request anything you want - or try to modify the YAML file, within your own repo.
That could allow to reproduce/check some fault scenarios.

@ianlancetaylor , you didn't explain what should I trace/log.
Anything that I should check, ahead of @thanm's investigation?

**Comment by ianlancetaylor** [comment]
I'm sorry, I don't know.

**Comment by thanm** [comment]
Is this a problem only with the Release cmake target? Or do you also see it with DCMAKE_BUILD_TYPE=RelWithDebInfo?

**Comment by advancedwebdeveloper** [comment]
It might no more be reproducible/no issue present - some errors of another kind are observable, during https://github.com/advancedwebdeveloper/clang_test_cpu_features/actions/runs/395799034

As you can observe in the logs - I caught these errors, while using Clang 9:

> [1197/2669] Building CXX object tools/gollvm/passes/CMakeFiles/LLVMCppGoPasses.dir/GoSafeGetg.cpp.o
> [1198/2669] Building CXX object tools/gollvm/passes/CMakeFiles/LLVMCppGoPasses.dir/RemoveAddrSpace.cpp.o
> [1199/2669] Building CXX object lib/ProfileData/CMakeFiles/LLVMProfileData.dir/SampleProfWriter.cpp.o
> [1200/2669] Building CXX object lib/ProfileData/CMakeFiles/LLVMProfileData.dir/SampleProfReader.cpp.o
> [1201/2669] Building CXX object tools/gollvm/passes/CMakeFiles/LLVMCppGoPasses.dir/GC.cpp.o
> [1202/2669] Building CXX object tools/gollvm/passes/CMakeFiles/LLVMCppGoPasses.dir/GoAnnotation.cpp.o
> [1203/2669] Building CXX object tools/gollvm/passes/CMakeFiles/LLVMCppGoPasses.dir/GoWrappers.cpp.o
> [1204/2669] Building CXX object tools/gollvm/passes/CMakeFiles/LLVMCppGoPasses.dir/GoNilChecks.cpp.o
> FAILED: tools/gollvm/passes/CMakeFiles/LLVMCppGoPasses.dir/GoNilChecks.cpp.o 
> 2020-12-02T10:43:03.8272246Z /usr/bin/clang++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/gollvm/passes -I/home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/passes -Iinclude -I/home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -O2 -g -DNDEBUG    -fno-exceptions -fno-rtti -std=c++14 -MD -MT tools/gollvm/passes/CMakeFiles/LLVMCppGoPasses.dir/GoNilChecks.cpp.o -MF tools/gollvm/passes/CMakeFiles/LLVMCppGoPasses.dir/GoNilChecks.cpp.o.d -o tools/gollvm/passes/CMakeFiles/LLVMCppGoPasses.dir/GoNilChecks.cpp.o -c /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/passes/GoNilChecks.cpp /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/passes/**GoNilChecks.cpp:361:68: error: no member named 'unknown' in 'llvm::LocationSize'**
> AA->alias(MemoryLocation(MMO1->getValue(), LocationSize::unknown(),
>                                                       ~~~~~~~~~~~~~~^ /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/passes/GoNilChecks.cpp:363:68: error: no member named 'unknown' in 'llvm::LocationSize'
> MemoryLocation(MMO2->getValue(), LocationSize::unknown(),
>                                                       ~~~~~~~~~~~~~~^
>  2 errors generated.

.
There is a bug, with GCC:

> FAILED: lib/CodeGen/AsmPrinter/CMakeFiles/LLVMAsmPrinter.dir/AsmPrinter.cpp.o 
> /usr/bin/c++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/CodeGen/AsmPrinter -I/home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/lib/CodeGen/AsmPrinter -Iinclude -I/home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -O2 -g -DNDEBUG    -fno-exceptions -fno-rtti -std=c++14 -MD -MT lib/CodeGen/AsmPrinter/CMakeFiles/LLVMAsmPrinter.dir/AsmPrinter.cpp.o -MF lib/CodeGen/AsmPrinter/CMakeFiles/LLVMAsmPrinter.dir/AsmPrinter.cpp.o.d -o lib/CodeGen/AsmPrinter/CMakeFiles/LLVMAsmPrinter.dir/AsmPrinter.cpp.o -c /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
> c++: internal compiler error: Killed (program cc1plus)

. I got the very same bug, as I caught with Clang 9, while using Clang 10:

> [1196/2669] Building CXX object tools/gollvm/passes/CMakeFiles/LLVMCppGoPasses.dir/GoNilChecks.cpp.o
> FAILED: tools/gollvm/passes/CMakeFiles/LLVMCppGoPasses.dir/GoNilChecks.cpp.o 
> /usr/bin/clang++-10  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/gollvm/passes -I/home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/passes -Iinclude -I/home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -O2 -g -DNDEBUG    -fno-exceptions -fno-rtti -std=c++14 -MD -MT tools/gollvm/passes/CMakeFiles/LLVMCppGoPasses.dir/GoNilChecks.cpp.o -MF tools/gollvm/passes/CMakeFiles/LLVMCppGoPasses.dir/GoNilChecks.cpp.o.d -o tools/gollvm/passes/CMakeFiles/LLVMCppGoPasses.dir/GoNilChecks.cpp.o -c /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/passes/GoNilChecks.cpp
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/passes/GoNilChecks.cpp:361:68: error: no member named 'unknown' in 'llvm::LocationSize'
>            AA->alias(MemoryLocation(MMO1->getValue(), LocationSize::unknown(),
>  /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/passes/GoNilChecks.cpp:363:68: error: no member named 'unknown' in 'llvm::LocationSize'
>                      MemoryLocation(MMO2->getValue(), LocationSize::unknown(),
> 2 errors generated.
. And the same bug is present with Clang 11, too.

**Comment by thanm** [comment]
OK, that looks a bit more actionable. I'll send a patch later this morning for the build problem.

For the original issue (crash in Combine redundant instructions) I am able to reproduce that as well, will need to take a closer look.

**Comment by advancedwebdeveloper** [comment]
Yes, your patch resolved the last issue.
I tried to re-run the workflow - and (as you can see) various packages are not compiled.
I am unsure what should be logged.

**Comment by thanm** [comment]
I just submitted [29d8ea6cf9e08a51f89d72dbeca6c0aed4c2016a](https://go.googlesource.com/gollvm/+/29d8ea6cf9e08a51f89d72dbeca6c0aed4c2016a), that should resolve the llvm-goc runtime error.

**Comment by advancedwebdeveloper** [comment]
From https://github.com/advancedwebdeveloper/clang_test_cpu_features/commit/e8a830d4c248db0961e0f57f9d61e032efd1cb15/checks/1491324337/logs (Clang 9):   

> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/build_relwdebinfo/tools/gollvm/libgo/sigtab.go
>  /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:22:39: error: use of undefined type 'epollevent'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:52:3: error: reference to undefined name 'events'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:52:11: error: reference to undefined name '_EPOLLIN'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:22:39: error: use of undefined type 'epollevent'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:72:4: error: reference to field 'events' in object which has no fields or methods
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:72:14: error: reference to undefined name '_EPOLLIN'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:72:25: error: reference to undefined name '_EPOLLOUT'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:73:34: error: reference to field 'data' in object which has no fields or methods
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:22:39: error: use of undefined type 'epollevent'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:155:8: error: reference to field 'events' in object which has no fields or methods
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:159:37: error: reference to field 'data' in object which has no fields or methods
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:160:9: error: reference to field 'events' in object which has no fields or methods
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:160:20: error: reference to undefined name '_EPOLLIN'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:161:55: error: reference to field 'events' in object which has no fields or methods
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:176:8: error: reference to field 'events' in object which has no fields or methods
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:176:17: error: reference to undefined name '_EPOLLIN'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:176:38: error: reference to undefined name '_EPOLLHUP'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:176:48: error: reference to undefined name '_EPOLLERR'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:179:8: error: reference to field 'events' in object which has no fields or methods
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:179:17: error: reference to undefined name '_EPOLLOUT'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:179:27: error: reference to undefined name '_EPOLLHUP'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:179:37: error: reference to undefined name '_EPOLLERR'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:183:42: error: reference to field 'data' in object which has no fields or methods
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:185:9: error: reference to field 'events' in object which has no fields or methods
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:185:20: error: reference to undefined name '_EPOLLERR'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/signal_unix.go:316:13: error: reference to undefined name '_ITIMER_PROF'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/signal_unix.go:321:13: error: reference to undefined name '_ITIMER_PROF'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/signal_unix.go:498:20: error: reference to undefined name '_SI_USER'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/signal_unix.go:508:20: error: reference to undefined name '_SI_USER'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/signal_unix.go:528:20: error: reference to undefined name '_SI_USER'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/signal_unix.go:534:20: error: reference to undefined name '_SI_USER'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/signal_unix.go:654:20: error: reference to undefined name '_BUS_ADRERR'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/signal_unix.go:664:40: error: reference to undefined name '_SEGV_MAPERR'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/signal_unix.go:664:70: error: reference to undefined name '_SEGV_ACCERR'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/signal_unix.go:675:8: error: reference to undefined name '_FPE_INTDIV'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/signal_unix.go:677:8: error: reference to undefined name '_FPE_INTOVF'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/signal_unix.go:762:92: error: reference to undefined name '_SI_USER'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/signal_unix.go:939:21: error: reference to undefined name '_SI_USER'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/signal_unix.go:1029:17: error: reference to undefined name '_SS_DISABLE'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:22:39: error: use of undefined type 'epollevent'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:22:39: error: use of undefined type 'epollevent'
> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/netpoll_epoll.go:22:39: error: use of undefined type 'epollevent'

.

**Comment by advancedwebdeveloper** [comment]
You can investigate the log for GCC oriented build https://github.com/advancedwebdeveloper/clang_test_cpu_features/commit/e8a830d4c248db0961e0f57f9d61e032efd1cb15/checks/1491324454/logs - it looks like the compilation process itself crashes:

> FAILED: lib/CodeGen/AsmPrinter/CMakeFiles/LLVMAsmPrinter.dir/AsmPrinter.cpp.o 
> 2020-12-03T09:00:19.1123741Z /usr/bin/c++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/CodeGen/AsmPrinter -I/home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/lib/CodeGen/AsmPrinter -Iinclude -I/home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -O2 -g -DNDEBUG    -fno-exceptions -fno-rtti -std=c++14 -MD -MT lib/CodeGen/AsmPrinter/CMakeFiles/LLVMAsmPrinter.dir/AsmPrinter.cpp.o -MF lib/CodeGen/AsmPrinter/CMakeFiles/LLVMAsmPrinter.dir/AsmPrinter.cpp.o.d -o lib/CodeGen/AsmPrinter/CMakeFiles/LLVMAsmPrinter.dir/AsmPrinter.cpp.o -c /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
> c++: internal compiler error: Killed (program cc1plus)

@thanm, which verbosity options should be enabled?
I am not familiar with GCC, really.

**Comment by advancedwebdeveloper** [comment]
I am confirming that go.googlesource.com/gollvm/+/29d8ea6cf9e08a51f89d72dbeca6c0aed4c2016a allowed to build gollvm with Clang 10:
https://github.com/advancedwebdeveloper/clang_test_cpu_features/runs/1491324386?check_suite_focus=true
. Same for Clang 11:
https://github.com/advancedwebdeveloper/clang_test_cpu_features/runs/1491324420?check_suite_focus=true
.
Everybody dance now :)

**Comment by advancedwebdeveloper** [comment]
I just tried to build for "release" - and I didn't get that issue, with GCC, any more:
https://github.com/advancedwebdeveloper/clang_test_cpu_features/runs/1491760391?check_suite_focus=true
. All tests passed successfully.
Clang 10 and Clang 11 built gollvm successfully, as before.

Not sure if it makes sense to support Clang 9.

Thanks for assisting/patching.
Closing this.
