### ISSUE TITLE
cmd/compile: improve "have X want Y" error with additional file and line information

### ISSUE THREAD

**Issue by raspi** [golang/go#42841]
### What version of Go are you using (`go version`)?

<pre>
go1.15.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```go
package main

type S interface {
	DoSomething() (int, error)
}

type myS struct{}

func (s myS) DoSomething() (string, error) {
	return ``, nil
}

func main() {
	var _ S = &myS{}
}
```

### What did you expect to see?

Show also line information (`foo.go:123:57`) for **have** line. The implementation might be in completely different file. In modern IDEs you simply can click the file information line to navigate to referenced file and line quickly. 

**want** could also have line information to referenced interface definition line?

```
./prog.go:14:6: cannot use &myS literal (type *myS) as type S in assignment:
	*myS does not implement S (wrong type for DoSomething method)
		have DoSomething() (string, error) at ./prog.go:9:28
		want DoSomething() (int, error)
```

### What did you see instead?

```
./prog.go:14:6: cannot use &myS literal (type *myS) as type S in assignment:
	*myS does not implement S (wrong type for DoSomething method)
		have DoSomething() (string, error)
		want DoSomething() (int, error)
```

**Comment by networkimprov** [comment]
cc @mdempsky @griesemer 

Seems overlooked by triage?

**Comment by ianlancetaylor** [comment]
@griesemer Should this stay in the Go1.18 milestone or should we move it to Backlog?

**Comment by griesemer** [comment]
I think this is either done or mostly done (or pending CL). We should keep this for 1.18; I will take care of it.

**Comment by odeke-em** [comment]
I've mailed a CL for this per https://golang.org/cl/373634.
