### ISSUE TITLE
x/tour: explain function syntax better

### ISSUE THREAD

**Issue by btracey** [golang/go#4284]
<pre>For those of us who are trying to pick up Go, but aren't CS majors, could we change the
description of 

<a href="http://tour.golang.org/#39">http://tour.golang.org/#39</a>

to be more explicit? I'm not sure how to parse the adder function declaration

func adder() func(int) int

It appears that adder is a function which takes no arguments, but returns a function
which takes an int as an argument and returns an int? Assuming that's correct, could you
also state how that works if it's nested? For example, what if the function adder
returns is also a closure? Is the definition

func adder() func1(int) func2(int) int

?</pre>

**Comment by kytrinyx** [comment]
This is now [/moretypes/21](http://tour.golang.org/moretypes/21).

The slide is focusing on the closure, and the function signature seems somewhat incidental. I suspect that adding explanations regarding the function signature might distract from the main point.

@adg What about adding a separate slide about function values?

**Comment by adg** [comment]
The [previous slide](http://tour.golang.org/moretypes/20) is about function values, but it doesn't say much. We could certainly expand on that.

**Comment by kytrinyx** [comment]
Agreed. I'll take this one.

**Comment by kytrinyx** [comment]
Would it be too much to expand the code example for the function values slide? E.g. something like this:

```
package main

import (
	"fmt"
	"math"
)

func compute(x, y float64, fn func(float64, float64) float64) float64 {
	return fn(x, y)
}

func main() {
	hypot := func(x, y float64) float64 {
		return math.Sqrt(x*x + y*y)
	}
	fmt.Println(hypot(5, 12))
	
	fmt.Println(compute(3, 4, hypot))
	fmt.Println(compute(3, 4, math.Pow))
}
```

**Comment by adg** [comment]
@kytrinyx how about just having `compute` take a single argument—the function—and then it does `fmt.Println(fn(3, 4))`. Then the example gets smaller too.

**Comment by kytrinyx** [comment]
Oh, nice. Yepp, I like that.
