### ISSUE TITLE
Plugins can't use different C libraries by CGO with the same symbol names

### ISSUE THREAD

**Issue by dsxack** [golang/go#42854]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go version go1.15.5 linux/amd64
root@2ce5210666df:/go# go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build189801058=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### hello1.c:

I have a `hello1/lib/hello1.c` library and built it into `hello1/lib/libhello1.a`

```c
#include <stdio.h>

void hello() {
    printf("Hello from C hello1.c\n");
}
```

#### hello2.c:

I have a `hello2/lib/hello2.c` library with the same function name `hello` that in `hello1.c`  and built it into `hello2/lib/libhello2.a`

```c
#include <stdio.h>

void hello() {
    printf("Hello from C hello2.c\n");
}
```

#### hello1.go:

I have a `hello1/hello1.go` and built it into `hello1/hello1.so` with `go build -buildmode=plugin`

```go
package main

/*
#cgo LDFLAGS: -L${SRCDIR}/lib -lhello1

void hello();
*/
import "C"
import "fmt"

func Hello() {
	fmt.Println("Hello from Go plugin hello1.go")
	fmt.Println("Call C hello1.c")
	C.hello()
}
```

#### hello2.go:

I have a `hello2/hello2.go` and built it into `hello2/hello2.so` with `go build -buildmode=plugin`

```go
package main

/*
#cgo LDFLAGS: -L${SRCDIR}/lib -lhello2

void hello();
*/
import "C"
import "fmt"

func Hello() {
	fmt.Println("Hello from Go plugin hello2.go")
	fmt.Println("Call C hello2.c")
	C.hello()
}
```

#### main.go:

I have a `main.go` in the root project dir and built it into `main` with `go build`.

```go
package main

import (
	"fmt"
	"plugin"
)

func main() {
	p1, err := plugin.Open("hello1/hello1.so")
	if err != nil {
		panic(err)
	}
	fmt.Println("Load Go plugin hello1.so")

	p2, err := plugin.Open("hello2/hello2.so")
	if err != nil {
		panic(err)
	}
	fmt.Println("Load Go plugin hello2.so")

	h1, err := p1.Lookup("Hello")
	if err != nil {
		panic(err)
	}

	h2, err := p2.Lookup("Hello")
	if err != nil {
		panic(err)
	}

	fmt.Println("Call Go plugin hello1.go")
	h1.(func())()
	fmt.Println("\nCall Go plugin hello2.go")
	h2.(func())()
}
```

### What did you expect to see?

```sh
Load Go plugin hello1.so
Load Go plugin hello2.so

Call Go plugin hello1.go
Hello from Go plugin hello1.go
Call C hello1.c
Hello from C hello1.c

Call Go plugin hello2.go
Hello from Go plugin hello2.go
Call C hello2.c
Hello from C hello2.c
```

### What did you see instead?

I see `Hello from C hello1.c` at the last line but I expected `Hello from C hello2.c`

```sh
Load Go plugin hello1.so
Load Go plugin hello2.so

Call Go plugin hello1.go
Hello from Go plugin hello1.go
Call C hello1.c
Hello from C hello1.c

Call Go plugin hello2.go
Hello from Go plugin hello2.go
Call C hello2.c
Hello from C hello1.c
```

**Comment by AlexRouSg** [comment]
If you only load `hello2.so` does it print what you expect?

**Comment by dsxack** [comment]
@AlexRouSg I can't impact to C libraries code because it is vendor libraries.

**Comment by dsxack** [comment]
@AlexRouSg yes, if I load `hello2.so` only it prints what I expect.

Also I can't impact to C libraries code because it is vendor libraries.

**Comment by AlexRouSg** [comment]
What happens when you use the `-fvisibility=hidden` gcc flag?

**Comment by dsxack** [comment]
@AlexRouSg yes, it works! Thank you!

```
Load Go plugin hello1.so
Load Go plugin hello2.so

Call Go plugin hello1.go
Hello from Go plugin hello1.go
Call C hello1.c
Hello from C hello1.c

Call Go plugin hello2.go
Hello from Go plugin hello2.go
Call С hello2.c
Hello from C hello2.c
```
