### ISSUE TITLE
rosetta2 crash during bootstrap

### ISSUE THREAD

**Issue by directionless** [golang/go#42864]
rosetta2 seems pretty inconsistent, given the inconsistencies, I'm not sure if this issue is useful. It did work the second time. But I wanted to send it along

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Issue is inconsistent. 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
seph@osquery-adp-1 src % go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/seph/Library/Caches/go-build"
GOENV="/Users/seph/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/seph/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/seph/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/seph/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/seph/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/seph/manual-go-build/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sj/rnzw7ddn78995n596yll525r0000gn/T/go-build512687466=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

1. Cloned go from git. sha is `358d35455d06b1ebee948efff123842490dcb797`
2. `GODEBUG=asyncpreemptoff=1 GOOS=darwin GOARCH=arm64 ./bootstrap.bash`

### What did you expect to see?

A successful compilation

### What did you see instead?

A giant crash, which then hung, and had to be control-c'ed.

<details><summary><code>output</code></summary><br><pre>
seph@osquery-adp-1 go % cd src                      
seph@osquery-adp-1 src % GODEBUG=asyncpreemptoff=1 GOOS=darwin GOARCH=arm64 ./bootstrap.bash
#### Building ../../go-darwin-arm64-bootstrap

Building Go cmd/dist using /Users/seph/go. (go1.15.5 darwin/amd64)
Building Go toolchain1 using /Users/seph/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for host, darwin/amd64.
# cmd/vendor/golang.org/x/arch/arm/armasm
runtime: unexpected return pc for cmd/compile/internal/ssa.rewriteValueAMD64_OpAMD64MOVLstore called from 0xc000038480
stack: frame={sp:0xc000939768, fp:0xc000939c10} stack=[0xc000938000,0xc00093a000)
000000c000939668:  000000c000939720  000000c000898528 
000000c000939678:  0000000002fc2b98  0000000000000601 
000000c000939688:  0101000000000000  0000000002fc2b98 
000000c000939698:  0000000000000000  0000000000000018 
000000c0009396a8:  000000c000083200  0000000000000018 
000000c0009396b8:  000000c000898528  000000000000003b 
000000c0009396c8:  000000c000038480  000000c000083220 
000000c0009396d8:  0000000000000000  0000000001865a00 
000000c0009396e8:  000000c000898528  0000000000000000 
000000c0009396f8:  0000000000000000  0000000000000000 
000000c000939708:  0000000000000000  000000c000939758 
000000c000939718:  0000000001033ee5 <runtime.goPanicIndex+165>  0000000001865a00 
000000c000939728:  000000c000898528  0000000001865a00 
000000c000939738:  000000c000898528  0000000000000001 
000000c000939748:  0000000000000001  0000000000000001 
000000c000939758:  000000c0009399b8  000000000133cc4c <cmd/compile/internal/ssa.rewriteValueAMD64_OpAMD64MOVLstore+24780> 
000000c000939768: <0000000000000001  0000000000000001 
000000c000939778:  000000c000713280  0000000000203000 
000000c000939788:  000000c0008f47c8  000000000128231d <cmd/compile/internal/ssa.(*Block).NewValue2A+93> 
000000c000939798:  000000c000848000  0000000000000977 
000000c0009397a8:  000000c000dbb500  000000c001011401 
000000c0009397b8:  0001b06000000003  000000c00104db88 
000000c0009397c8:  000000c0008f4820  00000000017099ce <cmd/compile/internal/gc.(*state).newValue2Apos+174> 
000000c0009397d8:  000000c001084438  0001b06000000003 
000000c0009397e8:  000000c000000977  000000c000dbb500 
000000c0009397f8:  000000000188f880  000000c000727b30 
000000c000939808:  000000c000a64d80  000000c00104db18 
000000c000939818:  000000c00104db88  000000c000713280 
000000c000939828:  000000000172e845 <cmd/compile/internal/gc.(*state).addr+3205>  000000c000928000 
000000c000939838:  0000000000000977  000000c000dbb500 
000000c000939848:  000000000188f880  000000c000727b30 
000000c000939858:  000000c00104d8e8  000000c0008f48c0 
000000c000939868:  000000000173b449 <cmd/compile/internal/gc.(*state).variable+73>  000000000182d880 
000000c000939878:  000000c000846120  000000c0008f48c0 
000000c000939888:  0000000001012b7b <runtime.mapassign_fast64ptr+91>  000000c0008f48e0 
000000c000939898:  00000000c4aba3ad  5033df393f0ae07c 
000000c0009398a8:  000000c001084438  5033df393f0ae07c 
000000c0009398b8:  000000c00104dbf8  000000c0008f4920 
000000c0009398c8:  000000000170ac7f <cmd/compile/internal/gc.(*state).zero+351>  000000000182d880 
000000c0009398d8:  000000c000846120  0000000001d203a0 
000000c0009398e8:  000000c000718048  0000000000000028 
000000c0009398f8:  000000c00104db88  000000c00104db18 
000000c000939908:  000000c00104dbf8  0000000000000028 
000000c000939918:  000000c00104dbf8  000000c0008f49f0 
000000c000939928:  000000000171dcac <cmd/compile/internal/gc.(*state).assign+2444>  000000c000928000 
000000c000939938:  000000c000dbb200  000000c00104db88 
000000c000939948:  000000c000718048  000000c000727b30 
000000c000939958:  000000c00104d878  000000c000848001 
000000c000939968:  000000c00104db18  000000c0000bd0e0 
000000c000939978:  000000010994184c  0020300000000000 
000000c000939988:  000000c00104daa8  000000c000713280 
000000c000939998:  000000000171e418 <cmd/compile/internal/gc.(*state).zeroVal+1304>  000000c000dbb200 
000000c0009399a8:  000000c000928000  00000000018c1de8 
000000c0009399b8:  000000c0009399f0  000000000170af78 <cmd/compile/internal/gc.(*state).stmtList+88> 
000000c0009399c8:  000000c000928000  000000c001184e00 
000000c0009399d8:  0000000000000001  0000000000000000 
000000c0009399e8:  000000c000a4d628  000000c000939c48 
000000c0009399f8:  000000000170c5f1 <cmd/compile/internal/gc.(*state).stmt+5681>  000000c000928000 
000000c000939a08:  000000c0011804c8  0000000000000000 
000000c000939a18:  0000000001010001 <runtime.mapdelete+833>  000000002a042600 
000000c000939a28:  0020300000000000  000000002a1fffff 
000000c000939a38:  0000000002fc0b30  0000000001017000 <runtime.heapBitsSetTypeGCProg+320> 
000000c000939a48:  0000000000000008  0000000000000001 
000000c000939a58:  000000c0008f4ab0  00000000010185f3 <runtime.(*mcentral).cacheSpan+403> 
000000c000939a68:  0000000002fc0b30  0000000000000000 
000000c000939a78:  0000000001013e82 <runtime.mapaccess2_faststr+674>  000000c0008f4b00 
000000c000939a88:  0000000100000006  0000000000000064 
000000c000939a98:  000000c000dbb200  a2000000010532de 
000000c000939aa8:  0000000000000000  0000000000000000 
000000c000939ab8:  000000c0008f4b10  00000000010185f3 <runtime.(*mcentral).cacheSpan+403> 
000000c000939ac8:  0000000000000000  0000000000000000 
000000c000939ad8:  0000000000000017  000000c0008f4b38 
000000c000939ae8:  0000000000000008  0000000002f2ec40 
000000c000939af8:  0000000002fc0b30  0000000000203000 
000000c000939b08:  0000000000000000  000000c0008f4b58 
000000c000939b18:  0000000001017cf7 <runtime.(*mcache).refill+311>  0000000001de8ae8 
000000c000939b28:  0000000001de8ae8  0000000000000000 
000000c000939b38:  0000000000000008  0000000000000400 
000000c000939b48:  0000000002fc0b30  0000000000203000 
000000c000939b58:  000000c0008f4b90  000000000100d2aa <runtime.(*mcache).nextFree+170> 
000000c000939b68:  0000000002fc0b30  0000000000000001 
000000c000939b78:  0000000000203000  0000000000203000 
000000c000939b88:  0000000002fc0b30  000000c0008f4c18 
000000c000939b98:  000000000100d79b <runtime.mallocgc+859>  000000c00084c008 
000000c000939ba8:  0000000000000008  0000000000000008 
000000c000939bb8:  000000000188f880  000000000100d701 <runtime.mallocgc+705> 
000000c000939bc8:  000100c000718090  0000000002fc0b30 
000000c000939bd8:  0000000000000008  0000000000000008 
000000c000939be8:  0000000002b60f18  0000000000000008 
000000c000939bf8:  000000c00084c008  000000c0000bd0e0 
000000c000939c08: !000000c000038480 >0000000000000000 
000000c000939c18:  000000c0008f4c80  000000000104f645 <runtime.growslice+421> 
000000c000939c28:  000000c00084c008  0000000000000000 
000000c000939c38:  000000c000928000  00000000018c1de8 
000000c000939c48:  000000c000939c80  000000000170af78 <cmd/compile/internal/gc.(*state).stmtList+88> 
000000c000939c58:  000000c000928000  000000c001184e80 
000000c000939c68:  0000000000000027  0000000000000004 
000000c000939c78:  000000c00036b200  000000c000939ea8 
000000c000939c88:  0000000001707887 <cmd/compile/internal/gc.buildssa+4359>  000000c000928000 
000000c000939c98:  000000c0011804b0  0000000000000000 
000000c000939ca8:  0000000000000000  0000000000000001 
000000c000939cb8:  000000c00084c008  0000000000000000 
000000c000939cc8:  0000000000000001  000000c00104da38 
000000c000939cd8:  0000000001de0410  760000000182c200 
000000c000939ce8:  0000002a01000000  0000000000000000 
000000c000939cf8:  0000000000000001  0000000000000001 
000000c000939d08:  0000000000000009 
fatal error: unknown caller pc

runtime stack:
runtime.throw(0x18a2a8f, 0x11)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/runtime/panic.go:1112 +0x72
runtime.gentraceback(0x1033ee5, 0xc000939720, 0x0, 0xc000083200, 0x0, 0x0, 0x7fffffff, 0x2062f7f40, 0x0, 0x0, ...)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/runtime/traceback.go:261 +0x1a56
runtime.addOneOpenDeferFrame.func1()
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/runtime/panic.go:717 +0x91
runtime.systemstack(0x2062f7fa0)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/runtime/asm_amd64.s:375 +0x66
runtime.mstart()
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/runtime/proc.go:1183

goroutine 35 [running]:
runtime.systemstack_switch()
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/runtime/asm_amd64.s:335 fp=0xc000939618 sp=0xc000939610 pc=0x106cc20
runtime.addOneOpenDeferFrame(0xc000083200, 0x1033ee5, 0xc000939720)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/runtime/panic.go:716 +0x7b fp=0xc000939658 sp=0xc000939618 pc=0x1035a3b
panic(0x1865a00, 0xc000898528)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/runtime/panic.go:925 +0x125 fp=0xc000939720 sp=0xc000939658 pc=0x10365c5
runtime.goPanicIndex(0x1, 0x1)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/runtime/panic.go:88 +0xa5 fp=0xc000939768 sp=0xc000939720 pc=0x1033ee5
runtime: unexpected return pc for cmd/compile/internal/ssa.rewriteValueAMD64_OpAMD64MOVLstore called from 0xc000038480
stack: frame={sp:0xc000939768, fp:0xc000939c10} stack=[0xc000938000,0xc00093a000)
000000c000939668:  000000c000939720  000000c000898528 
000000c000939678:  0000000002fc2b98  0000000000000601 
000000c000939688:  0101000000000000  0000000002fc2b98 
000000c000939698:  0000000000000000  0000000000000018 
000000c0009396a8:  000000c000083200  0000000000000018 
000000c0009396b8:  000000c000898528  000000000000003b 
000000c0009396c8:  000000c000038480  000000c000083220 
000000c0009396d8:  0000000000000000  0000000001865a00 
000000c0009396e8:  000000c000898528  0000000000000000 
000000c0009396f8:  0000000000000000  0000000000000000 
000000c000939708:  0000000000000000  000000c000939758 
000000c000939718:  0000000001033ee5 <runtime.goPanicIndex+165>  0000000001865a00 
000000c000939728:  000000c000898528  0000000001865a00 
000000c000939738:  000000c000898528  0000000000000001 
000000c000939748:  0000000000000001  0000000000000001 
000000c000939758:  000000c0009399b8  000000000133cc4c <cmd/compile/internal/ssa.rewriteValueAMD64_OpAMD64MOVLstore+24780> 
000000c000939768: <0000000000000001  0000000000000001 
000000c000939778:  000000c000713280  0000000000203000 
000000c000939788:  000000c0008f47c8  000000000128231d <cmd/compile/internal/ssa.(*Block).NewValue2A+93> 
000000c000939798:  000000c000848000  0000000000000977 
000000c0009397a8:  000000c000dbb500  000000c001011401 
000000c0009397b8:  0001b06000000003  000000c00104db88 
000000c0009397c8:  000000c0008f4820  00000000017099ce <cmd/compile/internal/gc.(*state).newValue2Apos+174> 
000000c0009397d8:  000000c001084438  0001b06000000003 
000000c0009397e8:  000000c000000977  000000c000dbb500 
000000c0009397f8:  000000000188f880  000000c000727b30 
000000c000939808:  000000c000a64d80  000000c00104db18 
000000c000939818:  000000c00104db88  000000c000713280 
000000c000939828:  000000000172e845 <cmd/compile/internal/gc.(*state).addr+3205>  000000c000928000 
000000c000939838:  0000000000000977  000000c000dbb500 
000000c000939848:  000000000188f880  000000c000727b30 
000000c000939858:  000000c00104d8e8  000000c0008f48c0 
000000c000939868:  000000000173b449 <cmd/compile/internal/gc.(*state).variable+73>  000000000182d880 
000000c000939878:  000000c000846120  000000c0008f48c0 
000000c000939888:  0000000001012b7b <runtime.mapassign_fast64ptr+91>  000000c0008f48e0 
000000c000939898:  00000000c4aba3ad  5033df393f0ae07c 
000000c0009398a8:  000000c001084438  5033df393f0ae07c 
000000c0009398b8:  000000c00104dbf8  000000c0008f4920 
000000c0009398c8:  000000000170ac7f <cmd/compile/internal/gc.(*state).zero+351>  000000000182d880 
000000c0009398d8:  000000c000846120  0000000001d203a0 
000000c0009398e8:  000000c000718048  0000000000000028 
000000c0009398f8:  000000c00104db88  000000c00104db18 
000000c000939908:  000000c00104dbf8  0000000000000028 
000000c000939918:  000000c00104dbf8  000000c0008f49f0 
000000c000939928:  000000000171dcac <cmd/compile/internal/gc.(*state).assign+2444>  000000c000928000 
000000c000939938:  000000c000dbb200  000000c00104db88 
000000c000939948:  000000c000718048  000000c000727b30 
000000c000939958:  000000c00104d878  000000c000848001 
000000c000939968:  000000c00104db18  000000c0000bd0e0 
000000c000939978:  000000010994184c  0020300000000000 
000000c000939988:  000000c00104daa8  000000c000713280 
000000c000939998:  000000000171e418 <cmd/compile/internal/gc.(*state).zeroVal+1304>  000000c000dbb200 
000000c0009399a8:  000000c000928000  00000000018c1de8 
000000c0009399b8:  000000c0009399f0  000000000170af78 <cmd/compile/internal/gc.(*state).stmtList+88> 
000000c0009399c8:  000000c000928000  000000c001184e00 
000000c0009399d8:  0000000000000001  0000000000000000 
000000c0009399e8:  000000c000a4d628  000000c000939c48 
000000c0009399f8:  000000000170c5f1 <cmd/compile/internal/gc.(*state).stmt+5681>  000000c000928000 
000000c000939a08:  000000c0011804c8  0000000000000000 
000000c000939a18:  0000000001010001 <runtime.mapdelete+833>  000000002a042600 
000000c000939a28:  0020300000000000  000000002a1fffff 
000000c000939a38:  0000000002fc0b30  0000000001017000 <runtime.heapBitsSetTypeGCProg+320> 
000000c000939a48:  0000000000000008  0000000000000001 
000000c000939a58:  000000c0008f4ab0  00000000010185f3 <runtime.(*mcentral).cacheSpan+403> 
000000c000939a68:  0000000002fc0b30  0000000000000000 
000000c000939a78:  0000000001013e82 <runtime.mapaccess2_faststr+674>  000000c0008f4b00 
000000c000939a88:  0000000100000006  0000000000000064 
000000c000939a98:  000000c000dbb200  a2000000010532de 
000000c000939aa8:  0000000000000000  0000000000000000 
000000c000939ab8:  000000c0008f4b10  00000000010185f3 <runtime.(*mcentral).cacheSpan+403> 
000000c000939ac8:  0000000000000000  0000000000000000 
000000c000939ad8:  0000000000000017  000000c0008f4b38 
000000c000939ae8:  0000000000000008  0000000002f2ec40 
000000c000939af8:  0000000002fc0b30  0000000000203000 
000000c000939b08:  0000000000000000  000000c0008f4b58 
000000c000939b18:  0000000001017cf7 <runtime.(*mcache).refill+311>  0000000001de8ae8 
000000c000939b28:  0000000001de8ae8  0000000000000000 
000000c000939b38:  0000000000000008  0000000000000400 
000000c000939b48:  0000000002fc0b30  0000000000203000 
000000c000939b58:  000000c0008f4b90  000000000100d2aa <runtime.(*mcache).nextFree+170> 
000000c000939b68:  0000000002fc0b30  0000000000000001 
000000c000939b78:  0000000000203000  0000000000203000 
000000c000939b88:  0000000002fc0b30  000000c0008f4c18 
000000c000939b98:  000000000100d79b <runtime.mallocgc+859>  000000c00084c008 
000000c000939ba8:  0000000000000008  0000000000000008 
000000c000939bb8:  000000000188f880  000000000100d701 <runtime.mallocgc+705> 
000000c000939bc8:  000100c000718090  0000000002fc0b30 
000000c000939bd8:  0000000000000008  0000000000000008 
000000c000939be8:  0000000002b60f18  0000000000000008 
000000c000939bf8:  000000c00084c008  000000c0000bd0e0 
000000c000939c08: !000000c000038480 >0000000000000000 
000000c000939c18:  000000c0008f4c80  000000000104f645 <runtime.growslice+421> 
000000c000939c28:  000000c00084c008  0000000000000000 
000000c000939c38:  000000c000928000  00000000018c1de8 
000000c000939c48:  000000c000939c80  000000000170af78 <cmd/compile/internal/gc.(*state).stmtList+88> 
000000c000939c58:  000000c000928000  000000c001184e80 
000000c000939c68:  0000000000000027  0000000000000004 
000000c000939c78:  000000c00036b200  000000c000939ea8 
000000c000939c88:  0000000001707887 <cmd/compile/internal/gc.buildssa+4359>  000000c000928000 
000000c000939c98:  000000c0011804b0  0000000000000000 
000000c000939ca8:  0000000000000000  0000000000000001 
000000c000939cb8:  000000c00084c008  0000000000000000 
000000c000939cc8:  0000000000000001  000000c00104da38 
000000c000939cd8:  0000000001de0410  760000000182c200 
000000c000939ce8:  0000002a01000000  0000000000000000 
000000c000939cf8:  0000000000000001  0000000000000001 
000000c000939d08:  0000000000000009 
cmd/compile/internal/ssa.rewriteValueAMD64_OpAMD64MOVLstore(0x0, 0xc0008f4c80)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/ssa/rewriteAMD64.go:12557 +0x60cc fp=0xc000939c10 sp=0xc000939768 pc=0x133cc4c
created by cmd/compile/internal/gc.compileFunctions
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/pgen.go:382 +0x129

goroutine 1 [chan send]:
cmd/compile/internal/gc.compileFunctions()
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/pgen.go:390 +0x186
cmd/compile/internal/gc.Main(0x18c1cf0)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/main.go:768 +0x361a
main.main()
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/main.go:52 +0xb1

goroutine 34 [runnable]:
cmd/compile/internal/ssa.(*Block).NewValue1I(0xc001037350, 0x292300000001e, 0x9ec, 0xc0000bc360, 0x1, 0xc001001180, 0xc001001180)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/ssa/func.go:414 +0xc7
cmd/compile/internal/gc.(*state).newValue1I(...)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:807
cmd/compile/internal/gc.(*state).call(0xc000928120, 0xc0011ee180, 0x1890000, 0x7)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:4727 +0x805
cmd/compile/internal/gc.(*state).callResult(0xc000928120, 0xc0011ee180, 0xc0012b0a00, 0xc0012b0fd8)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:4469 +0x45
cmd/compile/internal/gc.(*state).expr(0xc000928120, 0xc0011ee180, 0x0)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:2745 +0x4fe5
cmd/compile/internal/gc.(*state).stmt(0xc000928120, 0xc0011ee200)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:1271 +0x24f
cmd/compile/internal/gc.(*state).stmtList(0xc000928120, 0xc0011cf278)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:1050 +0x58
cmd/compile/internal/gc.(*state).stmt(0xc000928120, 0xc0011edf00)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:1068 +0x7f
cmd/compile/internal/gc.(*state).stmtList(0xc000928120, 0xc0011cf1e8)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:1050 +0x58
cmd/compile/internal/gc.(*state).stmt(0xc000928120, 0xc0011ee080)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:1072 +0x1631
cmd/compile/internal/gc.(*state).stmtList(0xc000928120, 0xc0011cf2c0)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:1050 +0x58
cmd/compile/internal/gc.(*state).stmt(0xc000928120, 0xc0011ed100)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:1068 +0x7f
cmd/compile/internal/gc.(*state).stmtList(0xc000928120, 0xc0011cf068)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:1050 +0x58
cmd/compile/internal/gc.(*state).stmt(0xc000928120, 0xc000f90500)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:1339 +0x1cae
cmd/compile/internal/gc.(*state).stmtList(0xc000928120, 0xc0011cf1a0)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:1050 +0x58
cmd/compile/internal/gc.buildssa(0xc00072e580, 0x0, 0x0)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:451 +0x1107
cmd/compile/internal/gc.compileSSA(0xc00072e580, 0x0)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/pgen.go:319 +0x5d
cmd/compile/internal/gc.compileFunctions.func2(0xc0008ee720, 0xc000896bf0, 0x0)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/pgen.go:384 +0x4d
created by cmd/compile/internal/gc.compileFunctions
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/pgen.go:382 +0x129

goroutine 36 [runnable]:
cmd/compile/internal/gc.buildssa(0xc00072fce0, 0x2, 0x0)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:355 +0x511
cmd/compile/internal/gc.compileSSA(0xc00072fce0, 0x2)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/pgen.go:319 +0x5d
cmd/compile/internal/gc.compileFunctions.func2(0xc0008ee720, 0xc000896bf0, 0x2)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/pgen.go:384 +0x4d
created by cmd/compile/internal/gc.compileFunctions
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/pgen.go:382 +0x129

goroutine 37 [runnable]:
cmd/compile/internal/ssa.(*Block).NewValue1I(0xc00111f578, 0x1f18000000005, 0xc0000009b4, 0xc0012a3140, 0x10, 0xc0010e91b8, 0xc0008b5200)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/ssa/func.go:414 +0xc7
cmd/compile/internal/gc.(*state).newValue1I(...)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:807
cmd/compile/internal/gc.(*state).addr(0xc0008b5200, 0xc000784f00, 0x0)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:4894 +0x1245
cmd/compile/internal/gc.(*state).stmt(0xc0008b5200, 0xc00122ce00)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:1265 +0x485
cmd/compile/internal/gc.(*state).stmtList(0xc0008b5200, 0xc001230cf0)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:1050 +0x58
cmd/compile/internal/gc.buildssa(0xc0000c0840, 0x3, 0x0)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/ssa.go:451 +0x1107
cmd/compile/internal/gc.compileSSA(0xc0000c0840, 0x3)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/pgen.go:319 +0x5d
cmd/compile/internal/gc.compileFunctions.func2(0xc0008ee720, 0xc000896bf0, 0x3)
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/pgen.go:384 +0x4d
created by cmd/compile/internal/gc.compileFunctions
	/Users/seph/manual-go-build/go-darwin-arm64-bootstrap/src/cmd/compile/internal/gc/pgen.go:382 +0x129
^C

</pre></details>

**Comment by networkimprov** [comment]
cc @cherrymui

**Comment by cherrymui** [comment]
There have been a number of different failure modes with Rosetta 2, see #42700. Until Rosetta 2 gets better, there are probably not much we can do. Closing as a dup.
