### ISSUE TITLE
go/types, types2: better error message for invalid use of constraint interface

### ISSUE THREAD

**Issue by voldyman** [golang/go#42881]
### What version of Go are you using (`go version`)?

<pre>
fmt.Printf("%s\n", runtime.Version())
devel +9daca74ad2 Wed Nov 18 00:18:01 2020 +0000

</pre>

### What operating system and processor architecture are you using (`go env`)?

go2 playground (https://go2goplay.golang.org/)

<details><summary><code>go env</code> Output</summary><br><pre>
fmt.Printf("%s/%s\n", runtime.GOOS, runtime.GOARCH)
linux/amd64

</pre></details>

### What did you do?
 ```
type SortableComparable interface {
	comparable
	GreaterOrEqual(other SortableComparable) bool
}
```

https://go2goplay.golang.org/p/LGpaCLkA31a

### What did you expect to see?
Successful compilation, since it's the same as the following code which compiles

```

type sortable interface {
	GreaterOrEqual(other sortable) bool
}

type SortableComparable interface {
	comparable
	sortable
}
```
https://go2goplay.golang.org/p/f2Lpuv-3JKl

### What did you see instead?

```
type checking failed for main
prog.go2:10:23: interface is (or embeds) comparable
```

**Comment by ianlancetaylor** [comment]
This isn't permitted, because it would require the type to have a method `GreaterOrEqual(other SortableComparable) bool`.  But since `SortableComparable` embeds `comparable`, it may only be used as a type constraint, not as an ordinary type.  So no type can ever have such a method.

But the error message could be better.  CC @griesemer.

**Comment by griesemer** [comment]
As an aside, the two programs you (@voldyman) are comparing are not the same: The first one has a different interface type for the `other` parameter than the second one.

**Comment by voldyman** [comment]
Got it, in that case the error message while trying to create a implementation is also not clear.

https://go2goplay.golang.org/p/-knY7KsfF67

```
type sortable interface {
	GreaterOrEqual(other sortable) bool
}

type SortableComparable interface {
	comparable
	sortable
}

type Num struct {
	num int
}

func (n Num) GreaterOrEqual(s sortable) bool {
	other, ok := s.(Num)
	if !ok {
		return false
	}
	return n.num >= other.num
}

var _ SortableComparable = Num{2}

```
```
type checking failed for main
prog.go2:29:7: interface is (or embeds) comparable
```

-----

related question: Is there a way to express "the type should have methods a & b, and also be allowed in the key of a map " with the current generics proposal?
(https://go2goplay.golang.org/p/MbM5zhGwMS9)

**Comment by griesemer** [comment]
@voldyman Interfaces that contain type lists or embed `comparable` cannot be used as type of a variable (incl. parameter, result, field, etc.); it can only be used as a constraint. But map keys can be interfaces even if they don't embed `comparable` (that's always been the case). Taking your example and [modifying it a bit](https://go2goplay.golang.org/p/w198WKF-022) shows how a `SortableComparable` can be used as a map key; though there is no way to define your own equality function that then would be used for the map. The latter would require a custom (generic) map, but that will be possible with generics.

**Comment by voldyman** [comment]
Thanks for the detailed answer!

(I'll leave this issue open for the compiler error message but feel free to close it if not required)
