### ISSUE TITLE
doc/go1.16: document vet changes for Go 1.16

### ISSUE THREAD

**Issue by dmitshur** [golang/go#42895]
As of filing this issue, the [Go 1.16 draft release notes](https://tip.golang.org/doc/go1.16) contained the following HTML:

```HTML
<h3 id="vet">Vet</h3>

<p>
  TODO

  <!-- CL 235677: https://golang.org/cl/235677: cmd/vet: bring in pass to catch invalid uses of testing.T in goroutines -->
</p>
```

Per [golang.org/s/release](https://golang.org/s/release), it's a release blocker for Go 1.16 Beta 1 to have a complete draft of the eventual release notes, and so the TODO needs to be resolved.

A sequence of steps to resolve this issue may be:

1. Come up with a draft release note entry in this issue, then move the issue to NeedsFix state.
2. Send a CL with "doc/go1.16:" [prefix](https://go-review.googlesource.com/q/project:go+doc/go1.16) and include "For #40700. Fixes #{this issue}." in the body.

**Comment by dmitshur** [comment]
@timothy-king has offered to take this. Thanks!

**Comment by randall77** [comment]
We might also want to mention https://go-review.googlesource.com/c/tools/+/248686 (vet pass to check for invalid frame pointer usage).

**Comment by randall77** [comment]
Actually, that change has not been vendored in from `x/tools` yet. Is that scheduled to happen at some point, or should I do that explicitly?

**Comment by dmitshur** [comment]
@randall77 I'm looking to pull in changes that are in scope for Go 1.16 in [CL 275446](https://golang.org/cl/275446) (which may end up being split into smaller commits, or otherwise changed not to pull everything in). That is to say, it should happen, but it's not guaranteed to. If it's important for it to be included in Go 1.16 beta 1, please file a separate issue for it and CC me on it. You can send a CL that updates just x/tools to resolve it.

**Comment by randall77** [comment]
Ok, I'll open a new issue and prepare some CLs.

**Comment by timothy-king** [comment]
@dmitshur Can you cc me if framepointer is added to the release?

**Comment by dmitshur** [comment]
@timothy-king Please see [CL 276372](https://golang.org/cl/276372) and [CL 276372](https://golang.org/cl/276373) that @randall77 just sent.
