### ISSUE TITLE
doc/go1.16: document encoding/json changes for Go 1.16

### ISSUE THREAD

**Issue by dmitshur** [golang/go#42898]
As of filing this issue, the [Go 1.16 draft release notes](https://tip.golang.org/doc/go1.16) contained the following HTML:

<dl id="encoding/json"><dt><a href="/pkg/encoding/json/">encoding/json</a></dt>
  <dd>
    <p>
      The error message for
      <a href="/pkg/encoding/json/#SyntaxError">SyntaxError</a>
      now begins with "json: ", matching the other errors in the package.
    </p>
    <p>
      <strong>TODO:</strong> <a href="https://golang.org/cl/234818">https://golang.org/cl/234818</a>: allow semicolon in field key / struct tag
    </p>
  </dd>
</dl>

---

Per [golang.org/s/release](https://golang.org/s/release), it's a release blocker for Go 1.16 Beta 1 to have a complete draft of the eventual release notes, and so the TODO needs to be resolved.

A sequence of steps to resolve this issue may be:

1. Come up with a draft release note entry in this issue, then move the issue to NeedsFix state.
2. Send a CL with "doc/go1.16:" [prefix](https://go-review.googlesource.com/q/project:go+doc/go1.16) and include "For #40700. Fixes #{this issue}." in the body.

**Comment by dsnet** [comment]
We'll probably roll back this change. See #42675.
