### ISSUE TITLE
os/exec: calling Command on file with UWP reparse point fails with "file does not exist"

### ISSUE THREAD

**Issue by viveklak** [golang/go#42919]
Windows 10 ships with some 0 length files in `C:\Users\<User>\AppData\Local\Microsoft\WindowsApps` with special [reparse points](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/8ac44452-328c-4d7b-a784-d72afd19bd9f#gt_4fed0b53-5fc8-4818-886f-93d87f3035e1) which when run trigger the windows app store app to be launched. 

Once installed, the same files result in the installed app to be run going forward. For instance, Windows 10 ships with python3.exe which is in fact a link to python3.8 available on the Windows App Store.  `C:\Users\<User>\AppData\Local\Microsoft\WindowsApps` happens to be on the PATH by default so once installed, the python3 interpreter should be invoked. However, when trying to run the same through Go's `exec.Cmd` we get a `file does not exist` error (see below for simple repro).

The main issue seems to be a call to `os.Stat` from the `exec.Cmd` run path. `os.Stat` on windows doesn't pass [`syscall.FILE_FLAG_OPEN_REPARSE_POINT`](https://github.com/golang/go/blob/f5978a09589badb927d3aa96998fc785524cae02/src/os/stat_windows.go#L106) resulting in the error (unlike [Lstat](https://github.com/golang/go/blob/f5978a09589badb927d3aa96998fc785524cae02/src/os/stat_windows.go#L114)).

### What version of Go are you using (`go version`)?

<pre>
$ go version
1.15.5
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Windows 10
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\User\AppData\Local\go-build
set GOENV=C:\Users\User\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\User\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\User\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\User\AppData\Local\Temp\go-build056150306=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

```
$ cat main.go
package main

import (
	"fmt"
	"os"
	"os/exec"
)

func do() error {
	res, err := os.Lstat("C:\\Users\\User\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe")
	if err != nil {
		return err
	}
	fmt.Println("python3 exists!")
	fmt.Printf("%#v\n", res)
	cmd := exec.Command("C:\\Users\\User\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe", "-c", "print('hello')")
	btes, err := cmd.CombinedOutput()
	if err != nil {
		return err
	}
	fmt.Printf("%v\n", btes)
	return nil
}

func main() {
	err := do()
	if err != nil {
		panic(err)
	}
}

PS C:\Users\User> go run main.go
```

### What did you expect to see?
```
python3 exists!
&os.fileStat{name:"python3.exe", FileAttributes:0x420, CreationTime:syscall.Filetime{LowDateTime:0x5094a4bc, HighDateTime:0x1d6a0b0}, LastAccessTime:syscall.Filetime{LowDateTime:0xb3aada47, HighDateTime:0x1d6be0b}, LastWriteTime:syscall.Filetime{LowDateTime:0xb3aada47, HighDateTime:0x1d6be0b}, FileSizeHigh:0x0, FileSizeLow:0x0, Reserved0:0x8000001b, filetype:0x0, Mutex:sync.Mutex{state:0, sema:0x0}, path:"", vol:0x16999dcb, idxhi:0x30000, idxlo:0x14bc9, appendNameToPath:false}
hello
```

### What did you see instead?
```
python3 exists!
&os.fileStat{name:"python3.exe", FileAttributes:0x420, CreationTime:syscall.Filetime{LowDateTime:0x5094a4bc, HighDateTime:0x1d6a0b0}, LastAccessTime:syscall.Filetime{LowDateTime:0xb3aada47, HighDateTime:0x1d6be0b}, LastWriteTime:syscall.Filetime{LowDateTime:0xb3aada47, HighDateTime:0x1d6be0b}, FileSizeHigh:0x0, FileSizeLow:0x0, Reserved0:0x8000001b, filetype:0x0, Mutex:sync.Mutex{state:0, sema:0x0}, path:"", vol:0x16999dcb, idxhi:0x30000, idxlo:0x14bc9, appendNameToPath:false}
panic: exec: "C:\\Users\\User\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe": file does not exist

goroutine 1 [running]:
main.main()
        C:/Users/User/main.go:28 +0x4b
exit status 2
```

**Comment by networkimprov** [comment]
cc @alexbrainman @mattn 

@gopherbot add OS-Windows

**Comment by mattn** [comment]
It caused by that findExecutable uses os.Stat instead of os.Lstat. os.Lstat resolve reparse-points.

```diff
diff --git a/src/os/exec/lp_windows.go b/src/os/exec/lp_windows.go
index 9ea3d76575..12c7e04e63 100644
--- a/src/os/exec/lp_windows.go
+++ b/src/os/exec/lp_windows.go
@@ -15,7 +15,7 @@ import (
 var ErrNotFound = errors.New("executable file not found in %PATH%")
 
 func chkStat(file string) error {
-	d, err := os.Stat(file)
+	d, err := os.Lstat(file)
 	if err != nil {
 		return err
 	}
```
This fixes the issue the program can not execute python.exe, but the python.exe exit with 9009 exit code. Probably, it is another issue.

**Comment by viveklak** [comment]
> This fixes the issue the program can not execute python.exe, but the python.exe exit with 9009 exit code. Probably, it is another issue.

Yes - I alluded to that in the original report but should have called it out in more detail:
> The main issue seems to be a call to os.Stat from the exec.Cmd run path. os.Stat on windows doesn't pass syscall.FILE_FLAG_OPEN_REPARSE_POINT resulting in the error (unlike Lstat).

A naive thought here would be to consider passing `syscall.FILE_FLAG_OPEN_REPARSE_POINT` to `CreateFile` from `os.Stat` similar to what `os.Lstat` does but I am not familiar enough with the semantics of Windows to judge the implications of that change.

As such, I see the following issues:
1. Running os.Stat on reparse point files returns an unexpected/misleading error
2. os.Exec is not able to exec a reparse point file due to the above.

**Comment by sachinjoseph** [comment]
I ran into [this](https://stackoverflow.com/questions/71865309/in-go-why-does-exec-command-fail-but-os-startprocess-succeed-launching-win) the other day; worked around it using `os.StartProcess()` (more details [here](https://stackoverflow.com/q/71865309/1724702)). Golang team, it'd be nice to have this bug fixed as this effectively makes the `os.Exec()` API unreliable and hence unusable on Windows.

**Comment by alexbrainman** [comment]
@sachinjoseph 

Does

https://go-review.googlesource.com/c/go/+/384160

fixes this bug?

If yes, please, help review the CL 384160.

Alternatively send your own fix (if you know how to fix it)

https://go.dev/doc/contribute

Thank you.

Alex

**Comment by sachinjoseph** [comment]
@alexbrainman @JanDeDobbeleer The [PR](https://go-review.googlesource.com/c/go/+/384160) modifies `os.Exec()` to [specially handle](https://go-review.googlesource.com/c/go/+/384160/6/src/os/stat_windows.go#50) files that contain the substring `/AppData/Local/Microsoft/WindowsApps` in its path. I don't think specially handling files that have a certain substring in its path is the right approach.

Changing `os.stat()` to `os.Lstat()` in `chkStat()` (called by `findExecutable()` [here](https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/os/exec/lp_windows.go#L47)) works for executing regular files (say `notepad.exe`) and files with reparse points (say `winget.exe`) - I verified this on my machine and also in a VM. Now I am not an expert in this area, and so I am not sure of any potential implications of this change though. Maybe the actual fix needs to go a level deeper into `os.Stat()` itself like in @JanDeDobbeleer's PR (but without the [special handling](https://go-review.googlesource.com/c/go/+/384160/6/src/os/stat_windows.go#50) for certain paths), because, today, on Windows, `os.Stat()` fails on `winget.exe` but succeeds on `winget.exe`.

**Comment by JanDeDobbeleer** [comment]
@sachinjoseph I agree. I'm looking for a new way to handle this in the correct spot but truth be told, it's a bit of a maze 😃. The problem is that in go lookpath can't resolve this. So it needs to be fixed somewhere over there ideally.

**Comment by JanDeDobbeleer** [comment]
@sachinjoseph decided to add an explicit call to `Readlink` rather than changing existing code around too much. Same result, no explicit locations mentioned, this will also support any other symbolic link.

**Comment by sachinjoseph** [comment]
@JanDeDobbeleer Great! How do I test this? Can I simply clone your fork/branch and build it? Do I need to enable CGO?

Were you able to launch `winget.exe` using `os.Exec()` with your changes?

**Comment by JanDeDobbeleer** [comment]
@sachinjoseph yes, you can simply take that branch and build it, doesn't need cgo. I didn't validate winget but theoretically that should just work.

**Comment by sachinjoseph** [comment]
@JanDeDobbeleer Let me try that

**Comment by sachinjoseph** [comment]
@JanDeDobbeleer I still see issues, although I don't see an error message running `exec.Cmd.Output()` anymore. 

### Test.go
```golang
package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

func main() {
	path := filepath.Join(os.Getenv("LOCALAPPDATA"), "Microsoft\\WindowsApps\\winget.exe")
	// path = "C:\\Program Files\\Git\\cmd\\git.exe"

	cmd := exec.Command(path, "--version")
	output, err := cmd.Output()
	fmt.Println(string(output))
	fmt.Println(err)

	fmt.Println("\nStat-ing the file")

	f, err := os.Stat(path)
	fmt.Println(f)
	fmt.Println(err)
}
```

### Go 1.18
```powershell
pwsh> go version        
go version go1.18 windows/amd64

pwsh> go run test.go    

exec: "C:\\Users\\username\\AppData\\Local\\Microsoft\\WindowsApps\\winget.exe": file does not exist

Stat-ing the file
<nil>
CreateFile C:\Users\username\AppData\Local\Microsoft\WindowsApps\winget.exe: The file cannot be accessed by the system.

pwsh> 
```

### @JanDeDobbeleer's [branch](https://github.com/JanDeDobbeleer/go/tree/symbolic-app-store-links)

```bash
pwsh> .\go.exe version
go version devel go1.19-aaf7044240 Tue Apr 19 21:19:47 2022 +0200 windows/amd64

pwsh> .\go.exe run test.go
v1.3.692-preview
<nil>

Stat-ing the file
<nil>
CreateFile C:\Users\username\AppData\Local\Microsoft\WindowsApps\winget.exe: The file cannot be accessed by the system.

pwsh>

```

**Comment by JanDeDobbeleer** [comment]
@sachinjoseph yes, stat doesn't resolve symlinks so I didn't touch it.

**Comment by alexbrainman** [comment]
@qmuntal can you, please, see if

https://go-review.googlesource.com/c/go/+/452375

looks reasonable to you?

Rob approved my CL, but I would not trust myself with that change. The CL uses some undocumented logic that @JanDeDobbeleer discovered. It appears to work on my Windows 10.

This is not urgent since we have to wait for Go source tree to open for Go 1.21 development anyway.

Thank you.

Alex

**Comment by alexbrainman** [comment]
@qmuntal re https://github.com/golang/go/issues/42919#issuecomment-1327888278

Please, review @JanDeDobbeleer https://go-review.googlesource.com/c/go/+/384160 instead.

He copied all changes from my https://go-review.googlesource.com/c/go/+/452375 and I abandoned my CL.

Thank you.

Alex

**Comment by qmuntal** [comment]
Sure!
