### ISSUE TITLE
x/build: use AWS EC2 Mac instances for macos builders

### ISSUE THREAD

**Issue by smasher164** [golang/go#42918]
For context: https://aws.amazon.com/blogs/aws/new-use-mac-instances-to-build-test-macos-ios-ipados-tvos-and-watchos-apps/

> The instances feature an 8th generation, 6-core Intel Core i7 (Coffee Lake) processor running at 3.2 GHz, with Turbo Boost up to 4.6 GHz.

> EC2 Mac instances with the Apple M1 chip are already in the works, and planned for 2021.

Related: #40762, #26530, #39782.

**Comment by martisch** [comment]
Can you clarify why those are better then the current mac builders?

**Comment by smasher164** [comment]
Actually, I failed to read this part of the announcement:

> The instances are launched as EC2 Dedicated Hosts with a minimum tenancy of 24 hours.

This doesn't work with the way we do our builds, so I'll go ahead and close this.
