### ISSUE TITLE
x/pkgsite: GetLatestMajorVersion in proxydatasource does not support incompatible modules

### ISSUE THREAD

**Issue by catzkorn** [golang/go#42922]
### What version of Go are you using (`go version`)?

<pre>
go1.15.5

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/charlotte/Library/Caches/go-build"
GOENV="/Users/charlotte/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/charlotte/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/charlotte/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/charlotte/src/pkgsite/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

</pre></details>

### What did you do?

I started the frontend locally with the direct proxy flag set.

```
$ go run ./cmd/frontend -direct_proxy
```

Navigated to http://localhost:8080/github.com/golang-migrate/migrate/v3@v3.5.2

### What did you expect to see?

I expected to see a warning that there was a greater version available as it does on the [pkg.go.dev](https://pkg.go.dev/github.com/golang-migrate/migrate/v3@v3.5.2).
<img width="1098" alt="Screenshot 2020-12-01 at 12 10 49" src="https://user-images.githubusercontent.com/46385858/100738971-53f86780-33ce-11eb-8a76-9ed51f0348d4.png">

### What did you see instead?

I saw no banner.
<img width="1085" alt="Screenshot 2020-12-01 at 12 10 07" src="https://user-images.githubusercontent.com/46385858/100738886-31664e80-33ce-11eb-8d26-1587fecbce3f.png">

### Discussion

I found this issue while working on and testing #42292. The problem appears to be that [GetLatestMajorVersion](https://github.com/golang/pkgsite/blob/d8d1bb1648ed5654e2adf063a7db1050ac03c1b2/internal/proxydatasource/datasource.go#L176) in the proxydatasource assumes that the first suffixed module uses a v2 suffix. In the case of golang migrate, the first suffixed module appears to be /v3 given that both v1 and v2 are on a non suffixed module. 

I would assume we could fix this by parsing the version returned from the first GetInfo call and using that as a basis for subsequent suffixed module names.

**Comment by sudo-sturbia** [comment]
@julieqiu I would like to claim this, if it's no problem.

**Comment by julieqiu** [comment]
Please do!
