### ISSUE TITLE
x/pkgsite: error starting frontend locally

### ISSUE THREAD

**Issue by Catzkorn** [golang/go#42921]
### What version of Go are you using (`go version`)?

<pre>
go1.15.5

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/charlotte/Library/Caches/go-build"
GOENV="/Users/charlotte/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/charlotte/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/charlotte/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/charlotte/src/pkgsite/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9g/lm8bfm3170d5zbpfxk68hgl80000gn/T/go-build274431613=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```
$ go run ./cmd/frontend              
```

### What did you expect to see?

I expected the server to start.

### What did you see instead?
```
2020/12/01 11:03:49 Critical: config.Init(ctx): secrets.Get(ctx, "quota-hmac-key"): need GOOGLE_CLOUD_PROJECT environment variable
exit status 1
```
This was introduced in https://github.com/golang/pkgsite/commit/3f9e3bf1395eb02e62659bece07415f713f6396b and breaks any exisiting local workflows.

This can be resolved by setting env var `GO_DISCOVERY_DISABLE_QUOTA` to `TRUE` but is not documented in the documentation. 

I intend to fix this issue by submitting a documentation update.

**Comment by julieqiu** [comment]
Fixed in https://go-review.googlesource.com/c/pkgsite/+/274232.
