### ISSUE TITLE
cmd/go2go: go2go translator issue with implicitly instantiated generic function

### ISSUE THREAD

**Issue by benjaminjkraft** [golang/go#42920]
Consider the following code:
```go
package main

func Map[T, U any](f func(T) (U, error), xs []T) ([]U, error) { return nil, nil }

func Apply(s string) func(func(string) (string, error)) (string, error) {
	return func(f func(string) (string, error)) (string, error) {
		return f(s)
	}
}

func main() {
	var input string
	var fs [](func(string) (string, error))
	Map[func(string) (string, error), string](Apply(input), fs) // works
	Map(Apply(input), fs)                                       // works, fails if previous line is removed
}
```
If we write out the types for `Map(Apply(input), fs)` everything works.  If we write them out on the first line, and then omit them on the second, it works.  But if we just omit them, the compiler returns errors (below) from the translated code; it seems to somehow be inferring `func(string) string` instead of `func(string) (string, error)` or something.

Sample errors:
```
./prog.go2:13: cannot use Apply(input) (type func(func(string) (string, error)) (string, error)) as type func(func(string) string) (string, error) in argument to instantiate୦୦Map୦func୮8string୮9୮0୮8string୮3୮0error୮9୦string
./prog.go2:13: cannot use fs (type []func(string) (string, error)) as type []func(string) string in argument to instantiate୦୦Map୦func୮8string୮9୮0୮8string୮3୮0error୮9୦string
```

Playground link: https://go2goplay.golang.org/p/J-5HQfAPIwM

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by griesemer** [comment]
This type-checks and even compiles fine with one or both Map function invocations (e.g., `go tool compile -G=3 main.go`); it is not a bug with type inference.

This looks like a bug in go2go (the source-to-source translator). Not clear that we want to spend time on fixing this as the real (compiler) implementation is coming along and eventually will supersede the translator. Leaving for @ianlancetaylor to decide if he wants to look into this.

**Comment by ianlancetaylor** [comment]
Oh, yes, sorry, this is a go2go bug.  We aren't going to be fixing bugs in go2go at this point.  If someone else wants to look into it, that would be fine.

**Comment by ianlancetaylor** [comment]
go2go is obsolete.
