### ISSUE TITLE
x/review/git-codereview: test timed out on windows-arm-zx2c4 builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#42925]
[2020-09-11T20:38:40-0edcede/windows-arm-zx2c4](https://build.golang.org/log/58a8dd9300dc4313d7f829aa0b794177a94a948f)

Not obvious to me whether the builder is just slow or the test triggered some kind of deadlock.

CC @zx2c4 @golang/release

**Comment by zx2c4** [comment]
It might just be slow. If this test is doing a lot of disk IO, that can really slow things down.

**Comment by bcmills** [comment]
It's testing the `git-codereview` Git hooks, so it probably does a moderate amount of I/O.

That said, I can't seem to run the test locally to get a baseline for how long it should take (#42926).

**Comment by zx2c4** [comment]
If it's doing a lot of git operations, this hits a triple whammy of slow: NTFS small file performance is pretty bad, the I/O on this box is pretty slow, and git itself is compiled only for x86 not arm, so it runs in Windows' rosetta2 situation.

**Comment by bcmills** [comment]
In that case, would it make sense to configure the builder to skip the `x/review` repo, or perhaps to use a larger timeout scale factor?

**Comment by zx2c4** [comment]
I think that's at least worth a try, yes. For starters, the timeout scale factor. I'm not quite sure how to go about doing that in the x/build repo, if you want to take a stab at it. Alternatively, if there's some env var I should set on the builder, I can do that.

**Comment by dmitshur** [comment]
The `GO_TEST_TIMEOUT_SCALE` variable can be used to scale timeout, but it applies to the entire builder, not a specific repository. It's defined [here](https://github.com/golang/go/blob/dd4a52c2a588c57edc76cb0a414ae6f2e5bf5d52/src/cmd/dist/test.go#L156-L161), and there are many examples of it used in [dashboard/builders.go](https://github.com/golang/build/blob/4ab6ffe488ae343ee9ea49d95ffa3837a5427073/dashboard/builders.go).

**Comment by zx2c4** [comment]
Will send a CL.

**Comment by bcmills** [comment]
This builder no longer exists, so the issue is obsolete.
(We may need to revisit this when a new `windows-arm` builder is added; see #47019.)
