### ISSUE TITLE
cmd/go: 'go build -n' is sometimes non-runnable due to indented EOF

### ISSUE THREAD

**Issue by sigxcpu76** [golang/go#42931]
### What version of Go are you using (`go version`)?

<pre>
go version go1.15.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE=""
GOENV=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH=""
GOPRIVATE=""
GOPROXY=""
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/sigxcpu/tmp/lock_analyzer/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build820090170=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

`go build -n`

### What did you expect to see?

A runnable script of all the executed commands that will be done by `go build`

### What did you see instead?

A non-runnable script because one of the `EOF`s is indented by a TAB.

This is the wrong output from a `go build -n`:

```
#go build -n        

...

mkdir -p $WORK/b001/
cat >$WORK/b001/_gomod_.go << 'EOF' # internal
package main
import _ "unsafe"
//go:linkname __debug_modinfo__ runtime.modinfo
var __debug_modinfo__ = "0w\xaf\f\x92t\b\x02A\xe1\xc1\a\xe6\xd6\x18\xe6path\ta.b/lock_analyzer\nmod\ta.b/lock_analyzer\t(devel)\t\n\xf92C1\x86\x18 r\x00\x82B\x10A\x16\xd8\xf2"
	EOF
cat >$WORK/b001/importcfg << 'EOF' # internal
...
```

**Comment by bcmills** [comment]
With what source code did you observe this issue?

Can you modify the existing test in `$GOROOT/src/cmd/go/testdata/script/build_dash_x.txt` such that it reproduces the problem?

**Comment by sigxcpu76** [comment]
Well, it looks that it was fixed here 
https://github.com/golang/go/commit/5abba0c73723a843315c0f7ed014617445af6243#diff-02850bc8beaa613f53f7b7ac9667d6c1e02f924aa0aa2cd9e8c56816673fb695

Btw, the title change is misleading because the indented EOF  meant that it was *always* unrunnable.

**Comment by bcmills** [comment]
> Btw, the title change is misleading because the indented EOF meant that it was always unrunnable.

It was at the very least runnable in `GOPATH` mode. (That is the condition that the `build_dash_x` test covered prior to [CL 255052](https://golang.org/cl/255052).)
