### ISSUE TITLE
all: cleanup ineffectual //go:linkname directives

### ISSUE THREAD

**Issue by mdempsky** [golang/go#42938]
There are a lot of //go:linkname directives in macOS packages that don't do anything. We should remove them.

To elaborate, a directive like `//go:linkname foo bar` sets the Go variable or function named `foo` to use `bar` as its linker symbol (instead of `mypkgpath.foo`, like it would normally use). But if there's no Go variable or function named `foo`, it just silently doesn't do anything.

In CL 273986 (2d6ff998edc0f3877ee24d28647a494491742f25), I removed the occurrences within the standard library, but there are more in the vendored x/sys package that need to be fixed. There might be more instances in other repos too.

To test for problems, you can checkout the `dev.regabi` branch; revert CL 274732 (42e46f4ae0c4f3d6bf7f3920fa936f056ea485c4); and then build packages like golang.org/x/sys/unix w/ various GOOS/GOARCH combinations.

**Comment by ianlancetaylor** [comment]
Is there more to do here?  Are we going to do anything further for the 1.17 release?

**Comment by dmitshur** [comment]
We're three weeks into the release freeze now. It seems this is either mostly done, or if there's more to do, progress can be continued in a future Go release, so I'll move it to Backlog. @mdempsky Please feel free to update the issue as needed.

**Comment by cuonglm** [comment]
@mdempsky seems we can close this issue now?

**Comment by Ebi-web** [comment]
ping
