### ISSUE TITLE
cmd/go: count flag has no effect on Examples

### ISSUE THREAD

**Issue by cherrymui** [golang/go#42936]
### What version of Go are you using (`go version`)?

tip (73e796cb007989449da95fb4adf936ee76b766ca)

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

darwin/amd64

### What did you do?

Running Example with -count flag.
```
$ go test -run=TestSprintf -count=2 -v fmt
=== RUN   TestSprintf
--- PASS: TestSprintf (0.00s)
=== RUN   TestSprintf
--- PASS: TestSprintf (0.00s)
PASS
ok  	fmt	0.063s
$ go test -run=ExampleSprintf -count=2 -v fmt
=== RUN   ExampleSprintf
--- PASS: ExampleSprintf (0.00s)
PASS
ok  	fmt	0.065s
```

### What did you expect to see?

Example runs N times with -count=N, same as running Tests.

### What did you see instead?

Example runs only once.

Sorry if this has discussed before or if a decision has been made.

**Comment by cagedmantis** [comment]
The test command flag description states that [examples are always run once](https://go.googlesource.com/go/+/refs/heads/master/src/cmd/go/internal/test/test.go#211).  The maintainers should be able to discuss this further.

**Comment by cherrymui** [comment]
Thanks. If this is intended, it is fine. We can close this.
