### ISSUE TITLE
x/pkgsite: remove tigerwill90/scenario-go-sdk on pkg.go.dev

### ISSUE THREAD

**Issue by tigerwill90** [golang/go#42945]
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/tigerwill90/scenario-go-sdk and all subfolder
 
### What is your user agent?
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36 

 
 
 
### Screenshot
![image](https://user-images.githubusercontent.com/26261762/100892684-e37b4480-34ba-11eb-9840-4855fc238f4e.png)

 
 
 
### What did you do?

I published this module too early, there are plenty of breaking changes coming up and I would like to republish the module under 0.x unstable version. 
 
### What did you expect to see?
![image](https://user-images.githubusercontent.com/26261762/100893324-8af87700-34bb-11eb-8ad5-963032e0041e.png)
Complete remove of the scenario-go-sdk module on pkg.go.dev

**Comment by julieqiu** [comment]
Done.

**Comment by tigerwill90** [comment]
@julieqiu thank's for your help. In reference to https://github.com/golang/go/issues/37938#issuecomment-601345213, I can not use the same path to republish the module later, right ?

**Comment by julieqiu** [comment]
Yup, that is correct.
