### ISSUE TITLE
access: approver access to oauth2

### ISSUE THREAD

**Issue by shinfan** [golang/go#42947]
See https://golang.org/wiki/GerritAccess

**Comment by shinfan** [comment]
I am the latest owner of go/oauth2 library so I would like to have the +2 approval access to the repository for reviewing and merging responsibilities. Thanks.

**Comment by shinfan** [comment]
Friendly ping

**Comment by cagedmantis** [comment]
Please list your Gerrit email address in the issue.

**Comment by shinfan** [comment]
My gerrit email: shinfan@google.com

Thanks for your help!

**Comment by cagedmantis** [comment]
Hi Shin,

Thank you for contributing to the Go project and helping out with oath2! I've discussed this request with the team (/cc @golang/release ), and we agreed to grant you access. I've added you to the may-start-trybots and approvers groups now.

Please be familiar with the rules for voting and submitting changes as described at https://golang.org/wiki/GerritAccess#approver-access-approvers. If you're unsure or have any questions, please don't hesitate to ask us.

Additionally, as described at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a trybot run.

Thank you again for contributing, your help is greatly appreciated!
