### ISSUE TITLE
ObjFile on stripped binaries

### ISSUE THREAD

**Issue by stevemk14ebr** [golang/go#42954]
On GO binaries with stripped .symtab sections the objfile tool fails to located the pclntab and fails to print embedded symbols. The table can still be found however by byte scanning the .text section of the binary for the header magic for the table: https://github.com/golang/go/blob/89f687d6dbc11613f715d1644b4983905293dd33/src/debug/gosym/pclntab.go#L169-L170

The gosym NewTable method does not require the .symtab section to correctly parse the pclntab table and is still useful for this case of stripped binaries. It may simply be passed an empty byte array as it's first argument:
https://github.com/golang/go/blob/2d0258d49568d4b34f5c4dec53985bb80bf370cc/src/cmd/internal/objfile/objfile.go#L152

I propose that a simple byte scan be added in objfile.go if the .pcln() method fails to locate the table by the standard symbols lookup. By falling back to byte scanning the tool can still print much useful information.

**Comment by cherrymui** [comment]
Could you clarify what the problem is?

> the objfile tool fails to located the pclntab and fails to print embedded symbols.

What is "the objfile tool"? `go tool objdump`? And waht is "embedded symbols"?

> go/src/cmd/internal/objfile/objfile.go
> return gosym.NewTable(symtab, gosym.NewLineTable(pclntab, textStart)) 

That `symtab` is the `.gosymtab` section, instead of `.symtab` section. How do you strip the binary so it has strips that section? Also, that section is actually anyway in recent versions of Go.

Could you clarify what program/command you run that you see unexpected result? Thanks.

**Comment by stevemk14ebr** [comment]
Sure, sorry my wording wasn't exact. The issue is this:
```
go tool objdump ./mtisfun_win_stripped
objdump: disassemble ./fmtisfun_win_stripped: no runtime.pclntab symbol found
```

The binary in question has its .symtab section zeroed out:
![image](https://user-images.githubusercontent.com/6619205/101041152-5384db80-354a-11eb-8a75-86d080902a88.png)

The reason this matters is because internally the objfile package attempts to resolve the pclntab by using this .symtab section:
https://github.com/golang/go/blob/2d0258d49568d4b34f5c4dec53985bb80bf370cc/src/cmd/internal/objfile/objfile.go#L148

which calls (for PE's) https://github.com/golang/go/blob/2d0258d49568d4b34f5c4dec53985bb80bf370cc/src/cmd/internal/objfile/pe.go#L111-L119

That symbol resolution fails, and therefore no golang symbols are parsed and the objdump tool faults. This is a poor failure case though as the pclntab section is (usually) still there! It can be located by performing a bytescan over the .text section for the magic pclntab magic.

**Comment by stevemk14ebr** [comment]
The patch is fairly simple, in obfile.go PCLineTable:
```
	textStart, symtab, pclntab, err := e.raw.pcln()
	if err != nil {
		textStart, textData, err := e.raw.text()
		// little endian go12magic
		pclntab_idx := bytes.Index(textData, []byte("\xFB\xFF\xFF\xFF\x00\x00"))
		if pclntab_idx == -1 {
			// big endian go12magic
			pclntab_idx = bytes.Index(textData, []byte("\xFF\xFF\xFF\xFB\x00\x00"))
			if pclntab_idx == -1 {
				// little endian go116magic
				pclntab_idx = bytes.Index(textData, []byte("\xFA\xFF\xFF\xFF\x00\x00"))
				if pclntab_idx == -1 {
					// big endian go116magic
					pclntab_idx = bytes.Index(textData, []byte("\xFF\xFF\xFF\xFA\x00\x00"))
					if pclntab_idx == -1 {
						return nil, err
					}
				}
			}
		}

		// The symbol table of the PE is stripped, but we still have the pclntab!
		fmt.Printf("found pclntab via signature! %X", textStart+uint64(pclntab_idx))

                // we don't know the epclntab but that's fine, the parser won't read extra!
		return gosym.NewTable([]byte{}, gosym.NewLineTable(textData[pclntab_idx:], textStart))
	}
```

**Comment by randall77** [comment]
How exactly was your symbol table stripped? Can you show us the *exact* commands you used starting with building your binary?
What platform are you on?

I'm not a fan of finding sections by looking for magic numbers. Magic numbers are useful if you know where they are and are just verifying them (e.g. at the start of file), but looking for them among a large corpus has a serious false positive problem. For example, the instruction sequence:
```
	movq	0xfbffffff(%rcx), %rcx
	addb	%al, (%rax)
```
Has one of your magic sequences in it.

**Comment by stevemk14ebr** [comment]
I work in security and often deal with malicious samples that are stripped by bad actors, this isn't a process i do. However you can generate a binary without symbols via: ```go build -ldflags="-s -w" <files>```. I agree that searching for magic bytes is not ideal, of course there are false positives. This particular magic isn't exactly the greatest, i would argue it needs more entropy and should probably be a little longer, but it's possible to deal with false positives like this as the parser will simply fail and we can try all candidates until one works. It's also know that this section is within the .text section which avoid a whole host of problems with data colliding.

**Comment by randall77** [comment]
> What platform are you on?

Still need an answer to this.

> However you can generate a binary without symbols via: go build -ldflags="-s -w" <files>

Works fine for me (darwin/amd64, go1.13.6):
```
$ go build -ldflags="-s -w" hello.go
$ go tool objdump hello
... lots of disassembly ...
```

Why use `go tool objdump` instead of binutil's `objdump` for this? If it was generated by a malicious actor, how do you even know the stripped binary is a Go binary?

**Comment by cherrymui** [comment]
On ELF, we look for ".gosymtab" _section_ (NOT ".symtab"), instead of "runtime.symtab" symbol. Can we do the same for PE?

I also don't think that looking for magic numbers are the right answer here.

**Comment by stevemk14ebr** [comment]
@randall77 I am on windows/linux but it's kind of irrelevant here as the symbol table (.gosymtab, .symtab, whatever) can be stripped and the pclntab still be present. This issue highlights that the symbol table (.gosymtab, .symtab, whatever) is used to _locate_ the .pclntab section which _can_ fail. This failure to locate the pclntab doesn't mean it isn't there however, and we can find it to still make objdump useful.

```
Why use go tool objdump instead of binutil's objdump for this
```
I specifically care about getting the pclntab metadata here as it gives function names and start/stop boundaries. 

```
how do you even know the stripped binary is a Go binary
```
as a reverse engineer it is incredibly easily to tell by just looking at the assembly patterns in IDA PRO

there's at least two unhandled failure cases:

1) When the symbol table itself is fully missing, ex: entire .gosymtab (ELF) or .symtab (PE) is just straight up missing
2) When the symbol table is there, but zero/malformed and the symbols cannot be located within these tables. You will get different errors for both of these cases

Now, the symbol table being corrupt/stomped _doesn't matter_ as the pclntab is independent of that.

**Comment by cherrymui** [comment]
Please don't confuse ".gosymtab" and ".symtab". They are always two different sections, on any platform (PE/ELF/Mach-O/etc.). What strip tool do you use? I don't think it should strip ".gosymtab" section on any platform. (However, the section should be empty anyway.)

"runtime.symtab" is a _symbol_, which should be at the beginning of the ".gosymtab" _section_. Please be careful with the names. Thanks.

**Comment by randall77** [comment]
> @randall77 I am on windows/linux but it's kind of irrelevant here

It's very relevant. Now that I know "windows", I can reproduce:

```
$ GOOS=windows go build -ldflags="-s -w" hello.go
$ go tool objdump hello.exe
objdump: disassemble hello.exe: no runtime.pclntab symbol found
```

**Comment by stevemk14ebr** [comment]
@cherrymui I am simply using the linker flags i specified earlier. I am sorry if I am not using the correct terms, I am referring to .gosymtab as a section for linux elf, and .symtab as a section for PE. These are what i refer to as the symbol tab as it seems GO uses them to store symbols inside of (such as to locate runtime.pclntab)
![image](https://user-images.githubusercontent.com/6619205/101066509-83d97380-3564-11eb-9217-51b74f463344.png)

@randall77 same happens for linux.

**Comment by randall77** [comment]
I don't think I understand the motivation for fixing this at all. For the Go project generally, that is.
A user tried to remove symbolic information from their binary. We should respect that wish and not intentionally resurrect that symbolic information despite their wishes.

The fact that they are a malicious user is unfortunate, but not IMO enough motivation to have our general-purpose tools sidestep someone's attempt to remove symbolic information.
Besides, this is an arms race. As soon as we implement this, the obfuscator will notice and just zero out more stuff. I don't think we want to go down that road. Consider yourself lucky that our tools don't show that symbolic information by default but it is still hidden in there somewhere for you.

**Comment by randall77** [comment]
(It might be better to have `go tool objdump` dump the whole text section as one big assembly function instead of erroring out, though.)

**Comment by cherrymui** [comment]
>  I am referring to .gosymtab as a section for linux elf, and .symtab as a section for PE

They should not be the same section. They should serve completely different purpose. If they are, it seems a bug in the linker.

> to locate runtime.pclntab

What I'm proposing is that we should not try to locate runtime.pclntab at all. We should put the pclntab in a separate _section_ and locate that section instead, which we do for ELF and Mach-O.

**Comment by cherrymui** [comment]
> (It might be better to have go tool objdump dump the whole text section as one big assembly function instead of erroring out, though.)

Agreed. This seems what the system `objdump` does, at least on some platforms.

**Comment by stevemk14ebr** [comment]
@randall77 fair enough, i think any tool should try as hard as possible before it fails, but that's not a philosophical direction i control. There's a real bug in the linux case though i think as the .gosymtab section being present or not is irrelevant (and it errors early)

The windows case is a bit trickier, @cherrymui your suggestion of going to a section based discovery vs a symbol based discovery I like personally. It avoids this co-dependancy of symbols <-> pcnltab and also bring the windows file format inline with what linux and macho do

**Comment by stevemk14ebr** [comment]
Closing as it's been shown there's no interest in resolving this. Hopefully this serves as documentation to some future person though. ✌️
