### ISSUE TITLE
"Go test -v" running for all tests's result(pass) is different form when I'm running individual test(fail) 

### ISSUE THREAD

**Issue by koseoyoung** [golang/go#42966]
### What version of Go are you using (`go version`)?

<pre>
$ go version 
go1.15.2 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/seoyoungko/Library/Caches/go-build"
GOENV="/Users/seoyoungko/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/seoyoungko/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/seoyoungko/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/seoyoungko/go/src/github.com/iotexproject/iotex-core/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5m/w57_zf0n76s7sy15dpnm9tx00000gn/T/go-build664261744=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

When I run all tests together by "go test -v" cmd, it pass for TestProtocol_ClaimReward test.
However, when I tried to run individual test by "go test -run TestProtocol_ClaimReward" cmd, it failed.

Is it possible to happen? 
![스크린샷 2020-12-03 오후 5 29 55](https://user-images.githubusercontent.com/31757627/100983800-2c9bc900-358d-11eb-9d2e-1613c196b898.png)

![스크린샷 2020-12-03 오후 5 30 24](https://user-images.githubusercontent.com/31757627/100983859-3de4d580-358d-11eb-8219-02edcb837499.png)

### What did you expect to see?

Same result. 

### What did you see instead?

Different result

**Comment by mvdan** [comment]
Did you raise an issue on that project? It's entirely possible to write a test that fails when `testing.Verbose` is set, for example.

Also, if you still think this is a bug in Go, please provide clear steps to reproduce, including a git clone.
