### ISSUE TITLE
x/website: linux/riscv64 is missing from valid combinations list

### ISSUE THREAD

**Issue by jfcg** [golang/go#42978]
Doc site misses `linux,riscv64` combo under `GOOS,GOARCH` [combo list](https://golang.org/doc/install/source#environment).
However go `1.15.5` can build with this combo and riscv64 is listed as a supported instruction set in [introduction](https://golang.org/doc/install/source#introduction).

**Comment by ALTree** [comment]
Looks like the doc page in the main repo was updated here: https://go-review.googlesource.com/c/go/+/250997

By no corresponding CL was sent to the website repository: 
https://github.com/golang/website/blob/c8f27351e764fa8954631d243dd24779108bd026/content/static/doc/install-source.html#L530
