### ISSUE TITLE
Add C++ STL-like algorithms as built in internal standard library for Go 2.0

### ISSUE THREAD

**Issue by kokizzu** [golang/go#42972]
lately I've been using golang a lot for competitive programming, sometimes uses ruby (because of their awesome built-in [combinatorial](https://apidock.com/ruby/Array/combination)/[permutation](https://apidock.com/ruby/Array/permutation)/[prime](https://apidock.com/ruby/Prime)/automatic-bignumber library). It would be nice if I could fully ditch C++ (especially the lower_bound/upper_bound/[next_permutation](https://play.golang.org/p/ljft9xhOEn) function) by having Go implement those functions inside standard library as go 2.0 released, something like this:

```
// same as C++ STL's lower_bound, upper_bound
pos := slice.LowerBound(arr interface{},cmpFunc func(a,b int)int) // cmpFunc returns -1, 0 or +1
pos := slice.UpperBound(arr interface{},cmpFunc func(a,b int)int)

// similar to lower_bound, upper_bound but return nearest value from sorted slice, eg.
// for example: [1,4,5,6,10] 
// when finding 3 NearestLowerBound = 0 (value=1) NearestUpperBound = 1 (value=4)
// when finding 9 NearestLowerBound = 4 (value=6) NearestUpperBound = 5 (value=10)
pos := slice.NearestLowerBound(arr interface{},cmpFunc func(a,b int)int)
pos := slice.NearestUpperBound(arr interface{},cmpFunc func(a,b int)int)

// same as C++ STL's next_permutation
haveNext := slice.NextPermutation(arr sort.Interface) 
```

this surely will increase Go's adoption and attract more competitive programmers.
Why as Go 2.0, because some of the competitive programming/online judges still using old version of Go, so when they decided to upgrade to Go 2.0, batteries already included:
- [HackerRank](https://www.hackerrank.com/environment) (1.13 2020-10-03)
- [LeetCode](https://support.leetcode.com/hc/en-us/articles/360011833974-What-are-the-environments-for-the-programming-languages-) (1.13 2020-10-03)
- [CodeForces](https://codeforces.com/blog/entry/79?#comment-392726) (1.8? 2017-10-28)
- [Google CodeJam](https://codingcompetitions.withgoogle.com/codejam/faq) (1.7.4 2020-10-03)
- [CodeChef](https://www.codechef.com/wiki/list-compilers) (1.7.4 2020-10-03)
- [Timus](https://acm.timus.ru/help.aspx?topic=go) (1.14.6 x64 2020-09-02)

**Comment by ianlancetaylor** [comment]
Currently we are hoping to add some form of generics to Go, in which case people will be able to write these functions themselves.  For the current design draft, see https://go.googlesource.com/proposal/+/refs/heads/master/design/go2draft-type-parameters.md.  I'm going to close this issue in favor of adding generics.  We can revisit if generics wind up not being adopted.

**Comment by randall77** [comment]
Have you looked at `sort.Search`? Why does that not work for you for your Nearest* functions?

**Comment by kokizzu** [comment]
> Have you looked at `sort.Search`? Why does that not work for you for your Nearest* functions?

Whoa nice, never knew this function before, thanks a lot
https://golang.org/pkg/sort/#Search
