### ISSUE TITLE
doc/go1.16: document changes to the language for Go 1.16

### ISSUE THREAD

**Issue by dmitshur** [golang/go#42976]
As of filing this issue, the [Go 1.16 draft release notes](https://tip.golang.org/doc/go1.16) contained the following HTML:

```HTML
<h2 id="language">Changes to the language</h2>

<p>
  TODO
</p>
```

---

Per [golang.org/s/release](https://golang.org/s/release), it's a release blocker for Go 1.16 Beta 1 to have a complete draft of the eventual release notes, and so the TODO needs to be resolved.

@griesemer Will it be "There are no changes to the language.", or are there changes in Go 1.16?

**Comment by griesemer** [comment]
I do not recall any language changes for 1.16.

**Comment by dmitshur** [comment]
Thanks. Then this issue is easy to resolve. :)
