### ISSUE TITLE
cmd/compile: refactor generic visitor code

### ISSUE THREAD

**Issue by mdempsky** [golang/go#42981]
There's a bunch of implementations of ad hoc, generic IR tree walking code within the compiler frontend.

<details>
<summary>Examples:</summary>

https://github.com/golang/go/blob/351bc2f38c4291c01299c2add16f1f5a96e54bb4/src/cmd/compile/internal/gc/alg.go#L789-L814

https://github.com/golang/go/blob/351bc2f38c4291c01299c2add16f1f5a96e54bb4/src/cmd/compile/internal/gc/const.go#L810-L818

https://github.com/golang/go/blob/351bc2f38c4291c01299c2add16f1f5a96e54bb4/src/cmd/compile/internal/gc/inl.go#L445-L447

https://github.com/golang/go/blob/351bc2f38c4291c01299c2add16f1f5a96e54bb4/src/cmd/compile/internal/gc/inl.go#L490-L503

https://github.com/golang/go/blob/351bc2f38c4291c01299c2add16f1f5a96e54bb4/src/cmd/compile/internal/gc/inl.go#L828-L845

https://github.com/golang/go/blob/351bc2f38c4291c01299c2add16f1f5a96e54bb4/src/cmd/compile/internal/gc/typecheck.go#L3700-L3705
</details>

It should be possible to rewrite a lot of this code to use `ir.Inspect` or `ir.InspectList` instead. This will eventually be helpful for getting rid of the generic Left/Right/etc methods.

For the markbreak case (and maybe others), it might be useful to provide ir analogs to [`ast.Walk`](https://golang.org/pkg/go/ast/#Walk) and [`ast.Visitor`](https://golang.org/pkg/go/ast/#Visitor). (See also [how ast.Inspect is implemented](https://golang.org/src/go/ast/walk.go?s=6291:6333#L374), as that API was inspirational for ir.Inspect.)

/cc @cuonglm

**Comment by rsc** [comment]
I have been working on this the last couple days. Please don't start.

**Comment by rsc** [comment]
https://go-review.googlesource.com/c/go/+/275311 is the CL introducing the API. See the rest of the stack for uses.
Best to discuss on the CLs themselves - I get too much GitHub spam to keep up with the issue tracker.

**Comment by mdempsky** [comment]
Russ's CLs have landed. This is done now.
