### ISSUE TITLE
`path.IsAbs()` wrong in Windows

### ISSUE THREAD

**Issue by axetroy** [golang/go#42995]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

```go
package main

import (
	"regexp"
	"path"
)

var (
	winAbsolutePathRegegp = regexp.MustCompile(`^(?i)[a-z]:.+`)
)

func main() {
	var s = "D:\\a\\whatchanged\\whatchanged"
	
	println(winAbsolutePathRegegp.MatchString(s))
	
	println(path.IsAbs(s))
}
```

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\runneradmin\AppData\Local\go-build
set GOENV=C:\Users\runneradmin\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\runneradmin\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\runneradmin\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\hostedtoolcache\windows\go\1.15.5\x64
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\hostedtoolcache\windows\go\1.15.5\x64\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\a\whatchanged\whatchanged\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\RUNNER~1\AppData\Local\Temp\go-build717683694=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Determine whether a windows path is an absolute path

### What did you expect to see?

`path.IsAbs("D:\\a\\whatchanged\\whatchanged")` // should be true

### What did you see instead?

`path.IsAbs("D:\\a\\whatchanged\\whatchanged")` // but got false

here is the CI:

https://github.com/axetroy/whatchanged/runs/1497192324

here is the source code:

https://github.com/axetroy/whatchanged/blob/5050ea45deb73d861df1b2e62f945502a2c78c7d/internal/client/git.go#L41-L43

**Comment by mattn** [comment]
Please use `path/filepath.Abs`.

**Comment by axetroy** [comment]
> Please use `path/filepath.Abs`.

ohoh.

Is there any difference between these two?

I checked the documents of these two packages, and his instructions are the same

```
IsAbs reports whether the path is absolute.
```

```
IsAbs reports whether the path is absolute.
```

**Comment by axetroy** [comment]
And it doesn’t seem to not handle windows style

```go
// IsAbs reports whether the path is absolute.
func IsAbs(path string) bool {
	return strings.HasPrefix(path, "/")
}
```

**Comment by mattn** [comment]
Please check path_windows.go

```
// IsAbs reports whether the path is absolute.
func IsAbs(path string) (b bool) {
	if isReservedName(path) {
		return true
	}
	l := volumeNameLen(path)
	if l == 0 {
		return false
	}
	path = path[l:]
	if path == "" {
		return false
	}
	return isSlash(path[0])
}
```
If this is not a question, please close this. Thank you.

**Comment by axetroy** [comment]
ok. my bad.
Thank you for your patience and have a good day. 👍
