### ISSUE TITLE
black lives matter

### ISSUE THREAD

**Issue by f-sys** [golang/go#43006]
Why is golang.org project politically active? I think is should stay politically neutral to be in conformity with code of conduct of golang community. BLM is political organization. If golang community wants to trully apply its code of conduct, it should

A) Remove BLM strip
or
B) Shows links to other political movements with different opinion on different political sides than BLM

**Comment by ALTree** [comment]
Please see https://github.com/golang/go/issues/41094#issuecomment-682574230.
