### ISSUE TITLE
x/tools/gopls: duplicates multi-line comment on first function after imports on every save

### ISSUE THREAD

**Issue by kdeconinck** [golang/go#43000]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 windows/amd64

gopls version
golang.org/x/tools/gopls v0.5.4
    golang.org/x/tools/gopls@v0.5.4 h1:PkQWDfzw8CxoseHDQniF2GhzmndN8KnQL6gcG2gnF3Y=
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\kdeconinck\AppData\Local\go-build
set GOENV=C:\Users\kdeconinck\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\kdeconinck\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\kdeconinck\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\kdeconinck\DEV\github.com\kdeconinck\GOSudoku\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\KDECON~1\AppData\Local\Temp\go-build977075402=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Create a new Go source file and add a function to the file.
Add a comment to that function which spawns multiple lines.

<pre>
// Package main implements the main entry point for the application.
package main

// PRIVATE: The method `main` implements the MAIN entry point for the application.
//          This method is executed when the application is started.
func main() {
	// TODO: Implement the 'MAIN' entry point for the application.
}
</pre>

Next save the document.

### What did you expect to see?

The document should be saved the same way as it was written.

### What did you see instead?

The lines below the first line of the comment of the method is duplicated.

<pre>
// Package main implements the main entry point for the application.
package main

// PRIVATE: The method `main` implements the MAIN entry point for the application.
//          This method is executed when the application is started.
//          This method is executed when the application is started.
func main() {
	// TODO: Implement the 'MAIN' entry point for the application.
}
</pre>

When saving again, there's a duplication again:

<pre>
// Package main implements the main entry point for the application.
package main

// PRIVATE: The method `main` implements the MAIN entry point for the application.
//          This method is executed when the application is started.
//          This method is executed when the application is started.
//          This method is executed when the application is started.
//          This method is executed when the application is started.
func main() {
	// TODO: Implement the 'MAIN' entry point for the application.
}
</pre>

### Related issues.

https://github.com/golang/go/issues/39147

### Additional information:

When the first method in the Go source file is a method that does NOT contain a comment or that does contain a comment which does NOT span multiple lines, other methods in this file containing comments which spans multiple lines are NOT duplicated.

<pre>
// Package main implements the main entry point for the application.
package main

func temp() {}

// PRIVATE: The method `main` implements the MAIN entry point for the application.
//          This method is executed when the application is started.
func main() {
	// TODO: Implement the 'MAIN' entry point for the application.
}
</pre>

**Comment by stamblerre** [comment]
Thank you for reporting this issue. The fix for this should be in the pre-release for gopls/v0.5.5 (which will be out later today). Can you try it out and confirm that it fixes the issue? You can download it by running `GO111MODULE=on go get golang.org/x/tools/gopls@v0.5.5-pre.1`.

**Comment by kdeconinck** [comment]
Thanks for the feedback.
I have installed it locally in my project and the issue seems to be gone.

Ticket can be closed.
