### ISSUE TITLE
macbook air M1 2020: rosetta error: ulock_wait failure: 105

### ISSUE THREAD

**Issue by yangcheng-icbc** [golang/go#43018]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
go get -u github.com/astaxie/beego
where exec:

**go: downloading golang.org/x/text v0.3.4
rosetta error: ulock_wait failure: 105**

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yangcheng/Library/Caches/go-build"
GOENV="/Users/yangcheng/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/yangcheng/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/yangcheng/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f1/hfylr73562nbwdw493ymr3qm0000gn/T/go-build606688756=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
go get -u github.com/astaxie/beego

### What did you expect to see?
installed beego

### What did you see instead?
install failed

**Comment by ALTree** [comment]
Thanks for the report, this is already tracked at #42700. Closing here.
