### ISSUE TITLE
"go mod vendor" picks wrong commit for a tagged version

### ISSUE THREAD

**Issue by coypoop** [golang/go#43034]
Apologies if it is a duplicate report.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 netbsd/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
NetBSD amd64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/fly/.cache/go-build"
GOENV="/home/fly/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="netbsd"
GOINSECURE=""
GOMODCACHE="/home/fly/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="netbsd"
GOPATH="/home/fly/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/pkg/go115"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/pkg/go115/pkg/tool/netbsd_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build989125027=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Reproducer script:
<pre>
#!/bin/sh
cat << EOF > main.go
package reporters

import (
	"github.com/onsi/ginkgo"

	ginkgo_reporters "kubevirt.io/qe-tools/pkg/ginkgo-reporters"
)

// NewReporters is a function to gather new ginkgo test reporters
func NewReporters() []ginkgo.Reporter {
	reporters := make([]ginkgo.Reporter, 0)
	if ginkgo_reporters.Polarion.Run {
		reporters = append(reporters, &ginkgo_reporters.Polarion)
	}
	if ginkgo_reporters.JunitOutput != "" {
		reporters = append(reporters, ginkgo_reporters.NewJunitReporter())
	}
	return reporters
}
EOF

cat << EOF > go.mod
module example.com/m

require (
	kubevirt.io/qe-tools v0.1.3
	github.com/onsi/ginkgo v1.12.1
)
EOF

go mod vendor

git clone https://github.com/kubevirt/qe-tools
sh -c "cd qe-tools && git checkout v0.1.3"

diff -ru qe-tools/ vendor/kubevirt.io/qe-tools/
</pre>

### What did you expect to see?

I expect to see no/little output from the `diff -ru qe-tools vendor/kubevirt.io/qe-tools/` at the end of running this script, as there should be no difference between Go's vendored v0.1.3 and the "git checkout v0.1.3" directory.

### What did you see instead?
Long diff, the wrong commit (two commits early) was picked.

**Comment by seankhliao** [comment]
(most likely) `kubevirt.io/qe-tools` moved their tag

if you try with `GOPROXY=direct` and a clean modcache
```
example.com/m imports
	kubevirt.io/qe-tools/pkg/ginkgo-reporters: kubevirt.io/qe-tools@v0.1.3: verifying module: checksum mismatch
	downloaded: h1:TUQdOK40a5/wLwYQwiy56WBaS+OYcGxAEHe9rhEPZZM=
	sum.golang.org: h1:ZDDolkD2IsHuPW8PNyty5fWO6wpI2BXcQpC65en/9FU=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by coypoop** [comment]
I see, thanks.
