### ISSUE TITLE
hash/hasmap - Allow Creation of a Fixed Seed

### ISSUE THREAD

**Issue by tebeka** [golang/go#43043]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/miki/.cache/go-build"
GOENV="/home/miki/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/miki/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/miki/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/miki/work/ardanlabs/gotraining/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build588961670=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
I'm testing a code that uses `hash/maphash`, since there's no way to create a fixed seed the test randomly fails.

### What did you expect to see?

I'd like to have a way to create a fixed `Seed` (like there is in `math/rand`)

### What did you see instead?

No way to create a fixed seed.

**Comment by randall77** [comment]
This feature is intentionally missing. Providing a way to generate a reproducible seed means we're locked into a hashing algorithm (a historical problem we've had with `math/rand`, see for example #8013) .

If you need fixed seed behavior for reproducing a test, you will need to build a mock of the hasher and use that while testing.

Conceivable the stdlib could provide that mock and declare a common interface, but I'd like to see it developed outside the stdlib first.

**Comment by tebeka** [comment]
Thanks for the explanation @randall77
