### ISSUE TITLE
cmd/go: go mod vendor should copy files matched by //go:embed

### ISSUE THREAD

**Issue by jayconrod** [golang/go#43077]
### What did you do?

In a package outside the main module (`example.com/p`), embed some files in a subdirectory `sub` using a `//go:embed` directive.

From the main module, import `example.com/p`.

Run `go mod vendor`.

### What did you expect to see?

The embedded files are present in `vendor/example.com/p/sub`. Other files from that directory are not vendored.

### What did you see instead?

`vendor/example.com/p/sub` is not present.

cc @bcmills @matloob @rsc

**Comment by toothrot** [comment]
Any update on this as a Go 1.16 release blocker?

**Comment by jayconrod** [comment]
This should still be a release blocker.

Ideally, we should report an error if there ends up being conflict or overlap between different vendored packages. There are a few known issues with that (#38571, #38342, #42970), and I don't think it's essential to solve that for 1.17.
