### ISSUE TITLE
x/pkgsite: can't figure out how to navigate to standard library

### ISSUE THREAD

**Issue by bcmills** [golang/go#43080]
### What is the URL of the page with the issue?

https://pkg.go.dev/search?q=std 
 
 
### What is your user agent?
 
`Mozilla/5.0 (X11; CrOS x86_64 13421.102.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.199 Safari/537.36`
 
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/5200974/101537794-15345580-396a-11eb-94d9-4f5388d7ccd7.png)
  
 
### What did you do?

1. Navigate to https://pkg.go.dev/.
2. Attempt to figure out how to list all packages in the Go standard library.
3. Not seeing any direct link, query for `std`, since I know from prior use that `go list std` lists the packages in the standard library.
  
 
### What did you expect to see?

A straightforward way to list the packages in the standard library, either via a direct link from https://pkg.go.dev/ or in the search results for the `std` query. 
 
 
### What did you see instead?

To figure out the URL for the standard library, I ended up searching for a known standard package (`encoding/binary`) and then following the `Discover Packages > Standard library` breadcrumb at the top of the page.

**Comment by jamalc** [comment]
I'm going to close this in favor of #40785.
