### ISSUE TITLE
dev.cmdgo: create dev branch for cmd/go

### ISSUE THREAD

**Issue by matloob** [golang/go#43084]
The cmd/go team would like to have a branch for doing feature development during the freeze. (There are relatively few outstanding 1.16 issues and it is uncommon for new cmd/go issues to be discovered during the freeze period).

cc @bcmills @jayconrod @golang/osp-team

**Comment by cagedmantis** [comment]
The `dev.cmdgo` branch has been created from the `4d27c4c223ccb7de3876abbac79b58ad9579be1a` commit of the `master` branch. Please let us know if you encounter any issues.
