### ISSUE TITLE
go/types, types2: provide better error message for short variable declarations

### ISSUE THREAD

**Issue by griesemer** [golang/go#43087]
Given
```Go
var a int
a, b, b := 1, 2, 3
_ = a
_ = b
```
The compiler reports: `b repeated on left side of :=`.
`types2` (`go tool compile -G`) reports: `b redeclared in this block`.

The compiler error message seems better because it's actually ok to "redeclare" a variable (here: `a`) with a short variable declaration.

cc: @findleyr

**Comment by griesemer** [comment]
cc: @findleyr

**Comment by findleyr** [comment]
This was resolved by the port to go/types: https://golang.org/cl/314629.
