### ISSUE TITLE
cmd/vet: does not understand multiple keys in key:value pair in struct tag

### ISSUE THREAD

**Issue by myitcv** [golang/go#43083]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +e10c94af26 Mon Dec 7 02:31:33 2020 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/myitcv/gostuff/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel +e10c94af26 Mon Dec 7 02:31:33 2020 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/tmp.Y0bBClLQls/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build628121616=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
go vet .

-- go.mod --
module mod.com

go 1.16
-- main.go --
package main

type MyStruct struct {
	Field1 string `json bson xml form:"field_1,omitempty" other:"value"`
}
```

### What did you expect to see?

No error (because this example is taken from https://github.com/golang/go/issues/40281#issuecomment-669324646)

### What did you see instead?

```
./main.go:4:2: struct field tag `json bson xml form:"field_1,omitempty" other:"value"` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair
```

Marking as a release-blocker because I believe it to be one.

Despite raising this issue, I share the concerns raised by @rogpeppe in https://github.com/golang/go/issues/40281#issuecomment-739822357. 

cc @rsc @mvdan @ianlancetaylor

**Comment by dmitshur** [comment]
Also CC @timothy-king.

**Comment by mvdan** [comment]
Hm, I'm surprised that the feature was merged into master without teaching vet about it.

**Comment by dmitshur** [comment]
@ianlancetaylor has offered to take a look, so I'll update the issue status to make that more visible.

**Comment by ianlancetaylor** [comment]
Sent https://golang.org/cl/277092 but it needs reviewers.

**Comment by timothy-king** [comment]
@ianlancetaylor I can review this.

**Comment by dmitshur** [comment]
This issue was closed because CL 277092 had a "Fixes golang/go#43083" line.

Re-opening to update the vendored copy of golang.org/x/tools in the standard library to pull in that change.

**Comment by ianlancetaylor** [comment]
Thanks.

**Comment by ianlancetaylor** [comment]
Note: proposal #40281 was declined after all, so this change was rolled back.
