### ISSUE TITLE
x/sys/windows/svc/mgr: CreateService ignores ErrorControl type

### ISSUE THREAD

**Issue by maja42** [golang/go#43094]
go1.15

### What did you do?
I created a new windows service using [CreateService](https://godoc.org/golang.org/x/sys/windows/svc/mgr#Mgr.CreateService). You can pass a service configuration which includes the filed `ErrorControl`.  It supports the following values:

```
	ErrorCritical = windows.SERVICE_ERROR_CRITICAL
	ErrorIgnore   = windows.SERVICE_ERROR_IGNORE
	ErrorNormal   = windows.SERVICE_ERROR_NORMAL
	ErrorSevere   = windows.SERVICE_ERROR_SEVERE
```

I tried to create a windows service with `ErrorIgnore`, which has the underlying uint32-value `0` - which is also go's zero-value.
CreateService sees that value, assumes that it's not populated, and replaces it with ErrorNormal (1).

There is no workaround (that I can see) to configure `ErrorIgnore` with the go API.
The only option is to install the service and then edit the registry-key at `r\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\<service>` with the name `ErrorControl`.

### What did you expect to see?

I expect the service to have the correct ErrorControl type.
If this can't be fixed due to backwards compatibility reasons, at least the goDoc should mention the issue and provide an alternative way of configuring this.

**Comment by mengzhuo** [comment]
https://github.com/golang/sys/blob/master/windows/svc/mgr/mgr.go#L117-L125
Kindly CC @zx2c4

**Comment by zx2c4** [comment]
Thanks for the patch. I've followed up on gerrit.
