### ISSUE TITLE
x/pkgsite: document that GitHub PRs are accepted in the CONTRIBUTING.md

### ISSUE THREAD

**Issue by julieqiu** [golang/go#43100]
Per https://golang.org/doc/contribute.html#sending_a_change_github, x/pkgsite accepts PRs. 

We should add this to the [CONTRIBUTING.md](https://github.com/golang/pkgsite/blob/master/CONTRIBUTING.md#getting-started), so that new contributors are aware of this option for contributing.

**Comment by kirandasika98** [comment]
Hi @julieqiu, Can I pick up this issue?

**Comment by julieqiu** [comment]
Please do!
