### ISSUE TITLE
cmd/compile: incorrect evaluation order of select statement clauses

### ISSUE THREAD

**Issue by mdempsky** [golang/go#43111]
The program below should run and terminate successfully. It does so when compiled with gccgo, but it fatal errors due to deadlock when compiled with cmd/compile.

```
package main

var ch = make(chan int)

func f() chan int {
	close(ch)
	ch = nil
	return nil
}

func main() {
	select {
	case <-ch:
	case f() <- 0:
	}
}
```

The issue is this code responsible for ordering receive clauses within select statements:

https://github.com/golang/go/blob/6c64b6db6802818dd9a4789cdd564f19b70b6b4c/src/cmd/compile/internal/gc/order.go#L892-L896

It should actually be checking IsAutoTmp like the code responsible for ordering send clauses:

https://github.com/golang/go/blob/6c64b6db6802818dd9a4789cdd564f19b70b6b4c/src/cmd/compile/internal/gc/order.go#L951-L959

Discovered with @cuonglm.

**Comment by cuonglm** [comment]
I fixed in https://go-review.googlesource.com/c/go/+/276132/3, not sure this is qualified to fix in go 1.16. Willing to make the fix to master if so.
