### ISSUE TITLE
x/pkgsite: image in readme and privacy

### ISSUE THREAD

**Issue by pierrre** [golang/go#43114]
If a readme includes images, they're showed directly on pkg.go.dev.
It could cause privacy/security issue:
- the image could be used to track users (statistics/IP/etc...)
- if the image is "malicious", and the web browser has a bug, it could crash it, or execute arbitrary code

We should probably have an image proxy (similar to what Github does).

I'm surprised nobody reported it already.
I haven't found any similar issue on the tracker.
Maybe I didn't search correctly.

**Comment by julieqiu** [comment]
Closing this as a duplicate of https://github.com/golang/go/issues/37128.

**Comment by pierrre** [comment]
sorry for the duplicate, I couldn't find this other issue in my search.
