### ISSUE TITLE
x/pkgsite: additional metadata in the right sidebar

### ISSUE THREAD

**Issue by jamalc** [golang/go#43129]
We want to surface useful information to Go users and help reinforce best practices for maintaining packages on pkg.go.dev. To do so, we plan to highlight the following metadata: 

- Has go.mod file
- Permissive license, according to https://pkg.go.dev/license-policy
- Tagged version
- Stable version (has a tagged version at v1.0.0 or higher)

This information will be displayed in the right sidebar in the order listed above. A toggle tip will explain in more detail what each item represents.

Meets all best practices		          
<img width="337" alt="Screen Shot 2020-12-10 at 4 25 39 PM" src="https://user-images.githubusercontent.com/18269441/101848001-7868e800-3b22-11eb-9e9b-2b1019c7dba4.png">

Meets no best practices
<img width="338" alt="Screen Shot 2020-12-10 at 5 50 25 PM" src="https://user-images.githubusercontent.com/18269441/101848015-7e5ec900-3b22-11eb-88c7-e106292651de.png">

This set of data is not an exhaustive representation of best practices but will provide a good foundation for one and should evolve over time to include information about things like popularity, code quality, and code stability.

**Comment by seh** [comment]
These details are not visible in a browser window not deemed to be sufficiently wide—in my case, about 885 pixels. Can we display these details elsewhere, such as at the bottom of the page if it's too narrow?
