### ISSUE TITLE
Memory could be down

### ISSUE THREAD

**Issue by zgb40302** [golang/go#43133]
What version of gRPC are you using?
v1.32.0

What version of Go are you using (go version)?
1.14

What operating system (Linux, Windows, …) and version?
linux  (kernel 3.10)

What did you do?

client (lua http/json) ----------> server(go grpc) ---------> index ( brpc)

because the delay of index  is long , so, the tcp buffer between server  and index  is full  ,then  the requests from server  to index  is timeout , at the time  the memory of server keeps rising。
when server start  ， ps result: 35513 root      20   0 1692384 431464  12128 S 203.3  0.7  59:48.71 webapp
when server timeout, ps result:  35513 root      20   0 5835044      4.3g  12164 S  21.1    6.9 111:56.14 webapp 

then  , I stop the client and index , the pprof result of server:
![image](https://user-images.githubusercontent.com/24806026/101854266-24024e80-3b9c-11eb-934b-e203f6c79f73.png)
but the RSS of server still 4.3g ，and  wait for 8 hours ,it is still 4.3g.

I  close the hugepage option , reproduce it , the memory could be still not down.
echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled
echo 'never' > /sys/kernel/mm/transparent_hugepage/defrag 

so ,  who know why could the memory of RSS not down,  and it is normal ?

thanks!

**Comment by mdlayher** [comment]
Please see https://github.com/golang/go/wiki/Questions. Closing.
