### ISSUE TITLE
x/blog:Only direct dependencies are recorded in the go.mod file: needs a recheck.

### ISSUE THREAD

**Issue by Yigaue** [golang/go#43153]
### What version of Go are you using (`go version`)?

<pre>
$ 1.15.6 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ N/A

</pre></details>

### What did you do?
cat go. mod

### What did you expect to see?

Only direct dependencies

### What did you see instead?
Both direct and indirect dependency.

### Update the go blog
Udert the Sub-heading "Adding a dependency",
I think the statement "Only direct dependencies are recorded in the go.mod file" is misleading or contradictory. A better explanation should be found for this. Thanks.

**Comment by toothrot** [comment]
Can you provide a simple program that illustrates this issue?
