### ISSUE TITLE
x/pkgsite: pq: function websearch_to_tsquery(unknown) does not exist

### ISSUE THREAD

**Issue by oiooj** [golang/go#43154]
I inited a DB and test pkgsite but when I search a keyword I got an error,  a pg function not found: websearch_to_tsquery(unknown).

```
2020/12/12 23:07:54 Error: fetchSearchPage(ctx, db, "http"): DB.Search(ctx, "http", 10, 0): "deep" search failed: DB running query local-6: pq: function websearch_to_tsquery(unknown) does not exist
2020/12/12 23:07:54 Info: 500 /search map[isRobot:false requestType:request end]
```

![image](https://user-images.githubusercontent.com/2253095/101987761-0be01b80-3cd1-11eb-86d0-de1bb55c80f4.png)

I inited the database using migrations/*.up.sql files,  Did I miss something？
Is there any guide to run this service for developing. Thanks.

/cc @julieqiu

**Comment by jba** [comment]
That is not one of our functions; it's built in to Postgres.

Try this from `psql` or other DB client:
```
select websearch_to_tsquery('foo'); 
```
If that fails, perhaps you have an older version of Postgres? We're on version 11.

If it succeeds, maybe there's a problem with the argument. Can you figure out what's being passed to the function?

**Comment by jba** [comment]
> Is there any guide to run this service for developing.

https://go.googlesource.com/pkgsite/+/master/doc/postgres.md is the best we have at the moment. Enhancements welcome.

**Comment by oiooj** [comment]
Yes , this function added in `PostgreSQL 11`, Thanks @jba
