### ISSUE TITLE
cmd/compile: possible escape analysis cleanup

### ISSUE THREAD

**Issue by rsc** [golang/go#4315]
<pre>from lvd; not a requirement for go 1.1

diff -r 959dee37d03d src/cmd/gc/esc.c
--- a/src/cmd/gc/esc.c Tue Oct 30 11:10:08 2012 +1100
+++ b/src/cmd/gc/esc.c Tue Oct 30 11:24:15 2012 +0100
@@ -390,15 +390,18 @@
  break;
  }

- escloopdepth(e, n-&gt;left);
- escloopdepth(e, n-&gt;right);
- escloopdepthlist(e, n-&gt;list);
- escloopdepth(e, n-&gt;ntest);
+ // TODO(lvd) left, right, list, ntest and rlist should only contain
expressions, not statements
+ // and the standard tree compiles fine with these branches commented
out, but that may not
+ // outweigh the time spent debugging a misjudged label leading to a
spurious stackallocation
+ // when someone violates this assumption somewhere unrelated.
+// escloopdepth(e, n-&gt;left);
+// escloopdepth(e, n-&gt;right);
+// escloopdepthlist(e, n-&gt;list);
+// escloopdepth(e, n-&gt;ntest);
  escloopdepth(e, n-&gt;nincr);
  escloopdepthlist(e, n-&gt;nbody);
  escloopdepthlist(e, n-&gt;nelse);
- escloopdepthlist(e, n-&gt;rlist);
-
+// escloopdepthlist(e, n-&gt;rlist);
 }

 static void</pre>

**Comment by odeke-em** [comment]
@randall77 do you think we should close this issue since the C code being referenced is no longer even in the source?

**Comment by randall77** [comment]
Yes, I think this issue is outdated.  @dr2chase rewrote a lot of the escape analysis code.
Closing.  If David thinks it is still relevant, he can reopen.

**Comment by dr2chase** [comment]
I'm happy leaving this closed, although(because) I am still not happy with the escape analysis code.
