### ISSUE TITLE
go get firebase.google.com/go/v4 not working

### ISSUE THREAD

**Issue by KavyaKandhway** [golang/go#43150]
### What version of Go are you using (`go version`)?
go version go1.15.6 windows/amd64
<pre>
$ go version
go version go1.15.6 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\User\AppData\Local\go-build
set GOENV=C:\Users\User\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\User\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\User\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\User\AppData\Local\Temp\go-build681828342=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Tried to run the command "go get firebase.google.com/go/v4"

### What did you expect to see?
package installation

### What did you see instead?
cannot find package "firebase.google.com/go/v4" in any of:
        c:\go\src\firebase.google.com\go\v4 (from $GOROOT)
        C:\Users\User\go\src\firebase.google.com\go\v4 (from $GOPATH)

**Comment by seankhliao** [comment]
exclude the `/v4` suffix if using GOPATH mode, see their [readme](https://github.com/firebase/firebase-admin-go#installation)

**Comment by KavyaKandhway** [comment]
tried that too
Still not woring

C:\Users\User\go>go get firebase.google.com/go
# cd C:\Users\User\go\src\google.golang.org\api; git pull --ff-only
fatal: not a git repository (or any of the parent directories): .git
package google.golang.org/api/iterator: exit status 128
cannot find package "google.golang.org/api/option" in any of:
        C:\Go\src\google.golang.org\api\option (from $GOROOT)
        C:\Users\User\go\src\google.golang.org\api\option (from $GOPATH)
cannot find package "google.golang.org/api/option/internaloption" in any of:
        C:\Go\src\google.golang.org\api\option\internaloption (from $GOROOT)
        C:\Users\User\go\src\google.golang.org\api\option\internaloption (from $GOPATH)
cannot find package "google.golang.org/api/transport/grpc" in any of:
        C:\Go\src\google.golang.org\api\transport\grpc (from $GOROOT)
        C:\Users\User\go\src\google.golang.org\api\transport\grpc (from $GOPATH)
cannot find package "google.golang.org/api/googleapi" in any of:
        C:\Go\src\google.golang.org\api\googleapi (from $GOROOT)
        C:\Users\User\go\src\google.golang.org\api\googleapi (from $GOPATH)
cannot find package "google.golang.org/api/transport" in any of:
        C:\Go\src\google.golang.org\api\transport (from $GOROOT)
        C:\Users\User\go\src\google.golang.org\api\transport (from $GOPATH)
cannot find package "google.golang.org/api/storage/v1" in any of:
        C:\Go\src\google.golang.org\api\storage\v1 (from $GOROOT)
        C:\Users\User\go\src\google.golang.org\api\storage\v1 (from $GOPATH)
cannot find package "google.golang.org/api/transport/http" in any of:
        C:\Go\src\google.golang.org\api\transport\http (from $GOROOT)
        C:\Users\User\go\src\google.golang.org\api\transport\http (from $GOPATH)

**Comment by bokunodev** [comment]
`go mod init` ?? 
sorry to interrupt

**Comment by KavyaKandhway** [comment]
Yup I figured it out... Thanks :D

**Comment by KavyaKandhway** [comment]
It worked thanks

**Comment by HPaulos** [comment]
excuse me , how did you figure it out? Can you please share how you did that, I was having the smae issue

**Comment by KavyaKandhway** [comment]
> excuse me , how did you figure it out? Can you please share how you did that, I was having the smae issue

I simply uninstalled the package(because previously it wasn't installed properly), then I reinstalled it.

**Comment by HPaulos** [comment]
Thanks man, that did solve my issue too!
