### ISSUE TITLE
Const has no type match

### ISSUE THREAD

**Issue by mark4z** [golang/go#43158]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.15.5

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mark4z/Library/Caches/go-build"
GOENV="/Users/mark4z/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mark4z/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mark4z/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/Cellar/go/1.15.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/j0/gv3fglgj6zz_jpfcshjqzwrr0000gn/T/go-build066167980=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

	u := uint32(1)
	const b = 2
	fmt.Print(u-b)

### What did you expect to see?
error: invalid operation: u - b (mismatched types uint32 and int)

### What did you see instead?

4294967295

It's a unpredictable behavior

**Comment by seankhliao** [comment]
`b` is an *untyped constant*, see [spec](https://golang.org/ref/spec#Constants), [blog post](https://blog.golang.org/constants)

**Comment by mdlayher** [comment]
See above, and also see https://github.com/golang/go/wiki/Questions. Closing.
