### ISSUE TITLE
cmd/go: allow invalid flag in #cgo LDFLAGS: CoreFoundation

### ISSUE THREAD

**Issue by steeve** [golang/go#43152]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/steeve/Library/Caches/go-build"
GOENV="/Users/steeve/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/steeve/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/steeve/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/td/p8xt8d953g37w9f841byty940000gn/T/go-build367258204=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Trying to build an iOS framework containing Go code with bazelbuild/rules_go.

### What did you expect to see?

A succesful build.

### What did you see instead?

```
go build runtime/cgo: invalid flag in #cgo LDFLAGS: CoreFoundation
```

I believe this is in line with https://github.com/golang/go/issues/42565 and is "caused" by https://github.com/golang/go/blob/go1.15.6/src/runtime/cgo/cgo.go.

**Comment by steeve** [comment]
cc @jayconrod also

**Comment by ianlancetaylor** [comment]
For the record, the use in runtime/cgo/cgo.go is `#cgo darwin,arm64 LDFLAGS: -framework CoreFoundation`.  In the flag checking code, `-framework` is expected to have a following argument, which in this case is `CoreFoundation`.  So it is supposed to work.  Just pointing this out as a place to investigate.

Just to confirm, you are cross-building for arm64?
