### ISSUE TITLE
x/pkgsite: remove github.com/mmontes11/crypto-trading

### ISSUE THREAD

**Issue by mmontes11** [golang/go#43162]
What is the URL of the page with the issue?
https://pkg.go.dev/github.com/mmontes11/crypto-trading

What is your user agent?
N/A

Screenshot
N/A

What did you do?
N/A

What did you expect to see?
Remove the package `github.com/mmontes11/crypto-trading`, it was created by mistake.

What did you see instead?
I cannot remove it manually.

**Comment by jba** [comment]
Done. It may take a few minutes for the cache to expire.
