### ISSUE TITLE
@@

### ISSUE THREAD

**Issue by Satsuk-yuuya** [golang/go#43169]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by ALTree** [comment]
Empty, closing.

**Comment by vpoulailleau** [comment]
Same here https://github.com/python/peps/issues/1735, looks like a bot…

**Comment by Satsuk-yuuya** [comment]
I use it.but I don't know in hacker.
so I am making Security.
thank you.

 from.Yuuya,s

2020年12月15日(火) 20:07 Vincent Poulailleau <notifications@github.com>:
