### ISSUE TITLE
cmd/compile: failure to diagnose re-declaring dot-imported identifiers

### ISSUE THREAD

**Issue by mdempsky** [golang/go#43167]
This program should fail to compile with an error that Index was already declared due to dot-importing package bytes: https://play.golang.org/p/EAPSJQRfm2F

go/types and gccgo correctly diagnose this; cmd/compile does not.

**Comment by KeKe-Li** [comment]
this dot-imported  identifiers   diagnose ,  not often  use. and it's not very consistent with the concept of go.

**Comment by mdempsky** [comment]
@KeKe-Li Sorry, I don't follow.

The Go spec defines how import declarations should behave: https://golang.org/ref/spec#Import_declarations. go/types and gccgo are correctly implementing that for the linked program. cmd/compile is not.

**Comment by cuonglm** [comment]
@mdempsky seems that we don't check for re-declared when processing `VarDecl` in noder.go?

**Comment by mdempsky** [comment]
@cuonglm I think we weren't setting `Block` correctly for the imported symbols, so `importdot` didn't set it correctly for the local aliases, and so `declare` didn't recognize it as a redeclaration.

I have fixes for a bunch of these dot-import issues. Just polishing up the CLs to get ready for upload.

**Comment by cuonglm** [comment]
> @cuonglm I think we weren't setting `Block` correctly for the imported symbols, so `importdot` didn't set it correctly for the local aliases, and so `declare` didn't recognize it as a redeclaration.
> 
> I have fixes for a bunch of these dot-import issues. Just polishing up the CLs to get ready for upload.

Ah right, seems that `s.Block` should be changed to `types.Block` in `importdot`.

**Comment by mdempsky** [comment]
Fixed on dev.regabi.
