### ISSUE TITLE
access: Github("go-approvers")

### ISSUE THREAD

**Issue by seankhliao** [golang/go#43161]
Hey, I'd like to ask for access to https://github.com/orgs/golang/teams/go-approvers for gardening focused on the issue tracker

github activity: https://github.com/golang/go/issues?q=is%3Aissue+commenter%3Aseankhliao

**Comment by myitcv** [comment]
@seankhliao - thank you for your excellent contributions on Slack too, especially the `#modules` channel.

**Comment by dmitshur** [comment]
Hi Sean,

Thank you so much for your contributions on the issue tracker and elsewhere, they've been very helpful! We've discussed this request on the team and agreed to grant you access. I've sent you an invite to the `go-approvers` group now.

Please let us know if you have any questions or issues, and thank you again!
