### ISSUE TITLE
cmd/link: support Windows resource files on windows/arm [freeze exception]

### ISSUE THREAD

**Issue by aclements** [golang/go#43182]
This is a formal freeze exception request for #42866 (which was maybe itself a freeze exception request, but that's not clear at the top).

In Go 1.16, windows/arm support is being revived. However, because of differences in platform tooling used to build Windows resource files, the Go linker is not currently compatible with resource files on windows/arm. Since it's common for Windows Go binaries to link against Windows resource files, it's not currently possible to build many complete Go applications on windows/arm.

@zx2c4 would like to land a series of fairly small changes to the Go linker ([summarized here](https://github.com/golang/go/issues/42866#issuecomment-741223275)) to support Windows resource files produced by platform tools on windows/arm. We'd like to do this in 1.16 to coincide with the revival of windows/arm support.

cc @golang/release

**Comment by dmitshur** [comment]
Thank you for making this freeze exception request. We've considered it on the release team and are okay with it.

Approved.

Is your plan to land those changes in time for the beta 1? This issue currently blocks beta 1 (because there isn't an okay-after-beta1 label).

**Comment by zx2c4** [comment]
The changes are ready now, as far as I can tell, so as soon as the +2s arrive, I'll submit them.

**Comment by aclements** [comment]
We're doing final reviews of @zx2c4 's CLs now. I don't think this has to block beta 1, though.
