### ISSUE TITLE
cmd/vet: unnecessary diagnostics about json:"-" on unexported fields

### ISSUE THREAD

**Issue by jech** [golang/go#43196]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 linux/amd64
</pre>

### What did you do?

I like to write code such as the following:
```
type description struct {
	fileName       string              `json:"-"`
	loadTime       time.Time           `json:"-"`
	modTime        time.Time           `json:"-"`
	fileSize       int64               `json:"-"`
	Description    string              `json:"description,omitempty"`
        ...
}
```
The unexported fields have a `json:"-"` tag, so that the resulting behaviour doesn't change if I happen to export the fields later.  Unfortunately, this causes `go vet` warning:

    group/group.go:567:2: struct field fileName has json tag but is not exported

There is apparently no way to disable this warning without disabling all JSON-related checks.  Please disable the warning in the particular case of a `json:"-"` tag, or at least provide a way to disable it without disabling all JSON-related checks.

### What did you expect to see?

`go vet` doesn't warn about `json:"-"` tags on unexported fields, only about non-trivial json tags.

### What did you see instead?

`go vet` complains, and there is no way to avoid the warning short of disabling all JSON-related checking.

**Comment by mdempsky** [comment]
I think it's fine to suppress a warning about `json:"-"` on unexported fields, since they're not an issue per se.

**Comment by laojianzi** [comment]
I think the change has been made in https://github.com/golang/tools/commit/73b12cab2531d716d7df68317338773313a49bac

**Comment by mdempsky** [comment]
Yep, thanks.
