### ISSUE TITLE
x/pkgsite: save the godoc!

### ISSUE THREAD

**Issue by awsom82** [golang/go#43199]
The new pkg.go.dev is nice. But it's much more uncomfortable to use it instead of an old one. Even an old button design looks better in my opinion.

**Comment by julieqiu** [comment]
Per https://blog.golang.org/godoc.org-redirect:

> The gddo repository will remain available for anyone who wants to keep running it themselves, or even fork and improve it. We will mark it archived to make clear that we will no longer accept contributions. However, you will be able to continue forking the repository.

Closing this issue.
