### ISSUE TITLE
Go test/generate/get running endlessly 

### ISSUE THREAD

**Issue by tiloKo** [golang/go#43192]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=C:\Users\xxx\go\bin
set GOCACHE=C:\Users\xxx\AppData\Local\go-build
set GOENV=C:\Users\xxx\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\xxx\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\xxx\go;C:\Users\xxx\git;
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\xxx\git\piper_CL\jenkins-library\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\xxx\AppData\Local\Temp\go-build997310438=/tmp/go-build -gno-record-gcc-switches
GOROOT/bin/go version: go version go1.15.6 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.15.6
</pre></details>

### What did you do?
go test in a folder not related to go does just output: package .: no Go files in <dir>
go test in a folder with go files just runs endlessly

same with go generate

same with go get

windows task manager -> "Analyze Wait chain" -> Displays go.exe is waithing for some of iths own threads endlessly

### What did you expect to see?
something, at least an error message

### What did you see instead?
nothing - it just runs endless

**Comment by mvdan** [comment]
This isn't enough information to figure out what's going on. Please provide a way to reproduce the hang.

**Comment by tiloKo** [comment]
I have this issue on my business computer - I tried to reproduce on my private PC but there everything works as expected. I try to investigate with our IT department what has changed and might have caused this.

Anyway could you point me to some information how I can analyze this in more detail? Is there a way that go itself is writing trace files or how I can obtain any other information about it? go test -trace does not write anything as it is the runtime which hangs, not my tests.

**Comment by mvdan** [comment]
you could try `go test -x -v` and run as few tests as possible, reducing the problem to as small an input as you can.

**Comment by tiloKo** [comment]
sorry for my limited capability to express the problem:
it is not the unit tests which hang, it is go itself. and it is not only go test but several go sub commands which hang. Other concrete example: 
go get golang.org/x/tools/gopls@latest
just does nothing, for hours, no output, just running and waiting for something which is not happening...

**Comment by mvdan** [comment]
If many go commands hang forever, that sounds like something is very wrong at a low level, perhaps with the system. Maybe try using a tool like `strace` to investigate what the processes are doing right up to when they get stuck, or sending SIGQUIT to get a stack trace dump of all goroutines.

cc @ianlancetaylor in case he has other ideas, but I still think this issue needs to be labelled WaitingForInfo because I don't see any actionable bug.

**Comment by randall77** [comment]
If you can, try disabling your antivirus and see if that helps.

**Comment by tiloKo** [comment]
- Unfortunately I cannot disable the antivirus on my business laptop - IT is analyzing the Anti virus Logs but did not came back to me...

- I downloaded ProcessMonitor and when executing "go get golang.org/x/tools/gopls@latest" the last "real" activity shown is reading a lot of *.mod files in <user_dir>\go\pkg\mod\cache\download\* after this only Thread Create, Thread Exit - every some seconds for about a dozen of threads...

- I created a process dump of go.exe from task manager and executed the "CrashHang" analysis of DebugDiag but it also just says it did not find any common issue and lists 19 Threads all waiting: 

ntdll!NtWaitForSingleObject+14 |  
-- | --
KERNELBASE!WaitForSingleObjectEx+93 |  
go+6d19e

only thread shown there which looks a little different is

ntdll!NtWaitForSingleObject+14 |  
-- | --
KERNELBASE!WaitForSingleObjectEx+93 |  
mfehcinj!Initialize+8566 |  
mfehcinj!Initialize+87fd |  
mfehcinj!Initialize+7f6d |  
mfehcinj+1e00 |  
mvcairo_x64+6037 |  
mvcairo_x64+5334 |  
mfehcthe+3975

searching for "mfehcinj" showed this result: https://github.com/golang/go/issues/42528

**Comment by tiloKo** [comment]
so it seems to be caused by McAfee - but why does it only affect go, everything else is working fine...

**Comment by mvdan** [comment]
Antivirus software have a track record of not liking Go programs at all, perhaps because of the runtime and unique compiler. There is not much you can do about it other than report the false positives, because there is nothing wrong with the binaries.

**Comment by tiloKo** [comment]
I finally could verify it works fine again once the virus scanner got disabled. Now the issue is reported to the vendor and I'm waiting for a new version.

**Comment by tiloKo** [comment]
As per McAfee this issue is realted to usage of WSL/WSL2...
https://kc.mcafee.com/corporate/index?page=content&id=KB91411
