### ISSUE TITLE
How to make go mod exclude a list of directories from scanning for dependencies

### ISSUE THREAD

**Issue by fearblackcat** [golang/go#43191]
I was wondering that how to use go mod if I want to ignore the directories that are demos or examples when I use go mod to download the useless dependencies which not require in my project.
Perhaps go mod should implement the feature just like in glide.yaml

> package: github.com/Masterminds/glide
> homepage: https://masterminds.github.io/glide
> **excludeDirs:**
    - node_modules
> ...

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.

**Comment by fearblackcat** [comment]
@mvdan This is not question. I think this should be a proposal.

Add new proposal for go mod to support excluding directories in project.

**Comment by mvdan** [comment]
See the previous proposals like https://github.com/golang/go/issues/30058 and https://github.com/golang/go/issues/37724. You phrased this issue as a question, not as a proposal.
