### ISSUE TITLE
spec: unclear whether error should be reported for non-comparable switch expression in empty switch

### ISSUE THREAD

**Issue by griesemer** [golang/go#43200]
For:
```Go
var a struct{ _ func() }
switch a {
}
```
the compiler reports an error:
```
cannot switch on a (type struct { _ func() }) (struct containing func() cannot be compared)
```
Since there's no `case` in the `switch` statement, this might be considered ok. The spec is not explicitly stating that this is invalid.

See also #43110.

**Comment by griesemer** [comment]
cc: @ianlancetaylor for input on what `gccgo` does.

**Comment by ianlancetaylor** [comment]
gccgo says

```
foo7.go:5:16: error: cannot switch on value whose type that may not be compared
    5 |         switch a {
      |                ^
```

So the message needs a little work but it has the same behavior.
