### ISSUE TITLE
x/pkgsite: broken image link on pkg.go.dev/std

### ISSUE THREAD

**Issue by julieqiu** [golang/go#43206]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/std  
 
### Screenshot
 
![Screen Shot 2020-12-16 at 12 18 44 AM](https://user-images.githubusercontent.com/5943521/102308260-45649100-3f34-11eb-9067-2b2bbeaaa59c.png)

 
### What did you expect to see?
 
The Gopher image in the README: https://go.googlesource.com/go/+/refs/heads/master/README.md
 
### What did you see instead?

A 404 on the image link (https://github.com/golang/go/raw/go1.15.6/src/doc/gopher/fiveyears.jpg). 

/cc @jba

**Comment by jba** [comment]
Fixed.
Required reprocessing stdlib.
