### ISSUE TITLE
embed: resolve string, []byte issues

### ISSUE THREAD

**Issue by rsc** [golang/go#43218]
Proposals #43216 and #43217 need to be resolved before the Go 1.16 release. Filing this issue in the Go 1.16 milestone for them.

**Comment by toothrot** [comment]
@rsc Is this ok to label as okay-after-beta1, or do you feel like this should block the Go 1.16 beta?

**Comment by ianlancetaylor** [comment]
This should not block the beta.

**Comment by ianlancetaylor** [comment]
Proposals #43216 and #43217 have been resolved, so closing this issue.
