### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by twr14152** [golang/go#43213]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/twr14152/go2run/misc
 
 
### What is your user agent?
 

 Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Raspbian Chromium/78.0.3904.108 Chrome/78.0.3904.108 Safari/537.36
 
 
### What did you do?
 Posted a package to the go.dev prematurely.  

 
 
 
### What did you expect to see?
 I expected to see the go2run/runcli package I created, and some others I was working on. However I didnt really know what to expect. Never done this before. I found a library of mine on here that I didnt post to go.dev. It showed a lot more of the github repo 'github.com/twr14152/Go_Network_Scripts'. So thats what I thought I was doing and I thought it might be a fluid process that got pulled occasionally. I'm guessing my assumption was wrong, and I know I need to work on package development process more. Whats currently on go.dev for go2run is not correct nor useful and I would like to get it removed if possible. 

 
### What did you see instead?

a misc folder that had little value.

**Comment by jba** [comment]
Done (wait a few minutes for cache to clear).
