### ISSUE TITLE
x/exp/shiny/driver/mtldriver: fails to build on darwin/arm64 because its mtl dependency doesn't support darwin/arm64 yet

### ISSUE THREAD

**Issue by bcmills** [golang/go#43221]
[2020-12-15T15:35:30-b5a6e24/darwin-arm64-11_0-toothrot](https://build.golang.org/log/3add507e07cc3b371788528c46a1366a3f8c7489)

```
# dmitri.shuralyov.com/gpu/mtl
In file included from mtl.m:5:
/tmp/buildlet/gopath/pkg/mod/dmitri.shuralyov.com/gpu/mtl@v0.0.0-20190408044501-666a987793e9/mtl.h:3:21: error: typedef redefinition with different types ('signed char' vs 'bool')
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/objc/objc.h:78:18: note: previous definition is here
```

CC @golang/release @dmitshur

**Comment by mvdan** [comment]
Does such a complex dependency really belong in x/exp? It feels like it will mean a continuous investment of time to keep it working on all the platforms we have builders on, which is probably the kind of work that belongs outside the x repos.

**Comment by dmitshur** [comment]
I've already prototyped a fix locally and intend to clean it up and push it.

**Comment by bcmills** [comment]
@mvdan, that's an interesting point, because last I checked that package was not actually build as a dependency of `x/exp` (see https://github.com/golang/go/issues/37175#issuecomment-585424741). I wonder what has changed since that analysis.

**Comment by dmitshur** [comment]
@bcmills In that comment, you ran `go list [...] all` presumably on Linux or another non-Darwin OS, which did not match the Darwin-only [`golang.org/x/exp/shiny/driver/mtldriver`](https://pkg.go.dev/golang.org/x/exp/shiny/driver/mtldriver) and [`golang.org/x/exp/shiny/driver/mtldriver/internal/coreanim`](https://pkg.go.dev/golang.org/x/exp/shiny/driver/mtldriver/internal/coreanim) packages that import `mtl`.

The `mtl` package is a real dependency of shiny when it is built with <code>-tags [metal](https://github.com/golang/exp/blob/b5a6e247da1035535aefee347e58caf75986052e/shiny/driver/mtldriver_darwin.go#L5)</code> on macOS.
