### ISSUE TITLE
x/exp,x/mobile/gl: build failure on darwin-arm64-11_0-toothrot due to missing OpenGL ES headers

### ISSUE THREAD

**Issue by bcmills** [golang/go#43220]
Note that the build failure here is on an `x/mobile` library, but the failure is observed while building the `x/exp` repo.

[2020-12-15T15:35:30-b5a6e24/darwin-arm64-11_0-toothrot](https://build.golang.org/log/3add507e07cc3b371788528c46a1366a3f8c7489)

```
# golang.org/x/mobile/gl
In file included from /tmp/buildlet/gopath/pkg/mod/golang.org/x/mobile@v0.0.0-20190719004257-d2bd2a29d028/gl/work.go:29:
./work.h:18:10: fatal error: 'OpenGLES/ES2/glext.h' file not found
#include <OpenGLES/ES2/glext.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

CC @golang/release @hyangah

**Comment by dmitshur** [comment]
I missed this and made a duplicate issue #43237. This was fixed, see that issue for details.
