### ISSUE TITLE
x/pkgsite: include package nav links in the Breadcrumb 

### ISSUE THREAD

**Issue by georgehu** [golang/go#43225]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/net/http?tab=versions
 
### What is your user agent?
 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

 
 
 
### Screenshot
 

[breadcrumb](https://user-images.githubusercontent.com/1890868/102383187-2390fb80-3f80-11eb-98e9-f4e19648570d.png)

 
 
### What did you do?
 Clicked on versions in the package view

 
 
 
### What did you expect to see?
 
 Breadcrumb to show 
 Discover Packages > Standard library > net > http > Version go1.15.6 

 
### What did you see instead?

 Discover Packages > Standard library > net > http

**Comment by seankhliao** [comment]
versions isn't a page, and there' no real value in adding it to the breadcrumb where it would obstruct copying th import path.
