### ISSUE TITLE
x/arch: TestObjdumpPowerTestdata failed on ppc64le

### ISSUE THREAD

**Issue by zhsj** [golang/go#43222]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 linux/ppc64le
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="ppc64le"
GOBIN=""
GOCACHE="/home/zhsj/.cache/go-build"
GOENV="/home/zhsj/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="ppc64le"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/zhsj/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/zhsj/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.15"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.15/pkg/tool/linux_ppc64le"
GCCGO="gccgo"
GOPPC64="power8"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/zhsj/t/arch/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build250095372=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

go test -v -run TestObjdumpPowerTestdata

### What did you expect to see?

Succeed.

### What did you see instead?

```
$ go test -v -run TestObjdumpPowerTestdata
=== RUN   TestObjdumpPowerTestdata
    ext_test.go:171: decode(7c230066) = "mfvsrd r3,vs1", 4, want "mffprd r3,f1", 4
    ext_test.go:171: decode(7c230166) = "mtvsrd vs1,r3", 4, want "mtfprd f1,r3", 4
    ext_test.go:171: decode(7c230066) = "mfvsrd r3,vs1", 4, want "mffprd r3,f1", 4
    ext_test.go:171: decode(7c230166) = "mtvsrd vs1,r3", 4, want "mtfprd f1,r3", 4
    ext_test.go:177: 848 test cases, 16 expected mismatches, 4 failures; 38055 cases/second
--- FAIL: TestObjdumpPowerTestdata (0.02s)
```

**Comment by cherrymui** [comment]
What version of the `objdump` command do you use? Thanks.

cc @laboger

**Comment by zhsj** [comment]
```
$ objdump --version
GNU objdump (GNU Binutils for Debian) 2.35.1
Copyright (C) 2020 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```

**Comment by laboger** [comment]
cc @pmur 
This is an extended mnemonic so probably just needs an update to the function allowedMismatchObjdump. In the case shown above both decodings are correct.

**Comment by laboger** [comment]
@cherrymui in what release do you want this fixed?

**Comment by cherrymui** [comment]
The x/arch repo has no versioned release. A fix can be checked in at any time.

In the main repo, the vendored copy of x/arch doesn't include tests, so I think there is nothing to be done there.

**Comment by laboger** [comment]
> The x/arch repo has no versioned release. A fix can be checked in at any time.

I noticed release branches starting with go 1.11  in the arch repo so that's why I was wondering.

**Comment by cherrymui** [comment]
I didn't know we have release branches. Thanks.

For this particular issue, I think it still can be checked in to the master branch at any time, if it is test-only.
