### ISSUE TITLE
x/pkgsite: floating header obscures printout

### ISSUE THREAD

**Issue by rsc** [golang/go#43238]
If you go to a multipage doc like https://pkg.go.dev/github.com/google/go-cmp/cmp and print from Chrome, you can see in the PDF preview that the floating header is printed at the top of every page. Unfortunately, on all but the first page, the floating header is printed **on top of** actual text that would be useful to be able to read.

If I edit the page with Chrome to make the UnixFixedHeader div "display: none" then the printout is fine. So maybe doing that in print-specific CSS would be enough.

**Comment by oiooj** [comment]
Yes, and we should also hide `DocNavMobile`, I'm working on it.

**Comment by rsc** [comment]
Thanks!
