### ISSUE TITLE
https://support.microsoft.com/ru-ru/windows

### ISSUE THREAD

**Issue by yasya1100** [golang/go#43231]
[
[

](url)
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by davecheney** [comment]
Empty issue, closing. 

@yasya1100 if this was unintentional, please open a new issue and complete the template.
