### ISSUE TITLE
x/pkgsite: license not detected for github.com/dennwc/gotrace

### ISSUE THREAD

**Issue by icholy** [golang/go#43267]
MIT license not being detected https://github.com/dennwc/gotrace/blob/master/LICENSE

### What did you do?

Visited: https://pkg.go.dev/github.com/dennwc/gotrace

### What did you expect to see?

The documentation

### What did you see instead?

Documentation not displayed due to license restrictions.

**Comment by seankhliao** [comment]
The license is not part of the `v1.0.1` release

```
* a0f953f (HEAD -> master, origin/master, origin/HEAD) Create LICENSE 1 year, 4 months ago <Denys Smirnov>
* 7cc9f5f (tag: v1.0.1) update readme 2 years ago <Denys Smirnov>
* 8da350b (tag: v1.0.0) add doc comments and fix golint warnings 2 years ago <Denys Smirnov>
* 1a7de00 Initial commit 5 years ago <Denys Smirnov>
```

**Comment by icholy** [comment]
@seankhliao good eye
