### ISSUE TITLE
x/pkgsite: support retractions

### ISSUE THREAD

**Issue by jba** [golang/go#43265]
Beginning with Go 1.16, module authors will be able to _retract_ versions of their modules. The `go` command will ignore retracted versions by default.

pkg.go.dev should expose that a version is retracted.

## UI Ideas

- The page for a retracted version should show that it is retracted, and display the rationale if any.

- In the list of module versions, retracted versions should either be displayed at the bottom, or indicated in some other way (such as a red strikethrough). They shouldn't be hidden, because someone might be using a retracted version and want to visit its page.

- We could show which imported packages are retracted, but that depends on having precise version information about imports (that is, the build list), which we don't currently have.

## Implementation

The proposal for retraction is at https://github.com/golang/go/issues/24031#issuecomment-597263309. In brief: retraction is done by adding `retract` directives in go.mod files. Each directive lists a range of versions and a rationale. Only the latest go.mod file, as defined by the go command's `@latest` query,  is authoritative.

- The modules table should have a column that contains the information in the `retract` directives, perhaps as JSON. The worker parses the go.mod file and populates the column during processing.

- The frontend reads the retractions from the latest version of a module and applies them to the module in the request.

This involves an extra DB query sometimes, but only when viewing a version that is not the latest, which is uncommon.

One wrinkle: the latest version can retract itself. In that case, finding the true latest version (the one that deserves the "LATEST" badge) requires another pass over the list of unretracted versions.

In an alternative design, there is a column `modules.retracted` which gives the state for each version, and the worker populates that for all versions when it is processing the latest one. This involves some subtleties:

- Writing rows other than the current one can result in deadlocks.
- The worker can process versions in any order, so it might see a version in a `retract` directive before it has processed it. Where should it store that information?

The advantages are fewer queries at serving time in some cases, and the ability to query easily for the latest unretracted version.

**Comment by zx2c4** [comment]
Another note on this:

- If all versions have been retracted, then it should display `@master`, mirroring the behavior of `go get`. The idea is that the default page shown on pkgsite should be consistent with what the use will get from a vanilla `go get`.

**Comment by jba** [comment]
@jayconrod, is the behavior above (get `@master` if all versions are retracted) the intended behavior? I couldn't find anything about that case at https://golang.org/ref/mod. How is it implemented in proxy mode?

**Comment by zx2c4** [comment]
Ah, you're right that I misspoke about @master, when I meant default branch.

Based on what you said, this is working as expected:

```
zx2c4@thinkpad ~ $ go version
go version go1.16 linux/amd64
zx2c4@thinkpad ~ $ GOPROXY=direct go list -m golang.zx2c4.com/wireguard@latest
golang.zx2c4.com/wireguard v0.0.0-20210309043227-6005c573e24a
zx2c4@thinkpad ~ $ go list -m golang.zx2c4.com/wireguard@latest
golang.zx2c4.com/wireguard v0.0.0-20210309043227-6005c573e24a
```

The idea would be to mirror this same `@latest` logic into x/pkgsite, so that the documentation shown corresponds.

**Comment by jamalc** [comment]
Here is a mockup of how we'll surface retractions on the versions page.

<img width="425" alt="Screen Shot 2021-04-06 at 11 30 52 AM" src="https://user-images.githubusercontent.com/18269441/113737242-db7f1b80-96cb-11eb-8789-d0f83388ae78.png">

**Comment by jba** [comment]
Retraction support is live.

**Comment by zx2c4** [comment]
Apparently it doesn't see the retractions in https://pkg.go.dev/golang.zx2c4.com/wireguard . The v0.0.20201119 version should retract all others and itself: https://git.zx2c4.com/wireguard-go/tree/go.mod?h=v0.0.20201119

**Comment by jba** [comment]
There's something odd going on. Did you perhaps change a tag?

According to the Go tools, the latest version of your module is indeed v0.0.20201119. But the proxy won't download that version, and here's what happens when I try to get it directly:
```
> GOPROXY=direct go get golang.zx2c4.com/wireguard@v0.0.20201119
go: downloading golang.zx2c4.com/wireguard v0.0.20201119
go get: golang.zx2c4.com/wireguard@v0.0.20201119: verifying module: checksum mismatch
        downloaded: h1:BbmPvlD3yvKCF1ybLUCHD+JYFn3my0MKPY24rJi41bY=
        sum.golang.org: h1:WJ4IKfT3SLG+YbM9aeZlgYB+X7hKzO66GEGBmxJPhjE=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```
The best approach would be to tag a new, later version that has a go.mod with all the desired retractions.

**Comment by zx2c4** [comment]
You're right. I _had_ changed a tag, after I realized that proxy.golang.org won't cache things without at least a single .go file beyond a few days. So that explains that.

Current status is that retractions don't seem to be propagating:

![image](https://user-images.githubusercontent.com/10643/115809896-41b6ae80-a3ed-11eb-8bea-6d73fd48f573.png)

All of those should actually be retracted, per the go.mod file:

![image](https://user-images.githubusercontent.com/10643/115809916-4ed39d80-a3ed-11eb-804e-f346e7d9853a.png)

**Comment by zx2c4** [comment]
It looks like it's still very goofed up:

![image](https://user-images.githubusercontent.com/10643/117139213-434c8300-adac-11eb-8c5f-14569fe9f6ca.png)

It thinks that the most recent commit is https://git.zx2c4.com/wireguard-go/commit/?id=6a128dd which is some random old commit from January, rather than the most recent commit, which is today.

**Comment by jba** [comment]
Sorry for the delay getting back to you.

Your module is an interesting case. You've retracted all the tagged versions, leaving only pseudo-versions. And some of those pseudo-versions, having been landed on top of tagged versions, are technically "later" than the more recent ones you've published. 

Can I suggest tagging the version you want to be latest with a new, higher tag? Tagged versions are definitely the way to go.

**Comment by zx2c4** [comment]
> You've retracted all the tagged versions, leaving only pseudo-versions.

I'm following precisely the suggestion given by the Go team earlier for retracting all versions. Things work perfectly with `go get`. CC @bcmills 

> Can I suggest tagging the version you want to be latest with a new, higher tag? Tagged versions are definitely the way to go.

The project is not yet ready to release a stable version. Therefore no tags are possible at the moment. Rather, the logic in pkgsite is clearly borked, as `go get` does the right thing.

**Comment by jba** [comment]
Agreed, pkgsite has a bug. We'll work on fixing it.

However, tags don't imply stability. You can tag with a major version of zero.

**Comment by jba** [comment]
Actually, I'm not sure that the bug is in pkgsite. Or at least, I don't quite know what the bug is.

To go over the logic again:

Since all the tagged versions are retracted, only the pseudo-versions matter.
Pseudo-versions are ordered by semver.
The most recent pseudo-version begins `v0.0.0`, but an older one has a higher version. The older is in the proxy's index and can be downloaded from the proxy:
```
> go get golang.zx2c4.com/wireguard@v0.0.20201119-0.20210128142622-6a128dde71d9
go: downloading golang.zx2c4.com/wireguard v0.0.20201119-0.20210128142622-6a128dde71d9
go get: upgraded golang.zx2c4.com/wireguard v0.0.0-20210506092213-60a26371f42f => v0.0.20201119-0.20210128142622-6a128dde71d9
```
Note that the `go` command thinks it is "upgrading" the version.

The difference between the `go` command and pkgsite is that the former knows only what the proxy tells it, and the proxy believes that the `v0.0.0` pseudo-version is the latest. I'm not sure why. @heschi @hyangah, is there logic to ignore pseudo-versions derived from retracted tagged versions? More likely, the proxy `@latest` endpoint is just tracking the main/master branch.

Pkgsite has the full history so it "correctly" serves the highest version.

@jayconrod @julieqiu What's the right fix here? Maybe pkgsite should ignore pseudo-versions derived from retracted versions?

**Comment by heschi** [comment]
We just report whatever `go get @latest` says. Based on what you're saying, I presume that retracted versions no longer serve as pseudoversion bases, so after the `20201119` tag was retracted the pseudoversions "downgraded".

As I think we've discussed elsewhere, AFAIK the only way to know for sure what the "latest" version is is to ask the `go` command each time.

**Comment by bcmills** [comment]
>  Based on what you're saying, I presume that retracted versions no longer serve as pseudoversion bases, so after the `20201119` tag was retracted the pseudoversions "downgraded".

That is correct. Ideally, when you retract an erroneous release version you should also retract the range of pseudo-versions derived from that release, although in some sense those pseudo-versions were never “released” to begin with.

**Comment by jba** [comment]
This should be fixed. https://pkg.go.dev/golang.zx2c4.com/wireguard shows a version published on May 13, a few days ago. Reopen if there are still problems.
