### ISSUE TITLE
x/website: Mention specifically that minor version is not allowed in Go directives

### ISSUE THREAD

**Issue by sagar-jadhav** [golang/go#43262]
I was trying out `Go` modules and find out that If I specify `1.15.4` instead of `1.15` my build failed with the following error:

```
invalid go version '1.15.4': must match format 1.23
```

I referred to this documentation https://golang.org/ref/mod#go-mod-file-go. I think it will be better If we also recommend not to use the minor version or give examples of the wrong values for better understanding.

**Comment by ALTree** [comment]
It does say

> **a positive integer followed by a dot and a non-negative integer** (for example, 1.9, 1.14)

which I think is pretty clear on the allowed format "an integer, a dot, another integer, that's it". The error you received on the bad version string is also very easy to understand: 

> 1.15.4': must match format 1.23

I'm not sure we need to make the explanation longer, and in general "bad" examples (like "DO NOT DO THIS, IT'S INVALID: `1.14.7`) are not great (you need to make it really clear that it's a bad example, which is often verbose, only presenting valid examples is generally preferable, IMO).

**Comment by sagar-jadhav** [comment]
@ALTree I agree with your explanation.

**Comment by ALTree** [comment]
Closing here then.
