### ISSUE TITLE
x/net/html: Text() corrupts underlying tokenizer buffer

### ISSUE THREAD

**Issue by Max-1892** [golang/go#43268]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1c/p7qvswhs13gbxtq6j5lqybp40000gn/T/go-build012787672=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I just wanted to verify the intent of the tokenizer interface. According to the documentation for `Raw`,

> Raw returns the unmodified text of the current token. Calling Next, Token, Text, TagName or TagAttr may change the contents of the returned slice.

In the case of escaped characters, in [this example](https://play.golang.org/p/DXFXCZR8RQH), I notice the underlying buffer returned by `Raw` gets partially updated after a call to `Text` with the unescaped version of the character but parts of the escaped character still exist. For example, if the original buffer was `a&lt;b`, after a call to `Text()`, the buffer looks like `a<bt;b`. This behavior seems correct according to the documentation but I wanted to verify this is consistent with the intent of `Raw`. It seems to limit the usefulness of `Raw` when used with `Next` and `Text`.

### What did you expect to see?
I was hoping to see the escaped character completely replaced in the underlying buffer returned by `Raw()` (`a<b`).

### What did you see instead?
The underlying buffer looks like `a<bt;b`.

**Comment by slrz** [comment]
How would that work? You'd have to update the slice's length which the example stashes away in a local variable.

**Comment by Max-1892** [comment]
Would it be useful to expose what parts of `Raw` are 'valid' (`z.raw.start` and `z.raw.end`) via additional methods?

**Comment by nigeltao** [comment]
> This behavior seems correct according to the documentation but I wanted to verify this is consistent with the intent of `Raw`.

This is working as intended.

If you want `"a&lt;b"`, call `Raw`.

If you want `"a<b"`, call `Text`.

If you want both, call `Raw`, copy the `[]byte` to your own buffer, then call `Text`.


> Would it be useful to expose what parts of `Raw` are 'valid' (`z.raw.start` and `z.raw.end`) via additional methods?

I don't understand the proposal. If you want `"a<b"` then it's not 'raw' *unmodified* text. The `"&lt;"` escape code has been 'cooked' to be `"<"`.
