### ISSUE TITLE
x/website: golang.org blocked from Sudan

### ISSUE THREAD

**Issue by mustafa678** [golang/go#43277]
I can't open the main website https://golang.org from Sudan. This was for political reasons I think they no longer apply to Sudan. Please remove the restrictions so that Sudanese people join the go comunity.

**Comment by ALTree** [comment]
cc @dmitshur

**Comment by dmitshur** [comment]
CC @golang/release.

**Comment by rsc** [comment]
golang.org's availability in Sudan is controlled solely by Google's overall posture, which is based on complying with relevant international laws, regulations, and so on. It's not something we on the Go team have any control over. My apologies.
