### ISSUE TITLE
cmd/compile: panic.Fatalf should not report "use of builtin panic not in function call" but instead "panic.Fatalf undefined (builtin panic has no field or method Fatalf)"

### ISSUE THREAD

**Issue by odeke-em** [golang/go#43285]
### What version of Go are you using (`go version`)?
At pre-Go1.16 on tip 55b58018f41e6de63bdaa8f3d9a284077d4e88c1

### Does this issue reproduce with the latest release?
Yes

### What did you do?
, running this code https://play.golang.org/p/akRcEUKPrTA  or inlined below
```go
package main

func main() {
	panic.Fatalf("foo")
}
```

### What did you expect to see?
```shell
panic.Fatalf undefined (builtin panic has no field or method Fatalf)
```

### What did you see instead?
```shell
use of builtin panic not in function call
```
which would be similar to panic being present on a line but without any invocation https://play.golang.org/p/35T1E3Xttpp or
```go
package main

func main() {
	panic
}
``` 
```shell
./prog.go:4:2: use of builtin panic not in function call
```

**Comment by choleraehyq** [comment]
How to figure out whether an error message is wrong? There is no specification about it. IMHO the current error message is not confused.

**Comment by mdempsky** [comment]
I think either error message is fine here. However, go/types reports the requested error message, so this will likely change once we adopt types2 anyway.

**Comment by odeke-em** [comment]
In Go1.23 given
```go
package main

func main() {
	panic.Fatalf("foo")
}
```
produces
```shell
cannot select on panic (built-in)
```

That's a much more mysterious message sine we've adopted types2.

**Comment by griesemer** [comment]
I'll fix the error message.

**Comment by odeke-em** [comment]
Thank you @griesemer and long time!
