### ISSUE TITLE
cmd/compile: runtime panic due to bad devirtualization

### ISSUE THREAD

**Issue by mdempsky** [golang/go#43292]
This program should run without crashing, but currently panics at tip:

```
package main

type I interface { M() chan int }

type A int
func (A) M() chan int { return nil }

type B int
func (B) M() chan int { return nil }

func main() {
	c := I(A(0))

	b := make(chan I, 1)
	b <- B(0)

	for i := 0; i < 2; i++ {
		select {
		case c = <-b:
		case <-c.M():
		default:
		}
	}
}
```

Based on test case reported by @kivikakk in #42284.

**Comment by mdempsky** [comment]
The issue is `reassigned` doesn't check for `OSELRECV`/`OSELRECV2`.

**Comment by mdempsky** [comment]
We weren't checking `OAS2RECV` either. :(

**Comment by mdempsky** [comment]
@kivikakk I believe CL 279352 should fix your issue. Can you try testing that for me please?

In case you're not familiar with Gerrit, the procedure to fetch and checkout the change locally are:

```
git fetch https://go.googlesource.com/go refs/changes/52/279352/1
git checkout FETCH_HEAD
```

(Other options are available if you click the "DOWNLOAD" link at golang.org/cl/279352, but they all amount to fetching that commit ref and then using some git command.)

**Comment by kivikakk** [comment]
Fetching and compiling now, will report back shortly 👍

**Comment by kivikakk** [comment]
Success! The use case I reported in #42284 no longer panics:

```console
$ ~/Code/go/bin/go version
go version devel +00468b24ae Sun Dec 20 01:16:30 2020 -0800 darwin/arm64
$ ~/Code/go/bin/go run main.go
2020/12/20 20:41:45 online
```

**Comment by mdempsky** [comment]
@kivikakk Great, thank you for confirming, and again for the report! I've submitted the fix. Cheers.
