### ISSUE TITLE
x/tools/go/ast/astutil: DeleteImport leaves behind inline comments

### ISSUE THREAD

**Issue by zhengxiaowai** [golang/go#43291]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hexiangyu.shawn/Library/Caches/go-build"
GOENV="/Users/hexiangyu.shawn/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/hexiangyu.shawn/go/pkg/mod"
GONOPROXY="*.byted.org,*.everphoto.cn"
GONOSUMDB="*.byted.org,*.everphoto.cn"
GOOS="darwin"
GOPATH="/Users/hexiangyu.shawn/go"
GOPRIVATE="*.byted.org,*.everphoto.cn"
GOPROXY="https://go-mod-proxy.byted.org,https://goproxy.cn,https://proxy.golang.org,direct"
GOROOT="/Users/hexiangyu.shawn/go/go1.15.5"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/Users/hexiangyu.shawn/go/go1.15.5/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/hexiangyu.shawn/larkcode/astcommon/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5t/nnz47qfs67q03v3nn_5kv45m0000gn/T/go-build873978903=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

i try use astutil.DeleteImport to delete a  import spec, just like：

```golang
import (
    "git.xxx.xxx/xx/other" 
    "git.xxx.xxx/xx/common" // i am a common package
)
```

i want to delete import "git.xxx.xxx/xx/common" with comment, but i got it:

```golang
import (
    "git.xxx.xxx/xx/other" 
    // i am a common package
)
```

### What did you expect to see?

```golang
import (
    "git.xxx.xxx/xx/other" 
)
```

### What did you see instead?

```golang
import (
    "git.xxx.xxx/xx/other" 
    // i am a common package
)
```

i check `golang.org/x/tools/go/ast/astutil/import_test.go`,  it's same my test.

So，i has a question:

why did delete a import spec which not contain comment？

this Comment Field belong to ast.ImportSpec in source ccode：

```golang
// An ImportSpec node represents a single package import.
ImportSpec struct {
    Doc     *CommentGroup // associated documentation; or nil
    Name    *Ident        // local package name (including "."); or nil
    Path    *BasicLit     // import path
    Comment *CommentGroup // line comments; or nil
    EndPos  token.Pos     // end of spec (overrides Path.Pos if nonzero)
}
```

i think delete a import spec which should delete a full ImportSpec (about comment)

why was it designed this way? 

Looking forward to your reply, Thanks.

**Comment by dmitshur** [comment]
This behavior doesn't reproduce for me, see https://play.golang.org/p/Ih5e7bjhbNp.

Did you provide the `*token.FileSet` parameter to `astutil.DeleteImport`?

If this problem still happens for you, please include a minimal program to reproduce it.
