### ISSUE TITLE
runtime: uninterruptible hang on os.Exit on darwin/arm64

### ISSUE THREAD

**Issue by aep** [golang/go#43294]
- go version go1.16beta1 darwin/arm64
- macos bigsur 11.1 arm64

### What did you do?

unfortunately i cant find a small reproducible example yet, or a root cause. 
maybe someone has an idea where to dig further.

the program calls C code. when commenting out the C calls, the issue does not appear.
It also does not appear on any other platform, including intel macosx

### What did you expect to see?

when main() exits, the program should exit immediately

### What did you see instead?

the last line in main() is executed (printf) but program wont exit for several seconds.

attempting to interrupt the program AFTER main exited using lldb will make lldb hang as well until the program finally exits and lldb just prints the exit code. pkill doesnt work either. 

Interrupting the program BEFORE exiting main, works just as expected.

i'm not used to debugging macos. on linux, you can attach a syscall tracer to see which syscall is blocking, but dtrace doesnt work for me (no output). Maybe someone has an idea what runs after main and how to see it in lldb

calling os.Exit anywhere, leads to the same behaviour, so this is not a defer issue. even panic() hangs

lldb is unable to read golangs debug symbols, so the best i came up with for a breakpoint was using runtime.Breakpoint, but i cant step over it to the next instruction. i'll just forever repeat the breakpoint.

**Comment by cherrymui** [comment]
Could you try if patching in CL https://go-review.googlesource.com/c/go/+/269378 helps? Thanks.

**Comment by aep** [comment]
building from source is unclear. the instructions do not work https://golang.org/doc/install/source

    GOARCH=arm64 ./make.bash

yields an x86_64 binary that only builds for x86_64

either way, using that binary, the issue is not solved. 

i dont think the fix is relevant anyway, since there aren't any atexit functions registered in my case.

**Comment by cherrymui** [comment]
Is it possible to share the source code of a reproducer?

**Comment by aep** [comment]
its open source, but i couldnt find a good small reproducable example yet.

```
git clone https://github.com/devguardio/carrier.git
cd carrier/cli/
go build -a
./cli identity
./cli net trace
```

the last command will hang for a few seconds after being successful, but only on macos big sur

**Comment by cherrymui** [comment]
Hmmm, I cannot reproduce.
```
% time ./cli identity
cDEXIP6HRNN7VV4R5TGZXNZ2XRZYXECD2LQHYBBS5F5RP3N3C6ZAZSCI
./cli identity  0.02s user 0.01s system 91% cpu 0.041 total
% time ./cli net trace
conduit.go:112: bootstrap
[WRN] carrier::endpoint timeout waiting for broker response
conduit.go:184: started broker con
[WRN] carrier::endpoint timeout waiting for broker response
conduit.go:184: started broker con
[WRN] carrier::endpoint timeout waiting for broker response
conduit.go:184: started broker con
conduit.go:53: started conduit
{
  "publishers": 0,
  "bytes_sent_per_epoch": 0,
  "bytes_recv_per_epoch": 0,
  "bytes_sent_per_second": 0,
  "bytes_recv_per_second": 0
}
conduit.go:60: stopping conduit
conduit.go:77: stopped conduit
./cli net trace  0.06s user 0.03s system 11% cpu 0.746 total
```

It exits quite quickly.

**Comment by aep** [comment]
yeah, network wasnt available, so it didnt do anything. 
let me try to reduce to a test without network

**Comment by aep** [comment]
i believe this is a bug in macos big sur.
simply sending packets slower makes the issue go away. It might be that something is waiting for network responses on behalf of the program, even though it has already closed the socket. 

i dont understand why this only happens when using C code inside golang, but i suspect its some sort of security thing that classifies golang programs differently. Or maybe its just because golang uses much more memory and causes a bug in some memory mapping.

Either way, this seems unlikely to be **caused** by golang, so i'm closing this.

**Comment by cherrymui** [comment]
Thanks for the investigation.

If you think Go uses more memory (or other resources) than it should, feel free to reopen or file a new bug. Thanks.
