### ISSUE TITLE
x/mobile: binary generated by gomobile contains _ptrace which is a private API banned by Apple iOS

### ISSUE THREAD

**Issue by libnat** [golang/go#43302]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/justintan/Library/Caches/go-build"
GOENV="/Users/justintan/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOOS="darwin"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cb/qs941gzn0sn5t40hb_5_cmqw0000gp/T/go-build437714881=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
<pre>
GO111MODULE=off gomobile bind -v -ldflags="-s -w" -target=ios mypackage
</pre>
It will generate an iOS framework. Then I submitted an iOS APP built with this framework to Apple Store for review. Got rejected because of using private API _ptrace. 
I use `nm` to scan this package, found mypackage generated by gomobile contains `_ptrace`
<pre>
Mypackage:go.o:                  U _ptrace
Mypackage:go.o: 0000000000080d00 t _syscall.libc_ptrace_trampoline
Mypackage:go.o: 0000000000ad4a40 s _syscall.libc_ptrace_trampoline.args_stackmap
</pre>

Perhaps this issue is caused by go, not x/mobile.

If `exec.Command("ls").Run()` is contained in my package or dependencies, `_ptrace` can be found in the binary. I am not sure if this is the only reason. 
<pre>
import "os/exec"
// ...
exec.Command("ls").Run()
</pre>

### What did you expect to see?
No `_ptrace` in the iOS binary generated by gomobile, so our APP can pass AppleStore's checking.

### What did you see instead?
`_ptrace` can be found in the iOS binary generated by gomobile

**Comment by cherrymui** [comment]
> go version go1.15.6 darwin/amd64

@libnat are you sure you're using Go 1.15.6? Thanks.

The CL above should fix this for Go 1.16. But I don't think Go 1.15 has this problem.

**Comment by libnat** [comment]
@cherrymui Thanks for your reply.
I did install Go 1.16 beta. Once the binary got rejected by Apple, I removed Go 1.16 beta, and dir: ~/go/bin ~/go/pkg.
Then I installed Go 1.15.6 again, built gomobile/gobind with Go 1.15.6. I tried several times, but still got this issue.
