### ISSUE TITLE
x/tools/gopls: improve presentation of package loading failure caused by cgo errors

### ISSUE THREAD

**Issue by hyangah** [golang/go#43307]
gopls: v0.6.1

I encountered a repo that uses `cgo` and requires tools (e.g.`pkg-config`, ...) and correct configuration to build `cgo`. 
Loading packages took a while and eventually failed because of my incomplete configuration. The `PROBLEMS` (diagnostics) section is flooded with hundreds of errors related to cgo types

![Screen Shot 2020-12-21 at 3 36 39 PM](https://user-images.githubusercontent.com/4999471/102819901-5719be80-43a2-11eb-807b-a9a929cb0a6a.png)

I could find the reasons from the `gopls (server)` trace channel of vscode. But it would be better to expose these error in the diagnostics page or with other means. Also, consider suppressing all the cgo-related type errors when the root cause is obvious. Finding the root cause out of hundreds of type errors seems impossible.

```
[Error - 3:28:30 PM] 2020/12/21 15:28:30 initial workspace load failed: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin github.com/some/repo/...]: exit status 2: go: downloading golang.org/x/net v0.0.0-20201031054903-ff519b6c9102
go: downloading github.com/stretchr/testify v1.6.1
...
go: downloading golang.org/x/text v0.3.4
# pkg-config --cflags  -- vips vips vips vips vips vips vips vips vips vips vips vips vips vips
pkg-config: exec: "pkg-config": executable file not found in $PATH
# pkg-config --cflags  -- vips vips vips vips vips vips vips vips vips vips vips vips vips vips
pkg-config: exec: "pkg-config": executable file not found in $PATH
```

**Comment by stamblerre** [comment]
Was the `go list` error shown at the bottom of the screen? If not, that definitely seems like a problem.

**Comment by hyangah** [comment]
No. I don't see any `go list` error message outside the gopls server trace.

Also,  tried `regenerate cgo definitions` codelens. There was no visible change or error message, which needs improvement.

```
[Trace - 16:54:37.207 PM] Sending request 'workspace/executeCommand - (19)'.
Params: {"command":"gopls.regenerate_cgo","arguments":["file:///work/govips/vips/arithmetic.go"]}


[Trace - 16:54:37.209 PM] Received request 'window/workDoneProgress/create - (6)'.
Params: {"token":"6129484611666145821"}


[Trace - 16:54:37.211 PM] Sending response 'window/workDoneProgress/create - (6)' in 1ms.
Result: 


[Trace - 16:54:37.211 PM] Received notification '$/progress'.
Params: {"token":"6129484611666145821","value":{"kind":"begin","title":"Regenerate cgo","cancellable":true,"message":"Running..."}}


[Trace - 16:54:37.218 PM] Received notification '$/progress'.
Params: {"token":"6129484611666145821","value":{"kind":"end","message":"gopls.regenerate_cgo: completed"}}


[Trace - 16:54:37.218 PM] Received response 'workspace/executeCommand - (19)' in 10ms.
Result: null

```

I happened to try `github.com/davidbyttow/govips` but  we can create a minimal repro for testing.

**Comment by stamblerre** [comment]
I have a CL to make the error message pop-up, but this also looks like a regression in #36770. Reopened that issue.
