### ISSUE TITLE
x/tools/cmd/godoc: handle file name arguments better, particularly w.r.t. GOPATH

### ISSUE THREAD

**Issue by robpike** [golang/go#4330]
<pre>Summary: If a package is present on GOPATH, godoc should find it, perhaps only after
failing to find it in GOROOT.

I believe there are a number of related problems here, hard to tease out. The exact
meaning of the arguments to godoc is not well documented, which is part of it.

But the key point is that godoc is too aggressive about resolving those
&quot;names&quot; inside $GOROOT even if $GOPATH is set, or even if it's not. On the
command line at least, godoc seems to disregard GOPATH completely.

Example (Ignore the fact my documentation is missing and just observe how godoc behaves):

% cd
% echo $GOROOT
/Users/r/go
% echo $GOPATH
/Users/r
% 
% cd rspace.cmd
/Users/r/src/code.google.com/p/rspace.cmd  # IN GOPATH
% ls
AUTHORS		LICENSE		codereview.cfg	now		typo
CONTRIBUTORS	README		freq		translate	unicode
% godoc now  # WHY DOESN'T THIS WORK?
2012/11/01 12:52:06 open /Users/r/go/src/pkg/now: no such file or directory  # TRUE BUT
&quot;now&quot; EXISTS IN THIS DIRECTORY AND/OR ON GOPATH
% godoc ./now # THIS DOES WORK, BUT IS FUSSY.
PACKAGE

package main
    import &quot;./now&quot;

tubenose=% godoc ./unicode
PACKAGE

package main
    import &quot;./unicode&quot;

% cd  # BACK HOME
% godoc now
2012/11/01 12:53:57 open /Users/r/go/src/pkg/now: no such file or directory  # WHAT
ABOUT GOPATH?
tubenose=% godoc /Users/r/src/code.google.com/p/rspace.cmd/now/ # GIVE FULL PATH AND IT
WORKS
PACKAGE

package main
    import &quot;/Users/r/src/code.google.com/p/rspace.cmd/now/&quot;

%</pre>

**Comment by adg** [comment]
Now that we have `go doc` I don't think this is worth addressing.
