### ISSUE TITLE
C  code failed to compile

### ISSUE THREAD

**Issue by mariavarg** [golang/go#43309]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by davecheney** [comment]
Please complete the issue template

**Comment by mariavarg** [comment]
check50 cs50/problems/2020/x/mario/less
#include <cs50.h>

#include <stdio.h>

int main(void)

 {
     int n;
do
{
    n = get_int("Height: ");
}
while (n < 8 && n > 1);
  for (int i = 0; i < n; i++)
  {
      for (int j = 0; j < n; j++)
      {
          if ( i + j < (n-1))
          printf("  ");
          else
          printf("#");
          printf(" \n");
  }
  }

**Comment by davecheney** [comment]
What did you do?

what did you see when you did it?

**Comment by davecheney** [comment]
There isn’t any Go code here, how is this problem related to Go

**Comment by mariavarg** [comment]
suggestions not at all?

**Comment by davecheney** [comment]
I’d this problem is unrelated to the use of CGO then it is likely you have raised your issue in the wrong place. Please explain how your problem related to Go or close this issue. Thank you
