### ISSUE TITLE
How can I force to use specific package version while running go mod download?

### ISSUE THREAD

**Issue by shreeharsha-factly** [golang/go#43300]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.13
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOOS="darwin"
GOARCH="amd64"
</pre></details>

### What did you do?

go.mod file
```
go 1.13

require (
  ...
  gorm.io/gorm v1.20.5
) 
```
 when I just run go mod download then packages in my go.mod file upgrades automatically even after I specified a version.

### What did you expect to see?

```
go 1.13

require (
  ...
  gorm.io/gorm v1.20.5
) 
```

### What did you see instead?
```
go 1.13

require (
  ...
  gorm.io/gorm v1.20.7
) 
```
How can I stop this upgrade while running go mod download?

**Comment by mdlayher** [comment]
Please see https://github.com/golang/go/wiki/Questions.
