### ISSUE TITLE
 Class AMSupportURLConnectionDelegate is implemented in both ??

### ISSUE THREAD

**Issue by adam-lee** [golang/go#43318]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +bc7e4d9257 Mon Dec 21 21:48:47 2020 +0000 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes. Just did `git pull`.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ uname -a
Darwin M1 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 arm64
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/adam/Library/Caches/go-build"
GOENV="/Users/adam/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/adam/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/adam/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="devel +bc7e4d9257 Mon Dec 21 21:48:47 2020 +0000"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0d/lxlj8q611gv3myfyq2dq6l6c0000gn/T/go-build8557189=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
$ sudo codesign -s - /opt/go/bin/*
```

### What did you expect to see?

No errors about `AMSupportURLConnectionDelegate` and `AMSupportURLSession`.

### What did you see instead?
```
$ sudo codesign -s - /opt/go/bin/*
objc[49507]: Class AMSupportURLConnectionDelegate is implemented in both ?? (0x1f721f8f0) and ?? (0x113fa02b8). One of the two will be used. Which one is undefined.
objc[49507]: Class AMSupportURLSession is implemented in both ?? (0x1f721f940) and ?? (0x113fa0308). One of the two will be used. Which one is undefined.
```

**Comment by mdlayher** [comment]
It isn't clear to me what you are actually trying to do. Is this problem related to Go? Are you trying to sign binaries produced by the Go compiler?

**Comment by cherrymui** [comment]
I don't think this has anything to do with Go. I've seen this message when running non-Go commands like `cc` or `git`. (The message doesn't stop the command from succeeding, though.)

**Comment by adam-lee** [comment]
I'm updating Go on my Apple Silicon (M1) system. If this is unrelated to
Go, and has more to do with Xcode, please close it. Thank you!
