### ISSUE TITLE
x/pkgsite: sbecker59/statuspage-api-client-go

### ISSUE THREAD

**Issue by sbecker59** [golang/go#43319]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/sbecker59/statuspage-api-client-go/api/v1/statuspage
 
### What did you expect to see?
 
My development is not yet complete. I wanted to create a 0.x release and not a 1.x. It is a mistake

**Comment by julieqiu** [comment]
Do you want us to remove this package entirely?

Per https://go.dev/about#removing-a-package:

> we can only remove a module entirely from the site. We cannot remove it just for specific versions.

**Comment by sbecker59** [comment]
Please remove packages :

v1 – github.com/sbecker59/statuspage-api-client-go
v1.0.5 – Dec 21, 2020
v1.0.4 – Dec 21, 2020
v1.0.3 – Dec 21, 2020
v1.0.2 – Dec 21, 2020
v1.0.1 – Dec 12, 2020
v1.0.0 – Dec 12, 2020

v0 – github.com/sbecker59/statuspage-api-client-go
v0.1.0 – Dec 21, 2020

**Comment by julieqiu** [comment]
Done. https://pkg.go.dev/github.com/sbecker59/statuspage-api-client-go now shows a 404.
