### ISSUE TITLE
x/tools/gopls: add "if err != nil" snippet completion for Test/Benchmark Functions

### ISSUE THREAD

**Issue by marwan-at-work** [golang/go#43310]
One of my favorite features of Gopls is that it can auto-complete my error returns by writing a contextual if-statement block like so:

```golang
if err != nil {
  return <zero types>, ${1:err}
}
``` 

It accomplishes the above by doing the following:

1. Checks if the enclosing function's signature returns an error 
2. Checks if the cursor's previous statement assigns an error. 
3. Offers an auto-complete snippet that writes out the entire block above.

The main logic of this feature lives here: https://github.com/golang/tools/blob/1965356128881de7178c4c0a1cbeb15035659dea/internal/lsp/source/completion/statements.go#L175

I propose that we update this function to include the following use case (that I find myself running into a lot): 

```golang
func TestSomeLogic(t *testing.T) {
  _, err := os.Open("foo")
  <>
}
```

If the client asked for completion at the previous cursor, we should offer the following completion: 

```golang
if err != nil {
  t.Fatal(err)
}
```

#### Reasoning:

Writing `if err != nil { t.Fatal(err) }` is quite common.

Quickly searching for the statement in popular repos I found that in the `x/tools` repository, this exact block appears about **393** times: 

<img width="407" alt="Screen Shot 2020-12-21 at 4 35 59 PM" src="https://user-images.githubusercontent.com/16294261/102824396-bf6c9e00-43aa-11eb-859f-9050b9c9c100.png">

While, in the `moby/moby` repository, it appears 749 times: 

<img width="408" alt="Screen Shot 2020-12-21 at 4 36 16 PM" src="https://user-images.githubusercontent.com/16294261/102824598-2ee28d80-43ab-11eb-9c4e-ff9c3e69ce30.png">

Therefore, having this auto-completion will make Go developer's write tests more quickly when they need it. 

In the future, more clever UX can be sketched out that will handle other common scenarios such as `Fatalf` but I believe as an initial implementation, t.Fatal(err) is a really good start and perhaps good enough.

**Comment by eyJhb** [comment]
Sorry for digging this issue up @marwan-at-work , but I am trying really hard to get this autocompletion to work. I have tried in Emacs with lsp-mode, VS Code with the `Go` extension and vim with coc.nvim.

I am using the latest gopls, and it seems to work fine, but i never get the autocomplete from gopls, to automatically insert the return values, ie.

```
package foo

func bar() error {
    _, err := ioutil.ReadFile("somefile")
    iferr<tab>
}
```

I am unsure what to do, for gopls to get triggered to give me these suggestions. Can you tell me what your setup is, and how you actually get the autocomplete?

Sorry for using improper channels.
