### ISSUE TITLE
go1.16beta1: Running go application with go run returns a runtime error.

### ISSUE THREAD

**Issue by rbo13** [golang/go#43320]
Hi, feel free to close this issue if this is a duplicate. I have encountered an error running my sample application with an initial go code.

This is my sample go code:
```go
package main

import "fmt"

func main() {
	fmt.Println("Hello, World!")
}
```

### What version of Go are you using (`go version`)?

<pre>
$ go version
$ go version go1.16beta1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Not sure.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/bito/Projects/dev/go/bin"
GOCACHE="/home/bito/.cache/go-build"
GOENV="/home/bito/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/bito/Projects/dev/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/bito/Projects/dev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16beta1"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/bito/Projects/dev/go/src/github.com/rbo13/hello-world/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4152057781=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Create a sample application, and run the application using `go run` command. Here is the [link](https://play.golang.org/p/xY2BPIIxBbk) of my sample code.

### What did you expect to see?
```
$ Hello, World
```

### What did you see instead?
```
$ go run main.go
# runtime
/usr/local/go/src/runtime/mgcsweepbuf.go:87:80: memstats.gc_sys undefined (type mstats has no field or method gc_sys)
/usr/local/go/src/runtime/mgcsweepbuf.go:106:102: memstats.gc_sys undefined (type mstats has no field or method gc_sys)
```

I did not encounter this issue when I was using `go 1.15` version.

**Comment by egonelbre** [comment]
Did you delete previous installation of Go before installing go1.16beta1? `mgcsweepbuf.go` does not exist in Go 1.16 codebase.

**Comment by bcmills** [comment]
If you are building the Go distribution from source, you may need to run `git clean -df` prior to `make.bash`.

**Comment by rbo13** [comment]
> Did you delete previous installation of Go before extracting go1.16beta1? `mgcsweepbuf.go` does not exist in Go 1.16 codebase.

No, I did not. Do I need to delete the previous installation first?

**Comment by egonelbre** [comment]
@rbo13 Yes, see the first line in https://golang.org/doc/install#install.

**Comment by rbo13** [comment]
> @rbo13 Yes, see the first line in https://golang.org/doc/install#install.

Oops, my bad. Didn't notice it. Will try it and see if it fixes the issue.

**Comment by rbo13** [comment]
Now works will close the issue. Sorry for the trouble. Didn't notice to delete the previous installation of go. Thanks for the help @egonelbre :+1:
