### ISSUE TITLE
x/tools/gopls: investigate why a pkgName has an Imported *types.Package with missing dependency

### ISSUE THREAD

**Issue by stamblerre** [golang/go#43339]
The new -mod=readonly changes have affected the behavior of unimported completions, leading to some strange behavior. Here's an example of the problem:

1. Create a new module. github.com/yuin/goldmark is already in your local module cache, but not in the `go.mod` file of the module.
2. Create a `main.go` file and start typing `goldmark`. You will see a completion for `goldmark` suggested.

<img width="1070" alt="Screen Shot 2020-12-23 at 2 11 38 AM" src="https://user-images.githubusercontent.com/5856771/102969729-35b0f380-44c4-11eb-9f15-67ef41d7d07c.png">

3. Accept the completion and add a `.` to trigger a subsequent completion.

<img width="678" alt="Screen Shot 2020-12-23 at 2 12 59 AM" src="https://user-images.githubusercontent.com/5856771/102969825-62650b00-44c4-11eb-9ccb-7a1f1eea91bd.png">

4. See no results because the new package has not yet been added to the `go.mod` file. However, no diagnostic is shown on the import because the file is still unsaved.

5. Typing any characters, even if they are incorrect, will cause the diagnostic to show up.
<img width="456" alt="Screen Shot 2020-12-23 at 2 15 53 AM" src="https://user-images.githubusercontent.com/5856771/102970040-cb4c8300-44c4-11eb-9faf-b9c09a7b722f.png">

Also, note that `goimports` works fine without the require in the `go.mod` file, but unimported completions fail in the specific case of an accepted unimported package completion followed by a `.` -- saving the file as-is causes the diagnostic to appear, but it does not cause unimported completions to appear.

/cc @findleyr @heschik

**Comment by myitcv** [comment]
This is roughly the same scenario I mentioned when discussing automatically accepting changes to `go.mod` in the context of `govim`. Because my argument is that accepting of the completion in step 3 is tantamount to automatically accepting that the requirement should be added to your `go.mod` (with an implied local `@latest`, because it's not guaranteed to be the real `@latest`)

**Comment by stamblerre** [comment]
IMO, the fixes needed here are to (1) show the diagnostic on the unsaved file (and figure out why it's not showing up), and (2) to make sure that unimported completions work even if the module has not yet been added to the `go.mod` file.

**Comment by stamblerre** [comment]
I'm not able to reproduce this simply in the playground so this may take some more investigation: https://play.golang.org/p/7NupO_XLpKX.

**Comment by stamblerre** [comment]
My mistake--it actually is reproducible with a simple example: https://play.golang.org/p/j5y5HtJ8Afm. Looks like this is WAI.
