### ISSUE TITLE
regexp: Repeated capture groups only capturing final captured match.

### ISSUE THREAD

**Issue by dwedul-figure** [golang/go#43332]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/danielwedul/Library/Caches/go-build"
GOENV="/Users/danielwedul/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/danielwedul/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/danielwedul/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/px/yz_xp7wj195g7n9k2h4dxp8w0000gp/T/go-build197526322=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://play.golang.org/p/qR9DDyTkvf0

### What did you expect to see?

<pre>
Regex: [^(A+B+)+$]
input: [ABAABBAAABBB].
FindStringSubmatch - Expected: [ABAABBAAABBB AB AABB AAABBB]
FindStringSubmatch -   Actual: [ABAABBAAABBB AB AABB AAABBB]
FindStringSubmatchIndex - Expected: [0 12 0 2 2 6 6 12]
FindStringSubmatchIndex -   Actual: [0 12 0 2 2 6 6 12]
FindAllStringSubmatch - Expected: [[ABAABBAAABBB AB] [ABAABBAAABBB AABB] [ABAABBAAABBB AAABBB]]
FindAllStringSubmatch -   Actual: [[ABAABBAAABBB AB] [ABAABBAAABBB AABB] [ABAABBAAABBB AAABBB]]
FindAllStringSubmatchIndex - Expected: [[0 12 0 2] [0 12 2 6] [0 12 6 12]]
FindAllStringSubmatchIndex -   Actual: [[0 12 0 2] [0 12 2 6] [0 12 6 12]]
</pre>

### What did you see instead?

<pre>
Regex: [^(A+B+)+$]
input: [ABAABBAAABBB].
FindStringSubmatch - Expected: [ABAABBAAABBB AB AABB AAABBB]
FindStringSubmatch -   Actual: [ABAABBAAABBB AAABBB]
FindStringSubmatchIndex - Expected: [0 12 0 2 2 6 6 12]
FindStringSubmatchIndex -   Actual: [0 12 6 12]
FindAllStringSubmatch - Expected: [[ABAABBAAABBB AB] [ABAABBAAABBB AABB] [ABAABBAAABBB AAABBB]]
FindAllStringSubmatch -   Actual: [[ABAABBAAABBB AAABBB]]
FindAllStringSubmatchIndex - Expected: [[0 12 0 2] [0 12 2 6] [0 12 6 12]]
FindAllStringSubmatchIndex -   Actual: [[0 12 6 12]]
</pre>

**Comment by ianlancetaylor** [comment]
I'm not really sure what to say except that that isn't how it works.  The number of subexpressions of a regexp is fixed by the definition of the regexp.  It does not depend on the input string.

**Comment by dwedul-figure** [comment]
Sorry. I could have sworn that that was how it worked in some other languages. I just tested it in Perl, though, and I am mistaken.
