### ISSUE TITLE
x/tools/gopls: removing dependencies with `go get path@none` adds all indirect dependencies

### ISSUE THREAD

**Issue by stamblerre** [golang/go#43335]
We are currently using `go get <module path>@none` to remove unused dependencies. However, this command also adds all of the given `<module path>`'s dependencies as indirect dependencies to the current module.

@bcmills, @jayconrod, @matloob: Is there a way to avoid this?

/cc @heschik @findleyr

**Comment by bcmills** [comment]
I'm planning to revise this behavior for lazy modules (as part of #36460), but I don't know of any way to avoid it in today's eager modules.

Would it make sense for `gopls` to remove unused dependencies using `go mod edit -droprequire` instead?

**Comment by bcmills** [comment]
I guess my real answer is, “lazy loading will solve this, hopefully in 1.17”.  😞

**Comment by stamblerre** [comment]
Ah, I see--thanks for the quick response! The reason we were using the go command to do this was because we wanted to keep the `go.sum` file tidy, but maybe we can just do textual edits for removing a dependency until 1.17.

**Comment by bcmills** [comment]
So, you _could_ check whether the `go.mod` and `go.sum` are tidy before the edit, and if they are, run `go get <path>@none` followed by `go mod tidy`. That should DTRT most of the time, albeit at the cost of running `go mod tidy` in the diagnostic.

**Comment by stamblerre** [comment]
> That should DTRT most of the time, albeit at the cost of running `go mod tidy` in the diagnostic.

Yeah, we can actually avoid calling it in the diagnostic and only do it when the fix is selected, so that should actually be fine. I didn't love the idea of 2 code paths for the same fix type, but maybe that is the best approach for now.
