### ISSUE TITLE
Go 1.16 beta1: ios/amd64 build fails

### ISSUE THREAD

**Issue by marten-seemann** [golang/go#43343]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16beta1 darwin/amd64
</pre>

### What did you do?

I have a cross-compilation test which I run on CI. It builds a binary for all supported GOOS / GOARCH combinations (as reported by `go tool dist list`).

Using Go 1.15.x, `GOOS=ios GOARCH=amd64` is unsupported:
```
cmd/go: unsupported GOOS/GOARCH pair ios/amd64
```

Go 1.16 apparently adds support, but building fails. On my Mac, the error message is the following:
```
❯ GOOS=ios GOARCH=amd64 go build example/main.go
# command-line-arguments
loadinternal: cannot find runtime/cgo
```
On CI (GitHub Actions), I'm getting the following failure:
```
# command-line-arguments
loadinternal: cannot find runtime/cgo
/opt/hostedtoolcache/go/1.16.0-beta1/x64/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find 1144: No such file or directory
/tmp/go-link-046955828/go.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
```

Not sure what exactly this means, nor do I particularly care about building for this architecture. However, if `go tool dist list` lists this as a support combination, I would have expected the build to succeed.

### What did you expect to see?

`go build` should succeed.

### What did you see instead?

`go build` failed, see above.

**Comment by egonelbre** [comment]
Maybe you need an explicit `CGO_ENABLED=1`?

**Comment by marten-seemann** [comment]
The code I’m building doesn’t use cgo, and the build settings I’m using work fine for all other combinations.

**Comment by egonelbre** [comment]
Ah, now I understand. It's using `amd64` and not `arm64`.

* `ios/amd64` was added in https://go-review.googlesource.com/c/go/+/263798.
* some of the `misc/ios` instructions were updated in https://go-review.googlesource.com/c/go/+/255257/.

https://github.com/golang/go/tree/master/misc/ios has instructions how to use it.

**Comment by egonelbre** [comment]
Also using `CGO_ENABLED=1 GOOS=ios GOARCH=amd64 go build example.go` does work on the tip and with `go1.16beta1`. So it seems `CGO_ENABLED` is required, regardless whether you are using `C`.

**Comment by egonelbre** [comment]
CC @eliasnaur.

**Comment by egonelbre** [comment]
Maybe it needs to make `CGO_ENABLED` default to `1` for that platform or throw an error when it has not been enabled -- no clue where it should go though.

**Comment by eliasnaur** [comment]
I'm not sure either. CC @cherrymui.

**Comment by cherrymui** [comment]
Yeah, `CGO_ENABLED` needs to be set to 1, because currently the ios port requires external linking, which uses the C linker.

> loadinternal: cannot find runtime/cgo

This is not an error. It should generate the executable and it probably runs fine.

> CGO_ENABLED=1 GOOS=ios GOARCH=amd64 go build example.go does work on the tip and with go1.16beta1.

Could you explain what doesn't work?

**Comment by cherrymui** [comment]
`CGO_ENABLED` is default to 0 for cross-compilation. It may be reasonable to error out on ports require cgo.

**Comment by egonelbre** [comment]
@cherrymui Erroring sounds less "risky" because it can be made to work later. I would create a change, but I have no clue where the appropriate place would be. (Also, probably faster if someone else who knows where and how to exactly restrict it.)

**Comment by cherrymui** [comment]
> Erroring sounds less "risky" because it can be made to work later.

Yeah, I think it shouldn't be hard to make internal linking work for iOS, then you don't need the C linker. Maybe in Go 1.17. Not sure it is that useful, though, since for actual iOS apps I think it generally needs some C (or other language) part.

That said, I think it's been the case for quite a while (CGO_ENABLED stuff for cross-compilation). As we're late in the release cycle, maybe it's better to do the erroring behavior in Go 1.17. This probably will be in cmd/go, but I'm not sure exactly where. Issue #31544 might be relevant (about the `loadinternal` message).

**Comment by cherrymui** [comment]
@egonelbre could you clarify if `CGO_ENABLED=1 GOOS=ios GOARCH=amd64 go build` works? (This is the primary issue) On my Mac it works fine.
```
$ CGO_ENABLED=1 GOOS=ios GOARCH=amd64 go build hello.go
$ ./hello
hello
```

**Comment by egonelbre** [comment]
@churrymui Yes `CGO_ENABLED=1 GOOS=ios GOARCH=amd64 go build` works.

The main issue is that `GOOS=ios GOARCH=amd64 go build` gives a really weird error - so it would be better to print out `CGO_ENABLED=1 is required for ios/amd64` or alternatively add `CGO_ENABLED=1` automatically.

**Comment by enty8080** [comment]
@cherrymui:

```
root@Ivans-Air work # ls
build.sh	main-ios	main.go
root@Ivans-Air work # rm main-ios
root@Ivans-Air work # CGO_ENABLED=1 GOOS=ios GOARCH=amd64 go build main.go 
# runtime/cgo
gcc_darwin_amd64.c:62:15: error: unknown token in expression
<inline asm>:1:12: note: instantiated into assembly here
gcc_darwin_amd64.c:62:15: error: invalid operand
<inline asm>:1:12: note: instantiated into assembly here
root@Ivans-Air work # ls
build.sh	main.go
```

What I should do with this?

**Comment by eliasnaur** [comment]
@enty8080 your `go build` command worked for egonelbre and cherrymui, so what's unusual about your setup? Are you building on an iDevice? What does `go env` say, and what about `clang -v`?

**Comment by enty8080** [comment]
@eliasnaur `root@Ivans-Air work #` means that I builds from MacBook Air.

> go version

```
go version go1.16beta1 darwin/arm64
```

> clang -v

```
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: arm64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

> go env

```
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/enty8080/Library/Caches/go-build"
GOENV="/Users/enty8080/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/enty8080/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/enty8080/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16beta1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mp/l216mspj1r793n3f2zhh8vg40000gn/T/go-build1298098095=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by eliasnaur** [comment]
I don't know the reason for your error. FWIW, Rob may have had the [same issue](https://groups.google.com/g/golang-dev/c/NgFm7tUI9nI/m/vUHgoB0DBwAJ):

> I also have to set CGO_ENABLED=0 because of an assembly language syntax error (something about [reg] notation) that stops the build.

**Comment by enty8080** [comment]
@eliasnaur I am using latest MacBook Air:
<img width="698" alt="Screenshot 2020-12-26 at 15 38 58" src="https://user-images.githubusercontent.com/54115104/103153396-80669000-4790-11eb-87d6-eab7465a90a3.png">

**Comment by cherrymui** [comment]
See https://tip.golang.org/misc/ios/README . For cross compilation in general, you need to set `CC` to the C cross compiler.

**Comment by enty8080** [comment]
@cherrymui Thanks, I answered here #43371

**Comment by cherrymui** [comment]
From https://github.com/golang/go/issues/43343#issuecomment-750832659 the ios/amd64 build works, so this issue is resolved.

I'll look into erroring out when cgo is not enabled (not necessarily in this release, though).
