### ISSUE TITLE
go/ssa/interp/testdata/src/fmt/fmt.go:3:6: missing function body 

### ISSUE THREAD

**Issue by ORESoftware** [golang/go#43340]
### What version of Go are you using (`go version`)?

<pre>
go version go1.15.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Not sure if latest, but this is what I see:
```

3c22fb02d7cf:mbk-rest-api mllsaal$ go install
# golang.org/x/tools/go/ssa/interp/testdata/src/fmt
../../../../pkg/mod/golang.org/x/tools@v0.0.0-20200918232735-d647fc253266/go/ssa/interp/testdata/src/fmt/fmt.go:3:6: missing function body

```

The missing func body is here on line 3:

```golang
package fmt

func Sprint(args ...interface{}) string  // here

func Print(args ...interface{}) {
	for i, arg := range args {
		if i > 0 {
			print(" ")
		}
		print(Sprint(arg))
	}
}
```

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mllsaal/Library/Caches/go-build"
GOENV="/Users/mllsaal/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mllsaal/go/pkg/mod"
GONOPROXY="*"
GONOSUMDB="*"
GOOS="darwin"
GOPATH="/Users/mllsaal/go"
GOPRIVATE="*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.5/libexec"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/mllsaal/go/src/github.com/memebank/mbk-rest-api/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cp/2b91jt_11ns65yb9485jtj5w0000gr/T/go-build350184406=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Not sure what happened, I did run `go fmt ./...` right before the error happened tho which is weird.

**Comment by davecheney** [comment]
This could be a corrupt Go installation. Can you reproduce this on another system?

**Comment by ORESoftware** [comment]
nah it's due to my comment on here:
https://github.com/golang/go/issues/32207

problem solved lol
