### ISSUE TITLE
proposal: spec: boolean shortcut should allow mismatched types

### ISSUE THREAD

**Issue by rsc** [golang/go#4336]
<pre>It is unclear to me what we are gaining by rejecting this program:

<a href="http://play.golang.org/p/yHXYQxkHbi">http://play.golang.org/p/yHXYQxkHbi</a>

package main

import &quot;fmt&quot;

type T bool

func main() {
    var t T
    var b bool
    fmt.Println(t &amp;&amp; b)
}

prog.go:10: invalid operation: t &amp;&amp; b (mismatched types T and bool)

This might tie in with the other bool cleanup we've been doing, or it might be something
to leave for Go 2.</pre>

**Comment by ianlancetaylor** [comment]
As noted above, this proposal is not backward compatible.  And defined boolean types are uncommon.  It doesn't seem worth making a non-backward-compatible change for this purpose.  Therefore, this is a **likely decline**.  Leaving open for four weeks for final comments.

**Comment by ianlancetaylor** [comment]
No further comments.
