### ISSUE TITLE
x/pkgsite: remove pseudoversions of github.com/incognitochain/go-incognito-sdk

### ISSUE THREAD

**Issue by hoang-incognito** [golang/go#43367]
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/incognitochain/go-incognito-sdk@v0.0.0-20201120084145-e1eb54967a92
https://pkg.go.dev/github.com/incognitochain/go-incognito-sdk@v0.0.0-20201120093532-df1a9e237f10
 https://pkg.go.dev/github.com/incognitochain/go-incognito-sdk@v0.0.0-20201122143508-42012d083ea9
 https://pkg.go.dev/github.com/incognitochain/go-incognito-sdk@v0.0.0-20201123043942-6ef68180f11d
https://pkg.go.dev/github.com/incognitochain/go-incognito-sdk@v0.0.0-20201201043536-ed6a0686adae
https://pkg.go.dev/github.com/incognitochain/go-incognito-sdk@v0.0.0-20201214064626-3e6319da2b28
### What is your user agent?
 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

 
 
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/60601492/103084272-30ad8a80-4611-11eb-8b6e-95bfe30be68d.png)

 
 
 
### What did you expect to see?
 
 REMOVE ALL this link
 
### What did you see instead?
nothing

**Comment by julieqiu** [comment]
Per https://go.dev/about#removing-a-package:

> we can only remove a module entirely from the site. We cannot remove it just for specific versions.

Would you like github.com/incognitochain/go-incognito-sdk to be remove entirely from pkg.go.dev?

**Comment by jamalc** [comment]
We currently do not support removing specific versions of a package. The best thing to do in your case is publish a tagged version. Then the psuedo versions will no longer appear on the versions page for your module.

**Comment by hoang-incognito** [comment]
@jamalc It done. thanks all
