### ISSUE TITLE
goimports customization

### ISSUE THREAD

**Issue by pjebs** [golang/go#43365]
There should be a way to customize the behavior of goimports and gofmt so that the `golang.org/x/...` packages are grouped with the `standard library`.

I (and prob many others) consider them to be de-facto standard library packages. It's just annoying when goimports mixes it up with "regular" 3rd party packages.

**Comment by mengzhuo** [comment]
I think it's correct that category "golang.org/x" packages as 3rd party.
The "x" means "experimental" packages and might changed without any backward compatibility.

**Comment by pjebs** [comment]
I understand that they don't have same backward compatibility promise.

I just want to configure goimports so for me (and other others) it gets grouped with standard library. That way, in the future (whether the API changes or not), when it gets moved to the standard library and the import path gets changed it looks nicer.

**Comment by mengzhuo** [comment]
You can simply group them into in one group and goimports will leave them alone.
```
"fmt"

"golang.org/x/net"
"golang.org/x/text"

"some-awesome-3rd-package"
```
