### ISSUE TITLE
x/tools/gopls: understand that defined integer types may be slice indexes when suggesting completions

### ISSUE THREAD

**Issue by cespare** [golang/go#43375]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, and with the current tip of gopls as well.

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

### What did you do?

I used a variable of a defined integer type to index into a slice. Specifically, I tried to use autocompletion to fill in the variable in the index expression.

Here's some example code in a single-file package:

```
package main

type myInt int

func main() {
	nnn := myInt(3)
	mmm := 3
	x := make([]string, 5)
	x[|] = "hi"
}
```

The `|` is where my cursor was when I invoked autocompletion.

### What did you expect to see?

I expected to see `nnn` and `mmm` equally suggested as possible completions.

If I selected `nnn` from the list, the completed code should be

    x[nnn] = "hi"

### What did you see instead?

`nnn` is ranked much lower than `mmm` -- it comes after some irrelevant entries from other packages (I filed #43374 for that).

If I nevertheless scroll down to `nnn` and select it, `nnn` is wrapped in an unnecessary `int` conversion:

    x[int(nnn)] = "hi"

I noticed this in my usual environment of vim + govim but I can reproduce this with vscode as well. Here are some screenshots.

![screen_20201225000158](https://user-images.githubusercontent.com/318501/103126837-70419a00-4644-11eb-8aa4-a19f0c7019dc.png)

![screen_20201225000018](https://user-images.githubusercontent.com/318501/103126769-37a1c080-4644-11eb-8762-ecc3ed3fa1db.png)

**Comment by muirdm** [comment]
The issue seems to be gopls infers the expected type at `x[<>]` as int instead of untyped int (i.e. `types.Typ[types.Int]` instead of `types.Typ[types.UntypedInt]`). This issue appears in a few more places around the completion code.
