### ISSUE TITLE
ios/arm64 executable: must specify a minimum supported OS version.

### ISSUE THREAD

**Issue by enty8080** [golang/go#43371]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16beta1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/enty8080/Library/Caches/go-build"
GOENV="/Users/enty8080/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/enty8080/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="ios"
GOPATH="/Users/enty8080/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16beta1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mp/l216mspj1r793n3f2zhh8vg40000gn/T/go-build2420543642=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

**On my Mac:**

```
# export GOOS=ios
# export GOARCH=arm64
# go build main.go
```

### What did you expect to see?

I expected to executable successfully executed in my jailbroken iOS terminal.

### What did you see instead?

**On my iOS device:**

```
$ ./main
dyld: MH_EXECUTE binaries must specify a minimum supported OS version
Abort trap 6
```

**iOS**: 13.3.3 (arm64)
**macOS:** Big Sur

**Comment by mengzhuo** [comment]
cc @cherrymui

**Comment by dmitshur** [comment]
Have you considered using [`gomobile`](https://pkg.go.dev/golang.org/x/mobile/cmd/gomobile) tool to build the binary, instead of the `go` tool directly? `gomobile` is higher level and should address this kind of issue.

If you’re using `go build` directly, does it help if you set `CGO_CFLAGS=-miphoneos-version-min=10.0` (and possibly also `CGO_CXXFLAGS`, `CGO_LDFLAGS`)?

**Comment by eliasnaur** [comment]
@enty8080 does CL 280313 linked above work for you?

**Comment by enty8080** [comment]
@dmitshur `gomobile` does not works for me. It returns: `can't find package command-line-tools`.

**Comment by enty8080** [comment]
@eliasnaur Yes, when this (https://golang.org/cl/280313) will be added?

**Comment by enty8080** [comment]
@eliasnaur @dmitshur @cherrymui  Also look at this please #43378

**Comment by eliasnaur** [comment]
> @eliasnaur Yes, when this (https://golang.org/cl/280313) will be added?

Go is in a freeze for Go 1.16, so it's up to the release team to decide whether something like CL 280313 should go in 1.16 or 1.17.

**Comment by enty8080** [comment]
@eliasnaur Also I faced this error:

```
root@Ivans-Air work # ls
build.sh	main-ios	main.go
root@Ivans-Air work # rm main-ios
root@Ivans-Air work # CGO_ENABLED=1 GOOS=ios GOARCH=amd64 go build main.go 
# runtime/cgo
gcc_darwin_amd64.c:62:15: error: unknown token in expression
<inline asm>:1:12: note: instantiated into assembly here
gcc_darwin_amd64.c:62:15: error: invalid operand
<inline asm>:1:12: note: instantiated into assembly here
root@Ivans-Air work # ls
build.sh	main.go
```

Solution from #43343

**Comment by cherrymui** [comment]
See https://tip.golang.org/misc/ios/README . Does it work with `GOOS=ios GOARCH=arm64 CGO_ENABLED=1 CC=$(go env GOROOT)/misc/ios/clangwrap.sh go build` (or amd64)? Thanks.

**Comment by enty8080** [comment]
@cherrymui yes it compiles successfully with this clangwrap. Thanks. But there is another problem with MH_EXECUTE

```
$ ./main
dyld: MH_EXECUTE binaries must specify a minimum supported OS version
Abort trap 6
```

**Comment by cherrymui** [comment]
@enty8080 What platform you are targeting, arm64 or amd64? How do you run the binary? Does the output binary has an LC_VERSION_MIN_IPHONEOS load command? (you can see it by running `otool -l <binary> | grep VERSION_MIN`) Thanks.

**Comment by enty8080** [comment]
@cherrymui Sorry, I tested old binary. Now it works fine. Thanks.

**Comment by enty8080** [comment]
@cherrymui Close issue?

**Comment by cherrymui** [comment]
@enty8080 thanks for confirming! Yeah, we can close this. I'll see if I can make it better documented.

> NOTE: On iOS device before running executable you should ldid -S <file> or Killed: 9 error appears.

@eliasnaur do you think there is anything actionable for Go about this? Thanks.

**Comment by eliasnaur** [comment]
@cherrymui, would you like to review https://go-review.googlesource.com/c/go/+/280313/? Porbably not for Go 1.16, but good for when GOOS=ios can produce working internally linked binaries.

**Comment by dmitshur** [comment]
Is it better/easier to document this somewhere, or update [`gomobile`](https://pkg.go.dev/golang.org/x/mobile/cmd/gomobile) to perform this step and point people to use it?

As far as I can tell, the main purpose of gomobile is to create functional iOS/Android applications. If it's no longer suitable for that purpose, perhaps we should make it clear that it's deprecated/non-functional.

**Comment by eliasnaur** [comment]
@dmitshur gomobile can produce mobile applications with `gomobile build`, however that mode is very limited. It's primary use is for generating convenient bridges from Go to ObjC/Swift and Java with the `gomobile bind` mode.

So I think it's a mistake to consider `gomobile` *the* way to build for mobile. For example, Gio doesn't use `gomobile` at all.

**Comment by dmitshur** [comment]
@eliasnaur Thanks. I've edited my comment above to clarify it's specifically about gomobile's `build` subcommand.

**Comment by cherrymui** [comment]
> @cherrymui, would you like to review https://go-review.googlesource.com/c/go/+/280313/? Porbably not for Go 1.16, but good for when GOOS=ios can produce working internally linked binaries.

Done. Yeah, it will be needed when we enable internal linking for ios.
