### ISSUE TITLE
Q: networking ala gnet

### ISSUE THREAD

**Issue by ivanjaros** [golang/go#43385]
There is the old https://github.com/tidwall/evio library and a newer and much better library https://github.com/panjf2000/gnet that seem to be providing incredible speed for networking. But they are incompatible with the built-in libraries like http or tls which makes them unusable in this realm.

So I am simply curious to know if there is any work being put towards refactoring the networking architecture that gnet is using and which would benefit the language as a whole?

**Comment by mdlayher** [comment]
Please see https://github.com/golang/go/wiki/Questions. Closing.
