### ISSUE TITLE
[Question] Opt out of GOPCLNTAB generation to combat reverse engineering binaries

### ISSUE THREAD

**Issue by leaanthony** [golang/go#43396]
Having read [this article](https://tuanlinh.gitbook.io/ctf/golang-function-name-obfuscation-how-to-fool-analysis-tools), it would seem that a useful feature of the Go compiler would be to not include/scramble the GOPCLNTAB section of the compiled binary. I'm not an expert in this field so please excuse my ignorance in this area. My driver is requests from users of my project who are facing people reverse engineering their projects. I attempted to find other issues opened for this but could not find any.

Thanks in advance.

**Comment by ALTree** [comment]
The information contained in pclntab cannot be removed without breaking several standard library function. Please see the discussion at #36555.

Closing here as a dup of #36555.
