### ISSUE TITLE
x/pkgsite: remove mariusor/littr.go

### ISSUE THREAD

**Issue by mariusor** [golang/go#43394]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/mariusor/littr.go

### What did you expect to see?
 
I am the owner of mariusor/littr.go, which underwent a rename (to mariusor/go-littr) because the default go tooling has issues with packages whose names end in `.go`. 

I expected that the package gets removed when it dissapears from github.
 
### What did you see instead?

I can still view the version of the package before the rename even though no external packages are importing it.

**Comment by jamalc** [comment]
Done.
