### ISSUE TITLE
x/pkgsite: valid license after undetected license doesn't update docs

### ISSUE THREAD

**Issue by bmizerany** [golang/go#43392]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/bmizerany/perm 
 
### What is your user agent?
 

 
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
```

### Screenshot

 

 
<img width="1396" alt="Screen Shot 2020-12-27 at 1 12 29 AM" src="https://user-images.githubusercontent.com/46/103167525-9ac85a00-47e0-11eb-8e68-653b0dc5dc0e.png">
 
### What did you do?
 

 
I published a go package on Github without a valid license according to the license policy and attempted to view the documentation on pkg.go.dev. I saw the screen above, realized my error, and added a LICENSE with valid MIT text. I attempted a refresh but that didn't take, so I tried Apache. That didn't take, so I waited to see if a cache was in the way, but gave up after 30 or so minutes.
 
### What did you expect to see?

Package documentation.

### What did you see instead?

An error regarding a violation of the license policy.

---

I'm leaving the repo as-is in hopes it is helpful in finding my error.

**Comment by seankhliao** [comment]
I think you just needed to wait longer/get the specific version, it's available now

**Comment by bmizerany** [comment]
Thank you!
