### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by go-provider** [golang/go#43415]
As per instructions at https://go.dev/about for removing a package: please remove 
https://pkg.go.dev/github.com/go-provider/loader
https://pkg.go.dev/github.com/go-provider/log
https://pkg.go.dev/github.com/go-provider/tcp
https://pkg.go.dev/github.com/go-provider/grpc
https://pkg.go.dev/github.com/go-provider/zap
https://pkg.go.dev/github.com/go-provider/mysql
https://pkg.go.dev/github.com/go-provider/http
https://pkg.go.dev/github.com/go-provider/toml-decoder
Thank you.

**Comment by jamalc** [comment]
Done.
