### ISSUE TITLE
x/tools/go/packages: error during the call to `packages.Load` with `-mod` other than empty.

### ISSUE THREAD

**Issue by ldez** [golang/go#43418]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 linux/amd6
</pre>

### Does this issue reproduce with the latest release?

It's not related to a specific version of Go.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ldez/.cache/go-build"
GOENV="/home/ldez/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ldez/sources/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ldez/sources/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/ldez/.gvm/gos/go1.15.6"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/ldez/.gvm/gos/go1.15.6/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build165529633=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```go
package main

import (
	"fmt"

	"golang.org/x/tools/go/packages"
)

func main() {
	conf := &packages.Config{
		BuildFlags: []string{"-mod=readonly"},
	}

	pkgs, err := packages.Load(conf)

	fmt.Println(err, pkgs)
}
```

The problem is related to the `state.getGoVersion()` call:

https://github.com/golang/tools/blob/929a8494cf60267d89035bc211b797a67b65a6b9/go/packages/golist.go#L848-L852

This call was introduced in https://github.com/golang/tools/commit/2f4fa188d925fdee3467708b69aa4761a429ae9d

I think that the call creates this problem because of the hard-coded `GO111MODULE=off`

https://github.com/golang/tools/blob/929a8494cf60267d89035bc211b797a67b65a6b9/internal/gocommand/version.go#L18

Because of the hard-coded `GO111MODULE=off` the value of `cfg.ModulesEnabled` is `false`.

https://github.com/golang/go/blob/4fd94558820100129b98f284e21b19fc27a99926/src/cmd/go/internal/work/init.go#L271-L274

Related to https://github.com/golangci/golangci-lint/issues/1502

### What did you expect to see?

```
<nil> [.]
```

### What did you see instead?

```
err: exit status 1: stderr: build flag -mod=readonly only valid when using modules
 []
```

**Comment by stamblerre** [comment]
Thank you for reporting this! I'm able to reproduce--the issue is that we clear out the invocation's Mod flag, but we don't remove any `-mod=` flag from the build flags. I'll have a fix soon.

**Comment by fc** [comment]
Upgrading to go 1.16 resolved it for me.
