### ISSUE TITLE
cmd/compile: method expressions are misprinted

### ISSUE THREAD

**Issue by mdempsky** [golang/go#43428]
On the dev.regabi branch, the error message for this source file:

```
package p

import "bytes"

var x int = (*bytes.Buffer).Len
```

mentions `*bytes.Buffer.Len`. That's incorrect: it should be `(*bytes.Buffer).Len`, as it appears in the source.

(I suspect this is related to the ir/fmt.go changes in 4629f6a51da5afabbebe9616f65fbfe0675d6039. Though it turns out we're printing it incorrectly even on master, where it prints as `bytes.(*Buffer).Len`.)

/cc @cuonglm

**Comment by ianlancetaylor** [comment]
We've printed the `bytes.(*Buffer).Len` version since at least Go 1.1.

**Comment by mdempsky** [comment]
@ianlancetaylor Thanks, that sounds believable. You aren't suggesting cmd/compile should continue printing it incorrectly though, are you?

In case it wasn't clear, the linker symbols used for pointer-receiver methods (including as they appear in runtime stack traces) are unchanged on dev.regabi; and while I believe the parentheses are superfluous there, I don't intend to remove them either. This issue is only about how method expressions are printed in Go-syntax compiler diagnostics, like error messages and `-m` output.

go/types correctly prints `(*bytes.Buffer).Len` in its diagnostics.

**Comment by mdempsky** [comment]
cmd/compile now prints diagnostics using Go syntax for method expressions on dev.regabi.
