### ISSUE TITLE
cmd/go: don't make "build constraints exclude all Go files" a fatal error for go test

### ISSUE THREAD

**Issue by josharian** [golang/go#43424]
I would like to run all the tests for a module I'm working on. Usually I would do that with `go test ./..`. Unfortunately, one of the packages is windows-only. `go test ./...` dies immediately with:

```
package path/to/the/package
	imports golang.org/x/sys/windows: build constraints exclude all Go files in /Users/josh/pkg/mod/golang.org/x/sys@v0.0.0-20201218084310-7d0127a74742/windows
```

It doesn't run any of the tests in any of the packages. I'd prefer if `go test ./...` informed me that it couldn't test the package in question, but continued to run the tests for the rest of the packages.

cc @bcmills @jayconrod 

As a workaround, @alexbrainman @bradfitz are you OK with me adding a non-windows stub file to golang.org/x/sys/windows?

**Comment by dmitshur** [comment]
> Unfortunately, one of the packages is windows-only. `go test ./...` dies immediately

If that package is windows-only, it wouldn't be picked up by the `./...` pattern. Maybe it's missing `// +build windows` constraints?

For example, on darwin/amd64, I can successfully run `go test ./...` at the root of the `golang.org/x/sys` module.

I think it's better to avoid adding non-windows stub files to a windows-only package, as that makes the package build on non-windows OSes but have a different API.

**Comment by josharian** [comment]
Arg. I got foiled again by the build tag syntax. Thank goodness the overhaul is happening soon. Sigh. Thanks.
