### ISSUE TITLE
Go 1.16 beta1: openbsd/mips64 build fails

### ISSUE THREAD

**Issue by marten-seemann** [golang/go#43442]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16beta1 darwin/amd64
</pre>

### What did you do?

I have a cross-compilation test which I run on CI. It builds a binary for all supported GOOS / GOARCH combinations (as reported by `go tool dist list`).

Using Go 1.15.x, `GOOS=openbsd GOARCH=mips64` is unsupported:
```
cmd/go: unsupported GOOS/GOARCH pair openbsd/mips64
```

Go 1.16 apparently adds support, but building fails:
```
❯  GOOS=openbsd GOARCH=mips64 go build example/main.go
# golang.org/x/sys/cpu
../../../../pkg/mod/golang.org/x/sys@v0.0.0-20200519105757-fe76b779f299/cpu/cpu_linux_mips64x.go:17:25: undefined: hwCap
```

Not sure what exactly this means, nor do I particularly care about building for this architecture. However, if `go tool dist list` lists this as a support combination, I would have expected the build to succeed.

### What did you expect to see?

`go build` should succeed.

### What did you see instead?

`go build` failed, see above.

**Comment by mengzhuo** [comment]
hwCap only been defined in Linux
https://github.com/golang/sys/blob/0d417f6369309be088e227ead8736fb722d759d3/cpu/hwcap_linux.go#L23

However it's weird that although the build tag strictly on linux but it still runs into it.

**Comment by mengzhuo** [comment]
CC @4a6f656c

**Comment by ianlancetaylor** [comment]
You need to update your golang.org/x/sys/cpu package past commit d785dc25833f1ad82a72435f1e369f016e16ee2c from August 20, 2020.

**Comment by marten-seemann** [comment]
This happens on my local machine as well as on a clean Go installation on CI. Not sure why it should be necessary to update golang.org/x/sys/cpu manually for this particular GOOS / GOARCH.

GitHub says (regarding https://github.com/golang/go/commit/d785dc25833f1ad82a72435f1e369f016e16ee2c): `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`
