### ISSUE TITLE
panic in src/database/sql/sql.go:2041 why

### ISSUE THREAD

**Issue by liaosimin** [golang/go#43445]
go version 1.13.14

panic stack：
........
panic(0x11871a0, 0x1e04370)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
sync.(*RWMutex).RLock(...)
/usr/local/go/src/sync/rwmutex.go:48
database/sql.(*Tx).grabConn(0x0, 0x14b9620, 0xc0014486f0, 0x0, 0x0, 0x0, 0x0)
/usr/local/go/src/database/sql/sql.go:2041 +0x57
database/sql.(*Tx).ExecContext(0x0, 0x14b9620, 0xc0014486f0, 0xc0010ff800, 0x101, 0xc001325400, 0xf, 0x10, 0x1123ae0, 0x1477a80, ...)
/usr/local/go/src/database/sql/sql.go:2291 +0x4c
gorm.io/gorm/callbacks.Create.func1(0xc0014487e0)
/opt/tiger/compile_path/pkg/mod/gorm.io/gorm@v1.20.7/callbacks/create.go:54 +0x33c
gorm.io/gorm.(*processor).Execute(0xc00007d980, 0xc0014487e0)
/opt/tiger/compile_path/pkg/mod/gorm.io/gorm@v1.20.7/callbacks.go:105 +0x224
gorm.io/gorm.(*DB).Create(0xc001448750, 0x124fee0, 0xc001b70980, 0x14b9620)
/opt/tiger/compile_path/pkg/mod/gorm.io/gorm@v1.20.7/finisher_api.go:20 +0xa7
code.byted.org/ad/account_dal/pkg/gorm_client.(*GORMX).Create(0xc0001d5380, 0x14b9620, 0xc00112dd40, 0x124fee0, 0xc001b70980, 0x0, 0x0)
.......

can somebody help me?

**Comment by davecheney** [comment]
Please try upgrading to go 1.15.6 and running the race detector.

**Comment by mengzhuo** [comment]
Hi, liaosimin 

0. It looks like you are using "gorm" and Go 1.13 , please upgrade to Go1.15 if possible.
1. Github issue is not a place for non-Go-itself related question and "go-nuts" is the right place for these topic. https://groups.google.com/g/golang-nuts

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
