### ISSUE TITLE
Crash at runtime/traceback.go:gentraceback

### ISSUE THREAD

**Issue by ffffwh** [golang/go#43441]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Cannot reproduce on go1.10, let alone the latest release.

### What operating system and processor architecture are you using (`go env`)?
Here is the compiling env. Running env is out of reach.
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/opt/go"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build089432846=/tmp/go-build"
</pre></details>

### What did you do?

It is a C++ server program, calling a go lib.

### What did you expect to see?

Program continues running for a long term.

### What did you see instead?

Program crashed after running for several days, with linux log

```
Dec 20 18:24:03 hostname kernel: myprogram[27064]: segfault at 119 ip 00007f5bb82c8bd2 sp 00007f5bb4840f70 error 4 in libgowrapper.so[7f5bb7fc3000+8e7000]
```

### My analysis
```
hex(0x7f5bb82c8bd2 - 0x7f5bb7fc3000)= 0x305bd2

(gdb) info sym 0x305bd2
runtime.gentraceback + 5522 in section .text
(gdb) break *0x305bd2  
Breakpoint 1 at 0x305bd2: file /opt/go/src/runtime/traceback.go, line 290.
```

[Link to the line](https://github.com/golang/go/blob/bf86aec25972f3a100c3aa58a6abcbcc35bdea49/src/runtime/traceback.go#L290)

```go
func gentraceback(...) int {
			flr = findfunc(frame.lr)
			if !flr.valid() {
				// This happens if you get a profiling interrupt at just the wrong time. ...
				doPrint := printing
				if doPrint && gp.m.incgo { // *** Line 290
					// We can inject sigpanic...
					doPrint = false
				}
```

`unsafe.Offsetof(m.incgo)` gives 0x119 so the crash point should be exact: `m==nil` thus accessing `m.incgo` cause the segfault.

`doPrint` should be true, so `pcbuf == nil && callback == nil` is true. `gentraceback()` should be called for 'stack prints'.

My questiones:
- How to reproduce 'get a profiling interrupt at just the wrong time'?
- Is `gp.m==nil` a go-side problem, or it could be caused by user-side code?

**Comment by davecheney** [comment]
Go 1.10 is long out of support. I'd strongly suggest upgrading to Go 1.15.6 or the 1.16 beta.

**Comment by toothrot** [comment]
Closing, and strongly supporting @davecheney's comment.

Please comment if you can reproduce in a supported version of Go.
