### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by asterixds** [golang/go#43468]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/search?page=2&q=grule
 
### What is your user agent?
 

 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
 
 
### Screenshot
 

 
<img width="720" alt="image" src="https://user-images.githubusercontent.com/7004432/103455213-25c6ba00-4ce3-11eb-8996-a4e27617acc0.png">

 
 
### What did you do?
 

searched for packages starting with "Grule" in pkg.go.dev. I found these packages with url github.com/asterixds/grule-rule-engine. These should be deleted as the original author of these packages is github.com/hyperjumtech/grule-rule-engine. I was  trying some modifications and took some shortcuts. I inadverdately uploaded these packages to the pkg repo and need to delete them as the original repo should be the only one in existence.
 
 
### What did you expect to see?
 only github.com/hyperjumtech/grule-rule-engine
 
 
### What did you see instead?

only github.com/hyperjumtech/grule-rule-engine and 
github.com/asterixds/grule-rule-engine

**Comment by jba** [comment]
We will no longer serve the `asterixds` path, but it will still appear in search results until #41817 is fixed.

**Comment by jba** [comment]
My mistake, that issue was fixed some time ago, so the path doesn't appear in search.
