### ISSUE TITLE
x/pkgsite: remove bdd.fi/x/runitor/pkg/api and bdd.fi/x/runitor/pkg/api/healthchecks

### ISSUE THREAD

**Issue by bdd** [golang/go#43464]
### Listings to be removed
* [bdd.fi/x/runitor/pkg/api/healthchecks](https://pkg.go.dev/bdd.fi/x/runitor/pkg/api/healthchecks)
* [bdd.fi/x/runitor/pkg/api](https://pkg.go.dev/bdd.fi/x/runitor/pkg/api)

### Reason
runitor is a command line tool and its opportunistic implementation of a Healthchecks API was never intended to be available as a separate package. v3.0 moved these implementations under `internal` while these listings are vestigial from v2.0.

**Comment by jba** [comment]
Done.
