### ISSUE TITLE
cmd/go2go: go2go playground: error with go fmt (generics)

### ISSUE THREAD

**Issue by candlerb** [golang/go#43470]
### What version of Go are you using (`go version`)?

https://go2goplay.golang.org/

`fmt.Println(runtime.Version())` reports `devel +abe4d3dce1 Tue Dec 8 17:59:47 2020 +0000`

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

https://go2goplay.golang.org/p/IUL1QDrtOwW

Click on "Format".  (Note: this program runs happily)

### What did you expect to see?

Program to be re-formatted

### What did you see instead?

```
prog.go:40:24: expected ']', found ',' (and 6 more errors)
```

**Comment by andig** [comment]
It does work when I run it from the link above.

**Comment by candlerb** [comment]
Are you sure you pressed "Format" not "Run"?  Or maybe you have to Run first, and then Format?

I am using Chrome 87 under macOS 10.14.6, and this is a screenshot of what I see when I click the "Format" button:

![image](https://user-images.githubusercontent.com/44789/103465109-aa8bf500-4d30-11eb-9a61-18bb2c95ee11.png)

I have just re-tested with Firefox and got the same result.

**Comment by ianlancetaylor** [comment]
The gofmt program does seem to work on the dev.go2go branch, so this may indicate a bug in the way we update the go2go playground.

CC @griesemer

**Comment by griesemer** [comment]
The `gofmt` command needs to specify that the parser should accept type parameters. It's just a missing flag setting. (Not sure if this ever worked in `dev.go2go`.)

**Comment by findleyr** [comment]
This fix is now deployed.
