### ISSUE TITLE
encoding/json: Decode does not error on invalid leading zeros

### ISSUE THREAD

**Issue by davecheney** [golang/go#43474]
### What version of Go are you using (`go version`)?

<pre>
go 1.16.beta1
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

darwin/amd64

### What did you do?

```
package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

func main() {
	s := `01`
	sr := strings.NewReader(s)
	dec := json.NewDecoder(sr)
	var f float64
	err := dec.Decode(&f)
	fmt.Println(f, err)
}
```

### What did you expect to see?

an error related to an invalid number

### What did you see instead?

```
0 <nil>
```

**Comment by cespare** [comment]
The decoder decodes a valid JSON value (`0`) and gives it back. The `1` is unconsumed. If you decode again, you will get the next JSON value in the stream (`1`).

https://play.golang.org/p/FNzEJED4Dyl

**Comment by davecheney** [comment]
Yes indeed, thank you.

**Comment by josharian** [comment]
Related: https://github.com/golang/go/issues/36225
