### ISSUE TITLE
x/tools/gopls: improve completion results when they depend on code after the current line in the same file

### ISSUE THREAD

**Issue by cespare** [golang/go#43471]
### What version of Go are you using (`go version`)?

1.15.6 / gopls 0.6.0

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

### Description

A problem I frequently encounter using gopls is that if the completion target depends on code defined in the same file but *after* the cursor position, the completion is non-functional unless the expression is extremely simple.

Here are some concrete examples using vscode.

If the type `S` is defined before the current function and I start typing a `range` statement, completion works fine:

![screen_20210103000926](https://user-images.githubusercontent.com/318501/103474404-53017f80-4d58-11eb-992c-5248bfdfddb4.png)

If the type `S` is defined after the current function and I start typing a `range` statement, completion is not useful (it suggests some irrelevant packages):

![screen_20210103000941](https://user-images.githubusercontent.com/318501/103474378-146bc500-4d58-11eb-9a23-997184d4ba20.png)

An `if` expression has the same problem:

![screen_20210103000955](https://user-images.githubusercontent.com/318501/103474397-3bc29200-4d58-11eb-8d46-c5931ff70374.png)

But if I only type a simple `s.`, completion works:

![screen_20210103001004](https://user-images.githubusercontent.com/318501/103474399-454bfa00-4d58-11eb-906c-4ac7ceb56648.png)

I understand that the problem of trying to parse partial (i.e., broken) code is, in the general case, impossible. But doing a passable job in the typical cases seems important. ISTM that a heuristic as simple as "try parsing the code after deleting the line that the cursor is on" would cover the examples I showed here and most of the instances I notice day to day.

I looked for an existing issue as best I could with GH issue search but didn't find anything.

**Comment by muirdm** [comment]
> try parsing the code after deleting the line that the cursor is on

The problem with that approach is that we need to parse the current line to know we are completing `s.` (i.e. to look for fields on the `S` struct).

See https://go-review.googlesource.com/c/tools/+/216482/ for a previous relevant fix. Adding phantom curlies (i.e. `if s. {}`) and re-parsing is one way to make things work. Perhaps `fixMissingCurlies` can be tweaked in some way to fix this case as well.
