### ISSUE TITLE
x/pkgsite: remove some repositories

### ISSUE THREAD

**Issue by acanalis** [golang/go#43478]
As per go.https://go.dev/about, 

I'd like to remove from the site the following packages of which I'm the author: 

https://pkg.go.dev/github.com/acanalis/bf
https://pkg.go.dev/github.com/acanalis/gather/algorithm
https://pkg.go.dev/github.com/acanalis/gather/gather
https://pkg.go.dev/github.com/acanalis/gather/gather/test
https://pkg.go.dev/github.com/acanalis/gather/input
https://pkg.go.dev/github.com/acanalis/gather

The reason why I ask is because the packages where experimental, and "gather" has since changed its name and became private. 

It would be great if I had an interface to add/remove my own packages from pkg.go.dev because: 
* I don't want to file an issue to this repository unless it's language related.
* I'd like to only show repositories that are for long term projects, and not one-offs, experiments, or WIPs.

https://github.com/golang/go/issues/43297#issuecomment-748950926 mentioned using annotations in the go.mod file, so in the future I'll probably be able to remove the packages myself. 

Thanks

**Comment by jba** [comment]
If we remove `gather`, we'll remove everything under that. (Our logic works by prefix.) Is that OK?

**Comment by acanalis** [comment]
> If we remove `gather`, we'll remove everything under that. (Our logic works by prefix.) Is that OK?

Absolutely, so ahead. Thanks!

**Comment by jba** [comment]
Done.
