### ISSUE TITLE
cmd/compile: internal compiler error: weird package in name (dev.regabi branch)

### ISSUE THREAD

**Issue by zikaeroh** [golang/go#43479]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +8fc44cf0fa Sun Jan 3 19:48:20 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

No, only on the regabi branch.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jake/.cache/go-build"
GOENV="/home/jake/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jake/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jake/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/jake/zikaeroh/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/jake/zikaeroh/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jake/pkger/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build831767264=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version devel +8fc44cf0fa Sun Jan 3 19:48:20 2021 +0000 linux/amd64
GOROOT/bin/go tool compile -V: compile version devel +8fc44cf0fa Sun Jan 3 19:48:20 2021 +0000
uname -sr: Linux 5.10.4-zen2-1-zen
/usr/lib/libc.so.6: GNU C Library (GNU libc) release release version 2.32.
gdb --version: GNU gdb (GDB) 10.1
</pre></details>

### What did you do?

Cloned https://github.com/markbates/pkger, built the dev.regabi branch, and did a `go build` in the `pkger` checkout.

### What did you expect to see?

No errors, a built binary.

### What did you see instead?

```
# github.com/markbates/pkger/here
here/here.go:14:5: internal compiler error: weird package in name: here.p => p, not ""

goroutine 1 [running]:
runtime/debug.Stack(0xe8d1a0, 0xc0000bc008, 0x0)
	/home/jake/zikaeroh/go/src/runtime/debug/stack.go:24 +0x9f
cmd/compile/internal/base.FatalfAt(0xe05000000002, 0xd6fb5c, 0x27, 0xc00008d498, 0x3, 0x3)
	/home/jake/zikaeroh/go/src/cmd/compile/internal/base/print.go:227 +0x1b9
cmd/compile/internal/base.Fatalf(...)
	/home/jake/zikaeroh/go/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/typecheck.(*exportWriter).localIdent(0xc000598de0, 0xc0003882d0, 0x0)
	/home/jake/zikaeroh/go/src/cmd/compile/internal/typecheck/iexport.go:1557 +0x234
cmd/compile/internal/typecheck.(*exportWriter).param(0xc000598de0, 0xc0003a1f40)
	/home/jake/zikaeroh/go/src/cmd/compile/internal/typecheck/iexport.go:754 +0x96
cmd/compile/internal/typecheck.(*exportWriter).paramList(0xc000598de0, 0xc0000bc3d8, 0x1, 0x1)
	/home/jake/zikaeroh/go/src/cmd/compile/internal/typecheck/iexport.go:748 +0x65
cmd/compile/internal/typecheck.(*exportWriter).signature(0xc000598de0, 0xc0003a48a0)
	/home/jake/zikaeroh/go/src/cmd/compile/internal/typecheck/iexport.go:738 +0x7e
cmd/compile/internal/typecheck.(*exportWriter).doTyp(0xc000598de0, 0xc0003a48a0)
	/home/jake/zikaeroh/go/src/cmd/compile/internal/typecheck/iexport.go:679 +0x7af
cmd/compile/internal/typecheck.(*iexporter).typOff(0xc0000c63c0, 0xc0003a48a0, 0xc000598d88)
	/home/jake/zikaeroh/go/src/cmd/compile/internal/typecheck/iexport.go:626 +0xd5
cmd/compile/internal/typecheck.(*exportWriter).typ(0xc000598d80, 0xc0003a48a0)
	/home/jake/zikaeroh/go/src/cmd/compile/internal/typecheck/iexport.go:609 +0x38
cmd/compile/internal/typecheck.(*iexporter).doDecl(0xc0000c63c0, 0xc000377180)
	/home/jake/zikaeroh/go/src/cmd/compile/internal/typecheck/iexport.go:438 +0x307
cmd/compile/internal/typecheck.WriteExports(0xc0003b0c40)
	/home/jake/zikaeroh/go/src/cmd/compile/internal/typecheck/iexport.go:274 +0x2a6
cmd/compile/internal/gc.dumpexport(0xc00009e750)
	/home/jake/zikaeroh/go/src/cmd/compile/internal/gc/export.go:34 +0x18c
cmd/compile/internal/gc.dumpCompilerObj(0xc00009e750)
	/home/jake/zikaeroh/go/src/cmd/compile/internal/gc/obj.go:106 +0x39
cmd/compile/internal/gc.dumpobj1(0x7ffc29438d9c, 0x23, 0x3)
	/home/jake/zikaeroh/go/src/cmd/compile/internal/gc/obj.go:62 +0x174
cmd/compile/internal/gc.dumpobj()
	/home/jake/zikaeroh/go/src/cmd/compile/internal/gc/obj.go:43 +0x50
cmd/compile/internal/gc.Main(0xd7ed10)
	/home/jake/zikaeroh/go/src/cmd/compile/internal/gc/main.go:349 +0x1305
main.main()
	/home/jake/zikaeroh/go/src/cmd/compile/main.go:54 +0xb1
```

/cc @mdempsky

**Comment by zikaeroh** [comment]
Bisects to [CL 274440](https://golang.org/cl/274440) for me.

**Comment by mdempsky** [comment]
Thanks for the bisection.

**Comment by zikaeroh** [comment]
Closing as fixed on `dev.regabi` (GitHub won't autoclose this until it's merged into `master`).
