### ISSUE TITLE
x/tools/gopls: error with cgo definitions

### ISSUE THREAD

**Issue by shuxiao9058** [golang/go#43473]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 linux/386
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="386"
GOBIN=""
GOCACHE="/home/jy/.cache/go-build"
GOENV="/home/jy/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/usr/local/golang/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/local/golang/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/golang/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/golang/go/pkg/tool/linux_386"
GCCGO="gccgo"
GO386="sse2"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g"
CGO_FFLAGS="-g"
CGO_LDFLAGS="-g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build579898133=/tmp/go-build"

</pre></details>

### What did you do?

"message": "char not declared by package C",
      "source": "compiler",
      "severity": 1,
      "range": {
        "end": {
          "character": 15,
          "line": 23
        },
        "start": {
          "character": 11,
          "line": 23
        }
      }

**Comment by stamblerre** [comment]
Can you please share your `gopls` logs? Information on how to capture them can be found [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs).

**Comment by shuxiao9058** [comment]
This is too abnormal, it turned  to be work well with some other small projects(with cgo).

**Comment by stamblerre** [comment]
Glad to hear it's working well with other projects. Is it OK to close this issue?
