### ISSUE TITLE
syscall: stringer API for Signal should include the symbolic identifier in its output

### ISSUE THREAD

**Issue by krader1961** [golang/go#43489]
The stringer interface for type `syscall.Signal` should include the Go syscall symbol name in the string for the signal. For example, "SIGTERM" should appear in the string if the value is `syscall.SIGTERM`. Alternatively, provide a separate method for explicitly converting a `syscall.Signal` to its syscall symbol.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

I did the equivalent of `fmt.Println(syscall.SIGTERM)`.

### What did you expect to see?

Something like `SIGTERM (terminated)`.

### What did you see instead?

`terminated`

**Comment by tklauser** [comment]
The `syscall` package is frozen and should only receive bug fixes. Instead, the corresponding `golang.org/x/sys` package should be used.

You can use `golang.org/x/sys/unix.SignalName` to get the symbolic identifier, i.e.

```go
package main

import (
	"fmt"

	"golang.org/x/sys/unix"
)

func main() {
	fmt.Printf("%s (%s)\n", unix.SignalName(unix.SIGTERM), unix.SIGTERM)
}
```

https://play.golang.org/p/DSzhx5y8SVI

which will print `SIGTERM (terminated)`.

**Comment by ianlancetaylor** [comment]
Changing the result of `syscall.Signal.String` seems likely to break currently broken programs.  As @tklauser says, use `unix.SignalName`.
