### ISSUE TITLE
x/sys/unix: Pipe does not work on Darwin

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#43498]
The x/sys/unix `Pipe` implementation is incorrect on Darwin.  The x/sys/unix package needs a change along the lines of the change to syscall/syscall_darwin.go in https://golang.org/cl/141639.  Unfortunately, it may have to be more complicated if we want to continue supporting Go 1.12 in the x/sys/unix package, as for 1.12 we should probably use the existing version of `Pipe`.

CC @randall77

**Comment by randall77** [comment]
Yikes, looks like this never worked. The `pipe` calling convention is different from the raw syscall and the libc call.
Any idea if there are others like this?

Fortunately I don't think we use `x/sys/unix.Pipe` anywhere in the stdlib. So no need to vendor in any fix here.

The corresponding x/sys/unix change to https://golang.org/cl/141639 was https://golang.org/cl/154179

It should be easy to keep supporting 1.12. There are separate files for <=1.12 and >1.12 support.

**Comment by randall77** [comment]
1.12 is actually when we cut over to libc system calls. So only <= 1.11 support would still need support for raw system calls.
But it looks like that support is already gone in `x/sys/unix`: https://golang.org/cl/250437
So the fix is easy.
