### ISSUE TITLE
cmd/go: auto-find module from package import

### ISSUE THREAD

**Issue by fwhezfwhez** [golang/go#43493]
In my company, There're many packages local and saved in restricted git repo.

To import those pkgs, I'm doing like :
```go
package main

import (
    "xxx"
)
```

Desperately xxx module not found. Even if I've already put xxx into $GOPATH/pkg/mod/xxx.

To fix this ,I must  type 
```
requires xxx
replace xxx ../../pkg/mod/xxx
```

It seems estremely bad and extra. Because once I put my projects not in GOPATH/src, the replace will changed to `../../../../path-togopath/pkg/mod/xxx`. Also it doesnt support 'replace xxx $GOPATH/pkg/mod/xxx'.

Suggest full path or from root?

No, because a repo will be developed by all kinds of os, besides, remote machie and local machine might have different root format.

Thus, I hope gomodule can support auto-find pkg. It seems easy realized just like GOPATH.

- first, make sure xxx pkg is at GOPATH/pkg/mod/xxx
- import xxx

Just throw 'replace' and 'require' away on this case!

**Comment by toothrot** [comment]
It seems like this would be non-deterministic if two packages have the same name.

/cc @bcmills @jayconrod @matloob

**Comment by jayconrod** [comment]
This is probably not feasible. The module cache (`$GOPATH/pkg/mod`) should not be modified manually, and the `go` command shouldn't look anywhere else for imported packages.

Is there a reason you can't use one of the workflows for private repositories described in [Private modules](https://golang.org/ref/mod#private-modules)? In most cases, you'd name your module after the repository URL (like `github.com/corp/mod` or `corp.example.com/mod.git`), then set `GOPRIVATE=git.com/corp` or `GOPRIVATE=corp.example.com`).

**Comment by kevlar700** [comment]
Frankly the private modules information seems meant for private hosting on github and is a pain to understand when you should be doing a hundred other things. I feel like modules were not designed with replacing GOPATH in mind. I shall probably move to a mono repo solution with sshfs be as replace seems buggy. Unfortunately there isn't a good solution for Windows hosts, either. Not sure if [this helps](https://roberto.selbach.ca/go-proxies) but hard to see if everything will keep working. Likely will work with a second  goproxy direct. Seems ridiculous!

**Comment by fwhezfwhez** [comment]
I hope go module has a more graceful, compatible style for some shared packages. It might look like:
```mod
module appname

go 1.13
require (
        ...
)

replace(
     ...
)

// xxx will refer to GOPATH/mod/native/xxx
// gog.xq5.com refer to GOPATH/mod/native/gog.xq5.com/yyy/zz
native(
   xxx
   gog.xq5.com/yyy/zz
)
```

Or, add a scheme that first find pkg from /gopath/mod/pkg/xxx, if not found, then /gopath/src/xxx, otherwise mod/native/xxx.


Next profile t oversions of a same pkg, it can share scheme of mod. All pkgs can look like  `GOPATH/mod/native/xxx@v1.2`

**Comment by fwhezfwhez** [comment]
> This is probably not feasible. The module cache (`$GOPATH/pkg/mod`) should not be modified manually, and the `go` command shouldn't look anywhere else for imported packages.
> 
> Is there a reason you can't use one of the workflows for private repositories described in [Private modules](https://golang.org/ref/mod#private-modules)? In most cases, you'd name your module after the repository URL (like `github.com/corp/mod` or `corp.example.com/mod.git`), then set `GOPRIVATE=git.com/corp` or `GOPRIVATE=corp.example.com`).

Private package named 'eagle'. This kind of packages have no prefix domain.

**Comment by jayconrod** [comment]
Closing this issue because it's not feasible. The module cache is just meant to be a cache; its contents are not editable.

I do agree that private and local modules are difficult to use, and we should streamline those workflows. But this kind of change to the module cache is not something we can do.

**Comment by fwhezfwhez** [comment]
@jayconrod Can go.mod support read system env value? It's like 
```mod
replace local/pkg => ${GOPATH}/local/pkg
```

**Comment by jayconrod** [comment]
@fwhezfwhez That doesn't work at the moment, but it's probably feasible. I'd hesitate to recommend that, since a `go.mod` checked in by one developer would not work for someone else on their team. Relative paths within the same repo are more likely to work.

#33586 is similar though.

Also if #26640 were implemented, it wouldn't be important for directives in a `go.mod.local` file to work for other devs.
