### ISSUE TITLE
x/sys: undefined: unix.SYS_IOCTL when compiling for OSX

### ISSUE THREAD

**Issue by andig** [golang/go#43494]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/andig/Library/Caches/go-build"
GOENV="/Users/andig/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/andig/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/andig/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/andig/htdocs/gokrazy/tools/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/73/89ycv7qn51j4kbm04jsz9b840000gn/T/go-build954882536=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Migrated from https://github.com/gokrazy/tools/issues/17. 

    go run github.com/gokrazy/tools/cmd/gokr-packer -hostname foo -overwrite foo -target_storage_bytes=1153441792 github.com/gokrazy/hello

Compile working with

	golang.org/x/sys v0.0.0-20200523222454-059865788121

### What did you expect to see?

Compile ok

### What did you see instead?

Compiling `gokrazy` fails when newer `x/sys` is used:

    golang.org/x/sys v0.0.0-20201015000850-e3ed0017c211

    # github.com/gokrazy/tools/cmd/gokr-packer
    cmd/gokr-packer/parttable_darwin.go:21:33: undefined: unix.SYS_IOCTL
    cmd/gokr-packer/parttable_darwin.go:24:33: undefined: unix.SYS_IOCTL

Looks as if `unix.SYS_IOCTL` has vanished for `darwin` between v0.0.0-20200523222454-059865788121...v0.0.0-20201015000850-e3ed0017c211. I'll try to bisect.

**Comment by andig** [comment]
Bisect good:

    golang.org/x/sys@3aab700007d75c6b1abee24ba9b040898310d0f7

bad: 

    golang.org/x/sys@196b9ba8737a10c9253b04174f25881e562da5b8

**Comment by ALTree** [comment]
This looks like #41868.

> golang.org/x/sys v0.0.0-20201015000850-e3ed0017c211

This is before the fix for #41868. Can you upgrade to latest and test again?

**Comment by andig** [comment]
> Can you upgrade to latest and test again?

Working with @latest. Thank you :)
