### ISSUE TITLE
x/tools/gopls: report diagnostics for embed comment embed package imported

### ISSUE THREAD

**Issue by wingyplus** [golang/go#43497]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +9abbe27710 Mon Dec 21 04:23:39 2020 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Can be reproduce on gopls 0.6.1.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/thanabodee/Library/Caches/go-build"
GOENV="/Users/thanabodee/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/thanabodee/pkg/mod"
GONOPROXY="<hidden>/*"
GONOSUMDB="<hidden>/*"
GOOS="darwin"
GOPATH="/Users/thanabodee"
GOPRIVATE="<hidden>/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/thanabodee/tools/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/thanabodee/tools/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="devel +9abbe27710 Mon Dec 21 04:23:39 2020 +0000"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x7/tl6gyzn92vzcr35t94xgt6y00000gp/T/go-build2368787650=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Try it with this code:

```go
package main

import (
	"fmt"
)

//go:embed hello.txt
var s string

func main() {
	fmt.Println(s)
}
```

### What did you expect to see?

Diagnostics should report as an error on line 7 (embed comment). Just like compiler report:

```
$ go run main.go
# github.com/wingyplus/test_embed
./main.go:7:3: //go:embed only allowed in Go files that import "embed"
```

### What did you see instead?

Diagnostics didn't report anything.

**Comment by stamblerre** [comment]
It looks like this has been rendered obsolete by recent changes, described in https://github.com/golang/go/issues/43217.

**Comment by wingyplus** [comment]
Thanks for pointing out. That's sound reasonable.
