### ISSUE TITLE
time: Marshal/Unmarshal Text/JSON - inconsistent results with +00:00 offset times 

### ISSUE THREAD

**Issue by rcowsill** [golang/go#43501]
### What version of Go are you using (`go version`)?

Go Playground (go1.14.13)

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Go Playground (go1.14.13)

### What did you do?
https://play.golang.org/p/Mk0RB83WgR-
```
timeText := "2020-12-26T14:36:48+00:00"
fmt.Printf("%v\n", timeText)

var t time.Time
t.UnmarshalText([]byte(timeText))

text, _ := t.MarshalText()
fmt.Printf("%v\n", string(text[:]))
```

### What did you expect to see?
```
2020-12-26T14:36:48+00:00
2020-12-26T14:36:48+00:00
```

### What did you see instead?

```
2020-12-26T14:36:48+00:00
2020-12-26T14:36:48Z
```

### Details
See extended example at: https://play.golang.org/p/ABJgLlT-XvG.

That shows how UnmarshalText and UnmarshalJSON both treat times with "+00:00" offset as distinct from those with an offset of "Z". The "+00:00" unmarshals as a local time with 0s offset from UTC, while the "Z" case unmarshals as a UTC time.

MarshalText and MarshalJSON, on the other hand, treat local times with 0 offset from UTC as identical to UTC times: both are output in "Z" form.

Compare with UnmarshalBinary and MarshalBinary, which are symmetrical for this case. A local time with 0s offset from UTC is preserved as such after passing through MarshalBinary and UnmarshalBinary.

I'd expect text and JSON Marshal/Unmarshal to be symmetrical for this case too.

**Comment by toothrot** [comment]
note: the playground version is go1.15.6.

See #12141, #10089, #17875, and others. 

I don't believe this is a bug, nor should MarshalBinary behave similarly to MarshalJSON/MarshalText. `RFC 3339` has multiple ways of semantically representing UTC, while the binary encoding does not. Feel free to ask on golang.org/wiki/Questions for details on `time` and JSON/text encodings.

**Comment by rcowsill** [comment]
> See #12141, #10089, #17875, and others.

The first two both relate to the zero Time. As of go1.15.6 the examples in those issues preserve the value across marshal/unmarshal (eg https://play.golang.org/p/VXUScwoGAH). This may have been fixed by https://github.com/golang/go/commit/5fbf35dc3fadd29785739fcec061d42157ea7861.

#17875 does appear to be a duplicate of this bug. Unfortunately the suggestion to use `Equal` is not suitable for my use case. Using `Equal` instead of `==` would mean that times with different offsets could compare equal (eg 14:00:00+01:00 and 15:00:00+02:00).

> I don't believe this is a bug, nor should MarshalBinary behave similarly to MarshalJSON/MarshalText. `RFC 3339` has multiple ways of semantically representing UTC, while the binary encoding does not.

I'm not sure I understand this point. Go's Time binary encoding has distinct representations for UTC and "local time with 0s offset from UTC", as far as I can see: https://play.golang.org/p/Wm0zG75c93a

As shown in that example, those two representations are preserved across a binary marshal/unmarshal pair. Am I misunderstanding what you're saying here?
