### ISSUE TITLE
x/tools/gopls: Options "completeUnimported" and "completionDocumentation" are not allowed.

### ISSUE THREAD

**Issue by thep0y** [golang/go#43509]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/thepoy/.cache/go-build"
GOENV="/home/thepoy/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/thepoy/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/thepoy/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/thepoy/development/go/exercises/web/fiber/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build053098660=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I just want to be able to use `gopls` to complete auto import packages and document prompts.
<details><summary><code>settings</code></summary><br><pre>
    "go.docsTool": "gogetdoc",
    "go.testFlags": [
        "-v",
        "-count=1"
    ],
    "go.buildTags": "",
    "go.buildFlags": [],
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.coverOnSave": false,
    "go.useCodeSnippetsOnFunctionSuggest": false,
    // "go.formatTool": "goimports",
    "go.gocodeAutoBuild": false,
    "go.goroot": "/usr/local/go",
    "go.gopath": "/home/thepoy/go",
    "go.toolsGopath": "/home/thepoy/go",
    // "go.autocompleteUnimportedPackages": true,
    "go.useLanguageServer": true,
    "[go]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
        "editor.snippetSuggestions": "none",
    },
    "go.toolsEnvVars": {
        "GO111MODULE": "on",
    },
    "gopls": {
        "usePlaceholders": true,
        "completeUnimported": true,
        "completionDocumentation": true,
        "hoverKind": "SynopsisDocumentation"
    },
</pre></details>

### What did you expect to see?

I want to know why there are two warnings, because these two options are working properly.

### What did you see instead?
![截图录屏_选择区域_20210105135038](https://user-images.githubusercontent.com/51874567/103611327-04710280-4f5d-11eb-97fd-f96805000d45.png)

**Comment by stamblerre** [comment]
These options are no longer supported, as both of them are now on by default. You can remove them from your settings and nothing will change.
