### ISSUE TITLE
x/pkgsite: suggest canonical module/package path when visiting repository path

### ISSUE THREAD

**Issue by danp** [golang/go#43518]
I was recently browsing https://github.com/rsc/rf and wanted to see its godoc so I naively visited https://pkg.go.dev/github.com/rsc/rf. This presented me with the `Oops! We couldn't find “github.com/rsc/rf”.` page which confused me.

Then I realized it may have a different canonical module path, so I checked go.mod and indeed it's at rsc.io/rf. Visiting https://pkg.go.dev/rsc.io/rf then worked as expected.

It would be nice if pkgsite suggested visiting https://pkg.go.dev/rsc.io/rf to me when visiting https://pkg.go.dev/github.com/rsc/rf. It seems to already know that rsc.io/rf comes from github.com/rsc/rf as part of linking github.com/rsc/rf under "Repository" at https://pkg.go.dev/rsc.io/rf.

This would also align with what happens when trying to `go get github.com/rsc/rf` in an existing module, which does suggest the canonical path:

```
% go get github.com/rsc/rf 
go: downloading github.com/rsc/rf v0.0.0-20210102024717-be19e66fb52d
go: github.com/rsc/rf upgrade => v0.0.0-20210102024717-be19e66fb52d
go get: github.com/rsc/rf@v0.0.0-20210102024717-be19e66fb52d: parsing go.mod:
	module declares its path as: rsc.io/rf
	        but was required as: github.com/rsc/rf
```

**Comment by mvdan** [comment]
As someone who uses vanity import paths, this would be welcome. Too many users still default to assuming they can use the github URL as-is, as either an import path or for the docs. That should fail and it already does, but the pkgsite failure is confusing with the 404.

**Comment by julieqiu** [comment]
If you visit https://pkg.go.dev/github.com/rsc/rf and click on the `Request github.com/rsc/rf` button, it'll show this message:

![image](https://user-images.githubusercontent.com/5943521/103807404-53359f80-5024-11eb-8f25-e5358fa52bad.png)

We're working on a change soon to show this page by default, and redirect users to the appropriate vanity import path.
