### ISSUE TITLE
go tool compile not support module-aware

### ISSUE THREAD

**Issue by edunx** [golang/go#43512]
<pre>
$ go version:go1.15 linux/amd64

</pre>

$ go env
```shell
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/edunx/.cache/go-build"
GOENV="/home/edunx/.config/go/env"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOMODCACHE="/home/edunx/go/3rd/pkg/mod"
GOOS="linux"
GOPATH="/home/edunx/go/3rd"
GOROOT="/home/edunx/go"
GOSUMDB="sum.golang.org"
GOTOOLDIR="/home/edunx/go/pkg/tool/linux_amd64"
```

## can't find import
go tool compile -I $GOPATH/pkg/mod -o kafka.o  *.go
kafka.go:6:2: can't find import: "golang.org/x/time/rate

**Comment by mvdan** [comment]
You should use `go build`, not `go tool coompile` directly.

The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
