### ISSUE TITLE
cmd/go2go: improve error messages for missing or superfluous type constraints

### ISSUE THREAD

**Issue by candlerb** [golang/go#43527]
### What version of Go are you using (`go version`)?

go2go playground

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

1. https://go2goplay.golang.org/p/m9YUDBTWwpA
    ```
    func (m *MyMap[KT,VT comparable]) set(k KT, v VT) { ...
    ```

2. https://go2goplay.golang.org/p/GDxiXiIIti7
    ```
    func blah[T1, T2](x T1) T2 { ...
    ```

### What did you expect to see?

1. error to the effect that a constraint was used in a place where it's not allowed
2. error to the effect that a type constraint is missing

### What did you see instead?

1. "missing ',' in type argument list"
2. "all type parameters must be named" (even though they _were_ named!)

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by griesemer** [comment]
The first error is fixed in the latest (internal, not deployed version). The 2nd error is correct but misleading: Since the type parameter list is `[T1, T2]` and since type parameter lists are syntactically like regular parameter lists (but for the `[]`'s), it looks like a parameter list with two constraints `T1` and `T2` and without explicitly named type parameters. For comparison, note that `func f(int, int){}` is a valid function declaration with unnamed value parameters.

Anyway, agreed that the error message should be better.

**Comment by candlerb** [comment]
A similar case occurs when defining generic *types* if you omit the constraint on the type parameter, e.g.
https://go2goplay.golang.org/p/GqCc1gE36NL

That is, if you write
```
type slot[T] ...
```
instead of
```
type slot[T any] ...
```

In the go2go playground, the error currently says "undeclared name: T", rather than "type parameter T is missing type constraint" 

> For comparison, note that `func f(int, int){}` is a valid function declaration with unnamed value parameters.

Ugh, I didn't realise that was allowed.  If you want to discard arguments, you can also write `func f(_, _ int){}`, and to me that makes the intention clearer.

**Comment by ianlancetaylor** [comment]
"type slot[T]  _some_type_" defines `slot` as an array of length `T` of element type _some_type_.  If `T` is not defined anywhere, then `undeclared name: T` is a correct error message.

That said, we might want to tweak the compiler error message here to make clear that the type is being interpreted as an array type.

**Comment by ianlancetaylor** [comment]
"type slot[T]  _some_type_" defines `slot` as an array of length `T` of element type _some_type_.  If `T` is not defined anywhere, then `undeclared name: T` is a correct error message.

That said, we might want to tweak the compiler error message here to make clear that the type is being interpreted as an array type.
