### ISSUE TITLE
cmd/link: provide a way to always use external linking if cgo is used

### ISSUE THREAD

**Issue by mwhudson** [golang/go#43525]
This came up as a potential solution for #43505 but I've wanted it for other reasons too (mostly because of other tools like patchelf that rely on implementation details of more common linkers): I would like a way to always use external linking if cgo is used, or to put it another way, never use internal linking to generate a dynamically linked binary. -linkmode and GO_EXTLINK_ENABLED control aspects of this behaviour but can't be used to get what I want.

**Comment by cherrymui** [comment]
Could you explain why `-linkmode=external` doesn't do what you want? It will use external linking even if cgo is not used, but that doesn't seem a big problem.

**Comment by mwhudson** [comment]
If you always external link, you always get a dynamic executable. I wouldn't mind that, but I thinks some other people might.
