### ISSUE TITLE
crypto/ecdsa: change hashToBytes to use copy instead of calling another function

### ISSUE THREAD

**Issue by pschou** [golang/go#43532]
Just reducing a double function call to a byte copy.  A TODO request.  ;)

Pull request
https://github.com/golang/go/pull/43531

Pull request discussion is here:
https://go-review.googlesource.com/c/go/+/281832

**Comment by mvdan** [comment]
This does not need to be a proposal. You wouldn't even need an issue really, since it's just an internal change that already had a TODO.

Also CC @mundaym.

**Comment by pschou** [comment]
Oh-- oops!  Thanks for the heads up here.  I didn't realize this.  Feel free to close it. :P
