### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by fulkgl** [golang/go#43534]
### What version of Go are you using (`go version`)?

<pre>
$ go version
</pre>
go version go1.15.6 windows/amd64

### Does this issue reproduce with the latest release?

yes. 2021-01-05 download and install.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\User\AppData\Local\go-build
set GOENV=C:\Users\User\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\User\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\User\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\User\AppData\Local\Temp\go-build600556626=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Download windows 64 bit and install. During the install a GUI windows asked for the install location with a default of C:\GO.
I changed that to D:\GO. This machine the C drive is a small SSD and the D drive a large hard disk. The install worked. But, a few issues.
(1) env var set to GOPATH=C:\Users\User\go
There is no C:\Users\User\go dir.
(2) env var PATH has D:\Go\bin; added (which is correct) but then it also has added C:\Users\User\go\bin (which is wrong, does not exist).
(3) website (https://golang.org/doc/tutorial/getting-started) directions for "write some code" (the obligatory hello world, thx K+R). For windows it says "cd %HOMEPATH%". To be technically correct, it should have 2 lines. First "%HOMEDRIVE%" and "cd %HOMEPATH%" for the second line.
(4) website section "Call code in an external package". I think it wants me to install a package. But the directions are not clear. Change "Doc" to "Documentation". Someone used short hand. New users that's a bad idea.

BTW, on a different machine I did the install on a Big Sur Mac machine and without changing the default install location everything worked. 

### What did you expect to see?

MSI installer apparently wasn't expecting someone like me to change the install location.

**Comment by AlexRouSg** [comment]
`GOPATH` is **not** the install location, it is something like your workspace.
`GOPATH/bin` is the location to put compiled binaries when building programs with `go install` or using `go get` to download and compile programs.

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.

**Comment by ALTree** [comment]
(4) is a valid point IMO. The tutorial says "On the Doc tab" but on pkg.go.dev that tab is "Documentation"; should probably fix the tutorial.
