### ISSUE TITLE
x/tools/gopls: regtest flakes on android-amd64-emu

### ISSUE THREAD

**Issue by findleyr** [golang/go#43554]
At least 2 regtests are flaking with some regularity on android-amd64-emu: TestWorkspaceDirAccess and TestUnimportedCompletion.

Due to the nature of these failures (they look like races), I don't think we should just ignore them. However, android is a low priority for gopls and they are causing noise on the builders.

I think we should exclude them from `-short` for now, but follow up.

CC @stamblerre

**Comment by stamblerre** [comment]
Agreed that we should look at these tests ASAP.

**Comment by findleyr** [comment]
I *think* this is now fixed, but I'll wait for more evidence that flakes are gone before closing.
