### ISSUE TITLE
net/url: why not return dst.String() directly?

### ISSUE THREAD

**Issue by rising622** [golang/go#43587]
https://github.com/golang/go/blob/304f769ffc68e64244266b3aadbf91e6738c0064/src/net/url/url.go#L1048

why not return dst.String() directly

**Comment by mvdan** [comment]
Most likely because you don't know if dst has a slash as a prefix?

The code doesn't seem terribly efficient in the case where the slash already exists, but I don't know if that actually matters.

**Comment by ianlancetaylor** [comment]
It's for historical reasons.  See https://golang.org/cl/264817.

But we can clean it up.  Sent https://golang.org/cl/282673.
