### ISSUE TITLE
go build error in docker

### ISSUE THREAD

**Issue by CanYouGiveMeAName** [golang/go#43586]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>
1.13.6
### Does this issue reproduce with the latest release?

Do not try. 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
In docker of CentOS.
### What did you do?

go build

### What did you see instead?

/usr/local/go/src/crypto/md5/md5.go:15:2: read /usr/local/go/src/encoding/binary/binary.go: read /usr/local/go/src/encoding/binary/binary.go: permission denied\r\n

**Comment by mengzhuo** [comment]
Hi, 

The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.

p.s. It's a permission issue, try adding sudo.

**Comment by agnivade** [comment]
What @mengzhuo said. Closing.
