### ISSUE TITLE
x/net/http2: ConnState Unable to track

### ISSUE THREAD

**Issue by fsyyft** [golang/go#43585]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

> 1.15.6

### Does this issue reproduce with the latest release?

> Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```
```

### What did you expect to see?

`net/http` package `Server` struct  in the SDK have `ConnState func(net.Conn, ConnState)`, But not exists in the 'Server' struct of 'x/net/http2'

With the `h2c` feature, when the state variable is converted to `http.StateHijacked` , I will no longer know the subsequent state of the connection.

I expect to be able to follow the status of this TCP connection until it is closed.

**Is there such a function or a flexible solution? Thank you**

**Comment by mengzhuo** [comment]
Hi, fsyyft

The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.

**Comment by cagedmantis** [comment]
@mengzhuo is correct. We don't use the issue tracker for questions. Thank you for your interest in Go!
