### ISSUE TITLE
gollvm: undefined symbol: os.direntType

### ISSUE THREAD

**Issue by timmyyuan** [golang/go#43583]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16beta1 gollvm LLVM 12.0.0git linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/tools"
GOVCS=""
GOVERSION="go1.16beta1 gollvm LLVM 12.0.0git"
GCCGO="/usr/local/bin/llvm-goc"
AR="ar"
CC="/usr/bin/cc"
CXX="/usr/bin/c++"
CGO_ENABLED="1"
GOMOD="/root/go/src/google.golang.org/grpc/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1383028238=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
</pre></details>

### What did you do?

```
git clone https://github.com/grpc/grpc-go.git google.golang.org/grpc
cd google.golang.org/grpc && make test
```

### What did you expect to see?

test passed

### What did you see instead?

```
go test -cpu 1,4 -timeout 7m google.golang.org/grpc/...
go: symbol lookup error: /usr/local/lib64/libgo.so.12git: undefined symbol: os.direntType
Makefile:20: recipe for target 'test' failed
```

**Comment by ianlancetaylor** [comment]
CC @thanm

**Comment by ianlancetaylor** [comment]
The function is defined in os/dir_gccgo_c.c.

**Comment by thanm** [comment]
Thanks, I'll take a look.

**Comment by thanm** [comment]
I've checked in a fix for this issue.
