### ISSUE TITLE
encoding/xml: Expose xml.Decoder.line

### ISSUE THREAD

**Issue by rzajac** [golang/go#43589]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

Creating custom XML schema validator.

### What did you expect to see?

It would be great to expose `xml.Decoder.line`. Creating custom errors with line numbers is better then offset. The offset is already available through `InputOffset()` method.

**Comment by seankhliao** [comment]
Merging into proposal #45628
