### ISSUE TITLE
stringer command not found

### ISSUE THREAD

**Issue by Nurs717** [golang/go#43590]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.15.6
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/admin/Library/Caches/go-build"
GOENV="/Users/admin/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/admin/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/admin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/54/ty3x9l1s18jb2hnjr4ymw0xr0000gn/T/go-build689003330=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
when i'm trying to use stringer package with command stringer -type=Pill
this occurs zsh: command not found: stringer
am I doing right?

### What did you expect to see?

creating new file pill_stringer.go

### What did you see instead?
zsh: command not found: stringer

**Comment by AlexRouSg** [comment]
If you installed stringer with `go get` the binary is placed into `${HOME}/go/bin` this location is not in the normal search location for binaries (i.e. the` ${PATH}` env variable).

**Comment by Nurs717** [comment]
can u please give step by step instruction or link how to do it. I'm new at it and can't catch it properly. thx

**Comment by AlexRouSg** [comment]
Search for `osx set path environment variable`

As this is not a bug, please see https://github.com/golang/go/wiki/Questions if you need more help than that.

**Comment by mvdan** [comment]
What @AlexRouSg said. The issue tracker is not for questions.
