### ISSUE TITLE
reflect: ArrayOf allows negative length

### ISSUE THREAD

**Issue by mdempsky** [golang/go#43603]
This program should probably panic instead of printing `[-100]uint8`: https://play.golang.org/p/gnjsjBoKNvQ

/cc @griesemer @ianlancetaylor

**Comment by ianlancetaylor** [comment]
I agree that this should panic.

**Comment by tpaschalis** [comment]
I'll take a stab if there's no objection!

**Comment by mdempsky** [comment]
@tpaschalis No objection. I think this should be a pretty straightforward issue to fix. Thanks.
