### ISSUE TITLE
cmd/link: "external linking is forced by" logging disrupts toolstash-check

### ISSUE THREAD

**Issue by josharian** [golang/go#43601]
I ran toolstash-check. Result:

```
linux-mips64le
linux-mipsle
linux-ppc64
linux-ppc64le
linux-riscv64
linux-s390x
aix-ppc64
android-386
android-amd64
darwin-amd64
dragonfly-amd64
freebsd-386
freebsd-amd64
freebsd-arm
freebsd-arm64
illumos-amd64
ios-amd64
# cmd/buildid
toolstash: linker output differs

inconsistent log line:
/var/folders/1t/n61cbvls5bl293bbb0zyypqw0000gn/T/go-build2025424745/b254/exe/a.out.log:206:
	2021/01/07 19:52:35 external linking is forced by: buildmode=pie
/var/folders/1t/n61cbvls5bl293bbb0zyypqw0000gn/T/go-build2025424745/b254/exe/a.out.stash.log:206:
	2021/01/07 19:52:37 external linking is forced by: buildmode=pie
# cmd/addr2line
toolstash: linker output differs

inconsistent log line:
/var/folders/1t/n61cbvls5bl293bbb0zyypqw0000gn/T/go-build2025424745/b226/exe/a.out.log:278:
	2021/01/07 19:52:36 external linking is forced by: buildmode=pie
/var/folders/1t/n61cbvls5bl293bbb0zyypqw0000gn/T/go-build2025424745/b226/exe/a.out.stash.log:278:
	2021/01/07 19:52:38 external linking is forced by: buildmode=pie
# cmd/cover
toolstash: linker output differs
```

And lots more of the same.

The change here is the timestamp of the log line. @thanm @cherrymui it'd be nice to fix this. There are several options. (Remove the logging, log that line only at higher verbosity, remove timestamps from that log entry, remove timestamps from all cmd/link logging.) Thoughts?

**Comment by thanm** [comment]
I guess I would be in favor of removing the timestamps (either from this entry or all entries).  I don't see how the stamp adds much myself.

**Comment by cherrymui** [comment]
I also think removing timestamps from all entries makes sense.

Question: how does toolstash-check invoke the linker? Passing `-v`? The `-v` flag isn't that useful to debug linker (non)deterministic issues. Maybe it can just stop passing `-v`.
