### ISSUE TITLE
cmd/cgo: document mininum gcc version

### ISSUE THREAD

**Issue by rittneje** [golang/go#43605]
When generating _cgo_export.c, cgo outputs several `#pragma GCC diagnostic ignored` directives. Such pragmas were introduced in gcc 4.6 (https://www.gnu.org/software/gcc/gcc-4.6/changes.html), so it would seem that at least that version is expected. (Ironically, the first pragma is to ignore unknown pragmas, but an older GCC will consider _that_ to be an unknown pragma.)

Unfortunately, I can't find anywhere that the minimum version has been documented. It would be helpful if it were included on one of the wiki pages, such as https://github.com/golang/go/wiki/MinimumRequirements or https://github.com/golang/go/wiki/cgo.

**Comment by ianlancetaylor** [comment]
GCC 4.6 was released in 2011.

I think it would be fine to add this the `MinimumRequirements` wiki page.  Anybody can do that.

**Comment by ALTree** [comment]
I added this to MinimumRequirements. Closing here, but feel free to edit my wording if you wish.

**Comment by dwillemv** [comment]
We are using gcc version 4.8.3. 
We are getting failures similar to those described at:
https://github.com/golang/go/issues/44880
Using go 1.16.3.

With the repro from that case, the output looks like:
/home/willem/development/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /dev/shm/go-link-383363645/000005.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status


What is the correct minimum gcc version?

**Comment by ALTree** [comment]
Are you sure you're not just hitting #43996?

**Comment by dwillemv** [comment]
You are correct. We are indeed hitting #43996. Thanks for the help.
