### ISSUE TITLE
cmd/compile: arm64Negate for floating point is not correct

### ISSUE THREAD

**Issue by lijunchen** [golang/go#43619]
### What version of Go are you using (`go version`)?
master

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
linux/arm64

### What did you do?

```go
package main

import (
        "fmt"
        "math"
)

//go:noinline
func test(a, b float64, x uint64) uint64 {
        if a < b {
                x = 0
        }
        return x
}

func main() {
        nan := math.NaN()
        fmt.Println(test(1, nan, 123))
}
```

### What did you expect to see?
123

### What did you see instead?
0

**Comment by lijunchen** [comment]
I have figured out what happened, create this issue to get an issue id for writing a test file.

**Comment by davecheney** [comment]
NaN is neither less than or greater than any number

https://play.golang.org/p/fYag0Dp6i0i

I don't think this is a bug.

**Comment by erifan** [comment]
> NaN is neither less than or greater than any number
> 
Yes, you are right. So the above case really seems to be a bug.

**Comment by lijunchen** [comment]
> NaN is neither less than or greater than any number
> 
> https://play.golang.org/p/fYag0Dp6i0i
> 
> I don't think this is a bug.

If we disable optimization, the output is 123 as expected. So there must be something wrong, I submit a patch, please take a look, thanks.
```
$ go run -gcflags -N t.go
123

$ go run t.go
0
```
