### ISSUE TITLE
x/tools/gopls: renaming mishandles embedded fields

### ISSUE THREAD

**Issue by mdempsky** [golang/go#43616]
I'd expect that if I try to use gopls to rename any of the `foo` identifiers to `bar` in the package below, then all 3 should change. However, gopls only updates 2 of them, resulting in an invalid source file.

```
package p

type foo int

var x struct { foo }

var _ = x.foo
```

I'm using gopls v0.6.2.

/cc @stamblerre @findleyr

**Comment by findleyr** [comment]
Thanks for reporting.  It looks like we just missed this case.

**Comment by mdempsky** [comment]
@findleyr Thanks for the quick fix. QQ: In the test case, it looks like it's testing renaming at the type declaration. Will the same fix also work for renaming at selector expressions (e.g., L7)?

**Comment by findleyr** [comment]
Err, no, that doesn't work.  My bad for missing that.

We need to update the corresponding logic to find the object being renamed.

**Comment by findleyr** [comment]
Upon a bit more consideration, I'm not sure this feature is perfectly symmetric.  When renaming the type name it makes sense that we should also update uses of embeddings of that type.  But it's not so clear that the reverse should hold.  If I am positioned on x.foo and perform the renaming, it could be surprising that this results in the foo type being renamed.

Perhaps we should disallow renaming embedded fields: the user should either rename the type OR give the field a name...

**Comment by mdempsky** [comment]
Yeah, I agree reporting an error instead of also renaming the type makes sense.
