### ISSUE TITLE
godoc broken for github.com/lawrencejones/pg2pubsub

### ISSUE THREAD

**Issue by lawrencejones** [golang/go#43611]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/lawrencejones/pg2pubsub 
 
### What did you do?
 
I renamed the github.com/lawrencejones/pg2pubsub to github.com/lawrencejones/pgsink a while back, but the godoc and pkg.go documentation is stuck at the old name.

I cannot create a new pkg.go package, as (I think) it's seeing the new repo as equivalent to the old? Whenever I try, it says that this path is not valid, despite my go.mod having the correct package name, and maybe I'm looking for the original name?

![image](https://user-images.githubusercontent.com/3518874/104093697-06e89a80-5284-11eb-9c3b-fc98d28a81a8.png)
 
### What did you expect to see?
 
My documentation appear under the new package name. 
 
### What did you see instead?

404.

**Comment by tmthrgd** [comment]
The highest tagged version (v0.1.0) has a [go.mod file](https://github.com/lawrencejones/pgsink/blob/v0.1.0/go.mod) with the old path. Try pushing a new tag now that you’ve changed the path in the HEAD go.mod file.

**Comment by lawrencejones** [comment]
Awesome, this looks like it works now.

Just to clean-up, is there anyway I can get the pg2pubsub package removed? Not a big deal if not, but would be good not to have two locations.

Also, thanks for your help. Was pretty confused!

**Comment by tmthrgd** [comment]
Glad that helped!

You can request packages by removed by opening an issue. Check out the instructions here: https://go.dev/about.

**Comment by lawrencejones** [comment]
Great, thank you.
