### ISSUE TITLE
x/text: overwriting a previous write

### ISSUE THREAD

**Issue by ondrejbudai** [golang/go#43623]
This [line of code](https://github.com/golang/text/blob/master/unicode/bidi/core.go#L499) of code has no effect because the value in `precedingCharacterType` is overridden later.

**Comment by davecheney** [comment]
@ondrejbudai feel free to send a PR if the tests pass after removing this line

**Comment by danishprakash** [comment]
@davecheney mind If I run the tests and send a PR?
