### ISSUE TITLE
proposal: Go 2: sync: OnDealloc for sync.Pool

### ISSUE THREAD

**Issue by pjebs** [golang/go#43634]
Currently the documentation states:

> Any item stored in the Pool may be removed automatically at any time without notification. If the Pool holds the only reference when this happens, the item might be deallocated.

It would be good if `sync.Pool` had a function `(p *Pool) OnDealloc(item interface{}) ` (Or maybe called `OnRemoval(item interface{})`, since something outside the pool may hold a reference to it)

It will operate like this:

Just before an item gets removed from the pool, then `OnDealloc()` gets called so we can call some cleanup code on the item itself.

It may or may not be vaguely related to: https://github.com/golang/go/issues/38057 and https://golang.org/pkg/runtime/#SetFinalizer

**Comment by ianlancetaylor** [comment]
What would people use this for?

Why not just use a finalizer?
