### ISSUE TITLE
x/tools/gopls: don't invalidate metadata on didOpen of go.mod

### ISSUE THREAD

**Issue by findleyr** [golang/go#43647]
This is an extension of #42529, where the solution to reload thrashing while editing the go.mod file was to only invalidate metadata on saves of the go.mod file.

Unfortunately, our invalidation logic treats didOpen notifications nearly identically to saves, as go.mod is in the "changed" set and saved == true.  This can cause problems in testing, and I also suspect could be disruptive in some large workspaces where metadata reloading takes many seconds. It's also just counter-intuitive.

Related to #43554.

Not a high priority.

**Comment by stamblerre** [comment]
This has been fixed as of https://golang.org/cl/317450.
