### ISSUE TITLE
dodeltimer

### ISSUE THREAD

**Issue by ldchao** [golang/go#43642]
https://github.com/golang/go/blob/81ea89adf38b90c3c3a8c4eed9e6c093a8634d59/src/runtime/time.go#L711
The heap manipulation in the siftupTimer() method of the dodeltimer() method also could cause our loop to skip some other timer. Can this situation cause unexpected mistakes?

**Comment by davecheney** [comment]
Thank you for raising this issue. We don't use the issue tracker for go development questions, I suggest you ask on golang-dev, https://groups.google.com/g/golang-dev, or send a change via the https://golang.org/doc/contribute.html

**Comment by ldchao** [comment]
Ok, thanks for your reply.
