### ISSUE TITLE
access: add timothy-king to go-assignees and go-approvers

### ISSUE THREAD

**Issue by timothy-king** [golang/go#43660]
https://github.com/orgs/golang/teams/go-assignees
https://github.com/orgs/golang/teams/go-approvers

Following https://github.com/golang/go/wiki/GithubAccess#assigneesSee https://golang.org/wiki/GithubAccess

**Comment by dmitshur** [comment]
Done. (A late) Welcome to the team, Tim!

CC @golang/release.
