### ISSUE TITLE
go/types, types2: type checker does not allow to use receive operation even all types in type list are channels 

### ISSUE THREAD

**Issue by tdakkota** [golang/go#43671]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +f065ff221b Tue Jan 12 15:56:55 2021 -0800 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
n/a

### What operating system and processor architecture are you using (`go env`)?
- `windows/amd64`
- go2go playground

### What did you do?

https://go2goplay.golang.org/p/4ERkDYXAVM-
Also, I got same result from `dev.typeparams` typechecker using
```
$ go tool compile -G ./example.go
```

The problem is here 
https://github.com/golang/go/blob/f065ff221b546c9ac550d947f89eb3b44b11fc2f/src/cmd/compile/internal/types2/expr.go#L156-L172

`x.typ.Chan()` returns `nil` if `x.typ` is a `*TypeParam`.
### What did you expect to see?
Successful type-check or a stub error like `generic slice expressions not yet implemented`. All types in `RecvChan[T]` type list support receive operation.

### What did you see instead?
An error
```
invalid operation: cannot receive from non-channel ch (variable of type parameter type C)
```

**Comment by tdakkota** [comment]
CC @griesemer

**Comment by griesemer** [comment]
This has not yet been implemented.

**Comment by rogpeppe** [comment]
I was about to file an issue about this when I found this one.

I'll also mention that type inference doesn't work when the type parameters are omitted from `Recv`, but I don't see any particular reason why it shouldn't.

**Comment by griesemer** [comment]
@rogpeppe Type inference does work if you remove one of the channel types from RecvChan. That is because constraint type inference requires exactly one type in the type list/set. Channels with channel directions are a bit special; they may need some special treatment. I filed a separate issue (#45920).

**Comment by griesemer** [comment]
This was fixed with the above CLs.
