### ISSUE TITLE
x/website: Getting Started tutorial doesn't work with Go 1.16

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#43672]
The [Getting Started](https://golang.org/doc/tutorial/getting-started) tutorial relies on `go run` modifying the `go.mod` automatically, which is now deprecated.

```
hello.go:5:8: no required module provides package rsc.io/quote; try 'go mod tidy' to add it
```

The tutorial should instruct the user to run `go get` immediately before editing the code *or* `go mod tidy` after editing the code.

/cc @stevetraut

**Comment by dmitshur** [comment]
Issue #43430 is related. CC @jayconrod.

Based on the discussion there, I suspect we prefer suggesting `go get` over `go mod tidy` for the specific task of adding new dependencies. (`go mod tidy` is fine to use for other module management, like removing unused dependencies.)

**Comment by jayconrod** [comment]
I think at tip we recommend `go get` instead of `go mod tidy`. In any case, the text will need to be updated.

I'll take a look soon after 1.16 release blockers are resolved.

**Comment by FiloSottile** [comment]
I just noticed that starting in Go 1.16, `go run .` doesn't work without a module, too.

https://golang.org/cl/283635 replaced `go run hello.go` with `go run .`, so that part will break with Go 1.16 too. My suggestion would be to introduce a `go mod init` earlier, because I think modules is something every developer will encounter in the first hour, while the `command-line-arguments` package is not something they need to know about at all, and can only confuse them. Alternatively, the CL can be rolled back.

**Comment by FiloSottile** [comment]
In https://github.com/golang/go/issues/43672#issuecomment-759741625 Jay
said we should be recommending "go get" now, but the doc was updated to use
"go mod tidy". Should we switch?

>

**Comment by jayconrod** [comment]
`go mod tidy` is easier to use, but `go get` is more precise. Since this doc is targeted at new users, `go mod tidy` is probably a better choice. Either is fine though.

**Comment by stevetraut** [comment]
I've heard the two commands suggested interchangeably at times. I think we should decide what the contexts for recommending `go get` and `go mod tidy` are and stick with them in docs. 

This is clearly a new user hunk of documentation. If `go mod tidy` is best for context, then we should keep it here. However, being the easiest doesn't necessarily make it the best practice (though the easiest *should* be the best practice for new users, IMO). We also should be about introducing the best practice commands for a given workflow.
