### ISSUE TITLE
std,cmd: add test to ensure that all modules in GOROOT are tidy

### ISSUE THREAD

**Issue by dmitshur** [golang/go#43687]
We can add a test that catches and reports when the a module in GOROOT is not tidy.

Having an automated test for this will prevent it from happening without anyone noticing, and it makes it easier for humans to review CLs that modify go.mod files, since they won't need to worry about checking this manually.

It's probably not a big deal if a module isn't tidy, but it turned out to be easy and inexpensive to perform this check as part of the test for #36852 and #41409, so let's try it. (If we find that it's unhelpful, or there are situations when modules must be non-tidy, we can remove it.)

CC @golang/release.

**Comment by bcmills** [comment]
> If … there are situations when modules must be non-tidy, we can remove it.

If we find any such situation, I would consider that a usability defect in the `go` command, and I would want to fix it there instead of removing the tidiness check.
