### ISSUE TITLE
cmd/compile: better error messages for use of ... with type parameters

### ISSUE THREAD

**Issue by griesemer** [golang/go#43680]
For `main.go`:
```Go
package p
func _[T ...any]() {}
```
The compiler reports
```
main.go:2:10: ...any is not a type
main.go:2:10: invalid use of '...'
```
with `go tool compile -G main.go`.

The error messages should be better. `...` should not be permitted for type parameters during parsing.

**Comment by findleyr** [comment]
@griesemer is there anything left here now that we've merged?

**Comment by griesemer** [comment]
@findleyr I'd like to keep it open for now. I'm still wondering if this shouldn't be a syntax error.

**Comment by griesemer** [comment]
Closing this. What we have seems fine for now. We can always reconsider if people stumble of this.
