### ISSUE TITLE
go/types, types2: missing error for shifts by huge untyped integers

### ISSUE THREAD

**Issue by griesemer** [golang/go#43697]
Per the spec:
> The right operand in a shift expression must have integer type or be an untyped constant representable by a value of type uint.

for the following code
```Go
package p

var x int
var _ = x << 100000000000000000000
```
`go/types` (and `types2`) should report an error but doesn't.

For reference, `cmd/compile` reports
```
main.go:4:11: constant 100000000000000000000 overflows uint
```

**Comment by griesemer** [comment]
cc: @findleyr

**Comment by findleyr** [comment]
Now that these changes are merged to master, I believe this can be closed.  @griesemer please reopen if I'm misunderstanding something.
