### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by chosangwon93** [golang/go#43691]
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/tmax-cloud/claim-operator/api/v1alpha1
 
 
### What is your user agent?
 

 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
 
 
### Screenshot
 

 
![image](https://user-images.githubusercontent.com/66065293/104596045-c7241780-56b6-11eb-8be5-81e36817f769.png)

 
 
### What did you do?
 i updated a pkg (github.com/tmax-cloud/claim-operator)

 
 
 
### What did you expect to see?
 remove pkg  (version v0.0.0-20201224052434-e7800d54877c) from pkg.dev.go 
 
### What did you see instead?

i want to see a latest version of github.com/tmax-cloud/claim-operator pkg

**Comment by julieqiu** [comment]
The package is now showing v0.0.0-20210114131930-51d726ff53ab, which is the latest commit in your repository.

In the future, you can visit https://pkg.go.dev/github.com/tmax-cloud/claim-operator/api/v1alpha1@master to update the package.
