### ISSUE TITLE
cmd/go: add mod vendor -check

### ISSUE THREAD

**Issue by fishy** [golang/go#43706]
Very similar to https://github.com/golang/go/issues/27005, I think a `go mod vendor -check` that returns non-zero when it would make any changes to `vendor/` directory would be useful in pre-commit hooks and CIs.

Things that could be different from `go mod tidy -check` are:

1. Unlike `go mod tidy -check`, this likely requires network access to work
2. This might be more go version dependent? I think the `vendor/modules.txt` file are different between 1.15 and 1.14, not sure if this will cause problems with proposed `go mod vendor -check`.

**Comment by bcmills** [comment]
Duplicate of #27348?

**Comment by fishy** [comment]
Yea I think #27348 pretty much covered it :+1:
