### ISSUE TITLE
syscall: make new RtlGenRandom API internal and safe

### ISSUE THREAD

**Issue by aclements** [golang/go#43704]
During the Go 1.16 API audit, @rsc and I noticed that the new Windows `syscall.RtlGenRandom` API is 1. needlessly unsafe, and 2. should be added to `internal/syscall/windows` instead because `syscall` is frozen.

This is release-blocker issue to track this.

/cc @zx2c4 @alexbrainman

**Comment by zx2c4** [comment]
I'll fix it.
