### ISSUE TITLE
net/mail: mail ParseAddressList can bypass and panic  

### ISSUE THREAD

**Issue by cor0ps** [golang/go#43714]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.4 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
C:\Users\xx\go\src\awesomeProject1>go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xx\AppData\Local\go-build
set GOENV=C:\Users\xx\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\xx\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\xx\go
set GOPRIVATE=
set GOPROXY=direct
set GOROOT=C:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\xx\go\src\awesomeProject1\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\xx\AppData\Local\Temp\go-build958360038=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

https://play.golang.org/p/efQXFJo-TIC

```
package main

import (
	"net/mail"
	"strings"
)

func main() {
	//"":;
	data := "\"\":;"
	list, err := mail.ParseAddressList(data)
	if err != nil {
		return
	}
	var addrs []string
	for _, addr := range list {
		addrs = append(addrs, addr.String())
	}
	_, err = mail.ParseAddressList(strings.Join(addrs, ","))
	if err != nil {
		panic(err)
	}

}
```

### What did you expect to see?
first  input  `"":;` can  bypass 

```
if handleGroup {
   if p.consume(':') {
      return p.consumeGroupList()
   }
}
```

second  is  panic: mail: no address

### What did you see instead?
panic: mail: no address

**Comment by mengzhuo** [comment]
ParseAddressList do return an error "mail: no address" without panic as expected.

@cor0ps The panic is raised in your code not net/mail module
```	
_, err = mail.ParseAddressList("")
if err != nil {
	panic(err)
}
```

**Comment by mengzhuo** [comment]
It seems we should check on addrs number at the end of parseAddressList

https://golang.org/src/net/mail/message.go?s=5170:5224#L307
```go
		if p.empty() {
			break
		}
	}
	return list, nil // we shoud check it here
```

I can send a CL for this issue , Is it OK for you ? @cor0ps

**Comment by odeke-em** [comment]
Thank you for this report @cor0ps, thanks @mengzhuo and @ALTree for the triage! @cuonglm perhaps we should also place this on our list for fuzzing?

**Comment by cor0ps** [comment]
@mengzhuo mengzhuo  you  can  make  a  issuse   and  have questions  can   contact with me  wechat：SuperTao99

```
	if p.empty() {
			break
		}
	}
	return list, nil // we shoud check it here
```
I  aggree with you

**Comment by cor0ps** [comment]
@odeke-em  I  found  this  use  gofuzz  tools   and  i  think  this have  a   securtiy  problem  and   this  can  get  a  CVE id

**Comment by mengzhuo** [comment]
> @odeke-em I found this use gofuzz tools and i think this have a securtiy problem and this can get a CVE id ？ thanks

I don't think it's a CVE, RFC 5322 stated that empty group is allowed.

https://tools.ietf.org/html/rfc5322#section-3.4
