### ISSUE TITLE
misc/cgo/testcarchive: TestSIGPROF failure with "signal: profiling timer expired" on WSL builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#43710]
[2021-01-14T22:01:23-e125ccd/linux-amd64-wsl](https://build.golang.org/log/ef2b879282c9d905bdb9d73ac8fb16fcd6cccaad)

```
##### ../misc/cgo/testcarchive
--- FAIL: TestSIGPROF (1.25s)
    carchive_test.go:769: 
    carchive_test.go:770: signal: profiling timer expired
FAIL
```

See previously #19320.

It's not clear to me whether this failure is due to a problem in the test, in the runtime, or in WSL itself.

CC @ianlancetaylor @mengzhuo @oiooj

**Comment by oiooj** [comment]
@bcmills WSL builder’s HTTS PROXY is so slowly now, I'm working it now.

**Comment by oiooj** [comment]
The network problem solved and builders online.
