### ISSUE TITLE
x/pkgsite: show a page for an empty directory that is above a nested module

### ISSUE THREAD

**Issue by julieqiu** [golang/go#43725]
https://pkg.go.dev/google.golang.org/grpc@v1.35.0/cmd currently returns a 404, because it is a directory in the module google.golang.org/grpc that does not contain any packages.

https://pkg.go.dev/google.golang.org/grpc/cmd/protoc-gen-go-grpc however is a nested module in the parent module, https://pkg.go.dev/google.golang.org/grpc. 
  
It would be useful to show a directory page containing the nested module at https://pkg.go.dev/google.golang.org/grpc@v1.35.0/cmd.

**Comment by ya5u** [comment]
@julieqiu I'd like to take this issue

**Comment by julieqiu** [comment]
Sounds great - thanks!
