### ISSUE TITLE
x/tools/gopls: Sublime Text 3 - LSP: Error loading workspace folders(excepted 1, got 0)

### ISSUE THREAD

**Issue by thep0y** [golang/go#43746]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/thepoy/.cache/go-build"
GOENV="/home/thepoy/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/thepoy/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/thepoy/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build522328134=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

According to the official document, gopls is enabled through LSP in sublime text 3. If I do not start sublime in the terminal, gopls will report an error: `Error loading workspace folders(excepted 1, got 0).`
If you start sublime in the terminal, everything is normal.
LSP setting:
```json
{
  "clients": {
    "gopls": {
      "enabled": true,
      "command": [
        "gopls"
      ]
    }
  }
}
```

Project structure:
![图片](https://user-images.githubusercontent.com/51874567/104829446-f309ed80-58ae-11eb-8614-ca112c27941f.png)

### What did you expect to see?
I hope `gopls` can run normally.

### What did you see instead?
`gopls` is not working.

**Comment by thep0y** [comment]
The shell I use is zsh. When I installed golang, I wrote the `GOROOT` environment variable in `/etc/zsh/zshenv`, causing sublime text to fail to read `GOROOT` when it was started graphically.
I deleted the `GOROOT` environment variable in `zshenv` and added `GOROOT` to `.profile`, this problem can be solved.

**Comment by agnivade** [comment]
This is a common problem with Sublime. Personally I prefer to encode the PATH logic in the sublime config itself like this:

```json
{
	"clients":
	{
		"gopls":
		{
			"command": ["/home/agniva/go/bin/gopls",
				"-v",
				"-rpc.trace",
				"-logfile=/home/agniva/gopls.log"],
			"enabled": true,
			"env": {
				"PATH": "/home/agniva/go/bin:/usr/local/go/bin"
			},
			"scopes":["source.go"],
			"syntaxes": [
				"Packages/Go/Go.sublime-syntax",
        		"Packages/GoSublime/syntax/GoSublime-Go-Recommended.sublime-syntax",
			],
			"settings": {
				"gopls.usePlaceholders": true,
				"gopls.completeUnimported": true,
			},
			"languageId": "go"
		}
	},
}
```
