### ISSUE TITLE
cmd/link: crash on undefined functions

### ISSUE THREAD

**Issue by go101** [golang/go#43748]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16beta1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Not on the the 1.15.5 stable release.

### What did you do?

```go
package main

import "C"

func main() {}

var a func() = f

var b = g()

func f()

func g() int {
	a()
	return 0
}
```

### What did you expect to see?

Reports `main.f·f: relocation target main.f not defined` as the stable release.

### What did you see instead?

Crash:
```
# command-line-arguments
main.f·f: relocation target main.f not defined
main.f·f: reloc 1 (R_ADDR) to non-elf symbol main.f (outer=main.f) 0 (Sxxx)
panic: elfrelocsect: size mismatch 1179176 != 1087592 + 91560

goroutine 75 [running]:
cmd/link/internal/ld.elfrelocsect(0xc000146000, 0xc0001422a0, 0xc00052e2a0, 0xc00053e000, 0x11cf, 0x11cf)
	/usr/local/go/src/cmd/link/internal/ld/elf.go:1126 +0xe65
cmd/link/internal/ld.relocSectFn.func1.1(0x6f23c8, 0xc000146000, 0xc0001422a0, 0xc00052e2a0, 0xc00053e000, 0x11cf, 0x11cf, 0xc000d6d900, 0xc000144460)
	/usr/local/go/src/cmd/link/internal/ld/asmb.go:202 +0x66
created by cmd/link/internal/ld.relocSectFn.func1
	/usr/local/go/src/cmd/link/internal/ld/asmb.go:201 +0x1bd
```

**Comment by odeke-em** [comment]
Thank you @go101 for this report, thank you @seankhliao for the triage; happy New Year to the both of you!

This is a regression from Go1.15, and thus I have marked it as a release blocker. Kindly cc-ing @mdempsky @cuonglm, and I'll also take a look too.

**Comment by mdempsky** [comment]
I see the same issue with Go 1.15.6, so I don't think this is a release blocker?

**Comment by mdempsky** [comment]
The program isn't valid anyway, unless there are additional files that weren't included in the report. You can't have a program that depends on function `main.f`, but then not supply a definition for it.
