### ISSUE TITLE
cmd/compile: strange initialization loop error

### ISSUE THREAD

**Issue by valyala** [golang/go#43741]
### What version of Go are you using (`go version`)?

go1.15

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```
GOOS=linux
GOARCH=amd64
```

### What did you do?

Tried to compile the following code:

```go
var a = f

func f() {
	a()
}
```

### What did you expect to see?

It should successfully compile, since `f` isn't called during `a` initialization.

### What did you see instead?

Compiler returns the following error:

```
./prog.go:3:5: initialization loop:
	prog.go:3:5: a refers to
	prog.go:5:6: f refers to
	prog.go:3:5: a
```

### Additional details

The following code with identical behavior successfully compiles:

```go
var a func()

func init() {
	a = f
}

func f() {
	a()
}
```

This minimal code snipped has been reduced from real production code, which uses global function table for expression evaluation. Below is a pseudo-code:
```go
type expr interface{}

type funcExpr struct {
	FuncName string
	Arg      expr
}

type F func(arg expr) float64

var funcTable = map[string]F{
	"abs": abs,
}

func abs(arg expr) float64 {
	var value float64
	switch t := arg.(type) {
	case *funcExpr:
		value = funcTable[t.FuncName](t.Arg)
	default:
		value = arg.(float64)
	}
	return math.Abs(value)
}
```

**Comment by seankhliao** [comment]
looks like it behaves according to spec, [package initialization](https://golang.org/ref/spec#Package_initialization):
* `var a = f` means `a` depends on `f`
* `func f() { a() }` means `f` depends on `a` , from spec:
  > A variable, function, or method x depends on a variable y if x's initialization expression or body (for functions and methods) contains a reference to y or to a function or method that depends on y.

**Comment by go101** [comment]
Here, how `a` depends on `f` is not very clear. `a` surely depends on `f`, but it doesn't depend on `f`'s body.

**Comment by ianlancetaylor** [comment]
The spec is intended to be clear and straightforward to implement for all Go compilers.  This is working as intended.

**Comment by go101** [comment]
But it looks the rule is unnecessarily to too restrict.

**Comment by ianlancetaylor** [comment]
The rule is stricter than it has to be, but not unnecessarily so.  A less strict rule would have to distinguish between a reference to a function and a call of that function, and would have to work for code like

```Go
var a = func() int { x := f; return x() }()
```

Since the most important goal is a spec that is clear and straightforward to implement for all Go compilers, we did not try to write a spec that would handle cases like that in their full generality.
