### ISSUE TITLE
x/pkgsite: github.com/nilsocket/sanitize & github.com/nilsocket/dl

### ISSUE THREAD

**Issue by nilsocket** [golang/go#43743]
Repo1: github.com/nilsocket/sanitize
Repo2: github.com/nilsocket/dl

Please remove my packages from pkg.go.dev i.e., go sum database and other sister sites.

I have deleted the repository, without knowing that I will not be able to update later (i.e., force push doesn't work).

Thank you.

**Comment by julieqiu** [comment]
Done.
