### ISSUE TITLE
x/pkgsite: incorrect item for github.com/ajstarks/decksh

### ISSUE THREAD

**Issue by ajstarks** [golang/go#43754]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/ajstarks/deck/cmd/dchart
 
 
### What is your user agent?
 
Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

### Screenshot
 
![image](https://user-images.githubusercontent.com/169692/104862303-19587900-5901-11eb-8a3d-1c0dc2a393a9.png)

 
### What did you do?

The path is incorrect -- it points to a defunct command when it should be the library at github.com/ajstarks/decksh
  
 
### What did you expect to see?
 
 The correct module for github.com/ajstarks/decksh
 
### What did you see instead?

the item is incorrectly under  github.com/ajstarks/deck > cmd > dchart

**Comment by seankhliao** [comment]
It appears you have 2 repos https://github.com/ajstarks/deck and https://github.com/ajstarks/decksh

The warning label in the version identifier already indicates that it is not part of the latest version of `deck`, and it doesn't show up in the listing from the latest revision: https://pkg.go.dev/github.com/ajstarks/deck/cmd

**Comment by ajstarks** [comment]
Note that  https://pkg.go.dev/github.com/ajstarks/deck/cmd should be removed.  The core issue is that decksh won't be built because it cannot find dchart.

**Comment by julieqiu** [comment]
> Note that https://pkg.go.dev/github.com/ajstarks/deck/cmd should be removed. 

Would you like us to remove that package entirely from the site, per https://go.dev/about#removing-a-package?

> If you are the author of a package and would like to have it removed from pkg.go.dev, please file an issue on the Go Issue Tracker with the path that you want to remove.
>
> Note that we can only remove a module entirely from the site. We cannot remove it just for specific versions.

**Comment by ajstarks** [comment]
@julieqiu yes, please remove it as per your site.  I suspect this old package is causing a clash that is preventing other module aware packages from building.  (you cannot build decksh because it depends on dchart which it cannot find.)

**Comment by jba** [comment]
Removed.
