### ISSUE TITLE
Function nesting calls a function that returns a pointer that implements the error, the returned error is always not equal to nil

### ISSUE THREAD

**Issue by gbabyX** [golang/go#43767]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>
go version go1.15.4 darwin/amd64

### Does this issue reproduce with the latest release?

No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/annoymous/Library/Caches/go-build"
GOENV="/Users/annoymous/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/annoymous/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/annoymous/go"
GOPRIVATE=""
GOPROXY=""
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you do?

https://play.golang.org/p/DPFR2p4-7Lv
```
package main

import (
	"fmt"
)

type ExampleError struct {
	Code int
	Err  error
}

func (e *ExampleError) Error() string {
	return fmt.Sprintf("code[%d], %s", e.Code, e.Err)
}

func func1() error {
	return func2()
}

func func2() *ExampleError {
	return nil
}

func main() {
	if err := func1(); err != nil {
		fmt.Print("err != nil")
	}
}
```

### What did you expect to see?
Not Print

### What did you see instead?
Print `err != nil`

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.

**Comment by davecheney** [comment]
This is known as a typed nil, there's an FAQ entry about this, https://golang.org/doc/faq#nil_error
