### ISSUE TITLE
x/pkgsite: v0.20.2 missing for k8s.io/client-go

### ISSUE THREAD

**Issue by nikhita** [golang/go#43775]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/k8s.io/client-go?tab=versions
 
### What is your user agent?
 

Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0
 
 
 
### Screenshot
 

 
![Screenshot from 2021-01-19 20-54-24](https://user-images.githubusercontent.com/16105680/105055029-a255e880-5a98-11eb-9577-3ab7e8644620.png)

 
 
### What did you do?
 

 
Originally reported in https://github.com/kubernetes/client-go/issues/923

The tag `v0.20.2` for k8s.io/client-go is missing in https://pkg.go.dev/k8s.io/client-go?tab=versions but exists at:
- https://github.com/kubernetes/client-go/tree/v0.20.2, https://github.com/kubernetes/client-go/releases/tag/v0.20.2
- https://proxy.golang.org/k8s.io/client-go/@v/v0.20.2.info
 
 
### What did you expect to see?
 
 The tag `v0.20.2` for k8s.io/client-go exists at https://pkg.go.dev/k8s.io/client-go?tab=versions
 
### What did you see instead?

The tag is missing.

cc @shu-mutou @dims

**Comment by julieqiu** [comment]
Added - you can see this version at https://pkg.go.dev/k8s.io/client-go@v0.20.2 and  https://pkg.go.dev/k8s.io/client-go?tab=versions:

<img width="412" alt="Screen Shot 2021-01-19 at 11 58 25 AM" src="https://user-images.githubusercontent.com/5943521/105067396-a4468a00-5a4d-11eb-886e-6e686e40f9f9.png">

**Comment by nikhita** [comment]
@julieqiu thank you!
