### ISSUE TITLE
wiki: CodeReviewComments change

### ISSUE THREAD

**Issue by bunyk** [golang/go#43770]
[Imports section](https://github.com/golang/go/wiki/CodeReviewComments#imports) shows example: 

```
import (
	"fmt"
	"hash/adler32"
	"os"

	"appengine/foo"
	"appengine/user"

	"github.com/foo/bar"
	"rsc.io/goversion/version"
)
```
From which it is not obvious that appengine is third-party package, not stdlib. And this is legacy way to import appengine: https://github.com/golang/appengine#updating-from-legacy-import-appengine-packages

I think this group should be removed from example, or updated.

**Comment by seankhliao** [comment]
I've removed the group.
