### ISSUE TITLE
cmd/go: TestScript/mod_get_fallback relies on x/tools not being tagged

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#43795]
The script assumes the go get log will say `golang.org/x/tools/@latest` rather than `golang.org/x/tools/@v/v0.1.0`.

**Comment by rolandshoemaker** [comment]
This is also an issue on 1.14 and 1.15. On 1.15 TestScript/get_update_unknown_protocol is also broken.
@gopherbot please open backport issues.

**Comment by dmitshur** [comment]
CC @jayconrod, @matloob, @bcmills via [owners](https://dev.golang.org/owners).
