### ISSUE TITLE
cmd/go: handle space in path to C compiler

### ISSUE THREAD

**Issue by apmckinlay** [golang/go#43808]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.7 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\andrew\AppData\Local\go-build
set GOENV=C:\Users\andrew\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\andrew\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\andrew\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=V:\gsuneido\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\andrew\AppData\Local\Temp\go-build158816006=/tmp/go-build -gno-record-gcc-switches
GOROOT/bin/go version: go version go1.15.7 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.15.7
gdb --version: GNU gdb (GDB) 8.1
</pre></details>

### What did you do?

<pre>
> go build -v -ldflags "-s -w -X 'main.builtDate=Jan 20 2021 11:17:27' -X main.mode=gui -H windowsgui"
</pre>

### What did you expect to see?

Successful build

### What did you see instead?

<pre>
# github.com/apmckinlay/gsuneido/builtin/goc
cgo: exec c:\Program: exec: "c:\\Program": file does not exist
</pre>

It builds successfully on 1.15.6 (and 1.16beta1)

I cut my path down to:

<pre>
PATH=C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\system32;C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;C:\Go\bin;C:\Users\andrew\go\bin
</pre>

In particular, mingw-w64 is in c:\program files
I think that was the default, but I can't remember for sure.

Cmd finds g++ using this path

<pre>
> g++ --version
g++ (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
</pre>

**Comment by AlexRouSg** [comment]
Duplicate of #41400

**Comment by apmckinlay** [comment]
I'm not sure this is the same as #41400 although it could be related.
My problem just started with 1.15.7.
That issue appears to affect older versions.
I don't have an external CC environment variable
My go env CC is just "gcc", no spaces.

**Comment by AlexRouSg** [comment]
@apmckinlay sorry for missing that it started with `1.15.7`

Then this looks due to the security fix in #43785

**Comment by apmckinlay** [comment]
@AlexRouSg That's what I was assuming

**Comment by AlexRouSg** [comment]
After reading the patches ... it looks like it sets the `CC` env var to the full path which contains spaces and thus triggering #41400
https://github.com/golang/go/commit/e8e7facfaa47bf21007c0a1c679debba52ec3ea0#diff-fec5b487b6c6e4cfdbf1e8af384e463d03693a05feb2f9b9a757feb0ab12e1e4R2028

So it does look like fixing #41400 would fix this too. Tho I'm not too sure what route it would eventually take.

cc @bcmills @rolandshoemaker

**Comment by rsc** [comment]
Apologies. The workaround is to use c:\progra~1 in your path for now.

**Comment by apmckinlay** [comment]
@rsc No worries, thanks.

**Comment by zzwx** [comment]
Imagining a new user downloading fresh go version and bumping into inability to compile anything.

**Comment by dmitshur** [comment]
@rsc This is a release blocker and doesn't have an assignee right now. Are you planning to work on it, or should someone else? Thanks.

**Comment by jayconrod** [comment]
I can take a look at this.

I was able to reproduce it on macOS by the way. It looks like it's an issue with spaces in the `CC` variable passed to `cgo`, not specifically a Windows issue.

This will likely need to be backported, so I'd rather not attempt a complete fix for #41400 yet.

**Comment by bcmills** [comment]
@jayconrod, if the alternative approach in https://github.com/golang/go/issues/41400#issuecomment-764998453 doesn't work out, another interim mitigation on Windows in particular might be to use [`GetShortPathName`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getshortpathnamew) to obtain the space-free version of the path that Russ suggested as a workaround in https://github.com/golang/go/issues/43808#issuecomment-763916597.

**Comment by jayconrod** [comment]
It looks like the alternative approach works out. It just means we revert [CL 284780](https://golang.org/cl/284780). That was part of the security fix, but it was a "belt and suspenders" fix, and we still have the belt: `internal/execabs` prevents cgo from using CC with relative paths in PATH.

**Comment by jayconrod** [comment]
@gopherbot Please backport to 1.14 and 1.15. This was a regression.
