### ISSUE TITLE
Building a totally static go binary.

### ISSUE THREAD

**Issue by hongyi-zhao** [golang/go#43801]
On Ubuntu 20.10, I use the following steps to build the go binary:

```
$ sudo apt-get build-dep -y golang
$ git clone https://github.com/golang/go.git go.git
$ cd go.git/src
$ ./make.bash
$ cd ../
$ ldd bin/go
	linux-vdso.so.1 (0x00007ffef27ee000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f540e41d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f540e233000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f540e475000)
```
It seems that it needs some distribution relevant dependencies for working correctly. Thus, I want to know whether I can build a  totally static go binary so that it can run under other Linux distributions.

Regards,
HY

**Comment by mdlayher** [comment]
Please see https://github.com/golang/go/wiki/Questions. Closing.
