### ISSUE TITLE
confusing error message when combining vendored module dependencies, private GitHub repository, version upgrade, and an expired GitHub Token.

### ISSUE THREAD

**Issue by kalexmills** [golang/go#43807]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.15.2
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kalexmills/.cache/go-build"
GOENV="/home/kalexmills/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/kalexmills/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/mnt/c/Users/Alex/Sanity/workspace/go-refs-test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build363522906=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

1. Use a private GitHub repository as a module dependency.
2. Vendor your dependencies using `go mod vendor`.
3. Allow the GitHub access token to expire (or corrupt it locally to mimic an 'expired' token).
4. Release a new version tag in your private repository
5. Update the version in `go.mod` to use the new version tag.
6. Attempt to build your dependent project (expect complaint about 'unknown revision')
7. Fix the GitHub access token.
8. Attempt to build your dependent project (expect dependency to be downloaded).

### What did you expect to see?

An error explaining that the GitHub token does not work.

### What did you see instead?

```
[10:12] go-refs-test> go build main.go
go: github.com/kalexmills/private@v1.1.0: reading github.com/kalexmills/private/go.mod at revision v1.1.0: unknown revision v1.1.0
```

After glancing through the source, I suspect the issue is around line 298 in the below snippet https://github.com/golang/go/blob/f1980efb92c011eab71aa61b68ccf58d845d1de7/src/cmd/go/internal/modfetch/codehost/git.go#L298-L336 If I'm reading it correctly, `r.refsErr` needs to be checked after line 298. I think instead it's falling through to the else clause at line 335 which is reporting the unknown revision.

I haven't yet attempted a fix, but I am open to doing so.

**Comment by seankhliao** [comment]
closing as dup of #25982 , please reopen if you disagree
