### ISSUE TITLE
cmd/compile: replace ir.Name map with ir.NameSet

### ISSUE THREAD

**Issue by oiooj** [golang/go#43819]
As [CL 282212](https://go-review.googlesource.com/c/go/+/282212/1..9/src/cmd/compile/internal/inline/inl.go) mentioned, we should clean all `map[*ir.Name]bool` with ` ir.NameSet`. 

I'm working on this clean.

/cc @mdempsky

**Comment by mdempsky** [comment]
This is fixed on dev.regabi. Thanks @oiooj!
