### ISSUE TITLE
time/format: Error parsing time format with European offset

### ISSUE THREAD

**Issue by haskovec** [golang/go#43813]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.15.6 darwin/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
When I try to parse a time returned by a workfront instance with a European time offset Go fails to parse it. The time format returned is `2020-08-17T17:00:00:000+0100`

To reproduce I wrote the following test code:
<pre>
func TestWorkfrontDateFormat(t *testing.T) {
	workfrontDate := "2020-08-17T17:00:00:000+0100"  //Set for European timezone

	_, err := time.Parse("2006-01-02T15:04:50:000-0700", workfrontDate)
	if err != nil {
		t.Errorf("Error parsing European Date: %#v", err)
	}
}

</pre>

### What did you expect to see?

I would expect it to correctly parse the time.

### What did you see instead?

It returns an error object:

<pre>
&time.ParseError{Layout:"2006-01-02T15:04:50:000-0700", Value:"2020-08-17T17:00:00:000+0100", LayoutElem:"0:000", ValueElem:":000+0100", Message:""}
</pre>

**Comment by seankhliao** [comment]
closed as dup of #36145 , please comment/reopen if you disagree
