### ISSUE TITLE
cmd/compile: "internal compiler error: curfn mismatch" on darwin-amd64-race builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#43826]
```
#!watchflakes
post <- log ~ `internal compiler error: curfn mismatch`
```

[2021-01-18T17:21:53-5a8fbb0/darwin-amd64-race](https://build.golang.org/log/b6b336e5e22f0528d838f9039ffd37e5464bfd4b)

See previously #37407, #37406, but note that those were believed to have been fixed by upgrading the builders.
(CC @randall77 @josharian @golang/release)

**Comment by mdempsky** [comment]
That seems like memory corruption. Either runtime bugs or faulty memory or something. That sort of failure shouldn't be random.

Another failure on the same machine, which also looks like a pointer is nil when it shouldn't be: https://build.golang.org/log/9a0af1fedad51a17898be428620c03c863e258a0

And another similar failure on the non-race version of the machine (not sure if the same physical hardware or not): https://build.golang.org/log/5e5d23f0d609ad291d7be138ef1ff147a6c613b1

**Comment by mdempsky** [comment]
That last one definitely looks like some sort of memory corruption. The error message is:

```
vet: /var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-10_15/go/src/reflect/type.go:2611:57: tt.Elem().Field(0).hodsTypeOf undefined (type Value has no field or method hodsTypeOf)
```

but that corresponding line of source is:

```
                typ = (*structType)(unsafe.Pointer(tt.Elem().Field(0).UnsafeAddr()))
```

So the string that should be "UnsafeAddr" is actually "hodsTypeOf"? Notably, the same length, but wrong bytes. It looks like maybe the string data for "methods" and "TypeOf" are consecutive in memory, and the pointer for "UnsafeAddr" is off.

**Comment by bcmills** [comment]
Agreed, it looks like memory corruption. My question is, is this memory corruption due to a hardware issue (e.g. overheading RAM), due to a kernel or platform bug, or due to a bug somewhere in the Go toolchain or runtime?
