### ISSUE TITLE
x/pkgsite: mismatch between GetLatestMajorPathForV1Path and getLatestMajorVersion

### ISSUE THREAD

**Issue by julieqiu** [golang/go#43849]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/mediocregopher/radix
 
 
### Screenshot
 

 
![image](https://user-images.githubusercontent.com/5943521/105515552-d3a20480-5ca2-11eb-9787-398c66d48507.png)

 
 
### What did you do?
 

Visited https://pkg.go.dev/github.com/mediocregopher/radix and was redirected to https://pkg.go.dev/github.com/mediocregopher/radix/v4. This should redirect to https://pkg.go.dev/github.com/mediocregopher/radix/v3, since that is the highest tagged version.

This is due to a mismatch in the logic between [GetLatestMajorPathForV1Path](https://github.com/golang/pkgsite/blob/0e6330833e046d05ddb37d1b4de85de979fbefcb/internal/postgres/path.go#L20) and [getLatestMajorVersion](https://github.com/golang/pkgsite/blob/7328fabf02857d4add36cde6133c95893950b7a7/internal/postgres/version.go#L146). GetLatestMajorPathForV1Path looks for the highest major version, numerically. getLatestMajorVersion takes into account whether the module has tagged versions.

**Comment by kirandasika98** [comment]
@julieqiu I would like to pick up this issue

**Comment by julieqiu** [comment]
This has been fixed.
