### ISSUE TITLE
cmd/cgo: "'_check_for_64_bit_pointer_matching_GoInt' declared as an array with a negative size" on darwin/arm64

### ISSUE THREAD

**Issue by Hywan** [golang/go#43842]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16beta1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yup. The beta.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/hwhost/Library/Caches/go-build"
GOENV="/Users/hwhost/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/hwhost/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/hwhost/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16beta1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="[hidden]"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vh/wyys3cl57jz0qp5t79vhrd200000gn/T/go-build952033984=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I tried to compile the following file with `go build main.go`:

```go
package foo

import "C"

func main() { }
```

### What did you expect to see?

A successful built.

### What did you see instead?

```
In file included from _cgo_export.c:4:
cgo-gcc-export-header-prolog:25:55: error: '_check_for_64_bit_pointer_matching_GoInt' declared as an array with a negative size
```

## Extra

It could be related to https://github.com/golang/go/issues/38693.
The `GOARCH` and `GOOS` are OK in this case.

**Comment by Hywan** [comment]
`_check_for_64_bit_pointer_matchin_GoInt` is defined as:

```c
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];
```

Let's evaluate this super quickly in C:

```c
int main() {
  printf(">> %lu\n", sizeof(void*));
  printf(">> %d\n", 64/8);
}
```

Execute it:

```
$ clang a.c -o a && ./a
>> 8
>> 8
```

I don't know how `cgo` calls `clang`, but it seems something is wrong in how it invokes it.

**Comment by bcmills** [comment]
CC @cherrymui

**Comment by bcmills** [comment]
Depending on how you were invoking `go build`, this looks like it may be a duplicate of #43692.

**Comment by cherrymui** [comment]
Weird. What is the output for `go build -x`? That should include how C compiler is invoked to compile C code.

> it may be a duplicate of #43692.

Could be. Does setting `CGO_CFLAGS="-arch arm64" CGO_LDFLAGS="-arch arm64"` help?

It is still weird in that even if it defaults to x86_64, it is still 64-bit and the pointer size should still be 8.

**Comment by bcmills** [comment]
Is it possible that the user's shell is a 32-bit binary, causing `clang` to default to some 32-bit arch?

**Comment by cherrymui** [comment]
I don't think ARM64 Mac supports 32-bit binary.

**Comment by Hywan** [comment]
Running `CGO_CFLAGS="-arch arm64" CGO_LDFLAGS="-arch arm64" go build main.go` solves the problem. That's weird.

`clang` and the shell, everything is 64-bit.

**Comment by Hywan** [comment]
Thanks :-)
