### ISSUE TITLE
fmt: flag _ not exposed to custom Formatters

### ISSUE THREAD

**Issue by josharian** [golang/go#43851]
I attempted to write a custom Formatter that uses the `_` flag.

Result: The custom Formatter doesn't receive the `_` flag, and the format verb is printed (along with Format being called!).

Reproduction below and at https://play.golang.org/p/sPPOdzVnC-W.

In the `Format "%_x":` block in the output, note the `_: false` line as well as the stray "x" output.

```go
package main

import (
	"fmt"
)

var flags = []int{'#', '+', '_', '0', ' '}

type T int

func (t T) Format(f fmt.State, verb rune) {
	for _, flag := range flags {
		fmt.Printf("\t%c: %v\n", flag, f.Flag(flag))
	}
}

func main() {
	var t T
	for _, flag := range flags {
		format := "%" + string(rune(flag)) + "x"
		fmt.Printf("Format %q:\n", format)
		fmt.Printf(format, t)
		fmt.Println()
	}
}
```

cc @robpike @martisch

**Comment by dmitshur** [comment]
CC @robpike, @martisch via [owners](https://dev.golang.org/owners).

**Comment by robpike** [comment]
What is the _ flag?

**Comment by seankhliao** [comment]
@josharian is this misreading the `-` flag (which is valid and `fmt`passes) as `_`?

**Comment by josharian** [comment]
OMG. Yes. Sheesh. Thank you. :)

But now I kinda wish fmt had an _ flag.
