### ISSUE TITLE
bug on all versions

### ISSUE THREAD

**Issue by salimicali** [golang/go#43852]
### What version of Go are you using (`go version`)?
go get command not work in iran
result :net/http: TLS handshake timeout

<pre>
$ go version
go version go1.15.6 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/yula/.cache/go-build"
GOENV="/home/yula/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/yula/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/yula/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/yula/Apps/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/yula/Apps/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build386250011=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.15.6 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.15.6
uname -sr: Linux 5.4.0-64-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.31-0ubuntu9.1) stable release version 2.31.
gdb --version: GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
</pre></details>

**Comment by seankhliao** [comment]
consider setting an alternate proxy, see https://github.com/golang/go/wiki/Modules#are-there-always-on-module-repositories-and-enterprise-proxies

dup #31186
