### ISSUE TITLE
crypto does not recognize the extension "authority key identifier"

### ISSUE THREAD

**Issue by GOODPWDCETCSZ** [golang/go#43868]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13, 1.15
</pre>

### Does this issue reproduce with the latest release?
Yes (1.15)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

Ubuntu, amd64

### What did you do?

1. Install ZCertificate (https://github.com/zmap/zcertificate)
2. ./zcertificate seed-77s38-921c17.pem

### What did you expect to see?
To show users duplicate extensions (authority key identifier) or report duplicate extension error according to RFC 5280.

### What did you see instead?
"extensions":{"key_usage":{"certificate_sign":true,"value":32},"basic_constraints":{"is_ca":false},"subject_key_id":"bc93a7c14d51a1b11e5dc9c191eadb5b53d5bc58"},"unknown_extensions":[{"id":"2.16.840.1.113730.1.13","critical":true,"value":"Fh1oZXJlIGlzIHRoZSBuc0NvbW1lbnQgY29udGVudA=="}]

[seed-77s38-921c17.zip](https://github.com/golang/go/files/5860245/seed-77s38-921c17.zip)

**Comment by seankhliao** [comment]
This appears to be an issue with zcertificate and not Go, both instances of `2.5.29.35` (`authorityKeyIdentifier`) are returned

```go
package main

import (
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"fmt"
	"log"
	"os"
)

func main() {
	b, err := os.ReadFile("x.pem")
	if err != nil {
		log.Fatal(err)
	}
	block, _ := pem.Decode(b)
	c, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		log.Fatal(err)
	}
	for _, e := range c.Extensions {
		fmt.Println(e.Id.String(), base64.StdEncoding.EncodeToString(e.Value))
	}
}
```
output:
```
» go run .
2.16.840.1.113730.1.13
---
2.5.29.35 MBaAFOrTnfL6EhUda5ABHx3bJ3+v0WXX
2.5.29.14 BBS8k6fBTVGhsR5dycGR6ttbU9W8WA==
2.5.29.15 AwICBA==
2.5.29.19 MAA=
2.16.840.1.113730.1.13 Fh1oZXJlIGlzIHRoZSBuc0NvbW1lbnQgY29udGVudA==
2.5.29.35 ME+hSqRIMEYxCzAJBgNVBAYTAlVOMQwwCgYDVQQIDANOWVMxDTALBgNVBAoMBFVOR0ExDTALBgNVBAsMBFVOU0MxCzAJBgNVBAMMAkRUggEB
```

**Comment by GOODPWDCETCSZ** [comment]
Thanks.
