### ISSUE TITLE
cmd/compile: builders are unhappy with dev.typeparams

### ISSUE THREAD

**Issue by mdempsky** [golang/go#43866]
A decent number of non-trybot builders at https://build.golang.org/?repo=&branch=dev.typeparams are failing. I was expecting the dev.regabi->dev.typeparams merge to help with this, and it did a little, but there's still a lot of red. We should probably try to investigate some of this before it becomes too hard to figure out the root cause.

A bunch of random notes:

1. A lot of the longtest builders initially started failing because of #43795. E.g., this failure was because of a faulty test: https://build.golang.org/log/2b42b8d257452fded5ccd804a16b9f087bfca40e. This was fixed on master, and the fix was merged to dev.regabi and then dev.typeparams.

2. On dev.typeparams we did change cmd/dist to run "go test std cmd" with and without `-G=3` (https://go-review.googlesource.com/c/go/+/285052), and this seems to coincide with some of the longtest builders getting stuck. Maybe that CL is interacting poorly with the build coordinator? (/cc @dmitshur) This seems to also coincide with the windows-race and openbsd-386 builders reacting badly.

3. The ppc64le builders have been failing for a while. The power9osu builder started failing at https://go-review.googlesource.com/c/go/+/279920. The buildlet became flaky a little bit after that, and seems to have gotten progressively worse, up to failing consistently recently. I tried reproducing on my personal ppc64le machine but didn't have any problems running all.bash with GOPPC64 set to either power8 or power9.

   I also skimmed the diff between dev.regabi and dev.typeparams, and I didn't see anything obvious that I thought should affect these builders. Regardless, I plan to backport a lot of the non-types2-dependent changes to dev.regabi, which should help narrow down the root cause (and hopefully help reduce conflicts to make future merges easier).

4. There are some windows failures that I think are just due to test/run.go's list of known-failing tests uses UNIX file paths, but test.goFileName uses filepath.Join. So it'll have `\` characters instead of `/` on Windows.

/cc @griesemer @findleyr @danscales

**Comment by mdempsky** [comment]
I've tried running dev.typeparams's cmd/compile w/ -race on ppc64le, and it didn't expose any issues either. Not terribly surprising, since I don't think there's any ppc64le-specific code on dev.typeparams, so any race issues should be caught by the amd64 racecompile bot.

Also, it does look like the x/build coordinator has some logic specific to handling "go_test:", so it does seem plausible the new "go_test_g3:" tests are causing some trouble: https://github.com/golang/build/blob/master/cmd/coordinator/coordinator.go

**Comment by griesemer** [comment]
dev.typeparams was merged into master successfully. I believe this can now be closed. @mdempsky ?

**Comment by findleyr** [comment]
I'm going to close this. I filed #51399 to clean up dev.typeparams.
