### ISSUE TITLE
cmd/go: 'go generate' fails to update PWD variable

### ISSUE THREAD

**Issue by bcmills** [golang/go#43862]
Most subprocess invocations in the `go` command use [`base.AppendPWD`](https://tip.golang.org/cmd/go/internal/base/#AppendPWD) to append an accurate value of `PWD` to the command's environment, which can speed up calls like `os.Getwd` and also help to provide less-confusing output from scripts.

As noted in https://github.com/golang/go/issues/43724#issuecomment-765717357 (CC @dylan-bourque), `go generate` currently fails to do so when invoking the generator command:
https://github.com/golang/go/blob/3a778ff50f7091b8a64875c8ed95bfaacf3d334c/src/cmd/go/internal/generate/generate.go#L451

It should be updated to do so.

(CC @matloob @jayconrod)

**Comment by robpike** [comment]
Oh, the cursed PWD variable. An apparently simple idea with offensively wide-ranging ramifications. An object lesson in  three letters for anyone paying attention.
