### ISSUE TITLE
imports syscall/js: build constraints exclude all Go files in D:\Go\src\syscall\js

### ISSUE THREAD

**Issue by sxy88** [golang/go#43865]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.15.6
</pre>

### Does this issue reproduce with the latest release?

i don't know

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=wasm
set GOBIN=
set GOCACHE=C:\Users\Sxy\AppData\Local\go-build
set GOENV=C:\Users\Sxy\AppData\Roaming\go\env
set GOEXE=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\Study\ProgramData\GoPath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=js
set GOPATH=D:\Study\ProgramData\GoPath
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set GOWASM=
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-fPIC -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Sxy\AppData\Local\Temp\go-build345168030=/tmp/go-build -gno-record-gcc-swi
tches

</pre></details>

### What did you do?

run a program in goland:
package main

import "syscall/js"

func main() {
	alert := js.Global().Get("alert")
	alert.Invoke("Hello World!")
}

### What did you expect to see?
no errors

### What did you see instead?

Run 'go build main.go'
package command-line-arguments
	imports syscall/js: build constraints exclude all Go files in D:\Go\src\syscall\js
Compilation finished with exit code 1

or

go run main.go
exec: "C:\\Users\\Sxy\\AppData\\Local\\Temp\\go-build246431802\\b001\\exe\\main": file does not exist

**Comment by seankhliao** [comment]
`syscall/js` is only valid for the `js` and `wasm` platforms
For questions please refer to https://github.com/golang/go/wiki/Questions
