### ISSUE TITLE
x/mobile: unable to run example/basic on mac osx 10.11.6 El Capitan

### ISSUE THREAD

**Issue by einthusan** [golang/go#43876]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
this is the latest support for this OS version

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/usr/local/gopath/bin"
GOCACHE="/Users/einthusan/Library/Caches/go-build"
GOENV="/Users/einthusan/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="github.com/paperboard"
GONOSUMDB="github.com/paperboard"
GOOS="darwin"
GOPATH="/usr/local/gopath"
GOPRIVATE="github.com/paperboard"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cj/ymv0b8js49l90hc7v5txjqg80000gn/T/go-build212890867=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

go install golang.org/x/mobile/example/basic

### What did you expect to see?
no errors and a compiled program

### What did you see instead?
the program did not compile and the following errors
```
# golang.org/x/mobile/app
darwin_desktop.m:175:30: error: use of undeclared identifier 'NSEventTypeKeyDown'
darwin_desktop.m:216:14: error: use of undeclared identifier 'NSWindowStyleMaskTitled'
darwin_desktop.m:220:22: error: use of undeclared identifier 'NSWindowStyleMaskResizable'
darwin_desktop.m:221:22: error: use of undeclared identifier 'NSWindowStyleMaskMiniaturizable'
darwin_desktop.m:222:22: error: use of undeclared identifier 'NSWindowStyleMaskClosable'
```

**Comment by seankhliao** [comment]
The examples use up to date (non deprecated) apis, use an earlier version of the examples to run on older is versions.

Ex. NSKeyDown is available for <= 10.12 and NSEventTypeKeyDown for >= 10.12

I'm going to close this since I don't think anything can be done

**Comment by einthusan** [comment]
But if we are supposedly going to use this repo to write cross-platform code, shouldn't this detail be hidden inside? Do you expect developers to be aware of these keydown differences, and various others?

**Comment by seankhliao** [comment]
It is hidden as long as you use an up to date OS

10.11 hasn't been supported for 2.5 years (apple security fixes)

**Comment by einthusan** [comment]
> It is hidden as long as you use an up to date OS
> 10.11 hasn't been supported for 2.5 years (apple security fixes)

This is more of an excuse that real support. My computer is working perfectly fine. I can run Go on it! Support should be there, and it is not that hard to support it either. Thanks for your time though.
