### ISSUE TITLE
gollvm: Attribute 'byval' type does not match parameter, in function unicode_1utf8.DecodeLastRune

### ISSUE THREAD

**Issue by advancedwebdeveloper** [golang/go#43870]
Hello.

One of few current bugs:

> cd /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/build_release/tools/gollvm/libgo && /usr/local/bin/cmake -E make_directory ./unicode && /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/build_release/./bin/llvm-goc -c -o /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/build_release/tools/gollvm/libgo/unicode/utf8.o -fgo-pkgpath=unicode/utf8 -I . /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/unicode/utf8/utf8.go
> Attribute 'byval' type does not match parameter!
> %call.1 = call { i64, i64 } @unicode_1utf8.DecodeRune(i8* nest undef, { i8*, i64, i64 }* byval(double) %tmp.20), !dbg !498
> Attribute 'byval' type does not match parameter!
> %call.1 = call { i64, i64 } @unicode_1utf8.DecodeRune(i8* nest undef, { i8*, i64, i64 }* byval(double) %tmp.20), !dbg !374
> in function unicode_1utf8.DecodeLastRune
> LLVM ERROR: Broken function found, compilation aborted!

. Extracted from https://github.com/advancedwebdeveloper/clang_test_cpu_features/commit/c86a560437d3c01b83bb0fa26ae3b5011b011c37/checks/1754290561/logs , which is generated by Clang 11 (a release build).

**Comment by toothrot** [comment]
What ref of gollvm were you testing against?

/cc @thanm

**Comment by thanm** [comment]
Hi @toothrot , I'll take a look at this time permitting -- it's most likely due to a change in LLVM.

**Comment by advancedwebdeveloper** [comment]
From https://github.com/advancedwebdeveloper/clang_test_cpu_features/commit/c86a560437d3c01b83bb0fa26ae3b5011b011c37/checks/1862483964/logs :

> BackendCABIOracleTests.RecursiveCall1Amd64
> lengths differ (302 vs 315) extra expected tokens: float> }* %cast.4, align 8 ret { double, <2 x float> } %ld.5 
> token vector diff at slot 225 (expected 'byval' result 'byval({')

**Comment by advancedwebdeveloper** [comment]
@thanm , why Aarch64 centric tests are executed on AMD64 server?
That's kind of odd.

**Comment by thanm** [comment]
Unit test fix on the way. 

>why Aarch64 centric tests are executed on AMD64 server

I guess I would say "Why not?"  For this unit test we don't need an arm64 processor or execution environment, we only need to verify that the ABI rules are being followed.  Unit tests are also quick to run, so we might as well do all of them.

**Comment by advancedwebdeveloper** [comment]
All builds are valid:

https://github.com/advancedwebdeveloper/clang_test_cpu_features/actions/runs/505920630
. I have removed some configurations.
