### ISSUE TITLE
gollvm: Attribute 'byval' type does not match parameter, in function internal_1cpu.Name

### ISSUE THREAD

**Issue by advancedwebdeveloper** [golang/go#43871]
Hello again.

Another bug, which I was able to track:

> /home/runner/work/clang_test_cpu_features/clang_test_cpu_features/clang_test_cpu_features/build_release/tools/gollvm/libgo/cpugen.go
> Attribute 'byval' type does not match parameter!
>  call void @internal_1cpu.appendBytes({ i8*, i64, i64 }* sret(bfloat) "go_sret" %sret.actual.6, i8* nest undef, { i8*, i64, i64 }* byval(bfloat) %data, { i32*, i64, i64 }* byval(bfloat) %tmp.0), !dbg !465
> Attribute 'byval' type does not match parameter!
>    call void @internal_1cpu.appendBytes({ i8*, i64, i64 }* sret(bfloat) "go_sret" %sret.actual.6, i8* nest undef, { i8*, i64, i64 }* byval(bfloat) %data, { i32*, i64, i64 }* byval(bfloat) %tmp.0), !dbg !465
>  Attribute 'byval' type does not match parameter!
>  call void @internal_1cpu.appendBytes({ i8*, i64, i64 }* sret(bfloat) "go_sret" %sret.actual.8, i8* nest undef, { i8*, i64, i64 }* byval(bfloat) %data, { i32*, i64, i64 }* byval(bfloat) %tmp.1), !dbg !473
>  Attribute 'byval' type does not match parameter!
>  call void @internal_1cpu.appendBytes({ i8*, i64, i64 }* sret(bfloat) "go_sret" %sret.actual.8, i8* nest undef, { i8*, i64, i64 }* byval(bfloat) %data, { i32*, i64, i64 }* byval(bfloat) %tmp.1), !dbg !473
> Attribute 'byval' type does not match parameter!
> call void @internal_1cpu.appendBytes({ i8*, i64, i64 }* sret(bfloat) "go_sret" %sret.actual.10, i8* nest undef, { i8*, i64, i64 }* byval(bfloat) %data, { i32*, i64, i64 }* byval(bfloat) %tmp.2), !dbg !481
> Attribute 'byval' type does not match parameter!
> call void @internal_1cpu.appendBytes({ i8*, i64, i64 }* sret(bfloat) "go_sret" %sret.actual.10, i8* nest undef, { i8*, i64, i64 }* byval(bfloat) %data, { i32*, i64, i64 }* byval(bfloat) %tmp.2), !dbg !481
> Attribute 'byval' type does not match parameter!
> call void @internal_1cpu.appendBytes({ i8*, i64, i64 }* sret(bfloat) "go_sret" %sret.actual.6, i8* nest undef, { i8*, i64, i64 }* byval(bfloat) %data, { i32*, i64, i64 }* byval(bfloat) %tmp.0), !dbg !386
> Attribute 'byval' type does not match parameter!
> call void @internal_1cpu.appendBytes({ i8*, i64, i64 }* sret(bfloat) "go_sret" %sret.actual.6, i8* nest undef, { i8*, i64, i64 }* byval(bfloat) %data, { i32*, i64, i64 }* byval(bfloat) %tmp.0), !dbg !386
> Attribute 'byval' type does not match parameter!
>  call void @internal_1cpu.appendBytes({ i8*, i64, i64 }* sret(bfloat) "go_sret" %sret.actual.8, i8* nest undef, { i8*, i64, i64 }* byval(bfloat) %data, { i32*, i64, i64 }* byval(bfloat) %tmp.1), !dbg !394
>  Attribute 'byval' type does not match parameter!
> call void @internal_1cpu.appendBytes({ i8*, i64, i64 }* sret(bfloat) "go_sret" %sret.actual.8, i8* nest undef, { i8*, i64, i64 }* byval(bfloat) %data, { i32*, i64, i64 }* byval(bfloat) %tmp.1), !dbg !394
> Attribute 'byval' type does not match parameter!
> call void @internal_1cpu.appendBytes({ i8*, i64, i64 }* sret(bfloat) "go_sret" %sret.actual.10, i8* nest undef, { i8*, i64, i64 }* byval(bfloat) %data, { i32*, i64, i64 }* byval(bfloat) %tmp.2), !dbg !402
>  Attribute 'byval' type does not match parameter!
>  call void @internal_1cpu.appendBytes({ i8*, i64, i64 }* sret(bfloat) "go_sret" %sret.actual.10, i8* nest undef, { i8*, i64, i64 }* byval(bfloat) %data, { i32*, i64, i64 }* byval(bfloat) %tmp.2), !dbg !402
> in function internal_1cpu.Name

. More details [here](https://github.com/advancedwebdeveloper/clang_test_cpu_features/commit/c86a560437d3c01b83bb0fa26ae3b5011b011c37/checks/1754290561/logs).

**Comment by thanm** [comment]
Dup of #43870

**Comment by advancedwebdeveloper** [comment]
Glad that you added this to your backlog.

**Comment by advancedwebdeveloper** [comment]
Ping

**Comment by toothrot** [comment]
Closing as a dup of #43870. Feel free to discuss further there. Please let me know if I am mistaken.
