### ISSUE TITLE
x/pkgsite: .JumpDialog's position is fixed but .ShortcutsDialog is not

### ISSUE THREAD

**Issue by Omkar76** [golang/go#43877]
My previous PR golang/pkgsite#21 (not released) solved problem of `.JumpDialog` not staying on viewport but I didn't know there is one more dialogue `.ShortcutsDialog`  which pops up on pressing <kbd>?</kbd>. So basically, `.JumpDialog` has `position:fixed` and `.ShortcutsDialog` has `position:absolute` which makes it look inconsistent.

**Comment by Omkar76** [comment]
Both dialog boxes use `.Dialog` class. I'll just add the `position:fixed` to `.Dialog` and remove it from '.JumpDialog`. The style will get applied to both dialogs. I'll send a PR soon.

**Comment by Omkar76** [comment]
@julieqiu, You added _NeedsFix_ label (which I guess, means there is currently no fix provided)  but I have already submitted a fix in PR golang/pkgsite#22 which corresponds to gerrit CL [golang.org/cl/286092](https://go-review.googlesource.com/c/pkgsite/+/286092#message-708e4040c94a9a4dc512b9dc51cd01a93d88024f)

Please have a look at it. Thank you.

**Comment by julieqiu** [comment]
Per https://github.com/golang/go/wiki/Gardening, For Go, we use the presence of certain labels (`Needs*` or `WaitingForInfo`) to indicate that an issue has been triaged. `NeedsFix` indicates that the path to resolution is known, but a CL has not been submitted yet to close this issue.
