### ISSUE TITLE
Windows cannot rename opened file

### ISSUE THREAD

**Issue by carbotaniuman** [golang/go#43874]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\quydx\AppData\Local\go-build
set GOENV=C:\Users\quydx\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\quydx\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\quydx\AppData\Local\Temp\go-build609388426=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you expect to see?
I opened a file with `os.OpenFile`. I delete it and it works like on Unix.

### What did you see instead?

I opened a file with `os.OpenFile`. I tried to delete it and I got a sharing violation.

**Comment by carbotaniuman** [comment]
No code because the code is peopeierttary and cannot be shared.

**Comment by seankhliao** [comment]
dup #32088
