### ISSUE TITLE
tour.golang.org returns server error for some languages

### ISSUE THREAD

**Issue by posener** [golang/go#43881]
In tour.golang.org second page (https://tour.golang.org/welcome/2) the user can choose a language.
Some of the languages work, but some result in "500 Server Error" page.

Specifically, the languages and corresponding domains that do not work:

* Arabic (https://go-tour-ar.appspot.com/)
* Traditional Chinese (https://go-tour-zh-tw.appspot.com/)
* German (https://go-tour-de.appspot.com/)
* Hebrew (https://go-tour-he.appspot.com/)
* Italian (https://go-tour-ita.appspot.com/)
* Romanian (https://go-tour-ro.appspot.com/)
* Russian (https://go-tour-ru-ru.appspot.com/)
* Spanish (https://gotour-es.appspot.com/)
* Turkish (https://go-tour-turkish.appspot.com/)
* Ukrainian (https://go-tour-ua.appspot.com/)

**Comment by ALTree** [comment]
Thanks for reporting the issue. This is already tracked at https://github.com/golang/tour/issues/1039, so I'm closing here as a dup.
