### ISSUE TITLE
go build Ubuntu x64 "Illegal instruction (core dumped)"

### ISSUE THREAD

**Issue by depers81** [golang/go#43893]
<pre>
$ go version go1.15.7 linux/amd64
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/depers/.cache/go-build"
GOENV="/home/depers/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/depers/work/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/depers/work"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build038733487=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

When compiled in Go1.15.7 for different platforms, this file does not work on other Linux.
When compiled on Server1, the executable on Server2 and Server3 does not work. When compiled on Server3, the file did not work on Server1 and Server 2 
Displayed an "Illegal instruction (core dumped)" error
Used command GOOS = linux GOARCH = amd64 go build -o hello_linux64 
But when compiling the file for Windows, it works on windows systems.

~/work/src/hello# GOOS=windows GOARCH=386 go build -o hello_win86.exe ~/work/src/hello# GOOS=windows GOARCH=amd64 go build -o hello_win64.exe ~/work/src/hello# GOOS=linux GOARCH=386 go build -o hello_linux86 
~/work/src/hello# GOOS=linux GOARCH=amd64 go build -o hello_linux64

Server1:
Architecture: x86_64 
Model name: Intel(R) Pentium(R) CPU G620 @ 2.60GHz 
OS: Ubuntu 18.04.5 LTS x64
Server2:
Architecture: x86_64 
Model name: Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz 
OS: Ubuntu 16.04.2 LTS x64
Server3:
Architecture: x86_64 
Model name: Intel(R) Xeon(R) CPU E5420 @ 2.50GHz 
OS: Ubuntu 18.04.5 LTS x64

**Comment by seankhliao** [comment]
please fill out the issue template, include the full error output and "this file"
