### ISSUE TITLE
cmd/compile: const eval should be exact independent of (mathematically equivalent) expression form (-G=3 option only)

### ISSUE THREAD

**Issue by griesemer** [golang/go#43908]
Factored out from #43891 :
```Go
package main

import "fmt"

const ulp1 = imag(1i + 2i / 3 - 5i / 3)
const ulp2 = imag(1i + complex(0, 2) / 3 - 5i / 3)

func main() {
	fmt.Printf("%g %g\n", ulp1, ulp2)
}
```
should print the same value (0) for both `ulp1` and `ulp2`, but currently reports:
```
0 1.4916681462400413e-154
```
This happens because `go/constant.ToFloat` doesn't convert to a rational number when it could, and then we lose mathematical precision.

Note this only happens with when using the -G=3 option (new type checker).

**Comment by ianlancetaylor** [comment]
FYI, gccgo prints the same value twice, but it doesn't print `0`.  It prints

```
1.727233711018889e-77 1.727233711018889e-77
```

**Comment by griesemer** [comment]
The test case is such that it should pass as long as both values are identical (which they are expected to be).

The compiler now uses exact computations for "small-ish" rational numbers; and only switches to floats when using rational numbers would be too expensive.

Presumably the difference between (the old) values 1.4916681462400413e-154 and 1.727233711018889e-77 stems from `cmd/compile` using 512 bits of mantissa, while `gccgo` only uses 256 bits (to be confirmed).

**Comment by ianlancetaylor** [comment]
It is certainly true that gccgo currently uses a floating point precision of 256 bits.

**Comment by griesemer** [comment]
This has been fixed in the `dev.typeparams` branch and already works correctly in the `master` and `dev.regabi` branch. Closing.
