### ISSUE TITLE
Golang Mod Install Error

### ISSUE THREAD

**Issue by MrJohnDo** [golang/go#43918]
go: gorm.io/driver/postgres@v1.0.7 requires
	gorm.io/gorm@v1.20.12: reading gorm.io/gorm/go.mod at revision v1.20.12: unknown revision v1.20.12

**Comment by seankhliao** [comment]
For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by MrJohnDo** [comment]
A brew update fixed the issue.
