### ISSUE TITLE
runtime: unable to use SIGSTOP to background

### ISSUE THREAD

**Issue by gopherbot** [golang/go#4391]
<pre>If I try to SIGSTOP the current process, that seems to only block one thread, while
other threads continue. I also tried signaling the session leader, same results.

This reproduces the problem:

$ cat sigstop.go
package main

import (
	&quot;syscall&quot;
	&quot;fmt&quot;
)

func main() {
	fmt.Println(&quot;one&quot;)
	pid := syscall.Getpid()
	err := syscall.Kill(pid, syscall.SIGSTOP)
	if err != nil {
		panic(&quot;bleh&quot;)
	}
	fmt.Println(&quot;two&quot;)
}

$ go build sigstop.go
$ ./sigstop
one
two

What is the expected output?

Compare to

$ cat sigstop.c
#include &lt;stdio.h&gt;
#include &lt;sys/types.h&gt;
#include &lt;unistd.h&gt;
#include &lt;signal.h&gt;

int main(void) {
  pid_t pid;

  printf(&quot;one\n&quot;);
  pid = getpid();
  kill(pid, SIGSTOP);
  printf(&quot;two\n&quot;);
}

$ gcc sigstop.c
$ ./a.out 
one

[1]+  Stopped                 ./a.out
$ fg
./a.out
two
$ 

Which compiler are you using (5g, 6g, 8g, gccgo)?

6g via &quot;go build&quot;

Which operating system are you using?

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.1 LTS
Release:	12.04
Codename:	precise

Which version are you using?  (run 'go version')

$ go version
go version go1</pre>

**Comment by ianlancetaylor** [comment]
This works as expected in Go 1.5 and on tip.
