### ISSUE TITLE
x/tools/gopls: intellisense for CGO function or data type

### ISSUE THREAD

**Issue by linlinlinlin** [golang/go#43919]
### What version of Go are you using (`go version`)?
1.14.6

### Does this issue reproduce with the latest release?
Write some CGO in Golang files.

![圖片](https://user-images.githubusercontent.com/8558312/105821286-a2ed0280-5ff5-11eb-904f-4c0300b8e3b3.png)

### What did you expect to see?
Should not show warning `not declared by package C` for C type or C exported function.

Not sure is it belong to gopls issue or others.

**Comment by heschik** [comment]
Please follow the VS Code [troubleshooting guide](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md), and then upload a log of the problem, following the "Collect gopls information" section.

**Comment by linlinlinlin** [comment]
Is it possible to collect only this project or files logs?
The gopls(server) log also collect all personal or internal project source code.

**Comment by heschik** [comment]
```
[Info  - 11:10:34 AM] 2021/01/27 11:10:34 go env for /Users/ggg_user/mxio
(root /Users/ggg_user/mxio)
(go version go version go1.15.7 darwin/amd64)
(valid build configuration = false)
(build flags: [-tags=bruno])
GONOSUMDB=
GOMOD=
GOSUMDB=sum.golang.org
GOFLAGS=
GOMODCACHE=/Users/ggg_user/go/pkg/mod
GONOPROXY=
GOROOT=/usr/local/Cellar/go/1.15.7/libexec
GO111MODULE=
GOCACHE=/Users/ggg_user/Library/Caches/go-build
GOINSECURE=
GOPRIVATE=
GOPROXY=https://proxy.golang.org,direct
GOPATH=/Users/ggg_user/go
```

The folder containing your cgo code is missing a go.mod and so can't be loaded. Please add a valid go.mod and try again?

**Comment by linlinlinlin** [comment]
I didn't have go.mod in this folder. Just `main.go  xxx.h dummy.cpp`. Build file by `go build -o xxx`. Library is put in `/usr/local/lib`
The dummy.cpp file is for this [issue](https://github.com/golang/go/issues/18460)

**Comment by stamblerre** [comment]
@linlinlinlin: `gopls` likely won't work well when you are outside of a module and outside of GOPATH. It is definitely recommended to use modules if possible.

**Comment by stamblerre** [comment]
Closing, as there hasn't been any activity on this for quite some time.

**Comment by shuxiao9058** [comment]
the same issue ...

**Comment by scaszoo** [comment]
Same for me . . .
Within a project with several packages in sub folders. The CGO Code is in a sub folder

**Comment by zandercodes** [comment]
Same :C

**Comment by hyangah** [comment]
Hi @shuxiao9058 @scaszoo @zandercodes @onewesong 

Do you mind creating new issues so we can understand how to improve?
Here is the list of the information that may help faster triage https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#file-an-issue
 
From reading [the comment](https://github.com/golang/go/issues/43919#issuecomment-797054285), the cause of this issue was partly due to the absence of `go.mod` file, but your cases may be different. Thanks for sharing your experience!

**Comment by xfzen** [comment]
the same issue...
