### ISSUE TITLE
crypto/x509: investigate signature verification added to CreateCertificate in Go 1.16

### ISSUE THREAD

**Issue by dmitshur** [golang/go#43928]
We're seeing a test failure in an google-internal target, and we've identified that it may be related to the change in  https://golang.org/cl/259697. This is the tracking issue for doing the investigation to determine if the problem is in CL 259697 or not.

Resolving this issue is a blocker for Go 1.16 via #43253.

CC @rolandshoemaker, @FiloSottile, @golang/release.

**Comment by rolandshoemaker** [comment]
Confirmed this isn't an issue in CL 259697.
