### ISSUE TITLE
crypto/rsa: RSA-PSS PKCS1v15 should support SHA3 hashes (and others)

### ISSUE THREAD

**Issue by shaunco** [golang/go#43923]
<pre>
$ go version
go version go1.15.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
```go
rsa.VerifyPKCS1v15(myPublicKey, crypto.SHA3_224, hashed, signature)
```

### What did you expect to see?
A properly verified hash. `pkcs1v15HashInfo()` needs to calculate the ASN1 DER prefix for algorithms that aren't in the lookup table.

### What did you see instead?
`crypto/rsa: unsupported hash function`

### Additional notes
The [current code](https://github.com/golang/go/blob/master/src/crypto/rsa/pkcs1v15.go#L207) has a table of precomputed ASN1 DER prefixes for 8 algorithms. All other algorithms get `crypto/rsa: unsupported hash function`, even though they are valid.

**Comment by FiloSottile** [comment]
It's a bit unclear to me why anyone would want to use legacy PKCS#1 v1.5 with SHA-3, but if there is a need I'd accept a PR to add the relevant ASN.1 prefixes.

**Comment by shaunco** [comment]
I too wish the originator of the signatures I'm dealing with had used PSS. I'll try to find some time to submit a PR so I can ditch the current workaround I put in place.

**Comment by w3bb** [comment]
Trying to reimplement a program, for some reason they use an SHA-3 hash in this way and it's broken for me.

@shaunco What's your workaround?

**Comment by tristov-aurora** [comment]
Unfortunately, it's still used, even in new hardware like [ZynqMP FPGA](https://docs.xilinx.com/r/en-US/ug1283-bootgen-user-guide/Verifying) -- RSA4096-SHA3-384 with pkcs#1v1.5 is the only [scheme](https://github.com/Xilinx/bootgen/blob/master/authentication-zynqmp.cpp#L269) it supports; I suspect there's other hardware out there with similar settings. In those cases no pkcs#1v.15 with SHA3 support also means it's hard (not impossible) to use Vault transit keys for signing.

**Comment by tristov-aurora** [comment]
> It's a bit unclear to me why anyone would want to use legacy PKCS#1 v1.5 with SHA-3, but if there is a need I'd accept a PR to add the relevant ASN.1 prefixes.

Unfortunately, it's still used, even in new hardware like [ZynqMP FPGA](https://docs.xilinx.com/r/en-US/ug1283-bootgen-user-guide/Verifying) -- RSA4096-SHA3-384 with pkcs#1v1.5 is the only [scheme](https://github.com/Xilinx/bootgen/blob/master/authentication-zynqmp.cpp#L269) it supports; I suspect there's other hardware out there with similar settings. In those cases no pkcs#1v.15 with SHA3 support also means it's hard (not impossible) to use Vault transit keys for signing.
