### ISSUE TITLE
runtime: recover does not correctly recover from panic

### ISSUE THREAD

**Issue by mdempsky** [golang/go#43921]
This program should exit normally, but it currently exits with a panic: https://play.golang.org/p/XnJ41HvD9Gw

It exits normally when compiled with gccgo or with `-gcflags=-N`. Notably, it does not crash with the alternative code I suggested at https://go-review.googlesource.com/c/go/+/286712/1/src/runtime/panic.go#1038. (Discovered this by accident while trying to test gccgo instead and happened to still have that test code patched into my local tree.)

/cc @danscales @randall77

**Comment by danscales** [comment]
Thanks for the test case @mdempsky .  I fixed this bug and added your test case to https://golang.org/cl/286712  .  I didn't fix the other bug that you filed -- that looks more complex to fix.  But I think we can just go with cl/286712 for the immediate Go 1.16 release (if reviewers are happy).
