### ISSUE TITLE
build: spurious missing $GOPATH error

### ISSUE THREAD

**Issue by rsc** [golang/go#43938]
make.bash (and friends) should not need GOPATH to be set.
Right now it is being set implicitly, which is good enough.
But if we make it impossible to set implicitly, make.bash fails.
It should not.

```
$ HOME='' GOPATH='' ./make.bash
missing $GOPATH
$ 
```

/cc @jayconrod @matloob @bcmills

**Comment by rsc** [comment]
Shorter repro case:

	HOME='' GOPATH='' go env

**Comment by rsc** [comment]
Another fun fact: run.bat (only!) clears GOPATH, and defaultGOPATH returns an empty string if the default GOPATH comes out the same as GOROOT.

So while I have no problems at all using GOROOT=$HOME/go and GOPATH=$HOME on my Unix systems, if I do the equivalent on Unix, I can't all.bat or run.bat because the cleared GOPATH drops to the default, which comes out equal to my GOROOT, so it gets cleared too, and then we hit the missing \$GOPATH fatal error.

The fatal error in cmd/go should still be fixed, but now that there's a non-empty default GOPATH, the clearing in run.bat is misleading at best and can be removed too. I'll do that.

**Comment by dmitshur** [comment]
[CL 288818](https://golang.org/cl/288818) has made an improvement in this area, but the bug in the original report still reproduces.

This issue doesn't seem critical and doesn't have an assignee, so moving to Backlog. If someone still has time to fix this or thinks it's important for 1.17, please update accordingly.
