### ISSUE TITLE
Can't use line breaks sometimes in the code

### ISSUE THREAD

**Issue by gnevesdev** [golang/go#43932]
Hi! I'm currently using Go 15, but I think it happens in other versions too... 

I don't know if it is relevant, but I'm using Linux. The same error already happened to me in Windows, but didn't test it in MacOS. 

The thing is that sometimes in the code I can't just break lines and separate some things. Like in this example:
```
callToFunction(arg1, arg2, arg3)
```

Sometimes there's a lot of arguments and I want to separate them like this:
```
callToFunction(
     arg1,
     arg2,
     arg3
)
```

I do that in C and it works fine... Though, in Go I need to do it like this:
```
callToFunction(
     arg1,
     arg2,
     arg3)
```

It's not a big problem, but it would be nice to be able to do it. 

And what makes this even stranger is that I can actually break lines sometimes and it's completely ok. Like in this example:
```
import(
     "fmt"
     "os"
)
```

**Comment by seankhliao** [comment]
add a trailing comma

For questions please refer to https://github.com/golang/go/wiki/Questions
