### ISSUE TITLE
x/pkgsite: symbol search popup fails to load

### ISSUE THREAD

**Issue by myitcv** [golang/go#43949]
### What is the URL of the page with the issue?

https://pkg.go.dev/cuelang.org/go@v0.3.0-beta.3.0.20210124142225-9c5489fc66ed/cue

### What is your user agent?

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.59 Safari/537.36
</pre>

### Screenshot

n/a

### What did you do?

Tried to launch the symbol search via `f`

### What did you expect to see?

A popup with a type-ahead box as usual, much like on https://pkg.go.dev/github.com/govim/govim/cmd/govim/config:

![Screen Shot 2021-01-27 at 09 02 35](https://user-images.githubusercontent.com/3374574/105968044-7c26de80-607e-11eb-9d54-e3202cd2330c.png)

### What did you see instead?

Nothing. Instead I see the following console errors:

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-inline' 'strict-dynamic' https: http: 'sha256-CgM7SjnSbDyuIteS+D1CQuSnzyKwL0qtXLU6ZW2hB+g=' 'sha256-dwce5DnVX7uk6fdvvNxQyLTH/cJrTMDK6zzrdKwdwcg=' 'sha256-Q0lBU5W61U2Bjmznl8iFgTCLw4PWCtS1taSwwNz3iGk=' 'sha256-T7xOt6cgLji3rhOWyKK7t5XKv8+LASQwOnHiHHy8Kwk=' 'sha256-1J6DWwTWs/QDZ2+ORDuUQCibmFnXXaNXYOtc0Jk6VU4=' 'sha256-y5EX2GR3tCwSK0/kmqZnsWVeBROA8tA75L+I+woljOE=' 'sha256-hsHIJwO1h0Vzwa75j0l07kUfQ7MEZGI/HlSPB/8leZ0=' 'sha256-CFun5NgnYeEpye8qcbQPq5Ycwavi4IXuZiIzSMNqRUw=' 'sha256-IHdniK/yZ8URNA2OYbc4R7BssOAe3/dFrSQW7PxEEfM=' 'sha256-hb8VdkRSeBmkNlbshYmBnkYWC/BYHCPiz5s7liRcZNM='". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

cue:3476 Uncaught ReferenceError: loadScript is not defined
    at cue:3476
(anonymous) @ cue:3476
cue:3482 Uncaught ReferenceError: loadScript is not defined
    at cue:3482
(anonymous) @ cue:3482
cue:3485 Uncaught ReferenceError: loadScript is not defined
    at cue:3485
(anonymous) @ cue:3485
cue:3488 Uncaught ReferenceError: loadScript is not defined
    at cue:3488
(anonymous) @ cue:3488
cue:3499 Uncaught ReferenceError: loadScript is not defined
    at cue:3499
```

**Comment by jamalc** [comment]
I cannot reproduce this but have a theory that it might've been a caching issue. Is this still happening @myitcv?

**Comment by myitcv** [comment]
Given the above link, no I can't reproduce this now.

Is the caching issue related to the console errors I included?

**Comment by jamalc** [comment]
It might be. Our Content Security Policy (CSP) uses content hashes of the JavaScript we serve to enhance the security of pkg.go.dev. The `loadScript` function is used to load the code that would have opened symbol search but it was not defined because its content hash did not match any of the content hashes in our CSP header.

Just to rule this out, is it possible that you have any browser extensions installed that might've altered JavaScript on the page?

**Comment by myitcv** [comment]
> Just to rule this out, is it possible that you have any browser extensions installed that might've altered JavaScript on the page?

No. Other pages on pkg.go.dev were working and continue to work.

**Comment by jamalc** [comment]
I haven't been able to reproduce this or seen it happen again so let's close this as a stale issue.
