### ISSUE TITLE
go get not downloading to src folder

### ISSUE THREAD

**Issue by adi1382** [golang/go#43945]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16beta1 darwin/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/aditya/Library/Caches/go-build"
GOENV="/Users/aditya/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/aditya/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/aditya/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.15.7/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.15.7/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16beta1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dc/mpdmt39s2j94rz4w2b9h91_c0000gn/T/go-build1453910353=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
command on terminal "go get go.uber.org/atomic@v1"
or another "go get" command

### What did you expect to see?
source files getting downloaded to "$GOPATH/src/"

### What did you see instead?
source files were not downloaded to "$GOPATH/src"
but files were downloaded to "$GOPATH/pkg/mod"

**Comment by mdempsky** [comment]
I think this is working as intended. See https://tip.golang.org/doc/go1.16#go-command.

**Comment by adi1382** [comment]
Thanks, It helped.
