### ISSUE TITLE
x/pkgsite: remove github.com/bizflycloud/node_exporter

### ISSUE THREAD

**Issue by BoTranVan** [golang/go#43943]
### What is the URL of the page with the issue?
 I can't get real version of my module when run my code with go get, ...
 
 
### What is your user agent?
 I can't get because my request was blocked

 
### What did you expect to see?
 
I need delete my module in pkg.dev.go that are:

1. github.com/bizflycloud/bizfly-agent
2. github.com/bizflycloud/node_exporter

many thanks

**Comment by jba** [comment]
Done.
