### ISSUE TITLE
doc/go1.16: document new go/build/constraint package

### ISSUE THREAD

**Issue by dmitshur** [golang/go#43957]
The new `go/build/constraint` package in Go 1.16 should be documented in the final Go 1.16 release notes as part of #40700.

CC @rsc.

**Comment by ianlancetaylor** [comment]
Why do I not see anything from the go/build/constraint package in api/go1.16.txt?

**Comment by ianlancetaylor** [comment]
Hmmm, they are printed by the API check but did not wind up in go1.16.txt or next.txt.

**Comment by dmitshur** [comment]
@ianlancetaylor Please see https://github.com/golang/go/issues/43407#issuecomment-768535817 and https://golang.org/cl/287412.

**Comment by ianlancetaylor** [comment]
Thanks, looks like go/build/constraint landed January 8, so we need some mechanism for checking for new additions late in the release cycle.  I, at least, never noticed it.

**Comment by dmitshur** [comment]
> Thanks, looks like go/build/constraint landed January 8, so we need some mechanism for checking for new additions late in the release cycle. I, at least, never noticed it.

I agree. I've CC'ed you on issue #43956 which is about resolving that and contains some more details.
