### ISSUE TITLE
x/pkgsite: removing some packages

### ISSUE THREAD

**Issue by jun-sheaf** [golang/go#43959]
We forked a few packages a while back and have since deleted them, but they are still listed here:

 - https://pkg.go.dev/github.com/mu-io/jwt-go
 - https://pkg.go.dev/github.com/mu-io/jwt-go/cmd/jwt

Could we have these packages removed?

**Comment by jba** [comment]
If we remove github.com/mu-io/jwt-go, we'll remove everything underneath it as well. Is that OK?

**Comment by jun-sheaf** [comment]
That's all right. Thank you.

**Comment by jba** [comment]
Done.
