### ISSUE TITLE
go/types, types2: type checker accepts import of package called "init"

### ISSUE THREAD

**Issue by griesemer** [golang/go#43962]
Given two packages (for convenience represented via single files both stored in the same directory):

`a.go`: `package init`
`b.go`: `package b; import "./a"`

the compiler reports "cannot import package as init - init must be a func", but the `go/types` and `types2` accept this (though they correctly don't accept a local rename to `init`).

cc: @findleyr

**Comment by findleyr** [comment]
The above CL was ported to dev.regabi in https://golang.org/cl/290570 (forgot to tag this issue). I think we can close this once dev.regabi becomes master.

**Comment by griesemer** [comment]
With the merge of `dev.typeparams` into `master`, this is not fixed.
