### ISSUE TITLE
net/rpc: server.go io.EOF error condition need errors.Is function 

### ISSUE THREAD

**Issue by lsixi** [golang/go#43964]
### go version

<pre>
v1.15.7

</pre>

### error

`readRequestHeader` method return a error like this:
```
if err == io.EOF || err == io.ErrUnexpectedEOF {
    err = fmt.Errorf("rpc: header unexpected eof %w", err)
    return
}
```

but `ServeCodec` method just use condition `err != io.EOF` 

### expect
false == errors.Is(err, io.EOF)

**Comment by ianlancetaylor** [comment]
I don't understand.  I don't see any code like

    err = fmt.Errorf("rpc: header unexpected eof %w", err)

in the net/rpc package.  Can you point to the exact line at https://golang.org/src/net/rpc/server.go ?  Thanks.
