### ISSUE TITLE
encoding/json: disable HTML escaping and omit final newline

### ISSUE THREAD

**Issue by 89z** [golang/go#43961]
I am encoding some JSON. I need to disable HTML escaping, and I need no trailing
newline. It seems no easy way to do this.

If I try `json#Marshal`, it does HTML escaping with no option to change. If I
try `json#Encoder.Encode`, it adds newline with no option to change. I came up
with this as a workaround:

~~~go
package main

import (
   "bytes"
   "encoding/json"
   "fmt"
   "log"
)

func compact(dst *bytes.Buffer, v interface{}) error {
   var src bytes.Buffer
   enc := json.NewEncoder(&src)
   enc.SetEscapeHTML(false)
   err := enc.Encode(v)
   if err != nil {
      return err
   }
   return json.Compact(dst, src.Bytes())
}

func main() {
   var dst bytes.Buffer
   e := compact(&dst, []string{"May", "June & July"})
   if e != nil {
      log.Fatal(e)
   }
   fmt.Printf("%q", dst.String())
}
~~~

but its pretty awkward. Also if you wanted to indent, it is difficult, since you
are now calling `json#Compact`, using `json#Encoder.SetIndent` would be pointless, you
would have to call `json#Indent` after everything is done.

https://golang.org/pkg/encoding/json

**Comment by seankhliao** [comment]
This is possible with the current api (as you've demonstrated), see
https://golang.org/doc/faq#x_in_std

**Comment by 89z** [comment]
@seankhliao my workaround is really inefficient. The `Compact` function is overkill to essentially remove a trailing newline, when it would be better if option to just not add the newline in the first place.

**Comment by 89z** [comment]
@seankhliao my workaround is really inefficient. The `Compact` function is overkill to essentially remove a trailing newline, when it would be better if option to just not add the newline in the first place.

Also that link doesnt really relate to this issue. Im not asking to add a new package.

**Comment by seankhliao** [comment]
You can just slice off the last element of the byte slice.

**Comment by 89z** [comment]
@seankhliao yeah, but again, it would be better if it wasnt added in the first place, even as an option.

**Comment by 89z** [comment]
Here is another approach, based on your suggestion:

~~~go
func marshal(v interface{}) ([]byte, error) {
   var dst bytes.Buffer
   enc := json.NewEncoder(&dst)
   enc.SetEscapeHTML(false)
   err := enc.Encode(v)
   if err != nil {
      return nil, err
   }
   return dst.Bytes()[:dst.Len() - 1], nil
}
~~~

Although since `bytes` is already being used, `TrimSpace` could be used instead:

https://github.com/golang/go/blob/00f2ff5c942e8f3e68cd10b5909278cda15c6bb5/src/encoding/json/stream_test.go#L150-L156

**Comment by mvdan** [comment]
Encoder enforcing a newline is unfortunate, but I agree with @seankhliao that it seems like a very minor inconvenience that doesn't warrant new API.

We are aware that Marshal and Encode are weird APIs, but they are not APIs we can break. And extending Encoder with more options isn't going to be particularly better in the long run :)

**Comment by mvdan** [comment]
cc @dsnet
