### ISSUE TITLE
x/tools/gopls: memory usage

### ISSUE THREAD

**Issue by juancer** [golang/go#43968]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.7 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\user\AppData\Local\go-build
set GOENV=C:\Users\user\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\user\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\user\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\user~1\AppData\Local\Temp\go-build341909526=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
just save a change on my project

### What did you expect to see?

Better improvement of the memory

### What did you see instead?
here you have the img:
[https://ibb.co/94kgRXy](https://ibb.co/94kgRXy)

**Comment by seankhliao** [comment]
please follow the steps in https://github.com/golang/tools/blob/gopls/v0.6.4/gopls/doc/troubleshooting.md#debug-memory-usage to include the relevant information when filing issues about gopls

**Comment by juancer** [comment]
Here you have it:
[https://we.tl/t-tViJpcpaTL](https://we.tl/t-tViJpcpaTL)

**Comment by seankhliao** [comment]
can you upload it as an attachment here instead?

**Comment by juancer** [comment]
which text do you want from the file?

**Comment by juancer** [comment]
[gopls.30384-18GiB-withnames.zip](https://github.com/golang/go/files/5886822/gopls.30384-18GiB-withnames.zip)

**Comment by heschik** [comment]
You seem to have a number of particularly expensive packages, notably golang.org/x/text, open in your workspace. Have you opened your entire GOPATH as your workspace folder? That will definitely lead to very high memory usage. We'd like to be more efficient, but for now you will be much better off opening just the project you're working on.

**Comment by juancer** [comment]
Hi @heschik, I just have one project and all the packages that I have installed is what i'm using.
Can I just disable the execution?

**Comment by heschik** [comment]
Please make sure that the folder you've opened as your workspace folder in VSCode contains only code you've written. If you still see high memory usage, please upload a gopls log following https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information?
