### ISSUE TITLE
embed: outdated sentences in documentation

### ISSUE THREAD

**Issue by gazerro** [golang/go#43978]
The documentation of the new `embed` package says:

> The variable must be of type string, []byte, or FS exactly. Named types or type aliases
> derived from those types are not allowed.

but the change https://golang.org/cl/282715 removed these limitations.

> Similarly, it [the //go:embed directive] can be used with both global and function-local variables,
> depending on what is more convenient in context.

but the change https://golang.org/cl/282714 removed support for vars embedded inside functions.

**Comment by ianlancetaylor** [comment]
Thanks for pointing that out.
