### ISSUE TITLE
cmd/go: golang.org/dl/?mode=json&include=all drops unstable versions

### ISSUE THREAD

**Issue by myitcv** [golang/go#43975]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +cd176b3615 Wed Jan 27 12:18:00 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/myitcv/gostuff/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel +cd176b3615 Wed Jan 27 12:18:00 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/tmp.MBLQ66sMZY/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3624228031=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

`go1.16rc1` has just been released. But this appears to have caused `go1.16beta1` to be dropped from: https://golang.org/dl/?mode=json&include=all. 

This is turn has caused any GitHub actions builds that have `go1.16beta1` in their build matrices, kicked off since the release of `rc1`, to fail.

### What did you expect to see?

Is there any harm in retaining all published versions in the JSON index?

### What did you see instead?

Per above.

cc @toothrot

**Comment by WillAbides** [comment]
I hope to see this merged soon. In the mean time I made an unfiltered version available at https://github.com/WillAbides/goreleases

**Comment by mvdan** [comment]
It appears this is a duplicate of https://github.com/golang/go/issues/37581, as @seankhliao found out. I assume we should close this newer one, as the old one was already confirmed as a bug :)

**Comment by myitcv** [comment]
Agreed.
