### ISSUE TITLE
cmd/compile: inline of a predicate uses temporary bool

### ISSUE THREAD

**Issue by gopherbot** [golang/go#4397]
by **jeff.allen**:

<pre>What steps will reproduce the problem?
If possible, include a link to a program on play.golang.org.
1. here is a program that makes a call to a predicate:

package main

func eq(a,b string) bool {
	return len(a) == len(b)
}

func main() {
	a := &quot;&quot;
	b := &quot;&quot;
	if eq(a,b) {
		println(&quot;ok&quot;)
	}
}

Inlining the predicate results in assembly with duplicate initialization of temporaries
on the stack and jumps forward and back. 

Is this really correct behavior? It seems suspiciously ugly.

What is the expected output?

This is the assembly from manually inlining the code (i.e. replacing a call to eq(a,b)
with the expression len(a)==len(b))

--- prog list &quot;main&quot; ---
0010 (streq.go:7) TEXT    main+0(SB),$16-0
0011 (streq.go:8) LEAQ    go.string.&quot;&quot;+0(SB),BX
0012 (streq.go:8) MOVQ    (BX),BP
0013 (streq.go:8) MOVQ    8(BX),CX
0014 (streq.go:9) MOVQ    (BX),BP
0015 (streq.go:9) MOVQ    8(BX),AX
0016 (streq.go:10) CMPQ    CX,AX
0017 (streq.go:10) JNE     ,26
0018 (streq.go:11) LEAQ    go.string.&quot;ok&quot;+0(SB),BX
0019 (streq.go:11) LEAQ    (SP),BP
0020 (streq.go:11) MOVQ    BP,DI
0021 (streq.go:11) MOVQ    BX,SI
0022 (streq.go:11) MOVSQ   ,
0023 (streq.go:11) MOVSQ   ,
0024 (streq.go:11) CALL    ,runtime.printstring+0(SB)
0025 (streq.go:11) CALL    ,runtime.printnl+0(SB)
0026 (streq.go:13) RET     ,

What do you see instead?

This is the assembly from 6g with inlining. Note the useless MOVB $0,.anon2, which after
two jumps (!), is overwritten by MOV AX,.anon2, then compared to $0.

--- prog list &quot;main&quot; ---
0010 (streq.go:7) TEXT    main+0(SB),$24-0
0011 (streq.go:8) LEAQ    go.string.&quot;&quot;+0(SB),BX
0012 (streq.go:8) MOVQ    (BX),SI
0013 (streq.go:8) MOVQ    8(BX),DX
0014 (streq.go:9) MOVQ    (BX),CX
0015 (streq.go:9) MOVQ    8(BX),BP
0016 (streq.go:10) MOVB    $0,.anon2+-1(SP)
0017 (streq.go:10) JMP     ,20
0018 (streq.go:10) MOVQ    $1,AX
0019 (streq.go:10) JMP     ,23
0020 (streq.go:10) CMPQ    DX,BP
0021 (streq.go:10) JEQ     ,18
0022 (streq.go:10) MOVQ    $0,AX
0023 (streq.go:10) MOVB    AX,.anon2+-1(SP)
0024 (streq.go:10) MOVBQZX .anon2+-1(SP),BX
0025 (streq.go:10) CMPB    BX,$0
0026 (streq.go:10) JEQ     ,35
0027 (streq.go:11) LEAQ    go.string.&quot;ok&quot;+0(SB),BX
0028 (streq.go:11) LEAQ    (SP),BP
0029 (streq.go:11) MOVQ    BP,DI
0030 (streq.go:11) MOVQ    BX,SI
0031 (streq.go:11) MOVSQ   ,
0032 (streq.go:11) MOVSQ   ,
0033 (streq.go:11) CALL    ,runtime.printstring+0(SB)
0034 (streq.go:11) CALL    ,runtime.printnl+0(SB)
0035 (streq.go:13) RET     ,

Which compiler are you using (5g, 6g, 8g, gccgo)?

6g

Which operating system are you using?

Linux

Which version are you using?  (run 'go version')

14893:591fc8a0131a</pre>

**Comment by alexey-s-sidorov** [comment]
I think this is all right. 
Tested on dev.ssa.
Fragment of objdumped binary:

0000000000401000 <main.main>:
 401000: mov %fs:0xfffffffffffffff8,%rcx
 401009: cmp 0x10(%rcx),%rsp
 40100d: jbe 401040 <main.main+0x40>
 40100f: sub $0x10,%rsp
 401013: callq 4202d0 <runtime.printlock>
 401018: lea 0x692b7(%rip),%rax # 46a2d6 <go.string.*+0xb6>
 40101f: mov %rax,(%rsp)
 401023: movq $0x2,0x8(%rsp)
 40102c: callq 420b90 <runtime.printstring>
 401031: callq 420560 <runtime.printnl>
 401036: callq 420350 <runtime.printunlock>
 40103b: add $0x10,%rsp
 40103f: retq 
 401040: callq 443a70 <runtime.morestack_noctxt>
 401045: jmp 401000 <main.main>
 401047: int3 
 401048: int3 
 401049: int3 
 40104a: int3 
 40104b: int3 
 40104c: int3 
 40104d: int3 
 40104e: int3 
 40104f: int3 

looks fixed.
