### ISSUE TITLE
x/website: add opensearch.xml

### ISSUE THREAD

**Issue by ORANGE-XFM** [golang/go#43982]
### What did you do?
using Firefox, select the "add godoc" as a search engine

### What did you expect to see?
golang search engine added to Firefox

### What did you see instead?
https://golang.org/opensearch.xml not found

copy/pasting this url in the adrowser gives an error page: 

    lstat $GOROOT/opensearch.xml: no such file or directory

**Comment by seankhliao** [comment]
Is it useful for golang.org to do this or is this better suited for pkg.go.dev (which includes the docs for stdlib)?

**Comment by seankhliao** [comment]
I just saw there's an opensearch file https://go.googlesource.com/website/+/refs/heads/master/content/static/opensearch.xml and it's linked via `<link>` tags but not served

**Comment by rsc** [comment]
Search box removed (#44357).
