### ISSUE TITLE
embed: go:embed produces error when "go.mod" has go version < 1.16

### ISSUE THREAD

**Issue by lestrrat** [golang/go#43980]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16rc1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

with the rc release? yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go version go1.16rc1 darwin/arm64
lestrrat@finch jwk % go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/lestrrat/Library/Caches/go-build"
GOENV="/Users/lestrrat/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/lestrrat/dev/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/lestrrat/dev"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16rc1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vb/gf1mcqdd2s509731hrnnvkjm0000gn/T/go-build3140323037=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Using [github.com/lestrrat-go/jwx](https://github.com/lestrrat-go/jwx/tree/develop/v1.1.0)@09b6dea (note that it's at a tracking branch)

```
lestrrat@finch jwx % cd jwk
lestrrat@finch jwk % go test               
```

### What did you expect to see?

```
lestrrat@finch jwx % cd jwk
lestrrat@finch jwk % go test   
PASS
ok  	github.com/lestrrat-go/jwx/jwk	5.437s
lestrrat@finch jwk % 
```

### What did you see instead?

```
lestrrat@finch jwx % cd jwk
lestrrat@finch jwk % go test               
# github.com/lestrrat-go/jwx/jwk_test [github.com/lestrrat-go/jwx/jwk.test]
./fs_test.go:13:3: go:embed requires go1.16 or later (-lang was set to go1.13; check go.mod)
FAIL	github.com/lestrrat-go/jwx/jwk [build failed]
lestrrat@finch jwk % 
```

### Discussion

My go.mod contains the following

```
lestrrat@finch jwk % cat ../go.mod
module github.com/lestrrat-go/jwx

go 1.13

require (
	github.com/goccy/go-json v0.3.4
	github.com/lestrrat-go/backoff/v2 v2.0.7
	github.com/lestrrat-go/codegen v1.0.0
	github.com/lestrrat-go/httpcc v1.0.0
	github.com/lestrrat-go/iter v1.0.0
	github.com/lestrrat-go/option v1.0.0
	github.com/lestrrat-go/pdebug/v3 v3.0.1
	github.com/pkg/errors v0.9.1
	github.com/stretchr/testify v1.6.1
	golang.org/dl v0.0.0-20210128152142-7744cb1878f1 // indirect
	golang.org/x/crypto v0.0.0-20201217014255-9d1352758620
	golang.org/x/mod v0.4.1 // indirect
	golang.org/x/tools v0.0.0-20210114065538-d78b04bdf963
)
```

If I change the line `go 1.13` to `go 1.16`, then it works on go1.16rc1

```
lestrrat@finch jwk % go test
# github.com/lestrrat-go/jwx/jwk_test [github.com/lestrrat-go/jwx/jwk.test]
./fs_test.go:13:3: go:embed requires go1.16 or later (-lang was set to go1.13; check go.mod)
FAIL	github.com/lestrrat-go/jwx/jwk [build failed]
lestrrat@finch jwk % go mod edit -go 1.16
lestrrat@finch jwk % go test             
PASS
ok  	github.com/lestrrat-go/jwx/jwk	5.648s
lestrrat@finch jwk % 
```

go1.16beta1 worked just fine.

```
lestrrat@finch jwk % go install golang.org/dl/go1.16beta1
lestrrat@finch jwk % go1.16beta1 download
go1.16beta1: already downloaded in /Users/lestrrat/sdk/go1.16beta1
lestrrat@finch jwk % go1.16beta1 test .
ok  	github.com/lestrrat-go/jwx/jwk	6.066s
lestrrat@finch jwk % 
```

Shouldn't features like this just depend on the runtime version, and not contents of go.mod?

**Comment by ianlancetaylor** [comment]
This is intentional, because a `//go:embed` comment will only work correctly with Go 1.16 or later.  A `//go:embed` comment requires importing the "embed" package, which is only available in Go 1.16.  So compiling a package with an earlier language version will fail.

**Comment by lestrrat** [comment]
Even with "// +build go1.16" protecting it? -- just making sure, because while I understand go:embed not working with go < 1.16, I would think that if the source code was not eligible for compilation via build tags, it should be ignored.

And if so, I would appreciate a doc explaining that go will not consider build tags in that case. My skimming through the release notes or the embed docs didn't produce such explanation. I can certainly provide a patch if need be.

**Comment by go101** [comment]
By my understanding,
* "// +build go1.16" specify the exact Go Toolchain version needed to compile a source file.
* "go 1.N" directive in a "go.mod" file specifies the features the containing module could use. So it doesn't
   * specify the minimum Go toolchain version to compile the module.
   * cover other modules in a program. https://play.golang.org/p/YlMYLWsP_0S

**Comment by lestrrat** [comment]
I have learned that `go mod tidy` on 1.15 which uses io/fs, regardless of build tags, will fail. Fair enough! Closing.

**Comment by mvdan** [comment]
> This is intentional, because a `//go:embed` comment will only work correctly with Go 1.16 or later. A `//go:embed` comment requires importing the "embed" package, which is only available in Go 1.16. So compiling a package with an earlier language version will fail.

@ianlancetaylor while I get the current check against `-lang`, I'm not sure I understand why it was done this way. If a module declares `go 1.16` in its go.mod, and then *only* imports the "embed" package in a Go file guarded by `// +build go1.16`, why should that fail?

**Comment by ianlancetaylor** [comment]
@mvdan Fair point.  I'll reopen.

**Comment by mvdan** [comment]
I should have clarified. I meant that the go.mod declares an older go language version, like `go 1.15`.

**Comment by ianlancetaylor** [comment]
Thanks, understood.

**Comment by zikaeroh** [comment]
> I have learned that `go mod tidy` on 1.15 which uses io/fs, regardless of build tags, will fail. Fair enough! Closing.

For reference, that's #40067, and it even affects users of modules that try and use new packages. No module can successfully guard its use of a new package with a build tag and have it not still break downstream users with older Go versions.

**Comment by amnonbc** [comment]
Having spent little time playing around with `//go:embed` and encountering the error myself,
I would say that error message is simple, clear, and reasonable.

If you want to use a language feature introduced in Go 1.16, you will need tools >= 1.16 
and version 1.16 or greater specified in your go.mod.
I may be missing something, but I can't think of any scenario where someone would want to add 
embedding while keeping the Go version specified as 1.15 or less.

**Comment by lestrrat** [comment]
The confusion is in the fact that we (well, at least I) have used build tags to switch between certain features that were newly introduced. For example, I have the following successfully compiling in go1.16rc1

```go
// +build go1.15

package ecutil

import (
  "math/big"
)

func bigIntFillBytes(v *big.Int, buf []byte) []byte {
  v.FillBytes(buf)
  return buf
}
```

```go
// +build !go1.15

package ecutil

import (
  "math/big"
)

func bigIntFillBytes(v *big.Int, buf []byte) []byte {
  data := v.Bytes()
  if len(data) > len(buf) {
    panic("ecutil: invalid call to bigIntFillBytes (len(data) > len(buf))")
  }

  copy(buf[len(buf)-len(data):], data)
  return buf
}
```

```
// go.mod
module ...
go 1.13 // FillBytes doesn't exist in 1.13, let alone 1.14
```

In this scenario, I was able to provide support for go 1.14 that doesn't have `(math/big).FillBytes()` while utilizing the new feature that only appeared in go 1.15

At first glance I fail to see the difference between the above and below

```go
// +build go1.16
import "embed"
```

```go
// +build !go1.16
// (code without embed)
```

```
// go.mod file
module ...
go 1.15 // kaput
```

`(math/big).Int.FillBytes` doesn't exist in go 1.14, why should it compile, when `import "embed"` doesn't?
I still think this is inconsistent, but  I closed this issue because I realized that this was not something new in go1.16. 

Hope that clears up my reasoning on this issue, at least.

**Comment by go101** [comment]
I guess the difference between the two is: generally new added APIs are not features. I do admit sometimes this is a little confusing.

I guess there are many feature switches in the compile code to control on/off of some admitted features.

**Comment by lestrrat** [comment]
@go101 I can appreciate the distinction, but I would argue that to the layman the question is just "does this code run on go 1.xx?". In that sense, differentiating between API changes or language features or toolchain changes don't really mean anything to me. As a library writer, I tried to give maximum flexibility to my users by adding a feature to pass in a `(io/fs).FS` to specify where to read files from, guarded by `// +build go1.16`. But that doesn't compile while I keep `go 1.15` in go.mod,  I'm just not going to provide this functionality :/ oh well.

To the maintainers: while I maintain that the current state is inconsistent and confusing, I can appreciate the history, the decisions that went behind, etc, so I'm not demanding immediate change or anything. Again, I think it's confusing, so I would hope that relevant parties see that there  is some room to either clarify the documentation or think this "feature" through a bit more now or in the future.

**Comment by amnonbc** [comment]
As a developer I often rely on the compiler to tell me when I have broken the code.
When I change the signature of a function for instance, the compiler will tell me if I have 
neglected to fix any call sites. 

The fact that it will fail on errors on files guarded by build tags
is a good thing. I develop on an intel machine. If my change breaks the build on s390 machines,
the compiler will tell me. If it didn't I might end up shipping code which failed to compile
on my first  s390 user. 

Of course people will tell me I should make sure that my CI system builds and test on every possible
permutation of supported architectures, OSes, compiler versions etc.  And they may be right.
But it is far better that compiler tells me about these problems straight away.

If this issue was "fixed" by allowing the code above to compile without error, it would make 
development and testing far harder. Please don't do it.

To @lestrrat, my suggestion would be: if you really have to support Go versions > 1.16, then don't 
use embed. In general I would aggressively kill off support for old Go versions, and only use language features
and APIs available on the oldest Go version I do support.

**Comment by go101** [comment]
It would be great if there is an official document to list the features each version supports (and to explain features and functionalities are different).

**Comment by amnonbc** [comment]
> It would be great if there is an official document to list the features each version supports (and to explain features and functionalities are different).

https://tip.golang.org/doc/go1.16 explains which new features were added to go1.16 which are not in go1.15.
Once 1.16 is released, anything before 1.15 becomes unsupported.

If we try to "help" our users by maintaining a table mapping features to versions,
this will in effect be supporting unsupported versions of Go and telling people that it is OK to use them.
This effort will be far better spent encouraging the community to upgrade to the current tools.

**Comment by go101** [comment]
@amnonbc 
Go 1.16 release notes might explains what features were added togo1.16, but it doesn't differentiate what are features and what are not.

@lestrrat
I some misunderstood your above comments. It looks gc1.16 views the embedding functionality (the `//go:embed` directive more specifically) as features, why is not a good idea by my opinion. I think it is just a functionality, not a feature.

> I tried to give maximum flexibility to my users by adding a feature to pass in a `(io/fs).FS` to specify where to read files from, guarded by // +build go1.16. But that doesn't compile while I keep go 1.15 in go.mod,

It looks this is not true. gc1.16 doesn't view `(io/fs).FS` as a feature.

**Comment by go101** [comment]
On the other hand, it is really worth considering how to handle the case if a new Go version both introduces and removes features.

**Comment by amnonbc** [comment]
The point I was trying to make earlier is that we are doing our users no favours if we try to "help" them continue to use
old versions of the tools.

The Go 1.0 promise guarantees the features don't get removed. But they will get added. And the best answer is 
to upgrade to the current version of the compiler.

**Comment by go101** [comment]
There might be features to be removed later, such as the `string(neither_rune_nor_byte_integer)` mentioned in https://github.com/golang/proposal/blob/master/design/28221-go2-transitions.md

**Comment by campoy** [comment]
I would like to point out that I ended up facing the same issue and created a gist reproducing it.

Then I realized this issue existed, but just in case the gist might be useful here it goes:

**Comment by zikaeroh** [comment]
@campoy That's #40067 and it's existed for a while (first seen when `hash/maphash` was added, see https://github.com/golang/go/issues/43980#issuecomment-770069014); I think the original issue is mainly about the fact that the Go compiler errors on `//go:embed` when the lang version is too low in go.mod, even when the code would be guarded by build tags (which IMO is the right way to guard the use, had it not been for #40067).

I'll also point out that the `go.mod` protection that was added really only makes sense for developers using `//go:embed`, but doesn't protect users in older compilers from potentially breaking their code, since modules with lower `lang` versions are allowed to require ones with newer `lang` versions (and `embed.String` and `embed.Bytes` were not added to force a compiler error via missing package), so I'm a bit dubious if this check will really end up having the intended effect to notify users that their code may silently break.

**Comment by rsc** [comment]
The expectation is that you don't use embed until you are ready to bump your users forward.
Build tags are not sufficient, precisely because of tools that need to analyze everything, such as `go mod tidy`.
The same thing happens (or will happen) with any language change gated by the go.mod version.

**Comment by vearutop** [comment]
Introducing `embed` dependency in an existing library (module) seems to effectively mean issuing a major version. Because isolating `embed` in a new package guarded with build tags is not possible due to this issue. And bumping required minimal Go version is a breaking change.

Am I missing a way to introduce `embed` dependency in a backwards compatible way?

**Comment by amnonbc** [comment]
I would not consider requiring the latest tools to build the code to be a breaking API change.

If the API stays the same, then the calling code does not ned to change, so the major version should not be incremented.

New code using new features will generally fail to build using old tools. 
The answer is for people to upgrade their tools to the current version.
They will anyway soon have no choice as 1.15 will be unsupported with a year.

So I would not try to protect new features with build tags. That way lies madness.

**Comment by vearutop** [comment]
Funny enough, I can "workaround" the issue by removing `go 1.11` statement from library's `go.mod`. :)

**Comment by amnonbc** [comment]
> Funny enough, I can "workaround" the issue by removing `go 1.11` statement from library's `go.mod`. :)

Yes having no `go VERSION` statement is logically equivalent to having a `go LATEST` statement
where LATEST is the actual version of the compiler used to compile the code.

**Comment by rogpeppe** [comment]
For the record, you can work around this issue by declaring `go 1.16` in your `go.mod` file and using build tags to guard the use of `go:embed`. For example:

```
// +build go1.16

package m

import (
	_ "embed"
	"fmt"
)

//go:embed hello.txt
var s string
```

**Comment by amnonbc** [comment]
> For the record, you can work around this issue by declaring `go 1.16` in your `go.mod` file and using build tags to guard the use of `go:embed`. For example:
> 
> ```
> // +build go1.16
> 
> package m
> 
> import (
> 	_ "embed"
> 	"fmt"
> )
> 
> //go:embed hello.txt
> var s string
> ```

Why do you need the build tag?

**Comment by rogpeppe** [comment]
> Why do you need the build tag?

Because the `embed` functionality and package is only available under 1.16 and later. You might want to add functionality that's available under later Go versions without breaking existing clients that are using earlier versions. The build tag allows you to do that.

**Comment by philippgille** [comment]
@rogpeppe Was that changed in a recent 1.15.x version? Because in the other comments in this thread it's mentioned that build tags _don't_ help in this particular case, which is one issue that the OP also mentions.

- OP mentioning it: https://github.com/golang/go/issues/43980#issuecomment-769611841
- Francesc posted a Gist for reproduction, declaring `go 1.16` in the `go.mod` file: https://github.com/golang/go/issues/43980#issuecomment-775640734
- Russ confirming that build tags don't work here: https://github.com/golang/go/issues/43980#issuecomment-776921265

Using the code from Francesc's Gist I can reproduce the issue with Go 1.15.7, but not anymore with Go 1.15.11.

**Comment by rogpeppe** [comment]
I believe that the build tag solution now works correctly with 1.15.11 - `go mod tidy` is now resilient to stdlib imports which don't exist.
