### ISSUE TITLE
net/http: test failed on freebsd-12.2-STABLE

### ISSUE THREAD

**Issue by bakul** [golang/go#43984]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16rc1 freebsd/amd64
</pre>

### Does this issue reproduce with the latest release?
No idea.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/home0/bakul/.cache/go-build"
GOENV="/usr/home0/bakul/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOINSECURE=""
GOMODCACHE="/usr/home0/bakul/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="freebsd"
GOPATH="/usr/home0/bakul/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
GOVCS=""
GOVERSION="go1.16rc1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/tmp/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3525808295=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
$ git clone https://go.googlesource.com/dl
$ cd dl/go1.16rc1
$ go run main.go download
$ sudo mv ~/sdk/go1.16rc1 /usr/local/go
$ cd /usr/local/go/src
$ ./all.bash
</pre>

### What did you expect to see?

all tests to pass

### What did you see instead?
<pre>
ok      net     160.991s
</pre>
The above test should take may be 2 seconds

<pre>
2021/01/29 00:20:35 httptest.Server blocked in Close after 5 seconds, waiting for connections:
  *net.TCPConn 0xc00071e168 127.0.0.1:46910 in state active
--- FAIL: TestTransportCloseResponseBody (79.37s)
    transport_test.go:2669: too long waiting for write error
2021/01/29 00:21:45 httptest.Server blocked in Close after 5 seconds, waiting for connections:
  *net.TCPConn 0xc0002f4020 127.0.0.1:48478 in state active
2021/01/29 00:21:45 httptest.Server blocked in Close after 5 seconds, waiting for connections:
  *net.TCPConn 0xc00085e048 127.0.0.1:48501 in state active
2021/01/29 00:21:45 httptest.Server blocked in Close after 5 seconds, waiting for connections:
  *net.TCPConn 0xc0003a00d0 127.0.0.1:48504 in state active
2021/01/29 00:21:45 httptest.Server blocked in Close after 5 seconds, waiting for connections:
  *net.TCPConn 0xc000410038 127.0.0.1:48506 in state active
  *net.TCPConn 0xc000466038 127.0.0.1:48528 in state active
FAIL
FAIL    net/http        201.785s
</pre>

And..
<pre>
ok      os/exec 484.477s
</pre>
This too should take a couple seconds or so.

<pre>
ok      cmd/vet 26.172s
FAIL
</pre>
No further tests were run after this

**Comment by bcmills** [comment]
See also #38370, #37510.

**Comment by problame** [comment]
@seankhliao does this only happen on FreeBSD 12.2 and not prior FreeBSD versions? If so, maybe #43873 is related as well.

**Comment by seankhliao** [comment]
No idea, I don't run freebsd

**Comment by problame** [comment]
@seankhliao sorry, that was meant to be an @bakul

**Comment by bakul** [comment]
No ideas as I don't have any machine running any older versions of FreeBSD.

**Comment by bakul** [comment]
This problem seems to have disappeared with go1.16 and FreeBSD-13.0-* -- closing this for now at least.
