### ISSUE TITLE
reflect: Zero() changes behavior in Go1.16rc1

### ISSUE THREAD

**Issue by koron** [golang/go#43986]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16rc1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

no. it reprocude with latest release candidate

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\koron\AppData\Local\go-build
set GOENV=C:\Users\koron\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\koron\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\koron\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Local\Go\current
set GOSUMDB=sum.golang.org
set GOTMPDIR=C:\Users\koron\go\tmp
set GOTOOLDIR=C:\Local\Go\current\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16rc1
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\koron\go\tmp\go-build183394138=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Run this program with Go 1.16rc1 and 1.15.7

```go
package main

import "reflect"

func main() {
	s := ""
	go116 := reflect.DeepEqual(reflect.Zero(reflect.TypeOf(s)), reflect.ValueOf(s))
	if go116 {
		println("I am Go 1.16 gopher!")
	} else {
		println("I am Go 1.15 or below gopher!")
	}
}
```

You can get it from https://play.golang.org/p/0tzp7aZhnQ8

### What did you expect to see?

`reflect.DeepEqual(reflect.Zero(reflect.TypeOf(s)), reflect.ValueOf(s))` returns `false` for both Go 1.16rc1 and Go 1.15.7

### What did you see instead?

Go 1.15.7 returns `false`, but Go 1.16rc1 returns `true`

**Comment by koron** [comment]
possible related change: https://github.com/golang/go/commit/8925290cf701fc8f7ec95e4df3d6a8d423b26780

**Comment by ALTree** [comment]
cc @randall77

**Comment by koron** [comment]
I'm thinkking it is bad idea comparing two `reflect.Value` by `reflect.DeepEqual`.
It was came from https://github.com/go-openapi/validate/blob/bfaa1f86114fc35873e768bea7490439cbc5ee1c/type.go#L140

**Comment by seankhliao** [comment]
given that this is in the docs:

> To compare two Values, compare the results of the Interface method. Using == on two Values does not compare the underlying values they represent.

I'm thinking this is not a supported operation

**Comment by go101** [comment]
As others mentioned, do
```
    reflect.DeepEqual(reflect.Zero(reflect.TypeOf(s)).Interface(), reflect.ValueOf(s).Interface())
```
instead.

`reflect.Value` is a struct with some unexported fields. The result of comparing its values depends on the implementations.

**Comment by randall77** [comment]
I concur, this does not look like a bug. `reflect.DeepEqual` used on `reflect.Value`s directly almost certainly isn't what you want.
I understand the mistake, though. At first glance it looks like it should work.  Maybe a vet check would be worthwhile here?

Anyway, closing. Please reopen if you think this analysis is wrong.

**Comment by ianlancetaylor** [comment]
See https://github.com/go-openapi/validate/issues/137.

**Comment by koron** [comment]
Thank you all. I'm satisfied with the conclusion. :+1:
