### ISSUE TITLE
x/pkgsite: anchor link heading obscured by top banner in Safari

### ISSUE THREAD

**Issue by myitcv** [golang/go#43999]
### What is the URL of the page with the issue?

https://pkg.go.dev/crypto@go1.15.6#PublicKey

### What is your user agent?

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15</pre>

### Screenshot

![Screen Shot 2021-01-29 at 20 11 32](https://user-images.githubusercontent.com/3374574/106322747-36c90380-626e-11eb-9245-d27c3f74f2c1.png)

### What did you do?

Visited the above link using Safari

### What did you expect to see?

The heading in the anchor link, per Chrome:

![Screen Shot 2021-01-29 at 20 12 32](https://user-images.githubusercontent.com/3374574/106322872-6aa42900-626e-11eb-977c-24600eb1adba.png)

### What did you see instead?

The heading obscured by the top banner:

![Screen Shot 2021-01-29 at 20 11 32](https://user-images.githubusercontent.com/3374574/106322975-8f989c00-626e-11eb-8277-e73e4e623cac.png)

cc @mpvl

**Comment by jamalc** [comment]
This is a known issue with WebKit based browsers. The WebKit team has [released a fix](https://bugs.webkit.org/show_bug.cgi?id=218076) and it is available in the WebKit Nightly Build. I'd prefer to wait for the next Safari release over making a Safari specific fix for this feature. We can leave this open for tracking purposes.

**Comment by jamalc** [comment]
This is fixed in the latest version of Safari.
