### ISSUE TITLE
x/tools/gopls: specify Options.LangVersion when invoking gofumpt

### ISSUE THREAD

**Issue by mvdan** [golang/go#43998]
gofumpt's API has an option to specify the Go language version to target: https://pkg.go.dev/mvdan.cc/gofumpt/format#Options

Unfortunately, this seems to not be wired into gopls: https://github.com/golang/tools/blob/e9a2c0706a5b9cc8ee5965d5a50c996ffb255a7b/gopls/internal/hooks/hooks.go#L26

This results in gofumpt having to fall back to assuming the code has to comply with Go 1.0 as a language, not enabling rules which affect newer language features such as octal numbers.

This should be an easy fix, I think. When run from the command line, `gofumpt` uses the version specified in `go.mod`, so gopls could do the same.

cc @stamblerre @ianthehat

**Comment by twmb** [comment]
If possible, this would be a good opportunity for a general mechanism to wire passing flags through gopls to formatters (so, for example with gofumpt, `-extra`).

**Comment by findleyr** [comment]
This was done in #51327, so closing this as a dupe.

**Comment by mvdan** [comment]
Huh, apologies for filing that twice.
