### ISSUE TITLE
fyne.io on Raspberry Pi 4 doesn't work

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [golang/go#43991]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16rc1 linux/arm

</pre>

### Does this issue reproduce with the latest release?

I doesn't work in 1.15.6 either. That's why I wanted to try it with the pre-release version

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

go env
GO111MODULE=""
GOARCH="arm"
GOBIN=""
GOCACHE="/home/pi/.cache/go-build"
GOENV="/home/pi/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/pi/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GOVCS=""
GOVERSION="go1.16rc1"
GCCGO="gccgo"
GOARM="6"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build758478153=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

go get fyne.io/fyne/v2/cmd/fyne_demo/
/home/pi/go/bin/fyne_demo

### What did you expect to see?

A UI window

### What did you see instead?

/home/pi/go/bin/fyne_demo
2021/01/29 16:02:29 Fyne error:  window creation error
2021/01/29 16:02:29   Cause: APIUnavailable: GLX: OpenGL ES requested but GLX_EXT_create_context_es2_profile is unavailable
2021/01/29 16:02:29   At: /home/pi/go/src/fyne.io/fyne/internal/driver/glfw/window.go:1220

**Comment by seankhliao** [comment]
This is a problem with fyne, not Go

**Comment by PolyglotOpenstreetmap** [comment]
OK, the problem was that fyne was trying to open that Window through my SSH tunnel.

I solved it by putting 

os.Setenv("DISPLAY", ":0.0")

before showing the window and now it shows on the screen attached to the Pi.

Just wanted to let you know, in case anyone else trips over this.

Jo
