### ISSUE TITLE
"non-declaration statement outside function body" while running go get or go run on ANY package

### ISSUE THREAD

**Issue by AskAlice** [golang/go#44001]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.15.6 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

I will try updating but I don't want to mess with my environment if someone knows how this issue can be identified, because it worked until it didn't.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env 
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\alice\AppData\Local\go-build
set GOENV=C:\Users\alice\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\alice\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\alice\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\alice\AppData\Local\Temp\go-build682913518=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
Well i first noticed it while trying to run an application locally. I tediously looked over my source to see if there was any sort of syntax error, but there wasnt. I later reverted my code to a known working branch and it continued to happen. Then I ran the following commands, and the same issue appeared...
<pre>
go get -u golang.org/x/lint/golint
go get -u honnef.co/go/tools/cmd/staticcheck
go get -u github.com/kisielk/errcheck
</pre>

### What did you expect to see?

it get these packages successfully.

### What did you see instead?

<pre>
go: found golang.org/x/lint/golint in golang.org/x/lint v0.0.0-20201208152925-83fdc39ff7b5
go: golang.org/x/tools upgrade => v0.1.0
# runtime
c:\go\src\runtime\panic.go:1189:1: syntax error: non-declaration statement outside function body
go: downloading honnef.co/go/tools v0.1.1
go: found honnef.co/go/tools/cmd/staticcheck in honnef.co/go/tools v0.1.1
go: honnef.co/go/tools upgrade => v0.1.1
go: golang.org/x/tools upgrade => v0.1.0
go: golang.org/x/xerrors upgrade => v0.0.0-20200804184101-5ec99f83aff1
go: golang.org/x/mod upgrade => v0.4.1
go: golang.org/x/sys upgrade => v0.0.0-20210124154548-22da62e12c0c
go: downloading golang.org/x/sys v0.0.0-20210124154548-22da62e12c0c
go: downloading golang.org/x/mod v0.4.1
# runtime
c:\go\src\runtime\panic.go:1189:1: syntax error: non-declaration statement outside function body
go: github.com/kisielk/errcheck upgrade => v1.5.0
go: downloading github.com/kisielk/errcheck v1.5.0
go: golang.org/x/tools upgrade => v0.1.0
go: golang.org/x/sys upgrade => v0.0.0-20210124154548-22da62e12c0c
go: golang.org/x/xerrors upgrade => v0.0.0-20200804184101-5ec99f83aff1
go: golang.org/x/mod upgrade => v0.4.1
# runtime
c:\go\src\runtime\panic.go:1189:1: syntax error: non-declaration statement outside function body
</pre>

For testing purposes, I tried running the hello world example on the go docs.
https://golang.org/doc/tutorial/getting-started

I followed the instructions...
```
mkdir hello
cd hello
code hello.go
```
and pasted this in
```go
package main

import "fmt"

func main() {
    fmt.Println("Hello, World!")
}
```
then ran
```
go run hello.go
```
and the output was
```
go run .
# runtime
c:\go\src\runtime\panic.go:1189:1: syntax error: non-declaration statement outside function body
```

I imagine there are other go commands that would cause the same output to appear.

I've packaged my C:\go and C:\users\alice\go folders into a zip file for debugging convenience.

[C:\go](https://drive.google.com/file/d/1KKPhvECNcpFXWYIRrfESmyNpn9R127k1/view?usp=sharing)

**Comment by davecheney** [comment]
This class of bug occurs if one copy of Go is unpacked on top of another. I’d go ahead and delete your go install and start afresh.

**Comment by AskAlice** [comment]
It worked after installing the latest update. 

I find that interesting given i had used it earlier today and it worked fine, and I didn't install go since then.... How could go unpack ontop of another? Could the VSCode extension maybe have have done that?
