### ISSUE TITLE
x/website/content/static/doc/tutorial: needs to suggest 'go mod init' before 'go run .'

### ISSUE THREAD

**Issue by hyangah** [golang/go#44003]
https://tip.golang.org/doc/tutorial/getting-started#code

The first section needs update to include `go mod init` command.
Otherwise, users will face a compile error for their first program.

```
$ go run .
go: cannot find main module; see 'go help modules'
```

cc @stevetraut

**Comment by seankhliao** [comment]
https://tip.golang.org/doc/tutorial/getting-started#call

The second section also needs an explicit call to `go get`

```
» go run .
main.go:6:2: no required module provides package rsc.io/quote; to add it:
	go get rsc.io/quote
```

**Comment by dmitshur** [comment]
This is the same as #43672, so I'll close this issue and update that one.
