### ISSUE TITLE
question: NaN hex value

### ISSUE THREAD

**Issue by andybbruno** [golang/go#44015]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/andrea/Library/Caches/go-build"
GOENV="/Users/andrea/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/andrea/workspace/TSXor-Go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/andrea/workspace/TSXor-Go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1q/6z9rflzn1bsb6nlh158wktwh0000gn/T/go-build270156418=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### Description

I'm writing a porting of a time-series compressor algorithm originally written in C++. Since the input is composed of floating-point values, and since I want to apply bitwise operations over them, I extensively use functions like `math.Float64bits()` and `math.NaN()`. During my tests, I notice that the [`NaN`](https://github.com/golang/go/blob/master/src/math/bits.go#L8) value is equal to `0x7FF8000000000001` whereas the C++ version is equal to `0x7FF8000000000000`. 

### Question

Why last bit is set to 1? Is there a particular reason? If not, can it be modified to allow compatibility with C++ `NaN`?

**Comment by seankhliao** [comment]
For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by andybbruno** [comment]
Sorry, I will convert it to a proposal
