### ISSUE TITLE
runtime: Why does hchan's closed field typed as uint32 and not as uint8 or bool?

### ISSUE THREAD

**Issue by FluorescentTouch** [golang/go#44038]
https://github.com/golang/go/blob/46cb016190389b7e37b21f04e5343a628ca1f662/src/runtime/chan.go#L37

I tried to find answer, but failed.
Hchan's _closed_ field can store values 0 or 1. 
What was the reason not to use at least _uint8_ or _uint16_ instead of _uint32_ ?
What the fundamental reasons not to use _bool_?
Hope, @dvyukov (last [modifier](https://go-review.googlesource.com/c/go/+/4900/) of this code) or anyone else can explain this to me for better understanding of chan internals.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
