### ISSUE TITLE
Attempting to link with file built for unknown-unsupported file format error

### ISSUE THREAD

**Issue by essial** [golang/go#44033]
### What version of Go are you using (`go version`)?
<pre>
go version go1.15.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/lunaticedit/Library/Caches/go-build"
GOENV="/Users/lunaticedit/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/lunaticedit/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/lunaticedit/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/lunaticedit/Documents/GitHub/fanticon/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b9/bh868mtn6m30qm46l6cfyc0m0000gn/T/go-build990067894=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Built an application.

### What did you expect to see?
It build without errors.

### What did you see instead?
```
/Users/lunaticedit/go/go1.15.7/bin/go build -i -o /private/var/folders/b9/bh868mtn6m30qm46l6cfyc0m0000gn/T/___10Fanticon github.com/essial/fanticon/cmd/fanticon #gosetup
# github.com/essial/fanticon/cmd/fanticon
ld: warning: ignoring file /var/folders/b9/bh868mtn6m30qm46l6cfyc0m0000gn/T/go-link-943942247/000000.o, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x4C 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x90 0x2E 0x00 0x00 0x01 0x00 0x00 0x00 )
```

The app actually finishes building and runs just fine, but I always get that link warning.

**Comment by davecheney** [comment]
Thank you for raising this issue, unfortunately you haven’t provided enough details for someone else to reproduce the problem you are having.

**Comment by essial** [comment]
I'm not sure how to provide more info.. Are there any debug switches I can use to send more info? The file path of 00000.o doesn't exist after the build.

**Comment by davecheney** [comment]
Can you provide a way for someone else to reproduce the error you are seeing?

**Comment by essial** [comment]
I figured it out! It seems if you have a file with the `.syso` extension, it blows up the linker and fails to build on linux (only has a warning on MacOSX). That should help!

**Comment by zephyrtronium** [comment]
The go tool intentionally includes syso files in the built archive, and it lists them in the `SysoFiles` field of `go list -json`. (I should have been more specific on Discord about the intent of having you run that command. It would have saved some trouble. My mistake!)

**Comment by cherrymui** [comment]
Do you want the .syso file to be included in the executable? If so, make sure it is an object file for the target platform (for macOS, it needs to be a Mach-O file). If not, rename the file to something else.

**Comment by ianlancetaylor** [comment]
It sounds like this has been fixed, so closing.  Please comment if I misunderstand.  Thanks.

**Comment by essial** [comment]
Why would it include this file?
I would think at minimum it should tell me what it's trying to link. Saying 00000.o doesn't tell me anything, thus there is no real path to troubleshoot this linker step error. I just so happened to suspect this file, but I can see this being a huge issue if you aren't a solo developer and someone accidentally includes one of these 'magic' file types that cause linkers to fail.

**Comment by ianlancetaylor** [comment]
A `.syso` file is passed to the system linker.  It has to be an object file that the system linker will accept.  You can build tags in the file name, as in "x_linux.syso", to only build on certain systems.

There aren't other magic file types.

It's true that the point of the linker invocation the original file name has been lost.  This is not trivial to fix, but please feel free to go ahead and open an issue for reporting the original name when there is an error linking a `.syso` file.  Thanks.
