### ISSUE TITLE
x/website: https://golang.org featured video is unavailable https://youtu.be/cQ7STILAS0M

### ISSUE THREAD

**Issue by ader1990** [golang/go#44037]
The featured video from https://golang.org (bottom-left of the page) is unavailable. The youtube link is https://www.youtube.com/watch?v=cQ7STILAS0M.

**Comment by ALTree** [comment]
Thanks for reporting this.

It appears that that video is actually just the same Pike talk of another video (Simplicity is Complicated" talk from dotGo 2015) that is working correctly, so in https://github.com/golang/website/commit/7323790c7fe317a99b0e54387446e56e161a114e the link to cQ7STILAS0M was replaced with a link to the latter video. 

Looking at the [relevant code](https://github.com/golang/website/blob/4c40783eaee9044e2e3ec516fe05a7e5c50e1fb0/content/static/doc/root.html#L149), it seems like the video that is now broken is actually *not* in the list of the ones that are choosen at random; but the broken video is still [used as a placeholder](https://github.com/golang/website/blob/4c40783eaee9044e2e3ec516fe05a7e5c50e1fb0/content/static/doc/root.html#L74) in the html, so if you browse golang.org with javascript *disabled*, the script that replaces the placeholder video with one of the working videos doesn't run, and you get the static placeholder, which unfortunately now points to a dead video.

I cannot get the broken video by refreshing the page, but if I disable javascript I indeed get that one. Do you have javascript disabled?

In any case the default video that is server when the script doesn't run should be replaced with a link to a working video.

**Comment by ader1990** [comment]
Hello @ALTree,

I do not have JS disabled, it just appears unavailable. I tried to refresh (CTRL+R) a couple of times, and some featured videos were available, but at some point the unavailable one appeared too.

**Comment by ALTree** [comment]
Interesting, I don't see how could you be served with the broken link [looking at the code](https://github.com/golang/website/blob/4c40783eaee9044e2e3ec516fe05a7e5c50e1fb0/content/static/doc/root.html#L149) (it's not in the list of the videos), but I don't really know javascript so I may be missing something. 

cc @dmitshur

**Comment by ader1990** [comment]
It seems there is some sort of concurrency bug on Chrome only (I can repro it sporadically). I cannot reproduce with Firefox. Google Chrome version used: Version 88.0.4324.104 (Official Build) (64-bit) on Windows 10.

**Comment by ader1990** [comment]
I could repro the issue on a MacBook Pro with Chrome.

**Comment by ALTree** [comment]
Oh... so maybe a data race between the javascript code substituting the video, and the static value being shown (which points to a video it shouldn't be shown).
