### ISSUE TITLE
Misleading and false compiler error on assignment count mismatch

### ISSUE THREAD

**Issue by tv42** [golang/go#44030]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

go1.15.7 is the latest stable at this time.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tv/.cache/go-build"
GOENV="/home/tv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/tv/.cache/go-mod-cache"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tv/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/nix/store/407lnd2j7cpzcdw53kvwqxy2pmhixp1z-go-1.15.7/share/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/nix/store/407lnd2j7cpzcdw53kvwqxy2pmhixp1z-go-1.15.7/share/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/run/user/1000/go-build860811162=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/f99NWjvCqKW

```
package main

// note that foo returns 1 value
func foo() int { return 42 }

func main() {
	tmp := foo(), nil
	// ./main.go:7:6: assignment mismatch: 1 variables but foo returns 2 values
	_ = tmp
}
```

### What did you expect to see?

```
assignment mismatch: 1 variables but right side has 2 values
```

### What did you see instead?

An incorrect statement about a helper function.

I arrived at this from copy-pasting the body of log/syslog.NewLogger inline to my calling function, customizing what it does, and replacing the return in `return log.New(s, "", logFlag), nil` with `logger := ...`, without noticing the `, nil` at the end. The error message lead me to reading `log.New`, which I was quite sure returned only one value.

**Comment by ALTree** [comment]
Dup of #43348.

**Comment by tv42** [comment]
Yes, it is. I'm not thrilled that an existing bug is closed like that, but this dup adds no value.
