### ISSUE TITLE
runtime:return wrong result

### ISSUE THREAD

**Issue by TonoT** [golang/go#44045]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.15.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?
```go
package main

import "fmt"

func main() {
	subsets([]int{9, 0, 3, 5, 7})
}
func subsets(nums []int) (res [][]int) {
	res = append(res, []int{})
	for _, v := range nums {
		if v==7{
			fmt.Println(res)
		}
		for _, r := range res {
			fmt.Println(r)
			s := append(r, v)
			res = append(res, s)
		}
	}
	return
}
```
we can see the result 
```
[[] [9] [0] [9 0] [3] [9 3] [0 3] [9 0 3] [5] [9 5] [0 5] [9 0 5] [3 5] [9 3 5] [0 3 5] [9 0 3 5]]
[]
[9]
[0]
[9 0]
[3]
[9 3]
[0 3]
[9 0 3]
[5]
[9 5]
[0 5]
[9 0 5]
[3 5]
[9 3 5]
[0 3 5]
[9 0 3 7]
```
for slice it's [9 0 3 5],but for range it change to [9 0 3 7]

**Comment by seankhliao** [comment]
reopening a new issue doesn't help

please take the time to understand how slices work https://tour.golang.org/moretypes/7

**Comment by TonoT** [comment]
> reopening a new issue doesn't help
> 
> please take the time to understand how slices work https://tour.golang.org/moretypes/7



> reopening a new issue doesn't help
> 
> please take the time to understand how slices work https://tour.golang.org/moretypes/7

你脑子有毛病？？？你有没有试过就直接关了？我提了两遍了，我要是不知道我会直接提issue

**Comment by seankhliao** [comment]
please keep our [code of conduct](https://golang.org/conduct) in mind when commenting on the issue tracker

**Comment by TonoT** [comment]
> please keep our [code of conduct](https://golang.org/conduct) in mind when commenting on the issue tracker

Have you acted on this issue. I made sure that there is a problem with golang, you closed?

**Comment by TonoT** [comment]
> please keep our [code of conduct](https://golang.org/conduct) in mind when commenting on the issue tracker

i‘m sorry ,i have problem
