### ISSUE TITLE
cmd/pprof: "emulated forward to an arm pc that isn't in translated code" on mac M1

### ISSUE THREAD

**Issue by xiazemin** [golang/go#44042]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xiazemin/Library/Caches/go-build"
GOENV="/Users/xiazemin/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xiazemin/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xiazemin/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hb/1q06vpss7_d1fw3ymxb1ztbr0000gn/T/go-build783208607=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
go tool pprof

### What did you expect to see?

profile

### What did you see instead?
(pprof) top
assertion failed [abi_info.kind == AbiKind::TranslatedCode]: emulated forward to an arm pc that isn't in translated code. arm_pc=0x101ddf4d8 abi_kind=6 emulation_interval=[0x101e3cb64,0x101e3cb7c) instruction_interval=[0x101e3cb4c, 0x101e3cb7c) x86_rip=0x7fff20392ee4
(ThreadContextRegisterState.cpp:677 move_to_instruction_boundary)
I have the problem on mac M1 when I use pprof .

**Comment by changkun** [comment]
Does the problem still exist in the M1 optimized 1.16 release candidate?

Download: https://golang.org/dl/go1.16rc1.darwin-arm64.tar.gz

**Comment by ALTree** [comment]
As @changkun pointed out go1.15 is not supposed to work on the arm64 macs, so please try with the 1.16 release candidate.

**Comment by ALTree** [comment]
(and it seems that rosetta 2 has issues, see #42700).

**Comment by cherrymui** [comment]
Yes, this is a dup of #42700 (which is actually not a Go bug). Closing. Thanks.

**Comment by xiazemin** [comment]
> Does the problem still exist in the M1 optimized 1.16 release candidate?
> 
> Download: https://golang.org/dl/go1.16rc1.darwin-arm64.tar.gz

gcc_arm64.S:34:16: error: brackets expression not supported on this target
