### ISSUE TITLE
Why slice value changed?

### ISSUE THREAD

**Issue by TonoT** [golang/go#44044]
### What version of Go are you using (`go version`)?

<pre>
$ go version
 go1.15.3
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xuezg/Library/Caches/go-build"
GOENV="/Users/xuezg/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xuezg/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xuezg/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m1/l8pld1xn5nz2217q615nnm7w0000gn/T/go-build278976286=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
```go
package main

import "fmt"

func main() {
	subsets([]int{9,0,3,5,7})
}
func subsets(nums []int) (res [][]int) {
	res=append(res,[]int{})
	for _, v := range nums {
		for _, r := range res {
			s:=append(r,v)
			res=append(res,s)
		}
		fmt.Println(res)
	}
	return
}
```

### What did you expect to see?
```
[[] [9]]
[[] [9] [0] [9 0]]
[[] [9] [0] [9 0] [3] [9 3] [0 3] [9 0 3]]
[[] [9] [0] [9 0] [3] [9 3] [0 3] [9 0 3] [5] [9 5] [0 5] [9 0 5] [3 5] [9 3 5] [0 3 5] [9 0 3 5]]
[[] [9] [0] [9 0] [3] [9 3] [0 3] [9 0 3] [5] [9 5] [0 5] [9 0 5] [3 5] [9 3 5] [0 3 5] [9 0 3 7] [7] [9 7] [0 7] [9 0 7] [3 7] [9 3 7] [0 3 7] [9 0 3 7] [5 7] [9 5 7] [0 5 7] [9 0 5 7] [3 5 7] [9 3 5 7] [0 3 5 7] [9 0 3 7 7]]
```
this is output 
but with my expect,the following is collect
```
[[] [9]]
[[] [9] [0] [9 0]]
[[] [9] [0] [9 0] [3] [9 3] [0 3] [9 0 3]]
[[] [9] [0] [9 0] [3] [9 3] [0 3] [9 0 3] [5] [9 5] [0 5] [9 0 5] [3 5] [9 3 5] [0 3 5] [9 0 3 5]]
[[] [9] [0] [9 0] [3] [9 3] [0 3] [9 0 3] [5] [9 5] [0 5] [9 0 5] [3 5] [9 3 5] [0 3 5] *[9 0 3 5]*[7] [9 7] [0 7] [9 0 7] [3 7] [9 3 7] [0 3 7] [9 0 3 7] [5 7] [9 5 7] [0 5 7] [9 0 5 7] [3 5 7] [9 3 5 7] [0 3 5 7] *[9 0 3 5 7]*]
```

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by TonoT** [comment]
> Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.
> 
> For questions please refer to https://github.com/golang/go/wiki/Questions

it's not question, for something ,the result is worry

```go
package main

import "fmt"

func main() {
	subsets([]int{9, 0, 3, 5, 7})
}
func subsets(nums []int) (res [][]int) {
	res = append(res, []int{})
	for _, v := range nums {
		if v==7{
			fmt.Println(res)
		}
		for _, r := range res {
			fmt.Println(r)
			s := append(r, v)
			res = append(res, s)
		}
	}
	return
}
```

```
[[] [9] [0] [9 0] [3] [9 3] [0 3] [9 0 3] [5] [9 5] [0 5] [9 0 5] [3 5] [9 3 5] [0 3 5] [9 0 3 5]]
[]
[9]
[0]
[9 0]
[3]
[9 3]
[0 3]
[9 0 3]
[5]
[9 5]
[0 5]
[9 0 5]
[3 5]
[9 3 5]
[0 3 5]
[9 0 3 7]

```
