### ISSUE TITLE
How to improve the parallelism of go routine？

### ISSUE THREAD

**Issue by nnsgmsone** [golang/go#44041]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/go//bin"
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/home/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/compress/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build475748650=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I'm not sure how to deal with this phenomenon when I find that the parallel performance using go routine is not very good when writing database(olap) code. I have written the following example to verify this:
``` 
package main

import (
    "fmt"
    "hash/crc32"
    "time"
)

const (
    Loop = 10000
)

func main() {                                                                                                                      
    data := make([]byte, 4<<20)
    t := time.Now()
    for i := 0; i < Loop; i++ {
        crc32.ChecksumIEEE(data)
    }
    fmt.Printf("process: %v\n", time.Now().Sub(t))
}
```
```
package main

import (
	"fmt"
	"hash/crc32"
	"sync"
	"time"
)

const (
	Mcpu = 8
	Loop = 10000 / Mcpu
)

func main() {
	data := make([]byte, 4<<20)

	var wg sync.WaitGroup

	t := time.Now()
	for i := 1; i < Mcpu; i++ {
		wg.Add(1)
		go func(idx int) {
			defer wg.Done()
			tt := time.Now()
			for j := 0; j < Loop; j++ {
				crc32.ChecksumIEEE(data)
			}
			fmt.Printf("%v's process: %v\n", idx, time.Now().Sub(tt))
		}(i)
	}
	{
		tt := time.Now()
		for j := 0; j < Loop; j++ {
			crc32.ChecksumIEEE(data)
		}
		fmt.Printf("0's process: %v\n", time.Now().Sub(tt))

	}
	wg.Wait()
	fmt.Printf("process: %v\n", time.Now().Sub(t))
}
```
My machine has exactly 8 cpu's and I found that the runtime does not decrease linearly when the number of go routines increases.
### What did you expect to see?
I want to achieve a linear performance improvement with  cpu computation when the number of routines is less than or equal to the number of cpus.

### What did you see instead?
When the number of routines is smaller than the cpu, increasing the number of routines does not improve the performance very much.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by nnsgmsone** [comment]
@seankhliao  I've gotten a reply and it looks like the routines will cause go to be less than suitable for writing cpu intensive programs. Thanks a lot!
