### ISSUE TITLE
x/tools/gopls: rejects modules ending in /v1

### ISSUE THREAD

**Issue by juancer** [golang/go#44046]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.7 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\user\AppData\Local\go-build
set GOENV=C:\Users\jcervantes\AppData\Roaming\go\env  
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\user\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\user\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\AppServ\www\xxx\yyy\zzz\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\User~1\AppData\Local\Temp\go-build933812622=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

My temporal gopls file:
<pre>
module gopls-workspace

require mywebsite.online/v1 v0.0.0-goplsworkspace

replace mywebsite.online/v1 => C:\AppServ\www\xxx\yyy\zzz
</pre>

Vscode Version:
<pre>
1.52.1
ea3859d4ba2f3e577a159bc91e3074c5d85c0523
x64
</pre>

gopls -v version
<pre>
Build info
----------
golang.org/x/tools/gopls v0.6.4
    golang.org/x/tools/gopls@v0.6.4 h1:PO8rURGmi+QEKZ3pk+ZXJh51EFTVTSXqxzoRzrGSTJM=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.4 h1:L8R9j+yAqZuZjsqh/z+F1NCffTKKLShY6zXTItVIZ8M=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.0 h1:8pl+sMODzuvGJkmj2W4kZihvVb5mKm8pB/X44PIQHv8=
    golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a h1:DcqTD9SDLc+1P/r1EmRBwnVsrOwW+kk2vWf9n+1sGhs=
    golang.org/x/sys@v0.0.0-20210119212857-b64e53b001e4 h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=
    golang.org/x/tools@v0.1.1-0.20210119222907-0a1a9685734a h1:ttr/sghFptib3jlHwNS65KwGoqjr03TFzso3kpHyia8=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.0.1-2020.1.6 h1:W18jzjh8mfPez+AwGLxmOImucz/IFjpNlrKVnaj2YVc=
    mvdan.cc/gofumpt@v0.1.0 h1:hsVv+Y9UsZ/mFZTxJZuHVI6shSQCtzZ11h1JEFPAZLw=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
</pre>

Go settings in vscode:
<pre>
"go.languageServerFlags": [
        "-rpc.trace",
    ],
    "gopls": {
        "codelenses": {
        "generate": false,
        "gc_details": true
        }
    }
</pre>
### What did you expect to see?

Should be working, no?, well, no... :(

### What did you see instead?
<pre>
Error loading workspace: C:\Users\user~1\AppData\Local\Temp\gopls-workspace-mod684399923\go.mod:3: invalid module path C:\Users\user~1\AppData\Local\Temp\gopls-workspace-mod684399923\go.mod:5: replace mywebsite.online/v1: invalid module path
</pre>

**Comment by heschik** [comment]
Modules cannot be named ending with `/v1`, so if you've named your module that way, this is working intended. Otherwise, please follow the [troubleshooting guide](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md) and upload a verbose log.

**Comment by juancer** [comment]
hi @heschik, I already tried with website.online and I got the same error. Could you provide me an example to test it please.

Best

**Comment by stamblerre** [comment]
@juancer: Can you please make sure that you reload your VS Code window after you changed the name of your module? If that still doesn't fix the issue, please share your logs as per the [troubleshooting guide](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md).

**Comment by juancer** [comment]
hi @heschik and @stamblerre, thank you for your help, the solution of the situation is: the name of the module must be the same of the folder, example: "github.com/user/project" the module must be "website.com/project" wtih this configuration, gopls works perfectly.
Regards
