### ISSUE TITLE
x/tour: russian translation unavailable

### ISSUE THREAD

**Issue by tixass** [golang/go#44043]
### What did you expect to see?
Tour in Russian language

### What did you see instead?
![Screenshot_12](https://user-images.githubusercontent.com/36311940/106456748-04521d00-649f-11eb-992a-569da050c3c1.png)

**Comment by seankhliao** [comment]
Translations are run by third parties, eg the russian one probably by https://groups.google.com/g/golang-nuts/c/6MN5esr08Sw/m/wO_rLiqmCQAJ

**Comment by ALTree** [comment]
Please see golang/tour#1039. Closing here.
