### ISSUE TITLE
cmd/compile: possible miscompilation comparing interface to concrete value

### ISSUE THREAD

**Issue by josharian** [golang/go#44051]
I noticed this while modifying package `context` in CL 288193.

To reproduce:

```
git fetch https://go.googlesource.com/go refs/changes/93/288193/2 && git checkout FETCH_HEAD
```

Note that the package context tests pass.

Now at `context/context.go:306`, replace:

```go
pdone, _ := p.done.Load().(chan struct{})
if pdone != done {
```

with

```go
if p.done.Load() != done {
```

The tests fail.

Those two formulations should be identical (given that `p.done.Load()` is a `chan struct{}`, which it always is).

That suggests to me that we might be miscompiling the comparison `p.done.Load() != done`.

I've been unable to reproduce in a more minimized form, although I haven't tried very hard.

Tentatively marking as release blocker until diagnosed.

cc @mdempsky @cuonglm @randall77

**Comment by randall77** [comment]
Here's a simple reproducer:
```
package main

var c = make(chan int)

func main() {
	test1()
	test2()
}

func test1() {
	x := (<-chan int)(c)
	y, _ := f().(chan int)
	if y == x {
		println("OK")
	} else {
		println("BAD")
	}
}
func test2() {
	x := (<-chan int)(c)
	if f() == x {
		println("OK")
	} else {
		println("BAD")
	}
}

//go:noinline
func f() interface{} {
	return c
}
```

I'm actually not sure what the right behavior actually is. The fact that directional channels exist at compile time but don't really exist at runtime is probably part of this.

**Comment by mdempsky** [comment]
It seems like the spec's definition of equality is non-transitive for channels stored in interfaces:

```
package main

func main() {
	a := make(chan int)
	b := (<-chan int)(a)
	c := interface{}(b)

	println(a == b, b == c, a == c)
}
```

I think this behavior is surprising but correct per https://golang.org/ref/spec#Comparison_operators. "A value x of non-interface type X and a value t of interface type T are comparable when values of type X are comparable and X implements T. They are equal if t's dynamic type is identical to X and t's dynamic value is equal to x." `chan int` and `<-chan int` are different types.

**Comment by cherrymui** [comment]
The spec says
```
Interface values are comparable. Two interface values are equal if they have identical dynamic types and equal dynamic values or if both have value nil.
A value x of non-interface type X and a value t of interface type T are comparable when values of type X are comparable and X implements T. They are equal if t's dynamic type is identical to X and t's dynamic value is equal to x.
```
and
```
Two channel types are identical if they have identical element types and the same direction.
```

So, when comparing as interface values, the direction matters, and `test2` returns false correctly.

When comparing as concrete channel types, the spec says
```
Channel values are comparable. Two channel values are equal if they were created by the same call to make or if both have value nil.
```
without mentioning direction. So it seems reasonable for them to be equal.

I agree this is confusing...

**Comment by josharian** [comment]
> It seems like the spec's definition of equality is non-transitive for channels stored in interfaces

That's horrifying.

**Comment by randall77** [comment]
Maybe there's something to do here, but not for 1.16.

**Comment by randall77** [comment]
This also happens for non-channel cases:
```
package main

func main() {
	x := new(int)
	type P *int
	p := P(x)
	println(x == p)
	println((interface{})(x) == (interface{})(p))
}
```
prints `true false`.

**Comment by cuonglm** [comment]
@cherrymui 

> without mentioning direction. So it seems reasonable for them to be equal.

So it seems to me that the code in `runtime/type.go:typesEqual` are wrong, as it checks the channel direction for equality:

https://github.com/golang/go/blob/0b6cfea6342a7d95f74bc9e273039236ebd7e64f/src/runtime/type.go#L641

**Comment by randall77** [comment]
@cuonglm That quote was about channel *values*, not channel *types*. Channel type comparisons do take into account direction. Channel value comparisons do not (not sure how that would work anyway).

**Comment by bcmills** [comment]
> > It seems like the spec's definition of equality is non-transitive for channels stored in interfaces
> 
> That's horrifying.

That may be, but equality is defined in terms of assignability (https://golang.org/ref/spec#Comparison_operators):
> In any comparison, the first operand must be assignable to the type of the second operand, or vice versa.

And assignability is already not transitive — both because of the “at least one of `V` or `T` is not a defined type” restrictions, and because a type assignable to an interface may also be assignable to a type that does _not_ implement that interface.

**Comment by go101** [comment]
This doesn't look like a bug. Should it be closed?
