### ISSUE TITLE
time: RFC3339Nano Z is invalid for offset according to RFC3339

### ISSUE THREAD

**Issue by Aulilino** [golang/go#44064]
the code: RFC3339Nano = "2006-01-02T15:04:05.999999999Z07:00"

https://github.com/golang/go/blob/32e789f4fb45b6296b9283ab80e126287eab4db5/src/time/format.go#L83

In the definition of RFC3339(https://www.ietf.org/rfc/rfc3339.txt),  there is a clear explanation of character “Z”. It means no UTC offset when "Z" appeared.

```
      Z           A suffix which, when applied to a time, denotes a UTC
                  offset of 00:00; often spoken "Zulu" from the ICAO
                  phonetic alphabet representation of the letter "Z".
```

**Comment by seankhliao** [comment]
This is used to trigger different printing behaviour, from the docs:

> Replacing the sign in the format with a Z triggers the ISO 8601 behavior of printing Z instead of an offset for the UTC zone.

I think this is working as intended?

**Comment by ianlancetaylor** [comment]
Please show us a small working code example that demonstrates the problem.  Right now I don't see it.  Thanks.

**Comment by Aulilino** [comment]
According to RFC3339, it means NO offset, when Z exists in the format. 

The correct format should be "2006-01-02T15:04:05.999999999", "2006-01-02T15:04:05.999999999+07:00" or ""2006-01-02T15:04:05.999999999-07:00""

**Comment by seankhliao** [comment]
`time.RFC3339Nano` is a layout string, not a time

> Some valid layouts are invalid time values for time.Parse, due to formats such as _ for space padding and Z for zone information.

**Comment by Aulilino** [comment]
Got it. Seems I got it wrong. Thanks.
