### ISSUE TITLE
cmd/go: can not set GO111MODULE

### ISSUE THREAD

**Issue by linlih** [golang/go#44061]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.15.6
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
go env -w GO111MODULE=off
warning: go env -w GO111MODULE=... does not override conflicting OS environment variable

**Comment by seankhliao** [comment]
please fill out the full issue template
