### ISSUE TITLE
x/pkgsite: expand all should be collapse all when all directories are expanded

### ISSUE THREAD

**Issue by julieqiu** [golang/go#44072]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/cloud.google.com/go@v0.76.0#section-directories
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
 
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/5943521/106648580-763d6b80-655e-11eb-8c45-5698a9c163dc.png)

 
 
### What did you do?
 
Clicked "Expand all"
 

### What did you expect to see?
 
"Expand all" to change to "Collapse all"
 
### What did you see instead?

"Expand all" without option to collapse.

/cc @jamalc

**Comment by julieqiu** [comment]
The "Expand all" toggle can also be omitted when there is nothing to expand. For example, on https://pkg.go.dev/net/http@go1.15.6#section-directories:

![image](https://user-images.githubusercontent.com/5943521/106648790-bac90700-655e-11eb-8d46-0bde69d7a8c0.png)

**Comment by Olament** [comment]
I am wondering what state the "expanding all" button should be when only some of the directories are expanded. Also, Do you expect the "expanding all" button changes to "collapse all" if I manually expanded all the directories?

**Comment by jamalc** [comment]
I think the states can be:

- All collapsed (the default/initial state)
Expand All

- Some expanded, some collapsed 
Expand All | Collapse All

- All expanded
Collapse All

/cc'ing @georgehu @fflewddur for UX input.

**Comment by georgehu** [comment]
I would suggest simplifying the middle state with only "Expand All." Since the default is collapsed, users intention would be closer to show all rather than hide all. Clicking twice would achieve the same goal as "collapse all." This would keep the function to a single action and maintain consistency. 

@jamalc @julieqiu
