### ISSUE TITLE
x/tools/godoc: may show Go version when an identifier was modified rather than originally added

### ISSUE THREAD

**Issue by dmitshur** [golang/go#44081]
godoc (and in turn, https://golang.org/pkg/) displays next to identifiers the version of Go when said identifier was added. This was #5778.

As reported by @benhoyt in a [golang-dev thread](https://groups.google.com/g/golang-dev/c/gsoj5Vv15j0/m/XR9CYSRkAgAJ), godoc may sometimes show that an identifier was added in a Go version too new.

This happens when a signature is modified in a later Go version. For example, the `os.Chmod` function was added in Go 1 and appears in api/go1.txt as:

```
pkg os, func Chmod(string, FileMode) error
```

In Go 1.16, the `os.FileMode` type was modified (in an API compatible way: it became a type alias to `fs.FileMode`), causing `os.Chmod` to show up in [api/go1.16.txt](https://github.com/golang/go/blob/fca94ab3ab113ceddb7934f76d0f1660cad98260/api/go1.16.txt#L387):

```
pkg os, func Chmod(string, fs.FileMode) error
```

(As far as I can tell from `aliasReplacer` and its comment, added to `cmd/api` by @rsc in [CL 243906](https://golang.org/cl/243906), the api file content is working as intended; please comment otherwise.)

The fix in godoc is to look for the earliest api/go*.txt file where an identifier was mentioned. I'll send a CL.

CC @ianlancetaylor, @julieqiu.

**Comment by julieqiu** [comment]
This is https://github.com/golang/go/issues/37102 for pkgsite. We are planning to add this information for all packages.
