### ISSUE TITLE
x/pkgsite: remove package pkg.go.dev/github.com/selfapy/pkcs7

### ISSUE THREAD

**Issue by anex-at-work** [golang/go#44094]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/selfapy/pkcs7
  
### What did you expect to see?
 
Please remove completely the next package: https://pkg.go.dev/github.com/selfapy/pkcs7

Thank you for your support!

**Comment by jamalc** [comment]
Done.
