### ISSUE TITLE
dev.boringcrypto: tags for releases

### ISSUE THREAD

**Issue by jbrindle** [golang/go#44107]
My build team is concerned about reproducibility in builds and needs to ensure that the Go toolset build being used is stable and will produce reproducible binaries.

Would it be possible for goboring releases to have corresponding tags?

### What did you expect to see?
<pre>
$ git tag -l dev.boringcrypto.go1.15.7
dev.boringcrypto.go1.15.7
</pre>

### What did you see instead?
<pre>
$ git tag -l dev.boringcrypto.go1.15.7
</pre>

**Comment by seankhliao** [comment]
cc @FiloSottile

**Comment by FiloSottile** [comment]
We generally don't tag dev branches, but the RELEASES file includes the git commit of each release, and it's append-only.

https://go.googlesource.com/go/+/refs/heads/dev.boringcrypto/misc/boring/RELEASES?format=TEXT

**Comment by jbrindle** [comment]
Tags incur basically no cost, what is the argument against them?

**Comment by FiloSottile** [comment]
Tags are a global namespace, and tagging a dev branch does not fit well with our release process. Can you help me understand what tags would help with that the RELEASES file doesn't provide?

**Comment by jbrindle** [comment]
We can use the RELEASES file, but tags are what we use everywhere else for dependency tracking due to their nearly universal use, especially within the Go ecosystem. 

So it's fine, but awkward. FIPS stuff, in particular, is very sensitive about supply chain management so exceptions to tracking have to be documented and handled specially.
