### ISSUE TITLE
How the receiving end detects CRC data

### ISSUE THREAD

**Issue by lysShub** [golang/go#44103]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
y

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\LYS\AppData\Local\go-build
set GOENV=C:\Users\LYS\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\OneDrive\code\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\OneDrive\code\go
set GOPRIVATE=
set GOPROXY=https://goproxy.io,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\LYS\AppData\Local\Temp\go-build523719098=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
The `hash/crc32` package provides function `ChecksumIEEE` to calculate CRC check code. How the receiving end detects data.

```golang
package main

import (
	"fmt"
	"hash/crc32"
)

func main() {
	data := []byte("Helloworld")

	S := crc32.ChecksumIEEE(data)
	fmt.Printf("S : 0x%04X\n", S)

	// append CRC check code
	data = append(data, uint8(S>>24), uint8(S>>16), uint8(S>>8), uint8(S))

	rS := crc32.ChecksumIEEE(data)
	fmt.Printf("rS: 0x%04X\n", rS)
	// S : 0xB6B6237D
	// rS: 0x7B50A967
}
```
Shouldn't `rS`  be 0x00000000??

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
