### ISSUE TITLE
Go build targetting darwin/arm64 throws linker error.

### ISSUE THREAD

**Issue by EralpCelebi** [golang/go#44109]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.8 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/eralp/.cache/go-build"
GOENV="/home/eralp/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/eralp/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build137109639=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

CGO_ENABLED=0 GOARCH=arm64 GOOS=darwin go build

### What did you expect to see?
Nothing :D

### What did you see instead?
eralp@DESKTOP-RK06TSQ:~/codes/go/felisd$ env CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build
/usr/lib/go-1.13/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: unrecognized option '-pagezero_size'
/usr/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status

Thanks for the help in advance :)

**Comment by seankhliao** [comment]
dup #27855

**Comment by EralpCelebi** [comment]
I used CGO_ENABLED=0 and I am still getting this error @seankhliao
