### ISSUE TITLE
Gitea can't run due to GLIBC version incompatibility 

### ISSUE THREAD

**Issue by typeless** [golang/go#44114]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.15.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 20.04.2 LTS

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mural/.cache/go-build"
GOENV="/home/mural/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/mural/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mural"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/mural/src/golang.org/go1.15.5"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/mural/src/golang.org/go1.15.5/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/mural/src/code.gitea.io/gitea/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build869777529=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```
TAGS='bindata sqlite sqlite_unlock_notify' make build
```

### What did you expect to see
An executable that runs on my Synology NAS.

### What did you see instead?
```
/volume1/homes/git/gitea/gitea: /lib/libc.so.6: version `GLIBC_2.28' not found (required by /volume1/homes/git/gitea/gitea)
```

**Comment by typeless** [comment]
This can be solved by using musl libc with the following build command:
```
CC=musl-gcc LDFLAGS='--linkmode external --extldflags "-static"' TAGS='bindata sqlite sqlite_unlock_notify' make build
```
I can send a patch for that.
But I am not sure how to integrate it into the Makefile. (let it the default or add new make target?) 
Or just leaving the issue open for others to consult might just be good enough.

**Comment by davecheney** [comment]
@typeless did you mean to raise this on the gitea repository?

**Comment by typeless** [comment]
Please
