### ISSUE TITLE
Add an include path for `go tool cgo` for  vendored c libs

### ISSUE THREAD

**Issue by Tatskaari** [golang/go#44125]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jpoole/.cache/go-build"
GOENV="/home/jpoole/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jpoole/core3:/home/jpoole/core3/plz-out/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/tm/tools/go/1.14/usr/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/tm/tools/go/1.14/usr/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build291593539=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
I'm trying to compile confluent kafka which has a dependency on librdkafka. We compile librdkafka ourselves and I'm trying link against that. We're using `go install` as so:

```
$ GO111MODULE="off" go install github.com/confluentinc/confluent-kafka-go/kafka
third_party/go/src/github.com/confluentinc/confluent-kafka-go/kafka/00version.go:24:10: fatal error: 'librdkafka/rdkafka.h' file not found
```

I get something similar when invoking cgo directly: 
```
$ go tool cgo third_party/go/src/github.com/confluentinc/confluent-kafka-go/kafka/00version.go
/tmp/plz_sandbox/third_party/go/src/github.com/confluentinc/confluent-kafka-go/kafka/00version.go:24:10: fatal error: 'librdkafka/rdkafka.h' file not found
#include <librdkafka/rdkafka.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
I've tried passing build flags to `go tool cgo` through `-gccgoflags` though I'm not sure which flags to use. I've tried adding `-Ithird_party/cc/librdkafka` and `-isysetem third_party/cc/librdkafka` etc. but I don't think `go tool cgo` respects these. 

### What did you expect to see?
I need a way to tell `go tool cgo` (or `go install`) about system include directories to look in our vendored directory for `#include <librdkafka/librdkafka.h>`

### What did you see instead?
There don't appear to be any build flags I can pass to do this.

**Comment by bcmills** [comment]
Does `CGO_CFLAGS` work for your use-case?

(See https://golang.org/cmd/cgo/#hdr-Using_cgo_with_the_go_command and https://tip.golang.org/cmd/go/#hdr-Environment_variables.)

**Comment by ianlancetaylor** [comment]
Use a `#cgo CPPFLAGS:` line in your Go file or set the `CGO_CPPFLAGS` environment variable.  Both are documented at https://golang.org/cmd/cgo.

**Comment by Tatskaari** [comment]
Ah thanks a lot! I was setting that to a relative path and it wasn't working. Using an abs path works great!
