### ISSUE TITLE
Build error if Windows 10 userpath has a space like "C:\Users\MY PROFILE"

### ISSUE THREAD

**Issue by MHunterG** [golang/go#44126]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.7 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
IDK

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\MY PROFILE\AppData\Local\go-build
set GOENV=C:\Users\MY PROFILE\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\MY PROFILE\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\MY PROFILE\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\MY~1\AppData\Local\Temp\go-build043879594=/tmp/go-build -gno-record-gcc-switches
GOROOT/bin/go version: go version go1.15.7 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.15.7
gdb --version: GNU gdb (GDB) 8.1
</pre></details>

#### Just started a new project on GOLANG using new Windows user with space in username like as "MY PROFILE":

`go build`
`cgo: exec C:\Users\MY: exec: "C:\\Users\\MY": file does not exist`

**Comment by seankhliao** [comment]
duplicate #41400
