### ISSUE TITLE
Upgrading go from 1.15.7 to 1.15.8 doesn't use old installation path on Windows

### ISSUE THREAD

**Issue by aegoroff** [golang/go#44134]
### What version of Go are you using (`go version`)?

<pre>
go version go1.15.8 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\egr\AppData\Local\go-build
set GOENV=C:\Users\egr\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\code\golang\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\code\golang
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\egr\AppData\Local\Temp\go-build202219370=/tmp/go-build
</pre></details>

### What did you do?

Just upgraded golang from 1.15.7 to 1.15.8 under Windows using msi package. I didn't take into account setup path while doing upgrade first time. So to fix this i had to uninstall Golang and install again using old path (c:\Go)

### What did you expect to see?
Go installed to my old path c:\Go

### What did you see instead?
Go installed to c:\Program Files\Go

**Comment by tmthrgd** [comment]
The path change was an intentional result of #42070 as installing under C:\Go is a potential security vulnerability. You might want to take a look at the discussion there.

**Comment by aegoroff** [comment]
Thank you for the explanation. I see it's due to security reasons (Permissions on c:\go are too weak)

**Comment by iWdGo** [comment]
[Installation documentation](https://golang.org/doc/install) still mentions c:\Go. Issue is tagged Go 1.16 and was closed without mentioning a backport. No documentation update seems available.
