### ISSUE TITLE
net: "cannot unmarshal DNS message" when using netdns=go under Windows/WSL2 running ubuntu 20.04

### ISSUE THREAD

**Issue by ncw** [golang/go#44135]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Haven't tried go1.16-rc1 or tip

### What operating system and processor architecture are you using (`go env`)?

The problem has been reproduced with Microsoft Windows [Version 10.0.19042.746], WSL2 with Ubuntu 20.04

### What did you do?

Run [this program](https://play.golang.org/p/XP5M7MxcxUC) on WSL2 with Ubuntu 20.04. It is a very simple program, essentially just calling ` net.LookupHost`

```go
fmt.Printf("Looking up %q\n", host)
addrs, err := net.LookupHost(host)
if err != nil {
	fmt.Printf("- Failed with error: %v\n", err)
} else {
	for _, addr := range addrs {
		fmt.Printf("- Addr: %v\n", addr)
	}
}
```

### What did you expect to see?

I expected it to resolve names correctly

### What did you see instead?

```
$ ./host  prevasonline.sharepoint.com
Looking up "prevasonline.sharepoint.com"
- Failed with error: lookup prevasonline.sharepoint.com on 172.29.224.1:53: cannot unmarshal DNS message

$ GODEBUG=netdns=go ./host prevasonline.sharepoint.com
Looking up "prevasonline.sharepoint.com"
- Failed with error: lookup prevasonline.sharepoint.com on 172.29.224.1:53: cannot unmarshal DNS message

$ GODEBUG=netdns=cgo ./host prevasonline.sharepoint.com
Looking up "prevasonline.sharepoint.com"
- Addr: 13.107.136.9
```

This issue was originally from https://github.com/rclone/rclone/issues/4984 and @hstaugaard and @black-snow have reported it. I (@ncw) haven't verified it personally since I don't have Windows with WSL2.

This issue is superficially similar to https://github.com/golang/go/issues/37362 and https://github.com/golang/go/issues/36718 but the adddress in question doesn't have any SRV records and we aren't doing an SRV query, just `HostLookup`

**Comment by seankhliao** [comment]
can this be run with `GODEBUG=netdns=go+2` and `GODEBUG=netdns=cgo+2`, also what if the DNS servers are changed (eg. to 8.8.8.8)?

**Comment by hstaugaard** [comment]
> can this be run with `GODEBUG=netdns=go+2` and `GODEBUG=netdns=cgo+2`, also what if the DNS servers are changed (eg. to 8.8.8.8)?

```
$ GODEBUG=netdns=go+2 ./host prevasonline.sharepoint.com
Looking up "prevasonline.sharepoint.com"
go package net: GODEBUG setting forcing use of Go's resolver
go package net: hostLookupOrder(prevasonline.sharepoint.com) = files,dns
- Failed with error: lookup prevasonline.sharepoint.com on 172.29.128.1:53: cannot unmarshal DNS message

$ GODEBUG=netdns=cgo+2 ./host prevasonline.sharepoint.com
Looking up "prevasonline.sharepoint.com"
go package net: using cgo DNS resolver
go package net: hostLookupOrder(prevasonline.sharepoint.com) = cgo
- Addr: 13.107.136.9
```

Can't test Googles DNS, no public DNS on work network.

**Comment by jryan128** [comment]
Same issues with a different go program. When I run with +2:

```go package net: built with netgo build tag; using Go's DNS resolver
go package net: hostLookupOrder(****) = files,dns
```

**Comment by moxli** [comment]
I tested it with 1.16.2 and got the same results.

```
mdorner@lt01858 ~/code/debug/rclone_wsl2_dns_go_debug> go version
go version go1.16.2 linux/amd64

mdorner@lt01858 ~/code/debug/rclone_wsl2_dns_go_debug> go run ./host.go prevasonline.sharepoint.com
Looking up "prevasonline.sharepoint.com"
Failed with error: lookup prevasonline.sharepoint.com on 172.30.192.1:53: cannot unmarshal DNS message

mdorner@lt01858 ~/code/debug/rclone_wsl2_dns_go_debug> GODEBUG=netdns=go go run ./host.go prevasonline.sharepoint.com
Looking up "prevasonline.sharepoint.com"
Failed with error: lookup prevasonline.sharepoint.com on 172.30.192.1:53: cannot unmarshal DNS message

mdorner@lt01858 ~/code/debug/rclone_wsl2_dns_go_debug> GODEBUG=netdns=cgo+2 go run ./host.go prevasonline.sharepoint.com
Looking up "prevasonline.sharepoint.com"
go package net: using cgo DNS resolver
go package net: hostLookupOrder(prevasonline.sharepoint.com) = cgo
- Addr: 40.108.168.35`
```

**Comment by ncw** [comment]
@seankhliao @gopherbot please re-open this - the info was provided above and the issue isn't fixed - thanks!

**Comment by eric-engberg** [comment]
I just started experiencing this issue myself with terraform 0.13.5... i haven't updated terraform so no idea why it suddenly started.

**Comment by tianhendi** [comment]
您的邮件我已经收到
