### ISSUE TITLE
cmd/compile: confusing message when go.mod file and vendor folder both present

### ISSUE THREAD

**Issue by dotaheor** [golang/go#44149]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.8 linux/amd64
go version go1.16rc1 linux/amd64
</pre>

### What did you do?

```
package main

import _ "aaa"

func main() {
}
```

### What did you expect to see?

`package aaa is not in GOROOT (GOROOT/src/aaa)`

### What did you see instead?

```
cannot find package "." in:
	ProjectRoot/vendor/aaa
```

**Comment by seankhliao** [comment]
What exactly did you do, I can't reproduce the issue as described

Also note that names without a dot in the first element are considered reserved for the standard library, using a proper name gives a better error message

```sh
» mkdir /tmp/example && cd /tmp/example

» go mod init example.com/foo
go: creating new go.mod: module example.com/foo

» cat << EOF > main.go
package main
import _ "aaa"
func main() {}
EOF

» go build
main.go:3:8: package aaa is not in GOROOT (/home/arccy/sdk/gotip/src/aaa)

» mkdir vendor

» go build
main.go:3:8: cannot find package "." in:
	/tmp/example/vendor/aaa
```

**Comment by dotaheor** [comment]
You exactly reproduced the error described above.

**Comment by seankhliao** [comment]
I don't think it's a problem? Without `vendor/` a package with a name like `aaa` cannot be retrieved by standard tooling so it makes sense to report it as not found in `GOROOT`. With `vendor/`, which can be created by other tools, it is possible to use a package named like that

**Comment by dotaheor** [comment]
OK, but shouldn't the message be
```
cannot find package "aaa" in:
	ProjectRoot/vendor
```

`package "."` confuses people.

**Comment by seankhliao** [comment]
that's #38748

**Comment by dotaheor** [comment]
Looks so.
