### ISSUE TITLE
cmd/compile: compiler can fault in low memory conditions

### ISSUE THREAD

**Issue by bradfitz** [golang/go#4415]
<pre>OpenBSD compiler crash,

From
<a href="http://build.golang.org/log/081228dc3bc44ae1f6911395558c17ae16176b61">http://build.golang.org/log/081228dc3bc44ae1f6911395558c17ae16176b61</a>

internal compiler error: fault</pre>

**Comment by mdempsky** [comment]
I think this is no longer an issue since cmd/compile was ported to Go. The Go runtime is now responsible for reporting when memory allocation fails.
