### ISSUE TITLE
runtime/metrics: typos in documentation

### ISSUE THREAD

**Issue by gazerro** [golang/go#44150]
There are some typos in the documentation of the new "runtime/metrics" package

* `encouranged` should be `encouraged`
* `"kind."` should be `"kind".`
* `the a tag` should be `the tag`

**Comment by ianlancetaylor** [comment]
Thanks for reporting these.  I think "kind." is not wrong; American English normally puts punctuation inside quotation marks.  I sent a change to fix the other two.
