### ISSUE TITLE
x/tools/gopls: `unusedparams` should ignore unused params in functions satisfying the `http.HandlerFunc` type

### ISSUE THREAD

**Issue by PSalant726** [golang/go#44152]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- 1.15.7 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- 0.6.5
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.53.0
* Check your installed extensions to get the version of the VS Code Go extension
	- 0.22.0

### Share the Go related settings you have added/edited

```json
"[go]": {
        "editor.codeActionsOnSave": { "source.organizeImports": true },
        "editor.formatOnSave": true
},
"[go.mod]": {
        "editor.codeActionsOnSave": { "source.organizeImports": true },
        "editor.formatOnSave": true
},
"go.coverOnTestPackage": false,
"go.formatTool": "goimports",
"go.lintFlags": ["--fast", "--max-same-issues=0"],
"go.lintTool": "golangci-lint",
"go.playground": { "run": false },
"go.testFlags": ["-count=1", "-cover"],
"go.toolsManagement.autoUpdate": true,
"gopls": {
        "ui.codelenses": { "generate": false, "test": true },
        "ui.completion.usePlaceholders": true,
        "ui.diagnostic.analyses": { "unusedparams": true }
}
```

### Describe the bug
With code like the below example, where a function (`previewHandler`) satisfies the `http.HanderlFunc` type, but does not use or modify the `http.Request` (second argument), the `unusedparams` analyzer included with `gopls` should not warn on the issue.

```go
package main

import (
  "log"
  "net/http"
  "text/template"

  "github.com/gorilla/mux"
)

func NewRouterWithRoutes() *mux.Router {
  var (
    router = mux.NewRouter()
    get    = router.Methods(http.MethodGet).Subrouter()
  )

  get.HandleFunc(PathPreview, previewHandler)

  return router
}

func previewHandler(w http.ResponseWriter, r *http.Request) {  // WARNING: potentially unused parameter: 'r' (unusedparams)
  if err := templates.ExecuteTemplate(w, "preview.html", &Page{}); err != nil {
    http.Error(w, err.Error(), http.StatusInternalServerError)
    log.Println(err)
  }
}
```

**Comment by hyangah** [comment]
Don't people use `_` or unnamed params to make it clear the params aren't used in the body?
The unusedparams analyzer already ignores parameters that do not have a name or are underscored.

cc @stamblerre

**Comment by PSalant726** [comment]
> Don't people use `_` or unnamed params to make it clear the params aren't used in the body?

Yes, some do, but this isn't strictly enforced by the compiler. I don't believe that `gopls` should warn on functions that implement such a commonly used type.

**Comment by giter** [comment]
I don't think we should use `_` to mark a large number of `context Context`

**Comment by findleyr** [comment]
I think there are benefits to leaving this diagnostic for unused parameters, even in `http.HandlerFunc`. Imagine the following scenario, where there are two writers in scope.

![image](https://user-images.githubusercontent.com/57144380/150601015-f305ab3d-ede0-4325-b518-e46beacf2a38.png)

In this case, the `unusedparams` diagnostic makes it more noticeable that the wrong writer is being used. This is admittedly a bit contrived, but not unreasonable, IMO.

Generally, I think the `unusedparams` analyzer falls into the category of "opinionated" analyzers, that not everyone agrees with. This is why it is disabled by default. When using this analyzer, I sometimes _do_ need to rename parameters to `_` just to make the analyzer happy. However, in those cases it arguably improves the clarity of the code:

- It becomes locally evident that the parameter is not used.
- There is one fewer name in scope.
- It is clear to the next reader that the parameter is intentionally unused.

To add to that, there is a nontrivial cost to keeping a list of signatures that are exempted from unused params diagnostics, both in terms of maintenance, and in terms of the cognitive overhead for users, who may be confused by a missing diagnostic.

Based on this, I think we will likely decline to make this change.

**Comment by PSalant726** [comment]
Based on feedback from @hyangah and @findleyr , and after continued use of `unusedparams` in several projects, I no longer believe this omission should be implemented.

If others disagree, I would encourage them to reopen this issue and continue to push it forward.
