### ISSUE TITLE
reflect: DeepEqual fails with matching key/value pairs in maps

### ISSUE THREAD

**Issue by codeblooded** [golang/go#44154]
### What version of go are you using?

I noticed the issue when running code commit c8bd8010ff, but I can confirm this problem exists on Go Playgrounds as well (see link in next section).

### What did you do?

I created two maps with equal keys and values. Then, I compared them using `reflect.DeepEqual`.

https://play.golang.org/p/OjDV7PWt1SY

### What did you expect to see?

> Map values are deeply equal when all of the following are true: they are both nil or both non-nil, they have the same length, and either they are the same map object or their corresponding keys (matched using Go equality) map to deeply equal values. (https://golang.org/pkg/reflect/#DeepEqual).

The maps are structurally different, but they have equal keys/values and length. I would expect them to be equal.

### What did you see instead?

The maps are not structurally identical, so `reflect.DeepEqual` returns false.

**Comment by fraenkel** [comment]
If you change your code to either
```
expected := &MissingComponents{map[string]int{
		DefaultClientPool: 4,
		DefaultServerPool: 1,
		DefaultDriverPool: 1,
	}}
```
or
`fmt.Printf("Do they match? %v\n", reflect.DeepEqual(actual.NodeCountByPool, expected))`
you end up with true. Comparing a struct to a map will never be equal.

**Comment by ianlancetaylor** [comment]
Closing because this is working as expected.  Please comment if you disagree.

**Comment by codeblooded** [comment]
Sorry, I extracted some of the logic into a playground and mistyped. Wasn't going to share the entire project. In the actual project, I'm not comparing a struct to a map. This is actually failing in a unit test using the ginkgo/gomega frameworks. According to [their docs](https://onsi.github.io/gomega/#equalexpected-interface), gomega uses `reflect.DeepEqual` under the hood:

For the following test case:
```go
It("sets the number of nodes missing from each pool", func() {
	actualReturn = CheckMissingPods(test, allRunningPods)
	Expect(actualReturn.NodeCountByPool).To(Equal(
		map[string]int{
			DefaultClientPool: 0,
			DefaultDriverPool: 0,
			DefaultServerPool: 0,
		},
	))
})
```

This is the failed expectation we are seeing:
```
• Failure [0.000 seconds]
CheckMissingPods some of pods from the current load test is running [It] sets the number of nodes missing from each pool 
~/benreed/grpc/test-infra/status/missing_pods_test.go:126

  Expected
      <map[string]int | len:4>: {
          "__default_pool (drivers)": 0,
          "__default_pool (servers)": 0,
          "workers-8core": 4,
          "__default_pool (clients)": 0,
      }
  to equal
      <map[string]int | len:4>: {
          "workers": 4,
          "__default_pool (clients)": 0,
          "__default_pool (drivers)": 0,
          "__default_pool (servers)": 0,
      }

 ~/benreed/grpc/test-infra/status/missing_pods_test.go:128
```

I will need to dive in to see if this is some sort of issue with gomega, since it did not replicate in the playground. I'll comment here if I cannot see a way gomega could cause this failure, and I'll update what I find regarding the framework in onsi/gomega#412.

**Comment by ianlancetaylor** [comment]
In the failure message one of the maps has the key `"workers-8core"` and the other has the key `"workers"`.

**Comment by codeblooded** [comment]
@ianlancetaylor Thank you. I don't see how I missed that. I haven't felt well the last two days, and I knew I'm feeling crazy tired… guess I just thought I was still functional. Sorry to waste your time.

**Comment by ianlancetaylor** [comment]
No worries.
