### ISSUE TITLE
virustotal reports an error for go1.15.8.linux-amd64.tar.gz

### ISSUE THREAD

**Issue by uli-heller** [golang/go#44161]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.15.8?
</pre>

Actually, I just downloaded the tar.gz. I don't use it due to the virus detection

### Does this issue reproduce with the latest release?

Don't know. It is probably more an issue of the artifact.

### What operating system and processor architecture are you using (`go env`)?

None, just downloaded the artifact and put it into virustotal.com

### What did you expect to see?

![image](https://user-images.githubusercontent.com/1677414/107229226-d11f0900-6a1d-11eb-9494-dd472668292f.png)

### What did you see instead?

![image](https://user-images.githubusercontent.com/1677414/107229242-d714ea00-6a1d-11eb-994d-0def7050de0f.png)

**Comment by ALTree** [comment]
Very likely a false positive, please see https://golang.org/doc/faq#virus.

**Comment by uli-heller** [comment]
Sorry, missed reading the faq, just searched the issues. Thx for your feedback
