### ISSUE TITLE
wiki: CodeReviewComments change: suggest got/want phrasing instead of actual/expected.

### ISSUE THREAD

**Issue by tylerhou** [golang/go#44179]
Google's internal Go style has converged on "got/want" phrasing for test failures, with got before want. This is [reflected in the Standard Library tests, but there are exceptions.](https://golang.org/src/io/io_test.go) Even in the linked io_test.go there is one test that is written in the "expected/got" style.

I think it would be useful for the external style guide to suggest "got/want" as the common convention for test output: "In test messages, prefer using the terms 'got/want' instead of 'actual/expected.'"

Creating a common convention would make it easier for programmers to read + understand unfamiliar Go tests. It would also mean that we could add a 'got/want' lint rule to Golint.

**Comment by dmitshur** [comment]
There is a [golang.org/wiki/TestComments](https://golang.org/wiki/TestComments) page that is a supplement to the main [golang.org/s/style](https://golang.org/s/style) guide but targets test code specifically (it was proposed and accepted in issue #34384).

This request is in scope of that page, and I think it's already covered there, see:

https://golang.org/wiki/TestComments#got-before-want

Perhaps we should include a link to TestComments from CodeReviewComments though.

CC @golang/release.

**Comment by tylerhou** [comment]
In TestComments there is no recommendation to use "got/want" instead of "actual/expected." Though I support adding it there instead.

**Comment by dmitshur** [comment]
I see that https://golang.org/wiki/TestComments#identify-the-function makes a relevant recommendation. Do you think that covers this?

**Comment by tylerhou** [comment]
The main goal that I want to accomplish is to write a linter rule that warns me if I ever use the words "expect" or "actual" in Go test output, because around 10% of the time I write "expected" instead of "want" and my readability reviewer nits me on it.

To accomplish the above goal, I would like a sentence in CodeReviewComments/TestComments that says "prefer got/want over actual/expected." That way if people ask whether my "avoid actual/expected" linter rule is within scope for Golint, I can point them to that sentence.

TestComments#identify-the-function implies that people should use got/want, but it doesn't explicitly say it. Which makes my case for a linter rule less strong. I would still support adding the "avoid actual/expected" sentence to that section, though.

**Comment by seankhliao** [comment]
Note #38968 where lint is marked for freeze/deprecation

**Comment by tylerhou** [comment]
In that case, I will look into adding this rule as a local modification of the our linter (which probably doesn't require this CodeReviewComments change).
