### ISSUE TITLE
cmd/link: go version go1.16beta1 darwin/arm64 on mac M1 do not support rd_kafka

### ISSUE THREAD

**Issue by xiazemin** [golang/go#44186]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?

/usr/local/go/pkg/tool/darwin_arm64/link: running clang failed: exit status 1
ld: warning: ld: warning: ignoring file /var/folders/hb/1q06vpss7_d1fw3ymxb1ztbr0000gn/T/go-link-108461093/go.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64ignoring file /var/folders/hb/1q06vpss7_d1fw3ymxb1ztbr0000gn/T/go-link-108461093/000000.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64

ld: warning: ignoring file /var/folders/hb/1q06vpss7_d1fw3ymxb1ztbr0000gn/T/go-link-108461093/000001.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64

Undefined symbols for architecture x86_64:
  "__cgo_topofstack", referenced from:
      __cgo_fe4f1822ce7d_Cfunc_ConfigEntry_by_idx in 000007.o
      __cgo_fe4f1822ce7d_Cfunc_ConfigResource_by_idx in 000007.o
      __cgo_fe4f1822ce7d_Cfunc_rd_kafka_AlterConfigs_result_resources in 000007.o
      __cgo_fe4f1822ce7d_Cfunc_rd_kafka_ConfigEntry_is_read_only in 000007.o
      __cgo_fe4f1822ce7d_Cfunc_rd_kafka_ConfigEntry_is_sensitive in 000007.o
      __cgo_fe4f1822ce7d_Cfunc_rd_kafka_ConfigEntry_is_synonym in 000007.o
      __cgo_fe4f1822ce7d_Cfunc_rd_kafka_ConfigEntry_name in 000007.o
      ...
  "_main", referenced from:
     implicit entry/start for main executable

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by seankhliao** [comment]
please fill out the full issue template

**Comment by cherrymui** [comment]
> ld: warning: ld: warning: ignoring file /var/folders/hb/1q06vpss7_d1fw3ymxb1ztbr0000gn/T/go-link-108461093/go.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64

It sounds like you compiled the program for x86 but trying to link it for arm64? Could you post the exact command(s) you run to build the program, as well as your environment?
