### ISSUE TITLE
Golang can be a foundation project?

### ISSUE THREAD

**Issue by netroby** [golang/go#44184]
Hello , today , the Rust foundation complete setup.
I wonder to know how do google think about golang. 
Can it be setup an opensource foundation to contribute golang as well?

I can see Google also backed up with Rust lang.

**Comment by netroby** [comment]
![image](https://user-images.githubusercontent.com/66301650/107320290-5f0cf980-6adb-11eb-98aa-dafd3d4d8cb7.png)
![image](https://user-images.githubusercontent.com/66301650/107320318-6f24d900-6adb-11eb-971d-90056bebc214.png)

**Comment by mdlayher** [comment]
I apologize for closing this, but this discussion is more suited to a mailing list than the Go issue tracker. Please see https://groups.google.com/g/golang-nuts.

**Comment by golang730** [comment]
rust除了所谓的“内存安全”外，没有任何优势，一点不人性化，看看那个语法乱的，长时间这样开发，难道不会累
相比之下go的“大道至简”却非常的能减轻开发者的心智负担，
