### ISSUE TITLE
go/doc: find a better home for Go documentation features like section headings

### ISSUE THREAD

**Issue by matttproud** [golang/go#44194]
[fluhus/godoc-tricks](https://github.com/fluhus/godoc-tricks) describes several extended tricks for the Godoc renderer that remain relevant for https://pkg.go.dev.  Particularly notable is the technique described as [Titles](https://pkg.go.dev/github.com/fluhus/godoc-tricks#Titles), which can be thought of as naive section headings as demonstrated below with the word "Limitations":

```go
// CreditCard models a lender-backed payment instrument.
//
// Limitations
//
// The type provides no native validation against its issuer.  It is a dumb data type.
type CreditCard struct{}
```

To date this technique is not substantively mentioned in any of the following:

* https://blog.golang.org/godoc
* https://golang.org/pkg/go/doc/ (minor prosaic allusion)

Considering its utility for information presentation, anchoring, etc., I propose the feature earn proper documentation.  I tried to search for an existing bug for this, but the closest thing I could find was https://github.com/golang/go/issues/18342.  The correct approach would probably involve amending the previous documents somehow (or maybe another).

**Comment by dmitshur** [comment]
I'll highlight the current documentation at https://golang.org/pkg/go/doc/#ToHTML:

> Each span of unindented non-blank lines is converted into a single paragraph. There is one exception to the rule: **a span that consists of a single line, is followed by another paragraph span, begins with a capital letter, and contains no punctuation other than parentheses and commas is formatted as a heading.**

If we had documentation about writing documentation (similar to https://blog.golang.org/godoc, but as evergreen documentation rather than a blog post), I agree this should be covered there. I don't know if there are plans to do this at this time.

CC @julieqiu, @stevetraut, @griesemer.

**Comment by dmitshur** [comment]
I expect [CL 410394](https://go.dev/cl/410394) (CC @rsc) will resolve this issue.
