### ISSUE TITLE
Plugins are picky about import paths/scopes even with identical libraries

### ISSUE THREAD

**Issue by ellemlabs** [golang/go#44197]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.6 linux/amd64
</pre>
### What did you do?

*lib1/lib.go*
```
package lib
type MyInt int
```
*plugin1.go*
```
package main
import lib "./lib1"
func GetMyInt() lib.MyInt {
return lib.MyInt(1)
}
```
*lib2/lib.go* is same contents as lib1/lib.go.
*plugin2.go* is same contents as plugin1.go, except it imports "./lib2" instead of "./lib1"

Both plugins are compiled as follows:
```
$ go build -buildmode=plugin plugin1.go
$ go build -buildmode=plugin plugin2.go
```

*loader.go*
```
package main
import lib "./lib1"
import "plugin"
func main() {
    plugin2,_ := plugin.Open("plugin2.so")
    symbol,_ := plugin2.Lookup("GetMyInt")
    myfunc := symbol.(func() lib.MyInt)
    println(myfunc())
}
```

This results in the panic:

```
panic: interface conversion: plugin.Symbol is func() lib.MyInt, not func() lib.MyInt (types from different scopes)
```

### What did you expect to see?

I expected to use plugin1 and plugin2 interchangeably when linking against the types in lib1.

### What did you see instead?

It seems Go doesn't like the idea of having two different import paths when asserting types from identical libraries.

However, this is a problem with what I'm dealing with. I've got a library with various types that will be used by other programmer's work ("plugins"). My software will then load the various plugins and assert the types against the same library. However, must I really force them to use the same GOPATH imports (ie, force them to use the same central github import path)? I like relative imports because it allows the programmer to use flexible project structures.

I would think that if the asserted type is completely identical to the memory footprint as the imported symbol, then it shouldn't panic as it technically makes it a valid symbol. I also want then to be able to make extensions to the library I distribute, which causes another panic being that the asserted types are of "different versions". 

**Is there no way for me to designate that lib1's types and lib2's types can be asserted against eachother?**

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
