### ISSUE TITLE
Now that Go Modules have been default for a long time, assume GO111MODULE=on by default. 

### ISSUE THREAD

**Issue by chewxy** [golang/go#44216]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.8 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="~/.cache/go-build"
GOENV="~/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="~/go/pkg/mod"
GONOPROXY="github.com/chewxy/graphqlsp"
GONOSUMDB="github.com/chewxy/graphqlsp"
GOOS="linux"
GOPATH="~/go"
GOPRIVATE="github.com/chewxy/graphqlsp"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build810152107=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
$ go get github.com/algolia/algoliasearch-client-go/v3@v3.16.0
```
The package is just an example. Any package with `@version` will fail with the same errors.

### What did you expect to see?

No errors

### What did you see instead?

<details><summary>go get output</summary><br><pre>
$ go get github.com/algolia/algoliasearch-client-go/v3@v3.16.0
go: cannot use path@version syntax in GOPATH mode
$ echo $GOPATH

$ echo $GO111MODULE

</pre>
</details>

This of course is easily fixed by 

```
$ export GO111MODULE=on
```

It's 2021. Shouldn't we be assuming that `$GO111MODULE=on` by default now? I'm aware of #37755 and I do think there might be some benefits for keeping GOPATH mode (which is very useful for working on interdependent packages with independent modules), but by default Go should always assume `$GO111MODULE=on` even when the environment variable is not set.

**Comment by fsouza** [comment]
This is already happening in 1.16 https://tip.golang.org/doc/go1.16#go-command

**Comment by ianlancetaylor** [comment]
Closing as dup of #41330.
