### ISSUE TITLE
all: merge dev.regabi to master when tree reopens

### ISSUE THREAD

**Issue by jeremyfaller** [golang/go#44224]
Development of the [register ABI](https://go.googlesource.com/proposal/+/refs/changes/78/248178/1/design/40724-register-calling.md) has continued while the 1.16 freeze has soaked. That work has wide-ranging effects on the compiler and runtime, and needs to be merged as soon as the tree reopens.

[Register ABI tracking issue](https://github.com/golang/go/issues/40724)

[Builder status](https://build.golang.org/?repo=&branch=dev.regabi)

This is a tracking issue for merging the `dev.regabi` branch to master once 1.16 ships.

**Comment by dmitshur** [comment]
This issue is ready to proceed, see https://github.com/golang/go/issues/44222#issuecomment-780122220. After this is done, please update that umbrella issue and let the next people in the list know. Thank you!
