### ISSUE TITLE
x/pkgsite: dhgitlab.dunnhumby.co.uk/dhgo/authproxy removal

### ISSUE THREAD

**Issue by ashleyjayawardene** [golang/go#44229]
### What is the URL of the page with the issue?

URL:  https://pkg.go.dev/dhgitlab.dunnhumby.co.uk/dhgo/authproxy
 

Hi,

I'd like to request the removal of a package from pkg.go.dev. We have found a package on the site that shouldn't be there. This documentation belongs to a private repository, which we would like to remain private. It also seems to have been published with some potentially sensitive information. The page seems old (dated april 2019) with available links to the code repository available, we think the code has been deleted from wherever it was hosted. I represent the owners/authors of this package, and we'd like to get the documentation page for this package removed from pkg.go.dev.

Thank you,
Dunnhumby Security Operations Analyst
Ashley Jayawardene

**Comment by jamalc** [comment]
Done.
