### ISSUE TITLE
math: Type Conversion of Inf(1) to int produces a negative integer instead of a positive one

### ISSUE THREAD

**Issue by BozeBro** [golang/go#44225]
```go
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println("Hello, playground")
	m := int(math.Inf(1))
	fmt.Println(m)
}

```
[go playground](https://play.golang.org/p/qAx6d8h5Hzg)

### What did you expect to see?

I expected to see positive infinity representation or  9223372036854775807

### What did you see instead?
 -9223372036854775807

**Comment by randall77** [comment]
This is implementation-dependent behavior, and not a bug.

The spec says:

> In all non-constant conversions involving floating-point or complex values, if the result type cannot represent the value the conversion succeeds but the result value is implementation-dependent.

Unfortunately +Inf is not representable as an `int`.
