### ISSUE TITLE
x/website: https://golang.google.cn/doc/tutorial/add-a-test

### ISSUE THREAD

**Issue by az13js** [golang/go#44236]
Hello, I found a spelling mistake in the tutorial published by official website. URL: [/doc/tutorial/add-a-test](https://golang.google.cn/doc/tutorial/add-a-test) , it says "If this code, you:", I think it should be "In this code, you:".

**Comment by ALTree** [comment]
Thanks for reporting this.

[CL 276772](https://go-review.googlesource.com/c/website/+/276772) would fix this, but it's in review.

**Comment by ALTree** [comment]
Fixed by the CL above.
