### ISSUE TITLE
spec: resulted type for division operation

### ISSUE THREAD

**Issue by inet56** [golang/go#44242]
In the spce at https://golang.org/ref/spec#Arithmetic_operators there is,

> Arithmetic operators apply to numeric values and yield a result of the same type as the first operand.

In my interpretation it says that,

```
3/2 - int
3/2.0 - int
3.0/2 - float64
3.0/2.0 - float64
```

But Go compiler produce `float64` for `3/2.0`.

**Comment by seankhliao** [comment]
This is covered as part of untyped constants / expressions: https://golang.org/ref/spec#Constant_expressions

3rd example:

```
const c = 15 / 4.0         // c == 3.75  (untyped floating-point constant)
```
