### ISSUE TITLE
x/tour: offline version of 'A Tour of Go' broken with modules

### ISSUE THREAD

**Issue by fzipp** [golang/go#44243]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16rc1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/fzipp/Library/Caches/go-build"
GOENV="/Users/fzipp/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/fzipp/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/fzipp/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16rc1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lc/1h4lth_d68zfy0rvwrv37tkm0000gn/T/go-build3688970254=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I tried to install the offline tour of Go via `go get` as described [here](https://golang.org/doc/#go_tour) and [here](https://tour.golang.org/welcome/3) and run it.

<pre>
$ go get golang.org/x/tour
go: downloading golang.org/x/tour v0.0.0-20201207214521-004403599411
go: downloading golang.org/x/tools v0.0.0-20190312164927-7b79afddac43
go: downloading golang.org/x/net v0.0.0-20190311183353-d8887717615a
$ tour
</pre>

### What did you expect to see?

Opening a web browser displaying my local version of the tour.

### What did you see instead?

<pre>
$ tour
2021/02/12 22:53:03 Couldn't find tour files: could not find go-tour content; check $GOROOT and $GOPATH
</pre>

Of course the files can't be found in $GOPATH, because `go get` downloaded it into the module cache.

**Comment by dmitshur** [comment]
Thanks for reporting. I'll take a look.

**Comment by dmitshur** [comment]
It's possible to fix this either by adjusting the code to look for tour files in module cache, or by embedding them in the binary. I chose with the latter and sent [CL 291849](https://golang.org/cl/291849).

**Comment by fzipp** [comment]
Thanks, the CL version starts locally.
There's still a problem with tour snippets that import "golang.org/x/tour/..." packages:

http://127.0.0.1:3999/moretypes/18
http://127.0.0.1:3999/methods/25
import "golang.org/x/tour/pic"
compile3.go:3:8: no required module provides package golang.org/x/tour/pic: working directory is not part of a module

http://127.0.0.1:3999/moretypes/23
import "golang.org/x/tour/wc"

http://127.0.0.1:3999/methods/22
import "golang.org/x/tour/reader"

http://127.0.0.1:3999/concurrency/8
import "golang.org/x/tour/tree"

**Comment by dmitshur** [comment]
Right, that will happen if the tour source code isn't available in GOPATH/src/golang.org/x/tour. To remove that requirement, we need to update tour to start building snippets in module mode (and supply a go.mod file that provides a version of the golang.org/x/tour module).

I've sent [CL 291889](https://golang.org/cl/291889) for that.

**Comment by dmitshur** [comment]
> It's possible to fix this either by adjusting the code to look for tour files in module cache, or by embedding them in the binary. I chose with the latter and sent [CL 291849](https://golang.org/cl/291849).

We can't quite start relying on Go 1.16+ APIs while Go 1.15 is still supported (not without causing much code duplication), so I sent [CL 298529](https://golang.org/cl/298529) to get the module cache fix in the interim.

**Comment by jfesler** [comment]
This works fine for running the binaries on the same host as you build the binaries.

https://github.com/google/go-licenses does the same trick.  Said binaries were not useful anywhere else.  I ended up having to duplicate the license data into a place I can embed, to produce a portable binary.

**Comment by dmitshur** [comment]
@jfesler Thanks for that information. Indeed, looking for content in the module cache can only work on a machine where Go is installed.

Go 1.17 will come out pretty [soon](https://groups.google.com/g/golang-dev/c/O3ae8bhs0ZU), at which point Go 1.15 will become unsupported and we can start relying on `//go:embed` for embedding assets into the binary itself ([CL 291849](https://golang.org/cl/291849)), which won't have that limitation.
