### ISSUE TITLE
x/website: merge module doc changes as part of Go 1.16 release

### ISSUE THREAD

**Issue by ALTree** [golang/go#44249]
1.16 introduces a `retract` directive. The new directive is not mentioned in the [Go Modules Reference](https://tip.golang.org/ref/mod#go-mod-file-grammar). The [CL adding the doc](https://go-review.googlesource.com/c/website/+/286952) will need to be merged before the 1.16 release (currently has a merge conflict).

In 1.16, go install will accepts arguments with version suffixes (`go install pkg@version`). The [CL adding the relevant doc](https://go-review.googlesource.com/c/website/+/285452) will need to be merged before the 1.16 release (currently has a merge conflict, and unresolved comments).

Filing an issue just to be sure this is on someone's radar.

cc @dmitshur @bcmills

**Comment by dmitshur** [comment]
Thanks. If I understand correctly, @jayconrod is planning to submit that CL stack as part of the Go 1.16 release, and we will coordinate the timing as needed. The merge conflict is because it’s a CL in the middle of a stack, I don’t think it’s a problem. The comments will need to be addressed.

Also CC @rsc, @stevetraut as FYI.

**Comment by ALTree** [comment]
Great! Thanks for confirming. I was trying to find documentation for the new `retract` directive and I was somewhat surprised I could find any in `tip.golang.org`. But I guess with the new `x/website` setup website changes will get committed at the very last moment from now on(?)...

**Comment by dmitshur** [comment]
For Go 1.16, yes, but that isn't a great experience and we'll look about improving it in the future (perhaps with a branch, or something else).

**Comment by dmitshur** [comment]
I left a [comment](https://go-review.googlesource.com/c/website/+/284812/2#message-e25b50802019ecb160605484bd532c2efa186dea) on CL 284812, the first unmerged CL in that stack, noting that it's safe to start landing it now. CC @jayconrod.

**Comment by ALTree** [comment]
Fixed by merging the aforementioned CL stack.
