### ISSUE TITLE
x/tools/gopls: gopls.add_dependency workspace edits not working?

### ISSUE THREAD

**Issue by myitcv** [golang/go#44247]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +e9c9683597 Tue Feb 9 18:40:13 2021 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.1.1-0.20210204180613-842a9283d6c6
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.0.0-20210204180613-842a9283d6c6
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/myitcv/gostuff/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel +e9c9683597 Tue Feb 9 18:40:13 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build474152825=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

This is a follow up to #44035. Thanks very much @heschik for addressing that issue in golang/tools@706a59c.

I've just tried this out, but I'm still not seeing workspace edits for `go.mod`. Given your change had test coverage, I suspect this is a configuration issue of some sort but I can't see what that might be.

I started with the same setup as before:

```
-- go.mod --
module example.com/repro

go 1.16
-- main.go --
package main

import (
	"fmt"

	_ "golang.org/x/tools/imports"
)

func main() {
	fmt.Println("hello, world!")
}
```

i.e. the requirement on `golang.org/x/tools/imports` is missing from `go.{mod,sum}`.

Loading `main.go` in Vim (using `govim`) gives error diagnostics as expected:

```
main.go|6 col 4| could not import golang.org/x/tools/imports (no required module provides package "golang.org/x/tools/imports")
main.go|6 col 4| golang.org/x/tools is not in your go.mod file
```

If we ask for suggested fixes at `main.go:6` we get a code action response with the `gopls.add_dependency` command.

If we execute the `gopls.add_dependency` command, `go.{mod,sum}` change beneath the editor and `gopls`, i.e. we don't see any workspace edits, despite the changes in golang/tools@706a59c.

Log files:

* [gopls.log](https://github.com/golang/go/files/5975233/gopls.log)
* [govim.log](https://github.com/golang/go/files/5975234/govim.log)

Is there something we (`govim`) are not doing right here?

As a side note, I suspect the `tempModfile` option is no longer valid given that we have `allowModfileModifications`? Because I initially had `tempModfile: true` and this resulted in the error message:

```
-modfile is unsupported for this Go version
```

But I can raise this as a separate issue if needs be.

### What did you expect to see?

`gopls.add_dependency` resulting in workspace edits for `go.{mod,sum}`.

### What did you see instead?

The files changing beneath the editor, and that change getting detected by the `govim` file watcher

---

cc @stamblerre @heschik 

FYI @leitzler

**Comment by heschik** [comment]
Sending workspace edits for a closed file causes VSCode to open it and leave the edits unsaved, which is undesirable, particularly for go.sum. To avoid that, gopls still directly edits closed files. You should see workspace edits if you open go.mod first.

**Comment by leitzler** [comment]
I did try out Pauls example (using the defaults; `tempModFile: true` / `allowModfileModifications: false`) according to:

1. Open `main.go`
2. Apply the suggested fix, i.e. calling execute for the provided `gopls.go_get_package`:

```
[Trace - 23:56:03.030 PM] Sending request 'workspace/executeCommand - (5)'.
Params: {"command":"gopls.go_get_package","arguments":[{"URI":"file:///private/var/folders/j4/l2j99h6d5qd6knjlllql0bb80000gn/T/tmp.7WMpQpFw/main.go","Pkg":"
golang.org/x/tools/imports","AddRequire":true}]}
```

3. Send `didChangeWatchedFiles` for `go.mod` and `go.sum` as the file watcher detects the updates:

```
[Trace - 23:56:04.156 PM] Sending notification 'workspace/didChangeWatchedFiles'.
Params: {"changes":[{"uri":"file:///private/var/folders/j4/l2j99h6d5qd6knjlllql0bb80000gn/T/tmp.7WMpQpFw/go.mod","type":2}]}


[Trace - 23:56:04.157 PM] Sending notification 'workspace/didChangeWatchedFiles'.
Params: {"changes":[{"uri":"file:///private/var/folders/j4/l2j99h6d5qd6knjlllql0bb80000gn/T/tmp.7WMpQpFw/go.sum","type":1}]}
```



Then I get a couple of other `go.sum` diagnostics back for both `main.go` and `go.mod`:
```
[Trace - 23:56:04.805 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///private/var/folders/j4/l2j99h6d5qd6knjlllql0bb80000gn/T/tmp.7WMpQpFw/main.go","version":1,"diagnostics":[{"range":{"start":{"line":5
,"character":1},"end":{"line":5,"character":31}},"severity":1,"source":"compiler","message":"error while importing golang.org/x/tools/imports: missing go.su
m entry for module providing package golang.org/x/mod/module (imported by golang.org/x/tools/internal/imports); to add:\n\tgo get golang.org/x/tools/interna
l/imports@v0.1.0"},{"range":{"start":{"line":5,"character":1},"end":{"line":5,"character":31}},"severity":1,"source":"compiler","message":"error while impor
ting golang.org/x/tools/imports: missing go.sum entry for module providing package golang.org/x/mod/semver (imported by golang.org/x/tools/internal/gocomman
d); to add:\n\tgo get golang.org/x/tools/internal/gocommand@v0.1.0"},{"range":{"start":{"line":5,"character":1},"end":{"line":5,"character":31}},"severity":
1,"source":"compiler","message":"error while importing golang.org/x/tools/imports: missing go.sum entry for module providing package golang.org/x/sys/execab
s (imported by golang.org/x/tools/internal/gocommand); to add:\n\tgo get golang.org/x/tools/internal/gocommand@v0.1.0"}]}


[Trace - 23:56:04.805 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///private/var/folders/j4/l2j99h6d5qd6knjlllql0bb80000gn/T/tmp.7WMpQpFw/go.mod","diagnostics":[{"range":{"start":{"line":4,"character":
0},"end":{"line":4,"character":33}},"severity":1,"source":"compiler","message":"error while importing golang.org/x/tools/internal/gocommand: missing go.sum
entry for module providing package golang.org/x/mod/semver (imported by golang.org/x/tools/internal/gocommand); to add:\n\tgo get golang.org/x/tools/interna
l/gocommand@v0.1.0"},{"range":{"start":{"line":4,"character":0},"end":{"line":4,"character":33}},"severity":1,"source":"compiler","message":"error while imp
orting golang.org/x/tools/internal/gocommand: missing go.sum entry for module providing package golang.org/x/mod/semver (imported by golang.org/x/tools/inte
rnal/gocommand); to add:\n\tgo get golang.org/x/tools/internal/gocommand@v0.1.0"},{"range":{"start":{"line":4,"character":0},"end":{"line":4,"character":33}
},"severity":1,"source":"compiler","message":"error while importing golang.org/x/tools/internal/gocommand: missing go.sum entry for module providing package
 golang.org/x/sys/execabs (imported by golang.org/x/tools/internal/gocommand); to add:\n\tgo get golang.org/x/tools/internal/gocommand@v0.1.0"},{"range":{"s
tart":{"line":4,"character":0},"end":{"line":4,"character":33}},"severity":1,"source":"compiler","message":"error while importing golang.org/x/tools/interna
l/gocommand: missing go.sum entry for module providing package golang.org/x/sys/execabs (imported by golang.org/x/tools/internal/gocommand); to add:\n\tgo g
et golang.org/x/tools/internal/gocommand@v0.1.0"},{"range":{"start":{"line":4,"character":0},"end":{"line":4,"character":33}},"severity":1,"source":"compile
r","message":"error while importing golang.org/x/tools/internal/imports: missing go.sum entry for module providing package golang.org/x/mod/module (imported
 by golang.org/x/tools/internal/imports); to add:\n\tgo get golang.org/x/tools/internal/imports@v0.1.0"},{"range":{"start":{"line":4,"character":0},"end":{"
line":4,"character":33}},"severity":1,"source":"compiler","message":"error while importing golang.org/x/tools/internal/imports: missing go.sum entry for mod
ule providing package golang.org/x/mod/module (imported by golang.org/x/tools/internal/imports); to add:\n\tgo get golang.org/x/tools/internal/imports@v0.1.
0"}]}
```

Is there something I'm missing out? (full log at https://gist.github.com/leitzler/d189c42bdb0dae8562682b47325938e2).

**Comment by leitzler** [comment]
Just to add to the above, I expected that applying the suggested fix would have the ~same effect as running `go get golang.org/x/tools v0.1.0` *before* I open `main.go`.

If I do run `go get` before, then I only get one diagnostic (warning) telling me that the require line should be direct (ideally `gopls` would fix that as well executing `gopls.go_get_package`).

**Comment by heschik** [comment]
@leitzler: I don't see how your problem is related to workspace edits, but it is a real (and rather embarrassing) mistake on my part, so I'll file a new bug. Thanks for the report.

**Comment by leitzler** [comment]
Thank you and apologies for the issue hijacking. Didn't see that it was unrelated.

**Comment by stamblerre** [comment]
That issue was https://github.com/golang/go/issues/44307, and it is now resolved. Can we close this?

**Comment by myitcv** [comment]
Yes, this can be closed.
