### ISSUE TITLE
cmd/link: LLVM's LLD does not create working Windows executables

### ISSUE THREAD

**Issue by zx2c4** [golang/go#44250]
I'm still uncertain whether we're missing a config option for LLD to get the behavior we want, or if this is a bug in LLD. I've filed this with LLVM: https://bugs.llvm.org/show_bug.cgi?id=49172

It looks like all of the go object is being merged into one readable/executable section, which then crashes on writes to data. I haven't figured out why yet.

Fixing this is an important step in getting cgo rolling with arm and arm64 on Windows, since there's no working binutils there.

Affects #38755, #36439, #43800.

CC @rsc @alexbrainman @cherrymui @mstorsjo

**Comment by thanm** [comment]
Related: #39326.  For that bug, the musl.cc clang compilers are being used.

**Comment by zx2c4** [comment]
Musl.cc uses gcc/binutils, not clang, and doesn't support arm or arm64 consequently.

**Comment by thanm** [comment]
Whoops, yes, you are right.  Same symptom however (use of lld results in non-working executable).

**Comment by zx2c4** [comment]
I've got a working fix now -- https://golang.org/cl/291630 . This should clear the way for doing cgo on windows/arm{64}.
