### ISSUE TITLE
bufio: SplitFunc documentation does not document ErrFinalToken

### ISSUE THREAD

**Issue by JensRantil** [golang/go#44261]
### What did you do?

I went to https://golang.org/pkg/bufio/#SplitFunc and read the documentation to implement a `SplitFunc`. In my implementation of a `SplitFunc`, for the case of atEOF, I simply returned `len(data), data, nil` thinking the `Scanner` would stop calling my function. It didn't (I was getting `panic: bufio.Scan: too many empty tokens without progressing`). I went back and looked at the "EmptyFinalToken" example [here](https://golang.org/pkg/bufio/#Scanner). It refered to [`ErrFinalToken`](https://golang.org/pkg/bufio/#ErrBadReadCount:~:text=var%20ErrFinalToken%20%3D%20errors.New(%22final%20token%22)) which I was surprised to see since it wasn't mentioned in [the `SplitFunc` documentation](https://golang.org/pkg/bufio/#SplitFunc).

### What did you expect to see?

I'd expect [the `SplitFunc` documentation](https://golang.org/pkg/bufio/#SplitFunc) to include a reference to [`ErrFinalToken`](https://golang.org/pkg/bufio/#ErrBadReadCount:~:text=var%20ErrFinalToken%20%3D%20errors.New(%22final%20token%22)).

### What did you see instead?

No reference to it at all.

**Comment by adesokanayo** [comment]
Suppose all that needs to be done here is to mention ErrFinalToken in the documentation for SplitFunc. I can do that if that is the case @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Yes, most likely one additional sentence would be appropriate in the docs for SplitFunc.  Thanks.
