### ISSUE TITLE
cmd/go: go command rejects references to .tbd files

### ISSUE THREAD

**Issue by kevinAlbs** [golang/go#44263]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.8 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kevin.albertson/Library/Caches/go-build"
GOENV="/Users/kevin.albertson/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/kevin.albertson/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/kevin.albertson/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pv/p1jss0l97mq0ddr7rjbcbdt00000gp/T/go-build829854566=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I am using cgo to link to a dylib with pkg-config.

```
$ brew install dlib
$ pkg-config --cflags --libs dlib-1
-I/usr/local/Cellar/dlib/19.21/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -L/usr/local/Cellar/dlib/19.21/lib -ldlib /usr/local/lib/libpng.dylib /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libz.tbd /usr/local/lib/libjpeg.dylib /usr/local/opt/openblas/lib/libopenblas.dylib /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libsqlite3.tbd
```

My cgo program attempts to link to it as follows:
```
// dlib.go
package dlib

// #cgo pkg-config: dlib-1
import "C"
```

The linker inputs `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libz.tbd ` `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libsqlite3.tbd` are rejected:

```
$ go build -o dlib dlib.go
go build command-line-arguments: invalid flag in pkg-config --libs: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libz.tbd
``` 

The dylib specifies a dependency on a `.tbd` file, which is a macOS [text based stub-library](https://developer.apple.com/forums/thread/4572?answerId=9366022#9366022), and describes the interface to a dylib or framework. I can work around this by specifying the environment variable `CGO_LDFLAGS_ALLOW='^.*tbd$'`.

Since it is a valid input to the linker, I think the allow-list for linker flags could add `tbd` to the list of [permitted direct inputs](https://github.com/golang/go/blob/33d72fd4122a4b7e31e738d5d9283093966ec14a/src/cmd/go/internal/work/security.go#L211). If that sounds reasonable, I'd be more than happy to submit a PR with a test.

**Comment by ianlancetaylor** [comment]
The file to fix is cmd/go/internal/work/security.go.
