### ISSUE TITLE
x/tools/gopls: unnecessary autocomplete of int() cast inside array index

### ISSUE THREAD

**Issue by evanw** [golang/go#44268]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

I'm on the latest version of the Go VSCode extension (0.22.1) which from what I understand is now using gopls.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/evan/Library/Caches/go-build"
GOENV="/Users/evan/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/evan/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/evan/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/j6/np400cw17sz0n5ljd67byrzw0000gn/T/go-build549777181=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

The automatic cast insertion in VSCode inserts unnecessary `int()` casts inside array index expressions:

<img width="413" src="https://user-images.githubusercontent.com/406394/107923912-000a1300-6f27-11eb-884a-565c310104a1.gif">

I keep having to delete these automatically inserted casts after autocompleting. While they don't alter the semantics of the code, they are visually noisy and I would prefer to not have them.

### What did you expect to see?

I would expect autocomplete to not insert explicit casts wherever the language supports implicit casts.

### What did you see instead?

It looks like the autocomplete feature of gopls always inserts explicit casts even when they are unnecessary.

**Comment by stamblerre** [comment]
Confirmed that this is fixed at master, and it will be part of the v0.6.6 release today.
