### ISSUE TITLE
Bug in time.Format

### ISSUE THREAD

**Issue by mipnw** [golang/go#44277]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

I have not tried 1.15.8

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

</pre></details>

### What did you do?

```
package main

import "time"

func main() {
	now := time.Now()
	println(now.Format("2001-01-01"))
	println(now.Format("2006-01-01"))
}
```

then
`go run main.go`

### What did you expect to see?
```
2021-02-15
2021-02-15
```

### What did you see instead?
```
15002-02-02
2021-02-15
```

**Comment by mdlayher** [comment]
This is not a bug, please read the documentation and examples at https://golang.org/pkg/time/#Time.Format.

**Comment by jolheiser** [comment]
Per https://golang.org/src/time/format.go

`2006-01-01` is converted like so: 
`2006` -> `2021`
`01` -> `02`
`01` -> `02`

My best guess for `2001-01-01` is:
`2 0 01` -> `15 (literal 0) 02`
`01` -> `02`
`01` -> `02`

e.g. there is no formatting layout for `2001`, however there are some matching sub-patterns `2` and `01`

**Comment by mipnw** [comment]
I've read  [https://golang.org/pkg/time/#Time.Format](https://golang.org/pkg/time/#Time.Format). It says "Format returns a textual representation of the time value formatted according to layout, which defines the format by showing how the reference time, defined to be would be displayed if it were the value; it serves as an example of the desired output."

The layout "2001-01-01" is an example of a desired YYYY-MM-DD output. What else is it an example of? 

The given explanation of "2006"->"2021" but "2001"->"15002" is not clear. Why? How is 2001 an example of year 15002? That part is nowhere to be seen in the documentation. That explanation be valid if the documentation did not say the layout can be "an example" but instead said the layout must be in accordance with some codes that explicitly define intent. Either the this layout is codified (e.g. 1 means day of week, 2 means year etc...), or it's an example (2001 means a 4 digit year).
  
Also YYYY-MM-DD happens to be one of several ISO-8601 formats. Is there an included format that yields exactly YYYY-MM-DD?

**Comment by seankhliao** [comment]
For questions please refer to https://github.com/golang/go/wiki/Questions
