### ISSUE TITLE
runtime/metrics: docs reference nonexistent names and removed features

### ISSUE THREAD

**Issue by zephyrtronium** [golang/go#44280]
The docs on `Sample` specify that the `Name` field must be set to a description returned by `Descriptions`. I believe this should refer to `All` instead, because there is no identifier named `Descriptions` in package metrics.

https://github.com/golang/go/blob/0cb3415154ff354b42db1d65073e9be71abcc970/src/runtime/metrics/sample.go#L13-L18

Additionally, the package-level documentation mentions that `Description` values describe "how difficult or disruptive it is to obtain," but this information appears to have been removed in 8f6a9acbb3f63a77175eaa153cace5f3b6d611b2 to save for the future. The only information of the style the documentation describes is whether a metric is cumulative.

https://github.com/golang/go/blob/0cb3415154ff354b42db1d65073e9be71abcc970/src/runtime/metrics/doc.go#L16-L21

**Comment by dmitshur** [comment]
CC @mknyszek.
