### ISSUE TITLE
crypto/x509: rewrite the parser to use x/crypto/cryptobyte

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#44299]
A x/crypto/cryptobyte parser has two advantages over an encoding/asn1 based parser: significant performance improvement due to avoiding reflection, and a much stricter profile/narrower security surface by only needing to support the X.509 profile rather than supporting all of the generic ASN.1 features.

https://go-review.googlesource.com/c/go/+/274234 contains a WIP rewrite which shows around 65% performance improvement and 70% reduction in memory allocations when parsing a typical web PKI certificate.

**Comment by rolandshoemaker** [comment]
Improving the performance of the parser could also address #35504, and if not exposing the cryptobyte based SAN parser to the tls package wcould also be a viable solution.

**Comment by ianlancetaylor** [comment]
Is this going to happen for 1.17?  Thanks.

**Comment by neild** [comment]
This appears to have been completed in [CL 274234](https://golang.org/cl/274234).
