### ISSUE TITLE
cmd/go: `go list -m --versions` behaves differently with retracted versions depending on the presence of `@latest`

### ISSUE THREAD

**Issue by hyangah** [golang/go#44296]
go version: 1.16rc1

```
$ cat go.mod
module f

go 1.16
```
The contents of `go.mod` don't change. I emptied the module cache before each command below.
The module I am querying here has v1.0.0 and v1.0.1, and both were retracted.

```
$ GOPROXY=direct GOSUMDB=off go  list -m -json  github.com/hyangah/retracttest/a
go list -m: module github.com/hyangah/retracttest/a: not a known dependency
```
vs.
```
$ GOPROXY=direct GOSUMDB=off go  list -m -json  github.com/hyangah/retracttest/a@latest
{
        "Path": "github.com/hyangah/retracttest/a",
        "Version": "v0.0.0-20201117044135-c0d2dc84e45f",
        "Time": "2020-11-17T04:41:35Z",
        "GoVersion": "1.15"
}
```

With `--versions`:
```
$ GOPROXY=direct GOSUMDB=off go  list -m -json --versions github.com/hyangah/retracttest/a
{
        "Path": "github.com/hyangah/retracttest/a",
        "Version": "v1.0.1",
        "Time": "2020-11-16T22:37:32Z",
        "GoVersion": "1.15"
}
```
vs.
```
$ GOPROXY=direct GOSUMDB=off go  list -m -json --versions github.com/hyangah/retracttest/a@latest
{
        "Path": "github.com/hyangah/retracttest/a",
        "Version": "v0.0.0-20201117044135-c0d2dc84e45f",
        "Time": "2020-11-17T04:41:35Z",
        "GoVersion": "1.15"
}
```

cc @jayconrod

**Comment by hyangah** [comment]
The first case is WAI according to @bcmills because the main module doesn't have the dependency.
The second case is also WAI because it's querying the origin.

**Comment by bcmills** [comment]
I can reproduce the `--versions` behavior in a clean module, so that's almost certainly a bug.

**Comment by bcmills** [comment]
I happened to be poking around in the `list` implementation for lazy loading today, and noticed this codepath:
https://github.com/golang/go/blob/0e85fd7561de869add933801c531bf25dee9561c/src/cmd/go/internal/modload/list.go#L134-L151

I think that extra call to `Query` for `listVersions` is just wrong. I'm going to fix this so that I don't have to port the wrongness forward for lazy loading. 😁
