### ISSUE TITLE
all: Go 1.16 release status

### ISSUE THREAD

**Issue by toothrot** [golang/go#44292]
Issue tracking the go1.16 release by releasebot.

**Comment by toothrot** [comment]
## Log

    2021/02/16 12:33:25 starting
    2021/02/16 12:33:25 working in /usr/local/google/home/rakoczy/go-releasebot-work/go1.16
    2021/02/16 12:33:25 $ git clone https://go.googlesource.com/go /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gitmirror
    2021/02/16 12:33:45 $ git config gc.auto 0
    2021/02/16 12:33:45 $ git fetch origin release-branch.go1.16
    2021/02/16 12:33:46 $ git clone --reference /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gitmirror -b release-branch.go1.16 https://go.googlesource.com/go /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gitwork
    2021/02/16 12:33:47 $ git codereview change relwork
    2021/02/16 12:33:47 $ git config gc.auto 0
    2021/02/16 12:33:48 an associated security release branch "release-branch.go1.16-security" does not exist; assuming it has been merged and deleted, so proceeding as usual
    2021/02/16 12:33:48 $ git rev-parse go1.16
    2021/02/16 12:33:48 Release status issue title: "all: Go 1.16 release status"
    2021/02/16 12:33:50 Release status issue: https://golang.org/issue/44292
    2021/02/16 12:33:50 $ git add VERSION
    2021/02/16 12:33:50 $ git commit -m go1.16
    
    Change-Id: I4c1350e0cb74ebfde5832973979e02997476d16c
     VERSION
    2021/02/16 12:33:50 $ git codereview mail -trybot
    2021/02/16 12:33:59 $ go get golang.org/x/build/cmd/release
    2021/02/16 12:35:15 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target src -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/da8436ded7e0e8464c8e164816f5a7bd0f4ab558_725781427 -rev da8436ded7e0e8464c8e164816f5a7bd0f4ab558
    2021/02/16 12:35:15 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target linux-386 -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/da8436ded7e0e8464c8e164816f5a7bd0f4ab558_725781427 -rev da8436ded7e0e8464c8e164816f5a7bd0f4ab558
    2021/02/16 12:35:15 skipping test-only target linux-amd64-longtest because of -skip-test="linux-amd64-longtest" flag
    2021/02/16 12:35:15 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target windows-amd64-longtest -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/da8436ded7e0e8464c8e164816f5a7bd0f4ab558_725781427 -rev da8436ded7e0e8464c8e164816f5a7bd0f4ab558
    2021/02/16 12:35:15 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target linux-amd64 -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/da8436ded7e0e8464c8e164816f5a7bd0f4ab558_725781427 -rev da8436ded7e0e8464c8e164816f5a7bd0f4ab558
    2021/02/16 12:35:15 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target linux-ppc64le -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/da8436ded7e0e8464c8e164816f5a7bd0f4ab558_725781427 -rev da8436ded7e0e8464c8e164816f5a7bd0f4ab558
    2021/02/16 12:35:15 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target darwin-arm64 -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/da8436ded7e0e8464c8e164816f5a7bd0f4ab558_725781427 -rev da8436ded7e0e8464c8e164816f5a7bd0f4ab558
    2021/02/16 12:35:15 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target windows-386 -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/da8436ded7e0e8464c8e164816f5a7bd0f4ab558_725781427 -rev da8436ded7e0e8464c8e164816f5a7bd0f4ab558
    2021/02/16 12:35:15 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target windows-amd64 -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/da8436ded7e0e8464c8e164816f5a7bd0f4ab558_725781427 -rev da8436ded7e0e8464c8e164816f5a7bd0f4ab558
    2021/02/16 12:35:15 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target linux-armv6l -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/da8436ded7e0e8464c8e164816f5a7bd0f4ab558_725781427 -rev da8436ded7e0e8464c8e164816f5a7bd0f4ab558
    2021/02/16 12:35:15 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target linux-s390x -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/da8436ded7e0e8464c8e164816f5a7bd0f4ab558_725781427 -rev da8436ded7e0e8464c8e164816f5a7bd0f4ab558
    2021/02/16 12:35:15 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target darwin-amd64 -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/da8436ded7e0e8464c8e164816f5a7bd0f4ab558_725781427 -rev da8436ded7e0e8464c8e164816f5a7bd0f4ab558
    2021/02/16 12:35:15 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target freebsd-386 -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/da8436ded7e0e8464c8e164816f5a7bd0f4ab558_725781427 -rev da8436ded7e0e8464c8e164816f5a7bd0f4ab558
    2021/02/16 12:35:15 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target linux-arm64 -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/da8436ded7e0e8464c8e164816f5a7bd0f4ab558_725781427 -rev da8436ded7e0e8464c8e164816f5a7bd0f4ab558
    2021/02/16 12:35:15 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target freebsd-amd64 -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/da8436ded7e0e8464c8e164816f5a7bd0f4ab558_725781427 -rev da8436ded7e0e8464c8e164816f5a7bd0f4ab558
    2021/02/16 13:03:26 
    
    The prepare stage has completed.
    
    Please review and submit https://go-review.googlesource.com/q/I4c1350e0cb74ebfde5832973979e02997476d16c
    and then run the release stage.

**Comment by toothrot** [comment]
## Latest build: go1\.16

- src ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.16/go1.16.src.tar.gz))
- linux\-386 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.16/go1.16.linux-386.tar.gz))
- linux\-armv6l ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.16/go1.16.linux-armv6l.tar.gz))
- linux\-amd64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.16/go1.16.linux-amd64.tar.gz))
- linux\-arm64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.16/go1.16.linux-arm64.tar.gz))
- freebsd\-386 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.16/go1.16.freebsd-386.tar.gz))
- freebsd\-amd64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.16/go1.16.freebsd-amd64.tar.gz))
- windows\-386 ([zip](https://golang-release-staging.storage.googleapis.com/go1.16/go1.16.windows-386.zip)) ([msi](https://golang-release-staging.storage.googleapis.com/go1.16/go1.16.windows-386.msi))
- windows\-amd64 ([zip](https://golang-release-staging.storage.googleapis.com/go1.16/go1.16.windows-amd64.zip)) ([msi](https://golang-release-staging.storage.googleapis.com/go1.16/go1.16.windows-amd64.msi))
- darwin\-amd64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.16/go1.16.darwin-amd64.tar.gz))
- darwin\-arm64 ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.16/go1.16.darwin-arm64.tar.gz))
- linux\-s390x ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.16/go1.16.linux-s390x.tar.gz))
- linux\-ppc64le ([tar\.gz](https://golang-release-staging.storage.googleapis.com/go1.16/go1.16.linux-ppc64le.tar.gz))
- linux\-amd64\-longtest (test only) - not built
  - skipped because of -skip-test="linux-amd64-longtest" flag
- windows\-amd64\-longtest (test only) - ok

## Log

    2021/02/16 13:10:30 starting
    2021/02/16 13:10:30 working in /usr/local/google/home/rakoczy/go-releasebot-work/go1.16
    2021/02/16 13:10:30 $ git fetch origin master
    2021/02/16 13:10:31 $ git fetch origin release-branch.go1.16
    2021/02/16 13:10:32 $ git clone --reference /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gitmirror -b release-branch.go1.16 https://go.googlesource.com/go /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gitwork
    2021/02/16 13:10:33 $ git codereview change relwork
    2021/02/16 13:10:34 $ git config gc.auto 0
    2021/02/16 13:10:34 an associated security release branch "release-branch.go1.16-security" does not exist; assuming it has been merged and deleted, so proceeding as usual
    2021/02/16 13:10:34 Release status issue title: "all: Go 1.16 release status"
    2021/02/16 13:10:34 Release status issue: https://golang.org/issue/44292
    2021/02/16 13:10:34 $ git rev-parse go1.16
    2021/02/16 13:10:39 $ git tag go1.16 f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8
    2021/02/16 13:10:39 $ git push origin go1.16
    2021/02/16 13:10:43 $ go get golang.org/x/build/cmd/release
    2021/02/16 13:11:48 skipping test-only target linux-amd64-longtest because of -skip-test="linux-amd64-longtest" flag
    2021/02/16 13:11:48 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target linux-arm64 -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8_190133433 -rev f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8 -skip_tests
    2021/02/16 13:11:48 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target linux-386 -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8_190133433 -rev f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8 -skip_tests
    2021/02/16 13:11:48 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target src -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8_190133433 -rev f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8 -skip_tests
    2021/02/16 13:11:48 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target freebsd-amd64 -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8_190133433 -rev f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8 -skip_tests
    2021/02/16 13:11:48 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target linux-ppc64le -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8_190133433 -rev f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8 -skip_tests
    2021/02/16 13:11:48 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target linux-amd64 -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8_190133433 -rev f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8 -skip_tests
    2021/02/16 13:11:48 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target windows-386 -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8_190133433 -rev f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8 -skip_tests
    2021/02/16 13:11:48 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target darwin-amd64 -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8_190133433 -rev f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8 -skip_tests
    2021/02/16 13:11:48 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target windows-amd64 -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8_190133433 -rev f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8 -skip_tests
    2021/02/16 13:11:48 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target windows-amd64-longtest -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8_190133433 -rev f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8 -skip_tests
    2021/02/16 13:11:48 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target freebsd-386 -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8_190133433 -rev f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8 -skip_tests
    2021/02/16 13:11:48 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target linux-armv6l -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8_190133433 -rev f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8 -skip_tests
    2021/02/16 13:11:48 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target darwin-arm64 -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8_190133433 -rev f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8 -skip_tests
    2021/02/16 13:11:48 $ /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/gopath/bin/release -target linux-s390x -user go-dev -version go1.16 -staging_dir /usr/local/google/home/rakoczy/go-releasebot-work/go1.16/release-staging/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8_190133433 -rev f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8 -skip_tests
    2021/02/16 13:24:17 changing milestone of issue 44249 to Go1.17
    2021/02/16 13:24:17 closing milestone Go1.16
    2021/02/16 13:24:18 
    
    The release stage has completed. Thanks for riding with releasebot today!
    
    Please refer to the playbook for the next steps.

**Comment by circa10a** [comment]
@toothrot Do you know when https://go.googlesource.com/tools.git/+refs gets updated with a 1.16 version?

**Comment by zikaeroh** [comment]
@circa10a You may be interested in #36882 (and linked issues); I don't think those branches are intended for use by anyone other than the Go team for specific purposes and shouldn't be depended on externally.

**Comment by circa10a** [comment]
Ah ok,  I was asking because I made a PR to bump the homebrew formula and their CI requires that to be present: https://github.com/Homebrew/homebrew-core/pull/71289

**Comment by zikaeroh** [comment]
That's the case laid out in https://github.com/golang/go/issues/36882#issuecomment-712831596, yeah. I'll defer to an actual Go team member, clearly (IDK if the policy actually changed given #36882 is open), I just recalled that thread existing. 🙂

**Comment by toothrot** [comment]
Similar to what @zikaeroh helpfully said, the canonical x/repo version info for a Go release is contained in the appropriate `go.mod` files in the Go repo. These branches are for helping us manage backports and security fixes for code vendored into Go, which is why they are named using an `internal` pattern, as pointed out in #36882 and #36842. 

I'm not sure what the tools repository is used for in homebrew, but the versioning strategy should probably be discussed somewhere listed here: http://golang.org/wiki/Questions.
