### ISSUE TITLE
doc: Broken image in readme

### ISSUE THREAD

**Issue by bobrik** [golang/go#44295]
### The issue

Commit 0cb3415154ff354b42db1d65073e9be71abcc970 by @rsc removed `doc/gopher/fiveyears.jpg`, which is referenced in README.md.

### What did you expect to see?

![image](https://user-images.githubusercontent.com/89186/108101520-31c0ce00-703c-11eb-861a-617210352029.png)

### What did you see instead?

![image](https://user-images.githubusercontent.com/89186/108101486-2372b200-703c-11eb-965b-b3a44fb2ca12.png)

**Comment by dmitshur** [comment]
@gopherbot Please backport this to Go 1.16. It is a safe documentation fix needed to restore the gopher image at https://pkg.go.dev/std#section-readme (and any other place that displays the README of the Go standard library at release tags).
