### ISSUE TITLE
path.Dir() does not work on Windows

### ISSUE THREAD

**Issue by kylhuk** [golang/go#44302]
### What version of Go are you using (`go version`)?
1.15.8

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
Windows 10 (20H2), amd64

### What did you do?
Use `path.Dir()` to get the path of a file.

### What did you expect to see?
The documentation suggests, that `path.Dir()` "returns all but the last element of path, typically the path's directory." [Source](https://pkg.go.dev/path#Dir)

### What did you see instead?
The function returned `.`

### Additional Info
This was mentioned in #28167 before, but was closed because of a work around. This was not a proper fix.

There are two possible solutions:
1. Either fix the documentation (easier) or 
2. the code.

`path.Dir()` as of now gives the user the suggestion, that this function is working on all paths, on all operating systems.

**Comment by slrz** [comment]
Use the `path/filepath` package to deal with the local machine's file system paths. The `path` package is for slash-separated paths like those found in URLs (e.g. `/golang/go/issues/44302`).

**Comment by kylhuk** [comment]
@slrz: You are actually right. The documentation is in the package documentation and not in the function documentation. Quote from `path`: "Package path implements utility routines for manipulating slash-separated paths.

The path package should only be used for paths separated by forward slashes, such as the paths in URLs. This package does not deal with Windows paths with drive letters or backslashes; to manipulate operating system paths, use the path/filepath package."

So thanks for pointing that out. I'll close this issue.
