### ISSUE TITLE
x/pkgsite: does not respect retract statements (formerly, proxy.golang.org: @v/list can become stale)

### ISSUE THREAD

**Issue by zx2c4** [golang/go#44306]
Here's an example of everything working as planned:

```
$ curl -s https://proxy.golang.org/golang.org/x/text/@latest | jq -r .Version
v0.3.5
$ curl -s https://proxy.golang.org/golang.org/x/text/@v/list | sort -Vr | head -n 1
v0.3.5
```

Here's an example of things not going as planned:

```
$ curl -s https://proxy.golang.org/golang.zx2c4.com/wireguard/@latest | jq -r .Version
v0.0.0-20210216200525-4e439ea10e32
$ curl -s https://proxy.golang.org/golang.zx2c4.com/wireguard/@v/list | sort -Vr | head -n 1
v0.0.20201118
```

In the first example `@latest==max(@v/list)` but in the second example `@latest!=max(@v/list)`. How could this be? Because I've removed all tags from my repository. I did this because tagging versions didn't make sense for it (just as it doesn't make sense for x/sys, while it does make sense for x/text). The intended effect was that `go get ...` would then give people the latest commit, rather than the latest tag. Unfortunately, due to the above weirdness, it gives people an old no longer existing tag.

The solution here is for `@v/list` to stop displaying removed tags. Note that that is different from removing old zips -- by all means, keep old zips so that people's dependencies don't break -- but `@v/list` should not display phantom tags.
CC @FiloSottile

**Comment by hyangah** [comment]
Please use the new [`retract` feature](https://golang.org/doc/go1.16#go-command) to remove undesirable versions. 

The list endpoint is supposed to return a list of all known versions. Since the proxy knew about `v0.0.20201118`, it's returning that. This is necessary to implement the `-retracted` flag.

**Comment by zx2c4** [comment]
The proxy should stop listing non-existent versions. Retract is further consequences than what this issue is about and not desirable here. This only concerns @v/list, not anything elsewhere.

**Comment by bcmills** [comment]
The version `v0.0.20201118` still exists in the abstract regardless of any change to the upstream tags: for example, its checksum won't disappear from the https://sum.golang.org database.

Extraneous versions in the `/@v/latest` endpoints should be mostly irrelevant to the `go` command. If you `retract` all of the versions in that list, then versions of the `go` command that support retraction (Go 1.16+) should fall back to the pseudo-version for the latest commit as you expect.

**Comment by zx2c4** [comment]
> The version v0.0.20201118 still exists in the abstract regardless of any change to the upstream tags: for example, its checksum won't disappear from the https://sum.golang.org database.

I'm not requesting that you stop serving `v0.0.20201118.zip`. What I'm asking is that `@v/list` stop serving stale information.

> Extraneous versions in the /@v/latest endpoints should be mostly irrelevant to the go command. If you retract all of the versions in that list, then versions of the go command that support retraction (Go 1.16+) should fall back to the pseudo-version for the latest commit as you expect.

This doesn't appear to be the case. So far as I can tell, it downloads the latest tag from `@v/list`, and since that old non-existent version doesn't have a retract statements, it doesn't see anything to retract.

**Comment by bcmills** [comment]
The `retract` directive does need to be in the semantically-highest listed version of the module, yes.

One way to make that work is to temporarily tag a higher version containing a `retract` directive that retracts both itself and the unwanted previous versions. Then `go mod download` that higher version via the proxy, so that it also becomes the highest tag in the proxy's list. Once that's done (and successfully ingested into the proxy), you can purge the erroneous tags so that users running with `GOPROXY=direct` won't bother checking the self-retracted version.

**Comment by zx2c4** [comment]
Thanks! That seemed to work indeed. @v/list still shows all the versions, but I guess it now downloads the bogus one I just pushed, and then removes itself as an acceptable candidate along with all the others an then does another download operation to @latest?

**Comment by bcmills** [comment]
Exactly — and that should work even if the user has other (private) proxies that are also still serving cached versions.

**Comment by zx2c4** [comment]
Couldn't you incorporate this step serverside, to remove entries from @v/list based on retract statement parsing, to prevent the extra downloads and latency and also sort of shoehorn pre-1.16 compatibility?

**Comment by bcmills** [comment]
In theory, yes — although that would cause Go 1.15 users to suddenly observe very different behavior, for which they may or may not be prepared.

Users upgrading from one Go release to another are generally at least somewhat prepared for changes in the tooling and underlying infrastructure, and can refer to the release notes to figure out what changed (especially if anything in their workflow breaks). OTOH, existing Go 1.15 users probably aren't expecting the behavior of `go` commands (even proxied ones) to suddenly change overnight.

**Comment by rsc** [comment]
It sounds like we can close this issue? We are not going to delete formerly published versions from the proxy storage, nor from the @v/list, which is how programs access that storage.

**Comment by zx2c4** [comment]
> The `retract` directive does need to be in the semantically-highest listed version of the module, yes.
> 
> One way to make that work is to temporarily tag a higher version containing a `retract` directive that retracts both itself and the unwanted previous versions. Then `go mod download` that higher version via the proxy, so that it also becomes the highest tag in the proxy's list. Once that's done (and successfully ingested into the proxy), you can purge the erroneous tags so that users running with `GOPROXY=direct` won't bother checking the self-retracted version.

Reopening this issue because this technique doesn't work on pkg.go.dev. Specifically, the highest-version logic still chooses the highest tag, despite the retract statements. While it might still make sense to serve retracted documentation when explicitly requested, the "default view" should certainly take into account the retract statements, so that it mirrors the actual API people are using with `go get`'d modules. CC @julieqiu

**Comment by hyangah** [comment]
pkgsite change to support retract is already tracked in https://github.com/golang/go/issues/43265 etc. So no need to reopen and change the subject of this issue.

**Comment by zx2c4** [comment]
Thanks, good to know.
