### ISSUE TITLE
`go install` fails for local source package

### ISSUE THREAD

**Issue by ronaldpetty** [golang/go#44315]
`go version go1.16 linux/amd64`

When running `go install` on 1.16 it no fails on a bare package (aka non-module). This may be correct, but its very unclear to me what is the recourse (even if the answer is "make it a module").

```
~/go/src/lab-program-construction$ pwd
/home/ubuntu/go/src/lab-program-construction
~/go/src/lab-program-construction$ cat program-construction.go 
package main

import "fmt"

func main() {
	fmt.Println("hello world")
}
~/go/src/lab-program-construction$ ls
program-construction.go
~/go/src/lab-program-construction$ go install
go: cannot find main module; see 'go help modules'
~/go/src/lab-program-construction$ go mod init
go: creating new go.mod: module lab-program-construction
go: to add module requirements and sums:
	go mod tidy
~/go/src/lab-program-construction$ ls
go.mod  program-construction.go
~/go/src/lab-program-construction$ go install
```

I have read https://github.com/golang/go/issues/40276 and will reread it, I hope the answer is in there, somewhere!

Any guidance appreciated.

**Comment by hyangah** [comment]
That is because module-aware mode is enabled by default since go1.16. 
See the 'Modules' section of https://golang.org/doc/go1.16#go-command.

**Comment by ronaldpetty** [comment]
@hyangah Thanks for that. I did see that before. I made a simple mistake. I did see that and tried to revert the behavior. My mistake was not 'exporting GO111MODULE=auto' just 'GO111MODULE=auto' is not enough.
