### ISSUE TITLE
io/ioutil: TempDir and TempFile don't mention new os alternatives

### ISSUE THREAD

**Issue by danp** [golang/go#44311]
With the 1.16 release, all the functions in io/ioutil reference a new alternative in the os package except for [TempDir](https://golang.org/pkg/io/ioutil/#TempDir) and [TempFile](https://golang.org/pkg/io/ioutil/#TempFile). This can make it easy to miss that [os.CreateTemp](https://golang.org/pkg/os/#CreateTemp) and [os.MkdirTemp](https://golang.org/pkg/os/#MkdirTemp) were added to replace them.

TempDir and TempFile should probably mention their new os alternatives.

**Comment by danp** [comment]
One way to fix this: have TempDir and TempFile call their new os alternatives and add a note to that effect, similar to [ReadAll](https://golang.org/pkg/io/ioutil/#ReadAll).

Looking at #42026 and https://golang.org/cl/266364, I'm not sure why TempDir and TempFile were not changed in that way when ReadAll and others were. If that would work, I'm happy to do that.

**Comment by ianlancetaylor** [comment]
https://golang.org/cl/285378 makes this change, but it didn't make it into the 1.16 release.
