### ISSUE TITLE
spec: Every type should have a method set which may be empty

### ISSUE THREAD

**Issue by DQNEO** [golang/go#44318]
# Problem

The spec says:

> A type may have a method set associated with it.

https://golang.org/ref/spec#Method_sets

This sentence implies it's possible that some types do not have a method set. 
A reader may wonder what's the difference between "a type with an empty method set" and "a type with no  method set".

I would like to propose a new sentence instead.

# Proposal

```diff
- A type may have a method set associated with it.
+ A type has a method set associated with it.
```

The new sentence would fit well the description about the empty interface:

> A type implements any interface comprising any subset of its methods and may therefore implement several distinct interfaces. For instance, all types implement the empty interface:
> interface{}

https://golang.org/ref/spec#Interface_types

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by griesemer** [comment]
Thanks for the suggestion.
