### ISSUE TITLE
GO 1.16 Program do not compile on raspberry pi

### ISSUE THREAD

**Issue by jpmieville** [golang/go#44320]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 linux/arm
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

$ go env
GO111MODULE=""
GOARCH="arm"
GOBIN=""
GOCACHE="/home/pi/.cache/go-build"
GOENV="/home/pi/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/pi/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
GOARM="6"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/pi/vaccin/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4049214872=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

go build my_program.go

### What did you expect to see?

to finish without compilation error. I compile the same program on Unbuntu without any problem

### What did you see instead?

\# runtime
/usr/local/go/src/runtime/mgcsweepbuf.go:87:80: memstats.gc_sys undefined (type mstats has no field or method gc_sys)
/usr/local/go/src/runtime/mgcsweepbuf.go:106:102: memstats.gc_sys undefined (type mstats has no field or method gc_sys)
/usr/local/go/src/runtime/stubs32.go:14:6: call16 redeclared in this block
	previous declaration at /usr/local/go/src/runtime/stubs.go:287:55

**Comment by davecheney** [comment]
This issue is often caused by a corrupt Go installation. Did you delete the previous version of go before unpacking 1.16?

**Comment by jpmieville** [comment]
I reinstalled Go 1.16 and it is working now. Thanks for the quick reply.

**Comment by davecheney** [comment]
@toothrot @dmitshur this class of error occurs after every point release. Do you think the installation instructions could be improved to highlight that previous installations should be removed first?

**Comment by dmitshur** [comment]
We can try, but we'll need to narrow down where the source of the problem was.

@jpmieville Which installation instructions did you follow when you ran into this issue? Was it https://golang.org/doc/install or somewhere else?

**Comment by agnivade** [comment]
It always happens if you don't remove the existing installation first before installing the new one. The installation page just mentions a single line

> If you have a previous version of Go installed, be sure to remove it before installing another.

I think it should be made part of the numbered list for better visibility so that users always go through it without fail.

**Comment by dmitshur** [comment]
Thank you for the feedback. I've filed #44426 about improving the Linux installation instructions.

**Comment by jpmieville** [comment]
> We can try, but we'll need to narrow down where the source of the problem was.
> 
> @jpmieville Which installation instructions did you follow when you ran into this issue? Was it https://golang.org/doc/install or somewhere else?

On my raspberry pi, I used the following shell script

#!/bin/bash
if [ -d "/usr/local/go/bin" ] ; then
	rm "/usr/local/go/bin"  
	echo "/usr/local/go/bin deleted"
fi
export GOLANG="$(curl https://golang.org/dl/|grep armv6l|grep -v beta|head -1|aw
k -F\> {'print $3'}|awk -F\< {'print $1'})"
echo "download $GOLANG" 
wget https://golang.org/dl/$GOLANG
echo "install $GOLANG" 
sudo tar -C /usr/local -xzf $GOLANG
rm $GOLANG
unset GOLANG

On my laptop, I did the installation manually by removing the previous installation

**Comment by seankhliao** [comment]
so it was an unclean removal (`/usr/local/go/bin` vs `/usr/local/go`)

**Comment by jpmieville** [comment]
Yes, it was because I deleted the folder and then reinstalled it, and then it worked fine.

**Comment by chovy** [comment]
how do i remove on ubuntu 20.04?

**Comment by agnivade** [comment]
Please see the latest instructions at: https://golang.org/doc/install#install. And for further questions, please use a forum. We don't monitor closed issues for troubleshooting questions.
