### ISSUE TITLE
cmd/compile: Failed to compile, AMD64 OS was compiled to 16-bits

### ISSUE THREAD

**Issue by ggdream** [golang/go#44328]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.16 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
PS C:\Users\E plus> go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\E plus\AppData\Local\go-build
set GOENV=C:\Users\E plus\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=F:\gopath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=F:\gopath
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=F:\go
set GOSUMDB=off
set GOTMPDIR=
set GOTOOLDIR=F:\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\EPLUS~1\AppData\Local\Temp\go-build4057894103=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I had just wanted to compile my vgo project by using `go run main.go`, but something went wrong. A minute later, i tried it by the simple `println('hello, world')`, but the same mistake happened. Finally, i rebooted the computer and it returned to normal

### What did you expect to see?
normally running

### What did you see instead?
fork/exec C:\Users\EPLUS~1\AppData\Local\Temp\go-build657859145\b001\exe\main.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

**Comment by ALTree** [comment]
We've had report of this error in the past, but I don't think we've ever truly understood what is causing this. 

In #41631 the OP claims it was their antivirus messing with the go process. Other occurrences: #33736, #38088.

If it fixed itself after a restart I would close here (unless you can provide more info that may help debugging). But it doesn't seem like an actual bug in Go to me.

**Comment by ggdream** [comment]
> We've had reports of this error in the past, but I don't think we've ever truly understood what is causing it.
> 
> In #41631 the OP claims it was their antivirus messing with the go process. Other occurrences: #33736, #38088.
> 
> If it fixed itself after a restart I would close here (unless you can provide more info that may help debugging). But it doesn't seem like an actual bug in Go to me.

It's okay, thank you for the reply!
