### ISSUE TITLE
access: approvers and may-start-trybots for new Google account

### ISSUE THREAD

**Issue by mundaym** [golang/go#44336]
I have switched to using a new Google account with Gerrit in order to be a part of my new employer's Google CLA group.

If possible can my new account (mike.munday@lowrisc.org) be granted the approvers and may-start-trybots permissions:
https://go-review.googlesource.com/#/admin/groups/1005,members
https://go-review.googlesource.com/#/admin/groups/1030,members

My old account should probably be removed from those groups at the same time (https://go-review.googlesource.com/q/owner:michael.munday%2540live.co.uk).

Thanks!

**Comment by seankhliao** [comment]
@golang/release

**Comment by toothrot** [comment]
Done. Sorry this took so long!

**Comment by mundaym** [comment]
> Done. Sorry this took so long!

No problem at all, it was a bit of a weird request. Thanks!
