### ISSUE TITLE
runtime/cgo: cannot build with -Wsign-compare

### ISSUE THREAD

**Issue by elagergren-spideroak** [golang/go#44340]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 linux/amd64
$ gcc version
gcc (Debian 8.3.0-6) 8.3.0
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="llvm-ar-11"
CC="clang-11"
CXX="clang++-11"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build291458045=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
$ cat x.go
package main

/*
#include <stdio.h>
static inline void hello() {
	puts("hello, world!");
}
*/
import "C"

func main() {
	C.hello()
}
$ CGO_CFLAGS="$(go env CGO_CFLAGS) -Wsign-compare" go build x.go
```

### What did you expect to see?

Successful compilation.

### What did you see instead?

```
# runtime/cgo
linux_syscall.c:42:2: error: comparison of integers of different signs: 'uintptr_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
linux_syscall.c:35:11: note: expanded from macro 'SET_RETVAL'
linux_syscall.c:47:2: error: comparison of integers of different signs: 'uintptr_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
linux_syscall.c:35:11: note: expanded from macro 'SET_RETVAL'
linux_syscall.c:52:2: error: comparison of integers of different signs: 'uintptr_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
linux_syscall.c:35:11: note: expanded from macro 'SET_RETVAL'
linux_syscall.c:57:2: error: comparison of integers of different signs: 'uintptr_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
linux_syscall.c:35:11: note: expanded from macro 'SET_RETVAL'
linux_syscall.c:62:2: error: comparison of integers of different signs: 'uintptr_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
linux_syscall.c:35:11: note: expanded from macro 'SET_RETVAL'
linux_syscall.c:67:2: error: comparison of integers of different signs: 'uintptr_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
linux_syscall.c:35:11: note: expanded from macro 'SET_RETVAL'
linux_syscall.c:73:2: error: comparison of integers of different signs: 'uintptr_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
linux_syscall.c:35:11: note: expanded from macro 'SET_RETVAL'
linux_syscall.c:79:2: error: comparison of integers of different signs: 'uintptr_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
linux_syscall.c:35:11: note: expanded from macro 'SET_RETVAL'
linux_syscall.c:84:2: error: comparison of integers of different signs: 'uintptr_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
linux_syscall.c:35:11: note: expanded from macro 'SET_RETVAL'
```

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport to 1.16.

This problem makes it hard to build 1.16 programs that use cgo if you want to use `-Wsign-compare` in `CGO_CFLAGS` (to check your own C code).  The CL fixes the problem.

**Comment by elagergren-spideroak** [comment]
@ianlancetaylor thanks.
