### ISSUE TITLE
dev.go2go: generic embedded field names are not found in composite literals

### ISSUE THREAD

**Issue by griesemer** [golang/go#44345]
[Example](https://go2goplay.golang.org/p/cSo1TnyhzUA):
```Go
package main

type E[T any] struct {
	A T
}

type T struct {
	E[int]
}

func main() {
	_ = T{E[int]{A: 1}}
	//_ = T{E: E[int]{A: 1}} // <<< this should work

	// manually it does work:
	var x T
	x.E = E[int]{A: 1}
}
```
We get an error: 
```
./prog.go2:13: unknown field 'E' in struct literal of type T
```
yet when a `T` is set up manually, the `E` field is recognized.

**Comment by griesemer** [comment]
cc: @findleyr

**Comment by griesemer** [comment]
It appears this error message is coming from the compiler, not the type checker (both `types2` and `go/types` can typecheck this code w/o problems). That is, the bug is probably in `go/go2go` in the `dev.go2go` branch. Unlikely that we're going to spend time to fix this in the prototype since we're now working on a real implementation (which will eventually appear in the playground).

**Comment by griesemer** [comment]
Leaving for @ianlancetaylor to decide.

**Comment by ianlancetaylor** [comment]
I agree that `_ = T{E: E[int]{A: 1}}` should work.

The go2go translation tool has many bugs with embedded fields.

**Comment by griesemer** [comment]
This appears to be working fine in Go 1.18 ([playground](https://go.dev/play/p/dcOIHDeZZIN)). Closing.
