### ISSUE TITLE
regexp/syntax: Compile can only return a nil error

### ISSUE THREAD

**Issue by Muddz** [golang/go#44341]
I can't see any reason why [func Compile(re *Regexp) (*Prog, error){} in regexp/syntax/compile.go](https://github.com/golang/go/blob/2f0da6d9e29d9b9d5a4d10427ca9f71d12bbacc8/src/regexp/syntax/compile.go#L70) should return any error objects at all. It will always just return a `nil` which makes this error check [in regexp/regexp.go](https://github.com/golang/go/blob/master/src/regexp/regexp.go#L178) unnecessary too.

<pre>
$ go version 1.6
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOHOSTOS=windows
</pre></details>

**Comment by ianlancetaylor** [comment]
Perhaps it was a mistake, but changing it now would break the Go 1 compatibility guarantee (https://golang.org/doc/go1compat).
