### ISSUE TITLE
cmd/compile: faild to build vitess.io/vitess/go/vt/vttablet/tabletserver/throttle

### ISSUE THREAD

**Issue by johejo** [golang/go#44344]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +2f0da6d9e2 Wed Feb 17 01:29:54 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

No, tip only

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/heijo/.cache/go-build"
GOENV="/home/heijo/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/heijo/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/heijo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/heijo/ghq/go.googlesource.com/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/heijo/ghq/go.googlesource.com/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel +2f0da6d9e2 Wed Feb 17 01:29:54 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/heijo/ghq/github.com/johejo/gcpanic/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1378102262=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```go
package main

import _ "vitess.io/vitess/go/vt/vttablet/tabletserver/throttle"

func main() {}
```

```
go build .
```

### What did you expect to see?

Build succeeds

### What did you see instead?

```
# vitess.io/vitess/go/vt/vttablet/tabletserver/throttle
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0xc1775b]

goroutine 1 [running]:
cmd/compile/internal/dwarfgen.scopePCs(0xc00086d700, 0xc000015188, 0x2, 0x2, 0xc0017a3e30, 0x2, 0x2)
        /home/heijo/ghq/go.googlesource.com/go/src/cmd/compile/internal/dwarfgen/scope.go:69 +0x7b
cmd/compile/internal/dwarfgen.assembleScopes(0xc00086d700, 0xc000153600, 0xc000a17680, 0x3, 0x4, 0xc0019580a0, 0x3, 0x4, 0x4, 0xc000a17680, ...)
        /home/heijo/ghq/go.googlesource.com/go/src/cmd/compile/internal/dwarfgen/scope.go:40 +0x14a
cmd/compile/internal/dwarfgen.Info(0xc00086d700, 0xc00086d780, 0xd55500, 0xc000153600, 0x51, 0xc000e0b8b0, 0x48, 0xffffffffffffffff, 0xc0013a5a60, 0x5580e5)
        /home/heijo/ghq/go.googlesource.com/go/src/cmd/compile/internal/dwarfgen/dwarf.go:121 +0xa49
cmd/internal/obj.(*Link).DwarfAbstractFunc(0xc000370000, 0xd55500, 0xc000153600, 0xc00086d700, 0x7ffcfbe28c39, 0x35)
        /home/heijo/ghq/go.googlesource.com/go/src/cmd/internal/obj/dwarf.go:413 +0xe2
cmd/compile/internal/dwarfgen.AbstractFunc(0xc00086d700)
        /home/heijo/ghq/go.googlesource.com/go/src/cmd/compile/internal/dwarfgen/dwinl.go:220 +0xc9
cmd/internal/obj.(*DwarfFixupTable).Finalize(0xc000125180, 0x7ffcfbe28c39, 0x35, 0x0)
        /home/heijo/ghq/go.googlesource.com/go/src/cmd/internal/obj/dwarf.go:672 +0x232
cmd/compile/internal/gc.Main(0xd8bf40)
        /home/heijo/ghq/go.googlesource.com/go/src/cmd/compile/internal/gc/main.go:290 +0x117c
main.main()
        /home/heijo/ghq/go.googlesource.com/go/src/cmd/compile/main.go:54 +0xb1
```

**Comment by randall77** [comment]
@thanm  for DWARF.

**Comment by thanm** [comment]
I'll take a look.
