### ISSUE TITLE
Dyninst WrapFunction does not work for C++ and golang

### ISSUE THREAD

**Issue by ManojKumarChauhan** [golang/go#44369]
[fastmalloc.tar.gz](https://github.com/golang/go/files/6002080/fastmalloc.tar.gz)

### What version of Go are you using (`go version`)?
latest version 10.2.1

<pre>
$ go version
1.15
</pre>

### Does this issue reproduce with the latest release?
Yes with every version

### What operating system and processor architecture are you using (`go env`)?
 16.04.1-Ubuntu x86_64 GNU/Linux
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
As per the implementation of WrapFunction on page no 24 of url https://dyninst.org/sites/default/files/manuals/dyninst/dyninstAPI.pdf,  I implemented fastMalloc in a library and origMalloc in a c program.
When origMalloc is the part of c program then wrapfunction works fine but when origMalloc is part of a library which is used by c program then wrpfunction does not work. The same issue exists for golang.

To reproduce the isue, get attached c file. Create library libwmalloc.so for libwmalloc.c, libomalloc.so for libomalloc.c, create c program from cprogram.c which uses libomalloc.so.  Use codecoverage to wrap origMalloc by fastMalloc.
### What did you expect to see?
wrpfunction should work when origMalloc is part of a library .

### What did you see instead?
wrpfunction does not work

**Comment by seankhliao** [comment]
this doesn't sound like a Go problem, if it doesn't work in C then there's no reason to believe it should work for Go.
