### ISSUE TITLE
x/pkgsite: long names have poor formatting

### ISSUE THREAD

**Issue by symbiont-ji** [golang/go#44365]
### What is the URL of the page with the issue?
 https://pkg.go.dev/google.golang.org/api@v0.40.0/compute/v1#pkg-types
 
 
### What is your user agent?
 Version 88.0.4324.182 (Official Build) (64-bit)

 
 
 
### Screenshot
 

 
 
![image](https://user-images.githubusercontent.com/72036878/108318973-b15eb200-718e-11eb-8fee-4356f7cafa07.png)

### What did you do?
 Just browsing that page

 
 
 
### What did you expect to see?
 Two things: 
 
 1. I expected the menu on the left that lists all the types and functions to be resizable, so that long names can actually be displayed. As it stands, this is completely useless; to browse them, I have to hover over each one of them and wait for actual url to show at the bottom of the window.
 2. I have a wide screen for a reason. Why are you filling the browser window with empty white space, when you could simply have expanded the individual frames to fill the whole width?
 
### What did you see instead?

This design that makes no sense in the year 2021.

**Comment by jamalc** [comment]
The layout of the documentation page has been adjusted to make better use of space on larger screens.
