### ISSUE TITLE
x/tools/gopls: invalid link in codeaction description

### ISSUE THREAD

**Issue by hyangah** [golang/go#44360]
gopls version: 0.6.6-pre.1
go version: 1.16

While there is still "Error Loading workspace" error is active because I opened a directory that contains multiple go modules,
I found the links included in the diagnostics message for import statements contain invalid links.

![Screen Shot 2021-02-17 at 10 05 31 PM](https://user-images.githubusercontent.com/4999471/108299734-f4a82900-716c-11eb-8b62-c1432850fc38.png)

![Screen Shot 2021-02-17 at 10 05 44 PM](https://user-images.githubusercontent.com/4999471/108299724-ef4ade80-716c-11eb-8cde-7620bc024bf0.png)

gopls trace shows the uri scheme is `file://`
```
[Trace - 22:10:41.002 PM] Sending request 'textDocument/codeAction - (33)'.
Params: {"textDocument":{"uri":"file:///Users/hakim/projects/google/misc-builder/cmd/cli/findwork.go"},"range":{"start":{"line":10,"character":1},"end":{"line":10,"character":32}},"context":{"diagnostics":[{"range":{"start":{"line":10,"character":1},"end":{"line":10,"character":32}},"message":"could not import github.com/google/subcommands (cannot find package \"github.com/google/subcommands\" in any of \n\t/usr/local/go/src/github.com/google/subcommands (from $GOROOT)\n\t/Users/hakim/go/src/github.com/google/subcommands (from $GOPATH))","code":"BrokenImport","codeDescription":{"href":"file:///pkg.go.dev/golang.org/x/tools/internal/typesinternal#BrokenImport"},"severity":1,"source":"compiler"}],"only":["quickfix"]}}
```

**Comment by stamblerre** [comment]
@findleyr: I guess we do need to add a scheme. Not sure why I didn't run into this issue.
