### ISSUE TITLE
x/tools/gopls: outside GOPATH/src && module

### ISSUE THREAD

**Issue by iamcmnut** [golang/go#44363]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.2 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
I'm not sure we didn't use the latest go version

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/iamcmnut/Library/Caches/go-build"
GOENV="/Users/iamcmnut/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/iamcmnut/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/iamcmnut/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/iamcmnut/tbox/projects/drex-microservices/gateway/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4m/s6j4mh2d4wjf9wxj5jvwvsbh0000gn/T/go-build941263063=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I'm using vs code with Go extension and its show me these message
Error loading workspace: You are outside of a module and outside of $GOPATH/src. If you are using modules, please open your editor to a directory in your module. If you believe this warning is incorrect, please file an issue: https://github.com/golang/go/issues/new.

<img width="253" alt="Screen Shot 2564-02-18 at 13 05 27" src="https://user-images.githubusercontent.com/2133659/108313046-388d4380-71ea-11eb-8316-a9527f0dd965.png">

### What did you expect to see?
It should not show this error and extension can jump to source file when I click the function

### What did you see instead?
It shows many errors on the files, it looks like it can not find dependency files.

**Comment by stamblerre** [comment]
Can you please share a `gopls` log by following the steps described [here](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-extension-logs)?

Is there any reason that you are working outside of your GOPATH and outside of a module?

**Comment by stamblerre** [comment]
Closing this issue as there hasn't been any activity on it for a few weeks. Please open a new issue if this problem persists.
