### ISSUE TITLE
rs_bug

### ISSUE THREAD

**Issue by rsonmez** [golang/go#44374]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.8 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ridvan/.cache/go-build"
GOENV="/home/ridvan/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ridvan/goeg_rs/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ridvan/goeg_rs"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build124408937=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.15.8 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.15.8
uname -sr: Linux 4.15.0-135-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.27-3ubuntu1.4) stable release version 2.27.
gdb --version: GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
</pre></details>

**Comment by ALTree** [comment]
Empty, closing.
