### ISSUE TITLE
os/exec: LookPath inconsistency on windows/arm64

### ISSUE THREAD

**Issue by rsc** [golang/go#44379]
After a recent Windows 10 update on my Surface Pro X, os/exec TestLookPath is failing.
It appears to be a bug introduced in the update in cmd.exe itself.

The transcript below seems to show that cmd.exe is not respecting the order of extensions in PATHEXT:
even though EXE comes before BAT, cmd is prefering a.bat over a.exe.

```
C:\Users\russc\tmp>dir
 Volume in drive C is Local Disk
 Volume Serial Number is 6254-048B

 Directory of C:\Users\russc\tmp

02/18/2021  08:13 AM    <DIR>          .
02/18/2021  08:10 AM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  420,601,499,648 bytes free

C:\Users\russc\tmp>mkdir p1

C:\Users\russc\tmp>copy con p1\a.bat
@echo a1.bat
^Z
        1 file(s) copied.

C:\Users\russc\tmp>copy ..\go\bin\go.exe p1\a.exe
        1 file(s) copied.

C:\Users\russc\tmp>p1\a.exe
Go is a tool for managing Go source code.
...

C:\Users\russc\tmp>p1\a.bat
a1.bat

C:\Users\russc\tmp>p1\a
a1.bat

C:\Users\russc\tmp>set PATHEXT
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

C:\Users\russc\tmp>p1\a.BAT
a1.bat

C:\Users\russc\tmp>p1\a.EXE
Go is a tool for managing Go source code.
...

C:\Users\russc\tmp>set PATH=C:\users\russc\tmp\p1

C:\Users\russc\tmp>a
a1.bat

C:\Users\russc\tmp>
```

**Edit**: I am running Windows 10 Home Insider Preview, Build 21301.rs_prerelease.210123-1645, on a Surface Pro X.

**Comment by zx2c4** [comment]
What makes you so certain this is arm64 only? Have you tried updating to the latest insider ring on amd64?

**Comment by rsc** [comment]
@jstarks says it repros on x64 as well. Will update the CL.

**Comment by jstarks** [comment]
I can confirm that this is broken on x64 as well. We (Microsoft) are looking into it.

**Comment by jstarks** [comment]
We've confirmed that this is an OS bug in prerelease versions of Windows. We'll fix this in an upcoming preview build. Thanks for the report, Russ.

**Comment by dmitshur** [comment]
@jstarks Thank you for fixing the bug and the update here.

@rsc Is there anything that needs to be done for Go 1.17 on Go's side, or is the fix in the OS sufficient? This issue can be updated to re-enable the failing LookPathTest that was skipped in [CL 293709](https://golang.org/cl/293709) (and possibly move it out of Go 1.17 milestone if it isn't expected to happen before the release).

**Comment by zx2c4** [comment]
I would think that trying to provide workarounds for prerelease OS builds is not going to be very productive. Microsoft is pretty good generally about trying not to break things in major releases, and users of prerelease accept that some things might not work very well. 21301 is quite old at this point too (though I'm not sure in which version it was fixed).
