### ISSUE TITLE
x/tour: several languages are offline

### ISSUE THREAD

**Issue by katiehockman** [golang/go#44382]
There are several versions of the tour in different languages which are offline: https://tour.golang.org/welcome/2

For these versions of the tour which are run by volunteers and are often online, we may consider taking them down entirely. Otherwise, it may be worth a small note at the top which indicates that these different versions may be down.

e.g. #41219

/cc @golang/release

**Comment by ALTree** [comment]
Tracking at golang/tour#1039.

>  are often online

In this case I believe it's more like "appspot removed Go1.9 support and any tour deployment that wasn't re-deployed by the owner after the deprecation has been offline since".

**Comment by dmitshur** [comment]
I think it makes sense to proceed with deleting them given how much time has passed. They can be re-added after being fixed.
