### ISSUE TITLE
time: LoadLocationFromTZData with slim tzdata uses incorrect zone

### ISSUE THREAD

**Issue by vcabbage** [golang/go#44385]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="linux"
</pre></details>

### What did you do?

Loaded tzdata with both "fat" and "slim" formats.

### What did you expect to see?

Same time zone info regardless of whether using "fat" or "slim" tzdata.

### What did you see instead?

Incorrect zones selected when using "slim" tzdata.

Comparing "fat" and "slim" versions of the 2021a tzdata I found 9 discrepancies:
```
America/Godthab
        FAT:   -03 | -10800
        SLIM:  -02 |  -7200
America/Nuuk
        FAT:   -03 | -10800
        SLIM:  -02 |  -7200
America/St_Johns
        FAT:   NST | -12600
        SLIM:  NST | -12652
Asia/Gaza
        FAT:   EET |   7200
        SLIM: EEST |  10800
Asia/Hebron
        FAT:   EET |   7200
        SLIM: EEST |  10800
Asia/Jerusalem
        FAT:   IST |   7200
        SLIM:  IDT |  10800
Asia/Tel_Aviv
        FAT:   IST |   7200
        SLIM:  IDT |  10800
Canada/Newfoundland
        FAT:   NST | -12600
        SLIM:  NST | -12652
Israel
        FAT:   IST |   7200
        SLIM:  IDT |  10800
```
Script used (doesn't work in playground): https://play.golang.org/p/iaduStbpjnU

`time/tzdata` is affected in Go 1.16 since it now uses the "slim" format.

Related: #42216

**Comment by vcabbage** [comment]
Some of the listed time zones are duplicates.
`America/Godthab` has been deprecated and replaced with `America/Nuuk`
`Canada/Newfoundland` has been deprecated and replaced with`America/St_Johns`
`Asia/Tel_Aviv` and `Israel` have been deprecated and replaced with`Asia/Jerusalem`

**Comment by ianlancetaylor** [comment]
Thanks for finding these cases.  Sending a fix.

**Comment by vcabbage** [comment]
@ianlancetaylor Thanks! Should this be considered for a 1.16 patch release since it affects `time/tzdata`?

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport issues.

We mishandle a couple of cases in the time extension strings used by the slim tzdata format.  The slim format is likely to appear on more and more systems going forward, and is what we use when people use the time/tzdata package.
