### ISSUE TITLE
cmd/compile: large unnamed struct can result in 'name too long' error at link time

### ISSUE THREAD

**Issue by rsc** [golang/go#4438]
<pre>Because we use the raw type literal in symbol names, if the result exceeds 8 kB (!),
then ld's Brdline will not be able to read the name into the Biobuf buffer, which will
make ld print 'name too long'. For enormous literals like this we need an alternate
plan, like using the sha1 sum of the type text instead.</pre>

**Comment by odeke-em** [comment]
Yeah, just like @minux mentioned, @rtoma's program can now be compiled fine,
as on the playground at https://play.golang.org/p/RGuspjE9uw

**Comment by rtoma** [comment]
Wow, blast from the past.

Verified with `go version go1.7.3 darwin/amd64`
Thanks for fixing.

**Comment by odeke-em** [comment]
@rsc or @griesemer can we close this s'il vous plait?
