### ISSUE TITLE
access: add zpavlinovic to go-assignees and go-approvers

### ISSUE THREAD

**Issue by zpavlinovic** [golang/go#44398]
https://github.com/orgs/golang/teams/go-assignees
https://github.com/orgs/golang/teams/go-approvers

Following https://github.com/golang/go/wiki/GithubAccess#assigneesSee https://golang.org/wiki/GithubAccess

**Comment by dmitshur** [comment]
CC @golang/release.

**Comment by toothrot** [comment]
Invites sent.
