### ISSUE TITLE
"go get" install a package to 'pkg' folder rather than 'src' folder

### ISSUE THREAD

**Issue by workerace** [golang/go#44392]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ungbee\AppData\Local\go-build
set GOENV=C:\Users\ungbee\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\ungbee\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\****\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ungbee\AppData\Local\Temp\go-build3506160039=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

I just ran below in terminal
>> go get github.com/PuerkitoBio/goquery
>> go run main.go

main.go

package main

import "github.com/PuerkitoBio/goquery"

### What did you see instead?
main.go:3:8: no required module provides package github.com/PuerkitoBio/goquery: working directory is not part of a module

And vscode error says 
"could not import github.com/PuerkitoBio/goquery (cannot find package "github.com/PuerkitoBio/goquery" in any of 
	D:\Program Files\Go\src\github.com\PuerkitoBio\goquery (from $GOROOT)
	C\src\github.com\PuerkitoBio\goquery (from $GOPATH)
	\Users\****\go\src\github.com\PuerkitoBio\goquery (from $GOPATH))"

I cannot find the package in 'src' folder. The package is found in 'pkg' folder of $GOPATH.

**Comment by seankhliao** [comment]
module mode is now default: https://golang.org/doc/go1.16#modules

**Comment by Yakkay0** [comment]
I solved it in Linux setting GO111MODULE="auto"`, as says the document provided by @seankhliao [https://golang.org/doc/go1.16#modules](url)

`export GO111MODULE="auto"`
