### ISSUE TITLE
x/website: webside 404 issue

### ISSUE THREAD

**Issue by EngsShi** [golang/go#44414]
webside 404 issue

https://golang.org/doc/articles/wiki/

<pre>
File doc/articles/wiki/
doc/articles/wiki/
open REDACTED: file does not exist

</pre>

you can jump from https://golang.org/doc/#writing-web-applications

**Comment by mvdan** [comment]
Dup of https://github.com/golang/go/issues/44314. It's still a 404 so I'm not sure when the fix will be deployed. @dmitshur @rsc I'm leaving this issue open until the page is fixed to prevent yet more duplicates.

**Comment by dmitshur** [comment]
Thanks, we'll deploy today. @toothrot is already on it, please close this issue when done.
