### ISSUE TITLE
go/types, types2: type-checker internal type printing doesn't print embedded fields that are alias types correctly

### ISSUE THREAD

**Issue by griesemer** [golang/go#44410]
Given
```Go
type E = map[string]int
type S struct {
   E
}
```
the struct `S` will be printed with an embedded field named `map[string]int` because we have lost information about its alias name.

This affects debugging and test cases, e.g., `src/go/internal/gccgoimporter/importer_test.go:97` wants `"type S struct{b int; A2"` but we only have `"type S struct{b int; map[Y]Z}"`.

The relevant printing code is in `go/types/typestring.go`, function `writeType`.

**Comment by griesemer** [comment]
If we solve the type alias related issues (by introducing an explicit type alias node), this issue would probably be fixed as well.

**Comment by ianlancetaylor** [comment]
@griesemer This is in the 1.18 milestone; time to move to 1.19?  Thanks.

**Comment by griesemer** [comment]
CL 381776, if it can be made to work, would fix this. Leaving open for a bit longer. But fine to move to 1.19 once we decide to move forward with the release.

**Comment by griesemer** [comment]
There's no easy fix that doesn't require major restructuring. We have lived with this for a long time, so not a regression. Leaving for 1.19.

**Comment by griesemer** [comment]
A proper fix will require quite a bit of work on alias type representation. We won't get to this for 1.19, but we may want to make it a goal for 1.20. Adjusting milestone.

**Comment by griesemer** [comment]
This is fixed if Alias nodes are enabled via `GODEBUG=gotypesalias=1`. Closing.
