### ISSUE TITLE
x/pkgsite: github.com/adrg/libvlc-go/v3 and github.com/adrg/libvlc-go/v2 not being updated to the latest version

### ISSUE THREAD

**Issue by adrg** [golang/go#44413]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/adrg/libvlc-go/v3
https://pkg.go.dev/github.com/adrg/libvlc-go/v2 

### What is your user agent?
 
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36`

### What did you do?

After releasing versions 3.1.1 and 2.1.1 of my package, I went to `pkg.go.dev` to manually update the module versions.
I went to https://pkg.go.dev/github.com/adrg/libvlc-go/v3@v3.1.1 so I would get the 404 page and then request
the module to be updated. However, that kept redirecting me back to version `v3.1.0`.

So then I made a request to `proxy.golang.org` instead. That worked but `pkg.go.dev` still did not show the latest version
of the module. I made multiple requests to the proxy and I think at some point I mistakenly omited the major version of the package:

```
https://proxy.golang.org/github.com/adrg/libvlc-go/@v/v3.1.1.info

instead of

https://proxy.golang.org/github.com/adrg/libvlc-go/v3/@v/v3.1.1.info
````

The results from https://index.golang.org/index?since=2021-02-18T20:20:43Z:
```
{"Path":"github.com/adrg/libvlc-go/v2","Version":"v2.1.1","Timestamp":"2021-02-18T20:35:57.112837Z"}
{"Path":"github.com/adrg/libvlc-go","Version":"v2.1.1+incompatible","Timestamp":"2021-02-18T20:42:10.955525Z"}
```

```
{"Path":"github.com/adrg/libvlc-go/v3","Version":"v3.1.1","Timestamp":"2021-02-18T20:38:54.088784Z"}
{"Path":"github.com/adrg/libvlc-go","Version":"v3.1.1+incompatible","Timestamp":"2021-02-18T20:36:32.864144Z"}
```

### What did you expect to see?

I was expecting `go.pkg.dev` to show the latest version of the packages (3.1.1 and 2.1.1).
 
### What did you see instead?

`go.pkg.dev` is currently showing the previous version (3.1.0, respectively 2.1.0).

**Comment by jba** [comment]
Thanks for the report. Yesterday's deployment broke our processing pipeline. It will be fixed in a few hours. I'll ping this bug when your modules are ready.

**Comment by adrg** [comment]
Thank you for the quick response. I look forward to the issue being fixed. I apologize for any inconvenience I may have caused.

**Comment by jba** [comment]
On the contrary, you found a hole in our alerting, so thank _you_.

**Comment by jba** [comment]
These are both ready.

**Comment by adrg** [comment]
Yes, both modules are updated. Thanks again.
