### ISSUE TITLE
access: may-start-trybots

### ISSUE THREAD

**Issue by pmur** [golang/go#44424]
I have been doing an increasing amount of work on golang for ppc64, and this would be helpful to reduce noise to others.  My linked account is murp@ibm.com. Can it be granted access to may-start-trybots and anything else required to perform CI on the go and go/arch repos?

**Comment by cagedmantis** [comment]
Hi Paul,

Thank you for your contributions and for requesting Trybots access! I've added you to the may-start-trybots group, so you should be able to do so now.

As you've likely read at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a Trybot run.

Let us know if you have any questions or issues with it, and thanks again! I apologize for the delay in responding to this request.
