### ISSUE TITLE
go/internal/gccgoimporter: TestInstallationImporter broken with tip gccgo

### ISSUE THREAD

**Issue by thanm** [golang/go#44425]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +e8379ab596 Sat Nov 7 16:59:40 2020 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/local/google/home/thanm/.cache/go-build"
GOENV="/usr/local/google/home/thanm/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/ssd2/go1/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/ssd2/go1"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/ssd2/ygo"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/ssd2/ygo/pkg/tool/linux_amd64"
GCCGO="/ssd/gcc-trunk/cross/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"It looks as though the signature for sorts.Int was changed as part of 1.16 in af8748054b, and this change has now made it into gccgo tip.  Given that the test is picking sort.Ints in an arbitrary fashion, it's probably best to pick a different type to examine.
It looks as though the signature for sorts.Int was changed as part of 1.16 in af8748054b, and this change has now made it into gccgo tip.  Given that the test is picking sort.Ints in an arbitrary fashion, it's probably best to pick a different type to examine.

CGO_ENABLED="1"
GOMOD="/ssd2/ygo/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build254549658=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

This requires using "tip" gccgo, as opposed to released gccgo. Add "gccgo" to PATH, then

```
$ cd `go env GOROOT`
$ cd src/go/internal/gccgoimporter
$ go test .
```

### What did you expect to see?

Passing test

### What did you see instead?

This faliure:

```
--- FAIL: TestInstallationImporter (0.65s)
    importer_test.go:41: Ints: got "func Ints(x []int)"; want "func Ints(a []int)"
FAIL
FAIL	go/internal/gccgoimporter	1.233s
FAIL
```

It looks as though the signature for sorts.Int was changed as part of 1.16 in af8748054b, and this change has now made it into gccgo tip at https://go-review.googlesource.com/c/gofrontend/+/280172.  Given that the test is picking `sort.Ints` in an arbitrary fashion, it's probably best to pick a different type to examine.

**Comment by ianlancetaylor** [comment]
@gopherbot Please backport to 1.16

This is fixed on tip, but causes a test failure on 1.16 when gccgo is installed.  The fix is trivial (https://golang.org/cl/294290) so let's backport it.
