### ISSUE TITLE
x/website: #go-install anchor in mod reference doesn't exist but is used in a few places

### ISSUE THREAD

**Issue by ALTree** [golang/go#44423]
The *[Add dependencies to current module and install them](https://golang.org/cmd/go/#hdr-Add_dependencies_to_current_module_and_install_them)* section in the cmd/go documentation links to a `#go-install` anchor in the modules reference, but the anchor does not exists:

> See 'go help install' or https://golang.org/ref/mod#go-install for details. 

https://golang.org/ref/mod#go-install goes nowhere.

The same anchor is also referenced in the new [1.16 modules change blogpost](https://blog.golang.org/go116-module-changes):

> Now we can all use go install program@latest instead. See **go install** for details.

With an href on the `go install` words.

What's strange is that I can see a section dedicated to `go install` (with an anchor) here:

https://github.com/golang/website/blob/a9ebb32b2bed8967e3688d11879261e95ac73891/_content/doc/mod.md

But I can't see it in the version deployed on the website.

cc @dmitshur @jayconrod

**Comment by jayconrod** [comment]
Oops, sorry about this. I merged the new docs on Tuesday, but it was after the cutoff for the 1.16 release. I think the site just needs to be redeployed.

@golang/release Could one of you do that today?

**Comment by dmitshur** [comment]
Yes, I'm doing a deploy now (also for #44414).
