### ISSUE TITLE
x/website: highlight removal of previous Go install in Linux installation instructions

### ISSUE THREAD

**Issue by dmitshur** [golang/go#44426]
Experience and feedback in #44320 (thank you @jpmieville, @davecheney, @agnivade) suggests that the current Linux installation instructions are prone to a user mistake: missing the step of removing the previous Go installation at /usr/local/go before extracting the new Go version into the same location.

Making that mistake results in a corrupted Go installation which may produce strange errors. Worse yet, there is a possibility of it failing silently but producing incorrect results, compromising the reliability of the installed Go version.

There is a mention that the previous Go installation should be removed above the numbered steps:

![image](https://user-images.githubusercontent.com/1924134/108515110-b6a52500-7292-11eb-858f-22326ffd1b22.png)

This issue is about highlighting it to reduce the chances of this important step being overlooked by users.

CC @straut, @jayconrod, @golang/release.

**Comment by dmitshur** [comment]
Given how important the step of removing the previous /usr/local/go directory before extracting, I think we must include it in the numbered steps.

The current instructions link to https://golang.org/doc/manage-install#uninstalling, but that's less ideal for two reasons: 1) we only need the /usr/local/go directory to be removed, while Uninstalling Go involves removing Go bin directory from PATH, which doesn't need to be done, and 2) it links to another page, taking the reader out of context; it's better to keep the installation instructions contained on a single page.

Step 1 also repeats "Download the archive" unnecessary: that was done in the https://golang.org/doc/install#download step above.

I have some worries about suggesting a command that begins with "rm -rf"

I came up with two alternatives that might work better.

### Alternative A

The first one avoids including the "rm -rf" command, asking the user to take it on themselves to know how to remove a directory on Linux.

It also adds the `-k` parameter to the tar command, so that the tar command fails if a previous tree hasn't been removed. This is better than silently proceeding and getting a corrupted installation.

![image](https://user-images.githubusercontent.com/1924134/108527681-91b7ae80-72a0-11eb-9536-76f8b0677e57.png)

### Alternative B

The second one combines "rm -rf /usr/local/go" with the "tar" command, and includes an Important note about what will happen and that the user should backup data as needed. Hopefully this is safe and convenient. It's unfortunate that the command is either long or split across two lines though.

![image](https://user-images.githubusercontent.com/1924134/108527761-a8f69c00-72a0-11eb-9f07-450a0702fc4f.png)

---

I'm currently slightly leaning towards B, because it seems more convenient, reliable, and safe. But if there are concerns with suggesting "rm -rf" then A should be the next best thing.

Let me know if you have thoughts or ideas for how to improve this.

**Comment by jayconrod** [comment]
Alternative B seems better to me. I think it's better to be clear that the old tree is removed while having something pasteable.
