### ISSUE TITLE
cmd/compile: type2 reports wrong internal compiler error with -d=panic

### ISSUE THREAD

**Issue by cuonglm** [golang/go#44445]
### What version of Go are you using (`go version`)?

tip

### Does this issue reproduce with the latest release?

No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Compile this program with `go tool compile -d=panic -G=1 main.go`
```
package main

import "sort"

func main() {
	sort.Sort(nil);
	var x int;
	sort(x);	// ERROR "package"
}
```

### What did you expect to see?

```
main.go:8:2: use of package sort not in selector
```
### What did you see instead?

```
main.go:8:2: use of package sort not in selector
<unknown line number>: internal compiler error: conf.Check error: main.go:8:2: use of package sort not in selector

goroutine 1 [running]:
runtime/debug.Stack(0x104ce18b8, 0x14000130008, 0x0)
	/Users/cuonglm/sources/go/src/runtime/debug/stack.go:24 +0x88
cmd/compile/internal/base.FatalfAt(0x0, 0x104ab6ab2, 0x14, 0x14000145880, 0x1, 0x1)
	/Users/cuonglm/sources/go/src/cmd/compile/internal/base/print.go:227 +0x18c
cmd/compile/internal/noder.check2(0x14000130160, 0x1, 0x1)
	/Users/cuonglm/sources/go/src/cmd/compile/internal/noder/irgen.go:72 +0x394
cmd/compile/internal/noder.LoadPackage(0x14000134070, 0x1, 0x1)
	/Users/cuonglm/sources/go/src/cmd/compile/internal/noder/noder.go:77 +0xc6c
cmd/compile/internal/gc.Main(0x104cd2548)
	/Users/cuonglm/sources/go/src/cmd/compile/internal/gc/main.go:187 +0x938
main.main()
	/Users/cuonglm/sources/go/src/cmd/compile/main.go:54 +0xb0
```

The old type checker is also panic, but that's a real bug there which I fixed in https://go-review.googlesource.com/c/go/+/294031/5

**Comment by cuonglm** [comment]
cc @mdempsky @griesemer

**Comment by mdempsky** [comment]
Probably we should just move the `ExitIfErrors` here above the `if err != nil` check: https://github.com/golang/go/blob/d4b26382342c98a95b85140b2863bc30c48edd68/src/cmd/compile/internal/noder/irgen.go#L74

That would ensure we exit gracefully if we've reported any errors, and still ICE if for some unusual reason typechecking failed but we didn't report any errors.
