### ISSUE TITLE
x/tools/gopls: Auto-make-up  when calling public method or value after press '.'

### ISSUE THREAD

**Issue by fwhezfwhez** [golang/go#44450]
On the case you want to build a new project when there exists old projects, using GOPATH, Every outer-package  public method can be well auto-make-up after press '.'

But now using gomodule, It can hardly auto-make-up method name unless I'm aware of what I want to import, then first go get it and then use it. This is too bad!

**Comment by ianlancetaylor** [comment]
CC @stamblerre

**Comment by stamblerre** [comment]
`gopls` does offer autocompletion for unimported packages that are available in your module cache (`$GOPATH/pkg/mod`). I'm not aware of any features in GOPATH mode that would provide completions for packages you have not downloaded yet.

If you can share a specific example of this issue, please do so. Please also take a look at our [troubleshooting guide](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md) and attach your `gopls` logs.

**Comment by fwhezfwhez** [comment]
@stamblerre 
gopls now works well, and this issue is not reporting a bug.

When I take response to many projects, and now I want to start a new project.

In the past using GOPATH, starting a new project is just convenient because all packages can be well completed by gopls because all these normal packages're already in GOPATH as old project have downloaded them and  share them.

Now using GOMODULE, even if I've hold many existed projects, when I start a new app project, I still need to consider which package I should go get first and then I can using gopls to auto completed its dot tip. I hope there exists a scheme that gopls can make-up a package that I use it in my new project in the first time(that it's just not go get yet), it can privilagedly refer to a package's newest version locally.

For example:
I own app1, app2 ,app3, app4  four projects and have built a big enough GOPATH/pkg/mod/.....

then, I want to start a new app5.

As I press `gin.`, ok now I dont actually go get github.com/gin-gonic/gin from app5 while GO111MODULE is on.

At this time , gopls should refer to 
```
GOPATH/pkg/mod/github.com/gin-gonic/gin@v1.1.0
GOPATH/pkg/mod/github.com/gin-gonic/gin@v1.2.0
GOPATH/pkg/mod/github.com/gin-gonic/gin@v1.3.0
GOPATH/pkg/mod/github.com/gin-gonic/gin@v1.4.0
```
Gopls counts a latest version of gin and then choose v1.4.0.

Then I got tip:
```
gin.
      |.New()
      |.Default()
      |.....
```
These tips are just appear before I execute go get github.com/gin-gonic/gin@...
                                     also before I firstly run app5 as `go.mod` is just auto-filled

**Comment by stamblerre** [comment]
This workflow already exists in `gopls`--it is what we refer to as "unimported completions". Can you please try this out and [share a log](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capture-logs) if it doesn't work as expected?

**Comment by stamblerre** [comment]
Closing this issue as there hasn't been any activity on it for 2 weeks. Please file a new issue if unimported completions do not work for you.
