### ISSUE TITLE
♟︎ not recognized as rune literal

### ISSUE THREAD

**Issue by heyitsanthony** [golang/go#44472]
### What version of Go are you using (`go version`)?

1.16

### Does this issue reproduce with the latest release?

Yes, https://play.golang.org/p/-hotpLlRhNT

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/a/.cache/go-build"
GOENV="/home/a/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/a/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/a/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3168975412=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```go
package main

import (
	"fmt"
)

var s = []rune{'♚', '♛', '♜', '♝', '♞' ,'♟︎'}

func main() {
	for i, v := range s {
		fmt.Println(i, v)
	}
}
```

### What did you expect to see?

Successful build.

### What did you see instead?

./prog.go:7:51: more than one character in rune literal

**Comment by dsnet** [comment]
That's because there's a [non-visible U+FE0E character](https://www.fileformat.info/info/unicode/char/fe0e/index.htm) to the right of the pawn.

You can see that by [running this snippet](https://play.golang.org/p/e_TcD3Y9GLb).

**Comment by heyitsanthony** [comment]
Ah ha, thank you. Closing.
