### ISSUE TITLE
math/rand: document whether NewSource always implements Source64

### ISSUE THREAD

**Issue by dsnet** [golang/go#44488]
The [concrete type returned by `NewSource` happens to implement `Source64`](https://play.golang.org/p/gxPB1je9grf). However, this is not documented in any way. Is this always guaranteed?

**Comment by ulikunitz** [comment]
I looked into the source code of rng.go and since Int63() calls Uint64(), NewSource is always returning a Source64 implementation.

```
// Int63 returns a non-negative pseudo-random 63-bit integer as an int64.
func (rng *rngSource) Int63() int64 {
	return int64(rng.Uint64() & rngMask)
}
```

**Comment by dsnet** [comment]
I believe the snippet you actually wanted to reference is:
https://github.com/golang/go/blob/87e984ab2988afccdb75a4c235b318ec6be46e6a/src/math/rand/rng.go#L237-L252

I'm aware that it current returns something that implements `Source64` and has done so for many years. The question is whether this should be a documented guarantee (which I think it should be).

**Comment by ianlancetaylor** [comment]
I think we should document it.
