### ISSUE TITLE
plugin: syscall.Mmap panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by oszika** [golang/go#44491]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, only using plugins. But it works with go1.15.8 (with plugins or not).

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/oszika/.cache/go-build"
GOENV="/home/oszika/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/oszika/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/oszika/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/example/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1397047588=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I build a plugin, that calls raftboltdb.NewBoltStore. Then I use this plugin.

Plugin: /tmp/example/plugin/main.go:
```
package main

import (
        "log"

        raftboltdb "github.com/hashicorp/raft-boltdb"
)

var Init = func() {
        log.Println(raftboltdb.NewBoltStore("/tmp/raft.db"))
}

func main() {}
```

Build: <pre>go build -buildmode=plugin -o plugin.so .</pre>

Main file: /tmp/example/main.go:
```
package main

import (
        "log"
        "plugin"
)

func main() {
        p, err := plugin.Open("plugin/plugin.so")
        if err != nil {
                log.Fatal(err)
        }
        s, err := p.Lookup("Init")
        if err != nil {
                log.Fatal(err)
        }

        f := *s.(*func())
        f()
}
```

Run: <pre>go run main.go</pre>

I'll try to call Init() in the main of plugin.go directly. There is no problem. It seems wrong only for plugins.

### What did you expect to see?
No panic, no error.

### What did you see instead?
panic: assignment to entry in nil map

goroutine 1 [running]:
syscall.(*mmapper).Mmap(0x7fe6d5321aa0, 0x6, 0x0, 0x8000, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/go/src/syscall/syscall_unix.go:75 +0x173
syscall.Mmap(...)
        /usr/lib/go/src/syscall/syscall_linux.go:1230
github.com/boltdb/bolt.mmap(0xc00000c1e0, 0x8000, 0x0, 0x0)
        /home/oszika/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/bolt_unix.go:50 +0xa5
github.com/boltdb/bolt.(*DB).mmap(0xc00000c1e0, 0x0, 0x0, 0x0)
        /home/oszika/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:277 +0x245
github.com/boltdb/bolt.Open(0x7fe6d50f560d, 0xc, 0xc000000180, 0x7fe6d538e7a0, 0x5f05c0, 0x5fdb80, 0x0)
        /home/oszika/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:230 +0x305
github.com/hashicorp/raft-boltdb.New(0x7fe6d50f560d, 0xc, 0x0, 0xc00012e000, 0xc00012e000, 0x0, 0x0)
        /home/oszika/go/pkg/mod/github.com/hashicorp/raft-boltdb@v0.0.0-20191021154308-4207f1bf0617/bolt_store.go:66 +0x4d
github.com/hashicorp/raft-boltdb.NewBoltStore(...)
        /home/oszika/go/pkg/mod/github.com/hashicorp/raft-boltdb@v0.0.0-20191021154308-4207f1bf0617/bolt_store.go:60
example/plugin.glob..func1()
        /tmp/example/plugin/main.go:10 +0x4a
main.main()
        /tmp/example/main.go:19 +0x176
exit status 2

### Workaround
Call syscall.Mmap in the main program.

**Comment by davecheney** [comment]
As an experiment can you try mmap'ing a file in the main program, not the plugin, you don't need to use the result, just call syscall.Mmap from func main.

**Comment by oszika** [comment]
Hi @davecheney ,

I called directly the Init() func in main. There is no problem. It seems wrong only for plugins.

**Comment by davecheney** [comment]
Thanks. Can you please update the issue description to include this change.

**Comment by oszika** [comment]
Yes

**Comment by davecheney** [comment]
Thank you, but that is not what I was suggesting.

I have a theory that the internal structure for tracking mmap allocations in the syscall package is not correctly initalised because it is not used in the main program. If you call syscall.Mmap from your main program, _not_ the plugin, then it will initalise the correct internal structures in the syscall package (or to be more specific, stop the linker stripping them out), and this may work around the problem.

**Comment by oszika** [comment]
Ok, sorry. I'am testing it.

**Comment by booss** [comment]
Hi,
I was able to reproduce using this code in plugin.go:
```
package main

import (
	"log"
	"os"
	"syscall"
)

var Init = func() {
	f, _ := os.Create("/tmp/temp")
	log.Println(syscall.Mmap(int(f.Fd()), 0, 42, syscall.PROT_READ|syscall.PROT_WRITE, syscall.MAP_SHARED))
}

func main() {}
```

**Comment by booss** [comment]
When I call Mmap directly from main:
```
package main

import (
	"log"
	"os"
	"syscall"
)

func main() {
	f, _ := os.Create("/tmp/temp")
	log.Println(syscall.Mmap(int(f.Fd()), 0, 42, syscall.PROT_READ|syscall.PROT_WRITE, syscall.MAP_SHARED))
}
```
I get this:
```
unexpected fault address 0x7ff9d0019000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7ff9d0019000 pc=0x499c96]

goroutine 1 [running]:
runtime.throw(0x4c56c9, 0x5)
	/usr/lib/go/src/runtime/panic.go:1117 +0x72 fp=0xc000070c60 sp=0xc000070c30 pc=0x432bf2
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:731 +0x2c8 fp=0xc000070c98 sp=0xc000070c60 pc=0x447848
fmt.(*pp).fmtBytes(0xc0000769c0, 0x7ff9d0019000, 0x2a, 0x2a, 0x76, 0x4c5868, 0x6)
	/usr/lib/go/src/fmt/print.go:477 +0x4b6 fp=0xc000070d50 sp=0xc000070c98 pc=0x499c96
fmt.(*pp).printArg(0xc0000769c0, 0x4aaf00, 0xc00000c030, 0x76)
	/usr/lib/go/src/fmt/print.go:696 +0x3b3 fp=0xc000070de8 sp=0xc000070d50 pc=0x49b6d3
fmt.(*pp).doPrintln(0xc0000769c0, 0xc000070f58, 0x2, 0x2)
	/usr/lib/go/src/fmt/print.go:1169 +0xb1 fp=0xc000070e58 sp=0xc000070de8 pc=0x49e411
fmt.Sprintln(0xc000070f58, 0x2, 0x2, 0x4ae600, 0x552f01)
	/usr/lib/go/src/fmt/print.go:281 +0x52 fp=0xc000070ea8 sp=0xc000070e58 pc=0x4982f2
log.Println(0xc000070f58, 0x2, 0x2)
	/usr/lib/go/src/log/log.go:329 +0x3f fp=0xc000070ee8 sp=0xc000070ea8 pc=0x4a047f
main.main()
	/home/alex/src/go/src/bolt1.16/main.go:11 +0x155 fp=0xc000070f88 sp=0xc000070ee8 pc=0x4a06d5
runtime.main()
	/usr/lib/go/src/runtime/proc.go:225 +0x256 fp=0xc000070fe0 sp=0xc000070f88 pc=0x435436
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000070fe8 sp=0xc000070fe0 pc=0x4645e1
exit status 2
```

**Comment by davecheney** [comment]
mmaping larger than the file will cause a SIGBUS, try mmaping /dev/zero.

**Comment by oszika** [comment]
In this case, If syscal.Mmap is called in the main file, and the plugin is used. There is no panic about syscall.Mmap. So, mapper.active is initialized.

**Comment by davecheney** [comment]
Thank you for confirming. I suspect this is some linker / deadcode initialisation oddity. I've marked this for investigation, someone from the linker team will pick it up in the US timezone.

**Comment by booss** [comment]
> mmaping larger than the file will cause a SIGBUS, try mmaping /dev/zero.

My bad, using "/dev/zero" works fine, thank you.

**Comment by oszika** [comment]
> Thank you for confirming. I suspect this is some linker / deadcode initialisation oddity. I've marked this for investigation, someone from the linker team will pick it up in the US timezone.

Ok thank you !

**Comment by networkimprov** [comment]
cc @ianlancetaylor

**Comment by cuiweixie** [comment]
i think this issue has been fixed by somehow!
using this version:
go version devel +23ffb5b9ae Sun Mar 28 03:27:04 2021 +0000 linux/amd64
it cannot be reproduced!

**Comment by oszika** [comment]
Yes indeed.
I confirm it's fixed using go1.16.3
