### ISSUE TITLE
x/website:https://golang.org/doc/code

### ISSUE THREAD

**Issue by ronaldpetty** [golang/go#44518]
Using https://golang.org/doc/code and Go 1.16.

The part where you use `go install` does not automatically download the remote package. What you see is in the document is:

```
$ go install example.com/user/hello
go: finding module for package github.com/google/go-cmp/cmp
go: downloading github.com/google/go-cmp v0.4.0
go: found github.com/google/go-cmp/cmp in github.com/google/go-cmp v0.4.0
```

What I got was:

```
$ go install example.com/user/hello
hello.go:7:2: no required module provides package github.com/google/go-cmp/cmp; to add it:
	go get github.com/google/go-cmp/cmp
```

After running `go get github.com/google/go-cmp/cmp`, rerunning produces:

```
$ go install example.com/user/hello
$
```

If I am correct, I am happy to update the document. If I am wrong, happy to learn why!

**Comment by Usarneme** [comment]
I am unable to reproduce the issue. Does this happen every time you enter the `go install...` command?

What are you seeing running `which go` and `go version` from the command line?
For example, I show: `/usr/local/go/bin/go` and `go version go1.16 darwin/amd64`

**Comment by ronaldpetty** [comment]
Thanks @Usarneme for trying. I just reran the entire document in 1.16 and its working. I suspect I must have messed up GO111 while messing around trying to confirm things. If I see again, will repost. Sorry about that.
