### ISSUE TITLE
go/types, types2: writeType does not invoke Qualifier when printing an unsafe.Pointer

### ISSUE THREAD

**Issue by cixel** [golang/go#44515]
Because `unsafe.Pointer` is a `*types.Basic`, the type stringifier uses a special case to print the package name:
```
case *Basic:
	if t.kind == UnsafePointer {
		buf.WriteString("unsafe.")
	}
```

As written, this does not allow a given Qualifier function to run and control how the package name is printed, which means that anything which wants to print something other than `"unsafe"` must do so by also special casing `unsafe.Pointer`.

Is there any reason not to use the Qualifier function in `writeType` when printing `unsafe.Pointer`? This would be a very quick change, but I wanted to make sure the current functionality isn't deliberate before opening a CL.

**Comment by findleyr** [comment]
This seems reasonable to me. Given that this logic predates https://golang.org/cl/11692 adding the Qualifier function, perhaps this was just an oversight.

CC @griesemer

**Comment by griesemer** [comment]
Thanks for pointing this out; I think @findleyr is correct, this looks like an oversight. Fix is pending.
