### ISSUE TITLE
The value of HeapAlloc  in runtime.MemStats is too smaller than RES in top command.

### ISSUE THREAD

**Issue by FakerGit** [golang/go#44527]
### What version of Go are you using (`go version`)?

<pre>
go 1.14

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build546006084=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you expect to see?
May the values of HeapAlloc and RES should be about the same size ? Or did I misunderstand the meaning？

### What did you see instead?
What I got from http://xxx/debug/pprof/heap?debug=1 :
```
# runtime.MemStats
# Alloc = 9233720
# TotalAlloc = 739456649232
# Sys = 2158662128
# Lookups = 0
# Mallocs = 6202925150
# Frees = 6202861652
# HeapAlloc = 9233720
# HeapSys = 2079162368
# HeapIdle = 2066374656
# HeapInuse = 12787712
# HeapReleased = 2063761408
# HeapObjects = 63498
# Stack = 1212416 / 1212416
# MSpan = 204816 / 3063808
# MCache = 6944 / 81920
# BuckHashSys = 1927739
# GCSys = 70965752
# OtherSys = 2248125
# NextGC = 13129152
# LastGC = 1614049133892415488
```

What I saw in top:
![image](https://user-images.githubusercontent.com/13702295/108810102-517c6700-75e5-11eb-92cc-b74c3f0ed87a.png)

----

Sorry in advance, I am not able to extract a runnable example at the moment as it is a little larger program I am debugging.
There is what I meet:
When encountering peak request periods, the memory used by the program skyrockets, but does not drop subsequently. At first, I think it may be caused by MADV_FREE. But I tried use a test program which will constantly request memory from the system and found no drop in the memory for program. 

I also tried `pprof` and found that heap in used was too small, only a few MB. I don't know where the rest of the memory is taken up.

Thank you for your time !

**Comment by davecheney** [comment]
Thank you for your issue. I suggest you review similar issues, https://github.com/golang/go/issues?q=is%3Aissue+is%3Aclosed+RSS and upgrade to Go 1.16.

**Comment by FakerGit** [comment]
> Thank you for your issue. I suggest you review similar issues, https://github.com/golang/go/issues?q=is%3Aissue+is%3Aclosed+RSS and upgrade to Go 1.16.
Thank you for the extremely quick response !
I'd like to confirm if it's because the OS doesn't actually reclaim the memory, so the RES shows that the program is still using so much memory. HeapReleased was almost equal to RES in top.

**Comment by davecheney** [comment]
Any difference between runtime.Memstats and what top reports is, sadly, top's problem.

**Comment by seankhliao** [comment]
`MADV_DONTNEED` only became default in 1.16 see [release notes](https://golang.org/doc/go1.16#runtime)

**Comment by FakerGit** [comment]
> Any difference between runtime.Memstats and what top reports is, sadly, top's problem.

So can I assume that HeapAlloc is close to the actual size of the physical system memory occupied by the program?

**Comment by FakerGit** [comment]
> `MADV_DONTNEED` only became default in 1.16 see [release notes](https://golang.org/doc/go1.16#runtime)

Sorry, I wrote it wrong, it should be MADV_FREE.

**Comment by davecheney** [comment]
> > Any difference between runtime.Memstats and what top reports is, sadly, top's problem.
> 
> So can I assume that HeapAlloc is close to the actual size of the physical system memory occupied by the program?

Sadly not, if part of the process has been swapped out the RSS, resident size, will be decreased, but RSS should not be larger than heapalloc.

**Comment by FakerGit** [comment]
If HeapInuse is 100MB and HeapReleased are 900MB, the program memory on the system shows 1G. Is it because the kernel is only reclaiming the memory freed by MADV_FREE under memory pressure? The system doesn't really get the memory back?

**Comment by davecheney** [comment]
>  Is it because the kernel is only reclaiming the memory freed by MADV_FREE under memory pressure? 

The kernel will often ignore madvise calls unless the system is under memory pressure. If memory has been marked as unneeded by the scavenger the kernel may take it back, but only if it needs it. Go 1.16 does use a stronger version of MADV_FREE (if supported), but again, the kernel can ignore it if it doesn't need memory at the time.

**Comment by FakerGit** [comment]
> > Is it because the kernel is only reclaiming the memory freed by MADV_FREE under memory pressure?
> 
> The kernel will often ignore madvise calls unless the system is under memory pressure. If memory has been marked as unneeded by the scavenger the kernel may take it back, but only if it needs it. Go 1.16 does use a stronger version of MADV_FREE (if supported), but again, the kernel can ignore it if it doesn't need memory at the time.

Got it. I will upgrade to Go 1.16 and use MADV_DONTNEED. Thank you very much for your help !
