### ISSUE TITLE
syscall/zsyscall_windows.go CreateFileMapping may be missing one case if the object exists before the function call

### ISSUE THREAD

**Issue by VolcanoKing** [golang/go#44539]
**This is the description in the Microsoft API Documentation:**

**Return value**
If the function succeeds, the return value is a handle to the newly created file mapping object.

If the object exists before the function call, the function returns a handle to the existing object (with its current size, not the specified size), and **GetLastError** returns **ERROR_ALREADY_EXISTS**.

If the function fails, the return value is NULL. To get extended error information, call GetLastError.

https://docs.microsoft.com/zh-cn/windows/win32/api/memoryapi/nf-memoryapi-createfilemappingw

**I think we should write it this way to handle errors, for example.**
```
func CreateFileMapping(...) {
	...
	handle = Handle(r0)
	err = errnoErr(e1)
	return
}
```

**Comment by networkimprov** [comment]
cc @alexbrainman @zx2c4

**Comment by zx2c4** [comment]
Fixed. Sending CL.

**Comment by zx2c4** [comment]
https://go-review.googlesource.com/c/sys/+/297332

**Comment by VolcanoKing** [comment]
In https://golang.org/cl/297332 windows/zsyscall_windows.go, I find that CreateMutex and CreateEvent had the same problem.
@alexbrainman @zx2c4 @gopherbot

**Comment by zx2c4** [comment]
Thanks. I've fixed those too in the same CL.
