### ISSUE TITLE
how to turn on go.sum processing in 1.16 like in 1.15

### ISSUE THREAD

**Issue by raydac** [golang/go#44531]
I have projects tuned for module system for 1.15, and tried to tune them to be built under 1.16 but there are major changes in module mode processing. I found that it is possible to turn off module mode with GO111MODULE=auto. But in my modules where I use some external packages, 1.16 complains about go.sum missing. Do you have provided any back-compatibility way to use 1.16 instead of 1.15? I was trying to play with GONOSUM and GOSUM but without success. How can I disable check of missing go.sum?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
