### ISSUE TITLE
x/playground: 'timeout running program' on many of the tour.golang examples 

### ISSUE THREAD

**Issue by nir-coh** [golang/go#44537]
### What version of Go are you using (`go version`)?

<pre>
$ official go playground version (can't tell because its giving me timeouts)

</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

Not relevant as I'm trying to run the tour.golang examples or just play.golang

### What did you do?

Tried running any of the code examples on the golang tour, for example:
https://tour.golang.org/concurrency/1

### What did you expect to see?

The code running successfully.

### What did you see instead?
<pre>
timeout running program
Go build failed.
</pre>

This has been a reoccurring problem over the last days. Sometimes I am able to run the code just fine but then it stops working for different periods of time.

**Comment by jimen0** [comment]
Could be related to #44343 if tour page uses 1.16.

**Comment by bcmills** [comment]
@golang/release

**Comment by toothrot** [comment]
Fixed by restarting sandbox instances that were OOM. We're still evaluating a root-cause.

**Comment by peterhellberg** [comment]
This seems to still be an issue. More often than not the playground times out. 

The situation is also especially bad when it tries to  download third party modules.

**Comment by dmitshur** [comment]
> Is there a tracking issue for this problem?

Yes, I suspect this is #44822.
