### ISSUE TITLE
performance issue when return a pointer

### ISSUE THREAD

**Issue by xing0821** [golang/go#44540]
### What version of Go are you using (`go version`)?

<pre>
I try to use  go version go1.15.8 linux/amd64. and go1.12.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/root/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/etcd-3.4.3/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build352582606=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
 I use ETCD(https://github.com/etcd-io/etcd/) and try to figure out a random performance issue, and I get some pprof trace like that:
```
      50ms       50ms    304:func (ki *keyIndex) findGeneration(rev int64) *generation {
      30ms       30ms    305:	lastg := len(ki.generations) - 1
         .          .    306:	cg := lastg
         .          .    307:
         .          .    308:	for cg >= 0 {
     100ms      100ms    309:		if len(ki.generations[cg].revs) == 0 {
         .          .    310:			cg--
         .          .    311:			continue
         .          .    312:		}
     170ms      170ms    313:		g := ki.generations[cg]
      10ms       10ms    314:		if cg != lastg {
      80ms       80ms    315:			if tomb := g.revs[len(g.revs)-1].main; tomb <= rev {
         .          .    316:				return nil
         .          .    317:			}
         .          .    318:		}
      30ms       30ms    319:		if g.revs[0].main <= rev {
     4.64s      4.64s    320:			return &ki.generations[cg]
         .          .    321:		}
         .          .    322:		cg--
         .          .    323:	}
         .          .    324:	return nil
         .          .    325:}
```
```
ROUTINE ======================== cmpbody in /usr/local/go/src/internal/bytealg/compare_amd64.s
     6.81s      6.81s (flat, cum)  8.34% of Total
         .          .     29://   R9 = address of output word (stores -1/0/1 here)
         .          .     30:TEXT cmpbody<>(SB),NOSPLIT,$0-0
         .          .     31:	CMPQ	SI, DI
         .          .     32:	JEQ	allsame
         .          .     33:	CMPQ	BX, DX
      10ms       10ms     34:	MOVQ	DX, R8
      30ms       30ms     35:	CMOVQLT	BX, R8 // R8 = min(alen, blen) = # of bytes to compare
         .          .     36:	CMPQ	R8, $8
         .          .     37:	JB	small
         .          .     38:
      10ms       10ms     39:	CMPQ	R8, $63
         .          .     40:	JBE	loop
         .          .     41:	CMPB	internal∕cpu·X86+const_offsetX86HasAVX2(SB), $1
         .          .     42:	JEQ     big_loop_avx2
         .          .     43:	JMP	big_loop
         .          .     44:loop:
      60ms       60ms     45:	CMPQ	R8, $16
         .          .     46:	JBE	_0through16
      30ms       30ms     47:	MOVOU	(SI), X0
     5.21s      5.21s     48:	MOVOU	(DI), X1
```
  and I try to disable GC by GOGC=off, but the problem still exist
### What did you expect to see?
 I want to know how to reduce the latency with get pointer and MOVOU instruction? and why.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
