### ISSUE TITLE
x/pkgsite: github.com/rk0cc/restcachy has been deleted

### ISSUE THREAD

**Issue by rk0cc** [golang/go#44547]
### What is the URL of the page with the issue?
https://pkg.go.dev/github.com/rk0cc/restcachy
 
 
### What is your user agent?
 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36 Edg/88.0.705.74

 
 
 
### Screenshot
 N/A

 
 
 
### What did you do?
This package has been deleted recently

 
 
 
### What did you expect to see?
github.com/rk0cc/restcachy's information of pkg.go.dev has been removed
 
 
### What did you see instead?
The content still existed

**Comment by jamalc** [comment]
Done.

**Comment by rk0cc** [comment]
Thank you, @jamalc
