### ISSUE TITLE
cmd/asm,cmd/compile,cmd/link,cmd/objdump: ppc64 ISA 3.1 support

### ISSUE THREAD

**Issue by pmur** [golang/go#44549]
This is a container task for implementing support for the upcoming POWER10 processor.

ISA 3.1 documentation can be found [here](https://ibm.ent.box.com/s/hhjfw0x0lrbtyzmiaffnbxh2fuo0fog0).

Notable additions we would like to support in golang:

* More crypto instructions
* Support for PC relative load/store/add immediate
* Prefixed instructions (two word instructions) for larger load/store/add immediate

The latter two features will require a bit of preparation work in the ppc64 backend. Go 1.17 development will focus on preparation work.

**Comment by laboger** [comment]
There is work being done to provide support in the assembler and disassembler on ppc64x for some instructions in ISA 3.1. The Go compiler will not be generating any of these instructions yet but they can be assembled and verified that they assemble to the correct instruction bits. Based on the recent comment in golang-dev about the Go 1.17 freeze, should this be marked as part of the Go 1.17 milestone?

**Comment by pmur** [comment]
I would like to get the cmd/objdump support in for 1.17.  It would be nice to get support for aligning prefixed opcodes in cmd/asm, but that is not a release blocker.

**Comment by Robert-M-Muench** [comment]
A bit OT: Does/Can the Go compiler generate instructions for float128 FPU calculations on this architecture? I wonder because there is no float128 type. One of the big advantages of this architecture is the native float128 support.

**Comment by pmur** [comment]
I think this support is effectively complete with the release of Go 1.21.
