### ISSUE TITLE
x/pkgsite: heading parsed incorrectly in documentation overview

### ISSUE THREAD

**Issue by julieqiu** [golang/go#44558]
### What is the URL of the page with the issue?

https://pkg.go.dev/cmd/go/#hdr-Import_path_checking is the closest anchor link.

https://pkg.go.dev/cmd/go/#hdr-Modules__module_versions__and_more is the expected URL.
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
 
### Screenshot
 

![image](https://user-images.githubusercontent.com/5943521/108909171-36642400-75f2-11eb-9d47-5abe9315eb05.png)
 
 
### What did you expect to see?
 
`Modules, module versions, and more` is a heading, as is the case on https://golang.org/cmd/go/#hdr-Modules__module_versions__and_more.

![image](https://user-images.githubusercontent.com/5943521/108909344-6f9c9400-75f2-11eb-8490-4a43ed452938.png)

### What did you see instead?

`Modules, module versions, and more` is not a heading.

/cc @jba @jamalc

**Comment by ya5u** [comment]
@julieqiu I'm going to work on this issue
