### ISSUE TITLE
Can change "ModifyResponse func(*http.Response) error" to "ModifyResponse func(*http.Response, *http.Request) error"  on net/http/httputil.ReverseProxy?

### ISSUE THREAD

**Issue by runner-mei** [golang/go#44563]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=off
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\meifakun\AppData\Local\go-build
set GOENV=C:\Users\meifakun\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=d:\developing\go\hengwei\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=d:\developing\go\hengwei\;d:\developing\go\meijing\tpt_vendor
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=d:\tools\go_amd64
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=d:\tools\go_amd64\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\mei\AppData\Local\Temp\go-build167834566=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I need set Cookie to Response by ModifyResponse.

like:

````golang
proxy.ModifyResponse = func(resp *http.Response, req *http.Request) error {
      switch req.URL.Path {
         case strings.HasPrefix( req.URL.Path, "/xxx"):
               setCookie(resp)
             .......
      }
}
````

### What did you expect to see?

	ModifyResponse func(*http.Response) error

### What did you see instead?
	ModifyResponse func(*http.Response, *http.Request) error

**Comment by runner-mei** [comment]
Or add a new field to net/http/httputil.ReverseProxy

ModifyResponseEx func(*http.Response, *http.Request) error

**Comment by seankhliao** [comment]
http.Response includes a Request field

**Comment by runner-mei** [comment]
Yes
