### ISSUE TITLE
x/pkgsite: Remove some packages in pkg.go.dev 

### ISSUE THREAD

**Issue by WiFeng** [golang/go#44561]
Remove packages, as follow:

github.com/WiFeng/go-sky/sky

and 
github.com/WiFeng/go-sky/sky/*
or
github.com/WiFeng/go-sky/sky/grpc
github.com/WiFeng/go-sky/sky/buffer
github.com/WiFeng/go-sky/sky/middleware
github.com/WiFeng/go-sky/sky/transport/http
github.com/WiFeng/go-sky/sky/transport/redis
github.com/WiFeng/go-sky/sky/pprof
github.com/WiFeng/go-sky/sky/sql
github.com/WiFeng/go-sky/sky/transport/grpc
github.com/WiFeng/go-sky/sky/transport/sql

thanks~~

**Comment by jamalc** [comment]
Done.
