### ISSUE TITLE
proposal: cmd/vet: check for `iterator variable reference`

### ISSUE THREAD

**Issue by FireFart** [golang/go#44587]
Hi,
I wanted to make a feature request as this happens way too often and results in strange errors which are hard to debug: The iterator variable reference (https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable) should be reported by `go vet`.

I think this would increase code quality a lot if those errors could be reported by analyzing the code.

**Comment by ianlancetaylor** [comment]
Dup of #16520.
