### ISSUE TITLE
access: give egonelbre submit permissions

### ISSUE THREAD

**Issue by egonelbre** [golang/go#44582]
Request to have access for submitting changes.

Made due to a request: https://go-review.googlesource.com/c/go/+/281232/8#message-a6b294d5af71e7b0f4042573182cec65e4d9c2ec

**Comment by josharian** [comment]
That request was actually intended to be for you to get submit permissions. :) Sorry for the ambiguity.

**Comment by egonelbre** [comment]
Fixed the PR :D.

**Comment by toothrot** [comment]
We're not comfortable moving forward with this at this time. This is a very sensitive permission, and we want to make sure we're making the right balance between the risk and the convenience of removing friction. Right now it doesn't seem like frequency or waiting on submit times is as big of an issue, but we're happy to reconsider if you run into problems in the future, or if you find yourself submitting CLs more frequently and it becomes a major inconvenience.

Thank you so much for your contributions.
