### ISSUE TITLE
gomobile http request crashes app

### ISSUE THREAD

**Issue by bramvbilsen** [golang/go#44590]
### What version of Go are you using (`go version`)?

<pre>
go version go1.15.8 windows/amd64
</pre>

### What did you do?
I am trying to send some data to a webserver before the app starts. I am using the basic example app template included in gomobile. I added the following code at the start of main:

```
client := &http.Client{}
req, _ := http.NewRequest("GET", "192.168.0.124:8000/log", strings.NewReader("TEST"))
client.Do(req)
```
I inserted it at the start of main:
```
func main() {
	client := &http.Client{}
	req, _ := http.NewRequest("GET", "192.168.0.124:8000/log", strings.NewReader("TEST"))
	client.Do(req)
	app.Main(func(a app.App) {
                ...
        }
        ....
}
```

### What did you expect to see?
A log on my webserver and the app not crashing.

### What did you see instead?
No log on my webserver and the app crashes.

**Comment by seankhliao** [comment]
don't ignore errors

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
