### ISSUE TITLE
mime: Add mime type for avif image file format

### ISSUE THREAD

**Issue by amittal-quot** [golang/go#44602]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/amittal/Library/Caches/go-build"
GOENV="/Users/amittal/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/amittal/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/amittal/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xt/2rbf0kx520745mdw84t5ztldq8b1dr/T/go-build1199050817=/tmp/go-build -gno-record-gcc-switches -fno-common"</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Build static server to serve images

### What did you expect to see?

AVIF images should have correct mime-type

### What did you see instead?
AVIF images do not have correct mime-type

I had created a Code review for change at https://go-review.googlesource.com/c/go/+/256478. At the time IANA list(https://www.iana.org/assignments/media-types/media-types.xhtml#image) did not include AVIF, but is included now.

I don't understand Gerrit well, So recreating here.

**Comment by odeke-em** [comment]
Thank you for filing this bug @amittal-quot, and welcome to the Go project! Thanks for the triage @seankhliao.

@amittal-quot we only add mime patterns that are included officially included and tabled up by the Web Hypertext Application Technology Working Group (WHATWG) and in https://mimesniff.spec.whatwg.org/#matching-an-image-type-pattern. There isn’t much the Go project can do before that pattern is sniff specified  by the WHATWG, and you can take a look at their issues per https://github.com/whatwg/mimesniff.

**Comment by seankhliao** [comment]
@odeke-em I assumed this would be accepted based on the activity today in the linked [CL 256478](http://golang.org/cl/256478)

**Comment by odeke-em** [comment]
Certainly for sniffing content in net/http as that’s where we enter mine
sniff signatures, we need a WHATWG signature first. If your change isn’t
for sniffing content types then perhaps my objection doesn’t apply.

**Comment by amittal-quot** [comment]
My change is getting the mime type for file using file using extension. In the patchset it was mentioned that mime need to be included by IANA list.

**Comment by amittal-quot** [comment]
I have changes the commit message, Is there any other change needed
