### ISSUE TITLE
this is about Go question of version 

### ISSUE THREAD

**Issue by E-c-h-o-Go** [golang/go#44606]
Since there is a possibility that there will be no Go 2 version, but continue with Go 1.X version, is it possible to change the version number to Go X?

For example Go 10 -> Go 10.1-> Go 10.1.2

Go 10 -> Go 11 -> Go 12

Or Go 2021 -> Go 2022
 
Thank you

**Comment by davecheney** [comment]
For what benefit?

**Comment by E-c-h-o-Go** [comment]
> For what benefit?

Pleasing to the eye 😄

**Comment by mdlayher** [comment]
I don't think it is realistic that the entire project versioning scheme would change at this point. I am going to close this issue.
