### ISSUE TITLE
x/pkgsite: Broken links for custom go-source tags (regression)

### ISSUE THREAD

**Issue by albertito** [golang/go#44607]
### What did you do?

Navigate to https://pkg.go.dev/blitiri.com.ar/go/spf (or any blitiri.com.ar package).

Click on any type or function name, or any of the *source files*.

### What did you expect to see?

I expected to be taken to the corresponding source page, e.g. https://blitiri.com.ar/git/r/spf/b/master/t/f=spf.go.html#line-49

### What did you see instead?

The links are broken because `{dir}` is not being replaced correctly.

### Context and additional information

https://blitiri.com.ar is my personal page, where I host my git and go repositories.

The git web viewer is [git-arr](https://blitiri.com.ar/p/git-arr/), and has been running fine for years.

I create the https://blitiri.com.ar/go/ remote import path by hand for all my Go packages/modules. They use the meta tags as follows:

```html
<meta name="go-import"
  content="blitiri.com.ar/go/log git https://blitiri.com.ar/repos/log" />
<meta name="go-source"
  content="blitiri.com.ar/go/log https://godoc.org/blitiri.com.ar/go/log https://blitiri.com.ar/git/r/log/b/master/t/{dir} https://blitiri.com.ar/git/r/log/b/master/t/{dir}/f={file}.html#line-{line}" />
```

These `go-import` meta tags have been working fine for years, and worked well in godoc.org and (IIRC) also in pkg.go.dev at least at some point.

I think what's happening is that `{dir}` is not being expanded correctly, and instead `{file}` contains the full path.

As an example, if you navigate to pgd's view of [blitiri.com.ar/go/chasquid/internal/safeio](https://pkg.go.dev/blitiri.com.ar/go/chasquid@v0.0.0-20201122093508-78df715a028a/internal/safeio), then click on any of the links, you can see they're broken because they are like this:

```
https://blitiri.com.ar/git/r/chasquid/b/master/t/%7bdir%7d/f=internal/safeio/safeio.go.html#line-26
```

Note how `{file}` is being expanded to `internal/safeio/safeio.go.html`, and `{dir}` being expanded to `{dir}` (sic).

Instead, `{dir}` should be expanding to `internal/safeio/`, and `file` to `safeio.go` as per the [spec](https://github.com/golang/gddo/wiki/Source-Code-Links) and historical behaviour.

This is probably related to issue #40477 in some way.

Please let me know if you need any additional information, thanks!

**Comment by jamalc** [comment]
This does look related. @jba should we close in favor of or merge this with #40477.

**Comment by jba** [comment]
I looked at git-arr to try to figure this out myself, but I didn't see how to link to a file or directory with a tag. I also don't see how to get the raw bytes of a file, which isn't strictly necessary but is used to generate the proper img URLs in readmes.

**Comment by jba** [comment]
Technically you are correct: that your links don't work with master is a bug. On the other hand, linking to master when the version is v1.2.3 is not a great user experience.

Why don't I make the master links work now, and when you have upgraded your software to handle tags and commits, let me know and I will generalize.

We understand the desire to have a more federated scheme, but we just don't have one that we're happy with.

**Comment by albertito** [comment]
> Technically you are correct: that your links don't work with master is a bug. On the other hand, linking to master when the version is v1.2.3 is not a great user experience.
> 
> Why don't I make the master links work now, and when you have upgraded your software to handle tags and commits, let me know and I will generalize.

SGTM, thanks!

Please let me know when the fix is in and I can check the links by hand to check it works.

I'll let you know once git-arr supports views of tags (and maybe arbitrary commits, although it being a static generator that might not be practical).

Thanks again!

**Comment by jba** [comment]
@albertito This should be live.

**Comment by albertito** [comment]
Thanks! I can see that it works for my particular site now, thanks, I appreciate the workaround :)

Has the regression for the general case been fixed though? What I mentioned above (https://github.com/golang/go/issues/44607#issue-816319006 and https://github.com/golang/go/issues/44607#issuecomment-795317951) affects all sites relying on the go-source spec, and IIUC you committed to continue to support.

Thanks!

**Comment by jba** [comment]
Sorry I didn't respond to your last comment, but I think I answered your question at https://github.com/golang/go/issues/44607#issuecomment-795684007.
