### ISSUE TITLE
GO.High Stream Security 

### ISSUE THREAD

**Issue by BOOGLE360** [golang/go#44605]
[LICENSE.txt](https://github.com/golang/go/files/6041952/LICENSE.txt)

### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go

 env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by davecheney** [comment]
Please stop.
