### ISSUE TITLE
x/tools/gopls: issue importing standard package in vscode

### ISSUE THREAD

**Issue by sickmon** [golang/go#44616]
Hello,

While writing code in VSCode, if I use a new package, that same is getting added to import package list as expected. But the newly visible package in import gives below error and then automatic suggestion for the package used somewhere else will also not show anything. Only solution is to close vscode gui and open again. I have also enabled experimental features but no luck.
..
could not import fmt (no required module provides package "fmt")compiler
..

Please let me know if it is a bug or another issue. Also, if any other information is needed. 
![gopls](https://user-images.githubusercontent.com/68516344/109208319-2ace5400-77d0-11eb-93d8-7bf5720a0550.jpg)

**Comment by stamblerre** [comment]
Can you please share your `gopls` logs? Information on how to capture them can be found [here](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information).

**Comment by sickmon** [comment]
Logs Attached. Please let me know if you need something else. 
[44616_logs.txt](https://github.com/golang/go/files/6048568/44616_logs.txt)

**Comment by hyangah** [comment]
Thanks, but we wanted to have the gopls log described in the [Collect gopls information](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information) section. 

From what you've shared I see that you are currently working in GOPATH mode with multiple directories in GOPATH (`/home/vagrant/golib:/home/vagrant/code`). 

Is the project directory under /home/vagrants/code/src and you opened the vscode from the /home/vagrants/code directory?
And, if possible I strongly recommend updating the go to 1.16.
1.15.1 is pretty outdated and lacks important security fixes.

**Comment by sickmon** [comment]
Hi ,

thanks for your suggestion. I updated go to 1.16 and its working as expected.

Thank you again.
