### ISSUE TITLE
go:embed is doing weird replacements on embedded byte arrays

### ISSUE THREAD

**Issue by Markcial** [golang/go#44620]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Not sure on how to try it, should I do a build from master?

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
</pre></details>

### What did you do?

create a sample file `test.txt`:

```
x % 8
```

create a go file:

```
package main

import (
	_ "embed"
	"fmt"
	"net/http"
)

//go:embed test.txt
var testBfr []byte

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, string(testBfr))
	})
	http.ListenAndServe(":8080", nil)
}
```

### What did you expect to see?

The server should return `x % 8`

### What did you see instead?

Server is returning `x %!(NOVERB)` instead

**Comment by seankhliao** [comment]
you use a printf function
