### ISSUE TITLE
cmd/go: do not compile test package if non-test can't build

### ISSUE THREAD

**Issue by rsc** [golang/go#44624]
I keep getting output like this from `go test`:

```
% go test ./...
?   	golang.org/x/website	[no test files]
# golang.org/x/website/internal/godoc
internal/godoc/examplefuncs.go:24:14: page.Value undefined (type *Page has no field or method Value)
# golang.org/x/website/internal/godoc [golang.org/x/website/internal/godoc.test]
internal/godoc/examplefuncs.go:24:14: page.Value undefined (type *Page has no field or method Value)
```

It's just noise to print the same errors twice.

An easy way to fix this would be to make the test version of the package have the non-test version as a (not strictly necessary) dependency. Then if the build of the non-test version fails, the build of test version won't be attempted.

/cc @jayconrod @matloob

**Comment by robpike** [comment]
I can't find the previous issue but I brought this up some time ago. If you can find it, what was the resolution? Or did it come back somehow?

**Comment by ALTree** [comment]
@robpike This one? f0fef323833b9b060024507a3229fa7bf9b523a8

**Comment by robpike** [comment]
Yes, which points to this one: https://github.com/golang/go/issues/5679
