### ISSUE TITLE
x/tools/gopls: add the nilness analysis 

### ISSUE THREAD

**Issue by ainar-g** [golang/go#44627]
The [nilness] analysis pass can detect some absurd conditions, like checking a value that has already been proven non-nil against nil.  This is especially useful during refactoring, when a new nil check appears before an existing one.  I think that this analysis would be a good fit for the `gopls` analysis suite.  If I recall correctly, it uses SSA, so it should probably be disabled by default.

If there are no objections, I am ready to send a CL soon-ish.

[nilness]: https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/nilness/

**Comment by findleyr** [comment]
Note that nilness was removed in https://golang.org/cl/219203, specifically because of the resources that SSA consumes.

That said, it makes sense to have available yet disabled by default.

**Comment by ainar-g** [comment]
Thanks for the review!
