### ISSUE TITLE
Compile-time code execution: func build()

### ISSUE THREAD

**Issue by manoeldesouza** [golang/go#44633]
## Summary
Embedding files into a Go executable with "embed" package is a strong feature implemented in version 1.16. In this issue, I propose some evolution of the concept to enable not only embedding files as possible now, but any type of arbitrary code execution at compile time.

## Concept
Current capability to embed files is based on a compiler directive which "magically" populates a variable as below:
```
//go:embed sample.txt
var text string
```

In this proposal I suggest embedding files would be executed from within a function named `func build()`. A comparison with "embed" package is below

```
var text string

func build() {
    content, err := ioutil.ReadFile("sample.txt")
    if err != nil {
        log.Fatal(err) // This becomes a compile-time error
    }

    text = string(content)
}
```

The `func build()` would operate similarly as existing with `func init()`. But while init() is a run-time preliminary execution code, build() would be run at compile-time only and pre-populate global variables.

A build function would enable not only to embed files, but also to apply calculations which would then populate global variables at compile time. Example of use case for such feature would be the calculation of CRC tables, among other big datasets which should be ready by compile time.

## Benefits
- Arbitrary code execution enables developer to express any time of code as build-time execution;
- Wider use-case then only embedding files;
- Consistency with other initialization function `func init()`;
- Prevent run-time impact (delay) with init functions doing preparation work;

## Risks / Impacts
This feature may conflict with existing code depending on package-level build() function, being used for different purposes.

**Comment by ALTree** [comment]
One of the core design goals of Go it that even large codebases should compile fast. Arbitrary code execution at compile time is *very* antithetical to that.

**Comment by ianlancetaylor** [comment]
Arbitrary code execution at build time would be a security hole when building third party packages.  People generally understand that running code from third party packages can be a security risk, and they take appropriate mitigations like running in a container.  People are much less likely to understand that merely compiling third party code is a security risk.

**Comment by Jictyvoo** [comment]
> Arbitrary code execution at build time would be a security hole when building third party packages. People generally understand that running code from third party packages can be a security risk, and they take appropriate mitigations like running in a container. People are much less likely to understand that merely compiling third party code is a security risk.

Maybe compile-time code execution can be behind an environment variable, that allows it or not for third-party packages. And will be allow by default for compiling current package.
