### ISSUE TITLE
cmd/link: fail to build when using time/tzdata on ARM

### ISSUE THREAD

**Issue by cherrymui** [golang/go#44639]
Branch out from https://github.com/golang/go/issues/44073#issuecomment-778854298

```
GOARCH=arm go build -tags timetzdata ./path/to/app
time/tzdata.init.0: unresolved inter-package jump to time.registerLoadFromEmbeddedTZData(time) from time/tzdata
```

This is fixed in CL https://golang.org/cl/292490 , but that didn't get into Go 1.16 release. Filing a separate issue so we can make a backport.

**Comment by cherrymui** [comment]
Fixed on tip already.

**Comment by cherrymui** [comment]
@gopherbot please backport this to Go 1.16. This causes programs fail to build without easy workaround.

**Comment by dmitshur** [comment]
@cherrymui Does this issue also exist in Go 1.15, or only 1.16?

**Comment by cherrymui** [comment]
I'm not really sure. By the logic of the code it probably could happen, but I'm not sure if it could be triggered by simply using tzdata package (as of Go 1.16) or only with some contrived cases.

**Comment by cherrymui** [comment]
@dmitshur I can reproduce with Go 1.15. Backport CL sent.
