### ISSUE TITLE
cmd/go: mod vendor nukes existing vendor directory

### ISSUE THREAD

**Issue by tamird** [golang/go#44646]
Running `go mod vendor` in the presence of a directory called "vendor" is dangerous. In particular, if such a directory contains git repositories, they are unceremoniously deleted. It'd be nice to have a best-effort check in place before performing destructive operations. Perhaps if "vendor" exists but "vendor/modules.txt" does not, the command should issue a warning.

**Comment by seankhliao** [comment]
possibly a duplicate of #26366 #44119

**Comment by bcmills** [comment]
Duplicate of #44646

**Comment by tamird** [comment]
Seems you marked it a duplicate of itself.

**Comment by bcmills** [comment]
Oops! Sorry, will fix.

**Comment by bcmills** [comment]
Duplicate of #44119

**Comment by matveynator** [comment]
Just nuked my two days work on the module....
Surprize!
