### ISSUE TITLE
x/pkgsite: support markdown-style links

### ISSUE THREAD

**Issue by tbpg** [golang/go#44645]
### What is the URL of the page with the issue?
 
All of them. 
 
### What is your user agent?

N/A.
 
### What did you do?
 
Have a markdown-style link in my GoDoc. For example:

```
Check out the awesome [documentation](https://pkg.go.dev).
```

### What did you expect to see?
 
Check out the awesome [documentation](https://pkg.go.dev).
 
### What did you see instead?

Check out the awesome \[documentation\](https://pkg.go.dev).

cc @julieqiu

**Comment by fzipp** [comment]
AFAIK doc comments for Go code are intentionally kept markup-free.

"[...] nor must they have their own machine-readable syntax (as with Javadoc). Godoc comments are just good comments, the sort you would want to read even if godoc didn't exist." https://blog.golang.org/godoc

**Comment by tbpg** [comment]
Closing in favor of the discussion in #48305.
