### ISSUE TITLE
enhancement of data type assertion compatibility

### ISSUE THREAD

**Issue by focusonline** [golang/go#44657]
If is it possible to get assertion more simple and compatible?
because larger data type can cover any type smaller than it.
for example, int64 can cover all integer type and uint64 can cover all unsigned integer type and float64 can cover float32,
so the below code is reasonable
```go
   var i inteface{}
   i = int8(0) // assign uint 0  to i
   j := i.(int64) // anyway variable i is an integer, but actually,"interface {} is int8, not int64" will be thrown
```
since generic type is taken into account, the above enchancement is worth considering.
thanks for any improvement of golang, it is awesome.

**Comment by ianlancetaylor** [comment]
I recommend using `reflect.ValueOf(i).Int()`.

**Comment by focusonline** [comment]
> I recommend using `reflect.ValueOf(i).Int()`.

Thanks for reply, it is a good solution, but I still wonder, if reflect has worse performance than assertion? actually, we do not need to squash the code for extreme performance, just being curious.
Thank you!  It resolved my problem already. the type is in a scope, and converted into the maximal type of it.
