### ISSUE TITLE
x/tools/gopls: format constant time.Duration in hover tooltip

### ISSUE THREAD

**Issue by ShoshinNikita** [golang/go#44667]
The current hover tooltip for `const X time.Duration` is not very useful because it displays nanoseconds:

![image](https://user-images.githubusercontent.com/30220965/109386418-88b38680-790b-11eb-88a8-9363b373e08e.png)

I guess it's not possible to display an actual declaration (`20 * time.Second` in this example). But I think it would be a good solution to display formatted duration as a comment. Something like this:

```go
const duration time.Duration = 20000000000 // 20s
```

**Comment by muirdm** [comment]
> I guess it's not possible to display an actual declaration (20 * time.Second in this example).

It should be possible to do that. I wonder if that might be the most useful thing in general:

```go
const flagA = 1
const flagB = 2
// Showing "3" isn't very useful. Showing "flagA | flagB" might be useful.
const someMask = flagA | flagB

const durA = 1*time.Minute
const durB = 1*time.Second
// Showing nanoseconds is not helpful. Showing "59s" might be helpful, but showing "durA - durB" might have the most meaning.
const timeout = durA - durB
```

**Comment by ShoshinNikita** [comment]
I agree `const someMask = flagA | flagB` can be useful. I also think `const someMask = flagA | flagB // 3` is even better
