### ISSUE TITLE
doc: Go 1.16 Release Notes has a broken golang.org link

### ISSUE THREAD

**Issue by LukeShu** [golang/go#44661]
In https://golang.org/doc/go1.16 where it says

> `ReadDir` => `os.ReadDir` (note: returns a slice of `os.DirEntry` rather than a slice of `fs.FileInfo`)

the hyperlink on `fs.FileInfo` goes to https://golang.org/pkg/fs/#FileInfo rather than to https://golang.org/pkg/io/fs/#FileInfo (the `io/` is missing).

**Comment by ianlancetaylor** [comment]
Thanks for reporting this.  It is already fixed by https://golang.org/cl/294669.  Should be fixed when the website is pushed.
