### ISSUE TITLE
all: failed to run make.bash on darwin arm64

### ISSUE THREAD

**Issue by cuonglm** [golang/go#44675]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```
$ GOROOT_BOOTSTRAP=/Users/cuonglm/sdk/go1.16 ./make.bash
Building Go cmd/dist using /Users/cuonglm/sdk/go1.16. (go1.16 darwin/arm64)
Building Go toolchain1 using /Users/cuonglm/sdk/go1.16.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
go tool dist: FAILED: /Users/cuonglm/sources/go/pkg/tool/darwin_arm64/go_bootstrap install -gcflags=all= -ldflags=all= -i cmd/asm cmd/cgo cmd/compile cmd/link: signal: segmentation fault
```

### What did you expect to see?

`make.bash` run successfully.

### What did you see instead?

`make.bash` failed after commit 5ff7ec98b7727b3641df25200345b1aa50b6ff35

cc @dr2chase @jeremyfaller @cherrymui

**Comment by cuonglm** [comment]
FYI, using the bootstrap binary produces the same error:

```
GOROOT_BOOTSTRAP=$(pwd)/../../go-darwin-arm64-bootstrap ./make.bash
```

**Comment by Rajalakshmi-Girish** [comment]
Also observed on ppc64le:
```
[root@rajalakshmi-workspace ~]# go version
go version go1.15.8 linux/ppc64le
[root@rajalakshmi-workspace ~]# git clone https://github.com/golang/go.git
Cloning into 'go'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 463350 (delta 2), reused 1 (delta 1), pack-reused 463321
Receiving objects: 100% (463350/463350), 238.53 MiB | 26.31 MiB/s, done.
Resolving deltas: 100% (370164/370164), done.
Checking out files: 100% (9735/9735), done.
[root@rajalakshmi-workspace ~]# cd go/src/
[root@rajalakshmi-workspace src]# ./make.bash
Building Go cmd/dist using /usr/local/go. (go1.15.8 linux/ppc64le)
Building Go toolchain1 using /usr/local/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
go tool dist: FAILED: /root/go/pkg/tool/linux_ppc64le/go_bootstrap install -gcflags=all= -ldflags=all= -i cmd/asm cmd/cgo cmd/compile cmd/link: signal: segmentation fault (core dumped)
[root@rajalakshmi-workspace src]#
```

**Comment by Rajalakshmi-Girish** [comment]
@cuonglm Can you please make the issue summary more generic to include power architecture?

**Comment by cuonglm** [comment]
> @cuonglm Can you please make the issue summary more generic to include power architecture?
> linux/ppc64le

I think it’s ok to add more failure in comments. Also there’s note in original CL https://go-review.googlesource.com/c/go/+/293392

**Comment by erifan** [comment]
Also observed on Linux/Arm64

**Comment by jcajka** [comment]
I have observed this on all non-intel arches supported by Fedora, that being linux/arm64, linux/arm32, linux/s390x and linux/ppc64le with various bootstrap GC versions, gcc&co. That makes me believe this is some internal GC issues introduce somewhere between Feb 27th and now based on builds that I periodically run. Trying to bisect it now.
