### ISSUE TITLE
cmd/go: warning message when getting a retracted module version is missing a trailing newline

### ISSUE THREAD

**Issue by liggitt** [golang/go#44674]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Used `go get` to fetch a retracted module version

```
$ go mod init testcase
go: creating new go.mod: module testcase

$ go get github.com/liggitt/retract20210126@v1.5.2
go: warning: github.com/liggitt/retract20210126@v1.5.2: retracted by module author: pre-module versions are obsolete
go: to switch to the latest unretracted version, run:
	go get github.com/liggitt/retract20210126@latestgo get: added github.com/liggitt/retract20210126 v1.5.2
```

### What did you expect to see?

A well-formed warning about the retracted version

### What did you see instead?

A missing newline garbled the command to run to switch to the latest version:

```
	go get github.com/liggitt/retract20210126@latestgo get: added github.com/liggitt/retract20210126 v1.5.2
```

**Comment by liggitt** [comment]
looks like the newline was dropped inhttps://go-review.googlesource.com/c/go/+/282121

**Comment by ALTree** [comment]
@gopherbot Please open a 1.16 backport issue for consideration. This is a garbled user-visibile message with no workaround.
