### ISSUE TITLE
x/pkgsite: exclude github.com/GameWorkstore/async-network-engine

### ISSUE THREAD

**Issue by john-rosa-playkids** [golang/go#44673]
### What is the URL of the page with the issue?
 github.com/GameWorkstore/async-network-engine
 
 
### What is your user agent?
 Your IP address range has been blocked

Unfortunately, our system has blocked your request for this page. We've had to do this because we routinely get crawlers and bots overloading our system with page requests and something about your web requests on our site has tripped off our sensors.

The IP Address you're using comes from a bad group of IP Addresses; we've had so much trouble with it that we've blocked the entire range. We're sorry if you got caught in the crossfire. We routinely block web hosting companies and VPNs because they generate too much "bad" traffic. Occasionally some ISPs send so much bad traffic that we're forced to block them entirely.

We're really sorry we had to do this, but we get so many badly-behaved bots who absolutely slam our servers and ruin it for everyone else; this is one of the ways we have to stop our servers from getting completely overloaded :(

If you are trying to get things like the latest version numbers or user agents for web browsers, please use our API instead of scraping the site. It helps support the project.

### What did you do?
 

cmd+clicked in import github.com/GameWorkstore/async-network-engine
instead of github.com/GameWorkstore/async-network-engine-go
 
 
### What did you expect to see?
 github.com/GameWorkstore/async-network-engine-go imported
 
 
### What did you see instead?
github.com/GameWorkstore/async-network-engine module doesn't exist / malformed. Of course, it's because async engine was registered on go site wrongly

**Comment by jba** [comment]
https://pkg.go.dev/github.com/GameWorkstore/async-network-engine seems fine. Can you explain your problem in more detail? Actual commands and their output would be helpful.

**Comment by john-rosa-playkids** [comment]
We need to remove https://pkg.go.dev/github.com/GameWorkstore/async-network-engine as the correct one if https://pkg.go.dev/github.com/GameWorkstore/async-network-engine-go, that's it.

**Comment by julieqiu** [comment]
Removed.
