### ISSUE TITLE
x/pkgsite: please remove incorrect package https://pkg.go.dev/github.com/TheWolfNL/random-string

### ISSUE THREAD

**Issue by TheWolfNL** [golang/go#44683]
### What is the URL of the page with the issue?

 https://pkg.go.dev/github.com/TheWolfNL/random-string
 
### What did you do?
 
created a package and messed up 
 
### What did you expect to see?
 
just one version of the package
 
### What did you see instead?

https://pkg.go.dev/github.com/TheWolfNL/random-string was an incorrect release where 
https://pkg.go.dev/github.com/thewolfnl/random-string is the working version.

**Comment by bcmills** [comment]
I'm curious — can you [`retract`](https://golang.org/ref/mod#go-mod-file-retract) the erroneous versions?

(I think that ought to work despite the difference in module path, although I'm not sure we've tested that scenario.)

CC @jayconrod @matloob

**Comment by TheWolfNL** [comment]
I thought it was highly unlikely that this would work, since the versions I'd want to retract are not showing up when doing this either:
```bash
go list -m -versions
# nor if I specify the module path
go list -m -versions github.com/TheWolfNL/random-string
```
But i've added the [retractions](https://github.com/TheWolfNL/random-string/blob/main/go.mod)

**Comment by bcmills** [comment]
Neato! That seems to have done the trick from the perspective of `cmd/go`, at least:
```
$ go get -d github.com/TheWolfNL/random-string@v0.0.0-20210228113105-9c881b0f8282
go: warning: github.com/TheWolfNL/random-string@v0.0.0-20210228113105-9c881b0f8282: retracted by module author: figuring out releases
go: to switch to the latest unretracted version, run:
        go get github.com/TheWolfNL/random-string@latest
go get: added github.com/TheWolfNL/random-string v0.0.0-20210228113105-9c881b0f8282
```

**Comment by julieqiu** [comment]
Removed.
