### ISSUE TITLE
time: Accept PT0S as valid Duration in time.ParseDuration

### ISSUE THREAD

**Issue by andig** [golang/go#44681]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/andig/Library/Caches/go-build"
GOENV="/Users/andig/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/andig/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/andig/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/andig/htdocs/evcc/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/73/89ycv7qn51j4kbm04jsz9b840000gn/T/go-build1971260061=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Parse zero duration:

    _, err := time.ParseDuration("PT0S")

https://play.golang.org/p/m5cKJNEHD-n

### What did you expect to see?
According to https://en.wikipedia.org/wiki/ISO_8601:
> Date and time elements including their designator may be omitted if their value is zero, and lower-order elements may also be omitted for reduced precision. For example, "P23DT23H" and "P4Y" are both acceptable duration representations. However, at least one element must be present, thus "P" is not a valid representation for a duration of 0 seconds. "PT0S" or "P0D", however, are both valid and represent the same duration.

### What did you see instead?

    time: invalid duration "PT0S"

**Comment by andig** [comment]
Update: also decoding `PT15H23M` fails which looks right?

**Comment by seankhliao** [comment]
The docs for `time.ParseDuration` specifies the format it supports (not ISO 8601)

Do you want to turn it into a proposal for spring ISO 8601 durations?

**Comment by andig** [comment]
> The docs for time.ParseDuration specifies the format it supports (not ISO 8601). Do you want to turn it into a proposal for supporting ISO 8601 durations?

Good question. Quick check seems to indicate that there's currently no library that supports both decoding `time.Duration` in iso8601 and unmarshalling from JSON.

Changing `time.Duration`s format seems out of question, even for Go2. I assume there is not much that can be done, maybe with the exception of adding iso8601 encoding/decoding functions?

**Comment by seankhliao** [comment]
iso8601 uses uppercase while Go uses lowercase, so in theory no separate function is needed. However, Go has rejected supporting time intervals greater than an hour so I would consider it unlikely to accept full iso8601 durations

**Comment by dmitshur** [comment]
CC @rsc via [owners](https://dev.golang.org/owners).

**Comment by andig** [comment]
If go and ISO duration use different case, one could decode both transparently using the same decoding function. This would be great for unmarshaling JSON. For encoding, as additional `ISO() string` function similar to time `ISOWeek()` could be added.

While this is not a proposal, I could update it if there‘s likelihood of interest. Reasoning is that there‘s currently no library that seems to support encoding and decoding of ISO durations, they are part of at least one emobility REST apis though.

**Comment by andig** [comment]
Note there is https://github.com/dylanmei/iso8601 or https://github.com/ChannelMeter/iso8601duration so it may not be necessary to have this in the language.
