### ISSUE TITLE
tour: Maintained?

### ISSUE THREAD

**Issue by AlbinoGeek** [golang/go#44687]
### Question

I notice 30+ PRs (some dating 2+ years) and hundreds of unanswered (and many janitorial/empty) issues in the tour repository -- with the only contributions being to clarify where issues should be made, and to bump the golang version (e.g: minor)

All of these things have led me to ask:

Is the tour actively maintained anymore?

#### Template Not Applicable

**Comment by ALTree** [comment]
"Maintained" as in "if it goes offline, will someone fix it and put it back online within a few hours?": Yes.
"Maintaned" as in "there's someone looking at the issue tracker daily and reviewing/merging PRs with small, mostly cosmetic, changes in the English text of the lessons": No, right now.

This kind of question is better suited for the golang-dev mailing list, we only use the issue tracker for bugs in Go.

**Comment by AlbinoGeek** [comment]
> "Maintaned" as in "there's someone looking at the issue tracker daily and reviewing/merging PRs with small, mostly cosmetic, changes in the English text of the lessons": No, right now.

Awesome, thank you!

Although, I would like to digress a little and show that some of the issues and PRs in the tour repository are not strictly cosmetic, and that some changes are legitimate in tuning or correcting the lesson material itself (or adding new chapters entirely.)

This is what led me to ask.

**Comment by ALTree** [comment]
> Although, I would like to digress a little and show that some of the issues and PRs in the tour repository are not strictly cosmetic, and that some changes are legitimate in tuning or correcting the lesson material itself (or adding new chapters entirely.)

Yes, what I meant is that it's mostly PRs doing small changes, not fixing critical or structural issues in the tour's content. With introductory material like the one in the tour, there's basically an infinite amount of... *small tuning* that can be done on the content. 

> The tour repository says in the README to create issues here, in this bug tracker, sorry about that. 

No problem, it meant for technical issues, the text is probably not very clear.

**Comment by AlbinoGeek** [comment]
Hmm... Alright, thank you.

It is not clear whether the tour seeks any improvements at this time based on these comments.
