### ISSUE TITLE
The "Projects" page in the Wiki disappear

### ISSUE THREAD

**Issue by LJHao288** [golang/go#44686]
### What version of Go are you using (`go version`)?
not related

### Does this issue reproduce with the latest release?
not related

### What operating system and processor architecture are you using (`go env`)?
not related

### What did you expect to see?
A page showing a curated list of Go (Open source) projects.

Original URL:
https://github.com/golang/go/wiki/Projects

### What did you see instead?
Empty page
![image](https://user-images.githubusercontent.com/20478850/109424075-748e8880-79e2-11eb-91a6-fcfed7e7719b.png)

It causes the bad reference at:
https://github.com/golang/go/wiki
![image](https://user-images.githubusercontent.com/20478850/109424201-039ba080-79e3-11eb-9274-793cbe927f76.png)
https://golang.org/pkg/
![image](https://user-images.githubusercontent.com/20478850/109424225-1c0bbb00-79e3-11eb-800c-9bfafb51c7a3.png)

**Comment by ianlancetaylor** [comment]
Thanks, looks like someone deleted it for some reason.  Restored.
