### ISSUE TITLE
cmd/go: mkdir C:\Program Files\Go: Access is denied.

### ISSUE THREAD

**Issue by Jassi10000** [golang/go#44691]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\dell\AppData\Local\go-build
set GOENV=C:\Users\dell\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Go\bin\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Go\bin
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\dell\AppData\Local\Temp\go-build2310080819=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I tried to install all the necessary modules for Go to setup in VS-Code , as I was preparing to make a project with GoLang

### What did you expect to see?
I expected to see all the Go tools properly setup , and after that smooth functioning in VS-Code

### What did you see instead?
gopls: failed to install gopls(golang.org/x/tools/gopls): Error: Command failed: c:\go\bin\go.exe get -v golang.org/x/tools/gopls
go: writing stat cache: mkdir C:\Program Files\Go: Access is denied.
go: writing stat cache: mkdir C:\Program Files\Go: Access is denied.
go: downloading golang.org/x/tools/gopls v0.6.6
go: writing go.mod cache: mkdir C:\Program Files\Go: Access is denied.
go: downloading golang.org/x/tools v0.1.0
go get golang.org/x/tools/gopls: mkdir C:\Program Files\Go: Access is denied.
 no output

**Comment by stamblerre** [comment]
@jayconrod @matloob @bcmills can you please take a look? I'm not sure what the advice is for troubleshooting permissions issues

**Comment by dmitshur** [comment]
I think a good next step here would be to determine if Go is installed properly and it's able to build programs. For example, does the `go run .` command in step 4 of https://golang.org/doc/tutorial/getting-started get you expected output?

The installed path changed recently in #42070 (CC @toothrot), but I don't think that should be causing this. It seems like the GOPATH directory may be misconfigured, possibly from a left-over previous installation.

**Comment by dmitshur** [comment]
The `go env` output includes:

```
set GOPATH=C:\Go\bin
```

That probably needs to be changed.

**Comment by bcmills** [comment]
The `writing stat cache` error comes from here:
https://github.com/golang/go/blob/4c1a7ab49c4c68907bc7f7f7f776edd9116584a5/src/cmd/go/internal/modfetch/cache.go#L221

That implies that the path from that error message is in the module cache, which defaults to `%GOPATH%\pkg\mod`.

The user-reported `go env` output shows:
```
set GOMODCACHE=C:\Go\bin\pkg\mod
…
set GOPATH=C:\Go\bin
```

So whatever generated that error message is using a different value for `GOPATH` and/or `GOMODCACHE`, probably `C:\Program Files\Go` or similar instead of `C:\Go\bin` as reported.

**Comment by bcmills** [comment]
So, what we need to know now is: what was the actual `go` command that generated that error message?

(Independently, setting `GOPATH` to `C:\Go\bin` seems very suspicious: `GOPATH` contains its own `bin` subdirectory at `%GOPATH%\bin`, so probably you want `GOPATH` set to `C:\Go` instead.)

**Comment by Jassi10000** [comment]
So all you respected peeps , who are actually helping with the doubt, first of all thank you but what I want is :  Can any one of you can tell me the clean precise steps I should finally do ?

**Comment by hyangah** [comment]
@Jassi10000 Did you install `go` using the official Windows go installer?  I don't know why the extension picked `c:\go\bin\go.exe` for go1.16.

If you have a previous version of `go.exe` installed there, please uninstall/delete `C:\Go` directory and reinstall using the official windows installed. `go1.16` should be installed in `C:\Program Files\Go\bin`.

**Comment by Jassi10000** [comment]
> @Jassi10000 Did you install `go` using the official Windows go installer? I don't know why the extension picked `c:\go\bin\go.exe` for go1.16.
> 
> If you have a previous version of `go.exe` installed there, please uninstall/delete `C:\Go` directory and reinstall using the official windows installed. `go1.16` should be installed in `C:\Program Files\Go\bin`.

yes sir , I did that  exactly same , that's why second time I changes the file directory , I think that was my only mistake , 
Ok  I think I should try again with the steps you mentioned

**Comment by dmitshur** [comment]
You can find instructions to uninstall a previous version at https://golang.org/doc/manage-install#uninstalling, and instructions to install a new version at https://golang.org/doc/install.

See https://golang.org/help/ for more places to get help. I'll close this issue since it doesn't seem to be a bug in the Go project.

**Comment by AliPeeri** [comment]
H

> ### What version of Go are you using (`go version`)?
> $ go version
> go version go1.16 windows/amd64
> ### Does this issue reproduce with the latest release?
> ### What operating system and processor architecture are you using (`go env`)?
> `go env` Output
> ### What did you do?
> I tried to install all the necessary modules for Go to setup in VS-Code , as I was preparing to make a project with GoLang
> 
> ### What did you expect to see?
> I expected to see all the Go tools properly setup , and after that smooth functioning in VS-Code
> 
> ### What did you see instead?
> gopls: failed to install gopls(golang.org/x/tools/gopls): Error: Command failed: c:\go\bin\go.exe get -v golang.org/x/tools/gopls
> go: writing stat cache: mkdir C:\Program Files\Go: Access is denied.
> go: writing stat cache: mkdir C:\Program Files\Go: Access is denied.
> go: downloading golang.org/x/tools/gopls v0.6.6
> go: writing go.mod cache: mkdir C:\Program Files\Go: Access is denied.
> go: downloading golang.org/x/tools v0.1.0
> go get golang.org/x/tools/gopls: mkdir C:\Program Files\Go: Access is denied.
> no output

is the issue solved ? because i have found a way to solve it.

**Comment by TUSHAR4541** [comment]
@AliPeeri no it's not

**Comment by Davo36** [comment]
I had this error after installing Go just now.  I ran VS Code in Administrator mode and it all went away... So for me I'm pretty sure it was a Windows permissions problem.

**Comment by AdamMK** [comment]
Had the same issue and resolved it with what @Davo36 did.

**Comment by Davo36** [comment]
> Had the same issue and resolved it with what @Davo36 did.

@AdamMK : Actually I had this again recently and I found the problem to be that I had my GOPATH variable set incorrectly.  I describe that here: https://github.com/golang/go/issues/26814

Go down to the bottom to see what I did.  I had 2 values for the GOPATH variable when viewing in the environment variables dialog box on Windows.

But it did look very much like a Windows permissions problem since Administrator mode makes it go away.

**Comment by HoytRen** [comment]
I don't think this issue is resolved. I install go with go1.17.3.windows-amd64.msi, and I still see the default repo path is "C:\Program Files\Go\src", then we will sure get the error because of the Windows protection. The repo should be in C:\Users\XXXX\ by default but not in C:\Program Files\, just as maven, nodejs and many others did. Ask for admin privilege doesn't make sense at all.

**Comment by jackgxl** [comment]
Tools environment: GOPATH=D:\code_go, GOBIN=D:\go\bin
Installing 10 tools at the configured GOBIN: D:\go\bin in module mode.
  gopkgs
  go-outline
  gotests
  gomodifytags
  impl
  goplay
  dlv
  dlv-dap
  staticcheck
  gopls

Installing github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest (D:\go\bin\gopkgs.exe) SUCCEEDED
Installing github.com/ramya-rao-a/go-outline@latest (D:\go\bin\go-outline.exe) SUCCEEDED
Installing github.com/cweill/gotests/gotests@latest (D:\go\bin\gotests.exe) SUCCEEDED
Installing github.com/fatih/gomodifytags@latest (D:\go\bin\gomodifytags.exe) SUCCEEDED
Installing github.com/josharian/impl@latest (D:\go\bin\impl.exe) SUCCEEDED
Installing github.com/haya14busa/goplay/cmd/goplay@latest (D:\go\bin\goplay.exe) SUCCEEDED
Installing github.com/go-delve/delve/cmd/dlv@latest (D:\go\bin\dlv.exe) SUCCEEDED
Installing github.com/go-delve/delve/cmd/dlv@master (D:\go\bin\dlv-dap.exe) SUCCEEDED
Installing honnef.co/go/tools/cmd/staticcheck@latest (D:\go\bin\staticcheck.exe) SUCCEEDED
Installing golang.org/x/tools/gopls@latest (D:\go\bin\gopls.exe) SUCCEEDED

All tools successfully installed. You are ready to Go. :)


make sure your GOPATH  GOROOT GOBIN GOPROXY are all correct !

**Comment by jackgxl** [comment]
go env -w GOPROXY=https://goproxy.io,direct
go env -w GOROOT=D:\go
go env -w GO111MODULE=on
go env -w GOBIN=D:\go\bin\go.exe
go env -w GOPATH=D:\code_go

**Comment by bcmills** [comment]
This issue is closed. If you are seeing similar symptoms, please [file a new issue](https://go.dev/issue/new) and fill out the complete template. Thanks.
