### ISSUE TITLE
x/tools/gopls: Go error notification

### ISSUE THREAD

**Issue by Jassi10000** [golang/go#44693]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\dell\AppData\Local\go-build
set GOENV=C:\Users\dell\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Go\bin\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Go\bin
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\dell\AppData\Local\Temp\go-build3505164714=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I just install / modify all the packages of GoLang in Command Pallette in VS - Code 

### What did you expect to see?
I don't expect to see the error mentioned in next ques

### What did you see instead?
Error loading workspace: You are outside of a module and outside of $GOPATH/src. If you are using modules, please open your editor to a directory in your module.

**Comment by stamblerre** [comment]
It sounds like you're working outside of a module, so I would recommend creating a module by using the `go mod init` command.

Also, can you please share your `gopls` logs? Information on how to capture them can be found [here](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information).

**Comment by Jassi10000** [comment]
@stamblerre Actually mam am totally new to Go, that's why facing so many issues, I have followed the official steps on the website of Go ,but still the results were not good 

can you pls guide me through the steps so I can start fresh and avoid these errors

**Comment by stamblerre** [comment]
@Jassi10000: Have you taken a look at https://golang.org/doc/tutorial/getting-started or https://blog.golang.org/using-go-modules? Otherwise you may be able to get some help in the #newbies channel of the [Gophers Slack](https://invite.slack.golangbridge.org/).

**Comment by stamblerre** [comment]
Closing this issue as there hasn't been activity on it for over a week.
