### ISSUE TITLE
x/pkgsite: mismatched version, tags, LATEST

### ISSUE THREAD

**Issue by dongsam** [golang/go#44694]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/tendermint/liquidity
 
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36
 
 
 
### Screenshot
![](https://tva1.sinaimg.cn/large/e6c9d24egy1go3xl9aaidj20v00qqwq3.jpg)
  
 
### What did you do?
 
The tags of other repo that were accidentally pushed are registered in the pkg.go.dev version, so the tags of other repo that are not the actual latest version are the base version

So we have removed the wrong tags in this repo and released higher tags. and 
call https://sum.golang.org/lookup/github.com/tendermint/liquidity@v1.2.0-rc1 and
https://proxy.golang.org/github.com/tendermint/liquidity/@v/db07fffbceb188c6bc4dcfb2096b9ae9b8a09a4e.info

https://github.com/tendermint/liquidity/issues/119 
 
### What did you expect to see?
 
Expected tag list of [github repo tags](https://github.com/tendermint/liquidity/releases) and tag list of [pkg.go.dev_versions](https://pkg.go.dev/github.com/tendermint/liquidity?tab=versions) to be synced
and set the latest version to be [v1.2.0-rc1](https://pkg.go.dev/github.com/tendermint/liquidity@v1.2.0-rc1)
 
### What did you see instead?

listed removed the wrong tags and set the latest version as the wrong v0.33.2

**Comment by seankhliao** [comment]
`@latest` won't match pre-releases when "stable" releases exist

You should be able to `retract` wrong versions, pkg.go.dev support for it is #43265
