### ISSUE TITLE
Bad conversion when marshalling uint8 slice

### ISSUE THREAD

**Issue by fbigand** [golang/go#44692]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes (I am running the latest version as far as I am aware of)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTOS="linux"
</pre></details>

### What did you do?

I wanted to Marshal a slice of uint8
```
unit8JSON, _ := json.Marshal([]uint8{1, 10, 100})
```

### What did you expect to see?
I expected to have a JSON string representing my slice
```
fmt.Println(string(uint8JSON))
// expecting [1, 10, 100]
```

### What did you see instead?
A JSON string type with ~random characters
```
fmt.Println(string(uint8JSON))
// saw "AQpk"
```

### Further investigation
I tested for the other type of integer, but it appears that only uint8 has a bad conversion

```
package main

import (
    ...
)

func main() {
    uint8Slice := []uint8{1, 10, 100}
    uint8JSON, _ := json.Marshal(uint8Slice)

    uint16Slice := []uint16{1, 10, 100}
    uint16JSON, _ := json.Marshal(uint16Slice)

    uint32Slice := []uint32{1, 10, 100}
    uint32JSON, _ := json.Marshal(uint32Slice)

    uint64Slice := []uint64{1, 10, 100}
    uint64JSON, _ := json.Marshal(uint64Slice)

    intSlice := []int8{1, 10, 100}
    intJSON, _ := json.Marshal(intSlice)

    fmt.Println("uint8 slice  ", string(uint8JSON))
    fmt.Println("uint16 slice ", string(uint16JSON))
    fmt.Println("uint32 slice ", string(uint32JSON))
    fmt.Println("uint64 slice ", string(uint64JSON))
    fmt.Println("int8 slice   ", string(intJSON))

    // console output

    // uint8 slice   "AQpk"
    // uint16 slice  [1,10,100]
    // uint32 slice  [1,10,100]
    // uint64 slice  [1,10,100]
    // int8 slice    [1,10,100]
}
```

**Comment by seankhliao** [comment]
This is due to `byte` being an alias for `uint8` and treating `[]byte` specially since this is the common case.

Unfortunate, but working as intended

**Comment by kevlar700** [comment]
Is there any way around this. It leaves you with the options of using more memory or more processing on the other end?

Somehow create a uint8 type that is treated like int8 by the JSON package?

Or perhaps a JSON package that does not do this?
