### ISSUE TITLE
gollvm: go-llvm-builtins.cpp:481:58: error: too few arguments to function call, expected at least 5, have 4

### ISSUE THREAD

**Issue by advancedwebdeveloper** [golang/go#44708]
From the extracted log, out [here](https://github.com/advancedwebdeveloper/clang_test_cpu_features/runs/2001120399?check_suite_focus=true):

> /home/runner/work/gollvm_build_process/gollvm_build_process/gollvm_build_process/llvm-project/llvm/tools/gollvm/bridge/go-llvm-builtins.cpp:481:58: error: too few arguments to function call, expected at least 5, have 4
> return builder->CreateAtomicRMW(op, args[0], args[1], o);
> /home/runner/work/gollvm_build_process/gollvm_build_process/gollvm_build_process/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1721:18: note: 'CreateAtomicRMW' declared here
> AtomicRMWInst *CreateAtomicRMW(AtomicRMWInst::BinOp Op, Value *Ptr,
> /home/runner/work/gollvm_build_process/gollvm_build_process/gollvm_build_process/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1708:3: note: 'CreateAtomicCmpXchg' declared here
> CreateAtomicCmpXchg(Value *Ptr, Value *Cmp, Value *New, MaybeAlign Align,

it gives a crash with Clang 10, 11 - and you can see [here](https://github.com/advancedwebdeveloper/gollvm_build_process/runs/2001351212?check_suite_focus=true) that Clang 13 also crashes (but I do not claim that the compilation error is the same)

CC @thanm @cherrymui @ianlancetaylor

**Comment by erifan** [comment]
This may be caused by the asynchronous update of Llvm and Gollvm, see https://reviews.llvm.org/D97223,  try

$ git diff
```
diff --git a/bridge/go-llvm-builtins.cpp b/bridge/go-llvm-builtins.cpp
index 5d784d2..eabfcea 100644
--- a/bridge/go-llvm-builtins.cpp
+++ b/bridge/go-llvm-builtins.cpp
@@ -478,7 +478,7 @@ static llvm::Value *atomicRMWMaker(llvm::AtomicRMWInst::BinOp op,
       llvm::isa<llvm::ConstantInt>(args[2]) ?
       llvmOrder(llvm::cast<llvm::ConstantInt>(args[2])->getZExtValue()) :
       llvm::AtomicOrdering::SequentiallyConsistent;
-  return builder->CreateAtomicRMW(op, args[0], args[1], o);
+  return builder->CreateAtomicRMW(op, args[0], args[1], llvm::MaybeAlign(), o);
 }

 static llvm::Value *atomicXchgMaker(llvm::SmallVectorImpl<llvm::Value*> &args,
@@ -538,7 +538,7 @@ static llvm::Value *atomicCasMaker(llvm::SmallVectorImpl<llvm::Value*> &args,
       llvm::isa<llvm::ConstantInt>(args[3]) &&
       !llvm::cast<llvm::ConstantInt>(args[3])->isZero();
   llvm::AtomicCmpXchgInst *cas =
-      builder->CreateAtomicCmpXchg(args[0], old, args[2], o, o2);
+      builder->CreateAtomicCmpXchg(args[0], old, args[2], llvm::MaybeAlign(), o, o2);
   cas->setWeak(weak);
   // LLVM cmpxchg instruction returns { valType, i1 }. Extract the second
   // value, and cast to Go bool type (i8).

```

**Comment by erifan** [comment]
I'm working on a fixing patch.
