### ISSUE TITLE
cmd/link: `ctxt.loader.Dump` is no effect.

### ISSUE THREAD

**Issue by qingyunha** [golang/go#44705]
https://github.com/golang/go/blob/5ff7ec98b7727b3641df25200345b1aa50b6ff35/src/cmd/link/internal/ld/main.go#L142

link exit with `os.Exit`, the defer function hava no effect.

**Comment by cherrymui** [comment]
As the comment says, `// dump symbol info on crash`. This is for debugging linker panics, and not intended to have effect on successful builds.
