### ISSUE TITLE
x/playground: cgo builds fail (e.g., importing "net" package) because "gcc" executable not found in $PATH

### ISSUE THREAD

**Issue by bradfitz** [golang/go#44714]
The playground is currently broken. e.g. https://play.golang.org/p/NbF8QOGEaYB

```go
package main

import (
	"fmt"
	"net"
)

func main() {
	fmt.Println(net.ParseIP("1.2.3.4"))
}
```

Results in:

```
# net
cgo: exec gcc: exec: "gcc": executable file not found in $PATH

Go build failed.
```

/cc @dmitshur

**Comment by dmitshur** [comment]
We've recently changed PATH as part of fixing for Go 1.16, maybe this is relevant.

CC @toothroot.

**Comment by toothrot** [comment]
I'm not sure if it's a PATH issue as much as it could be an issue with how we're building Go now. I don't think gcc has been present in the final container for a while. I'll take a look.

**Comment by toothrot** [comment]
We've determined that net is being marked stale now, and that this is broken as of golang.org/cl/295649, but have yet to determine why.
