### ISSUE TITLE
x/pkgsite: does not find package after module renaming

### ISSUE THREAD

**Issue by System-Glitch** [golang/go#44713]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/goyave.dev/goyave/v3@v3.7.0
 
### What is your user agent?
 

 
 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
 
### Screenshot
 

 
 
![image](https://user-images.githubusercontent.com/7251668/109525419-cd792200-7ab1-11eb-967c-9bad7416f766.png)

 
### What did you do?
 

 
 Context: https://github.com/go-goyave/goyave/discussions/129

TL;DR: I moved my package to a custom domain and used the HTML meta `go-import` to ensure `go get` still works: https://goyave.dev/goyave . The repo has been moved from my personal account to an organization. Therefore, import paths changed (from `github.com/System-Glitch/goyave/v3` to `goyave.dev/goyave/v3`). I tried to request pkg.go.dev to generate the new docs using this link: https://pkg.go.dev/goyave.dev/goyave/v3@v3.7.0 . I clicked the "Request <package name>" button.
 
### What did you expect to see?
 
 I expected go.pkg.dev to generate the new docs just like if it was a new module.
 
### What did you see instead?

For some reason, it doesn't find the repository. And when I go to https://pkg.go.dev/goyave.dev/goyave/v3 (without specifying version), it redirects me to the previous location.

**Comment by julieqiu** [comment]
https://pkg.go.dev/goyave.dev/goyave/v3 should now work.
