### ISSUE TITLE
why path = os.Getenv("GOMOD") print path = "" in the go project?

### ISSUE THREAD

**Issue by dreamlu** [golang/go#44729]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.15.8
</pre>

### Does this issue reproduce with the latest release?
no

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
1.project go env:
```go
....
GOMOD="/home/lu/go/gowork/work/gt/go.mod"
...
```
2. system go env:
```go
...
GOMOD=""
...
```

</pre></details>

### What did you do?

// in project 
path = os.Getenv("GOMOD")

### What did you expect to see?

get the GOMOD value, maybe other ways

### What did you see instead?
print value is ""

**Comment by dreamlu** [comment]
hello...

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
