### ISSUE TITLE
x/build/cmd/release: macOS installer doesn't add /usr/local/go/bin to PATH when installing Go 1.14

### ISSUE THREAD

**Issue by jcollum** [golang/go#44723]
### What version of Go are you using (`go version`)?

n/a, Go won't install

### Does this issue reproduce with the latest release?

n/a, I need to install a prior release

### What operating system and processor architecture are you using (`go env`)?

n/a, Go won't install

### What did you do?

Downloaded https://golang.org/doc/install?download=go1.14.15.darwin-amd64.pkg

Installed it

Opened a new terminal 

### What did you expect to see?

Go available at the command line 

### What did you see instead?

```
$ which go
go not found
```

### Additional info

The installer instructions say 

> The package installs the Go distribution to /usr/local/go. The package should put the /usr/local/go/bin directory in your PATH environment variable. You may need to restart any open Terminal sessions for the change to take effect.

That's not happening with the 1.14 installer. It would help a lot to have some separate instructions (in a readme or something) for older versions of Go. While I did solve this, the instructions were a little misleading. Just a sentence about older versions not automatically updating the PATH would help. 

I repeated this install several times today, with the same results every time.

**Comment by dmitshur** [comment]
> That's not happening with the 1.14 installer.

It should be, so if it isn't, that's unexpected. Can you check if the file `/etc/paths.d/go` exists after running the installer? It should contain "/usr/local/go/bin" with a newline at the end.

```
$ cat /etc/paths.d/go
/usr/local/go/bin
```
