### ISSUE TITLE
cmd/go: mention `go get` in `go help mod`

### ISSUE THREAD

**Issue by bukowa** [golang/go#44726]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
I were working with a module using command `go mod`; i expected that i can update dependency with commands:
`go mod update -u <dependency>`
`go mod update <dependency>@commit`

### What did you expect to see?
I expected for this to work. 
I expected for this to show in `go help mod`:
````
Usage:

        go mod <command> [arguments]

The commands are:

        download    download modules to local cache
        edit        edit go.mod from tools or scripts
        graph       print module requirement graph
        init        initialize new module in current directory
        tidy        add missing and remove unused modules
        vendor      make vendored copy of dependencies
        verify      verify dependencies have expected content
        why         explain why packages or modules are needed
````
### What did you see instead?
After asking a question regarding this topic on golang slack channel i received help from `Tim Heckman` that stated:
````
yeah, the choice was made to keep it as go get so all the existing Gophers wouldn't need to relearn the command(s).
````
````
yeah, that was kept for historical purposes... that was how dependencies have always been gotten.
````
He nicely explained to me that i have to use:
````
go get <dependency>@commit
go get -u <dependency>
````
Which for me is confusing - i expected that subcommand to be related to `go mod` but - it's not in the help of that command - while it's clearly related to modules.

**Comment by go101** [comment]
Do you mean to use `go mod update` to depreciate `go get`?

**Comment by bukowa** [comment]
I don't know about depreciating `go get` but because that command is related to modules - i believe it should be included in `go mod`

**Comment by mvdan** [comment]
Are we actually suggesting that `go mod` should gain a command to update modules? The last comments mention that, and @bcmills added the NeedsFix label. But the Documentation label is also present, which tells me we haven't decided to add a command yet.

In terms of docs, I do think `go get` is already mentioned pretty well:

```
$ go help mod
Go mod provides access to operations on modules.

Note that support for modules is built into all the go commands,
not just 'go mod'. For example, day-to-day adding, removing, upgrading,
and downgrading of dependencies should be done using 'go get'.
See 'go help modules' for an overview of module functionality.
```

`go help modules` doesn't directly talk about `go get`, but it points to a few places that do mention it pretty often.

If you think the docs aren't clear enough, how do you suggest we improve them?

It's understandable that you expected `go mod update` to exist, but if you run `go help mod` just like the error from `go mod update` tells you, you'll be pointed at `go get` straight away.

Also, in terms of "just update all dependencies", see https://github.com/golang/go/issues/28424.

**Comment by bukowa** [comment]
> 
> It's understandable that you expected `go mod update` to exist, but if you run `go help mod` just like the error from `go mod update` tells you, you'll be pointed at `go get` straight away.
> 

Yes I expected this tree to be clear, as where I learn very fast by looking at well structured data in key:value pair - not by having to execute 2 additional commands which my brain fogs a little specially as I am not native english speaker.

When working with structure data I would expect `go mod update` to work. One can think that there is no `update` command at all.
```
Usage:

        go mod <command> [arguments]

The commands are:

        download    download modules to local cache
        edit        edit go.mod from tools or scripts
        graph       print module requirement graph
        init        initialize new module in current directory
        tidy        add missing and remove unused modules
        vendor      make vendored copy of dependencies
        verify      verify dependencies have expected content
        why         explain why packages or modules are needed
```
