### ISSUE TITLE
cmd/compile: unaligned load constant offsets on ppc64

### ISSUE THREAD

**Issue by randall77** [golang/go#44739]
```
package main

type T struct {
	x [4]byte
	y [8]byte
}

func f(a T, _ byte, b T) bool {
	return a.y == b.y
}
```
```
% GOOS=linux GOARCH=ppc64le ~/go1.16/bin/go tool compile -S ~/gowork/tmp1.go
compile: invalid offset for DS form load/store 00004 (/Users/khr/gowork/tmp1.go:9)	MOVD	"".b+17(R1), R4
```
This has been failing since at least 1.13.

My reading of the PPC64.rules is that 2 byte and 4 byte operations can be at any offset, but 8 byte operations need to be at a multiple of 4. (Search for `%4 == 0` in those rules). To be precise, the operations can happen at any address, but we can't *encode* constant offsets that aren't a multiple of 4. Do I have that correct?

Split off from #42385 

@laboger

**Comment by laboger** [comment]
@randall77  Yes, that is correct. The error is when encoding the instruction word. 
After looking at this a bit I have a suspicion that the rules to combine byte loads and stores are causing the problem here.  For variables on the stack, the entire offset is not being considered.

**Comment by randall77** [comment]
Maybe the assembler could use REGTMP to add in odd offsets, if needed.
```
MOVD 19(R1), R2
```
to
```
ADD $3, R1, R31
MOVD 16(R31), R2
```

**Comment by laboger** [comment]
There are several options: 2 MOVWs, Create the full address 19+R1 in a base register, load the offset into an index register and use an indexed load or store. I've been avoiding this to keep the one to one mapping of Go -> power asm. But perhaps generating 2 instructions is better than failing in this way.

I'm thinking the indexed load or store would be best and we could do that in the rules, although would need a way to get the current stack offset at that point (which is found using AddAux in ppc64/ssa.go).

**Comment by randall77** [comment]
Unfortunately, we don't know the offset of local variables at lowering rewrite time. But we *do* know the alignment, so maybe we load-combine only if the type of the local variable is at least 4-byte aligned?

I think I'd rather go the assembly modification route. Weird offsets will be rare, so we won't be adding assembly very often. 
 And it will let us remove the `i%4==0` tests from the rewrite rules, which would more than pay for the extra instruction in many cases.

**Comment by cherrymui** [comment]
> I think I'd rather go the assembly modification route.

I'd go with that, too. This happened earlier on ARM64, caused quite a number of bugs, and we had to introduce several special cases around it. Eventually I changed the assembler and it's all done.

**Comment by laboger** [comment]
Yep just realized that.
I remember that those combining rules are mostly used with byte slices so if we add alignment checks most of those won't be lowered. But they could be changed to generate the full address in the base register and then have a 0 offset. That would also allow the i%4 check in those rules to be removed, allowing more cases to be matched.

I agree that we should fix this in the assembler though and get rid of those checks for alignment of 4 in the rules. And then the assembler won't fail if we hit this case. But I think @pmur has a change for asm9.go that we should wait on before changing this. I see there are multiple places to fix.

**Comment by laboger** [comment]
I think I can fix this in ppc64/ssa.go when processing the MOVD loads and stores. I'm testing out a change now.

**Comment by laboger** [comment]
I think this is done?

**Comment by cherrymui** [comment]
I think so. Thanks.
