### ISSUE TITLE
How to solve build constraints？

### ISSUE THREAD

**Issue by lysShub** [golang/go#44730]
### What version of Go are you using (`go version`)?

<pre>
$ go version
[root@ecs-kc1-large-2-linux-20210220124439 test]# go version
go version go1.14.12 linux/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
[root@ecs-kc1-large-2-linux-20210220124439 test]# go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_arm64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/workspace/MTUdiscover/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you do?
In different systems，I only achieve a same function with different codes. then use runtime.GOOS quote corresponding function
[the fun for linux](https://github.com/lysShub/MTUdiscover/blob/master/internal/rawnet/rawnet.go#L136)
[the fun for Windows](https://github.com/lysShub/MTUdiscover/blob/master/internal/rawnet/rawnetwindows/rawnetwindows.go15)
[quote the funs](https://github.com/lysShub/MTUdiscover/blob/master/internal/rawnet/rawnet.go#L170)

### What did you expect to see?
Compile normally

### What did you see instead?
```golang
[root@ecs-kc1-large-2-linux-20210220124439 test]# go run main.go
../internal/rawnet/rawnetwindows/rawnetwindows.go:11:2: build constraints exclude all Go files in /root/go/pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/windows
```

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
