### ISSUE TITLE
sync: Pool releasing items too quickly

### ISSUE THREAD

**Issue by pjebs** [golang/go#44744]
On GC, the Pool is releasing too many items which I believe should be retained significantly longer.
The creation of said item (via `New`)  is a time-consuming process for me so it's defeating the purpose of using the Pool to improve latency.

This is a revisit of: https://github.com/golang/go/issues/22950

It would be great if there was an option or a way for us to customize different strategies on when the Pool should release items.

**Comment by ianlancetaylor** [comment]
A `sync.Pool` is not meant to serve all purposes.  If it is costly to create new items, it's often best to maintain your own free list rather than to use a `sync.Pool`.

**Comment by randall77** [comment]
Could you describe your use behavior? Why is CL 166961 not enough?
