### ISSUE TITLE
cmd/link: fail to build when using time/tzdata on ARM [1.15 backport]

### ISSUE THREAD

**Issue by cherrymui** [golang/go#44748]
(Creating manually as I don't think gopherbot would do this after it already created one.)

Please consider #44639 (fixed in 098504c73ff6ece19566a1ac811ceed73be7c81d for Go 1.17) for backport to the next 1.15 minor release.

This causes programs fail to build without easy workaround. It applies to 1.15 as well.

**Comment by toothrot** [comment]
Approved. This is a serious issue with no workaround.
