### ISSUE TITLE
Linux and Windows have different access permissions on package Folders(Dirs's)

### ISSUE THREAD

**Issue by akhilravuri1** [golang/go#44755]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
$ go env
rakhil@waldevdbctpyl01:/work/rakhil/go1.16/go/bin$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rakhil/.cache/go-build"
GOENV="/home/rakhil/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/rakhil/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/rakhil/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/work/rakhil/go1.16/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/work/rakhil/go1.16/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3993866916=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Installed the package using go get -d github.com/ibmdb/go_ibm_db

### What did you expect to see?

Folders inside the package having read wite permission and files having read-only permission

### What did you see instead?

Folders also having read-only permission.

Please see the below screenshot:-
Linux Image:-
![image](https://user-images.githubusercontent.com/32290825/109757293-7e490380-7c0f-11eb-9eb3-5c79be600452.png)

Windows Image:-
![image](https://user-images.githubusercontent.com/32290825/109757328-8ef97980-7c0f-11eb-98d7-a1fec65dfefd.png)

Thanks,
Akhil

**Comment by bcmills** [comment]
Per https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfileattributesa:
> [`FILE_ATTRIBUTE_READONLY`] is not honored on directories. For more information, see “[You cannot view or change the Read-only or the System attributes of folders in Windows Server 2003, in Windows XP, or in Windows Vista.](https://support.microsoft.com/en-us/topic/you-cannot-view-or-change-the-read-only-or-the-system-attributes-of-folders-in-windows-server-2003-in-windows-xp-in-windows-vista-or-in-windows-7-55bd5ec5-d19e-6173-0df1-8f5b49247165)”

**Comment by bcmills** [comment]
Note that you can set the [`-modcacherw`](https://tip.golang.org/cmd/go/#hdr-Compile_packages_and_dependencies) flag to leave directories writable on all platforms.
