### ISSUE TITLE
Make a channel of receive-only channels

### ISSUE THREAD

**Issue by pascaldekloe** [golang/go#44763]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```go
fmt.Printf("%T", make(chan <-chan error))
```

### What did you expect to see?

"chan <-chan error"

### What did you see instead?

"chan<- chan error"

**Comment by ianlancetaylor** [comment]
I beleive you are looking for `make(chan (<- chan error))`.
