### ISSUE TITLE
crypto/rsa: EncryptOAEP documentation says "if a given public key is used to decrypt" instead of "encrypt"

### ISSUE THREAD

**Issue by kocmo** [golang/go#44777]
### What did you do?
Opened https://golang.org/pkg/crypto/rsa/#EncryptOAEP in browser

### What did you expect to see?

For example, if a given public key is used to **encrypt** two types of messages, then distinct label values could be used to ensure that a ciphertext for one purpose cannot be used for another by an attacker.

### What did you see instead?

For example, if a given public key is used to **decrypt** two types of messages then distinct label values could be used to ensure that a ciphertext for one purpose cannot be used for another by an attacker.

**Comment by dmitshur** [comment]
CC @FiloSottile, @katiehockman, @rolandshoemaker via [owners](https://dev.golang.org/owners).

**Comment by katiehockman** [comment]
I agree with @kocmo that the documentation is incorrect. If you are interested in fixing this, feel free to send a PR. Otherwise, one of us can look into it. Thanks.
