### ISSUE TITLE
x/tools/go/buildutil: support comma-delimited build tags in buildutil.TagsFlag

### ISSUE THREAD

**Issue by yaaase** [golang/go#44787]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.15.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mbillie/Library/Caches/go-build"
GOENV="/Users/mbillie/Library/Application Support/go/env"
GOEXE=""
GOFLAGS="-mod=vendor"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mbillie/digitalocean/cthulhu/docode/pkg/mod"
GONOPROXY="*.internal.digitalocean.com,github.com/digitalocean"
GONOSUMDB="*.internal.digitalocean.com,github.com/digitalocean"
GOOS="darwin"
GOPATH="/Users/mbillie/digitalocean/cthulhu/docode:/home/mbillie/digitalocean:/home/mbillie/go"
GOPRIVATE="*.internal.digitalocean.com,github.com/digitalocean"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/w5/jt734dx51w7c9sq8spdrb_6r0000gs/T/go-build425061423=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I would like to allow tools in the community to support the same format for build tags (e.g. comma delimited) as the go tool supports. Space separate tags have been deprecated in the go tool. This brings parity to tools that rely on golang.org/x/tools/go/build : see https://go-review.googlesource.com/c/tools/+/284214#message-fc9907b03ae75ae24145f421e623330b4b9b9158

**Comment by bcmills** [comment]
I note, per https://tip.golang.org/cmd/go/#hdr-Compile_packages_and_dependencies:

> ```
> -tags tag,list
> 	a comma-separated list of build tags to consider satisfied during the
> 	build. For more information about build tags, see the description of
> 	build constraints in the documentation for the go/build package.
> 	(Earlier versions of Go used a space-separated list, and that form
> 	is deprecated but still recognized.)
> ```

So this seems fine to add to `go/buildutil`.

CC @stamblerre @alandonovan

**Comment by aykevl** [comment]
Any update on this? We'd like to support commas in build tags in TinyGo and it would be really nice if we could keep using `buildutil.TagsFlag`.

**Comment by adonovan** [comment]
Seems like https://golang.org/cl/284214 has been languishing. Would you be willing to nudge it across the finish line? It doesn't look very hard.

**Comment by omnide** [comment]
I'll pick this up.
