### ISSUE TITLE
Build Issue on Windows

### ISSUE THREAD

**Issue by tossp** [golang/go#44782]
### What version of Go are you using (`go version`)?

<pre>
C:\Users\ts\develop\go.old\bin>go version
go version go1.15.8 windows/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
C:\Users\ts\develop\go.old\bin>go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ts\AppData\Local\go-build
set GOENV=C:\Users\ts\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\ts\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\ts\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,https://goproxy.io,direct
set GOROOT=C:\Users\ts\develop\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\ts\develop\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fmessage-length=0 -fdebug-prefix-map=C:\Users\ts\AppData\Local\Temp\go-build693598030=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

Try to compile f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8 

### What did you expect to see?

Compiled successfully

### What did you see instead?

C:\Users\ts\develop\go\src>all.bat
Building Go cmd/dist using C:\Users\ts\develop\go.old
Building Go toolchain1 using C:\Users\ts\develop\go.old
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
go install cmd/compile: copying C:\Users\ts\AppData\Local\Temp\go-build888002794\b092\exe\a.out.exe: open C:\Users\ts\develop\go\pkg\tool\windows_amd64\compile.exe: The process cannot access the file because it is being used by another process.
go tool dist: FAILED: C:\Users\ts\develop\go\pkg\tool\windows_amd64\go_bootstrap install -gcflags=all= -ldflags=all= -i cmd/asm cmd/cgo cmd/compile cmd/link: exit status 1

**Comment by AlexRouSg** [comment]
I would suggest chcking your antivirus first.

**Comment by tossp** [comment]
I tried to close Micorsoft Defender, but failed. It can be compiled in 1.15. x

**Comment by AlexRouSg** [comment]
I am unable to reproduce this on windows and the error message ("The process cannot access the file because it is being used by another process.") is consistant with a antivirus interfering. 

Not much can be done unless someone can reproduce this.

**Comment by ALTree** [comment]
> Previously, version 1.15. X was compiled normally.

Often antivirus vendors incorrectly flag Go versions that were just released, while older versions work fine because their binaries were whitelisted after some week.

**Comment by tossp** [comment]
host system info

```
C:\Users\ts>systeminfo | findstr Build
OS 版本:          10.0.19041 暂缺 Build 19041
```

**Comment by tossp** [comment]
![go](https://user-images.githubusercontent.com/2138631/109976361-a4b58e80-7d36-11eb-8918-4faa5fc8d7e8.gif)

**Comment by ALTree** [comment]
I would try - if you haven't already -, in order 1) to reboot the machine 2) to nuke the go folder and clone the repo again. If the issue persists then it's very likely the antivirus, and the only things you can do are 1) disable it 2) wait for them to whitelist Go1.16 and update their signature database.

We've seen this issue in the past, it was never a bug in Go.

**Comment by networkimprov** [comment]
@gopherbot add OS-Windows

**Comment by tossp** [comment]
@ALTree  Thank you very much for your help. According to your suggestion, I tried the same question again

**Comment by AlexRouSg** [comment]
I tried turning on windows defender and it still compiled fine for me. 
So you might want to look at other security software you have.

If you are using onedrive or other backup software on your user folder, it could cause this if it tries to sync at the same time you're compileing.

**Comment by tossp** [comment]
@AlexRouSg  Thank you very much. I retested as you suggested, but I still couldn't compile. This should be a special case.
