### ISSUE TITLE
x/website: dead anchor in download page

### ISSUE THREAD

**Issue by ALTree** [golang/go#44780]
https://golang.org/dl/ says:

> See https://proxy.golang.org/privacy for privacy information about these services and the [go command documentation](https://golang.org/cmd/go/#hdr-Module_downloading_and_verification) for configuration details including how to disable the use of these servers or use different ones. 

The link on ` go command documentation` points to https://golang.org/cmd/go/#hdr-Module_downloading_and_verification, but no such anchor exists at that page.

cc @dmitshur @stevetraut

**Comment by dmitshur** [comment]
Perhaps https://golang.org/cmd/go/#hdr-Configuration_for_downloading_non_public_code is a good place to consider linking to instead. That section gives a high level overview and links to https://golang.org/ref/mod at the bottom for more details.

CC @katiehockman, @jayconrod.

**Comment by dmitshur** [comment]
Right, the link I mentioned would be better if the "how to disable the use of" part was linked, but it's not.

My suggestion for CL 299129 would be to a minimal change that removes the (broken) anchor, leaving the link to the go command documentation, where "configuration details" are indeed described.
