### ISSUE TITLE
x/crypto: does x/cryto/ssh server supports AcceptEnv?

### ISSUE THREAD

**Issue by dyrone** [golang/go#44781]
As the issue title describes, does the x/cryto/ssh daemon server supports the AcceptEnv config?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
