### ISSUE TITLE
cmd/cgo: Calling C.SetEvent() with an event from C returns an invalid handler (error code 6)

### ISSUE THREAD

**Issue by FWidel** [golang/go#44807]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOHOSTARCH=amd64
set GOHOSTOS=windows
</pre></details>

### What did you do?
I created event in C:
```
 sg_hEventRecv = CreateEvent(nullptr, FALSE, FALSE, nullptr);
 VSCAN_SetRcvEvent(1, sg_hEventRecv)

```
Then I tried to use this event in cgo:
```
var event C.HANDLE
func signalState(){
C.SetEvent(event) 
}

//export VSCAN_SetRcvEvent
func VSCAN_SetRcvEvent(Handle VSCAN_HANDLE, Event C.HANDLE) int {
    event = Event
    return 0
}
```

### What did you expect to see?
To be able to call C.SetEvent(event), with event passed directly from C

### What did you see instead?
 error code 6 (invalid handler).

**Comment by AlexRouSg** [comment]
Please provide a complete runable example.
The following test program runs without error.

```
package main

/*
#include <windows.h>
#include <synchapi.h>

extern void VSCAN_SetRcvEvent(HANDLE);

static void test() {
	VSCAN_SetRcvEvent(CreateEvent(NULL, 0, 0, NULL));
}
*/
import "C"
import (
	"fmt"
)

var event C.HANDLE

func main() {
	C.test()

	if C.SetEvent(event) == 0 {
		fmt.Printf("%x\n", C.GetLastError())
	}
}

//export VSCAN_SetRcvEvent
func VSCAN_SetRcvEvent(Event C.HANDLE) {
	event = Event
}
```
