### ISSUE TITLE
x/pkgsite: page with the stdlib code is not UX-friendly (as it was before)

### ISSUE THREAD

**Issue by cristaloleg** [golang/go#44832]
### What is the URL of the page with the issue?
https://pkg.go.dev/encoding/base64#Encoding.Decode which redirects to 
https://go.googlesource.com/go/+/go1.16/src/encoding/base64/base64.go 

But it doesn't matter, 'cause the problem is related to https://go.googlesource.com 
 
### What is your user agent?
- Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:86.0) Gecko/20100101 Firefox/86.0
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15 
 
### Screenshot
Nothing to show.
 
### What did you do?
I would like to see the source code for some stdlib packages. https://pkg.go.dev now redirects to https://go.googlesource.com but https://godoc.org (and early pkg.go.dev ?) has redirected to https://github.com
 
 
### What did you expect to see?
Same features as on Github:
- download 'raw' code
- manually copy the whole file
- ~~see commits history~~
- ~~see git blame~~
- ~~file history (commits, links to the issues and so on)~~
 
 
### What did you see instead?
Sadly current UX and UI looks like this:
- Link to the raw code (named 'txt' at the end of the page) gives base64 of the file, which is a strange format for the code (txt!) to be read by a human.
- Manual copy removes empty lines (same behaviour between 3 browsers, no addons) (UPD: copy file content on the page, paste into IDE or any other editor)
- ~~No link to commits~~
- ~~No link to git blame~~
- ~~Nothing at all :(~~

I understand why Go stdlib is served via https://go.googlesource.com but still it's too feature limited to make daily work easy and simple.

Thank you.

UPD: updated after https://github.com/golang/go/issues/44832#issuecomment-791937266 comment, my bad.

**Comment by fzipp** [comment]
> Link to the raw code (named 'txt' at the end of the page) gives base64 of the file, which is a strange format for the code (txt!) to be read by a human.
Manual copy removes empty lines (same behaviour between 3 browsers, no addons)
No link to commits
No link to git blame
Nothing at all :(


Not sure what you mean. I see all of this:

![git-blame-etc](https://user-images.githubusercontent.com/598327/110207936-6b8c3400-7e86-11eb-94db-666ce26084bc.png)

**Comment by cristaloleg** [comment]
@fzipp my bad, it's. `[log]` and `[blame]` works as expected (whoever links to the issue aren't supported, just `golang/goXXX` or `#XXX`).

`[file]` redirect to the same page, but not a raw file as expected (only by me?)

**Comment by tmthrgd** [comment]
This and #44829 are duplicates. (This issue has more engagement and detail from what I can tell).

**Comment by seankhliao** [comment]
an option would be codesearch: https://cs.opensource.google/go which I think has better linking

**Comment by cristaloleg** [comment]
@seankhliao even better!
