### ISSUE TITLE
reflect: TypeOf(unsafe.Pointer(nil)).PkgPath() returns "", not "unsafe"

### ISSUE THREAD

**Issue by mdempsky** [golang/go#44830]
The documentation for reflect.Type.PkgPath says:

```
    // PkgPath returns a defined type's package path, that is, the import path
    // that uniquely identifies the package, such as "encoding/base64".
    // If the type was predeclared (string, error) or not defined (*T, struct{},
    // []int, or A where A is an alias for a non-defined type), the package path
    // will be the empty string.
```

unsafe.Pointer is not listed as a predeclared type: https://golang.org/ref/spec#Predeclared_identifiers (Though go/types lists it as one: https://golang.org/pkg/go/types/#BasicKind)

So it seems to reason that PkgPath should return "unsafe", but it instead returns "": https://play.golang.org/p/ZnUOgHjwz58

/cc @griesemer @ianlancetaylor

**Comment by odeke-em** [comment]
@mdempsky, thank you for catching this discrepancy, nice work! If I may ask, perhaps should we repurpose this as a proposal to include unsafe.Pointer into builtin but also to update the spec? I think this was just an oversight from commit https://github.com/golang/go/commit/20850fc014c27a9df4f4201844c0136725202800 almost 12 years ago in which we perhaps forgot to update the spec. @robpike @rsc @griesemer @ianlancetaylor is my assumption correct? Thank you.

**Comment by mdempsky** [comment]
unsafe.Pointer is mentioned in the spec. It's also declared in package unsafe, not the universe, so it's properly not listed as a predeclared type/identifier. I don't see any reason to change the spec here.

**Comment by ianlancetaylor** [comment]
At first glance this seems like a compiler bug to me.  It's probably treating `unsafe.Pointer` as a predeclared type rather than as a type defined in the "unsafe" package, so it's probably generating an `uncommonType` struct with a zero `pkgPath` field.  Or something like that.

**Comment by mdempsky** [comment]
I can believe it's actually a compiler bug.

FWIW, it looks like with gccgo, both PkgPath and also Name return `""`.

**Comment by ianlancetaylor** [comment]
For gccgo it's a libgo bug, because libgo holds the unique type descriptor for `unsafe.Pointer` (https://go.googlesource.com/gofrontend/+/refs/heads/master/libgo/runtime/go-unsafe-pointer.c).  But as far as I know the gc compiler doesn't work that way.

**Comment by mdempsky** [comment]
Sure. I'm just pointing out a similar issue also affects gccgo.

**Comment by go101** [comment]
It looks Go spec views unsafe things as builtin things in several places.
