### ISSUE TITLE
Search is gone

### ISSUE THREAD

**Issue by 89z** [golang/go#44835]
The Go site used to have a search feature, like this:

https://golang.org/search?q=ReadFrom

I know this existed up until as recent as 2021-02-14, from my browser history.
However now if you visit that link, you just get this:

~~~
File search
search

open REDACTED: file does not exist
~~~

**Comment by AlexRouSg** [comment]
It was intentionally removed. See #44357

**Comment by ALTree** [comment]
Closing since it has been removed intentionally.
