### ISSUE TITLE
cmd/go: documentation at golang.org for cmd/go has confusing formatting

### ISSUE THREAD

**Issue by kortschak** [golang/go#44846]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Visit [this documentation](https://golang.org/cmd/go/#hdr-Compile_and_install_packages_and_dependencies).

### What did you expect to see?

Properly formatted bullet points if they must be used.

### What did you see instead?

Bullet points that have \<pre\> text due to >1 space indent.

![Screenshot from 2021-03-08 07-10-07](https://user-images.githubusercontent.com/275221/110254130-b66c8f80-7fdd-11eb-85e1-72e563aca7b1.png)

The current system for documentation rendering is not capable of rendering multi-line bullet points with consistent indentation, so probably that formatting approach shouldn't be used.

**Comment by jayconrod** [comment]
@gopherbot Please backport to 1.16. This is a fix for documentation that will be current for several more months.
