### ISSUE TITLE
cmd/go: malformed import path "example.com/vers/β": invalid char 'β'

### ISSUE THREAD

**Issue by martin-flower** [golang/go#44842]
<pre>
go version go1.16 darwin/arm64
</pre>

issue reproduced with latest release

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary>
<br>
<pre>
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/martin/Library/Caches/go-build"
GOENV="/Users/martin/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/martin/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/martin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/martin/temp/vers/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7m/0mprszbx57zc2td3x0kj3l580000gn/T/go-build706797998=/tmp/go-build -gno-record-gcc-switches -fno-common"</pre>
</details>

### What did you do?
<pre>
package main
import (
	"fmt"
	"example.com/vers/β"
)

func main() {
	fmt.Println("Hello, World!")
	fmt.Printf("Somewhere β:%s", β.Somewhere())
}
</pre>

### What did you expect to see?

expected to compile correctly

### What did you see instead?
malformed import path "example.com/vers/β": invalid char 'β'

**Comment by martin-flower** [comment]
Compiles and executes correctly on

`go version go1.15.8 darwin/amd64
`

**Comment by odeke-em** [comment]
Thank you for this report @martin-flower and welcome to the Go project!

So in https://github.com/golang/go/issues/43052, we made cmd/go deliberately reject module paths that were non-ASCII and particularly added a release note for Go1.16 in https://golang.org/doc/go1.16#go-command per
![C6858E99-2D85-433C-B01A-074D6E758CBA](https://user-images.githubusercontent.com/4898263/110243267-7d191e80-7f0e-11eb-88c7-7a901e2c3a5f.jpeg)

@maruel reported this same issue in https://github.com/golang/go/issues/43035 but more intentionally a regression that the team fixed for Go1.16.
Kindly cc-ing @bcmills, @jayconrod, @matloob, but I don’t think there is anything that we can do here.

**Comment by kostich** [comment]
Is there a workaround for users who have packages named with non-ASCII characters? Like, some kind of punny-code?
