### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by I-Cat** [golang/go#44847]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>
![image](https://user-images.githubusercontent.com/68921721/110257611-a5376a80-7f6c-11eb-8ab5-fd8e7bd76e06.png)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?
A windows X32 or A windows X64 Installer

### What did you see instead?
Saw a windows amd installer 
I don't own a windows Phone I Own a Windows Laptop

![image](https://user-images.githubusercontent.com/68921721/110257629-b97b6780-7f6c-11eb-9c80-bb971805c3a9.png)

**Comment by fzipp** [comment]
> What did you expect to see?
> A windows X32 or A windows X64 Installer

Both are there, you selected them in the screenshots:
amd64 is also known as x64 or x86_64 (see https://en.wikipedia.org/wiki/X86-64), and 386 is also known as x32 or x86 (see https://en.wikipedia.org/wiki/IA-32).

> What did you see instead?
> Saw a windows amd installer
> I don't own a windows Phone I Own a Windows Laptop

You're probably thinking of arm64, which is not the same as amd64.

**Comment by mdlayher** [comment]
Closing per above.
