### ISSUE TITLE
ticker.Reset undefined (type *time.Ticker has no field or method Reset)

### ISSUE THREAD

**Issue by bo-er** [golang/go#44858]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.15.6

</pre>

### Does this issue reproduce with the latest release?
I haven't test it in the latest version(1.16.0)

### What operating system and processor architecture are you using (`go env`)?

$ go env

```GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/steve/go/bin"
GOCACHE="/Users/steve/Library/Caches/go-build"
GOENV="/Users/steve/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/steve/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/steve/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5y/vj4hwy553y53q9hnqh21bnjr0000gn/T/go-build924144234=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

I create a map to store tickers:
```
topicTickerMap = make(map[string]*time.Ticker)
```
And I put ticker into this map:

```go
topicTickerMap[deviceIDAttributeName] = time.NewTicker(time.Duration(2*deviceAttribute.ScanTime) * time.Second)
```
And I reset this ticker using following code:

```go
ticker, ok := topicTickerMap[deviceIDAttributeName]
if !ok {
return fmt.Errorf("Failed to get ticker:%v", ticker)
}
ticker.Reset(time.Duration(2*deviceAttribute.ScanTime) * time.Second)
```

The above code seems fine to me, and I can actually run my program without any complaining,
HOWEVER! whenever I run 

```
docker build
```
I get this error like non-stop:
```
 ticker.Reset undefined (type *time.Ticker has no field or method Reset)
```

### What did you expect to see?

I expect to see no error  runing docker build, and it makes no sense to give this  ` (type *time.Ticker has no field or method Reset)` error, how come type *time.Ticker had no field or method Reset ??

### What did you see instead?
I see the builder just made a complain about ` (type *time.Ticker has no field or method Reset)`

### Many thanks
I appreciate your time if you go this long to the end, thank you for your attention!

**Comment by AlexRouSg** [comment]
Please confirm the `go version` running in docker.
`ticker.Reset` was added in 1.15 so you need 1.15 or 1.16 running in docker.

**Comment by bo-er** [comment]
> Please confirm the `go version` running in docker.
> `ticker.Reset` was added in 1.15 so you need 1.15 or 1.16 running in docker.

OMG! I am just new to Go and I have NO IDEA that ticker wasn't part of Go until version 1.15, and I just checked my Dockerfile and I found this:
```
FROM golang:1.14.1 as builder
```

YES! The problem is clear! Thank you Alex! And thank you Brad! Wish you both a good day!❤️
