### ISSUE TITLE
Can not install go module !   what's problem ?

### ISSUE THREAD

**Issue by watangca** [golang/go#44856]
What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/folls/Library/Caches/go-build"
GOENV="/Users/folls/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/folls/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/folls/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dr/0hks8_y50xqffqdrtqtpdl3c0000gn/T/go-build2301911714=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.16 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.16
uname -v: Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
ProductName:	macOS
ProductVersion:	11.2.2
BuildVersion:	20D80
lldb --version: lldb-1200.0.44.2
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
</pre></details>

### What did you do?

Install go extension module with vscode 

### What did you see instead?

Error Log

ools environment: GOPATH=/User/folls/Desktop/go
Installing 1 tool at /User/folls/Desktop/go/bin in module mode.
  gopls

Installing golang.org/x/tools/gopls FAILED
{
 "killed": false,
 "code": 1,
 "signal": null,
 "cmd": "/usr/local/go/bin/go get -v golang.org/x/tools/gopls",
 "stdout": "",
 "stderr": "go: writing stat cache: mkdir /User: read-only file system\ngo: downloading golang.org/x/tools/gopls v0.6.6\ngo: writing stat cache: mkdir /User: read-only file system\ngo: downloading golang.org/x/tools v0.1.0\ngo get golang.org/x/tools/gopls: mkdir /User: read-only file system\n"
}

1 tools failed to install.

gopls: failed to install gopls(golang.org/x/tools/gopls): Error: Command failed: /usr/local/go/bin/go get -v golang.org/x/tools/gopls
go: writing stat cache: mkdir /User: read-only file system
go: downloading golang.org/x/tools/gopls v0.6.6
go: writing stat cache: mkdir /User: read-only file system
go: downloading golang.org/x/tools v0.1.0
go get golang.org/x/tools/gopls: mkdir /User: read-only file system
 no output

**Comment by ALTree** [comment]
The error says "read-only file system"; it looks like Go cannot write files where it needs to. This is probably an issue with your machine, not a Go bug. Does that folder exist? Can you write on it?

**Comment by bcmills** [comment]
From the `go env` output, I believe this is a typo in your `GOPATH` setting.

I see (emphasis added):

<code>
GOCACHE="<b>/Users</b>/folls/Library/Caches/go-build"
GOMODCACHE="/Users/folls/go/pkg/mod"
</code>
<p/>

but:

<code>
GOPATH=<b>/User</b>/folls/Desktop/go
</code>
<p/>


So the problem here seems to be that `/Users` has been typo'd as `/User`, and the `go` command cannot create the top-level `/User` directory (no `s`) because your root directory is (correctly) not writable.
