### ISSUE TITLE
x/tools/gopls: diagnostics shown for builtin.go

### ISSUE THREAD

**Issue by mreza0100** [golang/go#44866]
I don't know if this is a bug or...
if I go to build in source code, for example ctrl + click on string type then I will see 51 errors on golang build in types
![Screenshot from 2021-03-08 20-21-31](https://user-images.githubusercontent.com/59161329/110353210-097d2b80-804c-11eb-8b6e-2c14902ba0ff.png)

Information about Go version and etc is attached in information.txt file
[information.txt](https://github.com/golang/vscode-go/files/6102923/information.txt)

**Comment by stamblerre** [comment]
Thanks for the report, @mreza0100! This is definitely a bug.
