### ISSUE TITLE
Bitdefender reports that go output is infected with variant Babar.24615

### ISSUE THREAD

**Issue by v8tix** [golang/go#44864]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 windows/386
</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\malme\AppData\Local\go-build
set GOENV=C:\Users\malme\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\malme\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\malme\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Software\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Software\go\pkg\tool\windows_386
set GOVCS=
set GOVERSION=go1.16
set GCCGO=gccgo
set GO386=sse2
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\malme\AppData\Local\Temp\go-build2696886916=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
Because it´s not a problem related with the source code. I configured my antivirus to delete the variant each time.
![2021-02-27_16-13-01](https://user-images.githubusercontent.com/4001172/110350073-5c7dc100-8001-11eb-85b9-3fd0f864a246.png)

**Comment by ALTree** [comment]
False positive, happens all the time when a new Go version is release, please report the issue to the vendor.
