### ISSUE TITLE
x/tools/gopls: cold goimports cache causes slow code actions on first save

### ISSUE THREAD

**Issue by findleyr** [golang/go#44863]
For correctness reasons, gopls uses a separate goimports cache per workspace folder.  In some environments, warming up this cache can be costly (see also #42861 and #41969).  Users of the gopls daemon will pay this warm-up cost for each new session, which can be disruptive for workflows based around short-lived sessions (e.g. opening vim to perform a quick edit).

It's probably possible to significantly mitigate this warm-up time by sharing the directory scan of the module cache across goimports processEnvs.  From discussion with @heschik, we already have a [`dirInfoCache`](https://cs.opensource.google/go/x/tools/+/master:internal/imports/mod_cache.go;l=97;drc=92778473c2e66cce9cca86de3a98d22b1c550dea) abstraction, and it probably only depends on (`GOPATH`, `GOOS`, and `GOARCH`).  If this state were shared through the gopls cache, goimports would probably be quick for new vim sessions.

This is following up on a discussion in Slack with @myitcv, @leitzler, and @mvdan.

CC @stamblerre

**Comment by findleyr** [comment]
Another potential solution to the underlying problem could be to change the timing of our imports cache warm-up. Currently it's kicked off at first usage (unimported completion, code action, etc.).  Maybe we could/should just warm up the cache immediately following initialization.

**Comment by stamblerre** [comment]
After some discussion, we've agreed to try warming up the imports cache after the first `didOpen` of a Go file instead of after the first completion request.

**Comment by myitcv** [comment]
Thanks very much for raising this, @findleyr 

> Maybe we could/should just warm up the cache immediately following initialization.

This would help compared to the situation today, but would still represent unnecessary processing of the module cache each time a new view is established (and then a period refresh for each view).

If however, per your suggestion, we shared the goimports directory cache across views _and_ kicked off a scan of that on initialisation (in the case `-remote` is being used) then that would be the ultimate solution to my mind.

(I can imagine that when `-remote` is _not_ being used that doing anything more aggressive will lead to problems in the other direction, i.e. potentially needless processing of the modules cache)

**Comment by findleyr** [comment]
I believe this should be as fixed as it's going to get, for the time being. Shared sessions on a common remote will share their view of the module cache.

There's a lot we can do to speed up the initial indexing of the module cache, but that is more significant engineering effort and best left for a holistic redesign of goimports.

**Comment by myitcv** [comment]
This is outstanding, thank you. Very much looking forward to giving this all a test!
