### ISSUE TITLE
time, runtime: zero duration timer takes 2 minutes to fire

### ISSUE THREAD

**Issue by prattmic** [golang/go#44868]
Very rarely, zero duration timers fail to fire for 2 minutes. [This program](https://play.golang.org/p/ec0Gr2u7xbe) will occassionally fail. e.g.,

```
$ while ./timer; do echo again; done
again
again
again
again
again
again
again
again
again
panic: Expected time to get value from Timer channel to be less than 2 sec, took 2m0.006359722s, time on channel is 2021-03-08 15:17:38.623999432 -0500 EST m=+120.798106019, current time is 2021-03-08 15:17:38.624042501 -0500 EST m=+120.798149081
```

This reproduces on 1.16 (linux-amd64, other platforms not tested), but not 1.15. Thus this is probably more fallout from http://golang.org/cl/232298.

Failure seems to consistently occur at 2 minutes, which is a strong indication that this is related to the 2 minute force GC period. Most likely the scheduler is completely missing the timer until forced GC kicks it awake again. That makes this distinct from #44343, where timer expiration is slower but never missed.

cc @ChrisHines @aclements @mknyszek

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport to 1.16.

This issue can cause timers to fire up to two minutes late.

**Comment by mdempsky** [comment]
> NewTimer creates a new Timer that will send the current time on its channel after at least duration d.

Technically, 2 minutes is after at least 0 seconds. :>

**Comment by prattmic** [comment]
This is a bug in `timerpMask`. i.e, http://golang.org/cl/264477.

The logic behind `timerpMask` is based on the assumption that a P will only add timers to its own heap ([comment](https://cs.opensource.google/go/go/+/master:src/runtime/proc.go;l=5657;drc=125eca0f7210da1bbf1a4a1460a87d1c33366b99;bpv=1;bpt=1)).

This isn't quite true, as `addtimer` runs in a preemptible context, making the following sequence possible:

1. Call `addtimer` on P 0, G 1.
2. `addtimer` computes `pp := <*p for P 0>`.
3. P 0 preempted (likely in morestack on the `lock` call). G 1 placed on runq as runnable.
4. `timerpMask` cleared for P 0, as it has no timers.
5. P 1 starts running. `timerpMask` set for P 1, as "it may add a timer at any time".
6. G 1 continues execution on P 1, adding the timer to P 0's timer heap.

P 0's `timerpMask` bit will never be set until P 0 runs again, causing all timer stealing to skip P 0 and miss the timer.

`timerpMask` has this strange update location instead of simply updating directly in `doaddtimer` because updating a centralized data structure in the middle of the timer code adds too much contention.

Since it doesn't affect correctness, I believe it would be sufficient to fix this problem by updating `timerpMask` in the case of `doaddtimer` `pp != getg().m.p.ptr()`. This should be extremely rare, so it won't affect performance of the normal case.

**Comment by prattmic** [comment]
Alternatively, it may be cleaner to keep the expectation the `addtimer` only adds to its own P by making it retry if the P has changed after locking.
