### ISSUE TITLE
reflect: no efficient way to append to, or grow, a slice

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#44870]
This is based on https://groups.google.com/g/golang-nuts/c/S2gBW3BV4QU/m/mSPh2_FzBgAJ :

The reflect package has no efficient way to append to a slice represented as a `reflect.Value`.  This is available in the reflect2 package: https://pkg.go.dev/github.com/modern-go/reflect2#UnsafeSliceType.Append.  The reflect2 package also has a method to grow a slice to a new size: https://pkg.go.dev/github.com/modern-go/reflect2#UnsafeSliceType.Grow.

**Comment by go101** [comment]
If there will be something to do here, I think it would be a good chance to make slice grow implementation in reflection and non-reflection consistent: https://github.com/golang/go/issues/41239#issuecomment-704425822

**Comment by robpike** [comment]
What is "efficient"? It's possible to grow a slice with the reflect package using more primitive mechanisms. Is it worth providing a special case for that operation? How does one decide what reflect should optimize for?

**Comment by martisch** [comment]
Previous discussion about Append allocating a new slice header (in addition to potentially a new backing array) always: https://github.com/golang/go/issues/32424#issuecomment-636492432

**Comment by ianlancetaylor** [comment]
Sorry, I got confused here.  I think the reflect package is fine.

**Comment by advancedwebdeveloper** [comment]
CC @funny-falcon
