### ISSUE TITLE
cmd/link/internal/ld: TestWindowsIssue36495 fails on windows

### ISSUE THREAD

**Issue by erifan** [golang/go#44874]
Found this test failure from https://storage.googleapis.com/go-build-log/e16933d5/windows-amd64-2016_f006643d.log and https://storage.googleapis.com/go-build-log/e16933d5/windows-386-2008_32f17999.log, I'm sure it has nothing to do with the CL being tested.

**Comment by erifan** [comment]
The issue has been resolved by https://go-review.googlesource.com/c/go/+/299929

**Comment by tklauser** [comment]
I just hit this on https://golang.org/cl/299989 (based on latest `master`, with https://golang.org/cl/299929 in place), see https://storage.googleapis.com/go-build-log/041e4871/windows-amd64-2016_a33ebfaf.log

**Comment by tklauser** [comment]
> I just hit this on https://golang.org/cl/299989 (based on latest master, with https://golang.org/cl/299929 in place), see https://storage.googleapis.com/go-build-log/041e4871/windows-amd64-2016_a33ebfaf.log

Sorry, I didn't realize https://golang.org/cl/299929 wasn't submitted yet when writing this.
