### ISSUE TITLE
cmd/go: 'go get' does not add missing hash to go.sum when ziphash file missing from cache [1.15 backport]

### ISSUE THREAD

**Issue by jayconrod** [golang/go#44872]
I'm requesting that the fix for #44749 be backported to Go 1.15.

The problem affects both 1.15 and 1.16, though it is less noticeable on 1.15. I expect the fix to apply cleanly to 1.15, perhaps with a small change to the regression test.

(Manually created this issue due to #25574).

**Comment by dmitshur** [comment]
Approving per discussion in a release meeting. This backport applies to both 1.16 (#44812) and 1.15 (this issue).
