### ISSUE TITLE
missing go.sum entry for module providing package

### ISSUE THREAD

**Issue by BlueTearsY** [golang/go#44873]
Hello,
I use OpenWrt SDK compile the bettercap,but an error was encountered

`Building targets
../../../../../dl/go-mod-cache/golang.org/x/net@v0.0.0-20191014212845-da9a3fd4c582/idna/idna10.0.0.go:25:2: missing go.sum entry for module providing package golang.org/x/text/secure/bidirule (imported by golang.org/x/net/idna); to add:
	go get golang.org/x/net/idna@v0.0.0-20191014212845-da9a3fd4c582
../../../../../dl/go-mod-cache/golang.org/x/net@v0.0.0-20191014212845-da9a3fd4c582/idna/idna10.0.0.go:26:2: missing go.sum entry for module providing package golang.org/x/text/unicode/bidi (imported by golang.org/x/net/idna); to add:
	go get golang.org/x/net/idna@v0.0.0-20191014212845-da9a3fd4c582
../../../../../dl/go-mod-cache/golang.org/x/net@v0.0.0-20191014212845-da9a3fd4c582/idna/idna10.0.0.go:27:2: missing go.sum entry for module providing package golang.org/x/text/unicode/norm (imported by golang.org/x/net/idna); to add:
	go get golang.org/x/net/idna@v0.0.0-20191014212845-da9a3fd4c582
`

the go version is 1.16, before I use 1.15 is alright.
 please help me,what should I do? please ,please,please.  Thanks
![20210309085954](https://user-images.githubusercontent.com/20371554/110402196-eedf9c80-80b5-11eb-8f68-9f46e4c046d5.png)

**Comment by bcmills** [comment]
Did you run the `go get` commands suggested by the errors?

**Comment by bcmills** [comment]
(I see that `bettercap` is building using a `Makefile`, so https://github.com/bettercap/bettercap/issues/842 is probably the right place to discuss this error.)

**Comment by ooopSnake** [comment]
i have same issue,
workaround: `go build -mod=mod `

**Comment by BlueTearsY** [comment]
Thank you, I've solved the problem

**Comment by rblaine95** [comment]
Just leaving a comment here for the people that use [insert search engine name here] and come across this issue, this is how I fixed it for me:

Was having a very similar issue with building go but the module error was:
```
/go/pkg/mod/github.com/moby/moby@v17.12.0-ce-rc1.0.20200618181300-9dc6525e6118+incompatible/pkg/system/path.go:9:2: missing go.sum entry for module providing package github.com/containerd/continuity/pathdriver (imported by github.com/docker/docker/pkg/system); to add:
	go get github.com/docker/docker/pkg/system@v1.4.2-0.20200203170920-46ec8731fbce
make: *** [Makefile:78: /opt/build/helm/bin/helm] Error 1
```
I noticed that I had updated to Go 16, my last successful build was on Go 15.
Downgrading to Go 15 fixed it for me

**Comment by xdevs23** [comment]
Just running `go get -a` fixed the issue for me.
