### ISSUE TITLE
Go program using Cobra framework hang in execution

### ISSUE THREAD

**Issue by ionutnechita** [golang/go#44889]
Hi Golang Team,

I use Windows / Windows Server 2019 environment for run my CLI, but observe hang in execution.
GO version: go version go1.16 windows/amd64
Windows Server 2019 Version 1809 (OS Build 17763.737)

**Comment by ianlancetaylor** [comment]
There are many possible reasons for this.  We would need much more information to know whether this is a bug in Go, or a bug in your program, or a bug somewhere else.

If you are looking for help debugging the problem, please do not use this issue tracker, but instead use a forum.  See https://golang.org/wiki/Questions.  Thanks.

**Comment by mvdan** [comment]
Closing old issues that still have the WaitingForInfo label where enough details to investigate weren't provided. Feel free to leave a comment with more details and we can reopen.
