### ISSUE TITLE
Go 1.16 build error on centos 6.10 # bfd_get_reloc_size

### ISSUE THREAD

**Issue by qAison** [golang/go#44880]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/data/Dev/GoPath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/data/Dev/GoPath"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1492201664=/tmp/go-build"
</pre></details>

<details><summary><code>cat /etc/issue</code> Output</summary><br><pre>
$ cat /etc/issue
CentOS release 6.10 (Final)
Kernel \r on an \m
</pre></details>

<details><summary><code>uname -a</code> Output</summary><br><pre>
$ uname -a
Linux cs.ai.local 2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
</pre></details>

<details><summary><code>ld -v</code> Output</summary><br><pre>
$ uname -a
GNU ld version 2.20.51.0.2-5.48.el6 20100205
</pre></details>

<details><summary><code>gcc -v</code> Output</summary><br><pre>
$ gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC)
</pre></details>

### What did you do?
```
package main

// go1.15.8 can succeed 

// const int x = 42;
import "C"

import "fmt"

func main() {
  fmt.Println(int(C.x))
}
```

go build

### What did you expect to see?
build success

### What did you see instead?
command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-668338693/000005.o(.text+0x74): unresolvable H>HFH~H~HHHHHHHD relocation against symbol `stderr@@GLIBC_2.2.5'
/usr/bin/ld: BFD version 2.20.51.0.2-5.48.el6 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size

/usr/bin/ld: Please report this bug.

collect2: ld returned 1 exit status

**Comment by AlexRouSg** [comment]
According to #43605 and https://github.com/golang/go/wiki/MinimumRequirements
Go now requires gcc >= 4.6

**Comment by qAison** [comment]
> 根据[＃43605](https://github.com/golang/go/issues/43605)和https://github.com/golang/go/wiki/MinimumRequirements根据
> Go现在需要gcc> = 4.6

Okay thank you

**Comment by dwillemv** [comment]
This repro fails with gcc version 4.8.3 as well.

**Comment by ianlancetaylor** [comment]
The issue here is actually not the version of GCC, but the version of the linker.

**Comment by mx-psi** [comment]
> The issue here is actually not the version of GCC, but the version of the linker.

Is the minimum linker version documented? If not, should I open a new issue for this?

**Comment by seankhliao** [comment]
Feel free to edit the wiki page
