### ISSUE TITLE
cmd/go: 'go mod init' should report an error if module path is in standard library

### ISSUE THREAD

**Issue by 89z** [golang/go#44896]
If I have a file `a_test.go`:

~~~go
package main
import "testing"

func TestAbs(t *testing.T) {
   t.Error()
}
~~~

This test works as expected:

~~~
PS C:\> go mod init example
PS C:\> go test
--- FAIL: TestAbs (0.00s)
~~~

However if I happen to use a builtin name, I get unexpected result:

~~~
PS C:\> go mod init log
PS C:\> go test
PASS
ok      log     0.030s
~~~

My Go:

~~~
go version go1.16 windows/amd64
~~~

**Comment by jayconrod** [comment]
Closely related: #35270 and #39285

I think the difference here is that `go mod init` should fail if the module path is a package (or a prefix of a package) in the standard library.

**Comment by 89z** [comment]
@jayconrod I agree, as even though `init` currently succeeds, if you try to `import` it would just `import` the standard package rather than the local package.

**Comment by jayconrod** [comment]
Yeah, that ought to be an error as well (covered by #39285 I think).

Reporting an error from `go mod init` won't completely prevent this (`go.mod` could be written by hand), but it would be a good place to catch this early.

**Comment by bcmills** [comment]
I'm not entirely convinced that `go mod init` should reject these. I could imagine someone using a module of this form to prototype an addition they're proposing for the standard library, or to polyfill a package added in a subsequent Go release.

**Comment by 89z** [comment]
Ok fine, but a warning at least? I could see some people going crazy because they cant figure out what they are doing wrong.

**Comment by 89z** [comment]
closing for lack of interest
