### ISSUE TITLE
x/pkgsite: "copy path to clipboard" is off-center when hovered on Firefox

### ISSUE THREAD

**Issue by mvdan** [golang/go#44909]
![swappy-20210310_104748](https://user-images.githubusercontent.com/3576549/110618212-700a6280-818e-11eb-9a25-e0eba95a0365.png)

Happens on Firefox 86 on Linux for me, no matter the zoom level and including on incognito.

Note that this does not happen on Chromium 89.

**Comment by peterhellberg** [comment]
Same issue on Firefox Developer Edition 87.0b1 under macOS Mojave, so not limited to only Linux.
