### ISSUE TITLE
cmd/go: 'go install' interactively prompts for SSH password when fetching from a private Git repo

### ISSUE THREAD

**Issue by bcmills** [golang/go#44904]
The `go` command intentionally tries to suppress interactive prompts using `GIT_TERMINAL_PROMPT=0`.

Unfortunately, that isn't actually sufficient to suppress Git terminal prompts: if Git ends up connecting over SSH, then the `ssh` command itself may hijack the console to ask for a password.

According to various [scraps of information on the Internet](https://stackoverflow.com/questions/37182847/how-do-i-disable-git-credential-manager-for-windows), we may also need to set  `-o·BatchMode=yes` in our `GIT_SSH_COMMAND`, and perhaps also `GCM_INTERACTIVE=never`.

For me, this manifested as a hang in the `mod_get_private_vcs` test at [CL 297950](https://golang.org/cl/297950).

CC @jayconrod @matloob @kevinburke

**Comment by bcmills** [comment]
We discussed this issue with @rsc on 2021-03-23 and decided to give it a try for Go 1.17 (with the understanding that it might be reverted during the beta or in a point release if it turns out to be too invasive a fix).

(I hadn't dusted off the CL until just now because I was focused on landing #36460 before the freeze.)

**Comment by kevinburke** [comment]
> We discussed this issue with @rsc on 2021-03-23 and decided to give it a try for Go 1.17 (with the understanding that it might be reverted during the beta or in a point release if it turns out to be too invasive a fix).

Is there something that happened that made you bring this up just now? I haven't thought about this since you merged the referenced CL in March

**Comment by bcmills** [comment]
I was going through my outstanding changes and noticed that [CL 300157](https://golang.org/cl/300157) was still marked `wait-issue`, and remembered that we had actually discussed the issue enough to move forward.

**Comment by ckcr4lyf** [comment]
Curious at to why this was implemented - what is the requirement to disable password prompts unconditionally? It breaks yubikey ssh for me (see above referenced issue)

**Comment by BenjamenMeyer** [comment]
Honestly, it would be best to leave it to the user to decide how they want to be prompted.
I know some folks love to use SSH-Agent, and others simply don't put passwords on their SSH Keys; however...

- SSH Agent introduces security issues as it keeps keys in memory unencrypted for the duration of its operation until the user explicitly removes it from memory, most don't
- I've had at least one employer require SSH Keys to have password protection (ironically they later required SSH Agent for their SSH Bastion proxy too).

Personally I neither like using SSH Agent nor do I like having my SSH Keys unprotected. I keep passwords on them for a reason and I want to know whenever the key is used by a process.  If the goal is to reduce the number of prompts (a good goal) then perhaps there are other more secure ways to do so.
