### ISSUE TITLE
Typo in tutorial/call-module-code

### ISSUE THREAD

**Issue by pgalbavy** [golang/go#44906]
### What version of Go are you using (`go version`)?

Tutorial website / go 1.16

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

https://golang.org/doc/tutorial/call-module-code -> 

https://github.com/golang/website/blob/7e301e09e5c301ad4c225e8e240b6c3a0ba3d138/_content/doc/tutorial/call-module-code.html#L147

(Tested on Windows under VSC Terminal)

### What did you do?

Reading, following examples

### What did you expect to see?

PS C:\Users\peter\go> go mod edit -replace="example.com/greetings=../greetings"
go: cannot find main module; see 'go help modules'

### What did you see instead?

PS C:\Users\peter\go> go mod edit -replace=example.com/greetings=../greetings
go mod: -replace=example: need old[@v]=new[@w] (missing =)

**Comment by AlexRouSg** [comment]
`go mod edit -replace=example.com/greetings=../greetings` is a valid command string.
Go's flag parsing allows for `-flag=asdf` and `-flag asdf`
You can read it as `-replace="example.com/greetings=../greetings"`

**Comment by pgalbavy** [comment]
Except, if you try it, it doesn't work a per example in tutorial - perhaps adding quotes would also be a suitable fix; This may only break on Windows too.

**Comment by AlexRouSg** [comment]
Ahh yeah it looks like it's only in power shell, even cmd runs it fine.

**Comment by pgalbavy** [comment]
My fault for trying an IDE instead of just vi...

**Comment by AlexRouSg** [comment]
If you want to contribute the fix please read https://golang.org/doc/contribute

**Comment by pgalbavy** [comment]
OK, will try, thanks.

**Comment by tmthrgd** [comment]
I think this is probably a duplicate of #43179 and an example of the still unfixed PowerShell/PowerShell#6291.
