### ISSUE TITLE
net/http: toHTTPError() should use errors.Is() function

### ISSUE THREAD

**Issue by claudiofelber** [golang/go#44923]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Claudio\AppData\Local\go-build
set GOENV=C:\Users\Claudio\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Claudio\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Claudio\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Development\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Development\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Claudio\AppData\Local\Temp\go-build3762994767=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I am using `http.FileSystem` with some code that wraps errors with a stack trace:

```go
import (
    ...
    "github.com/pkg/errors"
)

func (cfs *CachingFileSystem) Open(name string) (http.File, error) {
    name = strings.TrimPrefix(name, "/")
    originalName := cfs.reverseCacheMap[name]
    if originalName == "" {
        originalName = name
    }
    f, err := cfs.FileSystem.Open(originalName)
    if os.IsNotExist(err) {
        f, err = cfs.openExternal(originalName)
    }
    return f, errors.WithStack(err)
}
```

When a file does not exists, the wrapped `os.ErrNotExist` is not detected by the net/http `toHTTPError()` function, because it is still using `os.IsNotExists(err)` and therefore the function returns `StatusInternalServerError` instead of `StatusNotFound`. See: https://github.com/golang/go/blob/1811aeae66bee899317403c92c83b56673919775/src/net/http/fs.go#L673-L675

By replacing `os.IsNotExists(err)` with `errors.Is(err, os.ErrNotExist)` the `os.ErrNotExists` condition is dectected correctly:

```go
if errors.Is(err, os.ErrNotExist) {
    return "404 page not found", StatusNotFound
}
```

### What did you expect to see?

`toHTTPError()` returning `StatusNotFound`

### What did you see instead?

`toHTTPError()` returning `StatusInternalServerError`

**Comment by seankhliao** [comment]
CC @bradfitz @rsc @empijei via [owners](https://dev.golang.org/owners).

**Comment by neild** [comment]
This should compare against `fs.ErrNotExist` and `fs.ErrPermission`. (Which are the same errors as in the `io` package, but `fs` is more canonical.

The `mapDirOpenError` function should also be updated to use `errors.Is`.

With those caveats, I think this change seems reasonable.
