### ISSUE TITLE
Question: Will we get functions like filter, map, reduce for arrays/slices after generics are introduced?

### ISSUE THREAD

**Issue by enkeyz** [golang/go#44927]
Most of the programming languages, have these in their standard library, and after generics introduced, adding these functions to the standard packages shouldn't be a problem.

Is it planned?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
