### ISSUE TITLE
golang path eroor visual studio

### ISSUE THREAD

**Issue by numf6** [golang/go#44934]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.8 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/users4/.cache/go-build"
GOENV="/home/users4/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/users4/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/users4/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/7013"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/7013/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build137673137=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.15.8 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.15.8
uname -sr: Linux 5.8.0-44-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.31-0ubuntu9.2) stable release version 2.31.
gdb --version: GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
</pre></details>

### What did you expect to see?
Failed to run '/snap/bin/go env' (cwd: undefined): Error: Command failed: /snap/bin/go env GOPATH GOROOT GOPROXY GOBIN GOMODCACHE

failed to run "/snap/bin/go version": Error: Command failed: /snap/bin/go version
 cwd: undefined
failed to run "/snap/bin/go version": Error: Command failed: /snap/bin/go version
 cwd: undefined

### What did you see instead?

{
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter.notebook.ipynb",
            "filenamePattern": "*.ipynb"
        }
    ],
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "go.installDependenciesWhenBuilding": true,
    "go.gotoSymbol.includeGoroot": true,
    "go.inferGopath": true,
    "go.gotoSymbol.includeImports": true,
    "go.gopath": "home/users4/go/bin"
}

**Comment by dmitshur** [comment]
If this is an issue with the VS Code Go extension, please take a look at the [troubleshooting](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md) and [help](https://github.com/golang/vscode-go#ask-for-help) links (from https://github.com/golang/vscode-go#quick-start). Otherwise please see https://golang.org/wiki/Questions for a better place to ask for help with this.

**Comment by Abhipise81** [comment]
Hi @numf I am also facing same issue, Can you let me know how did you solved this issue.
