### ISSUE TITLE
x/website: tutorial links to removed search

### ISSUE THREAD

**Issue by oncethor** [golang/go#44937]
### What version of Go are you using (`go version`)?

<pre>
I am not using a go version, I am browing the "Tour of Go", https://tour.golang.org/methods/21

</pre>

### Does this issue reproduce with the latest release?
It's not an issue with GO, it's an issue with golang.org website

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
I am following the tour of go tutorial, and once on page https://tour.golang.org/methods/21 if you click on the "many implementations" link, you'll get a "file does not exist" error

### What did you expect to see?
The list of implementations of the  Reader interface

### What did you see instead?
Error... file does not exist

**Comment by ALTree** [comment]
Dup of golang/tour#1140, we usually use that other issue tracker for bugs in the tour's content.
