### ISSUE TITLE
https://go-tour-ru-ru.appspot.com/ not working

### ISSUE THREAD

**Issue by Nurzhas1** [golang/go#44959]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by Nurzhas1** [comment]
https://go-tour-ru-ru.appspot.com/ not working

**Comment by fzipp** [comment]
See #44382

**Comment by ALTree** [comment]
Yes, closing as a dup.
