### ISSUE TITLE
x/pkgsite: importedby number and list don't agree

### ISSUE THREAD

**Issue by danp** [golang/go#44965]
(Opening from [a convo in Slack](https://gophers.slack.com/archives/C0166L4QGJV/p1615489680019100))

https://pkg.go.dev/modernc.org/sqlite?tab=importedby says `Known importers: 16` but the number of items in the list may not agree.

@julieqiu suggested it might be a difference between these places:

https://github.com/golang/pkgsite/blob/c16d5e9c5f440307d9cc4ca393d3ced9f25dbc20/internal/postgres/details.go#L80

https://github.com/golang/pkgsite/blob/5732477f0a15fbf76e03ab057305865af7547a3e/internal/postgres/search.go#L623

> It looks like there is a bug in that we filter out certain paths when computing the count, which leads to the discrepancy.

**Comment by jba** [comment]
The fundamental reason for the discrepancy is that the importer count we use for search has a different purpose than the one displayed on the imported-by tab. 

The count for search is used for ranking, so it is adjusted to produce a better ranking. In particular, it excludes importers that [are not themselves in our set of search documents](https://github.com/golang/pkgsite/blob/5732477f0a15fbf76e03ab057305865af7547a3e/internal/postgres/search.go#L647), such as internal packages (like github.com/frioux/leatherman/internal/notes) and modules whose import path differs from their go.mod file (like github.com/circonus-labs/circonus-unified-agent).

The imported-by tab shows the search count, leading to an obvious mismatch with the list of importers. However, if it displayed the actual number of importers in the list, then it there would still be a mismatch between that number and what you see in search.

Here are some fixes:
1. Drop the condition when counting importers for search. Search quality will be reduced, but by how much? We could figure that out.
2. Exclude the same importers on the imported-by tab. Not great if you're trying to track down users of a package.
3. Use the adjusted importers for search ranking, but display the unadjusted number.

In any case, I think we should go back to displaying the actual length of the list on the imported-by tab. At least the discrepancy with the search results won't be quite as obvious.

**Comment by jba** [comment]
Re point 1 above, the differences between raw and adjusted importers can be significant. For an extreme example, k8s.io/apimachinery/pkg/types has about 46,000 importers, but only about 18,000 of those are in the search table, presumably because there are many clones of that module.

It's still not clear how much searching a particular term would be affected by the changes; that is much harder to quantify.

**Comment by jba** [comment]
We now show both counts on the importers page.
