### ISSUE TITLE
encoding/csv: add field ForceQuotes to Writer or disable triple quoting...

### ISSUE THREAD

**Issue by paulmil1** [golang/go#44966]
copy of : https://github.com/golang/go/issues/12755

seriously, theres no customization to the standard writer,
turns out that standard encoder does not quote text in format "digits - digits", then importing it to excel and you see it performed a math subtraction operation, how do i quote that - i cant, if i added a quote myself - i'd have ended up having """LOL""" 
lol, primitivity of golang in its best

**Comment by mdlayher** [comment]
The previous issue was closed and it seems nothing has changed. If you don't intend to participate in good faith and provide an updated perspective, there's no reason to keep this issue open. Closing.

**Comment by paulmil1** [comment]
dont you guys really see the problem with how primitive the csv encoder is? LOL

**Comment by ianlancetaylor** [comment]
Experience has told us that we can't support all the existing customizations of the CSV format.  There are too many.  Supporting them all would produce a package that is difficult to use and test.

The code for encoding/csv.Writer is all of 182 lines, including comments.  If you need a non-standard format, I encourage you to copy the code and modify it for your purposes.
