### ISSUE TITLE
cmd/go: clarify suggested action when `install`ing a module while -mod=readonly is on

### ISSUE THREAD

**Issue by deltamualpha** [golang/go#44975]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yep.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/davidashby/Library/Caches/go-build"
GOENV="/Users/davidashby/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/davidashby/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/davidashby/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/davidashby/Code/ixauth/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zl/y389cwmn45sfrdcqt23b1ynh0000gn/T/go-build889417450=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
$ go install github.com/mitranim/gow
```

### What did you expect to see?

No output and a binary installed in `GOBIN`.

### What did you see instead?

```
no required module provides package github.com/mitranim/gow; to add it:
        go get github.com/mitranim/gow
```

My intention was to install a helper binary for some tests. Previously, I'd used `go get github.com/mitranim/gow` to install the binary into `GOBIN` (which I place in my PATH), but since my actual application doesn't rely on that module, I was excited to switch to `install` so I wouldn't have to run `go mod tidy` all the time to clean up after it. Instead, I got the somewhat cryptic error message above. This is related to -mod defaulting to readonly now, it seems.

Apparently, the proper invocation is to add a specific version to the install path: `go install github.com/mitranim/gow@latest` does what I expected. It'd be nice if the error-message hinted at that.

**Comment by jayconrod** [comment]
Thanks for opening this issue.

The `go` command should provide hints for both adding a dependency to the current module and for installing a command independent of the current module.

**Comment by deltamualpha** [comment]
The command does spit out a nice message when _not_ in a module: https://github.com/golang/go/blob/master/src/cmd/go/internal/work/build.go#L615, but `load.CheckPackageErrors(pkgs)` on line 618 exits on error and doesn't let us add any extra information afterward.

**Comment by deltamualpha** [comment]
Augmenting https://github.com/golang/go/blob/master/src/cmd/go/internal/modload/import.go#L73 looks like it has the least impact, but might appear more places than just `go install`. Maybe `"%s; to add it:\n\tgo get %s\nto install it as a binary:\n\tgo install %s@latest"`? Unclear to me if `e.Module.Version` would be expected to be set at this point in the execution (I think not, since `e.Module.Path == ""` is the trigger for that entire block.)

**Comment by iWdGo** [comment]
Issue seems to duplicate #42638 which was  solved by [CL 277355](https://go-review.googlesource.com/c/go/+/277355) merge to close 

```
>gotip version
go version devel go1.17-4c8f48ed4f Sat May 8 05:57:31 2021 +0000 windows/amd64

>gotip install github.com/mitranim/gow
go install: version is required when current directory is not in a module
        Try 'go install github.com/mitranim/gow@latest' to install the latest version
```

**Comment by deltamualpha** [comment]
Yep, that looks like it solves my concern!
