### ISSUE TITLE
A nil passed to an interface parameter violates function signature

### ISSUE THREAD

**Issue by mbrancato** [golang/go#44978]
### Does this issue reproduce with the latest release?

yes

### What did you do?

I'm rather new to Go, and am by no means any sort of expert in this area. While running some code for a while, I started to hit some odd panics. When I dug into it, I was getting an error like this:

```
panic: runtime error: invalid memory address or nil pointer dereference
```

My code was rather simple, it simply was doing some type checking with reflect to confirm if an interface was really a slice of concrete values. That part doesn't really matter, so I've made an example here: https://play.golang.org/p/jsJaTlm4hqt

The example function signature is: `func checkValue(value interface{})`

Stoping here, from a strongly typed perspective, shouldn't I **ALWAYS** be able to, at runtime, treat `value` as an interface in the function body?

Continuing on, I was not using a pointer, so I figured I needed to check if `value` was `nil`. This solved the issue but has left me wondering why I didn't realize this when writing it initially. I understand the underlying value could be `nil`, but shouldn't the type have conformed to the function signature at runtime?

If I had a function like this:
```go
func addOne(v int) int {
    return v+1
}
```
I would never think to check that `v` is an integer at runtime. In my example on Go Playground, it also doesn't work to try and assert the value type as an interface.

### What did you expect to see?

At runtime, a variable declared in a function signature should be its declared type and used as its declared type.

### What did you see instead?

Returning or passing `nil` to a function parameter will not generate an interface type at runtime.

**Comment by randall77** [comment]
A [type assertion](https://golang.org/ref/spec#Type_assertions) requires its argument to be non-nil to succeed.
Kind of strange that a `.(interface{}) ` of a `interface{}` can fail, but that's what the spec says.
[`reflect.TypeOf`](https://golang.org/pkg/reflect/#TypeOf) returns nil for the nil interface, so that's why you have a nil pointer exception.

I don't think there's any bug here. Please reopen if you disagree.
