### ISSUE TITLE
all: apply gofmt

### ISSUE THREAD

**Issue by Prajwal-Koirala** [golang/go#44980]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
The code itself isn't formatted

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\prajw\AppData\Local\go-build
set GOENV=C:\Users\prajw\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\prajw\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\prajw\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.2
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\prajw\AppData\Local\Temp\go-build365633068=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

Format all the code.

### What did you expect to see?
Formatted Code

### What did you see instead?
Not formatted code

Note: can someone make a PR just formatting all the code?

**Comment by ianlancetaylor** [comment]
What code are you talking about?

**Comment by Prajwal-Koirala** [comment]
The whole project in general.
I went though the code and see like multiple import statement instead of a block of imports. (alot of other examples like this but u get the idea)

Just do a `go fmt .` for the whole project and making a PR? is that fine?

**Comment by Prajwal-Koirala** [comment]
@ianlancetaylor 
What do u think of the PR?

**Comment by slrz** [comment]
This will result in lots of conflicts for work branched off the earlier state. It's also going to break `git blame` and similar stuff.

Requiring all new code submissions to be well-formatted is good but it's probably best to leave old code alone until it needs to be touched anyway.

**Comment by ianlancetaylor** [comment]
I replied on the change.  We definitely don't want to change any code under the test directory.
