### ISSUE TITLE
x/tools/gopls: Using memory for unknown reason

### ISSUE THREAD

**Issue by dragonly** [golang/go#44994]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
<pre>
$ gopls version
golang.org/x/tools/gopls v0.6.6
    golang.org/x/tools/gopls@v0.6.6 h1:GmCsAKZMEb1BD1BTWnQrMyx4FmNThlEsmuFiJbLBXio=
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN="/Users/dragonly/go/bin"
GOCACHE="/Users/dragonly/Library/Caches/go-build"
GOENV="/Users/dragonly/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/dragonly/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/dragonly/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pv/cqn4jtrj1kg6fwxwk31j9z1w0000gn/T/go-build348655080=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
profile gopls heap usage

### What did you expect to see?
the same usage as system monitor

### What did you see instead?
There's an 1G gap between the profile and the system monitor result.
![image](https://user-images.githubusercontent.com/8433465/111064038-e12e7a80-84ec-11eb-9c41-9688c574f383.png)

**Comment by D1CED** [comment]
What you are looking at are two very different kinds of metrics. gopls is showing you the sum of allocated memory of all live objects in your processes heap while your system monitor is likely showing RSS.
You can not expect any relation between these two numbers.

### Reasons why RSS can be larger than live object memory sum
- the page allocator holds reserves
- the regular allocator holds reserves (each size class and each thread)
- there are off (main-)heap resources 
- fragmentation
- there may be memory not reclaimed by the os (see madvfree)
- any tracing based garbage collected runtime will hold significant memory reserves (see GOGC)

### Reasons why live object memory sum can be larger than RSS
- there can be a large amount of static objects (they are not part of RSS)
- pages might be swapped
- pages might be deduplicated by the os (for e.g. linux uses copy-on-write when forking)

**Comment by mdlayher** [comment]
See above, I don't think there is anything actionable here. Closing.
