### ISSUE TITLE
crypto/elliptic: bake 88 kB p256Precomputed table into binary on iOS

### ISSUE THREAD

**Issue by bradfitz** [golang/go#44992]
The crypto/elliptic package, on amd64 and arm64, has an 88kB table that's lazily computed via `crypto/elliptic/p256_asm.go`:

```go
func (p *p256Point) p256BaseMult(scalar []uint64) {
        precomputeOnce.Do(initTable)
...

func initTable() {
        p256Precomputed = new([43][32 * 8]uint64)
```

That 43 * 32 * 8 * 8 bytes == 88 KB, which resides in the heap.

On iOS, in certain contexts (App Extensions: https://developer.apple.com/app-extensions/), the memory limits can be quite low, like 15 MB total non-pageable memory.

88 KB is enough to show up in profiles.

If the 88 KB were baked into the binary, however, it wouldn't count against the limit.

Can we just always bake it into the binary on iOS at least?

**Comment by FiloSottile** [comment]
From my side, there's no problem with compiling it in. In general, this is a binary size vs memory use concern. It would get linked into anything that uses crypto/tls or net/http.

**Comment by rsc** [comment]
If most uses of TLS are going to compute this table anyway, then precomputing is a net win. 

Do most TLS uses end up needing this table?

**Comment by rsc** [comment]
This proposal has been added to the [active column](https://golang.org/s/proposal-status#active) of the proposals project
and will now be reviewed at the weekly proposal review meetings.
— rsc for the proposal review group

**Comment by FiloSottile** [comment]
> Do most TLS uses end up needing this table?

Yes, a pretty good portion of TLS connections will use it.

Do we want to special-case iOS where this is a net win, or everywhere even if it will make binaries bigger? I would prefer not to have the complexity of supporting both modes, but it would not be particularly hard.

**Comment by rsc** [comment]
If most TLS connections need it anyway, then sure let's try doing the table on all platforms and see how it goes.

**Comment by rsc** [comment]
Based on the discussion above, this proposal seems like a **[likely accept](https://golang.org/s/proposal-status#likely-accept)**.
— rsc for the proposal review group

**Comment by rsc** [comment]
No change in consensus, so **[accepted](https://golang.org/s/proposal-status#accepted)**. 🎉
This issue now tracks the work of implementing the proposal.
— rsc for the proposal review group
