### ISSUE TITLE
Go Mods: local imports

### ISSUE THREAD

**Issue by vjerci** [golang/go#45001]
### What version of Go are you using (`go version`)?

<pre>
go 1.15.6
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
I have a local project `projectA` in goPath
`/Users/xxx/go/src/projectA`
I am starting a new local project `projectB` and i Am unable to include `projectA` using go modules 

### What did you expect to see?

I was hoping to be able to include it by just typing 
``` 
packageB

import packageA
```

since that didn't work because go modules requires `.` in first keyword of local path i was hoping we could use some special keyword `localhost.com/packageA` or `go get localhost/packageA` which would build a symlink to make it possible to include

### What did you see instead?
Some Errors

**Comment by mdlayher** [comment]
This looks like a usage question and not a problem with modules. See https://github.com/golang/go/wiki/Questions.
