### ISSUE TITLE
switch & fallthrough & break

### ISSUE THREAD

**Issue by haochen233** [golang/go#45013]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.15.7

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\peng\AppData\Local\go-build
set GOENV=C:\Users\peng\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\workspace
set GOPRIVATE=
set GOPROXY=https://goproxy.io,direct
set GOROOT=C:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\code\workspace\data_check\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\peng\AppData\Local\Temp\go-build402110134=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
just like c program language. I can decide break In switch expr.
However, the fallthrough statement provided by GO is executed without judging the next case, which strikes me as a bit anti-human

### What did you expect to see?
Instead of using the default break, the programmer can manually break.
OR
Fallthrough can make a judgment on the next case.

**Comment by cherrymui** [comment]
You can use the `fallthrough` statement for the fall-through behavior. See https://golang.org/ref/spec for the Go language spec.

If you want to ask question about Go, you are welcome to ask on a forum rather than on the issue tracker. See https://golang.org/wiki/Questions . Thanks.
