### ISSUE TITLE
cmd/go: 'go mod init' should reject module paths that are not valid import paths

### ISSUE THREAD

**Issue by nemith** [golang/go#45025]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Tested on Go 1.16.2 and on tip `using gotip`

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/bbennett/.cache/go-build"
GOENV="/home/bbennett/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/bbennett/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/bbennett/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/bbennett/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build45415822=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```
$ go mod init "bad module"
$ cat go.mod
module "bad module"

go 1.16
```

### What did you expect to see?

An error about the import path not being correct due to the space and not have the `go.mod` file created

### What did you see instead?

```
go: creating new go.mod: module bad mod
go: to add module requirements and sums:
	go mod tidy
```

Also once trying to use the module then I get an error about the module name.

```
[bbennett@bbennett-fedora-PC1RSH91 tmp]$ go run .
malformed import path "bad mod": invalid char ' '
```

**Comment by cherrymui** [comment]
cc @bcmills @jayconrod @matloob

**Comment by bcmills** [comment]
(See also #36774, #44052, #31549.)

**Comment by bcmills** [comment]
We can't reject module paths that fail `module.CheckPath`, but we certainly _should_ reject module paths that fail [`module.CheckImportPath`](https://pkg.go.dev/golang.org/x/mod/module#CheckImportPath).

I thought we had fixed this in [CL 211597](https://golang.org/cl/211597), but I guess we missed something there. 😞

CC @matloob @jayconrod

**Comment by nemith** [comment]
This may be as simple as adding ' '(space)  to the one of the reject lists  (it's really not a shell character or a fs character though).    I wonder what other character may need to be blocked.

**Comment by oiooj** [comment]
Yes, this issue fixed in CL 211597 .

```
  $WORK/gopath/src/mod
  > go mod init "bad module"
  [stderr]
  go mod init: too many arguments
  [exit status 1]
  FAIL: testdata/script/mod_invalid_importpath.txt:5: unexpected command failure
```

**Comment by bcmills** [comment]
@oiooj, it's nice that `go mod init` now correctly rejects this path, but IMO `too many arguments` is a pretty confusing error message. I'd like to leave this issue open to at least improve that. 🙂

**Comment by jayconrod** [comment]
`go mod init` currently does not reject spaces.

```
$ go mod init "bad module"
go: creating new go.mod: module bad module
$ cat go.mod
module "bad module"

go 1.16
```

(I think `testscript` interprets `"` literally; that would explain the `too many arguments` error, which I agree should be clarified).

Now that we have separate validation for import paths, perhaps we should call `module.CheckImportPath` on top of the existing restrictions? It shouldn't be possible to create a module with `go mod init` if we can't import its packages.

**Comment by iwdgo** [comment]
With the suggested CL, space in a module name is rejected as expected.

```
>goissue mod init "bad example"
go: malformed import path "bad example": invalid char ' '
```
