### ISSUE TITLE
x/pkgsite: Unable to rescan to detect new license

### ISSUE THREAD

**Issue by deefdragon** [golang/go#45027]
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/sohlich/elogrus
 
### What is your user agent?
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36
 
### Screenshot
 
 
![Capture](https://user-images.githubusercontent.com/3053654/111180894-724c3280-857b-11eb-9262-e8d9cee45dd1.PNG)

 
### What did you do?
Attempted to access the documentation for https://pkg.go.dev/github.com/sohlich/elogrus
 
### What did you expect to see?
Documentation related to the package
 
### What did you see instead?
 A License error, and a last scanned date of 2017. 
 
 The package now has a valid MIT license on the master branch, and on the v7 tag.

**Comment by jba** [comment]
The right path for your module, according to your go.mod file, begins with gopkg.in/sohlich/elogrus. https://pkg.go.dev/gopkg.in/sohlich/elogrus.v7 works fine.
The path starting with github.com is from before you had a go.mod file, and shouldn't be used.
If you'd like, we can remove it.

**Comment by deefdragon** [comment]
Not my package, so I cant make a decision on its removal. 

Would it be viable for packages that have a common source repository to be linked together somehow to prevent this in the future? Or some other form of detection of module path change? Its likely a rare edge case, but still infuriating if you are an outside user.

**Comment by jba** [comment]
We do detect and reject modules whose path does not match the path in the go.mod file. The problem is that the github package doesn't have a go.mod file to check with. pkg.go.dev only knows about module zip files (except, as a heuristic, we try to link source to the originating repo), so there's no way to tell that the github path is "bad" here.

Filed sohlich/elogrus#35.

**Comment by deefdragon** [comment]
Assuming nothing else needs to be taken care of then as it is now tracked in that ticket, closing this one.
