### ISSUE TITLE
timezone: update bash

### ISSUE THREAD

**Issue by Prajwal-Koirala** [golang/go#45047]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.9 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/prajwal/.cache/go-build"
GOENV="/home/prajwal/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/prajwal/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/prajwal/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.15"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.15/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build778870028=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Update the code for updating the timezone.

### What did you expect to see?
Using variables and not hard coding things.

### What did you see instead?
Everything hard coded.

### NOTE:
- One thing that i noticed was when doing `go generate time/tzdata` i get the error.
```
cannot find zoneinfo.zip file: open ../../../lib/time/zoneinfo.zip: no such file or directory
exit status 1
/usr/lib/go-1.15/src/time/tzdata/tzdata.go:5: running "go": exit status 1
```
It seems like it's hard coded where the timezone file is and need to change this too.

**Comment by ianlancetaylor** [comment]
It's OK to hard code things that don't change.

It would be fine to fix `go generate time/tzdata` to work even when invoked in a different directory.  That doesn't require any change to the shell script.

**Comment by Prajwal-Koirala** [comment]
> It's OK to hard code things that don't change.
> 
> It would be fine to fix `go generate time/tzdata` to work even when invoked in a different directory. That doesn't require any change to the shell script.

The problem with that shell script is, its very very very basic and should be used in local PC for demo testing and not on production, for example it will try and delete `work` folder without doing any checks or anything whats so ever, this just added checks to validate it and use system temp dir instead of their normal path.


Old Setup:
lets say a user invokes the shell script like this, `bash /home/USERNAME/Projects/go/lib/time/update.bash` than it will create all the folders and files in `/` from the place where it was executed, and not the right place and if the user has some important files or folder in that dir than it will delete those.

Example:

```
prajwal@Prajwal-Desktop:/mnt/c/Users/prajw/Projects$ mkdir -p work
prajwal@Prajwal-Desktop:/mnt/c/Users/prajw/Projects$ cd ../
prajwal@Prajwal-Desktop:/mnt/c/Users/prajw$ mkdir -p work
prajwal@Prajwal-Desktop:/mnt/c/Users/prajw$ bash Projects/test.sh
prajwal@Prajwal-Desktop:/mnt/c/Users/prajw$ ls
'3D Objects'         Cookies                 Favorites  'Local Settings'   NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf                                        ntuser.ini  'Saved Games'   Templates
 ansel              'Creative Cloud Files'   flutter     Music             NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms   Pictures     Searches       Videos
 AppData             Desktop                 go         'My Documents'     NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms   PrintHood    SendTo
'Application Data'   Documents               Intel       NetHood           ntuser.dat.LOG1                                                                                Projects     source
 Contacts            Downloads               Links       NTUSER.DAT        ntuser.dat.LOG2                                                                                Recent      'Start Menu'
prajwal@Prajwal-Desktop:/mnt/c/Users/prajw$ cd Projects/
prajwal@Prajwal-Desktop:/mnt/c/Users/prajw/Projects$ ls
test.sh  work
```

**Comment by ianlancetaylor** [comment]
The shell script is only expected to be used by Go maintainers who are updating the timezone information that is stored in the Go distribution.

Actually that script itself invokes `go generate time/tzdata`.

We can make this code a little more robust, but it should stay small and simple.  For example, we could add

    cd `go env GOROOT`/lib/time
