### ISSUE TITLE
cmd/compile: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by elagergren-spideroak** [golang/go#45044]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yep.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/$USER/gopath/bin"
GOCACHE="/Users/$USER/Library/Caches/go-build"
GOENV="/Users/$USER/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/$USER/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/$USer/gopath"
GOPRIVATE=""
GOPROXY="$PROXY"
GOROOT="/usr/local/go"
GOSUMDB="$SUMDB"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2b/74fz3jhd4wz4vnbf4z7ywzww0000gp/T/go-build2406540359=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://play.golang.org/p/vhFwohxt9c3

### What did you expect to see?

Anything other than an ICE.

### What did you see instead?

An ICE.

**Comment by randall77** [comment]
I believe this is fixed at tip.
```
% ../bin/go build ~/gowork/issue45044.go      
# command-line-arguments
../../../gowork/issue45044.go:8:6: invalid recursive type chain
	/Users/khr/gowork/issue45044.go:8:6: chain refers to
	/Users/khr/gowork/issue45044.go:8:6: chain
```

**Comment by elagergren-spideroak** [comment]
Yep. Thanks @randall77.

```
$ gotip run x.go
# command-line-arguments
./x.go:8:6: invalid recursive type chain
	/tmp/x.go:8:6: chain refers to
	/tmp/x.go:8:6: chain
```
