### ISSUE TITLE
runtime: map insertion should overwrite existing keys

### ISSUE THREAD

**Issue by randall77** [golang/go#45045]
Looks like this happens correctly in `mapassign`, but not in the `mapassign_faststr` variant.

@mdempsky 

First noticed as part of #45021

**Comment by networkimprov** [comment]
Backport candidate?

**Comment by cuonglm** [comment]
> Backport candidate?

I don't think this can be qualified for backport.

**Comment by randall77** [comment]
I agree. This is not a serious enough problem to warrant a backport.

https://github.com/golang/go/wiki/MinorReleases

> A “serious” problem is one that prevents a program from working at all.
