### ISSUE TITLE
x/website: wrong package synopses on stdlib packages containing programs

### ISSUE THREAD

**Issue by zephyrtronium** [golang/go#45042]
https://golang.org/pkg/ currently shows the wrong package synopses on stdlib packages containing ignore-constrained programs intended for `go run`. E.g., the synopsis on package runtime is `mkduff generates duff_*.s.`, on package os/exec is `This is a test program that verifies that it can read from descriptor 3 and that no other descriptors are open.`, &c.

**Comment by zephyrtronium** [comment]
Probably related, the same page now shows pages for `src/cmd`, which I believe it did not do previously.

**Comment by prattmic** [comment]
cc @rsc 

Perhaps golang.org/cl/296378 or one of the other CLs in the stack?

The March 10 snapshot of this page at https://web.archive.org/web/*/https://golang.org/pkg/ has the correct descriptions, so it seems recent.

**Comment by kortschak** [comment]
In all the cases that this is happening, the package documentation synopsis is obtained from a file that has a `// +build` tag (from memory all are `ignore`, though that's not likely relevant).

**Comment by zephyrtronium** [comment]
https://golang.org/pkg/ is still showing packages under src/cmd. This issue is not entirely resolved.
