### ISSUE TITLE
mail.ParseAddress("145175208@qq") return a valid result

### ISSUE THREAD

**Issue by stamaimer** [golang/go#45056]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/root/go/bin"
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOOS="linux"
GOPATH="/root/go"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build571966441=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
package main

import (
	"fmt"
	"log"
	"net/mail"
)

func main() {
	e, err := mail.ParseAddress("145175208@qq")
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(e.Name, e.Address)

}
```

### What did you expect to see?

log error

### What did you see instead?

 145175208@qq

**Comment by andrius4669** [comment]
`145175208@qq` is valid syntax according to [RFC 5322 section 3.4.1](https://tools.ietf.org/html/rfc5322#section-3.4.1)

**Comment by mdlayher** [comment]
Email address parsing is non-trivial and if it's compliant with the RFC, there is nothing to be done here. Closing.
