### ISSUE TITLE
go1.8.6 windows use which version sys

### ISSUE THREAD

**Issue by linger000** [golang/go#45050]
go verison 1.8.6 

when i build under windows os type with go version 1.8.6

get the error :

\golang.org\x\sys\windows\dll_windows.go:21: undefined: Errno

i guess the issue is the sys git version,but i dont know which branch to use.because it has not version ,and i lost my windows machine too.

**Comment by davecheney** [comment]
Are you able to upgrade your go version, 1.8 is many years out of support?

**Comment by linger000** [comment]
Because some reason,it is not a good time to update go version.

**Comment by AlexRouSg** [comment]
1.8 was released in 2017 so checkout a commit from 2017

**Comment by ianlancetaylor** [comment]
We only support two versions of Go, which currently means 1.15 and 1.16.  Sorry.

**Comment by linger000** [comment]
Thanks , I will try this solution later!
