### ISSUE TITLE
gollvm work fail with asm

### ISSUE THREAD

**Issue by JX-Zhang98** [golang/go#45057]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 gollvm LLVM 13.0.0git linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN="/home/jxzhang/workspace/gowork/bin"
GOCACHE="/home/jxzhang/.cache/go-build"
GOENV="/home/jxzhang/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jxzhang/workspace/gowork/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jxzhang/workspace/gowork"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/home/jxzhang/.local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/jxzhang/.local/gollvm/tools"
GOVCS=""
GOVERSION="go1.16 gollvm LLVM 13.0.0git"
GCCGO="/home/jxzhang/.local/gollvm/bin/llvm-goc"
AR="ar"
CC="/home/jxzhang/workspace/llvm_area/llvm-project/build/bin/clang"
CXX="/home/jxzhang/workspace/llvm_area/llvm-project/build/bin/clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build979330769=/tmp/go-build -gno-record-gcc-switches -funwind-tables"

</pre></details>

### What did you do?

I attempted  to compile a go demo with impored asm function.
It works well with original go compiler，but it failed with gollvm.

A link on [play.golang.org: https://play.golang.org/p/dEW5zPmfMqV](https://play.golang.org/p/dEW5zPmfMqV)

### What did you expect to see?
Build the binary successfully
(It can't print anything because I use a wrong system call number,,,maybe,,,It should can be compiled successfully anyway...)

### What did you see instead?
Gollvm compile with failure
```
# goasm/hello
hello/hello.s:3:18: error: expected register here
DATA  msg<>+0x00(SB)/8, $"Hello, W"
                 ^
hello/hello.s:4:18: error: expected register here
DATA  msg<>+0x08(SB)/8, $"orld!\n"
                 ^
hello/hello.s:5:1: error: invalid instruction mnemonic 'globl'
GLOBL msg<>(SB),NOPTR,$16
^~~~~
hello/hello.s:7:6: error: invalid character in input
TEXT ·PrintMe(SB), NOSPLIT, $0
hello/hello.s:10:19: error: invalid operand for instruction
        LEAQ    msg<>(SB), SI  
```

Thanks for your attention

**Comment by thanm** [comment]
This is expected behavior for gollvm and for gccgo -- they use the assembly syntax used by the system C compiler, not the syntax used by the main Go compiler's "cmd/asm". Also worth noting that under the hood, functions compiled by gollvm/gccogo are using the C/C++ calling convention + register ABI (meaning that even if the Go syntax were accepted, the assembly functions would not work properly).

The expectation is that folks will use build tags to avoid building the cmd/asm-specific files when building with gccgo or gollvm.

**Comment by thanm** [comment]
Closing as expected behavior, please reopen if needed.
