### ISSUE TITLE
x/pkgsite: pkg/proc/native package is missing from github.com/go-delve/delve/

### ISSUE THREAD

**Issue by hyangah** [golang/go#45067]
From https://pkg.go.dev/github.com/go-delve/delve@v1.6.1-0.20210315163646-333e84a0cb20/pkg/proc#section-directories
I noticed the directory is missing the native directory.
![Screen Shot 2021-03-15 at 8 35 19 PM](https://user-images.githubusercontent.com/4999471/111354873-2a054100-865d-11eb-9e4b-c4d05475aa8d.png)

https://github.com/go-delve/delve/tree/master/pkg/proc/native is the directory.
Suspected build constraints, but there are files without any build constraints.

**Comment by jba** [comment]
Some build contexts (js/wasm, for example) are deliberately broken by having files with two different package names. We currently treat this error as so serious that we shouldn't process the package at all, but it isn't. We should just ignore the bad build contexts and process the others.
