### ISSUE TITLE
x/build: remove Scaleway builders

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#45066]
With the introduction of AWS ARM builders (#36841), we can now remove Scaleway as a hosting provider. 
Removing Scaleway will allow us to stop running the [scaleway](https://go.googlesource.com/build/+/0364c525d92e341a99f77e10c942c94dfcf76435/cmd/scaleway/) application used to manage instances on the provider. 

We will continue to use Scaleway as a provider until:
* Go 1.15 is no longer supported. We currently package Go 1.15 with a Scaleway builder.
* We no longer use [Scaleway for trybots and slowbots](https://go.googlesource.com/build/+/0364c525d92e341a99f77e10c942c94dfcf76435/dashboard/builders.go#39).
    * #45064
    * #45065

@golang/release @cherrymui

**Comment by dmitshur** [comment]
This is currently in 1.17 milestone, but Go 1.15 will be supported throughout this milestone. Moving to 1.18 and adding early-in-cycle instead.

**Comment by cagedmantis** [comment]
Scaleway has advised us that we should migrate away from the c1 instances before July 1, 2021. They are in the process of being deprecated.

**Comment by cagedmantis** [comment]
Before the removal of Scaleway as a provider, the `linux-arm-scaleway` builder was used for the `linux-armv6l` release. It was configured to SkipTests during the release because the builder did not have enough resources to run the tests successfully.

```
	{
		GoQuery: "< go1.16beta1",
		OS:      "linux",
		Arch:    "arm",
		Builder: "linux-arm-scaleway",
		Goarm:   6, // For compatibility with all Raspberry Pi models.
		// The tests take too long for the release packaging.
		// Much of the time the whole buildlet times out.
		SkipTests: true,
	},
```

The set of changes introduced by this issue move the builder used to release `linux-armv6l` to the `linux-arm-aws` builder. With the use of this new builder we should enable test to run as we have previously done with for the Go 1.16 release. When we execute a simulated release for `linux-armv6l` on the `release-branch.go1.15` ( at time of testing ab7f8297f9734b24a43a942930258cda411f16a3), we run into a set of errors:

```
ok  	cmd/internal/test2json	0.202s
--- FAIL: TestPIESize (0.00s)
    --- FAIL: TestPIESize/TestPieSize-external (18.00s)
        elf_test.go:287: [/root/go/bin/go build -o /tmp/go-link-TestPieSize-external313361227/exeexternal -buildmode=exe -ldflags=-linkmode=external pie.go]
        elf_test.go:287: [/root/go/bin/go build -o /tmp/go-link-TestPieSize-external313361227/pieexternal -buildmode=pie -ldflags=-linkmode=external pie.go]
        elf_test.go:409: real size difference 0xfffffffffffffd4e, expected 0xfffffffffffffb0c
        elf_test.go:412: PIE unexpectedly large: got difference of 18446744073709550926 (2852468 - 2851560), expected difference 18446744073709550348
FAIL
FAIL	cmd/link	41.400s
ok  	cmd/link/internal/benchmark	0.034s
--- FAIL: TestRuntimeTypeAttrExternal (1.01s)
    dwarf_test.go:1022: DWARF type offset was 0x3b38+0x70a30, but test program said 0xc2d568
FAIL
FAIL	cmd/link/internal/ld	5.976s
ok  	cmd/link/internal/loader	0.039s
ok  	cmd/link/internal/sym	0.023s
--- FAIL: TestExternalLinkerCgoExec (2.02s)
    nm_test.go:189: want 0x958ac8 address for main.main symbol, but have 0xb4ac8
    nm_test.go:189: want 0xa13900 address for main.testdata symbol, but have 0x16f900
    nm_test.go:189: want 0x958aec address for main.testfunc symbol, but have 0xb4aec
FAIL
FAIL	cmd/nm	4.412s
ok  	cmd/objdump	3.419s
```
These same test failures were encountered when we began using the `linux-arm-aws` builder for the Go 1.16 and beyond #43202.  I'm going to create a backport CL for the fix for that issue in hopes that it will resolve the problem.
