### ISSUE TITLE
x/build: add linux-arm-aws to the set of trybots

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#45064]
As per our goals of including a trybot for any platform that can cause a release blocking issue (#29239), we will add linux-arm-aws to the set of trybots. It should be able to complete the trybot run limit of 10 minutes. These new trybots will help solve various open issues linked to host resources (#35628, #40872).  

This change will require renaming the linux-arm builders to linux-arm-scaleway because there is a need to map the AWS instances to some [slowbot aliases](https://go.googlesource.com/build/+/aeb22a9cfe01a71f7dc06ae9beeeb5ba6c605fb0/dashboard/builders.go#39).

@golang/release @cherrymui

**Comment by cherrymui** [comment]
SGTM, thanks.

As of now the old linux-arm builders don't seem to be provide much. Maybe we can consider just removing them.

**Comment by cagedmantis** [comment]
I would like to keep the Scaleway builders around until we no longer support Go 1.15. We used Scaleway builders to package Go 1.15 and I would like to continue using the same configuration to package the rest of Go 1.15. I can discuss it with the team today to ensure that this is a good idea.

**Comment by cherrymui** [comment]
Okay, thanks for the information.
