### ISSUE TITLE
x/tools/gopls: fix hover with dot imports

### ISSUE THREAD

**Issue by FlyingOnion** [golang/go#45063]
**Is your feature request related to a problem? Please describe.**
```
import (
  . "somepkg"
)

var (
  // foo somepkg.Foo
  foo Foo
)
```
When the mouse move to `Foo`, the prompt show `..Foo`
Especially, When `Foo` is used in an uncertain list arg (`fooList ...Foo`), the prompt will show `.....Foo`

**Describe the solution you'd like**
When import alias is `.`, show original package name `somepkg.Foo`, or just `Foo` directly.

**Comment by muirdm** [comment]
Similar to #44589. We should try to fix this bug systemically.
