### ISSUE TITLE
x/build: add linux-arm64-aws to the set of trybots

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#45065]
As per our goals of including a trybot for any platform that can cause a release blocking issue (#29239), we will add linux-arm64-aws to the set of trybots. It should be able to complete runs under the trybot limit of 10 minutes. This new trybot will help alleviate an issue linked to host resources (#36170). 

@golang/release @cherrymui

**Comment by bcmills** [comment]
This new TryBot is fairly flaky due to #41863.

Is someone planning to address that issue in the near term, or should the affected test(s) be skipped on the builder?

**Comment by dmitshur** [comment]
I think it makes sense to skip the affected tests and keep that issue open.

**Comment by cagedmantis** [comment]
I agree. It would be great to get to the bottom of this though.
