### ISSUE TITLE
x/build: iOS builders are down

### ISSUE THREAD

**Issue by mknyszek** [golang/go#45069]
The `ios-arm64-corellium` builders are currently down. https://farmer.golang.org/ indicates that they're currently missing and I've had a SlowBots job waiting on them for ~24h. I think it's the only job still waiting now. I confirmed that I also can't get them via gomote after about 30 minutes of waiting. https://build.golang.org/ also hasn't had a trybot job run on these builders in a while AFAICT.

**Comment by cherrymui** [comment]
The Android corellium builders seem missing as well.

**Comment by dmitshur** [comment]
CC @eliasnaur. Are you able to take a look?

**Comment by dmitshur** [comment]
It looks like they're back by now:

-	host-ios-arm64-corellium-ios: 0/3 (0 missing)
-	host-android-arm64-corellium-android: 0/3 (0 missing)
