### ISSUE TITLE
x/tools/gopls: gopls doesn't report errors when a return statement contains undeclared variable

### ISSUE THREAD

**Issue by ShoshinNikita** [golang/go#45075]
`gopls` version: v0.6.7

The bug was introduced in golang/tools@144d5ced6b0172174697ace34f69e2465fe58ac0. The minimal reproducible example:

```go
package main

func foo() int {
	return x, nil // No errors, expected 'wrong number of return values (want 1, got 2)' and 'undeclared name: x'
}

func bar() {
	return 5 // No errors, expected 'no result values expected'
}

func main() {
}
```

If we add `var x string` before the `return` statement, all errors will appear.

**Comment by findleyr** [comment]
I can reproduce, and will take a look.
