### ISSUE TITLE
x/tools/go/analysis/passes/inspect: typo in comment in inspect.go

### ISSUE THREAD

**Issue by Aseiide** [golang/go#45079]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/aseiide/Library/Caches/go-build"
GOENV="/Users/aseiide/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/aseiide/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/aseiide/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tj/6bk6q_71181_9x4vwmvbv4j40000gn/T/go-build4051281720=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

When I read this documentation, I found the broken link.

https://github.com/golang/tools/blob/master/go/analysis/passes/inspect/inspect.go#L6
`// (golang.org/x/tools/go/ast/inspect.Inspect) for the syntax trees of a`

When I try to jump to this link, I get Not found. like this.
![スクリーンショット 2021-03-17 19 09 22](https://user-images.githubusercontent.com/45246171/111457207-438cb280-875b-11eb-89b1-fc967b116c07.png)

### What did you expect to see?
I suggest  fix it to the correct url.

### What did you see instead?
I think this link is correct.

`//(golang.org/x/tools/go/analysis/passes/inspect) for the syntax trees of a `

**Comment by andreybokhanko** [comment]
This is a type name, not a URL. But indeed, it's incorrect -- should end with "inspector.Inspector".

Let me submit a patch in a few mins.

@ianlancetaylor please assign on me.

Yours,
Andrey
\===
Advanced Software Technology Lab
Huawei

**Comment by andreybokhanko** [comment]
Code review request submitted: https://go-review.googlesource.com/c/go/+/302570
