### ISSUE TITLE
bufio.ReadByte an error may occur 

### ISSUE THREAD

**Issue by l7i** [golang/go#45072]
### What version of Go are you using (`go version`)?

<pre>
go version go1.14 windows/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

func (b *Reader) ReadByte() (byte, error) {
	b.lastRuneSize = -1
	for b.r == b.w {
		if b.err != nil {
			return 0, b.readErr()
		}
		b.fill() // buffer is empty
	}
	c := b.buf[b.r]
	b.r++
	b.lastByte = int(c)
	return c, nil
}

at last, if buf is empty，b.r++，will not return err， and b.r is larger than r.w now

**Comment by ianlancetaylor** [comment]
if we get to the `b.r++`, we know for sure that `b.r != b.w`.  So I think that what you describe can't happen.

If you still think this is a problem, please write a program that demonstrates the problem.  You should be able to use a custom `io.Reader` that returns the values that cause the error.

**Comment by l7i** [comment]
i see, thanks
