### ISSUE TITLE
godoc does not work for local modules

### ISSUE THREAD

**Issue by soypat** [golang/go#45083]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/pato/.local/bin"
GOCACHE="/home/pato/.cache/go-build"
GOENV="/home/pato/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/pato/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pato/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3305217910=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### Problem
Running `godoc` on my machine does not show local modules. This seems to be a problem for other people too, see reddit thread https://www.reddit.com/r/golang/comments/m6l46z/what_are_the_problems_youve_faced_with_go_modules/

### Expected
Being able to run `godoc` in a directory that is not a GOPATH, GOMODCACHE or GOROOT

**Comment by seankhliao** [comment]
which version of `godoc` is this, and have you tried updating it?

**Comment by soypat** [comment]
Updating it did the trick. Sorry for the inconvenience.
