### ISSUE TITLE
Unable to access a go library with go binary

### ISSUE THREAD

**Issue by ManojKumarChauhan** [golang/go#45080]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.15
</pre>

### Does this issue reproduce with the latest release?
yes in all versions

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build531678036=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I created a go library 'go install -buildmode=shared testpackagename'
It will create libtestpackagename.so
Created a go binary
go build test.go
it will create test

Now I want to use libtestpackagename.so with test. I did not find anything which suggests how to use a so in go binary. So tried LD_PRELOAD.
export LD_PRELOAD=libtestpackagename.so;./test
but this will give the error 'main.main'

The solution is to create test like
go build -linkshared test.go

I do not want to use the linkshared option. 
Is there any option to use a go library in go binary?

### What did you expect to see?
Should be able to use go library in go binary.

### What did you see instead?
can't use go library in go binary. error main.main comes

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
