### ISSUE TITLE
x/tools/gopls: cannot install gopls v0.6.8

### ISSUE THREAD

**Issue by artyom** [golang/go#45099]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

N/a

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/artyom/Library/Caches/go-build"
GOENV="/Users/artyom/Library/Application Support/go/env"
GOEXE=""
GOFLAGS="-ldflags=-w -trimpath"
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/artyom/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/artyom/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/artyom/Library/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/artyom/Library/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lb/3rk8rqs53czgb4v35w_342xc0000gn/T/go-build459584806=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Tried to install [gopls/v0.6.8 release](https://github.com/golang/tools/releases/tag/gopls/v0.6.8):

### What did you expect to see?

<pre>
~ ¶ go install golang.org/x/tools/gopls@v0.6.8 ; echo $?
0
</pre>

### What did you see instead?

<pre>
~ ¶ go install golang.org/x/tools/gopls@v0.6.8 ; echo $?
go install golang.org/x/tools/gopls@v0.6.8: golang.org/x/tools/gopls@v0.6.8
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
1
</pre>

**Comment by komem3** [comment]
I think this is happening for the same reason as https://github.com/golang/go/issues/42627. It looks like need to remove the `replace` in go.mod.

**Comment by stamblerre** [comment]
Yes, this was a mistake in our release process--the replace directive should have been removed. We will be looking into improving our release process soon, so hopefully this will not happen again.

**Comment by stamblerre** [comment]
For now, please install `gopls` by using `go get golang.org/x/tools/gopls@v0.6.8`.
