### ISSUE TITLE
x/pkgsite: incorrect major version in banner for gopkg.in packages

### ISSUE THREAD

**Issue by julieqiu** [golang/go#45098]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/gopkg.in/yaml.v2 and https://pkg.go.dev/gopkg.in/yaml.v3

 
### Screenshot
 

![image](https://user-images.githubusercontent.com/5943521/111579650-c712c780-878c-11eb-9c85-41891cda88dd.png)

 

 
### What did you expect to see?
 
No banner, because the highest tagged major version is v2.

https://pkg.go.dev/gopkg.in/yaml.v3 should have a banner saying `The highest tagged major version is v2.` (without the extra dot in front of the major version).
 
### What did you see instead?

A banner showing `The highest tagged major version is .v3.`, with an extra dot in front of "v3":

**Comment by jba** [comment]
Fix is live.
