### ISSUE TITLE
x/pkgsite:  recognize and ignore the PSF license stack instead of failing entirely as UNKNOWN.

### ISSUE THREAD

**Issue by lostluck** [golang/go#45095]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/apache/beam@v2.13.0+incompatible/sdks/go/pkg/beam through
https://pkg.go.dev/github.com/apache/beam@v2.21.0+incompatible/sdks/go/pkg/beam 

 
### What is your user agent?
Mozilla/5.0 (X11; CrOS x86_64 13597.105.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.208 Safari/537.36
  
### Screenshot
N/A
 
### What did you do?
Include the Python Software Foundation ["license stack"](https://docs.python.org/3/license.html) in the Apache Beam LICENSE file.

### What did you expect to see?
Licences: Apache-2.0, BSD-3-Clause, MIT, PSF

### What did you see instead?
Licenses: UNKNOWN

https://pkg.go.dev/github.com/apache/beam@v2.13.0+incompatible/sdks/go/pkg/beam [during]
https://pkg.go.dev/github.com/apache/beam@v2.21.0+incompatible/sdks/go/pkg/beam [during]

Prior to including the PSF License, the file was parsed properly, and listed all the licenses, and after the license file was truncated in error, the Apache 2.0 license was correctly listed.

https://pkg.go.dev/github.com/apache/beam/sdks/go/pkg/beam?tab=versions [before]
https://pkg.go.dev/github.com/apache/beam@v2.22.0-RC1+incompatible/sdks/go/pkg/beam  [after]

While probably not common, large enough projects in multiple languages can have Go releases (like Apache Beam) and also include Python which is very much under it's own license, that doesn't prohibit the redistribution necessary for pkg.go.dev. I propose the PSF license is added to the set of "known" licenses, if only to avoid the bad state.

Even if the PSF isn't determined as recognized, failing into UNKNOWN when other licenses parse correctly seems like a bad behavior.

**Comment by jba** [comment]
I'm working on getting legal approval for the PSF license.

Meanwhile, your text does not match the [official OSI license text](https://opensource.org/licenses/Python-2.0) or the [licensecheck regular expression that matches it](https://github.com/google/licensecheck/blob/main/licenses/PSF-2.0.lre). For example, you have extra years in the copyright example in section 2 (note that it's only an example, not an actual copyright notice, so no need to add years). And there are differences in the CNI section, for instance you omit `BY CLICKING ON "ACCEPT" ...`. That's as far as I looked; there may be other discrepancies.

**Comment by lostluck** [comment]
That's very good to know, thank you! We're conferring with Apache Legal about what we actually need to include as well.

**Comment by lostluck** [comment]
Cross posting here as it's an earlier issue related to https://github.com/golang/go/issues/46291. 
That issue mentions that technically what beam has isn't the python 2 license, and whatever it is, cannot be accepted as a result. The overall solution is to move the python license to a separate LICENSE.python file (which will be ignored by pkg.go.dev) or to move it to a LICENSE file that's not at the shared root of the beam repo.
Closing this issue as the actions are on the Beam side to fix the beam godoc.
