### ISSUE TITLE
cmd/go: vendored dependencies default to go1.11 at head

### ISSUE THREAD

**Issue by kevinburkemeter** [golang/go#45109]
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kevin/Library/Caches/go-build"
GOENV="/Users/kevin/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/kevin/pkg/mod"
GONOPROXY="github.com/meterup"
GONOSUMDB="github.com/meterup"
GOOS="darwin"
GOPATH="/Users/kevin"
GOPRIVATE="github.com/meterup"
GOPROXY="direct"
GOROOT="/Users/kevin/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/kevin/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="devel +e4253cd023 Thu Mar 18 19:15:12 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s1/909yt58s4wj8h_7v7frr8rkm0000gn/T/go-build1139536333=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version devel +e4253cd023 Thu Mar 18 19:15:12 2021 +0000 darwin/amd64
GOROOT/bin/go tool compile -V: compile version devel +e4253cd023 Thu Mar 18 19:15:12 2021 +0000
uname -v: Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H524
lldb --version: lldb-1200.0.44.2
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
gdb --version: GNU gdb (GDB) 10.1
</pre></details>

### What did you expect to see?

I expect the vet check to complete since the Go version in go.mod is Go 1.16.

### What did you see instead?

```
$ make vet
GO111MODULE=on go vet ./...
# github.com/mholt/archiver/v3/zip
vendor/github.com/mholt/archiver/v3/zip/zip.go:153:32: 0o/0O-style octal literals requires go1.13 or later (-lang was set to go1.11; check go.mod)
vendor/github.com/mholt/archiver/v3/zip/zip.go:190:36: 0o/0O-style octal literals requires go1.13 or later (-lang was set to go1.11; check go.mod)
```

I have reproduced the issue in this sample repository: https://github.com/kevinburkemeter/repro-go-mod-vet

You should be able to download that and then run "make vet" to reproduce the issue.

**Comment by seankhliao** [comment]
cc @bcmills @jayconrod

**Comment by bcmills** [comment]
Ooh, neato! This is a bad interaction between [CL 302051](https://golang.org/cl/302051) and #36876, I think.
