### ISSUE TITLE
i want to test go, but i can't get the golang.org, even use ladder....

### ISSUE THREAD

**Issue by wish-wish** [golang/go#45116]
i want to use go, but i can't get the golang.org to download the binary,  even use ladder....
can anyone upload a go Binary Distributions to the release section?

**Comment by ianlancetaylor** [comment]
I'm sorry, I don't understand that you mean by "ladder".  There are Go binary distributions available at https://golang.org/dl/.

In general we don't use the issue tracker for questions.  You will get better answers on a forum.  See https://golang.org/wiki/Questions.  Thanks.

**Comment by wish-wish** [comment]
you network is clean, but my net work is dirty, i mean's the site golang.org is can't use at all.

**Comment by Tnze** [comment]
"ladder" means "proxy" I guess.

The domain golang.org is unreachable at China. Instead, use golang.google.cn
