### ISSUE TITLE
cmd/go: repeated, unhelpful errors when module cache can't be created

### ISSUE THREAD

**Issue by jayconrod** [golang/go#45113]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.16.2
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jayconrod/Library/Caches/go-build"
GOENV="/Users/jayconrod/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/does/not/exist/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/does/not/exist"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go/installed"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/installed/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rq/x0692kqj6ml8cvrhcqh5bswc008xj1/T/go-build3704992266=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Set environment variables such that the module cache directory can't be created as a directory. In this example below, I've explicitly set `GOMODCACHE` to a path I don't have access to.

```
export GOMODCACHE=/does/not/exist
go install golang.org/x/tools/gopls@latest
```

This came up in [this golang-nuts thread](https://groups.google.com/g/golang-nuts/c/RZ1qGp8REYg/m/0TUzeqjwCQAJ). In that example, neither `GOPATH` nor `GOMODCACHE` was set, so `GOMODCACHE` defaulted to `$HOME/go/pkg/mod`, but `$HOME/go` is not a directory.

### What did you expect to see?

An error message that explains what the problem is and how to fix it, printed once.

### What did you see instead?

An unhelpful message, printed multiple times.

```
$ go install golang.org/x/tools/gopls@latest
go: writing stat cache: mkdir /does: read-only file system
go: writing stat cache: mkdir /does: read-only file system
go: writing go.mod cache: mkdir /does: read-only file system
go: downloading golang.org/x/tools/gopls v0.6.8
go: writing go.mod cache: mkdir /does: read-only file system
go: downloading golang.org/x/tools v0.1.0
go install golang.org/x/tools/gopls@latest: mkdir /does: read-only file system
```

**Comment by atilkan** [comment]
Bad bot.

**Comment by wenjoy** [comment]
This issue should not be closed. I also encountered this problem and have no idea of solving it.

**Comment by mashaole** [comment]
i also have the same problem i cant install go commands on vs code such as gopls

**Comment by mashaole** [comment]
8 packages failed to install on vscode so i found a solution which is add these lines to your bash_profile, .bash_profile, .zshrc ,.zprofile: 
```
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
```

after that  only 2 packages failed after this so i just typed in `go install [package url]`

and it solved the problem
