### ISSUE TITLE
spec: shift string(1 << s) should be invalid

### ISSUE THREAD

**Issue by griesemer** [golang/go#45114]
```Go
package p
var s uint
var _ = string(1 << s)
```
is not accepted by the compiler:
```
bug.go:3:15: invalid operation: 1 << s (shift of type string)
```
Per the spec (https://golang.org/ref/spec#Constant_expressions):
"If the left operand of a non-constant shift expression is an untyped constant, it is first implicitly converted to the type it would assume if the shift expression were replaced by its left operand alone."

In this case, the left operand would be converted to `int` (not string). This is different from cases such as, say `float64(1 << s)` where `1` is implicitly converted to `1.0` because it can be done without loss of precision. It seems a bit far-fetched to claim that a `1` can be converted to a string without loss of precision. (That said, the spec is notoriously difficult to decipher with respect to shifts and implicit conversions.)

As an aside, there's still #3939 which is proposing to prohibit `string(int_value)`, and `go vet` is checking for this. So we're not permitting a new category of programs by making `string(1 << s)` valid.

Both `go/types` and `types2` accept this code.

The test `$GOROOT/test/fixedbugs/bug193.go` assumes that this code should fail.

**Comment by griesemer** [comment]
cc: @findleyr

**Comment by ianlancetaylor** [comment]
My vote is to change the spec, since cmd/compile, gccgo, and GoLLVM all reject this.  I'm assuming that nobody is clamoring for this to work.

**Comment by griesemer** [comment]
Fair enough. If anything, we need to clarify the spec in that regard.

**Comment by griesemer** [comment]
See #45117 for the implementation fix.
