### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by illfeel** [golang/go#45128]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?
MacBook Pro M1 Big Sur
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/youcan/Library/Go/bin"
GOCACHE="/Users/youcan/Library/Caches/go-build"
GOENV="/Users/youcan/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/youcan/Library/Go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/youcan/Library/Go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/youcan/Workspace/Go/Fiber/ezrest/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bq/58ry0q1x7hjf931wp4gjkfd40000gn/T/go-build462391625=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Install analysis tools on VSCode

**Comment by cherrymui** [comment]
Please complete the template, mention what fails or goes unexpected. Thanks.
