### ISSUE TITLE
x/tools/gopls: unable to upgrade gopls

### ISSUE THREAD

**Issue by iamshreeram** [golang/go#45133]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes. I'm seeing this issue after upgrading the golang version. 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> </summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sram/Library/Caches/go-build"
GOENV="/Users/sram/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/sram/ram/project/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/sram/ram/project/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sn/pw7xq23n2vj_wnq16lkgdrxh0000gn/T/go-build150007759=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
`go get golang.org/x/tools/gopls@latest`

### What did you expect to see?
Successful update of gopls version to 0.6.8

### What did you see instead?
Below error -
```
go: golang.org/x/tools/gopls latest => v0.6.8
# os/user
/usr/local/go/src/os/user/cgo_lookup_unix.go:20:10: fatal error: 'unistd.h' file not found
#include <unistd.h>
         ^~~~~~~~~~
1 error generated.
```

**Comment by cherrymui** [comment]
How did you install the Go toolchain? Does your system have a C toolchain (Xcode) installed?

**Comment by iamshreeram** [comment]
@cherrymui , I have installed go using brew. Yes, I do have xcode installed.

**Comment by iamshreeram** [comment]
Hi, I was able to fix this issue by updating clang version from **4.0.1** to **12.0.0**. 

Details:
1. I had older version (4.0.1) of clang running on my system that came with anaconda.
2. After removing the anaconda's clang, the system was able to point to the clang (version 12.0.0) of xcode  

`go get golang.org/x/tools/gopls@latest` worked well after above steps.
