### ISSUE TITLE
go/parser: missing object for composite lit types identifiers beginning statements

### ISSUE THREAD

**Issue by findleyr** [golang/go#45136]
In the following snippet, the `obj` identifiers in statements beginning with the composite literal `obj{}` are not resolved to the `obj` declaration.

```
type obj struct {}

func _() {
  obj{}
  obj{}.run()
}
```

The reason for this is that, while in the middle of parsing, LHS logic is pretty tricky to get right. Specifically, it's non-trivial to differentiate this case of a composite literal from, for example, the `ok {` in `if _, ok := m[k]; ok {...`.

See also #45104: this is easy to fix when post-processing the AST, but it's nearly impossible to match the broken behavior (because it relates to source layout rather than syntax).

Filing as a separate issue as I'm going to fix it prior to #45104, so that I can match behavior exactly with the new resolution logic.

CC @griesemer

**Comment by griesemer** [comment]
It might be easier to reproduce this bug in the new code than trying to fix the old code. Than you can still do exact behavior matching, and afterwards "fix the bug".

**Comment by findleyr** [comment]
> It might be easier to reproduce this bug in the new code than trying to fix the old code.

I have a fix for the old code. Reproducing in the new code would actually be quite tricky, because once parsed into a tree it's difficult to know if the CompositeLit you're looking at is at the start of an ExprStmt (this is what I meant above by "it relates to source layout rather than syntax").
