### ISSUE TITLE
x/pkgsite: remove github.com/PappasBrent/graph-spec

### ISSUE THREAD

**Issue by PappasBrent** [golang/go#45145]
Hi Go team,

I recently deleted the following repo:

github.com/PappasBrent/graph-spec

Could it please be deleted from pkg.go.dev? Given that the link to the package is now broken, it only makes sense to me that it should be removed.

Thank you

**Comment by Prajwal-Koirala** [comment]
@PappasBrent 
I am 99% sure it's completely automated.

**Comment by PappasBrent** [comment]
Ok, great. I still see it on the package list, so I figured I would open an issue in case the removal wasn't automated.

**Comment by julieqiu** [comment]
https://pkg.go.dev/github.com/PappasBrent/graph-spec now returns a 404.
