### ISSUE TITLE
Go escape analysis doesn't report variable escape with slice append

### ISSUE THREAD

**Issue by smiletrl** [golang/go#45148]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yea

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/smiletrl/Library/Caches/go-build"
GOENV="/Users/smiletrl/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/smiletrl/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/smiletrl/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/Cellar/go/1.16.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.2/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sq/2123x_0d19s90tx1q2wpgtxr0000gn/T/go-build1346053683=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I'm running escape analysis for a slice (with append), and it doesn't show this slice variable escaped. But in fact, there's heap allocation during the append process.

Here's the code https://play.golang.org/p/rLj488GDI0D, here's the test code https://play.golang.org/p/tTjveS2eAs6.

The escape analysis result is:

```
smiletrl@Rulins-MacBook-Pro example3 % go build -gcflags="-m -l" case1.go
# command-line-arguments
./case1.go:14:17: make([]employer, 1000) does not escape
./case1.go:29:12: ... argument does not escape
./case1.go:29:65: time.Now().Sub(start).Seconds() escapes to heap
```

and bench test result is:

```
smiletrl@Rulins-MacBook-Pro example3 % go test -bench=. -benchmem
goos: darwin
goarch: amd64
pkg: github.com/smiletrl/golang_escape/pkg/example3
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
BenchmarkSlice4-16    	  181234	      6480 ns/op	   32768 B/op	       1 allocs/op
PASS
ok  	github.com/smiletrl/golang_escape/pkg/example3	1.505s
```

Bench test shows that there's one heap allocation `1 allocs/op`, but escape analysis doesn't show anything like that `./case1.go:14:17: make([]employer, 1000) does not escape`.

The compile result is:

<details><summary><code> go tool compile -S case1.go</code> Output</summary><br><pre>
smiletrl@Rulins-MacBook-Pro example3 % go tool compile -S case1.go
"".getemployerSlice4 STEXT size=293 args=0x0 locals=0x3ed8 funcid=0x0
	0x0000 00000 (case1.go:13)	TEXT	"".getemployerSlice4(SB), ABIInternal, $16088-0
	0x0000 00000 (case1.go:13)	MOVQ	(TLS), CX
	0x0009 00009 (case1.go:13)	MOVQ	16(CX), SI
	0x000d 00013 (case1.go:13)	PCDATA	$0, $-2
	0x000d 00013 (case1.go:13)	CMPQ	SI, $-1314
	0x0014 00020 (case1.go:13)	JEQ	282
	0x001a 00026 (case1.go:13)	LEAQ	928(SP), AX
	0x0022 00034 (case1.go:13)	SUBQ	SI, AX
	0x0025 00037 (case1.go:13)	CMPQ	AX, $16888
	0x002b 00043 (case1.go:13)	JLS	282
	0x0031 00049 (case1.go:13)	PCDATA	$0, $-1
	0x0031 00049 (case1.go:13)	SUBQ	$16088, SP
	0x0038 00056 (case1.go:13)	MOVQ	BP, 16080(SP)
	0x0040 00064 (case1.go:13)	LEAQ	16080(SP), BP
	0x0048 00072 (case1.go:13)	FUNCDATA	$0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0048 00072 (case1.go:13)	FUNCDATA	$1, gclocals·0380c2a8d0fa28e01c0d123fff5f4bf6(SB)
	0x0048 00072 (case1.go:13)	FUNCDATA	$2, "".getemployerSlice4.stkobj(SB)
	0x0048 00072 (case1.go:14)	LEAQ	""..autotmp_3+80(SP), DI
	0x004d 00077 (case1.go:14)	MOVL	$2000, CX
	0x0052 00082 (case1.go:14)	XORL	AX, AX
	0x0054 00084 (case1.go:14)	REP
	0x0055 00085 (case1.go:14)	STOSQ
	0x0057 00087 (case1.go:14)	XORL	AX, AX
	0x0059 00089 (case1.go:14)	MOVL	$1000, CX
	0x005e 00094 (case1.go:14)	MOVL	$1000, DX
	0x0063 00099 (case1.go:14)	LEAQ	""..autotmp_3+80(SP), BX
	0x0068 00104 (case1.go:15)	JMP	112
	0x006a 00106 (case1.go:15)	INCQ	AX
	0x006d 00109 (case1.go:19)	MOVQ	SI, CX
	0x0070 00112 (case1.go:15)	CMPQ	AX, $1000
	0x0076 00118 (case1.go:15)	JGE	266
	0x007c 00124 (case1.go:19)	LEAQ	1(CX), SI
	0x0080 00128 (case1.go:19)	CMPQ	SI, DX
	0x0083 00131 (case1.go:19)	JHI	186
	0x0085 00133 (case1.go:19)	SHLQ	$4, CX
	0x0089 00137 (case1.go:19)	MOVQ	$4, 8(BX)(CX*1)
	0x0092 00146 (case1.go:19)	LEAQ	(BX)(CX*1), DI
	0x0096 00150 (case1.go:19)	PCDATA	$0, $-2
	0x0096 00150 (case1.go:19)	CMPL	runtime.writeBarrier(SB), $0
	0x009d 00157 (case1.go:19)	JNE	172
	0x009f 00159 (case1.go:19)	LEAQ	go.string."jack"(SB), R8
	0x00a6 00166 (case1.go:19)	MOVQ	R8, (BX)(CX*1)
	0x00aa 00170 (case1.go:19)	JMP	106
	0x00ac 00172 (case1.go:19)	LEAQ	go.string."jack"(SB), CX
	0x00b3 00179 (case1.go:19)	CALL	runtime.gcWriteBarrierCX(SB)
	0x00b8 00184 (case1.go:19)	JMP	106
	0x00ba 00186 (case1.go:19)	PCDATA	$0, $-1
	0x00ba 00186 (case1.go:19)	MOVQ	CX, "".emps.len+72(SP)
	0x00bf 00191 (case1.go:15)	MOVQ	AX, "".i+64(SP)
	0x00c4 00196 (case1.go:19)	LEAQ	type."".employer(SB), AX
	0x00cb 00203 (case1.go:19)	MOVQ	AX, (SP)
	0x00cf 00207 (case1.go:19)	MOVQ	BX, 8(SP)
	0x00d4 00212 (case1.go:19)	MOVQ	CX, 16(SP)
	0x00d9 00217 (case1.go:19)	MOVQ	DX, 24(SP)
	0x00de 00222 (case1.go:19)	MOVQ	SI, 32(SP)
	0x00e3 00227 (case1.go:19)	PCDATA	$1, $0
	0x00e3 00227 (case1.go:19)	CALL	runtime.growslice(SB)
	0x00e8 00232 (case1.go:19)	MOVQ	40(SP), BX
	0x00ed 00237 (case1.go:19)	MOVQ	48(SP), AX
	0x00f2 00242 (case1.go:19)	MOVQ	56(SP), DX
	0x00f7 00247 (case1.go:19)	LEAQ	1(AX), SI
	0x00fb 00251 (case1.go:15)	MOVQ	"".i+64(SP), AX
	0x0100 00256 (case1.go:19)	MOVQ	"".emps.len+72(SP), CX
	0x0105 00261 (case1.go:19)	JMP	133
	0x010a 00266 (case1.go:15)	PCDATA	$1, $-1
	0x010a 00266 (case1.go:15)	MOVQ	16080(SP), BP
	0x0112 00274 (case1.go:15)	ADDQ	$16088, SP
	0x0119 00281 (case1.go:15)	RET
	0x011a 00282 (case1.go:15)	NOP
	0x011a 00282 (case1.go:13)	PCDATA	$1, $-1
	0x011a 00282 (case1.go:13)	PCDATA	$0, $-2
	0x011a 00282 (case1.go:13)	CALL	runtime.morestack_noctxt(SB)
	0x011f 00287 (case1.go:13)	PCDATA	$0, $-1
	0x011f 00287 (case1.go:13)	NOP
	0x0120 00288 (case1.go:13)	JMP	0

</pre></details>

This func `runtime.growslice(SB)` does call `func mallocgc(size uintptr, typ *_type, needzero bool) unsafe.Pointer {`, which actually makes heap allocation.

GC trace command does show the GC records too.

```
smiletrl@Rulins-MacBook-Pro example3 % go build .  
smiletrl@Rulins-MacBook-Pro example3 % GODEBUG="gctrace=1" ./example3
```

<details><summary><code> GODEBUG="gctrace=1" ./example3</code> Output</summary><br><pre>
smiletrl@Rulins-MacBook-Pro example3 % GODEBUG="gctrace=1" ./example3
gc 1 @0.001s 3%: 0.010+0.19+0.059 ms clock, 0.17+0.043/0.15/0.078+0.95 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 2 @0.003s 3%: 0.023+0.14+0.035 ms clock, 0.37+0.058/0.097/0.039+0.56 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 3 @0.004s 4%: 0.024+0.22+0.034 ms clock, 0.39+0.040/0.091/0.020+0.55 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 4 @0.005s 4%: 0.023+0.15+0.025 ms clock, 0.37+0.057/0.088/0.001+0.41 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 5 @0.006s 4%: 0.025+0.21+0.011 ms clock, 0.40+0.040/0.096/0.013+0.18 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 6 @0.007s 4%: 0.025+0.13+0.019 ms clock, 0.40+0.021/0.066/0.086+0.31 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 7 @0.008s 4%: 0.025+0.15+0.003 ms clock, 0.40+0.017/0.098/0.088+0.056 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 8 @0.008s 5%: 0.023+0.11+0.026 ms clock, 0.37+0.017/0.099/0.057+0.41 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 9 @0.009s 5%: 0.024+0.11+0.012 ms clock, 0.38+0.013/0.085/0.12+0.20 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 10 @0.010s 5%: 0.024+0.12+0.029 ms clock, 0.39+0.022/0.11/0.055+0.47 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 11 @0.011s 5%: 0.024+0.12+0.036 ms clock, 0.38+0.022/0.079/0.059+0.58 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 12 @0.012s 5%: 0.026+0.12+0.022 ms clock, 0.41+0.036/0.12/0.054+0.36 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 13 @0.012s 5%: 0.042+0.19+0.037 ms clock, 0.68+0.018/0.088/0.070+0.59 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 14 @0.013s 5%: 0.024+0.10+0.019 ms clock, 0.39+0.016/0.068/0.089+0.30 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
...
gc 809 @0.670s 6%: 0.053+0.11+0.008 ms clock, 0.85+0.022/0.12/0.077+0.13 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 810 @0.671s 6%: 0.023+0.12+0.023 ms clock, 0.38+0.015/0.17/0.092+0.38 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 811 @0.672s 6%: 0.024+0.15+0.022 ms clock, 0.39+0.055/0.086/0.075+0.36 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 812 @0.673s 6%: 0.024+0.12+0.028 ms clock, 0.39+0.040/0.12/0.086+0.45 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 813 @0.674s 6%: 0.025+0.18+0.002 ms clock, 0.41+0.031/0.12/0.13+0.045 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 814 @0.674s 6%: 0.055+0.21+0.009 ms clock, 0.88+0.022/0.14/0.079+0.15 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 815 @0.675s 6%: 0.030+0.17+0.003 ms clock, 0.48+0.025/0.15/0.15+0.054 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 816 @0.676s 6%: 0.028+0.21+0.040 ms clock, 0.44+0.033/0.28/0.28+0.65 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 817 @0.677s 6%: 0.025+0.10+0.023 ms clock, 0.40+0.029/0.12/0.072+0.37 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 818 @0.678s 6%: 0.025+0.14+0.026 ms clock, 0.41+0.026/0.11/0.076+0.43 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
gc 819 @0.679s 6%: 0.024+0.14+0.003 ms clock, 0.38+0.026/0.17/0.087+0.051 ms cpu, 4->4->0 MB, 5 MB goal, 16 P
druation is: 0.679513306s
</pre></details>

The direct value assignment `//emps[i] = e` doesn't show any heap allocation.

### What did you expect to see?

Golang escape analysis does show the slice variable escaped.

`./case1.go:14:17: make([]employer, 1000) moved to heap`

### What did you see instead?

`./case1.go:14:17: make([]employer, 1000) does not escape`.

**Comment by randall77** [comment]
Use `make([]employer, 0, 1e3)` instead.

Your code is making slices of length 2000, the first 1000 being empty and the second 1000 being Jack. That requires 1 allocation.

**Comment by smiletrl** [comment]
@randall77, yea, thanks for the reply! I didn't notice that.

But wouldn't `emps = append(emps, e)` be reported to escape in this case? Or we could say, this is something happened at runtime, and escape analysis only happens at compile time. So it's kind of not escape's responsibility of reporting that out?

**Comment by randall77** [comment]
Escape analysis is only concerned with flow of data. `emps` does not escape here, it only flows to itself.

There's a related but distinct question of heap allocation vs. stack allocation. Generally to stack allocate a variable, it needs to not escape *and* have a size known at compile time. The allocation that happens here (in growslice) fails the second test, not the first.

**Comment by smiletrl** [comment]
excellent explanation, thanks!
