### ISSUE TITLE
index.golang.org/index  isn't reporting packages newer than 2019-04-18T02:07:41 currently

### ISSUE THREAD

**Issue by jphsd** [golang/go#45143]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
N/A - data pulled with curl
curl https://index.golang.org/index

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jphsd/Library/Caches/go-build"
GOENV="/Users/jphsd/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jphsd/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jphsd/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jphsd/go/src/jphsd.org/glui/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jx/_902qq451hv0kw88rcgsmq5h0000gn/T/go-build635998917=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I noticed my packages were no longer being updated in pkg.go.dev when I made new commits to them in github.

### What did you expect to see?
My packages updated.

### What did you see instead?
Stale packages.

**Comment by martisch** [comment]
It is starting to list packages from that date. See documentation at: https://index.golang.org/

> 'since': the oldest allowable timestamp (RFC3339 format) for module versions in the returned list. Default is the beginning of time, e.g. https://index.golang.org/index?since=2019-04-10T19:08:52.997264Z
> 'limit': the maximum length of the returned list. Default = 2000, Max = 2000, e.g. https://index.golang.org/index?limit=10
