### ISSUE TITLE
x/mod/modfile: document what the path is used for in Parse

### ISSUE THREAD

**Issue by dsnet** [golang/go#45149]
The [`Parse`](https://pkg.go.dev/golang.org/x/mod/modfile#Parse) function takes in a file name as the first argument. It does not seem obvious to me why a parse function should care about the file name at all in order to parse the contents of the the `go.mod` file. We should document better what this is used for and whether it is required.

Without studying the code too deeply, it seems that the filename is primarily used in error reporting and also to populate `modfile.File.Syntax.Name` but otherwise has not semantic impact on how the file is parsed.

In my situation, I don't have the original go.mod path on hand and it's not clear to me whether I should spend the effort to produce the exact right one or just put some arbitrary path.

**Comment by bcmills** [comment]
In is indeed just there for error output. (There are plenty of places in `cmd/go` itself where we just pass the string `"go.mod"` instead of a full path, when the full path is not available or not meaningful.)

Want to send a CL to clarify the documentation?
