### ISSUE TITLE
If I Assign a ReadCloser to Request.Body, I needn't to close the ReadCloser  by myself, Is it Right

### ISSUE THREAD

**Issue by agin719** [golang/go#45157]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
</pre></details>

### What did you do?

<details><summary><code>go env</code> Output</summary><br><pre>
package main

import (
    "log"
    "net/http"
    "os"
)

func main() {
    fd, err := os.Open("test")
    if err != nil {
        log.Fatal(err)
    }
    // return err: file is already closed
    defer fd.Close()
    //req, err := http.NewRequest("PUT", "http://localhost:8080/test.txt", fd)
    if err != nil {
        log.Fatal(err)
    }

    client := &http.Client{}
    res, err := client.Do(req)
    if err != nil {
        log.Fatal(err)
    }
    defer res.Body.Close()
}
</pre></details>

### What did you expect to see?
os.File is a ReadCloser, and the defer fd.Close() return a error that file is already closed.   My question is that will Request.Body be closed no matter when request finished?  
If I Assign a ReadCloser to Request.Body, I needn't to close the ReadCloser  by myself, Is it Right?

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
