### ISSUE TITLE
Error line:column positions are byte-based offsets, not character offsets

### ISSUE THREAD

**Issue by gonzojive** [golang/go#45169]
### What version of Go are you using (`go version`)?

<pre>
$  go version
go version go1.16.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.
### What operating system and processor architecture are you using (`go env`)?

n/a - playground

### What did you do?

See https://play.golang.org/p/J8yaQkcVFxI

```go
package main

func main() {
y := "😀" x
π 3
// "./prog.go:4:13: syntax error: unexpected x at end of statement"
// I would expect
// "./prog.go:4:10: syntax error: unexpected x at end of statement"
}

```

### What did you expect to see?

```
./prog.go:4:10: syntax error: unexpected x at end of statement
./prog.go:5:3: syntax error: unexpected literal 3 at end of statement
```

I would expect syntax error positions to be rune/character offsets, not byte offsets.

As far as I can tell this is working as intended, but it's at odds with most text editors' behavior. Apologies if this is a duplicate.

### What did you see instead?

```
./prog.go:4:13: syntax error: unexpected x at end of statement
./prog.go:5:4: syntax error: unexpected literal 3 at end of statement
```

**Comment by seankhliao** [comment]
See #10324 for the justification in making it a byte and not unicode code point offset

**Comment by gonzojive** [comment]
Thanks for the link. Feel free to close.
