### ISSUE TITLE
db.waitCount never decreases

### ISSUE THREAD

**Issue by voodoo-dn** [golang/go#45167]
### What version of Go are you using (`go version`)?

1.13.3

### Does this issue reproduce with the latest release?

Reproduced with 1.16.2

### What operating system and processor architecture are you using (`go env`)?

amd64

### What did you do?

We unexpectedly have seen strange counters in Grafana.

db.waitCount with huge number.

When I went to source code, i understand that this counter never decreases.

### What did you expect to see?

Counter decreases when connection given to consumer.

### What did you see instead?

Counter don't decreases.

The main question: Why used this behavior?

**Comment by seankhliao** [comment]
As the name (and the comments surrounding the value) imply, it is a counter: cumulative and monotonically increasing.
There are other places that describe the tradeoffs between counters and gauges in detail.

For questions please refer to https://github.com/golang/go/wiki/Questions
