### ISSUE TITLE
Go2 returning error automatically without manually checking it

### ISSUE THREAD

**Issue by ibudisteanu** [golang/go#45166]
I am working on a complex database **transaction** with 500+ lines of code inside and most of the functions are returning errors. The error handling in go is totally annoying in my case because no matter which error I get, the entire code is just not committing the database transaction by reverting any in-memory changes. So after writing 1000+ additional lines of code of `if err = func1(); err !=  nil { return }` only for checking errors I decided to switch to panics which removes 500+ lines of the additional code, but I do still have many error checks... Why don't we have a simple error checking operator like `output := func1() ?` or `output, err := func1() or return`. The golang is great but the error handling is simply terrible tbh.

**Comment by mdlayher** [comment]
This has been discussed countless times and you've ignored the issue/proposal template. Closing.

**Comment by ibudisteanu** [comment]
Of course I have read some of them. I just wanted to post my prost against the error handling of the golang. I even gave a concrete example where the golang error handling doesn't make any sense. In transactional databases.

**Comment by mdlayher** [comment]
The issue tracker is not the place to complain about error handling. Locking.
