### ISSUE TITLE
x/tools/gopls: Exhausted failed to load view

### ISSUE THREAD

**Issue by iamshreeram** [golang/go#45171]
### Issue
I use multi-module workspace (kinda monorepo). I'm getting an error from `gopls` that says -
```
Error loading workspace folders (expected 11, got 9) failed to load view for file:///Users/sram/ram/project: exhausted failed to load view for file:///Users/sram/ram/project/node: exhausted
```

`gopls` is looking for my `node` directory in my project workspace.

Below is the directory structure of my workspace:

<details><summary><code>my-workspace</code></summary><br><pre>
~
 | /.config
 | /.cabal/
 | /.nvm/
 | .bash_profile
 | .bashrc
 | /project/
 |  | /Clojure/
 |  |  | /allmycljprojects 
 |  | /Shell/
 |  |  | /allmybashprojects 
 |  | /rust/
 |  |  | /allmyrustprojects
 |  | /haskell/
 |  |  | /allmyhaskellprojects
 |  | /python/
 |  |  | /allmypythonprojects 
 |  | /go/
 |  |  | /bin
 |  |  | /pkg
 |  |  | /src
 |  |  |  | /github.com
 |  |  |  | /gitlab.com
 |  |  |  | /golang.org
 |  |  |  | /gopkg.in
 |  | /scala/
 |  |  | /allmyscalaprojects
 |  | /node/
 |  |  | /allmynodeprojects
</pre></details>

### Fix 
I would want to enable directory filters (`directoryFilters`) to explicitly say gopls to stop looking at `node` directory or `node_modules` in specific project path OR I want `gopls` to look at only the go directory in my project folder

Could you please help if below is right format? Will below help in specifying **gopls** to look only at go directory

    "gopls": {
         // "experimentalWorkspaceModule": true,
         "directoryFilters": ["+/~/project/go/"],
          ....
      }

Or Would I be able to use 

    "gopls": {
         // "experimentalWorkspaceModule": true,
         "directoryFilters":["-/Users/sram/ram/project/node/","-node_modules"],
          ....
      }

to make **gopls** to ignore all node directory?

### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.15.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes. I was seeing this issue even in earlier versions of `gopls`

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code></summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sram/Library/Caches/go-build"
GOENV="/Users/sram/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/sram/ram/project/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/sram/ram/project/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sn/pw7xq23n2vj_wnq16lkgdrxh0000gn/T/go-build150007759=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you expect to see?
No errors from `gopls`.

**Comment by stamblerre** [comment]
I believe you would want something like the following:

```json5
"gopls": {
     "directoryFilters":["-/Users/s0v00nr/ram/project","+/Users/s0v00nr/ram/project/go"],
}
```

if you only want `gopls` to look at the `go` directory.

/cc @heschi for confirmation

**Comment by iamshreeram** [comment]
Thanks! That worked. Below is my current config - 

```
    "gopls": {
        "ui.documentation.hoverKind": "SynopsisDocumentation",
        "build.directoryFilters":["-/Users/sram/ram/project","+/Users/sram/ram/project/go"],
        "build.experimentalWorkspaceModule": true,          
     }
```
