### ISSUE TITLE
During concurrent map write, why golang  kill whole process instead of killing only 1/2 goroutine?

### ISSUE THREAD

**Issue by omgommt** [golang/go#45179]
Concurrent map read/write can kill your whole application, even recover() cannot prevent/catch that
https://stackoverflow.com/questions/39288741/how-to-recover-from-concurrent-map-writes/39289246#39289246
But I am curious to know why golang made this behaviour to kill whole process instead of killing only 1/2 goroutine ?

### What version of Go are you using (`go version`)?
go version go1.13.5 darwin/amd64

### What did you do?
Developer

### What did you expect to see?
During concurrent map write error, Golang should not kill the whole process by throw()
and only kill goroutine accessing the memory concurrently.

### What did you see instead?
During concurrent map write error, Golang should kill the whole process by throw()

**Comment by ivanjaros** [comment]
you probably have that rw in the main thread, hence the entire app goes down. spin up a goroutine and run the code in it. if it crashes, it will take down only the green thread of that goroutine and not the main thread.

**Comment by omgommt** [comment]
@ivanjaros: Thanks for the reply.
it's happening even if some child goroutines are read/write data concurrently. If any child goroutine got error then main will be crashed.

https://play.golang.org/p/3qq06l1qH0B
You can also this code for the same.

**Comment by martisch** [comment]
the way to fix races is not to ignore them but to fix them. You can put a mutex on map access to prevent concurrent use. If go would just kill the go routine it might hold other state e.g. locks which could deadlock the program. Its better to be explicit that the program detected a race and that the program code needs to be fixed.

**Comment by omgommt** [comment]
Thanks, @martisch.
But instead of the killing process, if the goroutine returns panic, then the developer, can release the lock and other resources in defer functions.
I think this would be a better way for production code. It will avoid a surprise crash on production.

Other languages, like java, also handle concurrentModifiication cases in a similar way.

**Comment by martisch** [comment]
Instead of making the programmer work hard to anticipate every possible way for a go routine to exit non normally why not avoid the concurrent access to begin with?

The normal runtime concurrent access in maps is best effort so the concurrent access might not be detected and just lead to a potentially corrupted data in the map.

A crash in production is better than corrupted data in production.

**Comment by omgommt** [comment]
@martisch: Okay... got it.. understood the reason.
Thanks for clarifying.

**Comment by omgommt** [comment]
> A crash in production is better than corrupted data in production.

Apart from race condition issue, if their panic's and suppose handling them will cause inconsistency in data.
Would it be better to avoid using recover()? and let the application crash?


2. One way I can think of, we can implement a new type of handler of throw, like recoverThrow(). Let the developer decide, whether to crash the application for corrupt data or not, depending on the importance of that flow.

**Comment by omgommt** [comment]
Hi @martisch,
Adding one point, in favor of a production crash, is better.
i think goroutines keep on respawning/killed and can make the production system slow for a longer duration.
In case of a crash, we can quickly fix the issue.
