### ISSUE TITLE
csv reader fail with double quotes 

### ISSUE THREAD

**Issue by wakinaki** [golang/go#45172]
### What version of Go are you using (`go version`)?
go1.15.7 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
bigsur 11.2.1 amd64 (apple M1)

### What did you do?
import a csv file with this line:
14;440;0;"21700052";""MONITOR 19" HARD DISK 1GB 400"";02-01-2014;"";"";"230,000"

### What did you expect to see?
9 columns

### What did you see instead?
4 columns

We understand that the problem is ";""

**Comment by seankhliao** [comment]
Seems like you have bad data, `encoding/csv` follows [RFC 4180](https://tools.ietf.org/html/rfc4180)

> If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double quote. […]
