### ISSUE TITLE
io/fs: document whether []byte from ReadFile is (un)safe to modify

### ISSUE THREAD

**Issue by carlmjohnson** [golang/go#45186]
Here are the current docs for fs.ReadFileFS's ReadFile method:

```go
    // ReadFile reads the named file and returns its contents.
    // A successful call returns a nil error, not io.EOF.
    // (Because ReadFile reads the whole file, the expected EOF
    // from the final Read is not treated as an error to be reported.)
    ReadFile(name string) ([]byte, error)
```

This does not specify whether the returned `[]byte` must be safe to modify or not. I can see the argument for either. It's better for efficiency if it is unsafe and better for safety if it is safe. I think this needs to be documented because [Hyrum's Law](https://www.hyrumslaw.com)/[XKCD 1172](https://xkcd.com/1172/) ensures that very soon some `ReadFileFS` implementation will be made more efficient by returning an unmodifiable backing store `[]byte` and some clients will be made more efficient by modifying the return value of `fs.ReadFile`, which will lead to bugs.

**Comment by ianlancetaylor** [comment]
CC @rsc
