### ISSUE TITLE
runtime/cgo: relocation target _InterlockedExchangeAdd not defined in Windows build.

### ISSUE THREAD

**Issue by Simerax** [golang/go#45180]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes 1.16.2

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xf\AppData\Local\go-build
set GOENV=C:\Users\xf\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\xf\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\xf\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.2
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\xf\AppData\Local\Temp\go-build1530397974=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
I tried to build a project.
This project was previously succesfully built in go 1.14.6 on the same machine.

The interesting thing is I then uninstalled 1.16.2 and reinstalled 1.14.6 and it compiled fine again.
I then kept 1.14.6 and installed 1.16.2 as a second version on my system following [these](https://golang.org/doc/manage-install#installing-multiple) instructions. I was then able to build it with `go1.16.2`. 

So to me it seems like the problem is not in the go compiler itself but in something that go uses. 
I found a [microsoft article](https://docs.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-interlockedexchangeadd?redirectedfrom=MSDN) which states that

> This function is implemented using a compiler intrinsic where possible. For more information, see the WinBase.h header file and _InterlockedExchangeAdd

Does Go implement this Function itself or does go rely on gcc?
My gcc Version is 8.3.0

I don't really know which part of the project is relying on this function and I cannot share the project source code.
If someone knows how to trigger an include of that function just tell me I'll try to build it then.

### What did you expect to see?
succesful build like it was on 1.14.6

### What did you see instead?
`runtime/cgo(.text): relocation target _InterlockedExchangeAdd not defined`

**Comment by ianlancetaylor** [comment]
Go relies on a C compiler to implement the `InterlockedExchangeAdd` function.  This is only used by programs that use cgo, and such programs already require a C compiler anyhow.

I do not know why you only see this error in some cases.

CC @alexbrainman

**Comment by alexbrainman** [comment]
I agree with @ianlancetaylor - your program must be using cgo. And cgo requires properly working C compiler - gcc. With all proper libraries installed.

Perhaps you gcc installation is broken.

Perhaps if you show your program and full error output, we could try and reproduce the error ourselves.

Thank you.

Alex

**Comment by Simerax** [comment]
Like I said I cannot share the source code. It's proprietary company code.
I tested a little more the project also builds fine on 1.16.0 but still not on 1.16.2
I am unable to reproduce the error in a small example program.

I will close this now as it is very unlikely to be resolved and probably just a problem with the environment on my work machine.
