### ISSUE TITLE
x/build: consider making release information also available via GitHub Releases

### ISSUE THREAD

**Issue by ZacWolf** [golang/go#45185]
When trying to access: https://docs.github.com/rest/reference/repos#get-the-latest-release

Is this project handling releases in a way that would break the GitHub API?  
Is that intentional, or an issue of no one being aware?

Would be nice to be able to automate notification/upgrade for the latest released version, via the GitHub API.

**Comment by dmitshur** [comment]
The Go project provides an API for listing releases at https://golang.org/dl/?mode=json (also see #34864). It does not use GitHub releases at this time. It does use git tags, which are mirrored from the canonical https://go.googlesource.com/go source repository, so you could detect those.

I'm not aware if there's another issue tracking this. It could be a reasonable feature request to consider, but not a high priority at this time.

CC @golang/release.

**Comment by dmitshur** [comment]
Oh, I found an existing issue, #15966.

**Comment by ZacWolf** [comment]
Thanks for the information, about ```?mode=json``` URL. It sucks that it's another schema to parse-out, but it's better than parsing the HTML.
