### ISSUE TITLE
time.Parse("Jan 2, 2006", "Dec 4, 2019 11:14:25") returns an "extra text" error but does not even partially populate the time return value

### ISSUE THREAD

**Issue by rbucker** [golang/go#45195]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.16.2
</pre>

### Does this issue reproduce with the latest release?

YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rbucker/.cache/go-build"
GOENV="/home/rbucker/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/rbucker/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/rbucker/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/rbucker/bin/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/rbucker/bin/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="gcc-ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1925909121=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

time.Parse("Jan 2, 2006", "Dec 4, 2019 11:14:25")

https://play.golang.org/p/8RN0EnD2NMB

### What did you expect to see?

I'm thinking about the OS file exists test where one has to test the err to determine what type of file... or something like that, however, it would be better if the time variable was filled with whatever had been collected to that point.

### What did you see instead?

the default time value.

**Comment by ianlancetaylor** [comment]
I'm not sure what to say except: you're right.  If `time.Parse` is unable to parse the date, then it returns an error and an empty `time.Time` value.  That is how the function has worked since it was written, and changing it now would be more likely to introduce problems rather than fix them.
