### ISSUE TITLE
x/tour: Local version is different from the production version

### ISSUE THREAD

**Issue by leeyspaul** [golang/go#45196]
### What version of Go are you using (`go version`)?
go version go1.15.6 darwin/amd64

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
darwin, amd64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Run `go run golang.org/x/tour` to run the tour locally. 

### What did you expect to see?
The same version as it exists in production locally. 

### What did you see instead?
A different version with different pages. 

Local
![Screen Shot 2021-03-23 at 18 16 26](https://user-images.githubusercontent.com/16315857/112239534-e46be980-8c03-11eb-9d1f-9c2913282df3.png)

Production
![Screen Shot 2021-03-23 at 18 16 13](https://user-images.githubusercontent.com/16315857/112239516-dc13ae80-8c03-11eb-9499-0d0c3df6fb94.png)

**Comment by ALTree** [comment]
This is done on purpose. The part of the content prefixed with `#appengine:` are only displayed when the tour is deployed, and they're rendered in the local version.

**Comment by leeyspaul** [comment]
Thanks for the clarification! Is there a development workflow outlined anywhere? I was hoping to contribute to the content/tour!

**Comment by ALTree** [comment]
There's https://github.com/golang/tour, and AFAIK that's it. Keep in mind that only a few people in the Go team @ Google can deploy the tour. You can still send changes as described in the README of course.
