### ISSUE TITLE
wiki: new "CodeReviewConcurrency" page

### ISSUE THREAD

**Issue by leventov** [golang/go#45206]
@ianlancetaylor suggested in golang-nuts that https://github.com/code-review-checklists/go-concurrency can be moved into the Golang wiki.

**Comment by ianlancetaylor** [comment]
It's a wiki.  Anybody can add a new page.

**Comment by leventov** [comment]
Ok, added: https://github.com/golang/go/wiki/CodeReviewConcurrency

**Comment by ianlancetaylor** [comment]
Thanks.
