### ISSUE TITLE
x/pkgsite: missing anchors for "source files" and "directories" on a package page

### ISSUE THREAD

**Issue by neolit123** [golang/go#45210]
i could no find existing tickets for this. sorry if a dup.

### What is the URL of the page with the issue?
 
https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm
 
 
### What is your user agent?
 

```
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4350.0 Safari/537.36 
```

### Screenshot
 

 
 NONE
 
### What did you do?
 

 
reproduction steps:
- open this package [link](https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm).
- scroll to the bottom where "Source files" and "Directories" are.
- there are no clickable anchors ( ¶ ) over "Source files" and "Directories", so it's not possible to link to them.
 
 ### What did you expect to see?
 
anchors ( ¶ ) over the "Source files" and "Directories" sections for a certain package page.

NOTE: this was possible with the previous design of the go doc website.
the anchor for directories was `#pkg-subdirectories`
 
 ### What did you see instead?

no anchors.

**Comment by rdxmb** [comment]
@neolit123 

It seems that this has changed to `#section-directories`

https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm#section-directories

**Comment by neolit123** [comment]
thanks for the info.

**Comment by neolit123** [comment]
the change from`pkg-subdirectories` to `section-directories` is a minimal breaking change, which pkgsite could have avoided.
inspecting the HTML and looking at https://github.com/golang/pkgsite i think i can send a fix for the missing ¶.

**Comment by neolit123** [comment]
sent a PR for this here:
https://github.com/golang/pkgsite/pull/24

instead of pinning to the anchors to the new IDs, it might be a good idea to preserve the backwards compatibility and rename the IDs too. the diff for that would look like:

```diff
diff --git a/content/static/html/helpers/_unit_directories.tmpl b/content/static/html/helpers/_unit_directories.tmpl
index 3047e7b9..6d3d6a58 100644
--- a/content/static/html/helpers/_unit_directories.tmpl
+++ b/content/static/html/helpers/_unit_directories.tmpl
@@ -6,8 +6,9 @@
 
 {{define "unit_directories"}}
   <div class="UnitDirectories js-unitDirectories">
-    <h2 class="UnitDirectories-title" id="section-directories">
+    <h2 class="UnitDirectories-title" id="pkg-subdirectories">
       <img height="25px" width="20px" src="/static/img/pkg-icon-folder_20x16.svg" alt="">Directories
+      <a class="Documentation-idLink" href="#pkg-subdirectories">¶</a>
     </h2>
     <div class="UnitDirectories-expandButton js-expandAllDirectories">
       <button>Expand all</button>
diff --git a/content/static/html/helpers/_unit_files.tmpl b/content/static/html/helpers/_unit_files.tmpl
index 568c06f5..67c600f2 100644
--- a/content/static/html/helpers/_unit_files.tmpl
+++ b/content/static/html/helpers/_unit_files.tmpl
@@ -6,8 +6,9 @@
 
 {{define "unit_files"}}
   <div class="UnitFiles js-unitFiles">
-    <h2 class="UnitFiles-title" id="section-sourcefiles">
+    <h2 class="UnitFiles-title" id="pkg-sourcefiles">
       <img height="16px" width="12px" src="/static/img/pkg-icon-file_16x12.svg" alt="">Source Files
+      <a class="Documentation-idLink" href="#pkg-sourcefiles">¶</a>
     </h2>
     <div class="UnitFiles-titleLink">
       <a href="{{.SourceURL}}" target="_blank" rel="noopener">View all</a>
```

NOTE: i don't know what was the old ID for source files, was it `pkg-sourcefiles`?
let me know if you want this diff instead.
