### ISSUE TITLE
cmd/go: "go env" output should include GOEXPERIMENT

### ISSUE THREAD

**Issue by mdempsky** [golang/go#45226]
/cc @aclements @bcmills

**Comment by oiooj** [comment]
Do we need to add this environment into `go help environment` ?

**Comment by mdempsky** [comment]
I think that's fine, as long as it's made clear that it's for enabling experimental features that aren't supported or guaranteed to work and may change incompatibly or go away entirely in future releases.

I'd also recommend not listing available experiments. If necessary, point users towards cmd/internal/objabi.

**Comment by mdempsky** [comment]
I don't know why this got moved off the Go 1.17 milestone. I think it's important for user reports that `go env` indicate whether they've tampered with experiments.

**Comment by toothrot** [comment]
@mdempsky @bcmills Anything else to do before merging this change? The RC date is soon.

**Comment by mdempsky** [comment]
@toothrot I have a change for it, I just need to rebase it on top of the fix that was merged for #46815 for Go 1.17.

I plan to do that after mailing out CLs for #46742. I expect to have CLs for both of these out by EOD.

**Comment by mdempsky** [comment]
Okay, CLs [331109](https://go-review.googlesource.com/c/go/+/331109), [329654](https://go-review.googlesource.com/c/go/+/329654), and [328751](https://go-review.googlesource.com/c/go/+/328751) are mailed out for this issue.

@bcmills already approved the third only before rebasing. It's substantially unmodified by the rebase, so I think that CR+2 is still valid. I think just the first 2 need review.
