### ISSUE TITLE
x/pkgsite: my module does not show up on pkg.go.dev

### ISSUE THREAD

**Issue by deanveloper** [golang/go#45224]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/deanveloper/findregex
 
### What is your user agent?
 

 
 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
 
### Screenshot
 

 
![image](https://user-images.githubusercontent.com/3196327/112393981-29058c80-8cb9-11eb-9fc7-3d1dd09fa9af.png)

 
### What did you do?
 
Visit the page, request for the package to be added. It never gets added, no matter how long I wait.
 
I have followed the instructions at https://go.dev/about#adding-a-package, and the package is in the proxy at https://proxy.golang.org/github.com/deanveloper/findregex/@v/v1.0.0.info

### What did you expect to see?
 
 My package to be added
 
### What did you see instead?

"We're still working on “github.com/deanveloper/findregex”. Check back in a few minutes!". It has been probably about an hour, if not more.

**Comment by opennota** [comment]
It's finally there, it seems.

**Comment by deanveloper** [comment]
Looks like it got resolved. Hopefully the underlying issue was fixed
