### ISSUE TITLE
spec: define "addressable array"

### ISSUE THREAD

**Issue by choleraehyq** [golang/go#45229]
### What version of Go are you using (`go version`)?
1.16.2
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
Not related.
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
When I was reading https://golang.org/ref/spec#Address_operators, I found that the definition of "addressable" is using the term "addressable array".

> The operand must be addressable, that is, ...; or an array indexing operation of an addressable array.

But I can't find out any definition of "addressable array" itself. It seems to me that the definition of "addressable" is a cyclic definition. 

### What did you expect to see?
Definition of "addressable array".

### What did you see instead?
There is no definition of "addressable array" in the specification.

Maybe related: https://github.com/golang/go/issues/32714#issuecomment-504247727. IMHO, Ian only explained it from the implementation aspect, not the language specification aspect.

**Comment by randall77** [comment]
This is just a recursive definition. `x[i]` is addressable if `x` is addressable and is of array type.
