### ISSUE TITLE
x/tools/gopls: experimental semantic tokenizing of suggested argument names in user defined function types

### ISSUE THREAD

**Issue by soypat** [golang/go#45233]
### What did you do?
Define some function types:
```go
type Shape func(xyz ...float64) float64
type ABC func(uvw float64) (err error)

func (a Node) Sh(abc ...int) {}
```
gopls highlights `xyz` and `uvw` (suggested function argument names) as semantic tokens. This may be intentional, but I believe it is worth discussing if these "variable names" should be categorized as types, after all `abc` (in the same example) is not categorized as a semantic token.

<details><summary>Version info/env</summary>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
I am in the latest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$  go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/pato/go/bin"
GOCACHE="/home/pato/.cache/go-build"
GOENV="/home/pato/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/pato/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pato/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/home/pato/src/gofeas/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2731818870=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

</details>

**Comment by pjweinb** [comment]
That seems to be what it is doing. What should it do? gopls semtok produces
/*⇒4,keyword,[]*/type /*⇒5,type,[definition]*/Shape /*⇒4,keyword,[]*/func(/*⇒3,type,[definition]*/xyz /*⇒3,operator,[]*/.../*⇒7,type,[]*/float64) /*⇒7,type,[]*/float64
/*⇒4,keyword,[]*/type /*⇒3,type,[definition]*/ABC /*⇒4,keyword,[]*/func(/*⇒3,type,[definition]*/uvw /*⇒7,type,[]*/float64) (/*⇒3,type,[definition]*/err /*⇒5,type,[]*/error)

/*⇒4,keyword,[]*/func (/*⇒1,variable,[]*/a /*⇒4,variable,[definition]*/Node) /*⇒2,member,[definition]*/Sh(/*⇒3,parameter,[definition]*/abc /*⇒3,operator,[]*/.../*⇒3,type,[]*/int) {}

**Comment by soypat** [comment]
So the part that seems off to me is `/⇒3,type,[definition]/xyz`, as `xyz` is not really a definition, but really just an argument name suggestion. The user of the `Shape` type can choose to use `xyz` as the argument name or just any other name within the Go rules for identifier naming. Which brings me to the next point, `xyz` is closer to an identifier (`parameter` semtok).

**Comment by pjweinb** [comment]
thanks. let me think about it overnight. (or over-weekend).

**Comment by pjweinb** [comment]
There's the same issue in type X struct{A int}, which syntactically just has a StructDecl instead of a FuncDecl, so it need to change both places, i think.

**Comment by soypat** [comment]
Yes, I was about to create an issue complaining on that! The following declaration is confusing since all of the contents are colored the same!
```go
type rocket struct {
	// detalles constructivos
	caliber, length, massEmpty float64
	// esp. tecnicas
	thrustMax, burnTime, propInitialMass float64
	// rocket state
	apogee, empty, mainParachute bool
}
```
I believe `apogee`, `empty`, `mainParachute` should be colored differently than `bool` for the same reasons as function parameters.

**Comment by soypat** [comment]
Inline type definition seems to work as expected. The following example has the expected behaviour in `gopls v0.6.9`.

```go
v := struct{A int}{}
var w struct{A float64}
var u = struct{A complex128}{}
```
Does color `A` and its type differently.

**Comment by pjweinb** [comment]
I will produce a fix. Thanks for reporting this.

**Comment by pjweinb** [comment]
https://go-review.googlesource.com/c/tools/+/305209
