### ISSUE TITLE
x/crypto/ssh: unexpected empty user field for client conn

### ISSUE THREAD

**Issue by povsister** [golang/go#45249]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
It's not necessary here.

</pre></details>

### What did you do?
After using `golang.org/x/crypto/ssh` to connect to server successfully, unable to retrieve username used to connect to server.
```go
sshCfg := &ssh.ClientConfig{
    User: "root",
    Auth: []ssh.AuthMethod{
	    ssh.Password("testpw"),
    },
    HostKeyCallback: ssh.InsecureIgnoreHostKey(),
    Timeout: 3 * time.Second,
}

sshClient, _ := ssh.Dial("tcp", "test.server:22", sshCfg)

fmt.Println(sshClient.User())
// gives empty string

```

### What did you expect to see?
```go
fmt.Println(sshClient.User())
// should print "root"
```

### What did you see instead?
Server-side connection does not have this problem. The username at client-side seems to be dropped by accident here.
https://github.com/golang/crypto/blob/0c34fe9e7dc2486962ef9867e3edb3503537209f/ssh/client.go#L79-L81

I will open a pull-request to fix it later.

**Comment by povsister** [comment]
The reason why I opened this issue is that this bug blocks me from getting the user from existing SSH client.
Without running commands on remote (e.g: `whoami`), it's not possible to know which user is attached to the existing connection.

**Comment by networkimprov** [comment]
cc @FiloSottile
