### ISSUE TITLE
cmd/link: Linking with a non-clang linker fails when the path contains the string "clang"

### ISSUE THREAD

**Issue by woehr** [golang/go#45241]
### What version of Go are you using (`go version`)?

<pre>
1.16
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

The following code in https://github.com/golang/go/blob/74fe516c3549e8177aa5326e6ce17efd529e3383/src/cmd/link/internal/ld/lib.go#L1478 causes linking with a non-clang linker to fail when using a toolchain that exists in a path with the string "clang". The failure occurs because not all compilers (g++ in my case) support the flag "-Qunused-arguments".

Fix: If you want to know whether clang is being used, search the filename, not the entire path.

```
	if strings.Contains(argv[0], "clang") {
		argv = append(argv, "-Qunused-arguments")
	}
```
### What did you do?

Build a project with a toolchain under a path with the string "clang". For example, /home/clanger/compiler/bin/g++.

### What did you expect to see?

Linking should succeed.

### What did you see instead?

Linking failed.

**Comment by cherrymui** [comment]
> Fix: If you want to know whether clang is being used, search the filename, not the entire path.
> ```
>	if strings.Contains(argv[0], "clang") {
>		argv = append(argv, "-Qunused-arguments")
>	}
> ```

I think I understand your problem, but I'm not sure I followed what you meant here with the "fix'.

I guess we could check if the C linker is clang by running `$CC -v` or something.
cc @thanm

**Comment by woehr** [comment]
> > Fix: If you want to know whether clang is being used, search the filename, not the entire path.
> > ```
> >   if strings.Contains(argv[0], "clang") {
> >   	argv = append(argv, "-Qunused-arguments")
> >   }
> > ```
> 
> I think I understand your problem, but I'm not sure I followed what you meant here with the "fix'.
> 
> I guess we could check if the C linker is clang by running `$CC -v` or something.
> cc @thanm

Something like:
```
	path := "/some/path/with/clang/in/it"
	file := filepath.Base(path)
	if strings.Contains(file, "clang") {
		fmt.Println("is clang")
	} else {
		fmt.Println("not clang")
	}
```

**Comment by ianlancetaylor** [comment]
What if we just use `linkerFlagSupported` rather than trying to guess whether the linker is clang?
