### ISSUE TITLE
Question: Why does the recursive call to schedule not overflow the stack?

### ISSUE THREAD

**Issue by zonghaishang** [golang/go#45247]
The start of the go process will create some threads, which will trigger the go scheduling method. When the go process exits (goexit), the schedule method will be called again for the next round of scheduling. Why does the recursive call to schedule not overflow the stack?

![image](https://user-images.githubusercontent.com/15549777/112584606-2038c600-8e33-11eb-90ed-75217a842004.png)

### What version of Go are you using (`go version`)?

<pre>
$ go version 

1.15

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker for questions.  Please use a forum.  Thanks.

When using a forum, please show code as plain text or as a link to the Go playground or the Go source code.  Please don't show a screenshot.  Those are very hard to read for many people.  Thanks.

As the comment for the `schedule` function says, the function never returns.  There is no recursive call.

**Comment by zonghaishang** [comment]
Thank you for your reply. `schedule` does not call `schedule`  directly inside. There is no recursive call.
