### ISSUE TITLE
import cycle not allowed

### ISSUE THREAD

**Issue by Cruising0904** [golang/go#45255]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\q1\AppData\Local\go-build
set GOENV=C:\Users\q1\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\q1\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\q1\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.2
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\q1\Documents\workspace\go\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\q1\AppData\Local\Temp\go-build1384607938=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
I am a newbie 
I tried to work with excelize, followed the structure on https://xuri.me/excelize/ko/base/installation.html
but 

package main

import (
    "fmt"

    "github.com/360EntSecGroup-Skylar/excelize/v2"
)

func main() {
    f := excelize.NewFile()
    // 워크시트 만들기
    index := f.NewSheet("Sheet2")
    // 셀 값 설정
    f.SetCellValue("Sheet2", "A2", "Hello world.")
    f.SetCellValue("Sheet1", "B2", 100)
    // 통합 문서에 대 한 기본 워크시트를 설정 합니다
    f.SetActiveSheet(index)
    // 지정 된 경로를 기반으로 파일 저장
    if err := f.SaveAs("Book1.xlsx"); err != nil {
        fmt.Println(err)
    }
}

I put this code and run 
it seems not working saying 
 imports github.com/360EntSecGroup-Skylar/excelize/v2
        imports github.com/360EntSecGroup-Skylar/excelize/v2: import cycle not allowed
I studied and tried days.. I just think it's a bug 
if I put version suffix it seems not recognized in the system

![image](https://user-images.githubusercontent.com/29267295/112673270-df2ec900-8ea7-11eb-858c-1dc06b5fe881.png)

### What did you expect to see?
I hoped to see the code working and an excel file as an output

### What did you see instead?
package command-line-arguments
        imports github.com/360EntSecGroup-Skylar/excelize/v2
        imports github.com/360EntSecGroup-Skylar/excelize/v2: import cycle not allowed

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
