### ISSUE TITLE
crypto/hmac: panics

### ISSUE THREAD

**Issue by Mr-Leshiy** [golang/go#45252]
Hello I have found a weird behaviour of the sha256 Reset() method with the hmac. So I have the following question.
Why does this example produce panics ?
```go
sha256Hash := sha256.New()

salt := []byte{1, 2, 3}

hmac.New(func() hash.Hash {
	sha256Hash.Reset()
	return sha256Hash
}, salt)
```
```
panic: crypto/hmac: hash generation function does not produce unique values
```
But this example does not produce panics
```go
salt := []byte{1, 2, 3}

hmac.New(func() hash.Hash {
	return sha256.New()
}, salt)
```

What is the difference between these examples.

**Comment by ericlagergren** [comment]
This on purpose. See: https://github.com/golang/go/commit/2a206c7fcc91854a0ab78fe5799bda38dd330b11

cc: @FiloSottile

**Comment by FiloSottile** [comment]
An HMAC instance needs two independent hash instances simultaneously. Your first example used to produce incorrect results if you tried to call `hmac.Reset`.
