### ISSUE TITLE
x/tools/gopls: can't upgrade transitive dependencies

### ISSUE THREAD

**Issue by inliquid** [golang/go#45262]
1. VS Code
2. gopls@master

Getting this error when calling "Upgrade transitive dependencies". "Upgrade direct dependencies" works.

And when I call `go get -u -d ./...`, it also upgrades everything including transitive normally.

```
[Error - 16:51:49] 2021/03/27 16:51:49 command error: err: exit status 1: stderr: go: downloading golang.org/x/sys v0.0.0-20210326220804-49726bf1d181
go get all: module google.golang.org/protobuf@upgrade found (v1.26.0), but does not contain package google.golang.org/protobuf/internal/detectknown
go get all: module google.golang.org/protobuf@upgrade found (v1.26.0), but does not contain package google.golang.org/protobuf/internal/fieldnum
go get all: module google.golang.org/protobuf@upgrade found (v1.26.0), but does not contain package google.golang.org/protobuf/internal/fieldsort
go get all: module google.golang.org/protobuf@upgrade found (v1.26.0), but does not contain package google.golang.org/protobuf/internal/genname
go get all: module google.golang.org/protobuf@upgrade found (v1.26.0), but does not contain package google.golang.org/protobuf/internal/mapsort
go get all: module google.golang.org/protobuf@upgrade found (v1.26.0), but does not contain package google.golang.org/protobuf/internal/testprotos/fieldmaskpb


[Error - 16:51:49] Request workspace/executeCommand failed.
  Message: err: exit status 1: stderr: go: downloading golang.org/x/sys v0.0.0-20210326220804-49726bf1d181
go get all: module google.golang.org/protobuf@upgrade found (v1.26.0), but does not contain package google.golang.org/protobuf/internal/detectknown
go get all: module google.golang.org/protobuf@upgrade found (v1.26.0), but does not contain package google.golang.org/protobuf/internal/fieldnum
go get all: module google.golang.org/protobuf@upgrade found (v1.26.0), but does not contain package google.golang.org/protobuf/internal/fieldsort
go get all: module google.golang.org/protobuf@upgrade found (v1.26.0), but does not contain package google.golang.org/protobuf/internal/genname
go get all: module google.golang.org/protobuf@upgrade found (v1.26.0), but does not contain package google.golang.org/protobuf/internal/mapsort
go get all: module google.golang.org/protobuf@upgrade found (v1.26.0), but does not contain package google.golang.org/protobuf/internal/testprotos/fieldmaskpb

  Code: 0 

```

**Comment by stamblerre** [comment]
Thanks for the report! Currently, the upgrade transitive dependencies command runs `go get -u all` in your working directory. Does that fail with the same error message?

/cc @heschi for additional help on go commands/upgrading modules

**Comment by inliquid** [comment]
Yes, `go get -u all` fails
```
> go get -u all 
go: downloading golang.org/x/net v0.0.0-20210330075724-22f4162a9025
go: downloading github.com/golang/protobuf v1.5.2
go get all: module google.golang.org/protobuf@upgrade found (v1.26.0), but does not contain package google.golang.org/protobuf/internal/detectknown
go get all: module google.golang.org/protobuf@upgrade found (v1.26.0), but does not contain package google.golang.org/protobuf/internal/fieldnum
go get all: module google.golang.org/protobuf@upgrade found (v1.26.0), but does not contain package google.golang.org/protobuf/internal/fieldsort
go get all: module google.golang.org/protobuf@upgrade found (v1.26.0), but does not contain package google.golang.org/protobuf/internal/genname
go get all: module google.golang.org/protobuf@upgrade found (v1.26.0), but does not contain package google.golang.org/protobuf/internal/mapsort
go get all: module google.golang.org/protobuf@upgrade found (v1.26.0), but does not contain package google.golang.org/protobuf/internal/testprotos/fieldmaskpb
```

What's the difference between `go get -u all` and `go get -u -d ./...` in general? I was using latter all the time time since modules introduction on different projects with no issues. And it's actually mentioned in documentation, so I suppose it's officially recommended? https://golang.org/ref/mod#go-get

Also I'd like to see which `go` commands `gopls` is running, for example in gopls output (right now it's empty). Is it possible?

**Comment by stamblerre** [comment]
What Go version are you using? @bcmills mentioned that in 1.16, `go get -u -t ./...` should behave the same as `go get -u all`. For earlier versions, it seems like `go get -u -t ./...` is the correct command, so we'll switch to that.

> Also I'd like to see which go commands gopls is running, for example in gopls output (right now it's empty). Is it possible?

No, this is not possible. You will see the name of the command in the logs, but we don't currently log the full `go` command. Usually it has some additional flags and would be too verbose for most cases.

**Comment by inliquid** [comment]
I'm using `go1.16` right now it's `1.16.3`. Note that I'm using `go get -u -d ./...`, not `go get -u -t ./...` which effectively updates _transitive_ dependencies, not only direct ones.

**Comment by bcmills** [comment]
@inliquid, the `-u` flag is what causes transitive dependencies to be updated. The `-t` flag causes `go get` to trace the test dependencies of the named packages.

I think I also forgot the `-d` flag in my suggestion to @stamblerre.

So `go get -d -u -t ./...` means:
* `go get -d`: “fetch and download (but do not build)”
* `-u`: “upgraded transitive dependencies”
* `-t`: “including dependencies of tests”
* `./...`: “for all packages in subdirectories within the module”.
