### ISSUE TITLE
Testing with go 1.16 with unexpected call

### ISSUE THREAD

**Issue by binsta** [golang/go#45274]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.16.2
</pre>

### Does this issue reproduce with the latest release?
yeah, testing is better in 1.14

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code>
$ go env 
</summary><br><pre>
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\binst\AppData\Local\go-build
set GOENV=C:\Users\binst\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\binst\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\binst\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.2
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\binst\Desktop\store-api\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\binst\AppData\Local\Temp\go-build1283002382=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you expect to see?

[test_result.txt](https://github.com/golang/go/files/6218158/test_result.txt)

**Comment by ianlancetaylor** [comment]
I have not looked at the code in question.  The error you report says that the test code got an "invalid memory address or nil pointer dereference" at c:/Users/binst/Desktop/store-api/api/models/product_test.go:15.  Are you sure that your code is not trying to dereference a nil pointer?
