### ISSUE TITLE
cmd/cover: empty profile

### ISSUE THREAD

**Issue by devplayerJoe** [golang/go#45285]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.9 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="$HOME/Library/Caches/go-build"
GOENV="$HOME/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="$HOME/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="$HOME/go/project1/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nt/gc7658bs1132ttlcjdmlwwxm0000gn/T/go-build221587211=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I am generating respective coverage files for each ```_test.go``` file. However, I am getting an error while executing the ```gocovmerge``` command from last few days. I first encountered it on 25 March, then on 26-27 March, it worked fine. But again from 28-29 March, I am facing the same issue again. 

Executed below command to generate merged coverage profile file
<pre>
gocovmerge ${coverageDir}/myTest-*-coverage.profile
</pre>

### What did you expect to see?
Merged coverage profile file being generated without any error

### What did you see instead?
<pre>
2021/03/30 01:43:34 failed to parse profiles: line "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" doesn't match expected format: couldn't find a   before Count
</pre>

Kindly assist in nailing down the issue.

**Comment by seankhliao** [comment]
- go1.13 is no longer supported
- gocovmerge is not part of the Go project
- There isn't any info for us to do anything about this

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by devplayerJoe** [comment]
go1.13 is no longer supported-----> From when has this happened w.r.t. code pofile?

**Comment by devplayerJoe** [comment]
Got one coverage file having binary data. There are 40 ish test patterns for unit tests and all of them are creating separate coverage profile file ${profileName}.profile with command:
go test -p 1 -cover -v ./${pkgName} -run ${pattern} -coverprofile=${profileName}.profile ./${pkgName}
All other files are 1M in size and only file containing binary data in end has size 148K.
Any pointers on why it could happen?

**Comment by davecheney** [comment]
A bit of a long shot, but `./${pkgName}` should appear at the of the arguments, not intermixed with hyphenated flags. Maybe that helps.

**Comment by devplayerJoe** [comment]
> Got one coverage file having binary data. There are 40 ish test patterns for unit tests and all of them are creating separate coverage profile file `${profileName}.profile` with command:
> `go test -p 1 -cover -v ./${pkgName} -run ${pattern} -coverprofile=${profileName}.profile ./${pkgName}`
> All other files are 1M in size and only file containing binary data in end has size 148K.
> Any pointers on why it could happen?

Sorry for the  typo: ` ./${pkgName}` is  `${pkgName}` :
`go test -p 1 -cover -v ${pkgName} -run ${pattern} -coverprofile=${profileName}.profile ${pkgName}`


Keeping `${pkgName}` at the end of the argument list is not helping...still the problem persists.

**Comment by mvdan** [comment]
Closing old issues that still have the WaitingForInfo label where enough details to investigate weren't provided. Feel free to leave a comment with more details and we can reopen.
