### ISSUE TITLE
x/pkgsite: remove package github.com/gudvinr/gvonny

### ISSUE THREAD

**Issue by gudvinr** [golang/go#45287]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/gudvinr/gvonny
 
### What did you do?

1. Deleted repository
2. Opened page in the browser
 
### What did you expect to see?
 
Nothing, since this package doesn't exist anymore
 
### What did you see instead?

Documentation page for package that doesn't exist

**Comment by jamalc** [comment]
Done.
