### ISSUE TITLE
sort.Slice panic on empty slice

### ISSUE THREAD

**Issue by philpennock** [golang/go#45284]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 linux/amd64
</pre>

(and my colleague is on darwin/amd64; stack trace samples below from that.

### Does this issue reproduce with the latest release?

Yes, but not reliably.  Two people have each seen this once and been unable to reproduce live, and unable to reproduce in the playground.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pdp/.cache/go-build"
GOENV="/home/pdp/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/pdp/go/pkg/mod"
GONOPROXY="PRIVATE"
GONOSUMDB="PRIVATE"
GOOS="linux"
GOPATH="/home/pdp/go"
GOPRIVATE="PRIVATE"
GOPROXY="https://athens.home.pennock.cloud,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/home/pdp/tmp/go-build2390663162=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

We have not been able to reliably reproduce this failure, but two people on two OSes have now seen it: we have code which creates a slice of objects and then sorts them.  It normally works fine.  Occasionally the slice is empty (unknown reason) and then sort.Slice() panics in the callback:

```
panic: runtime error: index out of range [1] with length 0
```

I saw the same but with `range [0]` when this happened to me.

### What did you expect to see?

`sort.Slice([]foo{}, callback)` should never call the callback

### What did you see instead?

With minor redaction:

```
panic: runtime error: index out of range [1] with length 0
goroutine 52 [running]:
PRIVATE/pkg/model.(*implClouds).List.func1(0x1, 0x0, 0x0)
	PRIVATE/pkg/model/cloud.go:234 +0xea
sort.insertionSort_func(0xc00008bb98, 0xc0004430e0, 0x0, 0x3)
	/usr/local/Cellar/go/1.16.2/libexec/src/sort/zfuncversion.go:12 +0xab
sort.quickSort_func(0xc00008bb98, 0xc0004430e0, 0x0, 0x3, 0x4)
	/usr/local/Cellar/go/1.16.2/libexec/src/sort/zfuncversion.go:158 +0x1f6
sort.Slice(0x24bc320, 0xc00053bc50, 0xc00008bb98)
	/usr/local/Cellar/go/1.16.2/libexec/src/sort/slice.go:20 +0xe8
```

The triggering code is this; it's not a standalone snippet, I include it in case some aspect of invocation pattern jumps out at the maintainers as ticking some obscure corner:

```go
func (i *implClouds) List() CloudList {
	if i.list == nil {
		i.list = make(CloudList, 0, len(i.dict))
		for _, cloud := range i.dict {
			i.list = append(i.list, cloud)
		}
		sort.Slice(i.list, func(a, b int) bool {
			return i.list[a].Moniker() < i.list[b].Moniker()
		})
	}
	return i.list
}
```

**Comment by robpike** [comment]
It feels like a race to me. Another goroutine could be sorting i.list at the same time, since the field is visible to all goroutines.

If you don't believe that, try doing 

```
list = make ...
sort....
i.list = list
```

and I suspect you'll fix the race but expose other bugs.

**Comment by ianlancetaylor** [comment]
Be sure to try running your program under the race detector (https://blog.golang.org/race-detector).

**Comment by davidkemper** [comment]
Thanks for the quick feedback. We'll investigate more on our side.

**Comment by davidkemper** [comment]
You are indeed correct; this is a race condition: the lazy evalutation is now being accessed from goroutines from what before was a synchronous command set.

Thank you for your patience.

**Comment by philpennock** [comment]
Sigh.  Thank you Rob for the gentle correction and the immediate insight.  This issue can be marked invalid.  Sorry for the noise.

**Comment by robpike** [comment]
No problem, glad it was an easy one to spot.
