### ISSUE TITLE
go/build: running gcc failed: exit status 1 when I try to compile simple hello world program to android/arm

### ISSUE THREAD

**Issue by m-abdalrahman** [golang/go#45280]
### What version of Go are you using (`go version`)?

<pre>
go version go1.16.2 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN="/media/user/sda7/golang/go-lib/bin"
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/media/user/sda7/golang/go-lib/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/media/user/sda7/golang/go-lib"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/media/user/sda7/golang/go-lib/src/app/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3597029625=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
compile simple **Hello World** program to **android/arm** depending on this article https://rakyll.org/cross-compilation/  
**code:**
```
package main
import "fmt"
func main() {
    fmt.Println("hello world")
}
```
`GOOS=android GOARCH=arm GOARM=7 go build .
`

### What did you expect to see?
app.apk

### What did you see instead?
```
loadinternal: cannot find runtime/cgo
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
gcc: error: unrecognized command line option ‘-marm’; did you mean ‘-mabm’?

```

**Comment by cheater000** [comment]
Fucking coward Rick Garcia u ain't shit but a fucking liar all day long

**Comment by tklauser** [comment]
FYI, I've deleted a comment which contained profanity and slurs. This didn't add anything to the issue itself and was in violation of the [Go Community Code of Conduct](https://golang.org/conduct).

**Comment by AlexRouSg** [comment]
I think the author is trying to do a no cgo build based on what the linked article is saying.
I remember somewhere that cgo/ndk is required for android (sometime after that article was posted) but I can't find anything to link to.

cc @eliasnaur

**Comment by m-abdalrahman** [comment]
> Are the right gcc cross-compilers installed?

yes,
```
$ gcc --version 
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
@dr2chase 

> I think the author is trying to do a no cgo build based on what the linked article is saying.

yes, that's what I do @AlexRouSg

**Comment by eliasnaur** [comment]
See https://github.com/golang/go/tree/master/misc/android for getting started building programs for Android. @AlexRouSg is right that the NDK is needed, and if you want to use Go in apps you'll need `-buildmode c-shared` to build a shared library to use through JNI. There's also [GoMobile](https://github.com/golang/mobile) for making it easier embedding and calling of Go libraries.

**Comment by eliasnaur** [comment]
> ### What did you expect to see?
> 
> app.apk

The standard toolchain will definitely not output .apk (Android app) binaries. For that you need GoMobile, or perhaps even [Fyne](https://fyne.io) or (shameless plug) [Gio](https://gioui.org)

**Comment by cheater000** [comment]
Lmfao....Rick Garcia is nothing but a liar n cheat.

**Comment by m-abdalrahman** [comment]
> See https://github.com/golang/go/tree/master/misc/android for getting started building programs for Android. @AlexRouSg is right that the NDK is needed, and if you want to use Go in apps you'll need `-buildmode c-shared` to build a shared library to use through JNI. There's also [GoMobile](https://github.com/golang/mobile) for making it easier embedding and calling of Go libraries.

thank you, this meaning the old implementation in the article has been changed
`
GOOS=android GOARCH=arm GOARM=7 go build .
`
