### ISSUE TITLE
x/tools/gopls: renaming test file package declaration `package_test `-> `package` falsely claims import cycle

### ISSUE THREAD

**Issue by soypat** [golang/go#45317]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 linux/amd64
$ gopls version
golang.org/x/tools/gopls v0.6.9
    golang.org/x/tools/gopls@v0.6.9 h1:LBBcE2y3Tb4bp79JVLWCQBbvYCFEs5ADGWsQDoSLk1Q=
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/pato/go/bin"
GOCACHE="/home/pato/.cache/go-build"
GOENV="/home/pato/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/pato/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pato/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/home/pato/src/godesim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1047604572=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Renamed a *_test.go file package declaration from `package godesim_test` to `package godesim`

### What did you expect to see?
All good, package renamed. No biggie.

### What did you see instead?
Gopls insisted there was an import cycle, even after removing the `import ( "godesim" )` statement. After restarting gopls this did not persist. I've been able to reproduce it on several packages.

**Comment by soypat** [comment]
The problem seems to happen when there are other files with `package_test` package declaration who import the base package.

**Comment by findleyr** [comment]
I believe this is now fixed, along with #52500, but it warrants confirmation.

**Comment by findleyr** [comment]
I've confirmed that this is now resolved.
