### ISSUE TITLE
x/build: dragonfly-amd64 builder missing

### ISSUE THREAD

**Issue by tklauser** [golang/go#45312]
SlowBot runs for dragonfly were/are stuck on several CLs, e.g. https://golang.org/cl/304870, https://golang.org/cl/305230 or https://golang.org/cl/304369 (I re-triggered the latter to run on the dragonfly-amd64-5_8 builder which seems to be up).

On https://farmer.golang.org I see:

```
* host-dragonfly-amd64-master: 252 waiting (oldest 203h26m13s, newest 112h33m44s, progress 171h4m40s)
    * try: 1 (oldest 112h33m44s, newest 112h33m44s)
```

and

```
host-dragonfly-amd64-master: 0/0 (1 missing)
```

Related? #44584 #45215

/cc @golang/release @bcmills @dmitshur @tuxillo

**Comment by cagedmantis** [comment]
@tuxillo It seems like both of the dragonfly builders are missing:
```
host-dragonfly-amd64-5_8: 0/0 (1 missing)
host-dragonfly-amd64-master: 0/0 (1 missing)
```
I know we are working our way through #44584 and #45216. Can you take a quick look at the builders?

**Comment by tuxillo** [comment]
@cagedmantis I restarted them and they seem okay now. Let me know.

**Comment by dmitshur** [comment]
I see that both of these builders are online and doing work, so closing this.

```
host-dragonfly-amd64-5_8: 1/1
host-dragonfly-amd64-master: 1/1
```

Thank you @tuxillo.
