### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by ColeDrain** [golang/go#45329]
I spotted an error in the Go tutorial - **Call your code from another module** on the site [link to page](https://golang.org/doc/tutorial/call-module-code)

This
![go_issue](https://user-images.githubusercontent.com/42895532/113295018-8d46d280-92ef-11eb-880a-c974523225d3.PNG)

should be this: go mod edit -replace  example.com/greetings=../greetings

**Comment by AlexRouSg** [comment]
This is a powershell bug. 
The issue for changing the doc is #44924

**Comment by ColeDrain** [comment]
Oops... My bad. Thanks for your reply.
