### ISSUE TITLE
uncorrect GOPATCH

### ISSUE THREAD

**Issue by GrNikolay** [golang/go#45330]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.16.2 windows/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Admin\AppData\Local\go-build
set GOENV=C:\Users\Admin\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Admin\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Admin\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.2
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0

</pre></details>

### What did you do?
```
package main

import (
	"database/sql"
	"fmt"

	_ "github.com/go-sql-driver/mysql"
)

func main() {
	db, err := sql.Open("mysql", "mysql:mysql@tcp(127.0.0.1:3306)/goland")
	if err != nil {
		panic(err)
	}

	defer db.Close()

	fmt.Println("Подключено к MySQL")

}
```

**Console:**
```
go get -u github.com/go-sql-driver/mysql
go run main.go

```

### What did you expect to see?

```
"Подключено к MySQL"
```

### What did you see instead?

```
{
	"resource": "/D:/goland/mysql/main.go",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "BrokenImport",
		"target": {
			"$mid": 1,
			"external": "https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#BrokenImport",
			"path": "/golang.org/x/tools/internal/typesinternal",
			"scheme": "https",
			"authority": "pkg.go.dev",
			"fragment": "BrokenImport"
		}
	},
	"severity": 8,
	"message": "could not import github.com/go-sql-driver/mysql (cannot find package \"github.com/go-sql-driver/mysql\" in any of \n\tC:\\Program Files\\Go\\src\\github.com\\go-sql-driver\\mysql (from $GOROOT)\n\tC\\src\\github.com\\go-sql-driver\\mysql (from $GOPATH)\n\t\\Users\\Admin\\go\\src\\github.com\\go-sql-driver\\mysql (from $GOPATH))",
	"source": "compiler",
	"startLineNumber": 7,
	"startColumn": 4,
	"endLineNumber": 7,
	"endColumn": 18
}
```

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by GrNikolay** [comment]
> 
> 
> Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.
> 
> For questions please refer to https://github.com/golang/go/wiki/Questions


**I think that the problem here is not in the git. Import problem.** 


could not import github.com/go-sql-driver/mysql (cannot find package "github.com/go-sql-driver/mysql" in any of 
	C:\Program Files\Go\src\github.com\go-sql-driver\mysql (from $GOROOT)
	C\src\github.com\go-sql-driver\mysql (from $GOPATH)
	\Users\Admin\go\src\github.com\go-sql-driver\mysql (from $GOPATH))compilerBrokenImport
