### ISSUE TITLE
x/website: The StderrPipe example refers to "io.ReadAll"

### ISSUE THREAD

**Issue by danhigham** [golang/go#45348]
https://golang.org/pkg/os/exec/#Cmd.StderrPipe

The StderrPipe example has an error in it. It refers to "io.ReadAll" and it should be "ioutil.ReadAll" from io/ioutil package.

**Comment by nemith** [comment]
`io.ReadAll` was added in Go 1.16 and replaced ioutil with the ioutil being deprecated.  

https://golang.org/pkg/io/ioutil/#ReadAll

>  As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.

**Comment by nemith** [comment]
See https://golang.org/doc/go1.16#ioutil

**Comment by ianlancetaylor** [comment]
Working as intended.

**Comment by danhigham** [comment]
Ah, fair enough. I'll get my coat!
