### ISSUE TITLE
x/pkgsite: remove packages git.goodev.de/logol/*

### ISSUE THREAD

**Issue by john-gold** [golang/go#45343]
### What is the URL of the page with the issue?

- https://pkg.go.dev/git.goodev.de/logol/sorm/orm
- https://pkg.go.dev/git.goodev.de/logol/sorm/orm/ormerror
- https://pkg.go.dev/git.goodev.de/logol/mailer

### What did you do?

- Deleted repositories
- Opened pkg.go.dev pages in the browser

### What did you expect to see?

Nothing, since the packages don't exist anymore

### What did you see instead?

Documentation pages for the mentioned packages

**Comment by jamalc** [comment]
Done.
