### ISSUE TITLE
mutex

### ISSUE THREAD

**Issue by pzs-pzs** [golang/go#45351]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
no

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/puzhengsong/Library/Caches/go-build"
GOENV="/Users/puzhengsong/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="*.xiaoduoai.com,*.xiaoduotech.com"
GONOSUMDB="*.xiaoduoai.com,*.xiaoduotech.com"
GOOS="darwin"
GOPATH="/Users/puzhengsong/go"
GOPRIVATE="*.xiaoduoai.com,*.xiaoduotech.com"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2y/drl9zw754xz3cjww8t4_jb7c0000gn/T/go-build741237267=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

in mutex.go 
https://github.com/golang/go/blob/97b3ce430bb64fb6c8dfb244d400468932f2e984/src/sync/mutex.go#L207
`
if old>>mutexWaiterShift == 0 || old&(mutexLocked|mutexWoken|mutexStarving) != 0 {
				return
			}
`
can old&(mutexLocked|mutexWoken|mutexStarving) != 0 ==> old&mutexWoken != 0?

because the mutexLocked and mutexStarving is always 0 bit

**Comment by seankhliao** [comment]
The state of `old` can change in further iterations of the loop

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
