### ISSUE TITLE
x/pkgsite: remove packages github.com/craftslab/godiff/diff

### ISSUE THREAD

**Issue by craftslab** [golang/go#45367]
### What is the URL of the page with the issue?
 
- https://pkg.go.dev/github.com/craftslab/godiff/diff

### What did you do?
 
Opened pkg.go.dev pages in the browser

### What did you expect to see?

Nothing, since the packages don't exist anymore

### What did you see instead?

Documentation pages for the mentioned packages

**Comment by jba** [comment]
Done.
