### ISSUE TITLE
x/exp/cmd/gorelease: failing to build all of a sudden

### ISSUE THREAD

**Issue by jadekler** [golang/go#45362]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Not sure.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/deklerk/.cache/go-build"
GOENV="/home/deklerk/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/deklerk/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/deklerk/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/google-golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/google-golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/home/deklerk/workspace/exp/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1600608816=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
$ go build .
gorelease.go:100:2: no required module provides package golang.org/x/mod/modfile; to add it:
	go get golang.org/x/mod/modfile
errors.go:14:2: no required module provides package golang.org/x/mod/module; to add it:
	go get golang.org/x/mod/module
gorelease.go:103:2: no required module provides package golang.org/x/mod/zip; to add it:
	go get golang.org/x/mod/zip
```

### What did you expect to see?

No errors.

### What did you see instead?

Errors

-----------------

Seemed to happen all of a sudden about ~5m ago. I imagine some package was yanked or something?

**Comment by jadekler** [comment]
Per https://go-review.googlesource.com/c/exp/+/307069, a `go mod tidy` picks up a new version of a dep and it fixes the issue.

**Comment by dmitshur** [comment]
I can't reproduce this with Go 1.16.3. Are you sure there aren't local changes causing it? Does `git status` show a clean working directory? What about `git clean -dx --dry-run`?

**Comment by jadekler** [comment]
I'm thinking my module cache was borked somehow. :( I'll close this for now and re-open if I observe this again. Apologies for taking of your time!
