### ISSUE TITLE
Returned `reflect.Value` from `reflect.(Value).FieldByNameFunc` does not contain `json tag` for nested object

### ISSUE THREAD

**Issue by khanhtc1202** [golang/go#45365]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, on the latest go v1.16.3

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/s12228/Library/Caches/go-build"
GOENV="/Users/s12228/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/s12228/workspace/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/s12228/workspace/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0n/r_1ykvdj5vq092hj8qzt79d42q187t/T/go-build532364237=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```golang
type example struct {
    Obj example1 `json:"obj"`
}

type example1 struct {
    Name string `json:"name"`
}

...

nestedObj, ok := reflect.ValueOf(obj).Type().FieldByNameFunc(func(name string) bool {
	return name == cur
})
```

go playground: https://play.golang.org/p/ah2ujSwNoF5

### What did you expect to see?

For top-level fields of the above example struct, I could get the JSON tag name as expected, using `reflect.(Value).FieldByNameFunc`
```console
extracted: {Obj  main.example1 json:"obj" 64 [5] false} | tag name: obj
```

When iterating to deeper nested structs (`example1` in the above sample), expect to get JSON tag name for nested struct field
```console
extracted: {Name  string json:"name" 0 [0] false} | tag name: name
``` 

### What did you see instead?
But, the JSON tag name is emitted for nested structs currently

```console
extracted: {Name  string  0 [0] false} | tag name: 
```

**Comment by seankhliao** [comment]
you're passing an instance of `relfect.StructField` to `buildJsonPath` where it expects an instance of the field/struct.

For questions please refer to https://github.com/golang/go/wiki/Questions
