### ISSUE TITLE
Why checking for fewer than 6 parts in os/user/lookup_unix.go?

### ISSUE THREAD

**Issue by tkaehn** [golang/go#45371]
Why checking for fewer than six parts when skipping lines with fewer than 6 colons before?
Why double checking at all?

In contrast to this /etc/group is checked for 3 colons and 4 parts.

https://github.com/golang/go/blob/6986c02d72db6806a46406ef398aa10f26018c20/src/os/user/lookup_unix.go#L158

https://github.com/golang/go/blob/6986c02d72db6806a46406ef398aa10f26018c20/src/os/user/lookup_unix.go#L163

**Comment by AlexRouSg** [comment]
Because you can have 6 colons and less than 6 parts.
e.g. `kevin::1005:1006::/home/kevin:/usr/bin/zsh`

For questions please see https://github.com/golang/go/wiki/Questions

**Comment by mdlayher** [comment]
See above, closing.

**Comment by tkaehn** [comment]
This is not correct. Your example yields 7 parts as well:

```
package main

import (
        "bytes"
        "fmt"
        "strings"
)

func main() {
        colon := []byte(":")

        line := []byte("kevin::1005:1006::/home/kevin:/usr/bin/zsh")

        parts := strings.SplitN(string(line), ":", 7)

        fmt.Println(bytes.Count(line, colon) < 6, len(parts), parts)
}
```
```
$ go run .
false 7 [kevin  1005 1006  /home/kevin /usr/bin/zsh]
```

**Comment by AlexRouSg** [comment]
oops my bad, I remembered `SplitN` wrong

**Comment by ianlancetaylor** [comment]
The code is likely redundant.  Want to send a fix?
