### ISSUE TITLE
cmd/compile: CL 305829 broke plan9/amd64 build

### ISSUE THREAD

**Issue by fhs** [golang/go#45372]
After CL 305829 (commit 3300390ec70c6b8e2392e4ab32342d426e2d3532), the plan9/amd64 builder has been failing with this:
```
Building Go toolchain2 using go_bootstrap and Go toolchain1.
runtime: bad pointer in frame cmd/go/internal/load.loadImport at 0x281eec90: 0x2
fatal error: invalid pointer found on stack
```
See https://build.golang.org/log/62148fe37ac833f3b20c10296797908bca7a356c

It builds fine on my machine after I reverted the change.

CC @0intro 

@gopherbot add labels OS-Plan9, NeedsFix

**Comment by fhs** [comment]
CC @thanm

**Comment by thanm** [comment]
Thanks. 

The change in question seems fairly benign (since according to the Go ABI0 calling convention, any scratch register can be used in such situations).

Is there a plan9 expert who could advise me as to whether there this might be breaking some sort of Plan9 rule regarding register use?

**Comment by fhs** [comment]
CC @millerresearch

**Comment by millerresearch** [comment]
> CC @millerresearch

Sorry, amd64 is outside my zone of expertise. I wonder if there is anything in the _amd64.s files in the runtime which is touching that register?

**Comment by thanm** [comment]
>I wonder if there is anything in the _amd64.s files in the runtime which is touching that register?

That was the first thing I looked for.  Can't see anything specific to plan9 there. 

I'll poke around some more.

**Comment by thanm** [comment]
I can't seem to create a gomote to work on this problem -- maybe something is wrong with the builder?

Output from gomote create:

```
$ gomote create plan9-amd64-9front
# host type "host-plan9-amd64-0intro" is not elastic; 0 of 1 machines connected, 0 busy
# still creating plan9-amd64-9front after 5s; 0 requests ahead of you
# still creating plan9-amd64-9front after 10s; 0 requests ahead of you
...
# still creating plan9-amd64-9front after 15m50s; 0 requests ahead of you
# still creating plan9-amd64-9front after 15m55s; 0 requests ahead of you
# still creating plan9-amd64-9front after 16m0s; 0 requests ahead of you
```

Scheduler state doesn't seem to show anything else running:
![Screenshot from 2021-04-05 08-54-56](https://user-images.githubusercontent.com/12280172/113576348-6b01cd00-95ed-11eb-8434-fa2905c3a997.png)


@0intro, is this something you can help with?  It is unlikely I'll be able to investigate this problem if I can't triage it via gomote/builder.

**Comment by 0intro** [comment]
> I can't seem to create a gomote to work on this problem -- maybe something is wrong with the builder?

It should be fixed now. Please try again.

**Comment by thanm** [comment]
Thanks, yes, "gomote create" seems to have worked now. 

How exactly do we run "make.bash" on our plan9 builders?  I can't seem to see a copy of bash in any of the usual places (/bin/bash, /usr/local/bin/bash, etc). Thanks.

**Comment by 0intro** [comment]
> How exactly do we run "make.bash" on our plan9 builders? I can't seem to see a copy of bash in any of the usual places (/bin/bash, /usr/local/bin/bash, etc). Thanks.

On Plan 9, it's called `make.rc`.

**Comment by millerresearch** [comment]
I fired up a copy of 9legacy 9k flavour of Plan 9 on an amd64 machine and I see the same error. So it's not specific to 9front.

**Comment by 0intro** [comment]
The builder was historically called `9front`, because it used to run 9front during a year approximately, but it has been running 9legacy 9k since October 2015.

**Comment by millerresearch** [comment]
> has been running 9legacy 9k since October 2015.

Maybe time to rename it then?

**Comment by 0intro** [comment]
> Maybe time to rename it then?

Sure. I've just sent [CL 307409](golang.org/cl/307409).

**Comment by thanm** [comment]
plan9-amd64 builder seems to be hung on trybot/slowbot run... currently at 2 hours 21 mins. Maybe some sort of machine problem? Does it need to be rebooted?

![Screenshot from 2021-04-06 18-55-10](https://user-images.githubusercontent.com/12280172/113788095-494a3800-970a-11eb-8dea-e2fc84983568.png)

**Comment by 0intro** [comment]
It should be fixed now.

**Comment by thanm** [comment]
Thanks.
