### ISSUE TITLE
x/playground: unable to access shared playground link from Japanese IP

### ISSUE THREAD

**Issue by stt106** [golang/go#45378]
In order to access playground (and other things) I have been using a stable VPN service. Everything works fine with the playground until recently, while I can still access the site and run code with it, I can't share any code as there is no 'Share' button. This is not ideal but workable. What's not workable is I can't access shared playground link from others, such as https://play.golang.org/p/miQ92qs08j- and my current IP is 138.199.39.209 which is located in Japan.
It says: **Viewing and/or sharing code snippets is not available in your country for legal reasons. This message might also appear if your country is misdetected.** 

I wonder how does playground location detection works as when using a VPN I would have thought it shall detect my location based on connected vpn server location rather than my physical location. 
Playground is key in sharing small code snippet and it would be a shame to lose access.

**Comment by ALTree** [comment]
Another ipblock issue as in  #45246?

cc @golang/osp-team (but really this is an internal google issue)
