### ISSUE TITLE
bufio: make zero value of Reader useful

### ISSUE THREAD

**Issue by dsnet** [golang/go#45374]
Consider the following code pattern:
```go
var br bufio.Reader
for _, r := range readers {
    br.Reset(r)
    ... // make use of br
}
```

Currently, this pattern results in an infinite loop since the internal buffer of `bufio.Reader` is empty (resulting in no progress being made). The `bufio.Reader.Reset` method should initialize the internal buffer with `defaultBufSize` if it is empty.

**Comment by opennota** [comment]
> this pattern results in an infinite loop

How so? The program below doesn't hang.

```
package main

import (
	"bufio"
	"io"
	"os"
	"strings"
)

func main() {
	var br bufio.Reader
	readers := []io.Reader{strings.NewReader("data\n")}
	for _, r := range readers {
		br.Reset(r)
		io.Copy(os.Stdout, &br)
	}
}
```

**Comment by dsnet** [comment]
Interesting, this program does hang:
```go
package main

import (
	"bufio"
	"io"
	"strings"
)

func main() {
	var br bufio.Reader
	readers := []io.Reader{strings.NewReader("data\n")}
	for _, r := range readers {
		br.Reset(r)
		br.ReadBytes('\n')
	}
}
```

**Comment by aakturk** [comment]
> > this pattern results in an infinite loop
> 
> How so? The program below doesn't hang.

It does not hang, when calling io.Copy. Because io.Copy calls src.Read, bufio.Reader.Read here, and in turn, bufio.Reader.Read calls the internal reader's Read function when buffer is empty.

**Comment by aakturk** [comment]
Isn't it OK just doing this:

```go
func (b *Reader) Reset(r io.Reader) {
        // add this if statement
	if len(b.buf) < minReadBufferSize {
		b.buf = make([]byte, minReadBufferSize)
	}
	b.reset(b.buf, r)
}
```

**Comment by yunnian** [comment]
> ```go
> minReadBufferSize
> ```

This will not save memory

**Comment by yunnian** [comment]
> Isn't it OK just doing this:
> 
> ```go
> func (b *Reader) Reset(r io.Reader) {
>         // add this if statement
> 	if len(b.buf) < minReadBufferSize {
> 		b.buf = make([]byte, minReadBufferSize)
> 	}
> 	b.reset(b.buf, r)
> }
> ```

This will not save memory

**Comment by dsnet** [comment]
> Isn't it OK just doing this:

Yea, that's more or less what's proposed with saying "`bufio.Reader.Reset` method should initialize the internal buffer with `defaultBufSize` if it is empty."

> This will not save memory

I'm not sure what you're getting at. This issue isn't about saving memory, but making the zero value of `bufio.Reader` useful.
