### ISSUE TITLE
x/pkgsite: Remove packages github.com/palchukovsky/ss-go/*

### ISSUE THREAD

**Issue by palchukovsky** [golang/go#45382]
### What is the URL of the page with the issue?
 https://pkg.go.dev/search?page=2&q=palchukovsky%2Fss-go%2F%2A
 
### What did you do?
Many packages github.com/palchukovsky/ss-go/* were created by automation error and were added to the proxy cache.

It creates many errors "ambiguous import" in module dependency tree.

Now modules have removed from repository, but not from the cache.
 
### What did you expect to see?
All modules with path  github.com/palchukovsky/ss-go/* except github.com/palchukovsky/ss-go is removed from the proxy.

**Comment by jba** [comment]
Unfortunately we can't remove `github.com/palchukovsky/ss-go/*` without also removing `github.com/palchukovsky/ss-go`.

I will remove the following:
```
github.com/palchukovsky/ss-go/api
github.com/palchukovsky/ss-go/lambda
github.com/palchukovsky/ss-go/lib
```
Those paths and anything under them will be removed, and no new packages with those paths as a prefix will be allowed. However, a new package like `github.com/palchukovsky/ss-go/foo` will be allowed.

**Comment by jba** [comment]
Done.

**Comment by palchukovsky** [comment]
Thank you! But - is it possible to remove the whole github.com/palchukovsky/ss-go from the cache (and all sub-pathes) and then allow work with it from the scratch, without any disallowing for future naming?

**Comment by jba** [comment]
The short answer is no. We could of course remove things from our database, but the problem is that our database is designed to be a reflection of the Go module proxy. Sometimes we reprocess all or some of our data from the proxy, so we'd encounter your packages again and add them again. That is why we keep a prefix-based list of exclusions that is always in force.
