### ISSUE TITLE
testing/fstest TestFS rejects an FS that can read file.txt and /file.txt interchangeably

### ISSUE THREAD

**Issue by packrat386** [golang/go#45397]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2488690620=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I implemented an `io.FS` that was capable of opening both `file.txt` and `/file.txt` interchangeably, and then I ran `fstest.TestFS` against it. A concise reproduction can be found here: https://github.com/packrat386/fstest_repro.

### What did you expect to see?

I expected `fstest.TestFS` not to return an error.

### What did you see instead?

`file.txt: Open(/file.txt) succeeded, want error`

----------

In particular this issue came up because I was implementing and `io.FS` where the "working directory" is `/`, so `myFS.Open("file.txt")` and `myFS.Open("/file.txt")` are opening the same file. I'd like to be able to us `fstest.TestFS` to test my implementation, but doing so requires denying `myFS.Open("/file.txt")` even though it makes sense in context.

In general [checkBadPath](https://github.com/golang/go/blob/master/src/testing/fstest/testfs.go#L582-L613) within `fstest.TestFS`  seems like it's requirements are very pedantic (for exmaple, `os.Open("./.")` works just fine on my current machine). I don't really know enough about filepaths to say that the other ones should work or not.

**Comment by packrat386** [comment]
Also if this is in fact not desired behaviour I'd be happy to submit a pull request to fix it.

**Comment by seankhliao** [comment]
note `io/fs.FS.Open` says:

> 	// Open should reject attempts to open names that do not satisfy
>	// ValidPath(name), returning a *PathError with Err set to
>	// ErrInvalid or ErrNotExist.

and `io/fs.ValidPath` says:

> Path names passed to open are UTF-8-encoded, unrooted,...
> ... Paths must not start or end with a slash: “/x” and “x/” are invalid.

**Comment by packrat386** [comment]
I see. In that case I'll close this. Thanks.
