### ISSUE TITLE
flag: use strings.Builder instead of concatenating strings

### ISSUE THREAD

**Issue by jamespfennell** [golang/go#45392]
There is a single function in the flag package whose implementation uses string concatenation instead of the recommended strings.Builder. The function was last touched before strings.Builder was introduced in Go 1.10, which explains the old style code.

I am about to propose a PR to migrate the function to strings.Builder; filing this for tracking purposes.

**Comment by ianlancetaylor** [comment]
Note that it's not necessary to file an issue for a change that does not affect anything user visible.  It's OK to just send the change.  But filing an issue is OK too.  Thanks.
