### ISSUE TITLE
x/tools/gopls: high memory consumption

### ISSUE THREAD

**Issue by EgorRzh** [golang/go#45404]
### What version of Go are you using (`go version`)?
1.16
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 20.04
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/egor/.cache/go-build"
GOENV="/home/egor/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/egor/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/egor/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build638460739=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
I'am starting VSCode with installed Go extension. And gopls process use all memory (24Gb)

### Attached file with gopls logs
[gopls.9316-14GiB-nonames.zip](https://github.com/golang/go/files/6264210/gopls.9316-14GiB-nonames.zip)

**Comment by stamblerre** [comment]
Thank you for filing this issue and attaching the memory zip. Based on the heap profile, we think that a package in your workspace might have really large byte slice literals, which are known to take up a lot of memory in the type checker. Is that possible? You can look at the heap profile with package names to identify which package that might be.
