### ISSUE TITLE
os: TestErrIsNotExist in error_test.go is not robust

### ISSUE THREAD

**Issue by perillo** [golang/go#45407]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64
</pre>

In the `testErrNotExist` function, the code calls `os.Chdir` expecting to fail, but does not restore the original working directory in the case where it does not fail.  The following code however assumes that `os.Chdir` may not fail.

**Comment by gh4n** [comment]
Had a go at fixing this, would appreciate any/all feedback
