### ISSUE TITLE
Go for Windows x86 MSI version 1.15.3 is detected as malware by Windows Defender.

### ISSUE THREAD

**Issue by jedieaston** [golang/go#45415]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.15.3
</pre>

### Does this issue reproduce with the latest release?
No.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
Windows 10 (x86). I can't install Go to get the correct output due to the aforementioned bug.

</pre></details>

### What did you do?

1. Downloaded the Go 1.15.3 installer for Windows x86 from https://golang.org/dl/.
2. Verified the SHA256 hash matched what the site said (it did!)
3. Scanned the MSI with Windows Defender.

### What did you expect to see?

No threats detected.

### What did you see instead?

Apparently, Windows thinks that Go is `Trojan:Win32/CryptInject!MSR` in disguise. I've been trying to add the past releases of Go to WinGet (now that there is multiarch support), but I can't add this one, since it appears as a virus to Windows. I would've sent this to security@golang.org, but it's not a security issue I don't think, it's just that there's a false positive for Defender that the people with the developer certificates need to handle. (apparently. the form said it would be prioritized if the developer put it in). 

(If I need to send it to that email address, please feel free to close this. I could've gone either way).

Screenshot to prove I'm not telling a fib:

<img width="928" alt="image" src="https://user-images.githubusercontent.com/21368066/113796785-a8fa1080-9715-11eb-99a9-8061dfcc3927.png">

**Comment by jedieaston** [comment]
[VirusTotal](https://www.virustotal.com/gui/file/798adfac0c33df7b7e975438d356f87cf4eef6e17769b8d27c90ea1ebe9b8802/detection)

**Comment by seankhliao** [comment]
Please file with your antiivirus vendor

https://golang.org/doc/faq#virus
