### ISSUE TITLE
runtime/cgo: document Handle better

### ISSUE THREAD

**Issue by ainar-g** [golang/go#45427]
[CL 295369] (issue #37033) added the new type [`runtime/cgo.Handle`].  The documentation currently says:

> Handle provides a safe representation of Go values to pass between Go and C.  The zero value of a handle is not a valid handle, and thus is safe to use as a sentinel in C APIs.

But it doesn't mention what it means by an “unsafe” value.  I *assume* that what it means is a reference to the “[Passing pointers]” section of the `cgo` documentation, but the example code that the package currently provides simply passes a \[pointer to an] integer between Go and C.

I think that the code should be replaced with something better documented and closer to real-world scenarios, and also that perhaps direct links to the `cgo` documentation about which values are typically unsafe should be added.

[CL 295369]:            https://go-review.googlesource.com/c/go/+/295369
[Passing pointers]:     https://tip.golang.org/cmd/cgo/#hdr-Passing_pointers
[`runtime/cgo.Handle`]: https://tip.golang.org/pkg/runtime/cgo/#Handle

**Comment by dmitshur** [comment]
CC @oakad, @changkun, @ianlancetaylor.

**Comment by ianlancetaylor** [comment]
@ainar-g Please comment on https://golang.org/cl/308230.  Thanks.
