### ISSUE TITLE
x/blog: Recursive link on Developer Survey Results 2020

### ISSUE THREAD

**Issue by dtchanpura** [golang/go#45425]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.10 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Not Applicable

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
...
GOARCH="amd64"
GOOS="darwin"
...
</pre></details>

### What did you do?

Opened the link https://blog.golang.org/survey2020-results. Reached out to line after Thank you line.

> In 2020, we had another great turnout with 9,648 responses, about [as many as 2019](https://blog.golang.org/survey2020-results). Thank you for putting in the time to provide the community with these insights on your experiences using Go!

The link claims to compare with 2019 Results but the link instead leads to the same URL.

### What did you expect to see?

The link should be https://blog.golang.org/survey2019-results.

### What did you see instead?

The link is https://blog.golang.org/survey2020-results.

**Comment by qmuntal** [comment]
This has already been fixed in https://github.com/golang/blog/commit/67340572e3cf3e14f1eb1015d219b79598567143 but still not deployed.

**Comment by dtchanpura** [comment]
Oh sorry, didn't see it there.

**Comment by dmitshur** [comment]
Thanks @dtchanpura and @qmuntal. The latest x/blog commit has been deployed now, so I'll close this.
