### ISSUE TITLE
x/pkgsite: detects full text of GPL3 licenses as both GPL3 and GPL2

### ISSUE THREAD

**Issue by heschi** [golang/go#45432]
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/netdata/go.d.plugin, but this is just an example.
  
### What did you do?

Looked at the licenses for this module, which contains (I think) a verbatim copy of the GPL3 page at https://www.gnu.org/licenses/gpl-3.0.en.html. 
 
### What did you expect to see?
 
GPL3.
 
### What did you see instead?

GPL3 and GPL2.

@julieqiu showed me the license detector information for the module, which at a glance suggests that it's detecting the text in the "How to apply these terms to your software" section as GPL2, despite the rather critical "version 3" in it.

**Comment by jba** [comment]
I fixed the problem and updated our database.
