### ISSUE TITLE
x/website: missing `"` in code snippet

### ISSUE THREAD

**Issue by sko00o** [golang/go#45439]
### What version of Go are you using (`go version`)?

<pre>
$ go version
# Doesn't matter.
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
# Doesn't matter.
</pre></details>

### What did you do?

Find typo when reading reference.

https://golang.org/ref/mod#environment-variables

![image](https://user-images.githubusercontent.com/8807977/113972037-83334f80-986c-11eb-9e97-25277273fec1.png)

### What did you expect to see?

```
GOSUMDB="sum.golang.org+<publickey> https://sum.golang.org"
```

**Comment by ALTree** [comment]
cc @jayconrod
