### ISSUE TITLE
sys/windows/registry will not build go.mod file not found in current directory or any parent directory

### ISSUE THREAD

**Issue by chrisjd20** [golang/go#45446]
I cannot build or use sys windows registry:

``` go
import (
	"golang.org/x/sys/windows/registry"
)
```

``` powershell 
PS D:\go_http_web_service> go build .\http.go
http.go:24:2: no required module provides package golang.org/x/sys/windows/registry: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

### Version

<pre>
go version go1.16.3 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\chris\AppData\Local\go-build
set GOENV=C:\Users\chris\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\chris\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\chris\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\chris\AppData\Local\Temp\go-build3911830538=/tmp/go-build -gno-record-gcc-switches
</pre></details>

**Comment by AlexRouSg** [comment]
The message `go.mod file not found in current directory or any parent directory; see 'go help modules'` means that your project does not have a `go.mod` file. As of `1.16` modules is enabled by default so you would have to run `go mod init github.com/username/reponame` first followed by `go get .`

**Comment by chrisjd20** [comment]
Oh ok, I'll verify and then close. Thanks trying it out here shortly.

**Comment by chrisjd20** [comment]
Ok I guess I have no idea what im doing @AlexRouSg 

``` go
import (
	"golang.org/x/sys/windows/registry"
)
```
``` powershell
PS C:\Users\chris\go> go mod init golang.org/x/sys
go: creating new go.mod: module golang.org/x/sys
go: to add module requirements and sums:
        go mod tidy
PS C:\Users\chris\go> go mod tidy
$GOPATH/go.mod exists but should not
PS C:\Users\chris\go> go get golang.org/x/sys
$GOPATH/go.mod exists but should not
PS C:\Users\chris\go>
```

**Comment by chrisjd20** [comment]
```
PS C:\Users\chris> go mod init golang.org/x/sys
go: creating new go.mod: module golang.org/x/sys
go: to add module requirements and sums:
        go mod tidy
PS C:\Users\chris> go get golang.org/x/sys
go get golang.org/x/sys: unrecognized import path "golang.org/x": parse https://golang.org/x?go-get=1: no go-import meta tags ()
```

**Comment by AlexRouSg** [comment]
This should help https://golang.org/doc/tutorial/getting-started
You should not be running `go mod init` at `%USERPROFILE%/go` as the message says.
You should be running it inside your project folder, if your project folder is `%USERPROFILE%/go` then you have to move it.
Delete `%USERPROFILE%/go/go.mod` then make a new folder e.g. `%USERPROFILE%/myproject`, then add your source code, then run `cd %USERPROFILE%/myproject` then `go mod init github.com/yourusername/myproject`

**Comment by chrisjd20** [comment]
Ok, thanks.

**Comment by chrisjd20** [comment]
Figured it out. Was just that I'm a go-newb

``` go 
package main
import (
	"golang.org/x/sys/windows/registry"
)
```

``` 
go mod init go_http_web_service
go get golang.org/x/sys/windows/registry
go build .\http.go
```
