### ISSUE TITLE
-pkgdir flag ignored with 1.16

### ISSUE THREAD

**Issue by lazyhacker** [golang/go#45459]
When using the go 1.16 command (e.g. go get) with the -pkgdir flag, it seems like the flag is ignored and downloaded packages always gets installed into the default mod location.

### What version of Go are you using (`go version`)?

<pre>
go version go1.16.3 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xyz/.cache/go-build"
GOENV="/home/xyz/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/xyz/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xyz/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1374152825=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

go get -pkgdir /home/xyz/tmp fyne.io/fyne/v2

### What did you expect to see?

The downloaded packages would be in /home/xyz/tmp

### What did you see instead?

The download packages was installed in $GOPATH/pkg/mod

**Comment by seankhliao** [comment]
This is the expected behavior in module mode, from `go help install`:

> When module-aware mode is disabled, other packages are installed in the
> directory $GOPATH/pkg/$GOOS_$GOARCH. When module-aware mode is enabled,
> other packages are built and cached but not installed.

**Comment by lazyhacker** [comment]
What I'm seeing is that the modules are being downloaded except that instead of downloading to what is set by -pkgdir, it is always going into the default.

**Comment by seankhliao** [comment]
`-pkgdir` is a flag for build not get, module cache location is controlled by `GOMODCACHE`

**Comment by lazyhacker** [comment]
Thanks for the explanation!  

It was a little big confusing since the documentation says

   `The build flags are shared by the build, clean, get, install, list, run, and test commands`

I should have mentioned that I tried with `go build` as well:

```
git clone https://github.com/fyne-io/fyne
cd fyne/cmd/fyne
go build -pkg /tmp
```

Go will download the following into `$GOPATH/pkg/mod/...` rather then `/tmp` as specified by -pkgdir:

```
go: downloading github.com/lucor/goinfo v0.0.0-20200401173949-526b5363a13a
go: downloading github.com/Kodeworks/golang-image-ico v0.0.0-20141118225523-73f0f4cfade9
go: downloading github.com/jackmordaunt/icns v0.0.0-20181231085925-4f16af745526
go: downloading github.com/josephspurrier/goversioninfo v0.0.0-20200309025242-14b0ab84c6ca
go: downloading github.com/pkg/errors v0.9.1
go: downloading golang.org/x/mod v0.2.0
go: downloading golang.org/x/tools v0.0.0-20200328031815-3db5fc6bac03
go: downloading github.com/nfnt/resize v0.0.0-20180221191011-83c6a9932646
go: downloading github.com/akavel/rsrc v0.8.0
go: downloading golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
```

To do what I need would be to:

`GOMODCACHE=/tmp go build`

which is what I thought the -pkgdir flag was meant for:

```
install and load all packages from dir instead of the usual locations.
	For example, when building with a non-standard configuration,
	use -pkgdir to keep generated packages in a separate location.
```
So -pkgdir is only for the packages that is generated from the build and not the dependency modules.
