### ISSUE TITLE
cmd/go: TestScript/mod_list_update_nolatest broken on Windows builders

### ISSUE THREAD

**Issue by findleyr** [golang/go#45456]
Sample failure: https://build.golang.org/log/9511e1500ca6d9c44f2abaa8a9630d0e3ad41999

Judging from build.golang.org, failures appear to start at https://golang.org/cl/306572.

CC @jayconrod @bcmills @matloob

**Comment by jayconrod** [comment]
Ack. Looks like a bug in the test. I'll try and fix it forward.
