### ISSUE TITLE
file run in freebsd

### ISSUE THREAD

**Issue by wike2019** [golang/go#45464]
the main can not run in freefsd os ,the pictures is the info about os and app info

![image](https://user-images.githubusercontent.com/5925704/114129842-f2bf4280-9931-11eb-98f8-661b6f8a3389.png)
![image](https://user-images.githubusercontent.com/5925704/114129871-023e8b80-9932-11eb-8f34-356f86c6da3b.png)

**Comment by davecheney** [comment]
@wike2019 please open an new issue and complete the entire template. Thank you.
