### ISSUE TITLE
net/http: Request.Form field data may include HTML entities

### ISSUE THREAD

**Issue by adonovan** [golang/go#45479]
I'm no HTTP expert, so this could be working as intended, but I notice that when an HTML form is posted, the document's encoding is also used to encode the form data. So, if the document is Latin-1, and a text field contains "😃", which cannot be represented as Latin-1, then the client (Chrome, in my case) produces a URL `?f=%26%23128515%3B`, which is the URL-encoding of `"&#128515;"`, which is the HTML entity reference for U+1f603, a smiley face.

Is Chrome's behavior, of using an HTML entity reference `&#...;` when the form encoding cannot express the form data,
(a) normal for a client, or
(b) Chrome attempting to fail gracefully when asked to do the impossible?

If (a), are servers expected to handle HTML entity references in form data? I could see no mention of this expectation in the net/http package code or docs. I also can't see how a server could distinguish a Chrome-introduced HTML entity reference from a form that literally contained that sequence, which makes me think (a) is not the answer.
If (b) , is the usual advice "don't let that happen", in other words, make sure the HTML document's encoding is explicitly set to something like UTF-8?

A word of documentation in net/http might help. StackOverflow and the usual sources were surprisingly unhelpful.

**Comment by dmitshur** [comment]
CC @bradfitz, @neild, @empijei.

**Comment by empijei** [comment]
The HTTP form fields transport features are completely HTML agnostic. The HTTP spec never mentions such a feature as far as I know.

Here Go is just parsing the HTTP and relaying the information to the user code, which (if they want to support it) has to then decode this bit too (which I would advise against for security reasons).

My suggestion would be to not let it happen: always make sure you're using utf-8. Note that the stdlib always tries to do this when it has the power to choose. Moreover I'd suggest to not try to decode anything that comes from the client that might have been weirdly encoded. Either have some JS on the client (or the browser itself) that applies a well defined encoding or just reject anything you don't recognize.

On the documentation side of things: Go has an implementation of the HTTP spec, which doesn't meddle with HTML entity encoding in any way, so I'm not sure about adding a doc line about this. I fear it might create more confusion than solving issues.

**Comment by adonovan** [comment]
OK, thanks for explaining. In that case I'll close this as: net/http working as intended, Chrome working under impossible constraints.
