### ISSUE TITLE
x/tools/gopls: ~ in front of package declaration does not show an error

### ISSUE THREAD

**Issue by heschi** [golang/go#45478]
If I put a ~ in front of the package declaration of a file, gopls gets very slow, but doesn't report an error that the ~ is invalid syntax. I haven't investigated yet, but it feels like the `packages.Load` goes sideways and the file is removed from the package, causing lots of errors in other files about missing declarations. And then since the file isn't in a package, we don't diagnose it any more, perhaps.

**Comment by findleyr** [comment]
This doesn't seem to be a problem anymore, perhaps because of recent fixes to metadata invalidation.
