### ISSUE TITLE
x/pkgsite: remove tcw.im/ufc and tcw.im/ufc/redigo

### ISSUE THREAD

**Issue by staugur** [golang/go#45487]
### What is the URL of the page with the issue?
 
As per instructions at [https://go.dev/about](https://go.dev/about) for removing a package: please remove
[https://pkg.go.dev/tcw.im/ufc](https://pkg.go.dev/tcw.im/ufc) and [https://pkg.go.dev/tcw.im/ufc/redigo](https://pkg.go.dev/tcw.im/ufc/redigo)

This is my toolkit, but the submodules always use the old version in "go get", so I request to delete them to see if it can be resolved.

Thank you.

**Comment by jba** [comment]
If we remove tcw.im/ufc we'll remove everything under that (every path which has that as the prefix). Is that OK?

**Comment by staugur** [comment]
Of course!

**Comment by jba** [comment]
Done.

**Comment by staugur** [comment]
Sorry, reopen the issue here.

After deleting and requesting this package again, will `pkg.go.dev` no longer update the document?

I tried the [about#Adding a package](https://go.dev/about) method, but https://pkg.go.dev/tcw.im/ufc is still 404.

Can this package regenerate documentation? Still need to change the name?

Thanks.

**Comment by jba** [comment]
It's permanently removed. We can un-remove it if you want. Maybe it would help if you explain what your ultimate goal is. Usually people ask us to remove a package because they either don't want anyone to see it ever again, or because they have renamed it.

You mentioned something about submodules in your original post. Can you explain your problem in more detail?

**Comment by staugur** [comment]
Due to the time difference, I just received a reply. Okay, let me briefly describe it.

Cause
=====

`tcw.im/ufc` is the toolkit referenced by my personal project, there is no third-party dependency, and the warehouse address is [mygithub/go-ufc](https://github.com/staugur/go-ufc).

In other projects, I used [github.com/gomodule/redigo](https://github.com/gomodule/redigo) and simply packaged it.

I want to put it in the `mygithub/go-ufc` repository (located in the redigo subdirectory).

The module named `tcw.im/ufc/redigo` is not included in tcw.im/ufc. It is an independent module (but it depends on a version `<A>` of tcw.im/ufc).

Because it depends on `gomodule/redigo`, I don’t want to install `gomodule/redigo` for every project that imports tcw.im/ufc

Ready to work
==============

I refer to [golang/tools/gopls](https://github.com/golang/tools/tree/master/gopls) to set go.mod.

And `tcw.im` is a static blog generated with hugo, the `/ufc` and `/ufc/redigo` created index.html separately, including `go-import` and `go-source` meta, the content is:

```html
<meta name="go-import" content="tcw.im/ufc git https://github.com/staugur/go-ufc">
<meta name="go-source" content="tcw.im/ufc https://github.com/staugur/go-ufc/ https://github.com/staugur/go-ufc/tree/master{/ dir} https://github.com/staugur/go-ufc/blob/master{/dir}/{file}#L{line}">
```

Finally, `tcw.im/ufc/redigo` releases version `redigo/v<B>`, and the preparations are completed.

The warehouse structure now looks like this:

```
.
├── go.mod # module tcw.im/ufc
├── main.go
└── redigo
    # module tcw.im/ufc/redigo, require gomodule/redigo & tcw.im/ufc
    # replace tcw.im/ufc => ../
    ├── go.mod
    ├── go.sum
    ├── redigo.go
```

Test
====

Unfortunately, it can’t be reproduced now. I created and deleted a lot of tags when I tested before, but I remember that the general error message is:

```bash
$ go get tcw.im/ufc/redigo@v<B>
go: downloading tcw.im/ufc v<B>
go: downloading tcw.im/ufc/redigo v<B>
go get: tcw.im/ufc/redigo@v<X??> updating to
	tcw.im/ufc/redigo@v<B>: parsing go.mod:
	module declares its path as: tcw.im/ufc
	        but was required as: tcw.im/ufc/redigo
```

In `~/go/pkg/mod/tcw.im/`, `ufc@v<B>` and `ufc/redigo@v<B>` files are the same.

That is, the real files of `ufc/redigo` in the warehouse are not downloaded.

Installing `tcw.im/ufc/redigo` always downloads the wrong version of `tcw.im/ufc`,
as well as the wrong `tcw.im/ufc/redigo` source code.
This is why I delete the module in pkg.go.dev.

Concluding remarks
==================

Now that `tcw.im/ufc/redigo` has removed the dependency on `tcw.im/ufc`,
it seems to work.

No need to restore, I can change my name.

Thanks!
