### ISSUE TITLE
proxy.golang.org: mention retract directive in documentation

### ISSUE THREAD

**Issue by seankhliao** [golang/go#45489]
From the FAQ:

> **I removed a bad release from my repository but it still appears in the mirror, what should I do?**
>
> Whenever possible, the mirror aims to cache content in order to avoid breaking builds for people that depend on your package, so this bad release may still be available in the mirror even if it is not available at the origin. The same situation applies if you delete your entire repository. We suggest creating a new version and encouraging people to use that one instead.

The [go.mod retract directive](https://golang.org/ref/mod#go-mod-file-retract) should also be mentioned/linked

**Comment by mknyszek** [comment]
CC @katiehockman @heschi @hyangah

**Comment by katiehockman** [comment]
@mknyszek This issue is about the documentation at proxy.golang.org, not pkg.go.dev, so I went ahead and reverted the title change. LMK if I'm missing something.

**Comment by mknyszek** [comment]
Ah, my apologies. I asked who to CC here and I was directed to you. Do you know who is the right owner for proxy.golang.org?

**Comment by katiehockman** [comment]
You have the right owners (including me)! I was just noting that the title of the issue was correct as it was originally filed (ie. for proxy.golang.org), and shouldn't have been changed to pkg.go.dev, which is why I put it back. No worries :)

We'll take a look at updating our documentation for the site, so thanks for CCing us.

**Comment by jamalc** [comment]
The retract directive documentation has been added proxy.golang.org FAQ.
