### ISSUE TITLE
x/pkgsite: support build tags

### ISSUE THREAD

**Issue by lazyhacker** [golang/go#45497]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/lazyhacker.dev/getgo
 
 
### What is your user agent?
 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36

 
### Screenshot
 
![image](https://user-images.githubusercontent.com/5726006/114284980-8d8a5080-9a08-11eb-9cca-7842eb84d0c8.png)

 
### What did you do?
 
Created a go project. 
 
### What did you expect to see?
 
In the source code section there should be a `main_gui.go`.  In the directories section it should have `internal > guimain` 

These are recognized by go mod as the go.mod shows the dpendencies that it needs.
 
### What did you see instead?

 It is missing the `main_gui.go` source file and internal library `guimain`.

**Comment by seankhliao** [comment]
related #37232

**Comment by jba** [comment]
The `main_gui.go` file has a `gui` build tag, so we don't show it.

While we support a few common build tags for GOOS/GOARCH, it isn't feasible to support arbitrary tags. The nature of our backend/frontend split requires that the backend know all the build tags that will be available to the frontend. #37232 explains the problem in more detail.
