### ISSUE TITLE
x/pkgsite: remove github.com/manuelcoppotelli/flatten

### ISSUE THREAD

**Issue by manuelcoppotelli** [golang/go#45493]
### What is the URL of the page with the issue?
 
[https://pkg.go.dev/github.com/manuelcoppotelli/flatten](https://pkg.go.dev/github.com/manuelcoppotelli/flatten)

### What did you expect to see?

As per instructions at [https://go.dev/about](https://go.dev/about) for removing a package: please remove the whole [https://pkg.go.dev/github.com/manuelcoppotelli/flatten](https://pkg.go.dev/github.com/manuelcoppotelli/flatten) module.

I am the creator of this module.
It is an old module and neither the git repo nor the module exist anymore.

Thank you

**Comment by jba** [comment]
Done.
