### ISSUE TITLE
cmd/go2go: run command fails

### ISSUE THREAD

**Issue by justas68** [golang/go#45502]
Hi, I have a simple main package, which works if I do 
**go tool go2go translate main.go2**
**go run main.go**
But it fails if I try to run immediately with command 
**go tool go2go run main.go2**
Getting error:
`cannot find package "run" in any of:
        C:\Users\justast\Desktop\Go\go\src\run (from $GOROOT)
        C:\Users\justast\AppData\Local\Temp\go2go1730022865\src\run (from $GOPATH)
        C:\Users\justast\Desktop\Go\go2\src\run
C:\Users\justast\Desktop\Go\go\bin\go [run run main.go] failed: exit status 1`

**Comment by seankhliao** [comment]
cc @ianlancetaylor 

broken in [CL 303275](https://golang.org/cl/303275)

**Comment by seankhliao** [comment]
Closing as no longer relevant
