### ISSUE TITLE
memory not release

### ISSUE THREAD

**Issue by zhaoya881010** [golang/go#45516]
(pprof) top
Showing nodes accounting for 2048.44kB, 100% of 2048.44kB total
      flat  flat%   sum%        cum   cum%
 1024.38kB 50.01% 50.01%  1024.38kB 50.01%  runtime.malg
  512.05kB 25.00% 75.00%   512.05kB 25.00%  GoProxy/monicore.(*LimitedQueues).Get
  512.02kB 25.00%   100%   512.02kB 25.00%  GoProxy/monicore.(*Processer).ReqMsgDispatch
         0     0%   100%  1024.06kB 49.99%  GoProxy/monicore.(*Processer).run
         0     0%   100%  1024.38kB 50.01%  runtime.mstart
         0     0%   100%  1024.38kB 50.01%  runtime.newproc.func1
         0     0%   100%  1024.38kB 50.01%  runtime.newproc1
         0     0%   100%  1024.38kB 50.01%  runtime.systemstack
(pprof) alloc_space
(pprof) top
Showing nodes accounting for 147.67MB, 91.77% of 160.90MB total
Dropped 41 nodes (cum <= 0.80MB)
Showing top 10 nodes out of 58
      flat  flat%   sum%        cum   cum%
   38.15MB 23.71% 23.71%    38.15MB 23.71%  bufio.NewReaderSize
   21.51MB 13.37% 37.08%   105.16MB 65.36%  GoProxy/vendor/github.com/shirou/gopsutil/internal/common.ReadLinesOffsetN
   19.50MB 12.12% 49.20%    19.50MB 12.12%  strings.makeCutsetFunc
   14.50MB  9.01% 58.21%    14.50MB  9.01%  context.WithValue
   14.50MB  9.01% 67.22%       25MB 15.54%  bufio.(*Reader).ReadString
      12MB  7.46% 74.68%   149.17MB 92.71%  GoProxy/monicore.(*Processer).ReqMsgDispatch
   10.50MB  6.53% 81.21%    10.50MB  6.53%  bufio.(*Reader).ReadBytes
      10MB  6.22% 87.42%       10MB  6.22%  strings.genSplit
    3.50MB  2.18% 89.60%     3.50MB  2.18%  GoProxy/monicore.(*Core).ProcessReq
    3.50MB  2.18% 91.77%     3.50MB  2.18%  strings.Replace
(pprof)

go version 1.12 x64

linux 3.10-862.el7.x86_64

Cyclic calls, memory increases by 100 M a day.  It's strange that other machines do n' t have this problem. madv_free? 3.10 support madv_free?

**Comment by ALTree** [comment]
> go version 1.12 x64

Go 1.12 is no longer supported, moreover the last Go version returns memory to the OS more promptly (using  MADV_DONTNEED). I suggest you upgrade to Go1.16 and see if that makes things better. 

Anyway Go1.12 won't receive any more updates (we support the last two versions), so even if there was an issue there it won't be fixed.
