### ISSUE TITLE
cmd/vet: structtag field json warning for _

### ISSUE THREAD

**Issue by colin-sitehost** [golang/go#45536]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2204759132=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```go
type Struct struct{
        One   string `json:"one"`
        Two   string `json:"_"`
        Three string `json:"_"`
}
```

### What did you expect to see?
Structtag should be aware of the special meaning of ``` `json:"_"` ``` and succeed.

Maybe we can ignore any ``` `xxx:"_"` ``` tags? I think it is out of scope for structtag to be aware of all the repeatable sentinals for struct tags, since third parties can ignore these lints.

### What did you see instead?
```
structtag: struct field Three repeats json tag "_" also at main.go:5
```

**Comment by dsnet** [comment]
> Structtag should be aware of the special meaning of `json:"_"` and succeed.

I'm not aware of any special meaning for `json:"_"`. Did you mean `json:"-"`?

**Comment by colin-sitehost** [comment]
yep, the issue was a typo not a vet bug; sorry for the confusion.

**Comment by dsnet** [comment]
No worries, easy confusion to make.
