### ISSUE TITLE
runtime: port of builtins to ABIInternal breaks windows-amd64-regabi builder

### ISSUE THREAD

**Issue by mknyszek** [golang/go#45530]
Failing as of https://golang.org/cl/308931 with:

```
exit status 0xc0000005
```

It appears to fail consistently in `net/http/internal`.

CC @aclements @cherrymui

**Comment by aclements** [comment]
Failure is in `net/http/pprof`, actually.

**Comment by aclements** [comment]
Looks like `runtime·externalthreadhandler` (in assembly) calls `runtime·memclrNoHeapPointers` with some *very specific* assumptions about what it's going to smash or not smash.
