### ISSUE TITLE
go template: unexpected bad character U+0024 '$' in command

### ISSUE THREAD

**Issue by lizonglin313** [golang/go#45544]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.15.7
</pre>

### Does this issue reproduce with the latest release?
i do not know, may not

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I want use "$" in "href", like **this**:
```html
 href="/passOrg-view?ReguId={{  $Rid  }}&OrgId={{ .$org.ComorgId }}"
```
$Rid and .$org.ComorgId are variate, and i want to use them in url request, but i got this **error** like this after building and running main.exe:
```go
unexpected bad character U+0024 '$' in command
```

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
