### ISSUE TITLE
dl: show the download progress in megabytes (mebibytes) instead of bytes

### ISSUE THREAD

**Issue by perillo** [golang/go#45556]
Showing the download progress in bytes is not very convenient.  The current and total sizes should be in megabytes (mebibytes).

**Comment by mknyszek** [comment]
Sorry, but I'm missing what exactly "dl" is. The only reference I can find is the subset of `x/website` that references the download page.

**Comment by perillo** [comment]
It is the `golang.org/dl` module: https://go.googlesource.com/dl

**Comment by Hallicopter** [comment]
This seems like a somewhat beginner-friendly issue to solve. (Have used Go a lot, but never contributed) I would like to help out in case nobody else is working on it. 
Any pointers from where I can begin? 
I will explore the package a bit myself in the meanwhile.

**Comment by perillo** [comment]
@Hallicopter, I was sure to have already submitted the cl; sorry if you have already started working on it.

**Comment by Hallicopter** [comment]
That's not a problem at all! Just wanted to contribute back to Go in some way since it has helped me so much. I can always find something else.

**Comment by slrz** [comment]
Bytes is much nicer to re-use though. It's more precise and there is no possible confusion with regard to M vs. Mi unit prefixes. You can always convert to displaying MB using a trivial filter while the opposite direction is not possible (the proposed patch throws away information).

I don't think this change is a net improvement.

**Comment by perillo** [comment]
If it needs to be precise I can replace `MB` with `MiB` (as done by pacman, as an example).
About bytes being more precise, I'm not sure.  But I'm sure that with the size in byte, it is harder to follow how much data is being downloaded (at least for me).

To make the progress more precise we can choose the best unit, between KiB and MiB (again, as it is done by pacman).

Thanks.

**Comment by perillo** [comment]
[sample.txt](https://github.com/golang/go/files/6319023/sample.txt) shows the output with the latest patchset in https://golang.org/cl/310016.

The size is formatted in KiB without decimal digits when less then 2 MiB, and in MiB otherwise with 2 decimal digits.  This ensures that the max width in KiB (2048) and the min width in MiB (2.00) are the same (4).

The code changes are minimal and simple.

**Comment by perillo** [comment]
Here is an alternative implementation:
```go
func fmtsize(size int64) string {
	switch {
	case size < 10000:
		return strconv.FormatInt(size, 10) + " B"
	case size < 1000000:
		return strconv.FormatFloat(float64(size)/float64(KiB), 'f', 1, 64) + " KiB"
	}

	return strconv.FormatFloat(float64(size)/float64(MiB), 'f', 1, 64) + " MiB"
}
```

This works correctly only if the download size is greater than 100 MB (decimal).

**Comment by perillo** [comment]
This is probably the best version.  The formatting is similar to the one in `curl`.
```go
func fmtsize(size int64) string {
	// When formatted in KiB there are no decimal digits and when formatted in
	// MiB there is 1 decimal digit.  This ensures that the max width in KiB
	// and the min width in MiB are the same.
	switch {
	case size < 10*KiB:
		return strconv.FormatInt(int64(size), 10) + " B"
	case size < 10*MiB:
		return strconv.FormatFloat(float64(size)/float64(KiB), 'f', 0, 64) + " KiB"
	}

	return strconv.FormatFloat(float64(size)/float64(MiB), 'f', 1, 64) + " MiB"
}
```

**Comment by perillo** [comment]
> Change https://golang.org/cl/339869 mentions this issue: `dl: format download progress in human readable form`

Please note that this change is almost the same as the one I proposed: https://golang.org/cl/310016.  The difference is in the formatting.

**Comment by perillo** [comment]
Why using decimal units instead of binary units?
