### ISSUE TITLE
x/tools/gopls: Issue installing GopherJS package

### ISSUE THREAD

**Issue by Cbonnin88** [golang/go#45561]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.16.3

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Windows

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
I am trying to install a GopherJS package

```go
package main

import (
	"fmt"

	"syscall/js"
)

func main() {
	fmt.Println("Hello Go !")
	js.Global.Get("document").Call("alert", "Hello JavaScript!")
	println("Yo JavaScript console")

}
```

### What did you expect to see?
Hello Go inside of the compiler
hello JavaScript inside of the an JavaScript alert window
Yo JavaScript inside the web console

### What did you see instead?
Error loading workspace: You are outside of a module and outside of $GOPATH/src. If you are using modules, please open your editor to a directory in your module. If you believe this warning is incorrect, please file an issue: https://github.com/golang/go/issues/new.

**Comment by seankhliao** [comment]
please provide the output of `go env`

**Comment by heschi** [comment]
Please follow either https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md if you're a VS Code user or https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md if you're not.
