### ISSUE TITLE
x/pkgsite: https://pkg.go.dev/github.com/n4ch04/aws-policy

### ISSUE THREAD

**Issue by jfagoagas** [golang/go#45560]
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/n4ch04/aws-policy and https://pkg.go.dev/github.com/n4ch04/aws-policy@v1.0.0
 
 
### What is your user agent?
 

 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36

 
 
### Screenshot

![Screenshot 2021-04-14 at 14 03 06](https://user-images.githubusercontent.com/16007882/114707140-259a7980-9d2a-11eb-8ce0-eb085af3097d.png)
 
 
### What did you expect to see?
I can not get rid of this error message at https://pkg.go.dev/github.com/n4ch04/aws-policy@v1.0.0 and I do not understand what is wrong in the package or module name.
 ​
I think that a possible solution could be to remove this package and upload it again. Please, remove this package.

Thanks in advance.

**Comment by seankhliao** [comment]
tags can't be moved, tag a higher version and try again

**Comment by jfagoagas** [comment]
And deleting this package from pkg.go.dev is a better solution, isn't it?

**Comment by seankhliao** [comment]
removing it won't let you republish with the same name / version

**Comment by jfagoagas** [comment]
Okay, thank you!

I think that this is to maintain what is published if someone is using this package. Is that true?

**Comment by julieqiu** [comment]
> I think that this is to maintain what is published if someone is using this package. Is that true?

Yup, from https://proxy.golang.org:

> I removed a bad release from my repository but it still appears in the mirror, what should I do?
>
> Whenever possible, the mirror aims to cache content in order to avoid breaking builds for people that depend on your package, so this bad release may still be available in the mirror even if it is not available at the origin. The same situation applies if you delete your entire repository. We suggest creating a new version and encouraging people to use that one instead.

It looks like https://pkg.go.dev/github.com/n4ch04/aws-policy is now showing v1.0.1:

![image](https://user-images.githubusercontent.com/5943521/114781548-d151c280-9d46-11eb-9a46-3fa93784bff4.png)

**Comment by jfagoagas** [comment]
Yes! I have uploaded a new tag because v1.0.0 was the problem and now it works fine.

Thanks!
