### ISSUE TITLE
Why not provide positionToOffset or positionToPos function?

### ISSUE THREAD

**Issue by ChenhuaYang** [golang/go#45576]
There is a method convert Pos to Position in go/token/position.go, without the method opposites. If I know Filename, Line and Column， how to get Pos?

llvm also privide a  positionToOffset  function in SourceCode.cpp.

**Comment by ianlancetaylor** [comment]
Unlike many projects, we don't use the issue tracker for questions.  Please use a forum instead.  See https://golang.org/wiki/Questions.  Thanks.

A `token.Pos` is an encoded value that can only be interpreted with respect to a `token.File`, and can only be created from a `token.File`, using methods like `File.Pos`.
