### ISSUE TITLE
go/types: missing error for non-comparable switch expression in empty switch

### ISSUE THREAD

**Issue by griesemer** [golang/go#45575]
Missing `go/types` error for:
```Go
package p

func _() {
	var a struct{ _ func() }
	switch a {
	}
}
```
This has been fixed in `types2`. See #43200 for details.

**Comment by findleyr** [comment]
This was fixed in https://golang.org/cl/278813, which I just confirmed at tip with the example in this issue.

@griesemer where are you noticing the missing error?

**Comment by griesemer** [comment]
Never mind - it turns out that I was running the test incorrectly for `go/types`.
