### ISSUE TITLE
crypto/tls: TestServerHandshakeContextCancellation failure with "Socket is not connected" on js-wasm

### ISSUE THREAD

**Issue by bcmills** [golang/go#45590]
[2021-03-19T19:59:56-3b0d288/js-wasm](https://build.golang.org/log/279202c6899252eaa47c5f9a5e7f1015d225aa28)

```
--- FAIL: TestServerHandshakeContextCancellation (0.00s)
    handshake_server_test.go:1975: Unexpected server handshake error: write tcp 127.0.0.1:1->127.0.0.1:228: Socket is not connected
    handshake_server_test.go:1981: conn.Close does not error as expected when called multiple times on WASM
FAIL
FAIL	crypto/tls	8.362s
```

It isn't obvious to me whether this is the same underlying problem as #45299 and/or #45106 (CC @johanbrandhorst)

**Comment by bcmills** [comment]
Also seen on a TryBot: https://storage.googleapis.com/go-build-log/e31d7a76/js-wasm_498d5646.log

**Comment by johanbrandhorst** [comment]
With #45106 resolved, hopefully it should tell us whether this is the same bug.
