### ISSUE TITLE
Integer version of math.Max function

### ISSUE THREAD

**Issue by karthikprabhu17** [golang/go#45596]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.8 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kp/.cache/go-build"
GOENV="/home/kp/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/kp/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/kp/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build308031926=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/pejpBtG_z_o

### What did you expect to see?
I expected a integer version of the Max function. Typecasting all int to float64 make the line very unintelligible very easily. 

### What did you see instead?
I had to basically type cast the entire slice or type to a float64 before using it.

**Comment by smasher164** [comment]
One of the motivations behind the generics proposal is to be able to define a `Min` and `Max` functions across integral types. See [Type Parameters Proposal#Pervasiveness](https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#pervasiveness):

> The math package will be extended to provide a set of simple standard algorithms for all numeric types, such as the ever popular `Min` and `Max` functions.

In the meantime, there are [multiple intmath packages](https://pkg.go.dev/search?q=int+math) that define variations of min/max for every integral type. Does that work out for you?

**Comment by karthikprabhu17** [comment]
Thanks much. Definitely does. Appreciate the speedy response
