### ISSUE TITLE
x/tools/gopls: option to enable analysis across entire workspace

### ISSUE THREAD

**Issue by mgdotson** [golang/go#45600]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOOS="linux"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build867817669=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```
gopls version
golang.org/x/tools/gopls v0.6.10
    golang.org/x/tools/gopls@v0.6.10 h1:8Ebz8PymS2umcuCFhoz67unyJfWsipjTIrkBUF9kypg=
```
![image](https://user-images.githubusercontent.com/24966248/115070483-3a097e00-9eb2-11eb-99ba-918455c8379e.png)

VSCODE: Open up go workspace.  Analysis highlights on Explorer Panel do not show any files with any issues and analysis on bottom toolbar show 0 warnings and 0 issues.

Click on a file to open it and still no update to the issues or warnings.  Save the file - with no changes made, and the issues and warnings are only updated for the current directory with that file.

### What did you expect to see?

I expected to see all the issues and warnings for my entire workspace, top level project and all pkg sub modules.  Attached pictures should have all three files highlighted and both the directories.
![image (1)](https://user-images.githubusercontent.com/24966248/115070137-c23b5380-9eb1-11eb-8c25-551abb7e920a.png)
![image (2)](https://user-images.githubusercontent.com/24966248/115070146-c5ceda80-9eb1-11eb-9d4f-125793232e63.png)

### What did you see instead?

No analysis or warning evaluations.  I would expect to see all of the files with analysis issues or warnings in my explorer window and as a summary in my bottom toolbar

**Comment by mknyszek** [comment]
CC @stamblerre via https://dev.golang.org/owners

**Comment by mgdotson** [comment]
This seems to be working again once I restarted my Athens Proxy service as there was an issue downloading one of the mongo-drivers when changing lint tool setting to use `golanglint-ci`.

VSCode setting `"go.lintOnSave": "workspace"` is linting the entire workspace without issue and without setting `    "go.lintTool"` in vscode settings, the default `staticcheck` is being called as expected and entire workspace is being linted.
