### ISSUE TITLE
Easier unit testing of straightforward code.

### ISSUE THREAD

**Issue by sirkon** [golang/go#45605]
Hi.

# The problem

In practice is sometimes the easiest to implement some functionality  using a "smaller" function which is to be called by a "greater" one.

Imagine something like

```go
type Struct struct {
    …
}

func (s *Struct) GetByIDs(ctx context.Context, ids []string) ([]*Item, error) {
    var res []*Item
    for _, id := range ids {
        item, err := s.getByID(ctx, id)
        if err != nil {
            return nil, fmt.Errorf("get item by id=%s: %w, id, err)
        }

        res = append(res, item)
    }

    return res, nil
}

func (s *Struct) getByID(ctx context.Context, id string) (*Item, error) {
    …
}
```

`getByID` can be fairly complex at that calling different subsystems during its execution.

And now we may have a good unit test for `getByID`. In the same time we 

* Need to test it `geByID` again and again in a unit test for `GetByIDs`, just because it always calls `getByID`.
* In fact we just need to test if the thing is calling with right arguments. The aforementioned circumstances makes it not so easy: checks it with inner calls of `getByID`. This is anything but clear.

There are numerous way to overcome this, but they are anything but clear again: useless interfaces which only serve testing , or build tags + substructuring, or code generation (create a "copy" of struct calling). All these approaches smell and complicate implementation for no reason other than unit testing.

# What I would love to have

Some magic way to call some "substitution" of `getByID` in "derived" structure. I mean, the problem would be solved if I could make a new type

```go
import "./internal/structmock"

type getByIDsStruct struct {
    Struct

    mock *structmock.StructMock
}

func (s *getByIDsStruct) getByID(ctx context.Context, id string) (*Item, error) {
    return s.mock.getByID(ctx, id)
}
```

where `GetByID` called on this struct would call `(*getByIDsStruct).getByID` instead of `(*Struct).getByID`. This would make a unit testing a breeze in comparison. 

Obviously, there are can be different approaches but the desired behavior stays the same: a way to replace actual implementation with something different what would let us to emulate a behavior without artificial interfaces serving no real purpose. No need to provide this functionality into runtime, just some testing magic is enough.

**Comment by seankhliao** [comment]
To discuss ideas please use the forums: https://golang.org/wiki/Questions
Once there is a more concrete proposal how to improve testing feel free to open a new issue. The proposal as currently stated has no actionable content.

A proposal not only need to state a problem but also suggest a workable solution.
Consider writing an experience report: https://github.com/golang/go/wiki/ExperienceReports to
point out areas that need improvement drawn from experience working with Go.
