### ISSUE TITLE
math/rand should use not use static default seed

### ISSUE THREAD

**Issue by smadarasmi** [golang/go#45618]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.15.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sarinmadarasmi/Library/Caches/go-build"
GOENV="/Users/sarinmadarasmi/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/sarinmadarasmi/go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/sarinmadarasmi/go"
GOROOT="/usr/local/Cellar/go/1.15.6/libexec"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yv/9n_vr1dx52v36n61tf77xw1r0000gq/T/go-build785237644=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```go
import "math/rand"

func GetRandom() int64 {
    return rand.Int63()
}
```

Everytime your main program starts, the sequence of random numbers generated will be the same. 

### What did you expect to see?
I expected the sequence of random numbers generated to be unique. 

The issue is that the default seed, if not specified, is set to `1` which I think is quite dangerous. Most languages, when seed is not specified, will use the system time as the seed. I think we should make this consistent in Go to avoid mistakes and assumptions by developers. 

### What did you see instead?
Same sequence of generated random numbers because seed is always set as `1` unless specifically set. 

### Proposal 
Use `time.Now().UTC().UnixNano()` rather than `1` as the default seed for consistency with other programming languages. 

I wanted to submit an MR/patch on this issue right away but was not sure if there was a specific reason we went with default seed of `1`. Apologize if this issue has been reported but I didn't find it from a quick issue search.

**Comment by ALTree** [comment]
This is #11871.

> I think is quite dangerous.

Why? The `math` generator should never be used for security-sensitive applications. The fact the the sequence is deterministic and repeatable by default is a good thing.

**Comment by robpike** [comment]
Working as intended. You should be seeding the generator if you care about non-reproducibility.
