### ISSUE TITLE
cmd/go: `go get github.com/hajimehoshi/ebiten/examples/shader` failed with no-main error

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#45615]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hajimehoshi/Library/Caches/go-build"
GOENV="/Users/hajimehoshi/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/hajimehoshi/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/hajimehoshi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/tmp/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/60/khbk2xqn1c5bml1byjn89dwc0000gn/T/go-build1521022541=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
go mod init foo
go get github.com/hajimehoshi/ebiten/...
```

EDIT:

```
go mod init foo
go get github.com/hajimehoshi/ebiten/examples/shader
```

is better

### What did you expect to see?

No errors

### What did you see instead?

```
# github.com/hajimehoshi/ebiten/examples/shader
runtime.main_main·f: function main is undeclared in the main package
```

The shader package should include the main function.

I'm afraid I could not create a minimum case to reproduce this issue.

Thanks,

**Comment by seankhliao** [comment]
you're missing either a main function or build tags to hide all the files

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by hajimehoshi** [comment]
> you're missing either a main function or build tags to hide all the files

This error is different from the other errors:

```
$ go get github.com/hajimehoshi/ebiten/examples/rotate
github.com/hajimehoshi/ebiten/examples/rotate: no Go source files
package github.com/hajimehoshi/ebiten/examples/rotate: build constraints exclude all Go files in /Users/hajimehoshi/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.12.11/examples/rotate

$ go get github.com/hajimehoshi/ebiten/examples/shader
# github.com/hajimehoshi/ebiten/examples/shader
runtime.main_main·f: function main is undeclared in the main package

```

**Comment by seankhliao** [comment]
the code if v1.12.11 has unbuildtagged code without a main function

**Comment by hajimehoshi** [comment]
Right. So the odd thing is, when using `...`,

```
go get github.com/hajimehoshi/ebiten/examples/...
```

complains only for `shader` project, not for the other project that are unbuildtagged.

**Comment by seankhliao** [comment]
Only shader is a main program without build tags

```
$ cd examples
$ go list -f '{{ .Name }} {{ .Dir }}' ./...
twenty48 /home/arccy/tmp/ebiten/examples/2048/2048
blocks /home/arccy/tmp/ebiten/examples/blocks/blocks
keyboard /home/arccy/tmp/ebiten/examples/keyboard/keyboard
resources /home/arccy/tmp/ebiten/examples/resources
audio /home/arccy/tmp/ebiten/examples/resources/audio
fonts /home/arccy/tmp/ebiten/examples/resources/fonts
images /home/arccy/tmp/ebiten/examples/resources/images
blocks /home/arccy/tmp/ebiten/examples/resources/images/blocks
flappy /home/arccy/tmp/ebiten/examples/resources/images/flappy
keyboard /home/arccy/tmp/ebiten/examples/resources/images/keyboard
mascot /home/arccy/tmp/ebiten/examples/resources/images/mascot
platformer /home/arccy/tmp/ebiten/examples/resources/images/platformer
shader /home/arccy/tmp/ebiten/examples/resources/images/shader
main /home/arccy/tmp/ebiten/examples/shader
```

**Comment by hajimehoshi** [comment]
`generate.go` didn't have the build tag on 1.12 and 2.0 branch (not master branch). This was my fault. Thank you for the insights.
