### ISSUE TITLE
js.Global().Call("someFunc") - How to handle error responses gracefully ? 

### ISSUE THREAD

**Issue by mar1n3r0** [golang/go#45610]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
How do you handle error responses from a JS function so that the app  does not stop execution and exit ?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
