### ISSUE TITLE
'Sealed Box' functionality in x/crypto/nacl/box does not actually work round-trip

### ISSUE THREAD

**Issue by swsnider** [golang/go#45617]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.16.3
</pre>

### Does this issue reproduce with the latest release?

Yes, it repros on playground

### What operating system and processor architecture are you using (`go env`)?

N/A, repros on playground

### What did you do?

https://play.golang.org/p/T9Y1LIy0z1p

### What did you expect to see?

No panic, i.e. that OpenAnonymous(SealAnonymous(msg)) both works and is the identity function.

### What did you see instead?

box library returns `!ok` for this operation, and I've traced that locally to the line `if !poly1305.Verify(&tag, box[poly1305.TagSize:], &poly1305Key) {` in secretbox.go failing for reasons that are mysterious to me.

**Comment by seankhliao** [comment]
SealAnonymous says:
> SealAnonymous appends an encrypted and authenticated copy of message to out

so your encrypted message is prefixed by the blank space you allocated

https://play.golang.org/p/Xh13MHx97YQ

https://play.golang.org/p/1GXO2WJlxxC
