### ISSUE TITLE
Why can't recovery the panic from http.transport

### ISSUE THREAD

**Issue by iScorpius** [golang/go#45623]
### What version of Go are you using (`go version`)?

<pre>
go version go1.16.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes (Because i'm using the lastest version)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\galaxy\AppData\Local\go-build
set GOENV=C:\Users\galaxy\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\Runtime\go\cache\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\Runtime\go\cache
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Runtime\go\go1.16.2.windows-amd64\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Runtime\go\go1.16.2.windows-amd64\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.2
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\galaxy\AppData\Local\Temp\go-build3827531474=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
I want to request url from the specify interface , but when i specify an interface not exsit or not working or status down (only when i'm test application), it's panic error from http.transport.

<details><summary>here is the core code</summary><br><pre>
func getPublicNetIP(IF int, IFName string, uri string) (string, error) {
	var tr *http.Transport
	var lIP net.IP
	if IF <= 0 && IFName == "" {
		tr = &http.Transport{
			TLSClientConfig: &tls.Config{
				InsecureSkipVerify: true,
			},
		}
	} else if IF > 0 {
		var err error
		lIP, err = selectInterfaceByIndex(IF)
		if err != nil {
			return "", err
		}
	} else if IFName != "" {
		var err error
		lIP, err = selectInterfaceByName(IFName)
		if err != nil {
			return "", err
		}
	}
	if lIP != nil {
		tr = &http.Transport{
			TLSClientConfig: &tls.Config{
				InsecureSkipVerify: true,
			},
			DialContext: func(ctx context.Context, network string, addr string)(net.Conn, error) {
				lAddr, err := net.ResolveTCPAddr(network, lIP.String() + ":0")
				if err != nil {
					return nil, err
				}
				rAddr, err := net.ResolveTCPAddr(network, addr)
				if err != nil {
					return nil, err
				}
				conn, err := net.DialTCP(network, lAddr, rAddr)
				return conn, nil
			},
		}
	}
	client := &http.Client{Transport: tr}
	resp, err := client.Get(uri)
	if err != nil {
		fmt.Print(err.Error())
		return "", err
	}
	defer resp.Body.Close()

	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		fmt.Print(err.Error())
	}
	reg := regexp.MustCompile(`\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}`)
	rIP := reg.Find(body)
	if len(rIP) == 0 {
		return "", errors.New("IP is nil")
	}
	return string(rIP), nil
}
</pre></details>

### What did you expect to see?
I hope the `recover()` function can recovery the panic from http.transport,  but unfortunately, it can't.

### What did you see instead?
It throw the panic from http.transport, and terminate the program, recover() in main() function can't recovery any panic.
![Snipaste_2021-04-19_09-28-28](https://user-images.githubusercontent.com/20828349/115169811-ade59980-a0f1-11eb-8199-e59d2d69fdc8.png)
![Snipaste_2021-04-19_09-28-04](https://user-images.githubusercontent.com/20828349/115169814-afaf5d00-a0f1-11eb-9d8d-d8af8e2f5164.png)

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
