### ISSUE TITLE
net: Dial() connection refused error is not `syscall.ECONNREFUSED` value on windows

### ISSUE THREAD

**Issue by JamesDunne** [golang/go#45621]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

https://play.golang.org/p/9jvY6yme07T

### What did you expect to see?
Expected error value returned from `net.Dial()` to be a `syscall.Errno` value equal to `syscall.ECONNREFUSED`

### What did you see instead?
```
error is a syscall.Errno value: 0x274d
dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.
```

**Comment by ianlancetaylor** [comment]
The exact use of `sysca.ECONNREFUSED` is inherently system dependent.  It doesn't work on all systems.  In particular, as you've discovered, it doesn't work on Windows.

What are you really trying to do?

**Comment by JamesDunne** [comment]
Ah very well then.

I'm just trying to suppress otherwise noisy error logging of attempts to connect to a service that is not guaranteed to be up. I worked around the problem on windows by comparing to the exact syscall.Errno value I discovered.
