### ISSUE TITLE
flag: Value example use code that is reported by golint

### ISSUE THREAD

**Issue by perillo** [golang/go#45622]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

The `Value` example in the flag package (https://golang.org/pkg/flag/#example_Value) uses the code:

```go
if u, err := url.Parse(s); err != nil {
	return err
} else {
	*v.URL = *u
}
return nil
```

`golint` reports:
`if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)`.

Not sure if the code should be modified.

Thanks.

**Comment by ianlancetaylor** [comment]
Sure, we can change the example code.  Thanks.

**Comment by mvdan** [comment]
The change was abandoned; closing.
