### ISSUE TITLE
Content-Type is text/x-go on go master branch, why?

### ISSUE THREAD

**Issue by thinkerou** [golang/go#45625]
### What version of Go are you using (`go version`)?

<pre>
$ go1.16\go1.15 is ok
$ go master branch is error

</pre>

### Does this issue reproduce with the latest release?
go master branch can reproduce

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

here: https://github.com/gin-gonic/gin/blob/master/context_test.go#L1012

    func TestContextRenderFile(t *testing.T) {
	    w := httptest.NewRecorder()
	    c, _ := CreateTestContext(w)
    
	    c.Request, _ = http.NewRequest("GET", "/", nil)
	    c.File("./gin.go")
    
	    assert.Equal(t, http.StatusOK, w.Code)
	    assert.Contains(t, w.Body.String(), "func New() *Engine {")
	    assert.Equal(t, "text/plain; charset=utf-8", w.Header().Get("Content-Type"))
    }

### What did you expect to see?
Content-Type is `text/plain; charset=utf-8`

### What did you see instead?
Content-Type is `text/x-go; charset=utf-8`

**Comment by ZekeLu** [comment]
Can you debug your source code to find out where `text/x-go; charset=utf-8` is from? Please note that mime type is system-dependent.

https://github.com/golang/go/blob/a72622d028077643169dc48c90271a82021f0534/src/mime/type.go#L92-L109

BTW, unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by seankhliao** [comment]
As mentioned above, the returned content type depends on the mime database installed on the host system
