### ISSUE TITLE
go/types: missing error message for incorrect (generic) program

### ISSUE THREAD

**Issue by rvolosatovs** [golang/go#45635]
### What version of Go are you using (`go version`)?

```
go version 2021-03-22 linux/amd64
```

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/rvolosatovs/.local/bin.go"
GOCACHE="/home/rvolosatovs/.local/cache/go-build"
GOENV="/home/rvolosatovs/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/rvolosatovs/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/rvolosatovs"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/nix/store/jfzfymdd8pdia5jlvnc96nm5znjh9x6j-go2-unstable-2021-03-22/share/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/nix/store/jfzfymdd8pdia5jlvnc96nm5znjh9x6j-go2-unstable-2021-03-22/share/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="2021-03-22"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/rvolosatovs/src/github.com/rvolosatovs/collections/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/run/user/1000/go-build2470782358=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Panics(two or more parameters): https://go2goplay.golang.org/p/gc3cZ-qe5bG

Works: https://go2goplay.golang.org/p/AQ_JWojgRic
Prints correct error(single parameter): https://go2goplay.golang.org/p/bW2i30OWP6F

### What did you expect to see?

The first example should print an error same as last one

Note, that calls to identifiers defined in imported packages with multiple parameters fail with the same error

### What did you see instead?

Panic in parser

**Comment by ianlancetaylor** [comment]
This is a panic in the go2go type checker.  The current type checker reports an error (`undefined: some`).  I don't think it's worth updating the go2go type checker to better handle erroneous cases, but leaving for @griesemer .

**Comment by rvolosatovs** [comment]
Well
```
panic: prog.go2:4:7: unknown expression type *ast.ListExpr [recovered]
	panic: prog.go2:4:7: unknown expression type *ast.ListExp
```
is quite cryptic for the end user in my opinion, so I think it's definitely worth improving. Note, again, that it works fine with single parameter identifiers.

What's more important is that this seems to also break references to identifiers in different packages.
Locally, the `go2go` tool panics when instantiating multi-parameter imported types/functions.

**Comment by ianlancetaylor** [comment]
I don't see that error on tip.  Which version of the program are you testing?

**Comment by griesemer** [comment]
@rvolosatovs This is working as expected on tip (types2, and compiler with -G=3 option). It doesn't produce any error message with go/types at the moment, and that seems like a bug. What you are seeing is likely due to running a version that is not fully up-to-date. The `go2go` playground will be updated eventually, but currently is a bit behind.

**Comment by griesemer** [comment]
@findleyr This program:
```Go
package main

func main() {
	some[int, int]()
}
```
doesn't seem to produce an error message with `go/types` at the moment.
