### ISSUE TITLE
cmd/compile: compiler generates calls to empty functions

### ISSUE THREAD

**Issue by gopherbot** [golang/go#4563]
by **martisch@uos.de**:

<pre><a href="http://play.golang.org/p/NDxhDNrRC7">http://play.golang.org/p/NDxhDNrRC7</a>
empty (assembler) test function is inlined

--- prog list &quot;test&quot; ---
0000 (/Users/martisch/test.go:3) TEXT    test+0(SB),$0-0
0001 (/Users/martisch/test.go:6) RET     ,

--- prog list &quot;main&quot; ---
0002 (/Users/martisch/test.go:8) TEXT    main+0(SB),$0-0
0003 (/Users/martisch/test.go:10) RET     ,

but here:

<a href="http://play.golang.org/p/Nyd_WLfObv">http://play.golang.org/p/Nyd_WLfObv</a>
empty (assembler) test function gets called and is not inlined

--- prog list &quot;test&quot; ---
0000 (/Users/martisch/test.go:3) TEXT    test+0(SB),$40-0
0001 (/Users/martisch/test.go:7) RET     ,

--- prog list &quot;main&quot; ---
0002 (/Users/martisch/test.go:9) TEXT    main+0(SB),$0-0
0003 (/Users/martisch/test.go:10) CALL    ,test+0(SB)
0004 (/Users/martisch/test.go:11) RET     ,

What is the expected output?
I would assume as a basic optimization any empty function should get inlined or just no
call should be generated.

What do you see instead?
A call to an empty function is generated and the function is not inlined.

Which compiler are you using (5g, 6g, 8g, gccgo)?
6g

Which operating system are you using?
OS X 10.8.2

Which version are you using?  (run 'go version')
go version devel +111aa291b561 Mon Dec 17 12:01:00 2012 -0800 darwin/amd64</pre>

**Comment by randall77** [comment]
This has been fixed for a while.
We now do whole subtree inlining, and dead code elimination.
