### ISSUE TITLE
x/pkgsite: Tagged website API does not match tagged repo API

### ISSUE THREAD

**Issue by 89z** [golang/go#45640]
This commit was done two days ago:

https://github.com/kkdai/youtube/commit/4cbae9358f4ccb33fb81810ab6f0e5b5739bb977

and a tag was put on the same commit:

https://github.com/kkdai/youtube/releases/tag/v2.6.0

and supposedly, the website is showing the latest tag:

https://pkg.go.dev/github.com/kkdai/youtube/v2

but its not. The API should be `Sort`, not `SortFormats`:

https://pkg.go.dev/github.com/kkdai/youtube/v2#FormatList.SortFormats

**Comment by julieqiu** [comment]
It seems like the commit might have tagged before `SortFormats` was renamed to `Sort`. As described in https://go.dev/about:

> Data for the site is downloaded from proxy.golang.org. We monitor the Go Module Index regularly for new packages to add to pkg.go.dev. 

When I open the zip at http://proxy.golang.org/github.com/kkdai/youtube/v2/@v/v2.6.0.zip, `format_list.go` shows the contents pasted below, and contains the function `SortFormats`.

Per the FAQ section of https://proxy.golang.org, the best thing to do in this situation is to publish a new version.

> I removed a bad release from my repository but it still appears in the mirror, what should I do?
>
> Whenever possible, the mirror aims to cache content in order to avoid breaking builds for people that depend on your package, so this bad release may still be available in the mirror even if it is not available at the origin. The same situation applies if you delete your entire repository. We suggest creating a new version and encouraging people to use that one instead.

```
package youtube

import (
	"sort"
	"strconv"
	"strings"
)

type FormatList []Format

// FindByQuality returns the first format matching Quality or QualityLabel
func (list FormatList) FindByQuality(quality string) *Format {
	for i := range list {
		if list[i].Quality == quality || list[i].QualityLabel == quality {
			return &list[i]
		}
	}
	return nil
}

// FindByItag returns the first format matching the itag number
func (list FormatList) FindByItag(itagNo int) *Format {
	for i := range list {
		if list[i].ItagNo == itagNo {
			return &list[i]
		}
	}
	return nil
}

// Type returns a new FormatList filtered by mime type of video
func (list FormatList) Type(t string) (result FormatList) {
	for i := range list {
		if strings.Contains(list[i].MimeType, t) {
			result = append(result, list[i])
		}
	}
	return result
}

// Quality returns a new FormatList filtered by quality, quality label or itag,
// but not audio quality
func (list FormatList) Quality(quality string) (result FormatList) {
	for _, f := range list {
		itag, _ := strconv.Atoi(quality)
		if itag == f.ItagNo || strings.Contains(f.Quality, quality) || strings.Contains(f.QualityLabel, quality) {
			result = append(result, f)
		}
	}
	return result
}

// AudioChannels returns a new FormatList filtered by the matching AudioChannels
func (list FormatList) AudioChannels(n int) (result FormatList) {
	for _, f := range list {
		if f.AudioChannels == n {
			result = append(result, f)
		}
	}
	return result
}

// FilterQuality reduces the format list to formats matching the quality
func (v *Video) FilterQuality(quality string) {
	v.Formats = v.Formats.Quality(quality)
	v.Formats.SortFormats()
}

// SortFormats sorts all formats fields
func (list FormatList) SortFormats() {
	sort.SliceStable(list, func(i, j int) bool {
		return sortFormat(i, j, list)
	})
}

// sortFormat sorts video by resolution, FPS, codec (av01, vp9, avc1), bitrate
// sorts audio by codec (mp4, opus), channels, bitrate, sample rate
func sortFormat(i int, j int, formats FormatList) bool {
	// Sort by Width
	if formats[i].Width == formats[j].Width {
		// Sort by FPS
		if formats[i].FPS == formats[j].FPS {
			if formats[i].FPS == 0 && formats[i].AudioChannels > 0 && formats[j].AudioChannels > 0 {
				// Audio
				// Sort by codec
				codec := map[int]int{}
				for _, index := range []int{i, j} {
					if strings.Contains(formats[index].MimeType, "mp4") {
						codec[index] = 1
					} else if strings.Contains(formats[index].MimeType, "opus") {
						codec[index] = 2
					}
				}
				if codec[i] == codec[j] {
					// Sort by Audio Channel
					if formats[i].AudioChannels == formats[j].AudioChannels {
						// Sort by Audio Bitrate
						if formats[i].Bitrate == formats[j].Bitrate {
							// Sort by Audio Sample Rate
							return formats[i].AudioSampleRate > formats[j].AudioSampleRate
						}
						return formats[i].Bitrate > formats[j].Bitrate
					}
					return formats[i].AudioChannels > formats[j].AudioChannels
				}
				return codec[i] < codec[j]
			}
			// Video
			// Sort by codec
			codec := map[int]int{}
			for _, index := range []int{i, j} {
				if strings.Contains(formats[index].MimeType, "av01") {
					codec[index] = 1
				} else if strings.Contains(formats[index].MimeType, "vp9") {
					codec[index] = 2
				} else if strings.Contains(formats[index].MimeType, "avc1") {
					codec[index] = 3
				}
			}
			if codec[i] == codec[j] {
				// Sort by Audio Bitrate
				return formats[i].Bitrate > formats[j].Bitrate
			}
			return codec[i] < codec[j]
		}
		return formats[i].FPS > formats[j].FPS
	}
	return formats[i].Width > formats[j].Width
}
```

**Comment by 89z** [comment]
> It seems like the commit might have tagged before `SortFormats` was renamed to `Sort`.

This sentence doesnt make any sense. With Git, someone makes a commit, then they optionally tag that commit, either via the command line followed by `git push --tag`, or with the GitHub UI. Can you please explain what you are trying to convey here?

> When I open the zip at http://proxy.golang.org/github.com/kkdai/youtube/v2/@v/v2.6.0.zip, `format_list.go` shows the contents pasted below, and contains the function `SortFormats`.

This detail doesnt mean anything, as that link is not the canonical source of that data, this is:

https://github.com/kkdai/youtube/archive/refs/tags/v2.6.0.zip

> Per the FAQ section of https://proxy.golang.org, the best thing to do in this situation is to publish a new version.

Wouldnt the better option be to fix the proxy files? They do not match the canonical source, so by definition they are wrong. And even if someone were to do as you say, how do we know the problem wont repeat on the next tag?

**Comment by 89z** [comment]
Also, comically, if you go here:

https://pkg.go.dev/github.com/kkdai/youtube/v2#FormatList.SortFormats

and then click the link to source:

https://github.com/kkdai/youtube/blob/v2.6.0/format_list.go#L70

You get this:

~~~go
func (list FormatList) Sort() {
	sort.SliceStable(list, func(i, j int) bool {
		return sortFormat(i, j, list)
	})
}
~~~

**Comment by seankhliao** [comment]
The module ecosystem requires immutable versioning: https://golang.org/ref/mod#versions
The canonical version is the one first seen by the proxy/sumdb.. That an upstream moved a tag is an error on their part. 

```
GOPROXY=direct go get github.com/kkdai/youtube/v2
go: downloading github.com/kkdai/youtube/v2 v2.6.0
go: downloading github.com/kkdai/youtube v1.2.4
go get: github.com/kkdai/youtube/v2@v2.6.0: verifying module: checksum mismatch
	downloaded: h1:+xddr2ezK+KHHaskxtd5lk3iH1pBeUxxOe5jzSfKiNE=
	sum.golang.org: h1:WaP358yBQJEsN5y0L2RpvIM8p7DMKXd23byQhTi3sQY=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by 89z** [comment]
@seankhliao thanks.

I am not sure if thats what happened, but its possible. Here is a better quote:

> Once a tag is created, it should not be deleted or changed to a different revision. Versions are authenticated to ensure safe, repeatable builds. If a tag is modified, clients may see a security error when downloading it. Even after a tag is deleted, its content may remain available on module proxies.

https://golang.org/ref/mod#vcs-version

**Comment by 89z** [comment]
@seankhliao I tried that command, but it doesnt output anything:

~~~
PS C:\> $env:GOPROXY = 'direct'
PS C:\> go get github.com/kkdai/youtube/v2
PS C:\>
~~~

**Comment by 89z** [comment]
They have pushed a new version, so this issue is moot for now.
