### ISSUE TITLE
go/types: suspicious return of Typ[Int] in (*Checker).index

### ISSUE THREAD

**Issue by mdempsky** [golang/go#45667]
While looking at go/types source, I noticed this return statement at the end of `(*Checker).index`:

https://github.com/golang/go/blob/5f1df260a91183c605c08af7b00741d2761b84e4/src/go/types/expr.go#L1047-L1048

I think this should probably use `x.typ` instead of `Typ[Int]`. Untyped constants were already converted to `int` at line 1020.

I think the consequence of this is that for an expression like `make([]int, uint(1))`, the signature passed to `recordBuiltinType` will incorrectly report the parameter as `int` instead of `uint`. I haven't confirmed this though.

/cc @griesemer @findleyr

**Comment by findleyr** [comment]
Thanks. Your analysis is correct, and I've confirmed we're recording an incorrect signature.

We should fix this (right?), but that does seem to be the only consequence -- other uses of Checker.index only check for Typ[Invalid].

**Comment by griesemer** [comment]
Yes, it does look like a bug.
