### ISSUE TITLE
cmd/go2go: can't use other packages/files

### ISSUE THREAD

**Issue by LCaparelli** [golang/go#45674]
### What version of Go are you using (`go version`)?

<pre>
❯ bin/go version
go version devel +9cd52cf2a9 Tue Apr 13 00:32:27 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, I'm using the latest commit from the dev.go2go branch.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
❯ bin/go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lcaparelli/.cache/go-build"
GOENV="/home/lcaparelli/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/lcaparelli/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/lcaparelli/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/lcaparelli/gitrepos/goroot"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/lcaparelli/gitrepos/goroot/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel +9cd52cf2a9 Tue Apr 13 00:32:27 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3184285128=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I have set the `GO2PATH` variable to my project's root dir:

```
❯ echo $GO2PATH
/home/lcaparelli/go/src/github.com/LCaparelli/operails
```

My `main.go2` file imports the `github.com/LCaparelli/operails/factory` package:

```go
package main

import (
	"fmt"

	"github.com/LCaparelli/operails/factory"
)

type input struct {
	name string
}

type output struct {
	name string
}

func setName(in input, building output) output {
	building.name = in.name
	return building
}

func main() {
	f := factory.NewFactory[input, output](setName)
	out := f.Build(input{name: "test"})
	fmt.Printf("%#v", out)
}
```

And that package has a single file:

```go
package factory

type Factory[input any, output any] interface {
	Build(input) output
}

type factory [input any, output any] struct {
	buildSteps []func(input, output) output
}

func NewFactory[input any, output any](steps ...func(input, output) output) Factory[input, output] {
	return factory[input, output]{buildSteps: steps}
}

func (f factory[input, output]) Build(in input) output {
	var out output
	for _, step := range f.buildSteps {
		out = step(in, out)
	}
	return out
}
```

### What did you expect to see?

The program runs fine, as it does on the playground when it's all in the same file/package: https://go2goplay.golang.org/p/jx1GQjYTe2t

### What did you see instead?

`go tool go2go run main.go2` fails:

<details><summary><code>go tool go2go run main.go2</code> Output</summary><br><pre>
❯ bin/go tool go2go run main.go2
panic: /tmp/go2go-run400703277/main.go2:23:26: unknown expression type *ast.ListExpr [recovered]
	panic: /tmp/go2go-run400703277/main.go2:23:26: unknown expression type *ast.ListExpr

goroutine 1 [running]:
go/types.(*Checker).handleBailout(0xc0000f8160, 0xc0001019e8)
	/home/lcaparelli/gitrepos/goroot/src/go/types/check.go:249 +0xa5
panic(0x6597e0, 0xc00009fa90)
	/home/lcaparelli/gitrepos/goroot/src/runtime/panic.go:972 +0x1d4
go/types.(*Checker).exprInternal(0xc0000f8160, 0xc000159440, 0x6f56d8, 0xc0000ae180, 0x0, 0x0, 0x40)
	/home/lcaparelli/gitrepos/goroot/src/go/types/expr.go:1800 +0x4157
go/types.(*Checker).rawExpr(0xc0000f8160, 0xc000159440, 0x6f56d8, 0xc0000ae180, 0x0, 0x0, 0xc0000ae168)
	/home/lcaparelli/gitrepos/goroot/src/go/types/expr.go:1136 +0x85
go/types.(*Checker).use(0xc0000f8160, 0xc0000ffd90, 0x1, 0x1)
	/home/lcaparelli/gitrepos/goroot/src/go/types/call.go:768 +0xa8
go/types.(*Checker).exprInternal(0xc0000f8160, 0xc000159400, 0x6f5618, 0xc0000a0e70, 0x0, 0x0, 0x7f8f4cb002a0)
	/home/lcaparelli/gitrepos/goroot/src/go/types/expr.go:1452 +0x2b53
go/types.(*Checker).rawExpr(0xc0000f8160, 0xc000159400, 0x6f5618, 0xc0000a0e70, 0x0, 0x0, 0xc00016e370)
	/home/lcaparelli/gitrepos/goroot/src/go/types/expr.go:1136 +0x85
go/types.(*Checker).exprOrType(0xc0000f8160, 0xc000159400, 0x6f5618, 0xc0000a0e70)
	/home/lcaparelli/gitrepos/goroot/src/go/types/expr.go:1893 +0x57
go/types.(*Checker).call(0xc0000f8160, 0xc000159400, 0xc0000be5c0, 0x9c92fe404566e490)
	/home/lcaparelli/gitrepos/goroot/src/go/types/call.go:107 +0x69
go/types.(*Checker).exprInternal(0xc0000f8160, 0xc000159400, 0x6f5258, 0xc0000be5c0, 0x0, 0x0, 0xc000159400)
	/home/lcaparelli/gitrepos/goroot/src/go/types/expr.go:1749 +0x1d8c
go/types.(*Checker).rawExpr(0xc0000f8160, 0xc000159400, 0x6f5258, 0xc0000be5c0, 0x0, 0x0, 0xc000159400)
	/home/lcaparelli/gitrepos/goroot/src/go/types/expr.go:1136 +0x85
go/types.(*Checker).multiExpr(0xc0000f8160, 0xc000159400, 0x6f5258, 0xc0000be5c0)
	/home/lcaparelli/gitrepos/goroot/src/go/types/expr.go:1868 +0x53
go/types.(*Checker).exprList(0xc0000f8160, 0xc00009e770, 0x1, 0x1, 0x6ed100, 0xc000100bd0, 0x7f8f4cc9f338, 0x8, 0x8)
	/home/lcaparelli/gitrepos/goroot/src/go/types/call.go:270 +0xb4
go/types.(*Checker).initVars(0xc0000f8160, 0xc0000baae8, 0x1, 0x1, 0xc00009e770, 0x1, 0x1, 0x0)
	/home/lcaparelli/gitrepos/goroot/src/go/types/assignments.go:235 +0x94
go/types.(*Checker).shortVarDecl(0xc0000f8160, 0x6f2418, 0xc00001c8a0, 0xc00009e700, 0x1, 0x1, 0xc00009e770, 0x1, 0x1)
	/home/lcaparelli/gitrepos/goroot/src/go/types/assignments.go:361 +0x27e
go/types.(*Checker).stmt(0xc0000f8160, 0x0, 0x6f50d8, 0xc0000be600)
	/home/lcaparelli/gitrepos/goroot/src/go/types/stmt.go:416 +0x38e5
go/types.(*Checker).stmtList(0xc0000f8160, 0x0, 0xc0000be740, 0x3, 0x4)
	/home/lcaparelli/gitrepos/goroot/src/go/types/stmt.go:125 +0xd1
go/types.(*Checker).funcBody(0xc0000f8160, 0xc00017e060, 0xc0000b85c4, 0x4, 0xc00017e120, 0xc0000a0ed0, 0x0, 0x0)
	/home/lcaparelli/gitrepos/goroot/src/go/types/stmt.go:42 +0x1f3
go/types.(*Checker).funcDecl.func1()
	/home/lcaparelli/gitrepos/goroot/src/go/types/decl.go:856 +0x69
go/types.(*Checker).processDelayed(0xc0000f8160, 0x0)
	/home/lcaparelli/gitrepos/goroot/src/go/types/check.go:305 +0x3e
go/types.(*Checker).checkFiles(0xc0000f8160, 0xc0000ba0d0, 0x1, 0x1, 0x0, 0x0)
	/home/lcaparelli/gitrepos/goroot/src/go/types/check.go:271 +0xdc
go/types.(*Checker).Files(...)
	/home/lcaparelli/gitrepos/goroot/src/go/types/check.go:254
go/types.(*Config).Check(0xc0000c1720, 0xc0000b8508, 0x4, 0xc0000be280, 0xc0000ba0d0, 0x1, 0x1, 0xc0000c13b0, 0x1, 0x1, ...)
	/home/lcaparelli/gitrepos/goroot/src/go/types/api.go:390 +0xa5
go/go2go.rewriteFilesInPath(0xc0000bc420, 0x0, 0x0, 0xc0000dc060, 0x17, 0xc00009e550, 0x1, 0x1, 0x0, 0x0, ...)
	/home/lcaparelli/gitrepos/goroot/src/go/go2go/go2go.go:97 +0x525
go/go2go.rewriteToPkgs(0xc0000bc420, 0x0, 0x0, 0xc0000dc060, 0x17, 0xc0000a0170, 0xc0000dc060, 0x17, 0x7ffc4591f03c, 0x8)
	/home/lcaparelli/gitrepos/goroot/src/go/go2go/go2go.go:50 +0x173
go/go2go.Rewrite(...)
	/home/lcaparelli/gitrepos/goroot/src/go/go2go/go2go.go:34
main.translate(0xc0000bc420, 0xc0000dc060, 0x17)
	/home/lcaparelli/gitrepos/goroot/src/cmd/go2go/translate.go:15 +0x49
main.main()
	/home/lcaparelli/gitrepos/goroot/src/cmd/go2go/main.go:85 +0xfbb
</pre></details>

**Comment by LCaparelli** [comment]
Also tried keeping both files in the `main` package, but still as separate files. It rendered the same result.

<details><summary><code>go tool go2go run main.go2</code> Output</summary><br><pre>
❯ bin/go tool go2go run main.go2
panic: /tmp/go2go-run772358554/main.go2:21:18: unknown expression type *ast.ListExpr [recovered]
	panic: /tmp/go2go-run772358554/main.go2:21:18: unknown expression type *ast.ListExpr

goroutine 1 [running]:
go/types.(*Checker).handleBailout(0xc0000ee160, 0xc0001179e8)
	/home/lcaparelli/gitrepos/goroot/src/go/types/check.go:249 +0xa5
panic(0x6597e0, 0xc00004c380)
	/home/lcaparelli/gitrepos/goroot/src/runtime/panic.go:972 +0x1d4
go/types.(*Checker).exprInternal(0xc0000ee160, 0xc0005004c0, 0x6f56d8, 0xc00009a180, 0x0, 0x0, 0x40)
	/home/lcaparelli/gitrepos/goroot/src/go/types/expr.go:1800 +0x4157
go/types.(*Checker).rawExpr(0xc0000ee160, 0xc0005004c0, 0x6f56d8, 0xc00009a180, 0x0, 0x0, 0xc0000c4420)
	/home/lcaparelli/gitrepos/goroot/src/go/types/expr.go:1136 +0x85
go/types.(*Checker).use(0xc0000ee160, 0xc000115d90, 0x1, 0x1)
	/home/lcaparelli/gitrepos/goroot/src/go/types/call.go:768 +0xa8
go/types.(*Checker).exprInternal(0xc0000ee160, 0xc0005003c0, 0x6f5618, 0xc00008ce70, 0x0, 0x0, 0x40da4a)
	/home/lcaparelli/gitrepos/goroot/src/go/types/expr.go:1452 +0x2b53
go/types.(*Checker).rawExpr(0xc0000ee160, 0xc0005003c0, 0x6f5618, 0xc00008ce70, 0x0, 0x0, 0xc0000b0180)
	/home/lcaparelli/gitrepos/goroot/src/go/types/expr.go:1136 +0x85
go/types.(*Checker).exprOrType(0xc0000ee160, 0xc0005003c0, 0x6f5618, 0xc00008ce70)
	/home/lcaparelli/gitrepos/goroot/src/go/types/expr.go:1893 +0x57
go/types.(*Checker).call(0xc0000ee160, 0xc0005003c0, 0xc0000b4640, 0x4766ea190a13b5c5)
	/home/lcaparelli/gitrepos/goroot/src/go/types/call.go:107 +0x69
go/types.(*Checker).exprInternal(0xc0000ee160, 0xc0005003c0, 0x6f5258, 0xc0000b4640, 0x0, 0x0, 0x40)
	/home/lcaparelli/gitrepos/goroot/src/go/types/expr.go:1749 +0x1d8c
go/types.(*Checker).rawExpr(0xc0000ee160, 0xc0005003c0, 0x6f5258, 0xc0000b4640, 0x0, 0x0, 0xc0005003c0)
	/home/lcaparelli/gitrepos/goroot/src/go/types/expr.go:1136 +0x85
go/types.(*Checker).multiExpr(0xc0000ee160, 0xc0005003c0, 0x6f5258, 0xc0000b4640)
	/home/lcaparelli/gitrepos/goroot/src/go/types/expr.go:1868 +0x53
go/types.(*Checker).exprList(0xc0000ee160, 0xc00008a790, 0x1, 0x1, 0x6ed100, 0xc000116bd0, 0x7f30d1af8328, 0x8, 0x8)
	/home/lcaparelli/gitrepos/goroot/src/go/types/call.go:270 +0xb4
go/types.(*Checker).initVars(0xc0000ee160, 0xc00000e1a8, 0x1, 0x1, 0xc00008a790, 0x1, 0x1, 0x0)
	/home/lcaparelli/gitrepos/goroot/src/go/types/assignments.go:235 +0x94
go/types.(*Checker).shortVarDecl(0xc0000ee160, 0x6f2418, 0xc00001c1f8, 0xc00008a720, 0x1, 0x1, 0xc00008a790, 0x1, 0x1)
	/home/lcaparelli/gitrepos/goroot/src/go/types/assignments.go:361 +0x27e
go/types.(*Checker).stmt(0xc0000ee160, 0x0, 0x6f50d8, 0xc0000b4680)
	/home/lcaparelli/gitrepos/goroot/src/go/types/stmt.go:416 +0x38e5
go/types.(*Checker).stmtList(0xc0000ee160, 0x0, 0xc0000b4800, 0x3, 0x4)
	/home/lcaparelli/gitrepos/goroot/src/go/types/stmt.go:125 +0xd1
go/types.(*Checker).funcBody(0xc0000ee160, 0xc0000b0840, 0xc0000ac5d0, 0x4, 0xc0000b0900, 0xc00008ced0, 0x0, 0x0)
	/home/lcaparelli/gitrepos/goroot/src/go/types/stmt.go:42 +0x1f3
go/types.(*Checker).funcDecl.func1()
	/home/lcaparelli/gitrepos/goroot/src/go/types/decl.go:856 +0x69
go/types.(*Checker).processDelayed(0xc0000ee160, 0x0)
	/home/lcaparelli/gitrepos/goroot/src/go/types/check.go:305 +0x3e
go/types.(*Checker).checkFiles(0xc0000ee160, 0xc0000ae0d0, 0x1, 0x1, 0x0, 0x0)
	/home/lcaparelli/gitrepos/goroot/src/go/types/check.go:271 +0xdc
go/types.(*Checker).Files(...)
	/home/lcaparelli/gitrepos/goroot/src/go/types/check.go:254
go/types.(*Config).Check(0xc0000b7770, 0xc0000ac508, 0x4, 0xc0000b4280, 0xc0000ae0d0, 0x1, 0x1, 0xc0000b73b0, 0x1, 0x1, ...)
	/home/lcaparelli/gitrepos/goroot/src/go/types/api.go:390 +0xa5
go/go2go.rewriteFilesInPath(0xc0000b0420, 0x0, 0x0, 0xc0000d2060, 0x17, 0xc00008a550, 0x1, 0x1, 0x0, 0x0, ...)
	/home/lcaparelli/gitrepos/goroot/src/go/go2go/go2go.go:97 +0x525
go/go2go.rewriteToPkgs(0xc0000b0420, 0x0, 0x0, 0xc0000d2060, 0x17, 0xc00008c170, 0xc0000d2060, 0x17, 0x7ffdb59be03c, 0x8)
	/home/lcaparelli/gitrepos/goroot/src/go/go2go/go2go.go:50 +0x173
go/go2go.Rewrite(...)
	/home/lcaparelli/gitrepos/goroot/src/go/go2go/go2go.go:34
main.translate(0xc0000b0420, 0xc0000d2060, 0x17)
	/home/lcaparelli/gitrepos/goroot/src/cmd/go2go/translate.go:15 +0x49
main.main()
	/home/lcaparelli/gitrepos/goroot/src/cmd/go2go/main.go:85 +0xfbb
</pre></details>

**Comment by ianlancetaylor** [comment]
Looks like on the go2go branch go/parser and go/types have gotten out of synch.  go/parser can generate an `ast.ListExpr` that go/types doesn't recognize.

I'm not sure how much effort we want to put into keeping the go2go branch up to date, but maybe this is an easy fix.  I'm not sure.

CC @griesemer @findleyr

**Comment by findleyr** [comment]
Thanks. This isn't so much a result of things going out of sync, as it is (or at least was) just a bug in go/types.

@griesemer and I have been discussing some ast API changes -- among other things to avoid this type of bug. Once that's settled, I'll merge back to the go2go branch.

**Comment by LCaparelli** [comment]
Awesome, thanks!
