### ISSUE TITLE
x/crypto: sha3 misleading and incorrect comment

### ISSUE THREAD

**Issue by nerdralph** [golang/go#45683]
https://github.com/golang/crypto/blob/master/sha3/sha3.go#L125

The Write function is not just used for SHAKE, it's also used for SHA-3.
The comment has a typo, it should say "after reading".  I suggest the line be changed to:
`// if more data is written after reading`

**Comment by nerdralph** [comment]
The proposed change still refers to "ShakeHash" even though the Write function is not specific to SHAKE.

**Comment by seankhliao** [comment]
right, updated

**Comment by cherrymui** [comment]
cc @FiloSottile

**Comment by FiloSottile** [comment]
The comment also says produces an error, but actually it will panic. The behavior is correctly documented on ShakeHash.

https://pkg.go.dev/golang.org/x/crypto/sha3#ShakeHash

**Comment by FiloSottile** [comment]
Done in https://go.dev/cl/526937
