### ISSUE TITLE
x/pkgsite: refuses to update to new module version

### ISSUE THREAD

**Issue by 89z** [golang/go#45703]
I publicly posted a new tag three hours ago:

https://github.com/89z/page/releases/tag/v1.3.7

I then tried this page, since the doc site had not updated:

https://pkg.go.dev/github.com/89z/page@v1.3.7

Then I get this:

~~~
Fetching github.com/89z/page@v1.3.7
Feel free to navigate away and check back later, we’ll keep working on it!

We're still working on “github.com/89z/page@v1.3.7”. Check back in a few minutes!
~~~

but the doc site never updates. I thought it might be something with the new version, so I made a change and pushed yet another version, `v1.3.8`. However neither version will load on the public doc site. My module is not that big, the `.go` files only account for 22 KB.

**Comment by 89z** [comment]
As a workaround, you can run `godoc` from the local module directory, then browse to something like this:

~~~
localhost:6060/pkg/github.com/89z/page
~~~

https://pkg.go.dev/golang.org/x/tools/cmd/godoc

**Comment by julieqiu** [comment]
Fixed.

**Comment by 89z** [comment]
https://github.com/golang/go/issues/46535
