### ISSUE TITLE
cmd/compile: function argument debug_info locations always wrong without GOEXPERIMENT=noregabi

### ISSUE THREAD

**Issue by aarzilli** [golang/go#45720]
<pre>
$ go version
go version devel go1.17-5963f0a332 Fri Apr 23 05:38:47 2021 +0000 linux/amd64
</pre>

For example with https://github.com/go-delve/delve/blob/master/_fixtures/issue573.go, the DIE for main.foo contains this:

``` <2><639c1>: Abbrev Number: 15 (DW_TAG_formal_parameter)
    <639c2>   DW_AT_name        : x
    <639c4>   DW_AT_variable_parameter: 0
    <639c5>   DW_AT_decl_line   : 17
    <639c6>   DW_AT_type        : <0x359e0>
    <639ca>   DW_AT_location    : 1 byte block: 9c      (DW_OP_call_frame_cfa)

```

Giving the location of argument x as DW_OP_call_frame_cfa, however this is not true until main.foo actually copies the argument (which is stored in a register) there:

```
	issue573.go:17	0x4965a0	4c8d6424e0		lea r12, ptr [rsp-0x20]
	issue573.go:17	0x4965a5	4d3b6610		cmp r12, qword ptr [r14+0x10]
	issue573.go:17	0x4965a9	0f867b010000		jbe 0x49672a
=>	issue573.go:17	0x4965af*	4881eca0000000		sub rsp, 0xa0
	issue573.go:17	0x4965b6	4889ac2498000000	mov qword ptr [rsp+0x98], rbp
	issue573.go:17	0x4965be	488dac2498000000	lea rbp, ptr [rsp+0x98]
	issue573.go:17	0x4965c6	48898424a8000000	mov qword ptr [rsp+0xa8], rax
	issue573.go:17	0x4965ce	48899c24b0000000	mov qword ptr [rsp+0xb0], rbx
	issue573.go:17	0x4965d6	48c744242800000000	mov qword ptr [rsp+0x28], 0x0
	issue573.go:18	0x4965df	488d4c2468		lea rcx, ptr [rsp+0x68]
```

the argument values aren't correct until 0x4965df and users trying to inspect them will see junk before that point. Delve also uses this information to implement call injection. I can see a few solutions to this:

1. move the prologue_end marker way down, until after the arguments have been saved. This would mean that call injection is still broken and would have to be disabled but users wouldn't generally see junk inside function arguments.
2. have callers do the saving to the stack after copying the arguments to registers if `-N` is specified, I believe this is what C compilers do when optimizations are turned off.
3. actually have a correct argument list for function arguments where function arguments have a register as location until they are saved to the stack
4. Have `-N` imply `GOEXPERIMENT=noregabi`

IMHO the preferred solution would be (2) or (3) because it makes call injection work and lets users debug something that still has regabi enabled, but I don't know if either is possible given the timeline.

Regarding (4): delve could easily specify GOEXPERIMENT itself when compiling however I think it should be implied by `-N`: we've been telling users that `-N -l` is what produces a binary that's easy to debug and with this it would be no longer true. I also don't think `-N` would be useful to anyone, without GOEXPERIMENT=noregabi.

cc @dr2chase

**Comment by thanm** [comment]
Hi, thanks for the heads up.

This is a problem we're aware of and actively working on; please stay tuned for developments.

At the moment with -N the compiler is emitting location expressions that describe where parameters would be if the register ABI were not turned on, which is clearly broken.

The tentative plan is to emit a 2-piece location for each register param, the first part in the ABI register and then the stack home for the remainder of the function. For the program you mentioned, the "-l -N" prolog looks like

```
/home/thanm/issue573.go:17
  47f660:       lea    -0x20(%rsp),%r12
  47f665:       cmp    0x10(%r14),%r12
  47f669:       jbe    47f7ea <main.foo+0x18a>
  47f66f:       sub    $0xa0,%rsp
  47f676:       mov    %rbp,0x98(%rsp)
  47f67e:       lea    0x98(%rsp),%rbp
  47f686:       mov    %rax,0xa8(%rsp)
  47f68e:       mov    %rbx,0xb0(%rsp)
  47f696:       movq   $0x0,0x28(%rsp)
```

So the plan is to have the location expression for "x" look something like:

```
    00087e80 ffffffffffffffff 000000000047f660 (base address)
    00087e90 000000000047f660 000000000047f686 (DW_OP_reg0 (rax))
    00087ea3 000000000047f68e 000000000047f6b9 (DW_OP_fbreg: -168)
```

or something to this effect. 

Debug call injection is a separate issue; on that front we will have to ask for changes from Delve, since the debug call injection interface provided by the runtime has had to change with the regabi.

**Comment by aarzilli** [comment]
Ok, sounds good, thank you.

**Comment by thanm** [comment]
@aarzilli  I've submitted my CLs, so in theory this issue should be fixed now. Let me know if it is ok to close, or if you want to hold it open pending additional testing, that's fine too. Thanks.

**Comment by aarzilli** [comment]
There's one last problem that I've found. Formal parameters need to appear inside a function's DIE in the same order as they appear in the argument list. For the most part this does happen however because of $GOROOT/src/cmd/compile/internal/dwarfgen/scope.go:48

```
sort.Stable(varsByScopeAndOffset{dwarfVars, varScopes})
```

this isn't always the case:

1. return arguments are always listed before all input arguments
2. if the compiler runs out of registers arguments passed on the stack will appear first

**Comment by thanm** [comment]
OK, thanks. This is not surprising given the various changes in frame offset for registerized outputs, etc. I'll look into sending a patch.

**Comment by aarzilli** [comment]
I tried just disabling the sort and it seems to work, but I do not know if the input order can be trusted in all cases (I think it used to be wrong).
