### ISSUE TITLE
Go test -json does not include which test passed or failed

### ISSUE THREAD

**Issue by TomMD** [golang/go#45725]
### What version of Go are you using (`go version`)?

```
go version go1.15.7 linux/amd64
```

### Does this issue reproduce with the latest release?

Probably

### What operating system and processor architecture are you using (`go env`)?

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build532697346=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

1. Clone a go repository
2. Change into the directory
3. Run `go test ./... -json`

### What did you expect to see?

I expect useful JSON output such as:

```
{ "Action" : "fail", "Package" : "foo", "Test" : "bar" }
```

### What did you see instead?
I see `fail` and `pass` actions without a `Test` field at all. What test failed?  How is this usable without that information?

**Comment by seankhliao** [comment]
are you looking for the `-v` flag?

**Comment by TomMD** [comment]
@seankhliao Thank you for the fast response. I recognize this might be PBKAC what with me picking bad test cases. Some repositories are better structured and do have tests which report out (with or without `-v`):

```
  {
    "Time": "2021-04-23T15:25:21.4729673Z",
    "Action": "pass",
    "Package": "github.com/tinkerbell/tink/workflow",
    "Test": "TestRenderTemplate/template_with_<<_should_not_be_escaped_in_any_way",
    "Elapsed": 0
  },
```

So there is the test field that I wasn't seeing in my original attempts.  Desired information is still lacking, such as file and line number of the test, but I can tackle that as a new investigation and perhaps issue.

This issue is clearly invalid, thanks!
