### ISSUE TITLE
x/build/cmd/release: update to FreeBSD-[amd64|386]-11_4 builder for 1.17 Beta

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#45727]
The cmd/release command is currently configured to use the freebsd-{amd64,386}-11_2 builders for the freebsd release targets.

FreeBSD 11.2 will not be supported by the time Go 1.17 is released. We should use FreeBSD 11.4 builders during the release.

/cc @golang/release

**Comment by dmitshur** [comment]
Using the latest "patch" release of the oldest "major" release of FreeBSD that we support for issuing Go 1.17 releases seems consistent with what we've done before, and SGTM.
