### ISSUE TITLE
cmd/compile: internal compiler error: InitTodoFunc still has declarations (with -G=3)

### ISSUE THREAD

**Issue by mccolljr** [golang/go#45722]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.17-105a6e9518 Fri Apr 23 11:33:03 2021 +0000 darwin/amd6
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jmccollum/Library/Caches/go-build"
GOENV="/Users/jmccollum/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jmccollum/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jmccollum/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/jmccollum/go/src/github.com/golang/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/jmccollum/go/src/github.com/golang/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="devel go1.17-105a6e9518 Fri Apr 23 11:33:03 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jmccollum/go/src/github.com/golang/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0d/ncmx73fn4s1_n9bz83jdl0lh0000gn/T/go-build2307230618=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```go
package main

import (
	"fmt"
	"log"
)

func try[T any](v T, err error) T {
	if err != nil {
		panic(err)
	}
	return v
}

func handle(handle func(error)) {
	if issue := recover(); issue != nil {
		if e, ok := issue.(error); ok && e != nil {
			handle(e)
		} else {
			handle(fmt.Errorf("%v", e))
		}
	}
}

func main() {
	defer handle(func(e error) { log.Fatalln(e) })
	_ = try(fmt.Println("test"))
}

```

### What did you expect to see?
Program compiles and runs with no output

### What did you see instead?
Program fails to compile with an internal compiler error:
```
<unknown line number>: internal compiler error: InitTodoFunc still has declarations

goroutine 1 [running]:
runtime/debug.Stack()
        /Users/jmccollum/go/src/github.com/golang/go/src/runtime/debug/stack.go:24 +0x65
cmd/compile/internal/base.FatalfAt({0xa2b00, 0xc0}, {0x1934032, 0x191a737}, {0x0, 0x10000000100cc5b, 0x22097f0})
        /Users/jmccollum/go/src/github.com/golang/go/src/cmd/compile/internal/base/print.go:227 +0x157
cmd/compile/internal/base.Fatalf(...)
        /Users/jmccollum/go/src/github.com/golang/go/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/pkginit.Task()
        /Users/jmccollum/go/src/github.com/golang/go/src/cmd/compile/internal/pkginit/init.go:66 +0x8b6
cmd/compile/internal/gc.Main(0x1949ab8)
        /Users/jmccollum/go/src/github.com/golang/go/src/cmd/compile/internal/gc/main.go:197 +0xb38
main.main()
        /Users/jmccollum/go/src/github.com/golang/go/src/cmd/compile/main.go:55 +0xdd
```

**Comment by mccolljr** [comment]
This is the code section that is triggering the failure:
https://github.com/golang/go/blob/a956a0e909e1d60c8d55339e5e591a9d1db885c4/src/cmd/compile/internal/pkginit/init.go#L62-L67

I will do a bit more digging.

**Comment by mccolljr** [comment]
This is being generated directly from `gc.Main`:

https://github.com/golang/go/blob/95ed5c3800a87ddf9b0ec3958eaaa1a969306293/src/cmd/compile/internal/gc/main.go#L196-L199

The decls that are causing the panic seem to be the intermediate variables in the call `_ = try(fmt.Println("test"))`
```
.   NAME-main..autotmp_0 esc(N) Class:PAUTO Offset:0 AutoTemp OnStack Used int
.   NAME-main..autotmp_1 esc(N) Class:PAUTO Offset:0 AutoTemp OnStack Used error
```

**Comment by cherrymui** [comment]
cc @griesemer @mdempsky @findleyr

**Comment by griesemer** [comment]
Clearly related to the new code dealing with generic functions. Replacing the generic `try` function with:
```Go
func try(v int, err error) int {
	if err != nil {
		panic(err)
	}
	return v
}
```
makes the error go away.
