### ISSUE TITLE
x/net/route: FetchRIB can fail with "sysctl: cannot allocate memory"

### ISSUE THREAD

**Issue by bradfitz** [golang/go#45736]
x/net/route.FetchRIB on darwin and other BSDs can fail with "sysctl: cannot allocate memory".

Apparently this means that there was a race inside the kernel: it calculated the size of the routing table, allocated some memory, the routing table changed, and then it failed.

(see e.g. https://lists.freebsd.org/pipermail/freebsd-current/2014-February/048416.html)

Empirically, a retry loop around it fixes it.

During a long stress test, 1 retry was usually all it took to get a non-error result after an error. I only saw a few occurrences of 2 and one 3.

**Comment by cherrymui** [comment]
cc @ianlancetaylor
