### ISSUE TITLE
x/tools/gopls: address formatting issues with go-diff@v1.2.0

### ISSUE THREAD

**Issue by findleyr** [golang/go#45732]
In #45648, we discovered that gopls has formatting bugs when built with github.com/sergi/go-diff@v1.2.0. Unfortunately, there are probably many users that get this version due to installing with `go get -u`.

Until https://github.com/sergi/go-diff/issues/115 is fixed, or we find some other solution, we should at least warn users when built with go-diff@v1.2.0.

CC @stamblerre @heschi

**Comment by stamblerre** [comment]
I don't think there's anything to do here. All that remains is waiting for https://github.com/sergi/go-diff/pull/120 to be merged.

**Comment by FrankFang** [comment]
What's the correct way to install x/tools/gopls?

**Comment by findleyr** [comment]
See https://github.com/golang/tools/tree/master/gopls#installation

```
GO111MODULE=on go get golang.org/x/tools/gopls@latest
```

**Comment by OscarVanL** [comment]
The VS Code Go Extension has started complaining about a bad gopls installation, linking to this issue.

I tried running the command suggested by VS Code to fix it (same as above) but it says:

```
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

If I run `go install golang.org/x/tools/gopls@latest`I get no console output whatsoever and the error message does not go away.

Any idea what to do? Lots of stuff seems to be misbehaving. When I have the `"go.useLanguageServer": true,`option set VS Code will give incorrect errors on every third-party import, such as:

```
"gopkg.in/yaml.v3" imported but not usedcompilerUnusedImport
could not import gopkg.in/yaml.v3 (cannot find package "gopkg.in/yaml.v3" in any of 
	/usr/local/Cellar/go/1.17.1/libexec/src/gopkg.in/yaml.v3 (from $GOROOT)
	/Users/oscarvanleusen/go/src/gopkg.in/yaml.v3 (from $GOPATH))
```

However, this library must be installed as the code compiles fine (and yaml functions work). If I disable the language server the warning goes away.

Here's my settings.json file.

```
{
    "workbench.colorTheme": "Default Dark+",
    "files.autoSave": "afterDelay",
    "go.useLanguageServer": true,
    "go.languageServerExperimentalFeatures": {
            "diagnostics": true // for diagnostics as you type
    },
    "[go]": {
        "editor.insertSpaces": false,
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
        "editor.suggest.snippetsPreventQuickSuggestions": false
    },
    
    "go.liveErrors": {
        "enabled": true,
        "delay": 500
    },
    "go.lintTool": "revive",
    "go.toolsManagement.autoUpdate": true,
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "gopls": {

        "usePlaceholders": true, // add parameter placeholders when completing a function
    },
}
```

I've spent ages trying to get Go to work properly on my Mac with VS Code, but am close to giving up and trying Goland. Any suggestions?

**Comment by stamblerre** [comment]
@OscarVanL: Please take a look at the [Troubleshooting guide](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md) and open a new issue if that doesn't help you solve the problem.
