### ISSUE TITLE
Can't install the git-codereview command on mac, using contribution guide docs

### ISSUE THREAD

**Issue by roointan** [golang/go#45730]
Hello. I've tried installing git-codereview on my mac, using the provided command in Contribution Guide, but it doesn't work for me. Can somebody help me set it up?

I tried running go get -u golang.org/x/review/git-codereview
but can't get codereview to work.
I get this:
git: 'codereview' is not a git command. See 'git --help'.
Can somebody help me please?

### What version of Go are you using (`go version`)?

<pre>
go version go1.16.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/paiman/Library/Caches/go-build"
GOENV="/Users/paiman/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/paiman/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/paiman/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hs/6y9r9n0j75qfvv7gsb10kz6r0000gn/T/go-build2632970588=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
I tried running:

go get -u golang.org/x/review/git-codereview
(even with a sudo)

### What did you expect to see?
the help text

### What did you see instead?
git: 'codereview' is not a git command. See 'git --help'.

**Comment by seankhliao** [comment]
is $GOPATH/bin in your $PATH?

**Comment by roointan** [comment]
> is $GOPATH/bin in your $PATH?

I did this to install go on my mac:
https://golang.org/doc/install

$GOPATH is not set.
But I have /usr/local/go/bin in my $PATH
Do I need to explicitly set $GOPATH for this to work?

(documentations seem incomplete IMHO)

**Comment by roointan** [comment]
For anyone having this same issue, Seems $GOPATH is the workspace directory.

these will help:
https://golang.org/doc/code#GOPATH

**Comment by seankhliao** [comment]
The contributing guide covers this:

> Make sure git-codereview is installed in your shell path, so that the git command can find 

and in general assumes you have a Go development environment setup.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
