### ISSUE TITLE
x/review/git-codereview: complains about _content dir in x/website

### ISSUE THREAD

**Issue by seankhliao** [golang/go#45734]
`messageRE` in `git-codereview` is used to validate the commit message title, but this doesn't play nice with the new `_content/` directory in x/website.

```go
var messageRE = regexp.MustCompile(`^(\[[a-zA-Z0-9.-]+\] )?[a-zA-Z0-9-/,. ]+: `)
```

**Comment by cherrymui** [comment]
cc @kevinburke @rsc
