### ISSUE TITLE
embed: guarantee `(*FS).Open`'s returning value implements `io.Seeker`

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#45745]
From the current document, there is no guarantee whether `(*embed.FS).Open`'s returning value implements `io.Seeker` or not.

> Open opens the named file for reading and returns it as an fs.File.

IIUC the returned value always implements `io.Seeker` in the current implementation, and actually it is fine to assume this (e.g., https://github.com/golang/go/issues/44175#issuecomment-775545730). Would it be possible to make the current behavior explicit in the document?

**Comment by hajimehoshi** [comment]
CC @ianlancetaylor

**Comment by josharian** [comment]
Embedded directories do not implement Seek. (This bit me yesterday.)

**Comment by hajimehoshi** [comment]
Ah, I see. So I want a guarantee that `(*embed.FS).Open` returns a `fs.File` that implements `io.Seeker` when the returned value is a file, not a directory.

**Comment by josharian** [comment]
Yep. Or we could make directories seekers too, I guess.

**Comment by ianlancetaylor** [comment]
I think it would be fine to document that the result of `embed.FS.Open`, when opening a file that is not a directory, will implement `io.Seeker`.

**Comment by ianlancetaylor** [comment]
This doesn't have to be a proposal, so taking it out of the proposal process.

**Comment by hajimehoshi** [comment]
> Yep. Or we could make directories seekers too, I guess.

This sounds better to me, as `*os.File` has `Seek` even for directories. Always panicking at `openDir.Seek` should be fine.

> I think it would be fine to document that the result of embed.FS.Open, when opening a file that is not a directory, will implement io.Seeker.

Hmm, always having `Seek` sounds less confusing. What do you think?

**Comment by tmthrgd** [comment]
While it might be true currently, wouldn’t adopting this make it impossible/much-more-difficult for the compiler to change how embedded files are stored? For instance to automatically compress them. I seem to recall being able to decide that kind of thing at a later time was part of the original proposal or discussion.

**Comment by ianlancetaylor** [comment]
I suppose I don't see a reason to support `Seek` for embedded directories.  And we don't support it today.

Since we already support `Seek` for embedded files, it's going to be pretty hard to change that.  We can still compress the embedded data, we'll just have to decompress the entire file if it is opened.
