### ISSUE TITLE
go vet fails variadic args when explicit argument indexes are used

### ISSUE THREAD

**Issue by anacrolix** [golang/go#45742]
### What version of Go are you using (`go version`)?

go1.16.3

### Does this issue reproduce with the latest release?

Yes, with go version devel go1.17-4efd581383 Sun Apr 18 17:40:12 2021 +0000 darwin/amd64.

### What did you do?

https://play.golang.org/p/IRRf_3P24mQ

### What did you expect to see?
```
hello, world!
Program exited.
```
### What did you see instead?
```
./prog.go:9:2: Printf format has invalid argument index [2]
Go vet exited.

hello, world!
Program exited.
```

Note that it doesn't complain if the first argument index used is `[1]`. Also note that this *fails* tests, despite them passing just fine otherwise.

**Comment by josharian** [comment]
Nice find. Seems like vet has to assume any index >=1 is valid when used with varargs.

**Comment by josharian** [comment]
Optimistically marking 1.17, as this should be an easy fix. Might be a good project for a new contributor interested in vet.

**Comment by barudwale20** [comment]
@josharian I would like to pick this issue and fix it.

**Comment by josharian** [comment]
Great. Feel free to ask here if you have any questions. Note that the freeze starts in a week, so if we want this fixed in 1.17, we have to move fast. It's also ok to miss the freeze, but it means it won't go in for at least three months.

**Comment by barudwale20** [comment]
Sure @josharian, I will make sure that this fix won't miss the freeze date. Thanks for the update.

**Comment by cherrymui** [comment]
Dup of #34007. Thanks.
