### ISSUE TITLE
Cgo undefined reference to `myCfunction`

### ISSUE THREAD

**Issue by exapsy** [golang/go#45741]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/exapsy/.cache/go-build"
GOENV="/home/exapsy/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/exapsy/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/exapsy/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/exapsy/tmp/golang/compile_c/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1794320692=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

greeter.c

```c
#include "greeter.h"

#include <stdio.h>

int greet(const char *name, int year, char *out) {
	int n;

	n = sprintf(out, "Greetings, %s from %d! We come in peace :)", name,
		    year);

	return n;
}
```

greeter.h

```c
#ifndef GREETER_H
#define GREETER_H

int greet(const char *name, int year, char *out);

#endif
```

main.go

```golang
package main

/*
#cgo CFLAGS: -g -Wall
#include <stdio.h>
#include <stdlib.h>
#include "greeter.h"
*/
import "C"

import (
	"fmt"
	"unsafe"
)

func main() {
	name := C.CString("Gopher lul")
	defer C.free(unsafe.Pointer(name))

	year := C.int(2018)

	ptr := C.malloc(C.sizeof_char * 1024)
	defer C.free(unsafe.Pointer(ptr))

	size := C.greet(name, year, (*C.char)(ptr))

	b := C.GoBytes(ptr, size)
	fmt.Println(string(b))
}
```

From what I see, `greeter.c` is also imported correctly by cgo. So I do not get why it can't find a definition
```
$ go list
......
        "CgoFiles": [
                "main.go"
        ],
        "CFiles": [
                "greeter.c"
        ],
        "HFiles": [
                "greeter.h"
        ],
        "CgoCFLAGS": [
                "-g",
                "-Wall"
        ],
        "Imports": [
                "C",
                "fmt",
                "unsafe"
        ],
......
```

Run gcc compile to see if it compiles

```
$ gcc -c greeter.c
<successful - no output>
```

### What did you expect to see?

```
Greetings, Gopher from 2018! We come in peace :)
```

### What did you see instead?

Output:

```
$ go run ./main.go
# command-line-arguments
/usr/bin/ld: $WORK/b001/_x002.o: in function `_cgo_035103a157b9_Cfunc_greet':
/tmp/go-build/cgo-gcc-prolog:68: undefined reference to `greet'
collect2: error: ld returned 1 exit status
```

### Successful things I've tried

- Wrote the initialization of the function directly to the `greeter.h`, which worked
- Wrote the initialization inside `main.go` also worked

But for some reason placing the code only to `greeter.c` doesn't work. Everywhere else it does.

**Comment by AlexRouSg** [comment]
`go run ./main.go` will build only `main.go` and not include `greeter.c`
you need to do `go run .`

**Comment by exapsy** [comment]
@AlexRouSg  You're right, that solved it!
