### ISSUE TITLE
godoc cannot be run in GOPATH mode

### ISSUE THREAD

**Issue by 89z** [golang/go#45750]
~~~
go version go1.16.3 windows/amd64
~~~

I am trying to run this command [1]:

~~~
godoc -analysis=pointer
~~~

but I get this result:

~~~
using module mode; GOMOD=NUL
The -analysis flag is supported only in GOPATH mode at this time.
See https://golang.org/issue/34473.
~~~

Ok, fine, I will run in `GOPATH` mode. But how do I do that? I checked the code, and it seem the error only happens, if `-analysis` is used, and `GOMOD` is not empty [2]. That happens to be my situation:

~~~
PS C:\> go env GOMOD
NUL
~~~

So fine, I will change it to empty value:

~~~
PS C:\> go env -w GOMOD=
go env -w: GOMOD cannot be modified
~~~

Hm. So how do I do this?

1. https://golang.org/lib/godoc/analysis/help.html
2. https://github.com/golang/tools/blob/f74a6698/cmd/godoc/main.go#L208-L215

**Comment by 89z** [comment]
https://github.com/golang/go/issues/34473

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by 89z** [comment]
Looks like changing this line [1]:

~~~go
if goModFile != "" {
~~~

to this:

~~~go
if goModFile != "NUL" {
~~~

fixes the issue. PS @seankhliao, I really appreciate the way you robotically closed the issue with a boilerplate response!

1. https://github.com/golang/tools/blob/f74a6698/cmd/godoc/main.go#L208
