### ISSUE TITLE
Can't install delve on Win64

### ISSUE THREAD

**Issue by sudosandwich** [golang/go#45755]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\chris\AppData\Local\go-build
set GOENV=C:\Users\chris\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\chris\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\chris\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\tools\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\tools\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.3
set GCCGO=gccgo
set GO386=sse2
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=Z:\gak\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\tools\external\babun\.babun\cygwin\tmp\go-build1600398147=/tmp/go-build -gno-record-gcc-switches
lldb --version: lldb version 10.0.0
gdb --version: GNU gdb (GDB) (Cygwin 8.1.1-1) 8.1.1
</pre></details>

### What did you do?
Try to install delve via:
╭─chris@host /z/gak
╰─$ go install -v github.com/go-delve/delve/cmd/dlv@latest
C:\Users\chris\go\pkg\mod\github.com\go-delve\delve@v1.6.0\service\debugger\debugger.go:26:2: found packages native (proc.go) and your_operating_system_and_architecture_combination_is_not_supported_by_delve (support_sentinel.go) in C:\Users\chris\go\pkg\mod\github.com\go-delve\delve@v1.6.0\pkg\proc\native

### What did you expect to see?
Installation suceeded

### What did you see instead?
C:\Users\chris\go\pkg\mod\github.com\go-delve\delve@v1.6.0\service\debugger\debugger.go:26:2: found packages native (proc.go) and your_operating_system_and_architecture_combination_is_not_supported_by_delve (support_sentinel.go) in C:\Users\chris\go\pkg\mod\github.com\go-delve\delve@v1.6.0\pkg\proc\native

**Comment by davecheney** [comment]
Thank you for raising this issue. Please discuss this with the delve developer at GitHub.com/go-delve/delve.
