### ISSUE TITLE
testing: document that TestMain always runs before any benchmarks

### ISSUE THREAD

**Issue by opennota** [golang/go#45764]
The docs for `TestMain` say:

```
It is sometimes necessary for a test program to do extra setup
or teardown before or after testing.
```

https://golang.org/pkg/testing/#hdr-Main

But what if one needs to do extra setup before benchmarking? It appears that `TestMain` would also always run before benchmarks, but neither `TestMain` doc nor `M.Run` doc say anything about benchmarks.

**Comment by cherrymui** [comment]
cc @mpvl @bcmills
