### ISSUE TITLE
text/template: doc: `define` action is not listed and described in "Actions" section

### ISSUE THREAD

**Issue by kidlj** [golang/go#45762]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you expect to see?

In text/template [doc page](https://golang.org/pkg/text/template/), `define` action should be officially listed in 'Actions' section.

### What did you see instead?

In text/template [doc page](https://golang.org/pkg/text/template/), `define` action is described in a separate section, named ["Nested template definitions"](https://golang.org/pkg/text/template/#hdr-Nested_template_definitions), however, as an action, it's not listed in the ["Actions"](https://golang.org/pkg/text/template/#hdr-Actions) section as other actions do. It should also be there.

**Comment by cherrymui** [comment]
cc  @robpike @mvdan
