### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by lekan-pvp** [golang/go#45779]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.16
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 20.04 amd64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
run example on site under func os.WriteFile

https://play.golang.org/p/mCCjFLaE9Ua

### What did you expect to see?
nothing

### What did you see instead?
2009/11/10 23:00:00 open testdata/hello: no such file or directory

**Comment by cherrymui** [comment]
Thanks for reporting. See #9679. Closing as a dup..
