### ISSUE TITLE
doc/go1.17: document closure inlining affects function PC comparison

### ISSUE THREAD

**Issue by rski** [golang/go#45781]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.17-d5d24dbe41 Mon Apr 26 17:13:36 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

only master

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
~/go/src/playground/at-2021-04-26-204402 $ ~/Code/go/bin/go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rski/.cache/go-build"
GOENV="/home/rski/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/rski/go/pkg/mod"
GONOPROXY=""
GONOSUMDB="="
GOOS="linux"
GOPATH="/home/rski/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/rski/Code/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/rski/Code/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.17-d5d24dbe41 Mon Apr 26 17:13:36 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/home/rski/go/src/playground/at-2021-04-26-204402/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2782832869=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/Yw1lgRph4Kd

### What did you expect to see?

This should print `main.WithFoo.func1`, as with go 16.3

### What did you see instead?

After the regabi branch merge, this prints 

main.init.func1

This was temporarily fixed by 1129a60f1c1e64147ca1133857c4571ce9b87a35, which disabled inlining of functions that contain closures.

**Comment by cherrymui** [comment]
cc @danscales for inlining closures.

This is working as intended. We probably need to document it better.

**Comment by rski** [comment]
`This is working as intended.` interesting. The reason I figured out this happened is because it broke some code. It uses reflect like this to figure out if a test was passed a specific opt function, and the inlined version no longer compares equal with the non inlined version. Is this use pushing it and not covered by the compatibility guarantee?

**Comment by cherrymui** [comment]
Comparing PCs of functions is never intended to work (e.g. `func` values are incomparable). It may happen to work in some  cases, but not guaranteed to work.

**Comment by rski** [comment]
heh, I'm surprised we got away with it for so many go versions then. Thanks for the quick response, I'll replace the code with something less brittle.

**Comment by dmitshur** [comment]
@cherrymui Do you where a good place to document this might be?

**Comment by cherrymui** [comment]
I think it's better in the release notes. @danscales may already have a CL.

**Comment by dmitshur** [comment]
@danscales, if you don't mind I'll make you an assignee on this issue, but please feel free to update it if you're not able to get to this.

**Comment by danscales** [comment]
I already sent this text to Jeremy about a week ago:

Functions containing closures can now be inlined.  One effect of this change is that a function returning a constant closure may actually return a different closure function for each place that it is inlined.  Hence, this change could reveal bugs where Go functions are compared (incorrectly) by (unsafe) pointer value.  Go functions are by definition not comparable.

Is there a place that I should put this in the release notes (I'm not sure how to do it), or @cherrymui  do you want to just grab it (since I think you are collecting release notes).

**Comment by dmitshur** [comment]
Thank you Dan.

We can probably place that as a paragraph in the Runtime section at https://tip.golang.org/doc/go1.17#runtime. The corresponding file is here:

https://github.com/golang/go/blob/217f5dd496e14f0e0617c9efe0509073dec95d61/doc/go1.17.html#L214-L222
