### ISSUE TITLE
access: 

### ISSUE THREAD

**Issue by bufflig** [golang/go#45788]
See https://golang.org/wiki/GerritAccess

I would like "approvers" access (https://go-review.googlesource.com/#/admin/groups/1005,members) for my corp account pnyb@google.com.

**Comment by cagedmantis** [comment]
Hi Patrik,

Thank you for contributing to the Go project! You've been added to the may-start-trybots and approvers groups now.

Please be familiar with the rules for voting and submitting changes as described at https://golang.org/wiki/GerritAccess#approver-access-approvers. If you're unsure or have any questions, please don't hesitate to ask us.

Additionally, as described at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a trybot run.

Thank you again for contributing, your help is greatly appreciated!
