### ISSUE TITLE
encoding/json: Proposal - Flexible omitempty

### ISSUE THREAD

**Issue by PumpkinSeed** [golang/go#45787]
Questions unrelated.

I run into the issue where I wanted to omitempty a non-pointer struct. I couldn't make it happen properly so I think about a solution. So [this](https://go.googlesource.com/go/+/refs/heads/master/src/encoding/json/encode.go#341) is the code running I guess when there is the omitempty tag on the field. What if it would check for an extra interface implementation where we can flexibly determine when we consider a non-pointer struct as empty?

So use-case in [this](https://play.golang.org/p/Bz_MQIhWy4d) playground. It seems that the empty struct marshalled into the JSON. But if the Go has an interface like below I can implement this and the linked source can look for that implementation. If no any implementation than go with the default.

```
type Something interface {
  IsEmpty() bool
}
```

**Comment by ianlancetaylor** [comment]
Dup of #32675, see discussion at #11939.
