### ISSUE TITLE
pprof: source view is always blank at tip (due to upstream pprof bug)

### ISSUE THREAD

**Issue by zikaeroh** [golang/go#45786]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.17-0d1280c685 Mon Apr 26 18:54:39 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

On tip, yes, in Go 1.16, no.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jake/.cache/go-build"
GOENV="/home/jake/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jake/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jake/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/jake/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/jake/sdk/gotip/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.17-0d1280c685 Mon Apr 26 18:54:39 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4162563244=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version devel go1.17-0d1280c685 Mon Apr 26 18:54:39 2021 +0000 linux/amd64
GOROOT/bin/go tool compile -V: compile version devel go1.17-0d1280c685 Mon Apr 26 18:54:39 2021 +0000
uname -sr: Linux 5.11.16-zen1-1-zen
/usr/lib/libc.so.6: GNU C Library (GNU libc) release release version 2.33.
gdb --version: GNU gdb (GDB) 10.1
</pre></details>

### What did you do?

```
$ gotip test -run=- -bench 'Write' -benchmem -cpuprofile cpu.out -memprofile mem.out encoding/csv
$ gotip tool pprof -http=: mem.out
```

Then navigate to the "source" view at the top left.

### What did you expect to see?

A page containing the source of the benchmarked code.

### What did you see instead?

The source page is always empty with Go profiles.

This issue is technically https://github.com/google/pprof/issues/621, but as pprof is vendored into Go and the current version is broken (and the freeze is quite soon), I wanted to ensure this was triaged here.

**Comment by ALTree** [comment]
Thanks for reporting this, let's label this as a 1.17 `release-blocker` to make sure than when (if) the bug is fixed upstream, we vendor the fix before the 1.17 release.
