### ISSUE TITLE
sync: internal/poll.TestSplicePipePool fails on 32-bit platforms after sync.Pool CL 303949

### ISSUE THREAD

**Issue by cherrymui** [golang/go#45782]
After CL 303949 , there are a few failures for internal/poll.TestSplicePipePool fails on 32-bit platforms, e.g.

https://build.golang.org/log/6063d1764ac5d5c3644528362f002fb0a8a685d6   386
https://build.golang.org/log/de4fd7cd548eb95d0c76efc7d72513bdecf389d4   ARM
https://build.golang.org/log/19f144a0780b4f29d1533079c9141022de5d5672   MIPS

And internal/poll.Splice does use sync.Pool. So this CL is probably related.

@dr2chase @kels-ng

**Comment by bcmills** [comment]
See previously #45059 (CC @panjf2000 @ianlancetaylor @bradfitz).

**Comment by bcmills** [comment]
This also seems to be affecting some TryBot platforms (such as `linux-arm-aws`):
https://storage.googleapis.com/go-build-log/ea802e88/linux-arm-aws_4aeefd09.log

**Comment by bcmills** [comment]
Fixed by revert in [CL 313630](https://golang.org/cl/313630).
