### ISSUE TITLE
Leading zero in floating-point literals

### ISSUE THREAD

**Issue by delasy** [golang/go#45791]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/aaron/Library/Caches/go-build"
GOENV="/Users/aaron/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/aaron/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/aaron/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cm/2hc599zd3b70hs4kn9cntvh40000gn/T/go-build1836913933=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
```go
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello, playground", 0777., 0777, 0_777., 0_777)
}
```

### What did you expect to see?
```txt
Hello, playground 511 511 511 511
```
Or
```txt
Error: invalid radix point in octal literal
```

### What did you see instead?
```txt
Hello, playground 777 511 777 511
```

**Comment by delasy** [comment]
As [specification](https://golang.org/ref/spec#Slice_expressions) says, float can start with zero. At the same time integers starting with zero are octals. Ability to have floating-point literals starting with zero acting as decimals confuses me, and in my opinion should throw an error `invalid radix point in octal literal`. I'll be more than happy to open PR to fix this 🙂

**Comment by ianlancetaylor** [comment]
Unfortunately this is not something that we can change, as it would break the [Go 1 compatibility guidelines](https://golang.org/doc/go1compat.html).

This behavior is among the reasons that we introduced the `0o` prefix for octal numbers in the Go 1.13 release.

Closing because there isn't anything we can do here.
