### ISSUE TITLE
x/tools/gopls: evaluate hex/binary integer literals when mousing over

### ISSUE THREAD

**Issue by soypat** [golang/go#45802]
### What version of Go are you using (`go version`)?

<pre>
$ gopls version
golang.org/x/tools/gopls v0.6.10
    golang.org/x/tools/gopls@v0.6.10 h1:8Ebz8PymS2umcuCFhoz67unyJfWsipjTIrkBUF9kypg=

$ VsCode settings:
 "gopls": {	
        "ui.semanticTokens": true,
	},
    "editor.semanticHighlighting.enabled": true,
</pre>

### What did you do?

Mouse over a hex/binary notation integer 
```go
var (

    hex = 0xe34e
    bigBin = 0b1001001
    x = hex*0b1101
)
```

### What did you expect to see?
Gopls evaluate the number in decimal form and show me the result (I'm in VSCode). Gopls does this for `const` identifiers and it is super helpful!

### What did you see instead?
Nothing

**Comment by danishprakash** [comment]
I'd like to work on this cc: @stamblerre

**Comment by stamblerre** [comment]
@danishprakash: Sounds good! Let me know if you need any guidance.

**Comment by danishprakash** [comment]
@stamblerre I tried dabbling with this and have pushed my changes here https://github.com/golang/tools/compare/master...danishprakash:hover-evaluate-hex?expand=1. Let me know if that approach sounds good, I'll raise a pull request.

**Comment by stamblerre** [comment]
Thanks for working on that @danishprakash! It does look like the right approach so feel free to send a PR.

**Comment by danishprakash** [comment]
Posting the PR link here https://go-review.googlesource.com/c/tools/+/330309, not sure if the bot would backlink this. (ideally we should)
