### ISSUE TITLE
x/build: windows-arm-zx2c4 builder missing

### ISSUE THREAD

**Issue by dmitshur** [golang/go#45810]
The `windows-arm-zx2c4` builder is currently missing. From https://farmer.golang.org/#pools:

```
host-windows-arm64-zx2c4: 0/0 (1 missing)
```

@zx2c4 Are you able to take a look? Thank you.

CC @golang/release.

**Comment by zx2c4** [comment]
Should be handled.

**Comment by dmitshur** [comment]
Thank you.
