### ISSUE TITLE
go/types, types2: better error message for incompatible types due to method signature mismatch

### ISSUE THREAD

**Issue by griesemer** [golang/go#45813]
See the example in issue #42841.

`go/types` and `types2` produce an even less explicit error message. Match the compiler.

**Comment by griesemer** [comment]
cc: @findleyr

**Comment by odeke-em** [comment]
Howdy @griesemer and @findleyr! My CL https://go-review.googlesource.com/c/go/+/373634/ I believe fixes this issues to as it is now for go/types2, cmd/compile/types2 so let me update its commit message.
