### ISSUE TITLE
x/pkgsite: remove unintended package

### ISSUE THREAD

**Issue by fgergo** [golang/go#45821]
According to https://go.dev/about 
"If you are the author of a package and would like to have it removed from pkg.go.dev, please file an issue on the Go Issue Tracker with the path that you want to remove."

I inadvertantly pushed github.com/fgergo/np2stdio. I should have pushed github.com/fgergo/us2stdio, which I did later.

Please remove github.com/fgergo/np2stdio from pkg.go.dev.
Thanks!

**Comment by jba** [comment]
Done.
