### ISSUE TITLE
test: fuse.go consistently failing on noopt builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#45824]
The `fuse.go` test added in [CL 244737](https://golang.org/cl/244737) is consistently failing on the `noopt` builder:

```
# go run run.go -- fuse.go

fuse.go:178: no match for `Redirect Phi based on Phi$` in:
	fuse.go:178: Redirect SelectN based on SelectN
Unmatched Errors:
fuse.go:178: Redirect SelectN based on SelectN

FAIL	fuse.go	0.162s
```

[2021-04-28T12:51:42-f68878f/linux-amd64-noopt](https://build.golang.org/log/e4eceffcb96649ccced5a63cc3695707b9dc8b1e)
[2021-04-28T02:39:09-92d1afe/linux-amd64-noopt](https://build.golang.org/log/a6576ddf001ce47eb1726f1d7f5c1a11422b2e1a)

CC @randall77 @erifan

**Comment by dmitshur** [comment]
Fixed by [CL 314632](https://golang.org/cl/314632). Thanks @bcmills for reporting and @cherrymui for fixing.

**Comment by erifan** [comment]
Sorry for introducing the bug and thanks for reporting and fixing it.
