### ISSUE TITLE
x/website: anchor link broken in golang website mod.md

### ISSUE THREAD

**Issue by zihengCat** [golang/go#45828]
An anchor link URL broken in `website/_content/doc/mod.md` line 3038. 
Missing the doc: ***Why does "go get" use HTTPS when cloning a repository?***
> https://github.com/golang/website/blob/master/_content/doc/mod.md

**Comment by cherrymui** [comment]
x/website is supposed to be used for the golang.org website. The link is not broken there. https://golang.org/ref/mod#private-module-repo-auth

Closing. Thanks.
