### ISSUE TITLE
Do we need the Contributor Over Time chart?

### ISSUE THREAD

**Issue by starsz** [golang/go#45825]
Hi, we have generated a chart of contributors over time, which may be helpful to you.

You can referer to:
https://contributor-graph-api.apiseven.com/contributors-svg?chart=contributorOverTime&repo=golang/go

**Comment by ALTree** [comment]
Hi, that's a nice graph, but I don't think we need to put it on the website, repository statistics are better hosted externally (there are many website that will provide various stats given a public repository).

**Comment by ianlancetaylor** [comment]
You may want to share this graph on a forum.  See https://golang.org/wiki/Questions.

**Comment by starsz** [comment]
> Hi, that's a nice graph, but I don't think we need to put it on the website. Repository statistics are better hosted externally (there are many websites that will provide various stats given a public repository).

@ALTree @ianlancetaylor Thank you for your reply. I will share this graph on a forum. Haha.
