### ISSUE TITLE
cmd/go: go run . does not report package errors

### ISSUE THREAD

**Issue by rsc** [golang/go#45827]
```
% mkdir /tmp/z
% cd /tmp/z
% echo module m >go.mod
% echo package p >p.go
% echo package main >q.go
% go run .
go run: no packages loaded from .
% go build
found packages p (p.go) and main (q.go) in /private/tmp/z
% 
```

The error from `go run .` should mention the multiple package names, same as `go build`.
And the error from `go build` should probably be prefixed with `go:`.

/cc @jayconrod @matloob @bcmills

**Comment by bcmills** [comment]
What CL was this observed at? I submitted [CL 314050](https://golang.org/cl/314050) yesterday to fix a very similar symptom that I hit when testing the lazy-loading stack.

**Comment by bcmills** [comment]
This is not, in fact, fixed by CL 314050.

**Comment by bcmills** [comment]
It appears that `go/build` is setting the `Name` field arbitrarily to the first name encountered in any source file, which seems wrong if multiple files specify conflicting names.
