### ISSUE TITLE
time: doc: be more explicit about how the reference date works

### ISSUE THREAD

**Issue by carlmjohnson** [golang/go#45830]
It seems like the reference date, being a novel idea in Go's time package, is a stumbling block for developers new to Go. I think it's worth adding a paragraph to the documentation for Parse and Format that is extremely explicit. Something along the lines of:

> The following values are recognized:
> 
> month: 1 01 Jan January  
> day: 2 02 _2
> hour: 3 03 15
> minute: 4 04
> second: 5 05 05.0 (etc.)
> year: 6 06 2006
> timezone: -07 -0700 -07:00 MST
> day of week: Mon Monday
> meridiem: pm PM

**Comment by ianlancetaylor** [comment]
CC @robpike

**Comment by nogurenn** [comment]
@ianlancetaylor  Hello. I'm not sure if I should ping here since I'm a first time contributor, but I've [submitted a possible change](https://go-review.googlesource.com/c/go/+/315795) in the documentation on gerrit.

**Comment by robpike** [comment]
The problem may be worth addressing; people do have trouble understanding the reference date (and that's on me).

I have an idea how to do this. Assigning to myself.
