### ISSUE TITLE
Including github.com/googleapis/googleapis as a dependency in my project

### ISSUE THREAD

**Issue by delfick** [golang/go#45836]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yeap

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/stephenmoore/Library/Caches/go-build"
GOENV="/Users/stephenmoore/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/stephenmoore/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/stephenmoore/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/stephenmoore/.gimme/versions/go1.16.darwin.amd64"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/stephenmoore/.gimme/versions/go1.16.darwin.amd64/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/stephenmoore/Projects/lifx/go-lx/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0l/6kvsbpf56px14b8btjy86hb00000gn/T/go-build36383324=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I want to use `go list` to refer to the proto files in googleapis when I generate my proto files.

i.e.

```
PROTOAPIS=$(go list -f '{{.Dir}}' -m github.com/protocolbuffers/protobuf)/src
GOOGLEAPIS=$(go list -f '{{.Dir}}' -m github.com/googleapis/googleapis)

protoc  \
    -I$GOOGLEAPIS \
    -I$PROTOAPIS \
    *.proto
```

When I do a `go get` of those dependencies they are added to my go.mod and go list works and this solution is great.

However because none of my code imports those, when I do a `go mod tidy` those dependencies are removed from go.mod and I can't figure out how to make them remain.

### What would you like?

Is there a way of telling go.mod that I have this dependency that isn't actually imported anywhere?

**Comment by AlexRouSg** [comment]
See https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

**Comment by delfick** [comment]
Hi, I tried something similar. The problem is there isn't anything in googleapis that's a valid go import.

**Comment by AlexRouSg** [comment]
If you can `go get foo.com/bar`, you can `import _ "foo.com/bar"`
The whole point of adding a `//+build tools` to the file is to ignore build errors and to trick modules to track it.

**Comment by AlexRouSg** [comment]
*sorry deleted the previous comment cause I didn't test it

How were you able to `go get` these repos and have `go.mod` contain them?

**Comment by delfick** [comment]
go get will add them to go.mod and then go list will see them. I want to do it this way seeing as go get already does the right thing with versioning and caching and such without the need for submodules. Especially for this [directory](https://github.com/protocolbuffers/protobuf/tree/master/src) which I need.

**Comment by delfick** [comment]
I imagine the alternative I should go for is to use bazel to generate our protobuf code given we already use that in this project anyway.

**Comment by mvdan** [comment]
Maybe @jayconrod or @bcmills have ideas, but I think keeping dependencies with zero Go files in go.mod is not an intended feature. It tracks Go modules after all, and a module is defined as "a collection of [Go] packages".

**Comment by cherrymui** [comment]
Hi @delfick , we don't really use our issue tracker for questions. More people will see your question, and you will get better answers, if you ask on a forum rather than on the issue tracker. See https://golang.org/wiki/Questions. Thanks.

Since the discussion is already ongoing I'm going to leave this issue open for now. You can close it if you choose to discuss somewhere else. Thanks.

**Comment by delfick** [comment]
@cherrymui fair enough, sorry. I'll close for now and bring it back if that becomes necessary.

**Comment by ivanovaleksey** [comment]
@delfick have you found any solution?

**Comment by delfick** [comment]
nup. But when I find the time I'm gonna make a script that just git clones these things and use a path to that.

**Comment by ivanovaleksey** [comment]
just for the record, in a pet project I use `github.com/grpc-ecosystem/grpc-gateway v1` because I need swagger plugin.
`v1` also contains `third_party/googleapis` so this works fine
```
-I `go list -f '{{ .Dir }}' -m github.com/grpc-ecosystem/grpc-gateway`/third_party/googleapis
```
