### ISSUE TITLE
x/sys/unix: augment support for zos

### ISSUE THREAD

**Issue by billotosyr** [golang/go#45838]
I would like to add a small number of syscalls (and adjust one) to unix support for the s390x running zos. Other platforms should not be affected in any way.
Needed to be added:
Errno2
Err2ad
W_Getmntent_A (pure ascii version of W_Getmntent)
Select

Needed to be adjusted to be linux-like:
Mount
Unmount

I'd also like to add a small number of constants and types

**Comment by ianlancetaylor** [comment]
Thanks for working on this.  I just want to note that it's not necessary to open an issue for adding code like this to x/sys/unix.  You can just send a change.  Thanks.
