### ISSUE TITLE
x/pkgsite: visual glitch in top bar

### ISSUE THREAD

**Issue by 5KS** [golang/go#45841]
### What is the URL of the page with the issue?
https://pkg.go.dev/rsc.io/quote?tab=imports
.
### What is your user agent?
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36
.
### Screenshot
https://user-images.githubusercontent.com/83383490/116498962-2eb44a80-a8d5-11eb-82c1-70661058c193.mp4

.
### What did you do?
Visited the page in qutebrowser,
scrolled down with 'j' key.
.
### What did you expect to see?
A smooth transition of the top bar.
.
### What did you see instead?
A visual glitch.

**Comment by 5KS** [comment]
Same in Brave on Android.

**Comment by danil** [comment]
Reproducing same glitch on Firefox 90.0.2 (64-bit)
