### ISSUE TITLE
TypeByExtension(".js") = "text/plain; charset=utf-8", want "text/javascript; charset=utf-8"

### ISSUE THREAD

**Issue by sanrentai** [golang/go#45844]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

I think so
go version go1.16.3 windows/amd64 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\sanre\AppData\Local\go-build
set GOENV=C:\Users\sanre\AppData\Roaming\go\env  
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\gopath\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\gopath\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Go\src\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\sanre\AppData\Local\Temp\go-build4193613693=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

<pre>
func initMimeForTests() map[string]string {
	return map[string]string{
		".PnG": "image/png",
		".js":  "text/javascript; charset=utf-8",
	}
}
</pre>

### What did you see instead?

=== RUN   TestTypeByExtension
    d:\Go\src\mime\type_test.go:46: TypeByExtension(".js") = "text/plain; charset=utf-8", want "text/javascript; charset=utf-8"
--- FAIL: TestTypeByExtension (0.07s)

**Comment by seankhliao** [comment]
Where did you get that test case from? i don't see it defined anywhere, windows only tests for `.PnG`: https://github.com/golang/go/blob/master/src/mime/type_windows.go

**Comment by sanrentai** [comment]
@seankhliao  I write the test case. 
<pre>
func initMimeForTests() map[string]string {
	return map[string]string{
		".PnG": "image/png",
		".js":  "text/javascript; charset=utf-8",
	}
}
</pre>
By the way , the string "text/javascript; charset=utf-8" is over write by the func initMimeWindows

**Comment by seankhliao** [comment]
mime type detection is dependent on the host OS, if it doesn't provide the values you want, you'll have to change it at the OS level
