### ISSUE TITLE
runtime: TestGcSys "using too much memory" on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [golang/go#45847]
[jw@cn06 src]$ ./all.bash
Building Go cmd/dist using /usr/lib/golang. (go1.15.11 linux/arm64)
Building Go toolchain1 using /usr/lib/golang.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/arm64.

##### Testing packages.
ok      archive/tar     0.149s
ok      archive/zip     0.296s
ok      bufio   0.269s
ok      bytes   1.173s
ok      compress/bzip2  0.259s
ok      compress/flate  2.071s
ok      compress/gzip   0.135s
ok      compress/lzw    0.158s
ok      compress/zlib   0.232s
ok      container/heap  0.103s
ok      container/list  0.084s
ok      container/ring  0.076s
ok      context 0.077s
ok      crypto  0.076s
ok      crypto/aes      0.097s
ok      crypto/cipher   0.088s
ok      crypto/des      0.066s
ok      crypto/dsa      0.160s
ok      crypto/ecdsa    0.545s
ok      crypto/ed25519  0.313s
ok      crypto/elliptic 0.571s
ok      crypto/hmac     0.056s
ok      crypto/internal/subtle  0.086s
ok      crypto/md5      0.053s
ok      crypto/rand     0.213s
ok      crypto/rc4      0.131s
ok      crypto/rsa      0.456s
ok      crypto/sha1     0.153s
ok      crypto/sha256   0.147s
ok      crypto/sha512   0.068s
ok      crypto/subtle   0.076s
ok      crypto/tls      3.879s
ok      crypto/x509     1.958s
ok      database/sql    0.897s
ok      database/sql/driver     0.096s
ok      debug/dwarf     0.099s
ok      debug/elf       0.152s
ok      debug/gosym     0.139s
ok      debug/macho     0.022s
ok      debug/pe        0.098s
ok      debug/plan9obj  0.107s
ok      embed/internal/embedtest        0.047s
ok      encoding/ascii85        0.098s
ok      encoding/asn1   0.086s
ok      encoding/base32 0.215s
ok      encoding/base64 0.134s
ok      encoding/binary 0.051s
ok      encoding/csv    0.107s
ok      encoding/gob    0.219s
ok      encoding/hex    0.044s
ok      encoding/json   0.880s
ok      encoding/pem    0.112s
ok      encoding/xml    0.201s
ok      errors  0.076s
ok      expvar  0.037s
ok      flag    0.241s
ok      fmt     0.432s
ok      go/ast  0.111s
ok      go/build        4.967s
ok      go/build/constraint     0.092s
ok      go/constant     0.057s
ok      go/doc  0.224s
ok      go/format       0.086s
ok      go/importer     0.586s
ok      go/internal/gccgoimporter       0.105s
ok      go/internal/gcimporter  1.509s
ok      go/internal/srcimporter 28.030s
ok      go/parser       0.163s
ok      go/printer      1.223s
ok      go/scanner      0.088s
ok      go/token        0.144s
ok      go/types        9.628s
ok      hash    0.101s
ok      hash/adler32    0.062s
ok      hash/crc32      0.065s
ok      hash/crc64      0.036s
ok      hash/fnv        0.046s
ok      hash/maphash    0.485s
ok      html    0.085s
ok      html/template   0.420s
ok      image   0.377s
ok      image/color     0.064s
ok      image/draw      0.355s
ok      image/gif       1.554s
ok      image/jpeg      0.738s
ok      image/png       0.256s
ok      index/suffixarray       0.585s
ok      internal/abi    0.180s
ok      internal/cpu    0.087s
ok      internal/execabs        0.061s
ok      internal/fmtsort        0.070s
ok      internal/itoa   0.097s
ok      internal/poll   0.508s
ok      internal/profile        0.029s
ok      internal/reflectlite    0.343s
ok      internal/singleflight   0.094s
ok      internal/trace  0.304s
ok      internal/unsafeheader   0.065s
ok      internal/xcoff  0.040s
ok      io      0.127s
ok      io/fs   0.041s
ok      io/ioutil       0.056s
ok      log     0.081s
ok      log/syslog      1.308s
ok      math    0.055s
ok      math/big        3.230s
ok      math/bits       0.066s
ok      math/cmplx      0.039s
ok      math/rand       0.461s
ok      mime    0.057s
ok      mime/multipart  0.719s
ok      mime/quotedprintable    0.141s
ok      net     14.052s
ok      net/http        25.215s
ok      net/http/cgi    1.404s
ok      net/http/cookiejar      0.033s
ok      net/http/fcgi   0.161s
ok      net/http/httptest       0.119s
ok      net/http/httptrace      0.048s
ok      net/http/httputil       0.264s
ok      net/http/internal       0.043s
ok      net/http/pprof  5.244s
ok      net/internal/socktest   0.069s
ok      net/mail        0.033s
ok      net/rpc 0.105s
ok      net/rpc/jsonrpc 0.052s
ok      net/smtp        0.102s
ok      net/textproto   0.030s
ok      net/url 0.102s
ok      os      2.618s
ok      os/exec 4.108s
ok      os/signal       3.026s
ok      os/user 0.085s
ok      path    0.048s
ok      path/filepath   0.133s
ok      reflect 1.770s
ok      regexp  0.386s
ok      regexp/syntax   1.652s
--- FAIL: TestGcSys (0.09s)
    gc_test.go:30: expected "OK\n", but got "using too much memory: 47054848 bytes\n"
FAIL
FAIL    runtime 79.877s
ok      runtime/cgo     0.063s
ok      runtime/debug   0.261s
ok      runtime/internal/atomic 0.269s
ok      runtime/internal/math   0.152s
ok      runtime/internal/sys    0.128s
ok      runtime/metrics 0.060s
ok      runtime/pprof   18.752s
ok      runtime/race    0.968s
ok      runtime/trace   1.346s
ok      sort    0.307s
ok      strconv 2.163s
ok      strings 0.565s
ok      sync    2.184s
ok      sync/atomic     0.422s
ok      syscall 0.375s
ok      testing 2.439s
ok      testing/fstest  0.028s
ok      testing/iotest  0.036s
ok      testing/quick   0.271s
ok      text/scanner    0.040s
ok      text/tabwriter  0.037s
ok      text/template   0.177s
ok      text/template/parse     0.084s
ok      time    3.216s
ok      unicode 0.102s
ok      unicode/utf16   0.012s
ok      unicode/utf8    0.062s
ok      cmd/addr2line   6.335s
ok      cmd/api 7.821s
ok      cmd/asm/internal/asm    3.506s
ok      cmd/asm/internal/lex    0.052s
ok      cmd/compile/internal/dwarfgen   1.141s
ok      cmd/compile/internal/importer   1.356s
ok      cmd/compile/internal/ir 0.099s
ok      cmd/compile/internal/logopt     0.839s
ok      cmd/compile/internal/noder      0.029s
ok      cmd/compile/internal/ssa        1.117s
ok      cmd/compile/internal/ssagen     0.023s
ok      cmd/compile/internal/syntax     0.282s
ok      cmd/compile/internal/test       16.164s
ok      cmd/compile/internal/typecheck  1.283s
ok      cmd/compile/internal/types      0.053s
ok      cmd/compile/internal/types2     3.899s
ok      cmd/cover       6.021s
ok      cmd/doc 0.658s
ok      cmd/fix 1.755s
ok      cmd/go  43.302s
ok      cmd/go/internal/auth    0.045s
ok      cmd/go/internal/cache   0.463s
ok      cmd/go/internal/fsys    0.165s
ok      cmd/go/internal/generate        0.075s
ok      cmd/go/internal/get     0.119s
ok      cmd/go/internal/imports 0.083s
ok      cmd/go/internal/load    0.114s
ok      cmd/go/internal/lockedfile      0.280s
ok      cmd/go/internal/lockedfile/internal/filelock    0.100s
ok      cmd/go/internal/modconv 0.050s
ok      cmd/go/internal/modfetch        0.107s
ok      cmd/go/internal/modfetch/codehost       0.065s
ok      cmd/go/internal/modfetch/zip_sum_test   0.087s
ok      cmd/go/internal/modload 0.070s
ok      cmd/go/internal/mvs     0.094s
ok      cmd/go/internal/par     0.157s
ok      cmd/go/internal/search  0.086s
ok      cmd/go/internal/str     0.060s
ok      cmd/go/internal/test    0.065s
ok      cmd/go/internal/txtar   0.099s
ok      cmd/go/internal/vcs     0.239s
ok      cmd/go/internal/web     0.087s
ok      cmd/go/internal/work    0.055s
ok      cmd/gofmt       0.239s
ok      cmd/internal/archive    3.206s
ok      cmd/internal/buildid    0.965s
ok      cmd/internal/dwarf      0.052s
ok      cmd/internal/edit       0.054s
ok      cmd/internal/goobj      0.110s
ok      cmd/internal/moddeps    4.792s
ok      cmd/internal/obj        0.085s
ok      cmd/internal/obj/arm64  0.171s
ok      cmd/internal/obj/ppc64  0.080s
ok      cmd/internal/obj/riscv  0.095s
ok      cmd/internal/obj/s390x  0.040s
ok      cmd/internal/obj/x86    8.901s
ok      cmd/internal/objabi     0.103s
ok      cmd/internal/pkgpath    0.228s
ok      cmd/internal/src        0.039s
ok      cmd/internal/sys        0.051s
ok      cmd/internal/test2json  0.368s
ok      cmd/link        25.220s
ok      cmd/link/internal/benchmark     0.110s
ok      cmd/link/internal/ld    2.832s
ok      cmd/link/internal/loader        0.096s
ok      cmd/nm  5.868s
ok      cmd/objdump     7.367s
ok      cmd/pack        7.050s
ok      cmd/trace       0.342s
ok      cmd/vet 20.111s
FAIL
go tool dist: Failed: exit status 1
[jw@cn06 src]$ 

Before did yum golang to bootstrap.

**Comment by ksshannon** [comment]
See #37331 also.

**Comment by cherrymui** [comment]
Yes, this is #37331 . Closing as a dup. Thanks.
