### ISSUE TITLE
gccgo: cross compiling with GCC11.1 cause many undefined reference

### ISSUE THREAD

**Issue by bearx3f** [golang/go#45843]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.16.3
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="/usr/local/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/builds/booboo/test-cross-compile-gccgo-sparcv9-sun-solaris/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2245835495=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

compile go with gccgo

I'm guessing link func name is missing last character

<details><summary><code>sparcv9-sun-solaris2.11-ld -v</code> Output</summary><br>
<pre>
$ sparcv9-sun-solaris2.11-ld -v
GNU ld (GNU Binutils) 2.35.2
</pre>
</details>

<details><summary><code>gccgo -v</code> Output</summary><br>
<pre>
$ gccgo -v
Using built-in specs.
COLLECT_GCC=gccgo
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/sparcv9-sun-solaris2.11/11.1.0/lto-wrapper
Target: sparcv9-sun-solaris2.11
Configured with: /usr/src/gcc/configure --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=sparcv9-sun-solaris2.11 --with-sysroot=/sysroot/sparcv9-sun-solaris2.11 --with-gnu-as --with-gnu-ld --with-static-standard-libraries --disable-documentation --disable-libgcj --disable-multilib --disable-shared --enable-stage1-languages=c --enable-languages=c,c++,go -v
</pre>
</details>

<pre>
go build -compiler gccgo -o bin_gcc11 -trimpath -gccgoflags="-O3 -Wall -s -static-libgo -Wl,-dy -lnsl -lsocket -lrt"
</pre>

### What did you expect to see?
successfully compile

### What did you see instead?
<pre>
# test-cross-compile-gccgo-sparcv9-sun-solaris
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.fatalpanic..func1':
/usr/src/gcc/libgo/go/runtime/panic.go:1109: undefined reference to `exi'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.afterfork':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:988: undefined reference to `sigprocmas'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.beforefork':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:977: undefined reference to `sigprocmas'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/src/gcc/libgo/go/runtime/signal_unix.go:1002: undefined reference to `sigfillse'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.sigblock':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:1003: undefined reference to `sigprocmas'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `syscall.Exit':
/usr/src/gcc/libgo/go/runtime/runtime.go:66: undefined reference to `exi'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.setsig':
/usr/src/gcc/libgo/go/runtime/signal_gccgo.go:81: undefined reference to `sigfillse'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/src/gcc/libgo/go/runtime/signal_gccgo.go:83: undefined reference to `sigactio'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `syscall.runtime__AfterForkInChild':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:988: undefined reference to `sigprocmas'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.sigaddset':
/usr/src/gcc/libgo/go/runtime/signal_gccgo.go:137: undefined reference to `sigaddse'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.dieFromSignal':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:1014: undefined reference to `sigemptyse'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.dieFromSignal':
/usr/src/gcc/libgo/go/runtime/signal_gccgo.go:137: undefined reference to `sigaddse'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.unblocksig':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:1016: undefined reference to `sigprocmas'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.dieFromSignal':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:709: undefined reference to `rais'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/src/gcc/libgo/go/runtime/signal_unix.go:722: undefined reference to `rais'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/src/gcc/libgo/go/runtime/signal_unix.go:729: undefined reference to `exi'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.minitSignalStack':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:1039: undefined reference to `sigaltstac'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.minitSignalMask':
/usr/src/gcc/libgo/go/runtime/signal_gccgo.go:141: undefined reference to `sigdelse'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.minitSignalMask':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:1063: undefined reference to `sigprocmas'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.throw':
/usr/src/gcc/libgo/go/runtime/panic.go:1071: undefined reference to `exi'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.getsig':
/usr/src/gcc/libgo/go/runtime/signal_gccgo.go:106: undefined reference to `sigactio'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.initsig':
/usr/src/gcc/libgo/go/runtime/signal_gccgo.go:90: undefined reference to `sigactio'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.setsigstack':
/usr/src/gcc/libgo/go/runtime/signal_gccgo.go:99: undefined reference to `sigactio'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.setcpuprofilerate':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:289: undefined reference to `setitime'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.setProcessCPUProfiler':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:315: undefined reference to `setitime'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.startpanic__m':
/usr/src/gcc/libgo/go/runtime/panic.go:1170: undefined reference to `exi'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/src/gcc/libgo/go/runtime/panic.go:1166: undefined reference to `exi'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.sysAlloc':
/usr/src/gcc/libgo/go/runtime/mem_gccgo.go:60: undefined reference to `exi'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/src/gcc/libgo/go/runtime/mem_gccgo.go:56: undefined reference to `exi'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.dropm':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:1002: undefined reference to `sigfillse'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.sigblock':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:1003: undefined reference to `sigprocmas'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.dropm':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:988: undefined reference to `sigprocmas'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.needm':
/usr/src/gcc/libgo/go/runtime/proc.go:1626: undefined reference to `exi'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.needm':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:977: undefined reference to `sigprocmas'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/src/gcc/libgo/go/runtime/signal_unix.go:1002: undefined reference to `sigfillse'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.sigblock':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:1003: undefined reference to `sigprocmas'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.sigtrampgo':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:889: undefined reference to `exi'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/src/gcc/libgo/go/runtime/signal_unix.go:637: undefined reference to `exi'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/src/gcc/libgo/go/runtime/signal_unix.go:1014: undefined reference to `sigemptyse'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.sigtrampgo':
/usr/src/gcc/libgo/go/runtime/signal_gccgo.go:137: undefined reference to `sigaddse'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.unblocksig':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:1016: undefined reference to `sigprocmas'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.sigtrampgo':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:776: undefined reference to `rais'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.sighandler':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:531: undefined reference to `sigfillse'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/src/gcc/libgo/go/runtime/signal_unix.go:532: undefined reference to `sigprocmas'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.unblocksig':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:1014: undefined reference to `sigemptyse'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.sigaddset':
/usr/src/gcc/libgo/go/runtime/signal_gccgo.go:137: undefined reference to `sigaddse'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.unblocksig':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:1016: undefined reference to `sigprocmas'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.sigtrampgo':
/usr/src/gcc/libgo/go/runtime/signal_gccgo.go:122: undefined reference to `getpi'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.raiseproc':
/usr/src/gcc/libgo/go/runtime/signal_gccgo.go:122: undefined reference to `kil'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.scanstack':
/usr/src/gcc/libgo/go/runtime/mgcmark.go:740: undefined reference to `getpi'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.mexit':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:1002: undefined reference to `sigfillse'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.sigblock':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:1003: undefined reference to `sigprocmas'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.main':
/usr/src/gcc/libgo/go/runtime/proc.go:281: undefined reference to `exi'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.ensureSigM..func1':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:826: undefined reference to `sigfillse'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.ensureSigM..func1':
/usr/src/gcc/libgo/go/runtime/signal_gccgo.go:141: undefined reference to `sigdelse'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.ensureSigM..func1':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:832: undefined reference to `sigprocmas'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/src/gcc/libgo/go/runtime/signal_unix.go:844: undefined reference to `sigprocmas'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.ensureSigM..func1':
/usr/src/gcc/libgo/go/runtime/signal_gccgo.go:141: undefined reference to `sigdelse'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/src/gcc/libgo/go/runtime/signal_gccgo.go:137: undefined reference to `sigaddse'
/usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/bin/ld: /usr/local/lib/gcc/sparcv9-sun-solaris2.11/11.1.0/../../../../sparcv9-sun-solaris2.11/lib/sparcv9/libgo.a(runtime.o): in function `runtime.schedinit':
/usr/src/gcc/libgo/go/runtime/signal_unix.go:977: undefined reference to `sigprocmas'
collect2: error: ld returned 1 exit status
</pre>

**Comment by ianlancetaylor** [comment]
Did you build gccgo yourself?  In your build directory, what is the contents of the generated file sparcv9-sun-solaris2.11/libgo/runtime_linknames.go?  Thanks.

**Comment by bearx3f** [comment]
Yes I'm build gcc by myself 

and here you are content of sparcv9-sun-solaris2.11/libgo/runtime_linknames.go
<pre>
root@d3fc663ba707:/tmp/tmp.x6cBnklrDH# cat sparcv9-sun-solaris2.11/libgo/runtime_linknames.go
// Code generated by mklinknames.awk. DO NOT EDIT.

package runtime

import _ "unsafe"

//go:linkname libcPipe pip
//go:linkname libcPipe2 pipe
//go:linkname sigaction sigactio
//go:linkname sigprocmask sigprocmas
//go:linkname sigfillset sigfillse
//go:linkname sigemptyset sigemptyse
//go:linkname c_sigaddset sigaddse
//go:linkname c_sigdelset sigdelse
//go:linkname sigaltstack sigaltstac
//go:linkname raise rais
//go:linkname getpid getpi
//go:linkname kill kil
//go:linkname setitimer setitime
//go:linkname exit exi
</pre>

**Comment by ianlancetaylor** [comment]
Thanks.  That file is generated by libgo/mklinknames.awk, and clearly it is not working.  But I don't see why.  What version of awk do you have installed?  What do you see if you run `grep sigaltstack sparcv9-sun-solaris2.11/libgo/gen-sysinfo.go`?  Thanks.

**Comment by bearx3f** [comment]
I was compile gcc in docker build base on **buildpack-deps:buster**

<pre>
root@e815928baf27:/tmp/tmp.x6cBnklrDH# grep sigaltstack sparcv9-sun-solaris2.11/libgo/gen-sysinfo.go
type _sigaltstack struct { ss_sp *byte; ss_size uint64; ss_flags int32; Godump_0_pad [4]byte; }
const _sizeof_sigaltstack = 24
type _stack_t _sigaltstack
func _sigaltstack (*_stack_t, *_stack_t) int32 __asm__("sigaltstack")
const _SYS_sigaltstack = 97
</pre>

and awk version
<pre>
root@e815928baf27:/tmp/tmp.x6cBnklrDH# awk -W version
mawk 1.3.3 Nov 1996, Copyright (C) Michael D. Brennan

compiled limits:
max NF             32767
sprintf buffer      2040
</pre>

**Comment by choeger** [comment]
My last comment is not the root cause. The cause is in the mklinknames.awk script. It contains the following line:

```
asmname = substr(asmname, 0, length(asmname) - 2)
```

That 0 should be a 1 according to `man awk`:

```
       substr(s, i [, n])      Return the at most n-character substring of s starting at i.  If n is  omitted,  use
                               the rest of s.
```

I will try to come up with a patch. Where do I submit it, if it works?

**Comment by choeger** [comment]
Here is the patch I used to fix the build problem. @bearx3f you might want to give it a try. I tried to upstream it, but somehow I cannot send to gcc-patches@gcc.gnu.org .

(The changelog part might not apply to the 11.1.0 release tarball,  just delete it, it doesn't matter).
[0001-Fix-awk-substr-invocation-in-libgo-buildsystem.zip](https://github.com/golang/go/files/6453201/0001-Fix-awk-substr-invocation-in-libgo-buildsystem.zip)

**Comment by bearx3f** [comment]
@choeger I think here https://github.com/golang/gofrontend is proper way to submit patch

**Comment by bearx3f** [comment]
@ianlancetaylor maybe my problem is all about awk version

problem version
<pre>
root@e815928baf27:/tmp/tmp.x6cBnklrDH# awk -W version
mawk 1.3.3 Nov 1996, Copyright (C) Michael D. Brennan

compiled limits:
max NF             32767
sprintf buffer      2040
</pre>

success version
<pre>
root@d772f8344b47:/go# awk -W version
GNU Awk 4.2.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.1.2)
Copyright (C) 1989, 1991-2018 Free Software Foundation.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the.
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see http://www.gnu.org/licenses/.
</pre>

my issue is closed.
