### ISSUE TITLE
x/sys/unix: define new RTF flags introduced by macOS 11.3

### ISSUE THREAD

**Issue by riraccuia** [golang/go#45848]
@kumpfdp and I noticed there is a bunch of new routing flags that are being actively used starting with macOS 11.3

The sdk files don't seem to be out yet (or i just can't find it) at opensource.apple.com but here's one unofficial link: https://github.com/plentico/osxcross-target/blob/master/SDK/MacOSX11.3.sdk/usr/include/net/route.h

```
#define RTF_PROXY       0x8000000       /* proxying, no interface scope */
#define RTF_ROUTER      0x10000000      /* host is a router */
#define RTF_DEAD        0x20000000      /* Route entry is being freed */
#define RTF_GLOBAL      0x40000000      /* route to destination of the global internet */
```

**Comment by tklauser** [comment]
Pleas note that the `syscall` package is frozen per the package level godoc. These new constants should be added to the `golang.org/x/sys/unix` package instead.

**Comment by tklauser** [comment]
`RTF_PROXY`, `RTF_ROUTER` and `RTF_DEAD` are already present in the latest version of `golang.org/x/sys`. I've sent https://golang.org/cl/343509 to add the missing `RTF_GLOBAL`.
