### ISSUE TITLE
x/pkgsite: use moduleID in getPackagesInUnit

### ISSUE THREAD

**Issue by julieqiu** [golang/go#45854]
[getPackagesInUnit](https://github.com/golang/pkgsite/blob/c4f46a6c619e49ed6c9d7f230fd8d4f74aa02661/internal/postgres/unit.go) is used by the frontend [via getUnitWithAllFields](https://github.com/golang/pkgsite/blob/c4f46a6c619e49ed6c9d7f230fd8d4f74aa02661/internal/postgres/unit.go#L467). 

Since we can easily get the moduleID from the first query in that function, we should consider passing in the moduleID to getPackagesInUnit instead of (modulePath, version). This could increase performance since we no longer need to JOIN on the modules table and can filter by `u.module_id`.

**Comment by junjunjunk** [comment]
Hi. I'll try this issue!

**Comment by junjunjunk** [comment]
May I ask you one question?
getPackagesInUnit is also used by [ReInsertLatestVersion](https://github.com/golang/pkgsite/blob/754bc2ca63fe1af3d2ee0403617f20adfd18e77f/internal/postgres/insert_module.go).

And this method doesn't use module_id. So I can not replace the argument of getPackagesInUnit to use module_id.
Should I implement db's new method getPackagesInUnitUsingModuleId or get in module_id in ReInsertLatestVersion?

**Comment by julieqiu** [comment]
Thanks @junjunjunk!

> Should I implement db's new method getPackagesInUnitUsingModuleId or get module_id info in ReInsertLatestVersion?

Yup! I would add a new function.

You can share a lot of the same logic between the two functions, so it might be helpful to know that we use https://pkg.go.dev/github.com/Masterminds/squirrel to create shared queries in our codebase.

https://github.com/golang/pkgsite/blob/dfa0f1976413309fde70a10909a49793da16725b/internal/postgres/symbol_history.go#L62 is an example of a place where squirrel is used.

**Comment by junjunjunk** [comment]
Thank you for your thoughtful response!
I'll work on it with the resources you provided.
