### ISSUE TITLE
parse error with UPPER field

### ISSUE THREAD

**Issue by geerttouquet** [golang/go#45858]
We are using golang spansql 1.17.0

if we  parse the following sql (that is generate by google)

CREATE TABLE resourceWorkschedule (
  resourceWorkscheduleId STRING(MAX) NOT NULL,
  labelUpper STRING(MAX) NOT NULL AS (upper(label)) STORED,
  send_userRoleId STRING(MAX) NOT NULL,
  send_version TIMESTAMP NOT NULL OPTIONS (
    allow_commit_timestamp = true
  ),
) PRIMARY KEY(resourceWorkscheduleId);

we got following error / got "(" while expecting ")" 
the problem is related by  AS (upper(label)) STORED , I believe

is this possible to solve this ?

**Comment by AlexRouSg** [comment]
Did you meant to post here? 
I think you're looking for https://github.com/googleapis/google-cloud-go

**Comment by geerttouquet** [comment]
i am sorry, this is not correct
