### ISSUE TITLE
cmd/go: access $WORK directory from toolexec

### ISSUE THREAD

**Issue by dzonerzy** [golang/go#45864]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\DZONERZY\AppData\Local\go-build
set GOENV=C:\Users\DZONERZY\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\DZONERZY\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\DZONERZY\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.2
set GCCGO=gccgo
set GO386=sse2
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\DZONERZY\go\src\github.com\dzonerzy\guzzer\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -fmessage-length=0 -fdebug-prefix-map=C:\Users\DZONERZY\AppData\Local\Temp\go-build4099943664=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I'm trying to access $WORK variable via the -toolexec command , in order to modify the content of -importcfg before the compilation of a package

### What did you expect to see?
A way to modify -importcfg content before compilation

### What did you see instead?
There's not way to access the working directory via -toolexec

**Comment by ianlancetaylor** [comment]
CC @bcmills @jayconrod

**Comment by bcmills** [comment]
CC @matloob @mvdan

**Comment by mvdan** [comment]
This is possible today, without directly knowing $WORK. You just look at the compiler flags when it runs, and swap or modify the importcfg file.

https://github.com/burrowers/garble/blob/d34406d83279978529dd732ad59e07e867f68c95/main.go#L859-L866

https://github.com/burrowers/garble/blob/d34406d83279978529dd732ad59e07e867f68c95/main.go#L1413

I'm not opposed to exposing $WORK, but I don't think it's necessary for what you want here.

**Comment by dzonerzy** [comment]
Actually i need to read the content of the "old" importcfg file and add there some new packagefile directive, so i need to access the old file not only swap it

**Comment by mvdan** [comment]
Right. The code I shared shows a working example of reading the existing file and replacing it with a new one.

**Comment by dzonerzy** [comment]
Imo another option is to allow multiple -importcfg switch and just merge them at compile time

**Comment by mvdan** [comment]
I guess that's possible, but I don't see it as necessary. I also don't understand how it's related to your original request for $WORK. You can certainly read, modify, and replace `-importcfg` currently, so I'd suggest that you try that before suggesting changes to the toolchain.

**Comment by mvdan** [comment]
@dzonerzy I shared details (and even code!) about how this is possible with just a little bit of code today. Can you clarify whether it works for you or not? If it does not, please provide details to keep the issue open for further discussion.

**Comment by dzonerzy** [comment]
Your code solved my issue
