### ISSUE TITLE
Unexpected issue when assigning binary value to byte type

### ISSUE THREAD

**Issue by gomarcus** [golang/go#45862]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.16.3
</pre>

### What did you do?

```golang
package main

import (
	"fmt"
)

func main() {
	var c byte = ^0b01100000
	fmt.Printf("% 5v: %08b\n", c, c)
}

```

https://play.golang.org/p/kMX7fAL3M7F

### What did you expect to see?
<pre>
  159: 10011111
</pre>

### What did you see instead?
<pre>
./prog.go:8:6: constant -97 overflows byte
</pre>
Am I mistaken, or should this not actually be a problem?

**Comment by AlexRouSg** [comment]
If you do `var c byte = ^0b01100000` that is eq to `var c byte = byte(^int(0b01100000))`
So if you want to do operations on a int literal, you have to cast it first, i.e. `var c byte = ^byte(0b01100000)`

**Comment by gomarcus** [comment]
ahh ok. Thought the compiler might be able to infer from the context that it is supposed to be a byte.
Thanks for the quick feedback!
