### ISSUE TITLE
gollvm: error: invalid go:embed: build system did not supply embed configuration

### ISSUE THREAD

**Issue by JX-Zhang98** [golang/go#45880]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 gollvm LLVM 13.0.0git linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/lyf//workspace/gowork/bin"
GOCACHE="/home/lyf/.cache/go-build"
GOENV="/home/lyf/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/lyf/workspace/gowork/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/lyf//workspace/gowork"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/home/lyf/.local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/lyf/.local/gollvm/tools"
GOVCS=""
GOVERSION="go1.16.3 gollvm LLVM 13.0.0git"
GCCGO="/home/lyf/.local/gollvm/bin/llvm-goc"
AR="ar"
CC="/home/lyf/.local/llvmtools/bin/clang"
CXX="/home/lyf/.local/llvmtools/bin/clang++"
CGO_ENABLED="1"
GOMOD="/home/lyf/workspace/gowork/src/hwprojects/beego/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3381461740=/tmp/go-build -gno-record-gcc-switches -funwind-tables"

</pre></details>

### What did you do?
compile [govatar](https://github.com/o1egl/govatar) with gollvm

```
git clone https://github.com/o1egl/govatar.git
cd govatar
go build .
```

### What did you expect to see?
Build successfully

### What did you see instead?
Build failed due to embed
```
$ go build .
# github.com/o1egl/govatar
../govatar.go:51:5: error: invalid go:embed: build system did not supply embed configuration

```

**Comment by thanm** [comment]
Thanks for reporting. I'll take a look.

**Comment by thanm** [comment]
OK, this should be fixed at tip now.
