### ISSUE TITLE
x/pkgsite: How to deploy pkgsite to serve docs for internal packages 

### ISSUE THREAD

**Issue by asilverman** [golang/go#45895]
How can I deploy this application to serve documentation for go packages that are hosted in my internal network?

**Comment by jba** [comment]
See if this helps: https://go.googlesource.com/pkgsite/+/refs/heads/master/doc/frontend.md#local-mode.

**Comment by julieqiu** [comment]
See https://github.com/golang/go/issues/39827 for additional information. Closing as a duplicate.
