### ISSUE TITLE
x/pkgsite: Remove packages

### ISSUE THREAD

**Issue by physcat** [golang/go#45911]
Please remove all packages from: `github.com/physcat`. They are experimental and was not intended for caching.

I will try and make better use of `GOPRIVATE` and `GONOPROXY` in future experiments.

**Comment by julieqiu** [comment]
It doesn't seem like there are any packages with that prefix:

![image](https://user-images.githubusercontent.com/5943521/116899694-dd25fb80-ac05-11eb-8e47-c042f3d22ff6.png)

For future reference, you can retract your own packages by following the instructions at https://go.dev/about#removing-a-package.

**Comment by seankhliao** [comment]
@julieqiu the instructions there still say to file an issue? (and i see no mention of retract on the page)

**Comment by physcat** [comment]
@julieqiu thanks I suspect someone got there before you. I think everybody will be happy when we can retract our own mistakes. As @seankhliao mentioned the instructions are not yet on our version of the page, but I'll be checking for updated.

**Comment by julieqiu** [comment]
> I suspect someone got there before you. 

Yup you are correct :)

> the instructions are not yet on our version of the page

Also correct :) Thanks for letting me know! Looks like the CL hasn't been merged yet.
