### ISSUE TITLE
gich - A cross platform which utility written in Go (link broken)

### ISSUE THREAD

**Issue by guizzardi** [golang/go#45922]
gich - A cross platform which utility written in Go link is broken...

I think it is move to github -- > [https://github.com/jpoirier/gich](https://github.com/jpoirier/gich)

**Comment by davecheney** [comment]
@guizzardi where is this project referenced from, please reply with the precise url.

**Comment by guizzardi** [comment]
I apologize ...

In the projects list [https://github.com/golang/go/wiki/Projects#http](https://github.com/golang/go/wiki/Projects#http) under Command-line tools ...

**Comment by batara666** [comment]
could you please create a PR, appriciate

**Comment by ZekeLu** [comment]
@guizzardi The wiki is open for edit. I think you can edit it directly.

**Comment by seankhliao** [comment]
The wiki is open for everyone to edit directly, no need to file issues

**Comment by ZekeLu** [comment]
Obviously, #45923 is an invalid PR. @guizzardi do you have trouble to close (abandon) it? @seankhliao can you help to do something about it?
