### ISSUE TITLE
x/pkgsite:remove github.com/yukasaa/nummanip/calc

### ISSUE THREAD

**Issue by yukasaa** [golang/go#45926]
Please remove https://pkg.go.dev/github.com/yukasaa/nummanip/calc from pkg.go.dev.

**Comment by julieqiu** [comment]
You can now retract your own packages by following the instructions at https://go.dev/about#removing-a-package.

**Comment by yukasaa** [comment]
I am the author of this package, it is only for testing and it has some problems.

Please remove github.com/yukasaa/nummanip/calc from pkg.go.dev.

Thanks!

**Comment by mvdan** [comment]
> You can now retract your own packages by following the instructions at https://go.dev/about#removing-a-package.

@julieqiu that just points users at filing issues here, though. I don't see any instructions about retraction.

**Comment by julieqiu** [comment]
Sorry for the confusion - we're planning to update https://go.dev/about#removing-a-package with information on how to retract your package, but it looks like that change isn't live yet. 

https://pkg.go.dev/github.com/yukasaa/nummanip/calc has been removed, so closing this issue.
