### ISSUE TITLE
go/types: revisit mapping of TypeNames to TypeParams

### ISSUE THREAD

**Issue by mdempsky** [golang/go#45935]
When typechecking dev.go2go/src/cmd/go2go/testdata/go2path/src/chans/chans.go, go/types gives Exclusive the type:

    type chans.Exclusive struct{c chan Val₁₂₆}

but its corresponding method has type:

    func (*chans.Exclusive[Val₁₂₈]).Acquire() Val₁₂₈

I'm a bit surprised that Val₁₂₈ is a separate `*types.TypeParam` instance from Val₁₂₆. I get that it's a separate identifier with its own binding and scoping (and possibly different spelling), but I would expect the identifiers to map to the same underlying `*types.TypeParam` instance.

Are the separate TypeParam instances intentional/necessary? It seems a little tedious (and I'd imagine error-prone) translating between them.

/cc @griesemer @findleyr

**Comment by griesemer** [comment]
This is intentional. Each method declares its own type parameters. Also, methods are not instantiated when a type is instantiated (to avoid all kinds of problems with cycles). They are instantiated when the method is looked up.

There may be better implementation strategies down the road, but at least this is not a bug.

**Comment by mdempsky** [comment]
> This is intentional. Each method declares its own type parameters.

It's a bit ambiguous to me what you mean here, since there's the Object vs Type distinction within go/types. Specifically, I'm suggesting that methods on parameterized receiver types should still have their own `TypeName` instances, but these should point to the same `TypeParam` as the receiver type's declaration uses. Similar to how type aliases work.

> Also, methods are not instantiated when a type is instantiated (to avoid all kinds of problems with cycles). They are instantiated when the method is looked up.

Can you elaborate on how type instantiation is relevant here? E.g., if Exclusive.Acquire used Val₁₂₆ directly instead of Val₁₂₈, at lazy instantiation time isn't it just a matter of substituting a different variable?

**Comment by griesemer** [comment]
To clarify: Each method declares its own TypeName objects (one per type parameter) which are in a 1:1 correspondence to their own local type parameters. It may be possible for TypeName objects to share corresponding type parameters - I don't know and haven't focussed on it - I am just stating that this is the current implementation. The best representation of type parameters is something that I think we're still learning about.

The comment on instantiations of methods is unrelated. I just mentioned it as an additional thing that is "not coupled" with the receiver type.

**Comment by mdempsky** [comment]
Ack that this is currently working as intended, and it's not urgent to change (or even necessarily desirable). But as a user-visible detail of the go/types API, it does seem like something we want to consider before Go 1.18. That's why I filed this issue: I think this might be a worthwhile way to simplify/improve the API, and I wanted to make sure it's on our radar when the time comes to consider tweaks like this.

Is there somewhere else to track API feedback?

**Comment by griesemer** [comment]
Ack that this is user-visible and may need a revisit.

**Comment by findleyr** [comment]
> Is there somewhere else to track API feedback?

I'm going to file issue(s) soon for the go/ast and go/types API changes, though to be honest this wasn't on my radar. Let's keep this issue open, and I can reference it in the go/types API proposal.

**Comment by griesemer** [comment]
@findleyr Is there anything left to do here? (If not, please close.) We're not going to change the mapping at this point (and we already moved from lists of TypeNames to lists of TypeParams internally, which was an improvement).

**Comment by findleyr** [comment]
Agreed, I don't think there's anything to do here.

In particular, it has proven useful to have a bijection of TypeName<->TypeParam (via the `.Obj()` method), similar to `Named`. This would not be possible if the multiple TypeNames referred to the same TypeParam.

**Comment by griesemer** [comment]
Type parameters have an index (`go/types.TypeParam.Index()`) which identifies them. We are also considering providing an "owner" (the object which declares them).

cc: @findleyr in case he wants to add something

**Comment by findleyr** [comment]
As @griesemer said, `Index()` is the way to do the join.

@schroederc can you say more about what you're trying to do? It would help us to understand your use-case.

**Comment by schroederc** [comment]
I'm working on adding to support for generics to the [Kythe indexer](https://github.com/kythe/kythe) that provides xrefs for CodeSearch.

Looks like that API is still in flux: https://github.com/golang/go/blob/master/src/go/types/typeparam.go#L54.  Is there an ETA or a bug I can subscribe to for updates?

**Comment by findleyr** [comment]
Oh, that was an oversight. I thought `Index` was exported.

https://golang.org/issue/47916 is the tracking bug.

**Comment by findleyr** [comment]
Slight correction: I remember now that we intentionally held off on exporting `Index`, with the assumption that it would always be apparent from the surrounding code. It sounds like that's not the case for you. I see no harm in exporting it.
