### ISSUE TITLE
`build command-line-arguments: cannot find module for path _/path/to/package`

### ISSUE THREAD

**Issue by nations-Xiong** [golang/go#45934]
I get the message when I try to import packages in the same directory as `main.go`. Of course, I cannot run my program. Why there's an `_` before `/path/to/package`? Here is the message: 
`build command-line-arguments: cannot find module for path _/home/happy/Documents/HD/Documents/Golang/golangexercises/02_package/main/test_import`

**Comment by seankhliao** [comment]
What command did you run?

**Comment by AlexRouSg** [comment]
Please see https://golang.org/doc/tutorial/getting-started
on the required setup steps

**Comment by nations-Xiong** [comment]
Actually, I just ran `go run filename.go`. And I can't open the url.T_T

**Comment by AlexRouSg** [comment]
If you are in China you can use https://golang.google.cn/doc/tutorial/getting-started

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by nations-Xiong** [comment]
Thanks! I have figured it out!

**Comment by kikulikov** [comment]
@nations-Xiong What was that? I have that strange `_` in front of the path as well...
