### ISSUE TITLE
x/mod: comment indicating module is an indirect dependency is not removed when the comment has no whitespace

### ISSUE THREAD

**Issue by komuw** [golang/go#45932]
### What version of Go are you using (`go version`)?

<pre>
go version go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes
```
gotip version
go version devel go1.17-9f347035 Mon May 3 19:14:16 2021 +0000 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/me/Library/Caches/go-build"
GOENV="/Users/me/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/me/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/me/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/me/mystuff/ote/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gc/sfs6hvtd1r392kn91n3jp17m0000gn/T/go-build210366927=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```bash
rm -rf /tmp/example; mkdir -p /tmp/example; cd /tmp/example
tee -a go.mod <<EOF
module example
go 1.16
require github.com/pkg/errors v0.9.1 //indirect
EOF

tee -a main.go <<EOF
package main
import "github.com/pkg/errors"
func main(){errors.New("hi")}
EOF
go mod tidy
```

### What did you expect to see?
- The `//indirect` comment should be removed from the require stanza

### What did you see instead?
- The `//indirect` comment is replaced with a `//ct` comment

**Comment by komuw** [comment]
My guess is that this is caused by the call to `len()` here; https://github.com/golang/mod/blob/858fdbee9c245c8109c359106e89c6b8d321f19c/modfile/rule.go#L509-L514 which expects the `//indirect` comment to always have a space between `//` and `indirect`

**Comment by bcmills** [comment]
[CL 316569](https://golang.org/cl/316569) fixes this in the `x/mod` repo (thanks, @komuw!). I'll vendor it into the `cmd` module to fix the bug in `go mod tidy` and add a regression test at that point.
