### ISSUE TITLE
cmd/go: internal error: a requirement on <package> is needed but was not added during package loading

### ISSUE THREAD

**Issue by kevinburkemeter** [golang/go#45952]
On tip, I'm seeing the following error when I run this command:

```
$ make vendor
GO111MODULE=on go mod vendor && GO111MODULE=on go mod tidy
go: internal error: a requirement on github.com/rcrowley/go-metrics@v0.0.0-20201227073835-cf1acfcdf475 is needed but was not added during package loading
make: *** [Makefile:29: vendor] Error 1
```

I don't have time right now to investigate further or set up a reduced test case unfortunately. I was able to resolve the issue by adding the package in question to the go.mod file as e.g.

```master
github.com/rcrowley/go-metrics master
```

and then re-running the "make vendor" command above. I had to repeat this for each dependency.

It *may* have to do with:

- package A imports package B in go.mod, which imports package C in its own go.mod
- package A drops direct dependency on package B but it still exists in the vendor directory

**Comment by jayconrod** [comment]
cc @bcmills @matloob

**Comment by bcmills** [comment]
@kevinburkemeter, what `go` version is declared in your module's `go.mod` file? (I'm assuming it's something ≤1.16?)

**Comment by kevinburkemeter** [comment]
> @kevinburkemeter, what go version is declared in your module's go.mod file? (I'm assuming it's something ≤1.16?)

1.16
