### ISSUE TITLE
x/pkgsite: Project not showing up on pkg.go.dev after attempts made in vain

### ISSUE THREAD

**Issue by dsoprea** [golang/go#45969]
### What version of Go are you using (`go version`)?

1.16.3

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

amd64, gccgo

### What did you do?

Did a targeted fetch:

```
$ go get github.com/dsoprea/go-webp-image-structure@f9047d252ea5a7142d195918df2759b2dd657b6d
go: downloading github.com/dsoprea/go-webp-image-structure v0.0.0-20210505121052-f9047d252ea5
go get: added github.com/dsoprea/go-webp-image-structure v0.0.0-20210505121052-f9047d252ea5
```

Tried the pkg.go.dev page for the project and it's still not present.

Hit the proxy URL to try and induce an update:

https://proxy.golang.org/github.com/dsoprea/go-webp-image-structure/@v/v0.0.0-20210505121052-f9047d252ea5.info

```
{"Version":"v0.0.0-20210505121052-f9047d252ea5","Time":"2021-05-05T12:10:52Z"}
```

A search still shows not present:

(https://pkg.go.dev/search?q=github.com%2Fdsoprea%2Fgo-webp-image-structure)

![image](https://user-images.githubusercontent.com/715626/117143355-bb9c4f80-ad7e-11eb-98a5-3ef137801b05.png)

### What did you expect to see?

Package documentation.

### What did you see instead?

Missing documentation:

![image](https://user-images.githubusercontent.com/715626/117143508-ea1a2a80-ad7e-11eb-932d-b153b2735db7.png)

What am I missing?

**Comment by julieqiu** [comment]
I'm seeing this package now at https://pkg.go.dev/github.com/dsoprea/go-webp-image-structure:

![image](https://user-images.githubusercontent.com/5943521/117174095-602c8a80-ad9b-11eb-9bca-a9a52ec63456.png)

For future reference, you can also try visiting a specific version of the package (for example, https://pkg.go.dev/github.com/dsoprea/go-webp-image-structure@v0.0.0-20210505121052-f9047d252ea5) to fetch a version of the package that is not on pkg.go.dev.

**Comment by dsoprea** [comment]
Okay. Good to know. It'd be really helpful to document that in one or both of those "not found"-type pages.
