### ISSUE TITLE
x/tools/gopls: memoize allKnownSubdirs on the snapshot

### ISSUE THREAD

**Issue by stamblerre** [golang/go#45974]
@findleyr profiled didChange and found that this function was taking up the most time in `didModifyFiles` events, so we should cache the directories on the snapshot.

**Comment by findleyr** [comment]
This was mentioned in #45686, but a forthcoming benchmark suggests that allKnownSubdirs accounts for more than half of the time it takes to process (but not diagnose) a file change.
