### ISSUE TITLE
x/blog , x/pkgsite: Remove "Black Lives Matter" Banner

### ISSUE THREAD

**Issue by nilsocket** [golang/go#45970]
I understand this is sensitive topic.

Please consider removing "Black Lives Matter" Banner.

Reasoning:
A Technical project is supposed to be a **neutral platform**, not a place to further any political narrative/agenda.

From my limited understanding, above problem is specific to United States of America and world doesn't necessarily revolve around United States of America.

Thank you.

**Comment by ALTree** [comment]
Asked many times, see #39850, #43006, https://github.com/golang/go/issues/41094#issuecomment-682574230.

**Comment by theckman** [comment]
@nilsocket it's not limited to the US. Folks like F1 racer Lewis Hamilton, a citizen of the United Kingdom, also support the cause.

**Comment by nilsocket** [comment]
Personally I don't consider BLM as humanity problem.
I consider it as political movement.

I think people who consider it as humanity are just too naive.

> it's not limited to the US

I think one say it, if atleast 5 - 10% of population is involved in it.

**Comment by ALTree** [comment]
This is not the right place to discuss BLM.
