### ISSUE TITLE
cmd/go: 'go get -d' in a lazy module should promote transitive imports of the named package(s) to roots

### ISSUE THREAD

**Issue by bcmills** [golang/go#45979]
(This is a pre-release cleanup needed for #36460, noticed during testing.)

In `go 1.17` modules, we maintain the invariant that the modules providing all packages transitively imported by the main module are listed explicitly in its `go.mod` file.

`go get` currently adds a requirement on the module(s) providing the package(s) requested on the command line, but *not* their transitive imports. (This matches the behavior of `go get` in pre-1.17 modules.)

However, I expect that most users who run `go get` on a package will intend to actually import that package. If that is the case, then if they are in the default `-mod=readonly` mode their builds involving that package will fail until they run `go mod tidy`.

I would rather that `go get` make the requested package importable right away, with `go mod tidy` only needed to clean up any extraneous dependencies afterward. To make that work for `go 1.17` modules, `go get` should be changed to add explicit requirements for all of the indirectly-imported packages too.

CC @jayconrod @matloob

**Comment by dmitshur** [comment]
@bcmills Checking in from a release meeting as this a release blocking issue,  are there updates on this? Thanks.

**Comment by bcmills** [comment]
I'm still planning to do this. Honestly, I'm not sure that it even needs to block the beta — `go get` doesn't get a whole lot of user testing anyway, and following it with `go mod tidy` is fine as a workaround.

**Comment by bcmills** [comment]
`go get` in a `go 1.17` module now pulls in the transitive dependencies of its arguments, but perhaps it should also fix up the direct/indirect split as well. (Currently it marks even its arguments as `indirect`, which puts the new dependencies in a separate section due to #45965.) Leaving open for now while we (actively) consider what that behavior should be.

**Comment by bcmills** [comment]
On further consideration: it's easy to promote an `indirect` dependency to `direct`, by invoking `go get -d` or similar on the package that imports it. So, for example:
```
go get -d -t ./...
```
will remove the `// indirect` markings from all dependencies that are actually direct.

On the other hand, it's difficult to _demote_ a direct dependency to `// indirect`. Only `go mod tidy` and `go mod vendor` do that, and they're both rather large hammers.

So let's keep the default at `// indirect`, because it's not obvious that one is a better default than the other and starting as `indirect` is less disruptive for users to fix.

**Comment by bcmills** [comment]
Given the above reasoning, I'm calling this issue fixed.
