### ISSUE TITLE
runtime-gdb.py for LLDB?

### ISSUE THREAD

**Issue by nathan-fiscaletti** [golang/go#45981]
Is there a version of [`runtime-gdb.py`](https://golang.org/src/runtime/runtime-gdb.py) that will work with LLDB instead of GDB? I'd like to get the same type of functionality for debugging Go programs in LLDB as is provided to GDB using that script.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
