### ISSUE TITLE
net/url.Url: url.Path and url.RawPath not convertable for complex content

### ISSUE THREAD

**Issue by je4** [golang/go#45988]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 windows/amd64

</pre>

### Does this issue reproduce with the latest release?

go1.16 is latest version

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\micro\AppData\Local\go-build
set GOENV=C:\Users\micro\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\micro\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\micro\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\daten\go\go1.16
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\daten\go\go1.16\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\micro\AppData\Local\Temp\go-build2337608274=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

for a software project which deals with local and remote resources i need to wrap local files in url's.
these local files contain '%', '+' and ' ' characters. the `url.Parse()` function needs that the complex filename is escaped (error on '%' if part of filename) .

```
package main

import (
	"fmt"
	"net/url"
)

func main() {

	// Parse does not work with unescaped url's
	_, err := url.Parse("file://h/x%x x+x")
	fmt.Printf("cannot parse file://h/%s: %v\n", "x%x x+x", err)

	urlstr := "file://h/" + url.QueryEscape("x%x x+x")
	fmt.Printf("urlstr: %s\n", urlstr)
	u, _ := url.Parse(urlstr)

	fmt.Printf("u.String(): %s\n", u.String())
	fmt.Printf("u.Path: %s\n", u.Path)
	fmt.Printf("u.RawPath: %s\n", u.RawPath)
	fmt.Printf("u.EscapedPath(): %s\n", u.EscapedPath())
	unescapedPath, _ := url.QueryUnescape(u.EscapedPath())
	fmt.Printf("url.QueryUnescape(u.EscapedPath()): %s\n", unescapedPath)
}
```

### What did you expect to see?

the `u.Path` should contain a value, which is convertable into `u.RawPath` and vice versa.

### What did you see instead?

`u.Path` contains two '+' characters instead of blank and plus

Output:
<pre>
cannot parse file://h/x%x x+x: parse "file://h/x%x x+x": invalid URL escape "%x "
urlstr: file://h/x%25x+x%2Bx
u.String(): file://h/x%25x+x%2Bx
u.Path: /x%x+x+x
u.RawPath: /x%25x+x%2Bx
u.EscapedPath(): /x%25x+x%2Bx
url.QueryUnescape(u.EscapedPath()): /x%x x+x
</pre>

**Comment by seankhliao** [comment]
A query escape is not a path escape, if you need RawPath set it directly

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
