### ISSUE TITLE
x/website/cmd/golangorg: third party package documentation does not load in the browser any more

### ISSUE THREAD

**Issue by kevinburkemeter** [golang/go#45986]
For years now, I have laid out source code on my local computer by setting GOPATH to /Users/kevin so repositories get checked out to /Users/kevin/src/github.com/inconshreveable/log15, for example. I frequently need to inspect the source code of third party dependencies, and keeping them all checked out in GOPATH mode is the easiest way to inspect/grep/edit the source code I need.

I also run a godoc (now, golangorg) browser locally to view the documentation for different packages, and to be able to test what documentation will look like in a browser without needing to push it to a remote and then view via e.g. godoc.org. I wrote a shim that wraps around the godoc command that I use to automate starting/opening a browser, available here https://github.com/kevinburke/godocdoc. So I can go to e.g. http://localhost:6060/pkg/github.com/inconshreveable/log15 and view the documentation for that package with near-instantaneous reloading when I edit the documentation.

Some time recently, that stopped working. If I start the golangorg binary and try to visit http://localhost:6060/pkg/github.com/inconshreveable/log15, here's what I get:

<img width="651" alt="File github com:inconshreveable:log15 - The Go Programming Language 2021-05-05 21-02-58" src="https://user-images.githubusercontent.com/51895701/117240279-4d3ea800-ade5-11eb-98b3-c6c1717641ef.png">

I'd appreciate instructions on what I need to do in order to view source code in a browser locally. I'm happy to provide more information about my setup if that's helpful.

**Comment by seankhliao** [comment]
[godoc](golang.org/x/tools/cmd/godoc) continues to work, golangorg isn't intended to serve documentation

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by kevinburkemeter** [comment]
To be clear, I was reporting a regression, the command used to serve documentation and now it doesn't.

**Comment by seankhliao** [comment]
golang.org no longer needs to serve documentation, so the removal of is intended
