### ISSUE TITLE
proposal: spec: non-empty interface type for multiple case in type switch

### ISSUE THREAD

**Issue by krasin** [golang/go#460]
<pre>Before filing a bug, please check whether it has been fixed since
the latest release: run &quot;hg pull -u&quot; and retry what you did to
reproduce the problem.  Thanks.

What steps will reproduce the problem?
Try to compile attached file. It will fail with:
main.go:13: v.IsNil undefined (type reflect.Value has no field IsNil)

What is the expected output? What do you see instead?
It would be nice if it is compilable. The core of example is the switch:

var a reflect.Value
switch v := a.(type) {
case *reflect.InterfaceValue,
        *reflect.PtrValue:
        if v.IsNil() {
                fmt.Printf(&quot;null&quot;)
        }
}
Both reflect.InterfaceValue and reflect.PtrValue has IsNil method but if 
compiler sees the multiple type case, it suppose that v is just 
reflect.Value and could not find IsNil method.

What is your $GOOS?  $GOARCH?
linux, amd64

Which revision are you using?  (hg identify)

affe0f093696+ tip

Please provide any additional information below.
This issue was discussed during review of 
<a href="http://golang.org/cl/179125">http://golang.org/cl/179125</a> with Russ Cox.</pre>

Attachments:
1. <a href="https://storage.googleapis.com/go-attachment/460/0/main.go">main.go</a> (203 bytes)

**Comment by CostaOnGit** [comment]
Adding code example
```
package main

import "fmt"

func main() {
	var v uint8 = 0
	var t interface{} = v

	fmt.Printf("v: %T %T", v, &v)
	fmt.Println()
	fmt.Printf("t: %T %T", t, &t)
	fmt.Println()
	switch t := t.(type) {
	case int8, uint8:
		fmt.Printf("BUG : %T %T", t, &t)
		fmt.Println()
	}
	switch t := t.(type) {
	case uint8:
		fmt.Printf("Correct : %T %T", t, &t)
	case int8:
		fmt.Printf("Does'nt display : %T %T", t, &t)
		fmt.Println()
	default:
		fmt.Println("Won't print")
	}
}
```
Output
v: uint8 *uint8
t: uint8 *interface {}
BUG : uint8 *interface {}
Correct : uint8 *uint8

**Comment by ianlancetaylor** [comment]
@CostaOnGit I'm sorry, I don't understand your example.  Given two different cases, what else could the type be?  Are you suggesting that we should implicitly copy the code for each case?

**Comment by ianlancetaylor** [comment]
This suggestion seems to imply one of

1. copying the case code for each type, or
2. if all the cases are interface types, constructing the intersection of the interface types and using that as the type for the case, or
3. for any type, constructing a new interface type that is the intersection of all the methods of the types in the case.

None of these seem like likely changes to the language.  I'm going to close this.  If you disagree, please comment.  Thanks.
