### ISSUE TITLE
cmd/link: SIGSEGV running 'openshift-install version' for release-4.8 using external linking on PPC64LE [1.15 backport] 

### ISSUE THREAD

**Issue by toothrot** [golang/go#46002]
@pmur requested issue #45850 to be considered for backport to the next 1.15 minor release.

> @gopherbot this affects building openshift with go1.16, please consider a backport.

**Comment by dmitshur** [comment]
Approving per discussion in a release meeting. This backport applies to both 1.16 (#45927) and 1.15 (this issue).
