### ISSUE TITLE
crypto/tls: same x509 certificate in different tls connections costs too much memory

### ISSUE THREAD

**Issue by nejisama** [golang/go#46035]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

In our production environment, we use tls to communicate between applications. A client application will access dozens to thousands of server applications, and server applications will have dozens to thousands of machines.
Each machine will maintain one or two long TCP connections for communication. A client may have tens of thousands of tls connections, and each connection will save a copy of the server's x509 certificate information, resulting in a large amount of memory usage.
For the same server application, the certificates held are the same. The actual number of different certificates is much lower than the number of connections, but the same size of memory is still allocated for each connection in the memory.
For the mtls(Mutual TLS) scenario, the server's tls connection may also save the client's certificate, which will cause the same memory consumption, and the number of client certificates is also much lower than the number of client connections.

### What did you expect to see?

The same x509 certificate is reused through caching, and memory is no longer calculated and allocated separately for each connection, which reduces the memory usage.

### What did you see instead?

Each connection will parse and save the x509 certificate information, which takes up a lot of memory.

**Comment by slrz** [comment]
Aren't those parsed certificates also passed to user-provided code? Like with tls.Config's VerifyPeerCertificate, for example? What happens when that code mutates the cached certificates?

**Comment by andrius4669** [comment]
Not to mention that they're never deleted...

**Comment by nejisama** [comment]
> Aren't those parsed certificates also passed to user-provided code? Like with tls.Config's VerifyPeerCertificate, for example? What happens when that code mutates the cached certificates?

The x509.Certificate is stateless,I think if the cached certificate is also used elsewhere, it will have no effect

**Comment by nejisama** [comment]
> Not to mention that they're never deleted...

Yes, the current cache does not provide a delete/expiration plan.  Maybe set a maximum cache size is a simple way to control the cache memory use, but it is difficult to determine what this value is

**Comment by nejisama** [comment]
> Not to mention that they're never deleted...

How about add an expire time to the cache. The cache keeps the time that cache was cleaned, Whenever the cache needs to be updated, it is judged whether the expiration time is reached. If it is, the previous cache is cleared.

**Comment by nejisama** [comment]
> Aren't those parsed certificates also passed to user-provided code? Like with tls.Config's VerifyPeerCertificate, for example? What happens when that code mutates the cached certificates?

A way to not increase the export function is to directly put the cache in the x509.ParseCertificate?

**Comment by taoyuanyuan** [comment]
https://github.com/golang/go/blob/326a7925179ea669aa9f947dda82e425673cb220/src/net/interface.go#L179
ipv6ZoneCache has an expire time to the cache too.

**Comment by taoyuanyuan** [comment]
ping @rolandshoemaker  @FiloSottile

**Comment by nejisama** [comment]
ping @FiloSottile

**Comment by nejisama** [comment]
hello， any suggestions for this issue/ pr ? @FiloSottile @cagedmantis

**Comment by xdg** [comment]
I'm also interested in this, as we've also seen it in production.

I'd prefer an approach that adds an x509 cache field to the `tls.Config` struct (defaulting to nil) along with an associated interface.  Then users can opt into a cache, taking responsibility for the integrity of the data within and for designing their own eviction strategies.

**Comment by nejisama** [comment]
we found boring ssl have certificate cache too, see https://boringssl.googlesource.com/boringssl/+/HEAD/PORTING.md#crypto_buffer
```
With the standard OpenSSL APIs, when making many TLS connections, the certificate data for each connection is retained in memory in an expensive X509 structure. Additionally, common certificates often appear in the chains for multiple connections and are needlessly duplicated in memory.
```

**Comment by taoyuanyuan** [comment]
@rolandshoemaker  @FiloSottile 
Is the Golang team so arrogant? It's amazing!
no manners guys!
