### ISSUE TITLE
x509.DecryptPEMBlock Deprecated

### ISSUE THREAD

**Issue by alifpay** [golang/go#46031]
### What version of Go are you using (`go version`)?

<pre>
$ go 1.16.3

</pre>

### Does this issue reproduce with the latest release?

instead of this func 
x509.DecryptPEMBlock

how or which func to use ?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
