### ISSUE TITLE
runtime/cgo Undefined symbols for architecture arm64: _darwin_arm_init_mach_exception_handler

### ISSUE THREAD

**Issue by UnivexDont** [golang/go#46032]
### What version of Go are you using (`go version`)?
<pre>
go version go1.16.3 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/donto/Library/Caches/go-build"
GOENV="/Users/donto/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/donto/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/donto/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sh/qsg17h7x3137bt_p6qcqh1g80000gn/T/go-build4147123810=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

go build -trimpath -ldflags '-X "github.com/Dreamacro/clash/constant.Version=4e9e4b" -X "github.com/Dreamacro/clash/constant.BuildTime=2021-05-07-1435"' -buildmode=c-archive -o goClash_arm64.a

### What did you expect to see?

Build successed && generate .a for iOS

### What did you see instead?
runtime/cgo
Undefined symbols for architecture arm64:
  "_darwin_arm_init_mach_exception_handler", referenced from:
      _x_cgo_init in _x004.o
  "_darwin_arm_init_thread_exception_port", referenced from:
      _threadentry in _x004.o
      _x_cgo_init in _x004.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):

**Comment by AlexRouSg** [comment]
Your go version says `amd64` but your output says `arm64`
Please clarify whether you set `GOOS` and `GOARCH`

Also is there a reason you are not using `golang.org/x/mobile` ?

**Comment by UnivexDont** [comment]
already fixed

**Comment by jaroslavas** [comment]
So how have you fixed it?

**Comment by wuhan005** [comment]
> So how have you fixed it?

I switch my Go version from `go1.16.x` to `go1.14`. Then it works.

**Comment by ChristianOrgler** [comment]
That's not working for M1 MacBooks tho - any suggestion on how to fix it?

`go version go1.16.5 darwin/arm64`

Error:

```
go build -ldflags=-w -trimpath -v -o "/Users/someone/Library/Developer/Xcode/DerivedData/something-bipqhwawbdbbciblevyubvleyofz/Build/Intermediates.noindex/something.build/Debug-iphonesimulator/wireguard-go-bridge/libwg-go-arm64.a" -buildmode c-archive
runtime/ago
# runtime/cgo
Undefined symbols for architecture arm64:
  "_darwin_arm_init_mach_exception_handler", referenced from:
      _x_cgo_init in _x004.o
  "_darwin_arm_init_thread_exception_port", referenced from:
      _threadentry in _x004.o
      _x_cgo_init in _x004.o

ld: symbol(s) not found for architecture arm64
```

**Comment by mix717** [comment]
> That's not working for M1 MacBooks tho - any suggestion on how to fix it?
> 
> `go version go1.16.5 darwin/arm64`
> 
> Error:
> 
> ```
> go build -ldflags=-w -trimpath -v -o "/Users/someone/Library/Developer/Xcode/DerivedData/something-bipqhwawbdbbciblevyubvleyofz/Build/Intermediates.noindex/something.build/Debug-iphonesimulator/wireguard-go-bridge/libwg-go-arm64.a" -buildmode c-archive
> runtime/ago
> # runtime/cgo
> Undefined symbols for architecture arm64:
>   "_darwin_arm_init_mach_exception_handler", referenced from:
>       _x_cgo_init in _x004.o
>   "_darwin_arm_init_thread_exception_port", referenced from:
>       _threadentry in _x004.o
>       _x_cgo_init in _x004.o
> 
> ld: symbol(s) not found for architecture arm64
> ```

I know it's been almost a year ago but.. :) 
have you managed to fix it?

**Comment by blacktop** [comment]
ping same-zeezes

**Comment by drew-512** [comment]
Getting this here too

**Comment by drew-512** [comment]
Tried a number of things a crack this but unfortunately not:

1) tried building out go library's (.a) on both an `amd64` and `arm64` (M1) macs with go 1.19.4 -- same results
2) tried Xcode on 13.4 on OS 12.4 (M1) and on Xcode (11.3) on OS 10.14 (Mac Pro Mojave) -- same results  

Losing scary amounts of time on this issue, any help would be appreciated.
