### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by artemvarakin** [golang/go#46039]
looks like one of "each" words is excess in the first line of doc for WalkFunc https://golang.org/pkg/path/filepath/#WalkFunc

**Comment by ZekeLu** [comment]
fixed in #45905

**Comment by ALTree** [comment]
As @ZekeLu pointed out, this was already fixed on tip (https://tip.golang.org/pkg/path/filepath/#WalkFunc); closing here since there's nothing else to do.
