### ISSUE TITLE
encoding/xml cannot correctly encode form feed and vertical tab character

### ISSUE THREAD

**Issue by Olament** [golang/go#46048]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.16.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\user\AppData\Local\go-build
set GOENV=C:\Users\user\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\user\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\user\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\user\Desktop\read_test\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\user\AppData\Local\Temp\go-build1250888497=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

```golang
type Struct struct {
	XMLName xml.Name `xml:"struct"`
	Name1   string   `xml:"name1"`
	Name2   string   `xml:"name2"`
}

func main() {
	p := Struct{
		Name1: "\f",
		Name2: "\v",
	}
	content, err := xml.Marshal(&p)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(content))
}
```

### What did you expect to see?

```
<struct><name1>&#xC;</name1><name2>&#xB;</name2></struct>
```

### What did you see instead?

```
<struct><name1>�</name1><name2>�</name2></struct>
```

**Comment by ZekeLu** [comment]
FYI:

> XML does not allow "control" characters (0x00-0x1F) except for TAB (0x09), CR (0x0A), and LF (0x0D).

References:

* [4.11 Binary Data and Text with Control Characters - RFC 3470](https://tools.ietf.org/html/rfc3470#section-4.11)
* [2.2 Characters - Extensible Markup Language (XML) 1.0 (Fifth Edition)](https://www.w3.org/TR/xml/#charsets)

**Comment by Olament** [comment]
@ZekeLu Thanks for pointing it out! Issue resolved.
