### ISSUE TITLE
x/tools/gopls: support completing to Elem() type for slices, etc.

### ISSUE THREAD

**Issue by muirdm** [golang/go#46045]
In the example:

```go
var f func() string
var s []string
var a [1]string
var ch chan string
var m map[int]string

var _ string = <>
```

It would be nice if `<>` preferred `s`, `a`, `ch`, and `m`. We already prefer `f`. The completion candidate should include the appropriate expression to access the element type, such as `s[<>]` for indexable things, or `<-ch` for channels.

**Comment by findleyr** [comment]
Sounds good to me. We could theoretically go further (e.g. func() []string), but that's bound to get confusing. One degree of indirection feels about right.
