### ISSUE TITLE
runtime: switch to a fast, collision-resistant hash function

### ISSUE THREAD

**Issue by patrickmn** [golang/go#4604]
<pre>SipHash is a very fast PRG for short inputs developed by J. P. Aumasson and D. J.
Bernstein, competitive in speed with MurmurHash, but with the security benefits of
cryptographically strong hash functions, i.e. finding collisions is a major undertaking
even if the IV can be guessed, or if computing digests for the set of all IVs. Thus, it
can be an ideal choice for a hash table hash function, and provides significantly better
protection against collision attacks than a non-collision resistant hash function using
a random IV. It is also extremely simple. The entire implementation:
<a href="https://131002.net/siphash/siphash24.c">https://131002.net/siphash/siphash24.c</a>

Most notably, Perl, the first by far to adopt any kind of hash function randomization
(in the early 90s, when the attack was first described) have switched to SipHash in
their 64-bit implementation.

iant suggested I file this ticket as I was commenting on the now-closed
<a href="https://golang.org/issue/2630">https://golang.org/issue/2630</a>. I plan to make a sample
implementation and provide benchmarks to back this up. I don't think this is terribly
urgent, but that it would be a better long-term solution. It might even be faster than
FNV in some cases where collisions were common since Sip has better distribution.</pre>

**Comment by bradfitz** [comment]
Fixed by @khr in https://codereview.appspot.com/7543043
