### ISSUE TITLE
Permission denied, when remove a dependency

### ISSUE THREAD

**Issue by geometryolife** [golang/go#46049]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.16.3 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/Joe/.cache/go-build"
GOENV="/home/Joe/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/Joe/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/Joe/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3979750270=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.16.3 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.16.3
uname -sr: Linux 5.4.0-47-generic
LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.31-0ubuntu9.1) stable release version 2.31.
gdb --version: GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2

</pre></details>

### What did you do?

When I enable go modules and use the commands of `go mod tidy`, `go mod download`, `go mod vendor`, etc., the dependencies of `GOMODCACHE` do not have write permission. When I want to delete manually, I must use root user or sudo privileges. But when downloading dependencies using go get, I can delete them manually.

### What did you expect to see?

When you use go mod to get dependencies, the user owner of the file should be given `w` permissions.

### What did you see instead?

It is not normal if the user cannot take control of the files they download.

For example:
`rm -rf pkg/`
rm: cannot remove 'pkg/mod/go.etcd.io/etcd@v3.3.15+incompatible/etcdmain/util.go': Permission denied

I tried other versions of go and the same problem occurred. The same problem is having in centos

**Comment by AlexRouSg** [comment]
The mod cache is intentionally made read only. 
According to https://golang.org/ref/mod#module-cache
There is a flag to make newly downloaded modules read write. `-modcacherw `

**Comment by geometryolife** [comment]
> The mod cache is intentionally made read only.
> According to https://golang.org/ref/mod#module-cache
> There is a flag to make newly downloaded modules read write. `-modcacherw`

Thank you for your patient answer, I have learned a lot, and I am sorry to report a stupid issue.
