### ISSUE TITLE
cmd/compile: wrong argument order in DIE of function that has some arguments on the stack

### ISSUE THREAD

**Issue by aarzilli** [golang/go#46055]
```
$ go version
go version devel go1.17-4c8f48ed4f Sat May 8 05:57:31 2021 +0000 linux/amd64
```

Compile this function:

```
func regabistacktest(s1, s2, s3, s4, s5 string, n uint8) (string, string, string, string, string, uint8) {
	return s1+s2, s2+s3, s3+s4, s4+s5, s5+s1, 2*n
}
```

with `-N -l`, main.regabistacktest's DIE has the arguments in the order: *s1, s2, s3, s4, n, s5* instead of *s1, s2, s3, s4, s5, n*.

cc @thanm

**Comment by thanm** [comment]
Thanks, I'll take a look. I thought we had that sorted out already, but apparently not.
