### ISSUE TITLE
run.bash: document GO_TEST_SHORT and GO_TEST_TIMEOUT_SCALE; decide what to do with GOTESTONLY

### ISSUE THREAD

**Issue by perillo** [golang/go#46054]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/manlio/.local/bin"
GOCACHE="/home/manlio/.cache/go-build"
GOENV="/home/manlio/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE="*.local"
GOMODCACHE="/home/manlio/.local/lib/go/pkg/mod"
GONOPROXY=""
GONOSUMDB="*.local"
GOOS="linux"
GOPATH="/home/manlio/.local/lib/go:/home/manlio/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2218126867=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.16.4 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.16.4
uname -sr: Linux 5.11.16-arch1-1
/usr/lib/libc.so.6: GNU C Library (GNU libc) release release version 2.33.
gdb --version: GNU gdb (GDB) 10.1
</pre></details>

### What did you do?

The `run.bash` script documents the `GO_TEST_SHARDS` and `GO_BUILDER_NAME` environment variables, but not the `GOTESTONLY`, `GO_TEST_SHORT` and `GO_TEST_TIMEOUT_SCALE` enviroment variables.

**Comment by heschi** [comment]
cc @rsc as a wild guess for an owner.

**Comment by bcmills** [comment]
CC @golang/release, since the primary use-case for most of these variables is to configure the Go dashboard builders.

**Comment by dmitshur** [comment]
By now I think it's okay to document `GO_TEST_SHORT` and `GO_TEST_TIMEOUT_SCALE` variables and their effect, even if they're meant to be used internally in the project and its build system. The documentation can convey that fact.

We should probably remove or rename `GOTESTONLY`, it's not actively used by the build system as far as I can tell, and its naming pattern is inconsistent. That should wait until we're not in the freeze.
