### ISSUE TITLE
`//go:embed <path to file in parent directory>` doesn't work

### ISSUE THREAD

**Issue by gucio321** [golang/go#46056]
### What version of Go are you using (`go version`)?

<pre>
go version go1.16.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3225948580=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
There is a following package:
- main.go
- README.md
- assets:
  - assets.go

assets.go contains package assets loaded with `//go:embed` directive.
I'd like to add `README.md` file to assets.go, but `//go:embed ../README.md` doesn't work

### What did you expect to see?
the program should compile and work fine.

### What did you see instead?
```
assets/assets.go:59:12: pattern ../README.md: invalid pattern syntax
```

**Comment by seankhliao** [comment]
This is intentional and documnted

> Patterns may not contain ‘.’ or ‘..’ or empty path elements, nor may they begin or end with a slash.

**Comment by gucio321** [comment]
@seankhliao is it possible to make it a feature request?

**Comment by seankhliao** [comment]
It still can't cross module boundaries, and if it's in the same module you can just put the embed directive in a go file in the parent directory

**Comment by gucio321** [comment]
yah, this solution is possible, but it would be a bit crazy.
I'd need to add `go:embed` directive in main.go and pass on embeded variable to my app? it doesn't seem right.

**Comment by gucio321** [comment]
@seankhliao maybe `go:embed` in module area could be allowed?

**Comment by seankhliao** [comment]
This was an explicit design decision:
> Because embed.Files implements fs.FS, it cannot provide access to files with names beginning with .., so files in parent directories are also disallowed entirely, even when the parent directory named by .. does happen to be in the same module.

ref: https://go.googlesource.com/proposal/+/master/design/draft-embed.md

**Comment by lonnyzhang423** [comment]
> It still can't cross module boundaries, and if it's in the same module you can just put the embed directive in a go file in the parent directory

@gucio321  There is no need to put embed files into child directories, `*` can be used to match everything int the current directory.

I found this in embed draft.
https://go.googlesource.com/proposal/+/master/design/draft-embed.md#go_embed-directives

**Comment by purpleidea** [comment]
There's a major bug with this:

I have the COPYING license file in my project root. But my CLI package which wants to display that text is in a subdir. And so I can't `../COPYING` to embed it. I don't think you should be able to get out of the package root, but this blocks the obvious use case that we used go-bindata for :/

**Comment by JuanigTorres** [comment]
Wouldn't it be nice if embed couldn't support predefined variables like 'dirname' or 'projectname' to avoid some unexpected bug and thus avoid the '..' or '.'?

**Comment by gucio321** [comment]
it sounds nice!
Maybe we should make a new issue @JuanigTorres ?

**Comment by JuanigTorres** [comment]
Sounds good to me!

**Comment by AlexeyInc** [comment]
> it sounds nice! Maybe we should make a new issue @JuanigTorres ?

If it's still relevant I found good answer [here](https://github.com/golang/go/issues/41191#issuecomment-686621090).

**Comment by BapiGso** [comment]
maybe do this，Create a new assets.go in the directory that needs to be packaged

```
package assets

import "embed"

//go:embed *
var Assets embed.FS
```


Then use this variable in another package

`a :=&assets.Assets`

**Comment by KernelDeimos** [comment]
I want my webpack bundle to go in a different folder than the golang source code. I want to have a `build` folder that's `.gitignore`d in the root of my repository so it's easy to keep track of transient files vs persistent ones. The fact that `go:embed` won't let me do this is arbitrary and stupid. Just let me specify a "target folder" in the virtual (embedded) filesystem instead of assuming I want to copy the file structure relative to my source file (which I almost never want to do as it is)

**Comment by gucio321** [comment]
I think, we needs to "construct" a proposal issue to solve this problem.
Here is what I think:
I understend maintainers' point of view

> Because embed.Files implements fs.FS, it cannot provide access to files with names beginning with .., so files in parent directories are also disallowed entirely, even when the parent directory named by .. does happen to be in the same module.

In my opinion its not a good justification - it sounds like saying "we can't add this, since it is not implemented"

> It still can't cross module boundaries, and if it's in the same module you can just put the embed directive in a go file in the parent directory

First of all let me note that putting `go:embed` directive in a parent directory does not look good at all. Over that, it may cause "Import cyclomatic" (or anyhow it is called in go - cant remember exacltly). 
I agree that crossing module boundries wouldn't be good.
However, in my opinion, "shouldn't cross module boundries" does not equal "could not reffer to parent directory" - thats the point here. I think that compiler should accept `..` pattern and should compile successfully as long as go:embed doesn't reffer to file above `go.mod`'s location.

Any toughts?

**Comment by seankhliao** [comment]
As mentioned before, not having `..` isn't that it's just not implemented, it goes against the contract specified by `io/fs.FS`.

**Comment by gucio321** [comment]
> As mentioned before, not having .. isn't that it's just not implemented, it goes against the contract specified by io/fs.FS.

well, but `go:embed` does not need to use `fs.FS` in fact, does it? Maybe `embed.FS` should implement `fs.FS`, but in some extended form so that it could support `..` pattern?

**Comment by tigerinus** [comment]
The best practice here is to create a package in parent level with `go:embed` var in there; then reference to this var in the child level packages.

**Comment by fripSide** [comment]
It is stupid to just match child direction. Why do you always want to teach us how to layout our projects?
