### ISSUE TITLE
x/sys/linux: Add missing ioctl call to set watchdog timeout (WDIOC_SETTIMEOUT)

### ISSUE THREAD

**Issue by lhl2617** [golang/go#46058]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64
</pre>

### What did you expect to see?
An Ioctl call in `unix/ioctl_linux.go` for setting watchdog timeout, similar to the calls written for getting watchdog info (`IoctlGetWatchdogInfo`) and keeping the watchdog alive (`IoctlWatchdogKeepAlive`).

Tentatively, the function would look like:
```
// IoctlWatchdogSettimeout modifies the watchdog timeout (in seconds) for a
// watchdog device on the fly with the SETTIMEOUT ioctl. The actual timeout
// set for the device is returned, For more information, see
// https://www.kernel.org/doc/html/latest/watchdog/watchdog-api.html.
func IoctlWatchdogSettimeout(fd, timeout int) (*int, error) {
	err := ioctl(fd, WDIOC_SETTIMEOUT, uintptr(unsafe.Pointer(&timeout)))
	return &timeout, err
}
```
`WDIOC_SETTIMEOUT` is already defined in the error constants.

**Comment by ianlancetaylor** [comment]
Can't we just use `IoctlSetPointerInt` here?  We usually only add a new `Ioctl` function if a new type is required.  We don't want to add a new function for every single `ioctl` code.

**Comment by lhl2617** [comment]
Thanks for the reply--I'm actually not sure if `IoctlSetPointerInt` would work considering the value is passed as a copy? According to https://www.kernel.org/doc/html/latest/watchdog/watchdog-api.html#setting-and-getting-the-timeout, the timeout arg may be modified after the ioctl call to the actual set timeout supported by the device

**Comment by ianlancetaylor** [comment]
Hmmmm, in that case perhaps we need a new function `IoctlSetAndRetInt` or something like that.

**Comment by lhl2617** [comment]
Sounds good--my first thought was that `IoctlSetPointerInt` should've been designed to take in the value's pointer directly, but to not break anything `IoctlSetAndRetInt` would be neat. I will open a new issue for this :)

**Comment by lhl2617** [comment]
Closing--continuing at #46060
