### ISSUE TITLE
Go json unmarshal silent errors

### ISSUE THREAD

**Issue by saul-gush** [golang/go#46064]
### What version of Go are you using (`go version`)?

<pre>
$go version go1.16.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?

This is my code where one of the struct types didn't match and was silently causing errors in an API. 
```
	if err := json.Unmarshal([]byte(c.Body()), &input); err != nil {
		log.Print(err)
		return c.Status(503).JSON(Fail{Err: "Encoding error occured"})
	}
```

It reports in the console log: json: cannot unmarshal string into Go struct field LogsBilling.bytes_received of type int

It is the same issue as this link:
https://stackoverflow.com/questions/32708717/go-when-will-json-unmarshal-to-struct-return-error/48273008

They kindly provided a Go Playground to demonstrate it:
https://play.golang.org/p/Z37o-Y9BVI

### What did you expect to see?
json unmarshal seems to know there is an error but you cant capture or deal with it with "if err:= ". I think if it knows there is an error, it should be able to set "err:=" and not silently fail with just a log to console.

**Comment by seankhliao** [comment]
The setting is available if you use a decoder with [`DisallowUnknownFields`](https://pkg.go.dev/encoding/json#Decoder.DisallowUnknownFields)

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by saul-gush** [comment]
@seankhliao I think this is still should be open, I tested it with DisallowUnknownFields and got the same error: 

```
	decoder := json.NewDecoder(bytes.NewReader(c.Body()))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&input); err != nil {
		log.Print(err)
		return c.Status(503).JSON(Fail{Err: "Encoding error occured"})
	}
```

Error response: 
json: cannot unmarshal string into Go struct field LogsBilling.bytes_received of type int

My understanding from the documentation is that it throws an error when there are unknown fields, not type mismatching on unmarshal.

**Comment by seankhliao** [comment]
DisallowUnknownFields handles the case from the SO post/playground link

as for your own code, as far as i can tell it is correctly and not silently reporting an error
