### ISSUE TITLE
net/http: rogue log output to stderr in net/http package

### ISSUE THREAD

**Issue by ross-spencer** [golang/go#46067]
### What version of Go are you using (`go version`)?

<pre>
$ go version: 1.17 (master/main branch) 

</pre>

### Does this issue reproduce with the latest release?

Yes. 

### What did you do?

```
package testpackage

// Run this using $ go test

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"net/http"
	"testing"
)

// RoundTripFuncError describes an interface type that we will then implement.
type RoundTripFuncError func(req *http.Request) *http.Response

// RoundTripError implements Golang's roundtrip interface. In this
// version we want to simulate an error when trying to connect to a
// given SPARQL server.
func (fn RoundTripFuncError) RoundTrip(request *http.Request) (*http.Response, error) {
	return fn(request), fmt.Errorf("Mock error...")
}

// NewTestClientError returns *http.Client with Transport replaced to
// avoid making real calls out to the Internet. Transport will then do
// whatever we request of it. With this version we mock an error in the
// call.
func NewTestClientError(fn RoundTripFuncError) *http.Client {
	return &http.Client{
		Transport: RoundTripFuncError(fn),
	}
}

// TestRoundtrip...
func TestRoundtrip(t *testing.T) {
	httpClient := NewTestClientError(func(req *http.Request) *http.Response {
		return &http.Response{
			StatusCode: 418,
			// Send response to be tested
			Body: ioutil.NopCloser(bytes.NewBufferString("Some response")),
			// Must be set to non-nil value or it panics
			Header: make(http.Header),
		}
	})

	req, err := http.NewRequest("GET", "http://example.com", nil)

	if err != nil {
		// Do something...
	}

	_, err = httpClient.Do(req)
	if err != nil {
		// Do something...
	}
}
```

### What did you expect to see?

Expecting an response or error to handle, or something else? (This looks like a developer's note to self, not necessarily something for everyone?) 

### What did you see instead?

Seeing an output to `stderr` which I don't think we are expected to work with. It seems like this would be more idiomatic for the caller to deal with this somewhere, and not have the package itself output anything. I'd be interested to hear more about the intentions of the authorship though.

**Comment by seankhliao** [comment]
output is

```txt
2021/05/09 17:46:09 RoundTripper returned a response & error; ignoring response
```

from

https://github.com/golang/go/blob/5203357ebacf9f41ca5e194d953c164049172e96/src/net/http/client.go#L255

cc @bradfitz @rsc @empijei

**Comment by networkimprov** [comment]
cc @fraenkel @neild

**Comment by fraenkel** [comment]
The logging is correct. It is letting you know that you violated the RoundTripper contract.
```
RoundTrip must return err == nil if it obtained
a response, regardless of the response's HTTP status code.
A non-nil err should be reserved for failure to obtain a
response.
```

**Comment by ross-spencer** [comment]
Thanks @fraenkel. That provides helpful advice how to resolve that in my tests. I didn't realize logging was generally recommended in packages. Thanks for the feedback. Should I close this issue?

**Comment by fraenkel** [comment]
It isn't but there is little else one can do here. Given no error can be returned which would also be rude, a panic is just as bad. The logging was sufficient for you to notice which is its intent.

**Comment by bradfitz** [comment]
Yeah, I still think logging is the best compromise there. It's helpful but not too intrusive, but enough to get noticed.
