### ISSUE TITLE
x/sys/unix: add consts, structs and ioctl calls from `<mtd/mtd-user.h>`

### ISSUE THREAD

**Issue by lhl2617** [golang/go#46063]
### What did you expect to see?

It would be convenient to have MTD user space constants, utils and ioctl operations in the package.
An example use case is in Facebook's OpenBMC repo [here](https://github.com/facebook/openbmc/blob/helium/tools/flashy/lib/flash/flashcp/flashcp.go).

The proposed addition entails:
- Adding `#include <mtd/mtd-user.h>` in `unix/mkerrors.sh` with the sufficient regex changes
- Adding `#include <mtd/mtd-user.h>` in `unix/linux/types.go` with the necessary bindings (`C.struct_XXX` for structs, constants for enum)
- Adding the necessary `ioctl` functions in `unix/ioctl.go` for unique types.

**Comment by lhl2617** [comment]
According to @robpike in https://github.com/golang/go/issues/14873: 
> My point is that I don't want to see ioctl get helpers to make it look nice. It really doesn't need int and uint and *Termio and *Whatever helpers. The caller can do the conversion. It may be uglier but it will actually be faster, and anyway ioctl is hideous and I prefer not to hide that fact.

If necessary I think I will back off the `ioctl` functions change in `unix/ioctl.go` and leave the conversions to the caller.

**Comment by ianlancetaylor** [comment]
For better or for worse, I think that golang.org/x/sys/unix has clearly gone in a different direction since Rob's comment from five years ago.

**Comment by robpike** [comment]
Oh, worse. Yes, worse.

**Comment by lhl2617** [comment]
I've backed out the ioctl wrappers in
https://go-review.googlesource.com/c/sys/+/318211/

I'll be happy to maintain another package using these structs and constants--easier and better to not further pollute x/sys
