### ISSUE TITLE
cmd/go: panic in mod tidy when requiring main module

### ISSUE THREAD

**Issue by seankhliao** [golang/go#46078]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.17-c14ecac Sun May 9 17:07:22 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

1.16.4 has a different error

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/arccy/.cache/go-build"
GOENV="/home/arccy/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/arccy/.data/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/arccy/.data/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/arccy/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/arccy/sdk/gotip/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.17-c14ecac Sun May 9 17:07:22 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/arccy/tmp/testrepo-425/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3574983894=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

add a `require` for the main module, run `go mod tidy`

```sh
main » cat go.mod
module go.seankhliao.com/testrepo-425

go 1.17

require go.seankhliao.com/testrepo-425 v0.0.0

main » cat main.go
package main

func main() {}

main » go version
go version devel go1.17-c14ecac Sun May 9 17:07:22 2021 +0000 linux/amd64

main » go mod tidy
panic: newRequirements called with untrimmed build list: rootModules[0] is Target

goroutine 1 [running]:
cmd/go/internal/modload.newRequirements(0x0, {0xc00013c380, 0x1, 0x1}, 0xc0001a1fb0)
	/home/arccy/sdk/gotip/src/cmd/go/internal/modload/buildlist.go:103 +0x5f9
cmd/go/internal/modload.updateLazyRoots({0xa688a0, 0xc00011a000}, 0xc0001a1fb0, 0xc00012c230, {0x0, 0x0, 0x6}, {0x0, 0x0, 0x0})
	/home/arccy/sdk/gotip/src/cmd/go/internal/modload/buildlist.go:780 +0x5ed
cmd/go/internal/modload.updateRoots({0xa688a0, 0xc00011a000}, 0x203000, 0x203000, {0x0, 0xc0001a1f80, 0xc0001c2d00}, {0x0, 0x0, 0x0})
	/home/arccy/sdk/gotip/src/cmd/go/internal/modload/buildlist.go:524 +0x71
cmd/go/internal/modload.requirementsFromModFile({0xa688a0, 0xc00011a000})
	/home/arccy/sdk/gotip/src/cmd/go/internal/modload/init.go:696 +0x5d2
cmd/go/internal/modload.loadModFile({0xa688a0, 0xc00011a000})
	/home/arccy/sdk/gotip/src/cmd/go/internal/modload/init.go:440 +0x3ff
cmd/go/internal/modload.LoadPackages({0xa688a0, 0xc00011a000}, {{0x0, 0x0}, 0xc0001a1cb0, 0x1, 0x1, 0x1, 0x0, 0x1, ...}, ...)
	/home/arccy/sdk/gotip/src/cmd/go/internal/modload/load.go:315 +0x230
cmd/go/internal/modcmd.runTidy({0xa688a0, 0xc00011a000}, 0xc000146270, {0xc000114170, 0x0, 0x7ffea9940cbe})
	/home/arccy/sdk/gotip/src/cmd/go/internal/modcmd/tidy.go:82 +0x1c9
main.main()
	/home/arccy/sdk/gotip/src/cmd/go/main.go:201 +0xadf

main » go1.16.4 mod tidy
go: go.seankhliao.com/testrepo-425@v0.0.0: reading go.seankhliao.com/testrepo-425/go.mod at revision v0.0.0: unknown revision v0.0.0
```

### What did you expect to see?

a pretty error message

### What did you see instead?

panic

### other

cc @bcmills @jayconrod @matloob

**Comment by cuonglm** [comment]
git bisect point to 9a81702b974f9d6e5569f069baaad58a0829c63a
