### ISSUE TITLE
Random Crash of compiled concurrent program without error message

### ISSUE THREAD

**Issue by rpoe** [golang/go#46072]
### What version of Go are you using (`go version`)? 

<pre>
$ go version go1.16.4 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="linux"

</pre></details>

### What did you do?
I have written a program to implementing the observer pattern with go routines and channels.
Multiple ViewHandlers subscribe to ChangeManager to receive update whenever the subject changes.
The subject is changed by input from one of the ViewHandlers.

if the ViewHandlers subscribe with a buffered channel of sufficient buffer. Everythink works fine.
It fhe ViewHandler subsribe with an unbuffered channnel, the program randomly crashes without notice.

Please see the source in line 110 and 111 of the OK version.
line 110 is OK
line 111 crashes

Failing version https://play.golang.org/p/g1Y0hm4vSW3
Version Ok.: https://play.golang.org/p/k-RClhrZbaS

### What did you expect to see?
I expect in this situation at least a panic, but not a silent dying.
Fully I expect the program to work without crash in the unbuffered version. There is no reason to use buffered channels.

### What did you see instead?
A silent crash.

And this happens at different points in time. See the values of vx Tick y

I don't expect this random behavior.

**Comment by rpoe** [comment]
The issue was happening with Go 1.9 too. The I upgraded to Go 1.16 before I reported the error.
And is is happening with g1.16 android/arm64 too.

**Comment by seankhliao** [comment]
The program exits because the main goroutine exits. Your program has both a race (see https://blog.golang.org/race-detector) and a deadlock (try blocking the main goroutine).

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
