### ISSUE TITLE
go test -coverpkg=./... ./... ,  when adding coverpkg flag,  the init function in packages that have been imported several times will be executed multiple times

### ISSUE THREAD

**Issue by liufangwai** [golang/go#46075]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>
go 1.14

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
GO111MODULE="on"
GOARCH="amd64"
...
### What did you do?

root@dev:~/liufw/testut# ll
total 24
drwxr-xr-x 5 root root 4096 May 10 12:24 .
drwxr-xr-x 3 root root 4096 May 10 11:58 ..
-rw-r--r-- 1 root root   23 May 10 12:00 go.mod
drwxr-xr-x 2 root root 4096 May 10 12:10 model
drwxr-xr-x 2 root root 4096 May 10 12:11 test1
drwxr-xr-x 2 root root 4096 May 10 12:22 test2

package dependency tree:
   test1
   -- model
   test2 
   -- model

**test1/calc1.go**:
package test1

import (
    "fmt"
    "testut/model"
)

func init() {
    fmt.Println("pkg test1")
}
....

**test2/calc2.go:**

package test2

import (
        "fmt"
        "testut/model"
)

func init() {
    fmt.Println("pkg test2")
}
....

**model/db.go**

package model

import "fmt"

func init() {
        fmt.Println("package model")
}

func ListModel() int {
        return 2
}
....

Now I run my unit test :
`go  test -coverpkg=./... ./...`

### What did you expect to see?
I expect that the init function in package model will be executed only one times . 

### What did you see instead?
Instead, the ut result is as follwing:

**package model
pkg test1
pkg test2**
Before all tests
I'm TestAdd
12--- FAIL: TestAdd (0.00s)
    calc1_test.go:53: 1 + 2 expected be 3, but 3 got
I'm TestMul
FAIL
coverage: 55.0% of statements in ./...
After all tests
FAIL	testut/test1	0.002s
**package model
pkg test2
pkg test1**
Before all tests (test2)
I'm TestAdd
12--- FAIL: TestAdd2 (0.00s)
    calc2_test.go:53: 1 + 2 expected be 3, but 3 got
I'm TestMul
FAIL
coverage: 55.0% of statements in ./...
After all tests (test2)
FAIL	testut/test2	0.002s
FAIL

you can see that the init function in package 'model' have been execute twice （the string ‘package model’ was printed twice） . If the init function in package "model" have  any logic that is executed only once such as  table creation in database , then the ut will be fail

**Comment by seankhliao** [comment]
This is working as intended, tests works by compiling each package into its own test binary and executing it. As each test binary is its own program, init is executed every time.

**Comment by liufangwai** [comment]
> This is working as intended, tests works by compiling each package into its own test binary and executing it. As each test binary is its own program, init is executed every time.

@seankhliao  If the init function in package "model" have any logic that is executed only once such as table creation in database , Is there any suggestion ？

**Comment by ZekeLu** [comment]
Sorry to reply to the closed issue.

@liufangwai I think you should do that with something provided by your database. For example, most relational database support `IF NOT EXISTS` option.

* [PostgreSQL](https://www.postgresql.org/docs/current/sql-createtable.html)
* [MySql](https://dev.mysql.com/doc/refman/8.0/en/create-database.html)

**Comment by liufangwai** [comment]
@

> Sorry to reply to the closed issue.
> 
> @liufangwai I think you should do that with something provided by your database. For example, most relational database support `IF NOT EXISTS` option.
> 
> * [PostgreSQL](https://www.postgresql.org/docs/current/sql-createtable.html)
> * [MySql](https://dev.mysql.com/doc/refman/8.0/en/create-database.html)

I use beego orm: https://beego.me/docs/mvc/model/orm.md  , the offical demo is as following:

func init() {
    // Need to register model in init
    orm.RegisterModel(new(User), new(Profile))
}

The table creation is in init function .

**Comment by liufangwai** [comment]
> Sorry to reply to the closed issue.
> 
> @liufangwai I think you should do that with something provided by your database. For example, most relational database support `IF NOT EXISTS` option.
> 
> * [PostgreSQL](https://www.postgresql.org/docs/current/sql-createtable.html)
> * [MySql](https://dev.mysql.com/doc/refman/8.0/en/create-database.html)

A few projects use beego orm: https://beego.me/docs/mvc/model/orm.md  , the offical demo is as following:

func init() {
    // Need to register model in init
    orm.RegisterModel(new(User), new(Profile))
}

The table creation is in init function .

**Comment by liufangwai** [comment]
> Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.
> 
> For questions please refer to https://github.com/golang/go/wiki/Questions

Sorry , 

> > This is working as intended, tests works by compiling each package into its own test binary and executing it. As each test binary is its own program, init is executed every time.
> 
> @seankhliao If the init function in package "model" have any logic that is executed only once such as table creation in database , Is there any suggestion ？

I'm sorry to bother you , "Each test binary is its own program" is OK, but " init is executed every time" is confusing .  In my demo if there is another package “test” that import  package "test1" and "test2",  the "test" binary will fail to generate because of repeated execution of the init in package "model" , this is not as we expectd , and  unlike the behaviour of "go test ./...".  Looking forward to your reply  @seankhliao
