### ISSUE TITLE
x/crypto/curve25519: Element.carryPropagate is in a confusingly named file

### ISSUE THREAD

**Issue by rski** [golang/go#46122]
`func (v *Element) carryPropagate()` is in a file called  `fe_arm64_noasm.go`, but the build tags in it are `go:build !arm64 || !gc || purego`, so it doesn't build for arm64. In the same vein,` fe_amd64_noasm.go` also is not meant for amd64, it has `//go:build !amd64 || !gc || purego`

**Comment by heschi** [comment]
cc @FiloSottile @katiehockman @rolandshoemaker

**Comment by FiloSottile** [comment]
The classic structure is to have

* `foo_noasm.go` with `go:build !arm64 || !gc || purego`
* `foo_amd64.go` with `go:build arm64 && gc && !purego`
* `foo_amd64.s` with `go:build arm64 && gc && !purego`

but this package has different functions implemented in assembly for amd64 and arm64, so it needs two different corresponding `go:build !$GOARCH || !gc || purego`, one for no-arm64-asm, one for no-amd64-asm.

Anyone has better ideas for how to name them?

**Comment by rski** [comment]
eh, I'm ok with this so I'll just close the issue. If anyone else feels strongly they can fix this but I'm not likely to run into it again (monkey's paw curls)
