### ISSUE TITLE
crypto/ed25519: TestAllocations fails with BoringCrypto or without optimizations

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#46134]
```
--- FAIL: TestAllocations (0.02s)
    ed25519_test.go:202: expected zero allocations, got 3e+01
```

Testing performance profiles is brittle: it currently fails on the `noopt` builder, and on the `dev.boringcrypto` branch. Even if we skipped it on both, it would fail on `go test all` if run without optimizations, like Delve does.

We can make it run only on a specific builder, but I am worried that will eventually drift out of sync with builder naming and end up never running. Better than nothing, I guess.

**Comment by odeke-em** [comment]
@FiloSottile thank you for filing this issue. We haven't done anything related for this cycle Go1.18, hence I am punting the issue to Go1.19.

**Comment by ianlancetaylor** [comment]
CC @golang/security 

Looks like this didn't make 1.19.  Moving to backlog.  Please recategorize as appropriate.
