### ISSUE TITLE
Did `json.Unmarshal` change behaviour between 1.13 and 1.15?

### ISSUE THREAD

**Issue by alexec** [golang/go#46146]
### What version of Go are you using (`go version`)?

v1.13 and v1.15

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

Linux AMB 64.

### What did you do?

I unmarshal into an existing object, and the values of a slice within that object get all jumbled up.

```golang
json.Unmarshal(data, &pod.Spec)
```

`pod.Spec` already exists and contains data.

### What did you expect to see?

I'm actually not sure. If feels like the behavior changed, but unmarshalling into an object which already contains data - well I feel like I should expect problems.

**Comment by magical** [comment]
There was a CL targeted for 1.15 that changed the behavior of `json.Unmarshal` into existing slices, but it was reverted before the final release. See https://github.com/golang/go/issues/21092 and https://github.com/golang/go/issues/39427 for details. If you are running a beta of 1.15 that could be the cause.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
