### ISSUE TITLE
x/crypto/curve25519,crypto/ed25519: avo doesn't generate go:build lines

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#46155]
Due to mmcloughlin/avo#183, the autogenerated assembly is lacking `//go:build` lines.

See #41184.

/cc @tklauser

**Comment by dmitshur** [comment]
[CL 338629](https://golang.org/cl/338629) updates this issue. CC @mmcloughlin @josharian @ianlancetaylor.

@mmcloughlin If updating the generator is a change that needs more time, should we fix it inside the Go tree by adding a temporary "//go:generate gofmt" step to run on the avo-generated files? After the generator is updated to emit gofmt'ed Go code, the extra gofmt invocation can go away. (If updating the generator is equally fast and easy, then of course there's no need for this intermediate step.)

**Comment by ianlancetaylor** [comment]
According to https://github.com/mmcloughlin/avo/issues/183, this is done for our purposes.  Thanks @mmcloughlin .
