### ISSUE TITLE
x/pkgsite: Request to remove packages

### ISSUE THREAD

**Issue by loicsaintroch** [golang/go#46165]
### What is the URL of the page with the issue?

We are currently restructuring our Go modules and packages.
Is it possible to remove the following ones please?
- <https://pkg.go.dev/github.com/nunchistudio/fragment>
- <https://pkg.go.dev/github.com/nunchistudio/smithy>
- <https://pkg.go.dev/github.com/nunchistudio/blacksmith-catalogs>
- <https://pkg.go.dev/github.com/nunchistudio/blacksmith-integrations>

Thank you for your time.

**Comment by jamalc** [comment]
Done.
