### ISSUE TITLE
cmd/vet: doesn't use the typeparams parser even with the flags / tag.

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#46163]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.17-5c3524a906 2021-05-13 15:37:53 -0500 linux/amd64
</pre>

### What did you do?

```sh
$ cat > t.go <<WUT
package main

func main() {}
type s[T any] struct {t *T}
WUT

$ go vet -gcflags=-G=3 -tags typeparams ./t.go
```

### What did you expect to see?

No errors.

### What did you see instead?

```sh
# command-line-arguments
vet: ./t.go:4:10: expected ']', found any
```

**Comment by heschi** [comment]
cc @griesemer @ianlancetaylor @findleyr

**Comment by findleyr** [comment]
You need to rebuild vet with `-tags=typeparams`. `go install -tags=typeparams cmd/vet` should work.

**Comment by findleyr** [comment]
There is no longer any build constraint required on the dev.typeparams branch, which will be merged to master once the tree opens again. I think this can be closed, please reopen if there's anything additional.
