### ISSUE TITLE
undefined: syscall.Sethostname on darwin/arm64

### ISSUE THREAD

**Issue by dcruzin** [golang/go#46166]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.4 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/davidcruz/Library/Caches/go-build"
GOENV="/Users/davidcruz/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/davidcruz/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/davidcruz/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/davidcruz/Projects/restorepoint/src/restorepoint/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mq/cbx1nvyx21zg3kb81rcss0hm0000gn/T/go-build116809091=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
Trying to run my unit tests.

### What did you expect to see?
My test run successfully and no IDE warning for undefined references

### What did you see instead? 
`undefined: syscall.Sethostname`

**Comment by seankhliao** [comment]
Sethostname is not a valid call for darwin: https://pkg.go.dev/syscall?GOOS=darwin

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
