### ISSUE TITLE
proxy.golang.org: go mod vendor, go get <package>, etc not working with "unexpected EOF" error 

### ISSUE THREAD

**Issue by charlielj88** [golang/go#46179]
### What version of Go are you using (`go version`)?

<pre>
$ go version
v1.14
</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/nexus/.cache/go-build"
GOENV="/home/nexus/.config/go/env"
GOEXE=""
GOFLAGS="-mod=vendor"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="bitbucket.global.xxx.com"
GONOSUMDB="bitbucket.global.xxx.com"
GOOS="linux"
GOPATH="/home/nexus/go"
GOPRIVATE="bitbucket.global.xxx.com"
GOPROXY="https://proxy.golang.org"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/nexus/taric-proxy/taric-proxy/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build760853934=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

run the commands, 
go mod vendor
or
go get -v -x github.com/dgrijalva/jwt-go/@v/v3.2.0+incompatible

### What did you expect to see?

(The downloading successful response)

### What did you see instead?
go: github.com/dgrijalva/jwt-go@v3.2.0+incompatible: Get "https://proxy.golang.org/github.com/dgrijalva/jwt-go/@v/v3.2.0+incompatible.mod": unexpected EOF

**Comment by seankhliao** [comment]
1.14 is no longer supported, does this still happen with a supported release (1.15, 1.16)?
(It is also more likely to a network issue on your end)

**Comment by charlielj88** [comment]
> 1.14 is no longer supported, does this still happen with a supported release (1.15, 1.16)?
> (It is also more likely to a network issue on your end)

I also suspect this may be due to some network issue. However, I could directly open/access the link https://proxy.golang.org/github.com/dgrijalva/jwt-go/@v/v3.2.0+incompatible.mod via browser/using wget in the same environment. Wondering in the backend how the commands "go get"/"go mod" differ from opening the link directly.

I havn't got change to switch to 1.15/1.16 to test in the same environment, but definitely will give it a try.

**Comment by heschi** [comment]
I suspect you have a proxy configuration that wget and your browser understand but that Go does not.

**Comment by charlielj88** [comment]
> I suspect you have a proxy configuration that wget and your browser understand but that Go does not.

Yes I have a proxy for web access. From my IDE (VS Code) it should takes the same proxy settings (http_proxy/https_proxy) and I trigger the commands from the IDE only

**Comment by bcmills** [comment]
Could this be a proxy configuration issue? It looks superficially similar to #29809. (See especially https://github.com/golang/go/issues/29809#issuecomment-487727559.)

**Comment by charlielj88** [comment]
> Could this be a proxy configuration issue? It looks superficially similar to #29809. (See especially [#29809 (comment)](https://github.com/golang/go/issues/29809#issuecomment-487727559).)

Thanks a lot! After removed the "https://" from the proxy settings, I am able to connect and download. Have a nice day!
