### ISSUE TITLE
cmd/compile: introduce CINT64 to reduce memory footprint

### ISSUE THREAD

**Issue by davecheney** [golang/go#4617]
<pre>What steps will reproduce the problem?

Compiling exp/locale/collate consumes more than 200mb on 32bit platforms like arm (more
than 300 mb on amd64). The is most likely caused by the 50k line tables.go, and its ~
300k values.

Can anything be done to reduce the amount of memory consumed when compiling this package?</pre>

**Comment by josharian** [comment]
Now that the compiler is in Go, and we have a nice union type for constant values, and there's a renewed concern about compiler speed, adding CTINT64 might be worth another look.

**Comment by martisch** [comment]
I started evaluating replacing Mpint by several type implementations: one for CTRUNE and CTINT and an implementation for each one using an int64 and one using a big.int. 

I have gotten as far as replacing Mpint by an interface and changing the compiler not to depend on internal implementation details of CTINT/CTRUNE types. I also separated out the the CTRUNE type from Mpint by embedding an Mpint into a new Mprune type. My next step is to make an Integer interface satisfying type that uses only a int64 for storage and returns an Mpint which uses big.int on overflow when operated on. Ones i have gotten as far producing a working prototype that shows memory savings i will write another update with benchmark numbers.

**Comment by griesemer** [comment]
@martisch Have you considered go/constant? We could just use it, or borrow from it heavily.

**Comment by martisch** [comment]
@griesemer 
it indeed seems better to not have two duplicated implementations of constant values.

go/constant looks like it could be used as a drop in replacement (with some extensions) for gc Val when the compiler does not depend on implementation details of Val anymore.

go/constant does not seem to support an extra rune type or nil value type.
We would need to store that info elsewhere (e.g. in an enculapsing struct) or
would it be acceptable to extend go/constant directly to support new types rune32Val, runeVal, nilVal? Alternatively we can create an internal copy and extend it with these types.

We might not need the type constants CTINT, CTRUNE, ... as such after all and can just differentiate on the Kind of value directly always.

I will try out a CL first that just uses an texteneded go/constant and modify all the users in the compiler to use the new Val interface together with some helper functions. Will write back here if i encounter any not yet known problems with that approach.

**Comment by griesemer** [comment]
@martisch A few things to consider:
- go/constant was written to work with go/types - one might be able to add rune values but I'd much prefer not to: go/constants doesn't consider types, it's about values, and I'd rather not mix the concepts. A rune32 is really an int32. A runeVal is a value of untyped rune type. Nil is not a constant value and thus not represented as such. (go/types uses different untyped "ideal" types for the basic types).

- go/constant uses big.Rat to represent floats up to a certain size, at which point it transparently switches to a big.Float representation (when the rationals get too large). Not per see an issue, but something to keep in mind.

**Comment by martisch** [comment]
>  go/constants doesn't consider types, it's about values
agreed. seems better to keep it pure and store the ideal type information in an extra field besides the constant value. This also should allow to use the go/constant package without further modifications.

**Comment by martisch** [comment]
@mdempsky is working on making `cmd/internal/gc` use the `go/constant` package which should fix this issue since `go/constants `uses an int64 representation internally for small integers. 

https://github.com/golang/go/blob/f7342596daa892400e91a407cac5843bc43dcdd0/src/go/constant/value.go#L83
