### ISSUE TITLE
x/tools/cmd/godoc: godoc doesn't list packages installed via go get

### ISSUE THREAD

**Issue by inet56** [golang/go#46193]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tnv/.cache/go-build"
GOENV="/home/tnv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/tnv/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tnv/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build477839898=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I ran `godoc` and before that i installed it via `go get golang.org/x/tools/cmd/godoc`

### What did you expect to see?
documentation for stdlib and packages that was downloaded during go get

### What did you see instead?
docs for only stdlib

**Comment by crossphoton** [comment]
Let's just confirm what you did.
You started a server with `godoc` at port 6060 then when you visit it your package isn't listed.

Can you try the following things:
- Try using the flag `-index` and search a regexp in the query box.
- Try manually searching for the package instead of using the query box.
- Try using `go doc <package>`

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
