### ISSUE TITLE
Abnormal!!  send udp on Windows

### ISSUE THREAD

**Issue by lysShub** [golang/go#46194]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\LYS\AppData\Local\go-build
set GOENV=C:\Users\LYS\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\OneDrive\code\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\OneDrive\code\go
set GOPRIVATE=
set GOPROXY=https://goproxy.io,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\LYS\AppData\Local\Temp\go-build3131887322=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

```
conn, err := net.DialUDP("udp", &net.UDPAddr{IP: nil, Port: 19987}, &net.UDPAddr{IP: net.ParseIP("3.3.3.3"), Port: 19986})
if err != nil {
	fmt.Println(err)
	return
}
da := make([]byte, 1400)
var i int
go func() {
	for {
		time.Sleep(time.Second)
		fmt.Println(i)
	}
}()
for {
	conn.Write(da)
	time.Sleep(time.Nanosecond)
	i++
}
// echo
// 67
// 133
// 198
// 265
// ...
```
Only about 64 UDP packets are sent per second！！！And about 640 on other models of computers. 

If I comment it out `time.Sleep(time.Nanosecond)`;  about 4000 UDP packets are sent per second.

**Comment by mdlayher** [comment]
Your program has a data race, and please see https://github.com/golang/go/wiki/Questions. Closing.
