### ISSUE TITLE
 internal compiler error: bad type for ... argument

### ISSUE THREAD

**Issue by mpkondrashin** [golang/go#46195]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/michael/Library/Caches/go-build"
GOENV="/Users/michael/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/michael/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/michael/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ty/8m48h3sj26jfhx_6q6bty5l80000gn/T/go-build4218180710=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Following code:
<pre>
package main

func TwoArgs(a, b int) {
}

func main() {
	var actions [2]int
	TwoArgs(actions...)
}
</pre>
Produces internal compiles error
### What did you expect to see?
I assume that "actions..." can be used instead of two arguments provided that actions is two element array.

### What did you see instead?
./bug.go:8:9: internal compiler error: bad type for ... argument: [2]int

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new

**Comment by cuonglm** [comment]
Duplicated of #45913

**Comment by ALTree** [comment]
Thanks for reporting this. As Cuong pointed out, this is a dup of #45913, which is fixed on tip (fix will be included in go1.17). Closing here.
