### ISSUE TITLE
cmd/go: embed directive doesn't work in file with leading bom

### ISSUE THREAD

**Issue by kasini3000** [golang/go#46198]
### What version of Go are you using (`go version`)?

<pre>
Golang version with bug:
go version go1.16.4 windows/amd64
go version go1.16.3 windows/amd64
go version go1.16.3 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
win，linux
</pre></details>

### What did you do?

embed file in win，linux

### What did you expect to see?
abcd1111

### What did you see instead?

invalid go:embed: build system did not supply embed configuration

----------

go source file allows utf8 with bom, all my go source code is in this format. It works well until it hits go://embed!

This problem has bothered me for a month. I was discussing it in the Golang Technology Park in China, 
and @del-xiong discovered the problem. Thanks him! ! !

# Golang version with bug:
go version go1.16.4 windows/amd64
go version go1.16.3 windows/amd64
go version go1.16.3 linux/amd64

# golang source code:

```
package main

import (
	_ "embed"
	"fmt"
)

//go:embed h1.txt
var sss string

func main() {
	fmt.Println(sss)
}
```

# error message:
xxx.go:8:3: invalid go:embed: build system did not supply embed configuration

## **how to let problem gone**
Currently,
change xxx.go source file format,from utf8withbom ,to utf8nobom,
line end is CRLF no need change.

# h1.txt content:
abcd1111

**Comment by seankhliao** [comment]
related #35726

cc @jayconrod @bcmills @matloob
