### ISSUE TITLE
go/constant: add Kind.String

### ISSUE THREAD

**Issue by mdempsky** [golang/go#46211]
This proposal is to add a

    func (Kind) String() string

method to go/constant.Kind for returning the kind's name.

Rationale: When debugging cmd/compile and go/types issues involving go/constant.Value, I'm often finding myself checking the Value.Kind(). However, printing these out with Printf simply prints the ordinal value, and I can never remember which constant kinds are which. It would be very convenient if they just printed as "Int" or "Float" directly.

/cc @griesemer

**Comment by griesemer** [comment]
Agreed. I've been annoyed by this myself often enough.
This doesn't need to be a proposal. CL forthcoming.
