### ISSUE TITLE
go/token: incorrect interval in panic messages

### ISSUE THREAD

**Issue by findleyr** [golang/go#46215]
CL 262017 improved the panic messages produced by go/token on out of bounds position queries. However, it looks like there's a typo in the bounds notation, for example: `panic: invalid Pos value 98 (should be in [1, 75[)`.  The interval should be `[1, 75]`.  This typo occurs in two locations.

Filing as an issue as this is trivial and it would be nice to fix it for 1.17.  I'll send a CL.

CC @griesemer

**Comment by griesemer** [comment]
This is not a bug, I believe. The notation [a, b[ denotes the half-open interval [a, b).

**Comment by findleyr** [comment]
> This is not a bug, I believe. The notation [a, b[ denotes the half-open interval [a, b).

The interval in question is closed.
