### ISSUE TITLE
cmd/compile: bad inlining tree emitted for function literal

### ISSUE THREAD

**Issue by thanm** [golang/go#46234]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.17-8b0901fd32 Tue May 18 07:50:25 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Only on 1.17 / tip -- this problem is not present in 1.16.

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

### What did you do?

Run this program:  https://play.golang.org/p/VZWvwkvYUGx

### What did you expect to see?

In 1.16 you get a crash on a nil pointer, e.g. 

```
$ go run repro.go
begin main
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a2245]

goroutine 1 [running]:
main.WEA.func1(0x0)
	/tmp/repro.go:17 +0x5
main.(*CM).NewA(0xc0000eef40, 0x0, 0x0, 0x4c761f, 0x3, 0x0, 0xc0000eeed0, 0x2, 0x2, 0xb, ...)
	/tmp/repro.go:30 +0x42
main.(*R).CA(0xc0000eef48, 0x0, 0x0, 0x4c761f, 0x3, 0x0, 0x0, 0xb, 0x0)
	/tmp/repro.go:37 +0xd1
main.main()
	/tmp/repro.go:52 +0xc5
exit status 2
thanm@cetina:/tmp$ 

```

### What did you see instead?

Program gets an infinite loop in traceback:

```
begin main
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x487f00]

goroutine 1 [running]:
main.WEA(...)
        /tmp/repro.go:17
main.WEA(...)
        /tmp/repro.go:17
main.WEA(...)
        /tmp/repro.go:17
main.WEA(...)
        /tmp/repro.go:17
<repeats>
```

The problem sees to be in the runtime's traceback handling of inlining -- at the point of the fault we are at

```
Dump of assembler code for function main.(*R).CA.func1:
=> 0x0000000000487f00 <+0>:	movb   $0x1,(%rax)
   0x0000000000487f03 <+3>:	retq   
```

The inlining tree for this function (from go build -gcflags=-d=pctab=pctoinline) looks like

```
-- inlining tree for "".(*R).CA.func1:
0 | -1 | "".WEA (/tmp/repro.go:37:39) pc=0
```

The problem here is that the traceback code is trying to "back up" an instruction when landing on 0x0000000000487f00 to recover the parent PC (runtime code [here](https://go.googlesource.com/go/+/1c9e587b90172e7654db897d8c938ffc665e1673/src/runtime/traceback.go#446)), but this winds up hitting the same instruction, hence we never get out of the loop.

I'm tentatively marking this as a compiler bug, can be retitled if it turns out there are other components involved.

**Comment by cherrymui** [comment]
I think the problem here is that the function literal `main.(*R).CA.func1` itself is not actually an inlined function (its containing function `main.WEA` is). So it should not have an inlining tree at all.

**Comment by thanm** [comment]
Agree-- we don't want an inl tree for main.(*R).CA.func1.  Now working on trying to understand how it is we get the inltree.

**Comment by mdempsky** [comment]
When we clone a function literal because of inlining, do we have a way for users/debuggers to distinguish stepping through a cloned function literal vs the original? It seems like we should somehow maintain that information, along with position details about where it was cloned into.

(Of course, for release purposes, I think it's more critical to have traceback working reliably than to have perfect debugging info.)

**Comment by thanm** [comment]
> When we clone a function literal because of inlining, do we have a way for users/debuggers to distinguish stepping through a cloned function literal vs the original? It seems like we should somehow maintain that information, along with position details about where it was cloned into.

This is an interesting question.  I guess my question would be "does the user care"?  If the line table info and variable locations are correct (in the sense that they show the expected line numbers, and the debugger can print the right values), then I wonder whether it matters that you're in a clone or not.

**Comment by mdempsky** [comment]
That's fair. I think most users shouldn't need to worry about this. But I'm wondering about power users (particularly us) trying to diagnose suspected miscompilation that affects inlined function literals that were optimized differently than the original.

What about the position information for newfn and newfn.Nname? Could we update their positions at least to maintain inlining stack info? Can we use inlined positions for PEXTERN/PFUNC declarations, or are they limited to PAUTO?

I think if we could at least do that, it would address my theoretical power user concern.

**Comment by thanm** [comment]
Agree that if it's not being referenced by the instructions, it seems hard to imagine that it would be triggering the original bug. But it does seem a bit odd.

**Comment by cherrymui** [comment]
Yeah, the presence of the inline tree looks suspicious. What do you mean by "it's not being referenced by the instructions"? Thanks.

**Comment by thanm** [comment]
It shows up in the dump. For example in this code:

```
func (r *R) CA(ctx context.Context, cN string, nn *nAO) (*int, error) {
	cA, err := r.cM.NewA(ctx, cN, nn, WEA(), WEA())
	if err == nil {
```
the calls to WEA() get inlined. In the dump you can see this in the second column:

```
    39        00057 (<unknown line number>)	NOP
    39        00057 (/usr/local/google/home/thanm/gobugs/46234/repro.go:37)	XORL	AX, AX
    3b      0 00059 (/usr/local/google/home/thanm/gobugs/46234/repro.go:37)	JMP	96
    3d        00061 (/usr/local/google/home/thanm/gobugs/46234/repro.go:37)	MOVQ	AX, main..autotmp_36+8(SP)
    42        00066 (/usr/local/google/home/thanm/gobugs/46234/repro.go:37)	MOVQ	main..autotmp_24+24(SP)(AX*8), DX
```

Note the "0" for the instruction at 00059.

At least that's how I'm reading it; hopefully I am not off base.

**Comment by mdempsky** [comment]
>  What do you mean by "it's not being referenced by the instructions"?

In the instruction stream, the second column is always "-1" or blank.

However, I have been able to construct alternative cases where the instructions for an inlined function literal reference where the enclosing function was inlined to. I haven't successfully gotten any of them to crash with pprof yet though.

**Comment by cherrymui** [comment]
Okay, thanks. You're right that that one is not referenced. It is odd that the unreferenced inline tree appears. Maybe something along the line of the CL above would be necessary for unified IR.

**Comment by mdempsky** [comment]
I have this program: https://go.dev/play/p/OikFLBmKguY?v=gotip

Which produces this `-d=pctab=pctoinline` output:

```
funcpctab main.stress.func1 [valfunc=pctoinline]
     0     -1 00000 (/tmp/repro.go:12)  TEXT    main.stress.func1(SB), NOSPLIT|NEEDCTXT|ABIInternal, $0-0
     0        00000 (/tmp/repro.go:12)  TEXT    main.stress.func1(SB), NOSPLIT|NEEDCTXT|ABIInternal, $0-0
     0        00000 (/tmp/repro.go:12)  FUNCDATA        $0, gclocals·g2BeySu+wFnoycgXfElmcg==(SB)
     0        00000 (/tmp/repro.go:12)  FUNCDATA        $1, gclocals·g2BeySu+wFnoycgXfElmcg==(SB)
     0      0 00000 (/tmp/repro.go:12)  MOVQ    16(DX), AX
     4        00004 (/tmp/repro.go:12)  MOVQ    24(DX), CX
     8        00008 (/tmp/repro.go:12)  MOVQ    32(DX), BX
     c        00012 (/tmp/repro.go:12)  MOVQ    8(DX), DX
    10     -1 00016 (/tmp/repro.go:22)  MOVQ    DX, main.x0(SB)
    17        00023 (/tmp/repro.go:23)  MOVQ    AX, main.x1(SB)
    1e        00030 (/tmp/repro.go:24)  MOVQ    CX, main.x2(SB)
    25        00037 (/tmp/repro.go:25)  MOVQ    BX, main.x3(SB)
    2c        00044 (/tmp/repro.go:26)  RET
    2d done
wrote 5 bytes to 0xc000817078
 02 10 01 1d 00
-- inlining tree for main.stress.func1:
0 | -1 | main.foo (/tmp/repro.go:12:9) pc=0
--
```

And that output looks like it should be "wrong". Specifically, the inlining tree entry *is* actually used for loading the closure variable values. And the `pc=0` value seems like it would point back into those same instructions within the function, leading to an infinite loop during stack walking.

But pprof doesn't seem to be getting stuck there.

**Comment by mdempsky** [comment]
Okay, manually instrumenting the runtime at https://github.com/golang/go/blob/7f632f76db65f28038b8797fbfe5e15a9f63e387/src/runtime/traceback.go#L362, I can see that loop does go on infinitely because of the inlining cycle.

**Comment by mdempsky** [comment]
Actually, I'm going to file a new issue instead of reopening this one. I don't want to cause any weird issues for milestones.

**Comment by cherrymui** [comment]
Yeah, that indeed looks like a cycle.  Profiling collects at most 32 frames, so I guess the program doesn't fall into  infinite loop, but the profile would looks like a bunch of recursive calls.

**Comment by mdempsky** [comment]
@cherrymui I was able to confirm that the loop does go infinite. We only check the `n < max` condition at the top-level, whereas the inner loop for handling PCDATA_InlTreeIndex goes until it finds a negative value (which never happens with a cycle).

**Comment by cherrymui** [comment]
Oops... Good point. Thanks.
