### ISSUE TITLE
x/pkgsite: in some cases pkg.go.dev does not show the latest version as the latest

### ISSUE THREAD

**Issue by perillo** [golang/go#46236]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/perillo/go-portable
 
### What is the problem?
 
Due to an oversight, I tagged version `v0.3.0` of github.com/perillo/go-portable without first merging from the *develop* branch.  The result is that now there are two versions (`v0.2.0` and `v0.3.0`) with the same commit and date.

After merging from *develop*, I released `v0.4.0` but pkg.go.dev still thinks that `v0.3.0` is the latest release.  It can be verified at
https://pkg.go.dev/github.com/perillo/go-portable@v0.4.0,  where the version is marked as *not at latest*.

**Comment by jba** [comment]
Looks like this is fixed.
