### ISSUE TITLE
cmd/dist: bootstrap with gccgo fails

### ISSUE THREAD

**Issue by stevenpackardblp** [golang/go#46240]
### What version of Go are you using (`go version`)?

Compiling 1.16.4 release source code using GCC 9.3 gccgo.

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

linux amd64

### What did you do?

Attempting to build the 1.16.4 release using GCC 9.3 gccgo fails with:

```console
GOOS=linux GOARCH=amd64 \
GOROOT=/tmp/go-1.16 \
GOROOT_FINAL=/opt/go-1.16 \
GOROOT_BOOTSTRAP=/opt/go \
GCCGO=gccgo \
./make.bash
Building Go cmd/dist using /opt/go. (go1.12.2 gccgo (9.3.0-2+b20210507T23473637) 9.3.0 linux/amd64)
Building Go toolchain1 using /opt/go.
# bootstrap/cmd/compile/internal/ssa
cmd/compile/internal/ssa/flags_amd64_test.s:11:10: fatal error: textflag.h: No such file or directory
   11 | #include "textflag.h"
      |          ^~~~~~~~~~~~
compilation terminated.
```

### What did you expect to see?

Successful build

### What did you see instead?

Failed build

This is the same regression as #40855 and #30771. This worked in 1.16.3, and has regressed in 1.16.4.

**Comment by apaprocki** [comment]
It appears that #40875 was entered to help detect/prevent this regression.

**Comment by cherrymui** [comment]
This is weird. I don't think there is anything changed related to this between 1.16.3 and 1.16.4. Could you double check you're building Go 1.16.4? Maybe try `./clean.bash; ./make.bash -v=3` and paste the output? Thanks.

**Comment by stevenpackardblp** [comment]
Well, this is embarrassing. I apparently copied the 1.15.12 URL and imported it as the 1.16.4 source into our system. Once I imported the correct source, everything worked as expected, so this is totally on me. Please do consider working on #40875, though!
