### ISSUE TITLE
all, cmd/internal/moddeps: tree is inconsistent state and tests aren't reporting it

### ISSUE THREAD

**Issue by dmitshur** [golang/go#46254]
There are a few mild but unexpected inconsistencies in the tree at tip (commit 15a374d5c1336e9cc2f8b615477d5917e9477440 as of this posting):

- `cmd` uses [golang.org/x/sys@v0.0.0-20210511113859-b0526f3d8744](https://go.googlesource.com/go/+/15a374d5c1336e9cc2f8b615477d5917e9477440/src/cmd/go.mod#11) but `std` selects a different, slightly older version [golang.org/x/sys@v0.0.0-20210503173754-0981d6026fa6](https://go.googlesource.com/go/+/15a374d5c1336e9cc2f8b615477d5917e9477440/src/go.mod#8)
- net/http/{h2,socks}_bundle.go aren't in sync with x/net/{http2,internal/socks} packages selected in go.mod

Tests in `cmd/internal/moddeps` exist to catch this type of skew, yet longtest builders are green and these tests are passing locally:

```
$ gotip version
go version devel go1.17-15a374d5c Wed May 19 01:09:20 2021 +0000 darwin/amd64
$ gotip test cmd/internal/moddeps
ok  	cmd/internal/moddeps	1.045s
```

This is due to a recent bug in `findGorootModules` causing no modules to be found (similar to #46027), and therefore no modules to be tested:

```
$ gotip test -v cmd/internal/moddeps
=== RUN   TestAllDependencies
--- PASS: TestAllDependencies (0.38s)
=== RUN   TestDependencyVersionsConsistent
--- PASS: TestDependencyVersionsConsistent (0.00s)
PASS
ok  	cmd/internal/moddeps	0.494s
```

(Note no subtests run.)

I'll send a CL to fix the bug, add a safety check that at very least well-known modules are found, and get the tree into a tidy state again.

CC @golang/release, @bcmills, @findleyr, @FiloSottile.

**Comment by FiloSottile** [comment]
Sorry, in hindsight I should have added the safety check myself in the first CL.
