### ISSUE TITLE
x/pkgsite: Add support for BSD-2-Clause-Patent

### ISSUE THREAD

**Issue by mjmac** [golang/go#46252]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/daos-stack/daos/src/control@v0.0.0-20210518193705-8da0cad6cb96/lib/control
 
### What is your user agent?
 
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
 
### Screenshot
 
![Screenshot (32)](https://user-images.githubusercontent.com/83737/118744255-f93eb500-b821-11eb-86cd-c05769ee6863.png)

### What did you do?
 
Just visit the page.
 
### What did you expect to see?
 
 Generated Go documentation.
 
### What did you see instead?

A message saying that documentation is not displayed due to license restrictions.

### Other details

The project's LICENSE file is here: https://github.com/daos-stack/daos/blob/master/LICENSE

**Comment by jba** [comment]
Fixed.

**Comment by mjmac** [comment]
Thank you!
