### ISSUE TITLE
Base64 decoding not working correctly

### ISSUE THREAD

**Issue by arafat-java** [golang/go#46257]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
windows/amd64
</pre></details>

### What did you do?

https://play.golang.org/p/EHg3FJ57PEt

### What did you expect to see?
{"dn":"AUTO_permtstadm13","tgt":"TGT-1534-KkhuPbAqgrGsMPcFFKc0oGcEjW7gO4qtcRGLguUf2HxYD2wSBj-cas","uid":"AUTO_permtstadm13","un":"AUTO_permtstadm13}

### What did you see instead?
{"dn":"AUTO_permtstadm13","tgt":"TGT-1534-KkhuPbAqgrGsMPcFFKc0oGcEjW7gO4qtcRGLguUf2HxYD2wSBj-cas","uid":"AUTO_permtstadm13","un":"AUTO_permtstadm13

See the missing '}' at the end
The actual base64 decoded value has  a '}' at the end

The actual (expected) decoded value can be verified from any of the online decoders like https://codebeautify.org/base64-decode

**Comment by ALTree** [comment]
```
b, _ := base64.URLEncoding.DecodeString(
```

Don't ignore errors:

> illegal base64 data at input byte 196

`URLEncoding` needs padding. Add a `=` at the end of your string and it'll work. As documented:

> RawURLEncoding is the unpadded alternate base64 encoding defined in RFC 4648. It is typically used in URLs and file names. This is the same as URLEncoding but omits padding characters. 

You want to use `RawURLEncoding` if your input has no padding.
