### ISSUE TITLE
x/tools/gopls: CLI: `gopls check go.mod` hangs

### ISSUE THREAD

**Issue by findleyr** [golang/go#46251]
The gopls command line can check go files with `gopls check foo.go`, and should theoretically be able to also check modfiles. However, `gopls check go.mod` just hangs indefinitely.

We should either add support for checking modfiles, or return a meaningful error.

CC @stamblerre

**Comment by KarthikNayak** [comment]
Interesting! @stamblerre can I pick this up?

**Comment by KarthikNayak** [comment]
I actually went ahead and created a [PR](https://github.com/golang/tools/pull/324), but I need help writing tests, can someone point to where the tests for this section of the code lie?
