### ISSUE TITLE
net/http file descriptor leak when a a PUT request fails

### ISSUE THREAD

**Issue by dowgird** [golang/go#46267]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, it's the same on go1.16.4

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/local/google/home/dowgird/.cache/go-build"
GOENV="/usr/local/google/home/dowgird/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/usr/local/google/home/dowgird/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/local/google/home/dowgird/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/google-golang"
GOSUMDB="sum.golang.org"
GOTMPDIR="/usr/local/google/home/dowgird/gotmp"
GOTOOLDIR="/usr/lib/google-golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/usr/local/google/home/dowgird/mesh-agent/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/usr/local/google/home/dowgird/gotmp/go-build1340805612=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Ran the program below on a GCP VM with guest attributes **disabled**, with `ulimit -n 256`. It repeatedly sends a http request to set a guest attribute. 

The number 256 is arbitrary, just to demonstrate that the file descriptors are leaking. I am not sure what is the exact kind of HTTP error that triggers this behavior. It does not occur when guest attributes are enabled (and the PUT request succeeds).
```
package main

import (
        "fmt"
        "net/http"
        "strings"
)

func setGuestAttribute() error {
        url := "http://metadata.google.internal/computeMetadata/v1/instance/guest-attributes/foo/bar"
        client := &http.Client{}
        req, err := http.NewRequest("PUT", url, strings.NewReader("baz"))
        if err != nil {
                return err
        }
        req.Header.Add("Metadata-Flavor", "Google")
        _, err = client.Do(req)
        return err
}

func main() {
        for i := 0; i < 258; i++ {
                err := setGuestAttribute()
                if err != nil {
                        fmt.Printf("err:\n%v\n", err)
                }
        }
}

```

### What did you expect to see?
Maybe some errors but not ones about exhausting the file descriptor limit.
### What did you see instead?

```
Put "http://metadata.google.internal/computeMetadata/v1/instance/guest-attributes/foo/bar": dial tcp: lookup metadata.google.internal: too many open files
err:
Put "http://metadata.google.internal/computeMetadata/v1/instance/guest-attributes/foo/bar": dial tcp: lookup metadata.google.internal: too many open files
err:
Put "http://metadata.google.internal/computeMetadata/v1/instance/guest-attributes/foo/bar": dial tcp: lookup metadata.google.internal: too many open files
err:
Put "http://metadata.google.internal/computeMetadata/v1/instance/guest-attributes/foo/bar": dial tcp: lookup metadata.google.internal: too many open files
```

### Additonal info

I did some debugging. This doesn't happen when I modify `src/net/http/transport.go` `func (pc *persistConn) readLoop()` to include `case <-rc.callerGone` in the last `select` clause: https://github.com/golang/go/blob/6c1c055d1ea417d050503efe92c1eead0da68cef/src/net/http/transport.go#L2207

 My hypothesis is that the connection hangs in this `select` and does not notice the `roundTrip` has finished due to this case not being present in the select.

**Comment by coodie** [comment]
I verified that and indeed your code causes "too many open files" error. However when I close response body:

```
package main

import (
  "fmt"
  "net/http"
  "strings"
)

func setGuestAttribute() error {
  url := "http://metadata.google.internal/computeMetadata/v1/instance/guest-attributes/foo/bar"
  client := &http.Client{}
  req, err := http.NewRequest("PUT", url, strings.NewReader("baz"))
  if err != nil {
    return err 
  }
  req.Header.Add("Metadata-Flavor", "Google")
  resp, err := client.Do(req)
  if err != nil {
    return err 
  }
  defer resp.Body.Close()
  return nil 
}

func main() {
  for i := 0; i < 258; i++ {
    err := setGuestAttribute()
    if err != nil {
      fmt.Printf("err:\n%v\n", err)
    }   
  }
}
```

Error seems to go away.

**Comment by dowgird** [comment]
Thank you - it seems that the error is in the calling code.
