### ISSUE TITLE
go/types, cmd/compile/internal/types2: uninstantiated method in assignment check

### ISSUE THREAD

**Issue by findleyr** [golang/go#46275]
Consider the following:

```
package main

type N[T any] struct {
        *N[T]
        t T
}

func (n *N[T]) Elem() T {
        return n.t
}

type I interface {
        Elem() string
}

func main() {
        var n1 *N[string]
        var _ I = n1
        type NS N[string]
        var n2 *NS
        var _ I = n2
}
```

This program should type-check cleanly, but does not.  The type parameter is unsubstituted in the assignability check: `cannot use n2 (variable of type *NS) as I value in variable declaration: wrong type for method Elem (have func() T, want func() string)`.

CC @griesemer

**Comment by griesemer** [comment]
This fails in `lookup.go`, `Checker.missingMethod`, in the unify phase around lines 420. There's a TODO, this code may not be correct.
