### ISSUE TITLE
crypto/x509: add new FreeBSD root store path [freeze exception]

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#46284]
FreeBSD added a system root store that doesn't require installing a package. We should use that when it's available.

https://svnweb.freebsd.org/base?view=revision&revision=357082

There is a CL available already: https://golang.org/cl/321190

@golang/release, can I get a freeze exception for this? It's a very small change, platform specific, and lets us be more in sync with the trust policy of the platform.

**Comment by dmitshur** [comment]
Thanks for requesting a freeze exception and letting us know. This certainly looks very reasonable for Go 1.17. Moving from NeedsDecision to NeedsFix.
