### ISSUE TITLE
x/website: update the #go-nuts IRC channel server

### ISSUE THREAD

**Issue by seebs** [golang/go#46281]
Not so much the language, as: There's IRC drama involving freenode, and the Go web page says that, for real-time help, people should use the "official" IRC channel, #go-nuts on freenode. I'm not sure that's still the right place; most of the historical freenode ops have left, and the person still running things has put up announcements about this, and I don't know whether or not this has implications from the Go team's perspective, but I think it's at least worth waving this at people and asking what "official" means.

some statements:

Andrew Lee: https://freenode.net/news/freenode-is-foss
edk: https://gist.github.com/edk0/478fb4351bc3ba458288d6878032669d
fuchs: https://fuchsnet.ch/freenode-resign-letter.txt

I don't even know how to begin on this. (For what it's worth, though, I wasn't sure until I read Lee's post, but given that, I stopped using freenode and have migrated the tabs I had on various channels to libera.chat or oftc depending on where their respective communities went.)

**Comment by theckman** [comment]
Many others are also moving away from Freenode: https://twitter.com/TwitchiH/status/1395139030313017345

**Comment by seankhliao** [comment]
cc @golang/osp-team

**Comment by SamWhited** [comment]
We are in the process of registering `#go-nuts` on Libera.chat as a community or project. It would be good to have it listed on the website either way, and if we could get a core team member to verify that they're okay with it we can register as a project instead which gives us some added benefits (https://libera.chat/chanreg). If anyone from the Go team is interested, please reach out to me (`Sam` on libera.chat).

**Comment by A-UNDERSCORE-D** [comment]
The channel was just forced out of the hands of the go community. I guess that freenode made this decision for us.

**Comment by 4ad** [comment]
Indeed, we need to move: https://mastodon.sdf.org/@kline/106299403921451814

**Comment by danderson** [comment]
Ohai, one of the owners/operators of #go-nuts on freenode here. So, freenode has started taking a moderation policy that's pretty hostile to the ideals of the Go project (in particular, removal of bans on hate speech and various other such things), and as a couple folks mentioned, a few hours ago they unilaterally nuked #go-nuts, along with 700+ other channels of OSS projects, on the basis that its topic contained the string "libera".

After a lot of confusion and wading through hundreds of other angry channel owners, I was able to regain ownership of #go-nuts, but at this point it's fairly clear that freenode is a hostile environment to operate in, even by IRC's standards.

There are currently 20 people on the freenode channel, and 286 people on the libera channel. It seems like the community's already voted with its feet. All that remains is to update golang.org (https://go-review.googlesource.com/c/website/+/321731) and turn out the lights on the freenode channel. I have the IRC permission bits to do the latter, but I want to keep the channel around on life support as long as it's being referenced from golang.org. I defer to @golang/osp-team from here on, think of me as your consensus-driven sudo on freenode.

**Comment by SamWhited** [comment]
apologies for the (sort of) off-topic and for emailing everyone, but I couldn't find any contact info:

@danderson hi, I'm the one who registered `#go-nuts` on libera chat. In case you still want to be a mod; please reach out (`sam` on IRC, or `sam@samwhited.com` via XMPP or email). And thanks for helping to moderate the old channel!

Similarly, any old #go-nuts mods on here please reach out to me or one of the other ops and we'll be happy to restore your +o (I didn't want to make this a hostile takeover, I just wanted to claim the name as quickly as possible so that if the community moved order would be maintained and there wouldn't be a takeover).

**Comment by 4ad** [comment]
Yeah, so yeah:

`20:37 < rasenqan> -server notice- All references to libera.chat are now subject to network-wide ban (k-line)!  `

**Comment by dmitshur** [comment]
Thanks for reporting this and providing relevant information. This is indeed rather unfortunate, and I appreciate everyone's support with helping find a good resolution to this for the Go project.

Thanks for sending [CL 321731](https://golang.org/cl/321731) for this issue. Based on the information and feedback I'm seeing, it seems we should proceed with the change proposed there. The review comments I left there have already been addressed, so we can submit it soon, which will close this issue.

**Comment by dmitshur** [comment]
The updated https://golang.org/help page is deployed, closing.

**Comment by danderson** [comment]
I will finalize the cutover of the freenode channel later today. Thanks for updating the site.
