### ISSUE TITLE
go/ast: revert the added FuncDecl.IsMethod

### ISSUE THREAD

**Issue by findleyr** [golang/go#46297]
`+pkg go/ast, method (*FuncDecl) IsMethod() bool`

The `IsMethod` field was added to `FuncDecl` to report whether or not it is a method.

CC @griesemer

**Comment by ianlancetaylor** [comment]
As far as I can tell this is new API that was added without going through the proposal process.

Are we OK with that?

**Comment by findleyr** [comment]
This was an artifact of the dev.typeparams merge. Since it wasn't directly related to generics, it wasn't guarded by the `typeparams` constraint.

@griesemer and I discussed this API earlier today and decided to revert it.
