### ISSUE TITLE
go/types: unexport the GoVersion configuration option for Go 1.17

### ISSUE THREAD

**Issue by findleyr** [golang/go#46296]
`+pkg go/types, type Config struct, GoVersion string`

The `GoVersion` field was added to `types.Config` to configure the language version being type checked.

CC @griesemer

**Comment by ianlancetaylor** [comment]
No proposal here either.

**Comment by findleyr** [comment]
This change was ported from types2, where it was needed IIRC to support `-lang`.  It being exported was incidental, and for that reason in particular perhaps we should unexport this field and discuss it for 1.18.  @griesemer, what do you think?

**Comment by griesemer** [comment]
Some features (and thus error messages) depend on the Go version. As long as we're ok with `go/types` running against the latest language version we don't need to expose this.

**Comment by findleyr** [comment]
> Some features (and thus error messages) depend on the Go version. As long as we're ok with go/types running against the latest language version we don't need to expose this.

To clarify, I think this is a useful feature, and we _should_ expose it eventually. But the fact that it was exposed in go/types _for 1.17_ was incidental. The real reason it was added was for consistency with types2 (and because it has value of course). At the time we weren't thinking about 1.17.

If we think it's minor enough not to require a proposal, we can leave it in, but I certainly don't want it to be perceived as bypassing the proposal process. Since no one is clamoring for this change, unexporting the field and making a brief proposal at the start of the 1.18 cycle seems like a fine option. I feel roughly the same about #46298, though I think that change is even more minor.

I defer to both of you, as members of the proposal committee, for what is OK.

**Comment by griesemer** [comment]
Sorry for not being clear: What I meant is that we don't need to expose this for *Go1.17*. We can discuss what needs to be done for Go1.18.

**Comment by findleyr** [comment]
Filed a proposal at #46648 to discuss this feature for 1.18.
