### ISSUE TITLE
UTF8-BOM compile error with go mod

### ISSUE THREAD

**Issue by LiuYinCarl** [golang/go#46290]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.15 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
not sure

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/data/gopath/bin"
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/.golang/path"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/root/.golang/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/.golang/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/test/testbom/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build844510091=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

when I use Go module with utf-bom source code,  I cannot find the import package
```bash
$tree
.
├── go.mod
├── main.go   // UTF8-BOM
└── mypkg
    └── mypkg.go
```

```go
// main.go
package main

import (
	"fmt"
	"testbom/mypkg"
)

func SayHi() {
	fmt.Println("hi")
}

func main() {
	SayHi()
	mypkg.SayHello()
}
```

```go
//  mypkg.go
package mypkg

import "fmt"

func SayHello() {
	fmt.Println("Hello")
}
```

```go
// go.mod
module testbom

go 1.14
```

when I use `go build main.go` to compile it, it failed.  I found it's because the go source code cannot read the UTF8-BOM.
so I edit the souece code of  `go/src/cmd/go/internal/imports/scan.go`

```go
func scanFiles(files []string, tags map[string]bool, explicitFiles bool) ([]string, []string, error) {
	imports := make(map[string]bool)
	testImports := make(map[string]bool)
	numFiles := 0
Files:
	for _, name := range files {
		r, err := os.Open(name)
		if err != nil {
			return nil, nil, err
		}
               
               // I add these code to check if the source code is with BOM
		var fheader = make([]byte, 3)
		_, err = r.Read(fheader)
		if err != nil {
			fmt.Println("error: ", err)
		}
		if fheader[0] == 0xef && fheader[1] == 0xbb && fheader[2] == 0xbf {
			r.Seek(3, 0)
		} else {
			r.Seek(0, 0)
		}
                ///////////////////////////////////////////

		var list []string
                // if a file is with BOM, the return list is empty
		data, err := ReadImports(r, false, &list)
		r.Close()
		if err != nil {
			return nil, nil, fmt.Errorf("reading %s: %v", name, err)
		}
// ... ...
}
```

and then, I recompile the golang. when I compile the code above, it success. <br>
I hope you can confirm soon whether there is this problem, because many people use files with BOM. <br>
thanks for reading.

### What did you expect to see?

compile success

### What did you see instead?

main.go:5:2: cannot find package

**Comment by mvdan** [comment]
Dup of https://github.com/golang/go/issues/35726.
