### ISSUE TITLE
proposal: cmd/go: message about deprecated modules should not be a warning by default

### ISSUE THREAD

**Issue by theckman** [golang/go#46294]
### Context

The `go` command currently reports deprecation notices as a warning[0], even if that module version is still fully supported but the author and the `Deprecation` is informing consumers of a new major version (as we have no other mechanisms to communicate information to consumers).

0: https://github.com/golang/go/blob/814c5ff13810e800aeb67fd0371e21984d4d2c64/src/cmd/go/internal/modget/get.go#L1601

### Proposal

This proposal is to remove the word `warning` from the message that's printed when showing the deprecation, and leave it up to the Module author to provide the context around the severity in the deprecation message itself.

**Comment by seankhliao** [comment]
cc @bcmills @jayconrod @matloob

**Comment by peterbourgon** [comment]
Strong +1. I was surprised to see the word "warning" in the mesasging, because it was deliberately not part in the proposal.

**Comment by jayconrod** [comment]
This seems okay? If everyone's fine with this, I think we should go ahead and merge that CL rather than go through the proposal process.

**Comment by bcmills** [comment]
Agreed — I think we should just do this rather than send it through the proposal process. (It's just a rewording in the `go` command's output, so the proposal process seems too heavy, and since we don't guarantee output stability for the `go` command there are no backward- or forward-compatibility issues to worry about.)

**Comment by theckman** [comment]
Works for me. I only filed it as a proposal as I wasn't sure when that decision had been made to call it a warning, relative to the original proposal, or if it was something that had mistakenly been added during the implementation.

**Comment by jayconrod** [comment]
Ok sounds good. Submitted the CL, thanks for sending that.

I think I used "warning" just because retraction uses similar language, and the code that handles deprecation is close to that.
