### ISSUE TITLE
x/crypto/acme: allow setting client KID directly

### ISSUE THREAD

**Issue by Stanwise** [golang/go#46303]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

I have a service that uses `acme.Client` for communication with an RFC8555 CA. For technical reasons I need to reconstruct the `acme.Client` multiple times during the full flow.

Current implementation works overall, but I'd like to be able to specify `account KID` (equal to `Account.URI`) explicitly, instead of having the library always call the CA's account registration endpoint to obtain kid to cache: https://github.com/golang/crypto/blob/c07d793c2f9aacf728fe68cbd7acd73adbd04159/acme/acme.go#L152

### What did you expect to see?

I'd like to be able to create the client like this:
```
&acme.Client{
    Key:          signer,
    KID:          accountURI,
    DirectoryURL: directoryUrl,
    HTTPClient:   &http.Client{...}
},
```

And have the `kid` [field](https://github.com/golang/crypto/blob/c07d793c2f9aacf728fe68cbd7acd73adbd04159/acme/acme.go#L128) populated from it , e.g.: 
* `KID` field could be a string, only used in the first request to pre-populate the private mutex-protected `kid` value.
*  The following snippet could be added to `accountKID` function [between lines 151 and 152](https://github.com/golang/crypto/blob/c07d793c2f9aacf728fe68cbd7acd73adbd04159/acme/acme.go#L151-L152)

```
if c.KID != "" {	
  c.kid = c.KID
  return c.kid
}
```

### What did you see instead?

I have to specify the client like this:

```
&acme.Client{
    Key:          signer,
    DirectoryURL: directoryUrl,
    HTTPClient: &http.Client{...}
},
```

And then the library calls the CA's account registration endpoint to obtain `kid` to cache. This  results in a lot of unnecessary calls to the CA.

**Comment by rolandshoemaker** [comment]
(sent a CL for this, but just to articulate my thoughts here) This seems reasonable to me. I don't think adding a duplicate public field is worth the extra complexity, seems fine to just expose the existing `kid` field.
