### ISSUE TITLE
x/build/builder: make them self-updating

### ISSUE THREAD

**Issue by adg** [golang/go#4631]
<pre>Perhaps we could put a text file in the repo, like:

$ cat $GOROOT/misc/dashboard/builder/wanted-version.txt
84a2c61092a9

And then after a build, if that file doesn't match the current builder process's
runtime.Version(), rebuild the builder and re-exec the current process with the new one.

The extra file would mean we only update it when it's intentional, and not on every
build, which would add a risk of nuking all our builders at once.</pre>

**Comment by bradfitz** [comment]
No longer relevant.
