### ISSUE TITLE
Depricated function curve25519.ScalarMult.

### ISSUE THREAD

**Issue by joshaprior** [golang/go#46318]
Before ScalarMult got depricated you used to use
ScalarMult(dst, scalar, point *[32]byte) to get the shared key from your private key and someone elses public key

but now that you have to use X25519(scalar, point []byte) ([]byte, error) it doesn't accept [32]byte but []byte even though ScalarBaseMult needs [32]byte array, am i dumb or do i have to use this to get around this.

```
privkey := new(bytes.Buffer)

for i := range privateKey[:] {
	privkey.WriteByte(privateKey[i])
}
```

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
