### ISSUE TITLE
x/pkgsite: Remove packages

### ISSUE THREAD

**Issue by lwj5** [golang/go#46327]
### What is the URL of the page with the issue?
Hi could you help to remove these packages from the site?
 
https://pkg.go.dev/github.com/inquisico/artoo/pkg/artoo
https://pkg.go.dev/github.com/inquisico/artoo/pkg
 
We are restructuring and have taken them down from these repo from github

**Comment by jba** [comment]
If we remove github.com/inquisico/artoo/pkg, we will remove everything under it (everything with that path as a prefix). Is that OK?

**Comment by lwj5** [comment]
Yes! thanks a lot

**Comment by jba** [comment]
Done.
