### ISSUE TITLE
mime: ParseMediaType drops value with trailing semicolon

### ISSUE THREAD

**Issue by Illirgway** [golang/go#46323]
### What version of Go are you using (`go version`)?

<pre>
// up to go current playground version
package main

import (
	"fmt"
	"runtime"
)

func main() {
	fmt.Println(runtime.Version())
}
</pre>
go1.16.4

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
go playground env
 
### What did you do?

https://play.golang.org/p/kIcw1CfXcUq

```
package main

import (
	"fmt"
	"mime"
)

func main() {
	// example from rfc2231 (p.3)

	const (
		contentTypeSucc = `message/external-body; access-type=URL;
         URL*0="ftp://";
         URL*1="cs.utk.edu/pub/moore/bulk-mailer/bulk-mailer.tar"`
		contentTypeFail = `message/external-body; access-type=URL;
         URL*0="ftp://";
         URL*1="cs.utk.edu/pub/moore/bulk-mailer/bulk-mailer.tar";`	// <-- !!!
	)
	
	r1, p1, err1 := mime.ParseMediaType(contentTypeSucc)
	r2, p2, err2 := mime.ParseMediaType(contentTypeFail)
	
	fmt.Println(r1, p1, err1)
	fmt.Println(r2, p2, err2)
}
```

### What did you expect to see?
```
message/external-body map[access-type:URL url:ftp://cs.utk.edu/pub/moore/bulk-mailer/bulk-mailer.tar] <nil>
message/external-body map[access-type:URL url:ftp://cs.utk.edu/pub/moore/bulk-mailer/bulk-mailer.tar] <nil>
```

### What did you see instead?
```
message/external-body map[access-type:URL url:ftp://cs.utk.edu/pub/moore/bulk-mailer/bulk-mailer.tar] <nil>
message/external-body map[access-type:URL] <nil>
```

### Analysis
this https://github.com/golang/go/blob/go1.16.4/src/mime/mediatype.go#L170 (https://golang.org/src/mime/mediatype.go?#L170) should be `break` instead of `return`

### Question
Should I next time push fix commit instead of writing issue if I  found both a bug and a fix to it at once?

**Comment by ianlancetaylor** [comment]
If you are sure that it is a bug, it's OK to send a patch instead of filing an issue.  See https://golang.org/doc/contribute.html.  Thanks.
