### ISSUE TITLE
cmd/compile: remove assert in internal/noder

### ISSUE THREAD

**Issue by rsc** [golang/go#46329]
There's a func assert in cmd/compile/internal/noder with a TODO to remove.
(It would be a bad experience for users to hit the panic instead of a good error message.)
It's only reachable in the generics implementation, so it doesn't need to be
removed until Go 1.18. Filing this issue to make sure we remember.

**Comment by toothrot** [comment]
The Go 1.18 tree is now open, so it may make sense to address this issue now.

**Comment by toothrot** [comment]
@griesemer @findleyr

**Comment by toothrot** [comment]
Checking in again, as this issue is labeled a release blocker.

**Comment by heschi** [comment]
Ping again from the release team: what information is this issue waiting on?

**Comment by griesemer** [comment]
I believe this can be closed, but I'll leave to @mdempsky do decide.

**Comment by mdempsky** [comment]
I don't think there's any action to take here. The asserts are just internal consistency checks. They're not expected to fire on user code.
