### ISSUE TITLE
Why is Rune of fixed length(32bit)? What code philosophy is there？

### ISSUE THREAD

**Issue by linhongzhao321** [golang/go#46335]
### What version of Go are you using (`go version`)?

<details><summary><code>go version</code> Output</summary><br><pre>
$ go version
go version go1.14.12 darwin/amd64
</pre></details>

### Does this issue reproduce with the latest release?

NO

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOARCH="amd64"

</pre></details>

### Question

Why is Rune of fixed length(32bit)? 
What code philosophy is there？

A fixed 32 bit length seems to reduced space utilization?

**Comment by davecheney** [comment]
There are far more than 2^16 unicode code points defined today, more than would fit in a uint16.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
