### ISSUE TITLE
cmd/go: go get 403 Forbidden  Access denied  private bitbucket repositories

### ISSUE THREAD

**Issue by SHUFIL** [golang/go#46344]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.9 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOENV="/home/ubuntu/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="bitbucket.org/project-name/second-repo"
GONOSUMDB="bitbucket.org/project-name/second-repo"
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPRIVATE="bitbucket.org/project-name/second-repo"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ubuntu/repo-name/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build436192813=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
I have added private key in bitbucket , and can clone using `git@bitbucket.org:project-name/repo-name.git`
added `git config --global url."git@bitbucket.org:project-name".insteadOf "https://bitbucket.org/project-name"`

also Added GOPRIVATE=bitbucket.org/project-name/second-repo
<!--

```

A complete runnable program is good.
A link on play.golang.org is best.
-->



### What did you expect to see?

I need to pull library from second repositary 


### What did you see instead?
go get bitbucket.org/project-name/second-repo: reading https://api.bitbucket.org/2.0/repositories/project-name/second-repo?fields=scm: 403 Forbidden
        server response: Access denied. You must have write or admin access.

**Comment by mknyszek** [comment]
I'm not positive, but I think `GOPRIVATE` only works with Go modules. Is your repository a module?

CC @bcmills @jayconrod @matloob via https://dev.golang.org/owners

**Comment by bcmills** [comment]
The `go` command uses HTTPS to identify the repository corresponding to an import path, unless some prefix of the path has an explicit `.git` or similar suffix (see https://golang.org/ref/mod#vcs-find).

As a consequence, merely adding a private SSH key does not suffice — either you need to add HTTPS credentials (such as in a `.netrc` file; see https://golang.org/ref/mod#private-module-repo-auth), or you need to add an explicit `.git` suffix to the appropriate element of the import path.

**Comment by muhaarif** [comment]
Export the GOPRIVARE equal to bitbucket path.

Check with this solution,
https://community.atlassian.com/t5/Bitbucket-questions/How-do-I-run-go-get-on-a-private-repo/qaq-p/1385040

**Comment by SHUFIL** [comment]
Resolved the issue using blow steps , this is i used git clone using https.
1, ```
cat ~/.gitconfig
[user]
        email = username@domain.com
        name = username
```
2, `export GOPRIVATE=bitbucket.org/project-name/second-repo`
3,` GIT_TERMINAL_PROMPT=1 go get -v bitbucket.org/project-name/second-repo   `
It will ask user name and password for 3 times , thats it.

If you using ssh key , it will not ask user name and password , at last stage , and  we need to add below command 
`git config --global url."git@bitbucket.org:project-name".insteadof "https://bitbucket.org/project-name"`

**Comment by bcmills** [comment]
Sounds like there isn't anything more to do here, beyond the documentation already requested in #29953.
