### ISSUE TITLE
GOOSE=linux go run with CGO undefind package

### ISSUE THREAD

**Issue by Wintic** [golang/go#46340]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/******/Library/Caches/go-build"
GOENV="/Users/*******/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="********"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/*****/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5r/wcz_tgz17nv6hdn1wztjxv000000gp/T/go-build1308834621=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I had use package "github.com/yanyiwu/gojieba" 
when I run go build ***
![image](https://user-images.githubusercontent.com/29673009/119330302-a6994900-bcb8-11eb-8d73-bdd4b1f1ebe8.png)

It work

but run GOOSE=linux go build ***
![image](https://user-images.githubusercontent.com/29673009/119330429-c597db00-bcb8-11eb-945c-1e2770a856a0.png)

### What did you expect to see?
I don't know why
I want to know why

**Comment by seankhliao** [comment]
`GOOS` not `GOOSE`

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
