### ISSUE TITLE
os/exec: support os.Process.Signal(Interrupt) on Windows

### ISSUE THREAD

**Issue by insomnimus** [golang/go#46345]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.17-cca23a7373 Sat May 22 00:51:17 2021 +0000 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=D:\home\.go\bin
set GOCACHE=C:\Users\insomnia\AppData\Local\go-build
set GOENV=C:\Users\insomnia\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\home\.go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\home\.go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=devel go1.17-cca23a7373 Sat May 22 00:51:17 2021 +0000
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\insomnia\AppData\Local\Temp\go-build4037608551=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you expect to see?

`os.Process.Signal(os.Interrupt)` should work on windows.

### What did you see instead?

In the documentation for `os.Process.Signal()`, it says that sending os.Interrupt is not implemented on Windows.

It's not an insignificant bit of functionality, i think it should be implemented unless there's an obvious reason to not do so.
Currently this makes it difficult to manage exec.Cmd's properly on Windows.

**Comment by mattn** [comment]
Windows does not have signal feature as same as UNIX one. CTRL-C as you typed on command prompt does not send signal to the process. It is treated as key events. To simulate UNIX's CTLR-C on Windows, we have to use [GenerateConsoleCtrlEvent](https://docs.microsoft.com/en-us/windows/console/generateconsolectrlevent). However, the API does not work with detatched process. i.e. we can regard the CtrlEvent as os.Interrupt but it won't be same behavior.

**Comment by mknyszek** [comment]
As @mattn, I think this might be impossible. See #6720 for a more complete discussion. It was closed once that documentation was written.

**Comment by mknyszek** [comment]
Closing on the assumption that this isn't possible, but CCing @ianlancetaylor (via https://dev.golang.org/owners) and @alexbrainman (who was involved in #6720) just in case.

**Comment by alexbrainman** [comment]
I just re-read #6720 again. And, indeed, we can implement os.Interrupt (by using Windows Ctrl-Break) but we can only send it to a "console process group" which sometimes is OK, but generally is not possible. See https://github.com/golang/go/issues/6720#issuecomment-66087747

Alex
