### ISSUE TITLE
generics: Confusion between interfaces and constraints

### ISSUE THREAD

**Issue by millergarym** [golang/go#46359]
Is there any way of using constraints as return types where the value being returned is instantiated in the body of the function?

Or does this fall into [Possible future step: permitting constraints as ordinary interface types](https://github.com/golang/go/issues/45346)?

``` golang
type iors interface {
	type int, string
}

func Bar() iors {
  return int(1)
}

func Foo[T iors]() T {
  return int(1)
}
```

From https://go2goplay.golang.org/p/S5ppLsCtMPv

```
type checking failed for main
prog.go2:12:10: cannot use int(1) (constant 1 of type int) as T value in return statement
prog.go2:7:12: interface contains type constraints (int, string)
```

**Comment by millergarym** [comment]
It's becoming clearer.
The following works.

https://go2goplay.golang.org/p/eGjeoSCo7Ua

``` golang
type iors interface {
	type int, string
}

func Foo[T iors]() (t T) {
  fmt.Printf("%T\n", t)
  x := 1
  return *(*T)(unsafe.Pointer(&x))
}

func main() {
	a := Foo[int]()
	fmt.Printf("%T(%v)\n", a, a)
}
```

**Comment by millergarym** [comment]
Related to https://github.com/golang/go/issues/45380
Type switches on return types might be nice.

``` golang
func Foo[T iors]() (t T) {
	switch t.(type) {
	  ...
	}
}
```

**Comment by ianlancetaylor** [comment]
I don't see any action to take here.

Discussion about the generics proposal should take place on golang-nuts.  Thanks.

**Comment by millergarym** [comment]
@ianlancetaylor thanks for the response / triage.
I'm pushing on using generics as sumtypes, it's clear they're not there yet.

**Comment by ianlancetaylor** [comment]
There is some discussion at #45346.  But, yes, support for sum types is intentionally omitted.
