### ISSUE TITLE
pkgsite: showing incorrect LATEST version

### ISSUE THREAD

**Issue by icholy** [golang/go#46364]
### What did you do?

1. Tagged and pushed v0.0.2 and v0.0.3
2. Navigated to https://pkg.go.dev/github.com/icholy/structfields@v0.0.3

### What did you expect to see?

I expected to see version v0.0.3 as the LATEST

### What did you see instead?

"GO TO LATEST" link takes me to v0.0.2

![latest](https://user-images.githubusercontent.com/943597/119518180-4c46c980-bd46-11eb-9239-c6c71c35a699.png)
![latest2](https://user-images.githubusercontent.com/943597/119518917-f6beec80-bd46-11eb-8ccd-f69a1677a1ff.png)

**Comment by mknyszek** [comment]
CC @julieqiu @jba @jamalc via https://dev.golang.org/owners

**Comment by icholy** [comment]
I'll hold off pushing any new tags to this repo until this issue can be investigated.

**Comment by jba** [comment]
Seems to be fixed now. Probably just a transient state due to processing order.

**Comment by icholy** [comment]
>  Probably just a transient state due to processing order.

Commonly known as a design flaw.
