### ISSUE TITLE
x/tools/gopls/internal/regtest: TestDeleteModule_Interdependent flakes due to orphaned file reloading

### ISSUE THREAD

**Issue by findleyr** [golang/go#46375]
Looking at regtest failures for issue #46183, one common source of flakes in slower builders is TestDeleteModule_Interdependent in `golang.org/x/tools/gopls/internal/regtest/workspace`.

For example:
https://build.golang.org/log/c962f4fbb5df4c74ebe76f8aeb610eed3065f267
https://storage.googleapis.com/go-build-log/8b462d75/freebsd-amd64-12_2_e126050b.log

This test failure appears to be a race related to orphaned file reloading. All failures have a log message about `reloadOrphanedFiles`, but when it succeeds locally I never see this log message.

Since it is an experimental feature, we should disable this test until we understand it.

CC @stamblerre @heschi

**Comment by bcmills** [comment]
`greplogs -l -e 'FAIL: TestDeleteModule_Interdependent' --since=2022-07-14`
[2022-08-18T19:12:13-e55fb40-0eb56ca/openbsd-386-70](https://build.golang.org/log/5350f955d4b05114a20efa69e816d05619c82e77)

**Comment by findleyr** [comment]
Unfortunately I no longer reproduce that greplogs result (we think because of a dashboard bug where there is a maximum number of go revisions per repo revision).

The new failure is different, and interesting. Somehow we're not getting a definition result after the deletion, suggesting some sort of race.

**Comment by findleyr** [comment]
Seems to no longer be reproducing, and we've rewritten a lot of this logic.

Closing.
