### ISSUE TITLE
x/build/internal/sourcecache: increase download size limit to accommodate larger repositories in 2021

### ISSUE THREAD

**Issue by dmitshur** [golang/go#46379]
TryBots are failing on CL 322750 with:

```
reading website/212bb63fb0e7677bf1f7b9c00752b5ae51417f5b from gerrit: body over 52428800 bytes
```

~~It seems like the underlying error might be coming indirectly from Gerrit at this point.~~ Update: It's our own limit in x/build, see comment below.

We should determine if TryBots should be able to handle a large CL (it's adding approximately 70 MB of content from x/blog repo), or otherwise improve the error message to say that a known limit is being exceeded.

CC @golang/release, @rsc.

**Comment by dmitshur** [comment]
It seems that the compressed content of that CL is a 55 MB tarball, which exceeds our limit, currently 50 MB:

```Go
const maxSize = 50 << 20 // talks repo is over 25MB; go source is 7.8MB on 2015-06-15
```

([Source](https://github.com/golang/build/blob/b5eec309597d2d7c8dc2270644e869c1f8610c4b/internal/sourcecache/source.go#L125).)

It's probably time we increase that limit.

**Comment by rsc** [comment]
Indeed. x/website is only going to get bigger over time.

**Comment by dmitshur** [comment]
I'll send a CL to double the current limit. That should last some years.

**Comment by dmitshur** [comment]
Update on 2021-11-22:

x/talks content (74 MB compressed) is being moved into x/website in CL 365135, pushing it over 100 MB. [CL 366135](https://golang.org/cl/366135) updates the limit for x/website (only) to be 200 MB.
