### ISSUE TITLE
Can map[key] return dynamic response by func return declaration?

### ISSUE THREAD

**Issue by horizonzy** [golang/go#46387]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN="/Users/apple/go/bin"
GOCACHE="/Users/apple/Library/Caches/go-build"
GOENV="/Users/apple/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/apple/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/apple/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/Cellar/go/1.16.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4h/s_f39xcs6x9c8d1d9m5pyjkm0000gn/T/go-build2514324384=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```
func test(m map[string]string) string {
	return m["foo"]
}
```
compile normally.

```
func test1(m map[string]string) (string, bool) {
	return m["foo"]
}
```
compile error.

### What did you expect to see?

Can it infer the map[key]'s response by return declaration at this situation.

**Comment by ALTree** [comment]
This is #10947, also see this [golang-nuts thread](https://groups.google.com/g/golang-nuts/c/wNdPgX8Pumg/m/-xESRBEz6dwJ). In short, automatic expansion would be ambiguous in some cases:

```
func F(m1, m2 map[string]bool) (bool, bool, bool) {
return m1["a"], m2["b"]
} 
```

So this was a deliberate design decision. Closing here as a dup of #10947.
