### ISSUE TITLE
website: file search breaks

### ISSUE THREAD

**Issue by ms-choudhary** [golang/go#46382]
[File search](https://golang.org/search?q=Reader) on golang website breaks with following error:

```
 open REDACTED: file does not exist 
```

**Comment by AlexRouSg** [comment]
Search was removed, please explain where did you find a button that links to search.
See #44357

**Comment by ms-choudhary** [comment]
@AlexRouSg It's referenced here: [Readers](https://tour.golang.org/methods/21)

**Comment by fzipp** [comment]
@ms-choudhary Then it's a duplicate of golang/tour#1140

**Comment by ms-choudhary** [comment]
got it. Closing this then.
