### ISSUE TITLE
Failed to make array with length math.MaxInt32 in Linux MIPS 32bit

### ISSUE THREAD

**Issue by Loyalsoldier** [golang/go#46383]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/loyalsoldier/Library/Caches/go-build"
GOENV="/Users/loyalsoldier/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/loyalsoldier/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/loyalsoldier/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.4/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ly/gfpq76t50zv4995hp4tds9pw0000gn/T/go-build942322438=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
package main

import "math"

func main() {
	var arr [math.MaxInt32]int
	arr[0] = 0
}
```

Build the code above on Linux MIPS 32bit(softfloat and hardfloat), and it fails with error:

```
./test.go:6:10: type [2147483647]int larger than address space
./test.go:6:10: type [2147483647]int too large
```

### What did you expect to see?

Build successfully.

### What did you see instead?

Build failed.

**Comment by robpike** [comment]
The error messages make things pretty clear. You're asking for more memory than the machine can address. Working as intended.

**Comment by Loyalsoldier** [comment]
Thanks
