### ISSUE TITLE
go/types: audit error messages for go1.17

### ISSUE THREAD

**Issue by findleyr** [golang/go#46404]
With all the changes to go/types merged from the dev.typeparams branch, many error messages have changed.  In general these were all intentional improvements, but we should try to ensure that no error messages related to generics leak in 1.17. Such errors are marked, so fuzz testing might be helpful here, in addition to manual auditing.

CC @griesemer

**Comment by toothrot** [comment]
@findleyr  We're close to RC1, and this issue is a release blocker. Any updates?

**Comment by findleyr** [comment]
Same as #46403. For this, I just need to do a bit of due diligence. Barring surprises, I can close this out by Monday.

**Comment by findleyr** [comment]
Update: this can be closed once CL 329793 is merged.  Fuzzing found this test case relatively quickly, and did not find any others after a long time.

I also checked for leaks in our existing test data corpus. I feel satisfied that we've done our due diligence.
