### ISSUE TITLE
database/sql: query("now() + ?", time.Hour) is surprising

### ISSUE THREAD

**Issue by adonovan** [golang/go#46427]
Today I learned two fun facts:
1. in MySQL, although `now()` is a datetime, `now() + 0` is an integer formed from all of the decimal digits in the date. e.g. 2021-05-27 17:00:26 vs 20210527170026. (I'm not sure why one would ever want that.)
2. in Go's `database/sql` API for prepared statements, "?" applied to a duration value treats the duration (thanks to reflection on the underlying type) as an integer number of nanoseconds, not an interval. I don't know why one would ever want that either, since nanoseconds are not really useful in SQL.
  
The combination of these two facts means that the behavior of `query("now() + ?", 1*time.Hour)` isn't remotely close to what one might expect:
```
mysql> select now(), now() + interval 1 hour, now() + 60*60*1e9;
+---------------------+-------------------------+-------------------+
| now()               | now() + interval 1 hour | now() + 60*60*1e9 |
+---------------------+-------------------------+-------------------+
| 2021-05-27 17:13:53 | 2021-05-27 18:13:53     |    23810527171353 |
+---------------------+-------------------------+-------------------+
1 row in set (0.00 sec)
```
If database/sql were to treat durations specially, they could be mapped to `interval 1 hour`, avoiding this pitfall.

**Comment by mknyszek** [comment]
😱 

CC @kardianos via https://dev.golang.org/owners

Based on the OP this looks like a problem in older versions of Go as well, but could you please confirm that?

**Comment by seankhliao** [comment]
`database/sql` passes the arguments for drivers to process, specifically, drivers may implement [`database/sql/driver.NamedValueChecker`](https://pkg.go.dev/database/sql/driver#NamedValueChecker) to handle types outside the default list. Given the varying representations of durations in different databases (as noted in #4954), it doesn't make sense to do this in `database/sql` or `database/sql/dirver` and should instead be handled by individual drivers instead.

**Comment by adonovan** [comment]
I see. If it's impossible to support meaningfully on a range of databases, and if none support it today, then we should consider specifically disallowing it with a good error.

**Comment by seankhliao** [comment]
returning an error would prevent drivers from ever supporting this, and validation was specifically removed as part of the introduction of `NamedValueChecker`. [CL 38533](golang.org/cl/38533) / #18417

Closing there's nothing to do for the stdlib and requests should instead be filed with the drivers.
