### ISSUE TITLE
x/website: doc/install/gccgo is not up to date

### ISSUE THREAD

**Issue by perillo** [golang/go#46420]
https://golang.org/doc/install/gccgo does not list GCC 10 and GCC 11.

**Comment by mknyszek** [comment]
CC @ianlancetaylor via https://dev.golang.org/owners Is that correct? Does anything need to be updated on that page?

**Comment by perillo** [comment]
I have also noted that, starting from GCC 10, *Go* is no longer listed in the `New Languages and Language specific improvements` section.

Finally, for convenience, I would like to report a typo in the `gccgo` documentation.  In https://gcc.gnu.org/onlinedocs/gcc-11.1.0/gccgo/Function-Names.html#Function-Names, an AMPERSAND character was escaped:
`i := c_open(&amp;name[0], os.O_RDONLY, 0);`

**Comment by ianlancetaylor** [comment]
@perillo Thanks.  I fixed those problems in the GCC repos.
