### ISSUE TITLE
x/pkgsite: rendering < sign incorrectly in examples

### ISSUE THREAD

**Issue by codyoss** [golang/go#46424]
### What did you do?

Went to https://pkg.go.dev/sort#example-Slice

### What did you expect to see?

A working example I could copy and paste.

### What did you see instead?

See link, but:

```go
package main

import (
	"fmt"
	"sort"
)

func main() {
	people := []struct {
		Name string
		Age  int
	}{
		{"Gopher", 7},
		{"Alice", 55},
		{"Vera", 24},
		{"Bob", 75},
	}
	sort.Slice(people, func(i, j int) bool { return people[i].Name &lt; people[j].Name })
	fmt.Println("By name:", people)

	sort.Slice(people, func(i, j int) bool { return people[i].Age &lt; people[j].Age })
	fmt.Println("By age:", people)
```

Notice the `&lt;`

### Extra details:

- User agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36`

**Comment by AlekSi** [comment]
The same problem with `&`
