### ISSUE TITLE
go/types: dev.typeparams branch: cannot use T₈ value as type IBase in assignment: T₈ does not implement IBase (missing GetName method)

### ISSUE THREAD

**Issue by zllangct** [golang/go#46442]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.17-22f5ece3b13 Thu May 27 23:54:29 2021 +0000 windows/amd64
</pre>

### What did you do?
<pre>

type IBase interface {
	GetName() string
}

type Item struct {
	Name  string
}

func (p Item) GetName() string {
	return p.Name
}

var funcMap = map[reflect.Type]func(interface{})IBase{}

func AddCallback[T IBase](in T) {
	funcMap[reflect.TypeOf(in)] = func(src interface{}) IBase {
		return src.(T)
	}
}

func main() {
	item := Item{
		Name : "hello",
	}

	AddCallback[Item](item)
}
</pre>

### What did you see instead?
<pre>
# go_generic_test
.\main.go:119:3: cannot use T₈ value as type IBase in assignment:
	T₈ does not implement IBase (missing GetName method)
</pre>

**Comment by ianlancetaylor** [comment]
CC @griesemer @findleyr 

Note that the dev.typeparams branch is under very active development.  It is not expected to be stable or to work at all.  It's not particularly helpful to file bugs against it.  Thanks.

That said I'll keep this one open since you've already filed it.

**Comment by griesemer** [comment]
This is a good bug report, thanks.

Here's a simplified version:
```Go
package p

type C interface {
	m()
}

func _[T C]() {
	_ = func(x interface{}) C {
		return x.(T)
	}
}
```
reporting:
```
$ go tool compile -G=3 bug.go2
bug.go2:9:3: cannot use T₁ value as type C in assignment:
	T₁ does not implement C (missing m method)
```
But the same code does work on the [go2go playground](https://go2goplay.golang.org/p/mfKjsuC5MY3
), as expected. So this is a a regression of sorts.

**Comment by griesemer** [comment]
As an aside, the error message also shouldn't print the (internally used) subscripts.

**Comment by griesemer** [comment]
The compiler now accepts both the original and simplified code sample; so this seems to be working now.
