### ISSUE TITLE
runtime: timer.seq field seems unnecessary

### ISSUE THREAD

**Issue by someblue** [golang/go#46457]
What's the purpose of [`seq` field](https://github.com/golang/go/blob/go1.16.4/src/time/sleep.go#L19) in runtimeTimer?

According to runtime/time.go implementation, runtime/time.go define [`timer` struct](https://github.com/golang/go/blob/go1.16.4/src/runtime/time.go#L32), including seq field. This seq field will not be modified by runtime and always keep the value when timer struct was created. The only place to use seq field is [the callback of timer.f in runOneTimer](https://github.com/golang/go/blob/go1.16.4/src/runtime/time.go#L899).

However, in time/sleep.go, this seq field isn't set when initializing
- NewTimer: https://github.com/golang/go/blob/go1.16.4/src/time/sleep.go#L90-L94
- AfterFunc: https://github.com/golang/go/blob/go1.16.4/src/time/sleep.go#L169-L173
- NewTicker: https://github.com/golang/go/blob/go1.16.4/src/time/tick.go#L32-L37

And the callback runtimeTImer.f doesn't use this field too:
- sendTime used by NewTimer & NewTicker: https://github.com/golang/go/blob/go1.16.4/src/time/sleep.go#L142-L152
- goFunc used by AfterFunc: https://github.com/golang/go/blob/go1.16.4/src/time/sleep.go#L179-L181

At first I guess this is for some compatible reason. But even when go1.0.1 this seq field is not used: https://github.com/golang/go/blob/go1.0.1/src/pkg/time/sleep.go

The comment `each time calling f(arg, now) in the timer goroutine` in https://github.com/golang/go/blob/go1.16.4/src/runtime/time.go#L24 is inconsistent with the behavior.

It seems to me the seq field should be removed to help understand source code of timer more easily without confusion, and maybe improve the performance (very very slightly).

Should this seq field be remove? Please let me known if I miss something other!

**Comment by ZekeLu** [comment]
> dvyukov 2014/08/30 12:27:38
> > On 2014/08/29 18:53:11, rsc wrote: > This seems unrelated. Remove. 
> 
> This is required for Go netpoll. Previously I stored PollDesc* into arg.data, and seq into arg.type. Now *pollDesc occupies whole arg.

see https://codereview.appspot.com/132910043/diff/260001/src/pkg/runtime/time.go#newcode25

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker for discussions, only for actionable bug reports.  For questions and discussions, see https://golang.org/wiki/Questions.

As the above referenced comment points out, the `seq` field is used in runtime/netpoll.go, when `runOneTimer` passes it back.
