### ISSUE TITLE
x/mobile: panic: unsupported GOARCH: arm64

### ISSUE THREAD

**Issue by yyzl0418** [golang/go#46464]
goroutine 1 [running]:
main.archNDK(...)
	/Users/xxx/go/src/golang.org/x/mobile/cmd/gomobile/env.go:298
main.(*ndkToolchain).Path(0x14000197b00, 0x140000b8000, 0x29, 0x1011be402, 0x5, 0x0, 0x14000197938)
	/Users/xxx/go/src/golang.org/x/mobile/cmd/gomobile/env.go:327 +0xc0
main.envInit(0x14000016047, 0x31)
	/Users/xxx/go/src/golang.org/x/mobile/cmd/gomobile/env.go:108 +0xa0c
main.buildEnvInit(0x1014a8980, 0x1400011dc20, 0x0)
	/Users/xxx/go/src/golang.org/x/mobile/cmd/gomobile/env.go:79 +0x1a8
main.runBuildImpl(0x10149f860, 0x0, 0x0, 0x0)
	/Users/xxx/go/src/golang.org/x/mobile/cmd/gomobile/build.go:76 +0x38
main.runBuild(0x10149f860, 0x14000140020, 0x2)
	/Users/xxx/go/src/golang.org/x/mobile/cmd/gomobile/build.go:69 +0x28
main.main()
	/Users/xxx/go/src/golang.org/x/mobile/cmd/gomobile/main.go:73 +0x2c0

device: MacBook pro m1

**Comment by davecheney** [comment]
please fill out the entire template.

**Comment by AlexRouSg** [comment]
Looks like he is hitting this panic https://github.com/golang/mobile/blob/master/cmd/gomobile/env.go#L298
And looking up NDK, there is no darwin arm64 build https://developer.android.com/ndk/downloads

cc @hajimehoshi

**Comment by yyzl0418** [comment]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE="auto"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/xxx/Library/Caches/go-build"
GOENV="/Users/xxx/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xxx/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xxx/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.16.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.16.3/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qh/w0rmms1543l0501ptgw_zhxh0000gn/T/go-build2439043797=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
gomobile init




### What did you expect to see?



### What did you see instead?

goroutine 1 [running]:
main.archNDK(...)
/Users/xxx/go/src/golang.org/x/mobile/cmd/gomobile/env.go:298
main.(*ndkToolchain).Path(0x14000197b00, 0x140000b8000, 0x29, 0x1011be402, 0x5, 0x0, 0x14000197938)
/Users/xxx/go/src/golang.org/x/mobile/cmd/gomobile/env.go:327 +0xc0
main.envInit(0x14000016047, 0x31)
/Users/xxx/go/src/golang.org/x/mobile/cmd/gomobile/env.go:108 +0xa0c
main.buildEnvInit(0x1014a8980, 0x1400011dc20, 0x0)
/Users/xxx/go/src/golang.org/x/mobile/cmd/gomobile/env.go:79 +0x1a8
main.runBuildImpl(0x10149f860, 0x0, 0x0, 0x0)
/Users/xxx/go/src/golang.org/x/mobile/cmd/gomobile/build.go:76 +0x38
main.runBuild(0x10149f860, 0x14000140020, 0x2)
/Users/xxx/go/src/golang.org/x/mobile/cmd/gomobile/build.go:69 +0x28
main.main()
/Users/xxx/go/src/golang.org/x/mobile/cmd/gomobile/main.go:73 +0x2c0

**Comment by hajimehoshi** [comment]
@hyangah I don't have M1 Mac then I cannot test this, but I guess gomobile should support M1 environments and this should be easy. What do you think?

**Comment by hajimehoshi** [comment]
> And looking up NDK, there is no darwin arm64 build https://developer.android.com/ndk/downloads

Can't the toolchains be downloaded via Android Studio?

**Comment by AlexRouSg** [comment]
> Can't the toolchains be downloaded via Android Studio?

Nope, as far as I can tell, there is no M1 build of NDK at all yet.
But M1 should be able to run x86_64 code but I'm not sure if that works with the NDK

**Comment by hajimehoshi** [comment]
Ah that makes sense. Then for M1 mac, we should invoke x64 toolchains with Rosetta.

**Comment by seankhliao** [comment]
ndk support should be android/ndk#1299 , comments theresay rosetta works

**Comment by yyzl0418** [comment]
> > Can't the toolchains be downloaded via Android Studio?
> 
> Nope, as far as I can tell, there is no M1 build of NDK at all yet.
> But M1 should be able to run x86_64 code but I'm not sure if that works with the NDK

” gomobile build -target=ios ” ，the same mistake

**Comment by marcofeltmann** [comment]
> Ah that makes sense. Then for M1 mac, we should invoke x64 toolchains with Rosetta.

Unfortunately this may help for Android by now, but not for iOS as with Xcode 13:

```
❯ clang --version
Apple clang version 13.0.0 (clang-1300.0.18.6)
Target: arm64-apple-darwin20.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
