### ISSUE TITLE
x/pkgsite: Remove https://pkg.go.dev/github.com/angora-go/angora

### ISSUE THREAD

**Issue by kamal-github** [golang/go#46460]
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/angora-go/angora
 
 
### What is your user agent?
 

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 
 
 
### What did you expect to see?
 I am owner of this page https://pkg.go.dev/github.com/angora-go/angora, I would like it to be removed from `pkg.go.dev`

**Comment by jba** [comment]
Done.
