### ISSUE TITLE
x/pkgsite: allow an opt-in license check bypass

### ISSUE THREAD

**Issue by icholy** [golang/go#46470]
### What did you do?

Use a license that's not recognised by the license check tool

- [https://github.com/golang/go/issues/46291](https://github.com/golang/go/issues/46291)
- [https://github.com/golang/go/issues/45441](https://github.com/golang/go/issues/45441)
- [https://github.com/golang/go/issues/46252](https://github.com/golang/go/issues/46252)
- [https://github.com/golang/go/issues/43356](https://github.com/golang/go/issues/43356)

There are many more issues like this.

### What did you expect to see?

A way to instruct the pkgsite to render the docs regardless of license. Possibly a `go.mod` directive.

**Comment by ALTree** [comment]
That's probably not possible. From this [golang-dev thread](https://groups.google.com/g/golang-dev/c/mfiPCtJ1BGU/m/qtCrqlrEEwAJ), this segment of rsc's post explains why there's license detection:

> The teams working on the proxy and on pkg.go.dev have spent a lot of
time talking to Google's lawyers about what we can and can't do with
Go source code downloaded from the internet. **The rule we've been given
to follow is that serving a pretty HTML version of the docs is
displaying a modified version of the original, and we can only do that
if there's a recognized known-good license that gives us that
permission.**

**Comment by icholy** [comment]
We can still work within those constraints. There could be a special/additional license file which gives the pkgsite permission to render the docs. The license would be written in a way that's compatible with proprietary licenses.

**Comment by ALTree** [comment]
> There could be a special/additional license file which gives the pkgsite permission to render the docs.

Pretty burdensome if you ask me. And the website would still need to be able to recognize that 2nd licence, which wouldn't even be a standard one... seems like we're back at square one.

cc @jba on this.

**Comment by jba** [comment]
I'm sorry, I don't have any new ideas here.

We don't want to go the route where you give pkgsite special permission. That doesn't scale well to other sites and tools that have the same legal issue as we do.

If your license is not on our list, but is OSI-approved and grants the permission we need, there's a decent chance we can add it to our list. File an issue pointing to the license and we'll take a look.
