### ISSUE TITLE
x/tools/gopls: semantic tokenizing of package identifier

### ISSUE THREAD

**Issue by soypat** [golang/go#46475]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64

gopls version
golang.org/x/tools/gopls v0.6.11
    golang.org/x/tools/gopls@v0.6.11 h1:7S2k0xuVYc3secjy2uz0n+fGYxGJU6gXsLOmQ/r1HoI=
</pre>

### What did you do?

Import any package like so:

```go
import main

import "io"

func main() {
    err := io.EOF
    panic(err)
}
```

### What did you expect to see?
`io` tokenized differently from variables such as `err` in this case.

### What did you see instead?
`io` and `err` have same color.

### Motivation
I may be wrong, but are packages tokenized just like variables? It seems to be the case. I propose there be some distinction so that one can easily identify when one is dealing with a package level identifier (i.e. `io.EOF`) vs. a method/field (i.e. `err.Error()`).

Tokens available for a LSP implementation are [listed here.](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_semanticTokens). I believe `class` semantic token would be suited for packages as they represent a similar namespacey construct.

**Comment by pjweinb** [comment]
package names are 'namespace', err is 'variable'.  In the theme of my
vscode, the color of namespace is #4EC9B0 and variable is #9CDCFE (using
the command Editor: inspect tokens and scopes) What theme are you using?

there's a setting editor.tokenColorCustomizations, but the documentation
doesn't mention semantic tokens.

**Comment by soypat** [comment]
First of all thanks for the quick reply. You are right about there being a `editor.tokenColorCustomizations` option but I'm getting only the following properties available
* comments
* functions
* variables
* keywords
* numbers
* strings
* textMateRules
* types

I'm on VSCode

**Comment by stamblerre** [comment]
> Import any package like so:
> 
> ```go
> import main
> 
> import "io"
> 
> func main() {
>     err := io.EOF
>     panic(err)
> }
> ```

I just wanted to point out that there's a mistake in this example--it should be `package main` on the first line. Does fixing that correct the issue for you?

**Comment by soypat** [comment]
@stamblerre I was testing actual working packages, I typed the example up as a MWE. The issue still holds.

**Comment by stamblerre** [comment]
I think that, in this instance, this is an issue with the Darcula theme that you could perhaps raise in that repository. For contrast, see how it looks with VS Code's default dark theme:

![Screen Shot 2021-06-02 at 10 21 23 AM](https://user-images.githubusercontent.com/5856771/120497441-673fbc00-c38c-11eb-92d3-24369e479147.png)

`io` is indeed tokenized as a namespace:

![Screen Shot 2021-06-02 at 10 22 33 AM](https://user-images.githubusercontent.com/5856771/120497540-7f174000-c38c-11eb-8df7-ef298188aab2.png)

which logically makes more sense than changing it to class.

And `err` is a variable, as expected:

![Screen Shot 2021-06-02 at 10 23 10 AM](https://user-images.githubusercontent.com/5856771/120497643-93f3d380-c38c-11eb-8824-675b768f1b75.png)

If the Darcula theme doesn't provide differing colorization for namespace tokens, then that is an issue with the theme, not the tokenization here.

**Comment by soypat** [comment]
You are right. Switching to VSCode default highlighting I can see the namespace colorization.  I'm not sure what I was doing wrong before but after testing this and changing the settings (below) I can change Darcula's `namespace` token color.

```json
"editor.semanticTokenColorCustomizations": {"rules": {"type": "#ff0000","namespace":"#ff0000"}},
```
I'm closing this as it is not an issue related to go or gopls.
