### ISSUE TITLE
Why is version of a package on index.golang.org very different from the version on GitGub?

### ISSUE THREAD

**Issue by yurivict** [golang/go#46476]
This query:
> wget "https://index.golang.org/index?limit=1&since=2021-05-28T01:21:42.994935Z"

returns this record:
```
{"Path":"github.com/concourse/concourse","Version":"v1.6.1-0.20210527214455-4a0d7de97e1a","Timestamp":"2021-05-28T01:21:42.994935Z"}
```

However, https://github.com/concourse/concourse/tags shows that the last version is ```v7.3.1```.

How can it be that these versions are so different? Where does the version ```v1.6.1``` come from?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
