### ISSUE TITLE
testing: unclear if T.Name includes sub-tests as part of its string

### ISSUE THREAD

**Issue by mvdan** [golang/go#46488]
The current docs say:

>  Name returns the name of the running test or benchmark. 

For a `func TestFoo(t *testing.T)`, I think it's reasonably clear that Name will be `TestFoo`.

However, for a sub-test like `t.Run("Bar", ...)`, it's not clear from the documentation if Name will return `TestFoo/Bar` or just `TestFoo`.

Another open question is whether the name will be altered, just like it is when printing output. For example, `t.Run("bar baz", ...)` ends up printing `TestFoo/bar_baz` in the terminal, so if the subtest name is included in the Name method, I'm not sure which of the two I'd expect.

cc @mpvl as per the owners doc
cc @adg @bradfitz since they added the Name method

**Comment by ianlancetaylor** [comment]
From the proposal in #17231 I think it's clear that the name of a subtest is intended to be distinct from the name of the enclosing test.

**Comment by mvdan** [comment]
I'm not sure if that means that Name would always just return the root test's name :)

**Comment by ianlancetaylor** [comment]
What I mean is that for code like the following the two logged names should be different (and fortunately that is true today):

```Go
package x_test

import "testing"

func TestTop(t *testing.T) {
	t.Log(t.Name())
	t.Run("Sub", func(t *testing.T) {
		t.Log(t.Name())
	})
}
```

**Comment by mvdan** [comment]
Ah, gotcha. That's how I guessed it would work, so that's good to know. It seems to also obtain names just like they are printed, e.g. `TestTop/Sub_with_spaces` for `t.Run("Sub with spaces", ...)`.

**Comment by ianwoolf** [comment]
I pick this one.I will work for this in these few days :)

**Comment by ianwoolf** [comment]
i will work for it in these few days  :)
