### ISSUE TITLE
x/build/cmd/updatecontrib: add vscode-go and vulndb contributors to list of Go contributors

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#46487]
We should add the following repositories to the [list of repositories](https://go.googlesource.com/build/+/refs/heads/master/cmd/updatecontrib/updatecontrib.go#262) queried for Go contributors:
*  vscode-go
*  vulndb

@golang/release

**Comment by dmitshur** [comment]
These repos seem more different compared to the repositories that updatecontrib [currently tracks](https://github.com/golang/build/blob/10d5d32f2cce9f6668b9b524d57309fbde566a8e/cmd/updatecontrib/updatecontrib.go#L263-L294), which are primarily golang.org/x repos with Go code. (The proposal repository is a notable exception in that it doesn't have much Go code at all.)

vscode-go is primarily written in TypeScript, does not reuse the same license as in the Go repository, and has its own contribution guide. Is it desirable for its contributors to be automatically added to the Go repository's CONTRIBUTORS file? CC @hyangah for input.

vulndb is currently described as "Neither the code, nor the data, nor the existence of this repository is to be considered stable until an approved proposal." so perhaps we need to wait for that to change before considering next steps, but CC @rolandshoemaker and @FiloSottile for early input.

**Comment by cagedmantis** [comment]
Thanks for the input @hyangah.

**Comment by cagedmantis** [comment]
We've reached the decision that neither of these repositories will be used to seed contributor data. Thank you for the feedback, this has been helpful in clarifying what should seed the data.
