### ISSUE TITLE
How is `go list -m -u -json all` meant to be parsed? It's not emitting json parseable output

### ISSUE THREAD

**Issue by jadekler** [golang/go#46486]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.16.3
</pre>

### Does this issue reproduce with the latest release?

I imagine so.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/deklerk/.cache/go-build"
GOENV="/home/deklerk/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/deklerk/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/deklerk/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/deklerk/workspace/exp/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2758004077=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
$ go list -m -u -json all
{
	"Path": "gorelease-load-module",
	"Main": true,
	"Dir": "/tmp/gorelease-load714449427",
	"GoMod": "/tmp/gorelease-load714449427/go.mod",
	"GoVersion": "1.12"
}
{
	"Path": "example.com/retract",
	"Version": "v0.0.0-gorelease",
	"Replace": {
		"Path": "/tmp/gorelease892838020",
		"Dir": "/tmp/gorelease892838020",
		"GoMod": "/tmp/gorelease892838020/go.mod",
		"GoVersion": "1.12"
	},
	"Update": {
		"Path": "example.com/retract",
		"Version": "v0.0.1",
		"Time": "0001-01-01T00:00:00Z"
	},
	"Dir": "/tmp/gorelease892838020",
	"GoMod": "/tmp/gorelease892838020/go.mod",
	"GoVersion": "1.12"
}
{
	"Path": "example.com/retractdep",
	"Version": "v1.0.0",
	"Time": "0001-01-01T00:00:00Z",
	"Update": {
		"Path": "example.com/retractdep",
		"Version": "v1.0.1",
		"Time": "0001-01-01T00:00:00Z"
	},
	"Dir": "/tmp/gorelease_test-gocache487883119/pkg/mod/example.com/retractdep@v1.0.0",
	"GoMod": "/tmp/gorelease_test-gocache487883119/pkg/mod/cache/download/example.com/retractdep/@v/v1.0.0.mod",
	"GoVersion": "1.12",
	"Retracted": [
		"retracted by module author"
	]
}
```

This is not parseable: it's missing the top level list brackets and commas between the first level items.

### What did you expect to see?

Non-JSON-parseable output.

### What did you see instead?

JSON-parseable output.

------------

https://play.golang.org/p/UXPUT6NGoas

**Comment by psampaz** [comment]
It is parseable. Just use https://golang.org/pkg/encoding/json/#Decoder to parse it.

**Comment by jadekler** [comment]
Aha, thanks!
