### ISSUE TITLE
x/pkgsite: github.com/calamity-of-subterfuge/cos/v2

### ISSUE THREAD

**Issue by Tjstretchalot** [golang/go#46506]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/calamity-of-subterfuge/cos/v2
 
### What is your user agent?
 

 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
 
### Screenshot
 

 
![Screenshot 2021-06-01 164111](https://user-images.githubusercontent.com/931176/120403021-4037aa80-c2f8-11eb-9ce9-c8f6e48d9b8d.png)
 
 
### What did you do?
 

 
I intended to release a v0, but because of some confusion with thinking that /v2 on packages was referring to a different type of go.mod file (e.g., for whatever reason I thought it was the schema of the go.mod file) I added that to the end of the name of the module, and now I can't tag it as 0.0.1 because it redirects to to the /v2
 
 
### What did you expect to see?
 
It did what it should have done but maybe a warning since it didn't have any git tags
 
### What did you see instead?

It redirects github.com/calamity-of-subterfuge/cos to github.com/calamity-of-subterfuge/cos/v2 despite github.com/calamity-of-subterfuge/cos being the one that I should be using

**Comment by jba** [comment]
We're a little backed up in our processing right now, but the module without the v2 should be ready in a day or so.

**Comment by julieqiu** [comment]
Fixed.
