### ISSUE TITLE
proposal: Go 2: add random comparision operator, perhaps <> or <=>

### ISSUE THREAD

**Issue by malisetti** [golang/go#46511]
Another option is to have an operator, perhaps <> or <=>, which randomly chooses whether the comparison succeeds or fails. This could be used to drive high-quality tests for fault-tolerant programming.

_Originally posted by @robpike in https://github.com/golang/go/issues/45319#issuecomment-811864746_

I am making this proposal inspired from the above comment. If have a random comparison operator and have control over it's randomness via build flags it would be useful to write tests and also code.

**Comment by randall77** [comment]
That comment by Rob was a joke. If you're serious, please fill out the proposal template and reopen.
