### ISSUE TITLE
pool.put()

### ISSUE THREAD

**Issue by czzsunnyman** [golang/go#46515]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.16.3 windows/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\86135\AppData\Local\go-build
set GOENV=C:\Users\86135\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=F:\gopath\pkg\mod
set GONOPROXY=git.addnewer.com
set GONOSUMDB=git.addnewer.com
set GOOS=windows
set GOPATH=F:\gopath;C:\Users\86135\go
set GOPRIVATE=git.addnewer.com
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\LenovoSoftstore\Install\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\LenovoSoftstore\Install\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=F:\gopath\src\apiserver\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\86135\AppData\Local\Temp\go-build1364965771=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
    why does not the method  pool.put()  epmty the object?

### What did you expect to see?

i think pool.put() should empty the object such as bytebufferpool.put()，why not?

**Comment by mvdan** [comment]
What pool?

Also, see https://golang.org/wiki/Questions.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
