### ISSUE TITLE
cmd/go: TestWindowsDefaultBuildmodIsPIE/cgo fails on windows-arm64-aws

### ISSUE THREAD

**Issue by dmitshur** [golang/go#46510]
```
--- FAIL: TestWindowsDefaultBuildmodIsPIE (0.00s)
    --- FAIL: TestWindowsDefaultBuildmodIsPIE/cgo (9.23s)
        go_test.go:2129: running testgo [build -o C:\Users\gopher\AppData\Local\Temp\cmd-go-test-577963624\gotest1567665900\main.exe C:\Users\gopher\AppData\Local\Temp\cmd-go-test-577963624\gotest1567665900\main.go]
        go_test.go:2188: .edata section is not present
go test proxy running at GOPROXY=http://127.0.0.1:52061/mod
FAIL
FAIL	cmd/go	362.581s
```

Source: https://storage.googleapis.com/go-build-log/152255c1/windows-arm64-aws_1dc534d5.log from [CL 323992](https://go-review.googlesource.com/c/go/+/323992/2#message-ee53885b37e9b126fb21198087ae5ee01d6657f0).

This needs investigation.

**Comment by bcmills** [comment]
This test was added in [CL 230217](https://golang.org/cl/230217) (CC @alexbrainman @ianlancetaylor) for #35192 (CC @zx2c4 @aarzilli).

**Comment by alexbrainman** [comment]
The code that fails

https://github.com/golang/go/blob/18e666bad75362ef7d031ebf557effdc42dd290f/src/cmd/go/go_test.go#L2181-L2189

was added in

https://go-review.googlesource.com/c/go/+/264459

The code assumes that exported symbols are stored in `.edata` PE section. And that is a reasonable assumption for executable built with Mingw GCC.

Perhaps that assumption is incorrect for whatever C compiler is used on windows-amd64 builder. I would try to build executable as per test and look at executable PE sections.

/cc @qmuntal and @zx2c4 in case they have suggestions here

Alex

**Comment by qmuntal** [comment]
_Assumption: `windows-arm64-aws` uses a llvm toolchain._

I don't really know much about `llvm/clang`,  but looking at the `lld` [source code](https://rev.ng/gitlab/or1k/lld/-/blob/master/COFF/Writer.cpp#L349) it seems that the exported symbols are also stored in `.edata`.

My guess is that:
- The `cgo` toolchain is missing some parameters when invoking `clang`
- `lld` (clang's linker) is not seeing any exported symbol, thus it is not creating the `.edata` section.

**Comment by dmitshur** [comment]
@qmuntal See [here](https://github.com/golang/build/blob/8adac88dfeba46e64dabe820cdf83899e135506d/env/windows-arm64/startup.ps1#L122) for more information about the C toolchain `windows-arm64-aws` uses.

**Comment by alexbrainman** [comment]
> See [here](https://github.com/golang/build/blob/8adac88dfeba46e64dabe820cdf83899e135506d/env/windows-arm64/startup.ps1#L122) for more information about the C toolchain `windows-arm64-aws` uses.

Thanks for the link, but I don't have and don't use windows-arm64. So I don't plan working on it.

Alex

**Comment by dmitshur** [comment]
`TestWindowsDefaultBuildmodIsPIE/cgo` no longer fails on `windows-arm64-aws` as of [CL 327549](https://golang.org/cl/327549), so closing. (CC @zx2c4.)

There's also #46719 which is still open and can be used if there's something more to do.
