### ISSUE TITLE
x/pkgsite: new version processing is delayed

### ISSUE THREAD

**Issue by senpathi** [golang/go#46527]
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/senpathi/paramex
 
 
### What is your user agent?
 

 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
 
 
### What did you expect to see?
 
 I need to see v1.0.1 documentation here
 
### What did you see instead?

There is a previous untagged version's documentation

**Comment by jba** [comment]
We're experiencing processing delays for new modules. It may take a day or two for your module to show up. Sorry about that.

**Comment by 89z** [comment]
https://github.com/golang/go/issues/46350

**Comment by 89z** [comment]
https://github.com/golang/go/issues/46350

https://github.com/golang/go/issues/46527
https://github.com/golang/go/issues/46535
https://github.com/golang/go/issues/46538

**Comment by 89z** [comment]
CC @julieqiu

**Comment by jba** [comment]
Processing has resumed. We expect to be caught up over the weekend.

**Comment by senpathi** [comment]
Now It is Fixed. Thank You guys 🥇

**Comment by jba** [comment]
We're all caught up.
