### ISSUE TITLE
x/website: cannot Google search for Release History page

### ISSUE THREAD

**Issue by rittneje** [golang/go#46521]
Not sure if this is really an x/website issue or just a Google search algorithm bug, but when searching "golang releases" or "golang release history" I no longer see https://golang.org/doc/devel/release in the search results. I've tried multiple browsers and private windows but it never comes up anymore. However, it does show up if I use Yahoo or Bing.

**Comment by seankhliao** [comment]
cc @dmitshur

**Comment by dmitshur** [comment]
The URL of that page has changed very recently (it used to have an .html suffix, as in https://golang.org/doc/devel/release.html, but now it redirects to the shorter URL without the extension), so perhaps this just needs some time to reappear. Let's give that a chance.

CC @rsc.

**Comment by rittneje** [comment]
@dmitshur FYI it still doesn't show up in the search results.

**Comment by seankhliao** [comment]
I think this works now?

**Comment by dmitshur** [comment]
Thanks, indeed, it shows up now. Closing.
