### ISSUE TITLE
regexp compile an invalid regular expression: regexp.Compile("/dd[a-z]{,3}") returns no error

### ISSUE THREAD

**Issue by panush** [golang/go#46537]
### What version of Go are you using (`go version`)? 

<pre>
$ go version
go version go1.16.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output:
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/$USER/.cache/go-build"
GOENV="/$USER/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/$USER/go/pkg/mod"
GOOS="linux"
GOPATH="/$USER/go"
GOPROXY="https://proxy.golang.org,direct"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-lhs -L/usr/local/lib/"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1019713328=/tmp/go-build -gno-record-gcc-switches"</summary><br><pre>

$ go env

</pre></details>

### What did you do?
https://play.golang.org/p/4d7gR_xDEDB

reg, err2 := regexp.Compile("/dd[a-z]{,3}")

### What did you expect to see?
I expect Compile to return some error since I'm using an invalid regular expression

### What did you see instead?
Compile returned a nil error and a valid regexp object.

**Comment by seankhliao** [comment]
This is a valid regex https://play.golang.org/p/LRMBKINXzbH
