### ISSUE TITLE
x/website: install from source doesn't exist

### ISSUE THREAD

**Issue by svenwiltink** [golang/go#46545]
https://golang.org/doc/install-source.html (linked from https://golang.org/doc/install) shows the following error:

open REDACTED: file does not exist

**Comment by bcmills** [comment]
CC @golang/release

**Comment by bcmills** [comment]
(More evidence for #37047?)

**Comment by dmitshur** [comment]
This was missed in a recent refactor in [CL 296383](https://golang.org/cl/296383). We need to add a redirect from the old path at `_content/doc/install/source.html`:

```
<!--{
	"Redirect": "/doc/install/source"
}-->
```

#37047 is going to be more helpful for x/website now that it's going though larger refactors. CC @rsc.
