### ISSUE TITLE
internal/fuzz: add missing supported GOOS to internal/fuzz/sys_posix.go [freeze exception]

### ISSUE THREAD

**Issue by dchapes** [golang/go#46554]
Currently `src/internal/fuzz/sys_posix.go` only has build constraints for darwin linux.
When I add the missing `freebsd` constraint it works perfectly fine for me on freebsd/amd64 (FreeBSD 11.4).
I imagine it also works on the other BSDs as well, they are all reasonably POSIX compliant.

In future, in announcements such as [the one on the Go Blog](https://blog.golang.org/fuzz-beta), *please* include a sentence somewhere if the list of GOOS/GOARCH supported is limited! Believe it or not, there is a thriving world outside of Mac and Linux. It's a pain in the butt to go through the effort of downloading the dev.fuzz branch on a slow link to get nothing but an uninformative `panic: not implemented` and a stack trace!

**Comment by dr2chase** [comment]
I don't think it was tested across all the other OSes (yet), so "supported" might be too strong a word just yet.  Good to know that it works, though.

**Comment by katiehockman** [comment]
CC @golang/release
Requesting a freeze exception to support coverage instrumentation with FreeBSD. This will only affect fuzzing, not the default behavior of go test. https://go-review.googlesource.com/c/go/+/325209/ is the CL (it needs to be cherrypicked to master)

**Comment by bcmills** [comment]
(This is a release-blocker in the sense that it needs a decision on the freeze exception. If the freeze exception is not granted, we can move it to the Go1.19 milestone.)

**Comment by heschi** [comment]
Approved -- this is a small change to a new feature with low risk.
