### ISSUE TITLE
x/net/http2: 

### ISSUE THREAD

**Issue by kinjal-mori** [golang/go#46562]
### current go version

<pre>
$ go version
go version go1.10.3 linux/amd64

</pre>

### I am using go 1.10.3 and trying to install all packages by <pre> go get . </pre> but its giving me following error 
<pre> 
# golang.org/x/net/http2
../../../golang.org/x/net/http2/client_conn_pool.go:305:6: undefined: errors.Is
../../../golang.org/x/net/http2/server.go:234:72: undefined: tls.VersionTLS13
</pre>

Please help me with this

**Comment by davecheney** [comment]
Go 1.10 is long out of support. You should upgrade to Go 1.16, the most recent supported version.
