### ISSUE TITLE
vs code go run command  question

### ISSUE THREAD

**Issue by narojay** [golang/go#46561]
![image](https://user-images.githubusercontent.com/19280886/120763423-c5fe6480-c549-11eb-9bbb-95e989cbb27a.png)

Why the `go run .\server.go` command does not download the package automatically？

I need to  execute `go get github.com/labstack/echo` then  execute  `go run .\server.go`, I think it's a waste of time

How To Config or  Execute Command

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
