### ISSUE TITLE
proposal: strings: function: new function to reverse a string

### ISSUE THREAD

**Issue by 4f77616973** [golang/go#46568]
Golang doesn't seem to have an inbuilt function to reverse a given string. Here is my proposal for a basic function to reverse a string in Golang. 

```
func Reverse(s string) string {
    var reversed string
    for _, v := range s {
        reversed = string(v) + result
    }
    return reversed
}
```

This function can be added to _src/strings/strings.go_, along with other string functions such as explode, trim, uppercase etc.

**Comment by ALTree** [comment]
Hi,

this has been proposed, and rejected, in the past. See #14777 and #36887, in particular https://github.com/golang/go/issues/36887#issuecomment-591601541:

> strings.Reverse is a duplicate of #14777. It remains not needed often enough to merit inclusion in the standard library.

Closing here as a dup.
