### ISSUE TITLE
src/string: strings.go: syntax: Why Explode function doesn't follow Golang PascalCase convention.

### ISSUE THREAD

**Issue by nelsonlobo99** [golang/go#46567]
In strings.go, some functions like explode function do not follow PascalCase. Why is the explode function suppose to have limited scope.

Example:
Original syntax:
```
func explode(s string, n int)
```
Expected syntax: 
```
func Explode(s string, n int)
```

**Comment by ALTree** [comment]
The name is lowercase because the designer(s) of the API didn't want to make it part of the package's public interface. It's a private function, hence the lowercase name.
