### ISSUE TITLE
website: exclude line numbers when copying from source files

### ISSUE THREAD

**Issue by gopherbot** [golang/go#4656]
by **Dmitry.Gudkov**:

<pre>This bug is related to <a href="http://golang.org">http://golang.org</a> website

Code samples (e.g. <a href="http://golang.org/doc/articles/wiki/final.go)">http://golang.org/doc/articles/wiki/final.go)</a> contain line numbers
which makes copy-pasting of the entire code or some part of it littered with line
numbers so additional effort is required to clean up code before compiling.

Ubuntu 12.10, Chrome 23.0.1271.97</pre>

**Comment by ALTree** [comment]
Same as #18279, fixed by golang/tools@0a14ca4.
