### ISSUE TITLE
cmd/compile: failure to export mutually recursive type parameters

### ISSUE THREAD

**Issue by mdempsky** [golang/go#46575]
I have this test case working with unified IR, and I thought it was working with golang.org/cl/323029 last night when I tested it, but it's currently failing at de614651561c6d5bfe1e68bddaf0dedab9a0ecb0 when I try compiling with `-G=3` due to:

```
$GOROOT/test/typeparam/mutualimp.dir/a.go:11:6: internal compiler error: weird package in name: .dict => .dict from "", not "/usr/local/google/home/mdempsky/wd/go/test/typeparam/mutualimp.dir/a"
```

```
package a

type X int
func (x X) M() X { return x }

func F[T interface{ M() U }, U interface{ M() T }]() {}
func G() { F[X, X]() }
```

```
package b

import "./a"

func H() {
	a.F[a.X, a.X]()
	a.G()
}
```

/cc @danscales @randall77 @griesemer

**Comment by danscales** [comment]
Fixed by https://github.com/golang/go/issues/46575
