### ISSUE TITLE
x/build/cmd/release: menu install from right-click fails on Windows

### ISSUE THREAD

**Issue by iwdgo** [golang/go#46570]
### What version of Go are you using (`go version`)?

<pre>
go version go1.16.4 windows/amd64

Microsoft Windows [Version 10.0.19042.985]
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=<local app data profile>\go-build
set GOENV=<roaming app data directory>\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=%GOPATH%\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=%UserProfile%\Documents\<some directory>
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=%ProgramFiles%\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=%ProgramFiles%\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.4
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=<local app data directory>\Temp\go-build3116843351=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

Download latest windows msi package from https://golang.org/dl
Open Explorer and right-click to select "Install" menu (default in bold).
![image](https://user-images.githubusercontent.com/19574010/120834601-86447680-c563-11eb-9b43-34ed68728f86.png)

### What did you expect to see?
Usual prompt to confirm installation.

### What did you see instead?

![image](https://user-images.githubusercontent.com/19574010/120834525-6dd45c00-c563-11eb-92b4-d9c503217d6c.png)
Issue already occurs on `go1.16.4`

Workaround is to open `CMD` and run the `msi`. Then, the installation starts successfully.

**Comment by AlexRouSg** [comment]
I cannot reproduce this on windows, might be a antivirus thing or something local.

**Comment by iwdgo** [comment]
There is no report in the antivirus log but I cannot reproduce it anymore. Sorry for the noise.
