### ISSUE TITLE
x/tools/gopls: could not import local package

### ISSUE THREAD

**Issue by 2435043xia** [golang/go#46584]
1.project can be built successfully,it's work.
2.vscode(or gopls) show errors 'could not import **** package'
3.Goland will not have this problem, But I want to use vscode remote

The project structure is as follows:

Assume modName is MyProject

- GoPath
- src
     * MyProject   -----  open project
         * go.mod
         * cmd
             * package1
                * main.go   // import "MyProject/internal/package1"
         * internal
             * package1
                 * goFiles   ---- import "MyProject/internal/package2"    //show errors
             * package2
                 * goFiles

What should I change to let the error go away?

**Comment by findleyr** [comment]
Hi, I am assuming that the `GoPath` directory is part of your `GOPATH`. In that case, it looks like the code is not in `GoPath/src`. Per `go help gopath`:

```
The src directory holds source code. The path below src
determines the import path or executable name.
...
If DIR is a directory listed in the GOPATH, a package with
source in DIR/src/foo/bar can be imported as "foo/bar" and
```

However, you report that your build succeeds from the command line. Could you share:
 - what specific command succeeds, when run from which directory?
 - do you have a go.mod file in your project?

Thanks

**Comment by 2435043xia** [comment]
> Hi, I am assuming that the `GoPath` directory is part of your `GOPATH`. In that case, it looks like the code is not in `GoPath/src`. Per `go help gopath`:
> 
> ```
> The src directory holds source code. The path below src
> determines the import path or executable name.
> ...
> If DIR is a directory listed in the GOPATH, a package with
> source in DIR/src/foo/bar can be imported as "foo/bar" and
> ```
> 
> However, you report that your build succeeds from the command line. Could you share:
> 
> * what specific command succeeds, when run from which directory?
> * do you have a go.mod file in your project?
> 
> Thanks

My issue description is wrong,i have updated it.

1.I run "go build cmd/package1/main.go" in "MyProject" directory. The project is indeed under GOPATH/src
2.yes,i have go.mod.

**Comment by 2435043xia** [comment]
> Hi, I am assuming that the `GoPath` directory is part of your `GOPATH`. In that case, it looks like the code is not in `GoPath/src`. Per `go help gopath`:
> 
> ```
> The src directory holds source code. The path below src
> determines the import path or executable name.
> ...
> If DIR is a directory listed in the GOPATH, a package with
> source in DIR/src/foo/bar can be imported as "foo/bar" and
> ```
> 
> However, you report that your build succeeds from the command line. Could you share:
> 
> * what specific command succeeds, when run from which directory?
> * do you have a go.mod file in your project?
> 
> Thanks

I just tried to reproduce it with a new project, I failed.
I guess that there is a problem with my environment.This makes me very confused.
Thank you for your help. I will try to fix my environment
