### ISSUE TITLE
syscall: TestStdioAreInheritable fails on windows-arm64-aws because it tries to build a library using an unsupported build mode

### ISSUE THREAD

**Issue by dmitshur** [golang/go#46582]
The new-to-Go 1.17 windows/arm64 port (#36439) at this time doesn't support the c-shared build mode (#46549). `TestStdioAreInheritable` was added in [CL 316269](https://golang.org/cl/316269) and currently makes use of the c-shared build mode:

https://github.com/golang/go/blob/95939e8de71d9e8d8deea3d1605bd34130588292/src/syscall/syscall_windows_test.go#L107-L111

​The test fails on windows/arm64 as detected by the `windows-arm64-aws` builder:

```
--- FAIL: TestStdioAreInheritable (0.08s)
   ​syscall_windows_test.go:110: failed to build go library: exit status 1
       ​-buildmode=c-shared not supported on windows/arm64
FAIL
FAIL	syscall	0.353s
```

Source: https://storage.googleapis.com/go-build-log/78592762/windows-arm64-aws_f90b24c9.log from [CL 323991](https://go-review.googlesource.com/c/go/+/323991/2#message-9fca96040291eda63926f45afdbace7c9b9f101f).

The test can be skipped on windows/arm64 since that port doesn't meet the minimum requirements ([CL 323992](https://golang.org/cl/323992) adds this skip). Perhaps the test can be updated not to require c-shared build mode. As another option, the test may stop failing if the c-shared build mode gets enabled for windows/arm64 port.

CC @alexbrainman, @ianlancetaylor.

**Comment by dmitshur** [comment]
The windows/arm64 port supports c-shared build mode as of [CL 326310](https://golang.org/cl/326310), and `TestStdioAreInheritable` is no longer failing. (CC @zx2c4.) Closing as fixed.

**Comment by zx2c4** [comment]
That test is actually skipped now because those builders don't have native powershell.

**Comment by dmitshur** [comment]
Thanks. I understand issue #46701 tracks the remaining future work, so it's okay to keep this closed.
