### ISSUE TITLE
test: add test case for runtime type identity for generics instantiated with anonymous struct literals with tags

### ISSUE THREAD

**Issue by mdempsky** [golang/go#46591]
This program should print 2: https://go2goplay.golang.org/p/CC066DjHD5x

cmd/compile gets this right, but cmd/go2go prints 1.

/cc @ianlancetaylor @griesemer (thx @dominikh for test case)

**Comment by griesemer** [comment]
The go2go playground is not actively supported anymore.
But we should probably add a test case for the compiler, just to cover this.
cc: @ianlancetaylor

**Comment by cherrymui** [comment]
As noted, cmd/go2go is not actively supported now. Leave the issue open for adding the test case. Thanks.
