### ISSUE TITLE
go/types,cmd/compile/internal/types2: type instantiation fails to distinguish similarly named defined types within a package

### ISSUE THREAD

**Issue by mdempsky** [golang/go#46592]
This program is invalid, but go/types returns success for type checking it: https://go2goplay.golang.org/p/F-SWVR4f2dN (Note: The go2go diagnostic is only produced if/after type checking succeeded; contrast https://go2goplay.golang.org/p/o5NZXojNhMX.)

This appears to be because the string produced by `instantiatedHash` doesn't distinguish package-scope defined types from function-scope defined ones. In CL 324573, I've workaround around this by hacking writeTypeName to include TypeName.Pos when writing type names for instiantiatedHash:

https://go-review.googlesource.com/c/go/+/324573/8/src/cmd/compile/internal/types2/subst.go
https://go-review.googlesource.com/c/go/+/324573/8/src/cmd/compile/internal/types2/typestring.go

With that change, unified IR is able to successfully compile this test case that exercises a bunch of nested type parameters and similarly named defined types: https://go-review.googlesource.com/c/go/+/324573/8/test/typeparam/nested.go

/cc @griesemer @findleyr

**Comment by griesemer** [comment]
instantiatedHash is incorrect for local types (and the comment in the source says so).

**Comment by griesemer** [comment]
@mdempsky Is there anything left to do here (besides a clearer error message)?

For the example
```Go
package main

type T[_ any] int

type X int

func main() {
	type GlobalX = X
	type X int

	var _ T[X] = T[GlobalX](0)
}
```
the compiler now produces:
```
x.go:11:15: incompatible type: cannot use T[GlobalX](0) (constant 0 of type T[X]) as T[X] value
```
The error message remains confusing as the types appear to be the same. I filed #48295 for that.

**Comment by mdempsky** [comment]
Nope, sounds like this is fixed, and I think covered by test/typeparam/nested.go. Thanks for filing #48295.
