### ISSUE TITLE
x/website: ref/mod: wrong character for grave accent

### ISSUE THREAD

**Issue by rillig** [golang/go#46599]
_content/ref/mod.md (https://golang.org/ref/mod) says:
~~~markdown
grave accents (<code>&#60;</code>
~~~
which is rendered as:
> grave accents (<code>&#60;</code>

It should say instead:
~~~markdown
grave accents (<code>&#x60;</code>
~~~
which is rendered as:
> grave accents (<code>&#x60;</code>

**Comment by jerobado** [comment]
Hello, I'll send a PR shortly.
