### ISSUE TITLE
go compiler to raise an error if function not explicitly `return nil` with return value of interface type signature

### ISSUE THREAD

**Issue by ideawu** [golang/go#46627]
Many known that the famous `nil != nil` trap when using interface variable. The Golang FAQ "[Why is my nil error value not equal to nil?](https://golang.org/doc/faq#nil_error)" says:

> To return a proper nil error to the caller, the function must return an explicit nil:
> ```
> func returnsError() error {
> 	if bad() {
> 		return ErrBad
> 	}
> 	return nil
> }
> ```

And the FAQ show an bad(wrong) coding paradigm when a function with return value of interface type signature:

> ```
> func returnsError() error {
> 	var p *MyError = nil
> 	if bad() {
> 		p = ErrBad
> 	}
> 	return p // Will always return a non-nil error.
> }
> ```

So, would it be a good idea for go compiler, to discover these kind of bad code and treats as a programming error(or a friendly warning) that must be fixed? Whenever a function has return value of interface signature, it must explicitly has at least one line of

```
return nil
```

**Comment by seankhliao** [comment]
Consider any non error interface, there's no guarantee that valid code will always have a path that returns nil, eg:

```go
func New() io.Reader {
    return &myStruct{}
}
```

And in general, the false positive rate is going to be too high for both the compiler or `go vet` to do anything about it.

**Comment by timothy-king** [comment]
> And in general, the false positive rate is going to be too high for both the compiler or go vet to do anything about it.

Staticcheck has a checker for this [SA4023](https://staticcheck.io/docs/checks#SA4023). IMO there is room for `go vet` to potentially warn about this in the future. The false positive rate would need to be quite low. (Agree that an error in the compiler seems too likely to have false positives on valid programs.)
