### ISSUE TITLE
x/pkgsite: Docs not updated after charging my Github username

### ISSUE THREAD

**Issue by remyduthu** [golang/go#46623]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/remyduthu/Library/Caches/go-build"
GOENV="/Users/remyduthu/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/remyduthu/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/remyduthu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.4/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dl/z97t194j3xv19z0jljyyrksm0000gn/T/go-build3456480264=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Enter https://pkg.go.dev/github.com/remyduthu/faces in my browser.

### What did you expect to see?

The documentation for the new repository: https://github.com/remyduthu/faces.

### What did you see instead?

The documentation for the old repository (redirection): https://github.com/remydt/faces.

**Comment by remyduthu** [comment]
Maybe, the easiest way to fix it could be to delete the old documentation?

**Comment by jba** [comment]
It looks like you changed the tag on the new repo, which tends to confuse things.

Right now, the [go.mod file in the new repo at v1.0.0](https://github.com/remyduthu/faces/blob/v1.0.0/go.mod) has a module path that matches the repo.

However, at some point the module path referred to the old repo, and that is the version that the proxy knows about:
```
> curl -L -o faces.zip https://proxy.golang.org/github.com/remyduthu/faces/@v/v1.0.0.zip
> unzip faces.zip
> cat github.com/remyduthu/faces@v1.0.0/go.mod
module github.com/remydt/faces
...
```

When pkgsite notices that the module path doesn't match the go.mod contents, it redirects you to the path in the go.mod file. That explains the gray banner "Redirected from github.com/remyduthu/faces" when you visit https://github.com/remyduthu/faces.

What you should have done is made a new tag when you changed the go.mod file. You can still do that: just tag master v1.0.1 and `go get` it, and soon pkgsite should show the right path.

Closing, but re-open if there are still problems after doing that.

**Comment by jba** [comment]
> Perhaps the easiest way to fix it would be to delete the old documentation? That's not a problem as the actual package is not currently used.

I could also remove the path github.com/remydt and all sub-paths from the site, but that wouldn't fix the problem I described above. I think we'd just redirect to a 404.

Would you like me to remove github.com/remydt?

**Comment by remyduthu** [comment]
Yes please, remove the old github.com/remydt repository. Thanks!

**Comment by jba** [comment]
Done. https://pkg.go.dev/github.com/remyduthu/faces now returns a 404.
