### ISSUE TITLE
json.Marshal empty map[int64][]int64 got invalid result [123, 125]

### ISSUE THREAD

**Issue by echoface** [golang/go#46622]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.15.6

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/admin/huan/go_playground/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nl/rrdwh9nj1qz2r0_57hrt4fjc0000gp/T/go-bu
ild328730003=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```go
package main

import (
  "encoding/json"
  "fmt"
)
func main() {
  x := make(map[int64][]int64)
  c, e := json.Marshal(x)
  fmt.Println(c, e)
}
```

### What did you expect to see?
```json
{}
```

### What did you see instead?
```json
[123, 125]
```

**Comment by dsnet** [comment]
I believe this is working as intended. It's printing `c` as a Go slice of uints. If you do:
```go
fmt.Println(string(c), e)
```
then it prints as expected:
```
{} <nil>
```

**Comment by echoface** [comment]
omg, sorry for this. thanks
