### ISSUE TITLE
[dev.fuzz] testing: f.Cleanup called before fuzzing is done.

### ISSUE THREAD

**Issue by klauspost** [golang/go#46632]
### What version of Go are you using (`go version`)?

<pre>
λ gotip version
go version devel go1.17-5542c10fbf Fri Jun 4 03:07:33 2021 +0000 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
λ gotip env                                                                                                                                 
set GO111MODULE=                                                                                                                            
set GOARCH=amd64                                                                                                                            
set GOBIN=                                                                                                                                  
set GOCACHE=d:\temp\gocache                                                                                                                 
set GOENV=C:\Users\klaus\AppData\Roaming\go\env                                                                                             
set GOEXE=.exe                                                                                                                              
set GOFLAGS=                                                                                                                                
set GOHOSTARCH=amd64                                                                                                                        
set GOHOSTOS=windows                                                                                                                        
set GOINSECURE=                                                                                                                             
set GOMODCACHE=e:\gopath\pkg\mod                                                                                                            
set GONOPROXY=                                                                                                                              
set GONOSUMDB=                                                                                                                              
set GOOS=windows                                                                                                                            
set GOPATH=e:\gopath                                                                                                                        
set GOPRIVATE=                                                                                                                              
set GOPROXY=https://goproxy.io                                                                                                              
set GOROOT=C:\Users\klaus\sdk\gotip                                                                                                         
set GOSUMDB=sum.golang.org                                                                                                                  
set GOTMPDIR=                                                                                                                               
set GOTOOLDIR=C:\Users\klaus\sdk\gotip\pkg\tool\windows_amd64                                                                               
set GOVCS=                                                                                                                                  
set GOVERSION=devel go1.17-5542c10fbf Fri Jun 4 03:07:33 2021 +0000                                                                         
set GCCGO=gccgo                                                                                                                             
set AR=ar                                                                                                                                   
set CC=gcc                                                                                                                                  
set CXX=g++                                                                                                                                 
set CGO_ENABLED=1                                                                                                                           
set GOMOD=NUL                                                                                                                               
set CGO_CFLAGS=-g -O2                                                                                                                       
set CGO_CPPFLAGS=                                                                                                                           
set CGO_CXXFLAGS=-g -O2                                                                                                                     
set CGO_FFLAGS=-g -O2                                                                                                                       
set CGO_LDFLAGS=-g -O2                                                                                                                      
set PKG_CONFIG=pkg-config                                                                                                                   
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=d:\temp\wintemp\go-build102784969=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Run fuzzer:

```Go
func FuzzCleanup(f *testing.F) {
	var mu sync.Mutex
	var cleaned bool
	f.Cleanup(func() {
		mu.Lock()
		cleaned = true
		mu.Unlock()
	})
	f.Add([]byte("abc"))
	f.Fuzz(func(t *testing.T, data []byte) {
		time.Sleep(time.Second)
		mu.Lock()
		defer mu.Unlock()
		if cleaned {
			panic("Cleanup called before fuzzing finished.")
		}
	})
}
```

### What did you expect to see?

`f.Cleanup()`  is called when all fuzzers have finished, giving no output.

I think this is a reasonable expectation. Otherwise the usefulness is pretty reduced of `f.Cleanup`, or at least annoying to use, having to add a `sync.Waitgroup`.

### What did you see instead?

Output: https://gist.github.com/klauspost/fcbfa313d9dfab5b927fb7b80ad75775

**Comment by jayconrod** [comment]
This looks like a bug. I couldn't reproduce it at all on macOS, but I think I know why it's happening.

There are a couple places in `internal/fuzz` where we read from pipes. We don't want those reads to block after the context is cancelled (which happens after a timeout or after the user presses ^C). So the actual read is done in a goroutine, and the parent function returns when `ctx.Done()` is closed or the goroutine sends to a chan, indicating it's finished.

In one of these places, we call the fuzz function after the read completes successfully. If the context is cancelled while the fuzz function is running, we might start cleaning up while the fuzz function continues to run.
