### ISSUE TITLE
cmd/go: hangs in "found a crash, minimizing..."

### ISSUE THREAD

**Issue by klauspost** [golang/go#46634]
### What version of Go are you using (`go version`)?

<pre>
λ gotip version
go version devel go1.17-5542c10fbf Fri Jun 4 03:07:33 2021 +0000 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
λ gotip env                                                                                                                                  
set GO111MODULE=                                                                                                                             
set GOARCH=amd64                                                                                                                             
set GOBIN=                                                                                                                                   
set GOCACHE=d:\temp\gocache                                                                                                                  
set GOENV=C:\Users\klaus\AppData\Roaming\go\env                                                                                              
set GOEXE=.exe                                                                                                                               
set GOFLAGS=                                                                                                                                 
set GOHOSTARCH=amd64                                                                                                                         
set GOHOSTOS=windows                                                                                                                         
set GOINSECURE=                                                                                                                              
set GOMODCACHE=e:\gopath\pkg\mod                                                                                                             
set GONOPROXY=                                                                                                                               
set GONOSUMDB=                                                                                                                               
set GOOS=windows                                                                                                                             
set GOPATH=e:\gopath                                                                                                                         
set GOPRIVATE=                                                                                                                               
set GOPROXY=https://goproxy.io                                                                                                               
set GOROOT=C:\Users\klaus\sdk\gotip                                                                                                          
set GOSUMDB=sum.golang.org                                                                                                                   
set GOTMPDIR=                                                                                                                                
set GOTOOLDIR=C:\Users\klaus\sdk\gotip\pkg\tool\windows_amd64                                                                                
set GOVCS=                                                                                                                                   
set GOVERSION=devel go1.17-5542c10fbf Fri Jun 4 03:07:33 2021 +0000                                                                          
set GCCGO=gccgo                                                                                                                              
set AR=ar                                                                                                                                    
set CC=gcc                                                                                                                                   
set CXX=g++                                                                                                                                  
set CGO_ENABLED=1                                                                                                                            
set GOMOD=NUL                                                                                                                                
set CGO_CFLAGS=-g -O2                                                                                                                        
set CGO_CPPFLAGS=                                                                                                                            
set CGO_CXXFLAGS=-g -O2                                                                                                                      
set CGO_FFLAGS=-g -O2                                                                                                                        
set CGO_LDFLAGS=-g -O2                                                                                                                       
set PKG_CONFIG=pkg-config                                                                                                                    
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=d:\temp\wintemp\go-build1674875180=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

Ran a fuzz test, that ended up eating up all memory, causing OOMs to happen. This is Windows, so applications just crash and aren't killed by the OS.

Likely one or more of the workers crashed.

### What did you expect to see?

The controller printed `found a crash, minimizing...`, but never progressed from there.

Left it for about 15 minutes before I killed it.

### What did you see instead?

Fuzzer not getting stuck.

**Comment by rolandshoemaker** [comment]
This is a complicated problem, since Go doesn't provide any real way to deal with GC backpressure (see #29696 and the associated issues for background). Unless the worker process actually dies, killing the pipe used for RPC communication, the worker/coordinator has no way of knowing that there is a memory problem.

A simple-ish solution would be to just add a timeout to some/all of the RPC calls, so we can just bail out if the worker is taking longer than expected (and we assume it is dead). One question is, if the RPC times out, do we consider that a crash? (i.e. if a fuzz call times out, we copy the input and consider that a crasher).

Once we allow for continuous fuzzing (continuing when a crasher is find, rather than immediately exiting), we would need a way of marking a worker process dead, and ideally restarting it so we don't slowly run out of workers.

**Comment by katiehockman** [comment]
This is likely going to be a release blocker for Go 1.18.

**Comment by katiehockman** [comment]
I'm going to go ahead and close this. Please file a new issue if you experience this issue again.
