### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by zvischutz** [golang/go#46649]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>
1.16
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Really ? On your tutorials from all the example in the world you picked "Hail"?? 
https://golang.org/doc/tutorial/random-greeting

**Comment by seankhliao** [comment]
It is a valid greeting
https://en.wikipedia.org/wiki/Hail_fellow_well_met
