### ISSUE TITLE
x/pkgsite: purge all versions of https://pkg.go.dev/github.com/blocky/adlr

### ISSUE THREAD

**Issue by ianhecker** [golang/go#46640]
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/blocky/adlr
 
### What is your user agent?
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0  
 
### Screenshot
 
![Screenshot from 2021-06-07 15-30-02](https://user-images.githubusercontent.com/18134545/121090092-479dfe80-c7a5-11eb-930d-32581fad6fe2.png)
 
 ### What did you do?
 Because I am new to semver, i tagged and released v1.0.0 immediately (and incorrectly) for my github repo. 
Thinking I could correct the issue, I relabled and released tags v0.0.0 (which is what v1.0.0 should have been tagged as) through v1.3.0-alpha.
 
### What did you expect to see?
Since I deleted the v1.0.0 tag from github, (I do not want that tag anymore) I expected godocs to auto delete the documentation for v1.0.0 on https://pkg.go.dev/github.com/blocky/adlr
 
### What did you see instead?
I see versions of code correctly loaded for https://pkg.go.dev/github.com/blocky/adlr (v0.0.0, v1.0.0-alpha, v1.0.1-alpha, v1.0.2-alpha, v1.1.0-alpha, v1.2.0-alpha, and v1.3.0-alpha) while v1.0.0 still exists on https://pkg.go.dev/github.com/blocky/adlr and points to the older and original commit i tagged it as. 

I know it is expressly stated that you cannot remove one specific version, https://go.dev/about/#removing-a-package, from godocs, but could you purge all the versions for me, and I manually reload them? (in hopes that v1.0.0 is deleted?)

**Comment by jamalc** [comment]
Hi @ianhecker, you can retract accidentally published module versions using the [retract directive](https://golang.org/ref/mod#go-mod-file-retract) in your go.mod file.
