### ISSUE TITLE
x/tools/gopls: auto-generate API diff for releases

### ISSUE THREAD

**Issue by findleyr** [golang/go#46652]
From our team meeting: gopls auto-generates documentation for both its `workspace/executeCommand` API and its settings.

We should use this metadata to generate an API diff to attach to our releases, similar to how `cmd/api` works in the Go repo.

This may have helped in golang/vscode-go#1549

CC @hyangah @stamblerre

**Comment by findleyr** [comment]
This is probably as simple as capturing `internal/lsp/source/api_json.go` for each release. We can check it in, similar Go's `api/` directory.

This could also be used to generate 'added in gopls v0.7.0' commentary in our documentation.

**Comment by danishprakash** [comment]
I'd like to try this out @findleyr, let me know if that's okay.

**Comment by findleyr** [comment]
@danishprakash I believe @stamblerre already has an in-progress CL doing this.
