### ISSUE TITLE
runtime: deeply nested struct initialized with non-zero values

### ISSUE THREAD

**Issue by d-reinhold** [golang/go#46653]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, the issue is reproducible on the go playground (1.16.5).

### What did you do?
[This program](https://play.golang.org/p/q8O-h_iR_M2) instantiates a deeply nested struct by accessing an empty map.

### What did you expect to see?
Per the [go spec](https://golang.org/ref/spec#Index_expressions), this access should return a zero valued instance of the struct type.

### What did you see instead?
The ```string``` fields five levels deep in the struct are initialized with values of enormous lengths:

![Screen Shot 2021-06-08 at 12 26 02 PM](https://user-images.githubusercontent.com/815285/121248940-dd469600-c858-11eb-92c5-dbb8a9a77450.png)
The program does not crash.

A [slightly different version](https://play.golang.org/p/q37FEcogXOl) of this program forces the runtime stack to expand after initializing the corrupt struct, which causes the program to crash (this "bad pointer in frame" crash occurred in a production application, which motivated this investigation):

![Screen Shot 2021-06-08 at 12 30 38 PM](https://user-images.githubusercontent.com/815285/121249655-ade45900-c859-11eb-9ab0-7cfdbef76dae.png)

Slightly changing the depth/breadth of the nested struct can cause the issue to disappear, or can cause other, stranger behaviors:

In the context of my application, I have also seen the ```string``` fields be initialized with real string values from somewhere else in the application's memory:

![Screen Shot 2021-06-08 at 12 33 08 PM](https://user-images.githubusercontent.com/815285/121250004-16333a80-c85a-11eb-81f4-0529b5529231.png)

At other times, the application has consumed all system memory attempting to print the struct:
<img width="725" alt="Screen Shot 2021-06-08 at 1 07 11 PM" src="https://user-images.githubusercontent.com/815285/121250591-c012c700-c85a-11eb-9c32-96c2900b07b9.png">

**Comment by seankhliao** [comment]
@aclements @randall77 @mknyszek @prattmic

**Comment by thanm** [comment]
This looks like a linker / objwriter issue.

Building crash.go with "-S", I see:

```
...
go.map.zero SRODATA dupok size=4096
...
```

however when I inspect the binary, the map.zero symbol has a smaller size:

```
objdump -t main | fgrep map.zero
00000000004dfd00 g     O .rodata	0000000000000420 go.map.zero
```

I think what's happening here is that because the symbol is marked as a regular DUPOK symbol as opposed to having hashed content, there are multiple go.map.zero symbols at link time, and we wind up picking a smaller one.

There is actually code in the linker to detect this problem (under debug option -strictdups) but the code written to check data payload length and not symbol size (in this case there is no payload since it's essentially a BSS symbol). Bummer.

I'll work on a fix.

**Comment by thanm** [comment]
@gopherbot please consider this for backport to 1.15 and 1.16

**Comment by thanm** [comment]
@d-reinhold thank you for reporting this bug.  I have a tentative fix. It looks like this bug is also present in 1.15 and 1.16, so I will consult with the release team regarding back-porting the fix.

**Comment by d-reinhold** [comment]
@thanm Thanks for the quick fix! Looks like it's working against my test-case on master. Those backports will be appreciated as well!
