### ISSUE TITLE
x/tools/gopls: Warning in VS code: Error loading workspace

### ISSUE THREAD

**Issue by cvq** [golang/go#46664]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.16.5
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details>windows, amd64<summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre>windows, amd64</details>

### What did you do?

go env -w GO111MODULE=auto
install lidrary: go get github.com/AllenDang/giu@master

### What did you see instead?
VS Code Warning: Error loading workspace: You are outside of a module and outside of $GOPATH/src. If you are using modules, please open your editor to a directory in your module. If you believe this warning is incorrect, please file an issue: https://github.com/golang/go/issues/new.

**Comment by seankhliao** [comment]
which directory did you open vs code in?

**Comment by cvq** [comment]
it is my app directory like: "E:\MyProjects\GuiApp

**Comment by findleyr** [comment]
Does that directory have a go.mod file? Can you build your app?

**Comment by cvq** [comment]
There is no "go.mod". I can build my app using "go build".

**Comment by findleyr** [comment]
How exactly are you running `go build`? `go build foo.go` will still work without a module, but gopls does not have good support for single-file mode.

In any case, the correct solution to your problem is probably to create a module. See `go help modules` for more information on how to do this.

**Comment by keides2** [comment]
I also have the same go version go1.16.5 and the same error.
![image](https://user-images.githubusercontent.com/18452832/121654136-60295400-cad8-11eb-8492-3cd0ffa651f0.png)

**Comment by keides2** [comment]
The error disappeared by following the steps below.
Open the $GOPATH/src folder once and recompile.
Once again, when I open the workspace, the workspace settings start, so wait until it's done.
Then the error disappeared.
The language has changed from Japanese to English, but I have reset it again.

**Comment by findleyr** [comment]
Closing as it doesn't appear there is anything going on here other than what is described in the error message. In order for gopls to work, you must open either a subdirectory of GOPATH/src, or a directory inside a module.
