### ISSUE TITLE
x/pkgsite: XSS possible (?) by injecting HTML into Example output

### ISSUE THREAD

**Issue by markuswustenberg** [golang/go#46661]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/maragudk/gomponents#Attr
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15
  
### Screenshot
 
<img width="981" alt="image" src="https://user-images.githubusercontent.com/141763/121308416-539ed300-c901-11eb-8861-92909c59f16a.png">

<img width="978" alt="image" src="https://user-images.githubusercontent.com/141763/121308458-5e596800-c901-11eb-8d76-75470b31b0e4.png">
 
### What did you do?

I'm building a library to render HTML. I have some examples in the test code, that render a string like `<input required>` (in the screenshot). 
 
### What did you expect to see?
 
I expected the example output to be `<input required>` (as a string). It is on the first screenshot, but press the Run button, and there is no string.
 
### What did you see instead?

Instead, there's an HTML `input` field, which means that the output string isn't being properly escaped.

**Comment by markuswustenberg** [comment]
@jamalc cool with the quick turnaround time!

**Comment by jamalc** [comment]
@markuswustenberg, thank you for reporting!

**Comment by markuswustenberg** [comment]
@jamalc, has this not been deployed yet? I'm still seeing the issue live on the site.

**Comment by markuswustenberg** [comment]
Works perfectly. 😎
