### ISSUE TITLE
x/term: git-bash.exe reports stdout is not a terminal. 

### ISSUE THREAD

**Issue by gabyx** [golang/go#46681]
### What version of Go are you using (`go version`)?
1.16

### Does this issue reproduce with the latest release?
yes (v0.0.0-20210503060354-a79de5458b56)

### What operating system and processor architecture are you using (`go env`)?
Windows 10

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\gabriel.nuetzi\AppData\Local\go-build
set GOENV=C:\Users\gabriel.nuetzi\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\gabriel.nuetzi\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\gabriel.nuetzi\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=F:\Repositories\githooks\githooks\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\GABRIE~1.NUE\AppData\Local\Temp\go-build1896432741=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

```go
package main

import (
	"fmt"
	"os"

	"golang.org/x/term"
)


func main() {
	fmt.Print(term.IsTerminal(int(os.Stdout.Fd())))
}
```

1. Open "git-bash.exe" (from git-for-windows) -> `go run main.go`
2. Open VS Code -> Open Integrated Terminal (bash.exe from git-for-windows) -> `go run main.go`

### What did you expect to see?
1. **Output: "true"**
2. **Output: "true"**

### What did you see instead?
1. **Output: "false"** (wrong?)
2.  **Output: "true"** (correct)

@mattn: The package `isatty` has the exact same issue altough working differently:
`fmt.Print(isatty.IsTerminal(os.Stdout.Fd()))`

**Comment by gabyx** [comment]
I am most interested why this bahvior is happening...

**Comment by 89z** [comment]
I cant repro this. Using this program:

~~~
package main

import (
   "fmt"
   "syscall"
)

func main() {
   _, err := syscall.Open("CONIN$", syscall.O_RDWR, 0)
   fmt.Println(err)
}
~~~

With just PowerShell I get this:

~~~
PS C:\> .\open.exe
<nil>
~~~

Then with MSYS2 Bash, I get this:

~~~
PS C:\> bash.exe
bash-5.1$ ./open.exe
<nil>
~~~

Personally if Windows is going to be your "daily driver", I would recommend not using `git-bash.exe`, or WSL. Go is not like C, where you have all these supporting Makefiles and Shell scripts in the build process. For the most part, you just write Go code, then use the Go compiler to compile it. So I have discovered that Bash doesnt really need to be involved in the process, and I just use PowerShell now. If you really need Bash for some other reason, you can install the MSYS2 Bash package:

https://packages.msys2.org/package/bash

**Comment by 89z** [comment]
That isnt even a valid program:

~~~
imported and not used: "syscall"
imported and not used: "github.com/mattn/go-isatty" as isatty
~~~

and even if you fix it:

~~~go
package main

import (
   "golang.org/x/term"
   "os"
)

func main() {
   b := term.IsTerminal(int(os.Stdout.Fd()))
   println(b)
}
~~~

It doesnt produce an error with PowerShell:

~~~
PS C:\> go run main.go
true
~~~

and it doesnt produce an error with MSYS2 Bash:

~~~
PS C:\> bash
bash-5.1$ go run main.go
true
~~~

I would recommend just using PowerShell if you are on Windows, or if you must use Bash, then MSYS2 Bash:

https://packages.msys2.org/package/bash

**Comment by gabyx** [comment]
git-bash.exe as far as I know is a MSYS2 Bash.

**Comment by gabyx** [comment]
Since most Windows user use this bash, thats why I report it. Powershell is not an option, its a shitshow...

**Comment by 89z** [comment]
> `git-bash.exe` as far as I know is a MSYS2 Bash.

Nope. MSYS2 Bash is `bash.exe` or `sh.exe`. Anything with a different name is something else, so easy to tell.

> Since most Windows user use this bash, thats why I report it. Powershell is not an option, its a shitshow...

As an expert in Bash [1], I can say with confidence, that on Windows, PowerShell is the better option. Unless you have tried PowerShell 6 [2] or higher, I dont think youre making a valid claim here.

1. https://stackoverflow.com/help/badges/863/bash?userid=1002260
2. https://github.com/PowerShell/PowerShell

**Comment by seankhliao** [comment]
I believe this has the same cause as https://github.com/golang/go/issues/11914#issuecomment-613715787 (which is to say there's nothing we can do)

**Comment by cherrymui** [comment]
As this is Go issue tracker, it is probably not relevant to discuss the quality of various shells. Please bear in mind our [Gopher values](https://golang.org/conduct#values) and keep the feedback constructive. Thanks.

**Comment by 89z** [comment]
> As this is Go issue tracker, it is probably not relevant to discuss the quality of various shells. Please bear in mind our [Gopher values](https://golang.org/conduct#values) and keep the feedback constructive. Thanks.

As alluded to by @seankhliao (and by Ian in the other issue), this is a shell issue, not a Go issue.

So unless OP can strongly demonstrate that this in fact a Go issue, I think this should be closed.

**Comment by gabyx** [comment]
Its a shell issue, I close this.
