### ISSUE TITLE
x/tools/gopls: unsupported version 0 of Verneed record

### ISSUE THREAD

**Issue by bingoIsCoder** [golang/go#46680]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.3 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xx/.cache/go-build"
GOENV="/home/xx/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE="git.xxx.com"
GOMODCACHE="/home/xxx/go/pkg/mod"
GONOPROXY="git.xxx.com,xx.com"
GONOSUMDB="git.xxx.com,xx.com"
GOOS="linux"
GOPATH="/home/xxx/go:/mnt/e/go"
GOPRIVATE="git.xxx.com,xxx.com"
GOPROXY="https://goproxy.io"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build685780456=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
gopls can not work after I updating.
run gopls:

gopls: error while loading shared libraries: gopls: unsupported version 0 of Verneed record

**Comment by findleyr** [comment]
Hi, how did you install and update gopls? Did you use `go get`, or something else? If you installed from the command line, which command exactly did you execute?
