### ISSUE TITLE
x/tools/gopls: client not receiving messages from server

### ISSUE THREAD

**Issue by stamblerre** [golang/go#46694]
First reported on Slack.

(From 2 different runs)
Client side: https://gophers.slack.com/files/T029RQSE6/F024HF0KRQE?origin_team=T029RQSE6.
Server side: https://gophers.slack.com/files/T029RQSE6/F024HECSV7Y?origin_team=T029RQSE6.

The next step in investigation is to log jsonrpc2 bytes to files to understand what is actually happening over the wire.

**Comment by jvoll** [comment]
After following the instructions posted: https://gophers.slack.com/archives/C2B4L99RS/p1623424302142500

I have the following logs:
[gopls-server.txt](https://github.com/golang/go/files/6640161/gopls-server.txt)
[gopls.txt](https://github.com/golang/go/files/6640162/gopls.txt)
[log-extension-host.txt](https://github.com/golang/go/files/6640163/log-extension-host.txt)

None of the other log outputs in VS code seem to have anything interesting, most are empty or just a few lines.

This is the entire project on one screen:
![image](https://user-images.githubusercontent.com/1031170/121728368-073ec900-caa2-11eb-95ce-3c9ecbc4c4db.png)

I opened VS Code from my terminal: `cd test-project; code .`

**Comment by stamblerre** [comment]
From those instructions--do you have the `trace.log` file that should be generated in your test project?

**Comment by stamblerre** [comment]
And one more thing to try after this, is to delete the wrapper script and the `"go.alternateTools"` setting and instead add the following to your settings:


```json5
"go.languageServerFlags": [
	"-remote=auto",
	"-rpc.trace",
]
```

If `gopls` starts working, then the issue is that we are writing something that doesn't fit the protocol to stdout.

**Comment by jvoll** [comment]
Ah, I had forgotten to make the script an executable and therefore wasn't getting `trace.log`. I've fixed that now, here's the file. You can ignore the "CANCEL"'s in there (or just know that it means that the Go context got cancelled!). At one point recently we were debugging something and added a `fmt.Println("CANCEL") on context cancel and didn't manage to clean it up (it's buried somewhere deep and it wasn't worth tracking down).
[trace.log](https://github.com/golang/go/files/6640857/trace.log)

I also tried adding the '"-remote=auto",' in there and it seems to somewhat alleviate the problem? It's a bit strange, I can still reproduce the loading packages sometimes but not 100% of the time. It seems to help most on the smaller test projects than on the big project (I haven't got the big project working at all yet) but my data points are fairly limited and it's hard to say for sure.

**Comment by findleyr** [comment]
>  At one point recently we were debugging something and added a `fmt.Println("CANCEL")

That's the problem. Writing CANCEL to stdout breaks the jsonrpc2 stream.

**Comment by findleyr** [comment]
> I also tried adding the '"-remote=auto",' in there and it seems to somewhat alleviate the problem? It's a bit strange, I can still reproduce the loading packages sometimes but not 100% of the time.

I'm guessing that even when operating as a thin forwarder, gopls can hit some context cancellations.

Whelp, mystery solved.  Please re-build gopls with a clean GOROOT.

**Comment by jvoll** [comment]
Oh wow! Thank you so much for your help, that indeed fixed the problem!

I cleaned up cached modules (`go clean --modcache`) and some other stuff and rebuilt `gopls` and some other go packages on my system and that fixed things up.

Sorry for the weird issue and thanks for your time @stamblerre and @findleyr!
