### ISSUE TITLE
x/pkgsite: page is outdated and should be removed

### ISSUE THREAD

**Issue by leonsteinhaeuser** [golang/go#46690]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/leonsteinhaeuser/go-routemod
 
 
### What is your user agent?
 

 
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
 
### Screenshot

Latest:
![go-routemod](https://user-images.githubusercontent.com/42437185/121591172-759b7100-ca39-11eb-82fd-765d42e88a29.PNG)

@main: 
![go-routemod@main](https://user-images.githubusercontent.com/42437185/121591044-54d31b80-ca39-11eb-92b6-21ac818ce437.PNG)

 
 
### What did you do?
 

 
I renamed the package to *procroute*. Since the renamed package was redirected to *go-routemod* all the time, I decided to delete the Github repository and create a new repository with the correct name (procroute). Unfortunately, this did not help either. While I'm not entirely sure, I believe this also causes the following problem:

```
go get github.com/leonsteinhaeuser/procroute

go get: github.com/leonsteinhaeuser/procroute@none updating to
        github.com/leonsteinhaeuser/procroute@v1.0.0: parsing go.mod:
        module declares its path as: github.com/leonsteinhaeuser/go-routemod
                but was required as: github.com/leonsteinhaeuser/procroute
```
  
### What did you expect to see?
 
I expect to see nothing when I open the page: https://pkg.go.dev/github.com/leonsteinhaeuser/go-routemod

I also expect `go get github.com/leonsteinhaeuser/procroute` to work without redirection or other magic. 

### What did you see instead?

I can see an old, outdated, broken page. This page should no longer exist (after deletion of the repository).

**Comment by jamalc** [comment]
I've removed the from the site.
