### ISSUE TITLE
x/build: windows-*-longtest builders have no Git binary in %PATH%

### ISSUE THREAD

**Issue by bcmills** [golang/go#46693]
I got a shiny new Windows laptop for personal use, and out of curiosity I decided to install the Go toolchain and run `go test cmd/go` on it.

Unfortunately, that immediately uncovered two existing test failures (#46692 and #46691) that had not shown up in the Go project's builders — even the `longtest` builders.

The common, relevant factor between the two failing tests is this line:
```
[!exec:git] skip
```

That seems to imply that either the Go `windows-amd64-longtest` builder does not have a `git` binary installed, or that `git` binary is omitted from `%PATH%` when the `cmd/go` tests are run.

This seems like a pretty substantial (and unexpected) gap in test coverage, but hopefully it is pretty easy to fix. However, it may reveal issues that need to be fixed in previous releases. (For a start, we may need to backport the `GCM_INTERACTIVE` portion of [CL 300157](https://golang.org/cl/300157).)

CC @golang/release

**Comment by bcmills** [comment]
Per #46693, I think we should configure `git` on the Windows builders with `core.longpaths` set to `true`.

**Comment by bcmills** [comment]
Per #49841, we should also install any other VCS tools supported by the intersection of `go get` and Windows — at least Mercurial (`hg`).

**Comment by heschi** [comment]
LUCI bots have Git installed.
