### ISSUE TITLE
cmd/internal/moddeps: TestAllDependencies requires a writable GOPATH directory

### ISSUE THREAD

**Issue by tamird** [golang/go#46695]
```
--- FAIL: TestAllDependencies (14.42s)
    --- FAIL: TestAllDependencies/goroot(quick) (0.02s)
        moddeps_test.go:77: /opt/s/w/ir/x/w/go/bin/go list -mod=mod -m all: exit status 1
            go: could not create module cache: mkdir /nonexist-gopath: read-only file system
FAIL
FAIL	cmd/internal/moddeps	14.547s
```

Seen on go1.17beta1 in https://fxrev.dev/541662. Related to #46269. cc @bcmills

**Comment by bcmills** [comment]
This needs more logging. It is checking a module in `GOROOT` that is not supposed to have any dependencies, but trying to create a module cache (which implies that the module _does_ have dependencies, I think?).

**Comment by bcmills** [comment]
I suspect that this is a bug in `cmd/go`, in the `cmd/go/internal/modfetch.SideLock` function:
https://github.com/golang/go/blob/51a47b7ff2934b6c28ece51f6a37dc30bd37a02d/src/cmd/go/internal/modfetch/cache.go#L154-L156

There are places where we invoke `modfetch.SideLock` as a best-effort call, and those places should not fail if the module cache can't be created at all. (Moreover, if we're using `-mod=readonly` and the module cache directory doesn't exist, we probably shouldn't try to create it.)

**Comment by bcmills** [comment]
(But also, the test should be passing `-mod=readonly` instead of `-mod=mod`.)
