### ISSUE TITLE
syscall: in TestStdioAreInheritable, powershell on arm64/arm cannot load arm64/arm binaries because it is an intel process

### ISSUE THREAD

**Issue by zx2c4** [golang/go#46701]
ARM builds of Windows are still shipping an Intel powershell, which means we can't test arm shared libraries using powershell as a loader. This bug is to track that, if it ever changes, so we can remove the test skippage.

**Comment by cherrymui** [comment]
Is it possible to rewrite the test to not depend on powershell?

**Comment by alexbrainman** [comment]
> Is it possible to rewrite the test to not depend on powershell?

When I introduced TestStdioAreInheritable in CL 316269, I just adopted repro provided at https://github.com/golang/go/issues/44876#issue-825396212. After successfully built TestStdioAreInheritable, I tried to do something similar in C (compiled with GCC). But I could not do it.

I don't remember how much effort I put into conversion of TestStdioAreInheritable into C, but that was significant enough. I don't plan to work on this now. I also don't have any notes of what I tried.

Alex

**Comment by zx2c4** [comment]
> I don't remember how much effort I put into conversion of TestStdioAreInheritable into C, but that was significant enough. I don't plan to work on this now. I also don't have any notes of what I tried.

Should we just remove the test? Is it particularly useful?

**Comment by alexbrainman** [comment]
> Should we just remove the test?

Why? What is the benefit?

> Is it particularly useful?

The test verifies that #44876 stays fixed. I think it is useful.

Alex
