### ISSUE TITLE
doc/go1.17: change from issue 25192 is not mentioned in the go1.17 release notes

### ISSUE THREAD

**Issue by yansal** [golang/go#46706]
This program prints a different output with go1.16.5 and go1.17beta1
```go
package main

import (
	"fmt"
	"net/url"
)

func main() {
	u1, _ := url.Parse("http://host/path?q1=v1&q2=v2")
	fmt.Println(u1.Query())
	u2, _ := url.Parse("http://host/path?q1=v1;q2=v2")
	fmt.Println(u2.Query())
}
```
See https://github.com/golang/go/issues/25192 for the details.

There is no mention of this change in the go1.17 release notes (https://tip.golang.org/doc/go1.17), although it may break existing programs.

**Comment by bcmills** [comment]
@golang/security, someone want to add a release note?

**Comment by FiloSottile** [comment]
I have a draft almost ready, will mail it today.

**Comment by toothrot** [comment]
@FiloSottile Anything else to do here or can this be closed?

**Comment by FiloSottile** [comment]
All done!
