### ISSUE TITLE
x/pkgsite:https://pkg.go.dev/github.com/coopersong/irtc

### ISSUE THREAD

**Issue by coopersong** [golang/go#46713]
### What is the URL of the page with the issue?
 x/pkgsite:https://pkg.go.dev/github.com/coopersong/irtc
 
 
### What did you do?
 I have removed this package before because of an important bug. But now I fixed it. So I want to readd this package(github.com/coopersong/irtc) to pkg.go.dev.

 
 
 
### What did you expect to see?
 I want to readd this package(github.com/coopersong/irtc) to pkg.go.dev.
When I type https://pkg.go.dev/github.com/coopersong/irtc, I get the package information.

**Comment by julieqiu** [comment]
Fixed.
