### ISSUE TITLE
go build command-line-arguments: copying /tmp/go-build1657217666/b001/exe/a.out: open main: permission denied

### ISSUE THREAD

**Issue by kannanjmc** [golang/go#46729]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.16
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
17:43:03  gobuild       | GO111MODULE=""
17:43:03  gobuild       | GOARCH="amd64"
17:43:03  gobuild       | GOBIN=""
17:43:03  gobuild       | GOCACHE="/app/.cache/go-build"
17:43:03  gobuild       | GOENV="/app/.config/go/env"
17:43:03  gobuild       | GOEXE=""
17:43:03  gobuild       | GOFLAGS="-mod=vendor"
17:43:03  gobuild       | GOHOSTARCH="amd64"
17:43:03  gobuild       | GOHOSTOS="linux"
17:43:03  gobuild       | GOINSECURE=""
17:43:03  gobuild       | GOMODCACHE="/app/go/pkg/mod"
17:43:03  gobuild       | GONOPROXY=""
17:43:03  gobuild       | GONOSUMDB=""
17:43:03  gobuild       | GOOS="linux"
17:43:03  gobuild       | GOPATH="/app/go"
17:43:03  gobuild       | GOPRIVATE=""
17:43:03  gobuild       | GOPROXY="https://proxy.golang.org,direct"
17:43:03  gobuild       | GOROOT="/usr/local/go"
17:43:03  gobuild       | GOSUMDB="sum.golang.org"
17:43:03  gobuild       | GOTMPDIR=""
17:43:03  gobuild       | GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
17:43:03  gobuild       | GOVCS=""
17:43:03  gobuild       | GOVERSION="go1.16.3"
17:43:03  gobuild       | GCCGO="gccgo"
17:43:03  gobuild       | AR="ar"
17:43:03  gobuild       | CC="gcc"
17:43:03  gobuild       | CXX="g++"
17:43:03  gobuild       | CGO_ENABLED="0"
17:43:03  gobuild       | GOMOD="/go/src/(project path)go.mod"
17:43:03  gobuild       | CGO_CFLAGS="-g -O2"
17:43:03  gobuild       | CGO_CPPFLAGS=""
17:43:03  gobuild       | CGO_CXXFLAGS="-g -O2"
17:43:03  gobuild       | CGO_FFLAGS="-g -O2"
17:43:03  gobuild       | CGO_LDFLAGS="-g -O2"
17:43:03  gobuild       | PKG_CONFIG="pkg-config"
17:43:03  gobuild       | GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build423889831=/tmp/go-build -gno-record-gcc-switches"
<pre>
$ go env

</pre></details>

### What did you do?
building go app in jenkins

### What did you expect to see?

docker compose should build the go docker build image
### What did you see instead?
error in copying

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
