### ISSUE TITLE
HOW-TO request: additional database drivers

### ISSUE THREAD

**Issue by stud0709** [golang/go#46739]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.8 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ydzh/.cache/go-build"
GOENV="/home/ydzh/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ydzh/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build245499071=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### HOW-TO request
Please provide HOW-TO for *non-gophers* on adding database drivers. 

I tried to figure out how it works, no luck:
- <code>git clone ...</code>
- modify sql.go adding e.g. <code>_ "github.com/godror/godror"		 // register the Oracle driver</code> to the import section
- <code>go build</code> from within the source folder (just to test before installing)
- <code>go get</code> all the stuff shown as missing
- still no luck with build: <br><pre># _/home/ydzh/Documents/git/temp/sql_exporter
./metric.go:88:28: cannot use mf.config.ValueType() (type "github.com/free/sql_exporter/vendor/github.com/prometheus/client_golang/prometheus".ValueType) as type "github.com/prometheus/client_golang/prometheus".ValueType in return argument
./metric.go:234:12: undefined: "github.com/prometheus/client_golang/prometheus".LabelPairSorter
./target.go:67:12: undefined: "github.com/prometheus/client_golang/prometheus".LabelPairSorter
</pre>

How can I get this right?

Regards,

stud0709

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
