### ISSUE TITLE
cmd/compile: missing/bad error for "s"+bool

### ISSUE THREAD

**Issue by rsc** [golang/go#46749]
```
% cat /tmp/x.go
package main

func main() {
	var b bool
	_ = "Hello, " + b
}
% go1.13 tool compile /tmp/x.go
/tmp/x.go:5:16: cannot convert "Hello, " (type untyped string) to type bool
/tmp/x.go:5:16: invalid operation: "Hello, " + b (mismatched types string and bool)
% go1.15 tool compile /tmp/x.go
/tmp/x.go:5:16: cannot use "Hello, " (type untyped string) as type bool
% 
```

The Go 1.15 output is what is still printed today. Having two errors was definitely a bit annoying, but the fix should have been to delete the first one, not the second. I got this in a larger program as part of a larger expression, like:

	for _, host := range validHosts {
		list = append(list, `blah blah`+host)
	}

The error was cannot use "blah blah" (type untyped string) as bool. 
I spent quite a while puzzling through the problem of why my string would need to be a bool. 
The answer is that validHosts is a map[string]bool so host is a bool.
If the error had reported string+bool, the problem would have been far more obvious.

We should restore the second error and probably drop the first.
I think we could drop the first by making the implicit conversion of strings
just return plain string if the suggestion is bool.
Then the invalid operation or whatever other error will happen will be reported with more context.

Would be nice to fix for Go 1.17 but not a release blocker.

/cc @griesemer @mdempsky

**Comment by griesemer** [comment]
Compiling this with `-G=3` (using types2 for type checking) produces:
```
$ go tool compile -G=3 x.go
x.go:5:6: cannot convert "Hello, " (untyped string constant) to bool
```
which seems pretty good. So this will certainly be fixed for Go 1.18. Haven't looked into the compiler's type checker yet. @mdempsky ?

**Comment by rsc** [comment]
The -G=3 output has the same problem as the current regular output. It should say instead:

    x.go:5:16: invalid operation: "Hello, " + b (mismatched types string and bool)

**Comment by cuonglm** [comment]
@rsc You want to make it specific to string+bool or general?

The "invalid operation" seems unclear to me, as the op "+" is defined for both string and bool.

**Comment by griesemer** [comment]
@cuonglm I would expect that such a change should work in general (e.g. for `"foo" + 1` we should get an error "mismatched types string and int").

**Comment by mdempsky** [comment]
> Having two errors was definitely a bit annoying, but the fix should have been to delete the first one, not the second. 

Ack, the second error there was more helpful. I don't think it was specifically removed. I refactored a lot of the untyped constant handling in typecheck a while back (I think in that time period) to behave more consistently, and in particular to avoid printing multiple errors.

> The "invalid operation" seems unclear to me, as the op "+" is defined for both string and bool.

The invalid operation is trying to add two mismatched types. (Also, "+" isn't applicable to bool, but the point still stands if it was int or something.)

I think this basically similar to when we made `&&` and `||` print better diagnostics for operands that are impossible to coerce to a common type. We should figure out how to generalize that to more operations.

**Comment by mdempsky** [comment]
Related: #41500

**Comment by cuonglm** [comment]
> The invalid operation is trying to add two mismatched types. (Also, "+" isn't applicable to bool, but the point still stands if it was int or something.)

Yeah, my bad. I mean the op can
be applicable for both operands.

**Comment by rsc** [comment]
CL 328050 looks great. Thanks so much!
