### ISSUE TITLE
reflect: slightly different error messages converting slice to array pointer

### ISSUE THREAD

**Issue by gazerro** [golang/go#46743]
With Go 1.17, the message of the runtime error that occurs when converting a slice to an array pointer differs slightly from the error returned by the `Convert` method of the `reflect` package

> runtime error: cannot convert slice with length 1 to **pointer to array** with length 2

> reflect: cannot convert slice with length 1 to **array pointer** with length 2

Usually the error messages returned by reflect are different from the runtime error messages, but in this case I don't know if it was supposed to be the same.

**Comment by mdempsky** [comment]
I think the runtime error there is more correct: it's a "pointer to (array with length 2)", whereas the reflect wording suggests the pointer has a length, which is nonsensical as pointers do not have a length.

(That said, I was #TeamPointerToArray during the spec wording CL, but #TeamArrayPointer won out.)
