### ISSUE TITLE
runtime/pprof: TestMorestack failures on darwin/arm64

### ISSUE THREAD

**Issue by bcmills** [golang/go#46755]
[2021-06-15T10:13:08-abc56fd/darwin-arm64-11_0-toothrot](https://build.golang.org/log/4a966497d752c4313d8212f5398bc424730e2783)
[2021-04-30T00:32:42-303b194/darwin-arm64-11_0-toothrot](https://build.golang.org/log/7f2bde14bd04f81f1d713aaee421bf6204fcb061)

See previously #44418 (CC @cherrymui).

**Comment by bcmills** [comment]
Marking as release-blocker for 1.17 because the tests are newly unskipped on Darwin as of [CL 292229](https://golang.org/cl/292229) (CC @golang/release).

If it isn't important that the tests pass on this platform for 1.17, it seems ok to unblock the release by adding a skip on this builder, although fixing the test would be better still.

**Comment by prattmic** [comment]
Perhaps we just need to increase the stack growth time even more than golang.org/cl/307730?

**Comment by cherrymui** [comment]
Yeah, probably. Changed copying size from 8<<16 to 8<<18, it seems to pass on my Apple M1 machine reliably with 1000 runs. I'll send a CL.
