### ISSUE TITLE
x/pkgsite:github.com/coopersong/irtc

### ISSUE THREAD

**Issue by coopersong** [golang/go#46756]
### What is the URL of the page with the issue?
 pkg.go.dev/github.com/coopersong/irtc
 
 
### What did you do?
 

 I post a  remove request before for this package(github.com/coopersong/irtc) because of a bug, but then I fixed it. However, my package has been removed.
 
 
### What did you expect to see?
 My package(github.com/coopersong/irtc) can be accessed through URL pkg.go.dev/github.com/coopersong/irtc

**Comment by julieqiu** [comment]
Duplicate of #46713
