### ISSUE TITLE
template/html

### ISSUE THREAD

**Issue by Fruchtgummi** [golang/go#46754]
go version go1.16.3 windows/amd64

I use the template/html package. If I set a variable into html, 

Example

```
  {{range $kk, $vv := .Users -}}
      {{if eq $vv.Id $performedBy}}
          {{$pSurname = $vv.ContactData.Surname}} {{$pName = $vv.ContactData.Name}}
      {{- end}}
  {{- end}}
```

Whenever I fill a variable in a range, it writes me an empty row.  What can I do to prevent this from happening again?

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
