### ISSUE TITLE
syscall: TestGroupCleanupUserNamespace test failure on Fedora

### ISSUE THREAD

**Issue by rabajaj0509** [golang/go#46752]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.15
</pre>

### Does this issue reproduce with the latest release?
I am not sure, but I think so.

### What operating system and processor architecture are you using (`go env`)?
I am using Fedora 31, x86 architecture: `fc31.x86_64`

### What did you do?
```
# cd src
# ./all.bash
```

### What did you expect to see?
PASS

### What did you see instead?
```
--- FAIL: TestGroupCleanupUserNamespace (0.07s)
    exec_linux_test.go:327: id command output: "uid=0(root) gid=0(root) groups=0(root),65534(nobody) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023", expected one of ["uid=0(root) gid=0(root) groups=0(root)" "uid=0(root) gid=0(root) groups=0(root),65534(nobody)" "uid=0(root) gid=0(root) groups=0(root),65534(nogroup)" "uid=0(root) gid=0(root) groups=0(root),65534" "uid=0(root) gid=0(root) groups=0(root),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody)" "uid=0(root) gid=0(root) groups=0(root) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023"]
FAIL
FAIL	syscall	5.514s
```

**Comment by rabajaj0509** [comment]
To fix this issue, i tried to add `"uid=0(root) gid=0(root) groups=0(root),65534(nobody) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023",` line to the `exec_linux_test.go` file

Now I am facing an error:
```
--- FAIL: TestStdlibLowercase (0.02s)
    deps_test.go:830: package "syscall/rabajaj/Backups" should not use upper-case path
    deps_test.go:830: package "syscall/rabajaj/Backups/2a70a0e80c6dc7f87a6c9c6546358f0a" should not use upper-case path
    deps_test.go:830: package "syscall/rabajaj/Backups/2a70a0e80c6dc7f87a6c9c6546358f0a/file" should not use upper-case path
    deps_test.go:830: package "syscall/rabajaj/Cache" should not use upper-case path
    deps_test.go:830: package "syscall/rabajaj/Cache/index-dir" should not use upper-case path
    deps_test.go:830: package "syscall/rabajaj/CachedData" should not use upper-case path

```

Can someone help me fix this and contribute?

**Comment by tklauser** [comment]
@rabajaj0509 It looks like there are untracked files/directory in your Go source directory. Try cleaning the repo, e.g. using `git clean -f -x -d` and try to run the tests again.

**Comment by rabajaj0509** [comment]
Awesome! thanks @tklauser. It works like a charm now. Let me raise a PR for this one.

**Comment by rabajaj0509** [comment]
@tklauser is it ok if I close this PR: https://github.com/golang/go/pull/46753 and open a new one? because this PR is created against the 1.15 branch instead of the master branch?

**Comment by rabajaj0509** [comment]
@tklauser I have changed the base branch in the PR itself. I need to fetch and rebase the PR with the master branch, I will do that once I can clone the master branch.

**Comment by tklauser** [comment]
@rabajaj0509 it's probably easiest to reset your PR branch to the `master` branch and then cherry-pick your commit on top.

**Comment by rabajaj0509** [comment]
@tklauser done. Thank you for your inputs :)

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport issues

This test failure happens when running minor releases on some systems.  The fix is tiny, so may as well backport to avoid unexpected test failures when people build those releases from source.
