### ISSUE TITLE
x/build: Corellium builders are down

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#46779]
* host-android-arm64-corellium-android: 0/0 (3 missing)
* host-ios-arm64-corellium-ios: 0/0 (3 missing)

I've had a SlowBot run waiting for 12h. https://farmer.golang.org/try?commit=7bb44b0a

/cc @golang/release

**Comment by dmitshur** [comment]
CC @eliasnaur. Are you able to take a look? Thanks.

**Comment by eliasnaur** [comment]
Rebooted them. Would someone on the Go team like to get access to the Corellium dashboard?

**Comment by dmitshur** [comment]
Thank you Elias. Unfortunately, we can't make use of the offer to get access to the dashboard at this time (also see https://github.com/golang/go/issues/41610#issuecomment-702940002).
