### ISSUE TITLE
x/build: new builder for cmd/compile's "unified IR" mode

### ISSUE THREAD

**Issue by mdempsky** [golang/go#46786]
I'd like to add a builder for testing the compiler's new "unified IR" mode. This has landed on dev.typeparams, and it took all of 1 commits for us to accidentally break it again.

Proposed build config (caveat: this is just copy/paste/tweaked based on some of the other compiler experiment configs; I don't feel strongly about any of these if other changes would be appropriate):

```
        addBuilder(BuildConfig{
                Name:     "linux-amd64-unified-ir",
                HostType: "host-linux-buster",
                Notes:    "builder with GO_GCFLAGS=-d=unified=1, see golang.org/issue/46786",
                buildsRepo: func(repo, branch, goBranch string) bool {
                        return repo == "go" && branch == "dev.typeparams"
                },
                env: []string{
                        "GO_DISABLE_OUTBOUND_NETWORK=1",
                        "GO_GCFLAGS=-d=unified=1",
                },
                GoDeps: []string{
                        "cf1ae5fc364eb7f2ee5203e4c5e30411c3cfe01f", // dev.typeparams commit that added -d=unified
                },
        })
```

Caveat: It's expected that the `go tool dist test test:0_1` step will fail with unified IR currently. (There's a list of tests that are known to fail with the new types2 type checker, but test/run.go doesn't know -d=unified enables this too. I will fix this shortly.)

**Comment by mdempsky** [comment]
I just tried `GO_GCFLAGS=-d=unified=1` and it exploded a lot harder in test/run.go than I was expecting. Maybe it would be more robust as a GOEXPERIMENT instead.

**Comment by dmitshur** [comment]
From looking at the CL, I understand this issue needs to be updated to mention TryBots (that is, pre-submit builders too, not just post-submit ones). If this will be helpful for development, adding the builder makes sense, so moving to NeedsFix.

@mdempsky Do you expect it'll be helpful to have the builder indefinitely, or is there a point at which it'll stop being needed (because sufficient coverage becomes provided elsewhere)? Or is it not possible to predict this time (that's fine; I just wanted to ask)?

**Comment by mdempsky** [comment]
@dmitshur Sorry, I saw @cagedmantis 's CR+2 before seeing your questions here.

**Comment by mdempsky** [comment]
> Do you expect it'll be helpful to have the builder indefinitely, or is there a point at which it'll stop being needed (because sufficient coverage becomes provided elsewhere)?

This builder will only be needed for as long as we have the unified experiment. I'm hoping to make that the default for Go 1.18 (and feel reasonably confident that will happen), but there's a chance it doesn't make it until Go 1.19. I expect we'll be able to remove the experiment again shortly after it's released and enabled as default.

> Or is it not possible to predict this time (that's fine; I just wanted to ask)?

I definitely don't see it living indefinitely. I think we'll need it for less than a year, and possibly much less than that depending on how generics progress.

**Comment by dmitshur** [comment]
Thanks. Having that information written down here will be helpful in the future. I think it's okay to close the issue since the builder is added and my question is answered, unless you're aware of something more to do here.

**Comment by mdempsky** [comment]
@dmitshur Cool, sounds good. Thanks, closing again then.

**Comment by mdempsky** [comment]
One more QQ: I assume this has to wait for the x/build code to be re-deployed? What's the timeframe like for that? (No rush, just interested in making sure things are working.)

**Comment by cagedmantis** [comment]
I can deploy the builder as soon as there are no active remote buildlets in use. I can notify you once it's deployed. I expect it would be a little later on today.

**Comment by mdempsky** [comment]
@cagedmantis Later today sounds great, thanks.

**Comment by cagedmantis** [comment]
@mdempsky The coordinator has been deployed.

**Comment by mdempsky** [comment]
@cagedmantis Thanks, the trybot looks like it's working great (after submitting golang.org/cl/329269 to fix a compiler bug w/ unified mode).

One thing I notice though: the "unified" column is still blank here: https://build.golang.org/?repo=&branch=dev.typeparams

Did I mess up the builder config? Something wrong with the `GoDeps` commit ID maybe?

**Comment by cagedmantis** [comment]
@mdempsky I will take a look at this in a bit.

**Comment by cagedmantis** [comment]
@mdempsky I'm still troubleshooting this. I'm pulling in some other team members to take a look at this point.

**Comment by cagedmantis** [comment]
The coordinator has been deployed. It includes the changes in [CL 341931](https://golang.org/cl/341931).
