### ISSUE TITLE
debug/dwarf: BitOffset values of bitfields is not being set in newer version of DWARF

### ISSUE THREAD

**Issue by jtsylve** [golang/go#46784]
### What version of Go are you using (`go version`)?

<pre>
 go version go1.16.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes (including 1.17 beta 1)

### Background Information

The DWARF v4 Standard depreciated the `DW_AT_bit_offset` attribute in favor of a new `DW_AT_data_bit_offset` attribute.  The value of `DW_AT_bit_offset` was reserved for backwards compatibility.

See the following snippet from the v4 DWARF Standard [1]:

```
Attribute DW_AT_data_bit_offset is new in DWARF Version 4 and is also used for bit field
members (see Section 5.5.6). It replaces the attribute DW_AT_bit_offset when used for base
types as defined in DWARF V3 and earlier. The earlier attribute is defined in a manner suitable
for bit field members on big-endian architectures but which is wasteful for use on little-endian
architectures.

The attribute DW_AT_bit_offset is deprecated in DWARF Version 4 for use in base types, but
implementations may continue to support its use for compatibility. 
```

### The Issue

The `debug/dwarf` package only checks against `AttrBitOffset` and ignores the `AttrDataBitOffset` attribute, causing the `BitOffset` fields to be set to zero in newer versions of DWARF debug info.

### Possible Solution

`AttrDataBitOffset` should be checked if there is no `AttrBitOffset` attribute.

```diff
diff --git a/src/debug/dwarf/type.go b/src/debug/dwarf/type.go
index eb5a666ed3..2e5a605174 100644
--- a/src/debug/dwarf/type.go
+++ b/src/debug/dwarf/type.go
@@ -516,7 +516,10 @@ func (d *Data) readType(name string, r typeReader, off Offset, typeCache map[Off
 		}).Basic()
 		t.Name = name
 		t.BitSize, _ = e.Val(AttrBitSize).(int64)
-		t.BitOffset, _ = e.Val(AttrBitOffset).(int64)
+		haveBitOffset := false
+		if t.BitOffset, haveBitOffset = e.Val(AttrBitOffset).(int64); !haveBitOffset {
+			t.BitOffset, _ = e.Val(AttrDataBitOffset).(int64)
+		}
 
 	case TagClassType, TagStructType, TagUnionType:
 		// Structure, union, or class type.  (DWARF v2 §5.5)
@@ -578,7 +581,9 @@ func (d *Data) readType(name string, r typeReader, off Offset, typeCache map[Off
 			haveBitOffset := false
 			f.Name, _ = kid.Val(AttrName).(string)
 			f.ByteSize, _ = kid.Val(AttrByteSize).(int64)
-			f.BitOffset, haveBitOffset = kid.Val(AttrBitOffset).(int64)
+			if f.BitOffset, haveBitOffset = kid.Val(AttrBitOffset).(int64); !haveBitOffset {
+				f.BitOffset, haveBitOffset = kid.Val(AttrDataBitOffset).(int64)
+			}
 			f.BitSize, _ = kid.Val(AttrBitSize).(int64)
 			t.Field = append(t.Field, f)
 
 ```
### References

[1] [DWARF Debugging Information Format, Version 4 ](http://www.dwarfstd.org/doc/DWARF4.pdf)

**Comment by thanm** [comment]
This seems reasonable to me.  Would you like to send a patch? Thanks.

**Comment by jtsylve** [comment]
@seankhliao What is the fix needed?  I have already updated the PR to add the requested unit test.

**Comment by ianlancetaylor** [comment]
@jtsylve The "NeedsFix" label just means that closing this issue requires a fix to be applied to the repository.  The change you already sent can be that fix.  Thanks.

**Comment by jtsylve** [comment]
@ianlancetaylor My apologies.  I thought I was responding to the thread label on the PR and not the issue.  That makes sense.

**Comment by dvyukov** [comment]
For anybody who found this issue: currently there is a subtle difference in bitfield representation with dward4+, see:
https://go-review.googlesource.com/c/go/+/328709/comments/edf0619d_daec236f

**Comment by thanm** [comment]
I filed a new issue to track the problem Dmitry raised: https://github.com/golang/go/issues/50685
