### ISSUE TITLE
go/types, cmd/compile/internal/types2: ensure that Named.Orig is indempotent

### ISSUE THREAD

**Issue by mdempsky** [golang/go#46794]
In both unified IR and types2, an operation that seems useful is to take an instantiated `Named` and decompose it into the (original) TypeName and type arguments.

Currently there's a `Named.Orig` method, but it's not always the case that `Named.Orig` is idempotent. E.g., there are at least test cases where it's necessary to apply it twice.

This is a placeholder issue to look into this further before Go 1.18.

/cc @griesemer @findleyr

**Comment by mdempsky** [comment]
noder/writer.go code:

https://github.com/golang/go/blob/dd95a4e3dbe1e060b59840efd7311e8d5e82c08c/src/cmd/compile/internal/noder/writer.go#L235-L248

types2/typestring.go code:

https://github.com/golang/go/blob/1ba2074440a9b82b6e39c42f40b9d04858aa6c75/src/cmd/compile/internal/types2/typestring.go#L362-L379

**Comment by toothrot** [comment]
Checking in on this issue as it's labeled a release blocker for Go 1.18. Is there any update?

**Comment by toothrot** [comment]
Checking in on this as a release-blocking issue. Are there any updates?

**Comment by findleyr** [comment]
No updates, other than it's near the top of my queue? This got push backed by not-okay-after-beta1 release blockers.

We suspect there isn't a bug here any more, but I need to prove it.

**Comment by findleyr** [comment]
Will address this by next week.

**Comment by griesemer** [comment]
Removing this from release-blockers. Still something we need to investigate but we have no evidence that this is causing us troubles at the moment.

**Comment by griesemer** [comment]
The loop
```Go
for typ.orig != typ { 
	typ = typ.orig 
}
```
doesn't exist anymore in `types2` and `go/types`, and the unified build (where the other loop is) is not enabled yet for 1.18.

It's not clear that this is still a problem. Should investigate early in 1.19 development by trying to identify code for which the loop in the unified noder triggers.

**Comment by griesemer** [comment]
Related reproducer (extracted from https://storage.googleapis.com/go-build-log/a42378ee/linux-amd64-unified_c6889d3a.log):

- use current tip (`go version devel go1.19-81d3c25c6c`)
- in `cmd/compile/internal/types2/check.go`, set the `debug` flag to `true`
- in `$GOROOT/src`, run: GOEXPERIMENT=unified ./make.bash

The build crashes with a panic:
```
<unknown line number>: internal compiler error: panic: validType0(nil)
```
The root cause is that `t.orig.fromRHS` is `nil` in some cases (`cmd/compile/internal/types2/validtype.go:74`); yet `fromRHS` should always be set.

**Comment by findleyr** [comment]
> The root cause is that t.orig.fromRHS is nil in some cases (cmd/compile/internal/types2/validtype.go:74); yet fromRHS should always be set.

This seems like a separate bug, right? Am I missing some way in which that implies that Origin is not idempotent?

**Comment by griesemer** [comment]
It turns out that [this](https://github.com/golang/go/issues/46794#issuecomment-1069582818) is a separate issue (https://go.dev/cl/393436).

**Comment by ianlancetaylor** [comment]
@griesemer This issue is in the 1.19 milestone.  Should it be 1.20?  Backlog?  Thanks.

**Comment by griesemer** [comment]
@findleyr is this still relevant?

**Comment by findleyr** [comment]
I don't think this is relevant anymore, but defer to mdempsky to confirm that this no longer repros. Bumping to 1.20, since that's when we plan to land unified IR.

**Comment by mdempsky** [comment]
I think this has been fixed too. In unified IR I added extra asserts to make sure it's idempotent and they're passing. I'll reopen if I run into any issues again. Thanks!
