### ISSUE TITLE
x/website: syscall/js missing

### ISSUE THREAD

**Issue by 89z** [golang/go#46795]
If I go here, everything is normal:

https://golang.org/pkg/syscall

but if I go here, I am greeted with a blank page:

https://golang.org/pkg/syscall/js

**Comment by 89z** [comment]
As a workaround, this seems to do it:

https://pkg.go.dev/syscall/js

**Comment by seankhliao** [comment]
it's available if you specify the proper os/arch https://golang.org/pkg/syscall/js/?GOOS=js&GOARCH=wasm
