### ISSUE TITLE
x/build: adding linux-riscv64-unmatched builder

### ISSUE THREAD

**Issue by mengzhuo** [golang/go#46804]
According to #41956 and @cagedmantis suggestion. 

I’m requesting builder `linux-riscv64-unmatched`

**Comment by 4a6f656c** [comment]
It would be good to understand what the plan is for `linux/riscv64` builders moving forward - currently there are two already (although the the `linux-riscv64-unleashed` was absent for a long time and appears to have disappeared again). There seems to be limited value in running multiple builders for the same platform, if they're doing the same work. Obviously the unmatched hardware will be slightly faster CPU-wise and a lot faster I/O-wise - if this hardware is available perhaps we should run this and turn off the existing two once stable?

(the other option would be to look at sharding the workloads, but that has its own sets of challenges)

**Comment by dmitshur** [comment]
It's hard to have a concrete plan, since these builders are remote and depend on people running them. Having multiple builders for the same platform can help if one goes missing, another can still provide coverage. Having them share workload would likely be better, but we don't have good support for that.

> if this hardware is available perhaps we should run this and turn off the existing two once stable?

That seems reasonable to me.

Also CC @bradfitz who's the owner of `host-linux-riscv64-unleashed`.

**Comment by 4a6f656c** [comment]
> It's hard to have a concrete plan, since these builders are reverse and depend on people running them. Having multiple builders for the same platform can help if one goes missing, another can still provide coverage. Having them share workload would likely be better, but we don't have good support for that.

Running two might make sense, but I certainly doubt three is beneficial - even with one, if that disappears for a period of time, we can readily get a replacement online (especially now that the hardware is more readily available).

> > if this hardware is available perhaps we should run this and turn off the existing two once stable?
> 
> That seems reasonable to me.

Sounds like a plan.

> Also CC @bradfitz who's the owner of `host-linux-riscv64-unleashed`.

**Comment by dmitshur** [comment]
If this offer still stands @mengzhuo, I think we can proceed. Has a builder key already been provided, or does that need to happen? I can review CL 329489 this week.

**Comment by dmitshur** [comment]
cmd/coordinator has been redeployed, so the reverse builder should be able to connect. It’s visible at https://farmer.golang.org now:

> host-linux-riscv64-unmatched: 0/0 (1 missing)

**Comment by mengzhuo** [comment]
linux-riscv64-unmatched is up and running now. Thanks @dmitshur !
