### ISSUE TITLE
image: add RGBA64Image interface [freeze exception]

### ISSUE THREAD

**Issue by nigeltao** [golang/go#46811]
# Background

Issue #44808 proposes adding an `image.RGBA64Image` interface and related code to the standard library.

The proposal was [marked likely accept on 2021-04-29](https://github.com/golang/go/issues/44808#issuecomment-828668186).

(Some dates may be out by ±1 day, because when various web sites provide a time stamp, it's not always obvious what time zone it's in).

[cl/311129](https://go-review.googlesource.com/c/go/+/311129/) was sent out for [review on 2021-05-02](https://go-review.googlesource.com/c/go/+/311129/1#message-dafedd32d4bdb40a3815daab7b44b2c97ed4009c). This change is (+292 -0) lines of code. It only adds new interfaces and methods to satisfy them. It does not modify or delete existing code.

Go 1.17 entered release freeze on [2021-05-04](https://groups.google.com/g/golang-dev/c/HzfjCwV_k5E/m/Exxa05Y5BgAJ).

That proposal was [accepted on 2021-05-06](https://github.com/golang/go/issues/44808#issuecomment-832911318).

Unfortunately, the reviewers didn't see that the proposal was accepted [until over a month later, 2021-06-17](https://go-review.googlesource.com/c/go/+/311129/1#message-b7ca3501c68f2c4046b64d83ecfa2495c3063598), yesterday.

The reviewers have since given "Code-Review +2", with some minor suggestions, some conditional on whether this still lands in Go 1.17.

# Freeze Exception Request

I am asking for a Go 1.17 freeze exception, following the [process posted to golang-dev](https://groups.google.com/g/golang-dev/c/VNJFUxHWLHo/m/PBmGdYqoAAAJ).

@dmitshur

**Comment by dmitshur** [comment]
Thanks for making a freeze exception request. I'll discuss this with the @golang/release team tomorrow, and we'll try to make a decision by then.

**Comment by dmitshur** [comment]
We've discussed this exception, and it is approved. This will need to be mentioned in the release notes (#44513), which can be done in the same CL or a follow up one. Please proceed and get everything submitted before RC 1 (which won't happen before July).

I've update the milestone of issue #44808 to Go1.17, closing here.
