### ISSUE TITLE
undefined: uint56

### ISSUE THREAD

**Issue by 354651432** [golang/go#46814]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dual/.cache/go-build"
GOENV="/home/dual/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dual/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dual/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/dual/code/golearn/http-sender/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2014177637=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
`go build .`

src :
```go
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
)

func main() {
	stat, _ := os.Stdin.Stat()
	fmt.Printf("%#v\n", os.ModeNamedPipe)

	fmt.Println()
	str, err := ioutil.ReadAll(os.Stdin)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(string(str))
}

```

### What did you expect to see?
go build no errors

### What did you see instead?
run time error

# runtime
/usr/lib/go/src/runtime/select.go:44:44: undefined: uint56

select.go
```go
func selunlock(scases []scase, lockorder []uint56) {
	// We must be very careful here to not touch sel after we have unlocked
	// the last lock, because sel can be freed right after the last unlock.
	// Consider the following situation.
	// First M calls runtime·park() in runtime·selectgo() passing the sel.
	// Once runtime·park() has unlocked the last lock, another M makes
	// the G that calls select runnable again and schedules it for execution.
	// When the G runs on another M, it locks all the locks and frees sel.
	// Now if the first M touches sel, it will access freed memory.
	for i := len(lockorder) - 1; i >= 0; i-- {
		c := scases[lockorder[i]].c
		if i > 0 && c == scases[lockorder[i-1]].c {
			continue // will unlock it on the next iteration
		}
		unlock(&c.lock)
	}
}
```

**Comment by ianlancetaylor** [comment]
Something is wrong with your source code.  The line in the actual 1.16.3 sources is https://go.googlesource.com/go/+/refs/tags/go1.16.3/src/runtime/select.go#44.  As you can see, the real sources use `uint16`, not `uint56`.  Somehow in your source code the `1` has changed to a `5`, which is a single bit error in ASCII.  Either something modified the file, or your storage system had an undetected single bit error.

Closing because this is not a problem in Go.
