### ISSUE TITLE
[dev.typeparams] import generic package failed with '-G=3'.

### ISSUE THREAD

**Issue by rockman001** [golang/go#46816]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-2a7900762c24 Fri Jun 18 02:07:04 2021 +0000 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xxxxxx\AppData\Local\go-build
set GOENV=C:\Users\xxxxxx\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\xxxxxx\Go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\xxxxx\Go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Users\xxxxxx\sdk\gotip
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\xxxxx\sdk\gotip\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=devel go1.18-2a7900762c24 Fri Jun 18 02:07:04 2021 +0000
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\xxxxxx\xxxxxx\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\xxxxx\AppData\Local\Temp\go-build2258112569=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
pkg01:
<pre>
package pkg01

func To[T any](in interface{}) T{
	return in.(T)
}
</pre>

main:
<pre>
package main

import (
	"generic_test/pkg01"
)
func main() {
        var t = interface{}("hello")
	ret := pkg01.To[string](t)
        println("ret:", ret)
}
</pre>

### What did you expect to see?

output:
<pre>
ret: hello
</pre>

### What did you see instead?
<pre>
PS D:\xxxxxxxx\generic_test> gotip build -gcflags=-G=3 main.go
# generic_test/pkg01
pkg01\pkg01.go:3:6: missing function body
pkg01\pkg01.go:3:8: syntax error: unexpected [, expecting (
</pre>

**Comment by cuonglm** [comment]
You must use `-gcflags=all=-G=3`.

**Comment by rockman001** [comment]
> You must use `-gcflags=all=-G=3`.

thanks
