### ISSUE TITLE
exec.command("bash","***.sh")  fork/exec Permission denied 

### ISSUE THREAD

**Issue by zhaoya881010** [golang/go#46819]
golang verison 1.12 x64
linux suse 

exec.command("bash","test.sh")  fork/exec Permission denied 

strace pid print:
37659 execve("/bin/bash",["bash","test.sh"])
37659 <... execve resumed>  = -1 EACCES (Permission denied)
37659 _exit(253) = ?

bash test.sh is ok!

**Comment by seankhliao** [comment]
That looks like a permission portobello on your system and not a problem with go. Also 1.12 is no longer supported
