### ISSUE TITLE
How to distribute a Golang library/SDK without disclosing source code?

### ISSUE THREAD

**Issue by pradeep-mj** [golang/go#46824]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
</pre></details>

### What did you do?
A bunch of things related to -buildmode=shared e.g.
go build -buildmode=shared mylibrary
go install -buildmode=shared -linkshared std
go build -buildmode=shared std
go build -buildmode=shared std mylibrary

None of them worked.

https://docs.google.com/document/d/1nr-TQHw_er6GOQRsF6T43GGhFDelrAP0NqSS_00RgZQ/edit?pli=1# mentions: 

> "Building Go packages as a shared library
> 
> In this mode a Go package, or set of packages, may be built as a shared library.  A Go program that imports one or more of those Go packages may be linked against this shared library.
> ...
> This mode is mainly intended to support distro builders."

However, I could not find any details on how to make it work.

### What did you expect to see?
Our company is building a Golang library that we want to distribute to other companies (customers), who are then expected to use it in their Golang executables. There is no involvement of Cgo or C-based programs / libraries. Our source code is not intended to be open-sourced, nor do we want our customers to view it. I understand they can decompile and see the code if they want, but at least we don't want to give them the plaintext source code files.

What is the recommended way to do this using Golang? I could not find any working solution so far after searching a lot.
### What did you see instead?
Nothing so far. If sharing our source code with customers is the only way to do this, we may want to investigate source code obfuscation options.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
