### ISSUE TITLE
errors: Unexpected behavior of errors.As if the struct has the same name as one of its methods

### ISSUE THREAD

**Issue by wendellrios** [golang/go#46820]
### What version of Go are you using (`go version`)?

<pre>
$ go version
 go1.15 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

https://play.golang.org/p/gWmNCTUMtau

### What did you expect to see?

PASS: TestCanEmbedPointerIfTypeNameIsEqualMethodName

### What did you see instead?
    prog.go:40: B is not an UE, but it should be. I believe this is an error in the library.
--- FAIL: TestCanEmbedPointerIfTypeNameIsEqualMethodName (0.00s)

**Comment by tmthrgd** [comment]
This is how the language works. In your second test the embedded field and method conflict so the method isn’t promoted. B really doesn’t have a `UserError` method.

If you try and call it manually you’ll see:
```
cannot call non-function new(B).UserError (type *UserError)
```

**Comment by ianlancetaylor** [comment]
Closing because there is no bug here.
