### ISSUE TITLE
x/image/font: Opentype allocates bunch of memory when calculating Glyph of some characters.

### ISSUE THREAD

**Issue by hismailbulut** [golang/go#46836]
### What version of Go are you using (`go version`)?

<pre>
$ go version
 go1.16.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
I am using latest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\bulut\AppData\Local\go-build
set GOENV=C:\Users\bulut\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\bulut\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\bulut\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\bulut\scoop\apps\go\current
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\bulut\scoop\apps\go\current\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.5
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\bulut\AppData\Local\Temp\go-build547496714=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I am trying to render font with using image opentype package, everything is good except one font file.
The font is an .otf font and I packed with nerdfont packer from Cascadia Mono font. After drawing some glyphs
it freezes when it comes to nerd icons. Allocates bunch of memory and not finishing 'Glyph' function. If I try with
-race option it gives this error: 
==8788==ERROR: ThreadSanitizer failed to allocate 0x0001f6000000 (8422162432) bytes at 0x040094000000 (error code: 1455)

I am drawing glyph with this code:
```
func renderGlyph(face *font.Face, c rune) *image.RGBA {
	img := image.NewRGBA(image.Rect(0, 0, cellWidth, cellHeight))
	dot := fixed.P(0, cellHeight-descent)
	dr, mask, maskp, _, ok := face.Glyph(dot, c)
	if ok {
		draw.DrawMask(img, dr, image.White, image.Point{}, mask, maskp, draw.Over)
		return img
	}
	return nil
}
```

I tried font file with other programs and I don't see any issues. I can draw other fonts and characters with this
function. But only this one causing error. The base font file is original Cascadia Code and packed with nerd fonts.

This shows the usage of memory. Normally ~50 mb
![Ekran görüntüsü 2021-06-20 140354](https://user-images.githubusercontent.com/73897211/122671983-e8db7a80-d1d1-11eb-9565-1c218ab316a7.png)

And this is the font file:
[Cascadia Mono Regular Nerd Font Complete Mono Windows Compatible.zip](https://github.com/golang/go/files/6682174/Cascadia.Mono.Regular.Nerd.Font.Complete.Mono.Windows.Compatible.zip)

Edit:
I tried with same font but ttf and it's works perfectly. I don't know if this is an issue but high memory usage and not giving an error may need to be fixed.

### What did you expect to see?
Just draw the font.

### What did you see instead?
Memory corruption and I think a long unexpected loop.

**Comment by seankhliao** [comment]
can you provide a self contained, runnable example?

**Comment by hismailbulut** [comment]
I can be able to reproduce with this little test.
[opentypetest.zip](https://github.com/golang/go/files/6683134/opentypetest.zip)
