### ISSUE TITLE
how to get at udp "cmsg" data for ipv4 and ipv6?

### ISSUE THREAD

**Issue by dtaht** [golang/go#46831]
### What version of Go are you using (`go version`)?

<pre>
go version go1.16.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code># go env
</code> Output</summary><br><pre>
# go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.16"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.16/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3684522948=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
We're working on a couple of bufferbloat-detection programs that need to see control messages
and headers from IPv4 and IPv6 packets.  One of these is NTPsec, which needs to
see packet-receipt timestamps (SO_TIMESTAMP or SO_TIMESTAMPNS options);
NTPsec is written in C but we're contemplating moving it to Go for
memory safety. Another is irtt, a utility for performing isochronous
transit timing already written in Go.

See WIP here: https://github.com/heistp/irtt/commit/f656b60123b92ae021f85f03dc068a117daa7b59

This has run us head-on into some apparent gaps and oddities in the
Golang network interface which I'm hoping someone can explain.

First, I'm generally interested in the question of how to enable, send, and
retrieve CMSG data in Go. I see the entry points CmsgLen() and CmsgSpace()
in the sycall package, but they're poorly documented and there is no code example
of how to use them. Web searches don't turn up any good hits.

Can anyone point me at a working example of CMSG reception in Go?  I
am, as mentioned before, especially interested in being able to pick up
packet-receipt timestamps.

Second, there is a peculiar asymmetry in the design if the ipv4 and
ipv6 libraries.  I'd expect them to have APIs that are no more
different than is forced by the differing address sizes and packet
header formats, but this is definitely not the case.

In particular, the signature of the ReadFrom method has been quite
unstable.  In the ipv6 package one of its return values is an IPv6
Header; I was able to use this to get ECN bits, which irtt wants to
see (and eventually it's going to want the Flow field as well).
However, in the x/ipv6 package that return is gone, and I can't find
any entry point that allows me to get ECN bits Flow ID or other header
information from a packet.

In the IPv4 package getting the ECN bits apopeares to be possible, but
only by initializing a RawConn object.  Why is this required for IPv4
but not IPv6?  Can anyone point me at an example of code actually breaking
out a received IPv4 packert header?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
