### ISSUE TITLE
cmd/vet: false positive for uint128 ([2]uint64)

### ISSUE THREAD

**Issue by zhangyunhao116** [golang/go#46843]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/zyh/.cache/go-build"
GOENV="/home/zyh/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/zyh/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/zyh/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/zyh/GitHub/lscqtest/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2984921841=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
go vet these files

<details><summary><code>asm.go</code> Content </summary><br><pre>
// +build amd64,!gccgo,!appengine

package lscq

import "unsafe"

type uint128 [2]uint64

func compareAndSwapUint128(addr *uint128, old, new uint128) (swapped bool)
</pre></details>

<details><summary><code>asm_amd64.s</code> Content </summary><br><pre>
// +build amd64,!gccgo,!appengine

#include "textflag.h"

TEXT ·compareAndSwapUint128(SB),NOSPLIT,$0
	MOVQ addr+0(FP), R8
	MOVQ old+8(FP), AX
	MOVQ old+16(FP), DX
	MOVQ new+24(FP), BX
	MOVQ new+32(FP), CX
	LOCK
	CMPXCHG16B (R8)
	SETEQ swapped+40(FP)
	RET
</pre></details>
### What did you expect to see?

Nothing will happen.

### What did you see instead?
<pre>
./asm_amd64.s:7:1: [amd64] compareAndSwapUint128: invalid MOVQ of old+8(FP); github.com/zhangyunhao116/lscqtest.uint128 is 16-byte value
./asm_amd64.s:8:1: [amd64] compareAndSwapUint128: invalid offset old+16(FP); expected old+8(FP)
./asm_amd64.s:9:1: [amd64] compareAndSwapUint128: invalid MOVQ of new+24(FP); github.com/zhangyunhao116/lscqtest.uint128 is 16-byte value
./asm_amd64.s:10:1: [amd64] compareAndSwapUint128: invalid offset new+32(FP); expected new+24(FP)
./asm_amd64.s:24:1: [amd64] loadUint128: invalid MOVQ of val+8(FP); github.com/zhangyunhao116/lscqtest.uint128 is 16-byte value
./asm_amd64.s:25:1: [amd64] loadUint128: invalid offset val+16(FP); expected val+8(FP)
</pre>

**Comment by zhangyunhao116** [comment]
Some hints:
These errors come from 
https://github.com/golang/tools/blob/master/go/analysis/passes/asmdecl/asmdecl.go#L782
https://github.com/golang/tools/blob/master/go/analysis/passes/asmdecl/asmdecl.go#L800

Looks like `go vet` should allow a single instruction to load each part of an array?

**Comment by seankhliao** [comment]
cc @matloob

**Comment by josharian** [comment]
Try e.g.

```
MOVQ new_0+24(FP), BX
MOVQ new_1+32(FP), CX
```

That is, use underscores to refer to components of a composite type.

**Comment by zhangyunhao116** [comment]
@josharian It works, thanks a lot!

> Try e.g.
> 
> ```
> MOVQ new_0+24(FP), BX
> MOVQ new_1+32(FP), CX
> ```
> 
> That is, use underscores to refer to components of a composite type.
