### ISSUE TITLE
x/pkgsite: `v0.21.2` missing for `k8s.io/client-go`

### ISSUE THREAD

**Issue by shu-mutou** [golang/go#46844]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/k8s.io/client-go?tab=versions
 
### What is your user agent?
 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36
 
### Screenshot

![image](https://user-images.githubusercontent.com/12838129/122720998-19dbae00-d2ab-11eb-982c-0c57beebaee6.png)
 
### What did you do?
 
The tag `v0.21.2` for `k8s.io/client-go` is missing in https://pkg.go.dev/k8s.io/client-go?tab=versions
But exists at:
* https://github.com/kubernetes/client-go/tree/v0.21.2
* https://github.com/kubernetes/client-go/releases/tag/v0.21.2
* https://proxy.golang.org/k8s.io/client-go/@v/v0.21.2.info 
  
### What did you expect to see?

The tag `v0.21.2` for `k8s.io/client-go` exists at https://pkg.go.dev/k8s.io/client-go?tab=versions
 
### What did you see instead?

The tag is missing.

**Comment by jba** [comment]
Thanks for noticing. Fixed.
