### ISSUE TITLE
proxy.golang.org: IP addresses

### ISSUE THREAD

**Issue by kleaver** [golang/go#46853]
I'm wondering if there's any documentation of the IP addresses for proxy.golang.org.  I'm trying to allow these addresses in a firewall so I can download Go module dependencies from proxy.golang.org.  Closest I've found is the list [here](https://support.google.com/a/answer/10026322?hl=en), wondering if there's a subset of those ranges that can be relied on.

**Comment by seankhliao** [comment]
cc @katiehockman @heschi @hyangah

**Comment by heschi** [comment]
That's it -- proxy.golang.org is served by Google's generic frontend servers.

**Comment by heschi** [comment]
This was more of a question than an issue and it's answered. Closing.

**Comment by kleaver** [comment]
Thanks for your help, appreciate it!
