### ISSUE TITLE
Why I can't run test in go1.16.3

### ISSUE THREAD

**Issue by the-moment** [golang/go#46868]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.16.3

</pre>

### Does this issue reproduce with the latest release?
sry, i didn't try.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre>set GO111MODULE=off
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\hujitian\AppData\Local\go-build
set GOENV=C:\Users\hujitian\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\hujitian\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\hujitian\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,https://goproxy.io,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\hujitian\AppData\Local\Temp\go-build1428501175=/tmp/go-build -gno-record-gcc-switches</details>

### What did you do?

I run a xxx_test.go in my program.

### What did you expect to see?

success to run test

### What did you see instead?
flag provided but not defined: -test.v 

why i use go 1.16.3 still have this problem, need I change the version to 1.12?
or how can i fix this bug. please help

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by agnivade** [comment]
This is expected and documented: https://golang.org/doc/go1.13#testing and #31859.
