### ISSUE TITLE
x/pkgsite:cannot request documentation

### ISSUE THREAD

**Issue by and3rson** [golang/go#46876]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/and3rson/telemux

### What is your user agent?

`User-Agent | Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0`

### Screenshot

Just a message saying:

```
"github.com/and3rson/telemux" could not be found.
```
 
### What did you do?

Tried to browse documentation for my [project](//github.com/and3rson/telemux).
 
### What did you expect to see?
 
Documentation for my project.

I can still download it via https://proxy.golang.org/github.com/and3rson/telemux/@v/v1.0.1.zip.

I can also fetch https://sum.golang.org/lookup/github.com/and3rson/telemux@v1.0.1 and https://proxy.golang.org/github.com/and3rson/telemux/@v/v1.0.1.info. My repo has `go.mod`, `go.sum`, LICENSE, README and docstrings.

Also, my package doesn't seem to be present here - https://index.golang.org/index - is it OK?
 
### What did you see instead?

Error message (see screenshot).

**Comment by julieqiu** [comment]
Fixed.
