### ISSUE TITLE
 can only use path@version syntax with 'go get' and 'go install' in module-aware mode

### ISSUE THREAD

**Issue by hentzels** [golang/go#46875]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
$ brew upgrade go
Warning: go 1.16 already installed
yes, leatest version
and like described in help: go.mod in the same folder where started the build command

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xyzuser/Library/Caches/go-build"
GOENV="/Users/xyzuser/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xyzuser/go/pkg/mod"
GONOPROXY="github.<company>.com"
GONOSUMDB="github.<company>.com"
GOOS="darwin"
GOPATH="/Users/xyzuser/go"
GOPRIVATE="github.<company>.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xyzuser/go/src/github.<company>.com/coligo/cli/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hy/jp5519wj523cnntg7f_cstb00000gn/T/go-build1458645750=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

import (
conditions "<path-to-repo>@<feature-branch-name>/<subfolder>/<package-name>"
)

### What did you expect to see?
running build

### What did you see instead?
no compile error any more but an runtime error:
err: 
imports <path-to-repo>@<feature-branch-name>/<subfolder>/<package-name>: can only use path@version syntax with 'go get' and 'go install' in module-aware mode

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
