### ISSUE TITLE
json.Number doesnt supoprt NaN / INF

### ISSUE THREAD

**Issue by 0dayfall** [golang/go#46872]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
amd64
</pre></details>

### What did you do?

json.Number doesnt support NaN and INF which are supported in json.

### What did you expect to see?
A check or conversion for those.

### What did you see instead?
An error when marshalling.

**Comment by fzipp** [comment]
> json.Number doesnt support NaN and INF which are supported in json.

No, NaN and Infinity are not part of JSON.

**Comment by seankhliao** [comment]
Duplicate of #3480
