### ISSUE TITLE
x/tools/go/loader: can no longer load cgo files with local #includes

### ISSUE THREAD

**Issue by benjaminp** [golang/go#46877]
https://github.com/golang/tools/commit/67e49ef2d0f326051e22a4a55bdf9344ae1a8ed8 changed the loader to invoke `cmd/cgo` outside of the package directory, which is contrary to how `cmd/go` does it. That means the cwd inherited by `cmd/cgo`'s compiler invocations no longer includes any headers in the package directory.

**Comment by dmitshur** [comment]
CC @mdempsky, @ianlancetaylor.

**Comment by mdempsky** [comment]
It looks like `cmd/go` doesn't use the `-srcdir` flag when invoking `cmd/cgo`. Instead, it sets the `PWD` environment variable, which `os.Getwd` looks for.
