### ISSUE TITLE
go tool pprof list — missed source lines

### ISSUE THREAD

**Issue by uh-zuh** [golang/go#46871]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Egor\AppData\Local\go-build
set GOENV=C:\Users\Egor\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=c:\Egor\MyProject\Go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=c:\Egor\MyProject\Go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\XPrograms.Portable\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\XPrograms.Portable\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.5
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Egor\MyProject\learn_mail.ru\3\99_hw_go_bug\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Egor\AppData\Local\Temp\go-build163049723=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Sources and other files:
[go_tool_pprof_list_missed_source_lines.zip](https://github.com/golang/go/files/6694428/go_tool_pprof_list_missed_source_lines.zip)

Using `list` command in `go tool pprof` sometimes some lines of code are missing.

There is beginning of the function:
```
func SlowSearch(out io.Writer) {

	file, err := os.Open(filePath)
	if err != nil {
		panic(err)
	}

	fileContents, err := ioutil.ReadAll(file)
	if err != nil {
		panic(err)
	}

	r := regexp.MustCompile("@")
	seenBrowsers := []string{}
	uniqueBrowsers := 0
	foundUsers := ""

	lines := strings.Split(string(fileContents), "\n")
```

---

There are some additional lines in the beginning and some lines are missed in the end.
```
go test -bench . -cpuprofile bench_cpu.pprof
go tool pprof .\hw3.test.exe .\bench_cpu.pprof
```
Result:
```
(pprof) list SlowSearch
Total: 1.22s
ROUTINE ======================== hw3.SlowSearch in C:\Egor\MyProject\learn_mail.ru\3\99_hw_go_bug\common.go
         0      810ms (flat, cum) 66.39% of Total
         .          .     13:
         .          .     14:const filePath string = "./users.txt"
         .          .     15:
         .          .     16:func SlowSearch(out io.Writer) {
         .          .     17:
         .       10ms     18:   file, err := os.Open(filePath)
         .          .     19:   if err != nil {
         .          .     20:           panic(err)
         .          .     21:   }

...

         .      240ms     85:                   if ok, err := regexp.MatchString("MSIE", browser); ok && err == nil {
         .          .     86:                           isMSIE = true
         .          .     87:                           notSeenBefore := true
         .          .     88:                           for _, item := range seenBrowsers {
         .          .     89:                                   if item == browser {
         .          .     90:                                           notSeenBefore = false
(pprof)
```

---

There are some missed lines in the beginning.
```
go test -bench . -benchmem -cpuprofile bench_cpu.pprof -memprofile bench_mem.pprof -memprofilerate 1
```

Result:
```
(pprof) list SlowSearch
Total: 2.31s
ROUTINE ======================== hw3.SlowSearch in C:\Egor\MyProject\learn_mail.ru\3\99_hw_go_bug\common.go
         0      2.04s (flat, cum) 88.31% of Total
         .          .     32:
         .          .     33:   lines := strings.Split(string(fileContents), "\n")
         .          .     34:
```

---

I have tried to delete all binary files and rebuild -- result the same.
Commands `list`, `weblist`, web interface with parameter `-http` give same result with same missed lines in source code.

### What did you expect to see?

All lines of function in pprof list command.

### What did you see instead?

Some lines of the function are missed.

**Comment by ALTree** [comment]
Only lines around samples are showed in the listing. Pieces of the sources with no samples in it are not displayed.

**Comment by uh-zuh** [comment]
How to increase number of samples?

**Comment by ALTree** [comment]
By setting memprofilerate and cpuprofilerate, but even at max settings if a part of code doesn't have e.g. any allocation it won't be shown by default.

**Comment by uh-zuh** [comment]
There is enough CPU time and memory allocations in `ioutil.ReadAll()` call which located in missed lines.

I have used `-memprofilerate 1`, but there is no param cpuprofilerate:
```
> go test -bench . -benchmem -cpuprofile bench_cpu.pprof -memprofile bench_mem.pprof -memprofilerate 1 -cpuprofilerate=1  
flag provided but not defined: -cpuprofilerate
```

If I use `runtime.SetCPUProfileRate()` in code I get a warning:
```
runtime: cannot set cpu profile rate until previous profile has finished.
```

How can I set cpuprofilerate properly?

**Comment by uh-zuh** [comment]
@ALTree
