### ISSUE TITLE
net/http: Accept-Encoding:gzip not being added

### ISSUE THREAD

**Issue by 89z** [golang/go#46881]
If I make a request like this:

~~~
curl -v -H 'Accept-Encoding: gzip' https://github.com
~~~

I get this response:

~~~
< content-encoding: gzip
~~~

However this program errors out:

~~~go
package main

import (
   "fmt"
   "net/http"
   "strings"
)

func request() error {
   r, err := http.Get("https://github.com")
   if err != nil {
      return err
   }
   header := "content-encoding"
   for key := range r.Header {
      if strings.EqualFold(key, header) {
         return nil
      }
   }
   return fmt.Errorf("%q missing", header)
}

func main() {
   if err := request(); err != nil {
      panic(err)
   }
}
~~~

It seems `gzip` is supposed to be requested automatically:

https://github.com/golang/go/blob/go1.16.3/src/net/http/transport.go#L2561
https://github.com/golang/go/blob/go1.16.3/src/net/http/h2_bundle.go#L7577

~~~
go version go1.16.3 windows/amd64
~~~

**Comment by davecheney** [comment]
Pretty sure compressed bodies are handled transparently, same as chunked bodies.

**Comment by 89z** [comment]
I think this answers it

https://github.com/golang/go/blob/0ebd5a8de05823109263bef31b38be8c29d2cd54/src/net/http/transport.go#L2189-L2195
