### ISSUE TITLE
dev.boringcrypto: why is FIPS-only mode restricted to TLS 1.2?

### ISSUE THREAD

**Issue by claucece** [golang/go#46898]
Apologies if this has been already answered somewhere else.

Is the FIPS-only mode in dev.boringcrypto.go branch restricted to TLS 1.2?
https://github.com/golang/go/blob/dev.boringcrypto.go1.16/src/crypto/tls/boring.go#L32

Is there a reason for so? I couldn't find documentation around it. Apologies if it is indeed written somewhere.

**Comment by ianlancetaylor** [comment]
CC @FiloSottile @agl

**Comment by FiloSottile** [comment]
I believe FIPS 140 requires TLS 1.2. @agl can probably elaborate on that.

**Comment by agl** [comment]
The situation around FIPS 140 and TLS 1.3 is a little complex. However, Google is not in a position to give opinions on the interpretation of NIST rules and we recommend that you retain the services of an NVLAP lab for that.

As noted in [the README](https://go.googlesource.com/go/+/dev.boringcrypto/README.boringcrypto.md), the dev.boringcrypto branch is offered _in case it's useful_ and we're not warranting it in any particular context. If you have a lab opinion that says that it's reasonable to use BoringCrypto, as integrated into Go in dev.boringcrypto, with TLS 1.3 then you can of course change that line around.

**Comment by claucece** [comment]
Thank you @agl and @FiloSottile for the answers ;)
