### ISSUE TITLE
x/tools/gopls: vet the DegradeClosed memory mode and move out of experimental

### ISSUE THREAD

**Issue by findleyr** [golang/go#46902]
https://golang.org/cl/330529 fixed loading of std and cmd, resulting in better features for std and cmd but worse resource usage.

`"memoryMode": "DegradedClosed"` should per my recollection revert us to the old model, but it seems not to work. We should fix this. More generally, I think the degraded memory model could be useful for many users, and we should vet it and move it out of experimental.

CC @stamblerre

**Comment by findleyr** [comment]
I'm not sure we should remove the 'memoryMode' setting yet, until we have more data on the performance of gopls' new architecture. Moving this to v0.13.0.

**Comment by adonovan** [comment]
Perhaps we can provide users all the control the need with just two parameters to delay the onset of type checking and of go.analysis?

**Comment by adonovan** [comment]
> I'm not sure we should remove the 'memoryMode' setting yet, until we have more data on the performance of gopls' new architecture. Moving this to v0.13.0.

Should we remove it for v0.15?
