### ISSUE TITLE
cmd/compile: crashes in slicing array converted from slice

### ISSUE THREAD

**Issue by go101** [golang/go#46907]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17beta1 linux/amd64
</pre>

### What did you do?

```Go
package main

func SumPointer(b []byte) []byte {
	return (*[32]byte)(b[:32])[:]
}

func main() {
}
```

### What did you expect to see?

Compiles okay.

### What did you see instead?

Compiler crashes.

```
# command-line-arguments
./main.go:4:28: internal compiler error: 'SumPointer': bad type in slice int


Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
```

**Comment by ianlancetaylor** [comment]
CC @josharian @randall77 @mdempsky

**Comment by toothrot** [comment]
This looks like a serious issue. In 1.16, this would report: `cannot convert b[:32] (type []byte) to type *[32]byte`.

**Comment by josharian** [comment]
I'm AFK for a while, but on my phone, looks like the type for the return value in ssagen/ssa.go:3177 is wrong. It is TINT, but should be n.Type(). Anyone else should feel free to send this as a CL, if this diagnosis seems right.

**Comment by mdempsky** [comment]
Sorry for the assignment churn. I was trying to assign it to @cuonglm, because he jumped on it with CL 330672 (thanks @cuonglm!). But GitHub won't allow me to for some reason.

**Comment by cuonglm** [comment]
> Sorry for the assignment churn. I was trying to assign it to @cuonglm, because he jumped on it with CL 330672 (thanks @cuonglm!). But GitHub won't allow me to for some reason.

Yay, I actually have the CL ready one hour ago, but still trying to figure it out why the wrong type is not problem in normal case. Also, sounds like we are not consistent in the type argument passing with `OpSlicePtr`. But I think `n.Type()` is best here.

**Comment by mdempsky** [comment]
> still trying to figure it out why the wrong type is not problem in normal case.

Probably because SSA doesn't do any type checking to make sure types are consistent, and `int` and `*[N]T` are interchangeable in most cases.

Also, the feature is new, so we probably don't have any code to exercise that `*[N]T` is handled correctly by the garbage collector if it needs to get spilled out of the register set for some reason.

**Comment by ALTree** [comment]
@mdempsky Only people in the go-assignees group can be assigned issues: https://github.com/orgs/golang/teams, but Cuong is not part of that group.

**Comment by mdempsky** [comment]
@ALTree Thanks. Do you know how we fix that? I clicked around briefly, and either I couldn't figure out how to add members or I don't have authority to.

Cuong has been a Gerrit approver for a while now.

**Comment by ALTree** [comment]
He's a gerrit approver but Github Access and Gerrit Access are two separated things. 

He needs to be part of the Golang Github organization first, he's currently not (he's not in https://github.com/orgs/golang/people and his label says "collaborator", not "member").

He should open an issue as described here: https://github.com/golang/go/wiki/GithubAccess asking for Assignees and Editors roles (if he wishes to).

**Comment by cuonglm** [comment]
@ALTree Thanks, I filed https://github.com/golang/go/issues/46920
