### ISSUE TITLE
cmd/compile: memory corruption from `//go:notinheap` interface method wrappers

### ISSUE THREAD

**Issue by mdempsky** [golang/go#46903]
If `T` is a `//go:notinheap` type, then `*T` is treated like `uintptr` rather than pointer-shaped. One consequence of this is that the interface method wrappers for `T` need to use `**T` instead of `*T`.

However, reflectdata.methodWrapper doesn't handle this correctly. For example, this program panics, whereas it succeeds if you remove the `//go:notinheap` directive: https://play.golang.org/p/p7TiaXlyJzX

Discovered while reimplementing wrapper generation for unified IR.

**Comment by mknyszek** [comment]
@mdempsky This looks like it could be fixed, but I haven't been following the unified IR work so I'm not sure if that's been enabled by default. Please close if so. Thanks!

**Comment by ianlancetaylor** [comment]
The program in the initial comment now causes a compiler crash:

```
# command-line-arguments
esc
.   CALL tc(1) # <autogenerated>:1:0
.   .   DOTPTR main.M tc(1) # <autogenerated>:1:0
.   .   .   NAME-main..this ld(1) Class:PPARAM Offset:0 OnStack Used PTR-**A tc(1) # <autogenerated>:1:0
<autogenerated>:1: .this.M undefined (type **A has no field or method M)
```

This only happens when usin the `go:notinheap` directive, so this doesn't seem critical.  The `go:notinheap` directive isn't even documented.  So changing milestone to 1.19.

**Comment by cherrymui** [comment]
Maybe we can disallow putting notinheap types in interfaces. Do we need notinheap types in interfaces?

**Comment by mdempsky** [comment]
> Do we need notinheap types in interfaces?

I just tested hacking unified IR to reject converting notinheap types to interface, and the only error building the standard library is this code in netpoll.go for getting the `*_type` for `*pollDesc`:

```
netpoll.go:     pdEface any    = (*pollDesc)(nil)
netpoll.go:     pdType  *_type = efaceOf(&pdEface)._type
```

It's possible end users put cgo `C.foo` and `*C.foo` types into interfaces too, though cgo types don't have methods.

**Comment by cherrymui** [comment]
Thanks. These two don't need methods. So maybe we can make it that notinheap type doesn't satisfy any interface methods. So (only) empty interface is fine.

**Comment by randall77** [comment]
I like the idea of forbidding methods on notinheap types.
Or just that their methods don't satisfy otherwise corresponding interface methods?

**Comment by mdempsky** [comment]
I'm a bit worried about subtle desyncs between static and dynamic interface satisfiability.

How do folks feel about instead disallowing conversion of `T` and `*T` to any interface type (including empty interface), when `T` is notinheap and has methods?

The alternative is to implicitly treat all methods on a notinheap type as nointerface. I think that should work fine, but currently nointerface is only used for GOEXPERIMENT=fieldtrack, so it's a bit less exercised than other compiler code paths.

**Comment by mdempsky** [comment]
Okay, that SGTM. I'll double check the nointerface logic.

**Comment by mdempsky** [comment]
It's unfortunately not as simple as implicitly marking them all as nointerface methods, because we have to worry about promoted methods too. But we only want methods promoted to a NIH type's method set to be marked nointerface, whereas currently the `//go:nointerface` bit is shared across the base method and all promotions.

It might be a little more robust to require all methods (including promoted methods) on //go:notinheap types to be explicitly marked as //go:nointerface. That's perhaps more tedious for the runtime team, but would be more obvious what's happening too.

**Comment by ianlancetaylor** [comment]
Rolling milestone forward to 1.20.

**Comment by aclements** [comment]
Do I understand correctly that the symptom of this is now a compiler crash rather than memory corruption? If so, we should retitle the issue.

**Comment by cherrymui** [comment]
`//go:notinheap` is now `sys.NotInHeap`, and at tip it doesn't seem to have problems with `sys.NotInHeap`. I think we can close this now.
