### ISSUE TITLE
x/sys: windows.WTD_STATEACTION_VERIFY has incorrect value

### ISSUE THREAD

**Issue by konangc87** [golang/go#46906]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\fedegc\AppData\Local\go-build
set GOENV=C:\Users\fedegc\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\fedegc\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\fedegc\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.5
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\fedegc\AppData\Local\Temp\go-build2839842620=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you expect to see?
windows.WTD_STATEACTION_VERIFY value is 0x00000001 (according to [msdn](https://docs.microsoft.com/en-us/windows/win32/api/wintrust/ns-wintrust-wintrust_data#:~:text=the%20hWVTStateData%20member.-,WTD_STATEACTION_VERIFY,-0x00000001)) 

### What did you see instead?
windows.WTD_STATEACTION_VERIFY value is 0x00000010 ([types_windows.go](https://cs.opensource.google/go/x/sys/+/master:windows/types_windows.go;drc=6ca3eb03dfc2ec15b5cb1a66e77caadc71075763;l=683))

**Comment by toothrot** [comment]
@bufflig - this seems possibly a typo?

**Comment by networkimprov** [comment]
cc @alexbrainman @mattn

**Comment by alexbrainman** [comment]
> this seems possibly a typo?

I agree. It is a mistake in

https://go-review.googlesource.com/c/sys/+/285715

@konangc87 would you like to send a fix for your issue yourself? Here is

https://golang.org/doc/contribute

how to contribute.

/cc @zx2c4 because he authored the CL 285715.

Alex

**Comment by zx2c4** [comment]
Nice catch! Looks like a typo indeed? Or mingw headers are wrong? I'll have to check how this happened. I wonder, though, what the behavior of 0x10 is, as I've been using the bad code in question for some time.

I can send a CL for this if you don't want to.

**Comment by konangc87** [comment]
> > this seems possibly a typo?
> 
> I agree. It is a mistake in
> 
> https://go-review.googlesource.com/c/sys/+/285715
> 
> @konangc87 would you like to send a fix for your issue yourself? Here is
> 
> https://golang.org/doc/contribute
> 
> how to contribute.
> 
> /cc @zx2c4 because he authored the CL 285715.
> 
> Alex

No problem. I'll submit the fix =)

**Comment by zx2c4** [comment]
https://golang.org/cl/331010 covers it already.
