### ISSUE TITLE
x/tools/gopls: fails to load std and cmd workspace packages

### ISSUE THREAD

**Issue by findleyr** [golang/go#46901]
Gopls loads std and cmd with the go/packages queries "std/..." and "cmd/...", respectively, resulting in no workspace packages being loaded. As a result, the only packages considered part of the workspace are loaded via open files.

This seems to have been the case for a while, but may have become more noticeable with recent memory optimizations.

This is straightforward to fix, though it makes working in cmd and std a lot more resource intensive: 2.8G vs <1G for me, and find references on testing.T takes a good 5-10s.  I'd still prefer to fix it. If anyone wants the old behavior they can opt in to the degraded memory mode.

CC @stamblerre @mdempsky

**Comment by mdempsky** [comment]
How do you opt-in to the previous behavior?

**Comment by findleyr** [comment]
> How do you opt-in to the previous behavior?

`"memoryMode": "DegradeClosed"`
should do it.

We should verify this and move this setting out of experimental before releasing the attached change to std/cmd loading.

**Comment by findleyr** [comment]
Whelp, degraded memory mode doesn't seem to help much, actually. I'll file a separate issue for that.
