### ISSUE TITLE
Receiving error "Dynamic SQL Error\nSQL error code = -303" since upgrading Go version.

### ISSUE THREAD

**Issue by hmyrie** [golang/go#46918]
### What version of Go are you using (`go version`)?

<pre>
$ go version
version 1.16
</pre>

### Does this issue reproduce with the latest release?
Yes.  Worked under the previous version Go1.14.

Error started after upgrade to new version 1.16.

### What operating system and processor architecture are you using (`go env`)?
Running on Windows 10 Pro. x64-based processor.

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ictcon\AppData\Local\go-build
set GOENV=C:\Users\ictcon\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\ictcon\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\ictcon\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.5
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Go\AutoRx\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ictcon\AppData\Local\Temp\go-build3578739727=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
I upgraded to go version 1.16 from version 1.14

See sample of code below;
<pre>
func getErrCodes(w http.ResponseWriter, r *http.Request) {

	type Codes struct {
		Description  string  `json:"description"`
		Code   NullString  `json:"code"`
	}
	codes := []Codes{}

	conn, _ := sql.Open("firebirdsql", datapath)
    defer conn.Close()
	rows, err := conn.Query("select description, code from rcodes")
	if err != nil {
		respondWithError(w, http.StatusBadRequest, err.Error())
		logError(err.Error())
		return
	}
	defer rows.Close()
	for rows.Next() {
		var c Codes
		err := rows.Scan(&c.Description, &c.Code)
		if err != nil {
			respondWithError(w, http.StatusBadRequest, err.Error())
			logError(err.Error())
			return
		}
		codes = append(codes, c)
	}
	err = rows.Err()   // <-- error occurs here.
	if err != nil {
		respondWithError(w, http.StatusBadRequest, err.Error())
		logError(err.Error())
		return
	}
	respondWithJSON(w, http.StatusOK, codes)

}
</pre>

### What did you expect to see?

I expected to see the result set being returned from the database.

### What did you see instead?
Getting the error (for all select query):

{"error":"Dynamic SQL Error\nSQL error code = -303\narithmetic exception, numeric overflow, or string truncation\nstring right truncation\n"}

**Comment by seankhliao** [comment]
That's an error reported by your database driver, please report the problem there

**Comment by hmyrie** [comment]
Thanks for your response. Question though, 'Why would the query worked under Go1.14 and now throw an error under Go1.16?' Plus an empty result set is being returned prior to the line that generated the error. Just asking?
