### ISSUE TITLE
x/pkgsite: support standard lib documentation in dev.fuzz branch

### ISSUE THREAD

**Issue by katiehockman** [golang/go#46910]
@julieqiu requested a tracking issue for this:

We would like pkg.go.dev to support showing the standard library documentation at the tip of the dev.fuzz branch. For example, https://pkg.go.dev/std@dev.fuzz

**Comment by julieqiu** [comment]
https://pkg.go.dev/std@dev.fuzz can now be viewed at pkg.go.dev.
