### ISSUE TITLE
x/pkgsite: false-positive deprecation warning when the "Deprecated:" sentence does not start a paragraph

### ISSUE THREAD

**Issue by bcmills** [golang/go#46913]
### What is the URL of the page with the issue?
 
https://beta.pkg.go.dev/go/importer#ForCompiler
 
 
### What is your user agent?
 
Mozilla/5.0 (X11; CrOS x86_64 13904.55.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.102 Safari/537.36 
 
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/5200974/123319841-f741d300-d4fe-11eb-9775-873b5a54ba62.png)
 
 
 
### What did you do?
 
Attempt to read documentation for `importer.ForCompiler`. 
 
 
### What did you expect to see?

https://golang.org/wiki/Deprecated says (emphasis mine):
> To signal that an identifier should not be used, add **a paragraph to its doc comment that begins with** `Deprecated:` followed by some information about the deprecation, and a recommendation on what to use instead, if applicable.
 
The line that begins with `Deprecated:` for `importer.ForCompiler` is not at the start of its paragraph, so I expect it to apply only to the behavior described  in that paragraph and not to the `ForCompiler` function overall.
 

### What did you see instead?

The entire function is prominently marked as deprecated in the pkgsite UI.

**Comment by jba** [comment]
Whoops!

**Comment by findleyr** [comment]
I was just confused by this as well (and was about halfway through filing an identical issue before I thought to search).

For reference, the heuristic used by staticcheck is here:
https://github.com/dominikh/go-tools/blob/d694aadcb1f50c2d8ac0a1dd06217ebb9f654764/analysis/facts/deprecated.go#L31
