### ISSUE TITLE
net/http: suggestion employ `HandlerFunc` instead of `func(ResponseWriter, *Request)`

### ISSUE THREAD

**Issue by vituchon** [golang/go#46926]
Given the function's signature at https://github.com/golang/go/blob/37f9a8f69d6299783eac8848d87e27eb563500ac/src/net/http/server.go#L2473 the second parameter is of type `func(ResponseWriter, *Request)` that is defined as a type in the same source file, like this https://github.com/golang/go/blob/37f9a8f69d6299783eac8848d87e27eb563500ac/src/net/http/server.go#L2042

I guess you may (re)use the same definition instead, leading to write something like
`func (mux *ServeMux) HandleFunc(pattern string, handler HandlerFunc) {`

I was wondering is this is for any specific reason, if i miss something, please excuse me.

Victor.

**Comment by mvdan** [comment]
This would technically be a breaking change, because `HandlerFunc` is a named type. For example, the following line of Go would break with that change:

```
var f func(pattern string, handler func(ResponseWriter, *Request)) = mux.HandleFunc
```

The change would be a no-op of HandlerFunc was a type alias, but it can't be, because the point of it is that it has a method.

**Comment by vituchon** [comment]
i don't know where that line is, but i would guess that you may also replace that line; i mean, if you have already "trap" the function signature into a type (`HandlerFunc`), ¿why don't use that type instead of writing the entire signature again?

**Comment by mvdan** [comment]
I'm not saying that line exists in a particular place; I'm saying it's an example of user code that would break. If the code requires to be changed, usually that's what you call a breaking change.

**Comment by ianlancetaylor** [comment]
We can't make this change, so closing this issue.

For questions in general, please see https://golang.org/wiki/Questions.

**Comment by vituchon** [comment]
I see tipification as a "good" sign. 
I doubt that any client will complaint about using types. (in your example, why you don't use `mux.HandleFunc` directly)
I don't see it as a breaking change, i see as an improvement that, perpahs, come late.

**Comment by vituchon** [comment]
@ianlancetaylor why you can't make this change?

**Comment by ianlancetaylor** [comment]
@vituchon As @mvdan explained, it would break the Go 1 compatibility guarantee (https://golang.org/doc/go1compat).

**Comment by vituchon** [comment]
so i'm assuming that this works like in Pascal, where an anonymous type (a type without a given identifier) like `func(ResponseWriter, *Request)` is different from a named type with the same definition. ¿Right? 

So perpahps the root of the problem strives from there... i'm not saying that is good or bad, no.. i'm trying to understand how things work.

**Comment by ianlancetaylor** [comment]
For questions about how the language works, please use a forum.  See https://golang.org/wiki/Questions.  Thanks.

Yes, in Go, a defined type is different than the type with which it is defined.  https://golang.org/ref/spec#Type_identity

**Comment by vituchon** [comment]
Got it, thanks for bearing with me.
