### ISSUE TITLE
access: give cuonglm access to github groups

### ISSUE THREAD

**Issue by cuonglm** [golang/go#46920]
I'm asking for Assignees and Editors roles per @ALTree['s suggestion]:(https://github.com/golang/go/issues/46907#issuecomment-868289753)

- https://github.com/orgs/golang/teams/go-assignees
- https://github.com/orgs/golang/teams/go-approvers

So I can collaborate with others better (working on issues, prevent duplicated works ...).

per https://github.com/golang/go/wiki/GithubAccess

cc @ALTree @mdempsky @dmitshur

**Comment by ALTree** [comment]
CC @golang/release

**Comment by mdempsky** [comment]
I support this. According to https://github.com/golang/go/graphs/contributors, @cuonglm is the 31st most frequent committer to the Go project. I believe he's also been a Gerrit approver for over a year now.

I think it's only fair that we can assign issues to him too. :)

**Comment by toothrot** [comment]
Done! Thank you for your many contributions.
