### ISSUE TITLE
x/website: "seeker can't seek" error

### ISSUE THREAD

**Issue by 89z** [golang/go#46933]
~~~
PS C:\> curl https://golang.org/src/go.mod
seeker can't seek
PS C:\> curl -I https://golang.org/src/go.mod
HTTP/2 500
~~~

**Comment by 89z** [comment]
https://github.com/golang/go/issues/46809

**Comment by dmitshur** [comment]
Thanks for reporting. This is the same as #46809. The fix hasn't been deployed yet. That should happen sometime, though maybe not as soon due to #46934.

**Comment by 89z** [comment]
I think this is fixed
