### ISSUE TITLE
Question: how to speed compiling when using `go build -mod=vendor`

### ISSUE THREAD

**Issue by jianzhangbjz** [golang/go#46944]
### What version of Go are you using (`go version`)?

<pre>
$ go version
[cloud-user@preserve-olm-env ~]$ go version
go version go1.16.5 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
[cloud-user@preserve-olm-env ~]$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/data/jian/go/bin"
GOCACHE="/home/cloud-user/.cache/go-build"
GOENV="/home/cloud-user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/data/goproject/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/data/goproject"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/data/jian/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/data/jian/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1279982106=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I want to use the dependency packages with specific versions, and don't want to depend on the Network. So, we use `go build -mod=vendor ` for compiling. To save building time, we want to cache the binary **so that it only rebuilds when the source is newer.**

### What did you expect to see?

When using `go build` for building, it saves the `mod cache` ( `*.a` files) to the `$GOPATH/pkg/mod`. We can reuse this cache and rebuilding the binary faster.
But, when using `go build -mod=vendor`, it works/saves the cache( `*.a` files) to a random temporary(such as `/tmp/go-build1307922253/`) `WORK` folder, and remove it once compiling done. So, that means, it will never reuse the `mod cache` when running `go build -mod=vendor` for compiling. Is it right?
So, how to utilize the `mod cache` to speed the compiling when using the `go build -mod=vendor`? Much appreciate!

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by jianzhangbjz** [comment]
Thanks for your info, ask it in Slack: https://gophers.slack.com/archives/C029RQSEE/p1624784324040700

**Comment by jianzhangbjz** [comment]
Asked it again here: https://gophers.slack.com/archives/C9BMAAFFB/p1624841383206400

**Comment by jianzhangbjz** [comment]
Reopen it, since I thought this is a prroblem we should fix, at least a feature request.

**Comment by ianlancetaylor** [comment]
I don't think you are correctly describing how the system works.  Please use a forum, as suggested above, to see how the system works, and then file an issue describing specific changes to make.

In particular the module cache, the build cache, and the temporary work directory are all different things.
