### ISSUE TITLE
cmd/compile: internal error with variadic calls with a wrong number of arguments

### ISSUE THREAD

**Issue by gazerro** [golang/go#46957]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/marco/Library/Caches/go-build"
GOENV="/Users/marco/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/marco/go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/marco/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z9/xrln_qks56jbzxjbhs04fpm80000gn/T/go-build178768119=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Compile the following program

```
package main

func f(a int, b ...int) {}

func main() {
	f(nil...)
}
```

https://play.golang.org/p/q2VqTTvsay9

### What did you expect to see?

```
./prog.go:6:3: not enough arguments in call to f
	have (...int)
	want (int, ...int)
```

### What did you see instead?

```
./prog.go:6:3: internal compiler error: bad type for ... argument: nil

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
```

The same error occurs using `interface{}(nil)` instead of the predeclared identifier `nil`:

```
package main

func f(a int, b ...int) {}

func main() {
	f(interface{}(nil)...)
}
```

```
./prog.go:6:3: internal compiler error: bad type for ... argument: interface {}
```

**Comment by gazerro** [comment]
The internal error also occurs with any value not assignable to `[]T`. For example:

```
package main

func f(a int, b ...int) {}

func main() {
	m := map[string]string{}
	f(m...)
}
```
```
./prog.go:7:3: internal compiler error: bad type for ... argument: map[string]string
```

**Comment by dmitshur** [comment]
Thanks for reporting.

From brief testing, it looks like this issue is new to Go 1.16, and it still happens at tip. CC @mdempsky, @cherrymui.

**Comment by mdempsky** [comment]
Thanks for the report. /cc @cuonglm 

@dmitshur Is this backport eligible? The crash is unfortunate, but if it only affects invalid code, I'm inclined to think no. And the new typechecker in Go 1.18 should make this issue go away anyway.
