### ISSUE TITLE
x/tools/gopls: incorrect document outline for structs

### ISSUE THREAD

**Issue by RaymondNY** [golang/go#46958]
VS Code Version: 1.57.1
OS Version: win10
Reproduce:
![image](https://user-images.githubusercontent.com/18241498/123358650-66223900-d59e-11eb-90bf-9152095e65e7.png)
![image](https://user-images.githubusercontent.com/18241498/123358658-69b5c000-d59e-11eb-9948-ea5d8616c272.png)

Some struct, func should be visible in the outline.Only one extension is go

**Comment by findleyr** [comment]
Presumably this is due to AST trimming. I'll take a look.
