### ISSUE TITLE
How to use gccgo to test GO benchmarks?

### ISSUE THREAD

**Issue by hailingluo** [golang/go#46954]
Hi all,
I have a question about gccgo. I want to test the performance between gccgo and go in GO benchmark. For now, I have got some preliminary results in some benchmark such image/encoding/math. But I cannot run the benchmarks in the directory of runtime by using go test (which go is compiled by gccgo), any ideas or anyone else has tried this before? Thanks.

Best regards,
Luo.

**Comment by mdlayher** [comment]
Please see https://github.com/golang/go/wiki/Questions.
