### ISSUE TITLE
Thread-safe operation with Stdout and Stderr (exec. Cmd)

### ISSUE THREAD

**Issue by LazarenkoA** [golang/go#46952]
### What version of Go are you using (`go version`)?

<pre>
go version go1.16.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
I don't know

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\lazarenko.an\AppData\Local\go-build
set GOENV=C:\Users\lazarenko.an\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\GoMy\src\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\GoMy\src
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\GoMy\src\go1.16.4
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\GoMy\src\go1.16.4\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.4
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\lazarenko.an\IdeaProjects\testStdOut\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\LAZARE~1.AN\AppData\Local\Temp\go-build1433502750=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
The task when executing a command that can run for a long time periodically reads stdout and stderr,  I did it like this (code for example)
https://play.golang.org/p/MAH9dvrWS4K
But when running similar code on `go test-race` tests, I get a race in these places:
```
WARNING: DATA RACE
Read at 0x00c0002164a8 by goroutine 71:
  strings.(*Builder).String()
      D:/GoMy/src/go1.16.4/src/strings/builder.go:48 +0x344
  runner.(*runner).invoke()
      D:/WorkGIT/MIRS_STORAGE/GO/runner/runner.go:261 +0x355

Previous write at 0x00c0002164a8 by goroutine 77:
  strings.(*Builder).Write()
      D:/GoMy/src/go1.16.4/src/strings/builder.go:90 +0x149
  io.copyBuffer()
      D:/GoMy/src/go1.16.4/src/io/io.go:425 +0x2be
  io.Copy()
      D:/GoMy/src/go1.16.4/src/io/io.go:382 +0x84
  os/exec.(*Cmd).writerDescriptor.func1()
      D:/GoMy/src/go1.16.4/src/os/exec/exec.go:311 +0x51
  os/exec.(*Cmd).Start.func1()
      D:/GoMy/src/go1.16.4/src/os/exec/exec.go:441 +0x3b

```
<details><summary><code>D:/GoMy/src/go1.16.4/src/strings/builder.go:48</code> </summary>
<pre>
func (b *Builder) String() string {
	return *(*string)(unsafe.Pointer(&b.buf))
}
</pre>
</details>

<details><summary><code>D:/GoMy/src/go1.16.4/src/strings/builder.go:90</code> </summary>
<pre>
func (b *Builder) Write(p []byte) (int, error) {
	b.copyCheck()
	b.buf = append(b.buf, p...)
	return len(p), nil
}
</pre>
</details>

### What did you expect to see?
I want to get the code without race errors

### What did you see instead?
race

tell me is this a error or is everyone knows that this way of working with `Stdout` and `Stderr` is not thread-safe? which way is thread-safe?

**Comment by D1CED** [comment]
Thread safety depends on the Reader/Writer implementations you are providing exec.Cmd.

https://golang.org/pkg/os/exec/#Cmd

> Otherwise, during the execution of the command a separate goroutine
> reads from the process over a pipe and delivers that data to the
> corresponding Writer.

So it is not safe to use the `strings.Builder.String()` method on line 84.
This is a write-write conflict actually as the `Cmd` writes and the `String()` writes.

You better use a thread safe buffer or at least a thread safety wrapper.

**Comment by LazarenkoA** [comment]
" thread safe buffer"
which buffer is thread-safe?
