### ISSUE TITLE
net: TestCVE202133195 fails if /etc/resolv.conf specifies ndots larger than 3

### ISSUE THREAD

**Issue by shawn-xdji** [golang/go#46955]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version devel go1.17-c95464f0ea Sun Jun 27 05:06:30 2021 +0000 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Reproducible with go1.16.5

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
</pre></details>

### What did you do?

In /etc/resolv.conf there is "options ndots:5", then ./make.bash failed with the following error.

--- FAIL: TestCVE202133195 (0.00s)
    dnsclient_unix_test.go:1925: Resolver.LookupSRV returned unexpected error, got "lookup golang.org: SRV target is invalid", want "lookup golang.org: SRV header name is invalid"
    dnsclient_unix_test.go:1929: LookupSRV returned unexpected error, got "lookup golang.org: SRV target is invalid", want "lookup golang.org: SRV header name is invalid"
FAIL
FAIL	net	5.458s

**Comment by dmitshur** [comment]
CC @rolandshoemaker.

**Comment by shawn-xdji** [comment]
@gopherbot please backport to 1.16

**Comment by shawn-xdji** [comment]
@gopherbot please backport to 1.15
