### ISSUE TITLE
image/gif: typo in type blockReader struct docs

### ISSUE THREAD

**Issue by hiroakis** [golang/go#46967]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sano/Library/Caches/go-build"
GOENV="/Users/sano/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/sano/work/golang/1.15/cache2"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/sano/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/Cellar/go/1.16/libexec"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8n/zq1f67bx6z733nj8f0s2w10c0000gr/T/go-build3640241653=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Read the source code at github.com/golang/go/src/image/gif/reader.go

### What did you expect to see?

```
// blockReader parses the block structure of GIF image data, which comprises
// (n, (n bytes)) blocks, with 1 <= n <= 255. It is the reader given to the
// LZW decoder, which is thus immune to the blocking. After the LZW decoder
// completes, there will be a 0-byte block remaining (0, ()), which is
// consumed when checking that the blockReader is exhausted.
//
// To avoid the allocation of a bufio.Reader for the lzw Reader, blockReader
// implements io.ReadByte and buffers blocks into the decoder's "tmp" buffer.
```

### What did you see instead?

```
// blockReader parses the block structure of GIF image data, which comprises
// (n, (n bytes)) blocks, with 1 <= n <= 255. It is the reader given to the
// LZW decoder, which is thus immune to the blocking. After the LZW decoder
// completes, there will be a 0-byte block remaining (0, ()), which is
// consumed when checking that the blockReader is exhausted.
//
// To avoid the allocation of a bufio.Reader for the lzw Reader, blockReader
// implements io.ByteReader and buffers blocks into the decoder's "tmp" buffer.
```

**Comment by ianlancetaylor** [comment]
I'm not sure what is going on here but we just got at least three changes fixing this problem.  I'm going to try to go with the one that arrived first.

**Comment by hiroakis** [comment]
@ianlancetaylor I'm sorry for that. I could not find any issue, so I opened this issue and sent a change above. Should I abandon my change?

**Comment by ianlancetaylor** [comment]
It's fine, I will take care of it.  Thanks for working to make Go better.

I'm curious, though: is there some reason that we got three different fixes for the same problem at about the same time?

**Comment by hiroakis** [comment]
A Japanese Gopher, @tenntenn tweeted this typo https://twitter.com/tenntenn/status/1409887563041607682 . This is the reason why some Japanese submitted the same changes. I guess.

**Comment by ianlancetaylor** [comment]
Thanks!
