### ISSUE TITLE
flag provided but not defined: -test.v

### ISSUE THREAD

**Issue by fwhezfwhez** [golang/go#46978]
reopen #46869! 

I've define a new flagSet instance, but question still remains `flag provided but not defined: -test.v`.

However, version go1.12.17 works well when call flag.Parse in package's init function when this package is not main.

Now I use  go1.13.15 and refers to #46869 , til now this flag question still remains.

For some reason, I can't actually acept to run flag.Parse() in main.go.

Most my my dependcy works like

/appname/util/redistool

init.go
```go
func init() {}
	switch config.Mode {
	case "pro":
		RedisPool = newPool("x.x.x.x:6379", "pwdpro", 0)
	case "dev":
		RedisPool = newPool("y.y.y.y:6379", "pwddev", 0)
	default:
		RedisPool = newPool("z.z.z.z:6379", "pwddefault", 0)
	}
}
```

It means, as soon as you import reditool package, the datasource is autu loaded. To use it in this way, I usually call flag.Parse in config/init.go
```
var Mode string
func init() {
    flag.StringVar(&Mode, ......)
    flag.Parse()
}
```

If I just call flag.Parse in main.go, it means all my imports can't load well. because when execute redistool.init, flag is just not parsed yet!

By the way, below case can't run well

config/init.go
```go

var nf = flag.NewFlagSet(os.Args[0], flag.ExitOnError)

func init() {
	nf.StringVar(&(Node.Mode), "mode", "local", "go run main.go -profPort ':6060'")
	nf.Parse(os.Args[1:])
}

```

config/init_test.go
```go
func TestDefault(t *testing.T) {
	fmt.Println(Node.Mode)
}

```

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
