### ISSUE TITLE
os: example shows deprecated function

### ISSUE THREAD

**Issue by eliben** [golang/go#46976]
This is a documentation issue.

One of the examples in the `os` packages shows the usage of the `IsNotExist` function; however, this function's documentation recommends avoiding it in new code:

> This function predates errors.Is. It only supports errors returned by the os package. New code should use errors.Is(err, os.ErrNotExist). 

It seems like the example should be updated to demonstrate the new way of checking for this error instead.

**Comment by ianlancetaylor** [comment]
Hi Eli.  It's not necessary to open an issue for a documentation fix if you are going to send a patch anyhow.  It's OK to just send the patch without an issue.  Thanks.

**Comment by eliben** [comment]
> Hi Eli. It's not necessary to open an issue for a documentation fix if you are going to send a patch anyhow. It's OK to just send the patch without an issue. Thanks.

Thanks Ian, I'll keep this in mind for next time.
