### ISSUE TITLE
[dev.typeparams] incompatible type: cannot use s (variable of type string) as T value

### ISSUE THREAD

**Issue by zllangct** [golang/go#46980]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-6a5f7e8498b7 Tue Jun 29 21:50:53 2021 +0000 windows/amd64
</pre>

### What did you do?

<pre>
package main

func Test[T any]() {
	fn := func(in T) {
		println(in)
	}
	s := "hello world"
	fn(s)
}

func main() {
	Test[string]()
}
</pre>

### What did you expect to see?
<pre>
hello world
</pre>
### What did you see instead?
<pre>
 incompatible type: cannot use s (variable of type string) as T value
</pre>

**Comment by cuonglm** [comment]
This seems working as expected for me per https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#operations-permitted-for-any-type

cc @mdempsky @griesemer @findleyr

**Comment by zllangct** [comment]
> This seems working as expected for me per https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#operations-permitted-for-any-type
> 
> cc @mdempsky @griesemer @findleyr

the same error in go2go:
![20210630173637](https://user-images.githubusercontent.com/8629238/123938778-ffe84c80-d9c9-11eb-9cfe-14716eafaa16.png)

**Comment by cuonglm** [comment]
@zllangct to be clear, what I mean working as expected, mean the error here is expected behavior. You can't assign variable of different type (string) to any type (T).

**Comment by griesemer** [comment]
What @cuonglm said.

What may be confusing you (@zllangct) here is that `Test` is (implicitly) instantiated with the type `string`. But the `Test` function, by itself, doesn't know anything about the type parameter `T`, as its constraint is `any`, and furthermore, `T` is different from the `string` type. Thus, the error message is correct and expected.
