### ISSUE TITLE
Issue while copying the values to pointer values in slices

### ISSUE THREAD

**Issue by parixitsingh** [golang/go#46989]
### What version of Go are you using (`go version`)?

<pre>
$go version go1.15.6 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOOS=windows
GOARCH=amd64

</pre></details>

### What did you do?
https://play.golang.org/p/_9ilwMZxg5p

### What did you expect to see?
Copied all the elements from values slices to pointer values without changing the references

### What did you see instead?
All the elements in the pointer slice are changed to the last value appended.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
