### ISSUE TITLE
misc/swig/callback: unknown warning option '-Wno-lto-type-mismatch'

### ISSUE THREAD

**Issue by josharian** [golang/go#46991]
Running all.bash on my darwin/amd64 system fails:

```
# runtime/cgo
error: unknown warning option '-Wno-lto-type-mismatch'; did you mean '-Wno-selector-type-mismatch'? [-Werror,-Wunknown-warning-option]
FAIL	misc/swig/callback [build failed]
```

Looks like this was recently introduced to fix #46557.

cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
What C compiler are you using?  What version?

**Comment by ianlancetaylor** [comment]
Does https://golang.org/cl/332010 fix the problem?

**Comment by josharian** [comment]
> Does https://golang.org/cl/332010 fix the problem?

Yep!
