### ISSUE TITLE
net: TestCVE202133195 fails if /etc/resolv.conf specifies ndots larger than 3 [1.15 backport]

### ISSUE THREAD

**Issue by dmitshur** [golang/go#46994]
@shawn-xdji requested issue #46955 to be considered for backport to the next 1.15 minor release.

> @gopherbot ple​ase consider this for backport to 1.15, it's a test failure

**Comment by neild** [comment]
[CL 333331](https://golang.org/cl/333331) incorporates this fix on `release-branch.go1.15`.
