### ISSUE TITLE
`go test -parallel=1` executes tests in the same file in parallel (go version go1.16.3 darwin/amd64 - not latest)

### ISSUE THREAD

**Issue by ObiWahn** [golang/go#47009]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

The problem seems to be gone in `go version go1.16.5 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> (output)</summary><br><pre>
$ go env
» go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tipster/Library/Caches/go-build"
GOENV="/Users/tipster/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/tipster/.go/pkg/mod"
GONOPROXY="gitlab.foo.bar,foo.bar/project"
GONOSUMDB="foo.bar,foobar/project"
GOOS="darwin"
GOPATH="/Users/tipster/.go"
GOPRIVATE="gitlab.foo.bar,gitlab.foo.bar/project"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="/usr/local/bin/pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ss/9z3hrcx106dbzdd1y3_jblxh0000gp/T/go-build2531569612=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

**command:**
`go test -v ./repository/tests/... -parallel=1 -tags=integration`

**more context:**
I have created a `custom test main` as shown below. When executing my tests they are executed in parallel. The tests are in the same package (even file) and I do not use `.Parallel()` and pass `-parallel=1` to `go test`

<details><summary><code>custom test main</code> (go code)</summary><br><pre>
import (
	"context"
	"os"
	"testing"

	goredis "github.com/go-redis/redis"

	"gitlab.foo.bar/project/internal/app/risk/repository"
	"gitlab.foo.bat/internal/app/risk/repository/redis"
        "gitlab.foo.bar/project/internal/pkg/util"
	redisContainer "gitlab.foo.bar/project/internal/pkg/dockertest/redis"
)

var (
	testRepo repository.Repository
)

func TestMain(m *testing.M) {
	os.Exit(testRepository(m))
}

func testRepository(m *testing.M) int {
	endpoint, terminate, err := redisContainer.Start()

	client := goredis.NewClient(&goredis.Options{
		Addr: endpoint,
	})

	if err != nil {
		util.Panic("unable to create go redis client", err)
	}

	defer terminate(context.Background())
	defer client.Close()

	testRepo = redis.NewRepository(client, nil)

	return m.Run()
}
</pre></details>

When my test cases, that are in the same file, are run without `mutex` they execute concurrently. This leads to invalid stats in the RedisDB, that I use my for my integration tests. When I use a `mutex` as shown below the tests execute sequentially as expected.

<details><summary><code>tests with mutex</code> (go code)</summary><br><pre>
var m sync.Mutex
func TestA(t *testing.T) {
	m.Lock()
	defer m.Unlock()
	time.Sleep(time.Second * 3)
}
func TestB(t *testing.T) {
	m.Lock()
	defer m.Unlock()
	time.Sleep(time.Second * 3)
}
</pre></details>

### What did you expect to see?

```
=== RUN   TestRepository_StoreLoadEventData
--- PASS: TestRepository_StoreLoadEventData (3.02s)
=== RUN   TestRepository_StoreEventDataCheckEventIsFound
--- PASS: TestRepository_StoreEventDataCheckEventIsFound (3.01s)
```

### What did you see instead?

```
=== RUN   TestRepository_StoreLoadEventData
--- PASS: TestRepository_StoreLoadEventData (3.02s)
=== RUN   TestRepository_StoreEventDataCheckEventIsFound
--- PASS: TestRepository_StoreEventDataCheckEventIsFound (0.03s)
```

**Comment by adamluzsi** [comment]
The mentioned `mutext` is a `sync.Mutex` kept in a global variable within the test package scope.

example:
```go
var m sync.Mutex

func TestA(t *testing.T) {
	m.Lock()
	defer m.Unlock()
	// ...
}

func TestB(t *testing.T) {
	m.Lock()
	defer m.Unlock()
	// ...
}
```

**Comment by ObiWahn** [comment]
Something else caused the behavior ... sorry for the noise!
