### ISSUE TITLE
sort.SearchStrings search string, the index position is wrong

### ISSUE THREAD

**Issue by peibinzhu** [golang/go#47002]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Peter\AppData\Local\go-build
set GOENV=C:\Users\Peter\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Peter\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Peter\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.4
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Peter\AppData\Local\Temp\go-build3227295333=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Executed following program:
```go
package main

import (
	"fmt"
	"sort"
)

func main() {
	strArr := []string{"a", "b", "1", "2"}
	sort.Strings(strArr)
	fmt.Println(strArr)
	n := sort.SearchStrings(strArr, "5")
	fmt.Println(n)
}

```

Please note that in the above program, I provided a string number "5" that does not exist in the slice to search for the string. The returned index is not a new index, and the index position is not correct, which is very strange. I hope to pay attention to it.

### What did you expect to see?

4
I would expect 4 as output because when the string is not found in slice then the SearchString returns the length of the slice.

### What did you see instead?
2

**Comment by randall77** [comment]
`2` is the correct answer.
The sorted order is `1 2 a b`. `5` would be inserted at index 2 in that list.

Please refer to https://github.com/golang/go/wiki/Questions for good places to ask questions like these.
