### ISSUE TITLE
net/http: TestCancelRequestWhenSharingConnection can cause port exhaustion, leading to frequent test failures with "Only one usage of each socket address" on windows-amd64-longtest

### ISSUE THREAD

**Issue by bcmills** [golang/go#47016]
### What version of Go are you using?

`release-branch.go1.15`

### Does this issue reproduce with the latest release?

No.

### What did you expect to see?

Tests on the current release branches (`release-branch.go1.15` and `release-branch.go1.16`) consistently passing, especially for all [first class ports](https://github.com/golang/go/wiki/PortingPolicy#first-class-ports).

### What did you see instead?

Tests on the `windows-amd64-longtest` builder started failing intermittently in March, got better for a while in May, and are now failing in `net/http` on just about every run (https://build.golang.org/?repo=&branch=release-branch.go1.15#short):
![image](https://user-images.githubusercontent.com/5200974/124178221-519ede80-da7f-11eb-883e-701a7541d77c.png)

The failure mode consists of many `Only one usage of each socket address` errors (https://build.golang.org/log/30a479e652cc31796c8d900ab0494ffff5765266), sometimes accompanied by a test deadlock or timeout (https://build.golang.org/log/3ff9e1b80ee03390ebb171468f0fb00ceb23795d).

These failures result in TryBot / SlowBot failures on the release branch for unrelated backports (https://golang.org/cl/332330). Since the builders are consistently broken, there is a substantial risk that these failures will cause some other regression on this branch to go unnoticed.

CC @neild @golang/release

**Comment by cagedmantis** [comment]
I believe the work to try and resolve this issue has been previously tracked in #45358.

**Comment by bcmills** [comment]
> I believe the work to try and resolve this issue has been previously tracked in #45358.

Yeah, it's closely related.

I actually tried to find that issue before filing this one, but it didn't turn up in my search results — the problem described in the issue title seems to have been addressed, and the string in the current error message isn't mentioned in that issue at all. 😕

**Comment by dmitshur** [comment]
This flaky failure continues to be an issue but we're not going to block Go 1.15.14 on it. Moving to next milestone.

**Comment by cagedmantis** [comment]
As with the previous milestone: This flaky failure continues to be an issue but we're not going to block Go 1.15.15 on it. Moving to next milestone.

**Comment by cagedmantis** [comment]
We've moved it back to the Go1.15.15 milestone since it is actively blocking the release.

**Comment by cagedmantis** [comment]
@neild Since we think this issue exists on master (just not as likely to show up), show we create backport issues (and cls) from this issue? We would be backporting golang.org/cl/339594.

**Comment by neild** [comment]
@gopherbot please open backport issues.

**Comment by dmitshur** [comment]
Since there are dedicated backport issues, retargeted this issue to 1.17.

Closing as fixed by [CL 339594](https://golang.org/cl/339594).
