### ISSUE TITLE
Marking imports as required

### ISSUE THREAD

**Issue by MMulthaupt** [golang/go#47025]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

```
import "github.com/go-sql-driver/mysql"

f̶u̶n̶c̶ ̶g̶e̶t̶M̶y̶S̶Q̶L̶C̶o̶n̶f̶i̶g̶(̶)̶ ̶*̶m̶y̶s̶q̶l̶.̶C̶o̶n̶f̶i̶g̶ ̶{̶
	̶c̶o̶n̶f̶ ̶:̶=̶ ̶m̶y̶s̶q̶l̶.̶N̶e̶w̶C̶o̶n̶f̶i̶g̶(̶)̶
	̶/̶/̶ ̶.̶.̶.̶
	r̶e̶t̶u̶r̶n̶ ̶c̶o̶n̶f̶
̶}̶

func getMySQLDataSourceName() string {
	// return some constant string
}
```

Ctrl+S

### What did you expect to see?

`import "github.com/go-sql-driver/mysql"`

should become

`import _ "github.com/go-sql-driver/mysql"`

because the package contains an `init()` function.

### What did you see instead?

`import "github.com/go-sql-driver/mysql"`

is removed, dropping the driver from the build leading to runtime error.

### Additional comment

I'm not sure what's the best way to deal with this. I could create a .go file within the package which only contains the blank import, but that doesn't feel like something which is going to be self-explanatory to other programmers. Another thought is adding a way to mark imports as required to the spec. e.g.:

`import ! "github.com/go-sql-driver/mysql"`
`import ! ms "github.com/go-sql-driver/mysql"`

**Comment by ianlancetaylor** [comment]
I assume that you are using some tool that runs the goimports program on file save.  It's a feature of goimports that it removes imports that are no longer required, just as it adds imports that become required.  To tell goimports that an import is required, write

    import _ "github.com/go-sql-driver/mysql"

That is, add the `_` yourself.  There's no need to introduce any additional syntax.
