### ISSUE TITLE
cmd/go: suggestion to fail to build, or emit warning, on unused build tags

### ISSUE THREAD

**Issue by dans-stuff** [golang/go#47020]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 darwin/arm64
</pre>

### What did you expect to see?
I added a build tag (specifically `go build -tags lambda.norpc`), which is a build tag honored by https://github.com/aws/aws-lambda-go

However, it just so happened that the build tag was introduced in a version later than the version I had pinned. My go mod had v1.13, the build tag was introduced in v1.18

This was incredibly difficult to discover, therefor I am suggesting that passing a build tag should produce an error if that build tag is not found anywhere. At least a warning should be displayed, if not failing the build entirely.

**Comment by ianlancetaylor** [comment]
I think this would be fairly difficult in practice.  For example there is a standard library build tag `osusergo`, used only by the "os/user" package.  Some people routinely build with `go build -tags=osusergo`.  They don't want the build to fail just because the specific program they happen to be building doesn't import the "os/user" package.

**Comment by dans-stuff** [comment]
@ianlancetaylor Good to know! Perhaps a list of known common build tags could be omitted from the check? Normally I feel something like this would be in `go vet` but as it's a build argument, there's no way to include it there.

Conversely, if the tags are not found during normal compilation, a scan could be performed of all relevant source codes - all of stdlib, all of vendor - and if it is still not found that could be cause for a build failure? The problem you mentioned would still exist but in much rarer cases, perhaps rare enough that it is unlikely to have happened.

**Comment by seankhliao** [comment]
Doesn't seem to be feasible.
