### ISSUE TITLE
cmd/pprof: TestDisasm fails on raspbian

### ISSUE THREAD

**Issue by 68CodingMonkeys** [golang/go#47024]
#### What did you do?

1. git clone https://go.googlesource.com/go goroot
2. cd goroot/src
3. ./all.bash

#### What did you expect to see?

ALL TESTS PASSED

#### What did you see instead?

:
ok  	cmd/objdump	84.223s
ok  	cmd/pack	27.747s
--- FAIL: TestDisasm (21.25s)
    pprof_test.go:125: pprof disasm got Total: 160ms
         want contains "ROUTINE ======================== main.main"
FAIL
FAIL	cmd/pprof	62.966s
ok  	cmd/trace	0.536s
ok  	cmd/vet	100.480s
:

#### Does this issue reproduce with the latest release (go1.16.5)?

Maybe. Downloaded repo on 2 July of 2021. Cant tell until the build finishes.

FYI: apt-get gave me 11.1 but it stuggled being to old, so I decided to compile
latest and greatest on my own with official doc at https://golang.org/doc/install/source

I disabled the test by patching and  ignoring linux / arm, what impact has this?

#### System details

```
go version go1.11.6 linux/arm
GOARCH="arm"
GOBIN=""
GOCACHE="/home/ethereum/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ethereum/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.11"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.11/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version go1.11.6 linux/arm
GOROOT/bin/go tool compile -V: compile version go1.11.6
uname -sr: Linux 5.10.17-v7l+
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
/lib/arm-linux-gnueabihf/libc.so.6: GNU C Library (Debian GLIBC 2.28-10+rpi1) stable release version 2.28.
gdb --version: GNU gdb (Raspbian 8.2.1-2) 8.2.1
```

**Comment by cherrymui** [comment]
Looks similar to #56574, which is fixed in Go 1.20 onward. Closing for now. Feel free to reopen if this still happens. Thanks.
