### ISSUE TITLE
[bug report] flag provided but not defined: -test.v

### ISSUE THREAD

**Issue by fwhezfwhez** [golang/go#47047]
#46869 

I understand why it happens but still think this is a bug, not upgrading.

Because 

1. In go1.12.17 below versions, It's ok to call flag.Parse() in init function. Thus, our group dependency dir-structure is like
```
config
  |  - init.go
dep
  | - redistool
             | - init.gp
  | - db
        | -init.go
```

app global field `Mode` is seted in config/init.go
```go
func init() {
    flag.StringVar(&Mode)
    flag.Parse()
|
```

While redistool, db 's  `init.go` is just import config package like

```go
import "config"
func init() {
       Pool = newRedisPool(config.Redis.URL, config.Redis.Pw)
}
```

I can't just do all flag.Parse in main.go. Because while I import redistool, the redistool.init func has been executed, and at this time , config has not been parsed yet. 

This upgrading make all our dependcy can't use any more. It's a breaking change.

If it can't be solved, I guess I wll mark flag desperated and use system env to replace it.

By the way, this bug also will change style of doing testcase.

In the old version ,I just import my datasource package. It's auto loaded because it has it's init.

Now, I must do all init operations in test function,which is disgusting!

**Comment by seankhliao** [comment]
As we've said before, this is working as intended
