### ISSUE TITLE
encoding/json: custom type unmarshaling

### ISSUE THREAD

**Issue by imacks** [golang/go#47078]
### What version of Go are you using (`go version`)?

<pre>
$ go 1.16.5

</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

I have a slightly non-spec json input to parse:

```
{
  "foo": NaN
}
```

I tried unmarshaling to json.RawMessage, but can't go past json.Unmarshal. The error was thrown by the checkValid func.

### What did you expect to see?

This is similar to issue #3480. But since NaN is not quoted, the parser dismiss it as invalid json and never get to the custom UnmarshalJSON.

### What did you see instead?

Error saying cannot parse at 'N'.

This limitation also apply to things like Inf, 0x1234, etc. It would be great if there is an option to relax validation so that it can tolerate unquoted values, with the understanding that these values will be handled by custom unmarshalers. Obviously, the parser should return error if such values contain reserved chars like ,  : {} [].

**Comment by mknyszek** [comment]
I think `NaN` might be a lost cause (see #3480 and #25721), at least in the current `encoding/json` API. Closing this issue. Please feel free to comment about reopening if you think there's something new not captured in those conversations that you'd like to bring up about this, though.

**Comment by imacks** [comment]
Wow tks for the prompt response. I may be mistaken, but the 2 issues you mentioned talked about making the parser recognize specific keywords such as NaN, Inf, etc., which is not a good idea imo as it goes against the JSON spec.

Here, I am saying that the parser should not be too eager to throw an error when it read an invalid **value**. For example, the parser will error out at `x` when I want to be able to unmarshal `{"foo":0xBEEF}`, even if I am unmarshaling to `map[string]json.RawMessage`. My idea is that so long as we assume that a non-string value cannot contain any reserved character , [ ] { } : " and we're unmarshaling that value to json.RawMessage, the parser can simply assign without validation and continue. This gives the user a way to handle non-JSON spec values further down the line.

Since the proposed will change the parser's current behavior, maybe there can be a `x/json` package for this?

**Comment by dolmen** [comment]
This is just NOT JSON. Don't use `encoding/json` to parse that input.
