### ISSUE TITLE
io/fs: document ReadDirFile io.EOF implementation requirements more precisely

### ISSUE THREAD

**Issue by mknyszek** [golang/go#47086]
Splintering out from a discussion in #47062, it's probably worth pointing out that like an `io.Reader`, an `fs.ReadDirFile`'s `ReadDir` should return only an `io.EOF`, and not anything wrapping it. Code in `testing/fstest` already depends on this behavior and assumes it for a correct implementation.

Alternatively, because this API is relatively new, it might still be possible to relax it to allow for wrapping. However, since it's already been almost one full release and `io.EOF` is already used a sentinel in other APIs, it doesn't seem worth it to break the pattern.

**Comment by neild** [comment]
The `fs.ReadDirFile` interface is new, but `"*os/File".ReadDir` is old and returns an `io.EOF` sentinel without wrapping. Keeping the requirement that `io.EOF` be used without wrapping seems simplest.
