### ISSUE TITLE
misc/wasm: non-backwards compatible change in wasm_exec.js file

### ISSUE THREAD

**Issue by gazerro** [golang/go#47082]
Commit 862ddb3 made the `misc/wasm/wasm_exec.js` file incompatible with Wasm files compiled with version 1.16 or earlier. Executing a Wasm file compiled with Go 1.16 or earlier, using the latest `wasm_exec.js` file, causes the following browser error:

```
Uncaught (in promise) LinkError: import object field 'runtime.walltime1' is not a Function
```

There is no backwards compatibility guarantee for Wasm and even if there was, I think this change would not fall under this guarantee.

However, in order to run a Go program, compiled to WebAssembly, in the browser you should use one version or the other depending on the version of the compiler.

This also means that anyone distributing the program source code should provide both versions of the `misc/wasm/wasm_exec.js` file and document which version to use.

Also, those starting to experiment with WebAssembly may get the latest version of the `misc/wasm/wasm_exec.js` file from the Go repository but compiling with an older version of the compiler would result in error.

**Comment by lhl2617** [comment]
WASM support IIRC is still not stable, see https://github.com/golang/go/wiki/WebAssembly

> Also, those starting to experiment with WebAssembly may get the latest version of the misc/wasm/wasm_exec.js file from the Go repository but compiling with an older version of the compiler would result in error.

https://github.com/golang/go/wiki/WebAssembly advices to use 
```bash
$ cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" 
```
to obtain the file.

**Comment by mknyszek** [comment]
FWIW, I don't think we generally provide the expectation that internals between releases be compatible. I think this situation is (loosely) analogous to how even if you have a Go DLL, you need everything to be the same Go version -- everything needs to line up. In this case `wasm_exec.js` is just another toolchain artifact, albeit one that's always the same for the same Go version.

In this case, I think it's a failing of packaging the output. Perhaps `go build` should also copy in the correct `wasm_exec.js` file to the output directory, or package the output differently?

**Comment by mknyszek** [comment]
CC @neelance @cherrymui via https://dev.golang.org/owners

**Comment by dmitshur** [comment]
I agree that this is working as intended. Having `go build` copy `wasm_exec.js` may be reasonable behavior, but I'm not sure if the special case behavior it'd need would be justified at this point. If there's documentation we can improve to make it more clear that "WebAssembly modules produced by Go 1.x should be used with wasm_exec.js from Go 1.x", we should certainly do that.

I primarily want to add a data point that this isn't new to Go 1.17: WebAssembly support was added in Go 1.11, and the wasm_exec.js file has already changed in ways that are incompatible for some of the major releases since then.

**Comment by cherrymui** [comment]
+1 to @dmitshur that this is working as intended.

Maybe we could print some information about possible version mismatch when link error occurs.

Maybe we could add some version check to wasm_exec.js? Something like exporting a version symbol from the module and check it in the JS? This could be particularly helpful for cases that version mismatch does not result in a link error but a run-time error.
