### ISSUE TITLE
How to add DirName and serial to X509v3 Authority Key Identifier

### ISSUE THREAD

**Issue by weimumu** [golang/go#47096]
using crypto/x509.go i get the cert like 
![image](https://user-images.githubusercontent.com/20694989/124933258-54c53c00-e036-11eb-8bd0-70723d482a4d.png)
using openssl and authorityKeyIdentifier = keyid,issuer, i got the cert like
![image](https://user-images.githubusercontent.com/20694989/124933456-7d4d3600-e036-11eb-8456-fbf22b15e8fe.png)
how can i add the field DirName and serial to the cert using crypto/x509.go
i found the source code in crypto/x509.go like 
![image](https://user-images.githubusercontent.com/20694989/124933664-a4a40300-e036-11eb-8783-07539045396e.png)
![image](https://user-images.githubusercontent.com/20694989/124934412-40ce0a00-e037-11eb-9e07-9d00f10a0ac4.png)
i try to add some file to struct but it dose not work:
![image](https://user-images.githubusercontent.com/20694989/124934575-6ce98b00-e037-11eb-87ed-27a4ddb0dd81.png)
![image](https://user-images.githubusercontent.com/20694989/124934598-74109900-e037-11eb-98e1-a2d4d390435d.png)
it go the cert like
![image](https://user-images.githubusercontent.com/20694989/124934642-7d9a0100-e037-11eb-98c7-d3a86b8f6c2e.png)

**Comment by ITbat** [comment]
I have the same problem

**Comment by rayjun** [comment]
i get the same problem too...

**Comment by mdlayher** [comment]
Please see https://github.com/golang/go/wiki/Questions, closing.
