### ISSUE TITLE
encoding/json: support unmarshaling empty string into float

### ISSUE THREAD

**Issue by theWayToAI** [golang/go#47102]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.16.4
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?
mac M1
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```golang
        jsonData := `{"price":"","k":"ws"}`
	var req struct {
		Price     int64   `json:"price,omitempty,string"`
		K      string  `json:"k"`
	}
	err := json.Unmarshal([]byte(jsonData), &req)
	fmt.Println(err)
	fmt.Printf("%+v", req)
```

### What did you expect to see?
Hope that err can be nil.

Hope that encoding/json can add a new tag like omitempty to ignore the parse err when the input string is "". 
This issue has mentioned: https://github.com/golang/go/issues/26800
 In this issue, "" parse to 0 is not good, I agree that.
But hope that can add a new way for us to ignore this kinds of err instead of throwing an error.
Because we can ofter receive the json string like "price":"", it's right format, but it's inconvenient for us to parse it when there are a lot of fields like this, now we have to define all the fields as string, and parse it one by one using strconv.ParseFloat(), and judge every error and ignore the string "" ... 
Thanks.

### What did you see instead?
err: json: invalid use of ,string struct tag, trying to unmarshal "" into int64

**Comment by mvdan** [comment]
You can have custom behavior via UnmarshalJSON methods; I don't see why we should add more options for more edge cases.

**Comment by mknyszek** [comment]
I think I have to agree with @mvdan. I believe this behavior is already achievable with a `UnmarshalJSON` method, either on the req struct, or by defining a new type for your `Price` field (e.g. `type Price float64`). This way you don't need to define the price as a string, just use this type where you need it.

Please comment if we're misunderstanding, but closing for now.
