### ISSUE TITLE
bufio/bufio.go have unuseful comment

### ISSUE THREAD

**Issue by seifchen** [golang/go#47104]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.4 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/root/go"
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY="***"
GONOSUMDB="***"
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE="***"
GOPROXY="****,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/go/src/learn/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1243951107=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
When I read the go source， I found in bufio package have one comment in bufio/bufio.go line 29，
`// Buffered input` 
But I did not found any use. Should delete it.

**Comment by mknyszek** [comment]
Thanks for sending a PR. In general, you do not need to open an issue for a small change like this. You can just send the PR.
