### ISSUE TITLE
types2, go/types: repeated identical external instantiations of the same type will lead to different types

### ISSUE THREAD

**Issue by griesemer** [golang/go#47103]
Reminder issue:

Because we don't have a global type map for external
instantiations, instantiating the same type twice, independently but
with the same type arguments, will result in two different types. This
is not correct. We need to provide some form of context for external
instantiations (which means the importers). This is a separate issue,
not yet addressed.

cc: @findleyr, @danscales @mdempsky

**Comment by CRYPTOENFORCER** [comment]
Let's merge

**Comment by mdempsky** [comment]
Is this an issue with the InstantiateLazy API? That already requires passing in the Checker as an argument, I think to allow deduplication.

**Comment by griesemer** [comment]
No, this is not an issue with InstantiateLazy.

**Comment by griesemer** [comment]
@findleyr Is there anything left to do here now that we have the global `Environment`/`Context`?

**Comment by findleyr** [comment]
I do think we need more testing. Want to repurpose this issue, or shall I open a new one?

**Comment by toothrot** [comment]
@griesemer @findleyr Checking in as this is labeled a release-blocker for Go 1.18. Is there anything left on this issue?

**Comment by findleyr** [comment]
I think we need to also cover repeated instantiations of *Signature types, which are not currently handled. So this should remain as a release blocker.

**Comment by findleyr** [comment]
I am satisfied with this for 1.18. We may add additional testing during the freeze, but this is complete.
