### ISSUE TITLE
misc/wasm: wasm_exec.js does not enable strict mode

### ISSUE THREAD

**Issue by rhysd** [golang/go#47116]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rhysd/Library/Caches/go-build"
GOENV="/Users/rhysd/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/rhysd/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/rhysd/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.5/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/rhysd/.go/src/github.com/rhysd/actionlint/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/98/2tcw8j4157578xpvbqfrwdyr0000gn/T/go-build2360158005=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I'm running Wasm file with browsers which was compiled from Go source in [my project](https://github.com/rhysd/actionlint). It works fine, but when I read `misc/exec_wasm.js`, I noticed that it did not enable [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode). Enabling strict mode means:

### What did you expect to see?

The MDN document says:

> Strict mode makes several changes to normal JavaScript semantics:
>
> 1. Eliminates some JavaScript silent errors by changing them to throw errors.
> 2. Fixes mistakes that make it difficult for JavaScript engines to perform optimizations: strict mode code can sometimes be made to run faster than identical code that's not strict mode.
> 3. Prohibits some syntax likely to be defined in future versions of ECMAScript.

Due to historical reasons, browsers don't enable strict mode by default, but it should be enabled to avoid several JS pitfalls. For example, [TypeScript recommends enabling strict mode](https://www.typescriptlang.org/tsconfig#alwaysStrict).

If this change looks good to maintainers, I could submit a patch for this following [the strict mode migration guide](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode/Transitioning_to_strict_mode).

### What did you see instead?

`misc/exec_wasm.js` did not enable strict mode.

**Comment by seankhliao** [comment]
cc @neelance @cherrymui

**Comment by neelance** [comment]
Strict mode should probably be fine. :+1:

**Comment by rhysd** [comment]
Can I try to make changes for this issue following [the guideline](https://golang.org/doc/contribute)?

**Comment by neelance** [comment]
Sure :)

**Comment by rhysd** [comment]
@neelance I made [change for fixing this issue](https://go-review.googlesource.com/c/go/+/334269). Would you take a look?

**Comment by rhysd** [comment]
@neelance How can we proceed the review? If I need to do something, please let me know. I'll do it.
