### ISSUE TITLE
x/pkgsite: Mess with duplicated module on pkg.go.dev

### ISSUE THREAD

**Issue by nshmyrev** [golang/go#47126]
### What version of Go are you using (`go version`)?

go version go1.16.5 linux/amd64

### Does this issue reproduce with the latest release?

Seems so

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/shmyrev/.cache/go-build"
GOENV="/home/shmyrev/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/shmyrev/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/shmyrev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/shmyrev/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/shmyrev/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2629611323=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

It seems I accidentally created two modules:

https://pkg.go.dev/github.com/alphacep/vosk-api/go

and

https://pkg.go.dev/github.com/alphacep/vosk-api

Now, they block each other from updates.

### What did you see instead?

1. I have a tag v0.3.34 in my repo, this tag has no effect on the https://pkg.go.dev/github.com/alphacep/vosk-api/go
 module

2. I have commit v0.0.0-20210711135442-915dcab59706 but the site still thinks that earlier commit 
v0.0.0-20210711092632-d82052b16804 is the latest one and doesn't update the description doc

3. Wierd things happen when I try to retrieve the package:

<pre>
go get github.com/alphacep/vosk-api/go@v0.3.34
go get: module github.com/alphacep/vosk-api@v0.3.34 found, but does not contain package github.com/alphacep/vosk-api/go
</pre>

Any idea how to fix this all?

Thank you!

**Comment by jamalc** [comment]
You must prefix the version number part of the tag with the name of the subdirectory that is the module root. The `v0.3.34` tag only applies to the module github.com/alphacep/vosk-api. The version tag for github.com/alphacep/vosk-api/go would be `go/v0.3.34`. 

See the doc on [managing module source](https://golang.org/doc/modules/managing-source#repository-scope) for more information.

**Comment by nshmyrev** [comment]
@jamalc Thank you. Is it possible to delete https://pkg.go.dev/github.com/alphacep/vosk-api module?

**Comment by jamalc** [comment]
We can remove that module from pkg.go.dev but it will remain on the proxy. If all tags for github.com/alphacep/vosk-api were published to the go proxy in error consider retracting the github.com/alphacep/vosk-api tags so . Here are the docs on the [retract directive](https://golang.org/ref/mod#go-mod-file-retract).

/cc @julieqiu @jba if there is anything you would add here.

**Comment by nshmyrev** [comment]
Ok, I'll retract tags. Many thanks! Looks good for now.

go/v0.3.34 works perfectly!
