### ISSUE TITLE
path/filepath: IsAbs considers \\host\share as a relative path but should be recognized as an absolute path

### ISSUE THREAD

**Issue by MichaelEischer** [golang/go#47123]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
1.16.5 is the latest release at the moment.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Michael\AppData\Local\go-build
set GOENV=C:\Users\Michael\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Michael\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Michael\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.5
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Michael\AppData\Local\Temp\go-build1869960865=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
```Go
package main

import (
        "fmt"
        "path/filepath"
)

func main() {
        fmt.Println(filepath.IsAbs(`\\host\share`))
        fmt.Println(filepath.IsAbs(`\\host\share\`))
}
```

### What did you expect to see?
```
true
true
```

### What did you see instead?
```
false
true
```

According to https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#unc-paths "UNC paths must always be fully qualified." which suggests that there are no relative UNC paths, and thus `\\host\share` should also be considered as absolute path.

**Comment by odeke-em** [comment]
Thank you for the bug report @MichaelEischer! Kindly cc-ing @alexbrainman @zx2c4 for when y’all have some spare time/cycles.

**Comment by alexbrainman** [comment]
Thank you for bug report @MichaelEischer .

You might have a point with your reasoning, but I am not convinced we should change current behaviour.

Consider this: `\\host\share\` refers to a root directory of that share. What does `\\host\share` reefer to? Same root directory? I am not convinced. `\\host\share` is more like `C:` - it is more like a drive letter.

Also, `path/filepath.IsAbs(path/filepath.Volume(x))` currently always returns false regardless if path is UNC or not. This symmetry will break, if we change `path/filepath.IsAbs` behaviour.

Also let's hear what @mattn has to say about this. He, probably, wrote original code.

Alex

**Comment by MichaelEischer** [comment]
I'd say that `\\host\share` and `\\host\share\` refer to the same directory, as there are no relative UNC paths. But I also agree that `\\host\share` conceptually seems to be more of a volume than a directory. Interestingly `dir \\host\share\` on Windows prints that the directory listing is for volume and directory `\\host\share`, whereas for `dir C:\` I get volume `C:` and directory `C:\`.

Doesn't the IsAbs/Volume asymmetry already apply to `filepath.Rel` after the changes in #41230?
```
filepath.Rel(`C:`, `C:\dir`)
```
doesn't work, whereas
```
filepath.Rel(`\\host\share`, `\\host\share\file.txt`)
```
does.

**Comment by 180909** [comment]
Maybe [this](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#traditional-dos-paths) can give some help.

**Comment by mattn** [comment]
I agree with this change. `\\host\share` is not like `C:`. IsAbs have not to return result depend on last backslash for UNC paths. The syntax that can represent a relative path is only available if the path is `C:`.

```c
#include <stdio.h>
#include <stdlib.h>

int
main(int argc, char* argv[]) {
  char* paths[] = {
    "C:",
    "C:\\",
    "C:temp",
    "C:\\temp",
    "\\\\127.0.0.1",
    "\\\\127.0.0.1\\",
    "\\\\127.0.0.1\\C$",
    "\\\\127.0.0.1\\C$\\",
    NULL
  };
  for (char **p = paths; *p; p++) {
    char path[_MAX_PATH];
    char* res = _fullpath(path, *p, sizeof(path));
    printf("%s is %s\n", *p, res);
  }
  return 0;
}
```

```
C: is C:\temp
C:\ is C:\
C:temp is C:\temp\temp
C:\temp is C:\temp
\\127.0.0.1 is \\127.0.0.1
\\127.0.0.1\ is \\127.0.0.1\
\\127.0.0.1\C$ is \\127.0.0.1\C$
\\127.0.0.1\C$\ is \\127.0.0.1\C$\
```
(This is obviously thing)

**Comment by mattn** [comment]
But https://golang.org/cl/333911 seems wrong code. IsAbs should be separated for Windows.

**Comment by alexbrainman** [comment]
> Doesn't the IsAbs/Volume asymmetry already apply to `filepath.Rel` after the changes in #41230?

Indeed.

Alex
