### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ytxyyt** [golang/go#47149]
什么情况？
![Screenshot_20210713_022404_com termux](https://user-images.githubusercontent.com/84581911/125337531-b4e31780-e381-11eb-92b0-68d70f765bc5.jpg)

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
