### ISSUE TITLE
crypto and hash directories in the standard library are confused？

### ISSUE THREAD

**Issue by winnerxue** [golang/go#47157]
The "crypto" and "hash" directories in the standard library are confused，I think the following crypto directories should be migrated to hash

* crypto/md5
* crypto/shaxxx
* crypto/hmac

**Comment by cespare** [comment]
The separation is intentional: the crypto/xxx packages you mention implement cryptographic hashes (though some of them are cryptographically broken); the hash/xxx packages implement non-cryptographic hashes.

In any case, too late to change now.
