### ISSUE TITLE
proxy.golang.org: txn2/kubefwd package latest version points to an older version

### ISSUE THREAD

**Issue by flupec** [golang/go#47158]
### What version of Go are you using (`go version`)?

There is nothing to deal with go binary.

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

There is nothing to deal with go binary 

### What did you do?

Please, see a related problem in kubefwd package source repo https://github.com/txn2/kubefwd/issues/158

### What did you expect to see?
proxy must supply latest package version

### What did you see instead?
proxy supplies 1.18.2 version

**Comment by seankhliao** [comment]
see https://golang.org/ref/mod#versions

> Each version starts with the letter v, followed by a semantic version.
