### ISSUE TITLE
proxy.golang.org: module versions are not listed for versions higher than the current stable release

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#47153]
https://pkg.go.dev/go.oneofone.dev/radix@main?tab=versions
https://github.com/OneOfOne/radix/releases

I thought it was the go 1.18 line, but it's the same with go 1.14.

**Comment by jamalc** [comment]
I requested the documentation for your package following the instructions [here](https://go.dev/about/#adding-a-package).

Using @main in the URL for the versions page will only show the non-tagged version for a module. Looking at https://pkg.go.dev/go.oneofone.dev/radix?tab=versions I do see v1.0.1 in the list. Is that what you were expecting?

**Comment by seankhliao** [comment]
note they aren't in the proxy either https://proxy.golang.org/go.oneofone.dev/radix/@v/list

**Comment by OneOfOne** [comment]
Update: it seems to be the the `go 1.18` line.

**Comment by OneOfOne** [comment]
@jamalc @seankhliao it updated since I opened the bug after I tagged a release with go version to set to 1.14 in go.mod, the proxy ignores versions higher than the current stable release apparently.

Not sure if this is a bug or not so I'll reopen.

**Comment by julieqiu** [comment]
This is intended behavior of pkg.go.dev, since all of our data is fetched from the proxy. 

/cc @katiehockman @heschi @hyangah on whether this is an issue for the proxy.

**Comment by heschi** [comment]
AFAICT the only problem here is that you tagged `v1.0`, which is invalid semver. It should've been `v1.0.0`. Please correct me if I'm missing something.
