### ISSUE TITLE
Feature request : Go 2.0 with rustgo call? 

### ISSUE THREAD

**Issue by hiqsociety** [golang/go#47156]
To squeeze out every performance possible for calling rust function / modules.
Making calling rust function / variables as cheap + fast as possible. best if the overhead is just a function call.

**Comment by ianlancetaylor** [comment]
This sounds like cgo.  What are you suggesting that is not already supported by cgo?

**Comment by hiqsociety** [comment]
https://blog.filippo.io/rustgo/ <- this kind of implementation seems a bit complicated and manual. possible to make it more streamline and natural?

**Comment by ianlancetaylor** [comment]
From the Go point of view, I don't think that there is much that is Rust specific in that discussion by @FiloSottile.  If tthat is what you want then I think this is basically a duplicate of #42469.

**Comment by hiqsociety** [comment]
ok thx
