### ISSUE TITLE
x/website: Add information about idiomatic usage of internal packages

### ISSUE THREAD

**Issue by mickeyreiss** [golang/go#47178]
I am not able to find any mention of "Internal" packages in [`effective go`](https://golang.org/doc/effective_go).

In my mind, this feature is relevant for large codebases and libraries intended for public consumption. This way, developers can express which APIs are included in their package's compatibility promise.

It would be great if there were official recommendations regarding this feature. 

Additionally, I was not able to find a reference to this feature in the [spec](https://golang.org/ref/spec#Packages), although I do see it announced as a generally available feature in the [go1.4 release notes](https://golang.org/doc/go1.4#internalpackages).

**Comment by fzipp** [comment]
> Additionally, I was not able to find a reference to this feature in the spec

The spec would be the wrong place. Internal directories are not a language feature, but a feature of the `go` tool.
https://pkg.go.dev/cmd/go#hdr-Internal_Directories

**Comment by cherrymui** [comment]
"Effective Go" doesn't seem to cover package layouts. So mentioning internal packages seems beyond the scope of that article.

As @fzipp noted, it is documented with the cmd/go command.

@mickeyreiss is there any other suggestions about internal packages? Otherwise we can close this. Thanks.

**Comment by mickeyreiss** [comment]
Thanks for the responses.

> is there any other suggestions about internal packages?

My only suggestion is to provide guidance somewhere about the idiomatic usage: Are there any pitfalls or recommendations for using internal packages?
