### ISSUE TITLE
time: obsolete comment in zoneinfo.go

### ISSUE THREAD

**Issue by wzzhu** [golang/go#47189]
Obsolete comment in src/time/zoneinfo.go

```
// the start and end times bracketing sec when that zone is in effect,
// the offset in seconds east of UTC (such as -5*60*60), and whether
// the daylight savings is being observed at that time.
func (l *Location) lookup(sec int64) (name string, offset int, isDST bool, start, end int64)
```

should removed the last one
"and whether the daylight savings is being observed at that time".

Caused by this change:
"remove some unused return parameters" https://cs.opensource.google/go/go/+/8da180f6cac51f6cb8a316b962f797dbaf7ee96f

**Comment by tklauser** [comment]
The `isDST` return value was added again in https://golang.org/cl/264077, so incidentally the godoc comment is correct again.

**Comment by cherrymui** [comment]
As @tklauser pointed out, this works as intended now. Thanks.
