### ISSUE TITLE
x/tools/gopls: documented imports function for Neovim LSP executes any available code action

### ISSUE THREAD

**Issue by rentziass** [golang/go#47181]
The Lua function for supporting imports with Neovim native LSP support documented [here](https://github.com/golang/tools/blob/master/gopls/doc/vim.md#imports) does work for imports, but also runs any other code action available in the current range.

For example, if your cursor is on an empty struct declaration like this
```go
type A struct {
  name string
}

func example() {
  myStruct := &A{} # <- cursor on curly braces
}
```
and run the function with imports currently already organized, the next available code action that will be applied is filling that struct. So the result would be
```go
type A struct {
  name string
}

func example() {
  myStruct := &A{
    name: "",
  }
}
```

The reason for that is the context being provided to gopls does not limit code actions of interest to just `organizeImports`:
```lua
local context = { source = { organizeImports = true } }
```

This would instead do what's intended here:
```lua
local context = { only = { "source.organizeImports" } }
```

Although I figured this out the hard way, this has also been discussed in the [discussion cited in the docs](https://github.com/neovim/nvim-lspconfig/issues/115) :smile:

**Comment by rentziass** [comment]
Happy to submit a CL if this makes sense :)

**Comment by hyangah** [comment]
Feel free to send a CL to fix the document.
cc @ainar-g
