### ISSUE TITLE
Confused by slice len in goroutine

### ISSUE THREAD

**Issue by javasgl** [golang/go#47190]
### What version of Go are you using (`go version`)?

<pre>
go version go1.16.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="xxxxCaches/go-build"
GOENV="/xxxxApplication Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="xxxx/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/xxxx/goCode"
GOPRIVATE=""
GOPROXY=""
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/xxxx/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b1/bhf9j3q96m75223l3hh41ccw0000gn/T/go-build1210232747=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
package main

import (
	"fmt"
	"reflect"
	"runtime"
	"time"
	"unsafe"

	"golang.org/x/sync/errgroup"
)

func main() {

	fmt.Printf("Go version: %s\n", runtime.Version())

	runtime.GOMAXPROCS(5)

	a := run()

	fmt.Println("main.a ", fmt.Sprintf("%+v", (*reflect.SliceHeader)(unsafe.Pointer(&a))))
	fmt.Println("main.a1", "len", len(a), fmt.Sprintf("%p", a))
	time.Sleep(5 * time.Second)
	fmt.Println("main.a3", "len", len(a), fmt.Sprintf("%p", a))
}

func run() []int {

	seed := []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

	retChan := make(chan int, 2)

	res := make([]int, 0, 20)

	go func() {

		for v := range retChan {

			res = append(res, v)

			fmt.Println("out....", v,  fmt.Sprintf("%p", res))

		}

		fmt.Println("end....range", "len:", len(res), "pointer", fmt.Sprintf("%p", res))

		fmt.Println("end.....range", fmt.Sprintf("%+v", (*reflect.SliceHeader)(unsafe.Pointer(&res))))

	}()

	eg := errgroup.Group{}
	for _, i := range seed {
		i := i
		eg.Go(func() error {

			retChan <- i

			return nil
		})
	}
	eg.Wait()

	close(retChan)
	// fmt.Println("before return", fmt.Sprintf("%+v", (*reflect.SliceHeader)(unsafe.Pointer(&res))))
	fmt.Println("run return", "len:", len(res), fmt.Sprintf("%p", res), fmt.Sprintf("%+v", (*reflect.SliceHeader)(unsafe.Pointer(&res))))
	return res
}
```

### What did you expect to see?

len(slice)  ==  sliceHeader.Len

### What did you see instead?
```
Go version: go1.16.6
out.... 2 0xc0000c2000
out.... 10 0xc0000c2000
out.... 6 0xc0000c2000
out.... 7 0xc0000c2000
out.... 8 0xc0000c2000
out.... 9 0xc0000c2000
out.... 3 0xc0000c2000
out.... 4 0xc0000c2000
out.... 1 0xc0000c2000
out.... 5 0xc0000c2000
end....range len: 10 pointer 0xc0000c2000
end.....range &{Data:824634515456 Len:10 Cap:20}
run return len: 8 0xc0000c2000 &{Data:824634515456 Len:9 Cap:20}
main.a  &{Data:824634515456 Len:10 Cap:20}
main.a1 len 10 0xc0000c2000
main.a3 len 10 0xc0000c2000

```

![image](https://user-images.githubusercontent.com/5222868/125596405-9a877a4a-212f-4999-a72a-1b1d8ac00a7a.png)

the code is here : 

https://paste.ubuntu.com/p/hBQ4Ht2wv9/

**Comment by javasgl** [comment]
`
fmt.Println("run return", "len:", len(res), fmt.Sprintf("%p", res), fmt.Sprintf("%+v", (*reflect.SliceHeader)(unsafe.Pointer(&res))))
`
len(res) == 8 , but sliceHeader.Len = 9

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by fzipp** [comment]
`go run -race` says your code has a data race:

```
==================
WARNING: DATA RACE
Read at 0x00c0000b2030 by main goroutine:
  main.run()
      main.go:65 +0x284
  main.main()
      main.go:19 +0xc4

Previous write at 0x00c0000b2030 by goroutine 7:
  main.run.func1()
      main.go:39 +0x1d8

Goroutine 7 (finished) created at:
  main.run()
      main.go:35 +0x138
  main.main()
      main.go:19 +0xc4
==================
```

You have to fix it before wondering about strange effects.
