### ISSUE TITLE
Unable to install Go packages in Gitbash

### ISSUE THREAD

**Issue by tanviagwl98** [golang/go#47198]
### What version of Go are you using (`go version`)?
<pre>
$ go version 1.14
</pre>
### Does this issue reproduce with the latest release?
YES
### What operating system and processor architecture are you using (`go env`)?
Windows operating system  using GitBash
### What did you do?
I tried to install Go packages
1. go get -u github.com/yosssi/ace
2. go get -u github.com/sirupsen/logrus
3. go get -u github.com/jinzhu/gorm
4. go get -u github.com/protobuf/proto

go get -u **packagename**

### What did you expect to see?
Go package should be downloaded successfully

### What did you see instead?
**
![image](https://user-images.githubusercontent.com/45534001/125645185-6847ee90-a539-4ff9-9495-e70dfe1d067b.png)
**

**Comment by cherrymui** [comment]
> go version 1.14

Go 1.14 is no longer supported. Could you try a newer version of Go, preferably Go 1.16.6 or Go 1.17RC1?

The error message looks like network related. Possible network instability? Could you try it again, possibly with a stable network? And is it reproducible from other shell?

BTW, it would be better to paste the error message as text, instead of as a picture. Thanks.

**Comment by tanviagwl98** [comment]
> > go version 1.14
> 
> Go 1.14 is no longer supported. Could you try a newer version of Go, preferably Go 1.16.6 or Go 1.17RC1?
> 
> The error message looks like network related. Possible network instability? Could you try it again, possibly with a stable network? And is it reproducible from other shell?
> 
> BTW, it would be better to paste the error message as text, instead of as a picture. Thanks.

Thank you for your quick response. I have tried on higher version as well but same error was occurring. The image has the following text:

$ go get -u github.com/gogo/protobuf
 go: github.com/gogo/protobuf upgrade => v1.3.2
go: downloading github.com/gogo/protobuf v1.3.2
go get: github.com/gogo/protobuf@v1.3.2: stream error: stream ID 45; NO_ERROR

**Comment by tanviagwl98** [comment]
> > go version 1.14
> 
> Go 1.14 is no longer supported. Could you try a newer version of Go, preferably Go 1.16.6 or Go 1.17RC1?
> 
> The error message looks like network related. Possible network instability? Could you try it again, possibly with a stable network? And is it reproducible from other shell?
> 
> BTW, it would be better to paste the error message as text, instead of as a picture. Thanks.

I have been trying this since past two days, with a good network. I suppose network stability is not an issue here.
Thanks

**Comment by tanviagwl98** [comment]
Hi, I have resolved this issue. It was occurring due to VPN setting that I had to disable.

So, I am closing this issue now.

Thanks
