### ISSUE TITLE
math.Pow

### ISSUE THREAD

**Issue by bendh1** [golang/go#47191]
s := math.Pow(float64(1.2), float64(1/9))
fmt.Println(s)

the result is 1, why not 1.0204645356768483 ???

**Comment by MMMMMMoSky** [comment]
s := math.Pow(float64(1.2), float64(1.0/9.0))
fmt.Println(s)

**Comment by MMMMMMoSky** [comment]
1/9 == 0

**Comment by bendh1** [comment]
s := math.Pow(float64(8.0), float64(1.0/3.0))
fmt.Println(s)
1.9999999999999998

fmt.Println(float64(1.0 / 3.0))
0.3333333333333333

**Comment by randall77** [comment]
I agree, `math.Pow(8, 1/3.)` should be 2, not the float below 2. The actual result is closer to 2.

Proof: https://play.golang.org/p/BRHIwWv2iBB

Not sure what precision we guarantee for `math.Pow`.
