### ISSUE TITLE
go/types: do not accept generic features unless -lang is go1.18 or greater

### ISSUE THREAD

**Issue by griesemer** [golang/go#47205]
Reminder issue.
This would also apply to implicit instantiation of functions through type inference.

cc: @findleyr, @mdempsky, @ianlancetaylor

**Comment by odeke-em** [comment]
I am happy to report that @findleyr fixed this in CL https://go-review.googlesource.com/c/go/+/346433 aka commit b93581e47d358da9fc2d08032cd73797c2cb28a5 but we didn't catch that this issue had been opened 6 days earlier. Closing it but please feel free to correct me if am wrong. Thank you for the awesome and hard work @findleyr and @griesemer!
