### ISSUE TITLE
x/pkgsite: change back to github as a source viewer for stdlib

### ISSUE THREAD

**Issue by powerman** [golang/go#47202]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/testing
 
### What did you do?
 
Click on stdlib's function name to view it source code. 
 
### What did you expect to see?
 
https://github.com/golang/go/blob/go1.16.6/src/testing/testing.go#L263
 
### What did you see instead?

https://cs.opensource.google/go/go/+/refs/tags/go1.16.6:src/testing/testing.go;l=263

P.S. I mean it - maybe technically cs.opensource.google/go/go **is** the repository and github is just a mirror, but using cs.opensource.google instead of github hurts usability, so please revert this change or make it configurable choice.

**Comment by seankhliao** [comment]
can you give specific examples of "hurts usability"?

**Comment by ALTree** [comment]
These links never pointed to the github sources. Before the pkg.go.dev redirect, they .went to the files on golang.org/src, like this:

https://web.archive.org/web/20210409132622/https://golang.org/src/archive/tar/writer.go?s=432:876#L9

**Comment by twmb** [comment]
I too prefer Github, but this was never on GH so there is not a compelling reason to switch to GH.

I think any usability bit is going to be a matter of opinion, though. That said, IMO, a few things that are nice about Github:
- tabs are wide (they do not look like two spaces)
- even more colors for syntax highlighting
- comments are faded more, which has a clearer visual separation from code

**Comment by zikaeroh** [comment]
FWIW, many (if not all) of those are settings available in top right menu:

![image](https://user-images.githubusercontent.com/48577114/125704222-c5951bb3-9a13-4a24-a2a6-f55e7dfb69d9.png)

**Comment by twmb** [comment]
Awesome, I did not know that, thank you!

**Comment by go101** [comment]
If you need a rich code reading experience, you can try Golds (https://go101.org/article/tool-golds.html), which provides much richer code reading features than Github. (I'm the author)

**Comment by julieqiu** [comment]
This was topic was discussed on https://github.com/golang/go/issues/44832. If you have suggestions for the https://cs.opensource.google/go UI, feel free to send feedback to that team by clicking `Send Feedback` from the dropdown in the top right corner. 

Closing this issue.
