### ISSUE TITLE
 x/pkgsite: cannot view source of standard library on Firefox v. 90.0

### ISSUE THREAD

**Issue by iporsut** [golang/go#47213]
When I click link to view source of https://pkg.go.dev/fmt@go1.16.6#Print, it open https://cs.opensource.google/go/go/+/go1.16.6:src/fmt/print.go;l=241 but it has error. I can't view the source.

<img width="1278" alt="Screen Shot 2564-07-15 at 09 55 01" src="https://user-images.githubusercontent.com/216396/125720680-5ce6c045-f45a-4297-bf6f-07c3f8113ce0.png">

The error message is in Thai language localization it tell that permission denied. I also capture the log in inspector and found error like that. I'm not sure what happen because on Chrome doesn't error like that.

**Comment by tmthrgd** [comment]
I’ve got this error before using an ad blocker and I notice you have a B+ icon in your top bar for the DuckDuckGo Privacy Essentials extension (I think that’s what it’s called from the top of my head). Try disabling any ad blockers you have for cs.opensource.google and see if that helps.

It’s a really bad and vague error message though. I don’t believe the Go team have control over that.

**Comment by iporsut** [comment]
@tmthrgd After disable DuckDuckGo extension, I can access and don't have any error. Thank you very much.
