### ISSUE TITLE
os: DirFS has interaction with Chdir

### ISSUE THREAD

**Issue by kortschak** [golang/go#47214]
This is something that may not be significant enough to address, but I thought it was worth raising.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17rc1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/user/bin"
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/user/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17rc1"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build511087247=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Given a main.go from https://play.golang.org/p/Tccj4KWcX7X

```
$ cd /home/user/dirfs
$ mkdir dirA
$ go run main.go
```

### What did you see?

I saw exactly what I expected, but it could be something that may surprise some users.

```
2021/07/15 15:02:04 from "/home/user/dirfs/dirA": open dirA/file: no such file or directory
exit status 1
```

Given that the `DirFS` was handed a relative path, it's entirely reasonable for reads subsequent to a chdir to be now relative to the new working directory, but it may be worth clarifying that the `DirFS` does not hold an absolute path as its root unless it was handed one or some other way to indicate that chdir will alter the effective filesystem that's seen.

**Comment by seankhliao** [comment]
cc @rsc
