### ISSUE TITLE
access: gomote access token

### ISSUE THREAD

**Issue by iii-i** [golang/go#47226]
I'm working on implementing the golang race detector for s390x (wip branch: https://github.com/iii-i/go/tree/tsan-s390x). I've merged the LLVM part (https://reviews.llvm.org/D105629) and now I would like to get access to gomote in order to build `race_linux_s390x.syso` with racebuild for upstream submission.

cc @golang/release

```
$ echo $USER
iii
```

**Comment by cherrymui** [comment]
Hi @iii-i thanks for the work! For building the syso you don't have to have gomote access. You could just build it locally, and once you have a working process you can send a CL for golang.org/x/build/cmd/racebuild, and we can do the gomote part. Thanks.

**Comment by iii-i** [comment]
Thx, I've sent a CL: https://go-review.googlesource.com/c/build/+/336511
