### ISSUE TITLE
x/pkgsite: can't view "internal/" package docks after redirect from golang.org

### ISSUE THREAD

**Issue by bcmills** [golang/go#47225]
### What is the URL of the page with the issue?
 
https://tip.golang.org/cmd/go/internal/str
 
 
### What is your user agent?
 
`Mozilla/5.0 (X11; CrOS x86_64 13904.66.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36` 
 
 
### Screenshot

![image](https://user-images.githubusercontent.com/5200974/125827621-2b4cbc58-4a9a-4f86-b6a8-490e6f623f7f.png)

 
 
### What did you do?
 
Navigated to https://tip.golang.org/cmd/go/internal/str by entering the URL in the Chrome location bar.
 
 
### What did you expect to see?
 
Documentation for the `cmd/go/internal/str` package, as can still be viewed at https://tip.golang.org/cmd/go/internal/str/?m=old.
 
 
### What did you see instead?

404 Not Found

For my workflow, this represents a substantial regression from the old `golang.org` doc server.

This is closely related to #36940; see previously #36803.

**Comment by julieqiu** [comment]
Fixed.

**Comment by bcmills** [comment]
Wow, thanks for the quick turnaround! 😃
