### ISSUE TITLE
go1.16 go mod error unresolved dependency

### ISSUE THREAD

**Issue by dybxin** [golang/go#47239]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.16.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xxx/.cache/go-build"
GOENV="/home/xxx/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/xxx/Projects/GoProjects/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xxx/Projects/GoProjects"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1532406101=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you expect to see?

not red prompt

### What did you see instead?
![Screenshot from 2021-07-16 14-58-20](https://user-images.githubusercontent.com/14888437/125905806-9d8c642a-ce30-4d1b-9877-5eab790791f6.png)
![Screenshot from 2021-07-16 14-58-31](https://user-images.githubusercontent.com/14888437/125905814-f20ab1bf-d4b4-4233-aee8-2cbf620e0c6c.png)

**Comment by cherrymui** [comment]
@dybxin could you be clearer what the bug is? Are you reporting a bug for the IDE?

If you are asking a question about how to use Go, you will get better answers, if you ask on a forum rather than on the issue tracker. See https://golang.org/wiki/Questions. Thanks.

**Comment by heschi** [comment]
That UI looks like IntelliJ to me, in which case questions should be directed to IntelliJ.

**Comment by delabania** [comment]
Did you try to run `go get` command?
