### ISSUE TITLE
x/mobile: use GOOS=ios and remove the build tag ios usages

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#47238]
This is a proposal of refactoring. I propose to replace the current build tag `ios` usages with specifying GOOS=ios. This change means that Go 1.16 or newer will be required for gomobile. So, I'm fine if we have to wait more (e.g., Go 1.17 is released)

Background: GOOS=ios was introduced at Go 1.16. Before this, gomobile used a build tag `ios` for iOS projects. In Go 1.16 and newer, standard libraries have `*_ios.go` files, and apparently they also specify `// +build ios` explicitly at the same time. Then, we don't have an urgent issue around this.

@hyangah, @ydnar, What do you think?

**Comment by ydnar** [comment]
Sure, I think it makes sense.

Would you want the current iOS tests to pass as well?

It would probably need some additional updates, and ideally macOS CI so it doesn't continue to bit-rot.

**Comment by cherrymui** [comment]
cc @eliasnaur

**Comment by dmitshur** [comment]
Now that Go 1.17 is released (and thus 1.15 has become unsupported), there shouldn't be a reason not to do this. Also see discussion in #47952.
