### ISSUE TITLE
x/text/language: Parse can panic with index out of range 

### ISSUE THREAD

**Issue by cor0ps** [golang/go#47240]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=off
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xx\AppData\Local\go-build
set GOENV=C:\Users\xxxx\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\xxxxx\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\xxxx\go
set GOPRIVATE=
set GOPROXY=
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.5
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\xxxxx\AppData\Local\Temp\go-build2561473585=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Code:

https://play.golang.org/p/Df8Bx3l50Zp

### What did you expect to see?

program ok

### What did you see instead?

panic: runtime error: index out of range [4] with length 4

**Comment by cherrymui** [comment]
This looks similar to #41617 . Is this a dup? Thanks.

**Comment by cor0ps** [comment]
dup

**Comment by cor0ps** [comment]
> This looks similar to #41617 . Is this a dup? Thanks.

dup

**Comment by cherrymui** [comment]
Thanks. Closing.
