### ISSUE TITLE
cmd/compile: build tags don't respect the go version in go.mod

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#47259]
This mainly applies to dev.typeparams since everything breaks if you use generics and go.mod isn't set to 1.18, however I tested with tip and go1.16 and the same issue happens.

To reproduce:

* go.mod

```go
module x

go 1.15
```
* main.go

```go
package main

func main() {
        println(Version)
}
```

* main_go115.go

```go
//go:build !go1.16
// +build !go1.16

package main

const Version = "1.15"
```

* main_go116.go

```go
//go:build go1.16
// +build go1.16

package main

const Version = "1.16"
```

**Comment by seankhliao** [comment]
The build tags are chosen by the version of the toolchain used, not the the `go` directive (if it was it would be redundant)

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
