### ISSUE TITLE
Cannot build IPFS from source: combining dwarf failed: unknown load command 0x80000034 (2147483700)

### ISSUE THREAD

**Issue by unbeatable-101** [golang/go#47269]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 darwin/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/williamdavis/Library/Caches/go-build"
GOENV="/Users/williamdavis/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/williamdavis/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/williamdavis/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.16.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.16.5/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/williamdavis/go-ipfs/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/96/7_zsj2c13r751mhmyphh_4tm0000gn/T/go-build1384215899=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I ran 
```shell
% git clone https://github.com/ipfs/go-ipfs.git
% cd go-ipfs
% make build
```
and the build failed, here is the output 
[Terminal Saved Output.txt](https://github.com/ipfs/go-ipfs/files/6834147/Terminal.Saved.Output.txt)

### What did you expect to see?
The binary being properly compiled

### What did you see instead?
It errored out
[Terminal Saved Output.txt](https://github.com/ipfs/go-ipfs/files/6834147/Terminal.Saved.Output.txt)

**Comment by AlexRouSg** [comment]
Please test with `1.17rc1`, I have seen this error before on slack and `1.17` compiled fine for the other person.

**Comment by unbeatable-101** [comment]
Do you have a binary I can test? I cannot seem to build 1.17rc1.

**Comment by AlexRouSg** [comment]
https://golang.org/dl/#unstable

**Comment by unbeatable-101** [comment]
1.17rc1 works, thanks.

**Comment by AlexRouSg** [comment]
I would keep this open until we understand why 1.16 wasn't working, likely there would be something to fix.

**Comment by thanm** [comment]
load command 0x80000034 corresponds to LC_DYLD_CHAINED_FIXUPS. Support for this load command was added in https://go-review.googlesource.com/c/go/+/312729, which is part of Go 1.17. 

Closing this out as WAI, please re-open if needed.
