### ISSUE TITLE
access: may-start-trybots

### ISSUE THREAD

**Issue by rhysh** [golang/go#47267]
Hello! From https://golang.org/wiki/GerritAccess, could I please have Gerrit access for may-start-trybots, https://go-review.googlesource.com/#/admin/groups/1030,members ? My user ID there is 9210, with email address rhys@justin.tv. Thank you!

**Comment by seankhliao** [comment]
cc @golang/release

**Comment by rhysh** [comment]
Hi again. Is there something standing in the way of this, or is it general backlog / poor timing? CC @cagedmantis , it looks like you often handle these. Thanks.

**Comment by cagedmantis** [comment]
@rhysh The team will respond to this issue this week. We've been a bit busy working on the upcoming release.

**Comment by dmitshur** [comment]
Hi Rhys,

Thank you for your contributions, and for requesting trybot access. I've added your Gerrit account to the `may-start-trybots` group, so you should be able to do so now.

As you've likely seen at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at minimum skim CLs before starting a trybot run.

Thanks!
