### ISSUE TITLE
io/ioutil: mark functions as deprecated

### ISSUE THREAD

**Issue by iateadonut** [golang/go#47265]
### What version of Go are you using (`go version`)?

go version go1.16.5 linux/amd64

### What did you do?

go doc ioutil tempdir

### What did you expect to see?

a message that the function ioutil TempDir() has been moved to os MkdirTemp()

I'm wondering, because it looks like it's not even possible to make the update and a pull request.

**Comment by fzipp** [comment]
See the comments on https://golang.org/cl/284777

**Comment by ianlancetaylor** [comment]
In the Go 1.16 release `ioutil.TempDir` was not changed.  In the upcoming Go 1.17 release `ioutil.TempDir` just calls `os.MkdirTemp`, and the doc comment says so.

So I don't think anything needs to change here.
