### ISSUE TITLE
cmd/go: all.bash times out for go1.17rc1 on OpenBSD/amd64

### ISSUE THREAD

**Issue by rialpamu** [golang/go#47271]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17rc1 openbsd/amd64
</pre>

### Does this issue reproduce with the latest release?

No problem with the latest stable release go1.16.6

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rapm/.cache/go-build"
GOENV="/home/rapm/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="openbsd"
GOINSECURE=""
GOMODCACHE="/home/rapm/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="openbsd"
GOPATH="/home/rapm/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/rapm/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/rapm/local/go/pkg/tool/openbsd_amd64"
GOVCS=""
GOVERSION="go1.17rc1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3926604099=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

<pre>
git pull
git checkout go1.17rc1
cd src
bash ./all.bash
</pre>

### What did you expect to see?

Successful build running all the tests without errors

### What did you see instead?

<pre>
...
ok      cmd/doc 3.452s
ok      cmd/fix 47.487s
go test proxy running at GOPROXY=http://127.0.0.1:4682/mod
--- FAIL: TestScript (0.07s)
    --- FAIL: TestScript/mod_convert_vendor_yml (0.19s)
        script_test.go:252:
            # We should not create a go.mod file unless the user ran 'go mod init' explicitly.
            # However, we should suggest 'go mod init' if we can find an alternate config file. (0.036s)
            # The command we suggested should succeed. (0.066s)
            > cd ..
            $WORK/test
            > go mod init
            [stderr]
            go: creating new go.mod: module m
            go: copying requirements from vendor.yml
            go: to add module requirements and sums:
                go mod tidy
            > go list -m all
            [context deadline exceeded]
            FAIL: testdata/script/mod_convert_vendor_yml.txt:13: test timed out while running command

    --- FAIL: TestScript/mod_convert_vendor_manifest (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_convert_vendor_json (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_convert_vendor_conf (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_convert_tsv_insecure (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_convert_tsv (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_convert_godeps (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_update_wildcard (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_convert_glockfile (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_convert_glide (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_update_unknown_protocol (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_convert_git (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_update_all (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_convert_dep (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_convert (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_concurrent (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_update (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_clean_cache (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_case_cgo (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_cache_dir (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_tilde (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_case (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_cache_rw (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_test_only (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_build_versioned (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_build_tags (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_build_info_err (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_bad_filenames (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/cover_dot_import (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_race (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_insecure (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_goroot (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_non_pkg (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_legacy (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_issue11307 (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_internal_wildcard (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_insecure_update (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_go_file (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_insecure_redirect (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_insecure_no_longer_supported (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_insecure_env (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_dotfiles (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_insecure_custom_domain (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_dash_t (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_dot_slash_download (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_domain_root (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_custom_domain_wildcard (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_404_meta (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/get_brace (0.00s)
        script_test.go:150: test interrupted during setup: context deadline exceeded
    --- FAIL: TestScript/mod_deprecate_message (0.66s)
        script_test.go:252:
            # When there is a short single-line message, 'go get' should print it all. (0.218s)
            # When there is a multi-line message, 'go get' should print the first line. (0.249s)
            > go get -d multiline
            [stderr]
            SIGQUIT: quit
            PC=0x29617405a m=5 sigcode=0

            goroutine 0 [idle]:
            runtime.thrsleep(0xc000084358, 0x3, 0x0, 0x0, 0xc000084358)
                /home/rapm/local/go/src/runtime/sys_openbsd1.go:15 +0x39 fp=0x23d93c448 sp=0x23d93c420 pc=0x45a539
            runtime.semasleep(0xffffffffffffffff)
                /home/rapm/local/go/src/runtime/os_openbsd.go:112 +0xea fp=0x23d93c4a8 sp=0x23d93c448 pc=0x4354ca
            runtime.notesleep(0xe66758)
                /home/rapm/local/go/src/runtime/lock_sema.go:182 +0x78 fp=0x23d93c4d8 sp=0x23d93c4a8 pc=0x40d9f8
            runtime.templateThread()
                /home/rapm/local/go/src/runtime/proc.go:2385 +0x86 fp=0x23d93c4f8 sp=0x23d93c4d8 pc=0x440826
            runtime.mstart1()
                /home/rapm/local/go/src/runtime/proc.go:1407 +0x97 fp=0x23d93c520 sp=0x23d93c4f8 pc=0x43f197
            runtime.mstart0()
                /home/rapm/local/go/src/runtime/proc.go:1365 +0x66 fp=0x23d93c540 sp=0x23d93c520 pc=0x43f0e6
            runtime.mstart()
                /home/rapm/local/go/src/runtime/asm_amd64.s:248 +0x5 fp=0x23d93c548 sp=0x23d93c540 pc=0x46bee5

            goroutine 1 [chan receive]:
            runtime.gopark(0xa905d0, 0xc000082ef8, 0xe, 0x17, 0x2)
                /home/rapm/local/go/src/runtime/proc.go:366 +0x105 fp=0xc00014db70 sp=0xc00014db50 pc=0x43c665
            runtime.chanrecv(0xc000082ea0, 0x0, 0x1)
                /home/rapm/local/go/src/runtime/chan.go:576 +0x5f7 fp=0xc00014dc00 sp=0xc00014db70 pc=0x407f77
            runtime.chanrecv1(0xc000082ea0, 0x0)
                /home/rapm/local/go/src/runtime/chan.go:439 +0x2b fp=0xc00014dc30 sp=0xc00014dc00 pc=0x40792b
            cmd/go/internal/modget.(*resolver).performPathQueries(0xc0000cc700, {0xb24300, 0xc00009c000})
                /home/rapm/local/go/src/cmd/go/internal/modget/get.go:967 +0x132 fp=0xc00014dc70 sp=0xc00014dc30 pc=0x9476f2
            cmd/go/internal/modget.runGet({0xb24300, 0xc00009c000}, 0xe27a80, {0xc0000b0030, 0x1, 0x1})
                /home/rapm/local/go/src/cmd/go/internal/modget/get.go:294 +0x325 fp=0xc00014dd80 sp=0xc00014dc70 pc=0x941b45
            main.invoke(0xe27a80, {0xc0000b0010, 0x3, 0x3})
                /home/rapm/local/go/src/cmd/go/main.go:216 +0x3b1 fp=0xc00014de50 sp=0xc00014dd80 pc=0x976111
            main.main()
                /home/rapm/local/go/src/cmd/go/main.go:173 +0x9ea fp=0xc00014df88 sp=0xc00014de50 pc=0x97594a
            runtime.main()
                /home/rapm/local/go/src/runtime/proc.go:255 +0x248 fp=0xc00014dfe0 sp=0xc00014df88 pc=0x43c208
            runtime.goexit()
                /home/rapm/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00014dfe8 sp=0xc00014dfe0 pc=0x46e121

            goroutine 2 [force gc (idle)]:
            runtime.gopark(0xa90820, 0xe347a0, 0x11, 0x14, 0x1)
                /home/rapm/local/go/src/runtime/proc.go:366 +0x105 fp=0xc000040fb0 sp=0xc000040f90 pc=0x43c665
            runtime.goparkunlock(...)
                /home/rapm/local/go/src/runtime/proc.go:372
            runtime.forcegchelper()
                /home/rapm/local/go/src/runtime/proc.go:306 +0xc5 fp=0xc000040fe0 sp=0xc000040fb0 pc=0x43c4c5
            runtime.goexit()
                /home/rapm/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000040fe8 sp=0xc000040fe0 pc=0x46e121
            created by runtime.init.7
                /home/rapm/local/go/src/runtime/proc.go:294 +0x35

            goroutine 3 [GC sweep wait]:
            runtime.gopark(0xa90820, 0xe34a60, 0xc, 0x14, 0x1)
                /home/rapm/local/go/src/runtime/proc.go:366 +0x105 fp=0xc0000417b0 sp=0xc000041790 pc=0x43c665
            runtime.goparkunlock(...)
                /home/rapm/local/go/src/runtime/proc.go:372
            runtime.bgsweep()
                /home/rapm/local/go/src/runtime/mgcsweep.go:163 +0xaa fp=0xc0000417e0 sp=0xc0000417b0 pc=0x426b4a
            runtime.goexit()
                /home/rapm/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000417e8 sp=0xc0000417e0 pc=0x46e121
            created by runtime.gcenable
                /home/rapm/local/go/src/runtime/mgc.go:181 +0x75

            goroutine 4 [GC scavenge wait]:
            runtime.gopark(0xa90820, 0xe35280, 0xd, 0x14, 0x1)
                /home/rapm/local/go/src/runtime/proc.go:366 +0x105 fp=0xc000041f80 sp=0xc000041f60 pc=0x43c665
            runtime.goparkunlock(...)
                /home/rapm/local/go/src/runtime/proc.go:372
            runtime.bgscavenge()
                /home/rapm/local/go/src/runtime/mgcscavenge.go:265 +0xf8 fp=0xc000041fe0 sp=0xc000041f80 pc=0x4249f8
            runtime.goexit()
                /home/rapm/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000041fe8 sp=0xc000041fe0 pc=0x46e121
            created by runtime.gcenable
                /home/rapm/local/go/src/runtime/mgc.go:182 +0x8d

            goroutine 18 [finalizer wait]:
            runtime.gopark(0xa90820, 0xe66200, 0x10, 0x14, 0x1)
                /home/rapm/local/go/src/runtime/proc.go:366 +0x105 fp=0xc00003c740 sp=0xc00003c720 pc=0x43c665
            runtime.goparkunlock(...)
                /home/rapm/local/go/src/runtime/proc.go:372
            runtime.runfinq()
                /home/rapm/local/go/src/runtime/mfinal.go:177 +0xc6 fp=0xc00003c7e0 sp=0xc00003c740 pc=0x41b5c6
            runtime.goexit()
                /home/rapm/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00003c7e8 sp=0xc00003c7e0 pc=0x46e121
            created by runtime.createfing
                /home/rapm/local/go/src/runtime/mfinal.go:157 +0x57

            goroutine 21 [runnable]:
            runtime.makeslicecopy(0x9ad600, 0x1f, 0x1e, 0xc0000fd840)
                /home/rapm/local/go/src/runtime/slice.go:36 +0x19c fp=0xc0000b6e38 sp=0xc0000b6e30 pc=0x4520dc
            syscall.ByteSliceFromString(...)
                /home/rapm/local/go/src/syscall/syscall.go:53
            syscall.BytePtrFromString(...)
                /home/rapm/local/go/src/syscall/syscall.go:69
            syscall.Lstat({0xc0000fd840, 0x1e}, 0xc0001739b8)
                /home/rapm/local/go/src/syscall/zsyscall_openbsd_amd64.go:967 +0x85 fp=0xc0000b6ea8 sp=0xc0000b6e38 pc=0x481a25
            os.lstatNolog.func1(...)
                /home/rapm/local/go/src/os/stat_unix.go:46
            os.ignoringEINTR(...)
                /home/rapm/local/go/src/os/file_posix.go:246
            os.lstatNolog({0xc0000fd840, 0x1e})
                /home/rapm/local/go/src/os/stat_unix.go:45 +0x65 fp=0xc0000b6ef8 sp=0xc0000b6ea8 pc=0x4e9a05
            os.Lstat({0xc0000fd840, 0x1e})
                /home/rapm/local/go/src/os/stat.go:22 +0x4d fp=0xc0000b6f38 sp=0xc0000b6ef8 pc=0x4e934d
            os.(*File).readdir(0xc0000aa210, 0xffffffffffffffff, 0x2)
                /home/rapm/local/go/src/os/dir_unix.go:129 +0x7ad fp=0xc0000b7060 sp=0xc0000b6f38 pc=0x4df62d
            os.(*File).Readdir(0xc0000aa210, 0xffffffffffffffff)
                /home/rapm/local/go/src/os/dir.go:41 +0x51 fp=0xc0000b70e0 sp=0xc0000b7060 pc=0x4de811
            io/ioutil.ReadDir({0xc0000fd7a0, 0x1a})
                /home/rapm/local/go/src/io/ioutil/ioutil.go:63 +0x90 fp=0xc0000b7188 sp=0xc0000b70e0 pc=0x589f50
            cmd/go/internal/fsys.readDir({0xc0000fd7a0, 0x1a})
                /home/rapm/local/go/src/cmd/go/internal/fsys/fsys.go:246 +0x39 fp=0xc0000b71e0 sp=0xc0000b7188 pc=0x5d8819
            cmd/go/internal/fsys.ReadDir({0xc0000fd7a0, 0x1a})
                /home/rapm/local/go/src/cmd/go/internal/fsys/fsys.go:270 +0x39c fp=0xc0000b7578 sp=0xc0000b71e0 pc=0x5d8dbc
            cmd/go/internal/fsys.walk({0xc0000fd7a0, 0x1a}, {0xb27188, 0xc000155800}, 0xc0000b77f0)
                /home/rapm/local/go/src/cmd/go/internal/fsys/fsys.go:412 +0x72 fp=0xc0000b7640 sp=0xc0000b7578 pc=0x5da2b2
            cmd/go/internal/fsys.walk({0xc0000c8090, 0x17}, {0xb27188, 0xc000154300}, 0xc0000b77f0)
                /home/rapm/local/go/src/cmd/go/internal/fsys/fsys.go:427 +0x2b8 fp=0xc0000b7708 sp=0xc0000b7640 pc=0x5da4f8
            cmd/go/internal/fsys.Walk({0xc0000c8090, 0x17}, 0xc0000b77f0)
                /home/rapm/local/go/src/cmd/go/internal/fsys/fsys.go:443 +0xdf fp=0xc0000b7770 sp=0xc0000b7708 pc=0x5da6df
            cmd/go/internal/modload.matchPackages.func3({0xc0000c8090, 0x17}, {0x0, 0x0}, 0x2)
                /home/rapm/local/go/src/cmd/go/internal/modload/search.go:58 +0x15d fp=0xc0000b7858 sp=0xc0000b7770 pc=0x8695dd
            cmd/go/internal/modload.matchPackages({0xb24300, 0xc00009c000}, 0xc0000ac8a0, 0xc000152630, 0x1, {0x0, 0x0, 0x0})
                /home/rapm/local/go/src/cmd/go/internal/modload/search.go:127 +0x31d fp=0xc0000b7a50 sp=0xc0000b7858 pc=0x868e7d
            cmd/go/internal/modload.MatchInModule({0xb24300, 0xc00009c000}, {0x7f7ffffe7d6f, 0x9}, {{0x0, 0x0}, {0x0, 0x0}}, 0xc000152630)
                /home/rapm/local/go/src/cmd/go/internal/modload/search.go:187 +0x15b fp=0xc0000b7af8 sp=0xc0000b7a50 pc=0x86a35b
            cmd/go/internal/modget.(*resolver).matchInModule.func1()
                /home/rapm/local/go/src/cmd/go/internal/modget/get.go:653 +0xe8 fp=0xc0000b7bc0 sp=0xc0000b7af8 pc=0x944368
            cmd/go/internal/par.(*Cache).Do(0xc0000cc7d0, {0x9e9480, 0xc0001525d0}, 0xc000053cd0)
                /home/rapm/local/go/src/cmd/go/internal/par/work.go:128 +0x10e fp=0xc0000b7c20 sp=0xc0000b7bc0 pc=0x5f9c6e
            cmd/go/internal/modget.(*resolver).matchInModule(0xc0000cc700, {0xb24300, 0xc00009c000}, {0x7f7ffffe7d6f, 0x9}, {{0x0, 0x0}, {0x0, 0x0}})
                /home/rapm/local/go/src/cmd/go/internal/modget/get.go:652 +0x1c5 fp=0xc0000b7d28 sp=0xc0000b7c20 pc=0x944185
            cmd/go/internal/modget.(*resolver).queryPath.func1()
                /home/rapm/local/go/src/cmd/go/internal/modget/get.go:985 +0x20a fp=0xc0000b7e10 sp=0xc0000b7d28 pc=0x947a8a
            cmd/go/internal/modget.(*query).pathOnce(0xc00012d450, {0x7f7ffffe7d6f, 0x9}, 0xc000053ef8)
                /home/rapm/local/go/src/cmd/go/internal/modget/query.go:264 +0x95 fp=0xc0000b7ed8 sp=0xc0000b7e10 pc=0x950955
            cmd/go/internal/modget.(*resolver).queryPath(0xc0000cc700, {0xb24300, 0xc00009c000}, 0xc00012d450)
                /home/rapm/local/go/src/cmd/go/internal/modget/get.go:975 +0x9d fp=0xc0000b7f30 sp=0xc0000b7ed8 pc=0x94785d
            cmd/go/internal/modget.(*resolver).performPathQueries.func1()
                /home/rapm/local/go/src/cmd/go/internal/modget/get.go:963 +0x74 fp=0xc0000b7f60 sp=0xc0000b7f30 pc=0x947794
            cmd/go/internal/par.(*Queue).Add.func1(0xc0000aa160, 0xc0000939e0)
                /home/rapm/local/go/src/cmd/go/internal/par/queue.go:58 +0x7c fp=0xc0000b7fd0 sp=0xc0000b7f60 pc=0x5f929c
            runtime.goexit()
                /home/rapm/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000b7fd8 sp=0xc0000b7fd0 pc=0x46e121
            created by cmd/go/internal/par.(*Queue).Add
                /home/rapm/local/go/src/cmd/go/internal/par/queue.go:56 +0x25a

            rax    0x58
            rbx    0x23d93c448
            rcx    0x29617405a
            rdx    0x0
            rdi    0xc000084358
            rsi    0x3
            rbp    0x23d93c390
            rsp    0x23d93c388
            r8     0xc000084358
            r9     0xf5ff
            r10    0x0
            r11    0x206
            r12    0x4015e0
            r13    0x7f7ffffe7a88
            r14    0xc0000861a0
            r15    0x46bee0
            rip    0x29617405a
            rflags 0x206
            cs     0x2b
            fs     0x0
            gs     0x0
            [context deadline exceeded]
            FAIL: testdata/script/mod_deprecate_message.txt:8: test timed out while running command

FAIL
FAIL    cmd/go  529.747s
ok      cmd/go/internal/auth    0.202s
...
ok      cmd/trace       4.029s
ok      cmd/vet 74.318s
FAIL
go tool dist: Failed: exit status 1

</pre>

**Comment by jayconrod** [comment]
It looks like the whole test run timed out, and this is the place it happened to time out.

@rialpamu Could you tell us more about this machine? Even the test that succeeded seem to be running much, much slower than I usually se. For example, `go test -short cmd/fix` passes for me in 1.229s, but here it's 47.487s. Did these tests run significantly faster in 1.16.6?

**Comment by rialpamu** [comment]
ALL TESTS PASSED in final go1.17
