### ISSUE TITLE
x/pkgsite: "Documentation not displayed" despite recognized license

### ISSUE THREAD

**Issue by quentinmit** [golang/go#47273]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/gitlab.com/fospathi/phyz/celestial/solsys
 
### What is your user agent?
 

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.80 Safari/537.36
 
### Screenshot
 

 
 
![image](https://user-images.githubusercontent.com/115761/126084600-94d8c729-4485-4593-804c-4e4893a8d0cd.png)

As far as I can tell, this package is licensed CC0-1.0, as detected by pkg.go.dev and manual inspection of the repo, but the documentation is still not being displayed. https://pkg.go.dev/license-policy appears to list CC0-1.0 as a supported license.

**Comment by seankhliao** [comment]
The licence needs to apply to the entire module, not just a package as is the case for the repo
