### ISSUE TITLE
Discussions need categories

### ISSUE THREAD

**Issue by martinheidegger** [golang/go#47278]
I have been trying to open a discussion, but the user interface failed because there are no discussion categories available. This seems to be a github bug, but it seems to be easily fixable by creating a category?

[![Image from Gyazo](https://i.gyazo.com/9414595e01213dd4bc31dfdca6777bd8.gif)](https://gyazo.com/9414595e01213dd4bc31dfdca6777bd8)

<img width="228" alt="Screen Shot 2021-07-19 at 16 09 54" src="https://user-images.githubusercontent.com/914122/126117811-a3e52905-11d7-4e13-bf05-33d86d90d09c.png">

**Comment by ALTree** [comment]
But we have a category, it's called Discussions: https://github.com/golang/go/discussions/categories/discussions

Must be a Giuthub bug.

**Comment by seankhliao** [comment]
That's a locked category only available to maintainers/admins

cc @rsc are Discussions only intended to be opened by Go team members?

**Comment by ALTree** [comment]
> are Discussions only intended to be opened by Go team members?

That would make sense.

**Comment by rsc** [comment]
Yes, for right now we are limiting the use of GitHub Discussions until we know exactly how we want to use it.
See the "About Discussions" discussion on https://github.com/golang/go/discussions.

**Comment by martinheidegger** [comment]
I was reading the "About Discussions" post as an invitation to open a discussion. Thank you for the clarification.

**Comment by rsc** [comment]
Thanks @martinheidegger. I reworded the ending to try to make that clearer.
