### ISSUE TITLE
A question about ‘go test’

### ISSUE THREAD

**Issue by wayyoungboy** [golang/go#47274]
### What version of Go are you using (`go version`)?

<pre>
$ go version 16.4

</pre>

### I have a question about ‘go test’

When I need to get the test report, I have to exit the program. 

But it makes the service cannot work for others. 

Is there a way to output coverage reports without interrupting the service？

THINKS

**Comment by cuonglm** [comment]
Go don't use issue tracker for asking question, please see https://github.com/golang/go/wiki/Questions
