### ISSUE TITLE
crypto/cipher.StreamWriter allocates too much memory when combined with compress/gzip.Writer

### ISSUE THREAD

**Issue by geovanisouza92** [golang/go#47287]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.6 linux/amd64
go version go1.15.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="$HOME/.cache/go-build"
GOENV="$HOME/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="$HOME/.local/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="$HOME/.local/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="$HOME/.local/go1.16"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="$HOME/.local/go1.16/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build534269485=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Trying to write large CSV files with `encoding/csv.Writer`, compressing with `compress/gzip.Writer` and encrypting with AES-CTR-256 (`crypto/*`, the problem is `crypto/cipher.StreamWriter`).

I've made a minimal (but very close to my real case) example here: https://github.com/geovanisouza92/go-cipher-writer-example

### What did you expect to see?

Small and mostly constant memory usage and allocations.

### What did you see instead?

327k alloc/op + ~80MB memory usage.

---

The issue #26578 reported a similar problem, but as I noticed [in this change](https://github.com/golang/go/commit/0fb6f5f21b20759a0cdbc25df0c152600fd93b4d) the implementation of `cipher.StreamWriter` has other issues that maybe is not possible to fix without a breaking change.

I also noticed that there's an optimization (#8740) planned that could help, but currently it seems unplanned.

I'm not sure about the implementation path I took (using a map instead changing the buffer like #26578 did), but for my case it's working fine.

---

Edit: after some investigation, I found that using `*bufio.Writer` between `gzip.Writer` and `cipher.StreamWriter` reduces drastically the allocations (-37% ~ -98%). I'll update my working example later.

**Comment by thanm** [comment]
@FiloSottile

**Comment by geovanisouza92** [comment]
As I'd updated my example, I can confirm that using `*bufio.Writer` between `gzip.Writer` and `cipher.StreamWriter` can workaround the problem.

The performance is far better than implementing `[]byte` reuse manually (and maybe safer too).

So, I'll close this issue and let it sit here for future reference.
