### ISSUE TITLE
x/pkgsite: cannot use gestures in Chrome on MacOS to navigate forward/backward under package discovery

### ISSUE THREAD

**Issue by nerg4l** [golang/go#47285]
### What is the URL of the page with the issue?

`https://pkg.go.dev/*`

For example, navigating between https://pkg.go.dev/search?q=http and https://pkg.go.dev/net/http.

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36

Which means "Google Chrome Version 91.0.4472.164 (Official Build) (x86_64)".

### What did you do?

1. Opened https://pkg.go.dev/.
2. Clicked on "http" in example searches.
  This navigated me to https://pkg.go.dev/search?q=http.
3. Clicked on "net/http".
  This navigated me to https://pkg.go.dev/net/http.
4. Tried to navigate backward via gesture. (Swipe from left to right with two fingers on trackpad.)

### What did you expect to see?

The browser should have navigated me back to https://pkg.go.dev/search?q=http.

### What did you see instead?

Nothing happened.

### Additional information

Safari and FireFox are not affected.

**Comment by thanm** [comment]
@julieqiu @jamalc
