### ISSUE TITLE
Why basic types cannot be casted in return, while composite types can be?

### ISSUE THREAD

**Issue by denisvmedia** [golang/go#47299]
Here is an example demonstrating the question:

```go
package main

import (
	"fmt"
)


type Float float64
func convert(f Float) float64 {
	return f // ERROR: cannot use f (type Float) as type float64 in return 
}

type FloatSlice []float64
func convertSlice(f FloatSlice) []float64 {
	return f // no error
}

func main() {
	fmt.Println("Hello, playground")
}
```

For your convenience you can find it here: https://play.golang.org/p/4WLrsYPo31L

Could anyone please point me to the language specification, where it defines (and maybe even explains) the compiler behavior in this case?

Thank you.

P.S. If there is no spec on that, what is at least the reason for this behavior?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by davecheney** [comment]
`Float`, and `float64` are named types, Go will not automatically convert from one named type to another, however it will convert from an anonymous type `[]float64` to a named type `FloatSlice`
