### ISSUE TITLE
server memory increase on no service state

### ISSUE THREAD

**Issue by smbms** [golang/go#47297]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
centos 7,Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz，cpu cores : 4
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build129724444=/tmp/go-build"
</pre></details>

### What did you do?

a new http server.
one client connect server,server used:

```
select{
case <-timer.C:
{
time.reset(120s)
}
}
```

--------------

at this time,
if another interface called,response the client request,otherwise block 120s response a timeout error.
looks like long rotation training.

-----------------

now stress testing，use 60k client request service.
after stable:
top cmd res = 3.5GB,

stop test:
at 30 min ago,top res=450M，（open GODEBUG=madvdontneed=1）,[if close madvdontneed memory down to 2G+- stabled],
and next 30min ago,top res=2GB.(no service state the memory increase 1.5GB ？？？)

------

### What did you expect to see?
the memory stabled at 450M+-.

### What did you see instead?
no service state the memory increase 1.5GB

--------

the prometheus & pprof & centos data
prometheus：
![Uploading image.png…](https://ftp.bmp.ovh/imgs/2021/07/6ddeb1e30a5582fa.png)

-----

pprof:
runtime.MemStats
Alloc = 240774520
TotalAlloc = 9840123880
Sys = 3056058064
Lookups = 0
Mallocs = 102905393
Frees = 102750194
HeapAlloc = 240774520
HeapSys = 2884337664
HeapIdle = 2639020032      -----------madvdontneed=1 not released? (madvdontneed=0 == madvdontneed=1)
HeapInuse = 245317632     ----------- inuse 240M
HeapReleased = 2613510144
HeapObjects = 155199
Stack = 1343488 / 1343488
MSpan = 951320 / 34816000
MCache = 13888 / 16384
BuckHashSys = 1591611
GCSys = 111649480
OtherSys = 22303437
NextGC = 479226528
LastGC = 1626748587738759502

NumGC = 472
NumForcedGC = 0
GCCPUFraction = 0.00030084105056857313
DebugGC = false
MaxRSS = 3041533952

----

graph :
HeapInuse ~= 240M

----

centos top RES=1944M

----

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
