### ISSUE TITLE
cmd/go/internal/test: -vet accepts bad input

### ISSUE THREAD

**Issue by colin-sitehost** [golang/go#47309]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GOOS="linux"
GOPATH="/home/user/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2105906029=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
https://play.golang.org/p/t6Q8DJU3ON6
```sh
go test .
go test -vet=all .
```

### What did you expect to see?
```
ok  	trash/five	(cached) [no tests to run]
deprecated flag provided: -all
```

### What did you see instead?
```
ok  	trash/five	(cached) [no tests to run]
# trash/five
./main.go:7:8: using r before checking for errors
FAIL	trash/five [build failed]
FAIL
```

### What would you like done?
This came out of development on #45963 [[CL 334873](https://golang.org/cl/334873)]. It was discovered that `go test -vet=all`, actually works today. This is because unlike what the docs say `-vet` simply passes the list of "checks", with `-` prefixes, to `go vet` as flag arguments.
> 	-vet list
>	    Configure the invocation of "go vet" during "go test"
>	    to use the comma-separated list of vet checks.
>	    If list is empty, "go test" runs "go vet" with a curated list of
>	    checks believed to be always worth addressing.
>	    If list is "off", "go test" does not run "go vet" at all.

This was is an intended feature and seems quite brittle. As such, we should pin `-vet` to the documented interface, or define what "flags" we accept and update the the documentation. If we are not expanding the definition, we should ignore or error on all the deprecated and non-check name flags: `-V`, `-source`, `-c`, `-printfuncs`, and `-printf.funcs`(anything with a dot). (This is very much a blocklist, since we want to allow new checks to be added over time.)

**Comment by thanm** [comment]
@matloob per owners

**Comment by bcmills** [comment]
FWIW, the `go vet` subcommand currently scrapes the flags here:
https://github.com/golang/go/blob/3e48c0381fd1beb78e993e940c3b46ca9898ce6d/src/cmd/go/internal/vet/vetflag.go#L81-L98

Running `go tool vet -flags` locally, I see that it actually has a fair amount of structure in the `Usage` field. Perhaps we should only forward flags whose `Usage` string is of the form `enable %s analysis`?

**Comment by bcmills** [comment]
I don't think we should allow configuration of flags like `-c` and `-v` in `go test -vet`. If users want that much control, they can run `go vet` separately from `go test`.

**Comment by colin-sitehost** [comment]
Sweet, I too do not see the benefit in having `-vet` be a generic way to pass arbitrary flags, so I have struck the following section from the description: (persisted for historical purposes)
> Otherwise, there are three main problematic cases.
>
> #### distinguished
> This may be resolved in [CL 334873](https://golang.org/cl/334873), but basically we should really not be accepting distinguished values and other things in the list of checks: e.g. `-vet=off,anything`.
>
> #### deprecated
> Because the contract that `-vet` provides is "run these checks", it is really confusing how `-vet=v` runs more linters than `-vet=""` (or not passing `-vet`). Since the list of flags labelled as `no effect (deprecated)` is finite and (hopefully) fixed, we can could ignore or error if any are passed.
>
> #### value
> If we are committing to allowing full configuration of `vet`, which may well be a bad idea, things like `-c`, takes values as input and should be able to be configured. This could be something like `-vet=asmdecl,c=3,atomic`, which is disabled today, by the failure to parse flag values containing `=`s. `-vet=c3` would also be fine and is quite coreutils.
>
>Also worth noting are deprecated check flags like `-compositewhitelist`, and their non-deprecated alternatives, `-composites.whitelist`, but that should work with the `-c` fix: `-vet=asmdecl,composites.whitelist=false,atomic`.
>
> #### four
> The `-V` flag causes output to be very long and unreadable, since it is runs for every package that is compiled for testing. Even if we allow arbitrary flags, I support ignoring this one explicitly.

**Comment by colin-sitehost** [comment]
> Perhaps we should only allow flags whose `Usage` string is of the form `enable %s analysis`?

I have some concerns about the complexity of needing to keep these two components in sync, but if there is a clean way to do that, or somehow share the canonical list of vet checks: I am game.

**Comment by nishanths** [comment]
@colin-sitehost: Somewhat tangential/unrelated to the main issue. But it could lead to a separate issue in which `go test` isn't following documented behavior. 

`go help test` documents that:
> If go vet finds any problems, go test reports those and does not run the test binary.

However, In this issue description, the output you saw for `go test -vet=all .` was:
```
# trash/five
./main.go:7:8: using r before checking for errors
FAIL	trash/five [build failed]
testing: warning: no tests to run
PASS
ok  	trash/five	0.101s
```

So if the test binary did run (indicated by the `PASS ok trash/five` part) despite the vet failure, then `go test` didn't work as documented.

Can you confirm the actual output you saw/are seeing? I haven't been able to reproduce on macOS.

**Comment by colin-sitehost** [comment]
<details><summary>My working directory contains the files from the <a href=https://play.golang.org/p/t6Q8DJU3ON6>play link</a> above.</summary>

```go
// main.go

package main

import "net/http"

func main() {
	r, err := http.Get("example")
	defer r.Body.Close()
	if err != nil {
		panic(err)
	}
	_ = r
}
```
```go
// main_test.go

package main
```

</details>

However, now I cannot reproduce it, so I have moved the old text from the description to not confuse the issue further:
```
# trash/five
./main.go:7:8: using r before checking for errors
FAIL	trash/five [build failed]
testing: warning: no tests to run
PASS
ok  	trash/five	0.101s
```

**Comment by bcmills** [comment]
> I have some concerns about the complexity of needing to keep these two components in sync, but if there is a clean way to do that, or somehow share the canonical list of vet checks: I am game.

I can think of at least two such ways.

One is to write a `go:generate` script that updates a map or function, and then verify that that map or function is up to date in a unit test. (That's the approach I used for #18682.)

Another is to invoke the `vet` tool once at run-time before running tests, as is currently done in `go vet`. But that only seems preferable if the `vet` tool itself can be specified at run-time, which is certainly true for `go vet` today but I think not for `go test`.

**Comment by bcmills** [comment]
@zpavlinovic, we currently propagate `-vet=a,b,c` as `-a -b -c`, yes. What I think we should do instead is not filtering, but validation: `go test` should fail outright if any of the `-vet` parameters does not name a valid (or, perhaps, a once-valid) analyzer flag.

**Comment by zpavlinovic** [comment]
> One is to write a `go:generate` script that updates a map or function, and then verify that that map or function is up to date in a unit test. (That's the approach I used for #18682.)

This is then probably the most robust way going forward.

**Comment by timothy-king** [comment]
https://github.com/golang/go/issues/35487 suggests having an exported list of analyzers available somewhere. This would be robust (but it does mean initializing all of the vet packages just to get their names).

**Comment by zpavlinovic** [comment]
Should we then block this issue until #35487 is resolved?

**Comment by bcmills** [comment]
I don't think we need to block it on #35487. We can already scrape `go tool vet -flags` for `Usage` matching `^enable .* analysis$` or `^deprecated alias for -.*$` to get a list of the supported analysis flags.

That issue seems to be asking for a way to list the analyses _used by default_ by `go test` and `go vet`, which are a subset of the analyses supported by the `vet` tool itself — and `cmd/go` already knows that subset anyway.

**Comment by zpavlinovic** [comment]
Ok, so the plan forward is to rely on `go tool vet -flags` to get the list of supported analysis flags.
