### ISSUE TITLE
type package FieldByName return me false and expected true - critical

### ISSUE THREAD

**Issue by ahmedyusef9** [golang/go#47301]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
didn't check

### What operating system and processor architecture are you using (`go env`)?
GOOS=windows
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

<img width="442" alt="Capture" src="https://user-images.githubusercontent.com/39097896/126346837-182554c5-1192-4a30-893c-880454eb3c5d.PNG">

### What did you expect to see?
comparison two equal string == true

### What did you see instead?
false

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by ianlancetaylor** [comment]
Please send code as ordinary text, not as an image.  I can't read your image at all.  Thanks.

**Comment by ahmedyusef9** [comment]
`type Test1 struct {
    Test2 struct {
        Test3      struct {
            Test4 struct {
                Example        string `json:"example"`
                
            }
        }
    }
}
// columns = ["Example"]
// element = ["value"]
func fun_test(element []string, columns []string) {
    obj := Test1{}
    for index, _ := range columns {
        if (reflect.ValueOf(&obj.Test2.Test3.Test4).Elem()).FieldByName(columnName).CanSet() { 
            ...
        }
    }
}`

it's really strange because it just return me false just for the first element on the columns string array
