### ISSUE TITLE
github: add Autolink References for CLs when possible

### ISSUE THREAD

**Issue by colin-sitehost** [golang/go#47310]
It is quite handy how issue tags, #0000, automatically link in gerrit. Assuming the golang org pays for GitHub Pro or GitHub Team, there is a way to autolink CLs in the other direction: [docs](https://docs.github.com/en/enterprise-server@3.1/github/administering-a-repository/managing-repository-settings/configuring-autolinks-to-reference-external-resources). If not, or if it is impossible to make "CL " work with their parser, please close this with prejudice.

**Comment by seankhliao** [comment]
"CL " with a space isn't allowed:
> Reference prefix must only contain letters, numbers, or -:/#

cc @golang/osp-team

**Comment by dmitshur** [comment]
Thanks for suggesting this. Unfortunately, I don't think we're on a plan that supports this feature. If that changes we should consider this.

**Comment by mvdan** [comment]
Perhaps we can leave this open for some time, to see if we could nudge GitHub or any of our contacts there for a solution? It seems unnecessary to give up so quickly :)

**Comment by dmitshur** [comment]
Sure, let's use it as a tracking issue then.

**Comment by seankhliao** [comment]
i think one of the bots might do this now?
either way, it doesn't look like github is going to give us this.
