### ISSUE TITLE
is a program, not an importable package

### ISSUE THREAD

**Issue by juanchehin** [golang/go#47313]
Good morning I'm new to goland, when I want to run "go run." I get "is a program, not an importable package" does anyone know how to solve this problem?

I already installed GO in VSC

I already put "_" and "." before import into main.go[](url)

![1](https://user-images.githubusercontent.com/40132117/126477809-0a72e0ca-b288-4208-b22b-8dd89dcdb9fe.png)

![2](https://user-images.githubusercontent.com/40132117/126477815-c6bc7492-5560-4115-86ad-d0b335358134.png)

![6](https://user-images.githubusercontent.com/40132117/126477794-af27d188-38fe-4fb2-9824-c4b8b6d7e2e3.png)

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
