### ISSUE TITLE
x/exp/vulndb/govulncheck: test fails when "unzip" is not in PATH

### ISSUE THREAD

**Issue by bcmills** [golang/go#47314]
`golang.org/x/exp/vulndb/govulncheck` is persistently failing on the `longtest` builders since [CL 329809](https://golang.org/cl/329809):

```
--- FAIL: TestKubernetes (7.89s)
    main_test.go:300: failed to build k8s: 
    main_test.go:301: exec: "unzip": executable file not found in $PATH
FAIL
FAIL	golang.org/x/exp/vulndb/govulncheck	40.964s
```

It probably needs a `t.Skip` if `exec.LookPath("unzip")` fails. (Compare [`golang.org/x/tools/internal/testenv.NeedsTool`](https://beta.pkg.go.dev/golang.org/x/tools@v0.1.5/internal/testenv#NeedsTool).)

**Comment by bcmills** [comment]
(This is a release-blocker for Go 1.17 via #11811, but I don't expect that it will take much effort to fix.)

**Comment by zpavlinovic** [comment]
I have created a small CL that should just make the failure go away. Will follow it up with a solution using standard libraries.
