### ISSUE TITLE
x/pkgsite: group search by module

### ISSUE THREAD

**Issue by jba** [golang/go#47320]
Currently, each result on the search page displays one package, and multiple packages from the same module are displayed as separate results. We plan to change that. Although each result will still display a single package—the highest-scoring one for its module—we will group other packages from that module together in the same result. For example, say module M has 100 packages, p1, p2 ..., p100, with p1 ranked highest. Currently search will show 100 results for M, one for each package. After this change, it will show one result, M/p1, with an indication that there are 99 other packages in module M.

We will also group versions of a module, showing the latest version and grouping the rest.

**Comment by julieqiu** [comment]
Reposted from https://github.com/golang/go/issues/47321#issuecomment-902673865

> These features are live on https://beta.pkg.go.dev! 🎉
> 
> Give it a try, and please [file an issue](https://golang.org/s/pkgsite-feedback) for any feedback.
