### ISSUE TITLE
cmd/go: add 'go mod vendor -o <dir>'

### ISSUE THREAD

**Issue by rsc** [golang/go#47327]
Thinking about how to get a copy of all the code that is needed for a given build, for uploading to some kind of a remote build (Google App Engine or other similar systems).

Right now if you upload just the main module, then the remote build has to resolve all the dependencies. But what if the dependencies are private modules, and the remote build has no access to them? This happens.

The solution I have used in the past is to run `go mod vendor` and then do the upload of the main module. That works, but then you have a vendor directory you need to remove (assuming you don't want it in you repo). 

What could be done instead is to have the uploader itself run `go mod vendor`, zip up the main module, and then delete the vendor directory. That's almost perfect except that I think it's bad form for an uploader to be making changes in the actual directory being uploaded.

If instead `go mod vendor` took a `-o` flag saying what directory to write the vendor tree to, then the uploader could write it to a temporary place and then combine that with the contents of the actual main module directory.

We should do this for ~~Go 1.17~~ Go 1.18.

In the long term, we might also consider some kind of formal "archive of everything for a build", so that you could `go mod archive -o x.zip`, but there's a lot to figure out there about exactly what that zip file looks like, how you build it, and so on. 

For now if we do `go mod vendor -o`, then that will unblock uploaders.

**Comment by tpaschalis** [comment]
I can take a stab if there's no one already on it. From a quick look, it looks straightforward; adding the new option, and working with a different [`vdir`](https://github.com/golang/go/blob/ecaa6816bfdbcef2ad749958a11a321de5c2ebd8/src/cmd/go/internal/modcmd/vendor.go#L77).

**Comment by rsc** [comment]
I think I confused myself about which was the next release and meant Go 1.18 for this.
