### ISSUE TITLE
x/website: Google has restricted access to websites hosted on google servers for some locations

### ISSUE THREAD

**Issue by ali-aminian** [golang/go#47339]
Hi

I'm interested in Golang and I'm from Iran. Unfortunately, Google has banned access to websites hosted in google servers for Iranian users. I would like to ask to host the golang.org website on some other servers from other hosts other than amazon and google with less draconian restrictions so that people from all around the world can use the content.

kind regards.

**Comment by ALTree** [comment]
See #14707 and its duplicates. I don't think hosting the website anywhere else will solve the issue.

**Comment by ali-aminian** [comment]
So I guess that means goodbye Golang and hello Rust.

**Comment by ali-aminian** [comment]
and by the way, hosting golang.org on a server not powered by google definitely solves the problem. I can easily access websites like:
https://www.python.org/
https://en.cppreference.com
https://www.rust-lang.org/
I only have trouble accessing websites hosted on google. Even if you are not willing to solve the problem please stop spreading misleading information.

**Comment by ALTree** [comment]
https://github.com/golang/go/issues/12380#issuecomment-135836101 says it's due to crypto libraries in the standard library. 

Do https://en.cppreference.com or https://www.rust-lang.org/ or https://www.python.org/ distribute crypto code?

**Comment by ALTree** [comment]
Note that github itself is available to Iranian users just because [github obtained a license from the US government to offer GitHub to developers in Iran](https://github.blog/2021-01-05-advancing-developer-freedom-github-is-fully-available-in-iran/). And it happened in 2021, just a few months ago(?).

**Comment by ali-aminian** [comment]
Thank you for your responses. I will pay more attention next time. I just ended up using the godoc installed through my Ubuntu package manager since google has banned even most VPN servers.
I really appreciate your clarifying the issue.
