### ISSUE TITLE
go/types: race condition due to lazy initialization of universeError

### ISSUE THREAD

**Issue by mdempsky** [golang/go#47345]
This program triggers a race condition in go/types on dev.typeparams since 24f9eb2de34d8d92dac4c6ffaa55ff2234c639d2:

```
package main

import (
	"go/types"
	"sync"
)

func main() {
	var wg sync.WaitGroup

	for i := 0; i < 2; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			types.Universe.Lookup("error").Type().Underlying().(*types.Interface).NumMethods()
		}()
	}

	wg.Wait()
}
```

/cc @findleyr @griesemer

**Comment by findleyr** [comment]
@mdempsky thanks for that repro!

This is because we lazily write the interface type set. We should eagerly add an empty type set for interfaces in the universe.

**Comment by findleyr** [comment]
It seems that gopherbot did not find the 'fixes' line on the previous CL, because it was not the first mention of this issue? In any case, closing as fixed.

**Comment by zikaeroh** [comment]
FWIW, gopherbot did, but GitHub won't close issues via commits until those commits are merged back to the main branch of the repo (so for `dev.` branches you have to wait or close manually).
