### ISSUE TITLE
x/pkgsite:https://pkg.go.dev/github.com/rachmatgithub/pdftrongotesting

### ISSUE THREAD

**Issue by rachmatgithub** [golang/go#47346]
Please help remove the test page from pkg.go.dev.

https://github.com/rachmatgithub/pdftrongotesting

Thank you!

**Comment by julieqiu** [comment]
You can do that by retracting the module. See instructions here: https://go.dev/about/#removing-a-package.

**Comment by rachmatgithub** [comment]
I tried retracting the module, but its still listed under pkg.go.dev? Also
I tried removing/deleting my other repo and its also still listed in
pkg.go.dev. Any suggestions?

Thanks.

**Comment by julieqiu** [comment]
We can remove the package for you. We'll close this issue once that's done.

**Comment by rachmatgithub** [comment]
Thanks. Below are the packages listed still in go.dev even though I already
made it private and didnt list them:

https://github.com/rachmatgithub/pdftrongo
https://github.com/rachmatgithub/pdftrongosharedlib
https://github.com/rachmatgithub/pdftrongotesting

Thanks much.

**Comment by julieqiu** [comment]
We can remove those from pkg.go.dev.

Anytime you run `go get` on a public repository, a module is published to https://proxy.golang.org. pkg.go.dev watches that site for data, which is how it is added to the site. https://go.dev/about/#adding-a-package has more information on this process. 

Deleting a repository or making it private later on will not remove that code from either proxy.golang.org or pkg.go.dev. The FAQ section of https://proxy.golang.org has more information on this:

> I removed a bad release from my repository but it still appears in the mirror, what should I do?
> 
> Whenever possible, the mirror aims to cache content in order to avoid breaking builds for people that depend on your package, so this bad release may still be available in the mirror even if it is not available at the origin. The same situation applies if you delete your entire repository. We suggest creating a new version and encouraging people to use that one instead.

**Comment by rachmatgithub** [comment]
Thanks much for the info. Yeah please help remove those from pkg.go.dev
then.

Cheers.

**Comment by rachmatgithub** [comment]
Sorry, I missed one more. So there should be 4 packages that need removal:

https://github.com/rachmatgithub/pdftrongo
https://github.com/rachmatgithub/pdftrongosharedlib
https://github.com/rachmatgithub/pdftrongotesting
https://github.com/rachmatgithub/pdftrongo-linux

Thanks!

**Comment by julieqiu** [comment]
Would you like all packages under github.com/rachmatgithub to be removed?

**Comment by rachmatgithub** [comment]
Yes please, thanks!

**Comment by julieqiu** [comment]
Done.

**Comment by rachmatgithub** [comment]
Thank you so much, Julie!
