### ISSUE TITLE
Resetting a bufio.Writer seems to mutate for loop counter and loops indefinitely 

### ISSUE THREAD

**Issue by uri** [golang/go#47350]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes I tried using *go1.17rc1* as well

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/[redacted]/Library/Caches/go-build"
GOENV="/Users/[redacted]/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/[redacted]/dev/go/pkg/mod"
GONOPROXY="[redacted]/[redacted]/*,[redacted]/[redacted]/*"
GONOSUMDB="[redacted]/[redacted]/*,[redacted]/[redacted]/*"
GOOS="darwin"
GOPATH="/Users/[redacted]/dev/go"
GOPRIVATE="[redacted]/[redacted]/*,[redacted]/[redacted]/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/[redacted]/asdf/installs/golang/1.16.5/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/[redacted]/.asdf/installs/golang/1.16.5/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zc/4spbcbls0cb3mzcjpx83s60h0000gn/T/go-build1084932043=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I run the following:

```go
package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"sync"
)

func main() {
	_, pipew := io.Pipe()
	bufw := bufio.NewWriter(pipew)
	w := io.MultiWriter(os.Stdout, bufw)

	var wg sync.WaitGroup

	wg.Add(1)
	go func() {
		for i := 0; i <= 1819; i++ {
			if i%1000 == 0 {
				bufw.Reset(w)
			}
			fmt.Fprintf(w, "%d\n", i)
		}
		wg.Done()
	}()
	wg.Wait()
}
```

I realize that `bufw.Reset(w)` is not what I want and that I should have actually used `bufw.Reset(pipew)` and reset the buffer before it actually breaches the max size. However the behaviour of this program is still quite unexpected. 

### What did you expect to see?

Program to eventually finish.

### What did you see instead?

Seemingly infinite loop.

**Comment by neild** [comment]
The `bufw.Reset(w)` call configures `bufw` to write to itself, since `w` is a `MultiWriter` writing to `bufw`.

**Comment by uri** [comment]
I oh I see, so it's not actually looping indefinitely.
