### ISSUE TITLE
cmd/link: generate debugging information to display inlined functions in backtraces

### ISSUE THREAD

**Issue by remyoudompheng** [golang/go#4735]
<pre>Inlined functions do not show up in backtraces. It would be interesting to add support
for inlined functions in backtraces so that inlining of non-leaf functions does not
break behaviour.</pre>

**Comment by tdewolff** [comment]
Does this happen to be on anyone's radar for 1.8 or 1.9? Or is this a low-priority feature request?

More aggressive inlining would certainly give a large performance boost to a lot of constructs. For example, inlining thunk functions (#8421) and inlining functions that can't inline all the way down (@dr2chase comment in #11189). The last one would certainly help me in one spot: https://github.com/tdewolff/buffer/blob/master/lexer.go#L158, which is a function that is called very often but only sometimes calls the costly `read` function. `Peek` would increase performance for the parsers using this library by 10%-20%, which is a lot!

**Comment by thanm** [comment]
As far as I know, this is now fixed (see proposals [19348](https://go.googlesource.com/proposal/+/master/design/19348-midstack-inlining.md) and [22080](https://go.googlesource.com/proposal/+/master/design/22080-dwarf-inlining.md)). Closing, please re-open if needed.
