### ISSUE TITLE
reflect, unsafe: should provide access to non-exported methods

### ISSUE THREAD

**Issue by fenginsc** [golang/go#47356]
Hello everyone, after version 1.11, access to non-exported methods was cancelled, but from a flexibility point of view, access to non-exported methods should be provided.Other languages do the same, otherwise it feels limited to use.
Thanks.

**Comment by ianlancetaylor** [comment]
What kind of access do you suggest?

Note that even before 1.11 the reflect package did not permit calling unexported methods.

**Comment by robpike** [comment]
The reflect package allows one to examine the types in a program. It is not intended to be a way to defeat the type system. It does not step outside the bounds of Go's types and values, it just allows one to write programs that work on types not known at compile time.

If the author of the package didn't want that method available, it does not matter what the mechanism is: it will not be available.

**Comment by fenginsc** [comment]
Maybe you don't think Java, which can provide private method calls, is very good?

**Comment by beoran** [comment]
Yes, I can only speak for myself but in my opinion Java is not very good if it allows to bypass the type system like this.

**Comment by wdvxdr1123** [comment]
Using unsafe and linkname, it's possible to call a non-exported method for now.
