### ISSUE TITLE
spec: typographical inconsistency in character literals

### ISSUE THREAD

**Issue by rillig** [golang/go#47368]
### What did you do?

* Carefully read through https://golang.org/ref/spec#Rune_literals.

### What did you expect to see?
* The Unicode code points around the text "alert or bell" should be sorted.
* The Unicode code points around the text "alert or bell" should either use uppercase or lowercase hexadecimal digits.

### What did you see instead?
* There ordering of the code points is not apparent. It is neither alphabetical nor by code point nor "vertical first, then horizontal".
* U+000D is uppercase, U+000b is lowercase.

These inconsistencies are not critical in any way, I just wondered whether there was some reason for this inconsistency and for ordering the code points in exactly this way.

**Comment by ianlancetaylor** [comment]
The sorting is alphabetical by the single-character escape.

But I agree that the capitalization ought to be consistent.
