### ISSUE TITLE
net/url: QueryEscape() doesn't escape tilde

### ISSUE THREAD

**Issue by alive** [golang/go#47379]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.16.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
see go version

</pre></details>

### What did you do?

https://play.golang.org/p/meXdB3_Iklu

### What did you expect to see?
I expected to see the tilda characters converted to their URL escaped values: %7E.

### What did you see instead?
The tilda characters were not converted.

According to this: https://jkorpela.fi/tilde.html tildas are no long a character that must be encoded. However, I think they still should be for safety, or at least there should be an option to encode them. Chrome browser, for example, still encodes tildas in the body of a post request, which is where my use case lies.

**Comment by seankhliao** [comment]
That page refers to an obsoleted RFC

From the current [RFC 3986 Section 2.3](https://datatracker.ietf.org/doc/html/rfc3986#section-2.3):
> For consistency, percent-encoded octets in the ranges of ALPHA
   (%41-%5A and %61-%7A), DIGIT (%30-%39), hyphen (%2D), period (%2E),
   underscore (%5F), or tilde (%7E) should not be created by URI
   producers and, when found in a URI, should be decoded to their
   corresponding unreserved characters by URI normalizers.

What specific usecase requires an escaped tilde?

**Comment by alive** [comment]
that section of the RFC refers to URI only, not post body data, correct?
in my specific case, I'm trying to send an http post request to a website and the tilda character present in the post data not being encoded caused a bug.
Chrome,firefox,etc all encode '~' in the body of a post request, so I think Go should consider doing that as well.
