### ISSUE TITLE
Go get is pulling commit hash from wrong tag

### ISSUE THREAD

**Issue by DONSA** [golang/go#47378]
### What version of Go are you using (`go version`)?

<pre>
go version go1.16.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nulop/Library/Caches/go-build"
GOENV="/Users/nulop/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/nulop/go/pkg/mod"
GONOPROXY="github.com"
GONOSUMDB="github.com"
GOOS="darwin"
GOPATH="/Users/nulop/go"
GOPRIVATE="github.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/nulop/sdk/go1.16.6"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/nulop/sdk/go1.16.6/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/nulop/go/src/github.com/donsa/gqlgen/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fw/303jhf993zv1wr79_d3w9zm9vhc0f6/T/go-build3030822101=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
`go get github.com/vektah/dataloaden@a19b9a6e7c9e61b67e20b6c862b49ba0dab1ef27`.

### What did you expect to see?
Required module inside go.mod to be `github.com/vektah/dataloaden v0.3.0-0.20190515034641-a19b9a6e7c9e`.

### What did you see instead?
Required module inside go.mod is `github.com/vektah/dataloaden v0.2.1-0.20190515034641-a19b9a6e7c9e`

Go get Is pulling it from v0.2.1 ([a tag that doesn't even exist](https://github.com/vektah/dataloaden/tags)).
I believe this is not correct because this specific [commit](https://github.com/vektah/dataloaden/commit/a19b9a6e7c9e61b67e20b6c862b49ba0dab1ef27) belongs to tag v0.3.0.
By cloning `dataloaden` repo and running `git tag --contains a19b9a6e` it points to tag v.0.3.0.
By doing `git log --pretty=oneline v0.2.0...v0.3.0` I can see that the commit hash belongs to it as well.

Then if someone tries to use any package that imports `dataloaden` (as an indirect dependency), `go mod tidy` will remove it from or go.sum file (I believe because it can't find that commit hash associated with that tag) and then will complain about it:
```
$ go generate ./...
/Users/nulop/go/pkg/mod/github.com/vektah/dataloaden@v0.2.1-0.20190515034641-a19b9a6e7c9e/pkg/generator/generator.go:12:2: missing go.sum entry for module providing package github.com/pkg/errors (imported by github.com/vektah/dataloaden/pkg/generator); to add:
go get github.com/vektah/dataloaden/pkg/generator@v0.2.1-0.20190515034641-a19b9a6e7c9e
internal/dataloader/dataloader.go:1: running "go": exit status 1
```
And if we run the proposed command it will obviously fail:
```
go get: github.com/vektah/dataloaden/pkg/generator@v0.2.1-0.20190515034641-a19b9a6e7c9e: invalid pseudo-version: preceding tag (v0.2.0) not found
```

**Comment by seankhliao** [comment]
`v0.3.0` points to https://github.com/vektah/dataloaden/commit/9d6b85cf15084a11c813eb0ee91c604b0e4a1de0 which is the result of a merge of https://github.com/vektah/dataloaden/commit/a19b9a6e7c9e61b67e20b6c862b49ba0dab1ef27

In this case `go` is creating a [pseudoversion](https://golang.org/ref/mod#pseudo-versions) based on the most recent tag before the commit, which would be `v0.2.0`

**Comment by DONSA** [comment]
Ok, I will try to understand why go mod tidy for v1.16.6 is removing `dataloaden` dependency from my go.sum even though is being referenced in `gqlgen` go.mod. I think that's the reason why its failing.
Thanks for the clarification.
