### ISSUE TITLE
x/blog:

### ISSUE THREAD

**Issue by divyanshu-nference** [golang/go#47386]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.6 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Not sure, this may even be trivial.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
COMMAND : echo $GOPATH
OUTPUT : ~/go/1.16.6
COMMAND : echo $GOROOT
OUTPUT : ~/.goenv/versions/1.16.6

### What did you expect to see?
Since the src/go.mod file is in $GOROOT/src/go.mod and not in $GOPATH I doubt whether there's a typo in the article or is it different because I have goenv installed?

**Comment by seankhliao** [comment]
What page are you trying to open?

**Comment by divyanshu-nference** [comment]
@seankhliao 
https://blog.golang.org/using-go-modules

**Comment by seankhliao** [comment]
Note the article says **outside** GOPATH (and fwiw also GOROOT)

**Comment by divyanshu-nference** [comment]
Okay, I see.
But there's no src file under my $GOPATH

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
