### ISSUE TITLE
achieve mysql dump and restore in one command

### ISSUE THREAD

**Issue by ahamedmulaffer** [golang/go#47396]
i wanted to run this command using golang how can i achieve it using exec.Command

mysqldump -u root -p database_name | mysql -h remote_host -u root -p remote_database_name

please anyone help me

Thanks
Mike

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
