### ISSUE TITLE
x/build/cmd/relui: draft minor release announcement e-mail

### ISSUE THREAD

**Issue by toothrot** [golang/go#47404]
Release announcement task: Renders a template based on the release being issued:

Template: https://play.golang.org/p/RVv1MSPkHE3
```go
	versionCurrent = "1.15.2"
	versionPrev    = "1.14.9"
```

**Comment by abderrahmaneMustapha** [comment]
hello can i start working on this , i want to help ???

**Comment by dmitshur** [comment]
Thanks for offering help here, but this ended up being intertwined with #47405 and will be resolved as part of that.
