### ISSUE TITLE
x/build/cmd/relui: create tweet for a minor release

### ISSUE THREAD

**Issue by toothrot** [golang/go#47402]
Inside of a relui workflow, you should be able to start a step called Tweet Release Announcement, which requires the following information:

current version released: 1.16.2
new old version: 1.15.10
GOOS/GOARCH for image: linux/amd64
filesize for image: from golang.org/dl API?

After the task is completed, there should be a link called Create Tweet with the tweet text prepopulated as per: https://play.golang.org/p/AomPsnwSG9t, as well as a rendering of the image at https://play.golang.org/p/no9H86XIi0m

**Comment by abderrahmaneMustapha** [comment]
can i start working on this , i want to help ???

**Comment by dmitshur** [comment]
Thanks for offering help Toumi! This issue tracks a part of a larger ongoing work and has an assignee, so there isn't a good opportunity here at this time.

Heschi, if you don't mind, I'll send a CL for this as a way of making more incremental progress on #47405. I've made a staging twitter account that I want to test this with first.
