### ISSUE TITLE
cmd/link: An incorrect address was generated when using the LD linker

### ISSUE THREAD

**Issue by dangit815** [golang/go#47416]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.6 linux/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
[root@localhost bolt-case-1.16.6-ld]# go env
GO111MODULE="off"
GOARCH="arm64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/danny/go-1.16.6"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/danny/go-1.16.6/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1236999023=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

main.go

```
package main
  
import "fmt"

func main() {
    fmt.Println("Hello World!")
}
```

Build command:
`go build -a -buildmode=pie -ldflags='-linkmode=external -extld=gcc -extldflags "-fPIE -pie -Wl,--emit-relocs"'`

### What did you expect to see?

I run `objdump -r -D main`, get this:
![image](https://user-images.githubusercontent.com/27342851/127119312-1d164d89-5bda-42b3-bee8-3ecda6e6b034.png)

I run `readelf -r main`, get this:
![image](https://user-images.githubusercontent.com/27342851/127119656-84a494f5-12cd-48df-b9d8-00a3664f65dd.png)

The first 8 bytes of “runtime.buildVersion” object is the pointer to the string with golang version name. The pointers address (0x000db902) is invalid and fixed at runtime by the relocation on that address (0x190a00).
The address 0xdb0e1 is valid, pointing to the string and works fine at runtime.The same address (0xdb0e1) must be written in the runtime.buildVersion instead of garbage one.

### What did you see instead?

The pointers address (0x000db902) is invalid, different from 0xdb0e1.

**Comment by cherrymui** [comment]
Could you explain why it _must_ be written to the binary? If I understand your words correctly, it will be patched at run time by the dynamic linker anyway, so the program runs correctly?

**Comment by dangit815** [comment]
OK, Maybe my expression is not very clear and easy to misunderstand.

**Comment by dangit815** [comment]
Yes, maybe my expression is not very clear and easy to misunderstand.
In my opinion, when using ld linker, the golang runtime library is still statically linked to the binary, some other dynamic library like libc.so is dynamically linked to binary. We can use `ldd` to see which dynamic libraries are linked by this binary:
![image](https://user-images.githubusercontent.com/27342851/127598830-38f643a4-16c2-4653-8711-5cfc89736b0c.png)
So the pointers address on that address (0x190a00) should have been relocated to the correct address(0xdb0e1) in the binary at the time of linking(Link Time Relocation), not Load Time Relocation(at runtime).
I can show two correct examples.
1. use golang internal linker
`go build -a -buildmode=pie main.go`
Run `objdump -r -D`, get this:
![image](https://user-images.githubusercontent.com/27342851/127612343-972ef58c-7ada-4d22-ae7b-4b6ed13c16dd.png)
Run `readelf -r`, get this:
![image](https://user-images.githubusercontent.com/27342851/127612435-3c08b7a1-2abd-4398-ad55-11a66b6f6b22.png)
Obviously, the pointers address on that address (0x19ebe0) has been relocated to the correct address(0x000a0821) in  the binary.
2. use gold linker
`go build -a -buildmode=pie -ldflags='-linkmode=external -extld=gcc -extldflags "-fuse-ld=gold -fPIE -pie -Wl,--threads -Wl,--emit-relocs"'`
Run `objdump -r -D`, get this:
![image](https://user-images.githubusercontent.com/27342851/127613136-eaadf4c2-1f66-407d-b8d6-bfe8eb16ac45.png)
Run `readelf -r`, get this:
![image](https://user-images.githubusercontent.com/27342851/127613230-3499316a-b5ab-4831-bbfe-66734f1e9585.png)
The pointers address on that address (0x190a00) has been relocated to the correct address(0x000db0c1) in  the binary.

Thanks.

**Comment by cherrymui** [comment]
As you use `-buildmode=pie`, this is a PIE binary, which means it will be relocated at load time and dynamic relocations will be applied (even the Go runtime is included in the binary "statically").

Also, as you mentioned, when using external linking the final bytes are actually written out by the external linker, not the Go linker. I'm not sure we have control with that. (Even we have, I'm not sure this is necessary, as the dynamic linker will overwrite it anyway.)

**Comment by dangit815** [comment]
Do you think this is a bug of ld linker? Is it possible that it is related to the mechanism of go calling external linker?

If this is a bug in the ld linker, we may not be able to solve it on golang.

**Comment by cherrymui** [comment]
> So, do you think this is a bug of ld linker?

I don't think this is a bug. The generated program executes correctly (if I understand what you said correctly).

I think we can close this. Feel free to reopen if you disagree. Thanks.
