### ISSUE TITLE
types2: adjust types reported for shift expressions with constant RHS to match `go/types`

### ISSUE THREAD

**Issue by findleyr** [golang/go#47410]
As discussed in #47243, go/types should preserve the type of untyped constants on the RHS of a shift expression.

However, it does this inconsistently for integral vs non-integral types. Consider
```go
  var s int
  var _ = s << 1
  var _ = s << 2.
```
In 1.16 (and probably earlier), go/types reports the type of `1` as `untyped int`, but the type of `2.` as `uint`. It should preserve the type of `2.` as `untyped float`.

https://play.golang.org/p/aZZ48onPW2z

We're going to preserve this behavior for 1.17, but should try to fix it for 1.18.

CC @griesemer

**Comment by ianlancetaylor** [comment]
@griesemer This is in the 1.18 milestone; time to move to 1.19?  Thanks.

**Comment by griesemer** [comment]
There's a pending CL with failures. It's on my list to investigate.

**Comment by griesemer** [comment]
The issue here is what type is reported through the API but in contrast to `go/types` the current API works for the compiler. Eventually we want `types2` to match `go/types` in this respect but it doesn't seem important to do this for 1.18.

**Comment by griesemer** [comment]
Moving to 1.20. Should make the adjustment for use with the unified IR.

**Comment by griesemer** [comment]
Moving to 1.23.

**Comment by griesemer** [comment]
Moving to 1.24.

**Comment by griesemer** [comment]
It appears that this has been fixed (probably through a combination of the CLs mentioned in this issue). The [playground example](https://go.dev/play/p/aZZ48onPW2z?v=gotip) reports:
```
Types and Values of each expression:
 5: 8 | int                 | int
 6: 6 | s                   | int
 6: 6 | s << 1              | int
 6:11 | 1                   | untyped int = 1
 7: 6 | s                   | int
 7: 6 | s << 2.             | int
 7:11 | 2.                  | untyped float = 2
```
i.e., the recorded types of `1` and `2.` are as expected.
Also, `Checker.shift` is identical between go/types and types2 (modulo AST representation differences).

Closing and considered fixed.
