### ISSUE TITLE
x/pkgsite: dark theme preference not persisting

### ISSUE THREAD

**Issue by nishanths** [golang/go#47423]
### What is the URL of the page with the issue?
  
e.g. https://pkg.go.dev/net/http

But not https://pkg.go.dev/license-policy.

### What is your user agent?
 

Google Chrome:
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36

### Screenshot
 

 
Not useful. 
 
### What did you do?
 
The issue is possibly related to cookies, hence the use of incognito browser window for reliable reproducibility.

To preface, my system uses a light theme. 

In a new incognito window:

* Go to https://pkg.go.dev/net/http.
* Light theme is rendered, as expected.
* Pressed `t` (keyboard shortcut, albeit undocumented, to toggle light/dark mode).
* Page switched to dark theme, as expected.
* Inspected cookies by logging `document.cookie`; it contains `prefers-color-scheme=dark`, as expected.
* Reloaded the page. 
 
### What did you expect to see?
 
The page to render in dark mode.
 
### What did you see instead?

The page rendered in light mode.

It appears that the cookie `prefers-color-scheme` isn't being respected.

If I repeat the above steps for the URL https://pkg.go.dev/license-policy in a separate incognito window, the dark theme preference is respected. So it appears to also be something to do with package pages (e.g. `net/http`) vs. "static" pages (`license-policy`).

**Comment by nishanths** [comment]
# Debugging notes

These are with `curl/7.64.1`.

## https://pkg.go.dev/net/http

I tried three kinds of requests: no cookie, explicit light-theme cookie, and explicit dark-theme cookie.
```
% curl -sN 'https://pkg.go.dev/net/http' | head
% curl -sN --cookie 'prefers-color-scheme=light' 'https://pkg.go.dev/net/http' | head
% curl -sN --cookie 'prefers-color-scheme=dark' 'https://pkg.go.dev/net/http' | head
```
For all three requests, the response HTML did not have `data-theme="dark"`:
```
<html lang="en" data-layout="responsive" >
```
I would have expected it to have `data-theme="dark"` for the last request.

## https://pkg.go.dev/license-policy

I tried the same with the `license-policy` page.

```
% curl -sN 'https://pkg.go.dev/license-policy' | head
% curl -sN --cookie 'prefers-color-scheme=light'  'https://pkg.go.dev/license-policy' | head
% curl -sN --cookie 'prefers-color-scheme=dark'  'https://pkg.go.dev/license-policy' | head
````
The first two responses, as expected, have:
```
<html lang="en" data-layout="" >
```
The last one, as expected, has:
```
<html lang="en" data-layout="" data-theme="dark">
```

**Comment by jamalc** [comment]
Thank you for the detailed issue! The keyboard shortcut wasn't documented yet because it was mainly intended for debugging purposes. The caching strategy we use for the documentation page complicates setting a persistent theme choice that is rendered on the server. We'll need to rely on the visitors system-wide prefers-color-scheme setting while we figure out a workaround.
