### ISSUE TITLE
x/pkgsite: document dark mode

### ISSUE THREAD

**Issue by 89z** [golang/go#47421]
Im not sure what happenend, but some malicious user defaced the docs site:

> ![Untitled](https://user-images.githubusercontent.com/73562167/127153963-863341a2-b695-410f-93d0-bba534b3e669.png)

**Comment by 89z** [comment]
@julieqiu @jba @jamalc please, stop breaking my workflow. I use the doc site often, so I dont appreciate these unannounced changes with no switch to revert.

1. https://blog.golang.org/

**Comment by jba** [comment]
If you're referring to dark mode, you should be able to turn it off. Try typing `t` on any page.

**Comment by 89z** [comment]
@jba thanks, that seems to fix it, but why is it not documented?

~~~
PS C:\> curl -s https://pkg.go.dev/golang.org/x/net | rg dark
<div class="go-Header-inner go-Header-inner--dark">
PS C:\> curl -s https://pkg.go.dev/golang.org/x/net | rg mode
<img class="go-Icon" height="24" width="24"
src="/static/shared/icon/chrome_reader_mode_gm_grey_24dp.svg" alt="">
~~~

**Comment by ALTree** [comment]
Looks like it's not listed in the keyboard shortcuts window that appears on:

**Comment by 89z** [comment]
@ALTree "how to disabled dark mode" is not valid english

**Comment by 89z** [comment]
https://github.com/golang/go/issues/36980

**Comment by 89z** [comment]
Sigh. Can @julieqiu @jba @jamalc please reopen the issue. Its demonstrably not fixed yet:

~~~
PS C:\> curl -s https://pkg.go.dev/golang.org/x/net | rg dark
<div class="go-Header-inner go-Header-inner--dark">
PS C:\> curl -s https://pkg.go.dev/golang.org/x/net | rg mode
<img class="go-Icon" height="24" width="24"
src="/static/shared/icon/chrome_reader_mode_gm_grey_24dp.svg" alt="">
~~~

**Comment by fzipp** [comment]
> Try typing `t` on any page.

Typing `t` doesn't toggle the mode on macOS if the system preference is "Dark Mode". If the system preference is "Light Mode" the toggling works as expected.

**Comment by jamalc** [comment]
Fixed in https://golang.org/cl/337870.

**Comment by 89z** [comment]
Please, stop closing issues that are not fixed:

~~~html
PS C:\> curl -s https://pkg.go.dev/golang.org/x/net | rg dark
    <div class="go-Header-inner go-Header-inner--dark">
PS C:\> curl -s https://pkg.go.dev/golang.org/x/net | rg mode
      <img class="go-Icon" height="24" width="24" src="/static/shared/icon/chrome_reader_mode_gm_grey_24dp.svg" alt="">
~~~

CC @julieqiu @jba @jamalc

**Comment by fzipp** [comment]
@89z Merged isn't deployed. It will be fixed with the next deployment.

**Comment by jba** [comment]
This isn't quite persisting across all pages for me. (I'm using Chrome on a Mac.) 

1. Go to pkg.go.dev
2. Click out of search bar, type `t`; enter dark mode
3. click on "commands" to search for commands (url https://pkg.go.dev/search?q=command); in light mode now.

I wonder if it has something to do with the cache? Indeed, when I add a cache-busting query param, I see that search result page in dark mode.

**Comment by jba** [comment]
@89z, a word about how the tools work: when we prepare a CL/PR that we believe fixes an issue, we write "Fixes #NNNN" in the description. When the CL is submitted, GitHub notices that comment and closes the issue. That's a great convenience for developers, but unfortunately it means that issues get closed before users observe the fix—for projects that deploy rarely, perhaps weeks before they observe it. We deploy approximately daily (not on Fridays, holidays or weekends) so the lag is not great, but it is there. It's fine to comment on a closed issue asking when the next deployment or release or whatever will happen.

I hope that makes it clear that we're not trying to shut you down or minimize what you're going through.

**Comment by wxolp** [comment]
@jba apparently someone banned @89z from commenting on any issue - can you advise?

**Comment by Lyoness** [comment]
@89z has been been banned on the issue tracker for repeated violations of the [Go Code of Conduct](https://golang.org/conduct).

Specifically: 

- insulting/derogatory comments and language.
- repeated conduct considered inappropriate in a professional setting.

This repeated behavior is not in accordance with the Go CoC [values](https://golang.org/conduct#values) and [standards](https://golang.org/conduct#our-standards). Corrective action is in line with maintainer [responsibilities](https://golang.org/conduct#our-responsibilities) and at their discretion. The Go CoC Conduct board reviewed the entire history of behavior in the issue tracker, and concluded that a ban was appropriate corrective action. 

As the Go CoC states
>[We do not believe that all conflict is bad; healthy debate and disagreement often yield positive results. However, it is never okay to be disrespectful](https://golang.org/conduct#conflict-resolution).  

As the Go project continues to grow, maintainers manage an increasing load of issues. We understand user frustrations are a main motivation of taking the time to report issues, and as engineers who have used other software, we empathize with this frustration. Maintainers do their best to look at every issue, and determine the most helpful course of action. But Go has reached an issue volume [[7,335 Open     39,745 Closed](https://github.com/golang/go/issues?q=), as of today], where every snarking, unproductive, disrespectful comment is starting to feel like death by a thousand cuts. Our maintainers are not only human, but their well-being is vital to the success of Go. 

 Therefore, the Go Code of Conduct stewards are more actively enforcing the "never ok to be disrespectful" clause of the CoC, and giving maintainers full agency to take corrective actions in Go project spaces where the Go CoC is in effect.   

-Go CoC board.

**Comment by wxolp** [comment]
> * insulting/derogatory comments and language.

@89z simply asked politely to stop closing an issue that is not fixed. Regardless of any Golang processes, the simple fact of the matter is that, at the time @89z comment was posted, the issue was in fact not fixed, so its a valid concern.

If the Go team is going to arbitrarily close issues before they are fixed, thats their business, but a common courtesy would be a closing comment, such as:

> This issue is now fixed upstream. Please allow X days for change to be reflected on public facing site.

Thats all it would have taken, and any visiting the page would have understood the status of the issue. Instead you want to blame @89z for **your poor communication**. Well OK then, I wont bother you any more.

1. https://github.com/golang/go/issues/47421#issuecomment-888388205

**Comment by mvdan** [comment]
We should probably fold https://github.com/golang/go/issues/47553 into this issue, because "allow users to discover that there's a dark mode" via a button/setting somewhere is probably in line with documenting the feature.

**Comment by mvdan** [comment]
@wxolp worth noting that the ban came after a number of threads and comments from the person, many of which have been deleted by now. Hence "repeated violations". It's understandable that, by just looking at a single thread in isolation, the ban might seem out of place.

**Comment by tv42** [comment]
This was absolutely non-discoverable and way too easy to trigger by accident. Please reconsider dedicated a single-button alphabetical shortcut to such an annoying thing that's easy to toggle but hard to discover.

**Comment by cespare** [comment]
Keyboard shortcuts are appropriate for actions which need to be performed very often -- so much so that learning and memorizing a shortcut pays off in efficiency savings over time.

Toggling dark mode is essentially the opposite of that. People who like dark mode will turn it on once. Nobody needs to rapidly toggle it back and forth repeatedly every day.

I would be surprised if most uses of the `t` shortcut are intentional.

**Comment by jamalc** [comment]
Keyboard shortcut has been removed and replaced with a footer icon to indicate the active theme.
