### ISSUE TITLE
x/tools/gopls: stale embed diagnostics when preceded by const block

### ISSUE THREAD

**Issue by myitcv** [golang/go#47436]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.17-849b791129 Sun Jul 25 17:16:20 2021 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.1.5-0.20210708231608-69948257bde7
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.0.0-20210708231608-69948257bde7
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/myitcv/gostuff/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.17-849b791129 Sun Jul 25 17:16:20 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1114119742=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Firstly, a demonstration of a working setup:

```
-- dir/file.txt --
-- dir/other.go --
-- main.go --
package p

import "embed"

//go:embed main.go *.txt
var myFS embed.FS
```

Sequence is:

* Open `main.go`
* See diagnostic for bad `go:embed` directive
* Fix it, see diagnostic disappear
* Remove fix, see diagnostic return

The corresponding log file: [working.log](https://github.com/golang/go/files/6892370/working.log)

Things go wrong however if there is a `const` declaration list before the `go:embed` directive (at least my hacking seems to demonstrate this as the problem):

```
-- dir/file.txt --
-- dir/other.go --
-- main.go --
package p

import "embed"

const (
	Hello = "world"
)

//go:embed main.go *.txt
var myFS embed.FS
```

Sequence is:

* Open `main.go`
* See diagnostic for bad `go:embed` directive
* Fix it; diagnostic does _not_ disappear but it should ([bad_part1.log](https://github.com/golang/go/files/6892407/bad_part1.log))
* Close `govim` + `gopls`, because it is "stuck" at this point, and re-open.
* Notice that now there is no diagnostic
* Remove the fix, diagnostic does _not_ return as it should ([bad_part2.log](https://github.com/golang/go/files/6892409/bad_part2.log))

### What did you expect to see?

Consistent behaviour with respect to `go:embed` error diagnostics.

### What did you see instead?

As above.

---

cc @stamblerre

FYI @leitzler

**Comment by hyangah** [comment]
Interesting. I could reproduce this in vscode too.
I observed this stale diagnostics issue if `go:embed` is preceded by any code; the code doesn't have to be `const` block. I could repro the issue with `func F() {}` before the `go:embed` line. If the same code is placed after the `go:embed` directive, it doesn't affect and diagnostics work as expected.

**Comment by ShoshinNikita** [comment]
I could find the reason why the diagnostic works if `go:embed` is not preceded by any code. `parser.ParseFile` returns `*ast.File` with one extra comment if the mode is set to `parser.ImportsOnly | parser.ParseComments`:

**main.go:**

```go
package main

import (
	"fmt"
	"go/parser"
	"go/token"
)

func main() {
	const (
		mode = parser.ImportsOnly | parser.ParseComments
		src  = `
// Package main ...
package main

import (
	// fmt import ...
	_ "fmt"
	_ "github.com/pkg/errors" // errors import ...
)

// F ...
func F() {}

// B ...
func B() {}

// Hello ...
const Hello = "word"
`
	)

	f, err := parser.ParseFile(token.NewFileSet(), "x.go", src, mode)
	if err != nil {
		panic(err)
	}
	for _, c := range f.Comments {
		fmt.Printf("%q\n", c.Text())
	}
}
```

**Output:**

```
"Package main ...\n"
"fmt import ...\n"
"errors import ...\n"
"F ...\n"
```

`"F ...\n"` should not be listed here because the comment for `parser.ImportsOnly` says `stop parsing after import declarations`. So, I think there's a bug in `parser.ParseFile` function. What do you think?

**Comment by myitcv** [comment]
Thanks for the fix, @ShoshinNikita!

**Comment by ShoshinNikita** [comment]
cc @stamblerre - https://github.com/golang/go/issues/47436#issuecomment-893637070

**Comment by stamblerre** [comment]
@ShoshinNikita: That definitely seems like a bug! If you can, please open a new issue in this repo with the prefix "go/parser: " and include a playground link to your repro case.
