### ISSUE TITLE
[Need help] Why are there two scanner.go, can we merge them into one file?

### ISSUE THREAD

**Issue by diyism** [golang/go#47437]
I've  modifed 13 lines of src/cmd/compile/internal/syntax/scanner.go to support allman style braces:

https://github.com/golang/go/compare/master...forkgo-org:master#diff-8a3eef071ab7276287722ebb98acdb3521c251d2857d687cae762e394d1710e4

and my final go binnary can successfully run and build allman style go files(https://github.com/forkgo-org)
it seems that everything is OK,
but I don't know what's the usage of the file: https://github.com/forkgo-org/go/blob/master/src/go/scanner/scanner.go#L864
and I can't figure out how to modify it to keep it consistent with: https://github.com/forkgo-org/go/blob/master/src/cmd/compile/internal/syntax/scanner.go#L119

Why are there 2 scanner.go files? Can we merge them into one?

Sorry for forking golang go, blame me softly please, dear google guys.

Welcolm to help me fix the https://github.com/forkgo-org/go/blob/master/src/go/scanner/scanner.go#L864

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by diyism** [comment]
OK, I've moved it to https://forum.golangbridge.org/t/need-help-modify-two-scanner-go-files-to-support-allman-style-braces/24265
