### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by zubairhassan652** [golang/go#47438]
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/zubairhassan652/awesome
 
 
### What is your user agent?
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0

 
 
 
### Screenshot
 
<img width="1080" alt="Screenshot 2021-07-28 at 4 03 07 PM" src="https://user-images.githubusercontent.com/49283976/127312011-b98f3d88-fbf5-40b3-a7fe-65842735c3f3.png">

 
 
 
### What did you do?
 i am publishing my package with MIT license and it is not detected by the package index 

 
 
 
### What did you expect to see?
license detection and documentation 
 
 
### What did you see instead?
license not detected error

**Comment by seankhliao** [comment]
The version displayed (v0.1.0) doesn't have a license
