### ISSUE TITLE
go get: install protoc-gen-micro package on v3.5.0 error

### ISSUE THREAD

**Issue by soooldier** [golang/go#47431]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/tangyi/go/bin"
GOCACHE="/Users/tangyi/Library/Caches/go-build"
GOENV="/Users/tangyi/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/tangyi/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tangyi/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/Cellar/go@1.16/1.16.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go@1.16/1.16.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qw/qdzn2c917h12nsckk21gyqm40000gn/T/go-build2117429620=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
```shell
go get -v github.com/asim/go-micro/cmd/protoc-gen-micro/v3@v3.5.0
```

### What did you expect to see?

install the specified version protoc-gen-micro

### What did you see instead?
```shell
$ go get -v github.com/asim/go-micro/cmd/protoc-gen-micro/v3@v3.5.0
go get github.com/asim/go-micro/cmd/protoc-gen-micro/v3@v3.5.0: github.com/asim/go-micro@v3.5.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3
```

**Comment by mvdan** [comment]
I think you got the package path wrong. The /v3 suffix goes on the module path, not the package path:

> github.com/asim/go-micro/v3/cmd/protoc-gen-micro@v3.5.0

For more questions, see https://golang.org/wiki/Questions.

**Comment by mvdan** [comment]
Err, my bad - there *is* a nested module under cmd/protoc-gen-micro. But the v3.5.0 tag is for the root module, so that's why you're getting an error. Tags for a nested module need a prefix, for example: https://github.com/golang/tools/releases/tag/gopls%2Fv0.7.0

**Comment by soooldier** [comment]
It works! thx mvdan
