### ISSUE TITLE
runtime: unexpected slice append behavior on ARM

### ISSUE THREAD

**Issue by tmm1** [golang/go#47447]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 linux/arm
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

I have observed this bug on android and linux-based embedded ARM systems, primarily with 32-bit operating systems.

### What did you do?

I'm using a simple reflection loop to capture field indices into a global lookup map. On ARM systems, I noticed that the captured value is incorrect.

The code responsible looks like:

```go
	finfo := &fieldInfo{
		index: append(prefixIdx, f.Index...),
	}
```

changing it to the following fixes the issue:

```go
	idx := []int{}
	idx = append(idx, prefixIdx...)
	idx = append(idx, f.Index...)
	finfo := &fieldInfo{
 		index:  idx,
 	}
```

I have an executable test available in https://github.com/tmm1/gobug, along with a Dockerfile which runs it in an arm32 environment to replicate the failure:

```
$ git clone github.com/tmm1/gobug && cd gobug
$ make docker-build
#10 34.00 === RUN   TestTypeInfo
#10 34.01     types_test.go:27: 
#10 34.01               Error Trace:    types_test.go:27
#10 34.01               Error:          Not equal: 
#10 34.01                               expected: []int{1, 0}
#10 34.01                               actual  : []int{1, 1}
#10 34.01                               
#10 34.01                               Diff:
#10 34.01                               --- Expected
#10 34.01                               +++ Actual
#10 34.01                               @@ -2,3 +2,3 @@
#10 34.01                                 (int) 1,
#10 34.01                               - (int) 0
#10 34.01                               + (int) 1
#10 34.01                                }
#10 34.01               Test:           TestTypeInfo
#10 34.01 --- FAIL: TestTypeInfo (0.01s)
#10 34.01 FAIL
#10 34.01 FAIL  github.com/tmm1/gobug   0.105s
```

**Comment by seankhliao** [comment]
There is nothing in your code forcing `append` to allocate a new backing array, so when you do `append(prefixIdx, f.Index...)`, if `prefixIdx` has enough capacity it can use the same backing array and your 2 slices point to the same space.

**Comment by tmm1** [comment]
Could you help me understand why the behavior varies per platform?

Is it unreasonable to expect that my golang code would behave the same way on different computers?

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker for discussion.  You will get better and faster answers on a forum; see https://golang.org/wiki/Questions.  Thanks.

You may also want to read https://blog.golang.org/slices for more background.
