### ISSUE TITLE
compile: range loop should behave as a normal loop

### ISSUE THREAD

**Issue by urbanishimwe** [golang/go#47449]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17rc1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
 yes(go1.17rc1)

### What did you do?

made this program
```go
package main

import "fmt"

func main() {
	a := []int{0}
	for i := range a {
		if i < 100 {
			a = append(a, i+1)
		}
		fmt.Print(a[i], " ")
	}
}
```

### What did you expect to see?
I expected to see numbers printed from `[0, 100]`
as if I did this
```go
package main

import "fmt"

func main() {
	a := []int{0}
	for i := 0; i < len(a); i++ {
		if i < 100 {
			a = append(a, i+1)
		}
		fmt.Print(a[i], " ")
	}
}

```

### What did you see instead?
output: `0 `

**Comment by seankhliao** [comment]
From the [spec](https://golang.org/ref/spec#For_statements)

> For statements with range clause
> ...
> The range expression x is evaluated once before beginning the loop, with one exception: if at most one iteration variable is present and len(x) is constant, the range expression is not evaluated.

**Comment by urbanishimwe** [comment]
this was some kind of a proposal but okay!

**Comment by seankhliao** [comment]
You could file a language change proposal following: https://github.com/golang/proposal#language-changes but I doubt it would clear the bar of "have minimal impact on everybody else"
