### ISSUE TITLE
cmd/compile: ~19% of kubernetes build time is Type.HasShape1 on dev.typeparams

### ISSUE THREAD

**Issue by mdempsky** [golang/go#47456]
With kubernetes v1.21.1 (5e58841cce77d4bc13713ad2b91fa0d961e69192) and latest Go dev.typeparams (4a47e40a14c2051656d4ff4b768fe21a5fc308fa), according to `perf report` we're now spending about 19% of total build time within cmd/compile/internal/types.(*Type).HasShape1.

Within a checkout of github.com/kubernetes/kubernetes, run:

```
perf record -g go build -a -mod=mod ./cmd/kubelet
perf report
```

(Nothing special about kubernetes or v1.12.1; just what I happened to have handy and was using for profiling unified IR when I noticed Type.HasShape1.)

I know the GC shape code is new and likely to undergo a lot of changes in the near future anyway; but since this is a build performance impact that already affects normal, non-generics-enabled builds, I thought I'd mention it.

/cc @randall77 @danscales

**Comment by randall77** [comment]
Yes, I'm not surprised. I think we'll need something similar to `HasTParam` where we set it when building the type so we don't have to recursively look through deep types.

**Comment by danscales** [comment]
Yes, thanks for noting this @mdempsky , we will try to fix HasShape to be similar to HasTParam in the next week or two.

**Comment by randall77** [comment]
Hm, @gopherbot didn't seem to close this.
