### ISSUE TITLE
cmd/compile: export data doesn't need to record type parameter indices

### ISSUE THREAD

**Issue by griesemer** [golang/go#47451]
Reminder issue:
With [CL 338192](https://golang.org/cl/338192) we don't need to record type parameter indices in the export data anymore.
Should adjust the format at some point.

cc: @mdempsky

**Comment by mdempsky** [comment]
The unified IR export data format has never used type parameter indices.

**Comment by mdempsky** [comment]
Sorry, I confused this to be about the debug IDs (which unified IR has never used at all).

Unified IR uses the indices for writing out export data, but they're not encoded into the export data at all. I've also played with even removing uses of them within the writer, and can do that if you'd like to remove `TypeParam.Index` from the API.

**Comment by griesemer** [comment]
I filed this issue because of [this change](https://go-review.googlesource.com/c/go/+/338192/2/src/cmd/compile/internal/importer/iimport.go) on line 371. It seems to me that we read an index on that line that we don't need anymore?
