### ISSUE TITLE
x/pkgsite: pkg.go.dev/github.com/soniakeys/meeus refuses to exist

### ISSUE THREAD

**Issue by kortschak** [golang/go#47466]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/soniakeys/meeus or https://pkg.go.dev/github.com/soniakeys/meeus/v3
 
### What is your user agent?
 

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
 
### Screenshot
 

 
Not relevant. 
 
### What did you do?
 

Navigate to the URLs above.
 
### What did you expect to see?

Documentation for the package
 
 
### What did you see instead?

Not found.

The background for this is that likely the presence of the license is not recognised because it is not in the module, being in the repo root which does not have a go.mod. The obvious fix would be to ask the repo owner to place a license file in the v3 module. This is very unfortunately not possible.

**Comment by seankhliao** [comment]
I see documentation for the second link

First one 404s because there is no package/module at the root

**Comment by kortschak** [comment]
Thanks. When I looked it had not loaded and complained. Obviously it has got over that.
