### ISSUE TITLE
encoding/xml: Decoder escapes tab characters

### ISSUE THREAD

**Issue by chrisdoherty4** [golang/go#47464]
### What version of Go are you using (`go version`)?

Go 1.16.6 (play.golang.org)

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

play.golang.org

### What did you do?

Use the `encoding/xml` packages `Encoder` to output a tab character in `xml.CharData`. 

https://play.golang.org/p/oFvH6HEn310

```go
package main

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"io"
)

func parse(doc []byte) []byte {
	var buf bytes.Buffer
	encoder := xml.NewEncoder(&buf)

	decoder := xml.NewDecoder(bytes.NewReader(doc))

	func() {
		for {
			token, err := decoder.Token()
			if err == io.EOF {
				return
			} else if err != nil {
				panic(err)
			}

			if _, ok := token.(xml.CharData); ok {
				fmt.Printf("%s\n", token)
			}

			encoder.EncodeToken(token)
		}
	}()

	encoder.Flush()

	return buf.Bytes()
}

func main() {
	// xml document with tabs in.
	doc := []byte(`<Document>Hello		World</Document>`)

	fmt.Printf("Original: %s\n", doc)
	doc = parse(doc)
	fmt.Printf("Process 1: %s\n", doc)
	doc = parse(doc)
	fmt.Printf("Process 2: %s\n", doc)
}
```

Output: 
```
Original: <Document>Hello		World</Document>
Hello		World
Process 1: <Document>Hello&#x9;&#x9;World</Document>
Hello		World
Process 2: <Document>Hello&#x9;&#x9;World</Document>
```

### What did you expect to see?

Unescaped tab bytes are output as unescaped tab bytes.

### What did you see instead?

Unescaped tab bytes are output as escaped tab bytes.

**Comment by chrisdoherty4** [comment]
This could actually be worse than I though. CDATA tags are totally removed.

https://play.golang.org/p/gPrYuFfRcRK

**Comment by neild** [comment]
Simpler demonstration of `encoding/xml` marshaling tabs:

```
s, _ := xml.Marshal("\t")
fmt.Println(string(s))
```

Prints:

```
<string>&#x9;</string>
```

I'm not certain what's supposed to be not right here. `&#x9;` is a valid character reference representing a tab.

**Comment by chrisdoherty4** [comment]
It might not really be a bug, frankly. It just seems odd that the encoder doesn't respect whats input. The XML it outputs is totally valid though.

**Comment by neild** [comment]
> It just seems odd that the encoder doesn't respect whats input.

I'm not certain what this means; the encoder produces valid XML representing the input. Possibly escaping a tab character is unnecessary, but it certainly isn't wrong.
