### ISSUE TITLE
x/tools/gopls: migrate "test generation" features to gopls

### ISSUE THREAD

**Issue by n1lesh** [golang/go#47479]
vscode-go uses the `gotests` package to generate unit tests, which makes it hard to adjust the test generation behavior as mentioned here: [vscode-go issue #1594](https://github.com/golang/vscode-go/issues/1594).

We could move the test generation logic to `gopls`, which provides a few benefits,

1. Flexibility in modifying logic around test generation. Current vscode-go implementation uses `gotests` as a child process to generate tests, which makes it hard to customize test generation.
2. Reduction in the number of 3rd party tools for vscode-go. `gotests` package moves within `gopls`.

More about it [here](https://github.com/golang/vscode-go/issues/1652).

/cc @stamblerre

**Comment by beoran** [comment]
Currently, gotests is written to work as as a command only. I reccommend you would work together with @cweil and help to develop a version of gotests that also can be used as a module library, and which has the additional features you would like? This will then also benefit people who are not using gopls or VisualStudio, and want to integrate this in a different editor, like myself.

**Comment by findleyr** [comment]
@h9jiang is implementing this in golang/vscode-go#1594.

**Comment by findleyr** [comment]
(and is effectively done, so I'll close this)
