### ISSUE TITLE
gollvm: BackendArrayStruct.cpp:783:42: error: no matching function for call to ‘Llvm_backend::global_variable(const char [3], const char [3], Btype*&, bool, bool, bool, Location&)’

### ISSUE THREAD

**Issue by advancedwebdeveloper** [golang/go#47471]
Hi.

GCC's version is

>  (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
.

Was able to track down (at least) two errors:

> /home/runner/work/gollvm_build_process/gollvm_build_process/gollvm_build_process/llvm-project/llvm/tools/gollvm/bridge/go-llvm.h:258:14: note:   candidate expects 5 arguments, 7 provided
> /home/runner/work/gollvm_build_process/gollvm_build_process/gollvm_build_process/llvm-project/llvm/tools/gollvm/unittests/BackendCore/BackendArrayStruct.cpp: In member function ‘virtual void {anonymous}::BackendArrayStructTests_TestStructFieldAddressExpr_Test::TestBody()’:
> /home/runner/work/gollvm_build_process/gollvm_build_process/gollvm_build_process/llvm-project/llvm/tools/gollvm/unittests/BackendCore/BackendArrayStruct.cpp:783:42: error: no matching function for call to ‘Llvm_backend::global_variable(const char [3], const char [3], Btype*&, bool, bool, bool, Location&)’
>  783 |                                       loc);
>         |                                          ^

> /home/runner/work/gollvm_build_process/gollvm_build_process/gollvm_build_process/llvm-project/llvm/tools/gollvm/unittests/BackendCore/BackendArrayStruct.cpp:783:42: error: no matching function for call to ‘Llvm_backend::global_variable(const char [3], const char [3], Btype*&, bool, bool, bool, Location&)’

Archived logs:
https://github.com/advancedwebdeveloper/gollvm_build_process/suites/3361391333/logs
Raw logs:
https://github.com/advancedwebdeveloper/gollvm_build_process/commit/f5c21ee02bcc876c4993c37d607bfbe44e797881/checks/3192098762/logs

@thanm

**Comment by thanm** [comment]
Thanks. Sent https://go-review.googlesource.com/c/gollvm/+/338571 with a fix.

**Comment by advancedwebdeveloper** [comment]
Resolved.
Thanks
