### ISSUE TITLE
x/tools/gopls: find definition should return filename part as it is under Windows

### ISSUE THREAD

**Issue by wsw0108** [golang/go#47481]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

Windows 10, x64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\wsw\AppData\Local\go-build
set GOENV=C:\Users\wsw\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
</pre></details>

### What did you do?

Using gopls with eglot(`(setq eglot-extend-to-xref t)`).

`xref-find-definitions` under `math.Abs(...)`.

### What did you expect to see?

No new gopls server starts for the 'xrefed' go standard library file.

### What did you see instead?

A new gopls server starts for the  'xrefed' go standard library file.

EGLOT event buffer:
```
[client-request] (id:4) Sat Jul 31 11:14:35 2021:
(:jsonrpc "2.0" :id 4 :method "textDocument/definition" :params
          (:textDocument
           (:uri "file:///f%3A/GitHub/ombb/point.go")
           :position
           (:line 50 :character 14)))
[server-reply] (id:4) Sat Jul 31 11:14:35 2021:
(:jsonrpc "2.0" :result
          [(:uri "file:///C:/go/src/math/abs.go" :range
                 (:start
                  (:line 11 :character 5)
                  :end
                  (:line 11 :character 8)))]
          :id 4)
```

buffer-file-name for opened buffer `c:/Go/src/math/abs.go`.

https://github.com/joaotavora/eglot/blob/194b178ef41ccd3d937983f3829d44a546bb24d6/eglot.el#L1598-L1601

**Comment by wsw0108** [comment]
`file:///C:/go` and `c:/Go`, it is crazy...

Maybe this should be resolved in eglot.

**Comment by findleyr** [comment]
Hi, could you please share your full LSP logs for a session that produces this bug (see instructions [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capture-logs))?  That will help pinpoint where the incorrect casing is coming from.

Thanks.

**Comment by joaotavora** [comment]
@wsw0108  mentioning Eglot specific details to the authors of a language server is unlikely to be productive. You should post the requested details. If you want to open an issue in the Eglot tracker, you can, provided you follow the template there. If you don't have those details, you can also start a conversation in Eglot's discussion forum.

@findleyr from what I could gather of this description the problem had nothing to do with gopls

**Comment by wsw0108** [comment]
@findleyr log attached.
[gopls.txt](https://github.com/golang/go/files/6911965/gopls.txt)

Actually, the log file was generated after I modify eglot, otherwise after I call `textDocument/definition`, the log fill will be overwrited by the new gopls process.

- `go env GOROOT`, `c:/go`
- reply for `textDocument/definition`, `file:///C:/go/src/math/abs.go`
- `(buffer-file-name)`(Emacs), `c:/Go/src/math/abs.go`

**Comment by wsw0108** [comment]
reproduce repo [https://github.com/wsw0108/CASE-eglot](https://github.com/wsw0108/CASE-eglot).

```shell
cd CASE-eglot
emacs -Q -l init.el test.go
```

**Comment by findleyr** [comment]
Thanks for the logs, as they made it apparent that it is indeed gopls that is producing the upper-cased drive name.

Investigating, gopls actually _always_ uses upper-case drive names in its URIs: see https://github.com/golang/go/issues/36904. Because windows drive names are not case sensitive, gopls does this to normalize paths returned from different sources.

Unless I'm missing something, it seems like this must be handled client-side, i.e. in emacs.

I'm closing because I don't think there's anything we can reasonably do here, but please re-open if there's more to discuss.
