### ISSUE TITLE
nff-go packet reassemble question about how nff-go to use new dpdk ip_frag_death_row struct

### ISSUE THREAD

**Issue by zh7606559342012** [golang/go#47484]
### What version of Go are you using (`go version`)?
go version go1.16.4 linux/amd64
<pre>
$ go version
[root@localhost nff-go]# go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/zhenghao/share/go_project/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/zhenghao/share/go_project"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4079473019=/tmp/go-build -gno-record-gcc-switches"

</pre>

### What operating system and processor architecture are you using (`go env`)?
centos7.9 
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
3.10.0-1160.el7.x86_64
</pre></details>

### What did you do?
hello
i use nff-go low.go to create a new function in dpdk low.h ,it 's have some wrong ,could you help me ?
i find all net cant find the answer to the question
i base on 18.09 dpdk

in low.go
func CreateIpFragDeathTbl() Ip_Frag_Death_Row {
return C.create_ip_frag_death_row_table()
}

type Ip_Frag_Death_Row *C.struct_rte_ip_frag_death_row

in low.h
struct rte_ip_frag_death_row* create_ip_frag_death_row_table();

struct rte_ip_frag_death_row* create_ip_frag_death_row_table() {
struct rte_ip_frag_death_row* pdeath_row = NULL;
struct rte_ip_frag_death_row death_row;
death_row.cnt = 0;
pdeath_row = &death_row;
return pdeath_row;
}

when i am in nff-go to make cmdline make
it report worry

[root@localhost nff-go]# make
make -C nff-go-base
Checking for AVX support... AVX and AVX2
make[1]: Entering directory /home/zhenghao/share/go_project/src/5gc/vendor/github.com/intel-go/nff-go/nff-go-base' make[1]: Nothing to be done for all'.
make[1]: Leaving directory /home/zhenghao/share/go_project/src/5gc/vendor/github.com/intel-go/nff-go/nff-go-base' make -C dpdk Checking for AVX support... AVX and AVX2 make[1]: Entering directory /home/zhenghao/share/go_project/src/5gc/vendor/github.com/intel-go/nff-go/dpdk'
make[1]: Nothing to be done for all'. make[1]: Leaving directory /home/zhenghao/share/go_project/src/5gc/vendor/github.com/intel-go/nff-go/dpdk'
make -C test
make[1]: Entering directory /home/zhenghao/share/go_project/src/5gc/vendor/github.com/intel-go/nff-go/test' make -C stability make[2]: Entering directory /home/zhenghao/share/go_project/src/5gc/vendor/github.com/intel-go/nff-go/test/stability'
make -C testMerge
Checking for AVX support... AVX and AVX2
make[3]: Entering directory `/home/zhenghao/share/go_project/src/5gc/vendor/github.com/intel-go/nff-go/test/stability/testMerge'
go build -tags "" testMerge.go

5gc/vendor/github.com/intel-go/nff-go/internal/low
../../../internal/low/low.go:754:9: could not determine kind of name for C.create_ip_frag_death_row_table
make[3]: *** [testMerge] Error 2
make[3]: Leaving directory /home/zhenghao/share/go_project/src/5gc/vendor/github.com/intel-go/nff-go/test/stability/testMerge' make[2]: *** [testMerge] Error 2 make[2]: Leaving directory /home/zhenghao/share/go_project/src/5gc/vendor/github.com/intel-go/nff-go/test/stability'
make[1]: *** [stability] Error 2
make[1]: Leaving directory `/home/zhenghao/share/go_project/src/5gc/vendor/github.com/intel-go/nff-go/test'
make: *** [test] Error 2

pealse help me !
thank you!

### What did you expect to see?

make success 

### What did you see instead?
make err 

../../../internal/low/low.go:754:9: could not determine kind of name for C.create_ip_frag_death_row_table
make[3]: *** [testMerge] Error 2

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
