### ISSUE TITLE
x/tools/gopls: updates to go.sum needed, disabled by -mod=readonly with experimentalWorkspaceModule

### ISSUE THREAD

**Issue by mrosenc** [golang/go#47488]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.15.12 darwin/amd64
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/me/Library/Caches/go-build"
GOENV="/Users/me/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/me/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/me/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go@1.15/1.15.12/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go@1.15/1.15.12/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xq/3wt_bsxx5nsgzdmhwfs3p9nm0000gp/T/go-build066797790=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Running gopls under vscode with the experimental workspace mode enabled.

### What did you expect to see?
Gopls starting with no errors

### What did you see instead?
Error loading workspace: err: exit status 1: stderr: go: updates to go.sum needed, disabled by -mod=readonly : packages.Load error

The generated gopls.mod file looks reasonable:
<pre>
module gopls-workspace

go 1.12

require (
	changestream v1.9999999.0-goplsworkspace
	example.com/db_utils v1.9999999.0-goplsworkspace
	example.com/metrics_reporter v1.9999999.0-goplsworkspace
	file-diff v1.9999999.0-goplsworkspace
	file-proxy v1.9999999.0-goplsworkspace
	github.com/example/example/sre v1.9999999.0-goplsworkspace
	github.com/example/infra-tools/dbops v1.9999999.0-goplsworkspace
	github.com/example/infra-tools/explainer v1.9999999.0-goplsworkspace
	github.com/example/livequery v1.9999999.0-goplsworkspace
	harmonizer v1.9999999.0-goplsworkspace
	realtime v1.9999999.0-goplsworkspace
	vt-backfill-checker v1.9999999.0-goplsworkspace
	web-logger v1.9999999.0-goplsworkspace
	webhooks v1.9999999.0-goplsworkspace
)

replace changestream => /Users/me/example/example/changestream

replace file-diff => /Users/me/example/example/file-diff

replace file-proxy => /Users/me/example/example/file-proxy

replace example.com/db_utils => /Users/me/example/example/go/common/db_utils

replace harmonizer => /Users/me/example/example/harmonizer

replace github.com/example/infra-tools/dbops => /Users/me/example/example/infra-tools/dbops

replace github.com/example/infra-tools/explainer => /Users/me/example/example/infra-tools/explainer

replace example.com/metrics_reporter => /Users/me/example/example/infra-tools/metrics_reporter

replace github.com/example/livequery => /Users/me/example/example/livequery

replace realtime => /Users/me/example/example/realtime

replace github.com/example/example/sre => /Users/me/example/example/sre

replace vt-backfill-checker => /Users/me/example/example/vt-backfill-checker

replace web-logger => /Users/me/example/example/web-logger

replace webhooks => /Users/me/example/example/webhooks

</pre>

I've run go mod tidy in each individual module directory, so they are all clean.  I've attached the gpls server trace from vscode.

[gopls_trace.txt](https://github.com/golang/go/files/6912853/gopls_trace.txt)

This is essentially the issue reported here: https://github.com/golang/go/issues/44097 except I can't fix it by tiding the independent modules.

**Comment by findleyr** [comment]
Thanks for your report, and for taking the extra time to investigate the generated gopls.mod and produce a trace.

Looking through the logs, this pops out:
`/Users/me/example/example/gopls.mod:51: unknown directive: ~/example/example`

Did you use '~' in any of your go.mod files?

**Comment by mrosenc** [comment]
No, I don't have that in any of my mod files.  I think what happened here is that I gave you a trace that included the time when I manually generated the gopls.mod file and maybe was editing it.  I've generated a new trace from when I just started to when I get the errors, which should help focus.  Sorry about that.

[gopls_trace_2.txt](https://github.com/golang/go/files/6920772/gopls_trace_2.txt)

**Comment by mrosenc** [comment]
I tried deleting all the go.sum files and rebuilding all the projects to regenerate them, but that didn't help either.

**Comment by mrosenc** [comment]
This probably doesn't help, but I discovered the allowModfileModifications setting in vscode preferences and set it.  Now I don't get the error, but my trace included a bunch of notifications like:
[Trace - 00:05:05.874 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2021/08/03 00:05:05 discovered missing identifiers: map[memRecordCycle:true pageBits:true]\n\tpackage=\"runtime\"\n"}

Also gopls seems to work fine after this.  Sadly it didn't modify any go.mod/go.sum files as I had hoped, so there are no diffs to show, unless those modifications are hidden from me somehow.

I attached the new trace, though it might not be interesting.
[trace3.txt](https://github.com/golang/go/files/6920975/trace3.txt)

Let me know if there is anything else I can try.

**Comment by findleyr** [comment]
> This probably doesn't help, but I discovered the allowModfileModifications setting in vscode preferences and set it. Now I don't get the error, but my trace included a bunch of notifications like:This probably doesn't help, but I discovered the allowModfileModifications setting in vscode preferences and set it.

This will allow modifying the temporary go.mod and go.sum files used by the experimental workspace module, so we could conceivably try capturing these and diff.

If you're willing, you can do this as follows:

1. Start a gopls session in experimental workspace mode.
2. Look for a folder like `/tmp/gopls-<pid>.N/workspace.N`, where pid is the process ID of your current gopls instance.
3. Copy the `go.mod` and `go.sum` files from that directory.
4. Do the same with `allowModfileModifications=true`, and diff.

If you could do this, it would go a long way toward helping us understand the bug.

> Params: {"type":3,"message":"2021/08/03 00:05:05 discovered missing identifiers: map[memRecordCycle:true pageBits:true]\n\tpackage="runtime"\n"}

Sorry, this is spammy logging that we should remove. It's not related.

**Comment by findleyr** [comment]
> Look for a folder like /tmp/gopls-<pid>.N/workspace.N

More specifically: look in the effective temp directory on darwin -- I think it should be specified by `$TMPDIR` if it's not `/tmp`.

**Comment by mrosenc** [comment]
Thanks so much again for your help.  Sadly I did this several times and in every case the files in the gopls-pid.1 directory were the same with and without the option.  In addition there were directories like gopls-workspace-modDDDDDDDDD, these also contained go.mod and go.sum files, and these too were exactly the same in all cases.

**Comment by findleyr** [comment]
Hi, would it be possible for you to share your repro? It's surprising that the go.mod or go.sum files are the same.
