### ISSUE TITLE
x/pkgsite: https://pkg.go.dev/github.com/pdftron/pdftron-go

### ISSUE THREAD

**Issue by rachmatbcl** [golang/go#47490]
Hello, 

I have a go package in :
https://github.com/pdftron/pdftron-go

After running some tests, now that its published in 
https://pkg.go.dev/github.com/pdftron/pdftron-go

However, the above package seems to be missing files, ie: README.md, license.txt information, src_mac folder, among with many other go files. Can you tell me why they are missing?

Thank you.

**Comment by komuw** [comment]
`If we are not able to detect one of the licenses below, only limited package and module information will be made available.` - https://pkg.go.dev/license-policy  

There's a chance that the license you are using is not in the list recognised by pkg.go.dev. Check out; https://pkg.go.dev/license-policy

**Comment by jba** [comment]
The license isn't in our list. You can see in gray Details section, there is an X next to "redistributable license."

I am not a lawyer, but it appears to me that the license does not give us permission to do what we need to. You don't allow anyone to "repackage for distribution," but that is (arguably, in a legal sense) what we're doing.

I don't mean to imply by that analysis that you could somehow tweak the license to make it OK. For various reasons, we do need to limit the licenses we accept to the list linked above.

**Comment by rachmatbcl** [comment]
Thank you for the explanation.
