### ISSUE TITLE
x/mod/module: document that non-short Windows names not allowed in module paths

### ISSUE THREAD

**Issue by gazerro** [golang/go#47493]
The `CheckPath`, `CheckImportPath` and `CheckFilePath` functions (used to check module, import and file paths) reject Window short files (as `THISIS~1.TXT`) but also reject paths like `this-is-a-long-file-path~1` and `this-is-a-long-file-path~1.txt`.

A short file name can have at most 8 characters before the dot and its extension can have at most 3 characters.

**Comment by seankhliao** [comment]
This seems to be working as documented/intended?

CheckFilePath passes: https://play.golang.org/p/8u7pObwsxjX

While the other 2 are documented to reject such paths:

[CheckImportPath](https://pkg.go.dev/golang.org/x/mod/module#CheckImportPath):
> The element must not have a suffix of a tilde followed by one or more ASCII digits (to exclude paths elements that look like Windows short-names).

[CheckPath](https://pkg.go.dev/golang.org/x/mod/module#CheckPath):
>  A valid module path is a valid import path, as checked by CheckImportPath

**Comment by gazerro** [comment]
> CheckFilePath passes: https://play.golang.org/p/8u7pObwsxjX

You're right. `CheckFilePath` does not check for short names. I should have checked better.

> While the other 2 are documented to reject such paths:

Yes, they are documented but in my opinion the commit 4ab6fb194572846d53b80a92a0d87eaf31446542 that introduced this check was too restrictive and rejects path that are as documented but are not short-names in Windows.

**Comment by bcmills** [comment]
> in my opinion the original commit 4ab6fb1 that introduced this check was too restrictive and rejects path that are as documented but are not short-names in Windows.

Is there a specific reason we would need to allow these paths? (Are there existing widely-used packages that rely on them?)

I agree that the check may be somewhat more conservative than is strictly necessary, but I don't see a significant harm in leaving it that way.

**Comment by gazerro** [comment]
A part from that it may be somewhat more conservative, there is not a specific reason. Having understood that this implementation is a deliberate choice, it is okay for me to close this issue.

However, I recommend mentioning the short-name requirements in the documentation on the page

https://golang.org/ref/mod#go-mod-file-ident

Having to implement a module path validator, without using existing code, I went from this documentation to the code implementing it without reading the `CheckPath` function comment and so I hadn't read that the behavior was intentional.
