### ISSUE TITLE
x/mobile: Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by Higher08** [golang/go#47499]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.16.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/dmytro/Library/Caches/go-build"
GOENV="/Users/dmytro/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/dmytro/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/dmytro/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/86/5nplq84x6jl50czmncxkdqph0000gn/T/go-build543195465=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Build GOlang project with gomobile bind, import framework into iOS app and build it

### What did you expect to see?
Launched app)

### What did you see instead?

```
Undefined symbols for architecture arm64:
  "operator new(unsigned long)", referenced from:
      struct_utp_context::struct_utp_context() in Server(000033.o)
      _utp_init in Server(000033.o)
      _utp_create_socket in Server(000036.o)
  "___gxx_personality_v0", referenced from:
      struct_utp_context::struct_utp_context() in Server(000033.o)
      struct_utp_context::~struct_utp_context() in Server(000033.o)
      _utp_init in Server(000033.o)
      _utp_destroy in Server(000033.o)
      UTP_FreeAll(UTPSocketHT*) in Server(000036.o)
      _utp_create_socket in Server(000036.o)
      _utp_check_timeouts in Server(000036.o)
      ...
  "operator delete(void*)", referenced from:
      struct_utp_context::struct_utp_context() in Server(000033.o)
      struct_utp_context::~struct_utp_context() in Server(000033.o)
      _utp_init in Server(000033.o)
      _utp_destroy in Server(000033.o)
      UTP_FreeAll(UTPSocketHT*) in Server(000036.o)
      _utp_create_socket in Server(000036.o)
      _utp_check_timeouts in Server(000036.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation
```

**Comment by mengzhuo** [comment]
Could you elaborate on the code example?

**Comment by Higher08** [comment]
Code of usage in iOS app or GOlang code?

**Comment by Higher08** [comment]
I think it's happening because of this library https://github.com/anacrolix/go-libutp. And it seems that the clang compiler doesn't understand some functions in it. Is there a way to fix it?

**Comment by Higher08** [comment]
@mengzhuo

**Comment by mengzhuo** [comment]
> I think it's happening because of this library https://github.com/anacrolix/go-libutp. And it seems that the clang compiler doesn't understand some functions in it. Is there a way to fix it?

I DO NOT think it's a bug.

According to your environment settings:

```
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/dmytro/Library/Caches/go-build"
GOENV="/Users/dmytro/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
```

You may want to set `GOARCH=arm64`  to do cross compile.
And maybe it's related to https://github.com/golang/go/issues/47212

p.s. Github issue is not a place for question you should ask it at [Go-nuts](https://groups.google.com/g/golang-nuts)

**Comment by Higher08** [comment]
@mengzhuo, perhaps it was not clear from the description, but the build problem is in the Xcode. `gomobile bind` runs fine. If I remove this library from my golang project, the ios application starts
