### ISSUE TITLE
CPU and Memory activity take much longer than required to be released

### ISSUE THREAD

**Issue by c16a** [golang/go#47517]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOOS=linux
GOARCH=amd64
GOGC=20
GODEBUG=madvdontneed=1
</pre></details>

### What did you do?
Ran a soak test against a web API for several hours. This is run as Podman containers on RHEL8 AMIs hosted in AWS EC2. We've tried running this on several instance types but the results are similar.

1. We wanted GC to be a bit more aggressive, so we reduced it from 100 to 20.
2. We also set GODEBUG=madvdontneed=1

### What did you expect to see?
1. Objects out of scope are garbage collected
2. When the soak test ends, within a reasonably amount of time, the RAM and CPU utilisation comes back to how it was before the test.

### What did you see instead?
For a soak test spanning about 150 mins, the CPU and RAM utilisation take around 2 hours to come back to normal. If you observe the below graphs, the RAM and CPU take much longer to be released after the network activity has stopped.

:boom: **In later runs, the memory keeps growing (to over 99%) and the VM ultimately crashes due to OOM.** :boom:

![golang-issue-network](https://user-images.githubusercontent.com/2503348/128046546-fd86cf3a-7dda-42c1-b600-84ac91ced648.jpg)
![golang-issue-cpu](https://user-images.githubusercontent.com/2503348/128046567-decd449b-e748-44ad-a3ba-06321a91a5ce.jpg)
![golang-issue-memory](https://user-images.githubusercontent.com/2503348/128046592-1befe4a0-606a-499b-a0cd-d4a3164e8770.jpg)

In our latest adventure, we see even weirder behaviour (when the graph stops reporting, it was near the peak RAM). When the graph starts reporting again, it starts at around 300MB lesser memory usage.
![golang-issue-memory-gap](https://user-images.githubusercontent.com/2503348/128048653-76726ff1-2078-4c99-8454-03c984918bf0.jpg)

Is it possible that we're missing something?

**Comment by seankhliao** [comment]
This seems like an issue with how your application handles resources (caching/pools/background jobs?), how it reports metrics and not specifically a problem with the Go runtime.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
