### ISSUE TITLE
expvar: BenchmarkRealworldExpvarUsage times out on specific arm64 server

### ISSUE THREAD

**Issue by erifan** [golang/go#47511]
**This benchmark only get stuck in one type of our arm64/linux servers with n1 cpu and many cores.**

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.17-8a7ee4c51e Mon Aug 2 17:18:57 2021 +0000 linux/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/admin/.cache/go-build"
GOENV="/home/admin/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/admin/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/admin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/admin/go-master"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/admin/go-master/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="devel go1.17-8a7ee4c51e Mon Aug 2 17:18:57 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/admin/go-master/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2046940622=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
go test -bench BenchmarkRealworldExpvarUsage -count 5

### What did you expect to see?

Pass

### What did you see instead?
The benchmark is stuck.

### Linux kernel
Linux  5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

### gcc version
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

### Debug with delve:

**(dlv) goroutines**
  Goroutine 1 - User: /home/admin/go-master/src/testing/benchmark.go:284 testing.(*B).doBench (0xdf89c) [chan receive 451881h53m35.653003271s]
  Goroutine 2 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [force gc (idle) 451881h53m39.747847302s]
  Goroutine 3 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC sweep wait]
  Goroutine 4 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC scavenge wait]
  Goroutine 5 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [finalizer wait 451881h53m39.747877342s]
  Goroutine 52 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.747886983s]
  Goroutine 53 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.747895183s]
  Goroutine 54 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.747903383s]
  Goroutine 55 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.747913623s]
  Goroutine 56 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.747925623s]
  Goroutine 57 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.747933983s]
  Goroutine 58 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.747942263s]
  Goroutine 59 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.747951704s]
  Goroutine 60 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.747961824s]
  Goroutine 61 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.747970264s]
  Goroutine 62 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.747979704s]
  Goroutine 63 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.747991544s]
  Goroutine 64 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.747999904s]
  Goroutine 65 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748008384s]
  Goroutine 66 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748023545s]
  Goroutine 67 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748032265s]
  Goroutine 68 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748061625s]
  Goroutine 69 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748070545s]
  Goroutine 70 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748078385s]
  Goroutine 71 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748086826s]
  Goroutine 72 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748097186s]
  Goroutine 73 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748106586s]
  Goroutine 74 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748116626s]
  Goroutine 75 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748125946s]
  Goroutine 76 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748134306s]
  Goroutine 77 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748144986s]
  Goroutine 78 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748154827s]
  Goroutine 79 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748165027s]
  Goroutine 80 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748174827s]
  Goroutine 81 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748184147s]
  Goroutine 82 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748193947s]
  Goroutine 83 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748202787s]
  Goroutine 84 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748212027s]
  Goroutine 85 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748221588s]
  Goroutine 86 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748232188s]
  Goroutine 87 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748244028s]
  Goroutine 88 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748252228s]
  Goroutine 89 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748260308s]
  Goroutine 90 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748269828s]
  Goroutine 91 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748279348s]
  Goroutine 92 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748289989s]
  Goroutine 93 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748300709s]
  Goroutine 94 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748310549s]
  Goroutine 95 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748318669s]
  Goroutine 96 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748326509s]
  Goroutine 97 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 98 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748345669s]
  Goroutine 99 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.74835567s]
  Goroutine 100 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.74836411s]
  Goroutine 101 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.74837199s]
  Goroutine 102 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.74838067s]
  Goroutine 103 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.74839023s]
  Goroutine 104 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.74839907s]
  Goroutine 105 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.74840859s]
  Goroutine 106 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.74841655s]
  Goroutine 107 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748423871s]
  Goroutine 108 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748432151s]
  Goroutine 109 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748440551s]
  Goroutine 110 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748449031s]
  Goroutine 111 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748457191s]
  Goroutine 112 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748465551s]
  Goroutine 113 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748474391s]
  Goroutine 114 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748485111s]
  Goroutine 115 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748493592s]
  Goroutine 116 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748502192s]
  Goroutine 117 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748511592s]
  Goroutine 118 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748520192s]
  Goroutine 119 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748530632s]
  Goroutine 120 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748540752s]
  Goroutine 121 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748550832s]
  Goroutine 122 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748560273s]
  Goroutine 123 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748570913s]
  Goroutine 124 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748579593s]
  Goroutine 125 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748588073s]
  Goroutine 126 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748597713s]
  Goroutine 127 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748608273s]
  Goroutine 128 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748617753s]
  Goroutine 129 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748630874s]
  Goroutine 130 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748640954s]
  Goroutine 131 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748650394s]
  Goroutine 132 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748660274s]
  Goroutine 133 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748669994s]
  Goroutine 134 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748680314s]
  Goroutine 135 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748693915s]
  Goroutine 136 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748702435s]
  Goroutine 137 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748710915s]
  Goroutine 138 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748720075s]
  Goroutine 139 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748730115s]
  Goroutine 146 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748740875s]
  Goroutine 147 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748751075s]
  Goroutine 148 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748760156s]
  Goroutine 149 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748768356s]
  Goroutine 150 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748778196s]
  Goroutine 151 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748788436s]
  Goroutine 152 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748798476s]
  Goroutine 153 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748808636s]
  Goroutine 154 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748818556s]
  Goroutine 155 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748827637s]
  Goroutine 156 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748838517s]
  Goroutine 157 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748848757s]
  Goroutine 158 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748859077s]
  Goroutine 159 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748869117s]
  Goroutine 160 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 161 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m35.627432639s]
  Goroutine 162 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748898598s]
  Goroutine 163 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748908478s]
  Goroutine 164 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748918318s]
  Goroutine 165 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748927558s]
  Goroutine 166 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748937438s]
  Goroutine 167 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.748945398s]
  Goroutine 168 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 169 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 170 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m35.627519241s]
  Goroutine 171 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 172 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 173 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 174 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 175 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 178 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.74902396s]
  Goroutine 179 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m39.74903464s]
  Goroutine 180 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 181 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 182 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m35.627607802s]
  Goroutine 183 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 184 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m35.627626442s]
  Goroutine 185 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 186 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m35.600443748s]
  Goroutine 187 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m35.600454228s]
  Goroutine 188 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 189 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 190 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m35.600479148s]
  Goroutine 191 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 194 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m35.600496028s]
  Goroutine 195 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 196 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m35.627716044s]
  Goroutine 197 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m35.627723444s]
  Goroutine 198 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 199 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 200 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 201 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 202 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 203 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 204 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 205 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 206 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 207 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 208 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 209 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 210 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m35.627831965s]
  Goroutine 211 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 212 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 213 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m35.654495733s]
  Goroutine 214 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 215 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 216 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m35.627880726s]
  Goroutine 217 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 226 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m35.627897966s]
  Goroutine 227 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle) 451881h53m35.654545534s]
  Goroutine 228 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 229 - User: /home/admin/go-master/src/runtime/proc.go:367 runtime.gopark (0x4b52c) [GC worker (idle)]
  Goroutine 4162 - User: /home/admin/go-master/src/runtime/sema.go:56 sync.runtime_Semacquire (0x79b58) [semacquire]
  Goroutine 5978 - User: /home/admin/go-master/src/runtime/netpoll.go:229 internal/poll.runtime_pollWait (0x782e4) [IO wait]
[167 goroutines]
**(dlv) goroutine 5978**
Switched from 0 to 5978 (thread 3744652)
**(dlv) bt**
0  0x000000000004b52c in runtime.gopark
   at /home/admin/go-master/src/runtime/proc.go:367
1  0x0000000000043568 in runtime.netpollblock
   at /home/admin/go-master/src/runtime/netpoll.go:445
2  0x00000000000782e4 in internal/poll.runtime_pollWait
   at /home/admin/go-master/src/runtime/netpoll.go:229
3  0x00000000000a13f8 in internal/poll.(*pollDesc).wait
   at /home/admin/go-master/src/internal/poll/fd_poll_runtime.go:84
4  0x00000000000a1cc4 in internal/poll.(*pollDesc).waitRead
   at /home/admin/go-master/src/internal/poll/fd_poll_runtime.go:89
5  0x00000000000a1cc4 in internal/poll.(*FD).Read
   at /home/admin/go-master/src/internal/poll/fd_unix.go:167
6  0x0000000000160014 in net.(*netFD).Read
   at /home/admin/go-master/src/net/fd_posix.go:56
7  0x000000000016ad5c in net.(*conn).Read
   at /home/admin/go-master/src/net/net.go:183
8  0x00000000001a2008 in expvar.BenchmarkRealworldExpvarUsage.func5
   at ./expvar_test.go:588
9  0x000000000007d0c4 in runtime.goexit
   at /home/admin/go-master/src/runtime/asm_arm64.s:1133

**Comment by seankhliao** [comment]
cc @bradfitz

**Comment by bcmills** [comment]
The goroutines wedged in `GC worker (idle)` look a lot like #47511.

**Comment by bcmills** [comment]
Is this a regression in Go 1.17, or does this test also wedge on the latest Go 1.16 release?

**Comment by seankhliao** [comment]
@bcmills was there a different issue you want to reference?

**Comment by bcmills** [comment]
Argh, yeah. I meant #47505.

**Comment by erifan** [comment]
> Is this a regression in Go 1.17, or does this test also wedge on the latest Go 1.16 release?

I just tried Go 1.16.6, the answer is yes.

**Comment by bcmills** [comment]
Yes it's a regression, or yes it reproduces on 1.16.6? 😅

**Comment by erifan** [comment]
> Yes it's a regression, or yes it reproduces on 1.16.6? 😅

Sorry for the confusion, it reproduces on 1.16.6.

**Comment by erifan** [comment]
After verification, this problem has disappeared, so close this issue.
