### ISSUE TITLE
Why casting interface{} to cgo types is not allowed?

### ISSUE THREAD

**Issue by shockdev04** [golang/go#47523]
It's more of a technical question, not really an issue. Since we don't have variadic functions in cgo and there's currently no valid solution, I wonder if it'd be possible to cast interface{} to cgo types. So this would allow us to have more dynamic functions. I'm pretty sure we're not even allowed to assign types in a dynamic way to arguments in exported (//export) functions, neither the use of ellipsis is allowed. So what's the reason behind all those limits?

Thanks for answering.

**Comment by mdlayher** [comment]
Please see https://github.com/golang/go/wiki/Questions.
