### ISSUE TITLE
net/http: ServeContent add Cache-Control header

### ISSUE THREAD

**Issue by mhewedy** [golang/go#47539]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
I don't know

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mhewedy/Library/Caches/go-build"
GOENV="/Users/mhewedy/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mhewedy/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mhewedy/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.5/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_m/6fmdhfh952d1kvxm2h85c2rm0000gn/T/go-build4269072314=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

calling `http.ServeContent` to serve file from the server, it doesn't send "Cache-Control" header at all, and even the source code `fs.go` doesn't mention it.

### What did you expect to see?
According to retrofit (the famous Android HTTP client), it needs to see Cache-Control with value must-revalidate on the response header so it can send the HTTP request with "if-modified-since" HTTP request header. and hence `http.ServeContent` doesn't send such a header, then the resources are kept in Retrofit cache forever.

### What did you see instead?
http.ServeContent doesn't send "Cache-Control" response header at all.

**Comment by seankhliao** [comment]
cc @neild

**Comment by neild** [comment]
Given that there isn't a universally correct `Cache-Control` value, not setting one by default and leaving it up to the user to it if desired seems like the best approach.

**Comment by seankhliao** [comment]
Working as expected
