### ISSUE TITLE
cmd/dist: accept imports with leading space

### ISSUE THREAD

**Issue by XiaodongLoong** [golang/go#47544]
<pre>
$ ./make.bash 
Building Go cmd/dist using /usr/lib/go-1.11. (go1.11.6 linux/amd64)
Building Go toolchain1 using /usr/lib/go-1.11.
../../../../src/cmd/compile/internal/mips64/ggen.go:9: cannot find package "cmd/compile/internal/objw" in any of:
	/usr/lib/go-1.11/src/cmd/compile/internal/objw (from $GOROOT)
	/home/liuxiaodong/go-orig/pkg/bootstrap/src/cmd/compile/internal/objw (from $GOPATH)
go tool dist: FAILED: /usr/lib/go-1.11/bin/go install -gcflags=-l -tags=math_big_pure_go compiler_bootstrap bootstrap/cmd/...: exit status 1
</pre>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/liuxiaodong/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/liuxiaodong/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.11"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.11/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/liuxiaodong/go-orig/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build598535792=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I import packages and indent with spaces, just like this:
<pre>
diff --git a/src/cmd/compile/internal/mips64/ggen.go b/src/cmd/compile/internal/mips64/ggen.go
index 37bb871958..881fe8776d 100644
--- a/src/cmd/compile/internal/mips64/ggen.go
+++ b/src/cmd/compile/internal/mips64/ggen.go
@@ -6,7 +6,7 @@ package mips64
 
 import (
        "cmd/compile/internal/ir"
-       "cmd/compile/internal/objw"    // indent with tab
+        "cmd/compile/internal/objw"   // indent with spaces
        "cmd/compile/internal/types"
        "cmd/internal/obj"
        "cmd/internal/obj/mips"
</pre>

### What did you expect to see?
When I import packages and indent with spaces, I can execute make.bash successfully.
Just keep consistent with the behavior of the go compiler.
Thanks!

**Comment by seankhliao** [comment]
Go 1.11 is not a supported version, does this reproduce on the latest release?

**Comment by XiaodongLoong** [comment]
Yes
https://github.com/golang/go/blob/6e738868a7a943d7d4fd6bb1963e7f6d78111726/src/cmd/dist/buildtool.go#L291

**Comment by seankhliao** [comment]
The go code should be formatted with `gofmt` which will rewrite it to use tabs though

**Comment by ianlancetaylor** [comment]
cmd/dist is only used to build the Go standard library and tools.  It's OK for cmd/dist to assume that all the input files have gone through gofmt.  In fact, it's a good thing if cmd/dist fails if the files have not gone through gofmt.  So I don't think we should change this.

**Comment by XiaodongLoong** [comment]
IMO, code style and correct code might be different things. I usually develop Go code firstly and then modify the format with `gofmt`.  Code development may occur in the process of debugging without a good editor. This issue was also found during debugging.
Thanks!

**Comment by erifan** [comment]
> IMO, code style and correct code might be different things. 

You can think of this as a coding style error in Go. Just like 
```
if a > 0 {
...
}
```
can't be
```
if a > 0
{
...
}
```

> This issue was also found during debugging.

This just shows that this check works.

**Comment by ianlancetaylor** [comment]
> code style and correct code might be different things.

Sure.  But our rule for the standard library and tools is simple: all files must be formatted using gofmt.  No exceptions.

> I usually develop Go code firstly and then modify the format with gofmt. Code development may occur in the process of debugging without a good editor. This issue was also found during debugging.

Thanks, but I don't find any of these arguments to be convincing.  If cmd/dist supports files that are not formatted with gofmt, then it will be easier to accidentally submit such files to the repo.  We don't want that to happen, so let's not change cmd/dist.  Yes, this may requires using `go fmt` and it may occasionally lead to debugging, but it's still the right thing to do.

**Comment by XiaodongLoong** [comment]
@ianlancetaylor I got it. Thank you for answering my questions patiently. I will abandon the CL.

**Comment by ianlancetaylor** [comment]
Thanks.
