### ISSUE TITLE
 exec.Command run ffmpeg error Could not find video device with name XXX among source devices of type video

### ISSUE THREAD

**Issue by entrehuihui** [golang/go#47548]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.6 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\奔波霸\AppData\Local\go-build
set GOENV=C:\Users\奔波霸\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\奔波霸\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\奔波霸\go
set GOPRIVATE=
set GOPROXY=https://goproxy.io,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.6
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=F:\work\my\web\client\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\奔波霸\AppData\Local\Temp\go-build1829956365=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

```
func main() {
	cmd := exec.Command("ffmpeg.exe", "-re", "-f", "dshow", "-i", "video='CyberTrack H3'", "-f", "mpegts", "-an", "-vcodec", "libvpx", "-cpu-used", "5", "-deadline", "1", "-g", "10", "-error-resilient", "1", "-auto-alt-ref", "1", "-f", "rtp", "rtp://127.0.0.1:5004")
	cmd.Stderr = os.Stderr
	cmd.Stdout = os.Stdout

	err := cmd.Run()
	if err != nil {
		log.Println(err)
		return
	}
	err = cmd.Run()
	if err != nil {
		log.Println(err)
	}
}
```

### What did you expect to see?
I want to execute 
```
ffmpeg -re -f dshow -i video='CyberTrack H3' -r 30 -s 1280x720 -f mpegts -an -vcodec libvpx -cpu-used 5 -deadline 1 -g 10 -error-resilient 1 -auto-alt-ref 1 -f rtp rtp://127.0.0.1:5004
```
in  exec.Command。

![image](https://user-images.githubusercontent.com/22847681/128327853-e8f1d82b-bbac-458e-98d7-07ad96061060.png)

cannot execute the command line in the exec.Command.
At that time, I could successfully execute the change command directly in the terminal。 like
![image](https://user-images.githubusercontent.com/22847681/128328135-bd183da4-a269-4a10-a2da-1ecfb6762932.png)

### What did you see instead?
```
[dshow @ 0000019b48476500] Could not find video device with name ['CyberTrack H3'] among source devices of type video.
video='CyberTrack H3': I/O error
```

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
