### ISSUE TITLE
x/pkgsite: Add button to show keyboard shortcuts

### ISSUE THREAD

**Issue by silvanocerza** [golang/go#47552]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/fmt
 
### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0
 
### Screenshot

Not applicable. 

### What did you do?
 
I searched for a button to know which are the keyboards shortcuts.
 
### What did you expect to see?

A button labeled "Keyboard shortcuts" or something similar.
 
### What did you see instead?

Nothing.

**Comment by mvdan** [comment]
You can press `?` to see the shortcuts, but I agree it's not easy to discover.

**Comment by silvanocerza** [comment]
Yes, it's not easy. I found out about it from this comment: https://github.com/golang/go/issues/47421

**Comment by silvanocerza** [comment]
This seems solved to me, there is a button in the page footer now.

![image](https://user-images.githubusercontent.com/3314350/149505701-b24aebf0-e14e-47f5-8067-589c19b58e98.png)

**Comment by jamalc** [comment]
Thank you, yes, I'll close this issue.

**Comment by silvanocerza** [comment]
Same thing for #47553.
