### ISSUE TITLE
gopls/internal/analysis/undeclared: infer return types from call context when synthesizing a function

### ISSUE THREAD

**Issue by enkeyz** [golang/go#47558]
**Is your feature request related to a problem? Please describe.**
It would be a QoL change, and save time(Javascript, C# and other vscode language extensions also have this feature).

**Describe the solution you'd like**
When you want to call a function but it's not yet defined and implemented, it would be nice that if you could choose from the context menu, to define the method or function.
for example:
`
go handleConnection(conn)
`
then you click on the quick fixes content menu, and it automatically defines the function for you, like this:
`
func handleConnection(conn net.Con) {}
`

**Describe alternatives you've considered**

**Additional context**
![Screenshot from 2021-08-05 14-04-49](https://user-images.githubusercontent.com/17646853/128347348-0b4c4814-1431-4b05-bee2-237977d2f518.png)

**Comment by findleyr** [comment]
Thanks for the suggestion. I agree that this would be helpful, and should theoretically not be that difficult to add.

Transferred to the Go issue tracker, as this would be implemented by Gopls.

**Comment by rentziass** [comment]
This sounds fun, do you mind if I give it a try?
If I understood this correctly, when asking for code actions while on an undefined symbol that is a function call we should give the option to create an empty function with a signature that satisfies what that symbol is trying to do? Arguments would be what's being passed to the function, do we want to look at the "left" side too for return values?

**Comment by rentziass** [comment]
And re: argument names: if variables are passed to the function call like in @enkeyz example we could use those in the signature, what if instead this was the case?

```go
sum(1, 2)
// or
reverse("string to reverse")
```
I guess for non primitive types we could use a camel case version of the type name? (e.g. `net.Conn` => `conn`)
And for primitive types maybe the initial char? (e.g. `string` => `s`)
And for multiple arguments with the same type maybe append a number? For the `sum(1, 2)` example that would be
```go
func sum(i1, i2 int) {}
```
Sorry jumping ahead a bit maybe, just trying to think of edge cases to keep that generated function compilable.

**Comment by enkeyz** [comment]
`sum(1, 2)`: this also can be a variadic function: `func sum(nums ...int)`

**Comment by stamblerre** [comment]
@rentziass: Yes, you can definitely give this a try! You should be able to match on the error code that says that the interface isn't implemented, and then you will need to extract the expected function signature from the error message. I wouldn't focus on edge cases to start--the implementation doesn't need to be perfect, since it's a user-initiated action. You're right to say that this should be a code action for a given diagnostic.

**Comment by rentziass** [comment]
Hey @stamblerre, it's been a while! Cool, I'll give this shot (although I'll probably come back with more questions). As per the signature for the time being I'd focus on arguments rather than returned values, it sounds easier although I might be wrong again.

**Comment by findleyr** [comment]
@rentziass, I'd recommend starting this outside of the gopls codebase, using just `go/ast` and `go/types`. Given a package with a single undeclared name error, can you generate a stub that makes the error go away? This is the crux of the problem, but integrating with gopls' APIs for type information and diagnostics can be distracting. If you can solve the problem outside of gopls, we can help you integrate it as a quickfix.

**Comment by rentziass** [comment]
@findleyr thanks a lot, that's very useful!

**Comment by rentziass** [comment]
So I've put together [something that works](https://github.com/rentziass/functionquickfix) (or seems to work). I'm probably gathering the data I need to generate those stubs in a poor manner, so please let me know how it can be improved.

I've added a bunch of test cases I used to validate what I was doing (still staying well away from any possible values an undeclared func might be intended to return).

For arguments names, if an identifier was used the name of that identifier is reused, otherwise names are inferred by the type of the argument, e.g.:
- `int` -> `i`
- `error` -> `err`
- `net.Conn` -> `conn`
- `[]int` -> `i`

Also, if two arguments share the same identifier and/or type, argument name uniqueness is ensured, for example:
```go
c("some", "strings")

// results in
func c(s1 string, s2 string) {}
```

For the sake of this conversation, I'm reporting below what code fixed by generating function stubs for each case looks like right now, so whoever is interested in checking the outputs doesn't have to dive into code:
<details>
  <summary>Test Cases</summary>

### `u` is always the function that was undeclared to begin with.

### Primitives with an identifier
```go
package missingfunction

func a(s string) {
        u(s)
}

func u(s string) {}
```
### Imported types
```go
package missingfunction

import "io"

func a(r io.Reader) {
        u(r)
}

func u(r io.Reader) {}
```

### Non-primitive types, values and pointers
```go
package missingfunction

type T struct {}

func a() {
        pointer := &T{}
        var value T
        u(pointer, value)
}

func u(pointer *T, value T) {}
```

### Non-unique identifiers
```go
package missingfunction

func a(s string, i int) {
        u(s, i, s)
}

func u(s1 string, i int, s2 string) {}
```

### Literals / No identifiers
```go
package missingfunction

type T struct {}

func a() {
        u("hey compiler", T{}, &T{})
}

func u(s string, t1 T, t2 *T) {}
```

### Returned values from another function
```go
package missingfunction

import "io"

func a() {
        u(io.MultiReader())
}

func u(reader io.Reader) {}
```

### Passing an error
```go
package missingfunction

func a() {
        var err error
        u(err)
}

func u(err error) {}
```

### Using a function with multiple returned values as an argument
```go
package missingfunction

func a() {
        u(b())
}

func b() (string, error) {
        return "", nil
}

func u(s string, err error) {}
```

### Using operations as arguments
```go
package missingfunction

import "time"

func a() {
        u(10 * time.Second)
}

func u(duration time.Duration) {}
```

### Using a slice as argument
```go
package missingfunction

func a() {
        u([]int{1, 2})
}

func u(i []int) {}
```
</details>

If what's there is actually usable/useful, what's the plan now? :) also thanks for having me doing this, I'm having a blast!

**Comment by stamblerre** [comment]
This looks awesome, thanks for sharing this update @rentziass! I think the next step here would be to integrate this logic into the `gopls` codebase. This should be a ["type error analyzer"](https://pkg.go.dev/golang.org/x/tools/internal/lsp/source?utm_source=gopls#Hooks.TypeErrorAnalyzers), which is an analysis that provides quick fixes for type errors. You can find some examples here: https://github.com/golang/tools/tree/master/internal/lsp/analysis. Fillreturns (https://github.com/golang/tools/blob/master/internal/lsp/analysis/fillreturns/fillreturns.go) may be a good one to look at. Basically, you will want to create another folder in this directory named something like "implementmissing" and put the logic in an analyzer. You can add your test cases there as well, and then you can add your type error analyzer here: https://github.com/golang/tools/blob/a55d5155d907b5d1114e99daae56070cc0253114/internal/lsp/source/options.go#L1165.

With regards to naming parameters, you can also look at the code that does this in autocompletion [here](https://github.com/golang/tools/blob/a55d5155d907b5d1114e99daae56070cc0253114/internal/lsp/source/completion/literal.go#L193).

**Comment by enkeyz** [comment]
Would it be too big to ask, if you could implement this for methods too, not just functions?

**Comment by rentziass** [comment]
@enkeyz that's something I personally would have done after this piece, to keep this relatively small and reasonable. Another thing I'd like to look at as well is returned values expected for the function, i.e.

```go
var err error
err = myFunc() # undeclared myFunc
```

should generate

```go
func myFunc() error {}
```

**Comment by rentziass** [comment]
@stamblerre I'm finally getting to integrate this, although I noticed a todo in [analysis/undeclaredname](https://github.com/golang/tools/blob/master/internal/lsp/analysis/undeclaredname/undeclared.go#L72-L74) to handle the calling of undeclared functions. Given that `undeclared name` is the same type error I'd be handling here should I just add the ability to handle undeclared functions in that package to keep all of that in the same place? I'll start doing that, if you come back with a denial extracting to its own separate package shouldn't be that big of a deal :)

**Comment by rentziass** [comment]
Nope, I get it now, suggested fixes don't come out paired with `undeclaredname` diagnostics, separate package it is :D

**Comment by enkeyz** [comment]
Thanks for adding this feature, but there's one issue. When doing TDD, you write the tests first, so sometimes the function, or method doesn't exists.

So when you use this auto implement feature, it creates the function or method in the test file, instead of the normal file, where you put the package code.

Is this something you can solve?

**Comment by rentziass** [comment]
@enkeyz just a year late, sorry 😅 not sure this is something you can solve, test code is still part of a package and depending on whether you're using a `_test` package or not it might even be the same package as your non-test code.

@findleyr is it ok if I start looking into adding expected returned values too? After sometime spent as a user of this analyzer it really is a bit of a missing feature.

**Comment by findleyr** [comment]
@rentziass sounds good, please let us know how we can help.

**Comment by adonovan** [comment]
I change the title to reflect the remaining missing functionality: the 'undeclared' analyzer currently implements the missing function, but does not yet infer its return types from the context of the call.
