### ISSUE TITLE
runtime: "morestack on g0" in x/perf/storage/app on windows/arm64

### ISSUE THREAD

**Issue by bcmills** [golang/go#47557]
`$ greplogs --dashboard -l -md -e (?ms)morestack on g0.*FAIL\s+golang\.org/x/perf/storage/app`
[2021-02-20T03:31:36-40a54f1/6e73886/windows-arm64-10](https://build.golang.org/log/385ee6f7f695a451ecd1b181ad09a5de32704d26)
[2021-02-20T03:31:36-40a54f1/8a7ee4c/windows-arm64-10](https://build.golang.org/log/aeb400cfcf59bbf4f00179bda13970b35f7cd83c)
[2021-02-20T03:31:36-40a54f1/b8ca6e5/windows-arm64-10](https://build.golang.org/log/349e92ca2a0f108100a70acb7d87b42d48bb80bd)

```
fatal: morestack on g0
runtime: signal received on thread not created by Go.
…
FAIL	golang.org/x/perf/storage/app	0.274s
```

CC @prattmic @cherrymui @ianlancetaylor

**Comment by bcmills** [comment]
This is a release-blocker via #11811.

`windows/arm64` is not a [first-class port](https://github.com/golang/go/wiki/PortingPolicy#first-class-ports), so in theory this can be addressed by either fixing the underlying bug or adding skips to the relevant test(s).

(However, it looks like a pretty severe runtime bug to me.)

**Comment by heschi** [comment]
cc @mknyszek

**Comment by thanm** [comment]
I am kind of curious about how you are going to debug the test once it's build properly with DWARF. Delve doesn't support windows+arm64, so I assume gdb... does the builder actually have a gdb that works?

**Comment by mknyszek** [comment]
Coincidentally, I have a CL that fixes the recursive `runtime.abort` issue: https://go-review.googlesource.com/c/go/+/321789/. I should really land it, I totally forgot about it. After that, we should be able to get more info.

**Comment by thanm** [comment]
You might try working around the DWARF problem with

go test -ldflags=-w -c

**Comment by bcmills** [comment]
@gopherbot, please backport to Go 1.17. This failure mode is still occurring consistently on the go1.17 builder.
