### ISSUE TITLE
path/filepath: IsAbs considers C:\Projects\apilibrary\apilibrary.sln as a relative path but should be recognized as an absolute path

### ISSUE THREAD

**Issue by 180909** [golang/go#47556]
### What version of Go are you using (`go version`)?

<pre>
$ go version
playground
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
playground
</pre></details>

### What did you do?

https://play.golang.org/p/253ltb8aj6d

### What did you expect to see?

true

### What did you see instead?

false

**Comment by seankhliao** [comment]
Filepath behavior depends on the running system

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
