### ISSUE TITLE
x/pkgsite: Add button to toggle between light and dark theme

### ISSUE THREAD

**Issue by silvanocerza** [golang/go#47553]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/fmt
 
### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0
 
### Screenshot

Not applicable. 

### What did you do?
 
I searched for a button to toggle the current theme from dark to light.
 
### What did you expect to see?

A button with a sun/moon icon to switch between the light and dark theme.
 
### What did you see instead?

Nothing.

**Comment by mvdan** [comment]
See https://github.com/golang/go/issues/47421#issuecomment-893481259 :)
