### ISSUE TITLE
dev.loong64: create dev branch for the loong64 port

### ISSUE THREAD

**Issue by xen0n** [golang/go#47569]
Upstream work to bring up the LoongArch architecture is still at an early stage; many aspects of C & kernel ABIs haven't finalized yet, so it's unlikely for the `loong64` Go port to be finished in the 1.18 development cycle from an upstream perspective.

Because of this, and according to the Porting Policy (a port must be finished in the cycle it was started or will be removed), we (the LoongArch developer community & compiler engineers from the Loongson Corporation) are requesting the creation of a `dev.loong64` branch. Branching from the current tip is okay. 

Updates #46229

P.S. I haven't found any documentation on dev branch conventions and procedures, so I'm not sure whether it's appropriate for me to request this, and am just trying to replicate some previous dev branch request issues. Feel free to point out any issues!

P.P.S. Because the LoongArch ABIs might take a very long time to settle (perhaps due to circumstances I don't have position to comment on), a decision to postpone review work, and explicitly telling us to first polish things up out-of-tree, is okay from my viewpoint. I'm requesting a dev branch because I think it's important to collaborate as closely as possible for bringing up a new port, and for ensuring code quality by making individual changes step-by-step and have each one reviewed.

**Comment by ALTree** [comment]
cc @golang/release

**Comment by mengzhuo** [comment]
hi, any updates? @golang/release
I can create a new branch in the gerrit if this proposal approved.

**Comment by ALTree** [comment]
Closing as outdated, as the port was completed out-of-tree and then merged.
