### ISSUE TITLE
cmd/compile: use &runtime.zerobase for static pointer-to-zero-sized-thing

### ISSUE THREAD

**Issue by josharian** [golang/go#47582]
```go
package p

type I interface{ F() }

var V = []I{
	T{},
}

var P = &T{}

type T struct{}

func (t T) F() {}
```

`go tool compile -S x.go` includes:

```
"".V SDATA size=24
	0x0000 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00  ................
	0x0010 01 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 ""..stmp_0+0
"".P SDATA size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 ""..stmp_2+0
""..stmp_0 SDATA static size=16
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 0+0 t=24 type."".T+0
	rel 0+8 t=1 go.itab."".T,"".I+0
	rel 8+8 t=1 ""..stmp_1+0
""..stmp_1 SNOPTRBSS static size=0
""..stmp_2 SNOPTRBSS static size=0
```

Note that we're making static tmp symbols for zero-sized things. We should be able to omit stmp_1 and stmp_2 here and use a pointer to runtime.zerobase instead.

This happens a handful of times in std, but not enough for significant wins. Low priority.

**Comment by cherrymui** [comment]
The linker would combine all the zero-size static tmps and even with other static tmps. Does it actually matter?

Maybe not because it is not marked readonly? Maybe we could mark all zero-size data read-only.

**Comment by josharian** [comment]
> The linker would combine all the zero-size static tmps and even with other static tmps. Does it actually matter?

Realistically, not very much.
