### ISSUE TITLE
golang atomic.Value can't load the latest value?

### ISSUE THREAD

**Issue by bytewong123** [golang/go#47595]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
</pre></details>

### What did you do?

I read the resource code in golang atomic.Value, doubt the Load method cant get the latest value.
```
func (v *Value) Load() (x interface{}) {
    vp := (*ifaceWords)(unsafe.Pointer(v))
    typ := LoadPointer(&vp.typ)
    if typ == nil || uintptr(typ) == ^uintptr(0) {
        // First store not yet completed.
        return nil
    }
    data := LoadPointer(&vp.data)
    xp := (*ifaceWords)(unsafe.Pointer(&x))
    xp.typ = typ
    xp.data = data
    return
}
```
if another goroutine exec Store after ```data := LoadPointer(&vp.data)```, the Load returned value wont the latest

### What did you expect to see?

Load can get the latest store value

### What did you see instead?
Load may not get the latest value

**Comment by randall77** [comment]
I don't see why that is a problem. The implementation is free to treat the `Load` as happening before the `Store`.
