### ISSUE TITLE
x/pkgsite: remove retracted versions from search results

### ISSUE THREAD

**Issue by jba** [golang/go#47590]
We don't insert a retracted version into search results when we process it, but we also don't remove it if the retraction happens later.

**Comment by akshayjshah** [comment]
I've lost track of the open-source status of `pkg.go.dev` - is this something that I can help with, or is the source Google-internal?

**Comment by mvdan** [comment]
@akshayjshah https://github.com/golang/pkgsite

**Comment by jba** [comment]
Now live.
