### ISSUE TITLE
Go mod replace still looks online for the package

### ISSUE THREAD

**Issue by batistado** [golang/go#47596]
Even though I have go.mod files in all my packages and replace statements for local packages, go looks online for one of the package datastore.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xxx/Library/Caches/go-build"
GOENV="/Users/xxx/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xxx/go/pkg/mod"
GONOPROXY="github.com/xxx/*"
GONOSUMDB="github.com/xxx/*"
GOOS="darwin"
GOPATH="/Users/xxx/go"
GOPRIVATE="github.com/xxx/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.7"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xxx/go/src/sample-project/app/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n3/_ckjgzxj4pdc39ctm_wm6ntr0000gn/T/go-build638080012=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

$ cd sample-project/app
$ go mod tidy
go: found example.com/sample-project/menu in example.com/sample-project/menu v0.0.0-00010101000000-000000000000
go: finding module for package example.com/sample-project/datastore
example.com/sample-project/app imports
        example.com/sample-project/menu imports
        example.com/sample-project/datastore: cannot find module providing package example.com/sample-project/datastore: unrecognized import path "example.com/sample-project/datastore": reading https://example.com/sample-project/datastore?go-get=1: 404 Not Found

$ go run main.go
main.go:3:8: module example.com/sample-project/menu provides package example.com/sample-project/menu and is replaced but not required; to add it:
        go get example.com/sample-project/menu

My project is in /Users/xxx/go/src/ on Mac OS.

### What did you expect to see?

My app runs without any problems.

### What did you see instead?
[sample-project.zip](https://github.com/golang/go/files/6950312/sample-project.zip)

$go run main.go 
main.go:3:8: module example.com/sample-project/menu provides package example.com/sample-project/menu and is replaced but not required; to add it:
        go get example.com/sample-project/menu

**Comment by D1CED** [comment]
See https://golang.org/ref/mod#go-mod-file-replace

> replace directives only apply in the main module's go.mod file and are ignored in other modules. See Minimal version selection for details.

**Comment by seankhliao** [comment]
Note you typically only need 1 go.mod per project

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
