### ISSUE TITLE
Removed files in src\cmd\vendor\golang.org\x\sys\unix\ required for port on new os 

### ISSUE THREAD

**Issue by eDozor** [golang/go#47607]
Go 1.16.7
Removed files in src\cmd\vendor\golang.org\x \sys\unix\ required for port on new os. These files are used in mkall.sh.
https://go-review.googlesource.com/c/go/+/172979 

src/cmd/vendor/golang.org/x/sys/unix/mkasm_darwin.go Deleted 
src/cmd/vendor/golang.org/x/sys/unix/mkpost.go Deleted 
src/cmd/vendor/golang.org/x/sys/unix/mksyscall.go Deleted 
src/cmd/vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go Deleted 
src/cmd/vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go Deleted 
src/cmd/vendor/golang.org/x/sys/unix/mksyscall_solaris.go Deleted 
src/cmd/vendor/golang.org/x/sys/unix/mksysnum.go Deleted 
src/cmd/vendor/golang.org/x/sys/unix/types_aix.go Deleted 
src/cmd/vendor/golang.org/x/sys/unix/types_darwin.go Deleted 
src/cmd/vendor/golang.org/x/sys/unix/types_dragonfly.go Deleted 
src/cmd/vendor/golang.org/x/sys/unix/types_freebsd.go Deleted 
src/cmd/vendor/golang.org/x/sys/unix/types_netbsd.go Deleted 
src/cmd/vendor/golang.org/x/sys/unix/types_openbsd.go Deleted 
src/cmd/vendor/golang.org/x/sys/unix/types_solaris.go Deleted 

Removed files in 
SHA-1: d68ac59113e8c6d6a79abf9d608fd24c3566b91c
* {,cmd/}vendor: rerun 'go mod vendor' to prune ignored files
Updates #31088
Change-Id: Ia126e4e83ac5cb12c2c4151d5e5c975497598f24
Reviewed-on: https://go-review.googlesource.com/c/go/+/172979
Reviewed-by: Brad Fitzpatrick <bradfitz@golang.org>

**Comment by cherrymui** [comment]
You'd want to work on the golang.org/x/sys repo directly, instead of the vendored copy in GOROOT.

**Comment by eDozor** [comment]
You do not understand the essence of the questions. Take a close look at src\cmd\vendor\golang.org\x \sys\unix\mkall.sh.
There is a reference to these files, but they are not. Without them, I cannot create port goland to new architecture. These files are remembered in readmi.md in the  src/cmd/vendor/golang.org/x/sys/unix/ folder.

**Comment by cherrymui** [comment]
> Take a close look at src\cmd\vendor\golang.org\x \sys\unix\mkall.sh.

You should not use this file at all. Use the one in golang.org/x/sys repository ( https://pkg.go.dev/golang.org/x/sys ) instead. After updating the golang.org/x/sys repository, vendor it into GOROOT.

**Comment by ianlancetaylor** [comment]
cmd/vendor/golang.org/x/sys/unix is a copy of the repository hosted at golang.org/x/sys/unix.  All changes should be made to golang.org/x/sys/unix.  After the changes are made there, they can be copied into cmd/vendor/golang.org/x/sys/unix using `go get` and `go mod vendor`.  There is no reason for the files you mention to exist in cmd/vendor/golang.org/x/sys/unix.  They are only required in golang.org/x/sys/unix.
