### ISSUE TITLE
go/compile: doesn't respect modules' replace

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#47601]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Imported a module (B) that had a replace in its `go.mod` (C)

### What did you expect to see?

My main module `A` following the replacement in module `B`'s `go.mod` and using `C`'s fork.

### What did you see instead?

`../module.go:76:8: undefined: gzhttp.Get` because it's not using `C`'s fork.

* note, module C's fork is on git and accessible.

**Comment by mvdan** [comment]
See https://golang.org/ref/mod#go-mod-file-replace:

> replace directives only apply in the main module's go.mod file and are ignored in other modules. See Minimal version selection for details.

Also see https://golang.org/wiki/Questions. It can be hard to tell if you've found a bug or not, but if something simply isn't working how you expect, best to ask a question before filing a bug.
