### ISSUE TITLE
[dev.fuzz] cmd/go: fuzzer output buffered/missing when testing a sub package

### ISSUE THREAD

**Issue by stevenjohnstone** [golang/go#47603]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.17-4e07341afd Tue Aug 3 21:00:45 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

n/a

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/stevie/.cache/go-build"
GOENV="/home/stevie/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/stevie/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/stevie/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/stevie/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/stevie/sdk/gotip/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.17-4e07341afd Tue Aug 3 21:00:45 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/stevie/code/silent/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4292016643=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

In #fuzzing over in the gopher slack, @benhoyt reported that a fuzzer didn't give output. I made a minimal setup to reproduce the problem at https://github.com/stevenjohnstone/silent-beta-fuzz.

If you run the fuzzer outside of the package under test by specifying the package path, the output is lost.

### What did you expect to see?

The usual output every 3 seconds

### What did you see instead?

No output

**Comment by jayconrod** [comment]
Thanks for reporting this. I think I've seen this before... it has something to do with how `go test` buffers output from test processes. In any case, we do need to fix this.
