### ISSUE TITLE
gccgo: “use a small discontiguous stack for goroutines” may not be specified clearly enough to be implemented elsewhere

### ISSUE THREAD

**Issue by dilyanpalauzov** [golang/go#47622]
At https://golang.org/doc/install/gccgo#Gold is written:
> On x86 GNU/Linux systems the gccgo compiler is able to use a small discontiguous stack for goroutines. This permits programs to run many more goroutines, since each goroutine can use a relatively small stack. Doing this requires using the gold linker version 2.22 or later. You can either install GNU binutils 2.22 or later, or you can build gold yourself. 

This means, that ld.bfd and ld.lld do not support “small discontiguous stack “. As can be seen at https://sourceware.org/bugzilla/show_bug.cgi?id=28141 , this feature cannot be implemented in ld.bfd, because it lacks clear specification.

• Provide at https://sourceware.org/bugzilla/show_bug.cgi?id=28141 a clear specification for the feature of ld.gold “usage of small discontiguous stack for goroutines”

**Comment by dmitshur** [comment]
CC @ianlancetaylor.

**Comment by ianlancetaylor** [comment]
Added the spec to the sourceware bugzilla.
