### ISSUE TITLE
x/net/http2: outdated README

### ISSUE THREAD

**Issue by bradfitz** [golang/go#47624]
Reading http2 docs at https://pkg.go.dev/golang.org/x/net/http2, the first thing you see is this old text:

```
This is a work-in-progress HTTP/2 implementation for Go.

It will eventually live in the Go standard library and won't require
any changes to your code to use.  It will just be automatic.

Status:

* The server support is pretty good. A few things are missing
  but are being worked on.
* The client work has just started but shares a lot of code
  is coming along much quicker.

Docs are at https://godoc.org/golang.org/x/net/http2
...
```

Probably time to update that.

**Comment by dmitshur** [comment]
CC @neild, @tombergan via [owners](https://dev.golang.org/owners).

**Comment by dmitshur** [comment]
The [package comment](https://github.com/golang/net/blob/aaa1db679c0d7765d2b1cb1f92cac8ebf4d94c53/http2/http2.go#L5-L16) is more up to date and also shows up on pkg.go.dev. Maybe the README should just be deleted from that directory to avoid overlap.
