### ISSUE TITLE
x/tools/gopls: big number didn't show underscore in hover

### ISSUE THREAD

**Issue by donnol** [golang/go#47634]
when I have:

```go
const xxx = 10_000_000_000
```

and I use it:

```go
some.value = xxx
```

The problem comes, when I put the cursor to the const, the hover show 10000000000, not 10_000_000_000.

**Comment by stamblerre** [comment]
Thanks for the report, @donnol! I think this is actually the same issue as https://github.com/golang/go/issues/47453, so I'm going to close this issue as a duplicate.
