### ISSUE TITLE
io.Reader.Read() function will be blocked while using os.exec.StdoutPipe() to out print the sub-process' log

### ISSUE THREAD

**Issue by linyizhan-ILC** [golang/go#47633]
### What version of Go are you using (`go version`)?
1.14
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?

IDK

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

X86 cpu in centos linux os

### What did you do?

//
 stdout, err := cmd.StdoutPipe()
cmd.Start()
tmp:=make([]byte,512)
for{
    stdout.Read(tmp)
    fmt.Println(tmp)
}

but the output always hang at somewhere strange , i have add some print to see that the Read(tmp) will not stop during this , only I let more log outputing by sub process , the Read() will continue.
//
### What did you expect to see?

The way to workaroud this or show me the path of io.Reader.Read()'s source code to see why to will hang./

### What did you see instead?

Give me the other option to workaround this.

**Comment by ianlancetaylor** [comment]
1. Go 1.14 is no longer supported.
2. In order to help you, we will need to have a way to reproduce the problem.
3. You may get better help on a forum; see https://golang.org/wiki/Questions.
4. This may possible be related to #23019.
