### ISSUE TITLE
go install github.com/Peripli/service-manager-cli@<version> fails

### ISSUE THREAD

**Issue by i353590** [golang/go#47642]
### What version of Go are you using (`go version`)?
go version go1.16.7 darwin/amd64

GOARCH="amd64"

### What did you do?
 running the command - 
go install github.com/Peripli/service-manager-cli@1.11.10 OR go install github.com/Peripli/service-manager-cli@latest is failing with the following error:
\go install github.com/Peripli/service-manager-cli@v1.11.10: github.com/Peripli/service-manager-cli@v1.11.10
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.

### What did you expect to see?
The expectation was the successful installation of service-manager-cli.

### What did you see instead?
Error:
\go install github.com/Peripli/service-manager-cli@v1.11.10: github.com/Peripli/service-manager-cli@v1.11.10
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.

Thanks,
Shubham

**Comment by mvdan** [comment]
This is working as documented by `go help install`:

```
- No module is considered the "main" module. If the module containing
packages named on the command line has a go.mod file, it must not contain
directives (replace and exclude) that would cause it to be interpreted
differently than if it were the main module. The module must not require
a higher version of itself.
```

See https://github.com/golang/go/issues/40276 for more details. Also see https://golang.org/wiki/Questions.

**Comment by i353590** [comment]
Hello @dmitshur , @mvdan 

Thanks for your help :)
i will also report the bug here: https://github.com/Peripli/service-manager-cli/issues

Best Regards,
Shubham
