### ISSUE TITLE
access: approver/trust for ppc64 related changes

### ISSUE THREAD

**Issue by pmur** [golang/go#47644]
Hi, I would like to request access to approve/trust ppc64 related changes to the go and arch repositories. Thanks!

Gerrit e-mail: murp@ibm.com
Gerrit contributions: https://go-review.googlesource.com/q/owner:murp%2540ibm.com
Ref: https://go-review.googlesource.com/#/admin/groups/1005,members

See https://golang.org/wiki/GerritAccess

**Comment by ALTree** [comment]
cc @golang/release

**Comment by toothrot** [comment]
Thanks for pinging this. We're taking a look at it this week.

**Comment by toothrot** [comment]
Hi @pmur. I apologize for the delay. This has been granted! Please let me know if you have any issues.

**Comment by toothrot** [comment]
Also, thanks again for your contributions to Go.
