### ISSUE TITLE
x/tools/gopls: workspace/symbol response doesn't conform to spec when sending an empty query

### ISSUE THREAD

**Issue by mohkale** [golang/go#47655]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.16.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mohkale/.cache/go-build"
GOENV="/home/mohkale/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/mohkale/prog/.modules/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mohkale/prog/.modules/go:"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1016297562=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I had my LSP client send a workspace/symbols request to gopls with an empty query string.

### What did you expect to see?
It to return all the symbols in the workspace (as it is supposed to according to the [protocol specification](https://microsoft.github.io/language-server-protocol/specification#workspace_symbol)).

### What did you see instead?
The server returned no symbols.

**Comment by findleyr** [comment]
FTR, gopls also restricts to the top 100 results, which per this reading of the spec is also not conformant.

Note that there are a lot of symbols in a workspace. In Kubernetes, gopls has around 30mb of symbols in a minimal representation; when expanded with qualified paths and the full symbol struct, it could easily be 100mb+ of data. Furthermore, restricting to the top 100 results allows some not insignificant optimizations for all queries: gopls can avoid allocating results if the score is too low to make the top results list.

I just landed a sequence of optimizations (not yet released), that reduces query latency in Kubernetes from 2-3s down to around 50-100ms, and from my experimentation having very low latency significantly improves the user experience. I'd hate to sacrifice that in the name of conformance.

Why do you want too see all symbols?

**Comment by findleyr** [comment]
Thanks.

You're right that gopls is not conformant to the spec, unless we use a very generous reading that the client 'may request' but the server may choose how to satisfy that request.

But IMO the outcome of conforming to the spec here would be at best a footgun, and at worst a degraded experience for most users. This has come up before, but I'm not aware of any concrete reason to ask for all symbols.

The one reason I've heard is that in some UIs it's strange to open workspace symbols and get empty results. Maybe we should consider returning the top 100 symbols for an empty query.

Anyway, closing for now. If anyone wants to revisit this we can reopen.
