### ISSUE TITLE
cmd/compile: set the proper export version number before Go 1.18

### ISSUE THREAD

**Issue by danscales** [golang/go#47654]
When we get closer to the beta for 1.18, we need to set the export version number to its new value,
iexportVersionGo1_18 = 2.

We are temporarily setting the export version back to 1 (iexportVersionGoPosCol, also iexportVersionGoGenerics, since generic functions/types are backward compatible) for ease of internal testing, especially given a lot of x/tools and third-party tools that will break on the new export version.

**Comment by danscales** [comment]
https://go-review.googlesource.com/c/go/+/341211 is the change the needs to be mostly reverted to fix this issue.

**Comment by danscales** [comment]
@findleyr   Is there anything more on your side about the export version that you need to do?  If so, I can assign this bug to you as a reminder.  Otherwise, I think we can just close this issue, right?

**Comment by findleyr** [comment]
Yes, I think I still need to clean up once this has had enough time to propagate. Reassigning to myself, but also removing the release-blocker label.

**Comment by findleyr** [comment]
The top comment here looks wrong:
> When we get closer to the beta for 1.18, we need to set the export version number to its new value,
iexportVersionGenerics = 3.

> We are temporarily setting the export version back to 2 (in dev.typeparams, soon to be merged to master) for ease of internal testing, especially given a lot of x/tools and third-party tools that will break on the new export version.

We set it back to 1, and the new value will be 2. @danscales maybe amend?

**Comment by danscales** [comment]
OK, updated the top comment.  And removed release-blocker.

As an update, we have already change the export version in the compiler and x/tools, but there are some cleanup items that @findleyr still needs to do.  However, no longer a release blocker for beta1.

**Comment by danscales** [comment]
@findleyr  Can we close this now?  I confirmed with @heschi that are internal testing has proceed along and went fine.

**Comment by findleyr** [comment]
@danscales actually no, I just checked and there is still cleanup that needs to take place. Sending a CL now.
