### ISSUE TITLE
binary.Varint and binary.PutVarint have unexpected behavior

### ISSUE THREAD

**Issue by liubog2008** [golang/go#47659]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

https://play.golang.org/p/Ln_FQNDiSa-

```go
	ux, _ := binary.Uvarint([]byte{0x04})
	x, _ := binary.Varint([]byte{0x04})
```

### What did you expect to see?

Both `Uvarint` and `Varint` returns 4

### What did you see instead?

`binary.Varint([]byte{0x04})` returns 2

**Comment by liubog2008** [comment]
It seems as expected in test. But I can't understand the usage of this function.

**Comment by randall77** [comment]
The [specification](https://pkg.go.dev/encoding/binary) points to [how varints are encoded](https://developers.google.com/protocol-buffers/docs/encoding). In particular, see the [signed integer encoding](https://developers.google.com/protocol-buffers/docs/encoding#signed_integers).

Closing, this is not a bug.

**Comment by liubog2008** [comment]
Thanks
