### ISSUE TITLE
Consultation on slice expansion

### ISSUE THREAD

**Issue by colinrs** [golang/go#47661]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go version go1.14.13 darwin/amd6
</pre></details>

### What did you do?

I have a question, why do we [use addition instead of multiplication][1] when calculating the new cap when the slice is expanded? From my Benchmark, the multiplication looks faster 

### What did you expect to see?
https://github.com/golang/go/blob/master/src/runtime/slice.go#L182

```golang
	newcap := old.cap
	doublecap := newcap + newcap
	if cap > doublecap {
		newcap = cap
```

### What did you see instead?

Maybe can use multiplication instead of addition

#### main.go 

```golang
package main

func main(){
}

//go:noinline
func add(){
	new1 := 269
	_= new1 + new1

}

//go:noinline
func add2(){
	new1 := 269
	_ = new1*2
}
```

#### main_test.go

```golang

package main

import (
	"testing"
)
func BenchmarkAdd(b *testing.B) {
	for i := 0; i < b.N; i++ {
		add()
	}
}

func BenchmarkAddUseMulti(b *testing.B) {
	for i := 0; i < b.N; i++ {
		add2()
	}
}
```

```shell
go test -bench=.                  
goos: darwin
goarch: amd64
pkg: test
BenchmarkAdd-16                 895967389                1.35 ns/op
BenchmarkAddUseMulti-16         1000000000               1.06 ns/op
PASS
ok      test    3.191s
```

[1]: https://github.com/golang/go/blob/master/src/runtime/slice.go#L182

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker for questions or discussions.  Please use a forum instead.  See https://golang.org/wiki/Questions.  Thanks.

As far as your benchmark goes, when you are down at a nanosecond per op, benchmarks are highly affected by their exact position in the instruction cache.  You can't draw any serious conclusions from them.
