### ISSUE TITLE
x/website/_content/ref: lang version determining rule should be documented in Go Module Reference

### ISSUE THREAD

**Issue by go101** [golang/go#47662]
The behavior implemented in https://github.com/golang/go/issues/44976 should be documented at this section: https://golang.org/ref/mod#go-mod-file-go

ref: https://groups.google.com/g/golang-nuts/c/lhedc8YaWlM

**Comment by go101** [comment]
And as [Ian mentioned](https://groups.google.com/g/golang-nuts/c/lhedc8YaWlM/m/ER-r_JpPBAAJ), maybe the `-lang` version set in `-gcflags` should shadow the default 1.16 value.

**Comment by bcmills** [comment]
> And as Ian mentioned, maybe the `-lang` version set in `-gcflags` should shadow the default 1.16 value.

That seems fine, but please file a separate issue for it.
