### ISSUE TITLE
 Whether it is possible to specify .def file when golang compile to generate windows' DLL

### ISSUE THREAD

**Issue by akkuman** [golang/go#47666]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 windows/amd64
</pre>

### What did you do?

I want to know if it is possible to specify .def file when golang compile to generate windows' DLL

Just like I can use mingw for this purpose

```shell
gcc -shared -o a.dll functions.def a.cpp
```

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
