### ISSUE TITLE
x/build: publish Go binary releases to the Snap Store

### ISSUE THREAD

**Issue by samimessaoudi** [golang/go#47671]

**Comment by ianlancetaylor** [comment]
CC @golang/release

**Comment by dmitshur** [comment]
Please provide more information about this request.

What do you suggest be published (Go releases, or something else)?

Which Snap Store are you referring to? Link?

**Comment by samimessaoudi** [comment]
Distribute binary releases through [Snap Store](https://snapcraft.io/store) in order to make it installable and updatable on linux using snap CLI `sudo snap install go` for example.
The process would be triggered automatically after setting a GitHub action or using existant Go build tool.
Publishing Guide: [Snapcraft publishing guide](https://snapcraft.io/docs/snapcraft-overview)

**Comment by ALTree** [comment]
Unless I'm not up to date on this, the Release Team does not package and publish Go for Linux distros (for example the [.deb package for debian](https://packages.debian.org/buster/golang), etc...). They have external packagers/maintainers. Why would snap be different?
