### ISSUE TITLE
x/pkgsite: new v2 requests are getting rejected

### ISSUE THREAD

**Issue by wxolp** [golang/go#47670]
This package has a `v2` tag:

https://github.com/imthaghost/scdl/releases/tag/v2.0.2

and it has `v1` documentation:

https://pkg.go.dev/github.com/imthaghost/scdl

but if you try to access the `v2` documentation, it just says "Not found", with no recourse:

https://pkg.go.dev/github.com/imthaghost/scdl/v2

while other `v2` docs work fine:

https://pkg.go.dev/github.com/pelletier/go-toml/v2

**Comment by seankhliao** [comment]
The module declaration in the `go.mod` file says `github.com/imthaghost/scdl` while it has tagged `v2`
The documentation is still viewable via a pseudoversion (on the v1 module path), which is the same version go would have to import it with

**Comment by wxolp** [comment]
I dont know what any of that means

**Comment by wxolp** [comment]
I dont really understand what you just said, but it seems like whatever you just said would also apply to the toml package:

https://github.com/pelletier/go-toml/blob/master/go.mod

and again, the TOML package works, while the other one doesnt.

**Comment by seankhliao** [comment]
toml v2 is developed on its own branch which declares the correct version https://github.com/pelletier/go-toml/blob/v2.0.0-beta.3/go.mod

Closing as I believe this is working correctly and an issue should instead be filed with https://github.com/imthaghost/scdl

**Comment by wxolp** [comment]
The author updated go.mod, but documentation is still broken:

https://pkg.go.dev/github.com/vitali-fedulov/images/v2
