### ISSUE TITLE
unsafe cgo (fastcgo)

### ISSUE THREAD

**Issue by MatejMagat305** [golang/go#47687]
there is any plan to make oficial "unsafe cgo" (fastgo) like https://github.com/petermattis/fastcgo (which is much faster then normal cgo and more like call native  go function) like tool or package or additon to unsafe package?
(maybe similar `unsafe.fastCgo(c.somefn, ...args)` or `fastcgo.Call1Arg(c.somefn1, arg); fastcgo.Call2Arg(c.somefn2, arg1, arg2); ....`)
 I know it wil be unsafe and maybe sometime risk but it would be very usefull in some case when people need realy fast call cgo.

**Comment by mvdan** [comment]
It seems to be faster due to severe tradeoffs:

> WARNING: No attempt is made to play nice with the Go scheduler or GC. The goroutine executing a fastcgo call will never be interrupted and will delay the starting or completion of GC until it finishes.

I think you should just follow https://github.com/golang/go/issues/19574, as I don't think splitting the discussion in two is worthwhile.

> it would be very usefull in some case

Also see https://golang.org/doc/faq#x_in_std.

**Comment by mdlayher** [comment]
See above, closing.
