### ISSUE TITLE
runtime/pprof: apparent deadlock in TestGoroutineSwitch on linux-armv6l [1.17 backport]

### ISSUE THREAD

**Issue by prattmic** [golang/go#47688]
#47505 should be considered for backport to the 1.17 major release.

> This bug is not new and can cause deadlocks on linux/arm (`GOARM=6`) when profiling is turned on with no workaround. The biggest immediate issue for us is that this will cause new failures on all release builders, if not fixed.

I had to file this manually due to #25574.

**Comment by dmitshur** [comment]
Approved as a fix for a serious issue without a workaround. This backport applies to both 1.17 (this issue) and 1.16 (#47675).
