### ISSUE TITLE
Chrome does not recognize the ed25519 certificate

### ISSUE THREAD

**Issue by ggdream** [golang/go#47681]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.7 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\E plus\AppData\Local\go-build
set GOENV=C:\Users\E plus\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=F:\gopath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=F:\gopath
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=F:\go
set GOSUMDB=off
set GOTMPDIR=
set GOTOOLDIR=F:\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.7
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\EPLUS~1\AppData\Local\Temp\go-build1052031402=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

https://github.com/golang/go/blob/4c8ffb3baaabce1aa2139ce7739fec333ab80728/src/crypto/tls/generate_cert.go#L1

I used this file to generate the tls certificate. When using net/http to verify https, I found that only the RSA certificate is available, and Chrome does not recognize the ed25519 certificate

### What did you see instead?
~~~
This website cannot provide a secure connection 127.0.0.1 uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
Protocol not supported
The client and server do not support general SSL protocol versions or cipher suites.
~~~
Is this a browser issue that requires support to be turned on, or is it another issue?
Hope to enlighten me. Thanks!!

**Comment by seankhliao** [comment]
This is a chrome problem
