### ISSUE TITLE
cmd/cgo: use external c files

### ISSUE THREAD

**Issue by KrullBorg** [golang/go#47686]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tux/.cache/go-build"
GOENV="/home/tux/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/tux/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tux/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.16"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.16/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.7"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/tux/Documenti/sviluppo/zakutils_go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2332827378=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

in cgo documentation i found "When the Go tool sees that one or more Go files use the special import "C", it will look for other non-Go files in the directory and compile them as part of the Go package. Any .c, .s, or .S files will be compiled with the C compiler. ...."

so i moved my c code from preamble to an external c file

### What did you expect to see?

i expected that go build the program without problems, as happens when the code is in the preamble

### What did you see instead?

but when i build it doesn't find (link) the functions in the external file

what am I doing wrong? or what I did not understand?

thanks in advance

**Comment by mdlayher** [comment]
Please see https://github.com/golang/go/wiki/Questions.
