### ISSUE TITLE
fmt string formatting: arbitrary precision rounding for %f broken for exactly(?) two values

### ISSUE THREAD

**Issue by kotodharma** [golang/go#47697]
### What version of Go are you using (`go version`)?
I didn't find this in my own code, I found it on the Playground: https://play.golang.org/p/MO-g6v4BZWE

### Does this issue reproduce with the latest release?
Not sure, I assume that Playground has the latest.

### What did you see instead?
See the playground link of my minimal code example demonstrating the problem. Below is another copy of it. In a nutshell: when floating point numbers are rounded according to the specs given with the `%f` directive, it seems to work fine for all inputs _except_ in the case where the precision is zero (integer), and the value is exactly 0.50 or -0.50.
```
package main

import "fmt"

func main() {
	fmt.Printf("Expecting  0: |%1.0f|\n", 0.499999)
	fmt.Printf("Expecting  1: |%1.0f|\n", 0.500001)
	fmt.Printf("Expecting  1: |%1.0f|\n", 0.500000)
	fmt.Printf("Expecting -1: |%1.0f|\n", -0.500001)
	fmt.Printf("Expecting -1: |%1.0f|\n", -0.500000)
}
```
Incidentally I only discovered this while writing my own arbitrary precision rounding function using Sprintf, a hack that would not be necessary if the standard math library contained a function to do this for me, which apparently it doesn't, and AFAICT Go leadership doesn't feel is necessary. 
This is how I'm attempting to solve that problem: `fmt.Sprintf(fmt.Sprintf("%%1.%df", precision), value)`.

**Comment by seankhliao** [comment]
This is standard IEEE 754 float rounding to nearest even

Go spec: https://golang.org/ref/spec#Representability

> Rounding uses IEEE 754 round-to-even rules
