### ISSUE TITLE
x/tools/analysis/passes/printf: confusing message for incorrect use of %w

### ISSUE THREAD

**Issue by williammoran** [golang/go#47690]
This is the current message:
"log.Panicf call has error-wrapping directive %w, which is only supported for functions backed by fmt.Errorf"

I found this confusing and it took me a while to understand what it was trying to tell me. What it actually needs to communicate can be phrased much more directly and concisely. For example:
log.Panicf does not support the %w directive

The biggest issue is that the current message doesn't actually tell the user what's wrong.
* It tells me that I used %w, which I already knew
* It tells me that %w is only supported by functions backed by fmt.Error
Notice that it never told me that log.Panicf isn't backed by fmt.Error.

**Comment by stamblerre** [comment]
Thanks for reporting! This error message actually comes from the `printf` analyzer, so will move the issue to that component.

**Comment by timothy-king** [comment]
cc @zpavlinovic
