### ISSUE TITLE
sync/atomic: CompareAndSwapPointer should be CompareAndSwap

### ISSUE THREAD

**Issue by shoenseiwaso** [golang/go#47699]
The comment states CompareAndSwapPointer but it should be name of the function, CompareAndSwap:
https://github.com/golang/go/blob/2422c5eae5dc6539b4b7657ef7bfe58a65acb61d/src/sync/atomic/value.go#L129-L134

**Comment by rhysh** [comment]
CC @golang/release , this is a new API for Go 1.17, and the release branch doesn't have the fix yet (see https://github.com/golang/go/blob/release-branch.go1.17/src/sync/atomic/value.go#L129 ). For your consideration, so it doesn't get lost in the shuffle on Monday.

@gopherbot please backport to 1.17
