### ISSUE TITLE
x/pkgsite: "Standard library Imports" is non-standard title capitalization 

### ISSUE THREAD

**Issue by rsc** [golang/go#47701]
https://pkg.go.dev/rsc.io/tmp/blog2md?tab=imports

<img width="404" alt="Screen Shot 2021-08-14 at 8 25 29 AM" src="https://user-images.githubusercontent.com/104030/129446228-826526af-0940-4b0b-8363-e7a679903319.png">

"Standard library Imports" is oddly capitalized.
It should be "Standard Library Imports" or "Standard library imports".

**Comment by informeai** [comment]
Good question, since it is visible in the listing of various packages on github.I can't be wrong but I think it's default.

**Comment by rsc** [comment]
Indeed. This report is about the general display for all packages and not just this specific package.

**Comment by cespare** [comment]
The same level of heading in the [versions tab](https://pkg.go.dev/rsc.io/tmp/blog2md@v0.0.0-20210813200201-809266c06074?tab=versions) says "Versions in this module", so to be consistent it should probably be "Standard library imports".

![screen_20210814091223](https://user-images.githubusercontent.com/318501/129452563-c711c296-c86f-45cb-9dc9-82c42d807b14.png)
