### ISSUE TITLE
cmd/compile: incorrect error message on unclosed [ in map indexing

### ISSUE THREAD

**Issue by ALTree** [golang/go#47704]
```
go version go1.16.5 linux/amd64
go version devel go1.18-a632b433a1 Fri Aug 13 19:30:04 2021 +0200 linux/amd64
```

```
package p

func f(m map[int]int) int {
	return m[0
		]
}
```

```
$ go build test.go
# command-line-arguments
./test.go:4:12: syntax error: unexpected newline, expecting :
```

The `expecting :` part of the error message is plainly wrong, as there's no way to get a program that compiles by putting a `:` there.

go/types correctly reports `expected ']', found newline`.

cc @griesemer

**Comment by griesemer** [comment]
Note that is a syntax error and not a type-checking error, so the compiler doesn't know the type of `m`. In this case the parser assumes that the incomplete `m[0` was going to be a slice expression and thus expected a `:` (slices tend to be more common than maps). The error should probably be `syntax error: unexpected newline, expecting : or ]`.
