### ISSUE TITLE
cmd/compile: implict dereference using constraints doesn't compile with -G=3 as expected

### ISSUE THREAD

**Issue by abraithwaite** [golang/go#47713]
### What version of Go are you using (`go version`)?

<pre>
15:30:26 $ go version
go version devel go1.18-4d3cc847745 Thu Aug 12 20:22:27 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, on current HEAD of `dev.typeparams`.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
15:31:08 $ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/abraithwaite/.cache/go-build"
GOENV="/home/abraithwaite/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/abraithwaite/Projects/golang/pkg/mod"
GOOS="linux"
GOPATH="/home/abraithwaite/Projects/golang"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/abraithwaite/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/abraithwaite/sdk/gotip/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.18-4d3cc847745 Thu Aug 12 20:22:27 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4018258502=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do? What did you expect to see? What did you see instead?

Using the following program, when compiling I expected an implicit de-reference of the method receiver:

https://github.com/abraithwaite/go-typeparams-issues/blob/master/bug-report-1/main.go

I expected no compilation error.  This is what I saw instead:

```
15:32:18 $ go run -gcflags='-G=3' ./main.go
# command-line-arguments
<autogenerated>:1: cannot use .this (type *GenericSerializable[*main.SerDeString]) as type GenericSerializable[.shape.*uint8] in argument to GenericSerializable[.shape.*uint8].Send
```

I'm not sure why GenericSerializable is being passed as a pointer receiver instead of a value receiver as I've defined for `.Send`.

I saw this also: https://github.com/golang/go/issues/47031  Maybe it's related?  Seemed different enough to warrant opening this issue.

**Comment by mknyszek** [comment]
AFAIK dev.typeparams has been now merged into master, so I'm dropping that from the title.

Since this appears to be related to generics in the compiler frontend (?), CC @griesemer @mdempsky @danscales

**Comment by abraithwaite** [comment]
I'll try it on the master branch too!  Thanks for the update.

**Comment by griesemer** [comment]
This is an error reported by the compiler when writing object data to disk. The compiler front-end (types2, etc.) accepts this code just fine.

**Comment by mdempsky** [comment]
I think this is actually an issue with method wrapper generation with -G=3 mode. The error message is because the generated code is not well typed.

(FWIW, it compiles okay with `GOEXPERIMENT=unified`.)

**Comment by danscales** [comment]
This relates to some discrepancy in the naming of types, which leads to problems with wrapper generation.  I'll have a fix in the next day or so.
