### ISSUE TITLE
Get and Dial with tls.Config and context

### ISSUE THREAD

**Issue by haraldrudell** [golang/go#47717]
go version go1.16.6 darwin/amd64
— I have the arm64…
— linux/darwin 386/amd64/arm64

I would want GET/POST requests and tcp/udp Dial that features both tls.Config and context.Context
— tls.Config is required for using self-signed certificates if you have streamlined copy-less TLS deployments, ie. each box generates certificates and first request commissions
— context is required for timely abort of requests in progress
— Dialer for tcp
— http client for tcp/unix

I wrote the below:

```go
/*
© 2021-present Harald Rudell <harald.rudell@gmail.com> (https://haraldrudell.github.io/haraldrudell/)
All rights reserved.
*/

package parlnet

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"net/http"

	"github.com/haraldrudell/parl/error116"
)

type HttpClient struct {
	http.Client
}

func Get(requestURL string, tlsConfig *tls.Config, ctx context.Context) (resp *http.Response, err error) {
	return NewHttpClient(tlsConfig).Get(requestURL, ctx)
}

func NewTLSConfig(cert *x509.Certificate) (tlsConfig *tls.Config) {
	certPool := x509.NewCertPool()
	certPool.AddCert(cert)
	return &tls.Config{RootCAs: certPool}
}

func NewHttpClient(tlsConfig *tls.Config) (httpClient *HttpClient) {
	return &HttpClient{Client: http.Client{
		Transport:     NewTransport(tlsConfig),
		CheckRedirect: CheckRedirect,
		Jar:           nil,
		Timeout:       0,
	}}
}

func (ct *HttpClient) Get(requestURL string, ctx context.Context) (resp *http.Response, err error) {
	if ctx == nil {
		ctx = context.Background()
	}
	var httpRequest *http.Request
	if httpRequest, err = http.NewRequestWithContext(ctx, "GET", requestURL, nil); err != nil {
		panic(error116.Errorf("http.NewRequestWithContext: '%w'", err))
	}
	return ct.Client.Do(httpRequest)
}

func CheckRedirect(req *http.Request, via []*http.Request) (err error) {
	return
}

func NewTransport(tlsConfig *tls.Config) (httpTransport *http.Transport) {
	var defaultTransport *http.Transport
	var ok bool
	if defaultTransport, ok = http.DefaultTransport.(*http.Transport); !ok {
		panic(error116.New("DefaultTransport not http.Transport type"))
	}
	httpTransport = defaultTransport.Clone()

	// ensure tlsConfig is used
	httpTransport.TLSClientConfig = tlsConfig
	httpTransport.DialTLSContext = nil
	return
}
```

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by seankhliao** [comment]
see also https://golang.org/doc/faq#x_in_std

**Comment by haraldrudell** [comment]
This is not a question. It is a request to implement functions with signatures
```go
Get(requestURL string, tlsConfig *tls.Config, ctx context.Context)
func (*tls.Dialer).DialTLSContext(network string, addr string, tlsConfig *tls.Config, ctx context.Context) (net.Conn, error)
```
There have been long-running discussions on especially the Dial deficiency. The reason for this is likely that Go did not start out having context and instead had per-struct channel readers

**Comment by seankhliao** [comment]
`GetContext` was already rejected in #35562 , adding more arguments to it won't change the decision.

tls already has `Dialer.DialContext` adding a `tls.Config` when the receiver already has one seems to be more confusing than useful.
