### ISSUE TITLE
AST symbolication problem in struct initialization

### ISSUE THREAD

**Issue by awelc** [golang/go#47728]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

I don't know for sure (I can't install the newest version as this is a corporate machine).

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output (selected)</summary><br><pre>
$ go env
GOARCH="amd64"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9l/3m374q2d0slc4k8p72vv87bw0000gn/T/go-build4119325664=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I am working with go ASTs via the Go AST [package](https://pkg.go.dev/go/ast) and I noticed that the symbolication information computed for a particular AST does not seem to be correct - I am specifically talking about binding an identifier use with the declaration of this identifier.

Consider the following struct declaration:
```
type someStruct struct {
  someField int
}
```

Further consider the following function declaration (in the same file):

```
func foo() someStruct {
  return someStruct{someField : 42}
}
```

If you look at the AST generated out of this code, you will see that `someField` is unbound in the body of `foo`:

```
   120  .  .  .  .  .  .  .  .  .  0: *ast.KeyValueExpr {
   121  .  .  .  .  .  .  .  .  .  .  Key: *ast.Ident {
   122  .  .  .  .  .  .  .  .  .  .  .  NamePos: foo:9:21
   123  .  .  .  .  .  .  .  .  .  .  .  Name: "someField"
   124  .  .  .  .  .  .  .  .  .  .  .  Obj: nil
   125  .  .  .  .  .  .  .  .  .  .  }
   126  .  .  .  .  .  .  .  .  .  .  Colon: foo:9:31
   127  .  .  .  .  .  .  .  .  .  .  Value: *ast.BasicLit {
   128  .  .  .  .  .  .  .  .  .  .  .  ValuePos: foo:9:33
   129  .  .  .  .  .  .  .  .  .  .  .  Kind: INT
   130  .  .  .  .  .  .  .  .  .  .  .  Value: "42"
   131  .  .  .  .  .  .  .  .  .  .  }
   132  .  .  .  .  .  .  .  .  .  }
```

On the other hand, consider the following function declaration:

```
func foo(someField int) someStruct {
  return someStruct{someField : 42}
}
```

As you can see, in the AST generated from this code, `someField` is bound to the parameter declaration which I believe is incorrect.

```
    81  .  .  .  Type: *ast.FuncType {
    82  .  .  .  .  Func: foo:8:1
    83  .  .  .  .  Params: *ast.FieldList {
    84  .  .  .  .  .  Opening: foo:8:9
    85  .  .  .  .  .  List: []*ast.Field (len = 1) {
    86  .  .  .  .  .  .  0: *ast.Field {
    87  .  .  .  .  .  .  .  Doc: nil
    88  .  .  .  .  .  .  .  Names: []*ast.Ident (len = 1) {
    89  .  .  .  .  .  .  .  .  0: *ast.Ident {
    90  .  .  .  .  .  .  .  .  .  NamePos: foo:8:10
    91  .  .  .  .  .  .  .  .  .  Name: "someField"
    92  .  .  .  .  .  .  .  .  .  Obj: *ast.Object {
    93  .  .  .  .  .  .  .  .  .  .  Kind: var
    94  .  .  .  .  .  .  .  .  .  .  Name: "someField"
    95  .  .  .  .  .  .  .  .  .  .  Decl: *(obj @ 86)
    96  .  .  .  .  .  .  .  .  .  .  Data: nil
    97  .  .  .  .  .  .  .  .  .  .  Type: nil
    98  .  .  .  .  .  .  .  .  .  }
    99  .  .  .  .  .  .  .  .  }
   100  .  .  .  .  .  .  .  }
...
   144  .  .  .  .  .  .  .  .  .  0: *ast.KeyValueExpr {
   145  .  .  .  .  .  .  .  .  .  .  Key: *ast.Ident {
   146  .  .  .  .  .  .  .  .  .  .  .  NamePos: foo:9:21
   147  .  .  .  .  .  .  .  .  .  .  .  Name: "someField"
   148  .  .  .  .  .  .  .  .  .  .  .  Obj: *(obj @ 92)
   149  .  .  .  .  .  .  .  .  .  .  }
   150  .  .  .  .  .  .  .  .  .  .  Colon: foo:9:31
   151  .  .  .  .  .  .  .  .  .  .  Value: *ast.BasicLit {
   152  .  .  .  .  .  .  .  .  .  .  .  ValuePos: foo:9:33
   153  .  .  .  .  .  .  .  .  .  .  .  Kind: INT
   154  .  .  .  .  .  .  .  .  .  .  .  Value: "42"
   155  .  .  .  .  .  .  .  .  .  .  }
   156  .  .  .  .  .  .  .  .  .  }
```

**Comment by findleyr** [comment]
This is a known inaccuracy of object resolution in go/parser. The parser doesn't know whether someStruct is a struct or a map[int]int.  If it were a map[int]int, the incorrect resolution would actually be correct:
https://play.golang.org/p/H_1ozX1hV4P

You can use go/types to get accurate information.

See also #46485, which contains some additional background.

Closing as this is infeasible to fix.
