### ISSUE TITLE
go/types: add tests that exercise concurrent use

### ISSUE THREAD

**Issue by findleyr** [golang/go#47729]
x/tools has tests that exercise concurrent use of go/types, but go/types itself does not. With the various lazy operations in go/types, it is easy to introduce race conditions. This has bitten us several times in the past (#47726, #47345, #44434, from recent memory).

We should add tests that exercise valid concurrent use of go/types.

CC @griesemer

**Comment by ianlancetaylor** [comment]
@findleyr  This is in the 1.18 milestone; time to move to 1.19?  Thanks.

**Comment by ianlancetaylor** [comment]
@findleyr This is in the 1.19 milestone; time to move to 1.20? Or Backlog?  Thanks.
