### ISSUE TITLE
cmd/go: `mod tidy -go=1.17` should move indirect dependencies to the second require part

### ISSUE THREAD

**Issue by FireFart** [golang/go#47733]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/firefart/.cache/go-build"
GOENV="/home/firefart/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/firefart/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/firefart/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/firefart/code/project/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build661731482=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

ran `go mod tidy -go=1.17` as described on https://golang.org/doc/go1.17

### What did you expect to see?

I expected to see that the `// indirect` dependencies in my `go.mod` file get moved to the second indirect `require` part of the file.

### What did you see instead?

Some new indirect dependencies were added but the old `// indirect` are left untouched. If I remove the indirect entries from the first `require` block and run the command again, they are only added to the bottom. This is no deal breaker but I think this could be improved to make the go.mod file a bit clearer by also moving all previous indirects to the second block.

```
Because the number of explicit requirements may be substantially larger in an expanded Go 1.17 go.mod file, the newly-added requirements on indirect dependencies in a go 1.17 module are maintained in a separate require block from the block containing direct dependencies.
```

**Comment by seankhliao** [comment]
Can you share your go.mod?

**Comment by FireFart** [comment]
Sure here is my `go.mod` from go 1.16

```
module xxxx/yyy

go 1.16

require (
	github.com/DATA-DOG/go-sqlmock v1.5.0
	github.com/aws/aws-sdk-go-v2 v1.8.0
	github.com/aws/aws-sdk-go-v2/credentials v1.3.2
	github.com/aws/aws-sdk-go-v2/service/s3 v1.12.0
	github.com/aws/aws-sdk-go-v2/service/sesv2 v1.4.2
	github.com/cloudflare/cloudflare-go v0.20.0
	github.com/felixge/httpsnoop v1.0.2 // indirect
	github.com/go-redis/redis/v8 v8.11.3
	github.com/go-sql-driver/mysql v1.6.0
	github.com/gorilla/handlers v1.5.1
	github.com/gorilla/mux v1.8.0
	github.com/prometheus/client_golang v1.11.0
	github.com/prometheus/common v0.30.0 // indirect
	github.com/prometheus/procfs v0.7.2 // indirect
	github.com/sirupsen/logrus v1.8.1
	github.com/slack-go/slack v0.9.4
	github.com/streadway/amqp v1.0.0
	github.com/stripe/stripe-go/v72 v72.60.0
	golang.org/x/net v0.0.0-20210813160813-60bc85c4be6d // indirect
	golang.org/x/sys v0.0.0-20210816074244-15123e1e1f71 // indirect
	golang.org/x/text v0.3.7 // indirect
	golang.org/x/time v0.0.0-20210723032227-1f47c861a9ac // indirect
	google.golang.org/genproto v0.0.0-20210813162853-db860fec028c // indirect
	google.golang.org/grpc v1.40.0
	google.golang.org/protobuf v1.27.1
)
```

**Comment by andig** [comment]
I can confirm this finding. 

I've also noticed another "weird" behaviour: while the second part is generated during `go mod tidy -go=1.17`, if I merge the two require sections and run the command again, it will remain a single section. This seems a bit inconsistent as running tidy multiple times will lead to different results.

**Comment by seankhliao** [comment]
cc @bcmills @jayconrod @matloob

**Comment by jayconrod** [comment]
@gopherbot Please backport to 1.17. This is annoying behavior in a new feature, and the fix shouldn't be very disruptive.

**Comment by thomasf** [comment]
I don't know if it's related but in some projects I now have three require blocks which I don't think is explicitly mentioned in this issue before.

The first one has mixed direct and indirect dependencies, the second one only has direct dependencies and the third one only has indirect dependencies.

I belive that `go mod tidy -go=1.17` maybe didn't do what it was supposed to correclty. The bottom sections are added by `go get` of previously uninstalled dependencies after the 

```
module redacted

go 1.17

require (
	github.com/aws/aws-sdk-go v1.40.32
	github.com/beorn7/perks v1.0.1 // indirect
	github.com/buger/jsonparser v1.1.1
	github.com/cespare/xxhash/v2 v2.1.2 // indirect
	github.com/getsentry/sentry-go v0.11.0
	github.com/golang/protobuf v1.5.2 // indirect
	github.com/gorilla/mux v1.8.0
	github.com/jmespath/go-jmespath v0.4.0 // indirect
	github.com/justinas/alice v1.2.0
	github.com/kr/text v0.2.0 // indirect
	github.com/matttproud/golang_protobuf_extensions v1.0.1 // indirect
	github.com/niemeyer/pretty v0.0.0-20200227124842-a10e7caefd8e // indirect
	github.com/peterbourgon/ff/v3 v3.1.0
	github.com/pmezard/go-difflib v1.0.0 // indirect
	github.com/prometheus/client_golang v1.11.0
	github.com/prometheus/client_model v0.2.0 // indirect
	github.com/prometheus/common v0.30.0 // indirect
	github.com/prometheus/procfs v0.7.3 // indirect
	github.com/rs/xid v1.3.0
	github.com/rs/zerolog v1.24.0
	github.com/stretchr/testify v1.7.0
	golang.org/x/crypto v0.0.0-20210817164053-32db794688a5
	golang.org/x/sys v0.0.0-20210630005230-0f9fa26af87c // indirect
	google.golang.org/protobuf v1.27.1 // indirect
	gopkg.in/check.v1 v1.0.0-20200227125254-8fa46927fb4f // indirect
	gopkg.in/natefinch/lumberjack.v2 v2.0.0
	gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b // indirect
)

require (
	github.com/benbjohnson/hashfs v0.1.0
	github.com/davecgh/go-spew v1.1.1
)

require (
	github.com/MicahParks/keyfunc v0.7.0 // indirect
	github.com/dgrijalva/jwt-go v3.2.0+incompatible // indirect
	github.com/form3tech-oss/jwt-go v3.2.5+incompatible // indirect
	github.com/golang-jwt/jwt/v4 v4.0.0 // indirect
	github.com/gorilla/securecookie v1.1.1 // indirect
	github.com/pkg/errors v0.9.1 // indirect
)

```

If it's supposed to be three sections that I am sorry for making a noise about it if it isn't maybe `go mod tidy` should be able to fix this situation as well.
