### ISSUE TITLE
Test binary files couldn't be executed in docker images

### ISSUE THREAD

**Issue by juan-chan** [golang/go#47734]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.16.5 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/juan/.cache/go-build"
GOENV="/home/juan/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/juan/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/juan/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1654166708=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I built my `test.go` to a binary file by `go test -c xxx_test.go -o test`, and copied it to a docker image, I want to execute it
by using `CMD ["/app/test", "-test.v"]`, but I got an error: `/entrypoint.sh: exec: line 14: /app/test: not found`.

I tried to change some other base images, but neither could fix this, included `golang:1.16` (and alpine).

I ran into the image, and executed it by myself, I tried:

```sh
/app # ls -lFh
total 14M    
-rw-rw-r--    1 root     root         324 Aug 17 06:05 Dockerfile
-rw-rw-r--    1 root     root         960 Aug 17 06:05 config.yml
-rwxrwxr-x    1 root     root       13.5M Aug 17 06:05 test*
/app # ./test
sh: ./test: not found
/app # ./test*
sh: ./test: not found
/app # sh test
test: line 1: ELF: not found
test: line 2: D�: not found
test: test: line 1: line 2: w�: not found@$: not found

test: line 2: Dp�p�pנ��@q�@q�@q�0Q�td�e@�R: not found
test: line 3: �: not found
test: line 4: syntax error: unexpected ")"
/app # go version
go version go1.17 linux/amd64
```

But I could execute it in my computer, my os: `amd64 ubuntu 18.04.TLS`

What's wrong with this binary file? Why couldn't I execute it in a docker image? What should I do now?

### What did you expect to see?

Execute go test binary files in docker images.

### What did you see instead?

`/entrypoint.sh: exec: line 14: /app/test: not found`

`./test not found`

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by juan-chan** [comment]
I see. Anyway thanks for your reply, I figured this out just now.
