### ISSUE TITLE
windows defender of windows 10 reported virus

### ISSUE THREAD

**Issue by longjin1991** [golang/go#47731]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.17

</pre>

### What operating system and processor architecture are you using (`go env`)?

windows 10 64bit

</pre></details>

### What did you do?

i build example: go build ./main.go
// You can edit this code!
// Click here and start typing.
package main

import "fmt"

func main() {
	fmt.Println("Hello, 世界")
}

and windows defender of windows 10 reported virus and kill it.
Why does the golang program contain viruses?, please fix it.
![Capture](https://user-images.githubusercontent.com/23453308/129657584-2e75f7ef-762a-4270-b57c-3da26273313e.PNG)

this is the result when i scan on virustotal.com
https://www.virustotal.com/gui/file/356e4ac39a9ec0946dcecf7df5e184b4615333595ec11e53f3d63b2a98a04d2f/detection
![Capture](https://user-images.githubusercontent.com/23453308/129658143-4b397b4e-a9dd-4f5e-8d47-19881b0c5ebf.PNG)

**Comment by ianlancetaylor** [comment]
See https://golang.org/doc/faq#virus.
