### ISSUE TITLE
go mod tidy -go=1.17 doesn't work on Windows

### ISSUE THREAD

**Issue by leaanthony** [golang/go#47743]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\leaan\AppData\Local\go-build
set GOENV=C:\Users\leaan\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\leaan\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\leaan\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\leaan\AppData\Local\Temp\go-build3096104381=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
Ran `go mod tidy -go=1.17`

### What did you expect to see?
The command to work

### What did you see instead?
<pre>
> go mod tidy -go=1.17
invalid value "1" for flag -go: expecting a Go version like "1.17"
usage: go mod tidy [-e] [-v] [-go=version] [-compat=version]
Run 'go help mod tidy' for details.
</pre>

# Workaround
If you use double dash it works as expected:
<pre> go mod tidy --go=1.17</pre>

**Comment by seankhliao** [comment]
is this CMD, powershell or something else?

**Comment by jbdk** [comment]
I can can confirm the problem under powershell (v5.1)
It works fine under normal cmd

**Comment by seankhliao** [comment]
This is a powershell bug: https://github.com/PowerShell/PowerShell/issues/6291

Closing as there's nothing Go can do (it happens before it reaches `go`)

**Comment by leaanthony** [comment]
Ah, thanks for the clarification.
