### ISSUE TITLE
How can I prevent net/http send Pseudo-Header ?

### ISSUE THREAD

**Issue by qiankunxienb** [golang/go#47744]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.15.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code>
 </summary><br><pre>
$ go env

GOHOSTARCH="amd64"
 GOHOSTOS="darwin"
</pre></details>

### What did you do?

I have made requests from Python and Golang and compare the requests headers. I find there are one key different:

Headers by Python httpx:

![Headers by Python httpx](https://user-images.githubusercontent.com/71627005/129714802-133509a8-4789-442e-90ed-f36df086dd35.png)

Headers by Golang net/http
![Headers by Golang net/http](https://user-images.githubusercontent.com/71627005/129714885-b528843a-436d-45fa-8733-f80d28b6a77f.png)

Why do golang's net/http add the pseudo headers? How to prevent or remove these pseudo header?

### What did you expect to see?

Remove the pseudo headers fields.

### What did you see instead?

```
:authority: httpbin.org
:method: GET
:path: /headers
:scheme: https
```

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by davecheney** [comment]
These headers are part of the HTTP/2 request. HTTP/2 does not use a request line
