### ISSUE TITLE
x/website: error accessing "Writing Web Applications" section in docs

### ISSUE THREAD

**Issue by michaelgrigoryan25** [golang/go#47759]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.7 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I just visited https://golang.org/doc/articles/wiki/

### What did you expect to see?
I expected to see the page describing how to create a simple wiki using Go.

### What did you see instead?
I saw this error

```
template execution: template: doc/articles/wiki/index.html:77:2: executing "doc/articles/wiki/index.html" at <code "doc/articles/wiki/part1.go" `/^type Page/` `/}/`>: error calling code: open _content/doc/articles/wiki/doc/articles/wiki/part1.go: no such file or directory
```

![image](https://user-images.githubusercontent.com/56165400/129784865-6dca5b7d-cda0-433d-81bf-71457c0f114f.png)

**Comment by mknyszek** [comment]
CC @dmitshur who's listed as the owner of a bunch of other x/website packages.

**Comment by dmitshur** [comment]
This is likely introduced by recent x/website changes. @rsc Can you take a look?
