### ISSUE TITLE
x/website: /ref/mod page runs into template execution error as of CL 339403

### ISSUE THREAD

**Issue by AlekSi** [golang/go#47751]
### What did you do?

Opened https://golang.org/ref/mod in Safari 14.1.2 on macOS 11.5.1.

### What did you expect to see?

Working website.

### What did you see instead?

![image](https://user-images.githubusercontent.com/11512/129763725-89b267bb-800a-40d0-88aa-1e32364e7d45.png)

**Comment by AlekSi** [comment]
I guess it is the same as #47750.

**Comment by AlekSi** [comment]
Or not, as this issue is about golang.org, not golang.google.cn

**Comment by seankhliao** [comment]
cc @dmitshur

**Comment by dmitshur** [comment]
Thanks for reporting.

The last good version was golang/website@f8f1822, rolled back golang.org to that.

The problem is introduced with the following commit, golang/website@ef7fed48ece033b41e88ed9a4cf40cdf9bd9de05.

**Comment by forging2012** [comment]
Nice job!
It has now recovered.
Thanks all!
