### ISSUE TITLE
x/website: test page returns 500

### ISSUE THREAD

**Issue by fgm** [golang/go#47761]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 darwin/amd64
</pre>
(not applicable, this is a website issue)

### Does this issue reproduce with the latest release?

Yes, this is a website issue

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/fgm/Library/Caches/go-build"
GOENV="/Users/fgm/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/fgm/src/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/fgm/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org|direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/fgm/src/go/src/github.com/golang/website/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0g/p780bc554njc4qj110_8rmbr0000gn/T/go-build4101997795=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

(irrelevant, this is a website issue)

### What did you do?

Navigate to https://golang.org/test/

### What did you expect to see?

A normal page

### What did you see instead?

A 500 page with that content:

```
Error
template execution: template: site.tmpl:81:18: executing "site.tmpl" at <breadcrumb .URL>: error calling breadcrumb: template: site.tmpl:68:16: executing "breadcrumb" at <slice $elems 0 (sub (len $elems) 2)>: error calling slice: index out of range: -1
```

**Comment by fgm** [comment]
Bug apparently introduced when https://go-review.googlesource.com/c/website/+/339403 added use of `{{breadcrum .URL}}` in `site.tmpl` while moving it around.

**Comment by mknyszek** [comment]
CC @dmitshur

**Comment by dmitshur** [comment]
Thanks for reporting and bisecting @fgm.

CC @rsc as the author of [CL 339403](https://golang.org/cl/339403).
