### ISSUE TITLE
[Question] go tool pprof

### ISSUE THREAD

**Issue by clyang82** [golang/go#47770]
I have a pod use `7718Mi` memory when I use `top` to check.
But when I use `go tool pprof` to check the in-used memory usage, I can see `2215.54MB total`.
```
File: thanos
Type: inuse_space
Time: Aug 11, 2021 at 2:30pm (UTC)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 1854.79MB, 83.72% of 2215.54MB total
Dropped 121 nodes (cum <= 11.08MB)
Showing top 10 nodes out of 69
      flat  flat%   sum%        cum   cum%
  569.03MB 25.68% 25.68%   569.03MB 25.68%  github.com/thanos-io/thanos/pkg/store/labelpb.ReAllocZLabelsStrings
  418.21MB 18.88% 44.56%   418.21MB 18.88%  github.com/thanos-io/thanos/pkg/store/storepb/prompb.(*TimeSeries).Unmarshal
  238.55MB 10.77% 55.33%   329.05MB 14.85%  github.com/prometheus/prometheus/tsdb.newMemSeries
  129.54MB  5.85% 61.17%   129.54MB  5.85%  github.com/prometheus/prometheus/tsdb/chunkenc.(*bstream).writeByte
   92.58MB  4.18% 65.35%    92.58MB  4.18%  github.com/prometheus/prometheus/tsdb/index.(*MemPostings).Delete
   90.50MB  4.08% 69.44%    90.50MB  4.08%  github.com/prometheus/prometheus/tsdb.newTxRing (inline)
   87.01MB  3.93% 73.36%    87.01MB  3.93%  github.com/prometheus/prometheus/tsdb/chunkenc.NewXORChunk
   84.34MB  3.81% 77.17%    84.34MB  3.81%  github.com/prometheus/prometheus/tsdb.seriesHashmap.set
   83.01MB  3.75% 80.92%    83.01MB  3.75%  github.com/prometheus/prometheus/tsdb/encoding.(*Decbuf).UvarintStr (inline)
   62.03MB  2.80% 83.72%   144.53MB  6.52%  github.com/prometheus/prometheus/tsdb/record.(*Decoder).Series

```

What is gap here?

I saw there has answer in https://groups.google.com/g/golang-nuts/c/eEGrfc7taU0
> `top` This is the amount of physical RAM dedicated to your
program right now.
while, `pprof` is allocated heap.

But why it has big gap here? does it mean that there is memory leak? Thanks.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by mengzhuo** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by mdlayher** [comment]
See above, closing.
