### ISSUE TITLE
encoding/csv: documentation of `UseCRLF` is incomplete

### ISSUE THREAD

**Issue by rs-blade** [golang/go#47774]
According to the documentation of the UseCRLF flag here:
https://github.com/golang/go/blob/946e2543f878929752da9d16575dd5e96ac78532/src/encoding/csv/writer.go#L23

it only influences the line terminator. When looking at the code one can see that setting that flag to _true_ also impacts the output of the cell content: \r is removed and \n replaced by \r\n.
This behavior should also be reflected in the documentation!

**Comment by seankhliao** [comment]
csv doesn't escape newlines in cell contents, so if there's a newline in a cell it is also the end of an output line.

"hello", "foo\nbar", "world"
as csv would be 
```
hello,"foo
bar",world
```

**Comment by ruediger-stevens** [comment]
You're right. What I meant when writing \r and \n was the characters 13 and 10.
So to be clear: If UseCRLF is true a string of chars 0x41 0x0d 0x42 will become 0x22 0x41 0x42 0x22. So a quoted string where the 0x0d is removed (see here: https://github.com/golang/go/blob/8b471db71b95e9250f751f494a6a5359cb50d5cd/src/encoding/csv/writer.go#L89)
On the other hand  0x41 0x0a 0x42 becomes 0x22 0x41 0x0d 0x0a 0x42 0x22 (see here: https://github.com/golang/go/blob/8b471db71b95e9250f751f494a6a5359cb50d5cd/src/encoding/csv/writer.go#L97)

I think this is important to know, so the documentation should tell you about that behavior.

**Comment by seankhliao** [comment]
I understood that part, I'm saying that because it's not escaped in csv, an output line != single record and it changes all output line endings, not just end of record endings.
But feel free to send a PR/CL with what you think would make it clearer
