### ISSUE TITLE
x/tools/gopls: incorrect highlight of imports with major version suffix (semantic tokens)

### ISSUE THREAD

**Issue by papa-whisky** [golang/go#47784]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.17 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.7.1
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.59.0
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.27.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- I don't _think_ this is relevant to this issue? Let me know if so though and I'll provide it. As an aside, this command prints my go env, which in my case includes a `goproxy` URL that shows my API token, and I may well have pasted it here if I hadn't been more careful. Perhaps this template could advise caution before pasting?

### Share the Go related settings you have added/edited

```json
{
  "go.useLanguageServer": true,
  "[go]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    },
    "editor.snippetSuggestions": "none"
  },
  "gopls": {
    "usePlaceholders": true,
    "staticcheck": false,
    "gofumpt": true,
    "ui.semanticTokens": true
  },
  "go.lintTool": "golangci-lint",
  "go.toolsManagement.autoUpdate": true
}
```

### Describe the bug

With the `ui.semanticTokens` feature enabled, the package name is highlighted in import statements. However, if the import ends in `/vN` the highlighting is incorrect; the version is highlighted rather than the package name. Refer screenshot below.

### Steps to reproduce the behavior:
1. Set the `"ui.semanticTokens": true` option.
2. Use the default "Dark+" theme.
3. Import a package with a version suffix in the import path.

### Screenshots or recordings

<img width="291" alt="image" src="https://user-images.githubusercontent.com/20717799/129858594-182cd203-526c-44cc-b71d-d0dc76d9cd82.png">

**Comment by pjweinb** [comment]
Thanks for the report. I believe I know how to fix it.

**Comment by stamblerre** [comment]
Fixed by https://golang.org/cl/343909
