### ISSUE TITLE
reflect: ConvertibleTo returns false in go1.17 for slice values that previously returned true

### ISSUE THREAD

**Issue by liggitt** [golang/go#47785]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/liggitt/Library/Caches/go-build"
GOENV="/Users/liggitt/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/liggitt/.gvm/pkgsets/go1.17/global/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/liggitt/.gvm/pkgsets/go1.17/global"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/liggitt/.gvm/gos/go1.17"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/liggitt/.gvm/gos/go1.17/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/liggitt/tmp/convertible117/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7f/9xt_73f12xlby0w362rgk0s400kjgb/T/go-build2916420994=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Used the reflect ConvertibleTo function (via a call to https://github.com/stretchr/testify/blob/v1.7.0/assert/assertions.go#L78-L96) to compare slices of two different types with identical names/members/layouts in different packages. 

This worked as expected prior to go 1.17.

Minimal reproducer at https://github.com/liggitt/convertible117/blob/master/convertible_test.go

### What did you expect to see?

```
gvm use go1.16 && go test ./ -v -count=1
Now using version go1.16
=== RUN   TestConvertible
--- PASS: TestConvertible (0.00s)
PASS
ok  	github.com/liggitt/convertible117	0.629s
```

### What did you see instead?

```
gvm use go1.17 && go test ./ -v -count=1
Now using version go1.17
=== RUN   TestConvertible
    convertible_test.go:24: !convertible
--- FAIL: TestConvertible (0.00s)
FAIL
FAIL	github.com/liggitt/convertible117	0.566s
FAIL
```

**Comment by liggitt** [comment]
it looks like this was introduced in https://github.com/golang/go/commit/7473a6a0ebb270c24c20994d3ea6e3fd96def223#diff-8d7fac7a0925d669f941654f9b1cc5ea0be70dd93bfa3ab255456e510cd98cd7R1602 which added a PkgPath equality requirement to `haveIdenticalType`

**Comment by randall77** [comment]
If anything, this is a bug in 1.16.

If you add 
```
	_ = ([]b.Reference)(actual)
```

The compiler complains that the conversion is not allowed (both in 1.16 and 1.17).

Converting slices with different named element types, even if their structure is the same, is not allowed.

**Comment by mknyszek** [comment]
Based on @randall77's comment, it seems like the new behavior is technically more correct. Did the actual conversion also used to succeed? If so, this might be a breaking change (not saying we should roll it back, but maybe something to be aware of).

**Comment by liggitt** [comment]
> Based on @randall77's comment, it seems like the new behavior is technically more correct. Did the actual conversion also used to succeed?

yeah, it did (see the test case), which is really unfortunate

**Comment by randall77** [comment]
The behavior changed at https://go-review.googlesource.com/c/go/+/309729
Not sure that was intentional.

@jinzhu @ianlancetaylor 

@griesemer Am I right, that the new behavior is correct?

**Comment by liggitt** [comment]
> If so, this might be a breaking change (not saying we should roll it back, but maybe something to be aware of).

It seems like this a breaking change that is in bounds per https://golang.org/doc/go1compat ("If a compiler or library has a bug that violates the specification, a program that depends on the buggy behavior may break if the bug is fixed. We reserve the right to fix such bugs.")

At the very least this needs to be documented in the release notes, but it's worth asking if the benefits gained by the change outweigh the breakage incurred, or if there is an alternate way to fix the issue https://go-review.googlesource.com/c/go/+/309729 was addressing without breaking existing programs.

**Comment by randall77** [comment]
It definitely seems like a bug. This code prints false:
```
package main

import "reflect"

type A struct {
}
type B struct {
}

func main() {
	a := []A{}
	b := []B{}

	println(reflect.ValueOf(a).Type().ConvertibleTo(reflect.ValueOf(b).Type()))
}
```

In 1.16, `ConvertibleTo` only reports `true` if the base types are from two different packages and are identically named. That can't be right.

**Comment by randall77** [comment]
But I agree, we don't want to break existing programs lightly. We'll have to ponder whether/how to fix this, or document it, or whatever.

**Comment by ianlancetaylor** [comment]
As discussed above, this change is correct.  The types are not convertible and `reflect.ConvertibleTo` should not be reporting that they are convertible.  This change seems clearly correct.

I agree that this should be in the release notes.  It didn't occur to me that this would affect `ConvertibleTo` and `AssignableTo` in this way.

It's unfortunate that this breaks existing programs, but the earlier behavior was clearly a bug.  The reflect package should not be reporting that types are convertible when they are not convertible in the language.

We actually got the correct answer here in Go releases up to 1.7.  It broke in Go 1.8.  Looks like the breaking change was https://golang.org/cl/24190.

**Comment by randall77** [comment]
24190 was just the spec change, the actual breaking CL was https://go-review.googlesource.com/c/go/+/30191

**Comment by randall77** [comment]
Remilestoned to 1.17 for a doc fix.

**Comment by toothrot** [comment]
Change https://golang.org/cl/343669 can be abandoned, as we don't generally keep the release-branch's HTML up to date. The x/website change will correctly update the documentation.
