### ISSUE TITLE
x/pkgsite: improve pkgsite command 

### ISSUE THREAD

**Issue by jba** [golang/go#47780]
Improve golang.org/x/pkgsite/cmd/pkgsite so it can be used instead of golang.org/x/tools/cmd/godoc.

- [x] Serve modules from the module cache.
- [x] Serve modules directly from the proxy.

**Comment by peterbourgon** [comment]
> so it can be used instead of golang.org/x/tools/cmd/godoc

Please do not remove or deprecate godoc 🙏

**Comment by scott-cotton** [comment]
> > so it can be used instead of golang.org/x/tools/cmd/godoc
> 
> Please do not remove or deprecate godoc 🙏

godoc still has all the -analysis flags.  Does pkgsite offer that?

**Comment by jba** [comment]
> godoc still has all the -analysis flags. Does pkgsite offer that?

No.

`cmd/pkgsite` will just serve documentation from the local filesystem and, optionally, directly from the proxy. It won't have all the features of godoc. We won't remove `golang.org/x/tools/cmd/godoc`; feel free to use it as long as you wish.

**Comment by jba** [comment]
> An alternative could be an index page listing all the available modules from the cache.
> 
> > They are, it just takes a while for the first package (about a minute on my machine) because it has to clone the go repo and process it. After that, it's cached, so pretty fast.

Just added this: if you clone the go repo and point to it with the `-gorepo` flag, standard library pages will render slightly faster (not a lot faster).

**Comment by jba** [comment]
Since #47982 is done, I'm going to close this.
