### ISSUE TITLE
x/website: No Atom feed linked in new blog header

### ISSUE THREAD

**Issue by Merovius** [golang/go#47795]
### What is the URL of the page with the issue?

https://go.dev/blog/
 
### What did you do?
 
Tried subscribing to the new blog url via feedly. When that didn't work, looked at the web inspector.
 
### What did you expect to see?
 
A link to an RSS, Atom or JSON feed to subscribe in the `<head>`.

It seems the old link redirects to https://go.dev/blog/feed.atom which serves an Atom feed. Would be great to `<link>` that in the HTML as well, for discovery.

**Comment by dmitshur** [comment]
CC @jamalc, @rsc.

**Comment by sbinet** [comment]
now that `https://blog.golang.org` redirects to `https://go.dev/blog`, it would be great to have _a_ feed in place, be it RSS, Atom or JSON :)
