### ISSUE TITLE
cmd/compile: no stmt flag set for two lines of code that do generate instructions

### ISSUE THREAD

**Issue by aarzilli** [golang/go#47793]
```
$ go version
go version go1.17 linux/amd64
```

it also reproduces on 1.17 windows/amd64 and 1.16.

Reproduction steps:

1. Compile the tests of package `github.com/dolthub/dolt/go/libraries/doltcore/sqle` with `-gcflags='all=-N -l'` (commit d2c3c987593fe82e0571ffd3fda09afd340b4634 will do this)
2. See the pcln table generated for `github.com/dolthub/dolt/go/libraries/doltcore/sqle.NewTestEngine`
3. Lines 120 and 121 have instructions generated but none of them have the stmt flag set

Originally reported as https://github.com/go-delve/delve/issues/2664
cc @dr2chase

**Comment by dr2chase** [comment]
It happens in expand calls, not sure of the exact failure yet, other than the statement was hanging off an OpDereference.
To see for yourself:
```
git clone https://github.com/dolthub/dolt
cd dolt/go/libraries/doltcore/sqle
GOSSADIR=`pwd` GOSSAFUNC=NewTestEngine go test -c -gcflags=all='-N -l' .
```
