### ISSUE TITLE
types2, go/types: self-referential type parameter list is not accepted

### ISSUE THREAD

**Issue by griesemer** [golang/go#47796]
Example:

```Go
package p
type Eq[a Eq[a]] interface {
	Equal(that a) bool
}
```

produces

```
:2:13: Eq is not a generic type
```

Should this be permitted?

cc: @ianlancetaylor

**Comment by griesemer** [comment]
In any case, the error message needs to be fixed. `Eq` is a generic type.

**Comment by ianlancetaylor** [comment]
I can't think of a reason to forbid this.  It seems well-defined.  It would be more problematic in a function definition, where we would have to derive an operation set, but of course this can't happen in a function definition and the problem doesn't arise in a type definition.
