### ISSUE TITLE
x/website: golang.org wrongly redirects to golang.google.cn sometimes

### ISSUE THREAD

**Issue by ericlagergren** [golang/go#47808]
Upon visiting `golang.org` I'm redirected to `golang.google.cn`. This is wrong as my IP addresses are from the United States.

IPv6: 2001:19f0:8001:1ef6:5400:3ff:fe84:5ac
IPv4: 144.202.86.213

Also affects the playground.

**Comment by mknyszek** [comment]
CC @dmitshur

**Comment by xxchan** [comment]
Also for go.dev

**Comment by rsc** [comment]
As background, on the China-available Go home page we cannot serve user-generated content like playground shares. 
Until recently the way we did this was by silently dropping content based on where the request came from.
So for example requests served for golang.org to China left out the Share button under the home page playground.
The same was true for golang.google.cn, which is the actual page that is visible in China.

This IP-specific content bothered me and complicated caching, so I changed the code for 'golang.org in China', which is supposed to not happen anymore (golang.org was visible in China for a few months back in ~2018, long story) to redirect to golang.google.cn, before any cache lookups. Then any caching is fine.

This redirect has the effect of making it much clearer when we accidentally think a request is coming from China. Before, a few links would be missing and people wouldn't notice at all. Now, the redirect happens, which is more noticeable. Especially if the redirect changes a go.dev request to golang.org, which breaks the request entirely.

I put the old serving stack back up at https://oldstack-dot-golang-org.appspot.com/golang.org/. 
@ericlagergren and @xxchan, I'd be interested to know whether you see a "Share" link under the home page playground.

I will also look into why the geolocation is not working correctly. I wish we didn't have to do any of this, of course, but it is well beyond my powers to change these rules.

**Comment by xxchan** [comment]
@rsc There's no "Share".

**Comment by ericlagergren** [comment]
@rsc thanks for the explanation! I always appreciate how thoughtful you are.

> I'd be interested to know whether you see a "Share" link under the home page playground.

I do not.

> I will also look into why the geolocation is not working correctly.

Thank you. FWIW: the IP addresses in question are attached to my VPS which is located (five minutes from me!) in Seattle. If I'm not signed in, Google redirects me to `google.com.hk`. I think they've flagged whole blocks of addresses owned by Vultr as this isn't these aren't the first IP address it's happened with—just the first time I've decided to create an issue. :)

> I wish we didn't have to do any of this, of course, but it is well beyond my powers to change these rules.

I understand—it's definitely unfortunate.

**Comment by rsc** [comment]
Thanks for checking the old site. Now that we have the separate domain, I've gotten approval to drop the IP-based check here entirely. That should be in effect within a day or so and will fix this problem for golang.org.

**Comment by rsc** [comment]
As of right now the IP-based check should no longer be active. Thanks for the reports.
