### ISSUE TITLE
windows: go.exe from 1.17 msi installer is classified as malware

### ISSUE THREAD

**Issue by ah-edg** [golang/go#47807]
For https://golang.org/dl/go1.17.windows-amd64.msi
Defender reports Trojan:Win32/Zpevdo.B in go.exe (https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fZpevdo.B&threatid=2147729093)

Virustotal also shows 4 flags:
https://www.virustotal.com/gui/file/f81084fceedd3b422b105e3b6d1eff4520c23a1e9723342d860d92fad6314158/detection

**Comment by lyp256** [comment]
me too 
![image](https://user-images.githubusercontent.com/19305389/130031397-37573f61-24ef-44ff-a0ff-78d0a29e4164.png)

**Comment by ALTree** [comment]
False positive: https://golang.org/doc/faq#virus

Happens at every new release. They'll whitelist the 1.17 binaries and in a few days it'll be fixed.
