### ISSUE TITLE
x/website: google search results have incorrect title for documentation pages

### ISSUE THREAD

**Issue by prashantv** [golang/go#47805]
### What did you do?

Search google for "golang net http",
https://www.google.com/search?q=net+http+golang

### What did you expect to see?
The first result to be the [documentation for net/http ](https://pkg.go.dev/net/http)and the title of the result to be the title of the page, `http · net/http · pkg.go.dev`

### What did you see instead?

The first result was the correct URL, but the title is incorrect: `Documents - The Go Programming Language`

Screenshot:
![image](https://user-images.githubusercontent.com/140159/130019604-46e33900-7985-4967-9146-d66381177c83.png)

-----

This problem seems to affect subpackages, and different searches have different results. E.g., searching for ioutil,
https://www.google.com/search?q=ioutil+golang
has a title of `io.ioutil.ReadAll - The Go Programming Language` (picks a specific function).

I think this change is related to the stdlib being redirected to pkg.go.dev (referenced in https://go.dev/blog/tidy-web)

**Comment by mknyszek** [comment]
CC @dmitshur via https://dev.golang.org/owners

**Comment by seankhliao** [comment]
I think this can be closed now? Google search appears to have updated the indexed titles

**Comment by dmitshur** [comment]
Agreed, nothing more to do here.
