### ISSUE TITLE
x/pkgsite: unexpected added in version

### ISSUE THREAD

**Issue by Tanmay451** [golang/go#47819]
### What is the URL of the page with the issue?
 https://pkg.go.dev/log@go1.17#pkg-functions
 
 
### Screenshot
 

 
![Screenshot from 2021-08-19 23-05-52](https://user-images.githubusercontent.com/39707028/130117223-98b48ca1-8c18-4bab-a712-a58834192e5b.png)

 
 
### What did you expect to see?
added in go1.15
 
 
### What did you see instead?
added in go1.5

**Comment by julieqiu** [comment]
It seems like `log.Output` is present in go1.5 - https://go.googlesource.com/go/+/go1.5/src/log/log.go#344.

What made you expect to see go1.15?
