### ISSUE TITLE
crypto/rand: getentropy is not available on iOS

### ISSUE THREAD

**Issue by crawshaw** [golang/go#47812]
Go 1.17 switched to using getentropy in https://go-review.googlesource.com/c/go/+/302489. This function is marked private on iOS, so cannot be used by iOS apps:

```
ITMS-90338: Non-public API usage - The app references non-public
symbols in PlugIns/IPNExtension.appex/IPNExtension: _getentropy,
The app references non-public symbols in Tailscale: _getentropy.
```

**Comment by mknyszek** [comment]
CC @tklauser @ianlancetaylor @FiloSottile

**Comment by tklauser** [comment]
Sent https://golang.org/cl/343609 with a possible fix. I assume this should also be backported to 1.17?

**Comment by bradfitz** [comment]
Yes, this is a regression from Go 1.16 so I'd assume we'd backport.

**Comment by bradfitz** [comment]
@gopherbot, please cherry pick to Go 1.17.

**Comment by bradfitz** [comment]
@gopherbot, please backport to Go 1.17. It is a regression.

**Comment by DentonGentry** [comment]
Following up: we used a 1.17 toolchain with this fix applied to build our iOS app, and it passed the review process. Previously it was rejected for using the non-public `_getentropy` API.
