### ISSUE TITLE
Alpine based golang docker image for linux/s390x architecture missing  

### ISSUE THREAD

**Issue by Ashmita152** [golang/go#47810]
For alpine 3.14 as base image: golang image for linux/s390x arch is missing (which is available for alpine 3.13)

<img width="1607" alt="Screenshot 2021-08-19 at 9 47 24 PM" src="https://user-images.githubusercontent.com/16268376/130064365-d01f8d7a-7ba9-4166-8a03-dfce321d66d0.png">

At first I thought it maybe due to alpine not publishing image for linux/s390x but they do publish it.

<img width="1600" alt="Screenshot 2021-08-19 at 9 48 10 PM" src="https://user-images.githubusercontent.com/16268376/130064545-27c54154-823b-4132-b747-23a347534848.png">

Thanks!

**Comment by ALTree** [comment]
Assuming you're referring to hub.docker.com, these images are not published by this project. You'll have to report this to the people that package it. github.com/docker-library/golang I guess?

Closing here since there's nothing that can be done here.
