### ISSUE TITLE
cmd/go: GOPATH support in Go 1.17

### ISSUE THREAD

**Issue by ZiyaoQiao** [golang/go#47827]
**From the Go blog post:https://go.dev/blog/go116-module-changes, GoPATH support will be dropped in Go1.17, however, after the test, Go 1.17 still supports GOPATH. Also it's not mentioned in the release notes.
Currently, some of our projects are still relying on GOPATH and we're planning to migrate that. So it would be great if we could know when golang will truly drop support fo GOPATH.** 

### What version of Go are you using (`go version`)?

Go 1.17

### Does this issue reproduce with the latest release?

NA

### What operating system and processor architecture are you using (`go env`)?

amd64/linux

### What did you do?

Using GOPATH to import dependencies

### What did you expect to see?

Error running the project

### What did you see instead?
Running successfully

**Comment by ALTree** [comment]
See https://groups.google.com/g/golang-dev/c/hGwvCceDr14/m/On-0pc8OBgAJ

> For GOPATH mode for finding, loading, and building packages (i.e., what the go command does with GO111MODULE=off): we don't actually have a concrete plan to remove it yet. There won't be any major change in Go 1.17. It's possible we'll print a deprecation notice in 1.18, but we haven't settled on anything.

**Comment by mknyszek** [comment]
I think @ALTree's link answers your question. Perhaps that should be more visible? I'm not sure if it's necessary.

CC @jayconrod
