### ISSUE TITLE
cmd/go: option to initialize go mod from git submodules

### ISSUE THREAD

**Issue by mcandre** [golang/go#47824]
Hi,

I have historically used git submodules as the most reliable way to manage library dependencies in my Go projects. I would very much like to migrate to modern Go modules. However, the `go mod init` system does not appear to support generating go.mod configurations from git submodules.

When I try to do this, I either get NO modules in the resulting go.mod file, or else I get the latest versions of everything, which of course breaks my application. Please include automation for migrating `vendor/` directories from git submodules to go.mod.

Furthermore, when I try to explicitly copy the exact same git refs for the dependency versions, then `go mod` operations corrupt these. `go mod` checks out a completely different version of the dependency tree than I have in the original `vendor/` with git submodules.

If someone can help me to reliably migrate the exact same dependency tree to go mod, then I would be grateful.

Example:

https://github.com/mcandre/octane/tree/61e9374d9695f2b3f1489741396f4f3082f3fd74

**Comment by mknyszek** [comment]
CC @bcmills @matloob @jayconrod

**Comment by jayconrod** [comment]
Could you say more about how you're using submodules? Concepts in Go modules and Git submodules don't map directly to each other, so it's not clear to me how this would work or whether it would be feasible.

It sounds like you have submodules checked out into the vendor directory, presumably at locations that correspond to repository root paths. If that's the case, then `git submodule status` would show something like this for each repo:

```
012345abcdef vendor/example.com/repo
```

It's probably feasible for `go mod init` to list directories inside vendor containing .go files, find what submodule they belong to, then build a `go.mod` based on that. Does that sound about right?

We're probably not going to be able to get to this soon; I don't think many people are in this situation. In the mean time, you can simulate the result by using `go get` to pull in each dependency.

```
go get -d example.com/repo@012345abcdef
```

**Comment by mvdan** [comment]
> Could you say more about how you're using submodules? Concepts in Go modules and Git submodules don't map directly to each other, so it's not clear to me how this would work or whether it would be feasible.

This never got a response, and it seems like noone else needs this or cares to implement it, so I'm going to close this feature request for now.
