### ISSUE TITLE
compress/gzip: compressed file can be uncompressed with Linux tar, but not macOS archive utility

### ISSUE THREAD

**Issue by seaguest** [golang/go#47829]
### What version of Go are you using (`go version`)?
go 1.17

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/seaguest/Library/Caches/go-build"
GOENV="/Users/seaguest/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/seaguest/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/seaguest/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/seaguest/Work/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/go-build689013652=/tmp/go-build -gno-record-gcc-switches -fno-common"

```

### What did you do?

```
package main

import (
	"bytes"
	"compress/gzip"
	"encoding/csv"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
)

func main() {
	writeCSV("user.csv")
	compress("user.csv")
}

func writeCSV(fileName string) {
	records := [][]string{
		{"first", "last", "occupation"},
		{"John", "Doe", "gardener"},
		{"Lucy", "Smith", "teacher"},
		{"Brian", "Bethamy", "programmer"},
	}

	f, err := os.Create(fileName)
	defer f.Close()

	if err != nil {
		log.Fatalln("failed to open file", err)
	}

	w := csv.NewWriter(f)
	defer w.Flush()
	for _, record := range records {
		if err := w.Write(record); err != nil {
			log.Fatalln("error writing record to file", err)
		}
	}
}

func compress(fileName string) error {
	var bf bytes.Buffer
	w := gzip.NewWriter(&bf)

	dat, err := ioutil.ReadFile(fileName)
	if err != nil {
		log.Println(err)
		return err
	}
	w.Write(dat)
	w.Close()

	err = ioutil.WriteFile(filepath.Base(fileName)+".gz", bf.Bytes(), 0777)
	log.Println(err)
	return nil
}

```

### What did you expect to see?
csv file compressed successfully, can be opened successfully.

### What did you see instead?
when I use macOS archive utility to open, I got "Error 79 - Inappropriate file type or format"
if I use tar -xzvf , I got "tar: Missing type keyword in mtree specification"

this program works on Linux, but not on macOS M1
and I tried to compress a normal txt which contains "hello" inside, it works on macOS.

**Comment by mknyszek** [comment]
Generally speaking, I think the common tools found on most Linux boxes are very forgiving when it comes archives and compression formats. It may be that there's either something wrong with your code, or a bug in the library.

CC @mdempsky @dsnet

**Comment by seankhliao** [comment]
The program produces a gzipped file, not a tar archive.

**Comment by mknyszek** [comment]
D'oh. I should've looked more closely at the program. Thanks @seankhliao.

**Comment by seaguest** [comment]
Hi, it seems to be a problem with macOS archive utility.
gunzip can unzip the gz file on macOS.

**Comment by mdempsky** [comment]
If you want a file that the UNIX tar command can open, you need to use the `archive/tar` package (and then optionally *also* the `compress/gzip` package if you also want it gzip-compressed).

I don't know why/how GNU tar is able to handle bare gzip files that don't contain a tar archive, but that's news to me. I at least would not rely on that behavior.

Either way, this doesn't appear to be an issue with the Go standard library.

**Comment by seaguest** [comment]
@mdempsky 

sorry for my previous misleading information.
The program create csv file, then compress in gzip, then I use gunzip to decompress, they both work on macOS and linux.
however, the difference if when use archive utility to open the compressed gz on macOS, it gives "Error 79 - Inappropriate file type or format", while archive manager can open it on linux.

a little furthermore information, I use a hello.txt instead the csv file, then macOS can open it with archive utility, I guess this is due to some problem with macOS archive utility with csv gz file.
