### ISSUE TITLE
cmd/compile: "F is not a generic type" when F is a recursive generic interface

### ISSUE THREAD

**Issue by 4ad** [golang/go#47836]
On tip (e9e0d1ef70) with `-gcflags=-G=3`

Repro:
```
package p

type F[t F[t]] interface {}
```

Compiler rejects it with:

```
go build -gcflags=-G=3 j.go
# command-line-arguments
./j.go:3:10: F is not a generic type
```

However, it accepts this:

```
package p

type F[t F] interface {}
```

But that has other problems, see #47837.

**Comment by mknyszek** [comment]
CC @ianlancetaylor @griesemer

**Comment by tdakkota** [comment]
Seems like duplicate of https://github.com/golang/go/issues/47796

**Comment by 4ad** [comment]
Yep, seems like a dupe. In fact, I was trying to write that exact `Eq` when I found this.

**Comment by mknyszek** [comment]
Closing as duplicate of #47796.
