### ISSUE TITLE
net/http: allow customization of FileServer's directory HTML and styling

### ISSUE THREAD

**Issue by rbucker** [golang/go#47838]
https://github.com/golang/go/blob/e9e0d1ef704c4bba3927522be86937164a61100c/src/net/http/fs.go#L128-L165

The overarching purpose of the fileserver is to serve files in a safe way. But then it has this side effect of being able to generate a directory list. The directory list is a very basic PRE block with some A links. The code also sets the content-type. However, there is something missing.

- is the HTML that it generates simply the smallest code possible?
- is there a way to style that fragment either with a template or some CSS etc
- since it's just a PRE block should I wrap the handler in a handler and then write a header, then call the handler, then write the footer
- maybe there should be a callback instead of hardcoded
- maybe there should be a template feature

At the very least please update the documentation to set the intent.

**Comment by mknyszek** [comment]
If I understand correctly, the file server is meant as a very basic server. Very useful for one-offs and non-critical situations, but I don't think that this is ever intended to be a solution that is very customizable.

CC @neild

**Comment by mknyszek** [comment]
Actually, see #29945. This has been declined more than once. Closing.
