### ISSUE TITLE
x/pkgsite: Request removal of obsolete package paths

### ISSUE THREAD

**Issue by creachadair** [golang/go#47849]
The instructions at https://go.dev/about#removing-a-package suggest using module `retract` directives to remove package paths from the doc site. However, in this case I would like to remove a number of packages that I wrote, whose repositories have been moved (from Bitbucket to GitHub, as of 2019), and where the original repository has been deleted. I don't think I can do that via a `go.mod` directive.

If there is a different way to do this, can you please point me to the instructions? Otherwise, I would like to request removal of the following modules (with all their packages) from the doc site:

```
bitbucket.org/creachadair/bitstream
bitbucket.org/creachadair/blobstore
bitbucket.org/creachadair/cache
bitbucket.org/creachadair/cityhash
bitbucket.org/creachadair/ctrl
bitbucket.org/creachadair/culprit
bitbucket.org/creachadair/filedata
bitbucket.org/creachadair/fileinput
bitbucket.org/creachadair/flagstruct
bitbucket.org/creachadair/getpass
bitbucket.org/creachadair/goflags
bitbucket.org/creachadair/indexed
bitbucket.org/creachadair/ini
bitbucket.org/creachadair/keyfish
bitbucket.org/creachadair/misctools
bitbucket.org/creachadair/notifier
bitbucket.org/creachadair/pattern
bitbucket.org/creachadair/perm
bitbucket.org/creachadair/postscript
bitbucket.org/creachadair/prgfile
bitbucket.org/creachadair/pson
bitbucket.org/creachadair/scapegoat
bitbucket.org/creachadair/snapback
bitbucket.org/creachadair/stockopt
bitbucket.org/creachadair/tarsnap
bitbucket.org/creachadair/taskgroup
bitbucket.org/creachadair/vocab
bitbucket.org/creachadair/vql
```

**Comment by mknyszek** [comment]
CC @julieqiu @jba @jamalc

**Comment by julieqiu** [comment]
We can remove it.

**Comment by creachadair** [comment]
This appears to have been done, at least inasmuch as I no longer see these packages listed in searches. I'm not sure if I'm intended to close this, but from where I sit it appears resolved. Thank you!
