### ISSUE TITLE
spec: Type inference and functional options?

### ISSUE THREAD

**Issue by alecthomas** [golang/go#47868]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-e17439e087 Sat Aug 21 00:55:22 2021 +0000 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```go
package main

import "fmt"

type Option[T any] func(*Parser[T])

func Upgrade[T any]() Option[T] {
	return func(*Parser[T]) {}
}

func Description[T any](string) Option[T] {
	return func(*Parser[T]) {}
}

type Parser[T any] struct {}

func New[T any](options...Option[T]) *Parser[T] {
	p := &Parser[T]{}
	for _, o := range options {
		o(p)
	}
	return p
}

type SomeThing struct {}

func main() {
	p := New[SomeThing](Upgrade(), Description("A description"))
	// p := New[SomeThing](Upgrade[SomeThing](), Description[SomeThing]("A description"))
	fmt.Println("???", p)
}
```

This program fails with the following:

```
./main.go:24:29: cannot infer T (/Users/aat/Projects/goroot/foo/main.go:7:14) ([<nil>])
```

Which makes sense given the scope of type inference in the design. However, I thought I'd file this issue anyway, as functional options are very common in Go and this will make them quite tedious to use in conjunction with generic types:

```go
	p := New[SomeThing](Upgrade[SomeThing](), Description[SomeThing]("A description"))
```

The issue is phrased as a question in case there is some solution I'm not aware of, or it's just plain out of scope.

PS. Thanks for all the hard work getting it to this stage, it's looking super promising :)

**Comment by ianlancetaylor** [comment]
I think this is mentioned at https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#type-inference-for-generic-function-arguments .

**Comment by vikstrous2** [comment]
I worked around this limitation by introducing a config struct that the functional options act on. See https://github.com/vikstrous/dataloadgen/commit/a1d6c749385a89b0afe9953163c63bbecfebf91a#diff-f5110f13acbf40c384f0191d1967d0333e9d9a533def66f5e8b7518fdc80e226R10 for an example.

**Comment by alecthomas** [comment]
I'm okay to close this - this is a specific example of a more general problem described by the proposal and there are workarounds.
