### ISSUE TITLE
Go 1.17 installed from scoop has been detected as trojan by Windows Security

### ISSUE THREAD

**Issue by CornerSyrup** [golang/go#47874]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.17 windows/amd64
</pre>

### What did you do?

Scan block and remove

### What did you expect to see?

Not a threat

### What did you see instead?

Wanings

### Issue

Go 1.17 installed from scoop has been detected as trojan by Windows Security

![Screenshot (8)_LI](https://user-images.githubusercontent.com/87284079/130331677-cca627e5-bfd3-40a0-a21f-7fb754d29465.jpg)
![Screenshot (9)_LI](https://user-images.githubusercontent.com/87284079/130331679-1b8547dd-c91c-4280-8caf-70374214568a.jpg)
![Screenshot (11)_LI](https://user-images.githubusercontent.com/87284079/130331704-dac275f2-0708-4a47-9c1d-171701689538.jpg)

**Comment by fzipp** [comment]
See https://github.com/golang/go/issues/47807 /  https://golang.org/doc/faq#virus

**Comment by seankhliao** [comment]
https://golang.org/doc/faq#virus
