### ISSUE TITLE
cmd/compile: `<autogenerated>:1: cannot use .this (type *Map[int,struct{}]) as type Map[.shape.int,.shape.struct {}] in argument to Map[.shape.int,.shape.struct {}].Get`

### ISSUE THREAD

**Issue by dominikh** [golang/go#47877]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-6e50991d2a Sat Aug 21 18:23:58 2021 +0000 linux/amd64
</pre>

### What did you do?
```
package main

type Map[K comparable, V any] struct {
	m map[K]V
}

func NewMap[K comparable, V any]() Map[K, V] {
	return Map[K, V]{m: map[K]V{}}
}

func (m Map[K, V]) Get(key K) V {
	return m.m[key]
}

func main() {
	_ = NewMap[int, struct{}]()
}
```

### What did you see instead?
```
$ go build
# sandbox/sand2
<autogenerated>:1: cannot use .this (type *Map[int,struct{}]) as type Map[.shape.int,.shape.struct {}] in argument to Map[.shape.int,.shape.struct {}].Get
```

**Comment by danscales** [comment]
This is related to #47713 (similarly related to a discrepancy in the naming of types, which leads to problems with wrapper generation). I'll have a fix for both in the next day or so.
