### ISSUE TITLE
OpenBSD mips64 missing fcntl, ioctl elements

### ISSUE THREAD

**Issue by mcandre** [golang/go#47870]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/andrew/.cache/go-build"
GOENV="/home/andrew/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/andrew/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/andrew/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/andrew/.gvm/gos/go1.17"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/andrew/.gvm/gos/go1.17/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/andrew/go/src/github.com/mcandre/gus/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1711081068=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Source: https://github.com/mcandre/gus/tree/ff3398ce9c54491977a2ec0492444dc4b370c216

Trace:

```console
$ GOOS=openbsd GOARCH=mips64 go build cmd/gus/main.go
# golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/fcntl.go:26:42: undefined: Flock_t
vendor/golang.org/x/sys/unix/ioctl.go:14:47: undefined: Winsize
vendor/golang.org/x/sys/unix/ioctl.go:25:47: undefined: Termios
vendor/golang.org/x/sys/unix/sockcmsg_unix.go:53:18: undefined: Cmsghdr
vendor/golang.org/x/sys/unix/sockcmsg_unix.go:59:9: undefined: Cmsghdr
vendor/golang.org/x/sys/unix/syscall_openbsd.go:34:6: missing function body
vendor/golang.org/x/sys/unix/syscall_unix_gc.go:12:6: missing function body
vendor/golang.org/x/sys/unix/syscall_unix_gc.go:13:6: missing function body
vendor/golang.org/x/sys/unix/syscall_unix_gc.go:14:6: missing function body
vendor/golang.org/x/sys/unix/syscall_unix_gc.go:15:6: missing function body
vendor/golang.org/x/sys/unix/sockcmsg_unix.go:59:9: too many errors
```

### What did you expect to see?

The OpenBSD mips64 port successfully build.

### What did you see instead?

An error complaining that many fcntl and ioctl elements for OpenBSD mips64 are missing.

Note that other architectures for OpenBSD _do_ include these elements.

```console
$ GOOS=openbsd GOARCH=amd64 go build cmd/gus/main.go
$ ls main
main
```

**Comment by seankhliao** [comment]
Use a less out of date `golang.org/x/sys/unix`
