### ISSUE TITLE
types2: can't implement specific instances of generic mutually recursive interfaces

### ISSUE THREAD

**Issue by 4ad** [golang/go#47887]
On tip(6e50991d2a):

First, an example that works:

```
package p

type Fooer[t any] interface {
	foo(Barer[t])
}
type Barer[t any] interface {
	Fooer[t]
	bar(Fooer[t])
}

type Int int

func (n Int) foo(b Barer[Int]) { b.foo(n) }
func (n Int) bar(f Fooer[Int]) { f.foo(n) }
```

In this example, `Int` is both a `Fooer[int]` and a `Barer[int]`. Notice that in the `foo` method (which implements `Fooer[int]`), we know that `b` (a `Barer[int]`) is also a `Fooer[int]` (because we can call `foo` on it).

Now an example where this doesn't work:

```
package p

type Fooer[t any] interface {
	foo(Barer[t])
}
type Barer[t any] interface {
	bar(Bazer[t])
}
type Bazer[t any] interface {
	Fooer[t]
	baz(t)
}

type Int int

func (n Int) baz(int) {}
func (n Int) foo(b Barer[int]) { b.bar(n) }

```

Compiler rejects this code with:
```
go build k.go
# command-line-arguments
./k.go:17:40: incompatible type: cannot use n (variable of type Int) as Bazer[int] value
```

Go2go is [slighly more informative](https://go2goplay.golang.org/p/mOSRS-vXefm) as to why:
```
cannot use n (variable of type Int) as Bazer[int] value in argument to b.bar: wrong type for method foo (have func(b main.Barer[int]), want func(main.Barer[t]))
```

The compiler cannot unify the `t` with the `int`, but it should, just as in the first example. In particular, we try to claim that `Int` is a `Bazer[int]`. The first piece of evidence is the method `Int.baz(int)`. The second piece of evidence is that `Int` must also be a `Fooer[int]`. We prove this by implementing the requirement for `Fooer[int]`, namely that we have a `foo(Barer[int])` method. We do have such a method, it's `Int.foo(Barer[int])`. When proving something, we are allowed to use our induction hypothesis, namely we try to use the fact that a `Bazer[int]` is a `Fooer[int]`, but the compiler rejects this, although it shouldn't, because `Bazer[t]` being a `Fooer[t]` implies that `Bazer[int]` is a `Fooer[int]`.

This equivalent of this code code works in Rust as you would expect: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=295a0bbed80ab754c9a5b4a66651fae9.

**Comment by 4ad** [comment]
@ianlancetaylor @griesemer

**Comment by griesemer** [comment]
Possibly related to lazy method instantiation. Slightly simplified example:
```Go
package p

type F[t any] interface { f(G[t]) }
type G[t any] interface { g(H[t]) }
type H[t any] interface { F[t] }

type T struct{}
func (n T) f(b G[T]) { b.g(n) }
```

**Comment by griesemer** [comment]
Just for clarification, this is fixed in `go/types` and not yet in `types2` (and the compiler). But it will be ported shortly.

**Comment by griesemer** [comment]
This is now also fixed in the compiler.
