### ISSUE TITLE
Include cgo source files in go mod vendor

### ISSUE THREAD

**Issue by mcandre** [golang/go#47894]
It's really annoying how `go mod vendor` silently drops important native C/C++ source code files used by cgo.

Reminds me of how immature reflect's support for vendoring is.

At the very least, would be helpful for `go mod vendor` to warn the user when cgo files are excluded, so that the user will know why things are breaking. Instead of silently producing a borked vendor tree.

**Comment by seankhliao** [comment]
Duplicate of #26366
