### ISSUE TITLE
BUG division error

### ISSUE THREAD

**Issue by Dikman** [golang/go#47891]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes (1.17)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Dmitriy\AppData\Local\go-build
set GOENV=C:\Users\Dmitriy\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Dmitriy\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Dmitriy\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Programming\crocotta.go\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Dmitriy\AppData\Local\Temp\go-build2024659351=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I am run the next code:
<pre>
package main

import (
	"fmt"
)

func main() {
	var price float64 = 2.55
	var tickSize float64 = 0.001
	fmt.Println(price/tickSize) // <- must be 2550
}
</pre>

It also works in the playground :(
https://play.golang.org/p/MSUMySBjb4n

### What did you expect to see?

2550

### What did you see instead?

2549.9999999999995

**Comment by D1CED** [comment]
https://0.30000000000000004.com/

**Comment by randall77** [comment]
Neither 2.55 nor .001 can be represented exactly in floating point. This is expected.
