### ISSUE TITLE
cmd/go: Could not read from remote repository

### ISSUE THREAD

**Issue by AmirHussain93** [golang/go#47913]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.17

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary>$ go env</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/***/go/bin"
GOCACHE="/home/***/.cache/go-build"
GOENV="/home/***/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/***/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/***/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/****/go/src/github.*****.net/***-****/google/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build889135487=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I run the command "go build"

### What did you expect to see?
binary file for the code

### What did you see instead?

```
go: github.com/blang/semver@v3.5.1+incompatible: reading github.com/blang/semver/go.mod at revision v3.5.1: git ls-remote -q origin in /home/***/go/pkg/mod/cache/vcs/b6bc18656304150c7024c1930100743429fbf5f74599099c942888fecfe57378: exit status 128:
	ERROR: Repository not found.
	fatal: Could not read from remote repository.
	
	Please make sure you have the correct access rights
	and the repository exists.
go: downloading github.com/blang/semver v3.5.1+incompatible
go: downloading go.mongodb.org/mongo-driver v1.7.1
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/cenkalti/backoff/v4 v4.1.1
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/tidwall/gjson v1.8.1
go: downloading google.golang.org/api v0.50.0
go: downloading github.com/mohae/deepcopy v0.0.0-20170929034955-c48cc78d4826
go: github.com/blang/semver@v3.5.1+incompatible: reading github.com/blang/semver/go.mod at revision v3.5.1: git ls-remote -q origin in /home/amir/go/pkg/mod/cache/vcs/b6bc18656304150c7024c1930100743429fbf5f74599099c942888fecfe57378: exit status 128:
	ERROR: Repository not found.
	fatal: Could not read from remote repository.
	
	Please make sure you have the correct access rights
	and the repository exists.
```

**Comment by seankhliao** [comment]
does `git clone https://github.com/blang/semver` work for you?
