### ISSUE TITLE
spec: specify behavior of (*[N]T)(nil)

### ISSUE THREAD

**Issue by cuonglm** [golang/go#47917]
Reading the [slice to array pointer conversion](https://golang.org/ref/spec#Conversions_from_slice_to_array_pointer) in spec, I can't find any places that describe the behavior of `(*[N]T)(nil)`.

The current behavior seems to return `nil` in call cases:

```
package main

import "fmt"

func main() {
	fmt.Println((*[0]int)(nil))
	fmt.Println((*[1]int)(nil))
	fmt.Println((*[1000]int)(nil))
}
```

But that contradict with the spec:

> If the length of the slice is less than the length of the array, a run-time panic occurs.

For `var s []int`, thing works correctly:

```
var s []int
_ = (*[0]int)(s). // ok
_ = (*[1]int)(s)  // panic
```

cc @griesemer @mdempsky @josharian

**Comment by randall77** [comment]
```
	fmt.Println((*[0]int)(nil))
	fmt.Println((*[1]int)(nil))
	fmt.Println((*[1000]int)(nil))
```
These are not slice to array pointer, they are nil pointer to array pointer.

**Comment by cuonglm** [comment]
@randall77 Ah right, thanks, my bad.
