### ISSUE TITLE
go/types: make instantiation concurrency-safe

### ISSUE THREAD

**Issue by findleyr** [golang/go#47910]
Type instantiation is currently not concurrency-safe in go/types:
- instances are expanded lazily.
- instantiation hashing uses a package-local instanceHashing variable

See also #47729: the only reason this hasn't triggered test failures due to data races is that we lack test coverage for concurrent use in go/types, and x/tools is not yet exercising type instantiation.

CC @griesemer

**Comment by timothy-king** [comment]
This may be a concern for x/tools/go/ssa. Building for each package is done in its own go routine. Each will likely be instantiating types.
