### ISSUE TITLE
cmd/compile: `//go:nointerface` mishandled for promoted methods with -G=3

### ISSUE THREAD

**Issue by mdempsky** [golang/go#47928]
The test program below has type T that embeds type U, which has a go:nointerface method M. When compiled with GOEXPERIMENT=fieldtrack, the type assertion should fail. It correctly fails with -G=0 and GOEXPERIMENT=fieldtrack,unified; but it incorrectly succeeds with -G=3.

```
package main

func main() {
	var i interface{} = new(T)
	if _, ok := i.(interface{ Bad() }); ok {
		panic("FAIL")
	}
}

type T struct{ U }

type U struct{}

//go:nointerface
func (*U) Bad() {}
```

Notably, the test passes if `func main` is moved after the `Bad` method. Presumably the issue is that we don't call `irgen.funcDecl` (which currently handles setting `types.Field.Nointerface`) until after `types.ResumeCheckSize`. Probably we need to change `irgen.typeDecl` to set `types.Field.Nointerface` instead, so that it's already set before any method promotion happens.

Alternatively, maybe we can just get rid of Field.Nointerface in favor of checking Func.Pragma directly. If this works, it seems preferable.

/cc @cuonglm @danscales @randall77

**Comment by cuonglm** [comment]
@mdempsky Seems `-G=3` correctly panics, but `-G=0` and unified IR run successfully.
