### ISSUE TITLE
x/mobile: binding Gosseract fails

### ISSUE THREAD

**Issue by dpanic** [golang/go#47927]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.17 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/dpanic/go/bin"
GOCACHE="/home/dpanic/.cache/go-build"
GOENV="/home/dpanic/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dpanic/go/pkg/mod"
GOOS="linux"
GOPATH="/home/dpanic/go"
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1397584906=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I am trying to bind Go code for Android, code has CGO bindings for Tesseract.
I have all dependencies installed for tesseract.

I am trying to archive this with gomobile bind but I get following error:
```
$ gomobile bind  
gomobile: go build -buildmode=c-shared -o=/tmp/gomobile-work-1045436346/android/src/main/jniLibs/armeabi-v7a/libgojni.so ./gobind failed: exit status 2
# github.com/otiai10/gosseract
tessbridge.cpp:5:10: fatal error: 'tesseract/baseapi.h' file not found
```

### What did you see instead?
```tessbridge.cpp:5:10: fatal error: 'tesseract/baseapi.h' file not found```

**Comment by seankhliao** [comment]
This is an issue with your install of tesseract, see their issue tracker

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
