### ISSUE TITLE
fmt: get wrong data when using "%.30f" in fmt.Sprintf

### ISSUE THREAD

**Issue by xiaoyang-chen** [golang/go#47931]
### What version of Go are you using (`go version`)?

<pre>
$ go version
</pre>
go playground.  and. go version go1.16.6 darwin/amd64
### Does this issue reproduce with the latest release?
unknown,  reproduce in go playground and  go version go1.16.6 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
</pre></details>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xxx/Library/Caches/go-build"
GOENV="/Users/xxx/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xxx/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xxx/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct,https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.6/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/v8/lqjftghd06x4bdc946hl2gsc0000gn/T/go-build4061609802=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

fmt.Println(fmt.Sprintf("%.30f", 5.400000*float64(0.400000)))
https://play.golang.org/p/o4ARzVQfsw_0
### What did you expect to see?

get.  2.160000000000000000000000000000

### What did you see instead?
get  2.160000000000000142108547152020

**Comment by seankhliao** [comment]
Floating points are limited in accuracy and cannot represent all numbers
