### ISSUE TITLE
x/website: Managing Go installations is out of date

### ISSUE THREAD

**Issue by lu4p** [golang/go#47939]
With go 1.17 `go get` doesn't install binaries anymore (see https://golang.org/doc/go-get-install-deprecation)

The documentation at https://golang.org/doc/manage-install is out of date it should use the new go install syntax:
`go install golang.org/dl/go1.10.7@latest`

instead of the current `go get golang.org/dl/go1.10.7` which errors:
```
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

**Comment by fzipp** [comment]
Other instances of deprecated `go get` usage on the website: https://github.com/golang/go/issues/43684#issuecomment-815900010
