### ISSUE TITLE
x/tools/go/analysis/passes/nilness: false negative with pointers and type assertions

### ISSUE THREAD

**Issue by ainar-g** [golang/go#47938]
Currently, as of `golang.org/x/tools v0.1.6-0.20210820212750-d4cc65f0b2ff` and `go1.17`, `nilness` doesn't mark the following code as invalid despite `tt` being provably nil:

```go
package main

import "fmt"

type T struct {
	a int
}

func main() {
	n := 0
	var v interface{} = &n

	tt, ok := v.(*T)
	if ok {
		return
	}

	fmt.Println(tt.a)
}
```

If `ok` is false then `tt` is nil, since that is the default value for pointers.

Playground: https://play.golang.org/p/0ni1nXpLBFK.

**Comment by timothy-king** [comment]
The original example one could plausible infer that `ok` is always false as the set of types of `v` is `{*int}`. Inferring the set of types of `v` is probably not a good road to go down. Here is a simpler example that illustrates what could be supported:
```
func foo(i interface{}) {
	tt, ok := i.(*int)
	if ok {
		return
	}
	_ = *tt
}
```

Handling just the control flow looks feasible for easy cases. It could use roughly the same trick as [here](https://cs.opensource.google/go/x/tools/+/refs/tags/v0.1.5:go/analysis/passes/nilness/nilness.go;l=193-199):
```
				for _, d := range b.Dominees() {
					...
					if len(d.Preds) == 1 {
						if d == tsucc {
```
Brainstorming:
The checker would look for `if c then else` instructions where `(tt, c)` are the `ssa.Extract`s for indices 0 and 1 of an `*ssa.TypeAssert` instruction and the underlying type of `tt` is a pointer (/map/slice/interface) type. When the above trick is present on the else branch, one would strengthen the else branch with `tt` being nil. The true branch gains no information.

**Comment by ainar-g** [comment]
Yes, my example was both over- and undersimplified.  In the original code the type set isn't as clear.  Your example illustrates the problem better, thanks!
