### ISSUE TITLE
cmd/compile: remove assert failed in types2

### ISSUE THREAD

**Issue by oiooj** [golang/go#47947]
We need start to clean `assert` func in types2, maybe we can use `cmd/compile/internal/base` package to report accurate errors. see: #47883

/cc @mdempsky

**Comment by mdempsky** [comment]
types2 is meant to stay similar to go/types (i.e., decoupled from the rest of the compiler), and I'm not aware of any intent to remove the `assert` function. I'm not sure there's anything to coordinate here via an issue.

/cc @griesemer

**Comment by griesemer** [comment]
The `assert` calls in `types2` are not there for error handling; they are there to express internal invariants that are expected to be true, even in the presence of errors in the type-checked code. Assertions that fail point to a bug in the code that needs to be fixed; similar to how an "index out of bounds" error points to an error in the code indexing the array or slice.

Closing as there is nothing to do here.
