### ISSUE TITLE
syscall: Statfs_t on OpenBSD with f_

### ISSUE THREAD

**Issue by miraculli** [golang/go#47958]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 openbsd/amd64
</pre>

### Does this issue reproduce with the latest release?
Go 1.17 is not yet available on OpenBSD

### What operating system and processor architecture are you using (`go env`)?
openbsd/amd64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/.../.cache/go-build"
GOENV="/home/.../.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="openbsd"
GOINSECURE=""
GOMODCACHE="/home/.../go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="openbsd"
GOPATH="/home/.../go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/openbsd_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build521513831=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
This is related to https://github.com/nats-io/nats-server/issues/2445 
I want to build [nats-server](https://github.com/nats-io/nats-server) on openbsd but it fails due to undefined fields in syscall.Statfs_t on OpenBSD.

I tracked it somewhat down and can tell that this syscalls to `Statfs` work fine when calling with an "F_" prefix:

```
var fs syscall.Statfs_t
if err := syscall.Statfs(path, &fs); err == nil {
    fmt.Println(fs.F_bavail)
    fmt.Println(fs.F_bsize)
}
```

The field definition on OpenBSD can be found here: http://man.openbsd.org/statfs
But they look the same  (with that 'f_' prefix) on Linux and Darwin where nats-server builds fine.

### What did you expect to see?

This should compile on OpenBSD
```
var fs syscall.Statfs_t
if err := syscall.Statfs(path, &fs); err == nil {
    fmt.Println(fs.Bavail)
    fmt.Println(fs.Bsize)
}
```

### What did you see instead?

This compiles and runs on OpenBSD fine but is different from other OSes

```
var fs syscall.Statfs_t
if err := syscall.Statfs(path, &fs); err == nil {
	fmt.Println(fs.F_bavail)
	fmt.Println(fs.F_bsize)
}

```

**Comment by seankhliao** [comment]
`syscall` is frozen, `golang.org/x/sys/unix` had the right definitions https://cs.opensource.google/go/x/sys/+/master:unix/ztypes_openbsd_amd64.go;l=87?q=Bavail%20&ss=go%2Fx%2Fsys:unix%2F&start=31
