### ISSUE TITLE
Go mod does not support more than three path levels

### ISSUE THREAD

**Issue by niceSong** [golang/go#47951]
Use mod, If gitlab url more than three levels，the version will be error,  Content after the third level will be used as version number。
In go.mod:
<pre>
	gitlab.ebupt.com/5gc/5gc-cd/go-cicada v0.0.1
</pre>
will be error:
<pre>
go: gitlab.ebupt.com/5gc/5gc-cd/go-cicada@v0.0.1: reading gitlab.ebupt.com/5gc/5gc-cd/go-cicada/go-cicada/go.mod at revision go-cicada/v0.0.1: unknown revision go-cicada/v0.0.1
</pre>
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.16.5

</pre>

### Does this issue reproduce with the latest release?
uncertain

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tangyuyao/Library/Caches/go-build"
GOENV="/Users/tangyuyao/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/tangyuyao/go/pkg/mod"
GONOPROXY="gitlab.ebupt.com"
GONOSUMDB="gitlab.ebupt.com"
GOOS="darwin"
GOPATH="/Users/tangyuyao/go"
GOPRIVATE="gitlab.ebupt.com"
GOPROXY="direct"
GOROOT="/usr/local/Cellar/go/1.16.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.5/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/tangyuyao/work/EB/eb5gc/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9h/x_rfbpq50ng165kjrx2mm9r80000gp/T/go-build374665244=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Use gitlab, and path level is to many.

### What did you expect to see?
No matter how many levels of paths are used, dependency can be install on correctly

### What did you see instead?
Gitlab url more than three levels，the version will be error,

**Comment by seankhliao** [comment]
That is the lack due to a lack of authentication with gitlab

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
