### ISSUE TITLE
x/website: post https://go.dev/blog/tidy-web contains a broken link

### ISSUE THREAD

**Issue by ilikegolang** [golang/go#47975]
### What is the URL of the page with the issue?
https://go.dev/blog/tidy-web

### What is your user agent?
I browsed with Brave on Windows 10. The user agent string is the following
<pre>
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
</pre>

### What did you do?
Followed the first link in the first sentence of post https://go.dev/blog/tidy-web

### What did you expect to see?
A new post

### What did you see instead?
A page with an error.
Manually changing the URL from https://go.dev/blog/blog/go.dev to https://go.dev/blog/go.dev makes the linked post appear

Before manually editing (URL https://go.dev/blog/blog/go.dev)

![2021-08-26 11_06_18-- go dev - Brave](https://user-images.githubusercontent.com/69702053/130935484-bed1ab77-9501-4ed9-aa66-3f3780089c93.png)

After manually editing (URL https://go.dev/blog/go.dev)

![2021-08-26 11_06_18-- go dev - Brave_2](https://user-images.githubusercontent.com/69702053/130937699-8f1b9889-e1cb-4fb8-9f66-1995167b2e53.png)

**Comment by ilikegolang** [comment]
Hi all,
I'm sorry but as far as I can see the issue is still present.
Thanks.

**Comment by ALTree** [comment]
[CL 347912](https://go-review.googlesource.com/c/website/+/347912/), which should fix this, hasn't been merged yet.

**Comment by ALTree** [comment]
Fixed by the recent website re-deployment.
