### ISSUE TITLE
types2, go/types: (constraint) type inference for parameterized types is not implemented

### ISSUE THREAD

**Issue by griesemer** [golang/go#47990]
Reminder issue.

Per the evolving spec ([CL 294469](https://golang.org/cl/294469)), type inference is applied uniformly to type and function instantiations. For type instantiations, only constraint type inference will kick in, if any.

cc: @findleyr

**Comment by toothrot** [comment]
Reminding the reminder. Checking in on this issue as it's labeled a release blocker for Go 1.18. Is there any update?
