### ISSUE TITLE
go/types,cmd/compile/internal/types2: inconsistent handling of `len` on pointer-to-array type parameters

### ISSUE THREAD

**Issue by mdempsky** [golang/go#47991]
This package currently fails to typecheck in `H`:

```
package p

func F[Ptr interface{ ~*Elem }, Elem interface { [1]int }](p Ptr) int {
  return len(p) // ok: types2 allows implicit dereference here
}

func G[Ptr interface{ ~*Elem }, Elem interface { [1]int | [2]int }](p Ptr) int {
  return len(*p) // ok(?): types2 allows explicit dereference and length of Elem
}

func H[Ptr interface{ ~*Elem }, Elem interface { [1]int | [2]int }](p Ptr) int {
  return len(p) // FAIL(?): types2 says len(p) is not allowed
}
```

It's unclear to me the correct behavior here, but the current behavior at least seems inconsistent to me.

/cc @findleyr

**Comment by mdempsky** [comment]
> len(p) is permitted if p is a type parameter and len(t) is permitted for all types in the type set of p (additional rule)

I think this rule sounds reasonable; but my interpretation of it would be that F and H should both be valid, because Ptr's type set only contains pointer-to-array types and `len` is valid on all of those. But above you indicated those are still rejected?

Am I missing something? If not, can you elaborate how you interpret that rule to disallow F and H?

**Comment by griesemer** [comment]
I'm taking the rules fairly literally:
`len(p)` is a pointer to a type parameter (so not an array, nor a pointer to an array), hence `F` and `H` won't be valid.

Type-set computation doesn't extend past the boundaries of an interface. Doing that would have all kinds of implications that we've not explored at all. So the type set of `Ptr` is the set of all types whose underlying type is `*Elem`, and `Elem` is not an array, it's a type parameter.

**Comment by mdempsky** [comment]
Okay, I see. Thanks for elaborating.

I think rejecting both F and H is consistent and an improvement over the original behavior. I think it's the more conservative option too, so it makes sense to go with it at least for Go 1.18.

I'm inclined to think type-set computation *should* extend recursively, to be analogous to how defined types work; e.g., `len` is allowed on defined-pointer-to-defined-array types. But I agree we should think out the implications of that first before committing to it so we don't paint ourselves into a corner.

**Comment by griesemer** [comment]
Since the implementation of `len` (and related functions) has been updated to be consistent with these rules, I am going to consider this now "fixed". We can reconsider in the future.
