### ISSUE TITLE
x/website/go.dev: /learn page does not suggest installing the latest version and also suitable for my operating system

### ISSUE THREAD

**Issue by sina-devel** [golang/go#48007]
### What is the URL of the page with the issue?
 Why https://go.dev/learn does not suggest installing the latest version and also suitable for my operating system ?
 
 
### What is your user agent?
 Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0
 
 
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/61763643/131115992-ed671c0d-d942-48d8-9740-087f32685816.png)
 
 
### What did you expect to see?
 Go v1.17 installation suggestion for linux
 
 
### What did you see instead?
Go v1.15 installation suggestion for windows

**Comment by sina-devel** [comment]
> It's likely Go 1.15 was shown because a frontend fetch failed, or JavaScript execution is disabled. The relevant code is:
> 
> ```js
> async function getLatestVersion() {
>     let version = 'go1.15'; // fallback version if fetch fails
> ```

Thanks, I think this is because golang.org has been banned by Google for Iran, but by changing the ip, it only shows the latest version correctly and not the operating system

**Comment by seankhliao** [comment]
I believe this has been updated now.
The big button points to `/dl/` while the fallback has been updated to 1.17
