### ISSUE TITLE
cmd/compile: combine xor and rotate right into shifted EOR on arm64

### ISSUE THREAD

**Issue by ericlagergren** [golang/go#48002]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN="/Users/eric/gopath/bin"
GOCACHE="/Users/eric/Library/Caches/go-build"
GOENV="/Users/eric/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/eric/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/eric/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2f/2_yz21b92h94_pvr2m00gzh80000gn/T/go-build15658485=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://play.golang.org/p/LNnAPEjrB1u

### What did you expect to see?

The compiler generate EOR with a shifted register. E.g., turning

```
s.x3 = t3 ^ rotr(t3, 10) ^ rotr(t3, 17)
```

into (ignoring any typoed register names)

```
eor x3, x3, x2, ror #10
eor x2, x3, x2 ror #17
```

### What did you see instead?

```
mov	x3, #10
ror	x3, x2, x3
eor	x3, x3, x2
mov	x4, #17
ror	x2, x2, x4
eor	x2, x2, x3
```

**Comment by RuinanSun** [comment]
I will work with my teammates on this issue, thanks for reporting that.

**Comment by greatroar** [comment]
This is labeled arch-arm, but it's about arm64.
