### ISSUE TITLE
doc: make program snippets playable

### ISSUE THREAD

**Issue by minux** [golang/go#4801]
<pre>extend the -play feature from examples to {{code}} blocks.</pre>

**Comment by jfrazelle** [comment]
I think this can be closed

**Comment by jfrazelle** [comment]
Examples are playable?

**Comment by bradfitz** [comment]
@adg, @minux?

**Comment by jfrazelle** [comment]
err maybe `{{code}}` blocks are different :/

**Comment by adg** [comment]
I believe this is referring to the code includes in things like the 'writing web applications' codelab. I don't think this is the direction we want to take that stuff.
