### ISSUE TITLE
gerrit: implement CL auto-submit

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#48021]
(similar to #12482, but this issue is intended to track the work of actually implementing and deploying this functionality)

Authors should be able to add a "Auto-Submit" label to CLs, such that once all submission requirements are met the CL is automatically submitted. The usage "Auto-Submit" label should be restricted to the existing 'approvers' Gerrit group.

The basic conditions for triggering auto-submit should be (the first two of these can be boiled down to 'submittable' according to Gerrit):
* Trusted
* Code-Review+2
* TryBot-Result+1
* No unresolved comments

The one main open question is what restrictions should be in place around 'unreviewed' changes. Currently once a reviewer has +2'd a CL, if the author is in 'approvers' they can make changes to the CL before it is submitted (this is a common pattern, as reviewers will often +2 with small comments that the author should address before submitting). If we maintain the "Auto-Submit" label across patch sets, this behavior would essentially be maintained when using auto-submit functionality (since any comments would still need to be resolved, and a new TryBot-Result+1 would be required), although reviewers may be slightly less vigilante about looking at unreviewed changes which are submitted. 

Since the author would still need to re-label with "Run-TryBot" after pushing a new patch set, it seems reasonable though to explicitly require them to also re-label with "Auto-Submit". This wouldn't really provide any extra security, but would make the author explicitly say they want their new patch set auto-submitted. Another approach would be to require there be no new patch set between the last Code-Review+2 and the auto-submit being triggered. This would explicitly require the reviewer to approve any changes since their last review, but doesn't necessarily add any additional security, since the author would still be able to manually submit their patch, and seems likely to just reduce the value of this feature.

I'm in favor of not implementing any additional restrictions, and simply saying if the change has Code-Review+2 and there are no unresolved comments (and all other submittability(?) requirements are satisfied), allowing follow-up unreviewed changes to be submitted. This would maintain the status-quo, relying on the assumption that members of the 'approvers' group should be generally trusted not to submit major unreviewed changes and that reviewers should be aware of what unreviewed changes were submitted (i.e. that there weren't changes outside of what they requested in the submitted CL).

There are two major components of this change:
* Adding the auto-submit functionality to x/build/cmd/gopherbot
* Adding the "Auto-Submit" label to the gerrit config

cc @golang/release @golang/security

**Comment by dmitshur** [comment]
I performed a controlled test run on https://go-review.googlesource.com/c/build/+/383174, watching it closely. There weren't any unexpected findings, everything worked as intended.

Here's a log of events with some additional logging/information about decisions gopherbot took:

```
1. Send a CL with Auto-Submit+1, CL should not show up during dry-run

	>>> bailing because Auto-Submit (approved by user 6005) and TryBot-Result (<nil>) aren't approved

2. Run TryBots so patchset has TryBot-Result+1, CL should not show up during dry-run

	>>> bailing because !changeInfo.Submittable

3. Add Code-Review+2 (but not both Trust+1), CL should not show up during dry-run

	>>> bailing because !changeInfo.Submittable

4. Add second Trust+1, CL should show up during dry-run

	2022/02/04 12:24:07 [dry-run] would've submitted CL https://golang.org/cl/383174 ...

5. Add an unresolved comment, CL should not show up during dry-run

	>>> bailing because thread is unresolved 27f316d4_6ad5c7c7

6. Resolve comment, CL should show up during dry-run

	2022/02/04 12:26:44 [dry-run] would've submitted CL https://golang.org/cl/383174 ...

7. Push new patchset, CL should not show up during dry-run

	this cleared both TryBot-Result and Auto-Submit votes

	>>> bailing because Auto-Submit (<nil>) and TryBot-Result (<nil>) aren't approved

8. Re-add Auto-Submit+1, CL should not show up during dry-run

	>>> bailing because Auto-Submit (approved by user 6005) and TryBot-Result (<nil>) aren't approved

9. Run TryBots so patchset has TryBot-Result+1, CL should show up during dry-run

	2022/02/04 12:39:01 [dry-run] would've submitted CL https://golang.org/cl/383174 ...

10. Run gopherbot without --dry-run, CL should be submitted

	2022/02/04 12:41:40 submitting CL https://golang.org/cl/383174 ...
```

**Comment by rolandshoemaker** [comment]
We've basically implemented everything described here, any follow-up work can now have it's own issue. 🎉
