### ISSUE TITLE
x/build: upgrade the IOS version on host-ios-arm64-corellium-ios

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#48025]
We've recently discovered that the builder used to test IOS development is running an older version of IOS. Would it be possible to update the IOS version we test against in `host-ios-arm64-corellium-ios` to IOS 14? @znly

@golang/release 
/cc @aclements

**Comment by eliasnaur** [comment]
According to the Corellium dashboard they all run iOS 14.6. They had to be rebooted though.

**Comment by cherrymui** [comment]
Related: the builder seems running low on disk spaces https://build.golang.org/log/31adad851a2e2219de9e13aa83b2027a7ae0a379 `no space left on device`.

**Comment by eliasnaur** [comment]
Yeah, I noticed that as well. I've removed the leftover goroots I had lying around for stresstesting the SIGILL issue.

**Comment by cagedmantis** [comment]
Thank you for the update @eliasnaur. Please feel free to comment on the issue if you feel it's been closed in error.
