### ISSUE TITLE
cmd/go: improve diagnostic for module graph errors from unpruned transitive dependencies in 'go get'

### ISSUE THREAD

**Issue by bcmills** [golang/go#48024]
In the Go 1.17 release I left a TODO for a better error in a fairly obscure case (an error loading the versions found in the upgraded module graph, when that path arises from a transitive dependency of a `go 1.16` or earlier module).

The error today should indicate which module produced the error, but ideally the error should also log the path to that module.

Such errors should become more rare over time as modules upgrade to `go 1.17` and higher. However, it would still be nice to do the TODO for the better diagnostic at some point.

https://github.com/golang/go/blob/acdea4f9f792339ee27fb1f67539a7ca2e3af99a/src/cmd/go/internal/modload/edit.go#L255-L260

**Comment by quantonganh** [comment]
345392 had been merged, this can be closed?

**Comment by bcmills** [comment]
I completely overhauled `src/cmd/go/internal/modload/edit.go` in https://go.dev/cl/471595.

The conflicting path is now logged (in `src/cmd/go/internal/modget/get.go`) if the `-v` flag is set. I think we can consider this issue to be fixed. Thanks for following up!
