### ISSUE TITLE
runtime: Sycall Call function modifies value of procedure argument which is underlyingly immutable

### ISSUE THREAD

**Issue by cristeigabriel** [golang/go#48035]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\malloc\AppData\Local\go-build
set GOENV=C:\Users\malloc\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\malloc\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\malloc\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\malloc\Desktop\gohack\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\malloc\AppData\Local\Temp\go-build1453493053=/tmp/go-build -gno-record-gcc-switches
GOROOT/bin/go version: go version go1.17 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.17
</pre></details>

### What did you do?

In the rawest form, this is what I'm doing. I don't know if there's any Go playground servers which run Windows, so I haven't tried reproducing this issue in it, yet.
```
	fmt.Printf("%p\n", (*(**Player)(context.playerPtr)))
	fmt.Printf("%p\n", (*(**Player)(context.playerPtr)))
	a := (*(**Player)(context.playerPtr)).getHealth()
	fmt.Printf("%d %p\n", a, (*(**Player)(context.playerPtr)))
```

getHealth does the following:
```
func (player *Player) get(size uint32, ptrdiff uintptr) unsafe.Pointer {
	return Instance.csgo.readMemory(size, uintptr(unsafe.Pointer(player))+ptrdiff)
}

func (player *Player) getHealth() int {
	return *(*int)(player.get(4, 0x100))
}
```

readMemory does the following:
```
gReadProcessMemory  = gKernel32.MustFindProc("ReadProcessMemory")

func (process *Process) readMemory(size uint32, at uintptr) unsafe.Pointer {
	var address byte
	addressPtr := unsafe.Pointer(&address)

	state, _, _ := gReadProcessMemory.Call(uintptr(process.handle), at, uintptr(addressPtr), uintptr(size), 0)

	if state == 0 {
		panic(fmt.Sprintf("Epicly failed: RPM at %x is SUS!", at))
		return nil
	}

	return addressPtr
}
```
[ReadProcessMemory](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-readprocessmemory) has the following as the first 2 arguments: a process handle, a `const void*`.

I'm respectively passing a base address which is the result of turning a pointer into an uintptr, then combining that value with 0x100 in this scenario.

I don't see how WINAPI could be at fault modifying underlying content even though it'd have the 'permission' to overwrite what we're pointing at. Even then, though, I'm passing a result of an operation, not the raw pointer itself, which is the one being modified. I think it's the result of a direct semantic in Go?

### What did you expect to see?
address, same address, health (an integer that goes from 0 to 100), same address as the former two

### What did you see instead?
address, same address, (correct) health, new address which is consistent on all runs (0x6480) (changes according to the ptrdiff passed in get(...), but stays consistent with the same ptrdiff.)

For more context: I have more RPM calls within my software, and they don't cause any side effect as this procedure. This is the only, unique case where this happens. In the aforementioned, I also have the scenario where I take a pointer, convert it to an uintptr, then use that value for combination, then read at the newly produced address.

**Comment by randall77** [comment]
I find it hard to understand what this code is doing, or is intended to do. It would really help to have a full program we could run ourselves. Same for #48041 .

Your use of `unsafe` looks problematic. Please make sure you read and adhere to the restrictions described at https://pkg.go.dev/unsafe#Pointer
