### ISSUE TITLE
doc: document Boring Crypto release schedule

### ISSUE THREAD

**Issue by jawnsy** [golang/go#48043]
This is more of a question than an issue, though it would be helpful to document the release schedule for Go + Boring Crypto (which I'll call goboring) somewhere. Sorry if this documentation exists but I missed it! pointers to existing documentation would be much appreciated. If there's no documentation and a doc PR would be welcome, I'd be happy to open one given some guidance!

[Go 1.17 was released last week](https://go.dev/blog/go1.17) (Aug 16th), but it appears the corresponding build of goboring is not available yet (checking the [Google Cloud Storage bucket](https://storage.googleapis.com/go-boringcrypto) as well as [Docker Hub](https://hub.docker.com/r/goboring/golang/tags)). Are these releases typically expected to track the main Go release closely, or do they lag for some period of time?

Thanks so much for producing goboring :heart: 

cc @katiehockman @FiloSottile who I gather usually maintain this build

**Comment by ALTree** [comment]
It's also possible that there are no guarantees, and that's why the boringcrypto release process is not documented.

Go1.16 was released on Feb 16th, but[ the change adding the corresponding boringcrypto release](https://go-review.googlesource.com/c/go/+/296989) was merged on March 10th. So it appears that the boringcrypto releases can lag behind.

**Comment by jawnsy** [comment]
For anyone needing a new version, we found this image tag to be helpful: `us-docker.pkg.dev/google.com/api-project-999119582588/go-boringcrypto/golang:1.17.2b7` - I have no idea how well-supported this is, though

**Comment by seankhliao** [comment]
boringcrypto is now behind GOEXPERIMENT, and I believe that it won't see any further work with #69536 being the future direction.
