### ISSUE TITLE
SIGILL: illegal instruction use the golang 1.17 on CentOS 

### ISSUE THREAD

**Issue by kaiiak** [golang/go#48058]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, this is last version.

### What operating system and processor architecture are you using (`go env`)?
CentOS Linux release 7.7.1908 (Core)
Linux XXXXXXX 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="XXXXXXXXX"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="XXXXXXXXX"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2173003600=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

 Run a Micro Server on Linux

```
SIGILL: illegal instruction
PC=0x5ce7c1 m=3 sigcode=2
instruction bytes: 0xdb 0xff 0xff 0xff 0x45 0xf 0x57 0xff 0x64 0x4c 0x8b 0x34 0x25 0xf8 0xff 0xff

rax    0x0
rbx    0xed8be9311
rcx    0x4
rdx    0x0
rdi    0xc0015fe500
rsi    0xc0003cca80
rbp    0x0
rsp    0xc0012b9fe0
r8     0x3
r9     0x107eca1
r10    0x1c0de
r11    0x1a94fa6bb21864
r12    0xc0012b9a48
r13    0x0
r14    0xc00137fd40
r15    0x7f4b40574ac8
rip    0x5ce7c1
rflags 0x10206
cs     0x33
fs     0x0
gs     0x0

```

**Comment by randall77** [comment]
Looks like this jumped into non-code somehow - those instruction bytes are junk.
Is this reproducible? Can you show us your code? Without a way to reproduce, there's not much we can do.
The pc, 0x5ce7c1, is that in a sensible range in your binary? In the text section? If you disassemble your binary, what is at that pc?
