### ISSUE TITLE
crypto/sha256: escape analysis of digest.Sum disagrees on different architectures

### ISSUE THREAD

**Issue by dsnet** [golang/go#48055]
It seems to me that the result of escape analysis should be independent of the exact target architecture. This may be an assumption that is totally unfounded as my understanding of the escape analyzer is limited.

To reproduce, try building `crypto/sha256` on various architectures
```
for X in 386 amd64 amd64p32 arm armbe arm64 arm64be ppc64 ppc64le mips mipsle mips64 mips64le mips64p32 mips64p32le ppc riscv riscv64 s390 s390x sparc sparc64 wasm; do
    echo $X
    GOARCH=$X ../../../bin/go build -gcflags="-m" 2>&1 | egrep "d0|tmp"
   echo
done
```

The following architectures believe that [`d0`](https://github.com/golang/go/blob/56c3856d529d72e280ad6b185f7927657de86c37/src/crypto/sha256/sha256.go#L209) and [`tmp`](https://github.com/golang/go/blob/56c3856d529d72e280ad6b185f7927657de86c37/src/crypto/sha256/sha256.go#L220) escape to the heap:
```
arm
ppc64
mips
mipsle
mips64
mips64le
riscv64
```
while the following do not:
```
386
amd64
amd64p32
armbe
arm64
arm64be
ppc64le
mips64p32
mips64p32le
ppc
riscv
s390
s390x
sparc
sparc64
wasm
```

Using `GOARCH=arm` as an example, `-gcflags="-m=100` prints the relevant information:
```
./sha256.go:209:5:[1] (*digest).Sum stmt: d0 := *d
./sha256.go:209:2:[1] (*digest).Sum stmt: var d0 digest
./sha256.go:210:7:[1] (*digest).Sum stmt: hash := (*digest).checkSum(d0)
./sha256.go:210:2:[1] (*digest).Sum stmt: var hash [32]byte
./sha256.go:209:2: d0 escapes to heap:
./sha256.go:209:2:   flow: {heap} = &d0:
./sha256.go:209:2:     from d0 (address-of) at ./sha256.go:210:12
./sha256.go:209:2:     from (*digest).checkSum(d0) (call parameter) at ./sha256.go:210:21
./sha256.go:211:2:[1] (*digest).Sum stmt: if d0.is224 { return append(in, hash[:Size224]...) }
./sha256.go:212:3:[1] (*digest).Sum stmt: return append(in, hash[:Size224]...)
./sha256.go:214:2:[1] (*digest).Sum stmt: return append(in, hash[:]...)
./sha256.go:207:22: parameter in leaks to ~r0 with derefs=0:
./sha256.go:207:22:   flow: ~r0 = in:
./sha256.go:207:22:     from append(in, hash[:Size224]...) (call parameter) at ./sha256.go:212:16
./sha256.go:207:22:     from return append(in, hash[:Size224]...) (return) at ./sha256.go:212:3
./sha256.go:207:7: d does not escape
./sha256.go:207:22: leaking param: in to result ~r0 level=0
./sha256.go:209:2: moved to heap: d0

./sha256.go:220:6: tmp escapes to heap:
./sha256.go:220:6:   flow: {heap} = &tmp:
./sha256.go:220:6:     from tmp (address-of) at ./sha256.go:223:22
./sha256.go:220:6:     from tmp[0:56 - len % 64] (slice) at ./sha256.go:223:14
./sha256.go:220:6:     from (*digest).Write(d, tmp[0:56 - len % 64]) (call parameter) at ./sha256.go:223:10
./sha256.go:225:10:[1] (*digest).checkSum stmt: (*digest).Write(d, tmp[0:64 + 56 - len % 64])
./sha256.go:220:6: tmp escapes to heap:
./sha256.go:220:6:   flow: {heap} = &tmp:
./sha256.go:220:6:     from tmp (address-of) at ./sha256.go:225:25
./sha256.go:220:6:     from tmp[0:64 + 56 - len % 64] (slice) at ./sha256.go:225:14
./sha256.go:220:6:     from (*digest).Write(d, tmp[0:64 + 56 - len % 64]) (call parameter) at ./sha256.go:225:10
```

The tangible effect of this discrepancy is that `sha256.digest.Sum` always allocates on certain architectures.

**Comment by cuonglm** [comment]
This is because on these systems:

```
arm
ppc64
mips
mipsle
mips64
mips64le
riscv64
```

They use the [generic version](https://github.com/golang/go/blob/56c3856d529d72e280ad6b185f7927657de86c37/src/crypto/sha256/sha256block.go#L80), which make the `*digest` escape to heap.

Other architectures has their own implementation, which does not, e.g, for arm64 https://github.com/golang/go/blob/56c3856d529d72e280ad6b185f7927657de86c37/src/crypto/sha256/sha256block_arm64.go#L12

**Comment by randall77** [comment]
This is kind of unfortunate, because the digest clearly does not escape in `blockGeneric`. The problem is in sha256block_generic.go, where we do
```
var block = blockGeneric
```
That makes callers of `block` not know the target function, and thus has to assume escaping arguments.

It would be better to use a wrapper
```
func block(dig *digest, p []byte) { blockGeneric(dig, p) }
```
The wrapper will get inlined, and escape analysis will see the flow properly.
