### ISSUE TITLE
Working gif fails to decode with image/gif DecodeAll

### ISSUE THREAD

**Issue by AttilaTheFun** [golang/go#48050]
I'm using Go 1.16 and the following Gif is failing to decode with the image/gif DecodeAll function with the error: 
`gif: can't recognize format "8\x99\xbax\x99\x99"`

![Image](https://user-images.githubusercontent.com/3255391/131267554-663e1db8-eb35-4330-a87f-4226ff1b3d50.GIF)

After a little debugging, it seems like the gif has a version field that's not one of the supported types, or it doesn't have a version at all. (Maybe one is assumed?)
```
func (d *decoder) readHeaderAndScreenDescriptor() error {
	err := readFull(d.r, d.tmp[:13])
	if err != nil {
		return fmt.Errorf("gif: reading header: %v", err)
	}
	d.vers = string(d.tmp[:6])
	if d.vers != "GIF87a" && d.vers != "GIF89a" {
		return fmt.Errorf("gif: can't recognize format %q", d.vers)
	}
```

This is obviously a valid gif, and it works on all browsers and devices I've tested it on. I've also tested the Gif with https://github.com/h2non/filetype and it has the right magic numbers to be identified as a Gif. Maybe instead of choking on a gif with an unrecognized version, there should be an option to try anyways and assume it's the most common format?

**Comment by daddyman** [comment]
I downloaded the GIF and it seems to work for me. The GIF starts with GIF87a and looks to have a valid header:
```
00000000: 47 49 46 38 37 61 E0 01 E0 01 F7 00 00 00 00 00    GIF87a`.`.w.....
00000010: 1D 16 18 21 16 16 23 1A 17 2F 1C 17 3A 22 1C 2D    ...!..#../..:".-
00000020: 23 20 33 25 20 3C 2B 24 44 2C 25 49 2E 27 3C 2F    #.3%.<+$D,%I.'</
00000030: 2A 44 32 2B 4C 33 2C 51 36 2D 4B 3B 34 55 3B 31    *D2+L3,Q6-K;4U;1
00000040: 5A 3D 34 53 3E 39 67 3F 38 5E 42 37 54 43 3C 5E    Z=4S>9g?8^B7TC<^
```

This program prints out SUCCESS

```
package main

import (
    "fmt"
    "image/gif"
    "os"
)

func main() {
    f, _ := os.Open("test.gif")
    g, err := gif.DecodeAll(f)
    if err != nil {
        fmt.Printf("FAILED: %v\n", err)
    } else {
        fmt.Printf("SUCCESS: %+v\n", g)
    }
}
```

* Are you opening the correct file?
* Are you passing the reader pointed at the start of the file (haven't read anything from the reader after opening it)?

**Comment by AttilaTheFun** [comment]
Hmm thanks for the pointer @daddyman - I was able to verify that just immediately calling DecodeAll worked. I was previously decoding the config first, and then calling DecodeAll, but I was rewinding the file pointer between the calls. It seems like indirecting the file pointer through a readSeeker interface was causing some issues. I'll close this issue now, thanks!
