### ISSUE TITLE
database/sql: Control over connection pool

### ISSUE THREAD

**Issue by kisielk** [golang/go#4805]
<pre>From <a href="http://golang.org/src/pkg/database/sql/doc.txt">http://golang.org/src/pkg/database/sql/doc.txt</a>:

* Handle concurrency well.  Users shouldn't need to care about the
   database's per-connection thread safety issues (or lack thereof),
   and shouldn't have to maintain their own free pools of connections.
   The 'db' package should deal with that bookkeeping as needed.  Given
   an *sql.DB, it should be possible to share that instance between
   multiple goroutines, without any extra synchronization.

I think the current approach fails to achieve this because there is no control over the
dynamics of the pool. For example the pool size can grow without bound if there are
enough goroutines trying to use the DB connection. This is a problem if your database
has limits on the number of connections per user, as you end up with errors when trying
to use a *sql.DB.

The current workaround is to maintain your own fixed-size pool of *sql.DB's and ensure
each one is only used by one goroutine at a time, which seems counter to the package
design goals.

There should be a way to configure maxIdleConns, as well as a way to set the maximum
number of connections.</pre>

**Comment by ChrisHines** [comment]
It seems to me that the all of the requested features in the initial issue comment are fully satisfied by the current database/sql package and subsequent add-on requests have been rejected. Should we close this issue?

**Comment by bradfitz** [comment]
Sure. People can open new specific bugs as needed.
