### ISSUE TITLE
x/pkgsite: Apache 2.0 License detected but package documentation is still hidden

### ISSUE THREAD

**Issue by diegocarrion-wk** [golang/go#48068]
### What is the URL of the page with the issue?
https://pkg.go.dev/github.com/Workiva/ssllabs-go@v0.1.4/v3
 
 
### What is your user agent?
 

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
 
 
### Screenshot
 

<img width="1675" alt="Captura de Pantalla 2021-08-30 a la(s) 17 40 34" src="https://user-images.githubusercontent.com/33633850/131365845-059488d9-62ea-43cf-bfa6-db64c19d3e80.png">
 
 
### What did you do?
 

Our legal team requires that we add extra text at the bottom of our LICENSE file mentioning other repos used in the creation of the repository. In order to hopefully get pkg.go.dev to still show our documentation, we added a LICENSE.docs file with standard Apache 2.0 text only.
It appears that it does indeed detect an Apache 2.0 license along with an UNKOWN file.
 
### What did you expect to see?

We were hoping that we would see our package documentation, due to the inclusion of a detectable license.
 
 
### What did you see instead?

Package documentaion hidden message.

**Comment by jba** [comment]
This should be live by next Tuesday.

**Comment by jba** [comment]
I just confirmed that the doc is visible.
