### ISSUE TITLE
Go 1.17: Cross-compile with GOOS=Android leads to incorrect linking on linux/amd64 host

### ISSUE THREAD

**Issue by georgekav2** [golang/go#48063]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ubuntu/server/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3298679238=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Simply cross compiling on the linux/amd64 host for an Android binary
<pre>
$ env GOOS=android GOARCH=arm64 go build .
$ file serverd
</pre>

### What did you expect to see?
I expect the binary to be compiled for arm64 and dynamically linked against Android library or statically linked. 
<pre>
serverd: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, not stripped
</pre>

### What did you see instead?
I confirm an ARM64 compilation but the dynamic linker is the host's architecture and library and not the Android's one. 
<pre>
serverd: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=gGFFVo4RFV6aGfZVTEH6/eDLtKhLO6hgV6qTO7a3Q/sHoO_oaiLLGdS7iQjNSG/iaWj7bE06FH2AU8asBXn, not stripped
</pre>

On Windows (cygwin) I am getting the expected binary linking
<pre>
$ go version
go version go1.17 windows/amd64
$ file serverd
serverd: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, not stripped
</pre>

**Comment by cherrymui** [comment]
Probably due to #47760. CL https://go-review.googlesource.com/c/go/+/343010 should fix this. Could you try using Go tip (the master branch)? Thanks.

**Comment by cherrymui** [comment]
Closing as a dup of #47760. Feel free to reopen if this is mistaken. Thanks.
