### ISSUE TITLE
cmd/go: get -d upgrades version for modules in subfolder

### ISSUE THREAD

**Issue by bep** [golang/go#48069]
This worked as expected in Go 1.16.7. 

```bash
 go version && uname -a
go version go1.17 darwin/amd64
Darwin bep-mac16.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
```

```bash
mkdir mymod
cd mymod
go mod init mymod
go get -d github.com/bep/mod-subs/mod1@v1.0.0
go get -d github.com/bep/mod-subs/mod1
go get: upgraded github.com/bep/mod-subs/mod1 v1.0.0 => v1.1.0
```

```bash
mymod git:(master) ✗ go mod graph
mymod github.com/bep/mod-b@v1.0.0
mymod github.com/bep/mod-subs/mod1@v1.1.0
github.com/bep/mod-subs/mod1@v1.1.0 github.com/bep/mod-b@v1.0.0
github.com/bep/mod-subs/mod1@v1.1.0 github.com/bep/mod-d@v1.0.0
```

Doing the same with `go1.16.7`:

```bash
...
go mod graph
mymod github.com/bep/mod-subs/mod1@v1.0.0
github.com/bep/mod-subs/mod1@v1.0.0 github.com/bep/mod-b@v1.0.0
github.com/bep/mod-subs/mod1@v1.0.0 github.com/bep/mod-d@v1.0.0
```

**Comment by jayconrod** [comment]
Is this explained by https://golang.org/doc/go1.17#graph-pruning? The way the go command manages module graphs changed substantially in 1.17, and since this example starts with a new `go 1.17` module, this may be working as intended.

If not, please fill out the issue template and add more detail, especially in "What did you expect to see?".

**Comment by bep** [comment]
>"What did you expect to see?".

* I expect `go get -d some-module` to respect the version set in `go.mod`. This is a very simple dependency graph, and I can see no reason for an upgrade.
* This is a direct dependency and I can see no relevance with your "graph pruning" reference.
* This works as expected when the `go get`-ed module is living in the repository root.
* And as I said, this also works as expected in Go 1.16.7.

**Comment by jayconrod** [comment]
> I expect go get -d some-module to respect the version set in go.mod (as in: the version I already installed). This is a very simple dependency graph, and I can see no reason for an upgrade.

`go get -d path` is equivalent to `go get -d path@upgrade`. When no version is specified, `go get` upgrades the packages or modules listed on the command line to the latest available version. So `go get -d github.com/bep/mod-subs/mod1` *should* upgrade to `v1.1.0`. Both Go 1.16 and 1.17 will do that.

> This is a direct dependency and I can see no relevance with your "graph pruning" reference.

Graph pruning means that in 1.17, after the `go get` commands, your `go.mod` file looks like this. It includes explicit requirements on all modules needed to build the packages listed by the `go get` command.

```
module mymod

go 1.17

require (
	github.com/bep/mod-b v1.0.0 // indirect
	github.com/bep/mod-subs/mod1 v1.1.0 // indirect
)
```

This affects the output of `go mod graph`.

> This works as expected when the go get-ed module is living in the repository root.

Do you mean when the argument to `go get` is the main module or a package within the main module? Or do you mean when the argument is another module that's the subject of a `replace` directive? And by "works as expected" do you mean that it isn't upgraded? Or something else?

**Comment by seankhliao** [comment]
I see the same behaviour in 1.16 as 1.17:

```
main » go1.16.7 mod init test
go: creating new go.mod: module test

main » cat go.mod
module test

go 1.16


main » go1.16.7 get -d github.com/bep/mod-subs/mod1@v1.0.0
go get: added github.com/bep/mod-subs/mod1 v1.0.0

main » cat go.mod
module test

go 1.16

require github.com/bep/mod-subs/mod1 v1.0.0 // indirect


main » go1.16.7 get -d github.com/bep/mod-subs/mod1
go get: upgraded github.com/bep/mod-subs/mod1 v1.0.0 => v1.1.0

main » cat go.mod
module test

go 1.16

require github.com/bep/mod-subs/mod1 v1.1.0 // indirect
```

**Comment by bep** [comment]
OK, I'll close this for now (I repeated the steps above on Go 1.16 and now it behaved differently, which does not make much sense). I will get back to you when I find out what the _real issue is_

>go get -d path is equivalent to go get -d path@upgrade. 

That is not even mentioned in `go help get`. That is the behaviour I would expect from `go get -u`.

Anyhow, I will get back with a more stable test case.

**Comment by seankhliao** [comment]
It is mentioned as the first example:

> To add a dependency for a package or upgrade it to its latest version:
>
>     go get example.com/pkg

**Comment by bep** [comment]
You are all right, I'm sorry. My issue was something completely different.
