### ISSUE TITLE
cmd/gofmt: indenting of multi-line case list is confusing

### ISSUE THREAD

**Issue by pieter-biomerieux** [golang/go#48065]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 linux/amd64
</pre>

### What did you do?

I pass this file to gofmt:

```go
package main

import "fmt"
import "math/rand"

func main() {
r := rand.Intn(5)
switch r {
case 0:
fmt.Println("It's zero!")
case 1, 
2:
fmt.Println("It's one or two!")
default:
fmt.Println("It's something else")
}
}
```

### What did you see?
```go
package main

import "fmt"
import "math/rand"

func main() {
	r := rand.Intn(5)
	switch r {
	case 0:
		fmt.Println("It's zero!")
	case 1,
		2:
		fmt.Println("It's one or two!")
	default:
		fmt.Println("It's something else")
	}
}
```
Notice how the case list of `case 1,2` blends into the case's code.

### What did you expect?
I can think of two options:
- Add two indentation levels when starting the second line of the multi-line case list, and remove one indentation level when entering the case
```go
package main

import "fmt"
import "math/rand"

func main() {
	r := rand.Intn(5)
	switch r {
	case 0:
		fmt.Println("It's zero!")
	case 1,
			2:
		fmt.Println("It's one or two!")
	default:
		fmt.Println("It's something else")
	}
}
```
- Align with the first case of the case list
```go
package main

import "fmt"
import "math/rand"

func main() {
    r := rand.Intn(5)
    switch r {
    case 0:
        fmt.Println("It's zero!")
    case 1,
         2:
        fmt.Println("It's one or two!")
    default:
        fmt.Println("It's something else")
    }
}
```

**Comment by pieter-biomerieux** [comment]
I don't know the logic of gofmt. This might be the same issue as #48064. Sorry to double submit if this is the case.

**Comment by cherrymui** [comment]
No worries. It indeed looks like a dup. Closing.
