### ISSUE TITLE
cgo with static library build error

### ISSUE THREAD

**Issue by cavities** [golang/go#48070]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.7 linux/amd64

$g++  and gcc version
gcc version 8.4.0 (Ubuntu 8.4.0-1ubuntu1~18.04)
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cavity/.cache/go-build"
GOENV="/home/cavity/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/mnt/g/ubuntu_env/goxpath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/mnt/g/ubuntu_env/goxpath"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/mnt/g/ubuntu_env/goxroot/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/mnt/g/ubuntu_env/goxroot/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.7"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1264827653=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
tree
├── echo.h
├── echo.c
├── libecho.a
└── main.go

//echo.h
void echo1();
void echo2();

//echo.c
#include <stdio.h>
void echo1(){
    printf("echo1\n");
}
void echo2(){
    printf("echo2\n");
}

=> build to static lib
bash$ g++ -c echo.c

build .o file
- echo.o

ar crv libecho.a echo.o

build .a file
- libecho.a

//main.go

package main
// #cgo CXXFLAGS: -I.
// #cgo CFLAGS: -I.
// #cgo LDFLAGS: -static -L. -lecho
// #cgo LDFLAGS: -lstdc++
// #include "echo.h"
import "C"
import "fmt"

func main(){
    C.echo1()
    C.echo2()
    fmt.Println("say go\n")
}

No matter how I add LDFLAGS or change， when i go build it 

when i delete echo.c file
Show:

/tmp/go-build3395880773/b001/_x002.o: In function `_cgo_92b3b4849300_Cfunc_echo1':
/tmp/go-build/cgo-gcc-prolog:49: undefined reference to `echo1'
/tmp/go-build3395880773/b001/_x002.o: In function `_cgo_92b3b4849300_Cfunc_echo2':
/tmp/go-build/cgo-gcc-prolog:61: undefined reference to `echo2'
collect2: error: ld returned 1 exit status

So why do I need static library?

**Comment by cherrymui** [comment]
I'm not sure I understand what you want to do. Could you paste the full and exact commands you run, and the error message? Thanks.

> $ g++ -c echo.c

Try `gcc -c echo.c`. When compiling as C++ the function names may be mangled, whereas on the Go side it uses unmangled names, because it is a Go-C interface.

**Comment by mattn** [comment]
If you want to use `g++`, `extern "C"` should be used.

```cpp
extern "C" {
void echo1();
void echo2();
}
```

```cpp
#include <stdio.h>
#include "echo.h"
void echo1(){
printf("echo1\n");
}
void echo2(){
printf("echo2\n");
}
```

**Comment by cavities** [comment]
doesn't matter. What matters is that I can't go build , I'm actually calling someone else's static library

**Comment by cavities** [comment]
relocation R_X86_64_32S against symbol `_ZTV13memory_buffer' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status


even using   CFLAGS: -fPIC

**Comment by seankhliao** [comment]
Cgo works with a C interface, the (C++) library needs to export the correct identifiers for linking

**Comment by cavities** [comment]
when i build from ubuntu to centos, it's OK.
It should be with the kernel version.
