### ISSUE TITLE
x/pkgsite: "Why Go" overlaps with search box at specific widths

### ISSUE THREAD

**Issue by seankhliao** [golang/go#48073]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/search?q=multierror
https://beta.pkg.go.dev/search?q=multierror
 
### What is your user agent?
 
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
 
### Screenshot
![2021-08-30-210223](https://user-images.githubusercontent.com/11343221/131391330-f6ed9ca7-72da-4cfa-983f-2bec8aa659d2.png)
 
### What did you do?
 
Resize window width to around 924-970 px on pkg.go.dev
or 1040-1080 px on beta.pkg.go.dev
 
### What did you expect to see?
 
 "Why Go" doesn't overlap with search box
 
### What did you see instead?

"Why Go" overlaps

**Comment by jamalc** [comment]
Thanks for reporting, this should be fixed by [CL 345511](https://golang.org/cl/345511) and went out with today's deploy about 45 mins ago.
