### ISSUE TITLE
cmd/compile: "missing function body" detection stops working

### ISSUE THREAD

**Issue by cherrymui** [golang/go#48097]
### What version of Go are you using (`go version`)?

tip (bdc1bef8a0)

### Does this issue reproduce with the latest release?

No.

### What did you do?

Compiling the following code, with a bodyless function but not assembly file or linknames.

```
package p

func F()
```

### What did you expect to see?
```
$ go1.17 build x.go
# command-line-arguments
./x.go:3:6: missing function body
```

### What did you see instead?
```
$ go build x.go
$ go tool compile -complete x.go
```
No error for both commands. cmd/go does pass -complete to the compiler correctly, but the compiler doesn't detect the error.

cc @mdempsky @aclements @thanm

**Comment by cuonglm** [comment]
This seems `-G=3` issue, or specifically, `irgen` since when it also does not handle `//go:noescape`:

```
package p

func F()

//go:noescape
func f() {}
```
