### ISSUE TITLE
types2, go/types: need to detect invalid recursive type instantiation

### ISSUE THREAD

**Issue by griesemer** [golang/go#48098]
Per the [type parameters proposal](https://github.com/golang/proposal/blob/master/design/43651-type-parameters.md#generic-types):

_A generic type can refer to itself in cases where a type can ordinarily refer to itself, but when it does so the type arguments must be the type parameters, listed in the same order._

The type checkers currently don't do this test. Reminder issue.

cc: @findleyr

**Comment by findleyr** [comment]
Related: #45550.

**Comment by griesemer** [comment]
Related: #48096.

**Comment by findleyr** [comment]
This was just reported again in #48671, though in that case the recursion was through a method.

I don't think the same restriction should apply to methods. Consider the following:

```
func (*List[T]) ToInterfaceList() *List[interface{}]
```

Somewhat contrived, but one can imagine how something like this could be useful. Perhaps we need logic to detect infinitely expanding instantiation patterns.

**Comment by findleyr** [comment]
I opened #48703 for infinite recursion through method signatures. It is similar to this issue but requires a different fix.

Also marking this issue as a release blocker.

**Comment by griesemer** [comment]
@rogpeppe The compiler reports an error now for your [example](https://github.com/golang/go/issues/48098#issuecomment-938708866).

More generally, this general issue seems to have been addressed with the new nomono check in the type checkers. I believe @mdempsky wanted to add some more tests, so leaving this open for now but not a release blocker anymore.

**Comment by griesemer** [comment]
I am going to close this as fixed at this point.
