### ISSUE TITLE
cmd/vet: "unexpected kind tag" when running default 'go test' analyzers on a package that uses generics

### ISSUE THREAD

**Issue by bcmills** [golang/go#48101]
Now that #48094 is fixed, I'm running into another issue using generics, this time via `go vet` and whatever `cmd/vet` uses to import packages.

### What version of Go are you using (`go version`)?

<pre>
~/src/github.com/bcmills/unsafeslice$ gotip version
go version devel go1.18-144e0b1f6 Tue Aug 31 17:35:15 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ gotip env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/local/google/home/bcmills/.cache/go-build"
GOENV="/usr/local/google/home/bcmills/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/usr/local/google/home/bcmills/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/local/google/home/bcmills"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/google/home/bcmills/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/google/home/bcmills/sdk/gotip/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.18-144e0b1f6 Tue Aug 31 17:35:15 2021 +0000"
GCCGO="/usr/local/google/home/bcmills/bin/gccgo"
AR="ar"
CC="gcc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/usr/local/google/home/bcmills/src/github.com/bcmills/unsafeslice/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4211120039=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

In the root of the repository at https://github.com/bcmills/unsafeslice/commit/849066caf28406f55c56d79265767233bedb7669, run `go test .`.

### What did you expect to see?

A successful test run, or a test failure, or a compile error indicating a problem in my code.

### What did you see instead?

```
~/src/github.com/bcmills/unsafeslice$ gotip test .
# github.com/bcmills/unsafeslice_test
vet: ./safe_test.go:19:2: could not import github.com/bcmills/unsafeslice (cannot import "github.com/bcmills/unsafeslice" (unexpected kind tag in "github.com/bcmills/unsafeslice": 11), possibly version skew - reinstall package)
FAIL    github.com/bcmills/unsafeslice [build failed]
FAIL
```

CC @griesemer @findleyr @mdempsky @cuonglm

**Comment by bcmills** [comment]
Everything else seems to work at that commit if I bypass `vet`:
```
~/src/github.com/bcmills/unsafeslice$ gotip test -vet=off .
ok      github.com/bcmills/unsafeslice  0.018s
```

**Comment by findleyr** [comment]
This is because we've fallen behind in `go/internal/gcimporter`.

I can port the necessary importer changes.
