### ISSUE TITLE
Can the behavior of deserialization be controlled such as duplicate key?

### ISSUE THREAD

**Issue by anurnomeru** [golang/go#48114]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/anur/Library/Caches/go-build"
GOENV="/Users/anur/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/anur/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/anur/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/15/_sp2z3dd0fb8fstvwym6x9lh0000gn/T/go-build1387144217=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I called `gopkg.in/yaml.v3` to deserialize yaml, this yaml defined duplicate key, and the key-value is lost.

### What did you expect to see?
Want to customize the behavior, for example, set `vendor/gopkg.in/yaml.v3/decode.go:311` to false, so that the key bebind will overwrite the key previous.

Or continue parsing the duplicate key, and report the error.

### What did you see instead?
```
            shell: "zsh"
            workDir: "/root/nocalhost-dev"
            resources:
              limits:
                memory: 4Gi
                cpu: "1"
              requests:
                memory: 2Gi
                cpu: "0.5"
            persistentVolumeDirs:
              - path: "/root"
            debug:
              remoteDebugPort: 5005
            sync:
              type: send
              filePattern:
                - .
              ignoreFilePattern:
                - .git
                - ./build
                - ./bin

            gitUrl: git@e.coding.net:codingcorp/coding-artifacts.git
            command:
              run: [ "cd", "cmd/artifacts-gateway", "&&", "go", "run", "artifacts-gateway.go" ]
            sync:
              type: send
              filePattern:
                - ./backend
```

I defined some duplicate keys, and i get en empty struct.
struct:
```
type ServiceDevOptions struct {
	Name                  string                 `json:"name" yaml:"name"`
	Type                  string                 `json:"serviceType" yaml:"serviceType"`
	GitUrl                string                 `json:"gitUrl" yaml:"gitUrl"`
	DevImage              string                 `json:"devContainerImage" yaml:"devContainerImage"`
	WorkDir               string                 `json:"workDir" yaml:"workDir"`
	Sync                  []string               `json:"syncDirs" yaml:"syncDirs,omitempty"` // dev start -s
	PriorityClass         string                 `json:"priorityClass,omitempty" yaml:"priorityClass,omitempty"`
	PersistentVolumeDirs  []*PersistentVolumeDir `json:"persistentVolumeDirs" yaml:"persistentVolumeDirs"`
	BuildCommand          []string               `json:"buildCommand,omitempty" yaml:"buildCommand,omitempty"`
	RunCommand            []string               `json:"runCommand,omitempty" yaml:"runCommand,omitempty"`
	DebugCommand          []string               `json:"debugCommand,omitempty" yaml:"debugCommand,omitempty"`
	HotReloadRunCommand   []string               `json:"hotReloadRunCommand,omitempty" yaml:"hotReloadRunCommand,omitempty"`
	HotReloadDebugCommand []string               `json:"hotReloadDebugCommand,omitempty" yaml:"hotReloadDebugCommand,omitempty"`
	DevContainerShell     string                 `json:"devContainerShell" yaml:"devContainerShell"`
	DevContainerResources *ResourceQuota         `json:"devContainerResources" yaml:"devContainerResources"`
	DevPort               []string               `json:"devPorts" yaml:"devPorts"`
	Jobs                  []string               `json:"dependJobsLabelSelector" yaml:"dependJobsLabelSelector,omitempty"`
	Pods                  []string               `json:"dependPodsLabelSelector" yaml:"dependPodsLabelSelector,omitempty"`
	SyncedPattern         []string               `json:"syncFilePattern" yaml:"syncFilePattern"`
	IgnoredPattern        []string               `json:"ignoreFilePattern" yaml:"ignoreFilePattern"`
}
```

**Comment by seankhliao** [comment]
This is the issue tracker for the Go project, not gopkg.in/yaml.v3
