### ISSUE TITLE
sql scan string does not got right string , but i got  Numbers in scientific notation

### ISSUE THREAD

**Issue by cnmade** [golang/go#48113]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.17 windows/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes ， always can reproduce

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\admin\AppData\Local\go-build
set GOENV=C:\Users\admin\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\admin\go\pkg\mod
set GONOPROXY=git.coldlake.cn,code.aliyun.com
set GONOSUMDB=*
set GOOS=windows
set GOPATH=C:\Users\admin\go
set GOPRIVATE=git.coldlake.cn,code.aliyun.com
set GOPROXY=https://goproxy.io,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\workspace\netroby\gosense\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\admin\AppData\Local\Temp\go-build951611585=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

```
package test

import (
	"database/sql"
	"testing"
)

func TestSqliteQuery(t *testing.T) {
	db, err := sql.Open("sqlite3", "../vol/db.sqlite")
	if err == nil {
		t.Error(err)
	}
	rows, err := db.Query("SELECT id, content, similar_hash FROM gs_hotnews where similar_hash = '17913184137643624000'")
	if err != nil {
		t.Error(err)
	}
	var id int64
	var content string
	var similar_hash string

	for rows.Next() {
		err = rows.Scan(&id, &content, &similar_hash)
		if err != nil {
			t.Error(err)
		}
		t.Logf("%+v, %+v, %+v", id, content, similar_hash)
	}

}

```

This is a simple sqlite db
```
create table gs_hotnews
(
    id           integer
        primary key,
    created_at   datetime,
    updated_at   datetime,
    deleted_at   datetime,
    ts           text,
    content      text,
    publish_time integer,
    similar_hash integer
);

create index idx_gs_hotnews_deleted_at
    on gs_hotnews (deleted_at);

```
then we insert one row into it 
```
5726,2021-09-01 04:36:48.40449432+00:00,2021-09-01 04:36:48.40449432+00:00,,12:36:46,印度政府要求公用业务考虑增加煤炭进口，以提高发电能力。,1630471006,17913184137643624000

```

### What did you expect to see?

The column similar_hash should be string ,it will store a long number

### What did you see instead?

what i got

```
=== RUN   TestSqliteQuery
    sqlite_test.go:11: <nil>
    sqlite_test.go:26: 5726, 印度政府要求公用业务考虑增加煤炭进口，以提高发电能力。, 1.7913184137643624e+19
--- FAIL: TestSqliteQuery (0.00s)

FAIL
```

The result of similar_hash not what i expect. why you change the response , did i let you do that ? how dare you can .

**Comment by seankhliao** [comment]
This appears to be an issue with your database driver and not Go

Please keep our [Code of Conduct](https://golang.org/conduct) in mind when filling issues

**Comment by cnmade** [comment]
1. it's not my driver. https://github.com/mattn/go-sqlite3 
2. I am not professional engineer to written go src. Is it a driver problem or by go/sql problem ? how to know it .
3. I am happy to know as you tips . and i try to get reach the right place.
