### ISSUE TITLE
net/http: Server doesn't use ReadHeaderTimeout for TLS handshake deadline

### ISSUE THREAD

**Issue by bradfitz** [golang/go#48120]
The net/http.Server does:

```go
// Serve a new connection.
func (c *conn) serve(ctx context.Context) {
...
        if tlsConn, ok := c.rwc.(*tls.Conn); ok {
                if d := c.server.ReadTimeout; d > 0 {
                        c.rwc.SetReadDeadline(time.Now().Add(d))
                }
                if d := c.server.WriteTimeout; d > 0 {
                        c.rwc.SetWriteDeadline(time.Now().Add(d))
                }
                if err := tlsConn.HandshakeContext(ctx); err != nil {
```

But if only `Server.ReadHeaderTimeout` is set (and not `ReadTimeout`), it seems like `ReadHeaderTimeout` should be used for the TLS handshake deadline instead of infinite.

/cc @neild

**Comment by komuw** [comment]
related? https://github.com/golang/go/issues/35626

**Comment by cherrymui** [comment]
Yeah, it seems similar to #35626. @bradfitz @neild feel free to close if you think this is a dup. Thanks.

**Comment by bradfitz** [comment]
Not a dup, but similar. Different bugs involving the same tunables.
