### ISSUE TITLE
cmd/compile: cannot highlight AST lines in ssa.html

### ISSUE THREAD

**Issue by Zheng-Xu** [golang/go#48133]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-7622e41c84 Mon Aug 30 22:09:22 2021 +0000 linux/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

1. GOSSAFUNC=main.test go build test.go
2. Open ssa.html in browser.
3. Click any lines in any sections other than AST section.
4. Click any lines in AST section.

### What did you expect to see?
Corresponding lines in AST section should be highlight from step 3.
Lines in different sections(including AST) should be highlighted from step 4.

### What did you see instead?
No line highlight in AST section from step 3.
No line highlight in any sections from step 4.

This issue was introduced by CL 275785

**Comment by cherrymui** [comment]
cc @dr2chase @josharian

**Comment by erifan** [comment]
This is a regression since Go1.17, should we backport it to Go1.17 ?

**Comment by cherrymui** [comment]
No. We only backport serious issues without workarounds. This is clearly not serious. And ssa.html is mostly for compiler developers, not for general users.

**Comment by erifan** [comment]
> No. We only backport serious issues without workarounds. This is clearly not serious. And ssa.html is mostly for compiler developers, not for general users.

Ok.
