### ISSUE TITLE
go/src/runtime/internal fails to build on 32-bit ARM

### ISSUE THREAD

**Issue by jkowalski** [golang/go#48134]
### What version of Go are you using (`go version`)?
1.16.x and 1.17

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 20.04.3 on ARM (Raspberry PI 4, 32-bit mode), running inside Docker container `myoung34/github-runner:ubuntu-bionic`

### What did you do?
I'm running a build cluster consisting of 12 Raspberry PI 4s for [Kopia](https://github.com/kopia/kopia) that includes a mix of 64-bit and 32-bit ARM configurations executing GitHub actions workflows.

I've recently noticed that 32-bit ARM builds started being very flaky. At the beginning of a build when I download the required tools using `go get`, I frequently get this failure:

```
# runtime/internal/sys
27
/usr/local/go/src/runtime/internal/sys/stubs.go:9:7: PtrSize redeclared in this block
28
	/usr/local/go/src/runtime/internal/sys/arch.go:24:38: previous declaration
29
/usr/local/go/src/runtime/internal/sys/stubs.go:10:24: undefined: Uintreg
30
/usr/local/go/src/runtime/internal/sys/stubs.go:16:7: StackGuardMultiplier redeclared in this block
31
	/usr/local/go/src/runtime/internal/sys/arch.go:27:74: previous declaration
32
make: *** [/tmp/github-runner-kopia/kopia/kopia/tools/.tools/bin/gotestsum] Error 2
33
```

Sometimes it's this failure:

```
# runtime
27
/usr/local/go/src/runtime/mgcpacer.go:16:2: gcGoalUtilization redeclared in this block
28
	previous declaration at /usr/local/go/src/runtime/mgc.go:977:27
29
/usr/local/go/src/runtime/mgcpacer.go:29:2: gcBackgroundUtilization redeclared in this block
30
	previous declaration at /usr/local/go/src/runtime/mgc.go:990:33
31
/usr/local/go/src/runtime/mgcpacer.go:37:2: gcCreditSlack redeclared in this block
32
	previous declaration at /usr/local/go/src/runtime/mgc.go:998:23
33
/usr/local/go/src/runtime/mgcpacer.go:41:2: gcAssistTimeSlack redeclared in this block
34
	previous declaration at /usr/local/go/src/runtime/mgc.go:1002:27
35
/usr/local/go/src/runtime/mgcpacer.go:46:2: gcOverAssistWork redeclared in this block
36
	previous declaration at /usr/local/go/src/runtime/mgc.go:1007:32
37
/usr/local/go/src/runtime/mgcpacer.go:49:2: defaultHeapMinimum redeclared in this block
38
	previous declaration at /usr/local/go/src/runtime/mgc.go:167:33
39
/usr/local/go/src/runtime/mgcpacer.go:72:5: gcController redeclared in this block
40
	previous declaration at /usr/local/go/src/runtime/mgc.go:339:5
41
/usr/local/go/src/runtime/mgcpacer.go:74:6: gcControllerState redeclared in this block
42
	previous declaration at /usr/local/go/src/runtime/mgc.go:341:6
43
/usr/local/go/src/runtime/mgcpacer.go:277:29: (*gcControllerState).startCycle redeclared in this block
44
	previous declaration at /usr/local/go/src/runtime/mgc.go:433:6
45
/usr/local/go/src/runtime/mgcpacer.go:822:6: setGCPercent redeclared in this block
46
	previous declaration at /usr/local/go/src/runtime/mgc.go:225:34
47
/usr/local/go/src/runtime/mgcpacer.go:277:29: too many errors
48
tools/tools.mk:231: recipe for target '/tmp/github-runner-kopia/kopia/kopia/tools/.tools/bin/gotestsum' failed
49
```

The code is here:

https://github.com/kopia/kopia/blob/06451aa7c271c250199d1b1fa182d6417db57e71/tools/tools.mk#L232

Both failures were on `1.16` but I'm also seeing them after upgrading to `1.17`. 

The funny thing is this build cluster has been very stable for a long time and this issue only started happening around 3-4 days ago.

**Comment by jkowalski** [comment]
BTW. Golang is installed manually using `curl -s -L https://golang.org/dl/go1.17.linux-armv6l.tar.gz | tar -C /usr/local -xz`

**Comment by jkowalski** [comment]
It's possible that PR run that upgraded to 1.17 on top of previous 1.16 installation without cleaning it up (before or after) and it could have somehow "poisoned" the runner state. Looking at the logs, the PR affected 2 runners out of 5 and all runs after this had this problem. I'm going to wipe all runners state completely clean.

What's the proper way to clean up Go installation going forward? Do I just delete `/usr/local/go` or are the additional cache directories that need to be cleaned up?

**Comment by jkowalski** [comment]
Cleaning up fixed the issue, closing.

**Comment by ALTree** [comment]
> What's the proper way to clean up Go installation going forward?

Deleting /usr/local/go is enough, and also *required*. Never untar a new version on top of the older one.

**Comment by liudonghua123** [comment]
I have the same issue, it was because my go installation overwrite the old version files which maybe not complete. I uninstalled and removed the left files and installed again. Now this error disappeared.
