### ISSUE TITLE
cmd/go: fuzzing output adjustments

### ISSUE THREAD

**Issue by rsc** [golang/go#48132]
The current chatty fuzzing output should be more amenable to processing with test2json. There are only minor changes needed:

- It should start with a 'test beginning' header the same as when a regular test runs.
- Having done that, the "fuzzing," prefix should probably be "fuzz:", and all the output lines should begin with that, to separate them from prints.
- 'found a crash, minimizing...' should be 'fuzz: found a %d-byte crash input; minimizing'.

/cc @jayconrod @katiehockman

**Comment by rsc** [comment]
I see now that the header does happen with -v, just not without -v.
That is probably OK, since test2json requires -v. 
But the other adjustments should still be applied.

**Comment by rsc** [comment]
Watching the output more, it would help to use d.Round(1*time.Second).String() to format the elapsed duration d, instead of printing number of seconds. It gets tiring to do the mental math on lines like

	fuzzing, elapsed: 1389.0s, execs: 67961175 (48928/sec), workers: 16, interesting: 334

Duration.String would say 23m9s instead.

**Comment by rsc** [comment]
Thanks for the fixes. Looks like one was missed as far as the prefix:

    gathering baseline coverage, elapsed: 0s, workers: 16, left: 4178

I would suggest making this a bit closer to the status messages, like

    fuzz: elapsed: 0s, processing seed corpus: 0/4178 cases done

or something like that. I'm not sure what the 'left: 4178' means exactly, so the suggested rewrite may not be any good on that front. It seems like there should be a second one of those prints when it's completely done with the corpus, or whatever 'left: 0' would mean.

While I'm nitpicking:

    fuzz: found a 52-byte crash input; minimizing...

would be more concise and I think equally clear as

    fuzz: minimizing 52-byte crash input

I'm also not sure about the word 'crash' here, since in my case they are t.Fail inputs. There is no actual crash.
I wonder if it should be 'failure input'. 

Similarly, perhaps 'Crash written to ...' should be 'Failure input written to ...'

**Comment by rsc** [comment]
And does the number of workers ever change? Maybe it should just be printed once instead of in every message?

```
fuzz: elapsed: 3m27s, execs: 32025801 (154712/sec), workers: 16, interesting: 3
fuzz: elapsed: 3m30s, execs: 32472170 (154626/sec), workers: 16, interesting: 3
fuzz: elapsed: 3m33s, execs: 32957605 (154728/sec), workers: 16, interesting: 3
fuzz: elapsed: 3m36s, execs: 33428733 (154761/sec), workers: 16, interesting: 3
fuzz: elapsed: 3m39s, execs: 33887371 (154734/sec), workers: 16, interesting: 3
fuzz: elapsed: 3m42s, execs: 34354633 (154749/sec), workers: 16, interesting: 3
```

**Comment by katiehockman** [comment]
> Looks like one was missed as far as the prefix:

Will fix this, and the other nits! 👍 

> And does the number of workers ever change? Maybe it should just be printed once instead of in every message?

Nope. We can probably just print it once at the start.

As for the use of "crash", that's the verbiage we've been using throughout our documentation and blog posts so far to indicating any kind of failure that is found during fuzzing. It's also something that's used in a lot of other documentation around the web about fuzzing (like libfuzzer's `-minimize_crash` flag). Is this something you feel really strongly about? Otherwise, I'd really prefer to keep it.

**Comment by katiehockman** [comment]
> fuzz: minimizing 52-byte crash input

@jayconrod suggested keeping the `...` in a previous CL because it tells the user that something is in progress and they should wait. LMK if you disagree.

**Comment by rsc** [comment]
Thanks for the fixes. Using crasher is OK but we need to define it clearly in the docs (in package testing and also in reference docs), since it doesn't mean what it looks like.
