### ISSUE TITLE
x/sys/unix: does not define Time_t for FreeBSD

### ISSUE THREAD

**Issue by igalic** [golang/go#48148]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 freebsd/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/meena/.cache/go-build"
GOENV="/home/meena/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOINSECURE=""
GOMODCACHE="/home/meena/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="freebsd"
GOPATH="/home/meena/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/home/meena/src/time/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2640531444=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I tried to use `unix.Time_t` on a FreeBSD system:

```go
package main

import(
        "fmt"
        "golang.org/x/sys/unix"
)

func main() {
        fmt.Println(*(*unix.Time_t))
}
```

### What did you expect to see?

```
./time_t.go:9:14: type unix.Time_t is not an expression
```

### What did you see instead?

```
./time_t.go:9:14: undefined: unix.Time_t
```

**Comment by jharshman** [comment]
I'd like to take a pass at a fix if one isn't already underway,

**Comment by tklauser** [comment]
@jharshman please feel free to send a fix

**Comment by jharshman** [comment]
Haven't regenerated the files for arm and arm64. Not sure if this can be done without an emulator or without actually running the `./mkall.sh` command on arm architecture.
