### ISSUE TITLE
context.propagateCancel parent.Err() is panic

### ISSUE THREAD

**Issue by zgy666** [golang/go#48144]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
        parent := blademaster{}
	mc := new(MyContext)
	mc.c = make(chan struct{})
	parent.Context = mc
	ctx, _ := context.WithCancel(&parent)

	for i := 0; i < 10; i++ {
		wg.Add(1)
		go f(ctx, i)
	}
	time.Sleep(time.Second * 2)

	parent.Context = nil
	close(mc.c)

        wg.Wait()

type blademaster struct {
	context.Context
}

type MyContext struct {
	c chan struct{}
}

func (*MyContext) Deadline() (deadline time.Time, ok bool) {
	return
}

func (m *MyContext) Done() <-chan struct{} {
	return m.c
}

func (*MyContext) Err() error {
	return nil
}

func (*MyContext) Value(key interface{}) interface{} {
	return nil
}

func f(ctx context.Context, i int) {
	fmt.Println("context----", i)
	defer wg.Done()
Loop:
	for {
		select {
		case <-ctx.Done():
			fmt.Println("ctx done-------", i)
			break Loop
		}
	}
}

### What did you expect to see?
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x108d889]

goroutine 6 [running]:
main.(*blademaster).Err(0xc000010240)
        <autogenerated>:1 +0x29
context.propagateCancel.func1()
        /usr/local/go/src/context/context.go:281 +0xc2
created by context.propagateCancel
        /usr/local/go/src/context/context.go:278 +0x1d0

**Comment by seankhliao** [comment]
Your code doesn't follow the context interface properly
