### ISSUE TITLE
cmd/go: fuzz docs should update TB doc to say “T, B, and F.”

### ISSUE THREAD

**Issue by rsc** [golang/go#48146]
```
% gotip doc testing.TB
...
    TB is the interface common to T and B.
```

should say “T, B, and F.”

/cc @golang/fuzzing

**Comment by toothrot** [comment]
Checking in on this issue as it's labeled a release blocker for Go 1.18. Is there any update?

**Comment by uppalabharath** [comment]
@cherrymui , @julieqiu 

I gave a try to fix this issue.  I made the changes and raised a Gerrit review. 
But I need help is testing these changes. Is there a guide that I can follow to test out the fix.

Thanks
