### ISSUE TITLE
x/crypto/curve25519: consider removing dependency on "fmt" if worthwhile

### ISSUE THREAD

**Issue by dmitshur** [golang/go#48154]
The `curve25519` package imports `fmt` and uses it 3 times:

```Go
return nil, fmt.Errorf("bad scalar length: %d, expected %d", l, 32)
return nil, fmt.Errorf("bad point length: %d, expected %d", l, 32)
return nil, fmt.Errorf("bad input point: low order point")
```

If it makes sense to remove `fmt`, then the `golang.org/x/crypto/curve25519` can be moved in `go/build.TestDependencies` from:

```
# CRYPTO-MATH is core bignum-based crypto - no cgo, net; fmt now ok.
```

To:

```
# CRYPTO is core crypto algorithms - no cgo, fmt, net.
```

Similarly to how `crypto/ed25519/internal/edwards25519` was moved in [CL 276272](https://go-review.googlesource.com/c/go/+/276272/24/src/go/build/deps_test.go).

@FiloSottile, do you think doing so would be worthwhile?

**Comment by FiloSottile** [comment]
Yeah, why not, those can be simple `strconv.Itoa` and `errors.New` calls. I'll send a CL.

**Comment by dmitshur** [comment]
Sounds good. Please include a small test in x/crypto that this package doesn't import `fmt`, so this property doesn't accidentally regress without the benefit of go/build's test.

**Comment by aaqaishtyaq** [comment]
Hey @FiloSottile, I would like to work on this. I have removed dependency  on `fmt` from `curve25519/curve25519.go`.
Let me know if I am going right and additional changes I need to make. 

Thanks

**Comment by ianlancetaylor** [comment]
This doesn't seem urgent, moving milestone to Backlog.

**Comment by aaqaishtyaq** [comment]
@FiloSottile @ianlancetaylor Can we close the issue, please?
https://go-review.googlesource.com/c/go/+/413794/comment/babcbae2_b09a307d/

**Comment by dmitshur** [comment]
`golang.org/x/crypto/curve25519` no longer imports `fmt` as of [CL 348069](https://golang.org/cl/348069), and it's not vendored into standard library at all as of [CL 398914](https://go.dev/cl/398914), so everything here is done. Thanks @aaqaishtyaq.
