### ISSUE TITLE
src: a warning is now emitted if $GOROOT_BOOTSTRAP is not set after commit 840b429

### ISSUE THREAD

**Issue by siebenmann** [golang/go#48155]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-782aa42255 Thu Sep 2 15:14:50 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

No.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/homes/hawklords/cks/.cache/go-build"
GOENV="/homes/hawklords/cks/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/homes/hawklords/cks/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/homes/hawklords/cks/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/data/code/go-lang/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/data/code/go-lang/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.18-782aa42255 Thu Sep 2 15:14:50 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/data/code/go-lang/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmpfs/go-build811440550=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Starting from commit 840b4292c9cd5472babf562d3b6eaf727926fd90, "src: emit warning when make.bash run with invalid GOROOT_BOOTSTRAP", building Go emits a verbose warning message even when $GOROOT_BOOTSTRAP is not set at all. I believe no warning should be printed when this environment variable is unset so that you're using the default Go you already have (especially a confusing one that talks about $HOME/go1.4). A warning will encourage people to hard-code $GOROOT_BOOTSTRAP in their environment, with possible downstream consequences if things change and they forget to update their setting of this environment variable.

### What did you expect to see?

No warning.

### What did you see instead?

```
WARNING: /homes/hawkwind/u0/cks/go1.4/bin/go does not exist, found /usr/bin/go from env
WARNING: set /usr/lib/golang as GOROOT_BOOTSTRAP
Building Go cmd/dist using /usr/lib/golang. (go1.16.6 linux/amd64)
[...]
```

**Comment by cuonglm** [comment]
The purpose of that CL is exactly what you see, emit a warning when no `GOROOT_BOOTSTRAP` was unset, or set to invalid path. For building go, it requires you to have a valid `GORROT_BOOTSTRAP`, so if you unset or set to invalid value, thing may not work as you expected.

cc @mdempsky @ianlancetaylor @thanm

**Comment by mdempsky** [comment]
Oh, I missed that CL adds a warning when unset too. I think a typo'd path definitely needs a warning. I'm inclined to think having it unset doesn't need a warning though, assuming we found a default.

Open to hearing others' opinions.

**Comment by siebenmann** [comment]
The current warning message is potentially confusing, because it can be read to imply that you should have a $HOME/go1.4 as the first choice (which is not right).

If a valid GOROOT_BOOTSTRAP is considered to be required, not having a valid, working one should be a hard error, not a warning (and I assume that special checking for $HOME/go1.4 should be dropped entirely). If it is optional, an unspecified one should in my opinion not produce a two line, all caps "WARNING" message about the situation that reports attempting a default value of $HOME/go1.4 before falling back to whatever existing 'go' command it can find. This is the only WARNING produced while building from source. My personal expectation is that most people building Go tip from source don't set GOROOT_BOOTSTRAP because they haven't needed it so far.

Also, the current instructions for building Go from source say that GOROOT_BOOTSTRAP is optional, [here](https://golang.org/doc/install/source#go14). If it's required, these instructions should be updated when Go 1.18 is released, or perhaps before.

**Comment by cuonglm** [comment]
> Also, the current instructions for building Go from source say that GOROOT_BOOTSTRAP is optional, here. If it's required, these instructions should be updated when Go 1.18 is released, or perhaps before.

Can you point out where in the document says it's optional? AFAICT, `GOROOT_BOOTSTRAP` is always required, that's why `make.bash` set it a default value if you don't set. If you don't have a existed go toolchain in your env, and no `GOROOT_BOOTSTRAP` set, then you can't build go.

**Comment by bcmills** [comment]
@cuonglm, my understanding from this report is that the warning was observed _with_ an existing Go toolchain in `$PATH`.

**Comment by zikaeroh** [comment]
That's what I'm seeing too, though I typically use `gotip download` (the friendlier way to run tip).

```
$ gotip download
Updating the go development tree...
remote: Finding sources: 100% (2101/2101)
remote: Total 2101 (delta 997), reused 1762 (delta 997)
Receiving objects: 100% (2101/2101), 4.35 MiB | 3.97 MiB/s, done.
Resolving deltas: 100% (997/997), completed with 80 local objects.
From https://go.googlesource.com/go
 * branch                  master     -> FETCH_HEAD
   6cf1d5d0fa..acc2957bc9  master     -> origin/master
Previous HEAD position was 6cf1d5d0fa cmd/compile: generic SSA rules for simplifying 2 and 3 operand integer arithmetic expressions
HEAD is now at acc2957bc9 net/http: fix hang in probing for a zero-length request body
WARNING: /home/jake/go1.4/bin/go does not exist, found /usr/bin/go from env
WARNING: set /usr/lib/go as GOROOT_BOOTSTRAP
Building Go cmd/dist using /usr/lib/go. (go1.17 linux/amd64)
Building Go toolchain1 using /usr/lib/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/amd64.
---
Installed Go for linux/amd64 in /home/jake/sdk/gotip
Installed commands in /home/jake/sdk/gotip/bin
Success. You may now run 'gotip'!
```

I would also assume that unset (or empty?) is a valid setup.

**Comment by cuonglm** [comment]
> @cuonglm, my understanding from this report is that the warning was observed _with_ an existing Go toolchain in `$PATH`.

Yeah, I understand. The problem is that whether `GOROOT_BOOTSTRAP` is incorrectly set or unset (default to `$HOME/go1.4), we check whether `$GOROOT_BOOTSTRAP/bin/go` existed, if yes, use it, if not, find a valid `go` from env, and if any found, use that `go`'s `GOROOT` as `GOROOT_BOOTSTRAP`.

My point is that in both case, `GOROOT_BOOTSTRAP` is invalid, thus we should emit warning when we set the one that we found from env.

**Comment by zikaeroh** [comment]
I don't think unset is "invalid". Sure, `make.bash` needs `GOROOT_BOOTSTRAP` to build, eventually, but I don't think not setting it is wrong from the point of view of who's running it. For me, `make.bash` was the one configuring this detail for me. It itself documents `GOROOT_BOOTSTRAP` as:

```
# GOROOT_BOOTSTRAP: A working Go tree >= Go 1.4 for bootstrap.
# If $GOROOT_BOOTSTRAP/bin/go is missing, $(go env GOROOT) is
# tried for all "go" in $PATH. $HOME/go1.4 by default.
```

If `GOROOT_BOOTSTRAP` is set and invalid, I'd expect it to emit a warning, then pretend like it wasn't set at all, falling back to using what's in `PATH`.

**Comment by siebenmann** [comment]
About GOROOT_BOOTSTRAP being optional when you run the build scripts, quoting from [the official install instructions](https://golang.org/doc/install/source#go14), emphasis mine:

> The Go toolchain is written in Go. To build it, you need a Go compiler installed. The scripts that do the initial build of the tools look for a "go" command in $PATH, so as long as you have Go installed in your system and configured in your $PATH, you are ready to build Go from source. **Or if you prefer you can set $GOROOT_BOOTSTRAP** to the root of a Go installation to use to build the new Go toolchain; $GOROOT_BOOTSTRAP/bin/go should be the go command to use.

The official instructions not only say that GOROOT_BOOTSTRAP is optional, they imply that it's not the default way you should build Go. The default way is to have a Go compiler and let the scripts find it in your $PATH. Presumably using the documented default way should not emit a warning.

**Comment by zikaeroh** [comment]
> If `GOROOT_BOOTSTRAP` is set and invalid, I'd expect it to emit a warning, then pretend like it wasn't set at all, falling back to using what's in `PATH`.

Just to clarify my opinion a little; I think that the above make sense if warnings are desired, but honestly I think it might be better to completely error out when `GOROOT_BOOTSTRAP` is broken instead. If it's set but wrong, it's a little mysterious for the build to complete anyway (and maybe someone never sees the warning, or it's a part of a packaging step where the logs aren't always seen). But, maybe it doesn't really matter, given the intent of the bootstrap process is that by the end of `make.bash`, it didn't matter what `GOROOT_BOOTSTRAP` was anyway.
