### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by aswathizedon** [golang/go#48168]
This is mostly a concern with the banner at the top of the golang website. I kind of think it is not attractive to involve race relations in a programming language. The experience I've had makes me not only not want to use golang, but none of the technologies which touch golang. I'm sure I'm not the first person to think this, and I would sincerely appreciate if the it was removed from the website. Thanks! 

I'm not posting from the primary account I have because I do not want to have any relation with a group that effectively promotes violence (such as the group described in the banner). 

Increasing the amount of people which would use golang would likely increase.

**Comment by jpadrianoGo** [comment]
This banner made me want to use golang.

**Comment by ALTree** [comment]
Thanks for the issue.

The people running the website have made abundantly clear that they want the banner to stay, and this has been discussed in the past, see: #39850, #43006, https://github.com/golang/go/issues/41094#issuecomment-682574230 and many others. 

I'm closing here as a dup of previous discussions.
