### ISSUE TITLE
crypto/x509: invalid RDNSequence: invalid attribute value: unsupported string type: 18

### ISSUE THREAD

**Issue by mic6090** [golang/go#48171]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, the latest release has regression

 ### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\michael\AppData\Local\go-build
set GOENV=C:\Users\michael\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\michael\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\michael\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\src\go\apitest\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\michael\AppData\Local\Temp\go-build1442540087=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
https://play.golang.org/p/gVmDQZr638l

### What did you expect to see?
nil (no error when parse certificate)

### What did you see instead?
x509: invalid RDNSequence: invalid attribute value: unsupported string type: 18

go 1.17 encoding/x509 parser does not know about Numeric String (type 18 asn.1) while previous version of Golang does.

**Comment by seankhliao** [comment]
cc @FiloSottile @rolandshoemaker

**Comment by mic6090** [comment]
golang.org/x/crypto/cryptobyte, golang.org/x/crypto/cryptobyte/asn1 does not support tag 18 type while standard library encoding/asn1 does.
go1.16 does not have this issue - why go1.17 should use outdated code from golang.org/x/crypto/cryptobyte[/asn1] ?

**Comment by Theo730** [comment]
join the question 
solved the problem like this :
in go-1.17.3/src/vendor/golang.org/x/crypto/cryptobyte/asn1/asn1.go
added `NumericString     = Tag(18)`
in go-1.17.3/src/crypto/x509/parser.go
added 
`
func isNumeric(b byte) bool {
    return '0' <= b && b <= '9'
}
`
and processing
`
case cryptobyte_asn1.NumericString:
    for _, b := range value {
        if !isNumeric(b) {
            return "", errors.New("invalid NumrticString")
        }
    }
return string(value), nil
`
in 
`func parseASN1String(tag cryptobyte_asn1.Tag, value []byte) (string, error) {
    switch tag {
`

**Comment by rittneje** [comment]
@seankhliao @FiloSottile This is a regression from 1.16 that remains broken even in the latest head. Can the linked CL please be merged, and backported to 1.17?

**Comment by rittneje** [comment]
@seankhliao @FiloSottile @katiehockman @rolandshoemaker @agl

**Comment by rolandshoemaker** [comment]
@gopherbot please open a backport issue for 1.17. This is a regression in the parser rewrite that prevents parsing some certificates.
