### ISSUE TITLE
Can't correctly build with GOLLVM

### ISSUE THREAD

**Issue by bestbug456** [golang/go#48173]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

At this point in time I can't update to the latest version of GO

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/opt/vmsdk/helloworld/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build155675155=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I'm try to obtain the LLVM IR from a sample repository organise as follow:

<pre>
helloworld
    main.go
    describe.go
    hello
        hello.go
</pre>

I'm using the following commit for each of the indicated repository
<pre>
llvm-project: 43ff75f2c3feef64f9d73328230d34dac8832a91
llvm-project/llvm/tools/gollvm: 44a7a475cfd3b871b7a5a0941b8ab1ea9d489adc
llvm-project/llvm/tools/gollvm/gofrontend: be0d2cc2df9f98d967c242594838f86362dae2e7
llvm-project/llvm/tools/gollvm/libgo/libffi:737d4faa00d681b4c758057f67e1a02d813d01c2
llvm-project/llvm/tools/gollvm/libgo/libbacktrace: 5a99ff7fed66b8ea8f09c9805c138524a7035ece
</pre>

I've run the go build processes following close as I can the documentation as follow
<details><summary><code>Commands</code></summary><br><pre>
go build -work -x  1> transcript.txt 2>&1
/gollvm/install/bin/llvm-goc -c -g -m64 -fdebug-prefix-map=/tmp/go-build887393727/tmp/go-build -gno-record-gcc-switches -fgo-pkgpath=command-line-arguments -fgo-relative-import-path=/mygopath/src/tmp -I /tmp/go-build815658471/b001/_importcfgroot_ -o helloworld.ll -S -emit-llvm main.go 
</pre></details>

Which result in the following error
main.go:4:18: warning: helloworld/hello: Not a directory
main.go:4:18: error: import file 'helloworld/hello' not found
main.go:8:2: error: reference to undefined name 'hello'
main.go:9:2: error: reference to undefined name 'describe'

### What did you expect to see?
A compiled llvm IR

### What did you see instead?
The previosly reported error

Thanks for the support!

**Comment by cherrymui** [comment]
Could you show the complete list of commands you run? There is probably a missing piece about the import.

Could you try `go build -work -gccgoflags="-S -emit-llvm" main.go` after a normal build? The command may fail, but you may get the IR somewhere.

**Comment by bestbug456** [comment]
Hello @cherrymui,

The section "commands" contain all I've done. This is the result of the command you suggested

<pre>
go build -work -gccgoflags="-S -emit-llvm" main.go describe.go
WORK=/tmp/go-build144219385
go build: when using gc toolchain, please pass compile flags using -gcflags, and linker flags using -ldflags

/gollvm/install/bin/llvm-goc -c -g -m64 -fdebug-prefix-map=/tmp/go-build144219385/tmp/go-build -gno-record-gcc-switches -fgo-pkgpath=command-line-arguments -fgo-relative-import-path=/mygopath/src/tmp -I /tmp/go-build815658471/b001/_importcfgroot_ -o helloworld.ll -S -emit-llvm main.go describe.go
main.go:4:18: warning: helloworld/hello: Not a directory
main.go:4:18: error: import file 'helloworld/hello' not found
main.go:8:2: error: reference to undefined name 'hello'
main.go:9:2: error: reference to undefined name 'describe'
</pre>

I've also add describe.go this is the only difference between what you write and what I've done.

Thanks!

**Comment by cherrymui** [comment]
Could you show the source code you're compiling? Does it build with the gc toolchain (the main Go distribution)/

Note that you need a go.mod file if you use module mode, or set GOPATH environment variable and GO111MODULE=off if you're using legacy GOPATH mode.

**Comment by bestbug456** [comment]
Hello,

Apologies for delay. [Here](https://github.com/bestbug456/gollvmRepository) you can find my test repository.

Cheers

**Comment by cherrymui** [comment]
What version of Go do you use? If it is `go1.14.7`, it is quite old and no longer supported. Try using a newer version of  Go.

Let's take a step back. Can you build it with gollvm without emitting LLVM IR? (i.e. without -emit-llvm?)

https://github.com/golang/go/issues/48173#issuecomment-912622127 doesn't look like the full output. Can try `go clean -cache`, then `go build -x  -work`, and  paste the full command line and full output? Also, is your `go` command built from  the gc toolchain or gollvm? What is `go  version` output?

Anyway, this doesn't look like a bug to me, rather a question of setting on your side. For questions, it may be better if you ask on a forum rather than the issue tracker. See https://golang.org/wiki/Questions . Thanks.
