### ISSUE TITLE
x/tools/gopls: unable to use workspace mode due to misuse of -mod flag

### ISSUE THREAD

**Issue by mvdan** [golang/go#48186]
gopls @v0.0.0-20210902182115-3b801c8b8389
go version devel go1.18-ab7c904bf2 Fri Sep 3 05:27:58 2021 +0000 linux/amd64

I'm trying https://github.com/golang/go/issues/45713; I've set up a fairly simple go.work file as follows:

```
go 1.18

directory (
	git/ipfs
	src/ipld
	src/multicodec
)
```

And I've hit "go to definition" in ipfs, which should take me to a file within the multicodec module. This works without the workspace file; it just takes me inside the module download cache.

However, it just errors:

> Exception not caught: got error whilst handling command:GOVIMGoToDef: failed to call gopls.Definition: err: exit status 1: stderr: go: -mod may only be set to readonly when in workspace mode

It appears gopls is calling cmd/go with a -mod value other than "readonly" somewhere, which is not supported by workspace mode.

I'm happy to provide precise repro steps here, since all this code is open source after all, but I also imagine this is enough detail for you to figure out what you need.

cc @matloob @stamblerre

**Comment by mvdan** [comment]
It's possible this is caused by govim, as per @leitzler on Slack:

> This setting might be useful for you unless you have it set already: https://github.com/govim/govim/blob/61d4fa23afba84a51e9a88a81c721907261bd8cb/cmd/govim/config/config.go#L312

And @heschi then mentioned:

> The setting Pontus linked to is totally unsupported in gopls, but on by default in govim.

**Comment by leitzler** [comment]
It would be helpful with a repro from my point of view, I can give it a look into the `govim` side.
I haven't used `go.work` yet so it is unfamiliar territory. This simple example did work for me where I jump from `b.B` in `a/a.go` to `b/b.go`:
```
-- a/a.go --
package a

import "b"

const A = 2

func fn() {
	b.B
}
-- a/go.mod --
module a

go 1.18
-- b/b.go --
package b

const B = 1
-- b/go.mod --
module b

go 1.18
-- go.work --
go 1.17

directory (
    ./a
    ./b
)
```

I do however the setting I linked in my config (the default value is 1/true):
```
call govim#config#Set("ExperimentalAllowModfileModifications", 0)
```

Also had to enable workspace modules using:
```
call govim#config#Set("ExperimentalWorkspaceModule", 1)
```

**Comment by findleyr** [comment]
Thanks for the report.

@mvdan have you tried `call govim#config#Set("ExperimentalAllowModfileModifications", 0)`? Does that avoid the errors for you?

**Comment by mvdan** [comment]
I haven't had more time to dig into this or try again :) I also did not enable workspace support in gopls via `call govim#config#Set("ExperimentalWorkspaceModule", 1)`. I honestly assumed that gopls would just work out of the box with it, given that cmd/go from Go master now supports workspaces by default. If I still need to enable the feature in gopls, maybe the instructions in the proposal should be updated.

**Comment by findleyr** [comment]
> I honestly assumed that gopls would just work out of the box

Agreed, which is why I'm suspicious of this govim setting.  I can investigate and try to repro, but it will probably take a few days for me to get to this. If it's easy for you try unsetting this experimental feature in govim, that would help narrow it down.

**Comment by mvdan** [comment]
Ever since I disabled ExperimentalAllowModfileModifications, I haven't run into this error again. So I think the blame should indeed be put on that option being on when it shouldn't be. I've filed https://github.com/govim/govim/issues/1112 to fix that in govim.

I think we can close this issue for now, unless others run into similar errors with gopls again (with that experimental setting turned off!).
