### ISSUE TITLE
cmd/compile: cannot use .this (type *Foo[[]byte]) as type Foo[.shape.[]uint8] in argument

### ISSUE THREAD

**Issue by jfesler** [golang/go#48198]
### What version of Go are you using (`go version`)?

<pre>
% gotip version
go version devel go1.18-9133245 Sat Sep 4 20:35:25 2021 +0000 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Latest `gotip`, yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
% gotip env

GO111MODULE="on"
GOARCH="arm64"
GOBIN="/Users/jfesler/bin"
GOCACHE="/Users/jfesler/Library/Caches/go-build"
GOENV="/Users/jfesler/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jfesler/go/pkg/mod"
GONOPROXY="xxxx"
GONOSUMDB="*xxxx"
GOOS="darwin"
GOPATH="/Users/jfesler/go"
GOPRIVATE="xxxx"
GOPROXY="https://xxxx|direct"
GOROOT="/Users/jfesler/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/jfesler/sdk/gotip/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="devel go1.18-9133245 Sat Sep 4 20:35:25 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/05/dq8h20tn4h58j32qn6r75vdc0000gn/T/go-build2830397944=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

<pre><code>
package foo

import (
    "testing"
)

type Foo[T any] struct {
    Generator func() interface{}
}

func NewFoo[T any](template T, generator func() interface{}) Foo[T] {
    return Foo[T]{
        Generator: generator,
    }
}

func (foo Foo[T]) Get() T {
    return foo.Generator().(T)
}

func TestFoo(t *testing.T) {
    _ = NewFoo([]byte{}, func() interface{} {
        return make([]byte, 1)
    })
}

</code></pre>

### What did you expect to see?

Successful compile.

### What did you see instead?

<pre><code>
% gotip test
# xxxx/jfesler/uint8-byte-test [xxxx/jfesler/uint8-byte-test.test]
<autogenerated>:1: cannot use .this (type *Foo[[]byte]) as type Foo[.shape.[]uint8] in argument to Foo[.shape.[]uint8].Get
</cod></pre>

**Comment by korzhao** [comment]
Simple：
```golang
package main


type Foo[T any] struct {
}

func (foo Foo[T]) Get()  {
}

func main() {
	f := Foo[[]byte]{}
	f.Get()
}
```
