### ISSUE TITLE
cmd/compile: "UNREVIEWED" headers scattered around the tree

### ISSUE THREAD

**Issue by josharian** [golang/go#48194]
A bunch of files in the tree start:

```
// UNREVIEWED

```

I assume this is left over from generics work. Can those all be removed now?

cc @ianlancetaylor @griesemer @mdempsky

**Comment by griesemer** [comment]
Files marked as `//UNREVIEWED` need to be reviewed explicitly. I see (under `src`):
```
./cmd/compile/internal/importer/testdata/exports.go:// UNREVIEWED
./cmd/compile/internal/importer/testdata/issue25301.go:// UNREVIEWED
./cmd/compile/internal/importer/testdata/issue25596.go:// UNREVIEWED
./cmd/compile/internal/importer/testdata/versions/test.go:// UNREVIEWED
./cmd/compile/internal/importer/testdata/issue20046.go:// UNREVIEWED
./cmd/compile/internal/importer/testdata/a.go:// UNREVIEWED
./cmd/compile/internal/importer/testdata/b.go:// UNREVIEWED
./cmd/compile/internal/importer/testdata/p.go:// UNREVIEWED
./cmd/compile/internal/importer/testdata/issue15920.go:// UNREVIEWED
./cmd/compile/internal/noder/unified.go:// UNREVIEWED
./cmd/compile/internal/noder/decoder.go:// UNREVIEWED
./cmd/compile/internal/noder/sync.go:// UNREVIEWED
./cmd/compile/internal/noder/encoder.go:// UNREVIEWED
./cmd/compile/internal/noder/reader2.go:// UNREVIEWED
./cmd/compile/internal/noder/quirks.go:// UNREVIEWED
./cmd/compile/internal/noder/codes.go:// UNREVIEWED
./cmd/compile/internal/noder/writer.go:// UNREVIEWED
./cmd/compile/internal/noder/reloc.go:// UNREVIEWED
./cmd/compile/internal/noder/linker.go:// UNREVIEWED
./cmd/compile/internal/noder/reader.go:// UNREVIEWED
```
The importer test files should match the corresponding test files elsewhere and should be straight-forward. We review them by comparing them against existing reviewed files and pointing out the differences, if any.

The noder files are related to @mdempsky 's work on the unified IR and need to be reviewed in full. This is planned to happen by the end of October (before the freeze).

**Comment by toothrot** [comment]
Checking in on this issue as it's labeled a release blocker for Go 1.18. Is there any update?

**Comment by griesemer** [comment]
Several of these files have been reviewed and now we have a shorter list remaining:
```
./cmd/compile/internal/noder/unified.go:// UNREVIEWED
./cmd/compile/internal/noder/decoder.go:// UNREVIEWED
./cmd/compile/internal/noder/sync.go:// UNREVIEWED
./cmd/compile/internal/noder/encoder.go:// UNREVIEWED
./cmd/compile/internal/noder/reader2.go:// UNREVIEWED
./cmd/compile/internal/noder/quirks.go:// UNREVIEWED
./cmd/compile/internal/noder/codes.go:// UNREVIEWED
./cmd/compile/internal/noder/writer.go:// UNREVIEWED
./cmd/compile/internal/noder/reloc.go:// UNREVIEWED
./cmd/compile/internal/noder/linker.go:// UNREVIEWED
./cmd/compile/internal/noder/reader.go:// UNREVIEWED
```
These are all in new compiler files with functionality that may not be enabled by default for `Go1.18`. So the urgency to have this reviewed soon is lower.

cc: @mdempsky

**Comment by mdempsky** [comment]
Yeah, all of those files are only used for `GOEXPERIMENT=unified`, which we've decided to defer to Go 1.19.

**Comment by aclements** [comment]
There are a handful of unreviewed files remaining. Given that we're going to enable unified IR soon, can we get a quick status update on reviewing these?

```
internal/importer/ureader.go:1:// UNREVIEWED
internal/noder/codes.go:1:// UNREVIEWED
internal/noder/linker.go:1:// UNREVIEWED
internal/noder/quirks.go:1:// UNREVIEWED
internal/noder/reader.go:1:// UNREVIEWED
internal/noder/unified.go:1:// UNREVIEWED
internal/noder/writer.go:1:// UNREVIEWED
```

**Comment by griesemer** [comment]
@aclements My understanding is that @mdempsky is working on getting all the remaining prerequisites in place (such as a compiler-matching importer for go/types, which I reviewed yesterday). We will review these files soon.

**Comment by aclements** [comment]
If I'm not mistaken, once [CL 408234](https://go.dev/cl/408234) lands, the only remaining unreviewed file should be cmd/compile/internal/importer/ureader.go

Given that we're not enabling unified IR for 1.20, it seems like it should be okay to mark this okay-after-beta1 (or possibly even drop release-blocker?)

(This is great progress!)

**Comment by mdempsky** [comment]
Yeah, we can bump the issue for 1.20.

**Comment by griesemer** [comment]
@aclements Presumably you meant that "we're not enabling unified IR for 1.19" (rather than "for 1.20")?

**Comment by aclements** [comment]
Just checking in, it looks like cmd/compile/internal/importer/ureader.go is the only remaining UNREVIEWED file?

**Comment by cuonglm** [comment]
> Just checking in, it looks like cmd/compile/internal/importer/ureader.go is the only remaining UNREVIEWED file?

I think we just forgot to remove the UNREVIEWED header for those files, I sent https://go-review.googlesource.com/c/go/+/422617 for this.
