### ISSUE TITLE
Grammar rules about symbols

### ISSUE THREAD

**Issue by l0k18** [golang/go#48205]
A few months ago I learned that builtin functions (eg copy, append, len) can all be used as symbols in Go. I didn't think that made any sense, but I've never been one to use the `len` variable name for anything, usually 'l' or 'length'.

It begged the question  - what other built in stuff can have its name used?

I'm sure all the experts already know the answer. Is there a reason specifically why especially one cannot use the symbol `interface` as any time you leave out `{}` it will print two errors, one for the missing first parenthesis, and the second for the missing second. 

I'm wondering what the logic looks like that prints that error. Anyhow, `interface` alone may not appear alone anywhere, unless it has parentheses, and any place you put it with parentheses, it's a type trying to be a symbol, and vice versa.

interface is probably the solitary token in the whole compiler that only appears with punctuations.

Ok, yes, no, I am not really raising an issue, per se. I have seen too much code using 'len' as a variable name. interface is a really useful name for medium-to-long functions as a local variable. Naughty Go specification stole names from us.

**Comment by seankhliao** [comment]
Closing as this is non actionable

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by ianlancetaylor** [comment]
See https://golang.org/ref/spec#Predeclared_identifiers
