### ISSUE TITLE
crypto/tls:  maintain cipher suite order 

### ISSUE THREAD

**Issue by wxolp** [golang/go#48207]
It seems currently the client cannot send an unaltered list of CipherSuites, as `crypto/tls` current removes in some places, as well as changing order:

https://github.com/golang/go/blob/7b69ddc171938b8321a535dd79b8ca2ba56ac72d/src/crypto/tls/handshake_client.go#L94-L98

and then also adds in some places:

https://github.com/golang/go/blob/7b69ddc171938b8321a535dd79b8ca2ba56ac72d/src/crypto/tls/handshake_client.go#L125-L129

This is a problem as, I have encountered servers (for example `android.clients.google.com`) that will return `403 Forbidden` if CipherSuites sent by the client is in the wrong order, or if certain ciphers are added or removed.

**Comment by wxolp** [comment]
CC @FiloSottile @ulikunitz

**Comment by seankhliao** [comment]
Related #45430

**Comment by wxolp** [comment]
I found a workaround using another package below. Although I still this is something that should be an option in `crypto/tls`:

~~~go
package cipher

import (
   "bufio"
   "github.com/refraction-networking/utls"
   "net"
   "net/http"
)

func get(addr string) (*http.Response, error) {
   req, err := http.NewRequest("GET", addr, nil)
   if err != nil {
      return nil, err
   }
   dial, err := net.Dial("tcp", req.URL.Host + ":" + req.URL.Scheme)
   if err != nil {
      return nil, err
   }
   cfg := tls.Config{ServerName: req.URL.Host}
   client := tls.UClient(dial, &cfg, tls.HelloCustom)
   spec := tls.ClientHelloSpec{
      CipherSuites: []uint16{
         0x1302, // TLS_AES_256_GCM_SHA384
         0xC02C ,// TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      },
      Extensions: []tls.TLSExtension{
         &tls.SupportedCurvesExtension{
            []tls.CurveID{tls.X25519},
         },
         &tls.SupportedPointsExtension{
            SupportedPoints: []byte{0},
         },
      },
   }
   client.ApplyPreset(&spec)
   client.Handshake()
   req.Write(client)
   return http.ReadResponse(bufio.NewReader(client), req)
}
~~~

**Comment by FiloSottile** [comment]
@wxolp can you give us an example of an URL on that host that returns 403 based on cipher suite order, to reproduce the issue?

**Comment by wxolp** [comment]
I have been able to get a 200 OK response with Python and PHP, but not Go. From what I can tell, I am using the exact same request in all three cases, with only the "TLS fingerprint" being different. Here is an example request, email and password partially redacted:

~~~
POST /auth HTTP/1.1
Host: android.clients.google.com
User-Agent: python-requests/2.26.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 240
Content-Type: application/x-www-form-urlencoded
Authorization: Basic ODl6OmE1NzYxMjZlNzVlZjZiY2Y5ZDljNzEyZWIyN2RmZjFmOGFhZmQ1MWU=

sdk_version=17&Email=SOMETHING%40gmail.com&EncryptedPasswd=AFcb4KTD0IhjQFmNOtCgA...%3D%3D
~~~

**Comment by imroc** [comment]
Same issue, it's because cloudflare return 403 to prevent bots, event set the same header and cookie as web brower, only brower got 200 OK, I guess cloudflare can recognize the tls fingerprint, and there is no way to confgure the same client hello as web brower (e.g. chrome) using go, cuz go's cipher suite order is unconfigurable.
@FiloSottile

**Comment by FiloSottile** [comment]
Protections bypass is not a goal of crypto/tls. There are forks like https://github.com/refraction-networking/utls that attempt to make emulating fingerprints possible.

If all Cloudflare sites are blocking Go clients, we can escalate it with Cloudflare, but my guess is that they are detecting a mismatch between the User-Agent and the TLS stack, which is a valid signal to block.

**Comment by imroc** [comment]
My guess is the website enabled cloudflare's [Super Bot Fight Mode](https://blog.cloudflare.com/super-bot-fight-mode) 

[utls](https://github.com/refraction-networking/utls) is a choise, but seems not actively developed, it would be best if the standard library could support similar customizations

**Comment by seankhliao** [comment]
as mentioned above, this is a non-goal for `crypto/tls`
