### ISSUE TITLE
json: unmarshal with embedded fields doesn't decode unless json tag present

### ISSUE THREAD

**Issue by andig** [golang/go#48201]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/andig/Library/Caches/go-build"
GOENV="/Users/andig/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/andig/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/andig/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.17/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.17/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/andig/htdocs/_/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sv/rs_453y57xj86xsbz3kw1mbc0000gn/T/go-build1171148591=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.17 darwin/arm64
GOROOT/bin/go tool compile -V: compile version go1.17
uname -v: Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101
ProductName:	macOS
ProductVersion:	11.5.2
BuildVersion:	20G95
lldb --version: lldb-1205.0.28.2
Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
</pre></details>

### What did you do?

Decode json to struct containing promoted fields: https://play.golang.org/p/-RKYyGtied9

	type Status struct {
		Battery `json:"battery"`
		Range
	}

for input of

	data := `{
		"battery": {
			"value1": 1
		},
		"range": {
			"value2": 2
		}
	}`

### What did you expect to see?

Battery and Range should both be matched by the respective JSON elements and the inner values decoded. No error shown. Embedded field `Range` should be equivalent `Range Range` in that respect.

### What did you see instead?

Error on range.value since the `Range` ist not matched by the range JSON element.

I realize this is likely not a bug but I'm failing to see why this should be the expected behaviour. Couldn't find anything in https://pkg.go.dev/encoding/json about specific behaviour of embedded fields. There is:

> To unmarshal JSON into a struct, Unmarshal matches incoming object keys to the keys used by Marshal (either the struct field name or its tag), preferring an exact match but also accepting a case-insensitive match. By default, object keys which don't have a corresponding struct field are ignored (see Decoder.DisallowUnknownFields for an alternative).

Apart from their methods becoming promoted I did not expect anything weird to happen here without the json tag.

**Comment by Splizard** [comment]
The fields are promoted by default:
https://play.golang.org/p/eIKBe_XMobj

**Comment by andig** [comment]
It's not quite clear though how the language spec covers the behavior? But I agree, that it's more an education question than a go issue. Thank you!
