### ISSUE TITLE
What does allocs/op and B/op mean in go benchmark?

### ISSUE THREAD

**Issue by njuptlzf** [golang/go#48219]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
```shell
# go  test -bench=. -benchmem -v
BenchmarkIterAndRecursive/recursive2-56                       73          17519191 ns/op        17181082 B/op      15000 allocs/op
BenchmarkIterAndRecursive/iterative
BenchmarkIterAndRecursive/iterative-56                       316           3722242 ns/op          656082 B/op       5171 allocs/op
```

### What did you expect to see?
Please explain my output

**Comment by cuonglm** [comment]
Go project does not use Github issues for Q&A, you may find more information in https://github.com/golang/go/wiki/Questions
