### ISSUE TITLE
buildid.exe is marked as Win32/Uwamson.A!ml by Windows Defender

### ISSUE THREAD

**Issue by ramondeklein** [golang/go#48224]
I have downloaded GO v1.17 (Windows AMD64) from https://golang.org/dl/go1.17.windows-amd64.msi and when I install it, then Windows Defender reports `pkg/tool/windows_amd64/buildid.exe` as `Win32/Uwamson.A!ml`.

![image](https://user-images.githubusercontent.com/6048186/132341846-d670f25f-9fea-47ae-b82c-c0bc3560461e.png)

Based on a lot of reports, it may be a false positive. I did download the MSI again and reinstalled Go, but no change...

**Comment by ALTree** [comment]
Yeah, it's likely a false positive. You could check the checksum to be sure, see: https://golang.org/doc/faq#virus.

And maybe report the false positive to your antivirus vendor so they can fix their contraption.
