### ISSUE TITLE
x/pkgsite: integrate with Go vulnerability database

### ISSUE THREAD

**Issue by jba** [golang/go#48223]
Display information about vulnerabilities in packages and modules.

**Comment by jba** [comment]
This issue covers only vulnerabilities in the package or module being displayed, not transitive vulnerabilities.

We want to show vulnerability information in the following places:

- On the main page for a package.
-  On the versions page.
- In search.

**Comment by jba** [comment]
The original tasks for this issue are done. This issue now tracks the `/vuln`, `/vuln/list` and `/vuln/<ID>` routes.

**Comment by jba** [comment]
Ready for UI.

**Comment by jamalc** [comment]
Vulnerability database information is now available on beta. See the full list at https://beta.pkg.go.dev/vuln/list.

**Comment by seankhliao** [comment]
I'm wondering if the list should be displayed in reverse order with the most recent entries first.
And the content doesn't seem to be parsed as markdown

**Comment by jamalc** [comment]
The vulnerability web portal is live at https://pkg.go.dev/vuln/list.
