### ISSUE TITLE
cmd/compile: nil pointer in buildClosure

### ISSUE THREAD

**Issue by korzhao** [golang/go#48225]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18
</pre>

### Does this issue reproduce with the latest release?

Yes
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```go
package main

type Foo[T any] struct {
}

func (foo Foo[T]) Get()  {
}

var(
     _ = Foo[[]string]{}.Get
)

func main() {
}
```

### What did you see instead?
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x17c49ff]

goroutine 1 [running]:
cmd/compile/internal/noder.(*irgen).buildClosure(0xc0002fa200, 0x0, {0x1a63778, 0xc0003c2300})
        /Users/kezhao/google/go/src/cmd/compile/internal/noder/stencil.go:405 +0xc7f
```

@danscales

**Comment by thanm** [comment]
@randall77 @danscales
