### ISSUE TITLE
GO code with godror compilation error on Oracle Linux 6.8 gcc 4.4.7

### ISSUE THREAD

**Issue by droy208** [golang/go#48242]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/u02/netcracker/rbm/rd1321a1/infinys_root/output/.cache/go-build"
GOENV="/u02/netcracker/rbm/rd1321a1/infinys_root/output/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/u02/netcracker/rbm/rd1321a1/infinys_root/output/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/u02/netcracker/rbm/rd1321a1/infinys_root/output/go"
GOPRIVATE=""
GOPROXY="https://artifactorycn.netcracker.com/pd.sandbox-staging.go.group"
GOROOT="/u01/app/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/u01/app/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2375866878=/tmp/go-build"

</pre></details>

### What did you do?

I am compiling my GO code on Oracle Enterprise Linux(OEL)  6.8. GO code uses godror for Oracle DB. Upon compiling the go code I am getting errors. The main error message is :

*cgo: gcc did not produce error at completed:1*

I know others have reported the same error and the root cause was – gcc version was old.
The gcc version I am using 4.4.7 is the latest one for Oracle Enterprise Linux 6.8.
So, there is no question about using an older version of gcc.

This leads me to think that there is a *limitation* about GO language codes – 

*GO language code using godror cannot be compiled on LINUX version 6.8*  !!

Is this true or am I missing something ?

### What did you expect to see?

Successful compilation of GO code which uses godror on OEL 6.8

### What did you see instead?

go: downloading github.com/godror/godror v0.25.3
go: downloading github.com/go-logfmt/logfmt v0.5.0
# github.com/godror/godror
cgo: gcc did not produce error at completed:1
on input:

#line 1 "cgo-builtin-prolog"
#include <stddef.h> /* for ptrdiff_t and size_t below */

/* Define intgo when compiling with GCC.  */
typedef ptrdiff_t intgo;

#define GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; intgo n; } _GoString_;
typedef struct { char *p; intgo n; intgo c; } _GoBytes_;
_GoString_ GoString(char *p);
_GoString_ GoStringN(char *p, int l);
_GoBytes_ GoBytes(void *p, int n);
char *CString(_GoString_);
void *CBytes(_GoBytes_);
void *_CMalloc(size_t);

__attribute__ ((unused))
static size_t _GoStringLen(_GoString_ s) { return (size_t)s.n; }

__attribute__ ((unused))
static const char *_GoStringPtr(_GoString_ s) { return s.p; }
#line 8 "/u02/netcracker/rbm/rd1321a1/infinys_root/output/go/pkg/mod/github.com/godror/godror@v0.25.3/conn.go"

#include <stdlib.h>
#include "dpiImpl.h

#line 1 "cgo-generated-wrapper"
#line 1 "not-declared"
void __cgo_f_1_1(void) { __typeof__(CString) *__cgo_undefined__1; }
#line 1 "not-type"
void __cgo_f_1_2(void) { CString *__cgo_undefined__2; }
#line 1 "not-int-const"
void __cgo_f_1_3(void) { enum { __cgo_undefined__3 = (CString)*1 }; }
#line 1 "not-num-const"
void __cgo_f_1_4(void) { static const double __cgo_undefined__4 = (CString); }
#line 1 "not-str-lit"
void __cgo_f_1_5(void) { static const char __cgo_undefined__5[] = (CString); }
#line 2 "not-declared"
void __cgo_f_2_1(void) { __typeof__(char) *__cgo_undefined__1; }
#line 2 "not-type"
void __cgo_f_2_2(void) { char *__cgo_undefined__2; }
#line 2 "not-int-const"
void __cgo_f_2_3(void) { enum { __cgo_undefined__3 = (char)*1 }; }
#line 2 "not-num-const"
void __cgo_f_2_4(void) { static const double __cgo_undefined__4 = (char); }
#line 2 "not-str-lit"
void __cgo_f_2_5(void) { static const char __cgo_undefined__5[] = (char); }
#line 3 "not-declared"
void __cgo_f_3_1(void) { __typeof__(dpiConn) *__cgo_undefined__1; }
#line 3 "not-type"
void __cgo_f_3_2(void) { dpiConn *__cgo_undefined__2; }
#line 3 "not-int-const"
void __cgo_f_3_3(void) { enum { __cgo_undefined__3 = (dpiConn)*1 }; }
#line 3 "not-num-const"
void __cgo_f_3_4(void) { static const double __cgo_undefined__4 = (dpiConn); }
#line 3 "not-str-lit"
void __cgo_f_3_5(void) { static const char __cgo_undefined__5[] = (dpiConn); }
#line 4 "not-declared"
void __cgo_f_4_1(void) { __typeof__(dpiConn_breakExecution) *__cgo_undefined__1; }
#line 4 "not-type"
void __cgo_f_4_2(void) { dpiConn_breakExecution *__cgo_undefined__2; }
#line 4 "not-int-const"
void __cgo_f_4_3(void) { enum { __cgo_undefined__3 = (dpiConn_breakExecution)*1 }; }
#line 4 "not-num-const"
void __cgo_f_4_4(void) { static const double __cgo_undefined__4 = (dpiConn_breakExecution); }
#line 4 "not-str-lit"
void __cgo_f_4_5(void) { static const char __cgo_undefined__5[] = (dpiConn_breakExecution); }
#line 5 "not-declared"
void __cgo_f_5_1(void) { __typeof__(dpiConn_commit) *__cgo_undefined__1; }
#line 5 "not-type"
void __cgo_f_5_2(void) { dpiConn_commit *__cgo_undefined__2; }
#line 5 "not-int-const"
void __cgo_f_5_3(void) { enum { __cgo_undefined__3 = (dpiConn_commit)*1 }; }
#line 5 "not-num-const"
void __cgo_f_5_4(void) { static const double __cgo_undefined__4 = (dpiConn_commit); }
#line 5 "not-str-lit"
void __cgo_f_5_5(void) { static const char __cgo_undefined__5[] = (dpiConn_commit); }
#line 6 "not-declared"
void __cgo_f_6_1(void) { __typeof__(dpiConn_getServerVersion) *__cgo_undefined__1; }
#line 6 "not-type"
void __cgo_f_6_2(void) { dpiConn_getServerVersion *__cgo_undefined__2; }
#line 6 "not-int-const"
void __cgo_f_6_3(void) { enum { __cgo_undefined__3 = (dpiConn_getServerVersion)*1 }; }
#line 6 "not-num-const"
void __cgo_f_6_4(void) { static const double __cgo_undefined__4 = (dpiConn_getServerVersion); }
#line 6 "not-str-lit"
void __cgo_f_6_5(void) { static const char __cgo_undefined__5[] = (dpiConn_getServerVersion); }
#line 7 "not-declared"
void __cgo_f_7_1(void) { __typeof__(dpiConn_newVar) *__cgo_undefined__1; }
#line 7 "not-type"
void __cgo_f_7_2(void) { dpiConn_newVar *__cgo_undefined__2; }
#line 7 "not-int-const"
void __cgo_f_7_3(void) { enum { __cgo_undefined__3 = (dpiConn_newVar)*1 }; }
#line 7 "not-num-const"
void __cgo_f_7_4(void) { static const double __cgo_undefined__4 = (dpiConn_newVar); }
#line 7 "not-str-lit"
void __cgo_f_7_5(void) { static const char __cgo_undefined__5[] = (dpiConn_newVar); }
#line 8 "not-declared"
void __cgo_f_8_1(void) { __typeof__(dpiConn_ping) *__cgo_undefined__1; }
#line 8 "not-type"
void __cgo_f_8_2(void) { dpiConn_ping *__cgo_undefined__2; }
#line 8 "not-int-const"
void __cgo_f_8_3(void) { enum { __cgo_undefined__3 = (dpiConn_ping)*1 }; }
#line 8 "not-num-const"
void __cgo_f_8_4(void) { static const double __cgo_undefined__4 = (dpiConn_ping); }
#line 8 "not-str-lit"
void __cgo_f_8_5(void) { static const char __cgo_undefined__5[] = (dpiConn_ping); }
#line 9 "not-declared"
void __cgo_f_9_1(void) { __typeof__(dpiConn_prepareStmt) *__cgo_undefined__1; }
#line 9 "not-type"
void __cgo_f_9_2(void) { dpiConn_prepareStmt *__cgo_undefined__2; }
#line 9 "not-int-const"
void __cgo_f_9_3(void) { enum { __cgo_undefined__3 = (dpiConn_prepareStmt)*1 }; }
#line 9 "not-num-const"
void __cgo_f_9_4(void) { static const double __cgo_undefined__4 = (dpiConn_prepareStmt); }
#line 9 "not-str-lit"
void __cgo_f_9_5(void) { static const char __cgo_undefined__5[] = (dpiConn_prepareStmt); }
#line 10 "not-declared"
void __cgo_f_10_1(void) { __typeof__(dpiConn_release) *__cgo_undefined__1; }
#line 10 "not-type"
void __cgo_f_10_2(void) { dpiConn_release *__cgo_undefined__2; }
#line 10 "not-int-const"
void __cgo_f_10_3(void) { enum { __cgo_undefined__3 = (dpiConn_release)*1 }; }
#line 10 "not-num-const"
void __cgo_f_10_4(void) { static const double __cgo_undefined__4 = (dpiConn_release); }
#line 10 "not-str-lit"
void __cgo_f_10_5(void) { static const char __cgo_undefined__5[] = (dpiConn_release); }
#line 11 "not-declared"
void __cgo_f_11_1(void) { __typeof__(dpiConn_rollback) *__cgo_undefined__1; }
#line 11 "not-type"
void __cgo_f_11_2(void) { dpiConn_rollback *__cgo_undefined__2; }
#line 11 "not-int-const"
void __cgo_f_11_3(void) { enum { __cgo_undefined__3 = (dpiConn_rollback)*1 }; }
#line 11 "not-num-const"
void __cgo_f_11_4(void) { static const double __cgo_undefined__4 = (dpiConn_rollback); }
#line 11 "not-str-lit"
void __cgo_f_11_5(void) { static const char __cgo_undefined__5[] = (dpiConn_rollback); }
#line 12 "not-declared"
void __cgo_f_12_1(void) { __typeof__(dpiConn_setAction) *__cgo_undefined__1; }
#line 12 "not-type"
void __cgo_f_12_2(void) { dpiConn_setAction *__cgo_undefined__2; }
#line 12 "not-int-const"
void __cgo_f_12_3(void) { enum { __cgo_undefined__3 = (dpiConn_setAction)*1 }; }
#line 12 "not-num-const"
void __cgo_f_12_4(void) { static const double __cgo_undefined__4 = (dpiConn_setAction); }
#line 12 "not-str-lit"
void __cgo_f_12_5(void) { static const char __cgo_undefined__5[] = (dpiConn_setAction); }
#line 13 "not-declared"
void __cgo_f_13_1(void) { __typeof__(dpiConn_setCallTimeout) *__cgo_undefined__1; }
#line 13 "not-type"
void __cgo_f_13_2(void) { dpiConn_setCallTimeout *__cgo_undefined__2; }
#line 13 "not-int-const"
void __cgo_f_13_3(void) { enum { __cgo_undefined__3 = (dpiConn_setCallTimeout)*1 }; }
#line 13 "not-num-const"
void __cgo_f_13_4(void) { static const double __cgo_undefined__4 = (dpiConn_setCallTimeout); }
#line 13 "not-str-lit"
void __cgo_f_13_5(void) { static const char __cgo_undefined__5[] = (dpiConn_setCallTimeout); }
#line 14 "not-declared"
void __cgo_f_14_1(void) { __typeof__(dpiConn_setClientIdentifier) *__cgo_undefined__1; }
#line 14 "not-type"
void __cgo_f_14_2(void) { dpiConn_setClientIdentifier *__cgo_undefined__2; }
#line 14 "not-int-const"
void __cgo_f_14_3(void) { enum { __cgo_undefined__3 = (dpiConn_setClientIdentifier)*1 }; }
#line 14 "not-num-const"
void __cgo_f_14_4(void) { static const double __cgo_undefined__4 = (dpiConn_setClientIdentifier); }
#line 14 "not-str-lit"
void __cgo_f_14_5(void) { static const char __cgo_undefined__5[] = (dpiConn_setClientIdentifier); }
#line 15 "not-declared"
void __cgo_f_15_1(void) { __typeof__(dpiConn_setClientInfo) *__cgo_undefined__1; }
#line 15 "not-type"
void __cgo_f_15_2(void) { dpiConn_setClientInfo *__cgo_undefined__2; }
#line 15 "not-int-const"
void __cgo_f_15_3(void) { enum { __cgo_undefined__3 = (dpiConn_setClientInfo)*1 }; }
#line 15 "not-num-const"
void __cgo_f_15_4(void) { static const double __cgo_undefined__4 = (dpiConn_setClientInfo); }
#line 15 "not-str-lit"
void __cgo_f_15_5(void) { static const char __cgo_undefined__5[] = (dpiConn_setClientInfo); }
#line 16 "not-declared"
void __cgo_f_16_1(void) { __typeof__(dpiConn_setDbOp) *__cgo_undefined__1; }
#line 16 "not-type"
void __cgo_f_16_2(void) { dpiConn_setDbOp *__cgo_undefined__2; }
#line 16 "not-int-const"
void __cgo_f_16_3(void) { enum { __cgo_undefined__3 = (dpiConn_setDbOp)*1 }; }
#line 16 "not-num-const"
void __cgo_f_16_4(void) { static const double __cgo_undefined__4 = (dpiConn_setDbOp); }
#line 16 "not-str-lit"
void __cgo_f_16_5(void) { static const char __cgo_undefined__5[] = (dpiConn_setDbOp); }
#line 17 "not-declared"
void __cgo_f_17_1(void) { __typeof__(dpiConn_setModule) *__cgo_undefined__1; }
#line 17 "not-type"
void __cgo_f_17_2(void) { dpiConn_setModule *__cgo_undefined__2; }
#line 17 "not-int-const"
void __cgo_f_17_3(void) { enum { __cgo_undefined__3 = (dpiConn_setModule)*1 }; }
#line 17 "not-num-const"
void __cgo_f_17_4(void) { static const double __cgo_undefined__4 = (dpiConn_setModule); }
#line 17 "not-str-lit"
void __cgo_f_17_5(void) { static const char __cgo_undefined__5[] = (dpiConn_setModule); }
#line 18 "not-declared"
void __cgo_f_18_1(void) { __typeof__(dpiConn_shutdownDatabase) *__cgo_undefined__1; }
#line 18 "not-type"
void __cgo_f_18_2(void) { dpiConn_shutdownDatabase *__cgo_undefined__2; }
#line 18 "not-int-const"
void __cgo_f_18_3(void) { enum { __cgo_undefined__3 = (dpiConn_shutdownDatabase)*1 }; }
#line 18 "not-num-const"
void __cgo_f_18_4(void) { static const double __cgo_undefined__4 = (dpiConn_shutdownDatabase); }
#line 18 "not-str-lit"
void __cgo_f_18_5(void) { static const char __cgo_undefined__5[] = (dpiConn_shutdownDatabase); }
#line 19 "not-declared"
void __cgo_f_19_1(void) { __typeof__(dpiConn_startupDatabase) *__cgo_undefined__1; }
#line 19 "not-type"
void __cgo_f_19_2(void) { dpiConn_startupDatabase *__cgo_undefined__2; }
#line 19 "not-int-const"
void __cgo_f_19_3(void) { enum { __cgo_undefined__3 = (dpiConn_startupDatabase)*1 }; }
#line 19 "not-num-const"
void __cgo_f_19_4(void) { static const double __cgo_undefined__4 = (dpiConn_startupDatabase); }
#line 19 "not-str-lit"
void __cgo_f_19_5(void) { static const char __cgo_undefined__5[] = (dpiConn_startupDatabase); }
#line 20 "not-declared"
void __cgo_f_20_1(void) { __typeof__(dpiData) *__cgo_undefined__1; }
#line 20 "not-type"
void __cgo_f_20_2(void) { dpiData *__cgo_undefined__2; }
#line 20 "not-int-const"
void __cgo_f_20_3(void) { enum { __cgo_undefined__3 = (dpiData)*1 }; }
#line 20 "not-num-const"
void __cgo_f_20_4(void) { static const double __cgo_undefined__4 = (dpiData); }
#line 20 "not-str-lit"
void __cgo_f_20_5(void) { static const char __cgo_undefined__5[] = (dpiData); }
#line 21 "not-declared"
void __cgo_f_21_1(void) { __typeof__(dpiNativeTypeNum) *__cgo_undefined__1; }
#line 21 "not-type"
void __cgo_f_21_2(void) { dpiNativeTypeNum *__cgo_undefined__2; }
#line 21 "not-int-const"
void __cgo_f_21_3(void) { enum { __cgo_undefined__3 = (dpiNativeTypeNum)*1 }; }
#line 21 "not-num-const"
void __cgo_f_21_4(void) { static const double __cgo_undefined__4 = (dpiNativeTypeNum); }
#line 21 "not-str-lit"
void __cgo_f_21_5(void) { static const char __cgo_undefined__5[] = (dpiNativeTypeNum); }
#line 22 "not-declared"
void __cgo_f_22_1(void) { __typeof__(dpiObjectType) *__cgo_undefined__1; }
#line 22 "not-type"
void __cgo_f_22_2(void) { dpiObjectType *__cgo_undefined__2; }
#line 22 "not-int-const"
void __cgo_f_22_3(void) { enum { __cgo_undefined__3 = (dpiObjectType)*1 }; }
#line 22 "not-num-const"
void __cgo_f_22_4(void) { static const double __cgo_undefined__4 = (dpiObjectType); }
#line 22 "not-str-lit"
void __cgo_f_22_5(void) { static const char __cgo_undefined__5[] = (dpiObjectType); }
#line 23 "not-declared"
void __cgo_f_23_1(void) { __typeof__(dpiOracleTypeNum) *__cgo_undefined__1; }
#line 23 "not-type"
void __cgo_f_23_2(void) { dpiOracleTypeNum *__cgo_undefined__2; }
#line 23 "not-int-const"
void __cgo_f_23_3(void) { enum { __cgo_undefined__3 = (dpiOracleTypeNum)*1 }; }
#line 23 "not-num-const"
void __cgo_f_23_4(void) { static const double __cgo_undefined__4 = (dpiOracleTypeNum); }
#line 23 "not-str-lit"
void __cgo_f_23_5(void) { static const char __cgo_undefined__5[] = (dpiOracleTypeNum); }
#line 24 "not-declared"
void __cgo_f_24_1(void) { __typeof__(dpiShutdownMode) *__cgo_undefined__1; }
#line 24 "not-type"
void __cgo_f_24_2(void) { dpiShutdownMode *__cgo_undefined__2; }
#line 24 "not-int-const"
void __cgo_f_24_3(void) { enum { __cgo_undefined__3 = (dpiShutdownMode)*1 }; }
#line 24 "not-num-const"
void __cgo_f_24_4(void) { static const double __cgo_undefined__4 = (dpiShutdownMode); }
#line 24 "not-str-lit"
void __cgo_f_24_5(void) { static const char __cgo_undefined__5[] = (dpiShutdownMode); }
#line 25 "not-declared"
void __cgo_f_25_1(void) { __typeof__(dpiStartupMode) *__cgo_undefined__1; }
#line 25 "not-type"
void __cgo_f_25_2(void) { dpiStartupMode *__cgo_undefined__2; }
#line 25 "not-int-const"
void __cgo_f_25_3(void) { enum { __cgo_undefined__3 = (dpiStartupMode)*1 }; }
#line 25 "not-num-const"
void __cgo_f_25_4(void) { static const double __cgo_undefined__4 = (dpiStartupMode); }
#line 25 "not-str-lit"
void __cgo_f_25_5(void) { static const char __cgo_undefined__5[] = (dpiStartupMode); }
#line 26 "not-declared"
void __cgo_f_26_1(void) { __typeof__(dpiStmt) *__cgo_undefined__1; }
#line 26 "not-type"
void __cgo_f_26_2(void) { dpiStmt *__cgo_undefined__2; }
#line 26 "not-int-const"
void __cgo_f_26_3(void) { enum { __cgo_undefined__3 = (dpiStmt)*1 }; }
#line 26 "not-num-const"
void __cgo_f_26_4(void) { static const double __cgo_undefined__4 = (dpiStmt); }
#line 26 "not-str-lit"
void __cgo_f_26_5(void) { static const char __cgo_undefined__5[] = (dpiStmt); }
#line 27 "not-declared"
void __cgo_f_27_1(void) { __typeof__(dpiStmt_getInfo) *__cgo_undefined__1; }
#line 27 "not-type"
void __cgo_f_27_2(void) { dpiStmt_getInfo *__cgo_undefined__2; }
#line 27 "not-int-const"
void __cgo_f_27_3(void) { enum { __cgo_undefined__3 = (dpiStmt_getInfo)*1 }; }
#line 27 "not-num-const"
void __cgo_f_27_4(void) { static const double __cgo_undefined__4 = (dpiStmt_getInfo); }
#line 27 "not-str-lit"
void __cgo_f_27_5(void) { static const char __cgo_undefined__5[] = (dpiStmt_getInfo); }
#line 28 "not-declared"
void __cgo_f_28_1(void) { __typeof__(dpiVar) *__cgo_undefined__1; }
#line 28 "not-type"
void __cgo_f_28_2(void) { dpiVar *__cgo_undefined__2; }
#line 28 "not-int-const"
void __cgo_f_28_3(void) { enum { __cgo_undefined__3 = (dpiVar)*1 }; }
#line 28 "not-num-const"
void __cgo_f_28_4(void) { static const double __cgo_undefined__4 = (dpiVar); }
#line 28 "not-str-lit"
void __cgo_f_28_5(void) { static const char __cgo_undefined__5[] = (dpiVar); }
#line 29 "not-declared"
void __cgo_f_29_1(void) { __typeof__(dpiVersionInfo) *__cgo_undefined__1; }
#line 29 "not-type"
void __cgo_f_29_2(void) { dpiVersionInfo *__cgo_undefined__2; }
#line 29 "not-int-const"
void __cgo_f_29_3(void) { enum { __cgo_undefined__3 = (dpiVersionInfo)*1 }; }
#line 29 "not-num-const"
void __cgo_f_29_4(void) { static const double __cgo_undefined__4 = (dpiVersionInfo); }
#line 29 "not-str-lit"
void __cgo_f_29_5(void) { static const char __cgo_undefined__5[] = (dpiVersionInfo); }
#line 30 "not-declared"
void __cgo_f_30_1(void) { __typeof__(free) *__cgo_undefined__1; }
#line 30 "not-type"
void __cgo_f_30_2(void) { free *__cgo_undefined__2; }
#line 30 "not-int-const"
void __cgo_f_30_3(void) { enum { __cgo_undefined__3 = (free)*1 }; }
#line 30 "not-num-const"
void __cgo_f_30_4(void) { static const double __cgo_undefined__4 = (free); }
#line 30 "not-str-lit"
void __cgo_f_30_5(void) { static const char __cgo_undefined__5[] = (free); }
#line 31 "not-declared"
void __cgo_f_31_1(void) { __typeof__(int) *__cgo_undefined__1; }
#line 31 "not-type"
void __cgo_f_31_2(void) { int *__cgo_undefined__2; }
#line 31 "not-int-const"
void __cgo_f_31_3(void) { enum { __cgo_undefined__3 = (int)*1 }; }
#line 31 "not-num-const"
void __cgo_f_31_4(void) { static const double __cgo_undefined__4 = (int); }
#line 31 "not-str-lit"
void __cgo_f_31_5(void) { static const char __cgo_undefined__5[] = (int); }
#line 32 "not-declared"
void __cgo_f_32_1(void) { __typeof__(sizeof(dpiSubscrMessageTable)) *__cgo_undefined__1; }
#line 32 "not-type"
void __cgo_f_32_2(void) { sizeof(dpiSubscrMessageTable) *__cgo_undefined__2; }
#line 32 "not-int-const"
void __cgo_f_32_3(void) { enum { __cgo_undefined__3 = (sizeof(dpiSubscrMessageTable))*1 }; }
#line 32 "not-num-const"
void __cgo_f_32_4(void) { static const double __cgo_undefined__4 = (sizeof(dpiSubscrMessageTable)); }
#line 32 "not-str-lit"
void __cgo_f_32_5(void) { static const char __cgo_undefined__5[] = (sizeof(dpiSubscrMessageTable)); }
#line 33 "not-declared"
void __cgo_f_33_1(void) { __typeof__(uint32_t) *__cgo_undefined__1; }
#line 33 "not-type"
void __cgo_f_33_2(void) { uint32_t *__cgo_undefined__2; }
#line 33 "not-int-const"
void __cgo_f_33_3(void) { enum { __cgo_undefined__3 = (uint32_t)*1 }; }
#line 33 "not-num-const"
void __cgo_f_33_4(void) { static const double __cgo_undefined__4 = (uint32_t); }
#line 33 "not-str-lit"
void __cgo_f_33_5(void) { static const char __cgo_undefined__5[] = (uint32_t); }
#line 1 "completed"
int __cgo__1 = __cgo__2;

full error output:
cc1: error: unrecognized command line option "-fno-lto"

**Comment by ALTree** [comment]
> Is this true or am I missing something ?

It's true. Programs using cgo require gcc 4.6, this is documented [here](https://github.com/golang/go/wiki/MinimumRequirements#cgo).

Oracle Linux 5.8 is almost 10 years old, and if they don't package 4.6 on it, it looks like you can't use cgo there.

Closing here since I've answered your question. Feel free to comment here if I've missed anything.

**Comment by ALTree** [comment]
EDIT: oh, you're using 6.8, so it's still supported by Oracle. Yet, if they don't package gcc 4.6 for it, you can't use cgo on it.

**Comment by hurrycaine** [comment]
I am getting same for RHEL6 build agent I have.  gcc 4.4 is what comes with RHEL6, I understand RHEL6 is EOL or very close but  I don't thinks this is well documented issue. 

I have some code that is using **only std library** and it wont build on this RHEL6 server. I did not realize net package and os/user use cgo. I think I read that you can force net to be pure go but not sure about os/user?

This is the commit that adds 
https://github.com/golang/go/commit/24e9707cbfa6b1ed6abdd4b11f9ddaf3aac5ad88#diff-69d50bf3421265a97088019ef91db3994947348019dd209bad8c6b8ba21380c6

There are 3 listed fixes. All 3 are related to adding CGO_CFLAGS='-flto ... 
There was no mention of enforcing -flto for all, perhaps I missed it? 1 of the 3 the fix did not work 
https://github.com/golang/go/issues/43505


The following gcc packages are available as the default compiler:
RHEL8 : gcc 8.X or gcc 9.X in app stream.
RHEL7 : gcc 4.8.x
RHEL6 : gcc 4.4.x
RHEL5 : gcc 4.1.x
