### ISSUE TITLE
panic before main.main on macos:10.15.6  

### ISSUE THREAD

**Issue by sydnash** [golang/go#48243]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sydnash/Library/Caches/go-build"
GOENV="/Users/sydnash/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/sydnash/Documents/gowork/pkg/mod"
GONOPROXY="*xiaoduoai.com,*xiaoduotech.com"
GONOSUMDB="*xiaoduoai.com,*xiaoduotech.com"
GOOS="darwin"
GOPATH="/Users/sydnash/Documents/gowork"
GOPRIVATE="*xiaoduoai.com,*xiaoduotech.com"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/sydnash/work/code/src/gitlab.xiaoduoai.com/ecrobot/trump-coach/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g1/z086zczn0259wyqt_bfwrvb40000gn/T/go-build39857465=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

main.go
```go
package main

import (
	"fmt"

	_ "github.com/apache/pulsar-client-go/pulsar"
	_ "github.com/fatih/color"
)

func main() {
	fmt.Println("hello world")
}
```

go run main.go

### What did you expect to see?

i want see:  
       hello world

### What did you see instead?
  go run main.go
1# github.com/keybase/go-keychain
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff7267070a]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff7267070a
stack: frame={sp:0x7ffeefbff678, fp:0x7ffeefbff6c8} stack=[0x7ffeefb80718,0x7ffeefbff780)
0x00007ffeefbff578:  0x01007ffeefbff598  0x0000000000000004
0x00007ffeefbff588:  0x000000000000001f  0x00007fff7267070a
0x00007ffeefbff598:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff5a8:  0x0000000004034dd1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff648
0x00007ffeefbff5b8:  0x00000000045adef2  0x00007ffeefbff600
0x00007ffeefbff5c8:  0x0000000004035088 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000000498f220
0x00007ffeefbff5d8:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff5e8:  0x00007ffeefbff648  0x0000000004034dd1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff5f8:  0x000000000498f220  0x00007ffeefbff638
0x00007ffeefbff608:  0x0000000004035010 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff618
0x00007ffeefbff618:  0x0000000004035040 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000000498f220
0x00007ffeefbff628:  0x0000000004034dd1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff648
0x00007ffeefbff638:  0x00007ffeefbff668  0x0000000004034dd1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff648:  0x00007ffeefbff650  0x0000000004034e00 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff658:  0x00000000045b4fc8  0x000000000000002a
0x00007ffeefbff668:  0x00007ffeefbff6b8  0x000000000404a5d6 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff678: <0x00000000045b4fc8  0x000000c000034000
0x00007ffeefbff688:  0x00007ffeefbff6f8  0x0000000004027446 <runtime.(*mheap).allocSpan+0x0000000000000546>
0x00007ffeefbff698:  0x000000c0001e0000  0x0000000000006000
0x00007ffeefbff6a8:  0x000000c000000008  0x0000000200000001
0x00007ffeefbff6b8:  0x00007ffeefbff700 !0x00007fff7267070a
0x00007ffeefbff6c8: >0x00007ffeefbff700  0x0000000004930000
0x00007ffeefbff6d8:  0x00000000000007e4  0x0000000004164105 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff6e8:  0x000000000406653f <runtime.syscall+0x000000000000001f>  0x000000c000179bf0
0x00007ffeefbff6f8:  0x00007ffeefbff740  0x000000c000179bc0
0x00007ffeefbff708:  0x00000000040643b0 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000003
0x00007ffeefbff718:  0x0000000004008000 <runtime.(*cpuProfile).addExtra+0x0000000000000200>  0x8000000000000030
0x00007ffeefbff728:  0x000000000498f220  0x00000000049c2760
0x00007ffeefbff738:  0x0000000000000468  0x000000c0000001a0
0x00007ffeefbff748:  0x00000000040624c9 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff758:  0x0000000004655318  0x000000000498f220
0x00007ffeefbff768:  0x00007ffeefbff7b8  0x00000000040623c5 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff778:  0x000000000406237d <runtime.rt0_go+0x000000000000013d>
runtime.throw({0x45b4fc8, 0xc000034000})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff7267070a
stack: frame={sp:0x7ffeefbff678, fp:0x7ffeefbff6c8} stack=[0x7ffeefb80718,0x7ffeefbff780)
0x00007ffeefbff578:  0x01007ffeefbff598  0x0000000000000004
0x00007ffeefbff588:  0x000000000000001f  0x00007fff7267070a
0x00007ffeefbff598:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff5a8:  0x0000000004034dd1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff648
0x00007ffeefbff5b8:  0x00000000045adef2  0x00007ffeefbff600
0x00007ffeefbff5c8:  0x0000000004035088 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000000498f220
0x00007ffeefbff5d8:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff5e8:  0x00007ffeefbff648  0x0000000004034dd1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff5f8:  0x000000000498f220  0x00007ffeefbff638
0x00007ffeefbff608:  0x0000000004035010 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff618
0x00007ffeefbff618:  0x0000000004035040 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000000498f220
0x00007ffeefbff628:  0x0000000004034dd1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff648
0x00007ffeefbff638:  0x00007ffeefbff668  0x0000000004034dd1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff648:  0x00007ffeefbff650  0x0000000004034e00 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff658:  0x00000000045b4fc8  0x000000000000002a
0x00007ffeefbff668:  0x00007ffeefbff6b8  0x000000000404a5d6 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff678: <0x00000000045b4fc8  0x000000c000034000
0x00007ffeefbff688:  0x00007ffeefbff6f8  0x0000000004027446 <runtime.(*mheap).allocSpan+0x0000000000000546>
0x00007ffeefbff698:  0x000000c0001e0000  0x0000000000006000
0x00007ffeefbff6a8:  0x000000c000000008  0x0000000200000001
0x00007ffeefbff6b8:  0x00007ffeefbff700 !0x00007fff7267070a
0x00007ffeefbff6c8: >0x00007ffeefbff700  0x0000000004930000
0x00007ffeefbff6d8:  0x00000000000007e4  0x0000000004164105 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff6e8:  0x000000000406653f <runtime.syscall+0x000000000000001f>  0x000000c000179bf0
0x00007ffeefbff6f8:  0x00007ffeefbff740  0x000000c000179bc0
0x00007ffeefbff708:  0x00000000040643b0 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000003
0x00007ffeefbff718:  0x0000000004008000 <runtime.(*cpuProfile).addExtra+0x0000000000000200>  0x8000000000000030
0x00007ffeefbff728:  0x000000000498f220  0x00000000049c2760
0x00007ffeefbff738:  0x0000000000000468  0x000000c0000001a0
0x00007ffeefbff748:  0x00000000040624c9 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff758:  0x0000000004655318  0x000000000498f220
0x00007ffeefbff768:  0x00007ffeefbff7b8  0x00000000040623c5 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff778:  0x000000000406237d <runtime.rt0_go+0x000000000000013d>
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall, locked to thread]:
syscall.syscall(0x4164100, 0x1, 0x40487413, 0xc000179c80)
	/usr/local/go/src/runtime/sys_darwin.go:22 +0x3b fp=0xc000179bf0 sp=0xc000179bd0 pc=0x406115b
syscall.syscall(0x40a2306, 0xc000179c68, 0xc000179ca8, 0x40a2238)
	<autogenerated>:1 +0x26 fp=0xc000179c38 sp=0xc000179bf0 pc=0x4066d06
golang.org/x/sys/unix.ioctl(0x45a1361, 0x4, 0x1000004515200)
	/Users/sydnash/Documents/gowork/pkg/mod/golang.org/x/sys@v0.0.0-20210228012217-479acdf4ea46/unix/zsyscall_darwin_amd64.go:690 +0x39 fp=0xc000179c68 sp=0xc000179c38 pc=0x4163d99
golang.org/x/sys/unix.IoctlGetTermios(...)
	/Users/sydnash/Documents/gowork/pkg/mod/golang.org/x/sys@v0.0.0-20210228012217-479acdf4ea46/unix/ioctl.go:73
github.com/mattn/go-isatty.IsTerminal(0x45a1361)
	/Users/sydnash/Documents/gowork/pkg/mod/github.com/mattn/go-isatty@v0.0.12/isatty_bsd.go:10 +0x50 fp=0xc000179cd8 sp=0xc000179c68 pc=0x440bf10
github.com/fatih/color.init()
	/Users/sydnash/Documents/gowork/pkg/mod/github.com/fatih/color@v1.10.0/color.go:21 +0x7a fp=0xc000179d10 sp=0xc000179cd8 pc=0x440bfba
runtime.doInit(0x4936e40)
	/usr/local/go/src/runtime/proc.go:6498 +0x123 fp=0xc000179e48 sp=0xc000179d10 pc=0x40444e3
runtime.doInit(0x49331e0)
	/usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc000179f80 sp=0xc000179e48 pc=0x4044431
runtime.main()
	/usr/local/go/src/runtime/proc.go:238 +0x1e6 fp=0xc000179fe0 sp=0xc000179f80 pc=0x4037426
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000179fe8 sp=0xc000179fe0 pc=0x40646a1
exit status 2

**Comment by cherrymui** [comment]
Could you try updating golang.org/x/sys? Thanks.

Closing as a dup of #47776.

**Comment by sydnash** [comment]
it's worked for me.  thanks.
