### ISSUE TITLE
x/website: write a guide for fuzzing

### ISSUE THREAD

**Issue by jayconrod** [golang/go#48255]
We expect to have many users that are encountering fuzzing for the first time. We should write a thorough guide on how to use fuzzing effectively with that audience in mind.

An introductory guide should cover, at minimum:

* What fuzzing is.
* What fuzzing is good for (and not good for).
* How to write a fuzz target.
* How to run fuzzing with `go test -fuzz=target`, with information about relevant flags.
* What to do with a crasher if one is found
* Strategies for helping the fuzzer if it isn't finding any crashers after running for a while
* Current limitations of the native fuzzing support (e.g. it stops running after the first crash is found, it isn't currently supported to easily integrate with CI)

Some advanced topics that could be covered in other guides:

* Choosing a good seed corpus.
* Measuring coverage.
* Differential fuzzing.
* Fuzzing continuously.

**Comment by jayconrod** [comment]
We should reconsider what documentation should be part of the go command and where that should be located. Currently, I'm thinking:

* The `testing` package documentation should have a section on writing a fuzz target. It should explain the signature for the fuzz target (must take a `*testing.F`), what it must do (call `F.Add` then `F.Fuzz`), and what `testing` will do with it when fuzzing is enabled and disabled. This is meant to be reference documentation.
* `go help test` and `go help testflag` should explain all flags, including those related to fuzzing. They should be kept brief, pointing to other sources for more explanation.
* One or more guides on the website should tie this all together. Most users should read those first.
* We should delete `go help fuzz`. It will be redundant with the guides.

**Comment by toothrot** [comment]
Checking in on this issue as it's labeled a release blocker for Go 1.18. Is there any update?

**Comment by jayconrod** [comment]
Not yet. There are a lot of fuzzing issues. We'll get to them as soon as we can.

This one can be done during the freeze.

**Comment by toothrot** [comment]
@katiehockman Checking in on this as a release-blocking issue. Is there more left to do here?

**Comment by katiehockman** [comment]
There is more to do on it, and it's in progress. I can remove the release-blocker label though, as we'll keep working on it and get as much done before the release as we can.

**Comment by ianlancetaylor** [comment]
@katiehockman Is there more to do here for 1.18?  Thanks.

**Comment by katiehockman** [comment]
Nope I think we're in a pretty good spot at this point, and new things can be added at any time, so it isn't really tied to a release anymore. I'll go ahead and just close this.

**Comment by ronaldpetty** [comment]
Hi @katiehockman , I see this is closed, but not sure this warrants opening a new issue.

The "go doc testing" and this page https://pkg.go.dev/testing@master#hdr-Fuzzing still are pointing to this issue. I am see its @master, but unclear if that is 1.18 or not.

> TODO(#48255): write and link to documentation that will be helpful to users
who are unfamiliar with fuzzing.

I am using "go version go1.18beta2 darwin/amd64"

I actually found this ticket because I was hoping to find if there is some 'eta' when fuzzing stops running. I am running the FuzzHex example and still running after 22 minutes on 12 cores, 64 GB.  I assume we want to test everything, but unclear am I suppose to stop it?

**Comment by katiehockman** [comment]
Feel free to file a separate issue with those documentation suggestions, just in case I can't get to it soon. Thanks for pointing that out.
