### ISSUE TITLE
cmd/compile: generic function instantiated with wrong type

### ISSUE THREAD

**Issue by korzhao** [golang/go#48253]
### What version of Go are you using (`go version`)?
go tip 1.18
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```go
package main

import (
	"fmt"
	"reflect"
)

type A[T any] struct {
	B[int]
}
type B[T any] struct {
}
func (b B[T]) Bat() {
	t := new(T)
	fmt.Println(reflect.TypeOf(t).String())
}

type Foo struct {
	A[string]
}
func main() {
	Foo{}.A.Bat()
	Foo{}.A.B.Bat()
}
```

### What did you expect to see?
```
*int
*int
```

### What did you see instead?
```
*string
*int
```

**Comment by cuonglm** [comment]
Unified IR works right:

```
$ GOEXPERIMENT=unified go run p.go
*int
*int
```
