### ISSUE TITLE
go/parser, go/types: remove support for type list syntax (cleanup)

### ISSUE THREAD

**Issue by findleyr** [golang/go#48261]
Reminder issue.

We still have some code to support the type list syntax (`interface{ type A, B }`) in go/parser and go/types.

Filing this to make sure it is cleaned up.

CC @griesemer

**Comment by toothrot** [comment]
Checking in on this issue as it's labeled a release blocker for Go 1.18. Is there any update?

**Comment by findleyr** [comment]
No update. This is a lower priority than other issues, so probably won't be done until we're in the freeze.

**Comment by griesemer** [comment]
This is now a release-blocker. For one, the compiler doesn't actually permit the type list notation anymore (the functionality is disabled) so it's unlikely for `go/parser` to encounter such code. Secondly, `go/types` reports an error if it does in fact encounter such code. So no matter how this is sliced and diced, using a type list is invalid code.

**Comment by ianlancetaylor** [comment]
@griesemer @findleyr Is there more to do here for 1.18?  Thanks.

**Comment by griesemer** [comment]
@findleyr If this is only about cleaning up/removing unused code, let's move it to 1.19.

**Comment by findleyr** [comment]
Err, sorry for the lack of response on this issue.

This was done in https://go.dev/cl/359135.
