### ISSUE TITLE
doc: update FAQ for the arrival of parametric polymorphism

### ISSUE THREAD

**Issue by robpike** [golang/go#48274]
Many sections of the FAQ need tweaking, a few need replacement. Update before release.

For example, here's a question there that needs to be rethought: "Why does Go not have generic types?"

**Comment by dmitshur** [comment]
[CL 374215](https://go.dev/cl/374215) resolves this issue, but isn't to be submitted until Go 1.18 is released.

~Since there's nothing more to do here during 1.18 cycle, moving to 1.19 and adding early-in-cycle.~ Actually, we also have #49938 tracking this task, so we can can close this one.
