### ISSUE TITLE
Can you consider adding the ternary operator(?:) in the future?

### ISSUE THREAD

**Issue by WowYouCanReallyDance** [golang/go#48272]
that's so bad writting a lot if-else and define a local variable before return. so bad...

**Comment by ALTree** [comment]
See https://golang.org/doc/faq#Control_flow.

Also this has been asked in the past, see for example #39612 and others, this thread doesn't add anything to the past discussion, so I'm closing here as a dup.

**Comment by WowYouCanReallyDance** [comment]
The people who maintain this language must be a bunch of megalomaniacs, I'm sorry I don't see the future of ternary operator in Golang, I won't be using this language.

**Comment by WowYouCanReallyDance** [comment]
Just tell me which you want?
`
func Factorial(num int) int {
	return num * (num == 1 ? 1 : Factorial(num - 1))
}
`

`
func Factorial(num int) int {
	if num == 1 {
		return num * 1
	} else {
		return num * Factorial(num - 1)
	}
}
`

**Comment by ALTree** [comment]
@WowYouCanReallyDance personally, I prefer the second one, and I tend to write code like that even in languages with a ternary operator (like C).

**Comment by WowYouCanReallyDance** [comment]
@ALTree This is really a sad story, I have to say, no ternary operator is a great regret. It exists in almost all modern or older languages, and abuse is not a good reason to reject it.
