### ISSUE TITLE
x/tools/cmd/vet: warn about unused non-exported functions

### ISSUE THREAD

**Issue by griesemer** [golang/go#4827]
<pre>It's common to leave dead functions in larger packages as a result of refactoring over
time. go vet could issue warnings (some functions we may want to leave for debugging).

More generally, this could apply to all top-level consts, types, vars, and funcs - at
least to some extent.</pre>

**Comment by dhananjay92** [comment]
Do we need this? If so, I could work on it in 1.9. Let me know.

**Comment by minux** [comment]
IMHO, probably ok as an optional vet check, but as gri mentioned, it will
give false positive on debug functions, so we can't make it part of the
default checks.

Also note the check has to take test files and excluded files (via build
tags) into consideration too. Such a test would be nice, but I think it's
too complicated to get 100% right.

**Comment by robpike** [comment]
I think it's probably too hard to get the false positives rate low enough in the real world.

It might work as a lint check, which can be looser.

Closing.

**Comment by rsc** [comment]
I think that might be too much even for lint, but if anyone does want this check, 
https://github.com/dominikh/go-unused already does it.
