### ISSUE TITLE
runtime: add "maymorestack" hook for testing stack growth prologues

### ISSUE THREAD

**Issue by aclements** [golang/go#48297]
I plan to add a debugging hook for internal use that will be invoked in the prologue of any function that *may* call morestack (the stack growth function). This is inspired by the preemption bugs that led to #47302, #47304, and #47441.

In general, testing around morestack is difficult because almost all Go functions can potentially call morestack, but very few do at run time, and which ones do are highly unpredictable. As a result, if a particular function is incorrectly sensitive to whether morestack gets invoked (either to grow the stack or to preempt), it's highly unlikely that general testing will actually trigger the morestack path in that function.

The hook function will be called unconditionally before the stack bound check in any function that could call morestack. This particular placement means the hook can inject preemption or stack growth by simply setting the stack bound to a poisoned value and returning, since the stack bound check will then fail and enter morestack.

This hook is also useful for more precise lock order checking because it lets us model functions that "may" acquire any of the locks acquired by morestack. These are lock edges we only see in the rare cases where morestack is actually called, but lie latent in any function that could call it.

**Comment by ianlancetaylor** [comment]
> The hook function will be called unconditionally before the stack bound check in any function that could call morestack. 

How do you plan to make this happen?  Presumably we don't want to always call the hook in every function.  Perhaps I misunderstand.

**Comment by aclements** [comment]
I plan to always call the hook in every function. The hook call will only be added if the debug option is supplied, so the performance isn't really an issue. And, in fact, I've already implemented this and it has shockingly little performance impact. Unless you were thinking of some other problem?

**Comment by ianlancetaylor** [comment]
How is the debug option supplied?

**Comment by aclements** [comment]
In my current prototype, the compiler takes it as a -d=maymorestack=<symbol> argument and the assembler takes it as -maymorestack=<symbol> (because it doesn't have an equivalent of -d). So, e.g., you can supply the preemption-testing hook as

    GOFLAGS="-gcflags=runtime=-d=maymorestack=runtime.mayMoreStackPreempt -asmflags=runtime=-maymorestack=runtime.mayMoreStackPreempt"

But I'm happy to change this.

**Comment by ianlancetaylor** [comment]
That seems fine.  Thanks.  I just didn't find the original description very clear.  We have various different kinds of debugging hooks (e.g., `GODEBUG`).

**Comment by go101** [comment]
How to use use this option in go commands?
I didn't get the answer by reading the code.
`-gcflags=-d=maymorestack`?
Or another way?

**Comment by aclements** [comment]
@go101, see the [comments added in CL 359796](https://go-review.googlesource.com/c/go/+/359796/7/src/runtime/debug.go#64). Your usage is close, but you have to also specify which maymorestack hook function to use: `-gcflags=-d=maymorestack=X` where `X` is a function that can be used as a maymorestack hook, of which there are now two in runtime/debug.go.

**Comment by go101** [comment]
Thanks. Got it and make it work for a custom function. Cool feature!

**Comment by go101** [comment]
Er, it looks I misunderstood this option. I though the hook will be called when stacks grow. In fact, it is not.

**Comment by aclements** [comment]
@go101, right, it's called whenever they *might* grow. It's really intended as a way for us to amplify the rare things that happen when that path is (fairly unpredictably) taken. Hence the hooks to "always preempt" and "always move the stack". I'd also like to hook this up with the static lock rank checker so we can mark locks that *could be* taken by morestack if the conditions were right, but haven't gotten to that.
