### ISSUE TITLE
cmd/go:  incorrect DW_AT_comp_dir of package runtime/cgo in section .debug_info

### ISSUE THREAD

**Issue by zhouguangyuan0718** [golang/go#48319]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes.

### What operating system and processor architecture are you using (`go env`)?
Two go toolchains are installed on the same mechine, and they are almost the same expect for the `GOROOT` and `GOTOOLDIR`.
The details about the first go toolchain (henceforce called "toolchain1") are as follows：

<details><summary><code>~/goroot1/bin/go</code> Output</summary><br><pre>
$ ~/goroot1/bin/go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/mnt/h/1.code/02.Project/godev/cgodwarf/goroot1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1739691040=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

The details about the second go toolchain (henceforce called "toolchain2") are as follows：
<details><summary><code>~/goroot2/bin/go</code> Output</summary><br><pre>
$ ~/goroot2/bin/go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/mnt/h/1.code/02.Project/godev/cgodwarf/goroot2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/mnt/h/1.code/02.Project/godev/cgodwarf/goroot2/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2229440232=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
hello.go:
```go
package main

import _ "plugin" // to import runtime/cgo

func main() {
	println("hello")
}
```
The "hello.go" was built separately with the "toolchain1" and "toolchain2".
<pre>
$ ~/goroot1/bin/go build  -buildmode=pie -o hello  hello.go
$  readelf --debug-dump=info hello |grep DW_AT_comp_dir|grep src/runtime/cgo
    <61a4d>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <61f0e>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <62562>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <63261>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <63bdd>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <64193>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <6461d>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <650b3>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <65609>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <65b4c>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <66402>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo

$ ~/goroot2/bin/go build  -buildmode=pie -o hello  hello.go
$  readelf --debug-dump=info hello |grep DW_AT_comp_dir|grep src/runtime/cgo
    <61a4d>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <61f0e>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <62562>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <63261>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <63bdd>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <64193>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <6461d>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <650b3>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <65609>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <65b4c>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
    <66402>   DW_AT_comp_dir    : (indirect string, offset: 0x380): /mnt/h/1.code/02.Project/godev/cgodwarf/goroot1/src/runtime/cgo
</pre>

### What did you expect to see?
When the "hello.go" was built with "toolchain1" , the DW_AT_comp_dir of runtime/cgo in binary was expected to be "……/goroot1/src/runtime/cgo".
When the "hello.go" was built with "toolchain2" , the DW_AT_comp_dir of runtime/cgo in binary was expected to be "……/goroot2/src/runtime/cgo".

### What did you see instead?
When the "hello.go" was built with "toolchain1" and "toolchain2", the DW_AT_comp_dir of runtime/cgo is always "……/goroot1/src/runtime/cgo".

**Comment by thanm** [comment]
@bcmills @jayconrod

**Comment by zhouguangyuan0718** [comment]
[build_cgo_compdir.txt](https://github.com/golang/go/files/7184927/build_cgo_compdir.txt)

**Comment by zhouguangyuan0718** [comment]
The C objects file in runtime/cgo:

<pre>
root@DESKTOP-S0J32Q2:/mnt/h/1.code/7.godev/go/pkg/linux_amd64/runtime# ar -x cgo.a
root@DESKTOP-S0J32Q2:/mnt/h/1.code/7.godev/go/pkg/linux_amd64/runtime# objdump --dwarf=rawline  _x006.o

_x006.o:     file format elf64-x86-64

Raw dump of debug contents of section .debug_line:

  Offset:                      0x0
  Length:                      675
  DWARF Version:               3
  Prologue Length:             421
  Minimum Instruction Length:  1
  Initial value of 'is_stmt':  1
  Line Base:                   -5
  Line Range:                  14
  Opcode Base:                 13

 Opcodes:
  Opcode 1 has 0 args
  Opcode 2 has 1 arg
  Opcode 3 has 1 arg
  Opcode 4 has 1 arg
  Opcode 5 has 1 arg
  Opcode 6 has 0 args
  Opcode 7 has 0 args
  Opcode 8 has 0 args
  Opcode 9 has 1 arg
  Opcode 10 has 0 args
  Opcode 11 has 0 args
  Opcode 12 has 1 arg

 The Directory Table (offset 0x1b):
  1     /usr/include/x86_64-linux-gnu/bits
  2     /usr/lib/gcc/x86_64-linux-gnu/9/include
  3     /usr/include
  4     /usr/include/x86_64-linux-gnu/bits/types

 The File Name Table (offset 0x9d):
  Entry Dir     Time    Size    Name
  1     0       0       0       gcc_linux_amd64.c
  2     1       0       0       types.h
  3     2       0       0       stddef.h
  4     3       0       0       time.h
  5     1       0       0       pthreadtypes.h
  6     4       0       0       __sigset_t.h
  7     4       0       0       sigset_t.h
  8     3       0       0       signal.h
  9     3       0       0       stdint.h
  10    4       0       0       struct_FILE.h
  11    4       0       0       FILE.h
  12    3       0       0       stdio.h
  13    1       0       0       sys_errlist.h
  14    0       0       0       libcgo.h
  15    3       0       0       stdlib.h
  16    1       0       0       sigthread.h
  17    3       0       0       pthread.h
  18    0       0       0       libcgo_unix.h
  19    3       0       0       string.h
  20    3       0       0       errno.h
………………………………
</pre>
<pre>
 objdump --dwarf=info  _x006.o|grep DW_AT_comp_dir
    <15>   DW_AT_comp_dir    : (indirect string, offset: 0x1ce): /mnt/h/1.code/7.godev/go/src/runtime/cgo
</pre>


The go binary:
<pre>
objdump --dwarf=rawline hello

hello:     file format elf64-x86-64

Raw dump of debug contents of section .zdebug_line:

  Offset:                      0x0
  Length:                      560
  DWARF Version:               2
  Prologue Length:             378
  Minimum Instruction Length:  1
  Initial value of 'is_stmt':  1
  Line Base:                   -4
  Line Range:                  10
  Opcode Base:                 11

 Opcodes:
  Opcode 1 has 0 args
  Opcode 2 has 1 arg
  Opcode 3 has 1 arg
  Opcode 4 has 1 arg
  Opcode 5 has 1 arg
  Opcode 6 has 0 args
  Opcode 7 has 0 args
  Opcode 8 has 0 args
  Opcode 9 has 1 arg
  Opcode 10 has 0 args

 The Directory Table (offset 0x19):
  1     /mnt/h/1.code/7.godev/go/src/sync
  2     /mnt/h/1.code/7.godev/go/src/sync/atomic
  3     /mnt/h/1.code/7.godev/go/src/internal/race
  4     /mnt/h/1.code/7.godev/go/src/runtime

 The File Name Table (offset 0xb5):
  Entry Dir     Time    Size    Name
  1     0       0       0       <autogenerated>
  2     1       0       0       cond.go
  3     1       0       0       mutex.go
  4     1       0       0       runtime2.go
  5     1       0       0       map.go
  6     2       0       0       value.go
  7     1       0       0       once.go
  8     1       0       0       pool.go
  9     1       0       0       poolqueue.go
  10    1       0       0       rwmutex.go
  11    1       0       0       waitgroup.go
  12    1       0       0       runtime.go
  13    2       0       0       doc.go
  14    3       0       0       norace.go
  15    4       0       0       debug.go
  16    4       0       0       alg.go
………………
<pre>
<pre>
objdump --dwarf=info hello|grep DW_AT_comp_dir
    <22>   DW_AT_comp_dir    : .
    <28f>   DW_AT_comp_dir    : .
    <2852>   DW_AT_comp_dir    : .
    <29d1>   DW_AT_comp_dir    : .
    <312c>   DW_AT_comp_dir    : .
    <31ef>   DW_AT_comp_dir    : .
    <32c6>   DW_AT_comp_dir    : .
    <34bb>   DW_AT_comp_dir    : .
    <36b7>   DW_AT_comp_dir    : .
    <38e2>   DW_AT_comp_dir    : .
    <10581>   DW_AT_comp_dir    : .
    <10875>   DW_AT_comp_dir    : .
    <10ac3>   DW_AT_comp_dir    : .
    <10b73>   DW_AT_comp_dir    : .
    <10c11>   DW_AT_comp_dir    : .
    <10ce2>   DW_AT_comp_dir    : .
    <1177d>   DW_AT_comp_dir    : .
    <1182d>   DW_AT_comp_dir    : .
    <11929>   DW_AT_comp_dir    : .
    <119e6>   DW_AT_comp_dir    : .
    <11acb>   DW_AT_comp_dir    : .
    <11c11>   DW_AT_comp_dir    : .
objdump: Error: LEB value too large
    <4d247>   DW_AT_comp_dir    : .
    <4d96b>   DW_AT_comp_dir    : .
    <4da35>   DW_AT_comp_dir    : .
    <4db07>   DW_AT_comp_dir    : .
    <5f90e>   DW_AT_comp_dir    : (indirect string, offset: 0xe): /tmp/go-build
    <5f99c>   DW_AT_comp_dir    : (indirect string, offset: 0xe): /tmp/go-build
    <600de>   DW_AT_comp_dir    : (indirect string, offset: 0xe): /tmp/go-build
    <6016c>   DW_AT_comp_dir    : (indirect string, offset: 0xe): /tmp/go-build
    <601bb>   DW_AT_comp_dir    : (indirect string, offset: 0x39a): /mnt/h/1.code/7.godev/go/src/runtime/cgo
    <6067c>   DW_AT_comp_dir    : (indirect string, offset: 0x39a): /mnt/h/1.code/7.godev/go/src/runtime/cgo
    <60cd0>   DW_AT_comp_dir    : (indirect string, offset: 0x39a): /mnt/h/1.code/7.godev/go/src/runtime/cgo
    <619cf>   DW_AT_comp_dir    : (indirect string, offset: 0x39a): /mnt/h/1.code/7.godev/go/src/runtime/cgo
    <6234b>   DW_AT_comp_dir    : (indirect string, offset: 0x39a): /mnt/h/1.code/7.godev/go/src/runtime/cgo
    <62901>   DW_AT_comp_dir    : (indirect string, offset: 0x39a): /mnt/h/1.code/7.godev/go/src/runtime/cgo
    <62d8b>   DW_AT_comp_dir    : (indirect string, offset: 0x39a): /mnt/h/1.code/7.godev/go/src/runtime/cgo
    <63821>   DW_AT_comp_dir    : (indirect string, offset: 0x39a): /mnt/h/1.code/7.godev/go/src/runtime/cgo
    <63d77>   DW_AT_comp_dir    : (indirect string, offset: 0x39a): /mnt/h/1.code/7.godev/go/src/runtime/cgo
    <642ba>   DW_AT_comp_dir    : (indirect string, offset: 0x39a): /mnt/h/1.code/7.godev/go/src/runtime/cgo
    <64b70>   DW_AT_comp_dir    : (indirect string, offset: 0x39a): /mnt/h/1.code/7.godev/go/src/runtime/cgo
</pre>


The dwarfinfo of go files is different from c files.

The DW_AT_comp_dir   of go files is always ".". But there is absolutely path in  The Directory Table in debug_line， which is generated by linker. 
The DW_AT_comp_dir   of C files is always absolutely path. But there is relative path in  The Directory Table in debug_line， which is compiled by gcc and linker by gcc.

So it's can't be replace GOROOT to fix path with  -fdebug-prefix-map.
what we can do is to judge if any C source files exist in the package in GOROOT will be compiled or not, then the go execute will know it should use cache or not.

**Comment by zhouguangyuan0718** [comment]
[build_cgo_compdir.txt](https://github.com/golang/go/files/7186934/build_cgo_compdir.txt)

**Comment by bcmills** [comment]
Reconsidering this in the context of #50183: the `DW_AT_comp_dir` DIE in particular is supposed to indicate “the current working directory at compile time”, which for a C dependency of a Go program is not meaningful: the actual working directory of a C compile is a throwaway temp directory.

I think it _is_ important for reproducibility that the value of `DW_AT_comp_dir` be deterministic and well-defined, but I don't think it's important that it be any specific actual directory.
