### ISSUE TITLE
cmd/compile: struct field tag not working when use generics

### ISSUE THREAD

**Issue by nzlov** [golang/go#48317]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-c69f5c0d76 Fri Sep 10 10:45:59 2021 +0000 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nzlov/Library/Caches/go-build"
GOENV="/Users/nzlov/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/nzlov/workspace/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/nzlov/workspace/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Users/nzlov/program/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/nzlov/program/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="devel go1.18-c69f5c0d76 Fri Sep 10 10:45:59 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/nzlov/workspace/vgo/generices/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/71/4t6lk06x5y77f2wyln9vqnlw0000gn/T/go-build147050757=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```
package main

import (
	"encoding/json"
	"fmt"
)

type A[T any] struct {
	Name string `json:"name"`
	Data T `json:"d"`
	ErrResp ErrResp `json:"errorResponse"`
}

type ErrResp struct {
	Age int `json:"age"`
}

func main() {
	fmt.Printf("%+v\n", *a[int]())
}

func a[T any]() *T {

	data :=`{"name":"name","d":1,"errorResponse":{"age":10}}`
	a1 := A[T]{}
	 err := json.Unmarshal([]byte(data), &a1)
	if err!=nil{
		panic(err)
	}
	fmt.Printf("%+v\n",a1)
	return &a1.Data
}
```

### What did you expect to see?
```
{Name:name Data:1 ErrResp:{Age:10}}
```

### What did you see instead?
```
{Name:name Data:0 ErrResp:{Age:0}}
```

### Fix:

1.  use env `GOEXPERIMENT=unified`
2. return Unmarshal obj. like `ex1`
3. use full field name. like `ex2`

### Work examples:
1.
```
package main

import (
	"encoding/json"
	"fmt"
)

type A[T any] struct {
	Name string `json:"name"`
        Data T `json:"d"`
	ErrResp ErrResp `json:"errorResponse"`
}

type ErrResp struct {
	Age int `json:"age"`
}

func main() {
	fmt.Printf("%+v\n", *a[int]())
}

func a[T any]() *A[T] {
	data :=`{"name":"name","d":1,"errorResponse":{"age":10}}
	a1 := A[T]{}
	err := json.Unmarshal([]byte(data), &a1)
	if err!=nil{
		panic(err)
	}
	fmt.Printf("%+v\n",a1)
	return &a1  // <---- return Unmarshal obj
}
```

2.
```
package main

import (
	"encoding/json"
	"fmt"
)

type A[T any] struct {
	Name string `json:"name"`
        Data T `json:"data"`
	ErrorResponse ErrResp `json:"errorResponse"`  // <---- use full name
}

type ErrResp struct {
	Age int `json:"age"`
}

func main() {
	fmt.Printf("%+v\n", *a[int]())
}

func a[T any]() *T {

	data :=`{"name":"name","data":1,"errorResponse":{"age":10}}`
 	a1 := A[T]{}
 	err := json.Unmarshal([]byte(data), &a1)
 	if err!=nil{
		panic(err)
 	}
 	fmt.Printf("%+v\n",a1)
 	return &a1.Data
}
```

**Comment by thanm** [comment]
@randall77 @danscales
