### ISSUE TITLE
io: Seeker documentation does not match implementations

### ISSUE THREAD

**Issue by bcmills** [golang/go#48316]
### What version of Go are you using (`go version`)?

`go1.17`

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

Read https://pkg.go.dev/io@go1.17#Seeker. Compare the behavior it requires to the implementations of that interface in the standard library.

### What did you expect to see?

Behavior matching the documentation (emphasis mine).

> Seek sets the offset for the next Read or Write to offset, interpreted according to whence: SeekStart means relative to the start of the file, SeekCurrent means relative to the current offset, and SeekEnd means relative to the end. <strong>Seek returns the new offset relative to the start of the file and an error, if any.</strong>

The use of “and” here implies that implementations must return the current offset regardless of any error.

> Seeking to an offset before the start of the file is an error. <strong>Seeking to any positive offset is legal,</strong> but the behavior of subsequent I/O operations on the underlying object is implementation-dependent.

To me, “is legal” implies “does not result in an error”.

### What did you see instead?

Many implementations reject positive offsets that exceed the size of the entity being read:
* `debug/elf.readSeekerFromReader`: https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/debug/elf/reader.go#L80
* `embed.openFile`: https://github.com/golang/go/blob/90c5660616d7f006ca62adfec49310bf40e3b354/src/embed/embed.go#L371
* `testing/fstest.openMapFile`: https://github.com/golang/go/blob/213e157d3aad3fbb289d184a5cb4b18258162634/src/testing/fstest/mapfs.go#L194
* `io.SectionReader` has a particularly subtle variation on this. It represents the offset relative to the base of the section being read and fails to detect overflow: https://github.com/golang/go/blob/90c5660616d7f006ca62adfec49310bf40e3b354/src/io/io.go#L519
   * That means that it accepts _most_ positive offsets, but still rejects very large ones (https://play.golang.org/p/Rkk3LNhg129).

It isn't obvious to me whether `os.File.Seek` ever rejects positive offsets, since it passes the offset through to a platform-specific system call.

On error (for example, when the offset overflows or is otherwise invalid, or when an underlying system call fails), most implementations return `0` instead of “the new offset relative to the start of the file”.

* `bytes.Reader`: https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/bytes/reader.go#L131
* `debug/elf.readSeekerFromReader`: https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/debug/elf/reader.go#L81
* `embed.openFile`: https://github.com/golang/go/blob/90c5660616d7f006ca62adfec49310bf40e3b354/src/embed/embed.go#L372
* `os.File`: https://github.com/golang/go/blob/a25c58462992704dbb6819769f530b6cc6a8ebe3/src/os/file.go#L243
* `strings.Reader`: https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/strings/reader.go#L130
* `testing/fstest.openMapFile`: https://github.com/golang/go/blob/213e157d3aad3fbb289d184a5cb4b18258162634/src/testing/fstest/mapfs.go#L195

**Comment by bcmills** [comment]
Given that nearly every implementation in the standard library deviates from the documented `io.Seeker` behavior in the same systematic way, I think we should just update the `io.Seeker` documentation. I would suggest this wording (changes in bold):

> Seek sets the offset for the next Read or Write to offset, interpreted according to whence: SeekStart means relative to the start of the file, SeekCurrent means relative to the current offset, and SeekEnd means relative to the end. Seek returns the new offset relative to the start of the file <strike>and</strike> <b>or</b> an error, if any. <b>On error, Seek may return 0 instead of the current offset.</b>
> 
> Seeking to an offset before the start of the file is an error. Seeking to any positive offset <strike>is legal</strike> <b>may be allowed</b>, but <b>if the new offset exceeds the size of the underlying object</b> the behavior of subsequent I/O operations <strike>on the underlying object</strike> is implementation-dependent.

**Comment by bcmills** [comment]
The current clause was added in https://golang.org/cl/11403043 (along with the inconsistent `io.SectionReader` overflow behavior).

**Comment by andig** [comment]
> Seeking to any positive offset is legal

> Seeking to any positive offset is legal may be allowed, but if the new offset exceeds the size of the underlying object the behavior of subsequent I/O operations on the underlying object is implementation-dependent.

Does that mean that seeking will _never_ return an error and only error on the next io op? If that's the case- why not simply state so?

**Comment by bcmills** [comment]
> Does that mean that seeking will never return an error and only error on the next io op?

No. In practice (in ~all existing implementations), `Seek` _may or may not_ return an error for an invalid positive offset — it depends on the specific implementation and on just how invalid the offset actually is.

Some implementations return an error from `Seek` for any offset past the end of the data. Some never return an error for a positive offset as long as there is a valid underlying file, but do return an error if the file is invalid. Some return an error if the offset is “too positive” (and would overflow an internal representation).

In practice, if you want to use `Seek` correctly you should check the error from `Seek` itself but _also_ be aware that the next read may error out if the offset turned out not to be valid.

**Comment by andig** [comment]
> Seek may or may not return an error for an invalid positive offset — it depends on the specific implementation and on just how invalid the offset actually is.

In that case I could imagine the following to make it clearer: 

> If seeking to any positive offset and the new offset exceeds the size of the underlying object, then either `Seek` may error or the subsequent I/O operation depending on  implementation.
