### ISSUE TITLE
go/types, types2: better error message when using *interface instead of interface

### ISSUE THREAD

**Issue by zllangct** [golang/go#48312]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-b32209d22d Thu Sep 9 23:18:18 2021 +0000 windows/amd64
</pre>

### What did you do?
<pre>
package main

import (
	"fmt"
)

type ISetName interface {
	SetName(name string)
}

type Item struct {
	Name string
}

func (i *Item) SetName(name string)  {
	i.Name = name
}

func Hello[T ISetName]()  {
	ins := new(T)
	(ins).SetName("foo")
        fmt.Printf("%+v", ins)
}

func main() {
	Hello[Item]()
}
</pre>

### What did you expect to see?
<pre>
output: {Name:"foo"}
</pre>

### What did you see instead?
<pre>
// go version devel go1.18-b32209d22d
output:Item does not satisfy ISetName: wrong method signature
	got  func (*Item).SetName(name string)
	want func (ISetName).SetName(name string)
</pre>
<pre>
// go2go playground
output:Item does not satisfy ISetName: wrong method signature
	got  func (*Item).SetName(name string)
	want func (ISetName).SetName(name string)
</pre>

### when method 'SetName' with value receiver is ok, but pointer receiver not
<pre>
package main

import (
	"fmt"
)

type ISetName interface {
	SetName(name string)
}

type Item struct {
	Name string
}

func (i Item) SetName(name string)  {
	i.Name = name
}

func Hello[T ISetName]()  {
	ins := new(T)
	(ins).SetName("foo")
        fmt.Printf("%+v", ins)
}

func main() {
	Hello[Item]()
}
</pre>
<pre>
// go version devel go1.18-b32209d22d
output: error: cannot convert ins (variable of type *T) to ISetName
</pre>
<pre>
// go2go playground
output:&{Name:}
</pre>
It is seem that go2go playroung can work with value receiver method 'SetName', but  go version devel go1.18-b32209d22d not. 
<pre>
package main

import (
	"fmt"
)

type ISetName interface {
	SetName(name string)
}

type Item struct {
	Name string
}

func (i Item) SetName(name string)  {
	i.Name = name
}

func Hello[T ISetName]()  {
	ins := new(T)
	(*ins).SetName("foo")
        fmt.Printf("%+v", ins)
}

func main() {
	Hello[Item]()
}
</pre>
<pre>
// go version devel go1.18-b32209d22d
output: &{Name:}
</pre>

**Comment by cuonglm** [comment]
The error reported is correct, since when you call `new(T)`, this basically a pointer to interface `ISetname`. If you convert your program to non-generic, and run with go1.17, you will get a clearer error message:

```
func Hello(T ISetName) {
	ins := &T
	(ins).SetName("foo")
	fmt.Printf("%+v", ins)
}

func main() {
	Hello(&Item{})
}
```

```
$ go run t.go
./t.go:21:7: ins.SetName undefined (type *ISetName is pointer to interface, not interface)
```

Maybe we can make go/types and go/types2 produce a clearer error message.

cc @griesemer @findleyr

**Comment by griesemer** [comment]
Retitled, looking for better error message.
