### ISSUE TITLE
x/sys/windows/svc/eventlog.Open() fails with "Access Denied" on older versions of Windows Server, when compiled with latest Go v1.17.1

### ISSUE THREAD

**Issue by palladia** [golang/go#48322]
### What version of Go are you using (`go version`)?

<pre>
$ go version - 1.17.1

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

Built on Windows Server 2016, VS2017, AMD64
Problems observed on Windows Server 2008R2 and Windows Server 2012R2, AMD64

### What did you do?

Call to x/sys/windows/svc/eventlog.Open() returns "Access is denied"

### What did you expect to see?

Service is running at elevated privileges, should open without error

### What did you see instead?

On Windows Server 2008R2 and Windows Server 2012R2, calls to open eventlog fails with "Access" is denied.
This problem is not seen on newer versions of Windows Server (2016, 2019)
Problem is also not seen when compiled using Go 1.16.4. The program was running well, until upgrade to Go v1.17.1.

**Comment by thanm** [comment]
To clarify, this problem happens only with Go 1.17.1? Not with Go1.17?

**Comment by palladia** [comment]
I tested with Go 1.17.0, and same failures are seen.

**Comment by thanm** [comment]
@alexbrainman @bradfitz

**Comment by thanm** [comment]
Can you post a stand-alone example program that illustrates the problem? This would make it a lot easier to work on.

**Comment by alexbrainman** [comment]
> "Access is denied"

This error can be returned for many different reasons.

It is impossible to help here without at least a repro.

Alex

**Comment by palladia** [comment]
I will try to create a small repro program, but that might take me a while, since I don't have a Windows machine.

I can only speculate here, but is there any difference in how event log is opened in older versions of Windows vs. newer versions? I read that Go v1.17 introduced some changes to syscalls. Could that make a difference?

**Comment by palladia** [comment]
I have been unable to repro this.  Will close this for now.
