### ISSUE TITLE
go/types, types2: embedded field type cannot be a (pointer to a) type parameter

### ISSUE THREAD

**Issue by zllangct** [golang/go#48334]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-23832ba2e2 Sat Sep 11 05:05:56 2021 +0000 darwin/amd64
</pre>

### What did you do?
<pre>
package main

type A[T any] struct {
	T
}

func main(){
	_=A[int]{}
}
</pre>

### What did you expect to see?
ok
### What did you see instead?
<pre>
// go2go playground is ok, something wrong here
# command-line-arguments
./main1.go:4:2: embedded field type cannot be a (pointer to a) type parameter
</pre>

**Comment by fzipp** [comment]
This works as intended, see #43621. The go2go playground is outdated.
