### ISSUE TITLE
cmd/compiler:  internal compiler error: converting shape type to interface

### ISSUE THREAD

**Issue by mmrath** [golang/go#48344]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-0d8a4bfc96 Sun Sep 12 01:06:53 2021 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
No, using master as of today

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Compile repo at https://github.com/mmrath/validation

I am not able to reduce it to a minimal case but I'll try later tomorrow. 

### What did you expect to see?
Compile successfully or give some meaningful error

### What did you see instead?

<pre>
BAD FUNCTION
.   DCLFUNC tc(1) Iota:-1 ABI:ABIInternal FUNC-func(uintptr, *StringField[.shape.*uint8]) *StringField[.shape.*uint8] # string_field.go:72:6
.   DCLFUNC-Dcl
.   .   NAME-validation..dict tc(1) Class:PPARAM Offset:0 OnStack uintptr # string_field.go:72:6
.   .   NAME-validation.f tc(1) Class:PPARAM Offset:0 OnStack Used PTR-*StringField[.shape.*uint8] # string_field.go:72:7
.   .   NAME-validation.~r0 tc(1) Class:PPARAMOUT Offset:0 OnStack PTR-*StringField[.shape.*uint8] # string_field.go:72:37
.   DCLFUNC-body
.   .   AS tc(1) # string_field.go:73:10
.   .   .   DOT tc(1) SLICE-[]ValidationRule[.shape.*uint8] # string_field.go:73:3 validation.rules SLICE-[]ValidationRule[.shape.*uint8]
.   .   .   .   DOTPTR tc(1) Implicit validation.FieldValidator[.shape.*uint8] # struct_field.go:29:16 validation.FieldValidator validation.FieldValidator[.shape.*uint8]
.   .   .   .   .   NAME-validation.f tc(1) Class:PPARAM Offset:0 OnStack Used PTR-*StringField[.shape.*uint8] # string_field.go:72:7
.   .   .   APPEND tc(1) SLICE-[]ValidationRule[.shape.*uint8] # string_field.go:73:18 SLICE-[]ValidationRule[.shape.*uint8]
.   .   .   APPEND-Args
.   .   .   .   DOT tc(1) SLICE-[]ValidationRule[.shape.*uint8] # string_field.go:73:20 validation.rules SLICE-[]ValidationRule[.shape.*uint8]
.   .   .   .   .   DOTPTR tc(1) Implicit validation.FieldValidator[.shape.*uint8] # struct_field.go:29:16 validation.FieldValidator validation.FieldValidator[.shape.*uint8]
.   .   .   .   .   .   NAME-validation.f tc(1) Class:PPARAM Offset:0 OnStack Used PTR-*StringField[.shape.*uint8] # string_field.go:72:7
.   .   .   .   CONVIFACE tc(1) Implicit validation.ValidationRule[.shape.*uint8] # struct_field.go:29:16 validation.ValidationRule[.shape.*uint8]
.   .   .   .   .   CALL tc(1) PTR-*rule[.shape.*uint8] # string_field.go:73:43 PTR-*rule[.shape.*uint8]
.   .   .   .   .   .   FUNCINST tc(1) Implicit FUNC-func() *rule[.shape.*uint8] # string_field.go:73:40 FUNC-func() *rule[.shape.*uint8]
.   .   .   .   .   .   .   NAME-validation.notEmptyRule tc(1) Class:PFUNC Offset:0 FUNC-func[T₁₆]() *rule[validation.T₁₆] # string_field.go:14:6
.   .   .   .   .   .   FUNCINST-Targs
.   .   .   .   .   .   .   TYPE .shape.*uint8 tc(1) Offset:0 type .shape.*uint8
.   .   RETURN tc(1) # string_field.go:74:2
.   .   RETURN-Results
.   .   .   NAME-validation.f tc(1) Class:PPARAM Offset:0 OnStack Used PTR-*StringField[.shape.*uint8] # string_field.go:72:7
BAD CONVERSION
.   CONVIFACE tc(1) Implicit validation.ValidationRule[.shape.*uint8] # struct_field.go:29:16 validation.ValidationRule[.shape.*uint8]
.   .   CALL tc(1) PTR-*rule[.shape.*uint8] # string_field.go:73:43 PTR-*rule[.shape.*uint8]
.   .   .   FUNCINST tc(1) Implicit FUNC-func() *rule[.shape.*uint8] # string_field.go:73:40 FUNC-func() *rule[.shape.*uint8]
.   .   .   .   NAME-validation.notEmptyRule tc(1) Class:PFUNC Offset:0 FUNC-func[T₁₆]() *rule[validation.T₁₆] # string_field.go:14:6
.   .   .   FUNCINST-Targs
.   .   .   .   TYPE .shape.*uint8 tc(1) Offset:0 type .shape.*uint8
./struct_field.go:29:16: internal compiler error: converting shape type to interface

</pre>

**Comment by mmrath** [comment]
I was able to narrow down the issue to the code below in file `string_field.go`. If I remove this function code compiles fine

```
func (f *StringField[T]) LengthBetween(min, max int) *StringField[T] {
	f.rules = append(f.rules, lengthBetweenRule[T](min, max))
	return f
}
```

**Comment by cuonglm** [comment]
`go/types` accepts this, unified IR also build ok.

Maybe related to #47775

cc @randall77 @danscales

**Comment by korzhao** [comment]
simpler example:
```go
package main


type G[T any] interface {
	g()
}

type Foo[T any] struct {

}
func (foo *Foo[T])g()  {

}

func f[T any](){
	v := []G[T]{}
	v = append(v, &Foo[T]{})
}
func main() {
	f[int]()
}

```

**Comment by danscales** [comment]
Thanks for the issue @mmrath and the simpler example @korzhao 

OK, I understand the issue.  It relates to the automatic conversion to an interface in the append() call.    I have a fix in a much bigger change, so it will take a few days.  Just FYI, you can work around this issue for now by making the conversion to interface be explicit.  So, in the simpler example, change to:

```
   v = append(v, G[T](&Foo[T]{}))
```

**Comment by korzhao** [comment]
I used this patch and it works. @danscales 
```diff
diff --git a/src/cmd/compile/internal/noder/helpers.go b/src/cmd/compile/internal/noder/helpers.go
index 9487e76336..f728af6b6d 100644
--- a/src/cmd/compile/internal/noder/helpers.go
+++ b/src/cmd/compile/internal/noder/helpers.go
@@ -140,7 +140,7 @@ func Call(pos src.XPos, typ *types.Type, fun ir.Node, args []ir.Node, dots bool)
                // ODELETE: transformDelete requires that the arg is a map
                // OALIGNOF, OSIZEOF: can be eval'ed to a constant until types known.
                switch fun.BuiltinOp {
-               case ir.OMAKE, ir.OREAL, ir.OIMAG, ir.OAPPEND, ir.ODELETE, ir.OALIGNOF, ir.OOFFSETOF, ir.OSIZEOF:
+               case ir.OMAKE, ir.OREAL, ir.OIMAG, ir.ODELETE, ir.OALIGNOF, ir.OOFFSETOF, ir.OSIZEOF:
                        hasTParam := false
                        for _, arg := range args {
                                if fun.BuiltinOp == ir.OOFFSETOF {
@@ -158,6 +158,10 @@ func Call(pos src.XPos, typ *types.Type, fun ir.Node, args []ir.Node, dots bool)
                        if hasTParam {
                                return typed(typ, n)
                        }
+               case ir.OAPPEND:
+                       if !args[0].Type().IsSlice() {
+                               return typed(typ, n)
+                       }
                }
  
```
