### ISSUE TITLE
x/tools/gopls - "C" func optional second return value shown as type`bool` instead of `error`

### ISSUE THREAD

**Issue by avivdolev** [golang/go#48343]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
```
❯ gopls version
golang.org/x/tools/gopls v0.7.2
    golang.org/x/tools/gopls@v0.7.2 h1:kRKKdvA8GOzra8rhSFDClOR7hV/x8v0J0Vm4C/gWq8s=
```

vscode version :
```
Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:54:53.442Z (1 wk ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

vscode Go extension version `v0.27.2`

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY="github.com/twistlock/*"
GONOSUMDB="github.com/twistlock/*"
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE="github.com/twistlock/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/go/src/twistlock/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build38050727=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.17 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.17
uname -sr: Linux 5.4.0-81-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.31-0ubuntu9.2) stable release version 2.31.
gdb --version: GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
</pre></details>

### What did you do?
Editing this go file:
``` Go
package main

/*
#cgo LDFLAGS: -lm
#include <math.h>
*/
import "C"

func main() {
	n, err := C.sqrt(-1)
	println(n)
	println(err == nil)
	println(err.Error())
}
```

Or any other file that uses the second return value of a C function invocation ([documented here](https://pkg.go.dev/cmd/cgo#hdr-Go_references_to_C)) 

### What did you expect to see?
Running this with `go run` gives this output:
```
NaN
false
numerical argument out of domain
```

So no errors expected from gopls.

### What did you see instead?

gopls sees `err` as of type `bool`:

![image](https://user-images.githubusercontent.com/19855814/132983617-23d6030d-059a-485e-89ad-5d66b87338a0.png)

**Comment by stamblerre** [comment]
Can you please update your Go version to `go1.17.1`? I believe this was a 1.17 regression that was recently backported and released (https://github.com/golang/go/issues/47854).

**Comment by avivdolev** [comment]
Yes, updating to go1.17.1 resolved the issue
Thanks!
