### ISSUE TITLE
cmd/compile: internal compiler error: cannot handle alias type declaration (issue #25838): Callback

### ISSUE THREAD

**Issue by swapx** [golang/go#48353]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.15.6
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Linux

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/USER/test/bin"
GOCACHE="/home/USER/test/.cache"
GOENV="/home/USER/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/USER/test/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/epetkas/test"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/app/vbuild/RHEL7-x86_64/go/1.15.6"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/app/vbuild/RHEL7-x86_64/go/1.15.6/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=
CGO_CFLAGS=-g -O2
CGO_CPPFLAGS=
CGO_CXXFLAGS=-g -O2
CGO_FFLAGS=-g -O2
CGO_LDFLAGS=-g -O2
PKG_CONFIG=pkg-config
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build941578384=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Please see https://play.golang.org/p/5_1QLRDWwFL

### What did you expect to see?
$ go run cw_prototype.go
1. Cert updated - cert 1
Running callBack function - replace old cert with new cert: 'cert 1' in gRPC client
2. Cert updated - cert 2
Running callBack function - replace old cert with new cert: 'cert 2' in gRPC client
3. Cert updated - cert 3
Running callBack function - replace old cert with new cert: 'cert 3' in gRPC client
4. Cert updated - cert 4
Running callBack function - replace old cert with new cert: 'cert 4' in gRPC client
5. Cert updated - cert 5
Running callBack function - replace old cert with new cert: 'cert 5' in gRPC client

### What did you see instead?
$ go run cw_prototype.go
# command-line-arguments
.\cw_prototype.go:13:6: internal compiler error: cannot handle alias type declaration (issue #25838): Callback

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new

**Comment by ALTree** [comment]
Note that go 1.15 is no longer supported, only the two last versions are (right now, 1.17 and 1.16).

Anyway the 1.17 compiler crashes on this too. 

tip prints:

```
test.go:37:10: incompatible type: cannot use cw (variable of type *CertWatcher) as CertWatcherIf value
test.go:55:19: incompatible type: cannot use cw (variable of type *CertWatcher) as CertWatcherIf value
```

Which seems correct to me (so your reproducer does not compile). Possibly already fixed on tip? Do you have a reproducer that does compile?

**Comment by swapx** [comment]
Hello!
When I put the definition of the Interface in the beginning of the program, it solved the problem. Please have a look here: https://play.golang.org/p/GdQSiR2mUHf

**Comment by ALTree** [comment]
Thanks. So you don't have a program that crashes the tip compiler, I guess we can close this as fixed on tip(?)

**Comment by swapx** [comment]
Well, the first version of the program crashes the compiler. Is that an acceptable behaviour of the compiler ?

**Comment by ALTree** [comment]
This seems fixed on tip, and the first version is a program that doesn't compile anyway, so even if it does crash 1.17, I think it may not be worth a backport (to 1.17.2 for example).

**Comment by swapx** [comment]
A solution may not be required for backporting, but it should be fixed in latest version of Golang I think. Or ?

**Comment by ALTree** [comment]
After a major version is released (for example go1.17), minor releases are issued (1.17.1) following [this policy:](https://github.com/golang/go/wiki/MinorReleases)

> fixes for security issues, serious problems with no workaround, and documentation fixes are backported to the most recent two release branches, if applicable to that branch. 

In my opinion this doesn't qualify for a backport, since it's not a "serious problem without a workaround", given that the code doesn't compile anyway. So it would be fixed in go1.18 when it gets released.

Of course if we find a program that should compile (and it crashes the compiler), that would probably qualify for a backport.

**Comment by swapx** [comment]
If you fix it for go1.18 is fine for me.
