### ISSUE TITLE
strings, bytes: Title doesn't shield against emoji

### ISSUE THREAD

**Issue by 180909** [golang/go#48356]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN="/bin"
GOCACHE="/Users/wang/Library/Caches/go-build"
GOENV="/Users/wang/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/wang/go/pkg/mod"
GONOPROXY="gitlab.hexcloud.cn"
GONOSUMDB="gitlab.hexcloud.cn"
GOOS="darwin"
GOPATH="/Users/wang/go"
GOPRIVATE="gitlab.hexcloud.cn"
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/wang/open/source/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fc/5_f38pyn6k915kw7_vvfjhrc0000gn/T/go-build1773033347=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.17.1 darwin/arm64
GOROOT/bin/go tool compile -V: compile version go1.17.1
uname -v: Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101
ProductName:	macOS
ProductVersion:	11.5.1
BuildVersion:	20G80
lldb --version: lldb-1205.0.28.2
Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
</pre></details>

### What did you do?

[playground](https://play.golang.org/p/a0CvAAQCRn8)

### What did you expect to see?

☺☻☹Hello

### What did you see instead?

☺☻☹hello

**Comment by smasher164** [comment]
I don't see how this can be fixed without making a backwards-incompatible change for `Title`. I think handling emoji lies outside the scope of `strings` and `bytes`, and would warrant using something like `x/text`.

That being said, this seems similar to https://github.com/golang/go/issues/34994, which states that Unicode punctuation should be taken into account. More generally, if we treated any rune that's not alphanumeric as a separator, this could be fixed: https://play.golang.org/p/JRe3MVsgJ_G.

/cc @ianlancetaylor @mpvl

**Comment by ianlancetaylor** [comment]
We already have a comment on `bytes.TItle` saying that it doesn't handle punctuation correctly (https://pkg.go.dev/bytes#Title).  Perhaps we should just extend that comment to say that it doesn't handle emoji correctly either.  The function is generally problematic.

**Comment by smasher164** [comment]
Given how problematic the function is, and how `golang.org/x/text/cases` is a better alternative for most scenarios, shouldn't `bytes.Title` and `strings.Title` be deprecated?

**Comment by ianlancetaylor** [comment]
I would support deprecating them.

**Comment by seankhliao** [comment]
Title has been deprecated
