### ISSUE TITLE
reflect: map updates not working

### ISSUE THREAD

**Issue by randall77** [golang/go#48357]
This program crashes:

```
package main

import "reflect"

type T [129]byte

func main() {
	m := map[string]T{}
	v := reflect.ValueOf(m)
	v.SetMapIndex(reflect.ValueOf("a"), reflect.ValueOf(T{}))
	g = m["a"]
}

var g T
```

CL 345486 introduced a new optimization path to call the `_fast` map operations on string keys. But the fast operations also require the value to be <=128 bytes. When we violate that, bad things happen.

@dsnet

**Comment by dsnet** [comment]
Oops 😦!! Easy enough of a fix.
