### ISSUE TITLE
go/parser: cannot parse channel of channel with receive direction

### ISSUE THREAD

**Issue by vladimiroff** [golang/go#48354]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kiril/.cache/go-build"
GOENV="/home/kiril/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4024821342=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Tried to make channel of channels with receive direction: https://play.golang.org/p/1dR3qhjMF90

Simplified example, where a single click on "Format" highlights the issue: https://play.golang.org/p/M8Yn3NAP6V5
At first I thought this is a bug in gofmt, changing the semantic of my code.

### What did you expect to see?

Expected to be able to send channels with receive-only direction through that channel.

### What did you see instead?

The "root" channel is made with send-only direction instead, during make, thus making it useless:

```
./prog.go:9:9: invalid operation: <-chch (receive from send-only type chan<- chan int)
```

### Workaround

Adding parentheses around the inner channel solves the issue:

```go
	chch := make(chan (<-chan int))
```

**Comment by ALTree** [comment]
This is working as expected, from the [Language specification](https://golang.org/ref/spec#Channel_types):

>The <- operator associates with the leftmost chan possible:
>
> `chan<- chan int    // same as chan<- (chan int)`

as you noted, you need parentheses to get the direction to be associated to the right channel.
