### ISSUE TITLE
cmd/vet: add test for use of constraints package in way that is not forward compatible

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#48365]
In the discussion of the constraints package @benjaminjkraft raised an issue (https://github.com/golang/go/discussions/47319#discussioncomment-1034247).  This kind of code:

```Go
type MySigned interface { type int8, int16, int32, int64 }
func MyAbs[T MySigned](v T) T { ... }
func Abs[T constraints.Signed](v T) T { return MyAbs(v) }
```

will fail to compile if we add a new type to `constraints.Signed`, because the new type will not be accepted by the `MySigned` constraint.  However, we want to be able to add new types to the constraints package if we add new predeclared types to the language.  That is, this bit of code is not forward compatible with possible future changes to the constraints package.

We can avoid such difficulties by adding vet checks for the following:

1. Given a type parameter whose constraint is taken from the constraints package, don't use that type parameter to instantiate a type/function whose constraint is not `any` and is not taken from the constraints package.
2. Don't write a type switch to handle all types when using a constraint taken from the constraints package.

This issue is to add those vet checks.

**Comment by randall77** [comment]
> Don't write a type switch to handle all types when using a constraint taken from the constraints package.

How would you detect that? That is, how can you tell that the user is trying to handle all types?

**Comment by ianlancetaylor** [comment]
> How would you detect that? That is, how can you tell that the user is trying to handle all types?

Look for a type switch on a variable constrained by a constraint from the constraints package.  Give an error if all the types in the current constraints implementation appear as cases and there is no `default` case.

**Comment by randall77** [comment]
What if there is a default case that panics? `log.Fatalf`s?
What if the switch explicitly lists n-1 cases and they use default for the nth case?
There are probably other permutations also.

**Comment by ianlancetaylor** [comment]
We can't be perfect, but we can do better than nothing.

**Comment by robpike** [comment]
But vet needs to be close to perfect. "Better than nothing" is not good enough.

**Comment by zpavlinovic** [comment]
My concern is that this vet checker would not finding bugs in the user code, yet perhaps issues in the design. The current code is not buggy per se. 

So the checker findings IMO could be interpreted as warnings saying `if new types are added to the constraints package in the future and you do not refactor your code in the meantime, then you'll see a compilation error`. Not sure if this is what a vet checker should do.

**Comment by ianlancetaylor** [comment]
> But vet needs to be close to perfect. "Better than nothing" is not good enough.

Fair enough.  We may have to drop the type switch part of this idea.

**Comment by ianlancetaylor** [comment]
@zpavlinovic I see this as similar to the current vet warning about using an unkeyed composite literal with a struct type defined in a different package.  It warns about code that is correct at the moment but may break in the future.

**Comment by ianlancetaylor** [comment]
Moving to 1.19.

**Comment by ianlancetaylor** [comment]
Moving to Backlog.

**Comment by ianlancetaylor** [comment]
We decided against putting the constraints package into the standard library, so this issue is of little interest.  Closing.
