### ISSUE TITLE
path.Ext(photo) and filepath.Ext(photo) cannot find the real extensio of the photo file

### ISSUE THREAD

**Issue by jimmyyem** [golang/go#48377]
### What version of Go are you using (`go version`)?
1.6
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
MacOS  darwin/amd64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

the link is here:  https://gist.github.com/jimmyyem/cf8258d76f8bb10b41f994aa79cea156

### What did you expect to see?
I wanna get the rigth extension of the file at any time.

### What did you see instead?
I cannot get the corrent answer.

**Comment by seankhliao** [comment]
`path.Ext` expects a filepath, not a url path + query
