### ISSUE TITLE
`gofmt` automatically adding `go:build ` is annoying

### ISSUE THREAD

**Issue by alexec** [golang/go#48383]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes. Only with 1.17.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/acollins8/Library/Caches/go-build"
GOENV="/Users/acollins8/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/acollins8/go/pkg/mod"
GONOPROXY="*.intuit.com"
GONOSUMDB="*.intuit.com"
GOOS="darwin"
GOPATH="/Users/acollins8/go"
GOPRIVATE="*.intuit.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/acollins8/go/src/github.com/argoproj-labs/argo-dataflow/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s0/41b1vy2d6nn42rmgltmbrpdw0000gp/T/go-build1526554684=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you expect to see?

Running `brew upgrade` upgraded to golang 1.16. `gofmt` automatically add the directive. Now I have 2x directives to maintain. My PR got lots of changes in it I didn't want. This is annoying.

**Comment by seankhliao** [comment]
See also #41184

**Comment by alexec** [comment]
Fixed - uninstall Go 1.17 and reinstall Go 1.16.
