### ISSUE TITLE
cmd/compile/internal/syntax: unclear error message for function type have type parameters

### ISSUE THREAD

**Issue by cuonglm** [golang/go#48382]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-ee91bb8319 Tue Sep 14 02:53:17 2021 +0000 darwin/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Compile this program:

```
package p

type I func[T any]()
```

### What did you expect to see?

Friendly error message, like `gotype`:

```
$ gotype p.go
p.go:3:12: function type cannot have type parameters
```

### What did you see instead?

```
$ go tool compile p.go
p.go:3:15: syntax error: unexpected any, expecting ]
```

cc @griesemer @findleyr

**Comment by griesemer** [comment]
The fix is not hard but it's also subtle due to the way func type parsing is used in various places. If we address this, it needs to be a comprehensive fix which requires some careful parser changes.

Not urgent.
