### ISSUE TITLE
x/tools/gopls: experimentalWorkspaceModule does not work for the standard library

### ISSUE THREAD

**Issue by findleyr** [golang/go#48384]
Reminder issue: the `experimentalWorkspaceModule` setting does not behave correctly for std and cmd. We should (1) document this, and (2) investigate.

Moving this to v0.7.3 for at least improving the documentation.

CC @stamblerre

**Comment by heschi** [comment]
Dupe of https://golang.org/issue/45890?

**Comment by stamblerre** [comment]
Yep, closing and moving the other issue to v0.7.3 milestone.
