### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by brown2077** [golang/go#48401]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you see instead?
I have several users that are getting flagged by our antivirus for the following. Is this a GO update?
Path
c:\program files\go\pkg\tool\windows_amd64\pack.exe
SHA-256
6967a984ccfde4f0ba075ca029050dcbab59f49f41f9d904584fab754deb9aed
MD5	668612d3dd798567a8658d6fa04f1d98
SHA-1	f001af8faf42977b3583e5b188438695032ed1fa

**Comment by seankhliao** [comment]
https://golang.org/doc/faq#virus
