### ISSUE TITLE
runtime: x86 CPU feature optimizations dropped in Go 1.17

### ISSUE THREAD

**Issue by aclements** [golang/go#48406]
[CL 344329](https://golang.org/cl/344329) caused the runtime to no longer detect POPCNT, SSE 4.1, or FMA support on amd64. This affects the performance of `math/bits.OnesCount`, `math.FMA`, and most of the rounding functions in `math`.

This CL was released as part of Go 1.17, so this may be worth a back-port, or maybe the risk is too high for not enough reward.

/cc @martisch

**Comment by aclements** [comment]
@gopherbot , please backport to Go 1.17.

**Comment by aclements** [comment]
This is fixed by [CL 350151](https://golang.org/cl/350151).

**Comment by martisch** [comment]
Sorry.

Why do we think this made it to go1.17? The CL that caused the regression was submitted August 23 after go1.18 tree open. I cant see that change in the go1.17 release branch: https://github.com/golang/go/blob/21a4e67ad58e3c4a7c5254f60cda5be5c3c450ff/src/runtime/proc.go#L637

**Comment by aclements** [comment]
> Why do we think this made it to go1.17?

Sorry, I was mistaken about that.

**Comment by cespare** [comment]
Worth adding `GOARCH`/`GOOS` string constants somewhere?

**Comment by aclements** [comment]
Possibly. We already have `goarch.ArchFamily` and `goarch.Is*` constants, but the former is a bit of a mouthful and the latter are defined as 0/1 numeric constants, which are annoying to use in contexts like this. We also don't have an equivalent of `goarch.ArchFamily` for goos. Maybe we should just clean all of that up.
