### ISSUE TITLE
Propose a Centos Based docker image

### ISSUE THREAD

**Issue by henri9813** [golang/go#48417]
Could you propose a centos based docker image ?

It could be helpful to test some types of scripts on CentOS directly thanks to a golang:1.17-centos docker image for example

### What version of Go are you using (`go version`)?

every version

### What operating system and processor architecture are you using (`go env`)?

I use Centos :-)

**Comment by ALTree** [comment]
Docker images with Go are not released or maintained by this project, they're packaged by someone else (members of the docker or Go community I suppose). So I'm afraid this is not the right place to ask.

Closing here, feel free to comment if I've misunderstood your request.
