### ISSUE TITLE
cmd/cover: test timeout after 18m on plan9-arm

### ISSUE THREAD

**Issue by millerresearch** [golang/go#48416]
The cmd/cover test has been timing out quite frequently on plan9-arm. Most recent example [here](https://build.golang.org/log/317818d56ede2746f4347a03dbc0d8482abcacc4)

I don't know how far back in time this goes. Is there a simple way to search failed test results to find the earliest occurrence?

**Comment by cagedmantis** [comment]
You may be able to accomplish what you are seeking through the use of [fetchlogs](https://go.googlesource.com/build/+/refs/heads/master/cmd/fetchlogs/).

**Comment by millerresearch** [comment]
> You may be able to accomplish what you are seeking through the use of [fetchlogs](https://go.googlesource.com/build/+/refs/heads/master/cmd/fetchlogs/).

Thanks. Looks like the first failure was Jan 27 2021, then frequent occurrences from 3 March onwards.

I've managed to replicate the timeout once.  Proximate cause is that `go list -e json htmlunformatted` appears to be deadlocked.

**Comment by millerresearch** [comment]
The "deadlock" was `lockedfile.openFile` looping on a file in /tmp which was not actually locked: a bug in Plan 9 ramfs which was fixed some time ago, but somehow the patch wasn't applied on the plan9_arm builders. So, my fault. Should be OK now.

**Comment by millerresearch** [comment]
Still getting timeouts, so I'd better reopen the issue and investigate further.

**Comment by millerresearch** [comment]
There was a logic error in Plan 9 ramfs (used for /tmp on the builders), one consequence of which was a failure to maintain exclusive-open status on files. Now fixed, so it should be safe to close this issue.
