### ISSUE TITLE
Unable to run .go file in termux ?

### ISSUE THREAD

**Issue by sumithemmadi** [golang/go#48421]
I'm using termux android terminal emulator .I installed  golang on termux. When I install go Language first time  it worked fine it is executing the main.go file later I reinstalled termux and installed golang in it  now it's showing error

Here is my code.
`main.go`
```go
package main

import "fmt"

func main() {
	fmt.Println("Hello, World")
}
```
I run this `main.go` file on termux
```bash
~$ go run main.go
```
 3 days back it worked fine, when I reinstalled termux again and now it's showing error message.
```bash
~$ go run main.go
fork/exec /data/data/com.termux/files/usr/tmp/go-build104497825/b001/exe/main: no such file or directory
```
.
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.1 android/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes , 3 days back it worked fine now it's showing error.

### What operating system and processor architecture are you using (`go env`)?

<details><summary>
<code>go env</code> Output</summary><br><pre>
~ $ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/data/data/com.termux/files/home/.cache/go-build"
GOENV="/data/data/com.termux/files/home/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="android"
GOINSECURE=""
GOMODCACHE="/data/data/com.termux/files/home/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="android"
GOPATH="/data/data/com.termux/files/home/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/data/data/com.termux/files/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/data/data/com.termux/files/usr/lib/go/pkg/tool/android_arm64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="aarch64-linux-android-clang"
CXX="aarch64-linux-android-clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/data/data/com.termux/files/usr/tmp/go-build1124584764=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by seankhliao** [comment]
android version?

**Comment by sumithemmadi** [comment]
`Android Version 10`

```bash
~ $ termux-info
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.186-perf-g10af704 #1 SMP PREEMPT Sun Dec 27 14:28:21 WIB 2020 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
POCO F1
```
![Screenshot_2021-09-16-23-36-56-056_com android settings](https://user-images.githubusercontent.com/50250422/133662794-7eff99cc-7696-4352-b5a8-e53038c82070.jpg)

**Comment by seankhliao** [comment]
I just tried this and it seems to be #47760
I think this is a termux build/packaging issue and they need to set GO_LDSO
