### ISSUE TITLE
x/pkgsite: link to standard library from homepage

### ISSUE THREAD

**Issue by carlmjohnson** [golang/go#48435]
### What did you do?

Go to https://pkg.go.dev/

### What did you expect to see?

A link to https://pkg.go.dev/std

### What did you see instead?

Just examples of search terms.

If you already know the name of packages in the standard library, it's not a big deal to search for them, but if you want to explore the standard library, you need to find https://pkg.go.dev/std somehow, and the homepage gives no indication of how to get there.

**Comment by fzipp** [comment]
Technically you can click on "Docs", which leads to golang.org/doc, and then on "Packages", which leads to pkg.go.dev/std
But yes, at the latest when all content from golang.org is [moved to go.dev](https://go.dev/blog/tidy-web) the link needs to find a new home.

**Comment by ALTree** [comment]
This is already tracked in #40785, closing here in favour of the older thread.
