### ISSUE TITLE
x/pkgsite: Add a link to the stdlib overview on the root page of https://pkg.go.dev/

### ISSUE THREAD

**Issue by breml** [golang/go#48445]
### What did you do?

In the past, I often used https://golang.org/pkg/ to look up the documentation of the Go standard library, especially if I knew, that there is a package for x, but I didn't remember the exact name of the package.

With all package documentation now consolidated on https://pkg.go.dev/ this short way to the documentation for the standard library is gone and it took me a while to discover, that this documentation is still available at https://pkg.go.dev/std.

### What did you expect to see?

I would have found https://pkg.go.dev/std way earlier, if it would have been mentioned on https://pkg.go.dev/, e.g. below the search examples. In my opinion, the documentation of the Go standard library is one of the most important pieces of documentation and therefore it should not be "hidden" but immediately obvious how to get there.

### What did you see instead?

I can not find any mentioning of the Go standard library on the root page of https://pkg.go.dev/.

**Comment by seankhliao** [comment]
This is being tracked in #40785
