### ISSUE TITLE
Built-in type casting works differently in darwin/amd64 and darwin/arm64 of go1.17.1.

### ISSUE THREAD

**Issue by bang9211** [golang/go#48458]
I have 2 mac, the one uses intel(darwin/amd64) the other one uses M1(darwin/arm64).

I found my test case work differently in other CPU.

Built-in type casting of each version handles overflow differently.

![image](https://user-images.githubusercontent.com/24886864/133890909-9a402387-dd7f-48f9-a49d-56bbd98170af.png)

![image](https://user-images.githubusercontent.com/24886864/133890948-6dd7447d-a306-4e06-9c5c-b867006e5903.png)

there is no different except for arch(amd64, arm64) in 'go env', 'go version'.

**Comment by seankhliao** [comment]
See previously #19405 #29468
The result is implementation defined
