### ISSUE TITLE
x/pkgsite: requested package `could not be found` 

### ISSUE THREAD

**Issue by CAFxX** [golang/go#48451]
I recently created a new public github repo (https://github.com/CAFxX/decommit) but pkg.go.dev seems to be unable to access/parse it.

If I go to https://pkg.go.dev/github.com/CAFxX/decommit I get

![image](https://user-images.githubusercontent.com/408018/133860255-aa336097-b226-43c2-aa84-c66cf4ae4db7.png)

Once I click on "request", I get almost immediately, `"github.com/CAFxX/decommit" could not be found.`:

![image](https://user-images.githubusercontent.com/408018/133860302-aa33f26c-87c1-4078-9479-c4ed5b3cd9ac.png)

If I use `go get` it works:

```
❯ mkdir test

❯ cd test

❯ go mod init test
go: creating new go.mod: module test

❯ go get github.com/CAFxX/decommit
go: downloading github.com/CAFxX/decommit v0.0.0-20210917111054-076de2fd09f9
go get: added github.com/CAFxX/decommit v0.0.0-20210917111054-076de2fd09f9
go get: added golang.org/x/sys v0.0.0-20210910150752-751e447fb3d0
```

Even after running go get, pkgsite still says the same thing. So it seems that pkgsite is somehow choking on that repo.

**Comment by jamalc** [comment]
I see a fetch module error in the DB.

```
extractPackages(ctx, "github.com/CAFxX/decommit", "v0.1.1", r, d): module contains 0 packages: bad module
```

Is it possible the initial fetch contained no packages and the module got stuck in a bad state @jba @julieqiu?

**Comment by jba** [comment]
Having trouble debugging this because it succeeds when I run the worker locally, but gets a 490 on the deployed one, even though they are the same code.

Inserting more logging.

**Comment by jba** [comment]
I couldn't reproduce this locally because it depends on the Go version. The module builds in 1.17 but not in 1.16, because of the changes being made to build tags:
```
> git clone https://github.com/CAFxX/decommit
...
> cd decommit
> docker run -v $PWD:/go golang:1.16.7 env GOPATH= go build
go: downloading golang.org/x/sys v0.0.0-20210910150752-751e447fb3d0
//go:build comment without // +build comment
```

pkgsite runs on App Engine, which is still on 1.16, so we can't process this module. Just add back the `// +build` comment.
