### ISSUE TITLE
cmd/asm: R15 gets clobbered in plugin mode [issue:43661 also in 1.17and1.17.1]

### ISSUE THREAD

**Issue by zishen** [golang/go#48468]
What version of Go are you using (go version)?
go version : 1.17 and 1.17.1

Does this issue reproduce with the latest release?
Yes

What operating system and processor architecture are you using (go env)?
OS: linux x86_64

What did you do?
When I was in the compilation of a component named of "volcano.sh/volcano", this situation happened:
![截图](https://user-images.githubusercontent.com/7522079/133921453-ad0d6f4c-890a-4ceb-bd94-b83c50229b7d.PNG)

I found this problem have been solved here and incorporated into the go 1.17, the issue :[43661](https://github.com/golang/go/issues/43661)

so, why?

I also in plugin mode.

**Comment by randall77** [comment]
When dynamic linking (which includes plugin mode, I think), `R15` is reserved for the global offset table. User assembly code is not allowed to overwrite it.

This was fixed in xxhash about a month ago: https://github.com/cespare/xxhash/commit/e7a6b52374f7e2abfb8abb27249d53a1997b09a7
