### ISSUE TITLE
x/pkgsite: page number too large when seeing last page of package list

### ISSUE THREAD

**Issue by successgo** [golang/go#48481]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/search?page=5&q=http
 
### What is your user agent?
 

 
 google chrome 93.0 on macOS
 
### Screenshot
 

 
 
![image](https://user-images.githubusercontent.com/13791720/133962201-1aa8c8a1-227c-4233-b9a4-9f6faeafa48f.png)
![image](https://user-images.githubusercontent.com/13791720/133962203-70e06c34-7c91-44ed-bf32-8b0ccb1056be.png)

 
### What did you do?
 

 
 search package "http", and see the page 5.
 
### What did you expect to see?
 
 I expect to see page 5 package list.
 
### What did you see instead?

I see error of "Page number too large".

**Comment by jamalc** [comment]
This looks like a regression @julieqiu, could you take a look?

**Comment by jamalc** [comment]
I think I found the cause. We should increase [maxSearchOffset](https://cs.opensource.google/go/x/pkgsite/+/master:internal/frontend/search.go;l=132;bpv=0;bpt=0) to 100.
