### ISSUE TITLE
cmd/compile: ExampleInfo output not being checked

### ISSUE THREAD

**Issue by ameowlia** [golang/go#48494]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.17 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/adowns/Library/Caches/go-build"
GOENV="/Users/adowns/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/adowns/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/adowns/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/adowns/workspace/text/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4c/1b3s36l94blb6xg1_4p_13800000gn/T/go-build2465748359=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Ran a parser looking for instances of [this issue](https://github.com/golang/go/issues/48362) where there are any comment blocks _after_ "output" comment blocks. This makes the test pass regardless of what is in the output comment block.

### What did you expect to see?

No examples of [this issue](https://github.com/golang/go/issues/48362).

### What did you see instead?

Found that [ExampleInfo](https://github.com/golang/go/blob/9e60c371473ff15eb4b13981721b29f62e1d862c/src/cmd/compile/internal/types2/example_test.go#L191-L247) has a "TODO" comment after the "output" comment.

**Comment by dr2chase** [comment]
Thanks for working on this, I only added the label to get it off the automated triage pile.
