### ISSUE TITLE
cmd/go: commit a6ff433d6a927e8ad8eaa6828127233296d12ce5 reduces concurrency in compiler

### ISSUE THREAD

**Issue by dominikh** [golang/go#48490]
Commit a6ff433d6a927e8ad8eaa6828127233296d12ce5 changes the way flags get passed to the compiler. As an unintended side-effect, the `-c` (for concurrency) flag seems to no longer get passed from `go build` to `go tool compile`. This can be seen in the output of `go build -x`, and it can be felt when running `make.bash`, which went from ~600% CPU utilization on the commit's parent to ~390% CPU utilization.

/cc @cuonglm @bcmills @mvdan

**Comment by mvdan** [comment]
This probably means we should have an integreation test to ensure that the `-c` flag gets plumbed through to the compiler properly :)

**Comment by cuonglm** [comment]
So it seems the flags order change affect `gcBackendConcurrency`:

https://github.com/golang/go/blob/79159f2e83662dac4089e2f5231ec23de9da10b9/src/cmd/go/internal/work/gc.go#L185
