### ISSUE TITLE
x/pkgsite: API not detected

### ISSUE THREAD

**Issue by changkun** [golang/go#48509]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/golang.design/x/clipboard
 
### What is your user agent?
 
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
 
 
### What did you do?
 

 
Visit the page
 
 
### What did you expect to see?
 
 See APIs as it was displayed in older versions, e.g. https://pkg.go.dev/golang.design/x/clipboard@v0.4.6
 
### What did you see instead?

No API is displayed.

**Comment by jba** [comment]
This is the same problem as #48451: by removing the `// +build` comments, the package won't work with go 1.16, and that's currently the version we use to process modules. The fix is to add back those comments.

**Comment by changkun** [comment]
Since there is no auto-refresh or auto-reprocessing, the module will not be processed again unless I release a new version. right?

But 1.17 is indeed a supported version, and backward compatible, how about an upgrade to 1.17?

**Comment by jba** [comment]
We run on App Engine, which currently only supports 1.16. We'll upgrade as soon as we can.
Meanwhile, yes, you'd have to release a new version.
