### ISSUE TITLE
runtime:  Add error message when running non GOAMD64=v1 on unsupported hardware

### ISSUE THREAD

**Issue by martisch** [golang/go#48506]
With #45453 we are introducing GOAMD64 to build binaries that are not supported on all amd64 machines.

This can lead to an illegal instruction exception when running such a binary.

We should make best effort to report when such a binary with GOAMD64 > v1 is run on unsupported hardware.

One way to check is to add some assembly early in the runtime startup like it is done to detect MMX on 386 and print a short error message then exit the go program:
https://github.com/golang/go/blob/c7543e5db95d80205d1a0be3b4e946fac244601c/src/runtime/asm_386.s#L156

Waiting for internal/cpu to initialise to then do the minimum hardware checks in go code is likely to late as by that time an instruction that was emitted by the go compiler could have been used that already is unsupported.

/cc @mdempsky @randall77

**Comment by mknyszek** [comment]
@martisch Is this fixed now? It looks like it, but I wanted to double check. Please close if so. Thanks!
