### ISSUE TITLE
runtime/checkptr: erroneous "pointer arithmetic result points to invalid allocation"

### ISSUE THREAD

**Issue by ajwerner** [golang/go#48501]
### What version of Go are you using (`go version`)?

go version go1.16.5 darwin/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

darwin/amd64

### What did you do?

Consider the following test:

```go
package main

import (
	"reflect"
	"testing"
	"unsafe"
)

func TestExtractInt8FromStruct(t *testing.T) {
	type Foo struct {
		i16 int16
		i8  int8
	}
	off := reflect.TypeOf((*Foo)(nil)).Elem().Field(1).Offset
	int8Type := reflect.TypeOf((*int8)(nil)).Elem()
	getI8 := func(p uintptr) *int8 {
		return reflect.NewAt(int8Type, unsafe.Pointer(p+off)).Interface().(*int8)
	}
	foo := &Foo{i8: 10}
	got := getI8(reflect.ValueOf(foo).Pointer())
	if got != &foo.i8 {
		t.Fatal("failed to get pointer")
	}
}
```

### What did you expect to see?

I expected to see the test pass, however, under race, it fails. I believe that this procedure to extract the pointer to the underlying int8 from the pointer to the outer struct is sane. I don't see an obvious problem with it. The data in this approach always seems right. 

### What did you see instead?

```
fatal error: checkptr: pointer arithmetic result points to invalid allocation

goroutine 19 [running]:
runtime.throw(0x12018f0, 0x40)
	/usr/local/Cellar/go/1.16.5/libexec/src/runtime/panic.go:1117 +0x72 fp=0xc000062ce0 sp=0xc000062cb0 pc=0x1077b72
runtime.checkptrArithmetic(0xc00020a082, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.16.5/libexec/src/runtime/checkptr.go:43 +0xbe fp=0xc000062d10 sp=0xc000062ce0 pc=0x1047b7e
github.com/cockroachdb/cockroach/pkg/scratch.TestExtractInt8FromStruct.func1(0xc00020a080, 0xc00020a080)
	pkg/scratch/scratch_test.go:17 +0x73 fp=0xc000062d78 sp=0xc000062d10 pc=0x11b76f3
github.com/cockroachdb/cockroach/pkg/scratch.TestExtractInt8FromStruct(0xc000214300)
	pkg/scratch/scratch_test.go:20 +0x269 fp=0xc000062ed0 sp=0xc000062d78 pc=0x11b75c9
testing.tRunner(0xc000214300, 0x1201ef0)
	/usr/local/Cellar/go/1.16.5/libexec/src/testing/testing.go:1193 +0x203 fp=0xc000062fd0 sp=0xc000062ed0 pc=0x114b083
runtime.goexit()
	/usr/local/Cellar/go/1.16.5/libexec/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000062fd8 sp=0xc000062fd0 pc=0x10afa41
created by testing.(*T).Run
	/usr/local/Cellar/go/1.16.5/libexec/src/testing/testing.go:1238 +0x5d8
```

**Comment by ajwerner** [comment]
I have also verified that this isn't about the field being exported or not.

**Comment by ajwerner** [comment]
Thank you much for the quick reply! I was looking for such rules around the `reflect` package and not finding them. This works great.

Maybe, separately, I'll open a docs issue to point folks from `NewAt` to the `unsafe` documentation, what do you think?

**Comment by randall77** [comment]
I don't think `NewAt` needs that doc, as that's not where the violation stems from. If anything, it is the docs of `reflect.Pointer` that should have a cross-reference to that rule.
