### ISSUE TITLE
x/mobile: gomobile bind-target panics with error indicating arm64 is unsupported

### ISSUE THREAD

**Issue by ytxyyt** [golang/go#48510]
```
panic: unsupported GOARCH: arm64

goroutine 1 [running]:
main.archNDK(...)
        /go/src/golang.org/x/mobile/cmd/gomobile/env.go:408
main.(*ndkToolchain).Path(0x40001a1af0, {0x400001e031, 0xb}, {0x38207e, 0x5})
        /go/src/golang.org/x/mobile/cmd/gomobile/env.go:437 +0x78
main.envInit()
        /go/src/golang.org/x/mobile/cmd/gomobile/env.go:164 +0x1b4
main.buildEnvInit()
        /go/src/golang.org/x/mobile/cmd/gomobile/env.go:149 +0x2f4
main.runBuildImpl(0x6180c0)
        /go/src/golang.org/x/mobile/cmd/gomobile/build.go:86 +0x3c
main.runBuild(0x6180c0)
        /go/src/golang.org/x/mobile/cmd/gomobile/build.go:79 +0x28
main.main()
        /go/src/golang.org/x/mobile/cmd/gomobile/main.go:73 +0x4b4
```

**Comment by r3inbowari** [comment]
Android NDK does not contain arm64 toolchains (until and including NDK 23)
[about arm support pr](https://github.com/android/ndk/issues/1299)

**Comment by ytxyyt** [comment]
> Android NDK 不包含[有关 arm 支持的](https://github.com/android/ndk/issues/1299)arm64 工具链（直到并包括 NDK 23）
> [](https://github.com/android/ndk/issues/1299)

I compiled the ARM64 version of NDK on my own and was able to pack things in just fine use

**Comment by changkun** [comment]
> I compiled the ARM64 version of NDK on my own and was able to pack things in just fine use

It is not yet supported because NDK does not yet support arm64. If you build your own NDK, then you may have to maintain your own gomobile dependency. A workaround may set `arch` to "arm64" in https://github.com/golang/mobile/blob/6d8ad35e460371e979b330d80492cba19676f933/cmd/gomobile/env.go#L399-L406

**Comment by mknyszek** [comment]
@ytxyyt I think @changkun answered your question, but I'd appreciate it if you could fill in more detail about what exactly you were trying to do in your original post. As such, I left it as waiting for info.

I'm not familiar with exactly what's going on here though. Seems like this is unsupported. Should there be another issue about support if the NDK (Android SDK?) will support arm64 in the future? Thanks. Please close the issue if this is resolved.
