### ISSUE TITLE
cmd/go2go: shut down go2go playground

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#48517]
The go2go playground served its purpose and is now out of date and is more confusing than helpful.  It's time to shut it down.

Ideally go2goplay.golang.org should be replaced with a static page saying something along the lines of

This playground was used during the development of the generics proposal.  It is now out of date and has been shut down.  The generics proposal (https://golang.org/s/generics-proposal) has been accepted and (as of September 2021) is under active development aiming for inclusion in the Go 1.18 release.

CC @griesemer @golang/osp-team

**Comment by ianlancetaylor** [comment]
We should perhaps have the go2go playground redirect to the tip playground.  Though I don't know that we have a tip playground running at this point.

CC @golang/release

**Comment by changkun** [comment]
It would be nice to serve tip, and the latest two releases, as proposal accepted in #33629

**Comment by findleyr** [comment]
@changkun I agree that would be nice, but that is a modestly sized project that unfortunately none of us have time for at the moment.  It is also the case that the gotip playground will be redeployed many times a day, which may not be desirable for the non-tip playground (I'm honestly not sure if that argument holds water).

For now, I am planning to deploy gotipplay.golang.org, which will be identical to play.golang.org but using Go tip (I will probably also try to indicate this somewhere in the HTML, and change examples).  For technical reasons the URL must be gotipplay.golang.org, not e.g. gotip.play.golang.org.

**Comment by findleyr** [comment]
With help from @toothrot, https://gotipplay.golang.org is deployed. Next step is to clearly identify the go version in the UI, and redirect go2go.

The plan for the latter is to just overwrite the go2go app with a simple redirector.

**Comment by griesemer** [comment]
And it [works](https://gotipplay.golang.org/p/e5KE9zYU9uu)! Cool.

**Comment by ianlancetaylor** [comment]
Thanks!

**Comment by findleyr** [comment]
@toothrot just deployed the redirect service for go2goplay.golang.org, so this is now done.

**Comment by ianlancetaylor** [comment]
Thanks!
