### ISSUE TITLE
x/build/cmd/relui: tag golang.org/x repos continuously

### ISSUE THREAD

**Issue by toothrot** [golang/go#48523]
Plan: once a month (or whatever time unit)
For each x repo in dependency order (lowest first)
go get update all the deps to their latest tags
Wait for that to be green
Tag it with next version 

Can probably shoehorn into existing process, maybe not running automatically at first.
0.1.0, 0.2.0, 0.3.0...

**Comment by dmitshur** [comment]
> Wait for that to be green

Resolving this issue is blocked on coming up with a machine-understandable criteria of what "green" means.

**Comment by heschi** [comment]
At the moment, I expect to automatically tag all of the following repositories:

- arch
- crypto
- image
- mod
- net
- oauth2
- review
- sync
- sys
- term
- text
- time
- tools
- tour

Only a few of them are tagged already: mod, review, text, tools, tour. The rest will be tagged for the first time.

**Comment by FiloSottile** [comment]
Why v0 and not v1? We've been upholding the compatibility promise for a lot of these repositories if not all, and I don't think it would be feasible to make backwards-incompatible changes at this point.

**Comment by heschi** [comment]
That's entirely up to the project: if you tag (e.g.) a v1.0.0 on x/crypto, the automation will tag v1.1.0 next time it runs. I didn't want to run around asking people how they felt about each repo, and I also didn't want to publish a v1 unilaterally.

**Comment by heschi** [comment]
I'm gonna call this done. We haven't run it fully end-to-end yet because of the hiccups with x/tools, but it got very close. One possible followup is to have it mail CLs to specified reviewers, since it turns out almost none of our repositories have owners any more, but I'll decide about that next time we run it.
