### ISSUE TITLE
sort: Sort documentation should describe most common sort order

### ISSUE THREAD

**Issue by kevinburke** [golang/go#48527]
The docstring for sort.Sort says:

```go
// Sort sorts data.
// It makes one call to data.Len to determine n and O(n*log(n)) calls to
// data.Less and data.Swap. The sort is not guaranteed to be stable.
```

It would be nice if this explained which order data is returned in. I understand that you can call sort.Sort(sort.Reverse(data)), or provide a Less() function that returns true if `i` is greater than `j`, but we could provide some guidance about what is most likely to happen.

For example:

```go
// Sort sorts data.
// It makes one call to data.Len to determine n and O(n*log(n)) calls to
// data.Less and data.Swap. The sort is not guaranteed to be stable.
// Usually, the lowest value will be sorted first. Use Reverse to sort the
// highest value first.
func Sort(data Interface) {
```

Instead of "Usually", could also consider "By default", "When used with the methods in this package", etc.

**Comment by ianlancetaylor** [comment]
If we say anything here--I'm not sure we need to--we should just say "The result is sorted in ascending order according to the Less method."
