### ISSUE TITLE
x/pkgsite: linking to source code in GitHub Enterprise Server

### ISSUE THREAD

**Issue by sfllaw** [golang/go#48542]
#40477 suggests that we ask for new `internal.source.patterns` to support new code hosts.

We are using GitHub Enterprise Server which is hosted in a `github.*` domain. Currently, pkgsite is unable to resolve code from these repos because it only matches `github.com`: https://go.googlesource.com/pkgsite/+/5c86378aae4c9aeaf522db7e0a3b312d079f8c3e/internal/source/source.go#638

There is an existing model of self-hosted code repositories illustrated by `gitlab.*`. I suggest that we add something similar:

``` go
	{
		// Assume that any site beginning with "github." works like github.com.
		pattern:   `^(?P<repo>github\.[a-z0-9A-Z.-]+/[a-z0-9A-Z_.\-]+/[a-z0-9A-Z_.\-]+)(\.git|$)`,
		templates: githubURLTemplates,
	},
```

The downside to this approach is that people using other domain names will not be supported by this pattern, but I suspect the vast majority of people running GitHub Enterprise Server are using the `github.` subdomain.

**Comment by jba** [comment]
Sounds reasonable.

**Comment by jba** [comment]
Can you give me a URL to a file for testing? (We will hit it once and then record it for future tests, so the traffic will be minimal.)

**Comment by sfllaw** [comment]
@jba Sorry, we don’t expose our GitHub Enterprise instance to the world, nor do we expose our Pkg.go.dev instance, because of corporate reasons. :slightly_frowning_face: 

However, I have applied your patch and used `go run ./devtools/cmd/seeddb -seed internal-repos.txt -refetch` to refetch everything in our database.

I can confirm that the _Repository URL_ is now being properly detected.

**Comment by sfllaw** [comment]
:shipit: :tada:
