### ISSUE TITLE
cmd/compile/internal/ssa: TestInlineLines fails on Windows

### ISSUE THREAD

**Issue by bcmills** [golang/go#48550]
[CL 351529](https://golang.org/cl/351529) removes a workaround for #43938 on Windows on the regression test for #47880.

Unfortunately, that workaround seems to have been masking another bug on Windows.
https://storage.googleapis.com/go-build-log/033ed565/windows-amd64-2016_fd7dc5ba.log:
```
--- FAIL: TestInlineLines (0.07s)
    debug_lines_test.go:173: wanted inlines [[3] [4] [5] [4 10] [4 10] [4 11] [5 10] [5 10] [5 11] [4 10 16] [4 11 16] [5 10 16] [5 11 16]] but got []
FAIL
FAIL	cmd/compile/internal/ssa	5.867s
```

The failing test was added in [CL 348970](https://golang.org/cl/348970) (CC @dr2chase, @randall77), so this appears to be a test-regression for Go 1.18. (It is not clear to me whether the test regression also represents a regression in functionality.)

**Comment by dr2chase** [comment]
That's not an inlining bug, that's a bug in the regular expression for a path separator in the test.
We don't need this test to run on all OSes, so I would just leave it disabled on Windows like it originally was.

**Comment by bcmills** [comment]
Oh, that doesn't seem at all difficult to fix! I'll fold it in to CL 351529.
