### ISSUE TITLE
cmd/go: get does not enforce minimum version from package's go.mod file

### ISSUE THREAD

**Issue by weineran** [golang/go#48571]
### What version of Go are you using (`go version`)?

<pre>
$ go1.15.15 version
go version go1.15.15 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go1.15.15 env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/andrew/Library/Caches/go-build"
GOENV="/Users/andrew/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/andrew/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/andrew/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/andrew/sdk/go1.15.15"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/andrew/sdk/go1.15.15/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_w/xf7pz9xj08v6rqptdykvbcnm0000gn/T/go-build196002086=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

<pre>
GO111MODULE=on go1.15.15 get github.com/zricethezav/gitleaks/v7
</pre>

### What did you expect to see?
The target package (github.com/zricethezav/gitleaks/v7) has a go.mod file that specifies minimum version `go 1.16`. (https://github.com/zricethezav/gitleaks/blob/master/go.mod)
Therefore, I expect to see a meaningful error like this:

<pre>
Unable to get package. github.com/zricethezav/gitleaks/v7 requires minimum version [go1.16]. You are running [go1.15.15].
</pre>

### What did you see instead?
<pre>
...
pkg/mod/github.com/zricethezav/gitleaks/v7@v7.6.1/config/config.go:4:2: package embed is not in GOROOT (/Users/andrew/sdk/go1.15.15/src/embed)
</pre>

The error message is somewhat misleading. The command actually fails because `embed` did not exist before `go1.16`.

Instead, it seems to me the commands should fail immediately because the go version does not satisfy the minimum version specified in the package's go.mod file. It would be great to see something like this:

<pre>
Unable to get package. github.com/zricethezav/gitleaks/v7 requires minimum version [go1.16]. You are running [go1.15.15].
</pre>

**Comment by seankhliao** [comment]
A module needs to declare the higher version to be able to make use of the new features, however, it can still choose to support older versions through the use of build tags.

See also #43980

Closing as I don't think there's anything to do here
