### ISSUE TITLE
cmd/go: -workfile flag appears to not work with "go test"

### ISSUE THREAD

**Issue by mvdan** [golang/go#48576]
go version devel go1.18-051df0d722 Wed Sep 22 03:45:00 2021 +0000 linux/amd64

I am trying to test workspaces once again. I have lots of cloned git repositories, and often I just need to work on 2 or 3 at a time. I don't want to drop a single `go.work`; I need to switch between multiple workspaces depending on what I'm currently doing.

So I thought I'd drop a file like `foo.work` and temporarily use it via `go test -workfile=../foo.work ./...`. However, it appears to have no effect at all.

Worse even, it appears like `go test -workfile=doesnotexist ./...` also makes no difference at all. It seems like the flag is just never taking effect?

cc @matloob @bcmills @jayconrod

**Comment by mvdan** [comment]
I'm also surprised and slightly worried that I can't seem to find any test scripts exercising this flag :) Which probably explains why it doesn't work.

**Comment by jayconrod** [comment]
Reproduced with `go test`. `go list` and `go build` seem to work fine though, which is weird.

```
go list -workfile=stop.work a
go build -workfile=stop.work a
go test -workfile=stop.work a

-- stop.work --
go 1.18

directory ./a
-- a/a.go --
package a
-- a/a_test.go --
package a
-- a/go.mod --
module a

go 1.18
```

There are a couple test scripts that use `-workfile`, `work.txt` and `work_edit.txt`. We do need something more robust though.

**Comment by mvdan** [comment]
You're absolutely right that there are some tests, I apparently can't grep :)

**Comment by mvdan** [comment]
@matloob I was wondering if you've had time to look into this bug - due to my workflow with many dozens of git repositories cloned, I am largely unable to properly test and daily drive workspaces :) My current alternative is to keep moving `.work` files around, but that's proving to be unusable when I'm working on multiple projects concurrently, as I can only have one single `go.work` file with my directory layout.

**Comment by matloob** [comment]
Sorry was heads down trying to get things in for the freeze
will look at it now
