### ISSUE TITLE
gnet.Conn希望能增加AsyncWritev()接口

### ISSUE THREAD

**Issue by liuiangang** [golang/go#48574]
gnet.Conn希望能增加AsyncWritev()接口，在多路[]byte需要同时传输的场景性能较好，如果按照目前提供的AsyncWrite()接口，则需要业务将多个[]byte拼接成一个[]byte，这样多了拷贝次数

**Comment by jim3ma** [comment]
是不是发错地方了？不是应该发在 gnet 项目里么？

**Comment by mvdan** [comment]
I'm sorry but this issue tracker is in English. For questions, see https://golang.org/wiki/Questions. If you would like to ask questions in your language, perhaps try your local community.

**Comment by liuiangang** [comment]
sorry
