### ISSUE TITLE
Infinite for loops on unsigned numbers

### ISSUE THREAD

**Issue by storyicon** [golang/go#48586]
The following code will loop indefinitely:
```golang
var a uint64 = 10
for i := a; i >= 0; i-- {
   fmt.Println("i", i)
}
```
I understand why it is like this, but I think it is counterintuitive. Like the problem of "nil interface", it is easy for developers to generate bugs.
If the go team thinks this problem should not be solved in go, I think it should at least warn developers in lint like tools.

**Comment by seankhliao** [comment]
Note staticcheck has [SA4003](https://staticcheck.io/docs/checks#SA4003) which does this, which is integrated in `gopls`

**Comment by ALTree** [comment]
> I think it is counterintuitive

It's not... `i` is an unsigned integer and your loop termination condition is "loop as long as `i` is positive", which it always is, hence the loop will never terminate.

As seankhliao pointed out, staticcheck flags this, and golint is frozen, so I don't think there's anything else to do here. Go won't add warnings to the compiler, and of course we can't make this a compilation error.

**Comment by ianlancetaylor** [comment]
The general guideline for programming should be: don't use unsigned numeric types for counters.

All computer fixed-width integer types have odd behavior.  Signed integer types have odd behavior at very large values (either positive or negative).  Unsigned integer types have odd behavior at zero.  In practice, zero is a lot more common.  So use signed integer types.
