### ISSUE TITLE
crypto/tls: why does tls1.3 not support 0rtt？

### ISSUE THREAD

**Issue by yangqingxin1993** [golang/go#48597]

**Comment by mvdan** [comment]
See https://github.com/golang/go/issues/9671#issuecomment-519091516; I'm not sure if @FiloSottile has changed his plan after two years.

**Comment by komuw** [comment]
as to the why(or why not), this blog might be of interest: https://blog.trailofbits.com/2019/03/25/what-application-developers-need-to-know-about-tls-early-data-0rtt/
