### ISSUE TITLE
x/build: one ppc64le osuosl builder is configured differently from the rest, causing failures

### ISSUE THREAD

**Issue by pmur** [golang/go#48614]
This is related to #48554, it would appear some power9 builders are configured differently.

Sometimes the test to open `/dev/rtc0` is either skipped or passes, and sometime it fails. It is not clear if this test was always skipped previously (e.g the builder had no RTC device, or was prohibited from opening it, or has an RTC which supports alarms).

Are all the power9 builders provisioned and configured identically? Likewise, is it possible to tag golang.org/x/sys CI logs with more information about which builder they have run on (I am not sure if I am overlooking this one)?

Thanks!

**Comment by pmur** [comment]
@laboger fyi.

**Comment by laboger** [comment]
@bcmills We have found that the failures from #48554 were due to this rogue p9 builder that is not set up like the others so fails in a different way. This builder is not documented and not set up like the others. This builder should be stopped/disabled so people don't waste time tracking down bugs on this builder.

**Comment by mknyszek** [comment]
CC @dmitshur @toothrot

**Comment by pmur** [comment]
I would like to shutdown the go-ppc64le-p9 builder. Does anyone object? Also, what steps are needed to deactivate a builder?

**Comment by cagedmantis** [comment]
@pmur I'm not seeing `go-ppc64le-p9` on farmer.

**Comment by laboger** [comment]
> I 'm not seeing go-ppc64le-p9 on farmer.

We had opened a ticket with OSU and Paul asked them to delete it. It is gone now and it looks like all is working as expected.
The builders now match what is documented in x/build/env/linux-ppc64le/osuosl/NOTES.

**Comment by cagedmantis** [comment]
Thank you!

**Comment by dmitshur** [comment]
Closing since I understand this is all resolved, thanks again!
