### ISSUE TITLE
Go team quiet week: issue tracker responses will be delayed

### ISSUE THREAD

**Issue by rsc** [golang/go#48615]
_The issue tracker will be quiet from September 24 to October 4, to let Go team members and contributors disconnect and either recharge for a bit or do [focused, deep work](https://knowledge.wharton.upenn.edu/article/deep-work-the-secret-to-achieving-peak-productivity/)._

Here at Google, we have been encouraging people to make sure to take time off during this incredibly stressful year and a half. We’ve observed that one problem with taking a week or two off is that various discussions, meetings, golang-dev@ threads and issues happen while we are away, creating a backlog to work through on return. And even if you’re not taking time off, keeping up with this stream of interruptions can make it difficult to focus on individual work. I’m sure you’ve all seen this in your own jobs. 

We have established regular "quiet weeks", once per quarter, with as few interruptions as possible and, for people taking time off, as little to catch up on as possible. The goals for a quiet week are:

1. Create time for people to disconnect and take a real break, without feeling like they will need to catch up on what they missed when they return.

2. Create time for people who keep working to do deep work, without all the usual interruptions like meetings and online discussions.

The week (plus weekends) starting Friday, September 24 and ending Monday, October 4 is one of our quiet weeks. We’ve cancelled all our meetings for this week and committed to not having team-wide email or chat discussions either. The same applies to public Go conversations that we are typically part of: for this week, we will not be participating in golang-dev@ nor non-trivial GitHub issue tracker conversations (like proposals or anything trying to arrive at a decision). 

We will also be disconnecting as much as possible during the quiet week from other community forums like Gopher Slack, r/golang, and golang-nuts@. The conversations there are mostly not driven by the Go team, so they won’t be as affected, but just know that we won’t be trying to keep up with those either.

When we return on October 4, we will pick up where we left off. 

– Russ Cox, for the Go team

**Comment by dougmellon** [comment]
Thank you to everyone who has contributed. Enjoy the time - well deserved.

**Comment by rsc** [comment]
Welcome back everyone!
