### ISSUE TITLE
cmd/link: relocation target type not defined

### ISSUE THREAD

**Issue by korzhao** [golang/go#48617]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go tip
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```go
package main

type Foo[T any] interface {
	CreateBar() Bar[T]
}

type Bar[T any] func() Bar[T]

func (f Bar[T]) CreateBar() Bar[T] {
	return f
}

func abc[T any]() {
	var b Bar[T] = func() Bar[T] {
		var b Bar[T]
		return b
	}
	var _ Foo[T] = b()
}

func main() {
	abc[int]()
}
```

### What did you see instead?
```error
main.main: relocation target type.noalg.main.Foo[main.T₄] not defined
```

**Comment by cuonglm** [comment]
I can't reproduce with:

```
go version devel go1.18-8854368cb0 Sat Sep 25 01:24:46 2021 +0000 darwin/arm64
```

**Comment by korzhao** [comment]
> I can't reproduce with:
> 
> ```
> go version devel go1.18-8854368cb0 Sat Sep 25 01:24:46 2021 +0000 darwin/arm64
> ```

[Cl352117 ](golang.org/cl/352117) also fixed this issue.
I think this is another case of [Cl352117 ](golang.org/cl/352117).  I want to add a test case, just to cover this.
