### ISSUE TITLE
cmd/go: remove references to 'go help fuzz'

### ISSUE THREAD

**Issue by mfrw** [golang/go#48623]
### What version of Go are you using (`go version`)?
tip

<pre>
$ go version
go version devel go1.18-8854368cb0 Sat Sep 25 01:24:46 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
I did not check for the release, but the tip of `master` branch [as of 25-Sep-2021]

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary> <br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mfrw/.cache/go-build"
GOENV="/home/mfrw/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/mfrw/g/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mfrw/g"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/mfrw/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/mfrw/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.18-8854368cb0 Sat Sep 25 01:24:46 2021 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/mfrw/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build6268976=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

`go help fuzz`

### What did you expect to see?

Help about fuzzing.

### What did you see instead?
go help fuzz: unknown help topic. Run 'go help'.

Although:

git branch --contains [2212a1a339c7ac72ff2133855c97ae097444cb5c](https://go-review.googlesource.com/c/go/+/317973)
has `master`

Maybe I am missing something trivial :(

Apologies in advance if its known already or if its by design.

**Comment by seankhliao** [comment]
[CL 351113](https://golang.org/cl/351113) removed it but apparently not all the references

**Comment by mfrw** [comment]
Can I give it a stab ?
I think we have to remove fuzz refrences for master branch.
