### ISSUE TITLE
unicode: update to version 14.0

### ISSUE THREAD

**Issue by 180909** [golang/go#48621]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/wangjiahua/go/bin"
GOCACHE="/Users/wangjiahua/Library/Caches/go-build"
GOENV="/Users/wangjiahua/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/wangjiahua/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/wangjiahua/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vj/b75wqh2n5l324xzv_88g14vm0000gn/T/go-build2079872506=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.17.1 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.17.1
uname -v: Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165
lldb --version: lldb-1300.0.32.2
Swift version 5.5-dev
</pre></details>

### What did you do?
https://play.golang.org/p/9biSMo4sTqo

### What did you expect to see?
13.0.0

### What did you see instead?
14.0.0

**Comment by mknyszek** [comment]
CC @robpike via https://dev.golang.org/owners, but since that's dated, @rsc, maybe?

**Comment by thanm** [comment]
This issue is currently in the Go 1.18 milestone -- given that we are in the freeze and we don't have any CLs for it, I think it probably makes sense to move it out of the 1.18 milestone. Please comment if this is a problem, thanks.

**Comment by dmitshur** [comment]
Support for Unicode 15.0.0 (#55079) is now implemented, so there's nothing more to do in this issue. Please comment if I missed something.
