### ISSUE TITLE
Transilotion go tour to other languages

### ISSUE THREAD

**Issue by Mustafa-Asaad-iq** [golang/go#48628]
Hi, I send message to golang-nuts@googlegroups.com
but no one responds me this is my message:

> Hi, I want to translate the go tour to my native language I have finished the first page of the tour and I want to check if everything is good so when I want to deploy the website to app engine, it's asking me for money and even when I want to get 90 days free trial my credit card been rejected! (maybe this off topic) also and I don't know how to deploy the website to app engine, it's confusing 
> so can you please give instructions to deploy the website the right way and for free 
> because that is what you say "This shouldn't cost you anything; the Tour App usually runs inside App Engine's free quota."
> 
>  in https://github.com/golang/website/blob/master/tour/TRANSLATE
> Thank you

other qustion is  why you don't just add it to the original golang website I mean like any other website the translation are in the same repository?

**Comment by seankhliao** [comment]
While the tour may run within GCP's free limits, you still need an active account with billing information attached (that's GCP policy).
Translations are unofficial and maintained by external contributors, they may not always be up to date, and it seems better maintained by people who understand the language.
