### ISSUE TITLE
cmd/go: test -fuzz gives a confusing error when types mismatch

### ISSUE THREAD

**Issue by mvdan** [golang/go#48635]
I wrote a fuzz func like:

    f.Fuzz(func(t *testing.T, src string, parserOpts uint8, printerOpts uint16) {

Then I used f.Add as follows:

    f.Add("{ (foo; bar); baz; }", 0, 0)

I got a fairly confusing error:

    fuzz_test.go:66: mismatched types in corpus entry: [echo foo 0 0], want [string uint8 uint16]

Intuitively, I thought my code was right, because the untyped constant `0` can be assigned to `uint8` and `uint16` just fine. It took me a minute to realise that, when passing `0` as an argument, it assumes the `int` type.

I think the following error message would be much easier to understand:

    fuzz_test.go:66: mismatched types in corpus entry: [string int int], want [string uint8 uint16]

or, if you want to include the values:

    fuzz_test.go:66: mismatched types in corpus entry: [string("echo foo") int(0) int(0)], want [string uint8 uint16]

**Comment by mvdan** [comment]
Another reason the current error is confusing is that `[echo foo 0 0]` looks like four arguments, when it's actually three - due to the lack of quoting.

**Comment by mvdan** [comment]
(forgot to cc @katiehockman @jayconrod on this one, doing so quietly during the quiet week...)

**Comment by cespare** [comment]
I just ran into this as well. I hope the message can be improved before 1.18; I suspect that many people are going to see it when they use fuzzing for the first time.

In my case, I had something like this:

```
f.Add("")
f.Fuzz(func(t *testing.T, b []byte) { ... })
```

which lead to this confusing message:

```
fuzzdemo_test.go:9: mismatched types in corpus entry: [], want [[]uint8]
```

Simply adding quotes helps a lot:

    mismatched types in corpus entry: [""], want [[]uint8]

Both of @mvdan's suggestions are better yet:

    mismatched types in corpus entry: [string], want [[]uint8]
    mismatched types in corpus entry: [string("")], want [[]uint8]

**Comment by katiehockman** [comment]
Thanks @mvdan for the report, and @cespare for the update. I had missed this issue during triage!

I opted for the original suggestion of `fuzz_test.go:66: mismatched types in corpus entry: [string int int], want [string uint8 uint16]`. That seems the easiest to understand.

**Comment by mvdan** [comment]
Thank you! Certainly a simple change, but will be nice for the UX :)
