### ISSUE TITLE
cmd/go: test -fuzz seems to print a few "FAIL" lines when stopped via SIGINT

### ISSUE THREAD

**Issue by mvdan** [golang/go#48633]
For example, with https://github.com/mvdan/sh as a sample module that has a fuzz function:

```
$ git clone https://github.com/mvdan/sh
$ cd sh
$ git checkout 3d62b69e2043d02c69d7d0efaef371cf9dfcded0
$ cd syntax
$ go version
go version devel go1.18-aeea5bacbf Sat Sep 25 17:12:41 2021 +0000 linux/amd64
$ go test -run=- -vet=off -fuzz=Quote
fuzz: elapsed: 0s, gathering baseline coverage: 0/142 completed
fuzz: elapsed: 0s, gathering baseline coverage: 142/142 completed, now fuzzing with 16 workers
fuzz: elapsed: 3s, execs: 899119 (299642/sec), interesting: 0
fuzz: elapsed: 6s, execs: 1772118 (295318/sec), interesting: 0
^CFAIL
FAIL
FAIL
FAIL
fuzz: elapsed: 7s, execs: 1971588 (293890/sec), interesting: 0
PASS
ok  	mvdan.cc/sh/v3/syntax	6.728s
```

I imagine that the FAIL ourput lines shouldn't happen at all; nothing has failed, I've just stopped the fuzzing after a few seconds. The final line even says "ok" :)

cc @katiehockman @jayconrod

**Comment by mvdan** [comment]
Thank you for the quick turnaround!

**Comment by katiehockman** [comment]
@mvdan can you clarify whether this is happening every time you run this, or if it's just a flaky issue that you run into? My suspicion is that there's just some extraneous FAIL message coming from a worker that was interrupted, which is what you're seeing, but it's hard to be sure.

**Comment by mvdan** [comment]
The number of FAIL lines varies each time. I have 16 logical CPU cores, so the fuzzer launches 16 workers. Sometimes I see just a few FAIL lines, some other times I see over a dozen.

I don't think I've ever seen zero FAIL lines after a ^C. I just tried six times in a row, and it always showed at least a handful each time. So it's definitely not a rare occurrence for me.

**Comment by katiehockman** [comment]
I was just able to reproduce this locally even with the change that I mailed. So there is something else going on. (At best, my change will simply decrease the number of "FAIL" lines that occur, which doesn't really fix the issue)

**Comment by katiehockman** [comment]
I am still not sure how we are going to fix this, but I've at least narrowed it down to https://github.com/golang/go/blob/master/src/cmd/go/internal/test/test.go#L1797. When I run this locally with my patch, this is the `FAIL` line that is being printed (i.e. the one coming from the main go command process). Will look into how to avoid this.
