### ISSUE TITLE
Adding custom marshaller to value of a map removes the map from the output

### ISSUE THREAD

**Issue by robbyriverside** [golang/go#48634]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/robby/Library/Caches/go-build"
GOENV="/Users/robby/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/robby/golang/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/robby/golang:/Users/robby/projects:/Users/robby/toonavox"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/robby/samples/marshal/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7r/87xkrl_10yd6sk9qplnyzp5w0000gn/T/go-build4064495216=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
A simple example of adding a custom MarshalJSON.

Adding the MarshalJSON the map disappears from the output.
If I remove the custom marshaller, the Maps value is in the output.

https://play.golang.org/p/h6S-CFbUPgk

### What did you expect to see?
{
  "Value": false,
  "Properties": {
    "foo": "bar"
  },
  "Maps": {
    "one": {
      "Value": false,
      "Properties": {
        "one": "two"
      }
    }
  }
}

### What did you see instead?
{
  "Value": false,
  "Properties": {
    "foo": "bar"
  }
}

**Comment by AndrewHarrisSPU** [comment]
The root cause is related to this, I think (from the official spec):

> Given a struct type S and a defined type T, promoted methods are included in the method set of the struct as follows:
> 
> If S contains an embedded field T, the method sets of S and *S both include promoted methods with receiver T. The method set of *S also includes promoted methods with receiver *T.
> If S contains an embedded field *T, the method sets of S and *S both include promoted methods with receiver T or *T.

So in that sense it's working as intended, the `MarshalJSON` method `*M` is a promoted method on a `Top`. Two ideas that I could think of:

1. https://play.golang.org/p/DgH6kgO4Q6n (using a field name rather than embedding *M; slightly different from your expected output)
2. https://play.golang.org/p/sKtLiglB7s7 (less typing, and using "omit empty"; matches your expected output)

Hope this helps!

**Comment by seankhliao** [comment]
See above

For questions please refer to https://github.com/golang/go/wiki/Questions
