### ISSUE TITLE
x/tools/internal/typeparams failed to build x/tools@v0.1.6, types.Inferred is undefined

### ISSUE THREAD

**Issue by johejo** [golang/go#48632]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-aeea5bacbf Sat Sep 25 17:12:41 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

no, tip only

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/johejo/.cache/go-build"
GOENV="/home/johejo/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/johejo/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/johejo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/johejo/ghq/github.com/golang/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/johejo/ghq/github.com/golang/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.18-aeea5bacbf Sat Sep 25 17:12:41 2021 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/johejo/ghq/github.com/golang/tools/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3362662141=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
git clone https://github.com/golang/tools.git
cd tools/
git checkout v0.1.6
gotip build ./...
```

### What did you expect to see?

build succeeds

### What did you see instead?

```
# golang.org/x/tools/internal/typeparams
internal/typeparams/typeparams_go118.go:144:7: info.Inferred undefined (type *types.Info has no field or method Inferred)
internal/typeparams/typeparams_go118.go:144:42: undefined: types.Inferred
internal/typeparams/typeparams_go118.go:155:10: info.Inferred undefined (type *types.Info has no field or method Inferred)
internal/typeparams/typeparams_go118.go:158:14: info.Inferred undefined (type *types.Info has no field or method Inferred)
```

build succeeds in x/tools@ba6b94c735d2f7b74804e255e653a4292074ae76

Is there any plan to tag x/tools@v0.1.7?

**Comment by mvdan** [comment]
cc @findleyr

**Comment by findleyr** [comment]
Thank you for reporting. This was an oversight: we should have avoided tagging v0.1.6 with this API usage.

We'll tag v0.1.7 this week, and will probably have to retract v0.1.6. Sorry for the breakage.

**Comment by findleyr** [comment]
We've tagged x/tools@v0.1.7, which should fix the build breakage. For that version we've guarded usage of the new APIs behind a build constraint, in case they change again.

Closing. Sorry again for the breakage.

**Comment by mvdan** [comment]
Thanks for the quick fix!
