### ISSUE TITLE
go/types, types2: recursive call of generic function with concrete type argument fails

### ISSUE THREAD

**Issue by griesemer** [golang/go#48638]
```Go
package p
func g[P any](x P) {
        g[int](x)
}
```
does not type-check:
```
cannot use x (variable of type parameter P constrained by interface{}) as int value in argument to g[int]
```
[edited]: This looks like a correct error message after all: If `g` is called as `g[string]("foo")`, the type of `x` would be `string` and the local call `g[int](x)` would be incorrect.

**Comment by ianlancetaylor** [comment]
> ```Go
> package p
> func g[P any](x P) {
>         g[int](x)
> }
> ```

Is this code permitted at all?  It is a recursive reference from `g` to itself with a different set of type arguments.

**Comment by griesemer** [comment]
Agreed that this code should not be permitted because the argument `x` in the local call of `g` is of type `P` (which we don't know anything about) but that call requires the argument to be of type `int` (per the instantiation of `g`). In the first recursive call, `x` will be of type `int` but that's "too late".
