### ISSUE TITLE
cmd/go: add a test for coverage guidance while fuzzing

### ISSUE THREAD

**Issue by katiehockman** [golang/go#48654]
There are currently no tests today that can verify any potential regressions in the coverage guidance while fuzzing. For example, https://go-review.googlesource.com/c/go/+/351316 was merged which caused a major regression and removed ~all coverage guidance with `go test -fuzz`, but there weren't any tests that could catch this.

One tricky part of writing a test like this will be to avoid flakiness.

/cc @golang/fuzzing

**Comment by toothrot** [comment]
Friendly ping that this issue is marked as a release-blocker for Go 1.18.
