### ISSUE TITLE
Installing github.com/go-delve/delve/cmd/dlv@master FAILED

### ISSUE THREAD

**Issue by assdddddff** [golang/go#48661]
### What version of Go are you using (`go version`)?

<pre>
$ 1.57

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ window

</pre></details>

### What did you do?

install extension tools

### What did you expect to see?
install successfully

### What did you see instead?
Installing github.com/go-delve/delve/cmd/dlv@master FAILED
{
 "killed": false,
 "code": 1,
 "signal": null,
 "cmd": "C:\\Program Files\\Go\\bin\\go.exe get -v -d github.com/go-delve/delve/cmd/dlv@master",
 "stdout": "",
 "stderr": "go get: github.com/go-delve/delve/cmd/dlv@master: invalid version: Get \"https://goproxy.cn/github.com/go-delve/delve/cmd/dlv/@v/master.info\": Method Not Allowed\n"
}

1 tools failed to install.

dlv-dap: failed to install dlv-dap(github.com/go-delve/delve/cmd/dlv@master): Error: Command failed: C:\Program Files\Go\bin\go.exe get -v -d github.com/go-delve/delve/cmd/dlv@master
go get: github.com/go-delve/delve/cmd/dlv@master: invalid version: Get "https://goproxy.cn/github.com/go-delve/delve/cmd/dlv/@v/master.info": Method Not Allowed
 no output

**Comment by seankhliao** [comment]
This looks like a problem with goproxy.cn, please report to them
