### ISSUE TITLE
Build Error while go test -coverprofile

### ISSUE THREAD

**Issue by xiaozhoz** [golang/go#48664]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/var/lib/gitlab-runner/.cache/go-build"
GOENV="/var/lib/gitlab-runner/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/var/lib/gitlab-runner/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/var/lib/gitlab-runner/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/data/gitlab-runner/builds/sbx9DFU_/0/root/paas_go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2986009875=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

if i run with `/usr/local/go/bin/go test paas/common/util  -tags integration -v -failfast`, everything's good
```
gitlab-runner@ubuntu:/data/gitlab-runner/builds/sbx9DFU_/0/root/paas_go$ /usr/local/go/bin/go test paas/common/util  -tags integration -v -failfast
=== RUN   Test_generateFilePath
=== RUN   Test_generateFilePath/t1
=== RUN   Test_generateFilePath/t2
=== RUN   Test_generateFilePath/t3
=== RUN   Test_generateFilePath/t4
=== RUN   Test_generateFilePath/t5
--- PASS: Test_generateFilePath (0.00s)
    --- PASS: Test_generateFilePath/t1 (0.00s)
    --- PASS: Test_generateFilePath/t2 (0.00s)
    --- PASS: Test_generateFilePath/t3 (0.00s)
    --- PASS: Test_generateFilePath/t4 (0.00s)
    --- PASS: Test_generateFilePath/t5 (0.00s)
=== RUN   TestSortedStringsContains
=== RUN   TestSortedStringsContains/test_empty
=== RUN   TestSortedStringsContains/test_empty1
=== RUN   TestSortedStringsContains/test_empty2
=== RUN   TestSortedStringsContains/test_blank_string
=== RUN   TestSortedStringsContains/test_blank_string1
=== RUN   TestSortedStringsContains/test_with_un-ordered_string
=== RUN   TestSortedStringsContains/test_with_partial_string
=== RUN   TestSortedStringsContains/test_case_sensitive
=== RUN   TestSortedStringsContains/test_case_unsensitive
=== RUN   TestSortedStringsContains/test_chinses_case
--- PASS: TestSortedStringsContains (0.00s)
    --- PASS: TestSortedStringsContains/test_empty (0.00s)
    --- PASS: TestSortedStringsContains/test_empty1 (0.00s)
    --- PASS: TestSortedStringsContains/test_empty2 (0.00s)
    --- PASS: TestSortedStringsContains/test_blank_string (0.00s)
    --- PASS: TestSortedStringsContains/test_blank_string1 (0.00s)
    --- PASS: TestSortedStringsContains/test_with_un-ordered_string (0.00s)
    --- PASS: TestSortedStringsContains/test_with_partial_string (0.00s)
    --- PASS: TestSortedStringsContains/test_case_sensitive (0.00s)
    --- PASS: TestSortedStringsContains/test_case_unsensitive (0.00s)
    --- PASS: TestSortedStringsContains/test_chinses_case (0.00s)
=== RUN   TestRoundTimeToDay
=== RUN   TestRoundTimeToDay/t1
--- PASS: TestRoundTimeToDay (0.00s)
    --- PASS: TestRoundTimeToDay/t1 (0.00s)
PASS
ok      paas/common/util        0.003s
```

when i add coverprofile flag, run with `go test paas/common/util  -tags integration -v -failfast -coverprofile=profile.cov`, there is a build error.
```
gitlab-runner@ubuntu:/data/gitlab-runner/builds/sbx9DFU_/0/root/paas_go$ /usr/local/go/bin/go test paas/common/util  -tags integration -v -failfast -coverprofile=profile.cov
# paas/common/util
vet: $WORK/b059/json.cover.go:1:1: expected 'package', found 'EOF'
FAIL    paas/common/util [build failed]
FAIL
```

the only difference between two commands was `-coverprofile=profile.cov`, how does it lead to an error?
I cannot find `json.cover.go` on my machine or on the Internet. where is it from?

### What did you expect to see?

coverprofile flag should not cause error. or give more error information 

### What did you see instead?

error

**Comment by seankhliao** [comment]
I assume you have a `json.go` file in your package? Then `json.cover.go` would be the generated version with coverage instrumentation
As to what's causing the issue, it's difficult to tell without a reproducer

**Comment by xiaozhoz** [comment]
@seankhliao thx for you reply. 
There is no `json.go` file in my package. Actually there is no empty `*.go` file in my machine. don't know where it comes from.

However, the problem solved. I modified my `go.mod` file, replaced `go 1.14` to `go 1.17`. Everything's good, but I don't know why.

My another question is, is there a way to make `go` output more messages while encountering an error? like a verbose flag?

**Comment by seankhliao** [comment]
See `go help build`
