### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by xmg520** [golang/go#48672]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rome/Library/Caches/go-build"
GOENV="/Users/rome/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/rome/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/rome/go"
GOPRIVATE=""
GOPROXY="https://mirrors.aliyun.com/goproxy/,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/30/3946w0js4fb09wxth1xrnwb80000gn/T/go-build4110193043=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Follow the website tutorial to write code

### What did you expect to see?

Replace it says With this web server running, a visit to http://localhost:8080/view/test should show a page titled "test" containing the words "Hello world". with it says With this web server running, a visit to http://localhost:8080/view/TestPage should show a page titled "test" containing the words "Hello world".

### What did you see instead?

https://golang.org/doc/articles/wiki/

it says With this web server running, a visit to http://localhost:8080/view/test should show a page titled "test" containing the words "Hello world".

In fact, Testpage is written above，Not test

The correct way to write it is http://localhost:8080/view/TestPage

Thanks

**Comment by seankhliao** [comment]
There's this section which instructs you to create a test file:
> Open test.txt file in your editor, and save the string "Hello world" (without quotes) in it.
