### ISSUE TITLE
[dev.boringcrypto.go1.17] net/http/httptest: add fipsonly compliant certificate in for NewTLSServer()

### ISSUE THREAD

**Issue by saurabhsuniljain** [golang/go#48674]
### What version of Go are you using (`go version`)?

<pre>
$ go version
dev.boringcrypto.go1.17 
go version devel +6d5f0ff Tue Mar 23 16:43:45 2021 +0100 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/bld/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/bld"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel +6d5f0ff Tue Mar 23 16:43:45 2021 +0100"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/bld/src/daintree/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2061024702=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I am using dev.boringcrypto branch for fips compliance in my code.  I am facing issues while writing tests using `httptest.NewTLSServer()`

### Code: 
In my code I have an http client which I makes https GET calls.

### Testing: 
While writing tests I am using `NewTLSServer` function of `httptest` package for mocking the server. Then I am using Client() method of mock server created. Then I am calling my function which makes the https GET calls (that function will use the client that I got from mock server).

As my code has `import _ "crypto/tls/fipsonly"` the test fails. Client fails to verify the server certificate with below error.

```
http: TLS handshake error from 127.0.0.1:57328: remote error: tls: bad certificate
x509: certificate specifies an incompatible key usage
```

The issue is the default cert that is used by `NewTLSServer` method of `httptest` package is not fipsonly compliant. 
The cert could be found in this [file](https://github.com/golang/go/blob/dev.boringcrypto.go1.17/src/net/http/internal/testcert/testcert.go).

Also the test `ExampleConfig_keyLogWriter` [here](https://github.com/golang/go/blob/dev.boringcrypto.go1.17/src/crypto/tls/example_test.go#L99) seems to enable `InsecureSkipVerify` and has the comment  `// test server certificate is not trusted.`.

Playground link - https://play.golang.org/p/ahA8mKd7sRr (`import _ "crypto/tls/fipsonly"` not present as playground doesn't work on boring crypto branches.)

You can add missing import and repro the issue locally.

**Note**: The code also is bit flaky as it is dependent on multiple goroutine execution. One in 2-3 execution the http GET request would succeed, in other cases select loop will timeout.

### What did you expect to see?
Expected the client returned by httptest Server to be compatible and usable in testing, instead we being required to create our own client and set `InsecureSkipVerify` to true for testing.

### What did you see instead?
Client returned by httptest Server (NewTLSServer()) is not compatible in boring crypto branches.

**Comment by mknyszek** [comment]
CC @neild and maybe @FiloSottile ?

**Comment by neild** [comment]
@gopherbot please open backport issues
