### ISSUE TITLE
x/website GitHub stars in go.pkg.dev

### ISSUE THREAD

**Issue by gkarthiks** [golang/go#48676]
### What did you expect to see?

Upon loading any module in the go.pkg.dev, it would be great to see the star count as well if the module is from GitHub.

**Comment by mvdan** [comment]
Have you seen related issues like https://github.com/golang/go/issues/41805?

GitHub is just one hosting provider, so it seems wrong to hardcode features just for it. Plus, stars rarely mean anything on their own. I think some form of "popularity score" or "quality score" could be interesting to do (see the issue above), but it certainly can't be just stars.

**Comment by seankhliao** [comment]
See also #36952

**Comment by gkarthiks** [comment]
apologies, I will close this issue., I can understand why not GitHub stars definitely too.
