### ISSUE TITLE
x/website: https://golang.org

### ISSUE THREAD

**Issue by cprathermsu** [golang/go#48681]
### What version of Go are you using (`go version`)? 1.15.8

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?

I have a user who is attempting to curl the golang site. All attempts are met with connection reset by peer (pasted below). The user is able to telnet golang.org 443 successfully. Traceroutes and tcptraceroutes are getting to the golang server but the connection is getting reset. Are there any known issues with connection resets in conjunction with golang.org? 

curl -v https://golang.org
*   Trying x.x.x.x:443...
* Connected to golang.org (x.x.x.x) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to golang.org:443
* Closing connection 0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to golang.org:443

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by seankhliao** [comment]
What address is it actually connecting to?

**Comment by cprathermsu** [comment]
Thank you Sean. I apologize. like a dummy, I x'ed out the dst IPs: 
src: 10.x.x.x
dst: 142.250.72.17
service: 443

**Comment by cprathermsu** [comment]
WOPR gin # traceroute golang.org
traceroute to golang.org (142.250.72.17), 30 hops max, 60 byte packets
1  -x.x.x.net (x.x.x.x)  2.724 ms  2.690 ms  2.664 ms
2  -x.x.x.net (x.x.x.x)  0.128 ms  0.330 ms  0.316 ms
3  -x.x.x.net (x.x.x.x)  0.195 ms  0.236 ms  0.556 ms
4  -x.x.x.net (x.x.x.x)  0.327 ms  0.377 ms  0.368 ms
5  -x.x.x.net (x.x.x.x)  2.532 ms  2.504 ms  2.493 ms
6  den08s06-in-f17.1e100.net (142.250.72.17)  4.218 ms  4.246 ms  4.264 ms

sudo tcptraceroute golang.org 443
traceroute to golang.org (142.250.72.17), 30 hops max, 60 byte packets
1  -x.x.x.net (x.x.x.x)  1.072 ms  1.052 ms  1.045 ms
2  -x.x.x.net (x.x.x.x)  0.149 ms  0.146 ms  0.355 ms
3  -x.x.x.net (x.x.x.x)  2.229 ms  2.216 ms  2.260 ms
4  -x.x.x.net (x.x.x.x)  0.350 ms  0.389 ms  0.379 ms
5  -x.x.x.net (x.x.x.x)  33.083 ms  33.088 ms  33.094 ms
6  den08s06-in-f17.1e100.net (142.250.72.17) <syn,ack>  2.292 ms  2.380 ms  2.425 ms

**Comment by cprathermsu** [comment]
![GoLand-Conn-Reset-09292021](https://user-images.githubusercontent.com/89881831/135319783-33addd12-d053-4f33-85d3-6ab429a98f2a.JPG)

**Comment by seankhliao** [comment]
Is it just for golang.org or other sites as well (both Google and non Google sites)?

**Comment by cprathermsu** [comment]
Problem is fixed
