### ISSUE TITLE
Valid Unicode Codepoint Emojis Not Permitted in Runes

### ISSUE THREAD

**Issue by JulianKnodt** [golang/go#48683]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.17.1, playground version

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

Fails on playground.

### What did you do?

https://play.golang.org/p/GKmXPxtK52x

### What did you expect to see?

I expected it to compile and print the emoji character.

### What did you see instead?

Compilation fails, as it appears that the unicode is not a valid rune. This also happens for other sets of valid unicode code points, such as `weightlifter = U+1F3CB`.

It also seems to error either as multiple characters in rune literal, or invalid character in rune.

**Comment by seankhliao** [comment]
Your "rune" has a trailing code point https://play.golang.org/p/FUpPZyI8aa3

**Comment by JulianKnodt** [comment]
Hm, so it only works for a certain set of unicode characters which have a fixed number of code points?
Is it possible to update the compiler's error message for this case? It seems to be a strange edge case considering that it is not easily identifiable from just looking at the character itself.

I understand that runes can't support this case, but just saying "illegal character" is hard to understand.

**Comment by ianlancetaylor** [comment]
The error I see from the compiler is

x.go:8:14: more than one character in rune literal

That seems reasonably clear.  A rune literal can only include a single code point.  See https://golang.org/ref/spec#Rune_literals .

**Comment by JulianKnodt** [comment]
I think in `go vet` I'm getting the error that it's an illegal rune literal:
![image](https://user-images.githubusercontent.com/7675847/135384732-b181c9ee-73d2-47c0-8c07-ae99c5628107.png)
but probably nothing actionable.

Thanks anyhow!
