### ISSUE TITLE
Golang Call DLL In Windows,But DLL Func "Puts("XXX")" Not Work!

### ISSUE THREAD

**Issue by zld126126** [golang/go#48680]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.16

</pre>

### Does this issue reproduce with the latest release?
I dont know...

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env 
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=direct
set GOROOT=C:\Users\Administrator\go\bin\go1.16
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\Administrator\go\bin\go1.16\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\go_project\Go_GameFramework\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build3580930371=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
I want to run a DLL In Golang In Windows~

### What did you expect to see?
DLL CALL BACK SUCCESS **But I Found DLL Func C.Puts("") Not **Work!!!****

### What did you see instead?
DLL CODE:
...
extern "C" __declspec(dllexport) event * Go_event_new(struct event_base *m_pEventBase, event_callback_fn fn, void *ctx){
	printf("call Go_event_new");
	return event_new(m_pEventBase, -1, EV_PERSIST, fn, ctx);
}
...

GOLANG CODE:
...
ret, _, err := p.syscall.NewLazyDLL(s).NewProc(Go_event_new).Call(a...)
if err != nil && !IsFinishError(err) {
	logrus.WithField("err", fmt.Sprintf("%+v", err)).Errorln(`CppApplication Cpp_event_add err`)
}
return ret
...

I REALY NEED HELP !!! Please !!!

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
