### ISSUE TITLE
x/mobile: example ivy demo on ios should not require a Go installation

### ISSUE THREAD

**Issue by robpike** [golang/go#48694]
The ")demo" special command runs an interactive demonstration of ivy's abilities, but only prints an error message about the lack of a Go compiler when on iOS.

Fix that. Might require a change to how the demo runs in ivy proper, but should be isolatable to mobile if that makes more sense.

**Comment by mknyszek** [comment]
CC @hyangah via https://dev.golang.org/owners

**Comment by robpike** [comment]
Actually it's probably my job to fix this.

**Comment by ydnar** [comment]
@robpike does it work on macOS?

**Comment by robpike** [comment]
Yes, provided there is a Go compiler installed.
