### ISSUE TITLE
goroutine:  weird output, maybe it's a bug.

### ISSUE THREAD

**Issue by mocowo** [golang/go#48697]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 darwin/amd64
</pre>

### What did you do?

```
package main

import (
        "fmt"
        "time"
)

func main() {
        var y int32 = 1
        go func() {
                for {

                        y++
                        //fmt.Println( y)
                }
        }()
        time.Sleep(time.Second)
        fmt.Println("y=", y)

}
```

This will output 1. But, if cancel the //fmt.Println( y) comment in goroutine, it will print a big number. 
It' s strange. I guess, the two goroutine is running on different kernel of CPU, and the y value is in different register.

Hope Go can handle these weird scenarios like this.

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.

You have a data race. You can find help in one of the forums linked above.
