### ISSUE TITLE
x/text: "€" is incorrectly encoded as "\x80" in GB18030 (should have been "\xA2\xE3")

### ISSUE THREAD

**Issue by kennytm** [golang/go#48691]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Playground.

https://play.golang.org/p/ELVa9gu69JX

### What did you do?

Encode "€" (U+20AC). 

```go
package main

import (
	"fmt"
	"golang.org/x/text/encoding/simplifiedchinese"
)

func main() {
	s, _ := simplifiedchinese.GB18030.NewEncoder().String("€")
	if s != "\xA2\xE3" {
		panic(fmt.Sprintf("%x", s))
	}
}
```

### What did you expect to see?

Pass.

### What did you see instead?

```
panic: 80

goroutine 1 [running]:
main.main()
	/tmp/sandbox2937657549/prog.go:11 +0xb9
```

The character "€" is encoded into "\x80". This is a propriety extension by Microsoft in CP936 (GBK). In GB18030 standard the [proper encoding](https://en.wikipedia.org/wiki/GB_18030#cite_note-4) should be "\xA2\xE3". 

While the GB18030 *decoder* recognizes both "\x80" and "\xA2\xE3" as "€" (as it should), the *encoder* should prefer to generate "\xA2\xE3" over the non-standard "\x80".

**Comment by AlexanderYastrebov** [comment]
The question is whether GB18030 should actually decode `\x80` into `€` as the subject suggests:
> While the GB18030 decoder recognizes both "\x80" and "\xA2\xE3" as "€" (as it should)

From https://en.wikipedia.org/wiki/GB_18030#cite_note-4
> The euro sign is an exception which is given a single byte code of 0x80 in Microsoft's later versions of CP936/GBK and a two byte code of A2 E3 in GB18030.

From https://icu-project.org/docs/papers/gb18030.html
> Note: Like some GBK implementations, the original publication of GB 18030-2000 assigned the Euro currency symbol to the single byte 0x80. The updated mapping table from November leaves 0x80 unassigned and instead maps 0xa2e3 U+20ac for the Euro symbol.

E.g. iconv uses `\x80` in GBK and `\xa2\xe3` in GB18030 and does not cross-decode:
```
$ echo -n € | iconv -f UTF-8 -t GBK | xxd
00000000: 80                                       .
$ echo -n € | iconv -f UTF-8 -t GB18030 | xxd
00000000: a2e3                                     ..
$ echo -n € | iconv -f UTF-8 -t GBK | iconv -f GB18030 -t UTF-8
iconv: illegal input sequence at position 0
$ echo -n € | iconv -f UTF-8 -t GB18030 | iconv -f GBK -t UTF-8
iconv: illegal input sequence at position 0
```

Java on the other hand seems to treat GBK equal to GB18030:
```java
import java.io.UnsupportedEncodingException;

class Go48691 {

    public static void main(String[] args) throws UnsupportedEncodingException {
        System.out.print("encode GBK: ");
        for (byte b : "€".getBytes("GBK")) {
            System.out.format("%x", b);
        }
        System.out.println();

        System.out.print("encode GB18030: ");
        for (byte b : "€".getBytes("GB18030")) {
            System.out.format("%x", b);
        }
        System.out.println();

        System.out.format("decode 1 GBK: %s\n", new String(new byte[]{(byte)0x80}, "GBK"));
        System.out.format("decode 1 GBK: %s\n", new String(new byte[]{(byte)0x80}, "GB18030"));

        System.out.format("decode 2 GBK: %s\n", new String(new byte[]{(byte)0xa2, (byte)0xe3}, "GBK"));
        System.out.format("decode 2 GB18030: %s\n", new String(new byte[]{(byte)0xa2, (byte)0xe3}, "GB18030"));
    }
}
```
```
encode GBK: a2e3
encode GB18030: a2e3
decode 1 GBK: �
decode 1 GBK: �
decode 2 GBK: €
decode 2 GB18030: €
```

**Comment by AlexanderYastrebov** [comment]
According to https://encoding.spec.whatwg.org/#gbk-decoder and https://encoding.spec.whatwg.org/#gb18030-decoder
> GBK’s decoder is gb18030’s decoder.
> If byte is 0x80, return code point U+20AC.

i.e. both should decode `\x80` and `\xA2\xE3`. 

According to https://encoding.spec.whatwg.org/#gbk-encoder and https://encoding.spec.whatwg.org/#gb18030-encoder
> GBK’s encoder is gb18030’s encoder with its is GBK set to true.
> If is GBK is true and code point is U+20AC, return byte 0x80.
