### ISSUE TITLE
set GOMIPS=softfloat but show error syntax error: unexpected word (expecting ")")

### ISSUE THREAD

**Issue by zhizunbao84** [golang/go#48692]
i use go version go1.17.1 linux/amd64

i have a device with cpu look like below:
```
cat /proc/cpuinfo
system type : 96848EG2F2V1_UX
processor : 0
cpu model : Broadcom BMIPS4350 V8.1
BogoMIPS : 598.01
wait instruction : yes
microsecond timers : yes
tlb_entries : 32
extra interrupt vector : no
hardware watchpoint : no
ASEs implemented :
shadow register sets : 1
kscratch registers : 0
core : 0
VCED exceptions : not available
VCEI exceptions : not available

processor : 1
cpu model : Broadcom BMIPS4350 V8.1
BogoMIPS : 606.20
wait instruction : yes
microsecond timers : yes
tlb_entries : 32
extra interrupt vector : no
hardware watchpoint : no
ASEs implemented :
shadow register sets : 1
kscratch registers : 0
core : 0
VCED exceptions : not available
VCEI exceptions : not available
```

i test it with the simple program：
```
package main

import "fmt"

func main() {
	fmt.Print("hello,world")
}
```

i build with `GOOS=linux GOARCH=mips GOMIPS=softfloat CGO_ENABLED=0 go build`  and get hello, but when i run ./hello in my device, it `thell:line 1: syntax error: unexpected word (expecting ")")`

also i build with `GOOS=linux GOARCH=mipsle GOMIPS=softfloat CGO_ENABLED=0 go build`  and get hello, but when i run ./hello in my device, it thell:
```
./hello: line 8:EL▒▒    ▒ !▒D▒▒$
▒f▒▒"▒▒▒▒5
"<tz▒<
d{▒۶▒d▒
       ▒▒D▒\+8▒< ▒B$4<7!$
% q ▒▒t0$*▒▒▒

▒=A
A▒0b▒h
8}= ▒b
$
 $
▒▒▒*@F!$: not found
./hello: line 9: syntax error: unexpected ")"
```

**Comment by zhizunbao84** [comment]
i test it again.

i build with `GOOS=linux GOARCH=mips GOMIPS=softfloat CGO_ENABLED=0 go build -ldflags "-s -w"` and get hello, but when i run ./hello in my device, it thell: `line 1: syntax error: unexpected "("`

also i build with `GOOS=linux GOARCH=mipsle GOMIPS=softfloat CGO_ENABLED=0 go build  -ldflags "-s -w"` and get hello, but when i run ./hello in my device, it thell: `line 2: syntax error: unexpected "(" (expecting ")")`

**Comment by zhizunbao84** [comment]
my device info:

uname -a:
`Linux (none) 3.4.11-rt19 #1 SMP PREEMPT Fri Nov 20 00:26:52 CST 2020 mips GNU/Linux`

cat /proc/version:
`Linux version 3.4.11-rt19 (jenkins_wang@jenkins) (gcc version 4.6.2 (Buildroot 2011.11) ) #1 SMP PREEMPT Fri Nov 20 00:26:52 CST 2020`

**Comment by cherrymui** [comment]
It appears your machine executes the binary as a shell script? This is weird. What is the output of `file hello`?

Also, is your machine little endian or big endian?  You should use GOARCH=mips if it is big endian, GOARCH=mipsle if it is little endian.

**Comment by zhizunbao84** [comment]
the shell of my device is /bin/sh, is it a problem?
