### ISSUE TITLE
Is there a way to release memory manually? same as unset('value')

### ISSUE THREAD

**Issue by shuidaan** [golang/go#48696]
Excuse me, is there a way to release memory manually?

When there are a lot of concurrent accesses, the speed of memory release becomes a little important. Of course, when the concurrency is relatively small, a little waste of memory will not have a great impact on the system.

Especially now many people use tinygo to run on the MCU (singlechip). When the memory is used up, it will be released immediately, which is a little important.

Just like today's cars, they generally have automatic and manual gears, which can also be called automated manual transmission (AMT), which can be selected according to the needs of users. Improve user experience.

当并发访问量很多的时候，内存释放的速度变的有点重要。当然并发量比较少的时候，一点点内存的浪费对系统不会有太大影响。
尤其现在有很多人使用tinygo运行在单片机mcu之上，当内存使用完之后，马上被释放掉，显得有点重要了。
就好像现在汽车，一般都有自动档和手动挡，也可以叫作（Automated manual transmission ，AMT ），可以按照使用者的需要进行选择。提升用户使用体验。

**Comment by ALTree** [comment]
The answer is no: there's no `free` in Go. You can call [`runtime.GC`](https://pkg.go.dev/runtime#GC) to force a garbage collection, but there's no way to manually de-allocate memory. Also see #43582.

Closing here.
