### ISSUE TITLE
x/pkgsite: Package-level example not showing up on pkg.go.dev

### ISSUE THREAD

**Issue by spakin** [golang/go#48705]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/spakin/accumimage
 
### What is your user agent?
 

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36
 
### Screenshot
 

![accumimage](https://user-images.githubusercontent.com/650041/135509860-8076ef41-e982-4bf6-bc5c-6d5f3654c0a8.png)
 
### What did you do?
 

My GitHub repository, https://github.com/spakin/accumimage, contains a package-level example (no `Output:`) in [`scaledown_test.go`](https://github.com/spakin/accumimage/blob/effdf6f4a7fa22b636f1085260d6615038d9245e/scaledown_test.go).  This is not showing up when I view the page on https://pkg.go.dev/github.com/spakin/accumimage.  However, it does show up when I run `godoc -ex .` from the command line so I don't *think* my expression of the example is erroneous.
 
### What did you expect to see?

I expected to see an Examples section in the documentation with my example code listed.
 
### What did you see instead?

Nothing.  The page went right from Overview to Index.  An Examples section appears nowhere on the page.

**Comment by seankhliao** [comment]
Examples can't have arguments, `go vet` warns about this

**Comment by spakin** [comment]
Got it.  I'll remove the arguments and try again.  Thanks for the prompt response.
