### ISSUE TITLE
cmd/go: tests fail on linux-386-longtest due to untrusted CA

### ISSUE THREAD

**Issue by heschi** [golang/go#48700]
I think I've seen references to a LetsEncrypt CA trust chain expiring. Looks like the linux-386 builders are old enough to not trust the newer chain, maybe?

```
            go: module vcs-test.golang.org/insecure/go/insecure: git ls-remote -q origin in $WORK/gopath/pkg/mod/cache/vcs/a7b3b292787ccbf8e12c123e56b6ef2645bb1a8765494a8c7c0c4434893b4827: exit status 128:
            	fatal: unable to access 'https://vcs-test.golang.org/git/insecurerepo/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```

https://build.golang.org/log/6e5c8ce27cf161e6468d0ebfbad37d47cc365cdb
cc @golang/release

**Comment by bcmills** [comment]
I think this is a builder issue more than a `cmd/go` issue, except to the extent that the `cmd/go` tests should be more hermetic (which is not something we can fix easily or quickly).

The `go` command in general ought to be able to assume that the user has a valid set of root CAs, and the `longtest` builder really should be testing the “fetch a module from a secure VCS” paths.

**Comment by bcmills** [comment]
This also affects the `linux-amd64-longtest` builder now that #48699 has cleared.

**Comment by heschi** [comment]
I believe @cagedmantis fixed this. Thanks!

**Comment by cagedmantis** [comment]
I rebuilt the linux-x86-stretch container. This seemed to fix the issue.
