### ISSUE TITLE
I'm honestly unsure how useful this is compared to the typical `, ok` pattern. One of the things that I like about Go is that complexity typically moves vertically, rather than horizontally. For instance, I personally find

### ISSUE THREAD

**Issue by vinomeran** [golang/go#48732]
I'm honestly unsure how useful this is compared to the typical `, ok` pattern. One of the things that I like about Go is that complexity typically moves vertically, rather than horizontally. For instance, I personally find

```go
envVar, ok := os.LookupEnv("SOME_ENV_VARIABLE")
if !ok {
    envVar = "default value"
}
```
much more readable than
```go
envVar := optional.Of(os.LookupEnv("SOME_ENV_VARIABLE")).Default("default value").Must()
```

I guess what I am getting at is, what are the benefits of `Optional[T]` over `(T, bool)`? Are these benefits worth introducing 2 patterns that (possibly) do the same thing?

_Originally posted by @deanveloper in https://github.com/golang/go/issues/48702#issuecomment-931759166_

**Comment by deanveloper** [comment]
Was this accidentally created?

**Comment by mvdan** [comment]
Yeah it seems like this was a mistake. It doesn't add anything besides copy-pasting your comment.

**Comment by seankhliao** [comment]
I've seen a few of these issues reposting a comment with the same attribution format, posted by accounts that were freshly created
