### ISSUE TITLE
x/tools/gopls: compute analysis facts for non-workspace packages

### ISSUE THREAD

**Issue by goblinfactory** [golang/go#48738]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go1.17 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.7.2
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.60.2
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.28.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	-	gopkgs:	/Users/{username}/go/bin/gopkgs: go1.17
	-	go-outline:	/Users/{username}/go/bin/go-outline: go1.17
	-	gotests:	/Users/{username}/go/bin/gotests: go1.17
	-	gomodifytags:	/Users/{username}/go/bin/gomodifytags: go1.17
	-	impl:	/Users/{username}/go/bin/impl: go1.17
	-	goplay:	/Users/{username}/go/bin/goplay: go1.17
	-	dlv:	/Users/{username}/go/bin/dlv: go1.17
	-	dlv-dap:	/Users/{username}/go/bin/dlv-dap: go1.17
	-	golint:	/Users/{username}/go/bin/golint: go1.17
	-	gopls:	/Users/{username}/go/bin/gopls: go1.17
 
	
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```json
{
    "go.toolsManagement.autoUpdate": true,
    "go.lintTool": "golint",
    "go.vetOnSave": "workspace"
}
```

### Describe the bug
When "Go:vet On Save is enabled in settings; and a go file is edited and saved (containing an error that `go vet ./...` does pick up), then no error squiggles appear in the editor to show that there is a vet error.

### Required behavior

When "Go:vet On Save is enabled in settings; and a go file is edited and saved (containing an error that `go vet ./...` does pick up), then error squiggles MUST appear in the editor to show that there is a vet error.

### Steps to reproduce the behavior:

1. given a go file `testvet.go` with the following code

```go
package testvet

import (
	"fmt"
	"sync"
)

// TestThatVetRunsOnSave minimal code to show vet not running on save in VS code
func TestThatVetRunsOnSave() {

	ch := make(chan string)
	var wg sync.WaitGroup
	wg.Add(1)
	go printit(wg, ch)

	ch <- "one"
	ch <- "two"
	close(ch)
	wg.Wait()
	fmt.Println("done.")

}

func printit(wg sync.WaitGroup, ch chan string) {
	defer wg.Done()
	for t := range ch {
		fmt.Println(t)
	}
}
```

2. When I edit any text in this file that changes something, for example a space or comment
3. Then the editor should highlight the same lines of code containing vet errors, that the command line `go vet ./...` picks up as having an error. 
```
pkg/testvet/testvet.go:14:13: call of printit copies lock value: sync.WaitGroup contains sync.noCopy
pkg/testvet/testvet.go:24:17: printit passes lock by value: sync.WaitGroup contains sync.noCopy
```
4. Manually running the command , Go:vet workspace does work and causes the editor to report the correct errors and squigglies. (see screenshot below)

### Screenshots or recordings

To be clear, the screenshot below is the behaviour that we WANT to happen and be triggered on save, this is currently not happening and only happens when you manually run the command `Go;vet workspace`

![Screenshot 2021-10-01 at 19 33 36](https://user-images.githubusercontent.com/1073487/135670971-bebc680d-6657-43f3-a1d5-af7cd6c141d9.png)

In addition to this functionality not working, the user interface helptext in VSCode settings does not make sense. The setting helptext has this text, which refers to functionality that I believe is not longer valid.

![Screenshot 2021-10-01 at 19 45 06](https://user-images.githubusercontent.com/1073487/135671472-20f0c8ed-5e0b-480f-b73d-ad7fb7840aba.png)

I have tried all variations of this setting value; both `package` and `workspace`. Neither works.

**Comment by goblinfactory** [comment]
Hi all, I'm not sure if this might be the same reason that lint squigglies dont appear on save, and when you manually run the "linter" tool from vscode, all the squigglies appear as well as the backlog list of "problems" in the IDE "problem" pane. When you hit save in any file, then all the lint error squigglies dissapear and the backlog "problems" is cleared. Please let me know if I should raise another issue for this, or if the "facts" for stdlib would resolve this too?

**Comment by findleyr** [comment]
If we do this naively, computing analysis facts for the standard library will be very costly.

We want to do this, but my guess is that any solution that works for the standard library will work more generally.

**Comment by adonovan** [comment]
This was fixed at head by https://go.dev/cl/443099. I have verified that the original test case is now working.
