### ISSUE TITLE
time: mention reference date used for formatting in time.Parse

### ISSUE THREAD

**Issue by chriseyre2000** [golang/go#48757]
As of go1.17.1

This is a documentation issue so environment and recreation issues are irrelevent.

The documentation for the time.Parse fails to mention the "magical reference date" 
(https://programming.guide/go/format-parse-string-time-date-example.html)

This makes working with date parsing much harder than it needs to be.

**Comment by ALTree** [comment]
It does say in the 2nd sentence of the function's doc:

>  See the documentation for the constant called Layout to see how to represent the format.

Of course is not advisable to duplicate the information in the doc of every function that uses the format.

**Comment by chriseyre2000** [comment]
Hiding a key documentation point in a comment in an example function is close to the HHGTG: https://www.goodreads.com/quotes/40705-but-the-plans-were-on-display-on-display-i-eventually

I am not asking it to be copied everywhere, merely to be added to the documentation of the Parse function.

**Comment by ALTree** [comment]
> Hiding a key documentation point in a comment in an example function

? 

I'm referring to the section at the top of the package: https://pkg.go.dev/time#pkg-constants. It's hard to see how anyone scrolling through the documentation of `time` could miss the huge section about the layout string right at the beginning. 

The fixed layout string is used in `Parse` and in `Format` and in `ParseInLocation` and in `AppendFormat`. We'd need to replicate that big explanation several times.

**Comment by seankhliao** [comment]
I don't think there's anything to do here. If you read the signature for `time.Parse`, the first paragraph will redirect you to `Layout`, and if you searched the entire doc for `reference time`, the first instance is also for `Layout`.

The examples are that that, examples, and not suited for the function doc itself. Note that `time.Parse` also has an example (which will point you to `time.Format` for a longer explanation).

**Comment by mknyszek** [comment]
CC @rsc via https://dev.golang.org/owners
