### ISSUE TITLE
x/crypto/ssh: OpenSSH 8.8 disabled RSA signatures using the SHA-1 hash algorithm

### ISSUE THREAD

**Issue by fasmide** [golang/go#48758]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.8 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Though I didn't test it, I think it would reproduce, as this is most likely an issue with the ssh package and not so much golang itself.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/fas/.cache/go-build"
GOENV="/home/fas/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/fas/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/fas/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/8408"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/8408/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.8"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/fas/github.com/fasmide/sshdtests/server/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build725442376=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I tried out the [ssh.NewServerConn](https://pkg.go.dev/golang.org/x/crypto/ssh#example-NewServerConn) example - and used the latest OpenSSH client (8.8p1)

Using `golang.org/x/crypto v0.0.0-20210921155107-089bfa567519`

### What did you see instead?
<pre>
# ssh -p2022 172.17.0.1
Unable to negotiate with 172.17.0.1 port 2022: no matching host key type found. Their offer: ssh-rsa
</pre>

###  So what is this?
I think the ssh package doesn't implement [RFC8332](https://datatracker.ietf.org/doc/html/rfc8332), which in turn also needs [RFC8308](https://datatracker.ietf.org/doc/html/rfc8308) in order to work.

As far as I can tell, this makes it impossible for the ssh package to provide RSA based verification using stronger algorithms such as rsa-sha2-256 or rsa-sha2-512

**Comment by mpx** [comment]
This is #39885

**Comment by fasmide** [comment]
@mpx Yes is it! thanks! - I was unable to apply the necessary search terms :)
