### ISSUE TITLE
Retrieve two latest releases of Golang using Github API

### ISSUE THREAD

**Issue by MariaZarifyan** [golang/go#48760]
Hello. 

I am working with the Github API and trying to get the list of releases. The query https://api.github.com/repos/golang/go/git/refs/tags works properly and I get the list of tags, however when I do the same with the list of releases and using the following query, it returns an empty list: https://api.github.com/repos/golang/go/releases

I have also  tried to use https://api.github.com/repos/golang/go/git/refs/releases but it didn't work either. 
If you know any alternative methods of how to retrieve the two latest versions of Golang dynamically, please let me know. 

Best regards,
Maria

**Comment by ALTree** [comment]
https://golang.org/dl/?mode=json

Note that the github repository is just a mirror. The real repository is at https://go.googlesource.com/go.
