### ISSUE TITLE
crypto/hash: add a function that removes heap allocations in checkSum calls

### ISSUE THREAD

**Issue by johns1342** [golang/go#48776]
## Discussion

The current go crypto hash libraries [force an allocation in their `checkSum()` functions](https://cs.opensource.google/go/go/+/refs/tags/go1.17.1:src/crypto/md5/md5.go;l=181), and when running multiple hashes in parallel for doing analysis, the allocation starts to take a toll on CPU utilization (iirc around 60-80% utilized).  After removing that allocation locally by adding another function that accepts an output buffer, and rebuilding go, I was able to get utilization back up to 99%+.

Ideally the crypto hash libraries would provide something like a `SumTo(data, dst []byte)` function that would avoid the hash output buffer allocation.  This would be backwards compatible since it would only add one additional `SumTo` function to the hash libraries (I figure if someone is using the package's `Sum` function they are not that worried about allocations, so it would only need to be added to the struct).

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/john/Library/Caches/go-build"
GOENV="/Users/john/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/john/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/john/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zl/d7zp3qvn0jdclwj0zlcwc93w0000gn/T/go-build2238499849=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```go
package main

import (
	"crypto/md5"
	"testing"
)

func BenchmarkMD5(b *testing.B) {
	h := md5.New()
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		h.Sum([]byte("testing")) // alloc is done inside of checkSum()
	}
}
```

```bash
$go test -bench=. md5_test.go
goos: darwin
goarch: amd64
cpu: VirtualApple @ 2.50GHz
BenchmarkMD5-8           7722992               152.7 ns/op            24 B/op          1 allocs/op
PASS
ok      command-line-arguments  1.698s
```

### What did you expect to see?

Would like to see 0 allocs/op.

### What did you see instead?

1 alloc/op.

**Comment by johns1342** [comment]
I'd be interested in submitting a PR for this if it gets the green light.

**Comment by ianlancetaylor** [comment]
I don't think the `checkSum` function is allocating anything.  I think the allocation is coming from the call to `append` in `crypto/md5.(*digest).Sum`.

**Comment by johns1342** [comment]
@ianlancetaylor so it does.  Thank you for the quick response!  I was assuming the `digest` variable in `checkSum` was escaping, but if `checkSum` is inlined, then that makes sense.  I suppose the difference between `crypto/md5.Sum` and `crypto/md5.(*digest).Sum` was throwing me off, which may make this PR redundant with #21070.  Regardless, your comment solves my problem.

The only other thing I'd add is I think it might be a bit clearer if the `in` parameter was named `dst` or something related, similar to how the encoding packages name them.

For posterity, this code shows no allocs, and is actually correct (my prior example was just retrieving the null hash):

```go
package main

import (
	"bytes"
	"crypto/md5"
	"testing"
)

func BenchmarkMD5(b *testing.B) {
	h := md5.New()
	val := make([]byte, 16)
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		val = val[:0]
		h.Reset()
		h.Write([]byte("testing"))
		h.Sum(val) // slice containing hash returned here
	}
}
```
