### ISSUE TITLE
go fmt ./... does not add //go:build comments when subdirectory only contains tagged files

### ISSUE THREAD

**Issue by jrick** [golang/go#48771]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.1 openbsd/amd64
$ gotip version
go version devel go1.18-94323206a Mon Oct 4 15:50:43 2021 +0000 openbsd/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, 1.17.1, and tip.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jrick/.cache/go-build"
GOENV="/home/jrick/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="openbsd"
GOINSECURE=""
GOMODCACHE="/home/jrick/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="openbsd"
GOPATH="/home/jrick/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/jrick/src/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/jrick/src/go/pkg/tool/openbsd_amd64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/home/jrick/src/dcrwallet/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2608643202=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Ran `go fmt ./...` on a source tree to add `//go:build` lines wherever `//+build` was used.

When a package/subdirectory only contains files which require a build tag to be visible, the package is skipped over rather than being rewritten with the new line, because it does not match the `./...` expression.

```
$ find .
.
./go.mod
./main.go
./foo
./foo/foo.go
$ cat foo/foo.go
//+build ignore

package foo
$ go fmt ./...
$ cat foo/foo.go 
//+build ignore

package foo
```

I'm unable to reproduce this on the playground with the multiple files.

### What did you expect to see?

```
$ cat foo/foo.go
//+build ignore

package foo
$ go fmt ./...
$ cat foo/foo.go 
//go:build ignore
// +build ignore

package foo
```

### What did you see instead?

The package was not matched by ./... so it is not reformatted using the new `//go:build` lines.

**Comment by mvdan** [comment]
This is to be expected, I think; `go fmt ./...` will only format packages matched by `./...`. If you want to format all Go files, including those outside reachable packages, consider using `gofmt -l -w .` instead, which is file-based rather than package-based.

**Comment by jrick** [comment]
I see. That command does do what I'd want, although it obviously wasn't what I would have reached for first (nor was I aware it recursed through directories).

Feel free to close.
