### ISSUE TITLE
runtime: tests have gotten slower

### ISSUE THREAD

**Issue by josharian** [golang/go#48770]
I've noticed running all.bash recently that the runtime tests are really slow and CPU intensive.

On my M1, I tried doing `cd $GOROOT/runtime; go test -c; ./runtime.test -test.short` with recent Go versions. The runtime tests now take almost 3x longer than 1.17.

* Go 1.16: `6.46 real         7.76 user         2.52 sys`
* Go 1.17: `7.39 real         8.40 user         2.48 sys`
* Tip, Oct 4 '21 (94323206aee1363471a4ae3b8d40dd4ae7a5cd9c): `20.03 real        25.64 user         6.26 sys`

The slowest at tip are:

```
0.50s TestCgoCrashHandler
0.58s TestCgoExternalThreadSignal
0.67s TestCgoSignalDeadlock
0.71s TestCheckPtr2
0.72s TestCgoExternalThreadSIGPROF
0.77s TestEINTR
1.00s TestCheckPtr/CheckPtrAlignmentNilPtr
1.00s TestDeferKeepAlive
1.01s TestSpuriousWakeupsNeverHangSemasleep
1.13s TestVDSO
1.38s TestCgoCCodeSIGPROF
```

Perhaps some of these could be shortened, skipped, or marked parallel?

**Comment by cuonglm** [comment]
Maybe related https://github.com/golang/go/issues/48496

**Comment by josharian** [comment]
Ouch. Yes, quite possibly!

**Comment by mknyszek** [comment]
@josharian #48496 seems to have been resolved. Is this any better?

**Comment by josharian** [comment]
It is marginally better, but still much slower than previous releases.

* 1.17: `7.58 real         9.83 user         2.84 sys`
* tip (f6591839727e09cc5cb11d08b333fd2386e8aa1b): `18.80 real        26.15 user         7.19 sys`

Also, tip now contains log spam:

```
step 1
step 8
step 9
step 10
step 11
step 12
step 13
step 14
PASS
```

**Comment by josharian** [comment]
Mailed CL 364555 for the log spam.

**Comment by odeke-em** [comment]
How are we doing here @josharian?

**Comment by josharian** [comment]
Looks fixed.
