### ISSUE TITLE
x/build: unable to get ios-arm64-corellium gomote

### ISSUE THREAD

**Issue by mknyszek** [golang/go#48772]
The builders are already slow, but despite gomote claiming that it cancelled a build on one of them and was handing it to me, 97h24m0s passed without any response. Can we increase the builder pool for this type?

**Comment by mknyszek** [comment]
CC @dmitshur @toothrot

**Comment by toothrot** [comment]
These builders are owned by @znly.

It looks like the two builds in progress have stalled, which is why you never got a response: https://farmer.golang.org/temporarylogs?name=ios-arm64-corellium&rev=e48cf0db4edb139901946fcee1497bd539229d71&st=0xc005733ba0

The builders may need to be restarted.

**Comment by dmitshur** [comment]
I'll close this issue in favor of #49048. Once builders are back, it will be possible to get a gomote.
