### ISSUE TITLE
go pass by value？

### ISSUE THREAD

**Issue by 2bon** [golang/go#48788]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.17 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

ya

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\LENOVO\AppData\Local\go-build
set GOENV=C:\Users\LENOVO\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\LENOVO\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\LENOVO\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn
set GOROOT=D:\program files\scoop\apps\go\current
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\program files\scoop\apps\go\current\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\LENOVO\AppData\Local\Temp\go-build195223927
8=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
`package main

import (
   fmt "fmt"
)

func main() {
   s1 := "老铁@1"
   fmt.Println(s1)
   p1 := &s1
   fmt.Println(p1)
   s2 := *&s1
   fmt.Println(s2)
   s1 = "奥利给@?"
   fmt.Println(s1)
   p2 := &s1
   fmt.Println(p2)
   s3 := *p2
   fmt.Println(s3)
   fmt.Println(p1)
   fmt.Println(s2)
}`

### What did you expect to see?

（p2!=p1）

### What did you see instead?
（p2==p1）&（s1=s3!=s2）

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by 2bon** [comment]
isn't it a bug?

**Comment by ianlancetaylor** [comment]
I don't see a bug here.  Discussion should take place on a forum, not here.  Thanks.
