### ISSUE TITLE
x/pkgsite: Incorrect "latest" version leads to missing "Deprecated" message.

### ISSUE THREAD

**Issue by lgarron** [golang/go#48783]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/github/fakeca
 
### What is your user agent?
 
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36
```
 
### Screenshot
 
<img width="805" alt="Screen Shot 2021-10-04 at 17 07 37" src="https://user-images.githubusercontent.com/248078/135940669-650f71e0-3edd-4c76-8b73-69ce2300fa2e.png">

### What did you do?

I published a `v0.2.0` tag for three packages, each with a similar `// Deprecated:` comment in `go.mod`:

- https://pkg.go.dev/github.com/github/fakeca
- https://pkg.go.dev/github.com/github/certstore
- https://pkg.go.dev/github.com/github/ietf-cms

### What did you expect to see?
 
 All three show a `⚠ Deprecated` message like this:
 
<img width="604" alt="Screen Shot 2021-10-04 at 17 09 01" src="https://user-images.githubusercontent.com/248078/135940771-e0e70444-cbea-4ea5-a1f0-13967df546c8.png">

### What did you see instead?

https://pkg.go.dev/github.com/github/fakeca doesn't show the message, but the other packages do.

--------

https://pkg.go.dev/github.com/github/fakeca?tab=versions seems to know about `v0.2.0` but it doesn't seem to be getting picked up as the "latest". https://pkg.go.dev/github.com/github/fakeca@v0.2.0 shows this, and clicking "Go to latest" takes you to `v0.1.0`:

<img width="266" alt="Screen Shot 2021-10-04 at 17 14 01" src="https://user-images.githubusercontent.com/248078/135941053-88561f83-7f2f-4e8c-b8c5-60373a084b0f.png">

**Comment by FiloSottile** [comment]
The proxy has the right latest, so pkgsite seems to be behind.

```
go mod download -json github.com/github/fakeca@latest
{
	"Path": "github.com/github/fakeca",
	"Version": "v0.2.0",
	"Info": "/Users/filippo/pkg/mod/cache/download/github.com/github/fakeca/@v/v0.2.0.info",
	"GoMod": "/Users/filippo/pkg/mod/cache/download/github.com/github/fakeca/@v/v0.2.0.mod",
	"Zip": "/Users/filippo/pkg/mod/cache/download/github.com/github/fakeca/@v/v0.2.0.zip",
	"Dir": "/Users/filippo/pkg/mod/github.com/github/fakeca@v0.2.0",
	"Sum": "h1:xtBwXN7dmDPK8U5z0KHW1jupDVTDSINxrKRAc5//XFY=",
	"GoModSum": "h1:XhVUBgZ9+o0O6XzVXOl4H5qNxkV/MImtB3FuI/Zcti0="
}
```

**Comment by lgarron** [comment]
This seems to have resolved itself by now. 🤔

(But as documented with screenshots, it definitely was an issue for a while!)

**Comment by nishanths** [comment]
I'm running into the same issue with the module github.com/nishanths/exhaustive. The latest tag at the time of writing is v0.7.9, which pkg.go.dev knows about in its versions page: https://pkg.go.dev/github.com/nishanths/exhaustive?tab=versions.

![Screen Shot 2021-11-12 at 6 11 35 AM](https://user-images.githubusercontent.com/6028224/141389141-889e53a0-c0ae-406f-af43-550d99ee4ed9.png)

However the v0.7.9 main page doesn't seem to think its version the latest. Instead the v0.7.8 main page seems to think its version is the latest.

v0.7.9 main page:

![Screen Shot 2021-11-12 at 6 10 26 AM](https://user-images.githubusercontent.com/6028224/141389067-b87a5367-e2de-44ac-bcef-383688baf5e0.png)

v0.7.8 main page:

![Screen Shot 2021-11-12 at 6 10 40 AM](https://user-images.githubusercontent.com/6028224/141389081-f144c454-9e52-408a-b95a-25ebbc4df6cd.png)

(And just for completeness, no symbols were deprecated in packages in this module between the two versions.)

**Comment by jba** [comment]
I'm not sure exactly what happened there, but I do notice that v0.7.8, ...9, ...10 and ...1 were published within two hours of each other on November 11. It's possible that some out-of-order processing caused a temporary glitch, but it seems fine now: the latest page is v0.7.11, as it should be.
