### ISSUE TITLE
cmd/compile: open code unsafe.Slice

### ISSUE THREAD

**Issue by josharian** [golang/go#48798]
golang.org/cl/352953 used unsafe.Slice in the runtime. I am about to revert that change b/c it causes a 4% performance regression in a stack copying benchmark. At least half of that is due to function call overhead. We might want to open code unsafe.Slice instead of making it a runtime call.

cc @mdempsky

**Comment by ianlancetaylor** [comment]
Looking at the current implementation of `unsafe.Slice`, I see that it gives an error if the overall size of the slice is `> maxAlloc`, but I don't know why.  One can imagine using `unsafe.Slice` on a huge chunk of memory that is larger than `maxAlloc`, and doesn't seem any less safe than `unsafe.Slice` itself.

**Comment by mdempsky** [comment]
I think my rationale was to ensure the slice didn't wrap around the address space, and I just copied that from `growslice`. But reflecting on it now, it doesn't actually achieve that. Perhaps there's no reason to cap the addressed memory range.

Probably a better check would be `mem > -uintptr(ptr)` to prevent wrap around.

**Comment by zx2c4** [comment]
> I think my rationale was to ensure the slice didn't wrap around the address space, and I just copied that from `growslice`. But reflecting on it now, it doesn't actually achieve that. Perhaps there's no reason to cap the addressed memory range at `maxAlloc`.
> 
> Probably a better check would be `mem > -uintptr(ptr)` to prevent wrap around.

It's already "unsafe". Can we just omit all checks and have the compiler emit ideal code that assumes its usage is correct, just like unsafe.Pointer casts? Then we can put all sorts of safety checks behind checkptr, again like unsafe.Pointer casts.

**Comment by josharian** [comment]
Great. I'm thousands of miles from my computer, so I'm afraid I can't benchmark for you now. But the benchmark is checked in—StackCopyWithStkobj.

**Comment by cuonglm** [comment]
> It seems strange, but I even now can't reproduce on my M1. With and without unsafe.Slice give me the same benchmark result.

Never mind, I can reproduce on linux/amd64.

```
name                   old time/op    new time/op    delta
StackCopyWithStkobj-8    13.8ms ± 1%    14.5ms ± 3%  +5.09%  (p=0.000 n=10+9)
```
