### ISSUE TITLE
x/build: install fossil, bzr, and gpg binaries on linux-*-longtest builders

### ISSUE THREAD

**Issue by bcmills** [golang/go#48802]
The `go` command at least nominally supports five different version control systems: Git, Mercurial, Subversion, Fossil, and Bazaar. Of those, only three appear to be installed on the linux-amd64-longtest builder. That all but guarantees that regressions in support for the other two will not be detected by the builders.

The two missing tools are Fossil (provided by the `fossil` Debian package), and Bazaar (somewhat confusingly, now provided by the `brz` Debian package).

CC @golang/release

**Comment by cagedmantis** [comment]
The linux-x86-bullseye image has been updated after the submission of go.dev/cl/383156. This issue should be resolved after we switch the linux longtest builders to use the updated Debian bullseye image.

**Comment by cagedmantis** [comment]
The image has been updated. The issue should be resolved after the next coordinator deployment.
