### ISSUE TITLE
go list -m -u all

### ISSUE THREAD

**Issue by MyaLongmire** [golang/go#48806]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.17

</pre>

### Does this issue reproduce with the latest release?
go list -m: golang.zx2c4.com/wireguard@v0.0.20200121: retracted by module author

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/myalongmire/Library/Caches/go-build"
GOENV="/Users/myalongmire/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/myalongmire/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/myalongmire/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/myalongmire/Documents/src/telegraf/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g7/13tq4xbj5_51zmfvlg8w5zzc0000gn/T/go-build2517886252=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
tried go 1.16 tried installing golang.zx2c4.com/wireguard and tried updating also tried on a linux instead of mac

### What did you expect to see?
all of the dependencies listed

### What did you see instead?
go list -m: golang.zx2c4.com/wireguard@v0.0.20200121: retracted by module author

**Comment by seankhliao** [comment]
Seems to be working as intended

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by AlekSi** [comment]
See also #53594 that was fixed in 1.19
