### ISSUE TITLE
all: Go compiler/runtime performance monitoring system

### ISSUE THREAD

**Issue by prattmic** [golang/go#48803]
The runtime/compiler team is investigating the creation of a performance monitoring system, with a primary goal of reducing release toil by catching performance regressions as early as possible.

Requirements are still being discussed, but highlights include:

* Automation of performance data generation.
  * Benchmark execution solution that tracks commits to Go (e.g., x/build coordinator scheduling benchmark runs).
* Storage and visualization of performance data over time.
* Key set of "application-level" and "feature-focused" benchmarks.
* Active monitoring of changepoints.
* Easy debugging/reproduction.

cc @aclements @dr2chase @mknyszek @jeremyfaller @golang/release

**Comment by odeke-em** [comment]
> cc @odeke-em 

Thank you for the tag @mvdan!

Indeed, at Orijtech Inc we've been working on such a product ["Bencher"](https://bencher.orijtech.com/) for the past 2 quarters of 2021 and produced it recently https://twitter.com/odeke_et/status/1428650768135974919?s=21: we have an integration on the GitHub marketplace at https://github.com/marketplace/gobencher and we actually have something on our roadmap to add a Gerrit integration during Q4 2021 or Q1 2022. I had raised and shown the product to @Sajmani, @spf13, @ianlancetaylor and @ianthehat and others :-)

For example, take a look at one of our public users Entgo https://dashboard.github.orijtech.com/benchmark/2bb34b8e166747d2974f76825819acbd
![image](https://user-images.githubusercontent.com/4898263/136098327-8c246043-8586-4c41-97ae-5d6679db60a2.jpeg)
![image](https://user-images.githubusercontent.com/4898263/136098360-4a704ca4-01f6-4c51-a780-8992a0e5088f.jpeg)

We'd be delighted to work with the core runtime/compiler team and bring this first class to the Go tooling ecosystem!

Kindlying cc-ing my colleagues @cuonglm @kirbyquerby @willpoint @jhusdero

**Comment by mengzhuo** [comment]
I have some thoughts about this site/app:

1. Transparent. All results should be available to public like benchsave instead of internal site from Google.
2. Informative. Regression notice to Gerrit/owner of CL.
3. Easy to compare with different baselines like major versions of Go.

**Comment by mknyszek** [comment]
@mengzhuo All three of those things are already on our radar. :) Thanks.

**Comment by shawn-xdji** [comment]
Curious to know will benchmark fluctuation be taken into account, and how? Thanks.

**Comment by prattmic** [comment]
@shawn-xdji By fluctuation, I assume you mean noise in the results. We are taking a few approaches up front:

* Running benchmarks on a low-noise machines. For now we plan to use "sole-tenant" VMs on GCE, though we may move to physical machines if necessary.
* Rerunning the baseline benchmarks each time we test a new commit to help account for long term changes (e.g., OS upgrade changes performance).
* Changepoint detection will need to statistical handle a small amount of noise.
* We are only planning to track a curated set of benchmarks. Benchmarks that a fundamentally noisy will either be excluded or fixed.

Finally, all of this is something we'll need to learn on as we go and find out how big the issues are.

**Comment by shawn-xdji** [comment]
Thanks @prattmic, that answers my question, anticipate you will share some best practices later.

**Comment by prattmic** [comment]
For those that have been following along, the current basic dashboard is available at https://perf.golang.org/dashboard/.

**Comment by jake-ciolek** [comment]
@prattmic Awesome stuff, would it be possible to expand the date range further back?

**Comment by jake-volvo** [comment]
> @jake-ciolek https://go.dev/cl/413578 is rolled out, so now the graph duration and end date are adjustable.

Thank you. Great work. 

I have noticed the data goes back only to 22nd of March (even if I query for more). Would it be possible to extend it? 

Also, could we look in to other metrics, like the time to compile Go itself (compilebench?), the size of Go binary broken down by funcs (feed data from something like compilecmp). Perhaps timings of individual SSA passes. Just some ideas for things that could be useful.

**Comment by prattmic** [comment]
> I have noticed the data goes back only to 22nd of March (even if I query for more). Would it be possible to extend it?

That is when we started collecting data. It is theoretically possible to test older commits, but I don't think it is worth the effort since we have plenty to investigate already.

> Also, could we look in to other metrics, like the time to compile Go itself (compilebench?), the size of Go binary broken down by funcs (feed data from something like compilecmp). Perhaps timings of individual SSA passes. Just some ideas for things that could be useful.

The benchmarks we run are in x/benchmarks/cmd/bench (which most consists of configurations of x/benchmarks/cmd/bent (various unit benchmarks from the community) and x/benchmarks/sweet (large application-scale benchmarks)). We have a minimal set of benchmarks right now, and are certainly open to benchmarking additional things, like the ideas you suggested.
