### ISSUE TITLE
proposal: cmd/link: create an information section with eface type struct addresses

### ISSUE THREAD

**Issue by vpachkov** [golang/go#48840]
Unlike iface, which has itab structure and we could get to type struct (runtime/type.go), eface doesn't have one and the code (compiled with pic) gets type address directly, using lea instructions on x86.

Example : `lea 0x100050(%rip), %rax # 200500 <type.*+0x1234>`

To handle it I propose to create an information section (debug type, that could be stripped) with an array of eface type structures, so it could be easily found in a binary file.

This information is required for further handling of Golang executables by post-link-optimizer tools like Bolt to make it possible to read actual information about eface types and account it during further basic blocks reordering.

Golang support for Bolt was announced here: https://github.com/facebookincubator/BOLT/issues/154#issuecomment-842143948

Currently, we are close to upstream Golang support in Bolt, but it requires changes described in this proposal.

**Comment by rsc** [comment]
This proposal has been **[declined as retracted](https://golang.org/s/proposal-status#declined-as-retracted)**.
— rsc for the proposal review group
