### ISSUE TITLE
go/types, types2: error messages print `untyped nil`, compiler used to print just `nil`

### ISSUE THREAD

**Issue by griesemer** [golang/go#48852]
Maybe it's sufficient to just print `nil` where we print `untyped nil` in error messages. The `untyped nil` is printed to differenciate it from typed `nil`'s, but now we print the type of typed `nil`'s in parentheses.

Investigate.

Marked for 1.18 in case we consider it important for more concise error messages, but could easily be backlog.

cc: @findleyr

**Comment by griesemer** [comment]
Related: https://golang.org/cl/354631

**Comment by cuonglm** [comment]
To be clear, I think the compiler used to print just `nil` when constant involves, because technically, `nil` is not a constant. In other cases, the compiler does print `untyped nil`:

```
$ cat x.go
package p

var _ = copy(nil, []int{})
$ go tool compile -G=0 x.go
x.go:3:13: use of untyped nil
```
