### ISSUE TITLE
spec:  description of continue statements is not accurate

### ISSUE THREAD

**Issue by DQNEO** [golang/go#48864]
Current spec says:

https://github.com/golang/go/blob/2ac3bdf378ae408ad8c993084c1c6f7d05b7dff8/doc/go_spec.html#L5618-L5622

There are 2 problems.

## Problems

1) There is no "post statement" in "For statements with range clause"
 An implementation may have an internal post statement, but it's not declared in the spec.
2) Given that "The condition is evaluated before each iteration.", the next iteration may not begin.

```go
	for i := 1; i < 2; i++ {
		println(i)
		continue // the next iteration won't begin
	}
```

So I would like to propose a better description.

## Proposal

```diff
- A "continue" statement begins the next iteration of the innermost "for" loop at its post statement. 
+ A “continue” statement causes a jump to the end of the current iteration of the innermost “for” loop.
```

If this is acceptable, then I'm willing to send a change for review.

**Comment by griesemer** [comment]
Thanks for bringing this up. Please hold off with sending a CL for now while we're in the middle of tweaking the spec for generics. Documentation improvements such as this one can be made any time later.
