### ISSUE TITLE
gotip generic: incompatible type: cannot use int(m) (value of type int) as K value

### ISSUE THREAD

**Issue by donnol** [golang/go#48887]
### What version of Go are you using (`go version`)?

gotip version
go version devel go1.18-e1c294a56d Sat Oct 9 01:04:29 2021 +0000 windows/amd64

```go
type MM int

func Value[K ~int](m MM) K {
    return int(m) // incompatible type: cannot use int(m) (value of type int) as K value
}

func Value2[K ~int](k K) MM {
    return MM(k)
}
```

### What did you expect to see?

`gotip run main.go` work successfully.

### What did you see instead?

`gotip run main.go`:  **incompatible type: cannot use int(m) (value of type int) as K value**

Value2 is valid, but Value is not.

**Comment by seankhliao** [comment]
This looks correct, `Value2` declare a return type of `MM` and converts the return value to type `MM`

`Value` declares a return type of `K` but tries to return a value of type `int`
