### ISSUE TITLE
cmd/vet: support cgo packages

### ISSUE THREAD

**Issue by mewmew** [golang/go#4889]
<pre>What steps will reproduce the problem?
a.go located at <a href="http://play.golang.org/p/w44ApVc-Kr">http://play.golang.org/p/w44ApVc-Kr</a>
1. go run a.go
2. go vet a.go

What is the expected output?
Output from go run:
%!s(int=5)

Output from go vet:
a.go:7: arg for printf verb %s of wrong type
exit status 1

What do you see instead?
Output from go run:
%!s(int=5)

Output from go vet:
vet: a.go:3:8: could not import C (can't find import: C)
exit status 1

Which compiler are you using (5g, 6g, 8g, gccgo)?
6g

Which operating system are you using?
Linux

Which version are you using?  (run 'go version')
go version devel +8eb896294200 Sat Feb 23 15:08:36 2013 -0800 linux/amd64</pre>

**Comment by mewmew** [comment]
Close the issue for now as it has remained inactive for more than 6 months.

Anyone with more insight into the current status may re-open the issue or add a comment about the current progress.

**Comment by bradfitz** [comment]
I thought @mdempsky was still interested in this.

**Comment by mewmew** [comment]
> I thought @mdempsky was still interested in this.

Matthew, you may re-open this issue if you are still interested in it. I decided to close it, as it had been placed in the Go "black hole" that is the *unreleased* milestone.

Didn't mean to close it if you still had an interest in it.

Cheers /u

**Comment by bradfitz** [comment]
@mewmew, "unreleased" doesn't mean blackhole. It means it's not shipped with Go so it can be fixed at any point. But now that vet is part of the standard library, Unreleased is no longer appropriate. 

See also: #16623
