### ISSUE TITLE
cmd/compile (or runtime): deferred calls are missed under certain situations

### ISSUE THREAD

**Issue by go101** [golang/go#48898]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

</pre></details>

### What did you do?

```Go
package main

func main() {
	defer func() {
		println(recover().(int))
	}()
	func() {
		func() (_ [2]int) { type _ int; return }()
		func() {
			defer func() {
				defer func() {
					recover()
				}()
				defer panic(3)
				panic(2)
			}()
			defer func() {
				recover()
			}()
			panic(1)
		}()
		defer func() {}()
	}()
	
	var x = 123
	func() {
		defer print(x) // not executed!
		func() {
			defer func() {}()
			panic(4)
		}()
	}()
}
```

Based on [this one](https://play.golang.org/p/AjhP4QHH1QU) from [here](https://github.com/golang/go/issues/43941#issuecomment-768078732).

### What did you expect to see?

Prints `1234`.

### What did you see instead?

Prints `4`.

This issue is created by @ianlancetaylor's [suggestion](https://github.com/golang/go/issues/43941#issuecomment-939406101).

**Comment by ianlancetaylor** [comment]
Works up to Go 1.13, fails with Go 1.14 to tip.

CC @danscales
