### ISSUE TITLE
encoding/gob: allow types to implement an interface which lets them convert themself into an encodable value

### ISSUE THREAD

**Issue by Keithcat1** [golang/go#48894]
Currently, the encoding/gob package provides the ability to change the way a type is serialized or deserialized by implementing GobEncoder or GobDecoder on it. This works by having the type somehow convert itself from or to a byte slice and then gob just serializes the resulting bytes.
This isn't usually a problem, but some types can't be serialized as they are and require using the encoding/binary package or something similar to manually convert them to bytes and back again.
This approach is also problematic when trying to serialize a data structure that contains multiple pointers pointing to the same value. When serializing, gob will store the values behind the pointers, not the pointers themselves, and then later loading the data could cause unexpected effects.
A much nicer approach would be to add two new interfaces that allow their implementers to return values which should be serialized in their place and to convert back to the original type respectively.
I'm not sure what the names for these interfaces should be.

**Comment by seankhliao** [comment]
I don't see how that would solve your problem oh punters?
In any case your type can implement GobEncoder by converting itself to encodable values, calling encode on them and returning the result

**Comment by ianlancetaylor** [comment]
I guess it's not clear to me why you want to use gob to encode a value that is already being encoded by gob.

Can you give a specific example of a data structure that would use this new feature?  Thanks.

**Comment by seankhliao** [comment]
Seems like we already have a way of doing this (GobEncode or BinaryMarshaler or TextMarshaler),
and the proposed change would only save a few lines without being much more efficient (gob still has to do the same amount of work serializing structs).
