### ISSUE TITLE
access: want to access builder machine by Gomote tool

### ISSUE THREAD

**Issue by XiaodongLoong** [golang/go#48917]
Hi,

I want to support buildmode=c-shared on linux/mips64{,le} https://github.com/golang/go/issues/43264, but I have no mips64 architecture machine to test. So I need to access builder machine by Gomote tool and I requst a token.
On my computer, the $USER env variable is `loongson`.  My email address is liuxiaodong@loongson.cn.

Thanks!

**Comment by ALTree** [comment]
cc @golang/release

**Comment by XiaodongLoong** [comment]
@cherrymui  It is OK. Thanks!
