### ISSUE TITLE
cmd/go: go mod assumes a lexicographically linear ordering of versions

### ISSUE THREAD

**Issue by rittneje** [golang/go#48915]
This is basically an experience report, based on some issues we have run into with go mod.

Go mod fundamentally assumes that there is a simple ordering between all versions of a module. In essence, if version X is lexicographically less than version Y,  then Y is a superset of X. However, this is not always true, and can lead to some unexpected implications when dealing with transitive dependencies.

For example, suppose my main module has a direct dependency on version 1.0.0 of A, and version 2.0.0 of B. Also suppose that A has a dependency on version 3.0.0 of C, and B has a dependency on version 3.1.0 of C. As per minimum version selection, my main module will select version 3.1.0 of C to satisfy the indirect dependency.

Now suppose some bug is discovered in module C. They release a new version 3.1.1, and also backport the fix to version 3.0.1. Then module A releases a new version 1.0.1 that depends on version 3.0.1 of C. But module B has not released a new version yet.

In my main module, I update my dependency on A to the new version (1.0.1), under the pretense of pulling in the bugfix. However, due to minimal version selection, I will still be using version 3.1.0 of C. The root cause of the issue is that it incorrectly assumes that just because 3.1.0 > 3.0.1, that means that 3.1.0 contains all of 3.0.1. The only way for this to work correctly is for me to manually specify version 3.1.1 of C in my go.mod file, which is especially weird because it is not a direct dependency.

A similar issue unfolds with unversioned libraries. There go mod just orders by commit date. But the commits in question need not be from the same branch, so again there may not be a convenient linear history between them. This is especially problematic with cherry picks, where if one module is tracking a release branch, then a cherry pick would cause its HEAD to be considered newer than an older commit from the main branch.

**Comment by mvdan** [comment]
In your fifth paragraph, are you mixing up versions 3.x.y with 1.x.y? For example, it says `version 1.1.1 of C`, where I think it means `version 3.1.1 of C`.

I appreciate the experience report, by the way - I've run into similar versions of this subtle problem.

I think my only bit of input is that, if C's v3.1.0 is so terribly broken that v3.1.1 should always be preferred, v3.1.1 could retract v3.1.0, signaling to MVS that it should prefer v3.1.1. But I get that retraction should only be used for terribly broken versions, such as those containing security bugs, and often the bugs are not that severe - though still important.

**Comment by rittneje** [comment]
> In your fifth paragraph, are you mixing up versions 3.x.y with 1.x.y? For example, it says version 1.1.1 of C, where I think it means version 3.1.1 of C.

Yep, that was a typo, I have updated my original post.

> It does not merely order by commit date. The pseudo-versions that the go command generates for commits encode not only the commit timestamp, but also a version prefix derived from the highest semantic version tagged on any ancestor of the commit.

That assumes that there are tags, which is not universally true. For example, the x repos are not tagged (except for x/text).

> I don't think it actually is all that weird to need to upgrade an indirect dependency to pull in a bug-fix — and note that at go 1.17 and above your go.mod file already explicitly includes all “relevant” indirect dependencies.

That isn't really feasible when there are a lot of indirect dependencies to account for. It would be preferable for go mod to fail and force me to resolve the issue explicitly (by asking for 3.1.1 in this case) in my go.mod file.

**Comment by mvdan** [comment]
In terms of warnings to watch out for, how about:

> warning: you're upgrading from C v3.0.1, released 2021-09-01, to the older C v3.1.0, released 2021-06-01, when v3.1.1 exists, released 2021-10-01

This does not imply that v3.1.1 should always be preferred over v3.1.0, but it's certainly a strong signal in many practical scenarios.

**Comment by bcmills** [comment]
I don't think there is anything we can feasibly do here, but if you have a specific proposal please do feel free to file it.
(See https://go.dev/s/proposal.)
