### ISSUE TITLE
x/pkgsite: unable to fetch packages from module proxy (go.buf.build)

### ISSUE THREAD

**Issue by lrewega** [golang/go#48952]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/go.buf.build/library/go-grpc/envoyproxy/protoc-gen-validate/validate 
 
### What is your user agent?
 

 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36
 
### Screenshot
 

 
<img width="986" alt="Screen Shot 2021-10-13 at 4 36 25 PM" src="https://user-images.githubusercontent.com/639066/137209009-b6d8e942-b4a7-4ab8-862b-fbe64b1b90b7.png">
Clicking the "Request" button leads to:
<img width="878" alt="Screen Shot 2021-10-13 at 4 37 24 PM" src="https://user-images.githubusercontent.com/639066/137209069-93768239-d692-4ac6-a24e-7cf9b28b1ac5.png">

### What did you do?
 

 
Attempted to view documentation for any package available through go.buf.build, a module proxy.

### What did you expect to see?

Generated documentation for the package, e.g.:

https://godocs.io/go.buf.build/library/go-grpc/envoyproxy/protoc-gen-validate/validate

### What did you see instead?

The "Oops!" page as seen in the above screenshots.

---

I've tried following each of the linked instructions to fetch the package but none appear to succeed.

godocs.io seems to handle this fine, so I am not sure if the problem is with pkgsite or go.buf.build. If it's the latter, any guidance on what's incorrect would be much appreciated.

**Comment by seankhliao** [comment]
go.buf.build would also need to include a license for the generated code

**Comment by lrewega** [comment]
@jba great, thanks! I appreciate it.
