### ISSUE TITLE
json.Unmarshal not work good at object

### ISSUE THREAD

**Issue by coco-roll** [golang/go#48959]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
The lastst release is also reproduce

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/Library/Caches/go-build"
GOENV="/Users/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/Cellar/go/1.16.4/libexec"
GOSUMDB=""
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.4/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7p/syywyq8s4t500nf_fhcw58km0000gn/T/go-build1825247537=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```go
package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	var testMap map[string]interface{}

	strArr := "{\"11911007\":{\"11911007\":1,\"119110010\":1,\"11911006\":1,\"11911005\":1,\"119110011\":1,\"119110012\":1,\"11911004\":1,\"119110015\":1},\"119110010\":{\"000000\":1}}"
	if err := json.Unmarshal([]byte(strArr), &testMap); err != nil {
		panic(err)
	}
	fmt.Printf("first time Unmarshal map is:%+v\n", testMap)

	if err := json.Unmarshal([]byte("{\"11911007\":{\"000001\":1}}"), &testMap); err != nil {
		panic(err)
	}
	fmt.Printf("second time Unmarshal map is:%+v\n", testMap)

	return
}
```

### What did you expect to see?
See:
```
first time Unmarshal map is:map[119110010:map[000000:1] 11911007:map[119110010:1 119110011:1 119110012:1 119110015:1 11911004:1 11911005:1 11911006:1 11911007:1]]
second time Unmarshal map is:map[1911007:map[000001:1]]
```

### What did you see instead?
See:
```
first time Unmarshal map is:map[119110010:map[000000:1] 11911007:map[119110010:1 119110011:1 119110012:1 119110015:1 11911004:1 11911005:1 11911006:1 11911007:1]]
second time Unmarshal map is:map[119110010:map[000000:1] 11911007:map[000001:1]]
```

**Comment by coco-roll** [comment]
@dsnet @mvdan why not clear before unmarshaling map as Slice do? This is clear to the user。
Or explain the design？

**Comment by mvdan** [comment]
Even if we wanted to do that, we can't make the change to the existing API as it would break users.

**Comment by coco-roll** [comment]
@mvdan This is a problem.
Can add a option to decide whether to clear?

**Comment by dsnet** [comment]
You're welcome to file a new issue with a concrete proposal of what this option would look like and how it would work.

**Comment by coco-roll** [comment]
@dsnet I'd like to add a flag in :
`src/encoding/json/decode.go

// IsCLearMap  When this flag is true to unmarshal
//a JSON object into a map allocates a new map whatever.
//Otherwise Unmarshal reuses the existing map,
//keeping existing entries
var IsCLearMap = false
......
	if kv.IsValid() {
                 //use the flag
		if i == 0 && IsCLearMap {
			v.Set(reflect.MakeMap(t))
		}
		v.SetMapIndex(kv, subv)
		i++
	}
......
`

Then can use
`json.IsCLearMap = true` 
to decide clear when unmarshal a JSON object to a map

I make a test,it look work good.
default:
`package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	var testMap map[string]interface{}
	//json.IsCLearMap = true
	strArr := "{\"11911007\":{\"11911007\":1,\"119110010\":1,\"11911006\":1,\"11911005\":1,\"119110011\":1,\"119110012\":1,\"11911004\":1,\"119110015\":1},\"119110010\":{\"000000\":1}}"
	if err := json.Unmarshal([]byte(strArr), &testMap); err != nil {
		panic(err)
	}
	fmt.Printf("first time Unmarshal map is:%+v\n", testMap)

	if err := json.Unmarshal([]byte("{\"11911007\":{\"000001\":\"string\"}}"), &testMap); err != nil {
		panic(err)
	}
	fmt.Printf("second time Unmarshal map is:%+v\n", testMap)

	return
}
`
###  output is:

first time Unmarshal map is:map[119110010:map[000000:1] 11911007:map[119110010:1 119110011:1 119110012:1 119110015:1 11911004:1 11911005:1 11911006:1 11911007:1]]
second time Unmarshal map is:map[11911007:map[000001:string]]

`package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	var testMap map[string]interface{}
	json.IsCLearMap = true
	strArr := "{\"11911007\":{\"11911007\":1,\"119110010\":1,\"11911006\":1,\"11911005\":1,\"119110011\":1,\"119110012\":1,\"11911004\":1,\"119110015\":1},\"119110010\":{\"000000\":1}}"
	if err := json.Unmarshal([]byte(strArr), &testMap); err != nil {
		panic(err)
	}
	fmt.Printf("first time Unmarshal map is:%+v\n", testMap)

	if err := json.Unmarshal([]byte("{\"11911007\":{\"000001\":\"string\"}}"), &testMap); err != nil {
		panic(err)
	}
	fmt.Printf("second time Unmarshal map is:%+v\n", testMap)

	return
}
`

###  output is:

first time Unmarshal map is:map[119110010:map[000000:1] 11911007:map[119110010:1 119110011:1 119110012:1 119110015:1 11911004:1 11911005:1 11911006:1 11911007:1]]
second time Unmarshal map is:map[11911007:map[000001:string]]

**Comment by ianlancetaylor** [comment]
@coco-roll Please file suggestions in a new issue, not this closed issue.  Thanks.  See https://golang.org/s/proposal.

That said we are not going to add a global variable like `IsClearMap`.  That would be racy, and it would be break programs that have multiple goroutines using JSON simultaneously if they don't all want the same behavior.  We never use global variables in that way in the standard library.  Some other approach would be required.

**Comment by coco-roll** [comment]
@ianlancetaylor Ok, i open a new issue at [#49334](https://github.com/golang/go/issues/49334). We can discuss in there.
