### ISSUE TITLE
x/pkgsite: stdlib packages do not load (permission denied)

### ISSUE THREAD

**Issue by uhthomas** [golang/go#48956]
### What did you do?

Navigate to https://pkg.go.dev/bufio#ScanLines and try to follow it to the source.

### What did you expect to see?

The source.

### What did you see instead?

The hyperlink leads to https://cs.opensource.google/go/go/+/go1.17.2:src/bufio/scan.go;l=290 which shows "Permission denied."

![firefox_F13rJXGI0s](https://user-images.githubusercontent.com/9749173/137220090-8b4dcd02-cb31-484f-9cfb-c0112a5f481e.png)

**Comment by uhthomas** [comment]
![firefox_c4FGpWguLm](https://user-images.githubusercontent.com/9749173/137227440-3cefdcc0-c1b8-4b3e-8d17-b58d7f9174f7.png)

![firefox_gqBXgEQshx](https://user-images.githubusercontent.com/9749173/137227511-92f0d248-0b3f-423a-8a0b-623328aea5e6.png)

You might be onto something with extensions as it seems to open okay in Edge. After selectively disabling extensions, I narrowed it down to the [DuckDuckGo Privacy Essentials](https://addons.mozilla.org/en-GB/firefox/addon/duckduckgo-for-firefox/) extension.

Every other site (Google sites included) work absolutely fine?

**Comment by seankhliao** [comment]
Seems like a problem with the extension and not the site

Dup of #47213
