### ISSUE TITLE
types2, go/types: missing errors for invalid parameterized type declarations

### ISSUE THREAD

**Issue by griesemer** [golang/go#48962]
This is a new version of frozen #39938. The following code
```Go
package p

type T0[P any] struct {
        f P
}

type T1 struct { // <<< should get a cycle error here
        _ T0[T1]
}
```
is invalid because `T1` would expand indefinitely. The previous fix (https://golang.org/cl/240519) could lead to infinite sequences of instantiations (see #48951).

Correct solution of this problem requires some form of type flow analysis and is related to (and may be addressed with) #48098.

**Comment by griesemer** [comment]
cc: @findleyr

**Comment by griesemer** [comment]
The above program currently crashes the compiler with a simple nil pointer panic. @danscales is there an easy way to address this?

More generally, could cases like these be detected in the type checker through some variation of the nomono checker? cc: @mdempsky

**Comment by danscales** [comment]
OK, the compiler will no longer crash, and will report a type loop, though the position information is off.  So no longer a release blocker.  We will either fix things to make the position info more accurate, or Matthew may be able to update the nomono pass to catch this case earlier.

**Comment by mdempsky** [comment]
@griesemer @findleyr Looking into this now. Happy to extend the nomono check to handle this, but I'm wondering why this isn't caught by whatever logic is responsible for rejecting `type T struct{ _ T }`?

**Comment by griesemer** [comment]
@mdempsky The logic (`Checker.validType`) that detects `type T struct{ _ T }` can (and used to) detect cases like this, but for this to work it will need to instantiate the types fully. This will lead to an infinite sequence of instantiations. I'm not sure there's an easy extension of the `validType` function to handle this case and avoid the infinite recursion.

**Comment by griesemer** [comment]
@mdempsky see also the description on [CL 355732](https://go-review.googlesource.com/c/go/+/355732/).

**Comment by danscales** [comment]
@mdempsky  Assigning this issue to you, so you can comment as to whether you think it is feasible to change nomono to catch this recursive type in the beta time-frame (i.e. in the next couple weeks).  You can assign it back to me, if you don't think it makes sense or is feasible to do for Go 1.18.
