### ISSUE TITLE
types2, go/types: type-checking expands type forever

### ISSUE THREAD

**Issue by griesemer** [golang/go#48974]
This is from a [comment](https://github.com/golang/go/issues/48951#issuecomment-943452433) in #48951, reported by @jkmpariab. Reproducer:
```Go
package p

type Fooer interface {
	Foo()
}

type Fooable[F Fooer] struct {
	ptr F
}

func (f *Fooable[F]) Adapter() *Fooable[*FooerImpl[F]] {
	return &Fooable[*FooerImpl[F]]{&FooerImpl[F]{}}
}

//
// By removing the 'F Fooer' type param, program compiles sucessfully
//            |||||||||
//            vvvvvvvvv
type FooerImpl[F Fooer] struct {
}

func (fi *FooerImpl[F]) Foo() {}
```
cc: @findleyr

**Comment by findleyr** [comment]
Hmm, why exactly is this package invalid? Looks ok to me, and a fix I'm working on for another recursive case makes this type-check without error.

**Comment by griesemer** [comment]
Premature conclusion. I've adjusted the title.

**Comment by jkmpariab** [comment]
@griesemer The issue is not fixed yet. i'm testing on 
```
go version devel go1.18-bde0463da3 Tue Oct 19 11:52:34 2021 +0000 linux/amd64
```
please reopen the issue
