### ISSUE TITLE
cmd/vet: decide on support for type parameters in the printf analyzer

### ISSUE THREAD

**Issue by findleyr** [golang/go#48971]
This is a separate issue from #48704, because we need to make a non-trivial decision about the printf analyzer for 1.18.

The printf analyzer has come up several times in the context of updating tools for generics, because it is an example of where we might want to interrogate the type set of a type parameter -- see below.  After going back-and-forth, in my opinion we should be conservative and treat type parameters like interfaces, at least for 1.18.

For discussion, consider the following examples:

```go
// Example 1
func _[T ~int](t T) {
  fmt.Printf("%s", t)  // is this a mismatching verb? t might be a fmt.Stringer.
}

// Example 2
func _[T any](t T) {
  fmt.Printf("%d", t)  // t might be integral, or a fmt.Formatter
}

// Example 3
func _[T int|float64](t T) {
  fmt.Printf(“%s”, t)  // this is provably an error
}
```

In all of these examples, there are elements of the type parameter type set that do not match the printf verb being used, but in Examples 1 and 2 there may be false positives:
- In Example 1, the type argument must have int underlying, which doesn’t match `%s`, but we don’t know if it implements `fmt.Stringer` or `fmt.Formatter`.
- In Example 2, the type argument can be any type, and we don’t know if it is integral, or a `fmt.Formatter`.
- In Example 3, the type set is finite and we can prove that no type argument matches `%s`.

In the future we may want to report diagnostics in all three examples, but in the interest of caution **I think we should allow all three for 1.18**.  Vet has very high standards for avoiding false positives, and in Examples 1 and 2, the following  [advice](https://cs.opensource.google/go/x/tools/+/master:go/analysis/passes/printf/types.go;l=137;drc=92778473c2e66cce9cca86de3a98d22b1c550dea) about interfaces from the printf source applies:

> // Whether any particular verb is valid depends on the argument.
> // The user may have reasonable prior knowledge of the contents of the interface.

We could reasonably produce a diagnostic just for Example 3, but I think it will probably be uncommon to have a finite type set, and it is OK to miss this true positive in the interest of simplifying the implementation.

The counter argument to doing nothing is that with the new embedded elements in interfaces, we can now express type sets more precisely and it is more likely that a mismatching verb is actually a user error.  There is some precedent here, in both directions:
 - we warn about arguments of interface type that did not implement `error` for %w (cf. #48931)
 - …but removed diagnostics for other verbs with arguments of interface type, as we can’t know if their dynamic type implements `fmt.Formatter` (cf. #36564).

This counter argument is compelling, and I think we should consider adding these diagnostics for 1.19 -- in fact I prototyped this in [CL 351832](https://golang.org/cl/351832) -- but for 1.18 in particular I am concerned that we don’t have a good understanding of how generics will be used, particularly when updating existing code, and having opinionated vet checks here may get in the way.

Regardless, I think this needs to be discussed (hence the issue).

CC @timothy-king @scott-cotton @mvdan

**Comment by bcmills** [comment]
In my opinion:
* Example 1 should emit a warning, because the type parameter may be instantiated with a type that does not implement `fmt.Stringer`, and for such parameters the format string is wrong.
* Similarly for example 2. The warning should be suppressed only if _every_ valid instantiation of `T` matches the formatting verb.

While it is true that “the user may have reasonable prior knowledge of the contents of an interface”, it is also the case that type sets can provide much more precision than interface types, and I think `vet` should make use of that extra precision.

**Comment by findleyr** [comment]
Closing this as the associated proposal was accepted and implemented.
