### ISSUE TITLE
x/build/env/openbsd-{386,amd64}: add an OpenBSD 7.0 (or newer) builder

### ISSUE THREAD

**Issue by toothrot** [golang/go#48977]
OpenBSD 7.0 [has been released](https://www.openbsd.org/70.html). We should probably update the 6.4 builder to 7.0, and keep the 6.8 one around.

**Comment by bcmills** [comment]
Should we have [recurring](https://github.com/golang/go/labels/recurring) issues filed for builders with known support windows? It looks like the OpenBSD releases occur pretty reliably by October and May each year, so in theory the OpenBSD builder upgrades should happen at a predictable point in each Go development cycle.

**Comment by 4a6f656c** [comment]
For the record, the only two supported OpenBSD releases are currently 6.9 and 7.0 (6.8 is no longer a supported release).

**Comment by 4a6f656c** [comment]
> Should we have [recurring](https://github.com/golang/go/labels/recurring) issues filed for builders with known support windows? It looks like the OpenBSD releases occur pretty reliably by October and May each year, so in theory the OpenBSD builder upgrades should happen at a predictable point in each Go development cycle.

This is correct - OpenBSD is released on a 6 month interval, the 7.1 release will be around May 2022 and the 7.2 release will be around October 2022.

**Comment by bcmills** [comment]
The new `openbsd-386-70` builder is segfaulting on every subrepo on the 1.16 release branch, and on many of the subrepos for 1.17. Should we restrict it to only 1.18 and later, or do we expect someone to backport fixes for those releases?

**Comment by bcmills** [comment]
(The builder is also failing on `x/net` everywhere due to #42064; updated that issue with details.)

**Comment by heschi** [comment]
We should clearly turn it off for 1.16. FWIW, 1.17 looks no flakier than tip to me? Am I missing something?

**Comment by bcmills** [comment]
It's not clear to me whether 1.17 is worse than tip — there are certainly more `fail` cells at the head commit for the subrepos:
![image](https://user-images.githubusercontent.com/5200974/142253980-8abf91a1-eecd-46cd-a4c3-7d22f2d63e38.png)
