### ISSUE TITLE
The net package needs some IP manipulation/calculation functions

### ISSUE THREAD

**Issue by WyoMurf** [golang/go#48985]
### What version of Go are you using (`go version`)?
1.16.2 linux/amd64

### Does this issue reproduce with the latest release?

It's fairly logical that it will!

### What operating system and processor architecture are you using (`go env`)?
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/murf/.cache/go-build"
GOENV="/home/murf/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/murf/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/murf/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.16"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.16/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/murf/go/ipnet/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2404029805=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

This is an enhancement request. To the "net" module.
It has severely limited network range and IP operators.

What I needed:
1. A way to see if a big range contains a smaller range. A result code could return a boolean for containment, and either a boolean or an int for overlaps, if one is not completely in the other (the int could tell what kind of overlap, at the beginning, or at the end, or both if the "big" range is actually smaller than the other.
2. A way to get the 4 octets in an ipv4 IP for calculations. ipv6 could profit from this also
3. A way to get start and end addresses from a range.  (like 192.168.134.6/30, say)

This is just basic stuff, but missing from your library.
     
Oh, and another issue, is the source code. I could not find the ParseCIDR function definition in what purports to be the source code for this module! I may have been able to turn in a patch if I could find that one function!

### What did you expect to see?

Doesn't apply

### What did you see instead?

Dousn't apply

**Comment by seankhliao** [comment]
See #46518 and #47323
