### ISSUE TITLE
x/website: update 1.16 release notes to indicate that ReverseProxy no longer changes transfer-encoding: chunked to content-length for small responses

### ISSUE THREAD

**Issue by ameowlia** [golang/go#48996]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/adowns/Library/Caches/go-build"
GOENV="/Users/adowns/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/adowns/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/adowns/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/adowns/workspace/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4c/1b3s36l94blb6xg1_4p_13800000gn/T/go-build2945905512=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

1. I ran a small app that set `Transfer-Encoding: chunked`
1. I ran a reverse proxy that points to the app.
1. I curled the app via the reverse proxy.

See example in playground: [https://play.golang.org/p/pRkFwyre5Bt](https://play.golang.org/p/pRkFwyre5Bt).

### What did you expect to see?

Prior to golang 1.16.0, the response would contain the `Content-Length` header.

### What did you see instead?

Since golang 1.16.0, the response contains the `Transfer-Encoding: chunked` header.

I was able to use git bisect to narrow it down to [this commit](https://github.com/golang/go/commit/ca3c0df1f8e07337ba4048b191bf905118ebe251) that changed things.

This change broke some of our clients and it would be nice to call it out in the release notes.

### Current Release Note

_ReverseProxy now flushes buffered data more aggressively when proxying streamed responses with unknown body lengths._

[Link to release note](https://golang.org/doc/go1.16#net/http/httputil)

### Proposed Release Note

_ReverseProxy now flushes buffered data more aggressively when proxying streamed responses with unknown body lengths. Because of this, when a backend sends a small response with the `Transfer-Encoding: chunked` header, this header is no longer replaced with the `Content-Length` header._

Sending a CL momentarily.

**Comment by jamalc** [comment]
Closing this. See the CL for context.
