### ISSUE TITLE
build broken after dist clean

### ISSUE THREAD

**Issue by oldoldman** [golang/go#49020]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.1 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\yushang\AppData\Local\go-build
set GOENV=D:\tools\golangenv.txt
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\yushang\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\yushang\go
set GOPRIVATE=
set GOPROXY=https://goproxy.io,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.1
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\notes\golang\src\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\yushang\AppData\Local\Temp\go-build2562555640=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

1.
```
go tool dist clean
```
2. compile any go file will fail with
```
# runtime/internal/sys
D:\Go\src\runtime\internal\sys\arch.go:27:30: undefined: StackGuardMultiplierDefault
```

### What did you see instead?
It seems dist clean is a dangerous command

**Comment by seankhliao** [comment]
Seems to be working as expected, cleaning up for the built files distribution, requiring you to rebuild it

For questions please refer to https://github.com/golang/go/wiki/Questions
