### ISSUE TITLE
can't set GOCACHE via GOENV

### ISSUE THREAD

**Issue by oldoldman** [golang/go#49028]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.1 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=D:\golang\_buildcache
set GOENV=D:\tools\golangenv.txt
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\yushang\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\yushang\go
set GOPRIVATE=
set GOPROXY=https://goproxy.io,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.1
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\yushang\AppData\Local\Temp\go-build751646277=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I put some environment variables in a file
```
GOCACHE=D:\golang\_buildcache
GOPROXY=https://goproxy.io,direct
```
and set GOENV point to this file , after this , build failed with 
```
: The filename, directory name, or volume label syntax is incorrect.
```
if I set GOCACHE in the terminal
```
set GOCACHE=D:\golang\_buildcache
```
every thing is ok . 
Does this mean I must paste the output of ```go env``` in the terminal ? If so , why GOPROXY works fine without doing so? In my understanding , the behavior should be consistent.

**Comment by seankhliao** [comment]
use `go env -w ......` to set variables, it will handle the proper format/escaping.
