### ISSUE TITLE
cmd/compile: capture implicit constraints in export data

### ISSUE THREAD

**Issue by findleyr** [golang/go#49040]
With #48424, we allow users to elide `interface{}` in constraint expressions. We expose this in the type checker as `func (*Interface) IsImplicit() bool`.  It would be nice to capture this in export data, so that we can preserve this implicit bit on import.

CC @mdempsky @griesemer

**Comment by findleyr** [comment]
I can do this.  @griesemer and I discussed and this is probably as straightforward as exporting the embedded structural type, rather than the constraint interface itself, for implicit constraint interfaces.  Then when importing, we can detect that the constraint is not an interface and wrap it in an implicit interface.

Prototyped in https://golang.org/cl/357109.

**Comment by griesemer** [comment]
@findleyr is there anything left to do here?

**Comment by findleyr** [comment]
No, I don't think so. Closing.
