### ISSUE TITLE
cmd/compile: builtin print treat arguments differently from normal functions

### ISSUE THREAD

**Issue by go101** [golang/go#49042]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```Go
package main

import "fmt"

const X = '\x61' // 'a'
const Y = 0x62
const A = Y - X

func main() {
	fmt.Printf("%T \n", A << 32) // constant 4294967296 overflows rune
	println(A << 32) // okay
}
```

[Edit]: A simpler one:
```Go
package main

import "fmt"

const A = '\x01'

func main() {
	fmt.Println(A << 32) // constant 4294967296 overflows rune
	println(A << 32) // okay
}
```

### What did you expect to see?

Same behavior.

### What did you see instead?

Different behavior.

(Maybe this is not a bug, but it should be mentioned somewhere in docs.)

[Edit]: this has been broken since Go toolchain 1.14.

**Comment by go101** [comment]
It is okay before Go 1.14.

**Comment by cuonglm** [comment]
@ianlancetaylor Yeah, the code you pointed out is for the old typchecker, at tip, we're using `types2` instead. That's why I commented above that we should re-open this issue for more discussion.

**Comment by griesemer** [comment]
Per #49216 we will accept the correct behavior and document it in the release notes. If this ends up breaking a lot of code, we can re-open.
