### ISSUE TITLE
x/build: android and iOS corellium builders are missing

### ISSUE THREAD

**Issue by cherrymui** [golang/go#49048]
The android-arm-corellium and android-arm64-corellium builders seem missing, along with the ios-arm64-corellium builder (#48772 may be related for the latter).

host-android-arm64-corellium-android: 0/0 (3 missing)
host-ios-arm64-corellium-ios: 0/0 (3 missing)

cc @golang/release

**Comment by dmitshur** [comment]
CC @steeve as a point of contact in the builder's [README](https://github.com/golang/build/tree/master/env/corellium).

Also CC @changkun who has been contributing on iOS side, in case you're interested and able to help with the occasional restarts that the builders need.

**Comment by steeve** [comment]
Let me look into that. You were right in mentioning me.
Adding @eliasnaur as well.

**Comment by steeve** [comment]
I have restarted the builders on Corellium, indeed they were offline.

**Comment by dmitshur** [comment]
Thank you @steeve. Closing this issue since the builders are back.

I've sent [CL 363985](https://golang.org/cl/363985) to remove their known issue and add a new owner based on conversation in [this thread](https://groups.google.com/g/golang-dev/c/oiuIE7qrWp0).
