### ISSUE TITLE
runtime/cgo: pthread_create failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by justkeepsimple** [golang/go#49057]
### What version of Go are you using (`go version`)?

go version go1.13.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go-workspace"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build621629647=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
Invoking blocking syscall function with goroutine; 
When the Go process invokes the C function, it occupies an independent system thread. Therefore, if the C function is invoked concurrently in the Go program and the C function has blocking operations, the Go program may continuously create new system threads. However, the Go program does not recycle system threads. 
How did i do to let the Go program to recycle system threads?

**Comment by justkeepsimple** [comment]
> @justkeepsimple sadly Go 1.13 is no longer supported. Please upgrade to Go 1.17 and let us know if you still see the problem. Thanks

The problem persists after the new version（1.17.2） is compiled and run.

**Comment by justkeepsimple** [comment]
@davecheney 
after invoking C function, Call the function immediately.
func KillOne() {
	var wg sync.WaitGroup
	wg.Add(1)
	
	go func() {
		defer wg.Done()
		runtime.LockOSThread()
		return
	}()
	
	wg.Wait()
}

It seems to be working！

**Comment by cherrymui** [comment]
> However, the Go program does not recycle system threads.

Could you show a code example? Why do you think it doesn't? Thanks.

**Comment by seankhliao** [comment]
No new information
