### ISSUE TITLE
fixedbugs/bug513.go fails on ppc64le with go 1.17.2

### ISSUE THREAD

**Issue by nmeum** [golang/go#49066]
I am currently working on upgrading the [Alpine Linux](https://alpinelinux.org) Go package from 1.17.1 to 1.17.2. At Alpine, we run the Go testsuite as part of our package. With 1.17.2 the test suite fails *only on the ppc64le* architecture which is weird because our buildlogs indicate that it passed successfully with 1.17.1 on ppc64le. The test that fails is `fixedbugs/bug513.go` and as far as I can tell the test case itself has not been modified in the 1.17.2 release which leads me to believe that this might have regressed with 1.17.2. More information below.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 linux/ppc64le
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="ppc64le"
GOBIN=""
GOCACHE="/home/buildozer/.cache/go-build"
GOENV="/home/buildozer/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="ppc64le"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/buildozer/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/buildozer/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/buildozer/aports/community/go/src/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/buildozer/aports/community/go/src/go/pkg/tool/linux_ppc64le"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
GOPPC64="power8"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2007078828=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I build Go 1.17.2 as one would normally using `./make.bash` and ran the `fixedbugs/bug513.go` test case as follows:

```
go/test $ ../bin/go run run.go -- fixedbugs/bug513.go
```

### What did you expect to see?

A successful test run. 

### What did you see instead?

I consistently get the following test failure:

```
output should be empty when (optional) expected-output file fixedbugs/bug513.out is not present. Instead saw
FATAL: ThreadSanitizer CHECK failed: ./gotsan.cpp:14506 "((personality(old_personality | ADDR_NO_RANDOMIZE))) != ((-1))" (0xffffffffffffffff, 0xffffffffffffffff)

FAIL    fixedbugs/bug513.go     4.985s
exit status 1
```

**Comment by laboger** [comment]
This could be the same problem as in https://github.com/golang/go/issues/35547. When running in a container, if ASLR is active, the thread sanitizer code tries to disable it on ppc64le. But the container might not have the permissions to do the syscall that to  disable ASLR. There is a way to override that in the container as is described in this issue.
