### ISSUE TITLE
x/pkgsite: remove retracted module versions from search

### ISSUE THREAD

**Issue by julieqiu** [golang/go#49148]
The latest version of github.com/tredoe/osutil is `v1.0.6`, but the version that appears in search is v1.3.5. This is because v1.3.5 is retracted. We should remove retracted versions from search_documents.

https://pkg.go.dev/github.com/tredoe/osutil
<img width="396" alt="Screen Shot 2021-10-25 at 12 05 20 PM" src="https://user-images.githubusercontent.com/5943521/138730912-97c77b80-f12b-41be-90f5-7c4fbe05e7d6.png">

https://pkg.go.dev/search?q=tredoe%2Fosutil
<img width="626" alt="Screen Shot 2021-10-25 at 12 06 08 PM" src="https://user-images.githubusercontent.com/5943521/138731024-957ae644-99df-4610-9b15-59291c88ce27.png">

https://pkg.go.dev/github.com/tredoe/osutil@v1.3.5.
<img width="462" alt="Screen Shot 2021-10-25 at 12 06 52 PM" src="https://user-images.githubusercontent.com/5943521/138731145-b9a32379-aea0-489d-ac1c-ea8e27bf10c0.png">

/cc @golang/pkgsite

**Comment by bcmills** [comment]
https://pkg.go.dev/search?q=tredoe%2Fosutil is no longer showing the retracted module. @jamalc, is this fixed?

**Comment by jamalc** [comment]
Yes, this was fixed in https://golang.org/cl/341591. Thanks!
