### ISSUE TITLE
x/pkgsite: license file issue with only-for-human LICENSE.md file

### ISSUE THREAD

**Issue by kortschak** [golang/go#49155]
### What is the URL of the page with the issue?

https://pkg.go.dev/gonum.org/v1/gonum@v0.9.1-0.20210927225948-aad206551871/graph/formats/rdf
 
### What is your user agent?
 

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0

 
### What did you do?
 

 
Navigate to the url above.
 
### What did you expect to see?

Documentation. 

### What did you see instead?

License warning.

I imagine that this is due to the [LICENSE.md file in that directory](https://github.com/gonum/gonum/blob/aad20655187192a02cde632400237c4511c4f34a/graph/formats/rdf/LICENSE.md) which is not intended for machine interpretation and does not cover any text that would be rendered by pkg.go.dev.

Because of the exhaustive license name matching[1] it is unclear how to name this file so that it 1. is understandable to a human and 2. not incorrectly read by licensecheck.

[1]
>COPYING, COPYING.md, COPYING.markdown, COPYING.txt, LICENCE, LICENCE.md, LICENCE.markdown, LICENCE.txt, LICENSE, LICENSE.md, LICENSE.markdown, LICENSE.txt, LICENSE-2.0.txt, LICENCE-2.0.txt, LICENSE-APACHE, LICENCE-APACHE, LICENSE-APACHE-2.0.txt, LICENCE-APACHE-2.0.txt, LICENSE-MIT, LICENCE-MIT, LICENSE.MIT, LICENCE.MIT, LICENSE.code, LICENCE.code, LICENSE.docs, LICENCE.docs, LICENSE.rst, LICENCE.rst, MIT-LICENSE, MIT-LICENCE, MIT-LICENSE.md, MIT-LICENCE.md, MIT-LICENSE.markdown, MIT-LICENCE.markdown, MIT-LICENSE.txt, MIT-LICENCE.txt, MIT_LICENSE, MIT_LICENCE, UNLICENSE, UNLICENCE. The match is case-insensitive.

**Comment by seankhliao** [comment]
isn't the solution to just move the file into testdata/?

**Comment by kortschak** [comment]
That is what we ended up doing, and in our case that was reasonable. In the general case though having a technology force an action like this isn't really appropriate. Because of the limitations of the license recognition algorithms (certainly improved since the original version) this kind of advice has been made in the past, to the extent of (paraphrasing), "your valid BSD-3 license isn't recognised by the code, the best thing to do would be to change it". This kind of thing doesn't seem reasonable.

**Comment by seankhliao** [comment]
I think like https://github.com/golang/go/issues/46291#issuecomment-846416251 , without human review, it's not unreasonable to for pkgsite both be conservative in applying license restrictions (ANDing everything, like in this case) as well as asking for standardization in machine recognizable formats.

I'd like the close this as there doesn't appear to be anymore actionable items for now.

**Comment by kortschak** [comment]
The story around the approach to license handling has been very poor.
