### ISSUE TITLE
x/tools/cmd/godoc: example should jump to signature, not example proper

### ISSUE THREAD

**Issue by robpike** [golang/go#4919]
<pre>In godoc, I would prefer if the link that jumps to the
example instead jumped to the function, so we see a reminder of the
signature and doc comment for the function before the example. It's
usually only a few lines.

For example, jump to /pkg/unicode/utf8/#DecodeLastRune rather than
/pkg/unicode/utf8/#example_DecodeLastRune</pre>

**Comment by iamnande** [comment]
Hi there,

I made CL 24580, which I believe is a redo of a the fix in a previous change system. If any further work is necessary I'm willing to make an effort to fulfill. My first CL for any go project, feel free to tell me if anything is amiss.

**Comment by ysmolsky** [comment]
I just checked it here https://golang.org/pkg/unicode/utf8/ and here https://golang.org/pkg/bufio/ - all example links work as expected.
Perhaps, close it?

**Comment by agnivade** [comment]
@ysmolsky - The issue is about jumping to the function signature instead of the example. So, if you go to https://golang.org/pkg/unicode/utf8/ and click on "DecodeLastRune" under the Examples section - it should jump to https://golang.org/pkg/unicode/utf8/#DecodeLastRune instead of https://golang.org/pkg/unicode/utf8/#example_DecodeLastRune.

It is still not implemented currently as I see it.

**Comment by ysmolsky** [comment]
@agnivade thank you. it seems that I cannot read.

**Comment by ysmolsky** [comment]
I can make it work technically for the examples of functions and methods. But I don't know what should be the behaviour when there are multiple examples per type/method: https://golang.org/pkg/bufio/#pkg-examples, https://golang.org/pkg/database/sql/#pkg-examples. 

In the case of https://golang.org/pkg/bufio/#example_Scanner_custom it is obvious that we can jump to `type Scanner` and expand the example below. But what to do with https://golang.org/pkg/bufio/#example_Scanner_emptyFinalToken? And what about `DB.Query (MultipleResultSets)`?

I do not see an elegant solution here. Help?

**Comment by agnivade** [comment]
> But what to do with https://golang.org/pkg/bufio/#example_Scanner_emptyFinalToken? And what about DB.Query (MultipleResultSets)?

Going with the spirit of the issue, I think it should always jump to the parent type/method.

FWIW, I think this leads to counter-intuitive (and possibly confusing) behavior. If I click on an example anchor, it should lead me to the example. Straight and simple. If I wanted to know about the function, I would have clicked the function anchor.

This also makes examples more difficult to share. If I wanted to show an example of bufio wordcount (https://golang.org/pkg/bufio/#example_Scanner_words) and share the link, but it instead links to the documentation of the Scanner struct, that would be extremely confusing.

**Comment by agnivade** [comment]
> However, there could be a link to what the example is attached to at the start of the example to allow quickly jumping to the signature. This works whether the documentation is terse or verbose and regardless of the number of examples.

Fair enough. I have a related issue here https://github.com/golang/go/issues/17223 where I propose to expose a link for the example too. I can probably add what you are suggesting along with it.

I think we all agree that implementing the current solution as is, will cause more confusion than benefit. Plus, it's 5 years old :) Will leave it to @robpike for final thoughts.
