### ISSUE TITLE
os/exec: support uid/gid

### ISSUE THREAD

**Issue by gopherbot** [golang/go#4920]
by **brady**:

<pre>The golang Cmd module is pretty nifty, but lacks the ability to change user id, or group
id before executing. Given that its hard to tap into the fork/exec model any other way
it seems that the ability to do this in Cmd would be really useful.</pre>

**Comment by bradfitz** [comment]
@ianlancetaylor, how hard would this be?

**Comment by ianlancetaylor** [comment]
I guess I don't understand the request, because even when it was written it was possible to set user ID and group ID in os/exec, via `SysProcAttr.Credential`.  Support for that was added in https://golang.org/cl/4280065.

Closing, but please comment if I misunderstood.
