### ISSUE TITLE
cmd/compile: better error message syntax error in interface types

### ISSUE THREAD

**Issue by komuw** [golang/go#49205]
### What version of Go are you using (`go version`)?

<pre>
$ go version
gotip version             
go version devel go1.18-a3bb28e5ff Thu Oct 28 14:25:03 2021 +0000 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/homew/.cache/go-build"
GOENV="/home/homew/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/homew/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/homew/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/homew/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/homew/sdk/gotip/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.18-a3bb28e5ff Thu Oct 28 14:25:03 2021 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/homew/Downloads/cool/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/run/user/1000/go-build4161629763=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
mistakenly write;
```go
package main

type A interface {
	int  int64
}
func main() { }
```

### What did you expect to see?
`main.go:60:7: syntax error: unexpected int64, expecting semicolon or newline or | or }`

### What did you see instead?
`main.go:60:7: syntax error: unexpected int64, expecting semicolon or newline or }`

ie, Now that interfaces can be used as type constraints; the error message should probably include `|` as one of the expected tokens.

**Comment by mdempsky** [comment]
`.` and `(` would also be valid tokens to appear after `int`. I'm not sure we need to be exhaustive in listing possible tokens.

**Comment by griesemer** [comment]
Marking for 1.18 if we get to it, otherwise fine to delay to 1.19.

**Comment by griesemer** [comment]
The error is reported by `parser.list` which doesn't have enough information for a better error yet. Either provide more context or leave away stating what is expected.
