### ISSUE TITLE
x/pkgsite: package docs missing for packages that use "//go:build" without "// +build"

### ISSUE THREAD

**Issue by bcmills** [golang/go#49229]
### What is the URL of the page with the issue?

https://pkg.go.dev/testing@master 

 
### What is your user agent?
 
```
Mozilla/5.0 (X11; CrOS x86_64 14150.64.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.104 Safari/537.36
``` 
 

### Screenshot
 
![image](https://user-images.githubusercontent.com/5200974/139464098-858018b2-29ac-4fb7-9658-fb06cfc9d8f4.png) 
 
 
### What did you do?
 
Load docs for the `testing` package after [CL 344955](https://golang.org/cl/344955) 
 
 
### What did you expect to see?
 
Docs for the `testing` package.
 
 
### What did you see instead?

Only a listing of subdirectories.

**Comment by jba** [comment]
This is fixed and deployed for the stdlib at the current tip. Since the problem was in our preprocessing stage, other modules might need to be reprocessed. I've already reprocessed github.com/anacrolix/torrent@v1.34.0 and github.com/bcmills/more@main. If your module is still affected, comment here.
