### ISSUE TITLE
x/crypto/cryptobyte: add ReadUint32LengthPrefixed

### ISSUE THREAD

**Issue by wxolp** [golang/go#49227]
Some code I am working with takes `[]byte` input, with this format:

~~~
modulus_length | modulus | exponent_length | exponent
~~~

where the `_length` are both `uint32`. So I figured I could use something like `ReadUint32LengthPrefixed`, but I discovered it doesnt exist. I found these:

- https://godocs.io/golang.org/x/crypto/cryptobyte#String.ReadUint24LengthPrefixed
- https://godocs.io/golang.org/x/crypto/cryptobyte#String.ReadUint16LengthPrefixed
- https://godocs.io/golang.org/x/crypto/cryptobyte#String.ReadUint8LengthPrefixed

Am I missing something? Was this function not added for some reason?

**Comment by AlexanderYastrebov** [comment]
> Was this function not added for some reason?

One reason might be that string length is int which max value is less than unit32 max value on 32bit platforms.

**Comment by wxolp** [comment]
I thought about this some more, and I realized that in addition to the missing function, I dont actually like the signature of the existing functions. With the current functions, the prefix bytes are lost [1]. So if you actually care about those, then you couldnt use the current functions, you would have to implement your own. So I did that:

~~~go
package bytes
import "encoding/binary"

type buffer struct {
   buf []byte
}

func (b *buffer) readUint32LengthPrefixed() ([]byte, []byte, bool) {
   if len(b.buf) < 4 {
      return nil, nil, false
   }
   high := 4 + binary.BigEndian.Uint32(b.buf)
   if len(b.buf) < int(high) {
      return nil, nil, false
   }
   pre, buf := b.buf[:4], b.buf[4:high]
   b.buf = b.buf[high:]
   return pre, buf, true
}
~~~

1. https://godocs.io/golang.org/x/crypto/cryptobyte#String.ReadUint16LengthPrefixed
