### ISSUE TITLE
cmd/go: add proper documentation for workspace mode

### ISSUE THREAD

**Issue by matloob** [golang/go#49232]
Add full docs for each of the go work subcommands, a doc for getting started on workspace mode, and a reference-style document.

**Comment by ianlancetaylor** [comment]
@matloob Is there more work to do on this issue for 1.18?  Thanks.

**Comment by dmitshur** [comment]
Perhaps this is the same as #51301, and one of the two can be closed as a duplicate?

**Comment by matloob** [comment]
I'll close this one in favor of #51301.
