### ISSUE TITLE
exec on MacOS seems to be missing some context (java fails)

### ISSUE THREAD

**Issue by gwd** [golang/go#49235]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.17.2
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/dunlapg/Library/Caches/go-build"
GOENV="/Users/dunlapg/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/dunlapg/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/dunlapg/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.2/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/c9/4nnnchz9057_65kvf5lgrn5m0000gn/T/go-build1737413726=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Wrote the following code:

```go
package main

import (
	"fmt"
	"os"
	"os/exec"
)

func main() {
	cmd := exec.Command("java")

	cmd.Args = []string{"-version"}

	out, err := cmd.CombinedOutput()

	fmt.Printf("Output of java -version:\n%s\n", string(out))

	if err != nil {
		fmt.Printf("Basic java exec returned an error: %v\n", err)
		os.Exit(1)
	}
}
```

### What did you expect to see?

Similar output to running `java -version` from the command line:

```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

### What did you see instead?

```
$ go run exec-java.go
Output of java -version:
The operation couldn’t be completed. Unable to locate a Java Runtime that supports -version.
Please visit http://www.java.com for information on installing Java.


Basic java exec returned an error: exit status 1
exit status 1
```

### Further Info

Calling java in this manner used to work a few years ago; I don't know exactly when it broke, unfortunately.  I've also been unable to figure out exactly what context might be missing that causes it to fail.

For reference, the same programs in C and rust work as expected, so it's unlikely to be a permissions issue w/ MacOS.

```C
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>

int main(void) {
    pid_t child;
    int status;

    if ((child = fork())) {
        fprintf(stderr, "Waiting for child pid %d\n", child);
        wait(&status);
    } else {
        int err;
        char *argv[] = {"java", "-version", NULL};
        fprintf(stderr, "Child executing java\n");
        err = execve("/usr/bin/java", argv, NULL);
        perror("Executing Java");
        return 0;
    }
}
```

```rust
use std::process::Command;

fn main() {
    let output = Command::new("java")
        .arg("-version")
        .output()
        .expect("failed to execute process");

    println!("Output:\n{:?}", output);
}
```

**Comment by cherrymui** [comment]
Try
```
package main

import (
	"fmt"
	"os"
	"os/exec"
)

func main() {
	cmd := exec.Command("java", "-version")

	out, err := cmd.CombinedOutput()

	fmt.Printf("Output of java -version:\n%s\n", string(out))

	if err != nil {
		fmt.Printf("Basic java exec returned an error: %v\n", err)
		os.Exit(1)
	}
}
```

In your code `cmd.Args` is not set correctly. `cmd.Args[0]` should be the command itself, i.e. "java". See https://pkg.go.dev/os/exec#Cmd

**Comment by gwd** [comment]
Ah, I see -- this sentence from the [documentation](https://pkg.go.dev/os/exec#Command) confused me:

> The returned Cmd's Args field is constructed from the command name followed by the elements of arg, so arg should not include the command name itself.

I took this to mean that cmd.Arg[0] didn't include the command name itself; but I understand now that it's talking about the additional args to exec.Command().  (I.e., you shouldn't write `exec.Command("java", "java", "-version")`.)

Thanks for the quick reply, sorry for the noise.
