### ISSUE TITLE
cmd/compile: identical generic types compare unequal

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#49241]
(Note: this is my first attempt at writing generic code, the chances I am just wrong are high.)

crypto/elliptic has a few functions like `P256() Curve` and `P384() Curve` that return a singleton implementation of that curve. The singleton is part of the contract, because applications are expected to check what curve is in use by comparing it against the return value of `elliptic.P384()`.

In [CL 360015](https://go-review.googlesource.com/c/go/+/360015) I experimented with turning the concrete implementation of those singletons into a pointer to a generic type. (Feedback on the use of generics welcome!)

Unexpectedly, this led to a test failure that stems from this switch not matching the singletons anymore.

https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/crypto/x509/x509.go#L508-L521

I tried reproducing it with a contained example on the playground, but things worked as expected, so I am not sure what is going on. https://go2goplay.golang.org/p/9jnZvqnPDrh

/cc @griesemer

**Comment by griesemer** [comment]
Can you whittle down (remove everything that's not needed to re-produce the problem) in the real code and send that CL? Then we can cherry-pick and investigate.

**Comment by randall77** [comment]
Hm, the switch is failing because the itab of the incoming interface doesn't match the itab returned by the calls.
There are 4 identically-named, but different, itabs in this binary:
```
00000000011f4e08 s _go.itab.*crypto/elliptic.nistCurve[*crypto/elliptic/internal/nistec.P224Point],crypto/elliptic.Curve
00000000011f4e50 s _go.itab.*crypto/elliptic.nistCurve[*crypto/elliptic/internal/nistec.P224Point],crypto/elliptic.Curve
00000000011f4e98 s _go.itab.*crypto/elliptic.nistCurve[*crypto/elliptic/internal/nistec.P224Point],crypto/elliptic.Curve
00000000011f4ee0 s _go.itab.*crypto/elliptic.nistCurve[*crypto/elliptic/internal/nistec.P224Point],crypto/elliptic.Curve
```
That's not good. We require that itabs be unique, so that we can type switch using equality of itabs.

**Comment by randall77** [comment]
The linker is not deduplicating the itabs because their `_type` fields are different.
The 4 types are
```
1190f40
1191020
1191100
11911e0
```
I'm not sure yet why the types aren't being deduplicated. They have the same name, and they look identical except for the `ptrToThis` fields.

**Comment by randall77** [comment]
I've made a small repro that I think is the same underlying cause.
I think we need type deduplication in the linker.
It doesn't look like we have such a thing currently. Kind of surprises me that it hasn't been needed to date. Yet tests without generics that should provoke the same problem ... don't. More investigation needed.

**Comment by FiloSottile** [comment]
@rogpeppe prepared a self-contained testscript for this issue in #49245.

```
go run ./pkg1

-- go.mod --
module m

go 1.18
-- pkg1/main.go --
package main

import (
	"fmt"
	"os"
	"reflect"

	"m/pkg2"
	"m/pkg3"
)

func main() {
	i1 := pkg3.GetI()
	i2 := pkg2.Inst
	instEqual := i1 == i2
	if !instEqual {
		v1, v2 := reflect.ValueOf(i1), reflect.ValueOf(i2)
		ptrEqual := v1.Pointer() == v2.Pointer()
		typeEqual := v1.Type() == v2.Type()
		if !ptrEqual {
			fmt.Printf("pointer values are unequal\n")
		}
		if !typeEqual {
			fmt.Printf("types are not equal\n\t%v\n\t%v\n", v1.Type(), v2.Type())
		}
		os.Exit(1)
	}
}

-- pkg2/x.go --
package pkg2

import "m/pkg3"

var Inst = pkg3.GetI()

-- pkg3/x.go --
package pkg3

type I interface{}

type impl[P any] struct{
	_ byte
}

var instance = &impl[int]{}

func GetI() I {
	return instance
}
```

```
> go run ./pkg1
[stdout]
types are not equal
	*pkg3.impl[int]
	*pkg3.impl[int]

[stderr]
exit status 1
```
