### ISSUE TITLE
time: Add after or equal and before or equal

### ISSUE THREAD

**Issue by alexander-melentyev** [golang/go#49255]
Need AfterOrEqual and BeforeOrEqual methods in time package

If you need check t after or equal you code this
```go
if time.After(u) || time.Equal(u) {
    // ...
}
```
With needed methods
```go
if time.AfterOrEqual(u) {
    // ...
}
```
Code look cleaner

#49252

**Comment by moredure** [comment]
you can just use `!time.Before(u)`

**Comment by alexander-melentyev** [comment]
@moredure thank you!
