### ISSUE TITLE
Import cycle not allowed, is the principle really a good solution?

### ISSUE THREAD

**Issue by ankisme** [golang/go#49251]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.1 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I write simple code to try to describe real world, but "Import cycle not allowed" will compile error. So I could only rewrite the simple code to complex code.

"Import cycle not allowed" is a right principle, but it is not a principle to makes code simple, it makes code more complex.

Is it a temporary principle or a permanent principle? Will import cycle allowed in the future?

Is it designed after many consider and discuss, or only for personal preference?

I ask this question, because I think in real world, everything interacts with each other naturally.

For example, a teacher enter a classroom, many students enter a classroom, then teacher choose student a to ask, then the student b ask teacher. It is a normal simple requirement.

But in golang, the below code could not compile success, because import cycle not allowed. It is so strange.
```
testgo
│  main.go
│
├─classroom
│      ClassRoom.go
│
├─student
│      Student.go
│
└─teacher
        Teacher.go
```
```go
// main.go
package main

import (
	"testgo/classroom"
	"testgo/student"
	"testgo/teacher"
)

func main() {
	c := &classroom.ClassRoom{}
	t := &teacher.Teacher{}
	a := &student.Student{}
	b := &student.Student{}
	t.Enter(c)
	a.Enter(c)
	b.Enter(c)
	t.Ask(a)
	b.Ask(t)
	print(c)
}
```

```go
// classroom/ClassRoom.go
package classroom

import (
	"testgo/student"
	"testgo/teacher"
)

type ClassRoom struct {
	Teacher  *teacher.Teacher
	Students []*student.Student
}

func (c *ClassRoom) AddTeacher(t *teacher.Teacher) {
	c.Teacher = t
}

func (c *ClassRoom) AddStudent(s *student.Student) {
	c.Students = append(c.Students, s)
}
```

```go
// teacher/Teacher.go
package teacher

import (
	"testgo/classroom"
	"testgo/student"
)

type Teacher struct {
	TeacherName string
	InClassRoom *classroom.ClassRoom
}

func (t *Teacher) Enter(c *classroom.ClassRoom) {
	c.AddTeacher(t)
	t.InClassRoom = c
}

func (t *Teacher) Ask(s *student.Student) {

}
```

```go
// student/Student.go
package student

import (
	"testgo/classroom"
	"testgo/teacher"
)

type Student struct {
	StudentName string
	InClassRoom *classroom.ClassRoom
}

func (s *Student) Enter(c *classroom.ClassRoom) {
	c.AddStudent(s)
	s.InClassRoom = c
}

func (s *Student) Ask(t *teacher.Teacher) {

}
```

<font color="#dd0000"> Finally, it will compile error like below </font>
```
package testgo
	imports testgo/classroom
	imports testgo/student
	imports testgo/classroom: import cycle not allowed
```

There are more examples.

In real world, Cat catch Rat, Rat escape from Cat. `package Cat` import `package Rat`, and `package Rat` import `package Cat`.

In real world, Animal eat Fruit, Fruit be eat by Animal. `package Animal` import `package Fruit`, and `package Fruit` import `package Animal`.

In real world, import cycle occur everywhere.

But in golang, import cycle not allowed.

### What did you expect to see?

enable import cycle, just like the real world

### What did you see instead?

import cycle not allowed

**Comment by seankhliao** [comment]
This won't change.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by ankisme** [comment]
OK, sorry for I don't know the question link https://github.com/golang/go/wiki/Questions.
