### ISSUE TITLE
x/vuln/vulncheck: unavailable module version for github and local modules

### ISSUE THREAD

**Issue by zpavlinovic** [golang/go#49264]
For a project cloned from github or in current development under a specific version, how to obtain the version? Currently, the version string of packages.Module is "". Perhaps use something based on src/cmd/go/internal/vcs?

**Comment by bcmills** [comment]
See #37475 (slated for Go 1.18).

**Comment by zpavlinovic** [comment]
Regardless of whether a dependent module is vendored or a local version is used instead, it needs to appear in go.mod file with a version that vulncheck will pick up. The current module under analysis will have "" as version, but that is handled properly by vulncheck now.
