### ISSUE TITLE
blog: links to the fuzzer docs are broken

### ISSUE THREAD

**Issue by kevinburke** [golang/go#49278]
The [blog post introducing the fuzz beta](https://go.dev/blog/fuzz-beta) says:

> You can read more about fuzzing at pkg.go.dev, including [an overview of fuzzing with Go](https://pkg.go.dev/testing@master#hdr-Fuzzing) and [the godoc for the new testing.F type](https://pkg.go.dev/testing@master#F).

When I click on either of these links, I get taken to a page that lists subdirectories of the "testing" package but doesn't contain any information about fuzzing.

**Comment by kevinburke** [comment]
In the meantime, another place to look at the docs is here: https://github.com/golang/go/blob/master/src/testing/testing.go#L143-L232

**Comment by zikaeroh** [comment]
Unless I'm mistaken, this is #49229 (which is affecting a lot of stdlib packages).

**Comment by seankhliao** [comment]
Duplicate of #49229
