### ISSUE TITLE
cmd/compile/internal/types2: review implementation of indexing of generic types

### ISSUE THREAD

**Issue by danscales** [golang/go#49275]
On go tip (generics), the below program gets a compile error

./test.go:6:15: invalid operation: cannot index x (variable of type T constrained by interface{[]int64|map[int]int64})

Program:

```
package main

import "fmt"

func g[T interface{ []int64 | map[int]int64 }](x T) int64 {
	return x[3])
}

func main() {
	x := make(map[int]int64)
	y := make([]int64, 4)

	fmt.Printf("%v %v\n", g(x), g(y))
}
```
That happens even though individually the functions:

```
func g[T interface{ []int64 }](x T) int64 {
	return x[3]
}
```

and

```
func g[T interface{ map[int]int64 }](x T) int64 {
	return x[3]
}
```

compile/run fine.  We need a fix and/or need to decide exactly which of map/slice/array/string types can be combined in a type constraint, and allow indexing on the type param.  (And make rules more explicit if we disallow certain cases.)

@griesemer @findleyr

**Comment by griesemer** [comment]
The current generic indexing is both too relaxed and not tight enough. While this could be made to work, maps are sufficiently different from all the other indexable types that it gets very quickly extremely complicated. We probably should differentiate between all maps and all something else in the type set for now.

**Comment by griesemer** [comment]
Follow-up: This code is working as intended. If we have a map in the the type set, all types must be maps with the same underlying type, otherwise we cannot index.

What is not working correctly (missing tests!) is assignments to indexed generic expression that are not assignable (because e.g. the type set contains a string). Fix forthcoming.
