### ISSUE TITLE
cmd/go2go: cannot infer generic types when functions have no parameter

### ISSUE THREAD

**Issue by sina-devel** [golang/go#49279]
my code: https://go2goplay.golang.org/p/RmdhTCJTy1Q

### What did you expect to see?
nothing

### What did you see instead?
```
type checking failed for main
prog.go2:11:14: cannot infer T (prog.go2:3:11) ([<nil>])
prog.go2:17:14: cannot infer T (prog.go2:3:11) ([<nil>])
```

but this is works https://go2goplay.golang.org/p/T46pnt3s8kH

**Comment by thanm** [comment]
The go2go playground is out of date, we are in the process of decommissioning it, see https://github.com/golang/go/issues/48517. At the moment we don't have a "preview of 1.18" playground set up (hopefully that will happen soon). In the mean time, you might consider using https://pkg.go.dev/golang.org/dl/gotip (with appropriate caveats). Thanks.
