### ISSUE TITLE
unexpected output from go list command

### ISSUE THREAD

**Issue by ManojKumarChauhan** [golang/go#49283]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.16
</pre>

### Does this issue reproduce with the latest release?
yes
### What operating system and processor architecture are you using (`go env`)?
ubuntu 16.04.7
golang 1.16
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="/usr/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2928214481=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
trying to get the version details using go list command 
go list all -m github.com/gomodule/redigo/redis

I forked redis into github.com/ManojKumarChauhan/redigo/redis and tried to run go list command but it's giving following error:

go.opentelemetry.io/otel/exporters/otlp/otlpmetric/internal/connection/connection.go:26:2: found import comments "go.opentelemetry.io/otel/exporters/otlp/internal/otlpconfig" (options.go) and "go.opentelemetry.io/otel/exporters/otlp/otlpmetric/internal/otlpconfig" (optiontypes.go) in /root/go/src/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/internal/otlpconfig
cannot find package "-m" in any of:
	/usr/local/go/src/-m (from $GOROOT)
	/root/go/src/-m (from $GOPATH)

references
https://levelup.gitconnected.com/go-modules-replace-3ea6d0139c91
https://stackoverflow.com/questions/69748360/why-do-method-of-conn-interface-is-inlined/69748873#69748873

Without using -m option:
go.opentelemetry.io/otel/exporters/otlp/otlpmetric/internal/connection/connection.go:26:2: found import comments "go.opentelemetry.io/otel/exporters/otlp/internal/otlpconfig" (options.go) and "go.opentelemetry.io/otel/exporters/otlp/otlpmetric/internal/otlpconfig" (optiontypes.go) in /root/go/src/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/internal/otlpconfig

no version information is displayed.
Same error for go1.17.1 & go1.17.2 versions

### What did you expect to see?
go list -m command should print the version detail

### What did you see instead?
go list -m command is failed

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by ManojKumarChauhan** [comment]
I created this issue because one function in redigo package is inlined. Expert suggested to use 'go list all -m' command to solve that. But this command is not working in any go version so I created this issue. You are suggesting to ask in other forums which I already did.
