### ISSUE TITLE
runtime: non-cooperative goroutine preemption does not work when built using c-archive or c-shared

### ISSUE THREAD

**Issue by wangfakang** [golang/go#49288]
Non-cooperative goroutine preemption does not work when built using c-archive or c-shared, because of this [PR]( https://github.com/golang/go/commit/fbdfa99246ecbb04954a042a5809c4748415574d#diff-bac254c4b6706149a6bd923ec4ab48baadd95fdf1597192f78cf36616fe49f78R71) not install signal go handler and cause signal preemption disabled.

### What version of Go are you using (`go version`)?

<pre>
$ 1.14

</pre>

### Does this issue reproduce with the latest release?

yeah.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/fakang.wfk/.cache/go-build"
GOENV="/home/fakang.wfk/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"

</pre></details>

### What did you do?

test.c
```
#include <stdio.h>
#include <unistd.h>

#include"cgo.h"

int main(){
    sleep(1);
    printf("start cgo\n");
    test();
    printf("exit cgo\n");
    sleep(5);
    return 0;
}
```

cgo.go
```
package main

import (
        "runtime"
)

import "C"

func init() {
        runtime.GOMAXPROCS(1)
        go func() {
                println("init ok")
                for {
                }
        }()
}

//export test
func test() {
        println("I got scheduled!")
}

func main() {}
```

run:

go build -o cgo.so -buildmode=c-shared cgo.go
gcc -o main main.c  cgo.so  

### What did you expect to see?
./main
```
init ok
start cgo
I got scheduled!
exit cgo
```

### What did you see instead?
./main
```
init ok
start cgo
```

**Comment by wangfakang** [comment]
@ianlancetaylor The signal _SIGPROF may also need to be added because CPUProfile depends on it.
![image](https://user-images.githubusercontent.com/8215757/141403061-667fb240-95a7-4ce5-a59e-7793c8321822.png)

**Comment by ianlancetaylor** [comment]
Please always write plain text as plain text, never as an image.  Plain text is much easier to read and it is possible to cut and paste it.  Thanks.

If Go profiling is requested a signal handler will be installed for `SIGPROF` if necessary.  We definitely don't want c-archive or c-shared Go code to override the `SIGPROF` handling of the main program; we only want to use the Go handling if the Go program specifically requests it.

**Comment by wangfakang** [comment]
> Please always write plain text as plain text, never as an image. Plain text is much easier to read and it is possible to cut and paste it. Thanks.
> 
> If Go profiling is requested a signal handler will be installed for `SIGPROF` if necessary. We definitely don't want c-archive or c-shared Go code to override the `SIGPROF` handling of the main program; we only want to use the Go handling if the Go program specifically requests it.

Um, sorry. Because I didn't have permission to comment directly on the `go-review.googlesource.com` platform, so do it.
I have a question that if we don't want c-archive or c-shared Go code to override the `SIGPROF` handling of the main program, but why is it necessary to check  `SIGPROF` in [runtime·cgoSigtramp](https://github.com/golang/go/blob/6b3f4d388fe5602172f45361f438edf54699b953/src/runtime/sys_linux_amd64.s#L386)?
https://github.com/golang/go/blob/6b3f4d388fe5602172f45361f438edf54699b953/src/runtime/sys_linux_amd64.s#L436-L440

**Comment by ianlancetaylor** [comment]
The `cgoSigtramp` function is used in all build modes, not just c-archive and c-shared.  Also, to be clear, I am saying that for c-archive and c-shared we must not override the handling of `SIGPROF` by default.  If the program itself calls Go functions like `runtime/pprof.StartCPUProfile`, then the Go standard library will go ahead and override the handling of `SIGPROF`.  And in that case of course it's important that `cgoSigtramp` handle `SIGPROF` correctly.

Further discussion of these points should take place in a forum, not here on the issue tracker.  See https://golang.org/wiki/Questions.  Thanks.
