### ISSUE TITLE
time: ParseInLocation error 

### ISSUE THREAD

**Issue by FreeDemon** [golang/go#49284]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/freedemon/Library/Caches/go-build"
GOENV="/Users/freedemon/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/freedemon/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/freedemon/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/Cellar/go/1.17.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.2/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/freedemon/Documents/code/goProject/go2/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9y/nkxhf5yd3c7fvqdsdvdwm18r0000gn/T/go-build2346662675=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Why are these times incorrect and missed some time ?

<pre>
package main

import (
	"fmt"
	"time"
)

func main() {
	timeLayout := "2006-01-02 15:04:05"
	loc, _ := time.LoadLocation("Asia/Shanghai")

	time1, _ := time.ParseInLocation(timeLayout,"1991-09-14 16:50:50", loc)
	fmt.Println(time1)

	time2, _ := time.ParseInLocation(timeLayout,"1991-09-14 17:00:00", loc)
	fmt.Println(time2)

	time3, _ := time.ParseInLocation(timeLayout,"1991-09-15 00:50:00", loc)
	fmt.Println(time3)

	time4, _ := time.ParseInLocation(timeLayout,"1991-09-15 01:00:00", loc)
	fmt.Println(time4)
}
</pre>

### What did you expect to see?
1991-09-14 16:50:50 +0900 CDT
1991-09-14 17:00:00 +0900 CDT
1991-09-15 00:50:00 +0900 CDT
1991-09-15 01:00:00 +0800 CST

### What did you see instead?
1991-09-14 16:50:50 +0900 CDT
1991-09-14 18:00:00 +0900 CDT
1991-09-15 01:50:00 +0900 CDT
1991-09-15 01:00:00 +0800 CST

**Comment by ALTree** [comment]
This does seem a bug. 

In absence of a timezone indicator, `ParseInLocation` should interpret the timestamp as if it was in the given location. `Asia/Shanghai` did [end Daylight Saving Time](https://www.timeanddate.com/time/change/china/shanghai?year=1991) at 02:00, Sep 15 1991, but `1991-09-14 17:00:00` is several hours before that. Why it's corrected to 18:00 ?

cc @ianlancetaylor

**Comment by rchunping** [comment]
seems a bug
use this instead:

loc:= time.FixedZone("Asia/Shanghai",3600*8)

**Comment by FreeDemon** [comment]
> seems a bug use this instead:
> 
> loc:= time.FixedZone("Asia/Shanghai",3600*8)

thank u, i'll try it

**Comment by zhouguangyuan0718** [comment]
> > seems a bug use this instead:
> > loc:= time.FixedZone("Asia/Shanghai",3600*8)
> 
> thank u, i'll try it

The actual time between 1991-04-14 02:00:00  to   1991-09-15 01:00:00  in  Asia/Shanghai is Daylight Saving Time. We can't use fixed offset for it.

This bugs happens because it get a incorrect offset in the function time.Data:
https://github.com/golang/go/blob/bd580a0d10729553a7905481d17eed0436198866/src/time/time.go#L1444
At that time. the start is invalid, we can't get the correctly offset by lookup(start-1).

@FreeDemon You can't try the CL above. I think It can solve this problem.
https://github.com/golang/go/issues/49284#issuecomment-957815305

**Comment by zhouguangyuan0718** [comment]
@gopherbot  please open backport to 1.16 and 1.17
