### ISSUE TITLE
cmd/compile: gotip cannot infer generic types when functions have no generic parameter

### ISSUE THREAD

**Issue by sina-devel** [golang/go#49297]
### What version of Go are you using (`gotip version`)?

<pre>
$ gotip version
go version devel go1.18-62b29b0 Tue Nov 2 17:01:14 2021 +0000 linux/amd64
</pre>

### What did you do?
```go
package main

func zero[T any]() T {
	var o T
	return o
}

func getInt(a int) {}

func zeroInt() int {
	return zero()
}

func main() {
	zeroInt()
	getInt(zero())
}

```

### What did you expect to see?
Successful compilation

### What did you see instead?
```
main.go:11:13: cannot infer T (main.go:3:11)
main.go:17:13: cannot infer T (main.go:3:11)
```

**Comment by ianlancetaylor** [comment]
This is working as intended.  Inference is based only on function arguments and constraints.  See the description at https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#type-inference.

**Comment by sina-devel** [comment]
@ianlancetaylor Ok, and that means it is not possible to add it in future?

**Comment by ianlancetaylor** [comment]
It is possible to add it in the future.  But it would need a clear and precise design for how it works.  It should be written as a language change proposal; see https://golang.org/s/proposal.  It's not obvious to me how it should work; exactly what types should be inferred if I write `zero() + zero() != zero()`, and why?

**Comment by ianlancetaylor** [comment]
If I understand this correctly, it's basically the same as #50285, which is still open.
