### ISSUE TITLE
How to restrict pointer type's underlying type

### ISSUE THREAD

**Issue by SilverRainZ** [golang/go#49308]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-088bb4bf4a Tue Nov 2 06:25:39 2021 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Of course.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

We use  `~T` to restrict to all types whose underlying type is T,  so `~*T` restrict to all types whose underlying type is `*T`. How can we restrict to all pointer types whose point to underlying type `T`?

### What did you expect to see?

A syntax like `*~T`, which restricts to all pointer types whose point to underlying type `T`.

### What did you see instead?

There is no such a syntax.

**Comment by seankhliao** [comment]
what would the actual type of the pointer be?

**Comment by SilverRainZ** [comment]
Use `bool` as exmaple:

```
type MyBool bool

var a *bool
var b *MyBool
```

The actal type can be `*bool` or `*MyBool`, I hope there is a generic type can restrict to them.

**Comment by randall77** [comment]
Not sure what you're trying to do, but why not make the element type the type parameter, and use pointers to that type parameter in your code:
```
func f[T ~bool](x *T) *T { ... }
```
or even
```
func [T ~bool, P *T](x P) P { ... }
```

**Comment by ianlancetaylor** [comment]
This question has been answered, so closing.  In general please ask questions in a forum, rather than the issue tracker.  See https://golang.org/wiki/Questions.  Thanks.
