### ISSUE TITLE
time: Ticker.Reset(0) deadlocks

### ISSUE THREAD

**Issue by tfg13** [golang/go#49315]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/XXXX/Library/Caches/go-build"
GOENV="/Users/XXXX/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/XXXX/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/XXXX/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ct/1_807xnx3yvbbym9xwypyc540000gn/T/go-build1490192283=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://play.golang.org/p/weOQpA3YuFD

### What did you expect to see?

Either:
- panic the `Reset` call for setting duration to zero (this will panic in `time.NewTicker`, but does not in `time.Reset`)
- tick the channel as fast as possible (delay zero), lots of "tick" output in my example

### What did you see instead?

The ticker fires exactly one more tick, then stops - the example deadlocks because nothing is running anymore.
For any Duration >0 the ticker does not stop ticking after one tick.

**Comment by seankhliao** [comment]
cc @rsc

**Comment by bradfitz** [comment]
I suspect panicking will be too invasive of a change. I'm sure there's plenty of code in the wild that does some math to compute a duration for Reset and isn't careful about whether it's <= 0 when what the caller would instead want is "right away".

**Comment by zhouguangyuan0718** [comment]
> I suspect panicking will be too invasive of a change. I'm sure there's plenty of code in the wild that does some math to compute a duration for Reset and isn't careful about whether it's <= 0 when what the caller would instead want is "right away".

But if we make it tick as fast as possible when period is 0. This change is invasive, too.
Is it a reasonable choice if we keep as it is, and make this behavior as a feature?

**Comment by bradfitz** [comment]
Oh, sorry, I read this too quickly about being about Timer.Reset.

**Comment by zhouguangyuan0718** [comment]
I sent the CL above to fix this bug by adding a check. If duration <= 0, it will panic.
https://go-review.googlesource.com/c/go/+/361074/

If it is the right way to fix it, could anyone review it continue and submit?
Thanks.
