### ISSUE TITLE
x/build: host-openbsd-arm-joelsing is missing

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#49326]
From https://farmer.golang.org/#pools:

```
host-openbsd-arm-joelsing: 0/0 (1 missing)
```

@4a6f656c Are you able to take a look?
@golang/release

**Comment by 4a6f656c** [comment]
The builder machine has eaten another SD card - I'll replace it and get it back online when I can.

**Comment by 4a6f656c** [comment]
This builder has been rebuilt and is back online.

**Comment by dmitshur** [comment]
Thank you Joel.
