### ISSUE TITLE
x/pkgsite: package removal request for github.com/aletheia7/gogroup

### ISSUE THREAD

**Issue by aletheia7** [golang/go#49323]
### What is the path of the package that you would like to have removed?
github.com/aletheia7/gogroup
 
### Are you the owner of this package?
Yes.
 
### What is the reason that you could not retract this package instead?

Please remove all versions (v0.0.0 , v0.2.1, v2) except the only two tags of v0.1.0 and v0.2.0.

The old tags are gone from the git repo.

The go mod -retract complains about missing tags. I had to delete the repo and remake.

Please update pkg.go.dev.

**Comment by jamalc** [comment]
Looks like you were able to successfully retract. Please re-open if necessary.
