### ISSUE TITLE
cmd/link: why golang linker only save parts of  relocations into go.o in external linking mode?

### ISSUE THREAD

**Issue by hailingluo** [golang/go#49333]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 linux/arm64
</pre>

### What did you expect to see?
PATH: go\src\cmd\link\internal\arm64\asm.go
function: 
func elfreloc1(ctxt *ld.Link, out *ld.OutBuf, ldr *loader.Loader, s loader.Sym, r loader.ExtReloc, ri int, sectoff int64) bool {
   ...
}

In this function, it only emits some types of relocations into go.o as the following description. why?
There still exist some other types of relocations.

objabi.R_ADDR, objabi.R_DWARFSECREF -> elf.R_AARCH64_ABS32/elf.R_AARCH64_ABS64
objabi.R_ADDRARM64                  -> elf.R_AARCH64_ADR_PREL_PG_HI21 and elf.R_AARCH64_ADD_ABS_LO12_NC
objabi.R_ARM64_TLS_LE               -> elf.R_AARCH64_TLSLE_MOVW_TPREL_G0
objabi.R_ARM64_TLS_IE               -> elf.R_AARCH64_TLSIE_ADR_GOTTPREL_PAGE21 and elf.R_AARCH64_TLSIE_LD64_GOTTPREL_LO12_NC
objabi.R_ARM64_GOTPCREL             -> elf.R_AARCH64_ADR_GOT_PAGE and elf.R_AARCH64_LD64_GOT_LO12_NC
objabi.R_CALLARM64                  -> elf.R_AARCH64_CALL26

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
