### ISSUE TITLE
x/pkgsite: package removal request for github.com/kanjih/spnr

### ISSUE THREAD

**Issue by kanjih** [golang/go#49330]
### What is the path of the package that you would like to have removed?
github.com/kanjih/spnr 
 
### Are you the owner of this package?
Yes.

### What is the reason that you could not retract this package instead?
Because I published many versions accidentally (to practice how git tag & library versions works) before I actually release the library.

**Comment by kanjih** [comment]
notes:
I removed the repository from github because it was not official release.

**Comment by jamalc** [comment]
Have you already tried [retracting](https://go.dev/ref/mod#go-mod-file-retract) your module?

**Comment by kanjih** [comment]
In my case retracting doesn't work.
I already pushed many versions including v8, but that's not intentional and I'd like to start from v1 again.
In [pkg.go.dev](https://pkg.go.dev/github.com/kanjih/spnr), it says
> Notice  The highest tagged major version is v8.
But it's not intentional, I cannot remove this message by retracting.

So please remove all the docs so that I can publish docs from scratch again. Thanks!

**Comment by jamalc** [comment]
Once your module is removed from pkg.go.dev, documentation for any package that starts with the name `github.com/kanjih/spnr` will not be visible but your module will still be available for download from the [module proxy](https://proxy.golang.org/).

Published versions of a module are immutable. There is no way to start publishing github.com/kanjih/spnr from v1 again. If you plan to publish this module with a different name I'll go ahead and remove the module. If you want to keep the same name you should use the retract directive.

**Comment by kanjih** [comment]
Ok, I'll this module with a different name, please remove it.

**Comment by jamalc** [comment]
Done.
