### ISSUE TITLE
net: DialTCP doesn't set TCP keepalive (unlike Dialer.Dial)

### ISSUE THREAD

**Issue by database64128** [golang/go#49345]
### What version of Go are you using (`go version`)?

All current versions apply.

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Not platform specific.

### What did you do?

Call `net.DialTCP()`.

### What did you expect to see?

The default 15s TCP keepalive setting is applied to the connection.

### What did you see instead?

TCP keepalive is not enabled.

Merging [this section](https://github.com/golang/go/blob/2622235a99800d1d7add47c5c138f5efbe51361c/src/net/dial.go#L434-L442) into [newTCPConn](https://github.com/golang/go/blob/2622235a99800d1d7add47c5c138f5efbe51361c/src/net/tcpsock.go#L209) should solve this disparity between `net.Dialer.Dial[Context]()` and `net.DialTCP()`.

**Comment by seankhliao** [comment]
cc @ianlancetaylor @neild

**Comment by ianlancetaylor** [comment]
There is a key difference, though: `Dial` permits controlling the keep alive setting via the `Dialer.KeepAlive` field.  There is no way to control the keep alive setting for `DialTCP`, and no way to change it afterward.

If #49097 is adopted then we can set keep alive for the new `DialTCP` method of `Dialer`.  When we do that it will be reasonable to change the `net.DialTCP` function, as there will be a way to change the default.  Until then, or until there is some other mechanism to change the keep alive, I don't think we can do this.

**Comment by neild** [comment]
Wouldn't the way to control the keep alive setting be to use `Dialer.Dial` and type assert the resulting `net.Conn` to a `*TCPConn`?

**Comment by ianlancetaylor** [comment]
That works, but then you aren't using `net.DialTCP`.  Maybe I'm missing something.

**Comment by neild** [comment]
I guess I'm thinking that `net.DialTCP` is effectively a convenience wrapper for `net.Dial("tcp", ...)`, avoiding the need to type assert the result to a `*net.TCPConn`. If that's the case, then it seems reasonable for it to use the default value for any `net.Dial` configuration settings.

Maybe I'm missing something.

**Comment by ianlancetaylor** [comment]
As I see it the main reason to use `net.DialTCP` is to pass a `*net.TCPAddr` for the addresses rather than having to convert them to a string for `net.Dial`.

**Comment by database64128** [comment]
> There is a key difference, though: `Dial` permits controlling the keep alive setting via the `Dialer.KeepAlive` field. There is no way to control the keep alive setting for `DialTCP`, and no way to change it afterward.

You can change it afterwards by calling `net.TCPConn.SetKeepAlive` and `net.TCPConn.SetKeepAlivePeriod` right after `net.DialTCP`.

> as there will be a way to change the default.

One could also argue there's never been a way to override the default of setting `TCP_NODELAY` socket option in these dial functions and methods. I think it's safe to make setting `TCP_KEEPALIVE/INTVL/IDLE` the default with `net.DialTCP`, because these socket options, just like `TCP_NODELAY`, can be changed anytime during the socket's lifetime.

**Comment by ianlancetaylor** [comment]
Ah, sorry, missed the `SetKeepAlive` method.  Sure, this seems fine.
