### ISSUE TITLE
runtime: TestTracebackArgs failure for testTracebackArgs9

### ISSUE THREAD

**Issue by bcmills** [golang/go#49354]
`greplogs --dashboard -md -l -e 'FAIL: TestTracebackArgs' --since=2021-10-28T15:08:00`

[2021-11-04T00:15:11-6049630/darwin-amd64-10_15](https://build.golang.org/log/dbb3f935922bc17b5001ffb8428453434382f56e)

`testTracebackArgs9` is one of the cases added for #45728 in Go 1.18 (CC @cherrymui @mknyszek).

**Comment by cherrymui** [comment]
Thanks. I have a guess. Will send a CL.
