### ISSUE TITLE
cmd/go: go help testflag is poorly formatted for the -shuffle flag

### ISSUE THREAD

**Issue by sfllaw** [golang/go#49357]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 linux/amd64
</pre>

### What did you do?

<pre>
$ go help testflag
…
	-shuffle off,on,N
		Randomize the execution order of tests and benchmarks.
		It is off by default. If -shuffle is set to on, then it will seed
		the randomizer using the system clock. If -shuffle is set to an
		integer N, then N will be used as the seed value. In both cases,
		the seed will be reported for reproducibility.
…
</pre>

### What is the problem?

The following stanza of the help text is using a tab character instead of four spaces, unlike the rest of the help text:
https://github.com/golang/go/blob/629ffebd451613b32e6b9578ff4c807791197b38/src/cmd/go/internal/test/test.go#L309-L314

**Comment by thanm** [comment]
@bcmills @matloob

**Comment by tpaschalis** [comment]
Oh, that was me 😅  Thank you @sfllaw for catching this and congratulations on merging your first CL!
