### ISSUE TITLE
net: new UDP allocs test breaks on Plan 9

### ISSUE THREAD

**Issue by millerresearch** [golang/go#49376]
CL [361396](https://go-review.googlesource.com/c/go/+/361396) added `TestAllocs` in udpsock_test.go which fails with message "not supported by plan 9".

The test uses function `(*UDPConn).writeMsgAddrPort` which indeed is not supported on Plan 9 (perhaps someone else knows why not?).

A number of other tests in this file are skipped when running on Plan 9. It appears this one should be skipped too.

**Comment by mvdan** [comment]
cc @josharian

**Comment by josharian** [comment]
Fixed by CL 361634.
