### ISSUE TITLE
x/sys/unix: TestPoll failures with "wrong number of events" beginning 2021-11-04

### ISSUE THREAD

**Issue by bcmills** [golang/go#49380]
`greplogs --dashboard -md -l -e '(?m)FAIL: TestPoll .*\n\s+.*wrong number of events'`

[2021-11-05T07:00:05-7861aae-6fefb7f/linux-amd64](https://build.golang.org/log/47ef27ee6c57c716bf34df78933a93f60e051dcd)
[2021-11-05T00:52:09-7861aae-bd580a0/linux-amd64-race](https://build.golang.org/log/cffa5eda9b761c8b355102d873fc7f3ce3326c29)
[2021-11-04T21:41:49-7861aae-156abe5/linux-amd64-race](https://build.golang.org/log/e1bca2f6f772aa0c14dd43d21de68e7cd6162b86)

These all occurred after [CL 361255](https://golang.org/cl/361255) in `x/sys`, but I don't see how it could possibly be related. I suspect a regression on the Go side — @mknyszek, could this be another test that is overly sensitive to being interrupted by a GC cycle?

**Comment by bcmills** [comment]
(Marking as release-blocker for Go 1.18 because this appears to be a regression on linux-amd64, which is a first-class port.)

**Comment by mknyszek** [comment]
I'll look into it. I think you're probably right.

**Comment by mknyszek** [comment]
My attempts to reproduce this have been unsuccessful thus far. Is this particularly rare?

**Comment by mknyszek** [comment]
This failure mode is also so strange... It creates a FIFO that it then blocks on, and waits to time out. How could something be sent on that FIFO? What else could possibly get that FD?

**Comment by mknyszek** [comment]
Would it make sense to augment the test to print *which* events it thinks fired? Even if I can't reproduce locally, it should in theory pop up on the builders eventually.

**Comment by bcmills** [comment]
> My attempts to reproduce this have been unsuccessful thus far. Is this particularly rare?

It does seem to only occur in a small fraction of runs: we have a ton of `linux-amd64` builders and only a small number of failures per day (none at all since Nov. 6).

(But we've also had ∞% more failures than we did between whenever my `fetchlogs` data begins — I think at least sometime in 2019 at the moment? — and Nov. 4 of this year. 😅)

If we think it may have been fixed since Nov. 6, maybe we can park it in WaitingForInfo and see if it occurs again by the time the Gopherbot expires it?

----

`greplogs --dashboard -md -l -e '(?m)FAIL: TestPoll .*\n\s+.*wrong number of events' --since=2021-11-05T07:01:00`

[2021-11-06T13:10:06-c75c477-4f083c7/linux-amd64-race](https://build.golang.org/log/f0ab4ae502a5516972a1801056c3c6ccf268a723)
[2021-11-05T22:03:24-c75c477-035963c/linux-amd64-race](https://build.golang.org/log/74e0908f315f9956004c46364ea88ac96803bb62)

**Comment by bcmills** [comment]
> Would it make sense to augment the test to print _which_ events it thinks fired? Even if I can't reproduce locally, it should in theory pop up on the builders eventually.

I'm always in favor of more-descriptive test logs. 👍

**Comment by mknyszek** [comment]
Oops. I forgot to mark it as `golang/go#49380` in the CL. Anyway, golang.org/cl/363714 improves the logs. I'm going to put this in `WaitingForInfo` as you suggested Bryan, since we haven't seen it since Nov. 6th.

**Comment by bcmills** [comment]
Looks fixed to me.

`greplogs --dashboard -md -l -e '(?m)FAIL: TestPoll .*\n\s+.*wrong number of events' --since=2021-11-13`
