### ISSUE TITLE
test/recover4.go: failures with "interface is nil, not error" since 2021-11-04

### ISSUE THREAD

**Issue by bcmills** [golang/go#49381]
`greplogs --dashboard -md -l -e 'panic: interface conversion: interface is nil, not error'`

[2021-11-05T07:00:05-6fefb7f/linux-ppc64le-buildlet](https://build.golang.org/log/8cb959f5340b6b647c18d7e3b4e33fbd0ab02694)
[2021-11-05T07:00:05-6fefb7f/linux-ppc64le-power9osu](https://build.golang.org/log/6ce0fe929bde0c2d70814c1700e9cfbc1647b479)
[2021-11-05T05:29:10-3b5add5/linux-ppc64le-power9osu](https://build.golang.org/log/60fce8477619d915678810006150a72b21ebfec6)
[2021-11-05T00:52:06-3839b60/linux-mips64le-mengzhuo](https://build.golang.org/log/d43678391fab435e237125d7ef9dbf888cfd860a)
[2021-11-05T00:52:04-1c4cfd8/linux-mips64le-mengzhuo](https://build.golang.org/log/af5909f4913d43a0738b6df7d39d02d663eaf605)
[2021-11-04T21:52:51-1e0c3b2/linux-mips64le-mengzhuo](https://build.golang.org/log/52086f1022eb937319dd3d3ee8dd3d0c58c53f3f)
[2021-11-04T21:33:23-71fc881/linux-ppc64le-buildlet](https://build.golang.org/log/0e18e7b575c3a6437c9414176acc9cbb5153918a)
[2021-11-04T20:43:07-8248152/linux-mips64le-mengzhuo](https://build.golang.org/log/18efd13043cfcf129258c4754f808c80eff024b8)
[2021-11-04T20:31:02-978e39e/linux-ppc64le-power9osu](https://build.golang.org/log/366e43772961e364ab448f4b93a5f8c7d92f2b1c)
[2021-11-04T20:01:22-6d1fffa/linux-mips64le-mengzhuo](https://build.golang.org/log/3b142e85a74cfe3875ecc22f452a9641c9fe45cc)
[2021-11-04T20:00:54-961aab2/linux-ppc64le-buildlet](https://build.golang.org/log/fb58c482ea0f57c3de1a3bf14c5b6f5ae623386d)

**Comment by bcmills** [comment]
(Marked as release-blocker for Go 1.18 because this looks like a 1.18 regression.)

**Comment by laboger** [comment]
@bcmills How can we use greplogs? I couldn't find it.

**Comment by bcmills** [comment]
It's one of Austin's `go-misc` tools:
https://pkg.go.dev/github.com/aclements/go-misc/greplogs

**Comment by laboger** [comment]
I believe these are related to PacerRedesign. I can get the failure intermittently with the latest source but if I disable the PacerRedesign then I can't make it fail. The failures started about the time this was enabled.

**Comment by bcmills** [comment]
(CC @mknyszek)

**Comment by mknyszek** [comment]
That's... interesting. This suggests that the `memcopy` function just isn't faulting. I took a quick look and the main difference I see is that a GC is running during this test now whereas previous one was not.

I have a way to break the test with `GOEXPERIMENT=nopacerredesign` and just a well-placed GC:

```
diff --git a/test/recover4.go b/test/recover4.go
index 67ed970ecb..cd60382e65 100644
--- a/test/recover4.go
+++ b/test/recover4.go
@@ -1,4 +1,6 @@
+//go:build linux || darwin
 // +build linux darwin
+
 // run

 // Copyright 2015 The Go Authors. All rights reserved.
@@ -22,6 +24,7 @@ package main

 import (
        "log"
+       "runtime"
        "runtime/debug"
        "syscall"
        "unsafe"
@@ -54,6 +57,8 @@ func main() {

        other := make([]byte, 16*size)

+       go runtime.GC()
+
        // Note: Cannot call syscall.Munmap, because Munmap checks
        // that you are unmapping a whole region returned by Mmap.
        // We are trying to unmap just a hole in the middle.
```

For me, on `linux/ppc64le`, this fails immediately.

There's something else wrong with the test, or the runtime. I'm currently fielding a few other bugs so I'd appreciate some help with this.

**Comment by mknyszek** [comment]
Note that simply adding a `runtime.GC` call is not enough, because that's fully synchronous. It appears that the GC needs to be executing concurrently with the access. I don't know why that makes a difference.

Maybe there's something here about the goroutine doing the access migrating threads, and for whatever reason the result of the `munmap` just isn't visible on other threads? An execution trace would probably help flush this out. If it's a scheduling thing, then even just the execution trace or a well-place `Gosched` might be enough to poke the bug.

**Comment by mknyszek** [comment]
I poked the bug a few more times: I can reproduce on `linux-ppc64le-buildlet` just by adding a `trace.Start` and `defer trace.Stop` at the top of `main`. Looks like really any scheduling perturbation is enough to trigger this.

What's really interesting though is when I looked at the trace, the main goroutine never actually migrated Ps. It *may* have migrated OS threads or something, but certainly no Ps. I've also confirmed that, in fact, when this does happen, there's no segfault! So clearly something is super weird about that `munmap` on these platforms. I'm starting to wonder if this is some cache invalidation issue where, say, the executing code is migrated to another CPU or something after the `munmap` and the mapping still appears to be valid. Very, very little is going on in this test on the Go side.

Also, these platforms uniformly seem to have a relaxed memory model. Perhaps that's related in some way?

**Comment by mknyszek** [comment]
I'm not sure this indicates a larger issue. I'm going to mark this as not a beta blocker.

**Comment by mknyszek** [comment]
On a trybot, a new failure mode: https://storage.googleapis.com/go-build-log/0d23a8f3/linux-ppc64le-buildlet_73293137.log

**Comment by cherrymui** [comment]
Could it be possible that the runtime (or something else) that mmaps the pages immediately after our munmap? (I don't know why the runtime would map that, though.) Could we make the hole unwritable using a different way, maybe mprotect?

**Comment by mknyszek** [comment]
Yes! That's a really, really good point Cherry. That's sounds like it. I'll take a closer look tomorrow.

**Comment by mknyszek** [comment]
Yeah, that's exactly what's happening. Probably a `persistentalloc` mapping or something.

```
sysMap 0xc000000000 4194304
sysMap 0x7d3dca3e0000 131072
sysMap 0x7d3dca2e0000 65536
sysMap 0x7d3dc9ae0000 65536
sysMap 0x7d3dc5b10000 65536
sysMap 0x7d3da5c60000 65536
sysAlloc 0x7d3da37b0000 1048576
sysAlloc 0x7d3da37a0000 65536
sysAlloc 0x7d3da3790000 65536
sysAlloc 0x7d3da3750000 262144
recover4.go mapping 0x7d3da3650000 0x7d3da374ffff
sysAlloc 0x7d3da36d0000 262144
panic: interface conversion: interface is nil, not error

goroutine 1 [running]:
main.memcopy.func1()
	/workdir/go/test/recover4.go:35 +0x4c
main.memcopy({0x7d3da3650005?, 0x7d3da36d0000?, 0x40000?}, {0xc000080000?, 0x0?, 0x8698c?})
	/workdir/go/test/recover4.go:42 +0xdc
main.main()
	/workdir/go/test/recover4.go:72 +0x1e0
```
