### ISSUE TITLE
gerrit: Google/Gmail account requirement should be relaxed

### ISSUE THREAD

**Issue by illiliti** [golang/go#49383]
At the moment, you can't contribute to Go unless you provide your personal data to Google. This requirement should be relaxed as it is completely unacceptable for open-source project.

**Comment by seankhliao** [comment]
cc @golang/osp-team

**Comment by mvdan** [comment]
@illiliti for what it's worth, you can send a patch by opening a GitHub PR. You won't be able to reply on Gerrit to reviews, though.

**Comment by illiliti** [comment]
The problem is that such PRs cannot be merged because you need to sign CLA which require Google/Gmail account...

**Comment by ALTree** [comment]
I think the CLA is the bigger blocker; but the need for a google account it's not a requirement enforced by the Go Project: it's a Google CLA thing. According to [this](https://opensource.google/docs/cla/#external-contributors):

> Contributors must sign in with a Google account to sign the CLA or manage their CLA agreements.

Of course you could argue that the Go Project could stop requiring the CLA, but I don't think Google would be willing to drop it.

**Comment by illiliti** [comment]
I'm totally OK with CLA. Just stop requiring Google account to sign it.

**Comment by ianlancetaylor** [comment]
Unfortunately there is no mechanism for signing the Google CLA without creating a Google account.  This is not under the control of the Go team.  Closing this issue as unfortunate.

**Comment by 3llena-arch** [comment]
>he/him
>california
>sorry gobros, we cuckin'
you cant make this shit up
