### ISSUE TITLE
x/pkgsite: viewing std at master is broken

### ISSUE THREAD

**Issue by mvdan** [golang/go#49398]
For instance, https://pkg.go.dev/bytes@master is a 404, and https://pkg.go.dev/reflect@master gives an empty package.

I'm fairly sure these used to work. The latter is even linked form https://tip.golang.org/doc/go1.18 under the "reflect" section.

If the changelog will be shown to users in this form, then this bug is a release blocker for 1.18, I think.

cc @golang/pkgsite @golang/release

**Comment by dmitshur** [comment]
Indeed. This is #49229.

**Comment by mvdan** [comment]
Ah, apologies, my search did not show those.

**Comment by dmitshur** [comment]
Not a problem!
