### ISSUE TITLE
[feature request] Please support setuid

### ISSUE THREAD

**Issue by yurivict** [golang/go#49404]
Currently Golang isn't capable of setuid and requests like this [FreeBSD bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=259054) can't be honored. See also [this](https://github.com/coredns/coredns/issues/4917) discussion about the same issue.

**Comment by ianlancetaylor** [comment]
Can you be specific as to what is missing?  Neither link explains it, at least not to me.

On both FreeBSD and Linux systems `syscall.Setuid` should work fine.  (On Linux it has worked since the Go 1.16 release, on FreeBSD it worked all along).

**Comment by yurivict** [comment]
Somebody claimed that setuid isn't possible from Golang, but they were apparently wrong.

Thank you for your help.
