### ISSUE TITLE
x/pkgsite: Cookie Heading missing

### ISSUE THREAD

**Issue by u0nel** [golang/go#49418]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/net/http#ConnState.String
 
### What is your user agent?
 

`Mozilla/5.0 (X11; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0`

Just updated Firefox and it's also not working with firefox 94
`Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0`
 
 
### Screenshot
 

 
![image](https://user-images.githubusercontent.com/46542757/140621659-af1e85b1-ae1c-4fc7-86a1-598638bcad1a.png)

 
 
### What did you do?
 

 I tried opening https://pkg.go.dev/net/http#Cookie in Firefox
 
 
### What did you expect to see?
 A heading
 
 
### What did you see instead?

No heading.

I checked in Chromium and it works there.

**Comment by ameowlia** [comment]
The header showed up for me with:
* **OS:** macOS Big Sur v11.6 
* **Browser**: firefox v84.0.1 and v91.0.2

**Comment by u0nel** [comment]
I just tried with firefox in safe mode, which worked, so a plugin causes the problem.
