### ISSUE TITLE
proxy.golang.org: document process for unpublishing compromised modules

### ISSUE THREAD

**Issue by rittneje** [golang/go#49417]
Given the recent security incident with the coa and rc node packages, I would like to request that the process for getting compromised module versions unpublished from proxy.golang.org be recorded in the [FAQ](https://proxy.golang.org/) to allow for a speedy resolution should an incident occur. In a situation like this, simply retracting the compromised version is insufficient.

Please note that I am NOT intending to report a compromised version of any Go module in this issue. I'm just looking for documentation.

**Comment by heschi** [comment]
Thanks for the idea. We've added the FAQ entry; it should be visible shortly.

cc @hyangah @katiehockman
