### ISSUE TITLE
go get not installing dependencies

### ISSUE THREAD

**Issue by B3ns44d** [golang/go#49426]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
No idea I'm still new to `Go`

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/b3ns44d/.cache/go-build"
GOENV="/home/b3ns44d/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/b3ns44d/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/b3ns44d/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3130919800=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
So I want to create a simple HTTP server with the `gorilla/mux` package I did `go get -u github.com/gorilla/mux` to install the package but nothing happened the package is not installed

### What did you expect to see?
no issues :)

### What did you see instead?
```
could not import mux (cannot find package "mux" in any of 
    /usr/local/go/src/mux (from $GOROOT)
    /home/b3ns44d/go/src/mux (from $GOPATH))
```

after run `go run main.go`

```
main.go:5:2: package mux is not in GOROOT (/usr/local/go/src/mux)
```

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
