### ISSUE TITLE
NO_ERROR; received from peer

### ISSUE THREAD

**Issue by penghuazhou** [golang/go#49434]
What version of Go are you using (`go version`)?
go version go1.15.14 linux/amd64

What operating system and processor architecture are you using (`go env`)?
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build836394113=/tmp/go-build -gno-record-gcc-switches"

What did you do?
when I post with 500 goroutine use http2，it have this error accidental.

What did you expect to see?
I expect to see post success. 

What did you see instead?
NO_ERROR; received from peer
<img width="825" alt="wecom-temp-5734b5afd416339a6e49efbfcc3b7ac9" src="https://user-images.githubusercontent.com/13001038/140686472-824d110a-f658-455b-a21a-32544fd11778.png">

**Comment by cagedmantis** [comment]
Go 1.15 is not longer being actively developed. If this issue occurs with version 1.16 and above, please fill out the issue template and could you provide an example of the code that produced the error, preferably as a [Go playground](https://play.golang.org/) link?

**Comment by ianlancetaylor** [comment]
Please always send plain text as plain text, not as an image.  Images hard to read and hard to cut and paste from.  Thanks.

**Comment by penghuazhou** [comment]
thanks
