### ISSUE TITLE
runtime: newosproc doesn't handle clone returning EAGAIN

### ISSUE THREAD

**Issue by asuffield** [golang/go#49438]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

I haven't tried, but inspection of the code says it will.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
</pre></details>

(With apologies for pruning)

### What did you do?

I don't have a reproduction case for this one - it's very sensitive to something I haven't pinned down yet - but I have uncovered the nature of the bug via inspection.

Running go programs on sufficiently loaded systems sometimes crashes with "runtime: failed to create new OS thread (have 2 already; errno=11)". The really interesting thing here is errno=11, which is EAGAIN. If you read the Linux manpage for fork/clone it will refer to system limits; I have verified that is not the case in my scenario. At this point I said to myself (more than once): fork/clone aren't restartable syscalls, surely they can't actually return EAGAIN. Then I started doubting myself and went looking.

It turns out that Linux can and does return EAGAIN in some circumstances which are entirely undocumented in the manpages. The key code path ends up here:

https://elixir.bootlin.com/linux/v5.15.1/source/kernel/fork.c#L1523

And starts out over here:

https://elixir.bootlin.com/linux/v5.15.1/source/fs/exec.c#L1581

Which eventually led me back to this thread:

https://lore.kernel.org/lkml/20090329005343.GA12139@redhat.com/

It appears Linux has been willing to return EAGAIN to fork/clone for over a decade now, which means this code needs to handle that case somehow:

https://github.com/golang/go/blob/a97c527ac491cc13f6778010a2a81c84642ea1ca/src/runtime/os_linux.go#L167-L173

It is super unfortunate that the rlimit scenario also returns EAGAIN, but I don't see any solution other than retrying a few times before panic - but maybe there's something I haven't fully understood here, I'll admit I haven't pieced together exactly what's happening. The only thing I'm fully confident of is: there is some way in which go processes can crash with an EAGAIN returned from clone() which isn't caused by rlimits.

**Comment by ianlancetaylor** [comment]
Note: for the cgo case we use a loop with an increasing delay to handle `pthread_create` returning `EAGAIN`; see #18146 and https://go.googlesource.com/go/+/refs/heads/master/src/runtime/cgo/gcc_libinit.c#91.  We could certainly do the same thing for the non-cgo case, which is what you are describing.  It would be nice to have a test case.

**Comment by myitcv** [comment]
@asuffield hello! Long time no see :)

Noting that I run into this occasionally (~once a month), in exactly the scenario of load that @asuffield reports (generally at machine startup).
