### ISSUE TITLE
internal/fmtsort: channel tests make specious assumptions about object ordering

### ISSUE THREAD

**Issue by randall77** [golang/go#49431]
On the longtest builders:
```
--- FAIL: TestCompare (0.00s)
    sort_test.go:78: chan int: compare(0xc000196000,0xc00001e1e0)=1; expect -1
    sort_test.go:78: chan int: compare(0xc000196000,0xc00001e240)=1; expect -1
    sort_test.go:78: chan int: compare(0xc00001e1e0,0xc000196000)=-1; expect 1
    sort_test.go:78: chan int: compare(0xc00001e240,0xc000196000)=-1; expect 1
--- FAIL: TestOrder (0.00s)
    sort_test.go:227: map[chan int]string: got "CHAN1:1 CHAN2:2 CHAN0:0", want "CHAN0:0 CHAN1:1 CHAN2:2"
FAIL
FAIL	internal/fmtsort	0.004s
```
I think this is happening because `chans[0]` is in pointer space higher than `chans[1]` and `chans[2]`. It seems that these tests expect channels to sort in the order they are allocated, which isn't necessarily true.

@robpike

**Comment by robpike** [comment]
Yes, it looks like that's what's happening. Not sure how to make the test robust without essentially duplicating the package's own logic, which is unfortunate. Ideas welcome.

**Comment by bcmills** [comment]
It seems to me that sorting dynamically-allocated pointers by pointer value is inherently nondeterministic, given Go's memory model: if the values are relocated during the test, they will end up out of order. (That is: this test, strictly speaking, requires #46787.)

The fact that the language provides no way to statically allocate channel values further complicates the matter (compare #28366).

I don't think that there is a way to write this test that is guaranteed by the language spec to be deterministic.

**Comment by randall77** [comment]
Reopening to make this issue about making this test more robust.

**Comment by rsc** [comment]
@randall77, you reopened this bug. What is it meant to track now? Use of a Pinner? 
It should be a long time before we have objects moving in the heap, and channels are pretty much always going to be in the heap (especially channels held in globals).

**Comment by randall77** [comment]
Yes, just to make the test (and the actual code, maybe?) less dependent on object addresses. I'm not entirely clear on how that would happen, exactly. Maybe there's nothing concrete to do here.

**Comment by bcmills** [comment]
@qiulaidongfeng: is this fixed as of https://go.dev/cl/528796, or is there more to do?

**Comment by randall77** [comment]
I'm going to close, I think this is done.
Maybe someday someone can figure out how to write this test that doesn't depend on pinning. But that doesn't need an issue.
