### ISSUE TITLE
net/http: TestClientCallsCloseOnlyOnce failures with "host has failed to respond" on Windows

### ISSUE THREAD

**Issue by bcmills** [golang/go#49454]
```
--- FAIL: TestClientCallsCloseOnlyOnce (21.04s)
    client_test.go:2063: dial tcp 127.0.0.1:51357: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
FAIL
FAIL	net/http	25.262s
```

`greplogs --dashboard -md -l -e '(?m)FAIL: TestClientCallsCloseOnlyOnce.*\n.*host has failed to respond'`

[2021-11-05T22:03:24-035963c/windows-arm64-10](https://build.golang.org/log/e61b43ef384ed136c41bb57df31b9f270ddd1bf1)
[2020-12-23T02:10:51-b0b0d98/windows-arm-zx2c4](https://build.golang.org/log/8eca3854d5b1f5f4e632f974205af3dc72f21760)

CC @neild

**Comment by neild** [comment]
cc @bufflig 

This test creates 50 HTTP client connections, in sequence, to the same server. The error seems to indicate that one of them failed. I don't know what might cause this, but the fact that the failure has happened once in a year and only on Windows makes this hard to diagnose; I suspect it's an issue on the builder, but I don't know what. Something applying a rate limit to connection attempts?

Given the rarity of the failure, this is probably not a priority.

**Comment by bufflig** [comment]
I wonder if the fact that it happens on both arm 32 and 64 bit is significant? I agree that it seems really hard to diagnose when it happens this rarely. I can attempt to get it to happen with brute force running on my parallels VM, but I can not leave any guarantees of success.

**Comment by bcmills** [comment]
If the cause isn't easy to spot, I suggest that we give it a while to look for more occurrences. (I agree with Damien that this doesn't seem worth prioritizing at the moment.)

**Comment by bcmills** [comment]
There have been a lot of `net/http` fixes since this issue was filed, and `watchflakes` will file a new issue should it recur. Closing as obsolete.
