### ISSUE TITLE
x/pkgsite: keyboard shortcuts don't work on some pages

### ISSUE THREAD

**Issue by lrewega** [golang/go#49455]
### What is the URL of the page with the issue?
https://pkg.go.dev/github.com/Shopify/sarama
 
 
### What is your user agent?
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36 

 
 
 
### Screenshot
n/a

 
 
 
### What did you do?
- Pressed `f` to summon the "Jump To" modal.
- Pressed `?` or clicked the keyboard icon at the bottom of the page. 

 
 
 
### What did you expect to see?
- A "Jump To" modal. 
- A keyboard shortcuts modal.
 
### What did you see instead?
Nothing.

---

I'm guessing it has something to do with large pages/packages.

**Comment by carlmjohnson** [comment]
This is still broken for me with Safari.
