### ISSUE TITLE
cmd/6c: inefficient accesses to thread-local vars

### ISSUE THREAD

**Issue by dvyukov** [golang/go#4946]
<pre>parent: 15991:4cdeb75811c7 tip, linux/amd64

Code in runtime.entersyscall frequently accesses g and m thread-local vars. The
generated code is not particularly efficient:

         :                g-&gt;gcsp = g-&gt;sched.sp;                                                                                ▒
    5.17 :          416ca7:       mov    %fs:0xfffffffffffffff0,%rax                                                            ▒
    1.03 :          416cb0:       mov    %fs:0xfffffffffffffff0,%rcx                                                            ▒
    0.09 :          416cb9:       mov    0x20(%rcx),%rcx                                                                        ▒
    7.46 :          416cbd:       mov    %rcx,0x40(%rax)                                                                        ▒
         :                g-&gt;gcstack = g-&gt;stackbase;                                                                            ◆
    0.45 :          416cc1:       mov    %fs:0xfffffffffffffff0,%rax                                                            ▒
    0.36 :          416cca:       mov    %fs:0xfffffffffffffff0,%rcx                                                            ▒
    0.00 :          416cd3:       mov    0x8(%rcx),%rcx                                                                         ▒
    6.96 :          416cd7:       mov    %rcx,0x38(%rax)                                                                        ▒
         :                g-&gt;gcguard = g-&gt;stackguard;                                                                           ▒
    0.40 :          416cdb:       mov    %fs:0xfffffffffffffff0,%rax                                                            ▒
    0.45 :          416ce4:       mov    %fs:0xfffffffffffffff0,%rcx                                                            ▒
    0.00 :          416ced:       mov    (%rcx),%rcx                                                                            ▒
    6.02 :          416cf0:       mov    %rcx,0x48(%rax)                                                                        ▒
         :                g-&gt;status = Gsyscall;                                                                                 ▒
    0.18 :          416cf4:       mov    %fs:0xfffffffffffffff0,%rax                                                            ▒
    0.49 :          416cfd:       movw   $0x3,0x70(%rax)                                                                        ▒
             
If I manually cache g and m in local vars, the code becomes more compact:

         :                gp = g;                                                                                              ▒
    0.00 :          4173b6:       mov    %fs:0xfffffffffffffff0,%rax   
         :                gp-&gt;gcsp = gp-&gt;sched.sp;                                                                             ▒
    0.26 :          4173db:       mov    0x20(%rdx),%rcx                                                                       ▒
    6.55 :          4173df:       mov    %rcx,0x40(%rdx)                                                                       ▒
         :                gp-&gt;gcstack = gp-&gt;stackbase;                                                                         ▒
    1.12 :          4173e3:       mov    0x8(%rdx),%rcx                                                                        ▒
    0.00 :          4173e7:       mov    %rcx,0x38(%rdx)                                                                       ▒
         :                gp-&gt;gcguard = gp-&gt;stackguard;                                                                        ▒
    0.52 :          4173eb:       mov    (%rdx),%rcx                                                                           ▒
    5.28 :          4173ee:       mov    %rcx,0x48(%rdx)                                                                       ▒
         :                gp-&gt;status = Gsyscall;                                                                               ▒
    0.41 :          4173f2:       movw   $0x3,0x70(%rdx)     

and BenchmarkSyscall execution time drops from 30.2 to 26.2 ns/op.

Can we improve code generation for the thread-local vars?</pre>

**Comment by rsc** [comment]
6c is gone!
