### ISSUE TITLE
x/tools/go/analysis/internal/facts: importMap incorrectly handling *types.Named

### ISSUE THREAD

**Issue by timothy-king** [golang/go#49469]
go/analysis/internal/facts `importMap` appears to not be handling *types.Named correctly.

Below are 3 examples showing the files for packages `a`, `b`, and `c`. `importMap` for `c` should include `a` in all of these examples.

Example 1:
```
files: map[string]string{
	"a/a.go":  `package a; type A int; type T int`,
	"a2/a.go": `package a2; type A2 int; type Unneeded int`,
	"b/b.go":  `package b; import ("a"; "a2"); type B chan a2.A2; type F func() a.T`,
	"c/c.go":  `package c; import "b"; type C []b.B`,
},
```
This corresponds to a long standing [TODO](https://cs.opensource.google/go/x/tools/+/refs/tags/v0.1.7:go/analysis/internal/facts/facts_test.go;l=85) in the unit tests:
```
//{"b.F(nil)()", "myFact(a.T)"}, // no fact; TODO(adonovan): investigate
```
This example is a bit complex so it is broken down into 2 simpler cases.

Example 2:
```
files: map[string]string{
	"a/a.go": `package a; type a int; type T *a`,
	"b/b.go": `package b; import "a"; type B a.T`,
	"c/c.go": `package c; import "b"; type C b.B; var q = *C(nil)`,
},
```
To resolve the type of `c.q`, we need `a` to be included. To include `a` we need to step into the `Underlying()` of `b.B`.

Example 3:
```
files: map[string]string{
	"a/a.go": `package a; type T int`,
	"b/b.go": `package b; import "a"; type B struct{}; func (_ B) M() a.T { return 0 }`,
	"c/c.go": `package c; import "b"; var C b.B`,
},
```
To resolve "b.B" in the context of "C" we need to add the methods of `b.B`. This currently does not happen as `type B struct{}` is first visited by `addObj()` which marks the types.Object as visited. This then visits the *types.Named for `b.B` using `addType()`. The `if addObj(T.Obj())` check [here](https://cs.opensource.google/go/x/tools/+/refs/tags/v0.1.7:go/analysis/internal/facts/imports.go;l=44) then returns false and the methods are never visited. A fix is to track whether the type has been fully visited independently of `T.Obj()` so the order they happen in does not block adding the method.

Addressing both Example 3 and Example 2 fix Example 1. Examples 2 and 3 can be fixed independently.

Not sure which milestone to attach this to. The bugs are from 2017 so it is not obvious this needs to be rushed. 
A fix may have a noticeable impact on Analyzers that use Facts. That can then impact findings. Unclear what tests should happen before this is submitted. Before the 1.18 release seems reasonable to me.

**Comment by dmitshur** [comment]
Closing as fixed by [CL 362414](https://go.dev/cl/362414).

(Not sure why it didn't get closed automatically via the "Fixes" line in https://github.com/golang/tools/commit/8111118043894a9c0eab886fc370ca123dcf48f1. Hopefully it was just a one-off problem, possibly related to a [GitHub incident](https://www.githubstatus.com/incidents/ll8gxx3svld7) earlier that day.)
