### ISSUE TITLE
Go routine cascading context canceled

### ISSUE THREAD

**Issue by sofyan-ahmad** [golang/go#49468]
### What version of Go are you using (`go version`)?

<pre>
$ go version
Docker golang:1.16-alpine
</pre>

### Does this issue reproduce with the latest release?
Not really sure, I didn't have a chance to test it on the latest release

### What operating system and processor architecture are you using (`go env`)?
<details><summary>Dockerimage golang:1.16-alpine, running on top of Kubernetes on GCP
</summary</details>

### What did you do?

- I implemented go routing by calling a function with `go someFunction()`,
- Inside the function, I created new context background `context.Background()` without cancel
- Tested on my local machine MacBook Pro, everything was perfectly normal
- Deployed the code into Kubernetes, at first everything was running smoothly
- Suddenly got the error `Context Canceled` everywhere 
- Tried to fix it by implementing context with cancel, but the issue happened again
- The function was simple, it was calling external graphql client and calling Postgres database using pgx

### What did you expect to see?
Context should not be canceled, and routine should not leaking

### What did you see instead?
Cascading error `context canceled` everywhere

**Comment by ianlancetaylor** [comment]
For a problem like this we are going to need to see your code.

**Comment by bcmills** [comment]
#26356 may be relevant.
