### ISSUE TITLE
x/tools/gopls: context deadline exceeded with windows 10 wsl2

### ISSUE THREAD

**Issue by wu0407** [golang/go#49475]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.3 linux/amd64
gopls: v0.7.3
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go version go1.17.3 linux/amd64
xiaoqing@DESKTOP-NTTMOHE:~$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xiaoqing/.cache/go-build"
GOENV="/home/xiaoqing/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/xiaoqing/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xiaoqing/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2970027064=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

 Open kubernetes code in use vscode with wsl mode.
go extention report "go.mod context deadline exceeded" 
I see gopls use many cpu a few time, then low cpu and memory not increase.

### What did you expect to see?
no probelm

### What did you see instead?

###gopls trace log on local vscode
```
[Trace - 19:20:32.674 PM] Received notification 'window/logMessage'.
Params: {"type":1,"message":"2021/11/09 19:20:32 errors loading workspace: context deadline exceeded\n\tsnapshot=0\n\tdirectory=file:///mnt/d/git/kubernetes\n"}


[Error - 7:20:32 PM] 2021/11/09 19:20:32 errors loading workspace: context deadline exceeded
	snapshot=0
	directory=file:///mnt/d/git/kubernetes

[Trace - 19:20:32.675 PM] Sending response 'window/workDoneProgress/create - (5)' in 1ms.
Result: 


[Trace - 19:20:32.675 PM] Received notification '$/progress'.
Params: {"token":"8674665223082153551","value":{"kind":"begin","title":"Error loading workspace","message":"context deadline exceeded"}}


[Trace - 19:20:32.704 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///mnt/d/git/kubernetes/go.mod","diagnostics":[{"range":{"start":{"line":4,"character":0},"end":{"line":4,"character":24}},"severity":1,"source":"go list","message":"context deadline exceeded"}]}
```
###full log:
[gopls-wsl-context-timeout.txt](https://github.com/golang/go/files/7505071/gopls-wsl-context-timeout.txt)

**Comment by bcmills** [comment]
IIRC the `/mnt` filesystem on WSL2 is extremely slow. Perhaps `gopls` just needs to set a longer deadline?

**Comment by wu0407** [comment]
> IIRC the `/mnt` filesystem on WSL2 is extremely slow. Perhaps `gopls` just needs to set a longer deadline?

Yes, I can't find any options with gopls timeout.

**Comment by hyangah** [comment]
I am afraid timeout longer than 10min is not ideal - according to the trace, the loading failed after more than 10min. 

```
[Trace - 18:40:40.585 PM] Sending response 'window/workDoneProgress/create - (1)' in 5ms.
Result: 


[Trace - 18:40:40.587 PM] Received notification '$/progress'.
Params: {"token":"5577006791947779410","value":{"kind":"begin","title":"Setting up workspace","message":"Loading packages..."}}

[Error - 6:52:08 PM] 2021/11/09 18:52:08 initial workspace load failed: context deadline exceeded
```

I think for wsl, VS Code recommends [Visual Studio Code Remote - WSL](https://code.visualstudio.com/docs/remote/wsl) extension than starting with the `/mnt` filesystem. I see loading k8s workspace take ~22secs on my windows running on amd ryzen - still long time but not like more than 10min.

**Comment by hyangah** [comment]
@wu0407 Can you please check if you have the same issue when you use the WSL extension?

**Comment by wu0407** [comment]
same result with wsl extention start wsl and manual start wsl. @hyangah

**Comment by findleyr** [comment]
IIRC gopls has to read something like 25K files and load 3-6GB of memory for Kubernetes (depending on if you're using staticcheck). This takes 30-45s on my (rather powerful) linux desktop. I am not at all surprised to hear that gopls is unusable at such scale on WSL2.

We are considering a project to allow gopls to avoid loading the entire workspace for projects like Kubernetes, hopefully for early 2022. In the meantime, gopls will not work well for this use case, sorry.

I'm going to leave this in the backlog, so that we may find it while working on performance (and hopefully verify that it is improved).

**Comment by hg-hg** [comment]
Hi @findleyr, I'm facing the same issue with the following env:

```
go version go1.20.12 linux/amd64
golang.org/x/tools/gopls v0.14.2
```

I'm also using the `gopackagesdriver` imported from `rules_go v0.42.0`. Is this a known issue that has been fixed?
