### ISSUE TITLE
Goroutines in WebAssembly

### ISSUE THREAD

**Issue by KentAVP** [golang/go#49473]
I see code of proc.go https://github.com/golang/go/blob/c6a0b6f2de9a778b03a29c656531617a606761f0/src/runtime/proc.go#L169

and see following comment:

`no threads on wasm yet, so no sysmon`

is this means that there is no support of go routines in case we build for WebAssembly?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
