### ISSUE TITLE
x/sys/unix: mkmerge_test.go is not tested on the Go builders

### ISSUE THREAD

**Issue by bcmills** [golang/go#49484]
`unix/mkmerge.go` was updated in [CL 296889](https://golang.org/cl/296889) to add `//go:build` lines (#41184).

That caused the test in `unix/mkmerge_test.go` to start failing, but nobody noticed because `mkmerge_test.go` itself has the `ignore` constraint — it must be run explicitly to run it at all, and the Go builders do not know to do that.

Probably the simplest solution is to factor `mkmerge.go` out into a proper package (perhaps `x/sys/unix/internal/mkmerge`?), in which case its test will be run automatically by the builders.

Another option would be to add a `Test` function in `x/sys/unix` itself that runs `go test mkmerge.go mkmerge_test.go` as a subprocess.

CC @tklauser @jupj @ianlancetaylor

**Comment by jupj** [comment]
Factoring `mkmerge.go` out into a proper package sounds like a good and simple solution, testing is transparent in that way IMHO.

Do we need to verify that the Go builders catch the failing tests in `mkmerge_test.go`, before fixing the tests?

In this case the process could be:
1. First patch set: factor `mkmerge.go` and `mkmerge_test.go` into `x/sys/unix/internal/mkmerge`
2. See that the Go builders fail for `mkmerge_test.go`
3. Follow-up patch set (or separate CL?): fix the tests in `mkmerge_test.go` and see that Go builders do not fail anymore.

**Comment by bcmills** [comment]
I already fixed the failing test, so we don't need to observe it on the builder. Just factoring out a package ought to suffice.

If you want to see it in action, I would suggest publishing a patchset to Gerrit with an intentional regression in the test, running TryBots on that Gerrit change to confirm that the regression is caught, and then publishing a second patchset that removes the regression.

**Comment by jupj** [comment]
I did an attempt at package `x/sys/unix/internal/merge` in [CL 363334](https://golang.org/cl/363334). When running in Linux, `mkall.sh` prints the following error for mkmerge:

```
----- GENERATING: merging generated files -----
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
could not merge zerrors files: exit status 1
***** FAILURE:    merging generated files *****
```

The Docker-based build system for Linux uses a volume mounted at `x/sys/unix`, which doesn't include `x/sys/go.mod`, hence  package `internal/mkmerge` is not part of any module when used within the Docker-based build system.

Thoughts on how to address this?

**Comment by bcmills** [comment]
Oh, neato! We should probably change the build system to mount `x/sys` instead of `x/sys/unix`, since `x/sys/go.mod` is what declares the version of the language against which the package is written.

**Comment by jupj** [comment]
Thanks for the input!

I sent [CL 363594](https://golang.org/cl/363594) to change the build system to mount `x/sys`. Package `internal/mkmerge` seems to work as intended now.
