### ISSUE TITLE
cmd/compile: parenthesized constraint causes problems

### ISSUE THREAD

**Issue by griesemer** [golang/go#49485]
```Go
type T[P (any)] struct{}
```
is not recognized correctly:
```
x.go:3:8: undefined: P
```

**Comment by griesemer** [comment]
It turns out that we cannot make this work as expected (i.e., to be interpreted as a type parameter followed by a parameterized constraint):

In general, an expression of the form `T(x)` may be a conversion or a function call, both of which may potentially result in a constant result (there are constant conversions, and some built-in functions like `len` can produce constant results). Thus, when we see `[T (x)]` we cannot assume a type parameter `T` followed by a parameterized constraint `x` without type checking; it could potentially be an array length. Here's a valid [example](https://play.golang.org/p/bakWjFVdfyz):
```Go
package main

type A [len(*p)]struct{} // array declaration, not a parameterized type

var p *[10]byte

func main() {
	println(len(A{}))
}
```

**Comment by griesemer** [comment]
Closing as working as expected.

**Comment by go101** [comment]
Another intended case:

```Go
package main

type A [len (S)]struct{} // array declaration, not a parameterized type

const S = "Go"

func main() {
	println(len(A{})) // 2
}
```
