### ISSUE TITLE
x/pkgsite: package removal request for ministryofjustice/cloud-platform-environments/pkg/x

### ISSUE THREAD

**Issue by jasonBirchall** [golang/go#49487]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/ministryofjustice/cloud-platform-environments/pkg/ingress
https://pkg.go.dev/github.com/ministryofjustice/cloud-platform-environments/pkg/authenticate
https://pkg.go.dev/github.com/ministryofjustice/cloud-platform-environments/pkg/namespace
 
 
### Are you the owner of this package?

Yes

 
### What is the reason that you could not retract this package instead?

I completely messed up exported packages by creating submodules inside of each package. This has been rectified and now only have one module https://pkg.go.dev/github.com/ministryofjustice/cloud-platform-environments (that doesn't show up on pkg.go.dev when searching) because of my previous mistake. I cannot add the retraction because the submodules no longer exist.

Two of the modules in that list are imported by one another.

I would like the current live module to exist:
https://github.com/ministryofjustice/cloud-platform-environments/blob/main/go.mod

Sorry again. I recognise my error and have learnt from my mistake.

**Comment by jamalc** [comment]
We cannot remove the submodules of github.com/ministryofjustice/cloud-platform-environments without also removing the packages with the same path. You'll have to recreate and retract the modules.
