### ISSUE TITLE
syntax: parser doesn't recognize valid type parameter list

### ISSUE THREAD

**Issue by griesemer** [golang/go#49482]
There is a (known) ambiguity for type parameter lists. For
```Go
type T[P *int] struct{}
```
the parser cannot tell if this is a generic type declaration or an array type declaration with length `P*int`. In general, people will write `~*int` and there is the work-around `interface{*int}`; one just has to be aware of it.

But the parser also assumes that
```Go
type T[P *int, Q any] struct{}
```
is starting an array type declaration, yet this is clearly a valid type parameter list.

Should be fixed for 1.18 but is not a release blocker as there are work-arounds.

cc: @findleyr @ianlancetaylor

**Comment by griesemer** [comment]
Another work-around for the single type-parameter case would be a trailing comma, as in
```Go
type T[P *int,] struct{}
```
because type parameter lists (like all parameter lists) permit a trailing comma, while array type declarations don't.

**Comment by ianlancetaylor** [comment]
I assume that this also works:

```Go
type T[P (*int)] struct{}
```

**Comment by griesemer** [comment]
It should but currently doesn't, it appears. Filed a separate issue #49485.

**Comment by griesemer** [comment]
It turns out that [using parentheses](https://github.com/golang/go/issues/49482#issuecomment-964421066) [does not work in general](https://github.com/golang/go/issues/49485#issuecomment-964811684).

**Comment by findleyr** [comment]
Reopening as while auditing our port sheet I realized this fix did not get ported to go/parser. I have mailed the port in https://go.dev/cl/385575. Tentatively marking as a release blocker: the original bug may not have a release blocker, but it seems like a release blocker that the compiler accepts these expressions and go/parser _does not_, even if they will be uncommon in practice.

**Comment by findleyr** [comment]
CC @golang/release @mdempsky 

As mentioned above, I think this may be a release blocker. Since the CL is mailed, I have added the release-blocker label in hopes that it can get merged before the RC1. Please reach out to me if any concerns.

**Comment by findleyr** [comment]
While working on the port, I realized that there are valid cases that both parsers can't currently handle. For example:

```
type _[P *struct{}|int] struct{}  // example 1
type _[P *struct{}|~int] struct{}  // example 2
```

Example 1 is parsed as an array type, though it can be unambiguously parsed as a generic type declaration. Example 2 is a parser error.

I have a fix for both cases, but since this is not trivial I think it must wait until Go 1.19. I believe the CL above makes go/parser bug-compatible with the compiler.

**Comment by findleyr** [comment]
Thanks to @mdempsky's help, we landed the fix to make `go/parser` and `go/printer` consistent with the compiler. Moved this to 1.19, when we can consider further improvements to our parsing of ambiguous type parameter lists.
