### ISSUE TITLE
x/build: create windows-386-2012 builder

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#49490]
The Go1.18 release will require a supported version of Windows to be released on. While Windows Server 2012 does not have native i386 support, Microsoft Windows-32-on-Windows-64 (WOW64) allows you to run 32 bit software on an x64 system.

@golang/release

**Comment by zx2c4** [comment]
I think that CL went a bit too far. Adding a newer builder is good. But removing 2008 from trybots is maybe less good. That will surely bitrot Windows 7 support after some time.
