### ISSUE TITLE
x/pkgsite: Incorrect information displayed about Trim function. [A typo]

### ISSUE THREAD

**Issue by hugekontrast** [golang/go#49494]
### What is the URL of the page with the issue?
URL :  https://pkg.go.dev/strings#Trim
 
 
### What is your user agent?
 

 Mozilla/5.0 (Linux; Android 11; SM-M315F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Mobile Safari/537.36
 
 
### Screenshot
 
![Screenshot_20211110-135416_Chrome](https://user-images.githubusercontent.com/44055846/141077033-2ca23e07-1467-4c23-a98e-9d2899bb991a.jpg)

 
 
 
### What did you do?
 The trim function outputs string but in the text about it it's mention that it outputs slice of the string.

**Comment by seankhliao** [comment]
the documentation is correct it slices to return part of the string

**Comment by hugekontrast** [comment]
![Screenshot_20211110-135416_Chrome](https://user-images.githubusercontent.com/44055846/141505377-26f23a86-8c66-465b-9ecb-347ee6f1b776.jpg)

Listen returning of " a slice of the string" seems to be this  []string but instead the function is returning simple "string" as in its function signature. I think I'm looking at a grammatical mistake.
If it were to return a slice of a string then it would be
    func Trim(s, cutset string) []string
But the syntax is
     func Trim(s, cutset string) string

What do you think?

**Comment by seankhliao** [comment]
`[]string` would be "slice of strings"
what trim does is something like `s := "hello world"`, s[1:5]`, which is a slice of **the** string
