### ISSUE TITLE
time.Parse by 2020 has error parsing time "20060102 15:04:05" as "20200102 15:04:05": cannot parse "2 15:04:05" as "02"

### ISSUE THREAD

**Issue by WQMLSM** [golang/go#49498]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.16.4 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
