### ISSUE TITLE
x/pkgsite: documentation not displayed for HPND-sell-variant license

### ISSUE THREAD

**Issue by xyproto** [golang/go#49504]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/xyproto/wallutils?utm_source=godoc
 
### What is your user agent?
 
Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0
  
### Screenshot
 
![image](https://user-images.githubusercontent.com/52813/141163851-22e921fe-65c8-4fcf-8148-a3349641c58a.png)
 
### What did you do?

Tried to visit and browse the documentation:

http://godoc.org/github.com/xyproto/wallutils 
 
 ### What did you expect to see?
 
The package documentation.
 
### What did you see instead?

> Documentation not displayed due to license restrictions.
> See our license policy.

Wallutils is licensed under the MIT license, but the license file contains two of them, separated by `--`, because the original MIT license has slightly different wording.

**Comment by D1CED** [comment]
The license demands that

> [...] both that copyright notice and this permission notice appear in supporting documentation [...]

which pkg.go.dev clearly does not do. So the choice of not displaying the documentation is justified.

**Comment by xyproto** [comment]
I see. Thanks for the clarification!

**Comment by xyproto** [comment]
After moving the license for wayinfo.h from the `LICENSE` file into the source file at `include/wayinfo.h`, thus having just one license in the `LICENSE` file, the documentation for the package is generated and displayed correctly at `pkg.go.dev`.

I also changed the license from MIT to BSD-3 for the files that are not in `include/wayinfo.h`.

Moving license text around in the project made `pkg.go.dev` generate the API documentation. Is this is expected behavior, or an issue with the documentation generator?

**Comment by D1CED** [comment]
Currently go.dev uses github.com/google/licensecheck to detect a projects license which just has a list of files it goes over. It is a simple tool that does not traverse all files and neither does it look for source code comments that may be a license texts.

Here is the current official policy of go.dev along with a list of all the files that are consulted: https://pkg.go.dev/license-policy

**Comment by xyproto** [comment]
Using a simple license checker tool instead of a more advanced one is a bug in the pkg.go.dev website, then.

**Comment by xyproto** [comment]
Here is the `wallutils` commit that was the latest commit on `main` when this issue was first created: be7e0a39ddba14d7f04f2bf2ef22e739a41f54ab

**Comment by seankhliao** [comment]
the license checker correctly identified it as both HPND-sell-variant and MIT
the issue should be that HPND-sell-variant hasn't been approved

**Comment by xyproto** [comment]
Also, the HPND-sell-variant license only applies to the C header file `wayinfo.h`, that is not used when generating the documentation.

**Comment by rsc** [comment]
Looks like it is working now? If you put HPND-sell-variant in your LICENSE file, then pkgsite (and some people) will assume it applies to the whole repo. But it looks like you've taken it out, which will make sense to both pkgsite and people. So I believe this can be closed.

**Comment by xyproto** [comment]
Yes. Thanks for looking into this! I appreciate the automatic generation of documentation at pkg.go.dev.
