### ISSUE TITLE
go/build: embed reader does not handle a rune literal containing a doublequote character

### ISSUE THREAD

**Issue by kenshaw** [golang/go#49514]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.3 linux/amd64
</pre>

Also checked on a macOS and Windows VM, and had the same issue.

### Does this issue reproduce with the latest release?

Yes. Additionally, this was checked on go1.17.3 on a macOS and Windows VM and generated the same error.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ken/.cache/go-build"
GOENV="/home/ken/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ken/src/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ken/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1579404788=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Attempt to build / compile a `go:embed` statement after a rune declaration of `'"'`:

```go
package y

import (
	_ "embed"
)

var x = '"'

//go:embed a.txt
var afile []byte
```

### What did you expect to see?

No error.

### What did you see instead?

<pre>
ken@ken-desktop:~/y$ go build
# y
./y.go:9:3: invalid go:embed: build system did not supply embed configuration
</pre>

It's worth noting that this compiles without issue:

```go
package y

import (
	_ "embed"
)

var x = 'a'

//go:embed a.txt
var afile []byte
```

This also compiles without issue:

```go
package y

import (
	_ "embed"
)

//go:embed a.txt
var afile []byte

var x = '"'
```

**Comment by ianlancetaylor** [comment]
Nice example.  I'm pretty sure it's a bug in the go/build package when it looks for go:embed comments.
