### ISSUE TITLE
main.main: relocation target mypkg/pkg.Test[go.shape.int_0] not defined

### ISSUE THREAD

**Issue by zllangct** [golang/go#49524]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-d76b1ac3e1 Thu Nov 11 13:58:28 2021 +0000 darwin/amd64
</pre>
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/....../Library/Caches/go-build"
GOENV="/....../Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/......../go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/......../go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/......./sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/......./sdk/gotip/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="devel go1.18-d76b1ac3e1 Thu Nov 11 13:58:28 2021 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="............"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8s/qvy8nhvd0b932fq8lzb116j80000gn/T/go-build262027237=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
![image](https://user-images.githubusercontent.com/8629238/141329496-bd2b2da8-6cc4-4d91-8cb5-f26bb647090f.png)

pkg.go:
<pre>
package pkg

func Test[T int](in int) {}

</pre>

go.mod:

<pre>
module mypkg

go 1.18
</pre>

main.go:
<pre>
package main

import (
	"mypkg/pkg"
)

func main() {
	pkg.Test[int](1)
}
</pre>

### What did you see instead?
<pre>
# command-line-arguments
main.main: relocation target mypkg/pkg.Test[go.shape.int_0] not defined
</pre>

**Comment by randall77** [comment]
Something weird going on with completely empty bodies. Should be easy to fix.
