### ISSUE TITLE
x/tools/cmd/godoc: link "package foo" and "foo package" in text when "foo" exists

### ISSUE THREAD

**Issue by adg** [golang/go#4953]
<pre>It would be nice if godoc could automatically link text that refers to extant packages.</pre>

**Comment by Kegsay** [comment]
I think this *specific* feature request is "in the spirit of" the simple GoDoc style requirements in the same way that `http://` links are. They are regular comments that make sense on their own.

My use case is to be able to have well-documented package overviews which then link off to sub-packages for further reading. There is a concern that this could feature-creep (e.g. linking to a *specific definition* in a given package) but the simple case of linking to a package only seems pretty uncontroversial to me.

**Comment by seankhliao** [comment]
documentation links are available for modern doc systems https://go.dev/doc/comment#links
