### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by arunkumar183** [golang/go#49540]
### What did you do?
 
client1, err := goftp.DialConfig(config, machines.Machines[macindex].IpAddress)
above global pointer client1 wasn't accessible at both if...else statement   
 
 
 
### What did you expect to see?
we expect the global pointer client1 to be available at all places with in a go file.

 
 
 
### What did you see instead?
The global pointer vlient1 was only accessible on else part of the code and not on if part.
logic of program - create connection n if part, in the next loop iteration in the else part use that client1 to read remote dir contents.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
