### ISSUE TITLE
pkg.go.dev is down temporarily

### ISSUE THREAD

**Issue by jba** [golang/go#49549]
pkg.go.dev will be unavailable for up to an hour for planned downtime. In the meantime, use https://beta.pkg.go.dev.

**Comment by jba** [comment]
It's back up.

**Comment by n8jhj** [comment]
It seems to be down again, along with https://beta.pkg.go.dev.

**Comment by jba** [comment]
Looking into it. Try https://prod-frontend-mkqtu5uvoa-uc.a.run.app.

**Comment by changkun** [comment]
https://dev.golang.org/ and friends are also down.

**Comment by jba** [comment]
This is part of a larger outage, not pkgsite-specific. We'll post here as we learn more.

**Comment by n8jhj** [comment]
Looks like all these sites are back now. Thank you!

**Comment by jba** [comment]
Yes.
