### ISSUE TITLE
Cross compilation cgo project from Mac x86 for M1

### ISSUE THREAD

**Issue by GJoshi27** [golang/go#49545]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.9 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Not sure haven't tried go1.17

### What operating system and processor architecture are you using (`go env`)?

$ go env

GOARCH=arm64
GOOS=darwin
 'GOROOT': '/Users/joshiga/ws/dev/main/bora/build/package/COMPONENTS/cayman_go/sb-51450161/macosx-catalina/apple_mac64', 'GODEBUG': 'cgocheck=2', 'GOARCH': 'amd64', 'CGO_ENABLED': '1', ''GO111MODULE': 'off'

### What did you do?

I am trying to cross compile go app which is written in C, Objective-C, and Go.
It works fine on Mac x86, and I am trying to use the cross-compile it for M1.
CC version:
joshiga@joshiga-a01 bin % /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang --version
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/

CXX version:
joshiga@joshiga-a01 bin % /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ --version
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/

### What did you expect to see?
I was expecting it to successfully crosscompile and create a binary for ARM. Please
note for x86 Mac it works fine.
joshiga@joshiga-a01 bin % uname -a
Darwin joshiga-a01.vmware.com 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64

### What did you see instead?
go/pkg/tool/darwin_amd64/link: running /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed: exit status 1
Undefined symbols for architecture arm64:
  "___tsan_acquire", referenced from:
      _runtime.raceacquireg in go.o
      _runtime.raceacquirectx in go.o
  "___tsan_finalizer_goroutine", referenced from:
      _runtime.runfinq in go.o
  "___tsan_fini", referenced from:
      _runtime.racefini in go.o
  "___tsan_free", referenced from:
      _runtime.(*mspan).sweep in go.o
  "___tsan_func_enter", referenced from:
      _racefuncenter in go.o
  "___tsan_func_exit", referenced from:
      _runtime.racefuncexit in go.o
  "___tsan_go_atomic32_compare_exchange", referenced from:
      _sync/atomic.CompareAndSwapInt32 in go.o
  "___tsan_go_atomic32_fetch_add", referenced from:
      _sync/atomic.AddInt32 in go.o
  "___tsan_go_atomic32_load", referenced from:
      _sync/atomic.LoadInt32 in go.o
  "___tsan_go_atomic32_store", referenced from:
      _sync/atomic.StoreInt32 in go.o
  "___tsan_go_atomic64_compare_exchange", referenced from:
      _sync/atomic.CompareAndSwapInt64 in go.o
  "___tsan_go_atomic64_fetch_add", referenced from:
      _sync/atomic.AddInt64 in go.o
  "___tsan_go_atomic64_load", referenced from:
      _sync/atomic.LoadInt64 in go.o
  "___tsan_go_atomic64_store", referenced from:
      _sync/atomic.StoreInt64 in go.o
  "___tsan_go_end", referenced from:
      _runtime.goexit1 in go.o
      _runtime.(*p).destroy in go.o
  "___tsan_go_ignore_sync_begin", referenced from:
      _runtime.RaceDisable in go.o
      _racecallatomic in go.o
  "___tsan_go_ignore_sync_end", referenced from:
      _runtime.RaceEnable in go.o
      _racecallatomic in go.o
  "___tsan_go_start", referenced from:
      _runtime.racegostart in go.o
  "___tsan_init", referenced from:
      _runtime.raceinit in go.o
  "___tsan_malloc", referenced from:
      _runtime.mallocgc in go.o
      _runtime.gfget in go.o
      _runtime.stackalloc in go.o
  "___tsan_map_shadow", referenced from:
      _runtime.raceinit in go.o
      _runtime.racemapshadow in go.o
  "___tsan_proc_create", referenced from:
      _runtime.(*p).init in go.o
  "___tsan_proc_destroy", referenced from:
      _runtime.(*p).destroy in go.o
  "___tsan_read", referenced from:
      _runtime.raceread in go.o
  "___tsan_read_pc", referenced from:
      _runtime.racereadpc in go.o
  "___tsan_read_range", referenced from:
      _runtime.racereadrange in go.o
      _runtime.racereadrangepc1 in go.o
  "___tsan_release", referenced from:
      _runtime.racereleaseg in go.o
  "___tsan_release_acquire", referenced from:
      _runtime.racereleaseacquireg in go.o
  "___tsan_release_merge", referenced from:
      _runtime.racereleasemergeg in go.o
  "___tsan_write", referenced from:
      _runtime.racewrite in go.o
  "___tsan_write_pc", referenced from:
      _runtime.racewritepc in go.o
  "___tsan_write_range", referenced from:
      _runtime.racewriterange in go.o
      _runtime.racewriterangepc1 in go.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
