### ISSUE TITLE
runtime: gc pause bursts after upgrading from 1.16 to 1.17

### ISSUE THREAD

**Issue by dop251** [golang/go#49542]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dop/.cache/go-build"
GOENV="/home/dop/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dop/pkg/mod"
GOOS="linux"
GOPATH="/home/dop/projects"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1526968537=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

After upgrading our production servers with a version built with go 1.17.2 we saw a radically different GC pause profile (comparing to go 1.16.6):

![image](https://user-images.githubusercontent.com/995021/141448111-9eff9e3f-167a-4ef6-b8b7-8e22aa9db7c7.png)

What's plotted here is a change in PauseTotalNs measured every minute. The marker corresponds to the time of the rollout. Note that it did not start straight away, only when the load kicked in in the morning.

Zooming in showed there are "bursts" among otherwise normal sub-millisecond runs:

![image](https://user-images.githubusercontent.com/995021/141448605-73959235-0c35-43b2-a873-f1bb757ebadb.png)

To confirm this is a regression we did a build of the same code using go 1.16.6 and deployed it to one of the nodes. Also, we restarted another node at the same time, but left it running with 1.17.2. Comparing the graphs for the two nodes shows identical profile, except for the bursts which only occur on the node running 1.17.2:

![image](https://user-images.githubusercontent.com/995021/141449109-b71b0e77-3976-4119-8fb3-2cf3b59d2d08.png)

(green represents 1.16, yellow -- 1.17).
 
Here is what it looks like in the trace (we've managed to get a couple of examples):

![image](https://user-images.githubusercontent.com/995021/141445065-d62c036f-7d0f-439f-a83f-ab518675cf08.png)

The root cause is not immediately obvious to me, but I suspect there is a rare race condition which sometimes prevents STW to complete. Note, there is one event recorded during STW. In the end stack trace it shows `runtime.selectgo:327`. However in another example there is also an event recorded shortly before the end of STW, but it just says "proc stop".

We haven't been able to create a reproducible case for it. It looks like this only happens when heap size grows to a few tens of GB and then the frequency (but not the size) of the bursts depends on the load.

If there is any additional info required please let me know. 

### What did you expect to see?

Normal, sub-millisecond GC pauses.

### What did you see instead?

Random bursts of up to 100ms.

**Comment by prattmic** [comment]
@dop251 in your trace this is a forced GC (`runtime.forcegchelper`). Does that apply to all of the examples you've captured in the execution tracer?

**Comment by dop251** [comment]
I have seen 3 examples and yes, it is `runtime.forcegchelper` in all of them.

**Comment by prattmic** [comment]
Thanks, one more question:

> However in another example there is also an event recorded shortly before the end of STW, but it just says "proc stop".

This in particular does sound like the potential problem you describe. Specifically STW has to get all Ps to stop, so each P should have a "proc stop" event before STW continues. (Note that a P may already be stopped, so "proc stop" could be before STW). If a P takes a long time to stop, then that would block everything else.

I'd love to look at the trace you've collected to see if this is the case and what else is going on, if you think that is something you can share.

**Comment by dop251** [comment]
Is there a way to share it privately?

**Comment by prattmic** [comment]
Sure, feel free to email me `mpratt AT google.com`.

**Comment by dop251** [comment]
Shared a Google Drive folder with you.

**Comment by zhouguangyuan0718** [comment]
Hi, @prattmic . I encountered a similar problem. Any update about this issue?

**Comment by mknyszek** [comment]
Hi @zhouguangyuan0718, please file a new issue with additional details (platform, how you measured pause times, which versions of Go you're running, etc.). I think this issue is unfortunately too stale to continue. I don't believe we were able to reproduce this at the time. Closing for now.
