### ISSUE TITLE
x/tools/gopls: don't run gofmt on generated files

### ISSUE THREAD

**Issue by gudvinr** [golang/go#49555]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.17.3 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.7.3
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.61.0 (x64)
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.29.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- gopkgs:	/home/gudvin/tools/go/path/bin/gopkgs: go1.17.1
	go-outline:	/home/gudvin/tools/go/path/bin/go-outline: go1.17.1
	gotests:	/home/gudvin/tools/go/path/bin/gotests: go1.17.1
	gomodifytags:	/home/gudvin/tools/go/path/bin/gomodifytags: go1.17.1
	impl:	/home/gudvin/tools/go/path/bin/impl: go1.17.1
	goplay:	not installed
	dlv:	/home/gudvin/tools/go/path/bin/dlv: go1.17.1
	dlv-dap:	/home/gudvin/tools/go/path/bin/dlv-dap: go1.17.1
	gopls:	/home/gudvin/tools/go/path/bin/gopls: go1.17.1
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```json
{
    "editor.formatOnPaste": false,
    "editor.formatOnSave": false,
    "go.toolsManagement.autoUpdate": true,
    "go.vetOnSave": "workspace",
    "go.lintOnSave": "workspace",
    "go.toolsGopath": "~/path/to/go/",
    "gopls": {
        "build.experimentalWorkspaceModule": false,
        "ui.documentation.linksInHover": false,
        "usePlaceholders": false,
        "analyses": {
            "composites": false,
            "shadow": true,
            "ST1000": false,
            "ST1003": false
        },
        "ui.diagnostic.staticcheck": true
    }
}
```

### Describe the bug

When save action is called with generated file open in editor it then become formatted.

Generated code has comment matched by this regex:  
`^// Code generated .* DO NOT EDIT\.$`

In fact, extension warns that file should not be edited. But then proceeds to edit it by itself.

### Steps to reproduce the behavior:
1. Open generated file
2. Press Ctr+S

**Comment by findleyr** [comment]
> Even if generated code is poorly formatted editor shouldn't violate "DO NOT EDIT" rule without explicit command from user. It could mess up git diff very badly, for example. And you can't do anything to prevent that except by disabling formatting for every go file.

I don't disagree, but @hyangah thinking about this a bit more I'm wondering if gopls is the correct layer to solve this problem.  It's a bit strange for vscode-go to ask gopls to format a file, only to have gopls refuse.  With that said, it is probably easiest to implement this behavior in gopls.

Putting this in the backlog for now, as I don't think we have resources to prioritize this for the next minor release.

**Comment by findleyr** [comment]
Well @ShoshinNikita picked this up -- thanks! @hyangah in that CL, we're returning nil error. I feel like it would be better to surface an error, but will that disrupt vscode?

**Comment by adonovan** [comment]
See https://github.com/golang/go/issues/73959, which proposes to revert this behavior change.
