### ISSUE TITLE
iOS arm64 Compilation 

### ISSUE THREAD

**Issue by awcchungster** [golang/go#49553]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alexchung/Library/Caches/go-build"
GOENV="/Users/alexchung/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/alexchung/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/alexchung/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.2/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/alexchung/Documents/magellantest/storjiOS/StorjiOS/StorjiOS/uplink-c/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9s/m3f5htzd4g5gh_mbbzmt7xh80000gn/T/go-build896945876=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Please consider helping and not close for being a question. There isn't much knowledge in the ecosystem for compiling for iOS and I think this answer would help a lot.

I am trying to compile a C/Go code to run in my iOS swift app. The library compiles fine for normal amd64 architecture.

To do the compilation I start with this compilation step which generate a static .a archive.

> GOOS=ios GOARCH=arm64 CGO_ENABLED=1 CC=$(go env
> GOROOT)/misc/ios/clangwrap.sh go build -ldflags -w -v -tags ios -o
> "storj_uplink-arm64.a" -buildmode=c-archive

The next step after I use a scrub conversion to a dylib

> xcrun -sdk iphoneos clang -arch arm64 -fpic -shared -Wl,-all_load
> storj_uplink-arm64.a  -framework Corefoundation -o libuplinkc.dylib

In Xcode, I drag the dependency to the copy files build phase. From Swift, I check various symbol addresses that I need and I can confirm beyond that step. However when the actual binary is running, I receive a series of runtime errors.

> dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection
> DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

Based on these errors and steps, I believe this has to do with the Go build process, but it's not clear what is breaking. In case this helps, I'm using the Storj uplink-c to Swift bindings [relevant ticket here](https://github.com/storj-thirdparty/uplink-swift/issues/5). People seem pretty convinced the C library is fine and suggested I go to the Go community for more debugging. I've tried stackoverflow/Git, but this problem is low enough level people aren't able to help.

### What did you expect to see?

The core code works and functions are called

### What did you see instead?

In lldb debugger, this message is given with a Thread 12 signal SIGILL error.

    libuplinkc.dylib`golang.org/x/sys/cpu.getisar0:
    ->  0x10c7a36f0 <+0>:  mrs    x0, ID_AA64ISAR0_EL1
        0x10c7a36f4 <+4>:  str    x0, [sp, #0x8]
        0x10c7a36f8 <+8>:  ret    
        0x10c7a36fc <+12>: udf    #0x0

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
