### ISSUE TITLE
x/build/init: The init() call order is out of order

### ISSUE THREAD

**Issue by chasun-alive** [golang/go#49574]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.17
go version go1.17.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\Pragrams\GOPATH\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\Pragrams\GOPATH
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Golang\go1.17.2
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Golang\go1.17.2\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.2
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Pragrams\BlockChain\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build534148383=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
(1) I accessed SQL in a init() function, I Got `nil`
(2) Then, I did a little experiment, I found the order of `init()`  calls is not farthest first ! 
(3) Look at the code below，the actual call order is：B → C → A 
![QQ截图20211114032910](https://user-images.githubusercontent.com/47878132/141656693-f18c2ee8-7e5c-4a98-91b4-3ddf0dba2537.png)

<pre>
```A
func init() {
	fmt.Println("A", B)
}
func main() {
}
```
```B
func init() {
	fmt.Println("B", C)
}
var B int = 0

```
```C
var C *sqlx.DB

func init() {
	fmt.Println("C")
	database, err := sqlx.Open("mysql","root:My)4@0!1@tcp(localhost:3306)/blockchain")
	HandleError(err,"Utils.go:init")
	DB = database
}
```
</pre>

### What did you expect to see?
the call order of init() is ：the farthest C → B → A

### What did you see instead?
The order I see it ：B → the farthest C → A

**Comment by seankhliao** [comment]
package initialization order is specified here: https://golang.org/ref/spec#Package_initialization

the order you observed appears correct
