### ISSUE TITLE
cmd/compile: misleading error message for index expression

### ISSUE THREAD

**Issue by mdevan** [golang/go#49571]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

In this code:

```go
	if a, b := c["foo"]; b {
		fmt.Print(a)
	}
```
if the variable 'c' is not defined, these errors are reported:

```
./prog.go:8:10: assignment mismatch: 2 variables but 1 value
./prog.go:8:13: undefined: c
```

The first error message is misleading and redundant.

https://play.golang.org/p/I0TcR8834tK

### What did you expect to see?

Only the second error message (`undefined: c`).

### What did you see instead?

As shown above.

**Comment by odeke-em** [comment]
Thank you @mdevan for reporting this issue! It is fixed for Go1.18 thanks be to the excellent work that @findleyr and @griesemer implemented this cycle.
```shell
$ go version && go run main.go 
go version devel go1.18-5344dcae41 Tue Nov 9 00:08:42 2021 +0000 darwin/amd64
# command-line-arguments
./main.go:8:13: undefined: c
```

You can experiment with the latest Go version by following https://pkg.go.dev/golang.org/dl/gotip#pkg-overview
```shell
$ go install golang.org/dl/gotip@latest
$ gotip download
```

I shall therefore close this issue, but please don't hesitate to reach out and file more bugs as you see them.
