### ISSUE TITLE
net/http: https://http2.golang.org/reqinfo does not work anymore

### ISSUE THREAD

**Issue by tranb3r** [golang/go#49589]
The request `https://http2.golang.org/reqinfo` does not seem to work anymore.
I've tested several browsers, operating systems, dns.
Is it still available ? Any alternative solution ?

**Comment by ALTree** [comment]
> Is it still available?

Likely not; the http2 demo serve was turned off. See #49301.

Closing here, but feel free to post in #49301 if you have something to add.
