### ISSUE TITLE
go/types: Generics error message doesn’t match source code when using `any`

### ISSUE THREAD

**Issue by JeremyLoy** [golang/go#49583]
### What version of Go are you using (`go version`)?

Go 1.18 tip

### Does this issue reproduce with the latest release?

No, because it includes generics

### What operating system and processor architecture are you using (`go env`)?

Whatever the go playground runs on

### What did you do?

I ran into a compiler error using generics in a switch statement.
https://gotipplay.golang.org/p/XLZZhe3QvIh

### What did you expect to see?

`T any` was included in the error string

### What did you see instead?

`T interface{}` was used instead. While correct, this doesn’t match the source code and can be confusing.

**Comment by JeremyLoy** [comment]
It should be noted that this issue does not exist for other constraints, including custom ones

https://gotipplay.golang.org/p/26slgh8cSBp

**Comment by findleyr** [comment]
Well, I put my speculative workaround into https://golang.org/cl/363974. It does seem to generally improve type strings, but I'm still wary that we don't fully understand the consequences of such a change.

**Comment by griesemer** [comment]
Both the 1.17 compiler and the 1.18 compiler have trouble with aliases. This is not new. What is new is that with with 1.18 we introduce `any` which will likely become one of the most widely used aliases next to `byte`, so discrepancies in error printing will become more apparent.

The pending CL seems like a fine solution for this for now.
