### ISSUE TITLE
cmd/go: VCS stamping is slow

### ISSUE THREAD

**Issue by dominikh** [golang/go#49582]
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dominikh/.cache/go-build"
GOENV="/home/dominikh/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dominikh/prj/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dominikh/prj"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/dominikh/prj/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/dominikh/prj/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.18-c49627e81b Thu Nov 11 11:47:33 2021 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2629688203=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
$ git clone https://github.com/kubernetes/kubernetes
$ cd kubernetes

# Go 1.17
$ time go list ./...
go list ./...  5.45s user 0.60s system 414% cpu 1.459 total

# a37bebc042672d20837ea348d45e39740568cb77
$ time go list ./...
go list ./...  6.42s user 3.52s system 253% cpu 3.924 total

# 76cef81bcff371c88d277f17c712ecf22b8c83e7
$ time go list ./...
go list ./...  9.13s user 3.96s system 196% cpu 6.665 total
```

The two commits were found via bisection and make up for virtually all of the increase in runtime. The underlying storage is fast NVMe, which makes the slowdown more impressive, even for a repository the size of Kubernetes.

/cc @jayconrod @bcmills

**Comment by seankhliao** [comment]
cc @matloob

**Comment by mvdan** [comment]
I can reproduce; the problem seems to be that we run two `git` commands to get the build information for every package:

```
$ go list -x ./... |& grep '^git' | sort | uniq -c
     51 git show -s --format=%H:%ct
     51 git status --porcelain
```

We're not even running those commands in different directories:

```
$ go list -x ./...
cd /home/mvdan/git/kubernetes
git status --porcelain
cd /home/mvdan/git/kubernetes
git show -s --format=%H:%ct
cd /home/mvdan/git/kubernetes
git status --porcelain
cd /home/mvdan/git/kubernetes
git show -s --format=%H:%ct
cd /home/mvdan/git/kubernetes
git status --porcelain
```

The fix seems relatively simple: within a single build, if we've already queried the VCS information for a VCS root directory, cache that and avoid querying it again.

**Comment by dominikh** [comment]
Indeed, these seem to account for the entire slowdown:

```
( repeat 51; do; git show -s --format=%H:%ct; git status --porcelain; done; )  3.64s user 2.98s system 131% cpu 5.022 total
```

**Comment by bcmills** [comment]
At least suppressing the repeated calls should be an easy fix.

(This also looks like another case where #29666 would really help.)
