### ISSUE TITLE
x/website: feed.atom self link is incorrect

### ISSUE THREAD

**Issue by deltamualpha** [golang/go#49595]
looking at `https://go.dev/blog/feed.atom`, the `link` element at the top of the feed points to the wrong URL:

`<link rel="self" href="https://go.dev/feed.atom"></link>` (that URL is a 404.)

The element should instead be:

`<link rel="self" href="https://go.dev/blog/feed.atom"></link>`.

Related: #47795 would make the blog feed more discoverable.

**Comment by skeeto** [comment]
It seems the feed disappeared altogether a few hours ago. All I get now is an HTTP 404.

**Comment by powerman** [comment]
My RSS client used https://go.dev/blog/feeds/posts/default which is also 404 now. :disappointed:

**Comment by dmitshur** [comment]
Thanks everyone for reporting this, it is indeed a new problem.

It should be fixed within a couple of days, along with a test to avoid future regressions. Thanks for your patience.
