### ISSUE TITLE
debug/pe: reading debug_info section of PE files that use the DWARF5 form DW_FORM_line_strp causes error

### ISSUE THREAD

**Issue by aarzilli** [golang/go#49590]
Trying to read debug_info sections in PE files that use the form DW_FORM_line_strp will return the error `decoding dwarf section line_str at offset 0x0: underflow`.

**Comment by LomikXP** [comment]
We need fix in 1.16 too!

**Comment by bearsh** [comment]
any change to get this backported? AFAIK otherwise debugging does not work if the application needs gcc to build and gcc is >=11
