### ISSUE TITLE
access: may-start-trybots

### ISSUE THREAD

**Issue by changkun** [golang/go#49604]
See https://golang.org/wiki/GerritAccess

Hi! Could I maybe have Gerrit access for may-start-trybots, https://go-review.googlesource.com/#/admin/groups/1030,members?
It would be very helpful to help manage and test mobile builders referring to discussions in #49048, https://groups.google.com/g/golang-dev/c/oiuIE7qrWp0, and more.

My Gerrit user ID there is 30903, with the Gmail address mail@changkun.de. Thank you!

cc @golang/release @dmitshur @steeve

**Comment by dmitshur** [comment]
Thank you very much for your contributions to to the Go project, and especially for your help maintaining the mobile builders @changkun! This access is now granted to your Gerrit account.

As a reminder from https://go.dev/wiki/GerritAccess#running-trybots-may-start-trybots, please be sure to at minimum skim CLs before starting a trybot run.

Thank you again!
