### ISSUE TITLE
go/types, types2: confusing error message when using comparable in a union

### ISSUE THREAD

**Issue by Code-Hex** [golang/go#49602]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-c2397905e0 Sat Nov 13 03:33:55 2021 +0000 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

No, because it includes generics

### What operating system and processor architecture are you using (`go env`)?

Whatever the go playground runs on
### What did you do?

https://gotipplay.golang.org/p/FSMOjCXAtSL

### What did you expect to see?

can compile

### What did you see instead?

compile error

./prog.go:6:66: cannot use comparable in union (interface contains methods)

**Comment by syumai** [comment]
comparable interface should be treated as a union of enumerated comparable types, so expect to be able to use it in a union. (I think comparable interface does not contain method as a constraint.)
If it is not allowed to use comparable within a union, then I want a different error message like below.

```
cannot use comparable in union (comparable can not be a union element)
```

**Comment by findleyr** [comment]
CC @griesemer 

This is working as intended, at least for Go 1.18. See https://github.com/golang/go/issues/45346#issuecomment-862505803 for more context.  With respect to computing type sets, comparable behaves like an interface with methods.

I agree that we should improve the error message, however.

**Comment by Code-Hex** [comment]
Thank you for your comment.

To be honest, I didn't understand why comparable types are not allowed to be used in unions.
https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#comparable-types-in-constraints

This is jus curious. Are there any resources or links that can help me?

**Comment by griesemer** [comment]
Eventually there will be better documentation. We're in the middle of writing it. Suffice to say that for 1.18 at least, `comparable` cannot be part of a multi-element union.

Will keep this open to improve the error message.
