### ISSUE TITLE
net.ListenIP: failed when network is ip:50

### ISSUE THREAD

**Issue by WingPig99** [golang/go#49612]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
No, haven't try.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/--/Library/Caches/go-build"
GOENV="/Users/--/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/--/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/--/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.2/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sl/1s293gd924l4pw9jtqw37q0c0000gn/T/go-build1496403415=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Try to listen raw IP packet using `net.ListenIP("ip:50", address)`, see https://play.golang.org/p/iW558sJvrWq

### What did you expect to see?
Run succeed.

### What did you see instead?
socket: operation not supported on socket

**Comment by WingPig99** [comment]
Thanks, Sean. I tried with root permission, still has the problem on macOS. It works on Ubuntu 20.04.3.
```
sudo go run test.go
2021/11/16 15:34:01 Listen IP failed listen ip:50 127.0.0.1: socket: operation not supported on socket
```

**Comment by WingPig99** [comment]
@seankhliao Thank your for your reply. Should I close this issue or let it to wait further information?

**Comment by seankhliao** [comment]
Given that there's nothing Go can do about this I think it can be closed
