### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by nadroz** [golang/go#49617]
### What version of Go are you using (`go version`)?

<pre>
$ go version 
  - N/A (I'm reporting a website outage)

</pre>

### Does this issue reproduce with the latest release?
  - N/A (I'm reporting a website outage)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
  - N/A (I'm reporting a website outage)

</pre></details>

### What did you do?
I visited [the os package documentation page](https://pkg.go.dev/os) as well as the documentation pages for several other packages

### What did you expect to see?
The documentation for the os package (or in general any documentation pages)

### What did you see instead?
a 404 response page

**Comment by afq984** [comment]
Experienced the same ~20 minutes ago. Only pkg.go.dev gave 404. Main go.dev site was fine.
pkg.go.dev seems up now though.

**Comment by seankhliao** [comment]
This is a general GCP issue https://status.cloud.google.com/incidents/6PM5mNd43NbMqjCZ5REh

**Comment by seankhliao** [comment]
tracked in #49549
