### ISSUE TITLE
x/website: hamburger menu not working on iOS safari 

### ISSUE THREAD

**Issue by awmorgan** [golang/go#49629]
### What version of Go are you using (`go version`)?
Whatever’s on the website today 

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)? 
iOS 15.0.2

### What did you do?
Load golang.org in safari and touch menu icon in upper right corner of page 

### What did you expect to see?
Menu

### What did you see instead?
Nothing

**Comment by dr2chase** [comment]
The hamburger works fine (right this instant) on Android.
I will see if I can reproduce on someone's iPhone.

**Comment by awmorgan** [comment]
FYI: It is just the golang.org home page where it is not working.  If you click 'read more' on the home page then you get redirected to the go blog on go.dev/blog and the hamburger starts working on that site.

**Comment by prattmic** [comment]
FWIW, I am running iOS 15.1 and the menu on golang.org works fine in Safari.

**Comment by rsc** [comment]
Can you please try a force reload, however that is spelled in iOS Safari?
There may be some bad cache results for the supporting JS.

**Comment by awmorgan** [comment]
Force reload worked. Thanks Russ! By the way "force reload" is spelled "turn on airplane mode, refresh to fail, turn off airplane mode, refresh" ref: https://apple.stackexchange.com/a/392786/348057

**Comment by rsc** [comment]
Thanks, had no idea. What a magic spell!

Current theory is that the [outage yesterday](https://status.cloud.google.com/incidents/6PM5mNd43NbMqjCZ5REh) may have resulted in some of the intermittent 404s being cached for some of the JS, which of course would make it stop running in the pages.
