### ISSUE TITLE
json.Unmarshal panic with zero cap bytes slice

### ISSUE THREAD

**Issue by GerryLon** [golang/go#49637]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.3 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/workspace/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/workspace/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/soft/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/soft/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2428030964=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

a.go
```go
package main

import (
        "encoding/json"
        "fmt"
        "unsafe"
)

func NoAllocBytes(buf string) []byte {
        return *(*[]byte)(unsafe.Pointer(&buf))
}

type Test struct {
        Field []string `json:"field"`
}

func main() {
        jsonStr := `{"field":["aa"]}`
        testData := &Test{}
        // bytes := []byte(jsonStr)  // ok
        bytes := NoAllocBytes(jsonStr)
        err := json.Unmarshal(bytes, testData)
        fmt.Println(err, testData)
}
```
Makefile
```
all:
                                go build -gcflags='-l -N' -o no-inline a.go
                                go build -o normal a.go
run:
                                ./no-inline
                                ./normal
```

![image](https://user-images.githubusercontent.com/25873611/142227716-36b6c009-5605-44c1-93fe-f6904eb00586.png)

### What did you expect to see?
no panic in "normal compile mode"

### What did you see instead?
panic in "normal compile mode"

**Comment by randall77** [comment]
```
func NoAllocBytes(buf string) []byte {
        return *(*[]byte)(unsafe.Pointer(&buf))
}
```
This is not correct. You're making a slice with junk as its capacity. Anything using the resulting slice is bound to fail because the slice doesn't obey the invariant that len <= cap.

**Comment by GerryLon** [comment]
@randall77  Yes, you are right. But why the not inline compine will success?

**Comment by randall77** [comment]
Sometimes you get lucky with what junk gets assigned to the capacity, sometimes you don't. Inlining can affect that.
