### ISSUE TITLE
cmd/compile: "any" should be an alias for "interface{}", not a defined type

### ISSUE THREAD

**Issue by cherrymui** [golang/go#49665]
The spec says

> the predeclared type any is an alias for the empty interface.

I would interpret it as "any" being an alias type, not a defined type, i.e. essentially `type any = interface{}`.

But it seems the compiler treats "any" as a defined type, for example,
```
package main

import "fmt"

var x any
var y interface{}

func main() {
	fmt.Printf("%T\n%T\n", &x, &y)
}
```
This prints
```
*any
*interface {}
```

(In contrast, the spec says "byte" is an alias for "uint8", and both byte and uint8 print as "uint8".)

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by findleyr** [comment]
See also #49583.  I expected that change to only affect error messages from the type checker, not %T formatting (if indeed this is a consequence of that change).

**Comment by findleyr** [comment]
CC @danscales @mdempsky 

Discussing with @griesemer, the problem may be here:
https://cs.opensource.google/go/go/+/master:src/cmd/compile/internal/types/universe.go;l=113;drc=5344dcae4139de85b9e3d8cea81f9b65fc2bd25f

Should that be `TINTER`, not `TFORW`?

**Comment by mdempsky** [comment]
If we confirm that `any` should be an alias, not a defined type, I can fix cmd/compile.

**Comment by randall77** [comment]
@thanm This may be related to the `any` problem you were trying to fix in DWARF.

**Comment by griesemer** [comment]
`any` is definitively and alias for `interface{}`.

**Comment by griesemer** [comment]
See also the [forthcoming spec](https://tip.golang.org/ref/spec#Interface_types) (search for `predeclared type any`).
