### ISSUE TITLE
cmd/compile: panic: runtime error: index out of range if generic type's method never called

### ISSUE THREAD

**Issue by squareheadc** [golang/go#49667]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-e8cda0a Fri Nov 19 00:05:59 2021 +0000 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/squarehead/Library/Caches/go-build"
GOENV="/Users/squarehead/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/squarehead/Program/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/squarehead/Program/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/squarehead/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/squarehead/sdk/gotip/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="devel go1.18-e8cda0a Fri Nov 19 00:05:59 2021 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/squarehead/Program/go/src/play/generic/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/28/rqpspsvd3ysgqk9bqth_tx1c0000gn/T/go-build3854113625=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```go
package a

type A[T any] struct {
}

func (a A[T]) F() {
	_ = a
}
```

```go
package b

import "a"

type B[T any] struct {
	_ a.A[T]
}
```

```go
package main

import "b"

func main() {
	var _ b.B[int]
}

```

### What did you see instead?
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
cmd/compile/internal/typecheck.(*importReader).readFuncDcls.func1(...)
	/Users/squarehead/sdk/gotip/src/cmd/compile/internal/typecheck/iimport.go:1174
cmd/compile/internal/typecheck.(*importReader).readFuncDcls(0x4?, 0xc000320580)
	/Users/squarehead/sdk/gotip/src/cmd/compile/internal/typecheck/iimport.go:1182 +0x245
cmd/compile/internal/typecheck.(*importReader).funcBody(0xc000330c60, 0xc000320580)
	/Users/squarehead/sdk/gotip/src/cmd/compile/internal/typecheck/iimport.go:1125 +0x65
cmd/compile/internal/typecheck.(*importReader).doInline(0xc0000fd400?, 0xc000320580)
	/Users/squarehead/sdk/gotip/src/cmd/compile/internal/typecheck/iimport.go:1092 +0x99
cmd/compile/internal/typecheck.ImportBody(0xc000320580)
	/Users/squarehead/sdk/gotip/src/cmd/compile/internal/typecheck/iimport.go:80 +0x206
cmd/compile/internal/noder.checkFetchBody(0xc000329860)
	/Users/squarehead/sdk/gotip/src/cmd/compile/internal/noder/stencil.go:638 +0x96
cmd/compile/internal/noder.(*genInst).getInstantiation(0x1f87a20, 0xc000329860, {0xc00000e188, 0x1, 0x1000189c6c0?}, 0x20?)
	/Users/squarehead/sdk/gotip/src/cmd/compile/internal/noder/stencil.go:659 +0x5a
cmd/compile/internal/noder.(*genInst).instantiateMethods(0xc0000fd6b0?)
	/Users/squarehead/sdk/gotip/src/cmd/compile/internal/noder/stencil.go:585 +0x24e
cmd/compile/internal/noder.(*genInst).buildInstantiations(0x1f87a20, 0x1)
	/Users/squarehead/sdk/gotip/src/cmd/compile/internal/noder/stencil.go:60 +0x3a
cmd/compile/internal/noder.BuildInstantiations(...)
	/Users/squarehead/sdk/gotip/src/cmd/compile/internal/noder/stencil.go:47
cmd/compile/internal/noder.(*irgen).generate(0xc000338000, {0xc000312470, 0x2, 0x203000?})
	/Users/squarehead/sdk/gotip/src/cmd/compile/internal/noder/irgen.go:320 +0x3db
cmd/compile/internal/noder.check2({0xc000312470, 0x2, 0x2})
	/Users/squarehead/sdk/gotip/src/cmd/compile/internal/noder/irgen.go:92 +0x16d
cmd/compile/internal/noder.LoadPackage({0xc0000bc100, 0x2, 0x0?})
	/Users/squarehead/sdk/gotip/src/cmd/compile/internal/noder/noder.go:90 +0x335
cmd/compile/internal/gc.Main(0x1943f08)
	/Users/squarehead/sdk/gotip/src/cmd/compile/internal/gc/main.go:191 +0xb13
main.main()
	/Users/squarehead/sdk/gotip/src/cmd/compile/main.go:55 +0xdd
```

**Comment by ALTree** [comment]
cc @randall77 @danscales

**Comment by danscales** [comment]
Thanks for the issue and test case!  I'm working on this, have the simple fix.
