### ISSUE TITLE
x/pkgsite: use downloads stats more heavily in search weighting (will help enterprise libraries) 

### ISSUE THREAD

**Issue by JeremyLoy** [golang/go#49664]
I have one small, modestly successful package.

https://pkg.go.dev/github.com/JeremyLoy/config

Looking at this package on pkg.go.dev it doesn't seem like its used very much with only 2 imports. Anyone that stumbles upon it might not use it for fear that it isn't getting put through regular production testing.

On Github though, the story is markedly different. The "traffic" panel (which is only visible to the owner and is not public) shows 1.6k downloads with anywhere from 40-200 a day over the past two weeks. The repo itself sees anywhere from 2-10 unique visitors daily.

For my particular library, the clear reason the numbers look so bad is because **my library is meant for enterprise applications** where the source code is not public and therefore **imports aren't being picked up by the module proxy/website**. This category of "enterprise" libraries seems to be, at least from my point of view, very hard to find through the official website. I almost always refer to collections like [awesome-go](https://github.com/avelino/awesome-go) instead. (which also seems to categorize libraries better but that will probably make a good separate issue...)

I just want to emphasize that I'm not making this issue as some sort of vain self-promotion. I'm using my own library here as an example because its the only one I have access to the Traffic panel for. I'm truly just making this issue so I can find useful libraries for my job more easily 😃

**Comment by JeremyLoy** [comment]
![image](https://user-images.githubusercontent.com/20881794/142466807-454dd117-cfb7-4ce6-afa6-16ef7c283f80.png)

**Comment by heschi** [comment]
cc @golang/pkgsite

**Comment by JeremyLoy** [comment]
Another stat of interest that GitHub provides is “referers”

as you can see from the below screenshot, zero visits are from the official pkg.go.dev website. Most are from GitHub directly (I have many tags trying to hone my SEO) and the rest are from sites that are bespoke package aggregators like awesome-go.

**Comment by JeremyLoy** [comment]
![59A1DBFE-DD89-402C-8786-097197D64CD8](https://user-images.githubusercontent.com/20881794/143534475-56bbc008-f524-47df-a35e-859ffe55bd0d.jpeg)

**Comment by seankhliao** [comment]
I think in #41805 consensus was that downloads was not a good stat.
