### ISSUE TITLE
x/website: typo in blog

### ISSUE THREAD

**Issue by kaspar-metsa-helmes** [golang/go#49676]
### What is the URL of the page with the issue?
 https://go.dev/blog/declaration-syntax
 
 
### What did you do?
 I noticed a logical fallacy: "Pointers are the exception that proves the rule."

 
 
 
### What did you expect to see?
"Pointers are the exception to the rule."

"exception that proves the rule" is a phrase from Cicero but Cicero actually meant was "exception proves that a rule exists in cases where the exception does not apply"
Here is the backstory where the phrase originated and how it is used incorrectly nowadays:
https://philpapers.org/archive/HOLTEP

Cicero's friend Balbus wanted to keep his Roman citizenship, but other senators said that Rome had laws with many countries like Carthage where giving Roman citizenship to anyone from that country was forbidden - thus giving citizenship to Balbus, from Gades, should also be forbidden! Cicero said there is no explicit law that Gadus' citizens can't get Roman citizenship - the fact that such a law with Carthage exists means that in all other cases Roman citizenship can be granted - the exception of Carthage proves that there is a rule in cases not excepted.

**Comment by seankhliao** [comment]
This uses the colloquial meaning of the idiom
ref https://www.collinsdictionary.com/dictionary/english/the-exception-that-proves-the-rule
