### ISSUE TITLE
net: TestInterface* fails on an AIX server

### ISSUE THREAD

**Issue by WTaoGitHub** [golang/go#49675]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.7 aix/ppc64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="ppc64"
GOBIN=""
GOCACHE="/.cache/go-build"
GOENV="/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="ppc64"
GOHOSTOS="aix"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="aix"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/freeware/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/freeware/lib/golang/pkg/tool/aix_ppc64"
GOVCS=""
GOVERSION="go1.16.7"
GCCGO="gccgo"
GOPPC64="power8"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/opt/freeware/lib/gosrc/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -maix64 -pthread -mcmodel=large -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build890450651=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I was trying to install the Go v1.16.10 from the source on an AIX because I didn't find the download port for ppc64. 
1 download the source from https://golang.org/dl/go1.16.10.src.tar.gz
2 cd to src
3 ./all.bash

### What did you expect to see?
I expected success.

Or there is any downloadable  build of go1.16.10 for PPC64

### What did you see instead?
FAIL message.
`go tool dist: Failed: exit status 1
`
The test failed.
```
ok      mime/multipart  0.568s
ok      mime/quotedprintable    0.262s
--- FAIL: TestInterfaceAddrs (0.00s)
    interface_test.go:96: unexpected prefix length: 64/128 for &net.IPNet{IP:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1}, Mask:net.IPMask{0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}
--- FAIL: TestInterfaceUnicastAddrs (0.00s)
    interface_test.go:120: {1 16896 lo0  up|broadcast|loopback|multicast} unexpected prefix length: 64/128 for &net.IPNet{IP:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1}, Mask:net.IPMask{0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}
--- FAIL: TestInterfaceMulticastAddrs (0.00s)
    interface_test.go:142: unexpected prefix length: 64/128 for &net.IPNet{IP:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1}, Mask:net.IPMask{0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}
FAIL
FAIL    net     4.849s
ok      net/http        23.915s
ok      net/http/cgi    1.107s
ok      net/http/cookiejar      0.089s
ok 
```

Thanks

**Comment by seankhliao** [comment]
Is the machine setup correctly?
The IPv6 loopback is defined to be on `::1/128` while it appears to be `::1/64` on your system.

**Comment by WTaoGitHub** [comment]
@seankhliao 
Thanks for your help, after setting the IPv6 loopback to  `::1/128`, I can pass the test now.
