### ISSUE TITLE
x/net/http2: Client doesn't send body until ExpectContinueTimeout expires

### ISSUE THREAD

**Issue by mhr3** [golang/go#49677]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
This is a problem with x/net master

### What did you do?

Set a non-zero timeout for ExpectContinueTimeout on http.Transport and sent a POST request with `Expect: 100-continue` over h2.

### What did you expect to see?

The request uploads the data and finishes.

### What did you see instead?

The data doesn't start uploading until after the specified timeout expires, adding extra latency.

**Comment by heschi** [comment]
cc @neild

**Comment by neild** [comment]
@gopherbot Please open backport issues for 1.16 and 1.17.  This is a regression.
