### ISSUE TITLE
go run -modfile=<path/to/go.mod> doesn't find local packages within the referenced module

### ISSUE THREAD

**Issue by matthewmueller** [golang/go#49671]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/m/Library/Caches/go-build"
GOENV="/Users/m/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/m/dev/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/m/dev"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/m/dev/src/github.com/matthewmueller/hack/gomod/a/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4f/tcxcr6_55v9bp38d8g4hjlf80000gn/T/go-build1611476506=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I'd like to generate and build a main function that lives outside of my application. I noticed while trying this that `go run -modfile=<path/to/go.mod> main.go` doesn't pick up local packages inside the referenced module.

For example,

```
$ tree
.
├── app
│   ├── db
│   │   └── db.go
│   ├── go.mod
│   └── main.go
└── tmp
    └── main.go
```

**app/db/db.go**

```go
package db

func URL() string {
	return "postgres://localhost:5432/db"
}
```

**app/go.mod**

```
module app.com

go 1.17
```

**app/main.go**

```go
package main

import (
	"fmt"

	"app.com/db"
)

func main() {
	fmt.Println("from main", db.URL())
}
```

**tmp/main.go**

```go
package main

import (
	"fmt"

	"app.com/db"
)

func main() {
	fmt.Println("from tmp", db.URL())
}
```

Running `app/main.go` yields:

```
$ (cd app && go run main.go)
from main postgres://localhost:5432/db
```

However, when I run `tmp/main.go` pointing to `app/go.mod`, I get:

```
$ (cd tmp && go run --modfile=../app/go.mod main.go)
main.go:6:2: no required module provides package app.com/db; to add it:
        go get app.com/db
```

### What did you expect to see?

```
$ (cd tmp && go run --modfile=../app/go.mod main.go)
from tmp postgres://localhost:5432/db
```

I was originally going to write this off as me not using the flag properly, but it does work with remote modules that are required in `app/go.mod`, so this feels like a bug.

### What did you see instead?

See above.

**Comment by seankhliao** [comment]
With the file structure/commands you provided, I get:

```
$ cd tmp && go run -modfile=../app/go.mod
go: cannot find main module, but -modfile was set.
	-modfile cannot be used to set the module root directory.
```

If I set  a `go.mod` on  different (parent) directory, then I get the error you see.,
But it's correct, since that (parent) `go.mod` file will determine the module root and the package paths within the module will be wrong.
