### ISSUE TITLE
internal/fuzz: test_fuzz_minimize failures missing "got the minimum size" beginning 2021-11-17

### ISSUE THREAD

**Issue by bcmills** [golang/go#49685]
```
    --- FAIL: TestScript/test_fuzz_minimize (46.15s)
        script_test.go:257: 
            # We clean the fuzz cache during this test. Don't clean the user's cache. (0.000s)
            # Test that fuzzminimizetime cannot be negative seconds (18.682s)
            # Test that fuzzminimizetime cannot be negative times (2.829s)
            # Test that fuzzminimizetime can be zero seconds, and minimization is disabled (4.268s)
            # Test that fuzzminimizetime can be zero times, and minimization is disabled (7.046s)
            # Test that minimization is working for recoverable errors. (1.949s)
            # The error message that was printed should be for the one written to testdata. (0.000s)
            # Check that the bytes written to testdata are of length 50 (the minimum size) (1.023s)
            # Test that re-running the minimized value causes a crash. (4.685s)
            # Test that minimization is working for recoverable errors. Run it with -v this
            # time to ensure the command line output still looks right. (1.639s)
            > ! go test -v -fuzz=FuzzMinimizerRecoverable -run=FuzzMinimizerRecoverable -fuzztime=10000x .
            [stdout]
            === FUZZ  FuzzMinimizerRecoverable
            fuzz: elapsed: 0s, gathering baseline coverage: 0/1 completed
            fuzz: elapsed: 0s, gathering baseline coverage: 1/1 completed, now fuzzing with 16 workers
            fuzz: minimizing 427-byte failing input file
            fuzz: elapsed: 0s, minimizing
            --- FAIL: FuzzMinimizerRecoverable (0.24s)
                --- FAIL: FuzzMinimizerRecoverable (0.00s)
                    y_test.go:38: contains a non-zero byte of length 97
                
                Failing input written to testdata\fuzz\FuzzMinimizerRecoverable\064b38366638e28ac6d4036031db2afcda0528bfb8393486ed0358da0f930fe6
                To re-run:
                go test -run=FuzzMinimizerRecoverable/064b38366638e28ac6d4036031db2afcda0528bfb8393486ed0358da0f930fe6
            FAIL
            exit status 1
            FAIL	example.com/y	0.304s
            [exit status 1]
            > ! stdout '^ok'
            > stdout 'got the minimum size!'
            FAIL: testdata\script\test_fuzz_minimize.txt:54: no match for `(?m)got the minimum size!` found in stdout
```

`greplogs --dashboard -md -l -e '(?ms)FAIL: TestScript/test_fuzz_minimize.*no match for ...m.got the minimum size' --since=2021-06-01`

[2021-11-19T00:05:59-e8cda0a/linux-386-longtest](https://build.golang.org/log/c4981f87738996d3041a5710bcc6a65fde0d5831)
[2021-11-18T22:40:42-2375b6e/linux-386-longtest](https://build.golang.org/log/6f40a5c9636327faa45b9127eea3337d2907c1ea)
[2021-11-18T20:11:45-24898d6/windows-amd64-longtest](https://build.golang.org/log/adbea741b923c9c7873b003bfd305ef8caa86106)
[2021-11-18T14:00:00-14c3f74/windows-amd64-longtest](https://build.golang.org/log/a50d105074ad32587f526037e8deb5eaa3320112)
[2021-11-18T02:15:36-2463b4f/windows-amd64-longtest](https://build.golang.org/log/73fcc849233b0d1e3f0cc6494c7db7c4a5e0f5f4)
[2021-11-18T02:10:22-e3b48af/linux-386-longtest](https://build.golang.org/log/2582869c81deba71b1fb87355e83a68e3d41eb13)
[2021-11-17T21:26:25-0440fb8/linux-386-longtest](https://build.golang.org/log/5832408a9ed35ff22f9dcf91edace46ea1d2433c)
[2021-11-17T21:26:25-0440fb8/windows-amd64-longtest](https://build.golang.org/log/936f760c167a926d118148d95008db2e35e3dff6)

(CC @rolandshoemaker @katiehockman)

**Comment by rolandshoemaker** [comment]
After submitting CL365175 and CL365294 (the two fuzzing changes from yesterday) I am no longer able to reproduce this (at least on the linux-386-longtest builder).

**Comment by bcmills** [comment]
I merged [CL 365315](https://golang.org/cl/365315) (skipping the test) right around then. Are you testing with that rolled back?

**Comment by bcmills** [comment]
We could always try just rolling back the skip and seeing if the builders remain clear. The failure rate was high enough previously that it should show up within a half-dozen CLs or so if it's still broken.

**Comment by bcmills** [comment]
Rolled back the skip. Watching the builders to see whether this appears to be fixed.

**Comment by bcmills** [comment]
A fair number of `longtest` runs so far and no flakes from this test. Barring further evidence to the contrary, I'm calling this fixed.
