### ISSUE TITLE
x/website: "The Go Blog" Atom feed - https://go.dev/blog/feed.atom - disappeared from the website

### ISSUE THREAD

**Issue by rjc** [golang/go#49704]
### What is the URL of the page with the issue?
 
https://go.dev/blog/feed.atom
 
### What is your user agent?
 
N/A
 
### Screenshot
 
N/A
 
### What did you do?
 
Refreshed my newsreader's feeds.
 
### What did you expect to see?
 
An atom feed with "The Go Blog" entries.
 
### What did you see instead?

> open blog/feed.atom: file does not exist

Looking at my newsreader's `error.log`, the file dissapeared before 6 p.m. GMT on the 17th November:

    [2021-11-17 17:59:54] Error while retrieving https://go.dev/blog/feed.atom: HTTP response code said error 404

**Comment by seankhliao** [comment]
tracked in #47795

**Comment by rjc** [comment]
#47795 is a different issue altogether - first reported in August. #49595 started as something else, but now also noted the feed's disappearance. Either way, I'll keep an eye on both :^)

**Comment by seankhliao** [comment]
sorry, yes it's #49595
