### ISSUE TITLE
x/pkgsite: package removal request for github.com/rootblack45/go-authy

### ISSUE THREAD

**Issue by rootblack45** [golang/go#49703]
### What is the path of the package that you would like to have removed?

github.com/rootblack45/go-authy

 
 
 
### Are you the owner of this package?

Yes

 
### What is the reason that you could not retract this package instead?

This package has been deleted from my Github account a long time ago.

**Comment by heschi** [comment]
cc @jamalc

**Comment by jamalc** [comment]
Done.
