### ISSUE TITLE
x/tools/gopls: getting BrokenImport Error

### ISSUE THREAD

**Issue by n9hal** [golang/go#49715]
### What version of Go are you using (`go version`)?
1.17.2

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
NA

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre>
![image](https://user-images.githubusercontent.com/57591622/142818761-a173c96d-1c26-454c-82cb-c27743abef80.png)

</details>

### What did you do?

trying to import the gorm package.

### What did you expect to see?
to see proper output

### What did you see instead?

![image](https://user-images.githubusercontent.com/57591622/142818910-6dc8ebc3-342c-4019-a432-b34ccd3bbf55.png)

![image](https://user-images.githubusercontent.com/57591622/142819392-22301800-840b-431c-93c1-ddd4a07b9636.png)

**Comment by seankhliao** [comment]
Do you have a `go.mod` file in you project and did you open your editor there?

**Comment by n9hal** [comment]
yes. I tried without go.mod file also but same error

**Comment by seankhliao** [comment]
which directory/folder did you open vscode in?

**Comment by n9hal** [comment]
my go_workspace (Location: D:\Codes\go_workspace )

- vscode Screenshot

![image](https://user-images.githubusercontent.com/57591622/142821334-bbee7a5c-7b4a-4c31-964f-ae30d29265f4.png)

- env path
![image](https://user-images.githubusercontent.com/57591622/142821563-9274f7a6-dec4-48f1-bc00-13bd57873b17.png)

**Comment by n9hal** [comment]
and other thing when I used `go mod init` command to create the `go.mod` file, it shows the error like this 

![image](https://user-images.githubusercontent.com/57591622/142822523-cc5f050e-8350-463e-9bab-412163156425.png)

**Comment by hyangah** [comment]
Given that `go env GOMOD` output NULL, I guess your `go.mod` file is not in the workspace root.
The module root directory should be in the workspace root (D:\Codes\go_workspace) or you need to configure to work with multiple modules. Please see https://github.com/golang/vscode-go#setting-up-your-workspace - in particular, the last paragraph.

**Comment by n9hal** [comment]
Okay I'll try

**Comment by n9hal** [comment]
Thank you guys, Its working now...
