### ISSUE TITLE
UX Feedback From Someone Who Values Productivity

### ISSUE THREAD

**Issue by elibroftw** [golang/go#49713]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\maste\AppData\Local\go-build
set GOENV=C:\Users\maste\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\maste\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\maste\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\maste\Documents\GitHub\mnm-monero-node-manager\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\maste\AppData\Local\Temp\go-build208353593=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I was trying go for the first time. In particular I wanted to use https://github.com/webview/webview. 
So in a directory, I did `go get github.com/webview/webview`, and thought the module was ready to use. I then created a main.go file and copied their code. "no required module provides package github.com/webview/webview: go.mod file not found in current directory or any parent directory; see 'go help modules". The error message should be "package X is not required by any go.mod file in current or parent directory's. Did you use go mod init?" not "see go help modules" which is useless. Not only this, but if go get had just told me that it could create a `go.mod` for me, that'd have saved me a lot of time! There isn't even any status message! The last output message is still downloading. The user should see 
"downloaded package github.com/sciter-sdk/go-sciter"
"I see there is a go file in the current directry. If you wanted to use github.com/sciter-sdk/go-sciter in a file in the current directory, you can do so with `go get github... --mod-init OR -m filename`".

So what did I do next? I did `go mod init github.com/webview/webview` because I didn't realize package = module. After that, running `main.go` resulted in go telling me the package was a main file....So the error message here should've been "import X is defined as the module for go.mod, and is not defined as a requires there. Did you use go mod init X instead of go mod init yourpkg?" not "import "github.com/webview/webview" is a program, not an importable package."

Finally I went to your website's get started page. You tell me to enable dependency tracking but then give me a sub directory path? The example should be realstic; `go mod init main.go`. Simple, but actually no.

So now the `go.mod` has been created, BUT the next step is to create the file. It is simply illogical to create the file after we use a command with it rather than first creating the file and then using it in a command. The latter way also supports auto complete. But wait, why doesn't go mod init just create the file for me??? If the command is so simple, at least add a flag or by default create the go file for me. Even telling the user to use the flag `-c` to create a go file by the name provided to `init` would improve my productivity.

The first sentence of this repo says, "makes it easy to build simple", but that was not my experience at ALL. I looked at the README and there is some redundancy:

Official binary distributions are available at https://golang.org/dl/.
After downloading a binary release, visit https://golang.org/doc/install for installation instructions.

I hope you don't need me to spell it out, but the first link is redundant. The second link already has a one click download link plus instructions. It should be like this:

Download binary distributions from https://golang.org/doc/install for installation instructions. The probability that someone is spoofing their OS is so low, so you'd be saving people clicks by only providing the install link.

Sorry if I came off strong. It's just that hours of mine would be wasted if I didn't at least give you guys some good feedback. Go is a good start to dethroning C++, but adoption and beginner adoption will come no where close to Python if the starting UX is this unintuitive. I remember 7+ years ago, when I thought programming wasn't for me because of the bad UX I had with a raspberry Pi and a beginner Python turtle tutorial that didn't work and wasn't useful at all. I'm glad I had an open mind 2 years later to try a tutorial that actually taught. 

Another problem is that go get can't process https:// strings. There should be some error checking to account for cases where users decide to copy the URL. You can do this by a simple string startswith, and a replace http:// or https:// with an empty string.

**Comment by fzipp** [comment]
I'm not saying that error messages or documentation can't be improved, but I want to note two things:

- You tried to program in a new programming language without having read a beginner tutorial.
- When you finally read the beginner tutorial you ignored the instructions and made up your own thing:

> Finally I went to your website's get started page. You tell me to enable dependency tracking but then give me a sub directory path? The example should be realstic; go mod init main.go. Simple, but actually no.
> 
> So now the go.mod has been created, BUT the next step is to create the file. [...] why doesn't go mod init just create the file for me???

go.mod is not about tracking individual files. That's why it can't create "the file" for you. You increased your confusion by calling "go mod init" with "main.go" as its argument. The argument is supposed to be a name for the whole module you are going to create, not a file name.

**Comment by seankhliao** [comment]
The first error (only showing "downloading...") is because `go get` was used to both download dependencies and install executables. This is changing in the next release.

```
go get github.com/webview/webview
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

We've decided that most `go` commands should not implicitly change state.
We've also decided not to support `https://` in module names to not increase the confusion between module names and code hosting location, since they can differ. The arguments to `go` are always module names.

I believe the remainder is just not following the tutorial:
- `go mod init module.name/for/your/code` this creates `go.mod`, you should almost never have to edit the file directly
- write code in `*.go` files
- `go mod tidy` to download dependencies, or `go get` for more fine grained control over versioning

**Comment by elibroftw** [comment]
It's very confusing when the name of the project is "hello" but the name supplied to go mod init is "example/hello." What is example supposed to be exactly? I guess you think promoting blind following is a good idea? I would rather follow instructions incorrectly so that I do learn rather than follow instructions correctly, and not know why certain things were done. Do you see where we differ?

For example the project I'm trying to do is a desktop app, let's say "Cool App." I have a folder created called "Cool App." I see that I need to do `go mod init example/hello` so now I am stuck because I only came up with one name, not two. 

And then you end up creating a `hello.go` file anyways so that the file is in `hello/hello.go` but the name supplied to go mod init is `example/hello`. How is that not redundant? 
---
And for the URL support, I'm talking about letting the user know at the very least that http:// links are not supported rather that throwing a parsing error on a colon. And no I'm not talking about https in module names, I'm talking about installing from a URL. I've done it myself with Python, it's pretty neat. Maybe you shouldn't promote URL's as being the module name. The distinction that go is installing a module with a URL name instead of installing from a URL is not clear. So I guess you don't want to support installing from URL and that forks would need to go through a centralized Repo in order to be installed?

It's just not logical to use `go mod init` before creating a file to start coding in. At that point, you might as well just switch the tutorial to being like a Java tutorial, where the IDE takes care of boilerplate. That's the main issue, boilerplate code. Users shouldn't have to do boilerplate commands to get *some* boilerplate code. It should be one command `go new module`.
Only when the user does not supply a module path does `go` make it clear what it's trying to do. You are trying to organize files for us. `example.com/moduleName` but you know, what if users didn't have a website, so maybe there should be an example for people without any websites or who don't want the module to be associated with a website.

How about a new command then `go new modulename` that initializes a `go.mod` file and also a `main.go` file or a `modulename.go` file?

**Comment by seankhliao** [comment]
As the tutorial says:
> In actual development, the module path will typically be the repository location where your source code will be kept. For example, the module path might be github.com/mymodule. If you plan to publish your module for others to use, the module path must be a location from which Go tools can download your module

If you don't want to share it, you're free to choose some other name, like the `example/hello` used in the tutorial
Your directory layout should be

```
your-working-directory
├── go.mod              // created by `go mod init example/hello`, first line is `module example/hello`
└── hello.go            // write code in here
```

The 1 command is `go mod init name.of/module`
Which file you write your code in after doesn't matter
