### ISSUE TITLE
while installing through a makefile, getting go not found

### ISSUE THREAD

**Issue by sams2211** [golang/go#49714]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.3 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/student/go/bin"
GOCACHE="/home/student/.cache/go-build"
GOENV="/home/student/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/student/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/student/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/student/core/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3604357740=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.17.3 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.17.3
uname -sr: Linux 4.15.0-143-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.27-3ubuntu1.4) stable release version 2.27.
gdb --version: GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
</pre></details>

### What did you do?

 i downloaded www.github.com/terra-money/core and to install it , have to run `make install`
but all go command are working fine but getting this error for above package to install
`go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=terra -X github.com/cosmos/cosmos-sdk/version.AppName=terrad -X github.com/cosmos/cosmos-sdk/version.Version=0.5.6-oracle -X github.com/cosmos/cosmos-sdk/version.Commit=cb4b91199ff0d7c8260d102c6a595ca09d9079f6 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -w -s' -trimpath ./cmd/terrad
/bin/sh: 1: go: not found
Makefile:123: recipe for target 'install' failed
make: *** [install] Error 127`

any help ?

**Comment by seankhliao** [comment]
that is a makefile problem for that project not go problem
