### ISSUE TITLE
effective-go zh docs issues

### ISSUE THREAD

**Issue by shengzhou1216** [golang/go#49719]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.16
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?
“它是轻量级的， 所有消耗几乎就只有栈空间的分配”
“在Go中，函数字面都是闭包：其实现保证了函数内引用变量的生命周期与函数的活动时间相同。”

### What did you see instead?
[Go程](https://go-zh.org/doc/effective_go.html#Go%E7%A8%8B)第一段：
“它是轻量级的， 所有小号几乎就只有栈空间的分配” 中的“小号”应该是”消耗“
[Go程](https://go-zh.org/doc/effective_go.html#Go%E7%A8%8B)倒数第二行：
“在Go中，函数字面都是闭包：其实现在保证了函数内引用变量的生命周期与函数的活动时间相同。” 中的“其实现在”应该多了一个“在”

**Comment by seankhliao** [comment]
We don't operate the go-zh.org website (it's also very out of date).
I believe it's run by https://github.com/Go-zh
