### ISSUE TITLE
x/website: Download Go button on go.dev/doc/install page is broken, still points to golang.org

### ISSUE THREAD

**Issue by Pokom** [golang/go#49726]
### What is the URL of the page with the issue?
 
https://go.dev/doc/install
 
 
### What is your user agent?
 
```sh
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 Edg/96.0.1054.29
```
 
 
### Screenshot
![image](https://user-images.githubusercontent.com/1080566/142917638-14386e2b-f620-49fd-a630-3b2d279158ef.png)
 
 
### What did you do?
 
I tried to click the button to download the Windows installer.
 
 
### What did you expect to see?

The windows installer start to download. 
 
 ### What did you see instead?

![image](https://user-images.githubusercontent.com/1080566/142917727-8d8f560a-c9e5-40f4-834a-c41b8805f1ee.png)

**Comment by seankhliao** [comment]
cc @rsc  @dmitshur 
looks like missing content security policy for `golang.org/dl/?mode=json`

**Comment by dmitshur** [comment]
Also, the link is to "golang.org/dl/" but should likely be updated to "go.dev/dl/". CC @rsc.
