### ISSUE TITLE
runtime: "fatal error: unexpected signal during runtime execution" in cmd/go tests on darwin-amd64-race running macOS 12.0

### ISSUE THREAD

**Issue by bcmills** [golang/go#49723]
`greplogs --dashboard -md -l -e '(?m)\Adarwin-(?:.*\n)+^signal arrived during cgo execution' --since=2021-01-01`

[2021-11-22T16:53:57-cd0bf38/darwin-amd64-race](https://build.golang.org/log/854fa99c8fcc23af512b1d1a7c27a2bdefca2d74)
[2021-11-22T16:15:36-6275b54/darwin-amd64-race](https://build.golang.org/log/e1a68d46ddf47fc70e67d410125de3a6992aafce)

I don't see any CLs in the repo that would explain this failure, so I suspect that it was triggered by the `darwin-amd64-race` configuration change in [CL 365777](https://golang.org/cl/365777) for #49149 (CC @golang/release).

**Comment by cherrymui** [comment]
The environment printed at the top doesn't seem to have MallocNanoZone=0.

**Comment by heschi** [comment]
Deployed, cleared failed build, watching the dashboard.

**Comment by heschi** [comment]
Looks like mostly a success, but the cmd/go tests are failing, I would wager because they clear the environment. @bcmills should I file a bug?

**Comment by bcmills** [comment]
If you like, or we can reopen this one. Should be an easy fix, but we'll presumably need to backport it too.

**Comment by heschi** [comment]
example: https://build.golang.org/log/fc6170578af96cfeeac255e6670f1fef33468742

**Comment by bcmills** [comment]
@gopherbot, please backport to Go 1.16 and 1.17. This works around a regression in macOS 12.0.

**Comment by bcmills** [comment]
`cmd/go` fix is in, and I've got TryBots running on the backports. (They'll also be ready to merge as soon as the TryBots finish.)
