### ISSUE TITLE
x/exp/winfsnotify: TestNotifyEvents failures missing events on nested file

### ISSUE THREAD

**Issue by bcmills** [golang/go#49734]
```
--- FAIL: TestNotifyEvents (0.00s)
    winfsnotify_test.go:18: expected: "TestNotifyEvents.testdirectory/TestNotifyEvents.testfile": 0x100
    winfsnotify_test.go:24: received: "TestNotifyEvents.testdirectory/TestNotifyEvents.testfile": 0x100 == FS_CREATE
    winfsnotify_test.go:18: expected: "TestNotifyEvents.testdirectory/TestNotifyEvents.testfile": 0x2
    winfsnotify_test.go:24: received: "TestNotifyEvents.testdirectory/TestNotifyEvents.testfile": 0x2 == FS_MODIFY
    winfsnotify_test.go:18: expected: "TestNotifyEvents.testdirectory/TestNotifyEvents.testfile": 0x2
    winfsnotify_test.go:24: received: "TestNotifyEvents.testdirectory/TestNotifyEvents.testfile": 0x2 == FS_MODIFY
    winfsnotify_test.go:18: expected: "TestNotifyEvents.testdirectory/TestNotifyEvents.testfile": 0x40
    winfsnotify_test.go:24: received: "TestNotifyEvents.testdirectory/TestNotifyEvents.testfile": 0x40 == FS_MOVED_FROM
    winfsnotify_test.go:18: expected: "TestNotifyEvents.testdirectory/TestNotifyEvents.testfile.new": 0x80
    winfsnotify_test.go:24: received: "TestNotifyEvents.testdirectory/TestNotifyEvents.testfile.new": 0x80 == FS_MOVED_TO
    winfsnotify_test.go:18: expected: "TestNotifyEvents.testdirectory/TestNotifyEvents.testfile": 0x800
    winfsnotify_test.go:24: received: "TestNotifyEvents.testdirectory/TestNotifyEvents.testfile": 0x800 == FS_MOVE_SELF
    winfsnotify_test.go:18: expected: "TestNotifyEvents.testdirectory/TestNotifyEvents.testfile.new": 0x400
    winfsnotify_test.go:24: received: "TestNotifyEvents.testdirectory": 0x400 == FS_DELETE_SELF
    winfsnotify_test.go:26: did not receive expected event
FAIL
FAIL	golang.org/x/exp/winfsnotify	0.119s
```

`greplogs --dashboard -md -l -e 'FAIL: TestNotifyEvents'`

[2021-11-08T14:49:56-14c7236-ab31dbc/windows-amd64-2016](https://build.golang.org/log/5b41aec761620e2af7f47992417fb11cbd7d191a)
[2021-09-02T17:30:32-a062eea-7609b50/windows-386-2008](https://build.golang.org/log/0f595938c82be9c19b1f40fcd1f80e7cc40868d1)
[2021-05-05T20:34:22-b3083d5-15557af/windows-386-2008](https://build.golang.org/log/ff0f897c0e5d6482f46841ebb3ed97b0789aa85c)

As far as I can tell this package is more-or-less unchanged from [CL 4188047](https://golang.org/cl/4188047), over 10 years ago(!).

My best guess is that perhaps the test is overspecified: perhaps the OS sometimes delivers the events out of order between the parent directory and the child within it.

CC @bufflig @alexbrainman @mattn @hectorchu

**Comment by bufflig** [comment]
It's possible. The events arrive in batches, so you could imagine that it sometimes manages to collect several events in one batch and sometimes not, and that that could alter the order. Not the best interface if that is true though...

Flushing the events if things go wrong could help us see if that is the case. I put it on my todo list...

**Comment by bcmills** [comment]
`greplogs --dashboard -md -l -e 'FAIL: TestNotifyEvents' --since=2021-11-22`

[2022-01-04T21:10:15-025e73f-1c8f9d2/windows-amd64-longtest](https://build.golang.org/log/b1a13fbe6232b83dd3f7c1d1162f81ea1962bc2b)
[2021-11-22T20:34:40-ba1b3c3-f13fcd9/windows-386-2012](https://build.golang.org/log/467b3c45dfda0288f75e6332860acb5833cd583b)

**Comment by bcmills** [comment]
`greplogs --dashboard -md -l -e 'FAIL: TestNotifyEvents' --since=2022-01-18`

[2022-03-01T19:33:00-6cf2b20-258fc75/windows-amd64-2016](https://build.golang.org/log/ab7c5c65717f0e64e460be197d6a01aa091b4c86)
[2022-02-11T20:01:24-160e291-bcee121/windows-amd64-2016](https://build.golang.org/log/f41c3bf0a76057319214258840d416618136c70c)

**Comment by bcmills** [comment]
This is waiting on a review of the CLs to implement the (approved) proposal to delete the package and its test.

**Comment by bcmills** [comment]
Fixed by deleting the affected package. 😁
