### ISSUE TITLE
go/types, types2: incorrect behavior of API methods on invalid unions

### ISSUE THREAD

**Issue by findleyr** [golang/go#49739]
Consider the following code:

```
package p

type A int
type B int
type C interface{string}

type X interface{~A}
type Y interface{~B}
type Z interface{~int; C}
```

In this example, we have the following surprising behavior:

- `Identical(X.Type().Underlying(), Y.Type().Underlying()) == true`
- `Implements(X.Type().Underlying(), Y.Type().Underlying()) == true`
- `X.Type().Underlying().(*Interface).typeSet().IsEmpty() == false`
- `Identical(X.Type().Underlying(), Z.Type().Underlying)) == false`

The type set of `X` should be empty, per the update to the spec in https://golang.org/cl/362999. Are two interfaces with empty type sets identical? It's not clear to me, but we should be consistent.

CC @griesemer 

*found via fuzzing.

**Comment by griesemer** [comment]
Interfaces that define the same type set are identical. This may be too abstract for the spec, so perhaps we can rephrase a bit.

**Comment by findleyr** [comment]
Ok. But this is not just a documentation issue. There is a bug in our handling of `interface{~A}`, where `A` is defined: we raise an error but return an interface that is non-empty but has no concrete types that implement it (only interface types).

**Comment by griesemer** [comment]
@findleyr Is there anything left to do here?

**Comment by griesemer** [comment]
ping

**Comment by findleyr** [comment]
Thanks, I think this is done. Closing.
