### ISSUE TITLE
Subtracting a small positive duration from a large negative duration results in a large positive duration

### ISSUE THREAD

**Issue by jeffwidman** [golang/go#49740]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
I think so.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jeffwidman/Library/Caches/go-build"
GOENV="/Users/jeffwidman/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jeffwidman/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jeffwidman/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.2/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jeffwidman/Code/<redacted>/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ql/_wc1z7b12bx1k0ddhz5qd8_40000gn/T/go-build1808912620=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I have a small function that takes a `time.Time{}` value, calculates the duration until that value, subtracts 24 hours, and returns the resulting duration.

This has worked fine for a while. However, I was surprised to notice that if I pass it a `time.Time{}` with the zero value, that rather than giving me a large negative duration for the desired refresh time, it instead gives me a large **positive** duration.

I realize that the size of `time.Duration` is limited to ~290 years, so I'm not concerned about getting the exact value correct, but I was shocked to see the sign flip.

Confusingly, if I switch the order of the calculation to instead take the `time.Time{}` value, subtract 24 hours, and then calculate the duration until the value, I get the expected result for the sign.

Example:
https://go.dev/play/p/UyYeO2meOuW

```
package main

import (
	"fmt"
	"time"
)

func main() {
	expiresAt := time.Time{}
	fmt.Println("Expires at:", expiresAt)

	expiresIn := time.Until(expiresAt)
	fmt.Println("Expires in:", expiresIn)

	safetyMargin := 24 * time.Hour

	refreshIn := expiresIn - safetyMargin
	fmt.Println("Given a safety margin of", safetyMargin, "we should refresh in: ", refreshIn)

	// Alternative approach
	fmt.Println()
	fmt.Println("Alternative approach - subtract from time rather than duration:")
	fmt.Println("Expires at:", expiresAt)

	refreshAt := expiresAt.Add(-safetyMargin)
	fmt.Println("Given a safety margin of", safetyMargin, "we should refresh at: ", refreshAt)

	refreshIn2 := time.Until(refreshAt)
	fmt.Println("Refresh in", refreshIn2)
}

```

Output:
```
Expires at: 0001-01-01 00:00:00 +0000 UTC
Expires in: -2562047h47m16.854775808s
Given a safety margin of 24h0m0s we should refresh in:  2562023h47m16.854775808s

Alternative approach - subtract from time rather than duration:
Expires at: 0001-01-01 00:00:00 +0000 UTC
Given a safety margin of 24h0m0s we should refresh at:  0000-12-31 00:00:00 +0000 UTC
Refresh in -2562047h47m16.854775808s

Program exited.
```

**Comment by jeffwidman** [comment]
I'm interested in trying to fix this, but would appreciate any guidance if this is actually the expected behavior.

**Comment by ianlancetaylor** [comment]
Thanks for the note.  This is unfortunately unfixable.  A `time.Duration` is just an `int64`.  Go defines arithmetic on `int64` as using wrapping arithmetic.  So this is just something you have to watch out for.

Fortunately it can never happen with reasonable `time.Time` values.  It's always a mistake to use the zero value of `time.Time` (it represents January 1 in the year 1).

I'm going to close this because I don't think there is anything we can do.  Thanks for reporting it.

**Comment by jeffwidman** [comment]
Thanks for educating me, that all makes sense.
