### ISSUE TITLE
arm64 race detector link errors

### ISSUE THREAD

**Issue by DryHumour** [golang/go#49749]
Attempting to cross-compile with race detector from amd64 for arm64 fails, at least with our toolchain (a Yocto-ized SDK).

Various `__tsan_*` symbols are undefined.  (I assume that they are supposed to be resolved from the arm64 runtime?) There are also some DWARF errors relating to line number info out of bounds for the section size.  

Using only internal link mode also fails with undefined symbols and then faults.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/nschelle/.cache/go-build"
GOENV="/home/nschelle/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY="bitbucket.org/rockportnetworks/*"
GONOSUMDB="bitbucket.org/rockportnetworks/*"
GOOS="linux"
GOPATH="/go"
GOPRIVATE="bitbucket.org/rockportnetworks/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="aarch64-xilinx-linux-ar"
CC="aarch64-xilinx-linux-gcc"
CXX="aarch64-xilinx-linux-g++"
CGO_ENABLED="1"
GOMOD="/go/src/bitbucket.org/rockportnetworks/agent/go.mod"
CGO_CFLAGS="-march=armv8-a+crc -mtune=cortex-a72.cortex-a53 --sysroot=/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/aarch64-xilinx-linux -g -O2 -O2 -pipe -g -feliminate-unused-debug-types"
CGO_CPPFLAGS="-march=armv8-a+crc -mtune=cortex-a72.cortex-a53 --sysroot=/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/aarch64-xilinx-linux"
CGO_CXXFLAGS="-march=armv8-a+crc -mtune=cortex-a72.cortex-a53 --sysroot=/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/aarch64-xilinx-linux -g -O2 -O2 -pipe -g -feliminate-unused-debug-types"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-march=armv8-a+crc -mtune=cortex-a72.cortex-a53 --sysroot=/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/aarch64-xilinx-linux -g -O2 -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-march=armv8-a+crc -mtune=cortex-a72.cortex-a53 --sysroot=/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/aarch64-xilinx-linux -fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3895011355=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.17.3 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.17.3
uname -sr: Linux 5.8.0-63-generic
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Debian GLIBC 2.31-13+deb11u2) stable release version 2.31.
gdb --version: GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
</pre></details>

### What did you do?

<pre>
$ cat race.go
package main

// int x;
import "C"

func main() {
        var a int
        go func() { a = 1 }()
        go func() { a = 42 }()
        C.x = 99
}
$ go build -race
</pre>

### What did you expect to see?

No output i.e. success.

### What did you see instead?

<details><summary><code>go build -race</code> Output</summary><br><pre>
# bitbucket.org/rockportnetworks/agent/race
/usr/local/go/pkg/tool/linux_amd64/link: running aarch64-xilinx-linux-gcc failed: exit status 1
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: DWARF error: line info data is bigger (0x31020603) than the space remaining in the section (0x2117e)
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: DWARF error: line info data is bigger (0x73746174) than the space remaining in the section (0x1f802)
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: DWARF error: line info data is bigger (0xe9030a04) than the space remaining in the section (0x1dd48)
/tmp/go-link-3759056803/go.o: in function `runtime.mallocgc':
go.go:(.text+0xa0b0): undefined reference to `__tsan_malloc'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0xa0b4): undefined reference to `__tsan_malloc'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.(*sweepLocked).sweep':
go.go:(.text+0x1dc14): undefined reference to `__tsan_free'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x1dc18): undefined reference to `__tsan_free'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.goexit1':
go.go:(.text+0x38100): undefined reference to `__tsan_go_end'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x38104): undefined reference to `__tsan_go_end'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.gfget':
go.go:(.text+0x3a064): undefined reference to `__tsan_malloc'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x3a068): undefined reference to `__tsan_malloc'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.(*p).init':
go.go:(.text+0x3ab28): undefined reference to `__tsan_proc_create'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x3ab2c): undefined reference to `__tsan_proc_create'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.(*p).destroy':
go.go:(.text+0x3b008): undefined reference to `__tsan_go_end'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x3b00c): undefined reference to `__tsan_go_end'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x3b040): undefined reference to `__tsan_proc_destroy'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x3b044): undefined reference to `__tsan_proc_destroy'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.raceinit':
go.go:(.text+0x3fd5c): undefined reference to `__tsan_init'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x3fd60): undefined reference to `__tsan_init'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x3fddc): undefined reference to `__tsan_map_shadow'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x3fde0): undefined reference to `__tsan_map_shadow'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.racefini':
go.go:(.text+0x3fec0): undefined reference to `__tsan_fini'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x3fec4): undefined reference to `__tsan_fini'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.racemapshadow':
go.go:(.text+0x3ff58): undefined reference to `__tsan_map_shadow'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x3ff5c): undefined reference to `__tsan_map_shadow'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.racegostart':
go.go:(.text+0x3ffb4): undefined reference to `__tsan_go_start'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x3ffb8): undefined reference to `__tsan_go_start'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.raceacquireg':
go.go:(.text+0x4014c): undefined reference to `__tsan_acquire'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x40150): undefined reference to `__tsan_acquire'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.raceacquirectx':
go.go:(.text+0x401e8): undefined reference to `__tsan_acquire'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x401ec): undefined reference to `__tsan_acquire'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.racereleaseg':
go.go:(.text+0x4029c): undefined reference to `__tsan_release'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x402a0): undefined reference to `__tsan_release'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.racereleaseacquireg':
go.go:(.text+0x4034c): undefined reference to `__tsan_release_acquire'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x40350): undefined reference to `__tsan_release_acquire'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.racereleasemergeg':
go.go:(.text+0x403fc): undefined reference to `__tsan_release_merge'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x40400): undefined reference to `__tsan_release_merge'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.stackalloc':
go.go:(.text+0x468a8): undefined reference to `__tsan_malloc'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x468ac): undefined reference to `__tsan_malloc'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `racefuncenter':
go.go:(.text+0x5aa10): undefined reference to `__tsan_func_enter'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x5aa14): undefined reference to `__tsan_func_enter'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: DWARF error: line info data is bigger (0x7e03af06) than the space remaining in the section (0x1e0de)
/tmp/go-link-3759056803/go.o: in function `runtime.raceread':
go.go:(.text+0x5aa78): undefined reference to `__tsan_read'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x5aa7c): undefined reference to `__tsan_read'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.racereadpc':
go.go:(.text+0x5aa9c): undefined reference to `__tsan_read_pc'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x5aaa0): undefined reference to `__tsan_read_pc'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.racewrite':
go.go:(.text+0x5aab8): undefined reference to `__tsan_write'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x5aabc): undefined reference to `__tsan_write'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.racewritepc':
go.go:(.text+0x5aadc): undefined reference to `__tsan_write_pc'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x5aae0): undefined reference to `__tsan_write_pc'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.racereadrangepc1':
go.go:(.text+0x5ab00): undefined reference to `__tsan_read_range'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x5ab04): undefined reference to `__tsan_read_range'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.racewriterangepc1':
go.go:(.text+0x5ab20): undefined reference to `__tsan_write_range'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x5ab24): undefined reference to `__tsan_write_range'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: /tmp/go-link-3759056803/go.o: in function `runtime.racefuncexit':
go.go:(.text+0x5ab50): undefined reference to `__tsan_func_exit'
/opt/petalinux/2020.2/aarch64-xilinx-linux/sysroots/x86_64-petalinux-linux/usr/libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/9.2.0/real-ld: go.go:(.text+0x5ab54): undefined reference to `__tsan_func_exit'
collect2: error: ld returned 1 exit status
</pre></details>

Without the `import "C"` i.e. using internal link only:
<details><summary><code>go build -race</code> Output</summary><br><pre>
# bitbucket.org/rockportnetworks/agent/race
runtime.mallocgc: relocation target __tsan_malloc not defined
runtime.(*sweepLocked).sweep: relocation target __tsan_free not defined
runtime.goexit1: relocation target __tsan_go_end not defined
runtime.gfget: relocation target __tsan_malloc not defined
runtime.(*p).init: relocation target __tsan_proc_create not defined
runtime.(*p).destroy: relocation target __tsan_go_end not defined
runtime.(*p).destroy: relocation target __tsan_proc_destroy not defined
runtime.raceinit: relocation target __tsan_init not defined
runtime.raceinit: relocation target __tsan_map_shadow not defined
runtime.racefini: relocation target __tsan_fini not defined
runtime.racemapshadow: relocation target __tsan_map_shadow not defined
runtime.racegostart: relocation target __tsan_go_start not defined
runtime.raceacquireg: relocation target __tsan_acquire not defined
runtime.raceacquirectx: relocation target __tsan_acquire not defined
runtime.racereleaseg: relocation target __tsan_release not defined
runtime.racereleaseacquireg: relocation target __tsan_release_acquire not defined
runtime.racereleasemergeg: relocation target __tsan_release_merge not defined
runtime.stackalloc: relocation target __tsan_malloc not defined
racefuncenter: relocation target __tsan_func_enter not defined
runtime.raceread: relocation target __tsan_read not defined
runtime.racereadpc: relocation target __tsan_read_pc not defined
/usr/local/go/pkg/tool/linux_amd64/link: too many errors
unexpected fault address 0x7f04bb8965fd
fatal error: fault
</pre></details>

**Comment by seankhliao** [comment]
the race detector requirea CGo (cross compiler toolchain for target architecture)

**Comment by seankhliao** [comment]
Actually, see #49102

**Comment by DryHumour** [comment]
Doh!  I'd _swear_ I checked for existing issues.  Sorry!
