### ISSUE TITLE
x/pkgsite: not able to update my package in pkg.go.dev

### ISSUE THREAD

**Issue by nirrozenbaum** [golang/go#49747]
The path to my package is `https://pkg.go.dev/github.com/open-cluster-management/hub-of-hubs-data-types`.

I have initially created a pre-release tagged with version `v0.2.0` and published the package to `pkg.go.dev`.
this was on Nov 11th.

after few days I noticed something was missing, I added whatever was needed and recreated the tag `v0.2.0` on Nov 14th (deleted it and created again).

I wasn't able to update `pkg.go.dev` to show my version from Nov 14th and it keeps showing the version from Nov 11th.

how can I update it to show latest updates?

would appreciate your help.

p.s. 
I also tried publishing a new version with retract in go.mod in order to try and remove the package and then put it back.
it didn't work from some reason.

I'm the owner of this package.

**Comment by nirrozenbaum** [comment]
it took some time to update but eventually retract worked and v0.2.0 was removed.
now I'm trying to republish it.
it all works ok I'll close this issue

**Comment by nirrozenbaum** [comment]
unfortunately, now not only am I not able to update the doc, after trying to retract the packages I cannot push the tag again.
is it possible to just remove my package and I'll publish it again?

**Comment by artyom** [comment]
@nirrozenbaum I think that given how modules [proxy/sumdb](https://sum.golang.org) work, you cannot re-publish the modified module using the *exact same version* after it already made its way to the sumdb, as at that point it can be already used by someone.

The expected workflow is to publish a new version that retracts the previous broken release. So what you describe here as a bug is an intended behavior.

Please see this blog post, specifically the “Module Retraction” section <https://go.dev/blog/go116-module-changes#module-retraction>:

> [...] To keep module builds deterministic, a version cannot be modified after it is published. Even if you delete or change a version tag, proxy.golang.org and other proxies probably already have the original cached. [...]

It provides more details on the suggested workflow (publishing a new version).

**Comment by jamalc** [comment]
Thanks for the explanation, @artyom!
