### ISSUE TITLE
x/website/tour: using the Format button prints "[object Object]"

### ISSUE THREAD

**Issue by nishanths** [golang/go#49746]
I visited the "A Tour of Go" website at https://go.dev/tour/welcome/1. Then I clicked on the Format button next to the code editor. I expected to see either a human-readable error (if formatting failed) or no feedback (if formatting succeeded). But the output was:

```
[object Object]
```

Note that this happens regardless of whether or not the file has syntax errors. 

### Screenshot

![Screen Shot 2021-11-23 at 10 42 48 AM](https://user-images.githubusercontent.com/6028224/142974394-effeffd4-5930-4812-b2d7-7bcb2f98fc9f.png)

**Comment by seankhliao** [comment]
cc @rsc

**Comment by esote** [comment]
It's making a POST request to `/fmt`, but for go.dev that gives 404

**Comment by rsc** [comment]
Thanks. It should be using /_/fmt. Will fix.
