### ISSUE TITLE
x/website: Support gotip in playground

### ISSUE THREAD

**Issue by icholy** [golang/go#49758]
### What did you do?

Navigated to https://go.dev/gotipplay/

### What did you expect to see?

Something equivalent to: https://gotipplay.golang.org/

### What did you see instead?

open gotipplay: file does not exist

**Comment by seankhliao** [comment]
This is already in progress in [CL 366056](https://go.dev/cl/366056)

**Comment by icholy** [comment]
@seankhliao is there another issue tracking that work?
