### ISSUE TITLE
x/website: anchor links don't seem to work properly anymore

### ISSUE THREAD

**Issue by mvdan** [golang/go#49754]
I think this is a regression from when golang.org was replaced by go.dev in the past week or so.

If I go to https://go.dev/ref/spec#Order_of_evaluation on either Firefox 94.0.2 or Chrome 96.0.4664.45, the anchor link doesn't seem to be working properly, as I don't see the heading I linked to unless I scroll back up.

I imagine this might be related to the banners at the top, as they are what is blocking the view.

![image](https://user-images.githubusercontent.com/3576549/143062037-c000c9e1-2c31-4d41-aa15-53758b05318d.png)

Here is roughly what I expected to see:

![image](https://user-images.githubusercontent.com/3576549/143062134-a57f5c5e-85d8-41d0-95b4-7984f1e01008.png)

cc @dmitshur

**Comment by dmitshur** [comment]
CC @jamalc, @rsc.

**Comment by rsc** [comment]
Thanks. The problem is the floating header. It seems OK to me for now to just unfloat the header.
