### ISSUE TITLE
cmd/link: occasional failures with "unreachable sym in relocation" since 2021-09-12

### ISSUE THREAD

**Issue by bcmills** [golang/go#49752]
`greplogs --dashboard -md -l -e ': unreachable sym in relocation: '`

[2021-11-22T23:00:32-0244343/freebsd-amd64-13_0](https://build.golang.org/log/70f6697b676fd160422c61b188fb8f571de574c1)
[2021-11-19T21:57:03-6027b21/freebsd-amd64-13_0](https://build.golang.org/log/0843789b56a607842eb2386b6b8b0f26838c6009)
[2021-11-16T19:18:26-8122e49-6c36c33/freebsd-amd64-12_2](https://build.golang.org/log/e29bf09c48aa766ca8d6b7843df1e855cb2a1be8)
[2021-09-12T01:06:53-0d8a4bf/linux-riscv64-unmatched](https://build.golang.org/log/a58d8584ed523448c15befd6a2ba699886f59811)

CC @cherrymui @thanm

**Comment by thanm** [comment]
Not really sure what to do with this bug, given the failure mode. Normally I would lease a builder and run some test or set of tests in a loop to try to reproduce -- in this case, even if I were able to reproduce it a few times, what then?  I don't see any commonality in terms of the symbols that are suddenly being switched from reachable to unreachable.

**Comment by bcmills** [comment]
> Maybe it is due to memory corruption somewhere?

“possible memory corruption on FreeBSD” is #46272, open since May. 😩

Still, it seems odd to me that this particular failure mode doesn't show up in the logs until recently. Maybe the memory corruption has a non-trivial interaction with the 1.18 GC changes? (Perhaps the corruption is triggered by having the GC active during some step of the linking process?)

**Comment by thanm** [comment]
Just out of curiosity, how far back does "greplogs" go? What's the oldest log that it will fetch?

**Comment by bcmills** [comment]
Depends on what you've downloaded with `fetchlogs`. (It looks like my semi-arbitrary database for the main repo currently goes back to 2019-06-06.)

**Comment by toothrot** [comment]
Checking on this as a release blocker. Are there any updates? @thanm

**Comment by cherrymui** [comment]
Still look like memory corruption. Seems no new failure occurred since 11-22. Haven't tried to reproduce.

**Comment by thanm** [comment]
I kicked off a goswarm on freebsd-amd64-12_2 this morning trying to reproduce the issue. I'll leave it running for a day or two and see if that catches any new instances of the bug. I tried to do something similar for an AMD-specific VM (e.g. netbsd-amd64-9_0-n2d) but all.bash crashes almost immediately there (most of the time doesn't make it past the bootstrap).

**Comment by thanm** [comment]
OK, it took a while, but the swarm I started this morning did find a new instance of this problem on tip with freebsd-amd64-12_2 just now, so it definitely looks like this bug is alive and kicking.

**Comment by thanm** [comment]
Related: https://github.com/golang/go/issues/46272#issuecomment-991981762. I will retest this bug once we have an updated version of FreeBsd on our builders with the fix.

**Comment by thanm** [comment]
I ran a goswarm test (using the updated freebsd-amd64-13_0 builder image to include the [fix](https://github.com/freebsd/freebsd-src/commit/1d6ebddb62bc18833b21a15f8e7eb86102140100)) and did not detect any new failures over the course of a 40 hour run with 10 gomotes, so I am going to go ahead and close out this bug. See #46272 for more details on the kernel problem and the fix.
