### ISSUE TITLE
x/website: clicking "share" on the playground reloads the entire page

### ISSUE THREAD

**Issue by mvdan** [golang/go#49766]
I'm fairly sure this did not happen with the old play.golang.org - it would simply update the URL in the browser bar and in the "share" textbox, but it wouldn't reload the entire page.

I don't lose any code with the reload, but it's still slightly distracting. Particularly since the code takes nearly a second for me to fully render again, so the site becomes unusable while it's doing the presumably unnecessary reload.

**Comment by mvdan** [comment]
Switching between the built-in examples sort of has the opposite problem. The code does change without a full reload, but the URL doesn't change, so it remains on whatever URL I got from my last click of "share".

**Comment by nishanths** [comment]
Similar: https://github.com/golang/go/issues/49742.

But that issue doesn't mention the problem described in the [first comment here](https://github.com/golang/go/issues/49766#issuecomment-977205187):

> Switching between the built-in examples sort of has the opposite problem. The code does change without a full reload, but the URL doesn't change, so it remains on whatever URL I got from my last click of "share".

**Comment by zikaeroh** [comment]
Yes, apparently I didn't notice that the whole page actually reloaded and assumed it was some sneaky history modification in my issue. It definitely reloads everything and removes the output.
