### ISSUE TITLE
x/website: download button only knows about macOS and Windows

### ISSUE THREAD

**Issue by cespare** [golang/go#49765]
### What is the URL of the page with the issue?
 
https://go.dev/, for example
 
### What is your user agent?
 
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
```
 
 ### Screenshot
  
![screen_20211123133124](https://user-images.githubusercontent.com/318501/143132577-c10d771f-322b-4c9b-bc13-2564fd5598cf.png)
 
### What did you do?
 
Clicked the download button on the front page using a Linux machine
  
### What did you expect to see?
 
 A Linux tarball
 
### What did you see instead?

A Windows MSI

Reported on Twitter by @dominikh.

**Comment by mvdan** [comment]
I can reproduce. How was the new website tested against the old site for regressions? There's also https://github.com/golang/go/issues/49754, for example.

**Comment by rsc** [comment]
This is not a regression.
This part of https://go.dev/ has been like this for a very long time.
People are just paying more attention to it now.
Will fix.

**Comment by mvdan** [comment]
I meant regression as in: new users navigating to golang.org on Linux no longer get a Linux download button by default :)

**Comment by rsc** [comment]
Indeed. It's much worse that go.dev has always been like that!
