### ISSUE TITLE
cmd/go: workspace-mode graph pruning needs to follow upgraded roots

### ISSUE THREAD

**Issue by bcmills** [golang/go#49763]
In [CL 362754](https://golang.org/cl/362754) we added a `workspace` graph-pruning mode, to fix a bug that we identified through code review (added in the `work_prune` test script in that CL).

I've been thinking some more about that scenario, and I've identified a related problem arising from the interaction between workspaces and graph pruning.

The module graph in that example has edges like:
```
example.com/a -> example.com/b v1.0.0 -> example.com/q v1.1.0
example.com/p -> example.com/q v1.0.0
```

But what if `example.com/q` itself has edges to new, not-previously-imported dependencies?
```
example.com/q v1.1.0 -> example.com/r v1.0.0
```
With current workspace pruning semantics, that edge will be pruned out: it is pruned out of `a`'s dependency graph (because it is not relevant to any package imported by `a`), and it is not present in `b`'s dependency graph (because `b` requires a different version of `q` entirely).

The result is that `a` by itself may be tidy, and `p` by itself may be tidy, but loading the dependencies of `p` from the combined module graph is missing a dependency.

**Comment by bcmills** [comment]
Bah, typos.

**Comment by bcmills** [comment]
Another possible fix is to change the workspace pruning mode to do the expansion itself: after each round of loading from the roots, re-enqueue the selected version of each root if that version's dependencies have not yet been loaded.
(That would take the form of an extra condition and perhaps another layer of looping [in `modload.readModGraph`](https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/modload/buildlist.go;l=384-387;drc=master).)

If we end up encountering a spiral of upgrades, that doesn't allow us to prune out as many intermediate versions, but it does allow us to avoid reloading the graph multiple times — and <em>upgrade</em> spirals seem like they will be fairly short in practice and are relatively easy for the user to cut off by running `go work sync`.

CC @matloob

**Comment by cherrymui** [comment]
Any updates on this? Thanks. (checking in as this is a release blocker.)

**Comment by bcmills** [comment]
We pair-programmed this today (in CL 370663), and if it passes in the longtest builders it should resolve this issue for the release.
