### ISSUE TITLE
x/pkgsite: "gopkg.in/yaml.v2" is not a valid import path - 400 error

### ISSUE THREAD

**Issue by bbossola** [golang/go#49762]
### What is the URL of the page with the issue?
https://pkg.go.dev/gopkg.in/yaml.v2 
  
### What is your user agent?
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Screenshot
![image](https://user-images.githubusercontent.com/186370/143092887-b9ac84dc-50bc-419c-9510-828a378f3489.png)
 
### What did you do?
Just trying to get info on the package. Fails consistently every time. 

### What did you expect to see?
The summary page of the package
 
### What did you see instead?
A 400 error, as reported in the screenshot

**Comment by bbossola** [comment]
The same happens with:
https://pkg.go.dev/gopkg.in/validator.v2

**Comment by bbossola** [comment]
And of course also this:
https://pkg.go.dev/gopkg.in/yaml.v3

**Comment by bbossola** [comment]
Please note that this is a regression. Until yesterday, everything was working correctly.

**Comment by seankhliao** [comment]
cc @jba

**Comment by jba** [comment]
Fix deployed.
