### ISSUE TITLE
My cgo code can not free memories that malloced by c code that is compiled by a msvc compiler

### ISSUE THREAD

**Issue by molechen0728** [golang/go#49775]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
not sure.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env  
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPROXY=https://goproxy.io,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.2
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build413436447=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

On linux, my cgo code can free the memories whether they are malloced by my code or code .
But on windows , i can not free the memories that are not malloced by my cgo code and c can not free that i malloced.

### What did you expect to see?
I want to know why.

### What did you see instead?
if i free the wrong memories  ,program breaks.

**Comment by davecheney** [comment]
@molechen0728 please provide a runnable program that demonstrates the problem. Thank you.

**Comment by molechen0728** [comment]
[https://github.com/molechen0728/cgo49775](url)
[https://github.com/molechen0728/cpp49775](url)
@davecheney

**Comment by davecheney** [comment]
Can you please double check, that doesn’t appear to be a Go program. If you can work to reduce your sample program to the smallest examples that demonstrates the issue, that will improve the chances that someone can help.

**Comment by molechen0728** [comment]
It is a cgo program.

**Comment by molechen0728** [comment]
It is a cgo program. @davecheney

**Comment by AlexRouSg** [comment]
If you malloc from inside a dll, you must free from inside the same dll. 
As for why ... this explains it a little: https://devblogs.microsoft.com/oldnewthing/20161209-00/?p=94905
