### ISSUE TITLE
x/tools/gopls: fix analyzers.md formatting for generics code

### ISSUE THREAD

**Issue by hyangah** [golang/go#49774]
[infertypeargs](https://github.com/golang/tools/blob/1c35f2a5d7d38aa0d042c2835c404f744581bdf2/gopls/doc/analyzers.md#infertypeargs) analyzer documentation includes generics code snippet. The formatting is broken.

**Comment by findleyr** [comment]
Thanks, I hadn't noticed. Will fix.
