### ISSUE TITLE
cmd/go: "mod tidy" doesn't delete go.sum when go.mod has no dependencies

### ISSUE THREAD

**Issue by TwiN** [golang/go#49772]
It's not really a big deal, but I occasionally find myself having to manually delete `go.sum` files after removing all external dependencies from a project.

## Steps to Reproduce
1. Create a project
2. Add an external dependency 
3. Execute `go mod vendor`
4. Note how `go.sum` has been created
5. Remove the external dependency from the code
6. Execute `go mod tidy`
7. Note how the `go.sum` file is now empty.

Conversely, if you had never added an external dependency and executed `go mod vendor`, `go.sum` would have never been created, and the following error would have been displayed instead:
```console
go: no dependencies to vendor
```

https://github.com/golang/go/blob/1ac45e026b2cbae91e3495e2cc6e93b6d505b4f4/src/cmd/go/internal/modcmd/vendor.go#L190-L193

**Comment by heschi** [comment]
cc @matloob @bcmills

**Comment by dmitshur** [comment]
I suspect this is the same as #36236. (Please comment otherwise.)
