### ISSUE TITLE
x/tools/gopls: reports incorrect type for cgo errno value

### ISSUE THREAD

**Issue by minty99** [golang/go#49777]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
not sure

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/andrew/Library/Caches/go-build"
GOENV="/Users/andrew/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/andrew/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/andrew/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zd/drxy0rp51t9230whvm__wfb00000gn/T/go-build245735751=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I wrote this program to test error handling in cgo,
```go
package main

/*
#include <stdio.h>
#include <errno.h>

int f(int n) {
	errno = 1;
	return n * 100;
}
*/
import "C"
import "fmt"

func main() {
	ans, err := C.f(C.int(100))
	fmt.Println(ans)
	fmt.Println(err)
}
```

### Bug
I found the language server says type of `err` is `bool`. It actually is `syscall.Errno`.
I am using VSCode editor and I know this can be problem of vscode plugin, but I don't have knowledge to check what tool is buggy, so I report here first.
<img width="247" alt="Screen Shot 2021-11-24 at 1 57 12 PM" src="https://user-images.githubusercontent.com/3724119/143177505-61638e86-d532-4cf8-a083-76d2fb6b8ad4.png">

**Comment by findleyr** [comment]
Hi, thanks for reporting, and sorry for the breakage. This was a regression in Go 1.17: #47854, fixed in Go 1.17.1.  You can fix it by updating your Go version.
