### ISSUE TITLE
cmd/compile: allow methods implemented in assembly

### ISSUE THREAD

**Issue by MichaelTJones** [golang/go#4978]
<pre>It is presently not possible to create methods via assembler. I want to do just this.
Rather than think of this as a request for a new feature (and thus not suitable for Go
(1.1) could we think of it as a flaw in the present code, a defect therefore, and thus
suitable.</pre>

**Comment by nightlyone** [comment]
An alternative Idea would be to define this as a special case of inlining. Then as a first implementation turn the call into an immediate jump under the following conditions:
* no code is coming before and after the call from the method to the asm function
* the asm function has the same signature as the method but additionally accepts the receiver as the first argument.

The debug story is still unclear to me then as the only statement from the enclosing method would be the jump.

**Comment by rsc** [comment]
At this point, we've survived for a very long time without a way to write methods directly in assembly, and we've also successfully hidden the ABI for methods, and changed it over time. This is good and probably should not be undone. See also #27539.
