### ISSUE TITLE
x/tools/gopls: include Go version information in `gopls version` output

### ISSUE THREAD

**Issue by findleyr** [golang/go#49783]
As discussed in [CL 366736](https://golang.org/cl/366736), `gopls version` lacks information about the Go version used to build gopls (and possibly the Go version found by `exec.LookPath`). We should add it, to facilitate bug reporting.

CC @hyangah

**Comment by hyangah** [comment]
In case `gopls version` output format changes significantly, we need to adjust vscode-go's [gopls version parsing code](  https://github.com/golang/vscode-go/blob/6448e9df4db928fc73e5be153bf559581a3563ae/src/goLanguageServer.ts#L1215) and release vscode-go first.

**Comment by findleyr** [comment]
> In case gopls version output format changes significantly, we need to adjust vscode-go's gopls version parsing code and release vscode-go first.

If this is being parsed, maybe we should just add a `-json` flag? WDYT?

**Comment by hyangah** [comment]
I think `vscode-go` should stop parsing `gopls version` result but use `go version -m` as part of managing versions of all tools. :-) 

And I guess you may want to include the go version to the verbose output (`gopls -v version`) only.

**Comment by findleyr** [comment]
> I think vscode-go should stop parsing gopls version result but use go version -m as part of managing versions of all tools. :-)

Oh yeah, that sounds correct.

> And I guess you may want to include the go version to the verbose output (gopls -v version) only.

Yes, I think this should be `-v` only. We'll ask people to invoke `gopls -v version` in the issue template.

**Comment by hyangah** [comment]
As discussed in #50085, the plan for utilizing `go version -m` cannot work unless the editor always chooses the latest go version the user ever used. It seems like `-json` based on `runtime/debug.ReadBuildInfo` is the best option for now (assuming it's unlikely runtime/debug.ReadBuildInfo format changes significantly in the future).

**Comment by hyangah** [comment]
Closing (ended up implementing `-json` flag in cl/382274 too)
