### ISSUE TITLE
x/pkgsite: WTFPL Is not recognized

### ISSUE THREAD

**Issue by azer** [golang/go#49781]
I use WTFPL in nearly all my packages, and pkg.go.dev website doesn't show documentation due to its whitelisted license list missing WTFPL.
 
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/azer/crud/v2#section-documentation 
 

### What did you expect to see?
 
 Documentation of my WTFPL-licensed package
 
### What did you see instead?

Error: Documentation not displayed due to license restrictions.

See our license policy.

**Comment by seankhliao** [comment]
See https://github.com/golang/go/issues/36840#issuecomment-652926329
