### ISSUE TITLE
x/website: in certain browsers/scenarios, pressing [return] in playground editor does not move cursor to next line

### ISSUE THREAD

**Issue by nishanths** [golang/go#49794]
### What is the URL of the page with the issue?
 
 https://go.dev/play
 
### What is your user agent?
 

 
 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
 
#### Scenario 1

![Screen Shot 2021-11-25 at 5 40 02 PM](https://user-images.githubusercontent.com/6028224/143439346-99a40e23-37b3-4716-b61d-3793abb09002.png)

#### Scenario 2
 
![Screen Shot 2021-11-25 at 5 39 40 PM](https://user-images.githubusercontent.com/6028224/143439368-1be7222f-3ced-4394-9f32-52aaa75d1f1b.png)

### What did you do?
 
- Visited URL mentioned above.
- Move cursor to line 10, either using mouse or keyboard.
- Enter the text `type A struct {` (scenario 2 only).
- Press <kbd>return</kbd> on keyboard.
 
### What did you expect to see?
 
 Expected cursor to move to line 11.
 
### What did you see instead?

No change in cursor position.

### Extra notes

These are illustrative of the scenarios I can reliably reproduce the bug. There may or may not be more scenarios. Note that I was using Safari 15.1 on macOS 12. The issue didn't exist in Chrome. I didn't try other browsers.

**Comment by seankhliao** [comment]
Interesting, I can reproduce this on safari

**Comment by seankhliao** [comment]
cc @rsc

**Comment by rsc** [comment]
Seems to only happen on the very last line of the textarea, and only in Safari. Will dig into it.
