### ISSUE TITLE
$GOPATH/src error not letting me import external packages

### ISSUE THREAD

**Issue by John8790909** [golang/go#49797]
I keep on seeing this when ever I try to import a external package (go graphql, mux, etc..)

here is the vscode popup I keep getting:

Error loading workspace: You are outside of a module and outside of $GOPATH/src. If you are using modules, please open your editor to a directory in your module. 

I am on macOs btw can someone help me with this there is nothing on the internet about this

**Comment by seankhliao** [comment]
please see https://github.com/golang/vscode-go#setting-up-your-workspace

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
