### ISSUE TITLE
go get is downloading a large vcs cache and does not succeed

### ISSUE THREAD

**Issue by categorical** [golang/go#49793]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes. It is the latest stable version downloaded from https://go.dev/dl/ 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=d:\godev\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=d:\godev
set GOPRIVATE=
set GOPROXY=direct
set GOROOT=D:\opt\golang
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\opt\golang\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=D:\cygwin64\tmp\go-build106806973=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I typed in `go get -v github.com/go-delve/delve/cmd/dlv` to terminal
In addition, I have environment variables set for git to use an http proxy
```
http_proxy=http://123.23.3.123:12321
https_proxy=http://123.23.3.123:12321
HTTP_PROXY=http://123.23.3.123:12321
HTTPS_PROXY=http://123.23.3.123:12321
```

### What did you expect to see?

I expected to see `dlv` installed to `$GOPATH/bin`

### What did you see instead?
`go get` does not finish downloading, and errors out until probably when a network issue occurs
```
get "golang.org/x/image": found meta tag vcs.metaImport{Prefix:"golang.org/x/image", VCS:"git", RepoRoot:"https://go.googlesource.com/image"} at //golang.org/x/image?go-get=1
go get: github.com/go-delve/delve@v1.7.3 requires
        golang.org/x/tools@v0.1.8-0.20211028023602-8de2a7fd1736: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in d:\godev\pkg\mod\cache\vcs\7d9b3b49b55db5b40e68a94007f21a05905d3fda866f685220de88f9c9bad98a: exit status 128:
        error: 1461 bytes of body are still expected
        fatal: the remote end hung up unexpectedly
        fatal: early EOF
        fatal: index-pack failed
        warning: unable to unlink '(NULL)': Invalid argument
```
The `$GOPATH/pkg/mod/cache` directory looks like
```
$ du -sh *
9.4M    download
2.6G    vcs
```

I would like to know how to let it work with `GO111MODULE=on` and `GOPROXY=direct`.
Am I expected to see 2.6GiB (and ever increasing) of vcs cache in this case when installing `dlv`?

**Comment by categorical** [comment]
If I have `export GO111MODULE=off`, `go get` works fine by downloading the (54MiB) repository to `$GOPATH/src`.
`go install -v github.com/go-delve/delve/cmd/dlv@latest` was also tried resulting in the same problem.

**Comment by seankhliao** [comment]
What happens if you run `git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/*` in `d:\godev\pkg\mod\cache\vcs\7d9b3b49b55db5b40e68a94007f21a05905d3fda866f685220de88f9c9bad98a` ?

Note `pkg/mod/cache` is shared between everything that uses modules, not just this download

**Comment by seankhliao** [comment]
Tested this a bit and it looks like it's gopkg.in that's responding with server errors (ex 502 gateway errors)

**Comment by categorical** [comment]
The contents of the `cache/vcs` directory prior to `fetch`
```
$ du -s *|sort -n
4475    f1a8947fc1d98b87c6b2c048a81f70bc053e6e153096874a89819e1648e7b424
6132    1ba9cdedc663bd56a9687f5910f19e1ac5f7f472742441d370be599c409f87ec
6268    586d5e7bca434975f7910822954cf30664ba773297d33ecb5b66a7a6fdce25f3
6365    f72f7a6f267d2fe79b1e174efab21a591b07c84ef53364f65b8281fda7000b49
6570    879ce674f4d9f0a3a3f207a6503e782bb2113f1a3d0c1f8049cc523b96d9aa9e
7360    352eeab4f93e570632f9ece323fff86316be4bfcafd6c7231b69c0e8eebdd7b7
9066    3f44b113f6f35a158c08e5a21a9459e1b3e4e06a624ea800c3427641921b0e90
9255    09e416c991289a13aad7de4337bb96bc98ab89763cc18ac2f790771787c60ed5
11313   ed42bd05533fd84ae290a5d33ebd3695a0a2b06131beebd5450825bee8603aca
11637   8ce8c8474615d5c812f8c00ea4d3d17e65a044e13e4ded714ba67b0d574d973b
21215   da0444fc0003f84a590bd6521553c0531086778bca13ec63ace9e0dd258f4b51
21223   3b32abd765c055e8e34032d314be76dd548e10a3ca96aef4091adff372254b07
38876   14bb952cc8902e20fb82cb08a9d29b90b010f5d6d0d3737e9cb402b3b57a25b5
53171   38515699458adac9c8b61a0b44f9ad7a5f6edd7bcc2d7fae95930ec78f71e1b4
786013  461a63b9772f509ad6dbec285b16bb3603d20cbf5b324c1b0b97e0527058b46e
1569477 7d9b3b49b55db5b40e68a94007f21a05905d3fda866f685220de88f9c9bad98a
```
1st `fetch`
```
$ git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/*
Receiving objects:  16% (9716/60721), 3.38 MiB | 237.00 KiB/s
```
```
$ git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/*
error: 1562 bytes of body are still expected MiB | 254.00 KiB/s
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
warning: unable to unlink '(NULL)': Invalid argument
```
2nd `fetch`
```
$ git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/*
error: 1562 bytes of body are still expected MiB | 240.00 KiB/s
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
warning: unable to unlink '(NULL)': Invalid argument
```
`7d9b3b49b55db5b40e68a94007f21a05905d3fda866f685220de88f9c9bad98a`'s size has increased
```
$ du -s *|sort -n
6570    879ce674f4d9f0a3a3f207a6503e782bb2113f1a3d0c1f8049cc523b96d9aa9e
7360    352eeab4f93e570632f9ece323fff86316be4bfcafd6c7231b69c0e8eebdd7b7
9066    3f44b113f6f35a158c08e5a21a9459e1b3e4e06a624ea800c3427641921b0e90
9255    09e416c991289a13aad7de4337bb96bc98ab89763cc18ac2f790771787c60ed5
11313   ed42bd05533fd84ae290a5d33ebd3695a0a2b06131beebd5450825bee8603aca
11637   8ce8c8474615d5c812f8c00ea4d3d17e65a044e13e4ded714ba67b0d574d973b
21215   da0444fc0003f84a590bd6521553c0531086778bca13ec63ace9e0dd258f4b51
21223   3b32abd765c055e8e34032d314be76dd548e10a3ca96aef4091adff372254b07
38876   14bb952cc8902e20fb82cb08a9d29b90b010f5d6d0d3737e9cb402b3b57a25b5
53171   38515699458adac9c8b61a0b44f9ad7a5f6edd7bcc2d7fae95930ec78f71e1b4
786013  461a63b9772f509ad6dbec285b16bb3603d20cbf5b324c1b0b97e0527058b46e
1634869 7d9b3b49b55db5b40e68a94007f21a05905d3fda866f685220de88f9c9bad98a
```
I have `pkg/mod/cache` cleared a few times for this already,
either using `go clean -modcache` or `rm`, and I watched its size grow from 0 while `go get` is downloading,
so I believe its size is all for this download, though I repeated this `go get` a few times as well upon failures, and it might be cumulative.

**Comment by seankhliao** [comment]
If it's errors with git cloning, then there's not much `go` can do for you (unless you set GOPROXY and download zips over HTTP).
