### ISSUE TITLE
ponies: Chromium support

### ISSUE THREAD

**Issue by gopherbot** [golang/go#498]
by **danielheres**:

<pre>How about support code in &lt;script type=&quot;text/go&quot;&gt; in Chromium? Are there
any 
plans?</pre>

**Comment by rsc** [comment]
Moving priority-someday to the Unplanned milestone.

**Comment by bradfitz** [comment]
This can be closed now I think.

https://github.com/gopherjs/gopherjs is a thing and works pretty well.

Tracking bug for WebAssembly support is #18892
