### ISSUE TITLE
A Doubt about Func Sort of Package Sort 

### ISSUE THREAD

**Issue by NikhilSharmaWe** [golang/go#49807]
[Link](https://go.dev/play/p/MLLet0RpsAW) to the code

At line 14 I have used type sort.StringSlice type as an argument for sorting a string of slice, it works. 
`sort.Sort(sort.StringSlice(studyGroup))`

But in line 18 when I use  sort.StringSlice type as a reciever the function works in that case too. 
`sort.StringSlice(s).Sort()`

**What is the reason behind this kind of behavior**

### What version of Go are you using (`go version`)?

<pre>
Using Go Playground for this code

</pre>

### Does this issue reproduce with the latest release?

[Code](https://go.dev/play/p/MLLet0RpsAW)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?
I expected to see error for `sort.StringSlice(s).Sort()` case because the function Sort is defined as
 `func Sort(data Interface) {
        n := data.Len()
	quickSort(data, 0, n, maxDepth(n))
}`

### What did you see instead?
But the both the cases worked and sorted []string

**Comment by seankhliao** [comment]
`sort.Sort` and `sort.StringSlice.Sort` (which uses `sort.Sort`) are different things.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by NikhilSharmaWe** [comment]
@seankhliao I did not knew about that, apologies for the inconvenience.
