### ISSUE TITLE
database/sql if err == nil set needReset = true

### ISSUE THREAD

**Issue by mopo3ilo** [golang/go#49809]
If error == nil then the needReset set true and each db.Exec reseted session
<pre>
$ go version go1.17.3 linux/amd64
</pre>

https://github.com/golang/go/blob/bf88adadac9bbb1b190ba7af1010373823dabb06/src/database/sql/sql.go#L528-L530

https://github.com/golang/go/blob/bf88adadac9bbb1b190ba7af1010373823dabb06/src/database/sql/sql.go#L1445-L1450

**Comment by seankhliao** [comment]
What's the problem with that?
From the [CL that added it](https://go.dev/cl/73033):
> Most sessions have a way to reset the session state which is desirable to prevent one bad query from poisoning another later query with temp table name conflicts or other persistent session resources.

**Comment by mopo3ilo** [comment]
> What's the problem with that? From the [CL that added it](https://go.dev/cl/73033):

Example:
Parallel gorutines, in each first Exec create temporary tables, next execs use this tables and update data in db

**Comment by seankhliao** [comment]
That;s not safe, use `DB.Conn` if you need sessions

**Comment by mopo3ilo** [comment]
> That;s not safe, use `DB.Conn` if you need sessions

You do not understand me. Maybe a code example will help.

```go
func main() {
	wg := &sync.WaitGroup{}
	wg.Add(3)

	for i := 0; i < 3; i++ {
		go func(i int) {
			defer wg.Done()

			db, err := sql.Open("sqlserver", uri)
			if err != nil {
				return
			}
			defer db.Close()

			_, err = db.Exec("create table #tmp1(col int primary key)")
			fmt.Println(i, err)

			_, err = db.Exec("insert into #tmp1(col) values(@val)", sql.Named("val", i))
			// ^^^ session reseted, get error mssql: Invalid object name '#tmp1'.
			fmt.Println(i, err)
		}(i)
	}

	wg.Wait()
}
```
