### ISSUE TITLE
x/website: change title of landing page to "The Go Programming Language"

### ISSUE THREAD

**Issue by fzipp** [golang/go#49812]
The title of the new website's landing page is "go.dev". The title of the old website was "The Go Programming Language". The title shows up in bookmarks, the browser history and search engine results, and I think the more descriptive old title was better.
 
### What is the URL of the page with the issue?
 
https://go.dev/ 
 
### What did you expect to see?
 
"The Go Programming Language" 
 
### What did you see instead?

"go.dev"

### Screenshot

<img width="727" alt="go-issue-49812" src="https://user-images.githubusercontent.com/598327/143669032-643bdb0d-b238-4a68-9492-ade4abe68555.png">

**Comment by mknyszek** [comment]
CC @dmitshur
