### ISSUE TITLE
net/http: *http.Request RemoteAddr returns "@"(at sign) when HTTP server serving on unix listener

### ISSUE THREAD

**Issue by sunshineplan** [golang/go#49825]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=%USERPROFILE%\AppData\Local\go-build
set GOENV=%USERPROFILE%\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=%USERPROFILE%\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=%USERPROFILE%\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=%USERPROFILE%\Desktop\test\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=%USERPROFILE%\AppData\Local\Temp\go-build2198432139=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
```go
package main

import (
	"bufio"
	"context"
	"io"
	"log"
	"net"
	"net/http"
	"os"
)

const (
	network = "unix"
	address = "unix"
)

var srv = new(http.Server)

func main() {
	server()
	client()
	srv.Shutdown(context.Background())
	os.Remove(address)
}

func server() {
	listener, err := net.Listen(network, address)
	if err != nil {
		log.Fatal(err)
	}

	srv.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(r.RemoteAddr))
	})
	go srv.Serve(listener)
}

func client() {
	conn, err := net.Dial(network, address)
	if err != nil {
		log.Fatal(err)
	}

	req, err := http.NewRequest("GET", "/", nil)
	if err != nil {
		log.Fatal(err)
	}
	req.Write(conn)
	br := bufio.NewReader(conn)
	resp, err := http.ReadResponse(br, req)
	if err != nil {
		conn.Close()
		log.Fatal(err)
	}
	b, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatal(err)
	}
	log.Print(string(b))
	conn.Close()
}

````
https://go.dev/play/p/zc8rsEC6Jeb
### What did you expect to see?
2009/11/10 23:00:00 unix
### What did you see instead?
2009/11/10 23:00:00 @
#https://github.com/gin-gonic/gin/issues/2962

**Comment by seankhliao** [comment]
See:
https://github.com/golang/go/blob/0fa53e41f122b1661d0678a6d36d71b7b5ad031d/src/syscall/syscall_linux.go#L506-L511

The syscall returns a null byte, "unix" would be wrong since it could be an actual path
