### ISSUE TITLE
proxy.golang.org: Please delete package github.com/ectobit/arc

### ISSUE THREAD

**Issue by acim** [golang/go#49820]
### What did you do?

I renamed my package in go.mod from github.com/ectobit/arc to go.ectobit.com/arc

Please delete github.com/ectobit/arc so that I can use go.ectobit.com/arc in pkg.go.dev and with `go get`.

**Comment by cuiweixie** [comment]
`
export GOPROXY=https://proxy.golang.org
go get -v go.ectobit.com/arc  
`
go get return success in my mac

**Comment by acim** [comment]
Oh yes, it works now.
