### ISSUE TITLE
x/pkgsite: package removal request for github.com/scottfeldman/merle

### ISSUE THREAD

**Issue by scottfeldman** [golang/go#49822]
### What is the path of the package that you would like to have removed?

github.com/scottfeldman/merle

 
 
 
### Are you the owner of this package?

Yes

 
### What is the reason that you could not retract this package instead?

On github, I renamed the project from merle to merle-orig.  I then created a new project called merle.  pkg.go.dev shows the old project contents.  I'd like to delete the old project from pkg.go.dev, and then request the new project be loaded.  Thanks.

**Comment by jamalc** [comment]
Have you tried [retracting](https://go.dev/ref/mod#go-mod-file-retract) the module already?

**Comment by jamalc** [comment]
I think I understand. If the contents of merle-orig were never published as a tagged version with the path github.com/scottfeldman/merle, pkg.go.dev will show documentation for the new contents of github.com/scottfeldman/merle after publishing a tagged version.

**Comment by scottfeldman** [comment]
Please close this issue.  It seems resolved now.  I had put a retract
statement in go.mod of the old project meroel-orig.  Today, pkg.dev.go has
reindexed on the new repo merle, so I'm happy.  Thank you. Regards
