### ISSUE TITLE
x/pkgsite: Links to code hosted on GitLab under a sub-group are invalid

### ISSUE THREAD

**Issue by mitar** [golang/go#49827]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/gitlab.com/tozd/go/errors
 
### What is your user agent?
 
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
 
### What did you do?

1. Go to https://pkg.go.dev/gitlab.com/tozd/go/errors#As
2. Click on the link function link, which points to the source code
 
### What did you expect to see?

I expected to see the source code available under `https://gitlab.com/tozd/go/errors/blob/<commit>/stdlib.go#L47`.

### What did you see instead?

I was directed to invalid `https://gitlab.com/tozd/go/blob/<commit>/errors/stdlib.go#L47`.

**Comment by mitar** [comment]
This looks correct:
```
curl -s https://gitlab.com/tozd/go/errors?go-get=1
```
```html
<html><head><meta name="go-import" content="gitlab.com/tozd/go/errors git https://gitlab.com/tozd/go/errors.git" /><meta name="go-source" content="gitlab.com/tozd/go/errors https://gitlab.com/tozd/go/errors https://gitlab.com/tozd/go/errors/-/tree/main{/dir} https://gitlab.com/tozd/go/errors/-/blob/main{/dir}/{file}#L{line}" /></head><body>go get https://gitlab.com/tozd/go/errors</body></html>
```

**Comment by jamalc** [comment]
I don't have a gitlab account and the link is behind an auth wall, can anyone else verify this issue? cc/ @jba @julieqiu

**Comment by mitar** [comment]
Sorry, what auth wall? There should be no auth wall? Project and link are public?

**Comment by mitar** [comment]
So `curl` above works for me without any authentication.

**Comment by jamalc** [comment]
My mistake, the bad URL from the function source link brought me to a Gitlab sign-in page.

**Comment by jba** [comment]
Just to be clear: this has been fixed in the source. The actual pkg.go.dev links won't work until we deploy and then reprocess the broken modules.

I'm going to reopen this until that's done.

**Comment by mitar** [comment]
Awesome! Thank you for the quick fix!

**Comment by jba** [comment]
Fixed live.
