### ISSUE TITLE
syscall: `Read` on Windows causes `internal/syscall/windows.ERROR_INVALID_PARAMETER (87)`

### ISSUE THREAD

**Issue by qianxi0410** [golang/go#49826]
### What version of Go are you using (`go version`)?

<pre>
$ go version 
go1.17.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\qianxi\AppData\Local\go-build
set GOENV=C:\Users\qianxi\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=E:\GOPATH\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\GOPATH
set GOPRIVATE=
set GOPROXY=https://goproxy.io,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\qianxi\AppData\Local\Temp\go-build1867567529=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
My code is :
```go
func readClosed(conn net.Conn) bool {
	var readClosed bool
	f := func(fd uintptr) bool {
		one := make([]byte, 1024)
		// ERR: will cause error: The parameter is incorrect.
		n, err := syscall.Read(syscall.Handle(fd), one)

		if err != nil && err != syscall.EAGAIN || err == nil && n == 0 {
			readClosed = true
		}

		return true
	}

	conn.SetReadDeadline(time.Time{})

	var rawConn syscall.RawConn
	switch v := conn.(type) {
	case *net.TCPConn:
		rawConn, _ = v.SyscallConn()
	default:
		return false
	}

	// half closed
	if err := rawConn.Read(f); err != nil {
		return true
	}

	return readClosed
}
```

### What did you expect to see?
not cause  `internal/syscall/windows.ERROR_INVALID_PARAMETER (87)`

### What did you see instead?
 `internal/syscall/windows.ERROR_INVALID_PARAMETER (87)`

**Comment by mknyszek** [comment]
CC @bufflig

**Comment by mknyszek** [comment]
CC @alexbrainman

**Comment by mattn** [comment]
The connection should be managed by I/O Completion Port APIs. So it need to wait the completion with Overlapped.

```go
package main

import (
	"log"
	"net"
	"syscall"
	"time"

	"golang.org/x/sys/windows"
)

func newOverlapped() (*windows.Overlapped, error) {
	var ov windows.Overlapped
	h, err := windows.CreateEvent(nil, 0, 1, nil)
	if h == 0 {
		return nil, err
	}
	ov.HEvent = h
	return &ov, nil
}

func readClosed(conn net.Conn) bool {
	var readClosed bool
	f := func(fd uintptr) bool {
		one := make([]byte, 1024)
		var n uint32
		ov, err := newOverlapped()
		if err != nil {
			return false
		}
		defer windows.CloseHandle(ov.HEvent)

		err = windows.ReadFile(windows.Handle(fd), one, &n, ov)
		if err != nil && err == syscall.ERROR_IO_PENDING {
			if err = windows.GetOverlappedResult(windows.Handle(fd), ov, &n, true); err != nil {
				return false
			}
		}

		if err != nil && err != syscall.EAGAIN || err == nil && n == 0 {
			readClosed = true
		}

		return true
	}

	conn.SetReadDeadline(time.Time{})

	var rawConn syscall.RawConn
	var err error
	switch v := conn.(type) {
	case *net.TCPConn:
		rawConn, err = v.SyscallConn()
		if err != nil {
			log.Fatal(err)
		}
	default:
		return false
	}

	// half closed
	if err := rawConn.Read(f); err != nil {
		return true
	}

	return readClosed
}

func main() {
	conn, err := net.Dial("tcp", "localhost:8888")
	if err != nil {
		log.Fatal(err)
	}
	println(readClosed(conn))
}
```

**Comment by qianxi0410** [comment]
thanks :D. But it still does't work for me, so i switch my os to linux, now it works.
