### ISSUE TITLE
cmd/doc: help does not seem to be accurate for the "two arguments" mode

### ISSUE THREAD

**Issue by jroimartin** [golang/go#49830]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.3 linux/amd64
</pre>

<pre>
$ go version
go version devel go1.18-0fa53e41f1 Sat Nov 27 23:29:50 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, both in the latest stable and tip.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOOS="linux"
GOARCH="amd64"
</pre></details>

### What did you do?

```
$ go doc template New
package template // import "html/template"

func New(name string) *Template
    New allocates a new HTML template with the given name.
```

### What did you expect to see? / What did you see instead?

`go help doc` shows the following information regarding running "go doc" with two arguments: 

```
When run with two arguments, the first must be a full package path (not just a
suffix), and the second is a symbol, or symbol with method or struct field.
This is similar to the syntax accepted by godoc:

        go doc <pkg> <sym>[.<methodOrField>]
```

In `go doc template New`, `template` is a suffix. However, `go doc` shows documentation for html/template's New function. Which seems to be the same behavior of calling `go doc` with one argument (i.e. `go doc template.New`). The documentation explicitly says "the first (argument) must be a full package path (not just a suffix)".

It seems to me that the documentation is outdated. Also, if I'm not wrong, nowadays `godoc` does not accept that syntax anymore, as it only provides an http server mode.

### Extra information

`findNextPackage` is called when go doc is run with two arguments:

https://github.com/golang/go/blob/0fa53e41f122b1661d0678a6d36d71b7b5ad031d/src/cmd/doc/main.go#L214-L229

and:

https://github.com/golang/go/blob/0fa53e41f122b1661d0678a6d36d71b7b5ad031d/src/cmd/doc/main.go#L378-L380

**Comment by mknyszek** [comment]
CC @mvdan via https://dev.golang.org/owners

Maybe also @rsc?

**Comment by jroimartin** [comment]
@mvdan it seems that the change was first introduced in https://github.com/golang/go/commit/e3442b4ee85a0a491e9326593c2e8fc762337337:

```
cmd/doc: search for packages in the two-arg case

When given one argument, as in

	go doc binary.BigEndian

doc would search for the package, but when given two, as in

	go doc binary BigEndian

it would not. Fix the inconsistency.
```

Actually, there is a test that tests this behavior:

https://github.com/golang/go/blob/18934e11ba6ef2b2f21f091ddf4ab6814dcf1959/src/cmd/doc/doc_test.go#L920-L966

I'll send a CL later updating the doc.
