### ISSUE TITLE
x/website: code snippets in the blog are a different font-size than content after migration

### ISSUE THREAD

**Issue by theckman** [golang/go#49833]
Hello,

I found another regression in the website after migrating golang.org to go.dev. Specifically, the code snippets in blog posts are a much smaller font size than the text of the blog post itself. This makes the snippets very hard to read, and overall creates a pretty uncomfortable aesthetic on the page.

It looks like the issue is that the `font-size` for `pre` is set to `0.83em`. It looks much better when setting it to `1.0em`.

I've attached a screenshot showing the issue:

<img width="1395" alt="Screen Shot 2021-11-28 at 14 14 28" src="https://user-images.githubusercontent.com/787332/143788129-7696e3d4-64a2-4cc0-8faf-9f53d5bb2ad8.png">

Here's what it looks like when setting the `pre` `font-size` to `1em`:

<img width="1517" alt="Screen Shot 2021-11-28 at 14 17 35" src="https://user-images.githubusercontent.com/787332/143788322-9d1bcce2-d004-4ef0-97cc-b5061e56b7d5.png">

**Comment by mknyszek** [comment]
CC @dmitshur

**Comment by rsc** [comment]
Easy fix, will mail shortly.
