### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by potano** [golang/go#49838]
### Screenshot
 

 
![image](https://user-images.githubusercontent.com/32822313/143807598-df135fc3-c156-42c9-b51e-f33f7dbe67b2.png)

 
 
### What did you expect to see?  A listing of standard-library packages:
 
![image](https://user-images.githubusercontent.com/32822313/143807880-040a9e79-5a06-4e74-8199-6c0dac7eb584.png)

 
 
### What did you see instead?  A search page for any package (standard or user-submitted) on pkg.go.dev

I have often made use of the Packages link on golang.org to search for _standard_ packages and the Documentation link to see standard documentation.  Fortunately the redesign has not screwed up the latter, but does give me a problem when I want to look for standard packages.

Investigation using the Wayback Machine gives me insight into the issue:  before November 23 the Packages link on golang.org gave a redirect to pkg.go.dev/std whereas today the link on the redirected page goes to pkg.go.dev.  So now my problem comes down to the design of your site navigation and--more fundamentally--to the design philosophies of the two sites, golang.org and go.dev.

I know that you have expended great effort into the search functionality of pkg.go.dev and have commented about this on the blog.  I never tried using it since I try hard to use only the standard library.  Now that you've instituted the redirect to go.dev the search function is all I get.  You *really* need to make a link to pkg.go.dev/std.  It could go onto the search page that currently displays at pkg.go.dev.

Others have commented on the substitution of go.dev for golang.org.  I *_really_* appreciated the design of the golang.org page for its spareness and high information-to-space ratio.  There is _way_ too much going on the go.dev page for anyone not first investigating the Go language and ecosystem.  Even the navigation links speak to this.  On golang.org the choices were Documents / Packages / The Project / Help / Blog / Play.  The new page drops The Project and Help in favor of Why Go and Get Started.  Let me give you a hint:  someone who already uses Go no longer needs Why Go or Get Started but does need links to things like forums, wiki, and mailing lists.  Where are links to those on the new site?  I have to use the Wayback Machine to find them.

If you do find it necessary to offer a site to entice new users to Go, please consider maintaining a separate site for current users looking for authoritative answers.

**Comment by ALTree** [comment]
Regarding discoverability of the standard library documentation, see  #49737, #40785. #49768 is also relevant. I think there's some work in progress to link the std page in https://pkg.go.dev/.

In general I doubt  they'll ever go back to a two-website setup... golang.org was effectively dismissed.

**Comment by seankhliao** [comment]
Closing as dup as I think the main points are covered by the linked issues
