### ISSUE TITLE
for the crypto/tls library, I used the Funciton tls.X509KeyPair() to generate the Cert. the error msg is "x509: unsupported elliptic curve".

### ISSUE THREAD

**Issue by zhanghouxin07** [golang/go#49843]
hi,

my go version is 1.16.3 in linux. (docker container environment)

for the _**crypto/tls library,**_ I used the Funciton **_tls.X509KeyPair()_** to generate the Cert. the error msg is "x509: **_unsupported elliptic curve_**".

background: the .crt & .key (means Certificates and Private Keys) is generated by openssl, which algorithm is sm2 and sm3.
the sm2 & sm3 are algorithms from a OpenSSL after modification.

**_the cert and key file can parse by our openssl command, but cannot parse by the crypto/tls library , so I want to know the golang, Does it depend on The Openssl (maybe .so lib file)  in the container?_**

thanks very much

good health

**Comment by seankhliao** [comment]
no

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
