### ISSUE TITLE
cmd/go: tip build failure on Windows when using Mercurial VCS

### ISSUE THREAD

**Issue by gjmct** [golang/go#49841]
### What version of Go are you using (`go version`)?

<pre>
go version devel go1.18-1ea4d3b Mon Nov 29 00:58:50 2021 +0000 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\gavinm\AppData\Local\go-build
set GOENV=C:\Users\gavinm\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\gavinm\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\gavinm\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\gavinm\AppData\Local\Temp\go-build401408008=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What vcs version and extensions are you running?

<details><summary><code>hg version -v</code> Output</summary><br><pre>
Mercurial Distributed SCM (version 5.9.2)
(see https://mercurial-scm.org for more information)

Copyright (C) 2005-2021 Olivia Mackall and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Enabled extensions:

  convert   internal
  gpg       internal
  hggit     external  0.10.2 (dulwich 0.19.16)
  histedit  internal
  purge     internal
  rebase    internal
  strip     internal
</pre></details>

### What did you do?
<pre>
gotip build
</pre>

### What did you expect to see?
A successful build

### What did you see instead?
<details><summary>gotip build -v<pre>
error obtaining VCS status: exit status 255
        Use -buildvcs=false to disable VCS stamping
</pre></summary>
<pre>
gotip build -v
# cd C:\Users\gavinm\Go\src\quoi.nz\jei\qrtime; hg log -l1 -T {node}:{date(date,"%s")}
** unknown exception encountered, please report by visiting
** https://mercurial-scm.org/wiki/BugTracker
** Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)]
** Mercurial Distributed SCM (version 5.9.2)
** Extensions loaded: convert, gpg, hggit 0.10.2 (dulwich 0.19.16), histedit, purge, rebase, strip
Traceback (most recent call last):
  File "hg", line 58, in <module>
  File "mercurial\dispatch.pyo", line 144, in run
  File "mercurial\dispatch.pyo", line 250, in dispatch
  File "mercurial\dispatch.pyo", line 294, in _rundispatch
  File "mercurial\dispatch.pyo", line 470, in _runcatch
  File "mercurial\dispatch.pyo", line 480, in _callcatch
  File "mercurial\scmutil.pyo", line 153, in callcatch
  File "mercurial\dispatch.pyo", line 460, in _runcatchfunc
  File "mercurial\dispatch.pyo", line 1274, in _dispatch
  File "mercurial\dispatch.pyo", line 918, in runcommand
  File "mercurial\dispatch.pyo", line 1285, in _runcommand
  File "mercurial\dispatch.pyo", line 1271, in <lambda>
  File "mercurial\util.pyo", line 1886, in check
  File "mercurial\commands.pyo", line 4735, in log
  File "mercurial\logcmdutil.pyo", line 1231, in displayrevs
  File "mercurial\logcmdutil.pyo", line 303, in show
  File "mercurial\logcmdutil.pyo", line 631, in _show
  File "mercurial\templater.pyo", line 1094, in render
  File "mercurial\util.pyo", line 1796, in increasingchunks
  File "mercurial\templateutil.pyo", line 868, in flatten
  File "mercurial\templateutil.pyo", line 1072, in runtemplate
  File "mercurial\templateutil.pyo", line 921, in evalrawexp
  File "mercurial\templatefuncs.pyo", line 73, in date
  File "mercurial\utils\dateutil.pyo", line 128, in datestr
ValueError: Invalid format string
error obtaining VCS status: exit status 255
        Use -buildvcs=false to disable VCS stamping.
</pre>
</details>

Line 128 in <code>dateutil.pyo</code> is an attempt to parse a date format template.  Working backwards into the Go code, the problem seems to be this line in <code>vcs.go</code>:

<pre>
func hgStatus(vcsHg *Cmd, rootDir string) (Status, error) {
	// Output changeset ID and seconds since epoch.
	out, err := vcsHg.runOutputVerboseOnly(rootDir, `log -l1 -T {node}:{date(date,"%s")}`)
</pre>

Which I think is caused because "%s" isn't a recognised time format directive.

Changing the line to 
<pre>
	out, err := vcsHg.runOutputVerboseOnly(rootDir, `log -l1 -T {node}:{word(0, date|hgdate)}`)
</pre>

corrects the issue on my system, but I'm not 100% sure that this is what the expected output for this function should be.  Especially as I'm not even passing fluent in Python.

**Comment by ALTree** [comment]
cc @bcmills

**Comment by mpx** [comment]
I've tested Mercurial with the buildvcs functionality from v6.0.1 (2021-11-26) back to v3 (2014-05-01). v2 breaks since `-T` is missing. However, I didn't test Windows. It looks like the strftime format string isn't supported under Windows:

```
> hg log -l1 -T {node}:{date(date,"%s")}
hg: parse error at 18: not a prefix: %
({node}:{date(date,%s)}
                   ^ here)
```

There are a few options to consider:
- Find a common mercurial date format and add separate code to parse it. Epoch was useful since the format could be shared with `git`.
- Disable mercurial/buildvcs for Windows. This might be better at this stage since Go1.18 is getting close to release.

**Comment by mpx** [comment]
Can the VCS tools be installed on the Windows builder?

It would help catch this sort of incompatibility in future.

**Comment by bcmills** [comment]
> Can the VCS tools be installed on the Windows builder?

They don't even have a working `git` at the moment. 😞

(Added a comment on #46693.)

**Comment by bcmills** [comment]
This is a release-blocker because build stamping is new as of Go 1.18 and we have a contributed fix CL anyway.

Given the narrowness of the affected platform (Windows + `hg`) and the availability of `-buildvcs=false` as a workaround, this does not need to block the next beta release.
