### ISSUE TITLE
Parsing csv with few double quotes in same column

### ISSUE THREAD

**Issue by avdept** [golang/go#49858]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.17.2

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alex/Library/Caches/go-build"
GOENV="/Users/alex/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/alex/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/alex/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.2/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/md/1xt5fqb9521fghy457rr0wnh0000gn/T/go-build1822822460=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I have a simple CSV file with few rows like provided:
`Upcoming,"Weird Al" Yankovic,Comedy,other,values`
and I was using `encoding/csv` to parse this csv. However everything after second `" being treated as continuation of initial `"`, so the rest of file actually getting parsed as a single column like `"Weird Al" Yankovic,Comedy,other,values,.....` I also used `LazyQuotes` set to `true`

### What did you expect to see?
I expected csv parser to parse `"Weird Al" Yankovic` as a column, leaving rest of data out of current column

### What did you see instead?
All data after `"Weird Al" Yankovic` was parsed as the continuation of column

**Comment by seankhliao** [comment]
`encoding/csv` follows [RFC 4180](https://tools.ietf.org/html/rfc4180), your data doesn't conform:

> Each field may or may not be enclosed in double quotes (however
       some programs, such as Microsoft Excel, do not use double quotes
       at all).  If fields are not enclosed with double quotes, then
       double quotes may not appear inside the fields.

LazyQuotes is working as intended, treating the leading quote as part of a quoted field

**Comment by avdept** [comment]
Its not about LazyQuotes, its about overall parsing. LazyQuotes didn't help there @seankhliao

**Comment by ianlancetaylor** [comment]
@avdept As the package documentation states, the package only supports the format described in [RFC 4180]( https://datatracker.ietf.org/doc/html/rfc4180). Your document does not appear to conform to that RFC.

We made that restriction because there are a vast number of slightly different CSV formats in use.  Supporting all of them would produce a complex package that would be hard to use and nearly impossible to test.

So the right way is to either adjust your input as you are doing, or to make your own copy of the package (it's only a few hundred lines) and fix it for your format.
