### ISSUE TITLE
go/types, types2: audit performance before the beta

### ISSUE THREAD

**Issue by findleyr** [golang/go#49856]
As a matter of procedure, we should do a final audit of type checker performance before the beta.  We have good reason to believe that there have not been major regressions (via compiler profiling and ongoing usage), but so much has changed that it would be good to verify some baseline numbers.

**Comment by findleyr** [comment]
CC @griesemer

**Comment by aclements** [comment]
Just FYI, we're aiming for beta 1 at the beginning of next week. @findleyr, do you feel that you can make good progress on this by then?

**Comment by findleyr** [comment]
> Just FYI, we're aiming for beta 1 at the beginning of next week. @findleyr, do you feel that you can make good progress on this by then?

Yes, the release-blocking aspect of this issue is just to do a sanity check that we don't have major unexpected performance regressions (unlikely, given usage), and that there is no obvious low-hanging fruit.  It felt like we needed an issue to track our due diligence.

**Comment by findleyr** [comment]
I have done sufficient profiling to convince myself that we have not _obviously_ regressed from 1.17, looking at CPU usage and allocations while type checking various packages.

However, along the way I found a surprising non-linearity that dominates type checking for large packages like `runtime`. CL https://golang.org/cl/369434 eliminates this non-linearity and cuts the time to type check `runtime` by 6-7x, so it would probably be worth landing it during the freeze, even though it's not strictly a regression from our previous release.

**Comment by aclements** [comment]
Since the beta is out now and it sounds like you had a chance to audit the go/types performance, should we close this bug?

**Comment by findleyr** [comment]
Thanks, yes I think we can close this now.
