### ISSUE TITLE
x/website: broken link

### ISSUE THREAD

**Issue by heschi** [golang/go#49859]
The "Inside the Go Playground" link on go.dev/play is broken.

cc @toothrot

**Comment by ianlancetaylor** [comment]
I believe this was fixed by https://golang.org/cl/367335.  That just needs to be published.  (I don't have access to the publish-website button.)

**Comment by toothrot** [comment]
I believe @dmitshur has publishing power.

**Comment by dmitshur** [comment]
The new version has been published by following [x/website/cmd/golangorg#deploying-to-golang_org](https://go.googlesource.com/website/+/refs/heads/master/cmd/golangorg/#deploying-to-golang_org). (The Website-Publish vote wasn't used the CL has already been submitted.)
