### ISSUE TITLE
cmd/test2json: output is incorrect and fails to mark tests if using `TestMain`

### ISSUE THREAD

**Issue by dsesami** [golang/go#49866]
In summary, using the JSON output format seems to not function correctly when using `TestMain()`.

Assume two tests are available:
1. `TestMain()`
2. `TestSomethingElse()`

`TestMain()` is reserved and triggers `TestSomethingElse()` with `m.Run()`. I noticed this when using a `go test` to JUnit conversion tool. Initially, I thought that the bug was in the JUnit conversion tool, but then noted that the actions outputted by the `json` flag (in other words `go tool test2json`) had changed when I added `TestMain()`:

1. If `TestMain()` passes, it does not get the `"Action": "run"` field, and it is missing the `"Test":` field in the JSON output. If it fails, it is registered as an individual test and has appropriate action fields.
2. If `TestSomethingElse()` is called from TestMain, it is missing its `"Test":` field in its JSON entirely on pass, but registers actions correctly if it fails.

Without TestMain():
```
{
  "Time":"XYZ",
  "Action":"output",
  "Test":"TestSomethingElse",
  "Output":"XYZ Test logs foo bar baz"
}
```

With TestMain() calling it:
```
{
  "Time":"XYZ",
  "Action":"output",
  "Output":"XYZ Test logs foo bar baz"
}

```

3. ### What version of Go are you using (`go version`)?

<pre>
$ go version
1.17

</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
amd64, gccgo, other not apparently relevant flags...

GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2469022733=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

You can't actually run this in the code playground, as you need to run `go tool test2json` on a compiled `go test` binary (or use the `-json` flag)

Here's some test code you can paste into your environment, it's just TestMain() and a dummy test. https://go.dev/play/p/KDtlzPW9gDU

Compile it and run the binary as `go tool test2json -t ./your_binary`.

**Comment by mknyszek** [comment]
CC @rsc as the primary person in the `git blame` for `test2json` since we don't have an entry in https://dev.golang.org/owners for it.

**Comment by seankhliao** [comment]
`TestMain` doesn't affect this.
As indicated by the `test2json` help output::
> usage: go tool test2json [-p pkg] [-t] [./pkg.test -test.v]

pass the `-test.v`  flag to include the information on the surrounding tests

**Comment by dsesami** [comment]
Looks like you're right about -test.v! However, it's super strange to me that this action field isn't added during non -test.v runs. All log lines within a test should have that "Test" field in its JSON.
