### ISSUE TITLE
x/sys/unix types generation stopped inserting holes in some structs

### ISSUE THREAD

**Issue by nshalman** [golang/go#49863]
While working on https://github.com/WireGuard/wireguard-go/pull/39
I noticed that illumos doesn't emit routing messages at certain times and looked into adding them in
https://www.illumos.org/issues/14206

While doing that I was parsing the messages using https://github.com/golang/sys/blob/master/unix/ztypes_solaris_amd64.go#L326-L339 and things weren't quite right.
As pointed out in the illumos issue, there's a hole in the struct not reflected in the golang version, but that used to be there...
It was removed in https://github.com/golang/sys/commit/9029056a598ab609e3c81aae2b8607ac1bfe02eb
You can see that it used to exist here: https://github.com/golang/sys/blob/ef85f5a75ddf8e11f81e921f785d3a6b04eefbd6/unix/ztypes_solaris_amd64.go#L331-L345

I assume this is an issue with the code generation somehow? I suppose Solaris could have diverged, but I doubt it.
CC @tklauser 

Edit to clarify:
The issue here is confusion as to whether or not golang is enforcing 32 bit alignment in these structs.
If it is, then that explains the removal of the explicit holes in the structs and this is not actually a bug.

**Comment by alanc** [comment]
Solaris has not changed the defintion of `struct rt_msghdr` since it was made 64-bit clean in 1998 for the Solaris 7 release.

**Comment by nshalman** [comment]
This is not an issue. I was getting confused with fields that are swapped between RtMsghdr and IfMsghdr structs.
The code for parsing the messages is here: http://src.illumos.org/source/xref/illumos-gate/usr/src/cmd/cmd-inet/usr.sbin/route.c?r=550b6e40#2614-2620
