### ISSUE TITLE
os: atomicity guarantees of os.File.Write

### ISSUE THREAD

**Issue by motiejus** [golang/go#49877]
### What version of Go are you using (`go version`)?

<pre>
go1.17beta1-2573-g18934e11ba
</pre>

### What did you see?

Documentation on [os#File.Write](https://godocs.io/os#File.Write) does not mention that it is atomic (that is, multiple `Write` calls will not end up with interleaved output). However, it seems to be atomic (tracing from `os.File#Write` to `poll.FD#Write` is explained in a later comment):

```
motiejus ~/code/go/src/internal/poll $ git grep -w -A3 "func.*\<Write"
fd_plan9.go:func (fd *FD) Write(fn func([]byte) (int, error), b []byte) (int, error) {
fd_plan9.go-    if err := fd.writeLock(); err != nil {
fd_plan9.go-            return 0, err
fd_plan9.go-    }
--
fd_unix.go:func (fd *FD) Write(p []byte) (int, error) {
fd_unix.go-     if err := fd.writeLock(); err != nil {
fd_unix.go-             return 0, err
fd_unix.go-     }
--
fd_windows.go:func (fd *FD) Write(buf []byte) (int, error) {
fd_windows.go-  if err := fd.writeLock(); err != nil {
fd_windows.go-          return 0, err
fd_windows.go-  }
```

As this is not described in the official documentation, it leads to misunderstandings such as [this](https://godocs.io/go.uber.org/zap/zapcore#Lock):

> <...> In particular, *os.Files must be locked before use. 

... and excessive locking: all writes in Zap are thus additionally protected via a mutex. It would make sense to [remove the lock](https://github.com/uber-go/zap/blob/v1.19.1/writer.go#L98). Removing this lock would be easier if underlying function were documented to be safe for concurrent use, and guaranteed to not interleave output.

### What did you expect to see?

Explanation that concurrent use of `os.File#Write` will not interleave output.

Am I missing a case where it isn't and there is a risk of interleaved output? If you believe it makes sense to write it down (and downstreams to rely on), I will submit a PR with a documentation change.

**Comment by robpike** [comment]
This depends on the operating system that actually implements the write system call. They might all guarantee atomicity. I suspect not, although in practice it is likely to be hard to see the property fail.

Note that none of the hits from grep above are not in the os package.

**Comment by motiejus** [comment]
> This depends on the operating system that actually implements the write system call. They might all guarantee atomicity. I suspect not, although in practice it is likely to be hard to see the property fail.

Whether the system provides it or it doesn't is a tangential issue; this one is about the golang's current runtime guarantees. Once the docs are clarified (and the runtime contract is documented), I am planning to looking into at least the Linux version whether that locking still makes sense. Like I said, that's a different one.

> Note that none of the hits from grep above are in the os package.

os package ends up in the poll package, I skipped tracing for brewity. Here are the details.

Assume POSIX, which includes [windows][windows] (plan9 calls the plain syscall, but I wasn't able to find a `write(2)` for plan9, so can't confirm it's atomicity). Here is the call path for non-plan9:

[os.File#Write][1] -> [os.File#write][2] -> [poll.FD#Write][3]

... and that's how we end up in the `poll` package. Does that explain it?

[1]: https://github.com/golang/go/blob/go1.17/src/os/file.go#L172
[2]: https://github.com/golang/go/blob/go1.17/src/os/file_posix.go#L48
[3]: https://github.com/golang/go/blob/go1.17/src/internal/poll/fd_unix.go#L261

[windows]: https://github.com/golang/go/blob/go1.17/src/os/file_posix.go#L5

**Comment by prattmic** [comment]
> > This depends on the operating system that actually implements the write system call. They might all guarantee atomicity. I suspect not, although in practice it is likely to be hard to see the property fail.
> 
> Whether the system provides it or it doesn't is a tangential issue; this one is about the golang's current runtime guarantees. Once the docs are clarified (and the runtime contract is documented).

Could you clarify, what you are looking for? It sounds like you are looking for a documented contract something like "Write may be called concurrently and will perform the entire write either before or after concurrent calls."

I believe that this statement is true as I've written it because of the write locking in internal/poll (only double-checked on unix), but we may make multiple system calls, so we cannot guarantee atomicity from the perspective of other processes which may be relevant in some cases (e.g., on Linux, writes to a pipe are atomic only up to 4096 bytes).

**Comment by motiejus** [comment]
> Could you clarify what you are looking for? It sounds like you are looking for a documented contract something like "Write may be called concurrently and will perform the entire write either before or after concurrent calls."
> I believe that this statement is true as I've written it because of the write locking in internal/poll (only double-checked on unix), 

Yes, this is exactly what I am trying to get documented. Thank you for phrasing it so succinctly.

> but we may make multiple system calls, so we cannot guarantee atomicity from the perspective of other processes which may be relevant in some cases (e.g., on Linux, writes to a pipe are atomic only up to 4096 bytes).

Which means the "tangential issue above" may not be true. But let's keep the scope to the original issue (the contract) over here.

**Comment by slrz** [comment]
> ... and excessive locking: all writes in Zap are thus additionally protected via a mutex. It would make sense to [remove the lock](https://github.com/uber-go/zap/blob/v1.19.1/writer.go#L98). Removing this lock would be easier if underlying function were documented to be safe for concurrent use, and guaranteed to not interleave output.

Even if there was such a guarantee for os.File, Zap appears to accept any old io.Writer here. Those lack not only the promise of not interleaving output, they may not even be safe to invoke concurrently at all without the risk of corrupting internal state.

I guess it's similar for a lot of these cases, although eliding the lock might still be possible for the specific case of os.File (by type-asserting).

**Comment by abhinav** [comment]
That's valid, @slrz. It would allow us to update the recommendation in Zap's docs, though. Per [zapcore.Lock](https://pkg.go.dev/go.uber.org/zap@v1.19.1/zapcore#Lock):

> Lock wraps a WriteSyncer in a mutex to make it safe for concurrent use. In particular, *os.Files must be locked before use.

If os.File guarantees that a single `Write([]byte)` will not be interleaved with another concurrent write on the same os.File, then the recommendation above, and the corresponding unnecessary locks can be dropped.

**Comment by bcmills** [comment]
> I believe that this statement is true as I've written it because of the write locking in internal/poll (only double-checked on unix), but we may make multiple system calls, so we cannot guarantee atomicity from the perspective of other processes which may be relevant in some cases (e.g., on Linux, writes to a pipe are atomic only up to 4096 bytes).

I think that is correct. (Compare https://github.com/golang/go/issues/38751#issuecomment-623678316, in which we discovered that the `(*FD).Write` calls are locked but may result in multiple `write` syscalls.)

It may also be possible for `write` syscalls to be interleaved for file descriptors that refer to the same underlying open file description (for example, if they are aliased by a `dup` or `dup2` syscall), even within a single process.

**Comment by ianlancetaylor** [comment]
Previous discussion at https://golang.org/cl/174957.

As others have noted, there are various (unlikely) cases where writes can be interleaved.  Another case I haven't seen mentioned is that concurrent calls to the WriteAt method can be interleaved.

Although the current implementation takes a write lock, it's not obvious that we want to constrain all future implementations to take a write lock, given that the write lock is not in itself enough to absolutely guarantee that writes are never interleaved.

So I don't think we should document anything here.

**Comment by motiejus** [comment]
Thanks for pointing to the original issue.
