### ISSUE TITLE
x/pkgsite: package removal request for github.com/akamai/AkamaiOPEN-edgegrid-golang/v2 @ v2.8.0

### ISSUE THREAD

**Issue by robertolopezlopez** [golang/go#49878]
### What is the path of the package that you would like to have removed?

`github.com/akamai/AkamaiOPEN-edgegrid-golang/v2` -> just version `v2.8.0`

### Are you the owner of this package?

One of the maintainers.

### What is the reason that you could not retract this package instead?

We could not use the `retract` directive because this module is still using go 1.14.

**Comment by jamalc** [comment]
We're not able to remove individual versions of a module. A version containing retractions may retract itself. Can you publish and immediately retract a new version of the module using a later go version?

**Comment by robertolopezlopez** [comment]
hi @jamalc ,

Thank you for your support. I will consult our team.

Roberto
