### ISSUE TITLE
x/build: spurious "=C:=C:\golang" in environment

### ISSUE THREAD

**Issue by bcmills** [golang/go#49882]
I noticed in https://storage.googleapis.com/go-build-log/18934e11/windows-amd64-2016_977b0eeb.log (a TryBot run on Windows) that the Windows builder environment includes a bogus entry that begins "=C:=C:\golang":

<pre>
:: Running C:\workdir\go\bin\go with args […] and env ["GOBUILDEXIT=1" <strong>"=C:=C:\\golang"</strong> "ALLUSERSPROFILE=C:\\ProgramData" […]
</pre>

This appears to be a very old bug: the earliest occurrence of it I can find dates to 2018:

[2018-12-19T22:59:49-e147a91-f500f13/windows-amd64-2016](https://build.golang.org/log/d722acb34eeaf54b5c740527f84223a7d7e2a9e1)

But even that may just be a reflection of the extent of my `fetchlogs` database rather than the extent of the bug.

**Comment by mknyszek** [comment]
CC @dmitshur @cagedmantis

**Comment by bcmills** [comment]
According to https://devblogs.microsoft.com/oldnewthing/20100506-00/?p=14133, the `=C:` variable is produced by `cmd.exe` and is basically benign. (It looks weird in the logs, but shouldn't cause any harm.)
