### ISSUE TITLE
x/website/tour: broken links between pages

### ISSUE THREAD

**Issue by memark** [golang/go#49880]
### What did you do?

Go to a tour page with an site-internal link, e.g.
- https://go.dev/tour/basics/17 "modules"
- https://go.dev/tour/methods/20 "earlier exercise"

Click the link

### What did you expect to see?

Successful navigation to the new page

### What did you see instead?

404

It appears the URL segment "/tour" is missing from all internal links.

**Comment by mknyszek** [comment]
CC @rsc whose been looking at other small go.dev improvements.

**Comment by mknyszek** [comment]
The links are indeed broken.
