### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by tpa10** [golang/go#49887]
### What is the URL of the page with the issue?
https://go.dev/doc/manage-install
 
### What is your user agent?
NA (issue is with content, not with presentation)
 
### Screenshot
 NA (issue is with content, not presentation)

 
### What did you do?
Following the provided example:
"To install additional Go versions, run the go install command, specifying the download location of the version you want to install. The following example illustrates with version 1.10.7:

$ go install golang.org/dl/go1.10.7@latest
$ go1.10.7 download"
 
1.  Starting with version 1.15 installed:
 go version
go version go1.15.14 linux/amd64
2.  Attempt to "install version 1.17.3
  go install golang.org/dl/g01.17.3@latest
package golang.org/dl/g01.17.3@latest: can only use path@version syntax with 'go get'
 
### What did you expect to see?
Clean install of the latest version.
 
### What did you see instead?
The error message:
package golang.org/dl/g01.17.3@latest: can only use path@version syntax with 'go get'

**Comment by fzipp** [comment]
There's a typo in your command: you wrote "g0" (g-zero) in the path instead of "go" (g-o).

**Comment by seankhliao** [comment]
the instructions assume you start with a supported version of go, (1.16,1.17)
use `go get` if you're on an earlier version
