### ISSUE TITLE
x/website: preserve playground backend choice on "share"

### ISSUE THREAD

**Issue by fzipp** [golang/go#49885]
[CL 366056](https://golang.org/cl/366056) added support for multiple backends to the [playground](https://go.dev/play/).

When I choose "Go dev branch" and click "Share" the selection jumps back to "Go release". It would be nice if the choice was preserved, maybe even as part of the shareable URL.

**Comment by mknyszek** [comment]
CC @rsc

**Comment by rsc** [comment]
The jumping back is a duplicate of #49766, which has a fix pending.

We considered putting the Go version into the share URL but it would be a moving target and would lead to stale or strangely behaving links.
