### ISSUE TITLE
cmd/compile/internal/importer, go/internal/importer (+friends): can't import 'any' underlying

### ISSUE THREAD

**Issue by findleyr** [golang/go#49888]
The following logic is replicated to a few of our importers:
```
	if t, ok := p.typCache[off]; ok && (base == nil || !isInterface(t)) {
		return t
	}
```
https://cs.opensource.google/go/go/+/master:src/go/internal/gcimporter/iimport.go;l=258;drc=f90a42b41080cf5a289f151f2166d0d0a795e836

As a result, we don't use the cached, predeclared `any` when considering the RHS of a type declaration, as in

```
type Any any
```

When importing this code, we get

```
cannot import <package> (predeclared type missing from cache: 31), possibly version skew - reinstall package
```

(it is unfortunate that we did not add test coverage for this pattern, once `any` was allowed out of constraint position)

Notably, `cmd/compile/internal/typecheck` does not appear to have this problem:
https://cs.opensource.google/go/go/+/master:src/cmd/compile/internal/typecheck/iimport.go;l=745;drc=229b90931312aa1686f4bace25d1f40f896884ad

Discussing with @griesemer, we're not sure why that guard is necessary. Certainly it seems OK to add an exception for `any` there. If this doesn't work out, we may need to revert #49583, which would be unfortunate.

CC @mdempsky and @danscales who may have additional context, @heschi for awareness.

**Comment by findleyr** [comment]
Looked at this a bit more. The original problem is that we use the LHS of type declaration as the receiver type in interface methods on the RHS, so such RHS interfaces can't be reused.  Possibly we could stop doing this, but that's not a decision for now. To fix this bug, we can just allow reusing empty interfaces.

**Comment by dmitshur** [comment]
This issue is currently filed as release blocking and not okay after beta 1, so the Go 1.18 beta 1 is being blocked on it.

**Comment by findleyr** [comment]
> This issue is currently filed as release blocking and not okay after beta 1, so the Go 1.18 beta 1 is being blocked on it.

Yes, this is definitely a release blocker.  The CL to fix it is pending.
