### ISSUE TITLE
Proxy Authentication Required transport.go

### ISSUE THREAD

**Issue by whyynoot** [golang/go#49897]
<pre>
$ go version
go1.17.3 windows/amd64
</pre>

I saw you tryed to fix this but still doesnt work 
I Suggest you fixed this with GET Requests, but not with POST

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=off
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\mlgan\AppData\Local\go-build
set GOENV=C:\Users\mlgan\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\mlgan\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\mlgan\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\mlgan\AppData\Local\Temp\go-build2667324845=/tmp/go-build -gno-record-gcc-switches
</pre></details>

I am trying to make POST request with proxy. And I get `Proxy Authentication Required`
(https://go.dev/play/p/Qb-ZlO3Pzwf)

I expect request to go throw proxy. 

I saw Error on Posting: `Proxy Authentication Required`

So, the proxy Auth was fixed with updates when the request method is GET, but in post request I still get errors

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
