### ISSUE TITLE
x/playground: reopening closed playground loses content

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#49895]
With the old playground, if you close the tab (I do this quite often accidentally when I type ctrl-w trying to delete the last word), reopening it would bring it back without losing any content. You can easily verify this by trying the old playground at [go](https://gotipplay.golang.org/).

In the new playground, the reopened tab reverts the content to its original state, which can be very frustrating if one has spent a while editing there.

**Comment by mknyszek** [comment]
CC @rsc ? Should I be directing this to someone else, or to a group?

**Comment by rogpeppe** [comment]
Just bitten by this badly for the nth time after spending 15 minutes editing some code only to lose it. Any chance of a fix, please?

**Comment by seankhliao** [comment]
I think it's a race between https://go.googlesource.com/website/+/refs/heads/master/_content/js/playground.js#553 and whatever does the restoring (browser?)

**Comment by rogpeppe** [comment]
Yes, a race sounds about right - I thought I saw my content appear for a moment before before deleted.

**Comment by ZekeLu** [comment]
I have tested this issue with a local modified js file, and it turns out that the culprit is https://go.googlesource.com/website/+/refs/heads/master/_content/js/playsite.js#26. I have sent out a CL, hopefully that it will fix this issue.

**Comment by ZekeLu** [comment]
Hi @jamalc, I found that the CL has been deployed and just had a test. Unfortunately, it doesn't fix this issue reliably. The flow is  like this:

- The "hello world" example is loaded
-  => **maybe**: the click event of the run button is triggered (case 1)
-  => The user content is restored
-  => **maybe**: the click event of the run button is triggered (case 2)
-  => The server returns the fmt result
-  => The textarea is updated with the fmt result from the server.

Either case 1 or case 2 will happen, but not both.
In case 1, the source code of the "hello world" example is provided to the server and it will be the final text in the textarea.
In case 2, the user content is provided to the server, and it will be the final text in the textarea.

I think we have to remove `$('.js-playgroundRunEl').click();` or delay its execution to avoid the race.

**Comment by ZekeLu** [comment]
I found another issue caused by https://go.dev/cl/407055. When we open a shared code (for example,  https://go.dev/play/p/cnjP1PbosLa). The "Run" action could send `Loading share...` to https://go.dev/_/fmt, which result in:

```
prog.go:1:1: expected 'package', found Loading

Go build failed.
```

I'm very sorry for the error.  https://go.dev/cl/408414 will fix this issue too.
