### ISSUE TITLE
runtime: mkfastlog2table produces different output on darwin/arm64

### ISSUE THREAD

**Issue by josharian** [golang/go#49891]
On darwin/arm64 at 3ca57c7fb8bfc9b8b633f71a7aaa9de5fe76f63d (Nov 29, 2021), running `go generate` in package runtime generates a diff:

```diff
diff --git a/src/runtime/fastlog2table.go b/src/runtime/fastlog2table.go
index 6ba4a7d3f2..d8bb953939 100644
--- a/src/runtime/fastlog2table.go
+++ b/src/runtime/fastlog2table.go
@@ -8,22 +8,22 @@ const fastlogNumBits = 5
 
 var fastlog2Table = [1<<fastlogNumBits + 1]float64{
 	0,
-	0.0443941193584535,
-	0.08746284125033943,
-	0.12928301694496647,
-	0.16992500144231248,
-	0.2094533656289499,
+	0.044394119358453485,
+	0.08746284125033939,
+	0.12928301694496644,
+	0.16992500144231246,
+	0.20945336562894987,
 	0.24792751344358555,
 	0.28540221886224837,
-	0.3219280948873623,
-	0.3575520046180837,
-	0.39231742277876036,
-	0.4262647547020979,
-	0.4594316186372973,
-	0.4918530963296748,
+	0.32192809488736235,
+	0.35755200461808373,
+	0.3923174227787603,
+	0.42626475470209796,
+	0.45943161863729726,
+	0.4918530963296747,
 	0.5235619560570128,
 	0.5545888516776374,
-	0.5849625007211563,
+	0.5849625007211562,
 	0.6147098441152082,
 	0.6438561897747247,
 	0.6724253419714956,
@@ -31,7 +31,7 @@ var fastlog2Table = [1<<fastlogNumBits + 1]float64{
 	0.7279204545631992,
 	0.7548875021634686,
 	0.7813597135246596,
-	0.8073549220576042,
+	0.8073549220576041,
 	0.8328900141647417,
 	0.8579809951275721,
 	0.8826430493618412,
diff --git a/src/runtime/preempt_mips64x.s b/src/runtime/preempt_mips64x.s
index 996b592ae0..99e680c39e 100644
--- a/src/runtime/preempt_mips64x.s
+++ b/src/runtime/preempt_mips64x.s
@@ -1,7 +1,6 @@
 // Code generated by mkpreempt.go; DO NOT EDIT.
 
 //go:build mips64 || mips64le
-
 #include "go_asm.h"
 #include "textflag.h"
 
diff --git a/src/runtime/preempt_mipsx.s b/src/runtime/preempt_mipsx.s
index 7b169acd99..6d808813d1 100644
--- a/src/runtime/preempt_mipsx.s
+++ b/src/runtime/preempt_mipsx.s
@@ -1,7 +1,6 @@
 // Code generated by mkpreempt.go; DO NOT EDIT.
 
 //go:build mips || mipsle
-
 #include "go_asm.h"
 #include "textflag.h"
 
diff --git a/src/runtime/preempt_ppc64x.s b/src/runtime/preempt_ppc64x.s
index 2c4d02edfe..66c33276ec 100644
--- a/src/runtime/preempt_ppc64x.s
+++ b/src/runtime/preempt_ppc64x.s
@@ -1,7 +1,6 @@
 // Code generated by mkpreempt.go; DO NOT EDIT.
 
 //go:build ppc64 || ppc64le
-
 #include "go_asm.h"
 #include "textflag.h"
 
```

Should we regenerate and commit prior to the release?

**Comment by robpike** [comment]
Is this a change due to registerization of arguments? Or some other optimization? It's just the last digit changing, but it would be nice to understand why.

-rob

**Comment by rsc** [comment]
Why did it delete the blank lines? That's definitely a bug and not a math problem.

**Comment by rsc** [comment]
We don't need to regenerate and commit. The table is only used to get 5 digits of log. 

It is still interesting to find out why arm64 produces slightly different numbers. We have excised all the 387 intrinsics, so that's not it. I thought maybe the x86-64 asm was producing a different answer from the pure Go that arm64 would use, but setting haveArchLog = false in math/log_asm.go on x86-64 did not change the behavior of mkfastlog2table.

At that point I think it's all pure Go code - Log2 calls Log calls Frexp, and only Log had any assembly (on x86-64). It's a bit concerning but not enough to block the release.

**Comment by randall77** [comment]
Could be FMA on arm64. `mkfastlog2table` doesn't have any FMA issues, but maybe there are FMA candidates in math.Log2?

**Comment by rsc** [comment]
log2 itself is a single FMA. Could be.

**Comment by randall77** [comment]
I've verified that disabling FMA in `math.log2` (adding a `float64` cast) fixes the precision differences.

**Comment by josharian** [comment]
Phew. So now it's just a question of finding a way to make the generator programs stable and match the existing runtime directory.

**Comment by randall77** [comment]
I think the easiest thing would be just to copy `log2` out of math and into mkfastlog2table and add the `float64` cast that disables FMA.

**Comment by mknyszek** [comment]
This doesn't seem like it's necessarily a new issue in this release, and it certainly shouldn't block it. Moving this to the 1.19 milestone for now.

**Comment by ianlancetaylor** [comment]
Rolling forward to 1.20.  Please comment if you disagree.  Thanks.
