### ISSUE TITLE
Go1.17.3 Test Command Rejects Testing on Properly Used Internal Packages and Internal Packages Themselves

### ISSUE THREAD

**Issue by hollowaykeanho** [golang/go#49890]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/u0/Documents/monteur/.monteurFS/bin/gopath/bin"
GOCACHE="/home/u0/Documents/monteur/.monteurFS/bin/gocache"
GOENV="/home/u0/Documents/monteur/.monteurFS/bin/goenv"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/u0/Documents/monteur/.monteurFS/bin/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/u0/Documents/monteur/.monteurFS/bin/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/u0/Documents/monteur/.monteurFS/bin/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/u0/Documents/monteur/.monteurFS/bin/golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/u0/Documents/monteur/gopkg/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/user/1000/go-build982824238=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```
u0:gopkg$ pwd # gitlab.com/zoralab/monteur/gopkg
/home/u0/Documents/monteur/gopkg
u0:gopkg$ go test -timeout "14400s" -coverprofile "/home/u0/Documents/monteur/.monteurFS/tmp/test/go.profile" -race -v "/home/u0/Documents/monteur/gopkg/..."
package gitlab.com/zoralab/monteur/monteur
        monteur/composer.go:23:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/conductor not allowed
package gitlab.com/zoralab/monteur/monteur
        monteur/composer.go:24:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/libcmd not allowed
package gitlab.com/zoralab/monteur/monteur
        monteur/composer.go:25:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/liblog not allowed
package gitlab.com/zoralab/monteur/monteur
        monteur/Filesystem.go:19:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/libmonteur not allowed
package gitlab.com/zoralab/monteur/monteur
        monteur/composer.go:27:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/libsecrets not allowed
package gitlab.com/zoralab/monteur/monteur
        monteur/setup.go:27:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/libsetup not allowed
package gitlab.com/zoralab/monteur/monteur
        monteur/composer.go:28:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/libworkspace not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libcmd
        monteur/internal/libcmd/Manager.go:24:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/commander not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libcmd
        monteur/internal/libcmd/Manager.go:25:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/conductor not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libcmd
        monteur/internal/libcmd/Manager.go:26:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/endec/toml not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libcmd
        monteur/internal/libcmd/Manager.go:27:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/liblog not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libcmd
        monteur/internal/libcmd/Manager.go:28:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/libmonteur not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libcmd
        monteur/internal/libcmd/Manager.go:29:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/templater not allowed
package gitlab.com/zoralab/monteur/monteur/internal/liblog
        monteur/internal/liblog/Logger.go:23:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/libmonteur not allowed
package gitlab.com/zoralab/monteur/monteur/internal/liblog
        monteur/internal/liblog/Logger.go:24:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/logger not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libmonteur
        monteur/internal/libmonteur/TOML.go:21:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/commander not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libsecrets
        monteur/internal/libsecrets/Secrets.go:19:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/endec/toml not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libsecrets
        monteur/internal/libsecrets/Secrets.go:20:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/secrets not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libsetup
        monteur/internal/libsetup/Manager.go:26:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/checksum not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libsetup
        monteur/internal/libsetup/Manager.go:27:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/commander not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libsetup
        monteur/internal/libsetup/Manager.go:28:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/conductor not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libsetup
        monteur/internal/libsetup/Manager.go:29:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/endec/toml not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libsetup
        monteur/internal/libsetup/Manager.go:30:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/httpclient not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libsetup
        monteur/internal/libsetup/Manager.go:31:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/liblog not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libsetup
        monteur/internal/libsetup/Manager.go:32:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/libmonteur not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libsetup
        monteur/internal/libsetup/Manager.go:33:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/targz not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libsetup
        monteur/internal/libsetup/Manager.go:34:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/templater not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libworkspace
        monteur/internal/libworkspace/Workspace.go:22:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/endec/toml not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libworkspace
        monteur/internal/libworkspace/Pathing.go:27:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/filesystem not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libworkspace
        monteur/internal/libworkspace/Pathing.go:28:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/libmonteur not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libworkspace
        monteur/internal/libworkspace/Workspace.go:24:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/schema not allowed
package gitlab.com/zoralab/monteur/monteur/internal/libworkspace
        monteur/internal/libworkspace/Workspace.go:25:2: use of internal package gitlab.com/zoralab/monteur/gopkg/monteur/internal/styler not allowed
u0:gopkg$ go build app/monteur/main.go 
u0:gopkg$ ls
app  docs.go  go.mod  go.sum  main  monteur
u0:gopkg$ ./main --help
MONTEUR (V0.0.1)
────────────────
A software manufacturing automation and assembling tools in one app. Das Monteur - Getting the job
done locally and remotely at scale!


USAGES
──────
1)  $ monteur help
2)  $ monteur setup
3)  $ monteur test
4)  $ monteur clean
5)  $ monteur build
6)  $ monteur release
7)  $ monteur package
8)  $ monteur compose
9)  $ monteur publish


ARGUMENTS
─────────
build                execute the build job
clean                execute the clean job
compose              execute the publication composition job
help, --help, -h     call for help
package              execute the package job
publish              execute the publish job
release              execute the release job
setup                run repository setup for test, develop, and etc
test                 execute the test job

u0:gopkg$ go run app/monteur/main.go --help
MONTEUR (V0.0.1)
────────────────
A software manufacturing automation and assembling tools in one app. Das Monteur - Getting the job
done locally and remotely at scale!


USAGES
──────
1)  $ monteur help
2)  $ monteur setup
3)  $ monteur test
4)  $ monteur clean
5)  $ monteur build
6)  $ monteur release
7)  $ monteur package
8)  $ monteur compose
9)  $ monteur publish


ARGUMENTS
─────────
build                execute the build job
clean                execute the clean job
compose              execute the publication composition job
help, --help, -h     call for help
package              execute the package job
publish              execute the publish job
release              execute the release job
setup                run repository setup for test, develop, and etc
test                 execute the test job
u0:gopkg$ 
```

### What did you expect to see?
Go Test can operate properly for a correct use of `internal` package, and runs test for all `internal` packages just like public ones.

Rationale: some `internal` packages are a package that has potential to be up-streamed into library module somewhere in the future. However, as of now, they are currently kept inside `internal` as they are still under development.

### What did you see instead?
As above. The **ONLY WORKAROUND is not to use `internal` package entirely**.

Some research I did:
1. There is no issue with `go run` and `go build` with existing code bases. Compile was done perfectly.
2. The use of `internal` package is compliant to [specifications](https://pkg.go.dev/cmd/go#hdr-Internal_Directories).
3. There is no plan to scrap `internal` package.
4. Source code available for reference (note that the `go.mod` is inside `gopkg/` directory): https://gitlab.com/zoralab/monteur/-/tree/next

**Comment by rsc** [comment]
The go.mod in the gopkg directory says "module gitlab.com/zoralab/monteur".
That means the gopkg directory corresponds to the import path gitlab.com/zoralab/monteur.
It looks like you are trying to import the code in the directory gopkg/monteur/internal/conductor (among others).
Given that 
gopkg = gitlab.com/zoralab/monteur, that conductor directory has import path
gopkg/monteur/internal/conductor = gitlab.com/zoralab/monteur/monteur/internal/conductor

But your import statement says gitlab.com/zoralab/monteur/gopkg/monteur/internal/conductor.
That is, there is a unexpected gopkg in the import path.
The package with that import path doesn't exist, but if it did, 
the visibility rules would disallow importing it, and we check those first.

If you want to have the gopkg element in your import paths,
then you can change the go.mod to say "module github.com/zoralab/monteur/gopkg".
Otherwise, drop the /gopkg from the import statements.

**Comment by hollowaykeanho** [comment]
Hi @rsc , thanks and wow this is awkward. After correcting the module naming from the incorrect `module gitlab.com/zoralab/monteur` to `module gitlab.com/zoralab/monteur/gopkg` matching the git repository directory pathing, everything works fine.

No I do not intend to remove `gopkg/` pathing. Basically, I want to the entire Go source codes stays inside `gopkg/` so that the git root level can be used for other non-go operations. Hence the weird pathing: `monteur/gopkg/monteur`, so the Go customer can do the following to import the Go API without needing to rename it (If there is a better idea, I'm all ears):

```
import (
    "gitlab.com/zoralab/monteur/gopkg/monteur" // for API
    "gitlab.com/zoralab/monteur/gopkg/app/monteur" for binary application
)
```

----

There is another problem: Only Go Test is able to pick up this issue while Go Run and Go Build both reflecting inconsistent results.

IMO, I'm expecting all of them to fail and react consistently since the `go.mod` pathing is faulty. Should I re-title the issue or should I close the case if the reaction is expected?

**Comment by seankhliao** [comment]
If your build doesn't include any of packages with bad imports then no errors will be reported (`go build app/monteur/main.go` vs `go test ./...`)

**Comment by hollowaykeanho** [comment]
> If your build doesn't include any of packages with bad imports then no errors will be reported

@seankhliao, I'm mean that's the question on point with the case above: the `go.mod` module pathing is indeed broken so by right, all the import statement should break just like `go test`. However, `go build` and `go run` somewhat magically work as charm.

----

Since the issue is closed, my guess would be `go build` and `go run` both have some kind of self-healing mechanism even with a broken `go.mod`. This would be not detected until `go test` is implemented.
