### ISSUE TITLE
runtime/cgo: unknown warning option '-Wno-nullability-completeness'

### ISSUE THREAD

**Issue by KeeganRen** [golang/go#49913]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.17.3 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/keegan/Library/Caches/go-build"
GOENV="/Users/keegan/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/keegan/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/keegan/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
My OS is macOS Big Sur 11.6，when i use go build：

go build
-------
runtime/cgo
error: unknown warning option '-Wno-nullability-completeness'; did you mean '-Wno-delete-incomplete'? [-Werror,-Wunknown-warning-option]
 

I don‘t known how to solve this problem。

**Comment by bcmills** [comment]
That flag comes from here:
https://cs.opensource.google/go/go/+/master:src/runtime/cgo/cgo.go;l=27;drc=9cec50f50c29f5ef7264bf06ee7ac0991b4b36d6

It was apparently added for #35247 (CC @ianlancetaylor @tklauser).

**Comment by bcmills** [comment]
One thing isn't clear to me, though: why isn't this failure showing up on the Go project's own Big Sur builders?

I wonder if this is a regression in between macOS 11.0 (Nov. 17, 2020) and 11.6 (Sept. 13, 2021) — perhaps we haven't upgraded our builder images to track the current minor releases. (CC @golang/release)

**Comment by bcmills** [comment]
@KeeganRen, what version of the XCode toolchain do you have installed? (What does `clang --version` report?)

**Comment by ianlancetaylor** [comment]
Why is the compiler in the original report using `-Wunknown-warning-option`?  That should never be the default.  Are you turning it on explicitly?

**Comment by bcmills** [comment]
According to https://clang.llvm.org/docs/DiagnosticsReference.html#wunknown-warning-option, `-Wunknown-warning-option` is also enabled by default on `clang`.

**Comment by KeeganRen** [comment]
> @KeeganRen, what version of the XCode toolchain do you have installed? (What does `clang --version` report?)

Hi, Boss
My clang version is:

------
clang version 3.5.0 
Target: x86_64-apple-darwin20.6.0
Thread model: posix

**Comment by bcmills** [comment]
Clang 3.5 was released in 2014. How did you come to have that installed alongside a modern 13.0.0 `llvm-g++`?

**Comment by KeeganRen** [comment]
> @bcmills 
I'm sorry, I compiled clang3.5 a few years ago, but i forget it... and I have recently upgraded my os ..

now I use clang13, it's ok.

thanks.
