### ISSUE TITLE
writing struct to file will generate the redundant data

### ISSUE THREAD

**Issue by pplmx** [golang/go#49914]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 darwin/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/mystic/Library/Caches/go-build"
GOENV="/Users/mystic/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mystic/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mystic/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/opt/homebrew/Cellar/go/1.17.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.17.2/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n0/qvk0c6cs1qxg_ts1pqxhlpwr0000gn/T/go-build2187534776=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```golang
package main

import (
    "encoding/json"
    "os"
)

type S struct {
    S1List []S1
    S2List []S2
}

type S1 struct {
    Id   string
    Name string
}

type S2 struct {
    Id   string
    Name string
}

func main() {
    emptyData := &S{
        S1List: []S1{},
        S2List: []S2{},
    }
    bytesData, _ := json.Marshal(emptyData)
    f, _ := os.OpenFile("/var/tmp/cc.json", os.O_CREATE|os.O_WRONLY, 0777)
    _, _ = f.Write(bytesData)
}

```

### What did you expect to see?
```text
❯ cat /var/tmp/cc.json
{"S1List":[],"S2List":[]}%
```

### What did you see instead?
```text
❯ cat /var/tmp/cc.json
{"S1List":[],"S2List":[]}ull}%
```

**Comment by pplmx** [comment]
If 1.17.3, it will generate the following
```text
❯ cat /var/tmp/cc.json
{"S1List":[],"S2List":[]}:[]}%
```

**Comment by pplmx** [comment]
# `1.17.3`
If added json mapping, like this
```go
package main

import (
    "encoding/json"
    "os"
)

type S struct {
    S1List []S1 `json:"s_1_list"`
    S2List []S2 `json:"s_2_list"`
}

type S1 struct {
    Id   string `json:"id"`
    Name string `json:"name"`
}

type S2 struct {
    Id   string `json:"id"`
    Name string `json:"name"`
}

func main() {
    emptyData := &S{
        S1List: []S1{},
        S2List: []S2{},
    }
    bytesData, _ := json.Marshal(emptyData)
    f, _ := os.OpenFile("/var/tmp/cc.json", os.O_CREATE|os.O_WRONLY, 0777)
    _, _ = f.Write(bytesData)
}

```

## It will output
```text
❯ cat /var/tmp/cc.json
{"s_1_list":[],"s_2_list":[]}%
```

**Comment by pplmx** [comment]
The problem still exists in my project, but it will work fine when I extract this code segment to run locally

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by pplmx** [comment]
# FYI
https://stackoverflow.com/questions/70196876/why-in-golang-writing-file-takes-overwrite-behavior-as-default
