### ISSUE TITLE
x/playground: dev-branch code doesn't maintain dev-branch attribute when shared

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#49915]
The new playground makes it possible to use the dev branch to try examples only possible on tip (type parameter code being the prime example). However, a "Share" link created on that code doesn't work when run unless the "Go release" selector is first changed to "Go dev branch".

For example, I created this link by "Share" on the "Generic min" example: https://go.dev/play/p/kg938K7hORf . If you open that, clicking Run won't work as it should.

**Comment by seankhliao** [comment]
Duplicate of #49885
