### ISSUE TITLE
cmd/link: support more load commands on Mach-O [1.16 backport]

### ISSUE THREAD

**Issue by mknyszek** [golang/go#49923]
On the 1.16 release branch, the macOS 12 builder has been failing since it was brought up, basically.

The failures look like https://build.golang.org/log/158c3565da1dabd522292bee52369d329419a452 with a bunch of misc/cgo/testcshared tests failing.

CC @cherrymui @ianlancetaylor

**Comment by dmitshur** [comment]
CC @golang/release in case this is a problem with the builder itself or macOS 12.

**Comment by heschi** [comment]
Sorry for not paying attention when I brought up the builder. We're suffering for lack of https://golang.org/cl/312729. Should I disable the builder or backport that CL?

**Comment by ianlancetaylor** [comment]
Since 1.16 is still supported I think we should backport.

**Comment by FiloSottile** [comment]
Reverted to minimize risk for security release.
