### ISSUE TITLE
x/tools/go/types/typeutil: TestMapGenerics failure on linux-amd64 TryBot

### ISSUE THREAD

**Issue by bcmills** [golang/go#49931]
From https://storage.googleapis.com/go-build-log/60d5200e/linux-amd64_5c4ddb20.log (a TryBot on [CL 367848](https://golang.org/cl/367848)):
```
--- FAIL: TestMapGenerics (0.00s)
    map_test.go:353: At(F2) = <nil>, want new entry: false
    map_test.go:353: At(Fb1) = <nil>, want new entry: false
FAIL
FAIL	golang.org/x/tools/go/types/typeutil	0.052s
```

However, there have been no occurrences in the dashboard logs so far:

`greplogs --dashboard -md -l -e 'FAIL: TestMapGenerics'`
(No results.)

(CC @findleyr)

**Comment by findleyr** [comment]
The CL needs to be rebased, as it is missing https://golang.org/cl/366178 (parent is from Nov 16).
