### ISSUE TITLE
cmd/api: allow use with external packages

### ISSUE THREAD

**Issue by bamiaux** [golang/go#4993]
<pre>I'd like to be able to use go tool api on external packages and not just with the
standard go libray.
Something like 'go tool api ...mypackage' which generates a text file containing
mypackage public api.
This would be useful to prevent unecessary API breakage.</pre>

**Comment by shurcooL** [comment]
I'd like this too.

**Comment by shurcooL** [comment]
I can confirm the patch by @vbatts still works. There was one merge conflict (related to #7103 being already merged in), but it was harmless.

**Comment by bradfitz** [comment]
Dup of #13030 (x/build/cmd/release: do not ship cmd/api binary)

That is now fixed, meaning we no longer ship the api tool. It's our internal detail only.
