### ISSUE TITLE
x/website: running code in go.dev/tour doesn't work

### ISSUE THREAD

**Issue by leitzler** [golang/go#49936]
### What did you do?

Opened up https://go.dev/tour/welcome/1 and clicked the "Run" button in the embedded playground.

Browser: Chrome Version 96.0.4664.55 (Official Build) (x86_64)

### What did you expect to see?

Output populated.

### What did you see instead?

`Error communicating with remote server` in the output.

The POST request initated when pressing "Run" goes to `https://go.dev/_/compile?backend=undefined` and it throws an `500 Internal Server Error`.

Looks like an side effect from [CL 366056](https://go-review.googlesource.com/c/website/+/366056) where support for backends was added to the ordinary playground, while the tour doesn't have that option? If I remove `undefined` from the call it works as expected.

//cc @rsc

**Comment by fzipp** [comment]
The "Try Go" code box on the go.dev front page has the same problem.

**Comment by mknyszek** [comment]
CC @dmitshur @rsc

**Comment by mknyszek** [comment]
Ah, sorry. @jba already got to it. Please ignore, Dmitri, Russ.

**Comment by jba** [comment]
For the record, it was @jamalc.

**Comment by mknyszek** [comment]
Ah! My bad. I had only looked at the reviewer and nothing else on that page. Thanks.
