### ISSUE TITLE
x/website: "The Laws of Reflection" blog post needs a section on generics

### ISSUE THREAD

**Issue by griesemer** [golang/go#49939]
The blog post [The Laws of Reflection](https://go.dev/blog/laws-of-reflection), while old, is still a commonly used in-depth resource for the reflect package. There needs to be a preamble explaining how the reflect package is affected by generics (it isn't).

cc: @ianlancetaylor 
cc: @robpike

**Comment by robpike** [comment]
I would say rather than a preamble, it just needs a clarification in a couple of places. It also needs a tweak because Println etc. now handle reflect.Type more nicely, which invalidates a tiny bit of explanation.
