### ISSUE TITLE
x/website: FAQ needs to have a preamble re: generics

### ISSUE THREAD

**Issue by griesemer** [golang/go#49938]
The [FAQ](https://go.dev/doc/faq) need to be updated with a preamble/disclaimer as it was not written with generics in mind.

**Comment by griesemer** [comment]
cc: @robpike

**Comment by robpike** [comment]
It needs more of an update than a preamble. The FAQ should stay current.

**Comment by amnonbc** [comment]
https://go.dev/doc/faq#generics should be updated.

**Comment by ianlancetaylor** [comment]
There is a CL for this that is waiting for review (https://go.dev/cl/374215).  The CL won't be committed until the release.

**Comment by dmitshur** [comment]
@ianlancetaylor Since the CL resolving this issue is planned to be submitted right after 1.18 is released, is it okay to update move this issue to 1.19 milestone, keep release-blocker label, and add early-in-cycle, so that we can revisit this right after 1.18 is released? That way, the list of open 1.18 release blockers will be more actionable.

**Comment by ianlancetaylor** [comment]
Sure, I will make those changes.

**Comment by fzipp** [comment]
Re [CL 374215](https://go.dev/cl/374215):

Are the [comparisons](https://go.googlesource.com/website/+/0c76bda58c0d436874d588f73c991e86d6c9720f/_content/doc/faq.html#1944
) with other languages necessary at all? The FAQ doesn't do that to this extent for other language features. Maybe their relevant contents can be formulated as part of other questions or as questions about specific features on their own, which is conceptually more in line with the rest of the FAQ. For example:

- The Java comparison mentions the absence of type erasure, which could be covered by "How are generics implemented in Go?".
- The lack of variance could be covered by a separate question: "Why are there no generic covariance and contravariance?"

The comparisons tell more about other languages than about what Go does. The Python comparison does not say anything directly about Go at all.

**Comment by ianlancetaylor** [comment]
Personally I think the comparisons to other languages are useful, as they help explain the new features to people already familiar with those other languages.  At least, I hope they do.
