### ISSUE TITLE
go version go1.13 linux/amd64

### ISSUE THREAD

**Issue by maugomez77** [golang/go#49935]
$ go env

when using this particular library: 

module symantec/ams

go 1.17

require (
	github.com/hashicorp/vault v1.8.5
)

It pop ups this error: 

go: extracting github.com/hashicorp/vault v1.8.5
-> unzip /root/go/pkg/mod/cache/download/github.com/hashicorp/vault/@v/v1.8.5.zip: malformed file path "website/pages/api-docs/[[...page]].jsx": double dot

i also run already: 

go clean -cache
go clean -modcache

but looks to be a directive from go

**Comment by seankhliao** [comment]
go1.13 is no longer supported, this doesn't occur on supported versions

**Comment by maugomez77** [comment]
what supported version i can use ?

**Comment by seankhliao** [comment]
https://go.dev/doc/devel/release#policy
