### ISSUE TITLE
x/website: Effective Go needs to have a preamble re: generics

### ISSUE THREAD

**Issue by griesemer** [golang/go#49937]
[Effective Go](https://go.dev/doc/effective_go) needs to be updated with a preamble/disclaimer as it was not written with generics in mind.

cc: @robpike

**Comment by robpike** [comment]
It should also mention that is old and dated (and frozen) and has little about libraries and some other emergent best practices. A preamble is probably the right fit here.

**Comment by robpike** [comment]
Duplicate of https://github.com/golang/go/issues/48274

**Comment by susugagalala** [comment]
The book "The Go Programming Language" needs to be updated.

**Comment by amnonbc** [comment]
Effective Go is an excellent resource and should be kept current.

**Comment by ianlancetaylor** [comment]
Not doing this per CL 380634.
