### ISSUE TITLE
Error installing tools using go.

### ISSUE THREAD

**Issue by sreeharisj23** [golang/go#49956]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>
## go1.17.3
![go version](https://user-images.githubusercontent.com/48901974/144631199-70ce7cd3-5910-4f27-83fe-238b390989eb.png)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
![go env](https://user-images.githubusercontent.com/48901974/144631182-4c90bcd8-f111-4922-84d0-df8681441df7.png)

### What did you do?

go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest

### What did you expect to see?

A successful installation.

### What did you see instead?
![error](https://user-images.githubusercontent.com/48901974/144631608-ff049f1e-faab-40d2-8e51-6f7190db699b.png)

**Comment by ALTree** [comment]
Why post screenshots copy-pasting the result as text? These images are hard to read and the text inside won't show up when people search in the issue tracker. 

Please replace the screenshots with text.

**Comment by mvdan** [comment]
Also, please try 1.17.4 first, as it was just released with some fixes.

**Comment by seankhliao** [comment]
Can't reproduce this (with either our released versions or with kali packaged 1.17.3)

**Comment by sreeharisj23** [comment]
The issues was solved after I upgraded to Kali v2021.4.
