### ISSUE TITLE
database/sql: TestStmtCloseDeps failure on windows-amd64-longtest

### ISSUE THREAD

**Issue by bcmills** [golang/go#49958]
```
--- FAIL: TestStmtCloseDeps (5.11s)
    sql_test.go:2502: len(stmt.css) = 59; want <= 50
FAIL
FAIL	database/sql	6.414s
```

`greplogs --dashboard -md -l -e 'FAIL: TestStmtCloseDeps ' --since=2020-01-01`

[2021-11-27T19:49:32-a142d65/windows-amd64-longtest](https://build.golang.org/log/da2c51b22fd6c84732b927bb240baa44cad6c7b7)

This is the regression test for #5323. Only one failure has been seen in the logs, but since the test is skipped it short mode the sample size is relatively smaller than for most tests; however, there have been fairly recent changes in `database/sql` (CC @kardianos, @ianlancetaylor).

**Comment by kardianos** [comment]
Thanks. I'll try to duplicate ASAP and diagnose. I agree that fundamental changes were recently made.

**Comment by kardianos** [comment]
@bcmills I was unable to reproduce locally to date. When looking at the test itself, it contains a `time.Sleep` call that when I reduce the amount of time, it increase the number of open statements and fails the test. As such, I somewhat assume that perhaps this machine was loaded and starved the process of CPU for a bit and it failed to complete all the steps.

I could (a) ignore this, or (b) try to modify the test to not include this sleep.

**Comment by bcmills** [comment]
Given that users' development configurations and CI systems are likely even more variable than the Go project's builders, it seems like a good idea to modify the test to avoid arbitrary sleeps.

**Comment by kardianos** [comment]
database/sql tests are moving that direction; I'll see what I can do to remove the dependency on sleeps.

**Comment by bcmills** [comment]
`greplogs --dashboard -md -l -e 'FAIL: TestStmtCloseDeps ' --since=2021-12-04`

[2022-01-11T21:51:51-ad7eae2/windows-amd64-longtest](https://build.golang.org/log/e3bbf4c1dcd22026832184212d0d7ac43cea00d9)
[2021-12-16T22:39:00-b1a53ec/windows-amd64-longtest](https://build.golang.org/log/af4f0e9724f9c571b32d1b58c7ac95f1a3f3bd90)
[2021-12-12T14:36:21-8692bac/windows-amd64-longtest](https://build.golang.org/log/e12c5fbb58925541d2240f333083afff21b74636)
[2021-12-06T14:58:33-f8a8a73/windows-amd64-longtest](https://build.golang.org/log/f76ca6bdd4c99bdbae83ad56800657943d623072)

This is looking like a regression in Go 1.18 — possibly related to the runtime's pacing changes? (CC @mknyszek)
