### ISSUE TITLE
cmd/compile: failures with "symbol type.[…] listed multiple times" on freebsd-amd64-12_2 since 2021-11-24

### ISSUE THREAD

**Issue by bcmills** [golang/go#49967]
`greplogs --dashboard -md -l -e 'symbol type.* listed multiple times'`

[2021-12-02T15:48:58-28ec0fd/freebsd-amd64-12_2](https://build.golang.org/log/01f2561d76ca1fd024afee1e6634661e33c002b6)
[2021-12-01T18:47:44-3c63f30-08ecdf7/freebsd-amd64-12_2](https://build.golang.org/log/a956e85264ec734e41793bebd54fd67636edbada)
[2021-11-24T05:36:54-7cf1f38-47db3bb/freebsd-amd64-12_2](https://build.golang.org/log/375ffcfc356ea14c4659c8c09f6909b2a1054d0a)

**Comment by bcmills** [comment]
Marking as release-blocker for Go 1.18 because this failure mode appears to be new as of November.
It occurs during compilation, so it is not trivial to resolve by adding a test skip.

(CC @jeremyfaller for routing)

**Comment by bcmills** [comment]
So far these failures have only been seen on the `freebsd-amd64-12_2` builder, but with a sample size of N=3 it isn't obvious to me whether the underlying problem may affect other platforms.

**Comment by cherrymui** [comment]
The error is probably from the linker. May be the same cause s #49752.

**Comment by prattmic** [comment]
I haven't been trying to reproduce this (I'm going after https://github.com/golang/go/issues/46272#issuecomment-989027707), but this has reproduced in 2/5 of my crashes so far with:

    $ goswarm -i 25 freebsd-amd64-12_2 go/src/all.bash

**Comment by prattmic** [comment]
It seems plausible, but I haven't seen enough details to have confidence one way or another.

**Comment by cherrymui** [comment]
Same as #49752 . We can revisit once we have FreeBSD builders with kernel fixed.

**Comment by bcmills** [comment]
https://storage.googleapis.com/go-build-log/301db3f5/freebsd-amd64-12_2_faaeee15.log (a TryBot).

I think @heschi pushed an updated FreeBSD 13 builder today — is there a fix available for 12.2 as well?

**Comment by prattmic** [comment]
https://github.com/golang/go/issues/46272#issuecomment-996005449 noted that the fix is cherry-picked into FreeBSD 12 as well.

I believe https://lists.freebsd.org/archives/freebsd-snapshots/2021-December/000037.html is the latest 12 snapshot.

**Comment by heschi** [comment]
We're currently on 12.2, which doesn't have the fix. Would you like me to upgrade us to the latest 12.3 snapshot?

**Comment by bcmills** [comment]
Since 12.2 has TryBot failures that we can't easily work around by adding test skips, I think we would add an updated 12.3 builder as soon as is feasible and turn off the 12.2 TryBots.

(Probably we should keep the 12.2 post-submit builders up until the 12.3 builders have run for enough CLs to be confident that there are no significant regressions from 12.2 to 12.3.)

**Comment by thanm** [comment]
I am pretty sure this falls into the same category as #49752, which is now marked fixed-- I am going to try one more goswarm test on this one to check that the problem is no longer reproducible.

**Comment by thanm** [comment]
OK, I ran some tests with goswarm overnight (10 motes running all.bash for roughly 20 hours) using the freebsd-amd64-12_3 builder, which incorporates the [fix](https://github.com/freebsd/freebsd-src/commit/1d6ebddb62bc18833b21a15f8e7eb86102140100) for the problem identified in #46272. No new failures with the "unreachable sym" mode. I am going to close out this bug.

For posterity, here are the failures that did turn up:

15 times:

    --- FAIL: TestBlockProfile/debug=1 (0.02s)
        pprof_test.go:929: Bad chan send entry, expect:

7 times:

    --- FAIL: TestStackGrowth (32.10s)
     .. stack_test.go:154: finalizer did not run

4 times:

     ##### Testing race detector
     --- FAIL: TestOutput (10.16s)
       output_test.go:83: failed test case test_fails_on_race, expect:

5 times:

    # go run run.go -G=3 locklinear.go
    exit status 2
    panic: lockmany: too slow: 2000 ops: 16.141185ms; 4000 ops: 516.734873ms


then maybe a half dozen other singleton failures.
