### ISSUE TITLE
x/sys/unix: add Statfs for NetBSD

### ISSUE THREAD

**Issue by dundee** [golang/go#49968]
### What version of Go are you using (`go version`)?

<pre>
go version go1.17.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dundee/.cache/go-build"
GOENV="/home/dundee/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dundee/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dundee/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/dundee/work/gdu/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3967749979=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I am trying to call Statfs syscall on NetBSD.

```go
package main

import (
	"syscall"
)

func main() {
	info := &syscall.Statfs_t{}
	err := syscall.Statfs("/", info)
	if err != nil {
		panic(err)
	}
}
```

```bash
GOOS=netbsd go build main.go
```

### What did you expect to see?

Program compiles ok with GOOS=netbsd

### What did you see instead?

```
# command-line-arguments
./main.go:9:9: undefined: syscall.Statfs
```

I would like to work on the implementation myself.

**Comment by seankhliao** [comment]
Note `syscall` is frozen/deprecated, this would go in `golang.org/x/sys/unix`

Feel free to send a PR/CL

**Comment by dundee** [comment]
`Statfs` is deprecated in NetBSD. There is [statvfs](https://man.netbsd.org/statvfs.2) which looks to be implemented fine in `golang.org/x/sys/unix`. Closing.
