### ISSUE TITLE
x/website: dead link to Target's "Recommending GoLang at Target" blog post on home page

### ISSUE THREAD

**Issue by Syfadin** [golang/go#49960]
### What did you do?

I looked at the "Companies using Go" and there was a 404 on Target's 

### What did you expect to see?

The article "Recommending GoLang at Target"

Available on the waybackmachine https://web.archive.org/web/20191122223224/https://tech.target.com/infrastructure/2018/06/18/Recommending-GoLang-at-Target.html

### What did you see instead?
404 error https://tech.target.com/infrastructure/2018/06/18/Recommending-GoLang-at-Target.html

**Comment by mknyszek** [comment]
CC @spf13 maybe?

**Comment by ianlancetaylor** [comment]
A possible alternate link would be https://www.linkedin.com/pulse/golang-recommended-technology-targets-engineering-staff-shirsath .

**Comment by codyoss** [comment]
Talked to a contact of mine, it sounds like this particular article is not going to be re-published at this time onto their new blog platform.
