### ISSUE TITLE
x/benchmarks/cmd/bent: TestBent failing on Android builders since CL 320970 

### ISSUE THREAD

**Issue by bcmills** [golang/go#49964]
```
go: downloading github.com/BurntSushi/toml v0.3.1
bent.go:109:12: pattern configs/*: no matching files found

--- FAIL: TestBent (3.06s)
    bent_test.go:53: exit status 1
FAIL
exitcode=1
FAIL	golang.org/x/benchmarks/cmd/bent	36.184s
```

This is because the Android `exec` wrapper that runs the test only copies in that package's `testdata` directory and those of its parent directories. Since the `configs` directory is neither, the `go build` subprocess fails to rebuild `cmd/bent`.

I can think of three ways to address this:
1. Add appropriate skips to the test (so that we don't try to execute it on Android).
2. Adjust x/build/dashboard/builders.go to skip this repo on the Android builders.
3. Adjust the way the files are bundled (and perhaps also adjust the way the test executes `cmd/bent`) so that it can run successfully on Android.

(attn: @dr2chase, @prattmic, @mknyszek)

**Comment by dr2chase** [comment]
Can I create a temporary directory and write files in it on Android builders?
