### ISSUE TITLE
x/website: codewalk locks up scroll on initial page load for chrome

### ISSUE THREAD

**Issue by seankhliao** [golang/go#49972]
https://go.dev/doc/codewalk/functions/

On both linux and mac chrome, loading any of the codewalk pages seems to lock up scrolling of the main page.
Scrolling sidebar works.
Scrolling the main content area works and also seems to unlock whatever was preventing scrolling on the main page.

Doesn't seem to reproduce on mac safari

Chrome UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

**Comment by jamalc** [comment]
I think this is working as intended or a bug in Chrome. Scroll is prevented in the main page when continuously scrolling through the textarea. Main page scroll resumes when there is a short break between scrolling to an edge of the textarea and then scrolling again.
