### ISSUE TITLE
Stacktrace is not provided when the race detector crashed with more than 8128 alive goroutines

### ISSUE THREAD

**Issue by lni** [golang/go#49983]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes. 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/lni/gobin"
GOCACHE="/home/lni/.cache/go-build"
GOENV="/home/lni/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/lni/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/lni/go"
GOPRIVATE=""
GOPROXY="https://mirrors.tencent.com/go"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/lni/src/matrixcube/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build752892338=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Run my tests with -race enabled. 

### What did you expect to see?

I got the following error when running my tests with -race enabled. 

```
=== RUN   TestUpdateShardKeyRange
race: limit on 8128 simultaneously alive goroutines is exceeded, dying
```

When race detector crashed with more than 8128 simultaneously alive goroutines, I'd expect the runtime to print out the stacktrace of all those goroutines so I can check whether those goroutines actually suppose to be there. 

### What did you see instead?

Silent crash without any further info on those excessive number of goroutines.

**Comment by randall77** [comment]
Yes, that would be nice to have.
Fortunately, we should be getting a new race detector for 1.19 that doesn't have this limit. See #49761.
So I'm going to close this issue as unnecessary. It will be so nice to be in a world where that error just doesn't happen.
