### ISSUE TITLE
https://go.dev/tour/welcome/1

### ISSUE THREAD

**Issue by erayakgunn** [golang/go#49989]
### What is the URL of the page with the issue?
 https://go.dev/tour/welcome/1
 
 
### What is your user agent?
 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

 
 
 
### Screenshot
 
![Ekran görüntüsü 2021-12-05 212517](https://user-images.githubusercontent.com/95462146/144758722-7568abd9-c37e-48f8-a0a3-7c626cce127c.png)

 
 
 
### What did you do?
 I ran the command and program is not working.

 
 
 
### What did you expect to see?
 Hello, 世界
 
 
### What did you see instead?
Error communicating with remote server.
Program exited.

**Comment by seankhliao** [comment]
Dup of #49936 which looks merged but not deployed
