### ISSUE TITLE
image: decode a png file return unknown format

### ISSUE THREAD

**Issue by hmvhamide** [golang/go#49999]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I open a png image file and decode it in the following code, it returns unknown format.
The image
![orig](https://user-images.githubusercontent.com/61288183/144873845-ced9197d-cff8-4512-ab73-3e9efc8fae39.png)
 is attached.
Code: https://go.dev/play/p/op3ILPNJmCw

### What did you expect to see?

I expect the code to finish without error. Because  this is a valid png file and can be opened with image editors like GIMP.

### What did you see instead?
The following error printed:
error decoding image image: unknown format

**Comment by mdlayher** [comment]
Please see the package docs and example. https://pkg.go.dev/image
