### ISSUE TITLE
cmd/trace: add a name/desc to goroutines which are inactive when get a pprof trace

### ISSUE THREAD

**Issue by yifhao** [golang/go#49994]
### What version of Go are you using (`go version`)?

<pre>
$ go version
nothing to do with go version
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
nothing to do with go env
</pre></details>

### What did you do?
I got a pprof trace, then watch it on browser. I saw the last line 'N=xxx' with no link or name. 
it's easy to make a mistake about what it is meaning, many people may think it's the total number of goroutines.

### What did you expect to see?
I read the source code, and then find: the last line is the num of goroutines which are created before trace taken, and inactive during the trace.

I think may add a name/desc to it, like: inactive when trace.
in httpGoroutines func add:
![image](https://user-images.githubusercontent.com/12428110/144825424-a4478150-23fc-436c-a6a0-159a7b3c0606.png)
and then see:
![image](https://user-images.githubusercontent.com/12428110/144824742-436ff0a1-6ebe-41f1-a7ee-d11827a9a6e1.png)

### What did you see instead?
![image](https://user-images.githubusercontent.com/12428110/144824817-32211cb9-aba6-4afb-a996-45cc44585bb7.png)

**Comment by seankhliao** [comment]
cc @mknyszek @prattmic

**Comment by yifhao** [comment]
![image](https://user-images.githubusercontent.com/12428110/144836230-210db56b-76a5-41bf-b8e6-20afdf9464c3.png)
a href tag without text which means no action in tracing will display in browser a line like this.
![image](https://user-images.githubusercontent.com/12428110/144836346-23adbbc4-b7ed-457e-a2a3-6ea3b21b1db1.png)

**Comment by prattmic** [comment]
> Ideally we'd do even better and actually attach each goroutine's stack trace to the initial [EvGoCreate](https://cs.opensource.google/go/go/+/master:src/runtime/trace.go;l=233;drc=master). This should be possible since the world is stopped, but I could see that making starting tracing take a lot longer, especially with 5000+ goroutines, which I imagine is why it was avoided in the first place.

Actually, we already have `gp.startpc` with the initial goroutine entrypoint (in fact TraceStart even uses it as the "stack id" for EvGoCreate). If the cost is low enough, we could findfunc(gp.startpc) and include a func name string id along with the EvGoStart event.

**Comment by ianlancetaylor** [comment]
Moving to Backlog.  Please comment if you disagree.  Thanks.

**Comment by zikaeroh** [comment]
The above CL had a malformed "fixes" line; this issue should be closed now that it's merged.
