### ISSUE TITLE
runtime/pprof: new test TestLabelSystemstack is flaky

### ISSUE THREAD

**Issue by prattmic** [golang/go#50007]
`greplogs --dashboard -md -l -e 'TestLabelSystemstack'`:

[2021-12-05T12:50:44-ecf6b52/freebsd-arm-paulzhol](https://build.golang.org/log/ff42f9cb53e68c1b96c94050bfcc90f894ab502f)
[2021-12-05T12:50:44-ecf6b52/linux-mipsle-rtrk](https://build.golang.org/log/ac0a2528686547576645bd6a393fa59014da8f0c)
[2021-12-04T17:16:07-3396878/freebsd-arm-paulzhol](https://build.golang.org/log/639f9e551b3ccc0d38074c00cc015f940592c8d3)
[2021-12-04T17:16:07-3396878/openbsd-mips64-jsing](https://build.golang.org/log/98a085d27af7432ebef2758a48a41aa18e21172f)
[2021-12-04T11:59:35-1876b38/freebsd-arm-paulzhol](https://build.golang.org/log/d788c3295d98490bc0d1b16f059fc2b4f9be60f5)
[2021-12-04T11:59:35-1876b38/openbsd-mips64-jsing](https://build.golang.org/log/d1d17b1a5982dce21cefa8788864a81d20150082)
[2021-12-04T04:50:55-549cfef/freebsd-arm-paulzhol](https://build.golang.org/log/900f9415481dd00ac786e41075a1dc531d4bf2a2)
[2021-12-04T01:07:21-821bf04/linux-386](https://build.golang.org/log/63aaaf6dc716f45fa6a96be475328d1fd56a4a4f)
[2021-12-03T21:25:05-d20a0bf/linux-ppc64le-buildlet](https://build.golang.org/log/6e3582006b1ff559a600b7fbc1202d6d82e84841)
[2021-12-03T21:25:05-d20a0bf/openbsd-mips64-jsing](https://build.golang.org/log/be16acfe1b4e4a1e6a715566eb5aa0c55c991063)
[2021-12-03T16:11:38-9b0de08/linux-riscv64-unmatched](https://build.golang.org/log/bdda0f0319bc423a2d386da4f3686a74f5195f64)

Test originally added in https://golang.org/cl/351751 for #48577 and reverted in https://golang.org/cl/360757 because it was extremely flaky. Re-added https://golang.org/cl/367200. It is much less flaky now, but still a bit flaky.

cc @felixge @bcmills

**Comment by prattmic** [comment]
It looks like this is exposing a legitimate bug. Every one of these logs I've looked at looks something like this:

```
        1: 0x80ed151 (fmt.Fprintf:203) 0x817f28c (runtime/pprof.labelHog:1500) 0x817ec3b (runtime/pprof.TestLabelSystemstack.func2.1.1:1481) labels: map[]
        1: 0x80ece1b (fmt.newPrinter:140) 0x80ed14d (fmt.Fprintf:203) 0x817f28c (runtime/pprof.labelHog:1500) 0x817ec3b (runtime/pprof.TestLabelSystemstack.func2.1.1:1481) labels: map[key:[value]]
        1: 0x80f2ac0 (fmt.(*pp).doPrintf:1026) 0x80ed181 (fmt.Fprintf:204) 0x817f28c (runtime/pprof.labelHog:1500) 0x817ec3b (runtime/pprof.TestLabelSystemstack.func2.1.1:1481) labels: map[key:[value]]
        1: 0x80f355c (fmt.(*pp).doPrintf:1009) 0x80ed181 (fmt.Fprintf:204) 0x817f28c (runtime/pprof.labelHog:1500) 0x817ec3b (runtime/pprof.TestLabelSystemstack.func2.1.1:1481) labels: map[key:[value]]
```

Notice that the first entry is missing the label. Every runs seems to have the first sample missing the label. Perhaps we are dropping that somewhere?

**Comment by felixge** [comment]
😞 Sorry this is flaky again. I'll do some debugging now to see if I can figure out what's going on. Thanks for the details you provided @prattmic . Looks like there are no linux/amd64 failures so far?

**Comment by prattmic** [comment]
I am looking as well to see if I can find the discrepancy.

**Comment by prattmic** [comment]
Found the bug!

`profBuf.write` [uses an index](https://cs.opensource.google/go/go/+/master:src/runtime/profbuf.go;l=383;drc=master) in `b.tags` for each entry, even if that entry has no tag (that slice entry just remains 0). [`profBuf.read`](https://cs.opensource.google/go/go/+/master:src/runtime/profbuf.go;l=432;drc=master) similarly returns a tags slice with exactly as many entries as there are in data ("entries" in data may use multiple `uint64`s in that slice).

`profileBuilder.addCPUData` [iterates through the tags](https://cs.opensource.google/go/go/+/master:src/runtime/pprof/proto.go;l=312-316;drc=master) in lockstep with the data entries. _Except_ in the special case of the [first record](https://cs.opensource.google/go/go/+/master:src/runtime/pprof/proto.go;l=284;drc=master), where it forgets to increment tags. Thus the first read of profiling data has all tags off-by-one.

I will send a CL shortly.

**Comment by felixge** [comment]
@prattmic wow, that was fast! I only got as far as verifying that the tagPtr is still in-tact when `cpuprof.add(tagPtr, stk[:n])` gets called for the first sample :).

Given what you found, do you think this this will fix the test flakiness? Or would it just help with the tag accuracy of the first batch of samples?

**Comment by prattmic** [comment]
> Given what you found, do you think this this will fix the test flakiness? Or would it just help with the tag accuracy of the first batch of samples?

I'm not certain. I _hope_ it is the only bug and perhaps could even resolve [this TODO](https://cs.opensource.google/go/go/+/master:src/runtime/pprof/pprof_test.go;l=1461;drc=master;bpv=1), but I don't know yet.

**Comment by felixge** [comment]
> and perhaps could even resolve this TODO, but I don't know yet.

Just took your patch for a spin, and it looks very promising! I'd be happy to send a change for removing that TODO once your patch lands. Or feel free to make it part of your change if you think it's worth a shot.

https://gist.github.com/felixge/b3a2436035ccfc24d3a0aa0fe98b3c57

**Comment by prattmic** [comment]
https://golang.org/cl/369984 is expected to fix this. Will file a new bug if more issues come up.

**Comment by bcmills** [comment]
> Will file a new bug if more issues come up.

Looks like there is at least one failure mode remaining — filed #50050.
