### ISSUE TITLE
cmd/ld: unrecognized option '--high-entropy-va' on windows

### ISSUE THREAD

**Issue by jmwielandt** [golang/go#50020]
### What version of Go are you using (`go version`)?

go version go1.17.4 windows/amd64

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\josew\AppData\Local\go-build
set GOENV=C:\Users\josew\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\josew\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\josew\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.4
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\josew\go\src\timining.com\jarvis-server\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\josew\AppData\Local\Temp\go-build3912007158=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I tried to compile my pure go project with `go build -buildmode=c-shared`.

### What did you expect to see?

Successfully compilation.

### What did you see instead?

```
C:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: unrecognized option '--high-entropy-va'
c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: use the --help option for usage information
collect2.exe: error: ld returned 1 exit status
```

I've installed gcc compiler via MinGW. ld.exe's version is 2.28. MinGW says is the latest.

![imagen](https://user-images.githubusercontent.com/37153467/145023384-94efeb88-206d-461d-8340-19758115d2bb.png)

**Comment by zx2c4** [comment]
Your toolchain is likely too old.

Try one of these https://github.com/mstorsjo/llvm-mingw/releases

**Comment by jmwielandt** [comment]
@zx2c4 thanks you my god/ess and saviour! <3

**Comment by protonys** [comment]
Thank you very much
