### ISSUE TITLE
build: GOEXPERIMENT=unified fails using Go 1.17 as bootstrap toolchain

### ISSUE THREAD

**Issue by rsc** [golang/go#50029]
```
% GOROOT_BOOTSTRAP=$HOME/sdk/go1.17 GOEXPERIMENT=unified ./make.bash
go: unknown GOEXPERIMENT unified
Building Go cmd/dist using /Users/rsc/sdk/go1.17. ()
go: unknown GOEXPERIMENT unified
% 
```

I'm not sure what's going on here. It looks like maybe GOEXPERIMENT should be cleared during the use of the bootstrap toolchain in make.bash?

**Comment by cuonglm** [comment]
AFK now, but IIRC, there's an issue tracking this issue already (and also Matthew's CL to address it).

**Comment by rsc** [comment]
Thanks. I don't see it here. https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+goexperiment+unified

**Comment by rsc** [comment]
Looks like maybe CL 344512 is the fix.

**Comment by cherrymui** [comment]
This doesn't fail now. Probably fixed by CL https://go-review.googlesource.com/c/go/+/395879
