### ISSUE TITLE
x/pkgsite: Can't find GitLab project

### ISSUE THREAD

**Issue by abitrolly** [golang/go#50024]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/gitlab.com/abitrolly/dnf-go-gui
 
### What is your user agent?
 
Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0 
 
### Screenshot
  
![image](https://user-images.githubusercontent.com/8781107/145045113-bde49c5a-7c7a-4906-b282-36a97e259791.png)

### What did you do?
  
 Clicked Request button.
 
### What did you expect to see?
 
Indexed docs and dependencies for my project from https://gitlab.com/abitrolly/dnf-go-gui
 
### What did you see instead?

My project is not found.

**Comment by jamalc** [comment]
Your module does not have a valid module path.

This line should be `module gitlab.com/abitrolly/dnf-go-gui`
https://gitlab.com/abitrolly/dnf-go-gui/-/blob/master/go.mod#L1 

See the [modules reference](https://go.dev/ref/mod#go-mod-file) for more details.

**Comment by abitrolly** [comment]
Does it matter for command line tools that are not imported?

In any case is it possible to improve the error message to point to that?

**Comment by abitrolly** [comment]
Now I see the message is different. Haven't seen it before.

![image](https://user-images.githubusercontent.com/8781107/145648459-9032caaa-622e-4d8c-8c73-292d39379e93.png)

Changed the module name. I guess I need to wait for some cache to expire.

**Comment by abitrolly** [comment]
@jamalc just changed the name again https://gitlab.com/abitrolly/dnf-go-gui/-/commit/22a1ffde990bbc5817149369ed0b1a87d8c623d8 and cache is not expired. https://pkg.go.dev/gitlab.com/abitrolly/dnf-go-gui still complains about "gdnf" being note being a valid module path.

Also the spec https://go.dev/ref/mod#go-mod-file doesn't mention that module path should start with a domain name.
