### ISSUE TITLE
x/pkgsite: Package ffmpeg-go with Apache 2.0 License not recognized

### ISSUE THREAD

**Issue by scrouthtv** [golang/go#50021]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/u2takey/ffmpeg-go
 
### What is your user agent?
 
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0
 
### Screenshot
 
![grafik](https://user-images.githubusercontent.com/23227405/145035183-b38fb7d4-d4e9-47ba-85c2-6f3e8cdac985.png)
 
### What did you do?
 
1. Open  https://pkg.go.dev/github.com/u2takey/ffmpeg-go
 
### What did you expect to see?
 
The documentation for the `ffmpeg-go` package.
 
### What did you see instead?

Documentation not displayed due to license restrictions.

**Comment by jamalc** [comment]
The latest version of your module was published before you added the license. For pkg.go.dev to see the license you must publish a new version.
