### ISSUE TITLE
x/playground: show the go version

### ISSUE THREAD

**Issue by hyangah** [golang/go#50025]
The latest playgroud gives an option to choose between the released go version and the dev branch version, which is great. However, the meaning of "Go release"  was initially unclear to me. How about showing the precise version string for the stable released version instead of "Go release"?

<img width="844" alt="Screen Shot 2021-12-07 at 11 32 02 AM" src="https://user-images.githubusercontent.com/4999471/145068608-e89d00d4-81c6-449c-9984-1bbfef0b941c.png">

@findleyr

**Comment by findleyr** [comment]
I just submitted the first half of this: https://go-review.googlesource.com/c/playground/+/365854

I think @rsc will incorporate this endpoint into the UI.

**Comment by jimen0** [comment]
go.dev/play now shows the release version except for "Go dev branch". I believe this can now be closed. cc @seankhliao 😄
