### ISSUE TITLE
runtime/pprof: background GC goroutine sample have pprof labels

### ISSUE THREAD

**Issue by prattmic** [golang/go#50032]
[`gcBgMarkStartWorkers`](https://cs.opensource.google/go/go/+/master:src/runtime/mgc.go;l=1131;drc=master) starts several `gcBgMarkWorker` goroutines. This is called when starting the first GC. If the GC is triggered by a goroutine with pprof labels, then the GC worker goroutines will inherit the pprof labels.

cc @mknyszek @bcmills

**Comment by mknyszek** [comment]
It's worth noting that this can also happen after the first GC if `GOMAXPROCS` increases.
