### ISSUE TITLE
src: make.bash now requires $GOROOT_BOOTSTRAP to be set to use an existing Go toolchain in your $PATH

### ISSUE THREAD

**Issue by siebenmann** [golang/go#50037]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-0a15e7851a Tue Dec 7 22:33:39 2021 +0000 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
No.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/homes/hawklords/cks/.cache/go-build"
GOENV="/homes/hawklords/cks/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/homes/hawklords/cks/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/homes/hawklords/cks/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/data/code/go-lang/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/data/code/go-lang/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.18-0a15e7851a Tue Dec 7 22:33:39 2021 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/data/code/go-lang/go/src/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmpfs/go-build2431838020=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

If you have an existing Go toolchain on your $PATH, including Go 1.17, from commit 4300f105147dc0da9d1034704ad1cd24bedde5da onwards Go tip will fail to use it and instead will attempt to use one of $HOME/(sdk/go1.17 go1.17 go1.4) unless you set `$GOROOT_BOOTSTRAP`. If you don't have any of these (you may well not) and don't have `$GOROOT_BOOTSTRAP` set, the build fails with the fun error messages:

```
Building Go cmd/dist using /data/code/go-lang/v1.17. (go1.17.4 linux/amd64)
Building Go toolchain1 using /homes/hawklords/cks/go1.4.
go tool dist: FAILED: /homes/hawklords/cks/go1.4/bin/go install -gcflags=-l -tags=math_big_pure_go compiler_bootstrap bootstrap/cmd/...: fork/exec /homes/hawklords/cks/go1.4/bin/go: no such file or directory
```
If you set `$GOROOT_BOOTSTRAP`, things will work.

If it's unset, I think `make.bash` should start by trying to set `$GOROOT_BOOTSTRAP` by running `go env GOROOT`. Or at least do that before falling back to a Go 1.4 that may well not exist when people quite possibly have a perfectly good Go toolchain already available.

**Comment by ianlancetaylor** [comment]
Note that I see the same behavior before CL 369914.  With Go 1.17, with no $HOME/go1.4 directory and with Go 1.16 cmd/go on PATH

```
Building Go cmd/dist using /home/iant/go1.16. (go1.16.9 linux/amd64)
Building Go toolchain1 using /home/iant/go1.4.
go tool dist: FAILED: /home/iant/go1.4/bin/go install -gcflags=-l -tags=math_big_pure_go compiler_bootstrap bootstrap/cmd/...: fork/exec /home/iant/go1.4/bin/go: no such file or directory
```

So, yes, this should be fixed, but I don't think it's new.

**Comment by siebenmann** [comment]
For me this issue goes away (and `make.bash` builds) if I check out a08bbd964d, the commit `git log` reports as immediately before 4300f10514.

**Comment by siebenmann** [comment]
For me this issue has gone away from the new commit f5b5939c28ecb8b8c0897584fed78589c27348f6 onward. Also, my report here seems to be a duplicate of reports made in issue #44505 after the first commit landed.

**Comment by ianlancetaylor** [comment]
Yes, this is expected to be fixed now.  Thanks.
