### ISSUE TITLE
x/crypto/ssh: Why does the timeout parameter only work on tcp establishment?

### ISSUE THREAD

**Issue by xue8** [golang/go#50046]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.6 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
warning: GOPATH set to GOROOT (/Users/xuerongyue/soft/golang/go) has no effect
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/xuerongyue/Library/Caches/go-build"
GOENV="/Users/xuerongyue/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xuerongyue/soft/golang/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xuerongyue/soft/golang/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/Users/xuerongyue/soft/golang/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/xuerongyue/soft/golang/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xuerongyue/git/github/bao/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r_/82trt7cs6v9_njvn04h4lbym0000gn/T/go-build2567262407=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
https://go.dev/play/p/g1fBEI6l9Qp

When using `ssh.Dial` to establish an ssh connection, if the server network is reachable, but the server fails to send any data to the client because of the server failure, the client `hang` is left standing, even though the timeout parameter has been set. (See sample code)

Checking the code of `x/crypto/ssh` shows that the timeout parameter only works in the tcp establishment phase (as shown in the three handshakes), not in the ssh authentication login phase (as shown in the phase outside the three handshakes).

![image](https://user-images.githubusercontent.com/24730001/145245044-c7f10e3f-352e-425c-871e-d86412c51955.png)

For what reason does the timeout setting here not work in the ssh authentication phase?

### What did you expect to see?

The timeout parameter works on the ssh establishment.

### What did you see instead?

The timeout parameter only works on tcp establishment.

**Comment by seankhliao** [comment]
As the docs say https://pkg.go.dev/golang.org/x/crypto/ssh#ClientConfig :
> 	// Timeout is the maximum amount of time for the TCP connection to establish.
	//
	// A Timeout of zero means no timeout.
	Timeout time.Duration

See https://github.com/golang/go/issues/26643#issuecomment-451912519
