### ISSUE TITLE
Golang Generics: Type param for any function

### ISSUE THREAD

**Issue by nataneb32** [golang/go#50047]
Is there a way to refer to create a generic for every func?

```
func example[T ~func](f T) T {
   ...
}
```
Usage
```
func a(string)
func b(int) int

example(a)
example(b)
```

**Comment by nataneb32** [comment]
Depending on the response i will reformulate the question.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
