### ISSUE TITLE
runtime/slice.go: the value of the "newcap" is  incorrect in func "growslice"

### ISSUE THREAD

**Issue by zhucan** [golang/go#50041]
### What version of Go are you using (`go version`)?
![image](https://user-images.githubusercontent.com/13997135/145170930-ad86dba3-48e2-40ec-af52-13ce1aebd8e7.png)

### What operating system and processor architecture are you using (`go env`)?
![image](https://user-images.githubusercontent.com/13997135/145171053-0c0bb189-b51a-4e58-aa53-57bf14a399f2.png)

### What did you do?
a := make([]int, 0)
append(a, 1,2,3)

### What did you expect to see?
see the value of the newcap is zero.

### What did you see instead?
![image](https://user-images.githubusercontent.com/13997135/145171265-5632ba75-7fea-4a00-aab4-4b85b05e57dd.png)

if the old.cap is 0,  the newcap maybe is 0, because of we hadn't do "newcap = cap"

**Comment by zhouguangyuan0718** [comment]
The function is optimized. The excution order is different from the source code . Compiler can guarantee the logic of functions not be changed after optimizing.

**Comment by seankhliao** [comment]
Please don't use screenshots and also include code that actually demonstrates the issue

https://go.dev/play/p/GHOtDLIIsRJ

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by zhucan** [comment]
> The function is optimized. The excution order is different from the source code . Compiler can guarantee the logic of functions not be changed after optimizing.

I don't understand what you mean

**Comment by randall77** [comment]
Running with an optimized binary means that debugging information can be incomplete or misleading. That I think is the case here (`cap` and `newcap` are phi-connected, which is a tricky case). It's possible that this could be improved, but not a terribly high priority at the moment. If you require precise debugging information, it is best to turn optimizations off (`-gcflags=-N -l`).
