### ISSUE TITLE
affected/package: compiler

### ISSUE THREAD

**Issue by calvinreu** [golang/go#50049]
### What version of Go are you using (1.17.3)?

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/calvinreu/.cache/go-build"
GOENV="/home/calvinreu/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/calvinreu/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/calvinreu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/calvinreu/Documents/evosim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2451401394=/tmp/go-build -gno-record-gcc-switches")?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

for _, i := range sliceInSlice {
		i = make([]float32, 10)
		for _, j := range i {
			j = 200
		}
	}

https://go.dev/play/p/-u43s7slS3r

### What did you expect to see?
no error

### What did you see instead?
j not used

**Comment by randall77** [comment]
This is intentional. A write to a variable is not a use.
Use "_ = j" if you want to introduce a nominal use of a variable.
