### ISSUE TITLE
gcc failed affected/package: 

### ISSUE THREAD

**Issue by miketsukuba** [golang/go#50055]
### What version of Go are you using (`go version`)?
1.13
<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
no

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/2"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build925532583=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
I use go version 1.13 amd64, gcc, 7.5.0 on ubuntu,
I do not have problem with hello.go that mentioned in the previous issues:
package main

// const int x = 42;
import "C"

import "fmt"

func main() {
  fmt.Println(int(C.x))
}

but when I build another program that uses td-lib it shows gcc error:
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.

as i received a reply, it is due to low RAM (d terminated with signal 9 [Killed])

**Comment by ianlancetaylor** [comment]
This looks like not enough RAM to actually run GCC.  There isn't anything we can change in the Go project to fix that problem, so I'm going to close this issue.  Please comment if you disagree.

Note that Go 1.13 is no longer supported.  The most recently supported version of Go is 1.16.  Also GCC 7.5 is fairly old.
