### ISSUE TITLE
runtime: cgocall "Attempted to use unknown class" on darwin/amd64

### ISSUE THREAD

**Issue by uptycs-rgoel** [golang/go#50079]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes. I updated mac book pro (intel) yesterday to macOs Monterey and this issue started coming. I did not take backup, so I have to reset everything again. 2-3 days will go in it :(
I should have waited for 12.1 release. Also I though google is on top of things, so I did not expect this problem since Monterey was released long back.

Anyway, whatever happened, happened. Please provide solution ASAP.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> </summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rgoel/Library/Caches/go-build"
GOENV="/Users/rgoel/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/rgoel/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/rgoel/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/rgoel/gitlocal/uptycs-cloudquery/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z3/jrxgd4k547g8rg3lhdh3gss80000gn/T/go-build192539296=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Just upgraded my mac from Big Sur to the 12.0.1 
My Mac conf:
MacBook Pro (15-inch, 2018)
6 core / 32 gb ram
Radeon Pro 560X 4 GB

I think it is a problem with cgo library which might be using dependencies from old mac version. 

### What did you expect to see?
make for our project successful

### What did you see instead?
objc[1536]: Attempt to use unknown class 0x7ff8512fd360.
SIGABRT: abort
PC=0x7ff80fac9dfe m=0 sigcode=0
signal arrived during cgo execution
[Terminal Saved Output-make-failing.log](https://github.com/golang/go/files/7687799/Terminal.Saved.Output-make-failing.log)

**Comment by davecheney** [comment]
How can someone reproduce your issue so they can investigate the cause?

**Comment by seankhliao** [comment]
what does `make` do?

**Comment by cherrymui** [comment]
Maybe a dup of #49138 . Are use running with the race detector?  Thanks.

**Comment by wvell** [comment]
@uptycs-rgoel do you still have this problem when using gotip? Using gotip works for me.
