### ISSUE TITLE
import

### ISSUE THREAD

**Issue by pxy666** [golang/go#50087]
[{
	"resource": "/d:/Go_WorkSpace/src/gee-cache/n2-single-node/cache.go",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "BrokenImport",
		"target": {
			"$mid": 1,
			"external": "https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source%3Dgopls#BrokenImport",
			"path": "/golang.org/x/tools/internal/typesinternal",
			"scheme": "https",
			"authority": "pkg.go.dev",
			"query": "utm_source=gopls",
			"fragment": "BrokenImport"
		}
	},
	"severity": 8,
	"message": "could not import geecache/lru (cannot find package \"geecache/lru\" in any of \n\tD:\\Go\\src\\geecache\\lru (from $GOROOT)\n\tD:\\Go_WorkSpace\\src\\geecache\\lru (from $GOPATH))",
	"source": "compiler",
	"startLineNumber": 4,
	"startColumn": 2,
	"endLineNumber": 4,
	"endColumn": 16
}]

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
