### ISSUE TITLE
x/text/encoding: gbk encoding can not encoding rune `0x1E3F`

### ISSUE THREAD

**Issue by xiongjiwei** [golang/go#50088]
### What did you do?

https://go.dev/play/p/6Fi9SmefcEG

### What did you expect to see?

according to https://github.com/whatwg/encoding/blob/be3337450e7df1c49dca7872153c4c4670dd8256/index-gb18030.txt#L7540. Rune `0x1E3F` can be decoded and encoded.

**Comment by seankhliao** [comment]
The whatwg spec you linked is for GB18030 not GBK

https://go.dev/play/p/aBqMLoCfFy1
