### ISSUE TITLE
json.NewEncoder.Encode为什么要添加换行符？

### ISSUE THREAD

**Issue by RongStudy** [golang/go#50091]
https://github.com/golang/go/blob/8ff254e30ba9d9c13747fe42213c3f54b47c58e7/src/encoding/json/stream.go#L217
添加换行符仅仅是为了输出美观吗？？难道不需要有个参数来设置这个"\n"？

**Comment by xmx** [comment]
上面的注释已经说清除了，美观是一方面，如果是纯数字类型Encode，没有`\n`分割就傻傻的分不清，请看下面的示例：
```go
func TestEncode(t *testing.T) {
	buf := &bytes.Buffer{}
	_ = json.NewEncoder(buf).Encode(1)
	_ = json.NewEncoder(buf).Encode(2)
	t.Logf("%s", buf.String())
}
```
打印结果的是
```
1
2
```

如果没有`\n`的结果就是：
```
12
```
这样就分不清是Encode了`1`和`2`，还是Encode了`12`

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

See also https://github.com/golang/go/issues/43961#issuecomment-769722443
