### ISSUE TITLE
go/build: Build error of latest gotip under windows/amd64

### ISSUE THREAD

**Issue by tinytina2021** [golang/go#50092]
### What version of Go are you using (`go version`)?

<pre>
1.17.4
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
windows/amd64

</pre></details>

### What did you do?

go install golang.org/dl/gotip@latest
gotip download

### What did you expect to see?
Successful build of latest gotip

### What did you see instead?

```
C:\Users\Tina Ng\go>go install golang.org/dl/gotip@latest
go: downloading golang.org/dl v0.0.0-20211209150512-4ab242f9ec73

C:\Users\Tina Ng\go>gotip download
Updating the go development tree...
remote: Finding sources: 100% (205/205)
remote: Total 205 (delta 87), reused 182 (delta 87)
Receiving objects: 100% (205/205), 396.04 KiB | 3.74 MiB/s, done.
Resolving deltas: 100% (87/87), completed with 32 local objects.
From https://go.googlesource.com/go
 * branch            master     -> FETCH_HEAD
   a19e72c..8ff254e  master     -> origin/master
Previous HEAD position was a19e72c doc/go1.18: move fuzzing to tools section
HEAD is now at 8ff254e cmd/compile: preserve 'any' type alias in unified IR
Building Go cmd/dist using C:\Users\Tina Ng\go\go-1_17_4
Building Go toolchain1 using C:\Users\Tina Ng\go\go-1_17_4.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
go tool compile: exit status 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x1b8 pc=0xabc95c]

goroutine 1 [running]:
internal/poll.execIO(0xc00010e280?, 0xc00002f380?)
        C:/Users/Tina Ng/sdk/gotip/src/internal/poll/fd_windows.go:148 +0x1c
internal/poll.(*FD).Write(0xc00010e280, {0xc000030140, 0x9f, 0xa0})
        C:/Users/Tina Ng/sdk/gotip/src/internal/poll/fd_windows.go:695 +0x33b
os.(*File).write(...)
        C:/Users/Tina Ng/sdk/gotip/src/os/file_posix.go:48
os.(*File).Write(0xc000006018, {0xc000030140?, 0x9f, 0xc00007f990?})
        C:/Users/Tina Ng/sdk/gotip/src/os/file.go:176 +0x65
fmt.Fprintf({0x1494320, 0xc000006018}, {0x13255ae, 0x10}, {0xc00007f990, 0x3, 0x3})
        C:/Users/Tina Ng/sdk/gotip/src/fmt/print.go:205 +0x9b
fmt.Printf(...)
        C:/Users/Tina Ng/sdk/gotip/src/fmt/print.go:213
cmd/internal/objabi.versionFlag.Set({}, {0xc00001c18b, 0x4})
        C:/Users/Tina Ng/sdk/gotip/src/cmd/internal/objabi/flag.go:122 +0x33e
flag.(*FlagSet).parseOne(0xc00005a060)
        C:/Users/Tina Ng/sdk/gotip/src/flag/flag.go:968 +0x3c2
flag.(*FlagSet).Parse(0xc00005a060, {0xc0000323f0?, 0x2?, 0x0?})
        C:/Users/Tina Ng/sdk/gotip/src/flag/flag.go:1005 +0x4f
flag.Parse(...)
        C:/Users/Tina Ng/sdk/gotip/src/flag/flag.go:1036
cmd/internal/objabi.Flagparse(0xc00005a060?)
        C:/Users/Tina Ng/sdk/gotip/src/cmd/internal/objabi/flag.go:38 +0xb4
cmd/compile/internal/base.ParseFlags()
        C:/Users/Tina Ng/sdk/gotip/src/cmd/compile/internal/base/flag.go:176 +0x325
cmd/compile/internal/gc.Main(0x134f4b0)
        C:/Users/Tina Ng/sdk/gotip/src/cmd/compile/internal/gc/main.go:105 +0x46f
main.main()
        C:/Users/Tina Ng/sdk/gotip/src/cmd/compile/main.go:55 +0xdd
^C^C
C:\Users\Tina Ng\go>Terminate batch job (Y/N)?
y
'y' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Tina Ng\go>
```

**Comment by ALTree** [comment]
Thanks for reporting.

Did this started recently? Does it happen every time, or is it nondeterministic? Any chance of a bisect?

**Comment by tinytina2021** [comment]
Today I tried again using the latest go 1.17.5 release and I also disabled my antivirus file-protection temporarily and was able to successfully complete the build:

C:\Users\Tiny Ng\go>go install golang.org/dl/gotip@latest

C:\Users\Tiny Ng\go>gotip download
Updating the go development tree...
remote: Finding sources: 100% (868/868)
remote: Total 868 (delta 116), reused 470 (delta 116)
Receiving objects: 100% (868/868), 2.61 MiB | 900.00 KiB/s, done.
Resolving deltas: 100% (116/116), completed with 41 local objects.
From https://go.googlesource.com/go
 * branch              master     -> FETCH_HEAD
   8ff254e3..1afa432a  master     -> origin/master
Previous HEAD position was 8ff254e3 cmd/compile: preserve 'any' type alias in unified IR
HEAD is now at 1afa432a go/types, types2: record (top-level) union types
Building Go cmd/dist using C:\Users\Tiny Ng\go\go-1_17_5
Building Go toolchain1 using C:\Users\Tiny Ng\go\go-1_17_5.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for windows/amd64.
# runtime/cgo
   Creating library $WORK\b224\_cgo_.lib and object $WORK\b224\_cgo_.exp
---
Installed Go for windows/amd64 in C:\Users\Tiny Ng\sdk\gotip
Installed commands in C:\Users\Tiny Ng\sdk\gotip\bin
Success. You may now run 'gotip'!

C:\Users\Tiny Ng\go>which gotip
C:\Users\Tiny Ng\go\bin\gotip.EXE

C:\Users\Tiny Ng\go>gotip version
go version devel go1.18-1afa432a Tue Dec 14 01:48:22 2021 +0000 windows/amd64

C:\Users\Tiny Ng\go>

I reckon the earlier build error I reported must have been due to my antivirus protection being enabled while the build was progressing.
