### ISSUE TITLE
reflect/value.go: rune slice operation is private

### ISSUE THREAD

**Issue by zyxkad** [golang/go#50106]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 darwin/amd64
</pre>

### What did you expect to see?
I thought the line `301` func may public, like `reflect.Value.Bytes()`
```golang
/*299*/ // runes returns v's underlying value.
// It panics if v's underlying value is not a slice of runes (int32s).
/*301*/ func (v Value) runes /*That's private function? */ () []rune {
	v.mustBe(Slice)
	if v.typ.Elem().Kind() != Int32 {
		panic("reflect.Value.Bytes of non-rune slice")
	}
	// Slice is always bigger than a word; assume flagIndir.
	return *(*[]rune)(v.ptr)
}
```
**I don't think you want to private the function, because I don't find any code call this function**

Include line `1938`, `setRune()`
```golang
/*1936*/ // setRunes sets v's underlying value.
// It panics if v's underlying value is not a slice of runes (int32s).
/*1938*/ func (v Value) setRunes(x []rune) {
	v.mustBeAssignable()
	v.mustBe(Slice)
	if v.typ.Elem().Kind() != Int32 {
		panic("reflect.Value.setRunes of non-rune slice")
	}
	*(*[]rune)(v.ptr) = x
}
```

**Comment by ianlancetaylor** [comment]
The `runes` method is called by `cvtRunesString` which is used indirectly by the `Convert` method.  The `setRunes` method is called by `makeRunes` which is also used indirectly by `Convert`.

**Comment by zyxkad** [comment]
> The `runes` method is called by `cvtRunesString` which is used indirectly by the `Convert` method. The `setRunes` method is called by `makeRunes` which is also used indirectly by `Convert`.

Thanks, but why not public it?

**Comment by ianlancetaylor** [comment]
You can invoke the functionality via the `Convert` method, so there doesn't seem to be a reason to export these more specific methods.  In general a smaller API is simpler to understand and simpler to maintain, so we should only add new exported methods if there is a good reason to do so.
