### ISSUE TITLE
net/netip: ParseAddr gives different values with same input

### ISSUE THREAD

**Issue by capnspacehook** [golang/go#50111]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-766f89b5c6 Fri Dec 10 19:26:50 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/capnspacehook/.cache/go-build"
GOENV="/home/capnspacehook/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/capnspacehook/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/capnspacehook/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/capnspacehook/Documents/git/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/capnspacehook/Documents/git/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.18-766f89b5c6 Fri Dec 10 19:26:50 2021 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/capnspacehook/Documents/git/go/src/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3691310336=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Tested that `netip.ParseAddr` would produce the same value twice when given the same input:

https://go.dev/play/p/ZpqXiudtmA_P?v=gotip

### What did you expect to see?

```
true
netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffff00000000}, z:(*intern.Value)(0xc0000b4048)}, netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffff00000000}, z:(*intern.Value)(0xc0000b4048)}
```

### What did you see instead?

```
false
netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffff00000000}, z:(*intern.Value)(0xc0000b4048)}, netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffff00000000}, z:(*intern.Value)(0xc0000b4030)}
```

---

I found this bug and a few others while working on #49367.

**Comment by bradfitz** [comment]
Expanded example a bit: https://go.dev/play/p/3uzuOmxzN1c?v=gotip

/cc @josharian @danderson @mdlayher

**Comment by bradfitz** [comment]
And https://go.dev/play/p/owhCTtsY5Bn?v=gotip ... it stringifies without the zone, despite the `Zone` method returning `"0"`.

**Comment by bradfitz** [comment]
Ah! The 4-in-6 special case to stringify it with the dotted quad form omits the zone check:

```go
func (ip Addr) String() string {
        switch ip.z {
        case z0:
                return "invalid IP"
        case z4:
                return ip.string4()
        default:
                if ip.Is4In6() {
                        // TODO(bradfitz): this could alloc less.                                                                                     
                        return "::ffff:" + ip.Unmap().String()
                }
                return ip.string6()
        }
}
```

**Comment by bradfitz** [comment]
I assume this is `okay-for-after-beta1` too, @golang/release, but will leave that to y'all to tag.

**Comment by bradfitz** [comment]
Thanks, @capnspacehook!
