### ISSUE TITLE
syscall: syscall.Socket

### ISSUE THREAD

**Issue by colin84** [golang/go#50122]
go version 1.17
system： uos (linux arm64) 
the next code sometimes return error: socket: operation not permitted.
_, err := syscall.Socket(2, 1|syscall.SOCK_NONBLOCK|syscall.SOCK_CLOEXEC, 0)
if err != nil {
panic(os.NewSyscallError("socket", err))
}

**Comment by MatejMagat305** [comment]
you are in termux or laptom or other? if you are in termux/proot linux on termux there no way how request permision, if you are on other platform you schould try command sudo and I highly recomend use syscall or unix constants instead of number............

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
