### ISSUE TITLE
x/website: Installation issues in windows

### ISSUE THREAD

**Issue by SubratBarik** [golang/go#50123]
### What is the URL of the page with the issue?
 
 I am trying to install Revel framework in my windows system but couldn't proceed. I am new to Go.
 
### What is your user agent?
 

 
 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
 
 
### Screenshot
 

 
 https://ibb.co/cgs900p
 
### What did you do?
 

 
 I am trying to install Revel framework but it is not working  and showing some errors. I am following below URL: https://revel.github.io/tutorial/gettingstarted.html
 
 I am using go version: go1.17.5 windows/amd64
 
### What did you expect to see?
 
 Proper and working installation but seems like I am missing something here. Please advice.
 
### What did you see instead?

Screenshot: https://ibb.co/q9zyWN2

Errors: Please check the lines below

C:\Users\subrata.DESKTOP-EFH837L\gocode\paysignet>go get github.com/revel/revel
go get: module github.com/fsnotify/fsnotify: Get "https://proxy.golang.org/github.com/fsnotify/fsnotify/@v/list": read tcp [2405:201:8001:5821:1d0b:4845:ed9e:2569]:49197->[2404:6800:4009:831::2011]:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
go get: module github.com/go-stack/stack: Get "https://proxy.golang.org/github.com/go-stack/stack/@v/list": read tcp [2405:201:8001:5821:1d0b:4845:ed9e:2569]::4845:ed9e:2569]:49197->[2404:6800:4009:831::2011]:443: wsarecv: A connection attempt failed because the connected party did not properly resod of time, or espond after a period of time, or established connection failed because connected host has failed to respond.
go get: module github.com/mattn/go-colorable: Get "https://proxy.golang.org/github.com/mattn/go-colorable/@v/list": read tcp [2405:201:8001:5821:1d0b:4845:ed9821:1d0b:4845:ed9e:2569]:49197->[2404:6800:4009:831::2011]:443: wsarecv: A connection attempt failed because the connected party did not propr a period of timerly respond after a period of time, or established connection failed because connected host has failed to respond.
go get: module github.com/revel/config: Get "https://proxy.golang.org/github.com/revel/config/@v/list": read tcp [2405:201:8001:5821:1d0b:4845:ed9e:2569]:49195:ed9e:2569]:49197->[2404:6800:4009:831::2011]:443: wsarecv: A connection attempt failed because the connected party did not properly respondf time, or establ after a period of time, or established connection failed because connected host has failed to respond.
go get: module github.com/revel/pathtree: Get "https://proxy.golang.org/github.com/revel/pathtree/@latest": read tcp [2405:201:8001:5821:1d0b:4845:ed9e:2569]::4845:ed9e:2569]:57205->[2404:6800:4009:831::2011]:443: wsarecv: A connection attempt failed because the connected party did not properly resod of time, or espond after a period of time, or established connection failed because connected host has failed to respond.
go get: module golang.org/x/net/websocket: Get "https://proxy.golang.org/golang.org/x/net/websocket/@v/list": read tcp [2405:201:8001:5821:1d0b:4845:ed9e:25690b:4845:ed9e:2569]:57205->[2404:6800:4009:831::2011]:443: wsarecv: A connection attempt failed because the connected party did not properly rriod of time, or espond after a period of time, or established connection failed because connected host has failed to respond.
go get: module gopkg.in/natefinch/lumberjack.v2: Get "https://proxy.golang.org/gopkg.in/natefinch/lumberjack.v2/@v/list": read tcp [2405:201:8001:5821:1d0b:488001:5821:1d0b:4845:ed9e:2569]:57205->[2404:6800:4009:831::2011]:443: wsarecv: A connection attempt failed because the connected party did nod after a period t properly respond after a period of time, or established connection failed because connected host has failed to respond.
go get: module gopkg.in/stack.v0: Get "https://proxy.golang.org/gopkg.in/stack.v0/@v/list": read tcp [2405:201:8001:5821:1d0b:4845:ed9e:2569]:57205->[2404:680:57205->[2404:6800:4009:831::2011]:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a perstablished conneciod of time, or established connection failed because connected host has failed to respond.

Please help

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
