### ISSUE TITLE
x/pkgsite: package removal request for github.comAquarian-Age/{sjqm,zwds}

### ISSUE THREAD

**Issue by Aquarian-Age** [golang/go#50132]
### What is the path of the package that you would like to have removed?

https://github.com/Aquarian-Age/sjqm
https://github.com/Aquarian-Age/zwds

### Are you the owner of this package?

Yes

### What is the reason that you could not retract this package instead?

https://github.com/Aquarian-Age/sjqm
https://github.com/Aquarian-Age/zwds
I want to delete all the contents of the above two paths　Thank you

**Comment by jamalc** [comment]
Done.
