### ISSUE TITLE
affected/package: go get

### ISSUE THREAD

**Issue by dududko** [golang/go#50153]
### What version of Go are you using (`go version`)?

<pre>
➜ go version
go version go1.17.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
➜ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/dududko/Library/Caches/go-build"
GOENV="/Users/dududko/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/dududko/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/dududko/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/github/my/repo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lz/4l5hq8912vxdnzzxwfvb8zyh0000gn/T/go-build1102189466=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
I am trying to add a specific version of public dependency with `go.mod` not in the root of the repo but in the catalog `/go`. And I get the following *error*.
```
➜ go get -v github.com/trinsic-id/sdk/go@v1.2.0
go: downloading github.com/trinsic-id/sdk v1.2.0
go get: module github.com/trinsic-id/sdk@v1.2.0 found, but does not contain package github.com/trinsic-id/sdk/go
```

But it works if I if specify commit.
```
➜ go get -v github.com/trinsic-id/sdk/go@d047d64488e0ad99e291eb0e4e67fbd03c804a45
go: downloading github.com/trinsic-id/sdk/go v0.0.0-20211124202954-d047d64488e0
```

This is the first dependency I encounter this issue. Other dependencies are processed well but all of them have go.mod file in the root.

More details:
- Git is globally configured to use ssh.
- Cleaning gomod cache does not help.

**Comment by seankhliao** [comment]
modules not at the root of a repo have special requirements for tags

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
