### ISSUE TITLE
sync/atomic: test failures on qemu-aarch64

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#50188]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/parallels/.cache/go-build"
GOENV="/home/parallels/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/parallels/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/parallels/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build288752857=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

On Linux (amd64),

```sh
GOARCH=arm64 go test -c sync/atomic
qemu-aarch64 ./atomic.test
```

The QEMU version is here:
```
$ qemu-aarch64 --version
qemu-aarch64 version 4.2.1 (Debian 1:4.2-3ubuntu6.18)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers
```

### What did you expect to see?

The tests pass

### What did you see instead?

Some tests failed

```
--- FAIL: TestStoreLoadSeqCst32 (0.00s)
    atomic_test.go:1246: store/load are not sequentially consistent: 205/205 (206)
    atomic_test.go:1246: store/load are not sequentially consistent: 205/205 (206)
--- FAIL: TestStoreLoadSeqCst64 (0.00s)
    atomic_test.go:1291: store/load are not sequentially consistent: 534/534 (535)
    atomic_test.go:1291: store/load are not sequentially consistent: 534/534 (535)
FAIL
```

**Comment by cherrymui** [comment]
QEMU user mode emulation is not a supported platform and known to have bugs in the past. Is it reproducible  with full system emulation or a real hardware? Thanks.

**Comment by hajimehoshi** [comment]
> Is it reproducible with full system emulation or a real hardware? Thanks.
Hm, I'll try later...

**Comment by hajimehoshi** [comment]
https://bugs.launchpad.net/qemu/+bug/1908626

This seems a bug in QEMU. I'll try the latest QEMU later.

**Comment by cherrymui** [comment]
Thanks! We can close this one (for now).
