### ISSUE TITLE
x/tools/gopls: analyze Fuzz targets in the go/analysis/tests analyzer

### ISSUE THREAD

**Issue by hyangah** [golang/go#50198]
Idea came from https://github.com/golang/go/issues/46896#issuecomment-995201714

f.Fuzz takes `any` (aka `interface{}`) type but the parameter must be a fuction with no return value whose first argument is *T and whose remaining arguments match the matching testin.F.Add call.

Add an analyzer to detect misuse of Fuzz API.

**Comment by hyangah** [comment]
We think this is useful outside gopls and we can consider to add this to vet in the future.

**Comment by timothy-king** [comment]
Roughly a dup of https://github.com/golang/go/issues/46218. The suggestion for putting this into go/analysis/passes/tests/tests.go is a good one. The only real reason I can see to delay going into cmd/vet is that cmd/vet is under code freeze ATM.

**Comment by findleyr** [comment]
Let's close this as a dupe. We can start #46218 in gopls, but I think it eventually belongs in vet.

**Comment by findleyr** [comment]
Err, as I'm putting together gopls@v0.8.0 planning, I think it would be nice to have a tracking issue for just the gopls part of this. Reopening.

**Comment by findleyr** [comment]
Minor correct: fuzz targets can have return values.
