### ISSUE TITLE
cmd/vet: go 1.18 vet undocumented behavior change with use of -vettool

### ISSUE THREAD

**Issue by leighmcculloch** [golang/go#50195]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18beta1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

No, this issue does not reproduce with go1.17.5.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/leighmcculloch/.local/bin"
GOCACHE="/Users/leighmcculloch/Library/Caches/go-build"
GOENV="/Users/leighmcculloch/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/leighmcculloch/.local/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/leighmcculloch/.local/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/leighmcculloch/.local/bin/go/latest"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/leighmcculloch/.local/bin/go/latest/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18beta1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD="/Users/leighmcculloch/Code/stellar--go/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/q5/xb4dl4bs3cs32khlg0ryy0vw0000gp/T/go-build3668798394=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I ran go vet using the `-vettool` option.

```
go vet -all -composites=false -unreachable=false -tests=false ./...
go vet -vettool=$(which shadow) ./...
```

### What did you expect to see?

I expected to see `go vet`, when run with `-vettool`, to only run the vettool and not to run all the other vet checks. This is the behavior of go vet prior to Go 1.18.

I also expected to see the shadow tool get used to vet the code.

### What did you see instead?

I saw `go vet` output errors about composites, and I saw no outputs about issues that would normally be identified when running with `-vettool`.

It seems like the -vettool option is no longer taking any affect.

This issue is related to https://github.com/stellar/go/pull/4143.

**Comment by leighmcculloch** [comment]
I've attempted to reproduce this on another shell, and now I'm not seeing the same issue, so there's something environmental at play here that has happened on my local machine once, and is happening consistently inside GitHub Actions.

**Comment by leighmcculloch** [comment]
Ok, I believe the issue is the way we install the shadow tool in our scripts. We are using `go get` to do the install, which won't actually affect an install of a binary with Go 1.18.

**Comment by timothy-king** [comment]
Can you include the [possibly sanitized] output of `go vet -x` or `go vet -n`?
