### ISSUE TITLE
spec: document that type parameters are not permitted as constant declaration types

### ISSUE THREAD

**Issue by gazerro** [golang/go#50202]
The compilation of the following program fails with error `./prog.go:4:10: invalid constant type P`

```
package main

func f[P int]() {
	const y P = 5
}

func main() {}
```

but this behavior is not documented in the spec.

From the spec 5 is assignable to P because it is an untyped constant representable by a value of type P.

**Comment by ianlancetaylor** [comment]
CC @griesemer 

@gazerro Are you looking at https://tip.golang.org/ref/spec?

**Comment by griesemer** [comment]
I believe this is not yet fully documented in the in-progress spec. But here it is: type parameters cannot be constant types. While `5` can be stored in a variable of type `P`, it cannot be the value of a constant of type `P`.  Specifically, and this is documented in the section on conversions, if a constant is converted to a type parameter, say `P(5)`, the result is a non-constant value.

Leaving open until fully documented.

**Comment by gazerro** [comment]
> @gazerro Are you looking at https://tip.golang.org/ref/spec?

Yes.
