### ISSUE TITLE
x/website/internal/dl: provide json listing in version order

### ISSUE THREAD

**Issue by zx2c4** [golang/go#50201]
https://go.dev/dl/?mode=json gives all the current stable versions in descending order. Because they're sorted, this makes it easy to do things with tools like `jq`, without having to work out any finicky custom version-sort comparer.

https://go.dev/dl/?mode=json&include=all, however, gives all versions -- stable, archived, unstable -- out of order. This makes it very annoying to deal with from little tools like `jq`, since it's not trivial to sort version numbers.

Instead, we should sort the latter URL in the same descending order as the former URL.

CC @dmitshur

**Comment by dmitshur** [comment]
Since the suggestion here is to make &include=all give versions in sorted order, I think that means #47367 needs to be fixed first. Otherwise when there's more than 1 pre-release version, it won't be possible to rely on their order.

**Comment by zx2c4** [comment]
Didn't know about that; thanks. I'll look into it.

**Comment by zx2c4** [comment]
@dmitshur - The CL should now handle everything mentioned. Is there anything else needed?

**Comment by dmitshur** [comment]
Thanks. In general it looks good, I left minor comments.

As I mentioned on the CL, I expect this change to not to be disruptive, and one that we can make, but it's hard to know for sure in advance how smoothly it'll go. Since we're in a quiet week and right before holidays, let's defer next steps here to January.

**Comment by zx2c4** [comment]
Okay. Addressed your comments. Will plan on this being merged in January.
