### ISSUE TITLE
reflect: Type parameters name has ']'

### ISSUE THREAD

**Issue by eudore** [golang/go#50208]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18beta1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go:/root/hk-go:/data/web/golang"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18beta1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2104080393=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```go
package main

import (
	"fmt"
	"reflect"
)

type User struct{}
type Controller[T any] struct{}

func main() {
	i := reflect.TypeOf(new(Controller[User])).Elem()
	fmt.Println(i.String())
	fmt.Println(i.Name())
	fmt.Println(i.PkgPath())
}
```

### What did you expect to see?

I don’t know what the correct Type Parameters name is, but there shouldn’t be a ']' at the end. 

Intercept the string after the'.' in `src/reflect/type.go rtype.Name`.

### What did you see instead?

```
main.Controller[main.User]
User]
main
```

**Comment by ALTree** [comment]
cc  @rsc @ianlancetaylor as per owners.
