### ISSUE TITLE
x/website: Language Specification: Visible anchors for linkable sections

### ISSUE THREAD

**Issue by Deleplace** [golang/go#50210]
### What is the URL of the page with the issue?
 
 https://go.dev/ref/spec
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/13508141/146359991-2ffb242d-8d8e-46f2-8bdb-58c231c7aafa.png)
  
### What did you do?
 
 I wanted to create a direct hyperlink to [the section String concatenation](https://go.dev/ref/spec#String_concatenation) and add it to a webpage in another Go-related website.
 
### What did you expect to see?
 
Feature request: all the section headings (h2, h3, h4) would come with a trailing ¶ as a visual indicator for "Click here to get the direct URL to this section". Optionally, the ¶ char only shows up when the mouse approaches the heading. (All of this is the existing behaviour in all package pages at [pkg.go.dev](https://pkg.go.dev/github.com/shuLhan/share/lib/io#IsDirEmpty))
 
![image](https://user-images.githubusercontent.com/13508141/146360579-27d6df21-6279-4068-b02b-b4501d43f62e.png)

### What did you see instead?

- Section headings are not hyperlinks
- The h2 and h3 have links in the Table of Contents, which makes link creation easier. But not the h4.
- Almost all of the h2, h3, h4 already have an `id` attribute. This is great, let's make good use of it! I could create my link to the section "String concatenation", but I had to inspect the page HTML for this.
- A few `id` attributes are missing: Simple slice expressions, Full slice expressions, etc.

**Comment by ALTree** [comment]
I had the same issue the other day. I think the old specification page on golang.org had visible anchors, because I remember using them in the past; so this is a recent regression due to the website migration.

**Comment by mvdan** [comment]
Coming from https://github.com/golang/go/issues/56009 (a duplicate now closed), I'd like to see the same improvement to all structured documentation pages with headings under go.dev as well. For example, https://go.dev/ref/mod is a regular pain point for me, as I want to point other Go users to specific parts of the large page. cc @bcmills

**Comment by mvdan** [comment]
I believe https://github.com/golang/go/issues/68596 resolved this, even though it was filed much later. See https://github.com/golang/go/issues/70827 for a follow-up of mine where the anchors only show up if you hover over exactly where they would appear, which makes them hard to discover currently.
