### ISSUE TITLE
x/playground: The default "Report an issue" link says "x/website" in issue title

### ISSUE THREAD

**Issue by Deleplace** [golang/go#50219]
### What is the URL of the page with the issue?
 
 https://go.dev/play/
  
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/13508141/146399437-369e1179-23e9-40c0-9afc-274a8a4f968c.png)
  
### What did you do?
 
Click the "Report an issue" link in the footer.
  
### What did you expect to see?
 
 The "New issue page" with title placeholder "x/playground:"
 
### What did you see instead?

 The "New issue page" with title placeholder "x/website:"

**Comment by Deleplace** [comment]
The link href is `https://go.dev/s/website-issue`, which 302 to `https://github.com/golang/go/issues/new/?title=x%2Fwebsite:&body=%3C%21--%0APlease+answer+these+questions+before+submitting+your+issue.+Thanks%21%0A--%3E%0A+%0A%23%23%23+What+is+the+URL+of+the+page+with+the+issue%3F%0A+%0A+%0A+%0A%23%23%23+What+is+your+user+agent%3F%0A+%0A%3C%21--+%0AYou+can+find+your+user+agent+here%3A%0Ahttps%3A%2F%2Fwww.whatismybrowser.com%2Fdetect%2Fwhat-is-my-user-agent%0A--%3E%0A+%0A+%0A+%0A%23%23%23+Screenshot%0A+%0A%3C%21--%0APlease+paste+a+screenshot+of+the+page.%0A--%3E%0A+%0A+%0A+%0A%23%23%23+What+did+you+do%3F%0A+%0A%3C%21--%0AIf+possible%2C+provide+a+recipe+for+reproducing+the+error.%0A--%3E%0A+%0A+%0A+%0A%23%23%23+What+did+you+expect+to+see%3F%0A+%0A+%0A+%0A%23%23%23+What+did+you+see+instead%3F%0A%0A%0A%0A`

**Comment by ALTree** [comment]
I think it's correct. The playground is under x/website now.

**Comment by Deleplace** [comment]
My bad, then!

I was influenced by the existing Playground-related issues, which had the
distinctive title prefix.

**Comment by ALTree** [comment]
Yeah, it was moved recently in the website repo. Closing here.
