### ISSUE TITLE
testing: parallel fuzzing hangs with -parallel=1

### ISSUE THREAD

**Issue by AlekSi** [golang/go#50217]
```
go version devel go1.18-7f2314530e Thu Dec 16 00:34:10 2021 +0000 darwin/arm64
```

The following test hangs when run with `go test -parallel=1`:

```
func FuzzParallel(f *testing.F) {
	f.Add(42)

	f.Fuzz(func(t *testing.T, i int) {
		t.Parallel()
	})
}
```

It works with `-parallel=2` and other values. I think it should work in any case.

Small self-contained example is there: https://github.com/AlekSi/go-bug/tree/master/50217

**Comment by AlekSi** [comment]
@gopherbot fuzz

**Comment by AlekSi** [comment]
Bisected down to b2b6be71f27ef74510394dad822cfe8d5e56f4f4

**Comment by cherrymui** [comment]
cc @golang/fuzzing

**Comment by rolandshoemaker** [comment]
This seems like one of the things that should just be disabled, both within the `f.Fuzz` function, and disallowing the flag, since I'm not really sure _what it would do_. @katiehockman what do you think?

**Comment by thepudds** [comment]
FWIW, in terms of what it could do, the design doc includes:

```
// Run the fuzz test
f.Fuzz(func(t *testing.T, a string, num *big.Int) {
	t.Parallel() // seed corpus tests can run in parallel
```

Certainly seems reasonable to disallow it though, especially for a first version.

**Comment by AlekSi** [comment]
Running seed corpus entries in parallel actually works (as far as I can tell) and is very useful for me. If there is not enough time to fix it for `-parallel=1` edge case, maybe just explicitly fail in that case instead of hanging or removing the whole feature.

**Comment by katiehockman** [comment]
`t.Parallel()` in a fuzz target should be a no-op during fuzzing, but is similar to a `t.Parallel()` inside a `t.Run()` in that it runs the seed corpus in parallel when `-fuzz` isn't set.
This is just a bug I think. If we can't fix it, then just removing that functionality for 1.18 also seems fine. Will take a look.
