### ISSUE TITLE
runtime.Callers: got incorrect line number in some case

### ISSUE THREAD

**Issue by jxskiss** [golang/go#50213]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-7f23145 Thu Dec 16 00:34:10 2021 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Not in 1.17.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
mac, amd64
</pre></details>

### What did you do?

```go
package main

import (
	"fmt"
	"runtime"
	"runtime/debug"
	"strings"
)

func main() {
	withRecover()
}

var abc string

func willPanic() {
	abc = "1234"
	panic("oops...") // line 18
}

func withRecover() {
	defer func() {
		e := recover()
		if e != nil {
			fmt.Println(identifyPanic())
			fmt.Println(string(debug.Stack()))
		}
	}()
	willPanic()
}

func identifyPanic() string {
	var name, file string
	var line int
	var pc [16]uintptr
	n := runtime.Callers(3, pc[:])
	for _, pc := range pc[:n] {
		fn := runtime.FuncForPC(pc)
		if fn == nil {
			continue
		}
		file, line = fn.FileLine(pc)
		name = fn.Name()
		if !strings.HasPrefix(name, "runtime.") {
			break
		}
	}
	return fmt.Sprintf("%v:%v:%v", file, name, line)
}
```

### What did you expect to see?

The expected output is "/Users/wsh/go/src/github.com/jxskiss/gopkg/tt.go:main.willPanic:18".

But I got "... tt.go:main.willPanic:17".

### What did you see instead?

```text
/Users/wsh/go/src/github.com/jxskiss/gopkg/tt.go:main.willPanic:17
goroutine 1 [running]:
runtime/debug.Stack()
        /Users/wsh/sdk/gotip/src/runtime/debug/stack.go:24 +0x65
main.withRecover.func1()
        /Users/wsh/go/src/github.com/jxskiss/gopkg/tt.go:26 +0x74
panic({0x1092e60, 0x10c1928})
        /Users/wsh/sdk/gotip/src/runtime/panic.go:838 +0x207
main.willPanic(...)
        /Users/wsh/go/src/github.com/jxskiss/gopkg/tt.go:18
main.withRecover()
        /Users/wsh/go/src/github.com/jxskiss/gopkg/tt.go:29 +0x70
main.main()
        /Users/wsh/go/src/github.com/jxskiss/gopkg/tt.go:11 +0x17
```

---

If I change the line `abc = "1234"` in `willRecover` to assigning to a local variable, the output is correct.

**Comment by AlekSi** [comment]
That's not a problem with `runtime.Callers`, but with `runtime.FuncForPC`. From docs:

> To translate these PCs into symbolic information such as function names and line numbers, use CallersFrames. CallersFrames accounts for inlined functions and adjusts the return program counters into call program counters. Iterating over the returned slice of PCs directly is discouraged, as is using FuncForPC on any of the returned PCs, since these cannot account for inlining or return program counter adjustment.

**Comment by AlekSi** [comment]
So please close it :)
