### ISSUE TITLE
x/website: Effective Go: Visible anchors for linkable sections

### ISSUE THREAD

**Issue by Deleplace** [golang/go#50211]
### What is the URL of the page with the issue?
 
 https://go.dev/doc/effective_go
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/13508141/146362701-2d874829-5232-4ee3-af4c-e1248c31c0a8.png)
 
### What did you do?
 
I wanted to create a direct hyperlink to [the section Type switch](https://go.dev/doc/effective_go#type_switch) and add it to a webpage in another Go-related website.
  
### What did you expect to see?
 
 Feature request: all the section headings (h2, h3) would come with a trailing ¶ as a visual indicator for "Click here to get the direct URL to this section". Optionally, the ¶ char only shows up when the mouse approaches the heading. (All of this is the existing behaviour in all package pages at [pkg.go.dev](https://pkg.go.dev/github.com/shuLhan/share/lib/io#IsDirEmpty))

![image](https://user-images.githubusercontent.com/13508141/146362905-4e3e0142-243f-4dda-8026-7d81e2e8b71a.png)

 
### What did you see instead?

- Section headings are not hyperlinks.
- All of the h2, h3 already have an `id` attribute (this is great).
- All of the h2, h3 already have a corresponding link inside the Table of Contents.
- I had to search in the Table of Contents in order to click the "Type switch" and retrieve the relevant URL with the proper anchor.

**Comment by Deleplace** [comment]
This is like #50210, but milder, as all the relevant section URLs are already there, in the ToC.

**Comment by cherrymui** [comment]
cc @dmitshur

**Comment by mvdan** [comment]
I believe https://github.com/golang/go/issues/68596 resolved this, even though it was filed much later. See https://github.com/golang/go/issues/70827 for a follow-up of mine where the anchors only show up if you hover over exactly where they would appear, which makes them hard to discover currently.
