### ISSUE TITLE
x/playground: feature request: instant Share URL on each "Run"

### ISSUE THREAD

**Issue by Deleplace** [golang/go#50224]
### What is the URL of the page with the issue?
 
https://go.dev/play/ 
  
### Screenshot
 
![image](https://user-images.githubusercontent.com/13508141/146401649-d5878162-d8c7-46e5-b1cf-0d22e89ec227.png)
 
 
### What did you do?
 
- Write some code
- Clicked the "Run" button 
 
### What did you expect to see?
 
The URL of the page could be immediately updated with a permalink.  It is then slightly more immediate to share this already generated URL, without the need for the "Share" button. Of course, any change in the code would wipe the permalink from the URL bar (as it already does now).

I acknowledge that this feature incurs a small gain in UX (2s saved) and a potentially big cost server-side (durably store all the snippets ever run, durably keep a distinct URL for each of them). We may do some analysis to decide if the extra server storage burden is acceptable or not.
 
### What did you see instead?

The URL of the page remains "https://go.dev/play/", and then I have to click "Share" in order to actually generate a snippet URL.

**Comment by cherrymui** [comment]
I'm not sure if this needs to be a proposal ( https://golang.org/s/proposal ). It probably doesn't hurt if you make it one. Thanks. @Deleplace 

cc @toothrot

**Comment by seankhliao** [comment]
seems nobody else needs this for what can be a large increase in cost.
