### ISSUE TITLE
spec: should `len(a)` (and `cap(a)`) be constant for `a` of type parameter type constrained by same-size arrays?

### ISSUE THREAD

**Issue by griesemer** [golang/go#50226]
Reminder issue to consider this case. See also #42029 for background.

This can wait for 1.19 as going from a non-constant to a constant result for `len` and `cap` is a backward-compatible change (I think, since the type doesn't change, it's always `int`).

**Comment by griesemer** [comment]
Note that the [spec](https://tip.golang.org/ref/spec#Length_and_capacity) currently says:

> The expressions len(s) and cap(s) are constants if the type of s is an array or pointer to an array and the expression s does not contain channel receives or (non-constant) function calls; in this case s is not evaluated.

If it said

> The expressions len(s) and cap(s) are constants if s is an array or pointer to an array and the expression s does not contain channel receives or (non-constant) function calls; in this case s is not evaluated.

and we look at `array` (and `pointer to array`) as structural types, then we may need to make the result constant in some cases. The effect on real-life programs is negligible, this is mostly a spec precision issue.

In the implementation it would mean changing a call to `under` to `structuralType`.

cc: @ianlancetaylor

**Comment by go101** [comment]
Moving this to Go1.19 means it will be always as such. It is a problem same as `aConstString[i:j]`.

**Comment by go101** [comment]
BTW, it looks it is disallowed to pass addresses of array type parameter values to `len`:

```Go
package main


func f[T [2]int]() {
	var x T
	const _ = len(&x) // invalid argument: &x (value of type *T) for len
	var _ = len(&x)   // invalid argument: &x (value of type *T) for len
}

func main() {
	type T [2]int
	var x T
	const _ = len(&x) // okay
}
```

**Comment by griesemer** [comment]
Too late for 1.21 if anything needs to be done here.

**Comment by griesemer** [comment]
Moving to 1.23. We're not going to change this for 1.22.

**Comment by griesemer** [comment]
This is a (if minor) language change and thus needs to go through the proposal process. Closing this issue in favor of #65592.

**Comment by griesemer** [comment]
See also https://go-review.git.corp.google.com/c/go/+/562349/.
