### ISSUE TITLE
x/tools/go/analysis: confusing error message returned when ExportPackageFact is called with invalid type

### ISSUE THREAD

**Issue by adammw** [golang/go#50235]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.3 darwin/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/amalcontenti-wilson/Library/Caches/go-build"
GOENV="/Users/amalcontenti-wilson/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/amalcontenti-wilson/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/amalcontenti-wilson/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/amalcontenti-wilson/Code/zendesk/nodegroup-operator/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yq/18f4vk0j2m95ycmk2wk8j4qh0000gq/T/go-build1295760992=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Building a static analyser using the x/tools/go/analysis package, and passing in the actual Fact struct, rather than a pointer to it.

e.g.
```
	pass.ExportPackageFact(MyFact{data})
	// should be: pass.ExportPackageFact(&MyFact{data})
```

### What did you expect to see?

An error saying that it needed a pointer.

### What did you see instead?

```
invalid Fact type: got *reflect.rtype, want pointer
```

The type passed in is not a reflect.rtype, this is instead an internal type the error checking in checker.go uses to check the type. The error message should instead name the actual type passed in.

**Comment by timothy-king** [comment]
Improving the error message would definitely be helpful here. I would be supportive of improving it if it can be done simply enough. Not many people write Analyzers, and this should be caught in testing. So the situation is not too bad, but clarity would be an improvement. This would be a good place for a community contribution.
