### ISSUE TITLE
spec: decide whether we want to allow struct initialization of  type param type 

### ISSUE THREAD

**Issue by danscales** [golang/go#50233]
I have been wondering ever since if we really should support the example in this issue, which we current do, or disallow it:

https://github.com/golang/go/issues/48538

Consider this program, a modification of the example in the issue:

```
package p

type C interface {
        ~struct{ b1, b2 string }
}

func f[T C]() T {
        var x T = T{
                b1: "a",
                b2: "b",
        }

        x.b1 = "y" // <== this line gives an error, everything else is fine if it is removed.

       return x
}
```

Everything compiles fine if we remove the one marked line.  Basically, we are allowing a variable of typeparam T to be initialized with structural fields, because the type param is constrained to a single structural type, which is a struct type with b1 and b2 fields.  But we don't allow the marked line, which seems very similar.  Why are we allowed to initialize the b1 and b2 fields of x, but not directly assign to x.b1?

I think we should decide on this before 1.18 release, so we don't get stuck with backward compatibility of a possibly inconsistent design with our current state.

=====

Robert's list of possible alternatives:

1) do nothing
2) disallow struct literals where the type is a type parameter (even if it has a structural type)
3) allow x.b1 if there is a structural type
4) allow x.b1 if all types in the type parameter have a b1 field

2 is the conservative approach. Both 3 and 4 seem consistent with what we have. 1 seems a bit inconsistent.

**Comment by griesemer** [comment]
cc: @ianlancetaylor @findleyr

**Comment by ianlancetaylor** [comment]
For 1.18 I believe we should do either (2) or (3), whichever is easier.

In the long run I believe that we should do (4), except that we should permit `x.b1` if a) all the types in the type set have a field named `b1`, and b) all the `b1` fields have an identical type.

**Comment by akutz** [comment]
FWIW, I also verified that it is currently possible to _read_ the variable from a structural constraint ([example](https://gotipplay.golang.org/p/U4RFJ7hp21v)):

```go
package main

import (
	"fmt"
)

type structuralConstraint interface {
	~struct{ b1, b2 string }
}

type myStruct struct {
	b1 string
	b2 string
}

func getT[T structuralConstraint]() T {
	return T{
		b1: "a",
		b2: "b",
	}
}

func main() {
	t := getT[myStruct]()
	fmt.Println(t.b1, t.b2)
}
```

The above example prints:

```bash
a b
```

**Comment by ianlancetaylor** [comment]
@akutz That example shows using a composite literal with a structural constraint of struct type, which does indeed work today.  But it doesn't show reading a field.  The only code I see that reads the field is in `main`, where it is working with a fully instantiated type, not a type parameter with a structural constraint.

**Comment by danscales** [comment]
Yes, I was just about to comment as well.  I should have maybe mentioned in the original issue report above, but reading `x.b1` in generic function `f` above also does not work.

**Comment by griesemer** [comment]
This is working on the type-checker and compiler side.

Decision: To make it consistent we are going to support struct field references for type parameters with struct structural types as well (issue #50417).
