### ISSUE TITLE
x/mod/modfile: Parse only sets Module.Mod.Path, not Version

### ISSUE THREAD

**Issue by LittleFox94** [golang/go#50242]
When using `golang.org/x/mod/modfile.Parse()` to parse a `go.mod` file into `file File`, I expect `file.Module.Mod` to have both `Path` and `Version` set. Instead, only Path is set - including the version as last element.

The `go.mod` contained this line: `module github.com/onsi/ginkgo/v2` (the exact package being not important), running in `dlv` I confirmed the behavior:
```
(dlv) p file.Module.Mod
golang.org/x/mod/module.Version {
	Path: "github.com/onsi/ginkgo/v2",
	Version: "",}
```

I used `file, err := modfile.Parse(fmt.Sprintf("go.mod@%v", version), fileContents, nil)` to parse the file, no error was returned. The filename given as argument should be irrelevant to this problem.

Please either change the code to have `Path` and `Version` set or document this is not the case and what users should do instead.

<details>
<summary>Version details</summary>

```
go version go1.17.5 linux/amd64
golang.org/x/mod version v0.5.1
```

</details>

**Comment by seankhliao** [comment]
the `Version.Version` field documents the expected contents, in this case: 
> First, the top-level target of a build has no specific version and uses Version = ""
