### ISSUE TITLE
time: Multiple packages in the directory: time, main

### ISSUE THREAD

**Issue by 520MianXiangDuiXiang520** [golang/go#50244]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18beta1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

* yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\lenovo\AppData\Local\go-build
set GOENV=C:\Users\lenovo\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=E:\goProject\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\goProject
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,https://goproxy.io,direct
set GOROOT=E:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=E:\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18beta1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\lenovo\AppData\Local\Temp\go-build1614885817=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I plan to use the time package, but I got this error on goland：

```txt
Multiple packages in the directory: time, main
```

This seems to be caused by `genzabbrs.go`. Although it will not be compiled, it seems not good to have multiple packages in the same directory, so is it possible to move this type of file to another directory?

### What did you expect to see?

* A cleaner time directory

### What did you see instead?

* There are multiple different packages in the same directory

**Comment by seankhliao** [comment]
The file is guarded by the build tag `//go:build ignore`.
How are you using the package/building your program?

**Comment by ianlancetaylor** [comment]
This is normal and intended.  There are other examples of this in the standard library, such as crypto/md5 and encoding/gob.

**Comment by 520MianXiangDuiXiang520** [comment]
Yes, it won’t have any problems when compiling, I just think it’s a better idea to keep the directory clean. That’s okay, thanks for your reply

**Comment by onlyyours** [comment]
> Yes, it won’t have any problems when compiling, I just think it’s a better idea to keep the directory clean. That’s okay, thanks for your reply

I have the same problem, can you tell me how to fix?
