### ISSUE TITLE
syscall: NewCallback triggers data race on Windows when used from different goroutine

### ISSUE THREAD

**Issue by JohanKnutzen** [golang/go#50249]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\knutz\AppData\Local\go-build
set GOENV=C:\Users\knutz\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\knutz\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\knutz\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.4
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\knutz\AppData\Local\Temp\go-build2788134738=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

```
package main

import (
	"syscall"
)

func foo() {
	syscall.NewCallback(func(callerContext uintptr, iface uintptr, notificationType uint32) uintptr {
		return 0
	})
}

func main() {
	go foo()
	foo()
}

```
Built and run using:
```go build -race && ./main.exe```

### What did you expect to see?
Nothing
### What did you see instead?
```==================
WARNING: DATA RACE
Read at 0x00c000028000 by goroutine 6:
  runtime.mapaccess2()
      C:/Program Files/Go/src/runtime/map.go:452 +0x0
  syscall.compileCallback()
      C:/Program Files/Go/src/runtime/syscall_windows.go:308 +0x244

Previous write at 0x00c000028000 by main goroutine:
  runtime.mapassign()
      C:/Program Files/Go/src/runtime/map.go:571 +0x0
  syscall.compileCallback()
      C:/Program Files/Go/src/runtime/syscall_windows.go:324 +0x392
  main.main()
      C:/code/fd/hack/compile_syscall_race/main.go:15 +0x30

Goroutine 6 (running) created at:
  main.main()
      C:/code/fd/hack/compile_syscall_race/main.go:14 +0x2b
==================
Found 1 data race(s)```

**Comment by randall77** [comment]
Those map accesses are guarded by a lock. Not sure why the race detector would report on them.

**Comment by JohanKnutzen** [comment]
@randall77 From reviewing the code, that seems to be the case. Perhaps this is a bug in the race detector? More specifically when run on Windows

**Comment by cherrymui** [comment]
The race detector probably doesn't know about the lock. It seems runtime lock does not inform the race detector about the edge (unlike locks in the sync package). (Normally it is fine as the runtime  is  not race-instrumented. But that  code uses a map and mapassign/mapaccess have explicit race calls).

**Comment by prattmic** [comment]
@gopherbot please backport to 1.17 and 1.18. This triggers a false positive in the race detector for programs calling `syscall.NewCallback` from multiple goroutines. There is a workaround: use a single global lock around all calls to `syscall.NewCallback` in the program. However, that is quite invasive and difficult for complex code.
