### ISSUE TITLE
x/tools/gopls: add go:embed support

### ISSUE THREAD

**Issue by hamidfzm** [golang/go#50262]
**Is your feature request related to a problem? Please describe.**
Go embed feature introduced in version 1.16. Currently, go-vscode treats text like  `//go:embed app`  as a simple comment.

**Describe the solution you'd like**
Provide text highlighting or navigation by CTRL+Clicking on these comments

**Describe alternatives you've considered**
Goland provides this feature in its recent versions:
![Screenshot from 2021-12-10 18-21-42](https://user-images.githubusercontent.com/5591800/145593824-0f36941c-4ba4-40e0-a37b-7aa3f2001bcb.png)

**Additional context**
VS code view
![Screenshot from 2021-12-10 18-25-51](https://user-images.githubusercontent.com/5591800/145593934-1ca3c7fb-1701-4ba6-b7f5-97ea6f740c9f.png)

It would be really nice if we have this feature in my favorite code editor.

**Comment by ansaba** [comment]
List of improvements 

- [ ] checks for the "embed" import
- [ ] Report it as semantic for highlighting
- [ ] The directive must immediately precede a line containing the declaration of a single variable. Only blank lines and ‘//’ line comments are permitted between the directive and the declaration.

**Comment by findleyr** [comment]
We should also include a quick-fix to add the missing "embed" import.

**Comment by findleyr** [comment]
@vikblom expressed interest in picking this up.

I think the semantic highlighting support is a bit tricky to implement, so let's separate that bit out for now.

Viktor, if you are interested you could do the following:

- [ ] Update the [embeddirective](https://pkg.go.dev/golang.org/x/tools/gopls/internal/lsp/analysis/embeddirective) 
analyzer to check that the embed directive immediately precedes a line containing the declaration of a single variable. Only blank lines and ‘//’ line comments are permitted between the directive and the declaration.
- [ ] Update the analyzer to include a suggested fix to add the missing "embed" import.

I recommend doing this in two separate CLs. Adding the suggested fix is a little subtle (we should re-use the existing `gopls.add_import` custom command). So let's discuss the second item after the first is done.

I'll tentatively assign you. Let me know if you don't think you'll be able to work on this.

**Comment by findleyr** [comment]
Well, @vikblom it turns out I cannot assign you, so I assigned myself as your proxy :)

**Comment by vikblom** [comment]
Hi @findleyr, with the CL above merged I've started looking at suggesting a fix from the analyzer.

`analysis.Diagnostic` has a field for `SuggestedFixes` which seems straight forward enough. You mentioned `gopls.add_import`, best I can tell that command is backed by `source.AddImport`. Am I aiming for the right things?

Are there any requirement on placement for the import. I'm used to placing blank imports like `_ "embed"` last.

**Comment by vikblom** [comment]
Thanks @findleyr that approach works great :+1: 

I've added a `TestLSP` testcase with a golden file verifying that the import is added. Do you have any suggestion or tips on how to test the negative case? (That the other kind of reports (incorrect decl) does _not_ have a code action.)

**Comment by vikblom** [comment]
I noticed that I haven't kept all the docs up to speed, for example analyzers.md. That should probably be corrected as part of this issue.

**Comment by findleyr** [comment]
@vikblom the analyzer doc is auto-generated, and there is a test to enforce this: `cd gopls && go generate .`

**Comment by vikblom** [comment]
@findleyr I see! Then it's the analyzers `Doc` field that (maybe) needs an update. I was thinking it should mention the new variable check and suggested fixes, do you agree?

**Comment by vikblom** [comment]
Hi @findleyr, is there a path forward with semantic highlighting here, given that the vscode ticket was closed by triage? 

I tried out a naive `textDocument/documentLink` solution passing `file://` URIs. Emacs could handle both files and directories. VSCode only accepted files. Does it makes sense to use that as a opt-in or base case (only files) feature?

You mentioned code action+associated command and jump-to-definition+hover above, which seems doable. However if VSCode requires specific (or new) mechanisms to handle directories, this feature might spread to codebases (`vscode` or `vscode-go`) I'm not familiar with

**Comment by findleyr** [comment]
Hi @vikblom, very sorry for the slow response on this.

Let's not worry about semantic tokens for now, I think that's a low priority. We can treat highlighting `//go:` directives as a separate project.

We discussed this in our triage meeting, and I think jump-to-definition+hover is the best way to implement this feature, as it will be supported by the greatest number of LSP clients. For directories, perhaps we should just pick an arbitrary file in the directory?

**Comment by vikblom** [comment]
An arbitrary file could be unexpected as a user. But I don't see any alternatives if this is a limitation of LSP clients. I agree it is a good place to start. 

I'll try to put something together and post a CL.

**Comment by findleyr** [comment]
Great, thanks for sticking to this!

**Comment by vikblom** [comment]
Hi @findleyr, what do you think is the next step? Would tackling semantic highlighting make sense or do we let the issue rest for a bit?

**Comment by findleyr** [comment]
@vikblom if we're going to highlight go:embed, I think we should highlight all go: directives. Is that something you'd be interested in?

If so, I think we should perhaps make that a separate issue, and close this one.

**Comment by vikblom** [comment]
Sure, I'd be glad to take a look directive highlights!

Thanks again for all the help in this issue.

**Comment by findleyr** [comment]
Great! Opened https://go.dev/issue/63538.

Will close this then.
