### ISSUE TITLE
cmd/objdump: -S doesn't work with dynamically linked executable

### ISSUE THREAD

**Issue by MoZhonghua** [golang/go#50269]
`go tool objudmp -S` can't print source code when the executable is built with `go build -buildmode=pie`. pclntab data is not in elf section `.gopclntab`, but in `.data.rel.ro.gopclntab`. `.gosymtab` has similar problem.

**Comment by cherrymui** [comment]
Dup of #17883 . Thanks.

CL https://go-review.googlesource.com/c/go/+/227483 was my attempt but it doesn't work everywhere and still have problems.
