### ISSUE TITLE
net: IPNet.String panics with nil receiver

### ISSUE THREAD

**Issue by Beginner18** [golang/go#50271]
### What version of Go are you using (`go version`)?

1.15.5

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

panic, if IPNet is nil

```
func (n *IPNet) String() string {
	nn, m := networkNumberAndMask(n)
	if nn == nil || m == nil {
		return "<nil>"
	}
	l := simpleMaskLength(m)
	if l == -1 {
		return nn.String() + "/" + m.String()
	}
	return nn.String() + "/" + uitoa(uint(l))
}
```

### What did you expect to see?
IPNet.String() should not panic, even IPNet is nil

### What did you see instead?
```
    panic(0x194abc0, 0x2156090)
        	/usr/local/go/src/runtime/panic.go:969 +0x1b9
        net.networkNumberAndMask(0x0, 0x0, 0x10, 0x23bb108, 0xc000123d30, 0xc00003ed00, 0xc000077dd0)
        	/usr/local/go/src/net/ip.go:476 +0x26
        net.(*IPNet).String(0x0, 0xc00011f470, 0x18eed80)
        	/usr/local/go/src/net/ip.go:526 +0x45
```

**Comment by ianlancetaylor** [comment]
While in general the standard library is happy to panic when invoked on an invalid value, I agree that perhaps the `String` method should not do so.
