### ISSUE TITLE
could not import github.com/go-sql-driver/mysql (cannot find package "github.com/go-sql-driver/mysql" in any of

### ISSUE THREAD

**Issue by Millem1337** [golang/go#50274]
Error:
could not import github.com/go-sql-driver/mysql (cannot find package "github.com/go-sql-driver/mysql" in any of 
	C:\Program Files\Go\src\github.com\go-sql-driver\mysql (from $GOROOT)
	C:\Program Files\Go\src\github.com\go-sql-driver\mysql (from $GOPATH))

Code:
`package main

import (
	"database/sql"
	"fmt"
	"html/template"
	"net/http"

	_ "github.com/go-sql-driver/mysql"
)

func main(){
...
}
`

How to solve this? I saw the given problem, but the solution didn't help. I reinstalled Go, I put a different $GOPATH but nothing helps

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
