### ISSUE TITLE
cmd/go: do not name temp directories using import paths

### ISSUE THREAD

**Issue by rsc** [golang/go#5027]
<pre>Naming the temp work directories using import paths means that if you're building
x/y/z/w you end up working in /tmp/garbage/x/y/z/w and then you need to put compiled
packages somewhere during a test so you end up with
/tmp/garbage/x/y/z/w/_test/x/y/z/w.a. If the path is long, the doubling here can exceed
OS limits, especially on Windows where the limit is 250 bytes. 

We can shuffle things a little in the go command so that the import path need never
appear twice in the temporary path. That will buy us a little space.

A better fix is to use the \\?\ syntax on Windows to get longer path names, but that fix
is fraught with peril and too dangerous for Go 1.1. That's <a href="https://golang.org/issue/3358">issue #3358</a>.</pre>

**Comment by rsc** [comment]
Fixed by ee4fbbc621.

**Comment by robpike** [comment]
Wondering what the lowest issue number is that this burst will close.
