### ISSUE TITLE
x/text/cmd/gotext: "/" not extracted

### ISSUE THREAD

**Issue by remko** [golang/go#50288]
### What version of Go are you using (`go version`)?

go version go1.16.3 darwin/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
</pre></details>

### What did you do?

Run `go generate .` on a module with only the following file:

<pre>
package translations

//go:generate gotext -srclang=en update -out=catalog.go -lang=en,nl .

import (
	"golang.org/x/text/message"
)

func dummyMessages(p *message.Printer) {
	p.Printf("/b")
	p.Printf("/")
	p.Printf("/a")
}
</pre>

### What did you expect to see?

The string `/` to appear in  `locales/en/out.gotext.json`

### What did you see instead?

Only the strings `/b` and `/a`.

**Comment by seankhliao** [comment]
This looks intentional, see  https://go.googlesource.com/text/+/6c97a165dd661335ff7bce6104a008558123c353/message/pipeline/extract.go#811
and its call site https://go.googlesource.com/text/+/6c97a165dd661335ff7bce6104a008558123c353/message/pipeline/extract.go#290
