### ISSUE TITLE
go/types, types2: append within a generic function does not compile

### ISSUE THREAD

**Issue by stellirin** [golang/go#50281]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18beta1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

latest **beta** release

### What did you do?

A generic function with a union constraint of `[]byte | string` cannot append to a `[]byte`.

```go
func AppendBytes(buf []byte, s []byte) []byte {
	return append(buf, s[1:6]...)
}

func AppendString(buf []byte, s string) []byte {
	return append(buf, s[1:6]...)
}

type byteseq interface {
	string | []byte
}

// This should allow to eliminate the two functions above.
func AppendByteString[source byteseq](buf []byte, s source) []byte {
	return append(buf, s[1:6]...)
}
```

[https://gotipplay.golang.org/p/WGG7g3HTfZ-](https://gotipplay.golang.org/p/WGG7g3HTfZ-)

I expect this is a duplicate of a known issue but so far I was not able to find anytinhg. Similar functions are explicitly mentioned in the proposal: [https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#composite-types-in-constraints](https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#composite-types-in-constraints)

### What did you expect to see?

The program compiles.

### What did you see instead?

```
./prog.go:18:22: cannot use s[1:6] (value of type source constrained by byteseq) as type []byte in argument to append:
	cannot assign string (in source) to []byte
```

**Comment by ianlancetaylor** [comment]
CC @griesemer @findleyr

**Comment by zhangfannie** [comment]
I modified the above program, see https://gotipplay.golang.org/p/j31fyLkpZcL, it works now. 
`func AppendByteString[source byteseq](buf []byte, s source) []byte{
	return append(buf, []byte(s[1:6])...)
}`
Because I am not familiar with type parameters, I do not know if this modification changes its function. Thank you.

**Comment by zhangfannie** [comment]
Please ingore the above reply,  the above mofication changes its function. 🙂

**Comment by aarzilli** [comment]
Isn't this already disallowed by the current spec because byteseq doesn't have a specific type?

**Comment by griesemer** [comment]
The simple case is
```Go
package p

func _[S string|[]byte](s S) {
        var buf []byte
	_ = append(buf, s...)
}
```
which is currently disallowed because `S` has no structural type. But the spec has not been updated with respect to `append`, and we should have a special case here as we have for `copy`.
