### ISSUE TITLE
net: add method to UDPConn that exposes fcntl(FIONREAD)-like functionality

### ISSUE THREAD

**Issue by OlegPuchinin123** [golang/go#50306]
Hello !
How about add fcntl(fd, FIONREAD ...) call ot net.UDP connection ? This call return size of UDP for read.

Oleg.

**Comment by ianlancetaylor** [comment]
You can do it yourself using `UDPConn.SyscallConn` and `unix.IoctlGetInt` (from the golang.org/x/sys/unix package).  (Note that `FIONREAD` is used with `ioctl`, not `fcntl`.)
