### ISSUE TITLE
cmd/go: go install with -trimpath and muslc (alpine linux) gcc is needed

### ISSUE THREAD

**Issue by jerome-laforge** [golang/go#50311]
with `-trimpath` option with go install with muslc on default alpine linux, the go install doesn't work.
`apk add --no-cache build-base` can be executed as workaround before (but, we have to do each time on CI).

### What version of Go are you using (`go version`)?
go 1.17.5

### What did you do?
on our CI, with alpine linux:
- go install ./...

### What did you see instead?
```
# runtime/cgo
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH
```

**Comment by dmitshur** [comment]
cgo needs a C compiler is needed to build C code, this is working as expected.

If you prefer to disable cgo, you can configure that with the `CGO_ENABLED` environment option.

If your C compiler command is not "gcc", you can configure cgo to use a different command via the `CC` environment option.

See https://pkg.go.dev/cmd/go#hdr-Environment_variables for a list of environment variables supported by the go command.

For asking questions, please see https://golang.org/wiki/Questions.

**Comment by jerome-laforge** [comment]
Sorry, I didn't give enough information.
There is no CGO in my Go program. It is pure Go.

Futhermore, if I disable `-trimpath` into cmd line, then the compilation works without gcc.

I think, this issue is related with #37158, isn't it?

More info here from Ian Lance Taylor: https://groups.google.com/g/golang-nuts/c/dsqLZi2mEog/m/3mcMSda-BAAJ

**Comment by dmitshur** [comment]
I see, thanks for more context.

It seems like we can close this issue as a duplicate of #37158, do you agree?

Note that proposal #47257 has been accepted by now, so that will affect this situation when it is resolved.

**Comment by jerome-laforge** [comment]
Thanks for your support and the information.
