### ISSUE TITLE
cmd/compile: Type parameter is not validated in receiver

### ISSUE THREAD

**Issue by ilya-zz** [golang/go#50316]
### What version of Go are you using (`go version`)?

<pre>
$ go version
devel go1.18-90fb5a4f97 Wed Dec 22 00:11:21 2021 +0000
</pre>

### Does this issue reproduce with the latest release?
No, generics required

### What operating system and processor architecture are you using (`go env`)?
any
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Please refer to https://gotipplay.golang.org/p/pyAU-Se4Iqj

```
package main

import (
	"fmt"
)

type Foo[T any] struct {
	t T
}

func (f Foo[string]) Do() {
	fmt.Println(f.t)
}

func main() {
	x := Foo[int]{}
	x.Do()
}

```

### What did you expect to see?

A compiler error at line `func (f Foo[string]) Do()` explaining that `string` is an invalid type parameter value for `Foo` 

### What did you see instead?
The program successfully compiled and can be executed. Output:
```
0
Program exited.
```

**Comment by randall77** [comment]
`string` is not a keyword, just a predclared identifier. You can override it, e.g.

```
var string int = 3
```
Declares a variable of type `int`, value `3` and name `string`.

Similarly in your case, you're declaring the method `Do` on the generic type `Foo`, using the name `string` as the type parameter for the body of `Do`.

Dup of #48813

**Comment by ilya-zz** [comment]
@randall77  Thanks for explanation. 

But if we slightly modify the code:
```
package main

import (
	"fmt"
)

type Foo[T any] struct {
	t T
}

func Do(f Foo[string])  {
	fmt.Println(f.t)
}

func main() {
	x := Foo[int]{}
	Do(x)
}
```
we get:
`./prog.go:17:5: cannot use x (variable of type Foo[int]) as type Foo[string] in argument to Do`

Looks a little inconsistent.

**Comment by randall77** [comment]
I agree it does look a bit strange. But in the latter example you're not defining a new name `string`, you're using the actual predeclared `string` type and instantiating `Foo` with it. Type expressions in the receiver position and in argument position are very different w.r.t. generics.
