### ISSUE TITLE
cmd/compile:  "methods cannot have type parameters" compiler error reported twice

### ISSUE THREAD

**Issue by ilya-zz** [golang/go#50317]
### What version of Go are you using (`go version`)?

<pre>
$ go version
devel go1.18-90fb5a4f97 Wed Dec 22 00:11:21 2021 +0000
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

https://gotipplay.golang.org/p/-LsXizeqqJK
```
package main

import (
	"fmt"
)

type Foo[T any] struct {
	t T
}

func (f Foo[T]) Do[T any] () {
	fmt.Println(f.t)
}
```

### What did you expect to see?

The `methods cannot have type parameters` compiler error

### What did you see instead?
```
./prog.go:11:19: methods cannot have type parameters
./prog.go:11:20: invalid AST: method must have no type parameters
./prog.go:11:20: T redeclared in this block
	prog.go:11:13: other declaration of T
```

Not a big deal, but it probably would be a better DX to report `methods cannot have type parameters` only once.

**Comment by ianlancetaylor** [comment]
CC @griesemer @findleyr 

Thanks.  Marking for 1.18 but not a release blocker.
