### ISSUE TITLE
Float64 subtraction does not work for sufficiently large Floats

### ISSUE THREAD

**Issue by kevinburchfield** [golang/go#50328]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.5 darwin/amd64

Reproducible in go.dev REPL
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kb/Library/Caches/go-build"
GOENV="/Users/kb/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/kb/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/kb/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/kb/src/Go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/53/0s5pcxwj3bq32v_y97xdvvrr0000gn/T/go-build2232257766=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

While implementing polynomial remainders for primality testing, I discovered the subtraction operator does not work for sufficiently large Float64.

Link to replication: https://go.dev/play/p/ET1J7tyoJTe

### What did you expect to see?

I expect to see the right operand to be subtracted from the left operand

### What did you see instead?

No subtraction took place.

**Comment by randall77** [comment]
This is how floating point numbers work. The epsilon near `MaxFloat64` is huge, around 10^292. Subtracting values much smaller than that will return the same value you subtracted from.

Add this to your code:
```
fmt.Printf("%f\n", math.Log10(max-math.Nextafter(max, 0)))
```
