### ISSUE TITLE
doc: meaning of the new token ~ isn't written in release note

### ISSUE THREAD

**Issue by kybin** [golang/go#50333]
Go1.18 Release Notes document about the new token `~`.

```
The new token ~ has been added to the set of operators and punctuation. 
```

But what it is and why it has been added isn't documented.

**Comment by kybin** [comment]
OK. I found a link in go/token section that explains about the tilde, still I feel a summary should be noted inside of it.

**Comment by ianlancetaylor** [comment]
The quoted sentence is in a list of changes for generics, and the start of the list points to the detailed description of the language changes.  I think the sentence is clear in context.  I do not think we should add a detailed explanation of what it means at that point in the release notes; that is what the links before the list are before.  Do you have any other suggestions for how to make this clearer?  Thanks.

**Comment by kybin** [comment]
Hmm, I just wanted add some words to it. 

But if you say so, I don't want to object.
