### ISSUE TITLE
cmd/go: document that empty environment variables are treated as unset

### ISSUE THREAD

**Issue by vikyd** [golang/go#50335]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/fault/.cache/go-build"
GOENV="/home/fault/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/data/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/data/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="my/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3814949289=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```sh
➜  ~ export GOPRIVATE=aaa   
➜  ~ go env -w GOPRIVATE=bbb
warning: go env -w GOPRIVATE=... does not override conflicting OS environment variable
➜  ~ export GOPRIVATE=  
➜  ~ go env GOPRIVATE       
bbb
```

### What did you expect to see?

Expect `go env GOPRIVATE` print nothing. Because `GOPRIVATE` is exist, and its value is empty.

`an environment variable is set with empty value` vs `an environment variable is not exist`

- Go should use values from  GOENV only if `an environment variable is not exist`.
- Go should not use values from  GOENV when `an environment variable is set with empty value`.
  - this behavior is the same as the shell

### What did you see instead?
`go env GOPRIVATE` print `bbb`.

### Suggestion
Relative code: https://github.com/golang/go/blob/go1.17.5/src/cmd/go/internal/cfg/cfg.go#L239-L242

```go
	val := os.Getenv(key)
	if val != "" {
		return val
	}
```

Should be:

```go
	val, present := os.LookupEnv(key)
	if present {
		return val
	}
```

**Comment by thanm** [comment]
@bcmills @matloob per owners.

**Comment by desir1822** [comment]
how can i unset goprivate

**Comment by bcmills** [comment]
You can use `go env -u` to permanently unset a setting written with `go env -w`.

The Go environment variables are intended to be structured such that there is always some valid non-empty string you can use to get the default behavior. For `GOPRIVATE`, you could set something like `GOPRIVATE=none`, which wouldn't match any actual modules.

**Comment by desir1822** [comment]
> You can use `go env -u` to permanently unset a setting written with `go env -w`.
> 
> The Go environment variables are intended to be structured such that there is always some valid non-empty string you can use to get the default behavior. For `GOPRIVATE`, you could set something like `GOPRIVATE=none`, which wouldn't match any actual modules.
steps belows:

1. **go env**
<pre>in local terminal,i see :
set GOPRIVATE=five.com/library.git
set GOENV=C:\Users\001\AppData\Roaming\go\env
</pre>
2.**go env -w GOPRIVATE=none**
teminal says:
<pre>
warning: go env -w GOPRIVATE=... does not override conflicting OS environment variable
</pre>
watch  in GOENV=C:\Users\001\AppData\Roaming\go\env
<pre>
GO111MODULE=auto
GOPRIVATE=none
GOPROXY=https://goproxy.cn
</pre>
go env found:
<pre>
set GOPRIVATE=five.com/library.git
</pre>
3. **go env -u GOPRIVATE**
</pre>
watch  in GOENV=C:\Users\001\AppData\Roaming\go\env
<pre>
GO111MODULE=auto
GOPROXY=https://goproxy.cn
</pre>watch env goprivate disappears,but
go env found:
<pre>
set GOPRIVATE=five.com/library.git
</pre>
it still exist.

**Comment by desir1822** [comment]
> You can use `go env -u` to permanently unset a setting written with `go env -w`.
> 
> The Go environment variables are intended to be structured such that there is always some valid non-empty string you can use to get the default behavior. For `GOPRIVATE`, you could set something like `GOPRIVATE=none`, which wouldn't match any actual modules.

Dear bcmills,I slove it.In my OS Envrionment,i see it,and then delete it.It succeses!

**Comment by bcmills** [comment]
The current behavior of treating the empty string in the process environment as equivalent to unset is intentional.

And from what I can tell the behavior you are seeing with `go env -w` and `set` is consistent with that: if you set the variable to a non-empty value in both the `GOENV` file and the process environment, the environment wins; if you set it in the `GOENV` file but not the process environment, then the value from the `GOENV` file is used.

However, looking at https://pkg.go.dev/cmd/go#hdr-Environment_variables, I see:
> If an environment variable is unset, the go command uses a sensible default setting.

That sentence should be updated to say “unset or empty” instead of “unset”.

**Comment by desir1822** [comment]
thank you somuch,it works

Bryan C. Mills ***@***.***> 于2022年4月13日周三 01:54写道：
