### ISSUE TITLE
having trouble when implementing the interface 'Quantizer' and 'Drawer' of GIF

### ISSUE THREAD

**Issue by CuteReimu** [golang/go#50334]
https://github.com/golang/go/blob/b357b05b70d2b8c4988ac2a27f2af176e7a09e1b/src/image/draw/draw.go#L36-L41
https://github.com/golang/go/blob/b357b05b70d2b8c4988ac2a27f2af176e7a09e1b/src/image/draw/draw.go#L59-L64
https://github.com/golang/go/blob/b357b05b70d2b8c4988ac2a27f2af176e7a09e1b/src/image/gif/writer.go#L453-L456

When I want to write an image quantization algorithm myself, I need to implement `draw.Quantizer` and `draw.Drawer`. As you see, `opts.Quantizer.Quantize` returns the Palette. But actually, when calling `opts.Drawer.Draw`, I need not only the Palette, but also some other data from `Quantize`.

Is it possible to make the quantization data able to be used?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
