### ISSUE TITLE
x/tools/go/packages: cannot import bufio in Go 1.18

### ISSUE THREAD

**Issue by bobg** [golang/go#50338]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18beta1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes (v1.18beta1)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/bobg/.cache/go-build"
GOENV="/home/bobg/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/bobg/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/bobg/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/bobg/sdk/go1.18beta1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/bobg/sdk/go1.18beta1/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18beta1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/bobg/go/src/github.com/bobg/modver/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2427960209=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I was beginning to update github.com/bobg/modver for Go 1.18.

I was on my `go1.18` branch at commit https://github.com/bobg/modver/commit/561c808eebbd436d00bb9306490e6e5d7235b8fa

I ran `go1.18beta1 test -run TestMajor/major/hashsplit .`

### What did you expect to see?

I expected the test to pass, as it does under Go 1.17.

### What did you see instead?

```
internal error: package "bufio" without types was imported from "hashsplit"
```

Note, this happens at https://github.com/bobg/modver/blob/561c808eebbd436d00bb9306490e6e5d7235b8fa/compare.go#L188, during the call to `packages.Load`, which fatals out rather than returning an error.

**Comment by seankhliao** [comment]
did you try updating x/tools?

**Comment by bobg** [comment]
I have now. That fixed it - thanks (he said, embarrassed).
