### ISSUE TITLE
affected/package: slice,generic

### ISSUE THREAD

**Issue by sfqin** [golang/go#50349]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.18beta1
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOOS="darwin"
GOPATH="/Users/sfqin/go"
GOPROXY="https://goproxy.cn,https://proxy.golang.org,direct"
GOROOT="/Users/sfqin/MySoft/go"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/Users/sfqin/MySoft/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dw/4stxv28s0771sk_xjwlvw1y80000gp/T/go-build098000081=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
func Removes[T comparable](o T, s []T) bool {
	for i, v := range s {
		if o == v {
			s = append(s[:i], s[i+1:]...)
			return true
		}
	}
	return false
}

func TestRemove(t *testing.T) {
	s1 := []string{"test1", "test2", "test3", "test4"}
	for i, key := range s1 {
		if key == "test2" {
			s1 = append(s1[:i], s1[i+1:]...)
		}
	}
	fmt.Printf("s1 after remove, len:%v val:%v \n", len(s1), s1)
	s2 := []string{"test1", "test2", "test3", "test4"}
	Removes("test2", s2)
	fmt.Printf("s2 after remove, len:%v val:%v\n", len(s2), s2)
}
print result
s1 after remove, len:3 val:[test1 test3 test4] 
s2 after remove, len:4 val:[test1 test3 test4 test4]

### What did you expect to see?
i want see s2 print result is len:3 val:[test1 test3 test4] 

### What did you see instead?
not use generic features

**Comment by davecheney** [comment]
Parameters are passed to functions _by value_, the s you assign too inside your function is a copy of the callers s.
