### ISSUE TITLE
x/mobile: Keep having an unknown crash I can't debug on iOS

### ISSUE THREAD

**Issue by brunomunizaf** [golang/go#50343]
Hello,
I keep facing this crash and I have no idea on how to debug. I'm not a go dev although I use go mobile bindings on my iOS app. Can anyone give me a tip on how can I catch these crashes w/ symbols or idk, anything that tells me some information that is not there?

```
Thread 19 Crashed:
0   libsystem_kernel.dylib.       0x7fff6d9db112 __pthread_kill + 10
1   libsystem_pthread.dylib       0x7fff6da32214 pthread_kill + 263
2   libsystem_c.dylib             0x7fff2009be93 raise + 26
3   <Redacted-AppName>            0x1025368eb runtime.raise_trampoline + 11
4   <Redacted-AppName>            0x1025347f0 runtime.asmcgocall + 112	
```

I *suspect* this crash happens because the go mobile bindings run on several threads and whenever the app goes to background the stopping process takes some time - and i say that bc I've seen on Android how it performs - but iOS probably just kills the background window of processing the rest of this 'stopping'. But this is such a remote hunch that I can't even discuss w/ someone about it cause i have a total of zero information to base my arguments on.

Please anyone, any tip on how to gather more information on this would be extremely valuable for me.
Thanks, 

Bruno.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by brunomunizaf** [comment]
Ops, my bad. Thank you
