### ISSUE TITLE
Go 1.18 type inference failure?

### ISSUE THREAD

**Issue by bobg** [golang/go#50354]
### What version of Go are you using (`go version`)?

https://go.dev/play/?v=gotip

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

n/a

### What did you do?

Wrote a simple generic "map" function.

On slices, type inference works as I would expect: https://go.dev/play/p/vTd2xwnNA6_X?v=gotip

On generic iterators, however, it does not: https://go.dev/play/p/NnXSXNzx-GB?v=gotip

### What did you expect to see?

[1 4 9 16] (squares of [1 2 3 4])

### What did you see instead?

```
type *SliceIter[int] of inp does not match Iter[T] (cannot infer T and U)
```

(The `U` in this case is the result type of the `square` function, which appears in the expression that produces this error.)

Explicitly instantiating the type params fixes the problem (https://go.dev/play/p/81XMP4cWQoD?v=gotip) but I would have expected that to be unnecessary.

**Comment by ianlancetaylor** [comment]
Closing as dup of #50319.
