### ISSUE TITLE
Learn code on mobile with Dcoder

### ISSUE THREAD

**Issue by S30odeey** [golang/go#50366]
YDSTR on Dcoder
https://code.dcoder.tech/profile/ydstr.workers.dev

**Comment by S30odeey** [comment]
> YDSTR on Dcoder
> https://code.dcoder.tech/profile/ydstr.workers.dev

@ansaba @s3odeey

**Comment by ALTree** [comment]
@S30odeey please stop spamming the issue tracker, thanks.
