### ISSUE TITLE
gccgo: is discontiguous stack available in gold since binutils 2.21 or 2.22?

### ISSUE THREAD

**Issue by dilyanpalauzov** [golang/go#50378]
According to https://go.dev/doc/install/gccgo#Gold, GCCGO can be used with the gold linker, if the gold linker is from binutils version 2.22 or newer, because the linker supports since that version discontiguous stack.

The discontiguous stack is controlled in gcc by `-fsplit-stack`. Its documentation says at https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fsplit-stack, that the feature is available since gold/binutils 2.21.

Please clarify, whether the discontiguous stack feature is available in gold since binutils 2.21 or 2.22.

**Comment by ALTree** [comment]
We don't really use the issue tracker for questions but let's leave this open as a documentation issue in case that sentence is incorrect and needs to be fixed.

cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Does it really matter?  The current version of gold is 2.37.  The 2.22 release was over ten years ago.  Whether you are currently using 2.21 or 2.22, please upgrade.
