### ISSUE TITLE
net/http: add video/mpeg to DetectContentType

### ISSUE THREAD

**Issue by InfoLibre** [golang/go#50376]
### What is the URL of the page with the issue?

https://pkg.go.dev/net/http#DetectContentType

### What is your user agent?

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0

### What did you do?

I used http.DetectContentType with this uploaded MPEG file (unzip it to test):

[MOV01A.mpeg.zip](https://github.com/golang/go/files/7784885/MOV01A.mpeg.zip)

```
buff, err := file.Open()
head := make([]byte, 512)
_, err = buff.Read(head)
contentType = http.DetectContentType(head)
```

### What did you expect to see?

video/mpeg

### What did you see instead?

application/octet-stream (the MIME type of this file isn't recognized)

Could you add this MIME type to http.DetectContentType?

**Comment by seankhliao** [comment]
https://mimesniff.spec.whatwg.org/#matching-an-audio-or-video-type-pattern doesn't specify a pattern for `video/mpeg`
