### ISSUE TITLE
cmd/compile: better error message for invalid `for i,j,k := range`

### ISSUE THREAD

**Issue by SuryaprakashBS** [golang/go#50372]
### Does this issue reproduce with the latest release?
yes

### What did you do?
<pre>package main

var map1 map[string]int

var map2 map[string]int

func main() {
    map1["a"] = 1
    map1["b"] = 2
    
    for i,j,k := range map1{
    	map2[k] = j
    } 	
}
// https://go.dev/play/p/UUnsd-FmrT2</pre>

### What did you see?
./prog.go:15:14: internal compiler error: expected an error about map2[k]

**Comment by ALTree** [comment]
Thanks for reporting this. It triggers an internal compiler error on go1.17.5, but tip correctly gives an error:

> invalid AST: invalid lhs in range clause

Since the program is invalid, this may not qualify for a fix in a 1.17 minor release.

**Comment by thanm** [comment]
@randall77 @griesemer per owners.

**Comment by randall77** [comment]
I agree with @ALTree , I don't think there's anything to fix here.

**Comment by griesemer** [comment]
The error message here should be better: an "invalid AST" error is typically expected for ASTs that are created "manually" (not by the parser) and are incorrect.

I'm going to re-open this as a reminder to fix error message.
