### ISSUE TITLE
x/mobile: support for aab format

### ISSUE THREAD

**Issue by Lallassu** [golang/go#50371]
To build and publish to Playstore for Android it is now required to have aab format instead of the current apk format. Gomobile currently outputs in the apk format. 

Is this in the pipeline or anyone knows of a workaround for generating aab package from a gomobile build?

**Comment by ericlagergren** [comment]
At work, we have a small "wrapper" Android application that simply uses the contents of the APK. Our build step extracts the JNI libraries, etc. We then build AABs like normal.

It's a little more work, but we don't have to depend on gomobile for anything except code generation.

**Comment by Lallassu** [comment]
@ericlagergren thanks for the input. Can you explain a bit more in detail how that is done?

My gomobile build produces the apk that contains both my shared object (.so) and my openal.so file (and assets of course). Then a dex file. Do I understand you correctly that you have written a wrapper in java that acts as an "entry-point" that then uses the so files? Are you implementing your own event handler that then calls different functions in the shared library, for `draw`, `touch`etc?

Any pointers/links would be much appreciated. Meanwhile, I will try out some google-fu.

**Comment by Lallassu** [comment]
I managed to make it work by building `.so` files of my project and OpenAL (requires some mod of cmake files and `gomobile` cmd). Then use these with a new Android Studio project where I copied the `GoNativeActivity.java` as the entry point. Then I manage to build the AAB bundle from Android Studio.

**Comment by Splizard** [comment]
I think this issue should be reopened, gomobile is still going to need support for `.aab` to support android.

**Comment by Lallassu** [comment]
I've released my android game open sourced where I also describe how to build aab packages and OpenAL.

Http://github.com/lallassu/bintris
