### ISSUE TITLE
affected/package: generic problem

### ISSUE THREAD

**Issue by acehow** [golang/go#50384]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.18 beta
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
windows11
</pre></details>

### What did you do?

[1]. this is ok:  https://go.dev/play/p/RyrAKhkhBvF?v=gotip
[2]. but this is not ok:  https://go.dev/play/p/_ULlldy6XqP?v=gotip

### What did you expect to see?
I wonder what's the difference. It's a bug or something.
Maybe you can do something make [2] runs ok??

### What did you see instead?
I see [./prog.go:9:7: cannot use t (variable of type []string) as type []any in argument to test]

**Comment by martisch** [comment]
The `...any` means that the test function is having dest be a `[]any` as argument. https://go.dev/ref/spec#Passing_arguments_to_..._parameters

Rejecting a []string as input is working as intended a slice of strings is not a slice of interface{} and can not be used as such. 

This is a variant of
https://go.dev/doc/faq#convert_slice_of_interface which is obfuscated a bit by the ... syntax for variadic arguments.

`Maybe you can do something make [2] runs ok??` that would require the gp language to change which requires a language proposal and has been discussed before: e.g. https://github.com/golang/go/issues/21651 and is not trivial as []T and []any have differrent memory layouts currently so would require e.g. copies under the hood with other consequences to semantics of the conversion.
