### ISSUE TITLE
x/pkgsite: Super small typo in documentation of ShouldNotBeBlank

### ISSUE THREAD

**Issue by kamyarghiam** [golang/go#50388]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/smartystreets/assertions#section-readme
 
### What is your user agent?
 

 
 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
 
### Screenshot
 

 
<img width="1184" alt="Screen Shot 2021-12-29 at 3 44 51 PM" src="https://user-images.githubusercontent.com/34321858/147702040-9ba8a79e-c798-4589-857e-d3eea54ce63d.png">

 
 
### What did you expect to see?
 
 There is a typo with the definition of "ShouldNotBeBlank," I believe. The definition says 
`ShouldNotBeBlank receives exactly 1 string parameter and ensures that it is equal to "".` It should say that it ensures it is **not** equal to "". 

### What did you see instead?
`ShouldNotBeBlank receives exactly 1 string parameter and ensures that it is not equal to "".`

**Comment by seankhliao** [comment]
this should be reported to github.com/smartystreets/assertions
