### ISSUE TITLE
x/pkgsite: link to custom links is broken.

### ISSUE THREAD

**Issue by lostluck** [golang/go#50387]
### What is the URL of the page with the issue?
https://pkg.go.dev/about
 
 
### What is your user agent?  (N/A)
Mozilla/5.0 (X11; CrOS x86_64 14268.51.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.77 Safari/537.36
 
### Screenshot
 N/A
 
### What did you do?
Click on the link to "this issue" in the Adding links section. https://pkg.go.dev/about#adding-links

### What did you expect to see?
https://github.com/golang/go/issues/42968
  
 ### What did you see instead?
https://pkg.go.dev/issue/42968  (currently a 404)

**Comment by lostluck** [comment]
I'm happy to put in the quick fix to fix the link, and am spining up my contribution set up.

**Comment by lostluck** [comment]
https://go-review.googlesource.com/c/pkgsite/+/374854

**Comment by jamalc** [comment]
Fixed in [CL 374854](https://go-review.googlesource.com/c/pkgsite/+/374854)
