### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by yybinpitaya** [golang/go#50393]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.5 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\CDLX\AppData\Local\go-build
set GOENV=C:\Users\CDLX\AppData\Roaming\go\env  
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\07_Study\G_Golang\std\var\QbittorrentAutoLimitShare\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\CDLX\AppData\Local\Temp\go-build913644074=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

<pre>
type A struct {
}

func (this *A) Test() string {
	return "123"
}

type C struct {
	client *A
}

func main() {
	c := C{}
	log.Println(c.client.Test())

	var a *A
	log.Println(a.Test())

}

</pre>
### What did you expect to see?
panic error

### What did you see instead?

print 123
print 123

**Comment by Jason7602** [comment]
Actually, method call with receiver is a typical function call and and does not need to check whether the receiver is nil.
For details, see the [Language Specification](https://go.dev/ref/spec#Calls)

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
