### ISSUE TITLE
embed: http中使用embed，取消相对路径后，路径中/需要修改为\才能读取到静态资源

### ISSUE THREAD

**Issue by cnwangfei** [golang/go#50408]
### What version of Go are you using (`go version`)?

<pre>
$ go 1.16.11
</pre>
我是这样做的改动

[HttpEmbed](https://github.com/cnwangfei/go-HttpEmbed/blob/main/embed.go)

<pre>
package httpEmbed

import (
	"embed"
	"io/fs"
	"path"
	"path/filepath"
)

type Fs struct {
	*embed.FS        // 静态资源
	Path      string // 设置embed文件到静态资源的相对路径，也就是embed注释里的路径
}

func (f Fs) Open(name string) (fs.File, error) {
	// 拼接相对路径
	fullName := filepath.Join(f.Path, filepath.FromSlash(path.Clean("/"+name)))
	// 修改http路径中的\为/
	fullName = filepath.ToSlash(fullName)
	//fmt.Println(fullName)
	fs, err := f.FS.Open(fullName)
	return fs, err
}
</pre>

**Comment by mdlayher** [comment]
Sorry, we can't help with non-English issues on the tracker. See: https://github.com/golang/go/wiki/NonEnglish and for questions: https://github.com/golang/go/wiki/Questions.

**Comment by ianlancetaylor** [comment]
The `io.FS` package always uses forward slashes.  See https://pkg.go.dev/io/fs#ValidPath.
