### ISSUE TITLE
cmd/go: command to find minimum version with no known CVE

### ISSUE THREAD

**Issue by tamalsaha** [golang/go#50409]
Is it possible to introduce a `go mod` command/feature that can look at data from deps.dev and automatically use the minimum version that does NOT have a known CVE. With the prevalence of code scanners, we keep getting alerts regarding CVEs. Currently the process to fix such alerts require a lot of manual work. If `go mod` can automate some of this, that will be much appreciated. As an example, npm has a `npm audit fix` command that similar things for js projects. Thanks!

**Comment by ianlancetaylor** [comment]
CC @bcmills @matloob

**Comment by seankhliao** [comment]
I think if you're already upgrading beyond what your dependencies declare, it's unclear why you'd want minimum version without CVE rather than just upgrading to the latest. Many bugs get fixed without CVEs being filed.
