### ISSUE TITLE
proposal: encoding/json: using inspired jq syntax to unmarshal/marshall JSON

### ISSUE THREAD

**Issue by rramiachraf** [golang/go#50407]
Let's imagine we have this JSON:

```json
{
	"name": {
		"first": "John",
		"last": "Doe"
	}
}
```

And a developer wants to unmarshal it into this struct:

```go
type person struct {
          FirstName string
          LastName  string
}
```

I think using something like the syntax below would make doing the decoding process a lot easier without the need of a custom unmarshaler or using any external packages and would be a life saver when you have big JSON strings with dozens of nested data.

```go
type person struct {
          FirstName string `json:"name.firstname"`
          LastName  string `json:"name.lastname"`
}

**Comment by mdlayher** [comment]
The equivalent that works today is:

```go
type person struct {
    Name struct {
        First string `json:"first"`
        Last string `json:"last"`
    } `json:"name"`
}
```

Why does this need to be part of the standard library? Couldn't this syntax be implemented in a third party package? See https://go.dev/doc/faq#x_in_std.
