### ISSUE TITLE
cmd/go: compile .c files with swig too

### ISSUE THREAD

**Issue by gopherbot** [golang/go#5041]
by **meyerkp**:

<pre>I tried out the swig tutorial example using the swig and go (tip)
versions below:

SWIG Version 2.0.9 , 
$ go version
go version devel +dfbaf2b999a6 Tue Mar 12 21:37:18 2013 -0700 linux/amd64

The following files (attached) are in $GOPATH/src/example:
example.c, example.swig, declar.go

(declare.go was added to prevent go install complaining about the lack of go files in
the directory.

test.go is in $GOPATH/src/.

As per <a href="http://groups.google.com/group/golang-nuts/browse_thread/thread/3ff41b4e38f47f92">http://groups.google.com/group/golang-nuts/browse_thread/thread/3ff41b4e38f47f92</a>

The following error occurs:

 go build test.go
~/go/src$ ./test
./test: symbol lookup error:
/home/kmeyer/go/pkg/linux_amd64/swig/example-example-swig.so: undefined symbol:
My_variable</pre>

Attachments:
1. <a href="https://storage.googleapis.com/go-attachment/5041/0/example.c">example.c</a> (248 bytes)
2. <a href="https://storage.googleapis.com/go-attachment/5041/0/example.swig">example.swig</a> (314 bytes)
3. <a href="https://storage.googleapis.com/go-attachment/5041/0/test.go">test.go</a> (132 bytes)
4. <a href="https://storage.googleapis.com/go-attachment/5041/0/declar.go">declar.go</a> (16 bytes)

**Comment by ianlancetaylor** [comment]
I'm pretty sure this works now.  The SWIG support is completely different these days.
