### ISSUE TITLE
windows: go.exe missing in download archive https://go.dev/dl/go1.17.5.windows-amd64.zip

### ISSUE THREAD

**Issue by amhambra** [golang/go#50416]
### What version of Go are you using (`go version`)?

<pre>
note: I try to install go1.17.5 on a clean notebook where never go was installed before.
</pre>

### Does this issue reproduce with the latest release?
Yes
go1.17.4 windows zip does contain go.exe 

### What operating system and processor architecture are you using (`go env`)?

Windows 10 21H1 build 19043.1415
amd64

### What did you do?

download https://go.dev/dl/go1.17.5.windows-amd64.zip
no go.exe in go1.17.5.windows-amd64\go\bin

download https://go.dev/dl/go1.17.5.windows-amd64.msi
installed
missing go.exe in c:\Program files\go\bin

### What did you expect to see?
MSI install: c:\Program files\go\bin\go.exe
ZIP UNPACK: go1.17.5.windows-amd64\go\bin\go.exe

### What did you see instead?
missing go.exe

NOTE: antivirus program was disabled to check if older issue go.exe detected as malware can be ruled out.
NOTE: Disable seems not to work. Download on Linux was fine and I could find go.exe in 1.17.5 zip package.

**Comment by davecheney** [comment]
Is it possible that your AV software ate them?

**Comment by amhambra** [comment]
Nope, had disabled both.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
