### ISSUE TITLE
cmd/compile:  incorrect "cannot use .this" error when using _ for multiple type parameters in method declaration

### ISSUE THREAD

**Issue by samherrmann** [golang/go#50419]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18beta1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

N/A. Type parameters are not available in any other version that are currently available.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOVERSION="go1.18beta1"
</pre></details>

### What did you do?

```go
package main

import (
    "fmt"
)

func main() {
    foo := &Foo[string, int]{
        valueA: "i am a string",
        valueB: 123,
    }
    fmt.Println(foo)
}

type Foo[T1 any, T2 any] struct {
    valueA T1
    valueB T2
}

func (f *Foo[_,_]) String() string {
    return fmt.Sprintf("%v %v", f.valueA, f.valueB)
}
```
* [Playground](https://gotipplay.golang.org/p/-gvpfilXYC3)
* See [this StackOverflow post](https://stackoverflow.com/questions/70572713/cannot-use-this-error-when-using-for-multiple-type-parameters-in-method-decla) for more details.

### What did you expect to see?

I expected the code snippet above to build and run successfully.

### What did you see instead?

Build error:
```sh
<autogenerated>:1: cannot use .this (type *Foo[string,int]) as type *Foo[go.shape.string_0,go.shape.string_0] in argument to (*Foo[go.shape.string_0,go.shape.int_1]).String
```

**Comment by danscales** [comment]
Thanks for the issue report!

This is a problem in the main compiler (not the types2 typechecker).  It happens when generating method wrappers.  It looks like the use of  [_, _] in `func (f *Foo[_, _]) String() string {` is causing the bug - we are somehow interpreting the blanks as the same type.  Works fine if you just replace [_, _] with [T1, T2].
