### ISSUE TITLE
x/vulndb: automate published and modified times

### ISSUE THREAD

**Issue by julieqiu** [golang/go#50434]
Instead of manually filling out the published and last_modified timestamps when add a YAML report, these should be automatically generated based on the commit history when the database is created.

**Comment by rolandshoemaker** [comment]
Re-opening for the `last_modified` portion of this. I think the same `FileHistory` call can be reused, pulling the date from HEAD rather than the originating commit.

**Comment by neild** [comment]
Fixed by https://go.dev/cl/392539 (which I put the wrong issue link in).
