### ISSUE TITLE
x/build/cmd/coordinator: SlowBots status page broken for CL 375694

### ISSUE THREAD

**Issue by bcmills** [golang/go#50457]
The SlowBot status page at https://farmer.golang.org/try?commit=edfc2bef, linked from [CL 375694](https://go-review.googlesource.com/c/go/+/375694/3#message-a869de37952174356c179cf2b78cdc17ed029776), appears to be broken:
![unnamed](https://user-images.githubusercontent.com/5200974/148291847-cedf2439-e795-48e0-9142-d1960f740ff1.png)

That CL attempts to fix a test that fails fairly frequently on the builders (#34495), so I would like to be able to review and merge it soon. Is there something we can do to unblock the SlowBots?

(CC @golang/release)

**Comment by prattmic** [comment]
Fixed by https://golang.org/cl/375754.
