### ISSUE TITLE
go run takes too long to execute

### ISSUE THREAD

**Issue by NeutronX-dev** [golang/go#50459]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Happened to me before, but it worked afterwards

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Y\AppData\Local\go-build
set GOENV=C:\Users\Y\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Y\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Y\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.5
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Y\AppData\Local\Temp\go-build4075858684=/tmp/go-build -gno-record-gcc-switches
gdb --version: GNU gdb (GDB) 10.2
</pre></details>

### What did you do?
I made an application using [fyne.io](https://fyne.io/) and [faiface/beep](https://github.com/faiface/beep), everything was working great, I tried to test my program after a change and the console stayed blank. I restarted my computer, repaired Go, reinstalled Go, and nothing seems to work. I tried with another project ([NeutronX-dev/WorkshopDownloader](https://github.com/NeutronX-dev/WorkshopDownloader)) and it ran, but It took a good 5 minutes for it to just run. Retried with my newest project and It doesn't run.

Video:
https://vid.nutron.repl.co/vid/custom/?v=go-error-0

### What did you expect to see?
I expected a GUI to open and a message in the Terminal.

### What did you see instead?
Nothing

Edit: Compiling with both fyne nor go works. it just closes. And If i try from the terminal (`./main.exe`) shows nothing

**Comment by davecheney** [comment]
You could try `go run -v main.go` which will print the packages that are built.

Historically anti virus software on windows has caused a large % of issues. Please try check your AV software to see if it has decided to prevent you running the freshly built go binary.

**Comment by NeutronX-dev** [comment]
It does the same as If I were to just do `go run main.go`. And the anti-virus was disabled (File Shield) I disabled Beahavior Shield, and it still gives out nothing

**Comment by NeutronX-dev** [comment]
Apparently the problem was not with Go. I removed this code:
```go
Application.Lifecycle().SetOnStopped(func() {
	CloseChannel <- true
})
```
and the program seemes to have worked, but it stopped, so I figured that the Gorutine is executed and awaits for an error before calling `Window.ShowAndRun()`. And that was the problem, `main` awaits for a message, plus that if there are no errors with reading the audio it jumps to the loop instead of returning `nil`
