### ISSUE TITLE
cmd/compile: spurious "declared but not used" errors

### ISSUE THREAD

**Issue by rsc** [golang/go#50493]
Not a release blocker but good to fix if easy.

```
package p

func f() {
	x := 1
	v := 2
	switch v.(type) {
	case int:
		println(x)
	}
}
```

```
% go tool compile /tmp/x.go
/tmp/x.go:4:2: x declared but not used
/tmp/x.go:6:9: v (variable of type int) is not an interface
```

Looks like because the switch header couldn't type-check, the bodies were not considered. And since the bodies were not considered, it looks like x was never used. The compiler should print the real error on line 6 and not print about line 4.

**Comment by XiaodongLoong** [comment]
@rsc
I try  to fix this issue, but I found a similar issue(https://github.com/golang/go/issues/50639).
