### ISSUE TITLE
runtime/chan.go: Possibility of needless lock/unlock

### ISSUE THREAD

**Issue by roohat** [golang/go#50492]
When I was looking on how go implemented the channels for my personal C++ project, I saw this piece of code, which there are multiple instances of it in the same file:

https://github.com/golang/go/blob/11b28e7e98bce0d92d8b49c6d222fb66858994ff/src/runtime/chan.go#L201-L206

Why not check if channel is closed and panic without lock/unlock its mutex? Is it because `.closed` may have been manually modified without calling `.close()` and to make sure all locks are closed?

Not a go guy, hope I didn't waste your time with this question. Have a nice day 👋

**Comment by roohat** [comment]
Duplicate of #26011

**Comment by seankhliao** [comment]
there's a comment in the section above

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
