### ISSUE TITLE
affected/package: x/time/rate

### ISSUE THREAD

**Issue by lysShub** [golang/go#50490]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/worker/.cache/go-build"
GOENV="/home/worker/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/worker/go/pkg/mod"
GONOPROXY="git.querycap.com"
GONOSUMDB="git.querycap.com"
GOOS="linux"
GOPATH="/home/worker/go"
GOPRIVATE="git.querycap.com"
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/a/falcontsdb/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build209571013=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you expect to see?
golang.org/x/time v0.0.0-20211116232009-f0f3c7e86c11

```go
package main

import (
	"context"
	"fmt"
	"time"

	"golang.org/x/time/rate"
)

func main() {
	fmt.Println("golang.org/x/time/rate bug:")
	var ratelimit *rate.Limiter = rate.NewLimiter(5, 100)
	start := time.Now()
	for i := 0; i < 5; i++ {
		ratelimit.Wait(context.Background())
	}
	fmt.Println(time.Since(start))
	start = time.Now()
	for i := 0; i < 100; i++ {
		ratelimit.Wait(context.Background())
	}
	fmt.Println(time.Since(start))
}
```
Got:
```go
golang.org/x/time/rate bug:
0s
1.0016973s
```

### What did you see instead?
Expect:
```go
golang.org/x/time/rate bug:
5s
100s
```

**Comment by seankhliao** [comment]
https://pkg.go.dev/golang.org/x/time/rate#Limiter
> initially full

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
