### ISSUE TITLE
x/pkgsite: CreateOrder example on go.dev/doc/database/execute-transactions page doesn't compile

### ISSUE THREAD

**Issue by imballinst** [golang/go#50508]
### What is the URL of the page with the issue?

https://go.dev/doc/database/execute-transactions

### What is your user agent?

Firefox 94.0 (64-bit)

### Screenshot

The `fail` function (below the marked comment), expects 2 return values. However, the function only returns `fmt.Errorf(...)`.

![image](https://user-images.githubusercontent.com/7077157/148627818-64471923-ca04-486b-99be-b135af3c009f.png)

### What did you do?

I copy-pasted the code to my IDE (VS Code) and got an error (the `return` line was marked with a red line).

### What did you expect to see?

There should be no error in the copy-pasted function. It should return, maybe, `0, fmt.Errorf(...)`?

### What did you see instead?

Error during compilation.

```
./main.go:229:3: not enough arguments to return
	have (error)
	want (int64, error)
```

I'm new to Go, so please let me know if I did something wrong instead. Thanks!

**Comment by odeke-em** [comment]
Thank you for filing this bug @imballinst and welcome to the Go project! Thank you @seankhliao for the triage. Happy New Year y'all!

@willpoint is going to send a CL shortly to fix this.

**Comment by dharmit** [comment]
@odeke-em well the [PR](https://golang.org/cl/376974) looks good (or could've used `orderID` instead of `0` - no big deal). Could someone with enough rights help merge it so that the example isn't broken any more?
