### ISSUE TITLE
crypto/x509:1.17 introduced new test of certificate version

### ISSUE THREAD

**Issue by XIELongDragon** [golang/go#50518]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.17
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\XIE\AppData\Local\go-build
set GOENV=C:\Users\XIE\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\XIE\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\XIE\go;D:\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\XIE\AppData\Local\Temp\go-build2538790511=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
Do HTTPS request

In Go 1.17, introduced more checking of cert' version
https://cs.opensource.google/go/go/+/dev.boringcrypto.go1.17:src/crypto/x509/parser.go;l=841

And it did not exist in Go 1.16

https://cs.opensource.google/go/go/+/dev.boringcrypto.go1.16:src/crypto/x509/x509.go;l=1313 

This new checking will give a new error `x509: invalid version` while the old version will continue the HTTPS request 

### What did you expect to see?

The same code access to the same version of HTTPS server should be successful both while compiling in Go 1.16 and Go 1.17

### What did you see instead?

The same code access to the same version of HTTPS server should be successful both while compiling in Go 1.16 but got an error in Go 1.17

**Comment by ianlancetaylor** [comment]
CC @golang/security

**Comment by ianlancetaylor** [comment]
Note for maintainers: if this change is correct, which it likely is, it should probably be called out in the release notes.  Currently the 1.17 release notes say "ParseCertificate has been rewritten, and now consumes ~70% fewer resources. The observable behavior has not otherwise changed, except for error messages."

**Comment by FiloSottile** [comment]
With such a wide rewrite, and such a complex spec, it's impossible to guarantee that behavior will stay the same across the board (without a lot of fuzzing and making the new code significantly worse). What @rolandshoemaker did was make sure there are no observable changes *when verifying certificates that follow the WebPKI profile*, so maybe we should amend the release notes to say

> ParseCertificate has been rewritten, and now consumes ~70% fewer resources. The observable behavior when processing WebPKI certificates has not otherwise changed, except for error messages.

Anyway, this change looks correct to me, we only support X.509 v3 certificates, as profiled by RFC 5280.

**Comment by rolandshoemaker** [comment]
+1 to what Filippo said, this is correct behavior. It would be great if we could've made this change completely transparent but this tightening of what we support is likely to be beneficial in the long term anyway.

I like the suggested release note change.

**Comment by ianlancetaylor** [comment]
Thanks.
