### ISSUE TITLE
affected/package: misleading comments about panic in the add function

### ISSUE THREAD

**Issue by luyoyo** [golang/go#50525]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/liulu/Documents/learn/bin"
GOCACHE="/Users/liulu/Library/Caches/go-build"
GOENV="/Users/liulu/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/liulu/Documents/learn/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/didi/Documents/learn"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,https://mirrors.aliyun.com/goproxy/"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jz/gm2fxw8x4dqg1lg9ydyxl4w40000gn/T/go-build2365601841=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

When I learned the  add function, I see the code of panic as follows:
```
if w != 0 && delta > 0 && v == int32(delta) {
    panic("sync: WaitGroup misuse: Add called concurrently with Wait")
}
```
w, the number of waiter, is the number of waiting goroutines. There are only two operations: adding 1 and setting zero, so it must be greater than or equal to 0. The first time you use add function, such as add (n), you can see v = n, w = 0, and w != 0 indicates that the function of wait  has been executed, that is, it is not the first addition operation;

delta > 0 indicates that this is an addition operation. If v == int32(delta), that is, v + delta == delta, deduces v = 0, it may be the first time to add () or execute add (- 1) to reduce v to 0.

So I think the condition for this painc trigger should be two add concurrency. The first add reduces couter to 0, when the second add adds 1, the second will trigger painc here.

### What did you expect to see?
The code comment of panic should be changed as
```
if w != 0 && delta > 0 && v == int32(delta) {
    panic("sync: WaitGroup misuse: Add called concurrently with Add")
    // or panic("sync: WaitGroup misuse: Multiple add called concurrently")
}
```

### What did you see instead?
```
if w != 0 && delta > 0 && v == int32(delta) {
    panic("sync: WaitGroup misuse: Add called concurrently with Wait")
}
```

**Comment by seankhliao** [comment]
it's safe to call WaitGroup.Add concurrently. the panic is diagnosing Wait called before the first Add

**Comment by pengpeng1993** [comment]
> it's safe to call WaitGroup.Add concurrently. the panic is diagnosing Wait called before the first Add

Hmm ,it seem not safe to call WaitGroup Add concurrently. for instance  when first add reduces couter to 0 then first add suspend ,other add coming atomic Add successful will trigger painc. suppose other add's parameter is positive number 
then 
 	if w != 0 && delta > 0 && v == int32(delta) {
		panic("sync: WaitGroup misuse: Add called concurrently with Wait")
	}
I am new to use golang, and not sure if I understand this correctly, so let me know if i am wrong. thanks a bunch
