### ISSUE TITLE
net: TestLookupHostCancel failure with "too many open files" on netbsd-arm-bsiegert builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#50537]
```
#!watchflakes
post <- pkg == "net" && test == "TestLookupHostCancel" && `socket: too many open files`
```

```
--- FAIL: TestLookupHostCancel (5.41s)
    lookup_test.go:962: lookup www.google.com on 192.168.87.1:53: dial udp 192.168.87.1:53: socket: too many open files
FAIL
FAIL	net	25.064s
```

It's not clear to me whether this is a platform bug in the native resolver (CC @bsiegert), or if the parallel `net` tests are actually leaving too many file descriptors open when this test executes (compare #46279; CC @bradfitz @ianlancetaylor).

`greplogs --dashboard -md -l -e 'lookup www\.google\.com .*: too many open files'`

[2022-01-07T18:20:24-ade5488/netbsd-arm-bsiegert](https://build.golang.org/log/e1aa2029ece256662445e75f0e08a50c741cca51)

**Comment by bcmills** [comment]
Leaving on the backlog since there has only been one such failure so far.

If and when we see more of these, we might get a better idea of whether it is a platform bug or a test bug. (But note that more platforms will be skipping this test in order to resolve #50191.)

**Comment by bsiegert** [comment]
It could also be the number of open files in the system. On NetBSD, there is a global maximum that can be changed via `sysctl`. I'll increase this number on the 32-bit ARM builder.

**Comment by ianlancetaylor** [comment]
@bsiegert That error should report `ENFILE` ("too many open files in system") but the test is failing with `EMFILE` ("too many open files").

**Comment by ianlancetaylor** [comment]
This isn't the native resolver; if it were the error wouldn't say `socket`.  This is the Go resolver.

**Comment by ianlancetaylor** [comment]
As far as I can tell from the code, the fact that the context is canceled before calling `DefaultResolver.LookupHost` should mean that it does not create any UDP sockets.  The DNS lookup will eventually call `sysDialer.dialSerial` which checks the context in the loop.  So the loop in the test shouldn't create any file descriptors.  (Verified by running the test on Linux and counting the number of calls to the `socket` system call.)  The error is happening for the single valid lookup, without a canceled context, that the test runs at the end.

If that is correct, then it's weird that the test takes 5 seconds to run.

And it means that the failure doesn't have much to do with `TestLookupHostCancel` as such.

But I may have made some mistake in this analysis.
