### ISSUE TITLE
cmd/build: relocation target go.info.example/logger.loggingT not defined

### ISSUE THREAD

**Issue by lsytj0413** [golang/go#50546]
### What version of Go are you using (`go version`)?

<pre>
$ go version: go1.17.5 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

It reproduce this version:
```
   go1.17.1
   go1.17.5
   go1.17.6
   go1.17beta1
   go1.17rc2
```

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

use **go:linkname** with source:

file internal.s:
```
// NOTE:
// This file is stub file, to ensure the "//go:linkname" is usable.
// See https://pkg.go.dev/cmd/compile for more detail.
```

file config.go:
```
import (
	_ "unsafe" // We must import unsafe package to use "go:linkname"
)

// loggingT collects all the global state of the logging setup.
// NOTE: this is redefined for v2.logging
// nolint
type loggingT struct { // nolint
}

//go:linkname logging k8s.io/klog/v2.logging
var logging loggingT
```

and import this package in main.

### What did you expect to see?

go build success.

### What did you see instead?

```
go build -o /var/folders/n_/qhczpf412h3ghl93j3z6zzx00000gp/T/__debug_bin2079129682  .
# example
go.info.k8s.io/klog/v2.logging: relocation target go.info.example/logger.loggingT not defined
```

1. Test this on many go1.17, all of tested version reproduce this error.
2. Test this on go1.16.13, go build success.
3. go run success in go1.17

**Comment by ianlancetaylor** [comment]
I'm not sure why this is failing but in general the use of `go:linkname` to cross arbitrary package boundaries is not supported.  Why are you trying to do this?

**Comment by lsytj0413** [comment]
> 

The third-party package doesn't provide an exported function to modify the option, and the object is unexported, so i use the `go:linkname` to access it. I know this is not general solution, but in current scenario it works for me.

**Comment by ianlancetaylor** [comment]
This builds for me.  But there are no promises that or any other approach using `go:linkname` will continue to work.

I'm going to close this issue.

```Go
package main

import (
	_ "unsafe"

	_ "k8s.io/klog/v2"
)

type LoggingT struct {
	I int
}

//go:linkname logging k8s.io/klog/v2.logging
var logging LoggingT

var V LoggingT
var V2 interface{} = V

func main() {}
```
