### ISSUE TITLE
x/tools/go/analysis/passes/copylock: allow assignment to blank identifier

### ISSUE THREAD

**Issue by buglloc** [golang/go#50551]
After copylock was able to detect copylock in multi-assignment (https://github.com/golang/tools/pull/319) it starts report false positives on test type assertions.
For example, for code:
```
package tst

import (
	"sync"
)

type mut struct{ mu sync.Mutex }

func foo(a interface{}) {
	if _, ok := a.(mut); ok {
		_ = ok
	}
}
```
copylock reports:
```
/home/buglloc/work/projects/copylock-fp/tst/tst.go:10:14: assignment copies lock value to _: (github.com/buglloc/copylock-fp/tst.mut, bool) contains github.com/buglloc/copylock-fp/tst.mut contains sync.Mutex
```

Is there any reason not to check that lhs in [checkCopyLocksAssign](https://github.com/golang/tools/blob/52e95274200fabcac2b99138b37c22fec3ae0460/go/analysis/passes/copylock/copylock.go#L77) is points to blank identifier?

**Comment by bcmills** [comment]
Why would you need to do that kind of type-assertion? If `mut` is non-copyable, then it also isn't safe to copy a `mut` value into a variable of type `interface{}` — so the type that you're checking for should itself be impossible in this scenario.

(CC @timothy-king)

**Comment by timothy-king** [comment]
Like @bcmills, I am not yet really sure why we would not want to warn on this code example though. More details or a more realistic example might help here. FWIW suppressing the check on assignment to `_` identifiers should be straight-forward if it is desirable.

**Comment by buglloc** [comment]
Sorry for the bad example :(
In my case, we use this type-assertion in reflection, just to ignore unnecessary struct.
Unfortunately, the code is private, but I have tried to rewrite it as closely as possible:
```go

type Registrator interface {
	Register()
}

type Struct struct {
	sync.Mutex
	Nested map[string]Registrator
}

func register(v reflect.Value) bool {
	c, ok := v.Interface().(Registrator)
	if ok {
		c.Register()
	}

	return ok
}

func RegisterRecursively(value interface{}) {
	val := reflect.ValueOf(value)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	if val.Kind() != reflect.Struct {
		return
	}

	if _, ok := val.Interface().(Struct); ok {
		// A Struct handles registration on its own
		return
	}

	for i := 0; i < val.NumField(); i++ {
		field := val.Field(i)
		if !field.CanInterface() {
			continue
		}

		if register(field) {
			continue
		}

		if field.Kind() == reflect.Ptr {
			field = field.Elem()
		}

		switch field.Kind() {
		case reflect.Map:
			for _, item := range field.MapKeys() {
				register(field.MapIndex(item))
			}
		case reflect.Struct:
			RegisterRecursively(val.Field(i).Interface())
		}
	}
}
```

I agree with you that this code looks rather weird and can be rewritten, but safe for non-copyable objects I guess.

**Comment by bcmills** [comment]
The call to `val.Interface()` in that sequence copies the lock value that isn't supposed to be copied.

IMO one clearer way to write that reflection code is:
```go
	if val.Kind() == reflect.Ptr {
		if val.Type() == reflect.TypeOf((*Struct)(nil)) {
			// A *Struct handles registration on its own.
			return
		}
		val = val.elem()
	}
```

**Comment by buglloc** [comment]
Yeah, you're right. It turns out that there really is no possible scenario :)

Thanks!
