### ISSUE TITLE
About DefaultServeMux

### ISSUE THREAD

**Issue by liutaot** [golang/go#50566]
https://github.com/golang/go/blob/3d3f5d912b776424e50be276bc3a4ae02bf8d143/src/net/http/server.go#L2284
Why not like this?
```go
var DefaultServeMux = &ServeMux{}
````

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
