### ISSUE TITLE
wiki: TestComments change - assert libraries

### ISSUE THREAD

**Issue by rthier** [golang/go#50573]
The section about [Assert Libraries](https://github.com/golang/go/wiki/TestComments#assert-libraries) discourage the use of them.

But I guess there's a little bit mistake in this approach because we have good libraries that provide assert functions.

The argument _omits interesting information about what the test got right_ is not the real true, is more easy to understand what the test does with 2 or 3 `asserts` than a `if` with 2 or 3 `ORs` inline. Furthermore libraries as [Testify](https://github.com/stretchr/testify) provide rich and easy-readable informations when the test fails in the `assert` functions.

Finally, using `asserts` or `ifs` don't guarantee that the test is right, the argument _Assert libraries make it too easy to write imprecise tests_ is more about the quality of test than the use of an assert library.

**Comment by ianlancetaylor** [comment]
Thanks, but we are satisfied with the discussion as it stands.  If you want to discuss this, please use a forum, such as golang-nuts rather than the issue tracker.  See https://golang.org/wiki/Questions.  Thanks.
