### ISSUE TITLE
x/tools/gopls: add analyzer for vulnerability check

### ISSUE THREAD

**Issue by hyangah** [golang/go#50577]
References:

Experimental command line tool: https://pkg.go.dev/golang.org/x/exp/vulndb/govulncheck
Experimental API: https://pkg.go.dev/golang.org/x/exp/vulncheck
Vuln DB access API: https://pkg.go.dev/golang.org/x/vuln

* Gopls will publish the analysis results as LSP diagnostics to help easy integration in other LSP-aware integration.
* We may end up implementing additional custom command or notification to turn on/off the analysis easier or retrieve extra information about vulnerability details.
* However, vulncheck requires a whole-program analysis so it requires handling slightly different from typical analyzers.

cc @julieqiu @zpavlinovic

**Comment by hyangah** [comment]
We realized two different analysis types using the Vuln DB are feasible and useful.

One is a real-time analysis of the package import paths and surfacing the fact in real time using diagnostics.
Another is a full callgraph analysis (golang.org/x/vuln/cmd/govulncheck) that performs the whole program analysis and reports only the vulnerabilities that actually affect the analyzed packages. That can be expensive and it's suitable as one-off analysis command run. Gopls will export that interface as a custom gopls command and gopls vulncheck command (~= govulncheck packaged inside gopls).

This issue is tracking the progress for the first one.

**Comment by nightlyone** [comment]
@hyangah may I suggest contributing the second analysis to golangci-lint instead? Or make it available as a goanalysis pass that is easy to integrate into golangci-lint?

The reason is that I am not aware of any CI/CD pipeline that runs gopls commands. But I am aware of dozens of golangci-lint integrations in CI/CD pipelines. Integrating most linter work actually happens primarily there.

**Comment by hyangah** [comment]
Thanks for the suggestion. From our experiment - the second analysis takes easily a couple of minutes for a good size repo & accesses the network to retrieve the data. Is it really a good idea to add to a linter?

**Comment by hyangah** [comment]
We learned gopls does not compute/hold analysis facts for all packages in the workspace (https://github.com/golang/go/issues/48738), so there is some ground work to be done before integrating to gopls.

For short term, we are currently working on the analyzer that is pluggable to a linter that uses the go/analysis framework. (moving off of gopls/v0.9.0 milestone)

**Comment by hyangah** [comment]
We ended up with a slightly different approach which supports a hybrid mode of vulnerability scanning.

* Import-based analysis - that reports known vulnerabilities on the analyzed packages and the packages they import transitively. This can result in false positives if the project imports a vulnerable package but doesn't call the vulnerable part of the package.

* Govulncheck command integration - that reports vulnerabilities that are actually used by doing call graph analysis.

For CI uses, `govulncheck` and `govulncheck -json` seems to be working well already.

For more details - https://github.com/golang/vscode-go/wiki/features#analyze-vulnerabilities-in-dependencies
