### ISSUE TITLE
net/http/internal/testcert: backport use of FIPS-compliant certificate

### ISSUE THREAD

**Issue by qmuntal** [golang/go#50572]
https://github.com/golang/go/commit/90860e0c3110ac5898dfe8e0e0fafd0aea8d979a landed in master last week to fix #48674. The same issue affects all boring branches when `crypto/tls/fipsonly` is imported.

@neild @FiloSottile could we have that fix backported into go1.16 and go1.17, and then cut the corresponding boring releases?

IMO this issue is sever enough to meet the backport policy, but I'm not sure if it also applies to boring branches.

**Comment by neild** [comment]
Seems worth backporting, opened #50585 and #50586.
