### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by TimonDalton** [golang/go#50574]
https://pkg.go.dev/cloud.google.com/go/bigquery/storage/managedwriter
This code won't compile if ran.

### Screenshot
 
![image](https://user-images.githubusercontent.com/32957797/149165125-c18fef35-614d-44b3-a16a-5bf792fb675c.png)

 Problem:

 	mesgs := []*myprotopackage.MyCompiledMessage{
		{
			UserName: proto.String("johndoe"),
			EmailAddress: proto.String("jd@mycompany.mydomain",
			FavoriteNumbers: []proto.Int64{1,42,12345},
		},
		{
			UserName: proto.String("janesmith"),
			EmailAddress: proto.String("smith@othercompany.otherdomain",
			FavoriteNumbers: []proto.Int64{1,3,5,7,9},
		},
	}

Should be: (exclamation marks near change)

	mesgs := []*myprotopackage.MyCompiledMessage{
		{
			UserName: proto.String("johndoe"),
			EmailAddress: proto.String("jd@mycompany.mydomain"),//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
			FavoriteNumbers: []proto.Int64{1,42,12345},
		},
		{
			UserName: proto.String("janesmith"),
			EmailAddress: proto.String("smith@othercompany.otherdomain"),//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
			FavoriteNumbers: []proto.Int64{1,3,5,7,9},
		},
	}

**Comment by seankhliao** [comment]
Please report the problem to cloud.google.com/go/bigquery/storage/managedwriter
