### ISSUE TITLE
internal/fuzz: test_fuzz_minimize_interesting failures with "cannot unmarshal empty string"

### ISSUE THREAD

**Issue by bcmills** [golang/go#50606]
```
go test proxy running at GOPROXY=http://127.0.0.1:54100/mod
--- FAIL: TestScript (0.01s)
    --- FAIL: TestScript/test_fuzz_minimize_interesting (3.78s)
        script_test.go:257: 
            # Test that when an interesting value is discovered (one that expands coverage),
            # the fuzzing engine minimizes it before writing it to the cache.
            #
            # The program below starts with a seed value of length 100, but more coverage
            # will be found for any value other than the seed. We should end with a value
            # in the cache of length 1 (the minimizer currently does not produce empty
            # strings). check_cache.go confirms that.
            #
            # We would like to verify that ALL values in the cache were minimized to a
            # length of 1, but this isn't always possible when new coverage is found in
            # functions called by testing or internal/fuzz in the background. (3.574s)
            > go test -c -fuzz=.  # Build using shared build cache for speed.
            > env GOCACHE=$WORK/gocache
            > exec ./fuzz.test$GOEXE -test.fuzzcachedir=$GOCACHE/fuzz -test.fuzz=FuzzMinCache -test.fuzztime=1000x
            [stdout]
            --- FAIL: FuzzMinCache (0.60s)
                cannot unmarshal empty string
            FAIL
            [stderr]
            fuzz: elapsed: 0s, gathering baseline coverage: 0/1 completed
            fuzz: elapsed: 0s, gathering baseline coverage: 1/1 completed, now fuzzing with 16 workers
            fuzz: elapsed: 1s, execs: 551 (1226/sec), new interesting: 4 (total: 4)
            [exit status 1]
            FAIL: testdata\script\test_fuzz_minimize_interesting.txt:18: unexpected command failure
            
FAIL
FAIL	cmd/go	277.000s
```

`greplogs --dashboard -md -l -e '(?ms)FAIL: TestScript/test_fuzz_minimize_interesting.*cannot unmarshal empty string'`

[2022-01-13T20:43:56-6891d07/windows-amd64-longtest](https://build.golang.org/log/7206839242eb404a042aab7ff5270804a034b980)
[2021-12-02T22:53:18-fd4b391/windows-arm64-10](https://build.golang.org/log/ce6b7697b4006d6c2cb2ecd3c37af1ce42bd52a9)
[2021-12-01T10:19:34-0e1d553/windows-arm64-10](https://build.golang.org/log/f985c9b7290b372707a4f2c3f2bb3e4b6e278e77)
[2021-10-18T20:39:22-267abbe/windows-amd64-longtest](https://build.golang.org/log/b5e821bc571fbcb208e626adc15cca8cd0a9a036)
[2021-09-30T18:10:18-205640e/windows-arm64-10](https://build.golang.org/log/d33f1e2038d778e9fdafdaf86e30e63fb7a831d5)
[2021-09-29T16:45:42-2fad7db/windows-amd64-race](https://build.golang.org/log/7ba25a53f5a72e35f2441a2ba57bf8ff096144c4)

(attn @katiehockman @rolandshoemaker)

**Comment by toothrot** [comment]
Pinging as this issue is a release blocker for Go 1.18. Any updates?

**Comment by katiehockman** [comment]
Thanks, I'll take a look at it this week.

**Comment by katiehockman** [comment]
Just a side note: we thought we fixed this in https://github.com/golang/go/issues/48721, but apparently not. It's also still only affecting Windows it seems.
