### ISSUE TITLE
x/tools/gopls: support type parameters for function literal snippet completions

### ISSUE THREAD

**Issue by marwan-at-work** [golang/go#50623]
Given the following code:

```golang
type Tree[T any] struct{}

func (tree Tree[T]) Do(f func(s T)) {}

func _() {
  var t Tree[string]
  t.Do(fun) // trigger completion
}
```

The current completion that gopls gives for the `func(...) {}` snippet option is: `func(s T) {}`, but that is incorrect as T is not really valid. The correct solution would be whatever type was instantiated at compile time, so the completion in the example above should be `func(s string) {}`

**Comment by rkfg** [comment]
Does this change above also fix completion for generic type method receivers or is it a different issue? Currently it suggests the structure name but without type parameters so I have to add them manually every time. Same with calling a function with type parameters, placeholders for them would be nice (they can't be guessed of course).

**Comment by findleyr** [comment]
Thanks for the issue and CL, Marwan! Left some comments, and @pjweinb will be looking at completion issues.

@rkfg no I don't think this will fix the problem you describe. I opened https://github.com/golang/go/issues/50684 to track that issue.
