### ISSUE TITLE
debug/elf: `elf.Symbols()` never populates `Version` or `Library` struct fields. 

### ISSUE THREAD

**Issue by ok-john** [golang/go#50625]
### What version of Go are you using (`go version`)?

`go1.18-3b5eec9`

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

`linux/amd64`

### What did you do?

Viewed the `elf.Symbol`'s in both [cgo](https://git.sr.ht/~johns/symbols/tree/main/item/output/test-cgo.elf.symbols) & [go](https://git.sr.ht/~johns/symbols/tree/main/item/output/test.elf.symbols) elf binaries. See [here](https://git.sr.ht/~johns/symbols/tree/main/item/main.go), the binaries I looked at are included in that repo.

Used `ldd` to confirm the binaries in question are static and dynamically linked, respectively.

Used `readelf -{s, S}` to confirm the cgo binary contains no dynamic symbol table unlike the regular go binary.

### What did you expect to see?

Well I didn't really expect to see anything, just noticed this in passing & thought it was strange the fields never got populated. Peeking at the `Symbol` struct I noticed [this comment](https://cs.opensource.google/go/go/+/refs/tags/go1.17.6:src/debug/elf/file.go;l=175-178;drc=refs%2Ftags%2Fgo1.17.6) which suggests the `Version` & `Library` fields would be populated in the `.dynsym` table but not in the `.symtab` table.

Poking around a bit more, looks like there is no attempt to populate either field. ([ref](https://cs.opensource.google/go/go/+/master:src/debug/elf/file.go;l=566-571;drc=master))

### What did you see instead?

Neither `Version` or `Library` populated for either symbol table/binary.

**Comment by ianlancetaylor** [comment]
The `Version` and `Library` fields are set by the `DynamicSymbols` method: https://go.dev/src/debug/elf/file.go?#L1273, but only if the file has version information.  On a Linux system using glibc you will see version information if you use the `DynamicSymbols` method on libc itself.

In general, for questions about Go please use a forum rather than the issue tracker.  Thanks.  See https://golang.org/wiki/Questions.
