### ISSUE TITLE
doc: fuzzing tutorial: func main() invalid after adding error return

### ISSUE THREAD

**Issue by helloPiers** [golang/go#50628]
https://go.dev/doc/tutorial/fuzz

After changing the Reverse function to return an error, the func main() no longer compiles as it doesn't expect two return values.

**Comment by eliben** [comment]
This issue also exists in the "Completed code" at the end of the tutorial:

```
— main.go —

package main

import "fmt"

func main() {
    input := "The quick brown fox jumped over the lazy dog"
    rev := Reverse(input)
    doubleRev := Reverse(rev)
    fmt.Printf("original: %q\n", input)
    fmt.Printf("reversed: %q\n", rev)
    fmt.Printf("reversed again: %q\n", doubleRev)
}

```

This will not compile since `Reverse` now returns two values.
