### ISSUE TITLE
debug/elf: `elf.Symbols()` incorrectly returns `ErrNoSymbols` for valid elf binaries.   

### ISSUE THREAD

**Issue by ok-john** [golang/go#50626]
### What version of Go are you using (`go version`)?

`go1.18-3b5eec9`

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

`linux/amd64`

### What did you do?

Attempted to view the symbol table of both static & dynamically linked binaries compiled with gcc.

For example, `readelf -{s, S} /bin/ls` (or even `readelf -{s, S} /bin/*` on most distributions of linux) shows the symbol table of each elf binary without error. 

Attempting to view the symbol table of every binary under `/bin/*` on a basic linux distro by using `elf.Symbols()` failed in all cases. 

See example script [here](https://git.sr.ht/~johns/symbols/tree/main/item/bin.sh).

### What did you expect to see?

A valid return of `[]elf.Symbol` from `elf.Symbols()` for at least one elf binary. 

### What did you see instead?

`elf.Symbols()` returns `ErrNoSymbols` ([ref](https://cs.opensource.google/go/go/+/master:src/debug/elf/file.go;l=536-539;drc=master))

**Comment by ianlancetaylor** [comment]
In many Linux distros programs like /bin/ls have no `SHT_SYMTAB` section, so the debug/elf `Symbols` method on such a file will return `ErrNoSymbols`.  The `readelf -s` output that you mention is the dynamic symbols, the `SHT_DYNSYM` section (`readelf -s` displays both the normal symbols and the dynamic symbols).  With debug/elf you can fetch that information using the `DynamicSymbols` method.

**Comment by ok-john** [comment]
> In many Linux distros programs like /bin/ls have no `SHT_SYMTAB` section, so the debug/elf `Symbols` method on such a file will return `ErrNoSymbols`.  The `readelf -s` output that you mention is the dynamic symbols, the `SHT_DYNSYM` section (`readelf -s` displays both the normal symbols and the dynamic symbols).  With debug/elf you can fetch that information using the `DynamicSymbols` method.

Thanks for clarifying.
