### ISSUE TITLE
x/pkgsite: module fix request 

### ISSUE THREAD

**Issue by seancfoley** [golang/go#50636]
Please see https://github.com/golang/go/issues/50631
 
### What is the path of the package?

I am not trying to remove a package, I am trying to remove a module.  I want the package to remain but the module to go away.

The issue is described  here, but that ticket was closed with nothing done:
https://github.com/golang/go/issues/50631

Please see this package: https://pkg.go.dev/github.com/seancfoley/ipaddress-go/ipaddr

I do not want to remove that package.
I want to remove that module.
I want the package to remain part of the module https://pkg.go.dev/github.com/seancfoley/ipaddress-go
 
### Are you the owner of this package?

yes
 
### What is the reason that you could not retract this package instead?

There are no versions to retract.  Your instructions to retract, they involve retracting versions.  There are no versions.  According to all the documentation, you can only retract published versions.  I did not publish any versions of https://pkg.go.dev/github.com/seancfoley/ipaddress-go/ipaddr.  I attempted to publish version 1.0.0, but it did not work, because it seems I could not use that version number with the go.mod not at the root of the repo.  The go modules documentation is not clear on this.  I tried to make it work, but it would not, it seems you can use only special version numbers if you do not put the go.mod at the root of the repo.  So that version was never published.  So I had to move the module to https://pkg.go.dev/github.com/seancfoley/ipaddress-go in order to publish versions with normal semantic versioning.

So my module is now at https://pkg.go.dev/github.com/seancfoley/ipaddress-go

That seemed to work ok.  I have only published versions of https://pkg.go.dev/github.com/seancfoley/ipaddress-go

From https://pkg.go.dev/github.com/seancfoley/ipaddress-go, if I click on the "ipaddr" package it goes to https://pkg.go.dev/github.com/seancfoley/ipaddress-go@v1.0.2/ipaddr

On that page it has a red button "Go to latest" which takes me to my failed attempt to publish the package with the go.mod in a subdirectory. There are no versions in that failed attempt, only pseudo-versions, which of course I have not published, those are just commits. Nor are the dates of those pseudo-versions more recent. So they are clearly not the latest in any way, shape or form.  I want that red button "go to latest" to disappear.  And I want that package to not be a module, it needs to be a sub-package of the module github.com/seancfoley/ipaddress-go.

I opened a ticket to fix this: https://github.com/golang/go/issues/50631

And the ticket was closed with instructions to retract.  But there are no version to retract, I did not publish any versions for github.com/seancfoley/ipaddress-go/ipaddr. 

So I am opening this ticket as a request to fix this.  I am not entirely sure what needs to be done.  But I do want that red button "Go to latest" to disappear, and I do want the subpackage to be only a package and not a module.

**Comment by seankhliao** [comment]
We can't remove submodules without also removing the package.
A pseudoversion is still a version, crafted to order correctly in the presence of other semver compliant version numbers.
`retract` is the only way to fix this, it works with pseudoversions as well (they're all just version numbers).

**Comment by seancfoley** [comment]
@seankhliao please specify how this would work.

In what go.mod file would the retraction exist?  In the one for which the retracted versions do not exist, github.com/seancfoley/ipaddress-go?  I cannot retract versions that do not exist.

The other go.mod file, in github.com/seancfoley/ipaddress-go/ipaddr, I do not want to exist any longer.  So you are saying that to eliminate this module, I need to do another release of this same module?  That makes no sense.  I cannot retract release X in release X.  I also cannot do a release in order to eliminate all the releases.

**Comment by seankhliao** [comment]
you can retract the release it was released in, it also doesn't have to be on the main branch if you tag it

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by seancfoley** [comment]
"you can retract the release it was released in"

What is that supposed to mean?  That makes no sense.

**Comment by seancfoley** [comment]
You're calling this a discussion?
