### ISSUE TITLE
cmd/compile: declared but not used if use type switch on type parameter value

### ISSUE THREAD

**Issue by XiaodongLoong** [golang/go#50639]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-3b5eec9370 Fri Jan 14 21:54:39 2022 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
```
package p

func f[T any](a T) {
	x := 1
	z := 3
	switch a.(type) {
	case int:
		println(x)
	}
	println(z)
}

$ bin/go tool compile t2.go 
t2.go:4:2: x declared but not used
t2.go:6:9: cannot use type switch on type parameter value a (variable of type T constrained by any)
```

### What did you expect to see?
Don't output "x declared but not used"

### What did you see instead?
It should only output as following :
`t2.go:6:9: cannot use type switch on type parameter value a (variable of type T constrained by any)`

**Comment by ianlancetaylor** [comment]
Thanks.  Closing as dup of #50493.
