### ISSUE TITLE
net/http: 404 with http.FileServer with absolute path

### ISSUE THREAD

**Issue by wxolp** [golang/go#50638]
### What version of Go are you using (`go version`)?

~~~
go version go1.17 windows/amd64
~~~

### What did you do?

I have a file `C:\hello\index.go`:

~~~go
package main
import "net/http"

func main() {
   http.Handle("/assets", http.FileServer(http.Dir("assets")))
   println("ListenAndServe")
   http.ListenAndServe(":9000", nil)
}
~~~

I enter `go run index.go`, then make this request:

~~~
PS C:\> curl localhost:9000/assets/kitten.jpg
404 page not found
~~~

I know the path is valid:

~~~
PS C:\> curl -I file:/C:/hello/assets/kitten.jpg
Content-Length: 3000898
Accept-ranges: bytes
Last-Modified: Sun, 16 Jan 2022 01:14:58 GMT
~~~

I also tried these other lines:

~~~go
http.Handle("/assets", http.FileServer(http.Dir(`C:\hello\assets`)))
http.Handle("/assets/", http.FileServer(http.Dir("assets")))
http.Handle("/assets/", http.FileServer(http.Dir(`C:\hello\assets`)))
~~~

but I get 404 every time. What am I doing wrong?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by wxolp** [comment]
This is a bug...

**Comment by wxolp** [comment]
This command:

~~~go
http.Handle("/assets", http.FileServer(http.Dir("assets")))
~~~

Sets the filesystem root to `assets`, then the request is added on top of that.
So if you make a request like this:

~~~
/assets/kitten.jpg
~~~

Then the server will look for a path like this:

~~~
assets/assets/kitten.jpg
~~~

I have seen some people suggest using `StripPrefix`, but this seems to do the
job as well:

~~~
http.Handle("/assets/", http.FileServer(http.Dir(".")))
~~~

**Comment by seankhliao** [comment]
the trailing slash in the handler path is important

**Comment by wxolp** [comment]
When you burn a bridge, you dont go back and try to rebuild it. You own the fact that you burn bridges.
