### ISSUE TITLE
x/pkgsite: "go to latest" button points to something that is not the latest

### ISSUE THREAD

**Issue by seancfoley** [golang/go#50631]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/seancfoley/ipaddress-go@v1.0.2/ipaddr

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Screenshot

![image](https://user-images.githubusercontent.com/19226957/149632777-e2afa87a-48c6-4db8-b331-609bb2361531.png)

### What did you do?

I have attempted to publish my module.  The go modules documentation is not clear that you cannot use normal versioning numbering (eg v1.0.0) if you do not put the go.mod file at the root if the repository.  So initially I had the go.mod in the main package ipaddr which is a directory in the repository.  After a lot of trial and error, trying to figure out why the go tools would not work as I expected, I've now placed it at the root of the repo.

So my module is at https://pkg.go.dev/github.com/seancfoley/ipaddress-go

If I click on the "ipaddr" package is goes to https://pkg.go.dev/github.com/seancfoley/ipaddress-go@v1.0.2/ipaddr

On that page it has a red button "Go to latest" which takes me to my failed attempt to publish the package with the go.mod in a subdirectory.  There are no versions in that failed attempt.  Nor are the dates more recent.  So it is clearly not the latest in any way, shape or form.

### What did you expect to see?

I expect there to be no red button saying "Go to latest" taking you to a page which is not the latest.  

### What did you see instead?

I see a red button leading people to the wrong location.  It takes you to a version of the package which is clearly not the latest, neither by date, nor by version.  So the button should not be there, it is misleading.

**Comment by seankhliao** [comment]
`go` uses the longest module path to determine the containing module.
You'll need to use `retract` to fix this (both for pkg.go.dev and for the `go` tool to resolve properly).

**Comment by seancfoley** [comment]
The information I've seen on retract is for retracting versions, not pseudo-versions. Can you provide more info or a link?
