### ISSUE TITLE
strings: typo in comment

### ISSUE THREAD

**Issue by looshch** [golang/go#50634]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.17.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hlushch/Library/Caches/go-build"
GOENV="/Users/hlushch/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/hlushch/Projects/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/hlushch/Projects/go/"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.5/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nz/cqlmbdfs23schf6ndmr7gz440000gn/T/go-build2546855830=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Went to L20C51 in src/strings/builder.go

### What did you expect to see?

No extra whitespace

### What did you see instead?

Unneeded whitespace

**Comment by ianlancetaylor** [comment]
Thanks.  It's not necessary to open an issue for a typo if you are going to send a patch anyhow.  Just send the patch.  Thanks.

**Comment by looshch** [comment]
Got this, thank you.
