### ISSUE TITLE
x/pkgsite: package removal request for github.com/solomon-bush/log-harvestor-go

### ISSUE THREAD

**Issue by solomon-bush** [golang/go#50647]
### What is the path of the package that you would like to have removed?

github.com/solomon-bush/log-harvestor-go

### Are you the owner of this package?

Yes

### What is the reason that you could not retract this package instead?

I moved this repo to my organizations repo 'github.com/logharvestor'. Then I updated my go.mod file by changing the module path to the new repo. When I published the new version, I went to pkg.go.dev and realized that it was published twice. I tried everything in your documentation to remove the old package but cannot.

**Comment by jamalc** [comment]
Done.
