### ISSUE TITLE
why call runtime_doSpin after  setting awoke =true

### ISSUE THREAD

**Issue by chenniannian90** [golang/go#50655]
https://github.com/golang/go/blob/897b3da2e079b9b940b309747305a5379fffa6ec/src/sync/mutex.go#L121

According to the review, spinning is to set mutewoken. 
But why it may call runtime_doSpin after setting awoke =true？

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
