### ISSUE TITLE
x/pkgsite: package removal request for git.sr.ht/~koukas/go-managesieve

### ISSUE THREAD

**Issue by koukas** [golang/go#50668]
### What is the path of the package that you would like to have removed?

git.sr.ht/~koukas/go-managesieve

 
 
 
### Are you the owner of this package?

Yes

 
### What is the reason that you could not retract this package instead?

The project will be deleted entirely so no version should be available.

**Comment by bcmills** [comment]
> What is the reason that you could not retract this package instead?

Before deleting the project, you can publish a final release version that `retract`s itself and all prior releases. If you fetch that final release itself through `proxy.golang.org`, `pkg.go.dev` should pick up the final retraction.

**Comment by koukas** [comment]
Done.

**Comment by koukas** [comment]
All versions are retracted now. Thanks for your time!

**Comment by bcmills** [comment]
Thanks for following up! Do you still need the package removed outright from `pkg.go.dev`, or does the retraction notice suffice?

(Note that removing a package from `pkg.go.dev` does not necessarily remove it from `proxy.golang.org`; see the FAQ at https://proxy.golang.org/.)

**Comment by jamalc** [comment]
Done.
