### ISSUE TITLE
cmd/compile:   OSX Builds -ldflags processing looks to not include dash character

### ISSUE THREAD

**Issue by karlmutch** [golang/go#50662]
### What version of Go are you using (`go version`)?

<pre>
go version go1.18beta1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

N/A (1.18 Beta1)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/karlmutch/Library/Caches/go-build"
GOENV="/Users/karlmutch/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/karlmutch/projects/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/karlmutch/projects"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/karlmutch/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/karlmutch/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18beta1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/karlmutch/projects/src/github.com/xxxxxx/xxx-xxxx/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hv/zjrtcfqs64g1bhyh8wvx919r0000gp/T/go-build3854253269=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Perform a static build using the following

<pre>
go build -ldflags="-extldflags=static" -tags="osusergo netgo" ./cmd/kvserver</pre>

### What did you expect to see?

<pre>#github.com/shirou/gopsutil/disk
iostat_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:132:1: note: 'IOMasterPort' has been explicitly marked deprecated here</pre>

### What did you see instead?

<pre> github.com/shirou/gopsutil/disk
iostat_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:132:1: note: 'IOMasterPort' has been explicitly marked deprecated here
# github.com/fetchrobotics/sage-kernel/cmd/kvserver
/Users/karlmutch/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
clang: error: no such file or directory: 'static'; did you mean '-static'?</pre>

**Comment by ianlancetaylor** [comment]
The value that you pass as an argument to `-extldflags` is passed directly to the external linker.  You wrote `-extldflags=static` so the external linker is invoked with `static`.  That doesn't work.

You probably want `-extldflags=-static`.

**Comment by karlmutch** [comment]
I had discounted that because of ...
```
go build -ldflags="-extldflags=-static" -tags="osusergo netgo" ./cmd/kvserver
...
# github.com/fetchrobotics/sage-kernel/cmd/kvserver
/Users/karlmutch/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
