### ISSUE TITLE
cmd/compile: bad order of evaluation for multi-value f(g()) calls

### ISSUE THREAD

**Issue by mdempsky** [golang/go#50672]
This program panics when compiled with cmd/compile, but should succeed:

```
package main

func main() {
	ok := false

	f := func() func(int, int) {
		ok = true
		return func(int, int) {}
	}
	g := func() (int, int) {
		if !ok {
			panic("FAIL")
		}
		return 0, 0
	}

	f()(g())
}
```

This is because we rewrite `f()(g())` into `t1, t2 := g(); f()(t1, t2)` during type checking.

gccgo compiles it correctly.

**Comment by cuonglm** [comment]
It seems to me that we should evaluate `f()` before '`t1, t2 = g()`.

**Comment by mdempsky** [comment]
@cuonglm Yeah, rewriting as `t0 := f(); t1, t2 := g(); t0(t1, t2)` instead seems like a reasonable quick fix to me. I think direct function calls and method calls are probably the most common case though, so we should make sure those are still handled efficiently.

Longer term, I think we should probably incorporate order.go directly into unified IR.

**Comment by bcmills** [comment]
Is the order of evaluation actually specified here, or is this another case like #27804?

https://go.dev/ref/spec#Order_of_evaluation says:
> [W]hen evaluating the operands of an expression, assignment, or return statement, all function calls, method calls, and communication operations are evaluated in lexical left-to-right order.

I guess in this case `f()` is considered an “operand” of the call-expression?

**Comment by mdempsky** [comment]
Yeah, `f()` is an operand. But also it's simply to the left of the `g()` call, so it needs to be evaluated first per the "evaluated in lexical left-to-right order" rule.

/cc @griesemer @ianlancetaylor in case they interpret the spec differently here

**Comment by ianlancetaylor** [comment]
Yes, I think the call to `f` has to happen before the call to `g` in this test case.

I think this differs from #27804 which hinges on when we evaluate a variable in a tuple assignment.

The gc compiler got this right up to version 1.12.  In version 1.13 it started failing.  Possibly due to CL 114797; CC @josharian .

**Comment by mdempsky** [comment]
I suspect CL 166983 (c0cfe9687f4f1b862328c85b3a160bc86d200d32) is a more likely culprit.

**Comment by cuonglm** [comment]
> @cuonglm Yeah, rewriting as `t0 := f(); t1, t2 := g(); t0(t1, t2)` instead seems like a reasonable quick fix to me. I think direct function calls and method calls are probably the most common case though, so we should make sure those are still handled efficiently.
> 
> Longer term, I think we should probably incorporate order.go directly into unified IR.

Note that the rewriting of `f(g())` happens during old typecheck phase, not during order phase. Though, it's also reasonable to me for incorporating order.go directly into unified IR.
