### ISSUE TITLE
x/tools/gopls: include receiver type parameters when completing receivers

### ISSUE THREAD

**Issue by findleyr** [golang/go#50684]
Reported in https://github.com/golang/go/issues/50623#issuecomment-1013718996: when completing generic receivers, we omit receiver type parameters. It would be helpful if we could include them, with placeholders, rather than force the user to type them every time.

**Comment by pjweinb** [comment]
"A parameterized type may also have methods associated with it. In this case, the method receivers must declare the same number of type parameters as present in the parameterized type definition." from the draft language definition confirms that this is the right choice.

**Comment by rkfg** [comment]
I'm not sure if I do something wrong but this doesn't completely fix the bug. I'm testing it in VS Code. Yes, it now says `SyncMap[K,V]` in the popup but when I confirm this completion I only get `SyncMap` without type parameters:
![record](https://user-images.githubusercontent.com/184066/151980553-8953fe3c-6dd9-4914-96e3-59955a61f4c5.gif)

**Comment by pjweinb** [comment]
I misunderstood what vscode wants. The fix itself is easy, but it's bad
that our tests didn't uncover the problem.
