### ISSUE TITLE
General function call

### ISSUE THREAD

**Issue by blacksun1977** [golang/go#50712]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Darwin xxx.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zqh/Library/Caches/go-build"
GOENV="/Users/zqh/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zqh/bin/gopath/pkg/mod"
GONOPROXY="*.gitee.com,tygit.touch4.me,tygit.tuyoo.com"
GONOSUMDB="*.gitee.com,tygit.touch4.me,tygit.tuyoo.com"
GOOS="darwin"
GOPATH="/Users/zqh/bin/gopath"
GOPRIVATE="*.gitee.com,tygit.touch4.me,tygit.tuyoo.com"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Users/zqh/bin/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/Users/zqh/bin/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/zqh/ddz/server/endgame-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/14/stmh8xnx2dj0xfhnch598jqm0000gn/T/go-build3282234532=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
I  just write a simple Iter factory program, and i find the code return style may has problem
the correct code style is：

func newSimpleIter(data []string) Iter {
&nbsp;&nbsp;it := makeSimpleIter(data)
&nbsp;&nbsp;if it == nil {
&nbsp;&nbsp;&nbsp;&nbsp;return nil
&nbsp;&nbsp;}
&nbsp;&nbsp;return it
}

the bad code style is:

func newSimpleIter(data []string) Iter {
&nbsp;&nbsp;return makeSimpleIter(data)
}

logically, the two style are consistent，but the bad one cause panic.

### What did you expect to see?
I want konwn, why this happen?

[test1.txt](https://github.com/golang/go/files/7904839/test1.txt)
[test2.txt](https://github.com/golang/go/files/7904840/test2.txt)

test1.txt is the bad code, text2.txt is the correct code
change the "txt" to "go"  and run "go run test1.go", 
you can see its panic.

**Comment by WangLeonard** [comment]
Hi, I think It's a problem  about `nil` and `type(nil)`  
In test1, `it` in main func is `*main.simpleIter(nil)`, and in `Factory` it will return `it`, not `&emptyIter{}`  

I guess  
```go
func newSimpleIter(data []string) Iter {
	return makeSimpleIter(data)
}
```  
is equal to
```go
func newSimpleIter(data []string) Iter {
	var res Iter
	res = makeSimpleIter(data)
	return res
}
```

**Comment by seankhliao** [comment]
see above.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
