### ISSUE TITLE
cmd/compile: handle alias types in recursive types more consistently

### ISSUE THREAD

**Issue by griesemer** [golang/go#50729]
The following code
```Go
package p

var x T[B]

type T[_ any] struct{}
type A T[B /* ERROR invalid use of type alias */ ]
type B = T[A]
```
reports an error when we use `B` in a recursive type definition due to the way type aliases are handled inside the type checker. In this (and possibly many other similar) cases, the error can be avoided by restructuring the code slightly. This version compiles without error (declaration of `x` moved past the type declarations):
```Go
package p

type T[_ any] struct{}
type A T[B]
type B = T[A]

var x T[B]
```
The compiler should be able to avoid this error on its own.

Root cause: Currently, the type checker doesn't have a "forwarding mechanism" for type aliases that are being "used" before their respective type is fully known. To solve this problem in general, a forwarding mechanism/type needs to be introduced. This is only an issue with some recursive type definitions involving type aliases.

cc: @findleyr

**Comment by griesemer** [comment]
See #50259 and #50276.

**Comment by griesemer** [comment]
This error doesn't appear anymore due to some of the (partial) fixes done with the CLs above. There's still more to do to handle aliases correctly in all cases but that's separate from this issue. We should add a test to cover this specific case and then close this issue.

**Comment by AndrewHarrisSPU** [comment]
Was able to reach this in 1.19b2: https://gotipplay.golang.org/p/mpONhtxQI4a

(really excellent to have an issue number in the compiler error!)

**Comment by ajwerner** [comment]
Can we re-open this? It can still happen both in tip and in 1.19.4.

**Comment by griesemer** [comment]
Re-opened per previous comments and example: https://gotipplay.golang.org/p/mpONhtxQI4a

**Comment by Aaron3** [comment]
While this is mostly solved there are still an edge case.  Here's a full example: https://go.dev/play/p/vW_lpMaIH2h

In this example, Model is an interface where we don't care if we are dealing with a concrete struct of PetStore{}, Cat{}, Dog{}, Owner{} etc yet. All of which implement Model.

So the fix applied fixed the following two use cases:

1. accepting a concrete instance of the generic interface works. 

```
type Entity = TypedEntity[Model, []Model]

type TypedEntity[T Model, TS ~[]T] interface {
	RelateEntity(Entity)
}
```

2. And you can also accept an interface that uses the instance of the generic interface.

```
type Entity = TypedEntity[Model, []Model]

type EntityPlugin interface {
	RegisterEntity(ctx context.Context, c Entity) EntityPlugin
}
type TypedEntity[T Model, TS ~[]T] interface {
	AddPlugin(ctx context.Context, v ...EntityPlugin) TypedEntity[T, TS]
}
```

However, you can not do both together or you get the same vet error pointing to this issue again.

```
type TypedEntity[T Model, TS ~[]T] interface {
	AddPlugin(ctx context.Context, v ...EntityPlugin) TypedEntity[T, TS]
	RelateEntity(Entity)
}
```

**Comment by timothy-king** [comment]
For some reason I don't totally understand, I got a notification from "Aaron" from GH on this issue yesterday with the link https://github.com/golang/go/issues/50729#issuecomment-2454311351, but I do not see it here. Here is the message verbatim:
> While this is mostly solved there are still an edge case. Here's a full example: https://go.dev/play/p/vW_lpMaIH2h
> 
> In this example, Model is an interface where we don't care if we are dealing with a concrete struct of PetStore{}, Cat{}, Dog{}, Owner{} etc yet. All of which implement Model.
>
>So the fix applied fixed the following two use cases:
>
>accepting a concrete instance of the generic interface works.
>type Entity = TypedEntity[Model, []Model]
>
>type TypedEntity[T Model, TS ~[]T] interface {
>	RelateEntity(Entity)
>}
>And you can also accept an interface that uses the instance of the generic interface.
>type Entity = TypedEntity[Model, []Model]
>
>type EntityPlugin interface {
>	RegisterEntity(ctx context.Context, c Entity) EntityPlugin
>}
>type TypedEntity[T Model, TS ~[]T] interface {
>	AddPlugin(ctx context.Context, v ...EntityPlugin) TypedEntity[T, TS]
>}
>However, you can not do both together or you get the same vet error pointing to this issue again.
>
>type TypedEntity[T Model, TS ~[]T] interface {
>	AddPlugin(ctx context.Context, v ...EntityPlugin) TypedEntity[T, TS]
>	RelateEntity(Entity)
>}

**Comment by timothy-king** [comment]
Minimized reproducer of this example https://go.dev/play/p/_XljMNVUwEd :
```
type A = E[any]

type _ interface {
	G(c A)
}

type E[T any] interface {
	L(A)
}
```

**Comment by ianlancetaylor** [comment]
> For some reason I don't totally understand, I got a notification from "Aaron" from GH on this issue yesterday with the link https://github.com/golang/go/issues/50729#issuecomment-2454311351, but I do not see it here. 

This normally means that the person added a comment and then deleted it.

**Comment by timothy-king** [comment]
@ianlancetaylor Thanks. I've opened #70230 to focus on just on this example. Re-closing.
