### ISSUE TITLE
runtime/metrics: time histogram sub-bucket boundaries are wrong

### ISSUE THREAD

**Issue by mknyszek** [golang/go#50732]
The reported buckets for time-related histograms in the `runtime/metrics` package have their linear sub-buckets boundaries' distances between each other off by a factor of two, because of an off-by-one error in the function that generates them. As a result, the reported bucketing scheme is somewhat nonsensical.

**Comment by mknyszek** [comment]
@gopherbot Please open backport issues for Go 1.16 and Go 1.17.

This issues is not really possible to workaround because downstream users are supposed to take the reported bucketing for `runtime/metrics` histograms at face value, and they're currently just wrong. The fix is also very small, and very safe.

**Comment by dmitshur** [comment]
@mknyszek I understand [CL 380094](https://go.dev/cl/380094) was submitted now intentionally, so we can update the milestone of this issue to Go1.18 to reflect that.

**Comment by mknyszek** [comment]
Yes! Thank you.
