### ISSUE TITLE
affected/package: json

### ISSUE THREAD

**Issue by ghdiska** [golang/go#50735]
Failed to unmarshal json with double - in text 

if i try to unmarshal the following json i got an error from json.Unmarshal, my code works fine if there arent double - in value string

it works fine with  "AlarmName": "Lag on Kafka consumer group \"test.test-test\"" 

if doesn't works with  "AlarmName": "Lag on Kafka consumer group \"test.test-test-test\" for topic \"test\""

`{  "AlarmName": "Lag on Kafka consumer group \"test.test-test-test\" for topic \"test\"",    "AlarmDescription": "Usage of CPU by eks autoscaling group",    "AWSAccountId": "746534058873",    "NewStateValue": "ALARM",    "NewStateReason": "Threshold Crossed: 2 datapoints [7.0 (24/03/21 14:10:00), 7.8 (24/03/21 14:05:00)] were greater than or equal to the threshold (1.0).",    "StateChangeTime": "2021-03-24T14:11:57.306+0000",    "Region": "EU (Milan)",    "AlarmArn": "arn:aws:cloudwatch:eu-south-1:746534058873:alarm:eks-asg-cpu-utilization-eks-6ebb16e6-ca97-467b-52b1-62c05eb16cdd",    "OldStateValue": "INSUFFICIENT_DATA",    "Trigger": {        "MetricName": "CPUUtilization",        "Namespace": "AWS/EC2",        "StatisticType": "Statistic",        "Statistic": "AVERAGE",        "Unit": null,        "Dimensions": [{                "value": "eks-6ebb16e6-ca97-467b-52b1-62c05eb16cdd",                "name": "AutoScalingGroupName"            }        ],        "Period": 60,        "EvaluationPeriods": 5,        "ComparisonOperator": "GreaterThanOrEqualToThreshold",        "Threshold": 1.0,        "TreatMissingData": "- TreatMissingData:                    missing",        "EvaluateLowSampleCountPercentile": ""    }}` 

### What version of Go are you using (`go version`)?

go version go1.17 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOCACHE="/home/diska/.cache/go-build"
GOENV="/home/diska/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/diska/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/diska/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2127977226=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

**Comment by seankhliao** [comment]
It works: https://go.dev/play/p/tsxODDjRDNn

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
