### ISSUE TITLE
Code simplification

### ISSUE THREAD

**Issue by vector233** [golang/go#50736]
https://github.com/golang/go/blob/d15481b8c7f5f73a8b987a0c1deea04659ed0bb0/src/net/textproto/header.go#L13-L16
Is it better to change this code to the following format？other functions are written in this way
``` go
func (h MIMEHeader) Add(key, value string) {
	h[CanonicalMIMEHeaderKey(key)] = append(h[key], value)
}
```

**Comment by davecheney** [comment]
Your suggestion is not functionally the same as `CanonicalMIMEHeaderKey(key) != key` for some keys.

**Comment by vector233** [comment]
I

> Your suggestion is not functionally the same as `CanonicalMIMEHeaderKey(key) != key` for some keys.

sorry. no attention
