### ISSUE TITLE
reflect: Value.NumMethod and Type.NumMethod doesn't seem to agree on exported methods

### ISSUE THREAD

**Issue by mvdan** [golang/go#50746]
On e7d5857a5a82551b8a70b6174ec73422442250ce, I see:

```
// NumMethod returns the number of exported methods in the value's method set.
func (v Value) NumMethod() int {
    if v.typ == nil {
        panic(&ValueError{"reflect.Value.NumMethod", Invalid})
    }
    if v.flag&flagMethod != 0 {
        return 0
    }
    return v.typ.NumMethod()
}
```

Note that `Value.NumMethod` is documented to only return the number of *exported* methods. It calls `Type.NumMethod`, which is documented as:

```
// NumMethod returns the number of methods accessible using Method.
//
// Note that NumMethod counts unexported methods only for interface types.
```

Am I misreading the docs, or do they seem to disagree when it comes to interface types?

cc @dsnet
cc @ianlancetaylor @mdempsky given some past changes regarding `NumMethods` and exported methods

**Comment by cuonglm** [comment]
FYI, https://go-review.googlesource.com/c/go/+/264357

**Comment by dsnet** [comment]
Fixed in https://go-review.googlesource.com/c/go/+/396075
