### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by manjeettahkur** [golang/go#50742]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18beta1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\manjeet.s.v\AppData\Local\go-build
set GOENV=C:\Users\manjeet.s.v\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\manjeet.s.v\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\manjeet.s.v\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\manjeet.s.v\sdk\go1.18beta1
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\manjeet.s.v\sdk\go1.18beta1\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18beta1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\manjeet.s.v\go\src\github.com\manjeettahkur\data-and-algo\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\MANJEE~1.VDA\AppData\Local\Temp\go-build1391629200=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
package main

```
import (
	"fmt"
	"unsafe"
)

func main() {
	s1 := "foo"
	s2 := "foobar"

	fmt.Printf("s1 size: %T, %d\n", s1, unsafe.Sizeof(s1))
	fmt.Printf("s2 size: %T, %d\n", s2, unsafe.Sizeof(s2))
	fmt.Printf("s1 len: %T, %d\n", s1, len(s1))
	fmt.Printf("s2 len: %T, %d\n", s2, len(s2))
}
```

### What did you expect to see?
s1 size: string, 16
s2 size: string, 16
s1 len: string, 3
s2 len: string, 6

### What did you see instead?
Build Error: go build -o C:\Users\MANJEE~1.VDA\AppData\Local\Temp\__debug_bin3221234365.exe -gcflags all=-N -l .
# sync
..\..\..\..\..\sdk\go1.18beta1\src\sync\cond.go:64:26: undefined: qws (exit status 2)

Thanks

**Comment by seankhliao** [comment]
what is in the `sdk\go1.18beta1\src\sync\cond.go` file?
It shouldn't have any `qws`

**Comment by manjeettahkur** [comment]
I uninstall and reinstall now it's working. I don't know

**Comment by ALTree** [comment]
That file hasn't changed since 2018, the source code of your Go installation is corrupted.

Diff:

```
$ git diff
diff --git a/src/sync/cond.go b/src/sync/cond.go
index b254c9360a..96b8277c57 100644
--- a/src/sync/cond.go
+++ b/src/sync/cond.go
@@ -61,7 +61,7 @@ func (c *Cond) Wait() {
 //
 // It is allowed but not required for the caller to hold c.L
 // during the call.
-func (c *Cond) Signal() {
+func (c *Cond) Signal() {qws
        c.checker.check()
        runtime_notifyListNotifyOne(&c.notify)
 }
```

and then I run your reproducer, I get the same error:

```
$ gotip run test.go
# sync
gotip/src/sync/cond.go:64:26: undefined: qws
```

**Comment by manjeettahkur** [comment]
@ALTree and @seankhliao  Thanks for your support. I don't know  what was happen may be I have added something
