### ISSUE TITLE
affected/package: strings

### ISSUE THREAD

**Issue by saran-surya** [golang/go#50757]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.17.5 windows/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Programs\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Programs\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.5
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Programs\results\golang\playground\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
</pre></details>

### What did you do?
1) Create a two text files in English with two different Encodings and I wanted to process them
2) Once I am able to read the data, I wanted to remove the space using the ```strings.TrimSpace()```. It only works for utf-8 and not for utf-16

### Code
```go
package main

import (
	"fmt"
	"io/ioutil"
	"net/http"
	"strings"
)

func processFile(src string) {
	data, _ := ioutil.ReadFile(src)

	fmt.Println("--- original source ---")
	fmt.Println(string(data))
	fmt.Println(http.DetectContentType(data))

	fmt.Println("\n--- modified source ---")
	for _, val := range strings.Split(string(data), "\n") {
		fmt.Println(strings.TrimSpace(val))
	}
}

func main() {
	processFile("./utf-16-english.txt")
	processFile("./utf-8-english.txt")
}
```

### What did you expect to see?
1) I expect to see that Golang supports all the encoding formats, or at least provide an option for the reader to get the encoding format from the user.

### What did you see instead?
![image](https://user-images.githubusercontent.com/59312489/150645131-01e4d5c6-afb1-4049-b369-eb841aca11a3.png)
- As the image shows, the file with UTF-8 encoding works fine but other formats fail so.

### Note :
Kindly let me know if there is any other method to process files with different encodings written in English.

**Comment by seankhliao** [comment]
strings explicitly only supports UTF-8

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
