### ISSUE TITLE
go/types: TypeList has a String method, but TypeParamList does not

### ISSUE THREAD

**Issue by findleyr** [golang/go#50760]
Issue #47916 does not document the `String` method for `types.TypeList` (added in https://go.dev/cl/346552 to aid with debugging). Furthermore the otherwise symmetric `TypeParamList` type does not have a `String` method.

These two list types should be symmetric. Since `types.TypeList.String` was not covered by the proposal, probably we should remove this method and propose it for 1.19.

CC @griesemer

**Comment by griesemer** [comment]
Removing `String` from `types.TypeList` is fine, but we should ensure that we're not breaking any (possibly debugging) output that uses `%s` and relies on `TypeList` implementing `Stringer`.

On the other hand, there's also a format question for `types.TypeParamList.String`: what exactly should it print? (actual type parameter list with square brackets and constraints? just the type parameter names?)
