### ISSUE TITLE
affected/package: go1.18beta1 command not found

### ISSUE THREAD

**Issue by mar1n3r0** [golang/go#50768]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
https://go.dev/doc/tutorial/generics#installing_beta

**Comment by seankhliao** [comment]
GOPATH/bin or GOBIN needs to be in your PATH

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
