### ISSUE TITLE
modules: lwp-request conflicts with git insteadOf configuration

### ISSUE THREAD

**Issue by jtagcat** [golang/go#50776]
Unsure whether this is in-scope or not.

### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.18beta1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
already latest+

### What did you do?
global gitconfig:
```
[url "git@github.com:"]
        insteadOf = https://github.com/
```

### What did you expect to see?
```
$ go get github.com/kevinburke/ssh_config
```

### What did you see instead?
```
$ go get github.com/kevinburke/ssh_config
go: github.com/inconshreveable/mousetrap@v1.0.0: reading github.com/inconshreveable/mousetrap/go.mod at revision v1.0.0: git ls-remote -q origin in /home/jc/go/pkg/mod/cache/vcs/b31cc6adcdb1f156865c53a0fef7b8e24003f65599b9dd226954d55bf79673fe: exit status 128:
        git@github.com: Permission denied (publickey).
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
```

**Comment by seankhliao** [comment]
what is `lwp-request` ?

**Comment by seankhliao** [comment]
That looks like a problem between your setup and github.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by jtagcat** [comment]
> what is `lwp-request` ?

Perl program, don't know what exactly uses it (git?), there is are no verbosity options.
>This program can be used to send requests to WWW servers and your local file system. The request content
>       for POST and PUT methods is read from stdin.  The content of the response is printed on stdout.  Error
>       messages are printed on stderr.  The program returns a status value indicating the number of URLs that
>       failed.
