### ISSUE TITLE
crypto/tls: allow 256kB certificate messages

### ISSUE THREAD

**Issue by awnumar** [golang/go#50773]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/awnumar/Library/Caches/go-build"
GOENV="/Users/awnumar/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/awnumar/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/awnumar"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.6/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s2/fftr5j0n443f4z2sm11wlxv40000gn/T/go-build2260917661=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

1. Generate a very large certificate. I passed mkcert many short SANs to get this.
2. Start a Go TLS server.
3. Connect to it with a Go TLS client.

### What did you expect to see?

I expected the connection to succeed.

### What did you see instead?

`tls: handshake message of length 110013 bytes exceeds maximum of 65536 bytes`

The limit is defined [here](https://cs.opensource.google/go/go/+/master:src/crypto/tls/common.go;l=45;bpv=1;bpt=1?q=65536%20tls&ss=go%2Fgo):

```go
const maxHandshake = 65536 // maximum handshake we support (protocol max is 16 MB)
```

and it says that the protocol max is 16 MB, not 64 KiB. I assume this hard limit is to mitigate resource exhaustion attacks, but it would be preferable if it was configurable.

### Context

We dynamically generate certificates for mTLS within and across clusters and configure which services are allowed to open connections between each other using Subject Alternative Names. In extreme cases a service that needs to communicate with many other services could have a certificate that's larger than this limit.

This isn't a problem right now but a limit of 64 KiB provides a fairly small and uncomfortable safety buffer. Is there a reason that this limit is not configurable?

This issue is related to #35153 where @FiloSottile says "Documenting something makes it a backwards compatibility promise". Is making it configurable still possible while preserving backwards compatibility in the future?

**Comment by bcmills** [comment]
> Is making it configurable still possible while preserving backwards compatibility in the future?

Yes: making something configurable is backwards-compatible as long as the default behavior remains the same. (We can be certain that no existing program configures it to anything other than the default.)

**Comment by seankhliao** [comment]
cc @golang/security

**Comment by ianlancetaylor** [comment]
CC @golang/security 

Looks like this didn't make 1.19.  Moving to backlog.  Please recategorize as appropriate.  Thanks.

**Comment by fkalinski** [comment]
I've found real-world case where I can't connect to development server.
```handshake message of length 97407 bytes exceeds maximum of 65536 bytes```

The server has some extremely long list of SANs, but the certificate is still valid and works for at least for `curl` and Chrome and AFAIK it's conformant with RFC per "MAX indicates that the upper bound is unspecified. Implementations are free to choose an upper bound that suits their environment."

Also JDK has it's setting `jdk.tls.maxHandshakeMessageSize`. It would be good to have it configurable, so that even if it's against best practices let the user decide what `maxHandshake` works for them

**Comment by rolandshoemaker** [comment]
Is there a concrete API proposal here, It sounds like essentially what is wanted is a new field on tls.Config? i.e.

```
type Config {
    ...

    // MaxHandshakeMessageSize is the maximum acceptable TLS handshake message
    // size in bytes. The protocol maximum is 16MB, calling Conn.Handshake with
    // a value higher than this will result in an error. If
    // MaxHandshakeMessageSize is 0, the default value is 64KB.
    MaxHandshakeMessageSize int
}
```

**Comment by malt3** [comment]
What is the best way to move this forward? I can create an API proposal (similar to [this](https://github.com/golang/go/issues/50773#issuecomment-1768560887)) and provide an implementation if desired.

**Comment by rsc** [comment]
If 64kB is no longer a reasonable upper limit, it seems like we should bump to a new reasonable limit. That wouldn't be an API change.

**Comment by malt3** [comment]
I propose going directly to the maximum length provided by the spec (16MB), unless there are performance or security concerns that make this infeasible.

**Comment by awnumar** [comment]
Could there be some users that are implicitly relying on the low default limit to mitigate the threat of resource exhaustion attacks? There's no way to currently specify a request size limit in `net/http.Server`, and both http servers and TLS configs mainly deal with time limits rather than size limits.

Given how rarely this limit is run into, it might be safer to provide configurability rather than a change in behaviour. At some point (maybe even at the same time) the default can also be raised somewhat.

This is mainly a theoretical concern though and I'm not sure this would actually be a problem in practice. I'm just worried about internet-exposed servers suddenly being vulnerable to DDoS by a client opening thousands of connections with large handshakes then holding the connections open until timeout. This was the original motive for having a low limit, I imagine.

**Comment by FiloSottile** [comment]
This cap limits how much memory we can be made to allocate in a handshake (which happens before anything higher level such as net/http is brought in). We should not go straight to 16MiB.

If the only message that can conceivably be that big is the Certificates message, let's just make the cap for that specific message 256KiB or something like that.

That way most servers will be unaffected, and anyway it takes more work to do a DoS than just spamming giant Client Hello messages.

**Comment by rsc** [comment]
Retitled to be about allowing 256kB certificate messages. Assuming we agree that's the path forward, this doesn't need to be a proposal anymore.

**Comment by rsc** [comment]
No objects to that, so I am going to remove this from the proposal process.
