### ISSUE TITLE
cmd/go: log.showSignature=true in .gitconfig breaks VCS stamping

### ISSUE THREAD

**Issue by dpifke** [golang/go#50789]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18beta1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dave/.cache/go-build"
GOENV="/home/dave/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dave/Source/Go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dave/Source/Go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18beta1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/usr/share/go-1.18/src/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3850153072=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
$ go install
error obtaining VCS status: unrecognized VCS tool output: strconv.ParseInt: parsing " Signature made Fri 28 Feb 2020 07:31:38 AM MST\ngpg:                using RSA key 4AEE18F83AFDEB23\ngpg: Can't check signature: No public key\n95ecdbfc0b5f3e65790c43c77874ee5357ad8a8f:1582900298": invalid syntax
        Use -buildvcs=false to disable VCS stamping.
$ git config --get log.showSignature
true
$ go install -buildvcs=false
$ echo $?
0
</pre>

### What did you expect to see?

Successful compilation sans `-buildvcs=false` flag.

Removing `showSignature = true` from ~/.gitconfig works around the issue.

### What did you see instead?

Failed compilation.

**Comment by mpx** [comment]
This should be fixed in b1a53ece after go1.18beta1 was released (`--no-show-signature` was added).

**Comment by mknyszek** [comment]
CC @bcmills 

Thanks @mpx for the reference.

**Comment by mknyszek** [comment]
Tentatively applying release-blocker until we understand more.

**Comment by bcmills** [comment]
Since this is believed to have been fixed in https://go.dev/cl/367034 (thanks @andremarianiello!), I think there is nothing remaining to be done.

@dpifke, I'm going to close this for now but please reopen if it is not fixed as expected with `gotip` or the next Go 1.18 beta or RC release.

**Comment by dpifke** [comment]
Verified fixed on master, sorry for the noise.
