### ISSUE TITLE
x/tools/gopls: specify 'source' of template file diagnostic messages

### ISSUE THREAD

**Issue by hyangah** [golang/go#50786]
gopls version: v0.7.5
go version: go1.17.5

Template diagnostics is missing source and code info. 

```
[Trace - 14:23:45.054 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///Users/hakim/ww/some.gotmpl","version":2,"diagnostics":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":5}},"severity":1,"message":"missing value for command"}]}
```

Moreover, it would be nice gopls responds to the following codeAction requests with links to documentation like other compiler/syntax/lint messages, but I am afraid there is no good reference page to use yet.

**Comment by hyangah** [comment]
cc @pjweinb

**Comment by pjweinb** [comment]
Ever since https://golang.org/cl/380974 was submitted, gopls returns a source on template errors. Is there some reason this feature request should be open?
