### ISSUE TITLE
cmd/compile:   infinite recursion in types2

### ISSUE THREAD

**Issue by danscales** [golang/go#50782]
This code below causes an infinite recursion in types2.  This may already be fixed by some changes in flight (such as https://go-review.googlesource.com/c/go/+/379414/  for issue #48962 ), but I wanted to point out this simple example as another test case, if nothing else:

```
package p

type Numeric interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64
}

// numericAbs matches numeric types with an Abs method.
type numericAbs[T Numeric] interface {
	~struct{ Value T }
	Abs() T
}

// AbsDifference computes the absolute value of the difference of
// a and b, where the absolute value is determined by the Abs method.
func absDifference[T numericAbs[T]](a, b T) T {
	d := a.Value - b.Value
	return d.Abs()
}
```

This should not be valid code - in absDifference, we are constraining T to be also ~struct { Value T }, and also there is nothing that requires that T satisfies Numeric.  But would be good if the type checker doesn't have an infinite recursion.

@griesemer @findleyr

**Comment by griesemer** [comment]
This doesn't seem related to #48962. Simpler reproducer:
```Go
package p

type T[P int] struct{ f P }

func _[P T[P]]() {}
```
