### ISSUE TITLE
net/http: server sets TCPConn writebuf through ConnContext hook will block the send of a big response body

### ISSUE THREAD

**Issue by chenjie199234** [golang/go#50795]
### What version of Go are you using (`go version`)?

```
1.17.6
```

### Does this issue reproduce with the latest release?
```
yes
```

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
linux amd64
</pre></details>

### What did you do?

```
&http.Server{
	ReadTimeout:    time.Second,
	IdleTimeout:    time.Second,
	MaxHeaderBytes: 1024,
	ConnContext: func(ctx context.Context, conn net.Conn) context.Context {
		(conn.(*net.TCPConn)).SetReadBuffer(2048)
		(conn.(*net.TCPConn)).SetWriteBuffer(2048)
		return ctx
	},
}
use this server and write 12K+ data to response's body
but only 4096 data send
same code,but set the buf to 4096,all data will be send
but when i send 1M+ data when the buf is set to 4096,the send data truncate too
why?
```
this is the tcpdump file
wireshark filter is ```tcp.stream eq 18```
[pod-capture.cap.zip](https://github.com/golang/go/files/7931287/pod-capture.cap.zip)

### What did you expect to see?
```
all data should be send
```

### What did you see instead?

```
it will block on tcp write,and only part of the data will be send
```

**Comment by mknyszek** [comment]
CC @neild

**Comment by chenjie199234** [comment]
@mknyszek 
here is one request's trace info from pprof
it works on G1069312,and it finally blocks on internal/pool.(*FD).Write():283,no more trace info in this 60s.
[trace.zip](https://github.com/golang/go/files/7938812/trace.zip)

**Comment by chenjie199234** [comment]
here is one request's profile info from pprof
[profile.zip](https://github.com/golang/go/files/7938882/profile.zip)

**Comment by chenjie199234** [comment]
this is my self trace info
the start is the time when i get the request
the end is the time when the Write return
```
[TRACE] {"trace_id":"1643164511883031560_7626180989541976002","deep":1,"start":1643164511883037729,"end":1643165625828797709,"host_name":"supports-service-77cc9b447f-4btjv","role":"server","from_app":"unknown","from_ip":"10.136.207.227:23366","from_method":"unknown","from_path":"unknown","to_app":"psp-prod.supports","to_ip":"10.136.192.250","to_method":"POST","to_path":"/supports.gamelog/SearchLog","err_msg":"","err_code":0}
```

**Comment by chenjie199234** [comment]
i have 2 kubernetes cluster
one cluster works right,kubernetes‘ node’s linux kernel is 3.14+
one cluster works wrong,kubernetes' node's linux kernel is 3.10.0-957.21.3.el7.x86_64
and they have some difference on kernel's sysconfig
this is the only difference

**Comment by chenjie199234** [comment]
if delete
```
(conn.(*net.TCPConn)).SetReadBuffer(2048)
(conn.(*net.TCPConn)).SetWriteBuffer(2048)
```
every thing works fine
here is the trace from pprof after i delete it
[trace-delete-set-buf.zip](https://github.com/golang/go/files/7939001/trace-delete-set-buf.zip)
why?
