### ISSUE TITLE
net/http: http.Transport leaks context from the request 

### ISSUE THREAD

**Issue by juliens** [golang/go#50798]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/juliens/.cache/go-build"
GOENV="/home/juliens/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/juliens/dev/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/juliens/dev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/juliens/.gvm/gos/go1.17"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/juliens/.gvm/gos/go1.17/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3799944390=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
I use the `http.Transport` to make an HTTP request. I add a not empty struct in the request context.

You can reproduce it like [this](https://go.dev/play/p/4TPEYIbR2-V)

### What did you expect to see?
After the end of the request, the struct and the context are cleaned by the GC.

### What did you see instead?
After the end of the request, the struct and the context are **not** cleaned by the GC.

Maybe this is the same issue as https://github.com/golang/go/issues/43966

**Comment by mknyszek** [comment]
CC @neild

**Comment by netrebel** [comment]
We seem to be having the same problem. In long running instances, memory utilization is going up every day reaching 80-90% in ~12 days. We started seeing this issue when we upgraded from Go 1.11.3 (no modules) to 1.17 (with go-modules), before the Memory would stay under 30%. Servers have 4GBs.

When I run `pprof` I see something similar to the comment in the [ticket referenced](https://github.com/golang/go/issues/43966#issuecomment-927198600):

```
      flat  flat%   sum%        cum   cum%
    1.50MB  5.07%  5.07%    12.04MB 40.70%  net/http.(*Transport).dialConn
         0     0%  5.07%    12.04MB 40.70%  net/http.(*Transport).dialConnFor
    8.03MB 27.14% 32.21%     8.03MB 27.14%  bufio.NewWriterSize (inline)
    6.02MB 20.36% 52.57%     6.02MB 20.36%  bufio.NewReaderSize (inline)
```

**Comment by netrebel** [comment]
> We seem to be having the same problem. In long running instances, memory utilization is going up every day reaching 80-90% in ~12 days. We started seeing this issue when we upgraded from Go 1.11.3 (no modules) to 1.17 (with go-modules), before the Memory would stay under 30%. Servers have 4GBs.
> 
> When I run `pprof` I see something similar to the comment in the [ticket referenced](https://github.com/golang/go/issues/43966#issuecomment-927198600):
> 
> ```
>       flat  flat%   sum%        cum   cum%
>     1.50MB  5.07%  5.07%    12.04MB 40.70%  net/http.(*Transport).dialConn
>          0     0%  5.07%    12.04MB 40.70%  net/http.(*Transport).dialConnFor
>     8.03MB 27.14% 32.21%     8.03MB 27.14%  bufio.NewWriterSize (inline)
>     6.02MB 20.36% 52.57%     6.02MB 20.36%  bufio.NewReaderSize (inline)
> ```

In case this helps someone, this other ticket was closed with a comment explaining how to avoid this issue: https://github.com/newrelic/go-agent/issues/447#issuecomment-1268956221

**Comment by luca147** [comment]
Well I spotted in my case the solution, I have a global scope context that are aware when a term signal come and all of my workers need to be stopped when it comes. So every time a job start I create a new context with cancel and defer it. With this simple change the leak over bufio.NewWriterSize/bufio.NewReaderSize into transport disappear.

**Comment by urenner-n2i** [comment]
Any update on this issue? 
When connecting to new hosts very often, the memory consumption increases very quickly, and never decreases.

**Comment by nikita21** [comment]
We are seeing similar issue when we upgraded from Go 1.13 (no modules) to 1.17 (with go-modules). In our worker instances, memory utilization is going up every day reaching 80-90% in ~8 days. Even tried upgrading to 1.19 but issue still persists.
 
<img width="561" alt="Screenshot 2023-06-05 at 3 42 50 PM" src="https://github.com/golang/go/assets/6737058/9930643a-fcfb-4536-bcbd-e16047dcf45b">

**Comment by xsteadfastx** [comment]
my pprof looks exactly the same. are there any workarounds? what can i do?

**Comment by AlexanderYastrebov** [comment]
Request context is used to dial connection and there is also https://github.com/golang/go/issues/59017#issuecomment-1499653264 that suggests that it should not be used for that.

**Comment by AlexanderYastrebov** [comment]
#61524 only fixes request context leakage but does not fix *persistConn leaks which I plan to address separately.

**Comment by isubasinghe** [comment]
I am seemingly still hitting this in 1.23.3, should I open a new issue for this, or should this be reopened?
I am hitting exactly @nikita21's issue, I am seeing dialConn allocating more and more memory.
