### ISSUE TITLE
how to solve the problems using go/analysis lib?

### ISSUE THREAD

**Issue by jarrodcal** [golang/go#50797]
https://pkg.go.dev/golang.org/x/tools@v0.1.8/go/analysis

I am running ast/ssa tool  using go/analysis lib to analysis my projects.
like this：

`package unusedresult

var Analyzer = &analysis.Analyzer{
	Name: "unusedresult",
	Doc:  "check for unused results of calls to some functions",
	Run:  run,
	...
}

func run(pass *analysis.Pass) (interface{}, error) {
	...
}`

but it gives following error：
"could not import C (no metadata for C)" golang error 
`
-: C source files not allowed when not using cgo or SWIG: gcc_context.c gcc_fatalf.c gcc_libinit.c gcc_linux_amd64.c gcc_mmap.c gcc_setenv.c gcc_sigaction.c gcc_traceback.c gcc_util.c linux_syscall.c

/tmp/go-static-analysis-test/pkg/mod/github.com/tecbot/gorocksdb@v0.0.0-20191217155057-f0fad39f321c/options.go:5:8: could not import C (no metadata for C)

/tmp/go-static-analysis-test/pkg/mod/github.com/tecbot/gorocksdb@v0.0.0-20191217155057-f0fad39f321c/compaction_filter.go:46:10: undeclared name: C

/tmp/go-static-analysis-test/pkg/mod/github.com/tecbot/gorocksdb@v0.0.0-20191217155057-f0fad39f321c/compaction_filter.go:55:56: undeclared name: C`

my project uses CGO，how to solve?  Including the whole code in comments (CGO)?

Another question:
If the project does not use go module,   can use this library to scan the code？
if using go/analysis the project is required to use go module?
 
### What is your user agent?
Linux

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
