### ISSUE TITLE
proposal: Go 2: 

### ISSUE THREAD

**Issue by vituchon** [golang/go#50793]
¿Really Generics?

Don't get me wrong but.... i once stated

"As a reflection that I do... golang does not provide generics and this does not imply that we lack a tool, in fact with interfaces we already have all the genericity that we want... so the 'tool' to model exists... the issue is to get the hang of it!"

For me there was no need.

Okey, i guess to move on and try a new tool, but i don't know how much many time from now i start to see more messy code rather than simple (but i litttle longer perharps, and that open the ways to talk about the tradeoffs...).

Anyway! 

Greetings to all and keep the good work.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
