### ISSUE TITLE
cmd/link: migrate from legacy .zdebug to SHF_COMPRESSED for ELF

### ISSUE THREAD

**Issue by MaskRay** [golang/go#50796]
#11799 uses the legacy ELF compression format `.zdebug_*` instead of the standard `SHF_COMPRESSED` defined by the generic ABI. I understand that there is cross-binary-format convenience (Mach-O doesn't have `SHF_COMPRESSED`), but it'd be nice if Go matches the prevailing style and switches to `SHF_COMPRESSED` for ELF. In 2015-07, the binutils patch `[PATCH] Make default compression gABI compliant` (milestone: binutils 2.26) switched the default to the generic ABI format. It has been very difficult to find new `.zdebug` from that time on. New tools developed for ELF than would not be to support Go created legacy `.zdebug*` sections. We don't have to worry about the toolchain compatibility. There are more tools understanding `SHF_COMPRESSES` than tools only understanding `.zdebug`.

http://www.linker-aliens.org/blogs/ali/entry/elf_section_compression/ has some notes about alignment issues with `.zdebug`.

For Mach-O, since there isn't a section attribute, we may stick with `__zdebug_`.

**Comment by mengzhuo** [comment]
Is it `sect.Flags &= SHF_COMPRESSED`  in this compressed section helps?

https://github.com/golang/go/blob/16d6a5233a183be7264295c66167d35c689f9372/src/cmd/link/internal/ld/dwarf.go#L2224-L2235

**Comment by MaskRay** [comment]
There is a header difference.

The legacy `.zdebug` format uses (per http://www.linker-aliens.org/blogs/ali/entry/elf_section_compression/):
```c
typedef struct {
	uchar_t		gch_magic[4];  /* [ 'Z', 'L', 'I', 'B'] */
	uchar_t		gch_size[8];   /* unaligned 64-bit ELFDATAMSB integer */
} Chdr_GNU;
```

The generic ABI standard format (SHF_COMPRESSED) uses:
http://www.sco.com/developers/gabi/latest/ch4.sheader.html
```c
typedef struct {
	Elf32_Word	ch_type;
	Elf32_Word	ch_size;
	Elf32_Word	ch_addralign;
} Elf32_Chdr;

typedef struct {
	Elf64_Word	ch_type;
	Elf64_Word	ch_reserved;
	Elf64_Xword	ch_size;
	Elf64_Xword	ch_addralign;
} Elf64_Chdr;
```

**Comment by mknyszek** [comment]
CC @thanm @cherrymui @aclements

**Comment by cherrymui** [comment]
cc @aclements @thanm 

Maybe the old format was used because of old versions of GDB? @aclements might remember.

**Comment by aarzilli** [comment]
> Maybe the old format was used because of old versions of GDB? @aclements might remember.

I think the reason is that there is no equivalent of compressed sections in mach-o and PE, which would have to either be uncompressed or use zdebug anyway.
