### ISSUE TITLE
x/pkgsite: package removal request for github.com/jostgrant/turtorial-server

### ISSUE THREAD

**Issue by jostgrant** [golang/go#50808]
### What is the path of the package that you would like to have removed?
https://pkg.go.dev/github.com/jostgrant/turtorial-server 
Formerly hosted at https://github.com/jostgrant/turtorial-server
 
### Are you the owner of this package?
Yes.

### What is the reason that you could not retract this package instead?
Not understanding that things got published automatically -- I created a tag a day-or-two ago, have since moved the given repo to its own GH Org (https://github.com/turtorial-io/server) and then deleted the tag remotely / made a new one under a different name. To my knowledge, the above pkg.go.dev link points to a dangling tag I can't do anything with.

**Comment by jostgrant** [comment]
So not sure if I just resolved this, or made it worse. lol
Tried to "cheese it" by making a new repo in the old location (jostgrant/turtorial-server) and reverted back to the commit I made the tag in-question from , but did not publish any new in its place -- and added the obligatory `revert{}` command and my go.mod and pushed. Now when I go to pkg.go.dev and search "turtorial" the old entry still comes up but if I press the search button again it brings up the current location "turtorial-io/server".

**Comment by seankhliao** [comment]
If you want to try `retract`, add one with `retract [v0.0.0-0, vX.Y.Z]` and publish / pull through the proxy at `vX.Y.Z` (where `vX.Y.Z is the next version you would have published)

See also [blog post](https://seankhliao.com/blog/12022-01-19-unpublishing-go-modules/) for longer explanation

**Comment by jostgrant** [comment]
So I've been messing around a bit, and I'm afraid to basically add more tags / muck things up even more (because right now, I'm really just poking around in the dark). I'm either going to just wait for hopefully the jostgrant/turtorial-server package to be removed (in-effect of this issue) or publish an ugly hack of a tag I guess with a README that just points / refers to the other location.

**Comment by jostgrant** [comment]
Indirectly that was a response to @seankhliao if that wasn't clear.

**Comment by jostgrant** [comment]
Yeah, evidently I have no idea what I'm doing. Tried to do the latter re: the README and nothing updated. I'm just deleting the repo again and hoping someone takes pity on me. lol

**Comment by jostgrant** [comment]
Closing; Seems like retract did work! Just that it took about a day for some service to remove the old listing. Thanks @seankhliao for the help. :^)
