### ISSUE TITLE
cmd/buildid: crashes trying to write buildid in binary built by Go 1.5

### ISSUE THREAD

**Issue by stevemk14ebr** [golang/go#50809]
### What version of Go are you using (`go version`)?
1.17.2 linux/amd64

<pre>
$ go version
1.17.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
linux

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
run `go tool buildid -w <filepath>` on a go 1.5 binary and the following error will occur:

```
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
main.main()
        /usr/local/go/src/cmd/buildid/buildid.go:56 +0x60d
```

The line:
https://github.com/golang/go/blob/cfad1ff84c45f99f6ceee17f76e2cbaf2ff8598b/src/cmd/buildid/buildid.go#L56

This is because in go 1.5 the contentID did not exist, so the slash seperator is not present, causing issues. The buildid tool doesn't consider legacy buildID/actionID/contentID layouts.

### What did you expect to see?
The buildID / contentID to be written

### What did you see instead?
crash

**Comment by ianlancetaylor** [comment]
Also fails with Go 1.6 through Go 1.9.  Go 1.10 and later seem to work.

Those older versions of Go are not supported.  If someone wants to contribute a fix that would be fine but I don't think we are going to actively work on this.
