### ISSUE TITLE
x/net/websocket: allow configurable read size limit, and MaxHeaderBytes

### ISSUE THREAD

**Issue by slimsag** [golang/go#5082]
<pre>What steps will reproduce the problem?
    Currently go.net/websocket provides no way to limit how much data an websocket server reads, if an client sends very large amounts of data (messages, frames) the websocket server will allocate that memory, and will continue to do so, until the server runs out of memory or the client crashes.

[In someone else's tests] it has been observed that there is also no header limit
provided (for the same issue). (See discussion:
<a href="https://groups.google.com/forum/?fromgroups=#">https://groups.google.com/forum/?fromgroups=#</a>!topic/golang-nuts/2Tge6U8-QYI)

What is the expected output?
go.net/websocket should provide an way to set an maximum read size and maximum header
read size, to avoid attacks from potentially malicious clients.</pre>

**Comment by gdamore** [comment]
This actually is a tragic failing.  It means that Go websockets cannot be used safely in an unprotected network, since malefactor can simply request a giant message to DoS your service.

**Comment by gdamore** [comment]
Bump.  This is a *SECURITY FAILURE*.  Its a trivial remote DoS for websocket, meaning that you should *not* use native Golang websockets pretty much *anywhere*.

**Comment by gdamore** [comment]
In fact, this is probably the *only* reason that I have to use 3rd party Gorilla websocket instead of native golang one.  Which angers me as the Gorilla folks have busted compatibility for Go versions < 1.5 recently.

**Comment by artyom** [comment]
One option to limit incoming payload size can be introduction of optional "max.received message payload size" field to websocket.Codec struct, which, if non-zero, should be treated by Codec.Receive method as indication to wrap frame io.Reader into something similar to io.LimitedReader (that also has to report ErrUnexpectedEOF to recognize incomplete reads) right before the call to ioutil.ReadAll, which is a culprit here.

**Comment by ianlancetaylor** [comment]
Anybody want to send in a fix?  If you are unsure about the approach, discuss on the golang-dev mailing list first.

**Comment by artyom** [comment]
@ianlancetaylor will open a mailing list thread then, ready to get my hands on this.

**Comment by gdamore** [comment]
Yay!  Glad to see progress here!

On Mon, May 30, 2016 at 12:08 PM, Artyom Pervukhin <notifications@github.com
