### ISSUE TITLE
x/build: update gcc on Windows longtest builders

### ISSUE THREAD

**Issue by bcmills** [golang/go#50824]
As far as I can tell, the `gcc` used to run tests on the Go `windows-amd64-longtest` builders is currently version `5.1.0`:

```
gopher@SERVER-2016-V7- C:\godep\gcc64\bin>.\gcc --version
gcc (tdm64-1) 5.1.0
```

According to the [GCC release history](https://gcc.gnu.org/releases.html), 5.1.0 was released April 22, 2015, nearly seven(!) years ago. There have been subsequent maintenance releases up to GCC 5.5 (Oct. 10, 2017), and no apparent active maintenance since then.

The GCC flags required for [reproducible builds](https://reproducible-builds.org/docs/build-path/) are only available as of GCC 8 or higher, so having such an antiquated compiler on the Windows builders means that we cannot test cgo-enabled builds for reproducibility on the builders.

The builder image needs a few other updates for adequate test coverage as well (see #46693), so we should probably refresh `gcc` at the same time. (CC @golang/release)

Going forward, I would like to see us have a consistent plan for keeping builder images up to date. While it may be important to test against very old compilers, in general we expect users to work around platform bugs by upgrading their platform to fix those bugs — so it is even more important that we test against up-to-date platforms, especially on the `-longtest` builders.

**Comment by bcmills** [comment]
I would like to make build reproducibility a priority for 2022. Marking as release-blocker for Go 1.19, and I will have a separate conversation with the release team to make a plan to resolve this.

**Comment by ALTree** [comment]
Essentially #43195 and #35006. Some discussion in both places regarding the toolchains to use.

**Comment by bcmills** [comment]
Indeed! I had missed #35006 because it refers to `mingw` instead of `gcc`, and I had missed #43195 because it wasn't labeled `OS-Windows`. 😞

**Comment by bcmills** [comment]
Duplicate of #35006
