### ISSUE TITLE
x/tools/gopls: drop support for building at Go 1.12

### ISSUE THREAD

**Issue by findleyr** [golang/go#50827]
As discovered in [CL 380555](https://go.dev/cl/380555), some of our dependencies no longer support building with Go 1.12. This is to be expected -- 1.12 was a long time ago.

#50825 outlines a long-term plan to remove support for building gopls at legacy Go versions, but in the meantime we need to to mark gopls@v0.7.5 as the final release supporting being built by Go 1.12. Fortunately, this is consistent with our [stated](https://github.com/golang/tools/tree/master/gopls#supported-go-versions-and-build-systems) support for the four latest major Go versions.

Action items:

- [x] check with the VS Code team to see if there's anything we can do to help users avoid breakage when upgrading gopls from VS Code (CC @hyangah @suzmue)
- [x] document our new compatibility matrix.
- [x] update the v0.7.5 release notes
- [x] remove Kokoro 1.12 CI
- [ ] upgrade our dependencies, thus breaking the 1.12 build

**Comment by Davidrjx** [comment]
using golang v1.12.17 with gopls v0.7.5 not working, reporting 
```
../../../../pkg/mod/golang.org/x/tools@v0.1.9-0.20220114220130-fd7798718afd/go/analysis/passes/buildtag/buildtag.go:13:2: package go/build/constraint is not in GOROOT (/usr/local/go1.12.17/go/src/go/build/constraint)
../../../../pkg/mod/github.com/!burnt!sushi/toml@v0.4.1/decode_go116.go:6:2: package io/fs is not in GOROOT (/usr/local/go1.12.17/go/src/io/fs)
```

**Comment by findleyr** [comment]
@Davidrjx did you use `go get -u`?

The following works for me, from a directory not containing a go.mod file:
```
GO111MODULE=on go1.12.17 get golang.org/x/tools/gopls@v0.7.5
```

But also: go 1.12 is many years old at this point, and has not been supported by the Go team for some time (the Go team currently supports only Go 1.18 and Go 1.19). Is there a reason you cannot use a supported version of Go?

**Comment by Davidrjx** [comment]
> @Davidrjx did you use `go get -u`?
> 
> The following works for me, from a directory not containing a go.mod file:
> 
> ```
> GO111MODULE=on go1.12.17 get golang.org/x/tools/gopls@v0.7.5
> ```
> 
> But also: go 1.12 is many years old at this point, and has not been supported by the Go team for some time (the Go team currently supports only Go 1.18 and Go 1.19). Is there a reason you cannot use a supported version of Go?

i was building calico v3.9.1 and project source contains a go.mod file
