### ISSUE TITLE
go/types, types2: bad "invalid composite literal type" error for type parameter with pointer structural type

### ISSUE THREAD

**Issue by mdempsky** [golang/go#50833]
F below is valid non-generic code, so I'd expect G to compile successfully too. However, go/types and types2 currently reject it.

```
package p

func F() {
        type T = *struct{ f int }
        _ = []T{{f: 1}}
}

func G[T ~*struct{ f int }]() {
        _ = []T{{f: 1}}
}
```

/cc @griesemer @findleyr @ianlancetaylor

**Comment by mdempsky** [comment]
CL 381075 appears to be a fairly straightforward fix to this issue, assuming we decide it is an issue.

**Comment by griesemer** [comment]
I think we probably want to fix this.

**Comment by ianlancetaylor** [comment]
I'm fine with fixing this for 1.18 but I also think it's OK to let it wait until 1.19.

I'm a little bit concerned that we are focusing a bit too much on structural types.  At this point I expect them to be a tiny corner case.  If anything I think we should focus more on making operations work if they are supported by all elements of a type set that does not have a structural type.  But that is definitely for 1.19 or 1.20.  If we can make that work, then all these structural type details will be subsumed by the more general, and more useful, case.

**Comment by griesemer** [comment]
The fix does simplify the code and is arguably more regular, so there's that.

**Comment by ianlancetaylor** [comment]
I'm fine with fixing this for 1.18.
