### ISSUE TITLE
runtime: TestGdbBacktrace failures with "No such process." since 2021-10-15

### ISSUE THREAD

**Issue by bcmills** [golang/go#50838]
`greplogs --dashboard -md -l -e 'FAIL: TestGdbBacktrace .*(?:\n    .*)*: No such process\.'`

[2022-01-24T17:07:30-f88c3b9/linux-386](https://build.golang.org/log/85d78a8e75855b04f9c63eb1b8b571539d4dca98)
[2021-11-05T20:59:43-dbd3cf8/linux-amd64-nocgo](https://build.golang.org/log/351b7aac67c6917a3891e868cc43c9b611112676)
[2021-10-15T03:49:17-8dab959/linux-amd64-nocgo](https://build.golang.org/log/d0b2ca3f3e79d169b9d0915f0437ce9018eeb0f4)

This is a new failure mode for a known-flaky test (see #37405; CC @aclements, @jeremyfaller). Unfortunately, this failure mode appears to predate the CLs added for that issue.

**Comment by mknyszek** [comment]
Since this failure mode is old, I'm putting this in backlog. But if it looks like this is plaguing the dashboard enough, we might want to consider moving it into the 1.18 milestone.

**Comment by bcmills** [comment]
> Since this failure mode is old,

Note that this particular failure mode is _not_ old — it's new as of October. (The older failures for this test have different failure modes.)

**Comment by bcmills** [comment]
One more:

`greplogs --dashboard -md -l -e 'FAIL: TestGdbBacktrace .*(?:\n .*)*: No such process\.' --since=2022-01-26`

[2022-02-10T01:08:52-656d3f4/linux-386](https://build.golang.org/log/7f9d76ee6b48b0adca64498eebbd481dc97413b6)

Note that these failures are so far all on [first-class ports](https://go.dev/wiki/PortingPolicy#first-class-ports).

**Comment by bcmills** [comment]
This is a release blocker at least until a skip is added for this failure mode, then it can be moved back to the backlog.

(Given the other failure modes of this test, I don't think it's worth trying to get in a fix for the root cause during the freeze.)

**Comment by bcmills** [comment]
This looks like https://sourceware.org/bugzilla/show_bug.cgi?id=9086, open against `gdb` since 2005-08-03. 😩

**Comment by mknyszek** [comment]
Oof. I'll add the skip.

**Comment by bcmills** [comment]
I've got a CL pending already. I should also update the other skip with a comment for the GDB bug...

**Comment by mknyszek** [comment]
Ah OK. Feel free to send it to me.
