### ISSUE TITLE
cmd/compile: invalid field name *** in struct initializer

### ISSUE THREAD

**Issue by Reasno** [golang/go#50848]
### What version of Go are you using (`go version`)?

go 1.18beta1

<pre>
$ go version
go1.18beta1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes. 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/donew/Library/Caches/go-build"
GOENV="/Users/donew/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/donew/src/go/pkg/mod"
GONOPROXY="glab.tagtic.cn"
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/donew/src/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Users/donew/src/go/go1.18beta1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/donew/src/go/go1.18beta1/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18beta1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/donew/Downloads/go118bug/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/92/6vv251ls5_lgh6kmm9xq_wh80000gn/T/go-build1725229051=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

when I was playing with generics I discovered a subtle (possible) compiler bug. `go1.18beta1 vet` and `go1.18beta1 build` gives me no complaint but the `go1.18beta1 test` failed out of no good reason. 

The offending code is isolated in https://github.com/Reasno/go1.18beta1bug.

The code with generic: 

```go
package bar

type Data[K comparable, V any] struct {
	field int
}

type Dataset[K comparable, V any] struct{}

func (m *Dataset[K, V]) GetData() *Data[K, V] {
	d := &Data[K, V]{field: 1}
	return d
}

var DefaultDataset = Dataset[string, any]{}

func GetData() *Data[string, any] {
	return DefaultDataset.GetData()
}
```

and the test file: 
```go
package bar_test

import (
	bar "github.com/reasno/go1.18beta1bug"
	"testing"
)

func Test(t *testing.T) {
	bar.GetData()
}
```

### What did you expect to see?

The `go1.18beta1 test` compilation should be green.

### What did you see instead?

`go1.18beta1 test` rants: ../main.go:10:24: invalid field name bar.field in struct initializer

**Comment by mknyszek** [comment]
Because this seems to be fixed, not marking as a release blocker. Waiting for info from OP to verify that it's fixed at tip.

**Comment by Reasno** [comment]
I compiled go from git master and the issue remains

```bash
$ go version
go version devel go1.18-9ff0039848 Fri Jan 28 02:40:34 2022 +0000 darwin/amd64
$ go test
# github.com/reasno/go1.18beta1bug_test [github.com/reasno/go1.18beta1bug.test]
./main.go:10:24: invalid field name bar.field in struct initializer
FAIL    github.com/reasno/go1.18beta1bug [build failed]
```

**Comment by randall77** [comment]
I can't get it to fail at tip (@9ff00398489d9eb1822b3de028cd6ccf5674ebb3) but I can at 1.18beta1.

Just to be clear I have a directory `issue50848` with three items in it:

go.mod:
```
module issue50848

go 1.18
```
issue50848_test.go:
```
package issue50848_test

import (
	"testing"

	"issue50848/bar"
)

func Test(t *testing.T) {
	bar.GetData()
}
```
and a directory `bar` with one file in it, `bar.go`:
```
package bar

type Data[K comparable, V any] struct {
	field int
}

type Dataset[K comparable, V any] struct{}

func (m *Dataset[K, V]) GetData() *Data[K, V] {
	d := &Data[K, V]{field: 1}
	return d
}

var DefaultDataset = Dataset[string, any]{}

func GetData() *Data[string, any] {
	return DefaultDataset.GetData()
}
```

Which gives:
```
issue50848 % ~/go1.18beta1/bin/go test
# issue50848_test [issue50848.test]
./bar/bar.go:10:24: invalid field name bar.field in struct initializer
FAIL	issue50848 [build failed]
issue50848 % ~/sandbox/ro/bin/go test 
PASS
ok  	issue50848	0.004s
```
(`~/sandbox/ro` is synced and make.bash'd at the commit listed above.)

**Comment by Reasno** [comment]
> ```shell
> go version devel go1.18-9ff0039848 Fri Jan 28 02:40:34 2022 +0000 darwin/amd64
> ```

Looks like you are right. 

My IDE has `GOROOT="~/src/go/go1.18beta1"`set even though the binary I used is the latest.  In a fresh terminal, I can confirm the bug is fixed at tip. 

Thanks for the hard work.
