### ISSUE TITLE
doc: fuzzing tutorial: is the final test correct?

### ISSUE THREAD

**Issue by Alfa-Alex** [golang/go#50852]
https://go.dev/doc/tutorial/fuzz

The final test func is:
```go
01 func(t *testing.T, orig string) {
02    rev, err1 := Reverse(orig)
03    if err1 != nil {
04        return
05    }
06    doubleRev, err2 := Reverse(rev)
07    if err2 != nil {
08        return
09    }
10    if orig != doubleRev {
11        t.Errorf("Before: %q, after: %q", orig, doubleRev)
12    }
13    if utf8.ValidString(orig) && !utf8.ValidString(rev) {
14        t.Errorf("Reverse produced invalid UTF-8 string %q", rev)
15    }
}
```
Now, `Reverse(s)` returns an error `if !utf8.ValidString(s)`, which will cause us to early return in Line 08 if `!utf8.ValidString(rev)`. So the final `if` in Line 13 can never be true.

Looking at the preceding steps of the tutorial, I suppose we *do* want to fail if `rev` is not a valid utf8 string. So my guess is that we should move the test in Lines 13-15 to before Line 06!?

**Comment by mknyszek** [comment]
I think the way it's written is fine. The point of this function is to treat `Reverse` as a closed box. If there's a bug in `Reverse`, then line 13 could sometimes be true.

For example, if `Reverse` was implemented (incorrectly) as a simple byte swap (so UTF-8 validity is thrown out the window) then double-reverse would work, but the reversed string could contain invalid UTF-8 characters.

Because I don't see an actual issue here, I'm going to close this out. For questions like these, I suggest asking on https://groups.google.com/g/golang-nuts first before filing an issue. That way you can get an answer to your question and/or confirmation that there's an actual bug here, as well as feedback from others that there's something misleading about the tutorial.

**Comment by Alfa-Alex** [comment]
Perhaps I just didn't do a good job in describing the issue. Let me give you a working example:

## What's the problem with the final solution in the tutorial?
Use the final `Reverse` func but change the implementation such that it (incorrectly) does a simple byte swap:
```go
func Reverse(s string) (string, error) {
	if !utf8.ValidString(s) {
		return s, errors.New("input is not valid UTF-8")
	}
	b := []byte(s)
	for i, j := 0, len(b)-1; i < len(b)/2; i, j = i+1, j-1 {
		b[i], b[j] = b[j], b[i]
	}
	return string(b), nil
}
```
Use exactly the test that appears at the end of the tutorial to test this (incorrect!) function:
```go
func FuzzReverse(f *testing.F) {
	testcases := []string{"Hello, world", " ", "!12345"}
	for _, tc := range testcases {
		f.Add(tc) // Use f.Add to provide a seed corpus
	}
	f.Fuzz(func(t *testing.T, orig string) {
		rev, err1 := Reverse(orig)
		if err1 != nil {
			return
		}
		doubleRev, err2 := Reverse(rev)
		if err2 != nil {
			return
		}
		if orig != doubleRev {
			t.Errorf("Before: %q, after: %q", orig, doubleRev)
		}
		if utf8.ValidString(orig) && !utf8.ValidString(rev) {
			t.Errorf("Reverse produced invalid UTF-8 string %q", rev)
		}
	})
}
```
Output: `PASS`

### What would you expect instead?
`FAIL`

## Solution
My suggestion is to change the test such that it checks the utf8 validity right after the first `Reverse` call.
If you do so, the test will fail with the above (incorrect) `Reverse` function (which is what I would expect from this test):
```go
func FuzzReverse(f *testing.F) {
	testcases := []string{"Hello, world", " ", "!12345"}
	for _, tc := range testcases {
		f.Add(tc) // Use f.Add to provide a seed corpus
	}
	f.Fuzz(func(t *testing.T, orig string) {
		rev, err1 := Reverse(orig)
		if err1 != nil {
			return
		}
		if utf8.ValidString(orig) && !utf8.ValidString(rev) {
			t.Errorf("Reverse produced invalid UTF-8 string %q", rev)
		}
		doubleRev, err2 := Reverse(rev)
		if err2 != nil {
			return
		}
		if orig != doubleRev {
			t.Errorf("Before: %q, after: %q", orig, doubleRev)
		}
	})
}
```
Now the result is:
```
--- FAIL: FuzzReverse (0.05s)
    --- FAIL: FuzzReverse (0.00s)
        reverse_test.go:19: Reverse produced invalid UTF-8 string "\x93\xce"
    
    Failing input written to testdata/fuzz/FuzzReverse/9edc18acd071d487cf9bc9f806611d37dfd91e318afbcce33d0d12b959738d74
    To re-run:
    go test -run=FuzzReverse/9edc18acd071d487cf9bc9f806611d37dfd91e318afbcce33d0d12b959738d74
FAIL
```
