### ISSUE TITLE
x/build: plan9-arm builder "disk is full" failures starting 2022-01-26

### ISSUE THREAD

**Issue by bcmills** [golang/go#50857]
`greplogs --dashboard -md -l -e '(?ms)\Aplan9-arm .* disk is full' --since=2021-12-01`

[2022-01-27T05:30:27-bbe1937-a991d9d/plan9-arm](https://build.golang.org/log/4750ebcf5aa9f02468ff9c9cb4ddab5b160a1985)
[2022-01-27T05:30:27-aa10faf-a991d9d/plan9-arm](https://build.golang.org/log/1f5edf612112cf472c2dbebf4f7dc8df2ac648d8)
[2022-01-27T00:03:31-bbe1937-f4aa021/plan9-arm](https://build.golang.org/log/f82de6b8ce2c0afc2c0dd726e506c26af51d950e)
[2022-01-26T23:43:39-bbe1937-db48840/plan9-arm](https://build.golang.org/log/3cbe74efe432908017a65a831f586044aaa2fa9e)
[2022-01-26T22:09:36-bbe1937-ca6a5c0/plan9-arm](https://build.golang.org/log/0227236989eacb9aa9447848e9c93e4b9453f6ff)
[2022-01-26T17:58:00-bbe1937-719e989/plan9-arm](https://build.golang.org/log/637e5856e3b20362992840564c752d626931c76d)

(attn @millerresearch)

**Comment by millerresearch** [comment]
Yes, the disk (partition) was full. That particular machine was running the buildlet in a loop without re-booting between runs. I think it was the testcache which grew too much.

Given the overhead cost of saving test inputs in the cache (especially on Plan 9, but it's a nonzero cost anywhere), and given that every builder run should be independent and never use cached results, might it be a good idea to disable testcache for test runs on the builders? For the subrepo tests it's just a matter of adding `-count 1` to the parameters of the `go test` command sent to the builder. For the main tree test, I'm not sure how to disable the testcache with `go tool dist test`, but there ought to be simple way.

**Comment by bcmills** [comment]
Given that most of the Go project's own builders run in VMs, I would guess that the `buildlet` binary assumes that the build cache goes away completely in between runs.

Ah — here it is!
https://cs.opensource.google/go/x/build/+/master:cmd/buildlet/buildlet.go;l=211-212;drc=6d1c239cf4abb0e612c783ff67bf13966713df5f

For some reason the logic to clean the cache seems to be skipped on `windows` and `plan9` builders, and I don't see any comments in the code or in [CL 144637](https://go.dev/cl/144637) explaining why. @dmitshur, @bradfitz: can you offer any insight?

**Comment by millerresearch** [comment]
The usual plan9-arm builders re-boot between runs with a fresh empty disk partition, so normally there wouldn't be a cache to clean; so that's not a problem. My suggestion to disable the testcache for builders is because of the time overhead in saving testcache input information (involving sometimes huge numbers of `os.Stat` calls) which will never be used.

**Comment by bcmills** [comment]
`greplogs -l -e '(?ms)\Aplan9-arm .* disk is full' --since=2022-01-28`

(0 matching logs)
