### ISSUE TITLE
x/pkgsite: package removal request for github.com/VanMoof/tenjin-assets

### ISSUE THREAD

**Issue by mariebtreschow** [golang/go#50850]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/VanMoof/tenjin-assets@v0.0.4#readme-tenjin-assets
 
 
 
### Are you the owner of this package?
Yes

 
### What is the reason that you could not retract this package instead?
used internally

**Comment by jamalc** [comment]
I don't see you listed under the GitHub org for VanMoof. Is there some way you could demonstrate ownership over this package or could you use the [retract directive](https://go.dev/ref/mod#go-mod-file-retract) instead?

**Comment by jamalc** [comment]
I see the repo is private, archived, or deleted. I'll proceed with removal of the docs. As an FYI, this module will still persist in the module proxy.
