### ISSUE TITLE
x/tools/gopls: build mod diagnostics with GOWORK=off

### ISSUE THREAD

**Issue by findleyr** [golang/go#50862]
gopls relies on errors produced by the go command to suggest fixes to our users, but when using go.work, we don't get all of these errors. We can work around this by running `go` commands with `-workfile=off` to build our diagnostics.

Example (based on `gopls/internal/regtest/workspace.TestUseGoWork`):
```
[workspace]> ls -R
.:
go.work  moda  modb  tags

./moda:
a

./moda/a:
a.go  go.mod  go.sum

./modb:
b.go  go.mod  go.sum
[workspace]> cat ./modb/go.mod
module b.com

require golang.org/x/tools v0.1.9
[workspace]> cat ./moda/a/go.mod
module a.com

require b.com v1.2.3
[workspace]> cd modb
[modb]> GOPROXY=off go list all
../moda/a/a.go:4:2: b.com@v1.2.3: module lookup disabled by GOPROXY=off
[modb]> GOPROXY=off go list -workfile=off all
go: golang.org/x/tools@v0.1.9: module lookup disabled by GOPROXY=off
go: golang.org/x/tools@v0.1.9: module lookup disabled by GOPROXY=off
```

CC @matloob

**Comment by bcmills** [comment]
> `b.com@v1.2.3: module lookup disabled by GOPROXY=off`

That error message looks deeply wrong to me. `module lookup disabled` should imply that we are looking up an imported package, but `b.com@v1.2.3` implies that the module containing the package is already known. We should either get a `module@version` in the error or a `module lookup disabled`, but never both in the same error.

**Comment by bcmills** [comment]
(That is: I agree that there is at least one bug here, but it may be more fundamental than workspace mode. 😅)

**Comment by findleyr** [comment]
Some more interesting behavior! For some reason `-e -json` behaves quite differently with `-workfile=off`.

```
[modb]> GOPROXY=off go list -e -json b.com/...
{
        "Dir": "/home/rfindley/tmp/workspace/modb",
        "ImportPath": "b.com",
        "Name": "b",
        "Root": "/home/rfindley/tmp/workspace/modb",
        "Module": {
                "Path": "b.com",
                "Main": true,
                "Dir": "/home/rfindley/tmp/workspace/modb",
                "GoMod": "/home/rfindley/tmp/workspace/modb/go.mod"
        },
        "Match": [
                "b.com/..."
        ],
        "Stale": true,
        "StaleReason": "build ID mismatch",
        "GoFiles": [
                "b.go"
        ]
}
{
        "ImportPath": "b.com/...",
        "Match": [
                "b.com/..."
        ],
        "Incomplete": true,
        "Error": {
                "ImportStack": [],
                "Pos": "",
                "Err": "b.com@v1.2.3: module lookup disabled by GOPROXY=off"
        }
}
[modb]> GOPROXY=off go list -e -json -workfile=off b.com/...
go: golang.org/x/tools@v0.1.9: module lookup disabled by GOPROXY=off
go: golang.org/x/tools@v0.1.9: module lookup disabled by GOPROXY=off
```

**Comment by findleyr** [comment]
@bcmills @matloob is it valid to depend on this behavior from `go list`, that errors will be embedded in synthetic package results corresponding to the query string?

i.e. this result:
```
{
        "ImportPath": "b.com/...",
        "Match": [
                "b.com/..."
        ],
        "Incomplete": true,
        "Error": {
                "ImportStack": [],
                "Pos": "",
                "Err": "b.com@v1.2.3: module lookup disabled by GOPROXY=off"
        }
}
```

It works, and solves our problem, but feel rather incorrect.

**Comment by bcmills** [comment]
Hmm. In general if we can't determine the import path(s) for a pattern we should report an error for that pattern, so that should be safe to rely on.

I agree that it feels a bit iffy, but I think the only better alternative might be to omit the `ImportPath` field entirely for the error, and I'm not sure that's any better for tools. 😅
