### ISSUE TITLE
During tests, minor changes to code results in [no test files]

### ISSUE THREAD

**Issue by runar-rkmedia** [golang/go#50871]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18beta1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes (1.18beta1)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/runar/.cache/go-build"
GOENV="/home/runar/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/runar/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/runar/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/runar/sdk/go1.18beta1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/runar/sdk/go1.18beta1/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18beta1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/runar/gits/personal/skiver/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build471430461=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.18beta1 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.18beta1
uname -sr: Linux 5.16.2-arch1-1
/usr/lib/libc.so.6: GNU C Library (GNU libc) release release version 2.33.
</pre></details>

### What did you do?

I run my tests in a watcher, so I see the output on every save (I have verified that the issue persists without the watcher). 

One of my tests was failiing (TDD), giving me the expected error. If I uncommend/comment the line [./bboltStorage/category.go81](https://github.com/runar-rkmedia/skiver/blob/fde8f0088c4876f2045914f62233758797f57118/bboltStorage/category.go#L81), the error occurs / dissappears.

I have a repo which reproduces the error on this commit: https://github.com/runar-rkmedia/skiver/commit/fde8f0088c4876f2045914f62233758797f57118

```shell-script
git clone git@github.com:runar-rkmedia/skiver.git
git checkout fde8f0088c4876f2045914f62233758797f57118
go test ./...
```

### What did you expect to see?

My tests running, like this:

```
❯ go test ./...
?   	github.com/runar-rkmedia/skiver	[no test files]
# Running tests with Testza
## Using seed "1643321233933095887" for random operations
## System info: OS=linux | arch=amd64 | cpu=Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz | go=go1.18beta1

createdAt: "2022-01-27T23:07:13.937464229+01:00"
createdBy: jimb
id: id-8
key: ___root___
project_id: id-7
title: ""

 id-8
--- FAIL: TestSubCategory (0.00s)
    mock.go:25: Created temporary db-file /tmp/mockdb-skiver-1164937872
    sub_category_test.go:31: id-7
    mock.go:27: Cleaned up temporary db-file /tmp/mockdb-skiver-1164937872
panic: createdAt: "2022-01-27T23:07:13.937464229+01:00"
createdBy: jimb
id: id-8
key: ___root___
project_id: id-7
title: ""
 [recovered]
	panic: createdAt: "2022-01-27T23:07:13.937464229+01:00"
createdBy: jimb
id: id-8
key: ___root___
project_id: id-7
title: ""


goroutine 35 [running]:
testing.tRunner.func1.2({0x6e2520, 0xc000242ba0})
	/home/runar/sdk/go1.18beta1/src/testing/testing.go:1360 +0x24e
testing.tRunner.func1()
	/home/runar/sdk/go1.18beta1/src/testing/testing.go:1363 +0x39f
panic({0x6e2520, 0xc000242ba0})
	/home/runar/sdk/go1.18beta1/src/runtime/panic.go:838 +0x207
github.com/runar-rkmedia/skiver/bboltStorage.(*BBolter).CreateSubCategory.func1({{{0x37e091a5, 0xed9850e91, 0x96b2a0}, 0x0, {0xc000240318, 0x4}, {0xc00024031c, 0x4}, {0x0, 0x0}, ...}, ...})
	/home/runar/gits/personal/skiver/bboltStorage/category.go:84 +0x30a
github.com/runar-rkmedia/skiver/bboltStorage.Update[...].func1()
	/home/runar/gits/personal/skiver/bboltStorage/generics.go:142 +0x255
go.etcd.io/bbolt.(*DB).Update(0x0?, 0xc0002206b8)
	/home/runar/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:741 +0x82
github.com/runar-rkmedia/skiver/bboltStorage.Update[...](0xc0001f2140, {0x93f6a8, _, _}, {_, _}, _)
	/home/runar/gits/personal/skiver/bboltStorage/generics.go:126 +0x171
github.com/runar-rkmedia/skiver/bboltStorage.(*BBolter).CreateSubCategory(_, {_, _}, {_, _}, {{{0xc074e3c477e6ec9c, 0x5f5220, 0x96b2a0}, 0x0, {0xc000211e48, ...}, ...}, ...})
	/home/runar/gits/personal/skiver/bboltStorage/category.go:70 +0x6e5
github.com/runar-rkmedia/skiver/bboltStorage.TestSubCategory(0xc0001cc680)
	/home/runar/gits/personal/skiver/bboltStorage/sub_category_test.go:40 +0xc9b
testing.tRunner(0xc0001cc680, 0x76a108)
	/home/runar/sdk/go1.18beta1/src/testing/testing.go:1410 +0x102
created by testing.(*T).Run
	/home/runar/sdk/go1.18beta1/src/testing/testing.go:1457 +0x35f
FAIL	github.com/runar-rkmedia/skiver/bboltStorage	0.014s
?   	github.com/runar-rkmedia/skiver/config	[no test files]
?   	github.com/runar-rkmedia/skiver/frontend	[no test files]
ok  	github.com/runar-rkmedia/skiver/handlers	0.030s
ok  	github.com/runar-rkmedia/skiver/importexport	(cached)
?   	github.com/runar-rkmedia/skiver/internal	[no test files]
?   	github.com/runar-rkmedia/skiver/interpolator	[no test files]
ok  	github.com/runar-rkmedia/skiver/interpolator/lexer	(cached)
ok  	github.com/runar-rkmedia/skiver/interpolator/parser	(cached)
?   	github.com/runar-rkmedia/skiver/localuser	[no test files]
ok  	github.com/runar-rkmedia/skiver/models	(cached)
?   	github.com/runar-rkmedia/skiver/requestContext	[no test files]
?   	github.com/runar-rkmedia/skiver/translator	[no test files]
?   	github.com/runar-rkmedia/skiver/types	[no test files]
?   	github.com/runar-rkmedia/skiver/utils	[no test files]
FAIL
```

### What did you see instead?
> ❯ go test ./...
?   	github.com/runar-rkmedia/skiver	[no test files]

**Comment by runar-rkmedia** [comment]
Changing from:

```go
t.SubCategories = append(t.SubCategories, t)

```
to 

```go
ttt := t
ttt.SubCategories = append(t.SubCategories, t)
t = ttt

```

resolves the issues, and returns the correct result... am I missing something here?

**Comment by seankhliao** [comment]
Your code has bugs and isn't returning.
[no test files] is expected for the package at the root because you don't have any tests there.
This doesn't look like a bug in Go.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by runar-rkmedia** [comment]
Looking at this now, it kind of abvious that I accidently created an infinite loop here, by refferring to the wrong variable. Silly me...
