### ISSUE TITLE
go mod import failed

### ISSUE THREAD

**Issue by imChenChen** [golang/go#50873]
![530aea4a45ac28f036174a4f266e921](https://user-images.githubusercontent.com/74757765/151494865-1792d3d7-5541-438f-ba39-89daaf00a005.png)

help me!

**Comment by imChenChen** [comment]
GOPATH=E:\my_docs\tobias-go

**Comment by bokunodev** [comment]
the import path is `github.com/olivere/elastic/v7` please dont use issue tracker for a question.

https://go.dev/help
