### ISSUE TITLE
net/http/cookiejar: The result of Cookies cannot be SetCookies

### ISSUE THREAD

**Issue by molon** [golang/go#50874]
https://github.com/golang/go/blob/9ff00398489d9eb1822b3de028cd6ccf5674ebb3/src/net/http/cookiejar/jar.go#L220-L222

Why here is a simple cookie that only contains Name and Value.
Because sometimes we need to directly operate the jar, such cookies will be of little value in many scenarios.

**Comment by seankhliao** [comment]
Duplicate of #39420
