### ISSUE TITLE
net: TestUDPReadSizeError failure with read of length 0

### ISSUE THREAD

**Issue by bcmills** [golang/go#50870]
```
--- FAIL: TestUDPReadSizeError (0.12s)
    udpsock_test.go:433: got 0; want 19
FAIL
FAIL	net	8.513s
```

`greplogs --dashboard -md -l -e 'FAIL: TestUDPReadSizeError'`

[2022-01-27T19:55:38-1a2435c/darwin-amd64-11_0](https://build.golang.org/log/9f98621fff75f29a9ec5bf364a7bd69ee862c851)

The assertion is from this section of the test:
https://cs.opensource.google/go/go/+/master:src/net/udpsock_test.go;l=420-432;drc=b55cbbb9e76969d67fbc6e264a584ad18c2f95fa

The test was added in [CL 92475](https://go.dev/cl/92475) (CC @m4ns0ur), and this is the first such failure I can find in the logs.

The test appears to accept a `Timeout` error on any platform — or any error at all on Windows — but then still expects the `Read` to have returned an exact number of bytes. However, it's not clear to me how we can be sure that the `Write` has actually made it through the kernel before the timeout fires.

**Comment by mknyszek** [comment]
CC @neild
