### ISSUE TITLE
Increase the possibility of setting constants

### ISSUE THREAD

**Issue by kostyaBro** [golang/go#50875]
I propose to expand the possibilities of setting constants.
For example `partitionSize = (7 * 24 * time.Hour).Nanoseconds()` is the constant, but compiler think that it's not constant.

One solution, that I can see - check `reflect.Kind` type of all variables in the expression. If all types are primitives - it's constant.

**Comment by seankhliao** [comment]
It's non constant because of the method call to `Nanoseconds()`, not because of `time.Hour`,
Having const inputs into a function doesn't guarantee that it's side effect free and the result is const.

Side note: `const partitionSize = int64(7 * 24 * time.Hour)` works.
