### ISSUE TITLE
x/pkgsite: pressing the 'X' button doesn't close the search dialogue

### ISSUE THREAD

**Issue by katiehockman** [golang/go#50895]
### What is the URL of the page with the issue?
 
 All package pages (my screenshot is of: https://pkg.go.dev/crypto/tls)
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
 
### Issue

Pressing the 'X' button on the search dialogue doesn't close the dialog box. Pressing 'Esc' does that correctly, though.

To reproduce, go to https://pkg.go.dev/crypto/tls, press 'F' to open the search dialogue, then press the 'X' button in the top right corner of the dialogue.

/cc @golang/pkgsite

**Comment by jamalc** [comment]
I'm having trouble reproducing this issue. Is it still happening on all pages?

**Comment by katiehockman** [comment]
Yes it's still happening, but for some reason it doesn't reproduce if I use Chrome logged on with corp. Try using an incognito window to reproduce it, since that seems to consistently show the problem for me.
