### ISSUE TITLE
x/build/cmd/release: darwin-amd64 release tests aren't passing, cmd/go's TestScript/cgo_stale_precompiled fails

### ISSUE THREAD

**Issue by mknyszek** [golang/go#50892]
When working on the `go1.18beta2` release via releasebot (`releasebot -mode=prepare go1.18beta2`) I discovered two consecutive failures of the form:

```
go test proxy running at GOPROXY=http://127.0.0.1:51540/mod
--- FAIL: TestScript (0.02s)
    --- FAIL: TestScript/cgo_stale_precompiled (0.66s)
        script_test.go:257:
            # Regression test for https://go.dev/issue/47215 and https://go.dev/issue/50183:
            # A mismatched $GOROOT_FINAL or missing $CC caused the C dependencies of the net
            # package to appear stale, and it could not be rebuilt due to a missing $CC. (0.000s)
            # Control case: net must not already be stale. (0.654s)
            > ! stale net
            FAIL: testdata/script/cgo_stale_precompiled.txt:8: net is unexpectedly stale
```

I tried to get a third failure, but instead the buildlet hung along with others as per #50890. That issue also has the complete output of both failures produced by releasebot.

This issue seems potentially related to #48319 which included a fix that included a whole bunch of the same keywords that appear in the failure (https://golang.org/cl/380915).

CC @dmitshur @toothrot @bcmills

**Comment by mknyszek** [comment]
The failure just reproduced a third time in a row for a complete run. I think this is now blocking the beta.

**Comment by dmitshur** [comment]
Reproduced this locally just by setting `GOROOT_FINAL` to a non-empty string while running the test. Filed #50893 with details for that.

**Comment by bcmills** [comment]
This is another failure due to the same root cause as #46347. I'll rewrite the test to use the same approach as in https://go.dev/cl/c/go/+/322629/5/src/cmd/go/testdata/script/cgo_stale.txt, and follow up with one or more issues to align either the default behavior of `make.bash` or the dashboard builders with the behavior required by `cmd/release`.
