### ISSUE TITLE
text/scanner: hangs with IsIdentRune

### ISSUE THREAD

**Issue by wxolp** [golang/go#50909]
### What version of Go are you using (`go version`)?

~~~
go version go1.17 windows/amd64
~~~

### What did you do?

If I have this code:

~~~go
package main

import (
   "strings"
   "text/scanner"
)

func main() {
   src := strings.NewReader("hello\nworld\n")
   var s scanner.Scanner
   s.Init(src)
   s.IsIdentRune = func(ch rune, i int) bool {
      return ch != '\n'
   }
   s.Whitespace = 1<<'\n'
   for s.Scan() != scanner.EOF {
      println(s.TokenText())
   }
}
~~~

The program will print the two lines, but then it just hangs forever. I see this in the docs:

> The set of valid characters must not intersect with the set of white space characters.

but it seems that I am following the direction given.

1. https://godocs.io/text/scanner#Scanner.IsIdentRune

**Comment by seankhliao** [comment]
It looks like `IsIdentRune` is called with `scanner.EOF` and it goes into an infinite loop?

**Comment by seankhliao** [comment]
cc @griesemer

**Comment by griesemer** [comment]
If you change your `IsIdentRune` function to:
```Go
func(ch rune, i int) bool {
        return ch != '\n' && ch != scanner.EOF
}
```
it will work. Should be good enough as a work-around for now. (As an aside, for this example you don't need to set `IsIdentRune` nor `Whitespace`.)

The code using `IsIdentRune` should probably check for `EOF`. This appears to have been like this for a long time, so not a regression. Marking for 1.19.

**Comment by wxolp** [comment]
> If you change your `IsIdentRune` function to:
> 
> ~~~go
> func(ch rune, i int) bool {
>         return ch != '\n' && ch != scanner.EOF
> }
> ~~~
> 
> it will work.

Yes thank you, on another forum someone made that suggestion as well, seems like a good workaround.

> Should be good enough as a work-around for now. (As an aside, for this example you don't need to set `IsIdentRune` nor `Whitespace`.)

Yes, my example is probably not great, but I'm sure you could imagine a practical real world example that would have the same issue.

> The code using `IsIdentRune` should probably check for `EOF`.

Yes, I was thinking either this. You could argue for leaving the code as is, and just updating the documentation. However I don't think that's a good idea, as I don't really see EOF as being "whitespace", so in my opinion it is an issue with the code. Thanks again.
