### ISSUE TITLE
cmd/compile: int is not a type

### ISSUE THREAD

**Issue by chai2010** [golang/go#50902]
```Go
package main

var int int

func main() {}
```

https://go.dev/play/p/Q_9nl4PXV-_3

**Comment by go101** [comment]
By spec, the two `int`s are both the declared variable.

**Comment by beoran** [comment]
It is true that this error message is a bit confusing. What it means is that int is a reserved name for a type and you cannot name variables int.

Maybe an error message like this would be better:

/prog.go:7:9: int is not a valid variable name

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by beoran** [comment]
@seankhliao Maybe it is a bit soon to close this as a question? The error message really seems confusing, and I think that for Go it always has been a point of pride to provide clear error messages. Certainly in this case the message could be improved.

**Comment by seankhliao** [comment]
`int` is a valid variable name, but declaring it as a variable precludes shadows the its predeclared definition as a type.
eg: `var int bool` is valid.
The character offset `9` points to that.

**Comment by seankhliao** [comment]
Duplicate of #20219

**Comment by beoran** [comment]
Well, seeing the discussion in the liked issue i guess it is hard to improve the message. I will let it pass.
