### ISSUE TITLE
cmd/compile: spurious line info added to interface satisfaction error

### ISSUE THREAD

**Issue by rsc** [golang/go#50907]
```
% cat /tmp/x.go
package p

import (
	"fmt"
	"strings"
)

func main() {
	var b strings.Builder
	fmt.Fprintf(b, "hello")
}
% go tool compile -G=0 /tmp/x.go
/tmp/x.go:10:13: cannot use b (type strings.Builder) as type io.Writer in argument to fmt.Fprintf:
	strings.Builder does not implement io.Writer (Write method has pointer receiver)
% go tool compile /tmp/x.go
/tmp/x.go:10:14: cannot use b (variable of type strings.Builder) as type io.Writer in argument to fmt.Fprintf:
	strings.Builder does not implement io.Writer (Write method has pointer receiver) at $GOROOT/src/strings/builder.go:88:19
% 
```

The `$GOROOT` makes the added line info not useful.
I am not sure where that's coming from. 
But it's probably also just not useful in general:
much of the time, the type will be in a dependency
somewhere, and the user is not really helped
by printing the path of some file in the module cache.

The "at ..." should be deleted.

Not a beta blocker.

**Comment by AGMETEOR** [comment]
@rsc do you mind if I work on this incase it's not too complicated for a beginner contributor?

**Comment by ianlancetaylor** [comment]
@AGMETEOR Feel free to take a look, but it's very likely that this will be fixed by one of the compiler developers in a week or two.

**Comment by ianlancetaylor** [comment]
CC @griesemer @findleyr

**Comment by griesemer** [comment]
This was introduced by [CL 373634](https://go-review.googlesource.com/c/go/+/373634) which fixed two issues that wanted the line info...

Will remove.
