### ISSUE TITLE
x/pkgsite: redirect bug

### ISSUE THREAD

**Issue by dipuhasan** [golang/go#50900]
Do you have bug bounty?

Redirect url:
https://pkg.go.dev///%5Cexample.com/
https://pkg.go.dev///%5Cgoogle.com/
https://pkg.go.dev///%5Cevil.com/

Thanks

**Comment by mvdan** [comment]
cc @jba

**Comment by seankhliao** [comment]
Note this appears to be browser specific (doesn't work with curl), treating `Location: /\example.com` as `example.com`
https://bugs.chromium.org/p/chromium/issues/detail?id=500610

**Comment by ianlancetaylor** [comment]
@dipuhasan This is an open source project.  We don't have a bug bounty.  But thanks for reporting the problem.
