### ISSUE TITLE
cmd/compile: error message when comparing structs containing slices less helpful in go1.18

### ISSUE THREAD

**Issue by sarnesjo** [golang/go#50918]
In Go, slices are not comparable using `==`. The same is true for structs containing slices. ([spec](https://go.dev/ref/spec#Comparison_operators))

Using `go1.17.6`, this is reported with an error message that clearly states what is wrong:

```
./prog.go:13:7: invalid operation: a == b (struct containing []string cannot be compared)
```

Using `go1.18-a5c0b19080`, however, the error message is less helpful:

```
./prog.go:13:5: invalid operation: cannot compare a == b (operator == not defined on thing)
```

This can be reproduced on the Go Playground, by switching between "Go release" and "Go dev branch": https://go.dev/play/p/kvCNFuMZzOF

**Comment by ALTree** [comment]
Thanks for reporting this. The 1.17 error message is indeed quite better.

cc @griesemer
