### ISSUE TITLE
x/pkgsite: package removal request for github.com/jaehonam/go-yfinance

### ISSUE THREAD

**Issue by hadooboo** [golang/go#50926]
### What is the path of the package that you would like to have removed?

 

github.com/jaehonam/go-yfinance
 
### Are you the owner of this package?

yes
 
### What is the reason that you could not retract this package instead?

I've changed my github profile name and will not use this repo
(copied all contents to github.com/hadooboo/yfinance)

**Comment by jamalc** [comment]
Done.
