### ISSUE TITLE
x/build: surface port maintainers on dev.golang.org

### ISSUE THREAD

**Issue by bcmills** [golang/go#50933]
https://dev.golang.org/owners currently lists code owners for a large subset of packages in the Go project.

However, when it comes to tracking down build and test failures, code owners are only half of the story. Our [requirements for a new port](https://go.dev/wiki/PortingPolicy#requirements-for-a-new-port) also require that “[a]t least one developer must be named (and agree) to maintain the port, by making required updates in a timely manner as architecture or operating system requirements change.”

When we spot a port-specific issue, we need to know who to loop in to make the updates needed to resolve that issue.

Some of that information is currently embedded in the `Owners` field for the builder information in [`x/build/dashboard/builders.go`](https://cs.opensource.google/go/x/build/+/master:dashboard/builders.go), but:
* that information is difficult to find within the file,
* the file itself is not particularly discoverable, and
* nothing guarantees that the owner of the builder is the owner for the corresponding port.

Either `dev.golang.org/owners` or a similar page on `dev.golang.org` should identify port owners explicitly by `GOOS` and `GOARCH`.

(CC @golang/release for prioritization)

**Comment by bcmills** [comment]
(This issue may be a duplicate, but if so I couldn't find the issue it's a duplicate of. 😅)

**Comment by seankhliao** [comment]
this? #28596

**Comment by bcmills** [comment]
Duplicate of #28596
