### ISSUE TITLE
math/big: big.Int.MarshalJSON produces invalid json for nil

### ISSUE THREAD

**Issue by Snaipe** [golang/go#50940]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/snaipe/.local/var/cache/go-build"
GOENV="/home/snaipe/.local/etc/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/snaipe/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/snaipe/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/snaipe/b5/src/snai.pe/boa/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3656356402=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.com/p/Zz6ueutEwo7

### What did you expect to see?

MarshalJSON should return the JSON `null` value.

### What did you see instead?

MarshalJSON instead returns `<nil>` with no error, which is invalid JSON. At the very least, if MarshalJSON should not return `null` for nil `*big.Int`, an error should be returned rather than producing invalid JSON.

**Comment by nightlyone** [comment]
Should the big.Int.Unmarshal also parse this somehow to keep it symmetrical?

**Comment by Snaipe** [comment]
`big.Int.UnmarshalJSON` [already parses `null`](https://github.com/golang/go/blob/master/src/math/big/intmarsh.go#L76) so this would make things more consistent, as you pointed out.
