### ISSUE TITLE
net: skipped error check

### ISSUE THREAD

**Issue by komkom** [golang/go#50946]
### What version of Go are you using (`go version`)?

<pre>
$ go version

master

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> linux</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Checked the go source with a linter

### What did you see instead?

In the file net/dnsclient_unix.go in the function newRequest error handling is missing after calling b.Finish(). If the implementation of dnsmessage.Builder.Finish changes it is theoretically possible that the missing error handling introduces a nil pointer exception.

**Comment by ianlancetaylor** [comment]
Thanks.  It's not necessary to open an issue for a simple code fix if you are going to send the fix anyhow.  It's OK to just send the fix.  Thanks for doing this.
