### ISSUE TITLE
x/tools/gopls: create gopls-release-branch.0.8

### ISSUE THREAD

**Issue by findleyr** [golang/go#50957]
We are using the v0.8.0 milestone for Go 1.18 support. This milestone is scheduled for the end of February, but we'd like to start cutting prereleases soon as we add features.

Could someone on @golang/release assist with creating the new branch? Thanks.

**Comment by dmitshur** [comment]
Of course.

What would you like the branching point to be, the latest commit on the `master` branch? Is creating it today okay?

**Comment by findleyr** [comment]
> What would you like the branching point to be

The latest commit on `master` works.

> Is creating it today okay?

Yes, not super urgent but creating it today would be great.

Thanks!

**Comment by dmitshur** [comment]
Ok, I've created a new branch named `gopls-release-branch.0.8` in x/tools (next in sequence following the existing `gopls-release-branch.0.7` branch). Its initial commit was golang/tools@461d130035e971840054f875ee8e9da69440af8f:

https://go.googlesource.com/tools/+/refs/heads/gopls-release-branch.0.8

If something's not right, please comment or reopen.

I suspect owners of gopls may have an existing path to create these branches, so if asking us becomes too tedious, we can explore that next time.

**Comment by findleyr** [comment]
> so if asking us becomes too tedious, we can explore that next time.

I think it is only tedious for the release team, who must deal with the interrupt. Let me know if this workflow doesn't work for you :)
