### ISSUE TITLE
go/types, types2: review error messages

### ISSUE THREAD

**Issue by griesemer** [golang/go#50954]
Reminder issue.
- In some cases the Go 1.17 compiler produced better (more detailed) error messages than `go/types`, `types2`. Fix those cases.
- Remove the difference between compiler and type checker error messages.
- Review general format of error messages (use of `:` vs `()`) and normalize it.

cc: @findleyr

**Comment by OladapoAjala** [comment]
@griesemer I'd like to work on this issue. Kindly assign it to me and share more resources (if any) to get me started.

**Comment by griesemer** [comment]
Thanks, @OladapoAjala for your interest here. This is an area which we (the Go team) should address and own because it requires potential changes in the compiler's existing tests, `types2`, `go/types`, and changes to the error handling machinery (which are currently in progress), as well as determining a model for error message formats, requiring lots of communication between stakeholders.

If you want to contribute elsewhere, please look for issues labeled with "help wanted". Generally, due to ongoing development in the type checkers, those are not good areas for larger changes at the moment (smaller bug fixes are always welcome, though).

Thanks.

**Comment by OladapoAjala** [comment]
@griesemer thank you for the detailed response. I'd look around for issues I can contribute to, regards.

**Comment by griesemer** [comment]
In the meantime, the differences between compiler and type checker error messages have been removed.
We also continue to add missing information where Go 1.17 produced better error messages (case-by-case basis).
Finally, regarding the error format (":" vs "()" for clarifications): some of it is historic. We don't have a "grand unifying theory" for error message formatting but we're making it more regular in small steps.
Closing this as mostly done.
