### ISSUE TITLE
github: wiki isn't up to date with the decision to include generics

### ISSUE THREAD

**Issue by hayunofek** [golang/go#50966]
### What is the URL of the page with the issue?
https://github.com/golang/go/wiki

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0

### Screenshot

![image](https://user-images.githubusercontent.com/79948779/152129235-e7e2b583-22db-449b-8396-afced05bd0a2.png)

### What did you do?

Went into the GitHub Golang's wiki page.

### What did you expect to see?
I expected to not see a reference to a page which describes why Go doesn't use generics, since from Go 1.18 (not finalized yet, I know) Generics are a part of the programming language and this piece of information could be misleading to newcomers thinking that Generics aren't a part of Go/ about to be a part of Go.

### What did you see instead?
A reference to a summary of the discussion as to why Generics aren't included as part of the programming language.
Under https://github.com/golang/go/wiki#additional-go-programming-wikis it's the first point.

Apologies in advance for picking this topic for the issue, I haven't found any issue type that is concerning the GitHub wiki documentation.

**Comment by ALTree** [comment]
Thanks for reporting this. I've simply delete the link, since it pointed to a recap doc that is no longer current. People who wish to know the status quo about generic will be able to find a section in the FAQs after 1.18 is published.
