### ISSUE TITLE
cmd/go: 'go env' takes 5+ seconds on my Mac

### ISSUE THREAD

**Issue by rsc** [golang/go#50982]
I don't know why, but 'go env' regularly takes 5+ seconds on my MacBook Pro, and it's really annoying.
A second 'go env' shortly thereafter is quick.
I suspect the time is going into invoking clang to determine which flags are valid.
I wonder if we are doing that wrong, or if we can avoid it more often?
I also wonder whether this is due to some kind of antivirus/execution "safety" thing on my Mac that forgets that clang is OK.
But I don't know for sure it's clang at all.

Is anyone else seeing this?

**Comment by matloob** [comment]
I'm seeing this too.

**Comment by jfesler** [comment]
Observed ~2 seconds initial delay on `Mac mini (M1, 2020)`, and no perceivable delay on followup runs.

**Comment by beoran** [comment]
I just tried it on the work Mac and I also see this.

**Comment by robpike** [comment]
I just tested and got 7.5 seconds!

**Comment by juev** [comment]
I just tested several times and got:

```bash
> time go env
...
go env  0.05s user 0.05s system 74% cpu 0.126 total
```

**Comment by night-codes** [comment]
macOS 12.0.1 / MacBook Pro M1:
go env 0.04s user 0.19s system 82% cpu 0.278 total

**Comment by seankhliao** [comment]
It could also be a check on `go` itself and not `clang`, perhaps by macos gatekeeper

**Comment by hyangah** [comment]
Probably not `go` itself. 
I ran `go env GOOS` or `go env GOARCH` or `go env GOPROXY` before trying `go env`. The answer was immediate.
Then, I ran `go env`. That took good 5sec.

**Comment by vatine** [comment]
Just tried on my Mac (more data points, probably not hurtful):

```
% time go env
...
go env  0.08s user 0.20s system 49% cpu 0.570 total
% go version
go version go1.17.5 darwin/amd64
```
