### ISSUE TITLE
misc/cgo/test: failure with gcc 10

### ISSUE THREAD

**Issue by bsiegert** [golang/go#50987]
Example build log: https://build.golang.org/log/193a8f825e6a894f5e435df6958df8ad54a97306

I added a `netbsd-arm64-bsiegert` machine running a current development snapshot of NetBSD. Its gcc is version 10.3.0.

At the end of a test run, the cgo tests fail because of a warning generated by the verification for issue #5242:

```
##### ../misc/cgo/test
# misc/cgo/test
./test.go: In function 'issue5242':
./test.go:377:5: note: parameter passing for argument of type 'bar' changed in GCC 9.1
  377 | int issue5242(foo f, bar b) {
      |     ^~~~~~~~~
go build misc/cgo/test: C compiler warning promoted to error on Go builders
FAIL	misc/cgo/test [build failed]
2022/02/03 08:04:06 Failed: exit status 1
# misc/cgo/test
./test.go: In function 'issue5242':
./test.go:377:5: note: parameter passing for argument of type 'bar' changed in GCC 9.1
  377 | int issue5242(foo f, bar b) {
      |     ^~~~~~~~~
go build misc/cgo/test: C compiler warning promoted to error on Go builders
FAIL	misc/cgo/test [build failed]
2022/02/03 08:04:08 Failed: exit status 1
go tool dist: FAILED
```

This is due to a bugfix in how bitfields are passed by value in gcc 9.1, which technically breaks the ABI. 

Since this is precisely the case that is being tested, I don't see how the code could be changed to prevent the warning. We could pass `-Wno-psabi` to gcc maybe?

/cc @ianlancetaylor @mdempsky

**Comment by ianlancetaylor** [comment]
I think `-Wno-psabi` is the way to go.  Thanks.  Sent you a CL.

**Comment by bcmills** [comment]
@gopherbot, please backport to Go 1.17. The `netbsd-arm64-bsiegert` builder is currently failing on the release branch due to this issue.
