### ISSUE TITLE
cmd/compile: internal compiler error: width not calculated: go.shape.struct { Next *"".Node[go.shape.uint64_0] }_0

### ISSUE THREAD

**Issue by mishapoiuytrewq** [golang/go#50993]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18beta2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/misha/.cache/go-build"
GOENV="/home/misha/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/misha/.asdf/installs/golang/1.18beta2/packages/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/misha/.asdf/installs/golang/1.18beta2/packages"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/misha/.asdf/installs/golang/1.18beta2/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/misha/.asdf/installs/golang/1.18beta2/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18beta2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/misha/GolandProjects/test/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build351429637=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://go.dev/play/p/dRgjhsNTE8H?v=gotip
run <pre>$ go test . --race</pre>

### What did you expect to see?
<pre>
?       main    [no test files]
</pre>
### What did you see instead?
<pre>
# main
./main.go:10:2: internal compiler error: width not calculated: go.shape.struct { Next *"".Node[go.shape.interface {}_0] }_0
</pre>

**Comment by randall77** [comment]
Some type isn't sized correctly when running with checkptr.
```
go tool compile -d checkptr main.go
```
