### ISSUE TITLE
runtime: "fatal: systemstack called from unexpected goroutine" on Android

### ISSUE THREAD

**Issue by bcmills** [golang/go#51001]
```
#!watchflakes
post <- builder ~ `android` && `systemstack called from unexpected goroutine`
```

`greplogs --dashboard -md -l -e '^fatal: systemstack called from unexpected goroutine' --since=2021-01-01`

[2022-02-02T21:12:39-53d6a72/android-amd64-emu](https://build.golang.org/log/b2b458781057bd6fc7cb7317526d8d4338dd4320)
```
##### GOMAXPROCS=2 runtime -cpu=1,2,4 -quick
fatal: systemstack called from unexpected goroutineTrap 
exitcode=133
FAIL	runtime	59.879s
```
[2021-10-08T16:26:20-59d4e92-99c1b24/android-amd64-emu](https://build.golang.org/log/5ab35b44181c34407b2093a32ca19a240c0db863)
```
fatal: systemstack called from unexpected goroutineSegmentation fault 
exitcode=139FAIL	golang.org/x/net/publicsuffix	3.419s
```

I'll also note that `badsystemstackMsg` seems to be missing a final newline as of [CL 93659](https://go.dev/cl/93659) (CC @aclements @randall77). 😅

**Comment by bcmills** [comment]
This happened in a TryBot in https://storage.googleapis.com/go-build-log/f1e11825/android-amd64-emu_262486a5.log.

Marking as release-blocker because this affects TryBot runs. Since `android/amd64` is not a [first-class port](https://go.dev/wiki/PortingPolicy#first-class-ports), either the underlying bug can be diagnosed and fixed, or the builder can be removed from the default TryBot set. (I'll leave that choice up to @golang/runtime to decide and implement.)

**Comment by bcmills** [comment]
This may or may not be OS-specific. There is another failure in the builder logs since February, but on `plan9` rather than `android`; it isn't obvious to me whether that is an independent bug.

`greplogs -l -e 'fatal: systemstack called from unexpected goroutine' --since=2022-02-03`
[2022-03-05T21:20:16-e155b03-45f4544/plan9-amd64-0intro](https://build.golang.org/log/55228a33d03276e7c8e995a37a8dcd03377f3f54)

**Comment by bcmills** [comment]
`greplogs -l -e 'fatal: systemstack called from unexpected goroutine' --since=2022-03-06`
[2022-05-03T19:48:07-bccce90/android-arm64-corellium](https://build.golang.org/log/b0616a0bde53c5ae0039bc12934102683961ab2e)

**Comment by mknyszek** [comment]
@golang/runtime This is a second class port, but because it's a trybot, this is a release blocker. Should we consider removing this as a trybot? Is that bringing us enough value?

**Comment by dmitshur** [comment]
I've mailed [CL 407615](https://go.dev/cl/407615) that makes android-amd64-emu a post-submit builder only (in the main repo) while investigation of this issue is underway. If submitted, this issue can be unmarked as a release-blocker for Go 1.19.

**Comment by bcmills** [comment]
Curiously, this does not appear to be arch-specific: we've seen these failures on both `amd64` and `arm64`.

`greplogs -l -e 'fatal: systemstack called from unexpected goroutine' --since=2022-05-04`
[2022-05-20T22:30:37-2b0e457/android-arm64-corellium](https://build.golang.org/log/3080e82db577e4c5be2b2cf7f7052360bb6570c6)

**Comment by prattmic** [comment]
The first failure shows `exitcode=133`. This is likely bash parlance for exiting with signal 5 (SIGTRAP). From `man bash`: `The return value of a simple command is its exit status, or 128+n if the command is terminated by signal n.`

If I recall correctly, Android applies a seccomp syscall filter to (all?) processes. I wonder if we are violating this filter on the throw path, resulting in truncation of the stack trace.

**Comment by prattmic** [comment]
@golang/android do you know if the Android seccomp filters apply to processes on our builders, and if so [which one](https://cs.android.com/android/platform/superproject/+/master:bionic/libc/seccomp/seccomp_policy.cpp;l=273-283;drc=0ee5fb7bc803ecfad90276d39f73696d024e5939;bpv=1;bpt=1)?

**Comment by prattmic** [comment]
No repros of this on 25 gomotes all weekend. I did find #53250, plus several no context SIGSEGVs in the runtime test, like:

```
##### GOMAXPROCS=2 runtime -cpu=1,2,4 -quick
Segmentation fault 
exitcode=139
FAIL»...runtime»19.914s
FAIL
2022/06/05 22:34:10 Failed: exit status 1
```

(Some where in the standard runtime test rather the -cpu variant)

**Comment by bcmills** [comment]
> This isn't a first-class port, so dropping release-blocker.

This port is still run as a default TryBot until/unless [CL 407615](https://go.dev/cl/407615) is merged. IMO known failures on TryBots should still block releases, since they still add testing noise for anyone who uses TryBots on a pending change.

**Comment by bcmills** [comment]
In the interest of decoupling this issue from the Android TryBots in general, I've filed #53377 (as a release-blocker) to decide whether to remove the TryBots or fix their known failure modes.

**Comment by bcmills** [comment]
Summarizing the known failures with this pattern on Android:

`greplogs -l -e '(?ms)\Aandroid-.*^fatal: systemstack called from unexpected goroutine'`
[2022-05-20T22:30:37-2b0e457/android-arm64-corellium](https://build.golang.org/log/3080e82db577e4c5be2b2cf7f7052360bb6570c6)
[2022-05-03T19:48:07-bccce90/android-arm64-corellium](https://build.golang.org/log/b0616a0bde53c5ae0039bc12934102683961ab2e)
[2022-02-02T21:12:39-53d6a72/android-amd64-emu](https://build.golang.org/log/b2b458781057bd6fc7cb7317526d8d4338dd4320)
[2021-10-08T16:26:20-59d4e92-99c1b24/android-amd64-emu](https://build.golang.org/log/5ab35b44181c34407b2093a32ca19a240c0db863)

So it looks like this bug was probably introduced sometime in 2021..?

**Comment by ianlancetaylor** [comment]
Rolling forward to 1.20.

**Comment by heschi** [comment]
[2022-08-25T19:17:14-f64f12f/android-arm64-corellium](https://build.golang.org/log/c94dd2a5edae94663dea1b54fc4abe4b59c9af63)
[2022-08-22T14:48:53-6bdca82/android-arm64-corellium](https://build.golang.org/log/78b4ef767d76d072b92ae3e206bcddec5f1b7948)

**Comment by cherrymui** [comment]
Seems no new failure for some time.

**Comment by bcmills** [comment]
Note that the rate of testing is much lower now because of the freeze. (6 months is a good window size for checking failure rates.)

**Comment by bcmills** [comment]
Still none after the tree reopened. Maybe fixed?
