### ISSUE TITLE
affected/package: path and path/filepath

### ISSUE THREAD

**Issue by blacklat** [golang/go#51009]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

using path: https://go.dev/play/p/O7tj4JTXLQ1
using filepath: https://go.dev/play/p/j54pWYaz4_x

### What did you expect to see?
false

### What did you see instead?
true

### Question:
are you guys have mental problems ?
are these packages written by monkeys ?
if some idiot answers that this path is absolute then he shouldn't even call himself a programmer

**Comment by zyxkad** [comment]
No, I think absolutely path is meaning you **needn't** use the **current path** to get the absolute path _(another words, If you change you path with `cd` for example, the realpath will not change)_
In your case, the path `/../tmp` is an absolute path, because the realpath never change

**Comment by aiotter** [comment]
Absolute pathname is a pathname beginning with a single or more than two slashes. `/../tmp` is an absolute pathname.
See https://pubs.opengroup.org/onlinepubs/9699919799/

**Comment by seankhliao** [comment]
Please keep our [code of conduct](https://go.dev/conduct) in mind when filing issues.

This works as intended, as explained above.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by blacklat** [comment]
if you guys think this path is absolute then the conversation is over, there's no way to argue with people who don't know what they're saying

**Comment by randall77** [comment]
@blacklat If you think the path should not be considered absolute, then give us an argument as to why. Just stating the code returns the wrong answer without explaining why doesn't help.

I think it should be considered absolute because `ls /../tmp` and `ls /tmp` both do the same thing on my mac. And the result doesn't depend on my working directory.

**Comment by blacklat** [comment]
are you retarded? absolute path does not contain "." or "..", contains only the direct path, do you know the meaning of the word absolute ?
/tmp = absolute path
/../tmp = not absolute

I'm an elite coder, advanced programmer, don't make me explain what absolute path is for kids.

**Comment by randall77** [comment]
@blacklat I think you're thinking of canonicalized paths, not absolute paths. https://stackoverflow.com/questions/12100299/whats-a-canonical-path

**Comment by randall77** [comment]
The function `path.Clean` does some amount of canonicalization. Maybe you want `path.Clean(p) == p`?

**Comment by dominikh** [comment]
> if you guys think this path is absolute then the conversation is over

It's over.
