### ISSUE TITLE
cmd/go: invalid flag in #cgo CFLAGS: -F

### ISSUE THREAD

**Issue by zyxkad** [golang/go#51008]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="**"
GOCACHE="**"
GOENV="**"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="**"
GONOPROXY="yes"
GONOSUMDB=""
GOOS="darwin"
GOPATH="**"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2 -std=c17"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2 -std=c++17"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fh/sxp5v53x66j5_p6_9rxtx6b80000gp/T/go-build2886836689=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

package my_cgo

//#cgo CFLAGS: -F /usr/local/my_framework/lib -framework MyFramework
//#cgo LDFLAGS: -F /usr/local/my_framework/lib -framework MyFramework
//
//#include <MyFramework/somefile.h>
import "C"

### What did you expect to see?
Success

### What did you see instead?
go build xxx/xxx/xxx: invalid flag in #cgo CFLAGS: -F
[Finished in 458ms with exit code 1]

---

The option `-F` is actually in `clang`
```
$ clang --help | grep '\-F'
 -F <value>              Add directory to framework include search path
$ clang++ --help | grep '\-F'
 -F <value>              Add directory to framework include search path
```

**Comment by ianlancetaylor** [comment]
Was that the complete error message?  With Go 1.17 the error message should have mentioned https://golang.org/s/invalidflag, which explains how you can work around the problem.

**Comment by zyxkad** [comment]
Yes that's all, but it don't tell me <https://golang.org/s/invalidflag>

**Comment by zyxkad** [comment]
I was running `go test -v ${file}`, and I got it

**Comment by zyxkad** [comment]
I was trying `CGO_CFLAGS_ALLOW`, but it dosen't work
```
$ go env -w CGO_CFLAGS_ALLOW="-F"; echo $?
0
$ go env CGO_CFLAGS_ALLOW
[[GOT EMPTY]]
```

**Comment by bcmills** [comment]
@zyxkad, do you have `CGO_CFLAGS_ALLOW` explicitly set in your process environment? A value in the environment always overrides the value in the `go.env` file.

**Comment by ianlancetaylor** [comment]
From the code it looks like `-F/usr/local/my_framework/lib` will work without any environment variable setting, but we didn't consider the case of `-F /usr/local/my_framework/lib` (with a space after the `-F`).

**Comment by zyxkad** [comment]
> @zyxkad, do you have `CGO_CFLAGS_ALLOW` explicitly set in your process environment? A value in the environment always overrides the value in the `go.env` file.

No, I wasn't, I also try `export CGO_CFLAGS_ALLOW="-F"`
but it always return to me nothing

**Comment by zyxkad** [comment]
> From the code it looks like `-F/usr/local/my_framework/lib` will work without any environment variable setting, but we didn't consider the case of `-F /usr/local/my_framework/lib` (with a space after the `-F`).

Yes, that's work for me, thanks
