### ISSUE TITLE
spec: minor issue with intra-document links

### ISSUE THREAD

**Issue by jdreystadt** [golang/go#51002]
There are some broken intra-document links in The Go Programming Language Specification. There are href references to #assign_op, #ConstSpec, and #MethodName (2 references to this last one).

Fixing #assign_op is easy, change it to #Assignments as this is the only location in the document that discusses Assignment Operators.

I think #ConstSpec should be changed to #Constant_declarations since this is where the Production for ConstSpec is located.

I think #MethodName should be changed to #Interface_types since this is where the Production for MethodName is located.

**Comment by ianlancetaylor** [comment]
Thanks.  Closing as dup of #50915.
