### ISSUE TITLE
go/types, types2: allow choice between reg. expression or not in ERROR test comments

### ISSUE THREAD

**Issue by griesemer** [golang/go#51006]
`go/types` and `types2` (and the `syntax` package) rely on `ERROR` comments in test cases. Such a comment accepts a regular expression pattern that is then matched against the expected error:
```Go
// ERROR regexp pattern
```
Often we just want to see if the error string appears verbatim (as a substring) in the error output, we don't need reg. expression matching. If we could choose a non-regexp string in those cases, we wouldn't need to escape various characters, which would make these `ERROR` comments more readable.

Example:
```Go
// ERROR \*T2 does not implement I1 \(wrong type for method foo\)\n\t\thave foo\(x int\)\n\t\twant foo\(\)
```
would become
```Go
// ERROR *T2 does not implement I1 (wrong type for method foo)\n\t\thave foo(x int)\n\t\twant foo()
```
The non-regexp pattern might be the more common case. Maybe we could have `ERROR` and `ERRORx` (the latter is for regexp. matching).

cc: @findleyr

**Comment by griesemer** [comment]
Per discussion with @findleyr: Let's use `ERROR /regexp/` and `ERROR substring`:
`ERROR /regexp/` means that the error message must match the regular expression `regexp`
`ERROR substring` means that the error message must contain the substring `substring`

**Comment by griesemer** [comment]
@findleyr If the regexp ends in a `*`, the immediately following `/` will end a `/* ERROR` comment prematurely. Example: for regexp `invalid type T .*` we arrive at`/* ERROR /invalid type T .*/ */`. In other words, regexps ending in `*` cannot be written for `/* ERROR`-style comments.

We can live with this (it's rare), or we can chose a different mechanism to distinguish between substring and regexp error patterns (e.g. `ERROR` and `ERRORx`).

**Comment by findleyr** [comment]
Hmm, that's a good point that I hadn't considered.

ERRORx seems like a reasonable alternative to me.
