### ISSUE TITLE
x/tools: analysis does not work if there's a type error even with `RunDespiteErrors: true`

### ISSUE THREAD

**Issue by kdy1** [golang/go#51014]
### What version of Go are you using (`go version`)?

<pre>
❯ go version
go version go1.17.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes. The [problematic code](https://github.com/golang/tools/blob/4da8ceb6f1ad02b6af00ed2d8d62df1d56a07d2f/go/analysis/internal/checker/checker.go#L156-L167) is latest.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kdy1/Library/Caches/go-build"
GOENV="/Users/kdy1/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/kdy1/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/kdy1/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.6/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pw/7l7d6f6s6ngb9z17pc912mtc0000gn/T/go-build3641127775=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```go
package main

import (
	"golang.org/x/tools/go/analysis/multichecker"
	"my.pkg/internal/devtools/fixer/slicefix"
)

func main() {
	//singlechecker.Main(&slicefix.SliceFix)
	multichecker.Main(&slicefix.SliceFix)
}

```

Where slicefix is
```
package slicefix

import (
	"log"

	"golang.org/x/tools/go/analysis"
)

var (
	SliceFix = analysis.Analyzer{
		Name:             "slicefix",
		Doc:              "Auto dereference of slices",
		Run:              run,
		RunDespiteErrors: true,
	}
)

func run(pass *analysis.Pass) (interface{}, error) {
	log.Fatalf("Run")

	return nil, nil
}

```

### What did you expect to see?

I expected the analysis to be run, because I set `RunDespiteErrors` to true.

### What did you see instead?

```
/Users/kdy1/projects/tsc/codemap/loc.go:27:23: invalid argument: arr (variable of type *[]string) for len
fixer: error during loading
```

**Comment by zpavlinovic** [comment]
I was able to reproduce it and got the same issue with copylock analyzer. Working on a fix.
