### ISSUE TITLE
affected/package: time

### ISSUE THREAD

**Issue by roelvandergoot** [golang/go#51010]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.17
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/roel/.cache/go-build"
GOENV="/home/roel/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/roel/go/pkg/mod"
GONOPROXY="gitlab.com/EngineeringSoftware"
GONOSUMDB="gitlab.com/EngineeringSoftware"
GOOS="linux"
GOPATH="/home/roel/go"
GOPRIVATE="gitlab.com/EngineeringSoftware"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3551796939=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
fmt.Println(time.ParseDuration("2d"))
</pre>

### What did you expect to see?

<pre>
2d0h0m0s
</pre>
or
<pre>
48h0m0s
</pre>

### What did you see instead?

<pre>
0s time: unknown unit "d" in duration "2d"
</pre>

### Diff to solve this issue?

<pre>
diff --git a/src/time/format.go b/src/time/format.go
index 5fb9cdc969..1e7a4b9412 100644
--- a/src/time/format.go
+++ b/src/time/format.go
@@ -1500,6 +1500,7 @@ var unitMap = map[string]uint64{
        "s":  uint64(Second),
        "m":  uint64(Minute),
        "h":  uint64(Hour),
+       "d":  uint64(Day),
 }

 // ParseDuration parses a duration string.
</pre>

**Comment by seankhliao** [comment]
> Common durations. There is no definition for units of Day or larger to avoid confusion across daylight savings time zone transitions.

**Comment by roelvandergoot** [comment]
If you are worried about daylight savings you have to do something like `time.Date(2022,2,3,0,0,0,0,time.UTC) - time.Date(2022,2,2,0,0,0,0,time.UTC)` already. That doesn't mean that when somebody says "1d" that he/she means 24 hours 363 days of the year, "23h" one Sunday in March, and "25h" one Sunday in November (in North America). When people say "1d" they mean "24h". Even "1w" should always mean "7d". It starts breaking down with months, "1m" is ambiguous.

Finally, according to your definition "1h" is not always an hour either. Sometimes you have leap seconds. So maybe `time.ParseDuration('1h") should not be allowed either...

**Comment by ianlancetaylor** [comment]
The standard library time package does not support leap seconds, so one hour is always exactly 60 minutes and one minute is always exactly 60 seconds.

By not accepting `1d` in `ParseDuration` we force people to consider how to handle timezone transitions.  That is an intentional decision.

**Comment by roelvandergoot** [comment]
Okay. I'll write my own `parseDuration` then.
