### ISSUE TITLE
`go list ./...` stop scanning because of subfolders

### ISSUE THREAD

**Issue by marxangels** [golang/go#51035]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.3 linux/amd64
</pre>

### What did you do?
`go list ./...`

### What did you expect to see?
`Warning: pattern ./...: open gitea/data/indexers: permission denied`

### What did you see instead?
`pattern ./...: open gitea/data/indexers: permission denied`

------------------------------------------------------------------
If the current user can't access any of the subfolders, `go list ./...` throw `pattern ./...: open xxx: permission denied`,  and stop the scanning. As a result, the output got empty and this will break the following works.

Maybe throwing a `warning` is more appropriate for this, because there may be many subfolders, and it is troublesome to verify the permissions of all folders.

**Comment by marxangels** [comment]
There must be some scenarios that you need to set different owner permissions for subdirectories.

**Comment by seankhliao** [comment]
use `-e` (continue on error)

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by marxangels** [comment]
However, it doesn't make many difference

The -e flag changes the handling of erroneous packages, those that
cannot be found or are malformed. By default, the list command
prints an error to standard error for each erroneous package and
omits the packages from consideration during the usual printing.
With the -e flag, the list command never prints errors to standard
error and instead processes the erroneous packages with the usual
printing. Erroneous packages will have a non-empty ImportPath and
a non-nil Error field; **other information may or may not be missing**
(zeroed).

**Comment by seankhliao** [comment]
An error still seems appropriate, considering you've asked `go` to do something it can't do.

**Comment by marxangels** [comment]
Just wanna simply skip the inaccessible folder instead of interrupting the scanning.
Is such an idea mean too much?
Anyway, thank you very much for the explanation.
