### ISSUE TITLE
math/cmplx: unpredictable sign of 0 calling Sin and Cos for real arguments

### ISSUE THREAD

**Issue by robpike** [golang/go#51034]
[See https://go.dev/play/p/sSDqGhsdp5a
](https://go.dev/play/p/GXDFgG82Zh1)

This program prints `cmplx.Cos` and `cmplx.Sin` for a number of real arguments (imaginary part zero). The result is of course real, but the returned result often has negative zero as the imaginary part. I can't see a pattern, and I'm not sure if it matters or, if so, what the right thing to do is, but I wanted to record it.

In particular, check out this gem:

```
sin (0+0i) (0+0i)
cos (0+0i) (1-0i)
```

**Comment by ianlancetaylor** [comment]
This C program:

```C
#include <stdio.h>
#include <complex.h>

int main() {
  int i;
  for (i = 0; i <= 8; i++) {
    complex x = (complex)((double)(i - 4));
    complex r = csin(x);
    printf("sin %g+%gi %g+%gi\n", creal(x), cimag(x), creal(r), cimag(r));
    r = ccos(x);
    printf("cos %g+%gi %g+%gi\n", creal(x), cimag(x), creal(r), cimag(r));
  }
}
```

prints this:

```
sin -4+0i 0.756802+-0i
cos -4+0i -0.653644+-0i
sin -3+0i -0.14112+-0i
cos -3+0i -0.989992+0i
sin -2+0i -0.909297+-0i
cos -2+0i -0.416147+0i
sin -1+0i -0.841471+0i
cos -1+0i 0.540302+0i
sin 0+0i 0+0i
cos 0+0i 1+-0i
sin 1+0i 0.841471+0i
cos 1+0i 0.540302+-0i
sin 2+0i 0.909297+-0i
cos 2+0i -0.416147+-0i
sin 3+0i 0.14112+-0i
cos 3+0i -0.989992+-0i
sin 4+0i -0.756802+-0i
cos 4+0i -0.653644+0i
```

**Comment by robpike** [comment]
The Go cmplx library gives the same unpredictable signs for the imaginary part. That says we're doing the same as the C environment you are using, but it doesn't exactly say what the right result is

**Comment by robpike** [comment]
What I expected is either always +0i or that the imaginary part has the same sign as the real part. But that is based on surmise, not on what an expert knows and expects.

**Comment by robpike** [comment]
https://twitter.com/rob_pike/status/1490529340907417601 to see if anyone knows what's right here.

**Comment by changkun** [comment]
Not an expert but as far as I remember from school, when computing an inverse elementary function for complex numbers, we need distinguish between -0i and +0i, and `sqrt(-0.841471+0i) != sqrt(-0.841471-0i)`. 

A better question might be: what would experts expect for the result of `sqrt(sin(x+0i))` and `sqrt(sin(x-0i))`, or `log(sin(x+0i))` and `log(sin(x-0i))`, or etc?

I would expect the output sign of zero in imaginary part stay consistent with the input, for instance: Let x be real,
 
1) For `sin(x+0i) = sin(x)+0i`. If `sin(x) < 0`, then `sqrt(sin(x+0i)) = sqrt(sin(x)+0i) = sqrt(-sin(x))i`; if `sin(x) >= 0`, then `sqrt(sin(x+0i)) = sqrt(sin(x))`.
2) For `sin(x-0i) = sin(x)-0i`. If `sin(x) < 0`, then `sqrt(sin(x-0i)) = sqrt(sin(x)-0i) = -sqrt(-sin(x))i`; if `sin(x) >= 0`, then `sqrt(sin(x-0i)) = sqrt(sin(x))`.

**Comment by Rupt** [comment]
They appear to behave as if numerically evaluating the expansions
```
sin(x + iy) = sin(x)*cosh(y) + i*cos(x)*sinh(y)

cos(x + iy) = cos(x)*cosh(y) - i*sin(x)*sinh(y)
```

https://godbolt.org/z/Y535n4fbj

**Comment by n2vi** [comment]
I have not closely studied the Go library yet, but the origin of IEEE Floating Point choices in this regard can be found in Kahan's memo "Branch Cuts for Elementary Functions or Much Ado about Nothing's Sign Bit", which circulated in various versions, for example at https://people.freebsd.org/~das/kahan86branch.pdf.

**Comment by robpike** [comment]
@n2vi Thanks for that link. It's very helpful - if remarkably long and roundabout - and it helped me work out what's going on. The sign of the zero is determined by the sheet of the function approaching the "slit" (as Kahan calls it) in the plane where the function has trouble from a all-is-real-and-simple standpoint.

In the case of cosine, for example, where we see 1-0i, it's because the sign of the imaginary part is negative for complex numbers with small imaginary components and positive real ones. For instance,

```
fmt.Println(cmplx.Cos(0.001 + .001i))
````

prints

```
(0.9999999999998332-9.99999999999989e-07i)
```
Note the large negative exponent on the negative imaginary part.

So the answer is simple and makes sense. Not sure it needed 20+ pages to get there, but I'm happy it's sorted.
