### ISSUE TITLE
go/types: documentation on Type.Underlying needs clarification

### ISSUE THREAD

**Issue by dominikh** [golang/go#51036]
The documentation for (go/types.Type).Underlying says 

> Underlying returns the underlying type of a type w/o following forwarding chains.

but doesn't specify what a "forwarding chain" is. At first hunch one might assume it means `type T1 int; type T2 T1`, but T2's underlying type is `int`.

/cc @findleyr

**Comment by findleyr** [comment]
Thanks, I think this was actually a regression in 1.17, and nobody noticed :(

That commentary about forwarding chains relates to expansion of instances on the RHS of type declaration, and should not leak into the external documentation.

I'll fix this for 1.18.

CC @griesemer
