### ISSUE TITLE
cmd/cgo: const initializer `C: extern const` is not a constant

### ISSUE THREAD

**Issue by zyxkad** [golang/go#51044]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2 -std=c17"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2 -std=c++17"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fh/sxp5v53x66j5_p6_9rxtx6b80000gp/T/go-build3209812224=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### consttest.go
```golang
package testc

// #include "consttest.h"
import "C"

const (
  CONST_VAR int = (int)(C.CONST_VAR)
)
```

#### consttest.h
```c
#ifndef __CGO_CONSTTEST_H__
#define __CGO_CONSTTEST_H__

#ifdef __cplusplus
extern "C"{
#endif // __cplusplus

extern const int CONST_VAR;

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // __CGO_CONSTTEST_H__
```

#### consttest.cpp
```cpp
#include "consttest.h"
const int CONST_VAR = 1;
```

#### consttest_test.go
```golang
package testc_test

import "testing"
import (
  . "localhost/testc"
)

func TestConstVar(t *testing.T){
  t.Log("CONST_VAR:", CONST_VAR)
}
```

### What did you expect to see?
```
=== RUN   TestConstVar
    consttest_test.go:10: CONST_VAR: 1
--- PASS: TestConstVar (0.00s)
PASS
ok  	localhost/testc
```

### What did you see instead?
```
# localhost/testc
./consttest.go:8:3: const initializer int(*_Cvar_CONST_VAR) is not a constant
FAIL	localhost/testc [build failed]
FAIL
```

**Comment by zyxkad** [comment]
If I change `extern const int CONST_VAR;` to `const int CONST_VAR = 1;` it will work.

But in fact, I was mapping c++ enum to golang, I can't use namespace in the header file

**Comment by beoran** [comment]
Afaik, CGO does not support C++. You will have to make a pure C wrapper first

**Comment by zyxkad** [comment]
> Afaik, CGO does not support C++. You will have to make a pure C wrapper first

Yes, I'm making c wrapper, but how can I warp c++ enum to c _(constantly)_?

**Comment by beoran** [comment]
An extern int in C is much like a global variable, so I think that is why it maps to a variable in Go. The concept of a const in Go, where they are compile time constants), and in C(++) where const are in fact run time immutable variable,  is fundamentally different. The one cannot always be mapped to the other.

**Comment by ianlancetaylor** [comment]
A C `extern const` has to be a Go variable, not a Go constant, but beyond that it ought to work.  I haven't tried the test case above, but I don't see why it should fail.  But evidently it does, so this seems like a bug.

**Comment by zyxkad** [comment]
> A C `extern const` has to be a Go variable, not a Go constant, but beyond that it ought to work. I haven't tried the test case above, but I don't see why it should fail. But evidently it does, so this seems like a bug.

I cannot understand why `extern const` is a variable, not a constant.  
Do you worry about how to get the value from C?  
Or because you think It can change when runtime?

**Comment by ianlancetaylor** [comment]
Go does not have the concept of an "external constant."  In Go, all constant values are known at the point where the constant is declared.  When the cgo tool see a C `extern const`, it can only see the header file, not the C file.  It can't see the actual value of the constant.  So there is no way to represent a C `extern const` as a Go `const`.  It can only be represented as a Go variable.

**Comment by zyxkad** [comment]
> 

Ok, I think I can understand now, but It's hard to change my habit, I'll close it now
