### ISSUE TITLE
spec: can't range over parameter constrained by union type

### ISSUE THREAD

**Issue by tinne26** [golang/go#51053]
### What did you do?
Tried to execute this program: https://go.dev/play/p/JdOGVlCgCHh?v=gotip

It's fairly short, but to have the critical code here too:
```
type RuneIterable interface{ string | []rune }
func PrintEach[T RuneIterable](runes T) {
	for _, codePoint := range runes {
		fmt.Printf("next rune: '%s'\n", string(codePoint))
	}
}
```

### What did you expect to see?
Expected it to compile and print the runes, as using any of the two types alone in the interface does actually work.

### What did you see instead?
```
./prog.go:10:28: cannot range over runes (variable of type T constrained by RuneIterable) (T has no structural type)

Go build failed.
```

### Additional notes
- At first I expected this to work as a similar construct is shown at https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#composite-types-in-constraints where `type byteseq interface { string | []byte }` is used. But then I realized there's an ambiguity, as one might want to iterate a string as []byte or as []rune. It's not obvious what should even happen, and at least we should try to clarify it somewhere (maybe I missed something in the documentation).
- Using `range []rune(runes)` works, but it's unclear the translation will be transparent.
- Someone else also pointed on discord gophers that `interface { string | chan string }` would also be iterable but won't work. This might be another issue, I'm only mentioning it for context.

**Comment by ianlancetaylor** [comment]
Thanks.  This is expected.  We may try to tackle this for 1.19 or 1.20.  The key issue is that we will need to develop some theory and mechanism for generic types that are not covered by the type parameter list.  In this case the value type of `range` would be, as you say, either `rune` or `byte`.

If you look closely at the code in https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#composite-types-in-constraints you will see that it only uses `range` on values of type `[]T`, which is not problematic.  It does not use `range` on values of type `T`.

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by mymmrac** [comment]
Also, one case that can be investigated is range over `map` or `slice` type constrain, smallest example:
```go
func f[SliceOrMapType map[int]int | []int](sliceOrMap SliceOrMapType) {
	for range sliceOrMap {}
}
```

Currently, reports an error: 
```
cannot range over sliceOrMap (variable of type SliceOrMapType constrained by map[int]int|[]int) (SliceOrMapType has no core type)
```

**Comment by ianlancetaylor** [comment]
@mymmrac Yes, that is expected in Go 1.18.

**Comment by mymmrac** [comment]
> @mymmrac Yes, that is expected in Go 1.18.

Yep, I know, just wanted to mention, because it seems to be related to this issue

**Comment by ianlancetaylor** [comment]
Rolling forward to 1.20.  Please comment if you disagree.  Thanks.

**Comment by pat42smith** [comment]
If I understand #51053 correctly, and if it is implemented, then I suppose it would be possible to write a function that accepts either a push or a pull function this way:

```go
type Rangeable[X any] interface {
	func(yield func(X) bool) | func() (X, bool)
}

func f[X any, R Rangeable[X]](r R) {
	for x := range r {}
}
```

Is that right?

**Comment by griesemer** [comment]
No progress on this issue. Rolling forward to 1.22.

**Comment by griesemer** [comment]
Rolling forward to 1.23.

**Comment by griesemer** [comment]
This is tied to the requirement that range expressions must have a core type.
There's a larger issue (#63940) for investigating whether we can avoid the use of core types altogether - that would also require addressing this issue, one way or the other.
Closing in favor of #63940.
