### ISSUE TITLE
html/template: Error .. in attribute name

### ISSUE THREAD

**Issue by anoop012345** [golang/go#51065]
### What version of Go are you using (`go version`)?

<pre>
$ go1.17 

</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?

I am using "html/template" package, while try to execute the template by using t.Execute(wr io.Writer, data interface{}) function error return : `Error : "html/template:test_template: \"'\" in attribute name: \"Emoji';'><br /></span></p>\\n</div\"".
`

Template content is given below:

`<p style="font-family: Lato, sans-serif, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';">test</p>`

**Comment by seankhliao** [comment]
please include a reproducible example on go.dev/play
the input you gave doesn't report any errors: https://go.dev/play/p/AVEHUFrDQHt

**Comment by anoop012345** [comment]
I have created the issue here https://go.dev/play/p/qM49YITYZ_c
