### ISSUE TITLE
program run forever

### ISSUE THREAD

**Issue by ls-2018** [golang/go#51068]
### What version of Go are you using (`go version`)?

1.17.3

```
package main

import (
	"time"
)

func init() {
	go func() {
		for {
			time.Sleep(time.Second)
		}
	}()
}
func main() {
	waitQueue := make(chan int)
	waitQueue <- 1
	return
}

```
 

### What did you see?

The program will never end and there will be no panic

**Comment by seankhliao** [comment]
yes, that is what you have asked it to do

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
