### ISSUE TITLE
Unable to use more generic function to satisfy interface

### ISSUE THREAD

**Issue by JDeuce** [golang/go#51062]
### What version of Go are you using (`go version`)?
Latest playground

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
```
package main

import "fmt"

type S interface {
	Resolve(string)
}

type impl struct{}

func (i *impl) Resolve(a interface{}) {
	fmt.Println(a)
}

func main() {
	fmt.Println("start")
	x := S(&impl{})
	x.Resolve("hi")
}
```

### What did you expect to see?
Since the Resolve method in impl accepts `interface{}` it should be valid to pass it a string and it should be a valid implementation of the `S` interface

### What did you see instead?
```
cannot convert &impl{} (type *impl) to type S:
	*impl does not implement S (wrong type for Resolve method)
		have Resolve(interface {})
		want Resolve(string)
```

**Comment by randall77** [comment]
Method signatures in Go must match exactly for a type to satisfy an interface. Having arguments that are assignable to / return values that are assignable from is not enough.

Closing as a dup of #30602, there is much more discussion there.
