### ISSUE TITLE
about generics question

### ISSUE THREAD

**Issue by quarkcms** [golang/go#51060]
### What version of Go are you using (`go version`)?

<pre>
go version go1.18beta2 windows/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\DaiHang\AppData\Local\go-build
set GOENV=C:\Users\DaiHang\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\DaiHang\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\DaiHang\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18beta2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\quark\quark-go-beta\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\DaiHang\AppData\Local\Temp\go-build1285694975=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

<pre>
type Application struct {
	Container map[string]any
}

var application Application

func singleton[T any](abstract string, concrete T) {
	container := make(map[string]any)
	container[abstract] = concrete

	application.Container = container
}

func make(abstract string) any {
	return application.Container[abstract]
}

func main() {
	kernel := &http.Kernel{}

	singleton("httpkernel", kernel)

	httpkernel := make("httpkernel")

	httpkernel.Run()
}
</pre>
### What did you expect to see?

httpkernel.Run undefined (type any has no field or method Run)

### What did you see instead?
Execution the Run() method

**Comment by randall77** [comment]
The compiler is correct. The result type of `make` is `any`, which has no (statically known) methods. You would have to do a type assertion to the appropriate interface to call a method on it.
```
  httpkernel.(interface{Run()}).Run()
```
