### ISSUE TITLE
cmd/go: confusing error message (or incorrect behavior) when using -modfile with go run

### ISSUE THREAD

**Issue by findleyr** [golang/go#51079]
I'm experiencing some confusing behavior when trying to use the `-modfile` flag with `go run` -- it appears that `-modfile` is not being honored, though I have not ruled out an error on my side.

Context: in [CL 383375, patchset 2](https://go-review.googlesource.com/c/exp/+/383375/2), I am trying to use `x/tools` for the `copytermlist.go` script (used by `go generate`), but don't want to add an `x/tools` dependency to the module. I was planning to manage this additional dependency in a `go.tools.mod` file.

The `-modfile` flag appears not to work, even though copying over `go.mod` and `go.sum` _does_ work.

```
> go run -modfile=go.tools.mod copytermlist.go
copytermlist.go:25:2: no required module provides package golang.org/x/tools/go/ast/astutil; to add it:
        go get golang.org/x/tools/go/ast/astutil
> cat go.tools.mod
module golang.org/x/exp/typeparams

go 1.18

require golang.org/x/tools v0.1.9 // indirect
> cp go.tools.mod go.mod && cp go.tools.sum go.sum
> go run copytermlist.go
>
```

This doesn't match my mental model for how `-modfile` behaves.

CC @bcmills

**Comment by bcmills** [comment]
I'm not able to reproduce this failure mode from PS2 of that CL.

```
~/src/golang.org/x/exp/typeparams$ git rev-parse HEAD
ea96774d6baf9befe8eb7b3d5daa01b4aabcd1ae

~/src/golang.org/x/exp/typeparams$ git status
On branch issue51079-modfile
Your branch and 'origin/master' have diverged,
and have 1 and 4 different commits each, respectively.

nothing to commit, working tree clean

~/src/golang.org/x/exp/typeparams$ go1.18beta2 run copytermlist.go
copytermlist.go:25:2: no required module provides package golang.org/x/tools/go/ast/astutil; to add it:
        go get golang.org/x/tools/go/ast/astutil

~/src/golang.org/x/exp/typeparams$ go1.18beta2 run -modfile=go.tools.mod copytermlist.go

~/src/golang.org/x/exp/typeparams$
```

I'm not sure what to make of that, but at this point I don't have any other ideas about how it might have gone wrong. I did try setting `GOFLAGS=-modfile=/dev/null`, but the explicit `-modfile` flag overrode that too.

Is it possible that there was some kind of bad interaction with an IDE overlay, or a delayed file write? (Did you execute the command directly on the command line?)

**Comment by bcmills** [comment]
(I'm just adding this comment to reset the Gopherbot timer. 😅)
