### ISSUE TITLE
x/tools/gopls: completion for `f.Fuzz` parameter

### ISSUE THREAD

**Issue by hyangah** [golang/go#51089]
Going one step further from https://github.com/golang/go/issues/50198

It would be nice if gopls fills out the parameter automatically based on `f.Add` if it is present.

**Comment by findleyr** [comment]
Reopening, as I don't think this feature is quite working correctly.

If I am inside a fuzz function and type `f.Fuz`, the current implementation drops the completion to `Fuzz`. I think that's a bug -- it should only prune completions inside of a fuzz _target_.

**Comment by pjweinb** [comment]
I cannot reproduce this. Inside a FuzzFoo func, after typing a call to
f.Add, when I type f.F I get a oompletion, and if I keep typing I keep
getting the completion.

(If there hasn't been a call to f.Add, then there's no f.Fuzz completion.
Is that the problem?

**Comment by pjweinb** [comment]
closed by [393019](https://go-review.googlesource.com/c/tools/+/393019)
: 
internal/completion: default to regular completion for f.Fuzz without f.Add
