### ISSUE TITLE
x/sys/unix: go:linkname must refer to declared function or variable

### ISSUE THREAD

**Issue by weberc2-tempus** [golang/go#51091]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18beta2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

no, this seems to only affect `go1.18beta1` and `go1.18beta2`.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/craig.weber/Library/Caches/go-build"
GOENV="/Users/craig.weber/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/craig.weber/.gvm/pkgsets/go1.18beta2/global/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/craig.weber/.gvm/pkgsets/go1.18beta2/global"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/craig.weber/.gvm/gos/go1.18beta2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/craig.weber/.gvm/gos/go1.18beta2/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18beta2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/craig.weber/repos/github.com/weberc2/mono/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0s/gk8b_5s14_59cb4c6l6l0c6c35y91d/T/go-build1997345125=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

<pre>
$ go install github.com/segmentio/golines@latest
</pre>

### What did you expect to see?
No errors.

### What did you see instead?

```
# golang.org/x/sys/unix
../../../../.gvm/pkgsets/go1.18beta2/global/pkg/mod/golang.org/x/sys@v0.0.0-20191024172528-b4ff53e7a1cb/unix/syscall_darwin.1_13.go:25:3: //go:linkname must refer to declared function or variable
../../../../.gvm/pkgsets/go1.18beta2/global/pkg/mod/golang.org/x/sys@v0.0.0-20191024172528-b4ff53e7a1cb/unix/zsyscall_darwin_amd64.1_13.go:27:3: //go:linkname must refer to declared function or variable
../../../../.gvm/pkgsets/go1.18beta2/global/pkg/mod/golang.org/x/sys@v0.0.0-20191024172528-b4ff53e7a1cb/unix/zsyscall_darwin_amd64.1_13.go:40:3: //go:linkname must refer to declared function or variable
../../../../.gvm/pkgsets/go1.18beta2/global/pkg/mod/golang.org/x/sys@v0.0.0-20191024172528-b4ff53e7a1cb/unix/zsyscall_darwin_amd64.go:28:3: //go:linkname must refer to declared function or variable
../../../../.gvm/pkgsets/go1.18beta2/global/pkg/mod/golang.org/x/sys@v0.0.0-20191024172528-b4ff53e7a1cb/unix/zsyscall_darwin_amd64.go:43:3: //go:linkname must refer to declared function or variable
../../../../.gvm/pkgsets/go1.18beta2/global/pkg/mod/golang.org/x/sys@v0.0.0-20191024172528-b4ff53e7a1cb/unix/zsyscall_darwin_amd64.go:59:3: //go:linkname must refer to declared function or variable
../../../../.gvm/pkgsets/go1.18beta2/global/pkg/mod/golang.org/x/sys@v0.0.0-20191024172528-b4ff53e7a1cb/unix/zsyscall_darwin_amd64.go:75:3: //go:linkname must refer to declared function or variable
../../../../.gvm/pkgsets/go1.18beta2/global/pkg/mod/golang.org/x/sys@v0.0.0-20191024172528-b4ff53e7a1cb/unix/zsyscall_darwin_amd64.go:90:3: //go:linkname must refer to declared function or variable
../../../../.gvm/pkgsets/go1.18beta2/global/pkg/mod/golang.org/x/sys@v0.0.0-20191024172528-b4ff53e7a1cb/unix/zsyscall_darwin_amd64.go:105:3: //go:linkname must refer to declared function or variable
../../../../.gvm/pkgsets/go1.18beta2/global/pkg/mod/golang.org/x/sys@v0.0.0-20191024172528-b4ff53e7a1cb/unix/zsyscall_darwin_amd64.go:121:3: //go:linkname must refer to declared function or variable
../../../../.gvm/pkgsets/go1.18beta2/global/pkg/mod/golang.org/x/sys@v0.0.0-20191024172528-b4ff53e7a1cb/unix/zsyscall_darwin_amd64.go:121:3: too many errors
```

**Comment by ianlancetaylor** [comment]
You need to arrange to use a newer version of golang.org/x/sys.  The 2019-10-24 version doesn't work with Go1.18beta2.  Use the latest version instead.

**Comment by brizer** [comment]
> go get -u golang.org/x/sys/unix

Save my life, thanks.
