### ISSUE TITLE
gollvm: gofrontend: go version prints 'unknown'

### ISSUE THREAD

**Issue by erifan** [golang/go#51098]
### What version of Go are you using (`go version`)?

<pre>
gollvm tip branch
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
linux/arm64
</pre></details>

### What did you do?
go version

### What did you expect to see?
Normal go version information, such as `go version devel go1.18-69e1711f28 Mon Feb 7 23:45:09 2022 +0000 linux/arm64`

### What did you see instead?
go version **unknown** linux/arm64

Seems this CL https://go-review.googlesource.com/c/go/+/307820 is not properly exported to gofrontend. /CC @ianlancetaylor

**Comment by ianlancetaylor** [comment]
This is now fixed on mainline by https://go.dev/cl/414734 for #51850.  Thanks.
