### ISSUE TITLE
proposal: can go command provide an internal http server?

### ISSUE THREAD

**Issue by clearcodecn** [golang/go#51100]
Some other languages such as php or python, they provide a simple internal http server. 
```
php -S 0.0.0.0:9000

python -m http.server 9000

```

So can command `go` provide a internal sub command like: 

```
go -http 0.0.0.0:9000
```

**Comment by seankhliao** [comment]
That's out of scope for what the `go` tool is for, and the systems in place aren't suited for something like that.
In particular, those are scripting languages, and python works by loading the http.server module which does things when loaded directly from the command line.

There also doesn't seem to be a good reason why the `go` command should have a builtin fileserver.
