### ISSUE TITLE
spec: document behavior of type switches containing type parameter cases

### ISSUE THREAD

**Issue by griesemer** [golang/go#51110]
Specifically, document behavior when type instantiation leads to duplicate entries in the switch.

From conversation with @danscales:
> I think you may want to specify that a type parameter can be one of the types used in the type(s) of a case, as long as the typeparam satisfies the type of x (based on its bound).   You may want to mention explicitly that there may be duplicate cases after instantiation of a generic function/method with type args, and that is fine.   So, then, the first case matched is chosen.  Duplicate cases are only checked before instantiation.

cc: @danscales

**Comment by ianlancetaylor** [comment]
The proposal has this: https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#generic-types-as-type-switch-cases
