### ISSUE TITLE
x/build/cmd/relui: in prod deployment, make twitter secret in secret manager available to relui command

### ISSUE THREAD

**Issue by dmitshur** [golang/go#51122]
The production relui deployment ([deployment-prod.yaml](https://cs.opensource.google/go/x/build/+/master:cmd/relui/deployment-prod.yaml;l=1;drc=9076251d2245d34b4f6884d256c8237d40e257c7) in x/build/cmd/relui) runs the `relui` command, and currently provides some static flags and environment variables (see [here](https://cs.opensource.google/go/x/build/+/master:cmd/relui/deployment-prod.yaml;l=26-27;drc=9076251d2245d34b4f6884d256c8237d40e257c7) and [here](https://cs.opensource.google/go/x/build/+/master:cmd/relui/deployment-prod.yaml;l=31-36?q=deployment-prod.yaml)).

For upcoming production workflows, the `relui` binary will need to be also provided secrets from secret manager. Specifically, we want:

- [`secret.NameTwitterAPISecret`](https://pkg.go.dev/golang.org/x/build/internal/secret#NameTwitterAPISecret) for the ready workflows involving posting a tweet
    - (see #47402)
- [`secret.NameGobotPassword`](https://pkg.go.dev/golang.org/x/build/internal/secret#NameGobotPassword) for future workflows involving sending Gerrit CLs
- [`secret.NameSendGridAPIKey`](https://pkg.go.dev/golang.org/x/build/internal/secret#NameSendGridAPIKey) for future workflows involving sending email
    - (see #47404)

Based on sources like https://kubernetes.io/docs/concepts/configuration/secret/ and https://stackoverflow.com/questions/59079318/how-to-mount-multiple-files-secrets-into-common-directory-in-kubernetes, Kubernetes has support for arranging this. It can be implemented as files in a mounted volume (whose location can either be well-known by the relui command, or provided to it via a flag or env var), or via environment variables that relui can access.

This is the tracking issue for making these secrets available to the relui process in the production environment (a part of #47407).

CC @golang/release.

**Comment by heschi** [comment]
The [GCP secrets CSI driver](https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/blob/main/examples/app-secrets.yaml.tmpl) looked perfect but [doesn't work in Autopilot clusters]( https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/158), which makes me feel pretty dumb for using one :(

We could use an init container, or https://external-secrets.io/, but both feel too heavyweight for me.

https://github.com/GoogleCloudPlatform/berglas#library-usage is kinda neat, but I think I prefer something more explicit. So I think we should just take flags that are secret names and resolve them ourselves :-/

**Comment by dmitshur** [comment]
As part of resolving this issue, I've granted Secret Manager Secret Accessor role on the twitter API secret to relui's service account. Without that access, it correctly refuses to start up:

```
invalid value "secret:symbolic-datum-552/twitter-api-secret" for flag -twitter-api-secret: reading secret "twitter-api-secret" from project symbolic-datum-552 failed: rpc error: code = PermissionDenied desc = Permission 'secretmanager.versions.access' denied for resource 'projects/symbolic-datum-552/secrets/twitter-api-secret/versions/latest' (or it may not exist).
Usage of ./relui: [...]
```

The tweet workflows are ready and need secret access now, while the other workflows will be added later on. Now that we've done the work to propagate one secret, doing it for more is trivial, and there's no value in doing it preemptively.

So I'll scope this issue down to be just about the twitter credentials and update [CL 387274](https://go.dev/cl/387274) to close it.
