### ISSUE TITLE
cmd/go: loadinternal: cannot find runtime/cgo

### ISSUE THREAD

**Issue by billcoding** [golang/go#51124]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18beta2 windows/amd64
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Users\Administrator\sdk\go1.18beta2
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\Administrator\sdk\go1.18beta2\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18beta2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\Administrator\Desktop\aaaaa\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build1486301158=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
<pre>
GOOS=ios GOARCH=arm64 go1.18beta2.exe build
</pre>

### What did you expect to see?
<pre>
Build `ios/arm64` on `Windows`.
</pre>

### What did you see instead?
<pre>
$ GOOS=ios GOARCH=arm64 go1.18beta2.exe build
# main
loadinternal: cannot find runtime/cgo
C:\Users\Administrator\sdk\go1.18beta2\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1    
C:\Users\ADMINI~1\AppData\Local\Temp\go-link-1126134048\go.o: file not recognized: file format not recognized
collect2.exe: error: ld returned 1 exit status
</pre>

**Comment by beoran** [comment]
Do you have a C cross compiler for iOS and arm64 installed?

**Comment by cherrymui** [comment]
See https://cs.opensource.google/go/go/+/master:misc/ios/README . You'll need an iOS C toolchain (which probably is only available on macOS), and set up the environment accordingly. Thanks.
