### ISSUE TITLE
cmd/go: cover tool help command syntax does not work on Windows 

### ISSUE THREAD

**Issue by spekary** [golang/go#51126]
### What version of Go are you using (`go version`)? 

<pre>
1.17.5
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Windows

### What did you do?

Running 'go tool cover -help' issues a help message that includes this command suggestion:

`
go tool cover -func=c.out
`

This works on the Mac and Linux, but not on Windows. On Windows it produces the following error message:

`
too many arguments
For usage information, run "go tool cover -help"
`

The correct way to call this is:

`
go tool cover -func c.out
`

This works on all platforms.

Note that this bad usage pattern is sprinkled throughout the go ecosystem. For example, this web page: https://pkg.go.dev/cmd/cover, has this line:

`
Cover is a program for analyzing the coverage profiles generated by 'go test -coverprofile=cover.out'.
`

However, running that line in a windows cmd terminal produces:
`
no required module provides package .out; to add it: go get .out
`

Or here: https://pkg.go.dev/cmd/go#hdr-Build_constraints, it uses examples of `-buildmode=mode`, even though the documentation earlier specs it as `-buildmode mode`.

This clearly is a longstanding problem that should be easy to clean up.

**Comment by saurabh-mish** [comment]
Seeing this error in GitHub action CI when running `go tool cover -html=profile.out -o testcoverage.html`.

Commands preceding the above work fine:

```
go test -v ./... -coverprofile profile.out
go tool cover -func profile.out
```

**Comment by ianlancetaylor** [comment]
I just tested and `go tool cover -func=c.out` works fine for me on Windows.

I don't understand why it wouldn't work, as the flag parsing is done by Go code and that Go code looks for =.

Can somebody who is having this problem debug it?  Thanks.

**Comment by seankhliao** [comment]
This would be PowerShell/PowerShell#6291

**Comment by seankhliao** [comment]
Closing as a PowerShell bug
