### ISSUE TITLE
access: requesting Editor (go-approvers) for mengzhuo

### ISSUE THREAD

**Issue by mengzhuo** [golang/go#51131]
Github username: mengzhuo
Email: mengzhuo1203(at)gmail.com

https://github.com/orgs/golang/teams/go-approvers

Hi, @golang/release I had be an approver (+2) for a long time and I want to help gardening Github issue 
p.s. especially thoese Chinese users who report issue in Chinese :)

**Comment by ALTree** [comment]
cc @golang/release

**Comment by dmitshur** [comment]
Thanks for making the request.

Since you've already been granted Gerrit Code-Review+2 access, that implies TryBot, GitHub access as well, so moving this issue to NeedsFix.

Your GitHub account should be invited now, so closing.

Thank you again for your continued contributions to the Go project!
