### ISSUE TITLE
the RssFile of golang process in kernal 3.10 is different from kernal 5.4

### ISSUE THREAD

**Issue by 249043822** [golang/go#51130]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.6 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

the RssFile of golang process in kernal 3.10 is much different from kernal 5.4,  see the follow comparisons for detail

```
RssAnon:           39084 kB
**RssFile:           35116 kB**
RssShmem:              0 kB
VmData:  1305548 kB
VmStk:       132 kB
VmExe:    113548 kB
VmLib:      2088 kB
VmPTE:       448 kB
VmSwap:        0 kB

[root@k8s-node1 kdt]# uname -r
3.10.0-693.21.1.el7.x86_64

```

```
RssAnon:    35244 kB
**RssFile:    72452 kB**
RssShmem:        0 kB
VmData:   268428 kB
VmStk:      132 kB
VmExe:    57616 kB
VmLib:     1712 kB
VmPTE:      544 kB
VmSwap:        0 kB

root@ubuntu:/home/ubuntu# uname -a
Linux ubuntu 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### What did you expect to see?

There should be little difference.

**Comment by davecheney** [comment]
If this is the same go binary deployed on two different kernels, why do you think the issue is the Go program? Arguably this is a difference in the kernel’s memory accounting between that has changed in the last decade since 3.10 was released.

**Comment by 249043822** [comment]
@davecheney Sorry, I'm not sure, I only found a same gp binary running on kernal 4 and 5, the RssFile segment significantly increased, resulting in more total memory.

**Comment by davecheney** [comment]
Is it using more memory, or is it only *looking* like the process used less memory on the older kernel? Have you considered that newer kernels may have a different methodology for process size accounting.

**Comment by 249043822** [comment]
Maybe, I found C progaram has the same behavior.
