### ISSUE TITLE
Hitting curl https://go.dev/VERSION?m=text returns a go version package which is not available to download

### ISSUE THREAD

**Issue by domstorey** [golang/go#51135]
### What version of Go are you using (`go version`)?

Latest stable

### Does this issue reproduce with the latest release?

GOLANG_LATEST_STABLE_VERSION=$(curl https://go.dev/VERSION?m=text)

This currently returns `go1.17.7` but `go1.17.6` is the latest which is built and so this has broken our CICD pipeline

![image](https://user-images.githubusercontent.com/5566472/153458412-00239b1b-aac7-4fe1-88c1-b7f65d613e23.png)

Source available but not binary downloadable
![image](https://user-images.githubusercontent.com/5566472/153458256-2c6025cc-6056-4e6b-92ce-813283c6cdd1.png)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?

curl https://go.dev/VERSION?m=text should return the latest version available for download.

So for example this code works in our docker container:

```
RUN GOLANG_LATEST_STABLE_VERSION=$(curl https://go.dev/VERSION?m=text) \
  && curl -OL https://go.dev/dl/${GOLANG_LATEST_STABLE_VERSION}.linux-ppc64le.tar.gz \
```

### What did you see instead?

![image](https://user-images.githubusercontent.com/5566472/153459037-bac2a039-27ef-4544-91ad-97af83b49819.png)

:-)

**Comment by seankhliao** [comment]
VERSION is the version running the website, not latest version to download.

**Comment by seankhliao** [comment]
go.dev/dl/?mode=json

**Comment by domstorey** [comment]
Thanks you :-)
