### ISSUE TITLE
go/doc, x/pkgsite: add `comparable` as predeclared type

### ISSUE THREAD

**Issue by fzipp** [golang/go#51141]
[CL 359778](https://go-review.googlesource.com/c/go/+/359778) added `any` as predeclared type to go/doc, but not [`comparable`](https://pkg.go.dev/builtin@go1.18beta2#comparable).

This is the reason why pkg.go.dev (via its internal copy of go/doc) doesn't linkify `comparable`, e.g. [here](https://pkg.go.dev/golang.org/x/exp/slices#Contains).

/cc @findleyr

**Comment by findleyr** [comment]
Indeed, thank you for the investigation! Since this is an easy fix, I think we can probably get this into go/doc for 1.18.

CC @griesemer @jba

**Comment by findleyr** [comment]
Reopening to track the equivalent change for pkgsite.
