### ISSUE TITLE
proposal: time: add time helper UnixNano(nsec)

### ISSUE THREAD

**Issue by joshuamsager** [golang/go#51148]
Currently, the `time` package allows for converting `time.Time` [to nanoseconds](https://github.com/golang/go/blob/master/src/time/time.go#L1161). This issue proposes a symmetrical helper that converts nanoseconds to `time.Time`:

The proposed API follows a similar pattern to the existing helpers: `UnixMilli` and `UnixMicro` implemented in https://github.com/golang/go/commit/49dccf141f5e315739c5517b24572fff7cb13734:
```
func UnixNano(nsec int64) Time {
	return Unix(nsec/1e9, nsec%1e9)
}
```

**Comment by seankhliao** [comment]
`time.Unix(0, nsec)` already works though, and is explicitly documented to work as such
