### ISSUE TITLE
gccgo: building Kubernetes with gccgo fails

### ISSUE THREAD

**Issue by erifan** [golang/go#51142]
### What version of Go are you using (`go version`)?

<pre>
The latest gccgo built with gcc commit a645583d4d68eecdd9101e1013e7bf01907ea786.

</pre>

### Does this issue reproduce with the latest release?
For the latest main Go, no.
For the latest gccgo (gcc backend or llvm backend), yes!

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
Linux/arm64
</pre></details>

### What did you do?
Build Kubernetes with gccgo:

mkdir -p $GOPATH/src/k8s.io
cd $GOPATH/src/k8s.io
git clone https://github.com/kubernetes/kubernetes
cd kubernetes
make

### What did you expect to see?
A successful building.

### What did you see instead?
**F0211 08:42:39.639292   71314 deepcopy.go:890] Hit an unsupported type invalid type for invalid type, from k8s.io/component-base/config.LoggingConfiguration**
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks
        /home/erifan01/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1140
k8s_0io_1kubernetes_1vendor_1k8s_0io_1klog_1v2.loggingT.output
        /home/erifan01/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1088
k8s_0io_1kubernetes_1vendor_1k8s_0io_1klog_1v2.loggingT.printf
        /home/erifan01/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:753
k8s_0io_1kubernetes_1vendor_1k8s_0io_1klog_1v2.Fatalf
        /home/erifan01/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1642
k8s_0io_1kubernetes_1vendor_1k8s_0io_1gengo_1examples_1deepcopy_x2dgen_1generators.genDeepCopy.doStruct
        /home/erifan01/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go:890
k8s_0io_1kubernetes_1vendor_1k8s_0io_1gengo_1examples_1deepcopy_x2dgen_1generators.genDeepCopy.generateFor
        /home/erifan01/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go:698
k8s_0io_1kubernetes_1vendor_1k8s_0io_1gengo_1examples_1deepcopy_x2dgen_1generators.genDeepCopy.GenerateType
        /home/erifan01/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go:611
k8s_0io_1kubernetes_1vendor_1k8s_0io_1gengo_1generator.Context.executeBody
        /home/erifan01/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/generator/execute.go:321
k8s_0io_1kubernetes_1vendor_1k8s_0io_1gengo_1generator.Context.ExecutePackage
        /home/erifan01/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/generator/execute.go:282
k8s_0io_1kubernetes_1vendor_1k8s_0io_1gengo_1generator.Context.ExecutePackages
        /home/erifan01/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/generator/execute.go:51
k8s_0io_1kubernetes_1vendor_1k8s_0io_1gengo_1args.GeneratorArgs.Execute
        /home/erifan01/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/args/args.go:213
main.main
        /home/erifan01/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go:75

goroutine 4 [chan receive]:
k8s_0io_1kubernetes_1vendor_1k8s_0io_1klog_1v2.loggingT.flushDaemon
        /home/erifan01/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1283
created by k8s_0io_1kubernetes_1vendor_1k8s_0io_1klog_1v2.k8s_0io_1kubernetes_1vendor_1k8s_0io_1klog_1v2..init0
        /home/erifan01/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:420 +0xa0
Makefile.generated_files:252: recipe for target 'gen_deepcopy' failed
make[1]: *** [gen_deepcopy] Error 1
Makefile:526: recipe for target 'generated_files' failed
make: *** [generated_files] Error 2

I didn't dig into the issue, but since the project can be built with the latest main Go, maybe it's a gccgo bug.

**Comment by cherrymui** [comment]
The error

> F0211 08:42:39.639292 71314 deepcopy.go:890] Hit an unsupported type invalid type for invalid type, from k8s.io/component-base/config.LoggingConfiguration

is from a tool used in kubernetes make file. It is not from gccgo.

Maybe kubernetes's build tool does not support gccgo well. I tend to think it is more of an issue of kubernetes, instead of gccgo.
