### ISSUE TITLE
net: use EDNS to increase DNS packet size

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#51153]
Issue #51127 lists a bunch of cases where the Go DNS resolver has trouble because it follows [RFC 1035](https://datatracker.ietf.org/doc/html/rfc1035) and only accepts 512 byte packets.  https://go.dev/cl/385035 uses EDNS(0) to advertise that the resolver accepts a larger packet size, and accepts packets up that increased size (1232 bytes per https://dnsflagday.net/2020/).  The CL is reported to fix the immediate problem found in #51127, that the Go resolver fails on WSL: https://github.com/golang/go/issues/51127#issuecomment-1035908203.

I would like to request a freeze exception to include https://go.dev/cl/385035 in the 1.18 release.  If acceped for 1.18 I'll also open backport issues to earlier releases.

The CL should be safe.  Accepting a larger packet size does not cause harm.  EDNS(0) was designed to be backward compatible with DNS servers that don't understand it; per [RFC 1035](https://datatracker.ietf.org/doc/html/rfc1035), released in 1987, they should just ignore it.  EDNS(0) was first specified in [RFC 2671](https://datatracker.ietf.org/doc/html/rfc2671) in 1999, and restated and refined in [RFC 6891](https://datatracker.ietf.org/doc/html/rfc6891) in 2013.  It is unlikely that there any DNS servers out there that can't at least ignore it.

CC @golang/release

**Comment by ianlancetaylor** [comment]
CC @mdempsky

**Comment by toothrot** [comment]
Although this is late in cycle, this is a small, focused change that we intend to backport regardless, which makes sense to accept. 

We've discussed a bit and are supportive of merging this before the RC.

**Comment by mdempsky** [comment]
I agree that compliant DNS servers shouldn't have any issues with the use of EDNS. But the rationale for this CL is to accommodate non-compliant servers that send invalid responses, so it seems like we should also be mindful about non-compliant servers/firewalls that break EDNS.

Will there be more release candidates before Go 1.18? If so, I think including in Go 1.18 seems reasonable.

I'm not sure why this is important to backport though?

**Comment by toothrot** [comment]
Backporting is justified to me by the comments in "Miscellany" in #51127. This tooling is critical for some users, and forcing them to upgrade to (as of yet unreleased 1.18) isn't a great workaround. I assume this impacts the Go command as well.

**Comment by seankhliao** [comment]
The go command almost always links to libc, which means using the platform C resolver by default and not the netgo one.

**Comment by mateusz834** [comment]
@seankhliao 
> The go command almost always links to libc, which means using the platform C resolver by default and not the netgo one.

When compiled with libc, the net package decides at runtime whether to use cgo or go resolver

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport issues.

**Comment by fweimer-rh** [comment]
@ianlancetaylor This will cause new failures because `FORMERR`/`NOTIMPL` fallback appears to be missing from the implementation. It may be necessary to implement timeout handling as well (retrying without EDNS0 in case of a timeout).

**Comment by ianlancetaylor** [comment]
@fweimer-rh Do you think that we need to worry about those possibilities in practice?  I don't see anything in glibc, although it's true that that case is different because the user must explicitly opt-in to EDNS in the resolv.conf file.

If those are real possibilities then I will revert the CL.  It's too late in the release cycle to add that kind of complexity.

Thanks.

**Comment by fweimer-rh** [comment]
@AaronFriel The initial buffer sizes vary on the NSS functions used (1024 and 2048, see `resolv/nss_dns/dns-hosts.c`). There is also the NSS-based `ERANGE` retry loop, but I'm not sure if this only applies after TCP fallback. (There is dynamic buffer allocation in `resolv/res_send.c`, but that's only for the second response in a dual/parallel `AF_UNSPEC` lookup.) However, I wouldn't recommend the glibc implementation as a model for a stub resolver.

**Comment by AaronFriel** [comment]
Fair, I also wouldn't use glibc as a reference. I'm merely offering a compromise to maximize compatibility with real world DNS resolvers without advertising full EDNS0 support.

**Comment by ianlancetaylor** [comment]
After discussion, we currently plan to do this:

* roll back CL 385035
* add a change to accept DNS packets up to 1232 bytes, to help WSL
* backport that DNS packet change to 1.16 and 1.17
* reinstall CL 385035 after the 1.18 release, so that it has some testing for 1.19

**Comment by ianlancetaylor** [comment]
OK, changes made.  Moving this issue to 1.19 to use EDNS.
