### ISSUE TITLE
os: os Process.Kill() not working on windows

### ISSUE THREAD

**Issue by gianniLesl** [golang/go#51151]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

Tested with go version 1.17, 1.17.1, 1.17.3, 1.17.6, and 1.17.7 

The feature is working on 1.16.14 and earlier.

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

GOOS="windows" GOARCH="amd64"

### What did you do?

I created a small script to use to kill particular processes on windows. When I compile and run the executable though I get the error `DuplicateHandle: The handle is invalid.`

Source code: https://go.dev/play/p/Ik3UMsABNQI

### What did you expect to see?

Expected Process.Kill to kill the running process without error

### What did you see instead?

`DuplicateHandle: The handle is invalid.`

**Comment by bcmills** [comment]
The `os.Process` struct has unexported fields, so you can't expect to create a valid one using a struct literal.

Instead, look up the desired PID using [`os.FindProcess`](https://pkg.go.dev/os#FindProcess).

**Comment by gianniLesl** [comment]
We expected this to work because it was working in 1.16.14, so 1.17 break backwards compatibility. This seems to be the change that broke us https://github.com/golang/go/commit/105c5b50e0098720b9e24aea5efa8e161c31db6d?diff=split . When I run with the function 
```
func TerminateProcess(process os.Process, exitCode int) error {
	h, e := syscall.OpenProcess(syscall.PROCESS_TERMINATE, false, uint32(process.Pid))
	if e != nil {
		return os.NewSyscallError("OpenProcess", e)
	}
	defer syscall.CloseHandle(h)
	e = syscall.TerminateProcess(h, uint32(exitCode))
	if e != nil {
		return os.NewSyscallError("TerminateProcess", e)
	}

	runtime.KeepAlive(process)
	return nil
}
```

execution succeeds.

Source Code: https://go.dev/play/p/mELlwQqiBZa

(Note: When we run os.FindProcess on 1.16 and 1.17 it returns "OpenProcess: Access is denied." for our processes)

**Comment by ianlancetaylor** [comment]
Writing

```Go
	process := os.Process{
		Pid: pid,
	}
```

was never supposed to work.  I'm sorry that it did.

**Comment by beoran** [comment]
In this case, it should have been documented that it cannot work. While there are unexported members, it isn't immediately clear from the docs that Kill will not work.
