### ISSUE TITLE
x/tools/gopls: incorrect signature help for method expressions

### ISSUE THREAD

**Issue by findleyr** [golang/go#51155]
Gopls shows the method signature rather than receiver type as the first parameter type in signatureHelp on method expressions:

![image](https://user-images.githubusercontent.com/57144380/153672841-3c3156aa-0a9a-4a6b-8266-013274dbedf9.png)

This screenshot should instead show `X.n(X, string)` or `n(X, string)`. Notably, the associated diagnostic shows the correct signature.

**Comment by tttoad** [comment]
@findleyr This issue looks like it's been fixed by https://go.dev/cl/611836.
