### ISSUE TITLE
proposal: affected/package: context

### ISSUE THREAD

**Issue by shaharzeira** [golang/go#51169]
Improve performance of the close function of cancelCtx, 
by adding a condition to check if it has been closed, before entering the lock.

	if err == nil {
		panic("context: internal error: missing cancel error")
	}
	**_if c.err != nil {
		return // already canceled
	}_**
	c.mu.Lock()
	if c.err != nil {
		c.mu.Unlock()
		return // already canceled
	}
	c.err = err
	if c.done == nil {
		c.done = closedchan
	} else {
		close(c.done)
	}

**Comment by davecheney** [comment]
I’m afraid that will not work, the double check lock idiom died with the introduction of SMP hardware.
