### ISSUE TITLE
reflect: Type interface is unimplemented comparable (generics)

### ISSUE THREAD

**Issue by Code-Hex** [golang/go#51179]
### What version of Go are you using (`go version`)?

<pre>
$ gotip version
go version devel go1.18-e50f0f372b Fri Feb 11 05:11:58 2022 +0000 darwin/arm64
</pre>

### What did you do?

The document for reflect.Type interface has described is comparable.

> Type values are comparable, such as with the == operator, so they can be used as map keys.

However, I tried to compare with a function using generics comparable, and I get a compilation error.

### What did you expect to see?

compilable

### What did you see instead?

compilation error.

https://go.dev/play/p/vPcBpD86rST?v=gotip

**Comment by hopehook** [comment]
I find it is work fine at the latest code, which is failed on the go playground.

**Comment by hopehook** [comment]
@griesemer

**Comment by dmitshur** [comment]
Also CC @findleyr.

**Comment by ianlancetaylor** [comment]
It's true that `reflect.Type` is not treated as a comparable type, and it's true that that may be problematic in some cases.  That said, we aren't going to do anything here for 1.18.

**Comment by ianlancetaylor** [comment]
Rolling forward to 1.20.

**Comment by ianlancetaylor** [comment]
Closing in favor of #56548 which attempts to address the general issue.
