### ISSUE TITLE
spec: should array of interfaces be allowed as constrain?

### ISSUE THREAD

**Issue by KZiemian** [golang/go#51178]
<pre>
$ go version
go version go1.18beta2 linux/amd64
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kamil/.cache/go-build"
GOENV="/home/kamil/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/kamil/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/kamil/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/kamil/sdk/go1.18beta2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/kamil/sdk/go1.18beta2/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18beta2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/kamil/go/src/github.com/KZiemian/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1092432607=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

This is follow up to discussion on [golang-nuts](https://groups.google.com/g/golang-nuts/c/yHIxVgZpqpk).
```go
type someType [3]interface {
	SomeMethod()
}
```
This define three elements array, which every element is an interface. As this [code](https://go.dev/play/p/XSwZIBxfOH4?v=gotip) show `someType` can be used as constraint in generic function definition (?). I'm on my second read of [_Type parameters proposal_](https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md) and I would say "No". But, I may be wrong.

**Comment by fzipp** [comment]
Any type can be used as constraint, because `[T constraintElements]` can be short for `[T interface{constraintElements}]`, see https://tip.golang.org/ref/spec#Type_constraints. This is not in the original type parameters proposal, because it was added by a later proposal.

**Comment by KZiemian** [comment]
@fzipp Thank you for the information. From what I understand `[T someInterface]` is not treated directly as a constraint/interface, but it is implicit converted to `[T interface{smeInterface}]`, am I right?

While writing `[T int | float64]` instead of `[T interface{ int | float64}]` looks very nice, I have doubts about situation with `someInterface`. More generally, when underling type of constraint is not an interface, but contains interface type (I hope what I wrote have some sense), looks too error prone to me. I'm not consider myself a gopher, only Go student, so I may be totally wrong and we need constraint that contains interface types.

**Comment by fzipp** [comment]
@KZiemian No, `[T someInterface]` is treated as `[T someInterface]`, but these are equivalent anyway:

```
[T someInterface]
[T interface{someInterface}]
[T interface{interface{someInterface}}]
[T interface{interface{interface{someInterface}}}]
[T interface{interface{interface{interface{someInterface}}}}]
...
```

**Comment by KZiemian** [comment]
So I must to understand why `interface{someInterface}` is equivalent to `interface`. Thank you for information.

**Comment by dmitshur** [comment]
Is there anything left here that would need to be done for 1.18, or is this resolved now? Thanks.

CC @findleyr, @ianlancetaylor.

**Comment by findleyr** [comment]
Hi, per my reading the original question is resolved: using `[3]interface{...}` in constraint position is implicitly treated as `interface{[3]interface{...}}`. The fact that the element type of the array is an interface does not matter here.

Closing as I don't see anything actionable. Please reopen if I missed something.
