### ISSUE TITLE
cmd/compile: peculiar error message caused by two type parameters with the same name

### ISSUE THREAD

**Issue by KZiemian** [golang/go#51177]
<pre>
$ go version
go version go1.18beta2 linux/amd64
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kamil/.cache/go-build"
GOENV="/home/kamil/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/kamil/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/kamil/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/kamil/sdk/go1.18beta2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/kamil/sdk/go1.18beta2/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18beta2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/kamil/go/src/github.com/KZiemian/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1092432607=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

I try to test Go type parameters in all ways that I can, so I checked what defining two type parameters with the same name do. Compiling this [code](https://go.dev/play/p/4Fx_IEgnrup?v=gotip) give on my computer error message
<pre>
# command-line-arguments
./Go-s11-26.go:13:33: T redeclared in this block
            /home/kamil/go/src/github.com/KZiemian/Go-s11-26.go:13:19: other declaration of T
./Go-s11-26.go:30:46: cannot infer T (/home/kamil/go/src/github.com/KZiemian/Go-s11-26.go:13:33)
</pre>

Maybe it is as it should be, but it looks somewhat wrong to me. Someone with bigger expedience should judge it.

Slightly different version of [code](https://go.dev/play/p/2b2MYJZ6LMz?v=gotip), also give similar error message.

**Comment by randall77** [comment]
The first error looks exactly right. It's saying you declared `T` twice, at line 13 (19 and 33 are the column numbers).
The second error is kind of spurious, resulting from the fact that the thing you're calling didn't typecheck correctly. That error should probably be suppressed.

**Comment by hopehook** [comment]
Perhaps correct code is like this: https://go.dev/play/p/sd9bia4ybSv?v=gotip

**Comment by KZiemian** [comment]
@randall77 Does showing full path in "/home/kamil/go/src/github.com/KZiemian/Go-s11-26.go:13:19: other declaration of T" is correct? It feels wrong to me, but this may be just my feeling.

@hopehook I didn't think how correct code would look like. I just tried to test Go1.18beta in every way that I can imagine, even the silly one, and look if something crash/give weird result. I now working through [_Type Parameters Proposal_](https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md) to find answers to few true problems that I have. This is just byproduct of it.
