### ISSUE TITLE
cmd/go: module source tree too big for github.com/pulumi/pulumi-azure-native/sdk

### ISSUE THREAD

**Issue by burhan** [golang/go#51175]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.7 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\burhan\AppData\Local\go-build
set GOENV=C:\Users\burhan\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\burhan\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\burhan\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.7
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\burhan\AppData\Local\Temp\go-build1513202360=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

This is a duplicate of #29210, #25470 and #25470, but as mentioned in [this comment](https://github.com/golang/go/issues/29210#issuecomment-453125125) opening a new issue here.

Reported at the Pulumi  repo as https://github.com/pulumi/pulumi-azure-native/issues/1502

**Comment by ianlancetaylor** [comment]
CC @bcmills @matloob

**Comment by bcmills** [comment]
From https://github.com/pulumi/pulumi-azure-native/issues/1502#issuecomment-1039568608 it sounds like this is being resolved by the maintainers of that module. I appreciate the data point, but I think at this point we don't need to make a `cmd/go` change to accommodate it.
