### ISSUE TITLE
proxy.golang.org - remove accidental package "wonderland.org"

### ISSUE THREAD

**Issue by pgalbavy** [golang/go#51187]
While "learning" I accidentally managed to create a vanity URL for my module in my root domain and not one level down. It's still there:

`
curl https://proxy.golang.org/wonderland.org/@v/list
`

Can this be somehow manually removed?

The correct, full path is working even though it is full of redacted semantic tagged versions (also my bad):

`
curl https://proxy.golang.org/wonderland.org/geneos/@v/list
`

I have logn since fixed the HTML meta data.

**Comment by dmitshur** [comment]
If you haven't already, please take a look at the "I removed a bad release from my repository but it still appears in the mirror, what should I do?" question in the FAQ at https://proxy.golang.org.

It's possible to retract an accidentally published module version as described at https://golang.org/ref/mod#go-mod-file-retract, and to request a removal request for pkg.go.dev specifically as described at https://pkg.go.dev/about#removing-a-package. To avoid breaking builds, `proxy.golang.org` doesn't remove versions.

CC @heschi, @bcmills.
