### ISSUE TITLE
spec: do shifts really require core types?

### ISSUE THREAD

**Issue by dominikh** [golang/go#51182]
The current specification at tip says that

> For shifts, the [core type](https://tip.golang.org/ref/spec#Core_types) of both operands must be an integer.

The core type of an interface (ignoring channels) is defined as

> There is a single type U which is the [underlying type](https://tip.golang.org/ref/spec#Underlying_types) of all types in the [type set](https://tip.golang.org/ref/spec#Interface_types) of T

If I am not mistaken, the following shouldn't compile

```
func Shift[T int32 | int64](x T) {
	_ = x << x
}
```

because T has no core type.

Is this a mistake in the spec, the type checker, or my understanding?

/cc @griesemer @findleyr

**Comment by griesemer** [comment]
This is a bug in the spec. Thanks for pointing it out. Shifts behave more like the other numeric operations in that respect. Please feel free to comment on https://go-review.googlesource.com/c/go/+/385536.

**Comment by dominikh** [comment]
> Please feel free to comment on https://go-review.googlesource.com/c/go/+/385536.

Thanks, will do that going forward (sans the other issue I just filed :smile: )
