### ISSUE TITLE
gofrontend: plugin package is missing

### ISSUE THREAD

**Issue by erifan** [golang/go#51203]
### What version of Go are you using (`go version`)?

<pre>
$ go version
Latest Gccgo built from tip
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
Linux/arm64, Linux/amd64
</pre></details>

### What did you do?
$ gccgo -c plug.go
$ cat plug.go
package foo

import(
        "plugin"
)

type PluginInterface struct {
        pluginMap     map[string]*plugin.Plugin
}

func (p *PluginInterface) myOpen(path string) (*plugin.Plugin, error) {
        return plugin.Open(path)
}

Actually this issue was found when building tidb,
git clone https://github.com/pingcap/tidb.git
cd tidb
make

### What did you expect to see?
No error

### What did you see instead?
plug.go:4:15: error: import file 'plugin' not found
    4 |         "plugin"
      |               ^
plug.go:8:41: error: expected package
    8 |         pluginMap     map[string]*plugin.Plugin
      |                                         ^
plug.go:11:55: error: expected package
   11 | func (p *PluginInterface) myOpen(path string) (*plugin.Plugin, error) {
      |                                                       ^
plug.go:12:9: error: return with value in function with no return type
   12 |         return plugin.Open(path)
      |         ^

I found 'plugin' is not included in libgo/libgo-packages.txt file, is this intended ? /CC @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Thanks.  Closing as dup of #36403.  It's a known problem, hard to fix.
