### ISSUE TITLE
x/tools/gopls: support conversion between raw and interpreted string literals

### ISSUE THREAD

**Issue by pgaskin** [golang/go#51200]
**Is your feature request related to a problem? Please describe.**
I've often needed to convert between raw (<code>&#96;…&#96;</code>) and interpreted (`"…"`) strings, especially when pasting literals between files in different languages. This would also make it easier to edit complex string literals.

**Describe the solution you'd like**
Code actions or refactoring options for converting between the two forms:

- Interpreted to raw (one option for if `strconv.CanBackquote`, another one which is similar but allows newlines).
  - If the string contains backticks, this action could either be hidden or made to transform it to <code>&#96; + "&#96;" + &#96;</code>. If it transforms it, another action to merge consecutive concatenated literals into a single one would be useful.
- Raw to interpreted (i.e. `%q`).
- Raw to interpreted ASCII (i.e. `%+q`) (for completeness; I wouldn't really use this one much).

**Describe alternatives you've considered**
I currently manually convert between forms, using regular expressions for large strings. I've considered making this as a separate VSCode extension, but I think this fits better in gopls since it's Go-specific.

**Additional context**
N/A

**Comment by findleyr** [comment]
Thanks for the contribution! Moved to the gopls@v0.15.0 milestone so we remember to mention this in the release notes.
