### ISSUE TITLE
encoding/json json.Unmarshel cannot deal with leading zeros

### ISSUE THREAD

**Issue by xplora1a** [golang/go#51205]
In the process of dealing with the readings coming from a electricity meter I was trying to process these json strings:
{"datetime":"2022-02-14T19:53:08Z","import":0000504.720,"export":0117950.472}
unmarshel was returning a empty struct

Changing the input data to:
{"datetime":"2022-02-14T19:53:08Z","import":504.720,"export":117950.472}
Resolved the problem

package main

import (
	"fmt"
	"encoding/json"
	"time"
)

func main() {

	type HydroMeter struct {
		M1datetime	string `json:"datetime"`
		M1import	float32	`json:"import"`
		M1export	float32 `json:"export"`
	}
	hydrometer1 := `{"datetime":"2022-02-14T19:53:08Z","import":0000504.720,"export":0117950.472}`
	var hydroMeter HydroMeter
	json.Unmarshal([]byte(hydrometer1), &hydroMeter)
	fmt.Println(hydroMeter)	

	hydrometer2 := `{"datetime":"2022-02-14T19:53:08Z","import":504.720,"export":117950.472}`
	json.Unmarshal([]byte(hydrometer2), &hydroMeter)
	fmt.Println(hydroMeter)	
	fmt.Println(time.Parse(time.RFC3339, hydroMeter.M1datetime))
}

$ go run unmarshal.go 
{ 0 0}
{2022-02-14T19:53:08Z 504.72 117950.47}
2022-02-14 19:53:08 +0000 UTC <nil>

**Comment by mvdan** [comment]
You aren't checking the errors: https://go.dev/play/p/-_MM7KETebL

JSON does not allow leading zeros in natural numbers, like `001`. Leading zeros are only allowed in cases where you need them, like `0.5`. See https://www.json.org/json-en.html and https://stackoverflow.com/questions/27361565/why-is-json-invalid-if-an-integer-begins-with-a-leading-zero.

Int he future, see https://golang.org/wiki/Questions.

**Comment by xplora1a** [comment]
thanks Daniel @mvdan
