### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by Beaelf** [golang/go#51201]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN="/Users/cd.l/go/bin"
GOCACHE="/Users/cd.l/Library/Caches/go-build"
GOENV="/Users/cd.l/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/cd.l/go/pkg/mod"
GONOPROXY=""
GONOSUMDB="github.com/***/*"
GOOS="darwin"
GOPATH="/Users/cd.l/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/cd.l/Documents/workspace/***/***/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0n/g4x9qh0n6vb9zp0_06b0hsqr0000gn/T/go-build3173792104=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
```
go test -v -race ./...
```

### What did you expect to see?

run my test cases

### What did you see instead?
<img width="962" alt="image" src="https://user-images.githubusercontent.com/27497831/154013847-cbaa6fb0-5052-45fd-846c-21d15d0f1cde.png">

**Comment by ALTree** [comment]
Looks like #49138. Please update to the latest 1.16 minor release, it should be fixed there.

Also please don't post screenshots of text, they make much harder to search the issues database. A textual search for "unknown class" will not find this issue, because you put the error into an image.
