### ISSUE TITLE
os/signal, runtime: fatal signal 33 on android-arm64-corellium due to AllThreadsSyscall rewrite

### ISSUE THREAD

**Issue by prattmic** [golang/go#51213]
android-arm64-corellium [failed](https://build.golang.org/log/5c0d42c7f06396d75f1656baa474402b50287497) on https://go.dev/cl/383434. It would seem that signal 33 is fatal on that builder for some reason.

cc @bcmills @aclements

**Comment by dmitshur** [comment]
CC @changkun in case the `android-arm64-corellium` builder configuration is relevant in this issue.

**Comment by changkun** [comment]
The current connected (two) android corellium builders should work as expected. These connected builders have no configuration change. Hence if there is a failure, it might likely be a failure due to relevant code change.
