### ISSUE TITLE
cmd/go: hang in 'exec powershell' in TestScript/build_acl_windows on windows/arm64

### ISSUE THREAD

**Issue by bcmills** [golang/go#51210]
```
#!watchflakes
post <- goos == "windows" && test == "TestScript/build_acl_windows" && `exec powershell`
```

`greplogs --dashboard -md -l -e 'FAIL: TestScript/build_acl_windows .*(?:\n    .*)*\> exec powershell.*(?:\n    .*)*: test timed out while running command' --since=2019-03-08`

[2022-02-12T05:44:16-f14ad78/windows-arm64-11](https://build.golang.org/log/e7752b0116134113690d4833ae051af814ca1225)
[2022-02-11T22:01:05-badba35/windows-arm64-10](https://build.golang.org/log/6c88f301dbd5059cd54e48a0f2ed0ffa1d65228a)

**Comment by bcmills** [comment]
It's curious that the only two failures occurred within a few hours of each other — close enough that the coordinator could have been running them concurrently. It kind of makes me wonder whether something in the PowerShell executable is non-hermetic. 🤔

This test was converted to a script test in [CL 165752](https://go.dev/cl/165752), so the test itself is fairly old. Since these are the first time we've seen this failure mode, I'm going to leave this test enabled to see whether any future failures are also time-correlated.

**Comment by qmuntal** [comment]
> It kind of makes me wonder whether something in the PowerShell executable is non-hermetic.

Looking at the logs, I think the hand happens while running `go build -o $TMP\main.exe main.go`, so before `powershell` is executed.

Still no clue.
