### ISSUE TITLE
cmd/compile: internal compiler error on illegal assignement

### ISSUE THREAD

**Issue by Karitham** [golang/go#51236]
### What version of Go are you using (`go version`)?

devel (right now, go version devel go1.18-2c4c1ad Wed Feb 16 20:29:09 2022 -0800 linux/amd64)

### Does this issue reproduce with the latest release?

yes

### What did you do?

Improved example code by @madxmike

https://go.dev/play/p/bziYa_LWmkO?v=gotip

### What did you expect to see?

Illegal assignment error

### What did you see instead?

Compiler error

**Comment by dmitshur** [comment]
CC @mdempsky, @randall77.

**Comment by mdempsky** [comment]
Simplified test case:

```
package main

func f([]byte)     {}
func g[T []byte]() { f(T(nil)) }
func main()        { g[[]byte]() }
```

**Comment by danscales** [comment]
This issue is the same as the second testcase in #51232 , so let's make this the main issue for this case.  I'll make a note in #51232 .

**Comment by danscales** [comment]
I have the rough fix for this one.
