### ISSUE TITLE
doc: document race detector cgo requirements

### ISSUE THREAD

**Issue by andig** [golang/go#51235]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.6 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/andig/Library/Caches/go-build"
GOENV="/Users/andig/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/andig/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/andig/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.17.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.17.6/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sv/rs_453y57xj86xsbz3kw1mbc0000gn/T/go-build3031970245=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.17.6 darwin/arm64
GOROOT/bin/go tool compile -V: compile version go1.17.6
uname -v: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
ProductName:	macOS
ProductVersion:	12.2
BuildVersion:	21D49
lldb --version: lldb-1300.0.42.3
Swift version 5.5.2-dev
</pre></details>

### What did you do?

Use goreleaser to create multi-platform release. Amongst others, goreleaser executes:

    CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -race  main.go

### What did you expect to see?

Sucess

### What did you see instead?

    go build: -race requires cgo

I would like to request documenting the cgo requirements per platform as part of https://go.dev/doc/articles/race_detector.

**Comment by mengzhuo** [comment]
@ianlancetaylor How about this doc?

Requirements
---------------------------------
The race detector require cgo and support the os/arch below:

* linux/amd64
* linux/ppc64le
* linux/arm64
* freebsd/amd64
* netbsd/amd64
* darwin/amd64
* darwin/arm64
* windows/amd64

**Comment by andig** [comment]
Thank you @ALTree I was under the impression that it didn't need cgo on all platforms, but if it's helpful to mention that it does!

**Comment by ALTree** [comment]
@andig I think #6508 and #9918 still apply.

**Comment by ianlancetaylor** [comment]
As far as I can tell using the race detector has required cgo on Windows for several releases.  What does `go env CGO_ENABLED` print for both of the releases you are testing.

**Comment by inliquid** [comment]
@ianlancetaylor I could pass `vet=off` and it did the trick. 

So this works:
```
>go1.19.5 test -v -count=1 -race -vet=off .
<...>
```

This doesn't:
```
>go test -v -count=1 -race -vet=off .
go: -race requires cgo; enable cgo by setting CGO_ENABLED=1
```

But w/o `vet=off` go1.19 also breaks:
```
>go1.19.5 test -v -count=1 -race .          
# runtime/cgo
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in %PATH%
FAIL    gitlab.ptsecurity.com/ptcs/policy-enforcer/cmd/policy-enforcer [build failed]
FAIL
```

Despite this fancy trick everything worked until `go1.20` and now it looks like a regression.

**Comment by ianlancetaylor** [comment]
I don't know why `-vet=off` would make any difference here.  That sounds like a bug.  It makes me think that something got into your build cache somehow.  What happens if you run `go1.19.5 test -a -v -count=1 -race -vet=off` ?

**Comment by inliquid** [comment]
@ianlancetaylor 
> I don't know why -vet=off would make any difference here.

Initially I found this was mentioned here: https://github.com/golang/go/issues/27089#issuecomment-415329050

> What happens if you run go1.19.5 test -a -v -count=1 -race -vet=off ?
```
>go1.19.5 test -a -v -count=1 -race -vet=off
# runtime/cgo
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in %PATH%
```

**Comment by ianlancetaylor** [comment]
OK, so forcing the rebuild demonstrates the problem even if you use `-vet=off`.  I think that means that it was only working with 1.19 because the of the prebuilt packages.  In Go 1.20 we no longer include those with binary releases (https://go.dev/doc/go1.20#go-command).  So it's possible that this is a bit of a regression for people using binary releases.  It's possible that in Go 1.19 the race detector would work out of the box for programs that do not require cgo even if there is no C compiler installed, because the C compiler was run when building the packages.  In Go 1.20 that is no longer true.  This is just a guess, though.  If you want to pursue this further, please open a new issue with this possibility.  Thanks.

**Comment by elafontaine** [comment]
Thanks Ian, it makes sense (at least on my setup (I was going mad)).  I had a project that I compiled on go 1.17 and I've just now started on a new project in VS code and I had different behaviour until tonight when I rebuilt the old binary.  Now it keeps failing as mention.   I had passed a flag for the test environment which is `-race` and was wondering why the old project was able to run the debug mode of tests with `cgo_enabled=0` while the new one required `gcc` to be present.  

Thanks a lot for this issue.  I will install gcc now.

**Comment by d0vgan** [comment]
Guys, I'm I Windows user and I still have this problem. An attempt to run the race detector leads to:
```
# runtime/cgo
cgo-builtin-prolog:1: stddef.h: No such file or directory
```
So I'm having a proposal: could you add a hint for Windows users, mentioning this issue on the download page and explaining what this CGO is and how to install it?
