### ISSUE TITLE
net: net.FileConn(os.Stdin) fails

### ISSUE THREAD

**Issue by masp** [golang/go#51230]
### What version of Go are you using (`go version`)?
<pre>
> go version
go version go1.17.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xxx/.cache/go-build"
GOENV="/home/xxx/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/xxx/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xxx/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.7"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3050204946=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
https://go.dev/play/p/xNJIPxpQ7Y8

### What did you expect to see?
No error from `net.FileConn(os.Stdin)`

### What did you see instead?
This error:

<pre>
2009/11/10 23:00:00 file file+net /dev/stdin: getsockopt: socket operation on non-socket

Program exited.
</pre>

**Comment by ianlancetaylor** [comment]
`net.FileConn` only supports `os.File` values that are created from network connections.  You can't use any arbitrary `net.FileConn` with any arbitrary file.
