### ISSUE TITLE
cmd/go: add release note for changes to go.mod automatic-update behavior in 1.18

### ISSUE THREAD

**Issue by h31** [golang/go#51242]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18rc1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/artyom/Library/Caches/go-build"
GOENV="/Users/artyom/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/artyom/.asdf/installs/golang/1.18rc1/packages/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/artyom/.asdf/installs/golang/1.18rc1/packages"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/artyom/.asdf/installs/golang/1.18rc1/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/artyom/.asdf/installs/golang/1.18rc1/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18rc1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pr/5k6c2yx97cjb9t5fh0httxv80000gn/T/go-build2521786815=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

1. Create `go.mod` with the following content:
```
module DepSync

go 1.17
```
2. Create `main.go` with the following content:
```
package main

import (
	"github.com/davecgh/go-spew/spew"
)

func main() {
	spew.Println()
}
```
3. Run `go mod vendor`

### What did you expect to see?

```
$ go version
go version go1.17.7 darwin/amd64
$ go mod vendor
go: finding module for package github.com/davecgh/go-spew/spew
go: found github.com/davecgh/go-spew/spew in github.com/davecgh/go-spew v1.1.1
$ cat go.mod
module DepSync

go 1.17

require github.com/davecgh/go-spew v1.1.1
$ ls vendor/
github.com  modules.txt
```

### What did you see instead?

```
$ go mod vendor
DepSync imports
	github.com/davecgh/go-spew/spew: no required module provides package github.com/davecgh/go-spew/spew; to add it:
	go get github.com/davecgh/go-spew/spew
```

**Comment by dmitshur** [comment]
Thank you for testing out the RC and making this report. When you say "stopped updating", do you mean this used to work with 1.17.7 and older?

CC @bcmills, @matloob.

**Comment by bcmills** [comment]
The change in `go mod vendor` was intentional ([CL 336151](https://go.dev/cl/336151), for #45551), but it appears that we are missing a release note for it.
