### ISSUE TITLE
cmd/compile: WebAssembly built from fyne_demo command crashes browser optimizer in Chrome

### ISSUE THREAD

**Issue by Bluebugs** [golang/go#51241]
### What version of Go are you using (`go version`)?

<pre>
go version go1.17.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes.

### What operating system and processor architecture are you using (`go env`)?

This is a bug concerning the webassembly output and its use in Chrome.

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cedric/.cache/go-build"
GOENV="/home/cedric/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/cedric/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/cedric/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/cedric/go/src/fyne.io/fyne/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2399108240=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Running fyne_demo (https://github.com/fyne-io/fyne/tree/master/cmd/fyne_demo) from the develop branch as a web assembly application in Chrome lead to its optimizer crashing in version >100 and an infinite loop in nightly build. I have hosted a demo online at https://fyne.ddlm.me/ that will show the problem.

A bug has been opened for Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1287331 , but in case there is something that can be done on the go side of the command, it would be interesting to know.

### What did you expect to see?

I would expect the same result on Chrome as I get on Safari and Firefox, a running application.

### What did you see instead?

It does crash on Chrome inside its optimization pass after 15s of the application running (it get disable when using the web dev tools) while it work on Firefox and Safari.

**Comment by dmitshur** [comment]
CC @neelance, @cherrymui.

**Comment by Bluebugs** [comment]
Testing with Chrome Version 106.0.5249.91 (Official Build) (64-bit) today and not having rebuild with any different Go version, it does work. The bug was in Chrome somewhere and is not fixed. Thanks to anyone involved.
