### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by Suha652** [golang/go#51260]
### Go'nun hangi sürümünü kullanıyorsunuz ('go sürümü')? <pre> $ go sürüm </pre> ### Bu sorun en son sürümle birlikte yeniden oluşturuluyor mu? ### Hangi işletim sistemini ve işlemci mimarisini kullanıyorsunuz ('go env')? <><summary><code>go env</code> Output</summary><br><pre> $ go env </pre></details> ### Ne yaptınız?  ### Ne görmeyi bekliyordun? Onun yerine ne gördün?

**Comment by mdlayher** [comment]
Sorry, we can only help in English on this tracker.
