### ISSUE TITLE
*tls.Conn does not have a UnderlyingConn() to access the *net.Conn via an exported identifier

### ISSUE THREAD

**Issue by andrewhodel** [golang/go#51272]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.6 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zip/Library/Caches/go-build"
GOENV="/Users/zip/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zip/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zip/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2n/6lp_hgtd1jzbhrzvzldlm8m40000gn/T/go-build301895266=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I need to access the underlying connection of a *tls.Conn exported identifier, but there is no UPPERCASE function to return it.

### What did you expect to see?

I expected to be able to access the *net.Conn of a *tls.Conn to modify it, keep alive can be modified after creation.

### What did you see instead?

The lack of an error explaining that an identifier is printed with "%+v" but not accessible and a uninformative error when attempted.

**Comment by ALTree** [comment]
> I expected to be able to access the *net.Conn of a *tls.Conn to modify it, keep alive can be modified after creation.

Dup of #29257, a [`Conn.NetConn`](https://pkg.go.dev/crypto/tls@master#Conn.NetConn) method was added and it will be in go1.18

**Comment by andrewhodel** [comment]
Thank you, how's your search engine?



Andrew

**Comment by andrewhodel** [comment]
Also, the gorilla websocket library that is looking for a new maintainer
has a function, conn.UnderlyingConn() that does the same thing to provide
access to the *tls.Conn.conn object.

Might want to work with them on naming.



Andrew
