### ISSUE TITLE
This again is invalid, a type assertion to net.TCPConn from a net.Conn object does not allow SetKeepAlive() to be used, it panics.

### ISSUE THREAD

**Issue by andrewhodel** [golang/go#51278]
```
panic: interface conversion: net.Conn is *tls.Conn, not *net.TCPConn
```

https://github.com/golang/go/issues/51277

**Comment by mdlayher** [comment]
You've made it clear you have no intention of participating in good faith, and have repeatedly called the integrity of others into question for trying to ask questions to assess the issue you are trying to solve.

Please review https://go.dev/conduct before participating further.
