### ISSUE TITLE
This is not true and the involved team member has lied, ruining my credibility and directly opposed himself by focusing on a tls.Conn object when he should know it requires type-assertion to a net.TCPConn object

### ISSUE THREAD

**Issue by andrewhodel** [golang/go#51277]
https://github.com/golang/go/issues/51274

You are supposed to be able to type-assert or cast a `net.Conn` to a `net.TCPConn`.

The go team member created a situation where he lied about that, then said there was no issue.

**Comment by andrewhodel** [comment]
Honest, read through it.

He basically set me up by saying it should be cast to a `tls.Conn` when he knew the problem required a `net.TCPConn`.

Then he said there was no issue, but the issue is honest.

**Comment by andrewhodel** [comment]
I request that you allow me write access to that issue, so I can redeem my credibility while proving your inadequacy as you attempted to do to me.

**Comment by andrewhodel** [comment]
Here is how he did it.

<img width="870" alt="Screen Shot 2022-02-20 at 8 01 43 PM" src="https://user-images.githubusercontent.com/741705/154837522-721ee235-cc00-4596-ba3b-e5e95006d918.png">

**Comment by andrewhodel** [comment]
As you can see, I actually told him that `tls.conn.NetConn()` does not exist as he was the requestor of that type-assertion.

Why does Google pay people to do this to decent people?

**Comment by andrewhodel** [comment]
As a continuation, here is that truth:

```
# command-line-arguments
./ispapp-go-client.go:236:20: uc.(*net.TCPConn).NetConn undefined (type *net.TCPConn has no field or method NetConn)
Andrews-MacBook-Pro:ispapp-go-client zip$ git diff
diff --git a/ispapp-go-client.go b/ispapp-go-client.go
index 2a188b3..216e993 100644
--- a/ispapp-go-client.go
+++ b/ispapp-go-client.go
@@ -233,7 +233,7 @@ func new_websocket(host *Host) {
 
        fmt.Println(reflect.TypeOf(uc))
        fmt.Printf("%+v\n", uc)
-       //uc.conn.SetKeepAlive(true)
+       uc.(*net.TCPConn).NetConn().SetKeepAlive(true)
 
        // set host.WanIfName
        var ipaddrstr, port, iperr = net.SplitHostPort(c.LocalAddr().String())
```

**Comment by andrewhodel** [comment]
The program is still not working as documented.

**Comment by andrewhodel** [comment]
Here is proof `net.TCPConn` has a SetKeepAlive method.

https://cs.opensource.google/go/go/+/refs/tags/go1.17.7:src/net/tcpsock.go;l=159

**Comment by andrewhodel** [comment]
The program is still not working as documented.

This is a bug in Go.  Fix it or leave it open as the truth.

**Comment by andrewhodel** [comment]
This is how it actually works.

```
uc.(*net.TCPConn).SetKeepAlive(true)
```

**Comment by andrewhodel** [comment]
I need you to allow me to resolve the issue you incorrectly closed and locked me out of.

People need to know how to do this, every Apple laptop has power darkmode and it works with keep alive flagged tcp packets.

**Comment by ALTree** [comment]
Glad you were able to solve the issue with net.TCPConn. For the record, I suggested a generic `tls.Conn` assertion because in the first post you were asking about `tls.Conn.NetConn( )`. Of course it's up to you to decide if that makes sense in your code.
