### ISSUE TITLE
https://pkg.go.dev/encoding/base64 does not have an EncodeString() function but has a DecodeString() function

### ISSUE THREAD

**Issue by andrewhodel** [golang/go#51287]
It should be fixed.

https://pkg.go.dev/encoding/base64

There's no reason that the functions shouldn't conform on encoding and decoding.

**Comment by mengzhuo** [comment]
There is EncodeToString
https://pkg.go.dev/encoding/base64#Encoding.EncodeToString

Also Github issue is for issue tracker only, if you think it a proposal please change title with prefix  "proposal:"  instead of bug form.

**Comment by andrewhodel** [comment]
That isn't conforming to the standard of the decode function that accepts a
string.

**Comment by mengzhuo** [comment]
AFAIK there is no "standard" of decode functions, only MarshalXXXX for encoding interfaces.

Grepping "EncodeString" shows nothing but testcase for json.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by andrewhodel** [comment]
I'm not concerned with "as far as you know".

I'm concerned with the fact that there is a DecodeString function and there
is no EncodeString function.



Andrew

**Comment by andrewhodel** [comment]
Why did you close this, I opened another issue to remove the DecodeString() function if there is not going to be an EncodeString() function.

https://github.com/golang/go/issues/51288
