### ISSUE TITLE
Showing Unnecessary Error/Warning Message for Golang in VS Code.

### ISSUE THREAD

**Issue by ShifatHasanGNS** [golang/go#51297]
**[ Filepaths ]**

 GoLang /
............... notes /
........................ _greet.go_
............... _go.mod_
............... _test.go_

-----------------------------------------------
**[ Contents of _go.mod_ ]**

```
module golang

go 1.17
```

-----------------------------------------------
**[ Contents of _greet.go_ ]**

```
package notes

import "fmt"

func Greet() {
    fmt.Println("Hello 中国!")
}
```

-----------------------------------------------
**[ Contents of _test.go_ ]**

```
package main

import (
    "fmt"
    "golang/others"
)

func main() {
    fmt.Println(notes.Greet())
}
```

-----------------------------------------------
**[ Error Message ]**

**could not import _golang/others_** (cannot find package "**golang/others**" in any of 
	_C:\Program Files\Go\src\golang\others_ (from **$GOROOT**)
	_C:\Users\Shifat Hasan\Go\src\golang\others_ (from **$GOPATH**))

-----------------------------------------------
**[ VS Code Notification ]**

Error loading workspace: You are outside of a module and outside of $GOPATH/src. If you are using modules, please open your editor to a directory in your module. If you believe this warning is incorrect, please file an issue: https://github.com/golang/go/issues/new.

-----------------------------------------------
HOW  CAN  I  SOLVE  THIS  PROBLEM ?  PLEASE  HELP  ME ...

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
