### ISSUE TITLE
net/http: race between operations on maxClientStreamID and inGoAway.

### ISSUE THREAD

**Issue by doujiang24** [golang/go#51309]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yeah, maybe. I haven't reproduced it yet.
Just found this issue based on code.

race may happen on such a flow:

```

 fields                                 write goroutine                       read goroutine

                                                                         1. read(false), in processHeaders
inGoAway
                                       2. set to true, in goAway
----------------------------------------------------------
                                       3. read(old), in scheduleFrameWrite 
maxClientStreamID
                                                                        4. set(a new), in processHeaders
```

The server may have already processed the new request while the client got the old stream id in the GoAway frame,
and the client will retry the new request again.

Yeah, the race is very very small, but I think it indeed exists in theory.
eg. these three things happen at the same time:
1. server received a request header,
2. server got a signal to start graceful stop,
3. an OS schedule on the read goroutine between operation 1 and operation 4(make it is long enough time).

Or, do I misunderstand the code?
Thanks!

**Comment by mengzhuo** [comment]
Can you build your exmaple code with -race ?
https://go.dev/doc/articles/race_detector

**Comment by doujiang24** [comment]
@mengzhuo Thanks for your reply.
In my opinion, it's hard to build a reproducible example even with `-race`.

I think the key point is:
we assume there may be a long time between these two lines, eg. an OS schedule that `-race` can not simulate.
https://github.com/golang/go/blob/master/src/net/http/h2_bundle.go#L5525-L5565

**Comment by ianlancetaylor** [comment]
CC @neild to see if there is a race in the net/http code.

**Comment by doujiang24** [comment]
@neild Could you please take a look at this issue? Thanks.
