### ISSUE TITLE
sync.map: range is deadlock！

### ISSUE THREAD

**Issue by zqhhh** [golang/go#51311]
### What version of Go are you using (`go version`)?

<pre>
go version go1.17.3 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1997717128=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

1. Here my demo code
```
package main

import (
	"fmt"
	"log"
	"net/http"
	_ "net/http/pprof"
	"sync"
	"time"
)

var Sm = sync.Map{}

func main() {
	go http.ListenAndServe(fmt.Sprintf("0.0.0.0:%d", 18080), nil)
	for i := 0; i < 100; i++ {
		Sm.Store(i, i)
	}
	go worker1()
	time.After(5 * time.Second)
	go worker2()

	select {}

}

func do1() {
	log.Println("runDO1")
	Sm.Range(func(key, value interface{}) bool {
		time.Sleep(1 * time.Millisecond)
		return true
	})
}

func worker1() {
	for {
		do1()
	}
}

func do2() {
	defer func() {
		Sm = sync.Map{}
		// Sm.Range(func(key, value interface{}) bool {
		// 	Sm.Delete(key)
		// 	return true
		// })
		for i := 0; i < 100; i++ {
			Sm.Store(i, i)
		}
	}()
	Sm.Range(func(key, value interface{}) bool {
		if key.(int)%10 == 0 {
			return false
		}
		time.Sleep(1 * time.Millisecond)
		return true
	})
	log.Println("runDO2")
}

func worker2() {
	for {
		do2()
	}
}


```
- 
After running for a while. function do1() `Sm.range` deadlock occurred.
If I use 
```
 Sm.Range(func(key, value interface{}) bool {
 	Sm.Delete(key)
 	return true
 })
``` 
instead `Sm = sync.Map{}` .It works fine.

- 
I find if  del code:
```
if key.(int)%10 == 0 {
	return false
}
```
also works fine
-->

### What did you expect to see?
It Should work fine, but not yet

### What did you see instead?
Why not use `Sm = sync.Map{}` To del all map key? Why does this deadlock happen

**Comment by davecheney** [comment]
This looks like memory corruption. Have you tried running your program under the race detector? See https://blog.golang.org/race-detector .

**Comment by zqhhh** [comment]
> return false

I just tried it and saw the warning message。Thanks

**Comment by hopehook** [comment]
I think “Sm = sync.Map{}” is dangerous when there is a race condition.

**Comment by davecheney** [comment]
Thank you. This is not a big in Go, closing.
