### ISSUE TITLE
gccgo: linkname directive doesn't support non exported functions

### ISSUE THREAD

**Issue by erifan** [golang/go#51313]
### What version of Go are you using (`go version`)?

<pre>
$ go version
gccgo tip
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
linux/arm64, linux/amd64
</pre></details>

### What did you do?
$ go run main.go
$ cat main.go
```
package main

import (
        "unsafe"
)

//go:linkname unsafeNew reflect.unsafe_New
func unsafeNew(typ unsafe.Pointer) unsafe.Pointer

func unsafeAdd(p unsafe.Pointer) unsafe.Pointer {
        p = unsafeNew(p)
        return unsafe.Pointer(uintptr(p)+1)
}

func main() {
        a := 1
        p := unsafeAdd(unsafe.Pointer(&a))
        println(p)
}
```

### What did you expect to see?
0x400001a079

### What did you see instead?
/usr/local/bin/ld: $WORK/b001/_pkg_.a(_go_.o): in function `main.unsafeAdd':
/home/eric/main.go:11: undefined reference to `main.unsafeNew'
/usr/local/bin/ld: $WORK/b001/_pkg_.a(_go_.o): in function `main.main':
/home/eric/main.go:11: undefined reference to `main.unsafeNew'
collect2: error: ld returned 1 exit status

**Comment by ianlancetaylor** [comment]
You shouldn't use `go:linkname` like this, and besides for gccgo you need to use different names.  For gccgo it's `reflect.unsafe__New`.  Butt there are no guarantees that that will work.  Don't do it.

**Comment by erifan** [comment]
> For gccgo it's reflect.unsafe__New

This works, thanks @ianlancetaylor  @cherrymui
