### ISSUE TITLE
net/url: no default port information after parse URL without explicit port

### ISSUE THREAD

**Issue by kdh6429** [golang/go#51329]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.7 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ME\AppData\Local\go-build
set GOENV=C:\Users\ME\AppData\Roaming\go\env  
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\ME\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\ME\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.7
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ME\AppData\Local\Temp\go-build2535369338=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I tried to convert a string(with no port, 80) address into a URL form with _(u *URL) Parse(ref string) (*URL, error)_

### What did you expect to see?
URL struct that has port as 80

### What did you see instead?
"" (empty string)

(u *URL) Parse(ref string) (*URL, error) If there is no port information in the method, I would like to have port 80 by default.

**Comment by davecheney** [comment]
Thank you for raising this issue. Can you please post a small example program using https://go.dev/play/ that demonstrates the problem.

**Comment by kdh6429** [comment]
https://go.dev/play/p/ixt68e1izE6
@davecheney I hope this example helps to understand the problem.

**Comment by davecheney** [comment]
Yes it does, thank you. From my understanding the package is working correctly, there is no port value in that url.

**Comment by ianlancetaylor** [comment]
Thanks, but the package is working as documented and intended.  Even if we wanted to change it, changing it now would likely break existing Go code.  It's easy enough to write a little function to do

```Go
    port := url.Port()
    if port == "" {
        port = "80"
    }
    return port
```

**Comment by kdh6429** [comment]
Thank you all. As you said, the package is working correctly, and I am writing the code like the sample code above. I was wondering if there is any thought to handle the condition within the package :)
