### ISSUE TITLE
api: audit for Go 1.18

### ISSUE THREAD

**Issue by dmitshur** [golang/go#51333]
This is a tracking issue for doing an audit of API additions for Go 1.18.
The list was populated from `api/go1.18.txt` including changes as of https://go.dev/cl/384154.

### bufio ###

- [x] pkg bufio, method (*Writer) AvailableBuffer() []uint8
- [x] pkg bufio, method (ReadWriter) AvailableBuffer() []uint8

### bytes ###

- [x] pkg bytes, func Cut([]uint8, []uint8) ([]uint8, []uint8, bool)

### crypto/tls ###

- [x] pkg crypto/tls, method (*Conn) NetConn() net.Conn

### debug/buildinfo ###

- [x] pkg debug/buildinfo, func Read(io.ReaderAt) (*debug.BuildInfo, error)
- [x] pkg debug/buildinfo, func ReadFile(string) (*debug.BuildInfo, error)
- [x] pkg debug/buildinfo, type BuildInfo = debug.BuildInfo

### debug/elf ###

- [x] pkg debug/elf, const R_PPC64_RELATIVE = 22
- [x] pkg debug/elf, const R_PPC64_RELATIVE R_PPC64

### debug/dwarf ###

- [x] pkg debug/dwarf, type BasicType struct, DataBitOffset int64
- [x] pkg debug/dwarf, type StructField struct, DataBitOffset int64

### debug/plan9obj ###

- [x] pkg debug/plan9obj, var ErrNoSymbols error

### go/ast ###

- [x] pkg go/ast, method (*IndexListExpr) End() token.Pos
- [x] pkg go/ast, method (*IndexListExpr) Pos() token.Pos
- [x] pkg go/ast, type FuncType struct, TypeParams *FieldList
- [x] pkg go/ast, type IndexListExpr struct
- [x] pkg go/ast, type IndexListExpr struct, Indices []Expr
- [x] pkg go/ast, type IndexListExpr struct, Lbrack token.Pos
- [x] pkg go/ast, type IndexListExpr struct, Rbrack token.Pos
- [x] pkg go/ast, type IndexListExpr struct, X Expr
- [x] pkg go/ast, type TypeSpec struct, TypeParams *FieldList

### go/constant ###

- [x] pkg go/constant, method (Kind) String() string

### go/token ###

- [x] pkg go/token, const TILDE = 88
- [x] pkg go/token, const TILDE Token

### go/types ###

- [x] pkg go/types, func Instantiate(*Context, Type, []Type, bool) (Type, error)
- [x] pkg go/types, func NewContext() *Context
- [x] pkg go/types, func NewSignatureType(*Var, []*TypeParam, []*TypeParam, *Tuple, *Tuple, bool) *Signature
- [x] pkg go/types, func NewTerm(bool, Type) *Term
- [x] pkg go/types, func NewTypeParam(*TypeName, Type) *TypeParam
- [x] pkg go/types, func NewUnion([]*Term) *Union
- [x] pkg go/types, method (*ArgumentError) Error() string
- [x] pkg go/types, method (*ArgumentError) Unwrap() error
- [x] pkg go/types, method (*Interface) IsComparable() bool
- [x] pkg go/types, method (*Interface) IsImplicit() bool
- [x] pkg go/types, method (*Interface) IsMethodSet() bool
- [x] pkg go/types, method (*Interface) MarkImplicit()
- [x] pkg go/types, method (*Named) Origin() *Named
- [x] pkg go/types, method (*Named) SetTypeParams([]*TypeParam)
- [x] pkg go/types, method (*Named) TypeArgs() *TypeList
- [x] pkg go/types, method (*Named) TypeParams() *TypeParamList
- [x] pkg go/types, method (*Signature) RecvTypeParams() *TypeParamList
- [x] pkg go/types, method (*Signature) TypeParams() *TypeParamList
- [x] pkg go/types, method (*Term) String() string
- [x] pkg go/types, method (*Term) Tilde() bool
- [x] pkg go/types, method (*Term) Type() Type
- [x] pkg go/types, method (*TypeList) At(int) Type
- [x] pkg go/types, method (*TypeList) Len() int
- [x] pkg go/types, method (*TypeParam) Constraint() Type
- [x] pkg go/types, method (*TypeParam) Index() int
- [x] pkg go/types, method (*TypeParam) Obj() *TypeName
- [x] pkg go/types, method (*TypeParam) SetConstraint(Type)
- [x] pkg go/types, method (*TypeParam) String() string
- [x] pkg go/types, method (*TypeParam) Underlying() Type
- [x] pkg go/types, method (*TypeParamList) At(int) *TypeParam
- [x] pkg go/types, method (*TypeParamList) Len() int
- [x] pkg go/types, method (*Union) Len() int
- [x] pkg go/types, method (*Union) String() string
- [x] pkg go/types, method (*Union) Term(int) *Term
- [x] pkg go/types, method (*Union) Underlying() Type
- [x] pkg go/types, type ArgumentError struct
- [x] pkg go/types, type ArgumentError struct, Err error
- [x] pkg go/types, type ArgumentError struct, Index int
- [x] pkg go/types, type Config struct, Context *Context
- [x] pkg go/types, type Config struct, GoVersion string
- [x] pkg go/types, type Context struct
- [x] pkg go/types, type Info struct, Instances map[*ast.Ident]Instance
- [x] pkg go/types, type Instance struct
- [x] pkg go/types, type Instance struct, Type Type
- [x] pkg go/types, type Instance struct, TypeArgs *TypeList
- [x] pkg go/types, type Term struct
- [x] pkg go/types, type TypeList struct
- [x] pkg go/types, type TypeParam struct
- [x] pkg go/types, type TypeParamList struct
- [x] pkg go/types, type Union struct

### net ###

- [x] pkg net, func TCPAddrFromAddrPort(netip.AddrPort) *TCPAddr
- [x] pkg net, func UDPAddrFromAddrPort(netip.AddrPort) *UDPAddr
- [x] pkg net, method (*Resolver) LookupNetIP(context.Context, string, string) ([]netip.Addr, error)
- [x] pkg net, method (*TCPAddr) AddrPort() netip.AddrPort
- [x] pkg net, method (*UDPAddr) AddrPort() netip.AddrPort
- [x] pkg net, method (*UDPConn) ReadFromUDPAddrPort([]uint8) (int, netip.AddrPort, error)
- [x] pkg net, method (*UDPConn) ReadMsgUDPAddrPort([]uint8, []uint8) (int, int, int, netip.AddrPort, error)
- [x] pkg net, method (*UDPConn) WriteMsgUDPAddrPort([]uint8, []uint8, netip.AddrPort) (int, int, error)
- [x] pkg net, method (*UDPConn) WriteToUDPAddrPort([]uint8, netip.AddrPort) (int, error)

### net/http ###

- [x] pkg net/http, func MaxBytesHandler(Handler, int64) Handler
- [x] pkg net/http, method (*Cookie) Valid() error

### net/netip ###

- [x] pkg net/netip, func AddrFrom16([16]uint8) Addr
- [x] pkg net/netip, func AddrFrom4([4]uint8) Addr
- [x] pkg net/netip, func AddrFromSlice([]uint8) (Addr, bool)
- [x] pkg net/netip, func AddrPortFrom(Addr, uint16) AddrPort
- [x] pkg net/netip, func IPv4Unspecified() Addr
- [x] pkg net/netip, func IPv6LinkLocalAllNodes() Addr
- [x] pkg net/netip, func IPv6Unspecified() Addr
- [x] pkg net/netip, func MustParseAddr(string) Addr
- [x] pkg net/netip, func MustParseAddrPort(string) AddrPort
- [x] pkg net/netip, func MustParsePrefix(string) Prefix
- [x] pkg net/netip, func ParseAddr(string) (Addr, error)
- [x] pkg net/netip, func ParseAddrPort(string) (AddrPort, error)
- [x] pkg net/netip, func ParsePrefix(string) (Prefix, error)
- [x] pkg net/netip, func PrefixFrom(Addr, int) Prefix
- [x] pkg net/netip, method (*Addr) UnmarshalBinary([]uint8) error
- [x] pkg net/netip, method (*Addr) UnmarshalText([]uint8) error
- [x] pkg net/netip, method (*AddrPort) UnmarshalBinary([]uint8) error
- [x] pkg net/netip, method (*AddrPort) UnmarshalText([]uint8) error
- [x] pkg net/netip, method (*Prefix) UnmarshalBinary([]uint8) error
- [x] pkg net/netip, method (*Prefix) UnmarshalText([]uint8) error
- [x] pkg net/netip, method (Addr) AppendTo([]uint8) []uint8
- [x] pkg net/netip, method (Addr) As16() [16]uint8
- [x] pkg net/netip, method (Addr) As4() [4]uint8
- [x] pkg net/netip, method (Addr) AsSlice() []uint8
- [x] pkg net/netip, method (Addr) BitLen() int
- [x] pkg net/netip, method (Addr) Compare(Addr) int
- [x] pkg net/netip, method (Addr) Is4() bool
- [x] pkg net/netip, method (Addr) Is4In6() bool
- [x] pkg net/netip, method (Addr) Is6() bool
- [x] pkg net/netip, method (Addr) IsGlobalUnicast() bool
- [x] pkg net/netip, method (Addr) IsInterfaceLocalMulticast() bool
- [x] pkg net/netip, method (Addr) IsLinkLocalMulticast() bool
- [x] pkg net/netip, method (Addr) IsLinkLocalUnicast() bool
- [x] pkg net/netip, method (Addr) IsLoopback() bool
- [x] pkg net/netip, method (Addr) IsMulticast() bool
- [x] pkg net/netip, method (Addr) IsPrivate() bool
- [x] pkg net/netip, method (Addr) IsUnspecified() bool
- [x] pkg net/netip, method (Addr) IsValid() bool
- [x] pkg net/netip, method (Addr) Less(Addr) bool
- [x] pkg net/netip, method (Addr) MarshalBinary() ([]uint8, error)
- [x] pkg net/netip, method (Addr) MarshalText() ([]uint8, error)
- [x] pkg net/netip, method (Addr) Next() Addr
- [x] pkg net/netip, method (Addr) Prefix(int) (Prefix, error)
- [x] pkg net/netip, method (Addr) Prev() Addr
- [x] pkg net/netip, method (Addr) String() string
- [x] pkg net/netip, method (Addr) StringExpanded() string
- [x] pkg net/netip, method (Addr) Unmap() Addr
- [x] pkg net/netip, method (Addr) WithZone(string) Addr
- [x] pkg net/netip, method (Addr) Zone() string
- [x] pkg net/netip, method (AddrPort) Addr() Addr
- [x] pkg net/netip, method (AddrPort) AppendTo([]uint8) []uint8
- [x] pkg net/netip, method (AddrPort) IsValid() bool
- [x] pkg net/netip, method (AddrPort) MarshalBinary() ([]uint8, error)
- [x] pkg net/netip, method (AddrPort) MarshalText() ([]uint8, error)
- [x] pkg net/netip, method (AddrPort) Port() uint16
- [x] pkg net/netip, method (AddrPort) String() string
- [x] pkg net/netip, method (Prefix) Addr() Addr
- [x] pkg net/netip, method (Prefix) AppendTo([]uint8) []uint8
- [x] pkg net/netip, method (Prefix) Bits() int
- [x] pkg net/netip, method (Prefix) Contains(Addr) bool
- [x] pkg net/netip, method (Prefix) IsSingleIP() bool
- [x] pkg net/netip, method (Prefix) IsValid() bool
- [x] pkg net/netip, method (Prefix) MarshalBinary() ([]uint8, error)
- [x] pkg net/netip, method (Prefix) MarshalText() ([]uint8, error)
- [x] pkg net/netip, method (Prefix) Masked() Prefix
- [x] pkg net/netip, method (Prefix) Overlaps(Prefix) bool
- [x] pkg net/netip, method (Prefix) String() string
- [x] pkg net/netip, type Addr struct
- [x] pkg net/netip, type AddrPort struct
- [x] pkg net/netip, type Prefix struct

### reflect ###

- [x] pkg reflect, const Pointer = 22
- [x] pkg reflect, const Pointer Kind
- [x] pkg reflect, func PointerTo(Type) Type
- [x] pkg reflect, method (*MapIter) Reset(Value)
- [x] pkg reflect, method (Value) CanComplex() bool
- [x] pkg reflect, method (Value) CanFloat() bool
- [x] pkg reflect, method (Value) CanInt() bool
- [x] pkg reflect, method (Value) CanUint() bool
- [x] pkg reflect, method (Value) FieldByIndexErr([]int) (Value, error)
- [x] pkg reflect, method (Value) SetIterKey(*MapIter)
- [x] pkg reflect, method (Value) SetIterValue(*MapIter)
- [x] pkg reflect, method (Value) UnsafePointer() unsafe.Pointer

### runtime/debug ###

- [x] pkg runtime/debug, func ParseBuildInfo(string) (*BuildInfo, error)
- [x] pkg runtime/debug, method (*BuildInfo) String() string
- [x] pkg runtime/debug, type BuildInfo struct, GoVersion string
- [x] pkg runtime/debug, type BuildInfo struct, Settings []BuildSetting
- [x] pkg runtime/debug, type BuildSetting struct
- [x] pkg runtime/debug, type BuildSetting struct, Key string
- [x] pkg runtime/debug, type BuildSetting struct, Value string

### strings

- [x] pkg strings, func Clone(string) string
- [x] pkg strings, func Cut(string, string) (string, string, bool)

### sync ###

- [x] pkg sync, method (*Mutex) TryLock() bool
- [x] pkg sync, method (*RWMutex) TryLock() bool
- [x] pkg sync, method (*RWMutex) TryRLock() bool

### syscall ###

- [x] pkg syscall (freebsd-386), type SysProcAttr struct, Pdeathsig Signal
- [x] pkg syscall (freebsd-386-cgo), type SysProcAttr struct, Pdeathsig Signal
- [x] pkg syscall (freebsd-amd64), type SysProcAttr struct, Pdeathsig Signal
- [x] pkg syscall (freebsd-amd64-cgo), type SysProcAttr struct, Pdeathsig Signal
- [x] pkg syscall (freebsd-arm), type SysProcAttr struct, Pdeathsig Signal
- [x] pkg syscall (freebsd-arm-cgo), type SysProcAttr struct, Pdeathsig Signal
- [x] pkg syscall (windows-386), func SyscallN(uintptr, ...uintptr) (uintptr, uintptr, Errno)
- [x] pkg syscall (windows-amd64), func SyscallN(uintptr, ...uintptr) (uintptr, uintptr, Errno)

### testing ###

- [x] pkg testing, func MainStart(testDeps, []InternalTest, []InternalBenchmark, []InternalFuzzTarget, []InternalExample) *M
- [x] pkg testing, method (*F) Add(...interface{})
- [x] pkg testing, method (*F) Cleanup(func())
- [x] pkg testing, method (*F) Error(...interface{})
- [x] pkg testing, method (*F) Errorf(string, ...interface{})
- [x] pkg testing, method (*F) Fail()
- [x] pkg testing, method (*F) FailNow()
- [x] pkg testing, method (*F) Failed() bool
- [x] pkg testing, method (*F) Fatal(...interface{})
- [x] pkg testing, method (*F) Fatalf(string, ...interface{})
- [x] pkg testing, method (*F) Fuzz(interface{})
- [x] pkg testing, method (*F) Helper()
- [x] pkg testing, method (*F) Log(...interface{})
- [x] pkg testing, method (*F) Logf(string, ...interface{})
- [x] pkg testing, method (*F) Name() string
- [x] pkg testing, method (*F) Setenv(string, string)
- [x] pkg testing, method (*F) Skip(...interface{})
- [x] pkg testing, method (*F) SkipNow()
- [x] pkg testing, method (*F) Skipf(string, ...interface{})
- [x] pkg testing, method (*F) Skipped() bool
- [x] pkg testing, method (*F) TempDir() string
- [x] pkg testing, type F struct
- [x] pkg testing, type InternalFuzzTarget struct
- [x] pkg testing, type InternalFuzzTarget struct, Fn func(*F)
- [x] pkg testing, type InternalFuzzTarget struct, Name string

### text/template/parse ###

- [x] pkg text/template/parse, const NodeBreak = 21
- [x] pkg text/template/parse, const NodeBreak NodeType
- [x] pkg text/template/parse, const NodeContinue = 22
- [x] pkg text/template/parse, const NodeContinue NodeType
- [x] pkg text/template/parse, method (*BreakNode) Copy() Node
- [x] pkg text/template/parse, method (*BreakNode) String() string
- [x] pkg text/template/parse, method (*ContinueNode) Copy() Node
- [x] pkg text/template/parse, method (*ContinueNode) String() string
- [x] pkg text/template/parse, method (BreakNode) Position() Pos
- [x] pkg text/template/parse, method (BreakNode) Type() NodeType
- [x] pkg text/template/parse, method (ContinueNode) Position() Pos
- [x] pkg text/template/parse, method (ContinueNode) Type() NodeType
- [x] pkg text/template/parse, type BreakNode struct
- [x] pkg text/template/parse, type BreakNode struct, Line int
- [x] pkg text/template/parse, type BreakNode struct, embedded NodeType
- [x] pkg text/template/parse, type BreakNode struct, embedded Pos
- [x] pkg text/template/parse, type ContinueNode struct
- [x] pkg text/template/parse, type ContinueNode struct, Line int
- [x] pkg text/template/parse, type ContinueNode struct, embedded NodeType
- [x] pkg text/template/parse, type ContinueNode struct, embedded Pos

### unicode/utf8

- [x] pkg unicode/utf8, func AppendRune([]uint8, int32) []uint8

CC @rsc, @ianlancetaylor, @golang/release.

**Comment by ianlancetaylor** [comment]
- bufio: accepted proposal #45727
- bytes: accepted proposal #46336
- crypto/tls: accepted proposal #29257
- debug/buildinfo: accepted in #39301 and #37475; no formal proposal
- debug/elf: routine new constants, no proposal required
- debug/dwarf: routine update for #50685 and #46784, no proposal required
- debug/plan9obj: accepted proposal #48052
- go/ast: updates for generics
- go/constant: accepted in #46211; no formal proposal but it's fine
- go/token: updates for generics
- go/types: updates for generics (accepted proposal #47916)
- net: accepted proposal #46518
- net/http: accepted proposals #39567 and #46370
- net/netip: accepted proposal #46518
- reflect: accepted proposals #47651, #46293, #47658, #48218, #46131, #48294
- runtime/debug: accepted in #39301 and #37475; no formal proposal
- strings: accepted proposals #46336 and #45038
- sync: accepted proposal #45435
- syscall: accepted proposals #46258 and #46552
- testing: accepted proposal #44551
- text/template/parse: accepted proposal #20531
- unicode/utf8: accepted proposal #47609

**Comment by ianlancetaylor** [comment]
The only cases where a concern could be raised are the changes to debug/buildinfo, runtime/debug, and go/constant.  All the rest either have officially affected proposals or clearly do not need them.  To be clear, I think the changes to those three packages are fine.

**Comment by dmitshur** [comment]
Thank you Ian.

Russ, are you able to take a look at the remaining unchecked boxes?

**Comment by rsc** [comment]
constant.Kind.String is fine. I am amused that constant.String is a constant.Kind while constant.Kind.String is not.

**Comment by rsc** [comment]
debug/buildinfo and runtime/debug should have had a proposal. 
It looks like I said otherwise in https://github.com/golang/go/issues/39301#issuecomment-638361488 but that was when I thought it was going into x/mod. My mistake.

Bryan, Michael, Jay, and I did talk a lot about these APIs when they were being designed, though, so I think they have gotten sufficient attention. If I'd noticed this at the start of the freeze I'd have kicked them over to the release process for good measure, but at this point I'm not going to hold up all of Go 1.18. They're OK as is.

Apologies for the mistake and the deviation from standard process. We will endeavor to do better next time.

**Comment by rsc** [comment]
I believe that covers everything. Thanks Ian for checking the proposal issues. I wonder if going forward we should require the API file to have the proposal issue number at the end of the line. That would make this a lot easier for Go 1.19+.
