### ISSUE TITLE
net/http: redirect should requires Location header

### ISSUE THREAD

**Issue by yywing** [golang/go#51345]
When get a http response with status 302 and no Location Header

1.  call  `redirectBehavior ` get `shouldRedirect` `true`  https://github.com/golang/go/blob/master/src/net/http/client.go#L738
2. build next request ,and check Location Header https://github.com/golang/go/blob/master/src/net/http/client.go#L645
3. call `CheckRedirect`

It should be:

1.  call  `redirectBehavior ` get `shouldRedirect` `true`  
2. call `CheckRedirect`
3. build next request ,and check Location Header https://github.com/golang/go/blob/master/src/net/http/client.go#L645

**Comment by mengzhuo** [comment]
Please fulfill the Go issue template, thanks.

**Comment by mengzhuo** [comment]
After reading the xray#1493 I think the title should be 
redirect should requires Location header

And keeping same logic with 307/308
```
if resp.Header.Get("Location") == "" {
		shouldRedirect = false
}

```

Kindly cc @neild for comfirm

**Comment by seankhliao** [comment]
related #49281

**Comment by mengzhuo** [comment]
Thanks.
Duplicated with #49281
