### ISSUE TITLE
affected/package: GO111MODULE conflicts with GOPROXY

### ISSUE THREAD

**Issue by a3sroot** [golang/go#51359]
### What version of Go are you using (`go version`)?

<pre>
$ go version
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/a3sroot/Library/Caches/go-build"
GOENV="/Users/a3sroot/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/a3sroot/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/a3sroot/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.7"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="****/golang/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="****"

</pre>

### Does this issue reproduce with the latest release?

go version go1.17.7 darwin/amd64

### What did you do?

GO111MODULE conflicts with GOPROXY,
When I set GO111MODULE to off, goproxy doesn't take effect.
![image](https://user-images.githubusercontent.com/81551286/155678958-a5e2aee0-53c7-4f24-9d18-0117bb9359d9.png)

### What did you expect to see?

I want to generate the package into src under gopath so that I can go install easily.
i need .a file.

**Comment by mengzhuo** [comment]
This is work as intended, the only module based command (mod, get, etc...) is using GOPROXY as proxy to fetch modules.
You should use other general proxy protocals like HTTP(S)_PROXY to fetch package with GO111MODULE=off

Close WAI
