### ISSUE TITLE
cmd/compile: seg fault with generics, channels and closures 

### ISSUE THREAD

**Issue by KevinStrong** [golang/go#51355]
This bug is re-producable on Go Playground [here](https://go.dev/play/p/wwWYpx-BhIp?v=gotip)

### What version of Go are you using (`go version`)?

<pre>
$ go version go1.18rc1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, go1.18.rc1

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kevinstrong/Library/Caches/go-build"
GOENV="/Users/kevinstrong/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/kevinstrong/go/pkg/mod"
GONOPROXY="github.com/merit"
GONOSUMDB="github.com/merit"
GOOS="darwin"
GOPATH="/Users/kevinstrong/go"
GOPRIVATE="github.com/merit"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/kevinstrong/sdk/go1.18rc1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/kevinstrong/sdk/go1.18rc1/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18rc1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/kevinstrong/code/go-sandbox/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hz/nb5q5m612zl1dkwtzj_jyvvm0000gn/T/go-build3831904386=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

[Here is link to go playground](https://go.dev/play/p/wwWYpx-BhIp?v=gotip)  
It is the same as the link at the top of this post.

### What did you expect to see?

The value "test" printed.

### What did you see instead?

A segmentation fault.

**Comment by mengzhuo** [comment]
CC @griesemer

**Comment by randall77** [comment]
Looks like we're capturing the dictionary for use in the `go`'d closure incorrectly. Instead of putting the dictionary in the closure, we're putting the address of a slot on the stack that contains the dictionary. Of course, that slot is an address on the stack of the caller, which might be long gone by the time the goroutine runs.
Maybe forcing the dictionary to always be captured by value instead of by address would fix it. I thought we already did that, but maybe not.

**Comment by ianlancetaylor** [comment]
This seems to be an incorrect compilation of a valid program, so marking as a release blocker.

CC @danscales

**Comment by randall77** [comment]
@findleyr No, this is definitely backend stuff.
