### ISSUE TITLE
cmd/compile: internal compiler error: missing type [Go 1.18 Beta 2]

### ISSUE THREAD

**Issue by dp-arri** [golang/go#51360]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18beta2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
No.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/puettma/Library/Caches/go-build"
GOENV="/Users/puettma/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/puettma/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/puettma/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/puettma/sdk/go1.18beta2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/puettma/sdk/go1.18beta2/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18beta2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/puettma/dev/experiments/tmp/go18betabug/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_3/h09lh98n15n211s4zkj8cw258f016f/T/go-build840956101=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://go.dev/play/p/u5yZjTiK8aF?v=gotip

### What did you expect to see?

`./prog.go:6:13: use of builtin cap not in function call`

### What did you see instead?

`./prog.go:6:13: internal compiler error: missing type for &{0xc00038af60 [0xc00038af90] false {{{0xc00038af30 6 13}}}} (*syntax.CallExpr)`

**Comment by ALTree** [comment]
Thanks for reporting this.

cc @danscales @griesemer

**Comment by mvdan** [comment]
This is perhaps stating the obvious, but have you tried with go1.18rc1 or Go master (https://pkg.go.dev/golang.org/dl/gotip)? beta2 is nearly a month old at this point.

**Comment by griesemer** [comment]
@mvdan It fails on the tip playground which is  basically up-to-date. So this is definitively a type-checker bug. Must be some trivial oversight given that this just passes. Sigh.

**Comment by mvdan** [comment]
I hadn't noticed the gotip URL parameter in the playground link, good point :)

**Comment by griesemer** [comment]
Looks like some error is supressed where it shouldn't.
```Go
package p

func _() {
        len.Println()
}
```
Trace:
```
testdata/manual.go2:3:6:        -- func _
testdata/manual.go2:3:10:       -- _: func()
testdata/manual.go2:4:20:       -- expr len.Println()
testdata/manual.go2:4:12:       .  -- expr len.Println
testdata/manual.go2:4:9:        .  .  -- expr len
testdata/manual.go2:4:9:        .  .  => len (built-in)
testdata/manual.go2:4:12:       .  => len.Println (invalid operand)
testdata/manual.go2:4:20:       => len.Println() (invalid operand)
```
