### ISSUE TITLE
gomobile  "Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock"  on the ios side

### ISSUE THREAD

**Issue by shumintao** [golang/go#51370]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.7 darwin/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/taoshumin_vendor/Library/Caches/go-build"
GOENV="/Users/taoshumin_vendor/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/taoshumin_vendor/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/taoshumin_vendor/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/Cellar/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.7"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/taoshumin_vendor/go/src/x6t.io/goios/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f3/8ybmg5ls2g768bmzj3wl_48h0000gn/T/go-build4215473156=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```
I use gomobile to package the framework of iOS, and the golang test code runs normally, but ios can't get the unix permission, how to solve this? 

```

- docker.go

<img width="997" alt="image" src="https://user-images.githubusercontent.com/26895243/155823953-64320c72-b048-4787-90b8-7a6d333507e9.png">

- ios swift 
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/26895243/155823908-80dca472-cb61-4d0d-a772-9dfc13c8a5e8.png">

- Macpro M1

<img width="573" alt="image" src="https://user-images.githubusercontent.com/26895243/155824432-2f878816-19f2-40dd-8ecf-16b56da513e9.png">

```
○ cd /var/run/    
(base) ╭─taoshumin_vendor at taoshumin_vendor的MacBook Pro in /var/run
╰─○ ls
auditd.pid                                           com.apple.wifivelocity                               portmap.socket
automount.initialized                                com.docker.vmnetd.sock                               pppconfd
com.apple.AssetCache                                 cupsd                                                resolv.conf
com.apple.DumpPanic.finishedPMUFaultHandling         diskarbitrationd.pid                                 syslog
com.apple.DumpPanic.finishedThisBoot                 docker-cli.sock                                      syslog.pid
com.apple.WindowServer.didRunThisBoot                docker.sock                                          systemkeychaincheck.done
com.apple.dt.instruments.servicehub_64551.32_501.pid filesystemui.socket                                  systemkeychaincheck.socket
com.apple.logind.didRunThisBoot                      fudinit                                              usbmuxd
com.apple.loginwindow.didRunThisBoot                 hdiejectd.pid                                        utmpx
com.apple.mdmclient.daemon.didRunThisBoot            mDNSResponder                                        vpncontrol.sock
com.apple.softwareupdate.availableupdatesupdated     mds                                                  wifi
(base) ╭─taoshumin_vendor at taoshumin_vendor的MacBook Pro in /var/run
╰─○ ll docker.sock 
lrwxr-xr-x  1 root  daemon    47B  2 24 22:57 docker.sock -> /Users/taoshumin_vendor/.docker/run/docker.sock
```

### What did you expect to see?

```
I hope it works fine on the ios side.
```

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
