### ISSUE TITLE
cmd/go: `go get private_module@version_tag` fails if the same commit has been downloaded with pseudo-version previously (before being tagged)

### ISSUE THREAD

**Issue by central182** [golang/go#51374]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes. I've tried 1.16.14 and 1.17.7. (Inside Docker containers from images `golang:1.16.14` and `golang:1.17.7` respectively.)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY="github.com/central182"
GONOSUMDB="github.com/central182"
GOOS="linux"
GOPATH="/go"
GOPRIVATE="github.com/central182"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.14"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/example/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4247023591=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### On my host machine
1. Create a private Go module. (Say it's hosted on https://github.com/central182/foobar and the latest commit is `ef2f664`, with tag `v1.0.9` pointing to some earlier commit.)
2. Launch a Docker container that is able to access my private repositories on GitHub.
```
$ docker run -it -v /home/me/shared_ssh:/root/.ssh golang:1.16.14
```

#### Inside Docker
3. Do the necessary configuration for downloading private Go modules via SSH.
```
$ export GOPRIVATE=github.com/central182
$ git config --global url."ssh://git@github.com".insteadOf "https://github.com"
```
4. Create a temporary Go module.
```
$ cd ~ && mkdir example && cd example && go mod init example
go: creating new go.mod: module example
```
5. Get the `foobar` module with its latest commit hash `ef2f664`.
```
$ go get github.com/central182/foobar@ef2f664
go: downloading github.com/central182/foobar v1.0.10-0.20220226164108-ef2f6641951f
go get: added github.com/central182/foobar v1.0.10-0.20220226164108-ef2f6641951f
```

#### On my host machine
6. Tag `ef2f664` with `v1.0.10` and push it to GitHub.
```
$ git tag v1.0.10
$ git push --tags
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:central182/foobar.git
 * [new tag]         v1.0.10 -> v1.0.10
$ git log --oneline
ef2f664 (HEAD -> main, tag: v1.0.10, origin/main) Empty commit
```

#### Inside Docker
7. Try to get the `foobar` module with the tag `v1.0.10`, and watch it fail.
```
$ go get github.com/central182/foobar@v1.0.10
go get: github.com/central182/foobar@v1.0.10: invalid version: resolves to version v1.0.11-0.20220226164108-ef2f6641951f (v1.0.10 is not a tag)
```
8. However, if I repeat step 7 again, the download will succeed.
```
$ go get github.com/central182/foobar@v1.0.10
go: downloading github.com/central182/foobar v1.0.10
go get: upgraded github.com/central182/foobar v1.0.10-0.20220226164108-ef2f6641951f => v1.0.10
```

### What did you expect to see?

No failure at step 7.

### What did you see instead?

The tag did exist while `go` said otherwise.

**Comment by mengzhuo** [comment]
Duplicate with #51312

**Comment by m1o1** [comment]
Seems the duplicate issue changed to narrow the scope and this seems like a different issue now. We also ran into a similar issue as the one here.

**Comment by central182** [comment]
Now 1.18.4 is out

> supposedly fixing https://github.com/golang/go/issues/51312 according to https://github.com/golang/go/issues/53588

but I can still replicate the issue with the exact steps I described earlier.

@mengzhuo Could you please take a look into this? Or should I create a new issue instead?
