### ISSUE TITLE
proposal: Function evaluation in `if` with variable assignment should be done after checking the conditions

### ISSUE THREAD

**Issue by Kaushal28** [golang/go#51375]
Consider the following code:

```Go
func main() {
    if err := foo(); false && err == nil {
      // ...
    }
}

func foo() error {
    return nil
}
```

Here, `foo` should not be evaluated because condition will result in `false` irrespective of the value of `err`. This applies to similar case with condition:

```Go
err := foo(); true || err == nil
```
Here the condition will be evaluated to `true` in all the cases, so function evaluation is not required at all.

I tried to achieve with different syntax like this:

```Go
func main() {
    if false && (err := foo(); err == nil) {
      // ...
    }
}
```
But it's not allowed in Go. I don't think there is even a way to achieve this currently.

Also, this behaviour will be inline with existing behaviour of `if` statement without variable assignment. Consider the following snippet:

```Go
func main() {
    if false && foo() {
        // ...
    }
}

func foo() bool {
    return true
}

```

Here, because of `false` as an initial condition, the `foo` won't be evaluated at all.

This might save a few lines of code and time to evaluate the function if the other condition(s) can determine the result of the combined condition.

Let me know if this examples/explanation is confusing or I am supposed to provide more details. Thanks!

**Comment by randall77** [comment]
This change is not [backwards compatible](https://go.dev/doc/go1compat), so I don't think we can do it as proposed.

It's easy enough to do currently. Your first example:
```
if false {
    if err := foo(); err == nil {
    }
}
```
It just requires more than one `if` statement.
