### ISSUE TITLE
x/crypto/ssh: data race on c.remoteId

### ISSUE THREAD

**Issue by dvyukov** [golang/go#5137]
<pre>$ go test -race code.google.com/p/go.crypto/ssh

WARNING: DATA RACE
Write by goroutine 20:
  code.google.com/p/go.crypto/ssh.(*clientChan).waitForChannelOpenResponse()
      code.google.com/p/go.crypto/ssh/channel.go:482 +0x250
  code.google.com/p/go.crypto/ssh.(*ClientConn).NewSession()
      code.google.com/p/go.crypto/ssh/session.go:538 +0x1f5
  code.google.com/p/go.crypto/ssh.TestInvalidServerMessage()
      code.google.com/p/go.crypto/ssh/session_test.go:287 +0xb0
  testing.tRunner()
      src/pkg/testing/testing.go:346 +0x12f
  gosched0()
      src/pkg/runtime/proc.c:1209 +0x9f

Previous read by goroutine 22:
  code.google.com/p/go.crypto/ssh.(*channel).sendClose()
      code.google.com/p/go.crypto/ssh/channel.go:105 +0x3f
  code.google.com/p/go.crypto/ssh.(*clientChan).Close()
      code.google.com/p/go.crypto/ssh/channel.go:499 +0x16d
  code.google.com/p/go.crypto/ssh.(*chanList).closeAll()
      code.google.com/p/go.crypto/ssh/client.go:510 +0xe9
  code.google.com/p/go.crypto/ssh.func·005()
      code.google.com/p/go.crypto/ssh/client.go:198 +0xab
  code.google.com/p/go.crypto/ssh.(*ClientConn).mainLoop()
      code.google.com/p/go.crypto/ssh/client.go:203 +0xfb
  gosched0()
      src/pkg/runtime/proc.c:1209 +0x9f

Goroutine 20 (running) created at:
  testing.RunTests()
      src/pkg/testing/testing.go:426 +0xaef
  testing.Main()
      src/pkg/testing/testing.go:358 +0xab
  main.main()
      code.google.com/p/go.crypto/ssh/_test/_testmain.go:125 +0xda
  runtime.main()
      src/pkg/runtime/proc.c:182 +0x91

Goroutine 22 (finished) created at:
  code.google.com/p/go.crypto/ssh.Client()
      code.google.com/p/go.crypto/ssh/client.go:47 +0x2bd
  code.google.com/p/go.crypto/ssh.Dial()
      code.google.com/p/go.crypto/ssh/client.go:431 +0xa7
  code.google.com/p/go.crypto/ssh.dial()
      code.google.com/p/go.crypto/ssh/session_test.go:75 +0x549
  code.google.com/p/go.crypto/ssh.TestInvalidServerMessage()
      code.google.com/p/go.crypto/ssh/session_test.go:285 +0x45
  testing.tRunner()
      src/pkg/testing/testing.go:346 +0x12f
  gosched0()
      src/pkg/runtime/proc.c:1209 +0x9f</pre>

**Comment by hanwen** [comment]
@ianlancetaylor  can be closed.
