### ISSUE TITLE
affected/package: Slices do not cut correctly. 

### ISSUE THREAD

**Issue by Jcowwell** [golang/go#51389]
### What version of Go are you using (`go version`)?

<pre>
go version go1.18rc1 darwin/arm64

</pre>

### Does this issue reproduce with the latest release?

Yes: https://go.dev/play/p/9Xyqfj22OlK

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/jcowwell/Library/Caches/go-build"
GOENV="/Users/jcowwell/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jcowwell/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jcowwell/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18rc1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jcowwell/Local Github Projects/github.com/Jcowwell/go-algorithm-club/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/c8/v4pc4g9d35n8slx7m825npgc0000gn/T/go-build1603233430=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Created a Function to slice elements at a specific index:

```
// Initially Tested with Generic Function but also made a non-Generic Function to be sure. 
func GenericRemoveElementAtIndexFromSlice[T any](slice []T, index int) {
	if index >= len(slice) {
		return
	}
	slice = append(slice[:index], slice[index+1:]...)
}
```
based on this StackOverFlow response: https://stackoverflow.com/a/37335777/6427171

I noticed in the comments that a bug occurs like so: https://go.dev/play/p/9Xyqfj22OlK

My program: https://go.dev/play/p/UxCOi9YKCD8?v=gotip

### What did you expect to see?
Expected to see a slice with an element removed with no duplicate elements at the end. 

EX: 
```
a := []int{1,2,3,4,5,6,7,8} 
RemoveElementAtIndex(a, 0)
> a 
[2,3,4,5,6,7,8]
```

### What did you see instead?

EX: 
```
a := []int{1,2,3,4,5,6,7,8} 
RemoveElementAtIndex(a, 0)
> a 
[2,3,4,5,6,7,8,8]
```

According to the Wiki in SliceTricks, one should be able to cut a value from a slice like so: https://github.com/golang/go/wiki/SliceTricks#cut, 
but when doing so the last value is duplicated. I've provided a Go Playground code snippet to demonstrate this. Thinking of wiring a quick loop to see if there's a minimum/maximum for this occurrence.

**Comment by randall77** [comment]
I think there is some confusion here about how slices work. Please read https://go.dev/blog/slices-intro
In particular, you have to assign the result of `GenericRemoveElementAtIndex` back to `a` in order to change the length of `a`.
There's nothing about generics here - the same problem occurs if you replace `T` with `int`.
