### ISSUE TITLE
x/website: Why is nil mentioned explicitly in t.Fatalf

### ISSUE THREAD

**Issue by 1Mark** [golang/go#51388]
### What is the URL of the page with the issue?
 https://go.dev/doc/tutorial/add-a-test

Instead of 

    t.Fatalf(`Hello("Gladys") = %q, %v, want match for %#q, nil`, msg, err, want)

Use

    t.Fatalf(`Hello("Gladys") = %q, %v, want match for %#q`, msg, err, want)

If agreed, then this should be updated too (transitively)
From

    greetings_test.go:15: Hello("Gladys") = "Hail, %v! Well met!", <nil>, want match for `\bGladys\b`, nil

To

    greetings_test.go:15: Hello("Gladys") = "Hail, %v! Well met!", <nil>, want match for `\bGladys\b`

**Comment by seankhliao** [comment]
nil is the expected error
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
