### ISSUE TITLE
runtime: vdso_linux.go: invalid operation: division by zero

### ISSUE THREAD

**Issue by uhthomas** [golang/go#51383]
### What version of Go are you using (`go version`)?

<pre>
$ bazel run @go_sdk//:bin/go -- version
go version devel go1.17-9a8788c99d Tue Nov 16 10:53:28 2021 +0100 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ bazel run @go_sdk//:bin/go -- env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/thomas/.cache/go-build"
GOENV="/home/thomas/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/thomas/go/pkg/mod"
GONOPROXY="<redacted>"
GONOSUMDB="<redacted>"
GOOS="linux"
GOPATH="/home/thomas/go"
GOPRIVATE="<redacted>"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/thomas/.cache/bazel/_bazel_thomas/b3860946b0ed29b82afe181b73c30609/external/<redacted>/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/thomas/.cache/bazel/_bazel_thomas/b3860946b0ed29b82afe181b73c30609/external/<redacted>/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.17-9a8788c99d Tue Nov 16 10:53:28 2021 +0100"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/thomas/<redacted>/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2864877589=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Follow https://github.com/bazelbuild/rules_go/wiki/Editor-setup.

### What did you expect to see?

No errors.

### What did you see instead?

```
[Error - 4:58:54 PM] Request textDocument/codeAction failed.
  Message: context canceled
  Code: 0 
[Info  - 4:58:55 PM] 2022/02/27 16:58:55 falling back to safe trimming due to type errors: [/home/thomas/.cache/bazel/_bazel_thomas/b3860946b0ed29b82afe181b73c30609/external/go_sdk/src/runtime/vdso_linux.go:55:38: invalid operation: division by zero /home/thomas/.cache/bazel/_bazel_thomas/b3860946b0ed29b82afe181b73c30609/external/go_sdk/src/runtime/vdso_linux.go:56:38: invalid operation: division by zero] or still-missing identifiers: map[memRecordCycle:true pageBits:true]
	package="@io_bazel_rules_go//stdlib:runtime"
```

**Comment by randall77** [comment]
That error doesn't make any sense. That divide is done at compile time, not runtime, and it is clearly a nonzero divide.

I suspect some sort of misinstalled Go. Can you build a Go hello world program and run it?

Your Go version looks like a nonstandard build - can you try using a released version?

Can you show us a complete log of what you did? All the commands you typed and all the output from each of those.

What OS are you running on?
