### ISSUE TITLE
x/pkgsite: package removal request for github.com/tonuniverse/goton

### ISSUE THREAD

**Issue by cryshado** [golang/go#51387]
### What is the path of the package that you would like to have removed?

`github.com/tonuniverse/goton`
 
### Are you the owner of this package?

Yes, I am the owner of the [tonuniverse](https://github.com/tonuniverse) organization
 
### What is the reason that you could not retract this package instead?

The package was published by mistake. I then deleted the repository, 
but after recreating it I was unable to retract the package 😥

**Comment by PythoNyashka** [comment]
The package is marked as `Retracted`, but still shows up in searches at [pkg.go.dev](https://pkg.go.dev/

![telegram-cloud-photo-size-2-5253778196502002159-y](https://user-images.githubusercontent.com/46900925/155954385-f24ec9ee-4f1d-4a6e-ad41-973a7590ab21.jpg)
