### ISSUE TITLE
affected/package: net/internal/socket/sys_unix.go missing function body

### ISSUE THREAD

**Issue by 000191750** [golang/go#51382]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go 1.10.4
</pre>

### Does this issue reproduce with the latest release?
2022/2/27

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>amd64</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I ‘m going to instal go-ssdp, but a promblem raise ,
 go/src/golang.org/x/net/internal/socket/sys_unix.go:16:6: missing function body
go/src/golang.org/x/net/internal/socket/sys_unix.go:19:6: missing function body
go/src/golang.org/x/net/internal/socket/sys_unix.go:22:6: missing function body
go/src/golang.org/x/net/internal/socket/sys_unix.go:25:6: missing function body

I open the file ,there is no return and body in line 16, 19, 22, 25

I don know how to fix it

**Comment by seankhliao** [comment]
1.10 is not supported, use an up to date version
