### ISSUE TITLE
x/pkgsite: package removal request for [github.com/guoliang1994/go-i18n]

### ISSUE THREAD

**Issue by guoliang1994** [golang/go#51393]
### What is the path of the package that you would like to have removed?
github.com/guoliang1994/go-i18n
gopkg.in/guoliang1994/go-i18n.v1
gopkg.in/guoliang1994/go-i18n.v2
 
 
 
### Are you the owner of this package?
yes

 
### What is the reason that you could not retract this package instead?
The package was published by mistake. I want to delete the error versions, I then deleted the tags,
but after recreating it I was unable to retract the version.

**Comment by jamalc** [comment]
I see the retracted versions. To clarify, you want these packages completely removed from pkg.go.dev? This applies to all existing and future versions of a package. Once removed, newer versions will not appear.
