### ISSUE TITLE
x/crypto/ssh: chacha20-poly1305@openssh.com without common MAC algorithm.

### ISSUE THREAD

**Issue by Daedaluz** [golang/go#51406]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/me/.cache/go-build"
GOENV="/home/me/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/me/src/go/pkg/mod"
GONOPROXY="*"
GONOSUMDB="*"
GOOS="linux"
GOPATH="/home/me/src/go"
GOPRIVATE="*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.7"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2220880823=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
package main

import (
	"crypto/rand"
	"golang.org/x/crypto/ed25519"
	"golang.org/x/crypto/ssh"
	"log"
	"net"
)

var sshConfig = &ssh.ServerConfig{
	Config: ssh.Config{
		KeyExchanges: []string{"curve25519-sha256@libssh.org"},
		Ciphers:      []string{"chacha20-poly1305@openssh.com"},
		//MACs:         []string{"hmac-sha1"},
		MACs: []string{},
	},
	NoClientAuth: true,
}

func handleSSHClient(conn net.Conn) {
	sshClient, _, reqs, err := ssh.NewServerConn(conn, sshConfig)
	if err != nil {
		log.Println(err)
		conn.Close()
		return
	}
	go ssh.DiscardRequests(reqs)
	log.Println(err)
	sshClient.Close()
}

func main() {
	_, pKey, _ := ed25519.GenerateKey(rand.Reader)
	signer, _ := ssh.NewSignerFromKey(pKey)
	sshConfig.AddHostKey(signer)
	server, err := net.Listen("tcp", ":2222")
	if err != nil {
		log.Fatal("listen:", err)
	}
	for {
		client, err := server.Accept()
		if err != nil {
			log.Println(err)
			continue
		}
		go handleSSHClient(client)
	}
}

```

### What did you expect to see?
Ignored MAC negotiation since `chacha20-poly1305@openssh.com` offers both encryption and authentication.

### What did you see instead?
`2022/03/01 15:32:24 ssh: no common algorithm for client to server MAC; client offered: [umac-64-etm@openssh.com umac-128-etm@openssh.com hmac-sha2-256-etm@openssh.com hmac-sha2-512-etm@openssh.com hmac-sha1-etm@openssh.com umac-64@openssh.com umac-128@openssh.com hmac-sha2-256 hmac-sha2-512 hmac-sha1], server offered: []`

Adding any of the supported MAC algorithms by the client seems to make the connection work, but as i understand it, 
if using `chacha20-poly1305@openssh.com` then the offered MAC algorithms should be ignored and no MAC is required to be negotiated.

I tested with `ssh -c chacha20-poly1305@openssh.com  -p 2222 localhost`

Did i understand something wrong, or is this a bug?

**Comment by mengzhuo** [comment]
cc @FiloSottile @rolandshoemaker
