### ISSUE TITLE
spec: generic assignment rules are too strict when a constraint includes a single named type

### ISSUE THREAD

**Issue by go101** [golang/go#51403]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18rc1 linux/amd64
</pre>

### What did you do?

```Go
package main

func main() {}

type Bytes []byte

var x []byte
var y Bytes

func init() {
	x = y // okay
	y = x // okay
}

func f[T Bytes](v T) {
	x = v // okay
	y = v // error
	v = x // okay
	v = y // error
}

func g[T ~[]byte](v T) {
	x = v // okay
	y = v // error
	v = x // okay
	v = y // error
}

func h[T Bytes | []byte](v T) {
	x = v // okay
	y = v // error
	v = x // okay
	v = y // error
}
```

### What did you expect to see?

All the assignments in this program are legal

### What did you see instead?

Only half of them are legal.
Honestly, this conforms to the tip spec: https://tip.golang.org/ref/spec#Assignability
But the rules are too strict (comparing to the ordinary value assignment rules).

**Comment by go101** [comment]
In practice, programmers could use two assignments (each one has an operand of unnamed types) to replace the illegal assignment, to walk around this restriction, which makes the restriction look needless.

**Comment by go101** [comment]
And the rules for `make` calls:

```Go
func foo[T chan bool | chan int]() {
	_ = make(T) // error: invalid argument: no core type
}

func bar1[T chan<- int | <-chan int]() {
	_ = make(T) // error: invalid argument: no core type
}
```

The restriction is needless, for a value of `T` could be passed through (value) parameters of type parameters anyway:

```Go
func g(any) {}

func foo_a[T chan bool | chan int](x T) {
	g(x)
}

func bar1_a[T chan<- int | <-chan int](x T) {
	g(x)
}
```

**Comment by go101** [comment]
Maybe the slice expression rule is also over strict for slices and arrays.

```Go
func tag[T []int | [2]int](c T) {
	_ = c[0] // okay
	_ = c[:] // invalid operation: cannot slice c: T has no core type
}
```

**Comment by go101** [comment]
BTW, the description in tip spec is not accurate:

> If a is not a map:
> * the index x must be an untyped constant or its [core type](https://tip.golang.org/ref/spec#Core_types) must be an [integer](https://tip.golang.org/ref/spec#Numeric_types)

However, the `N` type parameter has not a core type:
```Go
func foo[N int | byte](a []int, i N) int {
	return a[i] // okay
}
``` 

Similar for:

> For shifts, the [core type](https://tip.golang.org/ref/spec#Core_types) of both operands must be an integer.

```Go
func bar[N int | byte](x int, i N) int {
	return x << i // okay
}
```

**Comment by go101** [comment]
However, the two defined types are identical here.

**Comment by randall77** [comment]
I think you mean except `g`? That code can clearly have assignments between two different defined types.

For the others, I think the question is, are the defined types `Bytes` and `T`, or `Bytes` and `Bytes`? I don't think the spec is very clear on that point. For structural type constraints, do we use the bound on `T`, or `T` itself?

I would think we want to leave the behavior as is, at least for now. We're close to the release and if there's a question about how things should work, we should err on the side of rejecting programs. We can always loosen later, but we can't tighten later. In addition, there are very easy workarounds for all of these cases - just add a cast.

**Comment by ianlancetaylor** [comment]
CC @griesemer @findleyr 

I don't think we should change anything here for 1.18.  Perhaps we can consider this for 1.19.  These seem like edge cases to me, though.  If they follow the spec as written, then I don't see any particular need to change anything.

**Comment by griesemer** [comment]
I don't believe the rules for assignments are too strict. This works:
```Go
package p

type Bytes []byte

var x []byte
var y Bytes

func init() {
	x = y // okay
	y = x // okay
}

func f[T Bytes](v T) {
	x = v // okay
	y = Bytes(v)
	v = x // okay
	v = T(y)
}

func g[T ~[]byte](v T) {
	x = v // okay
	y = Bytes(v) 
	v = x // okay
	v = T(y)
}

func h[T Bytes | []byte](v T) {
	x = v // okay
	y = Bytes(v)
	v = x // okay
	v = T(y)
}
```
We never allow assignments of differently named types w/o conversions in Go as @randall77 already pointed out, independent of whether the code is generic or not. `T` is a named type and so is `Bytes`. We need a conversion when we move from one to the other. We are not going to change that.

With respect to these rules, note that they now rely on the notion of a [named type](https://tip.golang.org/ref/spec#Types) which is clearly defined. Type parameters are named types. I believe these rules are pretty clear.

The `make` rules seem fine as is. If you have concrete reasons why they do not work for important cases, please file a proposal.

The spec error with respect to shifts is known (#51182). Indexing rules have a special section on type parameters. Slicing rules could be relaxed but it gets complicated quickly. We're not going to change that for 1.18, and we probably should require a proposal for that.

More generally, please file individual issues for different problems, otherwise it is different to keep track of what's taken care of and what is not. Thanks.

I am going to close this. I don't see any need for action here besides what is already known.

**Comment by go101** [comment]
> The make rules seem fine as is. If you have concrete reasons why they do not work for important cases, please file a proposal.

As I have mentioned above, if type parameter `x` of type `T` is allowed, then the `y` variable should be probably too.
And I don't see any harm made by allowing `y`.
And will allowing `y` reduce a bit compiler implementation complexity?

```Go
func g(any) {}

func foo_a[T chan bool | chan int](x T) {
	g(x)
	var y = make(T)
	g(y)
}
```
I don't know whether or not the current approach will affect user happiness.
It is not bad to keep things unchanged now, and let somebody make a proposal to change it later.

**Comment by griesemer** [comment]
@go101 The harm is a more complicated rule for `make`. Extra complexity may be justified if this is an important use case but I think the jury is still out on that. Let's see what people are going to do with generics and then take it from there. Thanks.

**Comment by go101** [comment]
I see, except that I don't understand "The harm is a more complicated rule for `make`". At least from user perspective, the rule becomes simpler and it will make things more consistent.

I agree this is not important enough to be settled down in 1.18.

**Comment by griesemer** [comment]
@go101 Please suggest the new (simpler) rule for the spec as a proposal and assign it to me. If it is indeed simpler, we may consider it for 1.19. Thanks.

**Comment by go101** [comment]
> Please suggest the new (simpler) rule 

Doesn't removing the core type requirement for `make` calls make the rule simpler?

From the user perspective, if the type of a value used in a generic function is specified,
either it is an ordinary type or a type parameter type, the value should be legal.
For example, in the following code, `foo` and `bar` both compiles okay, but
`dot` doesn't. This rule is simple to explain. Adding extra restrictions makes things complicate.

```Go
func foo[T int|string](x T) {
	_ = x // okay
}

func bar[T [2]int|[8]int](x T) {
	_ = x[1] // okay
}

func dot[T [2]int|[2]string](x T) {
	_ = x[1] // error: invalid operation: cannot index x
}
```

**Comment by griesemer** [comment]
I don't see a rule here, just examples. "should be legal" is not really a sufficient explanation. But let's not discuss this here, this issue is closed. If you have a concrete suggestion (not an example), please file a proposal. For reference, [here](https://tip.golang.org/ref/spec#Making_slices_maps_and_channels) are the current rules for `make`. Thanks.

**Comment by go101** [comment]
Okay. I will make one when I clear my thoughts. The rule might be "the specific types must be of the same type kind".
