### ISSUE TITLE
exp/vulncheck/internal/binscan: inlined vulnerable symbols not detected in Binary(...)

### ISSUE THREAD

**Issue by zpavlinovic** [golang/go#51412]
### Does this issue reproduce with the latest release?

Yes.

### What did you do?

Removed the `noinline` annotation from the code in `binary_test.go` of https://go-review.googlesource.com/c/exp/+/386199.

### What did you expect to see?

Vulnerable symbols reported.

### What did you see instead?

No vulnerable symbols reported.

It seems that the logic for extracting all symbols in a binary is not picking this up.

cc @rolandshoemaker

thanks @neild for bringing this to attention

**Comment by jba** [comment]
Inlined symbols are not visible in the official way to read a binary, the `debug/gosym` package. After constructing a `gosym.Table` with
```
    lineTab := gosym.NewLineTable(pclntab, textOffset)
    if lineTab == nil {
        return nil, nil, errors.New("invalid line table")
    }
    tab, err := gosym.NewTable(nil, lineTab)
```
I looked through all of `tab` and did not see the inlined symbol. 

This assumes that the code for opening binaries in https://go.googlesource.com/vuln/+/80a8e6d117ee69f5f35757fa24d5f7600294fd8b/vulncheck/internal/binscan/exe.go is correct.

**Comment by zpavlinovic** [comment]
@neild mentioned in an offline discussion that the information about inlined symbols might be in the binary, but not in the symbol tables. If I recall correctly, inlined code could have a pointer to is original function (used for debugging purposes).

**Comment by jba** [comment]
I'm currently working on extracting the information from the DWARF data.
