### ISSUE TITLE
cmd/compile: irgen uses wrong dict param to generate code for getting dict type

### ISSUE THREAD

**Issue by mdempsky** [golang/go#51413]
Since submitting https://go-review.googlesource.com/c/go/+/388534, the linux-amd64-noopt builder is failing in test/typeparam/mdempsky/13.go:

https://build.golang.org/log/e4383af359722053b9d212fc3c8c69351e0ffbd1

```
##### ../test
# go run run.go typeparam/mdempsky/13.go
exit status 2
# command-line-arguments
typeparam/mdempsky/13.go:38:3: internal compiler error: 'G[go.shape.interface { Abs() "".MyInt }_0,go.shape.int_1].func1': addr of undeclared ONAME .dict. declared: map[a0:v5 r0:v6 .dict:v4]
```

I'm not immediately able to reproduce this failure locally.

/cc @danscales @randall77

**Comment by mdempsky** [comment]
Oh, I forgot the noopt builder uses `-N -l`, not just `-N`.

This is repro'able with `go run -gcflags="-N -l" test/typeparam/mdempsky/13.go`.

A slightly different failure message occurs with `-gcflags=-l` instead:

```
# command-line-arguments
./13.go:38:3: internal compiler error: 'G[go.shape.interface { Abs() "".MyInt }_0,go.shape.int_1].func1': Value live at entry. It shouldn't be. func G[go.shape.interface { Abs() "".MyInt }_0,go.shape.int_1].func1, node .dict, value nil
```

**Comment by cuonglm** [comment]
It seems to me this issue should be cherry pick to 1.18 branch

cc @randall77 @danscales @mdempsky

**Comment by mdempsky** [comment]
I think so too. Otherwise delve will have issues debugging generic code, right?

**Comment by cuonglm** [comment]
> I think so too. Otherwise delve will have issues debugging generic code, right?

Yeah, indeed. delve is the biggest user of `-gcflags="-N -l"

**Comment by cuonglm** [comment]
Reopening for backport to 1.18 release branch.

**Comment by dmitshur** [comment]
@cuonglm Thanks for flagging this issue.

We've discussed it on the release (and compiler) team. It is important for it to be fixed, but this late in the Go 1.18 release cycle we need to prioritize not to make more changes before the final release.

As a result, we'll consider this fix for backport to Go 1.18.1 (which is no more 2-3 weeks away from today) rather than blocking the final Go 1.18 release on it (scheduled for this week). Updating this issue accordingly.

**Comment by dmitshur** [comment]
@gopherbot Please consider this for backport to 1.18. This is a serious issue—see https://github.com/golang/go/issues/51460#issuecomment-1067119330 and https://github.com/golang/go/issues/51460#issuecomment-1067151392 for detailed rationale to backport.

**Comment by cuonglm** [comment]
This issue can now be closed.
