### ISSUE TITLE
access: go-approvers

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#51422]
See https://go.dev/wiki/GithubAccess

Hi, I've been a go-approver for several years and was suddenly removed from GitHub's Go organization yesterday... Apparently, I am still an approver in the Gerrit.

* Activity: [issues](https://github.com/golang/go/issues?q=is%3Aissue+commenter%3Ahajimehoshi)
* Contributions: [gerrit](https://go-review.googlesource.com/q/owner:hajimehoshi%2540gmail.com), [golang/go](https://github.com/golang/go/commits?author=hajimehoshi), [golang/mobile](https://github.com/golang/mobile/commits?author=hajimehoshi)

Could I be a member again?

/CC @hyangah @dmitris @changkun @matloob @johanbrandhorst 

Thanks,

**Comment by ALTree** [comment]
cc @golang/release

**Comment by dmitshur** [comment]
Hi Hajime,

Thanks for making this request. Apologies for the removal, it was the action of an automated robot and just needed us to manually restore access. I've re-added you to the Go GitHub organization now, so this should be resolved. (You'll need to accept an invite.)

Thank you for your continued contributions to Go!

**Comment by hajimehoshi** [comment]
Thanks!
