### ISSUE TITLE
net.go: What is the reasoning behind mapping errors?

### ISSUE THREAD

**Issue by gprossliner** [golang/go#51427]
Hello!

I'm currently developing a tool involving testing the availability of different external services. Among others, TCP and HTTP are supported. Cancelation is done by passing a context.Context instance. I need to handle context.Canceled specially.

What behaves like expected is `http.NewRequestWithContext`. It returns an context.Canceled error.
What was unexpected to me is that `net.dialer.DialContext` returns just a string error (`errors.New("operation was canceled")`  net.go:412) on cancelation. Because it doesn't wrap the original error, this is hard to handle.

I debugged the stdlib, and came to this func:
https://github.com/golang/go/blob/40e24a942bce7b10e23a7282e673ac8a758ca378/src/net/net.go#L425-L434

* What is the reasoning behind mapping specific errors with "string-errors" generally?
* Why is the original error not wrapped?

**Demo (all pseudo code, will not compile!)**
```go

type Test interface {
  Test(ctx context, Context) error
}

// httpTest is a struct implementing the "Test" interface
func (t httpTest) Test(ctx context, Context) error {
  httpRequest, _ := http.NewRequestWithContext(ctx, "GET", t.url, nil)
  response, err := http.DefaultClient.Do(httpRequest)
  if err != nil {
	return err
  }
}

// tcpTest is a struct implementing the "Test" interface
func (t tcpTest) Test(ctx context, Context) error {
  dialer := &net.Dialer{ }
  con, err := dialer.DialContext(ctx, "tcp", t.endpoint)
  if err != nil {
    return err
  }
}
```

Error-Handling takes place in the caller code. I also need to know if the Operation has ben canceled, like:
```go
func RunTest(ctx, test Test) {
  err := test.Run(ctx)

  // handle Context Cancalation
  if errors.Is(err, context.Canceled) {
    fmt.Println("Context Canceled")
  } else {
   // tcpTest branches to else on cancelation, which is unexpected
    fmt.Println("Error: "+ err.Error())    
  }
}

```

Thanks!

**Comment by mengzhuo** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by gprossliner** [comment]
Hi @mengzhuo! Thanks for the immediate action, Closing ... :-(

I understand this policy. But I really think that this should be considered a Issue.
Maybe I should rewrite / rephase it.

**Comment by mengzhuo** [comment]
> Hi @mengzhuo! Thanks for the immediate action, Closing ... :-(
> 
> I understand this policy. But I really think that this should be considered a Issue. Maybe I should rewrite / rephase it.

Well, unfortunately closing question is triage protocal.
I think you might want to proposal about new exported error type in net packages.
https://github.com/golang/proposal#readme

**Comment by ianlancetaylor** [comment]
`mapErr` exists because when we introduced contexts into the net package we didn't want to break existing code by changing the errors that were returned.
