### ISSUE TITLE
crypto/tls: run BoringSSL test suite (BoGo)

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#51434]
BoringSSL has an extensive TLS test suite with a mechanism to run it against other TLS stacks. We should hook it up to crypto/tls.

**Comment by ianlancetaylor** [comment]
CC @golang/security 

Looks like this didn't make 1.19.  Moving to Backlog.  Please recategorize as appropriate.  Thanks.

**Comment by FiloSottile** [comment]
In the same vein, we should consider running the https://github.com/tlsfuzzer/tlsfuzzer test suite, too.
