### ISSUE TITLE
x/vulndb: build broken on release-branch.go1.16 since CL 386696

### ISSUE THREAD

**Issue by bcmills** [golang/go#51433]
The `x/vulndb` build has been broken on the `release-branch.go1.16` builder since [CL 386696](https://go.dev/cl/386696) (CC @jba @julieqiu @neild). The failure was detected and reported by the TryBots (https://go-review.googlesource.com/c/vulndb/+/386696/3#message-00588b82f4f505c7202a3ccb89e76fc690afa4a7), but the CL was committed without addressing the breakage.

The policy of the Go project (documented in #11811) is that the builds for the `x/` repos need to stay green, so this is a release-blocker for the Go 1.16.15 minor release (CC @golang/release).

If we don't actually care about this repo on this configuration, the builders can be configured not to run it. However, from the failure message it should also be straightforward to address by running `go mod tidy -go=1.16` and committing the resulting `go.sum` changes.

**Comment by bcmills** [comment]
(Assigning to @cagedmantis at his request.)

**Comment by dmitshur** [comment]
> If we don't actually care about this repo on this configuration, the builders can be configured not to run it.

This has been done in [CL 388934](https://go.dev/cl/388934), submitted at the time of this posting. I'll update this issue once coordinator is redeployed with that change.

@bcmills Will it be helpful to clear the failing test results, or is redeploying the new builder policy sufficient to resolve this?

**Comment by dmitshur** [comment]
Coordinator with build policy change in CL 388934 is deployed, so at least new builds won't happen. I'll leave the rest to Carlos and Bryan here.

**Comment by bcmills** [comment]
> Will it be helpful to clear the failing test results, or is redeploying the new builder policy sufficient to resolve this?

Ordinarily it would be helpful to clear the failures, although I've already collected today's failures for triage so it probably isn't necessary.

**Comment by bcmills** [comment]
Looks like `build.golang.org` is no longer showing the failure, and since the Coordinator will no longer run the repo it won't continue to add noise in the builder triage process, so I believe this is resolved. Closing.
