### ISSUE TITLE
affected/package: The problem about 'new []int'

### ISSUE THREAD

**Issue by NbTOne** [golang/go#51450]
![image](https://user-images.githubusercontent.com/39721050/156519295-abac6a5d-db40-4da1-ad3f-1b990f760b93.png)

It doesn't look normal. Why?

**Comment by mengzhuo** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by mengzhuo** [comment]
Please check [Type Identity](https://go.dev/ref/spec#Type_identity) for detail.
> Two array types are identical if they have identical element types and the same array length.

However for size zero:
> A struct or array type has size zero if it contains no fields (or elements, respectively) that have a size greater than zero. Two distinct zero-size variables may have the same address in memory.

Here is a quick example:
https://go.dev/play/p/aW7RTypVY8g
