### ISSUE TITLE
net/http ServeContent > checkIFMatch checks for "Etag" instead of "ETag" header.

### ISSUE THREAD

**Issue by dlfoo** [golang/go#51451]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.17 darwin/amd64

</pre>

### Does this issue reproduce with the latest release? 

Yes and it looks to also be in 1.18

https://cs.opensource.google/go/go/+/refs/tags/go1.17.7:src/net/http/fs.go;drc=2f0e5bf907b16a8106ae68920edffe90362e16ce;l=412
https://cs.opensource.google/go/go/+/refs/tags/go1.18rc1:src/net/http/fs.go;drc=6df0957060b1315db4fd6a359eefc3ee92fcc198;l=412

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Attempted to set the "ETag" on the http.ResponseWriter passed into the [checkIFmatch](https://cs.opensource.google/go/go/+/refs/tags/go1.17.7:src/net/http/fs.go;drc=2f0e5bf907b16a8106ae68920edffe90362e16ce;l=391) func.

### What did you expect to see?
A match.

### What did you see instead?
No Match because I was using "ETag" not "Etag".

**Comment by seankhliao** [comment]
the header map uses a single canonical capitalization (textproto.CanonicalMIMEHeaderKey) as documented by its exported methods, use that.

**Comment by seankhliao** [comment]
[RFC 7230](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2) states that headers are case insensitive, Go's behaviour is following spec, your client isn't.
