### ISSUE TITLE
cmd/compile: double error when break is not in a loop

### ISSUE THREAD

**Issue by alicebob** [golang/go#51456]
### What version of Go are you using (`go version`)?

<pre>
go version devel go1.19-d3fe4e193e Thu Mar 3 16:02:44 2022 +0000 linux/amd64
</pre>

and

<pre>
go version go1.18rc1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

(edit) No, on 1.17.7 it's a single error.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/harmen/.cache/go-build"
GOENV="/home/harmen/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/harmen/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/harmen/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/harmen/src/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/harmen/src/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.19-d3fe4e193e Thu Mar 3 16:02:44 2022 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2287321463=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```
package main

func main() {
	break
}
```

https://go.dev/play/p/pyIH7X9EZMT?v=gotip

### What did you expect to see?

A single error

### What did you see instead?

```
harmen@umount:/tmp$ go run foo.go
# command-line-arguments
./foo.go:4:2: break is not in a loop, switch, or select
./foo.go:4:2: break is not in a loop, switch, or select statement
harmen@umount:/tmp$ 
```

**Comment by ALTree** [comment]
Thanks for reporting this. Tentatively putting it in the 1.19 milestone because it's a (non-serious) 1.18 regression.

**Comment by ianlancetaylor** [comment]
CC @griesemer 

Rolling forward to 1.20.  Please comment if you disagree.  Thanks.
