### ISSUE TITLE
Go 1.18 beta reports M1 MacBook as AMD64 instead of ARM64

### ISSUE THREAD

**Issue by achille-roussel** [golang/go#51464]
### What version of Go are you using (`go version`)?

```
$ go version
go version go1.18beta1 darwin/amd64
```

### Does this issue reproduce with the latest release?

1.18 beta2 seems affected as well:

```
$ go1.18beta2 version
go version go1.18beta2 darwin/amd64
```

gotip is not:
```
$ gotip version
go version devel go1.19-4f04e1d Tue Mar 1 06:01:28 2022 +0000 darwin/arm64
```
```
$ gotip env
GO111MODULE="on"
GOARCH="arm64"
```

### What operating system and processor architecture are you using (`go env`)?

I am using a MacBook M1 (arm64) with OSX 12.2

### What did you do?

Building programs that use build tags of file extensions to provide architecture-specific code breaks because assembly routines that generate AMD64 code are compiled on ARM64 systems.

### What did you expect to see?

`go version` and `go env` should properly detect that the platform is arm64 and not amd64, for example:

```
$ go version
go version go1.18beta1 darwin/arm64
```

### What did you see instead?

(see output of `go version`)

**Comment by seankhliao** [comment]
You installed the wrong version but it's running because of rosetta 2. Install the arm64 version.

**Comment by achille-roussel** [comment]
User issues indeed, I realized this afterwards when reinstalling Go! 

I go confused by OSX/M1 being able to run some amd64 programs (it breaks on some vectorized instructions).

Thanks for following up quickly!
