### ISSUE TITLE
cmd/compile: embedding comparable is not considered in calculating type sets

### ISSUE THREAD

**Issue by go101** [golang/go#51472]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18rc1 linux/amd64
</pre>

### What did you do?

```Go
package main

func main() {
	foo("Abc")
	foo([]byte{}) // compiles okay, but should not
}

type C interface {
	comparable
	[]byte | string
}
	
func foo[T C](x T) {}
```

### What did you expect to see?

Fails to compile.

### What did you see instead?

Compiles okay.

**Comment by ianlancetaylor** [comment]
CC @griesemer @findleyr

**Comment by griesemer** [comment]
Briefly looked at this. It appears we're forgetting to consider the "comparable" field in typesets under some circumstances. Appears like a trivial oversight, as the actual type set computations are ok. Will fix tomorrow.

**Comment by griesemer** [comment]
Quick update: fix is pending but given that we're so short before the release, I'll spend some time adding more tests; this shouldn't have slipped. CL probably later today or tomorrow.
