### ISSUE TITLE
x/pkgsite: where is the Request button for adding a new package?

### ISSUE THREAD

**Issue by flyflypeng** [golang/go#51471]
### What is the URL of the page with the issue?

https://pkg.go.dev/about#adding-a-package

### What is your user agent?
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36

### Screenshot

![image](https://user-images.githubusercontent.com/8475378/156691224-b7322aae-02ef-4b4f-847b-f95bd98568b9.png)

### What did you do?

I want to find the "Request" button on the https://pkg.go.dev/ page.

### What did you expect to see?

I want to find the "Request" button on the https://pkg.go.dev page, so I can make a request to add a new package.

### What did you see instead?

No Request button on the https://pkg.go.dev page.

![image](https://user-images.githubusercontent.com/8475378/156691594-ff2f402a-1755-4254-9027-4e602fb36e51.png)

**Comment by seankhliao** [comment]
the faq linked in the page has answers.
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
