### ISSUE TITLE
go/types, types2: missing type due to delayed type-type inference

### ISSUE THREAD

**Issue by findleyr** [golang/go#51489]
This is a follow-up on #51233: in type declarations, it is possible to substitute for type arguments before they are fully resolved.

While investigating this afternoon I was able to construct another crasher:
https://go.dev/play/p/V5Jl7-WDV4K?v=gotip

This may be complicated, but the mechanism is simple: force an expansion of T before R[int] is resolved. In this case, this is forced by the call to `var x = T[int]{}.F`. We currently lack controls to ensure that inference happens before substitution. I am not sure whether it is trivial to introduce such a mechanism.

CC @griesemer

**Comment by findleyr** [comment]
In #51527 we have disabled type-type inference for 1.18, so this can be moved to 1.19.

**Comment by ianlancetaylor** [comment]
Rolling forward to 1.20.  Please comment if you disagree.  Thanks.

**Comment by findleyr** [comment]
I don't think we're ever going to add type-type inference, and if we do the mechanism will be different. So I think this is no longer relevant.
