### ISSUE TITLE
cmd/compile: a little inconsistency on uses of type parameters in type parameter lists

### ISSUE THREAD

**Issue by go101** [golang/go#51499]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18rc1 linux/amd64
</pre>

### What did you do?

```Go
type C1[T []T] struct{} // okay
type C2[T *T] struct{}  // error: undefined: T
```

### What did you expect to see?

Both compiles.

### What did you see instead?

The second one doesn't compile.

Not sure if this is intended, just feel they should be consistent.

**Comment by ianlancetaylor** [comment]
CC @griesemer 

For 1.19.

**Comment by griesemer** [comment]
This is working correctly according to the spec. The `C2` type parameter list is ambiguous and [per the spec](https://tip.golang.org/ref/spec#Type_parameter_lists) and is parsed as an (invalid) array declaration since `T` is unknown. These work:
```Go
type C2[T *T,] struct{}
type C3[T interface{*T}] struct{}
```
