### ISSUE TITLE
cmd/dist: when using GOROOT_FINAL, require GOROOT to be explicitly provided

### ISSUE THREAD

**Issue by dmitshur** [golang/go#51504]
Based on my current understanding, I think we should make it a fatal error if the GOROOT_FINAL environment variable is set to a non-empty string, but the GOROOT environment variable is unset or set to an empty string. Doing this should reduce the costs of maintaining and developing Go, without negatively affecting utility.

That is, if GOROOT_FINAL needs to be set (rare), it isn't unreasonable to require GOROOT to also be set explicitly in order to avoid possible ambiguity that arises if it isn't set.

This is a follow up from https://github.com/golang/go/issues/50893#issuecomment-1024680292.

Issue #42563 might be relevant here, in that this requires knowing the explicit environment the user provided while calling make.bash, and not get confused if make.bash itself [sets GOROOT](https://github.com/golang/go/blob/55a60cadc3f5d01f76ac9435da2ed941e194a29b/src/make.bash#L166).

**Comment by iwdgo** [comment]
GOROOT_FINAL has been removed following https://github.com/golang/go/issues/62047. Documentation indicates when GOROOT could be set. There does not seem to be anything left to do for this issue.
