### ISSUE TITLE
crypto/elliptic: mention P-521 slowdown in Go 1.18 release notes

### ISSUE THREAD

**Issue by pascaldekloe** [golang/go#51508]
The release notes for Go 1.18 state “P-224 and P-384 are now approximately four times faster.”, which is correct. However, it fails to mention the two times slower for P-521. I would argue that such a significant loss in performance is something people should be aware of.

**Comment by ALTree** [comment]
cc @FiloSottile

**Comment by dibrinsofor** [comment]
@bcmills can I take this up?

**Comment by dmitshur** [comment]
@dibrinsofor Thanks, it's fine to prepare a CL as long as you're taking into account that this issue is currently in NeedsDecision [state](https://go.dev/wiki/HandlingIssues#needs-decision).

**Comment by ianlancetaylor** [comment]
CC @golang/security 

This issue is about the 1.18 (not 1.19) release notes.  I'm not sure exactly what to write.  Anybody want to send a patch?  Thanks.

**Comment by pascaldekloe** [comment]
It's way too late now. 🤣
