### ISSUE TITLE
x/website: incorrect expected release date for Go 1.18  

### ISSUE THREAD

**Issue by golangninja** [golang/go#51505]
The expected release date **was** February, 2022; however, the date has already been exceeded. Please update the following page: https://tip.golang.org/doc/go1.18

**Comment by ianlancetaylor** [comment]
Thanks, my understanding is that that note will be removed as part of the release process.

CC @golang/release

**Comment by dmitshur** [comment]
The draft notice is indeed removed as part of resolving #47694.
I've sent [CL 390374](https://go.dev/cl/390374) to update the expected release date, and another that removes the notice.
