### ISSUE TITLE
go/pkg/tool/windows_amd64/pack.exe: PUA:Win32/Caypnamer.A!ml

### ISSUE THREAD

**Issue by dsyx** [golang/go#51514]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.17.8 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GOHOSTARCH=amd64
set GOHOSTOS=windows
</pre></details>

### What did you do?

I downloaded the [latest (1.17.8) Go](https://go.dev/dl/go1.17.8.windows-amd64.zip) from go.dev and extracted it. Then, windows defender popped up a warning:

```
This app has been blocked

Detected: PUA:Win32/Caypnamer.A!ml
Status: Deleted
... ...

Affected items:
    file: C:\go\pkg\tool\windows_amd64\pack.exe
```

However the version (1.17.2) I was using before did not receive such a warning.

**Comment by ALTree** [comment]
Thanks for reporting this, but it's a false positive caused by the fact that the 1.17.8 binary is newer; also see https://go.dev/doc/faq#virus. Complaining to your antivirus vendor may convince them to stop flagging Go binaries.
