### ISSUE TITLE
vendor/golang.org/x/sys/unix/syscall_linux_gc.go:10:6: missing function body

### ISSUE THREAD

**Issue by jiangxiaobin96** [golang/go#51513]
### What version of Go are you using (`go version`)?

<pre>
$ go version 
go version go1.17 linux/riscv64
</pre>

### What operating system and processor architecture are you using (`go env`)?
GOARCH="riscv64"

### What happened?
When i build dashboard-metrics-scraper and met the following errors.
```
# golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/syscall_linux_gc.go:10:6: missing function body
vendor/golang.org/x/sys/unix/syscall_linux_gc.go:14:6: missing function body
vendor/golang.org/x/sys/unix/syscall_unix_gc.go:12:6: missing function body
vendor/golang.org/x/sys/unix/syscall_unix_gc.go:13:6: missing function body
vendor/golang.org/x/sys/unix/syscall_unix_gc.go:14:6: missing function body
vendor/golang.org/x/sys/unix/syscall_unix_gc.go:15:6: missing function body
```
I find the similar answer about [loongson](https://github.com/loongson/go/issues/1) but don't know where to download sys source code for RISCV64.
So how to solve this problem?

**Comment by mengzhuo** [comment]
This is unrelated to the Go project. 
You should update version of golang.org/x/sys/unix in `dashboard-metrics-scraper`.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
