### ISSUE TITLE
x/net/publicsuffix: effectiveTDLPlusOne for subdomain of amazonaws.com yields wrong value

### ISSUE THREAD

**Issue by leandrosansilva** [golang/go#51510]
When calling `publicsuffix.EffectiveTLDPlusOne("inbound-smtp.us-east-1.amazonaws.com")`, I'd expect to obtain `amazonaws.com`, but instead I obtain the unmodified value `inbound-smtp.us-east-1.amazonaws.com`.

Tested version: latest as on `2022-03-06`.

Some code reproducing the issue (on playground: https://go.dev/play/p/VAYufCl2LDY):

```go
package main

import (
	"fmt"

	"golang.org/x/net/publicsuffix"
)

func main() {
	domains := []string{
		"amazon.co.uk",
		"books.amazon.co.uk",
		"www.books.amazon.co.uk",
		"amazon.com",
		"inbound-smtp.us-east-1.amazonaws.com",
	}

	for _, domain := range domains {
		eTLDPlusOne, _ := publicsuffix.EffectiveTLDPlusOne(domain)

		fmt.Printf("%s -> %s\n", domain, eTLDPlusOne)
	}
}
```

The result is:
```
amazon.co.uk -> amazon.co.uk
books.amazon.co.uk -> amazon.co.uk
www.books.amazon.co.uk -> amazon.co.uk
amazon.com -> amazon.com
inbound-smtp.us-east-1.amazonaws.com -> inbound-smtp.us-east-1.amazonaws.com
```

**Comment by mengzhuo** [comment]
cc @neild

**Comment by rentiansheng** [comment]
I also found this issue .
reason:
psl-maintainers@amazon.com at https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat
Submit "us-east-1.amazonaws.com" domain .

publicsuffix.EffectiveTLDPlusOne( "inbound-smtp.us-east-1.amazonaws.com") 

result :  "inbound-smtp.us-east-1.amazonaws.com".  not expect "us-east- 1. amazonaws.com"

**Comment by leandrosansilva** [comment]
Hi @rentiansheng, it seems that the publicsuffix database is quite messy regarding those domains. 

For instance, `EffectiveTDLPlusOne("inbound-smtp.eu-west-1.amazonaws.com")` properly yields `amazonaws.com`, and the only difference is that `east` becomes `west`.

An update version of the sample code is at: https://go.dev/play/p/McXmywFKGG0

Probably the solution there is either adding `west` to the database (and maybe all the other variations) or remove both from the database.

Should I close the current issue and open one at the `publicsuffix` repository?

For the context, my current use case is  to obtain a company's main domain from some SMTP relay domain name. Please let me now if anyone thinks publicsuffix is not suitable for that.

**Comment by jub0bs** [comment]
@leandrosansilva This is expected behaviour.

`us-east-1.amazonaws.com` is (at the time of writing) the most specific suffix in the [PSL](https://publicsuffix.org/list/public_suffix_list.dat) that matches domain `inbound-smtp.us-east-1.amazonaws.com`.

Therefore, the eTLD+1 is `us-east-1.amazonaws.com` plus the label immediately to the left, i.e. `inbound-smtp.us-east-1.amazonaws.com`.

**Comment by dpanic** [comment]
I have another situation with amazonaws.com.
domain, err := publicsuffix.EffectiveTLDPlusOne("ec2-1-1-1-1.compute-1.amazonaws.com")
publicsuffix: cannot derive eTLD+1 for domain "ec2-1-1-1-1.compute-1.amazonaws.com"

While others work:
test.test.amazonaws.com -> amazonaws.com
test.123.amazonaws.com -> amazonaws.com

**Comment by jub0bs** [comment]
@dpanic 

Working as expected. The [public-suffix list](https://publicsuffix.org/list/public_suffix_list.dat) contains the entry `*.compute-1.amazonaws.com`. Therefore, according to the [spec](https://github.com/publicsuffix/list/wiki/Format), `ec2-1-1-1-1.compute-1.amazonaws.com` is an eTLD. Therefore, you cannot derive its eTLD+1; you'd need [one more label on the left](https://go.dev/play/p/myPScO6h6W4) for that.

**Comment by dpanic** [comment]
Great. I think there should be one more function which can bypass such
behaviour for *.amazonaws.com and similar.
Something which can extract real TLD + one.
For me it is not logical that (even if present in public suffix list)
compute-1.amazonaws.com is treated as TLD.

**Comment by dpanic** [comment]
> ec2-1-1-1-1.compute-1.amazonaws.com

Sure. Implemented workaround. https://go.dev/play/p/1xKKMF0RzV-

``` Go
// ExtractDomain extracts domain from suffix list
func ExtractDomain(hostname string) (domain string, err error) {
	tmp := strings.Split(hostname, ".")
	results := make([]string, 0)

	for i := 0; i < len(tmp); i++ {
		test := strings.Join(tmp[i:], ".")
		domain, _ = publicsuffix.EffectiveTLDPlusOne(test)
		if domain != "" {
			results = append(results, domain)
		}
	}

	sort.Strings(results)
	if len(results) > 0 {
		domain = results[len(results)-1]
	}

	if domain == "" {
		err = ErrDomainNotExtracted
	}
	return
}
```

**Comment by jub0bs** [comment]
@leandrosansilva If you're satisfied with the answers you've got, could you please self-close this issue? Thanks.
