### ISSUE TITLE
internal/fuzz: int32 corpus values that aren't valid UTF-8 runes marshal as 0xFFFD

### ISSUE THREAD

**Issue by bcmills** [golang/go#51528]
I found #51526 by examining the edge-cases in the `internal/fuzz` encoding tests, and it also affects `internal/fuzz`.

int32 values such as `0xd800` (half a surrogate pair) and `unicode.MaxRune + 1` marshaled to the Unicode replacement character (`0xFFFD`) instead of the original character, losing both reproducibility and input-diversity in the fuzz corpus.

**Comment by bcmills** [comment]
Reopening for 1.18 backport.

**Comment by dmitshur** [comment]
Closed by merging commit bf366ef711ca735b3dd52ba63d2106a27c55aef7 (CL 390816) to release-branch.go1.18.
