### ISSUE TITLE
cmd/compile: wrong panic message for method call on nil of generic interface type

### ISSUE THREAD

**Issue by mdempsky** [golang/go#51521]
The program below currently prints `FAIL interface conversion: interface is nil, not main.I` and exits with failure when built with cmd/compile. I think this is incorrect, as there's no type assertion in the user code.

I believe the correct behavior is the method call `p.M()` should raise a "nil pointer dereference" panic, and so the test program should quietly exit with success.

This isn't a spec compliance issue per se, as the Go spec doesn't mandate any particular panic messages. But it is inconsistent with the documentation for package runtime.

```
package main

import (
	"fmt"
	"strings"
)

type I interface{ M() }

func F[P I](p P) { p.M() }

func main() {
	defer func() {
		err := recover()
		if err, ok := err.(error); ok && strings.Contains(err.Error(), "nil pointer dereference") {
			return
		}
		fmt.Println("FAIL", err)
	}()

	F[I](nil)
}
```

Marking for Go 1.19, because I doubt this affects any real users.

/cc @griesemer @ianlancetaylor @randall77

**Comment by mdempsky** [comment]
Another failure case, but this one currently fails to link due to `main.main: relocation target go.interface { M() go.shape.int_0 }.M not defined`:

```
package main

import (
	"fmt"
	"strings"
)

func F[T any]() {
	interface{ M() T }.M(nil)
}

func main() {
	defer func() {
		err := recover()
		if err, ok := err.(error); ok && strings.Contains(err.Error(), "nil pointer dereference") {
			return
		}
		fmt.Println("FAIL", err)
	}()

	F[int]()
}
```

**Comment by ianlancetaylor** [comment]
Rolling forward to 1.20 as it should be fixed by unified IR.  Please comment if you disagree.  Thanks.

**Comment by mdempsky** [comment]
This is fixed with GOEXPERIMENT=unified, which will be enabled by default in 1.20.
