### ISSUE TITLE
x/build/cmd/gerritbot: Force pushing with just editing the commit message won't trigger the gopherbot

### ISSUE THREAD

**Issue by Lukas-J** [golang/go#51537]
In https://github.com/golang/website/pull/98 I changed the commit message multiple times but the gopherbot didn't get triggered.

I used `git commit --amend` and then `git push --force` on the "patch-1" branch.

**Comment by ianlancetaylor** [comment]
What you need to instead is to edit the title and first comment of the GitHub pull request.  See https://go.dev/wiki/CommitMessage.
