### ISSUE TITLE
runtime: Windows "high-resolution" timer seems to do the opposite

### ISSUE THREAD

**Issue by CannibalVox** [golang/go#51530]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Stephen\AppData\Local\go-build
set GOENV=C:\Users\Stephen\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\msys64\mingw64\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:/msys64/mingw64
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\Stephen\projects\testslice\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\msys64\tmp\go-build805753431=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Ran this code on any release post-1.16, on windows:

<pre>
package main

import (
	"fmt"
	"time"
)

func main() {
	t := time.NewTicker(5 * time.Millisecond)
	begin := make(chan bool)
	var count int
	go func() {
		<-begin
		for range t.C {
			count++
		}
	}()
	begin <- true
	time.Sleep(time.Second)
	t.Stop()
	fmt.Println(count)
}
</pre>

### What did you expect to see?

~200ish ticks over the life of the program

### What did you see instead?

64 ticks

Additional:

This works correctly on 1.15.15. Probably seems to be introduced in 1.16 It is important to understand the following:

The new code seems to substitute high-resolution timers in place of setting the timer resolution to 1ms at the start of a program. However, **my system timer is already set to 1ms** and despite that, go sleeps/ticks/etc. are operating at 15.whatever millisecond resolution on my windows system.

**Comment by ALTree** [comment]
Seems like it could be a dup of #44343?

**Comment by ALTree** [comment]
Yeah, I think it is. Closing here, please comment if you think it's not a dup of https://github.com/golang/go/issues/44343.

**Comment by CannibalVox** [comment]
I think you're right- thank you very much!
