### ISSUE TITLE
x/website: update to latest spec just before release

### ISSUE THREAD

**Issue by griesemer** [golang/go#51532]
To get the most up-to-date spec into the 1.18 release, rather than cherry-picking possibly multiple CLs until the release, we should create a single CL (immediately before the release) in the release branch which contains a 1:1 copy of the latest spec at tip.

cc: @dmitshur

**Comment by griesemer** [comment]
@go101 I will take care of this for the next version. Thanks.

**Comment by go101** [comment]
Some inconsistencies between spec and gc:

* a call to the `close` function doesn't require its argument has a core type, but spec says it requires.
* for a neither a map nor a type parameter container, index expression is not required to have a core type, but the spec says it is required (I have mentioned this several times and still think it is not right described in the spec)
