### ISSUE TITLE
types2: math.MaxFloat32 is unexpectedly inferred as float64

### ISSUE THREAD

**Issue by changkun** [golang/go#51556]
### What did you do?

https://go.dev/play/p/uYfc9rcmP1j?v=gotip

```go
package main

import "math"

type V[T ~float32 | ~float64] struct {
	X T
}

func NewV[T ~float32 | ~float64](x T) V[T] {
	return V[T]{x}
}

func main() {
	x := NewV(math.MaxFloat32)
	switch (interface{})(x).(type) {
	case V[float32]:
		println("OK")
	case V[float64]:
		panic("???")
	}
}
```

### What did you expect to see?

OK

### What did you see instead?

???

**Comment by krhubert** [comment]
MaxFloat32 is a float64 const 😕 So everything works as expected.

**Comment by changkun** [comment]
> MaxFloat32 is a float64 const

Aren't they untyped consts?

```
const (
	MaxFloat32             = 0x1p127 * (1 + (1 - 0x1p-23)) // 3.40282346638528859811704183484516925440e+38
	SmallestNonzeroFloat32 = 0x1p-126 * 0x1p-23            // 1.401298464324817070923729583289916131280e-45

	MaxFloat64             = 0x1p1023 * (1 + (1 - 0x1p-52)) // 1.79769313486231570814527423731704356798070e+308
	SmallestNonzeroFloat64 = 0x1p-1022 * 0x1p-52            // 4.9406564584124654417656879286822137236505980e-324
)
```

**Comment by ALTree** [comment]
`fmt.Printf("%T\n", math.MaxFloat32)` also prints `float64`, it's not related to type-inference. Spec:

> An untyped constant has a default type which is the type to which the constant is implicitly converted in contexts where a typed value is required. [...] **The default type of an untyped constant is** bool, rune, int, **float64**, complex128 or string respectively, depending on whether it is a boolean, rune, integer, floating-point, complex, or string constant.

**Comment by changkun** [comment]
That's indeed a bit non-intuitive. If spec has defined default type, I don't much more we can do here...
