### ISSUE TITLE
access:   https://github.com/orgs/golang/teams/go-assignees ; https://github.com/orgs/golang/teams/go-approvers

### ISSUE THREAD

**Issue by EbenezerJesuraj** [golang/go#51557]
See https://go.dev/wiki/GithubAccess

GitHub Username: EbenezerJesuraj 
GitHub ID: #33781574
email id: ebenezerjesuraj@gmail.com

Requesting for access:

Editors Access (https://github.com/orgs/golang/teams/go-approvers) for working on issues in golang organization and to contribute to the Open-Source Community..

**Comment by mvdan** [comment]
What do you need the access for? You've only commented on one GitHub issue, so I don't think you need access to do issue gardening at this point. You also similarly do not need special Gerrit access to contribute code or documentation changes.

**Comment by EbenezerJesuraj** [comment]
Oh Okay.. Sure, I assumed you need access to contribute code/documentation, apologies..

**Comment by EbenezerJesuraj** [comment]
I am closing this issue for the time being.
