### ISSUE TITLE
fmt: `%#v` does not produce coherently formatted code according to `go fmt`

### ISSUE THREAD

**Issue by cyrus-and** [golang/go#51571]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/cyrus/Library/Caches/go-build"
GOENV="/Users/cyrus/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/cyrus/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/cyrus/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.6/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_c/v38f5wmj2gzbkwkvx8_0czmw0000gn/T/go-build2402225313=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```go
package main

import "fmt"

func main() {
	fmt.Printf("%#v", map[int]int{1: 2, 3: 4})
}
```

https://go.dev/play/p/YOTYntHzfWq

### What did you expect to see?

```
map[int]int{1: 2, 3: 4}
```

### What did you see instead?

```
map[int]int{1:2, 3:4}
```

---

### Comment

It's no biggie, really. I just thought that since that verb bothers placing the space after the comma, it should in my opinion, go the extra mile and produce a nicely formatted Go code.

For clarity, let me explain why this is a *issue*. I'm using `go generate` to produce some code that I don't want to version control (yeah I know, it won't be `go get`-table), and when I run `go fmt` I don't want those file names to end up in the output.

Alternatively, I could just put all the generated files in a separated package and esclude it from `go fmt`, but stil...

**Comment by seankhliao** [comment]
`%#v` won't generate valid Go code in all cases, only a code-like representation. In any case https://pkg.go.dev/go/format#Source is what you want.

Closing as I don't think anything needs to be done here.
