### ISSUE TITLE
fmt: `fmt.Println` change the value of the pointer

### ISSUE THREAD

**Issue by YogiLiu** [golang/go#51570]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.7 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xxx\AppData\Local\go-build
set GOENV=C:\Users\xxx\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\xxx\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\xxx\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.7
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\xxx\AppData\Local\Temp\go-build165214742=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

```go
package main

import "fmt"

func main() {
	a := new([0]int)
	b := new([0]int)
	fmt.Println(a == b) // Unexpected output: true
	fmt.Println(a, b)   // Output: &[] &[]

	c := new([0]int)
	d := new([0]int)
	fmt.Println(c == d) // Output: false

	e := new([1]int)
	f := new([1]int)
	fmt.Println(e == f) // Output: false
	fmt.Println(e, f)   // Output: &[0] &[0]

	g := new([1]int)
	h := new([1]int)
	fmt.Println(g == h) // Output: false
}
```

### What did you expect to see?
Output value of line 8: `false`

### What did you see instead?
Output value of line 8: `true`

**Comment by ALTree** [comment]
This is allowed by the spec:

> A struct or array type has size zero if it contains no fields (or elements, respectively) that have a size greater than zero. *Two distinct zero-size variables may have the same address in memory.*

Stress on *may*. It can happen, but it's not mandatory, and using these zero-sized values in certain ways can cause it to not happen anymore.
