### ISSUE TITLE
cmd/go: Can not shift constant integer while convert result to floating-number

### ISSUE THREAD

**Issue by mkideal** [golang/go#51585]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.17.8
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Compile following code:

```go
package main

import (
	"fmt"
)

func main() {
	var x = 2
	fmt.Println(float64(1 << x))
}
```

Playground: https://go.dev/play/p/GbHxUjOVJD6

### What did you expect to see?

Output: `4`

### What did you see instead?

Compile error: `invalid operation: 1 << x (shift of type float64)`

If i change the code to `float64(int(1) << x)`, it's ok. But this error doesn't look like an error.

**Comment by blackgreen100** [comment]
I believe this is consistent with the language specifications.

> If the left operand of a non-constant shift expression is an untyped constant, it is first implicitly converted to the type it would assume if the shift expression were replaced by its left operand alone.

- The shift expression `1 << x` is non-constant because it involves the variable `x`
- the left operand is the untyped constant `1`
- implicitly converted to the type it would assume if there were no shift -> `float64(1)`
- shift on `float64` is an invalid operation

**Comment by mkideal** [comment]
It's a reasonable explanation, but it looks a little weird.

**Comment by robpike** [comment]
Working as described by the spec. Not exactly as intended, as the shift rules were incredibly difficult to sort out - I was joking about them to Robert Griesemer just yesterday - but how they work. The behavior of this expression is a casualty of making things seem right in more idiomatic contexts.
