### ISSUE TITLE
x/website: playground's textbox has poor contrast

### ISSUE THREAD

**Issue by dominikh** [golang/go#51584]
The playground has rather poor contrast now: 
![image](https://user-images.githubusercontent.com/39825/157604683-46ad7087-7028-4ed4-863a-a77fd9965e35.png)

Looking at the CSS, the text's color is `var(--color-text-subtle)`. I think it goes without saying that the text shouldn't be subtle.

**Comment by seebs** [comment]
it apparently does not in fact go without saying, but strongly agreed. it's good to have reasonably high contrast. too-high can be uncomfortable, but this is starting to be too faint to read easily.

**Comment by Deleplace** [comment]
I strongly agree that the input code and the output didn't have a strong enough contrast.

Thank you Egon.

## Before CL 391394

<img width="356" alt="image" src="https://user-images.githubusercontent.com/13508141/157681741-d8a2519c-1a86-432b-ab90-bf68e8eaf11f.png">

## After CL 391394

<img width="335" alt="image" src="https://user-images.githubusercontent.com/13508141/157682084-df907237-6356-4153-9aef-3f128d841226.png">

**Comment by jamalc** [comment]
Thanks for reporting this, we fixed this in [CL 391535](https://go-review.googlesource.com/c/website/+/391535) as part of a set of bug fixes for the dark theme.
