### ISSUE TITLE
affected/package: test

### ISSUE THREAD

**Issue by Aklscc** [golang/go#51583]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.14.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

I find it first time.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Aklscc\AppData\Local\go-build
set GOENV=C:\Users\Aklscc\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\GoWork
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Users\Aklscc\.g\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\Aklscc\.g\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\YANFA-~1\
</pre></details>

### What did you do?

I want to test the result in `for` loop. Such as:
```go
var i = 0

type Good struct {
}

func (receiver *Good) Next() bool {
	if i != 5 {
		i++
		return receiver.Next()
	}
	return false
}
func TestFor(t *testing.T) {
	g := Good{}
	for g.Next() {
		if i == 3 {
			t.Error(i)
		}
	}
}
```

### What did you expect to see?

I want to see a `FAIL` result, but it aways get a `PASS`.
```
=== RUN   TestFor
--- PASS: TestFor (0.00s)
PASS
ok      FTPDemo 0.286s
```
Maybe the `For` statement do nothing when I run `go test`.

### What did you see instead?

How should I do?

**Comment by davecheney** [comment]
g.Next returns false.

**Comment by Aklscc** [comment]
> g.Next returns false on the first invocation.

Thanks. I make some terrible code in the actual project. You are right.
