### ISSUE TITLE
runtime: panic in sweeper in go 1.17.7

### ISSUE THREAD

**Issue by dongpipi** [golang/go#51597]
https://github.com/golang/go/blob/4ea866a9969f4ff2ffd975116a17bbe01ce00469/src/runtime/mgcsweep.go#L436

![image](https://user-images.githubusercontent.com/43511390/157707839-9f682125-a818-4f7c-8d9d-b608c16125e8.png)

**Comment by dongpipi** [comment]
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x42a40b]

goroutine 18 [running]:
runtime.throw({0x5eeafe6, 0xc00016c658})
	/data10/home/liuyidong.eddy/go/src/runtime/panic.go:1198 +0x71 fp=0xc00016c618 sp=0xc00016c5e8 pc=0x43cbb1
runtime.sigpanic()
	/data10/home/liuyidong.eddy/go/src/runtime/signal_unix.go:719 +0x396 fp=0xc00016c668 sp=0xc00016c618 pc=0x4530b6
runtime.(*sweepLocked).sweep(0xab623e0, 0x0)
	/data10/home/liuyidong.eddy/go/src/runtime/mgcsweep.go:436 +0x12b fp=0xc00016c740 sp=0xc00016c668 pc=0x42a40b
runtime.sweepone()
	/data10/home/liuyidong.eddy/go/src/runtime/mgcsweep.go:290 +0x109 fp=0xc00016c7b0 sp=0xc00016c740 pc=0x429d09
runtime.bgsweep()
	/data10/home/liuyidong.eddy/go/src/runtime/mgcsweep.go:166 +0x105 fp=0xc00016c7e0 sp=0xc00016c7b0 pc=0x429bc5
runtime.goexit()
	/data10/home/liuyidong.eddy/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00016c7e8 sp=0xc00016c7e0 pc=0x470601
created by runtime.gcenable
	/data10/home/liuyidong.eddy/go/src/runtime/mgc.go:181 +0x55

**Comment by randall77** [comment]
You're getting a segv, not a divide by zero error, so this failure isn't caused by the size being zero.
Probably one of those pointers is null. We'll need more info to help you here. Please fill out the issue template, and ideally provide us with a program that we could run ourselves that demonstrates the problem.
