### ISSUE TITLE
net/http - HTTP Response body not filling POST data values

### ISSUE THREAD

**Issue by D3vil0per** [golang/go#51606]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.8 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ uname -a
Linux pwnbox-base 5.14.0-2parrot1-amd64 #1 SMP Debian 5.14.6-2parrot1 (2021-09-25) x86_64 GNU/Linux
</pre></details>

### What did you do?

Noted that for some websites (for example Wordpress Login pages), when net/http is used for performing a HTTP POST request (not tested for GET requests), some variables inside the HTTP response body don't store POST data provided by the request For example, by running the following GO script for performing a HTTP POST request to a public Wordpress-based website:

```golang
package main

import (
    "bytes"
    "encoding/json"
    "fmt"
    "io/ioutil"
    "net/http"
)

func main() {
    reqBody, err := json.Marshal(map[string]string{
        "log": "admin",
        "pwd": "tedsdad",
        "wp-submit": "Log In",
        "redirect_to": "http://www.rangelagos.com/wp-admin/",
        "testcookie": "1",
    })
    if err != nil {
        print(err)
    }
    resp, err := http.Post("http://www.rangelagos.com/wp-login.php",
        "application/json", bytes.NewBuffer(reqBody))
    if err != nil {
        print(err)
    }
    defer resp.Body.Close()
    body, err := ioutil.ReadAll(resp.Body)
    if err != nil {
        print(err)
    }
    fmt.Println(string(body))
}
```
inside the HTTP response body, on the login form section, we get this html code:
```html
         <p>
                <label>Username<br />
                <input type="text" name="log" id="user_login" class="input" value="" size="20" tabindex="10" /></label>
        </p>
```
Focus on the `value` variable that is empty.

If we execute the same HTTP Post request by the following cURL command:
```
curl 'http://www.rangelagos.com/wp-login.php' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Content-Type: application/x-www-form-urlencoded' -H 'Origin: http://www.rangelagos.com' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: http://www.rangelagos.com/wp-login.php' -H 'Cookie: xLanguage_=en; wordpress_test_cookie=WP+Cookie+check' -H 'Upgrade-Insecure-Requests: 1' -H 'Sec-GPC: 1' --data-raw 'log=admin&pwd=dsads&wp-submit=Log+In&redirect_to=http%3A%2F%2Fwww.rangelagos.com%2Fwp-admin%2F&testcookie=1'
```
inside the HTTP response body, on the login form section, we get this html code with the right value of `value` variable:
```html
        <p>
                <label>Username<br />
                <input type="text" name="log" id="user_login" class="input" value="admin" size="20" tabindex="10" /></label>
        </p>
```
in this last case, we have the `value` variable correctly filled by the data `admin`.
It means that the `value` variable, in some specific cases, cannot be written with the right value but stay empty.

Tried also by other go scripts of other mates or found online but with the same result.

**Comment by cuiweixie** [comment]
i think it is something about server side response.

**Comment by anticrisis** [comment]
> If we execute the same HTTP Post request by the following cURL command

Just a note that the curl request is not identical to your go code's request. It's different in several ways, including using `application/x-www-form-urlencoded` rather than `application/json`.

**Comment by seankhliao** [comment]
This is a server side issue, not one with Go.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
