### ISSUE TITLE
go/types, types2: alias types are restricted to basic interfaces, should allow arbitrary interfaces

### ISSUE THREAD

**Issue by go101** [golang/go#51616]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18rc1 linux/amd64
</pre>

### What did you do?

```Go
type C[T any] interface{~int; M() T}
type C1 = C[bool] // error
type C2 = comparable // error
type C3 = interface {~[]byte | ~string} // error
```

I didn't find this is documented in tip spec.

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by griesemer** [comment]
This is just a bug. I don't see a reason why there should be a restriction here. It's a trivial change but too late for 1.18.
