### ISSUE TITLE
cmd/link: intermittently produces segfaulting executables with binutils 2.27-44

### ISSUE THREAD

**Issue by godfried** [golang/go#51611]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.8 linux/amd64
</pre>

We build go from source ourselves using this Makefile:
```Makefile
GO_BUILD_VERSION=1.17.8

clonego:
	git clone https://go.googlesource.com/go

checkoutversion:
	(cd go && git checkout go${GO_BUILD_VERSION} )

buildgo:
	(cd go/src && ./make.bash )

targz:
	tar -czf go-${GO_BUILD_VERSION}-linux-amd64.tar.gz ./go

buildall: clonego checkoutversion buildgo targz

clean:
	rm -rf ./go
	rm *tar.gz

.PHONY: clonego checkoutversion buildgo targz clean

.DEFAULT_GOAL:=buildall
```

The reason for building go ourselves is that from go 1.16 our version of binutils no longer worked with the pre-compiled go release. We encountered the problem described here https://github.com/golang/go/issues/43996
Our version of binutils:
```
$ yum list  binutils
Installed Packages
binutils.x86_64                                                                                     2.27-44.base.fc20                                                                                      @/binutils-2.27-44.base.fc20.x86_64
```

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/pieter/dev/myrepo/bin"
GOCACHE="/home/pieter/.cache/go-build"
GOENV="/home/pieter/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/pieter/go/pkg/mod"
GONOPROXY="*.mydomain.co.za"
GONOSUMDB="*.mydomain.co.za"
GOOS="linux"
GOPATH="/home/pieter/go"
GOPRIVATE="*.mydomain.co.za"
GOPROXY="http://artifactory1.mydomain.co.za:8081/artifactory/go-modules"
GOROOT="/home/pieter/dev/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/home/pieter/dev/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.8"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/pieter/dev/myrepo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build99898503=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.17.8 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.17.8
uname -sr: Linux 3.10.0-693.fc20.x86_64
/lib64/libc.so.6: GNU C Library (GNU libc) stable release version 2.18, by Roland McGrath et al.
gdb --version: GNU gdb (GDB) Fedora 7.7.1-21.fc20
</pre></details>

### What did you do?

I built 1000 'empty' go executables with: `@go build -o ./bin -compiler=gc ./vt/tools/dummies/...`
The only code in these programs is:
```go
package main

func main(){}
``` 
All of the programs are in the ./vt/tools/dummies folder and are named dummy0 ... dummy999.
After compiling them successfully 148 times, on the 149th compilation on of the binaries cannot be executed and segfaults:
```
[pieter@devbox2 next]$ bin/dummy191
Segmentation fault
```
The `go build` command itself exits cleanly.

### What did you expect to see?

`go build` to produce valid executables, and if it doesn't, it should fail.

### What did you see instead?

`go build` exits cleanly but produced an executable that segfaults.

I compared the segfaulting binary to a valid binary in Ghidra. The segfaulting one is on the left (dummy191.sf)

<img width="1627" alt="Screenshot 2022-03-10 at 13 16 05" src="https://user-images.githubusercontent.com/1863111/157808730-e4a7d55e-163f-444d-a2ef-e3f6225289e1.png">
<img width="579" alt="Screenshot 2022-03-10 at 13 12 21" src="https://user-images.githubusercontent.com/1863111/157808633-bb6655cc-b75e-4e69-8acf-6945c240a8e8.png">
<img width="1627" alt="Screenshot 2022-03-10 at 13 14 42" src="https://user-images.githubusercontent.com/1863111/157808701-0cd31563-252e-4a74-bf69-1a4bec1f16a3.png">
<img width="771" alt="Screenshot 2022-03-10 at 13 12 43" src="https://user-images.githubusercontent.com/1863111/157808644-6e7cacbf-3ce9-4ce1-8f2b-e0ea45f07887.png">
<img width="1627" alt="Screenshot 2022-03-10 at 13 13 49" src="https://user-images.githubusercontent.com/1863111/157808692-bbfab3c3-4252-4f0e-8dff-16aaa487aea6.png">
<img width="771" alt="Screenshot 2022-03-10 at 13 12 55" src="https://user-images.githubusercontent.com/1863111/157808662-3d9b0f31-f4e6-44d9-9982-cc3226940024.png">
<img width="1627" alt="Screenshot 2022-03-10 at 13 13 39" src="https://user-images.githubusercontent.com/1863111/157808675-8e13a0f4-9412-454f-b1ff-23b8692c68f1.png">
<img width="771" alt="Screenshot 2022-03-10 at 13 13 08" src="https://user-images.githubusercontent.com/1863111/157808666-a9cad9e4-cb67-4aa0-816a-3ebefc6146c1.png">

**Comment by ALTree** [comment]
Is this specifically a 1.17.8 thing? Or you can reproduce this with other releases?

**Comment by tianhendi** [comment]
您的邮件我已经收到

**Comment by godfried** [comment]
I was also able to reproduce it on 1.17.
I haven't looked further back than that.

**Comment by godfried** [comment]
Updated case info with reason for building go from source.
We suspect that the version of binutils (2.27-44) on our OS could be the reason for segfaults.

**Comment by bcmills** [comment]
Do the test programs that you are building have C dependencies?

What happens if you build with `CGO_ENABLED=0` and/or `-ldflags=all=-linkmode=internal`?

**Comment by godfried** [comment]
They do not have C dependencies.
I'll test with those flags added.

**Comment by godfried** [comment]
@bcmills I still encountered the seg fault with both `CGO_ENABLED=0` and `-ldflags=all=-linkmode=internal`
I only tested with both set.
The code I am testing is completely dependency free, it is just:
```
package main

func main(){}
```
So I would not think that CGO_ENABLED or linkmode=internal should affect it.

**Comment by godfried** [comment]
Is there anything else you need from me?

**Comment by bcmills** [comment]
Are there any differences in the actual commands used to build the executables?

(What differences, if any, do you see if you run `go clean -cache`, then build the individual binaries with the `-x` flag passed to `go build` to get it to dump the commands as it executes them?)
