### ISSUE TITLE
cmd/asm: add TRN1 and TRN2 arm64 instruction support

### ISSUE THREAD

**Issue by josharian** [golang/go#51628]
It'd be lovely if the assembler supported the TRN1 and TRN2 arm64 instructions. (Would they be called VTRN1 and VTRN2 instead? Not sure.)

Thanks!

https://developer.arm.com/documentation/ddi0602/2020-12/SIMD-FP-Instructions/TRN1--Transpose-vectors--primary--

cc @zhangfannie

**Comment by josharian** [comment]
In case it helps, here are some tested assembled instructions:

```
	// TRN1	V2.D2, V3.D2, V20.D2
	WORD $0x4EC32854

	// TRN2	V2.D2, V3.D2, V21.D2
	WORD $0x4EC36855   

	// TRN1	V4.D2, V5.D2, V22.D2
	WORD $0x4EC52896   

	// TRN2	V4.D2, V5.D2, V23.D2
	WORD $0x4EC56897

	// TRN1	V6.D2, V7.D2, V20.D2
	WORD $0x4EC728D8   

	// TRN2	V6.D2, V7.D2, V23.D2
	WORD $0x4EC768D9   

	// TRN1	V8.D2, V9.D2, V20.D2
	WORD $0x4EC9291A   

	// TRN2	V6.D2, V7.D2, V23.D2
	WORD $0x4EC768DB   
```

**Comment by mengzhuo** [comment]
cc @zhangfannie @erifan ARM maintainer

**Comment by zhangfannie** [comment]
@josharian Add their assembly support right away. Thank you.

**Comment by zhangfannie** [comment]
@josharian The gun assembly syntax is: `TRN2 <Vd>.<T>, <Vn>.<T>, <Vm>.<T>`， its golang assembly syntax is: ` VTRN2 <Vm>.<T>, <Vn>.<T>, <Vd>.<T>`. Thank you.
