### ISSUE TITLE
proposal: affected/package:  About the problem of filepath.Walk ignoring Symlink.

### ISSUE THREAD

**Issue by Maicss-chen** [golang/go#51627]
I saw a reply to solve this problem:

> Walk does not follow symbolic links, by design. Otherwise it is difficult to avoid loops. I will update the docs.

But if all links are used as a file, even if this link points to a folder, it will not further resolve it, is it a problem?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
