### ISSUE TITLE
image:  Smaller png image

### ISSUE THREAD

**Issue by achims1** [golang/go#51641]
If I have an 8-bit image, but after drawing the image, a lot of useless data is added, which will increase the bandwidth during transmission. Can we add some functions to the existing golang for users to choose? Your own image size and format, such as the website tinypng, compress png as needed, while ensuring that the image size remains unchanged

**Comment by seankhliao** [comment]
Lossy compression is a complicated thing with many different possible algorithms.
This sort of thing seems better suited to live in a third party package.
See also https://go.dev/doc/faq#x_in_std
