### ISSUE TITLE
gollvm: some built-in libgo tests failed

### ISSUE THREAD

**Issue by AblakatovMikhail** [golang/go#51648]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version unknown linux/amd64
llvm-project/llvm/tools/gollvm$ git log --oneline | head -n 1
9bc0905 gollvm: fix libgo cmake rules to include new C source
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Ran all built-in libgo tests:
<pre>
build-release$ for target in $(ninja -t targets | grep check_libgo_ | sed -e 's/\(.*\):.*/\1/') ; do ninja $target 2>&1 | grep "FAILED:" ; done
</pre>

### What did you expect to see?

Nothing, all tests pass

### What did you see instead?

<pre>
FAILED: tools/gollvm/libgo/CMakeFiles/check_libgo_internal_fmtsort
FAILED: tools/gollvm/libgo/CMakeFiles/check_libgo_math_cmplx
FAILED: tools/gollvm/libgo/CMakeFiles/check_libgo_mime
FAILED: tools/gollvm/libgo/CMakeFiles/check_libgo_os_signal
FAILED: tools/gollvm/libgo/CMakeFiles/check_libgo_runtime
FAILED: tools/gollvm/libgo/CMakeFiles/check_libgo_runtime_debug
FAILED: tools/gollvm/libgo/CMakeFiles/check_libgo_runtime_pprof
</pre>

+ `internal/fmtsort` fails due to the same issue described at #51238. I've got a fix for this one already. I will submit a cl soon.
+ `os/signal` requires cmake files to be updated, I'll submit a cl fixing this.
+ `runtime` fails due to the same issue described at #51098.
+ `runtime/debug` requires the same check added for runtime in gofrontend with https://go-review.googlesource.com/c/gofrontend/+/140517/
+ I also may have a fix for `runtime/pprof` but I'm not sure yet.

----------------------

_Mikhail Ablakatov_

**Comment by heschi** [comment]
cc @thanm

**Comment by thanm** [comment]
Thanks for that investigation.

**Comment by ianlancetaylor** [comment]
I think that everything here is fixed now.  Thanks for reporting the problems.
