### ISSUE TITLE
cmd/go: allow "go run" to run command in current directory

### ISSUE THREAD

**Issue by titanous** [golang/go#5164]
<pre>1. go run *.go

What is the expected output?

[program runs]

What do you see instead?

go run: cannot run *_test.go files (foo_test.go)

Which compiler are you using (5g, 6g, 8g, gccgo)?

6g

Which operating system are you using?

OS X 10.8.2

Which version are you using?  (run 'go version')

go version devel +946f0a049860 Sat Mar 30 11:18:56 2013 -0700 darwin/amd64

Please provide any additional information below.

This worked with the 1.0.3 go tool.</pre>

**Comment by myml** [comment]
@rsc This is simple and Forgotten

**Comment by rsc** [comment]
Forgotten, maybe, but not simple.

**Comment by rsc** [comment]
I reread the discussion on https://golang.org/cl/50970043/, and I still don't see a way to integrate this. Obviously the command-line 'go run' could run the program in the current directory, but then 'go run arg' and 'go run arg.go' behave completely differently. I think this is probably OK to leave as is. For single-file programs people know about 'go run foo.go', and for larger programs 'go build && ./myprog' seems to be working fine.
