### ISSUE TITLE
affected/package: docker gcc:11，GoString() return messy code from char*

### ISSUE THREAD

**Issue by xyd113** [golang/go#51640]
mac 10.15.5

### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.16.5 gccgo (GCC) 11.2.0
</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/libexec/gcc/x86_64-linux-gnu/11.2.0"
GOVCS=""
GOVERSION="go1.16.5 gccgo (GCC) 11.2.0"
GCCGO="/usr/local/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/data/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build819749012=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
</pre></details>

### What did you do?
<pre>
1. docker pull gcc:11
2. docker run -it --name gcc11  gcc:11
3. create a new project
4. edit hi.cpp,hi.h and main.go file
5. run command "g++ hi.cpp -fPIC -shared -o libhi.so"
6. run command "go run mdsAgent.go"
</pre>

### What did you expect to see?
<pre>
start---------
return: hello world
pStr: hello world
pStr len: 11
cha= hello world
returnStr= hello world  type= string
</pre>

### What did you see instead?
<pre>
start---------
return: hello world
pStr: hello world
pStr len: 11
cha=  ?f
returnStr=   type= string
</pre>

#### hi.h
<pre>
#ifndef WRAPPER_H_
#define WRAPPER_H_
#ifdef __cplusplus
extern "C"
{
#endif
char* hi();
#ifdef __cplusplus
}
#endif
#endif // WRAPPER_H_
</pre>

#### hi.cpp
<pre>
#include <iostream>
#include <stdio.h>
#include <string.h>
#include "hi.h"
#ifdef __cplusplus
extern "C"{
#endif

char* hi(){
    std::string tmp = "hello world";
    std::cout << "return: "<< tmp << std::endl;
    const char* pBuf = tmp.c_str();
    char* pStr = const_cast<char*>(pBuf);
    std::cout << "pStr: "<< pStr << std::endl;
    std::cout << "pStr len: "<< strlen(pStr) << std::endl;
    return pStr;
}

#ifdef __cplusplus
}
#endif
</pre>

#### main.go
<pre>
package main

/*
#cgo CFLAGS : -I./
#cgo LDFLAGS: -L./ -lhi
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "hi.h"
*/
import "C"
import (
	"fmt"
	"reflect"
	"strings"
	"unsafe"
)

func main(){
	fmt.Println("start---------")
	hhh := C.hi()
	cha := C.GoString((*C.char)(unsafe.Pointer(hhh)))
	fmt.Println("cha=", cha)
	returnStr := C.GoString(hhh)
	fmt.Println("returnStr=", returnStr, "type=", reflect.TypeOf(returnStr).Name())
}
</pre>

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
