### ISSUE TITLE
go/parser: incorrectly allows parenthesized embedded types

### ISSUE THREAD

**Issue by findleyr** [golang/go#51655]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.8 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, and at tip.

### What did you do?

https://go.dev/play/p/xOwV_SZwGCU

Parsed this
```
package p

type I1 interface{}

type I2 struct{ (I1) }
```

### What did you expect to see?

An error

### What did you see instead?

No error

I believe in the process of adding support for generics, we accidentally dropped this error. This has been present since at least Go 1.17, so (IMO) should be OK to fix in a patch release of Go 1.18, backported to Go 1.17.

CC @griesemer

**Comment by ianlancetaylor** [comment]
What is the current status here?  This issue is currently in the 1.19 milestone.  Should it move to 1.20?  To Backlog?  Thanks.

**Comment by griesemer** [comment]
I think we should fix this but it doesn't need to be fixed for 1.19. Moving to 1.20.

**Comment by griesemer** [comment]
Once this is fixed, address the respective TODO in go/types/testdata/examples/types.go.
