### ISSUE TITLE
text/template: break/continue require no whitespace around them

### ISSUE THREAD

**Issue by JRaspass** [golang/go#51670]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18rc1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18rc1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build149032034=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

`break`/`continue` in templates require no whitespace around them unlike other keywords.
https://go.dev/play/p/pbmCi6ystSG?v=gotip

### What did you expect to see?

`{{ range . }}{{ continue }}{{ end }}` compiles fine.

### What did you see instead?

```
panic: template: :1: unexpected " " in in {{continue}}
```

**Comment by heschi** [comment]
cc @robpike @rsc

**Comment by martinrode** [comment]
Shouldn’t this ticket be open until its merged?

**Comment by seankhliao** [comment]
It is merged into tip

**Comment by martinrode** [comment]
How about a backport to the next point release?

**Comment by ianlancetaylor** [comment]
@gopherbot Please open a backport to 1.18.

These new text/template features are new in the 1.18 release, but they have a oddity in that don't permit whitespace.  It's probably worth fixing that in 1.18 so that they people don't have to slightly contort their new code until 1.19 comes out.
