### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by lorddoskias** [golang/go#51677]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/.gostuff/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/.gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.17"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.17/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.7"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/gobpf-dns/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3939396067=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Trying to attach a bpf program to a socket:

   `    err = syscall.SetsockoptInt(fd, syscall.SOL_SOCKET, syscall.SO_ATTACH_BPF, bpfFd)`

The problem is that syscall.SO_ATTACH_BPF is not defined. In the linux kernel it's defined to `50` so in zerrors_linux_amd64.go
 it should be defined as 0x32

### What did you expect to see?
Proper compilation of aforementioned line

### What did you see instead?
./tcpsnoop.go:68:55: undefined: syscall.SO_ATTACH_BPF

**Comment by seankhliao** [comment]
Ss the `syscall` package documentation says, it's deprecated. Use `golang.org/x/sys/unix`.
