### ISSUE TITLE
spec: combining mark & non spacing mark as invalid go identifiers make it pointless to use Devanagari identifiers

### ISSUE THREAD

**Issue by gopherbot** [golang/go#5167]
by **suraj@barkale.com**:

<pre>1. What is a short input program that triggers the error?
Using a typical word in Devanagari used as identifier will cause compiler error. (e.g.
नमस्ते := &quot;Hello&quot;)
Sample program at: <a href="http://play.golang.org/p/uxBtQZUjxU">http://play.golang.org/p/uxBtQZUjxU</a>

Aside: Indentation is removed by play.golang.org editor after adding Devanagari
character anywhere on a line.

2. What is the full compiler output?
prog.go:6: invalid identifier character 0x94d
prog.go:6: invalid identifier character 0x947
prog.go:7: invalid identifier character 0x94d
prog.go:7: invalid identifier character 0x947

3. What version of the compiler are you using?  (Run it with the -V flag.)
1.03

4. Please provide any additional information below.
Go specification only recognize Lu, Ll, Lt, Lm, Lo and '_' as valid letter for
identifiers. However, unlike other languages Devanagari script uses signs (e.g. U+0947)
to represent vowels. So using Devanagari for identifiers is pointless in go (imagine
writing English without using 'aeiou').

My suggestion is to amend Go specification by allowing combining-mark &amp;
non-spacing-mark characters in identifiers.

This will be similar to Java identifier rules givent at
<a href="http://docs.oracle.com/javase/1.4.2/docs/api/java/lang/Character.html#isJavaIdentifierPart(char)">http://docs.oracle.com/javase/1.4.2/docs/api/java/lang/Character.html#isJavaIdentifierPart(char)</a>
A character may be part of a Java identifier if any of the following are true:
  * it is a letter
  * it is a currency symbol (such as '$')
  * it is a connecting punctuation character (such as '_')
  * it is a digit
  * it is a numeric letter (such as a Roman numeral character)
  * it is a combining mark
  * it is a non-spacing mark
  * isIdentifierIgnorable returns true for the character

I am willing to work for a patch if this proposal is accepted.</pre>

**Comment by robpike** [comment]
Probably not good to change the definition of an identifier in Go 1. Too much code knows the rules.

**Comment by rsc** [comment]
Now tracked as #20706.
