### ISSUE TITLE
x/crypto/ssh: Unmarshal for SSH_AGENTC_EXTENSION

### ISSUE THREAD

**Issue by lpcalisi** [golang/go#51689]
OpenSSH 8.9 will include the ability to control how and where keys in ssh-agent may be used, both locally and when forwarded (subject to some [limitations](https://www.openssh.com/agent-restrict.html#limitations)).

This new feature implements a new agent extension  an it doesn't compatible with Golang SSH Agent library. This kind of messages could not be parsed by [Unmarshall](https://github.com/golang/crypto/blob/3147a52a75dda54ac3a611ef8978640d85188a2a/ssh/messages.go#L382) method.

The message format is:
```
byte            SSH_AGENTC_EXTENSION (0x1b)
string          session-bind@openssh.com
string          hostkey
string          session identifier
string          signature
bool            is_forwarding

```

The error is `ssh: parse error in message type 27`, when 27 is the `SSH_AGENTC_EXTENSION` message type (referenced in [SSH Agent Protocol](https://datatracker.ietf.org/doc/html/draft-miller-ssh-agent-00#section-5.1))

**Comment by seankhliao** [comment]
cc @FiloSottile

**Comment by lpcalisi** [comment]
hi team! any news about it? thanks you!

**Comment by jrcasso** [comment]
just a call-out: I'm encountering this error when binding the ssh-agent in Docker builds as described [here](https://docs.docker.com/develop/develop-images/build_enhancements/#using-ssh-to-access-private-data-in-builds).

**Comment by bdols** [comment]
not sure if I'm in the right project, but I'm also seeing this exact error of `ssh: parse error in message type 27` when using the ssh-agent binding with docker-ce and rootless containerd w/nerdctl. But, I'm only seeing this with a ubuntu 22 base image whereas with a ubuntu 20 base image I do not see this error.

**Comment by gcsfred2** [comment]
I'm encountering this error when binding the ssh-agent in Docker builds. No solution.

**Comment by AkihiroSuda** [comment]
@jrcasso @bdols @gcsfred2 
Probably https://github.com/moby/buildkit/issues is the right repo to report your issues.
