### ISSUE TITLE
x/website: generics and fuzzing tutorials have an outdated paragraph for Go 1.18 Beta

### ISSUE THREAD

**Issue by gazerro** [golang/go#51688]
The tutorial on generics has an outdated paragraph "Installing and using the beta"

https://go.dev/doc/tutorial/generics#installing_beta

Now that go 1.18 has been released, it should be removed.

**Comment by ianlancetaylor** [comment]
CC @eliben

**Comment by gazerro** [comment]
The fuzzing tutorial also contains the paragraph "Installing and using the beta"

https://go.dev/doc/tutorial/fuzz

**Comment by dmitshur** [comment]
Thanks @eliben. I'll point out that [CL 382057](https://go.dev/cl/382057) makes a change related to this (and it can be be closed after this issue is resolved).
