### ISSUE TITLE
x/exp/vulncheck: make package compatible with go1.17 or older

### ISSUE THREAD

**Issue by hyangah** [golang/go#51687]
The package depends on new features available after go1.18 (e.g `debug/buildinfo`) 
that means it is not buildable with older versions of go. 
In theory, consuming applications (e.g. gopls) can choose to use build tags to
disable features depending on this package completely when the are built with go1.17 or older.

But I believe not all parts of the `vulncheck` package need to depend on go1.18. (e.g. `Source`)
So I wonder if it's possible to leave some those accessible when using go1.17 or older. 

@zpavlinovic

**Comment by zpavlinovic** [comment]
I believe this is mainly related to `Binary` API. cc'ing @rolandshoemaker

**Comment by hyangah** [comment]
Requiring go1.18+ for `Binary` is reasonable IMO.

We can consider to offer two versions of `Binary`. One with build tag go1.18. Another with an empty Binary() that returns an error.

If decided to support building with older versions of Go, builder/trybot setup with go1.17 may be desirable to prevent regression due to accidental use of go1.18 features (generics, for example).

**Comment by hyangah** [comment]
x/exp/vulncheck is moved to x/vuln/vulncheck
and I believe this was fixed in https://go-review.googlesource.com/c/vuln/+/395095 during the move.

cc @julieqiu
