### ISSUE TITLE
cmd/compile: maps with type params doesn't recognize map-clearing range idiom

### ISSUE THREAD

**Issue by wgrr** [golang/go#51699]
In go1.18, the compiler output for this program (https://go.dev/play/p/GVufoDzAG5-) on tested targets {openbsd,linux}/{amd64,arm64,386} the generic version does not use runtime.mapclear, instead it iterates over the map deleting each element, I expected both functions generate a very similar code, instead `clear` generates (roughly):

```
mov    rbx,rax
lea    rax,type.map[string]bool
xchg   ax,ax
call   runtime.mapclear
```

clear2 (copied from [exp/maps.Clear](https://cs.opensource.google/go/x/exp/+/43aec2f8:maps/maps.go;l=57)) generates (roughly):

```
call   runtime.mapiterinit
jmp    loop
start: mov rcx,QWORD PTR [rdx]
mov    rdi,QWORD PTR [rdx+0x8]
lea    rax,type.go.shape.map[string]bool_0
mov    rbx,QWORD PTR [rsp+0x20]
call   runtime.mapdelete_faststr
lea    rax,[rsp+0x28]
call   runtime.mapiternext
loop:  mov rdx,QWORD PTR [rsp+0x28]
test   rdx,rdx
jne    start
```

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/w/bin"
GOCACHE="/home/w/.cache/go-build"
GOENV="/home/w/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/w/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/w/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="/usr/bin/gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build896486634=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by cuonglm** [comment]
FYI, `clear` and `clear2` are compiled the same with unified IR.
