### ISSUE TITLE
golang.org/x/exp/slices: inconsistent naming

### ISSUE THREAD

**Issue by frioux** [golang/go#51698]
Most of the functions use `E` for the names of the elements within slices, but a few use `Elem`.  The former strikes me as more Go, but I don't care.  Just struck me as inconsistent.

**Comment by heschi** [comment]
cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
The only function I see that uses `Elem` is `offByOne` in slices_test.go.  I'll change that one, but did I miss any?

**Comment by ianlancetaylor** [comment]
Oh, I see, the sort functions.  Got it.

**Comment by ianlancetaylor** [comment]
The fix here was completed by https://go.dev/cl/399315.
