### ISSUE TITLE
runtime: some tests fails on Windows with CGO_ENABLED=0

### ISSUE THREAD

**Issue by henryas** [golang/go#51695]
### What version of Go are you using (`go version`)?

go version go1.18 windows/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?
OS: Windows 11

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\henry\AppData\Local\go-build
set GOENV=C:\Users\henry\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\henry\go\pkg\mod
set GONOPROXY=github.com/henryas
set GONOSUMDB=github.com/henryas
set GOOS=windows
set GOPATH=C:\Users\henry\go
set GOPRIVATE=github.com/henryas
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\henry\Programs\Go\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\henry\Programs\Go\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fmessage-length=0 -fdebug-prefix-map=C:\Users\henry\AppData\Local\Temp\go-build230480319=/tmp/go-build -gno-record-gcc-switches

### What did you do?
I tried to build go1.18 from source, by running all.bat. CGO_ENABLED is set to 0 (false). Antivirus is turned off. 

### What did you expect to see?
It should build and pass the tests.

### What did you see instead?
It builds fine but fails the tests. Here are the failed tests:

--- FAIL: TestVectoredHandlerDontCrashOnLibrary (0.24s)
    signal_windows_test.go:37: failed to build go library: exit status 1
        go: no Go source files
--- FAIL: TestLibraryCtrlHandler (0.06s)
    signal_windows_test.go:161: failed to build go library: exit status 1
        go: no Go source files
FAIL
FAIL    runtime 83.530s

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport issues

These tests will fail if run with `CGO_ENABLED=0`.  The fix is trivial and test-only.  We may as well backport it.
