### ISSUE TITLE
x/website: mistaken run command on workspaces tutorial page

### ISSUE THREAD

**Issue by ClaytonXia** [golang/go#51693]
### What is the URL of the page with the issue?
 https://go.dev/doc/tutorial/workspaces
 
 
### What is your user agent?
 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36

 
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/39251907/158504034-559e3c6e-116f-4912-80a4-fab5eb058412.png)

 
 
 
### What did you do?
  Run command: `go run example/hello`

 
### What did you expect to see?
 HELLO
 
 
### What did you see instead?
package example/hello is not in GOROOT

### Fix
I guess the command should be `go run example.com/hello`. Isn't it?

**Comment by fzipp** [comment]
Yes, it should be `go run example.com/hello`.

There's another bug in the tutorial:

> 3. Add the new function.
> [...]
> Add a new folder to the workspace/example/stringutil directory containing the following contents:

This should be "Add a new _file_ ..."

**Comment by seankhliao** [comment]
Fixed in [CL 393360](https://go.dev/cl/393360)
