### ISSUE TITLE
cmd/compile: remove support for "broken" IR and types

### ISSUE THREAD

**Issue by mdempsky** [golang/go#51691]
Now that -G=0 mode is gone, `types.Type.SetBroke` and `ir.Node.SetDiag` should never be called with `true` as an argument. I suggest:

1. We change these methods to base.Fatalf if called with true, and change Broke/Diag to always return false. (We may need to land some fixes first; e.g., seems like test/typeparam/mdempsky/11.go is failing with unified IR currently.)
2. Do a global replacement of `t.Broke() -> false` and `n.Diag() -> false`. (Along with followup simplifications like `!false -> true` and `false && x -> false`.)
3. Remove any `if false { ... }` code paths.
4. Replace any `t.SetBroke(true)` or `n.SetDiag(true)` code paths with base.Fatalf instead.

**Comment by cuonglm** [comment]
@mdempsky do you think we can close this issue now?

**Comment by cuonglm** [comment]
> @mdempsky do you think we can close this issue now?

kindly ping :smiley:

**Comment by mdempsky** [comment]
@cuonglm Thanks, yeah, seems good to close now.
