### ISSUE TITLE
x/website: go.dev/VERSION isn't 1.18

### ISSUE THREAD

**Issue by zijer** [golang/go#51701]
### What is the URL of the page with the issue?
https://go.dev/VERSION
 
### What is your user agent?
`Mozilla/5.0 (Android 11; Mobile; rv:95.0) Gecko/95.0 Firefox/95.0`
 
### Screenshot
![s](https://user-images.githubusercontent.com/15065054/158530317-65f698d4-78f3-4715-9243-54af8bd937d7.jpg)

### What did you do?
Open the page

### What did you expect to see?
`go1.18`
 
### What did you see instead?
`go1.17.8`

**Comment by Jacalz** [comment]
Duplicate of https://github.com/golang/go/issues/51686?

**Comment by seankhliao** [comment]
VERSION is is the website version not the release version, use /dl/?mode=json

**Comment by rsc** [comment]
This is fixed now, FWIW. Sorry it took longer than expected.
