### ISSUE TITLE
go:linkname must refer to declared function or variable

### ISSUE THREAD

**Issue by littlejiancc** [golang/go#51706]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wxj/Library/Caches/go-build"
GOENV="/Users/wxj/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/wxj/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/wxj/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/Users/wxj/sdk/go1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/wxj/sdk/go1.18/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/wxj/go/src/demo/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/85/j24r836d5ygfhjgsn4j5zr0m0000gn/T/go-build178809849=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

<pre>
$ tree
.
├── 1.s
├── go.mod
├── go.sum
├── inner
│   └── inner.go
└── main.go
</pre>

<pre>
$ cat inner.go
package inner

type name struct {
	name string
}

func hello() {
	n := name{
		name: "jack",
	}
	println("hello", n.name)
}

</pre>

<pre>
$ cat main.go
package main

import (
	`fmt`

	_ "demo/inner"
	_ "unsafe"
)

//go:linkname hello demo/inner.hello
func hello()

//go:linkname runtimeG runtime.g
type runtimeG struct {
}

func main() {
	hello()
	r := runtimeG{}
	fmt.Println(r)
}

</pre>

<pre>
go run main.go
</pre>

### What did you expect to see?

<pre>
hello jack
{}
</pre>

### What did you see instead?

<pre>
# command-line-arguments
./main.go:13:3: //go:linkname must refer to declared function or variable
</pre>

I think runtimeG is declared in main.go, And it works well in version 1.17.8 and 1.16.4

**Maybe I'm using it incorrectly, hope it clears my mind, thanks very much!**

**Comment by seankhliao** [comment]
reaching into the runtime isn't supported

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by JasonRadcliffe** [comment]
I had the same issue running go 1.18  today - the solution on this thread solved it for me. I don't think the variable name runtime has anything to do with it. This does seem like it might be a bug of some kind given I fresh installed go on a fresh image and had source code version mismatching going on.

https://stackoverflow.com/questions/71507321/go-1-18-build-error-on-mac-unix-syscall-darwin-1-13-go253-golinkname-mus

**Comment by philandrewatfamilyzone** [comment]
The solution is here https://stackoverflow.com/questions/71507321/go-1-18-build-error-on-mac-unix-syscall-darwin-1-13-go253-golinkname-mus

**Comment by PhilAndrew** [comment]
The solution is here https://stackoverflow.com/questions/71507321/go-1-18-build-error-on-mac-unix-syscall-darwin-1-13-go253-golinkname-mus

**Comment by shearn89** [comment]
To summarise the fix in case of linkrot, try:

`go get -u golang.org/x/sys`

to update `sys` and hopefully fix the issue.

**Comment by chengjoey** [comment]
Even after upgrading the golang.org/x/sys package, the problem is still not solved, why close this issue
@seankhliao

**Comment by mvdan** [comment]
We appear to be conflating two issues here.

(1) People who try to use `//go:linkname` themselves to directly access unexported APIs in the standard library. If you do that, it may work, but it is not supported nor guaranteed to keep working in future Go versions. It is not covered by the Go backwards compatibility guarantee.

This is what the original author mentioned, and Sean is right to have closed the issue - you are free to use the linker directive, but you're on your own when it breaks. In fact, I even struggle to find any official documentation that explains how to use `//go:linkname` - I'm fairly sure it wasn't really intended for use outside of the standard library and some tightly-coupled packages like `x/sys/unix`.

(2) People who get build errors with a particular versions of Go and `x/sys`. Like previous commenters have mentioned, this is most likely because either of your Go or `x/sys` versions are too old.

As you can see on https://build.golang.org/, the "x" modules like `x/sys` are continuously tested on Go master as well as the two latest stable Go versions (1.18.x and 1.19.x at the time of writing). If your `x/sys` version is recent, your Go version should be recent too.

Similarly, if your Go version is recent, you should make sure your `x/sys` version is recent as well. I personally do this by running `go get -t -u ./...` on my projects every now and then, such as when doing a new major release or when upgrading Go to a new major version.

**Comment by littlejiancc** [comment]
hi @mvdan 

Whether it's a `//go:linkname` struct to runtime package or a custom package, this works in go1.17, but not in go1.18 and go1.19, I want to know the reason but I didn't find the relevant documentation.

**Comment by mvdan** [comment]
If you mean your original example, again, that was always undocumented behavior and never guaranteed to work.

**Comment by chengjoey** [comment]
> If you mean your original example, again, that was always undocumented behavior and never guaranteed to work.

project:
```
├── 1.s
├── inner
│   └── inner.go
└── main.go
```

inner.go:
```
package inner

import (
	"fmt"
)

var a int = 100

type student struct {
	age int
}

func hello() {
	fmt.Println("hello")
}
```

main.go:
```
package main

import (
	"fmt"
	_ "unsafe"

	_ "demo/inner"
)

//go:linkname A demo/inner.a
var A int

//go:linkname Student demo/inner.student
type Student struct{}

//go:linkname Hello demo/inner.hello
func Hello()

func main() {
	Hello()
	fmt.Println(A)
	fmt.Println(Student{})
}
```

run `go run main.go`

result in 1.17 version:
```
hello
100
{}
```

result in 1.18 and later:
```
# command-line-arguments
./main.go:13:3: //go:linkname must refer to declared function or variable
```

I didn't import the x/sys package or the runtime package, I think should get the same result in different versions

**Comment by chengjoey** [comment]
> > If you mean your original example, again, that was always undocumented behavior and never guaranteed to work.
> 
> project:
> 
> ```
> ├── 1.s
> ├── inner
> │   └── inner.go
> └── main.go
> ```
> 
> inner.go:
> 
> ```
> package inner
> 
> import (
> 	"fmt"
> )
> 
> var a int = 100
> 
> type student struct {
> 	age int
> }
> 
> func hello() {
> 	fmt.Println("hello")
> }
> ```
> 
> main.go:
> 
> ```
> package main
> 
> import (
> 	"fmt"
> 	_ "unsafe"
> 
> 	_ "demo/inner"
> )
> 
> //go:linkname A demo/inner.a
> var A int
> 
> //go:linkname Student demo/inner.student
> type Student struct{}
> 
> //go:linkname Hello demo/inner.hello
> func Hello()
> 
> func main() {
> 	Hello()
> 	fmt.Println(A)
> 	fmt.Println(Student{})
> }
> ```
> 
> run `go run main.go`
> 
> result in 1.17 version:
> 
> ```
> hello
> 100
> {}
> ```
> 
> result in 1.18 and later:
> 
> ```
> # command-line-arguments
> ./main.go:13:3: //go:linkname must refer to declared function or variable
> ```
> 
> I didn't import the x/sys package or the runtime package, I think should get the same result in different versions

I found that in version 1.18 and later, functions and variables still work, the linkname for struct is not supported, but I didn't find instructions in the official documentation

**Comment by mvdan** [comment]
See https://go-review.googlesource.com/c/go/+/333109/. Once again, none of this is documented nor supported as far as I can tell.

**Comment by chengjoey** [comment]
> See https://go-review.googlesource.com/c/go/+/333109/. Once again, `go:linkname` is not documented nor supported as far as I can tell.

ok, since there is not documented nor supported then I have nothing to say

**Comment by chengjoey** [comment]
https://github.com/golang/go/blob/15da892a4950a4caac987ee72c632436329f62d5/src/cmd/compile/internal/noder/noder.go#L291-L310

https://github.com/golang/go/blob/15da892a4950a4caac987ee72c632436329f62d5/test/linkname2.go#L16-L30

i think may be the error `go:linkname must refer to declared function or variable` is re-enabled in 1.18 and only support `Func`, `Var`.

but in 1.17, basically all types are supported

**Comment by mvdan** [comment]
@chengjoey see https://github.com/golang/go/issues/55889#issuecomment-1259507026.

**Comment by mdempsky** [comment]
You can't use `//go:linkname` on a `type` declaration.

**Comment by fzhange** [comment]
> To summarise the fix in case of linkrot, try:
> 
> `go get -u golang.org/x/sys`
> 
> to update `sys` and hopefully fix the issue.

it's powerful

**Comment by JohnAllen** [comment]
Sounds like this was definitely a bug report since upgrading the package fixed it.

**Comment by chengjoey** [comment]
> You can't use `//go:linkname` on a `type` declaration.

I agree with your point of view, just looks a little confused that 1.18 and later versions will report an error,but 1.17  don't report an error
