### ISSUE TITLE
runtime: wrong type assertion result when using generic types

### ISSUE THREAD

**Issue by disksing** [golang/go#51700]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

doesn't matter. It can reproduce on the go playground.
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

https://go.dev/play/p/A9VuqCpJ7r5

### What did you expect to see?

As `S` does not have method name `M1` or `M2`, it should not panic.

### What did you see instead?

Panic and output `iface1`. I also noticed that if I rename `IFace2` to `AFace2`, the result is panic and output `iface2`.

**Comment by heschi** [comment]
Tentatively marking release blocker.

**Comment by mdempsky** [comment]
`S` and `m3` aren't even needed. Just `f(0)` repros the issue too.

**Comment by mdempsky** [comment]
It seems to happen for any named type. E.g., instantiating `B` as `[]int` doesn't cause problems, but instantiating it as `SliceInt` does.

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport to 1.18.

This appears to be incorrect code generation, so we should backport the fix when we have one.
