### ISSUE TITLE
os: TestOpenFileLimit fails on openbsd

### ISSUE THREAD

**Issue by rsc** [golang/go#51713]
For #46279, we added os.TestOpenFileLimit, which checks that it can open 1200 files.
This test fails on openbsd, even after doing setrlimit(RLIMIT_NOFILE, lim) with lim.Cur raised to lim.Max.

Perhaps the builder runs with a hard limit < 1200. 
Whatever the reason, OpenBSD is not a first-class port,
so the test will be skipped with a pointer to this issue,
and we will leave the issue for any OpenBSD maintainers
that want to take a look.

**Comment by mengzhuo** [comment]
FYI: It still failed on openbsd/mips64

https://build.golang.org/log/8d2a91e75462acd10f0dc525f53e25004631e444
