### ISSUE TITLE
x/website: typo in workspaces tutorial

### ISSUE THREAD

**Issue by algonzalez** [golang/go#51716]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.18 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOAMD64=v1
</pre></details>

### What did you do?

Reading tutorial on workspaces; line https://github.com/golang/website/blob/76352824d2e26b9d9407709835151c27642d45b3/_content/doc/tutorial/workspaces.md?plain=1#L193 does not appear to be accurate.

### What did you expect to see?

Text for creating a file such as: 

    Create a `toupper.go` file in the `workspace/example/stringutil` directory with the following contents:

### What did you see instead?

Text for adding a folder:

     Add a new folder to the `workspace/example/stringutil` directory containing the following contents:

**Comment by seankhliao** [comment]
This was fixed in [CL 393360](https://go.dev/cl/393360)
