### ISSUE TITLE
generics: Generic function not accepting nil as an argument 

### ISSUE THREAD

**Issue by alwindoss** [golang/go#51729]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/opt/gohome/bin"
GOCACHE="/home/alwin/.cache/go-build"
GOENV="/home/alwin/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/opt/gohome/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/opt/gohome"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/alwin/Sandbox/dev/tap/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build174870830=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I ran this program. [Code in Play](https://go.dev/play/p/lIYnWwoRiq1)

### What did you expect to see?
For the code to run without errors

### What did you see instead?
`
./main.go:10:20: cannot infer T (/home/alwin/Sandbox/dev/tap/main.go:14:13)
`

**Comment by alwindoss** [comment]
Problem is the line that is passing `nil` as a parameter to the generic function `pass`

**Comment by seankhliao** [comment]
working as intended, `nil` has no type.

**Comment by alwindoss** [comment]
But if there is a function with the argument of type `interface{}` i can always pass a nil.
`any` in this case is `interface{}` so why can't i pass nil?

**Comment by alwindoss** [comment]
I think this issue should not be closed without a discussion. The point i have raised about the ability to pass `nil` to an argument of type `interface{}` should be considered.
By not doing it perhaps we are introducing ambiguity in the way interface{} type works before generics vs after generics

**Comment by randall77** [comment]
You can always provide the type parameter explicitly, e.g. `pass[*int](nil)`. The problem is if you just write `pass(nil)`, what should `T` be? `*int`? `[]byte`? It is underspecified.
If you want to pass a nil as an interface, use `pass[any](nil)`.

**Comment by alwindoss** [comment]
Thanks @randall77 for showing how to make it work and @ianlancetaylor for explaining the difference.

I modified the program and ran and it passes. It passes because now it has a type that satisfies the constraint

[Modified Code ](https://go.dev/play/p/89pq9aKovg1)

**Comment by alwindoss** [comment]
Just a thought @ianlancetaylor 
This is something very subtle. Would it make sense to have an example in this tutorial https://go.dev/doc/tutorial/generics

**Comment by ianlancetaylor** [comment]
I thought about it but I think it would be too complicated to put into the tutorial.  I don't think it's something that people new to Go are likely to run into.
