### ISSUE TITLE
cmd/cgo: pointer to incomplete C type is mangled when passed through interface type and generic type assert

### ISSUE THREAD

**Issue by kbolino** [golang/go#51733]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

This is the latest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/kbolino/Library/Caches/go-build"
GOENV="/Users/kbolino/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/kbolino/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/kbolino/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/kbolino/Documents/GoModules/cgo-generics/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/59/hjg6jvkd71s8djph6yqbdn0h0000gn/T/go-build78106070=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```go
package main

// #include <stdlib.h>
// struct incomplete_type;
import "C"

import (
	"fmt"
	"unsafe"
)

func main() {
	someMem := C.malloc(16)
	defer C.free(someMem)
	ptrIn := (*C.struct_incomplete_type)(someMem)
	fmt.Printf("ptrIn  = %016x\n", uintptr(unsafe.Pointer(ptrIn)))
	var iface interface{} = ptrIn
	ptrOut := recoverPointer[C.struct_incomplete_type](iface)
	fmt.Printf("ptrOut = %016x\n", uintptr(unsafe.Pointer(ptrOut)))	
}

func recoverPointer[T any](val interface{}) *T {
	return val.(*T)
}
```

This is a minimal example; the original use case involved `cgo.Handle` and passing pointers across the Go/C boundary.

### What did you expect to see?

```
ptrIn  = <some_val>
ptrOut = <some_val>
```

A compilation error or panic would also have sufficed. 

### What did you see instead?

```
ptrIn  = <some_val>
ptrOut = <some_other_val>
```

for example,

```
ptrIn  = 0000600000dbc010
ptrOut = 0000014000059f30
```

**Comment by ianlancetaylor** [comment]
Here is a standalone example that doesn't use cgo.  This appears to be a bug in the way that generic code handles type assertions, or notinheap pointers, or something.  CC @randall77 .

```Go
package main

import (
	"log"
	"unsafe"
)

//go:notinheap
type S struct{}

func main() {
	p := (*S)(unsafe.Pointer(uintptr(0x8000)))
	var v any = p
	p2 := v.(*S)
	if p != p2 {
		log.Fatalf("%p != %p", unsafe.Pointer(p), unsafe.Pointer(p2))
	}
	p2 = typeAssert[*S](v)
	if p != p2 {
		log.Fatalf("%p != %p from typeAssert", unsafe.Pointer(p), unsafe.Pointer(p2))
	}
}

func typeAssert[T any](v any) T {
	return v.(T)
}
```

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport to 1.18

This appears to be invalid code generation, so we should backport  a fix when we have one.
