### ISSUE TITLE
cmd/compile: cleanup code paths that aren't needed now that -p is required

### ISSUE THREAD

**Issue by mdempsky** [golang/go#51734]
Since CL 391014 (a987aaf5f7a5f64215ff75ac93a2c1b39967a8c9), cmd/compile now requires the -p flag. There's a lot of code to handle code paths that aren't needed any more.

At least a few cleanups I can think of:

1. Initialize types.LocalPkg with base.Ctxt.Pkgpath instead of `""`.
2. Change types.TypeHash to use t.LinkString instead of fmtTypeIDHash.
3. Get rid of "package height" and just sort method sets on identifier and package path. (We can just write package height as 0 in the iexport data format; public importers ignore it anyway.)
4. Change cmd/link (or cmd/internal/obj?) to Fatalf if it sees `"".` in any linker symbols.

Perhaps other opportunities.

The iexport file format uses `""` for the current package too, which probably needs to be retained for compatibility with legacy importers.

/cc @randall77 @dr2chase @cuonglm

**Comment by randall77** [comment]
I think point 2 will be the right fix to revert/improve what CL 389474 did.

**Comment by cuonglm** [comment]
> I think point 2 will be the right fix to revert/improve what CL 389474 did.

I'm going to send a CL for this.

**Comment by cuonglm** [comment]
> > I think point 2 will be the right fix to revert/improve what CL 389474 did.
> 
> I'm going to send a CL for this.

Hmm, simply changing `types.TypeHash` to use `t.LinkString()` make `go run run.go` panic with:

```
panic: interface conversion: reflect.Type is *reflect.rtype, not *reflect.rtype (types from different scopes)

goroutine 1 [running]:
reflect.PointerTo(...)
	/home/cuonglm/sources/go/src/reflect/type.go:1442
encoding/json.newTypeEncoder({0x566c30?, 0x516440?}, 0x1?)
	/home/cuonglm/sources/go/src/encoding/json/encode.go:422 +0x3e5
encoding/json.typeEncoder({0x566c30?, 0x516440})
	/home/cuonglm/sources/go/src/encoding/json/encode.go:404 +0x16b
encoding/json.typeFields({0x566c30, 0x528440})
	/home/cuonglm/sources/go/src/encoding/json/encode.go:1385 +0x668
encoding/json.cachedTypeFields({0x566c30?, 0x528440})
	/home/cuonglm/sources/go/src/encoding/json/encode.go:1417 +0xab
encoding/json.(*decodeState).object(0xc0000022a8, {0x5123c0?, 0xc00002e5c0?, 0xc000061980?})
	/home/cuonglm/sources/go/src/encoding/json/decode.go:654 +0x21e
encoding/json.(*decodeState).value(0xc0000022a8, {0x5123c0?, 0xc00002e5c0?, 0xc0000619d0?})
	/home/cuonglm/sources/go/src/encoding/json/decode.go:373 +0x45
encoding/json.(*decodeState).unmarshal(0xc0000022a8, {0x5123c0?, 0xc00002e5c0?})
	/home/cuonglm/sources/go/src/encoding/json/decode.go:180 +0x1de
encoding/json.(*Decoder).Decode(0xc000002280, {0x5123c0, 0xc00002e5c0})
	/home/cuonglm/sources/go/src/encoding/json/stream.go:73 +0x177
main.glob..func1()
	/home/cuonglm/sources/go/test/run.go:68 +0x1a5
main.init()
	/home/cuonglm/sources/go/test/run.go:75 +0x3f9
exit status 2
```

It seems to need more work than I expect, so feel free to go ahead if you have one, otherwise, I will take another look when I'm back with my laptop.

cc @mdempsky @randall77

**Comment by mdempsky** [comment]
@cuonglm At least step 1 needs to happen before we can do step 2. :)

**Comment by mdempsky** [comment]
Okay, all of the outstanding cleanup CLs for this have landed. In particular, LinkString is now used for type hashing.

The only remaining cleanup is removing package height. That can wait until Go 1.20.

**Comment by mdempsky** [comment]
I think this is more or less done now. This issue has served its purpose.
