### ISSUE TITLE
cmd/compile: internal compiler error: panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by blaubaer** [golang/go#51765]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\demo\AppData\Local\go-build
set GOENV=C:\Users\demo\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\demo\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\demo\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\development\github.com\blaubaer\demo
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\demo\AppData\Local\Temp\go-build2763200917=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

I was using the following code (https://go.dev/play/p/KwmzJ6V1JwN)

```golang
package main

import (
	"errors"
	"log"
)

var (
	ErrEof = errors.New("end of iterator reached")
)

type empty[T any] struct{}

func (this *empty[T]) Next() (empty T, _ error) {
	return empty, ErrEof
}

func doSomethingWithIterator[T any](what interface{ Next() (T, error) }) {
	v, err := what.Next()
	if err != nil {
		log.Fatalln(err)
		return
	}
	log.Println(v)
}

func main() {
	i := &empty[string]{}
	doSomethingWithIterator[string](i)
}

```

### What did you expect to see?

The code compiles and run.

### What did you see instead?
```
# github.com/blaubaer/demo
.\demo.go:29:33: internal compiler error: panic: runtime error: index out of range [0] with length 0

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

**Comment by ALTree** [comment]
Thanks for reporting this. `tip` is also affected.

cc @randall77 @danscales

**Comment by randall77** [comment]
This appears to be due to confusion between `empty`, the generic type, and `empty`, the local variable of the `Next` function. The code thinks it is trying to get the type parameters of the former, but it is in fact trying to get the type parameters of the latter, which fails.
Not sure why yet.

**Comment by cuonglm** [comment]
> This appears to be due to confusion between `empty`, the generic type, and `empty`, the local variable of the `Next` function. The code thinks it is trying to get the type parameters of the former, but it is in fact trying to get the type parameters of the latter, which fails. Not sure why yet.

The problem is that `noder` will store the symbol of the generic base type. But the symbol declaration maybe changed when re-declaring variable with the same name. So the code:

```
origRParams := deref(orig).OrigSym().Def.(*ir.Name).Type().RParams()
```

will return wrong type parameters.

**Comment by mdempsky** [comment]
@gopherbot backport to Go 1.18; this is a compiler bug that could theoretically lead to silent miscompilation of valid user code

**Comment by mdempsky** [comment]
@gopherbot please backport to Go 1.18; this is a compiler bug that could theoretically lead to silent miscompilation of valid user code
