### ISSUE TITLE
runtime: doAllThreadsSyscall has an unaligned atomic load on 32-bit architectures

### ISSUE THREAD

**Issue by mknyszek** [golang/go#51776]
The 64-bit loads [here](https://cs.opensource.google/go/go/+/master:src/runtime/os_linux.go;l=814;drc=9d34fc5108d91bfcce3c465069dbb2c563af4229) and [here](https://cs.opensource.google/go/go/+/master:src/runtime/os_linux.go;l=825;drc=9d34fc5108d91bfcce3c465069dbb2c563af4229) are unaligned on 32-bit architectures (see #599).

I would just fix this, but it's unclear to me what the right fix is. This is right at the top of the `m` struct, so adding padding is tricky because there could be other 64-bit loads below in the struct that will become unaligned. (I think maybe `fastrand`? I didn't check, maybe there isn't any.) Simultaneously, making these loads not atomic seems slightly dangerous on weak memory architectures.

This might need a backport to Go 1.18? I think these lines are new in Go 1.18.

CC @prattmic @aclements

**Comment by mknyszek** [comment]
Oh, I should also mention, these loads are the only atomic accesses of this field.

**Comment by prattmic** [comment]
`procid` is actually only 32-bits on Linux (gettid returns uint32), so as a workaround we could cast to `*uint32` and use a 32-bit atomic load.

**Comment by prattmic** [comment]
cc @golang/release re @mknyszek's note that we have no nocgo coverage outside of amd64.

**Comment by dmitshur** [comment]
Ack. If it's deemed helpful, adding a 32-bit nocgo builder using any of our virtualized VM-based host types, e.g., `linux-386-nocgo`, sounds reasonable. Please feel free to file an issue and send a CL for it. I'll prioritize the access issue to so that you'd also be able to deploy it after the CL lands. Thanks!

**Comment by aclements** [comment]
Potentially relevant is #50860, since those atomic types would let us fix these alignment issues.

> This might need a backport to Go 1.18? I think these lines are new in Go 1.18.

I believe you are right that this is new in 1.18.

**Comment by prattmic** [comment]
Fixed in https://go.dev/cl/399754.

@gopherbot Please backport to 1.18. This is a regression with no workaround.

**Comment by bradfitz** [comment]
Even without builder coverage, we could at least have some coverage that all fields in the runtime that are accessed as 64-bit atomics all have correct offsets for a handful of varied build contexts?

**Comment by cherrymui** [comment]
Does procid really need to be 64-bit? I think it is the tid (thread ID), which is 32-bit on many platforms. Where do we really need 64-bit procid?

**Comment by mknyszek** [comment]
I asked @prattmic the same thing: it's because on some OSes (any OS that uses `pthread_self`) represent the thread ID as a `uintptr`, which in the worst case is 64 bits wide.

Though, we could maybe just make it a `uintptr`?

**Comment by mknyszek** [comment]
I believe this is now fixed.
