### ISSUE TITLE
x/pkgsite: package removal request for github.com/karthikfbk/certinfo

### ISSUE THREAD

**Issue by karthikfbk** [golang/go#51771]

**Comment by karthikfbk** [comment]
What is the path of the package that you would like to have removed?
[github.com/karthikfbk/certinfo](https://github.com/karthikfbk/certinfo)

Are you the owner of this package?
yes - but forked from another repo

What is the reason that you could not retract this package instead?
repository deleted

**Comment by jamalc** [comment]
Done.
