### ISSUE TITLE
context: panic: interface conversion: interface {} is bool, not chan struct {} // 

### ISSUE THREAD

**Issue by gq0** [golang/go#51789]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.8 linux/arm
</pre>

### Does this issue reproduce with the latest release?
It was not tested with 1.18 yet.

### What operating system and processor architecture are you using (`go env`)?

Linux  4.14.114 armv7l

### What did you do?

We use the context to signal when to stop the goroutine in various places like shown below. 

```golang
for {
  select {
    case <-ctx.Done():
	    return nil
    case .... 
  }
}
```

For a couple of months we randomly get on some of our IoT gateway in the field:

```panic: interface conversion: interface {} is bool, not chan struct {}```

At the point `<-ctx.Done()`

Sometimes, it is not a boolean but rather a value attached to the context. But we couldn't identify a pattern yet.

### What did you expect to see?

No panic, instead signaling on the done channel.

### Hint

I am not 100% but could it be that the `done` `atomic.Value` is not 64bit aligned? At least then, we might have issues with our 32bit arm architecture.
https://go-review.googlesource.com/c/go/+/288193/4/src/context/context.go#342

```golang
type cancelCtx struct {
	Context

	mu       sync.Mutex            // protects following fields
-->	done     atomic.Value          // of chan struct{}, created lazily, closed by first cancel call
	children map[canceler]struct{} // set to nil by the first cancel call
	err      error                 // set to non-nil by the first cancel call
}
```

**Comment by gq0** [comment]
Yes

```
panic: interface conversion: interface {} is bool, not chan struct {}
goroutine 179 [running]:
context.(*cancelCtx).Done(0x28beab0)
/usr/local/go/src/context/context.go:361 +0x13c
github.com/grid-x/client/pkg/ioexchange.(*Mapper).Run(0x24a5f80, {0xb5a518, 0x28beab0})
/go/src/github.com/grid-x/client/pkg/ioexchange/mapper.go:80 +0xb4
main.main.func11(0x24a5f80, 0x26bce08, 0x280e070, 0x2498300)
/go/src/github.com/grid-x/client/cmd/monitoring/main.go:614 +0x30
created by main.main
```

**Comment by mvdan** [comment]
@gq0 have you tried reproducing with `-race`? Sometimes this kind of bug can be caused by memory corruption due to data races.

**Comment by gq0** [comment]
No, not yet. Because it takes some time to occur and not on all systems. But we give it a try.

Regarding the `cancelCtx` type is my assumption right on a 32bit system?

```golang
type cancelCtx struct {
	Context                              // 32 bit, is this right on armv7?
	mu       sync.Mutex            // 64 bit
-->	done     atomic.Value          // not 64 bit aligned
      ....
}
```

**Comment by ianlancetaylor** [comment]
It's OK if `atomic.Value` is not aligned on a 64-bit boundary.  The implementation of `atomic.Value` only does 32-bit atomic accesses on a 32-bit system.

What is not OK is using `atomic.LoadInt64` and friends on a misaligned `int64` on a 32-bit system.  But `atomic.Value` doesn't do that.

**Comment by gq0** [comment]
@ianlancetaylor, thanks for the clarification 👍🏻

**Comment by gq0** [comment]
It was an issue related to the passing of the context to a goroutine and wrapping of it later, similar https://github.com/buildkite/agent/pull/1606
