### ISSUE TITLE
x/tools/gopls: completion gives unneeded generic type instantiation snippet 

### ISSUE THREAD

**Issue by muirdm** [golang/go#51783]
```go
func foo[T float64 | int](a T) T {
	return a
}

func main() {
	var _ int = fo<>
}
```

Completing to "foo" at <> inserts "int(foo[T float64|int](a T))" (ignore the extra type conversion), but most likely the type argument can be inferred so gopls should offer just "foo(a int)" instead.

**Comment by muirdm** [comment]
Would this work: if there is one type param and it is the func’s return type and one of the variants is assignable to the expected type (int in this case), then presume type inference will work and omit the instantiating snippet? Is there any programmatic interface to check type param inference?

**Comment by muirdm** [comment]
@findleyr Can we hook in to type param inference to determine a priori if a generic function's type params will/might be inferable after the normal params are filled in? I know sometimes it depends on the arguments, but my feeling is that type param inference works most of the time if it can work at all for a given function.

In a similar vein, the heuristic I suggested above would not work in all cases, but I think it would be an improvement (i.e. if type inference will "probably" work, don't give the type param snippet).

**Comment by rogeryk** [comment]
The completion of generic functions is currently very poor. In most cases, type parameters are unnecessary. If you use completion now, you must also delete the type parameters after completion.

The standard library already has the "slices" and "maps" packages, so providing a completion experience for generic functions would be very helpful. If it is difficult to determine whether type parameters should be completed, it is also acceptable to remove the type parameters in complete (it is only needed in rare cases).

**Comment by findleyr** [comment]
@muirdm suggested here essentially the same as I suggested in https://github.com/golang/go/issues/64480#issuecomment-1834540272, apologies that this slipped through the cracks during generics work.

go/types does not provide precisely what we need, but as I commented on the other issue, I think a simple heuristic is probably good enough.

We should fix this soon.

**Comment by rogeryk** [comment]
E can infer from S, so the E also is free.


> (The instantiations that would not be inferred are labeled "non-trivial".)  

> So I think this heuristic will not work for such cautiously-written library functions.

I don’t think we need to consider whether the type parameter can be omitted in all scenarios, the type parameter should always be specified in rare cases.

I thought of a simple solution to alleviate this problem, we can change the tabstop range.
For example.
current complete snippet
```go
slices.Clone[${1:S ~[]E}, ${2:E any}](${3:s S})
```
change to
```go
slices.Clone${1:[${2:S ~[]E}, ${3:E any}]}(${4:s S})
```
Then we can simply ignore the type parameter if we don't need it

**Comment by rogeryk** [comment]
I gave it a try and it looks good, it shouldn't be too difficult whether you need the type parameters or not.

![iShot_2023-12-24_00 30 26](https://github.com/golang/go/assets/28089185/44e9b874-abd2-4a3a-8820-8422e1d69f9a)
