### ISSUE TITLE
x/pkgsite: package removal request for github.com/dmulholl/argo

### ISSUE THREAD

**Issue by dmulholl** [golang/go#51795]
### What is the path of the package that you would like to have removed?

https://github.com/dmulholl/argo

 
 
### Are you the owner of this package?

Yes.

 
### What is the reason that you could not retract this package instead?

When I first created this package I briefly experimented with the idea of making it `v3` of a predecessor library before ultimately deciding that it should be its own new `v0`.

While I was experimenting, the documentation for this ephemeral `v3` version got automatically uploaded to pkg.go.dev and is now blocking the actual `v0` documentation from showing up.

Obviously my own fault but if it's possible I'd appreciate it if you could wipe everything except the `v0` documentation. Thanks!

**Comment by seankhliao** [comment]
as the repo still exists, you should use retract to fix this
