### ISSUE TITLE
x/pkgsite: '' is rendered as smart doublequotes in <pre> block

### ISSUE THREAD

**Issue by kortschak** [golang/go#51807]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/google/cel-go@v0.10.1/ext#hdr-Join
 
### What is your user agent?
 

[Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)

### Screenshot
 

 
![Screenshot from 2022-03-19 20-09-39](https://user-images.githubusercontent.com/275221/159116087-aaf3e2ca-eea4-4dd7-8e08-d4defc3ec4c9.png)
 
### What did you expect to see?
 
No smart quotes in \<pre\> blocks.
 
### What did you see instead?

Smart quotes in \<pre\> blocks.

**Comment by kortschak** [comment]
On further thought, given that authors can already encode `“` and `”` through unicode in the source if they really want it, and the quote conversion makes it impossible to express things like empty strings from some other languages (and empty raw strings in Go) and quoted single quotes in SQL, I think it would be better to just remove this feature.

**Comment by mvdan** [comment]
I would also remove "quote conversion" entirely, not just in `<pre>` blocks, but perhaps I'm missing what was the point of adding that in the first place.

**Comment by seebs** [comment]
"Smart" quote conversion isn't.

**Comment by jamalc** [comment]
Let's limit this issue to removing the conversion in `<pre>` blocks to fix the bug.

**Comment by kortschak** [comment]
@jamalc I will send another PR completely removing this for discussion. Given the changes that @rsc has made in the content in https://go.dev/cl/384262 changing '' to “ and ” it would make sense not to double process, particularly given the issues I raise above.
