### ISSUE TITLE
affected/package: Debugging programs compiled with go version go1.18 darwin/amd64 is not supported. Use go sdk for darwin/arm64.

### ISSUE THREAD

**Issue by carpedil** [golang/go#51801]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
</pre></details>

### What did you expect to see?

i can debug my code step by step in goland

### What did you see instead?

Error running 'TestParser_Result in XXXXXX': Debugging programs compiled with go version go1.18 darwin/amd64 is not supported. Use go sdk for darwin/arm64.

**Comment by aarzilli** [comment]
You can't debug programs built with the darwin/amd64 version of go on arm64 (i.e. M1) you have to install the darwin/arm64 version of go.

**Comment by mengzhuo** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by hikerwu** [comment]
I failed at go1.16.7 and go1.18, succeed at go1.18.2， so you can have a try.

**Comment by axeltaglia** [comment]
Work for me with 1.18.2!
