### ISSUE TITLE
go/types: need best effort generic func instantiation

### ISSUE THREAD

**Issue by muirdm** [golang/go#51803]
On Go 1.18, I don't seem to get an Instances entry for "foo" in:

```go
func foo[T int](a T) T {
	return a
}

func main() {
	foo[int]() // <-- no Instances entry for this foo
}
```

It seems to be unhappy because the parameter is absent, however the type parameter is specified which seems like it should be enough to fill in Instances. Without the Instances entry it is difficult for gopls to offer regular parameter completions since gopls can't resolve the instantiated type signature to get the parameter type (unless there is another way?).

/cc @findleyr

**Comment by muirdm** [comment]
Oh I see - if the type checker is happy then the type of the CallExpr.Fun becomes the instantiated signature (so looking in Instances would not be necessary). I'll update the title a bit.

**Comment by findleyr** [comment]
I agree we for consistency we should record in Instances, but since this has a viable workaround I will put it in the 1.19 milestone.  CC @griesemer 

(@komuw I'm a little confused by your thumbs down: is there a reason why we shouldn't do this?)

**Comment by komuw** [comment]
@findleyr
Umh, seems I might have fat fingered that 😃.
Don't mind me.

**Comment by muirdm** [comment]
> since this has a viable workaround

AFAIK there is no way to get the instantiated *types.Signature when the type params are specified but some func args are missing. My previous comment was realizing that If the type checker resolved the signature in this case I wouldn't need to look at Info.Instances since Info.Types would already contain the instantiated Signature.

But we can filter against the type param constraint, which is better than nothing (maybe that is the workaround you are referring to?).

**Comment by findleyr** [comment]
Aha, I did in fact misinterpret your comment. I thought we were somehow recording in Types but not Instances (which doesn't make much sense).

One viable workaround is to CheckExpr the CallExpr.Fun. For example as we do with the infertypeargs analyzer:
https://cs.opensource.google/go/x/tools/+/master:internal/lsp/analysis/infertypeargs/run_go118.go;l=63;drc=2762b18206b1d81e1b5c4ae93377fa732b86bcdf

Not ideal, but possible.

**Comment by ianlancetaylor** [comment]
@findleyr What is the current status here?  This issue is currently in the 1.19 milestone.  Should it move to 1.20?  To Backlog?  Thanks.

**Comment by findleyr** [comment]
Let's move to 1.20.

**Comment by findleyr** [comment]
I will reevaluate this for 1.20, but it may slip again.
