### ISSUE TITLE
when i upgrade to V 1.18 it's give error on execution app

### ISSUE THREAD

**Issue by YallaPayInc** [golang/go#51804]
after removing old V 1.17 totally from the server and installing V 1.18 correctly and ensured also that GO was extracted in the correct path 

so.I go to try run: Go version but i got this error as below, 

I used GO version : go1.18.darwin-amd64.tar.gz

my Enviroment OS : Ubunto 21.10 LTS ,

**bash: /usr/local/go/bin/go: cannot execute binary file: Exec format error**

**Comment by mengzhuo** [comment]
You're OS is Ubuntu(linux) but using Go binary for Macos (darwin)

Unlike other projects, we do not use the issue tracker for questions such as these. It is only used for bugs and feature proposals. I will close this issue and please visit https://github.com/golang/go/wiki/Questions.
