### ISSUE TITLE
x/website: go.work details in Workspace posts

### ISSUE THREAD

**Issue by ronaldpetty** [golang/go#51817]
Hello,

I am new to Go workspaces. I am looking around the various blog posts and unclear where one should place go.work.

* https://go.dev/doc/tutorial/workspaces (Create the workspace -> where does go.work live, seems in the "hello" module and not in the parent)
* https://go.dev/doc/gopath_code#Workspaces (no mention of go.work)
* https://go.dev/ref/mod#go-work-file (no details on where to place go.work)

The `go help work` also doesn't mention where it should go.

Again, it is new, I am also new to it, so most likely I am overthinking/looking, but so far seems unclear to me.

**Comment by seankhliao** [comment]
The first one does say the directory to create it in.
The second one isn't relevant, workspaces are only for modules.
The third one specifies that go.work files define their own workspaces, there is nowhere in particular that you need to place them.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by ronaldpetty** [comment]
Thanks Sean,

Not sure I agree with the assessment, but per your last comment, I added the bug here because the page itself links to "report an issue".  Maybe that should link to what you have above.

https://go.dev/doc/tutorial/workspaces (see footer of page)

**Comment by seankhliao** [comment]
> 2. From the command prompt, create a directory for your code called workspace.
> ```
> $ mkdir workspace
> $ cd workspace
> ```
> ...
> **Initialize the workspace**
> In the `workspace` directory, run:
> ```
> $ go work init ./hello
> ```

**Comment by ronaldpetty** [comment]
Sean,
I did indeed see that. What I didn't see is why (or is that the standard place going forward). I know at some point some blogs are high-level tutorials and others are the details. Just trying to figure out what is the expected/right way, but felt like it just wasn't clear.  Will keep at it, I am probably just bouncing around too many pages. Thanks again for your time.
