### ISSUE TITLE
golang/go 1.18

### ISSUE THREAD

**Issue by graux** [golang/go#51821]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
**Compilation machine:**
Fedora 35 -  5.16.14-200.fc35.x86_64 @ Intel  i7-7700HQ
**Server: (the error happened here)** (no go installed)
Fedora 35 - 5.16.13-200.fc35.x86_64 @ Intel Core Processor (Broadwell, IBRS)

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/fgrau/.cache/go-build"
GOENV="/home/fgrau/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/fgrau/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/fgrau/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4253010991=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
It is quite difficult to reproduce. I have an API application made of 4 projects, using packages for http, gorilla mux, negroni, pgxpool, redis, etc.
The application serves a static folder with a negroni middleware, and a custom made JSON/Rest API.
The system worked well in go1.16.14. But after installing go1.18 the project is acting up.
 
### What did you expect to see?
The browser loading the web application as before, no CSS/HTML/AJAX/CORS errors.

### What did you see instead?
After building and deploying to production with go.1.18, no code changes, the system worked well for a while.
But after some hours running, maybe under higher load, the customers could not use the application because the CSS was not working.
Of three CSS files served by a negroni static middleware, **one css file served some html with the folders of the root directory of my server!**. Furthermore, the file was served as a folder, with a final / . Please review the image:

![image](https://user-images.githubusercontent.com/2606751/159142127-47061660-b922-4c1e-9217-032588dbdb1b.png)

I've recompiled and deployed three times. The problem has manifested every single time after some time.
At the moment I've reverted back to 1.16, recompiled, and deployed.  Thus far the problem has not shown up.
I cannot reproduce it in my development workstation.

**Comment by seankhliao** [comment]
Even though this may have manifested when you upgraded to go 1.18, this doesn't look like an bug in `go` or the standard library. It is more likely a problem in the framework you're using or your application code.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
