### ISSUE TITLE
cmd/compile: internal compiler error: walkExpr: switch 1 unknown op RECOVER

### ISSUE THREAD

**Issue by ahazhangxin** [golang/go#51839]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
it is already the latest version

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zhangxin/Library/Caches/go-build"
GOENV="/Users/zhangxin/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zhangxin/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zhangxin/go"
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/Cellar/go/1.18/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.18/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dg/2q4522bs3959p0x7tbn61_kw0000gn/T/go-build3463372418=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

`			go func() {
				defer func() {
					if r := recover(); r != nil {
						glog.Errorf("error=%v", r)
					}
				}()
}`

it seems fixed in https://go-review.googlesource.com/c/go/+/342350/
but in this version it appears again

### What did you expect to see?

compiles correctly

### What did you see instead?
`walk
.   RECOVER INTER-interface {} tc(1) # hello_dao.go:50:21
hello_dao.go:50:21: internal compiler error: walkExpr: switch 1 unknown op RECOVER`

**Comment by mvdan** [comment]
Could you please provide a full program to reproduce this crash?

**Comment by ahazhangxin** [comment]
`package main

import (
	"runtime"
	"sync"

	"github.com/golang/glog"
)

var prefetchOnce sync.Once

func testRecover() {
	if "darwin" != runtime.GOOS {
		prefetchOnce.Do(func() {
			go func() {
				defer func() {
					err := recover()
					if err != nil {
						//fmt.Println(err)
						glog.Errorf("error=%v", err)
					}
				}()
			}()
		})
	}
}

func main() {
	testRecover()
}
`

when i use go build test.go 
`# command-line-arguments
walk
.   RECOVER INTER-interface {} tc(1) # test.go:17:20
./test.go:17:20: internal compiler error: walkExpr: switch 1 unknown op RECOVER

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
`

**Comment by hopehook** [comment]
A simple demo:

```
package main

func main() {
	testRecover()

}

func testRecover() {
	if false {
		func() {
			defer func() {
				_ = recover()
			}()
		}()
	}
}
```

**Comment by cuonglm** [comment]
Not sure this is qualified for backporting, since when the `runtime.GOOS` checking is likely to happen so often in user code. A workaround can be moving the code for specific OS to separated file, instead of checking for `runtime.GOOS`.

cc @mdempsky @cherrymui

**Comment by mvdan** [comment]
I do think this should be backported if possible, as it's a regression with a seemingly small fix.

**Comment by ianlancetaylor** [comment]
CC @randall77
