### ISSUE TITLE
go/parser not parsing `any` struct field as InterfaceType

### ISSUE THREAD

**Issue by nirhaas** [golang/go#51830]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/nhaas/Library/Caches/go-build"
GOENV="/Users/nhaas/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/nhaas/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/nhaas/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/t8/83vffqv11_bbfxbbdc3fsfx40000gn/T/go-build159688595=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Tried to parse a struct with an `any` field, thinking it should be parsed as an empty interface (`interface{}`).

```go
package main

import (
	"fmt"
	"go/parser"
	"go/token"

	"github.com/davecgh/go-spew/spew"
)

func main() {
	fset := token.NewFileSet() // positions are relative to fset

	src := `package foo

type Sus struct {
	B interface{}
	C any
}
`

	// Parse.
	f, err := parser.ParseFile(fset, "", src, parser.ParseComments)
	if err != nil {
		fmt.Println(err)
		return
	}

	// Print.
	spew.Dump(f.Decls)
}
```

### What did you expect to see?

Both `B` and `C` fields parsed as InterfaceType.

### What did you see instead?

`B interface{}` parsed as InterfaceType.
`C any` parsed as identifier (`ast.Ident`).

**Comment by ianlancetaylor** [comment]
The type of `C` really is an identifier: the identifier `any`.  It's true that in a full compilation the type of `any` will be an interface type, but that's the job of go/types, not the job of go/parser.

Closing because this is behaving as expected.
