### ISSUE TITLE
cmd/compile: could not import "package" (cannot import "package" (type parameter bound more than once), possibly version skew - reinstall package)

### ISSUE THREAD

**Issue by elagergren-spideroak** [golang/go#51836]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

This is the latest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/elagergren/gopath/bin"
GOCACHE="/Users/elagergren/Library/Caches/go-build"
GOENV="/Users/elagergren/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/elagergren/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/elagergren/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/elagergren/git/some/path/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2b/74fz3jhd4wz4vnbf4z7ywzww0000gp/T/go-build2780518648=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://go.dev/play/p/oIoBIbuJ4n8

### What did you expect to see?

It compile correctly.

### What did you see instead?

Compiler error.

**Comment by elagergren-spideroak** [comment]
Related to #49893

**Comment by elagergren-spideroak** [comment]
Note that the problem the duplicate package name, `a/a`. Changing it to `a/b` fixes the problem: https://go.dev/play/p/5DWggeq6O_f

**Comment by ianlancetaylor** [comment]
CC @griesemer @findleyr

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport to 1.18

This seems to be a compiler error on valid code.

**Comment by findleyr** [comment]
I can take a look at this.

Presumably the problem is that the key in this index is incorrect, and doesn't differentiate the two packages:
https://cs.opensource.google/go/go/+/master:src/cmd/compile/internal/importer/iimport.go;l=219;drc=d35ed094864617d82c5701f56811ad68b37eda6e
