### ISSUE TITLE
net/netip: inconsistent terminology for IPv4-mapped IPv6 addresses in documentation

### ISSUE THREAD

**Issue by favonia** [golang/go#51834]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Read https://pkg.go.dev/net/netip@go1.18

### What did you expect to see?

A consistent name for IPv4 addresses wrapped in IPv6 addresses.

### What did you see instead?

Many different names or phrases have appeared in the documentation, and they seem to refer to the same thing:

- IPv4-mapped IPv6 address
- IP4-mapped IPv6 address
- IPv6-mapped IPv4 address
- v6-mapped form
- v6-mapped IPv6 address
- v6-mapped IPv4 IP

**Comment by ianlancetaylor** [comment]
CC @bradfitz @josharian

**Comment by favonia** [comment]
This seems to be fixed by #51950.

**Comment by favonia** [comment]
@hopehook If you are still interested, I think #51950 did not fix one `IP4` in the comments to `IPv4`. However, at this point, it's already much better than what it was.

**Comment by hopehook** [comment]
@favonia Thanks.
