### ISSUE TITLE
cmd/go: go work use -r panics when given a directory that does not exist

### ISSUE THREAD

**Issue by notfilippo** [golang/go#51841]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rossi/Library/Caches/go-build"
GOENV="/Users/rossi/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/rossi/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/rossi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.18/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.18/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK="/Users/rossi/go.work"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p0/53xvt8l57dj14b_pxf9dyyvw0000gn/T/go-build2599584196=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
go work use -r does_not_exist
```

### What did you expect to see?

An error message detailing that the directory does not exist.

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x141cdf5]

goroutine 1 [running]:
cmd/go/internal/workcmd.runUse.func2({0x7ff7bfeff8ff, 0xe}, {0x0, 0x0}, {0x5?, 0xc0000d3880?})
	/usr/local/Cellar/go/1.18/libexec/src/cmd/go/internal/workcmd/use.go:118 +0x35
cmd/go/internal/fsys.Walk({0x7ff7bfeff8ff, 0xe}, 0xc0000d39a8)
	/usr/local/Cellar/go/1.18/libexec/src/cmd/go/internal/fsys/fsys.go:441 +0x64
cmd/go/internal/workcmd.runUse({0x16dbd58?, 0xc00002a110?}, 0xc00002c528?, {0xc0000200e0, 0x1, 0x2?})
	/usr/local/Cellar/go/1.18/libexec/src/cmd/go/internal/workcmd/use.go:117 +0x97f
main.invoke(0x19be780, {0xc0000200c0, 0x3, 0x3})
	/usr/local/Cellar/go/1.18/libexec/src/cmd/go/main.go:218 +0x2ee
main.main()
	/usr/local/Cellar/go/1.18/libexec/src/cmd/go/main.go:175 +0x78e
```

### Proposed solution

In [go/src/cmd/go/internal/workcmd/use.go](https://github.com/golang/go/blob/7eaad60737bc507596c56cec4951b089596ccc9e/src/cmd/go/internal/workcmd/use.go#L110), starting from line 110.

```diff
+absArg, _ := pathRel(workDir, useDir)

+info, err := os.Stat(absArg)
+if err != nil {
+	if os.IsNotExist(err) {
+		base.Errorf("go: %v directory not found", absArg)
+	} else {
+		base.Errorf("go: %v", err)
+	}
+	continue
+} else if !info.IsDir() {
+	base.Errorf("go: %s not a directory", absArg)
+	continue
+}

if !*useR {
	  lookDir(useDir)
	  continue
}

// Add or remove entries for any subdirectories that still exist.

err = fsys.Walk(useDir, func(path string, info fs.FileInfo, err error) error {
+	if err != nil {
+		return err
+	}
	...
}
```

Happy to open a pull request if needed

**Comment by mknyszek** [comment]
CC @matloob @bcmills

**Comment by bcmills** [comment]
@gopherbot, please backport to Go 1.18. This is a user-facing panic in a feature introduced in Go 1.18.
