### ISSUE TITLE
x/build/dashboard: update darwin-arm64-11_0-toothrot builder macOS version to a newer point release

### ISSUE THREAD

**Issue by dmitshur** [golang/go#51851]
The new "Test execution environment" information in a recent build log ([example](https://build.golang.org/log/c77b38f4a093cd97a67f40231d63f7f998f8288b)) shows that `darwin-arm64-11_0-toothrot` is testing Go with darwin version `xnu-7195.41.8~9`, which corresponds to macOS Big Sur 11.0 (e.g., using this [release history](https://en.wikipedia.org/wiki/MacOS_Big_Sur#Release_history) as one source).

https://support.apple.com/en-us/HT201222 describes this version as "Preinstalled only on certain Mac models; please update to macOS Big Sur 11.0.1". It might not be possible to update to 11.0.1 today since newer point releases have superseded it, but updating to a newer version such as 11.6.5 should be available and fine.

Doing so should help make the information the builder produces more representative of uses of Go on Big Sur. It may also make a difference on occasional "unexpected stale targets reported by go list" failures ([recent example](https://build.golang.org/log/850fedbcc6ee497bcf4e16d1971d63aa00a65ca4)), though it's hard to predict.

CC @golang/release. (@toothrot asked to be assigned, so done, but please feel free to prioritize this maintenance opportunity vs others as needed.)

**Comment by toothrot** [comment]
Updated the machine.

[Recent build log](https://build.golang.org/log/1f9ed39d78d9eddd6f93273c0a5456f928264fba): 
```
# OS Version: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Tue Feb 22 21:10:42 PST 2022; root:xnu-7195.141.26~1/RELEASE_ARM64_T8101 arm64
```

This corresponds to 11.6.5 according to [Wikipedia](https://en.wikipedia.org/wiki/MacOS_Big_Sur#Release_history).

I've also unstacked the machines, which might have thermal benefits @bcmills, though they never feel particularly warm.
