### ISSUE TITLE
go: type parameter T is not comparable with >

### ISSUE THREAD

**Issue by elliotchance** [golang/go#51861]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/elliot/Library/Caches/go-build"
GOENV="/Users/elliot/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/elliot/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/elliot/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.18/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.18/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/elliot/Library/Mobile Documents/com~apple~CloudDocs/Development/github.com/elliotchance/pie/v2/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bt/185kd2pd0z132w85dn0x0y7w0000gn/T/go-build4078449481=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://go.dev/play/p/gOHY0ZMajP2

### What did you expect to see?

5

### What did you see instead?

```
./prog.go:14:6: invalid operation: s > max (type parameter T is not comparable with >)
```

I've tried a few different ways to coerce it to a `T` - but always with the same error.

**Comment by rittneje** [comment]
As per the documentation `comparable` only means it supports `==` and `!=`. (Probably it should have been called `equatable` instead.) You are looking for `golang.org/x/exp/constraints.Ordered`. https://go.dev/play/p/zRP649RJU6t

**Comment by daniel-santos** [comment]
Perhaps it should be renamed then?

**Comment by ianlancetaylor** [comment]
The spec has always referred to this property as "comparable", meaning a type whose values can be compared.
