### ISSUE TITLE
x/tools/go/pointer: example breaks with generics in sync/atomic

### ISSUE THREAD

**Issue by rsc** [golang/go#51889]
https://go.dev/cl/381317 is failing on x/tools/go/pointer
because that package is trying to do something with all
the dependencies of fmt, and sync/atomic is adding a use
of generics—Pointer[T]—in its API.

I believe that @timothy-king's work on go/ssa may fix this,
but it hasn't landed yet and he is on vacation. 
So for now I am filing this bug and will disable
x/tools/go/pointer/example_test.go.

**Comment by timothy-king** [comment]
I expect this to be working after https://go-review.googlesource.com/c/tools/+/397854. I cherry picked https://go.dev/cl/394974 into gotip and ran:
```
% gotip test -timeout 30s -run ^Example$ golang.org/x/tools/go/pointer
ok      golang.org/x/tools/go/pointer   0.733s
```
Closing for now. Please re-open if this is not working for you.
