### ISSUE TITLE
cmd/gofmt : gofmt issue with new generics

### ISSUE THREAD

**Issue by nagnagendra** [golang/go#51898]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.18 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1871870308=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I have written some code using go generics which is recently introduced in 1.18
While formatting the code using gofmt we're getting error as below

Error : sample.go:26:21: expected '(', found '['

Sample generic function :

 ```
func SumIntsOrFloats[K comparable, V int64 | float64](m map[K]V) V {
    var s V
    for _, v := range m {
        s += v
    }
    return s
} 
```

**Comment by ALTree** [comment]
You probably have an old `gofmt` binary somewhere. That code snippet is formatted correctly with Go1.18's `gofmt`. That error is what you got on the old one, that didn't support type parameters.

**Comment by khinshankhan** [comment]
If it's any help, my editor was using `goimports` before, and now it uses `gofmt` with the `-s` flag and works perfectly.

My go version is currently `go version go1.19.3 darwin/amd64`.
