### ISSUE TITLE
debug/gosym: LineToPC doesn't work on macho files 

### ISSUE THREAD

**Issue by yardenlaif** [golang/go#51890]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yarden/Library/Caches/go-build"
GOENV="/Users/yarden/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/yarden/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/yarden/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/yarden/go/go1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/yarden/go/go1.18/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6y/b_gs76zj0bl0frr40g1hrp080000gn/T/go-build2100507712=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I'm trying to use the `LineToPC` function in the `gosym` package. This is my parsing code:
https://go.dev/play/p/U1Rqy7nmrxd
You will have to use your own macho file to parse (pass to `getTable`) and fix the filename/lineno accordingly.
The macho file I try to parse was built with this command:
`go build -gcflags="-N -l" -o helloWorld main.go`

### What did you expect to see?
The pc for the given filename and lineno

### What did you see instead?
The filename and line I pass exist, but the error I am getting is:
> no code at /Users/yarden/GolandProjects/playground/helloWorld/main.go

When I run the same code but try to parse an elf (I pass an elf to `getTable`), everything works as expected. The problem only occurs on macho files.

**Comment by mknyszek** [comment]
CC @aclements @cherrymui maybe?

**Comment by mknyszek** [comment]
Does this reproduce with older releases as well, or is this a regression in 1.18?

**Comment by yardenlaif** [comment]
Works in 1.15, but not in 1.16 and 1.17

**Comment by jeremyfaller** [comment]
feels like this should be backported too.
