### ISSUE TITLE
cmd/link: error on windows/arm64 with clang/lld 13.0.1

### ISSUE THREAD

**Issue by jeremyd2019** [golang/go#51903]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 windows/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=arm64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=arm64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\msys64\clangarm64\lib\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\msys64\clangarm64\lib\go\pkg\tool\windows_arm64
set GOVCS=
set GOVERSION=go1.18
set GCCGO=gccgo
set AR=ar
set CC=clang
set CXX=clang++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\msys64\tmp\go-build1929041516=/tmp/go-build -gno-record-gcc-switches
</pre></details>

Windows 11 ARM64, running MSYS2's package of clang/llvm/lld 13.0.1.

### What did you do?

Download and extract https://downloads.rclone.org/v1.58.0/rclone-v1.58.0.tar.gz
```
  go build -ldflags -s
  (
    cd librclone
    go build --buildmode=c-shared -ldflags -s -o librclone.dll
  )
```

### What did you expect to see?

Successful build.

### What did you see instead?

```
# github.com/rclone/rclone/librclone
.debug_frame+1MB: addpesym: could not map .debug_frame+1MB symbol with non .text or .rdata or .data section
.debug_frame+2MB: addpesym: could not map .debug_frame+2MB symbol with non .text or .rdata or .data section
```

I have also seen this same error with hugo, but in that case the error only occurred when `-ldflags=-linkmode=external` was used and went away without that option.

**Comment by jeremyd2019** [comment]
That error message appears to come from https://github.com/golang/go/blob/4aa1efed4853ea067d665a952eee77c52faac774/src/cmd/link/internal/ld/pe.go#L690

**Comment by cherrymui** [comment]
I don't have a way to test it. Could you try if CL https://go-review.googlesource.com/c/go/+/395215 fixes it? Thanks!

**Comment by jeremyd2019** [comment]
I applied that patch to go 1.18, rebuilt go, and then built librclone.  It successfully built the DLL, but trying to load it gives an error that it's not a valid Win32 application.

**Comment by jeremyd2019** [comment]
That patch did however result in a successful and functional hugo.exe built with `-ldflags=-linkmode=external`

**Comment by jeremyd2019** [comment]
I haven't been able to figure out what's wrong with the DLL that Windows won't load it.  I'm attaching it in case somebody has some idea of what to look for.

[librclone.zip](https://github.com/golang/go/files/8338650/librclone.zip)

**Comment by cherrymui** [comment]
Thanks for testing. It seems the CL does fix the immediate issue.

> trying to load it gives an error that it's not a valid Win32 application. 

This looks like something different. How do you load the DLL?

**Comment by jeremyd2019** [comment]
I created a new issue to discuss the invalid DLL
