### ISSUE TITLE
cmd/vet: report that value of err is never used 

### ISSUE THREAD

**Issue by wxolp** [golang/go#51902]
### What version of Go are you using (`go version`)?

~~~
go version go1.18 windows/amd64
~~~

### What did you do?

Using this program:

~~~go
package hello
import "strconv"

type private int

func Public() (private, error) {
   n, err := strconv.Atoi("99")
   if err != nil {
      return 0, err
   }
   _, err = strconv.Atoi("88")
   return private(n), nil
}
~~~

### What did you expect to see?

With other tools [1], I get this error:

~~~
this value of err is never used (SA4006)
~~~

1. https://github.com/dominikh/go-tools

### What did you see instead?

but nothing with `go vet`. I am trying to find something that works with Go 1.18. It seems `unusedresult` should cover this case.

**Comment by ALTree** [comment]
Staticcheck flags much more stuff than `go vet`, and I don't think it's feasible - or desirable - to port every staticcheck warning to `go vet` just because staticcheck happens not to work with Go 1.18 at the moment.

> It seems unusedresult should cover this case.

`unusedresult` takes a list of functions whose result must be used; this is much more general, since it could potentially flag *any* function call that returns an error.

**Comment by wxolp** [comment]
> Staticcheck flags much more stuff than `go vet`, and I don't think it's feasible - or desirable - to port every staticcheck warning to `go vet` just because staticcheck happens not to work with Go 1.18 at the moment.

@ALTree thank you for the feedback. Respectfully, the purpose of this issue isn't to "port every staticcheck warning". I simple reading of the issue can confirm that. I would appreciate if you don't misreprent my original comments.

I am interested in this specific issue, as detailed in the original post. If other staticcheck items are also added, I might be interested in that, but not at this time.

**Comment by seankhliao** [comment]
Despite the name, `unusedresult` is only for pure functions, and not for things like not using an error variable.

General catching of error is #20148

**Comment by ALTree** [comment]
>  Respectfully, the purpose of this issue isn't to "port every staticcheck warning". A simple reading of the issue can confirm that. I would appreciate it, if you don't misrepresent my original comments

To clarify: you wrote "I get this warning with staticcheck , but it doesn't work with 1.18. I'm looking for something that works with Go1.18". I simply wanted to point out that this argument applies to *every* check that staticcheck has, so *per se* it's not an argument in favour of the specific check you were asking. Sorry if that wasn't clear.

**Comment by wxolp** [comment]
> To clarify: you wrote "I get this warning with staticcheck , but it doesn't work with 1.18. I'm looking for something that works with Go1.18".

@ALTree no, I didn't write that. Now you're not only misrepresenting me, but you're literally misquoting me. What I actually wrote was:

> With other tools, I get this error [...], but nothing with `go vet`. I am trying to find something that works with Go 1.18.

I would appreciate if you please stop misquoting and misrepresenting my argument. This is especially true, given that if you read the post as a whole, it should become true to the average person, that this post is about a single problem, not porting the entirely of staticcheck to Go tools.

I think in the future, it would serve you well not to be pointlessly argumentative to people posting issues. If you are interested in having semantic arguments, maybe another forum would be better suited for that.

**Comment by wxolp** [comment]
> To clarify: you wrote "I get this warning with staticcheck , but it doesn't work with 1.18. I'm looking for something that works with Go1.18".

@ALTree no, I didn't write that. Now you're not only misrepresenting me, but you're literally misquoting me. What I actually wrote was:

> With other tools, I get this error [...], but nothing with `go vet`. I am trying to find something that works with Go 1.18.

I would appreciate if you please stop misquoting and misrepresenting my argument. This is especially true, given that if you read the post as a whole, it should become true to the average person, that this post is about a single problem, not porting the entirely of staticcheck to Go tools.

I think in the future, it would serve you well not to be pointlessly argumentative to people posting issues. If you are interested in having semantic arguments, maybe another forum would be better suited for that.
