### ISSUE TITLE
runtime/debug: ReadBuildInfo returns !ok

### ISSUE THREAD

**Issue by ablqk** [golang/go#51915]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

It only reproduces with the lastest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="~/.cache/go-build"
GOENV="~/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="..."
GONOPROXY="..."
GONOSUMDB="..."
GOOS="linux"
GOPATH="..."
GOPRIVATE="..."
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1839977099=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I am using the debug package in a unit testing environment:

```
import "runtime/debug"

func Test_modinfo(t *testing.T) {
	_, ok := debug.ReadBuildInfo()
	if ok {
		t.Fail()
	}
}
```

### What did you expect to see?

The test passes in version 1.17
 
### What did you see instead? 

The test does not pass in version 1.18

### My investigation so far

https://github.com/golang/go/blob/master/src/runtime/debug/mod.go#L15
Apparently, the `modinfo()` method returns exactly 32 bytes in 1.18, and 0 in 1.17, leading to a different behaviour.

It happens both on my machine and in my CI docker image which uses go latest.

**Comment by seankhliao** [comment]
I can't reproduce it, with
```
func Test_modinfo(t *testing.T) {
	bi, ok := debug.ReadBuildInfo()
	if ok {
		t.Log(bi)
		t.Fail()
	}
}
```
The output for 1.17.8 and 1.18 are:
```
main » go1.17.8 test
--- FAIL: Test_modinfo (0.00s)
    main_test.go:11: &{go.seankhliao.com/testrepo-833 {go.seankhliao.com/testrepo-833 (devel)  <nil>} []}
FAIL
exit status 1
FAIL	go.seankhliao.com/testrepo-833	0.001s
```
```
main » go1.18 test   
--- FAIL: Test_modinfo (0.00s)
    main_test.go:11: go	go1.18
        path	go.seankhliao.com/testrepo-833
        mod	go.seankhliao.com/testrepo-833	(devel)	
        build	-compiler=gc
        build	CGO_ENABLED=1
        build	CGO_CFLAGS=
        build	CGO_CPPFLAGS=
        build	CGO_CXXFLAGS=
        build	CGO_LDFLAGS=
        build	GOARCH=amd64
        build	GOOS=linux
        build	GOAMD64=v1
        build	vcs=git
        build	vcs.revision=ce9d04da5cfff9b82b1961bc82ae0482841f799a
        build	vcs.time=2022-03-24T14:30:06Z
        build	vcs.modified=true
        
FAIL
exit status 1
FAIL	go.seankhliao.com/testrepo-833	0.001s
```
Which looks to be working as intended

**Comment by slavabobik** [comment]
On my env I could reproduce that
```
go version
go version go1.18 darwin/amd64

```
