### ISSUE TITLE
cmd/gofmt: inconsistent indentation of struct fields of containing tab

### ISSUE THREAD

**Issue by fraenky8** [golang/go#51910]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, also playground.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/user/Coding/Go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/user/Coding/Go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.18/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.18/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8v/jgh2dzcn62n0lfyws13mc_rw0000gp/T/go-build3442110454=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Run `gofmt -d` on the following program

https://go.dev/play/p/bVJxvovrvWB

```go
package main

import "fmt"

type S struct {
	S       string
	Integer int //  extra long field name to point out the indentation
}

func main() {
	s := []S{
		{
			S:       "Hello World",
			Integer: 42,
		},
		{
			S:       "\t",
			Integer: 42,
		},
		{
			S:       "	", // an actual <tab>
			Integer: 42,
		},
		{
			S:       `	`, // an actual <tab>
			Integer: 42,
		},
		{
			S:       "\u0009",
			Integer: 42,
		},
	}

	fmt.Printf("%#v", s)
}
```

### What did you expect to see?

```go
	s := []S{
		{
			S:       "Hello World",
			Integer: 42,
		},
		{
			S:       "\t",
			Integer: 42,
		},
		{
			S:       "	", // an actual <tab>
			Integer: 42,
		},
		{
			S:       `	`, // an actual <tab>
			Integer: 42,
		},
		{
			S:       "\u0009",
			Integer: 42,
		},
	}
```

### What did you see instead?

The fields with the actual tab-value are not indented as expected. Is this expected behavior?

```go
	s := []S{
		{
			S:       "Hello World",
			Integer: 42,
		},
		{
			S:       "\t",
			Integer: 42,
		},
		{
			S: "	", // an actual <tab>
			Integer: 42,
		},
		{
			S: `	`, // an actual <tab>
			Integer: 42,
		},
		{
			S:       "\u0009",
			Integer: 42,
		},
	}
```

**Comment by mknyszek** [comment]
Is this new in Go 1.18?

CC @griesemer via https://dev.golang.org/owners

**Comment by griesemer** [comment]
This doesn't look like a new issue; I can reproduce this with Go 1.16. Looks like some unexpected interaction of the "actual <tab>" character with the formatting routine (`tabwriter`) which uses tabs for alignment, even though in the case of literal strings (as we have here), they string contents should be protected from such interaction.

cc: @mvdan any interest in looking into this?

**Comment by mvdan** [comment]
Fix sent :) Definitely one of those that took longer to debug than to actually fix.

The literals are indeed escaped from the tabwriter. The problem was in the code that predicts the size of each node as printed on a single line; it got confused by tab characters.
