### ISSUE TITLE
go mod tidy does not solves the issue for running make generate

### ISSUE THREAD

**Issue by NikhilSharmaWe** [golang/go#51921]
- make generate gives error
```
Error : build sigs.k8s.io/kubebuilder/v3/cmd: cannot load embed: malformed module path "embed": missing dot in first path element
make: *** [Makefile:71: generate-testdata] Error 1
```
![Screenshot (813)](https://user-images.githubusercontent.com/77074571/159963670-7751aaeb-67f9-404d-bdac-e1a53ce38af2.png)
 
- I run go mod tidy to solve the issue it make some changes in go.mod but it does not solves the issue and gives same error.

**go version go1.17.1 windows/amd64**

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
