### ISSUE TITLE
Go mod local replace no longer linked dynamically in 1.18, requires constant vendoring

### ISSUE THREAD

**Issue by berndverst** [golang/go#51932]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.0 darwin/arm64

</pre>

### Does this issue reproduce with the latest release?

Latest release only!

### What operating system and processor architecture are you using (`go env`)?

Darwin Arm64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/bverst/Library/Caches/go-build"
GOENV="/Users/bverst/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/bverst/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/bverst/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.8"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/bverst/src/dapr/mongoissue/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x9/9dhxnxcd5bjbyktd4h_vhgyc0000gn/T/go-build729128645=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

1. Overwrite a module in go mod `go mod edit -replace=github.com/dapr/components-contrib=../components-contrib`
2. Make changes to local copy of module
3. Build project and notice that changes do not appear
4. Run `go mod vendor` and build project and notice changes do appear
5. Repeat from step 2... fully reproducible.

### What did you expect to see?

As recently as Go 1.17.8 it was not necessary to run `go mod vendor` to sync my locally replaced modules, these were just dynamically linked. Building my project would always use the latest version.

### What did you see instead?

The locally replaced module is still cached with whatever version was last vendored.

**Comment by seankhliao** [comment]
As far as I can tell it has always worked this way:
```
» exa -T                     
.
├── dep
│  ├── dep.go
│  └── go.mod
└── main
   ├── go.mod
   ├── main.go
   └── vendor
      ├── example
      │  └── dep
      │     └── dep.go
      └── modules.txt

0:20:48 ~/tmp/51932 0:00:00
» cat dep/dep.go     
package dep

var V = 2

0:21:09 ~/tmp/51932 0:00:00
» cat main/vendor/example/dep/dep.go 
package dep

var V = 1

0:21:22 ~/tmp/51932 0:00:00
» cd main                       

0:21:23 ~/tmp/51932/main 0:00:00
» cat go.mod                        
module example

go 1.17

require example/dep v0.0.1

replace example/dep => ../dep

0:21:25 ~/tmp/51932/main 0:00:01
» go1.16.14 run .
1

0:21:27 ~/tmp/51932/main 0:00:00
» go1.17.8 run .         
1

0:21:29 ~/tmp/51932/main 0:00:00
» go1.18 run .         
1
```

**Comment by seankhliao** [comment]
Setting the `go` directive in `go.mod` to `go 1.13` will get the behavior you're describing, this is documented in `go help build`.

Closing as I believe this is working as documented.
