### ISSUE TITLE
proposal: Return channel from goroutine

### ISSUE THREAD

**Issue by neelsg** [golang/go#51938]
Hi everyone,

It would be nice if the `go` keyword worked as an expression instead of a statement with the return value being a channel of whatever type the called function return value is.

As an example, the following code in the Go tour:
```
func sum(s []int, c chan int) {
	sum := 0
	for _, v := range s {
		sum += v
	}
	c <- sum // send sum to c
}

func main() {
	s := []int{7, 2, 8, -9, 4, 0}

	c := make(chan int)
	go sum(s[:len(s)/2], c)
	go sum(s[len(s)/2:], c)
	x, y := <-c, <-c // receive from c

	fmt.Println(x, y, x+y)
}
```

Could be refactored as:
```
func sum(s []int) int {
	sum := 0
	for _, v := range s {
		sum += v
	}
	return sum
}

func main() {
	s := []int{7, 2, 8, -9, 4, 0}

	c1 := go sum(s[:len(s)/2])
	c2 := go sum(s[len(s)/2:])
	x, y := <-c1, <-c2 // receive from c

	fmt.Println(x, y, x+y)
}
```

### Motivation

Subjectively, this would lead to simpler code, but another major advantage would be decoupling the called function from concurrency design. In the example above, when writing `func sum` you don't need to support / think about concurrency at all. This makes it so that any function could potentially get used as a goroutine even if the original author of that function did not design for it. If you want to implement concurrency, but the `sum` function is written by someone else or is located in a third-party library, currently you would have to create a wrapper function such as:
```
func sumWrapper(s []int, c chan int) {
	c <- sum(s) // send sum to c
}
```

### No impact on existing code

Given that `go` is currently only used as a statement instead of an expression, this won't break anything and would have no impact on any existing code.

### Notes

- My apologies if this was proposed before (I searched and couldn't find anything)
- This is my first proposal, so my apologies also if I used the wrong format
- This is taking some inspiration from how async/await works in Javascript, but is better in my opinion as it does not require the original function to be marked with `async`.

**Comment by seankhliao** [comment]
Seems like #26287 #25821 #33046
Please comment if you disagree
