### ISSUE TITLE
runtime: redundant allocation & copy in return string([]byte)

### ISSUE THREAD

**Issue by jfcg** [golang/go#51937]
### What version of Go are you using (`go version`)?
`go1.17.8`

### Does this issue reproduce with the latest release?
yes also with `go1.18`

### What operating system and processor architecture are you using (`go env`)?
x86_64 Linux

### What did you do?
pkg.go
```go
package pkg

// ToLower converts ascii string s to lower-case
func ToLower(s string) string {
	if s == "" {
		return ""
	}
	buf := make([]byte, len(s))

	for i := 0; i < len(s); i++ {
		c := s[i]
		if 'A' <= c && c <= 'Z' {
			c |= 32
		}
		buf[i] = c
	}
	return string(buf)
}
```
pkg_test.go
```go
package pkg

import "testing"

func BenchmarkToLower(b *testing.B) {
	str := "SomE StrInG"
	want := "some string"
	var res string

	for i := 0; i < b.N; i++ {
		res = ToLower(str)
	}
	if res != want {
		b.Fatal("ToLower error")
	}
}
```
`go test -v -bench ToLower -benchmem -count=3` prints
```
BenchmarkToLower-4      18710726                66.86 ns/op           32 B/op          2 allocs/op
BenchmarkToLower-4      17420910                65.57 ns/op           32 B/op          2 allocs/op
BenchmarkToLower-4      17085405                63.16 ns/op           32 B/op          2 allocs/op
```
### What did you expect to see?
I was expecting to see a single memory allocation in `ToLower()` since there is no other reference to `buf`.

### What did you see instead?
As is clear in bench output, there must a redundant allocation & copy in `return string(buf)`.

**Comment by seankhliao** [comment]
I think this is a dup of #50846
Please comment if you disagree
