### ISSUE TITLE
all: move dev.boringcrypto into main branch behind GOEXPERIMENT

### ISSUE THREAD

**Issue by rsc** [golang/go#51940]
The dev.boringcrypto branch started out as a bit of an experiment, back in the Go 1.8 time frame. It is clearly here to stay as something that we maintain alongside the main distribution.

Maintaining a whole separate branch is cumbersome, requiring frequent conflict resolution during merges and being just generally painful. 

It would be far less upkeep if we kept the boringcrypto code in the main branch behind a GOEXPERIMENT, same as we do for GOEXPERIMENT=fieldtrack. We should do that.

This bug is to track work toward that goal. Generally speaking it will require a little bit of rewriting of parts that we can't reasonably merge and then a bunch of build tags.

**Comment by qmuntal** [comment]
@rsc have you considered moving `crypto/internal/boring` to `golang.org/x/crypto/boring` and use it as a vendored package? This approach is showing good results in our out-of-tree [OpenSSL port](https://github.com/microsoft/go-crypto-openssl), reducing code bloat in the main repo and making it easier to maintain and backport.

**Comment by rsc** [comment]
@srikanthps They will not. You will be able to use go build -tags boringcrypto in a standard Go 1.19 release. Note that all things boringcrypto are unsupported, and this is not guaranteed to continue working in future releases.

**Comment by rsc** [comment]
@pfox1969 The BoringCrypto module being used did not change as part of this work.

**Comment by qmuntal** [comment]
@rsc I've submitted https://go.dev/cl/413754 which cleans a longstanding `crypto/sha1` leftover related to boring. Hope it can make it into go1.19 as this issue is still open.

**Comment by ianlancetaylor** [comment]
@rsc Is there anything left to do for this issue?

**Comment by rsc** [comment]
This is all done.

**Comment by liggitt** [comment]
> @srikanthps They will not. You will be able to use go build -tags boringcrypto in a standard Go 1.19 release. Note that all things boringcrypto are unsupported, and this is not guaranteed to continue working in future releases.

fwiw, I was not able to get this to work with `go build -tags boringcrypto ...`, but setting `GOEXPERIMENT=boringcrypto go build ...` worked fine.

**Comment by ianlancetaylor** [comment]
@rsc Was the new approach of `GOEXPERIMENT=boringcrypto` ever documented anywhere?

**Comment by rsc** [comment]
We don't officially support boringcrypto. To the extent that there was documentation before, it was at https://go.googlesource.com/go/+/refs/heads/dev.boringcrypto/README.boringcrypto.md, and that has been updated.

**Comment by rsc** [comment]
@liggitt, missed your Aug 5 comment. You found the right answer: GOEXPERIMENT works, -tags does not. I've updated my comment above.

**Comment by linouk23** [comment]
👋 everyone, could someone take a look at https://stackoverflow.com/questions/75638176/how-can-i-check-whether-my-golang-app-is-fips-compliant, thanks!
