### ISSUE TITLE
cmd/go: reject list -export -find more clearly

### ISSUE THREAD

**Issue by rsc** [golang/go#51952]
cmd/go/internal/list/list.go says

	// These pairings make no sense.
	if *listFind && *listDeps {
		base.Fatalf("go list -deps cannot be used with -find")
	}
	if *listFind && *listTest {
		base.Fatalf("go list -test cannot be used with -find")
	}

but the same is true of *listExports.

	% go list -export -f '{{.Export}}' strconv
	/Users/rsc/go/pkg/darwin_amd64/strconv.a
	% go list -export -find -f '{{.Export}}' strconv
	# strconv
	../../strconv/atof.go:13:8: could not import math (open : no such file or directory)
	../../strconv/atoi.go:7:8: could not import errors (open : no such file or directory)
	../../strconv/bytealg.go:10:8: could not import internal/bytealg (open : no such file or directory)
	../../strconv/eisel_lemire.go:22:2: could not import math/bits (open : no such file or directory)
	../../strconv/quote.go:10:2: could not import unicode/utf8 (open : no such file or directory)
	% 
	
This should probably be fixed in cmd/go and possibly also in the docs, which say nothing about -find being incompatible with other flags.

**Comment by ianlancetaylor** [comment]
@bcmills @matloob This issue is marked for 1.19.  It's just been rolling forward in milestones.  Should it move to Backlog?  Thanks.

**Comment by bcmills** [comment]
Looks like a contributor sent a fix CL that we missed. I've reviewed it (it's small, self-contained, and low-risk), so I think this can indeed make Go 1.19.
