### ISSUE TITLE
path: Split and Base functions do not handle Windows file paths

### ISSUE THREAD

**Issue by algonzalez** [golang/go#51951]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOVERSION=go1.18
set GCCGO=gccgo
set GOAMD64=v1
</pre></details>

### What did you do?

https://play.golang.com/p/PjD4wd90jdN

### What did you expect to see?
path   : /tmpfs/me/foo
-> dir : /tmpfs/me/
-> file: foo
-> base: foo
path   : \users\me\foo.exe
-> dir : \users\me\ 
-> file: foo.exe
-> base: foo.exe
path   : C:\users\me\foo.exe
-> dir : C:\users\me\
-> file: foo.exe
-> base: foo.exe

### What did you see instead?
path   : /tmpfs/me/foo
-> dir : /tmpfs/me/
-> file: foo
-> base: foo
path   : \users\me\foo.exe
-> dir : 
-> file: \users\me\foo.exe
-> base: \users\me\foo.exe
path   : C:\users\me\foo.exe
-> dir : 
-> file: C:\users\me\foo.exe
-> base: C:\users\me\foo.exe

**Comment by mvdan** [comment]
Are you aware of the filepath package?

**Comment by ianlancetaylor** [comment]
The path package is for slash separated strings.

The path/filepath package changes behavior based on the operating system it is run on.

Closing because I don't think there is anything to do here.  Please comment if you disagree.
