### ISSUE TITLE
x/text: Title() behaves differently than strings.Title()

### ISSUE THREAD

**Issue by hangxie** [golang/go#51956]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/xiehang/Library/Caches/go-build"
GOENV="/Users/xiehang/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xiehang/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xiehang/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.18/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.18/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xiehang/dev/parquet-tools/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vj/wtn1vqpj12g4k75p7snx28d80000gn/T/go-build3311008797=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://go.dev/play/p/qGo_iTp7AQ7

### What did you expect to see?
`cases.Title()` behaves the same as `strings.Title()`, I believe this is what https://github.com/golang/go/issues/48367 tells (explicitly)

### What did you see instead?
`cases.Title()` changes the first character to uppercase, and change rest of the string lowercase
`strings.Title()` changes the first character to uppercase, leave rest of the string untouched.

**Comment by frederikhors** [comment]
Surprisingly, in the same minutes you, @hangxie and I discovered the same problems: https://github.com/golang/go/issues/48367#issuecomment-1079506378.

**Comment by ianlancetaylor** [comment]
I'm not sure there is anything to do here.  Evidently we were mistaken in thinking that `cases.Title` was a drop-in replacement for `strings.Title`.  Sorry about that.  But changing `cases.Title` would lead to compatibility concerns.  And the deprecation notice for `strings.Title` doesn't actually refer to `cases.Title`.

I'm open to suggestions.

**Comment by smasher164** [comment]
`cases.Title` does work as a substitute for `strings.Title` as long as you pass in the `cases.NoLower` option to the `Caser`.
The corrected version of the example should be
https://go.dev/play/p/uzYSvdtKNRy
```Go
package main

import (
	"fmt"
	"strings"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

func main() {
	orig := "thisIsCool"
	c := cases.Title(language.Und, cases.NoLower).String(orig)
	s := strings.Title(orig)
	fmt.Printf("orig: %s\ncases: %s\nstrings: %s\n", orig, c, s)
}
```
which outputs
```
orig: thisIsCool
cases: ThisIsCool
strings: ThisIsCool
```

**Comment by hangxie** [comment]
> cases.Title does work as a substitute for strings.Title as long as you pass in the cases.NoLower option to the Caser.

Perfect, thank you!
