### ISSUE TITLE
plugin: "built with a different version of package" error with go 1.18 & CGO

### ISSUE THREAD

**Issue by dtrudg** [golang/go#51955]
### What version of Go are you using (`go version`)?

<pre>
go version go1.18 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dtrudg/.cache/go-build"
GOENV="/home/dtrudg/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dtrudg/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dtrudg/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/dtrudg/Git_sylabs/singularity/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build864842809=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

We have a plugin (https://github.com/sylabs/singularity/blob/master/e2e/plugin/testdata/runtime_singularity/callback.go) that indirectly imports a package containing some CGO code (https://github.com/sylabs/singularity/tree/master/internal/pkg/util/user).

I have tried to extract a simpler reproducer, but haven't managed to hit the same issue yet... so what follows is, unfortunately, a terse description of a rather complicated build...

Our main binary is compiled with the following `go build` and `GOFLAGS` contains `-trimpath`

```
go build
  -mod=readonly
  -buildmode=pie
  -tags "containers_image_openpgp exclude_graphdriver_btrfs exclude_graphdriver_devicemapper sylog singularity_engine fakeroot_engine apparmor selinux seccomp"  
  -gcflags=github.com/sylabs/singularity/...="-trimpath /home/dtrudg/Git_sylabs/singularity=>github.com/sylabs/singularity@v0.0.0" 
  -asmflags=github.com/sylabs/singularity/...="-trimpath /home/dtrudg/Git_sylabs/singularity=>github.com/sylabs/singularity@v0.0.0"
  -o ./singularity 
  /home/dtrudg/Git_sylabs/singularity/cmd/singularity
```

The plugin is built by copying the source into a temporary directory, and then using the following `go build`:

```
go build 
  -a 
  -o /tmp/plugin-1291001354/src/plugin.so 
  -mod=readonly 
  -ldflags -X main.PluginRootDir=/usr/local/libexec/singularity/plugin 
  -trimpath 
  -buildmode=plugin 
  -tags containers_image_openpgp exclude_graphdriver_btrfs exclude_graphdriver_devicemapper sylog singularity_engine fakeroot_engine apparmor selinux seccomp
  .
```

### What did you expect to see?

With Go 1.17.8 or prior, the compiled plugin can be loaded by the main binary without issue.

### What did you see instead?

With Go 1.18, the plugin is compiled without issue, but when the main binary attempts to load it, it fails with an error:

```
plugin.Open("/tmp/plugin-1836960432/src/plugin"): plugin was built with a different version of package github.com/sylabs/singularity/internal/pkg/util/user
```

Examining the pkghashbytes for the "github.com/sylabs/singularity/pkg/image" package, I can see a difference between the main binary and plugin:

```
main binary: 
go.link.pkghashbytes.github.com/sylabs/singularity/internal/pkg/util/user: 
[233 225 141 122 49 203 202 104]

plugin:
go.link.pkghashbytes.github.com/sylabs/singularity/internal/pkg/util/user:
[189 134 9 108 2 209 91 245]
```

I can see that there is a difference in the strings section exposed in `cmd/compile/internal/typecheck/iexport.go`:

```
main binary compilation
# github.com/sylabs/singularity/internal/pkg/util/user
export: hdr strings 533, data 950, index 1039

plugin compilation
# github.com/sylabs/singularity/internal/pkg/util/user
export: hdr strings 504, data 950, index 1039
```

Grabbing these and converting to text we have:

strings section in the main binary build…
```
Lgithub.com/sylabs/singularity@v0.0.0/internal/pkg/util/user/identity_unix.goNameUIDGIDGecosDirShelluidUser~r0~r1$autotmp
lookupUnixUidNgithub.com/sylabs/singularity@v0.0.0/internal/pkg/util/user/cgo_lookup_unix.goname
lookupUserusernamegidGroup
lookupUnixGidlookupGroup	groupnamecurrentIgithub.com/sylabs/singularity@v0.0.0/internal/pkg/util/user/membership.golistesc:,/tmp/go-build2510098997/b050/_cgo_gotypes.gouser	.inittaskCurrentCurrentOriginalGetGrGIDGetGrNamGetPwNamGetPwUID
UIDInAnyGroup	UIDInList
```

strings section in the plugin build…
```
Lgithub.com/sylabs/singularity@v0.0.0/internal/pkg/util/user/identity_unix.goNameUIDGIDGecosDirShelluidUser~r0~r1$autotmp
lookupUnixUidNgithub.com/sylabs/singularity@v0.0.0/internal/pkg/util/user/cgo_lookup_unix.goname
lookupUserusernamegidGroup
lookupUnixGidlookupGroup	groupnamecurrentIgithub.com/sylabs/singularity@v0.0.0/internal/pkg/util/user/membership.golistesc:_cgo_gotypes.gouser	.inittaskCurrentCurrentOriginalGetGrGIDGetGrNamGetPwNamGetPwUID
UIDInAnyGroup	UIDInList
```

The difference here being an extra `,/tmp/go-build2510098997/b050/` prior to `_cgo_gotypes.gouser` in the build of the main binary.

I'm not sure what might have changed from 1.17.x -> 1.18 to cause this?

A quick `strings $(which singularity)` (main binary) for different 1.18 and 1.17.8 builds shows at least some kind of difference without the context:

**Go 1.18**
```
strings $(which singularity) | grep "_cgo_gotypes.go"
_cgo_gotypes.go
/tmp/go-build2709203403/b271/_cgo_gotypes.go
/tmp/go-build2709203403/b666/_cgo_gotypes.go
```

**Go 1.17.8**
```
strings $(which singularity) | grep "_cgo_gotypes.go"
_cgo_gotypes.go
/tmp/go-build1536705585/b262/_cgo_gotypes.go
```

Any pointers on where to go here would be appreciated!

**Comment by zhouguangyuan0718** [comment]
I'm a little confused. When you build the plugin,  you use `-trimpath` for `go build`. But when you build the main binary, you only use `-trimpath` for `-gcflags`. How does other pkghash 
 equal, such as runtime? As I know, the hash of every package is related to the path of it.  The path is different when "-trimpath" is enabled.

**Comment by dtrudg** [comment]
> I'm a little confused. When you build the plugin, you use `-trimpath` for `go build`. But when you build the main binary, you only use `-trimpath` for `-gcflags`. How does other pkghash equal, such as runtime? As I know, the hash of every package is related to the path of it. The path is different when "-trimpath" is enabled.

The general `-trimpath` is user for the main binary in addition to the asmflags and gcflags trimpath, but it is set via `GOFLAGS` env var
>> Our main binary is compiled with the following go build and GOFLAGS contains -trimpath

Am pretty confident this is working, as we don't see any issue with Go 1.17.8 or older - this problem only occurs with Go 1.18... and the error occurs only for a particular package that uses cgo. Other plugins that don't use our `github.com/sylabs/singularity/internal/pkg/util/user` package are fine with Go 1.18.

I can pull out the strings section for Go 1.17.8 (which works) tomorrow, with exactly the same build flags / GOFLAGS to clarify a bit further.

**Comment by dtrudg** [comment]
By looking into `src/cmd/compile/internal/noder/noder.go trimFilename()` which calls `src/cmd/internal/objabi/line.go Absfile` I think I've found this is related to building with a `-trimpath` inside `-gcflags` on Go 1.18.

When building with a `-trimpath` in `-gcflags`...

```
/home/dave/Git_sylabs/go/bin/go build 
-mod=readonly 
-buildmode=pie 
-trimpath 
-tags "containers_image_openpgp exclude_graphdriver_btrfs exclude_graphdriver_devicemapper sylog singularity_engine fakeroot_engine apparmor selinux seccomp" 
-ldflags="-B 0x`head -c20 /dev/urandom|od -An -tx1|tr -d ' \n'`" 
-gcflags=github.com/sylabs/singularity/...="-trimpath /home/dtrudg/Git_sylabs/singularity=>github.com/sylabs/singularity@v0.0.0" 
-asmflags=github.com/sylabs/singularity/...="-trimpath /home/dtrudg/Git_sylabs/singularity=>github.com/sylabs/singularity@v0.0.0" 
-o cmd/starter/c/starter-suid 
/home/dtrudg/Git_sylabs/singularity/cmd/starter/main_linux.go
```

... it's apparent that AbsFile doesn't receive the rewrite that will remove the `/tmp/gobuildxxxxx` path for the `_cgo_gotypes.go`. It only recieves the rewrite that was set via the `-gcflags`:

```
# github.com/sylabs/singularity/internal/pkg/util/user
AbsFile dir:/home/dtrudg/Git_sylabs/singularity file:/tmp/go-build2238438623/b050/_cgo_gotypes.go rewrites:/home/dtrudg/Git_sylabs/singularity=>github.com/sylabs/singularity@v0.0.0
trimFilename: b.Filename()=/tmp/go-build2238438623/b050/_cgo_gotypes.go b.Trimmed()=false b.IsFileBase()=true filename=/tmp/go-build2238438623/b050/_cgo_gotypes.go
```

If I drop the `-gcflags` from `go build` then `AbsFile` is getting a rewrite that removes the `/tmp/go-buildxxxx` from the _cgo_gotypes.go` path:

```
/home/dave/Git_sylabs/go/bin/go build
-mod=readonly
-buildmode=pie
-trimpath
-tags "containers_image_openpgp exclude_graphdriver_btrfs exclude_graphdriver_devicemapper sylog singularity_engine fakeroot_engine apparmor selinux seccomp"
-ldflags="-B 0x`head -c20 /dev/urandom|od -An -tx1|tr -d ' \n'`"
-asmflags=github.com/sylabs/singularity/...="-trimpath /home/dtrudg/Git_sylabs/singularity=>github.com/sylabs/singularity@v0.0.0"
-o cmd/starter/c/starter-suid
/home/dtrudg/Git_sylabs/singularity/cmd/starter/main_linux.go 

# github.com/sylabs/singularity/internal/pkg/util/user
AbsFile dir:/home/dtrudg/Git_sylabs/singularity file:/tmp/go-build1956690545/b050/_cgo_gotypes.go rewrites:/home/dtrudg/Git_sylabs/singularity/internal/pkg/util/user=>github.com/sylabs/singularity/internal/pkg/util/user;/tmp/go-build1956690545/b050=>
trimFilename: b.Filename()=/tmp/go-build1956690545/b050/_cgo_gotypes.go b.Trimmed()=false b.IsFileBase()=true filename=_cgo_gotypes.go
```

**Comment by seankhliao** [comment]
So, similar to #47256 , use the high level `-trimpath` and not the individual tool flags.
In which case I don't think there's anything to do here?

**Comment by dtrudg** [comment]
> So, similar to https://github.com/golang/go/issues/47256 , use the high level -trimpath and not the individual tool flags.
In which case I don't think there's anything to do here?

Our main binary compilation uses the `-trimpath` in the tool flags as we have a somewhat wacky process of using `runtime.Caller(0)` and some substitution to identify our own source path so that our CLI can provide a command to compile plugins code that is not within our source tree. 

I'll look into whether we can do this more sanely, but at the time it was the implementation that a developer came up with to allow people to build plugins via our own CLI.

I guess I'm interested in pursuing this a bit more, as it used to work up to and including 1.17 - and presumably the gcflag trimpath could just be appended to the rewrites that AbsFile sees, rather than replace them... which would maintain the 1.17 behavior?

**Comment by dtrudg** [comment]
Having come across a definitive message, while browsing through issues, that...

> [rsc](https://github.com/rsc) commented [on Apr 22, 2019](https://github.com/golang/go/issues/24976#issuecomment-485632911)
> Direct use of -gcflags=-trimpath is unsupported.

... we'll drop back to a more restrictive approach for building plugins in our app, that doesn't require that.

Apologies for the noise!
