### ISSUE TITLE
x/tools/gopls: go vet: Printf incorrect type check in generic method

### ISSUE THREAD

**Issue by ogau** [golang/go#51968]
Type in printf function for floating-point verb is specified correctly, but go vet shows this as an error

### gopls version
gopls v0.8.1

### Editor and settings
vscode 1.65.2
 ```
"gopls": {
        "ui.diagnostic.staticcheck": true,
        "ui.completion.usePlaceholders": true,
        "ui.diagnostic.analyses": {
            // "fieldalignment": true,
            "nilness": true,
            "shadow": true,
            "unusedparams": true,
            "unusedwrite": true
        },
        "ui.diagnostic.annotations": {
            "bounds": true,
            "escape": true,
            "inline": true,
            "nil": true
        },
    },
```

### What did you see?
![image](https://user-images.githubusercontent.com/25056868/160248873-a8fe00ec-449c-44c1-ab1f-04773450208e.png)
![image](https://user-images.githubusercontent.com/25056868/160248959-dd21b6f4-7910-49e3-8548-f3af0c823858.png)

**Comment by fzipp** [comment]
Your `float64` is not what you think it is: https://go.dev/doc/faq#types_in_method_declaration
