### ISSUE TITLE
cmd/compile: In bits.Len(x|1), compiler doesn't realize argument is never zero

### ISSUE THREAD

**Issue by greatroar** [golang/go#51964]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 linux/amd64
$ gotip version
go version devel go1.19-ab0f7611d73 Mon Mar 14 09:19:01 2022 +0000 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH=amd64
GOAMD64=v2
```

### What did you do?

```
func len1(x uint64) int { return bits.Len64(x | 1) }
```

The expression bits.Len64(x|1) occurs in output from a protobuf compiler, where it calculates the size of a varint.

### What did you expect to see?

```
ORQ	$1, AX
BSRQ	AX, AX
INCQ	AX
RET
```

### What did you see instead?

```
ORQ	$1, AX
BSRQ	AX, CX
MOVQ	$-1, DX
CMOVQEQ	DX, CX
LEAQ    1(CX), AX
RET
```

It looks like this could be solved by extending the following rule to handle BSRQ:

https://github.com/golang/go/blob/0652274c10f8f2a520c30bf43bb968dac91bf9f5/src/cmd/compile/internal/ssa/gen/AMD64.rules#L2075-L2076

**Comment by renthraysk** [comment]
bits.Len32() still outputs unnecessary code for nonzero arguments. As it does x := uint64(arg)*2 + 1 to ensure a nonzero argument for BSFQ rather than use a conditional move after.
