### ISSUE TITLE
wasm: can't get stdout of go wasm in nodejs environment

### ISSUE THREAD

**Issue by hubvue** [golang/go#51975]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.18
</pre>
### Question
I am making a generic [gowasmer](https://github.com/hubvue/tools/tree/main/packages/go-wasmer) to load go wasm in browser and nodejs platform, but I have a problem with the go wasm example of [example's](https://github.com/golang/go/tree/master/misc/wasm), I can get the stdout of the go program by intercepting `console.log` in the browser environment, but I can't do it in the nodejs environment, is there any way to get the stdout of the go program in the nodejs environment to get the stdout of the go application?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
