### ISSUE TITLE
compile error when implementing an interface with a func named the same name as the interface

### ISSUE THREAD

**Issue by bmizerany** [golang/go#51973]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/bmizerany/Library/Caches/go-build"
GOENV="/Users/bmizerany/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/bmizerany/go/pkg/mod"
GONOPROXY="tier.run"
GONOSUMDB="tier.run"
GOOS="darwin"
GOPATH="/Users/bmizerany/go"
GOPRIVATE="tier.run"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.18/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.18/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/var/folders/rf/6fdgwbmj2rxf1jw13q4fv7h80000gn/T/tmp.3xXbUvwe/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rf/6fdgwbmj2rxf1jw13q4fv7h80000gn/T/go-build2703488555=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.18 darwin/arm64
GOROOT/bin/go tool compile -V: compile version go1.18
uname -v: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
lldb --version: lldb-1300.0.42.3
Swift version 5.5.2-dev
</pre></details>

### What did you do?

Wrote this:

```
package main

import "io"

type R struct {
        io.Reader
}

var _ io.Reader = R{}

type I interface {
        I()
}

type S struct {
        I
}

var _ I = S{}

func main() {}
```

### What did you expect to see?

The program to compile.

### What did you see instead?

```
tmp.3xXbUvwe % go build
# test
./x.go:19:11: cannot use S{} (value of type S) as type I in variable declaration:
	S does not implement I (missing I method)
```

If I rename `I()` to `F()` it compiles. Renaming `I` to `F` and leaving `I()` works too:

```
package main

import "io"

type R struct {
	io.Reader
}

var _ io.Reader = R{}

type F interface {
	I()
}

type S struct {
	F
}

var _ F = S{}

func main() {}
```

```
tmp.3xXbUvwe % go build
tmp.3xXbUvwe % echo $?
0
```

**Comment by seankhliao** [comment]
`S.I` here refers to the embedded variable of type `I` and the method is at S.I.I()`.
Closing as not a but

**Comment by bmizerany** [comment]
@seankhliao Ah! Thank you. Might it be possible to output a helpful warning in this case?
