### ISSUE TITLE
x/pkgsite: package removal request for github.com/gongxulei/gong

### ISSUE THREAD

**Issue by gongxulei** [golang/go#51985]
### What is the path of the package that you would like to have removed?
[github.com/gongxulei/gong](https://pkg.go.dev/github.com/gongxulei/gong@v0.0.0-20220127145151-000496133b7e)

 
 
 
### Are you the owner of this package?
Yes

 
### What is the reason that you could not retract this package instead?
I have already deleted the content from github

**Comment by jamalc** [comment]
Done.
