### ISSUE TITLE
cmd/compile: missing source information in ssa view

### ISSUE THREAD

**Issue by katsusan** [golang/go#51988]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="/usr/local/bin/gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build481024948=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

1. try following source:
```Golang

package main

func main() {
        r := min(1, 6)
        println(r)
}

func min[T int | int32 | int64](x, y T) T {
        if x < y {
                return x
        }
        return y
}
```
2. run `GOSSAFUNC='min[go.shape.int_0]' go tool compile z.go` and open the generated ssa.html.

### What did you expect to see?

The source of function `min` shown in *sources* column.

### What did you see instead?

![image](https://user-images.githubusercontent.com/11537821/160453492-6708b2e6-2027-4eb8-a3ce-23a1b0abc0cd.png)

### Possible reason

The typeschecker seems giving wrong endline info in `ir.Func`.
```
>>> info frame
Stack level 0, frame at 0xc000467a30:
 rip = 0xa6b5ef in cmd/compile/internal/ssagen.buildssa (/usr/local/go/src/cmd/compile/internal/ssagen/ssa.go:348); saved rip = 0xa6442c
 called by frame at 0xc000467af8
 source language unknown.
 Arglist at 0xc0004676b0, args: fn=0xc000445080, worker=0, ~r0=<optimized out>, ~r0=<optimized out>
 Locals at 0xc0004676b0, Previous frame's sp is 0xc000467a30
 Saved registers:
  rip at 0xc000467a28
>>> p fn.Nname.sym.Name
$26 = "min[go.shape.int_0]"
>>> p fn.Endlineno
$27 = {
  index = 0,
  lico = 0
}
```

**Comment by mdempsky** [comment]
> The typeschecker seems giving wrong endline info in ir.Func.

Thanks. Probably `(*genInst).genericSubst in noder/stencil.go just needs `newf.Endlineno = gf.Endlineno`.

**Comment by hopehook** [comment]
> > The typeschecker seems giving wrong endline info in ir.Func.
> 
> Thanks. Probably `(*genInst).genericSubst` in cmd/compile/internal/noder/stencil.go just needs `newf.Endlineno = gf.Endlineno`.

I did this and the result is as follows, func min outputs twice, not sure if it is necessary to deduplicate.

![image](https://user-images.githubusercontent.com/7326168/162420862-de564cbe-25cc-4007-bf10-621cbfaa4578.png)

**Comment by hopehook** [comment]
> > > The typeschecker seems giving wrong endline info in ir.Func.
> > 
> > 
> > Thanks. Probably `(*genInst).genericSubst` in cmd/compile/internal/noder/stencil.go just needs `newf.Endlineno = gf.Endlineno`.
> 
> I did this and the result is as follows, func min outputs twice, not sure if it is necessary to deduplicate.
> 
> * Read sources of target function fn.   `output once`
> * Read sources of inlined functions.   `output once`
> 
> ![image](https://user-images.githubusercontent.com/7326168/162420862-de564cbe-25cc-4007-bf10-621cbfaa4578.png)

@mdempsky Hi, Matthew Dempsky. Could you take a look at this question.

**Comment by mdempsky** [comment]
@hopehook Hi, sorry, I'm not familiar with that part of the compiler. I'm not sure why the debug view is listing the sources twice. Removing the duplication seems desirable to me, if you want to investigate why.

**Comment by hopehook** [comment]
@mdempsky Thank you very much. I don't know the exact reason, so I don't dare to change it here.
