### ISSUE TITLE
affected/package: error:  wsasend: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by wangyuanwenGit** [golang/go#51998]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.5 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=auto
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\Nelo\AppData\Local\go-build
set GOENV=C:\Users\Nelo\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=E:\Projects\GO\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\Projects\GO
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=E:\tools\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=E:\tools\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.5
set GCCGO=gccgo
set GO386=sse2
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Nelo\AppData\Local\Temp\go-build3291980313=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I have an http/https proxy server, which is used to request remote services, and then transparently transmit the results back to the client directly, and an error occurs when the client returns a large request.

error:
[ERROR]: io.Copy failed, code: 648720, msg: readfrom tcp 127.0.0.12:49152->127.0.0.1:54055: write tcp 127.0.0.12:49152->127.0.0.1:54055: wsasend: An existing connection was forcibly closed by the remote host.

`func DirectReplyHttp(w http.ResponseWriter, resp *http.Response) (int64, error) {
//w is the original client； resp is the final server
	  copyHeader(w.Header(), resp.Header)
	  w.WriteHeader(resp.StatusCode)
  
	  rc, err := io.Copy(w, resp.Body)
	  if err != nil {
                  //this code error
		  ErrorLog("io.Copy failed, code: %d, msg: %s", rc, err.Error())
		  return rc, err
	  }
  
	  AddFlowIncc(int64(rc))
	  DebugLog("resp: resp.StatusCode :%d, Content-Range: %s Direct copy peekResp, Len: %d", resp.StatusCode, resp.Header.Get("Content-Range"), rc)
  
	  return rc, nil
  }`

### What did you expect to see?
witout any error

### What did you see instead?
**[ERROR]: io.Copy failed, code: 648720, msg: readfrom tcp 127.0.0.12:49152->127.0.0.1:54055: write tcp 127.0.0.12:49152->127.0.0.1:54055: wsasend: An existing connection was forcibly closed by the remote host.**

**Comment by seankhliao** [comment]
the error says the remote end closed the connection. I don't think there's anything to do here.
