### ISSUE TITLE
go get: Use a specific SSH identity?

### ISSUE THREAD

**Issue by dzrw** [golang/go#51996]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

1.17

### Does this issue reproduce with the latest release?

I don't know.

### What operating system and processor architecture are you using (`go env`)?

Darwin, amd64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I created two GitHub profiles, profileA and profileB with SSH access and setup ssh/config (below) to configure how the `git` command cloned repos.  Combined with a gitconfig that redirects HTTPS to SSH, this allows me to determine which SSH identity is used with which repo and it works well.

However, although `go get "github.com/..."` will use profileA to request modules from private repositories, `go get "alt.github.com/..."` fails with an error (below).  The problem is obviously that go get is looking at the raw path to determine whether or not it's a special github link, and doesn't know how to resolve the true path through SSH config.  I'm sure there are good reasons that it works this way.

Yet, my problem remains. Is there any way to make `go get` use a different SSH identity?

<details><pre>
Host alt.github.com
	AddKeysToAgent yes
	UseKeychain yes
	Hostname github.com
	User git
	IdentityFile ~/.ssh/id_profileB

Host github.com
	AddKeysToAgent yes
	UseKeychain yes
        User git
	IdentityFile ~/.ssh/id_profileA
</pre></details>

### What did you expect to see?

I expected to be able to `go get` modules using the profileB SSH identity.

### What did you see instead?

An error: 

<details><pre>
go get: unrecognized import path "alt.github.com/golang/go": reading https://alt.github.com/golang/go?go-get=1: 404 Not Found
</pre></details>

**Comment by seankhliao** [comment]
The server has to respond to the https query to determine module roots/vcs system, your approach won't work.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
