### ISSUE TITLE
x/build/cmd/release: windows-amd64 release process is failing on tip due to unexpected stale targets after second build

### ISSUE THREAD

**Issue by dmitshur** [golang/go#52009]
As detected early by @heschi via work on #51797, Go 1.19 tip tree that will be used during the release process is not passing on the `windows/amd64` release target.

Bisection shows the problem starts with [CL 391809](https://go.dev/cl/391809) (CC @bcmills). Either there's a problem in that CL that is uncovered only during the sequence of steps the current release process performs (since it's not being caught by builders), or there's a problem with that [sequence](https://cs.opensource.google/go/x/build/+/master:cmd/release/release.go;l=646-662;drc=6ea17ddc88ca435004b2b12185c446455fa11a8f) which is only being uncovered by that change.

Its parent commit (d68615f64b0d7c1e886f4b8c1267ecc1c4da76ad) gets as far as API check successfully, but commit 0433f5770b9c92b06d5a15c8d2a70f00597faac4 fails early in the "Building (all.bash to ensure tests pass)" step with:

```
# (The release command uses builders to create a release artifact locally.
#  It does not publish anything, so it's safe to run for testing needs.)
$ release -target=windows-amd64 -version=go1.19alpha126 -watch -rev=0433f5770b9c92b06d5a15c8d2a70f00597faac4
[...]
2022/03/28 18:59:19 windows-amd64: Installing go1.4 (second time, for all.bash).
2022/03/28 18:59:22 windows-amd64: Building (all.bash to ensure tests pass).
Building Go cmd/dist using C:\workdir\go1.4
Building Go toolchain1 using C:\workdir\go1.4.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for windows/amd64.

HASH[build internal/goarch]
[...]
HASH[link cmd/dist]: bdb2e2909c821c8e0277ce92f8c75b485d05999d0d32e4da1e549e1b9d4dbfab
cmd/dist true
go tool dist: unexpected stale targets reported by go list -gcflags="" -ldflags="" for [std cmd] (consider rerunning with GOMAXPROCS=1 GODEBUG=gocachehash=1):
	STALE cmd/addr2line: build ID mismatch
	STALE cmd/api: build ID mismatch
	STALE cmd/asm: build ID mismatch
	STALE cmd/buildid: build ID mismatch
	STALE cmd/cgo: build ID mismatch
	STALE cmd/compile: build ID mismatch
	STALE cmd/cover: build ID mismatch
	STALE cmd/dist: build ID mismatch
	STALE cmd/doc: build ID mismatch
	STALE cmd/fix: build ID mismatch
	STALE cmd/go: build ID mismatch
	STALE cmd/gofmt: build ID mismatch
	STALE cmd/internal/metadata: build ID mismatch
	STALE cmd/link: build ID mismatch
	STALE cmd/nm: build ID mismatch
	STALE cmd/objdump: build ID mismatch
	STALE cmd/pack: build ID mismatch
	STALE cmd/pprof: build ID mismatch
	STALE cmd/test2json: build ID mismatch
	STALE cmd/trace: build ID mismatch
	STALE cmd/vet: build ID mismatch
```
(complete log https://gist.github.com/dmitshur/80444d6afa37edb6dcdc2f2979545762)

This test failure can be reproduced with [cmd/release](https://golang.org/x/build/cmd/release) (can only be done by someone with [gomote access](https://github.com/golang/build/tree/master/cmd/releasebot#permissions)).

CC @golang/release.

**Comment by bcmills** [comment]
As expected, running `make.bat` followed by `all.bat` on a raw builder does not reproduce this failure.

I suspect that it is something to do with the environment or args passed to the scripts. I'm adding some logging to `cmd/release` and re-running to try to suss that out.

**Comment by bcmills** [comment]
I did eventually reproduce this by setting `GO_BUILDER_NAME` before running `run.bat` on a gomote instance. (`cmd/dist`'s behavior changes based on whether it is running on a builder, because the builder is only supposed to run `run.bat` in a `GOROOT` that has already run `make.bat` and not been modified since.)
