### ISSUE TITLE
cmd/compile: Benchmarks ordering problem with generics

### ISSUE THREAD

**Issue by ogau** [golang/go#52002]
### What version of Go are you using (`go version`)?

<pre>
1.18
</pre>

### What did you do?

Benchmarks code: [https://go.dev/play/p/zNLHtksAcAS](https://go.dev/play/p/zNLHtksAcAS)
If we run the test twice in a different order of execution of benchmarks, we will get an interesting dependency.
All subsequent code after generics degrades performance.
```
goos: windows
goarch: amd64
cpu: AMD Ryzen 3 PRO 2200G with Radeon Vega Graphics
BenchmarkNativeMethod-4          4061136               307.5 ns/op
BenchmarkNativeMethod-4          3827776               305.0 ns/op
BenchmarkGenericMethod-4          379663              2719 ns/op
BenchmarkGenericMethod-4          385132              2723 ns/op
```

```
goos: windows
goarch: amd64
cpu: AMD Ryzen 3 PRO 2200G with Radeon Vega Graphics
BenchmarkGenericMethod-4          442808              2858 ns/op
BenchmarkGenericMethod-4          427164              2755 ns/op
BenchmarkNativeMethod-4          2047842               571.2 ns/op
BenchmarkNativeMethod-4          2036937               593.8 ns/op
```
With this flags, performance both generics and non-generics becomes around `~600ns  ns/op`
`go test -bench=. -count=2 -gcflags=all=-d=unified`

### What did you expect to see?

In general, I expected to see the same performance of both generic and non-generic code, but I was amazed by the behavior of the order of benchmarks.

###

**Comment by seankhliao** [comment]
On the difference between which one is placed first, I think that's just code alignment, `BenchmarkNativeMethod-4` is faster when it's placed after the generic version on my computer.

**Comment by cherrymui** [comment]
Yeah, could be code alignment. I don't see  the generated code has any difference when the order changes. Could you try a different machine? Thanks.
