### ISSUE TITLE
affected/package: found pointer to free object (go runtime)

### ISSUE THREAD

**Issue by sanjaynirankari** [golang/go#52008]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.15.10

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

We used workgroup here, we didn't pass workgroup to any function and it's crashing on waitgroup wait method. 

### What did you expect to see?

The program to start up normally on all hosts.

### What did you see instead?

  0xc001bf3c80 free  unmarked
  0xc001bf3e00 free  unmarked
  fatal error: found pointer to free object
  runtime stack:
  runtime.throw(0x30c2b91, 0x1c)
  /usr/local/go/src/runtime/panic.go:1116 +0x72
  runtime.(*mspan).reportZombies(0x7fc084366ab0)
  /usr/local/go/src/runtime/mgcsweep.go:827 +0x376
  runtime.(*mspan).sweep(0x7fc084366ab0, 0xc000601100, 0x1)
  /usr/local/go/src/runtime/mgcsweep.go:451 +0x81b
  runtime.(*mcentral).uncacheSpan(0x4d40598, 0x7fc084366ab0)
  /usr/local/go/src/runtime/mcentral.go:383 +0xec
  runtime.(*mcache).releaseAll(0x7fc0ad85a7d0)
  /usr/local/go/src/runtime/mcache.go:162 +0x6a
  runtime.(*mcache).prepareForSweep(0x7fc0ad85a7d0)
  /usr/local/go/src/runtime/mcache.go:189 +0x46
  runtime.acquirep(0xc00007e800)
  /usr/local/go/src/runtime/proc.go:4467 +0x3d
  runtime.stopm()
  /usr/local/go/src/runtime/proc.go:1926 +0xed
  runtime.gcstopm()
  /usr/local/go/src/runtime/proc.go:2142 +0xbc
  runtime.schedule()
  /usr/local/go/src/runtime/proc.go:2632 +0x47d
  runtime.goschedImpl(0xc000f91080)
  /usr/local/go/src/runtime/proc.go:2866 +0xda
  runtime.gopreempt_m(0xc000f91080)
  /usr/local/go/src/runtime/proc.go:2894 +0x34
  runtime.newstack()
  /usr/local/go/src/runtime/stack.go:1047 +0x1bc
  runtime.morestack()
  /usr/local/go/src/runtime/asm_amd64.s:449 +0x8f
  goroutine 1 [semacquire, 630 minutes]:
  sync.runtime_Semacquire(0xc0007bd238)
  /usr/local/go/src/runtime/sema.go:56 +0x45
  sync.(*WaitGroup).Wait(0xc0007bd230)
  /usr/local/go/src/sync/waitgroup.go:130 +0x65

**Comment by seankhliao** [comment]
We no longer support 1.15, sorry.
