### ISSUE TITLE
access: TryBots (aktau@)

### ISSUE THREAD

**Issue by aktau** [golang/go#52012]
I've started contributing some small CLs (e.g.: https://go-review.googlesource.com/c/go/+/395679) and it would be useful to smoothen the release process if I could start TryBots on a change.

Group:  https://go-review.googlesource.com/#/admin/groups/1030,members

cc @dmitshur

**Comment by dmitshur** [comment]
Thanks for making this request.

We've discussed it during a @golang/release team meeting today and agreed to grant this access. It's done now.

Please refer to https://go.dev/wiki/GerritAccess#running-trybots-may-start-trybots for information related to TryBots.
