### ISSUE TITLE
x/sys/unix: TestPidfd fails on GOARCH mips builders

### ISSUE THREAD

**Issue by mdlayher** [golang/go#52014]
I implemented `unix.Waitid` in https://go-review.googlesource.com/c/sys/+/395936/, and @tklauser commented:

> This CL seems to break the mips64-rtk, mips64le-rtk and mipsle-rtk builders:
```
 --- FAIL: TestPidfd (0.00s)
    syscall_linux_test.go:243: failed to check for child exit: invalid argument
FAIL
FAIL	[golang.org/x/sys/unix](http://golang.org/x/sys/unix)	0.684s
```

> https://build.golang.org/log/405cfcebea4c1b0f00de4d988c2b1baf527b8008
> https://build.golang.org/log/c2446e254921d971f655b00c86d5cb3aa2957e1a
> https://build.golang.org/log/650f8e0343be7531952a38c71957f33ee6272e66
>
> Maybe kernel version is too old on these builders?

For now, I will add a skip on EINVAL in this test.

/cc @tklauser @ianlancetaylor

**Comment by mdlayher** [comment]
Ping @bogojevic @milanknezevic and @mengzhuo as the owners of these builders.

**Comment by mengzhuo** [comment]
`linux-mipsle-mengzhuo` runs on 5.4.110 is it affected?

**Comment by draganmladjenovic** [comment]
@mdlayher It looks like pidfd_open is introduced during 5.3 and waitid with P_PIDFD is introduced in 5.4. These machines are at 5.3.3*.

**Comment by mdlayher** [comment]
Any chance these builders could be bumped to 5.10.x LTS? I believe that'd solve the immediate problem.

I don't have any context on mips or the builders, I'm just reporting what Tobias told me above. See logs.

**Comment by draganmladjenovic** [comment]
Not in the meantime. Not sure if there is another pidfd* syscall that can be easily used to construct the test instead of waitid.

**Comment by mdlayher** [comment]
The test can stay skipped for now, no problem. Thanks.
