### ISSUE TITLE
x/build/cmd/gopherbot: closeStaleWaitingForInfo fails to close issues

### ISSUE THREAD

**Issue by hyangah** [golang/go#52017]
We are trying to understand why gopherbot is not closing old stale issues
For example vscode-go issue 2020 (note: I intentionally avoid linking to the issue)
which was labeled with "WaitingForInfo" multiple months ago. 

I tested gopherbot with `go run gopherbot.go --dry-run=true --only-run="close stale WaitingForInfo"`  and observed:

When [`closeStaleWaitingForInfo`](https://cs.opensource.google/go/x/build/+/master:cmd/gopherbot/gopherbot.go;l=1155) handles the mentioned issue (vscode-go 2020), the `gi` `(maintner.GitHubIssue`) does not have any entry in its `events` field. As a result,  the callback set for [`gi.ForeachEvent`](https://cs.opensource.google/go/x/build/+/master:cmd/gopherbot/gopherbot.go;l=1171-1185) never runs, and the issue is never considered as stale one. 

![Screen Shot 2022-03-29 at 2 29 32 PM](https://user-images.githubusercontent.com/4999471/160680589-4eb7d859-4e1c-4692-a6b4-103df3c1c116.png)
 
I am not familiar with maintner nor gopherbot, and am not sure if this is a bug in maintner code, or an incomplete log somewhere.
Not only this issue, I also observed some issues have incorrect states - for example, `Closed` field is not set for closed issue, etc. 

Help with inspecting maintner is greatly appreciated.
 
ps. Why don't we move some of issue gardening automation (like closing stale issues) to github actions?

**Comment by dmitshur** [comment]
The change helped, and vscode-go issue 2020 (among many others in the vscode-go issue tracker) has now been correctly closed by gopherbot by the `closeStaleWaitingForInfo` task. Please let us know if you spot something unexpected.

I'll close this issue as fixed, and issues #40640 and #37370 are still open to track what still remains to fully handle transferred issues.

Thanks for the detailed report.
