### ISSUE TITLE
cmd/compile: generic function appears to use incorrect type descriptor

### ISSUE THREAD

**Issue by QuantumGhost** [golang/go#52026]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOOS="darwin"
GOPROXY="https://goproxy.io,https://mirrors.aliyun.com/goproxy/"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yv/fd8s2yw54cldnj29jx3qxrh80000gn/T/go-build4280234465=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

[Go 2 Playground Link](https://gotipplay.golang.org/p/Y_7IzmPpk5I)

### What did you expect to see?

Type assertion to `None` returns `true`.
Type Switch prints `s is a None`.

### What did you see instead?

Type assertion to `None` returned `false`.
Type Switch prints `oops`.

**Comment by ianlancetaylor** [comment]
CC @randall77 @mdempsky

**Comment by kraleva** [comment]
Since you are returning a generic type from your returnOption function, go would expect None to be generic as well. If you do change it to None[T], it seems to work for me :) At least that is a possible solution to the problem.

**Comment by go101** [comment]
It is really a bug.

It looks the problem is gone if the line `s = returnOption[int](0)` is changed to `s = returnOption[string](0)`.

**Comment by ii64** [comment]
https://gotipplay.golang.org/p/p-xVGVKSW10
```go
switch (any)(s).(type) {
```

**Comment by randall77** [comment]
@gopherbot please open a backport issue for 1.18.
