### ISSUE TITLE
x/tools/gopls: semantic tokens for channel arrows are missing

### ISSUE THREAD

**Issue by hyangah** [golang/go#52024]
Spin off from https://github.com/golang/vscode-go/issues/2146#issuecomment-1081916769

![Screen Shot 2022-03-29 at 10 02 38 AM](https://user-images.githubusercontent.com/4999471/160629096-26649266-ecc1-4bfd-b888-ed9fd9b7beee.png)

Arrows (`<-`) don't get semantic token info, so only textmate scopes are applied. (see the screenshot - I enabled the semantic token feature).

![Screen Shot 2022-03-29 at 10 04 38 AM](https://user-images.githubusercontent.com/4999471/160629564-e3f81213-0352-42f0-8041-0667df447aea.png)

gopls version v0.8.1
go version go1.18

cc @pjweinb

**Comment by pjweinb** [comment]
[397479](https://go-review.googlesource.com/c/tools/+/397479) fixed this
