### ISSUE TITLE
access: may-start-trybots

### ISSUE THREAD

**Issue by wdvxdr1123** [golang/go#52033]
See https://go.dev/wiki/GithubAccess

Hi! I've started to contribute to go compiler, it would be very helpful if I can start trybots to check the changes. Thanks.

Group: https://go-review.googlesource.com/#/admin/groups/1030,members
Gerrit User: https://go-review.googlesource.com/q/owner:wdvxdr%2540golangcn.org
Email: wdvxdr@golangcn.org

cc @golang/release @dmitshur

**Comment by cherrymui** [comment]
Hi Wayne,

Thank you for your contributions and for requesting Trybots access! I've added you to the may-start-trybots group, so you should be able to do so now.

As you've likely read at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a Trybot run.

Let us know if you have any questions or issues with it, and thanks again!
