### ISSUE TITLE
net/http: TestServerConnState failures missing second `active` state after TLS handshake errors

### ISSUE THREAD

**Issue by bcmills** [golang/go#52049]
```
2022/03/30 05:35:07 http: TLS handshake error from 127.0.0.1:14164: EOF
2022/03/30 05:35:07 http: TLS handshake error from 127.0.0.1:33976: EOF
2022/03/30 05:35:07 http: TLS handshake error from 127.0.0.1:18644: EOF
--- FAIL: TestServerConnState (0.17s)
    serve_test.go:4199: unexpected conn in state new
    serve_test.go:4199: unexpected conn in state active
    serve_test.go:4199: unexpected conn in state closed
    serve_test.go:4241: Request(s) produced unexpected state sequence.
        Got:  [new active idle closed]
        Want: [new active idle active closed]
FAIL
FAIL	net/http	42.044s
```

`greplogs --dashboard -md -l -e 'FAIL: TestServerConnState .*(\n    .*)*Got:\s+\[new active idle closed\]'`

[2022-03-29T17:21:21-f71daa6/openbsd-arm64-jsing](https://build.golang.org/log/4fb895cbce4c466a652dbd0cccb6ddd9707872ef)
[2022-01-19T20:54:49-1efc581/plan9-arm](https://build.golang.org/log/7ac460af3f6f6e041b092295661f4dd1ed2aeea8)
[2021-11-17T19:50:58-88474d4/openbsd-386-68](https://build.golang.org/log/05f51713bb7e4d70572607aa3c6cfb4b3838476c)

(CC @neild)

**Comment by prattmic** [comment]
Most (but not all) of the failures in #56577 are this failure mode. Should we dupe this into that bug?

**Comment by bcmills** [comment]
Yep, that seems fine.

**Comment by bcmills** [comment]
Duplicate of #56577
