### ISSUE TITLE
affected/package: Type Parameters

### ISSUE THREAD

**Issue by bilaleluneis** [golang/go#52042]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/bilaleluneis/Library/Caches/go-build"
GOENV="/Users/bilaleluneis/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Applications/go-sdk/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Applications/go-sdk/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/bilaleluneis/Developer/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/bilaleluneis/Developer/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fg/frvgdhsj07z2dnj0gkfw0qr00000gn/T/go-build4255747838=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

package main

// constraint interfaces
type collection[T any] interface {
	push(T)
	pop() (T, error)
}

type indexable[C collection[T], T any] interface {
	at(int) (T, error)
}

// valid collection and indexable
type list[T any] struct {}
func(l *list[T]) push(_ T){}
func(l *list[T]) pop() (T, error) {
	var p T
	return p, nil
}
func(l *list[T]) at(_ int) (T, error) {
	return l.pop()
}

// this should not compile, as invalid doesnt implement collection and indexable is constrained to a collection type
type invalid[T any] struct{}
func (i *invalid[T]) at(_ int) (T, error) {
	var p T
	return p, nil
}

func main() {}

### What did you expect to see?
expected compilation error stating that struct "invalid[T any]" does not implement collection interface and so at(int) will fail to compile because it expects a collection as constraint

### What did you see instead?
successful compilation with no errors

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
