### ISSUE TITLE
x/net/http2: TestUnreadFlowControlReturned_Server failures due to INTERNAL_ERROR since 2022-03-15

### ISSUE THREAD

**Issue by bcmills** [golang/go#52051]
```
--- FAIL: TestUnreadFlowControlReturned_Server (16.39s)
    --- FAIL: TestUnreadFlowControlReturned_Server/body-closed (14.15s)
        server_test.go:3844: body-closed timedout
        server_test.go:3868: body-closed stream error: stream ID 5; INTERNAL_ERROR; received from peer
FAIL
FAIL	golang.org/x/net/http2	184.809s
```

`greplogs --dashboard -md -l -e 'FAIL: TestUnreadFlowControlReturned_.*' --since=2022-01-01`

[2022-03-30T02:16:17-de3da57-d1060d8/plan9-386-0intro](https://build.golang.org/log/64cdec817674cce288c0c5b13d5309baaefdcd74)
[2022-03-25T01:24:44-27dd868-8ab42a9/plan9-386-0intro](https://build.golang.org/log/3671c250dd0cea8dd8de197f26641af86282accf)
[2022-03-18T19:32:40-27dd868-a682a5c/plan9-386-0intro](https://build.golang.org/log/666994403b88c738695dac36b55ce967a12f5b18)
[2022-03-18T16:57:07-27dd868-0a49f70/plan9-386-0intro](https://build.golang.org/log/1a81ef4d76665a89bdc5eddd5a444c002d8ba1a7)
[2022-03-15T01:00:36-27dd868-44a0da4/plan9-386-0intro](https://build.golang.org/log/592c54d66100b2245e46fa21101c4deefc316443)

(attn @0intro; CC @neild)

See previously #49645.

**Comment by dmitshur** [comment]
This has also happened on a `netbsd/arm64` builder recently:

https://build.golang.org/log/ebd81abf53025263ed94ef3462193b7efc319315

This is the only open bug for this problem I'm finding. @bcmills Do you think it's better to expand the scope of this one to be non-Plan9 specific or file a separate tracking one for `netbsd/arm64`?

**Comment by bcmills** [comment]
The output in the test log looks exactly the sam to me, so I'd be inclined to expand the scope. The fact that there are no GOOS or GOARCH elements in common suggests that this is a platform-independent bug (quite possibly timing related).

**Comment by bcmills** [comment]
Yep, here's the problem: another arbitrary timeout. Should be a trivial fix, so I'll go ahead and mail it.

https://cs.opensource.google/go/x/net/+/master:http2/server_test.go;l=3828-3829;drc=c960675eff93b7ce235fa4b1578d83fa48ea129c

**Comment by bcmills** [comment]
Moving to the Go 1.19 milestone since `x/net/http2` is bundled into the main repo — especially given that it's a test-only fix and has a pending CL.

**Comment by dmitshur** [comment]
> `x/net/http2` is bundled into the main repo [...] test-only fix

I think Go1.19 milestone is fine, just note that only the http2 package code is bundled into the standard library and not its tests, so nothing in the main repo will change when the next dependency update is performed.
