### ISSUE TITLE
mime: mime.ExtensionsByType returns an unexpected extension ",v" for "text/plain"

### ISSUE THREAD

**Issue by PetitCassoulet** [golang/go#52065]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/me/.cache/go-build"
GOENV="/home/me/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/me/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/me/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/me/project/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build697837538=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
package main

import (
	"fmt"
	"mime"
)

func main() {
	val, err := mime.ExtensionsByType("text/plain")
	if err != nil {
		panic(err)
	}

	fmt.Printf("%+v", val)
}
</pre>

### What did you expect to see?
Definitely not `,v` as a valid extension

### What did you see instead?
`[,v .asc .inf .ini .txt]`

**Comment by jimen0** [comment]
Hi @PetitCassoulet - Per the docs, on Linux following files are checked for the mime types database:

```text
/usr/local/share/mime/globs2
/usr/share/mime/globs2
/etc/mime.types
/etc/apache2/mime.types
```

Source: https://cs.opensource.google/go/go/+/refs/tags/go1.18:src/mime/type_unix.go;l=19-32

Maybe one of these is corrupted in your system? I get the correct output both with 1.17 and current tip on a macos system.

Thanks!

**Comment by seankhliao** [comment]
As noted above, mime types are provided by the underlying system, and it looks like this was an intentional addition by OS maintainers: https://unix.stackexchange.com/questions/666614/reason-for-text-plain-pattern-v-in-shared-mime-info

Closing as there's nothing to do in Go.
