### ISSUE TITLE
strconv: treat \x7f like the rest of ASCII when quoting

### ISSUE THREAD

**Issue by robpike** [golang/go#52062]
See https://go.dev/play/p/F4GlQBQL7UC

As mentioned in [https://groups.google.com/d/msgid/golang-nuts/60ad41f0-10d6-417d-a604-6a151c357d93n%40googlegroups.com](https://groups.google.com/d/msgid/golang-nuts/60ad41f0-10d6-417d-a604-6a151c357d93n%40googlegroups.com) (which started a decade ago, almost)
, the 0x7f byte prints with \u not \x. That isn't incorrect, but it is inconsistent.

If it's worth fixing, it's a one-liner in strconv.appendEscapedRune

I vote for fixing it, although it could break some things. It trips over just what ASCII means, and to be honest \x7f is the ASCII rubout or del character.

**Comment by peterGo** [comment]
The Unicode Standard classifies 007F as a C0 Control Character. The other C0 Control Characters print as \x, 007F should print as \x.

Unicode Standard   
http://www.unicode.org/versions/latest/   

C0 Controls and Basic Latin    
Range: 0000–007F   
https://unicode.org/charts/PDF/U0000.pdf   

Control character 007F  = DELETE

**Comment by zamicol** [comment]
I wrote a larger test that prints the extended range.  Everything is as I would expect except for \x7F.

https://go.dev/play/p/j_Mm9O98hnz
