### ISSUE TITLE
cmd/compile: devirtualization changes program behavior

### ISSUE THREAD

**Issue by go101** [golang/go#52072]
Moved from https://github.com/golang/go/issues/38634#issuecomment-1084040645.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 linux/amd64
</pre>

It looks this problem started from Go 1.16.

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```Go
package main

type I interface{ M() }

type T struct{}

func (T) M() {}

var pt *T

func f() (r int) {
	defer func(){recover()}()

	var i I = pt
	defer i.M()
	r = 1
	return
}

func g()(r int) {
	defer func(){recover()}()

	var i I = pt
	f := i.M
	defer f()
	r = 1
	return
}

func main() {
	println(f()) // 0
	println(g()) // 1
}
```

[edit]: another example:

```Go
package main

type I interface{ M() }

type T struct{
	x int
}

func (t T) M() {
	println(t.x)
}

func f() {
	var t = &T{1}
	var i I = t
	defer i.M()
	t.x = 2
	return
}

func g() {
	var t = &T{1}
	var i I = t
	f := i.M
	defer f()
	t.x = 2
	return
}

func main() {
	f() // 1
	g() // 2
}
```

### What did you expect to see?

Same return results.

### What did you see instead?

Different results.

Changing the `i` variable to global makes this inconsistency gone.

**Comment by cuonglm** [comment]
In `f`, `i.M` can be devirtualized to `*T`, while in `g`, it does not. So `defer i.M()` becomes `defer pt.M()`, and `pt` is evaluated as nil pointer dereference.

Changing `i` to a global variable make it can not be devirtualized in both cases.

**Comment by zitudu** [comment]
It obeys the Go Specification of [Defer statements](https://go.dev/ref/spec#Defer_statements) and [Selectors](https://go.dev/ref/spec#Selectors).

For `defer i.M()` in f, `i` is nil, and panic immediately.

> If a deferred function value evaluates to nil, execution [panics](https://go.dev/ref/spec#Handling_panics) when the function is invoked, not when the "defer" statement is executed.

`g` uses the selector and gets the `(*T).M` method, then defer calls the method and results in run-time panic.

> 2. For a value x of type I where I is an interface type, x.f denotes the actual method with name f of the dynamic value of x. If there is no method with name f in the [method set](https://go.dev/ref/spec#Method_sets) of I, the selector expression is illegal.

> 6. If x is of interface type and has the value nil, [calling](https://go.dev/ref/spec#Calls) or [evaluating](https://go.dev/ref/spec#Method_values) the method x.f causes a [run-time panic](https://go.dev/ref/spec#Run_time_panics).

**Comment by go101** [comment]
> If a deferred function value evaluates to nil, execution [panics](https://go.dev/ref/spec#Handling_panics) when the function is invoked, not when the "defer" statement is executed.

So the `r = 1` statement should be executed by the spec, right?

**Comment by zitudu** [comment]
> > If a deferred function value evaluates to nil, execution [panics](https://go.dev/ref/spec#Handling_panics) when the function is invoked, not when the "defer" statement is executed.
> 
> So the `r = 1` statement in `f` should be executed by the spec, right?

You're right... I went back and read the specs carefully. I think it should be like this: 

when defer is executed, it will first calculate the function address and parameters (if any), and then invoke the function before returns. The problem is that nil is encountered when getting the function address.

Defer:
> Each time a "defer" statement executes, the function value and parameters to the call are [evaluated as usual](https://go.dev/ref/spec#Calls) and saved anew but the actual function is not invoked. Instead, deferred functions are invoked immediately before the surrounding function returns, in the reverse order they were deferred. That is, if the surrounding function returns through an explicit [return statement](https://go.dev/ref/spec#Return_statements), deferred functions are executed after any result parameters are set by that return statement but before the function returns to its caller. If a deferred function value evaluates to nil, execution [panics](https://go.dev/ref/spec#Handling_panics) when the function is invoked, not when the "defer" statement is executed.

Calls:
> A method call x.m() is valid if the [method set](https://go.dev/ref/spec#Method_sets) of (the type of) x contains m and the argument list can be assigned to the parameter list of m. If x is [addressable](https://go.dev/ref/spec#Address_operators) and &x's method set contains m, x.m() is shorthand for (&x).m()

**Comment by go101** [comment]
For the first example shown above, the outputs are `2 2` with gccgo.
Personally, I think gccgo is right here, for it is self-consistent.

But the outputs of the following program is `2 1` for gccgo and `1 1` for gc.
I don't know who is right here.

@ianlancetaylor @griesemer  

```Go
package main

type I interface{ M() }

type T struct{
	x int
}

func (t T) M() {
	println(t.x)
}

func f() {
	var t = &T{1}
	var i I = t
	defer i.M()
	t.x = 2
	return
}

func g() {
	var t = &T{1}
	var i I = t
	f := i.M
	defer f()
	i = &T{2}
	return
}

func main() {
	f()
	g()
}
```

**Comment by cuonglm** [comment]
@mdempsky maybe we should not devirtualize if there's deref op? Or if there's a deref op, rewrite it to:

```
dt := i.(*T)
if dt == nil {
    defer i.M()
else {
    defer (*dt).M()
}
```

**Comment by mdempsky** [comment]
I'm under the impression this only affects `defer` and `go` statements. Is that the case?

If so, I'm fine just not devirtualizing defer/go calls at all.
