### ISSUE TITLE
net/url: JoinPath() drops trailing slashes

### ISSUE THREAD

**Issue by drigz** [golang/go#52074]
### What version of Go are you using (`go version`)?

dev branch (playground)

### Does this issue reproduce with the latest release?

No, url.JoinPath() is not in Go 1.18.

### What operating system and processor architecture are you using (`go env`)?

dev branch (playground)

### What did you do?

https://go.dev/play/p/xCJcVPN5pPh?v=gotip

```
func main() {
	fmt.Println(url.JoinPath("http://host/foo", "bar/"))
}
```

### What did you expect to see?

The trailing slash should be preserved: `http://host/foo/bar/`

### What did you see instead?

The trailing slash is lost: `http://host/foo/bar`

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport to 1.18

This function is new in 1.18 so we should keep it consistent with this change.

**Comment by carlmjohnson** [comment]
The function is slated for 1.19. It missed 18.

**Comment by ianlancetaylor** [comment]
Whoops.  Thanks.

**Comment by carlmjohnson** [comment]
What should url.JoinPath do in these cases:

```go
url.JoinPath("https://example.com/a//")
url.JoinPath("https://example.com/a//", "")
```

I think the output should be "https://example.com/a//" and "https://example.com/a/" but I can be argued into thinking otherwise.

**Comment by ianlancetaylor** [comment]
Personally I think it's OK if `JoinPath` drops extra trailing slashes.  I guess it should be documented, though.
