### ISSUE TITLE
runtime/race: upstream OpenBSD support is removed

### ISSUE THREAD

**Issue by cherrymui** [golang/go#52090]
LLVM TSAN removed OpenBSD support ( https://reviews.llvm.org/rG53065c543fe3f1e7913c9e8f2487d76034afa249 )
What do we do for the race detector on OpenBSD? Do we want to remove it, or try to add it back to LLVM?

cc @dvyukov @4a6f656c @golang/runtime

**Comment by beoran** [comment]
Why was it even dropped? It is not very clear from the issue above.

**Comment by qbit** [comment]
I added the initial bits for llvm. No clue why they added it - I will ask.

My pref is to keep it enabled in Go if at all possible. I use the feature pretty regularly.

**Comment by randall77** [comment]
For now we can just not update TSAN on openbsd. The updates we want to do are mostly performance, so it is ok if it isn't available everywhere (the 8192 goroutine limit might be annoying if it is gone everywhere else, though).

Longer term that isn't a solution, though. At some point we'd have to either fix openbsd support or drop the openbsd race detector.

**Comment by dvyukov** [comment]
Honestly, I don't know what happened. But it was removed from everywhere, not just tsan.
It seems that the simplest option is not update OpenBSD runtime.

**Comment by ianlancetaylor** [comment]
I don't think there is anything we can do here, other than carry forward the old OpenBSD race support, so closing this issue.
