### ISSUE TITLE
x/build/cmd/racebuild: OOM on linux-ppc64le-buildlet builder

### ISSUE THREAD

**Issue by cherrymui** [golang/go#52105]
I tried to update the race detector syso files, using the racebuild command. The script OOMs consistently on linux-ppc64le-buildlet builder. It seems the OOMing happens at the step when checking out the LLVM repository to /workdir. The repository is rather big.

/workdir is tmpfs. A workaround is to check out the repository to disk, e.g. /tmp, which seems to work.

Or maybe we want to somehow increase the memory of the PPC64 builders (see also #49957).

**Comment by dmitshur** [comment]
From a brief look, the host type of `linux-ppc64le-buildlet` is `host-linux-ppc64le-osu`, described as:

> Debian Buster; run by Go team on osuosl.org; see x/build/env/linux-ppc64le/osuosl

For increasing the memory, we might need the involvement of the Go team at osuosl.org. The workaround seems reasonable to me.
