### ISSUE TITLE
go build with -trimpath on arm mac produces other results than on amd64

### ISSUE THREAD

**Issue by markussiebert** [golang/go#52107]
### What version of Go are you using (`go version`)?

1.18

### Does this issue reproduce with the latest release?

yes - with all releases I tried

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/markussiebert/Library/Caches/go-build"
GOENV="/Users/markussiebert/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/markussiebert/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/markussiebert/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1c/hwkzhxjs6v18m_zgp7_mtzyc0000gn/T/go-build577411362=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
```bash
#!/bin/bash
echo "GOROOT: $GOROOT / GOPATH: $GOPATH"
BASEPATH=$(git rev-parse --show-toplevel)
cd "$BASEPATH/lambda"
GOOS=linux
GOARCH=amd64
GOPROXY=https://proxy.golang.org,direct
go mod tidy
go build -trimpath -ldflags="-s -w -buildid="
ls -la cdk-sops-secrets
touch -t 202002020000 cdk-sops-secrets
```
### What did you expect to see?
Identical results on all platforms

### What did you see instead?
I build my project local and in github actions - and the builds on github are a littlebit smaller and have other shasums. If I build them in the same docker image (also amd64, not arm64) on my m1 mac, they are identical. But building them native on my mac without docker produces other results but is a lot faster.

**Comment by cherrymui** [comment]
Does your program use cgo? Have you tried setting CGO_ENABLED=0?

**Comment by markussiebert** [comment]
yes - I tried with CGO_ENABLED=0 and 1 ... no success

**Comment by cherrymui** [comment]
Are they having identical version of Go? Could you share the exact commands you run? Could you show which section(s) have different size (e.g. by comparing the output of  `objdump -h`)? Thanks.

I'm not sure we guarantee to produce identical binaries from different machines/environments. But maybe there is something we can do to help.

**Comment by markussiebert** [comment]
Hi, thank you for your answer.

So I build the lambda this way on my m1 mac and with github actions in the  golang:1.18.0-buster image:

```bash
#!/bin/bash
echo "GOROOT: $GOROOT / GOPATH: $GOPATH"
BASEPATH=$(git rev-parse --show-toplevel)
cd "$BASEPATH/lambda"
GOOS=linux
GOARCH=amd64
GOPROXY=https://proxy.golang.org,direct
go build -trimpath -buildvcs=false -ldflags="-s -w -buildid="
ls -la cdk-sops-secrets
shasum cdk-sops-secrets
touch -t 202002020000 cdk-sops-secrets
chmod 755 cdk-sops-secrets
ls -la cdk-sops-secrets
shasum cdk-sops-secrets
```

This produces this on my arm mac:

❯ objdump -h lambda/cdk-sops-secrets

lambda/cdk-sops-secrets:        file format mach-o arm64

Sections:
Idx Name            Size     VMA              Type
  0 __text          00851f80 0000000100001000 TEXT
  1 __symbol_stub1  000006c0 0000000100852f80 TEXT
  2 __rodata        002ac088 0000000100853640 DATA
  3 __rodata        0028db78 0000000100b00000 DATA
  4 __typelink      00007344 0000000100d8db80 DATA
  5 __itablink      00001ed0 0000000100d94ee0 DATA
  6 __gosymtab      00000000 0000000100d96db0 DATA
  7 __gopclntab     0052b070 0000000100d96dc0 DATA
  8 __go_buildinfo  000019b0 00000001012c4000 DATA
  9 __nl_symbol_ptr 00000490 00000001012c59b0 DATA
 10 __noptrdata     0004cb78 00000001012c5e40 DATA
 11 __data          00016d10 00000001013129c0 DATA
 12 __bss           00034ce0 00000001013296e0 BSS
 13 __noptrbss      0000fc10 000000010135e3c0 BSS

and

**Comment by markussiebert** [comment]
hmm ... looks strange to me

**Comment by seankhliao** [comment]
You're building binaries for 2 different OS/architectures.
```
GOOS=linux
GOARCH=amd64
GOPROXY=https://proxy.golang.org,direct
```
only sets it for the line it is on, not subsequent lines.
Also, disable CGo.

**Comment by markussiebert** [comment]
holy moly - if you do it right, it works ???

```bash
#!/bin/bash
echo "GOROOT: $GOROOT / GOPATH: $GOPATH"
BASEPATH=$(git rev-parse --show-toplevel)
cd "$BASEPATH/lambda"
export GOOS=linux 
export GOARCH=amd64
export GOPROXY=https://proxy.golang.org,direct
export CGO_ENABLED=0
go build -trimpath -buildvcs=false -ldflags="-s -w -buildid="
ls -la cdk-sops-secrets
shasum cdk-sops-secrets
touch -t 202002020000 cdk-sops-secrets
chmod 755 cdk-sops-secrets
ls -la cdk-sops-secrets
shasum cdk-sops-secrets
```

```bash
❯ shasum lambda/cdk-sops-secrets
6f98461025ba7ebf0660b3295db884b1660604fb  lambda/cdk-sops-secrets
❯ shasum assets/cdk-sops-secrets
6f98461025ba7ebf0660b3295db884b1660604fb  assets/cdk-sops-secrets
```

![image](https://user-images.githubusercontent.com/16692560/162613171-c540e565-f5df-4b24-92ee-fbb5458ebc6d.png)

Thank you a lot!

**Comment by seankhliao** [comment]
Closing as there is no bug.
