### ISSUE TITLE
proposal: Go 2: 

### ISSUE THREAD

**Issue by carr123** [golang/go#52115]
hello, does Go generics support using constant values as params ?

in C++

template<class TT,TT init>
class class2
{
public:
        TT data;
        class2()
        {
             data = init;
        }     
};

class2<int,100> col;

the "100" is the constant value as template param

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
