### ISSUE TITLE
cmd/compile: slice constraints prevent indexing

### ISSUE THREAD

**Issue by jfcg** [golang/go#52129]
### What version of Go are you using (`go version`)?
1.18

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
Linux Amd64

### What did you do?
Tried to `go build`:
```go
func presort1[Slice ~[]int | ~[]uint](slc Slice) {
	l, h := 0, 10
	for h < len(slc) {
		if slc[h] < slc[l] {
			slc[h], slc[l] = slc[l], slc[h]
		}
		l++
		h++
	}
}

type MyInt int
type MySlice []MyInt

func presort2(slc MySlice) {
	l, h := 0, 10
	for h < len(slc) {
		if slc[h] < slc[l] {
			slc[h], slc[l] = slc[l], slc[h]
		}
		l++
		h++
	}
}
```
### What did you expect to see?
No errors.

### What did you see instead?
`presort1` does not compile with error
```
invalid operation: cannot index slc (variable of type Slice constrained by ~[]int|~[]uint)
```
`presort2` is fine

**Comment by rittneje** [comment]
As a workaround, this works:
```go
func presort1[T ~int | ~uint](slc []T) {
	l, h := 0, 10
	for h < len(slc) {
		if slc[h] < slc[l] {
			slc[h], slc[l] = slc[l], slc[h]
		}
		l++
		h++
	}
}
```

**Comment by jfcg** [comment]
That has a narrower scope, cannot accept MySlice for example

**Comment by rittneje** [comment]
No, that still works. https://go.dev/play/p/h3nx0geBIRf

**Comment by go101** [comment]
There is a principle rule: the type of a value must be a specified type, which might be either an ordinary type or a type parameter. In the first comment, `slc[h]` and `slc[l]` both might be `int` or `uint`, which breaks this rule.

**Comment by ianlancetaylor** [comment]
This is expected according to the current spec.  We may change it some day, but not soon.  Closing.
