### ISSUE TITLE
cmd/go: fuzzing doesn't work with environment startup

### ISSUE THREAD

**Issue by Ferrany1** [golang/go#52133]
### What version of Go are you using (`go version`)?

`go version go1.18 darwin/amd64`

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
```

### What did you do?

Running fuzz test with environment (containers with https://github.com/testcontainers/testcontainers-go and services in runtime) to test api routes

```
//go:build fuzzing

package main

import (
	"bytes"
	"context"
	"net/http"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
)

func FuzzFoo(f *testing.F) {
	initEnvironment(f)
	f.Add("first")
	f.Fuzz(
		func(t *testing.T, tenant string) {
			t.Run("testFoo", func(t *testing.T) { testFoo(t, tenant) })
		},
	)
}

func initEnvironment(tb testing.TB) {
	ctx := context.Background()
	_, err := testcontainers.GenericNetwork(
		ctx,
		testcontainers.GenericNetworkRequest{
			NetworkRequest: testcontainers.NetworkRequest{
				Name:        "test_fuzz",
				ReaperImage: testcontainers.ReaperDefaultImage,
			},
		},
	)
	require.NoError(tb, err)

	containerRequest := testcontainers.ContainerRequest{
		Name:  "cocroach-fuzz",
		Image: "cockroachdb/cockroach:v21.1.11",
		Cmd:   []string{"start-single-node", "--insecure"},
		ExposedPorts: []string{
			"127.0.0.1:26257:26257/tcp",
			"127.0.0.1:8080:8080/tcp",
		},
		WaitingFor:  wait.ForListeningPort("26257/tcp"),
		ReaperImage: testcontainers.ReaperDefaultImage,
		Networks:    []string{"test_fuzz"},
	}
	require.NoError(tb, err)

	container, err := testcontainers.GenericContainer(
		ctx,
		testcontainers.GenericContainerRequest{
			ContainerRequest: containerRequest,
			Started:          false,
		},
	)
	require.NoError(tb, err)
	err = container.Start(ctx)
	require.NoError(tb, err)

	err = container.StartLogProducer(ctx)
	require.NoError(tb, err)

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	})
	s := http.Server{Addr: "0.0.0.0:8090"}
	go s.ListenAndServe()
}

func testFoo(tb testing.TB, tenant string) {
	request, err := http.NewRequest(http.MethodPut, "http://127.0.0.1:8090/", bytes.NewBuffer([]byte(tenant)))
	require.NoError(tb, err)

	response, err := http.DefaultClient.Do(request)
	require.NoError(tb, err)
	defer func() {
		require.NoError(tb, response.Body.Close())
	}()
	require.Equal(tb, http.StatusOK, response.StatusCode)
}

```

Command:  go test -fuzz=FuzzFoo -tags fuzzing -test.fuzztime 3m ./fuzz_test.go

Starting without initializing environment produces correct output

### What did you expect to see?

`fuzz: elapsed: 0s, gathering baseline coverage: 1/1 completed, now fuzzing with 4 workers
`
### What did you see instead?

```
fuzz: elapsed: 0s, gathering baseline coverage: 0/1 completed
fuzz: elapsed: 0s, gathering baseline coverage: 0/1 completed
--- FAIL: FuzzFoo (15.07s)
    fuzzing process terminated without fuzzing: EOF
FAIL
exit status 1
```

**Comment by Ferrany1** [comment]
Seems like problem occurs because of testcontainers

**Comment by seankhliao** [comment]
please fill out the issue template properly and include a self contained, reproducible example

**Comment by Ferrany1** [comment]
> please fill out the issue template properly and include a self contained, reproducible example

I'll add example later, what I'm also missing from template?

**Comment by Ferrany1** [comment]
> please fill out the issue template properly and include a self contained, reproducible example

Added example with command, as I mentioned above it seems like testcontainers lib somehow affects fuzzing, because without it everything is fine

**Comment by Ferrany1** [comment]
> please fill out the issue template properly and include a self contained, reproducible example

Anything else needed?

**Comment by seankhliao** [comment]
Fuzzing runs multiple subprocesses so it can catch crashes. Your use of testcontainers isn't compatible with that, the processes compete for shared global (OS) resources.
The bad error message is from testcontainers not reporting a proper error.

**Comment by Ferrany1** [comment]
> Fuzzing runs multiple subprocesses so it can catch crashes. Your use of testcontainers isn't compatible with that, the processes compete for shared global (OS) resources. The bad error message is from testcontainers not reporting a proper error.

But it seems okay if i start containers manually in docker, so it occurs because of some inner testcontainer work?
However it work okay in unit tests without any errors produced on side of testcontainers

**Comment by mdonkers** [comment]
In case others come across this, the solution is adding `-parallel 1` as parameter to the fuzzing test.
At least in my scenario running fuzzing against a testcontainer (DB to verify string formatting) worked fine.
