### ISSUE TITLE
cmd/compile: No error when using interface with typeset with variable

### ISSUE THREAD

**Issue by icholy** [golang/go#52139]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/icholy/.cache/go-build"
GOENV="/home/icholy/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/icholy/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/icholy/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build722358823=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

``` go
package main

func main() {
	var _ interface{ string | any } = "test"
}
```

https://go.dev/play/p/L9p1kcNJs9O

### What did you expect to see?

```
./prog.go:4:8: interface contains type constraints

Go build failed.
```

### What did you see instead?

Compiled successfully.

**Comment by mdempsky** [comment]
Spec says "Interfaces whose type sets **can be** defined entirely by a list of methods are called basic interfaces."

So that suggests to me that it's intended that `interface{ string | any }` is a basic type, and thus should be valid as a variable type. And the compiler is correct to accept it.

Related #52124.

**Comment by griesemer** [comment]
@mdempsky Correct. This interface is the same as `interface{}` and thus permitted in this context.
