### ISSUE TITLE
net/http: DetectContentType does not detect image/heic

### ISSUE THREAD

**Issue by abezzub** [golang/go#52144]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/uname/Library/Caches/go-build"
GOENV="/Users/uname/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/uname/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/uname/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.18/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.18/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bw/m4317tjx769_rr503g4sxzkr0000gn/T/go-build2546652830=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

extracted the first 512 bytes of a HEIC image (produced by iPhones) and ran net/http.DetectContentType on it
```
contentType := http.DetectContentType(fileBytes)
```

### What did you expect to see?

`image/heic`

### What did you see instead?

`application/octet-stream`

**Comment by seankhliao** [comment]
at this point in time, whatwg has not determined a pattern for heic: https://mimesniff.spec.whatwg.org/#matching-an-image-type-pattern

**Comment by josharian** [comment]
If you're willing to go beyond whatwg, or for anyone else who finds this issue, https://github.com/strukturag/libheif/issues/83 is helpful.
