### ISSUE TITLE
interface and func as parameters

### ISSUE THREAD

**Issue by EvenBoom** [golang/go#52146]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=D:\GoFuture\bin
set GOCACHE=C:\Users\乐谱里的画\AppData\Local\go-build
set GOENV=C:\Users\乐谱里的画\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\GoFuture\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\GoFuture
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ 乐谱里~1\AppData\Local\Temp\go-build1467603294=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

The results are different when struct A has only one field and B has two or above fields, and it just happens when parameter type is interface.
I'm not sure if that's a bug.
Please clear my doubts, tx!

``` golang
package main

import (
	"fmt"
)

func main() {
	a := A{}
	m("A", a, SetAI(&a))
	b := B{}
	m("B", b, SetBI(&b))
}

type A struct {
	I int
	S string
}

type B struct {
	I int
}

func SetAI(a *A) A {
	a.I = 10
	return *a
}

func SetBI(b *B) B {
	b.I = 10
	return *b
}

func m(name string, arg1, arg2 interface{}) {
	fmt.Println(name+":", arg1, arg2)
}
``` golang


### What did you expect to see?
A: {10} {10}
B: {10} {10}


### What did you see instead?
A: {0 } {10 }
B: {10} {10}

**Comment by ianlancetaylor** [comment]
In a function call like `m("A", a, SetAI(&a))` the Go language does not specify whether the second argument or the third argument is evaluated first.  This code could be equivalent to

```Go
    t1 := a
    t2 := SetAI(&a)
    m("A", t1, t2)
```

or it could be equivalent to

```Go
    t2 := SetAI(&s)
    t1 := a
    m("A", t1, t2)
```

Different compilers can produce different results.  Even different versions of the same compiler can produce different results.

In general we do not use the issue tracker for questions.  If you have further questions about Go please use a forum.  See https://go.dev/wiki/Questions.  Thanks.

**Comment by go101** [comment]
related issues: 
* https://github.com/golang/go/issues/27821, for normal assignments
* https://github.com/golang/go/issues/25609, for function result returning

The current issue is for function argument passing.

**Comment by EvenBoom** [comment]
I got it, thanks everyone!
