### ISSUE TITLE
Using slice doesn't work properly 

### ISSUE THREAD

**Issue by acumino** [golang/go#52152]
### What version of Go are you using (`go version`)?
Both 1.17 and 1.18

### Does this issue reproduce with the latest release?

Yes

### What did you do?
Using slices in recursion and assigning its values to some value in any struct. 

See here: https://go.dev/play/p/iUZ5tF5AUJP 

The correct printed value should be 
```
[{[value1 value1 value1 value1 value1 value2 value3]}]
```
But it is printing 
```
[{[value1 value1 value1 value1 value1 value3 value3]}]
```

The same thing works fine if we don't use any struct.

See here: https://go.dev/play/p/d3ZLQTDPeoy

In this case the printed value is
```
[value1 value1 value1 value1 value1 value2 value3]
```

**Comment by randall77** [comment]
This is how slices work. Append does not always make a copy, but often appends in place.
See https://go.dev/blog/slices-intro for more background.

This patch fixes your code:
```
	if len(a) == 7 {
		a2 := make([]string, len(a))
		copy(a2, a)
		res := test{l: a2}
```
