### ISSUE TITLE
affected/package: go.dev website.

### ISSUE THREAD

**Issue by arsenikov** [golang/go#52161]
### What did you expect to see?

Generics in Go: summary, features and cautions from go 1.18 release group photo

### What did you see instead?

Generics in Go: summary, features and cautions from go 1.18 realease group photo

### What should be changed?
# L771
alt="Generics in Go: summary, features and cautions from go 1.18 realease group photo"

Should be changed to the following,
# L771
alt="Generics in Go: summary, features and cautions from go 1.18 release group photo"

### Summary

There is a small typo in the alt attribute of the image tag inside the div tag with the class "GoCarousel-eventThumbnail"

**Comment by ianlancetaylor** [comment]
What page do you see the type on?  Thanks.

**Comment by seankhliao** [comment]
I believe this refers to the Meetups section of the  https://go.dev/learn/ page, which pulls in data from meetup.com
The event that's linked has the typo in their title https://www.meetup.com/Women-Who-Go-Utah/events/htjjnsydchbfb/
Closing as I don't think there's anything to do on the Go side.

**Comment by arsenikov** [comment]
Ok
