### ISSUE TITLE
proposal: encoding/xml: Keep the annotation after do xml.Unmarshal

### ISSUE THREAD

**Issue by CyberLife-Markus** [golang/go#52174]
When the XML file is parsed by the Unmarshal function, restoring it using Marshal loses the original annotation content。

When dealing with some complex XML configuration files, the annotation information of corresponding fields is often very useful. Would you consider restoring the file annotation information during restoration？
example：

- user.xml

```
<!-- Field content comment......-->
<user name="common">
.....
```

- xml.go

```
	if err = xml.Unmarshal(userXMLFile, &user); err != nil {
		panic(err)
	}
	// Update of some field values...
	context, err := xml.Marshal(&user)
	if err != nil {
		panic(err)
	}
	// Output:
	// <!-- Field content comment......-->
	// <user name="new_username">
	// .....
```

**Comment by seankhliao** [comment]
see the `comment` tag option
