### ISSUE TITLE
net: TestDialParallel failures due to longer-than-expected delay on Windows

### ISSUE THREAD

**Issue by bcmills** [golang/go#52173]
```
--- FAIL: TestDialParallel (6.16s)
    dial_test.go:173: dialClosedPort: measured delay 1.0028044s
    dial_test.go:313: #5: got 1.2757236s; want <= 1.20336528s
FAIL
FAIL	net	55.514s
```

`greplogs --dashboard -md -l -e 'FAIL: TestDialParallel .*(?:\n    .*)*got .*; want <= .*'`

[2022-04-05T18:01:26-9e16cc1/windows-amd64-longtest](https://build.golang.org/log/b425090f4d802e521f1c11f26e72b33bcc6ca18e)

Note that the test currently uses a hard-coded heuristic for the timing bounds:
https://cs.opensource.google/go/go/+/master:src/net/dial_test.go;l=302-309;drc=da7891f6f36c48f2931ed916ed305330c06f9bd7

(See previously #35616; CC @ianlancetaylor @neild.)

**Comment by bcmills** [comment]
Since `windows/amd64` is a first-class port, this is a release-blocker for Go 1.19.

(It may be possible to resolve by making the timing bounds even more lax, or by somehow eliminating the timing bounds entirely if the test is meaningful without them.)

**Comment by prattmic** [comment]
FWIW, I've been attempting to reproduce a different Windows issue, but have managed to reproduce this twice thus far in ~1hr of testing with 25 windows-amd64-longtest gomotes using https://github.com/mknyszek/goswarm/.

**Comment by heschi** [comment]
@prattmic is this OK after beta 1?

**Comment by prattmic** [comment]
@neild will know better, but I imagine so, it is quite rare now.

**Comment by neild** [comment]
Yes, this is okay after beta1.

The test is irredeemably flaky. I think it needs to be rewritten.
