### ISSUE TITLE
x/pkgsite: Subpackage to recognise version tags

### ISSUE THREAD

**Issue by pjebs** [golang/go#52177]
I have a repo: https://github.com/rocketlaunchr/showerglass.

At the root level there is a module called: `github.com/rocketlaunchr/showerglass` with a package called `main`. It is simply a demo project that uses the package inside the `core` directory.

In the core directory is the actual package for mass consumption. It has a module called `github.com/rocketlaunchr/showerglass/core` with a package called `showerglass`.

If I tag the repo at `v1.0.0`, pkg.go.dev does not seem to recognise the `github.com/rocketlaunchr/showerglass/core` module as `v1.0.0`. It assumes the entire module is unversioned. 

This is causing issues with third-party use of my package (in terms of adding a version to their `go.mod` file. It is also causing issues with me not being able to "force" pkg.go.dev to update the docs to the current version since I can't append `@v1.0.0`.

**Comment by seankhliao** [comment]
Modules have separate identities and versions, that's how both the go command and pkgsite work.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by pjebs** [comment]
How do I version my package then?

**Comment by D1CED** [comment]
You version a submodule by creating a tag starting with the path relative to the root of the repository followed by the version. So `relative/path/v1.x.y`. [Example](https://github.com/go-modules-by-example/submodules)

**Comment by pjebs** [comment]
Thanks @D1CED
