### ISSUE TITLE
strconv: index out of range in FormatFloat

### ISSUE THREAD

**Issue by catenacyber** [golang/go#52187]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/catena/Library/Caches/go-build"
GOENV="/Users/catena/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/catena/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/catena/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/catena/go/src/github.com/catenacyber/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pp/dc1dtf9x2js3v0jx_m010nqr0000gn/T/go-build4237848497=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.17.6 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.17.6
uname -v: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
lldb --version: lldb-1316.0.9.41
Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
gdb --version: GNU gdb (GDB) 9.1
</pre></details>

### What did you do?

Run https://go.dev/play/p/tGb3ISbthgv

### What did you expect to see?

The program finishing and printing somme dummy data

### What did you see instead?

```
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
strconv.formatDecimal(0x41196f?, 0x7f25fd803500?, 0x0?, 0x0?, 0x7f25fd9fffff?)
	/usr/local/go-faketime/src/strconv/ftoaryu.go:219 +0x278
strconv.ryuFtoaFixed64(0xc000070e80, 0x7f25fd803500?, 0xc00003c5e0?, 0x0)
	/usr/local/go-faketime/src/strconv/ftoaryu.go:154 +0x1c5
strconv.genericFtoa({0xc000016018, 0x0, 0x18}, 0x2624542108?, 0x0, 0x0, 0x7f262454d0f8?)
	/usr/local/go-faketime/src/strconv/ftoa.go:149 +0x41c
strconv.FormatFloat(0x405058?, 0x70?, 0x0, 0x60?)
	/usr/local/go-faketime/src/strconv/ftoa.go:48 +0x74
main.main()
	/tmp/sandbox175921334/prog.go:11 +0x2e

Program exited.
```

Found by https://github.com/catenacyber/ngolo-fuzzing on oss-fuzz 
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46427

**Comment by catenacyber** [comment]
The one-liner reproducer is `strconv.FormatFloat(6.013470016999068e-154, byte(0x0), int(0), int(64))`

**Comment by ianlancetaylor** [comment]
CC @remyoudompheng

**Comment by catenacyber** [comment]
friendly ping @remyoudompheng What is coming for this issue ?

**Comment by remyoudompheng** [comment]
Interestingly there is no issue with valid uses of the package as show by this example:
```go
package main

import (
      "strconv"
)

func main() {
      x := 6.013470016999068e-154
      println(strconv.FormatFloat(x, 'f', 0, 64))
      println(strconv.FormatFloat(x, 'g', 0, 64))
      println(strconv.FormatFloat(x, 'e', 0, 64))
      println(strconv.FormatFloat(x, 'x', 0, 64))
}
```

The issue was already present in Go 1.15 with the following panic message:
`panic: strconv: internal error: extFloat.FixedDecimal called with n == 0`

The same message exists in Go 1.1 and probably even before (I am not able to run Go 1.0).
It seems the expected output is `"%" + string(fmt)`
