### ISSUE TITLE
cmd/compile: writing output: write $WORK/b216/_pkg_.a: file too large

### ISSUE THREAD

**Issue by TheSecEng** [golang/go#52195]
### What version of Go are you using (`go version`)?

<pre>
> go version
go version go1.18 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOENV="/Users/zacharyschulze/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zacharyschulze/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zacharyschulze/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/zacharyschulze/.projects/formulate/auth/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/l9/1zycp06j2dz031y3fscvs1mm0000gn/T/go-build2294249676=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```
> FORMULATE_CONFIG=config/development.yaml go run main.go serve
# golang.org/x/net/trace
compile: writing output: write $WORK/b216/_pkg_.a: file too large
# github.com/magiconair/properties
compile: writing output: write $WORK/b052/_pkg_.a: file too large
# google.golang.org/protobuf/reflect/protoreflect
compile: writing output: write $WORK/b171/_pkg_.a: file too large
# github.com/klauspost/compress/huff0
compile: writing output: write $WORK/b311/_pkg_.a: file too large
# gopkg.in/ini.v1
compile: writing output: write $WORK/b168/_pkg_.a: file too large
# golang.org/x/sys/unix
compile: writing output: write $WORK/b048/_pkg_.a: file too large
# go.mongodb.org/mongo-driver/x/bsonx/bsoncore
compile: writing output: write $WORK/b289/_pkg_.a: file too large
# github.com/spf13/cobra
compile: writing output: write $WORK/b347/_pkg_.a: file too large
# github.com/spf13/afero
compile: writing output: write $WORK/b138/_pkg_.a: file too large
# golang.org/x/net/http2
compile: writing output: write $WORK/b260/_pkg_.a: file too large
# github.com/xdg-go/stringprep
compile: writing output: write $WORK/b328/_pkg_.a: file too large
```

```
> go build -o bin/auth .
# google.golang.org/protobuf/reflect/protoreflect
compile: writing output: write $WORK/b171/_pkg_.a: file too large
# github.com/klauspost/compress/huff0
compile: writing output: write $WORK/b311/_pkg_.a: file too large
# github.com/magiconair/properties
compile: writing output: write $WORK/b052/_pkg_.a: file too large
# golang.org/x/net/trace
compile: writing output: write $WORK/b216/_pkg_.a: file too large
# github.com/spf13/cobra
compile: writing output: write $WORK/b347/_pkg_.a: file too large
# gopkg.in/ini.v1
compile: writing output: write $WORK/b168/_pkg_.a: file too large
# golang.org/x/sys/unix
compile: writing output: write $WORK/b048/_pkg_.a: file too large
# go.mongodb.org/mongo-driver/x/bsonx/bsoncore
compile: writing output: write $WORK/b289/_pkg_.a: file too large
# github.com/spf13/afero
compile: writing output: write $WORK/b138/_pkg_.a: file too large
# golang.org/x/net/http2
compile: writing output: write $WORK/b260/_pkg_.a: file too large
# github.com/xdg-go/stringprep
compile: writing output: write $WORK/b328/_pkg_.a: file too large
```

### What did you expect to see?

Program to run

### What did you see instead?

File to large errors

**Comment by mengzhuo** [comment]
Could you complete "What did you do" with command line you run?

**Comment by TheSecEng** [comment]
Done

**Comment by mengzhuo** [comment]
Could you provide output of "ulimit -a"? I think you might set up file size limit accidentally.

**Comment by TheSecEng** [comment]
FWIW, this only began after upgrading to 1.18

**Comment by TheSecEng** [comment]
> Could you provide output of "ulimit -a"? I think you might set up file size limit accidentally.

```
> ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              1000
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       5568
-n: file descriptors                256
```

Looks like it!
