### ISSUE TITLE
x/pkgsite: package removal request forgithub.com/shopify/sarama

### ISSUE THREAD

**Issue by dethi** [golang/go#52192]
### What is the path of the package that you would like to have removed?

`github.com/shopify/sarama`

### Are you the owner of this package?

No, but please read the reason bellow.

### What is the reason that you could not retract this package instead?

The package is present twice in the index, once as `Shopify/sarama` and another as `shopify/sarama`.

https://pkg.go.dev/github.com/shopify/sarama -> hasn't indexed any version since 2019
https://pkg.go.dev/github.com/Shopify/sarama -> actually show the latest version (v1.32.0)

The correct casing should be `Shopify/sarama` (`github.com/Shopify/sarama`). I'm not sure why both versions are present in the index, but this is confusing user looking for the latest documentation. 

A simple Google search returns `shopify/sarama` as first result instead of `Shopify/sarama`:
<img width="727" alt="Screenshot 2022-04-06 at 23 39 29" src="https://user-images.githubusercontent.com/1011520/162084170-5150d2cd-05e8-494d-9d1a-9c8887ddad1a.png">

**Comment by seankhliao** [comment]
masked in https://go.dev/cl/400357
