### ISSUE TITLE
strings: EqualFold is not equivalent to comparing ToLower

### ISSUE THREAD

**Issue by bjkail** [golang/go#52204]
#52022 added [this statement](https://github.com/golang/go/blob/3a0cda43a49793429bc38bdcb1d2112179b02fe1/src/strings/strings.go#L1047) to the doc for `strings.EqualFold`:
> EqualFold(s, t) is equivalent to Tolower(s) == Tolower(t).

[This program](https://go.dev/play/p/pFqpaxzocoL) seems to be a counterexample.

(Additionally, it seems like the doc meant to say `ToLower` rather than `Tolower`?)

**Comment by hopehook** [comment]
Thanks. I'll follow up on this issue.

**Comment by hopehook** [comment]
> It seems like the doc meant to say ToLower rather than Tolower?

ToLower

**Comment by ainar-g** [comment]
Interestingly enough, this particular example seems to be okay with `strings.ToUpper`.  See <https://go.dev/play/p/JFkZxxPOhWe>.

**Comment by typesanitizer** [comment]
Example where comparison via `strings.ToUpper` is different from comparison via `EqualFold`. https://go.dev/play/p/9g3vAh5wCKN

**Comment by ianlancetaylor** [comment]
Thanks for the examples.

@hopehook Sorry for the incorrect suggestion.

**Comment by hopehook** [comment]
@ianlancetaylor Thanks Ian for the help. I really underestimated the complexity here.

**Comment by hopehook** [comment]
@typesanitizer @ainar-g Thanks for the examples.

I think you are more professional than me. If there is a good solution that can be implemented, I suggest that you can open another issue, solve it together, and help it become better.
