### ISSUE TITLE
doc: relnotes for net errors.Is behavior is backwards

### ISSUE THREAD

**Issue by bjkail** [golang/go#52205]
#51428 added [release notes](https://tip.golang.org/doc/go1.19#:~:text=When%20a%20net%20package%20function%20or%20method%20returns) for `errors.Is`
> When a net package function or method returns an "I/O timeout" error, the error will now satisfy `errors.Is(err, context.Canceled)`. When a net package function returns an "operation was canceled" error, the error will now satisfy `errors.Is(err, context.DeadlineExceeded)`. 

This is backwards: "I/O timeout" corresponds to `context.DeadlineExceeded`, and "operation was canceled" corresponds to `context.Canceled`.

**Comment by cherrymui** [comment]
cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Whoops, thanks.  Sent https://go.dev/cl/398895.
