### ISSUE TITLE
access: approvers

### ISSUE THREAD

**Issue by tatianab** [golang/go#52215]
See https://go.dev/wiki/GerritAccess

New member of Go Security team at Google.

Group: https://go-review.googlesource.com/#/admin/groups/1005,members
Gerrit user: https://go-review.googlesource.com/q/owner:tatiana@golang.org

**Comment by cherrymui** [comment]
Hi Tatiana,

Welcome to the team! I've added you to the may-start-trybots and approvers groups now.

Please be familiar with the rules for voting and submitting changes as described at https://golang.org/wiki/GerritAccess#approver-access-approvers. If you're unsure or have any questions, please don't hesitate to ask us.

Additionally, as described at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a trybot run.

Thanks!
