### ISSUE TITLE
x/tools/gopls: panic in hover

### ISSUE THREAD

**Issue by lixiangzhong** [golang/go#52211]
gopls version: v0.8.2 (go1.18)
gopls flags: 
update flags: proxy
extension version: 0.32.0
go version: 1.18
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Wed, 06 Apr 2022 04:16:53 GMT
restart history:
Wed, 06 Apr 2022 01:30:19 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1409d42]

goroutine 8796 [running]:
go/types.(*Package).Path(...)
	  package.go:31
golang.org/x/tools/internal/lsp/source.linkData({0x1c3ee48%3F, 0xc0001aaaf0%3F}, 0xc00822cff0)
	  hover.go:408  0x3a2
golang.org/x/tools/internal/lsp/source.HoverIdentifier({0x1c38550%3F, 0xc0059dc080%3F}, 0xc000264140)
	  hover.go:325  0xa7e
golang.org/x/tools/internal/lsp/source.Hover({0x1c38550, 0xc0059dc080}, {0x1c40b00%3F, 0xc00c3c6480}, {0x1c38898, 0xc00ea76120}, {0x89ac030%3F, 0xc0%3F})
	  hover.go:79  0xf7
golang.org/x/tools/internal/lsp.(*Server).hover(0x187da60%3F, {0x1c38550, 0xc0059dc080}, 0xc0089ac030)
	  hover.go:27  0x1e5
golang.org/x/tools/internal/lsp.(*Server).Hover(0xc0107a8080%3F, {0x1c38550%3F, 0xc0059dc080%3F}, 0x187da60%3F)
	  server_gen.go:144  0x25
golang.org/x/tools/internal/lsp/protocol.serverDispatch({0x1c38550, 0xc0059dc080}, {0x1c44670, 0xc0001ce120}, 0xc0089ac000, {0x1c387f0, 0xc0059dc000})
	  tsserver.go:467  0x13fa
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1({0x1c38550, 0xc0059dc080}, 0xc0089ac000, {0x1c387f0, 0xc0059dc000})
	  protocol.go:154  0x90
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1({0x1c38550, 0xc0059dc080}, 0xc0089ac000, {0x1c387f0%3F, 0xc0059dc000%3F})
	  lsprpc.go:506  0xa43
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x1c38550, 0xc0059dc080}, 0xc009e0f068, {0x1c387f0%3F, 0xc0059dc000%3F})
	  handler.go:35  0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x20a
[Error - 12:16:32 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, do you by any chance recall what you were hovering over when you hit this panic? I believe this is a regression in https://go.dev/cl/385016, but clearly we did not have tests for this type of hover, so it would be great if we could write down a reproducer rather than just being defensive.

Thanks!

**Comment by lixiangzhong** [comment]
sorry,I didn't record the situation at that time, and I can't reproduce it now
