### ISSUE TITLE
affected/package: The bug that reflects assignment to linked list

### ISSUE THREAD

**Issue by aurora-go** [golang/go#52229]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
not clear

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\12194\AppData\Local\go-build
set GOENV=C:\Users\12194\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\dev\code\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\dev\code\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\env\go1.18.windows-amd64\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\env\go1.18.windows-amd64\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\12194\AppData\Local\Temp\go-build3751061322=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
When the function is called by reflection, the input parameters of the function are parsed, and the linked list parameters are injected through map[string]interface{}

### What did you expect to see?
What I expect is that the linked list parameters should correspond exactly to the data of map[string]interface{}, and the last linked list node should not appear, and there should be a zero value phenomenon.

### What did you see instead?
The last node of the linked list parameter sets the value through reflection, and part of the printed result is zero. After running it several times, the probability of complete assignment success is about 50%. Note, this is only the case for the last linked list node.

**Comment by seankhliao** [comment]
can you provide a self contained, code example that demonstrates the problem.

**Comment by aurora-go** [comment]
Paste the code directly, too much. I have extracted the relevant code in the tool. The main.go file has written the code with the problem. You can control the child node Next and try to run it a few more times to see the effect. https://github.com/aurora-go/Test

**Comment by seankhliao** [comment]
You have a bug in your code around map iteration/returning.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
