### ISSUE TITLE
x/website: define the term `root module` in ref/mod

### ISSUE THREAD

**Issue by perillo** [golang/go#52227]
The documentation for *workspaces* introduced a new term `root module` in the *Go Module Reference*.
The term is used in [the glossary for **workspace**](https://go.dev/ref/mod#glos-workspace), but it is never defined.

**Comment by perillo** [comment]
The article https://go.dev/blog/get-familiar-with-workspaces uses the term `root module` in the first paragraph, but later use the term `main module` in

 * `use`: adds a module on disk to the set of main modules in a workspace [...]

This is a bit confusing.

**Comment by mvdan** [comment]
I think the docs mean to use "main module" consistently; there might have been a mistake due to the similar concept that is "root package".

**Comment by cherrymui** [comment]
cc @matloob @bcmills

**Comment by bcmills** [comment]
Yes, it would be correct to use “main module” instead, since https://go.dev/ref/mod#minimal-version-selection also uses the term “main modules”:
> MVS starts at the main modules (special vertices in the graph that have no version) and traverses the graph
