### ISSUE TITLE
x/build/dashboard: linux-mips64le-mengzhuo repeatedly timing out while writing snapshot

### ISSUE THREAD

**Issue by dmitshur** [golang/go#52235]
Almost all recent commits don't have a build result for this builder yet, as seen on build.golang.org:

<img width="55" alt="image" src="https://user-images.githubusercontent.com/1924134/162482510-8c6698a2-953d-4b42-82e0-7cd94533dcea.png">

From coordinator logs:

```
$ kubectl logs coordinator-deployment-86f6c447fc-qkkhc | grep 'failed to write snapshot to GCS'
2022/04/08 14:28:29 [build linux-mips64le-mengzhuo 3e7ffb862f550c38ce0611b970a4dce10a01226e]: failed to write snapshot to GCS after copying 6622422 bytes: context deadline exceeded
2022/04/08 14:41:16 [build linux-mips64le-mengzhuo 3e387528e54971d6009fe8833dcab6fc08737e04]: failed to write snapshot to GCS after copying 5668283 bytes: context deadline exceeded
2022/04/08 14:54:19 [build linux-mips64le-mengzhuo 3e7ffb862f550c38ce0611b970a4dce10a01226e]: failed to write snapshot to GCS after copying 7044318 bytes: context deadline exceeded
2022/04/08 15:06:47 [build linux-mips64le-mengzhuo 3e387528e54971d6009fe8833dcab6fc08737e04]: failed to write snapshot to GCS after copying 5897663 bytes: context deadline exceeded
2022/04/08 15:19:49 [build linux-mips64le-mengzhuo 3e387528e54971d6009fe8833dcab6fc08737e04]: failed to write snapshot to GCS after copying 5864896 bytes: context deadline exceeded
2022/04/08 15:33:23 [build linux-mips64le-mengzhuo 3e387528e54971d6009fe8833dcab6fc08737e04]: failed to write snapshot to GCS after copying 5930430 bytes: context deadline exceeded
```

The write snapshot timeout at this moment is [5 minutes](https://cs.opensource.google/go/x/build/+/master:cmd/coordinator/buildstatus.go;l=871;drc=c3175ea8ba74b2c2f0adacce240f6e1495f49fed), and this builder is running into that timeout repeatedly while only writing approximately 5-7 MB. A typical snapshot is around 150 MB, so at that speed it'd need more than 2 hours.

Is this an unexpected issue with the builder and/or its internet uplink speed, or should the builder be configured with `SkipSnapshot: true`? I see that it already has `FlakyNet: true` set. @mengzhuo, are you able to take a look and advise how you'd like to proceed? Thanks.

CC @golang/release.

**Comment by dmitshur** [comment]
Based on the comment in [CL 399034](https://go.dev/cl/399034), I see a possible explanation is if the builder is slow on compression, not the upload, so the 2 hour estimate might be way off.

If so, we can see the effect that [CL 398697](https://go.dev/cl/398697) makes after it's deployed (soon).

**Comment by dmitshur** [comment]
@mengzhuo Result after making the timeout 15 minutes instead of 5:

```
2022/04/09 00:10:30 [build linux-mips64le-mengzhuo 0f0c89243044a5a5de142e51da3a98f082fd3771]: failed to write snapshot to GCS after copying 18973578 bytes: context deadline exceeded
```

It was able to transfer an approximate additional ~10 MB in the 10 extra minutes. It seems even 20 minutes would not be nearly enough.

**Comment by mengzhuo** [comment]
@dmitshur Thank you and this detail update. I've changed the proxy and it works.

**Comment by mengzhuo** [comment]
Since I transfer all MIPS owner to @Rongronggg9 , we can close this issue now.
