### ISSUE TITLE
affected/package: go env

### ISSUE THREAD

**Issue by desir1822** [golang/go#52230]
### What version of Go are you using (`go version`)?
Go1.16
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?

no

### What operating system and processor architecture are you using (`go env`)?
win10
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\001\AppData\Local\go-build
set GOENV=C:\Users\001\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\001\go\pkg\mod
set GONOPROXY=five.com/library.git
set GONOSUMDB=five.com/library.git
set GOOS=windows
set GOPATH=C:\Users\001\go
set GOPRIVATE=five.com/library.git
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Users\001\go\go1.16
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\001\go\go1.16\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\testmod\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fme
ssage-length=0 -fdebug-prefix-map=C:\Users\001\AppData\Local\Temp\go-build20
37510353=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
once upon a time, GOPRIVATE is set.But today,i want to modify the variable by "go env -w".It warns:warning: go env -w GOPRIVATE=... does not override conflicting OS environmen
t variable

### What did you expect to see?

how can i modify/unset the GOPRIVATE

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
