### ISSUE TITLE
spec: typo in "Embedded interfaces" section

### ISSUE THREAD

**Issue by powerman** [golang/go#52234]
> The type set of T is the intersection of the type sets defined by T's explicitly declared methods and the type sets of T’s embedded interfaces.

Sounds like term "intersection" must be replaced with "union".

**Comment by cherrymui** [comment]
I don't think it should. For
```
type Inner interface { ... }

type Outer interface {
  M()
  Inner
}
```
The type set of `Outer` is the types that implement `Inner` and also have an `M` method, which is the intersection of the type set of `Inner` and the type set that has an `M` method.

Thanks.

**Comment by powerman** [comment]
@cherrymui The problem is "type set" contains both a *union* and an *intersection*: it's a union of (union of methods) and (intersection of types). To me current wording sounds incorrect and misleading.

**Comment by cherrymui** [comment]
"Type set" is the set of types (that implement that interface). It is different from "method set", which is the union of the method sets of the embedded interfaces and the explicitly included methods.
