### ISSUE TITLE
x/pkgsite: package removal request for github.com/cyril1929

### ISSUE THREAD

**Issue by cyril1929** [golang/go#52243]
### What is the path of the package that you would like to have removed?
github.com/cyril1929
(i.e. 2 packages: github.com/cyril1929/zipkin-go-opentracing and github.com/cyril1929/zipkin-go-opentracing2)
 
### Are you the owner of this package?
yes
 
### What is the reason that you could not retract this package instead?
I did some tests with go mod by making dummy tags, without knowing this index database.
Now I know.
It was only tests, this package is currently not used by anyone. It can be removed without any problem.

**Comment by jamalc** [comment]
Done.
