### ISSUE TITLE
access: may-start-trybots 

### ISSUE THREAD

**Issue by zhouguangyuan0718** [golang/go#52249]
See https://go.dev/wiki/GithubAccess

Hi! I've started to contribute to go compiler, linker and runtime. It would be very helpful if I can start trybots to check my recently changes about dwarf. Thanks.

Group: https://go-review.googlesource.com/#/admin/groups/1030,members
Gerrit User: https://go-review.googlesource.com/q/owner:zhouguangyuan%2540golangcn.org
Email: [zhouguangyuan@golangcn.org](mailto:zhouguangyuan@golangcn.org)

cc @golang/release

**Comment by seankhliao** [comment]
cc @golang/release

**Comment by zhouguangyuan0718** [comment]
Hi again. Is there any decisions of this has been made? It will be better if I could get the access before this weekend. I'm planing to do more about issue #52209 this weekend. I hope I could run trybots myself to make sure my CLs works well. I can find out more bugs before I'm ready to review. 

CC @cherrymui , it looks like you handle these recently, Thanks.

**Comment by dmitshur** [comment]
Thanks for making this request @zhouguangyuan0718.

@thanm and I are already in the process of looking at this request (we have a rotation in place). We'll try to get back to you when possible. Thanks for your patience.

**Comment by thanm** [comment]
Hi,

Thank you for your contributions and for requesting Trybots access...  I've added you to the may-start-trybots group, so you should be able to do so now.

As you've likely read at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a Trybot run.

Let us know if you have any questions.

Cheers, Than
