### ISSUE TITLE
cmd/compile: compiler crash on valid code

### ISSUE THREAD

**Issue by Apakhov** [golang/go#52241]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64
</pre>
also reproduces on https://go.dev/play/

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/apakhov/Library/Caches/go-build"
GOENV="/Users/apakhov/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/apakhov/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/apakhov/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.18/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.18/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f7/27f7jd_n39sgk_j5kdmll529rw8xry/T/go-build3996695027=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://go.dev/play/p/w45g1myrZTl

### What did you expect to see?

compilation success

### What did you see instead?
<pre>
<autogenerated>:1: internal compiler error: unexpected dot in identifier: .rcvr1

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new

Go build failed.
</pre>

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport to 1.18

This is a compiler crash on valid code.

**Comment by ianlancetaylor** [comment]
CC @randall77 @mdempsky

**Comment by wdvxdr1123** [comment]
A smaller repro:
https://go.dev/play/p/QIaJ1iVUFjE
