### ISSUE TITLE
access: add kortschak to approvers

### ISSUE THREAD

**Issue by kortschak** [golang/go#52246]
https://go-review.googlesource.com/#/admin/groups/1030,members
https://go-review.googlesource.com/#/admin/groups/1005,members

Please add me to approvers and may-start-trybots.

**Comment by seankhliao** [comment]
cc @golang/release

**Comment by dmitshur** [comment]
Thanks for making this request.

What is the Gerrit email address? Is https://go-review.googlesource.com/q/owner:dan%2540kortschak.io the right one?

**Comment by kortschak** [comment]
Yes, that's correct.

**Comment by heschi** [comment]
Hi Dan,

Thank you for all your contributions to the Go project and ecosystem! I've discussed this request with the team (/cc @golang/release), and we agreed to grant you access. I've added you to the may-start-trybots and approvers groups now.

Please be familiar with the rules for voting and submitting changes as described at https://golang.org/wiki/GerritAccess#approver-access-approvers. If you're unsure or have any questions, please don't hesitate to ask us.

Additionally, as described at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a trybot run.

Thank you again for contributing, your help is greatly appreciated!
