### ISSUE TITLE
x/pkgsite: package removal request for github.com/gabe-lee/packing-crate

### ISSUE THREAD

**Issue by gabe-lee** [golang/go#52254]
### What is the path of the package that you would like to have removed?
github.com/gabe-lee/packing-crate

 
 
 
### Are you the owner of this package?
Yes

 
### What is the reason that you could not retract this package instead?
All package versions were retracted, but the package underwent significant refactor and re-assessment of goals and I ended up re-writing the entire thing from scratch with a different API in another package, the remaining package on pkgsite is an artifact of a non-existent repository.

**Comment by jamalc** [comment]
Done.
