### ISSUE TITLE
Request to remove googletagmanager.com/ from golang sites

### ISSUE THREAD

**Issue by sofeepokhrel** [golang/go#52250]
Hello, 

The official golang.org / go.dev site contains google tracking site called 
`https://www.googletagmanager.com/gtag/js?id=UA-11222381-7`

![Screenshot_2022-04-09_15-48-57](https://user-images.githubusercontent.com/103311708/162566713-670ab11c-6c23-497f-b0f1-e1815e786b9b.png)

I request to remove tracking contents or any content from any site that have tracking codes in it. 

I also want to ask,

By looking google tracking codes in go.dev. I feel if golang programming langauge source code also contains  other tracking codes.

I dont have hate to anybody. I love any company, i love golang. But i dont like being tracked, even in programming language site.
Thank you.

**Comment by illiliti** [comment]
[They already track contributors and sell their data by forcing to register google account](https://github.com/golang/go/issues/49383). Why would they remove tracking?

**Comment by rsc** [comment]
The Go web site uses Google Analytics to better understand how people use the site, where they spend time on it, and so on. It can also help us better understand latency and JS errors, as described in #40958. Among other reasons, that information helps us run the site effectively with a very small team. We will not be removing that. And of course the Go web site is not alone in using Google Analytics. Many sites on the web do the same. You appear to have a way to block Google Analytics already.

As for Go itself, there is no tracking per se but the go command does by default connect to a Google-run module proxy and checksum database, as is noted on the home page below the download button as well as at the top of https://go.dev/dl/. That page in turn links to https://proxy.golang.org/privacy, which explains exactly what information is and is not collected, and for how long. If you have any concerns about Go itself, I hope those details help. It is simple to configure Go not to use these services, but note that doing so gives up the reliability, security, and efficiency they provide.

I hope that answers any questions you have.

**Comment by sofeepokhrel** [comment]
> As for Go itself, there is no tracking per se but the go command does by default connect to a Google-run module proxy and checksum database, as is noted on the home page below the download button as well as at the top of https://go.dev/dl/. That page in turn links to https://proxy.golang.org/privacy, which explains exactly what information is and is not collected, and for how long. If you have any concerns about Go itself, I hope those details help. It is simple to configure Go not to use these services, but note that doing so gives up the reliability, security, and efficiency they provide.


☹️
@rsc  please do something.
Report big issue about these google tracking (even in go command), and many others to golang core team, rather than closing issue and be silent about these topics.

**Comment by enkeyz** [comment]
Google tracking people. Mind blown.

**Comment by ianlancetaylor** [comment]
@sofeepokhrel @rsc is a member of the Go core team.

**Comment by sofeepokhrel** [comment]
I think Golang team can't do anything. Nor golang is complete *free *opensource. 
It is said to be opensource, and its lie.

https://github.com/golang/go/blob/master/PATENTS

> [](https://github.com/)"This implementation" means the copyrightable works distributed by
> Google as part of the Go project.
> 
> Google hereby grants to You a perpetual, worldwide, non-exclusive,
> no-charge, royalty-free, irrevocable (except as stated in this section)
> patent license to make, have made, use, offer to sell, sell, import,
> transfer and otherwise run, modify and propagate the contents of this
> implementation of Go, where such license applies only to those patent
> claims, both currently owned or controlled by Google and acquired in
> the future, licensable by Google that are necessarily infringed by this
> implementation of Go.  This grant does not include claims that would be
> infringed only as a consequence of further modification of this
> implementation.  If you or your agent or exclusive licensee institute or
> order or agree to the institution of patent litigation against any
> entity (including a cross-claim or counterclaim in a lawsuit) alleging
> that this implementation of Go or any code incorporated within this
> implementation of Go constitutes direct or contributory patent
> infringement, or inducement of patent infringement, then any patent
> rights granted to you under this License for this implementation of Go
> shall terminate as of the date such litigation is filed. 


https://github.com/golang/go/blob/master/LICENSE

> 
> [](https://github.com/)Copyright (c) 2009 The Go Authors. All rights reserved.
> 
> Redistribution and use in source and binary forms, with or without
> modification, are permitted provided that the following conditions are
> met:
> 
>    * Redistributions of source code must retain the above copyright
> notice, this list of conditions and the following disclaimer.
>    * Redistributions in binary form must reproduce the above
> copyright notice, this list of conditions and the following disclaimer
> in the documentation and/or other materials provided with the
> distribution.
>    * Neither the name of Google Inc. nor the names of its
> contributors may be used to endorse or promote products derived from
> this software without specific prior written permission.
> 
> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
> "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
> LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
> A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
> OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
> SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
> LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
> DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
> THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
> (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
> OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


Nothing can be done. 
Just going with the flow and policies changes of google , shall also come here... ofcourse. 
Sorry me fooling here. :( 

Good luck go for nice future.

**Comment by tjpnz** [comment]
The developer community is highly represented when it comes to the use of ad and content blocking. How certain is the team that GA data is useful when it comes to making important decisions about the site?

**Comment by ianlancetaylor** [comment]
@sofeepokhrel "Lie" is a strong word.  Please be aware of the Go community code of conduct: https://go.dev/conduct.  In particular, please be charitable and respectful.  Thanks.

When it comes to computer programs, "open source" is a well defined term.  See https://opensource.org/osd.  I believe that Go is open source according to that definition.  I'm not sure why you are simply quoting the LICENSE and PATENTS file.  Those are widely used license grants and I believe that they are generally considered to follow the open source definition.

@tjpnz We are certain.  Thanks.  If you want to block Google Analytics, you may.  That will not cause you to lose access to anything on the site.
