### ISSUE TITLE
runtime: panic while panicking discards error message

### ISSUE THREAD

**Issue by myaaaaaaaaa** [golang/go#52257]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2719610640=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.18 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.18
uname -sr: Linux 5.17.1-arch1-1
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.35.
</pre></details>

### What did you do?

https://github.com/golang/go/issues/17671 fixed a hang caused by recursive panicking, but as a side effect, panic messages are now always discarded even if the recursion isn't endless. Is it feasible for the runtime to attempt to print the error even in the middle of a panic, and only stop after reaching a certain recursion depth?

Minimal example is available here: https://go.dev/play/p/IpGNUlM9YFP

### What did you expect to see?

```
fatal error: panic while printing panic value: important error message

stack trace omitted...
```

### What did you see instead?

```
fatal error: panic while printing panic value

stack trace omitted...
```

**Comment by ianlancetaylor** [comment]
I don't see what the runtime can do with an example like that.  It can't print the original panic value, because attempting to print it will itself panic.  You seem to be suggesting that it should print it anyhow, but there is literally nothing to print.  The attempt to find something to print failed.

**Comment by seankhliao** [comment]
This seems to be asking for printing the second panic value?
Where first is `panic(exampleError{})` and second is `panic("important error message")` that happens when trying to print the first panic.

**Comment by myaaaaaaaaa** [comment]
> This seems to be asking for printing the second panic value? Where first is `panic(exampleError{})` and second is `panic("important error message")` that happens when trying to print the first panic.

Yes, that's correct. Right now a workaround to get the second panic value printed is to do something like `panic(fmt.Sprintf("%v", exampleError{}))`

**Comment by ianlancetaylor** [comment]
Ah, got it, thanks.  Sorry for the confusion.

**Comment by myaaaaaaaaa** [comment]
No worries, it's admittedly a fairly bizarre scenario.

I've updated the playground link with a hopefully clearer explanation, copied here for convenience: https://go.dev/play/p/IpGNUlM9YFP
