### ISSUE TITLE
net: WriteMsgUDPAddrPort should accept IPv4 destination addresses on IPv6 UDP sockets

### ISSUE THREAD

**Issue by database64128** [golang/go#52264]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/database64128/.cache/go-build"
GOENV="/home/database64128/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/database64128/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/database64128/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1725863524=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Create an IPv6 UDP socket listening on `::`. Call `WriteMsgUDPAddrPort` with an IPv4 target address.

### What did you expect to see?

The write succeeds, just like `WriteMsgUDP`.

### What did you see instead?

```
write udp [::]:52794->12.34.56.78:12345: address 12.34.56.78: non-IPv6 address
```
https://github.com/golang/go/blob/db7183ccf9e7c245872864833e78a469e8747031/src/net/ipsock_posix.go#L215-L228

The check performed here should allow IPv4 as well.

**Comment by moredure** [comment]
@database64128 maybe !addr.IsValid() ?

**Comment by dmitshur** [comment]
CC @ianlancetaylor, @neild.

**Comment by bradfitz** [comment]
@ianlancetaylor @neild, now that we're moving more stuff over to `net/netip`, this is pretty painful.

Candidate for Go 1.19 + backport to Go 1.18?

**Comment by bradfitz** [comment]
@gopherbot, please backport to Go 1.18.

**Comment by dr2chase** [comment]
With respect to backports, what's the status of this bug/fix?
#54074 (1.18 backport) is still open.

**Comment by dmitshur** [comment]
The status of #54074 is that it's approved, but a cherry-pick CL hasn't been made yet. I made [CL 425488](https://go.dev/cl/425488) following https://go.dev/wiki/MinorReleases#making-cherry-pick-cls.
