### ISSUE TITLE
type parameter can not infer the shared underlying type (unsure if bug or feature request)

### ISSUE THREAD

**Issue by dans-stuff** [golang/go#52260]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

[https://go.dev/play/p/TR_hVFrldXH](https://go.dev/play/p/TR_hVFrldXH)

### What did you expect to see?

I expect the compiler to infer that A and B have the same underlying type.

This expectation comes from being able to pass an `A{}`, and a `map[string]int{}` and having the underlying type correctly inferred, and from being able to specify the underlying type manually to overcome the failed inference.

### What did you see instead?

I get a compile error `type B of B{} does not match inferred type A for M`

**Comment by seankhliao** [comment]
`m1, m2 M` means you want the same type for both.

```
func Equal2[K, V comparable](m1, m2 map[K]V) bool {
	return true
}
```

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
