### ISSUE TITLE
cmd/compile: compiler crash with "Dictionary should have already been generated"

### ISSUE THREAD

**Issue by benjivesterby** [golang/go#52279]
### What version of Go are you using (`go version`)?

**1.18**

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/benji/go/bin"
GOCACHE="/home/benji/.cache/go-build"
GOENV="/home/benji/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/benji/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/benji/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/benji/src/test/bug/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build616750673=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

Tried using this generic method [`go.structs.dev/gen/FMap.Flip()`](https://github.com/structsdev/gen/blob/e7434889096983a00a312e5b70b754063c450afe/map.go#L44) cross-package and received the following error:

```shell
benji | bug $ go build ./...
# go.structs.dev/gen/bug/imp
<autogenerated>:1: internal compiler error: Dictionary should have already been generated: go.structs.dev/gen..dict.FMap[string,go.structs.dev/gen/bug/lib.MyType].Flip

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

Here is a complete reproducible version:

[bug.tar.gz](https://github.com/golang/go/files/8466925/bug.tar.gz)

```shell
benji | bug $ tree
.
├── go.mod
├── go.sum
├── imp
│   └── imp.go
└── lib
    └── lib.go

2 directories, 4 files
```

```go
// lib/lib.go
package lib

import (
	"fmt"
	"strings"

	. "go.structs.dev/gen"
)

type MyType uint8

const (
	FIRST MyType = iota
	SECOND
	THIRD
)

var typeStrs = FMap[MyType, string]{
	FIRST:  "FIRST",
	SECOND: "SECOND",
	THIRD:  "THIRD",
}

var typeStrsR = typeStrs.Flip()

func (self MyType) String() string {
	str, exists := typeStrs[self]
	if !exists {
		return "UNKNOWN"
	}

	return str
}

func ParseMyType(t string) (MyType, error) {
	tpe, exists := typeStrsR[strings.ToUpper(t)]
	if !exists {
		return 0, fmt.Errorf("invalid type: %s", t)
	}
	return tpe, nil
}
```

```go
// imp/imp.go
package imp

import "go.structs.dev/gen/bug/lib"

func Print() {

	lib.FIRST.String()
}
```

### What did you expect to see?

I expected it to compile and be able to use the flipped map as a normal type aliased `go.structs.dev/gen/Map`

### What did you see instead?

Got this error:

```shell
benji | bug $ go build ./...
# go.structs.dev/gen/bug/imp
<autogenerated>:1: internal compiler error: Dictionary should have already been generated: go.structs.dev/gen..dict.FMap[string,go.structs.dev/gen/bug/lib.MyType].Flip

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

**Comment by ianlancetaylor** [comment]
A simpler version of lib.go that doesn't require an import but still recreates the problem:

```Go
// lib/lib.go
package lib

type Map[K comparable, V any] map[K]V

type FMap[K, V comparable] Map[K, V]

func (m FMap[K, V]) Flip() FMap[V, K] {
	out := make(FMap[V, K])
	for k, v := range m {
		out[v] = k
	}

	return out
}

type MyType uint8

const (
	FIRST MyType = iota
)

var typeStrs = FMap[MyType, string]{
	FIRST:  "FIRST",
}

func (self MyType) String() string {
	str, exists := typeStrs[self]
	if !exists {
		return "UNKNOWN"
	}

	return str
}
```

**Comment by ianlancetaylor** [comment]
CC @randall77 @mdempsky

**Comment by ianlancetaylor** [comment]
@gopherbot Please open a backport to 1.18

This looks like a compiler crash on valid code.

**Comment by mdempsky** [comment]
Repro on playground: https://go.dev/play/p/lFHvAeGwc1g?v=gotip

**Comment by dr2chase** [comment]
I'm looking at this, as part of my "learn generics by playing with bugs", and I see (with two debugging boolean set and -W=2)
```
# bug/lib
...
=== Finalized dictionary .dict.FMap[string,"".MyType].Flip
```
Where the missing dictionary is `bug/lib..dict.FMap[string,bug/lib.MyType].Flip`.

Do I read this correctly as an export/import problem?

**Comment by dr2chase** [comment]
Still slogging, intermittent with other work, but with `gdlv` on the failed compile, it is compiling
`(*FMap[string,bug/lib.MyType]).Flip` -- so this is an an export problem, for the initial export (and not, say, a re-export of something in `bug` with inlining).  Perhaps, actually a naming problem, in some way similar to https://go-review.googlesource.com/c/go/+/391574 ?

The bug does not reproduce when inlining is turned off.
The bug does not reproduce with `GOEXPERIMENT=unified`.

**Comment by dr2chase** [comment]
Further work.  A simpler version of lib/lib.go:
```
// lib/lib.go
package lib

type FMap[K comparable, V comparable] map[K]V

//go:noinline
func (m FMap[K, V]) Flip() FMap[V, K] {
	out := make(FMap[V, K])
	return out
}

type MyType uint8

const (
	FIRST MyType = 0
)

var typeStrs = FMap[MyType, string]{
	FIRST: "FIRST",
}

func (self MyType) String() string {
	return typeStrs[self]
}

// func F() FMap[string, MyType] {
// 	return typeStrs.Flip()
// }
```
Uncomment F at the bottom to make it pass; I think this is an export problem, where the exported inline for `MyType.String()` includes a reference to `typeStrs` (type `FMap[MyType, string]`) which in turn has a method `Flip()` which mentions the type `FMap[string, MyType]` which also has a method `Flip`.  I haven't figured out where/how this is all supposed to be exported, only that it is not.
