### ISSUE TITLE
cmd/compile: crash on an unusual program

### ISSUE THREAD

**Issue by go101** [golang/go#52278]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 linux/amd64
</pre>

### What did you do?

```Go
package main

func main() {
	_:
	_: // internal compiler error: label missing tag
}
```

### What did you expect to see?

Compiles okay.

### What did you see instead?

Fails to compile.

```
# command-line-arguments
./main.go:5:3: internal compiler error: label missing tag

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

**Comment by dmitshur** [comment]
CC @golang/runtime.

**Comment by nimelehin** [comment]
Seems, the current implementation removes labels after processing them in `func (e *escape) stmt(n ir.Node)`, so the 2nd blank label could not be found.
