### ISSUE TITLE
x/build: one freebsd-arm-paulzhol builder is missing

### ISSUE THREAD

**Issue by dmitshur** [golang/go#52277]
From https://farmer.golang.org:

```
host-freebsd-arm-paulzhol: 0/0 (1 missing)
```

Perhaps the builder needs attention or its `ExpectNum` configuration value is out of date. @paulzhol, are you able to take a look?

**Comment by paulzhol** [comment]
Sorry I was doing some maintenance and upgrading the host, but it took longer than expected. I've restored it for now and will continue during the weekend.

**Comment by dmitshur** [comment]
No problem at all, and thanks for the update. This issue was mostly to ensure it wasn't gone without you realizing that. Since it's back, marking as fixed.
