### ISSUE TITLE
cmd/go: workspace problems

### ISSUE THREAD

**Issue by haraldrudell** [golang/go#52271]
Version: go1.18
Repro in latest release
macOS 12.3.1 M1 Max

In order to reduce imports in a large package, I used a workspace with embedded go.mod. This no work with **go workspace sync**

github.com/haraldrudell/parl
┠  go.work: use ./mains, use .
┠  go.mod: next to no dependencies
┠ mains
 └ go.mod: requires the internet

### Problem 1: “go work sync” for importer no work
<blockquote><strong>go work sync</strong><br />
go: github.com/haraldrudell/parl/mains@v0.4.4:
reading github.com/haraldrudell/parl/mains/mains/go.mod
at revision mains/v0.4.4:
unknown revision mains/v0.4.4<br/>
1-21:11:23 foxyboy@c66 import-parl%
</blockquote>
Note: import-parl is a project that runs something from every package. It’s got a similar module set-up, too, for its imports

### Problem 2: no version tags on pkg.go.dev
Although mains package is in the same repository with the same git tags,
mains doesn’t get a version or version history:

https://pkg.go.dev/github.com/haraldrudell/parl/mains
— Version: v0.0.0-20220411030804-48d01f316f70

https://pkg.go.dev/github.com/haraldrudell/parl
— Version: v0.4.3

### Problem 3: go get -u
go get -u doesn’t seem to like life either. You have to specify the specific versions

go get github.com/haraldrudell/parl/mains@v0.4.4

### What did you expect to see?
* I expected go work sync to complete successfully with status code 0
* I expected the mains sub-package to be of version  v0.4.3
* I expected go get -u to upgrade to latest available version

### What did you see instead?
status code 1: error
Version: v0.0.0-20220411030804-48d01f316f70

Note: I am a target of HoffmanMoritzPincus. Anything with my name on it may be quickly hidden, discredited or closed

**Comment by haraldrudell** [comment]
It seems the cause is that the sub-packages do not get version number from the repository git tag.
Instead of using the version of the top package, they have git versions like v0.0.0-20220412173619-21bc3de3d441, the time there being utc

If they are upgraded using:
**go get -u github.com/haraldrudell/parl/mains@latest**
it works

works for me…

**Comment by dmitshur** [comment]
Modules inside subdirectories indeed need to be tagged separately, as described at https://go.dev/ref/mod#module-path and https://go.dev/ref/mod#vcs-version. Since I understand there's no more issue here, closing.
