### ISSUE TITLE
crypto/tls: avoid allocating context.WithCancel on each read/write op

### ISSUE THREAD

**Issue by moredure** [golang/go#52298]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/mikefaraponov/Library/Caches/go-build"
GOENV="/Users/mikefaraponov/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mikefaraponov/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mikefaraponov/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.18/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.18/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fm/wf4m_47533q_06bcn3vz54500000gn/T/go-build3774033150=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Established connection via tls.Client and doing read/write operations

### What did you expect to see?
No context.WithCancel should be allocated on each read/write operation, only on first Handshake

### What did you see instead?
Each time I am doing `(tls.Conn).Read` or `(tls.Conn).Write` operation context.WithCancel allocated

### Possible solution?
https://github.com/golang/go/pull/52274 - Check handshake first in Handshake, before trying to create context.WithCancel

**Comment by moredure** [comment]
https://github.com/golang/go/pull/52274

**Comment by dt** [comment]
Is this a duplicate of https://github.com/golang/go/issues/50657

**Comment by moredure** [comment]
@dt indeed!
