### ISSUE TITLE
affected/package: go 1.18

### ISSUE THREAD

**Issue by buzzy** [golang/go#52300]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 gccgo (GCC) 11.2.0 linux/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
bash-5.1# go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/.cache/go-build"
GOENV="/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/libexec/gcc/aarch64-unknown-linux-gnu/11.2.0"
GOVCS=""
GOVERSION="go1.16.5 gccgo (GCC) 11.2.0"
GCCGO="/usr/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/source/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3068417902=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
</pre></details>

### What did you do?
I am trying to compile go 1.18 using gccgo 11.2.0 with ./all.bash

### What did you expect to see?
A working go binary

### What did you see instead?
Failure during compilation

<pre>
/tmp/source/go/src/internal/abi/abi.go:48:7: internal compiler error: '(*RegArgs).Dump': nil register for value: v12 = SelectN <mem> [0] v11
(*RegArgs).Dump method(*RegArgs) func()
  b17:
    (-47) v5 = Arg <*RegArgs> {r} : r[*RegArgs] (r[*RegArgs])
    (?) v1 = InitMem <mem>
    (48) v6 = CALLstatic <mem> {AuxCall{runtime.printlock}} v1
    (48) v7 = SelectN <mem> [0] v6
    (?) v104 = SB <uintptr> : SB
    (?) v54 = SP <uintptr> : SP
    (?) v102 = MOVDaddr <*uint8> {go.string."Ints:"} v104 : R0
    (?) v107 = MOVDstore <mem> [8] v54 v102 v7
    (?) v106 = MOVDstore <mem> [16] v54 v102 v107
    (48) v9 = CALLstatic <mem> {AuxCall{runtime.printstring}} [16] v106
    (48) v10 = SelectN <mem> [0] v9
    (48) v11 = CALLstatic <mem> {AuxCall{runtime.printunlock}} v10
    (48) v12 = SelectN <mem> [0] v11
    (+49) v13 = LoweredNilCheck <void> v54 v12
    (+52) v40 = CALLstatic <mem> {AuxCall{runtime.printlock}} v12
    (52) v41 = SelectN <mem> [0] v40
    (52) v42 = CALLstatic <mem> {AuxCall{runtime.printnl}} v41
    (52) v43 = SelectN <mem> [0] v42
    (52) v44 = CALLstatic <mem> {AuxCall{runtime.printunlock}} v43
    (52) v45 = SelectN <mem> [0] v44
    (+53) v46 = CALLstatic <mem> {AuxCall{runtime.printlock}} v45
    (53) v47 = SelectN <mem> [0] v46
    (?) v105 = MOVDstore <mem> [8] v54 v12 v47
    (?) v123 = MOVDstore <mem> [16] v54 v12 v105
    (53) v49 = CALLstatic <mem> {AuxCall{runtime.printstring}} [16] v123
    (53) v50 = SelectN <mem> [0] v49
    (53) v51 = CALLstatic <mem> {AuxCall{runtime.printunlock}} v50
    (53) v52 = SelectN <mem> [0] v51
    (+57) v78 = CALLstatic <mem> {AuxCall{runtime.printlock}} v52
    (57) v79 = SelectN <mem> [0] v78
    (57) v80 = CALLstatic <mem> {AuxCall{runtime.printnl}} v79
    (57) v81 = SelectN <mem> [0] v80
    (57) v82 = CALLstatic <mem> {AuxCall{runtime.printunlock}} v81
    (57) v83 = SelectN <mem> [0] v82
    (+58) v84 = CALLstatic <mem> {AuxCall{runtime.printlock}} v83
    (58) v85 = SelectN <mem> [0] v84
    (?) v95 = MOVDstore <mem> [8] v54 v12 v85
    (?) v76 = MOVDstore <mem> [16] v54 v12 v95
    (58) v87 = CALLstatic <mem> {AuxCall{runtime.printstring}} [16] v76
    (58) v88 = SelectN <mem> [0] v87
    (58) v89 = CALLstatic <mem> {AuxCall{runtime.printunlock}} v88
    (58) v90 = SelectN <mem> [0] v89
    (+62) v116 = CALLstatic <mem> {AuxCall{runtime.printlock}} v90
    (62) v117 = SelectN <mem> [0] v116
    (62) v118 = CALLstatic <mem> {AuxCall{runtime.printnl}} v117
    (62) v119 = SelectN <mem> [0] v118
    (62) v120 = CALLstatic <mem> {AuxCall{runtime.printunlock}} v119
    (62) v121 = SelectN <mem> [0] v120
    (+63) v122 = MakeResult <mem> v121
    Ret v122
name r[*RegArgs]: [v5]

go tool dist: FAILED: /tmp/source/go/pkg/tool/linux_arm64/compile -std -pack -o /tmp/go-tool-dist-426457388/internal/abi/_go_.a -p internal/abi -importcfg /tmp/go-tool-dist-426457388/internal/abi/importcfg /tmp/source/go/src/internal/abi/abi.go /tmp/source/go/src/internal/abi/abi_generic.go: exit status 2
/tmp/source/go/src/runtime/internal/sys/intrinsics_common.go:112:10: internal compiler error: 'TrailingZeros64': resultInArg0 value's input SP cannot be an output of v25 = MOVDnop <int> v24

go tool dist: FAILED: /tmp/source/go/pkg/tool/linux_arm64/compile -std -pack -o /tmp/go-tool-dist-426457388/runtime/internal/sys/_go_.a -p runtime/internal/sys -importcfg /tmp/go-tool-dist-426457388/runtime/internal/sys/importcfg /tmp/source/go/src/runtime/internal/sys/consts.go /tmp/source/go/src/runtime/internal/sys/intrinsics.go /tmp/source/go/src/runtime/internal/sys/intrinsics_common.go /tmp/source/go/src/runtime/internal/sys/sys.go /tmp/source/go/src/runtime/internal/sys/zversion.go: exit status 2
/tmp/source/go/src/runtime/internal/math/math.go:15:3: internal compiler error: 'MulUintptr': nil register for value: v15 = MOVDstore <mem> {~r0} v29 v20 v24
MulUintptr func(uintptr, uintptr) (uintptr, bool)
  b1:
    (-13) v8 = Arg <uintptr> {a} : a[uintptr] (a[uintptr])
    (-13) v9 = Arg <uintptr> {b} : b[uintptr] (b[uintptr])
    (?) v1 = InitMem <mem>
    (?) v29 = SP <uintptr> : SP
    (-14) v22 = LoadReg <uintptr> v8 : R0
    (-14) v27 = LoadReg <uintptr> v9 : R1
    (14) v12 = OR <uintptr> v22 v27 : R2
    (14) v25 = CMPconst <flags> [4294967296] v22
    ULT v25 -> b5 b2
  b2: <- b1
    Z v22 -> b5 b7 (likely)
  b5: <- b2 b1
    (-15) v23 = VarDef <mem> {~r0} v1
    (-15) v24 = VarDef <mem> {~r1} v23
    (+15) v20 = MUL <uintptr> v22 v27 : R0
    (15) v15 = MOVDstore <mem> {~r0} v29 v20 v24
    (15) v43 = MOVBstorezero <mem> {~r1} v29 v15
    (15) v21 = MakeResult <mem> v43
    Ret v21
  b7: <- b2
    (-18) v39 = VarDef <mem> {~r0} v1
    (-18) v40 = VarDef <mem> {~r1} v39
    (+18) v36 = MUL <uintptr> v29 v15 : R2
    (18) v42 = MOVDstore <mem> {~r0} v29 v15 v40
    (+17) v32 = UDIV <uintptr> v29 v15 : R0
    (17) v35 = CMP <flags> v29 v15
    (17) v33 = GreaterThanU <bool> v35 : R0 (overflow[bool])
    (18) v41 = MOVBstore <mem> {~r1} v35 v15 v42
    (18) v37 = MakeResult <mem> v41
    Ret v37
name a[uintptr]: [v8]
name b[uintptr]: [v9]
name overflow[bool]: [v33]

go tool dist: FAILED: /tmp/source/go/pkg/tool/linux_arm64/compile -std -pack -o /tmp/go-tool-dist-426457388/runtime/internal/math/_go_.a -p runtime/internal/math -importcfg /tmp/go-tool-dist-426457388/runtime/internal/math/importcfg /tmp/source/go/src/runtime/internal/math/math.go: exit status 2
/tmp/source/go/src/internal/cpu/cpu_arm64_hwcap.go:38:49: internal compiler error: 'hwcapInit': panic during regalloc while compiling hwcapInit:

interface conversion: ssa.Location is nil, not *        bootstrap_1cmd_1compile_1internal_1ssa  ssa.Register

goroutine 1 [running]:
bootstrap/cmd/compile/internal/ssa.Compile..func1
        /tmp/source/go/src/cmd/compile/internal/ssa/compile.go:46
panic
        :0
bootstrap_1cmd_1compile_1internal_1ssa.regAllocState.regalloc
        /tmp/source/go/src/cmd/compile/internal/ssa/regalloc.go:1574
bootstrap/cmd/compile/internal/ssa.regalloc
        /tmp/source/go/src/cmd/compile/internal/ssa/regalloc.go:148
bootstrap_1cmd_1compile_1internal_1ssa.Compile
        /tmp/source/go/src/cmd/compile/internal/ssa/compile.go:98
bootstrap/cmd/compile/internal/ssagen.buildssa
        /tmp/source/go/src/cmd/compile/internal/ssagen/ssa.go:602
bootstrap_1cmd_1compile_1internal_1ssagen.Compile
        /tmp/source/go/src/cmd/compile/internal/ssagen/pgen.go:183
bootstrap/cmd/compile/internal/gc.compileFunctions..func6
        /tmp/source/go/src/cmd/compile/internal/gc/compile.go:153
bootstrap/cmd/compile/internal/gc.compileFunctions..func2
        /tmp/source/go/src/cmd/compile/internal/gc/compile.go:125
bootstrap/cmd/compile/internal/gc.compileFunctions..func5
        /tmp/source/go/src/cmd/compile/internal/gc/compile.go:152
bootstrap/cmd/compile/internal/gc.compileFunctions
        /tmp/source/go/src/cmd/compile/internal/gc/compile.go:163
bootstrap_1cmd_1compile_1internal_1gc.Main
        /tmp/source/go/src/cmd/compile/internal/gc/main.go:310
main.main
        /tmp/source/go/src/cmd/compile/main.go:55

go tool dist: FAILED: /tmp/source/go/pkg/tool/linux_arm64/compile -std -pack -o /tmp/go-tool-dist-426457388/internal/cpu/_go_.a -p internal/cpu -importcfg /tmp/go-tool-dist-426457388/internal/cpu/importcfg -asmhdr /tmp/go-tool-dist-426457388/internal/cpu/go_asm.h -symabis /tmp/go-tool-dist-426457388/internal/cpu/symabis /tmp/source/go/src/internal/cpu/cpu.go /tmp/source/go/src/internal/cpu/cpu_arm64.go /tmp/source/go/src/internal/cpu/cpu_arm64_hwcap.go /tmp/source/go/src/internal/cpu/cpu_arm64_linux.go /tmp/source/go/src/internal/cpu/cpu_no_name.go: exit status 2
</pre>

**Comment by ianlancetaylor** [comment]
Unfortunately GCC 11.2 has a known bug that causes it to fail when used as a bootstrapping compiler.  You must use 11.3 or later (or 10.4 or later).  See #47771.
