### ISSUE TITLE
x/pkgsite: github.com/google/go-tpm-tools not working with pkg.go.dev

### ISSUE THREAD

**Issue by josephlr** [golang/go#52314]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/google/go-tpm-tools/cmd@v0.3.7
 
### What is your user agent?
 
[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes) 
 
### Screenshot
 
Not Found
"github.com/google/go-tpm-tools/cmd@v0.3.7" could not be found. 
 
### What did you do?

We have a repository (https://github.com/google/go-tpm-tools) which has [version tags](https://github.com/google/go-tpm-tools/tags) for its main module (located at the directory root) and submodules (`launcher` and `cmd`). This is following the advice at https://go.dev/ref/mod#vcs-version
 
### What did you expect to see?
 
I expected pkg.go.dev to properly display the modules
 
### What did you see instead?

https://pkg.go.dev/github.com/google/go-tpm-tools/cmd@v0.3.7 does not work, and there is no option to "re-request" the module.

The other two modules in this repository properly display:
  - https://pkg.go.dev/github.com/google/go-tpm-tools@v0.3.7 
  - https://pkg.go.dev/github.com/google/go-tpm-tools/launcher@v0.3.7

The "pseudo-version" link for `github.com/google/go-tpm-tools/cmd` also works:
  - https://pkg.go.dev/github.com/google/go-tpm-tools/cmd

This also does not to be an issue with our github tags or https://proxy.golang.org. All the following links work correctly:
  - https://proxy.golang.org/github.com/google/go-tpm-tools/@v/v0.3.7.info
  - https://proxy.golang.org/github.com/google/go-tpm-tools/cmd/@v/v0.3.7.info
  - https://proxy.golang.org/github.com/google/go-tpm-tools/launcher/@v/v0.3.7.info

**Comment by josephlr** [comment]
After a few minutes, I was able to re-request the module documentation. However, it now just says `We're still working on “github.com/google/go-tpm-tools/cmd@v0.3.7”. Check back in a few minutes`. Returning to the same site a few minutes later just displays the same dialog to re-request the documentation.

**Comment by josephlr** [comment]
Checking again today, everything now seems to be displaying correctly. I'm still not sure what caused the original issue to begin with though.

**Comment by jamalc** [comment]
We were experiencing some processing lag after a brief outage.
