### ISSUE TITLE
all: provide macOS downloads for Go 1.18.1

### ISSUE THREAD

**Issue by dmitshur** [golang/go#52317]
The Go 1.18.1 release does not have macOS binaries available for download at https://go.dev/dl/ at this time. This is a known issue, and we are working on making those binaries available as soon as possible.

This is the tracking issue.

Until this is resolved, it's possible in the meantime to build Go 1.18.1 on macOS from [source code](https://go.dev/doc/install/source) or via the [gotip](https://pkg.go.dev/golang.org/dl/gotip) command. If you can wait for this issue to be resolved, it'll become possible to download Go 1.18.1 macOS binaries as usual.

CC @cherrymui, @golang/release.

**Comment by ghostsquad** [comment]
I tried to download & unzip/untar from :
```
download_url="https://dl.google.com/go/go${version}.${platform}-${arch}.tar.gz"
```

on macOs, and received 
```
tar: Error opening archive: Unrecognized archive format
```

Will that problem be solved at the same time that this is resolved?

**Comment by dmitshur** [comment]
@ghostsquad Yes. What you're describing will work after this issue is fixed.

**Comment by amnonbc** [comment]
Quite a lot of devs are using macs, and I imagine many are tripping up on the missing binaires.

So unless a fix is imminent, it might be worth adding 
some text to https://go.dev/dl/ saying something on the lines of 

"The mac binaries are missing right now. (This is a known issue <link to issue>).
We are hoping to get it fixed by DD/MM/YYYY. If you are a mac user, then best to carry on using 1.18
till then (link to 1.18 mac installers for AMD and arm). If you can't wait, then you can install from source
<link in build from source instructions>"

**Comment by alexellis** [comment]
I also had this issue this morning and it's really confusing.

Here's my workaround:

```bash
# Intel
curl -SL https://go.dev/dl/go1.18.darwin-amd64.pkg -o go1.18.darwin-amd64.pkg

# M1
curl -SL https://go.dev/dl/go1.18.darwin-amd64.pkg -o go1.18.darwin-arm64.pkg
```

Then `open filename` to install.

**Comment by amnonbc** [comment]
> I also had this issue this morning and it's really confusing.
> 
> Here's my workaround:
> 
> ```shell
> # Intel
> curl -SL https://go.dev/dl/go1.18.darwin-amd64.pkg -o go1.18.darwin-amd64.pkg
> 
> # M1
> curl -SL https://go.dev/dl/go1.18.darwin-amd64.pkg -o go1.18.darwin-arm64.pkg
> ```
> 
> Then `open filename` to install.

That will give you the 1.18 version from a few weeks ago.

Another option of mac users is to run `brew install golang` 
which will install go 1.18.1

**Comment by alexellis** [comment]
There's currently no download listed at all, but yes that's for 1.18 - so at least something that you can use to resume work while we wait for a fix on the website which currently shows no downloads for Darwin on the main downloads page beyond 1.17.

**Comment by nezorflame** [comment]
@alexellis it's there in the "Archived" section, since all previous releases go there
<img width="1035" alt="sh" src="https://user-images.githubusercontent.com/3906766/163189849-c1718c2d-f169-42b3-b865-3713e28d9a22.png">

**Comment by alexellis** [comment]
Good to know. I couldn't find this when I looked 👍 or perhaps it could be more obvious

**Comment by amnonbc** [comment]
> Good to know. I couldn't find this when I looked 👍 or perhaps it could be more obvious

Generally we want everyone to be using the latest release.
So we normally would not want to make it easier for people to find older versions.
Today is an exception.

**Comment by dmitshur** [comment]
We were able to resolve this problem by now, and all macOS downloads for Go 1.18.1 are available at https://go.dev/dl/ as usual, both for `darwin/amd64` and `darwin/arm64` ports.

Sorry for the trouble this delay caused, and thanks to everyone for your patience. We needed this extra time to resolve a problem in our release pipeline. There's ongoing work to improve our release process to minimize the chance of such occurrences in the future (for example, see #40279 for one of the high-level tracking issues).

I'm closing this since the issue is resolved, and will also unpin it after some time passes.

**Comment by bobbykjack** [comment]
Is there no binary available for Intel Macs?
