### ISSUE TITLE
x/website: invisible text on go.dev/solutions/clis

### ISSUE THREAD

**Issue by luiderek** [golang/go#52312]
### What is the URL of the page with the issue?
 https://go.dev/solutions/clis
 
 
### What is your user agent?
 [Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
 
### Screenshot
![image](https://user-images.githubusercontent.com/12964172/163043743-fc9f9b55-8a16-4b97-8fce-d7478375f6d4.png)

### What did you do?
load the page
 
### What did you expect to see?
visible text
 
### What did you see instead?
![image](https://user-images.githubusercontent.com/12964172/163043895-5d9e9cc9-604d-4a52-bf9a-add21b0e1ba9.png)

after text highlighted, anchor/background color are the same

**Comment by robpike** [comment]
I'm seeing this too, on my m1 mac running chrome or safari, both.

**Comment by ianlancetaylor** [comment]
CC @jamalc
