### ISSUE TITLE
syscall: Faccessat checks wrong group

### ISSUE THREAD

**Issue by neild** [golang/go#52313]
The `syscall.Faccessat` function checks whether the calling process can access a file.

`Faccessat` contains a bug where it checks a file's group permission bits if the process's user is a member of the *process's* group rather than a member of the *file's* group.

https://github.com/golang/go/blob/c9fe126c8bf25d14b233f1ccaff12c1bffbd4971/src/syscall/syscall_linux.go#L112

```
	var fmode uint32
	if uint32(uid) == st.Uid {
		fmode = (st.Mode >> 6) & 7
	} else {
		var gid int
		if flags&_AT_EACCESS != 0 {
			gid = Getegid()
		} else {
			gid = Getgid()
		}

		if uint32(gid) == st.Gid || isGroupMember(gid) { // <-- this should be isGroupMember(st.Gid), not gid
			fmode = (st.Mode >> 3) & 7
		} else {
			fmode = st.Mode & 7
		}
	}
```

Since a process's user is usually a member of the process's group, this causes Faccessat to usually check a file's group permissions even if the process's user is not a member of the file's group.

Thanks to @256dpi for reporting this.

**Comment by neild** [comment]
This bug only occurs on Linux systems, and when `syscall.Faccessat` is called with a non-zero `flags` parameter.

**Comment by neild** [comment]
`"golang.org/x/sys/unix".Faccessat` suffers from the same problem, but only on Linux kernels < 5.8.

**Comment by neild** [comment]
@gopherbot please open backport issues.

**Comment by heschi** [comment]
This shipped in yesterday's minor releases.
