### ISSUE TITLE
x/build/cmd/release: Windows zip/installer includes unnecessary `pkg/tool/windows_amd64/api.exe`

### ISSUE THREAD

**Issue by dagood** [golang/go#52335]
### What version of Go are you using (`go version`)?

https://go.dev/dl/go1.18.1.windows-amd64.zip

### What did you expect to see?

I don't think `pkg/tool/windows_amd64/api.exe` should be included. `pkg/tool/linux_amd64/api` isn't included in the Linux tar.gz.

The logic behind leaving out `api` is explained in [cmd/release/release.go#L506-L510](https://github.com/golang/build/blob/bf72255434a480f9b59722f048ee456d31faf62e/cmd/release/release.go#L506-L510) and https://github.com/golang/go/issues/13030:

```go
	// Users don't need the api checker binary pre-built. It's
	// used by tests, but all.bash builds it first.
	if err := client.RemoveAll(ctx, b.toolDir()+"/api"); err != nil {
		return err
	}
```

* https://github.com/golang/go/issues/13030

### What did you see instead?

`pkg/tool/windows_amd64/api.exe` is in the zip. It also shows up after using the msi installer.

---

I think `cmd/release` is probably just missing the code to remove the `.exe` because it was originally written with Linux in mind. I spotted this when I was comparing a Go build I did vs. the official Go build--this didn't break something I was working on. It seems pretty minor. (The file is only 5 MB.)

**Comment by dmitshur** [comment]
Thanks for the report. That does look like a simple oversight caused by the ".exe" suffix.

I think this might be convenient for @heschi to incorporate into work in #51797.

**Comment by heschi** [comment]
Indeed. Added to the stack.

**Comment by dmitshur** [comment]
> Added to the stack.

Not mailed yet or am I not looking in the [right place](https://go-review.googlesource.com/c/build/+/398694/5/internal/task/buildrelease.go#130)?

**Comment by heschi** [comment]
I just haven't mailed it yet to spare everyone the ~20 emails, but it's in my local stack.
