### ISSUE TITLE
net/http: DetectContentType: add audio/amr signature

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#52334]
The signature for that audio file type is missing.

**Comment by OneOfOne** [comment]
https://go-review.googlesource.com/c/go/+/400174

**Comment by neild** [comment]
https://mimesniff.spec.whatwg.org/#matching-an-audio-or-video-type-pattern doesn't include a pattern for audio/amr.

**Comment by OneOfOne** [comment]
@neild I'd like to argue that it's a popular enough format in the mobile world specially with older headsets that it warrants support.

**Comment by neild** [comment]
We don't really want to be in the business of making judgments about what is popular enough or not. `DetectContentType` is documented as following the WHATWG algorithm; the way to add a new type is to convince WHATWG to add it.
