### ISSUE TITLE
cmd/go: Since 1.18.1, go run always uses -buildvcs=false

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [golang/go#52338]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/circleci/.cache/go-build"
GOENV="/home/circleci/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/circleci/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/circleci/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/home/circleci/project/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2409035375=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Attempting to extract VCS info from `debug.ReadBuildInfo()` when running under `go run`.

1. https://go.dev/play/p/_09ZOz1UlC7
2. Create a new directory
3. `go mod init example`
4. Save the playground code as `main.go`
5. `git add . && git commit -m 'example'`
6. `go run .`

### What did you expect to see?

With go 1.18.0, I get:
```
$ go run . 
-compiler gc
CGO_ENABLED 1
CGO_CFLAGS 
CGO_CPPFLAGS 
CGO_CXXFLAGS 
CGO_LDFLAGS 
GOARCH amd64
GOOS linux
GOAMD64 v1
vcs git
vcs.revision 3905f8828680bce9d913660e098c704687ec309b
vcs.time 2022-04-13T20:07:46Z
vcs.modified false
```

### What did you see instead?

With go 1.18.1:
```
$ go run . 
-compiler gc
CGO_ENABLED 0
GOARCH amd64
GOOS linux
GOAMD64 v1
```

Even worse, `-buildvcs=auto` is not recognized:
```
$ go run -buildvcs=auto .
invalid boolean value "auto" for -buildvcs: parse error
usage: go run [build flags] [-exec xprog] package [arguments...]
Run 'go help run' for details.
```

Even even worse, `-buildvcs=true` is _ignored_:
```
$ go run -buildvcs=true .
-compiler gc
CGO_ENABLED 0
GOARCH amd64
GOOS linux
GOAMD64 v1
```

**Comment by mgabeler-lee-6rs** [comment]
Presumably this is (unintentional) fallout from #51723 and/or #51748

**Comment by seankhliao** [comment]
The backport for `-buildvcs=auto` is still open, so that's not expected to work yet #51798

cc @bcmills @matloob

**Comment by bcmills** [comment]
`go run` intentionally should not stamp VCS metadata. It has a nonzero latency cost and essentially zero benefit; the fact that it happened to stamp the binary in Go 1.18 was a bug missed during pre-release testing.

`go run` may be used with or without an explicit version.
* With an explicit version, there is no applicable VCS containing the package anyway.
* Without an explicit version, the VCS metadata can be recovered by running the VCS tool manually, since (by definition) `go run` does not result in a binary to be stored and shipped separately from the VCS and the `go run` command must have occurred within the repository.

**Comment by mgabeler-lee-6rs** [comment]
@bcmills I ask you reconsider for the following context/reasons:

1. The use case of `go run .` has VCS data available
2. At the very least, if `go run` is never going to stamp VCS data, then it should report an error if you invoke it as `go run -buildvcs=true`. Currently it accepts this flag but silently ignores it.

**Comment by aathan** [comment]
I am also having a lot of trouble getting `go build -buildvcs=true` to embed anything but `(devel)` as the version string for our internal included package, and the buildinfo.Settings including nothing but this:

```
-compiler = gcSetting CGO_ENABLED = 1Setting CGO_CFLAGS = Setting CGO_CPPFLAGS = Setting CGO_CXXFLAGS = Setting CGO_LDFLAGS = Setting GOARCH = amd64Setting GOOS = linuxSetting GOAMD64 = v1Dep github.com/PuerkitoBio/purell = v1.1.1
```

The documentation for BuildInfo is laughably sparse, and there is no indication how to add entries to Settings nor how to modulate the version strings embedded in the executable for the main program.

Maybe all of that info comes from what should be obvious places to those more familiar with go's package system than I am, but I have had no luck getting `go build` to embed anything useful when building inside a committed git repo.

**Comment by paralin** [comment]
Let's say you require a package in go.mod...

```
module mymodule

require github.com/gopherjs/gopherjs latest
```

And then you run it with go run...

```
go mod tidy
go run github.com/gopherjs/gopherjs -- build ./
```

Let's say we want to use `debug.ReadBuildInfo` in the GopherJS compiler to determine the version & mod sum for gopherjs from `go.mod` used when we ran `go run`.

This is a situation where -buildvcs=true with go run makes sense.
