### ISSUE TITLE
x/tools/gopls: Adding a warning when never actually consuming the contents of a string builder

### ISSUE THREAD

**Issue by m1212e** [golang/go#52355]
When using a string builder like this:

```
func() {
    var data strings.Builder
    data.WriteString("something")
}
```
no warning will be displayed, since the declared variable is used. On other occasions, such as not passing a reference to a json unmarshal, the linter displays a warning that the user might want something different. I think it would be pretty cool to have such a warning when never calling .String() or returning the string builder.

**Comment by findleyr** [comment]
This is an interesting idea, but I am not sure it is worth pursuing. For reference, there is precedent for checking this type of correct usage, e.g. with the [lostcancel](https://cs.opensource.google/go/x/tools/+/master:go/analysis/passes/lostcancel/lostcancel.go;l=21;drc=4054736f966a6d82ab3392c35ba8b0c0e6d724f8) analyzer.

How does this suit the vet [philosophy](https://github.com/golang/go/tree/master/src/cmd/vet)? How correct could this analyzer be? How frequent are the bugs that it catches? How precise would it be?

I'm not sure that this type of bug is frequent enough to warrant supporting a new analyzer: unlike calling `cancel()`, using a string builder's output is usually critical to the program's control flow. For that reason, I suspect people are much less likely to forget to call `.String()`. Furthermore, I am not sure how accurate this analyzer could be without additional machinery like SSA:  builders are often passed around.

Some data showing that this type of bug is common would help the discussion. For example how often does it occur in open-source codebases?

CC @timothy-king

**Comment by timothy-king** [comment]
> How precise would it be?

I think a vet checker would need to give up on most escapes for the `strings.Builder`, and report if there are no reads to the variable. After those restrictions, I am not too concerned about precision.

> How frequent are the bugs that it catches? 
> For example how often does it occur in open-source codebases?

+1 more real world examples would help assess impact and frequent.

**Comment by guodongli-google** [comment]
This example is a good one for the **UnusedResult** checker in DeepGo. Basically, all the side-effects within `WriteString` are on the receiver `data`, and the function return is not used. If `data` is not used after the function call, then it indicates a bug.
