### ISSUE TITLE
x/pkgsite: missing examples for https://pkg.go.dev/github.com/qqiao/pipeline@v1.0.0

### ISSUE THREAD

**Issue by qqiao** [golang/go#52363]
### What is the URL of the page with the issue?
https://pkg.go.dev/github.com/qqiao/pipeline@v1.0.0

### What is your user agent?
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36'

### Screenshot
N/A

### What did you do?
Submitted the module to pkg.go.dev.

### What did you expect to see?
pkg site should include a set of examples for various functions of the module since they are present in the `*_test.go` files as `Example*` functions. These examples also runs correctly by using `go test -v ./...`.

Also, running `godoc -http=:6060` generates a local version that correctly shows the examples.

### What did you see instead?
No examples section.

**Comment by ianlancetaylor** [comment]
This may be related to generics.  Perhaps the use of a generic type is causing the pkgsite code to fail to connect the example with the method.

**Comment by ianlancetaylor** [comment]
CC @golang/pkgsite

**Comment by jba** [comment]
Ian is correct. See #52496.

I'm working on a fix for the standard library, which I'll then backport to pkgsite.
