### ISSUE TITLE
affected/package: std/go run does not work as expected with nested go.mod

### ISSUE THREAD

**Issue by haraldrudell** [golang/go#52365]
go1.18

### What did you do?

With all this tagging I have to do for multiple sub-packages, I set off to make a push script in a subdirectory, losing the bash. Obviously, you do not want your build dependencies in the shipping product, which is the top go.mod. So there is a go.mod in the zbuild subdirectory.
This does not work with 1.18, because go looks for the top go.mod, not the closest go.mod

I had:
parl
┠ go.mod module github.com/haraldrudell/parl
┖zbuild
 ┠go.mod module main
 ┖pushparl.go

To run this, you have to cd into the zbuild directory. However, module resolution does not work because go looks in the top go.mod and it appears this behavior cannot be changed. I tried moving dependencies as subdirectories in the parl directory, I believe this works if you check it in so it is visible to go get. I tried a few replace, but finally moved the push script to another repository

* I think go should use the closest go.mod for module resolution starting at the current directory
* nested go.mod is something we need
* We need nested go.mod because of fewer repositories and more modules
* go run should have a -cd option like openvpn, that changes directory to where go.mod is
* gopls v0.8.3 said it does not support nested go.mod

A peculiarity is that in the broken mode, running a directory does not work 'go run .' but running files work 'go run *.go'

This no work either:
go run -modfile=gox.mod *.go

### What did you expect to see?
I expected go run to use the closest go.mod for module resolution, in this case in the current directory

### What did you see instead?
go complained and asked me to run go get. The program would not run

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
