### ISSUE TITLE
Inconsistency in generics constraint

### ISSUE THREAD

**Issue by Jimmy-Z** [golang/go#52367]
This doesn't work
```go
package main

import (
	"fmt"
)

type A struct{}

func (_ A) say() {
	fmt.Println("I'm A")
}

type B struct{}

func (_ B) say() {
	fmt.Println("I'm B")
}

type speaker interface {
	A | B
}

func ask[T speaker](a T) {
	a.say()
}

func main() {
	var a A
	var b B
	ask(a)
	ask(b)
}
```
```
./prog.go:24:4: a.say undefined (type T has no field or method say)
```
playground: https://go.dev/play/p/kDsN8X-fTr4

However this works:
```go
package main

import (
	"fmt"
)

type number interface {
	int | float32
}

func add[T number](a T, b T) T {
	return a + b
}

func main() {
	fmt.Println(add(1, 1))
	fmt.Println(add(float32(1), 1))
}
```
Basically following the tutorial: https://go.dev/doc/tutorial/generics
playground: https://go.dev/play/p/beL56erdLYr

So go is able to tell `int` and `float32` both have operator `+` but couldn't tell `A` and `B` both have method `say`, I'd say this is a serious inconsistency.

**Comment by rittneje** [comment]
This limitation is mentioned in the release notes. https://tip.golang.org/doc/go1.18#generics
> The Go compiler only supports calling a method m on a value x of type parameter type P if m is explicitly declared by P's constraint interface. Similarly, method values x.m and method expressions P.m also are only supported if m is explicitly declared by P, even though m might be in the method set of P by virtue of the fact that all types in P implement m. We hope to remove this restriction in a future release.

**Comment by Jimmy-Z** [comment]
Thanks, I didn't read that.

Believe me I googled before firing the issue but couldn't find anything, is there already an issue tracking this? should I close this?
