### ISSUE TITLE
cmd/go: Using go.work with parallel repo

### ISSUE THREAD

**Issue by JordnL** [golang/go#52369]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="darwin"
</pre></details>

### What did you do?
- I am trying to use go.work to reference a parallel repository
- We have a repository that contains a kubernetes operator and parallel to it, is a repo that defines operator resources (like rbac and crd)
<pre>
$ tree ./Parent -L 1
Parent
  ├── operator
  └── resources
</pre>
<pre>
$ cat operator/go.work
go 1.18

use ../resources
</pre>

### What did you expect to see?

We expected the go test to pass

### What did you see instead?

<pre>
$ go test
directory . outside modules listed in go.work or their selected dependencies
</pre>

similar to this issue: https://github.com/golang/go/issues/49632

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
