### ISSUE TITLE
x/pkgsite: package removal request for https://github.com/Bandwidth/go-bandwidth

### ISSUE THREAD

**Issue by ajrice6713** [golang/go#52405]
### What is the path of the package that you would like to have removed?

https://github.com/Bandwidth/go-bandwidth

 
 
 
### Are you the owner of this package?

Yes

 
### What is the reason that you could not retract this package instead?

Package is deprecated and for our v1 service that is no longer live - we dont want to confuse users that accidentally find this client expecting it to work

Additionally, it pre-dates the `go.mod` file and does not conform to the current package manager requirements

**Comment by jamalc** [comment]
Done.
