### ISSUE TITLE
cmd/go: build fails with sym links ("no Go files")

### ISSUE THREAD

**Issue by jhgit** [golang/go#52406]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 freebsd/amd64
</pre>

### Does this issue reproduce with the latest release?

Unknown

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>env GOPATH=/tmp/go go env</code> Output</summary><br><pre>
$ env GOPATH=/tmp/go go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xxx/.cache/go-build"
GOENV="/home/xxx/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOINSECURE=""
GOMODCACHE="/home/xxx/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="freebsd"
GOPATH="/tmp/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="cc"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2409260475=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I am trying to build some go projects (e.g., https://github.com/FiloSottile/age, https://github.com/muesli/duf).

If I start with an GOPATH pointing to an empty directory tree or one already populated with downloaded files, the build succeeds.  If GOPATH is a directory with symbolic links to files in another directory, the build fails.

Here is a script to reproduce the problem (using 'age' as an example,  but this happens with other go projects as well).  This script uses a tool called 'lndir' to create a hierarchy of sym links.  It uses /tmp/src and /tmp/go and /tmp/go-links as working directories.

    $ cat repro
    rm -rf /tmp/src
    mkdir /tmp/src
    cd /tmp/src
    wget --quiet https://github.com/FiloSottile/age/archive/refs/tags/v1.0.0.zip
    unzip v1.0.0.zip > /dev/null
    cd age-1.0.0

    echo "=== first build starting with no downloaded packages"
    echo "=== download packages to /tmp/go"
    find /tmp/go -type d -exec chmod u+w {} +
    rm -rf /tmp/go
    env GOPATH=/tmp/go go mod vendor
    env GOPATH=/tmp/go go build -v -o age ./cmd/age
    ls -al age

    echo "=== now do another build starting with the packages downloaded already"
    rm age
    env GOPATH=/tmp/go go build -v -o age ./cmd/age
    ls -al age

    echo "=== now build using tree of links to source packages in /tmp/go-links"
    cd ..
    mv age-1.0.0 age-1.0.0.no-links
    unzip v1.0.0.zip > /dev/null
    cd age-1.0.0
    rm -rf /tmp/go-links
    mkdir /tmp/go-links
    lndir /tmp/go /tmp/go-links > /dev/null
    env GOPATH=/tmp/go-links go mod vendor
    env GOPATH=/tmp/go-links go build -v -o age ./cmd/age
    ls -al age

    $ sh repro

Observe errors (as shown below) from running `repro` script.

I'm not sure where to start looking for the source of this error.  Apologies if this issue is mis-categorized, but I'm also not sure if this is the best place to start.

### What did you expect to see?

No errors.

### What did you see instead?

Errors like the following (for a build of age):

    package filippo.io/age/cmd/age
            imports filippo.io/age/agessh
            imports filippo.io/edwards25519: no Go files in /tmp/src/age-1.0.0/vendor/filippo.io/edwards25519
    package filippo.io/age/cmd/age
            imports filippo.io/age
            imports golang.org/x/crypto/chacha20poly1305: no Go files in /tmp/src/age-1.0.0/vendor/golang.org/x/crypto/chacha20poly1305
    package filippo.io/age/cmd/age
            imports golang.org/x/crypto/cryptobyte: no Go files in /tmp/src/age-1.0.0/vendor/golang.org/x/crypto/cryptobyte
    .
    .

Notice that vendor packages are missing (silently not downloaded) from the source tree after 'go mod vendor' when using the GOPATH hierarchy with symbolic links.

**Comment by ianlancetaylor** [comment]
In general the go tool intentionally does not support symlinks, but I don't know whether we've written that down anywhere.

CC @bcmills

**Comment by jhgit** [comment]
It seems to me that you generally have to do something special to "fail" to read a link that ultimately points to the desired file.  If you just "read" the filename (the name of the link), it (the system that allows symlinks to exist) would normally follow the link and things would just "just work".  I certainly don't know what _go_ is doing under the covers, so I imagine it's more complicated than that.  But I wouldn't think _go_ would need to do anything special to do the typical "right" thing for symlinks, which is to just let the system follow the sym link to access the contents of the file in question.

That said, this is an extremely difficult thing to debug and something of a cryptic failure.  Go does not emit any information indicating why 'go mod vendor' behaves differently.  If the decision is to "not support symlinks", at least go should provide more information so a user can see what is happening.  Maybe there is a better way to trace what's going on, and I am just not aware of it yet.  My first instinct was to add extra -v's, but that didn't help (for that matter a single -v didn't help).
