### ISSUE TITLE
cmd/compile: internal compiler error: panic: nil node incrementing const

### ISSUE THREAD

**Issue by andrealancichinetti** [golang/go#52401]
### What version of Go are you using (`go version`)?

<pre>
go version go1.18 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

It is the latest

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/andrea/Library/Caches/go-build"
GOENV="/Users/andrea/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/andrea/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/andrea/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/andrea/Desktop/work/cedar/optiswitch3/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/l1/f52v6_6x7r3898mqkgxf_pbm0000gn/T/go-build1397093389=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

https://go.dev/play/p/x5mhMhIElMa

### What did you expect to see?

cannot assign to x (declared const)

Go build failed.

### What did you see instead?

<unknown line number>: internal compiler error: panic: nil node

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new

**Comment by thanm** [comment]
@randall77 @griesemer @mdempsky
