### ISSUE TITLE
Error with Building Code with Generics Using Build Tags

### ISSUE THREAD

**Issue by kdonthi** [golang/go#52418]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.18
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ironman/Library/Caches/go-build"
GOENV="/Users/ironman/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/ironman/go/pkg/mod"
GONOPROXY="github.com/bloXroute-Labs"
GONOSUMDB="github.com/bloXroute-Labs"
GOOS="darwin"
GOPATH="/Users/ironman/go"
GOPRIVATE="github.com/bloXroute-Labs"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/ironman/go/go1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/ironman/go/go1.18/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/ironman/Documents/GitHub/serum-api/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ml/m51hb57x5ps51lm1bqdq3dzw0000gn/T/go-build2794738531=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

There is a file for integration tests with a build flag. When I try to run the tests using the build tag, it points me to an error with generics. The code pointed to by the error looks like this:
```
func[A, B](param1) // specifically the comma between the generic types A and B
```
And the error is this: `test/integration/grpc_test.go:88:53: expected ']' or ':', found ','`

However, when I take the build tags out, it starts working.

The command to run the test looks like this:
```
go test ./test/integration -tags=integration
```

### What did you expect to see?
I expected the test to run without any errors.

### What did you see instead?
There is an error with the generics.

**Comment by ianlancetaylor** [comment]
Please show us a small self-contained example that we can use to recreate the problem.  Thanks.
