### ISSUE TITLE
questions: same code run in different linux kernel version shows different memory usage

### ISSUE THREAD

**Issue by Howie59** [golang/go#52422]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.17.7
</pre>

### Does this issue reproduce with the latest release?

```golang
package main
func main() {
    for {}
} 
```

### What operating system and processor architecture are you using (`go env`)?
centos 8.0, kernel version 4.18.0

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/data/local/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/data/local/go"
GOPRIVATE=""
GOPROXY="http://goproxy.cn"
GOROOT="/data/local/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/data/local/golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.7"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1416722979=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

go build  then run it background
then top -p pid

### What did you expect to see?
same execucatable binary uses apparently different memory
the process on centos 8.0(kernel 4.18.0) use 5mb, while centos 7.0(kernel 3.10.0) use less than 1mb

### What did you see instead?
i build it based on go version 1.14, same binary use approximate same memory

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
