### ISSUE TITLE
affected/package: generics

### ISSUE THREAD

**Issue by AlekseyKanaev** [golang/go#52426]
### What version of Go are you using (`go version`)?
go1.18.1 darwin/arm64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
macOS Monterey 12.3.1
"arm64"

### What did you do?

https://go.dev/play/p/9sWxXYmAcUH

### What did you expect to see?
Code complies without any errors

### What did you see instead?
I got following errors:

_./main.go:16:9: cannot use generic type GenericCacheWrapper[T any] without instantiation_
_./main.go:12:9: cannot use generic type GenericCacheWrapper[T any] without instantiation_

**Comment by wdvxdr1123** [comment]
I think this is expected. Here is a correct version: 
https://go.dev/play/p/evwPBDigVLZ
