### ISSUE TITLE
/usr/local/go/src/sync/pool.go:213

### ISSUE THREAD

**Issue by fxld** [golang/go#52432]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.17.2
</pre>

### Does this issue reproduce with the latest release?
no

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

My go process is stuck, but it won't restart automatically.so, i open dlv to look for clues.
The clue I found was that all goroutines were competing for a lock whta named AllPoolsMu in golang pool.go:213.
this is deadlock.
<img width="718" alt="image" src="https://user-images.githubusercontent.com/37835664/164027839-15a479b8-4569-4047-a996-f37326fee8b3.png">
<img width="802" alt="image" src="https://user-images.githubusercontent.com/37835664/164027902-d0d6dbb4-21d5-4893-97d5-6a0e33954271.png">
<img width="810" alt="image" src="https://user-images.githubusercontent.com/37835664/164027991-52de45c8-d0f2-4796-b1bb-33759a7a47ad.png">
you see many of goroutines waiting for AllPoolsMu

### What did you expect to see?
How can I solve this problem？
How can I see which gorouties has this lock?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
