### ISSUE TITLE
x/pkgsite: package update request for github.com/nytimes/grocery

### ISSUE THREAD

**Issue by jackcook** [golang/go#52453]
### What is the path of the package that you would like to have removed?

github.com/nytimes/grocery

### Are you the owner of this package?

Yes
 
### What is the reason that you could not retract this package instead?

We accidentally requested the package's addition to pkg.go.dev before renaming the repository and decided to force-push an update reflecting the name change. v0.1.0 currently points to the previous version of the package, which no longer exists on GitHub. You can see this in how the timestamp at https://proxy.golang.org/github.com/nytimes/grocery/@latest does not match the one from GitHub, and also in how an attempt to `go get` the package returns a warning.

**Comment by seankhliao** [comment]
The proxy and checksum database implement an immutable log, once published the meaning of a particular version can't be changed. What you can do is bump up the version and retract the previous one.
