### ISSUE TITLE
runtime: TestSelectFairness failures with "unfair select"

### ISSUE THREAD

**Issue by bcmills** [golang/go#52465]
```
#!watchflakes
post <- pkg == "runtime" && test == "TestSelectFairness"
```

`greplogs --dashboard -md -l -e 'FAIL: TestSelectFairness .*(?:\n    .*)*unfair select'`

[2022-04-20T16:05:16-338a817/illumos-amd64](https://build.golang.org/log/7800b28584cb9aef9403caa1a10362d2d6388fc2)
[2022-03-23T19:31:43-2792a41/netbsd-386-9_0](https://build.golang.org/log/ce89e44434c38feeb66b2473ed62f16dde246b0f)
[2020-08-19T00:10:22-98a0071/js-wasm](https://build.golang.org/log/68e4bcc3c6b6b9bf02988973314b0585360b7214)

@golang/runtime: [the comment for this test](https://cs.opensource.google/go/go/+/master:src/runtime/chan_test.go;l=482-485;drc=ca7c6ef33d9eca2dbc7eb46601a051dc7dc4e411) suggests that it has a confidence level of “six nines”, which would be one spurious failure per ~1M runs. Is it still in line with that target?

See previously #34808, #22047.

**Comment by mengzhuo** [comment]
The "six nines" requires less than 244 out of 10000 trials however the fail logs shows 5245,5253,5246.

**Comment by randall77** [comment]
This last one looks to be about a 1 in a million chance of being that unbalanced (258 extra heads above the expected 5000 out of 10000 trials).
Maybe there is an issue here? But I'm inclined to just soften the test. I don't think the world would end if selects weren't perfectly random (60/40, say).
