### ISSUE TITLE
x/crypto/ssh/terminal: mark functions as Deprecated? 

### ISSUE THREAD

**Issue by kevinburkesegment** [golang/go#52469]
Currently the functions in x/crypto/ssh/terminal just call their equivalents in golang.org/x/term. 

Should we mark those functions as Deprecated? This will e.g. trigger people who are using staticcheck to import the new package, which is smaller and more focused than the x/crypto module. 

Happy to do this, just wanted to ask first in the name of Chesterton's Fence and all that.

**Comment by ianlancetaylor** [comment]
SGTM

**Comment by kevinburkesegment** [comment]
Sorry; the mistake is on my end. We were using an outdated version of the x/crypto project before the "Deprecation" notice, but I was looking at a newer source code version in my browser.

The updated package has a "Deprecated" tag on it, that's correctly picked up by build tools. Closing.
