### ISSUE TITLE
cmd/go: all.bash tests fail on master (ab9d31da9e) in TestIsTerminal

### ISSUE THREAD

**Issue by ainar-g** [golang/go#52461]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes on ab9d31da9e, no on ebe1435fbb.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ainar/.cache/go-build"
GOENV="/home/ainar/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ainar/go/pkg/mod"
GONOPROXY="REMOVED"
GONOSUMDB="REMOVED"
GOOS="linux"
GOPATH="/home/ainar/go"
GOPRIVATE="REMOVED"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/ainar/go/go1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/ainar/go/go1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3035289250=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```sh
time ./all.bash
```

### What did you expect to see?

A clean build.

### What did you see instead?

```none
[normal all.bash output up to this point]

##### cmd/go terminal test
--- FAIL: TestIsTerminal (0.00s)
    terminal_test.go:35: stdout is not a terminal
    terminal_test.go:38: stderr is not a terminal
FAIL
exit status 1
FAIL    cmd/go/testdata/testterminal18153       0.003s
go tool dist: Failed: exit status 1
Command exited with non-zero status 1
1774.90user 274.45system 3:39.00elapsed 935%CPU (0avgtext+0avgdata 3163960maxresident)k
788360inputs+10075200outputs (3551080major+47148408minor)pagefaults 0swaps
```

* * *

**EDIT:** After some experimentation, whether or not the `time` utility is used doesn't seem to matter, and neither does whether or not `all.bash` is called from a `tmux` terminal or a simple GNOME terminal.

**Comment by chenguoqi-cc** [comment]
I also encountered the same problem

**Comment by seankhliao** [comment]
cc @adg @bcmills 
Note previous issues #18153 #34877

**Comment by archana-ravindar** [comment]
we are seeing that ./all.bash fails with the same error on master for ppc64le as well

**Comment by bcmills** [comment]
This wasn't caught on the builders because (understandably) none of the builders run with `stdout` as an actual terminal.

(https://cs.opensource.google/go/go/+/master:src/cmd/go/testdata/testterminal18153/terminal_test.go;l=8-12;drc=2580d0e08d5e9f979b943758d3c49877fb2324cb)

**Comment by prattmic** [comment]
Note that this also caused failures on `TestScript/test_output_wait`.

**Comment by adg** [comment]
Damn, sorry for the noise.
I wonder if the change should still be applied even without the test?
It seems hard to test reliably.

**Comment by ianlancetaylor** [comment]
I'm not 100% sure, but it sounds like #18153 is calling for the opposite of what your change does.  So maybe we need to decide whether we made a mistake in handling #18153.
