### ISSUE TITLE
cmd/go: cannot get modules, ‘file too large’ error on module cache

### ISSUE THREAD

**Issue by matiaspascansky96** [golang/go#52471]
Go version: 1.17.8

### Does this issue reproduce with the latest release?
Yes, tried it with version 1.18.1

### What operating system and processor architecture are you using (`go env`)?
Macbook m1 Big Sur 11.5.2 

### What did you do?

I am trying to build and "go get" in a project with aws (github.com/aws/aws-sdk-go@v1.43.6) and go genproto (google.golang.org/genproto@v0.0.0-20220222213610-43724f9ea8cf) dependencies

### What did you expect to see?
Success and build compilation.

### What did you see instead?
 google.golang.org/genproto@v0.0.0-20220222213610-43724f9ea8cf: write /Users/matias.pascansky/go/pkg/mod/cache/download/google.golang.org/genproto/@v/v0.0.0-20220222213610-43724f9ea8cf.zip834934505.tmp: file too large

github.com/aws/aws-sdk-go@v1.43.6: write /Users/matias.pascansky/go/pkg/mod/cache/download/github.com/aws/aws-sdk-go/@v/v1.43.6.zip1268850339.tmp: file too large

**Comment by seankhliao** [comment]
what's the output of `ulimit -a`?

**Comment by matiaspascansky96** [comment]
> what's the output of `ulimit -a`?

-t: cpu time (seconds)              unlimited
-f: file size (blocks)              24000
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8176
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       2666
-n: file descriptors                20000

**Comment by matiaspascansky96** [comment]
> > what's the output of `ulimit -a`?
> 
> -t: cpu time (seconds) unlimited -f: file size (blocks) 24000 -d: data seg size (kbytes) unlimited -s: stack size (kbytes) 8176 -c: core file size (blocks) 0 -v: address space (kbytes) unlimited -l: locked-in-memory size (kbytes) unlimited -u: processes 2666 -n: file descriptors 20000

still same error

**Comment by ianlancetaylor** [comment]
24000 blocks means that you can only create a file up to 24,576,000 bytes in size.

Try setting the ulimit to unlimited and see how large the generated file is.

**Comment by matiaspascansky96** [comment]
> 24000 blocks means that you can only create a file up to 24,576,000 bytes in size.
> 
> Try setting the ulimit to unlimited and see how large the generated file is.

I set ulimit -f to unlimited, reboot and still get same error. The output when I write ulimit -a now is:

-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8176
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       2666
-n: file descriptors                20000

**Comment by matiaspascansky96** [comment]
> 24000 blocks means that you can only create a file up to 24,576,000 bytes in size.
> 
> Try setting the ulimit to unlimited and see how large the generated file is.

Worked! TY!
