### ISSUE TITLE
runtime: time management in OpenBSD port is wildly misconfigured

### ISSUE THREAD

**Issue by mknyszek** [golang/go#52475]
In the Go runtime, on most platforms, we generally assume that thread-level sleeps (and other time-based things) try to wake up in an amount of time that's somewhere close to what we pass. The one exception here, across the runtime, is Windows. For Windows, we [query interrupt time](https://cs.opensource.google/go/go/+/master:src/runtime/sys_windows_amd64.s;l=343?q=sys_windows_amd64.s&ss=go%2Fgo) because it's more efficient, and work around sleeps that rounded to a clock with coarse granularity.

OpenBSD has a [coarse-granularity](https://github.com/openbsd/src/blob/1ce5116978952e11c7146aae18a374d548ce446b/sys/conf/param.c?q=tick_nsec#L73) clock for [sleeps](https://github.com/openbsd/src/blob/1ce5116978952e11c7146aae18a374d548ce446b/sys/kern/kern_synch.c?q=tsleep_nsec+path%3A%2F%5Esys%5C%2Fkern%5C%2F%2F#L178), but the runtime doesn't act like it. (Thanks @prattmic for digging up these links!) That results in situations like this one:

```
gc 22 @0.471s 78%: 19+20+0.018 ms clock, 76+0.14/0.22/0+0.072 ms cpu, 4->4->1 MB, 4 MB goal, 0 MB stacks, 0 MB globals, 4 P
gc 23 @0.511s 79%: 19+0.17+0.015 ms clock, 77+0.094/0.097/0.10+0.060 ms cpu, 4->4->1 MB, 4 MB goal, 0 MB stacks, 0 MB globals, 4 P
gc 24 @0.531s 79%: 19+0.20+0.017 ms clock, 76+0.11/0.092/0.12+0.068 ms cpu, 4->4->1 MB, 4 MB goal, 0 MB stacks, 0 MB globals, 4 P
gc 25 @0.551s 80%: 19+0.23+0.016 ms clock, 76+0.086/0.079/0.10+0.064 ms cpu, 4->4->1 MB, 4 MB goal, 0 MB stacks, 0 MB globals, 4 P
gc 26 @0.571s 80%: 19+0.17+0.014 ms clock, 76+0.095/0.084/0.10+0.057 ms cpu, 4->4->1 MB, 4 MB goal, 0 MB stacks, 0 MB globals, 4 P
gc 27 @0.591s 81%: 19+0.17+0.004 ms clock, 77+0.084/0.091/0.10+0.016 ms cpu, 4->4->1 MB, 4 MB goal, 0 MB stacks, 0 MB globals, 4 P
gc 28 @0.611s 81%: 19+0.16+0.016 ms clock, 77+0.089/0.083/0.10+0.066 ms cpu, 4->4->1 MB, 4 MB goal, 0 MB stacks, 0 MB globals, 4 P
gc 29 @0.631s 79%: 19+20+0.003 ms clock, 77+0/0.16/2.1+0.014 ms cpu, 5->6->3 MB, 6 MB goal, 0 MB stacks, 0 MB globals, 4 P
gc 30 @0.671s 80%: 19+0.13+0.013 ms clock, 77+0.096/0.084/0.10+0.055 ms cpu, 5->5->2 MB, 6 MB goal, 0 MB stacks, 0 MB globals, 4 P
gc 31 @0.691s 78%: 19+19+0.015 ms clock, 77+0.060/0.30/0.17+0.060 ms cpu, 4->10->8 MB, 4 MB goal, 0 MB stacks, 0 MB globals, 4 P
```

The above text is a GC trace for `TestDecodeMemoryConsumption` in the `image/gif` package. Note the _very_ high GC stop-the-world times for the transition to the mark phase. This is time not spent in the pause, but actually trying to stop the world:

<img width="2981" alt="Screen Shot 2022-04-21 at 3 11 05 PM" src="https://user-images.githubusercontent.com/1248668/164556170-1305f80d-0907-4b09-8c06-24ab9ce35617.png">

Typically the runtime is waiting on one P, and [it goes to sleep on a note for 100µs](https://cs.opensource.google/go/go/+/master:src/runtime/proc.go;l=1223?q=stopTheWorldWithSema&ss=go%2Fgo). If undisturbed, it takes between 10 and 20 ms to actually wake up. But that should be OK, because it's woken up early if the last P to stop actually stops. Except that we have thread-level sleeps in other parts of the runtime that have the same latency! For example, [`runqgrab` might call `usleep(3)`](https://cs.opensource.google/go/go/+/master:src/runtime/proc.go;l=5908;bpv=1?q=runqgrab&ss=go%2Fgo), but that too takes 10-20ms to return. This was a common one I discovered (and confirmed as a source of latency) and there are sure to be more.

The runtime needs to be overhauled for the OpenBSD port to treat sleeps as we would on Windows.

This is closely related to #14183.

**Comment by mknyszek** [comment]
Turns out, the only sleep this matters for is that `runqgrab` sleep. Fixing that seems to resolve this issue.

**Comment by bcmills** [comment]
Could this also (perhaps partially) explain #50189, or are the sleeping paths for `net` separate from the ones involved here?
