### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by mksong-icon** [golang/go#52477]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/icon-project/goloop@v1.2.12?tab=versions
 
### What is your user agent?
 
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36`
  
### Screenshot
 
<img width="341" alt="image" src="https://user-images.githubusercontent.com/41312340/164573158-64a2ec36-179f-4ad6-870b-3f354b92dc72.png">
 
 
 
### What did you do?
 
 Watching versions
 
### What did you expect to see?
 
 Seeing versions which are actually released.
 
### What did you see instead?

Unreleased versions apears

**Comment by seankhliao** [comment]
If a version was accessible at any point in time and pulled through the cache it will show up, even if you later remove it from upstream.
What you can do is increase the version and retract previous ones.
