### ISSUE TITLE
invalid operation: w.real == nil (mismatched types T and untyped nil)

### ISSUE THREAD

**Issue by billcoding** [golang/go#52483]
```
./prog.go:15:15: invalid operation: w.real == nil (mismatched types T and untyped nil)

Go build failed.
```

[Playground Code](https://go.dev/play/p/8e5oO7AQpXv)

**Comment by seankhliao** [comment]
real is not guaranteed to be comparable to nil.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
