### ISSUE TITLE
affected/package: net. "use of closed network connection"

### ISSUE THREAD

**Issue by Icarus9913** [golang/go#52480]
### What version of Go are you using (`go version`)?

<pre>
go 1.18.0
</pre>

### Source codes
```shell

package main

import (
	"net"
	"net/http"
	"time"
)

func main()  {
	listener, err := net.Listen("tcp", net.JoinHostPort("0.0.0.0", "0"))
	if nil!=err{
		panic(err)
	}

	httpServer := &http.Server{}
	go func() {
		err :=httpServer.Serve(listener)
		if nil!=err && err!=http.ErrServerClosed && err!=net.ErrClosed{
			panic(err)
		}
	}()

	time.Sleep(time.Second)
	err = listener.Close()
	if nil!=err{
		panic(err)
	}
	time.Sleep(time.Second)
}

```

### Error
```shell
panic: accept tcp [::]:64309: use of closed network connection

goroutine 6 [running]:
main.main.func1()
        .../main.go:19 +0xb3
created by main.main
       .../main.go:16 +0x15a
exit status 2

```

### Question：

Is that a right situation with this panic? Why I close the listener the server got one error that not belong 'http.ErrServerClosed' ?
And What is the right way to handle this error?

**Comment by qiulaidongfeng** [comment]
What version of Go are you using (go version)?

> go1.18.1 windows/amd64

Question：
Will reproduce #52480 the problems mentioned

**Comment by ZekeLu** [comment]
@Icarus9913 Did you mean to call `func (srv *Server) Shutdown(ctx context.Context) error`?

```diff
- err = listener.Close()
+ err = httpServer.Shutdown(context.Background())
```

**Comment by Icarus9913** [comment]
@ZekeLu It's same. Deep into `Shutdown` you will find it calls `listener.Close()`

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
