### ISSUE TITLE
net/http:  pollWait panic on android11/arm64

### ISSUE THREAD

**Issue by wangcheng711** [golang/go#52481]
111

**Comment by mengzhuo** [comment]
cc @changkun @thanm

**Comment by wangcheng711** [comment]
I recompile the program, upload to the phone, the first run, and then access the gin-web interface, it is easy to panic, usually the first time no problem, no problem after. 

set GOARCH=arm64
set CGO_ENABLED=1
set GOOS=android
set CC=C:\Users\admin\AppData\Local\Android\Sdk\ndk\23.1.7779620\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android30-clang.cmd
set CXX=C:\Users\admin\AppData\Local\Android\Sdk\ndk\23.1.7779620\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android30-clang++.cmd
go build -v -ldflags "-w -s"
