### ISSUE TITLE
x/pkgsite:  why non-struct variable cannot support annotate?

### ISSUE THREAD

**Issue by iiimapidan** [golang/go#52484]
when I use embed for complier static resource into go binary ,i  found i need use  comment to implement it. It seems not be readability.

### Screenshot

![image](https://user-images.githubusercontent.com/100209029/164680549-2b77d4dc-75a0-4417-9844-6be999e72bef.png)

![image](https://user-images.githubusercontent.com/100209029/164680609-80c9a498-d84b-4481-9e88-59082c5f71cf.png)

### What did you expect to see?

why non-struct variable cannot support annotate?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
