### ISSUE TITLE
x/tools/gopls: support using modules in go.work that are outside the workspace directory

### ISSUE THREAD

**Issue by findleyr** [golang/go#52488]
Right now there is a fair bit of logic in gopls that relies on having a workspace directory that is a parent of all active modules (for e.g. checking workspace containment).

This is an umbrella issue tracking support for `go.work` files that use modules in arbitrary directories.  We have some related issues (e.g. #48929), but no overarching issue for this feature.

**Comment by findleyr** [comment]
I believe this should have been fixed by https://go.dev/cl/400822, but we need more testing.

**Comment by hyangah** [comment]
Verified gopls recognizes GOWORK=/tmp/go.work. However, changes to the file content (e.g. add/remove modules to the workspace defined by this file) are not yet recognized - gopls is watching only changes in files in the workspace currently.

**Comment by findleyr** [comment]
Thanks, filed https://go.dev/issue/53631 for that. I'll close this issue.
