### ISSUE TITLE
x/sys: stdio handle inheritance getting changed after dynamic loading of a DLL

### ISSUE THREAD

**Issue by aayush13890** [golang/go#52498]
This issue was first reported against golang/go repo and was addressed in Go 1.17.
Issue: https://github.com/golang/go/issues/44876
Fix: https://github.com/golang/go/commit/4c8f48ed4f3db0e3ba376e6b7a261d26b41d8dd0

But this change is not part of golang/sys [code](https://github.com/golang/sys/blob/master/windows/syscall_windows.go#L626). Changes in the above commit need to be made in golang/sys repo as well. Thanks!

**Comment by thanm** [comment]
Sounds like a good change to make. 

Want to send a CL?

**Comment by alexbrainman** [comment]
I doubt anyone uses `golang.org/x/sys/windows.Stdin`. People use either `os.Stdin` or `syscall.Stdin`.

But sure. We should change `golang.org/x/sys/windows` code too.

@aayush13890 do you want to send a change?

Here is how to contribute

https://go.dev/doc/contribute

Alex

**Comment by rkennedy** [comment]
I agree that few people actually use _that_ `Stdin`. However, the `init` function will still always initialize those variables, which has the _process-wide_ side effect of clearing the inheritance flags from the standard handles, so it's definitely a bug that needs fixing.

On the other hand, if it's really the case that nobody uses the identifiers from x/sys, then perhaps the best action would be to remove the declarations entirely?

**Comment by aayush13890** [comment]
@alexbrainman @thanm any suggestions on the @rkennedy 's question above? I will go through the steps to contribute in the meanwhile. Thanks!

**Comment by alexbrainman** [comment]
> @alexbrainman @thanm any suggestions on the @rkennedy 's question above?

@aayush13890 if you refer to

> the best action would be to remove the declarations entirely

I don't think we can remove the declarations. We always try not to break people code. So even if one person is using this code, we should try and fix them.

Alex

**Comment by aayush13890** [comment]
@alexbrainman  @rkennedy @thanm I have submitted the CL. I am making a change to this repo for the first time. Please let me know if I am missing anything. Also, how do I run all the tests inside https://github.com/golang/sys/tree/master/windows?

I tried running:

# pwd
/root/Aayush/go-repos/go-sys/sys

# ls
AUTHORS  codereview.cfg  CONTRIBUTING.md  CONTRIBUTORS  cpu  execabs  go.mod  internal  LICENSE  PATENTS  plan9  README.md  unix  windows

# go test ./...
warning: GOPATH set to GOROOT (/usr/local/go) has no effect
ok      golang.org/x/sys/cpu    (cached)
ok      golang.org/x/sys/execabs        0.016s
ok      golang.org/x/sys/internal/unsafeheader  (cached)
ok      golang.org/x/sys/unix   0.612s
ok      golang.org/x/sys/unix/internal/mkmerge  (cached)
?       golang.org/x/sys/windows/mkwinsyscall   [no test files]
