### ISSUE TITLE
time: second precision timezone format not documented

### ISSUE THREAD

**Issue by alicebob** [golang/go#52516]
`go doc time` says:

```
    Numeric time zone offsets format as follows:

        "-0700"  ±hhmm
        "-07:00" ±hh:mm
        "-07"    ±hh
```

However, timezones with second precision ("-07:00:00" and "-070000") are also supported: https://github.com/golang/go/blob/master/src/time/format.go#L151

Could these be added to the documentation? Took me a while to figure out why my pre-1900 date with LMT timezone parsed correctly.

**Comment by ianlancetaylor** [comment]
Thanks for the report.  Want to send a patch?
