### ISSUE TITLE
debug/dwarf: slice bounds out of range in Ranges (sic)

### ISSUE THREAD

**Issue by catenacyber** [golang/go#52528]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/catena/Library/Caches/go-build"
GOENV="/Users/catena/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/catena/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/catena/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/catena/go/src/github.com/catenacyber/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pp/dc1dtf9x2js3v0jx_m010nqr0000gn/T/go-build4237848497=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.17.6 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.17.6
uname -v: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
lldb --version: lldb-1316.0.9.41
Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
gdb --version: GNU gdb (GDB) 9.1
</pre></details>

### What did you do?

Run https://go.dev/play/p/BcTdyPIdHkm?v=gotip

### What did you expect to see?

The program finishing and printing Hello

### What did you see instead?

```
panic: runtime error: slice bounds out of range [9:1]

goroutine 1 [running]:
debug/dwarf.(*Data).dwarf2Ranges(0xc0000c2000?, 0xb?, 0x0?, 0x0?, {0x0?, 0x4c7a48?, 0x56c2e8?})
	/usr/local/go-faketime/src/debug/dwarf/entry.go:1106 +0x2b9
debug/dwarf.(*Data).Ranges(0xc0000c2000, 0xc0000a0300)
	/usr/local/go-faketime/src/debug/dwarf/entry.go:1068 +0x2b7
main.main()
	/tmp/sandbox3267791668/prog.go:14 +0x1ca

Program exited.
```

Found by https://github.com/catenacyber/ngolo-fuzzing on oss-fuzz 
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46789

cc @thanm

**Comment by qiulaidongfeng** [comment]
您使用的是什么版本的 Go（go 版本）？

go1.18.1 windows/amd64

问题：
会重现https://github.com/golang/go/issues/52480提到的问题

**Comment by qiulaidongfeng** [comment]
What version of Go are you using (go version)?

go1.18.1 windows/amd64

Question：
Will reproduce #52480 the problems mentioned

**Comment by qiulaidongfeng** [comment]
What version of Go are you using (go version)?

go1.18.1 windows/amd64

Question：
Will reproduce #52528 the problems mentioned

**Comment by qiulaidongfeng** [comment]
"src / debug / dwarf / entry.go:386" ,seems to be the problem

**Comment by thanm** [comment]
I'll take a look.

**Comment by catenacyber** [comment]
This seems to have been silently fixed 

Does no longer fail on gotip but stil fails on go 1.19

**Comment by ianlancetaylor** [comment]
Presumably fixed by https://go.dev/cl/434936 for #53529.

We aren't going to backport this kind of fix, so closing as a dup.
