### ISSUE TITLE
go/doc/comment: list inside comment that start and end with "/* */" does not formatted

### ISSUE THREAD

**Issue by shuLhan** [golang/go#52539]
Following #51082, I think there is a bug with list formatting when comment start and end with `/*`...`*/` in the current tip branch, or maybe a missing exception in the proposal since the spec still allow comment start/end with `/*`...`*/`.

### What version of Go are you using (`go version`)?

The latest tip from playground.

### Does this issue reproduce with the latest release?

No, only tip.

### What did you do?

See https://go.dev/play/p/WfIdp2WQphD?v=gotip

### What did you expect to see?

The list on the comment section reformated, as below

```
/*
testCommentSlashStart method with header and list

# Header

Here is the list,

  - a
  - b
*/
```

### What did you see instead?

```
/*
testCommentSlashStart method with header and list

# Header

Here is the list,

* a
* b
*/
func testCommentSlashStart() {}
```

**Comment by thanm** [comment]
@rsc

**Comment by heschi** [comment]
ping: this is a release blocker that hasn't been updated in a while.

**Comment by ianlancetaylor** [comment]
According to the rules at https://github.com/golang/proposal/blob/master/design/51082-godocfmt.md, a list is only recognized as a series of indented lines.  In this example, the list items are not indented.  Closing because this is working as expected.  Please comment if you disagree.
