### ISSUE TITLE
x/text/cmd/gotext: gotext does not work with generics

### ISSUE THREAD

**Issue by tux21b** [golang/go#52553]
The following minimal example produces an error with Go 1.18.1:

```
package main

import (
	"fmt"

	"golang.org/x/text/language"
	"golang.org/x/text/message"
)

func Print[T any](s T) {
	fmt.Println(s)
}

func main() {
	p := message.NewPrinter(language.English)
	Print(p.Sprintf("Hello World"))
}
```

Stacktrace:

```
❯ go run golang.org/x/text/cmd/gotext extract       
panic: T

goroutine 661 [running]:
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001659e10, {0x8d5e28?, 0xc007d56fc0?}, 0x0)
        /home/christoph/go/pkg/mod/golang.org/x/tools@v0.1.10/go/ssa/methods.go:237 +0x5b1
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001659e10, {0x8d5e00?, 0xc0045f6a50?}, 0x0)
        /home/christoph/go/pkg/mod/golang.org/x/tools@v0.1.10/go/ssa/methods.go:233 +0x708
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001659e10, {0x8d5d88?, 0xc0045fae00?}, 0x0)
        /home/christoph/go/pkg/mod/golang.org/x/tools@v0.1.10/go/ssa/methods.go:209 +0x448
golang.org/x/tools/go/ssa.(*Program).needMethodsOf(0xc001659e10, {0x8d5d88?, 0xc0045fae00?})
        /home/christoph/go/pkg/mod/golang.org/x/tools@v0.1.10/go/ssa/methods.go:145 +0x70
golang.org/x/tools/go/ssa.(*Package).build(0xc008ef0960)
        /home/christoph/go/pkg/mod/golang.org/x/tools@v0.1.10/go/ssa/builder.go:2284 +0x111
sync.(*Once).doSlow(0x628f00?, 0xc0026fb080?)
        /usr/lib/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
        /usr/lib/go/src/sync/once.go:59
golang.org/x/tools/go/ssa.(*Package).Build(...)
        /home/christoph/go/pkg/mod/golang.org/x/tools@v0.1.10/go/ssa/builder.go:2272
golang.org/x/tools/go/ssa.(*Program).Build.func1(0x4d?)
        /home/christoph/go/pkg/mod/golang.org/x/tools@v0.1.10/go/ssa/builder.go:2256 +0x4c
created by golang.org/x/tools/go/ssa.(*Program).Build
        /home/christoph/go/pkg/mod/golang.org/x/tools@v0.1.10/go/ssa/builder.go:2255 +0x19c
exit status 2
```

The error itself seems to be related to this issue https://github.com/golang/go/issues/48525. Please note that in order to trigger the error, one must manually update x/tools, otherwise another error is triggered. See https://github.com/golang/go/issues/52552.

PS: and please ignore the misuse of generics in this example. I just needed some code that uses generics.

**Comment by cagedmantis** [comment]
Also see #50558

**Comment by zpavlinovic** [comment]
Is this issue still present? It should go away with one of the newer versions of tools: https://github.com/golang/text/blob/master/go.mod

**Comment by tux21b** [comment]
It still does not work with the latest released version of /x/text (v0.3.7) and /x/tools (v0.1.10).

Updating /x/text to the latest commit on master (v0.3.8-0.20220509174342-b4bca84b0361, which also updates tools to v0.1.11-0.20220504162446-54c7ba520b92) seems to solve the problem. Can we get another release before closing this issue?

**Comment by esote** [comment]
> Can we get another release before closing this issue?

@tux21b `x/text` v0.3.8 and v0.4.0 have been released since your comment, is this issue good to close?

**Comment by tux21b** [comment]
Ah, yes. Thanks for asking @esote. Everything is working fine now!
