### ISSUE TITLE
go.dev: redirected pages are returning invalid TLS responses

### ISSUE THREAD

**Issue by johanbrandhorst** [golang/go#52551]
### What is the URL of the page with the issue?

https://play.go.dev/

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0

### Screenshot

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/6604151/165142952-24c6128a-d7ce-41c8-bffe-0d4552df8647.png">

### What did you do?

Tried to load the playground

### What did you expect to see?

A working playground

### What did you see instead?

A browser error

**Comment by findleyr** [comment]
CC @rsc @jamalc 

Looks like https://go.dev/play works fine.

**Comment by findleyr** [comment]
https://blog.go.dev suffers the same problem, so I guess it is happening for all redirected URLs.

**Comment by dmitshur** [comment]
Has `play.go.dev` worked before and is it intended to work? I've only seen:
- https://play.golang.org (old URL, notably subdomain of golang.org)
- https://go.dev/play (new URL after [tidying Go websites](https://go.dev/blog/tidy-web), under go.dev domain)

**Comment by findleyr** [comment]
Based on the following link I assumed it was meant to work, but I can't say if it ever did :)
 https://cs.opensource.google/go/x/website/+/master:cmd/golangorg/server.go;l=185;drc=7a60f303d8c4f3c0c7daab7b2175a6ff4f692698

**Comment by jamalc** [comment]
Only learn.go.dev was correctly mapped in our DNS config so the redirect for the other domains never worked. I've updated the table. It might take an hour or so before everything is working as expected.

**Comment by rsc** [comment]
These are working now. Sorry for not getting them right from the start, and thanks @jamalc!
