### ISSUE TITLE
x/pkgsite: Override licensecheck logic

### ISSUE THREAD

**Issue by spakin** [golang/go#52554]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/lanl/clp

### What is your user agent?

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

### Screenshot

![clp](https://user-images.githubusercontent.com/650041/165153610-ef9e1044-c77a-4a4c-b4b4-2c6b2d50b189.png)

### What did you do?

Navigated to https://pkg.go.dev/github.com/lanl/clp

### What did you expect to see?

Documentation

### What did you see instead?

A notice that "Documentation not displayed due to license restrictions."

### Commentary

[clp](https://pkg.go.dev/github.com/lanl/clp) is licensed under what's really a BSD-3-Clause license.  Unfortunately, my institution dictates specific wording that's just different enough from the stock wording that licensecheck reports too low confidence for pkg.go.dev to show the documentation:
```
57.8% of text covered by licenses:
BSD-3-Clause at [45:93] IsURL=true
BSD-3-Clause at [1176:2684] IsURL=false
```
Is there some way a license file can indicate that it really is some particular license, despite what the checker is able to discern?  As you can see, I added the BSD-3-Clause URL to clp's [`LICENSE.md`](https://github.com/lanl/clp/blob/23dd491c65c4a4af896a4e28ee3f8db7ee2d32a4/LICENSE.md) file, but this merely increases licensecheck's confidence rather than forcing it to honor the specified license.

If there's no such feature, let's treat this as a feature request.

(This issue is somewhat related to #49155.)

**Comment by jba** [comment]
> Is there some way a license file can indicate that it really is some particular license, despite what the checker is able to discern? 

IANAL, but you can see how that raises issues. "This is a BSD-3 license, even though it clearly states that you cannot redistribute our software." How would a court rule on that? For the same reason, we do not look at SPDX identifiers.

If your wording is not too divergent or idiosyncratic, consider a PR that modifies https://github.com/google/licensecheck/blob/main/licenses/BSD.lre. That way everyone can learn about your variant.

As a fallback, we may be able to add it to https://go.googlesource.com/pkgsite/+/refs/heads/master/internal/licenses/exceptions.

**Comment by spakin** [comment]
> IANAL, but you can see how that raises issues. "This is a BSD-3 license, even though it clearly states that you cannot redistribute our software." How would a court rule on that? For the same reason, we do not look at SPDX identifiers.

Ah, good point.

Let me therefore ask a more technical question: What threshold does pkg.go.dev require for a license to be considered a match?  I'll use that to see if a modest change to [`BSD.ire` ](https://github.com/google/licensecheck/blob/main/licenses/BSD.lre) will accept my institution's variant wording.  As you can see from my initial post, I'm currently at 57.8%.  If I need to get to 60%, that's one thing; if I need to get to 95%, that's a tougher challenge.

**Comment by jba** [comment]
Each License Regular Expression (LRE) is binary: it either matches some text, or it doesn't.

75% of the file must be matched by some LRE. (Some license files are concatenations of multiple licenses.)

Your LICENSE.md sort of looks like a BSD-3 license; there's not a lot of extra text. I would expect it to be close to the BSD-3 LRE. I didn't look carefully enough to see where it diverges. If you can point out the differences to me, perhaps we can see how to tweak the LRE together.

**Comment by jba** [comment]
Sorry I haven't replied; I'm attending a multi-day meeting. I hope to revisit this Friday or next Monday.

**Comment by spakin** [comment]
It looks like I may be allowed by my institution to move the troublesome paragraph from `LICENSE.md` to `README.md`.  I believe that will solve the problem in the specific case of [`github.com/lanl/clp`](https://github.com/lanl/clp).

It would still be helpful to others releasing software paid for in part by the US Government if the license checker knew to ignore text that looks like a US Government rights clause.  Does that sound like a practical feature addition?

**Comment by jba** [comment]
I'm sorry I haven't had the bandwidth to pursue this. Although I agree on the general solution, it would be much better for all at this point if you moved the paragraph.

**Comment by spakin** [comment]
Done.
