### ISSUE TITLE
net/http.NewRequest panics on nil body

### ISSUE THREAD

**Issue by brandon-ja** [golang/go#52578]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="//Users/myusername/go/bin"
GOCACHE="/Users/myusername/Library/Caches/go-build"
GOENV="/Users/myusername/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/myusername/go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/myusername/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/myusername/src/weavelab.xyz/diff-generator/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sz/5rthrj0j2pz0xqwsf52xxs8m0000gq/T/go-build668136691=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.18.1 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.18.1
uname -v: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
ProductName:	macOS
ProductVersion:	12.3.1
BuildVersion:	21E258
lldb --version: lldb-1316.0.9.41
Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
</pre></details>

### What did you do?

```go
package main

import (
    "bytes"
    "log"
    "net/http"
)

func main() {
    var bodyBuffer *bytes.Buffer
    _, err := http.NewRequest("GET", "test", bodyBuffer)
    if err != nil {
        log.Fatalln("Err: ", err)
    }

    log.Println("Success")
}
```

### What did you expect to see?
Running this code should log "Success".
This is confirmed by the following code which functions as I would expect.

```go
package main

import (
    "log"
    "net/http"
)

func main() {
    _, err := http.NewRequest("GET", "test", nil)
    if err != nil {
        log.Fatalln("Err: ", err)
    }

    log.Println("Success")
}
```

### What did you see instead?
Running the provided example results in a panic: runtime error due to a `nil` pointer dereference.

```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x111eb84]

goroutine 1 [running]:
bytes.(*Buffer).Len(...)
	/usr/local/Cellar/go/1.18.1/libexec/src/bytes/buffer.go:73
net/http.NewRequestWithContext({0x11923e8?, 0xc0000b2008}, {0x115c94b?, 0xc0000021a0?}, {0x115cb6d?, 0x4?}, {0x1191780, 0x0?})
	/usr/local/Cellar/go/1.18.1/libexec/src/net/http/request.go:893 +0x564
net/http.NewRequest(...)
	/usr/local/Cellar/go/1.18.1/libexec/src/net/http/request.go:831
main.main()
	/Users/myusername/src/net_http_bug/main.go:11 +0x4e
exit status 2
```

**Comment by cespare** [comment]
@brandon-ja if you provide a `*bytes.Buffer`, it will need to be valid (not nil).

It may be that you are getting confused by the difference between a nil `*bytes.Buffer` and a nil `io.Reader`. See https://go.dev/doc/faq#nil_error.

Closing as there is no issue here that I can see.
