### ISSUE TITLE
build: failure to build with riscv64 and go-bootstrap

### ISSUE THREAD

**Issue by paralin** [golang/go#52583]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 linux/amd64
</pre>

### Description

Using the go-bootstrap-1.4.x C-based Go compiler to bootstrap Go with build.bash,

When the target GOARCH is set to riscv64:

```
Building Go toolchain1 using go-1.4-bootstrap-20171003.
src/cmd/compile/internal/ssa/rewriteRISCV64.go:4814
invalid operation: y << x (shift count type int64, must be unsigned integer)
```

The code attempts to unset GOARCH before calling the bootstrap compiler, since the bootstrap compiler only needs to build for the host OS during this stage of the bootstrap. In later bootstrap passes, support for the actual target arch is usually compiled in.

However, the environment variable is unset /after/ calling bootstrapRewriteFile, which causes the issue.

By unsetting GOARCH /before/ calling bootstrapRewriteFile, the build.bash script completes successfully.

Fixed by PR: https://go-review.googlesource.com/c/go/+/400376

**Comment by ianlancetaylor** [comment]
CC @4a6f656c

**Comment by mengzhuo** [comment]
BTW, I can't reproduce with go 1.16
`GOARCH=riscv64 GOOS=linux ./bootstrap.sh`

**Comment by paralin** [comment]
@mengzhuo the issue appears only when bootstrapping with go 1.4.x.

**Comment by paralin** [comment]
It's a simple fix, not sure what more investigation is needed. The buildcfg in that bootstrap step does not need the GOARCH environment variables to be set. It was a mistake in the code to call buildcfg before unsetting those environment variables. The original intent of the code was to have those unset during this portion of the bootstrap process.

This fixes a build failure in Buildroot and is currently included as a .patch in the tree there. We build Go with the go1.4.x go-bootstrap as per this: https://go.dev/doc/install/source#bootstrapFromSource

Please review when possible so we can upstream this patch. Thanks.

**Comment by mengzhuo** [comment]
cc @bcmills

**Comment by paralin** [comment]
Updated & confirmed that the build fails w/o the patch & is fixed with it.

Determined why & updated commit message:

 - buildtool.go:198: calls bootstrapRewriteFile(src)
 - bootstrapRewriteFile: buildtool.go:283 calls:
 - isUnneededSSARewriteFile: checks os.Getenv("GOARCH")
 - isUnneededSSARewriteFile: returns "", false
 - bootstrapRewriteFile: calls bootstrapFixImports
 - boostrapFixImports: generates code go1.4 cannot compile

By unsetting GOARCH here we are causing isUnneededSSARewriteFile to return true
instead of false which generates stub functions bypassing the incompatible code.

buildtool.go:272 in isUnneededSSARewriteFile is the only place the GOARCH
environment variable is checked apart from the xinit function.

This patch simply moves the os.Setenv("GOARCH", "") to before the block of code
where bootstrapRewriteFile is called.
