### ISSUE TITLE
x/playground: pressing run or share on lynx gives a "bad html" error

### ISSUE THREAD

**Issue by mindfarm** [golang/go#52585]
This was reported and confirmed on IRC

```
13:46 < Andrew> While visiting and putting code (playing)
                with play.golang.org, lynx says bad html:
                no form action defined, while pressing run
                or share
13:53 < b0nn> Yeah - I get it too; you can report it as an
              issue on the go github page I think
13:57 < Andrew> problem is (1) submitting issues/prs on
                github requires nonfree javascript and a
                modern web browser and (2) I don
13:57 < Andrew> 't have one... 
```
The problem is that accessing the play.golang.org website using lynx (command line browser) produces warnings and errors

**Comment by dieselburner** [comment]
My vision is that whoever nowadays uses lynx is hardcore enough to fix the code (or implement new) by them own.

Sorry, but for developers it's a waste of time - this browser is used by [0.5%](https://www.nngroup.com/articles/browser-usage-statistics/) of population. Oh wait, article was written in 1997.

**Comment by mvdan** [comment]
If the browser is right that the HTML is incorrect, I think it's fair to try to fix bugs like that when they are reported. I don't expect the developers to test on every browser under the sun continuously, but if valid bugs are reported, I don't see why they can't be fixed if someone sends a patch.

**Comment by seankhliao** [comment]
The playground API accepts json, not a html form. I also don't see how the run results would be streamed to a browser not running js without significant rework of both front and backend.

**Comment by mindfarm** [comment]
I've tried with a number of other command line browsers, but wasn't able to get the Run button to activate
Tried
* [lynx](https://lynx.invisible-island.net/)
* [links](http://links.twibright.com/)
* links2
* [w3m](http://w3m.sourceforge.net/)
* [elinks](https://github.com/rkd77/elinks)

I think it's right to close this as javascript does indeed seem to be the stumbling block (I tried to build spidermonkey for elinks so that I could get javascript running in a CLI browser, but to no avail [Run-time dependency tre found: NO] and it's not that important to me)
