### ISSUE TITLE
affected/package: go mod vendor

### ISSUE THREAD

**Issue by yankurniawan** [golang/go#52588]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/yan/codes/go/bin"
GOCACHE="/Users/yan/Library/Caches/go-build"
GOENV="/Users/yan/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/yan/codes/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/yan/codes/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/yan/codes/jigspace/src/bitbucket.org/jigspace/jigpipeline/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/px/4h4hhv3j61ggkqyd1hq975j40000gn/T/go-build1356284066=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
go mod vendor

### What did you expect to see?
success

### What did you see instead?
<pre>
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/dustin/go-humanize@v1.0.0: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/dustin/go-humanize@v1.0.0" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/dustin/go-humanize@v1.0.0/english: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/dustin/go-humanize@v1.0.0/english" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/eknkc/amber@v0.0.0-20171010120322-cdade1c07385: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/eknkc/amber@v0.0.0-20171010120322-cdade1c07385" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/eknkc/amber@v0.0.0-20171010120322-cdade1c07385/amberc: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/eknkc/amber@v0.0.0-20171010120322-cdade1c07385/amberc" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/eknkc/amber@v0.0.0-20171010120322-cdade1c07385/parser: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/eknkc/amber@v0.0.0-20171010120322-cdade1c07385/parser" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/jmespath/go-jmespath@v0.0.0-20180206201540-c2b33e8439af: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/jmespath/go-jmespath@v0.0.0-20180206201540-c2b33e8439af" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/jmespath/go-jmespath@v0.0.0-20180206201540-c2b33e8439af/cmd/jpgo: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/jmespath/go-jmespath@v0.0.0-20180206201540-c2b33e8439af/cmd/jpgo" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/jmespath/go-jmespath@v0.0.0-20180206201540-c2b33e8439af/fuzz: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/jmespath/go-jmespath@v0.0.0-20180206201540-c2b33e8439af/fuzz" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/joho/godotenv@v1.3.0: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/joho/godotenv@v1.3.0" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/joho/godotenv@v1.3.0/autoload: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/joho/godotenv@v1.3.0/autoload" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/joho/godotenv@v1.3.0/cmd/godotenv: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/joho/godotenv@v1.3.0/cmd/godotenv" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/klauspost/pgzip@v1.2.5: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/klauspost/pgzip@v1.2.5" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/mattn/go-zglob@v0.0.2-0.20191112051448-a8912a37f9e7: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/mattn/go-zglob@v0.0.2-0.20191112051448-a8912a37f9e7" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/mattn/go-zglob@v0.0.2-0.20191112051448-a8912a37f9e7/cmd/zglob: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/mattn/go-zglob@v0.0.2-0.20191112051448-a8912a37f9e7/cmd/zglob" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/mattn/go-zglob@v0.0.2-0.20191112051448-a8912a37f9e7/fastwalk: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/mattn/go-zglob@v0.0.2-0.20191112051448-a8912a37f9e7/fastwalk" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/mattn/go-zglob@v0.0.3: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/mattn/go-zglob@v0.0.3" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/mattn/go-zglob@v0.0.3/cmd/zglob: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/mattn/go-zglob@v0.0.3/cmd/zglob" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/mattn/go-zglob@v0.0.3/fastwalk: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/mattn/go-zglob@v0.0.3/fastwalk" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/nfnt/resize@v0.0.0-20180221191011-83c6a9932646: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/nfnt/resize@v0.0.0-20180221191011-83c6a9932646" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/pkg/errors@v0.9.1: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/pkg/errors@v0.9.1" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/pmezard/go-difflib@v1.0.0/difflib: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/pmezard/go-difflib@v1.0.0/difflib" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/satori/go.uuid@v1.2.1-0.20181028125025-b2ce2384e17b: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/satori/go.uuid@v1.2.1-0.20181028125025-b2ce2384e17b" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/tylerb/graceful@v1.2.15: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/tylerb/graceful@v1.2.15" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/tylerb/graceful@v1.2.15/tests: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/tylerb/graceful@v1.2.15/tests" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/urfave/negroni@v1.0.0: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/github.com/urfave/negroni@v1.0.0" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/assert.v1@v1.2.1: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/assert.v1@v1.2.1" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1/non-standard/validators: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1/non-standard/validators" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1/translations/en: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1/translations/en" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1/translations/fr: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1/translations/fr" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1/translations/id: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1/translations/id" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1/translations/ja: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1/translations/ja" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1/translations/nl: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1/translations/nl" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1/translations/pt_BR: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1/translations/pt_BR" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1/translations/zh: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1/translations/zh" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1/translations/zh_tw: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/go-playground/validator.v9@v9.29.1/translations/zh_tw" should not have @version
bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/unrolled/render.v1@v1.0.0: import path "bitbucket.org/jigspace/jigpipeline/lib/go/pkg/mod/gopkg.in/unrolled/render.v1@v1.0.0" should not have @version
</pre>

**Comment by yankurniawan** [comment]
It worked with 1.17.9

**Comment by seankhliao** [comment]
should the entire lib/go directory tree exist? it looks like you have a copy of the module cache in there

**Comment by yankurniawan** [comment]
I have tried to remove entire lib/go folder, GOCACHE folder and GOMODCACHE folder, but the errors are still there.

**Comment by yankurniawan** [comment]
I deleted the wrong lib/go directory. After I deleted lib/go folder it works again! Thanks.
