### ISSUE TITLE
x/tools/gopls: Unknown command help

### ISSUE THREAD

**Issue by LeGEC** [golang/go#52598]
#### What did you do?

```
$ gopls help version
gopls: Unknown command help

...

Usage:
  gopls help [<subject>]

...

# check exit code:
$ echo $?
2
```

#### What did you expect to see?

a help message for the selected topic, or a list of topics if topic doesn't exist

#### What did you see instead?

an error message stating "Unknown command help", along with a help message inviting me to type `gopls help [<subject>]`

or a message inidcating the correct command to type for a `<subject>` (probably `gopls <subject> -h` ?)

#### Build info

```
golang.org/x/tools/gopls v0.8.3
    golang.org/x/tools/gopls@v0.8.3 h1:Mxm94ix8oSARQ6svioO6SxKEYWT/VCP54/448LOHzrk=
    ...
go: go1.18.1
```

**Comment by hyangah** [comment]
cc @adonovan
