### ISSUE TITLE
affected/package: fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by binbinshi** [golang/go#52596]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.18.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes ,  i use the new realse 1.18.1 ; 
macos menterey 12.3.1 (21E258) Intel 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xxx/Library/Caches/go-build"
GOENV="/Users/xxx/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xxx/go/pkg/mod"
GONOPROXY="xxx-inc.com"
GONOSUMDB="xxx-inc.com"
GOOS="darwin"
GOPATH="/Users/xxx/go"
GOPRIVATE="git-pd.megvii-inc.com"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Users/xxx/go1.18.1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/xxx/go1.18.1/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xxx/Downloads/xxx/xxx/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/t6/njt55p6n0m524xxkmbmxlnbc0000gn/T/go-build2387888142=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
when i debug on my ide , build is ok but runtime error appear :
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7ff810eaacb6]

runtime stack:
runtime.throw({0x79139ce?, 0xffffffffffffffff?})
	/Users/xxx/go1.18.1/src/runtime/panic.go:992 +0x71
runtime.sigpanic()
	/Users/xxx/go1.18.1/src/runtime/signal_unix.go:802 +0x3a9

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x6e72f70, 0xc000b3f6d8)
	/Users/xxx/go1.18.1/src/runtime/cgocall.go:157 +0x5c fp=0xc000b3f6b0 sp=0xc000b3f678 pc=0x40053bc
github.com/mattn/go-ieproxy._Cfunc_CFNumberGetValue(0x0, 0x9, 0xc0009391d0)
	_cgo_gotypes.go:194 +0x49 fp=0xc000b3f6d8 sp=0xc000b3f6b0 pc=0x5f80829
github.com/mattn/go-ieproxy.cfNumberGetGoInt.func1(0x5f80be9?, 0x6e73010?)

goroutine 40 [syscall]:
os/signal.signal_recv()
	/Users/xxx/go1.18.1/src/runtime/sigqueue.go:148 +0x28
os/signal.loop()
	/Users/xxx/go1.18.1/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	/Users/xxx/go1.18.1/src/os/signal/signal.go:151 +0x2a

goroutine 42 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000206100)
	/Users/xxx/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xad
created by go.opencensus.io/stats/view.init.0
	/Users/xxx/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x8d

### What did you expect to see?

fix it and can run debug on ide

**Comment by ianlancetaylor** [comment]
This looks like your Go program called a C function that made a NULL dereference.

Is there something that makes you think that this is a problem with Go?

**Comment by binbinshi** [comment]
everything is ok in go 1.17.1 ,   after update to go1.18.1 when i restart ,  see the error ;  
ubuntu16.04 can normal start and build ;
go build is ok ,  i can see the build exectable binaray

**Comment by binbinshi** [comment]
my project mod  github.com/mattn/go-ieproxy not the latest  version， modify to  0.0.6 , everything is ok
