### ISSUE TITLE
why runtime had to wait for main_init_done in the scenario of C calls go?

### ISSUE THREAD

**Issue by wangfakang** [golang/go#52601]
In some cases we need to C calls Go to wakeup the init of Go, but now the Go runtime requires C calls Go until after Go initialization is completed. 

https://github.com/golang/go/blob/master/src/runtime/proc.go#L232-L241

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker for questions.  You will usually get a better and faster answer on a forum.  See https://go.dev/wiki/Questions.  Thanks.

It's true that it doesn't work for a Go `init` function to call a C function that calls a Go function.  That seems hard to fix.
