### ISSUE TITLE
cmd/cgo: inconsistent compiler behaviour when compiling a C.struct

### ISSUE THREAD

**Issue by twystd** [golang/go#52611]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/w4/4zn787bj71j0cs7h24l60xsw0000gn/T/go-build2072774135=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

When building a shared-lib/DLL with `cgo` it fails to compile with the following error:
```
> go build -trimpath -buildmode=c-shared  -o ../lib/libuhppoted.so ./...

profile.ID undefined (type *_Ctype_struct_TimeProfile has no field or method ID)
```
if the struct `C.struct_TimeProfile` is defined in _main.go_ and is passed as an argument to a function in another file in the the same (`main`) package. However, it compiles successfully if:
- the Go _func_ using `C.struct_TimeProfile` is in `main.go`
- or the Go _func_ using `C.struct_TimeProfile` is in in an entirely different Go file
- or the `C.struct_TimeProfile` is unpacked to a Go struct in main.go

Other:
- `C.struct_TimeProfile` is identical (other than names) to another _struct_ (`C.struct_Card)` that does not show the same behaviour
- Renaming structs, fields and files (on the possibility that TimeProfile might just be reserved) does not change the behaviour

I've attached tar.gz files with minimal examples that fail and succeed.

### What did you expect to see?
_Compiles without error irrespective of where the function is located_

### What did you see instead?
_Compiles with the following error unless the func is a specific file:_
```
dll/time_profiles.go:22:10: profile.profile_id undefined (type *_Ctype_struct_TimeProfile has no field or method profile_id)
```

[fails.tar.gz](https://github.com/golang/go/files/8586941/fails.tar.gz)
[succeeds.tar.gz](https://github.com/golang/go/files/8586942/succeeds.tar.gz)

**Comment by twystd** [comment]
Additional information - can confirm that I've been able to reproduce the problem on:

1. A newly created VPS with:
   - Ubuntu 22.04 x64
   - go version go1.18.1 linux/amd64

2. A newly created VPS with:
   - Windows 2022 Standard
   - go version go1.18.1 windows/amd64
   - gcc (tdm64-1) 10.3.0

**Comment by kkHAIKE** [comment]
root cause is the files order, last file `time_profiles.go` **need the type** override `main.go` **define the type**(cgo tool use global var typedef), so i guess can't ref type cross file in cgo(satisfy the current go file)

**Comment by twystd** [comment]
Oh, right .. if I build with the source files specified individually and _main.go_ as the last file it compiles ok. 

`go build -trimpath -buildmode=c-shared -o ./lib/libuhppoted.so ./...` seemingly compiles the files in (reverse ?) alphabetical order (or presumably directory order) which is why _cards.go_ compiles just fine but _time_profiles.go_ does not. Not having come across this problem before I had always assumed the compiler/linker was automatically resolving ordering issues.

Thanks - I'll dig a bit into the options to see if there's an alternative to manually specifying the files, but this issue can be closed.

**Comment by twystd** [comment]
Ref. [go/issues/38186: cmd/compile: builds not reproducible if input file order is different](https://github.com/golang/go/issues/38186#issuecomment-606940430)

> In short, the order in which files are presented to the compiler matters. It is the responsibility of the build tool to provide the files in some reproducible order.
> 
> I am going to close this since the spec is pretty clear. I believe the go tool sorts the filenames for reproducible behavior 
>

**Comment by ianlancetaylor** [comment]
Reopening because I think there is still a bug here.  Renaming the source files in a package should not have a significant effect on the result.  It certainly shouldn't change between a successful build and a failing build.

**Comment by twystd** [comment]
When phrased like that it does sound like there may be more to it - it was certainly unexpected behaviour and the workaround is inconvenient even in such a small project.

Some additional info - building with the `-work` option the generated `_cgo_gotypes.go` file shows the difference in the generated code:

_succeeded:_
```
type _Ctype_struct_Card struct {
	card_number _Ctype_uint32_t
}

type _Ctype_struct_TimeProfile struct {
	profile_id _Ctype_uint32_t
}
```

_failed:_
```
type _Ctype_struct_Card struct {
	card_number _Ctype_uint32_t
}

//go:notinheap
type _Ctype_struct_TimeProfile struct{}
```

**Comment by twystd** [comment]
Ok, I can confirm that [404497: cmd/cgo: dont override declared struct type](https://go-review.googlesource.com/c/go/+/404497) seems to fix the immediate problem:
```
go version
go version devel go1.19-a4af356075 Fri May 6 20:17:52 2022 +0000 linux/amd64

go build -trimpath -buildmode=c-shared  -o ./lib/libuhppoted.so ./...
go build -trimpath -buildmode=c-shared  -o ./lib/libuhppoted.so dll/cards.go         dll/main.go          dll/time_profiles.go
go build -trimpath -buildmode=c-shared  -o ./lib/libuhppoted.so dll/cards.go         dll/time_profiles.go dll/main.go
go build -trimpath -buildmode=c-shared  -o ./lib/libuhppoted.so dll/main.go          dll/cards.go         dll/time_profiles.go 
go build -trimpath -buildmode=c-shared  -o ./lib/libuhppoted.so dll/main.go          dll/time_profiles.go dll/cards.go
go build -trimpath -buildmode=c-shared  -o ./lib/libuhppoted.so dll/time_profiles.go dll/cards.go         dll/main.go
go build -trimpath -buildmode=c-shared  -o ./lib/libuhppoted.so dll/time_profiles.go dll/main.go          dll/cards.go
```

I'm still a bit puzzled about why `cgo` was generating incorrect an incorrect _struct_ definition in the first place i.e. why did it create:
```
//go:notinheap
type _Ctype_struct_TimeProfile struct{}
```

when the only mention in _time_profiles.go_ is as a _func_ parameter:
```
func getTimeProfile(profile *C.struct_TimeProfile, deviceID uint32, profileID uint32) error {
...
}
```

**Comment by kkHAIKE** [comment]
https://github.com/golang/go/blob/a131fd1313e0056ad094d234c67648409d081b8c/src/cmd/cgo/gcc.go#L2523-L2527

cgo dont know player how to use the struct declaration, in pure c, empty declaration is use for previously-declared struct, most of time use for handle.
