### ISSUE TITLE
x/website/_content/blog: raw markdown on index page

### ISSUE THREAD

**Issue by robpike** [golang/go#52616]
The page

https://go.dev/blog/all

contains a link to "Go at Heroku" by Keith Rarick and Blake Mizerany, but the rendering of the entry contains raw markdown:

```text
[Go at Heroku](https://go.dev/blog/heroku), 21 April 2011
Keith Rarick and Blake Mizerany

_This week’s blog post is written by_ [_Keith Rarick_](http://xph.us/) _and_ [_Blake Mizerany_](http://itsbonus.heroku.com/), _systems engineers at_ [Heroku](http://www.heroku.com/). _In their own words, they "eat, drink, and sleep distributed systems." Here they discuss their experiences using Go._
```

**Comment by gh73962** [comment]
The heroku.article's summary is
"_This week’s blog post is written by_ [_Keith Rarick_](http://xph.us/) _and_ [_Blake Mizerany_](http://itsbonus.heroku.com/), _systems engineers at_ [Heroku](http://www.heroku.com/). _In their own words, they "eat, drink, and sleep distributed systems." Here they discuss their experiences using Go._"

maybe we need correct it to simple string?

**Comment by gh73962** [comment]
The heroku.article's summary is 
```
_This week’s blog post is written by_ [_Keith Rarick_](http://xph.us/) _and_ [_Blake Mizerany_](http://itsbonus.heroku.com/), _systems engineers at_ [Heroku](http://www.heroku.com/). _In their own words, they "eat, drink, and sleep distributed systems." Here they discuss their experiences using Go._
```
maybe we need correct it to simple string?

**Comment by gh73962** [comment]
> The heroku.article's summary is
> 
> ```
> _This week’s blog post is written by_ [_Keith Rarick_](http://xph.us/) _and_ [_Blake Mizerany_](http://itsbonus.heroku.com/), _systems engineers at_ [Heroku](http://www.heroku.com/). _In their own words, they "eat, drink, and sleep distributed systems." Here they discuss their experiences using Go._
> ```
> 
> maybe we need correct it to simple string?

![image](https://user-images.githubusercontent.com/31007143/165926132-e98f7f8e-84c8-4aae-a295-f644820fe231.png)
