### ISSUE TITLE
proposal: regexp: support \C to match a single byte

### ISSUE THREAD

**Issue by bxlxx** [golang/go#52632]
I wonder if plan to support \C to match a single byte?

**Comment by ianlancetaylor** [comment]
Are there any other regular expression variants that support that?

**Comment by bxlxx** [comment]
I didn't see any other regular expression variants of golang, I read the use of \C in the syntax of re2.

**Comment by rsc** [comment]
There are no plans, because it requires operating one byte at a time, and the regexp implementation is fundamentally rune-at-a-time.

**Comment by rsc** [comment]
This proposal has been added to the [active column](https://golang.org/s/proposal-status#active) of the proposals project
and will now be reviewed at the weekly proposal review meetings.
— rsc for the proposal review group

**Comment by ianlancetaylor** [comment]
Closing as infeasible.

**Comment by rsc** [comment]
This proposal has been added to the [active column](https://golang.org/s/proposal-status#active) of the proposals project
and will now be reviewed at the weekly proposal review meetings.
— rsc for the proposal review group
