### ISSUE TITLE
cmd/compile: mark shape type dupok 

### ISSUE THREAD

**Issue by zhouguangyuan0718** [golang/go#52633]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.19-fd6c556dc8 Sat Apr 30 04:04:40 2022 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
No, it marks all type description dupok in 1.18.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/mnt/d/01.golang/01.GOPATH/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/mnt/d/01.golang/02.playground/01.demo/playground/dwarftype/gopath/"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/mnt/d/01.golang/03.godev/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/mnt/d/01.golang/03.godev/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.19-fd6c556dc8 Sat Apr 30 04:04:40 2022 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/mnt/d/01.golang/02.playground/01.demo/playground/dwarftype/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3478615306=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
`go install -buildmode=shared -linkshared std`

### What did you expect to see?
Success.

### What did you see instead?
<pre>
# /tmp/go-build415098603/b236/libstd.so
2022/04/30 22:37:52 duplicated definition of symbol type.go.shape.*uint8_0, from crypto/tls and crypto/elliptic
</pre>

**Comment by dr2chase** [comment]
Marked it "needs investigation" to get it off the dashboard, but it is a bug, repros just fine for me, the fix looks sensible, and I pinged the likely reviewers.

**Comment by randall77** [comment]
@gopherbot please open a backport issue for 1.18.
