### ISSUE TITLE
cmd/compile: optimized range memclr doesn't work with pointers to arrays

### ISSUE THREAD

**Issue by josharian** [golang/go#52635]
```go
package p

type T struct {
	a *[10]int
	b [10]int
}

func (t *T) resetA() {
	for i := range t.a {
		t.a[i] = 0
	}
}

func (t *T) resetB() {
	for i := range t.b {
		t.b[i] = 0
	}
}
```

resetA compiles to a loop. resetB compiles to a call to runtime.memclrNoHeapPointers. I believe that resetA should also call memclrNoHeapPointers.

This showed up as a hot spot in my code today (with much larger arrays).

cc @randall77 @cuonglm @mdempsky

**Comment by josharian** [comment]
As evidence that this is just a missed optimization, here is equivalent code using a new intermediate type:

```go
type T struct {
	c *A
}

type A struct {
	x [10]int
}

func (t *T) resetC() {
	for i := range t.c.x {
		t.c.x[i] = 0
	}
}
```

This generates `runtime.memclrNoHeapPointers`. (And also provides a workaround.)

**Comment by renthraysk** [comment]
There is a simpler workaround ```for i := range *t.a {```.

**Comment by josharian** [comment]
@renthraysk unfortunately, that won't work. It has the right semantics, but for the optimization to kick in the range expression has to match the LHS assignment expression (without index) exactly, but `*t.a[i] = 0` won't compile.

**Comment by josharian** [comment]
@renthraysk I am astonished that that works, and I wrote the original optimization. Now that you say it, I see why. Anyway, I still think this is worth fixing. 📦

**Comment by renthraysk** [comment]
Yea, agreed. Actually thought I filed an issue for this, but seems just tweeted about it back in 2017, so my bad.

> Subtle diff in
> func f1(in *[96]byte) { for i := range in { in[i] = 0 } }
> func f2(in *[96]byte) { for i := range *in { in[i] = 0 } }
>

**Comment by rip-create-your-account** [comment]
The following generates slightly more efficient code for my computer.
```go
func (t *T) resetC() {
	*t.a = [10]int{}
}
```
There's no `runtime.memclrNoHeapPointers` call at all. Instead the compiler seems to choose a suitable algorithm based on the size of the array. To me it seems like all of the loops above should compile to this.

**Comment by go101** [comment]
It looks the `memclr` way is more efficient than the assignment way for small arrays.
Should the runtime internal unify the implementation for the two ways?
