### ISSUE TITLE
cmd/go: go test -buildvcs=true does not include vcs information

### ISSUE THREAD

**Issue by carlmjohnson** [golang/go#52648]
### What version of Go are you using (`go version`)?

go version go1.18.1 darwin/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/adhoc/bin"
GOCACHE="/Users/adhoc/Library/Caches/go-build"
GOENV="/Users/adhoc/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/adhoc/src/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/adhoc/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.18.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.18.1/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p7/jc4qc9n94r3f6ylg0ssh1rq00000gs/T/go-build2620312267=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Run `go test -buildvcs=true .`

### What did you expect to see?

Have debug.ReadBuildInfo() include vcs information.

### What did you see instead?

Information was not included.

Compare https://github.com/golang/go/issues/52338, cc @bcmills

**Comment by seankhliao** [comment]
[CL 393894](https://go.dev/cl/393894)

**Comment by carlmjohnson** [comment]
I agree that the VCS information should not be included by default. But if you specifically add `-buildvcs=true`, it should either include the information or error out. In my case, I'm testing a package that parses debug.ReadBuildInfo, which is kind of a weird thing to do, but I don't think it's so weird that the VCS information should _never_ be includable.

**Comment by bcmills** [comment]
I suppose that now that we have `-buildvcs=auto`, we could theoretically make `-buildvcs=true` add stamping for tests. 🤔

**Comment by alexedwards** [comment]
I'd like to see consistency in behavior across the different `go` tools. If `go test -buildvcs=true` adds stamping for tests, then `go run -buildvcs=true` should add stamping too. 

I wouldn't want to see us end up in a scenario like this:

* `go build` adds stamping by default (if a VCS repo is present)
* `go test` only adds stamping if `-buildvcs=true`
* `go run` never adds stamping, even if `-buildvcs=true` (which is where things were left on https://github.com/golang/go/issues/52338)

**Comment by carlmjohnson** [comment]
I think it’s fine for go test to default to omitting and go run to disallow it, but it should error out if you request an impossible option.

**Comment by bcmills** [comment]
@gopherbot, please backport to Go 1.18. The requested `-buildvcs` behavior for this particular use-case was present in Go 1.18, but regressed in Go 1.18.1 as a byproduct of the fix for #51767. Now that `-buildvcs=auto` has been added for #51798, the Go 1.18 behavior for `-buildvcs=true` can be restored.

**Comment by nightlyone** [comment]
If this invalidates the test cache after every git commit, this sounds like a really bad idea to me. 

What real world use case would be enabled by this behaviour?

**Comment by carlmjohnson** [comment]
Testing that your binary contains build information. 

Most people should have it set to auto or off most of the time. What’s the problem with slow builds for people who deliberately turn it on?

**Comment by dr2chase** [comment]
With respect to backports, what's the status of this bug/fix?
#53177 (1.18 backport) is still open.

**Comment by bcmills** [comment]
The backport is waiting on a bit of soak time. (The need for soak time is why it didn't make 1.19 as well.)
