### ISSUE TITLE
x/pkgsite: link symbols on pkg.go.dev/vuln pages to the corresponding pkg.go.dev/<path>#<symbol>

### ISSUE THREAD

**Issue by julieqiu** [golang/go#52660]
It would be nice if symbols on the pkg.go.dev/vuln pages linked to the corresponding symbol on the pkg.go.dev package page. 

For example, on https://pkg.go.dev/vuln/GO-2021-0242, `Rat.SetString` and `Rat.UnmarshalText` should link to https://pkg.go.dev/math/big#Rat.SetString and https://pkg.go.dev/math/big#Rat.UnmarshalText. 

We could change the description field to a markdown type in the yaml reports, and have it parsed by pkgsite when rendering the page. 

/cc @golang/vulndb @golang/pkgsite

**Comment by julieqiu** [comment]
The `details` field for OSV supports markdown: https://ossf.github.io/osv-schema/#summary-details-fields.

We currently only populate `details` (example: https://vuln.go.dev/golang.org/x/text.json).

**Comment by jba** [comment]
What about using Affected.EcosystemSpecific.Symbols instead?

**Comment by hyangah** [comment]
This is fixed.
