### ISSUE TITLE
x/build/cmd/coordinator: some x-repo builders not allowed from TRY=line

### ISSUE THREAD

**Issue by bcmills** [golang/go#52667]
https://go.dev/wiki/SlowBots currently says:
> For the main Go repository, the terms after `TRY=` can also be:
>
> * `x/repo`, where `repo `is one of the golang.org/x repositories whose tests should be executed. This runs a default builder for the given repo (`linux-amd64` as of writing).
> * `x/repo@builder`, where `repo` is as above, and `builder` is a builder name from the [builder list](https://farmer.golang.org/builders). This runs the specified builder for the given repo. For example, `x/sys@linux-arm64-aws`.

I attempted to use that functionality in https://go-review.googlesource.com/c/go/+/403694/1#message-384468da277d8d207745408ee312e594834c0c3b, with the line
```
TRY=longtest,windows-amd64-longtest,x/sys@longtest,x/sys@windows-amd64-longtest
```

I expected that that would run the usual TryBots, plus `longtest` and `windows-amd64-longtest` SlowBots for the `go` repo, plus `longtest` and `windows-amd64-longtest` SlowBots for the `x/sys` repo.

However, the `x/sys` SlowBots were not included in that run, and the Coordinator didn't reply with any kind of error message for the `TRY=` line.

**Comment by bcmills** [comment]
I tried again in https://go-review.googlesource.com/c/go/+/403694/1#message-e384c689409e2701273d9ea9e87a132aee29c93b with just
```
TRY=x/sys@windows-amd64-longtest
```
but that doesn't seem to have worked either.

**Comment by findleyr** [comment]
The reason for this is likely that windows-amd64-longtest is not a TryBot, which is currently required:
https://cs.opensource.google/go/x/build/+/master:cmd/coordinator/coordinator.go;l=1312;drc=993f2c6f22a69963d73f42c2712c601bff8c3939

Unfortunately, it is only surfaced in logs, and not in a message back to the CL.

This actually came up in chat recently: I think we don't actually need to impose this restriction.

**Comment by findleyr** [comment]
Reopening until the coordinator is deployed.

As a follow-up, I'll try to include more details about parsing failures / invalid slowbots in the starting message.

**Comment by dmitshur** [comment]
I'll redeploy coordinator with this change after https://farmer.golang.org/#remote reaches 0 active gomote sessions.

**Comment by dmitshur** [comment]
The fix is deployed; thanks Bryan and Rob.
