### ISSUE TITLE
x/sys: execabs isGo119ErrDot redeclared in go 1.15

### ISSUE THREAD

**Issue by scottTomaszewski** [golang/go#52668]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build372615255=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

go 1.15 has issues with the `isGo119ErrDot` function being redeclared: 

<pre>
$ go get golang.org/x/tools/cmd/goimports
# golang.org/x/sys/execabs
root/go/src/golang.org/x/sys/execabs/execabs_go119.go:11:6: isGo119ErrDot redeclared in this block
	previous declaration at root/go/src/golang.org/x/sys/execabs/execabs_go118.go:9:31
</pre>

You can reproduce the issue with this Docker file, run `docker build .` on it

<pre>
FROM docker:20.10.12
RUN apk add curl git
RUN curl -LO "https://dl.google.com/go/go1.15.7.linux-amd64.tar.gz"
RUN tar -C /usr/local -xzf go1.15.7.linux-amd64.tar.gz
ENV PATH /usr/local/go/bin:${PATH}
RUN go version
RUN go env
RUN go get golang.org/x/tools/cmd/goimports
</pre>

We started experiencing this issue after this change: https://cs.opensource.google/go/x/sys/+/b6088ccd6cba9272b1e5639ef2df5b5731b85abc

### What did you expect to see?

No failure

**Comment by bcmills** [comment]
Note that per the [release policy](https://go.dev/doc/devel/release#policy), Go 1.15 is no longer supported.

However, it's an easy fix and I don't see much harm in applying it (beyond enabling folks to use insecure, out-of-date Go releases).

**Comment by scottTomaszewski** [comment]
Fixed, thank you :pray:
