### ISSUE TITLE
x/website: it may be a wrong logic in this sentence?

### ISSUE THREAD

**Issue by MaoScut** [golang/go#52664]
### What is the URL of the page with the issue?
 
 https://go.dev/blog/supply-chain
 
### What is your user agent?
 

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 
### Screenshot
 

 
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/20971422/166436438-96168b9f-da06-4873-b46c-5961fb90fcaa.png">

 
 
### What did you expect to see?
there is a "even", so the words following the "even" should be some "good thing", right?
It is an explicit security design goal of the Go toolchain that neither fetching nor building code will let that code execute, even if it is **trusted** and **safe**.

**Comment by seankhliao** [comment]
"even if" means

> despite the possibility that; no matter whether.
