### ISSUE TITLE
cmd/compile: internal compiler error: Value live at entry. It shouldn't be.

### ISSUE THREAD

**Issue by ddaa2000** [golang/go#52673]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=      
set GOCACHE=C:\Users\ddaa\AppData\Local\go-build
set GOENV=C:\Users\ddaa\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\ddaa\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\ddaa\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\programing\go\bugReview\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ddaa\AppData\Local\Temp\go-build1175442941=/tmp/go-build -gno-rec
ord-gcc-switches

</pre></details>

### What did you do?
https://go.dev/play/p/sgQ1Oc01pz2

### What did you expect to see?
compile successfully

### What did you see instead?
<pre>
./prog.go:9:6: internal compiler error: 'main': Value live at entry. It shouldn't be. func main, node .autotmp_5, value v118

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new

Go build failed.
</pre>

**Comment by dr2chase** [comment]
@randall77 @dr2chase @mdempsky

**Comment by ianlancetaylor** [comment]
Closing on the assumption that this is a dup of #52590.  Thanks for reporting it.

**Comment by cuonglm** [comment]
@ianlancetaylor This is different bug involve initialization of composite literal.

**Comment by mdempsky** [comment]
Yeah, #52590 was an exporter issue, but this issue is reproducible with a single source file (i.e., no export involved).

**Comment by ianlancetaylor** [comment]
Ah, sorry.

**Comment by cuonglm** [comment]
@mdempsky Seems the bug was introduced when the compiler was changed to handle array literal with more than 4 elements. This program:

```
package p

type b bool

func f() {
	func() [10][]bool {
		return [10][]bool{
			[]bool{bool(g(false) < "")},
			[]bool{}, []bool{}, []bool{}, []bool{}}
	}()
}

func g(b) (s string) { return }
```

compile ok with go1.4 :smiley:

**Comment by mdempsky** [comment]
@cuonglm Thanks. Do you want to take this issue?

**Comment by cuonglm** [comment]
> @cuonglm Thanks. Do you want to take this issue?

Yes, no problem!

**Comment by cuonglm** [comment]
@mdempsky So for code like:

```
package p

func f() {
	var x string
	func() [10][]bool {
		return [10][]bool{
			[]bool{bool(x < "")},
			[]bool{}, []bool{}, []bool{}, []bool{}}
	}()
}
```

We initialize the code roughly as:

```
.stmp_1[0] = len(x) < 0
~R0 = .stmp_0
```

Then call to fixedlit at L573 (cmd/compile/internal/walk/complit.go) rewrites it to:

```
.stmp_1[0] = .autotmp_4 < 0
~R0 = .stmp_0
autotmp_3 = <nil>
autotmp_2 = &.autotmp_3
.autotmp_4 = len(x)
.autotmp_2[0] = .autotmp_4 < 0
<node VARKILL>
```

I have no ideal how to fix it yet.

**Comment by mdempsky** [comment]
@cuonglm Okay, I can take a look tomorrow. Thanks for investigating!

**Comment by cuonglm** [comment]
> @cuonglm Okay, I can take a look tomorrow. Thanks for investigating!

Don't mind, I think I figured it out!

**Comment by dr2chase** [comment]
@dmitshur did we want to push for a backport for this one, or does it not make the train for next week?

**Comment by mdempsky** [comment]
This isn't a Go 1.18 regression. I don't think it needs to be backported.

**Comment by randall77** [comment]
Generally ICEs that are triggered only by fuzzing the compiler don't need backporting.
If it generated bad code, then maybe.
