### ISSUE TITLE
runtime: sysMemStat overflow on openbsd-mips64-jsing

### ISSUE THREAD

**Issue by mknyszek** [golang/go#52682]
Example failure: https://build.golang.org/log/94e9c9c820d29aa509ffe49c14cb5c8784954f99

This started happening as of the SetMemoryLimit CLs. Notably, linux-mips64le looks OK.

**Comment by bcmills** [comment]
(CC @golang/openbsd, @golang/mips)

**Comment by mengzhuo** [comment]
Bisect shows https://go-review.googlesource.com/c/go/+/399474 is the bad commit
CC @mknyszek

**Comment by mknyszek** [comment]
I've reassigned this to @4a6f656c. I don't have the time at this moment to look into this, and it's low priority for me because it's a second class port. I'm willing to take a look later, but I can't make any promises on when.

**Comment by cherrymui** [comment]
This code https://cs.opensource.google/go/go/+/master:src/runtime/mheap.go;l=1185 calls `h.pages.free` in `allocSpan` (from a stack allocation before the allocation of the 64K stack. What allocation that is? I don't know...). I think this may cause the scavenger to find something, as it marks bits in the scavengeIndex, without changing `heapFree` (?). The condition `needPhysPageAlign` is OpenBSD specific.

**Comment by mknyszek** [comment]
Oh, wow. OK. Thanks for figuring that out!!

Ugh. This case is super annoying. When that memory gets allocated, its scavenged bits get cleared. So, when the edges of the allocation are subsequently freed, they're always considered unscavenged, even though we didn't actually use them. If we want to maintain that behavior, we need to figure out exactly how much of those "edge" pages were scavenged and make the appropriate update. This looks like it was pretty much always wrong; we just got lucky.

We can avoid this entirely by just finding a big enough region that we can slice up, and then allocate only the aligned part in the first place, so we don't have to free the edges. I'll send a patch.

**Comment by mknyszek** [comment]
Another, potentially simpler solution, would be to just always overallocate and have the stack code do the alignment. It wastes memory instead of CPU time, though.
