### ISSUE TITLE
runtime: index out of range in scavenger page lookup on GOAMD64=3 due to Len8 codegen issue

### ISSUE THREAD

**Issue by mknyszek** [golang/go#52681]
Example failure: https://build.golang.org/log/c367b3a210d28381bd2aa0bc2741b1492a6e4a7f

The candidate chunk discovered from the new scavenger index doesn't refer to a region of memory the page allocator thinks is mapped. No reproducer yet, but working on it.

**Comment by mknyszek** [comment]
This failure occurred a second time in a row on `linux-amd64-goamd64v3`. Looks like that's what's necessary to reproduce.

**Comment by mknyszek** [comment]
https://build.golang.org/log/40c03ce87d00a750855c376d71e74cc6615229ab

**Comment by mknyszek** [comment]
Confirmed. I can reproduce locally by just doing:

```
GOAMD64=v3 ./make.bash
```

**Comment by mknyszek** [comment]
I can also reproduce the issue in the scavenger tests. If I build the toolchain without `GOAMD64=v3`, and then run:

```
GOAMD64=v3 ~go test -run="Scavenge" -count=1 runtime
``

it fails.

**Comment by randall77** [comment]
Looking at the amd64 v3 rules, I think I found a bug. Does the scavenger use `math/bits.Len16` or `math/bits.Len8`?

**Comment by randall77** [comment]
Ah yes, looks like it uses `sys.LeadingZeros8` which probably uses the same builtin as `Len8`. The bug is the rule in `cmd/compile/internal/ssa/gen/AMD64.rules:108`, it's not right for 16/8 bits.

**Comment by Jorropo** [comment]
I have the same problem, I have bisect it to 91f863013e6b5ba870f6bfbfda0b735cf54fb3ca.

**Comment by mknyszek** [comment]
@cherrymui came to the same conclusion, that the codegen rules aren't right, specifically if the high bits of the register that's being used are not zero.
