### ISSUE TITLE
x/tools/cmd/godoc: package listing readability

### ISSUE THREAD

**Issue by anacrolix** [golang/go#5270]
<pre>The package listing at <a href="http://tip.golang.org/pkg/">http://tip.golang.org/pkg/</a> is significantly more readable and
navigable than that at <a href="http://golang.org/pkg/">http://golang.org/pkg/</a>, but appears this way only due to
misconfiguration. I think the godoc package listings should always look like the former,
misconfiguration or not.</pre>

**Comment by agnivade** [comment]
@adg - Is this waiting on something ? https://golang.org/pkg/ and https://tip.golang.org/pkg/ look the same now. i.e. - both have indentation.
