### ISSUE TITLE
crypto/elliptic: s390x elliptic assembly refactoring in Go1.19 [freeze exception]

### ISSUE THREAD

**Issue by billotosyr** [golang/go#52709]
We are working to move the s390x elliptic assembly into the new refactored form as designated by Filippo, but we need more time to get everything reviewed and finalized. We have been working to base ours against Filippos CLs, (not all of which have been integrated). For now we are basing our changes on CL 399755, as suggested by Filippo. Given the new +2 review policy, it will be a challenge to meet the freeze deadline, but it shouldn't spill out much past the deadline. Note that this only affects s390x linux -- no other platform. I respectfully request a reasonable grace period beyond the freeze. Our CL has begun the review process: CL 404058

**Comment by l-lindsay** [comment]
cc @golang/release

**Comment by FiloSottile** [comment]
I'm not opposed to a freeze exception on my side, as long as there are only s390x changes, like in CL 404058 currently. Note that even with the new review policy, the only major step is getting a single +2 from someone who can review the assembly changes. We'll take care of the other +1.

**Comment by FiloSottile** [comment]
Was this approved @golang/release? The CL is ready.

**Comment by cagedmantis** [comment]
This freeze exception has been approved.
