### ISSUE TITLE
cmd/vet: lock copy warning and unsafe.Offsetof

### ISSUE THREAD

**Issue by oakad** [golang/go#52700]
go 1.18.1

This may not be a bug but it was not obvious to me how to avoid the warning.

Consider the following situation:
```
type B struct {
	sync.Mutex
}

type D struct {
	some int
	base B
}

const baseOffset = unsafe.Offsetof(D{}.base)
```

This now triggers a warning with go vet: "call of unsafe.Offsetof copies lock value: B".

Clearly:
1. Either go vet should be made to recognize `Offsetof` usage
2. Or, `Offsetof` should be modified somehow to avoid triggering the warning

**Comment by dr2chase** [comment]
@matloob @timothy-king can one of you give this a look? I went looking for a duplicate, I'd swear I'd seen recent mention of something very similar but I couldn't find it.

**Comment by zpavlinovic** [comment]
I believe `reflect.{Alignof, Offsetof}` should be excluded from the analysis of calls in the copy-lock checker as these functions do not really evaluate expressions (#12946, #20262).

Interestingly, `reflect.Sizeof` is already covered by the checker (in addition to `len`, `cap`, and `new`).

**Comment by timothy-king** [comment]
This is roughly the same as https://github.com/golang/go/issues/21800. The fix goes back to https://go-review.googlesource.com/c/go/+/66210/. Given the age of the issue and the other fix, I don't think a fix needs to be back ported.
