### ISSUE TITLE
go/types: NewMethodSet doesn't terminate for recursively embedded generics

### ISSUE THREAD

**Issue by dominikh** [golang/go#52715]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.19-fbb47e81c1 Wed May 4 20:20:28 2022 +0000 linux/amd64
</pre>

### What did you do?
https://go.dev/play/p/cFb8uD0dfU1

### What did you expect to see?
For types.NewMethodSet to terminate.

### What did you see instead?
It doesn't terminate.

/cc @griesemer @findleyr

**Comment by findleyr** [comment]
Thank you for reporting. This is unfortunate. Lazy expansion of the embedded types allows the search to expand infinitely, as it uses pointer identity.

This should be straightforward to fix.

**Comment by findleyr** [comment]
Related: #51580

**Comment by findleyr** [comment]
@gopherbot please port to 1.18. This is an infinite recursion via valid usage of the go/types API.
