### ISSUE TITLE
golang.org/x/net/publicsuffix: EffectiveTLDPlusOne returns incorrect result

### ISSUE THREAD

**Issue by devilHorns13** [golang/go#52720]
### What version of Go are you using?
<pre>
go version devel go1.19-dd97871282 Thu Apr 14 18:00:13 2022 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/user/go-linux-amd64-bootstrap/bin"
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/user/go-linux-amd64-bootstrap"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/go-linux-amd64-bootstrap/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.19-dd97871282 Thu Apr 14 18:00:13 2022 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3132258848=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
<pre>publicsuffix.EffectiveTLDPlusOne("bar.webhop.me")</pre>
https://go.dev/play/p/D06yGTm_K9j?v=gotip

### What did you expect to see?
`webhop.me`

### What did you see instead?
`bar.webhop.me`

**Comment by ZekeLu** [comment]
According to https://publicsuffix.org/list/public_suffix_list.dat, `webhop.me` is an `eTLD`. So `bar.webhop.me` is an `eTLD+1`. The result is correct.

**Comment by devilHorns13** [comment]
@ZekeLu Thanks.
