### ISSUE TITLE
affected/package: godoc

### ISSUE THREAD

**Issue by mmngreco** [golang/go#52730]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

```bash
mkdir test
go get github.com/pb-/gotypist@latest
go mod init test
godoc -http :8000
```

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mgreco/.cache/go-build"
GOENV="/home/mgreco/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/mgreco/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mgreco/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/mgreco/test/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3402884810=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I've just installed go, and created a module and tried to serve doc.

### What did you see instead?

```bash
$ godoc -http :8000
using module mode; GOMOD=/home/mgreco/test/go.mod
go: no module dependencies to download
2022/05/05 21:14:34 godoc: corpus fstree is nil
```

**Comment by seankhliao** [comment]
The commands you listed don't make sense and don't correspond to the output you've given. What did you actually do?

**Comment by mmngreco** [comment]
Hi @seankhliao thank you for your quick response.  Silly mistakes, I've just update the original post (only changes the module directory, hopefully not relevant for this issue).

**Comment by mmngreco** [comment]
I'm not sure if I understood correctly you previous comment, why the commands don't make sense?

**Comment by D1CED** [comment]
What version of godoc do you have installed? I had a similar issue some time ago when upgrading to go1.18 but also updating godoc (to v0.1.10) fixed the issue for me.

**Comment by mmngreco** [comment]
I've recently installed `godoc` wiht latest tag so I assume that I have [v0.1.10](https://pkg.go.dev/golang.org/x/tools/cmd/godoc?tab=versions) installed.  

I've tried to obtain the version but I don't know how to do it ¯\_ (ツ) _/¯ unfortunately, there isn't a `godoc version`.

**Comment by ZekeLu** [comment]
@mmngreco 

> I've tried to obtain the version but I don't know how to do it

`go version -m $(which godoc)`

> The commands you listed don't make sense and don't correspond to the output you've given.

Try to execute the commands in this order:

```diff
  mkdir test
+ cd test
+ go mod init test
  go get github.com/pb-/gotypist@latest
- go mod init test
  godoc -http :8000
```

**Comment by mmngreco** [comment]
Thank you @ZekeLu, I think I'm frustrated with this, that's why I missed the `cd test` step in the body. However I've tried your suggestion and I've got the same result:

```bash
$ rm -rf test
$ mkdir test
mkdir: created directory 'test'
$ cd test
$ go mod init test
go: creating new go.mod: module test
$ go get github.com/pb-/gotypist@latest
go: added github.com/mattn/go-runewidth v0.0.9
go: added github.com/nsf/termbox-go v0.0.0-20200418040025-38ba6e5628f1
go: added github.com/pb-/gotypist v0.0.0-20211124210140-925d43aa609a
$ godoc -v -http :8000
using module mode; GOMOD=/home/mgreco/test/go.mod
2022/05/06 06:49:43 newDirTree reading /favicon.ico: file does not exist
2022/05/06 06:49:43 godoc: corpus fstree is nil
```

**Comment by ZekeLu** [comment]
You're welcome! Please post the output of `go version -m $(which godoc)` too.

**Comment by mmngreco** [comment]
I've also tried to provide a docker script but I've got another problem... Should I open another issue with this? 

```bash
docker run --rm -it golang:buster /bin/bash
mkdir test
cd test
go mod init test
go get github.com/pb-/gotypist@latest
godoc -v -http :8000
```

## Log

```python
$ docker run --rm -it golang:buster /bin/bash
root@d8f261d55899:/go# mkdir test
root@d8f261d55899:/go# cd test
root@d8f261d55899:/go/test# go mod init test
go: creating new go.mod: module test
root@d8f261d55899:/go/test# go get github.com/pb-/gotypist@latest
go: downloading github.com/pb-/gotypist v0.0.0-20211124210140-925d43aa609a
go: downloading github.com/nsf/termbox-go v0.0.0-20200418040025-38ba6e5628f1
go: downloading github.com/mattn/go-runewidth v0.0.9
go: added github.com/mattn/go-runewidth v0.0.9
go: added github.com/nsf/termbox-go v0.0.0-20200418040025-38ba6e5628f1
go: added github.com/pb-/gotypist v0.0.0-20211124210140-925d43aa609a
root@d8f261d55899:/go/test# godoc -v -http :8000
bash: godoc: command not found
```

**Comment by mmngreco** [comment]
> You're welcome! Please post the output of go version -m $(which godoc) too.

Here it goes:

```bash
$ go version -m $(which godoc)
/home/mgreco/go/bin/godoc: go1.18
        path    golang.org/x/tools/cmd/godoc
        mod     golang.org/x/tools      v0.1.10 h1:QjFRCZxdOhBJ/UNgnBZLbNV13DlbnK0quyivTnXJM20=
        dep     github.com/yuin/goldmark        v1.4.1  h1:/vn0k+RBvwlxEmP5E7SZMqNxPhfMVFEJiykr15/0XKM=
        dep     golang.org/x/mod        v0.6.0-dev.0.20220106191415-9b9b3d81d5e3        h1:kQgndtyPBW/JIYERgdxfwMYh3AVStj88WQTlNDi2a+o=
        dep     golang.org/x/net        v0.0.0-20211015210444-4f30a5c0130f      h1:OfiFi4JbukWwe3lzw+xunroH1mnC1e2Gy5cxNJApiSY=
        dep     golang.org/x/sys        v0.0.0-20211019181941-9d821ace8654      h1:id054HUawV2/6IGm2IV8KZQjqtwAOo2CYlOToYqa0d0=
        dep     golang.org/x/xerrors    v0.0.0-20200804184101-5ec99f83aff1      h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
        build   -compiler=gc
        build   CGO_ENABLED=1
        build   CGO_CFLAGS=
        build   CGO_CPPFLAGS=
        build   CGO_CXXFLAGS=
        build   CGO_LDFLAGS=
        build   GOARCH=amd64
        build   GOOS=linux
        build   GOAMD64=v1

```

**Comment by ZekeLu** [comment]
> bash: godoc: command not found

`godoc` is not included. You have to install it manually.

**Comment by mmngreco** [comment]
> > bash: godoc: command not found
> 
> `godoc` is not included. You have to install it manually.

agg sorry for the noise. Exactly, adding `go install golang.org/x/tools/...@latest` it works in the docker container but still not working in my local machine.

**Comment by mmngreco** [comment]
Ok, as I could make it work using docker I've decided to make a fresh installation of go:

```bash
sudo apt remove --purge golang-go  # as I've installed using apt
rm -rf ~/go
wget https://go.dev/dl/go1.18.1.linux-amd64.tar.gz
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.18.1.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin  # add into bashrc
```

I also have the variable `export GOPATH="$HOME/go"` in my `.bashrc`  I've removed that too.

...and now all it works as expected!

Thank you for the support! :-)
