### ISSUE TITLE
go/internal/gcimporter:  test failed with exporting stenciled functions

### ISSUE THREAD

**Issue by wdvxdr1123** [golang/go#52735]
### What did you do?
Add this file to test/typeparam
https://go.dev/play/p/fyK6PtgbKdJ

### What did you expect to see?

Test get passed.

### What did you see instead?

--- FAIL: TestImportTypeparamTests (32.80s)
    --- FAIL: TestImportTypeparamTests/export_stenciled.go (0.14s)
        gcimporter_test.go:225: imported object "Do[go.shape.int_0]" was not type-checked
FAIL
exit status 1
FAIL    go/internal/gcimporter  33.995s

cc @griesemer @findleyr

**Comment by seankhliao** [comment]
Seems to be working
