### ISSUE TITLE
x/pkgsite: RFC section link appears to be broken by newline

### ISSUE THREAD

**Issue by mdlayher** [golang/go#52738]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/mdlayher/ndp#RouteInformation

### What is your user agent?

n/a, server rendering issue

### Screenshot

![image](https://user-images.githubusercontent.com/1926905/167141514-66e73820-5562-4d27-bf75-9db4095b31a1.png)

### What did you do?

Navigated to package docs for my NDP package.

### What did you expect to see?

RFC 4191, Section 2.3 presented as a full hyperlink as is done in https://pkg.go.dev/github.com/mdlayher/ndp#PrefixInformation.

### What did you see instead?

The RFC section hyperlinking logic appears to be confused by a newline in a doc comment. For example, this works:

```go
// A PrefixInformation is a a Prefix Information option, as described in RFC 4861, Section 4.6.1.
type PrefixInformation struct {
	PrefixLength                   uint8
	OnLink                         bool
	AutonomousAddressConfiguration bool
	ValidLifetime                  time.Duration
	PreferredLifetime              time.Duration
	Prefix                         netip.Addr
}
```

This does not:

```go
// A RouteInformation is a Route Information option, as described in RFC 4191,
// Section 2.3.
type RouteInformation struct {
	PrefixLength  uint8
	Preference    Preference
	RouteLifetime time.Duration
	Prefix        netip.Addr
}
```

Note that the RFC section is word wrapped to a new line in the latter case.

**Comment by seankhliao** [comment]
I think the new doc design #51082 drops support for magic RFC links, so not sure if this is intended to work in the future?
ref https://github.com/golang/go/discussions/48305#discussioncomment-1304365
