### ISSUE TITLE
reflect: StructOf field offset calculation may overflow

### ISSUE THREAD

**Issue by lmb** [golang/go#52740]
### What version of Go are you using (`go version`)?

<pre>
% go version
go version go1.18.1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

Darwin / amd64.

### What did you do?

```
func TestLargeArray(t *testing.T) {
	elem := reflect.TypeOf(uint32(0))
	max := int(^uintptr(0) / elem.Size())
	arr := reflect.ArrayOf(max, elem)

	fields := []reflect.StructField{
		{Name: "A", Type: arr},
		{Name: "B", Type: reflect.TypeOf("")},
	}

	typ := reflect.StructOf(fields)
	var offset uintptr
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		if i > 0 && field.Offset == offset {
			t.Fatalf("field %d: duplicate offset %d", i, field.Offset)
		} else {
			t.Logf("field %d: offset %d", i, field.Offset)
		}
		offset = field.Offset
	}
}
```

### What did you expect to see?

I'd expect offsets to be correct or `StructOf` to panic.

### What did you see instead?

```
=== RUN   TestLargeArray
    foo_test.go:107: field 0: offset 0
    foo_test.go:105: field 1: duplicate offset 0
--- FAIL: TestLargeArray (0.00s)
```

I think the problem lies in this call to align: https://github.com/golang/go/blob/f87e28d1b9ab33491b32255f333f1f1d83eeb6fc/src/reflect/type.go#L2630

On my machine, `size` is `0xfffffffffffffffc` and `ft.align` is `8` for field `B`. `0xfffffffffffffffc + 0x7` is `0x10000000000000003` aka `0x0000000000000003` due to truncation / overflow.

**Comment by randall77** [comment]
Looks like structs aren't defensive against overflow in general. Adding complication, we only store 63 bits of size, not 64.
