### ISSUE TITLE
x/pkgsite: package removal request for github.com/vikpe/qw-serverstat

### ISSUE THREAD

**Issue by vikpe** [golang/go#52755]
### What is the path of the package that you would like to have removed?
github.com/vikpe/qw-serverstat

 
 
 
### Are you the owner of this package?
yes

 
### What is the reason that you could not retract this package instead?
I added the retract directive but it seems to  have no effect

```go
module github.com/vikpe/qw-serverstat

go 1.18

retract (
	v0.1.6
	v0.1.5
	v0.1.4
	v0.1.3
	v0.1.2
	v0.1.1
	v0.1.0
)
```

versions are still visible and not marked as retracted on pkg.go.dev

![image](https://user-images.githubusercontent.com/1616817/167249360-fa0d8479-2d9d-4aa1-bf97-3455ca2e17db.png)

**Comment by jamalc** [comment]
Done.
