### ISSUE TITLE
affected/package: go template crash when meets content like {{.vars.X-test}}

### ISSUE THREAD

**Issue by wangbinbupt** [golang/go#52754]
### What version of Go are you using (`go version`)?
go version go1.18.1 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
wangbin@wubuntu:/code/test$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/wangbin/.cache/go-build"
GOENV="/home/wangbin/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/code/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/code/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/bin/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/bin/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4148638487=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
I have a function using template to get value. It works OK until I have a map entry with key including "-"

code:
1. define StepResult 
type Stack struct {
	GinContext *gin.Context
	StepResult map[string]interface{}
	Name       string
}
2.create a map in StepResult
		vars := make(map[string]string, paramLen)
		stack.StepResult["vars"] = vars
                vars["X-test"] = "abc"

3.use template to query variables {{.vars.X-test}}
func (stack Stack) QueryFromStepResult(template string) string {
	tmpl, _ := template.New("key").Parse(template)
	buf := new(bytes.Buffer)
	tmpl.Execute(buf, stack.StepResult)
	return buf.String()
}

### What did you expect to see?
get the value

### What did you see instead?
crash
runtime error: invalid memory address or nil pointer dereference
/usr/bin/go/src/text/template/exec.go:164 (0x9c1fba)
        errRecover: panic(e)
/usr/bin/go/src/runtime/panic.go:838 (0x6366a6)
        gopanic: done = runOpenDeferFrame(gp, d)
/usr/bin/go/src/runtime/panic.go:220 (0x64c835)
        panicmem: panic(memoryError)
/usr/bin/go/src/runtime/signal_unix.go:818 (0x64c805)
        sigpanic: panicmem()
/usr/bin/go/src/text/template/exec.go:215 (0x9c23ec)
        (*Template).execute: if t.Tree == nil || t.Root == nil {
/usr/bin/go/src/text/template/exec.go:201 (0xb0a1d4)
        (*Template).Execute: return t.execute(wr, data)
/code/go/tms-go-apihub/broker/hub/stack.go:26 (0xb0a0a7)
        Stack.QueryFromStepResult: tmpl.Execute(buf, stack.StepResult)

**Comment by seankhliao** [comment]
Like go code, `X-test` is parsed as `X - test`.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by wangbinbupt** [comment]
This is obvious a bug, not a discussion.
If I can define a map using key including -, then template should be able to handle it.
This a key name not variable name.

**Comment by ZekeLu** [comment]
See https://pkg.go.dev/text/template

> - The name of a key of the data, which must be a map, preceded by a period, such as
>  	.Key
>  The result is the map element value indexed by the key.
> Key invocations may be chained and combined with fields to any depth:
>  .Field1.Key1.Field2.Key2
>  Although **the key must be an alphanumeric identifier**, unlike with field names they do not need to start with an upper case letter. Keys can also be evaluated on variables, including chaining:
>  $x.key1.key2

You can use `{{index .vars "X-test"}}` in this case.
