### ISSUE TITLE
flag provided but not defined: -mod

### ISSUE THREAD

**Issue by MariaZarifyan** [golang/go#52766]
Hello. 

I am using the go version go1.18 and amd64 processor architecture. 

```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GOOS="linux"
GOPATH="/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build543860680=/tmp/go-build -gno-record-gcc-switches"
```
I want to execute the following two commands 
```
go get -u
go mod tidy -e
```
(I added the -e flag, so it ignores the errors)

First, the problem is that the command `go mod tidy -e` runs with the warning 
[WARN] [2022-05-06 15:55:17,666 +0000] - Invalid Go package manager type: 'modules'

And after that, when it tries to resolve the dependencies, it says the following:
```
To ignore the vendor directory, use -mod=readonly or -mod=mod.
To sync the vendor directory, run:
go mod vendor
```
I tried to add the flags and ran  `go mod tidy -e -mod=readonly` and also `go mod tidy -e -mod=mod`

but in both cases got the following error : 
```
flag provided but not defined: -mod
usage: go mod tidy [-e] [-v] [-go=version] [-compat=version]
Run 'go help mod tidy' for details.
```
Has the -mod flag been deprecated? Does anyone know how to solve this issue?

Thank you in advance.
Kind regards, 
Maria

**Comment by seankhliao** [comment]
> [WARN] [2022-05-06 15:55:17,666 +0000] - Invalid Go package manager type: 'modules'

Is not message created by the `go` command.

`-mod` is still there it isn't for the mod tidy subcommand.

It looks like you are using some other wrapper tool, please direct your questions to them.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
