### ISSUE TITLE
cmd/compile:  internal compiler error: InitLSym called twice on func

### ISSUE THREAD

**Issue by ddaa2000** [golang/go#52768]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.9 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
In go1.17.9 but not in go1.18.1

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ddaa\AppData\Local\go-build
set GOENV=C:\Users\ddaa\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\ddaa\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\ddaa\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Users\ddaa\sdk\go1.17.9
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\ddaa\sdk\go1.17.9\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.9
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\programing\go\bugReview\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ddaa\AppData\Local\Temp\go-build360413202=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
https://go.dev/play/p/OdkfxnAXSkd?v=goprev

### What did you expect to see?
compile successfully

### What did you see instead?
./prog.go:17:12: internal compiler error: InitLSym called twice on main.func1

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new

Go build failed.

**Comment by cuonglm** [comment]
Duplicated of #49029

I think this issue is not qualified for backporting.
