### ISSUE TITLE
internal/cpu: test is  unfriendly to code coverage ("over

### ISSUE THREAD

**Issue by thanm** [golang/go#52760]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.19-4e79f06dac Fri May 6 22:04:35 2022 +0000 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by ianlancetaylor** [comment]
Real bug report is #52761.
