### ISSUE TITLE
cmd/compile: compiler crash on too large channel type

### ISSUE THREAD

**Issue by ddaa2000** [golang/go#52767]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.9 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Latest release in go1.17.9, but not in go1.18.1

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ddaa\AppData\Local\go-build
set GOENV=C:\Users\ddaa\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\ddaa\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\ddaa\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Users\ddaa\sdk\go1.17.9
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\ddaa\sdk\go1.17.9\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.9
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\programing\go\bugReview\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ddaa\AppData\Local\Temp\go-build360413202=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
https://go.dev/play/p/3ViYxZ6i_5a?v=goprev

### What did you expect to see?
./prog.go:4:11: channel element type too large (>64kB)

Go build failed.

### What did you see instead?
./prog.go:4:11: internal compiler error: bad type: chan struct { Field2 [1000][1000][1000]string }

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new

Go build failed.

**Comment by dr2chase** [comment]
I'm pretty sure this is a won't-fix.  It's a 1.17 fuzzer bug fixed in 1.18 (replacing ICE with an error message) that didn't make the backport threshold back whenever we fixed it.

@dmitshur, your opinion?

**Comment by dmitshur** [comment]
I agree with this not meeting the bar for backport to 1.17, and it doesn't affect valid Go program that build successfully. We can move this issue to Go 1.18 milestone and close as fixed.

**Comment by qiulaidongfeng** [comment]
I saw this on go.dev/play in go1.20, go1.21,gotip are all outputs
./prog.go:4:2: channel element type too large (>64kB).
The issue seem to have been fixed long ago.
