### ISSUE TITLE
cmd/go: Downloaded zip file permissions in $GOMODCACHE/cache/download are too restrictive

### ISSUE THREAD

**Issue by dmgk** [golang/go#52765]
[os.CreateTemp](https://github.com/golang/go/blame/master/src/cmd/go/internal/modfetch/fetch.go#L244 ) in [downloadZip](https://github.com/golang/go/blame/master/src/cmd/go/internal/modfetch/fetch.go#L200) creates files with 0600 permissions and as a consequence, after the final [os.Rename](https://github.com/golang/go/blame/master/src/cmd/go/internal/modfetch/fetch.go#L308), the downloaded zip files are left readable only by their owner.

Such restrictive permissions create problems in build/CI environments where `go mod download` is a separate step and performed under a distinct "download" user. For example, it makes it impossible to do `go mod verify` during the build stage, if the build stage is executed under a "build" user that is distinct from the "download" user.

It's doesn't seem that making cached zip files readable by "group" and "others" (0644) would compromise cache integrity, but it would fix the above issue.

**Comment by seankhliao** [comment]
did the

**Comment by seankhliao** [comment]
does the `-modcacherw` flag do what you want?
the cache is readonly by default because of tests: https://github.com/golang/go/issues/27161#issuecomment-433102620

**Comment by dmgk** [comment]
No, `-modcacherw` sets cache directories permissions. This issue is about zip archives permissions.
