### ISSUE TITLE
access: restore go-approvers and security GitHub memberships

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#52773]
It's me again.

I think the Google bot unceremoniously dropped me from the whole Go organization.

It'd probably make sense for me to be in

- https://github.com/orgs/golang/teams/go-approvers
- https://github.com/orgs/golang/teams/security
  (to get `@golang/security` cc's, even if I'm not going to be active on them for a bit)

See https://go.dev/wiki/GithubAccess

**Comment by dr2chase** [comment]
@dmitshur @rsc PTAL

**Comment by dmitshur** [comment]
Yep, googlebot tends to do this. Re-invited. Welcome back!
