### ISSUE TITLE
[]byte type conversion to string, this cannot printf

### ISSUE THREAD

**Issue by LjtGentle** [golang/go#52780]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 windows/amd64

</pre>
my example
`var buff = []byte{123, 34, 105, 116, 101, 109, 115, 34, 58, 91, 123, 34, 108, 97, 98, 101, 108, 34, 58, 34, 97, 49, 40, 97, 84, 114, 101, 101, 231, 172, 172, 228, 184, 128, 228, 184, 170, 232, 138, 130, 231, 130, 185, 41, 34, 44, 34, 100, 101, 115, 99, 34, 58, 34, 97, 84, 114, 101, 101, 231, 172, 172, 228, 184, 128, 228, 184, 170, 232, 138, 130, 231, 130, 185, 34, 44, 34, 114, 101, 108, 97, 116, 105, 118, 101, 34, 58, 34, 97, 49, 34, 44, 34, 116, 121, 112, 101, 34, 58, 55, 44, 34, 99, 104, 105, 108, 100, 114, 101, 110, 34, 58, 123, 34, 114, 101, 102, 101, 114, 101, 110, 99, 101, 95, 97, 112, 112, 105, 100, 34, 58, 34, 116, 101, 115, 116, 58, 97, 84, 114, 101, 101, 95, 105, 100, 34, 44, 34, 114, 101, 102, 101, 114, 101, 110, 99, 101, 95, 115, 99, 104, 101, 109, 97, 105, 100, 34, 58, 34, 97, 84, 114, 101, 101, 95, 115, 99, 104, 101, 109, 97, 95, 105, 100, 34, 44, 34, 114, 101, 102, 101, 114, 101, 110, 99, 101, 95, 102, 105, 101, 108, 100, 34, 58, 34, 97, 49, 34, 44, 34, 102, 111, 114, 101, 105, 103, 110, 95, 97, 112, 112, 105, 100, 34, 58, 34, 116, 101, 115, 116, 58, 98, 84, 114, 101, 101, 95, 105, 100, 34, 44, 34, 102, 111, 114, 101, 105, 103, 110, 95, 115, 99, 104, 101, 109, 97, 105, 100, 34, 58, 34, 98, 84, 114, 101, 101, 95, 115, 99, 104, 101, 109, 97, 95, 105, 100, 34, 44, 34, 102, 111, 114, 101, 105, 103, 110, 95, 102, 105, 101, 108, 100, 34, 58, 34, 98, 50, 34, 44, 34, 109, 117, 108, 116, 105, 112, 108, 101, 34, 58, 102, 97, 108, 115, 101, 125, 125, 44, 123, 34, 108, 97, 98, 101, 108, 34, 58, 34, 97, 50, 40, 97, 84, 114, 101, 101, 231, 172, 172, 50, 228, 184, 170, 232, 138, 130, 231, 130, 185, 41, 34, 44, 34, 100, 101, 115, 99, 34, 58, 34, 97, 84, 114, 101, 101, 231, 172, 172, 50, 228, 184, 170, 232, 138, 130, 231, 130, 185, 34, 44, 34, 114, 101, 108, 97, 116, 105, 118, 101, 34, 58, 34, 97, 50, 34, 44, 34, 116, 121, 112, 101, 34, 58, 55, 44, 34, 99, 104, 105, 108, 100, 114, 101, 110, 34, 58, 110, 117, 108, 108, 125, 44, 123, 34, 108, 97, 98, 101, 108, 34, 58, 34, 97, 51, 40, 97, 84, 114, 101, 101, 231, 172, 172, 51, 228, 184, 170, 232, 138, 130, 231, 130, 185, 41, 34, 44, 34, 100, 101, 115, 99, 34, 58, 34, 97, 84, 114, 101, 101, 231, 172, 172, 51, 228, 184, 170, 232, 138, 130, 231, 130, 185, 34, 44, 34, 114, 101, 108, 97, 116, 105, 118, 101, 34, 58, 34, 97, 49, 34, 44, 34, 116, 121, 112, 101, 34, 58, 51, 44, 34, 99, 104, 105, 108, 100, 114, 101, 110, 34, 58, 110, 117, 108, 108, 125, 93, 44, 34, 110, 101, 103, 97, 116, 105, 118, 101, 34, 58, 110, 117, 108, 108, 125}
	str = string(buff)
	fmt.Println("str=", str)`

**Comment by mengzhuo** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by go101** [comment]
What is the error message?

Maybe `str = string(buff)` should be `var str = string(buff)`?
