### ISSUE TITLE
gollvm/gofrontend: when evaluates x twice in "x op= y", which was detectable if evaluating y affects x.

### ISSUE THREAD

**Issue by xqq0629** [golang/go#52811]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>
gollvm
### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
Debian
Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz (Cascade Lake)
### What did you do?

error case:
```
package main
import "fmt"
func mapscase() int {
    one := map[int]int{0: 1299}
    two := map[int]int{0: 2388}

    x := one
    x[0] += func() int {
        x = two
        return 1113
    }()

    return two[0]
}

func main() {
    a := mapscase()
    fmt.Println(a)
}
```

### What did you expect to see?
3501

### What did you see instead?
2412
[cmd/compile: "x[i] op= y" evaluates x[i] more than once](https://github.com/golang/go/issues/21687) can also be referenced.

### Error & Solution
An output of `2412` indicates that x[0] was evaluated twice as follows: once indexing into the old map to read the value 1299, and then once into the new to store the value `1299 + 1113`.

gofrontend doesn't consider such case: when evaluates x twice in "x op= y", evaluating y may affect x. In such case, y on the right should be evaluated first and x on the left should be read latter.

**Comment by heschi** [comment]
cc @thanm

**Comment by ianlancetaylor** [comment]
I don't think that the language spec provides any guarantees about the order of evaluation of this statement.  If you think that it does guarantee the order, can you explain your reasoning?  Thanks.

CC @griesemer @mdempsky

**Comment by mdempsky** [comment]
Rationale: the `x` in `x[0] += ...` should only be evaluated once. It's unspecified whether `x` is evaluated before or after the RHS function call, so `x` may evaluate to either map. But whichever map it evaluates to, we should load from and store back to the same map.

Printing `one one` demonstrates that gccgo is loading from the first map, and then writing back to the second map. That's incorrect.

**Comment by griesemer** [comment]
I would agree with that. Per the [spec](https://go.dev/ref/spec#IncDec_statements)

> The assignment proceeds in two phases. First, the operands of [index expressions](https://go.dev/ref/spec#Index_expressions) and [pointer indirections](https://go.dev/ref/spec#Address_operators) (including implicit pointer indirections in [selectors](https://go.dev/ref/spec#Selectors)) on the left and the expressions on the right are all [evaluated in the usual order](https://go.dev/ref/spec#Order_of_evaluation). Second, the assignments are carried out in left-to-right order.

So the operand `x` of `x[0]`, should be evaluated at most once.

**Comment by ianlancetaylor** [comment]
OK, thanks.

**Comment by huanglanzhiguan** [comment]
We found this issue by testing GoLLVM using the test case:
fixedbugs/issue21687.go

**Comment by mdempsky** [comment]
@huanglanzhiguan Thanks. That would have been a helpful detail to mention in the original issue report.

**Comment by ianlancetaylor** [comment]
I've written a patch for the gofrontend to attempt to fix this problem (https://go.dev/cl/405617).  When I run the initial program in this issue with the gc compiler, it prints 3501.  When I run it with the patched gofrontend, I get 2388.

This hinges on how we execute

```Go
    x[0] += func() int {
        x = two
        return 1113
    }()
```

I'm currently executing it as

```Go
    t1 := x
    t2 := 0
    t3 := func() int { x = two; return 1113 }()
    t1[t2] = t3
```

When I do that, the program prints 2388.

The only way to get 3501 is for the function to be executed before loading `x`.  I don't see why that is mandatory.

Does anybody think that the gofrontend is incorrect in printing 2388?  Does anybody think that gc is incorrect in printing 3501?  Thanks.

**Comment by mdempsky** [comment]
It's correct for the reported, obfuscated test case to print either 2388 or 3501 (2388+1113). It's just incorrect to print other values, including 2412 (1299+1113).

The original issue21687.go test case was written specifically to be flexible about order-of-evaluation variations in compilers.

The new gofrontend behavior sounds correct to me.
