### ISSUE TITLE
net/url: get file path error

### ISSUE THREAD

**Issue by Dami-star** [golang/go#52842]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://mirrors.aliyun.com/goproxy/"
GOROOT="/usr/local/go1.18.1"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go1.18.1/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="/usr/local/gcc-12.1.0/bin/gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/gosmith/bugReview/template0/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you do?
package main

import (
    "fmt"
    "net/url"
)

func main() {
    u, _ := url.Parse("file:///home/dami/Desktop/%25.txt")
    fmt.Println(u.Path)
}

### What did you expect to see?
 go run main.go
/home/dami/Desktop/%25.txt

### What did you see instead?
 go run main.go
/home/dami/Desktop/%.txt

**Comment by ZekeLu** [comment]
`%25` is the percent-encoding of `%`. `url.Parse()` will unescape `%25` to its original form `%`. So the result is correct.

See https://www.rfc-editor.org/rfc/rfc3986#section-2.4

> Because the percent ("%") character serves as the indicator for percent-encoded octets, it must be percent-encoded as "%25" for that octet to be used as data within a URI.

**Comment by Dami-star** [comment]
> `%25`是 的百分比编码`%`。`url.Parse()`将 unescape`%25`到 它 原来 的 形式`%`. 所以结果是正确的。
> 
> 见https://www.rfc-editor.org/rfc/rfc3986#section-2.4
> 
> > 因为百分比 ("%") 字符用作百分比编码八位字节的指示符，所以它必须被百分比编码为 "%25"，才能将该八位字节用作 URI 中的数据。

**Comment by Dami-star** [comment]
Ok, thanks, if the actual file is %25.txt, the url should be file:///home/dami/Desktop/%2525.txt
