### ISSUE TITLE
gccgo: internal compiler error: in set_type_index

### ISSUE THREAD

**Issue by ddaa2000** [golang/go#52841]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 linux/amd64
$ gccgo --version
gccgo (GCC) 12.1.0
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://mirrors.aliyun.com/goproxy/"
GOROOT="/usr/local/go1.18.1"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go1.18.1/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="/usr/local/gcc-12.1.0/bin/gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/gosmith/bugReview/template0/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3110484687=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
https://go.dev/play/p/lU3CSLY5h5F
using gccgo:
go build -compiler=gccgo -gccgoflags="-static-libgo

### What did you expect to see?
Compile successfully.

### What did you see instead?
# bugReview
go1: internal compiler error: in set_type_index, at go/gofrontend/export.cc:741
0x753287 Export::set_type_index(Type const*)
        ../../gcc-12.1.0/gcc/go/gofrontend/export.cc:741
0x7c2517 Export::assign_type_indices(std::vector<Named_object*, std::allocator<Named_object*> > const&)
        ../../gcc-12.1.0/gcc/go/gofrontend/export.cc:789
0x7c3a91 Export::export_globals(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Package*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Package*> > > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Package*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Package*> > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Import_init_set const&, Bindings const*, std::unordered_set<Named_object*, std::hash<Named_object*>, std::equal_to<Named_object*>, std::allocator<Named_object*> >*)
        ../../gcc-12.1.0/gcc/go/gofrontend/export.cc:645
0x81e787 Gogo::do_exports()
        ../../gcc-12.1.0/gcc/go/gofrontend/gogo.cc:5231
0x80e8bb go_parse_input_files(char const**, unsigned int, bool, bool)
        ../../gcc-12.1.0/gcc/go/gofrontend/go.cc:159
0x80a03f go_langhook_parse_file
        ../../gcc-12.1.0/gcc/go/go-lang.cc:359
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.

**Comment by heschi** [comment]
cc @ianlancetaylor
