### ISSUE TITLE
x/pkgsite: package removal request for [github.com/chaiyd/aliyun-tools]

### ISSUE THREAD

**Issue by chaiyd** [golang/go#52848]
### What is the path of the package that you would like to have removed?
- github.com/chaiyd/aliyun-tools

 
 
 
### Are you the owner of this package?
- yes

 
### What is the reason that you could not retract this package instead?
-  Rename the github address to tools-go
- new giithub address：
   - https://github.com/chaiyd/tools-go.git

**Comment by jamalc** [comment]
Done.
