### ISSUE TITLE
affected/package: Testing (with rpc server, net/rpc)

### ISSUE THREAD

**Issue by sivansha** [golang/go#52847]
### What version of Go are you using (`go version`)?
go1.18 linux/amd64
<pre>
$ go version
go1.18 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"

</pre></details>

### What did you do?
A test function register an rpc server.
when running the test function once, or more than once separately (e.g. 'go test -v -count 1 ./src/server/...' once or more ) all works fine.
However, when running with -count > 1 (e.g. 'go test -v -count 2 ./src/server/...') an error is returned about 'multiple registrations for /_goRPC_'

a full minimal example code can be found on stackOverflow:
https://stackoverflow.com/questions/72191616/net-rpc-server-stay-registered-when-running-test-more-than-once-with-the-count

### What did you expect to see?

I expected the 'count' flag to make the test to run more than once just like running it more than once manually. surely running 'go test -v -count 2...' can be expected to be equivalent to running 'go test -v -count 1...' twice? 

### What did you see instead?

Running 'go test -v -count 1' any number of times works fine, but running 'go test -v -count x...', with x > 1, fail with:
  panic: http: multiple registrations for /_goRPC_ [recovered]
	panic: http: multiple registrations for /_goRPC_

Thanks!

**Comment by seankhliao** [comment]
error looks correct, you are registering it twice in 2 runs.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by sivansha** [comment]
@seankhliao 
Hello Sean,
Base on which definition of the behavior of the 'count' flag do you conclude that this behavior is expected?

I could not find an exact definition, but common sense seems to dictated that running:
> go test -count 2...

Should behave like running:
> go test -count 1...
> go test -count 1...

I would love to understand how did you conclude that this is expected?
 
What is actually expected to my understanding is that the -count flag will make each run completely independent and the behavior I seeing seems as an abnormal behavior of the testing suite.

Could you please elaborate why do you think that the rpc registration should be kept from one iteration of the test to another? To me it seems simply no true.
