### ISSUE TITLE
x/exp/apidiff: ignore "internal" packages during comparison

### ISSUE THREAD

**Issue by pohly** [golang/go#52864]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13 (only for building)
</pre>

### Does this issue reproduce with the latest release?

Yes (of apidiff).

### What did you do?

We use apidiff in a Go project to prevent merging of PRs which break the API:
https://github.com/kubernetes/klog/blob/main/hack/verify-apidiff.sh

One PR removes an exported function from "internal/serialize": https://github.com/kubernetes/klog/pull/326

### What did you expect to see?

apidiff should not complain.

### What did you see instead?

https://github.com/kubernetes/klog/runs/6372237998?check_suite_focus=true

```
Inspecting API of ../old...
go: downloading github.com/go-logr/logr v1.2.0
go: extracting github.com/go-logr/logr v1.2.0
go: finding github.com/go-logr/logr v1.2.0
Comparing with ../old...
FAIL: k8s.io/klog/v2/internal/serialize contains incompatible changes:
- TrimDuplicates: removed
```

**Comment by heschi** [comment]
cc @jba

**Comment by jba** [comment]
@pohly, could you look at the above CL and see if it meets your needs?

I feel that it shouldn't be impossible to compare internal packages. I think a flag would help.

**Comment by pohly** [comment]
That change made it work for us without any changes on our side, thanks!

I agree that a flag may be useful for other scenarios, but disabled by default seems like the right choice.
