### ISSUE TITLE
affected/package: cmd

### ISSUE THREAD

**Issue by ChrisALiles** [golang/go#52860]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.18.1

</pre>

### What operating system and processor architecture are you using (`go env`)? darwin/amd64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
Chris>go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/chrisliles/go/bin"
GOCACHE="/Users/chrisliles/Library/Caches/go-build"
GOENV="/Users/chrisliles/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/chrisliles/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/chrisliles/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/chrisliles/go/src/github.com/ChrisALiles/LISP15/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qk/fxlbf89j76x5cy11ctzk1fg40000gn/T/go-build2860175308=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Tried to compile a program.

[
](https://go.dev/play/p/K-BFUTrBHwE)

### What did you expect to see?
Successful compilation.

### What did you see instead?
./prog.go:15:5: initialization loop for fns
	./prog.go:15:5: fns refers to
	./prog.go:21:6: applyCar refers to
	./prog.go:17:6: chek refers to
	./prog.go:15:5: fns

Go build failed.

I don't think this should be an error. The initialisation of the "fns" variable only involves a reference to the "applyCar" function, not a call to it, so it should not make any difference which functions call which.
Could I have an opinion on this please before I attempt to delve any further?
(note that the program does not make much logical sense, it's just an extraction of the perceived problem from a larger program which doe make sense).

**Comment by mengzhuo** [comment]
Could you provide/edit issue with code example?

**Comment by ChrisALiles** [comment]
https://go.dev/play/p/K-BFUTrBHwE
Sorry, I included this link originally (or tried to) - don't know what happened to it.

**Comment by ianlancetaylor** [comment]
This is not permitted by the language.  See https://go.dev/ref/spec#Package_initialization.  The initialization rules don't try to check whether code will be executed, they just check for lexical references.  This is to simplify the rules and to ensure that all Go compilers enforce the same set of rules.  You can always work around these kinds of issues by using an `init` function.

Closing because this is working as documented and intended.

**Comment by robpike** [comment]
This is behaving as defined in the language spec. See the section on Package Initialization, which reads:  

_Dependency analysis does not rely on the actual values of the variables, only on lexical references to them in the source, analyzed transitively._

**Comment by ChrisALiles** [comment]
OK thank you.
