### ISSUE TITLE
affected/package: crypto/ssh

### ISSUE THREAD

**Issue by bigbang009** [golang/go#52865]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.4 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
</pre></details>

### What did you expect to see?

When i execute command by using ssh with windows operating system, and get the stdout, there is nothing to return.
But, when i take a breakpoint or sleep in start function of session, the stdout will give the result, not empty.
![image](https://user-images.githubusercontent.com/36918717/168083073-549a0bac-bd80-463f-a321-de746b057fbc.png)

It must be appear while using ssh protocol to connect sshd which is in windows operating system. However, it does not appear in linux operating system

**Comment by heschi** [comment]
Start is asynchronous. Perhaps you meant to use Run?

This doesn't seem to be a bug in Go. If you have questions about how to use Go, see https://go.dev/wiki/Questions.

**Comment by bigbang009** [comment]
Yes，I use Run function, there is session start in Run like this.
```
func (s *Session) Run(cmd string) error {
	err := s.Start(cmd)
	if err != nil {
		return err
	}
	return s.Wait()
}
```
