### ISSUE TITLE
x/tools/gopls: The analyzers documentation doesn't mention some analyzers

### ISSUE THREAD

**Issue by pjweinb** [golang/go#52874]
### What did you do?
I read x/tools/gopls/doc/analyzers.md to try to find the setting that would turn off useless messages labelled QF1003. 

### What did you expect to see?

Some mention of QF1003, or a hint about where to find information about it.

### What did you see instead?

nothing.

**Comment by dominikh** [comment]
In the meantime, all of Staticcheck's analyzers are documented at https://staticcheck.io/docs/checks/.

**Comment by findleyr** [comment]
I think we should just clearly link to staticcheck docs.
