### ISSUE TITLE
x/pkgsite: Imported by reports 0 in error

### ISSUE THREAD

**Issue by wxolp** [golang/go#52872]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/edgeware/mp4ff/mp4

### What is your user agent?

None of your business

### Screenshot

No

### What did you do?

Just go to that page

### What did you expect to see?

If you go here:

https://pkg.go.dev/github.com/edgeware/mp4ff/mp4?tab=importedby

youll see that it is imported by other stuff.

### What did you see instead?

~~~
Imported by: 0
~~~

**Comment by jamalc** [comment]
[GetImportedBy](https://cs.opensource.google/go/x/pkgsite/+/master:internal/postgres/details.go;l=79) and [GetImportCount](https://cs.opensource.google/go/x/pkgsite/+/master:internal/postgres/details.go;l=103) are the relevant code paths here. I see two issues. GetImportedBy is version unaware and GetImportCount only returns the count for latest version (versions available in the search documents table). Compare [v0.28.0](https://deps.dev/go/github.com%2Fedgeware%2Fmp4ff/v0.28.0) and [v0.27.0](https://deps.dev/go/github.com%2Fedgeware%2Fmp4ff/v0.27.0) on deps.dev. 

/cc @jba

**Comment by jba** [comment]
We think we understand the problem and we have a fix. We'll update here when it's ready.

**Comment by jba** [comment]
This is fixed in production.
