### ISSUE TITLE
syscall: add Mmap for Solaris and Illumos?

### ISSUE THREAD

**Issue by bcmills** [golang/go#52875]
Solaris supports an [`mmap`](https://docs.oracle.com/cd/E88353_01/html/E37841/mmap-2.html) syscall.

[`x/sys/unix.Mmap`](https://pkg.go.dev/golang.org/x/sys/unix#Mmap) is defined for GOOS=solaris, and [`runtime.mmap`](https://cs.opensource.google/go/go/+/master:src/runtime/os3_solaris.go;l=396-414;drc=c3c74777bc5dcd351af6dc4811011241efe07d21) appears to use the system call as well.

And yet, even though `Mmap` exists on Solaris and `syscall.Mmap` exists on most Go Unix ports, for some reason [`syscall.Mmap`](https://pkg.go.dev/syscall#Mmap) does not appear to be defined for `GOOS=solaris` or `GOOS=illumos`.

We're looking at possibly using `syscall.Mmap` in `cmd/go` in https://go.dev/cl/403975 (CC @matloob). Would it make sense to add `syscall.Mmap`, `syscall.Munmap`, and related constants for Solaris and Illumos for consistency with other platforms?

(CC @ianlancetaylor @tklauser @golang/solaris @golang/illumos)

**Comment by ianlancetaylor** [comment]
Although the syscall package is frozen, I think that this kind of addition is OK since it matches other targets.

**Comment by tklauser** [comment]
I too think this OK.

There have been additions like this in the past when a particular function was present in `syscall` for some, but not platforms. See e.g. https://go.dev/cl/403394, https://go.dev/cl/391434, https://go.dev/cl/390714 for some recent examples where this was the case for `solaris` and `illumos`.
