### ISSUE TITLE
proposal: affected/package: 

### ISSUE THREAD

**Issue by syncMutex** [golang/go#52889]
I need to be able to do this.
```
func a() {
  return
}

func b() {
  return a()
}

b()
```

it shows an error as `a() (no value) used as value` but  neither `a()` return anything nor `b()`.

**Comment by seankhliao** [comment]
`return` requires expressions (values). There are no values so it's an error.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
