### ISSUE TITLE
access: Gerrit "approvers" group

### ISSUE THREAD

**Issue by rhysh** [golang/go#52881]
I'd like to request access to the `approvers` group on Gerrit, https://go-review.googlesource.com/#/admin/groups/1005,members . My Gerrit email address is `rhys@justin.tv`. I've been [contributing code](https://go-review.googlesource.com/q/owner:rhys%2540justin.tv) on occasion for the past several years, and more frequently in the last couple releases.

CC @golang/release 

Thank you!

**Comment by heschi** [comment]
Hi Rhys,

Thank you for all your work on performance analysis and tuning! I've discussed this request with the team (/cc @golang/release), and we agreed to grant you access. I've added you to the approvers group now.

Please be familiar with the rules for voting and submitting changes as described at https://golang.org/wiki/GerritAccess#approver-access-approvers. If you're unsure or have any questions, please don't hesitate to ask us.

Thank you again for contributing, your help is greatly appreciated!
