### ISSUE TITLE
net: cannot send UDP packet in windows 11

### ISSUE THREAD

**Issue by Ovi3** [golang/go#52883]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.7 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Not try

(I only reproduce this issue on my company client. Cannot bother him for more info)
### What operating system and processor architecture are you using (`winver`)?

<details><summary><code>winver</code> Output</summary><br><pre>
$ winver
Windows OS 11 Version 21H2 (Build 22000.613)
</pre></details>

### What did you do?

```golang
package main

import (
	"net"
)

func main() {
	conn,err := net.DialUDP("udp",nil, &net.UDPAddr{
		IP: net.IPv4(8,8,8,8),
		Port: 9090,
	})

	if err != nil {
		panic(err)
	}

	_,err = conn.Write([]byte("udp test"))
	if err != nil {
		panic(err)
	}

	conn.Close()
}
```
open wireshark and run this code, there is no udp packet to 8.8.8.8:9090, and no panic error

but when I add code that reading from udp connection. It work:
```golang
package main

import (
	"net"
	"time"
)

func main() {
	conn,err := net.DialUDP("udp",nil, &net.UDPAddr{
		IP: net.IPv4(8,8,8,8),
		Port: 9090,
	})

	if err != nil {
		panic(err)
	}

	_,err = conn.Write([]byte("udp test"))
	if err != nil {
		panic(err)
	}

	conn.SetReadDeadline(time.Now().Add(1 * time.Second))
	buf := make([]byte,1024)
	_, _, _ = conn.ReadFromUDP(buf)

	conn.Close()
}
```

I also use Python, It work too:

```python
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.sendto(b"test", ('8.8.8.8', 9090))
```

So I think maybe it's not windows 11 problem.

**Comment by heschi** [comment]
cc @ianlancetaylor @neild

**Comment by neild** [comment]
Is is possible the packet is making it into a send buffer that isn't flushed when the program exits?

What happens if you insert a `select{}` after the write (causing the program to block indefinitely without exiting) instead of reading from the conn?

**Comment by Ovi3** [comment]
I add `select{}` after the write (or add `time.Sleep(3 * time.Second)`) , It works.
```golang
package main

import (
	"net"
)

func main() {
	conn,err := net.DialUDP("udp",nil, &net.UDPAddr{
		IP: net.IPv4(8,8,8,8),
		Port: 9090,
	})

	if err != nil {
		panic(err)
	}

	_,err = conn.Write([]byte("udp test"))
	if err != nil {
		panic(err)
	}

        select{}

	conn.Close()
}
```

**Comment by seankhliao** [comment]
Closing as this seems to be working
