### ISSUE TITLE
affected/package: crypto/ssh

### ISSUE THREAD

**Issue by bigbang009** [golang/go#52884]
Continue the issue discussion in [52865](https://github.com/golang/go/issues/52865)

My cod like this 
`	err = sshApi.Session.Run(cmd)

	defer sshApi.Close()
	if err != nil {
		return sshApi.GetStdOut(), sshApi.GetStdErr(), err, exc.ErrRunCmd.Code
	} else {
		return sshApi.GetStdOut(), sshApi.GetStdErr(), err, 0
	}`

`func (s *Session) Run(cmd string) error {
	err := s.Start(cmd)
	if err != nil {
		return err
	}
	return s.Wait()
}
`
if i add sleep after the position of s.ch.SendRequest of Start, i can get the stdout, if not i get nothing
![image](https://user-images.githubusercontent.com/36918717/168202840-a25efc9a-1f10-4395-b1ef-b86b86f09800.png)

it appear only in windows operating system, i don't know why.

**Comment by bigbang009** [comment]
I hope someone could give me some guidance, thanks

**Comment by mdlayher** [comment]
The issue tracker is not for questions about using Go, please see https://go.dev/wiki/Questions.
