### ISSUE TITLE
x/net/http2/h2c: h2c server hangs on empty r.Body read and fails on writes + hangs for POSTs

### ISSUE THREAD

**Issue by ldemailly** [golang/go#52882]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.2 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="arm64"
GOVERSION="go1.18.2"
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
</pre></details>

### What did you do?

h2c server - with code to read request body:

https://go.dev/play/p/yaKhF5u4ut6
```golang
package main

import (
	"crypto/tls"
	"fmt"
	"io"
	"log"
	"net"
	"net/http"
	"net/url"

	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
)

func server() {
	h2s := &http2.Server{}

	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Printf("Got %v %v request from %v\n", r.Method, r.Proto, r.RemoteAddr)
		body, err := io.ReadAll(r.Body)
		if err != nil {
			log.Fatalf("server body read err: %v\n", err)
		}
		fmt.Printf("read %d from body\n", len(body))
		w.WriteHeader(http.StatusAccepted)
		fmt.Fprintf(w, "Hello, %v; HTTP Version: %v\n\nbody:\n%s\n", r.URL.Path, r.Proto, string(body))
	})

	server := &http.Server{
		Addr:    ":8001",
		Handler: h2c.NewHandler(handler, h2s),
	}
	fmt.Printf("H2c Server starting on %s\n", server.Addr)
	err := server.ListenAndServe()
	if err != nil {
		panic(err)
	}
}

func main() {
	server()
}
```

### What did you expect to see?
```
$ curl -d bar --http2 localhost:8001/foo
Hello, /foo; HTTP Version: HTTP/2.0

body:
bar
```
to succeed - it hangs

note that --http2-prior-knowledge or --http1.1 works fine

### What did you see instead?
hang on curl side, server side:

```
H2c Server starting on :8001
Got POST HTTP/1.1 request from 127.0.0.1:57205
read 3 from body
2022/05/12 17:15:13 http: response.WriteHeader on hijacked connection from main.server.func1 (h2-bug.go:51)
2022/05/12 17:29:16 http: response.Write on hijacked connection from fmt.Fprintf (print.go:205)
```

If not doing a POST (ie without a body) the ReadAll hangs (that I could workaround by checking the method, even though it probably shouldn't hang)

**Comment by ldemailly** [comment]
Forgot to mention that this is with
```
curl 7.83.0 (aarch64-apple-darwin21.3.0) libcurl/7.83.0 (SecureTransport) OpenSSL/1.1.1o zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.47.0 librtmp/2.3 OpenLDAP/2.6.2
Release-Date: 2022-04-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zstd
```

and just rechecked, same with go1.18.2

just the error is only on 2nd write:
```
H2c Server starting on :8001
Got POST HTTP/1.1 request from 127.0.0.1:57528
read 3 from body
2022/05/12 17:29:16 http: response.Write on hijacked connection from fmt.Fprintf (print.go:205)
```

**Comment by ldemailly** [comment]
Code is also available on https://github.com/fortio/h2-bug

**Comment by heschi** [comment]
cc @neild

**Comment by ldemailly** [comment]
Thanks! Note that the same happens when trying to use ReverseProxy as well (which is how I went down this path:)

```
2022/05/14 14:21:57 http2: Framer 0x1400014e1c0: wrote SETTINGS len=18, settings: MAX_CONCURRENT_STREAMS=100, INITIAL_WINDOW_SIZE=33554432, ENABLE_PUSH=0
2022/05/14 14:21:57 http2: Framer 0x1400014e1c0: wrote HEADERS flags=END_HEADERS stream=1 len=74
web2 req: /echo?delay=1s
2022/05/14 14:21:58 http: response.WriteHeader on hijacked connection from net/http/httputil.(*ReverseProxy).ServeHTTP (reverseproxy.go:337)
2022/05/14 14:21:58 http: response.Write on hijacked connection from net/http/httputil.(*ReverseProxy).copyBuffer (reverseproxy.go:467)
```


```golang
	httpURL, _ := url.Parse("http://localhost:8080/")
	httpProxy := httputil.NewSingleHostReverseProxy(httpURL)
	mux := http.NewServeMux()

	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Printf("web req: %v\n", r.URL)
		httpProxy.ServeHTTP(w, r)
	})
	h2s := &http2.Server{}
	srv := &http.Server{
		Addr:    ":8001",
		Handler: h2c.NewHandler(mux, h2s),
	}
	//http2.ConfigureServer(srv, nil)
	log.Fatal(srv.ListenAndServe())
```
```

**Comment by ZekeLu** [comment]
I think the server is not correctly configured. Here is the revised version that works: https://go.dev/play/p/hO_OnkMS-wz

I will highlight the changes at the end of this comment.

According to the doc of https://pkg.go.dev/golang.org/x/net/http2#ConfigureServer,

> ConfigureServer must be called before s begins serving.

And here is the now deleted http2 server demo that could be helpful: https://github.com/golang/net/blob/69e39bad7dc2bbb411fa35755c46020969029fa7/http2/h2demo/h2demo.go

```diff
 package main
 
 import (
-   "crypto/tls"
    "fmt"
    "io"
    "log"
-   "net"
    "net/http"
-   "net/url"
 
    "golang.org/x/net/http2"
-   "golang.org/x/net/http2/h2c"
 )
 
 func server() {
    h2s := &http2.Server{}
 
    handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        fmt.Printf("Got %v %v request from %v\n", r.Method, r.Proto, r.RemoteAddr)
        body, err := io.ReadAll(r.Body)
        if err != nil {
            log.Fatalf("server body read err: %v\n", err)
        }
        fmt.Printf("read %d from body\n", len(body))
        w.WriteHeader(http.StatusAccepted)
        fmt.Fprintf(w, "Hello, %v; HTTP Version: %v\n\nbody:\n%s\n", r.URL.Path, r.Proto, string(body))
    })
 
+   http.HandleFunc("/", handler)
+
    server := &http.Server{
        Addr:    ":8001",
-       Handler: h2c.NewHandler(handler, h2s),
    }
+   http2.ConfigureServer(server, h2s)
    fmt.Printf("H2c Server starting on %s\n", server.Addr)
    err := server.ListenAndServe()
    if err != nil {
        panic(err)
    }
 }
 
 func main() {
    server()
 }
```

**Comment by ZekeLu** [comment]
Ah, I totally missed the h2c part. Thank you for pointing that out and sorry for making the noise.

**Comment by ldemailly** [comment]
yeah as I mentioned in the description (sorry if it's noisy/unclear) `--http2-prior-knowledge` does work fine

**Comment by neild** [comment]
The `h2c` package handles protocol upgrades by reading the initial HTTP/1 request and rewriting it into an HTTP/2 stream of bytes:
https://go.googlesource.com/net/+/refs/heads/master/http2/h2c/h2c.go#208

It then takes those converted HTTP/2 bytes, prepends them to the subsequent HTTP/2 stream sent from the client, and presents this to the HTTP/2 server impementation.

The conversion from HTTP/1 to HTTP/2 does not appear to support request bodies at all, so any initial HTTP/1 request with a body is mishandled. Also, I think reading from the request body at all (even when it's not present) may be broken due to the synthetic HTTP/2 request not including an END_STREAM flag.

To make things even more fun, a fundamental problem with this approach is that it doesn't deal with HTTP/2 flow control at all.

I honestly have no idea how to fix this without completely rearchitecting h2c support. If we want to support h2c, we should stop rewriting HTTP/1 requests into HTTP/2 and have a real mechanism for handing off an upgraded request to the HTTP/2 server.

**Comment by ldemailly** [comment]
I used the your cl branch and I can confirm this fixes the issue I reported! thanks so much! do you know when it'll be available on the main branch?

while I have you I would love an h2c upgrade client and a way for the ReverseProxy to do h2c prior knowledge (h2c:// urls?)
(the reason I need all this is to write a simple proxy that can do h1.1, h2c and grpc proxy https://github.com/fortio/proxy still doesn't work for grpc after this fix - possibly because I don't know how to change the ReverseProxy Director http.Request to tell it to try h2)

**Comment by ldemailly** [comment]
Answering my own question, I got it working !!
```golang
	rp := httputil.ReverseProxy{
		Director: Director,
		Transport: &http2.Transport{
			AllowHTTP: true,
			DialTLS: func(network, addr string, cfg *tls.Config) (net.Conn, error) {
				return net.Dial(network, addr)
			},
		},
	}
```
Still wondering how to configure as h2c upgrade though so it would work with h1.1 targets with a single transport

**Comment by ldemailly** [comment]
unfortunately because of https://github.com/golang/go/issues/44840#issuecomment-1133417501 I can't seem to use my fork to make a release (do I miss something obvious in my go.mod?)
