### ISSUE TITLE
affected/package: net/http The request could not be sent

### ISSUE THREAD

**Issue by a3sroot** [golang/go#52888]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.2 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Code

```
package main

import (
	"log"
	"net/http"
	"os"
	"syscall"
)
func processFork(nochdir, noclose int) int {
	if syscall.Getppid() == 1 {
		return 0
	}
	ret1, ret2, err := syscall.RawSyscall(syscall.SYS_FORK, 0, 0, 0)
	if err != 0 {
		return -1
	}
	if ret2 < 0 {
		os.Exit(-1)
	}
	if ret1 > 0 {
		os.Exit(0)
	}
	_ = syscall.Umask(0)

	//create the new SID for the child process
	s_ret, s_errno := syscall.Setsid()
	if s_errno != nil {
		log.Printf("Error: syscall.Setsid error:%d", s_errno)
	}

	if s_ret < 0 {
		return -1
	}

	//modify the process execute directory
	if nochdir == 0 {
		os.Chdir("/")
	}

	//redirect the IO stream
	if noclose == 0 {
		f, e := os.OpenFile("/dev/null", os.O_RDWR, 0)
		if e == nil {
			fd := f.Fd()
			syscall.Dup2(int(fd), int(os.Stdin.Fd()))
			syscall.Dup2(int(fd), int(os.Stdout.Fd()))
			syscall.Dup2(int(fd), int(os.Stderr.Fd()))
		}
	}
	return 0
}
func main() {
	processFork(0,1)
	req,err := http.NewRequest("GET","http://127.0.0.1",nil)
	if err != nil {
		log.Fatal(err)
	}
	httpClient :=&http.Client{

	}
	log.Println("1111")

	_, err = httpClient.Do(req)
	if err != nil {
		return
	}

}

```
I want to use processfork to move the process to the background, but when I do so, my net/http can't send a request and will only establish a connection.
A connection will be established on Linux
No connection will be established on Darwin and there is no response

### What did you expect to see?

net/http works normally, and my process can be placed in the background.

### What did you see instead?

Net / HTTP cannot send the request normally.

**Comment by ZekeLu** [comment]
Relevant issue: #227

**Comment by mdlayher** [comment]
Per the above issue, I don't think there's anything to do here since this sort of operation is explicitly not supported in Go. Closing.
