### ISSUE TITLE
cmd/compile: <unknown line number>: internal compiler error: panic: nil node

### ISSUE THREAD

**Issue by stianhj** [golang/go#52887]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.2 linux/amd64
</pre>

Tried with `go1.18.1 linux/amd64` as well.

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/stian/.cache/go-build"
GOENV="/home/stian/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/stian/code/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/stian/code/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/stian/down/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/stian/down/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4054702887=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```go
package main

func main() {
	const a = "foo"
	a += "bar"
}
```
```sh
$ go run main.go
```

### What did you expect to see?

```
# command-line-arguments
./main.go:5:4: cannot assign to a (declared const)
```
(that's the output from version 1.17.4)

### What did you see instead?

```
# command-line-arguments
<unknown line number>: internal compiler error: panic: nil node

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

**Comment by cuonglm** [comment]
This is fixed at tip:

```
$ go version
go version devel go1.19-016d755213 Thu May 12 22:32:42 2022 +0000 linux/amd64
$ go tool compile p.go 
p.go:5:2: cannot assign to a (untyped string constant "foo")
```
