### ISSUE TITLE
affected/package: The new version doesn't support Chinese catalog, so the original project can't run.

### ISSUE THREAD

**Issue by nuan1989** [golang/go#52918]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.18

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
win10 64

### What did you do?

The previous version can download the directory with Chinese, but the new version does not support the directory with Chinese, so many old projects can't be started. There is no way to upgrade, so we can only use the old version.

### What did you expect to see?
I hope I can support Chinese catalogues as before. thank you!

### What did you see instead?
![12](https://user-images.githubusercontent.com/43518669/168510051-5a4aca31-0cd5-4264-abf1-a1860c6910bb.png)

**Comment by mengzhuo** [comment]
This is work as intended.
https://go.dev/ref/spec#ImportPath
> Implementation restriction: A compiler may restrict ImportPaths to non-empty strings using only characters belonging to [Unicode's](https://www.unicode.org/versions/Unicode6.3.0/) L, M, N, P, and S general categories (the Graphic characters without spaces) and may also exclude the characters !"#$%&'()*,:;<=>?[\]^`{|} and the Unicode replacement character U+FFFD.

**Comment by nuan1989** [comment]
> 

Ok, thank you.
