### ISSUE TITLE
x/pkgsite: package removal request for github.com/ivanglie/go-cbr-client/v2

### ISSUE THREAD

**Issue by ivanglie** [golang/go#52913]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/ivanglie/go-cbr-client/v2
 
 
### Are you the owner of this package?

I am the owner of this package
 
### What is the reason that you could not retract this package instead?

I was playing around and forked an existing project then accidentally published this package.

It does not work and I have no plans to maintain the code. There should be no risk to any builds by removing.

**Comment by jamalc** [comment]
Done.

**Comment by ivanglie** [comment]
> Done.

Thanx
