### ISSUE TITLE
cmd/dist: make.bash failed on linux/386 due to unknow symbol

### ISSUE THREAD

**Issue by erifan** [golang/go#52919]
### What version of Go are you using (`go version`)?

<pre>
$ go version
Bootstrap go version is go1.13.8 linux/386

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="386"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_386"
GCCGO="gccgo"
GO386="387"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/golang/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build482662605=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Run in linux/386 container, run:
$ linux32
$ cd golang/src
$ ./make.bash

It can also be reproduced like this on a linux/amd64 machine:
$ cd golang/src
$ linux32
$ ./make.bash

### What did you expect to see?

Build successfully.

### What did you see instead?
\# ./make.bash
Building Go cmd/dist using /usr/lib/go-1.13. (go1.13.8 linux/386)
Building Go toolchain1 using /usr/lib/go-1.13.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/386.
\# cmd/trace
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): relocation target __stack_chk_fail_local not defined
runtime/cgo(.text): relocation target __stack_chk_fail_local not defined
\# cmd/pprof
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): relocation target __stack_chk_fail_local not defined
runtime/cgo(.text): relocation target __stack_chk_fail_local not defined
\# cmd/go
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): unknown symbol __stack_chk_fail_local in pcrel
runtime/cgo(.text): relocation target __stack_chk_fail_local not defined
runtime/cgo(.text): relocation target __stack_chk_fail_local not defined
go tool dist: FAILED: /root/golang/pkg/tool/linux_386/go_bootstrap install std cmd: exit status 2

**Comment by seankhliao** [comment]
which version are you trying to build?

**Comment by erifan** [comment]
> which version are you trying to build?

The latest version.

**Comment by ianlancetaylor** [comment]
It looks like your C compiler defaults to `-fstack-check` being enabled.  That configuration is not supported by Go.  Try setting `CC="gcc -fno-stack-check"` in the environment when running make.bash.

**Comment by ianlancetaylor** [comment]
Oh, I just noticed that you are building 1.13.8, which is long out of date.  The current version is 1.18.2.  Try that version.

**Comment by erifan** [comment]
> It looks like your C compiler defaults to `-fstack-check` being enabled. That configuration is not supported by Go. Try setting `CC="gcc -fno-stack-check"` in the environment when running make.bash.

Yes, you are right. Setting `CC="gcc -fno-stack-check"` seems doesn't work, I worked around the issue by adding `-fno-stack-protector` to `CGO_CFLAGS `and `CGO_LDFLAGS`. Thanks, this is the root cause of this issue, no need to do anything in go, so close it.

**Comment by tianon** [comment]
FWIW, I'm getting the exact same failure on `linux/386` in Alpine Linux when building 1.19beta1 with Go 1.18 from Alpine's package repository as my bootstrap.

**Comment by paralin** [comment]
Ran into this building for i386 on go1.19 on Buildroot, adding  -fno-stack-protector to CGO_CFLAGS fixes it.

**Comment by nmeum** [comment]
Just for the record: I bisected this and the build failure with `-fstack-protector` was introduced in Go 1.19 with commit 2049649e8bf582bd1ee19d2e565e4e3bc3f466ea which explains why the build starting failing on i386 with Go 1.19.
