### ISSUE TITLE
x/pkgsite: skynet license

### ISSUE THREAD

**Issue by DangerCZ** [golang/go#52923]
This package's documentation is being blocked by License. Site says it's not redistributable while it actually **is redistributable**.
https://pkg.go.dev/gitlab.com/SkynetLabs/skyd@v1.5.10/skymodules/renter/contractor

**Comment by seankhliao** [comment]
seems to use a custom license https://gitlab.com/SkynetLabs/skyd/-/blob/master/LICENSE.md not recognized by OSI 

cc @jba

**Comment by jba** [comment]
Sorry for the delay in getting to this.

@seankhliao is correct. We only recognize licenses listed in our [license policy](https://pkg.go.dev/license-policy). We can also add any [OSI license](https://opensource.org/licenses/alphabetical) to that list if it isn't already there. But we cannot accept any other license at this time.
