### ISSUE TITLE
x/build: spurious `cannot find package` on plan9-arm

### ISSUE THREAD

**Issue by bcmills** [golang/go#52928]
```
#!watchflakes
post <- builder ~ `^plan9` && ` cannot find package`
```

```
go/src/runtime/cgocall.go:90:2: cannot find package "runtime/internal/sys" in:
	/boot/workdir/go/src/runtime/internal/sys
go tool dist: Failed: exit status: 'go 11148: 1'
```

`greplogs -l -e '(?ms)\Aplan9.* cannot find package' --since=2022-01-01`
[2022-05-13T19:51:03-540f8c2/plan9-arm](https://build.golang.org/log/4531b31057dbe7101bba7700302568c0d12a2be7)

Looks like probably a filesystem bug to me..?

(attn @golang/plan9)

**Comment by millerresearch** [comment]
Duplicate of #46526 - the 'fid in use' message is the significant one, showing that it's an underlying filesystem error. I changed the message to 'newfid 0xNNN in use' to try to get more useful information, but diagnosis is still elusive. It's clearly a Plan 9 problem not a go problem.
