### ISSUE TITLE
cmd/compile: using generics with -buildmode=plugin results in compiler crash

### ISSUE THREAD

**Issue by ryanjoneil** [golang/go#52937]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="darwin"
GOVERSION="go1.18.2"
</pre></details>

### What did you do?

I can compile this plugin:

```go
package main

func Foo(bar any) any {
	return bar
}

func main() {}
```

```
foo % go build --buildmode plugin
foo % ls -hl foo.so 
-rw-r--r--  1 ryan  staff   1.2M May 16 14:17 foo.so
```

But if I change `Foo` to `Foo[T any]` I get a compiler error:

```go
package main

func Foo[T any](bar T) T {
	return bar
}

func main() {}
```

```
foo % go build -buildmode=plugin
# foo
./main.go:4:9: internal compiler error: writeType func[Foo.T](Foo.T) Foo.T

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

### What did you expect to see?

I expected it to compile a `foo.so` plugin file.

### What did you see instead?

```./main.go:4:9: internal compiler error: writeType func[Foo.T](Foo.T) Foo.T```

**Comment by ianlancetaylor** [comment]
CC @randall77 @mdempsky 

```
# command-line-arguments
../../foo10.go:4:9: internal compiler error: writeType func[Foo.T](Foo.T) Foo.T

goroutine 1 [running]:
runtime/debug.Stack()
	../../go/src/runtime/debug/stack.go:24 +0x65
cmd/compile/internal/base.FatalfAt({0x0?, 0x0?}, {0xd34328, 0xc}, {0xc000461b20, 0x1, 0x1})
	../../go/src/cmd/compile/internal/base/print.go:227 +0x1d7
cmd/compile/internal/base.Fatalf(...)
	../../go/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/reflectdata.writeType(0xc00013cecc?)
	../../go/src/cmd/compile/internal/reflectdata/reflect.go:947 +0x105
cmd/compile/internal/reflectdata.WriteTabs()
	../../go/src/cmd/compile/internal/reflectdata/reflect.go:1370 +0x125
cmd/compile/internal/gc.dumpdata()
	../../go/src/cmd/compile/internal/gc/obj.go:119 +0x73
cmd/compile/internal/gc.Main(0xd60548)
	../../go/src/cmd/compile/internal/gc/main.go:319 +0x1165
main.main()
	../../go/src/cmd/compile/main.go:55 +0xdd
```

**Comment by mdempsky** [comment]
I assume we don't expect package plugin to be able to access generic functions?

If so, seems like this should be an easy fix.

**Comment by ianlancetaylor** [comment]
Certainly the plugin package is not going to be able to access an uninstantiated generic function.

It's likely that it also shouldn't be able to access an instantiated version of a generic function.

**Comment by mdempsky** [comment]
FWIW, the workaround for this in Go 1.18 is to not declare exported generic functions in your main package. E.g., rename `Foo` to `_Foo`.

I don't think this needs a backport to Go 1.18. It's something that has never worked, only affects plugins (which are relatively unused/unsupported anyway), and there's an easy workaround.

If anyone else disagrees though, feel free to request a backport. The CL should cleanly apply to the 1.18 release branch.

**Comment by ryanjoneil** [comment]
I was actually hoping on a lark that this _would_ work inside a plugin, but it makes sense why it wouldn't. It's easy enough to use `any` inside the plugin and wrap the appropriate functions with generics in the code that loads it. The biggest thing was that the error was opaque.
