### ISSUE TITLE
cmd/compile: improve fuzzer [freeze exception]

### ISSUE THREAD

**Issue by randall77** [golang/go#52948]
I'd like to request a freeze exception for getting 3 fuzzing upgrade libraries submitted. I think they are ~ready to go now but we're past the 1-week grace period. The CLs are 387334, 387335, and 387336.

The CLs are not particularly risky. When not fuzzing none of the runtime code gets executed. The compiler code is a bit more entwined but should be a no-op when fuzzing is not enabled.

@golang/release

**Comment by dmitshur** [comment]
Thanks for letting us know about this. I believe we're in agreement that this is okay. Approved.
