### ISSUE TITLE
cmd/compile: miscompilation in pointer operations

### ISSUE THREAD

**Issue by ddaa2000** [golang/go#52957]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ddaa\AppData\Local\go-build
set GOENV=C:\Users\ddaa\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\ddaa\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\ddaa\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\programing\go\bugReview\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ddaa\AppData\Local\Temp\go-build2453048728=/tmp/go-build -gno-rec
ord-gcc-switches
</pre></details>

### What did you do?
https://go.dev/play/p/PzaV1hSZ5QG

### What did you expect to see?
Print {true}

### What did you see instead?
Print {false}
Though similar to:
https://github.com/golang/go/issues/52953
This bug can be triggered by go version lower than 1.16, while the above one can only be triggered by 1.17 and 1.18

**Comment by bcmills** [comment]
It looks like this input was found through fuzzing, but it's a very non-minimal input — which makes it difficult to debug.

Can you configure the fuzzer to perform at least simple minimizations to produce clearer bug reports?

**Comment by ericlagergren** [comment]
Here's a minimal repro: https://go.dev/play/p/u_srbI_bWXm

It seems almost identical to #52953.

**Comment by ericlagergren** [comment]
@cherrymui's CL 407014 also fixes this bug.

**Comment by bcmills** [comment]
I think the fact that this also reproduces on 1.16 is likely a red herring: the pre-1.17 bug may well have been fixed in 1.17.

(And note that 1.16 is no longer supported and not receiving backport fixes.)

**Comment by bcmills** [comment]
Duplicate of #52953
