### ISSUE TITLE
Fallthrough Statement is not excepted

### ISSUE THREAD

**Issue by ad3n** [golang/go#52950]
### What version of Go are you using (`go version`)?

<pre>
go version go1.18.1 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/g2academy/Library/Caches/go-build"
GOENV="/Users/g2academy/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/g2academy/go/pkg/mod"
GONOPROXY="bitbucket.org/gotoko"
GONOSUMDB="bitbucket.org/gotoko"
GOOS="darwin"
GOPATH="/Users/g2academy/go"
GOPRIVATE="bitbucket.org/gotoko"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.18.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.18.1/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/g2academy/go/course/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wv/nv0yzj291515sqxgmy7nqjrm0000gn/T/go-build4033544454=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
```
package main

import (
	"fmt"
)

func main() {
	var pi float32 = 3.14
	switch {
	case pi == 3.14:
		fmt.Println("pi == 3.14")
		fallthrough
	case pi == 11.00:
		fmt.Println("pi == 11.00")
	default:
		fmt.Println("i'm here")
	}
}

```

<img width="364" alt="Screen Shot 2022-05-18 at 06 26 31" src="https://user-images.githubusercontent.com/7464920/168928349-29422b8e-e4a9-41e1-bf23-a84446c10b99.png">

### What did you expect to see?

The `pi == 11.00` block is executed

### What did you see instead?

The `pi == 11.00` block is not executed

**Comment by seankhliao** [comment]
looks like it's working as expected

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by ianlancetaylor** [comment]
In the future, please paste plain text as plain text, not as an image.  Thanks.
