### ISSUE TITLE
cmd/compile: miscompilation in pointer operations

### ISSUE THREAD

**Issue by ddaa2000** [golang/go#52953]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ddaa\AppData\Local\go-build
set GOENV=C:\Users\ddaa\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\ddaa\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\ddaa\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\programing\go\bugReview\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ddaa\AppData\Local\Temp\go-build2453048728=/tmp/go-build -gno-rec
ord-gcc-switches
</pre></details>

### What did you do?
https://go.dev/play/p/yxl_PHRHUyf

### What did you expect to see?
The program print true.

### What did you see instead?
The program print false.
(This bug can be found in go1.17.9, but not in go1.16.15 and before)

**Comment by mengzhuo** [comment]
cc @randall77

**Comment by orian** [comment]
@cuonglm my example has this bug without a return statement

**Comment by cherrymui** [comment]
It looks to me that the AST is fine, but the initial SSA isn't quite right. It generates a wrong value for the assignment `ret = T{Field1: *v}`

**Comment by cherrymui** [comment]
Okay, maybe the AST is indeed not quite right. `ret = T{Field: *v}` is compiled to
```
. BLOCK-init
. . AS tc(1) # x.go:12:6
. . . NAME-main.ret esc(no) Class:PAUTO Offset:0 Addrtaken OnStack Used main.T tc(1) # x.go:9:6
. . BLOCK tc(1) # x.go:12:16
. . BLOCK-List
. . . AS tc(1) # x.go:12:16
. . . . DOT main.Field1 bool tc(1) # x.go:12:16
. . . . . NAME-main.ret esc(no) Class:PAUTO Offset:0 Addrtaken OnStack Used main.T tc(1) # x.go:9:6
. . . . DEREF bool tc(1) # x.go:12:18
. . . . . NAME-main.v esc(no) Class:PAUTO Offset:0 OnStack PTR-*bool tc(1) # x.go:11:6
```
which is effectively
```
ret = T{}
ret.Field1 = *v
```
This is not equivalent to the original code as the value of `*v` changes after the first assignment (`ret=T{}`).

Perhaps we need to evaluate the RHS (`*v`) before rewriting the assignment.

**Comment by cuonglm** [comment]
> @cuonglm my example has this bug without a return statement

Thanks for better reproducible program. Sounds like the problem was introduced long time ago, at least go1.16 also print false.

**Comment by benhoyt** [comment]
FWIW, @orian's example happens as far back as Go 1.5. With such a simple repro, it's surprising this hasn't been run into (or at least reported) earlier!

```
$ go1.5.4 run t.go
false
$ go1.6.4 run t.go
false
$ go1.7.6 run t.go
false
$ go1.8.7 run t.go
false
$ go1.9.7 run t.go
false
$ go1.10.8 run t.go
false
$ go1.11.13 run t.go
false
$ go1.12.17 run t.go
false
$ go1.13.15 run t.go
false
$ go1.14.15 run t.go
false
$ go1.15.15 run t.go
false
$ go1.16.15 run t.go
false
$ go1.17.10 run t.go
false
$ go version
go version go1.18.1 linux/amd64
$ go run t.go
false
$ gotip version
go version devel go1.19-c087121daf Wed May 18 19:52:53 2022 +0000 linux/amd64
$ gotip run t.go
true
$ cat t.go
package main

import "fmt"

type T struct {
	Field1 bool
}

func main() {
	var ret T
	ret.Field1 = true
	var v *bool = &ret.Field1
	ret = T{Field1: *v}
	fmt.Println(ret.Field1)
}
```
