### ISSUE TITLE
crypto/x509: checkSignature why the loop doesn't `break` after finding `algo`?

### ISSUE THREAD

**Issue by dchaofei** [golang/go#52955]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOVERSION="go1.18"
</pre></details>

### What did you do?

I read the `go` source code and found a performance issue, checkSignature why the loop doesn't `break` after finding `algo`?
https://github.com/golang/go/blob/aedf298daf508b564e4dddc7687fff8822315a5e/src/crypto/x509/x509.go#L818-L829

### What did you expect to see?

The `for` of the checkSignature function requires an early `break`
```
	for _, details := range signatureAlgorithmDetails {
		if details.algo == algo {
			hashType = details.hash
			pubKeyAlgo = details.pubKeyAlgo
			break
		}
	}
```

### What did you see instead?

If this needs to be fixed, I'd be happy to submit a `pr`

**Comment by seankhliao** [comment]
cc @golang/security

**Comment by rolandshoemaker** [comment]
Adding a `break` seems reasonable, there should only ever be a single matching algorithm and this doesn't need to be constant time. Feel free to send a CL, although be aware that since we are in the freeze window at the moment, your change will not be merged until ~August, when the tree re-opens for 1.20 changes.
