### ISSUE TITLE
x/tools/gopls: a new internal diff implementation

### ISSUE THREAD

**Issue by findleyr** [golang/go#52966]
This is a tracking issue for landing https://go.dev/cl/396855, implementing a new internal diff algorithm to reduce our external dependencies.

(I will file a separate umbrella issue for the entire process of making this switch. This issue exists for milestone tracking).

**Comment by mvdan** [comment]
Is the CL link wrong? I see:

> internal/lsp: add an option to get notified of bug reports

**Comment by findleyr** [comment]
> Is the CL link wrong?

Whoops, indeed! Fixed. Thanks.
