### ISSUE TITLE
x/tools/gopls: update protocol generation to support unions

### ISSUE THREAD

**Issue by findleyr** [golang/go#52969]
In the implementation of #41567, it is likely that we will need to extend our support for workspace edits.

Specifically, the [WorkspaceEdit](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceEdit) protocol type supports resource operations creating, renaming, and deleting files:
```
documentChanges?: (
		[TextDocumentEdit](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentEdit)[] |
		([TextDocumentEdit](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentEdit) | [CreateFile](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#createFile) | [RenameFile](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#renameFile) | [DeleteFile](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#deleteFile))[]
	);
```

However, our protocol generation only supports `[]TextDocumentEdit`:
https://cs.opensource.google/go/x/tools/+/master:internal/lsp/protocol/tsprotocol.go;l=5702;drc=b7d757405fe14c924baefbdedd785e4c6a7a0f88

In order to implement package renaming, we'll want to rename directories, and so will need to be able to express this in our `WorkspaceEdit` response.

CC @dle8 @pjweinb

**Comment by findleyr** [comment]
@pjweinb what's left here? Of the top of my head:
- check in the new generator
- sync with Dylan's change for DocumentChanges

Anything else?

**Comment by pjweinb** [comment]
the second has already happened, and I'm struggling with the first.

**Comment by findleyr** [comment]
FYI: just filed #55080 for an issue I'm seeing with JSON marshalling now.

**Comment by findleyr** [comment]
I think we should attempt to do some additional conformance testing following #55099. One possibility would be the following:
1. capture LSP logs from e.g. our regression tests, before and after this change
2. for each test, do something silly to make the RPCs deterministic, such as sorting them
3. diff. If there's something causing noise, filter it out, repeat.

**Comment by pjweinb** [comment]
I think this is done.
(https://go-review.git.corp.google.com/c/tools/+/455475)
