### ISSUE TITLE
proxy.golang.org: files lose executable bit

### ISSUE THREAD

**Issue by yurivict** [golang/go#52999]
In this [repository](https://github.com/divVerent/aaaaxy) the file version.sh has executable permission bit.

But in this [tarball](https://proxy.golang.org/github.com/div!verent/aaaaxy/@v/v1.2.34.zip) fetched from Go servers the executable bit is gone from version.sh

**Comment by seankhliao** [comment]
Dup of #34965
Closing as working as intended https://github.com/golang/go/issues/34965#issuecomment-546053393
