### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by smallbaiprogrammer** [golang/go#52994]
go version 1.17.6
env windows 10
There is a problem when reading file by funcation readFile in package io.
The same data in last or other line, answer is different. Though their content is same. But put them in map, you can find two same keys.  
data
![image](https://user-images.githubusercontent.com/67349524/169278066-5afee50a-1ce4-4010-8d65-ba70423ee86d.png)
code
![image](https://user-images.githubusercontent.com/67349524/169278129-1d25fa8b-ef19-4e28-9f8b-1827e130dd3d.png)
result
![image](https://user-images.githubusercontent.com/67349524/169278156-117a62b1-ecf8-4e48-8228-e918b2d01504.png)

**Comment by mengzhuo** [comment]
I think those lines are different.
Could you try `fmt.Printf("%d\t%q\n", n, line)` instead?

**Comment by seankhliao** [comment]
windows newlines end with `\r\n`, splitting by `\n` isn't enough.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
