### ISSUE TITLE
x/pkgsite: permission error cs.opensource.google

### ISSUE THREAD

**Issue by mjacksonest** [golang/go#53006]
### What is the URL of the page with the issue?
 This page: 
 https://pkg.go.dev/errors@go1.18.2
links to:
 https://cs.opensource.google/go/go/+/go1.18.2:src/errors/wrap.go;l=14
 
 
### What is your user agent?
 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36

 
 
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/49253151/169410763-dfbd16ed-9345-49a8-ae61-977078f14918.png)

 
 
 
### What did you do?
 Click link to source code

 
 
 
### What did you expect to see?
 source code
 
 
### What did you see instead?
permission error

**Comment by seankhliao** [comment]
this issue tracker isn't for cs.opensource.google

**Comment by andrewstuart** [comment]
@mjacksonest if you haven't figured it out yet, or for anybody else who ends up here like me, I was able to get past this by disabling DuckDuckGo privacy essentials for this site.
