### ISSUE TITLE
cmd/gofmt: gofmt does not format indented comments

### ISSUE THREAD

**Issue by ayushr2** [golang/go#53005]
<pre>
$ /tmp/go/bin/go version
go version devel go1.19-668041e Tue May 17 18:55:46 2022 +0000 linux/amd64
</pre>

gofmt does not format indented comments anymore. Simple reproducer:

```
$ cat ~/test.go 
package test

//Top level bad comment.
func main() int {
        //Indented bad comment.
}
$ /tmp/go/bin/gofmt ~/test.go 
package test

// Top level bad comment.
func main() int {
	//Indented bad comment.
}
```

**Comment by prattmic** [comment]
cc @rsc

**Comment by prattmic** [comment]
I believe this is working as intended.

From the [proposal](https://github.com/golang/proposal/blob/master/design/51082-godocfmt.md#reformatting-doc-comments): "We propose that gofmt and go/printer reformat doc comments to a conventional presentation, updating old syntax to new syntax and standardizing details such as the indentation used for preformatted blocks, the exact spacing in lists, and so on."

Your "indented bad comment" is not a doc comment, and thus does not get formatted. That would be another proposal.

Was this a change in behavior? Then it may be a bug. I don't believe we used to do any formatting of comments, but I could be forgetting. Do you have an example of changed behavior?

**Comment by mvdan** [comment]
I agree with @prattmic - I also confirmed that Go 1.18.2's gofmt does not modify either of the two comments.

Removing from the 1.19 milestone, because the regression that the issue reports seems to not be present.
