### ISSUE TITLE
wiki: TestComments change - Assert Libraries

### ISSUE THREAD

**Issue by ObsidianCat** [golang/go#53011]
The first section, "Assert Libraries" advises not to use any libraries and brings two arguments, one of them is that "assert" stops tests earlier. The claim is simply not true.

The probably most popular testing library [testify](https://github.com/stretchr/testify) has two packages assert and require.
**asert**
> Every assert func returns a bool indicating whether the assertion was successful or not, this is useful for if you want to go on making further assertions under certain conditions.

**require**
> The require package provides same global functions as the assert package, but instead of returning a boolean result they terminate current test.

assert does not stop test execution, only require does.

**Comment by mdlayher** [comment]
There are no specific references to testify in that section and therefore I don't think there is anything to do here. Closing.
