### ISSUE TITLE
gccgo: no panic on nil pointer dereference

### ISSUE THREAD

**Issue by ddaa2000** [golang/go#53012]
### What version of Go are you using (`go version`)?

<pre>
$ gccgo -v
Using built-in specs.
COLLECT_GCC=/usr/local/gcc-12.1.0/bin/gccgo
COLLECT_LTO_WRAPPER=/usr/local/gcc-12.1.0/libexec/gcc/x86_64-pc-linux-gnu/12.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc-12.1.0/configure --prefix=/usr/local/gcc-12.1.0 --enable-languages=c,c++,go --with-arch-32=i586
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 12.1.0 (GCC) 
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://mirrors.aliyun.com/goproxy/"
GOROOT="/usr/local/go1.18.1"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go1.18.1/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="/usr/local/gcc-12.1.0/bin/gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build847055300=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
https://go.dev/play/p/x2C91_hk5IP?v=gotip

### What did you expect to see?
Program throws a panic.

### What did you see instead?
Program throws no panic in gccgo-12.1.0.

**Comment by ddaa2000** [comment]
The default or -O0 flag will not trigger this bug, the -O1 and above will trigger it

**Comment by ianlancetaylor** [comment]
This is a bug in the GCC middle-end.  I've sent https://gcc.gnu.org/pipermail/gcc-patches/2022-July/597678.html to fix it.

**Comment by ianlancetaylor** [comment]
The patch is committed to mainline GCC.
