### ISSUE TITLE
affected/package:  Cannot be used after installation

### ISSUE THREAD

**Issue by sunjunjie1314520** [golang/go#53024]
![image](https://user-images.githubusercontent.com/34414647/169665593-49854a57-0545-49dd-9e3b-089aafc77087.png)
![image](https://user-images.githubusercontent.com/34414647/169665601-447b4eb7-bb53-4426-b0cc-9bb7b5ca49ac.png)

Windows 11 Cannot be used after installation

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
