### ISSUE TITLE
affected/package: append() unexpected result with fourth element (and more)

### ISSUE THREAD

**Issue by alexeypershinov** [golang/go#53027]
### What version of Go are you using (`go version`)?

<pre>
$ go version 17.7

</pre>

### Does this issue reproduce with the latest release?
Yes, it reproduce in the latest release 1.18.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alexey.pershinov/Library/Caches/go-build"
GOENV="/Users/alexey.pershinov/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/alexey.pershinov/Projects/Go/pkg/mod"
GONOPROXY="bb.delivery-club.ru"
GONOSUMDB="bb.delivery-club.ru"
GOOS="darwin"
GOPATH="/Users/alexey.pershinov/Projects/Go"
GOPRIVATE="bb.delivery-club.ru"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.7"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/alexey.pershinov/Projects/Go/src/bb.delivery-club.ru/autoassignment/worker/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3h/cxb0w5nn1zv_r834lmm9qc500000gn/T/go-build4006142325=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
I try to append() new value by slice to slice in the for cycle in different paths.
So i have an unexpected result with appending the fourth element to the path.
See more in Golang playground snippet: https://go.dev/play/p/YqMSGESPEDK

### What did you expect to see?
I expect the that the result of native append() will be equal the result of custom appendIntSliceTest()

### What did you see instead?
The result of append() is unexpected with fourth element.

Check it, please 🙏
Thank you!

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
