### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by YangFengY** [golang/go#53033]
### What is the URL of the page with the issue?
  https://pkg.go.dev/sort@go1.18.2#example-Reverse

 
### What is your user agent?
        no agent

 
 
 
### What did you do?
 

          import (
	      "fmt"
	     "sort"
         )

      s := []int{5, 2, 6, 3, 1, 4} // unsorted
	reverse := sort.Reverse(sort.IntSlice(s))
	fmt.Printf("%v\n",reverse)

 
 
 
### What did you expect to see?
           &{4,1,3,6,2,5}
 
 
### What did you see instead?
         &{[5 2 6 3 1 4]}

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
