### ISSUE TITLE
cmd/compile: fix Unified IR known test failures in test/run.go

### ISSUE THREAD

**Issue by mdempsky** [golang/go#53058]
There are still a handful of known failures for Unified IR in test/run.go: https://github.com/golang/go/blob/0a30cf9536f06d52a214370e9eeb03f8bcfc1e6a/test/run.go#L1995

The tests where diagnostics spelling has changed are fine.

But the tests for linkname errors and channel/array type size issues need to be fixed. Off hand I'm not sure why the existing typecheck code isn't just doing the right thing for Unified IR, but I expect it should be easy to massage into working now. (There's no -G=0 mode anymore, so it's fine to move the existing error logic around, if that's the easiest solution.)

/cc @cuonglm @dr2chase

**Comment by cuonglm** [comment]
The fix for channel/array type size is trivial, I have it in my local stack for a long time. Do you want me to send CL now or wait until we have dev.unified branch?

**Comment by mdempsky** [comment]
Oh great. I think now is fine, since they're bug fixes and should be small.

FYI, I'm out of office until next Tuesday though. David or Keith may be able to review though.

**Comment by mdempsky** [comment]
Thanks @cuonglm !
