### ISSUE TITLE
affected/package: select/default (code nop fidget spinner)

### ISSUE THREAD

**Issue by joel-rieke** [golang/go#53054]
### What version of Go are you using (`go version`)?

<pre>
go version go1.17.8 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Several instances of for { select { default: <-- empty default were implemented in some code we were writing.

### What did you expect to see?
Compiler error -- indicating the egregious nature of this sort of code.

### What did you see instead?
Technically, this is legitimate code.  But intermittently (whenever the for loop is activated) cpu spins at 100%.  I know this feels like baby sitting, but I've seen this code sneak in enough, I think you'd do the whole world a favor by preventing this sort of code from being written in the first place.  I do see a warning created by one of the code analyzers, but that doesn't seem to be enough to me (I ignore code warning often in big projects, and I imagine others do to).  Now, there may be some cases where this is legitimate (I can't think of any at this moment), but eliminating the base case if at all possible seems like it would be a good thing?

**Comment by seankhliao** [comment]
Given that it is code with legitimate usecases (eg spinlocks), this is definitely a better fit for static analysis.
It is unfortunate that you choose to ignore their warnings but that isn't a strong reason to turn this into invalid code (which is a breaking language change).

**Comment by joel-rieke** [comment]
> Given that it is code with legitimate usecases (eg spinlocks), this is definitely a better fit for static analysis. It is unfortunate that you choose to ignore their warnings but that isn't a strong reason to turn this into invalid code (which is a breaking language change).

Not a matter of choosing to ignore.  Sometimes there is are many warnings that are inconsequential and you happen across a project.  Many people who are just compiling a project to use -- so we often won't look at warnings in those cases.  Sad that you closed this so quickly.

**Comment by ianlancetaylor** [comment]
@joel-rieke Sorry, there's really nothing else we can do here.  The code is valid Go.  We aren't going to change the language to make it not valid.  Our approach for this kind of issue has always been to use static analysis--and static analysis tools already detect this case.

**Comment by timothy-king** [comment]
One thing the Go team could maybe do is to try to make sure there are Go static analysis tools whose warnings are more worth not ignoring.

We can certainly add a "cmd/vet" checker to warn on each `for { select { default: [empty body]`. I don't know if this would clear the low false positives requirement for `cmd/vet`. Also if another checker is doing a good job already, this weakens the ROI for distributing a checker with significant overlap.

> I do see a warning created by one of the code analyzers, but that doesn't seem to be enough to me (I ignore code warning often in big projects, and I imagine others do to).

@joel-rieke Can you give us more details about this? What is the tool? What are its other warnings? This is the type of information that could convince us that maybe we should look into adding additional static analysis.

**Comment by joel-rieke** [comment]
> @joel-rieke Sorry, there's really nothing else we can do here. The code is valid Go. We aren't going to change the language to make it not valid. Our approach for this kind of issue has always been to use static analysis--and static analysis tools already detect this case.

Maybe it's just a matter of me figuring out a better process to trigger a build failure when something like this happens.  Maybe just need to add static analysis to our pipeline -- but I'd like it to be really lightweight so that it only looks for egregious things like this.  Though I'd like that tool to allow me to specify (watch only for this particular set of egregious things)

I do understand not adding unnecessary overhead/bloat to the compiler.  But some things like this, I think language builders could really contribute to help we programmers who make foolish errors that just chew through cpu (and electricity) from making bad mistakes like this.

**Comment by joel-rieke** [comment]
> One thing the Go team could maybe do is to try to make sure there are Go static analysis tools whose warnings are more worth not ignoring.
> 
> We can certainly add a "cmd/vet" checker to warn on each `for { select { default: [empty body]`. I don't know if this would clear the low false positives requirement for `cmd/vet`. Also if another checker is doing a good job already, this weakens the ROI for distributing a checker with significant overlap.
> 
> > I do see a warning created by one of the code analyzers, but that doesn't seem to be enough to me (I ignore code warning often in big projects, and I imagine others do to).
> 
> @joel-rieke Can you give us more details about this? What is the tool? What are its other warnings? This is the type of information that could convince us that maybe we should look into adding additional static analysis.

Yes!  I bet I could add another tool to our build pipeline to prevent things like this.  A compile flag would be easiest, but even being able to add a light weight instantiation of static analysis or cmd vet that would catch a very specific set of known CPU spinners would be really nice and take a weight off of my worry pile.
