### ISSUE TITLE
proposal: slice/list/map should support more operators, such as in, not in.

### ISSUE THREAD

**Issue by yuezhongtao** [golang/go#53067]
The current operation of built-in container types is not elegant enough. The scenarios are as follows.
1. To determine whether an element exists in the list/slice, we need to traverse the list/slice in the business code
2. To get the map key value set, you need to traverse the entire map in the business code
3. Judging whether the map contains key values is not elegant enough

The solution is as follows:
1. slice/list/map supports in and not in operators.
```
s := []string{"e1"}
if "e1" in s {
  //todo
}
if "e2" not in s {
  //todo
}
```
2. Map supports Keys(), Values() operations
```
m := make(map[string]string)
keys := m.Keys()
vals := m.Values()
```

**Comment by seankhliao** [comment]
The current plans look to be the following, with potential to move them into the standard library at some point (see #45955 #47649).

```
import "golang.org/x/exp/slices"

if slices.Contains(s, "e1") {
    // todo
}
```

```
import "golang.org/x/exp/maps"

keys := maps.Keys(m)
vals := maps.Values(m)
```

`if "e2" not in s {` is a breaking language change adding 2 new keywords, and `keys := m.Keys()` is also a language change adding methods to builtin types, I think their feasibility is low. As we already have concrete plans to handle these usecases, I'm going to close these here. Please comment if you disagree.
