### ISSUE TITLE
add new feature: visualize the code base in uml diagrams

### ISSUE THREAD

**Issue by HashemJaafar** [golang/go#53068]
I prefer for go language to add all uml diagrams to visualize the code base.
this tool will help us to learn new code base very fast and find bugs and plan the code.
to create this uml diagrams we should use command line ```go create uml [name of uml diagram] [name of the package]```

**Comment by seankhliao** [comment]
This looks like it falls outside the scope of the `go` tool, which is focused on building and testing go code.
Seems it would be a better fit for an external tool which can be developed independently outside the rigid go release cycle.

**Comment by HashemJaafar** [comment]
me to i prefer it to be out side the go tools in the start. but the new go release come i prefer it to be with go tool preinstalled to make it very popular and that will help golang to be more popular because of there tools like uml

**Comment by HashemJaafar** [comment]
> This looks like it falls outside the scope of the `go` tool, which is focused on building and testing go code.
> Seems it would be a better fit for an external tool which can be developed independently outside the rigid go release cycle.

me to i prefer it to be out side the go tools in the start. but the new go release come i prefer it to be with go tool preinstalled to make it very popular and that will help golang to be more popular because of there tools like uml
