### ISSUE TITLE
x/tools/gopls: provide quickfix for composite literals with unkeyed fields

### ISSUE THREAD

**Issue by hyangah** [golang/go#53062]
gopls provides diagnostics about composite literals with unkeyed fields.
It will be convenient if the diagnostic is accompanied with the quickfix.

![Screen Shot 2022-05-24 at 8 22 58 PM](https://user-images.githubusercontent.com/4999471/170153012-58cf90c2-7cac-463d-aab4-264d99f458f6.png)

**Comment by hyangah** [comment]
@suzmue @jamalc Can you take a look if this can be implemented while investigating on a related feature (inLayHints)?

**Comment by findleyr** [comment]
I think this can be an inLayHint suggestion (by providing [InlayHint](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_inlayHint) textedits), but it would be good to have available as a quickfix as well.

**Comment by suzmue** [comment]
A quick fix was added to add field names to struct literals with unkeyed fields. 

![addfieldnames](https://user-images.githubusercontent.com/6634754/176773424-6e9874e3-2e11-4b90-bd16-296cd198c321.gif)
