### ISSUE TITLE
advice

### ISSUE THREAD

**Issue by LIngMax** [golang/go#53078]
This article is automatically translated

Proposal
Go is great, and this has led me to a solution to make go code readability easier.
We are looking for a way to read and write (global variable concurrency without contention).

Background
Our current concurrency solutions are problematic.
The problems piled up as the project got bigger.

Option 1 is usually locked: but this approach can greatly affect code readability, especially in the if scope.
mutexb.Lock()
mutexb.Unlock()
This scheme made our million-line project code extremely complex, and failing to add it would result in an error and flash back.
Such stability is unacceptable to us. It is difficult to audit anyone without mistakes.
I even thought about switching to NodeJS because it's stable, even though it sucks up memory CG.

Option 2.  GOMAXPROCS(1) // Single thread
This approach will affect the CPU multi-core utilization, we use multi-open process approach can also achieve the goal
Concurrent reading and writing of global variables will cause an error flash back result, which is about 80% less than the occurrence of multi-core, but there are still a small number of concurrent competing flash back

Workarounds
We hope that GO can add an automatic locking mode for reading and writing global variables to avoid concurrent flashback caused by locking errors

Or something like this to increase concurrency stability
Runtime. GOMAXPROCS(1) // Single thread

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
