### ISSUE TITLE
reflect: undeprecate StringHeader, SliceHeader

### ISSUE THREAD

**Issue by rsc** [golang/go#53079]
CL https://go-review.googlesource.com/c/go/+/401434 marked these as deprecated, but if you want to do something like extract the pointer inside a string or a slice, it is unclear what you should use instead. We need to have an available answer before we ship a release with them deprecated.

See also #53003.

**Comment by bcmills** [comment]
Within `std` we currently have the [`internal/unsafeheader`](https://pkg.go.dev/internal/unsafeheader) package, which defines `String` and `Slice` structs, but they're only marginally safer and not very ergonomic either.

**Comment by dmitshur** [comment]
CC @ianlancetaylor.
