### ISSUE TITLE
x/pkgsite: package removal request for github.com/jagottsicher/hundejahre

### ISSUE THREAD

**Issue by jagottsicher** [golang/go#53088]
### What is the path of the package that you would like to have removed?
github.com/jagottsicher/hundejahre
respectively:
https://pkg.go.dev/github.com/jagottsicher/hundejahre

 
  
### Are you the owner of this package?
Yes!

 
### What is the reason that you could not retract this package instead?
Was for educational purpose only and us useless. retract does not work (or I do something wrong.

**Comment by seankhliao** [comment]
The current go.mod is invalid, it still needs the `module github.com/...` and `go 1.X` lines.

**Comment by jamalc** [comment]
Done.
