### ISSUE TITLE
affected/package: http

### ISSUE THREAD

**Issue by kasrasaeed** [golang/go#53091]
### What version of Go are you using (`go version`)?

<pre>
$ go version latest

</pre>

### What operating system and processor architecture are you using (`go env`)? linux  amd64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
running service from my  app binary on linux ubuntu 20

### What did you expect to see?
No error

### What did you see instead?
 dial tcp: lookup google.com on 127.0.0.53

I did some research, seems there is a problem with go standard library package and  It turns out that if you cross-compile Go to Darwin or Linux your programs won’t use the system DNS resolver

**Comment by seankhliao** [comment]
that is a system configuration error

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
