### ISSUE TITLE
proposal: affected/package: runtime

### ISSUE THREAD

**Issue by mappjzc** [golang/go#53108]
We have the struct p with two methods, func a() and func B()
As follows
```
type P struct {
    // ...
}

func (p *P) a() {
    // ...
}


func (p *P) B() {
    // ...
}

```

The func a is called by frame.And the func B is called by users.
As follows
```
// frame
func Create(callback *func(*P) ) {
go func() {
    for {
        p := &P{}
        p.a()
        callback(p)
    }
}()
}
```

```
// user
func main() {
  // other code
  
  Create(func(p *P) {
      p.B()
      return
  })
  
  // other code
}
```

For the performance of it. Neither A nor B have a lock.So both A and B are goroutine-unsafe.
In the above example this is fine.

But some users may use the following unconsciously.
```
// user
func main() {
  // other code
  
  Create(func(p *P) {
      go func() {
        p.B()
      }
      return
  })
  
  // other code
}
```
Most of the time, this code works fine. But very rarely, this code produces incorrect data.
Because both func a() and func B() are goroutine-unsafe, they cannot be called from two different goroutines.

In the case of complex calling relationships, such codes are difficult to detect one by one with the naked eye. And in most cases, they can pass unit tests and e2e tests correctly.

it's too bad.

So we need a solution to find all the places where B() is called across goroutines.

I need an API that can efficiently record the goroutine a pointer is in. And there is a corresponding API that can check whether the pointer is currently consistent with the goroutine in which the record was recorded.

As follow:
```
func (p *P) a() {
    //  record which goroutine runing for p. 
    API(p)
    // ...
}


func (p *P) B() {
    if API_Check(p)  {
      // ...
    } else {
        panic("It is forbidden to call method B in other gorouting.Because the method is goroutine-unsafe")
    }
}
```

I think such the API should belong to the runtime package?

There are used for no-lock methods. Therefore, as high performance as possible.

**Comment by mdlayher** [comment]
Please see https://go.dev/doc/articles/race_detector. This is a bug in your program and Go already provides facilities for detecting it. Closing.
