### ISSUE TITLE
x/time: fix rate limiter bug

### ISSUE THREAD

**Issue by zwkno1** [golang/go#53123]
https://github.com/golang/time/pull/17
我提交了这个pr，修复rate limiter的bug，有人帮我合进去吗？

**Comment by ZekeLu** [comment]
It looks like that my PR https://github.com/golang/time/pull/22 fixes the same issue with a different approach.

**Comment by mengzhuo** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
