### ISSUE TITLE
runtime: windows foreground sound after writing to stdout/err pipe

### ISSUE THREAD

**Issue by dImrich** [golang/go#53121]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.2 windows/amd64
go version go1.17.7 windows/amd64
go version go1.14 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Damian\AppData\Local\go-build
set GOENV=C:\Users\Damian\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\gopath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\gopath
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\gopath\src\github.com\dImrich\test\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Damian\AppData\Local\Temp\go-build1081402863=/tmp/go-build -gno-record-gcc-switches
</pre></details>
OS: Windows 10, Version 1909, build 18363.1556

### What did you do?
<pre>
fmt.Fprint(os.Stdout, string([]byte{7})) // Bug
fmt.Fprint(os.Stderr, string([]byte{7})  // Bug
fmt.Fprint(os.Stderr, string([]byte{6})  // Ok
fmt.Fprint(os.Stderr, string([]byte{7,11,22,33})  // Bug
fmt.Fprint(os.Stderr, "aa", string([]byte{7,10,42,63}, "bb")  // Bug
fmt.Fprint(os.Stderr, "aa", string([]byte{8,10,42,63}, "bb")  // Ok
</pre>
### What did you expect to see?
Normal behaviour without any sound playing

### What did you see instead?
I hear `C:\WINDOWS\Media\Windows Foreground.wav`, played by conhost.exe process

**Comment by ZekeLu** [comment]
> **ASCII CHARACTER #7. CHAR BEL - BELL, ALERT**
> 
> Initially was used to make a sound of bell on the terminal. Time passed and later it was used in the role of a beep on systems that didn't actually possess a physical bell.

See https://www.asciihex.com/character/control/7/0x07/bel-bell-alert

**Comment by dImrich** [comment]
- [ ]

**Comment by dImrich** [comment]
I knew it can't be bug and it's some legacy shit. I guess I should just knew that ascii control characters existed. It really ruined my day, I was working with data which had 0x07 prefix for some reason entirely not connected to control characters. It's just very bad design imo, but what do I know, I'm just dummy. I was expecting that output is just output and that invisible parts of output won't do any actions on my OS.

Thanks for the link to the fmt docs, I didn't ever used format verbs in my whole life. /Sarcasm
