### ISSUE TITLE
Golang/go wiki sidebar vandalism?

### ISSUE THREAD

**Issue by thediveo** [golang/go#53139]
The sidebar of https://github.com/golang/go/wiki shows arabic text that doesn't seem to be in any way related to this wiki, at least when running Google translate on it. Vandalism?

**Comment by seankhliao** [comment]
Removed, thanks for reporting.

**Comment by switchupcb** [comment]
@seankhliao, is that you? Oh hey man! Suprised to see you in the office on a Sunday afternoon. Let me guess. Wife made you sleep on the couch again? _Ahhh._ Don't worry bout it. Happens to the best of us. Well, I'm heading out but keep up the good work champ. See you tommorow morning!
