### ISSUE TITLE
idea to make go faster and still easy.

### ISSUE THREAD

**Issue by HashemJaafar** [golang/go#53130]
### i have idea to make go faster and still easy.
i see in **rust** they use Ownership and borrowing to make faster program but it is difficult to use .
the idea i have is to add two **keyword** the first **keyword** is `unsafe` like **rust** the second is `Ownership` the `Ownership` is just keyword that start code block like `unsafe`.
this two keyword will make **golang** code work very fast and still easy to read and write.
**just to know if they add this two keyword in golang new version i don't think old code will brock.**

**Comment by mengzhuo** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
