### ISSUE TITLE
x/build/cmd/relui: manually retry failed tasks

### ISSUE THREAD

**Issue by toothrot** [golang/go#53165]
In relui, tasks occasionally fail. It would be nice if there were an mechanism for retrying a task. This is particularly important for the release test stage, which can be flaky.

**Comment by dmitshur** [comment]
This will be very helpful.

Just mentioning that [task.ErrTweetTooLong](https://pkg.go.dev/golang.org/x/build/internal/task#ErrTweetTooLong) is one example of an error type that we know to be non-retryable (for the same input) in contrast to a networking error, and so it can be used if we're looking for some test case for supporting that as part of configuring retryable tasks.
