### ISSUE TITLE
runtime: TestMutexFairness failures after 120s on openbsd-arm64-jsing with `-cpu=10`

### ISSUE THREAD

**Issue by bcmills** [golang/go#53174]
```
##### sync -cpu=10
--- FAIL: TestMutexFairness (119.29s)
    mutex_test.go:227: can't acquire Mutex in 10 seconds
FAIL
FAIL	sync	360.801s
```

`greplogs -l -e 'FAIL: TestMutexFairness' --since=2022-02-01`
[2022-05-26T14:42:13-581a63c/openbsd-arm64-jsing](https://build.golang.org/log/5b483f2833d6e83ec982061209dc0713b5d86e62)
[2022-05-18T00:45:20-1c6706c/openbsd-arm64-jsing](https://build.golang.org/log/f2a44d20008f2171c8a1771513ba16ea1bcb1faa)

(attn @4a6f656c @golang/openbsd; CC @golang/runtime)

What seems especially odd to me is that the test took almost exactly two minutes to time out both times, even though it should be failing after only 10 seconds:
https://cs.opensource.google/go/go/+/master:src/sync/mutex_test.go;l=226;drc=645d07819b2224ba4d759829443f7c6442162c69

That suggests that either the main `TestMutexFairness` goroutine isn't being scheduled, or the runtime timer heap isn't being processed.

And in both cases the overall running time of the test is also almost an exact multiple of 120 seconds.

It looks to me like something is causing goroutine scheduling (or perhaps OS thread scheduling?) to wedge until some 2-minute watchdog timer fires. #52703 may be related.

**Comment by 4a6f656c** [comment]
There appears to be a kevent related hang that can be triggered on OpenBSD 7.1 - I've applied a workaround (per #52703)

**Comment by 4a6f656c** [comment]
Also, FWIW the 120s timeout is likely coming from here:

  https://build.golang.org/log/afeae56f967155165fedf1eb30224754ebb9b18a
