### ISSUE TITLE
go build how to write output to filename

### ISSUE THREAD

**Issue by yangyile1990** [golang/go#53195]
mkdir -p bin/ && go build -ldflags "-X main.Version=v0.5.6-1-g4bb7d74" -o file ./bin/name-v0.5.6-1-g4bb7d74 ./...
stat /Users/yangyile/work/bxnpush/bin/name-v0.5.6-1-g4bb7d74: directory not found
make: *** [build] Error 1

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by yangyile1990** [comment]
Thank you! I think it's my fault，I don't konw why but this make command can build all go main packages in the project file.
