### ISSUE TITLE
crypto/tls: superfluous "return" in generate_cert.go

### ISSUE THREAD

**Issue by JeremyRand** [golang/go#53198]
### What version of Go are you using (`go version`)?

Git 46ab7a5c4f80d912f25b6b3e1044282a2a79df8b

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

linux/ppc64le, but that seems inapplicable to this issue.

### What did you do?

Read the source for `generate_cert.go`, saw what looks like a superfluous `return`.

https://github.com/golang/go/blob/46ab7a5c4f80d912f25b6b3e1044282a2a79df8b/src/crypto/tls/generate_cert.go#L157-L160

### What did you expect to see?

~~~
	if err != nil {
		log.Fatalf("Failed to open key.pem for writing: %v", err)
	}
~~~

No return, since `log.Fatalf` makes it unnecessary, just like in the rest of the file.

### What did you see instead?

~~~
	if err != nil {
		log.Fatalf("Failed to open key.pem for writing: %v", err)
		return
	}
~~~

The `return` seems unnecessary, and doesn't match the style in the rest of the file when `log.Fatalf` is used.

**Comment by dmitshur** [comment]
Thanks for reporting. This is a valid issue, albeit very minor. Please feel free to mail a CL that removes the extra `return`, since it's indeed not needed and inconsistent. (It's also okay to mail a CL right away for an issue like this.) Thanks.
