### ISSUE TITLE
runtime: on Linux, better do not treat the initial thread/task group leader as any other thread/task

### ISSUE THREAD

**Issue by thediveo** [golang/go#53210]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.2 linux/arm64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/harald/.cache/go-build"
GOENV="/home/harald/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/harald/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/harald/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/9768"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/9768/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1573233552=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### Note

This issue is based on the discussion [LockOSThread, switching (Linux kernel) namespaces: what happens to the main thread...?](https://groups.google.com/g/golang-nuts/c/dx-jweSVxHk) in golang-nuts, where I was asked by Ian Lance Tayler to file an issue here.

The service as well as the namespace switching Go modules use cgo, in case this might be relevant to this issue discussion.

### What did you do?

A Go service enters multiple Linux-kernel network namespaces in order to gather various networking data and statistics. It does so from an HTTP service handler in two different ways: first, by locking the OS thread of the current (handler) goroutine, switching the thread's network namespace, gathering information, switching back into the goroutine thread's original network namespace, and unlocking the OS thread. It uses the open source Go module github.com/thediveo/lxkns for this, and [ops.Visit](https://github.com/thediveo/lxkns/blob/aab2468af1ccf0a0f442093c5b9b90215dbd033e/ops/switchns.go#L172) in particular. Corresponding unit test checks (using github.com/thediveo/namspill) ensure that the afterwards _all_ threads are actually correctly in their original states regarding their network namespace attachments.

Second, for some operations as part of the service handler, the handler creates new goroutines that also get OS thread locked and switched into other network namespaces, but never unlocked so that when the corresponding goroutines have gathered their data, they simply end, which should terminate the associated tainted threads. This uses the [ops.Execute](https://github.com/thediveo/lxkns/blob/aab2468af1ccf0a0f442093c5b9b90215dbd033e/ops/switchns.go#L144) function in the aforementioned lxkns Go module. Again, a series of unit tests with namespace checks ensure that during testing no network namespace changes end up in unlocked threads and thus unsuspecting goroutines.

### What did you expect to see?

After the service handler finishes and the goroutines it had created as part of its service have all wound down, no thread of the service program/process should be switched into a different network namespace as when originally starting the program/process.

### What did you see instead?

The initial thread -- or task group leader -- that represents the whole program/process has its network namespace switched and not attached to the original network namespace at start anymore. Based on the Go module used for namespace switching any error in switching between namespaces is reported and logged by the service, or caught while under unit test. No namespace switching errors are logged in production, nor while under test. The fault with the initial thread, however, is reproducible in production, but unfortunately not (yet) under test.

### What happens when a Goroutine locks the initial thread and terminates while under lock?

Based on the above mentioned discussion in golang-nuts, the Go scheduler seems to assume that all threads of a process are equal. However, with respect to Linux, this isn't "fully true". The initial task of a process is the (what I think is called) "task group leader". Terminating this thread, such as in the process of a terminated thread-locked goroutine, has consequences which other threads that aren't task group leaders do not exhibit. For instance, some process-related elements in the /proc filesystem become unavailable when the task group leader terminates, while the process with the other tasks still lives on. According to Michael Kerrisk's excellent man page for [proc(5)](https://man7.org/linux/man-pages/man5/proc.5.html):

- proc/[pid]/cwd: "In a multithreaded process, the contents of this symbolic link are not available if the main thread has already terminated (typically by calling [pthread_exit(3)](https://man7.org/linux/man-pages/man3/pthread_exit.3.html))."
- /proc/[pid]/exe: "In a multithreaded process, the contents of this symbolic link are not available if the main thread has already terminated (typically by calling [pthread_exit(3)](https://man7.org/linux/man-pages/man3/pthread_exit.3.html))." (Michael is copy and pasting here)
- /proc/[pid]/fd/: "In a multithreaded process, the contents of this symbolic link are not available if the main thread has already terminated (typically by calling [pthread_exit(3)](https://man7.org/linux/man-pages/man3/pthread_exit.3.html))." (me envisioning Michael starting to wear out Ctrl-V)
(I think he forgot /proc/[pid]/fdinfo/ as one is the other's evil twin)
- /proc/[pid]/root: "In a multithreaded process, the contents of this symbolic link are not available if the main thread has already terminated (typically by calling [pthread_exit(3)](https://man7.org/linux/man-pages/man3/pthread_exit.3.html))."
- /proc/[pid]/task: guess what ... yes ... "In a multithreaded process, the contents of this symbolic link are not available if the main thread has already terminated (typically by calling [pthread_exit(3)](https://man7.org/linux/man-pages/man3/pthread_exit.3.html))."

The vast majority of Go programs will never need to worry about this situation; however, some system-level tools might need to.

Should the Go scheduler handle the initial task differently in order to avoid pulling part of a process' /proc information from under its feed? If I'm not mistaken one of the side effects of terminating a goroutine that has been scheduled to the initial thread and locked is a crash, based on comments in the runtime sources (IIRC).

Or would the workaround be to advise developers to lock the initial thread immediately in an init function to the initial goroutine and then to make sure that all potentially "deadly" activities always happen on new goroutines that are then locked to other threads, but never to the already locked initial thread? Would this be reliable?

**Comment by prattmic** [comment]
To paraphrase, what you are saying is that the runtime should never exit the thread group leader? (This is already true, see below)

More precisely, it perhaps shouldn't allow locking to the thread group leader in the first place (force the goroutine to switch threads first) so that it never needs to exit. Is my understanding correct?

> If I'm not mistaken one of the side effects of terminating a goroutine that has been scheduled to the initial thread and locked is a crash

We actually already don't allow the thread group leader to exit, see [here](https://cs.opensource.google/go/go/+/master:src/runtime/proc.go;l=1474;drc=46ab7a5c4f80d912f25b6b3e1044282a2a79df8b;bpv=1;bpt=1). So is your concern with /proc still relevant? Are you worried that tools will look at /proc/[pid] files and think that the entire thread group is inside of some namespace because the thread group leader is still in that namespace after a locked goroutine exited without leaving the namespace?

cc @golang/runtime

**Comment by thediveo** [comment]
@prattmic many thanks for the quick reply! More so as this explains what I was seeing in production. I totally overlooked how `mexit` handles `m0` especially.

So, my concern isn't relevant (anymore).

And under this condition my "workaround" by locking the initial goroutine to the initial thread/task/m0 looks like the correct thing to do.

Not allowing to lock the thread group leader would actually make it impossible to avoid the situation I've seen in production, as there's otherwise no control over m0 not (accidentally) getting scheduled to a goroutine that want to go to its grave with its personal thread in hand.

Thank you very much again for the quick answer and satisfying explanation, so I am closing this issue fully satisfied 😀
