### ISSUE TITLE
x/vuln: allow filtering for private modules

### ISSUE THREAD

**Issue by julieqiu** [golang/go#53224]
This TODO is copied from https://github.com/golang/vuln/blob/8957372cdf327922ff87e08e4ac22aabba60684d/client/client.go#L30:

Allow filtering private module, possibly at a database level. (e.g. I may want to use multiple databases, but only lookup a specific module in a subset of them)

**Comment by zpavlinovic** [comment]
Does not apply any more. govulncheck allows just a single database now (and the new client does not have this TODO anymore).
