### ISSUE TITLE
encoding/xml: unexpected EOF with AutoClose

### ISSUE THREAD

**Issue by wxolp** [golang/go#53229]
### What version of Go are you using (`go version`)?

~~~
go version go1.18 windows/amd64
~~~

### What did you do?

Using this code, everything works fine:

~~~go
package hello

import (
   "encoding/xml"
   "strings"
   "testing"
)

func TestHead(t *testing.T) {
   body := strings.NewReader(`<head><meta charset="utf-8"></head>`)
   dec := xml.NewDecoder(body)
   dec.Strict = false
   var head struct {
      Meta struct {
         Charset string `xml:"charset,attr"`
      } `xml:"meta"`
   }
   err := dec.Decode(&head)
   if err != nil {
      t.Fatal(err)
   }
}
~~~

then I tried to remove `<head>`:

~~~go
package hello

import (
   "encoding/xml"
   "strings"
   "testing"
)

func TestMeta(t *testing.T) {
   body := strings.NewReader(`<meta charset="utf-8">`)
   dec := xml.NewDecoder(body)
   dec.Strict = false
   var meta struct {
      Charset string `xml:"charset,attr"`
   }
   err := dec.Decode(&meta)
   if err != nil {
      t.Fatal(err)
   }
}
~~~

### What did you expect to see?

No error

### What did you see instead?

I get `unexpected EOF`. Note I also tried setting the `.AutoClose` and `.Entity`, but the error remains.

**Comment by dmitshur** [comment]
Thanks for reporting.

The [Strict](https://pkg.go.dev/encoding/xml#Decoder.Strict) field documentation includes:

> Strict defaults to true, enforcing the requirements of the XML specification.
> If set to false, the parser allows input containing common mistakes:
> * If an element is missing an end tag, the parser invents
>    end tags as necessary to keep the return values from Token
>   properly balanced.
> * In attribute values and character data, unknown or malformed
>    character entities (sequences beginning with &) are left alone.

This might be a bug in handling when an end tag is missing, or a feature request to handle this additional scenario. Are you able to take a look at where in the code the `unexpected EOF` is coming from?

CC @rsc via https://dev.golang.org/owners.

**Comment by seankhliao** [comment]
`AutoClose = []string{"meta"}` is necessary,
but it looks like it's not consulted if EOF is reached right after the end of the tag
https://go.dev/play/p/DeDqnVDfEio

**Comment by wxolp** [comment]
closing for lack of interest
