### ISSUE TITLE
affected/package: text/template

### ISSUE THREAD

**Issue by farmin-yrd** [golang/go#53239]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

</pre></details>

### What did you do?

https://go.dev/play/p/Br7TxggWjtr

### What did you expect to see?
with a different template name, we should get the same result as when the template name is the same as the file name
t, err := template.New("tmpl").ParseFiles("tmpl.txt") 

### What did you see instead?
when the template name is different from the file name, no result is obtained.
to fix it I modified the parseFile function in the file "/src/text/template/helper.go" at line 85 like this: 
```go
var tmpl *Template
		if t == nil {
			t = New(name)
		}
		if name == t.Name() {
			tmpl = t
		} else {
			tmpl = t.New(name)
			// what I added here
			t = tmpl
		}
		_, err = tmpl.Parse(s)
		if err != nil {
			return nil, err
		}
```

**Comment by seankhliao** [comment]
from ParseFiles:

> Since the templates created by ParseFiles are named by the base names of the argument files, t should usually have the name of one of the (base) names of the files. If it does not, depending on t's contents before calling ParseFiles, t.Execute may fail. In that case use t.ExecuteTemplate to execute a valid template.

Closing as this is working as documented
