### ISSUE TITLE
go/fmt.Println: cannot use args (variable of type []string) as type []any in argument to fmt.Println

### ISSUE THREAD

**Issue by zyxkad** [golang/go#53230]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.2 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

<https://go.dev/play/p/xbaMtJ1hR0N>

### What did you expect to see?
```
a b c
1 2 3

Program exited.
```

### What did you see instead?
```
./prog.go:9:14: cannot use args (variable of type []string) as type []any in argument to fmt.Println
./prog.go:11:14: cannot use args2 (variable of type []int) as type []any in argument to fmt.Println

Go build failed.
```

**Comment by randall77** [comment]
This is expected. In Go you cannot convert `[]int` or `[]string` to `[]any`. They have different memory layouts, among other things.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by tanghai-code** [comment]
I have the same problem. How did you solve it

**Comment by zyxkad** [comment]
> I have the same problem. How did you solve it

I defined function for cover `int`s to `any`s

**Comment by tanghai-code** [comment]
> > I have the same problem. How did you solve it
> 
> I defined function for cover `int`s to `any`s

Got it, thank you:)

**Comment by KEINOS** [comment]
All as described by @randall77. The below is to clarify for those coming through google.

```diff
package main

import "fmt"

func main() {
-	args := []string{"a", "b", "c"}
+	args := []any{"a", "b", "c"}
	fmt.Println(args...)

-	args2 := []int{1, 2, 3}
+	args2 := []any{1, 2, 3}
	fmt.Println(args2...)
	// Output:
	// a b c
	// 1 2 3
}
```
- https://go.dev/play/p/5lMSlLW4elj @ GoPlayground
