### ISSUE TITLE
compress/zlib: compressed data is different from zlib-flate

### ISSUE THREAD

**Issue by aagu** [golang/go#53232]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/aagu/.cache/go-build"
GOENV="/home/aagu/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/aagu/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/aagu/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build718718165=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I am learning about the git object storage recently. I tried to use the `compress/zlib` to implment the `git hash-object` command, the snippet of exmple code could be found at https://go.dev/play/p/_a_CGxRHTcy. The compress data will be write to the `.git/objects/[ref-header]/[ref-body]`.

### What did you expect to see?
The content of git object can be displayed as: `git cat-file -p [some digest]`.

### What did you see instead?
The content could not be read by git:
<pre>
git cat-file -p e69de29bb2d1d6434b8b29ae775ad8c2e48c5391
fatal: unable to stream e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 to stdout
</pre>

The content compress by `compress/zlib` was:
<pre>
cat .git/objects/e6/9de29bb2d1d6434b8b29ae775ad8c2e48c5391 | xxd
00000000: 785e 4aca c94f 5230 6000 0000 00ff ff    x^J..OR0`......
</pre>

I tried to decompress and recompress the content like this:
<pre>
cat .git/objects/e6/9de29bb2d1d6434b8b29ae775ad8c2e48c5391 | zlib-flate -uncompress | zlib-flate -compress=5 | xxd
00000000: 785e 4bca c94f 5230 6000 0009 b001 f0    x^K..OR0`......
</pre>
The output is now be the same with `git hash-object` does.

I have tried with compress level from 1 to 9 of the `compress/zlib` lib, but none of them can produce `785e 4bca c94f 5230 6000 0009 b001 f0`

I am not familiar with the zlib algo, can any one be kind to help me out? Thanks in advance!

**Comment by dsnet** [comment]
The underlying compression format is [RFC 1951](https://datatracker.ietf.org/doc/html/rfc1951). The Go implementation only guarantees that it produces valid output that is compatible with RFC 1951, but does not guarantee that it outputs any specific sequence of bits.

**Comment by aagu** [comment]
@dsnet Thanks for the reply, it turns out that I just called `Flush` instead of `Close` for the zlib writer, so the output write to file is not correct.
