### ISSUE TITLE
database/sql somesql wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by 943885179** [golang/go#53245]
### i want to add more data into db,but some sql, like `insert into tab(a,b,c,d,....) values(a,b,c,d,....),(a,b,c,d,....)`,some sql is ok,but some sql is error,

**Comment by 943885179** [comment]
the sql in other client is ok,but use go database/sql is error

**Comment by mengzhuo** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
