### ISSUE TITLE
x/website: https://go.dev/ref/ produces weird directory listing

### ISSUE THREAD

**Issue by willfaught** [golang/go#53243]
### What version of Go are you using (`go version`)?

N/A?

### Does this issue reproduce with the latest release?

N/A? It's observable now.

### What operating system and processor architecture are you using (`go env`)?

N/A? Observed with Safari 15.4 (17613.1.17.1.13) on macOS Monterey 12.3.1 (21E258) on an iMac (Retina 5K, 27-inch, 2017).

### What did you do?

I navigated to `https://go.dev/ref/`.

### What did you expect to see?

Some kind of summary of the available reference material, including links to the language spec and memory model.

### What did you see instead?

Some weird directory-like listing that has a link to module documentation (good), a link to some default template (bad), no links to the language spec or memory model (bad), and a link to the root page (which it calls "..", which is fine, I guess, but not very web-y) (fine).

<img width="361" alt="Screen Shot 2022-06-05 at 12 00 36 PM" src="https://user-images.githubusercontent.com/63830/172066364-71a79c6f-e528-44f4-8396-fd03be4c9f89.png">

**Comment by willfaught** [comment]
The default questions aren't applicable to the website. Perhaps add a separate website issue template?

**Comment by cherrymui** [comment]
cc @dmitshur

**Comment by dmitshur** [comment]
`https://go.dev/ref` (no trailing slash) redirects to https://go.dev/doc/#references. I suspect this issue can be resolved by making `https://go.dev/ref/` do the same.

**Comment by willfaught** [comment]
Unrelated, but why not actually move ref/* stuff under doc/ if it's going to be listed on doc/? The old paths could just redirect.

**Comment by hyangah** [comment]
The reference docs served from `/ref/*` paths are either in GOROOT/doc (go_mem.html, go_spec.html) or in x/website/_content/ref (mod.md). None of them are from x/website/_content/doc directory. Given that they are somewhat special (spec!) and serving paths are different from other docs, I think it's better to keep ref/mod.md in ref and minimize change.

In cl/413914, I added `/ref/index.md` and that helped avoid [an old issue](https://github.com/golang/website/blob/4056b246ea265f261d3bf1186f3c7954e115a2e4/internal/redirect/redirect.go#L111) that prevented setting redirect for `/ref/`.
