### ISSUE TITLE
x/pkgsite: package removal request for github.com/sari3l/requests

### ISSUE THREAD

**Issue by sari3l** [golang/go#53248]
### What is the path of the package that you would like to have removed?

github.com/sari3l/requests

### Are you the owner of this package?

yes

### What is the reason that you could not retract this package instead?

Version control mess

**Comment by seankhliao** [comment]
The module still exists and is public
Asking that it be removed here will only hide it from pkg.go.dev, it won't change go's dependency resolution or allow you to modify the existing version tags. Are you sure that's what you want?

**Comment by sari3l** [comment]
Excuse me, how long will it take to delete from pkg.go.dev?

**Comment by jamalc** [comment]
Done.

**Comment by sari3l** [comment]
Thanks a lot.
