### ISSUE TITLE
cmd/compile: internal compiler error: assertion failed

### ISSUE THREAD

**Issue by fogfish** [golang/go#53254]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

The issue is reproducible at
* darwin/amd64
* linux/amd64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kolesnik/Library/Caches/go-build"
GOENV="/Users/kolesnik/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/kolesnik/devel/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/kolesnik/devel/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/kolesnik/devel/go/src/github.com/fogfish/dynamo/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gj/dt8b38qd4xx60g9y89d5mfj40000gn/T/go-build2387231264=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

`assertion failed` error appears while trying to run `go test ./...` or `go vet ./...` on the library that uses various generic abstraction. It has started to fail at 1.18.3 release but works perfectly with 1.18.1 and also building the library with `go build ./...` works with 1.18.3.

You can reproduce an error with following commands
```
git clone https://github.com/fogfish/dynamo
cd dynamo
go test ./...
```

### What did you expect to see?

Successful compilation.

### What did you see instead?

```
go test ./...
# github.com/fogfish/dynamo/internal/ddb [github.com/fogfish/dynamo/internal/ddb.test]
/Users/kolesnik/devel/go/pkg/mod/github.com/fogfish/golem@v0.8.5/pure/hseq/hseq.go:99:11: internal compiler error: assertion failed
```

The error report fails to compile dependency but building that decencies in other context also works fine.

Something fishy is going on... any advice is welcome how to debug this issue!

**Comment by cherrymui** [comment]
Reproduced at tip. Here is the error message
```
/Users/cherryyz/gopkg/pkg/mod/github.com/fogfish/golem@v0.8.5/pure/hseq/hseq.go:99:11: internal compiler error: assertion failed

goroutine 1 [running]:
runtime/debug.Stack()
	/Users/cherryyz/src/go-tmp/src/runtime/debug/stack.go:24 +0x65
cmd/compile/internal/base.FatalfAt({0x138ceb8?, 0xc0?}, {0x193e93e, 0x10}, {0x0, 0x0, 0x0})
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/base/print.go:227 +0x1d7
cmd/compile/internal/base.Fatalf(...)
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/base.Assert(...)
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/base/print.go:239
cmd/compile/internal/noder.assert(...)
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/noder/stencil.go:27
cmd/compile/internal/noder.convertUsingDictionary(0xc00138ceb8, 0xc000455250?, {0x1805371?, 0x0?}, {0x1aa9690, 0xc001361440}, {0x1aa9ae0?, 0xc00139e640}, 0xc00132bb20)
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/noder/stencil.go:1487 +0x837
cmd/compile/internal/noder.(*genInst).dictPass.func1({0x1aa9ae0, 0xc00139e640})
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/noder/stencil.go:1330 +0x39e
cmd/compile/internal/ir.editNodes(...)
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/ir/node_gen.go:1388
cmd/compile/internal/ir.(*ReturnStmt).editChildren(0xc00138f2d0?, 0xc000e904b0)
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/ir/node_gen.go:962 +0xa2
cmd/compile/internal/ir.EditChildren(...)
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/ir/visit.go:185
cmd/compile/internal/noder.(*genInst).dictPass.func1({0x1aaacd8, 0xc00139e550})
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/noder/stencil.go:1230 +0x11b
cmd/compile/internal/ir.editNodes(...)
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/ir/node_gen.go:1388
cmd/compile/internal/ir.(*Func).editChildren(0xc000455510?, 0xc000e904b0?)
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/ir/func.go:152 +0x74
cmd/compile/internal/ir.EditChildren(...)
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/ir/visit.go:185
cmd/compile/internal/noder.(*genInst).dictPass.func1({0x1aa9e78, 0xc0013643c0})
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/noder/stencil.go:1230 +0x11b
cmd/compile/internal/noder.(*genInst).dictPass(0x1fcab00, 0xc00138ceb8)
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/noder/stencil.go:1400 +0x150
cmd/compile/internal/noder.(*genInst).buildInstantiations(0x1fcab00)
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/noder/stencil.go:78 +0x1cc
cmd/compile/internal/noder.BuildInstantiations(...)
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/noder/stencil.go:44
cmd/compile/internal/noder.(*irgen).generate(0xc000690300, {0xc000372ff0, 0x6, 0x200d760?})
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/noder/irgen.go:333 +0x3d1
cmd/compile/internal/noder.check2({0xc000372ff0, 0x6, 0x6})
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/noder/irgen.go:87 +0x14d
cmd/compile/internal/noder.LoadPackage({0xc0000be100, 0x6, 0x6})
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/noder/noder.go:84 +0x49c
cmd/compile/internal/gc.Main(0x1966cf8)
	/Users/cherryyz/src/go-tmp/src/cmd/compile/internal/gc/main.go:189 +0xbbd
main.main()
	/Users/cherryyz/src/go-tmp/src/cmd/compile/main.go:57 +0xdd
```

It appears to be from instantiating a generic function. cc @randall77

**Comment by wdvxdr1123** [comment]
Here is a simple repro.
https://go.dev/play/p/cjrTt3JyRTZ?v=gotip

```go
package main

type Interface[T any] interface {
}

func F[T any]() Interface[T] {
	var i int
	return i
}

func main() {
	F[int]()
}
```

**Comment by arvidfm** [comment]
I also got the same error. MWE of the code I was working with:

```go
package main

import "fmt"

type Interface[K any] interface {
	Name() string
}

type interfaceImpl[K any] struct {
	name string
}

func (i interfaceImpl[K]) Name() string {
	return i.name
}

type Type[T any, K any] struct {
	interfaceImpl[K]
}

func main() {
	a := Type[int, int]{
		interfaceImpl[int]{name: "hello"},
	}
	printName(a)
}

func printName[T any](k Type[T, int]) {
	fmt.Println(k.Name())
}
```

**Comment by wdvxdr1123** [comment]
@arvidfm I believe this is an another issue because of different stack backtrace. I open a new issue and will mail a fix soon.
