### ISSUE TITLE
affected/package:  arm64 crash

### ISSUE THREAD

**Issue by wangcheng711** [golang/go#53252]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.11 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=arm64
set CGO_ENABLED=1
set GOOS=android
go build

### What did you see instead?
unexpected fault address 0x1d28011b0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1d28011b0 pc=0x63af17e004]

goroutine 20 [running]:
runtime.throw({0x63aeae794c, 0x5})
        d:/go/src/runtime/panic.go:1198 +0x54 fp=0x4000145b30 sp=0x4000145b00 pc=0x63aef7c974
runtime.sigpanic()
        d:/go/src/runtime/signal_unix.go:742 +0x1e4 fp=0x4000145b70 sp=0x4000145b30 pc=0x63aef942b4
net/http.(*Server).maxHeaderBytes(...)
        d:/go/src/net/http/server.go:858
net/http.(*Server).initialReadLimitSize(...)
        d:/go/src/net/http/server.go:865
net/http.(*conn).serve(0x753c9e5638, {0x40003c1800, 0x4000482570})
        d:/go/src/net/http/server.go:1857 +0x864 fp=0x4000145fc0 sp=0x4000145b80 pc=0x63af17e004
runtime.goexit()
        d:/go/src/runtime/asm_arm64.s:1133 +0x4 fp=0x4000145fc0 sp=0x4000145fc0 pc=0x63aefaf1f4
created by net/http.(*Server).Serve
        d:/go/src/net/http/server.go:3034 +0x4b8

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x74918bc6e8, 0x72)
        d:/go/src/runtime/netpoll.go:303 +0xb4
internal/poll.(*pollDesc).wait(0x4000490098, 0x72, 0x0)
        d:/go/src/internal/poll/fd_poll_runtime.go:84 +0x38
internal/poll.(*pollDesc).waitRead(...)
        d:/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0x4000490080)
        d:/go/src/internal/poll/fd_unix.go:402 +0x1ec
net.(*netFD).accept(0x4000490080)
        d:/go/src/net/fd_unix.go:173 +0x2c
net.(*TCPListener).accept(0x40004842b8)
        d:/go/src/net/tcpsock_posix.go:140 +0x2c
net.(*TCPListener).Accept(0x40004842b8)
        d:/go/src/net/tcpsock.go:262 +0x34
net/http.(*Server).Serve(0x40004ba000, {0x63b1e74f50, 0x40004842b8})
        d:/go/src/net/http/server.go:3002 +0x37c
net/http.(*Server).ListenAndServe(0x40004ba000)
        d:/go/src/net/http/server.go:2931 +0xb0
net/http.ListenAndServe(...)
        d:/go/src/net/http/server.go:3185
github.com/gin-gonic/gin.(*Engine).Run(0x4000402d00, {0x400031ff48, 0x1, 0x1})
        d:/gocode/pkg/mod/github.com/gin-gonic/gin@v1.8.0/gin.go:379 +0x214
main.main()

goroutine 19 [IO wait]:
internal/poll.runtime_pollWait(0x74918bc5f8, 0x72)
        d:/go/src/runtime/netpoll.go:303 +0xb4
internal/poll.(*pollDesc).wait(0x4000490118, 0x72, 0x0)
        d:/go/src/internal/poll/fd_poll_runtime.go:84 +0x38
internal/poll.(*pollDesc).waitRead(...)
        d:/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x4000490100, {0x40001e5000, 0x1000, 0x1000})
        d:/go/src/internal/poll/fd_unix.go:167 +0x1dc
net.(*netFD).Read(0x4000490100, {0x40001e5000, 0x1000, 0x1000})
        d:/go/src/net/fd_posix.go:56 +0x44
net.(*conn).Read(0x4000488170, {0x40001e5000, 0x1000, 0x1000})
        d:/go/src/net/net.go:183 +0x4c
net/http.(*connReader).Read(0x4000416a50, {0x40001e5000, 0x1000, 0x1000})
        d:/go/src/net/http/server.go:780 +0x260
bufio.(*Reader).fill(0x400007aba0)
        d:/go/src/bufio/bufio.go:101 +0x10c
bufio.(*Reader).ReadSlice(0x400007aba0, 0xa)
        d:/go/src/bufio/bufio.go:360 +0x38
bufio.(*Reader).ReadLine(0x400007aba0)
        d:/go/src/bufio/bufio.go:389 +0x30
net/textproto.(*Reader).readLineSlice(0x4000416a80)
        d:/go/src/net/textproto/reader.go:57 +0x84
net/textproto.(*Reader).ReadLine(...)
        d:/go/src/net/textproto/reader.go:38
net/http.readRequest(0x400007aba0)
        d:/go/src/net/http/request.go:1029 +0x74
net/http.(*conn).readRequest(0x40004a6140, {0x63b1e77e18, 0x400041c040})
        d:/go/src/net/http/server.go:966 +0x224
net/http.(*conn).serve(0x40004a6140, {0x63b1e77ec0, 0x4000482570})
        d:/go/src/net/http/server.go:1856 +0x858
created by net/http.(*Server).Serve
        d:/go/src/net/http/server.go:3034 +0x4b8

goroutine 21 [IO wait]:
internal/poll.runtime_pollWait(0x74918bc418, 0x72)
        d:/go/src/runtime/netpoll.go:303 +0xb4
internal/poll.(*pollDesc).wait(0x40000a0198, 0x72, 0x0)
        d:/go/src/internal/poll/fd_poll_runtime.go:84 +0x38
internal/poll.(*pollDesc).waitRead(...)
        d:/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x40000a0180, {0x4000439000, 0x1000, 0x1000})
        d:/go/src/internal/poll/fd_unix.go:167 +0x1dc
net.(*netFD).Read(0x40000a0180, {0x4000439000, 0x1000, 0x1000})
        d:/go/src/net/fd_posix.go:56 +0x44
net.(*conn).Read(0x4000010008, {0x4000439000, 0x1000, 0x1000})
        d:/go/src/net/net.go:183 +0x4c
net/http.(*connReader).Read(0x4000482390, {0x4000439000, 0x1000, 0x1000})
        d:/go/src/net/http/server.go:780 +0x260
bufio.(*Reader).fill(0x4000480300)
        d:/go/src/bufio/bufio.go:101 +0x10c
bufio.(*Reader).ReadSlice(0x4000480300, 0xa)
        d:/go/src/bufio/bufio.go:360 +0x38
bufio.(*Reader).ReadLine(0x4000480300)
        d:/go/src/bufio/bufio.go:389 +0x30
net/textproto.(*Reader).readLineSlice(0x4000090cf0)
        d:/go/src/net/textproto/reader.go:57 +0x84
net/textproto.(*Reader).ReadLine(...)
        d:/go/src/net/textproto/reader.go:38
net/http.readRequest(0x4000480300)
        d:/go/src/net/http/request.go:1029 +0x74
net/http.(*conn).readRequest(0x40000da1e0, {0x63b1e77e18, 0x400048e000})
        d:/go/src/net/http/server.go:966 +0x224
net/http.(*conn).serve(0x40000da1e0, {0x63b1e77ec0, 0x4000482570})
        d:/go/src/net/http/server.go:1856 +0x858
created by net/http.(*Server).Serve
        d:/go/src/net/http/server.go:3034 +0x4b8

**Comment by cherrymui** [comment]
Thanks for the issue. Could you share the source code of your program, or how this issue can be reproduced? Thanks.
