### ISSUE TITLE
Map-clearing compiler optimization

### ISSUE THREAD

**Issue by loganmallory** [golang/go#53263]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go1.18.1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/loganmallory/Library/Caches/go-build"
GOENV="/Users/loganmallory/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/loganmallory/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/loganmallory/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.18.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.18.1/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/loganmallory/code/mandark/core/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/54/hqns0t411d73n4r2df8tbp0r0000gn/T/go-build2870026131=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Looking at this issue [#20138](https://github.com/golang/go/issues/20138) and this code merge https://go-review.googlesource.com/c/go/+/110055/  , it seems like the compiler should automatically detect map clears of the form:

```
for k := range m {
    delete(m, k)
}
```

and replace the loop with an optimized map clear.

However, when I benchmarked the following code, it appears that only the first case is optimized while the others are much slower:

```
var n = 4096

// 1 - simple case
// works as expected, compiler optimizes map clear ... 2us per clear
func Benchmark_1(b *testing.B) {
	m := make(map[int]int, n)

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		//fill up the map 50%
		b.StopTimer()
		for j := 0; j < n/2; j++ {
			m[j] = i
		}
		b.StartTimer()

		//clear the map
		for k := range m {
			delete(m, k)
		}
	}
}

// 2 - function clears the map
// compiler does not optimize map clear ... 50us per clear
func clearMap(m map[int]int) {
	for k := range m {
		delete(m, k)
	}
}
func Benchmark_2(b *testing.B) {
	m := make(map[int]int, n)

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		//fill up the map 50%
		b.StopTimer()
		for j := 0; j < n/2; j++ {
			m[j] = i
		}
		b.StartTimer()

		//clear the map
		clearMap(m)
	}
}

// 3 - map is held in a struct
// compiler does not optimize map clear ... 50us per clear
type Wrapper struct {
	m map[int]int
}
func (w *Wrapper) clearMap() {
	for k := range w.m {
		delete(w.m, k)
	}
}
func Benchmark_3(b *testing.B) {
	w := &Wrapper{m: make(map[int]int, n)}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		//fill up the map 50%
		b.StopTimer()
		for j := 0; j < n/2; j++ {
			w.m[j] = i
		}
		b.StartTimer()

		//clear the map
		w.clearMap()
	}
}
```

I also tried to explore this in Godbolt but I'm not too familiar with Go bytecode:
 1 - Simple case: https://godbolt.org/z/98oYGGrWf
 2 - Map passed to clearing function: https://godbolt.org/z/xabq3czj8
 3 - Map wrapped in struct: https://godbolt.org/z/63Wa48M4h

### What did you expect to see?
I expected that the map clears in cases 2 and 3 (50us per map clear) would be optimized by the compiler just like in case 1 (2us per map clear)

### What did you see instead?
The map clears in cases 2 and 3 do not seem to be optimized, they take 50us per map clear while case 1 takes 2us per map clear

**Comment by randall77** [comment]
I believe this is a dup of #53157.
