### ISSUE TITLE
x/pkgsite: Search result title is wrong

### ISSUE THREAD

**Issue by atilkan** [golang/go#53260]
### What is the URL of the page with the issue?
Google search result
 
 
 
### Screenshot
 

<img width="227" alt="Screen Shot 2022-06-07 at 02 39 19" src="https://user-images.githubusercontent.com/68614829/172266566-5e6c8b1a-4f13-48b3-90ba-f4c35c4a7736.png">

 
 
 
### What did you do?
 

Searched it.
 
 
### What did you expect to see?
Title: pkg.go.dev 
 
 
### What did you see instead?
Title: go.pkg.dev
Which is a proxy URL to a paid product of google cloud. I will assume this is an honest mistake and not google being evil. 

<img width="502" alt="Screen Shot 2022-06-07 at 02 44 00" src="https://user-images.githubusercontent.com/68614829/172266916-bbc74524-7b44-4923-ae34-2f49e4c4ad02.png">

**Comment by hyangah** [comment]
It looks like **a true bug in Google search**.  Other search engines don't have this issue 😉.
Unfortunately, I am afraid there isn't any  actionable from the go project to address this issue. 

Can you please report this problem (and any google.com search quality related issues) directly to google using the "Send feedback" link?
 https://support.google.com/websearch/answer/6223687?hl=en&co=GENIE.Platform%3DDesktop&oco=0
 
Thanks!

**Comment by atilkan** [comment]
I don't think this is a search bug. I think it is SEO configuration of the site.

**Comment by hyangah** [comment]
@atilkan That's great - can you share more on why you think it is SEO config issue? I was told by google it is a rare but known issue on their side, but maybe they misunderstood this issue. Any guidance or hint is greatly appreciated.

**Comment by atilkan** [comment]
It feels rather simple thing to fix. I may be wrong.
If it is a known issue there is no point of reporting it again. Thank you.
