### ISSUE TITLE
Randomness appears panic 

### ISSUE THREAD

**Issue by ddzrc** [golang/go#53265]
Randomness appears panic
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
just run in 1.17.7

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
**os：**
Linux host-6891d0637088 4.18.0-6.8.0 #1 SMP Tue May 31 06:06:47 CST 2022 x86_64 GNU/Linux

**cpu：** 
processor       : 23
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
stepping        : 2
microcode       : 0x2b
cpu MHz         : 2600.163
cache size      : 15360 KB
physical id     : 1
siblings        : 12
core id         : 5
cpu cores       : 6
apicid          : 27
initial apicid  : 27
fpu             : yes
fpu_exception   : yes
cpuid level     : 15
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bt                                  s rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c r                                  drand lahf_lm abm cpuid_fault epb invpcid_single intel_ppin tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida ara                                  t pln pts
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips        : 4799.90
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
</pre></details>

**code：**
 ```
     8: func Recover(cleanups ...func()) {
      9:         for _, cleanup := range cleanups {
=>  10:                 cleanup()
     11:         }
     12:
    13:         if p := recover(); p != nil {
    14:                 logx.ErrorStack(p)
    15:         }
```
   

        recover.go:10   0x825acb        488b1a          mov rbx, qword ptr [rdx]
        recover.go:10   0x825ace        ffd3            call rbx
 Recover use example：
defer Recover（func(){...}）
panic occur in line no 10
### What did you expect to see?

no panic

### What did you see instead?

panic

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
