### ISSUE TITLE
go/types, types2: error messages sometimes use `x|y` and sometimes `x | y` for union terms

### ISSUE THREAD

**Issue by griesemer** [golang/go#53279]
Reminder issue: Should use consistent spacing for union terms in error messages.

**Comment by griesemer** [comment]
cc: @findleyr

**Comment by griesemer** [comment]
Decision: use `x | y` to match gofmt.

**Comment by ianlancetaylor** [comment]
@griesemer Anything left to do for this issue?  Thanks.

**Comment by griesemer** [comment]
CLs are present but I ran into problems with x/tools. Will try again.

**Comment by griesemer** [comment]
Haven't gotten around to this. Not urgent. Moving to 1.20.
