### ISSUE TITLE
syscall: dropping FreeBSD 11 compatibility code in go1.20

### ISSUE THREAD

**Issue by dmgk** [golang/go#53280]
Go 1.18 release notes [state](https://tip.golang.org/doc/go1.18#freebsd) that Go 1.18 will be the last release that still supports FreeBSD 11.x, which reached EOL on September 30, 2021. Yet there's still FreeBSD 11.x compatibility code in the tree introduced by e.g. https://github.com/golang/go/commit/dc6eb200dd59dfedaa5259565b8ef1aa96a39271 and https://github.com/golang/sys/commit/5535b4e6bf4d5ce873049ff678353d726336e396 which still requires COMPAT_FREEBSD11 in the kernel.

It's probably too late for 1.19, but are there any plans to remove this 11.x compat code in 1.20 and drop COMPAT_FREEBSD11 requirement?

**Comment by ianlancetaylor** [comment]
CC @paulzhol @golang/freebsd

**Comment by paulzhol** [comment]
Hi, yes sorry I'll try to get around doing that this weekend. 
IIRC the 64-bit inode code in `syscall` and `sys/unix` does a runtime detection. So on FreeBSD 12.0 and up, the new syscalls are used. The new structs are always used, even in FreeBSD 11 with a compatibility hack to convert the old layout to the new.

The only user of `COMPAT_FREEBSD11` is  the `runtime` package for the `kevent` syscall in the poller which has an extra argument in FreeBSD 12. And it is not dynamic. Also `COMPAT_FREEBSD11` is still part of the GENERIC kernel, even on arm64.

On a related note, how do I get Gerrit credentials to trigger the build bots?

**Comment by ianlancetaylor** [comment]
> On a related note, how do I get Gerrit credentials to trigger the build bots?

See https://go.dev/wiki/GerritAccess.

**Comment by dmgk** [comment]
Thanks.
