### ISSUE TITLE
syscall: constant EPOLLET inconsistent with /usr/include/sys/epoll.h on Linux

### ISSUE THREAD

**Issue by gopherbot** [golang/go#5328]
by **dpsplunk**:

<pre>See <a href="http://tip.golang.org/pkg/syscall/">http://tip.golang.org/pkg/syscall/</a> and search in page for EPOLLET

Compare value against /usr/include/sys/epoll.h on Linux (or possibly
/usr/include/x86_64-linux-gnu/sys/epoll.h if on Ubuntu 12.04)

Go version has a negative value; whereas, Linux version is positive.

Value is positive on Linux Ubuntu 10.04 LTS and Ubuntu 12.04 LTS.</pre>

**Comment by bradfitz** [comment]
It's correct in https://godoc.org/golang.org/x/sys/unix
