### ISSUE TITLE
internal/goos: gengoos is not generating `zgoos_*.go` files

### ISSUE THREAD

**Issue by Halamix2** [golang/go#53299]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.18.3
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/halamix2/.cache/go-build"
GOENV="/home/halamix2/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/halamix2/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/halamix2/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1111947426=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I've tried to run gengoos utility

### What did you expect to see?
All `zgoos_*.go` should be (re)generated

### What did you see instead?
None of the `zgoos_*.go` files were (re)generated, due to changes in `syslist.go` introduced in https://github.com/golang/go/commit/38174b3a3514629b84dcd76878b2f536b189dd7b

**Comment by cherrymui** [comment]
cc @golang/runtime
