### ISSUE TITLE
runtime: TestFakeTime fails with fatal error "must be able to track idle limiter event"

### ISSUE THREAD

**Issue by cherrymui** [golang/go#53294]
`TestFakeTime` has some recent failures on a few builders. The output includes "fatal error", "must be able to track idle limiter event", and sometimes with bunch  of junk text.
E.g.
```
--- FAIL: TestFakeTime (6.72s)
    crash_test.go:124: running go build -o /ramdisk8GB/workdir-host-aix-ppc64-osuosl/tmp/go-build1941044317/testfaketime_-tags=faketime.exe -tags=faketime
    time_test.go:44: raw stdout: "\x00\x00PB\x11t\xef\xed\xab\x18`\x01\x00\x00\x00\aline 2\n\x00\x00PB\x11t\xef\xed\xab\x18`\x01\x00\x00\x00\aline 3\n\x00\x00PB\x11t\xef\xed\xe6\xb3*\x00\x00\x00\x00\aline 5\n\x00\x00PB\x11t\xef\xed\xe6\xb3*\x00\x00\x00\x00\x142009-11-10T23:00:01Z"
    time_test.go:45: raw stderr: "\x00\x00PB\x11t\xef\xed\xab\x18`\x00\x00\x00\x00\aline 1\n\x00\x00PB\x11t\xef\xed\xab\x18`\x02\x00\x00\x00\aline 4\n\x00\x00PB\x11t\xef\xed\xe6\xb3*\x01\x00\x00\x00\rfatal error: \x00\x00PB\x11t\xef\xed\xe6\xb3*\x01\x00\x00\x00(must be able to track idle limiter event\x00\x00PB\x11t\xef\xed\xe6\xb3*\x01\x00\x00\x00\x01\n"
    time_test.go:68: want [[{1257894000000000001 line 2
        } {1257894000000000001 line 3
        } {1257894001000000000 line 5
        } {1257894001000000000 2009-11-10T23:00:01Z}] [{1257894000000000000 line 1
        } {1257894000000000002 line 4
        }]], got [[{1257894000000000001 line 2
        } {1257894000000000001 line 3
        } {1257894001000000000 line 5
        } {1257894001000000000 2009-11-10T23:00:01Z}] [{1257894000000000000 line 1
        } {1257894000000000002 line 4
        } {1257894001000000001 fatal error: } {1257894001000000001 must be able to track idle limiter event} {1257894001000000001 
        }]]
```

[2022-06-08T17:11:00-432158b/aix-ppc64](https://build.golang.org/log/81a24b91148758f5981210b4c976b6ae2d7c3913)
[2022-06-07T23:00:27-30b929b/linux-386-longtest](https://build.golang.org/log/87e9b76ad0fe87e6534c14bdd9b70dc2cd2367c4)
[2022-06-07T17:36:56-81033fb/linux-amd64-longtest](https://build.golang.org/log/eb36642a0168a57a61904f929d8191f10dd60f7f)
[2022-06-07T16:59:48-0c3a054/linux-386-longtest](https://build.golang.org/log/5c48e658d9b337fea95b800772228b2edddb038a)
[2022-06-06T15:15:21-846f971/linux-386-longtest](https://build.golang.org/log/21ad7c3bbaa6104924f0f1fe3f9cd8b6c75100bf)
[2022-06-04T20:10:54-0293c51/linux-386-longtest](https://build.golang.org/log/cc64f1bff04b2c479cc3fee0ce0b885051ca4561)
[2022-06-03T20:54:45-54a2f4b/linux-s390x-ibm](https://build.golang.org/log/f2d5ee7a30edcdd27b63bae4e0dd2dd97e00572e)

That throw is added recently in CL https://go-review.googlesource.com/c/go/+/410122 .
cc @mknyszek @prattmic @golang/runtime

**Comment by prattmic** [comment]
The problem is in https://cs.opensource.google/go/go/+/master:src/runtime/proc.go;l=5077-5082;drc=2882786bf4cd779f166e9ced82a4da2ea0f8b1f9;bpv=1;bpt=1, which is effectively a specialized `pidleget`, but is missing the new logic added in https://go-review.googlesource.com/c/go/+/410122.

We can patch-fix that, or I think we could just replace the loop with pidleget, since any P will still steal the timer even if it doesn't own it.

**Comment by prattmic** [comment]
This bug definitely only affects faketime. I guess we should keep it as a release blocker since it could trigger on the Go playground, but is OK after beta 1.

**Comment by prattmic** [comment]
For reference, this reproduces quickly with:

```
$ cd src/runtime/testdata/testfaketime
$ go build -tags=faketime
$ while ./testfaketime; do true; done
```
