### ISSUE TITLE
net/textproto: Customize to call the function 'CanonicalMIMEHeaderKey'

### ISSUE THREAD

**Issue by angYuHao** [golang/go#53304]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

<pre>
yes
</pre>

The key of token in the request header of many servers is nonstandard. When I want to proxy the server restful api, the function 'CanonicalMIMEHeaderKey' cause me trouble
The token keyword carried by my request is 'AuthToken'
After the function CanonicalMIMEHeaderKey, it becomes 'Authtoken'
the server can't identify 'Authtoken'

**Comment by seankhliao** [comment]
use the header map directly.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
