### ISSUE TITLE
cmd/go: failed to build if the testdata contains broken symlinks

### ISSUE THREAD

**Issue by johejo** [golang/go#53305]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.19-1a2ca95ad2 Thu Jun 9 01:07:11 2022 +0000 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

No, tip only.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/mitsuoheijo/Library/Caches/go-build"
GOENV="/Users/mitsuoheijo/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mitsuoheijo/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mitsuoheijo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/mitsuoheijo/ghq/github.com/golang/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/mitsuoheijo/ghq/github.com/golang/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="devel go1.19-1a2ca95ad2 Thu Jun 9 01:07:11 2022 +0000"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/mitsuoheijo/ghq/github.com/goreleaser/goreleaser/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bq/s3vkkxm17jq79lx5qy3856zh0000gn/T/go-build2641546270=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
git clone https://github.com/goreleaser/goreleaser.git
cd goreleaser/
go build ./...
```

### What did you expect to see?

Build succeeds.

### What did you see instead?

```
stat /Users/mitsuoheijo/ghq/github.com/goreleaser/goreleaser/pkg/archive/testdata/badlink.txt: no such file or directory
pattern ./...: stat /Users/mitsuoheijo/ghq/github.com/goreleaser/goreleaser/pkg/archive/testdata/badlink.txt: no such file or directory
```

Related d65166024f3969289be5c74fd8be7d06a93264f1

I encountered the same thing in several repository builds.
- https://github.com/argoproj/argo-cd
- https://github.com/helm/helm

**Comment by cherrymui** [comment]
cc @matloob @bcmills @rsc

**Comment by johejo** [comment]
I don't know if it's the intended change, but it doesn't seem to have happened since https://github.com/golang/go/commit/36147dd1e8d8e21affbf5d8a758608e63304e4a7.

**Comment by johejo** [comment]
See #53387
