### ISSUE TITLE
cmd/go: go:embed fails with special characters in module parent directory

### ISSUE THREAD

**Issue by ryanjoneil** [golang/go#53314]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOVERSION="go1.18.3"
</pre></details>

### What did you do?

I have a simple file structure for a main package under a directory `foo`.

```txt
% tree foo
foo
└── example
    ├── baz.txt
    ├── go.mod
    └── main.go
```

`go.mod` is just the model name and Go version.

```
module example

go 1.18
```

The `main.go` embeds `baz.txt` and prints its contents.

```go
package main

import (
	_ "embed"
	"fmt"
)

//go:embed baz.txt
var baz string

func main() {
	fmt.Println(baz)
}
```

`baz.txt` contains a simple string,

```
xyzzy
```

This works as expected.

```
% cd foo/example/
example % go build
example % ./example 
xyzzy
```

If I change the parent directory of the module from `foo` to `[foo]`, `go build` cannot find `baz.txt`.

```
example % cd ../../
% mv foo '[foo]'
% cd \[foo\]/example 
example % go build
main.go:8:12: pattern baz.txt: no matching files found
```

### What did you expect to see?

I expected the same behavior in both cases (`go build` succeeding).

### What did you see instead?

`go build` cannot resolve the embed if a parent directory of the module contains square brackets. It doesn't seem like this should matter, since it is outside the module itself and is a valid directory name.

**Comment by cherrymui** [comment]
There may be a restriction on the file path. But I couldn't find the documentation.

cc @rsc @bcmills
