### ISSUE TITLE
dial tcp: i/o timeout || hangs while running make for lxc/distrobuilder

### ISSUE THREAD

**Issue by Zhme-Kakarot** [golang/go#53320]
I am unsure what to post here, but I have this so far.

`../go/pkg/mod/github.com/klauspost/pgzip@v1.2.5/gunzip.go:26:2: github.com/klauspost/compress@v1.15.1: Get "https://storage.googleapis.com/proxy-golang-org-prod/b6d1094046d27988-github.com:klauspost:compress-v1.15.1.zip?Expires=1654908337&GoogleAccessId=gcs-urlsigner-prod%40golang-modproxy.iam.gserviceaccount.com&Signature=LxTsPDy8OHM5cQ%2FChFTCWSa4%2BVZ5r0KxLmCaXptMQxPI6oNxoF0zhelE%2BI5L4ZTx1v1tlmj48mkpZnow69c5UrGZM6egO44fAKxn0rC3B4ygfJ62e5BnAiZmJuT4vkMB44F8ht14bXYlHBN9Tz%2BbaZxZm2Art%2FR9xTXYMZWGUhCNTjYTLUrIs4HMMWQlq6riW486EI822c3VmXJd1LlcpZi%2FKlT9J6kymjN%2BZenwlgxWBZ594Jt9IdJH%2BlBXzVq6t8OGLRy%2FmcILBp9h3rIQ3u%2F4br8Z6ZXCMZYnyl6wbtMc17bMSTYuzVgWRAlFnBE%2F61eiFAhZFi21ES4DGI6Dcw%3D%3D": dial tcp: i/o timeout
make: *** [Makefile:9: default] Error 1`

I have tried to clear the cache which appears to make the output more successful, but I know not.

Here is a most robust output from `make`

`┌─[user@parrot]─[~/distrobuilder]
└──╼ $make
gofmt -s -w .
go install -v ./...
go: downloading github.com/lxc/lxd v0.0.0-20220330110539-f7a4698244cb
go: downloading github.com/sirupsen/logrus v1.8.1
go: downloading github.com/flosch/pongo2 v0.0.0-20200913210552-0d938eb266f3
go: downloading github.com/spf13/cobra v1.4.0
go: downloading golang.org/x/sys v0.0.0-20220330033206-e17cdc41300f
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading gopkg.in/flosch/pongo2.v3 v3.0.0-20141028000813-5e81b817a0c4
go: downloading github.com/mudler/docker-companion v0.4.6-0.20211015133729-bd4704fad372
go: downloading gopkg.in/antchfx/htmlquery.v1 v1.2.2
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/gorilla/websocket v1.5.0
go: downloading gopkg.in/inconshreveable/log15.v2 v2.0.0-20200109203555-b30bc20e4fd1
go: downloading github.com/pkg/sftp v1.13.4
go: downloading gopkg.in/macaroon-bakery.v2 v2.3.0
go: downloading github.com/containerd/containerd v1.6.2
go: downloading github.com/docker/docker v20.10.14+incompatible
go: downloading github.com/fsouza/go-dockerclient v1.7.10
go: downloading github.com/heroku/docker-registry-client v0.0.0-20211012143308-9463674c8930
go: downloading github.com/opencontainers/umoci v0.4.8-0.20211009121349-9c76304c034d
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading github.com/urfave/cli v1.22.5
go: downloading github.com/antchfx/xpath v1.2.0
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading golang.org/x/net v0.0.0-20220325170049-de3da57026de
go: downloading github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
go: downloading github.com/pborman/uuid v1.2.1
go: downloading github.com/robfig/cron/v3 v3.0.1
go: downloading github.com/go-stack/stack v1.8.1
go: downloading github.com/mattn/go-colorable v0.1.12
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading github.com/kr/fs v0.1.0
go: downloading golang.org/x/crypto v0.0.0-20220321153916-2c7772ba3064
go: downloading github.com/juju/webbrowser v1.0.0
go: downloading github.com/julienschmidt/httprouter v1.3.0
go: downloading gopkg.in/errgo.v1 v1.0.1
go: downloading gopkg.in/httprequest.v1 v1.2.1
go: downloading gopkg.in/macaroon.v2 v2.1.0
go: downloading github.com/go-macaroon-bakery/macaroonpb v1.0.0
go: downloading github.com/rogpeppe/fastuuid v1.2.0
go: downloading github.com/containerd/continuity v0.2.2
go: downloading github.com/docker/distribution v2.8.1+incompatible
go: downloading github.com/opencontainers/go-digest v1.0.0
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.1
go: downloading github.com/apex/log v1.9.0
go: downloading github.com/cyphar/filepath-securejoin v0.2.3
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/opencontainers/image-spec v1.0.2
go: downloading github.com/opencontainers/runtime-spec v1.0.3-0.20210326190908-1c3f411f0417
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/rootless-containers/proto/go-proto v0.0.0-20210921234734-69430b6543fb
go: downloading github.com/vbatts/go-mtree v0.5.0
go: downloading github.com/google/uuid v1.3.0
go: downloading golang.org/x/text v0.3.7
go: downloading google.golang.org/protobuf v1.28.0
go: downloading golang.org/x/sync v0.0.0-20210220032951-036812b2e83c
go: downloading github.com/moby/term v0.0.0-20210619224110-3f7ff695adc6
go: downloading github.com/morikuni/aec v1.0.0
go: downloading github.com/russross/blackfriday/v2 v2.1.0
go: downloading github.com/docker/libtrust v0.0.0-20160708172513-aabc10ec26b7
go: downloading github.com/klauspost/compress v1.15.1
go: downloading github.com/opencontainers/runc v1.1.1
go: downloading github.com/moby/sys/mount v0.3.1
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/moby/sys/mountinfo v0.6.0
../go/pkg/mod/github.com/klauspost/pgzip@v1.2.5/gunzip.go:26:2: github.com/klauspost/compress@v1.15.1: Get "https://storage.googleapis.com/proxy-golang-org-prod/b6d1094046d27988-github.com:klauspost:compress-v1.15.1.zip?Expires=1654908337&GoogleAccessId=gcs-urlsigner-prod%40golang-modproxy.iam.gserviceaccount.com&Signature=LxTsPDy8OHM5cQ%2FChFTCWSa4%2BVZ5r0KxLmCaXptMQxPI6oNxoF0zhelE%2BI5L4ZTx1v1tlmj48mkpZnow69c5UrGZM6egO44fAKxn0rC3B4ygfJ62e5BnAiZmJuT4vkMB44F8ht14bXYlHBN9Tz%2BbaZxZm2Art%2FR9xTXYMZWGUhCNTjYTLUrIs4HMMWQlq6riW486EI822c3VmXJd1LlcpZi%2FKlT9J6kymjN%2BZenwlgxWBZ594Jt9IdJH%2BlBXzVq6t8OGLRy%2FmcILBp9h3rIQ3u%2F4br8Z6ZXCMZYnyl6wbtMc17bMSTYuzVgWRAlFnBE%2F61eiFAhZFi21ES4DGI6Dcw%3D%3D": dial tcp: i/o timeout
make: *** [Makefile:9: default] Error 1
`

Please let me know what I can provide to improve this request for help!  I apologize for the poor posting.  I have not created an issue before.

**Comment by mengzhuo** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

--------------
p.s. Please check whether you can connect to https://proxy.golang.org.

**Comment by Zhme-Kakarot** [comment]
Thank you, I will head over there!
