### ISSUE TITLE
cmd/compile: missing combine constant store cases on amd64

### ISSUE THREAD

**Issue by wdvxdr1123** [golang/go#53324]
### What version of Go are you using (`go version`)?
gotip

### What did you do?

```go
func a(b []byte, idx int) {
	binary.LittleEndian.PutUint64(b[idx:], 123)
}
```

### What did you expect to see?

```asm
MOVQ $123, (AX)(DX*1)
```

### What did you see instead?

```asm
MOVB $123, (AX)(DI*1)
MOVB $0, 1(AX)(DI*1)
MOVB $0, 2(AX)(DI*1)
MOVB $0, 3(AX)(DI*1)
MOVB $0, 4(AX)(DI*1)
MOVB $0, 5(AX)(DI*1)
MOVB $0, 6(AX)(DI*1)
MOVB $0, 7(AX)(DI*1)
```

**Comment by klauspost** [comment]
I am also seeing this for non-constants, eg `binary.LittleEndian.PutUint64(a, binary.LittleEndian.Uint64(b))` will for [non-trivial](https://go.dev/play/p/1mjcj4Qt_83) cases [outputs](https://godbolt.org/z/acP7a3Pvh):

```
        MOVQ    (AX)(DX*1), DX
[...]
        MOVB    DL, (AX)(DI*1)
        MOVQ    DX, SI
        SHRQ    $8, DX
        MOVL    DX, 1(AX)(DI*1)
        MOVQ    SI, DX
        SHRQ    $40, SI
        MOVW    SI, 5(AX)(DI*1)
        SHRQ    $56, DX
        MOVB    DL, 7(AX)(DI*1)
```

Load is fine, but the store is split into an 8 byte write, a 32 bit write, a 16 bit write and finally an 8 bit write. Seems rather random.

**Comment by randall77** [comment]
@klauspost Yes, that doesn't look good. Should be fixable somehow.

**Comment by randall77** [comment]
I'm going to open a second issue for Klaus's example, as there's already a CL to fix the OP's case.
