### ISSUE TITLE
x/website: URL typo in "Go Doc Comments" 

### ISSUE THREAD

**Issue by tebeka** [golang/go#53338]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.18.3
</pre>

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/miki/.cache/go-build"
GOENV="/home/miki/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/miki/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/miki/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/miki/sdk/go1.18.3"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/miki/sdk/go1.18.3/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4155690658=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Look at https://go.dev/doc/comment "Links" section

### What did you expect to see?

`// [JSON and Go]: https://golang.org/doc/articles/json_and_go.html`

### What did you see instead?

`// [JSON and Go]: https://golang.org/doc/articles/json_and_go.htmlpackage json`

(The `package json` suffix is a typo IMO)

**Comment by ianlancetaylor** [comment]
Fixed.
