### ISSUE TITLE
cmd/go: 'go fmt' shouldn't reformat comments of unexported identifiers

### ISSUE THREAD

**Issue by aarzilli** [golang/go#53339]
Starting in go1.19 go fmt reformats certain comments to conform to the new go/doc syntax (#51082).

The reformatting is always fine for doc comments that conformed to the previous go/doc syntax since it does not alter the way they are rendered.

Doc comments of unexported identifiers are never (?) rendered by either godoc or pkgsite, therefore they should not be reformatted since they might not conform to go/doc syntax.

For example:

```
// blah blah blah
// - blah blah blah
//   blah blah
// blah blah blah
```

reformats to:

```
// blah blah blah
// - blah` blah blah
//
// 	blah blah
//
// blah blah blah
```

**Comment by robpike** [comment]
If you run

```
go doc -u
```

('u' for unexported) the comments are shown. The behavior is working as intended.

**Comment by aarzilli** [comment]
Fair enough, in that case I will close this issue. Still, it seems risky.
