### ISSUE TITLE
x/website: the GC guide URL of Go 1.19 Release Notes is invalid.

### ISSUE THREAD

**Issue by uji** [golang/go#53337]
### What did you do?

I accessed https://tip.golang.org/doc/go1.19 and opened the GC guide URL.

<img width="1302" alt="スクリーンショット 2022-06-12 15 21 11" src="https://user-images.githubusercontent.com/49834542/173219950-13013303-d4ce-46aa-ae50-26ab96a8aae3.png">

### What did you expect to see?

It should be accessible.

### What did you see instead?
There was no page. 

<img width="794" alt="image" src="https://user-images.githubusercontent.com/49834542/173220048-2515101d-f2e5-4836-abaa-c9b247b30fc0.png">

**Comment by changkun** [comment]
cc @prattmic @mknyszek

**Comment by narqo** [comment]
There is also the same "broken" link in the `runtime/debug.SetMemoryLimit` docs https://pkg.go.dev/runtime/debug@master#SetMemoryLimit

**Comment by prattmic** [comment]
This is expected. We intend to have this doc ready by the 1.19 release so we went ahead and added a link to the draft release notes. I don't think we have a tracking issue for it though, so this will work nicely. :)

**Comment by mknyszek** [comment]
Yeah, sorry about this everyone. I've been dealing with other issues but I'm finally getting around to this.

I think I want to put up a work-in-progress page there temporarily just so at the very least the link isn't broken and it's more clear what the current status is. Any objections?

**Comment by mknyszek** [comment]
@prattmic I created a new issue to track work on this actually, just because the original post on this issue refers specifically to the broken link. See #53360.
