### ISSUE TITLE
cmd/compile: incomplete relocation support on ppc64le

### ISSUE THREAD

**Issue by nehaljwani** [golang/go#53345]
Since https://github.com/golang/go/commit/2c4f389c I am unable to compile go with `CGO_ENABLED=1` on `ppc64le` with `GCC 10.3.0` and `binutils 2.36.1`

I see errors like:
```
/path/to/go/pkg/linux_ppc64le/a/b/c/d.a(_x???.o): unknown relocation type <>; compiled without -fpic?
```

Where `<>` are numbers: `31, 60, 119, 120`. I am not sure if I am reading this correctly, but these correspond to:
`R_PPC_PLT16_HA`, `R_PPC64_PLT16_LO_DS`, `R_POWERPC_PLTSEQ`, `R_POWERPC_PLTCALL` and references to these are missing in:
```
src/cmd/link/internal/loadelf/ldelf.go
src/cmd/link/internal/ppc64/asm.go
src/debug/elf/elf.go
```

**Comment by mengzhuo** [comment]
@golang/ppc64 @laboger

**Comment by pmur** [comment]
Hi @nehaljwani, thank you for reporting. Would you be able to share the gcc flags used to compile the C code?  A simplified test case would help me. I suspect it just needs to make libc call with the compiler options used on the project.

I am still digging through the linked CI logs trying to understand how the linked utility is being compiled.

A trivial workaround is to explicitly request external linking on ppc64le. This was the behavior prior 1.18 with any cgo usage. I will try to implement these relocs. They are fairly new (introduced with ELFv2 1.5), but I suspect we need to handle with newer GCC.

**Comment by pmur** [comment]
@nehaljwani is one of the CFLAG options `-fno-plt`, or similar option to optimize library calls in C/C++? I can reproduce a similar error using this option.

**Comment by nehaljwani** [comment]
Hello @pmur, we use:
```
CGO_CFLAGS=-ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe
```
