### ISSUE TITLE
Json decode to http reqdata:   decoder := json.NewDecoder and decoder.Decode(&recvData) getting error is invalid character '\t' in string literal.

### ISSUE THREAD

**Issue by sachusachin622** [golang/go#53363]
### What version of Go are you using (`go version`)?

<pre>
$ go version : go1.13

</pre>

### What did you do?
Hi ,
I am trying to decoding the json data which is received from http request, while decoding am getting erros is invalid character '\t' in string literal error.

here is my code:
func RecvdMsgFromAp(response http.ResponseWriter, req *http.Request) {
    //// RECEIVED FROM AP ////
    fmt.println("IDM@Go :: req.Body is %v", req.Body)
    decoder := json.NewDecoder(req.Body)
    var recvData Request_struct
    err := decoder.Decode(&recvData)
    if err != nil {
        fmt.println("error is %v", err)
    }
}

### What did you expect to see?
Json decoder should decode properly.

### What did you see instead?
while decoding getting error is invalid character '\t' in string literal error.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
