### ISSUE TITLE
net/http/cgi: the SERVER_NAME variable in the CGI environment should not contain the port

### ISSUE THREAD

**Issue by zapateo** [golang/go#53368]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/zapateo/.cache/go-build"
GOENV="/home/zapateo/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/zapateo/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/zapateo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/zapateo/Programmi/go1.18.3.linux-amd64/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/zapateo/Programmi/go1.18.3.linux-amd64/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4099781282=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Executing a CGI in a subprocess using the `net/http/cgi.Handler`, passing a `*http.Request` that contains a port in its `Host`.

### What did you expect to see?

The `SERVER_NAME` variable in the CGI environment should not contain the port, according to the [section 4.1.14](https://datatracker.ietf.org/doc/html/rfc3875#section-4.1.14) of the RFC 3875.

Such spec should be implemented by the `net/http/cgi` package, as stated in:

https://github.com/golang/go/blob/c29be2d41c6c3ed78a76b4d8d8c1c22d7e0ad5b7/src/net/http/cgi/host.go#L8-L9

### What did you see instead?

The `SERVER_NAME` env variable, initialized here:

https://github.com/golang/go/blob/c29be2d41c6c3ed78a76b4d8d8c1c22d7e0ad5b7/src/net/http/cgi/host.go#L141

is initialized with `req.Host`, which may contain the port.

**Comment by seankhliao** [comment]
a similar issue for REMOTE_HOST/PORT was #9861

cc @neild @bradfitz
