### ISSUE TITLE
net/http: TestTransportReuseConnection_Gzip_.* failures with "didn't reuse connection"

### ISSUE THREAD

**Issue by bcmills** [golang/go#53373]
```
#!watchflakes
post <- pkg == "net/http" && test ~ `TestTransportReuseConnection_Gzip_.*` && `didn.t reuse connection` && date < "2023-08-30"
```

----

```
2022/06/08 19:53:00 http: TLS handshake error from 127.0.0.1:21458: EOF
--- FAIL: TestTransportReuseConnection_Gzip_ContentLength (0.10s)
    transport_test.go:4447: didn't reuse connection
FAIL
FAIL	net/http	11.607s
```

`greplogs -l -e 'FAIL: TestTransportReuseConnection.*(?:\n .*)* didn'\''t reuse connection' --since=2022-01-01`
[2022-06-08T19:41:54-bdde41e/freebsd-amd64-race](https://build.golang.org/log/c5f8eaf80181ce31fb61ba0591bd87294c562fc9)

See previously #22212.

Perhaps a good first step would be to modify the test to use `net/http/httptrace` to dump more information about what's going on with the connections?

(CC @neild @golang/freebsd)

**Comment by ayang64** [comment]
if noone else does, i'll take a look this afternoon.  assigning to myself as a reminder.

**Comment by bcmills** [comment]
This does not appear to be freebsd-specific:
`greplogs -l -e 'FAIL: TestTransportReuseConnection_.*\n\s.*didn.t reuse connection' --since=2022-01-01`
[2022-08-16T16:27:35-a45bbea/darwin-amd64-nocgo](https://build.golang.org/log/d5aa93922ef0ec047abf89ab9726e9c8bee18386)
[2022-08-12T16:38:52-f001df5/windows-arm64-11](https://build.golang.org/log/bc8966b825fa3b7efda951e3264231efacaa0fa7)
[2022-06-08T19:41:54-bdde41e/freebsd-amd64-race](https://build.golang.org/log/c5f8eaf80181ce31fb61ba0591bd87294c562fc9)

Note that `darwin/amd64` is a first-class builder (attn @neild).

**Comment by neild** [comment]
Added a watchflakes stanza to the issue description.

**Comment by neild** [comment]
(Still waiting for a flake with the additional tracing; the one at a45bbeae predates the tracing.)

**Comment by bcmills** [comment]
I suspect this was fixed by https://go.dev/cl/483116. Closing as “probably fixed”, and `watchflakes` can file a new issue for it if I'm wrong.
