### ISSUE TITLE
cmd/link: cgo fails to link on macos 13 beta (arm64)

### ISSUE THREAD

**Issue by ptxmac** [golang/go#53372]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

tl;dr: 13.0 Beta (22A5266r) on Apple silicon (arm64)

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/ptx/Library/Caches/go-build"
GOENV="/Users/ptx/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/ptx/go/pkg/mod"
GONOPROXY=<censored>
GONOSUMDB=<censored>
GOOS="darwin"
GOPATH="/Users/ptx/go"
GOPRIVATE=<censored>
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xf/5whnbpls5d31z5dyrpdf_zh80000gn/T/go-build3396597166=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.18.3 darwin/arm64
GOROOT/bin/go tool compile -V: compile version go1.18.3
uname -v: Darwin Kernel Version 22.0.0: Tue May 24 20:30:32 PDT 2022; root:xnu-8792.0.50.111.3~5/RELEASE_ARM64_T8103
ProductName:	macOS
ProductVersion:	13.0
BuildVersion:	22A5266r
lldb --version: lldb-1400.0.17.202
Apple Swift version 5.7 (swiftlang-5.7.0.113.202 clang-1400.0.16.2)
</pre></details>

### What did you do?

Attempt to compile the following program:
```go
package main

// #include <stdio.h>
import "C"

func main() {
	C.putchar('a')
}
```

### What did you expect to see?

This should Just-Work™ and create a valid arm64 binary

### What did you see instead?

A long list of linker warnings followed by an error:

<pre>
$ go build -v main.go
# command-line-arguments
/usr/local/go/pkg/tool/darwin_arm64/link: running clang failed: exit status 1
ld: warning: pointer not aligned at address 0x100090467 ('_type.*' + 1127 from /var/folders/xf/5whnbpls5d31z5dyrpdf_zh80000gn/T/go-link-1884331981/go.o)
  ...snip around 2000 lines of minor variations of this warning
ld: warning: pointer not aligned at address 0x10009CA17 ('_type.*' + 51735 from /var/folders/xf/5whnbpls5d31z5dyrpdf_zh80000gn/T/go-link-1884331981/go.o)
ld: unaligned pointer(s) for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
</pre>

**Comment by ptxmac** [comment]
> I'm able to reproduce the issue by using Xcode 14 beta on macOS 12.5 beta

Oh that's good news - then I should be able to use another version of xcode.

**Comment by cherrymui** [comment]
@ptxmac could you try if Go tip (which now includes the CL) works on the new OS with the new Xcode? Thanks!

**Comment by ptxmac** [comment]
Just tested with 
```
$ gotip version
go version devel go1.19-ecc268a Thu Jun 16 01:03:59 2022 +0000 darwin/arm64
```

Just perfect! - Thanks!

**Comment by nikitagriaznov** [comment]
It looks like beta 3 update solved this issue
