### ISSUE TITLE
os/exec: using lsof costs 100% CPU and blocked

### ISSUE THREAD

**Issue by shentupenghui** [golang/go#53385]
### What version of Go are you using (`go version`)?
go version go1.17.5 linux/amd64

### Does this issue reproduce with the latest release?
Yes, i've upgrade go to latest version and rebuild project, still happens

### What operating system and processor architecture are you using (`go env`)?
<img width="500" alt="image" src="https://user-images.githubusercontent.com/25290236/173715488-86021998-0939-4d23-b5e4-c75c2e1ce89b.png">

### What did you do?
how i use exec in my code:
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/25290236/173715678-3cb0f104-c509-44d8-a6b6-09d24f3eb547.png">

### What did you expect to see?
I expect it runs both normally and quickly just as before like used in  terminal

### What did you see instead?
this command is blocked for about 5min, cost 100% CPU, and return nothing
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/25290236/173715947-ed55d32a-eb91-442f-94a0-f1adc4aa7d46.png">

**Comment by mengzhuo** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

---------------

p.s. You're executing `sh -c lsof -i:%d` without quotes around lsof.
