### ISSUE TITLE
encoding/xml: not marshalling nil pointer in struct without ",omitempty" 

### ISSUE THREAD

**Issue by martinrode** [golang/go#53408]
The xml marshaler skips nil pointers in struct values even if "omitempty" is not set. This is not what I would expect from encoding. I expect that behaviour if I set ",omitempty" on the struct field, but not without.

The problem is in the stdlib where this code returns nil and is not encoding a value if it is a nil pointer. This is different from how encoding/json behaves where "nil" is encoded into "null" if not ",omitempty" is set.

```go
  marshal.go:

	// Drill into interfaces and pointers.
	// This can turn into an infinite loop given a cyclic chain,
	// but it matches the Go 1 behavior.
	for val.Kind() == reflect.Interface || val.Kind() == reflect.Pointer {
		if val.IsNil() {
// Why are we returning HERE??
   		    return nil
		}
		val = val.Elem()
	}
```

Documentation https://pkg.go.dev/encoding/xml says this:

```
- a field with a tag including the "omitempty" option is omitted
  if the field value is empty. The empty values are false, 0, any
  nil pointer or interface value, and any array, slice, map, or
  string of length zero.
```
From this I understand that "any nil pointer or interface value" WITHOUT the ",omitempty" is NOT omitted during marshalling...

**Comment by seankhliao** [comment]
please include example code that demonstrates the issue

**Comment by mvdan** [comment]
Pleaes read the docs - they do state this quite clearly:

> Marshal handles an array or slice by marshaling each of the elements. Marshal handles a pointer by marshaling the value it points at or, if the pointer is nil, by writing nothing. Marshal handles an interface value by marshaling the value it contains or, if the interface value is nil, by writing nothing. Marshal handles all other data by writing one or more XML elements containing the data.

**Comment by martinrode** [comment]
**Well, to me this is not clear, it's surprising and unnecessary.** If you read the docs further, it talks about how it handles structs below the first paragraph which explains the start of the marshalling (imho).

**For struct with pointers or interfaces, the ",omitempty" option is useless otherwise.** And it is different than MarshalJSON. And there is no way working around this issue. So please re-open the ticket and let's discuss this further.

An example can be found here: https://goplay.space/#1ipwnPTcOwh

**Since the current behaviour can be restored by using ",omitempty" on affected struct fields, I think this is a patch to consider.**

* It would bring the behaviour in line with the JSON lib
* There is no workaround for this problem at the moment unless you implement your own MarshalXML
* Current users who rely on this behaviour can use ",omitempty" in their structs

And I think it is ok that the documentation says, it ignores NIL interface and NIL pointer when it STARTS MARSHALLING (thus the text at the beginning), but further down when you talk about how structs and struct tags are handled we read this:

```
The XML element for a struct contains marshaled elements for each of the exported fields of the struct, with these exceptions:

- a field with a tag including the "omitempty" option is omitted
  if the field value is empty. The empty values are false, 0, any
  nil pointer or interface value, and any array, slice, map, or
  string of length zero.
```

**Comment by mvdan** [comment]
If you think the docs are confusing, there's always the option of sending a patch to make them easier to understand. In my brief skim of the docs, I didn't see a clear way to do that.

As for changing the behavior - unfortunately we cannot change documented behavior due to https://go.dev/doc/go1compat. Supporting the behavior that you want would require either custom code (like you describe) or new API like an option, for which a detailed proposal should be filed instead: https://github.com/golang/proposal

**Comment by martinrode** [comment]
**To me the docs are pretty clear and I see the current implementation at fault.** I am not happy with the way it works at the moment. And it happened in the past that Stdlib feature were refined / matched with the docs. And since the old behaviour can easily be achieved by using ",omitempty", **I don't see such a change breaking the promise (which is more about the language itself and not some struct field info interpretation!).**

So please re-consider a fix for this in an upcoming version of Go. I am happy to send in a patch which fixes this issue.

As for the doc change, you can simply NOT TALK about "nil pointer" or "interface values" in the ",omitempty" explanation (which is a copy from the MarshalJSON behaviour), as it has no effect whatsoever anyways... 

```
- a field with a tag including the "omitempty" option is omitted
  if the field value is empty. The empty values are false, 0, any array, slice, map, or
  string of length zero. "omitempty" has no effect on nil pointer or interface values as
  those are omitted by default.
```

**Comment by seankhliao** [comment]
That can't be correct, change the field to a `string` and now you can't differentiate between empty and nil

**Comment by martinrode** [comment]
I respect your unfortunate decision. Users could have restored the current behaviour using ",omitempty".

Anyways, I do not want to give up easily, so I will suggest a new tag for struct field ",notomitempty" or so, to get the behaviour I need.

Please consider updating the docs at least, see above for a suggestion. "omitempty" talks about "nil pointer and interface" which is clearly not happening and as such a bug in the docs.
