### ISSUE TITLE
Error loading workspace: cannot run go project with other folders/module (needs to be opened by itself - macbook m1)

### ISSUE THREAD

**Issue by tuffwes** [golang/go#53418]
Error loading workspace: You are outside of a module and outside of $GOPATH/src. If you are using modules, please open your editor to a directory in your module.

This is just ridiculous. why do I have to do that? Frustrating... Please fix.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
