### ISSUE TITLE
cmd/compile: ambiguous selector with generic interface & embedded types

### ISSUE THREAD

**Issue by phemmer** [golang/go#53419]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="linux"
</pre></details>

### What did you do?

```go
package main

import "fmt"

type MyString string
type MyByteSlice []byte
type Both struct {
	MyString
	MyByteSlice
}

func (s1 MyString) Concat(s2 MyString) MyString            { return s1 + s2 }
func (bs1 MyByteSlice) Concat(bs2 MyByteSlice) MyByteSlice { return append(bs1, bs2...) }
func (b1 Both) Concat(b2 Both) Both {
	return Both{
		b1.MyString.Concat(b2.MyString),
		b1.MyByteSlice.Concat(b2.MyByteSlice),
	}
}

type Concatable[T any] interface {
	Concat(T) T
}

func Repeat[T Concatable[T]](c T) T {
	return c.Concat(c)
}

func main() {
	s := MyString("foo")
	bs := MyByteSlice("foo")
	b := Both{MyString("foo"), MyByteSlice("foo")}
	fmt.Println(Repeat(s))
	fmt.Println(Repeat(bs))
	fmt.Println(Repeat(b))
}
```
https://go.dev/play/p/Jyws-pz9k5X

### What did you expect to see?
successful compilation

### What did you see instead?
```
./prog.go:26:10: ambiguous selector c.Concat

Go build failed.
```

The error is with the `Both` type (as if I remove it, the issue goes away). However on `Both`, `Concat` is not ambiguous. `Both` has it's own `Concat` method, and should not be trying to fall through to either of the embedded types.

**Comment by thanm** [comment]
@griesemer

**Comment by griesemer** [comment]
Simplified [reproducer](https://go.dev/play/p/ZGup1qvBp5H):
```Go
package main

type T1 struct{}
type T2 struct{}
type Both struct {
	T1
	T2
}

func (T1) m()   {}
func (T2) m()   {}
func (Both) m() {}

func f[T interface{ m() }](c T) {
	c.m()
}

func main() {
	var b Both
	// b.m()         // <<< this (without the f(b) below) is ok
	f(b)
}
```
The type checker (types2) doesn't have a problem with this, the error appears to arrive later, in the noder or after instantiation in the compiler (have not yet investigated).

@mdempsky Can you confirm that this problem is present/absent with unified IR?

**Comment by mdempsky** [comment]
> @mdempsky Can you confirm that this problem is present/absent with unified IR?

Yeah, the test program appears to run correctly with `GOEXPERIMENT=unified go run`.

**Comment by griesemer** [comment]
Thanks, @mdempsky .
Unless we hear otherwise from users, we can probably just wait for the unified IR to fix this in 1.20.
Assigning to you and I for now so it's on the radar.

**Comment by cuonglm** [comment]
@mdempsky @griesemer I sent CL [414836](https://go.dev/cl/414836) to fix this issue, is it worth to make it fixed for go1.19 or just wait for unified IR in go1.20 like you said above?

**Comment by griesemer** [comment]
@cuonglm The fix seems simple enough, but we're also close to RC1. I will ping the compiler/runtime team to chime in.
