### ISSUE TITLE
proxy.golang.org: gin-gonic/gin v1.8.0 CC

### ISSUE THREAD

**Issue by jtagcat** [golang/go#53426]
cc towards https://github.com/gin-gonic/gin/issues/3195

**Comment by seankhliao** [comment]
Looks like working as intended for the proxy.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
