### ISSUE TITLE
expvar: panic: interface conversion: interface is nil, not expvar.Var

### ISSUE THREAD

**Issue by catenacyber** [golang/go#53422]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/catena/Library/Caches/go-build"
GOENV="/Users/catena/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/catena/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/catena/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/catena/go/src/github.com/catenacyber/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pp/dc1dtf9x2js3v0jx_m010nqr0000gn/T/go-build4237848497=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.17.6 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.17.6
uname -v: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
lldb --version: lldb-1316.0.9.41
Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
gdb --version: GNU gdb (GDB) 9.1
</pre></details>

### What did you do?

Run https://go.dev/play/p/L708GRIfgkv?v=gotip

### What did you expect to see?

The program finishing and printing hello

### What did you see instead?

```
panic: interface conversion: interface is nil, not expvar.Var

goroutine 1 [running]:
expvar.(*Map).Do(0xc000062240, 0xc000111ef8)
	/usr/local/go-faketime/src/expvar/expvar.go:227 +0x13c
expvar.(*Map).String(0xc000062240?)
	/usr/local/go-faketime/src/expvar/expvar.go:117 +0x9c
main.main()
	/tmp/sandbox2633615687/prog.go:14 +0x75

Program exited.
```

Found by https://github.com/catenacyber/ngolo-fuzzing on oss-fuzz 
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48049

Seems like fix for #52719 was not complete

**Comment by catenacyber** [comment]
Or maybe gotip on playground does not have latest patch...

**Comment by 0xkaruru** [comment]
No,I see.

**Comment by seankhliao** [comment]
The playground has a slight lag for tip, you can get the version via `fmt.Println(debug.ReadBuildInfo())`, currently `go	devel go1.19-ecc268aa26 Thu Jun 16 01:03:59 2022 +0000`, 5 commits behind the expvar fix.
Or go to https://gotipplay.golang.org/ which is the backend.

Doesn't repro locally on tip / `go version devel go1.19-9068c6844d Thu Jun 16 21:58:40 2022 +0000 linux/amd64`

**Comment by seankhliao** [comment]
Duplicate of #52719

**Comment by catenacyber** [comment]
Thanks, I had wrongly read the fix was merged longer ago :-)
