### ISSUE TITLE
x/build/env/linux-arm64/packet: remove host-linux-arm64-packet

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#53436]
The machine hosting the linux-arm64-packet builders is being decommissioned on June 27, 2022. We need to remove `host-linux-arm64-packet` and `linux-arm64-packet` before the machine is decommissioned. 

We appreciate @pgmwoa and their team for providing this builder to the community for all of these years.

@golang/release

**Comment by aaqaishtyaq** [comment]
Hey @cagedmantis, I would like to take up this task. From the first look, the `linux-arm64-packet ` machine is getting decommissioned soon and the task is to remove the builder machine setup. 
I tried to remove it in the CL above. Please take a look.
