### ISSUE TITLE
os: os.Stat says broken symlinks do not exist as checked by os.IsNotExist()

### ISSUE THREAD

**Issue by quackduck** [golang/go#53437]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/ishan/Library/Caches/go-build"
GOENV="/Users/ishan/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/ishan/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/ishan/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/opt/go/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_d/8s653yvs3rjcnwqy_dc45wh40000gn/T/go-build2011038208=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### To reproduce:

1. Make a file and a symlink pointing to that file
2. Delete the file
3. Check if the symlink exists according to `os`

I made a program that does this: https://go.dev/play/p/pCoJBeM6-rC

<details><summary>Code</summary>

```go
package main

import (
	"fmt"
	"os"
)

func main() {
	_, err := os.Create("file")
	check(err)
	err = os.Symlink("file", "symlink")
	check(err)
	err = os.Remove("file")
	check(err)

	_, err = os.Stat("symlink")
	if os.IsNotExist(err) {
		fmt.Println(err) // shouldn't run, because we never deleted the symlink
	}
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
```

</details>

### What did you expect to see?

That `os` says the symlink exists (even if the file it points to doesn't).

### What did you see instead?

An error that the symlink does not exist.

**Comment by ZekeLu** [comment]
I think you want to use https://pkg.go.dev/os#Lstat in this case.

**Comment by quackduck** [comment]
That fixes it, but I don't see why os.Stat should say the symlink does not exist when it does exist.

**Comment by ianlancetaylor** [comment]
That's how `os.Stat` works: it reports information about the target of the symlink.  If the target does not exist, that is what it reports.  If you want information about the symlink itself, you have to use `os.Lstat`, as @ZekeLu suggests.

This is consistent with the C functions `stat` and `lstat.

Closing because there is anything to do here.

**Comment by quackduck** [comment]
Ah, thanks
