### ISSUE TITLE
go test: The package test prompts irrelevant error information (no exception through code analysis) and the compilation of binary packages is normal

### ISSUE THREAD

**Issue by conero** [golang/go#53457]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Use Latest stable release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ksj\AppData\Local\go-build
set GOENV=C:\Users\ksj\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\programdata\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\programdata\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\conero\~\devtool\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ksj\AppData\Local\Temp\go-build2436805339=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

1. excuse `go test`  Prompt irrelevant exception error information, and the actual code has no exception (follow the syntax rules).
2. excuse `go build ` use the same library to perform normal.

test function like :
```go
func TestStdRepoUrl(t *testing.T) {
	tUrl := "https://host/svn/~/bigdata20220412"
	rfUrl := "https://host/svn/~/bigdata20220412"
	rfTy := ""

	if ru, rt := StdRepoUrl(tUrl); ru != rfUrl || rt != rfTy {
		t.Errorf("Address (%v) translation error, unexpected structure.", tUrl)
	}
}
```

source function code:
```go
// function
func StdRepoUrl(vUrl string) (rpUrl, vType string) {
	u, er := url.Parse(vUrl)
	if er == nil {
		if strings.Index(vUrl, ".git") > -1 {
			vType = RepoGit
		} else if u.Scheme == "svn" || u.Scheme == "svn+ssh" {
			vType = RepoSvn
		}
	} else {
		vUrl = fs.StdPathName(vUrl)
		if strings.Index(vUrl, ".git") > -1 {
			vType = RepoGit
		} else {			
			if vUrl[len(vUrl)-1:] != "/" {
				vUrl += "/"
			}
		}
	}
	rpUrl = vUrl
	return
}

// Warnf: gitee.com/conero/uymas/logger.Logger).Warnf
func (l *Logger) Warnf(message string, args ...interface{}) {
	l.formatLevel(LogWarn, message, args...)
}
```

run test and get fail msg:
```shell
go test -v ./repo -run TestStdRepoUrl
go test ./repo
```

> github link: https://github.com/conero/vd-err53457

### What did you expect to see?

Error free is like normal compilation and compliance with syntax rules. Prompt no error, no error actually.

### What did you see instead?

```shell
# conero.cn/devtool/repo
repo\patch.go:50:6: (*gitee.com/conero/uymas/logger.Logger).Warnf call needs 1 arg but has 2 args
FAIL    conero.cn/devtool/repo [build failed]
FAIL
```

**Comment by ianlancetaylor** [comment]
The output you are seeing occurs because by default `go test` runs `go vet`, as documented at https://pkg.go.dev/cmd/go#hdr-Test_packages.  To turn off the vet checks, use `go test -vet=off`.

Here the signature of the function being called is

```Go
func (l *Logger) Warnf(message string, args ...interface{})
```

but the call looks like

```Go
					lger.Warnf("%v Source file write compressed file error", dp.Filename, er)
```

The vet check is correctly telling you that `Warnf` was invoked with a string with a single `%v` but that two arguments are being passed.  Either one argument should be omitted or there should be another `%v` or whatever in the format string.

Closing because this is working as documented and intended.
