### ISSUE TITLE
cmd/compile: internal compiler error: width not calculated: int128

### ISSUE THREAD

**Issue by ShadiestGoat** [golang/go#53454]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, this is the latest release

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/shady/.cache/go-build"
GOENV="/home/shady/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/shady/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/shady/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/shady/projects/bug-go/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1859839587=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I tried to compile [this repo](https://github.com/ShadiestGoat/Go-Bug)

### What did you expect to see?

I expected it to compile normally.

### What did you see instead?

A compiler bug:

<pre>
# github.com/ShadiestGoat/Go-Bug/profile
profile/matchingNew.go:48:2: internal compiler error: width not calculated: int128

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
</pre>

**Comment by mengzhuo** [comment]
Confirmed that 1.18.3 and master affected by this issue.

cc @griesemer @ianlancetaylor

**Comment by ianlancetaylor** [comment]
CC @randall77 @mdempsky

**Comment by mengzhuo** [comment]
Bisect shows 9dd71ba91397c7f69571ae7f0810d64f2f38547a is the first bad commit

**Comment by randall77** [comment]
@gopherbot please open a backport to 1.17 and 1.18.

This bug causes an ICE in rare circumstances.

**Comment by ShadiestGoat** [comment]
Hello, I'm sorry, but I don't get what this means. 

Is this a "won't fix" issue, or does this mean that it has been resolved?
