### ISSUE TITLE
x/exp/shiny/driver/x11driver: error has missing info

### ISSUE THREAD

**Issue by JorgeCepeda** [golang/go#53467]
### What version of Go are you using (`go version`)?
<pre>
None
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
The error happened on:
aarzilli/gdlv#16
and
noisetorch/NoiseTorch#207
without any conclusion of how it did (https://github.com/golang/exp/blob/master/shiny/driver/x11driver/screen.go#L642)

### What did you expect to see?
Some info about the arguments for better debugging

### What did you see instead?
An error about what failed without its data

**Comment by ianlancetaylor** [comment]
Please tell us exactly what you did and exactly what happened.  If possible, please tell us how to reproduce the problem.  Thanks.

**Comment by JorgeCepeda** [comment]
In this case I'm just reporting that others had it and request some more info on the error, sorry, I don't even use Go

**Comment by ianlancetaylor** [comment]
Neither of the issues you mention have any helpful information.

I don't see any action that we can take here.

**Comment by JorgeCepeda** [comment]
My proposal was printing "Something failed: x was not found" instead of no extra information

**Comment by ianlancetaylor** [comment]
CC @nigeltao

**Comment by aarzilli** [comment]
As far as I can tell that error can't tell you anything more useful, that function is only called once and always with a depth of 32. So, if you see that error, it means it can't find a visual id with depth 32 and the expected color masks.
The only way to find out why would be to look at the output of xdpyinfo. Making the error include a list of all visual ids is unreasonable, there tends to be a lot of them (I have 600).
