### ISSUE TITLE
new keyword 'clone' for slices/arrays/maps

### ISSUE THREAD

**Issue by halturin** [golang/go#53468]
I couldn't find anything similar to my idea in the issues (am I missing it?)
It would be nice to have `clone` feature instead of manually for/range copying. 
```
slice := []int{1,2,3}
newslice := clone(slice)
```

**Comment by seankhliao** [comment]
https://pkg.go.dev/golang.org/x/exp/slices#Clone
https://pkg.go.dev/golang.org/x/exp/maps#Clone
