### ISSUE TITLE
go1.18.3.linux-amd64 -- fatal error-- signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x46ef9f

### ISSUE THREAD

**Issue by tobelangbowan** [golang/go#53462]
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x46ef9f]

goroutine 1 [running]:
runtime.throw({0xe650f3?, 0x0?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc00038f788 sp=0xc00038f758 pc=0x442171
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:825 +0x305 fp=0xc00038f7d8 sp=0xc00038f788 pc=0x457705
aeshashbody()
        /usr/local/go/src/runtime/asm_amd64.s:1343 +0x39f fp=0xc00038f7e0 sp=0xc00038f7d8 pc=0x46ef9f
runtime.mapiternext(0xc000284900)
        /usr/local/go/src/runtime/map.go:934 +0x2cb fp=0xc00038f850 sp=0xc00038f7e0 pc=0x41be8b
runtime.mapiterinit(0x4196a5?, 0x0?, 0xd0?)
        /usr/local/go/src/runtime/map.go:861 +0x228 fp=0xc00038f870 sp=0xc00038f850 pc=0x41bb68
reflect.mapiterinit(0xc00038f960?, 0x7ff728042428?, 0xd0?)
        /usr/local/go/src/runtime/map.go:1373 +0x19 fp=0xc00038f898 sp=0xc00038f870 pc=0x46b9f9

goroutine 15 [select]:
database/sql.(*DB).connectionOpener(0xc00039d520, {0x10cd4a8, 0xc0003c26c0})
        /usr/local/go/src/database/sql/sql.go:1226 +0x8d
created by database/sql.OpenDB
        /usr/local/go/src/database/sql/sql.go:794 +0x18d

goroutine 13 [IO wait]:
internal/poll.runtime_pollWait(0x7ff7503a1fc8, 0x72)
        /usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000090a00?, 0xc0003d6000?, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc000090a00, {0xc0003d6000, 0x1000, 0x1000})
        /usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000090a00, {0xc0003d6000?, 0x412229?, 0x4?})
        /usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000010680, {0xc0003d6000?, 0x0?, 0x0?})
        /usr/local/go/src/net/net.go:183 +0x45
net/http.(*persistConn).Read(0xc0003986c0, {0xc0003d6000?, 0xc000094a20?, 0xc000069d30?})
        /usr/local/go/src/net/http/transport.go:1929 +0x4e
bufio.(*Reader).fill(0xc0000810e0)
        /usr/local/go/src/bufio/bufio.go:106 +0x103
bufio.(*Reader).Peek(0xc0000810e0, 0x1)
        /usr/local/go/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc0003986c0)
        /usr/local/go/src/net/http/transport.go:2093 +0x1ac
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1750 +0x173e

goroutine 14 [select]:
net/http.(*persistConn).writeLoop(0xc0003986c0)
        /usr/local/go/src/net/http/transport.go:2392 +0xf5
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1751 +0x1791

goroutine 34 [sleep]:
time.Sleep(0x1dcd6500)
        /usr/local/go/src/runtime/time.go:194 +0x12e
gopkg.in/mgo%2ev2.(*mongoCluster).syncServersLoop(0xc0002c6100)
        /home/wq/adapters/pkg/mod/gopkg.in/mgo.v2@v2.0.0-20180705113604-9856a29383ce/cluster.go:368 +0xf5
created by gopkg.in/mgo%2ev2.newCluster
        /home/wq/adapters/pkg/mod/gopkg.in/mgo.v2@v2.0.0-20180705113604-9856a29383ce/cluster.go:78 +0x1db

goroutine 50 [select]:
github.com/streadway/amqp.(*Connection).heartbeater(0xc00029e280, 0x2540be400, 0xc0000819e0)
        /home/wq/adapters/pkg/mod/github.com/streadway/amqp@v0.0.0-20190827072141-edfb9018d271/connection.go:551 +0x1b8
created by github.com/streadway/amqp.(*Connection).openTune
        /home/wq/adapters/pkg/mod/github.com/streadway/amqp@v0.0.0-20190827072141-edfb9018d271/connection.go:782 +0x531

**Comment by tobelangbowan** [comment]
I used ”go get -u golang.org/x/sys“, still getting an error

**Comment by seankhliao** [comment]
that's not enough information to be actionable, please fill out the issue template, and if possible provide the code or a reproducer for the issue

**Comment by tobelangbowan** [comment]
When I use go1.16 version, there is no problem, using go1.18 will have the above error.

**Comment by ianlancetaylor** [comment]
@tobelangbowan How can we recreate the problem?

Have you tried running the program after building with `-race`?

**Comment by tobelangbowan** [comment]
> @tobelangbowan How can we recreate the problem?
> 
> Have you tried running the program after building with `-race`?
I have switched back to the go1.16 version without any problems

**Comment by zishen** [comment]
May be the resion for reflect2 v1.0.1. In 1.18 it should be update to v1.0.2.
see: https://milhamh.dev/check-your-package-dependency-issue-for-go-118

**Comment by elianka** [comment]
@tobelangbowan have you resolved your problem?

**Comment by asifui22** [comment]
? Destination name None
? Editing the deployment configuration will overwrite existing configuration, are you sure you want to continue? Yes
Adding app to mta config: sapaqmmasterdatacharacteristics
Error @sap/fiori:deploy-config cf --base ui5.yaml --config ui5-deploy.yaml 

[2023-08-23 17:20:58]  INFO get parameters
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x45f79f]

goroutine 1 [running]:
runtime.throw({0x7f1c92?, 0x1?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc000141618 sp=0xc0001415e8 pc=0x433851
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:825 +0x2ec fp=0xc000141668 sp=0xc000141618 pc=0x448c2c
aeshashbody()
        /usr/local/go/src/runtime/asm_amd64.s:1343 +0x39f fp=0xc000141670 sp=0xc000141668 pc=0x45f79f
runtime.mapiternext(0xc000037780)
        /usr/local/go/src/runtime/map.go:934 +0x2cb fp=0xc0001416e0 sp=0xc000141670 pc=0x40fa4b
runtime.mapiterinit(0x0?, 0xc00021b0d0?, 0xc0001991e1?)
        /usr/local/go/src/runtime/map.go:861 +0x228 fp=0xc000141700 sp=0xc0001416e0 pc=0x40f728
reflect.mapiterinit(0x7aa2a0?, 0xc0001417b0?, 0xc0001417d0?)
        /usr/local/go/src/runtime/map.go:1373 +0x19 fp=0xc000141728 sp=0xc000141700 pc=0x45ce59
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
        /home/circleci/go/src/github.com/SAP/cloud-mta/vendor/github.com/modern-go/reflect2/unsafe_map.go:112
github.com/json-iterator/go.(*mapEncoder).Encode(0xc00019f710, 0xc000198c18, 0xc00007cd80)
        /home/circleci/go/src/github.com/SAP/cloud-mta/vendor/github.com/json-iterator/go/reflect_map.go:257 +0x21c fp=0xc0001417e0 sp=0xc000141728 pc=0x67cdbc
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc000120820?, 0x0?, 0x0?)
        /home/circleci/go/src/github.com/SAP/cloud-mta/vendor/github.com/json-iterator/go/reflect_optional.go:70 +0xa4 fp=0xc000141830 sp=0xc0001417e0 pc=0x6829c4
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc00021b0b0, 0xc000198c18, 0xc00019f5c0?)
        /home/circleci/go/src/github.com/SAP/cloud-mta/vendor/github.com/json-iterator/go/reflect.go:219 +0x82 fp=0xc000141868 sp=0xc000141830 pc=0x675962
github.com/json-iterator/go.(*Stream).WriteVal(0xc00007cd80, {0x777e20, 0xc000198c18})
        /home/circleci/go/src/github.com/SAP/cloud-mta/vendor/github.com/json-iterator/go/reflect.go:98 +0x158 fp=0xc0001418d8 sp=0xc000141868 pc=0x674c78
github.com/json-iterator/go.(*dynamicEncoder).Encode(0x79f100?, 0xc000198f01?, 0xc00007cd98?)
        /home/circleci/go/src/github.com/SAP/cloud-mta/vendor/github.com/json-iterator/go/reflect_dynamic.go:15 +0x39 fp=0xc000141908 sp=0xc0001418d8 pc=0x677339
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc00019f470, 0x76e9a4?, 0xc00007cd80)
        /home/circleci/go/src/github.com/SAP/cloud-mta/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56 fp=0xc000141980 sp=0xc000141908 pc=0x68adf6
github.com/json-iterator/go.(*structEncoder).Encode(0xc00019f530, 0x8787c8?, 0xc00007cd80)
        /home/circleci/go/src/github.com/SAP/cloud-mta/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x765 fp=0xc000141a68 sp=0xc000141980 pc=0x68b805
github.com/json-iterator/go.(*Stream).WriteVal(0xc00007cd80, {0x7b9aa0, 0xc00019f020})
        /home/circleci/go/src/github.com/SAP/cloud-mta/vendor/github.com/json-iterator/go/reflect.go:98 +0x158 fp=0xc000141ad8 sp=0xc000141a68 pc=0x674c78
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc000120820, {0x7b9aa0, 0xc00019f020})
        /home/circleci/go/src/github.com/SAP/cloud-mta/vendor/github.com/json-iterator/go/config.go:299 +0xc9 fp=0xc000141b70 sp=0xc000141ad8 pc=0x66bda9
github.com/json-iterator/go.Marshal({0x7b9aa0?, 0xc00019f020?})
        /home/circleci/go/src/github.com/SAP/cloud-mta/vendor/github.com/json-iterator/go/adapter.go:34 +0x3b fp=0xc000141b98 sp=0xc000141b70 pc=0x6603fb
github.com/SAP/cloud-mta/mta.printResult({0x777e20?, 0xc000198c18?}, {0x0?, 0x1?, 0x0?}, 0x4000107?, {0x0?, 0x0?}, 0x816750, 0x816a20)
        /home/circleci/go/src/github.com/SAP/cloud-mta/mta/mta_services.go:482 +0x2fe fp=0xc000141cd8 sp=0xc000141b98 pc=0x6ace5e
github.com/SAP/cloud-mta/mta.WriteResult(...)
        /home/circleci/go/src/github.com/SAP/cloud-mta/mta/mta_services.go:467
github.com/SAP/cloud-mta/mta.RunAndWriteResultAndHash({0x7f50d5?, 0x533bf1?}, {0x7ffc1307cbe6, 0x33}, {0x0?, 0x0, 0x0?}, 0x816820)
        /home/circleci/go/src/github.com/SAP/cloud-mta/mta/mta_services.go:514 +0x14c fp=0xc000141d88 sp=0xc000141cd8 pc=0x6ad30c
github.com/SAP/cloud-mta/cmd.glob..func10(0xabcbc0?, {0xc00007a840?, 0x2?, 0x2?})
        /home/circleci/go/src/github.com/SAP/cloud-mta/cmd/mta.go:220 +0x4f fp=0xc000141dd8 sp=0xc000141d88 pc=0x75810f
github.com/spf13/cobra.(*Command).execute(0xabcbc0, {0xc00007a800, 0x2, 0x2})
        /home/circleci/go/src/github.com/SAP/cloud-mta/vendor/github.com/spf13/cobra/command.go:852 +0x67c fp=0xc000141eb0 sp=0xc000141dd8 pc=0x57f2bc
github.com/spf13/cobra.(*Command).ExecuteC(0xabe740)
        /home/circleci/go/src/github.com/SAP/cloud-mta/vendor/github.com/spf13/cobra/command.go:960 +0x39c fp=0xc000141f68 sp=0xc000141eb0 pc=0x57f89c
github.com/spf13/cobra.(*Command).Execute(...)
        /home/circleci/go/src/github.com/SAP/cloud-mta/vendor/github.com/spf13/cobra/command.go:897
github.com/SAP/cloud-mta/cmd.Execute(...)
        /home/circleci/go/src/github.com/SAP/cloud-mta/cmd/root.go:33
main.main()
        /home/circleci/go/src/github.com/SAP/cloud-mta/main.go:11 +0x25 fp=0xc000141f80 sp=0xc000141f68 pc=0x7596a5
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc000141fe0 sp=0xc000141f80 pc=0x435f72
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000141fe8 sp=0xc000141fe0 pc=0x462261
Do you need to install @sap/generator-fiori globally?
npm install -g @sap/generator-fiori
OR
yarn global add @sap/generator-fiori

**Comment by asifui22** [comment]
Hello.
faceing this problem. double check Yamal file. and maintained it as per requirement but no luck

**Comment by ianlancetaylor** [comment]
@asifui22 This issue is closed.  If you think you have found a bug in Go, please open a new issue.  But please be aware that the reflect2 package relies on unsafe and unsupported techniques, and must exactly match the version of Go that you are using.

**Comment by zhuzaiye** [comment]
build command: `go build -v -tags=jsoniter -o elst-primary-api2` main.go will cause this error
but: `go build -v  -o elst-primary-api2` withoud `-tags=jsoniter` will not cause this error

env: go 1.18

reason is "reflect2 package relies on unsafe and unsupported techniques, and must exactly match the version of Go that you are using" ???

```go
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x460e3f]

goroutine 13 [running]:
runtime.throw({0x107fd39?, 0x413b85?})
        C:/Golang/go1.18/src/runtime/panic.go:992 +0x71 fp=0xc000092ec0 sp=0xc000092e90 pc=0x434111
runtime.sigpanic()
        C:/Golang/go1.18/src/runtime/signal_unix.go:825 +0x2ec fp=0xc000092f10 sp=0xc000092ec0 pc=0x44954c
aeshashbody()
        C:/Golang/go1.18/src/runtime/asm_amd64.s:1343 +0x39f fp=0xc000092f18 sp=0xc000092f10 pc=0x460e3f
runtime.mapiternext(0xc00010d100)
        C:/Golang/go1.18/src/runtime/map.go:934 +0x2cb fp=0xc000092f88 sp=0xc000092f18 pc=0x40faab
runtime.mapiterinit(0x40d2c5?, 0xc000037088?, 0xc0000bb330?)
        C:/Golang/go1.18/src/runtime/map.go:861 +0x228 fp=0xc000092fa8 sp=0xc000092f88 pc=0x40f788
reflect.mapiterinit(0xf392e0?, 0xc000676908?, 0xc0000930b8?)
        C:/Golang/go1.18/src/runtime/map.go:1373 +0x19 fp=0xc000092fd0 sp=0xc000092fa8 pc=0x45d999
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
        C:/Golang/goproject/pkg/mod/github.com/modern-go/reflect2@v0.0.0-20180701023420-4b7aa43c6742/unsafe_map.go:112
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc0001773b0, 0xc0000bb360, 0xc000102180)
        C:/Golang/goproject/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_map.go:291 +0x225 fp=0xc000093138 sp=0xc000092fd0 pc=0x78f6a5
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc000109740, 0xc000176bd0, 0xc00010d100?)
        C:/Golang/goproject/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:219 +0x82 fp=0xc000093170 sp=0xc000093138 pc=0x787e22
github.com/json-iterator/go.(*Stream).WriteVal(0xc000102180, {0xf52740, 0xc000176bd0})
        C:/Golang/goproject/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:98 +0x158 fp=0xc0000931e0 sp=0xc000093170 pc=0x787138
github.com/json-iterator/go.(*dynamicEncoder).Encode(0xc000093278?, 0x79e707?, 0xc000102198?)
        C:/Golang/goproject/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_dynamic.go:15 +0x39 fp=0xc000093210 sp=0xc0000931e0 pc=0x789679
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0001771a0, 0xea87c1?, 0xc000102180)
        C:/Golang/goproject/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:110 +0x56 fp=0xc000093288 sp=0xc000093210 pc=0x79c8b6
github.com/json-iterator/go.(*structEncoder).Encode(0xc000177230, 0x1400f88?, 0xc000102180)
        C:/Golang/goproject/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:158 +0x652 fp=0xc000093360 sp=0xc000093288 pc=0x79d1b2
github.com/json-iterator/go.(*Stream).WriteVal(0xc000102180, {0xfd9520, 0xc00010d000})
        C:/Golang/goproject/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:98 +0x158 fp=0xc0000933d0 sp=0xc000093360 pc=0x787138
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc000314500, {0xfd9520, 0xc00010d000})
        C:/Golang/goproject/pkg/mod/github.com/json-iterator/go@v1.1.9/config.go:299 +0xc9 fp=0xc000093468 sp=0xc0000933d0 pc=0x77e3e9
github.com/json-iterator/go.API.Marshal-fm({0xfd9520?, 0xc00010d000?})
        <autogenerated>:1 +0x3e fp=0xc000093490 sp=0xc000093468 pc=0x7a833e
github.com/gin-gonic/gin/render.WriteJSON({0x7fd83fd95840, 0xc000402300}, {0xfd9520, 0xc00010d000})
        C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/render/json.go:69 +0x63 fp=0xc0000934c8 sp=0xc000093490 pc=0x950bc3
github.com/gin-gonic/gin/render.JSON.Render(...)
        C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/render/json.go:55
github.com/gin-gonic/gin/render.(*JSON).Render(0xc000109410?, {0x7fd83fd95840?, 0xc000402300?})
        <autogenerated>:1 +0x45 fp=0xc0000934f8 sp=0xc0000934c8 pc=0x9534e5
github.com/gin-gonic/gin.(*Context).Render(0xc000402300, 0xc8, {0x13f8c50, 0xc000109410})
        C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:913 +0xf8 fp=0xc000093528 sp=0xc0000934f8 pc=0x95b038
github.com/gin-gonic/gin.(*Context).JSON(...)
        C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:956
elst-primary-api/pkg/app.(*Gin).Success(0xf52740?, {0xf52740?, 0xc000176bd0?})
        C:/awsomeworks/awsomework_golang/sinewave_go/elst-primary-api/pkg/app/response.go:30 +0xfe fp=0xc0000935e0 sp=0xc000093528 pc=0xc6cefe
elst-primary-api/controllers/api/v1.GetAppProtocols(0xc000402300?)
        C:/awsomeworks/awsomework_golang/sinewave_go/elst-primary-api/controllers/api/v1/opinion_feedback.go:118 +0x3fb fp=0xc000093688 sp=0xc0000935e0 pc=0xe3f9fb
github.com/gin-gonic/gin.(*Context).Next(...)
        C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165
elst-primary-api/routers.CorsDomain.func1(0xc000402300)
        C:/awsomeworks/awsomework_golang/sinewave_go/elst-primary-api/routers/cors_domain.go:19 +0x138 fp=0xc0000936d0 sp=0xc000093688 pc=0xe6aef8
github.com/gin-gonic/gin.(*Context).Next(...)
        C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1(0xc000402300)
        C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99 +0x82 fp=0xc000093720 sp=0xc0000936d0 pc=0x963742
github.com/gin-gonic/gin.(*Context).Next(...)
        C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc000402300)
        C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241 +0xe7 fp=0xc0000938d8 sp=0xc000093720 pc=0x962867
github.com/gin-gonic/gin.(*Context).Next(...)
        C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000003ba0, 0xc000402300)
        C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489 +0x63e fp=0xc000093a58 sp=0xc0000938d8 pc=0x96191e
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000003ba0, {0x13f9ed0?, 0xc000826460}, 0xc000402200)
        C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445 +0x1c5 fp=0xc000093a98 sp=0xc000093a58 pc=0x961105
net/http.serverHandler.ServeHTTP({0xc000176ab0?}, {0x13f9ed0, 0xc000826460}, 0xc000402200)
        C:/Golang/go1.18/src/net/http/server.go:2916 +0x43b fp=0xc000093b58 sp=0xc000093a98 pc=0x6ca97b
net/http.(*conn).serve(0xc0005750e0, {0x13fab48, 0xc0001769c0})
        C:/Golang/go1.18/src/net/http/server.go:1966 +0x5d7 fp=0xc000093fb8 sp=0xc000093b58 pc=0x6c5977
net/http.(*Server).Serve.func3()
        C:/Golang/go1.18/src/net/http/server.go:3071 +0x2e fp=0xc000093fe0 sp=0xc000093fb8 pc=0x6cb2ce
runtime.goexit()
        C:/Golang/go1.18/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000093fe8 sp=0xc000093fe0 pc=0x463901
created by net/http.(*Server).Serve
        C:/Golang/go1.18/src/net/http/server.go:3071 +0x4db

```

**Comment by zhuzaiye** [comment]
> build command: `go build -v -tags=jsoniter -o elst-primary-api2` main.go will cause this error but: `go build -v -o elst-primary-api2` withoud `-tags=jsoniter` will not cause this error
> 
> env: go 1.18
> 
> reason is "reflect2 package relies on unsafe and unsupported techniques, and must exactly match the version of Go that you are using" ???
> 
> ```go
> unexpected fault address 0x0
> fatal error: fault
> [signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x460e3f]
> 
> goroutine 13 [running]:
> runtime.throw({0x107fd39?, 0x413b85?})
>         C:/Golang/go1.18/src/runtime/panic.go:992 +0x71 fp=0xc000092ec0 sp=0xc000092e90 pc=0x434111
> runtime.sigpanic()
>         C:/Golang/go1.18/src/runtime/signal_unix.go:825 +0x2ec fp=0xc000092f10 sp=0xc000092ec0 pc=0x44954c
> aeshashbody()
>         C:/Golang/go1.18/src/runtime/asm_amd64.s:1343 +0x39f fp=0xc000092f18 sp=0xc000092f10 pc=0x460e3f
> runtime.mapiternext(0xc00010d100)
>         C:/Golang/go1.18/src/runtime/map.go:934 +0x2cb fp=0xc000092f88 sp=0xc000092f18 pc=0x40faab
> runtime.mapiterinit(0x40d2c5?, 0xc000037088?, 0xc0000bb330?)
>         C:/Golang/go1.18/src/runtime/map.go:861 +0x228 fp=0xc000092fa8 sp=0xc000092f88 pc=0x40f788
> reflect.mapiterinit(0xf392e0?, 0xc000676908?, 0xc0000930b8?)
>         C:/Golang/go1.18/src/runtime/map.go:1373 +0x19 fp=0xc000092fd0 sp=0xc000092fa8 pc=0x45d999
> github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
>         C:/Golang/goproject/pkg/mod/github.com/modern-go/reflect2@v0.0.0-20180701023420-4b7aa43c6742/unsafe_map.go:112
> github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc0001773b0, 0xc0000bb360, 0xc000102180)
>         C:/Golang/goproject/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_map.go:291 +0x225 fp=0xc000093138 sp=0xc000092fd0 pc=0x78f6a5
> github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc000109740, 0xc000176bd0, 0xc00010d100?)
>         C:/Golang/goproject/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:219 +0x82 fp=0xc000093170 sp=0xc000093138 pc=0x787e22
> github.com/json-iterator/go.(*Stream).WriteVal(0xc000102180, {0xf52740, 0xc000176bd0})
>         C:/Golang/goproject/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:98 +0x158 fp=0xc0000931e0 sp=0xc000093170 pc=0x787138
> github.com/json-iterator/go.(*dynamicEncoder).Encode(0xc000093278?, 0x79e707?, 0xc000102198?)
>         C:/Golang/goproject/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_dynamic.go:15 +0x39 fp=0xc000093210 sp=0xc0000931e0 pc=0x789679
> github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0001771a0, 0xea87c1?, 0xc000102180)
>         C:/Golang/goproject/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:110 +0x56 fp=0xc000093288 sp=0xc000093210 pc=0x79c8b6
> github.com/json-iterator/go.(*structEncoder).Encode(0xc000177230, 0x1400f88?, 0xc000102180)
>         C:/Golang/goproject/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:158 +0x652 fp=0xc000093360 sp=0xc000093288 pc=0x79d1b2
> github.com/json-iterator/go.(*Stream).WriteVal(0xc000102180, {0xfd9520, 0xc00010d000})
>         C:/Golang/goproject/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:98 +0x158 fp=0xc0000933d0 sp=0xc000093360 pc=0x787138
> github.com/json-iterator/go.(*frozenConfig).Marshal(0xc000314500, {0xfd9520, 0xc00010d000})
>         C:/Golang/goproject/pkg/mod/github.com/json-iterator/go@v1.1.9/config.go:299 +0xc9 fp=0xc000093468 sp=0xc0000933d0 pc=0x77e3e9
> github.com/json-iterator/go.API.Marshal-fm({0xfd9520?, 0xc00010d000?})
>         <autogenerated>:1 +0x3e fp=0xc000093490 sp=0xc000093468 pc=0x7a833e
> github.com/gin-gonic/gin/render.WriteJSON({0x7fd83fd95840, 0xc000402300}, {0xfd9520, 0xc00010d000})
>         C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/render/json.go:69 +0x63 fp=0xc0000934c8 sp=0xc000093490 pc=0x950bc3
> github.com/gin-gonic/gin/render.JSON.Render(...)
>         C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/render/json.go:55
> github.com/gin-gonic/gin/render.(*JSON).Render(0xc000109410?, {0x7fd83fd95840?, 0xc000402300?})
>         <autogenerated>:1 +0x45 fp=0xc0000934f8 sp=0xc0000934c8 pc=0x9534e5
> github.com/gin-gonic/gin.(*Context).Render(0xc000402300, 0xc8, {0x13f8c50, 0xc000109410})
>         C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:913 +0xf8 fp=0xc000093528 sp=0xc0000934f8 pc=0x95b038
> github.com/gin-gonic/gin.(*Context).JSON(...)
>         C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:956
> elst-primary-api/pkg/app.(*Gin).Success(0xf52740?, {0xf52740?, 0xc000176bd0?})
>         C:/awsomeworks/awsomework_golang/sinewave_go/elst-primary-api/pkg/app/response.go:30 +0xfe fp=0xc0000935e0 sp=0xc000093528 pc=0xc6cefe
> elst-primary-api/controllers/api/v1.GetAppProtocols(0xc000402300?)
>         C:/awsomeworks/awsomework_golang/sinewave_go/elst-primary-api/controllers/api/v1/opinion_feedback.go:118 +0x3fb fp=0xc000093688 sp=0xc0000935e0 pc=0xe3f9fb
> github.com/gin-gonic/gin.(*Context).Next(...)
>         C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165
> elst-primary-api/routers.CorsDomain.func1(0xc000402300)
>         C:/awsomeworks/awsomework_golang/sinewave_go/elst-primary-api/routers/cors_domain.go:19 +0x138 fp=0xc0000936d0 sp=0xc000093688 pc=0xe6aef8
> github.com/gin-gonic/gin.(*Context).Next(...)
>         C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165
> github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1(0xc000402300)
>         C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99 +0x82 fp=0xc000093720 sp=0xc0000936d0 pc=0x963742
> github.com/gin-gonic/gin.(*Context).Next(...)
>         C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165
> github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc000402300)
>         C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241 +0xe7 fp=0xc0000938d8 sp=0xc000093720 pc=0x962867
> github.com/gin-gonic/gin.(*Context).Next(...)
>         C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165
> github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000003ba0, 0xc000402300)
>         C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489 +0x63e fp=0xc000093a58 sp=0xc0000938d8 pc=0x96191e
> github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000003ba0, {0x13f9ed0?, 0xc000826460}, 0xc000402200)
>         C:/Golang/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445 +0x1c5 fp=0xc000093a98 sp=0xc000093a58 pc=0x961105
> net/http.serverHandler.ServeHTTP({0xc000176ab0?}, {0x13f9ed0, 0xc000826460}, 0xc000402200)
>         C:/Golang/go1.18/src/net/http/server.go:2916 +0x43b fp=0xc000093b58 sp=0xc000093a98 pc=0x6ca97b
> net/http.(*conn).serve(0xc0005750e0, {0x13fab48, 0xc0001769c0})
>         C:/Golang/go1.18/src/net/http/server.go:1966 +0x5d7 fp=0xc000093fb8 sp=0xc000093b58 pc=0x6c5977
> net/http.(*Server).Serve.func3()
>         C:/Golang/go1.18/src/net/http/server.go:3071 +0x2e fp=0xc000093fe0 sp=0xc000093fb8 pc=0x6cb2ce
> runtime.goexit()
>         C:/Golang/go1.18/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000093fe8 sp=0xc000093fe0 pc=0x463901
> created by net/http.(*Server).Serve
>         C:/Golang/go1.18/src/net/http/server.go:3071 +0x4db
> ```

**when update gin version to latest, this bug will not occur.**
