### ISSUE TITLE
cmd/compile: miscompilation of value switch involving generic interface types

### ISSUE THREAD

**Issue by mdempsky** [golang/go#53477]
https://go.dev/play/p/03EsH4Y3wv3

The above program should terminate quietly with success. However, in Go 1.18, it instead silently miscompiles into code that at runtime panics:

```
panic: interface conversion: main.X is not interface { M(go.shape.int_0) }: missing method M
```

Since this is a silent miscompilation, I think a fix and backport are appropriate. Ideally fix it to compile correctly, but even changing it to ICE would be preferable IMO.

/cc @randall77 @dr2chase @cuonglm

**Comment by dr2chase** [comment]
@randall77 did you see this yet?

**Comment by dr2chase** [comment]
Do we think this needs a backport to 1.18?

**Comment by mdempsky** [comment]
@dr2chase I think so.

@gopherbot Please backport to Go 1.18. This is a silent miscompilation of valid Go code.
