### ISSUE TITLE
x/tools/gopls: do not format broken function call site

### ISSUE THREAD

**Issue by hyangah** [golang/go#53478]
Save this code:

```
package pkg

import (
	"net/http"
)

func handler(w http.ResponseWriter, r *http.Request) {
	http.Error(w, ) // incomplete
}
```

See the "," in `http.Error(w, ) // incomplete` is removed.

I think we shouldn't format the line with syntax errors.

**Comment by muirdm** [comment]
I don't think the trailing comma is a syntax error. To do this we would need to look at the type checker error about missing argument, but that would be a significant departure from gofmt.

**Comment by adonovan** [comment]
As Muir explains, formatting is a very shallow operation that works on any valid parse tree. It does not and cannot use types as part of its formatting decisions.

**Comment by hyangah** [comment]
This case makes me more convinced vscode-go's default behavior that "formats on save" by default is not the right choice. (https://github.com/golang/vscode-go/issues/1815)
