### ISSUE TITLE
flag: UnquoteUsage checks for IsBoolFlag() method presence but doesn't actually call it

### ISSUE THREAD

**Issue by ldemailly** [golang/go#53473]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

not relevant (but apple silicon M1 macos)

### What did you do?

Implemented a generic set of flag extension and part of the generic includes:
```golang
func (d *DynValue[T]) IsBoolFlag() bool {
	var v T
	switch any(v).(type) {
	case bool:
		return true
	default:
		return false
	}
}
```

Yet despite returning false for the non bool, flag.PrintDefaults through UnquoteUsage thinks all my types are booleans (don't require a `value`) and thus my usage output regressed from for instance

```diff
-  -loglevel value
+  -loglevel
         loglevel, one of [Debug Verbose Info Warning Error Critical Fatal]
 (default Info)
```

### What did you expect to see?

`value` still output

### What did you see instead?

nothing

ps: I can workaround by making the bool type special but it's unfortunate

**Comment by ldemailly** [comment]
```golang
package main

import "flag"

type NotBool struct{}

func (f *NotBool) IsBoolFlag() bool {
	return false
}

func (f *NotBool) Set(v string) error {
	return nil
}
func (f *NotBool) String() string {
	return ""
}

func main() {
	value := NotBool{}
	flag.Var(&value, "test", "test usage, line above should be -test value")
	flag.PrintDefaults()
}
```

output
```
% go run .
  -test
    	test usage, line above should be -test value
```

expected:
```
% go run .
  -test value
    	test usage, line above should be -test value
```

https://go.dev/play/p/URV2A7fhI4-

**Comment by ldemailly** [comment]
any chance to backport to 1.19?

**Comment by ianlancetaylor** [comment]
This doesn't seem to me to fit the backport requirements (https://github.com/golang/go/wiki/MinorReleases).

**Comment by ldemailly** [comment]
yes I guess it's not a big bug (even though the fix is really small and safe) - oh well... will wait then, thanks
