### ISSUE TITLE
With the introduction of fuzzing to 1.18 what is the future for "testing/quick"?

### ISSUE THREAD

**Issue by jurisbu** [golang/go#53496]
As I understand there is a certain overlap to "testing/quick" and fuzzing. Currently it seems feature set is not 1 to 1 map and "testing/quick" seems to be more flexible in terms of various argument types that can be tested.

Will fuzzing eventually replace "testing/quick"?

**Comment by seankhliao** [comment]
as the package documentation says

> The testing/quick package is frozen and is not accepting new features.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
