### ISSUE TITLE
net/http: FileServer handles methods it does not understand

### ISSUE THREAD

**Issue by pascaldekloe** [golang/go#53501]
A `DELETE` gets served happily with HTTP 200 (OK) for example. The status code should be HTTP 405 (Method Not Allowed) instead, including an `Allow: GET, HEAD`.

The issue applies to Go versions up to 1.19 beta.

**Comment by pascaldekloe** [comment]
HTTP 200 on a DELETE means that the resource (file) has been removed @jacobishao.

**Comment by dr2chase** [comment]
@neild can you give this and the corresponding CL a look?  It looks plausible to me but IANAE.

**Comment by pascaldekloe** [comment]
Change https://go.dev/cl/413554 is fully approved, yet no commit was made. 🤨 Comments are frozen. I don't have permission to submit.
