### ISSUE TITLE
go/token: AddFile induces heavy contention in parallel parsing [freeze exception]

### ISSUE THREAD

**Issue by adonovan** [golang/go#53507]
https://go-review.googlesource.com/c/go/+/411909 reduces two sources of contention in parser-heavy workloads: FileSet.AddFile allocates memory in the middle of an otherwise tiny critical section, and FileSet.Pos uses a mutex to guard a cache, turning read-only operations into exclusive locks. Both are major sources of contention in gopls.

I'd like to include the fix in the next release.

@golang/release @gri @findleyr

**Comment by cagedmantis** [comment]
This change doesn't seem to pose a significant risk. The release candidate has not been released yet. This change is approved.
