### ISSUE TITLE
runtime: madvdontneed documentation is confusing

### ISSUE THREAD

**Issue by Jorropo** [golang/go#53525]
[In runtime](https://github.com/golang/go/blob/7a82c6859f14d97b741073083849bace7693f7e2/src/runtime/extern.go#L112-L115) we can read:
> madvdontneed: setting madvdontneed=0 will use MADV_FREE
instead of MADV_DONTNEED on Linux when returning memory to the
kernel. This is more efficient, but means RSS numbers will
drop only when the OS is under memory pressure.

I find the `This` here very confusing, I read this as `madvdontneed=0` (`MADV_FREE` fast but bad RSS and `MADV_DONTNEED` slow but accurate) since it's the option explained in the previous sentence while in reality it's speaking about `madvdontneed=1`.

I belive `This` should just be replaced with `MADV_DONTNEED` or `DONTNEED`.

**Comment by ianlancetaylor** [comment]
CC @mknyszek

**Comment by Jorropo** [comment]
@mknyszek thx you are right I confused them.
This then make this sentence correct, I don't think it need to be changed.
