### ISSUE TITLE
cmd/go: TestScript/mod_list_pseudo fails with "server response: 404 page not found" in AIX

### ISSUE THREAD

**Issue by ayappanec** [golang/go#53533]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.17.11
</pre>

### Does this issue reproduce with the latest release?
The issue is seen in the recent versions of 1.17.X releases, ie., 1.17.11 & 1.17.10 but not in 1.17.9 
Not sure about 1.18.X release though. 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="ppc64"
GOBIN=""
GOCACHE="/home/buildusr/.cache/go-build"
GOENV="/home/buildusr/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="ppc64"
GOHOSTOS="aix"
GOINSECURE=""
GOMODCACHE="/home/buildusr/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="aix"
GOPATH="/home/buildusr/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/freeware/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/freeware/lib/golang/pkg/tool/aix_ppc64"
GOVCS=""
GOVERSION="go1.17.9"
GCCGO="gccgo"
GOPPC64="power8"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -maix64 -pthread -mcmodel=large -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build931399689=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

As part of building go 1.17.11, the test suites are ran and there we see "TestScript/mod_list_pseudo" is failing. 

....
ok      cmd/compile/internal/types2     6.106s
ok      cmd/cover       32.048s
ok      cmd/doc 1.434s
ok      cmd/fix 20.615s
go test proxy running at GOPROXY=http://127.0.0.1:44088/mod
--- FAIL: TestScript (0.06s)
    --- FAIL: TestScript/mod_list_pseudo (1.64s)
        script_test.go:253:
            # Regression test for golang.org/issue/32715.
            # When using $GOPATH/pkg/mod/cache/download as a proxy,
            # 'latest' queries should prefer tagged versions over pseudo-versions. (0.655s)
            > go mod download github.com/dmitshur-test/modtest5@v0.0.0-20190619020302-197a620e0c9a
            > go mod download github.com/dmitshur-test/modtest5@v0.5.0-alpha
            > go mod download github.com/dmitshur-test/modtest5@v0.5.0-alpha.0.20190619023908-3da23a9deb9
e
            [stderr]
            go mod download: github.com/dmitshur-test/modtest5@v0.5.0-alpha.0.20190619023908-3da23a9deb9e
: reading http://127.0.0.1:44088/mod/github.com/dmitshur-test/modtest5/@v/v0.5.0-alpha.0.20190619023908-3
da23a9deb9e.info: 404 Not Found
                server response: 404 page not found
            [exit status 1]
            FAIL: testdata/script/mod_list_pseudo.txt:10: unexpected command failure

FAIL
FAIL    cmd/go  723.774s
ok      cmd/go/internal/auth    0.056s

The same failure is also seen with 1.17.10 but not in 1.17.9
So I presume some changes that went in 1.17.10 has created this regression.

**Comment by heschi** [comment]
cc @bcmills

**Comment by bcmills** [comment]
> I presume some changes that went in 1.17.10 has created this regression.

Looking at the log in https://go.googlesource.com/go/+log/refs/heads/release-branch.go1.17 I don't see anything in between 1.17.9 and 1.17.10 that seems even remotely related.

@ayappanec, what happens if you run `go clean -testcache`? If it still reproduces in the same way, can you `git bisect` the exact start of the failure?

**Comment by ayappanec** [comment]
The problem is with AIX native tar command unable to properly extract the testdata file. It extracts the file as " github.com_dmitshur-test_modtest5_v0.5.0-alpha.0.20190619023908-3da23a9de " rather than as "github.com_dmitshur-test_modtest5_v0.5.0-alpha.0.20190619023908-3da23a9deb9e.txt". 
I think the go source tar file generation changed from 1.17.10 onwards , probably some encoding related things. 
Once I used GNU tar in AIX , it is proper. 

Anyway I close this issue as it is not really a go issue.
