### ISSUE TITLE
x/pkgsite: part of github.com/rk0cc's and organization packages removal request

### ISSUE THREAD

**Issue by rk0cc** [golang/go#53546]
### What is the path of the package that you would like to have removed?

* github.com/rk0cc/restsnap-dl-lib
* github.com/rk0cc/bobsfou
* github.com/rk0cc/shakv/kvpair
* github.com/Anitemp-Health/atda

### Are you the owner of this package?

Yes. (Including @Anitemp-Health which I am a founder of this organization)

### What is the reason that you could not retract this package instead?

<table>
    <thead>
        <tr>
            <th>Package</th>
            <th>Reason to be removed</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>github.com/rk0cc/bobsfou</td>
            <td rowspan="3">These projects have been abandoned already.</td>
        </tr>
        <tr>
            <td>github.com/rk0cc/restsnap-dl-lib</td>
        </tr>
        <tr>
            <td>github.com/rk0cc/shakv/kvpair</td>
        </tr>
        <tr>
            <td>github.com/Anitemp-Health/atda</td>
            <td>
                 Design fault when pocessing binary data with ignoring max capacity of slice
                 <br/>
                 (It should be better with buffer)
            </td>
        </tr>
    </tbody>
</table>

**Comment by findleyr** [comment]
This is done.
