### ISSUE TITLE
net/http: problematic content type check

### ISSUE THREAD

**Issue by xepozz** [golang/go#53545]
When go http server cannot recognize content type it tries to read 512 bytes from the resource. You can see it [here](https://github.com/golang/gofrontend/blob/47380f733ca932384e59492d2f04374edd8ec95e/libgo/go/net/http/fs.go#L238).

It's a dirty cheat. 
First of all the resource can be unavailable for further reading.
Secondly if you try to implement your own WebDAV server you need to append or cut part of bytes to fill the buffer right.
Due to code will smell like the following.
```golang
if len(f.data) < len(p) {
	// min buffer for http server is 512, so if file is less than one we need to add empty bytes
	missed := len(p) - len(f.data)
	copy(p, append(make([]byte, missed)))
} else {
	copy(p, f.data[:len(p)])
}
```

Any ideas how to prevent this behaviour? 
BTW go hasn't recognized `.md` and `.py` files as `text/plain` type.

**Comment by ianlancetaylor** [comment]
You don't have to supply 512 bytes to satisfy the content type check.  You can simply return the bytes available, and then `io.EOF`.

Go will read the MIME extensions that are defined on your system.  You didn't mention what kind of system you are using.  Your program can define additional MIME extensions by calling https://pkg.go.dev/mime#AddExtensionType.

I don't see a bug here, and we don't use the issue tracker for questions or discussion, so closing.  If you have further questions, please see https://go.dev/wiki/Questions.

**Comment by xepozz** [comment]
> You don't have to supply 512 bytes to satisfy the content type check. You can simply return the bytes available, and then io.EOF.

Thanks, I will try next time.
I'm under MacOS 12.4.
