### ISSUE TITLE
affected/package: `go build` or `go mod vendor` excessive downloading to go/pkg/mod/cache 

### ISSUE THREAD

**Issue by mgholam** [golang/go#53548]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

1. Building a project with a 23 MB `vendor` folder and cleared `cache` folder works fine (all files for building present).
2. Building the same project with no `vendor` folder and cleared `cache` folder download +800 MB.

### What did you expect to see?
I expect `go mod tidy` or `go mod vendor` to only download what is needed to build i.e 23 MB not +800 MB

### What did you see instead?
Excessive download to the `go/pkg/mod/cache` folder.

**Comment by mvdan** [comment]
`go mod vendor` only keeps needed packages, but the downloading of dependencies happens at the module level. A module will often contain packages you don't need right now.

For reference, see https://go.dev/ref/mod.
