### ISSUE TITLE
x/website: ref/mod GOWORK should be capitalized in "go env gowork"

### ISSUE THREAD

**Issue by kkasemos** [golang/go#53550]
### What is the URL of the page with the issue?
https://go.dev/ref/mod#workspaces
 
 
### What is your user agent?
[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes) 

 
 
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/1111838/175758385-34fdd864-bf91-471d-8f9b-429ec9c7f999.png)

 
 
 
### What did you do?
Reading the content 

 
 
 
### What did you expect to see?
 Should gowork be GOWORK?
 
 
### What did you see instead?
gowork

**Comment by eistak** [comment]
@kkasemos 
Thanks for your raising issue and sorry for jump in.
I pushed the CL below earlier regarding this issue.
https://go-review.googlesource.com/c/website/+/414154

I'm a newbie in Go lang community and wanted to know the way how to contribute this community.
It'd be great if you could tell me this kind of post or commit way were inappropriate.

**Comment by kkasemos** [comment]
@eistak
Thank you for the information.

I'm new to the community as well.

From my view (worked as API support before), it is always great for users to hear that their issue was already fixed.
