### ISSUE TITLE
x/sys/unix: missing socket constants

### ISSUE THREAD

**Issue by AlonZivony** [golang/go#53557]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.18.2

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/alonz/.cache/go-build"
GOENV="/home/alonz/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/alonz/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/alonz/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/alonz/go/src/libbpfgo/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1901468926=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I am using the x/sys/unix pacakge.
I want to support all possible socket `level` and `optname` values for the `setsocketopt` syscall, but some of the values have no constants (because they are from newer kernel versions).

The following values are missing:
* `level`:
    * SOL_MCTCP
    * SOL_MCTP
    * SOL_SMC

* `optname`:
    * SO_NETNS_COOKIE
    * SO_BUF_LOCK
    * SO_RESERVE_MEM
    * SO_TXREHASH

### What did you expect to see?

I want to use the values like the following - `unix.SOL_MCTCP`.

**Comment by seankhliao** [comment]
From https://pkg.go.dev/golang.org/x/sys/unix the only ones I see missing are "SOL_MCTCP" and "SOL_SMC", but I also don't see "SOL_MCTCP" mentioned anywhere on the internet at all?

**Comment by AlonZivony** [comment]
You are right, it seems that the `optname` values are available in the newest version.
About the missing `level` values - you can see that they are supported by the newest kernel in the following source code page - https://elixir.bootlin.com/linux/latest/source/include/linux/socket.h#L330

**Comment by ianwoolf** [comment]
Do the following source code pages support the missing `optname`?  I send a cl according to the following code.

> https://elixir.bootlin.com/linux/latest/source/include/uapi/asm-generic/socket.h#L125

**Comment by ianwoolf** [comment]
> I assume you meant `SOL_MPTCP`, not `SOL_MCTCP`?
> 
> All but `SOL_SMC` should be in latest tip of the package:
> 
> ```
> % git grep -E "SOL_(MPTCP|MCTP|SMC)"
> zerrors_linux.go:2583:  SOL_MCTP                                    = 0x11d
> zerrors_linux.go:2584:  SOL_MPTCP                                   = 0x11c
> ```
> 
> It seems we generate these constants from glibc's sys/socket.h, and glibc 2.35 which [we currently use to generate](https://cs.opensource.google/go/x/sys/+/87e55d71:unix/linux/Dockerfile;l=20-21) the constants doesn't seem to have `SOL_SMC` yet. If we want `SOL_SMC` now, without waiting for a glibc version providing it, we could probably add it similarly to how `SOL_NETLINK` is defined: https://cs.opensource.google/go/x/sys/+/87e55d71:unix/mkerrors.sh;l=294-296

the `level` add to glibc at the following commit

- https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=6488f4d00653b489e7969c0a489dc665c26514a8;hp=81e7fdd7ccff3745db0b0d8ffa1ec9fab6dcee67
- https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=fdc1ae67fef27eea1445bab4bdfe2f0fb3bc7aa1;hp=2c0915cbf570cb9c8a65f1d20a55c5a7238e5b63

glibc 2.35 not contain these commit. So glibc 2.35 which [we currently use to generate](https://cs.opensource.google/go/x/sys/+/87e55d71:unix/linux/Dockerfile;l=20-21) the constants doesn't have `SOL_SMC` `SOL_MPTCP` and `SOL_MCTP` yet.  

 Do we need to wait for glibc to release? 

@ianlancetaylor

**Comment by ianlancetaylor** [comment]
We don't have to wait for glibc.  But we do need to ensure that anything we do is correct for all supported operating systems.  I'm frankly pretty skeptical about the `SOL_NETLINK` code mentioned above.

**Comment by ianlancetaylor** [comment]
Argh, I totally missed that.  Thanks.  This approach seems fine.
