### ISSUE TITLE
affected/package: 修正websocket大小写拼写

### ISSUE THREAD

**Issue by f4nff** [golang/go#53570]
![image](https://user-images.githubusercontent.com/19538878/175961050-a6305a25-a7b7-4364-9fed-5d586b44af1b.png)
![image](https://user-images.githubusercontent.com/19538878/175961068-6aae53b6-f607-4d8f-a798-45890b01a6a0.png)
[reader.zip](https://github.com/golang/go/files/8992693/reader.zip)

**Comment by mvdan** [comment]
You didn't fill the template, and we can't read the title, so I'm going to close this for now. Also, please don't post screenshots of text - just post the text or links to code.

The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
