### ISSUE TITLE
cmd/link: ELF external linking puts all symbols in dynamic symbol table

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#53579]
Currently external linking on ELF systems passes `-rdynamic` to the external linker, which tells it to put all exported symbols into the dynamic symbol table.  This is unnecessary in the normal case.  It wastes space in the executable, and effectively disables garbage collection in the external linker.  We should instead only export symbols that may need to be exported.

I have a patch for this which we can try for the 1.20 release.

**Comment by tkoeppe** [comment]
Interesting that there are so many linkers that don't have `--export-dynamic-symbol`. Do they perhaps offer some other way of selectively exporting symbols?

**Comment by ianlancetaylor** [comment]
`--export-dynamic-symbol` was added to GNU ld in the 2.35 release (mid-2020).  The gold linker has had it since 2012.  lld has it; I don't know when it was added but it has probably always had it.

I think we're just seeing builders using older versions of the GNU linker.  I don't think the GNU linker provides any other mechanism.

**Comment by tkoeppe** [comment]
Re "how long can the command line get": instead of `--export-dynamic-symbol` we have also been using `--dynamic-list` and put all the to-be-exported symbols in a file. That flag too might not be universally available, though.

**Comment by tkoeppe** [comment]
Fair enough. I think with lld the various flags can be combined and the symbol lists are merged, but I also don't find the documentation entirely clear.
