### ISSUE TITLE
windows10/installation: I encountered anomalies with go1.18.3.windows-amd64.msi 

### ISSUE THREAD

**Issue by truthadjustr** [golang/go#53581]
- go version go1.18.3 windows/amd64
- Yes
- I am using Windows 10
- I edited Windows 10 environment variable with all my might

The `GOPATH` environment variable cannot be redefined under `user1` in a Windows 10 system from where it was installed. It always stick to `$USER/go` value. However, if I switch to `user2`, I can see the `GOPATH` re-definition there. 

Open DOS console and `echo %GOPATH%`.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by truthadjustr** [comment]
I am just reporting that it is a bug in the installer, probably. It is hard-coding `GOPATH` to a fixed value.
