### ISSUE TITLE
os: Symlink returns Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by zdszxp** [golang/go#53582]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.10 windows/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOOS=windows
set GOPROXY=https://proxy.golang.org,direct
set GOSUMDB=sum.golang.google.cn
set GOTMPDIR=
set GOVCS=
set GOVERSION=go1.16.10
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

</pre></details>

### What did you do?
I ran this test (go\src\os\os_test.go's TestSymlink):

```golang
func TestSymlink(t *testing.T) {
	testenv.MustHaveSymlink(t)

       /-----------------add code begin---------------
        now := time.Now()
	now.Zone()
       /-----------------end----------------------------

	defer chtmpdir(t)()
	from, to := "symlinktestfrom", "symlinktestto"
	file, err := Create(to)
	if err != nil {
		t.Fatalf("Create(%q) failed: %v", to, err)
	}
	if err = file.Close(); err != nil {
		t.Errorf("Close(%q) failed: %v", to, err)
	}
	err = Symlink(to, from)
	if err != nil {
		t.Fatalf("Symlink(%q, %q) failed: %v", to, from, err)
	}
	tostat, err := Lstat(to)
	if err != nil {
		t.Fatalf("Lstat(%q) failed: %v", to, err)
	}
	if tostat.Mode()&ModeSymlink != 0 {
		t.Fatalf("Lstat(%q).Mode()&ModeSymlink = %v, want 0", to, tostat.Mode()&ModeSymlink)
	}
	fromstat, err := Stat(from)
	if err != nil {
		t.Fatalf("Stat(%q) failed: %v", from, err)
	}
	if !SameFile(tostat, fromstat) {
		t.Errorf("Symlink(%q, %q) did not create symlink", to, from)
	}
	fromstat, err = Lstat(from)
	if err != nil {
		t.Fatalf("Lstat(%q) failed: %v", from, err)
	}
	if fromstat.Mode()&ModeSymlink == 0 {
		t.Fatalf("Lstat(%q).Mode()&ModeSymlink = 0, want %v", from, ModeSymlink)
	}
	fromstat, err = Stat(from)
	if err != nil {
		t.Fatalf("Stat(%q) failed: %v", from, err)
	}
	if fromstat.Name() != from {
		t.Errorf("Stat(%q).Name() = %q, want %q", from, fromstat.Name(), from)
	}
	if fromstat.Mode()&ModeSymlink != 0 {
		t.Fatalf("Stat(%q).Mode()&ModeSymlink = %v, want 0", from, fromstat.Mode()&ModeSymlink)
	}
	s, err := Readlink(from)
	if err != nil {
		t.Fatalf("Readlink(%q) failed: %v", from, err)
	}
	if s != to {
		t.Fatalf("Readlink(%q) = %q, want %q", from, s, to)
	}
	file, err = Open(from)
	if err != nil {
		t.Fatalf("Open(%q) failed: %v", from, err)
	}
	file.Close()
}
```

### What did you expect to see?

I expected the test to pass.

### What did you see instead?

```golang
=== RUN   TestSymlink
    os_test.go:903: Symlink("symlinktestto", "symlinktestfrom") failed: symlink symlinktestto symlinktestfrom: Cannot create a file when that file already exists.
--- FAIL: TestSymlink (0.04s)
```

If I don't add the relevant code about the time, the test passes, but if I add it, the link can't be created

**Comment by zdszxp** [comment]
> Per the [Go release policy](https://go.dev/doc/devel/release#policy), `go1.16.10` is no longer supported. Does this issue still reproduce on a supported release or at HEAD?
> 
> For that matter, how are you running an `os` test with local changes using a released Go version? 🤔
> 
> What was the exact command line that you ran to run the test?
> 
> Some versions of Windows require that the program be run with Administrator privileges to create symlinks; [Windows 10 and after](https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/) also allows other users to create symlinks if the device is in Developer Mode. If symlinks are not enabled, that should cause `testenv.MustHaveSymlink` to skip the test. What version of Windows are you running, and do you have Developer Mode enabled?

yes, this issue can reproduce with the latest release go1.18.3。I have run the test with Administrator privileges to create symlinks,and it can create symlinks but it returns errror。I just show the existence of this problem through this test。You can call symlink after calling zone and the problem will arise

**Comment by ianlancetaylor** [comment]
Please tell us exactly what you are doing, and exactly what happens.  If you are modifying the code that comes with Go, please show us the complete file that you are running.  Thanks.

**Comment by zdszxp** [comment]
> Please tell us exactly what you are doing, and exactly what happens. If you are modifying the code that comes with Go, please show us the complete file that you are running. Thanks.

I don't  modify the code that comes with Go.You can run this test:
```golang
func TestSymlink(t *testing.T) {
	now := time.Now()
	now.Zone()
	from, to := "symlinktestfrom", "symlinktestto"
	file, err := os.Create(to)
	if err != nil {
		t.Fatalf("Create(%q) failed: %v", to, err)
	}
	if err = file.Close(); err != nil {
		t.Errorf("Close(%q) failed: %v", to, err)
	}
	err = os.Symlink(to, from)
	if err != nil {
		t.Fatalf("Symlink(%q, %q) failed: %v", to, from, err)
	}
}
```

```golang
=== RUN   TestSymlink
    util_test.go:71: Symlink("symlinktestto", "symlinktestfrom") failed: symlink symlinktestto symlinktestfrom: Cannot create a file when that file already exists.
--- FAIL: TestSymlink (0.02s)

FAIL
```

**Comment by zdszxp** [comment]
> Hmm, I don't reproduce this.
> 
> ![image](https://user-images.githubusercontent.com/10111/176392880-03cb9d73-f6c4-4d0b-a566-3082afa3041c.png)
> 
> Could you please test with adding small sleep?
> 
> ```go
> func TestSymlink(t *testing.T) {
>         now := time.Now()
>         now.Zone()
>         from, to := "symlinktestfrom", "symlinktestto"
>         file, err := os.Create(to)
>         if err != nil {
>                 t.Fatalf("Create(%q) failed: %v", to, err)
>         }
>         if err = file.Close(); err != nil {
>                 t.Errorf("Close(%q) failed: %v", to, err)
>         }
> 
>         time.Sleep(1 * time.Second)
> 
>         err = os.Symlink(to, from)
>         if err != nil {
>                 t.Fatalf("Symlink(%q, %q) failed: %v", to, from, err)
>         }
> }
> ```

![image](https://user-images.githubusercontent.com/16612321/176397734-2afe343b-e956-47fe-935a-eaf579f8e4e3.png)

**Comment by mattn** [comment]
Do you always check that symlinktestfrom does not exist before testing?

**Comment by zdszxp** [comment]
> Do you always check that symlinktestfrom does not exist before testing?

I debug the code. The code src\os\file_windows.go:369 returns ERROR_ACCESS_DENIED (5),  but the symbolic link has been created, then CreateSymbolicLink in src\os\file_windows.go:374 creates it again

**Comment by mattn** [comment]
I don't understand what happen on this case, but at least os.Symlink for Window should not do second try if err is not ERROR_PRIVILEGE_NOT_HELD, I think.

```diff
diff --git a/src/os/file_windows.go b/src/os/file_windows.go
index db5c27dd30..c0cb501450 100644
--- a/src/os/file_windows.go
+++ b/src/os/file_windows.go
@@ -368,6 +368,9 @@ func Symlink(oldname, newname string) error {
 	}
 	err = syscall.CreateSymbolicLink(n, o, flags)
 	if err != nil {
+		if err.(syscall.Errno) != syscall.ERROR_PRIVILEGE_NOT_HELD {
+			return err
+		}
 		// the unprivileged create flag is unsupported
 		// below Windows 10 (1703, v10.0.14972). retry without it.
 		flags &^= windows.SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE
```

**Comment by zdszxp** [comment]
> @zdszxp It sounds like you are saying that even though `CreateSymbolicLink` returns `ERROR_ACCESS_DENIED`, it creates the symlink anyhow. Why would it do that?

yes

**Comment by zdszxp** [comment]
> I don't understand what happen on this case, but at least os.Symlink for Window should not do second try if err is not ERROR_PRIVILEGE_NOT_HELD, I think.
> 
> ```diff
> diff --git a/src/os/file_windows.go b/src/os/file_windows.go
> index db5c27dd30..c0cb501450 100644
> --- a/src/os/file_windows.go
> +++ b/src/os/file_windows.go
> @@ -368,6 +368,9 @@ func Symlink(oldname, newname string) error {
>  	}
>  	err = syscall.CreateSymbolicLink(n, o, flags)
>  	if err != nil {
> +		if err.(syscall.Errno) != syscall.ERROR_PRIVILEGE_NOT_HELD {
> +			return &LinkError{"symlink", oldname, newname, err}
> +		}
>  		// the unprivileged create flag is unsupported
>  		// below Windows 10 (1703, v10.0.14972). retry without it.
>  		flags &^= windows.SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE
> ```



> ```go
> ERROR_ACCESS_DENIED 
> ```

This is a question, but another question is, why it will return ERROR_ACCESS_DENIED) in windows10, when I call now.Zone before calling os.Symlink, but the link is still created successfully, if I remove the code about time, os.Symlink executes correctly

**Comment by alexbrainman** [comment]
> I run this code:

@zdszxp why do you use `E:` drive to run your code on? What is `E:` drive mapped to?

I cannot reproduce your issue here.

I run this test https://go.dev/play/p/TMpFxBKkafD as simple user on my local `C:` drive:

```
c:\Users\user\dev\src\issues\go\53582>a.exe -test.v
=== RUN   TestSymlink
    a_test.go:22: Symlink("symlinktestto", "symlinktestfrom") failed: symlink symlinktestto symlinktestfrom: A required privilege is not held by the client.
--- FAIL: TestSymlink (0.00s)
FAIL

c:\Users\user\dev\src\issues\go\53582>
```

As simple user on `X:` drive that is mapped to remote samba server:

```
X:\rw>copy /y c:\Users\user\dev\src\issues\go\53582\a.exe . && a.exe -test.v
        1 file(s) copied.
=== RUN   TestSymlink
    a_test.go:22: Symlink("symlinktestto", "symlinktestfrom") failed: symlink symlinktestto symlinktestfrom: A required privilege is not held by the client.
--- FAIL: TestSymlink (0.03s)
FAIL

X:\rw>
```

And locally as an Administrator:

```
C:\WINDOWS\system32>cd c:\Users\user\dev\src\issues\go\53582

c:\Users\user\dev\src\issues\go\53582>a.exe -test.v
=== RUN   TestSymlink
--- PASS: TestSymlink (0.00s)
PASS

c:\Users\user\dev\src\issues\go\53582>
```

Perhaps you can try and put some println in Go library code and figure out what is happening on your PC. Please note that your system environment will affect your result. See https://github.com/golang/go/issues/53582#issuecomment-1168802469 for  example.

I also noticed that CreateSymbolicLink API uses `BOOLEAN` return type, unlike all other Windows API that use `BOOL`. You can see it listed in https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinkw . But Go code is using `BOOLEAN`. And `BOOLEAN` appears to be correct value according to current Microsoft docs and https://microsoft.public.win32.programmer.kernel.narkive.com/Xd6JhpEr/createsymboliclink-problem-in-windows-7-rtm (I googled for it).

Not sure what to do here.

Alex
