### ISSUE TITLE
net/http: failures with `ERROR_OPERATION_ABORTED` on windows/arm64

### ISSUE THREAD

**Issue by bcmills** [golang/go#53584]
```
--- FAIL: TestServerHijackGetsBackgroundByte (0.00s)
    serve_test.go:5911: Peek = "", read tcp 127.0.0.1:51202->127.0.0.1:51203: wsarecv: The I/O operation has been aborted because of either a thread exit or an application request.; want foo, nil
    serve_test.go:5916: context unexpectedly canceled
FAIL
FAIL	net/http	7.162s
```

`greplogs -l -e 'The I/O operation has been aborted(?:.*\n)*FAIL\s+net/http'`
[2022-06-28T16:57:18-533082d/windows-arm64-11](https://build.golang.org/log/646e74ccd1a67ab5b4544e769e60cb968eb69561)

This is the same error message observed on this platform (in a different test) in #52893.

This error code seems to be `ERROR_OPERATION_ABORTED`.
(https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--500-999-)

(CC @neild @golang/windows @qmuntal)

**Comment by bcmills** [comment]
[2022-07-07T19:06:45-84e58bf-8ac58de/windows-arm64-10](https://build.golang.org/log/19c253b30970693c188b30a40acf40b389017a9d):
```
2022/07/07 20:56:22 Close("uploads/20220708.1/0.txt") took 0.00 seconds
2022/07/07 20:56:22 query: q="label0:0" sql={"SELECT r.Content FROM (SELECT UploadID, RecordID FROM RecordLabels WHERE Name = ? AND Value = ?) t0 LEFT JOIN Records r USING (UploadID, RecordID)" []interface {}{"label0", "0"}}
2022/07/07 20:56:22 query: q="label1:0" sql={"SELECT r.Content FROM (SELECT UploadID, RecordID FROM RecordLabels WHERE Name = ? AND Value = ?) t0 LEFT JOIN Records r USING (UploadID, RecordID)" []interface {}{"label1", "0"}}
2022/07/07 20:56:22 query: q="label0:5 name:Name" sql={"SELECT r.Content FROM (SELECT UploadID, RecordID FROM RecordLabels WHERE Name = ? AND Value = ?) t0 INNER JOIN (SELECT UploadID, RecordID FROM RecordLabels WHERE Name = ? AND Value = ?) t1 USING (UploadID, RecordID) LEFT JOIN Records r USING (UploadID, RecordID)" []interface {}{"label0", "5", "name", "Name"}}
2022/07/07 20:56:22 query: q="label0:0 label0:5" err=EOF
2022/07/07 20:56:22 Close("uploads/20220708.1/0.txt") took 0.00 seconds
2022/07/07 20:56:22 Close("uploads/20220708.2/0.txt") took 0.00 seconds
2022/07/07 20:56:22 multipart: NextPart: read tcp 127.0.0.1:49791->127.0.0.1:49792: wsarecv: The I/O operation has been aborted because of either a thread exit or an application request.
--- FAIL: TestUploads (0.00s)
    upload_test.go:90: /upload response:
        {"uploadid":"20220708.1","fileids":["20220708.1/0"],"viewurl":"view:20220708.1"}
    upload_test.go:90: /upload response:
        {"uploadid":"20220708.2","fileids":["20220708.2/0"],"viewurl":"view:20220708.2"}
    upload_test.go:84: post /upload: 500 Internal Server Error
2022/07/07 20:56:22 Close("uploads/20220708.1/0.txt") took 0.00 seconds
FAIL
FAIL	golang.org/x/perf/storage/app	0.239s
```

**Comment by bcmills** [comment]
Gathering all of these occurrences in one place, since this looks like either a `net/http` bug or a platform bug exposed by `net/http`.

`greplogs -l -e 'The I/O operation has been aborted'`
[2022-07-07T19:06:45-84e58bf-8ac58de/windows-arm64-10](https://build.golang.org/log/19c253b30970693c188b30a40acf40b389017a9d)
[2022-06-28T16:57:18-533082d/windows-arm64-11](https://build.golang.org/log/646e74ccd1a67ab5b4544e769e60cb968eb69561)
[2022-06-06T20:48:03-c960675-a71ca3d/windows-arm64-10](https://build.golang.org/log/d3e571b1e0919c4c38aaf57ac44d70d39354a0e7)
[2022-06-01T22:59:44-c960675-46ab7a5/windows-arm64-11](https://build.golang.org/log/dcacf63ad7350b63946609fa45671ad25e5dad50)
[2022-05-23T22:10:24-2e3eb7b-2138124/windows-arm64-10](https://build.golang.org/log/23d77d351267e20b6d39f5db14aec40b79b419f5)

**Comment by qmuntal** [comment]
I'm looking into this. Still trying to reproduce it.

**Comment by bcmills** [comment]
There have been a lot of `net/http` fixes since this issue was filed, and `watchflakes` will file a new issue should it recur.

@qmuntal, should we close this as obsolete?

**Comment by qmuntal** [comment]
> @qmuntal, should we close this as obsolete?

Yes, I couldn't repro nor find the culprit.
