### ISSUE TITLE
crypto/x509: ParseRevocationList misses entry extensions

### ISSUE THREAD

**Issue by aarongable** [golang/go#53592]
### What version of Go are you using (`go version`)?

go1.19beta1

### What did you do?

1) Create an `x509.RevocationList` with an entry which has extensions (such as a reasonCode)
2) Use `x509.CreateRevocationList` to sign and serialize the CRL to DER
3) Use `x509.ParseRevocationList` to parse the CRL

Full demonstration: https://go.dev/play/p/ejqFzRaValY?v=gotip

### What did you expect to see?

The exact same in-memory structures should be recreated. In particular, the individual entries should still have all of their extensions.

### What did you see instead?

Individual entries are missing their extensions.

**Comment by dr2chase** [comment]
@agl @FiloSottile can one or both of you give the CL a look?  This code is not my department, though the bug looks completely plausible.

**Comment by aarongable** [comment]
@rolandshoemaker is this also worth a freeze exception?
