### ISSUE TITLE
cmd/go: 'go list -m -u' fails when latest version is retracted

### ISSUE THREAD

**Issue by jayconrod** [golang/go#53594]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/jay/Library/Caches/go-build"
GOENV="/Users/jay/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jay/go/pkg/mod"
GONOPROXY="[redacted]"
GONOSUMDB="[redacted]"
GOOS="darwin"
GOPATH="/Users/jay/go"
GOPRIVATE="[redacted]"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go/installed"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/installed/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/58/l_czn8qd73v1dstwqh3xmf2m0000gn/T/go-build1355845410=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

1. Require a module, say `example.com/m`, at the highest release version, say `v1.2.0`, which is retracted.
2. Run `go list -m -u example.com/m`

### What did you expect to see?

`go list -m -u` should report the module path and current version and note that the current version is retracted. It should not report an update.

```
$ go list -m -u example.com/m
example.com/m v1.2.0 (retracted)
```

### What did you see instead?

`go list -m -u` exits with a non-zero status and prints an error about the retraction.

```
$ go list -m -u example.com/m
go: example.com/m@v1.2.0: retracted by module author: Accidentally published. Use v0.2.0 instead.
$ echo $?
1
```

**Comment by dr2chase** [comment]
@bcmills can you (in your copious free time) have a look at the CL?  It looks safe and sensible to me.
