### ISSUE TITLE
os: OpenFile always truncates (ignores flags)

### ISSUE THREAD

**Issue by aytekinar** [golang/go#53591]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

My host OS is Windows 11 Enterprise.

I am using Go inside a (Docker-based) development container (based on the image `golang:1.18-bullseye`) under Visual Studio Code.

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/workspace/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2210480654=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I have used the following Go code:

```go
// main.go
package main

import (
	"log"
	"os"
)

func overwriteFileWithGarbage(garbage string) (n int, err error) {
	file, err := os.OpenFile("/tmp/some-file.txt", os.O_CREATE|os.O_WRONLY, 0666)
	if err != nil {
		return
	}
	defer func() {
		if fileErr := file.Close(); err == nil {
			err = fileErr
		}
	}()
	n, err = file.WriteString(garbage)
	return
}

func main() {
	if n, err := overwriteFileWithGarbage("garbage"); err != nil {
		log.Fatalf("error occurred: %v\n", err)
	} else {
		log.Printf("%d bytes written\n", n)
	}
}
```

and run the following to reproduce the issue:

```bash
$ echo "line-1" >> /tmp/some-file.txt
$ echo "line-2" >> /tmp/some-file.txt
$ echo "line-3" >> /tmp/some-file.txt
$ cat /tmp/some-file.txt
line-1
line-2
line-3
$ go run main.go
2022/06/28 21:56:02 7 bytes written
```

### What did you expect to see?

```bash
$ cat /tmp/some-file.txt 
garbage
```

### What did you see instead?

```bash
$ cat /tmp/some-file.txt 
garbageline-2
line-3
```

**Comment by seankhliao** [comment]
looks normal, did your want `O_TRUNC`?

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by aytekinar** [comment]
Apologies for the noise! I think I should take a break, now.

Somehow, I have been reading/inferring `O_TRUNC` as being `O_APPEND`. Hence, leaving `O_TRUNC` outside, I was thinking/hoping to get the file created from scratch every time 🤦🏻 Totally my bad!
