### ISSUE TITLE
encoding/base32: uses more space in buffer than returned in EncodedLen method

### ISSUE THREAD

**Issue by mateusz834** [golang/go#53606]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go version go1.18.3 linux/amd64
[mateusz@arch example ]$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/mateusz/go/bin"
GOCACHE="/home/mateusz/.cache/go-build"
GOENV="/home/mateusz/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/mateusz/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mateusz/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/mateusz/code/example/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1154144156=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```
func main() {
	enc := base32.HexEncoding.WithPadding(base32.NoPadding)

	data := []byte{0: 255, 15: 255}

	fmt.Println(enc.EncodedLen(len(data))) //26

	buf := [128]byte{}

	enc.Encode(buf[:], data)
	fmt.Printf("%v\n", string(buf[:]))  //VS0000000000000000000000VS000000
	fmt.Println(enc.EncodeToString(data)) //VS0000000000000000000000VS
}
```
https://go.dev/play/p/nv53zKwHz3E

### What did you expect to see?
	fmt.Printf("%v\n", string(buf[:]))   //VS0000000000000000000000VS
	fmt.Println(enc.EncodeToString(data)) //VS0000000000000000000000VS

### What did you see instead?
	fmt.Printf("%v\n", string(buf[:]))   //VS0000000000000000000000VS000000
	fmt.Println(enc.EncodeToString(data)) //VS0000000000000000000000VS

**Comment by bcmills** [comment]
The `Encode` method seems to be working as documented. See the example at https://pkg.go.dev/encoding/base32#example-Encoding.Encode.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and [proposals](https://go.dev/s/proposal-process) only.

For asking questions, see the resources listed at https://go.dev/wiki/Questions.

**Comment by mateusz834** [comment]
So then why the encoding/base64 does not append '0' characters at the end?
https://go.dev/play/p/gRnZ-1lEXgw

**Comment by mateusz834** [comment]
In some weird cases it could lead to security issues: https://go.dev/play/p/ZUzDf04bO1K

**Comment by ianlancetaylor** [comment]
For questions, please see https://go.dev/wiki/Questions.  Thanks.
