### ISSUE TITLE
go/doc/comment: support links in lists in comments 

### ISSUE THREAD

**Issue by golightlyb** [golang/go#53610]
The proposed (#51082) [new go doc comment additions](https://tip.golang.org/doc/comment) supports lists, links, and doc links.

I feel its implied by the proposal that lists, because they can contain multiple paragraphs, should be able to contain links and doclinks. However, the current implementation of go/doc/comment does not support this, and treats lists as paragraphs of plain text.

This is how it would look with a list containing a doc link:

    //  - Do this, or...
    //  - Use [encoding/json.Marshal]

With a list containing a link:

    //  - Do this, or...
    //  - See [RFC]
    //
    // [RFC]: https://datatracker.ietf.org/doc/html/rfc2616

With a list containing a link, in a weird embedded link format, that also works (but perhaps shouldn't?)

    //  - Do this, or...
    //  - See [RFC], or...
    //
    //    [RFC]: https://datatracker.ietf.org/doc/html/rfc2616
    //  - Something else

See pull request imminently

**Comment by ianlancetaylor** [comment]
CC @rsc
