### ISSUE TITLE
go vet: `uintptr` is a pointer type, so the fmt verb "%p" should apply without errors.

### ISSUE THREAD

**Issue by chewxy** [golang/go#53622]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

A minimal reproducable case:
```
func TestVerb(t *testing.T){
	p := uintptr(4) // chosen by fair roll of a die. Guaranteed to be random.
	t.Logf("%p", p)
}
```

### What did you expect to see?
No errors. 

### What did you see instead?
```
./machine_test.go:7:2: (*testing.common).Logf format %p has arg p of wrong type uintptr
```
This is caused by `go vet` (specifically it's due to the use of `golang.org/x/tools/go/analysis/passes/printf` - the [`matchArg`](https://github.com/golang/tools/blob/master/go/analysis/passes/printf/types.go#L59) function doesn't recognize `uintptr` as a pointer type)
 
Not sure where to file this as this involves the `go` command (i.e. `go test` and `go vet` causes this) but the root cause is in the tools library.

**Comment by cuonglm** [comment]
`uintptr` is a numeric type, not a pointer type.

**Comment by robpike** [comment]
% go doc builtin.uintptr
    package builtin // import "builtin"
    
    type uintptr uintptr
        uintptr is an integer type that is large enough to hold the bit pattern of
        any pointer.
