### ISSUE TITLE
cmd/go: `go build` fails to read vcs info from isolated git submodule

### ISSUE THREAD

**Issue by MichaelVoelkel** [golang/go#53640]
### What version of Go are you using (`go version`)?
1.18.3

### Does this issue reproduce with the latest release?
Yes, with latest 1.18 (that is, 1.18.3), which is not the latest Go release itself, though

### What operating system and processor architecture are you using (`go env`)?
It's a docker container but reproduces on Apple Silicon and on Debian 10 x86.

### What did you do?
I just tried building my image:
```
docker build --no-cache -f deploy/Dockerfile .
```
and got output:
```
 > [3/4] RUN go build .:
#7 0.265 error obtaining VCS status: exit status 128
#7 0.265 	Use -buildvcs=false to disable VCS stamping.
------
executor failed running [/bin/sh -c go build .]: exit code: 1
```

### What did you expect to see?
No error.

### What did you see instead?
Failure.

So, to make this reproducible, I created a nested git repository because the error does not occur if I remove the nested/.git file. Recursively cloning the repo, `cd`ing into nested and then run aforementioned build command reproduces it for me on two systems:

https://github.com/MichaelVoelkel/vcs-test

I mean, sure, `.git` links to a folder that does not exist and just not copying _everything_ into Docker would immediately help. But why does Go even care?

**Comment by MichaelVoelkel** [comment]
I mean, if you phrase the title like this...

It cannot read it from there because the submodule that is checked out has, instead of .git folder, a .git file. This file only has the content like:
```
gitdir=../modules/something
```
So, clearly it cannot read it.

So the better question is: Why is it needed that VCS is read? And if it's needed, then I am probably the wrongdoer myself for having the isolated submodule?

**Comment by seankhliao** [comment]
```
 > [4/6] RUN git status:
#8 0.832 fatal: not a git repository: /../.git/modules/nested
```

I would consider this a git issue (the way it handles git dirs in submodules).
Like #53532 we could return a better error (the git output), but ultimately it would still be up to the user to decide if they want to embed vcs info (provide a complete .git dir) or not (`-buildvcs=false` or remove the .git file/dir).

cc @bcmills @matloob

**Comment by seankhliao** [comment]
> Why is it needed that VCS is read?

I would refer you to the description of the build flag https://pkg.go.dev/cmd/go#:~:text=buildmode%27%20for%20more.-,%2Dbuildvcs,-Whether%20to%20stamp

**Comment by kkHAIKE** [comment]
we can ignore(goto omitVCS when cfg.BuildBuildvcs is auto) vcsCmd.Status err when .git is file(submodule)

https://github.com/golang/go/blob/9a2001a8cc75b1ceda17da828edcee93c9d9f42c/src/cmd/go/internal/load/pkg.go#L2479-L2486
