### ISSUE TITLE
x/build: remove openbsd-amd64-68 from default TryBot set

### ISSUE THREAD

**Issue by bcmills** [golang/go#53646]
The default TryBot set currently includes builders for [`openbsd-amd64-68`](https://cs.opensource.google/go/x/build/+/master:dashboard/builders.go;l=2062;drc=93f9179ef70d943cedff5e1d3b52066ecc2c3332) and [`openbsd-amd64-70`](https://cs.opensource.google/go/x/build/+/master:dashboard/builders.go;l=2084;drc=93f9179ef70d943cedff5e1d3b52066ecc2c3332).

However, the `-68` builder seems to be much less reliable: it has failed repeatedly with symptoms matching #34988, whereas the `-70` builder, to my knowledge, has not.

Given that the default TryBot set includes a more reliable OpenBSD builder already, I think we should demote the less-reliable one to a post-submit builder and SlowBot.

(CC @golang/openbsd @golang/release)

**Comment by heschi** [comment]
Agreed, I think this is leftover cleanup from when I upgraded to 7.0. Michael, you're on interrupts this week, can you take a look?

**Comment by mknyszek** [comment]
Confirmed fixed.
