### ISSUE TITLE
x/website: Bitly case study page returning 403 for images

### ISSUE THREAD

**Issue by hoomand** [golang/go#53657]
### What is the URL of the page with the issue?
 https://bitly.com/blog/why-we-write-everything-in-go/?utm_source=go-dev&utm_medium=referral&utm_campaign=go-dev&utm_content=case-study
 

This is a page that you are linking to from the [case studies](https://go.dev/solutions/#case-studies) page.
 
### What is your user agent?
 

 
 [Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
### Screenshot
 

 
 
![Snip20220702_9](https://user-images.githubusercontent.com/650589/176983494-c203723f-6512-4074-9182-aaec2f05b098.png)

 
### What did you do?
 

 
The images return a 403 error. I tested this on Firefox too.
I couldn't find a link on Bitly website to report an error.
They should either be contacted or this page gets removed from the case studies.
 
### What did you expect to see?
 
 Graphs/images
 
### What did you see instead?

403 error

**Comment by ZekeLu** [comment]
cc @modi98 who authored https://github.com/golang/website/commit/7b9aa998daa093e32ba52549924a0927f5879d3f

**Comment by modi98** [comment]
it depends if we're updating the case study link, we could reference this issue in the Change Request, cc: @jamalc

**Comment by dmitshur** [comment]
This seems to be resolved now:

<img width="641" alt="image" src="https://user-images.githubusercontent.com/1924134/192028154-d974575b-b133-4ff6-bd5e-ad229c1e433e.png">
