### ISSUE TITLE
go/types/testdata/fixedbugs: git rejects file with carriage returns

### ISSUE THREAD

**Issue by willfaught** [golang/go#53664]
### What version of Go are you using (`go version`)?

1.18.3

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

```
~/Developer/proj/internal/go/src main
❯ git add ./go/types/testdata/fixedbugs # copied from ~/Developer/go/src, the go repo (version go1.18.3)
fatal: CRLF would be replaced by LF in internal/go/src/go/types/testdata/fixedbugs/issue39754.go2

~/Developer/go/src tags/go1.18.3 24s
❯ xxd ./go/types/testdata/fixedbugs/issue39754.go2
00000000: 2f2f 2043 6f70 7972 6967 6874 2032 3032  // Copyright 202
00000010: 3020 5468 6520 476f 2041 7574 686f 7273  0 The Go Authors
00000020: 2e20 416c 6c20 7269 6768 7473 2072 6573  . All rights res
00000030: 6572 7665 642e 0d0a 2f2f 2055 7365 206f  erved...// Use o
```

You can see the CR before the LF in the hex view.

### What did you expect to see?

`git add` succeed.

### What did you see instead?

`git add` fail.

**Comment by ianlancetaylor** [comment]
I don't know enough about git to understand what is going on, but crlf is valid in a Go file.  I don't know why this test case is using crlf, but we shouldn't have to change the file to work around git.  Clearly git is able to handle crlf files, as evidenced by the fact that the file exists in Go's git repository.  So it seems to me that this must have something to do with some local git configuration on your system.

**Comment by willfaught** [comment]
Wow, fast response! :)

You're right, I just realized I have Git config that has CRLF policy:

```
[core]
autocrlf = input
safecrlf = true
```

Setting either of those to false makes it work.

The issue isn't about removing CRs from valid Go. I'd say it's about making the implementation compatible with typical Git config people use to keep line endings consistent across platforms. For instance, without these policies, if I had added a new line to this file on macOS, then committed it, the line endings would be inconsistent within the file, and it would probably appear malformed in Windows Notepad. If Go intends to support Windows, and accept contributions from Windows users, then it seems to me like a good idea to use one line ending everywhere.

**Comment by alexbrainman** [comment]
> For instance, without these policies, if I had added a new line to this file on macOS, then committed it, the line endings would be inconsistent within the file, and it would probably appear malformed in Windows Notepad.

Try making the change you are suggesting, and then see if running all.bash or all.bat succeed. I have a feeling there is a test that will break. And don't worry about breaking Windows Notepad - no one uses it anyway.

Alex

**Comment by ZekeLu** [comment]
In fact, we have a line ending policy:

https://github.com/golang/go/blob/e822b1e26e20ef1c76672c0b77b0fd8a97a1fe84/.gitattributes#L1-L16

And as stated in `.gitattributes`, **git-codereview gofmt** will cover it. But it seems that it does not cover go files in `testdata` directory.

cc @qmuntal: maybe you want to check your default line ending of your editor (because the commit 3e387528e54971d6009fe8833dcab6fc08737e04 uses `CRLF`).

**Comment by willfaught** [comment]
@alexbrainman The broader point was that it will appear malformed using the Windows line ending convention. I mentioned Notepad in particular for specificity, but I think the broader point stands.

**Comment by ianlancetaylor** [comment]
It's useful to have test cases that use crlf, to ensure that those kinds of files continue to work.  I don't personally care whether we change some of them, but we should not change all of them.

**Comment by ZekeLu** [comment]
That makes sense. I'm going to abandon the CL.

**Comment by willfaught** [comment]
It would at least be clearer why the file has CRLF if its name indicated it. I assumed it was a bug because there's nothing about the file that seems to be about CRs. Aside from test cases specifically checking that CR is accepted, everything else could just have LF.

**Comment by seankhliao** [comment]
Seems to be working as intended.
