### ISSUE TITLE
Calling errors.Unwrap on certain non-nil errors returns nil rather than the underlying error

### ISSUE THREAD

**Issue by ddemoss222** [golang/go#53668]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.18
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
The API I am writing processes errors prior to issuing an HTTP response. 
Some helper functions to assist with this behavior are given errors that may or may not be wrapped using the fmt.Errorf("%w", err) notation.
In a development environment, I propagate the fully wrapped errors to the client to expedite debugging, but in production the added context is undesirable, so the helper func calls Unwrap on errors prior to sending the response.

There was a scenario where an error was passed to this helper function that had never been wrapped. As the expected behavior from calling "Unwrap" is to simply return the underlying error, it was surprising to me that in this scenario calling unwrap turned a non-nil error into a nil, leading to a nil pointer dereference panic, as I then attempted to call Error() on a nil error.

### What did you expect to see?

```go
var MockErr = errors.New("This needs to unwrap")

func TestUnwrap(t *testing.T) {
  w := errors.Unwrap(fmt.Errorf("%w", MockErr))
  // succeeds
  assert.Equal(t, MockErr, w)
  e := errors.Unwrap(MockErr)
  // fails, e == nil
  assert.Equal(t, MockErr, e)
}
```

### What did you see instead?

Instead of unwrapping to the underlying error, it returned a nil since it wasn't wrapped. This created an unexpected nil pointer dereference panic. 

Finally, I assert that returning the underlying error from the second test case would be most in accordance to the Principle of Least Surprise.

Other mentions of this issue: https://github.com/golang/go/issues/38227

**Comment by seankhliao** [comment]
`errors.Unwrap` is documented to return `nil` if there is no `Unwrap` method defined on the error. Changing that would be considered a breaking change.

It sounds to me that you should create your own helper function with the semantics you want (`errors.Unwrap` is only 6 lines).

Closing for the same reason as #38227
