### ISSUE TITLE
runtime: plan9: exit status is not passed correctly to exits syscall

### ISSUE THREAD

**Issue by oridb** [golang/go#53669]
In commit  364ced62559. the definition of exit in the plan 9 go runtime was changed like so:

```
-               status = append(itoa(tmp[:len(tmp)-1], uint64(e)), 0)
+               sl := itoa(tmp[:len(tmp)-1], uint64(e))
+               // Don't append, rely on the existing data being zero.
+               status = tmp[:len(sl)+1]
```

However, itoa only puts the converted number "somewhere" in the buffer. Specifically, it
builds it from the end of the buffer towards the start -- meaning that the first byte of the buffer
is a 0 byte, and the resulting C string that's passed to exits is empty, leading to a falsely
successful exit.

### What version of Go are you using (`go version`)?

HEAD. It was broken in commit  364ced62559,

### What operating system and processor architecture are you using (`go env`)?

Plan 9

### What did you do?

```
% cat test.go
package main

import "os"

func main() {
	os.Exit(2)
}
cpu% go run test.go; echo $status
cpu%
```

### What did you expect to see?

An exit status of 2.

### What did you see instead?

A successful exit status.

**Comment by ianlancetaylor** [comment]
CC @dr2chase
