### ISSUE TITLE
affected/package: os/exec

### ISSUE THREAD

**Issue by fayfive** [golang/go#53678]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.15 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/alfred/.cache/go-build"
GOENV="/home/alfred/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/alfred/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/alfred/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build419012674=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I want to exec the command "mysqlbinlog".
```
exe1 := "mysqlbinlog"
args1 := []string{"-h" + config.GetAppYaml().Master.Ip,
				"-u" + config.GetAppYaml().Master.TableUser,
				"-p" + config.GetAppYaml().Master.TablePassword,
				"-j" + status.ReadMasterLogPos,
				"-t", "--read-from-remote-server",
				status.MasterLogFile}
log.Println(exe1, args1) //mysqlbinlog [-h192.168.13.18 -uroot -p1234 --start_position=160692445 --read-from-remote-server mysql-bin.000042]
cmd1 := exec.Command(exe1, args1...)

f, err := os.OpenFile(config.GetExecutePath()+"my.sql", os.O_CREATE|os.O_RDWR, 0777)
if err != nil {
return
}
defer f.Close()
cmd1.Stdout = f
cmd1.Stderr = os.Stderr
err = cmd1.Run()
if err != nil {
log.Println("error is :", err)
return
}
```
It doesn't work well and no error. The file "my.sql" is very small about 900 Bytes. But in fact that , It's about 100MB when I exec the command `mysqlbinlog -h192.168.13.18 -uroot -p1234 --start_position=160692445 --read-from-remote-server mysql-bin.000042` in the terminal.

**Comment by mengzhuo** [comment]
Which is using 100MB memory mysqlbinlog or this go program?
What do you expect from this issue?

**Comment by fayfive** [comment]
100MB is the file what I saved through mysqlbinlog.
I want to exec the command `mysqlbinlog` in golang.
I want to use mysqlbinglog to  save the binlog. But it can't do that.

**Comment by ZekeLu** [comment]
```diff
  args1 := []string{"-h" + config.GetAppYaml().Master.Ip,
  				"-u" + config.GetAppYaml().Master.TableUser,
  				"-p" + config.GetAppYaml().Master.TablePassword,
+ 				"-j" + status.ReadMasterLogPos,
+ 				"-t", "--read-from-remote-server",
  				status.MasterLogFile}
- log.Println(exe1, args1) //mysqlbinlog [-h192.168.13.18 -uroot -p1234 --start_position=160692445 --read-from-remote-server mysql-bin.000042]
```

It seems that you used different arguments in the go app. Have you try the exact same arguments in the terminal?

**Comment by ZekeLu** [comment]
> [--to-last-log](https://dev.mysql.com/doc/refman/5.7/en/mysqlbinlog.html#option_mysqlbinlog_to-last-log), -t
>
> Do not stop at the end of the requested binary log from a MySQL server, but rather continue printing until the end of the last binary log. If you send the output to the same MySQL server, this may lead to an endless loop. This option requires [--read-from-remote-server](https://dev.mysql.com/doc/refman/5.7/en/mysqlbinlog.html#option_mysqlbinlog_read-from-remote-server).

I think you should not specify `-t` in the argument list.

**Comment by mengzhuo** [comment]
Closed since it's not a Go issue.
