### ISSUE TITLE
json.NewDecoder(req.Body) is not working getting invalid character '\t' in string literal error.

### ISSUE THREAD

**Issue by sachusachin622** [golang/go#53679]
Hi ,
I am trying to json decode the http.request body, Getting invalid character '\t' in string literal error.
**golang-version:** go1.13.linux-amd64.tar.gz
here is my code:
ubuntu:~/practice$ cat http_test.go 
package main

import (
        "encoding/json"
        "log"
        "net/http"
        "fmt"
       )

type Request_data struct {
    APIVersion      string
    RequestCategory string
    Password      string 
  }

func test(response http.ResponseWriter, req *http.Request) {
         var recvData Request_data
        decoder := json.NewDecoder(req.Body)
        err := decoder.Decode(&recvData)
        if err != nil {
            fmt.Println("err is %v",err)
        }
        fmt.Println("recvData: %v",recvData)
        response.Header().Set("Content-Type", "application/json")
        response.WriteHeader(http.StatusOK)
        data, err := json.Marshal(recvData)
        response.Write(data)
        fmt.Println("!!!Response is Success!!!")
}

func main() {
        http.HandleFunc("/", test)
        log.Fatal(http.ListenAndServe(":8000", nil))
}
ubuntu:~/practice$ 

Here Password field contains "Horizontal Tab and space" in between the Password string.
Please help to fix this issue.

Thanks,
Sachin

**Comment by ZekeLu** [comment]
Please provide the raw request content sent to the HTTP server. It's very likely that the request is not a valid JSON.

**Comment by seankhliao** [comment]
Looks more likely to be bad data on your side, also 1.13 is no longer supported.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
