### ISSUE TITLE
cmd/go: '$/' is an invalid environment variable name on plan 9

### ISSUE THREAD

**Issue by oridb** [golang/go#53671]
When running the tests on plan 9, there are currently a number of failures when attempting to set
the environment, with the message:

```
can't open: '/env//' create without DMDIR
```

This is because src/cmd/go/script_test.go atempts to set '$/' to indicate the path separator.

### What version of Go are you using (`go version`)?

commit e822b1e26e20ef1c76672c0b77b0fd8a97a1fe84

### Does this issue reproduce with the latest release?

The issue was added with commit 742dcba7bb9

### What operating system and processor architecture are you using (`go env`)?

Plan 9 (9front, amd64)

<details><summary><code>go env</code> Output</summary><br><pre>
% go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/usr/orib/lib/cache/go-build'
GOENV='/usr/orib/lib/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='plan9'
GOINSECURE=''
GOMODCACHE=''
GONOPROXY=''
GONOSUMDB=''
GOOS='plan9'
GOPATH=''
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/orib/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLDIR='/usr/orib/go/pkg/tool/plan9_amd64'
GOVCS=''
GOVERSION='VERS'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='6c'
CXX='g++'
CGO_ENABLED='0'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-g -O2'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-g -O2'
CGO_FFLAGS='-g -O2'
CGO_LDFLAGS='-g -O2'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build388427748=/tmp/go-build -gno-record-gcc-switches'

</pre></details>

### What did you do?

./run.rc

### What did you expect to see?

More tests passing than I did

### What did you see instead?

script_test.go failing with

```
can't open: '/env//' create without DMDIR
```

**Comment by oridb** [comment]
Removing setting the environment variable fixes some of the script tests, but others fail with a missing path separator in paths. Currently, I'm having trouble finding where $/ is getting used to create the paths.

**Comment by ianlancetaylor** [comment]
CC @bcmills 

I see `$/` used, as `${/}`, in a number of tests in cmd/go/testdata/script.

Perhaps we should just omit `/` and `:` when setting the background process environment in `testScript.startBackground`.

**Comment by oridb** [comment]
Got it, I swapped the generated/golden output when I was reading it, and was looking for a place $/ was used in the go commands to generate the paths.

Need to run some tests, but patch on the way.

**Comment by oridb** [comment]
with this, after the latest run I'm down to just these failures:

```
go test proxy running at GOPROXY=http://127.0.0.1:42950/mod
--- FAIL: TestScript (0.04s)
    --- FAIL: TestScript/work_env (0.68s)
        script_test.go:272: 
            # (2022-07-03T21:39:54Z)
            > go env GOWORK
            [stdout]
            $WORK/gopath/src/go.work
            > stdout '^'$GOPATH'[\\/]src[\\/]go.work$'
            > go env
            [stdout]
            GO111MODULE=''
            GOARCH='amd64'
            GOBIN=''
            GOCACHE='/usr/orib/go/pkg/obj/go-build'
            GOENV='/no-home/lib/go/env'
            GOEXE=''
            GOEXPERIMENT=''
            GOFLAGS=''
            GOHOSTARCH='amd64'
            GOHOSTOS='plan9'
            GOINSECURE=''
            GOMODCACHE='$WORK/gopath/pkg/mod'
            GONOPROXY=''
            GONOSUMDB=''
            GOOS='plan9'
            GOPATH='$WORK/gopath'
            GOPRIVATE=''
            GOPROXY='http://127.0.0.1:42950/mod'
            GOROOT='/usr/orib/go'
            GOSUMDB='localhost.localdev/sumdb+00000c67+AcTrnkbUA+TU4heY3hkjiSES/DSQniBqIeQ/YppAUtK6'
            GOTMPDIR=''
            GOTOOLDIR='/usr/orib/go/pkg/tool/plan9_amd64'
            GOVCS='*:all'
            GOVERSION='VERS'
            GCCGO='gccgo'
            GOAMD64='v1'
            AR='ar'
            CC='6c'
            CXX='g++'
            CGO_ENABLED='0'
            GOMOD='/dev/null'
            GOWORK='$WORK/gopath/src/go.work'
            CGO_CFLAGS='-g -O2'
            CGO_CPPFLAGS=''
            CGO_CXXFLAGS='-g -O2'
            CGO_FFLAGS='-g -O2'
            CGO_LDFLAGS='-g -O2'
            PKG_CONFIG='pkg-config'
            GOGCCFLAGS='-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=$WORK/tmp/go-build3717227846=/tmp/go-build -gno-record-gcc-switches'
            > stdout '^(set )?GOWORK="?'$GOPATH'[\\/]src[\\/]go.work"?$'
            FAIL: testdata/script/work_env.txt:4: no match for `(?m)^(set )?GOWORK="?\$WORK/gopath[\\/]src[\\/]go.work"?$` found in stdout
            
    --- FAIL: TestScript/modfile_flag (30.64s)
        script_test.go:272: 
            # (2022-07-03T21:42:57Z)
            # Tests the behavior of the -modfile flag in commands that support it.
            # The go.mod file exists but should not be read or written.
            # Same with go.sum. (0.006s)
            # go mod init should create a new file, even though go.mod already exists. (0.108s)
            # 'go env GOMOD' should print the path to the real file.
            # 'go env' does not recognize the '-modfile' flag. (0.092s)
            # 'go list -m' should print the effective go.mod file as GoMod though. (0.098s)
            # go mod edit should operate on the alternate file (0.102s)
            # 'go list -m' should add sums to the alternate go.sum. (30.168s)
            > go list -m -mod=mod all
            [stderr]
            go: rsc.io/quote@v1.5.2: Get "http://127.0.0.1:42950/mod/rsc.io/quote/@v/v1.5.2.mod": dial tcp 127.0.0.1:42950: i/o timeout
            [exit status: 'go 576711: 1']
            FAIL: testdata/script/modfile_flag.txt:28: unexpected command failure
            
    --- FAIL: TestScript/mod_install_pkg_version (3.06s)
        script_test.go:272: 
            # (2022-07-03T21:44:10Z)
            # 'go install pkg@version' works outside a module. (1.426s)
            # 'go install pkg@version' reports an error if modules are disabled. (0.090s)
            # 'go install pkg@version' ignores go.mod in current directory. (1.360s)
            > cd m
            $WORK/gopath/src/m
            > cp go.mod go.mod.orig
            > ! go list -m all
            [stderr]
            go: example.com/cmd@v1.1.0-doesnotexist: reading http://127.0.0.1:42950/mod/example.com/cmd/@v/v1.1.0-doesnotexist.info: 404 Not Found
            	server response: 404 page not found
            go: example.com/cmd@v1.1.0-doesnotexist: missing go.sum entry; to add it:
            	go mod download example.com/cmd
            [exit status: 'go 582499: 1']
            > stderr '^go: example.com/cmd@v1.1.0-doesnotexist: missing go.sum entry; to add it:\n\tgo mod download example.com/cmd$'
            > go install example.com/cmd/a@latest
            > cmp go.mod go.mod.orig
            > exists $GOPATH/bin/a$GOEXE
            > go version -m $GOPATH/bin/a$GOEXE
            [stderr]
            $WORK/gopath/bin/a: could not read Go build info from $WORK/gopath/bin/a: unrecognized file format
            > stdout '^\tmod\texample.com/cmd\tv1.0.0\t' # "latest", not from go.mod
            FAIL: testdata/script/mod_install_pkg_version.txt:24: no match for `(?m)^\tmod\texample.com/cmd\tv1.0.0\t` found in stdout
            
FAIL
FAIL	cmd/go	409.564s
```

**Comment by mvdan** [comment]
For some context, the testscript fork of `script_test.go` reached a similar conclusion: https://github.com/rogpeppe/go-internal/pull/115

With the caveat that we want to keep `${/}` working where possible, for the sake of backwards compatibility.

**Comment by bcmills** [comment]
@oridb, I'm trying to better understand the nature of the problem. `cmd/go` uses `os/exec` under the hood, so if these environment variables are not valid on Plan 9, does that imply that some behavior in `exec.Cmd` also needs to change, or at least have its documentation clarified?

For example, should `(*exec.Cmd).Start` fail explicitly on Plan 9 if the `Env` slice contains an entry beginning with `/`? (Or should it ignore such entries entirely?)
