### ISSUE TITLE
cmd/go: `go version` says file not executable on cross-compiled binary

### ISSUE THREAD

**Issue by inliquid** [golang/go#53681]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\***\AppData\Local\go-build
set GOENV=C:\Users\***\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\***\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\***\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\***\AppData\Local\Temp\go-build934652975=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
On a Windows machine I compiled a Linux binary with `GOOS=linux go build`, then I tried `go version <binary>` and `go version -m <binary>`. 
In both cases the result was:
```
<binary>: not executable file
```
When I run `file <binary>` I see the following:
```
<binary>: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=***, not stripped
```

### What did you expect to see?
Build info for that binary.

### What did you see instead?
Above message.

**Comment by seankhliao** [comment]
Is it for any build executable? can you share a built artifact?

**Comment by inliquid** [comment]
It's for any executable.

**Comment by qmuntal** [comment]
`go version` on windows just checks the target file extension, if it ends with `.exe` it's an executable, else it's not:

https://github.com/golang/go/blob/c1110910713766eb06d75ed48db3722d318a845e/src/cmd/go/internal/version/version.go#L112-L118

Looking at the code, it works as expected, although I agree it could be smarter. Somehow related to #48187.

**Comment by inliquid** [comment]
Obviously when you compile for other systems extension could be missing. I think this check is unnecessary. Moreover checking executable bit on Unix (if I understand logic correctly) also makes no sense. What if I just unzipped this from the archive and want to check that info. Why should I make it runnable just to be able to analyze contents? This misleads: "runnable" or "allowed to run" != "executable".

**Comment by qmuntal** [comment]
I've updated CL 391855 to remove the is-executable check, so all files go through `buildinfo.ReadFile` regardless of the file extension and the host OS.

**Comment by quantonganh** [comment]
391855 had been merged, I think this can be closed.
