### ISSUE TITLE
codereview: minor fixes needed in /api JSON parsing

### ISSUE THREAD

**Issue by rsc** [golang/go#5369]
<pre>---------- Forwarded message ----------
From: Marc-Antoine Ruel &lt;maruel@chromium.org&gt;
Date: Sat, Apr 6, 2013 at 8:06 AM
Subject: Changes are required to /api and its clients
To: codereview-discuss &lt;codereview-discuss@googlegroups.com&gt;
Cc: Dirk Pranke &lt;dpranke@chromium.org&gt;, Robbie Iannucci
&lt;iannucci@chromium.org&gt;, rmistry &lt;rmistry@chromium.org&gt;, Russ Cox
&lt;rsc@google.com&gt;

Hi

- The dev_appserver now allocates automatic ids using the 'scattered' id allocation
policy by default. For more information, please see &quot;Specifying the Automatic ID
Allocation Policy&quot;:
<a href="https://developers.google.com/appengine/docs/python/tools/devserver#Using_the_Datastore">https://developers.google.com/appengine/docs/python/tools/devserver#Using_the_Datastore</a>
- Globally consistent indexes in the experimental Search API are now deprecated and will
be removed in the next release.
Ref: <a href="https://code.google.com/p/googleappengine/wiki/SdkReleaseNotes">https://code.google.com/p/googleappengine/wiki/SdkReleaseNotes</a>

The thing that needs to be fixed is that the json api needs to use strings for key ids
instead of json numbers because the ids were never guaranteed to fit within 53 bits.

This impacts /api client scripts so the switch over requires all scripts that are using
this API to support both json number or string in preparation.

The actual changes, using 8249043 as an example are:
<a href="https://codereview.appspot.com/api/8249043/">https://codereview.appspot.com/api/8249043/</a>
&quot;patchsets&quot; list will be strings.
&quot;issue&quot; will be a string.

<a href="https://codereview.appspot.com/api/8249043/5001">https://codereview.appspot.com/api/8249043/5001</a>
&quot;issue&quot; will be a string.
&quot;patchset&quot; will be a string.
For each item in &quot;files&quot;, &quot;id&quot; will be a string.

I haven't coded the change yet, this email is an advanced warning. The only thing I know
for sure is that it will break the Chromium Commit Queue.

M-A</pre>

**Comment by cmarcelo** [comment]
@rsc This seems to refer to the system before Gerrit. Now that Go moved, should this be closed?

**Comment by rsc** [comment]
Indeed: we no longer codereview.py nor codereview.appspot.com. Best kind of bug fix. Thanks.
