### ISSUE TITLE
x/pkgsite: BSD-3-Clause-LBNL

### ISSUE THREAD

**Issue by safaci2000** [golang/go#53690]
### What is the URL of the page with the issue?
 
 https://github.com/esnet/gdg
 
### What is your user agent?
 

 
 [Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
### Screenshot
 

 
 
![Screen Shot 2022-07-05 at 11 11 38 AM](https://user-images.githubusercontent.com/62894/177360427-de2cff8d-da00-4263-871c-383791bc7f68.png)

 
### What did you do?
 

 
 Navigated to: https://pkg.go.dev/github.com/esnet/gdg and got the error
 
### What did you expect to see?

A rendering of the package documentation.  

I believe the license should be compatible with Go's OSS mentality.

Please find the License here, which should be compatible with a BSD License: https://github.com/esnet/gdg/blob/master/LICENSE

This might be helpful as well: https://spdx.org/licenses/BSD-3-Clause-LBNL.html

 
### What did you see instead?

The screenshot uploaded above.

**Comment by seankhliao** [comment]
cc @jba 

It is in https://opensource.org/licenses/alphabetical
