### ISSUE TITLE
crypto/x509: ParseRevocationList does not populate Number and AuthorityKeyId fields

### ISSUE THREAD

**Issue by aarongable** [golang/go#53726]
### What version of Go are you using (`go version`)?

go1.19rc1

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Use `x509.ParseRevocationList()` to parse a CRL which contains the crlNumber and authorityKeyIdentifer extensions (such as one produced using `x509.CreateRevocationList()`).

See https://go.dev/play/p/6gSi8pmdzBd?v=gotip for a demonstration.

### What did you expect to see?

The `RevocationList.Number` and `RevocationList.AuthorityKeyId` fields should be populated from the values in their corresponding extensions.

### What did you see instead?

The `.Number` and `.AuthorityKeyId` fields retain their zero-values.

**Comment by FiloSottile** [comment]
@rolandshoemaker this might be worth a freeze exception since it's a new API.

**Comment by rolandshoemaker** [comment]
Yup agreed, cc @golang/release this adds expected functionality in a new API that was missing and the patch is minimal.

**Comment by dmitshur** [comment]
Note that fixing a bug or problem discovered in a new API thanks to pre-release testing is generally in scope of the freeze (within [balance](https://go.dev/s/release#may-1--november-1-release-freeze-begins)), so a freeze exception might not be needed if you think this fix is okay to accept at this stage.

**Comment by heschi** [comment]
Marking as tentative release-blocker since it's a change to a new API.

**Comment by dmitshur** [comment]
I think we should aim to make it clear whose input an issue in a NeedsDecision state is waiting on.

I think at this point this doesn't warrant a freeze exception (it's within scope) and so the crypto/x509 owners should (i.e., we should remove "[freeze exception]" suffix). Thoughts?

**Comment by heschi** [comment]
Works for me; done.
