### ISSUE TITLE
x/website: there may be a defination mistake at https://go.dev/ref/spec#StructType

### ISSUE THREAD

**Issue by fumeboy** [golang/go#53732]
### What is the URL of the page with the issue?
 
https://go.dev/ref/spec#StructType
 
### What is your user agent?
 

 
 [Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36]
 
### Screenshot
 

 
 
<img width="664" alt="image" src="https://user-images.githubusercontent.com/30453942/177760228-9973f69a-e445-4105-b45a-e7810018b6b1.png">

<img width="554" alt="image" src="https://user-images.githubusercontent.com/30453942/177760332-a5f13cce-a622-48d3-96b4-67b445b58869.png">
 
 
### What did you expect to see?
 
at screenshot1, you could see the defination of `EmbeddedField` is `[ "*" ] TypeName `, but at screenshot2, the  EmbeddedField with `[typeArgs]` is OK. I think that should be fix to `EmbeddedField = [ "*" ] TypeName [ typeArgs ]`

**Comment by ianlancetaylor** [comment]
Thanks.  Dup of #53240, which is already fixed on tip.
