### ISSUE TITLE
x/tools/gopls/internal/regtest/inlayHints: sandbox cleanup failure with `directory not empty`

### ISSUE THREAD

**Issue by bcmills** [golang/go#53735]
```
PASS
closing test runner: errors closing the test runner:
	error(s) cleaning sandbox: cleaning modcache: <nil>; removing files: unlinkat /data/golang/workdir/tmp/gopls-regtest-1818400705/TestEnablingInlayHints/enable_parameter_names/experimental: directory not empty
FAIL	golang.org/x/tools/gopls/internal/regtest/inlayHints	1.228s
```

Typically a `directory not empty` error in test cleanup indicates a race in the code under test: it is likely that some operation (in this case perhaps a `cmd/go` operation?) was left running after the test function completed.

This test was added in [CL 411911](https://go.dev/cl/411911) (attn @suzmue @findleyr @jamalc).

Compare #50707.

**Comment by bcmills** [comment]
> A better solution is to retry cleanup, as is done for other tests that invoke the go command.

I'm confused — if the problem is that a `go` invocation is orphaned in flight, wouldn't that invocation still race with the retry? 🤔

It seems to me that we should figure out how the command is being orphaned and terminate it properly.

**Comment by bcmills** [comment]
(Compare https://pkg.go.dev/golang.org/x/tools/internal/stack/stacktest#NoLeak.)

**Comment by findleyr** [comment]
Yes, you're right. Upon investigation, it's not enough even to guarantee that cleanup succeeds: I have reproduced cases where even after shutdown succeeds, a go command is executed and recreates the GOPATH directory!

**Comment by findleyr** [comment]
Hmm. Well Friday of a quiet week seems like a good day to (try to) fix gopls's concurrency model!
