### ISSUE TITLE
embed, cmd/go:  embedded files add support for fs.Open

### ISSUE THREAD

**Issue by hktalent** [golang/go#53742]
embed, cmd/go:  embedded files add support for fs.Open
That is to say, once I embed a directory, reading and writing to this directory can be operated using the regular file api
Of course, you can set a policy when embedding, for example
Use local files first, then embedded files

**Comment by mengzhuo** [comment]
If you wish to change API please take a look at [proposal wiki](https://github.com/golang/proposal#readme) and reform your current issue, thanks.
