### ISSUE TITLE
x/website: the EBNF def of `FunctionType`.`Result` is wrong

### ISSUE THREAD

**Issue by fumeboy** [golang/go#53746]
### What is the URL of the page with the issue?
 
 https://go.dev/ref/spec#Function_types

### the definition in doc is
 
FunctionType   = "func" [Signature](https://go.dev/ref/spec#Signature) .
Signature      = [Parameters](https://go.dev/ref/spec#Parameters) [ [Result](https://go.dev/ref/spec#Result) ] .
Result         = [Parameters](https://go.dev/ref/spec#Parameters) | [Type](https://go.dev/ref/spec#Type) .
Parameters     = "(" [ [ParameterList](https://go.dev/ref/spec#ParameterList) [ "," ] ] ")" .
ParameterList  = [ParameterDecl](https://go.dev/ref/spec#ParameterDecl) { "," [ParameterDecl](https://go.dev/ref/spec#ParameterDecl) } .
ParameterDecl  = [ [IdentifierList](https://go.dev/ref/spec#IdentifierList) ] [ "..." ] [Type](https://go.dev/ref/spec#Type) .
 
### the mistack is

the `Result` shouldnt be produce by `= Parameters`. the `Parameters` support `(... T)` but you couldnt write func signature like `func () (...T)`

**Comment by fumeboy** [comment]
<img width="973" alt="image" src="https://user-images.githubusercontent.com/30453942/177955852-738f225a-260f-4440-b447-b0e2157d7fd1.png">

and the complier tell me `...T` should be place as final param, not tell me `...T` shouldnt be place at `Result`

**Comment by heschi** [comment]
cc @ianlancetaylor @griesemer

**Comment by ianlancetaylor** [comment]
There are many cases where the spec's EBNF syntax accepts code that the text then reports as invalid.
