### ISSUE TITLE
spec: doesn't describe syntax clearly about where to use `whitespace` and `newline`

### ISSUE THREAD

**Issue by fumeboy** [golang/go#53744]
### What is the URL of the page with the issue?
 
 https://go.dev/ref/spec#Notation
 
 
### Screenshot
 

* screenshot1
<img width="844" alt="image" src="https://user-images.githubusercontent.com/30453942/177938825-16341713-a08b-4163-ac06-a779731c2fdf.png">

* screenshot2

<img width="816" alt="image" src="https://user-images.githubusercontent.com/30453942/177939350-a79dc739-761c-48f3-b70a-7dd591687b38.png">
 
### What did you see instead?

at screenshot1, you could see the  EBNF definition `Type = ... | "(" Type ")" .` which means the Type expr could be wrapped by `( )`, but the EBNF definition doesnt point out how to parse the BLANK part between the `"("` and `Type` and  the BLANK part between`Type` and `")"`. 

is all BLANK part could contain newline(`\n`) ? the screenshot2 tell me not. in fact, the first BLANK part could have a newline, but second couldnt. 

there are some code snippets i wrote to confirm where could have a newline:

```go
// the expr is RIGHT
type A [T any, T2 any] (
struct{ F string })
```

```go
// the expr is WRONG
type A [T any, T2 any] (
struct{ F string }
)
```

```go
// the expr is WRONG
type A
[T any, T2 any] (
struct{ F string })
```

```go
// the expr is RIGHT
type
A[T any, T2 any] (struct{ F string })
```

```go
// the expr is RIGHT
import
f "fmt"
```

```go
// the expr is WRONG
import f 
"fmt"
```

**Comment by heschi** [comment]
cc @ianlancetaylor @griesemer

**Comment by ianlancetaylor** [comment]
In these reports, please paste plain text as plain text, such as text from the spec.  Please do not use screenshots.  Screenshots are much harder to read.  Thanks.

**Comment by ianlancetaylor** [comment]
I think your questions are answered by https://go.dev/ref/spec#Semicolons, which explains when a semicolon is automatically inserted.  See also https://go.dev/doc/faq#semicolons.
