### ISSUE TITLE
x/pkgsite: incorrect rendering of old doc comments

### ISSUE THREAD

**Issue by DevDorrejo** [golang/go#53759]
### What is the URL of the page with the issue?
 https://pkg.go.dev/fmt
 
 
### What is your user agent?
 

 [Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
 
### Screenshot
 

 
![image](https://user-images.githubusercontent.com/7697566/178058497-0b4cce63-20e0-4797-80cd-313224ec49c4.png)

 
 
### What did you do?
 The information in the website is incomplete in the other flags section compared to: https://golang.google.cn/pkg/fmt/

 
 
 
### What did you expect to see?
 Other flags:

```
+	always print a sign for numeric values;
	guarantee ASCII-only output for %q (%+q)
-	pad with spaces on the right rather than the left (left-justify the field)
#	alternate format: add leading 0b for binary (%#b), 0 for octal (%#o),
	0x or 0X for hex (%#x or %#X); suppress 0x for %p (%#p);
	for %q, print a raw (backquoted) string if strconv.CanBackquote
	returns true;
	always print a decimal point for %e, %E, %f, %F, %g and %G;
	do not remove trailing zeros for %g and %G;
	write e.g. U+0078 'x' if the character is printable for %U (%#U).
' '	(space) leave a space for elided sign in numbers (% d);
	put spaces between bytes printing strings or slices in hex (% x, % X)
0	pad with leading zeros rather than spaces;
	for numbers, this moves the padding after the sign
```
 
 
### What did you see instead?

Other flags:

- always print a sign for numeric values; guarantee ASCII-only output for %q (%+q)

- pad with spaces on the right rather than the left (left-justify the field) # alternate format: add leading 0b for binary (%#b), 0 for octal (%#o), 0x or 0X for hex (%#x or %#X); suppress 0x for %p (%#p); for %q, print a raw (backquoted) string if strconv.CanBackquote returns true; always print a decimal point for %e, %E, %f, %F, %g and %G; do not remove trailing zeros for %g and %G; write e.g. U+0078 'x' if the character is printable for %U (%#U). ' ' (space) leave a space for elided sign in numbers (% d); put spaces between bytes printing strings or slices in hex (% x, % X) 0 pad with leading zeros rather than spaces; for numbers, this moves the padding after the sign

**Comment by seankhliao** [comment]
The 1.19 docs render correctly: https://pkg.go.dev/fmt@go1.19beta1

Looks like a poor interaction with the old format

**Comment by ianlancetaylor** [comment]
Pretty sure this is fixed on tip, though, so it's a temporary issue.

**Comment by hyangah** [comment]
This is an unfortunate corner case. We don't have a plan to invent a workaround, so closing.
All pkg docs for go1.19 and newer were updated to work with the new styling syntax.
