### ISSUE TITLE
cmd/go: try both hg and git if bitbucket API returns 403 forbidden

### ISSUE THREAD

**Issue by gopherbot** [golang/go#5375]
by **shminoach**:

<pre>Attempting to 'go get' a package from a private bitbucket repository fails:

package bitbucket.org/foo/bar: <a href="https://api.bitbucket.org/1.0/repositories/foo/bar">https://api.bitbucket.org/1.0/repositories/foo/bar</a>: 403
FORBIDDEN

This has been reported on golang-nuts a few times:
<a href="https://groups.google.com/forum/#">https://groups.google.com/forum/#</a>!topic/golang-nuts/1CBFuTZC4zU
<a href="https://groups.google.com/forum/#">https://groups.google.com/forum/#</a>!topic/golang-nuts/cnhwNeR_fDE
<a href="https://groups.google.com/forum/#">https://groups.google.com/forum/#</a>!topic/golang-nuts/li8J9a-Tbz0

It appears that the actual failure is during an API call that attempts to determine
whether the repo is using hg or git. I'm guessing it would be possible to work around
this by catching the 403 status code and trying hg and git each in turn.</pre>

**Comment by akaspin** [comment]
Any news? Six months!

**Comment by bradfitz** [comment]
@akaspin, nobody is working on this. And it's not scheduled for any release.

If this is affecting you, you're welcome to work on a fix.

**Comment by MyChaOS87** [comment]
any chance this gets integrated in a minor version update for at least Go1.4 as this is clearly a bug and completely preventing go get from working when using bitbucket private repositories.

**Comment by bradfitz** [comment]
Sorry, this is almost certainly below our very high bar for what goes into point releases. It's very likely the case that there will be no Go 1.4.x releases at all, with Go 1.5 right around the corner.
