### ISSUE TITLE
sync.Once hangs on second .Do call till first .Do exits

### ISSUE THREAD

**Issue by MasterDimmy** [golang/go#53758]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.8.3
</pre>

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?
ALL, windows, linux.

### What did you do?

https://go.dev/play/p/prI8PqfND1k

```
var once sync.Once

	myfunc := func() {
		for {
			time.Sleep(time.Second)
		}
	}

	go once.Do(myfunc)

	time.Sleep(time.Second)
	once.Do(myfunc)

	fmt.Println("intended to be seen")
```

### What did you expect to see?

"intended to be seen"

### What did you see instead?

Nothing. Program hangs.

First once.Do called myfunc .
Second once.Do MUST NOT wait till first ends, since it is garanteed to be runned, but it locks program on inner mutex.lock.

sync.Once.Do garantees to be f() called only one time, and since it called the first time, it should not wait till f() ends, it should forbid second call and that it is it's task. So the fix is:
```
func (o *Once) doSlow(f func()) {
	o.m.Lock()
	if o.done == 0 {
		atomic.StoreUint32(&o.done, 1)
		o.m.Unlock()
		f()
		return
	}
		o.m.Unlock()
}

```

Also, __**second issue is**__ there is no way to detect such hangs during runtime via pprof. We only see huge amount of goroutings count, hanging on sync.(*Once).doSlow and no position or function, called it.

**Comment by seankhliao** [comment]
> Because no call to Do returns until the one call to f returns

This is working as designed.
