### ISSUE TITLE
cmd/go: mod tidy considers directory starting with _

### ISSUE THREAD

**Issue by tsdtsdtsd** [golang/go#53765]
### What version of Go are you using (`go version`)?

Tested with:  
- go1.17.6 linux/amd64
- go1.18.3 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tsd/.cache/go-build"
GOENV="/home/tsd/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/tsd/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tsd/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build572917264=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```sh
pwd
# /tmp/go-test

go mod init example.com/user/go-test
# go: creating new go.mod: module example.com/user/go-test

mkdir _data
sudo chown root:tsd _data
sudo chmod 700 _data
go mod tidy
# pattern all: open /tmp/go-test/_data: permission denied
```

### What did you expect to see?
Successful execution of `go mod tidy`

While it's correct that permission denying rules are a fact in this situation, the go tool should still ignore/skip this folder.  
The [Go Modules Reference](https://go.dev/ref/mod#go-mod-tidy) states:
> Note that go mod tidy will not consider packages in the main module in directories named testdata or with names that start with . or _ unless those packages are explicitly imported by other packages.

### What did you see instead?
The tool exits with `pattern all: open /tmp/go-test/_data: permission denied` without changing go.mod/go.sum

**Comment by bcmills** [comment]
Neat find! I think this is closely related to [CL 416179](https://go.dev/cl/416179).

**Comment by bcmills** [comment]
Indeed, looks like that change will fix this issue. Thanks for reporting!
