### ISSUE TITLE
affected/package: sync

### ISSUE THREAD

**Issue by LeslieRan** [golang/go#53769]
### What version of Go are you using (`go version`)?

<pre>
Go1.17

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/admin/Library/Caches/go-build"
GOENV="/Users/admin/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/admin/go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/admin/go"
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/Cellar/go/1.17.8/libexec"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.8/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.8"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jy/nw8ct9y52lzd00_fchgbgbfh0000gn/T/go-build877044505=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
grpc 1.45.0 was used.

### What did you expect to see?

No panic

### What did you see instead?

A panic occurred:

```
fatal error: sync: inconsistent mutex state

goroutine 4312 [running]:
runtime.throw({0x310db78, 0x11270fc0952719})
	/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc00afcfba8 sp=0xc00afcfb78 pc=0x436ef1
sync.throw({0x310db78, 0x164d000001c0})
	/usr/local/go/src/runtime/panic.go:1184 +0x1e fp=0xc00afcfbc8 sp=0xc00afcfba8 pc=0x46621e
sync.(*Mutex).lockSlow(0x539af80)
	/usr/local/go/src/sync/mutex.go:125 +0xe5 fp=0xc00afcfc18 sp=0xc00afcfbc8 pc=0x475845
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
sync.(*Pool).pinSlow(0xc00b69bb30)
	/usr/local/go/src/sync/pool.go:213 +0x7f fp=0xc00afcfcb0 sp=0xc00afcfc18 pc=0x47621f
sync.(*Pool).pin(0xc00b69bb30)
	/usr/local/go/src/sync/pool.go:206 +0x4e fp=0xc00afcfcc8 sp=0xc00afcfcb0 pc=0x47616e
sync.(*Pool).Get(0xc00b69bb30)
	/usr/local/go/src/sync/pool.go:128 +0x25 fp=0xc00afcfd00 sp=0xc00afcfcc8 pc=0x475ea5
google.golang.org/grpc/internal/transport.(*bufferPool).get(...)
	/go/pkg/mod/google.golang.org/grpc@v1.45.0/internal/transport/transport.go:62
google.golang.org/grpc/internal/transport.(*http2Client).handleData(0xc00b6f2000, 0xc00b69ba70)
	/go/pkg/mod/google.golang.org/grpc@v1.45.0/internal/transport/http2_client.go:1077 +0x2fc fp=0xc00afcfdc8 sp=0xc00afcfd00 pc=0x82115c
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc00b6f2000)
	/go/pkg/mod/google.golang.org/grpc@v1.45.0/internal/transport/http2_client.go:1534 +0x91c fp=0xc00afcffc8 sp=0xc00afcfdc8 pc=0x82515c
google.golang.org/grpc/internal/transport.newHTTP2Client·dwrap·7()
	/go/pkg/mod/google.golang.org/grpc@v1.45.0/internal/transport/http2_client.go:364 +0x26 fp=0xc00afcffe0 sp=0xc00afcffc8 pc=0x81b0e6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00afcffe8 sp=0xc00afcffe0 pc=0x46b6e1
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/go/pkg/mod/google.golang.org/grpc@v1.45.0/internal/transport/http2_client.go:364 +0x192f
```

**Comment by seankhliao** [comment]
Without a way to reproduce the issue, this issue is inactionable.
Also, please try to run it under the race detector.

**Comment by LeslieRan** [comment]
OK, thank you !

**Comment by mvdan** [comment]
Closing for now. Also see https://golang.org/wiki/Questions.
