### ISSUE TITLE
cmd/compile: excessive instrumentation for libFuzzer

### ISSUE THREAD

**Issue by randall77** [golang/go#53760]
```
func f() {
}
```
When compiled with
```
go tool compile -d=libfuzzer -S f.go
```
We get a call to `runtime.libfuzzerTraceConstCmp1`, which seems unnecessary.

This happens because we add (in the order pass):
```
if counter == 255 {
    counter = 1
} else {
    counter += 1
}
```
But then we add instrumentation to all integer comparisons (in the walk pass):
```
runtime.libfuzzerTraceConstCmp1(counter, 255)
```
I don't think we need to rewrite the internal libfuzzer counter overflow check to use the runtime comparison function. Only user comparisons should be so treated. I guess it technically doesn't hurt, but it will be slow.

@kyakdan

**Comment by mdempsky** [comment]
Would it be more efficient to emit something like:

```
tmp := int(counter) + 1
counter = uint8(counter + counter>>8)
```

so the counter increment is branchless?
