### ISSUE TITLE
affected/package: documentation

### ISSUE THREAD

**Issue by mneverov** [golang/go#53771]
Please remove `Don't be clever` advice from the [memory model](https://go.dev/ref/mem).

The statement is annoying. I think there is no other language that has such advice in their specification.
Does this advice apply to go core team too?

**Comment by mneverov** [comment]
@rsc let's plan it, reopen the issue and fix the docs

**Comment by ianlancetaylor** [comment]
We may disagree on what the memory model document says.  When I look at it, the memory model does not tell people not to read the documentation.  It tells people to not write programs to rely on the details of the memory model.  We're not discouraging people from reading and understanding it.

Thanks for pointing out that #5045 was still open.  It was fixed back in January and when the 1.19 release comes out, fairly soon, that fix will be visible on at https://go.dev/ref/mem.  I closed #5045.
