### ISSUE TITLE
x/crypto: x509: invalid certificate policies

### ISSUE THREAD

**Issue by akshaykanawat** [golang/go#53773]
<pre>
certBlock, _ := pem.Decode([]byte(publicKey))
certificate, err = x509.ParseCertificate(certBlock.Bytes)
if err != nil {
    fmt.Println("Unable to parse certificate ", err)
    return
}

I am getting below error while trying to Parse a pem file
"x509: invalid certificate policies"

I am able to Parse the same certificate in Python using OpenSSL package.
</pre>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.17.10 darwin/arm64

</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/xyz/Library/Caches/go-build"
GOENV="/Users/xyz/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xyz/Go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xyz/Go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go@1.17/1.17.10/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go@1.17/1.17.10/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.10"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xyz/bitbucket/panverification-nsdl/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2m/hnqlmbbn65304zdfqp3gvrt80000gp/T/go-build1656833850=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you expect to see?
I am expecting successful parsing of certificate

### What did you see instead?
Getting error: x509: invalid certificate policies

**Comment by seankhliao** [comment]
Without a reproducer (certificate that triggers the problem), this issue is inactionable.
