### ISSUE TITLE
affected/package: golang.org/dl failed to download 1.19rc1@latest

### ISSUE THREAD

**Issue by cnmade** [golang/go#53774]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.18.3
</pre>

### Does this issue reproduce with the latest release?
I am trying to download 1.19rc1

```bash
 go install golang.org/dl/1.19rc1@latest
go: golang.org/dl/1.19rc1@latest: module golang.org/dl@latest found (v0.0.0-20220706180819-0ef8f243a9a9), but does not contain package golang.org/dl/1.19rc1
```

### What operating system and processor architecture are you using (`go env`)?
```bash
```
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nomore/Library/Caches/go-build"
GOENV="/Users/nomore/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/nomore/go/pkg/mod"
GONOPROXY="*.dz11.com,code.aliyun.com,gitee.com,*.coldlake.cn"
GONOSUMDB="*"
GOOS="darwin"
GOPATH="/Users/nomore/go"
GOPRIVATE="*.dz11.com,code.aliyun.com,gitee.com,*.coldlake.cn"
GOPROXY="https://goproxy.cn/"
GOROOT="/usr/local/Cellar/go/1.18.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.18.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s8/w2xf8qxj6v712bq3_w_p7clw0000gp/T/go-build3115741191=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```bash
 go install golang.org/dl/1.19rc1@latest
go: golang.org/dl/1.19rc1@latest: module golang.org/dl@latest found (v0.0.0-20220706180819-0ef8f243a9a9), but does not contain package golang.org/dl/1.19rc1
```

### What did you expect to see?

download go1.19rc1 without any problem

### What did you see instead?
not contain package golang.org/dl/1.19rc1

**Comment by cnmade** [comment]
I followed by the install instruction.

![image](https://user-images.githubusercontent.com/278153/178166882-3708ceec-e201-49cd-bbc1-1bc3edb2de1e.png)

**Comment by seankhliao** [comment]
you have a typo

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
