### ISSUE TITLE
generics: cannot embed type parameter

### ISSUE THREAD

**Issue by leaxoy** [golang/go#53779]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.18
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?
Type parameter can refer another type parameter. In below case, I create a function that return a getter and a setter interact with state. In setter, I want a T value or a function which receive the old value then return a new value, I define a new type parameter `S` with either T or func(T)T, but it says `cannot embed type parameter`.

### What did you see instead?
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/8556349/178208251-74f1807a-544d-4080-86e3-8f95f91dd471.png">

**Comment by seankhliao** [comment]
you have a typo
also please don't use screenshots, they are difficult to read

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by leaxoy** [comment]
Why this is closed and marked not planned, this is a real use case.

**Comment by ianlancetaylor** [comment]
On tip, which will become 1.19, this prints

```
foo.go:3:29: term cannot be a type parameter
```

This is a documented restriction.  See the "General Interfaces" section of https://go.dev/ref/spec#Interface_types, which says "In a union, a term cannot be a type parameter...."

This restriction is imposed because it is difficult to understand how to build the type set of such a construct.
