### ISSUE TITLE
cmd/trace: TestAnalyzeAnnotationTaskTree failures since 2022-07-08

### ISSUE THREAD

**Issue by bcmills** [golang/go#53784]
`greplogs -l -e 'FAIL: TestAnalyzeAnnotationTaskTree'`
[2022-07-11T08:23:57-59ab6f3/linux-amd64-nocgo](https://build.golang.org/log/d79cbc8ef1190b25176dea1dfe9ad97b61f2db6f)
[2022-07-08T18:51:33-5c1a13e/linux-loong64-3a5000](https://build.golang.org/log/c75a4b08644edf9c51e174dca3bca6812f1f6465)
[2022-07-08T17:00:50-180bcad/freebsd-amd64-race](https://build.golang.org/log/0765de9bde930581c900ada0f14a8b8674a002ca)
[2022-07-08T12:57:49-14abe8a/darwin-amd64-race](https://build.golang.org/log/bcb04a889b7b64bf22054f98baa76c7893824156)
[2022-07-08T12:57:49-14abe8a/openbsd-amd64-70](https://build.golang.org/log/26496cb7ee1b393680a05c2661055cd92c3240c5)

The first of these failures in the logs is at [CL 415634](https://go.dev/cl/415634), but the failure rate for this test is not 100% — it could have been introduced in a somewhat earlier change. However, given the number of failures in the log this looks like a very recent regression.

(attn @golang/runtime)

**Comment by bcmills** [comment]
See previously #24081.

**Comment by prattmic** [comment]
I was able to reproduce this on my linux-amd64 workstation:

```
$ go test cmd/trace -run TestAnalyzeAnnotationTaskTree -count 100
--- FAIL: TestAnalyzeAnnotationTaskTree (0.00s)
    annotations_test.go:228: got task 4:        task1
                start: 25956 end: 639582 complete: true
                13 goroutines
                13 regions:
                        task1.region(goid=21)
                        (goid=23)
                        (goid=24)
                        (goid=11)
                        (goid=25)
                        (goid=26)
                        (goid=27)
                        (goid=28)
                        (goid=29)
                        (goid=30)
                        (goid=31)
                        (goid=32)
                        (goid=33)
                1 children:
                        task2
        ; want {parent: children:[task2] regions:[task1.region]}
FAIL
FAIL    cmd/trace       0.146s
FAIL
```

Though I seem to have gotten lucky? I can't reproduce again even with `-count 10000`.

**Comment by prattmic** [comment]
This can be reproduced pretty easily with:

```go
package main

import (
        "context"
        "runtime"
        "runtime/trace"
        "os"
)

var sink int

func child(ctx context.Context) {
        runtime.GC()
        for i := 0; i < 100000; i++ {
                sink = i
        }
}

func main() {
        f, err := os.Create("/tmp/trace.out")
        if err != nil {
                panic(err)
        }
        defer f.Close()

        if err := trace.Start(f); err != nil {
                panic(err)
        }
        defer trace.Stop()

        ctx := context.Background()
        ctx, task := trace.NewTask(ctx, "thisisatask")
        defer task.End()

        trace.WithRegion(ctx, "thisisaregion", func() {
                go child(ctx)
                for i := 0; i < 5*100000; i++ {
                        sink = i
                }
        })
}
```

On `go tool trace` `/usertask?type=thisisatask`, we see:

```

When	Elapsed	Goroutine ID	Events
0.000079565s	332.722µs		Task 1 (goroutine view) (complete)
0.000079565	 .         	1	task thisisatask (id 1, parent 0) created
0.000089574	 .    10009	1	region thisisaregion started (duration: 319.7µs)
0.000098214	 .     8640	1	new goroutine 7: main.child
0.000412287	 .   314073	1	task end
0.000617513	 .   205226	7	new goroutine 17: runtime.gcBgMarkWorker
0.000653357	 .    35844	7	new goroutine 8: runtime.gcBgMarkWorker
0.000700023	 .    46666	7	new goroutine 33: runtime.gcBgMarkWorker
0.000733251	 .    33228	7	new goroutine 18: runtime.gcBgMarkWorker
0.000765459	 .    32208	7	new goroutine 9: runtime.gcBgMarkWorker
0.000797095	 .    31636	7	new goroutine 19: runtime.gcBgMarkWorker
0.000824072	 .    26977	7	new goroutine 34: runtime.gcBgMarkWorker
0.000864920	 .    40848	7	new goroutine 35: runtime.gcBgMarkWorker
0.000890686	 .    25766	7	new goroutine 36: runtime.gcBgMarkWorker
0.000920815	 .    30129	7	new goroutine 20: runtime.gcBgMarkWorker
0.000957888	 .    37073	7	new goroutine 10: runtime.gcBgMarkWorker
0.000978858	 .    20970	7	new goroutine 37: runtime.gcBgMarkWorker
GC:181.036µs
```

Interestingly, the "goroutine view" visualization already filters out the GC goroutines.

I think we should just exclude system goroutines from the [task inheritance](https://cs.opensource.google/go/go/+/master:src/internal/trace/goroutines.go;drc=c1a4e0fe014568501b194eb8b04309f54eee6b4c;bpv=1;bpt=1;l=169) mentioned above.

Other goroutines created in a region are interesting to see even if they don't perform task operations. GC goroutines are not. (It may be interesting to see that a GC was triggered by this task, but these gcBgMarkWorker events only appear on the _first_ GC, which makes this a poor "GC start" indicator")
