### ISSUE TITLE
x/sys: FreeBSD 11 builders on release-branch.go1.17 broken since CL 415714

### ISSUE THREAD

**Issue by bcmills** [golang/go#53783]
[CL 415714](https://go.dev/cl/415714) regenerated `x/sys` with compatibility only for FreeBSD 12 and higher.

However, the FreeBSD `11_4` builders are still configured to run the repo on `release-branch.go1.17`, and are now failing on that branch.

We should either fix `x/sys` to restore compatibility until `release-branch.go1.17` is no longer being maintained, or explicitly disable this repo on those builders.

(attn @golang/freebsd, @golang/release)

**Comment by paulzhol** [comment]
FreeBSD 11.4 is [EOL](https://www.freebsd.org/security/unsupported/) since September 30, 2021. release-branch.go1.19 is ws already branched out. I wouldn't like to revert if 1.17 is about to be dropped.

**Comment by bcmills** [comment]
Sounds good. Want to send a CL to disable those builders for the `x/sys` repo?
