### ISSUE TITLE
builtin: append replaces values

### ISSUE THREAD

**Issue by Vector-Hector** [golang/go#53795]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 windows/amd64
</pre>

### What did you do?

[Play](https://play.golang.com/p/3rmT80hRlPo)

```go
arr := []string{"a", "b", "c"}
_ = append(arr[:2], "e")
	
fmt.Println(arr)
```
Result:
`["a", "b", "e"]`

### What did you expect to see?

I expected append to create a new slice, that is `["a", "b", "e"]`. I did not expect `append` to change the original slice `arr` as it does not target that slice. If I instead use `append(arr[:2], "e", "f")`, it does not change `arr` (as expected).

### What did you see instead?

The slice `arr` changed its third value from `"c"` to `"e"`.

**Comment by mdlayher** [comment]
Working as intended, you need to use the result of append as it may reallocate the underlying array if there is insufficient space for new elements.

**Comment by mdlayher** [comment]
See: https://pkg.go.dev/builtin#append

**Comment by timothy-king** [comment]
@Vector-Hector `arr[:2]` does have the capacity to store "e". Use the 3 argument form of a slice expression, `a[low : high : max]`, if you intend on controlling capacity: https://go.dev/ref/spec#Slice_expressions.

https://play.golang.com/p/UNFoS592mq5 prints "3 vs 2":
```
func main() {
	c := []string{"a", "b", "c"}
	fmt.Println(cap(c[:2]), " vs ", cap(c[:2:2]))
}
```
