### ISSUE TITLE
cmd/compile: tests for code generation

### ISSUE THREAD

**Issue by bradfitz** [golang/go#5379]
<pre>There are no tests for code generation, as far as I know.

Whenever I see CLs like <a href="https://golang.org/issue/5367?c=12">https://golang.org/issue/5367?c=12</a> I cringe,
not seeing a test, fearing it'll regress.

It'd be nice if cmd/[568][gc] could have a directory of input functions and golden -S
output.  If they don't match, fail.  If some major change happens that breaks most the
golden files, we could have a script in the test directory to re-baseline the golden
files from the actual output.</pre>

**Comment by rsc** [comment]
Maybe @randall77 will do better than I did.

**Comment by bradfitz** [comment]
(Triaging old bugs)

@josharian @mdempsky @brtzsnr, maybe one of you has thoughts on SSA testing? Or maybe the view is that the current testing is satisfactory?

**Comment by josharian** [comment]
There are still some issues here.

As a recent example, Keith added an optimization to coalesce multiple one byte loads, which got broken, and no one noticed until a new performance bug got filed. I'm not sure how to write a test for that that won't be annoyingly fragile, though.

That's for optimization. The correctness front is looking better, with many SSA-instigated tests. Correctness is easier, because you can just write regular Go, like the 1/0 test that went in today.

**Comment by mdempsky** [comment]
Agreed. I think we're in good shape for correctness testing, but we don't have a good solution for testing that instruction-level micro-optimizations are working as intended.

From memory, LLVM has a lot of FileCheck (http://llvm.org/docs/CommandGuide/FileCheck.html) tests, and some of them are used to inspect generated assembly instruction sequences. Maybe we could implement something similar.

**Comment by brtzsnr** [comment]
The way I tested the compiler for a while was to run randomly generated code on go1.5 go1.6 and dev.ssa and compare the results. I found quite a few bugs in all three versions, and lots of missed optimizations in the new compiler. The source of tester is here https://github.com/brtzsnr/gostress. It's limited however to arithmetic operations and branches. No loops, no bounds checking, no calls, no slices, no strings, etc.

For speed I mostly looked at the binary size of pkg/tools/linux_amd64/* which is an indirect measure. Compilebench is also another metric. I also tested changes on my personal projects and saw a speedup of ~2% in the last week. Maybe tracking the performance on a set of benchmarks would be nice (e.g. all benchmarks in stdlib).

Performance regressions are indeed the most problematic. For example I recently retested https://go-review.googlesource.com/#/c/19727/ and concluded it's now a regression. I don't know when that happened and I don't know how to test this.

**Comment by randall77** [comment]
There is now some infrastructure for such tests, see cmd/compile/internal/gc/asm_test.go.  It compiles tests and looks to make sure the right (and not the wrong) instructions are in the generated assembly.

There aren't a whole lot of tests there, but the mechanism is in place.  I think that's enough to close this issue.
