### ISSUE TITLE
x/tools/gopls: test cleanup errors during shutdown with `ERROR_SHARING_VIOLATION` on Windows

### ISSUE THREAD

**Issue by findleyr** [golang/go#53819]
Following the recent change to await proper shutdown of the regtest environment ([CL 416594](https://go.dev/cl/416594)), we get one new flake on windows:

```
--- FAIL: TestRegenerateCgo (7.42s)
    --- FAIL: TestRegenerateCgo/experimental (4.02s)
        runner.go:322: closing the sandbox: error(s) cleaning sandbox: cleaning modcache: <nil>; removing files: remove C:\Users\gopher\AppData\Local\Temp\gopls-regtest-2462642078\TestRegenerateCgo\experimental\work: The process cannot access the file because it is being used by another process.
```

https://build.golang.org/log/27834526d9f9152f3bc200e902c97d8a73d55452
https://build.golang.org/log/b4e52dbee66f77feae2f7fa17e2981087e7fbbcb

If we've learned anything from investigating these flakes, it is that they are often (if not usually) actual races in gopls. Unfortunately the goroutine dump at test failure point does not show anything interesting. It is possible that problematic goroutines had exited before the dump.

**Comment by bcmills** [comment]
Note that Windows in particular seems to produce this error spuriously (compare #51442), or at least for reasons we haven't yet been able to diagnose (see also #25965).

In the `testing` package in the standard library, we're currently working around it with a retry loop:
https://cs.opensource.google/go/go/+/master:src/testing/testing.go;l=1115-1143;drc=de9805c702bcc19bcf3c783d1c2e43fdf4e1d30e

Would it be possible for `gopls` to use the `testing` package to create and clean up its sandbox directories? If not, you might consider copying the `testing` retry loop into the `gopls` test harness.

**Comment by findleyr** [comment]
Thank you @bcmills! I was about to ping you to ask, because I seemed to recall the exact context you have just produced :)

I'll copy the removeAll logic.

**Comment by bcmills** [comment]
Note that these failures still persist after [CL 417117](https://go.dev/cl/417117). 🤔

**Comment by findleyr** [comment]
My investigation into the persistent errors suggested that the new problem is simply that the server did not have enough time to shut down: not that there is a bug in shutdown itself, or that the retry logic doesn't work.

This seems to have been fixed by https://go.dev/cl/417583.

**Comment by findleyr** [comment]
Note: this seems to have gone away so I will close this issue with a CL to improve/remove the shutdown timeout, as suggested by @bcmills in a follow-up comment on https://go.dev/cl/417583.
