### ISSUE TITLE
x/exp/maps: Clone does not preserve nil 

### ISSUE THREAD

**Issue by icholy** [golang/go#53817]
The `x/exp/maps.Clone` function doesn't preserve `nil` the way `x/exp/slices.Clone` does.

``` go
package main

import (
	"fmt"

	"golang.org/x/exp/maps"
)

func main() {
	var m map[string]int
	fmt.Printf("%#v\n", m)             // map[string]int(nil)
	fmt.Printf("%#v\n", maps.Clone(m)) // map[string]int{}
}
```

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/icholy/.cache/go-build"
GOENV="/home/icholy/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/icholy/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/icholy/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4044300034=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Cloned a `nil` map using `x/exp/maps.Clone`.

### What did you expect to see?

The cloned map is also `nil`

### What did you see instead?

The cloned map is an empty non-nil map.

**Comment by mknyszek** [comment]
CC @ianlancetaylor
