### ISSUE TITLE
cmd/go: reject packages whose import paths collide with std packages

### ISSUE THREAD

**Issue by hyangah** [golang/go#53825]
### What version of Go are you using (`go version`)?

<pre>
$ go1.19rc1 version
go version go1.19rc1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
--- go.mod ---
module sync

go1.18

--- sync.go ---
// this is my sync!
package main

```

### What did you expect to see?

build error
(no `main` function!)

### What did you see instead?

no error

```
$ go1.19rc1 build .
$ echo $?
0

$ go1.19rc1 doc .
this is my sync!

$ go1.19rc1 list -f '{{.ImportPath}} {{.Dir}}' .
sync /Users/hakim/sdk/go1.19rc1/src/sync
```
And `go list` is confused, as a result, tools that depend on x/tools/go/packages (e.g. `gopls`) are **very** confused.

**Comment by dominikh** [comment]
It's worth clarifying that the `go build .` command in the example builds the stdlib `sync` package, not our package, driven by `go list`'s confusion.

**Comment by seankhliao** [comment]
I think this is either #35270 or #26227
