### ISSUE TITLE
affected/package: net/http  Getting Wrong ETag value in Head Request response 

### ISSUE THREAD

**Issue by vaidhyanathan93** [golang/go#53840]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go-repos/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go-repos:/opt/go/path:/home/user/go-code"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go/root"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/root/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3523550096=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

URL Tried: https://raw.githubusercontent.com/vaidhyanathan93/Todo/master/5001.png

### What did you expect to see?
```
Etag:[W/"6cdcd3768a6db6eeffffcb12b5983ed56f0871aa76a6e79ac428118edc00eb09"]
```

### What did you see instead?
```
Etag:["803bf92997cf948d66b9b067dd9988dc15942ea6b7c223084dc6593db5e2862f"]
```

The issue happens only for the HEAD Request but for Get request, It is correct.  This seems to be

**Comment by seankhliao** [comment]
This is what the server is sending back

```
2022/07/13 16:18:41 http2: decoded hpack field header field "etag" = "\"803bf92997cf948d66b9b067dd9988dc15942ea6b7c223084dc6593db5e2862f\""
```
vs
```
2022/07/13 16:18:41 http2: decoded hpack field header field "etag" = "W/\"6cdcd3768a6db6eeffffcb12b5983ed56f0871aa76a6e79ac428118edc00eb09\""
```
