### ISSUE TITLE
gollvm: add linkname for runtime variables

### ISSUE THREAD

**Issue by alexanius** [golang/go#53842]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version unknown linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```
$ cat m.go
package main

import _ "unsafe"

//go:linkname memstats runtime.memstats
var memstats struct {
  Alloc int64
  TotalAlloc uint64
  Sys uint64
  Lookups uint64
  Mallocs uint64
  Frees uint64
  HeapAlloc uint64
  HeapIdle uint64
  HeapInuse uint64
  HeapReleased uint64
  HeapObjects uint64
  StackInuse uint64
  StackSys uint64
  MSpanInuse uint64
  MSpanSys uint64
  MCacheInuse uint64
  MCacheSys uint64
  BuckHashSys uint64
  GCSys uint64
  OtherSys uint64
  NextGC uint64
  LastGC uint64
  PauseTotalNs uint64
  PauseNs [256]uint64
  PauseEnd [256]uint64
  NumGC uint32
  NumForcedGC uint32
  GCCPUFraction float64
  EnableGC bool
  DebugGC bool
  BySize [61]struct {
          Size uint32
          Mallocs uint64
          Frees uint64
  }
}

func main() {
  println(memstats.Alloc)
}

$ go run m.go
# command-line-arguments
./m.go:5:3: error: memstats is not a function; '//go:linkname' is only supported for functions
```

### What did you expect to see?

No error

### What did you see instead?

Error

### Discussion

I suggested a patch [here ](https://go-review.googlesource.com/c/gofrontend/+/415694) and want to have an issue I work with.

The situation is the following: I'm porting a Go project from GC to GoLLVM. This project uses some third-party packages with linkname to runtime internal object. I have no possibility to avoid it so I want to make GoLLVM use linkname for variables from compiler internal packages. The suggested patch is a prototype that enables linkname for variables from runtime package.

**Comment by ianlancetaylor** [comment]
I think that what we need here is a way to say whether a particular variable is intended to be a reference to a variable defined in another package, or whether it is intended to be a definition of the variable.  I don't see a way to do that with a single `go:linkname` directive.  I think we need to define two new directives and support them in the gc compiler and the gofrontend code.  The way do that is to write a proposal (https://go.dev/s/proposal) describing the new proposed semantics.

**Comment by ianlancetaylor** [comment]
I understand that you have a problem with existing code.  However, I want to set things up so that future code can be correct.  I don't want to insert a hack that supports existing code in a way that doesn't prepare us for the future.  I'm not going to add your suggestion to the current implementation.  Sorry.

**Comment by alexanius** [comment]
After some discussions with product teams we came to conclusion that they will not change their code. So now the proposal for new directive is not needed because nobody will use it.

Thanks for comments and discussion. I'll close this issue till better days.
