### ISSUE TITLE
x/vuln/cmd/govulncheck: provide version flag

### ISSUE THREAD

**Issue by hyangah** [golang/go#53867]
`-v` or `--version`

We can ask users to run `go version -m` when reporting an issue but this is more approachable.

**Comment by seankhliao** [comment]
Will `govulncheck` have tagged/released versions to report?

**Comment by corani** [comment]
In my CI job I've added a `go version -m govulncheck | awk '$1 == "mod" { print $3 }'` for the time being. A proper version flag would be appreciated.

**Comment by atc0005** [comment]
> Will `govulncheck` have tagged/released versions to report?

+1 for this idea.

Dependabot currently does not support tracking updates via pseudo versions, so having tagged releases would be really useful for any projects bundling it.

**Comment by zpavlinovic** [comment]
govulncheck now supports `--version` flag.
