### ISSUE TITLE
Request Failure Connection with dyanmodb

### ISSUE THREAD

**Issue by estherrs** [golang/go#53861]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.18.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
GO111MODULE="off"
GOARCH="amd64"
GOBIN="/Users/esthersue/go/bin"
GOCACHE="/Users/esthersue/Library/Caches/go-build"
GOENV="/Users/esthersue/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/esthersue/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/esthersue/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8m/b1hsv_350dnbrshykgb_rjj80000gn/T/go-build2590030861=/tmp/go-build -gno-record-gcc-switches -fno-common"
### What did you do?
This is my first time working with Dyanmodb and Go. I was following this tutorial: https://doncicuto.medium.com/getting-started-with-dynamodb-in-go-part-1-a25c5522edd4
When I run "go run main.go", I get an error. I'm not sure why. 

### What did you expect to see?
I expected to create a table in Dyamnodb.

### What did you see instead?
RequestError: send request failed
caused by: Post "http://localhost:8000/": dial tcp 127.0.0.1:8000: connect: connection refused

**Comment by ianlancetaylor** [comment]
I think you need to talk to the dynamodb community.  We can help you with the Go standard library, but not with dynamodb, which is a separate project.

In general, for questions about Go, please see https://go.dev/wiki/Questions for a list of good places to ask questions.
