### ISSUE TITLE
x/tools/gopls: unskip all previously flaky regtests

### ISSUE THREAD

**Issue by findleyr** [golang/go#53878]
This is a follow up to https://go.dev/issue/53781, a deterministic panic that made it into gopls@v0.9.0 in part because a flaky regression test had been skipped, and not un-skipped when the root cause of flakiness was resolved.

We have recently made improvements to several potential sources of flakiness: server shutdown races, invalidation races, and performance. We also have resources to work on flakes that weren't available during the 1.18 push. In light of #53781, we should endeavor to unskip (and further de-flake if necessary) all regression tests that have been unconditionally skipped. This issue tracks that effort:

Currently skipped tests:

- [x] TestQuickFixEmptyFiles: (#48773)
- [x] TestModFileModification (#40269)
- [x] TestCreateDependency (#54073, newly added)
- [x] TestSumUpdateFixesDiagnostics (#51352)
- [x] Test_Issue38211(#44098)
- [x] TestWatchReplaceTargets (#50748)
- [x] TestChangePackageName (#41061)
- [x] TestDeleteModule_Interdependent (#46375)

**Comment by mknyszek** [comment]
FWIW it looks like TestCreateDependency had a flake:

[2022-09-01T03:24:42-49ab44d-86e9e0e/openbsd-amd64-70](https://build.golang.org/log/7d3e7d2ab3f3598f8aca010a72e3b83c428a0661)

Should this get a new issue or is it relevant enough to this?

**Comment by findleyr** [comment]
@mknyszek thanks for reporting.

Hmm. I don't think that flake is actually related to TestCreateDependency: it is simply an error deleting the test files during cleanup.

greplogs also turned up the following recent failure in go/packages tests on openbsd:
https://build.golang.org/log/d9906d7b11d2e43bded9199a00d40d2f8ac47f31

I wonder if this is a recent regression on openbsd? Unclear, so probably best not to assume, and instead file separate new issues for gopls and go/packages.

**Comment by bcmills** [comment]
The `unlinkat` failure looks like #49751 to me.

**Comment by findleyr** [comment]
We have unskipped all flaky regtests.
