### ISSUE TITLE
x/build/vcs-test: migrate to GKE

### ISSUE THREAD

**Issue by heschi** [golang/go#53889]
I wanted to do this a year ago but never got around to it. I don't think we can use Ingress because it requires SSH access, but we can get rid of the VM at least.

cc @golang/release

**Comment by bcmills** [comment]
Better still, I would like to eliminate `vcs-test` as a service entirely (that's #27494).

The caching issues with `vcs-test` GCS buckets are a constant source of friction when writing the tests, the test data is managed by a subset of the Go team (which means it also doesn't go through the usual code-review process), and the fact that those tests require access to a `golang.org` domain makes them extremely flaky for contributors who work offline or in areas of the world with unreliable networking.

I'm still evaluating to what extent that's actually feasible.

**Comment by heschi** [comment]
Sounds good, but will take at least a year to roll out by definition, so I'm not going to wait on it :)

**Comment by aclements** [comment]
Since the CLs have landed, is there more to do for this issue?

**Comment by heschi** [comment]
The DNS rollout finished over the weekend and I don't see failures on the dashboard, so nope, all done.
