### ISSUE TITLE
x/tools/gopls: add a diagnostic (and quick-fix) when a package is outside of go.work

### ISSUE THREAD

**Issue by findleyr** [golang/go#53880]
It can be very confusing when gopls does not function properly because a package is excluded by go.work.

We should provide a friendly error message, preferably as a diagnostic on the package name and/or module name, with a quick fix to add the module to go.work.

**Comment by thediveo** [comment]
Just for clarification: by "is excluded by go.work" do you mean that a Go module **isn't listed** in a `use` statement in a `go.mod`?

**Comment by findleyr** [comment]
From in-person discussion, this can be achieved approximately as follows:

In Server.checkForOrphanedFiles, where we generate the "No packages found" diagnostic, we need to determine if a `go work use` command could potentially fix the problem. For this, we can use the following heuristic:
 - GOWORK is set (check snapshot.WorkFile)
 - The orphaned file is in a module (check parent directories for a go.mod file)
 - That directory is not included in the go.work file (call snapshot.ParseWork for the workfile uri)
 
 If these conditions hold, then we can suggest a quickfix to run `go work use .` from the directory containing the file. The Go command should do the right thing.
 
 We could go further and try to check whether the file would be excluded by build tags even if we use its module, but that is probably overkill.
