### ISSUE TITLE
x/build/cmd/relui: run boringcrypto tests on Go 1.19+

### ISSUE THREAD

**Issue by heschi** [golang/go#53891]
Now that boringcrypto is integrated into the standard toolchain, we don't need a special release process to build the binaries. We do still need to run the tests.

cc @golang/release

**Comment by dmitshur** [comment]
Also see [CL 395815](https://go.dev/cl/395815).

**Comment by heschi** [comment]
I did this accidentally for #53799: the advisory TryBot set includes boringcrypto.
