### ISSUE TITLE
x/sys/windows: add GetLargePageMinimum

### ISSUE THREAD

**Issue by piotr-sneller** [golang/go#53900]
Hello,

could you please add [GetLargePageMinimum()](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-getlargepageminimum) to the windows API wrappers? The VirtualAlloc() flag MEM_LARGE_PAGES is supported, but per the documentation, the block size should then be large page aligned. This alignment information is missing due to the lack of the GetLargePageMinimum() function. The proposed extension closes the gap.

Many thanks for considering my request.

**Comment by ianlancetaylor** [comment]
Taking this out of the proposal process, as adding a wrapper for an ordinary Windows call does not require a proposal.

Want to send a patch for this?
