### ISSUE TITLE
x/pkgsite: package removal request for [type path here]

### ISSUE THREAD

**Issue by rppala3** [golang/go#53915]
### What is the path of the package that you would like to have removed?
github.com/rppala3/broadcast-go

 
 
 
### Are you the owner of this package?
yes

 
### What is the reason that you could not retract this package instead?
I renamed the git repository from **broadcast-go** to **broadcast-channel** and now I'm facing this error:
~~~~
go: github.com/rppala3/broadcast-channel@v1.0.0: parsing go.mod:
	module declares its path as: github.com/rppala3/broadcast-go
	        but was required as: github.com/rppala3/broadcast-channel
~~~~
I temporally solved writing the line below into the *go.mod*, but I would like solve this misaddressing online as well.
`replace github.com/rppala3/broadcast-channel v1.0.0 => github.com/rppala3/broadcast-go v1.0.0`

**Comment by seankhliao** [comment]
The contents of the module proxy are immutable. Removing it from pkgsite won't fix the problem. fix your go.mod and bump up the version.
