### ISSUE TITLE
interface: Can the interface trap be fixed?

### ISSUE THREAD

**Issue by Jesgoal** [golang/go#53910]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```
package main

import (
	"fmt"
	"net"
)

func trap(con net.Conn) net.Conn {
	if con == nil {
		fmt.Println("con is nil")
	}
	fmt.Println(con)
	return con
}
func main() {
	var con *net.TCPConn
	c := trap(con)
	if c == nil {
		fmt.Println("c is nil")
	} else {
		c.Close()
	}
}
```

### What did you see instead?
```
<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x13fc7f11d]

goroutine 1 [running]:
net.(*TCPConn).Close(0x0)
	<autogenerated>:1 +0x1d
main.main()
```

**Comment by robpike** [comment]
This is an instance of https://go.dev/doc/faq#nil_error

The value of 'con' is a nil pointer, but the promotion to the argument of trap creates a non-nil interface, one a type that has been set, so it is not nil.

The simplest fix is to change the type of con from *net.TCPConn to net.Conn.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
