### ISSUE TITLE
modernc.org/sqlite tests timing out on linux/riscv64 using go1.19rc2

### ISSUE THREAD

**Issue by danp** [golang/go#53925]
(opening this on behalf of someone who does not have a GitHub account)

[modernc.org/sqlite](http://modernc.org/sqlite) v1.17.3 (f40342ecdc29), tagged about a month ago, passes all tests with up to and including go1.18.3 (1.18.4 was not tried) on supported targets as [listed here](https://pkg.go.dev/modernc.org/sqlite#hdr-Supported_platforms_and_architectures).

The tests fail with Go1.19 rc1 and rc2 on linux/riscv64. The [full list here](https://modern-c.appspot.com/-/builder/?importpath=modernc.org%2fsqlite) includes also platforms not officially supported.

The linux/riscv64 timeouts after a 24 hour limit. Before the tests ran for about 12 hours to completion.

**Comment by danp** [comment]
It seems likely the windows failure is related to a Go version check in the test that needs to account for 1.19.

**Comment by bcmills** [comment]
It would be helpful to have goroutine dumps for the `linux/riscv64` timeouts — if the system is deadlocked somewhere we would need at least some starting point to unravel it.

Did the Windows issues turn out to be fixed by https://gitlab.com/cznic/sqlite/-/commit/1cd30edd99d4b46618cf0190efadc8fc94e2a701?

**Comment by danp** [comment]
Think we tracked down the linux/ricsv64 timeout to the 1.19 RLIMIT_NOFILE change. The test that was hanging tries to exhaust all possible file descriptors and with 1.19 there are now likely many more of them. A change will be made to ensure the hard limit stays reasonable. That possibly explains the failures on the other (unsupported) platforms as well.

Going to close this! Thanks for your patience and attention.
