### ISSUE TITLE
x/tools/gopls: TestUseGoWork failure on `darwin-arm64-11`

### ISSUE THREAD

**Issue by bcmills** [golang/go#53934]
`greplogs --dashboard -md -l -e 'FAIL: TestUseGoWork' --since=2022-07-08`
[2022-07-14T21:01:58-db8f89b-aa80228/darwin-arm64-11](https://build.golang.org/log/cbff206e69443d9ec55c0fb38c5b0f3205fe7ba9)

I don't see the `no package for given file position` symptom from #53733 (CC @findleyr); it isn't clear to me whether this failure mode is related.

**Comment by findleyr** [comment]
I still see only that failure when running greplogs. A lot of code has changed here (for the better!), and I suspect that this is now fixed.

We can reopen if it reoccurs.
