### ISSUE TITLE
cmd/compile: GOSSAHASH debugging switch needs to be accessible outside SSA

### ISSUE THREAD

**Issue by dr2chase** [golang/go#53937]
From time to time when debugging the compiler, it is helpful to use the GOSSAHASH environment variable to switch modified code on/off to search for exactly where a bug has its effect.  However, this is currently limited to the `ssa` package.  In the past I've edited the code to make it accessible outside of `ssa` when I needed it, and then discarded the edit.  This seems like a waste of time, I've done this more than once, so it should be refactored into `base`.

**Comment by laboger** [comment]
Is there any documentation on how GOSSAHASH can be used? I see GOSSAFUNC mentioned in cmd/compile/internal/ssa/README.md.

**Comment by dr2chase** [comment]
Common case for me is to use it in conjunction with a program I wrote that uses it to implement a search ([`github.com/dr2chase/gossahash`](https://github.com/dr2chase/gossahash) which could itself use better documentation).  I added a comment to the new source code that might work for you, if it needs more, this is a good time to ask:

https://go-review.googlesource.com/c/go/+/418015/2/src/cmd/compile/internal/base/hashdebug.go

Oh, right away (checking my shell history for examples) I see a missing tweak `GOMAXPROCS=1 gossahash -- ./make.bash`, got to run the compiler single threaded if that is what is failing, if you want a good search.
