### ISSUE TITLE
go/mod: no way to have sub-package import parent package

### ISSUE THREAD

**Issue by pjebs** [golang/go#53945]
### What version of Go are you using (`go version`)?

go 1.18

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Windows 7

### What did you do?

1. I have a module (with a package).
2. I have a sub-package (no go.mod file inside).
3. I want to sub-package to import the parent package.
4. The parent package does not reference the sub-package. (i.e. no import cycles)

What I am trying to achieve is basically:

https://pkg.go.dev/database/sql#Register (parent package)
https://github.com/go-sql-driver/mysql/blob/master/driver.go#L84 (but as a sub-package)

### What did you expect to see?

Someone it working.

### What did you see instead?

go mod keeps complaining about package ambiguities etc and it seems to not be possible.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
