### ISSUE TITLE
go build freezes

### ISSUE THREAD

**Issue by halturin** [golang/go#53951]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.11 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/taras/.cache/go-build"
GOENV="/home/taras/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/taras/devel/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/taras/devel/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/nix/store/k375arxkpvdb3c50y6wx9kp654k3ir8x-go-1.17.11/share/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/nix/store/k375arxkpvdb3c50y6wx9kp654k3ir8x-go-1.17.11/share/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.11"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/taras/devel/go/src/github.com/ergo-services/metrics/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build168671815=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

just run `go build` in my project it shows errors in my code and freezes with consuming 100% CPU. Is there any way to get any debug info for the investigation?

**Comment by seankhliao** [comment]
-x to print execution commands
kill it with SIGABRT to get a traceback

**Comment by halturin** [comment]
Hmm, it's weird. After launching with the -x option, it froze for a short period of time and normally stopped (I couldn't manage to send SIGABRT signal). Now it doesn't freeze whether I use the -x option or not. But before that, it "sleeps" even longer 30 seconds until I stop it with ctrl-c.

Anyway, thanks for the tip. I'll provide a more detailed report next time if I get this issue again.

**Comment by yetone** [comment]
The same problem, without -x it freezes, with -x it works normally.

**Comment by fgazat** [comment]
Same here. Tried to launch with -x once and now it works
