### ISSUE TITLE
x/build/cmd/gomote: `gomote run` arguments are subtle and tedious

### ISSUE THREAD

**Issue by bcmills** [golang/go#53957]
### What version of Go are you using (`go version`)?

<details><summary><code>~$ go version -m $(which gomote)</code></summary>

<pre>
/usr/local/google/home/bcmills/bin/gomote: devel go1.19-b9c4d94fdb Fri Jun 24 18:54:27 2022 +0000
        path    golang.org/x/build/cmd/gomote
        mod     golang.org/x/build      v0.0.0-20220623213349-3ceb9f4e34a9      h1:UXzH6j5xqqdwolS/8sIboizJIjD1FchifnbxqrO4wro=
        dep     cloud.google.com/go/compute     v1.3.0  h1:mPL/MzDDYHsh5tHRS9mhmhWlcgClCrCa6ApQCU6wnHI=
        dep     github.com/aws/aws-sdk-go       v1.30.15        h1:Sd8QDVzzE8Sl+xNccmdj0HwMrFowv6uVUx9tGsCE1ZE=
        dep     github.com/golang/groupcache    v0.0.0-20200121045136-8c9f03a8e57e      h1:1r7pUrabqp18hOBcwBwiTsbnFeTZHV9eER/QT5JVZxY=
        dep     github.com/golang/protobuf      v1.5.2  h1:ROPKBNFfQgOUMifHyP+KYbvpjbdoFNs+aK7DXlji0Tw=
        dep     github.com/googleapis/gax-go/v2 v2.1.1  h1:dp3bWCh+PPO1zjRRiCSczJav13sBvG4UhNyVTa1KqdU=
        dep     github.com/jmespath/go-jmespath v0.4.0  h1:BEgLn5cpjn8UN1mAw4NjwDrS35OdebyEtFe+9YPoQUg=
        dep     go.opencensus.io        v0.23.0 h1:gqCw0LfLxScz8irSi8exQc7fyQ0fKQU/qnC/X8+V/1M=
        dep     golang.org/x/net        v0.0.0-20220127200216-cd36cc0744dd      h1:O7DYs+zxREGLKzKoMQrtrEacpb0ZVXA5rIwylE2Xchk=
        dep     golang.org/x/oauth2     v0.0.0-20211104180415-d3ed0bb246c8      h1:RerP+noqYHUQ8CMRcPlC2nvTa4dcBIjegkuWdcUDuqg=
        dep     golang.org/x/sync       v0.0.0-20210220032951-036812b2e83c      h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
        dep     golang.org/x/sys        v0.0.0-20220209214540-3681064d5158      h1:rm+CHSpPEEW2IsXUib1ThaHIjuBVZjxNgSKmBLFfD4c=
        dep     golang.org/x/text       v0.3.7  h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
        dep     golang.org/x/time       v0.0.0-20210723032227-1f47c861a9ac      h1:7zkz7BUtwNFFqcowJ+RIgu2MaV/MapERkDIy+mwPyjs=
        dep     google.golang.org/api   v0.70.0 h1:67zQnAE0T2rB0A3CwLSas0K+SbVzSxP+zTLkQLexeiw=
        dep     google.golang.org/genproto      v0.0.0-20220222213610-43724f9ea8cf      h1:SVYXkUz2yZS9FWb2Gm8ivSlbNQzL2Z/NpPKE3RG2jWk=
        dep     google.golang.org/grpc  v1.44.0 h1:weqSxi/TMs1SqFRMHCtBgXRs8k3X39QIDEZ0pRcttUg=
        dep     google.golang.org/protobuf      v1.27.1 h1:SnqbnDw1V7RiZcXPx5MEeqPv2s79L9i7BJUlG/+RurQ=
        dep     gopkg.in/inf.v0 v0.9.1  h1:73M5CoZyi3ZLMOyDlQh031Cx6N9NDJ2Vvfl76EDAgDc=
        build   -compiler=gc
        build   CGO_ENABLED=1
        build   CGO_CFLAGS=
        build   CGO_CPPFLAGS=
        build   CGO_CXXFLAGS=
        build   CGO_LDFLAGS=
        build   GOARCH=amd64
        build   GOOS=linux
        build   GOAMD64=v1
</pre>
</details>

### What did you do?

```
$ gomote create linux-amd64
$ gomote run user-bcmills-linux-amd64-0 pwd
```

```
$ gomote create windows-amd64-2012
$ gomote run user-bcmills-windows-amd64-2012-0 dir
```

### What did you expect to see?

The output of the `pwd` or `dir` command.

### What did you see instead?

On Linux, commands typically only work if they are given by absolute path, even if the command would be available in the `$PATH` normally available on the builder (compare #32430):
```
~$ gomote run user-bcmills-linux-amd64-0 pwd
Error running run: fork/exec /workdir/pwd: no such file or directory

~$ gomote run user-bcmills-linux-amd64-0 /bin/pwd
/workdir
```

On Windows, commands seem to require not only the absolute path, but also the magic `-system` flag, and the failure mode without it is incredibly misleading:
```
~$ gomote run user-bcmills-windows-amd64-2012-0 dir
Error running run: exec: "C:\\workdir\\dir": file does not exist

~$ gomote run user-bcmills-windows-amd64-2012-0 cmd /c dir
Error running run: exec: "C:\\workdir\\cmd": file does not exist

~$ gomote run user-bcmills-windows-amd64-2012-0 'C:\windows\system32\cmd.exe' /c dir
Error running run: Error trying to execute C:\windows\system32\cmd.exe: buildlet: HTTP status 400 Bad Request: requires 'cmd' parameter

~$ gomote run -system user-bcmills-windows-amd64-2012-0 'C:\windows\system32\cmd.exe' /c dir
 Volume in drive C has no label.
 Volume Serial Number is C8EA-22A6

 Directory of C:\workdir

07/02/2018  05:51 PM    <DIR>          .
07/02/2018  05:51 PM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  19,789,328,384 bytes free
```

**Comment by mknyszek** [comment]
Thanks for filing this, this is on my radar and I plan to resolve it.

**Comment by bcmills** [comment]
I think https://go.dev/cl/367896 will be necessary (but perhaps not sufficient) to get to a state that works more like the native `$PATH` search. I'm going to get that reviewed and merged, and you're welcome to follow up with further improvements on top of it. 🙂

**Comment by mknyszek** [comment]
Thanks @bcmills! I suspect your CL is indeed sufficient. I could've sworn I saw an empty `PATH` on a builder before, but executing `/usr/bin/env` on a Linux instance does indeed reveal that there is a baseline `PATH` set.

**Comment by dmitshur** [comment]
Tested with the new coordinator and buildlet versions, and it works as expected:

```
$ gomote v2 create linux-amd64
dmitshur-linux-amd64-0
$ gomote v2 run dmitshur-linux-amd64-0 pwd     
/bin
```

<details><summary>gomote legacy</summary><br>

```
$ gomote create linux-amd64
user-dmitshur-linux-amd64-0
$ gomote run user-dmitshur-linux-amd64-0 pwd
/bin
```

</details>
