### ISSUE TITLE
cmd/compile: GOEXPERIMENT=unified on macOS fails fixedbugs/issue27836.go

### ISSUE THREAD

**Issue by dr2chase** [golang/go#53954]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.19-de8101d21b Mon Jul 18 18:04:23 2022 +0000 X:unified darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/drchase/Library/Caches/go-build"
GOENV="/Users/drchase/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT="unified"
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/drchase/work/gocode/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/drchase/work/gocode"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/drchase/work/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/drchase/work/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="devel go1.19-de8101d21b Mon Jul 18 18:04:23 2022 +0000 X:unified"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/v6/9yfw749x623dr55rpm6ntnsc0095tn/T/go-build1756414274=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
GOEXPERIMENT=unified ./make.bash
cd ../test
go run run.go -- fixedbugs/issue27836.go
```

### What did you expect to see?
Success

### What did you see instead?
```
<unknown line number>: internal compiler error: have package "test/Äfoo" (0xc00044fd10), want package "test/Äfoo" (0xc00044fb80)
```

**Comment by dr2chase** [comment]
I'm going to start bisecting.  I tried this on a hunch that something had changed in tip (since the dev.unified branch was working, till the latest merge).

**Comment by dr2chase** [comment]
It was working on May 2, at the boringcrypto merge 0668e3cb1a .
That still might be part of the problem, but I want to see what bisecting finds, now that I have good and bad points.

**Comment by dr2chase** [comment]
So the other half of the problem, no surprise, was `cmd/compile: set LocalPkg.Path to -p flag`.

**Comment by bcmills** [comment]
> I would expect the same problem could arise if a Go module had a similarly named directory: it would be compiled as one path on macOS due to canonicalization, and a different one on other OSes.

That shouldn't be the case (modulo bugs, of course), but see also #38342 and #38571 🙃
