### ISSUE TITLE
Feature Request | I want a breakpoint function, not `runtime.Breakpoint()`.

### ISSUE THREAD

**Issue by y-okamoto-1113** [golang/go#53967]
I'm sorry, but I didn't know if I should create the Issue in Delve or here...

I want a breakpoint function, not `runtime.Breakpoint()`.
I meant "breakpoint function" like `binding.pry` in ruby, `breakpoint()` in python.

# `runtime.Breakpoint()` is not what i expected.
`main.go` is here.
```main.go
package main

import "runtime"

func main() {
	println("Hello World 1")
	runtime.Breakpoint()
	println("Hello World 2")
}

```

if i run `go run main.go`, **the process was killed and outputted the following**.(replaced my username as XXX)
```
Hello World 1
SIGTRAP: trace trap
PC=0x1045b4550 m=0 sigcode=0

goroutine 1 [running]:
runtime.breakpoint()
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/asm_arm64.s:111 fp=0x14000098f50 sp=0x14000098f50 pc=0x1045b4550
runtime.Breakpoint(...)
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/proc.go:4302
main.main()
        /Users/XXX/Public/work/go-debug/main.go:7 +0x3c fp=0x14000098f70 sp=0x14000098f50 pc=0x1045b6b3c
runtime.main()
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/proc.go:250 +0x250 fp=0x14000098fd0 sp=0x14000098f70 pc=0x104590a10
runtime.goexit()
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/asm_arm64.s:1263 +0x4 fp=0x14000098fd0 sp=0x14000098fd0 pc=0x1045b4984

r0      0x0
r1      0x1
r2      0x140000021a0
r3      0x0
r4      0x0
r5      0x1
r6      0x1d0
r7      0x200
r8      0x10461b880
r9      0xe
r10     0x0
r11     0x60
r12     0x14000022060
r13     0x16b89b1f0
r14     0x0
r15     0x1
r16     0x140000983a0
r17     0x14000098f30
r18     0x0
r19     0x10
r20     0x8
r21     0x3
r22     0x104649fd4
r23     0x0
r24     0x0
r25     0x0
r26     0x0
r27     0x1
r28     0x140000021a0
r29     0x14000098f48
lr      0x1045b6b3c
sp      0x14000098f50
pc      0x1045b4550
fault   0x1045b4550
exit status 2
```

I expected that `runtime.Breakpoint` breaks(stops) processes and debug easily like `delve`. But didn't...
I WANT BREAKPOINT FUNCTION, PLEASE!

**Comment by qmuntal** [comment]
If I'm not wrong, Ruby `binding.pry` and Python `breakpoint()` are not just adding a breakpoint instruction but also initiating a debugging session using a configurable debugger.

So, trying to rephrase this request, what @y-okamoto-1113 wants is that `runtime.Breakpoint()` stops the program execution and attaches a debugger, i.e. Delve, to the current process. Am I right?

**Comment by Jorropo** [comment]
@y-okamoto-1113 `runtime.Breakpoint` work as you ask for assuming you are running with delve:
```console
$ dlv debug a.go
Type 'help' for list of commands.
(dlv) c
Hello World 1
> [hardcoded-breakpoint] main.main() ./a.go:8 (hits total:0) (PC: 0x45b394)
     3:	import "runtime"
     4:	
     5:	func main() {
     6:		println("Hello World 1")
     7:		runtime.Breakpoint()
=>   8:		println("Hello World 2")
     9:	}
```
I don't understand what you are asking for.

**Comment by seankhliao** [comment]
This seems clearly out of scope for the runtime / standard library.
Maybe one of the debuggers can provide this.
