### ISSUE TITLE
cmd/dist/test: -race flag not supported for linux/s390x although cmd/internal/sys/supported begs to differ

### ISSUE THREAD

**Issue by haubenr** [golang/go#53981]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.4 linux/s390x
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="s390x"
GOBIN=""
GOCACHE="/home/haubenr/.cache/go-build"
GOENV="/home/haubenr/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="s390x"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/haubenr/Work/Development/workspaces/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/haubenr/Work/Development/workspaces/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_s390x"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
AR="ar"
CC="s390x-linux-gnu-gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -march=z196 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2211726378=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

The knative.dev go-based e2e testcases are being run with the `go test -race ...`  command. While this works fine for the main x86_64 platform, for linux/s390x the command always reports `-race is not supported on linux/s390x`.

### What did you expect to see?

Race detection is enabled for linux/s390x in the go codebase, but for some reason the implementations in `cmd/internal/sys/supported.go` and `cmd/dist/test.go` have diverged although the comments in both files suggest otherwise. This should be fixed, with `cmd/dist/test.go`exhibiting the same behaviour as the main implementation in `cmd/internal/sys/supported.go`.

### What did you see instead?

Race detection does not work when calling `go test -race` whereas the actual implementation in the go codebase suggests otherwise.

**Comment by cherrymui** [comment]
Thanks for the report. Sent the CL above to make cmd/dist match.

However, you're seeing `-race is not supported on linux/s390x` because you're using Go 1.18.4, whereas the race detector support is added for Go 1.19, see https://tip.golang.org/doc/go1.19#runtime/race .
