### ISSUE TITLE
x/sys/unix/linux: mkall.go runs targets single threaded

### ISSUE THREAD

**Issue by ctII** [golang/go#54009]
### What operating system and processor architecture are you using?

```
GOOS="linux"
GOARCH="amd64"
```

### What did you do?
Ran `GOOS="linux" ./mkall.sh`

### What did you see?
All targets are seemly run single threaded leading to a runtime of roughly 29-30 minutes

### What did you expect to see?
Multiple architecture's targets being worked on at roughly the same time, decreasing time taken to generate relevant files.
Some preliminary tests shows a speedup to about 7 minutes with parts of the targets being done in separate goroutines, with a i7-7700HQ 4c8t

**Comment by cherrymui** [comment]
@ctII thanks for the issue. Sounds like you're working on improving it? Would you like to send a CL? (See https://go.dev/doc/contribute for how to contribute to Go.) Thanks.

**Comment by ctII** [comment]
> @ctII thanks for the issue. Sounds like you're working on improving it? Would you like to send a CL? (See https://go.dev/doc/contribute for how to contribute to Go.) Thanks.

Yes, I am currently working on improving this. I will send a CL
