### ISSUE TITLE
x/build: add power10 builder for ppc64le when available at OSU

### ISSUE THREAD

**Issue by laboger** [golang/go#54000]
There is supposed to be a power10 system available at OSU within the next month.

Once it is ready we'd like to have a power10 builder set up so we can add power10 support to Golang.

The initial builders for Power were set up and managed by the Go team but when we wanted to add a power9 builder that was done by a member of our team @ceseo  (although is currently managed by the Go team). Let us know how to proceed with initial set up of this system.

**Comment by ceseo** [comment]
I think you can just follow [these instructions](https://github.com/golang/go/wiki/DashboardBuilders). It's what I did back then.

FWIW, the current power9 builders were set up by @bradfitz. The ones I had set up were then deactivated and the VMs removed. I don't remember why we changed this, though.

**Comment by laboger** [comment]
@pmur Should this be closed now that the p10 builder is up and running?

**Comment by pmur** [comment]
Yes, it's up and running CI against GOPPC64=power10.
