### ISSUE TITLE
runtime: create runtime_realgcount func to reduce one time stw when fetch goroutine profile

### ISSUE THREAD

**Issue by Jun10ng** [golang/go#54014]
Using `goroutineProfileWithLabelsConcurrent` to fetch the number of goroutines leads to STW,  

Maybe we can directly call `gcount() + fing` to avoid STW on pre-profile phase.

@rhysh  If I were wrong, please correct me, thanks.

**Comment by ianlancetaylor** [comment]
There is no API change here, so taking this out of the proposal process.
