### ISSUE TITLE
affected/package: encoding/json's design  is bad

### ISSUE THREAD

**Issue by introspection3** [golang/go#54016]
### What version of Go are you using (`go version`)?
all 
<pre>
$ go version
all 
</pre>

### Does this issue reproduce with the latest release?

no

### What operating system and processor architecture are you using (`go env`)?
all

### What did you do?

       m := map[string]int64{"abc": math.MaxInt64}
	strBytes, _ := json.Marshal(m)
	json := string(strBytes)
	//this json will be used by javascript,(as json is javascript),but javascript can't use this MaxInt64,
	//so you should give an option to Marshal int64 as string

### What did you expect to see?

	//so you should give an option to Marshal int64 as string

### What did you see instead?

no

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by introspection3** [comment]
@seankhliao you have resolved this bug now,congratulation................
bad action
