### ISSUE TITLE
encoding/csv does not properly work with Quote set to '\t'

### ISSUE THREAD

**Issue by tvanriper** [golang/go#54021]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jvanriper/.cache/go-build"
GOENV="/home/jvanriper/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jvanriper/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jvanriper/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jvanriper/Documents/golang/test/tsv/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build40180683=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.18.4 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.18.4
uname -sr: Linux 5.15.55-1-MANJARO
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	21.3.5
Codename:	Ruah
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.35.
</pre></details>

### What did you do?

Attempted to use encoding/csv to parse a tab separated values file that has empty columns.

This play link demonstrates the problem pretty clearly.

https://go.dev/play/p/gIQE_fdrZwe

### What did you expect to see?

For columns without values, I expected to see an empty string.

### What did you see instead?

The column is missing altogether.

**Comment by seankhliao** [comment]
> // If TrimLeadingSpace is true, leading white space in a field is ignored.
> // This is done even if the field delimiter, Comma, is white space.
> TrimLeadingSpace bool

Closing as working as documented
