### ISSUE TITLE
x/crypto/ssh: can't establish ssh connection using signed key

### ISSUE THREAD

**Issue by kt97679** [golang/go#54027]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
ubuntu 18.04 amd64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/XXX/.cache/go-build"
GOENV="/home/XXX/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/var/tmp/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/var/tmp/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/XXX/bin/go1.18.4"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/XXX/bin/go1.18.4/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/XXX/work/go/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2094095442=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
```
$ go run 001-ssh-test.go 127.0.0.1:22
2022/07/24 08:44:16 Connecting to 127.0.0.1:22
2022/07/24 08:44:16 We've got a live session!
$ go run 001-ssh-test.go 10.19.197.10:22
2022/07/24 08:44:25 Connecting to 10.19.197.10:22
2022/07/24 08:44:28 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
exit status 1
$ cat 001-ssh-test.go 
package main

import (
        "log"
        "net"
        "os"
        "os/user"

        "golang.org/x/crypto/ssh"
        "golang.org/x/crypto/ssh/agent"
)

func logFatal(err error) {
        if err != nil {
                log.Fatal(err)
        }
}

func main() {

        sock, err := net.Dial("unix", os.Getenv("SSH_AUTH_SOCK"))
        logFatal(err)

        u, err := user.Current()
        logFatal(err)

        cfg := &ssh.ClientConfig{
                User: u.Username,
                Auth: []ssh.AuthMethod{ssh.PublicKeysCallback(agent.NewClient(sock).Signers)},
                HostKeyCallback: ssh.InsecureIgnoreHostKey(),
        }

        log.Printf("Connecting to %s\n", os.Args[1])
        client, err := ssh.Dial("tcp", os.Args[1], cfg)
        logFatal(err)

        _, err = client.NewSession()
        logFatal(err)

        log.Println("We've got a live session!")
}
$ cat go.mod 
module test
require golang.org/x/crypto v0.0.0-20220722155217-630584e8d5aa
require golang.org/x/sys v0.0.0-20220722155257-8c9f86f7a55f // indirect
go 1.18
$
```

### What did you expect to see?

Connection is established using signed key.

### What did you see instead?

Connection is not established with an error message:
```
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

### Additional information

I have 2 keys in the agent and I can connect ok via ssh command to 127.0.0.1 (accepts only unsigned keys) and 10.19.197.10 (accepts only signed keys):
```
$ ssh-add -l
4096 SHA256:m+Hthc93TjF0wcAoq8OyrKZjDl8LE5ddhQwzwnBA02c /home/XXX/.ssh/id_rsa (RSA)
4096 SHA256:m+Hthc93TjF0wcAoq8OyrKZjDl8LE5ddhQwzwnBA02c /home/XXX/.ssh/id_rsa (RSA-CERT)
$ ssh 127.0.0.1 "dpkg -l|grep openssh"
Warning: Permanently added '127.0.0.1' (ECDSA) to the list of known hosts.
ii  openssh-client                        1:7.6p1-4ubuntu0.7                     amd64        secure shell (SSH) client, for secure access to remote machines
ii  openssh-server                        1:7.6p1-4ubuntu0.7                     amd64        secure shell (SSH) server, for secure access from remote machines
ii  openssh-sftp-server                   1:7.6p1-4ubuntu0.7                     amd64        secure shell (SSH) sftp server module, for SFTP access from remote machines
$ ssh 10.19.197.10 "dpkg -l|grep openssh"
ii  openssh-client                        1:7.6p1-4ubuntu0.6                  amd64        secure shell (SSH) client, for secure access to remote machines
ii  openssh-server                        1:7.6p1-4ubuntu0.6                  amd64        secure shell (SSH) server, for secure access from remote machines
ii  openssh-sftp-server                   1:7.6p1-4ubuntu0.6                  amd64        secure shell (SSH) sftp server module, for SFTP access from remote machines
$
```
Versions of the ssh components are in the output above.

**Comment by kt97679** [comment]
Hi @FiloSottile , here is an issue I filed per your request. Thanks!

**Comment by cherrymui** [comment]
cc @FiloSottile @golang/security

**Comment by kt97679** [comment]
Folks, do you have any news on this by any chance?

**Comment by kt97679** [comment]
Any help with resolving this issue will be very much appreciated.

**Comment by shuLhan** [comment]
@kt97679 Can you run ssh-agent with -d option and test running your program again?

```
$ ssh-agent -d -a $SSH_AUTH_SOCK
...
$ go run 001-ssh-test.go 10.19.197.10:22
# wait until exit
```

and copy-paste the output once the program exit.

Also, what is the `ssh-add -L` print?

**Comment by kt97679** [comment]
Tried today, still see failure:
```
go: downloading golang.org/x/crypto v0.3.0
go: downloading golang.org/x/sys v0.2.0
go: downloading golang.org/x/term v0.2.0
go: upgraded golang.org/x/crypto v0.1.0 => v0.3.0
go: upgraded golang.org/x/sys v0.1.0 => v0.2.0
2022/11/16 18:44:55 Connecting to 10.19.197.10:22
2022/11/16 18:44:57 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
exit status 1
```
Can I provide more details to help with the fix of this issue?

**Comment by kt97679** [comment]
Issue is still there:
```
$ cat 001-ssh-test.sh
#!/bin/bash

go get -u
go mod tidy
go run 001-ssh-test.go 10.19.197.10:22
$ ./001-ssh-test.sh
go: downloading golang.org/x/crypto v0.4.0
go: downloading golang.org/x/sys v0.3.0
go: downloading golang.org/x/term v0.3.0
go: upgraded golang.org/x/crypto v0.3.0 => v0.4.0
go: upgraded golang.org/x/sys v0.2.0 => v0.3.0
2023/01/02 11:40:54 Connecting to 10.19.197.10:22
2023/01/02 11:40:56 ssh: handshake failed: ssh: unable to authenticate,
attempted methods [none publickey], no supported methods remain
exit status 1
$
```
It seems that this is a regression. I have old binary that works with signed keys ok and here is dependency:
```
$ strings ossh|grep ssh/client.go
/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210817164053-32db794688a5/ssh/client.go
$
```

**Comment by kt97679** [comment]
issue is reproducible with golang.org/x/crypto v0.5.0
```
$ ./001-ssh-test.sh
go: downloading golang.org/x/crypto v0.5.0
go: downloading golang.org/x/sys v0.4.0
go: downloading golang.org/x/term v0.4.0
go: upgraded golang.org/x/crypto v0.4.0 => v0.5.0
go: upgraded golang.org/x/sys v0.3.0 => v0.4.0
2023/01/06 10:01:55 Connecting to 10.19.197.10:22
2023/01/06 10:01:57 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
exit status 1
$
```

**Comment by kt97679** [comment]
Hi folks, I found list of versions here: https://deps.dev/go/golang.org%2Fx%2Fcrypto/v0.0.0-20151201002508-7b85b097bf75/versions and was able to identify versions where issue was introduced:
```
$ for x in v0.0.0-20220314234659-1baeb1ce4c0b v0.0.0-20220314234724-5d542ad81a58 v0.0.0-20220315160706-3147a52a75dd; do echo $x && sed -ie "s@\(require golang.org/x/crypto \).*@\1$x@" go.mod && go mod tidy && go run 001-ssh-test.go 10.19.197.10:22; done
v0.0.0-20220314234659-1baeb1ce4c0b
2023/02/06 20:58:16 Connecting to 10.19.197.10:22
2023/02/06 20:58:19 We've got a live session!
v0.0.0-20220314234724-5d542ad81a58
2023/02/06 20:58:19 Connecting to 10.19.197.10:22
2023/02/06 20:58:22 ssh: handshake failed: agent: unsupported algorithm "ssh-rsa"
exit status 1
v0.0.0-20220315160706-3147a52a75dd
2023/02/06 20:58:22 Connecting to 10.19.197.10:22
2023/02/06 20:58:24 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
exit status 1
$ 
```
I really hope this will help with fixing this issue. Thank you.

**Comment by kt97679** [comment]
From what I see issue is related to this change: https://github.com/golang/crypto/commit/5d542ad81a58c89581d596f49d0ba5d435481bcf#diff-bb5baf29632fd3d0305064ad6e6dc4b9849778a8cd1513f08cf9e866c61210acL775-L783

**Comment by href** [comment]
I see the same issue as you, and I was so far unable to get a workaround. To me this seems pretty much broken.

**Comment by avron99** [comment]
-       golang.org/x/crypto v0.0.0-20210513164829-c07d793c2f9a
+       golang.org/x/crypto v0.12.0
now i am stuck too

**Comment by Dentrax** [comment]
Hey, I just this exact same case. `agent.NewClient(conn).Signers()` returns nothing.

```bash
$ ssh USER@IP
// OK - working as expected
```

```bash
$ echo $SSH_AUTH_SOCK
/private/tmp/com.apple.launchd.REDACTED/Listeners

$ ssh-add -l
The agent has no identities.

$ cat ~/.ssh/config
Host *
    IdentityAgent "~/Library/Group Containers/REDACT.com.1password/t/agent.sock"
```

Minimal reproducible code snippet adopted from: https://cs.opensource.google/go/x/crypto/+/master:ssh/agent/example_test.go;drc=ac88ee75c92c889b97e05591e9a39b6480c538b3

```go
package main

import (
	"log"
	"net"
	"os"

	"golang.org/x/crypto/ssh"
	"golang.org/x/crypto/ssh/agent"
)

func main() {
	socket := os.Getenv("SSH_AUTH_SOCK")
	conn, err := net.Dial("unix", socket)
	if err != nil {
		log.Fatalf("Failed to open SSH_AUTH_SOCK: %v", err)
	}

	agentClient := agent.NewClient(conn)

	signers, err := agentClient.Signers()
	if err != nil {
		log.Fatal(err)
	}
	
	println("signers", len(signers))
	
	config := &ssh.ClientConfig{
		User: "pe",
		Auth: []ssh.AuthMethod{
			ssh.PublicKeysCallback(agentClient.Signers),
		},
		HostKeyCallback: ssh.InsecureIgnoreHostKey(),
	}

	sshc, err := ssh.Dial("tcp", "10.85.5.198:22", config)
	if err != nil {
		log.Fatal(err)
	}

	sshc.Close()
}

```

`go run main.go`

Resulting with error:

```
signers 0
2023/09/19 18:01:26 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

Issue still persist with `v0.0.0-20220314234659-1baeb1ce4c0b` `crypto` package [^1].

Environment: `macOS 13.5.2, M1 Max, go1.21.1`

Could someone please confirm if this is a _known_ BUG?

/cc @FiloSottile @rolandshoemaker @golang/security per [owners](https://dev.golang.org/owners).

[^1]: https://github.com/golang/go/issues/54027#issuecomment-1420211355

**Comment by drakkan** [comment]
@Dentrax I think you are experiencing a different problem than initially reported.

@kt97679 @href @avron99 can you please try this [CL](https://go-review.googlesource.com/c/crypto/+/510155)? If it doesn't solve this issue as well, I'll take a closer look. Thank you

**Comment by hxlhxl** [comment]
after upgrade these two pkgs, It finally worked!


from

```go.mod
golang.org/x/crypto v0.0.0-20200208060501-ecb85df21340
	golang.org/x/sys v0.0.0-20200202164722-d101bd2416d5 // indirect
```

to

```
golang.org/x/crypto v0.14.0
golang.org/x/sys v0.13.0
```

**Comment by w11ch0** [comment]
> después de actualizar estos dos paquetes, ¡finalmente funciona!
> 
> De
> 
> ```
> golang.org/x/crypto v0.0.0-20200208060501-ecb85df21340
> golang.org/x/sys v0.0.0-20200202164722-d101bd2416d5 // indirect
> ```
> 
> Para
> 
> ```
> golang.org/x/crypto v0.14.0
> golang.org/x/sys v0.13.0
> ```

What are the commands to update it?

**Comment by drakkan** [comment]
> We're seeing the same issue and have bisected the cause back to the same commit as @kt97679 did [above](https://github.com/golang/go/issues/54027#issuecomment-1420211355).
> 
> @drakkan we tested your [linked CL](https://github.com/golang/go/issues/54027#issuecomment-1732573808) and confirmed it did not fix the error.

Hello,

the linked CL is included in v0.16.0. I used the test program provided and can't replicate the issue:

```
$ ssh-add -l
2048 SHA256:d0O4g73+vimS3esODdebewx7KlTw48PR7ZE9G2DbrU0 nicola@nicola-VirtualBox (RSA-CERT)
$ go run main.go 192.168.1.231:22
2023/12/08 10:28:48 Connecting to 192.168.1.231:22
2023/12/08 10:28:48 We've got a live session!
```

here is the go.mod

```
module 54027

go 1.21.5

require golang.org/x/crypto v0.16.0

require golang.org/x/sys v0.15.0 // indirect
```

If I set golang.org/x/crypto v0.15.0 in go.mod I can replicate the issue

```
$ go run main.go 192.168.1.231:22
2023/12/08 10:30:36 Connecting to 192.168.1.231:22
2023/12/08 10:30:36 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
exit status 1
```

so it seems fixed.

Please confirm that you are testing with x/crypto v0.16.0 and provide additional info if the issue is not fixed for you. Thank you

**Comment by stephenm-stripe** [comment]
@drakkan thanks for the follow up. We've done more digging an uncovered the root cause. I've opened an issue with more details in https://github.com/golang/go/issues/64785. The tl;dr is the remote server we're interacting with is not compliant with the RFC. The reason why we're able to bisect this error message back to the same commit as others is that the commit introduced the `ext-info-c` handling. With that new flow, we triggered the bad server behaviour based on the `server-sig-algs` response from the ext-info packet. As noted in my linked issue, OpenSSH handles this differently and without error. Commenting this here for others in case they encounter the same error, but otherwise, our issue is separate from the other comments above.

**Comment by madhaiyanmuthu** [comment]
> > después de actualizar estos dos paquetes, ¡finalmente funciona!
> > De
> > ```
> > golang.org/x/crypto v0.0.0-20200208060501-ecb85df21340
> > golang.org/x/sys v0.0.0-20200202164722-d101bd2416d5 // indirect
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Para
> > ```
> > golang.org/x/crypto v0.14.0
> > golang.org/x/sys v0.13.0
> > ```
> 
> What are the commands to update it?

please use the below commands:
```
    go get golang.org/x/sys 
    go get golang.org/x/crypt
    go mod tidy
``` 
if possible update go version to latest
