### ISSUE TITLE
affected/package: When I tried to crate new go file in vs code, I got problem without writing a single character in the file.

### ISSUE THREAD

**Issue by einfintie** [golang/go#54039]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.18.4
</pre>

### Does this issue reproduce with the latest release?

```Yes```

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env 
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\codz\AppData\Local\go-build
set GOENV=C:\Users\codz\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\codz\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\codz\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Program\Program-lang\GO
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Program\Program-lang\GO\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.4
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\codz\AppData\Local\Temp\go-build2596316587=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
```I'm a student of CS and I'm learning Go-lang because I think that this is modern C```

### What did you expect to see?
``` Expect to see clean window when create new file.```

### What did you see instead?

>(https://stackoverflow.com/q/73103858/19610721)

<details><summary>This is the error shown in problems section of VS Code</summary><br>
<pre>expected ';', found 'EOF'  syntax[Ln 1, Col 1] </pre>
<br><br>
<pre>
[{
	"resource": "/d:/VS-Codespace/C lang/new1.go",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "expected ';', found 'EOF'",
	"source": "syntax",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]
</pre></details>

**Comment by mengzhuo** [comment]
This is worked as intended, as spec requires a package clause.

https://go.dev/ref/spec#Source_file_organization

----
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
