### ISSUE TITLE
go compiler: internal compiler error: assertion failed

### ISSUE THREAD

**Issue by Primetalk** [golang/go#54046]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.18.4 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/user1/Library/Caches/go-build"
GOENV="/Users/user1/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/user1/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/user1/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.18.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.18.4/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/user1/Primetalk/goio/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0g/jh8kp3pn3mz52jzfyq8c5md80000gn/T/go-build522047264=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

<pre>
$ cd Primetalk
$ git clone git@github.com:Primetalk/goio.git
$ cd goio
$ go test ./...
# github.com/primetalk/goio/resource
resource/closable_io.go:13:62: internal compiler error: assertion failed

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
ok  	github.com/primetalk/goio/fun	0.368s
ok  	github.com/primetalk/goio/io	1.658s
ok  	github.com/primetalk/goio/option	0.211s
FAIL	github.com/primetalk/goio/resource [build failed]
ok  	github.com/primetalk/goio/slice	0.488s
ok  	github.com/primetalk/goio/stream	1.189s
FAIL	github.com/primetalk/goio/text [build failed]
FAIL
</pre>

### What did you expect to see?

<pre>
$ go1.18.1 test ./...
ok  	github.com/primetalk/goio/fun	0.401s
ok  	github.com/primetalk/goio/io	1.743s
ok  	github.com/primetalk/goio/option	0.684s
ok  	github.com/primetalk/goio/resource	0.846s
ok  	github.com/primetalk/goio/slice	0.278s
ok  	github.com/primetalk/goio/stream	1.118s
ok  	github.com/primetalk/goio/text	0.866s
</pre>

### What did you see instead?

<pre>
internal compiler error: assertion failed
</pre>

**Comment by cherrymui** [comment]
This looks like a dup of #53852 , and should be fixed by CL https://go.dev/cl/417615 . Thanks.
