### ISSUE TITLE
cmd/go: no error reported for duplicate module paths among modules in go.work

### ISSUE THREAD

**Issue by findleyr** [golang/go#54048]
Spin off from #53933, where gopls did not present a workspace error for a problematic `go.work` file because the `go` command was happy.

The go command does not return an error for duplicate module paths in a `go.work` file. Instead, it happily lets the last directory win:

```sh
$ ls -R
.:
go.work  mod1  mod2

./mod1:
a.go  go.mod

./mod2:
a.go  go.mod
$ cat go.work
go 1.19

use (
        ./mod1
        ./mod2
)
$ cat mod1/go.mod
module golang.org/foo

go 1.18
$ cat mod2/go.mod
module golang.org/foo

go 1.18
$ go list -m -json all
{
        "Path": "golang.org/foo",
        "Main": true,
        "Dir": "/home/rfindley/tmp/duplmodpath/mod2",
        "GoMod": "/home/rfindley/tmp/duplmodpath/mod2/go.mod",
        "GoVersion": "1.18"
}
```

CC @bcmills

**Comment by bcmills** [comment]
We do check that the same directory doesn't appear multiple times:
https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/modload/init.go;l=583-585;drc=86b5f6a7be707b9d84108df6f459c7e84bf9dbac

However, we haven't parsed the actual `go.mod` files at that point and can't check for duplicate `module` directives.
Probably the right place to do this check is in the `makeMainModules` helper-function here:
https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/modload/init.go;l=1011;drc=2ff563a00e45308fad74f1f86d816f4f636584a0

**Comment by ianwoolf** [comment]
i'm working on it. i will send a cl recently.

**Comment by ianwoolf** [comment]
please feel free to review, thanks
