### ISSUE TITLE
cmd/compile: ICE on embedded method expression with receiver parameter of derived type

### ISSUE THREAD

**Issue by mdempsky** [golang/go#54058]
This program is valid, but ICEs with the nounified frontend: https://go.dev/play/p/54ohNsbev55

It appears to be a bad interaction between method expressions, receiver parameters of derived type, and method embedding.

It currently works with GOEXPERIMENT=unified. Marking for Go 1.20, because I expect enabling unified IR by default is how we'll fix this issue.

/cc @golang/compiler

**Comment by cuonglm** [comment]
Unified IR is enabled now, this is fixed at tip.

Should we close this one?

@mdempsky @randall77

**Comment by mdempsky** [comment]
Yeah, this never worked, so no need for backports. There's a regress test for this in typeparam/mdempsky/20.go too.
