### ISSUE TITLE
x/tools/gopls: allow to clear upgrade check diagnostics

### ISSUE THREAD

**Issue by hyangah** [golang/go#54065]
"Check for upgrades", "Upgrade transitive dependencies", "Upgrade direct dependencies" codelenses in go.mod file provide convenient ways of checking available upgrades from time to time.

![Screen Shot 2022-07-26 at 10 50 40 AM](https://user-images.githubusercontent.com/4999471/181038358-ae9bee4d-1861-45f3-a2f4-7fbd25e15bb3.png)

However, often times, I want to stay with the current dependencies after selectively upgrading a couple of chosen modules.
Currently there is no convenient way to hide the diagnostics produced as a result of running one of these code lenses without upgrading the modules. (except restarting the language server)

It would be nice if there is a way to clear these diagnostics. 
One way to do it is to use the approach gc_details codelens uses (toggle).
Another way is to provide a separate codelens that disposes all the upgrade check diagnostics. (One concern is currently, there are too many codelenses :-))

**Comment by suzmue** [comment]
Another alternative is to add a command to clear the upgrade check diagnostics / all of the additional diagnostics that were added (vulnerability diagnostics, upgrade information, etc): `> Go: Reset go.mod Diagnostics`

This command can then be run to get rid of the diagnostics, but will not take the extra space of a codelens in the go.mod file.

cc @jamalc
