### ISSUE TITLE
go.dev site not working 

### ISSUE THREAD

**Issue by AdeboyeDN** [golang/go#54062]
![FireShot Capture 013 - go dev - go dev](https://user-images.githubusercontent.com/65312338/181004547-06ecfe3a-c029-49fb-9d3e-f4bb68192231.png)

My connection is strong and also i can access other site, i even tried other browsers still same error

**Comment by mvdan** [comment]
I see it working fine, and sites like https://downforeveryoneorjustme.com/go.dev confirm that. It sounds like your network isn't working particularly well - perhaps your internet provider is messing with the connection.
