### ISSUE TITLE
x/build/cmd/racebuild: apt-get update problems on linux gomotes

### ISSUE THREAD

**Issue by thanm** [golang/go#54070]
### What version of Go are you using (`go version`)?

Tip for Go, x/build

<pre>
$ go version
go version devel go1.19-c847a2c9f0 Fri Jul 1 01:36:45 2022 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

### What did you do?

Ran "racebuild" with tip Go and a recent LLVM commit, e.g. 

go build .
./racebuild   --goroot=/ssd2/ygo  --rev=b6374437af39af66896da74a1dc1b8a0ece26bee --gorev=3e97294663d978bf8abb7acec7cc615ef2f1ea75 
870 Steel Stock Rd, Clarksville, Tennessee 37040, United States
### What did you expect to see?

Successful run.

### What did you see instead?

Many of the linux-line systems targeted by racebuild run "apt" commands to download things like git onto the gomote, so as to use git to download the LLVM repo.  These apt commands, e.g. things like [this](https://go.googlesource.com/build/+/63ffb1768a62e897ca23fd7bc3ecbbc66902b9cb/cmd/racebuild/racebuild.go#161) seem to be failing. Here is an example from a linux-arm64 gomote:

```
$ apt-get update
Get:1 http://security.debian.org/debian-security buster/updates InRelease [73.5 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
Reading package lists...
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldstable-updates'
$ echo $?
100
$
```

Not sure exactly what the issue is here, but it is impacting the ability to update race builders for most of the supported architectures (windows is not impacted, but lots of other os/arch combinations are).

**Comment by thanm** [comment]
@golang/release

**Comment by cagedmantis** [comment]
The solution to this is updating our Debian builders more often. A quick fix may be to add the `--allow-releaseinfo-change` flag to the `apt-get update` command in racebuild.

**Comment by toothrot** [comment]
We should consider updating to bullseye (current stable), which is supported by the Debian Security Team (rather than the LTS team) in #40561

**Comment by cagedmantis** [comment]
I believe the builders in question have been updated to Debian Bullseye. Is there any additional work that needs to happen to close this issue?

**Comment by thanm** [comment]
No objections on my part.

**Comment by cagedmantis** [comment]
Thanks @thanm. Apologies for this taking a bit longer than anticipated.
