### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by baixiaoshi** [golang/go#54080]
### What version of Go are you using (`go version`)?

<pre>
go version go1.17.2 darwin/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="arm64"
GOBIN="/Users/lion/gopath/bin"
GOCACHE="/Users/lion/Library/Caches/go-build"
GOENV="/Users/lion/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/lion/gopath/pkg/mod"
GOOS="darwin"
GOPATH="/Users/lion/gopath"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Users/lion/src/go/go1.17.2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/lion/src/go/go1.17.2/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/lion/gopath/src/demo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/72/2splrvts5klbzkjrkdr71dcw0000gn/T/go-build3161908003=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

use nginx config proxy proto request golang tls server ,trigger error
<pre>
[ERR] Failed to read proxy prefix: tls: first record does not look like a TLS handshake
</pre>

golang source code

![image](https://user-images.githubusercontent.com/5595933/181146851-7a713021-f5a6-486d-81e0-a4f7ba4b1b1a.png)

it`s not support proxy protocol v1, it`s a bug? or not support this proxy protocol

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
