### ISSUE TITLE
x/pkgsite: package removal request for https://pkg.go.dev/github.com/inhoho/common_library

### ISSUE THREAD

**Issue by inhoho** [golang/go#54106]
### What is the path of the package that you would like to have removed?
https://pkg.go.dev/github.com/inhoho/common_library

 
 
 
### Are you the owner of this package?
yes

 
### What is the reason that you could not retract this package instead?
The repo was deleted.

**Comment by hyangah** [comment]
Have you tried to retract the module instead?
https://pkg.go.dev/about#removing-a-package

Just removing it from pkgsite won't affect proxy.golang.org, and it will be still accessible.
