### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by redstorm-fyy** [golang/go#54109]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
NO

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=off
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.4
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=F:\P4Nezha\Server\deploy\gs\go.mod
set GOWORK=F:\P4Nezha\Server\deploy\go.work
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build3046723960=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

My project is offline without the network.
Online libraries are copied to local directories.
I use go.work to point to the local directories.

First, I set the GOPROXY
go env -w GOPROXY=direct

Then I run two commands

go clean -modcache
go build .

The go build command blocked.

If the computer is connected to the network,  the go build command is OK. 
And in this case there is a  "pkg/mod/cache/download" directory in the modcache
If offline, and modcache is deleted, the go build blocked. 
I don't know why.

### What did you expect to see?
go build will not block

### What did you see instead?
 go build is blocked, and the cmmand is running forever.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by redstorm-fyy** [comment]
This is not a question. This bug is fixed by go1.18.5
