### ISSUE TITLE
affected/package: builtin Inlining causes spec violation in recover()

### ISSUE THREAD

**Issue by seunghyupoh3517** [golang/go#54119]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.18.4

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/seunghyupoh3517/.cache/go-build"
GOENV="/home/seunghyupoh3517/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/seunghyupoh3517/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/seunghyupoh3517/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/linuxbrew/.linuxbrew/Cellar/go/1.18.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/linuxbrew/.linuxbrew/Cellar/go/1.18.4/libexec/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc-5"
CXX="g++-5"
CGO_ENABLED="1"
GOMOD="/home/seunghyupoh3517/Work/FluxNinja/aperture/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2367899641=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```
func (r *PanicHandlerRegistry) Go(f func()) {
	go func() {
		debug.SetPanicOnFault(true)
		defer r.Recover()
		f()
	}()
}

func Go(f func()) {
       getPanicHandlerRegistry().Go()
}

func (r *PanicHandlerRegistry) Recover() {
	v := recover()
	if v != nil { ...
}

func Recover() {
        getPanicHandlerRegistry().Recover()
}
```

``` 
import (
  ph "..."
)

// Does recover
func main() {
      ph.Go(func() {
        panic("panic")
      })
}

// Does not recover
func main() {
      defer ph.Recover()
      panic("panic")
}
```

### What did you expect to see?
```
The return value of recover is nil if any of the following conditions holds:
    panic's argument was nil;
    the goroutine is not panicking;
    **recover was not called directly by a deferred function.**
```
According to the recover() spec, the third condition, the return value of recover in both cases should be nil and not recovered. 

### What did you see instead?
The first case where has `Go.func()..` recovers from the panic and returns the value and the second case does not recover and return nil.

Note:
It seems that the go compiler is doing inline functions when those are in the same file so `r.Recover()` gets expanded locally and it gets the error value passed to the call of panic from recover and recovers. Maybe some other optimization is making it work.

**Comment by ianlancetaylor** [comment]
Here the deferred function is `r.Recover`.  The call to `recover` occurs inside that deferred function, so I would expect it to recover the panic.

**Comment by seunghyupoh3517** [comment]
@ianlancetaylor Thanks for the quick response! I have added two small examples where it breaks in our project. This inconsistent behavior occurs numerous places in our project - could you please take a look?

**Comment by randall77** [comment]
I don't see a bug here. In the first case, you're deferring `(*PanicHandlerRegistry) Recover`, and that function calls `recover`. `recover` was called directly by the deferred function.

**Comment by seunghyupoh3517** [comment]
@randall77 Thanks for the reply! Then how is the second case considered as 'not directly called by the deffered function'?

**Comment by cherrymui** [comment]
Agree with @ianlancetaylor and @randall77 that this works as intended.

For your second case, the deferred function `ph.Recover`  does not  _directly_ call `recover`, but indirectly via `(*PanicHandlerRegistry).Recover`, so it does not recover the panic.

In general, we don't really use our issue tracker for questions. It would be better if you ask on a forum rather than on the issue tracker. See https://golang.org/wiki/Questions  . Thanks.
