### ISSUE TITLE
affected/package: fmt.println

### ISSUE THREAD

**Issue by leiqiang** [golang/go#54117]
### What version of Go are you using (`go version`)?

<pre>
go version go1.18.4 windows/amd64

</pre>

i don't know 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\MyClary\AppData\Local\go-build
set GOENV=C:\Users\MyClary\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=E:\GO\fish\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\GO\fish
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Program Files\Go
set GOSUMDB=sum.golang.google.cn
set GOTMPDIR=
set GOTOOLDIR=D:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.4
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\WINDOWS\TEMP\go-build3139600615=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

func main() {

	var c chan int = make(chan int)

	go fmt.Println(<-c)

	c <- 1

	var s string

	fmt.Scanln(&s)

}

fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
main.main()
        E:/GO/fish/src/main.go:11 +0x3e

### What did you expect to see?

the code is running right

### What did you see instead?

func main() {

	var c chan int = make(chan int)

	go func() {fmt.Println(<-c)}()

	c <- 1

	var s string

	fmt.Scanln(&s)

}

the code is right but why?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
