### ISSUE TITLE
x/sys/unix: on FreeBSD PtraceLwpInfoStruct, PtraceIoDesc and PtraceIO all can not be used safely

### ISSUE THREAD

**Issue by aarzilli** [golang/go#54113]
These all represent tracee addresses as `*byte` which makes `-d=checkptr` fail and the GC occasionally barf.

**Comment by cherrymui** [comment]
cc  @ianlancetaylor @bradfitz @tklauser @golang/runtime

**Comment by bcmills** [comment]
(CC @golang/freebsd)

**Comment by hyangah** [comment]
Based on the new port policy, cl/419915 needs reviews from @golang/freebsd
