### ISSUE TITLE
cmd/test: Generic not declared by package when testing with GOEXPERIMENT=unified 

### ISSUE THREAD

**Issue by phemmer** [golang/go#54112]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="linux"
</pre></details>

#### `local/test/main.go`
```
package main

import (
	"fmt"

	"local/test/mypkg"
)

func main() {
	var mg *mypkg.MyGeneric[struct{}]
	fmt.Printf("%v\n", mg)
}
```

#### `local/test/go.mod`
```
module test

go 1.18

require local/test/mypkg v0.0.0

replace local/test/mypkg => ./mypkg
```

#### `local/test/mypkg/mypkg.go`
```
package mypkg

type MyGeneric[T any] struct{}
```
#### `local/test/mypkg/go.mod`
```
module mypkg

go 1.18
```

#### Command

```
$ GOEXPERIMENT=unified go test -v .
```

### What did you expect to see?
```
?   	test	[no test files]
```

(or a successful test if test files are present)

### What did you see instead?
```
# test
vet: ./main.go:10:16: MyGeneric not declared by package mypkg
```

### Additional information
Note that `GOEXPERIMENT=unified go build .` works perfectly fine.

I have to use `GOEXPERIMENT=unified` due to #53419

**Comment by cherrymui** [comment]
The fix of #53419 is included in Go 1.18.4. So you shouldn't need to use `GOEXPERIMENT=unified` anymore. Also `GOEXPERIMENT=unified` is an in-progress developmental work, and not a supported feature. Thanks.
