### ISSUE TITLE
Go program hangs up indefinitely with Go modules enabled 

### ISSUE THREAD

**Issue by esimov** [golang/go#54123]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.4 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/esimo/.cache/go-build"
GOENV="/home/esimo/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/esimo/projects/Go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/esimo/projects/Go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/esimo/projects/Go/src/esimov/pigo/go.mod"
GOWORK="/home/esimo/projects/Go/src/esimov/go.work"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you do?
I'm running Go under Linux through WSL and after some changes done in the project directory with the Go modules enabled each time when I'm trying to run a go program it hangs up indefinitely. I also have Go installed on Windows and this issue is not happening here. I found this [SO thread](https://stackoverflow.com/questions/37033541/go-command-hangs-indefinitely) resembling the same issue I'm facing right now. After restarting WSL it used to work at the first time, but it's not working anymore. If I'm disabling `GO111MODULE` it's working. I'm running out of ideas what could be wrong.

### Update:

One interesting situation I found: I have another project directory on the Windows environment. As you might know under WSL, the Windows file system can be accessed from the `/mnt` folder. In my case the Go projects folder can be access under the following path: `/mnt/c/Users/esimo/Projects/Go/src/github.com/esimov`.  On Linux the Go projects folder is a bit different: `/home/esimo/projects/Go/src/esimov`. Now with go mod enabled in case if I'm removing the `go.work` file from the projects root directory the go command is working, otherwise the go command hangs up. I tried to replicate the same situation on the Linux environment, but even if the `go.work` file is present it's still not working.

I'm showing the go.work files:

**Windows**:
```bash
go 1.18

use (
        ../egonelbre/expgio
        ./ascii-fluid
        ./ascii-fluid/vendor/github.com/gorilla/websocket
        ./ascii-fluid/vendor/github.com/mattn/go-runewidth
        ./caire
        ./colidr
        ./colidr/vendor/gocv.io/x/gocv
        ./colorquant
        ./diagram
        ./diagram/vendor/github.com/google/gxui
        ./dithergo
        ./expgio
        ./expgio/f32color
        ./facemask
        ./forensic
        ./go-concurrency
        ./go-generics
        ./legoizer
        ./legoizer/vendor/github.com/lucasb-eyer/go-colorful
        ./pigo
        ./pigo-face-tracking
        ./pigo-face-tracking/vendor/github.com/gorilla/websocket
        ./pigo-openfaas-faceblur/build/pigo-faceblur/function
        ./pigo-openfaas-faceblur/pigo-openfaas-faceblur
        ./pigo-wasm-demos
        ./pigo/vendor/github.com/disintegration/imaging
        ./pigo/vendor/golang.org/x/term
        ./stackblur-go
        ./talks
        ./triangle
        ./triangle-app/server
        ./triangle-app/server/vendor/github.com/esimov/triangle
        ./triangle-app/server/vendor/github.com/gorilla/mux
)
```
Linux:
```bash
go 1.18

use (
        ../dominikh/gotraceui
        ../xyproto/o/v2
        ./ascii-fluid
        ./ascii-fluid/vendor/github.com/gorilla/websocket
        ./ascii-fluid/vendor/github.com/mattn/go-runewidth
        ./caire
        ./colidr
        ./colidr/vendor/gocv.io/x/gocv
        ./colorquant
        ./diagram
        ./diagram/vendor/github.com/google/gxui
        ./dithergo
        ./facemask
        ./forensic
        ./go-concurrency
        ./go-generics
        ./legoizer
        ./legoizer/vendor/github.com/lucasb-eyer/go-colorful
        ./pigo
        ./pigo-face-tracking
        ./pigo-face-tracking/vendor/github.com/gorilla/websocket
        ./pigo-openfaas-faceblur/build/pigo-faceblur/function
        ./pigo-openfaas-faceblur/pigo-openfaas-faceblur
        ./pigo-wasm-demos
        ./pigo/vendor/github.com/disintegration/imaging
        ./pigo/vendor/golang.org/x/term
        ./stackblur-go
        ./talks
        ./triangle
        ./triangle-app/server
        ./triangle-app/server/vendor/github.com/esimov/triangle
        ./triangle-app/server/vendor/github.com/gorilla/mux
)
```
I don't see any significant differences in terms of structure.

**Comment by seankhliao** [comment]
try `-v -x`

**Comment by esimov** [comment]
@seankhliao I don't understand.

**Comment by bcmills** [comment]
@esimov, this issue needs more detail to be actionable.
* What specific commands did you run?
* When you pass `-x` to those commands, what additional output do you get?
* Did you try sending `SIGQUIT` to the stuck command? (A goroutine dump would be helpful.)
* Do `pstree` and/or `top` show anything interesting running at the time?
* How do you have WSL configured? (Is `/home/esimo` a native Linux filesystem, or is it mounted on a Windows filesystem? IIRC WSL cross-platform file operations are still extremely slow.)

**Comment by esimov** [comment]
@bcmills I have updated the issue description.
> How do you have WSL configured?

`/home/esimo` is a native Linux filesystem

The interesting thing is that before making the above mentioned changes, the whole system was working perfectly and unfortunately I'm unable to understand what can be wrong that any `go run` command I'm trying hangs up indefinitely with go mod enabled.

**Comment by esimov** [comment]
I have upgraded to go1.18.5 and it looks like that the issue is not reproducing anymore. I'm not really sure what could've be wrong, but I haven't done anything else then upgrading to the latest release and updating the environment variables. The issue is not reproducing on the Windows environment too.
