### ISSUE TITLE
generic type is not working properly when compared to nil

### ISSUE THREAD

**Issue by schweigert** [golang/go#54122]
### What version of Go are you using (`go version`)?

<pre>
$ go version

1.18.4

</pre>

### Does this issue reproduce with the latest release?

code that works:

```golang
package gspec

type nilMatcher[T any] struct{}

func (it nilMatcher[T]) Match(value T, path string) error {
	if it.isNil(value) {
		return nil
	}

	return fmt.Errorf("%s should be nil [%s]", ReferValue(value), path)
}

func (it nilMatcher[T]) isNil(value any) bool {
	return value == nil
}
```

Code that should work, as T is any just like the argument

```golang
package gspec

type nilMatcher[T any] struct{}

func (it nilMatcher[T]) Match(value T, path string) error {
        // Error comparing T with nil. But in the previous case, using any as the argument type directly worked.
	if value == nil {
		return nil
	}

	return fmt.Errorf("%s should be nil [%s]", ReferValue(value), path)
}
```

The code I'm trying to write is in this open source package: https://github.com/krakenland/gspec

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by ianlancetaylor** [comment]
See the discussion at https://go.dev/doc/faq#nil_error.
