### ISSUE TITLE
mime/multipart: wrong error wrapping in multipart.go on L346?

### ISSUE THREAD

**Issue by pH-T** [golang/go#54133]
### What version of Go are you using (`go version`)?
go1.18.3 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What did you do?
tried to catch errors with `errors.Is(err, io.EOF)` from `multipart.NewReader(...)..NextPart()`

### What did you expect to see?
expected to catch io.EOF errors, but it seems to only work if we enter the `if` in [L337](https://github.com/golang/go/blob/go1.18.3/src/mime/multipart/multipart.go#L337) - io.EOF is directly returned.

### What did you see instead?
`multipart: NextPart: EOF` --> wrongly (?) wrapped error

changing`%v` to `%w` in [L346](https://github.com/golang/go/blob/go1.18.3/src/mime/multipart/multipart.go#L346) fixed this issue - so most likely a bug?

**Comment by cherrymui** [comment]
Do you have a code example that doesn't work as expected? Thanks.

**Comment by pH-T** [comment]
hi @cherrymui, 
thanks for your fast response!

here is a code example: https://go.dev/play/p/BfjeTIOkq-M

**Comment by seankhliao** [comment]
From the definition of `io.EOF`: 

> Functions should return EOF only to signal a graceful end of input. If the EOF occurs unexpectedly in a structured data stream, the appropriate error is either ErrUnexpectedEOF or some other error giving more detail.

This is an unexpected end of input, so the error is correct.

**Comment by pH-T** [comment]
hi @seankhliao,
indeed the error itself is correct - I never said something different!
Im pretty sure that the "wrapping" in [L346](https://github.com/golang/go/blob/go1.18.3/src/mime/multipart/multipart.go#L346) is wrong! By returning the io.EOF with "%v" it is not wrapped and thus not useable with `errors.Is()`.
By replaceing the "%v" with a "%w" it works as expected...
So its not about the error itself!

**Comment by seankhliao** [comment]
but allowing you to test against EOF is wrong, since EOF represents a clean exit, and this is not

**Comment by pH-T** [comment]
hi @seankhliao,
the following code is used in `mime/multipart/multipart.go#L346`:
```
...
		if err != nil {
			return nil, fmt.Errorf("multipart: NextPart: %v", err)
		}
...
```

by using "%v" the caller can not check the error and it does not have to be an io.EOF error - it could be any error...
so the caller just sees the error but is not able to check what kind of error it is! 

further I do not understand what you mean by "but allowing you to test against EOF is wrong, since EOF represents a clean exit, and this is not" - you should be allowed to test against any error (error wrapping - https://pkg.go.dev/errors) but thats a different topic...
