### ISSUE TITLE
x/pkgsite: package removal request for [type path here]

### ISSUE THREAD

**Issue by fieldju** [golang/go#54131]
### What is the path of the package that you would like to have removed?

https://github.com/armory-io/go-commons version >= 1.0.0

 
 
 
### Are you the owner of this package?

Yes

 
### What is the reason that you could not retract this package instead?

We accidentally released 1.0.0 yesterday and want to be able to publish 1.0.0 when the package is stable.
I don't think the proxy has cached any of the 1.0.0 versions but the doc site has (when I use `go get github.com/armory-io/go-commons` it doesn't install 1.+).

**Comment by seankhliao** [comment]
it's already there https://proxy.golang.org/github.com/armory-io/go-commons/@v/list

There are no actions we can take that will allow you to redefine what v1.0.0 points to.
