### ISSUE TITLE
image/png: invalid format: chunk out of order

### ISSUE THREAD

**Issue by kmicki** [golang/go#54142]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/deck/.cache/go-build"
GOENV="/home/deck/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/deck/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/deck/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3730379239=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Try to decode e.g. [this file](https://cdn2.steamgriddb.com/file/sgdb-cdn/grid/085c11a3f81d28b2f3ac128aa9565d1a.png) with png.Decode().

### What did you expect to see?

No error and decoded image.

### What did you see instead?

*invalid format: chunk out of order*

### What I think is the cause

It looks like the problem is [here](https://github.com/golang/go/blob/9a2001a8cc75b1ceda17da828edcee93c9d9f42c/src/image/png/reader.go#L896-L905).

This code expects that PLTE chunk is present only for Color type = 3 (Paletted). If it is present for other types, the mentioned error is thrown.

According to [PNG specification](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html#C.PLTE), PLTE chunk may appear also for types 2 or 6. The PNG file linked above is type 2 and contains PLTE chunk, so it is compliant with PNG specs.

**Comment by seankhliao** [comment]
cc @nigeltao
