### ISSUE TITLE
encoding/binary: Uvarint and ReadUvarint are no longer consistent

### ISSUE THREAD

**Issue by dsnet** [golang/go#54146]
Ever since `ReadUvarint` was modified in #41185 to limit reading to only 10 bytes, this made it such that `Uvarint` and `ReadUvarint` disagree about the definition of a varint. We should put the 10-byte limit in Uvarint as well and treat it as an overflow condition. This can occur for denormalized varints where a small integer uses more bytes to encode than necessary.

For comparison, `protowire.ConsumeVarint` holds to the stricter definition of a varint where it only handles up to 10 bytes and then treats [any additional bytes as an overflow condition](https://github.com/protocolbuffers/protobuf-go/blob/6875c3d7242d1a3db910ce8a504f124cb840c23a/encoding/protowire/wire.go#L370).

**Comment by ulikunitz** [comment]
Uvarint in 1.18.5 handles MaxVarintLen64=10. Do you have an example showing different behavior of ReadUvarint and Uvarint?

**Comment by dsnet** [comment]
Ah my mistake. I must have been reading an older version of the code. I see the check there.
