### ISSUE TITLE
golang.org/x/net v0.0.0-20210525063256-abc453219eb5

### ISSUE THREAD

**Issue by bihailong** [golang/go#54145]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
the version from "golang.org/x/net v0.0.0-20201110031124-69a78807bb2b" to "golang.org/x/net v0.0.0-20210525063256-abc453219eb5"

### What operating system and processor architecture are you using (`go env`)?
Linux version 4.4.180-1.el6.elrepo.x86_64 (mockbuild@Build64R6) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC) ) #1 SMP Thu May 16 16:37:14 EDT 2019
CentOS release 6.9 (Final)

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/bihailong/.cache/go-build"
GOENV="/home/bihailong/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/bihailong/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build816801613=/tmp/go-build"
</pre></details>

### What did you do?
the version from "golang.org/x/net v0.0.0-20201110031124-69a78807bb2b" to "golang.org/x/net v0.0.0-20210525063256-abc453219eb5"

### What did you see instead?
![image](https://user-images.githubusercontent.com/10085581/181924613-53b26272-9b03-43d3-98f6-f185a06dc991.png)

**Comment by bihailong** [comment]
Generate a core,It should be a bug.

**Comment by bihailong** [comment]
![image](https://user-images.githubusercontent.com/10085581/181924710-fb65bc92-f1ac-4980-a5e6-9d936365483d.png)

**Comment by seankhliao** [comment]
please fill out the issue template.

**Comment by bihailong** [comment]
> please fill out the issue template.

fill done.

**Comment by seankhliao** [comment]
Go 1.14 is no longer supported.
The latest versions of x/net are from 20220728
