### ISSUE TITLE
net/http: Server.IdleTimeout not worked as expected

### ISSUE THREAD

**Issue by ray2011** [golang/go#54140]
### What version of Go are you using (`go version`)?

<pre>
go version go1.18.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/raynor/.cache/go-build"
GOENV="/home/raynor/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/raynor/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/raynor/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/raynor/sdk/go1.18.3"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/raynor/sdk/go1.18.3/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="/usr/bin/gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK="/home/raynor/iGame/go.work"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build800292898=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
set http.Server.IdleTimeout to 30s

### What did you expect to see?
A idle conn is closed after 30s

### What did you see instead?
The idle conn is closed after 10s

The detail is in https://github.com/pyroscope-io/client/issues/18

**Comment by seankhliao** [comment]
Looks like it's working as expected
