### ISSUE TITLE
runtime: TestCgoCrashHandler and TestCgoSignalDeadlock compilation failure on openbsd/amd64

### ISSUE THREAD

**Issue by gopherbot** [golang/go#5415]
by **raul.san@sent.com**:

<pre>I compiled Go in OpenBSD 5.3 for arch. 386 with `ulimit -d 2036792; ulimit -p 512` and
it worked ok, but it fails in amd64.

ok      regexp/syntax   0.828s
--- FAIL: TestCgoCrashHandler (0.83 seconds)
        crash_test.go:78: expected &quot;main: recovered done\nnew-thread: recovered done\nsecond-new-thread: recovered done\nmain-again: recovered done\n&quot;, but got &quot;# command-line-arguments\n/usr/bin/ld: /var/tmp/go-link-uH0FNo/go.o: relocation R_X86_64_32 can not be used when making a shared object; recompile with -fPIC\n/var/tmp/go-link-uH0FNo/go.o: could not read symbols: Bad value\ncollect2: ld returned 1 exit status\n/usr/local/go/pkg/tool/openbsd_amd64/6l: running gcc failed: unsuccessful exit status 0x100\n&quot;
--- FAIL: TestCgoSignalDeadlock (0.56 seconds)
        crash_cgo_test.go:21: expected &quot;OK\n&quot;, but got &quot;# command-line-arguments\n/usr/bin/ld: /var/tmp/go-link-73A0Ps/go.o: relocation R_X86_64_32 can not be used when making a shared object; recompile with -fPIC\n/var/tmp/go-link-73A0Ps/go.o: could not read symbols: Bad value\ncollect2: ld returned 1 exit status\n/usr/local/go/pkg/tool/openbsd_amd64/6l: running gcc failed: unsuccessful exit status 0x100\n&quot;
FAIL</pre>

**Comment by 4a6f656c** [comment]
This was fixed in #5067.
