### ISSUE TITLE
syscall: Missing open flags for AMD64

### ISSUE THREAD

**Issue by AlonZivony** [golang/go#54167]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
</pre></details>

### What did you do?

I want to use `syscall.openat`, so I want to open a directory using `syscall.open` using the `O_PATH` flag.
However, it seems that it is not defined in the `syscall` library.
I have seen that other architectures have this flag in their source code, but for some reason it is missing for normal AMD64.
Might be that other flags are missing too (didn't check).

**Comment by jacobishao** [comment]
@AlonZivony if you the syscall.O_PATH flag, can you compile your program?

**Comment by seankhliao** [comment]
syscall is frozen, use golang.org/x/sys/unix

**Comment by AlonZivony** [comment]
Thanks @seankhliao!
