### ISSUE TITLE
Unexpected type assertion

### ISSUE THREAD

**Issue by CarstenLeue** [golang/go#54166]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

```go
package weird

import "fmt"

type Weird[A any] interface {
	fmt.Stringer
}

type weird struct {
}

func (weird) String() string {
	return "Weird"
}

func MakeWeird[A any]() Weird[A] {
	return weird{}
}

func IsWeird[A any](data Weird[A]) bool {
	switch data.(type) {
	case weird:
		return true
	default:
		return false
	}
}
```

then print 

```go
fmt.Println(W.IsWeird(W.MakeWeird[int]()))
```

https://go.dev/play/p/CGZnDAyFB8y

### What did you expect to see?

I would have expected to see `true`

### What did you see instead?

The output is false

**Comment by mvdan** [comment]
See https://github.com/golang/go/issues/45380#issuecomment-1014950980.

Also, the Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
